### ISSUE TITLE
Post-installation messages can't be hidden. Regression?

### ISSUE THREAD

**Issue by smz** [joomla/joomla-cms#10006]
#### Steps to reproduce the issue

- Perform fresh Joomla installation from current staging
- Login as administrator
- Try to hide Post-installation messages

#### Expected result
Post-installation messages being hidden

#### Actual result
Post-installation messages **can't** be hidden

#### System information (as much as possible)
Win 8.1, PHP 5.6.18, MySQL 5.6.28, Joomla "staging"  (_HEAD at #9c5ab09_)

#### Additional comments
Performed fresh install two times in a raw, always with empty DB.
In both cases I installed multilingual (en-GB + it-IT) with sample data.
Same result in both cases.

**Comment by brianteeman** [comment]
Tested current staging with both english and italian and can not confirm this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10006">issues.joomla.org/joomla-cms/10006</a>.</sub>

**Comment by MATsxm** [comment]
Same as @brianteeman not able to reproduce

**Comment by smz** [comment]
Sorry guys, must be a glitch here...
Closing (will reopen in case it persist...)

**Comment by smz** [comment]
Sorry, but I'm still experiencing this **if I install multilingual**: no problem if installing en-GB **only** :confused: 

Just to be sure, are you using a similar environment (_OS, PHP, etc._)?

**Comment by smz** [comment]
(and apparently there is another unrelated issue: while installing I get errors if I didn't had previously wiped out my DB and try to rely on the installation "Drop" feature..)

**Comment by smz** [comment]
Nope: re-installed MySQL from scratch and both problems disappeared. Local issue. Sorry for the inconvenience.

**Comment by brianteeman** [comment]
As I stated I did a test multilingual install.

**Comment by smz** [comment]
> As I stated I did a test multilingual install.

I know. My question was about **environment** (_OS, PHP, etc._), but anyway the issue was a local one, as I stated.
