### ISSUE TITLE
Drop up for list formfields modified with the chosen.jquery

### ISSUE THREAD

**Issue by schnuti** [joomla/joomla-cms#10001]
The problem is most obvious if you have one or more selectlists at the bottom in modals. On normal pages you probably do not have select lists at the bottom. Maybe though a meny with submenus.

Bootstrap dropdowns change to dropups automaticly. If chosen.jquery is loaded, this functionality is missing. If it's loaded, it changes all select fields on the page and you can't prevent it, as far as I know.
[harvesthq issue since 2011](https://github.com/harvesthq/chosen/issues/155) It looks that it'll take some time to get a solution from that side.

I found a manual solution and ask if 3 rows CSS should be added to the chosen.css or somehere else?

`
.chzn-drop-up ~ div .chzn-drop{
   top: auto;
   bottom: 100%;
 }
 `

Then you can add the chzn-drop-up class to the listfield in your form xml file.

This works for me, the list appears above the field and the style is ok for me. 

Edit:
How to test to see the effect. In real the problem only appears if the select is at the bottom. 
This is probably easier than to use a PR with the Patch-Tester as only the CSS would change..

1. Add the above CSS code to chosen.css in /media/jui/css.
2. Open the article.xml in /administrator/omponents/com_content/models/forms.
3. Look for field name access
4. Add the attribute class="chzn-drop-up"   
5. Be sure that your browser hasn't cached the choosen.css
6. Go to article creation in backend.
7. Click on Access and this should show a "drop up"
8. Click on the other fields to the right and they show a drop down.

That's the effect.

You can test the same in frontend. Edit then the article.xml in the frontend path. You can see the frontend problem below.

**Comment by schnuti** [comment]
I added test instructions above.
I did not make a PR for the CSS, as I don't know if the chosen.css is a 1 to 1 copy from the vendor. If so it may complicate things with Joomla specific code inside it.
A quick test is possible without it as described.

**Comment by brianteeman** [comment]
It is not a 1 to 1 copy of the chosen.css as I can see it has been edited in the past - not sure that was a good idea though

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10001">issues.joomla.org/joomla-cms/10001</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Issue is same on 3.7.staging.
