### ISSUE TITLE
Languages content access level

### ISSUE THREAD

**Issue by bgvsan** [joomla/joomla-cms#10019]
#### Steps to reproduce the issue
Install languages and configure a multi language site, enable System - Language Filter plugin
#### Expected result

Show all the language published

#### Actual result

The language module doesn't show any of the language published, if I change in contents languages the level access (from public to guest or vice versa) the list in the dropdown appear, or the flags are shown, after selecting one language the site looks like is looping at the address mysite/en-gb/ 

#### System information (as much as possible)

Joomla! 3.4.8 Stable

#### Additional comments
created also 3 menu, one for italian language, 1 for english,, 1 for all, the flags are displayed in the administration menu and the Multilanguage Status confirm the languages correctly installed

**Comment by brianteeman** [comment]
Please update to the current support release 3.5.1 and report back<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10019">issues.joomla.org/joomla-cms/10019</a>.</sub>

**Comment by bgvsan** [comment]
same issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10019">issues.joomla.org/joomla-cms/10019</a>.</sub>

**Comment by brianteeman** [comment]
Please post a screenshot of the Multilingual Status module<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10019">issues.joomla.org/joomla-cms/10019</a>.</sub>

**Comment by Bakual** [comment]
Sounds like the issue we fixed with 3.4.1 and where there is a postinstall message for exactly that issue.
If you updated from an earlier version, you need to save the content languages once so they get a proper access value assigned.
Check you postinstall messages, there should be a message saying exactly this:
> `You have possible issues with your multilingual settings`
> `Since Joomla! 3.4.0 you may have issues with the System - Language Filter plugin on your web site. To fix them please open the Language Manager and save each content language manually to make sure an Access level is saved.`

**Comment by bgvsan** [comment]
saved again all the language but same issue.
![screen shot 2016-04-21 at 13 29 53](https://issues.joomla.org/uploads/1/946216ede1667078f3eb8c1a00a4a38f.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10019">issues.joomla.org/joomla-cms/10019</a>.</sub>

**Comment by bgvsan** [comment]
i have checked no post install message<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10019">issues.joomla.org/joomla-cms/10019</a>.</sub>

**Comment by infograf768** [comment]
I guess you should rather ask for help on the forums as one needs access to your site to see what is wrong.

**Comment by bgvsan** [comment]
ok, my first though was to post on forum, but with an issue on the registration captcha a was unable to register :(

the second bad thingh is that on (contact an amministrator) there is a link to a no reply address.

this morning seems to be fixed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10019">issues.joomla.org/joomla-cms/10019</a>.</sub>

**Comment by brianteeman** [comment]
Closed as the forum is the best place for this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10019">issues.joomla.org/joomla-cms/10019</a>.</sub>
