### ISSUE TITLE
Suffix to URL Causing Invalid Security Token

### ISSUE THREAD

**Issue by rociopts** [joomla/joomla-cms#10010]
#### Steps to reproduce the issue
Enable Suffix to URL then go to frontend login 

#### Expected result
For user to login via the frontend

#### Actual result
Invalid Security Token Error

#### System information (as much as possible)
Noticed issue after Update 3.5

#### Additional comments
I can properly login and make changes only if  the suffix is removed from links but this defeats the purpose of enabling Suffix to URL.

**Comment by mbabker** [comment]
Can't confirm.  Frontend login works just fine on www.joomla.org and developer.joomla.org.

**Comment by brianteeman** [comment]
I am unable to replicate this.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10010">issues.joomla.org/joomla-cms/10010</a>.</sub>

**Comment by richard67** [comment]
Me neither.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10010">issues.joomla.org/joomla-cms/10010</a>.</sub>

**Comment by brianteeman** [comment]
@rociopts as no one can replicate this then the problem you are facing must be something specific to your site and not a general issue with joomla. Please use the forum for support http://forum.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10010">issues.joomla.org/joomla-cms/10010</a>.</sub>

**Comment by izima97** [comment]
I have this issue after upgrade to 3.6.4. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10010">issues.joomla.org/tracker/joomla-cms/10010</a>.</sub>
