### ISSUE TITLE
Unable to logout from admin when using mobile device

### ISSUE THREAD

**Issue by Doomfinger** [joomla/joomla-cms#10027]
#### Steps to reproduce the issue
Using a windows mobile phone running windows 8.1. Log in to Administrator, perform tasks and then attempt to logout.

#### Expected result
Return to Admin login splash screen.

#### Actual result
Returns to control panel or last page viewed.

#### System information (as much as possible)
Server PC:- Windows PC running Windows 10 64bit,
Server Programme:- Abyss X2.
Mobile phone:- Nokia Lumia 635.
Network:- Not via mobile network, used via local router.

#### Additional comments
This method of access is not recommended except for emergency patches due to the inherent limitations of the mobile phone.

**Comment by brianteeman** [comment]
@bakual you are the only windows mobile user I know

**Comment by Bakual** [comment]
@brianteeman Unfortunately (or fortunately?) I use now an Android as well :smile:

**Comment by brianteeman** [comment]
Lol

**Comment by Doomfinger** [comment]
Yes, not the recommended way of addressing Joomla and I do not intend to use it again but in my case it was to correct a niggling typo. However the problem still stands.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10027">issues.joomla.org/joomla-cms/10027</a>.</sub>

**Comment by brianteeman** [comment]
Just need to find a developer who has a windows mobile phone so we can
review the issue and create a solution

**Comment by zero-24** [comment]
@brianteeman if we have wifi in manchester i can help with my WindowsPhone for testing ;)

Also navigating the backend e.g. components etc don't work for my Lumia 630 & Win 8.1 ;)

**Comment by zero-24** [comment]
But i have no idea what the problem could be.

**Comment by brianteeman** [comment]
great - of course we have wifi ;)

On 22 April 2016 at 14:33, zero-24 <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> if we have wifi in
> manchester i can help with my WindowsPhone for testing ;)
>
> Also navigating the backend e.g. components etc don't work for my Lumia
> 630 & Win 8.1 ;)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10027#issuecomment-213429863>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by pe7er** [comment]
Thank you for reporting this issue @Doomfinger
We've reproduced the error on a Windows Phone with 8.1.
This is a known issue which cannot be solved in this version of Joomla.

**Comment by brianteeman** [comment]
closed
