### ISSUE TITLE
Bug in Calendar form field, week

### ISSUE THREAD

**Issue by schnuti** [joomla/joomla-cms#10038]
#### Steps to reproduce the issue
Click on a "date" field in a form. 
1. You'll see a week number that is wrong.
2. The first day of the week is a sunday. 

#### Expected result
1. A correct week. I have week 16 today the popup says 15.  
You can do some calculations on [timeanddate.com](http://www.timeanddate.com/date/weeknumber.html)
2. Is a bug for a lot of users living in countries following international satandards ISO 8601 where monday is the first day of the week. If it's not configurable the ISO standard should be followed.

You get the expected results with the php-object DateTime(). I've tested.

#### System information (as much as possible)
Joomla 3.5.1
PHP  7.0.4

#### Additional comments
It's better to remove the week from the popup than show a false one. This can be done by changing a js setting. I wanted to use the calandar to help the user find a week number - not possble,

I also tried to modify the setting for the first week day but it seems not to work.

I tried to use a template override for the isis template but the javascript code didn't load for some reason?

I'm not fit enough to make a PR with javascript.

**Comment by brianteeman** [comment]
In the xml file for your language is a field
/<firstday> where you can define if a week starts on a sunday or monday

Does this resolve your problem?

**Comment by brianteeman** [comment]
oops looks like the name of the field was swallowed by github
it is < weekday ><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10038">issues.joomla.org/joomla-cms/10038</a>.</sub>

**Comment by schnuti** [comment]
Thanks a lot, changing language solved both week and date.
The other language has <firstDay> set to 1 in the xml.
I normaly work in English on backend for wich I get it as described above.

Are you a week behind?

Please close the issue!

**Comment by schnuti** [comment]
Me too. Tag disappear.

Tag is firstDay

**Comment by brianteeman** [comment]
Closing - its weird that the week starts on different days in different places

**Comment by schnuti** [comment]
@brianteeman 
Yes that's weird with the day but more problems with the week.
If I have a delivery in week 17 I have only a few days left. You have more than a week.
Is this true? It's really up to misunderstandings between producer and customer.

**Comment by brianteeman** [comment]
Not all parts of the world consider the week to begin with Monday. For example, in some Muslim countries, the normal work week begins on Saturday, while in Israel it begins on Sunday. In the US, although the work week is usually defined to start on Monday, the week itself is often considered to start on Sunday.

**Comment by schnuti** [comment]
@brianteeman 
I know and knew about the differences to the start of the week.
I see the problem with the **WEEK-NUMBER** that you might promise a delivery in week 16, i.e. this week for me and next week for you.

**Comment by brianteeman** [comment]
Yeah it's a pain. In the UK we even have another week count based on the
tax year so week 1 begins April 1st.
