### ISSUE TITLE
always use "/usr/sbin/sendmail" as SendMail path no matter what real path I set in Global Configuration

### ISSUE THREAD

**Issue by baijianpeng** [joomla/joomla-cms#10032]
#### Steps to reproduce the issue

Enter backed Global Configuration of Joomla 3.5.1, Server Tab, Email Settings:

Choose "Sendmail" as the email method.

Since I use XAMPP for Windows as localhost testing server, I input the real path of sendmail.exe to the "Sendmail path" field:

`D:/xampp/sendmail/sendmail.exe`

Fill other fields of email settings. Then click on the "Send test email " button.

#### Expected result

I hope it will successfully send out the testing email.

#### Actual result

No, no email sent out, I got following error message:

> Could not execute: /usr/sbin/sendmail

#### System information (as much as possible)

Joomla 3.5.1
PHP 7
XAMPP for windows
Windows 10 64-bit

#### Additional comments

I just wonder: why the error message tell me a different path of sendmail while I had already fill that field with another real path?

**Comment by andrepereiradasilva** [comment]
i think the problem is joomla does not use that conf var.

maybe after https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/factory.php#L685 adding this line:
```php
$mail->set('Sendmail', $conf->get('sendmail', '/usr/sbin/sendmail'));
```

**Comment by sovainfo** [comment]
@baijianpeng Configure sendmail_path in php.ini and phpmailer will respect it, provided it contains the word sendmail. Currently it doesn't mention sendmail in it which is why it defaults to /usr/sbin/sendmail.

**Comment by baijianpeng** [comment]
If Joomla only read sendmail path from php.ini, why show an input box for this parameter in "Global Configuration"?

**Comment by sovainfo** [comment]
Not saying Joomla only reads from php.ini, just answering your question. Agree with the solution proposed by @andrepereiradasilva 
Joomla fails to communicate to phpmailer the path to the sendmail.
phpmailer stupidly enough only accepts a path from php.ini sendmail_path that requires the word sendmail in it. It defaults to /usr/sbin/sendmail otherwise.

**Comment by mbabker** [comment]
See #10342
