### ISSUE TITLE
Empty initial value for CURRENT default on JForm user field

### ISSUE THREAD

**Issue by sakicnet** [joomla/joomla-cms#10036]
#### Steps to reproduce the issue
Make a form with following xml:
`<field name="owner" type="user" default="CURRENT" label="Owner" description="" />`

#### Expected result
`<input type="hidden" id="jform_params_owner_id" name="jform[params][owner]" value="USER_ID" class="field-user-input " data-onchange="">`

#### Actual result
`<input type="hidden" id="jform_params_owner_id" name="jform[params][owner]" value="0" class="field-user-input " data-onchange="">`

#### Additional comments
See pull request [10035](https://github.com/joomla/joomla-cms/pull/10035) for fix.

**Comment by brianteeman** [comment]
@sakicnet you dont need to create a Pull Request AND and an issue on the tracker. Its magical so when you create a Pull Request it is automatically created on the issue tracker<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10036">issues.joomla.org/joomla-cms/10036</a>.</sub>
