### ISSUE TITLE
Mass mail in acl

### ISSUE THREAD

**Issue by JurgenG** [joomla/joomla-cms#10041]
Currently, any user with access to the backend, can send mass emails.
I see 2 reasons why this is not a good idea:

1. In some cases a different mailing application is used (e.g. AcyMail). This then creates confusion
2. In some cases I don't want all backend users to have access to this functionality

Currently, the only hack is to tweak the core files (remove the menu item). And even then, this hack only hides the functionality, but doesn't disable it.

The logical approach would be if there would be an ACL line for allowing or disallowing (or inheriting) send permissions.

**Comment by brianteeman** [comment]
Reset the priority to the documented standards https://docs.joomla.org/Bug_and_Issue_Tracker_Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10041">issues.joomla.org/joomla-cms/10041</a>.</sub>

**Comment by zero-24** [comment]
There is an option to disable mass mail in the global configuration.

BE -> System -> Global Configuration -> Server -> Disable Mass Mail

**Comment by JurgenG** [comment]
Thanks Brian. That solved the acute issue. :)
