### ISSUE TITLE
"Edit State own" permission should also be in joomla

### ISSUE THREAD

**Issue by danish1023** [joomla/joomla-cms#10044]
#### Feature Request

"Edit State own" permission should also be in joomla

**Comment by JoshuaLewis** [comment]
Would love to see a "Delete Own" permission which would allow users to delete only their own articles.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10044">issues.joomla.org/joomla-cms/10044</a>.</sub>

**Comment by schnuti** [comment]
Nice idea without the "Delete own". Delete is another level of responsibilty. I guess hard to implement in 3.x.

**Comment by andrepereiradasilva** [comment]
Same issue? https://github.com/joomla/joomla-cms/issues/6801

**Comment by pe7er** [comment]
Thank you for creating this but it appears that this issue has been reported https://github.com/joomla/joomla-cms/issues/6801 
We'll close it for now. If this is not correct then this can be re-opened. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10044">issues.joomla.org/joomla-cms/10044</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@pe7er forgot to close?

**Comment by pe7er** [comment]
@andrepereiradasilva Yes, you're right. thanks!

**Comment by brianteeman** [comment]
Closed
