### ISSUE TITLE
Admin menu batch process modal too small to operate

### ISSUE THREAD

**Issue by shamsbd71** [joomla/joomla-cms#10040]
#### Steps to reproduce the issue
Go to any Joomla 3.5.1 menu manager, then select a menu and click on batch button from top toolbar. now you can see something like this 
![screen shot 2016-04-22 at 05 10 14](https://issues.joomla.org/uploads/1/2eebb79b4a4ea6dcd5e8189d87061b0c.png)

#### Expected result
modal view should be at least in a height so we can see the menu and select them from the list. 

#### Actual result
Please note the height of the modal, its too small to select a menu from a menu group.
please see these pictures too.
![screen shot 2016-04-22 at 05 10 15](https://issues.joomla.org/uploads/1/d90e444275f6c51e81b0c544bf514fd6.png)
![screen shot 2016-04-22 at 05 10 16](https://issues.joomla.org/uploads/1/4fde30c2b6b36d18afd5786f8eba44f2.png)

#### System information (as much as possible)
joomla 3.5.1, php 5.5.9, ubuntu 14.04, chrome browser

#### Additional comments
the modal body has 114px height. it has max-height: 400px; there should be a min-height too.

**Comment by SharkyKZ** [comment]
Duplicate issue #9970 PR #9817

**Comment by brianteeman** [comment]
Closed as requested<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10040">issues.joomla.org/joomla-cms/10040</a>.</sub>
