### ISSUE TITLE
Images installed when no content is selected

### ISSUE THREAD

**Issue by Twincarb** [joomla/joomla-cms#10048]
#### Steps to reproduce the issue
Install Joomla
Install Joomla Content - Select None

#### Expected result
No content to be installed

#### Actual result
Images are installed irrespective of selection

#### Additional comments
I just realised that each time I install Joomla, the first thing I do is remove the images, before carrying on setting a site up.

**Comment by brianteeman** [comment]
In this case content means database content so it is working exactly as intended but feel free to submit a pull request to amend that behaviour so that it also refers to sample images
