### ISSUE TITLE
Home page displaying as index

### ISSUE THREAD

**Issue by MFraiman** [joomla/joomla-cms#10069]
#### Steps to reproduce the issue

Total Joomla / web developer beginner here, so pardon my lack of jargon ability, but the home page (only) of my site, www.OutpostMagazine.com is displaying seemingly as an html index. I uploaded a new article and iFrame this morning but the site looked fine after that. Seems to be CSS disconnected but I also have no idea what I'm talking about. 

#### Expected result

For the site to be normal.

#### Actual result

It is not. 

#### System information (as much as possible)

Joomla 3.3.6, currently Chrome/Safari on a MacBook though primarily Windows 10. (This error happened on my home computer, not at the office.)

#### Additional comments

Thanks for your help and patience!

**Comment by brianteeman** [comment]
This is a hosting problem. Please speak to your web host to fix this or use the forum http://forum.joomla.org
