### ISSUE TITLE
Finder - Content Maps Smart search

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#10061]
Go to Content maps and the search tools is always open with Branch selected. @andrepereiradasilva can you take a look please. It doesnt appear to be fixed by the two existing bug fixes for finder

**Comment by andrepereiradasilva** [comment]
that one is the next one i will review in terms of searchtools.

**Comment by andrepereiradasilva** [comment]
please test https://github.com/joomla/joomla-cms/pull/10068

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10061">issues.joomla.org/joomla-cms/10061</a>.</sub>
