### ISSUE TITLE
Fatal Error on Inflector Class

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#10080]
#### Steps to reproduce the issue
use Joomla\String\Inflector;

$inflector  = Inflector::getInstance();

#### Actual result
Fatal error: Cannot use 'String' as class name as it is reserved in /pubic_html/libraries/vendor/joomla/string/src/String.php on line 19

#### System information (as much as possible)
PHP Built On
Darwin 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64

Database Version 	
5.5.5-10.1.10-MariaDB

Database Collation 	
utf8_general_ci

Database Connection Collation 	
utf8mb4_general_ci

PHP Version 	
7.0.4

Web Server 	
Apache/2.4.18 (Unix) OpenSSL/1.0.2g PHP/7.0.4 mod_perl/2.0.8-dev Perl/v5.16.3

WebServer to PHP Interface 	
apache2handler

Joomla! Version 	
Joomla! 3.5.1 Stable [ Unicorn ] 05-April-2016 22:45 GMT

Joomla! Platform Version 	
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

User Agent 	
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by mbabker** [comment]
Fixed with https://github.com/joomla/joomla-cms/pull/9704
