### ISSUE TITLE
RFC - Remove Installation Folder Message

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#10088]
Despite adding instructions that the word installation should not be translated when it refers to the name of the actual folder that should be deleted the vast majority of translations have still translated this word.

This causes repeated problems when inexperienced users misunderstand the instruction and delete the entire joomla install.

As the translators are clearly ignoring the request not to translate this word then I would like to propose that we update the strings so that they use a hardcoded non-translatable string for INSTALLATION

**Comment by MATsxm** [comment]
+1

**Comment by Twincarb** [comment]
When the final page with the "Congratulations Joomla! is now installed" 

I would expect that it means everything is completed not there is one more step to take. Yellow box should only appear if the final part of the install script was unable to remove the "installation" folder.

This would remove the requirement for the string, I have no idea how many installs are affected to a degree that the install script is able to unpack and make changes to the appropriate folder but then unable to delete the "installation" folder.

At this point I agree that the "installation" should be hard coded.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10088">issues.joomla.org/joomla-cms/10088</a>.</sub>

**Comment by brianteeman** [comment]
@twincarb currently that would not be possible as on the same screen that you have the option to remove the /installation folder you also have the option to install additional languages<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10088">issues.joomla.org/joomla-cms/10088</a>.</sub>

**Comment by brianteeman** [comment]
Only today the cz installation files were merged by @Bakual  with this mistake repeated<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10088">issues.joomla.org/joomla-cms/10088</a>.</sub>

**Comment by brianteeman** [comment]
Closing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10088">issues.joomla.org/joomla-cms/10088</a>.</sub>
