### ISSUE TITLE
Problem with module Modules: Articles - Newsflash com_modules

### ISSUE THREAD

**Issue by vihuarar** [joomla/joomla-cms#10085]
I need to configure a module to show the latest news in the home page... but I need to set in some articles a "finish publishing date"... because we want that an article is just visible for certain dates.. and then disappear...

#### Steps to reproduce the issue
Configure Modules: Articles - Newsflash, to show articles from a category...

#### Expected result
The module shows the articles.... and don't show the articles that has the "publishing dates" with a pasted date...

#### Actual result
The module shows all the articules.. included the articles that has a past date...

#### System information (as much as possible)
I have Joomla! 3.5.1
ubuntu 14.04

**Comment by brianteeman** [comment]
I cannot confirm that an article with an end publishing date in the past is displayed with the newsflash module.

Please use the forum for support http://forum.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10085">issues.joomla.org/joomla-cms/10085</a>.</sub>

**Comment by vihuarar** [comment]
You dont have to confirm that... because I did it... and It didnt work... so I think this is a bug...

I didnt understand your comment... why you cant confirm that? whats your argument?

**Comment by brianteeman** [comment]
Because it worked perfectly for me

On 25 April 2016 at 14:23, vihuarar <notifications@github.com> wrote:

> You dont have to confirm that... because I did it... and It didnt work...
> so I think this is a bug...
>
> I didnt understand your comment... why you cant confirm that? whats your
> argument?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10085#issuecomment-214324120>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
> You dont have to confirm that... because I did it... and It didnt work... so I think this is a bug...

For someone else to fix a bug, usually they have to be able to confirm it's a bug instead of blindly chasing after an issue posted somewhere.  If it can't be reproduced consistently, odds are that it's not a bug.

**Comment by vihuarar** [comment]
@brianteeman I think I found the problem.... but not the solution... still I think this is a but... but only when a super administrator login in the front end...

If you login in the front end like super administrator... 
The module shows all the articules.. included the articles that has a past date...

but if you login with a register user (standard user) the module shows the articles.... and don't show the articles that has the "publishing dates" with a pasted date...

**Comment by brianteeman** [comment]
That would make perfect sense and is the expected behaviour as a super
administrator will always see expired and deleted content

On 25 April 2016 at 14:50, vihuarar <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> I think I found the
> problem.... but not the solution... still I think this is a but... but only
> when a super administrator login in the front end...
>
> If you login in the front end like super administrator...
> The module shows all the articules.. included the articles that has a past
> date...
>
> but if you login with a register user (standard user) the module shows the
> articles.... and don't show the articles that has the "publishing dates"
> with a pasted date...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10085#issuecomment-214337117>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
