### ISSUE TITLE
Send test email not able to send e-mail

### ISSUE THREAD

**Issue by javigomez** [joomla/joomla-cms#10083]
#### Steps to reproduce the issue
Go to System -> Global Settings -> Server

Make sure your Mail Settings are properly set and try to send a Test email:

![screen shot 2016-04-25 at 05 15 10](https://issues.joomla.org/uploads/1/b60c651c9dbe07c931fd69940362173e.png)

You should see that system was not able to send the mail.

However, try this:

- create a new Joomla user (in order to send a dummy mail to him)
- Go to Users -> Mass mail Users and send a dummy mail 

![screen shot 2016-04-25 at 05 15 10](https://issues.joomla.org/uploads/1/336e261d268d3b5c7ef95c7e5cdfd37b.png)

You should receive it this time:

![screen shot 2016-04-25 at 05 15 10](https://issues.joomla.org/uploads/1/7d159cf5e2b31d9dc353c59605e10f0b.png)

So, my guess is that there is something wrong in the "Send email test" button.

#### Expected result
The "Send email test" button in  Global Configuration sends a dummy e-mail without issues.

#### Actual result
The "Send email test" button in  Global Configuration returns: "Test mail could not be sent.Could not instantiate mail function."

#### System information (as much as possible)
I'm using https://github.com/joomlatools/joomlatools-vagrant#joomlatools-vagrant webserver with Mailcatcher https://mailcatcher.me/ with port 1025 and Joomla 3.5.1

**Comment by zero-24** [comment]
@javigomez can you try the current staging? There was a fix for the test mail see: https://github.com/joomla/joomla-cms/pull/9904

**Comment by javigomez** [comment]
You are right @zero-24. Working in `staging` without issues:

![screen shot 2016-04-25 at 15 44 04](https://cloud.githubusercontent.com/assets/1375475/14785757/a1a34a9a-0afc-11e6-9f3e-2e24b69925df.png)
![screen shot 2016-04-25 at 15 43 58](https://cloud.githubusercontent.com/assets/1375475/14785758/a1a950b6-0afc-11e6-99e5-83bac4bbe099.png)
