### ISSUE TITLE
Setting for visible "Author, Views, etc" for article [com_content]

### ISSUE THREAD

**Issue by sanek4life** [joomla/joomla-cms#10099]
Settings for Article "fields", like "Author, Views, Category, etc".

Who can view this fields in article?

![fields options](https://cloud.githubusercontent.com/assets/3662519/14828326/3279d67c-0bef-11e6-8bcb-e6568e79fc42.png)

This is be good settings for registered members or site editors. Some private for this fields.

###Example###

I'm site editor and i'm interesting, how many times people view my article, but i'm not want show this information for all site visitors. and i'm no have access to "site admin", i'm add new Articles from frontpage.

**Comment by brianteeman** [comment]
This is not currently available. You could do it with a template override. This will not be added to the core as it will increase the complexity o the user interface for something that can be done from the administrator interface.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10099">issues.joomla.org/joomla-cms/10099</a>.</sub>
