### ISSUE TITLE
Community Builder 2.0.14 fails to install  (PHP Version 7.0.5)

### ISSUE THREAD

**Issue by johnduncanferguson** [joomla/joomla-cms#10094]
**Notice**

Database driver 'pdomysql' is not supported. Please use MySQL instead.
**Warning**

**Extension **Install**: Custom install routine failure.**
**Error**
My System Information 

**PHP Built On**	Windows NT MORITA-PC 10.0 build 10586 (Windows 10) i586
**Database Version**	5.5.5-10.1.13-MariaDB
**Database Collation**	utf8mb4_general_ci
**Database Connection Collation**	utf8mb4_general_ci
**PHP Version**	7.0.5
**Web Server**	Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.5
**WebServer to PHP Interface**	apache2handler
**Joomla! Version**	Joomla! 3.5.1 Stable [ Unicorn ] 05-April-2016 22:45 GMT
**Joomla! Platform Version**	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
**User Agent**	Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Error installing **package****
**Install**
**Update**
**Manage**
**Discover**
**Database**
**Warnings**
**Install Languages**
**Update Sites**
??Community Builder 2.0.14??

**Comment by alikon** [comment]
you should contact the extension developer, i suppose not a joomla fault here

**Comment by zero-24** [comment]
Hi,

the Community Builder is an external component and not the Joomla Core. As the error message sounds like a issue with CB `Install: Custom install routine failure.` Please contact there support team: https://www.joomlapolis.com/forum

Thanks.

**Comment by brianteeman** [comment]
closed for the reasons stated above
