### ISSUE TITLE
Optimize com_content SQL queries and cache

### ISSUE THREAD

**Issue by joomla-ua** [joomla/joomla-cms#10103]
#### Steps to reproduce the issue

If over 80 000 articles site is down with 500 error.

Authors add new news every 3-5 minutes.

Always all com_content cache clear

**Comment by zero-24** [comment]
Can you provide some debug data?

Examples
- SQL Querys (Joomla debug)
- PHP Version
- MySQL Version
- Apatche Version
- which caching mechanisme do you use/try redis memcache?
- what is your hosting infrastructure? Shared hosting? Vps? Other?

**Comment by alikon** [comment]
Plus are you using some 3dp extension?

**Comment by wilsonge** [comment]
I'm closing this until we get some new information at which point we can reopen this PR
