### ISSUE TITLE
Mismatched use of JDatabaseQueryLimitable

### ISSUE THREAD

**Issue by ssv445** [joomla/joomla-cms#10108]
While using limit & offset on a query objects (which is inherited from JDatabaseQuery but does not implement JDatabaseQueryLimitable), there is no way limit & offset can be utilized.

Query as -
 $db->setQuery($query, $start,$offset)
It will set limit & offset on db object.
https://github.com/joomla/joomla-cms/blob/3.5.1/libraries/joomla/database/driver.php#L2115

But when the limit & offset is expected to be utilized a cross check is done on JDatabaseQuery
https://github.com/joomla/joomla-cms/blob/3.5.1/libraries/joomla/database/driver/mysqli.php#L569

This way in any way, I cannot apply limit & offset without implementing JDatabaseQueryLimitable.

#### Expected result
Should return only limited records

#### Actual result
Currently when we mention limit & offset on query, and execute it, it returns all records.

#### Additional comments
This is a simple fix, to check for same class.

**Comment by brianteeman** [comment]
As it is a "simple fix" please submit a pull request

**Comment by brianteeman** [comment]
Closed as we have a pull request
