### ISSUE TITLE
Question: "Display in menu" field

### ISSUE THREAD

**Issue by sural98** [joomla/joomla-cms#10105]
"Display in menu" field was newly introduced in 3.5.1 for menu items.
On the other hand we have menu status dropdown (publish/unpublished/trashed).
Do you think it is somewhat duplicate?
That is menu status can be selected as published while it can be rendered as unpublished?
SUGGESTION:
According to me menu item creation is a duplicate work since Joomla 1.5 in that sense thus "display in menu" field could be an option in category manager so that when a category entry is selected as a menu item we no longer need to create menu items at all.

**Comment by brianteeman** [comment]
It has completely different purposes. If a menu is unpublished then it cat
be used. If it is set to be hidden (display in menu) then it can be used
but is not displayed. Plus your suggestion only applies to something that
has a category this option (display in menu) can be used for any type of
menu item

On 27 April 2016 at 09:10, sural98 <notifications@github.com> wrote:

> "Display in menu" field was newly introduced in 3.5.1 for menu items.
> On the other hand we have menu status dropdown
> (publish/unpublished/trashed).
> Do you think it is somewhat duplicate?
> That is menu status can be selected as published while it can be rendered
> as unpublished?
> SUGGESTION:
> According to me menu item creation is a duplicate work since Joomla 1.5 in
> that sense thus "display in menu" field could be an option in category
> manager so that when a category entry is selected as a menu item we no
> longer need to create menu items at all.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10105>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
> We have a menu where we have 5 items: Home; The company; Services; Portfolio; Contacts
But we don't want to show "Home" in the main menu, just: The company; Services; Portfolio; Contacts.

> create "hidden" menu items that exist in the menu and the website but aren't displayed in the main menu without having to create another menu for those "hidden" menu items.

More info in the PR which implemented that option https://github.com/joomla/joomla-cms/pull/8816

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10105">issues.joomla.org/joomla-cms/10105</a>.</sub>
