### ISSUE TITLE
ACL access.xml action names containing "_" not properly inserted in database

### ISSUE THREAD

**Issue by virgilbugnariu** [joomla/joomla-cms#10107]
#### Steps to reproduce the issue
Updating permissions from the ACL permissions form will improperly update the permission saved in the assets table. This only happens when the **action** **name** value contains an "_" (underscore). For example:
    
    <action name="avchat3.allow_user_interface" [...]

#### Expected result
In the assets table in the **rules** column, it should be saved as 

    {"avchat3.allow_user_interface":{"1":0,"2":1} [...]

#### Actual result
However, the action name seems to stop at the first encountered "_", additionally adding the second word (after the underline) as the user role ID, so the rules cell looks like:
    
    {"avchat3.allow":{"user":1 [...]

#### System information (as much as possible)

Fresh Joomla 3.5.1 installation running on Apache, PHP 5.6

#### Additional comments

I can confirm that on Joomla! 3.4.8 everything worked as expected.

**Comment by brianteeman** [comment]
Is this resolved by #9648 that has already been merged into staging?

On 27 April 2016 at 13:51, Virgil B. <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> Updating permissions from the ACL permissions form will improperly update
> the permission saved in the assets table. This only happens when the
> *action* *name* value contains an "_" (underscore). For example:
>
> <action name="avchat3.allow_user_interface" [...]
>
> Expected result
>
> In the assets table in the *rules* column, it should be saved as
>
> {"avchat3.allow_user_interface":{"1":0,"2":1} [...]
>
> Actual result
>
> However, the action name seems to stop at the first encountered "_",
> additionally adding the second word (after the underline) as the user role
> ID, so the rules cell looks like:
>
> {"avchat3.allow":{"user":1 [...]
>
> System information (as much as possible)
>
> Fresh Joomla 3.5.1 installation running on Apache, PHP 5.6
> Additional comments
>
> I can confirm that on Joomla! 3.4.8 everything worked as expected.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10107>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by virgilbugnariu** [comment]
Hi Brian,

Sorry, I must have missed the issue posted on GitHub. 
I updated the **permissions.js** and **permissions.min.js** files and the permissions are saved properly.

You can close the issue.
Thank you for your help.


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10107">issues.joomla.org/joomla-cms/10107</a>.</sub>

**Comment by brianteeman** [comment]
Closed
