### ISSUE TITLE
Ordering broken in Redirects component

### ISSUE THREAD

**Issue by tgv604** [joomla/joomla-cms#10104]
#### Steps to reproduce the issue

1) Sort the list by some column, say ID or hits

2) Do something with an item -- publish/trash/etc.

#### Expected result

After page reload the ordering would stay

#### Actual result

After page reload the ordering resets to default.

Default ordering has no indication what it is, too.

#### System information (as much as possible)

php version irrelevant, haappens on different servers

#### Additional comments

I suspect it broke with introduction of searchtools but not too sure

**Comment by brianteeman** [comment]
Is this with 351 or current staging?

**Comment by brianteeman** [comment]
I cant confirm this with current staging - can you please confirm - maybe I misunderstood somethig<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10104">issues.joomla.org/joomla-cms/10104</a>.</sub>

**Comment by tgv604** [comment]
it's current release, 3.5.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10104">issues.joomla.org/joomla-cms/10104</a>.</sub>

**Comment by brianteeman** [comment]
Please test with staging as I believe this has already been fixed

**Comment by andrepereiradasilva** [comment]
yes i think it's fixed by https://github.com/joomla/joomla-cms/pull/9971.

But, pelase test in latest staging https://github.com/joomla/joomla-cms/archive/staging.zip

**Comment by andrepereiradasilva** [comment]
now that https://github.com/joomla/joomla-cms/pull/9971 has been merged.

It's fixed in latest staging.

**Comment by brianteeman** [comment]
Closed
