### ISSUE TITLE
Incorrect Documentation on JFactory::getCache()

### ISSUE THREAD

**Issue by gsexton** [joomla/joomla-cms#10112]
#### Steps to reproduce the issue
 Examine the entry for getCache() on this page:

https://api.joomla.org/cms-3/classes/JFactory.html

#### Expected result

The document states:

"Returns the global JCache object"

See: \JCache

#### Actual result

The actual returned object is a JCacheController.

**Comment by photodude** [comment]
Looks right in the code, but the API definitely shows the wrong information

https://github.com/joomla/joomla-cms/blob/881021635765e6b055188e6ad7d25d50a6db2cf8/libraries/joomla/factory.php#L254-L268

**Comment by gsexton** [comment]
It's the comment at the head:


Returns the global {@link JCache} object




On 4/27/2016 6:35 PM, Walt Sorensen wrote:
>
> Looks right in the code, but the API definitely shows the wrong 
> information
>
> https://github.com/joomla/joomla-cms/blob/881021635765e6b055188e6ad7d25d50a6db2cf8/libraries/joomla/factory.php#L254-L268
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/joomla/joomla-cms/issues/10112#issuecomment-215273379>
>

-- 
George Sexton
*MH Software, Inc.*
Voice: 303 438 9585
http://www.connectdaily.com

**Comment by brianteeman** [comment]
Please submit a Pull request to fix it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10112">issues.joomla.org/joomla-cms/10112</a>.</sub>

**Comment by photodude** [comment]
If I read the code right it should be JCache since it "Returns a reference to a cache adapter object, always creating it" thus a JCache object as the JFactory code is calling `JCache::getInstance()` 

If the JFactory code was using `JCacheController::getInstance()` it "Returns a reference to a cache adapter object, always creating it" it would be a JCacheController object.

If I followed the JFactory code correctly, the [DocBlock at line 263](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/factory.php#L263) should be JCache

@gsexton Since this is your issue, do you want to submit a Pull Request to fix it?

**Comment by mbabker** [comment]
It returns `JCacheController`.  `JCache::getInstance()` returns a `JCacheController` instance "decorating" `JCache`.

**Comment by gsexton** [comment]
On 4/28/2016 10:26 AM, Michael Babker wrote:
>
> It returns |JCacheController|. |JCache::getInstance()| returns a 
> |JCacheController| instance "decorating" |JCache|.
>

I'm kind of a beginner at PHP, can you explain to me what "instance 
"decorating" JCache" means? I'll do a pull request, I just want to make 
sure I understand that first.

> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/joomla/joomla-cms/issues/10112#issuecomment-215484915>
>

-- 
George Sexton
*MH Software, Inc.*
Voice: 303 438 9585
http://www.connectdaily.com

**Comment by gsexton** [comment]
Never mind. I found some stuff. That means the doc is still wrong... I'll submit a pull request. I want to fix the issue with JCache->setLifeTime() not telling what the units are.

**Comment by photodude** [comment]
Thanks for the clarification @mbabker (It's nice to have people around who are well versed in what these things truly mean when the documentation is lacking in specifics)

We should probably clarify this distinction in the documentation too.

**Comment by photodude** [comment]
@gsexton one of the best ways to get your feet wet and/or build your skills is to Submit PR's.

**Comment by photodude** [comment]
@mbabker Looks like the [3.5 API docs](https://api.joomla.org/cms-3/classes/JCache.html#method_getInstance) are Wrong for `JCache::getInstance()` as it says the response is JCache object, whereas the `JCache::getInstance()` [code correctly shows JCacheController](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/cache/cache.php#L75-L84) for the return.

Seems a bit strange...

**Comment by izharaazmi** [comment]
Can we close this as the PR #10152 was merged?
