### ISSUE TITLE
behavior.php script issue: JavaScript virus injection Reason: long string Code

### ISSUE THREAD

**Issue by gianni972** [joomla/joomla-cms#10118]
#### Steps to reproduce the issue
Scan a joomla website using siteguarding.com

#### Actual result
JavaScript virus injection Reason: long string Code: DHTML Date\/Time Selector\n(c) dynarch.com 2002-2005 \/ Author: Mihai Bazon\nFor latest version visi

The file is libraries/cms/html/behavior.php

**Comment by brianteeman** [comment]
Automated tests will often produce false positives like this. You should notify siteguarding.com that their test result is fals<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10118">issues.joomla.org/joomla-cms/10118</a>.</sub>
