### ISSUE TITLE
Possibility to abort a drag and drop action in tinymce

### ISSUE THREAD

**Issue by designbengel** [joomla/joomla-cms#10119]
#### Steps to reproduce the issue
By taking the wrong image by from computer (drag and drop) it would be great to have a possibility to abort the upload process. For example when i upload the high resolution image by mistake.

#### Expected result
Button and/or esc command to abort the process

**Comment by brianteeman** [comment]
Not sure it will ever be possible as YCFS :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10119">issues.joomla.org/joomla-cms/10119</a>.</sub>

**Comment by designbengel** [comment]
That was me! the "S" :-D <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10119">issues.joomla.org/joomla-cms/10119</a>.</sub>

**Comment by MATsxm** [comment]
depends the pic...

**Comment by brianteeman** [comment]
Closed as it is not possible currently and it is an external library not our own - sorry<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10119">issues.joomla.org/joomla-cms/10119</a>.</sub>
