### ISSUE TITLE
Ajax ACL - javascript ignoring "inherited" state

### ISSUE THREAD

**Issue by JurgenG** [joomla/joomla-cms#10121]
I was so stupid as to document 2 bugs in 1 video.
The first part of my video points out the solved issue. The second part (from 1:15) points out a second bug in the javascript...

(I will remove this video in 1 month from now):
https://dl.dropboxusercontent.com/u/7584025/troubleshooting.ogv

My impression is, the JS checks if the resp. is true ... and if it's not, it goes to "else".
There should be an elseif, discerning inherited from false.

**Comment by dgt41** [comment]
For the second part can you check that you language actually contains the translated string for `JLIB_RULES_ALLOWED`
The file is language/en-GB/en-GB.lib_joomla.ini (with respect to your language code)

**Comment by andrepereiradasilva** [comment]
it also happens in english. the permission js don't process the "Inherited" (only Allowed or Denied) so it fallback to Denied (else).

See https://github.com/joomla/joomla-cms/blob/staging/media/system/js/permissions.js#L54-L65

**Comment by infograf768** [comment]
I confirm the Ajax bug

**Comment by JurgenG** [comment]
This isn't a language issue, as a few have already pointed out. I think it's just a matter of adding an extra 'else' clause to have this fixed, but maybe I'm overseeing something.

**Comment by infograf768** [comment]
Indeed.
We have 3 values: 0 for Denied, 1 for Allowed empty for inherited.

**Comment by andrepereiradasilva** [comment]
i think this is already solved in 3.6.2, @JurgenG can you confirm?

**Comment by andrepereiradasilva** [comment]
is this solved or not?

**Comment by zero-24** [comment]
Closing.  If it is still a issue please reopen.

**Comment by JurgenG** [comment]
Sorry, I was gone a bit. It indeed seems solved. Thanks for fixing :)
