### ISSUE TITLE
Repositioning of image doesn´t work anymore (tinymce)

### ISSUE THREAD

**Issue by designbengel** [joomla/joomla-cms#10120]
#### Steps to reproduce the issue
Open an article with an image inbetween the text. 
Try to reposition the image by dragging it to another position of the article

#### Expected result
Normally the textindicator showed up and i could move the image to another position

#### Actual result
Seems the editor recognizes the moving as drag and drop action from computer, repositioning doesn´t work.

**Comment by brianteeman** [comment]
I cant replicate this see this movie or am I missing something
![screen shot 2016-04-28 at 06 38 12](https://issues.joomla.org/uploads/1/3b1c85f4139f1e79d3cc51c8cb52ff84.gif)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10120">issues.joomla.org/joomla-cms/10120</a>.</sub>

**Comment by designbengel** [comment]
Thanks for testing this @brianteeman , seems it´s an issue with chrome. Will test it later once more...

**Comment by brianteeman** [comment]
That recording was with chrome ;)

On 28 April 2016 at 12:44, designbengel <notifications@github.com> wrote:

> Thanks for testing this @brianteeman <https://github.com/brianteeman> ,
> seems it´s an issue with chrome. Will test it later once more...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10120#issuecomment-215398971>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by designbengel** [comment]
can i excuse with "#ycfs" was sitting next to me and i was under pressure ;) ?
