### ISSUE TITLE
Backend en-GB.com_joomlaupdate file. Mistake in source string

### ISSUE THREAD

**Issue by jofrank** [joomla/joomla-cms#10132]
String: COM_JOOMLAUPDATE_VIEW_DEFAULT_NO_DOWNLOAD_URL_DESC

Full: An update to Joomla %1$s was found, but it wasn't possible to fetch the download URL for that update. There are two possibilities why this happens:<br>- Your host doesn't support <a href="https://www.joomla.org/technical-requirements.html">the minimum requirements for Joomla %1$s</a> and there is no alternative download for your configuration available.<br>- There is a problem with Joomla Update Server.<br><br>Please try to download the update package from <a href="https://www.joomla.org/download.html">the official Joomla download page</a> and use the Upload and Install tab.

Mistake: The text of the tab is 'Upload Package File' and NOT 'Upload and Install'. 'Upload and Install' is the text on the button in the tab.

**Comment by brianteeman** [comment]
Actually in the current staging it is Upload and Update<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10132">issues.joomla.org/joomla-cms/10132</a>.</sub>

**Comment by brianteeman** [comment]
Please see #10133 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10132">issues.joomla.org/joomla-cms/10132</a>.</sub>
