### ISSUE TITLE
com_banners: Module does not show any content when attached inside article

### ISSUE THREAD

**Issue by valerie16901** [joomla/joomla-cms#10140]
#### Steps to reproduce the issue

-Create a banner, including some meta keywords.
-Create a banner module an setup the option "Search by Meta Keyword" to "YES".
-Activate the module in any position let's say "position-7" on Protostar template
-Disable the cache for the banners module and save.

-Create a Content article and setup some Meta Keywords which will be used to display the banner accordingly.
-Embed the module Banners inside the article using the "Module" button on the tinyMCE editor (the syntax will look something like this {loadmodule mod_banners,banners module title} ) and save it.
#### Expected result

-The Banners module works good and shows the banner according to the Meta Keywords in the "position-7" or any other position in the default Protostar template.
-The banners module should also work the same way when embedded inside the article, displaying the banners according to the Meta Keywords.
#### Actual result

-The Banners module embedded inside the article shows no content at all.
-The source code shows:
< div class = " module " >
< h3 > Banners module title< / h3 >
< div class = " banner group " > < / div >
< / div > 
#### Additional comments

-I tried to disable all the joomla cache and the problem still persist.
-When disabling the option "Search by Meta keyword" inside the Banners Module, the module can display his content inside the article with no issue.

**Comment by brianteeman** [comment]
I followed the instructions above and can NOT confirm this on a clean install
When search by metakeyword was not selected a banner was displayed
When search by metakeyword was selected a banner was not displayed and unlike the report the raw code was not displayed
 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10140">issues.joomla.org/joomla-cms/10140</a>.</sub>

**Comment by brianteeman** [comment]
Ignore my last comment
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10140">issues.joomla.org/joomla-cms/10140</a>.</sub>

**Comment by brianteeman** [comment]
I created a banner with the meta keyword test and embedded a banner module in an article with the meta keyword test. 
I then inserted a banner module in that article
When search by metakeyword was not selected a banner was displayed
When search by metakeyword was selected a banner was not displayed 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10140">issues.joomla.org/joomla-cms/10140</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Issue exists in 3.7-staging.

**Comment by GeraintEdwards** [comment]
Issue still exists in 3.7.3-staging.

I have investigated the cause and found the reason for the problem.

components/com_content/views/article/view.html.php calls the onContentPrepare plugin (which in turn loads the embedded module) BEFORE it calls _prepareDocument (which sets the meta data).

Changing the order of these calls could have unforseen consequences - e.g. plugins that set the meta tags based on the content or category would break.

I can see many benefits of making the viewed article available within the loadmodule methods of the content plugin.  For example a new custom module that is used to display the custom fields of the currently viewed article.

This may be a better solution - I would be interested in other people's views before suggesting some code changes.

**Comment by chmst** [comment]
Confirmed also for J4.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10140">issues.joomla.org/tracker/joomla-cms/10140</a>.</sub>

**Comment by chmst** [comment]
This feature is based on the meta keywords in an article. 
As we do not render the meta keywords any more (https://github.com/joomla/joomla-cms/pull/25258) this cannot work in new sites.

**Comment by brianteeman** [comment]
> This feature is based on the meta keywords in an article.
> As we do not render the meta keywords any more (https://github.com/joomla/joomla-cms/pull/25258) this cannot work in new sites.

It should still work - thats why we kept the keywords

**Comment by chmst** [comment]
Trying to use it in my new site J4 , but there are no keywords in the head. Maybe I am missing a param?

**Comment by brianteeman** [comment]
yes there are no keywords in the head. that is correct.

from memory it is matching the value oif the keyword in the article and the keyword in the banner

**Comment by chmst** [comment]
https://github.com/joomla/joomla-cms/blob/4.1-dev/modules/mod_banners/src/Helper/BannersHelper.php#L38  The module uses <meta name="keywords" here. 

I see that the related_items module searches for keywords in the article, not in <meta

**Comment by brianteeman** [comment]
banners should do it the same way now. it was missed in error

**Comment by N6REJ** [comment]
@brianteeman can you fix the missed code?

**Comment by brianteeman** [comment]
sadly not

**Comment by MacJoom** [comment]
I'm working on it - its all about knowing the $article which is calling the banner module - that's where i'm stuck.

**Comment by MacJoom** [comment]
I have investigated the code of the banners generation and found that the rendering of banners in a banners module with 'Select by keywords' set to 'Yes' is completely broken  - not just as a module in an article - since the keywords are not set in the document anymore and the BannersHelper gets it from there with  $keywords = explode(',', $app->getDocument()->getMetaData('keywords')); - i have a solution for the original issue, but i'm looking for a solution fixing this for the banners in a position too

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39016 . Thanks in advance.
