### ISSUE TITLE
TinyMce on mobile viewport not rendering correctly

### ISSUE THREAD

**Issue by Twincarb** [joomla/joomla-cms#10151]
#### Steps to reproduce the issue
1. Using a mobile viewport 
2. GO to com_content add article, click "+Article" in TinyMce the popup doesn't size to the device unable to close.
3. Go to frontend edit, click "+Article" in TinyMce and see the same as above.

#### Expected result
popup to resize as appropriate.

#### Actual result
modal doesn't resize

#### System information (as much as possible)
Latest staging 

#### Additional comments

**Comment by JoomliC** [comment]
> Apply patch #10147 & #10076 

@Twincarb Please, to prevent real confusion, thanks to edit your issue, and focus only on TinyMCE modals not responsive ;-)
This is were the problem you mention in other PR is, not in modal-body and Bootstrap modals patches ;-)

Thank you!

**Comment by Twincarb** [comment]
Having had a read on the TinyMCE github page, it looks like this is a known issue with TinyMCE not working as expected with mobile viewports.

There are comments from last year suggesting that they are working on a lightweight version for mobiles, while this affects and is an issue for Joomla it isn't one that can be rectified at the moment.
Depending on if there is a separate mobile version released or if it will be integrated into the main version will depend on if this issue is valid. ie if it's a separate solution thats provided and needing to be put into Joomla then I feel it's valid, however if it's just upgrading to the version of TinyMCE that fixes the issue then it isn't valid...

@brianteeman @JoomliC views on if a valid issue or not please.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10151">issues.joomla.org/joomla-cms/10151</a>.</sub>

**Comment by JoomliC** [comment]
I think this issue is valid, as even if issue in TinyMCE library, it affects Joomla usuability on mobile.
@Twincarb do you have a direct link to where this question is raised on TinyMCE GitHub ?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10151">issues.joomla.org/joomla-cms/10151</a>.</sub>

**Comment by Twincarb** [comment]
@JoomliC 
The original thread is an old one from 2013 https://github.com/tinymce/tinymce/issues/1307 

It's still an open issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10151">issues.joomla.org/joomla-cms/10151</a>.</sub>

**Comment by brianteeman** [comment]
As this is an issue with an external library there really isnt anything we can do.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10151">issues.joomla.org/joomla-cms/10151</a>.</sub>
