### ISSUE TITLE
com_finder Notice when saving filter

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#10187]
Create a filter in Smartsearch, save.
`[02-May-2016 09:08:04 UTC] PHP Notice:  Undefined property: FinderTableFilter::$d2 in ROOT/administrator/components/com_finder/tables/filter.php on line 83

**Comment by infograf768** [comment]
@chrisdavenport

**Comment by brianteeman** [comment]
Closed please see #10192 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10187">issues.joomla.org/joomla-cms/10187</a>.</sub>
