### ISSUE TITLE
Untranslated Strings in en-GB.com_users.ini - Upon user registering email to admin SUBJECT and BODY both unstranslated (missing in lang file).

### ISSUE THREAD

**Issue by edzz83** [joomla/joomla-cms#10209]
#### Steps to reproduce the issue

Upon registration in the back end of joomla (i tried registering a super user) I get administrator emails containing the following untranslated strings:
COM_USERS_EMAIL_REGISTERED_NOTIFICATION_TO_ADMIN_BODY (in the body of email)
COM_USERS_EMAIL_ACCOUNT_DETAILS (in the subject)

#### Expected result

Translated string from the enGB file found in: administrator/language/en-GB/en-GB.com_users.ini, am unsure what this used to contain. I bleieve it used to advise that you had a registration along with what website the email has come from, and what the users name was.

#### Actual result

Untranslated lines:
COM_USERS_EMAIL_REGISTERED_NOTIFICATION_TO_ADMIN_BODY (in the body of email)
COM_USERS_EMAIL_ACCOUNT_DETAILS (in the subject)

#### System information (as much as possible)

Joomla 3.5.1
Language enGB

#### Additional comments

I checked administrator/language/en-GB/en-GB.com_users.ini,
it does not contain a translation for:
COM_USERS_EMAIL_REGISTERED_NOTIFICATION_TO_ADMIN_BODY
COM_USERS_EMAIL_ACCOUNT_DETAILS

When i add these to the file it works fine.

This is def appears to be an issue with the enGB file not containing the translations in release, i am running latest 3.5.1. It appears to be an issue with release (or update not updating the file correctly, however i can see that the last modified date is perfectly correct on this file in line with the 3.5.1 update). Not sure how to report it properly tho. Hope this is correct.

**Comment by infograf768** [comment]
The strings are present in 3.5.1 as well as staging.

They are not in administrator/language/en-GB/en-GB.com_users.ini BUT in the site language folder ROOT/language/en-GB/en-GB.com_users.ini

They are used ONLY when registration is done from frontend.

When you  create a new user in back-end (i.e. when the Joomla User plugin is set to send Notification Mail to User) these strings are not used.

![screen shot 2016-05-03 at 08 49 32](https://cloud.githubusercontent.com/assets/869724/14976510/9c69fd38-110c-11e6-8522-eac6bd19fc35.png)

The strings used are in administrator/language/en-GB/en-GB.plg_user_joomla.ini

`PLG_USER_JOOMLA_NEW_USER_EMAIL_BODY="Hello %s,\n\n\nYou have been added as a User to %s by an Administrator.\n\nThis email contains your username and password to log in to %s\n\nUsername: %s\nPassword: %s\n\n\nPlease do not respond to this message as it is automatically generated and is for information purposes only."`


and

`PLG_USER_JOOMLA_NEW_USER_EMAIL_SUBJECT="New User Details"`

I just tested to be sure and it works fine.
![screen shot 2016-05-03 at 08 56 02](https://cloud.githubusercontent.com/assets/869724/14976546/eec5523a-110c-11e6-81de-ba7bedb28abb.png)

**Comment by edzz83** [comment]
Strange, 

Can you perhaps offer a tip as to how/why my installation would be firing off emails with these langauge attributes incorrectly... I feel like the answer is in your post somewhere but it alludes me.

**Comment by sovainfo** [comment]
The only thing I can think of is an extension that forgets to load the right message file.
The string is only used when enduser is registering. So, I suspect a plugin that you installed that uses that string. 

Suggest to post on forum.joomla.org to find out what is causing this issue in your environment. Consider this issue not a problem with Joomla core and to be closed.
It can be reopened when it turns out to be an issue in Joomla core.

**Comment by Lumiga** [comment]
Same issue over here, but it looks like everything is fine or NOT?.


![search](https://cloud.githubusercontent.com/assets/22007393/23167787/03a7bb0e-f846-11e6-9683-db45ee685cfa.jpg)

**Comment by RobertPHeller** [comment]
It is also broken with Joomla! 3.10.  I can't find any extensions or plugins that might cause this problem.  I am not sure how to fix it, short of recoding the PHP code involved (eg hard coding the strings into the PHP code).  Has anyone ever figured out what is going on here?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10209">issues.joomla.org/tracker/joomla-cms/10209</a>.</sub>

**Comment by RobertPHeller** [comment]
I disabled ALL of the non-Joomal! code admin extensions and it still does not work.  What else can I do?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10209">issues.joomla.org/tracker/joomla-cms/10209</a>.</sub>

**Comment by RobertPHeller** [comment]
OK, upon further groveling in system settings (I turned on Debug Language on a test site) and created a test user from the admin side.  For some reason, administrator/language/en-GB/en-GB.plg_user_joomla.ini is not being loaded.  Why would that be?  What controls the loading of language files and what would prevent a language file from being loaded?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10209">issues.joomla.org/tracker/joomla-cms/10209</a>.</sub>

**Comment by RobertPHeller** [comment]
Even further groveling shows that the strings in question are COM_USERS_EMAIL_ACCOUNT_DETAILS and COM_USERS_EMAIL_REGISTERED_NOTIFICATION_TO_ADMIN_BODY, which are in language/en-GB/en-GB.com_users.ini, which is not loaded, when adding a new user *from the backend* (eg from the adminstrator page's Users->Manage->Add new user link).  These strings are used in plugins/user/wbs_autologin/wbs_autologin.php.  Is there something missing here?  We are running Joomla! 3.10.11 Stable [ Daraja ] 14-August-2022 14:18 GMT <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10209">issues.joomla.org/tracker/joomla-cms/10209</a>.</sub>

**Comment by alikon** [comment]
sorry but  this `wbs_autologin` is not a core plugin

**Comment by RobertPHeller** [comment]
OK, disabling that extension fixes things.  Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10209">issues.joomla.org/tracker/joomla-cms/10209</a>.</sub>
