### ISSUE TITLE
en-GB County -State or Province language inconsistency

### ISSUE THREAD

**Issue by Twincarb** [joomla/joomla-cms#10204]
#### Steps to reproduce the issue
com_contact
location can be selected as "State or Province" 

#### Expected result
location can be selected as "County" 

#### Actual result
"State or Province" 

#### System information (as much as possible)
J3.5.1 + loads of extensions

#### Additional comments
Rather than ploughing ahead and proposing a PR to correct the language strings is there a logical reason for using the en-US language instead of the correct en-GB.

**Comment by andrepereiradasilva** [comment]
> correct en-UK
you mean en-GB, right?

**Comment by Twincarb** [comment]
Yeah en-GB I speak it but don't always know what it's called!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10204">issues.joomla.org/joomla-cms/10204</a>.</sub>

**Comment by infograf768** [comment]
This the kind of issues we can't really solve.
The language used in the UI does not specially means the country in which it is used, as contacts may live anywhere.
In France, it would not be County, State or Province <b> for the address of someone living in France</b> but "Departement".
But why would I limit my contacts to someone living in France?

**Comment by brianteeman** [comment]
Agree

If we added County then where do we stop

On 3 May 2016 at 11:23, infograf768 <notifications@github.com> wrote:

> This the kind of issues we can't really solve.
> The language used in the UI does not specially means the country in which
> it is used, as contacts may live anywhere.
> In France, it would not be County, State or Province * for the address of
> someone living in France* but "Departement".
> But why would I limit my contacts to someone living in France?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10204#issuecomment-216489176>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Having discussed this with some of the en-GB working group we agree that technically it should have always been county but realistically as this is something that has been this way for 10 years and changing it would effect the frontend of an existing web site we have decided not to change this string. A site owner can already create an override if it is relevant to their site.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10204">issues.joomla.org/joomla-cms/10204</a>.</sub>
