### ISSUE TITLE
Admin: 500 Error when not logged in and calling json view

### ISSUE THREAD

**Issue by mahagr** [joomla/joomla-cms#10212]
#### Steps to reproduce the issue

Log out and enter to ```administrator/index.php?option=com_xxx&format=json``` (GET or POST)

Note: Component and view doesn't need to exist as the request gets intercepted by Joomla.

#### Expected result

401 Unauthorized

#### Actual result

500 View not found [name, type, prefix]: login, json, loginView

#### Additional comments

Result should be the same for all non-html views (or as long as loginView doesn't exist).

**Comment by mbabker** [comment]
Believe it or not 401 is NOT the expected result because you've gotten past all the redirects and ACL checks at that point and Joomla is trying to give the user a login page.  And considering Joomla's error handling layer barely handles HTML requests, can't say I'm surprised non-HTML gives something "broken".

**Comment by mahagr** [comment]
I know how it works, I just think there should be some error catching in login controller to send out different response. After all it is unauthorized request which cannot be handled by login component.

**Comment by mahagr** [comment]
How about something like this?

	public function display($cachable = false, $urlparams = false)
	{
		/*
		 * Special treatment is required for this component, as this view may be called
		 * after a session timeout. We must reset the view and layout prior to display
		 * otherwise an error will occur.
		 */
		$this->input->set('view', 'login');
		$this->input->set('layout', 'default');

		try 
		{
			parent::display();
		}
		catch (Exception $e)
		{
			if (!strpos($e->getMessage(), 'loginView'))
			{
				throw $e;
			}
			
			throw new RuntimeException(JText::_('JERROR_ALERTNOAUTHOR'), 401);
		}
	}

**Comment by mbabker** [comment]
The display task can't do anything useful (login/logout could conceivably).  A fix though IMO shouldn't be limited to com_login (maybe if you want to change the error code it'd need to be).  Globally you have this issue with all components and throwing a 500 view not found message when it should probably be 404, at least that would be a more correct code for the condition.  And even by the HTTP spec 403 would be the preferred code.

I would not suggest string parsing the exception message here.  If the checked conditions of the string change, it changes the required checks.  If you really want this one case to change, I'd say check the request format and throw your exception before calling the parent display method.

**Comment by mahagr** [comment]
You're right, this would be much better:

	public function display($cachable = false, $urlparams = false)
	{
		/*
		 * Special treatment is required for this component, as this view may be called
		 * after a session timeout. We must reset the view and layout prior to display
		 * otherwise an error will occur.
		 */
		$this->input->set('view', 'login');
		$this->input->set('layout', 'default');

		// For non-html formats we do not have login screen, so just display 403 instead
		if ($this->input->get('format', 'html') !== 'html') {
			throw new RuntimeException(JText::_('JERROR_ALERTNOAUTHOR'), 403);
		}

		parent::display();
	}

**Comment by mahagr** [comment]
I wouldn't display 404 code when user hasn't been logged in. All components already show 403 if you do not have permissions to access them, regardless if the view/task exists or not.

**Comment by mbabker** [comment]
Globally IMO a 500 code for controller/view not found isn't right and a 404
should be returned.  com_content doesn't support JSON views; a 404 would
better communicate that than 500 which should mean a server error.  Also
globally HTML error pages shouldn't be the error response format but that's
a B/C breaking refactoring for another year.

**Comment by mahagr** [comment]
Oh yes, I must be sleeping as I didn't pay attention that the response was really 500 -- I was just thinking this one case as 404 would be wrong for unauthorized, too.

I agree that globally 500 response is wrong and 404 would be the correct response as those are really pages which do not exist. I also think that its a bug and not API change...

But what about the above change? Its really confusing for users to start getting 500 errors if their session timed out -- 403 errors would allow me to display proper message instead of just displaying the error.

**Comment by mbabker** [comment]
Eh, that'd work.

**Comment by wilsonge** [comment]
If the issue is just that we don't have a json view for that page - then I think it is supposed to be a 415 Unsupported Media Type status?

**Comment by mahagr** [comment]
I think it should be consistent with all the components. Each component starts with 403 error check if you don't have access to them -- regardless if the view exists/is supported or not. The only exception is the login screen which appears to the guests, but as login is only supported with html, I would still return 403, which would happen if login didn't intercept the request.

The best reason for returning either `403` is that it can then properly be handled inside the client which is making that request. Any other code wouldn't make any sense because of it changes the behaviour of the application. Why would the same request first return `200 OK` and after 15 minutes `415 Unsupported`? It just doesn't make any sense from the application point of view. 

I'll fin some time to implement this in a few days.

**Comment by mahagr** [comment]
There is now pull request from this issue.

**Comment by zero-24** [comment]
Set to "closed" on behalf of @zero-24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10212">issues.joomla.org/joomla-cms/10212</a>

**Comment by zero-24** [comment]
PR is: https://github.com/joomla/joomla-cms/pull/10888 Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10212">issues.joomla.org/joomla-cms/10212</a>.</sub>
