### ISSUE TITLE
[Tag] urls field expand after each save

### ISSUE THREAD

**Issue by Mouchachnuk** [joomla/joomla-cms#10211]
#### Steps to reproduce the issue
Create a new tag then save it (keep the tag open, dont save and close)
Check the urls field, you get "{}"
Save the tag again without any modification
Check the urls field, you get "{"0":"{}"}"
Save again
Check the urls fiels, you get "{"0":"{\"0\":\"{}\"}"}"

After multiple save, you get "{"0":"{\"0\":\"{\\\"0\\\":\\\"{\\\\\\\"0\\\\\\\":\\\\\\\"{\\\\\\\\\\\\\\\"0\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"{\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"0\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"{}\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"}\\\\\\\\\\\\\\\"}\\\\\\\"}\\\"}\"}"}"

#### System information (as much as possible)
Joomla 3.5.1

**Comment by brianteeman** [comment]
Thank you for reporting this but it has already been fixed (#9574) and will be in the next release 3.6
