### ISSUE TITLE
 Cannot open file for writing log when Loggin into the Joomla 3.4 Admin area

### ISSUE THREAD

**Issue by leslieongit** [joomla/joomla-cms#10222]
#### Steps to reproduce the issue

Go to administrator area, use correct login username and password.

#### Expected result

An error has occurred.

0 Cannot open file for writing log 

#### Actual result

Unsuccessful login

#### System information (as much as possible)

An error has occurred.

0 Cannot open file for writing log 
Return to Control Panel Button but redirects to login to administrator page.

#### Additional comments

Running on Joomla 3.4, YouJoomla template

**Comment by brianteeman** [comment]
Please use the forum for support on your web site http://forum.joomla.org

**Comment by leslieongit** [comment]
Thanks
