### ISSUE TITLE
Missing options for "remove ID" from URL

### ISSUE THREAD

**Issue by radik10** [joomla/joomla-cms#10258]
![screen shot 2016-05-06 at 03 22 20](https://issues.joomla.org/uploads/1/810e0bea1ba90178aa80d7bf459884a9.jpg)#### Steps to reproduce the issue
install latest Joomla - in article options is missing parameter to "turn on/off" ID from sef links in URL

#### Expected result
see attached image
founded from: http://developernote.com/2012/05/how-to-remove-id-from-url-in-joomla-2-5/ - it will be great SEO help!!!

#### Actual result
missing parametters

#### System information (as much as possible)
J 3.5.1, PHP 5.4.4

#### Additional comments
code to add in to the "**administrator\components\com_content\config.xml**" :
<field name="sef_advanced_link"
    type="radio"
    default="0"
    label="Sef Advanced Mode"
    description="Remove ItemID from Content URL?">
        <option    value="0">JNO</option>
        <option    value="1">JYES</option>
</field>
+ add localization strings in to the language *.ini files

**Comment by brianteeman** [comment]
This is intended behaviour and this advanced behaviour will be present in Joomla 3.7

**Comment by radik10** [comment]
hi, this issue with numbers in URL (for articles in blog) is since Joomla 1.5 - now is J. 3.5 and you want to wait till Joomla 3.7. J 3.7 will be ready in 1-2 years - it is a long time for such small change... There are many complainers to this behavior of Joomla (numbers in blog articles in URL).Look at Wordpress - there is much bigger progress in adding new stuff in to the CMS - why is Joomla so slow (in adding new stuff)? Code is ready to use, why to wait? Thanks for reconsideration.
Regards
Radovan 

    On Friday, May 6, 2016 10:28 AM, Brian Teeman <notifications@github.com> wrote:
 

 Closed #10258.—
