### ISSUE TITLE
The most recent request was denied because it contained an invalid security token.

### ISSUE THREAD

**Issue by Orsey** [joomla/joomla-cms#10255]
#### Steps to reproduce the issue

Login to site or admin
Wait until the end of the session
Reload page, and automatic get to the login page
Try login

#### Expected result

Log on website

#### Actual result
 Get empty page with text:

"The most recent request was denied because it contained an invalid security token. Please refresh the page and try again."

or

"РџРѕСЃР»РµРґРЅРёР№ Р·Р°РїСЂРѕСЃ Р±С‹Р» РѕС‚РєР»РѕРЅС‘РЅ, РїРѕСЃРєРѕР»СЊРєСѓ РѕРЅ СЃРѕРґРµСЂР¶РёС‚ РЅРµРїСЂР°РІРёР»СЊРЅС‹Р№ РїР°СЂР°РјРµС‚СЂ Р±РµР·РѕРїР°СЃРЅРѕСЃС‚Рё (security token). РџРѕР¶Р°Р»СѓР№СЃС‚Р°, РѕР±РЅРѕРІРёС‚Рµ СЃС‚СЂР°РЅРёС†Сѓ Рё РїРѕРїСЂРѕР±СѓР№С‚Рµ РµС‰Рµ СЂР°Р·."

#### System information (as much as possible)

The platform on which works PHP Linux s14.thehost.com.ua 3.13.0-83-generic # 127 ~ precise1-Ubuntu SMP Fri Mar 11 12:53:08 UTC 2016 x86_64
The database version 5.6.29
Database coding utf8_general_ci
Encoding database connection utf8mb4_general_ci
Version PHP 5.3.10-1ubuntu3.22
Apache Web Server
The interface between the web server and PHP apache2handler
Joomla version! Joomla! 3.5.1 Stable [Unicorn] 05-April-2016 22:45 GMT
Joomla version! Platform Joomla Platform 13.1.0 Stable [Curiosity] 24-Apr-2013 00:00 GMT
The user's browser Mozilla / 5.0 (Windows NT 10.0; WOW64) AppleWebKit / 537.36 (KHTML, like Gecko) Chrome / 50.0.2661.94 Safari / 537.36

#### Additional comments

How can I skip the blank screen and no sign of this error?

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10255">issues.joomla.org/joomla-cms/10255</a>.</sub>

**Comment by Orsey** [comment]
So, this is no problem of Joomla? Is this my personaly problem?

**Comment by omikron** [comment]
Don't think so, we have been having this issue on all our sites that have been upgraded to 3.5.1.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10255">issues.joomla.org/joomla-cms/10255</a>.</sub>

**Comment by roland-d** [comment]
If you are using caching on your site, disable the page cache plugin. You should no longer have this issue. Let me know if that is the case for you.

**Comment by omikron** [comment]
Yes disabling cache fixes the issue, but obviously not an optimal fix.

Is something broke with the joomla cache plugin?

**Comment by roland-d** [comment]
@omikron Did you disable the general cache setting or just the page plugin? You said you are having the issue on all your upgraded sites. That is no longer the case?

**Comment by roland-d** [comment]
A little update on this, using the current staging codebase, I can no longer reproduce this so it looks to me fixed for the next release.
