### ISSUE TITLE
Validation JS does not validate all form fields if placed outside FORM tag and it can try to validate fields of other forms if inside the FORM Tag

### ISSUE THREAD

**Issue by ggppdk** [joomla/joomla-cms#10259]
#### Steps to reproduce the issue
```
<form ... id="form-id-1" class="form-validate"/>
  <input form="form-id-2"   type="text" name="jform_field_a" class="required" />
  ...
</form>

<input  form="form-id-1"   type="text" name="jform_field_b" class="required" />
```

#### Expected result
Field:  jform_field_a **is not included** in the validation
Field:  jform_field_b **is included** in the validation

#### Actual result
Neither of the above is happening

#### System information (as much as possible)
any

**Comment by ggppdk** [comment]
I found when bug was introduced:

This commit had replaced mootools code with jQuery code
https://github.com/joomla/joomla-cms/commit/763c69f4bedc38f62ddf4f04af9d3d7fe3f3a719

But also the old mootools code:
```
var elements = form.getElements('fieldset').concat(Array.from(form.elements));
```

was replaced with this code that introduced the bug:
```
$(form).find('input, textarea, select, fieldset, button')
```

correct one would be:
```
$(form).find('fieldset').toArray().concat(Array.from(form.elements));
```

**Comment by ggppdk** [comment]
As i said above 
- the commit that replaced mootools code for selecting form fields with jQuery code

**is simply not equivalent**

This PR fixes the issue that was introduced by mootools removal commit:

https://github.com/joomla/joomla-cms/pull/10136

**Comment by brianteeman** [comment]
@dgt41 could you take a look at this please<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10259">issues.joomla.org/joomla-cms/10259</a>.</sub>

**Comment by dgt41** [comment]
I am gonna make a pr with vanilla validation.js and will use @ggppdk code from the comment above. 
The idea is to allow html5 pattern tag to be used wherever is set.
Also fix the current jquery version although I think we just replace it with native code. Validation is not doing something extraordinary to need jquery.

**Comment by ggppdk** [comment]
I am using this to get all form elements
```
$form.find('fieldset').toArray().concat(Array.from(form.elements)) ;
```

Also to get elements on specific container that is added at runtime i am using:

```
	attachToForm = function(form, container)
	{
 	 	var inputFields = [], elements,
 	 		$form = jQuery(form);
		
		var elements = typeof container !== 'undefined' && container ?
			jQuery(container).find('input, textarea, select, fieldset, button').toArray() :
			$form.find('fieldset').toArray().concat(Array.from(form.elements)) ;
```

**Comment by ggppdk** [comment]
@dgt41 

Currently how do you attach validation to form fields added by JS during user actions ?

i need to override 
attachToForm()
in order to do it, see the "container" parameter which is the place at which new form elements were added

**Comment by dgt41** [comment]
I am on my mobile right now but if I remember correctly all you have to do is push the new elements to the relative (form) array. I don't think it's tricky

**Comment by dgt41** [comment]
Also if the events part of https://github.com/joomla/joomla-cms/pull/11378 are available then validation can be triggered on each field as the users enters data, which will improve the UX/UI a lot (think of a green tick or a red x depending on the validity of the entered data, in real time)

**Comment by ggppdk** [comment]
About IE8 / IE9 and early versions of IE10 not supporting the form="..." attribute 

i am placing the elements back into 
```
<form>
</form>
```
 before submiting, so submiting works for them too

Also it is ok if for these browsers (IE8 / IE9 and ?early? versions of IE10) if validation does not work for fields that use form="..." attribute and are placed outside of  FORM tag

just now it does not work for any other browsers (which are 96%)

i am just calling for an improvement for the future,

- luckily Joomla allows overriding the validation JS , so this is not a problem for me,

i am just calling for an improvement for the future

**Comment by franz-wohlkoenig** [comment]
> I am gonna make a pr with vanilla validation.js

@dgt41 is a PR coming?

**Comment by dgt41** [comment]
Check https://github.com/joomla/joomla-cms/blob/4.0-dev/media/system/js/fields/validate.js

**Comment by franz-wohlkoenig** [comment]
@dgt41 thanks for Info about Joomla! 4.0

**Comment by franz-wohlkoenig** [comment]
@dgt41 can this Issue be closed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10259">issues.joomla.org/tracker/joomla-cms/10259</a>.</sub>

**Comment by brianteeman** [comment]
closed due to lack of response
