### ISSUE TITLE
Contents  > Articles > Search tools issues (windows 8.1 / chrome)

### ISSUE THREAD

**Issue by jhumez** [joomla/joomla-cms#10265]
#### Steps to reproduce the issue
Log in in the backoffice
Go to the Contents > Articles page
Click on the Search tools button.

#### Expected result
The fields status, category, tags, ... should appears

#### Actual result
The fields does not appears

#### System information (as much as possible)
OS: Windows 8.1
Browser: Chrome 50.0.2661.94 m

#### Additional comments
With another computer with XP OS and windows 10 OS it worked

**Comment by andrepereiradasilva** [comment]
Using latest staging in Windows 10 or Windows 7 on Chrome 50 works fine.

Don't have windows 8.1 to test.

**Comment by JoomliC** [comment]
@jhumez on which joomla version? 3.5.1 or latest staging version?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10265">issues.joomla.org/joomla-cms/10265</a>.</sub>

**Comment by widmann-it** [comment]
Using latest staging in Windows 10 or Windows 8.1 on Chrome 50.0.2661.94  (64 Bit)  works

**Comment by brianteeman** [comment]
Please use the forum for support on your site as this has not been able to be replicated. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10265">issues.joomla.org/joomla-cms/10265</a>.</sub>
