### ISSUE TITLE
com_finder (smartsearch) untranslated filters

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#10260]
#### Steps to reproduce the issue
Load another language than English in back-end.
Go to Smartsearch Indexed Content equivalent page
The equivalent filter "- Select type of content -" displays the filter types in English

![screen shot 2016-05-06 at 10 42 16](https://cloud.githubusercontent.com/assets/869724/15068390/40d0488e-1377-11e6-857a-b730fdc3fae8.png)

from field
```
		<field
			name="type"
			type="sql"
			label="JOPTION_FILTER_CATEGORY"
			description="JOPTION_FILTER_CATEGORY_DESC"
			default="0"
			query="SELECT id AS value, title AS type FROM #__finder_types ORDER BY title"
			onchange="this.form.submit();"
			>
			<option value="">COM_FINDER_MAPS_SELECT_TYPE</option>
		</field>
```
I Purged the db and re-indexed with another language loaded. It did not delete the `_finder_types` table and no change to the filters.
Same after deleting the `_finder_types` table and reindexing. The english values are re-added to the table.

Similar issue for "- Select Branch -" in the Content Maps page

@chrisdavenport

**Comment by andrepereiradasilva** [comment]
Please test https://github.com/joomla/joomla-cms/pull/10263

**Comment by infograf768** [comment]
Closing as we have 2 PRs to test.
