### ISSUE TITLE
SimplePie Update Incomplete

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#10280]
The following steps are still required after the SimplePie update to a Composer managed dependency:

- Removal of the SimplePie library extension from the database (new install and update)
- Removal of the SimplePie library extension's manifest
- Deleting `libraries/simplepie` on update

**Comment by zero-24** [comment]
Set to "closed" on behalf of @zero-24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10280">issues.joomla.org/joomla-cms/10280</a>

**Comment by zero-24** [comment]
see: #10285 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10280">issues.joomla.org/joomla-cms/10280</a>.</sub>
