### ISSUE TITLE
Cannot add web installer

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#10297]
#### Steps to reproduce the issue

Go to Extensions -> Manage (Install)
Click "Add "Install from Web" tab"

#### Expected result

Install from web plugin installed

#### Actual result

Error
Unable to find install package

#### System information (as much as possible)

latest staging

#### Additional comments

Probably related:
- https://github.com/joomla/joomla-cms/commit/c52e0d2ea90b9a73ac224d757a23add064f94e00

@wilsonge

**Comment by mbabker** [comment]
Part of it probably comes from the fact that their [XML manifest](http://appscdn.joomla.org/webapps/jedapps/webinstaller.xml) only targets 3.5 with their latest release.

**Comment by andrepereiradasilva** [comment]
you're right (again...)

Just used bump.php to "dowgrade" to 3.5.0 and now it installs.

So gone close this.
