### ISSUE TITLE
Regression installer

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#10309]
George broke the web again

**Comment by wilsonge** [comment]
https://twitter.com/GW1992/status/729272888692453376 I got there first

**Comment by brianteeman** [comment]
Resolved by reverting #10309<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10309">issues.joomla.org/joomla-cms/10309</a>.</sub>
