### ISSUE TITLE
RFC - Remove testing data from distribution

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#10330]
There really is no good reason to include the testing sample data in the released version of joomla - it only has a purpose and use during the staging lifecylcle

It is fairly trivial to add the testing sample data to the list of files excluded from a build if people agree.

**Comment by andrepereiradasilva** [comment]
i agree, also another suggestion. sample data should not create things that are already created by joomla.sql. ex: the component menu.

**Comment by mbabker** [comment]
I'd rather see the sample data (hell, joomla.sql too) rewritten to not be static SQL dumps.  But hey, a guy can dream...

**Comment by andrepereiradasilva** [comment]
that would be even greater.

**Comment by chrisdavenport** [comment]
+1 (especially as it's been on our roadmap for a while now: https://developer.joomla.org/cms/roadmap.html)

**Comment by brianteeman** [comment]
Until someone actually does it words are great but don't change anything.
It's at least 6 months since PLT said someone said they were doing that. In
the meantime I can do this PR in ten minutes.

**Comment by chrisdavenport** [comment]
The PLT roadmap is only asking for the 10 minute PR.  We can do the clever stuff another day. :-)

**Comment by brianteeman** [comment]
I guess I misread the minutes of the meeting in Germany.

**Comment by zero-24** [comment]
see: https://github.com/joomla/joomla-cms/pull/10364

**Comment by zero-24** [comment]
Set to "closed" on behalf of @zero-24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10330">issues.joomla.org/joomla-cms/10330</a>

**Comment by zero-24** [comment]
Closing as we have a PR here https://github.com/joomla/joomla-cms/pull/10364<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10330">issues.joomla.org/joomla-cms/10330</a>.</sub>

**Comment by Bakual** [comment]
Actually, I did a PR once to make the sample data an after installation process using an admin module, a plugin per sample set and com_ajax (https://github.com/joomla/joomla-cms/pull/7680). It was working with testing data, the others would still have to be done.
Reason it stopped was that with the upcoming webservice layer this would become simpler, which I agree to a degree.
