### ISSUE TITLE
Please allow sorting of articles by modification date

### ISSUE THREAD

**Issue by lanoxx** [joomla/joomla-cms#10355]
#### Steps to reproduce the issue

1. Login to the Administrator component
2. Go to *Content->Articles*
3. Notices that there is only a column named 'Date' which corresponds to the creation date of each article.

#### Expected result

There should be another column with the modification date.

#### Actual result

No column with modification date is present. Sorting articles by the last modification date is not possible.

#### System information (as much as possible)

I am using Joomla 3.5.1.

#### Additional comments

This feature would be useful to see which articles have been modified recently, currently I need to open each article and look at the modification date.

**Comment by BurtNL** [comment]
Good request +1!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10355">issues.joomla.org/joomla-cms/10355</a>.</sub>

**Comment by izharaazmi** [comment]
In my custom components I use modified / created in the same column which looks like this:
![image](https://cloud.githubusercontent.com/assets/6706189/15212833/b6be8874-1860-11e6-92bd-e7d9d2aee934.png)

Sortable by either created date or modified date from the *sort by* dropdown list. Column header click always sorts by modified date. May be this can be implemented in Joomla core components too with little or no modifications!

Please suggest!

**Comment by BurtNL** [comment]
Looks good, would be nice to have in Joomla!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10355">issues.joomla.org/joomla-cms/10355</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a Pr for testing #11014<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10355">issues.joomla.org/joomla-cms/10355</a>.</sub>
