### ISSUE TITLE
Regression: Install Languages may be broken on some sites

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#10352]
Go to the page: administrator/index.php?option=com_installer&view=languages

Click on the button "Find Languages"

The page may remain empty on a manually updated site to last staging, even after database fix.

This is due to this update sql: ROOT/administrator/components/com_admin/sql/updates/mysql/3.6.0-2016-04-08.sql
```
INSERT INTO `#__extensions` (`extension_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `custom_data`, `system_data`, `checked_out`, `checked_out_time`, `ordering`, `state`)
 VALUES (801, 'English (United Kingdom)', 'package', 'pkg_en-GB', '', 0, 1, 1, 1, '', '', '', '', 0, '0000-00-00 00:00:00', 0, 0);

-- Change update site extension id to the new extension.
UPDATE `#__update_sites_extensions` SET `extension_id` = 801 WHERE `update_site_id` = 3 AND `extension_id` = 600;
```
On one of my sites the id 801 was used by the weblinks package:

![screen shot 2016-05-09 at 12 42 52](https://cloud.githubusercontent.com/assets/869724/15110863/b52eee4c-15e3-11e6-9489-511fd7fe7549.png)

I suggest to NOT at least change  the id 600 to 801 in _update_sites_extensions

**Comment by andrepereiradasilva** [comment]
we can use 802.

**Comment by andrepereiradasilva** [comment]
i will change it to 802 id

**Comment by infograf768** [comment]
why not keep 600? it is fishing for issues when changing this id. it is not necessry to change imho

**Comment by andrepereiradasilva** [comment]
because is the `pkg_en-GB` extension manifest that has the update site.
See https://github.com/joomla/joomla-cms/blob/staging/administrator/manifests/packages/pkg_en-GB.xml#L22

**Comment by andrepereiradasilva** [comment]
PR https://github.com/joomla/joomla-cms/pull/10353

**Comment by zero-24** [comment]
Set to "closed" on behalf of @zero-24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10352">issues.joomla.org/joomla-cms/10352</a>

**Comment by zero-24** [comment]
Closing as we have a PR #10353 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10352">issues.joomla.org/joomla-cms/10352</a>.</sub>
