### ISSUE TITLE
Why I can not use "xcache" as session handler?

### ISSUE THREAD

**Issue by baijianpeng** [joomla/joomla-cms#10371]
#### Steps to reproduce the issue

Enter Joomla 3.5.1 backend "Global Configuration -> System  ->  Session Settings", choose "xcache" for Session Handler.

#### Expected result

I can login in and logout as usually and more faster.

#### Actual result

I can login in Joomla backend, but when click on any link or menu, I will be force logout .

#### System information (as much as possible)

Joomla 3.5.1

```
# php56 -v
PHP 5.6.21 (cli) (built: Apr 28 2016 07:07:46)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with XCache v3.2.0, Copyright (c) 2005-2014, by mOo
    with XCache Optimizer v3.2.0, Copyright (c) 2005-2014, by mOo
    with XCache Cacher v3.2.0, Copyright (c) 2005-2014, by mOo
    with XCache Coverager v3.2.0, Copyright (c) 2005-2014, by mOo
```

#### Additional comments

I had already copied xcache.ini content to php.ini of php56.

**Comment by brianteeman** [comment]
I really dont know but please use the forum for support http://forum.joomla.org
