### ISSUE TITLE
"Display in Menu" option not working on live site

### ISSUE THREAD

**Issue by bloominari** [joomla/joomla-cms#10372]
#### Steps to reproduce the issue
1. I login to my Joomla Menu Admin (Version 3.5.1)
2. I clear my Joomla Cache, my browser cache, and all other cache
3. I choose a menu item, and go to the tab called "Link Type", and select NO under "Display in Menu"

Link that shows what happens here: http://screencast-o-matic.com/watch/cDh6ne1PDW

#### Expected result
1. To NOT see my Menu item that I chose to NOT display on the menu
2. After clearing cache, I still see my menu items.

Feel free to contact me at @bloominari on gitterhub (github chat)

Jaime Nacach
Bloominari.com

**Comment by bloominari** [comment]
UPDATE: Please note that I'm using the Helix 2 Framework on my site, and in order to fix this issue temporarily, and be able to actually hide my menus (without un-publishing the item, so people can still see the page IF they have the URL, but can no longer browse the page via the menu) I applied a custom CSS class called "hidden" to the menu item (under the "Helix Megamenu options").

The CSS class is
`.hidden {display: none !important;} /* For hiding any elements you don't want to see */`

Once this class is applied on the backend under the Helix options, the item no longer shows on my menu.

Yet, I would prefer to simply use Joomla's 3.5.1 new feature, an not apply this CSS class.

See screenshot for reference.

![screen shot 2016-05-09 at 7 39 41 pm](https://cloud.githubusercontent.com/assets/14933286/15134124/19e1cabe-161e-11e6-83cc-74179af1fd49.png)

**Comment by bloominari** [comment]
Just realized that adding this "custom class" via Helix 2 framework, also applied the CSS class to the <body> tag of the actual pages, and thus all my content on each hidden menu item's related page (article) was also hidden... 

Thus, I had to remove this "hidden" class, and I'm back to square one (trying to figure out how to "hide" some menu items, without un-publishing, and without any other methods).

**Comment by brianteeman** [comment]
This is a problem with the helix framework and not a problem with joomla.

**Comment by brianteeman** [comment]
I am closing this as it is not an issue with Joomla but with the Helix framework and you should report the issue to the makers of Helix<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10372">issues.joomla.org/joomla-cms/10372</a>.</sub>

**Comment by bloominari** [comment]
Thanks for letting me know :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10372">issues.joomla.org/joomla-cms/10372</a>.</sub>
