### ISSUE TITLE
Regresssion: escape does not work anymore in lang strings when bootstrap.addTab is used

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#10381]
Everywhere where we have a code like (90 instances in core)
```
echo JHtml::_('bootstrap.addTab', 'myTab', 'folder', JText::_('PLG_INSTALLER_FOLDERINSTALLER_TEXT', true));
```
`true` is supposed to escape the strings and not show the escape.
See https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/language/text.php#L44
It does not anymore.
I get here:
![screen shot 2016-05-10 at 13 03 50](https://cloud.githubusercontent.com/assets/869724/15144443/bc3bedd0-16af-11e6-8747-0884a3e75822.png)

If I take off the `true`, it works again.

**Comment by infograf768** [comment]
It looks like it is limited to the "bootstrap.addTab" usage.

**Comment by brianteeman** [comment]
So thats great we can remove the "true" functionality<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10381">issues.joomla.org/joomla-cms/10381</a>.</sub>

**Comment by infograf768** [comment]
OK, will do for all the instances

**Comment by infograf768** [comment]
Closing as we have a patch

https://github.com/joomla/joomla-cms/pull/10389<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10381">issues.joomla.org/joomla-cms/10381</a>.</sub>
