### ISSUE TITLE
When I choose "memcached" as cache handler, my Joomla turns slower

### ISSUE THREAD

**Issue by baijianpeng** [joomla/joomla-cms#10398]
#### Steps to reproduce the issue

My VPS is CentOS 7 64-bit. So I installed memcached via following command:

`yum install php56-php-memcached --enablerepo=remi`

Then I see "memcached" appear on the drop-down list of "Cache Handler" parameter in Joomla backend Global Configuration. So I choose it as cache handler. Other settings like port etc, all kept as the default values.

#### Expected result

I hope this will make my website faster.

#### Actual result

Then after several hours I noticed that my website turns slower.
Well, I switched back to "file" method as the cache handler, the website recovered, faster.

#### System information (as much as possible)

Apache version: 2.4.6
Joomla core version: 3.5.1
PHP version: 5.6.21
memcached version: 2.2.0
libmemcached version: 1.0.16

#### Additional comments

Maybe I did not install the correct "memcached" version? I noticed that there is also another "memcached" on http://memcached.org/, that version is 1.4.25. From the version number I know they are different "memcached".

So, which one is the correct "memcached" for Joomla cache handler?

Thank you.

**Comment by brianteeman** [comment]
I really dont know but please use the forum for support

**Comment by mbabker** [comment]
Also related is #9898

And yes, 2.2.0 is the latest PECL Memcached version.
