### ISSUE TITLE
Notice when JModelList call getFilterForm before populating model state

### ISSUE THREAD

**Issue by Devportobello** [joomla/joomla-cms#10416]
#### Steps to reproduce the issue
Edit file: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/views/articles/view.html.php#L43
Move ```$this->filterForm = $this->get('FilterForm');```
before ```$this->items = $this->get('Items');```

Administrator side:
Configuration > Error Reporting: System default or Maximum or Development
Then Articles listing

Will throw:
```Notice: Undefined property: JObject::$list.direction in PathTo\Joomla_3_5_1\libraries\legacy\model\list.php on line 453```
```Notice: Undefined property: JObject::$list.limit in PathTo\Joomla_3_5_1\libraries\legacy\model\list.php on line 454```
```Notice: Undefined property: JObject::$list.ordering in PathTo\Joomla_3_5_1\libraries\legacy\model\list.php on line 455```
```Notice: Undefined property: JObject::$list.start in PathTo\Joomla_3_5_1\libraries\legacy\model\list.php on line 456```

#### System information (as much as possible)
Joomla 3.5.1

**Comment by schnuti** [comment]
@Devportobello 
As I understand your post, it's ok as it is and you get notices if you modify.it? Or the oppisite?

I*ve tested around a lot with error message level set to show noticces lately. Have not seen this.

**Comment by Devportobello** [comment]
Actually it's ok
I noticed this in 1 of my third component who call [filterForm](https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/model/list.php#L347-L369) before calling -eg- [getItems](https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/model/list.php#L169-L198) ...
So, calling filterForm before [populating state](https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/model/list.php#L479)

**Comment by schnuti** [comment]
So everything ok then?
You were lucky to find the notices. 
If you don't call populateState before filterForm and getItems , I'm pretty sure that both will fail to show correct data.  With or without notice

Maybe you could try to find a general way to call  populateState for the listviews, if it's not yet called, Otherwise you could override the methods in your own code.

I think I'm right.

**Comment by Devportobello** [comment]
> If you don't call populateState before filterForm and getItems , I'm pretty sure that both will fail to show correct data. With or without notice

Dont agree :) but maybe i missing something

[getItems](https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/model/list.php#L185) will call [getState](https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/model/legacy.php#L439) to [populate state](https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/model/list.php#L467)
When filterForm never populate state before [loading form data](https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/model/list.php#L452-L457)

**Comment by schnuti** [comment]
Yes, you are right. Sorry.

`		// Get a storage key.
		$store = $this->getStoreId();
`
Makes the trick in my code.
And filterForm doesn*t call populateState.

**Comment by wilsonge** [comment]
Closed as we have a PR in #10435

**Comment by patricmutwiri** [comment]
I've tried getting rid of that error by interchanging the position of `$this->filterForm    	= $this->get('FilterForm');` and `$this->items			= $this->get('Items');` and still nothing.
