### ISSUE TITLE
Error in joomla.org and other site's with Joomla 

### ISSUE THREAD

**Issue by TalosDx** [joomla/joomla-cms#10419]
#### Steps to reproduce the issue
1. Go to any page.
2. Then replace .html on any characters
example 
before
https://www.joomla.org/core-features.html
after
https://www.joomla.org/core-features.htwfa

Error 500 or(error with my site
Fatal error: Uncaught Exception: Представление не найдено [name, type, prefix]: profile, awg, usersView in /home/www/site/ba/libraries/legacy/controller/legacy.php:885 Stack trace: #0 /home/www/site/ba/components/com_users/controller.php(39): JControllerLegacy->getView('profile', 'awg') #1 /home/www/site/ba/libraries/legacy/controller/legacy.php(728): UsersController->display() #2 /home/www/site/ba/components/com_users/users.php(15): JControllerLegacy->execute('display') #3 /home/www/site/ba/libraries/cms/component/helper.php(405): require_once('/home/www/site/...') #4 /home/www/site/ba/libraries/cms/component/helper.php(380): JComponentHelper::executeComponent('/home/www/site/...') #5 /home/www/site/ba/libraries/cms/application/site.php(191): JComponentHelper::renderComponent('com_users') #6 /home/www/site/ba/libraries/cms/application/site.php(230): JApplicationSite->dispatch() #7 /home/www/site/ba/libraries/cm in /home/www/site/ba/libraries/legacy/controller/legacy.php on line 885![screen shot 2016-05-11 at 09 01 22](https://issues.joomla.org/uploads/1/e0d8521218b32ab2058396ce4c58b372.png)

#### Additional comments

![screen shot 2016-05-11 at 09 01 22](https://issues.joomla.org/uploads/1/298a5f975ab0bddace3ae0d9fb733dc0.png)

**Comment by andrepereiradasilva** [comment]
Cannot reproduce this in latest staging.

/test-page.html (article page that exists) = OK

/test-page.hdsklfjlsdfsdf = 404 error
![image](https://cloud.githubusercontent.com/assets/9630530/15183640/d2790a4e-1789-11e6-9d85-5dd4eeb6a5a9.png)

**Comment by andrepereiradasilva** [comment]
And in profile to be more in line with your test
![image](https://cloud.githubusercontent.com/assets/9630530/15183792/8ea77782-178a-11e6-9dd0-4da0bf3fcd16.png)

**Comment by mbabker** [comment]
If you're getting an uncaught exception then something is unregistering the core global exception handler or you've been hacked.  The error message is 100% correct (even if it's not "user friendly").

**Comment by andrepereiradasilva** [comment]
joomla.org has a 500 error https://www.joomla.org/core-features.htwfa

**Comment by mbabker** [comment]
Because `mod_search` is rendered on the error page and it tries calling `$doc->addHeadLink()` which doesn't exist on anything but an HTML object.  So the error page throws an error there.

**Comment by andrepereiradasilva** [comment]
oh ... the error page "thing" again :)

**Comment by mbabker** [comment]
Reason 5214890 why I hate Joomla's error handling layer 😉

**Comment by TalosDx** [comment]
How fixed this bug? See link: https://www.joomla.org/core-features.htwfa
This it's fixed, but how?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10419">issues.joomla.org/joomla-cms/10419</a>.</sub>

**Comment by mbabker** [comment]
There isn't a core fix.  In the case of `joomla.org` we changed to using Smart Search (mod_finder) instead of "legacy" search (mod_search) and the former module doesn't have a `JDocument` call like the latter does (in part because that feature was never fully implemented for some reason).

You shouldn't be getting an uncaught exception message.  The fact you are means that the core bootstrap process has been altered or something has overloaded the core exception handler.  Make sure your includes/framework.php and libraries/cms.php files are the correct versions then check for any uses of `set_exception_handler()` or `restore_exception_handler()` in your installation.

For further support, please use the [Joomla! Forum](http://forum.joomla.org).
