### ISSUE TITLE
travis and jenkins are failing

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#10429]
#### Steps to reproduce the issue

See the main repo readme.md

#### Expected result

Travis and jenkins green

#### Actual result

Travis and jenkins failing

#### System information

It looks like that we have a CS issue on the sysinfo.php i can try to have a look if i'm back to a computer ;)

**Comment by JoomliC** [comment]
Line 619 line exceeded 150 characters... Mentionned it in my last PR ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10429">issues.joomla.org/joomla-cms/10429</a>.</sub>

**Comment by wilsonge** [comment]
Fixed

**Comment by zero-24** [comment]
Thanks @wilsonge

**Comment by JoomliC** [comment]
Thanks @wilsonge :+1:
