### ISSUE TITLE
Article icons is not override in template

### ISSUE THREAD

**Issue by Grigory90** [joomla/joomla-cms#10421]
Icon print, email and edit is not iverride in template.
I added PR for fix this problem.

**Comment by brianteeman** [comment]
Where is the PR?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10421">issues.joomla.org/joomla-cms/10421</a>.</sub>

**Comment by Grigory90** [comment]
Added, fix typo...

**Comment by brianteeman** [comment]
Thanks for reporting this - you dont need to create an issue and create a pr - when you create a pr github creates the issue automatically so I can close this and look at the Pr<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10421">issues.joomla.org/joomla-cms/10421</a>.</sub>
