### ISSUE TITLE
Enhancement: possibility to restrict a usergroup to a menuitem

### ISSUE THREAD

**Issue by ggeorgg** [joomla/joomla-cms#10447]
Is it possible to allow a usergroup only to be able to create or modify menuitems under a specific Menuitem as parentitem? 
It is already possible with ACL to allow a usergroup to create and modify articles only in a specific categorie. I would like this feature and I haven't seen anything about how I could realize this. 
Here's an example how I would like to realize it on my site:
Create usergroup with special rights. This usergroup has access to joomla backend and the menu component.
Now here is my menu structure already created by a superuser:
-Menuitem1
-Menuitem2
--Submenuitem1
--Submenuitem2

Now I want my new usergroup to be able to see the whole structure but I want this group only to be able to create or modify subsubmenuitems for example for submenuitem2.

Is this already possible? Or can we make this possible by adding categories to the menuitems like with articles? 

Best regards

**Comment by brianteeman** [comment]
Perhaps with this recent merge https://issues.joomla.org/tracker/joomla-cms/9814

**Comment by infograf768** [comment]
I think #9814 deals only with menutypes and not menu items

**Comment by ggeorgg** [comment]
Infograf is right. I think what I want to do is possible with this merge, but then I would need to split up my big main menu, create a new menu which can be modified by a usergroup. But this is not what I had in mind because I would lose the dependencies in my menu structure like "parent" and "child" menu item.

**Comment by ggeorgg** [comment]
Unfortunately creating this homepage for my local sports club and reading through code is only a hobby for me, so I can't implement this feature but if I can help in another way, please let me know!

**Comment by zero-24** [comment]
Just to be sure you are talking about the backend correct?

**Comment by ggeorgg** [comment]
yes

**Comment by andrepereiradasilva** [comment]
The Menu ACL that will exist in 3.6.0 (thanks to @bembelimen) is estabelished at Menu types level and will "propagate" the same permissions to all menu items inside the menu type.
Not possible yet to override that permission at the menu item level.

PR are welcomed.

**Comment by franz-wohlkoenig** [comment]
@andrepereiradasilva is your Statement above also in 3.7 so i let this Issue open?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10447">issues.joomla.org/tracker/joomla-cms/10447</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened in the future if it is updated.
