### ISSUE TITLE
Menu item edit screen closes to wrong url

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#10458]
#### Steps to reproduce the issue
Menu >>> hover over a menu >>> click to create a menu
Click Cancel or finish creating the menu ... save and click Close

#### Expected result
Page returns to administrator/index.php?option=com_menus

#### Actual result
Page returns to administrator/index.php?option=com_menus&view=items&menutype= with a 403 error 

#### System information (as much as possible)
Tested on live site and xampp localhost

#### Additional comments
If you have (during admin session) already visited administrator/index.php?option=com_menus&view=items&menutype=_menuname_ ... then Cancel or Close will return to that page.  Otherwise it returns to administrator/index.php?option=com_menus&view=items&menutype= with a 403 error![screen shot 2016-05-14 at 07 29 05](https://issues.joomla.org/uploads/1/a569f70a39e33ec89e2638bbe273a438.jpg)

**Comment by andrepereiradasilva** [comment]
confirmed.
@infograf768 the one i talked you about.

**Comment by andrepereiradasilva** [comment]
IMHO we shouldn't use `'*'`  to identify the no menu item selection, just `''` (empty string) like all other filters..

**Comment by Webdongle** [comment]
It used to return to 
administrator/index.php?option=com_menus and displayed the first menu alphabetically.  Now it returns to 
administrator/index.php?option=com_menus&view=items&menutype=
and appends a menu name only if a menu has previously been visited during that login session.

**Comment by andrepereiradasilva** [comment]
@Webdongle please test https://github.com/joomla/joomla-cms/pull/10459

**Comment by andrepereiradasilva** [comment]
Confirmed.
The second *subissue* in this issue (the wrong redirect) already exists in 3.5.1.

**Comment by andrepereiradasilva** [comment]
You check that issue with this:
1. Use 3.5.1
2. Logout from backend
3. Login in the backend
4. Go directly to the admin menu Menus -> Any Menu -> Add new menu item
5 .Notice the URL in the new/edit menu item page (&menutype=xxxxxx)
6. Now press select menu item and select one menu item type and close
7 .Notice the URL in the new/edit menu item page (no &menutype=xxxxxx)

**Comment by andrepereiradasilva** [comment]
ok second PR to solve the redirect issue https://github.com/joomla/joomla-cms/pull/10460

Please test.

**Comment by Webdongle** [comment]
#10460 solves this issue so closed

**Comment by andrepereiradasilva** [comment]
@Webdongle https://github.com/joomla/joomla-cms/pull/10460 doesn't solve the two issues.

Even with https://github.com/joomla/joomla-cms/pull/10460 if you go to `/administrator/index.php?option=com_menus&view=items&menutype=` you get the 403 error.

Thast's why i also created https://github.com/joomla/joomla-cms/pull/10459. Please test.

**Comment by Webdongle** [comment]
@andrepereiradasilva 

Now I am lost ... administrator/index.php?option=com_menus&view=items&menutype= was the url that was reached after clicking Cancel or Close in the menu item.  It was not typed in directly.

When #10460 is applied then clicking Cancel or Close in the menu item returns to administrator/index.php?option=com_menus&view=items&menutype=_menuname_.  That fixes this issue ... the issue never occurred when the 'menu items' on the side bar had been visited.  So to test #10458 prevents this error from happening even before that patch is applied because the test instructions require the 'menu items' on the side bar is visited

However #10460 can be tested without visiting the 'menu items' on the side bar and can be tested for this issue.  I have tested and it fixes this issue.

**Comment by andrepereiradasilva** [comment]
https://github.com/joomla/joomla-cms/pull/10460 fixes this issue itself, because you don't have anymore the `/administrator/index.php?option=com_menus&view=items&menutype=` URL directly on joomla (that i know of). In other words the problem is masked.

https://github.com/joomla/joomla-cms/pull/10469 fixes the issue one step further by allowing to use that URL without a 403 as a fallback (in case the menu type is not found or something) to the all menu items.

**Comment by Webdongle** [comment]
> "_#10459 fixes the issue one step further by allowing to use that URL without a 403 as a fallback (in case the menu type is not found or something) to the all menu items list view_"

Ah but before the issue began >>> navigating Menus ... hover over menu ... select create new menu ... then cancel or close ... never didn't look for anything in 'all menu items list view'.  It just returned to administrator/index.php?option=com_menus&view=items ... it didn't look for for anything with &menutype=

This issue was about the url that the close/cancel returned to was incorrect  so #10460 fixes this.  _#10459 is separate because it deals with handling the wrong url not replacing it.  Will test later but can't reproduce the issue following the test instructions it has.

**Comment by andrepereiradasilva** [comment]
You're right https://github.com/joomla/joomla-cms/pull/10460 solves the issue described here.

> Will test later but can't reproduce the issue following the test instructions it has.

Thanks. Updated test instructions and title to remove the link to this issue.
