### ISSUE TITLE
SEF - Plugin should be able to identify absolute path when srcset-attribute is applied

### ISSUE THREAD

**Issue by knewbeee** [joomla/joomla-cms#10463]
#### Steps to reproduce the issue

Should be easy to reproduce.

#### Expected result

If the Root-URL of a Joomla-site is for e.g.

http://www.example.org/customer2/

The browser should load/check with success (as it is the case when src attribute is applied):
http://www.example.org/customer2/images/myimage.jpg when using srcset attribute

#### Actual result

For the srcset-attribut this behaviour is not provided and the path remains on the relative path.
This results in an incorrect Image-Link for the browser:

http://www.example.org/customer2/index.php/de/images/myimage.jpg

#### System information

PHP-Version 5.5.30
Webserver Apache/2.2.22 (Ubuntu)
Joomla!-Version Joomla! 3.5.1 Stable

#### Additional comments

Thanks to Re:Later for providing/reporting this issue.
https://forum.joomla.de/index.php/Thread/1963-html5-picture-und-srcset-tags-verwenden/?postID=12740#post12740

**Comment by andrepereiradasilva** [comment]
Please test https://github.com/joomla/joomla-cms/issues/10463

**Comment by zero-24** [comment]
I guess you mean https://github.com/joomla/joomla-cms/issues/10464 ;) @andrepereiradasilva

**Comment by andrepereiradasilva** [comment]
yes that one. And plese not that PR will not solve all srcset possibilities, only the case described.

**Comment by zero-24** [comment]
Set to "closed" on behalf of @zero-24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10463">issues.joomla.org/joomla-cms/10463</a>

**Comment by zero-24** [comment]
Closing as we have a Pull Request. For testing that please see: https://docs.joomla.org/Testing_Joomla!_patches/de and the Pull Request description ;) Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10463">issues.joomla.org/joomla-cms/10463</a>.</sub>
