### ISSUE TITLE
[Button] for "send activation e-mail again"

### ISSUE THREAD

**Issue by sanek4life** [joomla/joomla-cms#10524]
Websites in a certain time might have a problem with sending messages, but users can registered on the site.

Users do not have the letter with the activation, because the site is temporarily could not send letters because of incorrect e-mail settings.

Please add the ability to resend your activation email, if the user has not yet passed on the link in an email.

=====================

also:

if the letter with the activation does not send to the e-mail user, Joomla need to show a message in the registration form on the website with a request to inform the administrator of the site. and to communicate with the administration in such a case, you can specify a link, such as Facebook.

probably almost all the site administrators faced with the problem of sending emails from the site. such a problem I had when changing hosting.

**Comment by 4digitalworld** [comment]
this is a very necessary function

**Comment by brianteeman** [comment]
This is basically the same issue as #13620 so I am going to close this one so that we only have one issue
