### ISSUE TITLE
[com_contact] Single contact, Miscellaneous Information tab, Module button inoperant

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#10525]
#### Steps to reproduce the issue
Edit or create a contact.
Go to Miscellaneous Information
Click Module button in the Editor.
Select a module. Save.
It adds something like : {loadmodule mod_articles_news,News Flash}

#### Expected result
Front-end display of the module selected.

#### Actual result
Front-end display of the code : {loadmodule mod_articles_news,News Flash}

#### System information (as much as possible)

Any joomla 3.5.1 distribution.

#### Additional comments
Our solution is -> in components/com_contact/views/contact/tmpl/default.php
``` php
<dd> 
       <span class="contact-misc"> 
           <!--<?php //echo $this->contact->misc; ?>--> 
           <?php echo JHtml::_('content.prepare', $this->contact->misc, '', 'com_contact.contact'); ?> 
                       </span> 
   </dd>
```
But it is only a workaround.

**Comment by andrepereiradasilva** [comment]
confirmed.

**Comment by andrepereiradasilva** [comment]
Also happens on tags description, and probably in a lot of editor fields across the components.

**Comment by andrepereiradasilva** [comment]
since, that i know of, the plugin thta convert that shortcode is only for content, the button "+Module" shouldn't be there IMO (like they aren't in modules). Should only be in com_content (categories and articles).

**Comment by ghazal** [comment]
Precisely.
That's why I just gave a workaround.
Nevertheless, since it's here, people want to use it.

**Comment by brianteeman** [comment]
You need to look at how the custom html module deals with this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10525">issues.joomla.org/joomla-cms/10525</a>.</sub>

**Comment by andrepereiradasilva** [comment]
i think it's here https://github.com/joomla/joomla-cms/blob/staging/plugins/content/loadmodule/loadmodule.php

**Comment by ggppdk** [comment]
Please test the PR, 

A comment: 
- J3.5.x added **onContentPrepare** event triggering in a fews views


Now please look at the code of the PR (**it is very small**), in case of contact
- the text is 
neither: $item->**text**
nor: $item->**description**

it is $item->**misc**

if other views are such a case, then they should be fixed too in a similar way

**Comment by brianteeman** [comment]
No thats not correct @ggppdk I am preparinga PR now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10525">issues.joomla.org/joomla-cms/10525</a>.</sub>

**Comment by brianteeman** [comment]
Please see #10539<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10525">issues.joomla.org/joomla-cms/10525</a>.</sub>

**Comment by ggppdk** [comment]
@brianteeman 

it is a choice to disallow the module button

but i can agree that it is a different issue that my PR 
- as it fixes an onContentPrepare bug of the view,
i will open a new issue then, thanks

**Comment by brianteeman** [comment]
New PR is #11419
