### ISSUE TITLE
Can save Article or Category without valid name in modal view

### ISSUE THREAD

**Issue by BurtNL** [joomla/joomla-cms#10520]
It looks like it is possible to save an article or category without a valid name, while working in the modal view.

#### Steps to reproduce the issue
Install latest staging and multilanguage functionality, since the tab Associations is needed for this test.
Make sure you have 2 articles or 2 categories in 2 different languages.
Open an article and go to tab Associations. Make sure the Edit-button is present.

![screen shot 2016-05-16 at 15 48 21](https://issues.joomla.org/uploads/1/58cb40363e918539044fd4713a49ae4e.jpg)

Edit the associated article via that Edit-button, clear the name of the article and click 'Save'.
Saving is not possible after this click, a red warning will be shown, as expected.

Click 'Save and Close'. Now the article will be saved with an empty name and no warning will be shown.

#### Expected result
A warning should have been showed: Invalid field: name.

#### Actual result
No warning about the missing name of the article, the article can be saved.
As a result the article is locked in the overview of articles.

#### System information (as much as possible)
Windows 10 / WAMP

#### Additional comments
This issue seems to be present in all modal views while editing a topic in such a view.

**Comment by andrepereiradasilva** [comment]
was able to reproduce in categories associations @JoomliC

**Comment by JoomliC** [comment]
Ok!
Confirmed, and issue already there in... 3.5.1!

In fact, you can test with 3.5.1 (before i did any change based on module edit modal) with module edit, and the issue was already there. (Go to Menus > open a menu > go to Modules Assignment tab, and then click on one module name to edit the module, and do as here, click on Save & Close after deleting the module title : same issue).
Not related to my change, but of course we need to fix it! ;-)

I will try to find a good solution to prevent such possible issue. (a way to not close the modal, if an error occures).
Or... to remove the <code>save & close</code>, to keep only <code>close</code> and <code>save</code> buttons ?

**Comment by JoomliC** [comment]
@BurtNL Tested, no "visible" error message, and article locked, but i can't save it with an empty name (the previous name is still there).
So did you really get an empty name after saving ? (article ? category ? module ?)

**Comment by JoomliC** [comment]
> was able to reproduce in categories associations

@andrepereiradasilva with your test with category edit in association, with <code>Save & Close</code>, and with latest staging (as categories modals merged) are you able to save with a empty title (i mean the title is really empty in database!) or it close, but in reality, nothing was changed in database ?
(which would mean a better behavior than in 3.5.1, where it's possible to really save an empty title for module in database, but with alreay changes done in 3.6.0-dev, this is not anymore possible for me (with the previous fixes)).

Thanks for help! ;-)

**Comment by andrepereiradasilva** [comment]
the title is not changed.

**Comment by JoomliC** [comment]
@andrepereiradasilva Thanks! (that means a better behavior than 3.5.1 when in modal)
I've got maybe an idea on how to not close if any error... Maybe will check this tomorrow ;-)

**Comment by JoomliC** [comment]
@BurtNL @andrepereiradasilva Just created the PR with fix for category, newsfeed and contact edit modal : https://github.com/joomla/joomla-cms/pull/10522
Note: as i have other changes to update article edit, and to do a code review for module, i will add this patch in the same time, in separated PRs (to come this week of course, to have all done for 3.6.0 ;-) )
Thanks for reporting this issue, and testing! 👍 

Note: I think we can close here as we have a PR ;-)

**Comment by brianteeman** [comment]
Closed as we have a PR #10522<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10520">issues.joomla.org/joomla-cms/10520</a>.</sub>
