### ISSUE TITLE
JDatabaseImporterPdomysql missing xmlToCreate()

### ISSUE THREAD

**Issue by Eighke** [joomla/joomla-cms#10527]
This commit https://github.com/joomla/joomla-cms/pull/7378 added a new method `xmlToCreate()` but it is missing on `JDatabaseImporterPdomysql`. As result we cannot use `mergeStructure()` using PDO driver.

https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/database/importer/mysqli.php#L54

PS: Shouldn't it extends the mysqli one? It is basically the same.

**Comment by brianteeman** [comment]
@alikon any interest from you in doing this

**Comment by alikon** [comment]
some times ago i've made #14272 but seems doesn't meet interest....so...if there is some interest ....else...

**Comment by brianteeman** [comment]
Fair enough and a valid comment. Purely up to you.

**Comment by alikon** [comment]
@franz-wohlkoenig  this can be closed as we have pr #23320

**Comment by ghost** [comment]
Thanks @alikon
