### ISSUE TITLE
Condition in JFactory::getUser() never false

### ISSUE THREAD

**Issue by alex-filat** [joomla/joomla-cms#10543]
#### Steps to reproduce the issue
Request the user with active user id
f.e. JFactory::getUser(308), assuming logged in user's id is 308

#### Expected result
below condition must be false
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/factory.php#L246
elseif (!($instance instanceof JUser) || is_string($id) || $instance->id !== $id)

#### Actual result
but this condition alway true becouse 
$instance->id !== $id is always true because $instance->id is string type and $id must be not string type

**Comment by infograf768** [comment]
As far as I know, $id is also a string
```
object(JUser)[33]
  protected 'isRoot' => null
  public 'id' => string '122' (length=3)

```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10543">issues.joomla.org/joomla-cms/10543</a>.</sub>

**Comment by alex-filat** [comment]
That is the problem. If we pass id type string then condition is true and function will create new user instead of return the existing.

**Comment by Quy** [comment]
Since `is_string($id)` condition is true, the last condition will not be evaluated. This issue can be closed.

**Comment by ghost** [comment]
closed as stated above.

Thanks @Quy.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10543">issues.joomla.org/tracker/joomla-cms/10543</a>.</sub>
