### ISSUE TITLE
Plugin system languagecode doesn't show proper meta itemprop

### ISSUE THREAD

**Issue by gagnonjeanfrancois** [joomla/joomla-cms#10540]
Hi, 

This is a little request for the Plugin system languagecode, I would be great if it could show the proper meta itemprop in the article. 

#### Steps to reproduce the issue

Extensions > Plug-ins > Enable : system code language
In the "Code" table : Set alternative language 
exemple : en-UK to en-CA or fr-FR to fr-CA

#### Expected result

On the front end load an article and take a look to the body : The meta itemprop should show `<meta itemprop="inLanguage" content="en-CA">`

#### Actual result

On the front end load an article and take a look to the body html : The meta itemprop will show `<meta itemprop="inLanguage" content="en-UK">`

**Comment by gagnonjeanfrancois** [comment]
**Expected result**

On the front end load an article and take a look to the body : The meta itemprop should show meta itemprop="inLanguage" content="en-CA"

**Actual result**

On the front end load an article and take a look to the body html : The meta itemprop will show meta itemprop="inLanguage" content="en-UK"

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10540">issues.joomla.org/joomla-cms/10540</a>.</sub>

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/10542

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10540">issues.joomla.org/joomla-cms/10540</a>

**Comment by infograf768** [comment]
Closing as we have a patch https://github.com/joomla/joomla-cms/pull/10542<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10540">issues.joomla.org/joomla-cms/10540</a>.</sub>
