### ISSUE TITLE
ACL regression

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#10544]
Create a user group as child of Administrator with these global permissions:

![screen shot 2016-05-18 at 11 47 44](https://cloud.githubusercontent.com/assets/869724/15354660/f721f0bc-1cee-11e6-9c03-ee3676a8f0b0.png)

Configure All components permissions as such:

![screen shot 2016-05-18 at 11 53 39](https://cloud.githubusercontent.com/assets/869724/15354725/4eaa5f40-1cef-11e6-8e5d-fbd951a9c815.png)

Fatal error:
`( ! ) Fatal error: Call to a member function addChild() on a non-object in /Applications/MAMP/htdocs/testwindows/trunkgitnew/administrator/modules/mod_menu/menu.php on line 59`

![screen shot 2016-05-18 at 12 02 00](https://cloud.githubusercontent.com/assets/869724/15354955/7469def8-1cf0-11e6-9bb7-51461e1e6902.png)

This was working perfectly well before (I don't know when it started to go wrong). I.e. users in demoacces group could access back-end and look at stuff (with a small hack for the toolbar buttons to prevent them from saving anyhting).

**Comment by infograf768** [comment]
OK, I found the issue:
This group is NOT authorised to create. As soon as I make it able to create then the issue is solved.

IMHO, the fatal error should not happen. It should degrade gracefully by displaying a "You are not authorised to create items here" OR not displaying the submenus of the type "Add New Article"

**Comment by andrepereiradasilva** [comment]
> not displaying the submenus of the type "Add New Article"

IMO this should be the result

**Comment by andrepereiradasilva** [comment]
If you replace this https://github.com/joomla/joomla-cms/blob/staging/administrator/modules/mod_menu/tmpl/default_enabled.php#L132-L141

with this

```php
	if ($createMenu)
	{
		$menu->addChild(new JMenuNode(JText::_('MOD_MENU_MENU_MANAGER_NEW_MENU'), 'index.php?option=com_menus&view=menu&layout=edit', 'class:newarticle'));
		$menu->getParent();
		$menu->addSeparator();
		$menu->addChild(new JMenuNode(JText::_('MOD_MENU_MENUS_ALL_ITEMS'), 'index.php?option=com_menus&view=items&menutype=*', 'class:menumgr'), $createMenu);
		$menu->getParent();
	}
```

no fatal error

**Comment by infograf768** [comment]
That does not work here.

**Comment by infograf768** [comment]
Issue is definitely with $createMenu, as you rightfully found out, as setting it to true solves the Fatal error.

**Comment by andrepereiradasilva** [comment]
please test https://github.com/joomla/joomla-cms/pull/10545

Thsi can be closed.

**Comment by brianteeman** [comment]
Closed as requested
