### ISSUE TITLE
Cache time inconsistency

### ISSUE THREAD

**Issue by ptdev** [joomla/joomla-cms#10553]
Hi, I've enabled the Joomla cache with APC User Cache. I've set the cache time on the configuration to "15" (which according to the description, should be 15 minutes).

Unfortunately, Joomla seems to still use that number as seconds instead of minutes.

Having seen this I then changed the cache time to "300", cleared the cache and tried it again.

Now Joomla stores most of the cache for 300 seconds but there are still a lot of cached items with 15 seconds timeout.

Below are some screenshots of my joomla configuration and APCu status page.

![screen shot 2016-05-19 at 09 28 26](https://cloud.githubusercontent.com/assets/1280528/15387618/fe2c8036-1da5-11e6-8e8a-9ac549f7bec2.png)

![screen shot 2016-05-19 at 09 29 57](https://cloud.githubusercontent.com/assets/1280528/15387664/2dc54530-1da6-11e6-826e-dbaf29976586.png)

#### Steps to reproduce the issue
Enable Joomla Cache (conservative/APC User Cache)
Set "Cache Time" to "15"

#### Expected result
Joomla stores the cache items with 15 minutes expiration (900 seconds)

#### Actual result
Joomla stores the cache items with 15 seconds expiration

#### System information (as much as possible)
debian 8.4
nginx 1.9.10
php-fpm 5.6.20
php-apcu 4.0.7
joomla 3.5.1

#### Additional comments
I've posted about this before on #8707 and according to that thread, this issue should have been resolved on a recent cache system rewrite so if anyone using apcu could try to reproduce and confirm if this is also happening to them it would be great.

**Comment by andrepereiradasilva** [comment]
you can test yoursef if it's solved.
Downlaod and install latest staging as a normal installation https://github.com/joomla/joomla-cms/archive/staging.zip

**Comment by ptdev** [comment]
Hey, you're right, it is fixed on staging.

Since 3.5.1 was released after it was stated on #8707 that the issue had been fixed I assumed that the fix was already included on that version but apparently not and it seems it'll only be fixed on 3.6.

Thanks. Closing.
