### ISSUE TITLE
ACL: bugs and oddities

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#10552]
A. On a legacy test site (updated since 1.6 to staging) the **Administrator Group**, when set to "Inherited" for "Administrator Login", calculates the settings to "Not Allowed" in Global Configuration (related to C.)

![legacy](https://cloud.githubusercontent.com/assets/869724/15385520/6b8ba872-1da2-11e6-88b2-b9ab5e237d2f.png)
On a vanilla new staging site, it is fine at first:

![global admin](https://cloud.githubusercontent.com/assets/869724/15385545/966cca58-1da2-11e6-8168-59390c153eb1.png)

B. On both legacy and vanilla staging, when displaying the permissions for a component (here com_content), the Calculated Setting displays a lock with **Allowed (Super User)** although it concerns Administrator and not a Super User. Also as the settings can be changed, the lock makes no sense.

![compallowed](https://cloud.githubusercontent.com/assets/869724/15385686/78e23d46-1da3-11e6-8c87-9d7ca2817fa0.png)

C. In the component Permissions, If I change "Access Administration Interface" to anything else than "Inherited", it changes OK to "Denied" or "Allowed", BUT there is no way to get it back  to its former state by using "Inherited". It will always now display "Not Allowed" if using "Inherited". This could also explain the legacy test site result in Global Configuration Permissions (see A. where I may have changed default setting at one point).

![notallowed](https://cloud.githubusercontent.com/assets/869724/15385801/3a7b2a76-1da4-11e6-8976-7bb9a1348a40.png)

D. Let's create a new Group "TestGroup" with Administrator group as Parent.

![newgroup](https://cloud.githubusercontent.com/assets/869724/15385903/fa9302c0-1da4-11e6-8c0d-9978e87db101.png)

In Global Configuration, let's set the "Delete" field for this new group to "Denied"

![testgroupdenied](https://cloud.githubusercontent.com/assets/869724/15386037/cd7e6af8-1da5-11e6-992d-8dabaa9c8ec3.png)

I am expecting that, by default, the "Delete" permission for this new group in any component would be set to "Denied". This is not the case. Also tested with other fields than "Delete"

![notdenied](https://cloud.githubusercontent.com/assets/869724/15386118/3890f68a-1da6-11e6-8003-86d1a01113b6.png)

**Comment by andrepereiradasilva** [comment]
> A. On a legacy test site (updated since 1.6 to staging) the Administrator Group, when set to "Inherited" for "Administrator Login", calculates the settings to "Not Allowed" in Global Configuration (related to C.)

> C. In the component Permissions, If I change "Access Administration Interface" to anything else than "Inherited", it changes OK to "Denied" or "Allowed", BUT there is no way to get it back to its former state by using "Inherited". It will always now display "Not Allowed" if using "Inherited". This could also explain the legacy test site result in Global Configuration Permissions (see A. where I may have changed default setting at one point).

I think it's the same issue as https://github.com/joomla/joomla-cms/issues/10121

B. and D. i think are another issues,

**Comment by phproberto** [comment]
Checking this now from jandbeyond bug squash session.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10552">issues.joomla.org/joomla-cms/10552</a>.</sub>

**Comment by infograf768** [comment]
:smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10552">issues.joomla.org/joomla-cms/10552</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman this aCL stuff should IMHO be a release-blocker

**Comment by brianteeman** [comment]
will take a look tomorrow

On 31 May 2016 at 22:40, andrepereiradasilva <notifications@github.com>
wrote:

> @brianteeman <https://github.com/brianteeman> this aCL stuff should IMHO
> be a release-blocker
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10552#issuecomment-222829933>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8dleehkardubRu4iEHXzOqWP3I6wks5qHKrZgaJpZM4Ih_7e>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by aschkenasy** [comment]
for me this happens only with the administrator group which is automatically calculated as su?

**Comment by brianteeman** [comment]
Can I close this Issue now as it looks like everything has been addressed in existing PR now?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10552">issues.joomla.org/joomla-cms/10552</a>.</sub>

**Comment by sovainfo** [comment]
Confirm B, C, D are solved in 3/6/0 Beta 2 (3.5.0->3.5.1->3.6.0.alpha->3.6.0 Beta 1->36.0 Beta2)

**Comment by andrepereiradasilva** [comment]
sovainfo see https://github.com/joomla/joomla-cms/pull/10793

**Comment by infograf768** [comment]
Closing this as it is solved by #10793
