### ISSUE TITLE
View com_installer discover. Button Discover doesn't purge database.

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#10550]
Joomla 3.5.1

#### Expected behavior
When you click button Discover in view
administrator/index.php?option=com_installer&view=discover
all entries in database table xy_extensions with state = -1 ("not installed yet") should be deleted before webspace is checked for not installed extensions.

#### Actual behavior
When a folder with not installed extension is removed from webspace after it was found with button Discover it's always displayed in view
administrator/index.php?option=com_installer&view=discover

#### Testing Instructions
- Create folder /plugins/content/discovertest/
- Create file /plugins/content/discovertest/discovertest.xml
```
<?xml version="1.0" encoding="utf-8"?>
<extension version="3.5" type="plugin" group="content" method="upgrade">
<name>discovertest</name>
<files>
<filename plugin="discovertest">discovertest.php</filename>
</files>
</extension>
```
- Backend: Goto administrator/index.php?option=com_installer&view=discover
- Click button Discover.
- New item in view/list: discovertest. Don't install!
- Have a look in database table xyz_extensions
- You'll see an entry (highest extension_id) with state -1 and name discovertest.

- Delete new folder above.
- Click button Discover.
- Nothing has changed in list of view and in database. Still an entry discovertest (that's not installable and not present anymore in webspace).

None of the methods discover() (libraries/cms/installer/[adapter] or com_installer itself) is calling a purge() method. All are just setting state = -1 but never remove them if outdated.

**Comment by andrepereiradasilva** [comment]
Add 
```php
$this->purge();
```
here https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_installer/models/discover.php#L139

**Comment by bertmert** [comment]
This solution doesn't output any error message if purge() returns a false. I don't know if the discover procedure should stop then or not, output a message or not.

**Comment by Bakual** [comment]
@bertmert Andre ist right, just add that line back where he said. It was his PR https://github.com/joomla/joomla-cms/pull/9114 which removed the line accidentally in the discover method.

**Comment by infograf768** [comment]
Anyone creates the PR?

**Comment by bertmert** [comment]
Test https://github.com/joomla/joomla-cms/pull/10558 please.
