### ISSUE TITLE
Problem with css and type="text/css"

### ISSUE THREAD

**Issue by sonosergio** [joomla/joomla-cms#10562]
#### Steps to reproduce the issue
Navigate with Microsoft Edge 25.10586 and use Joomla with rokbooster or use css file with extension .php

#### Expected result
Browser load css file

#### Actual result
Windows Edge don't load css file

#### System information (as much as possible)
Microsoft Edge 25.10586
Windows 10

#### Additional comments
i think that the problem is that IE Edge don't load file without extension css if type is not defined.
In fact, if in html code appears
`<link rel="stylesheet" href="/cache/rokbooster/1b5f72ab3d50029b755b5ceb3bf0903e.php" type=""/>`
it not work
but changing the file joomla-cms/libraries/joomla/document/renderer/html/head.php 
and add
```
if (!is_null($strAttr['mime']) && (!$document->isHtml5() || $strAttr['mime'] == 'text/css'))
			{
				$buffer .= ' type="' . $strAttr['mime'] . '"';
			}
```
to display
`<link rel="stylesheet" href="/cache/rokbooster/1b5f72ab3d50029b755b5ceb3bf0903e.php" type="text/css"/>`
it's work

**Comment by brianteeman** [comment]
This is surely not a joomla issue but one for the rokbooster extension. Css
files are not supposed to have php as the file extension.

**Comment by sonosergio** [comment]
> Css files are not supposed to have php as the file extension.
why not?
[https://www.google.it/webhp?ion=1&espv=2&ie=UTF-8#q=css%20with%20php%20extension](https://www.google.it/webhp?ion=1&espv=2&ie=UTF-8#q=css%20with%20php%20extension)

the problem is that in the specification of html5 
[https://dev.w3.org/html5/spec-preview/Overview.html#attr-link-type](https://dev.w3.org/html5/spec-preview/Overview.html#attr-link-type)
is write 
_The type attribute gives the MIME type of the linked resource. It is purely advisory. The value must be a valid MIME type._

and Windows Edge use this value to indetify the type of file
