### ISSUE TITLE
Error in plugin page com_plugins "Fatal error: Cannot redeclare class PluginsHelper"

### ISSUE THREAD

**Issue by maofree** [joomla/joomla-cms#10582]
#### Steps to reproduce the issue
from the image you can get it
I get this error only from one site on my local server, probably it has a different configuration
however thi is a php error.
the joomla's version is the 3.5.1
I can you you the access to my site, if you need it![screen shot 2016-05-21 at 13 34 02](https://issues.joomla.org/uploads/1/bd99a1c4e09f5b0dc367aadb9f3d8f26.png)

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.joomla.org
