### ISSUE TITLE
Issue with unpacking tar.gz archives if there are very long file paths

### ISSUE THREAD

**Issue by Chraneco** [joomla/joomla-cms#10580]
#### Steps to reproduce the issue
1. Put a `die` statement at the end of method `JArchivTar::extract` in order to be able to inspect the contents of the extracted temporary files.
2. Install the .tar.gz version of this extension: https://github.com/JoomGallery/BootOne/releases/tag/v1.0-alpha5
3. Go to `tmp/install_*` and observe that the two files `footer.bootone.php` and `header.bootone.php` have been extracted into the root of this temporary directory instead of the folder `BootOne-1.0-alpha5/administrator/components/com_joomgallery/layouts/joomgallery/common/` as in the original structure of the archive.
#### Expected result

Files `footer.default.php` and `header.default.php` should be extracted into `tmp/install_*/BootOne-1.0-alpha5/administrator/components/com_joomgallery/layouts/joomgallery/common/`.
#### Actual result

Files `footer.default.php` and `header.default.php` are extracted into `tmp/install_*/`.
#### System information (as much as possible)

Joomla! 3.5.1 on localhost with Xampp.

**Comment by brianteeman** [comment]
This sounds very similar to #6554

**Comment by Chraneco** [comment]
Indeed, sorry I didn't see that one.
However, I tested with the latest version of Joomla! which already includes that change and it still occurs.

**Comment by franz-wohlkoenig** [comment]
@Chraneco does this Issue exist on 3.7.-staging?

**Comment by franz-wohlkoenig** [comment]
closed as no Reply.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10580">issues.joomla.org/tracker/joomla-cms/10580</a>.</sub>
