### ISSUE TITLE
3.6.0 Alpha 1 problem in cancelling menu item creation

### ISSUE THREAD

**Issue by gunjanpatel** [joomla/joomla-cms#10603]
#### Steps to reproduce the issue

Please find this video, https://youtu.be/huDwAPmncT4
If you are logged in then please logout and login back to reproduce this issue.

#### Expected result

It should list menu items from selected menu.

#### Actual result
![screen shot 2016-05-23 at 08 09 41](https://issues.joomla.org/uploads/1/9ab7b72c7a2d7260bcdd9687303c5c80.png)

#### System information (as much as possible)

Using **Firefox 46.0.1**

**Comment by wojsmol** [comment]
@gunjanpatel See https://github.com/joomla/joomla-cms/issues/10518#issuecomment-219541996

**Comment by brianteeman** [comment]
Closed as a duplicate report<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10603">issues.joomla.org/joomla-cms/10603</a>.</sub>
