### ISSUE TITLE
Messages inside the new Joomla 3.6 updater

### ISSUE THREAD

**Issue by stevejburge** [joomla/joomla-cms#10604]
Just some small feedback on the new Joomla 3.6 updater

1) Visually, it's almost impossible to see that "the official Joomla download page" is a link

2) This isn't a relevant explanation, "The maximum file size for uploads is set to less than 8MB which may impact on uploading large extensions."

Might be better to say something about the impact on uploading Joomla updates?

![screen shot 2016-05-23 at 9 14 15 am](https://cloud.githubusercontent.com/assets/3868028/15472048/20aabff0-20c7-11e6-9ffe-f908db792353.png)

**Comment by mbabker** [comment]
1's an issue with links in alerts in general; Bootstrap 2.3 just didn't deal with it.  Might be a good idea to implement Bootstrap 3's `alert-link` class for the core templates.

**Comment by zero-24** [comment]
I think we can close here as the first issue can be fixed with @mbabker 's PR #10678 and the seccond one with my #10707 

maybe @stevejburge can you give them a quick test?

**Comment by stevejburge** [comment]
Sorry, maybe my fault, but I applied these using the Patch Tester and didn't see any visual changes.

**Comment by mbabker** [comment]
#10678 isn't actually changing anything on the update component's views.  It did change the alert on the Extension Manager's install page as a quick demo but that's it so far (and the only reason I did that was to make testing the added the CSS/LESS definition easy).  With that one merged we can work through other places where alerts are used, it's just a lot of places to review and I went for the quickest route to at least make the styling options available.

**Comment by zero-24** [comment]
Thevlanguage updates are now RTC. Thanks

**Comment by roland-d** [comment]
@stevejburge Isssue #10678 only shows on the Install from Web message on the Extension -> Install page. The link is now bold to make it stand out more. I would assume this is present if you look there after applying the patch.

Issue #10707 only changes a single word on the message.

This issue can be closed as we have started the necessary PRs.
