### ISSUE TITLE
Media Manager not outputing any error when trying to upload a zip file that contains php files

### ISSUE THREAD

**Issue by compojoom** [joomla/joomla-cms#10609]
As far as I understand there is a new security feature that scans the content of a zip file uploaded through the media manager and forbids the upload if that zip file contains any php files. 

In my case this is pretty stupid as I want people to upload zip files containing php code, but anyway. That's not the point of this issue here. 

When uploading such an "incorrect" file I would expect to at least get an error message or at a warning. Instead the page just refreshes and no message is displayed. 

#### Steps to reproduce the issue
Go to media manager. (make sure that you have set the zip file extension in the allowed extension types) Try to upload a zip file containing php files.

#### Expected result
The file should upload.

#### Actual result
The file doesn't upload and not error message is shown. The file list just refreshes.

#### System information (as much as possible)
Tested on several 3.5.1 installations

#### Additional comments
I tried to upload the test zip files here but GitHub says "unfortunately, we don't support that file type", which is also pretty confusing as ZIP is listed as a supported file type, but it's way better than joomla's omission of an error whatsoever.

**Comment by zero-24** [comment]
Can you provide the file e.g. via GD or Dropbox or similiar?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10609">issues.joomla.org/joomla-cms/10609</a>.</sub>

**Comment by conconnl** [comment]
The new MediaManager improvements project can be found here, maybe it's good to fix it in the new version.
https://github.com/joomla-projects/media-manager-improvement <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10609">issues.joomla.org/joomla-cms/10609</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@conconnl have you opened an issue so i can close this Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10609">issues.joomla.org/tracker/joomla-cms/10609</a>.</sub>

**Comment by conconnl** [comment]
No and i'm not sure for what I need to make a issue. I don't have any issues at the moment.

**Comment by franz-wohlkoenig** [comment]
@conconnl i misread your comment above, sorry for that.

**Comment by franz-wohlkoenig** [comment]
@laoneo should i open an ssue like this on  https://github.com/joomla-projects/media-manager-improvement?

**Comment by laoneo** [comment]
Yes I think it is a good idea, then we have it tracked.

**Comment by franz-wohlkoenig** [comment]
done: https://github.com/joomla-projects/media-manager-improvement/issues/166
