### ISSUE TITLE
Install may not start because of Content-Security-Policy header, but Pre-Installation Check does not notice this

### ISSUE THREAD

**Issue by hagman** [joomla/joomla-cms#10617]
#### Steps to reproduce the issue
1. Prepare a web server to issue Content-Security-Headers that do not allow "unsafe-eval", e.g., with Apache, add 
`header set Content-Security-Policy "default-src 'self' 'unsafe-inline'" `
to the VirtualHost configuration
2. Download and unpack Joomla to the web server
3. Visit your Joomla web server and follow the first-run installation tasks

#### Expected result
Installation starts once all conditions of the "Pre-Installation Checks" are met.
If there still is a problem, a helpful message should be displayed

#### Actual result
A popup "Process in progress. Please wait ..." comes up. Nothing else happens

#### System information (as much as possible)
Should not matter; tested with Ubuntu 12.04, Apache, Joomla 3.5.1

#### Additional comments
An additional Pre-Installation Check for good-enough Content-Security-Policy should be added.
It might simply be an additional line in the Pre-Installation Check table that shows a red "NO", which is changed into a green "YES" by some Javascript that relies on `unsafe-inline` and `unsafe-eval` to be present.
See also http://joomla.stackexchange.com/questions/16635/joomla-install-does-not-start

**Comment by andrepereiradasilva** [comment]
That i know of joomla, as a whole, doesn't work without `'self' 'unsafe-eval' 'unsafe-inline'` in the js CSP rules (`script-src`). And also you need `'self' 'unsafe-inline'` for the CSS rules (`style-src`).

So if you are just using the default CSP fallback (`default-src`) the `'self' 'unsafe-eval' 'unsafe-inline'` is always needed for joomla to work.

But agree a js check could exist in installation and admin sys info.

Note: don't know exactly why `unsafe-eval` is needed, but the `unsafe-inline` is needed for all the inline scripts/styles Joomla uses.

**Comment by brianteeman** [comment]
Sorry but this is not something that can be changed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10617">issues.joomla.org/joomla-cms/10617</a>.</sub>
