### ISSUE TITLE
[3.6.0 Alpha1] 3.6.0-2016-04-01.sql does not apply

### ISSUE THREAD

**Issue by shur** [joomla/joomla-cms#10611]
I'm trying to test the new update on my test platform (j3.5.1, updated, not freshly installed).
I noticed that this file [3.6.0-2016-04-01.sql](https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/sql/updates/mysql/3.6.0-2016-04-01.sql) doesn't apply its changes in #__update_sites table in my database. Digging deeper I found out that this file refers to these names:
```"Joomla! Core" and "Joomla! Extension Directory"```
but in my case this table contains such names (without symbol "!"):
```"Joomla Core" and "Joomla Extension Directory"```
Sure sql cannot find these names and cannot apply.

#### Steps to reproduce the issue
Install Joomla 3.3.0 or earlier version.
Update to Joomla 3.5.1

#### Expected result
Go to database #__update_sites table
There should be "Joomla! Core" and "Joomla! Extension Directory" site names.

#### Actual result
In fact, the names are without symbol "!".
So we get an obvious difference between updated Joomla and freshly installed Joomla.
Because of this 3.6.0-2016-04-01.sql cannot be applied.

#### Additional comments
Exploring the problem I discovered when this inconsistency was made.
In Joomla 3.3.1 installation joomla.sql file contains:
```
INSERT INTO `#__update_sites` (`update_site_id`, `name`, `type`, `location`, `enabled`, `last_check_timestamp`) VALUES
(1, 'Joomla Core', 'collection', 'http://update.joomla.org/core/list.xml', 1, 0),
(2, 'Joomla Extension Directory', 'collection', 'http://update.joomla.org/jed/list.xml', 1, 0),
(3, 'Accredited Joomla! Translations', 'collection', 'http://update.joomla.org/language/translationlist_3.xml', 1, 0);
```

In Joomla 3.3.3 installation joomla.sql file contains:
```
INSERT INTO `#__update_sites` (`update_site_id`, `name`, `type`, `location`, `enabled`, `last_check_timestamp`) VALUES
(1, 'Joomla! Core', 'collection', 'http://update.joomla.org/core/list.xml', 1, 0),
(2, 'Joomla! Extension Directory', 'collection', 'http://update.joomla.org/jed/list.xml', 1, 0),
(3, 'Accredited Joomla! Translations', 'collection', 'http://update.joomla.org/language/translationlist_3.xml', 1, 0);
```

As you see, exclamation mark has appeared, but only for freshly installed Joomla.
But how about those site that update their Joomla? These names were never renamed.

**Comment by Bakual** [comment]
So the SQL has to be adjusted to included the old names as well. Do you want to create a PR for that?

**Comment by shur** [comment]
I think this in file 3.6.0-2016-04-01.sql we should first rename old names to exclude any further inconsistency. And then apply changes only to the new names.
I'm not sure if I'll be able to create a PR correctly for all databases. So if someone can do that - I'd be happy.

**Comment by Bakual** [comment]
Closing as we have a PR
