### ISSUE TITLE
Per-article "Show intro text" option ignored: Single Article

### ISSUE THREAD

**Issue by helvecio** [joomla/joomla-cms#10623]
#### Steps to reproduce the issue

1. In **Global Configuration -> Articles** set **Show Intro Text** to **Show**.
2. In **menu options (single article/featured)** set **Show Intro Text** to **Hide**.
3. In article options of the specific article, set **Show Intro Text** to **Hide**.

#### Expected result
Hidden Intro text
#### Actual result
The intro text for this specific article is still shown in the article view.
#### System information (as much as possible)
**PHP Built On** Linux host.aveiro-mindnet.com.br 2.6.32-673.8.1.lve1.4.3.el6.x86_64 #1 SMP Wed Feb 10 08:57:30 EST 2016 x86_64
**Database Version** 5.5.49-cll
**Database Collation** latin1_swedish_ci
**Database Connection Collation** utf8mb4_general_ci
**PHP Version** 5.3.29
**Web Server** Apache/2.4.16 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
**WebServer to PHP Interface** cgi-fcgi
**Joomla! Version** Joomla! 3.5.1 Stable [ Unicorn ] 05-April-2016 22:45 GMT
**Joomla! Platform Version** Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
**User Agent** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0 
#### Additional comments
When **Show Intro Text** is set to **Hide** in **Global Configurations**, the intro text will not display, as expected.

**Comment by smz** [comment]
@halvecio:

You might be interested in reading https://github.com/joomla/joomla-cms/pull/9801 and the discussion starting with https://github.com/joomla/joomla-cms/pull/10519#issuecomment-220298214

**Comment by helvecio** [comment]
I have realized this issue happened due to a separate inactive menu and its itens.
