### ISSUE TITLE
showon field attribute doesn't work in modal

### ISSUE THREAD

**Issue by grantg182** [joomla/joomla-cms#10624]
#### Steps to reproduce the issue

Create new form fields for custom article options, e.g. /templates/t3_bs3_blank/etc/extrafields/myfields.xml

In myfields.xml, create a repeating group to appear in a modal. Example:-

`
<field name="list_subtitles" type="Repeatable" icon="list" description="TPL_GROUP_EXTRA_FIELDS_SUBTITLES_DESC" label="TPL_GROUP_EXTRA_FIELDS_SUBTITLES_LABEL" default="{'subtitlelanguage':['']}">
    <fields name="params">
    <fieldset hidden="true" name="list_subtitles" repeat="true">
        <field name="subslang" multiple="false" type="list" label="TPL_GROUP_EXTRA_FIELDS_SUBTITLES_SUBTITLE_TITLE" description="TPL_GROUP_EXTRA_FIELDS_SUBTITLES_SUBTITLE_DESC" filter="unset">        
            <option value="1">English</option>
            <option value="2">Spanish</option>
            <option value="3">German</option>
        </field>
        <field name="subssrc" type="url" showon="subslang:2" label="TPL_GROUP_EXTRA_FIELDS_SUBTITLES_SUBTITLE_FILE" description="TPL_GROUP_EXTRA_FIELDS_SUBTITLES_SUBTITLE_FILE_DESC" filter="unset" />         
    </fieldset>
    </fields>
</field>
`
#### Expected result

Click the 'Select' field to display the modal. In the modal, initially there should be only the select list showing - the text field should not appear until the select option value '2' has been selected.
#### Actual result

However, the text field is displayed at all times. The showon function works as expected outside of a modal, however. E.g:-

```
<fieldset hidden="true" name="list_subtitles" repeat="true">
    <field name="subslang" multiple="false" type="list" label="TPL_GROUP_EXTRA_FIELDS_SUBTITLES_SUBTITLE_TITLE" description="TPL_GROUP_EXTRA_FIELDS_SUBTITLES_SUBTITLE_DESC" filter="unset">        
        <option value="1">English</option>
        <option value="2">Spanish</option>
        <option value="3">German</option>
    </field>
    <field name="subssrc" type="url" showon="subslang:2" label="TPL_GROUP_EXTRA_FIELDS_SUBTITLES_SUBTITLE_FILE" description="TPL_GROUP_EXTRA_FIELDS_SUBTITLES_SUBTITLE_FILE_DESC" filter="unset" />         
</fieldset>
```

However, this removes the repeatable nature I desire.
#### System information (as much as possible)

Joomla 3.5.1

**Comment by franz-wohlkoenig** [comment]
@grantg182 can you confirm Issue on latest Staging too?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10624">issues.joomla.org/tracker/joomla-cms/10624</a>.</sub>

**Comment by grantg182** [comment]
Yes, unfortunately it appears to be no different in 3.6.5 using the above example.

**Comment by franz-wohlkoenig** [comment]
thanks for Info, set Status to "Need Review" on Issue Tracker.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10624">issues.joomla.org/tracker/joomla-cms/10624</a>.</sub>

**Comment by Fedik** [comment]
No chance it will be fixed anytime.
Use https://docs.joomla.org/Subform_form_field_type instead of `Repeatable`. 
There 'showon' should work.

**Comment by Bakual** [comment]
Closing as it's a known issue which will not be fixed
The repeatable formfield is deprecated and replaced by the subform one for reasons like this one.
