### ISSUE TITLE
Debug untranslated strings section shows: S_MESSAGES_LOGGED="messages logged**

### ISSUE THREAD

**Issue by beni71** [joomla/joomla-cms#10626]
#### Steps to reproduce the issue
1. Under System > Global configuration set "debug language" = yes.
2. Set "debug system" = yes.
3. Save & close
4. Under Extensions > plugins open the "system debug" plugin and set "Log Deprecated API" = yes.
5. Save and scroll down and expand "Untranslated Strings".

#### Expected result
On the bottom of the page there should be a debug section "untranslated strings" and in this section there should be only the item "None".

#### Actual result
The debug section "untranslated strings" is showing:
S_MESSAGES_LOGGED="messages logged**"

#### System information (as much as possible)
Source code from stage cloned. Currently, this 3.6.0-alpha2-dev.
PHP 7.0.6

#### Additional comments
The problem lies in the nested language string call in JROOT\plugins\system\debug\debug.php

In line 1785, there is something like:
... **JText::**sprintf(**JText::**_('PLG_DEBUG_LOGS_LOGGED'), $logEntriesTotal) ...

This is wrong. It must be either:
... JText::sprintf('PLG_DEBUG_LOGS_LOGGED', $logEntriesTotal) ...

or:
... sprintf(JText::_('PLG_DEBUG_LOGS_LOGGED'), $logEntriesTotal) ...

I don't know which solution is the recommended.

**Comment by infograf768** [comment]
I confirm. It should be:

`JText::sprintf('PLG_DEBUG_LOGS_LOGGED', $logEntriesTotal)`

Will make patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10626">issues.joomla.org/joomla-cms/10626</a>.</sub>

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10626">issues.joomla.org/joomla-cms/10626</a>

**Comment by infograf768** [comment]
Closed as we have a patch to test https://github.com/joomla/joomla-cms/pull/10627

Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10626">issues.joomla.org/joomla-cms/10626</a>.</sub>
