### ISSUE TITLE
core.edit.own permission doesn't allow to insert article link with a XTD "Article" button

### ISSUE THREAD

**Issue by yild** [joomla/joomla-cms#10636]
#### Steps to reproduce the issue

User/group isn't allowed to insert link to article via XTD "Article" button when we want to limit users to edit its own articles.
"Global Configuration/Permissions settings", Edit Own == Allowed, function "Article" (XTD button) rise JERROR_ALERTNOAUTHOR message.

#### Expected result

User/group should be allowed to add article link even with core.edit.own set to Allowed not only with core.edit.

#### Actual result

User/group are not allowed to add article link with core.edit.own permissions (only, core.edit set to Denied).

#### Additional comments

Problem is in components\com_content\content.php file

current code:

    elseif ($input->get('view') === 'articles' && $input->get('layout') === 'modal')
    {
        if (!$user->authorise('core.edit', 'com_content'))
        {
            JFactory::getApplication()->enqueueMessage(JText::_('JERROR_ALERTNOAUTHOR'), 'warning');

            return;
        }
    } 

changed code to:

    elseif ($input->get('view') === 'articles' && $input->get('layout') === 'modal')
    {

    if (!($user->authorise('core.edit', 'com_content') ||
	$user->authorise('core.edit.own', 'com_content')))
        {
            JFactory::getApplication()->enqueueMessage(JText::_('JERROR_ALERTNOAUTHOR'), 'warning');

            return;
        }
    }

gives wanted result - users/groups with core.edit.own permission only are allowed to insert links

**Comment by infograf768** [comment]
please make pr

**Comment by yild** [comment]
I've tried but failed to do so...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10636">issues.joomla.org/joomla-cms/10636</a>.</sub>

**Comment by brianteeman** [comment]
Just make your change to the staging branch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10636">issues.joomla.org/joomla-cms/10636</a>.</sub>

**Comment by andrepereiradasilva** [comment]
go to https://github.com/joomla/joomla-cms/blob/staging/components/com_content/content.php and press the edit icon (pencil). make the changes, had a commit description, save and submit a PR explaining what you have done and how to test.

**Comment by yild** [comment]
Thanks... done :)
https://github.com/joomla/joomla-cms/pull/10653<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10636">issues.joomla.org/joomla-cms/10636</a>.</sub>

**Comment by brianteeman** [comment]
Thanks. Closing as we have a pull request for testing
