### ISSUE TITLE
Custom module is always div

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#10643]
#### Steps to reproduce the issue

create a new custom module, select advanced tab, enter at Module Tag "Section"

#### Expected result

New module with section 

#### Actual result

div

#### System information (as much as possible)

Joomla 3.6.0 Alpha 1

**Comment by andrepereiradasilva** [comment]
confirmed.

**Comment by andrepereiradasilva** [comment]
actually not confirmed.
Is there.

```html
<section class="moduletable">
	<h3>module title</h3>
	<div class="custom">
		<p>module content</p>
	</div>
</section>
```

**Comment by 810** [comment]
for me its:

 ````<div class="custom section-signup bg-faded" abp="525">````

**Comment by 810** [comment]
ok I had Module Style = inherit

I have changed it to html5, now its ok

**Comment by 810** [comment]
but when I added a class on the module, its now showed twice :

````html
<section class="moduletable section-signup bg-faded" abp="525">
    <div class="custom section-signup bg-faded" abp="526">
      <div class="container" abp="527">
	   <h3 class="text-xs-center m-b-3" abp="528">Sign up to receive free updates as soon as they hit!</h3>
      </div>
    </div>
</section>
````
