### ISSUE TITLE
'Batch process the selected menu items' modal needs to be taller

### ISSUE THREAD

**Issue by jamield** [joomla/joomla-cms#10647]
If you select several menu items in the backend menu manager to batch move them to a different menu item on a site with many menu items the tiny height of the batch process modal makes it very difficult to find the menu/menu item you want to move them under. It should be much taller.

#### Steps to reproduce the issue

Login in to admin. Select a menu from menu manager. Select several menu items and click the 'batch' button at the top. Attempt to move menu items under a different one.

#### Expected result

Larger modal

#### Actual result

Small modal.

#### System information (as much as possible)

N/A

#### Additional comments

Happy to contribute the solution if someone can tell me how :)

**Comment by andrepereiradasilva** [comment]
what joomla version this happens?

**Comment by jamield** [comment]
3.5.1


Jamie Derrick
mobile: +44 (0)7740 348799
web: jderrick.co.uk
email: jamie.derrick@jderrick.co.uk
<http://twitter.com/jamiederrick>  <http://uk.linkedin.com/in/jamiederrick>

**Comment by JoomliC** [comment]
There's already a lot of improvements and fixes done for modals in 3.6.0, and some new ones in process ;-)
Could you test it on current staging or 3.6.0-alpha ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10647">issues.joomla.org/joomla-cms/10647</a>.</sub>

**Comment by JoomliC** [comment]
There's already a lot of improvements and fixes done for modals in 3.6.0, and some new ones in process ;-)
Could you test it on current staging or 3.6.0-alpha ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10647">issues.joomla.org/joomla-cms/10647</a>.</sub>

**Comment by jamield** [comment]
I don't have a copy of 3.6.0-alpha at the moment. Will have a look when I
get a chance.


Jamie Derrick
mobile: +44 (0)7740 348799
web: jderrick.co.uk
email: jamie.derrick@jderrick.co.uk
<http://twitter.com/jamiederrick>  <http://uk.linkedin.com/in/jamiederrick>

**Comment by andrepereiradasilva** [comment]
3.6.0 alpha 1 -> https://github.com/joomla/joomla-cms/releases/tag/3.6.0-alpha
Latest staging -> https://github.com/joomla/joomla-cms/archive/staging.zip

**Comment by brianteeman** [comment]
Closed as already fixed

**Comment by jamield** [comment]
Any more information on who/what/where this was fixed please?

**Comment by andrepereiradasilva** [comment]
not sure, but i think it was solved here https://github.com/joomla/joomla-cms/pull/9817

**Comment by jamield** [comment]
Super thanks for that!

**Comment by JoomliC** [comment]
> not sure, but i think it was solved here #9817

Exactly! :+1:
