### ISSUE TITLE
Batch process of articles and menus with scrollbar is harder to use in 3.5+ then in previous versions

### ISSUE THREAD

**Issue by zluzunov** [joomla/joomla-cms#10645]
#### Steps to reproduce the issue
1. Open admin site on a Joomla installation, on a desktop computer, with default admin template
2. The webs site needs to have a large number (20+) of categories on several levels (2+). For menus 6+ menus, each with 10+ entries
3. Go to articles or menus
4. Select several items
5. Use batch button
6. In the batch popup try to copy articles between categories or to menu items between menus. this is a comman task when using Joomla multilingual

#### Expected result
The batch processing in Joomla 3, versions before 3.5 was much more user-friendly and less time consuming. It did not take me 3 to 4 tries to select the target category or menu item.

#### Actual result
Drop downs, when there are many categories or menus, are not visible at all. I suppose because of the z-index they fall behind the border of the popup window. See attached screenshot.
with the current batch popup size it take 3 to 4 tries to select the correct target category or menu item
![screen shot Articles Batch](https://issues.joomla.org/uploads/1/6782b0b35332699d66a93ed6222d69af.jpg)
![screen shot Menus Batch](https://issues.joomla.org/uploads/1/87e039bee94af7b7cf68272ed2774001.jpg)

#### System information (as much as possible)
Desktop computer. Joomla 3.5.1, browsers Frefox 46.0.1, Chrome 50

#### Additional comments
This is more a user experience and interface usability issue.

**Comment by brianteeman** [comment]
Thank you for reporting this but it has already been resolved as will be seen in the next release of Joomla 3.6
