### ISSUE TITLE
"Configure ACL & Options" action : wrong "Calculated Settings"

### ISSUE THREAD

**Issue by ladyjer** [joomla/joomla-cms#10655]
#### Steps to reproduce the issue
Grant a group the "Configure ACL & Options" Action on a component. Choose a group that has no any other permission on that component (nor inherited neither allowed). Joomla! calculates settings as the group has become a super user for that component.

![screen shot 2016-05-28 at 08 11 13](https://issues.joomla.org/uploads/1/63bb7dd5c4838a7e13d3c372f7f16499.jpg)

#### Expected result
A user that belongs to that group must be able to access that component back-end panel, edit, delete, create objects inside that component.

#### Actual result
The user cannont access the administrator panel of the component

![screen shot 2016-05-28 at 08 16 32](https://issues.joomla.org/uploads/1/9eb45b73871f096fdabbadb744af0723.jpg)

#### System information (as much as possible)

Joomla! 3.6.0-alpha2-dev

#### Additional comments
If I force the access to the administration panel this way:

![screen shot 2016-05-28 at 08 20 29](https://issues.joomla.org/uploads/1/9eaa1253b662c6b19b8d4f26caf3e28f.jpg)

I get the access to the administration panel of the component, but still can't edit, delete, create. I've got to force all single actions (granting 'Allow') to get the full control of the component.

PBFIT

**Comment by infograf768** [comment]
see also #10552

**Comment by brianteeman** [comment]
Closed as it looks like this has been resolved by #10793 - if it hasnt been then it can always be reopened
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10655">issues.joomla.org/joomla-cms/10655</a>.</sub>
