### ISSUE TITLE
access.xml - I can't change the value of my personnal action

### ISSUE THREAD

**Issue by fuscage** [joomla/joomla-cms#10651]
#### Steps to reproduce the issue
go to the access.xml (for example in administrator\components\com_content) and create these news actions  : 
- action name="core.edit.published_state" title="MyTitle1" description="MyDesc1" 
- action name="12345678901234567890.12345678901234567890.12345678901234567890" title="MyTitle2" description="MyDesc2" 

like this (I deleted the '<' for the preview) :

	section name="component" />
		action name="core.admin" title="JACTION_ADMIN" description="JACTION_ADMIN_COMPONENT_DESC" />
		action name="core.options" title="JACTION_OPTIONS" description="JACTION_OPTIONS_COMPONENT_DESC" />
		action name="core.manage" title="JACTION_MANAGE" description="JACTION_MANAGE_COMPONENT_DESC" />
		action name="core.create" title="JACTION_CREATE" description="JACTION_CREATE_COMPONENT_DESC" />
		action name="core.delete" title="JACTION_DELETE" description="JACTION_DELETE_COMPONENT_DESC" />
		action name="core.edit" title="JACTION_EDIT" description="JACTION_EDIT_COMPONENT_DESC" />
		action name="core.edit.state" title="JACTION_EDITSTATE" description="JACTION_EDITSTATE_COMPONENT_DESC" />
		action name="core.edit.own" title="JACTION_EDITOWN" description="JACTION_EDITOWN_COMPONENT_DESC" />

		action name="core.edit.published_state" title="MyTitle1" description="MyDesc1" />
		action name="12345678901234567890.12345678901234567890.12345678901234567890" title="MyTitle2" description="MyDesc2" />
	section />

save the file and go to the parameter and try to change both value to allowed

that's doesn't works for "core.edit.published_state", why ?

#### Expected result
save the "allowed" rigth to the action "core.edit.published_state"

#### Actual result

the result of "core.edit.published_state" stay "herited"

#### Additional comments

In joomla 3.3 it was ok

**Comment by brianteeman** [comment]
Reset issue priority according to documented standards https://docs.joomla.org/Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10651">issues.joomla.org/joomla-cms/10651</a>.</sub>

**Comment by bertmert** [comment]
Don't use underscores. Just [a-z].
core.edit.publishedstate

**Comment by fuscage** [comment]
Thanks for your reply, indeed, without the "_" it's ok but it is a "workaround"? Or in the futur Joomla specifies this new rules (for the name of the action) ? Because in Joomla 3.3 it's was ok...

**Comment by bertmert** [comment]
> Because in Joomla 3.3 it's was ok...

Ah, OK, I didn't know that.

**Comment by brianteeman** [comment]
Closed as yu have resolved your issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10651">issues.joomla.org/joomla-cms/10651</a>.</sub>
