### ISSUE TITLE
[com_checkin] Date creation is unknown.

### ISSUE THREAD

**Issue by shur** [joomla/joomla-cms#10661]
#### Steps to reproduce the issue
Go to Administration panel > Extensions: Manage > Search Tool: Select type - Component
All components from Joomla Project have filled Date column, with the exception for Check-in component.
Сomponent Check-in > Date: Unknown

in `/administrator/components/com_checkin/checkin.xml` missing creationDate string e.g.:
`<creationDate>April 2006</creationDate>`

#### Additional comments
This can be easily remedied, if only to know what date to insert here?

**Comment by JoomliC** [comment]
I'm working on a PR to bump version, and seen that too ;-)
So, you can create the PR to add create date, and add May 2016<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10661">issues.joomla.org/joomla-cms/10661</a>.</sub>

**Comment by shur** [comment]
Ok, and what about Language component that have only year in date column?

**Comment by shur** [comment]
2 PR added ;)

**Comment by alikon** [comment]
@shur ops parallel working

**Comment by alikon** [comment]
@shur can you please  close this issue cause we have 2 PR

**Comment by alikon** [comment]
thank you
