### ISSUE TITLE
PHP 7.0.7 backend menu notice

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#10660]
#### Steps to reproduce the issue
Install PHP 7.0.7
Turn Error Reporting to Development
Load backend

#### Expected result

No errors

#### Actual result

Notice: Only variables should be passed by reference in \administrator\modules\mod_menu\tmpl\default_enabled.php on line 23

#### Additional comments

Fix: remove $ reference in JAdminCssMenu::addChild() arguments.

**Comment by brianteeman** [comment]
Pretty certain this has already been reported and a pr submitted. On my
phone right now so it is hard to check

**Comment by SharkyKZ** [comment]
#10452 

This can be closed as duplicate.

**Comment by sovainfo** [comment]
Also, the fix proposed is wrong. The proper fix is to remove the &, not the $ !. 
Fortunately, that is what is implemented with #10452.

**Comment by Denitz** [comment]
Sure &, sorry, I was in hurry :)
