### ISSUE TITLE
[com_content]allow chaning of the db query for articles through plugins

### ISSUE THREAD

**Issue by algisinfo** [joomla/joomla-cms#10668]
Allowing the change of the db query for the articles displayed by com_content will allow better search functions developed for extensions that use articles (like j2store or fieldsattach).

**Comment by mbabker** [comment]
It's been brought up before and usually shot down adding plugin events which allow query manipulation.

**Comment by brianteeman** [comment]
@mbabker so are you shouting it down again or not?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10668">issues.joomla.org/joomla-cms/10668</a>.</sub>

**Comment by mbabker** [comment]
I'm not a fan of any event at any point in the system that allows database queries to be manipulated.  That to me opens the door for far more issues than benefits, including altering the expected dataset (removing expected fields).

**Comment by brianteeman** [comment]
Closing it then. Thanks
