### ISSUE TITLE
Unwanted characters in the alias

### ISSUE THREAD

**Issue by KapulaGabor** [joomla/joomla-cms#10672]
#### Steps to reproduce the issue
Install Joomla_3.5.1 and install Hungarian language pack
http://community.joomla.org/translations/joomla-3-translations.html#hu-hu

Set the front end language to Hungarian but the admin still English.
Create a new Category or Article like this: "közös" and the alias result will be "koezoes" instead of "kozos". Same for letter "ü" = "ue" instead of "u".

If you set the site admin to Hungarian, the characters will be okay. 
So "ö" will be "o" and "ü" will be "u" as we wanted.

I discussed it with our Hungarian translator and we would like to correct this.

Thank you very much.

**Comment by bertmert** [comment]
On the other hand e.g. in German it's correct to convert umlauts like ü to ue.

**Comment by brianteeman** [comment]
What is the content language?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10672">issues.joomla.org/joomla-cms/10672</a>.</sub>

**Comment by KapulaGabor** [comment]
The content language is Hungarian.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10672">issues.joomla.org/joomla-cms/10672</a>.</sub>

**Comment by andrepereiradasilva** [comment]
i think this has been fixed with https://github.com/joomla/joomla-cms/pull/10348 which is already merged.
Can you test in joomla 3.6.0 alpha 1 or latest staging?

**Comment by csbalazs** [comment]
It's ok in 3.6.0 alpha 1.
![image](https://cloud.githubusercontent.com/assets/1657924/15636049/14f8eef8-25f3-11e6-8a37-6d204539ca14.png)

**Comment by brianteeman** [comment]
Great - we can close this then

**Comment by infograf768** [comment]
Default transliteration in core (when not overriden by a specific language transliteration in xx-XX.localise.php) is here:
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/language/transliterate.php

As you can see
`'u'		=>	'u,ù,ú,û,ü,ũ,ū,ŭ,ů,ű,ų,у',`
`ü` is fine and would never give `ue`
but
`'oe'	=>	'œ,ö',`

`ö` indeed gives an `oe` (as used in German).
