### ISSUE TITLE
SEF mode Links from Numeric Tag Won't work in Popular Tags module

### ISSUE THREAD

**Issue by pmleconte** [joomla/joomla-cms#10689]
#### Steps to reproduce the issue
Create a numeric tag in an article and create a new Popular Tags module, using the cloud display option. 

#### Expected result
Display an article which is tagged by the numeric tag.

#### Actual result
404 Error

#### System information (as much as possible)
Joomla 3.5.1/php 7.0/mysql 5.7.11/ SEF mode

#### Additional comments
To correct this, modify modules/mod_tags_popular/tmpl/cloud.php, line 46 should contain
...$item->tag_id . **'-'** . $item->alias)...
instead of 
...$item->tag_id . ':' . $item->alias)...

**Comment by andrepereiradasilva** [comment]
If you already have the solution please open a a Pull Request (PR).

More info http://extensions.joomla.org/blog/item/how-to-contribute-to-joomla-through-github

**Comment by wojsmol** [comment]
@pmleconte @andrepereiradasilva Please test https://github.com/joomla/joomla-cms/pull/10693

**Comment by brianteeman** [comment]
Closed as we have a pr
