### ISSUE TITLE
Template Protostar: favicon not showing when Joomla is in a subfolder

### ISSUE THREAD

**Issue by JurgenG** [joomla/joomla-cms#10684]
#### Steps to reproduce the issue
1. Create a LAMP setup (root: /var/www/html)
2. Install Joomla in the folder /var/www/html/default
3. Go to http://localhost/default/index.php

#### Expected result
The default favicon.ico shows in the tab

#### Actual result
The favicon.ico file is not found. The browser looks for http://localhost/favicon.ico and not for http://localhost/default/favicon.ico

#### System information (as much as possible)
See attached system info

#### Additional comments
[systeminfo-2016-05-30T21-58-27+02-00.txt](https://issues.joomla.org/uploads/1/d7f10dfd17c6b31d78160e7896fc900e.txt)

**Comment by roland-d** [comment]
@JurgenG I run all my test sites in a WAMP setup with subfolders and don't see the issue there nor on my Mac with LAMP setup and subfolders. What is in the source code for the favicon?

**Comment by zero-24** [comment]
what browser do you use for testing? If i recall correctly there is such a issue with the IE?

**Comment by JurgenG** [comment]
I'm using Chrome (version 51) and Firefox (version 48) - both on Linux.
But this is an issue that is showing in the source code (plain HTML)

This is in the source code:
<link href="/templates/protostar/favicon.ico?random=796167" rel="shortcut icon" type="image/vnd.microsoft.icon" />
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10684">issues.joomla.org/joomla-cms/10684</a>.</sub>

**Comment by JurgenG** [comment]
so here's the code again:
```html
<link href="/templates/protostar/favicon.ico?random=796167" rel="shortcut icon" type="image/vnd.microsoft.icon" />
```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10684">issues.joomla.org/joomla-cms/10684</a>.</sub>

**Comment by roland-d** [comment]
That doesn't look like my site:
```
<link href="/joomla-cms/templates/protostar/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon" />
```

What is that **random=796167** doing in your URL?

**Comment by brianteeman** [comment]
@jurgenG Please can you reply to the comment above or we will have to conclude that this is not a core joomla issue and will close<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10684">issues.joomla.org/joomla-cms/10684</a>.</sub>

**Comment by JurgenG** [comment]
My apologies. This indeed is not a core issue.
I forgot that I installed Joomla My Little Helper - won't use it again, it does all kinds of tracking oddities...

**Comment by ggppdk** [comment]
Even if you don't use it, it is good to report your findings to the author of the plugin, thus bugs can be fixed, also some issues are not bugs they are results of configuration
