### ISSUE TITLE
Probably outdated file in components/com_contact

### ISSUE THREAD

**Issue by jo-sf** [joomla/joomla-cms#10694]
In searching for all XML forms that define the field "custom_reply" I found beside some other files the file

`components/com_contact/models/forms/form.xml`

But when I checked the contents of this XML file and compared it with the other XML files I found I had the strong suspicion that this file is no longer up-to-date and is no longer used.

Main reason for this suspect is that some of the message defines used in that XML file don't exist in any language file, e.g. "CONTACT_CONFIG_CUSTOM_REPLY_DESC" or "Contact_Email_BANNED_SUBJECT_DESC" (note the upper/lower case form).

Can you please check whether this XML file is still in use?

**Comment by bertmert** [comment]
Yes, it's outdated since J!1.6.? when contact was moved to JForm. form.xml was replaced by contact.xml then.
https://github.com/joomla/joomla-cms/commit/a34dd3dfed79effd990b1f64eee178bd5b9aeff5#diff-bcdc310b6bd770234bbf93e90ba81937

Found no issues in com_contact after I've deleted form.xml from current staging installation.

**Comment by bertmert** [comment]
Please test https://github.com/joomla/joomla-cms/pull/10730

**Comment by brianteeman** [comment]
I am guessing that it was kept originally because a third party template
could be using it and unless it has been marked as deprecated we cant just
remove it.

On 5 June 2016 at 09:55, bertmert <notifications@github.com> wrote:

> Please test #10730 <https://github.com/joomla/joomla-cms/pull/10730>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10694#issuecomment-223800867>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8ZCXNcOFePAxoy2VhI84wzpgKt2Eks5qIo8FgaJpZM4IqvQU>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by jo-sf** [comment]
@brianteeman 
Even if this file has been kept because it is or was probably used by a third-party template it will no longer work today since the message defines used in that XML file no longer exist in any .ini file. So if any template should really still use this file (or depends upon the existence of this file) this template itself is IMO outdated and should be changed accordingly.

You say that the XML file should be marked as deprecated prior that it can be removed. How can you mark an XML file as deprecated? I've seen functions being marked that way - but XML files?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10694">issues.joomla.org/joomla-cms/10694</a>.</sub>

**Comment by brianteeman** [comment]
Fair point. Can you submit a PR to remove it?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10694">issues.joomla.org/joomla-cms/10694</a>.</sub>

**Comment by jo-sf** [comment]
Please see PR #10786 

This PR currently only removes the file form.xml from future versions.

I think the file shall be added to `administrator/components/com_admin/script.php` but I'm not sure with which Joomla version this patch will be applied.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10694">issues.joomla.org/joomla-cms/10694</a>.</sub>

**Comment by infograf768** [comment]
To consider it as deprecated but still let use it for B/C (unlikely used but one never knows...), it should not be added to deleteUnexistingFiles() in script.php.

**Comment by mbabker** [comment]
Then it can't be deleted at all because then it's inconsistent (the file exists on sites created and updated from 1.6 to 3.5.1 but not 3.6 or later).  Either it goes completely away in one pull request or it stays in the system.

**Comment by brianteeman** [comment]
Closed as there is a PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10694">issues.joomla.org/joomla-cms/10694</a>.</sub>
