### ISSUE TITLE
Contact field in repeatable field

### ISSUE THREAD

**Issue by cdekok** [joomla/joomla-cms#10691]
I needed this for contact_modal but i think this is related to all fields that use modals.
the button does nothing when you hit it, now bootstrap does not allow modals in modals i believe.

is it really necessary to add the modal for repeatable fields can't we change it so that the add / remove buttons are rendered behind the field. It would provide easier access to edit the form to.

**Comment by brianteeman** [comment]
Yes you are correct bootstrap doesnt allow a modal within a modal. So unfortunately it isnt possible to do what you want with a repeatable field. But the good news is that in Joomla 3.6 there is a new way of doing this called subform - see https://github.com/joomla/joomla-cms/pull/7829 -  which should let you achieve what you want to do<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10691">issues.joomla.org/joomla-cms/10691</a>.</sub>
