### ISSUE TITLE
Keepalive Behavior Not HTML4/5 compatible

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#10697]
#### Steps to reproduce the issue

A combination of https://github.com/joomla/joomla-cms/pull/9665 and the HTML5 declarations for the core templates has caused the keepalive behavior to misbehave in the backend.  Unencoding the ampersand makes it work again.

#### Expected result

A request to `administrator/index.php?option=com_ajax&format=json` with a 200 response

#### Actual result

A request to `administrator/index.php?option=com_ajax&amp;format=json` with a 404 response

#### Additional comments

Checking `$doc->isHtml5()` isn't enough here because the core templates set this flag when they get rendered, long after the component is rendered and calls this behavior.

**Comment by andrepereiradasilva** [comment]
that i know of there is no html error in having keepalive without the `&amp;` in html5 ...

For render as XHTML the problem is not the `&`, the problem is that for correct xhtml rendereing the scipts should be inside a `<![CDATA`

Example:

This **does** gives error** in w3c validator
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<title>Home</title>
	<script type="text/javascript">
		var a="/index.php?option=com_ajax&format=json";
	</script>
</head>
<body>
	<p>&nbsp;</p>
</body>
</html>
```

This **doesn't gives error** in w3c validator
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<title>Home</title>
	<script type="text/javascript">
	//<![CDATA[
		var a="/index.php?option=com_ajax&format=json";
	//]]>
	</script>
</head>
<body>
	<p>&nbsp;</p>
</body>
</html>
```

**Comment by andrepereiradasilva** [comment]
More info see, for instance, http://javascript.about.com/library/blxhtml.htm

**Comment by andrepereiradasilva** [comment]
IMHO solution https://github.com/joomla/joomla-cms/pull/9665 doesn't make sense because you are making a ajax call with a incorrect URL.

i think it as noting to do with the html5 change.

**Comment by andrepereiradasilva** [comment]
so first let's correct keepalive url.

And them we could try to fix xml errors

**Comment by andrepereiradasilva** [comment]
PR to fix the keealive URL part https://github.com/joomla/joomla-cms/pull/10698

**Comment by andrepereiradasilva** [comment]
actually the CDATA is already in  JDocument html render

See https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/document/renderer/html/head.php#L254-L258

**Comment by andrepereiradasilva** [comment]
so IMO this should be closed.

**Comment by zero-24** [comment]
Set to "closed" on behalf of @zero-24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10697">issues.joomla.org/joomla-cms/10697</a>
