### ISSUE TITLE
User Profile Plugin: if "Terms of Service" are not accepted, user can still register

### ISSUE THREAD

**Issue by pmleconte** [joomla/joomla-cms#10690]
#### Steps to reproduce the issue
User Profile Plugin, select "Required" on "Terms of Service" option and select any article in "article Terms of service"
Create a new user thru frontend menu, leave "no" in "accept the tos", the new user is still created

#### Expected result

Should display an error message: 
Please read the Terms of Service. You will not be able to register if you do not agree with them.

#### Actual result
No error message, user is created

#### System information (as much as possible)
Joomla 3.5.1/php 7/ mysql 5.7

#### Additional comments
To correct this, the line 376 of the file plugins/user/profile/profile.php should contain 
if (($task == 'register') && ($tosenabled) && ($tosarticle) && ($option == '**com_users**')) 
instead of 
if (($task == 'register') && ($tosenabled) && ($tosarticle) && ($option == 'com_user'))

**Comment by SharkyKZ** [comment]
Duplicate #9792.

**Comment by infograf768** [comment]
Please close issue.

**Comment by roland-d** [comment]
Closed as duplicate.
