### ISSUE TITLE
Module/menu batch popup select overflow hidden.

### ISSUE THREAD

**Issue by joris85** [joomla/joomla-cms#10709]
#### Steps to reproduce the issue
Select module and click on batch.
If your want to move it to a menu item the popup disappears behind the overflow scroll.
Problem:
https://www.dropbox.com/s/0dq7zbxm6r8zqap/Screenshot%202016-06-02%2012.25.40.png?dl=0

#### Expected result
I would expect that i can see the whole list without scrolling.
Just like a dropdown.

Would expect:
https://www.dropbox.com/s/ow7r4wsv5e2kh8n/Screenshot%202016-06-02%2012.25.59.png?dl=0

I added custom css to the template:
.admin .modal-body {
 overflow: visible !important;
}

No idea if this breaks anything else but it works well for this problem.

Any ideas?

**Comment by brianteeman** [comment]
Thanks for reporting this. 
This has already been identified and fixed for the next release of Joomla
