### ISSUE TITLE
Sub Form Field (small problems)

### ISSUE THREAD

**Issue by WS-Theme** [joomla/joomla-cms#10718]
That's really awesome and working very well!! However I have noticed two things:

1) Form Field Media: It's not possible to add preview="true" to get the Image permanent next to the Field

2) Form Field Radio: It's not possible to add class="btn-group" to transform the Radio Buttons to the Styled Version of Radios. It works but only the first time! When adding a new Field it stops working

![screen shot 2016-06-03 at 04 28 43](https://issues.joomla.org/uploads/1/d70b00887361dea8fc02b76e0fb391ad.png)

**Comment by dgt41** [comment]
@WS-Theme for the 1st issue: can you try the repeatable with the layout overrides from :https://github.com/joomla/joomla-cms/pull/5871 (the one on the protostar template) and report back if that solves the problem?

**Comment by ufuk-avcu** [comment]
I have the first issue also:
![administrator_index php](https://cloud.githubusercontent.com/assets/13818234/15936911/1275dd58-2e6d-11e6-9a47-cdd652cc6422.png)

**Comment by Fedik** [comment]
@ufuk-avcu add `class="advancedSelect"` to your `list` fields

**Comment by ufuk-avcu** [comment]
@Fedik thank you. How to solve the problem from the first screenshot, with the radio buttons?

**Comment by Fedik** [comment]
It is more complicated.
For fix the styling of the radio buttons  need to rewrite part of `/administrator/templates/isis/js/template.js` that responsible for it. For now that script work only on `doomready` and do not have possibility to call it for the dynamic content.

**Comment by ufuk-avcu** [comment]
@Fedik another Problem within a SubFormField: The showon Attribute don't works as excepted. If you use showon for a textfield and add an additional row, this field is shown by default. If you save the page, then the showon attribute Works as expected. Have you an idea to fix this?

**Comment by Fedik** [comment]
Unfortunately I do not have a fix. The reason is the same, the "showon" script do not see the fields wich added dynamically.

Let's hope the brave man, who can fix it, will appear soon :smile:

**Comment by titusvk** [comment]
I guess the best way to solve those problems with js initialisation is the use of a callback function similar to tinyMCEs. All fields with js should support it.

**Comment by Orsey** [comment]
After adding new row I seen elements with same IDs (look screenshot)
![image](https://user-images.githubusercontent.com/2915062/31663910-36b5945a-b34c-11e7-9da8-60f955881270.png)

**Comment by Fedik** [comment]
@Orsey nice painting 😄 
but your issue already was fixed in `joomla:staging` #16480

**Comment by brianteeman** [comment]
Closed as stated above
