### ISSUE TITLE
TinyMCE doesn't save empty value for Prohibited Elements

### ISSUE THREAD

**Issue by titusvk** [joomla/joomla-cms#10717]
#### Steps to reproduce the issue

Open TinyMCE Plugin
Remove all Prohibited Elements script,applet,iframe
Click Save

#### Expected result

Field Empty after Save

#### Actual result

Field shows default values after save

#### System information (as much as possible)

Joomla 3.51

**Comment by infograf768** [comment]
this is an old issue. Just enter a space.

**Comment by zero-24** [comment]
Or enter something like cms (see the tooltip)

**Comment by zero-24** [comment]
With 3.6 there will be a switch to use the joomla filter settings for tinymce too

**Comment by infograf768** [comment]
this can be closed imho

**Comment by titusvk** [comment]
yes, thanks
