### ISSUE TITLE
New ACL module permission - limit module edit from frontend

### ISSUE THREAD

**Issue by yild** [joomla/joomla-cms#10715]
In current modules permissions tab there are only limited forms of permission settings:
Delete, Edit, Edit state and Frontend editing, three of which are only for backend purpose.

When I want to allow user/group to Edit via Frontend they can edit ALL* module: module settings (title, position, publish dates and so one). Why not to split Frontend editing to (at least) two permissions:
- Frontent state editing
- Frontent content editing

Why I think that Frontend editing is not enough, example for a Custom module:

Users are not allowed to edit Categories Description without giving them access to backend, I thought that I can simulate category description by using Custom module and allow user/group to edit its content - and content only, atm with Frontend editing users can edit all settings, further it may overwhelm them - to many unnecessary 'dangerous' options.

*that's overstatement but still..

**Comment by brianteeman** [comment]
Sorry but as there has been no interest by anyone in moving forward with this feature request I am going to close it,
