### ISSUE TITLE
Code evaluation error with MacGDBp on index.php

### ISSUE THREAD

**Issue by franzpeter** [joomla/joomla-cms#10714]
#### Steps to reproduce the issue
I am working on a Mac using MAMP. PHP version is 7.0.0 I have activated Xdebug and use MacGDP. Joomla version is 3.5.1. If calling the Joomla homepage (i.e.index.php) it complains about that: define('JOOMLA_MINIMUM_PHP', '5.3.10');
Using the evaluation button to get a window to enter and verify that code the result of entering:
define('JOOMLA_MINIMUM_PHP', '5.3.10');
is:
error evaluating code

#### Expected result
NO error for index.php

#### Actual result
error evaluating code

#### System information (as much as possible)
Joomla 3.5.1, php 7, MAMP with debug and MacGDBp![screen shot 2016-06-02 at 08 58 30](https://issues.joomla.org/uploads/1/25b803a980c7cb29ba35623803bcf085.png)

#### Additional comments
The same occurs too for the administrator/index.php

**Comment by mbabker** [comment]
It's an error with that platform that needs to be reported to those developers.  That line of code is perfectly valid PHP syntax.
