### ISSUE TITLE
[plg_search_tags] Search results include unpublished, archived and trashed tags.

### ISSUE THREAD

**Issue by EmilMassey** [joomla/joomla-cms#10712]
#### Steps to reproduce the issue
1. Make sure _Search - Tags_ plugin is enabled
2. Create a tag
3. Unpublish, archive or trash it
4. Type a tag name in a mod_search module.

#### Expected result
Search results shouldn't include unpublished tags.

#### Actual result
Unpublished, archived or trashed tags are listed on search results site.

**Comment by brianteeman** [comment]
Closing this as we have a Pull Request

@EmilMassey you dont need to create a n issue on the tracker and a pull request on github. The issue tracker is super clever and will automatically create an issue when you create a pull request<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10712">issues.joomla.org/joomla-cms/10712</a>.</sub>
