### ISSUE TITLE
"List of all tags" menu item does not show site name in page title if requested

### ISSUE THREAD

**Issue by Giuse69** [joomla/joomla-cms#10725]
#### Steps to reproduce the issue
Create a menu item of type "List of all tags".
In Global Settings - SEO, set Include site name in page title to Before (or After).
Go to front end and click to that menu item of list of all tags

#### Expected result
Page title in the browser should include site name and then the menu item name.

#### Actual result
Page title does not include site name.

**Comment by bertmert** [comment]
Confirmed. I'll provide PR

**Comment by bertmert** [comment]
Please test https://github.com/joomla/joomla-cms/pull/10727

**Comment by brianteeman** [comment]
Closed as we have a PR for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10725">issues.joomla.org/joomla-cms/10725</a>.</sub>
