### ISSUE TITLE
"List of all tags" menu item incompatible with caching

### ISSUE THREAD

**Issue by Giuse69** [joomla/joomla-cms#10724]
#### Steps to reproduce the issue
Create a tag A with subtags A1, A2.
Create a tag B with subtags B1, B2.
Create a menu item MENU_A of type "list of all tags" for A to show all tags below A.
Create a menu item MENU_B of type "list of all tags" for B to show all tags below A.
Enable caching.
Go to frontend and click on MENU_A: you get the list of subtags of A.
Now click on MENU_B

#### Expected result
you must get the list of subtags of B.

#### Actual result
the URL in the browser changes with MENU_B but the same page is reloaded showing MENU_A.

**Comment by mbabker** [comment]
Unless there's a typo in your instructions you're getting the desired
behavior?

**Comment by Giuse69** [comment]
Hi, no, I am not getting the correct behavior: the first menu item that is selected makes Joomla! render the correct page, the second click on the other menu item shows the first page again and not the second one, though the URL has changed in the correct one.
So:
click on MENU_A => URL of MENU_A displayed and PAGE_A shown
click on MENU_B => URL of MENU_B displayed but PAGE_A shown
The same happens if clicking first on MENU_B and after on MENU_A: I get always MENU_B also if I click on MENU_A the second time.
is it more clear?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10724">issues.joomla.org/joomla-cms/10724</a>.</sub>

**Comment by bertmert** [comment]
Confirmed for current staging. Will provide PR.

**Comment by bertmert** [comment]
Please test https://github.com/joomla/joomla-cms/pull/10728

@Giuse69 You just have a typo in your instructions "...for B to show all tags below A."

**Comment by brianteeman** [comment]
Closed as we have a PR for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10724">issues.joomla.org/joomla-cms/10724</a>.</sub>
