### ISSUE TITLE
missing slashes in URL with activated SEF if link target is not in menu

### ISSUE THREAD

**Issue by lyrischesich** [joomla/joomla-cms#10736]
#### Steps to reproduce the issue
Turn on SEF in Backend and create (with JCE-Editor) a link to an article that is not linked in any menu. In my case I got:

```
index.php?option=com_content&amp;view=article&amp;id=677:gespraechsforum-handy-in-der-schule&amp;catid=261:medienbildung&amp;Itemid=472
```
(Where the appended Itemid 472 is the one of the main menu which is okay for me.)

#### Expected result
I am expecting a SEF url that points to the selected article:
```
http://www.humboldtschule-berlin.de/261-humboldt-gymnasium/profil/medienbildung/677-gespraechsforum-handy-in-der-schule
```

#### Actual result
I got the right url, but all slashes after the hostname-part are missing: 
```
http://www.humboldtschule-berlin.de/261-humboldt-gymnasiumprofilmedienbildung677-gespraechsforum-handy-in-der-schule
```
#### System information (as much as possible)
Joomla! 3.5.1 Stable [ Unicorn ] 05-April-2016 22:45 GMT
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 
PHP  5.4.45-0+deb7u3 
Apache

#### Additional comments
Adding the following 3 lines before the `return`-statement in the `build`-function of the `ContentRouter`-class (in the file `./components/com_content/router.php`) fixed the problem for me, but I am pretty shure that this is not the right solution:
```php
for($i=0;$i<count($segments)-1;$i++) {
   if(strlen($segments[$i])>0) $segments[$i] = $segments[$i]."/";
}
```

**Comment by bertmert** [comment]
I cannot confirm in current staging Joomla (3.6.0-alpha...).

Tested TinyMCE and JCE.

- Activated SEO.
- Created new category in first level. (Alias: first-level-new)
- Created new article in this category. (Alias: article-first-level-new)
- Opened another article.
- Inserted link with editor Link Button:

```
<a href="index.php?option=com_content&amp;view=article&amp;id=73:article-first-level-new&amp;catid=78:first-level-new&amp;Itemid=435">Link without menu</a>
```

Got link in FE:

```
<a href="/78-first-level-new/73-article-first-level-new">Link</a>
```

**Comment by brianteeman** [comment]
I cannot confirm this either. 
It sounds like it must be an issue with your specific site. Please use the forum for support http://forum.joomla.org or http://forum.joomla.de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10736">issues.joomla.org/joomla-cms/10736</a>.</sub>
