### ISSUE TITLE
Languages Flags not for high resolution devices

### ISSUE THREAD

**Issue by Chacapamac** [joomla/joomla-cms#10734]
#### • Steps to reproduce the issue

In multi-language situation the frontend flags (Language switcher) are not optimized for high resolution devices. As example the English (GB) look bad on mobile or high resolution device.
#### • Expected result

The flags should be at least 2 time the size and reduced to half in the frontend to look good on all devices.
They should also be reduced in the backend (Administration) to not appear to big.
#### Actual result

I personnally replace the original Joomla flags I used with bigger flags that I reduced by CSS, but the backend is way more difficult to style. I end-up with admin section with flag 2 time bigger. Don’t look to good but at least the frontal flags appear nice on all devices.
#### System information (as much as possible)
- Joomla 3.5.1 and lower
- Try in multiple browser
#### Additional comments

Not a big issue but not really Pro as everybody using Joomla on High def and mobile devices multilingual site see the problem

**Comment by brianteeman** [comment]
@infograf768 where do we get the flags from? Maybe they have larger size available?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10734">issues.joomla.org/joomla-cms/10734</a>.</sub>

**Comment by dgt41** [comment]
@brianteeman I would suggest to replace the old gifs with these https://github.com/lipis/flag-icon-css

**Comment by infograf768** [comment]
We got them from various sources. Sometimes made them to size from larger ones found on the Net. Sometimes made them up totally (Tamil).

@Chapacamac

The solution for you is simple: do NOT delete the flags existing as anyway they are used in back-end.
If you want to use bigger flags (you have to make them) in frontend, make an override for the langswitcher module (mod_languages/default.php) in your template html folder. For example:
replace every occurence of
`$language->image . '.gif'` by
$language->image . '.png'

and add the new .png files in media/mod_languages/images/

**Comment by brianteeman** [comment]
Seems a good idea to me. If we can fix an issue in core then we shouldn't
tell people to make an overr

**Comment by andrepereiradasilva** [comment]
i don't know if the flags used by crowin are fre to use, but they are png and have a nice definition
if a decision to change the language flags to png is done, it seems a good start point...

**Comment by dgt41** [comment]
@brianteeman it can be done with no B/C break: https://css-tricks.com/svg-fallbacks/

@andrepereiradasilva good idea, but still svg is a better format (scalable)

**Comment by andrepereiradasilva** [comment]
you meand svg with fallback: svg > png > gif?
ie8 and some old browsers does not support svg right? http://caniuse.com/#feat=svg

**Comment by dgt41** [comment]
Yup! Use svg for good browsers and fall back to our gifs for IE8

**Comment by dgt41** [comment]
I've already started some work on this but there are too many files that need to be renamed and that's a boring process. Some day, with no actual work, I will finish this. I guess I can publish the branch if someone wants to do the remapping...

**Comment by brianteeman** [comment]
go for it

**Comment by Chacapamac** [comment]
For the flags, I will start with vector (Adobe Illustrator) Files
Not sure of the copyright of these set of 6 files for a total of 287 flags (Seem REALLY Precise…)
Find here —> http://all-free-download.com/free-vector/download/various-of-world-flags-vector-set_525993.html
Author —> http://freedesignfile.com/29665-various-of-world-flags-vector-set-04/
File Source —> http://www.zcool.com.cn

License: Creative Commons (Attribution 3.0)

Not sure if usable, 

I saw good set to sale ($10) where I get my photos (License only restriction “Not for Resale Item”)

**Comment by dgt41** [comment]
@Chacapamac svgs ARE vector and from https://github.com/lipis/flag-icon-css the license is ok to use in joomla

**Comment by mbabker** [comment]
IIRC the flags are being revisited in 4.0 (and I think there's either an issue or PR somewhere for that), at this point I don't think we're going to change them in 3.x.

**Comment by Bakual** [comment]
Some discussion is here: https://github.com/joomla/joomla-cms/pull/12014

**Comment by C-Lodder** [comment]
Some of the SVG's for these flags are huge. IIR, one of them was about 480kb

**Comment by brianteeman** [comment]
Closing here as @mbabker stated they are not going to be changed for 3.x and we have an issue for 4.x #12014

**Comment by Chuda515** [comment]
Can [PSD File](http://psdpedia.com "") be Supported.. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10734">issues.joomla.org/tracker/joomla-cms/10734</a>.</sub>
