### ISSUE TITLE
To discuss: Overrides in Joomla! select-field and identification.

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#10743]
I´d like to discuss with you the override selection field and overrides in general.
For now the selection field for example is at the article options at the very bottom.

I think that the overrides will become more and more important (also for example with the new custom fields) and should be better recognizable and reachable by the administrator. I think it´s important to see fast, if an article (or a category or field ...) is using an override and if so which one. 

Also i feel like it would be nice to have the possibility to override just the plain "content area" 
For example with custom fields i wouldn´t want to change the whole article output - just the area between the tags `<div itemprop="articleBody">` - by "excluding" this area into another override i´m more save when the main layout it updated / improved.

For many projects i´m starting to lose the overview what is overridden by what. Could be of course just my issue/opinion but maybe something to improve?

Would be happy to hear your thoughts about this.

**Comment by brianteeman** [comment]
Something like this?

![screen shot 2016-06-07 at 04 37 16](https://issues.joomla.org/uploads/1/dc3f09d5f7004489418e9714cd7b4700.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10743">issues.joomla.org/joomla-cms/10743</a>.</sub>

**Comment by designbengel** [comment]
Yes, thank you Brian! Maybe even at the very top, because it´s so significant how the output will be.

**Comment by brianteeman** [comment]
I guess that we should really rename it as well from "Alternative layout" to just "Layout"

**Comment by designbengel** [comment]
+1

**Comment by proweb** [comment]
+1

**Comment by franz-wohlkoenig** [comment]
i like the Idea of @coolcat-creations and renaming to "Layout" of @brianteeman

**Comment by laoneo** [comment]
Guess we can close this one as we have a PR.
