### ISSUE TITLE
Tag auto-complete in non-latin layout

### ISSUE THREAD

**Issue by Evgentret** [joomla/joomla-cms#10741]
#### Steps to reproduce the issue
Start typing a tag in russian layout, for example. Russian language have letter on a comma button.
When I type this letter - joomla closes the tag, so if I type a Tab button

#### Expected result
When I type comma - tag will close; when I type a letter on a comma button - jommla will not close a tag, and letter has typed correctly in a tag

**Comment by brianteeman** [comment]
This sounds like the identical problem as #10761 so I am closing this here so we just have the conversation in one place<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10741">issues.joomla.org/joomla-cms/10741</a>.</sub>
