### ISSUE TITLE
The new subform field is not responsive #7829

### ISSUE THREAD

**Issue by ufuk-avcu** [joomla/joomla-cms#10769]
#### Steps to reproduce the issue
Go to https://github.com/joomla/joomla-cms/pull/7829 . Here are the testing instructions. What i do in addition is to use this in a Joomla Template and not in a Module.

#### Expected result
If i resize the Browser, it should responsive.

#### Actual result
It's not responsive

#### System information (as much as possible)
J3.6 Beta1
PHP7
MySQL 5.5
Custom Template (not a Framework)
![templates_ edit style -administrator_index php](https://cloud.githubusercontent.com/assets/13818234/15932955/031212a0-2e5e-11e6-84fe-6f9f2197534b.png)

**Comment by Fedik** [comment]
Repeatable field allow to set custom layout, 
by default it use `joomla.form.field.subform.repeatable` (for `multiple` mode),
if you set `joomla.form.field.subform.repeatable-table` then the subform will be rendered in `<table>` and table cannot be responsive , of course.

It expected result.

**Comment by ufuk-avcu** [comment]
@Fedik thank you for your explanation. But is something like this achivable: http://getbootstrap.com/css/#tables-responsive ?

**Comment by mbabker** [comment]
Not in the scope of Joomla 3 since the core is based on Bootstrap 2.

**Comment by ufuk-avcu** [comment]
Ok thank. I close this.
