### ISSUE TITLE
How to create page coupon from Joomla?

### ISSUE THREAD

**Issue by hoangquynhchihn** [joomla/joomla-cms#10766]
i am admin for [ma giam gia](https://giamgiachotui.com "ma giam gia").

Website I'm having problems when large user access and posts. I want to know whether to move to Joomla to speed as well as easy hosting options.

Thanks

**Comment by brianteeman** [comment]
This is the issue tracker for bug reporting. Please use the forum for this type of question http://forum.joomla.org
