### ISSUE TITLE
Matching file extension

### ISSUE THREAD

**Issue by Evgentret** [joomla/joomla-cms#10762]
#### Steps to reproduce the issue
Allowing "zip" extension in parameters of media manager
Uploading file: "name of program ver1.0.11.exe.zip" - FAIL. Work ONLY if I also allow extensions .exe .11 .0

#### Expected result
System checks only last extension of file

**Comment by bertmert** [comment]
It's a security feature not a bug. But I think it's an annoying feature, too.

When a filename contains one of these file extensions with a leading dot somewhere(!) upload will be blocked **at the latest** here:
https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/helper/media.php#L93-L96
That's the case with *ver.exe.zip* but also *ver.exe.quack.copy.zip*

BTW: When I use uppercase *.EXE.zip*  I can upload.

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10762">issues.joomla.org/joomla-cms/10762</a>.</sub>
