### ISSUE TITLE
Regression: Installation cannot procede from step 1

### ISSUE THREAD

**Issue by ot2sen** [joomla/joomla-cms#10765]
#### Steps to reproduce the issue
Standard install of the j36b1 zip 
Installation page show up nicely at step 1 and you can fill in the details.
Clicking either of the 'Next' button doesn´t work. Stuck at step 1

#### Expected result

Expected to move to step 2 when clicking 'Next'

#### Actual result

No action happen when clicking 'Next'

#### System information (as much as possible)
PHP 7.0.7

**Comment by infograf768** [comment]
Changed priority.

Tested with php 5.4.4 and all is fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10765">issues.joomla.org/joomla-cms/10765</a>.</sub>

**Comment by ot2sen** [comment]
Tried same zip locally using PHP 5.6.8 and installation went fine.
The reported problem occurred on a SG account, extracting the zip with their filemanager

**Comment by ot2sen** [comment]
Wiped the fileset and tried re uploading and extract. Installation did start and go to step 1, but again it couldn´t proceed to step 2. 

So I went to cpanel to swap PHP version from 7.0.7 to 5.6 
Trying the installation again and now it did complete all steps and installed as expected.

**Comment by ot2sen** [comment]
PS no problem in swapping back to PHP 7.0.7 after installation. Everything else seems to work fine, except the installation steps

**Comment by ghazal** [comment]
Tested with PHP 7.0.7.
No problem so far.

**Comment by bertmert** [comment]
I don't know what a _SG account_ is but
tested with 7.0.6 and "extract automatically after upload" via FTP GUI at All-Inkl, current staging. No problem.

**Comment by zero-24** [comment]
@bertmert `SG account ` => SiteGround ;)

**Comment by brianteeman** [comment]
Tested with php 7.0.7 on siteground and could ***NOT*** replicate this - had no problem at all
http://36beta.teeman.net//<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10765">issues.joomla.org/joomla-cms/10765</a>.</sub>

**Comment by ot2sen** [comment]
@brianteeman did you use the zip download?
I just tested the Joomla_3.6.0-beta1-Beta-Full_Package.tar.gz  at the same setup and this works without issues and installs as should at the same account using PHP 7.0.7.

Yesterday I used the Joomla_3.6.0-beta1-Beta-Full_Package.zip which didn´t work with PHP 7.0.7, but did work when swapping to PHP 5.6

**Comment by brianteeman** [comment]
I used Joomla_3.6.0-beta1-Beta-Full_Package.zip

On 10 June 2016 at 07:56, ot2sen <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> did you use the zip
> download?
> I just tested the Joomla_3.6.0-beta1-Beta-Full_Package.tar.gz at the same
> setup and this works without issues and installs as should at the same
> account using PHP 7.0.7.
>
> Yesterday I used the Joomla_3.6.0-beta1-Beta-Full_Package.zip which didn´t
> work with PHP 7.0.7, but did work when swapping to PHP 5.6
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10765#issuecomment-225107539>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8VEER-iFSXJx3RpBQjJVkoZTqftUks5qKQqwgaJpZM4IxrXl>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by ot2sen** [comment]
Ok, let me try a fresh download of that again and lets hope it was a temporary stand alone problem for that hosting account yesterday. Will report back :)

**Comment by brianteeman** [comment]
Thanks

On 10 June 2016 at 08:07, ot2sen <notifications@github.com> wrote:

> Ok, let me try a fresh download of that again and lets hope it was a
> temporary stand alone problem for that hosting account yesterday. Will
> report back :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10765#issuecomment-225109027>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8WZZI2FUkiHmFFzHpFxZMz3wfUdbks5qKQ0YgaJpZM4IxrXl>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by ot2sen** [comment]
Confirmed. A fresh download of the zip package, upload/extract/install, today works fine on the same account.
Must have been account specific finding yesterday that is now solved.
Can be closed. Thanks for testing

**Comment by brianteeman** [comment]
Closing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10765">issues.joomla.org/joomla-cms/10765</a>.</sub>
