### ISSUE TITLE
Joomla Backend login creates directory .pki in root of webserver

### ISSUE THREAD

**Issue by balkj** [joomla/joomla-cms#10773]
#### Steps to reproduce the issue
Login to Joomla v3.5.1 Backend creates directory .pki in the root of the webserver. 
After deleting directory .pki, directory is created again during Joomla backend login.

#### Expected result
Not creating any directories during Joomla backend login.

#### Actual result
Creating of directory .pki in the fileserver root.

#### System information (as much as possible)
PHP Built On  Linux webserver01.sylconia.nl 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64  
Database Version  5.1.69-log  
Database Collation  latin1_swedish_ci  
Database Connection Collation  utf8_general_ci  
PHP Version  5.6.22  
Web Server  Apache/2.4.6 (CentOS)  
WebServer to PHP Interface  fpm-fcgi  
Joomla! Version  Joomla! 3.5.1 Stable [ Unicorn ] 05-April-2016 22:45 GMT  
Joomla! Platform Version  Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT  
User Agent  Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko

**Comment by mbabker** [comment]
I'd suggest checking for a third party extension that could be doing this or with your hosting provider.  Joomla core doesn't have anything working with anything PKI related.

**Comment by balkj** [comment]
Issue is already checked with hosting provider. Issue occurred after Joomla upgrade from 3.4.8 to 3.5.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10773">issues.joomla.org/joomla-cms/10773</a>.</sub>

**Comment by brianteeman** [comment]
As Michael said there is nothing in the core of joomla that can create a file. It must be an extension. Please use the forum for support http://forum.joomla.org this site is for reporting bugs and creating features in the core of Joomla<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10773">issues.joomla.org/joomla-cms/10773</a>.</sub>
