### ISSUE TITLE
3.6.0-beta1: Multi TinyMCE editors cause recursion error when inserting image

### ISSUE THREAD

**Issue by tranduyhung** [joomla/joomla-cms#10774]
#### Steps to reproduce the issue

- Install Joomla 3.6.0-beta1
- Create a new article, click "Image" button in TinyMCE to insert an image into article's content, it works.
- Edit administrator/components/com_content/models/forms/article.xml, replace the "metakey" field from

		<field name="metakey" type="textarea"
			label="JFIELD_META_KEYWORDS_LABEL" description="JFIELD_META_KEYWORDS_DESC"
			rows="3" cols="30" />

to

		<field name="metakey" type="editor"
			label="JFIELD_META_KEYWORDS_LABEL" description="JFIELD_META_KEYWORDS_DESC"
			filter="JComponentHelper::filterText" buttons="true" />

- Refresh your article form, check in "Publishing" tab to see if "Meta Keywords" field now becomes a TinyMCE editor instead of textarea field
- Try to insert an image in "Meta Keywords" field or article content field, the image popup is not closed after you click "Insert" button. If you check in browser's developer tool, there is an error , for Chrome it is "Uncaught RangeError: Maximum call stack size exceeded", for Firefox it is "too much recursion", the code causes this problem is

			jModalClose = function() {
				oldClose.apply(this, arguments);
				tinyMCE.activeEditor.windowManager.close();
			};

#### Expected result

Image is inserted into TinyMCE editor and the image popup is closed, no matter how many TinyMCE editors are available on the page.

#### Actual result

Image is inserted successfully but image popup is not closed.

#### System information (as much as possible)

- Joomla! Version: Joomla! 3.6.0-beta1 Beta [ Noether ] 8-June-2016 23:13 GMT
- Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
- Tried on Chrome 51.0.2704.84 and Firefox 45.1.1

**Comment by brianteeman** [comment]
Is this new in 3.6 or did this problem exit before?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10774">issues.joomla.org/joomla-cms/10774</a>.</sub>

**Comment by dgt41** [comment]
@tranduyhung was the cursor set to the editor in position metakey (did you click inside the editor, before clicking the insert button) ? 
This might happen with current code if the editor is not set as active and there are more than one instances (I can figure out that by reading the code above). There might be an easy solution for that, will check it this weekend

**Comment by tranduyhung** [comment]
@brianteeman This problem doesn't exist in 3.5.x or older 3.x releases.
@dgt41 Yes the cursor was in the editor and the image was inserted at the cursor's position successfully. the only problem was the image popup was not closed after image was inserted into editor.

**Comment by tranduyhung** [comment]
This issue still exists in RC. My only solution for now is switching to another editor like JCE.

**Comment by dgt41** [comment]
Please test #11048

**Comment by dgt41** [comment]
Set to "closed" on behalf of @dgt41 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10774">issues.joomla.org/joomla-cms/10774</a>
