### ISSUE TITLE
Placeholder not showing if zero(0) value in hint - JFormField*

### ISSUE THREAD

**Issue by Globulopolis** [joomla/joomla-cms#10777]
#### Steps to reproduce the issue
Add a `0` to hint attribute like this
`<field name="year" type="text" default="" label="COM_YEAR" hint="0"/>`

#### Expected result
It should be an input:
`<input name="year" id="year" value="" type="text" placeholder="0"/>`

#### Actual result
`<input name="year" id="year" value="" type="text"/>`

#### System information (as much as possible)
Joomla 3.5.0

#### Additional comments
The problem exists in [JFormFieldCalendar](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/fields/calendar.php#L154), [JFormFieldColor](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/fields/color.php#L293), [JFormFieldEMail](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/fields/email.php#L51), [JFormFieldNumber](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/fields/number.php#L153), [JFormFieldPassword](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/fields/password.php#L155), [JFormFieldTel](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/fields/tel.php#L52), [JFormFieldText](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/fields/text.php#L175), [JFormFieldTextarea](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/fields/textarea.php#L148), [JFormFieldUrl](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/fields/url.php#L51).

**Comment by brianteeman** [comment]
Confirmed <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10777">issues.joomla.org/joomla-cms/10777</a>.</sub>

**Comment by bertmert** [comment]
Please test first PR https://github.com/joomla/joomla-cms/pull/10782
(only for calendar field).

**Comment by Globulopolis** [comment]
@bertmert I can confirm that this PR fix the problem.

**Comment by infograf768** [comment]
@Globulopolis 
please note your test successful here:
https://issues.joomla.org/tracker/joomla-cms/10782

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10777">issues.joomla.org/joomla-cms/10777</a>

**Comment by infograf768** [comment]
Closed as we have a patch https://issues.joomla.org/tracker/joomla-cms/10782<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10777">issues.joomla.org/joomla-cms/10777</a>.</sub>
