### ISSUE TITLE
com_finder inserting &format=json to search result URL

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#10785]
#### Steps to reproduce the issue

Is there any chance or something in a custom component finder plugin that will or might insert a &format=json to the search result URL?

#### System information (as much as possible)

Joomla 3.5.1
Linux Server running Php 7

#### Additional comments

Sorry if I am posting in a wrong place, I don't know where to post to get development help since the joomla forum doesn't help at all.

**Comment by chrisdavenport** [comment]
So you're trying to get the search results list in json format?

**Comment by brianteeman** [comment]
@frogydiak Please respond to the question from @chrisdavenport 

If a reply is not received within a few weeks then this will be closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10785">issues.joomla.org/joomla-cms/10785</a>.</sub>

**Comment by brianteeman** [comment]
Closing due to lack of response - it can always be reopened if updated<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10785">issues.joomla.org/joomla-cms/10785</a>.</sub>
