### ISSUE TITLE
message shown after installing with invalid prefix is ambiguous

### ISSUE THREAD

**Issue by slibbe** [joomla/joomla-cms#10789]
#### Steps to reproduce the issue
Installing new 3.6Beta1 when prefix has format abcd_ followed by the regular _ (so with two trailing underscores). 

#### Expected result
Two possibilities:
1. normal installing continues
2. an unambiguous message appears which is easy to understand for everyone

#### Actual result
A message (see attachment) appears. I would say that the format I used does comply with show message, but it is not apparently.

#### System information (as much as possible)
Occurs with both mysql 5.5.46 & postgresql 9.3.9, php 5.6.14 . All this on a ScotchBox 2.5 built on Ubuntu 15.04![screen shot 2016-06-11 at 09 14 02](https://issues.joomla.org/uploads/1/4220382a01c60b87cc87400690514ac6.jpg)

**Comment by Twincarb** [comment]
Which part is ambiguous the message you receive initially below.
Create a table prefix or use the randomly generated one. <strong>Ideally four or five characters long, it may only contain alphanumeric characters and MUST end in an underscore. Make sure that the prefix chosen is not already used by other tables</strong>.
Or
The table prefix must start with a letter, be followed by optional alphanumeric characters and by an underscore

both say <strong>an underscore</strong> which means one. The only alternative is to use <strong>a single underscore</strong>

The only error I can see is the second string is missing a "." at the end.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10789">issues.joomla.org/joomla-cms/10789</a>.</sub>

**Comment by brianteeman** [comment]
I am closing this. The message is 100% correct<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10789">issues.joomla.org/joomla-cms/10789</a>.</sub>
