### ISSUE TITLE
Joomla Admin Area Redirects me to Front end Homepage

### ISSUE THREAD

**Issue by MainaWycliffe** [joomla/joomla-cms#10799]
I am currently using Joomla 3.5.1 and i have the following issue

#### Steps to reproduce the issue
Transferred the site from one server to another
Changed the TMP and Log paths
I log into the backed end and it was successful
I try to edit an article, module, plugin, template
I get redirected to the front end homepage (the funny thing, global check in shows i have opened successfully.)
#### Expected result
I should be redirected to edit article page, edit module page

#### Actual result
Redirected to the homepage of the site

#### System information (as much as possible)
PHP 5.6 (Native) - Both Servers
Joomla 3.5.1

#### Additional comments
I tried a couple of solutions, such as using Akeeba Backup to transfer the site, Upload the database manually but the problem persists. One thing i did notice was that, every time i dropped all tables and uploaded the same version of the database again, a problem would solve on one part and reappear on another menu. The default Joomla extensions (Articles, Menu, Module, Plugins ) are the ones mainly affected although at one time Form Fabrik was affected and solved that by a simple re installation.

**Comment by brianteeman** [comment]
Please use the forum for support http:/forum.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10799">issues.joomla.org/joomla-cms/10799</a>.</sub>
