### ISSUE TITLE
error resulting in a database that needs to be 'fixed' with upgrade from 3.5.1 to 3.6Beta1

### ISSUE THREAD

**Issue by slibbe** [joomla/joomla-cms#10790]
#### Steps to reproduce the issue
Install a Joomla 3.5.1 with Postgresql, than upgrade this to 3.6beta1.

#### Expected result
Upgrade goes fine and smooth with no errors.

#### Actual result
Error shown (see attachment) which should be 'fixed' with fix button afterwards.

#### System information (as much as possible)
Postgresql 9.3.9, PHP 5.6.14 . Doing this testing in ScotchBox 2.5 based on Ubuntu 15.04 .

#### Additional comments
![screen shot 2016-06-11 at 09 21 34](https://issues.joomla.org/uploads/1/d8f487c4f03166a344d0a1b3d6968512.jpg)

**Comment by brianteeman** [comment]
Closed as we have a pull request.#10792 please test
