### ISSUE TITLE
Module Assignment (menu assignment) UL list broken in module manager

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#10808]
#### Steps to reproduce the issue
I was just messing around with menus in staging (2 to 4 days old). Moved some menu items into other menus and so on.

Afterwards I opened a module and wanted to change Module Assignment settings.

It looks weird. I don't know why. Had no time yet to make investigations.

![13-06-_2016_14-47-46](https://cloud.githubusercontent.com/assets/11038612/16008373/fa433b46-3177-11e6-94b4-7d041d137453.jpg)

![13-06-_2016_14-49-58](https://cloud.githubusercontent.com/assets/11038612/16008390/186155ea-3178-11e6-8c0e-84b197a9870b.jpg)

![13-06-_2016_14-51-07](https://cloud.githubusercontent.com/assets/11038612/16008396/1d8fe4f0-3178-11e6-8642-2b9975379fb6.jpg)

![13-06-_2016_14-52-03](https://cloud.githubusercontent.com/assets/11038612/16008403/24369a1a-3178-11e6-82cf-47798526a094.jpg)

**Comment by bertmert** [comment]
Some of the LI are outside of `<ul class="treeselect">`. No UL as parent.

![13-06-_2016_15-10-12](https://cloud.githubusercontent.com/assets/11038612/16008707/80740d02-3179-11e6-9645-a737ba886f86.jpg)

**Comment by brianteeman** [comment]
Can you see if the rebuild menu button fixes it.

**Comment by bertmert** [comment]
> Can you see if the rebuild menu button fixes it.

No, it doesn't. When I remember correctly this issue was reported some time ago in a forum. But ?

**Comment by brianteeman** [comment]
I saw it once before but it turned out to be a corrupt menu

On 13 June 2016 at 14:21, bertmert <notifications@github.com> wrote:

> Can you see if the rebuild menu button fixes it.
>
> No, it doesn't. When I remember correctly this issue was reported some
> time ago in a forum. But ?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10808#issuecomment-225578546>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8U14cYaw0EOdghhT5-SqaFYDbUXqks5qLVlbgaJpZM4I0TtY>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by bertmert** [comment]
OK! I'll make some investigations when I have time. Low priority ;-)

**Comment by bertmert** [comment]
Australien Parks > Image Gallery and below had to high levels after moving.
Instead of 2, 3 they had 3, 4. This gap (1->3) closed UL to early.
After opening Image Gallery and just saving it, it had level 1 and could be moved to level 2 afterwards.
Don't know why.
Closing.

**Comment by jimhill10** [comment]
Tracked it down my my sites.  The issue was with the plugin System - Regular Labs - Modals. I discovered this because the menu display broken right after loading one of the menu items that uses the surrounding {modal} tags.  To get around this just disable that plugin, do your menu assignment, then enable it again.  I will report it to NoNumber.  

Jim

**Comment by jdockum** [comment]
My apologies for the necro-post, but I had the same problem and fixed it the same way @ghost did. 
I didn't fully understand his answer about levels, but made sense of it. I thought I'd add feedback in case someone else ever got stuck with this.

Basically, there are menu items which think they have a parent item but there isn't one. It might happen when moving menu items into another menu. 

If you look at your module, find the first menu name without the collapsible button. In ghost's example, it is the 'FRUIT SHOP' menu. Then look at the menu above it - that's where the problematic item(s) will be. Then just look for menu items that are indented (child items) but have no parent. Open them, save & close, and the module assignment will be back to normal.
