### ISSUE TITLE
Multilingual problem URL

### ISSUE THREAD

**Issue by thebestju** [joomla/joomla-cms#10806]
Hi, 
I am trying to develop a multilingual website in French and English. French is the default language. 
Option "Remove the language code of the URL" is on "Yes".French URL is http://nomdedomaine.com and english URL is http://nomdedomaine.com/en/ but when I'm on English language, the link on the french flag is /fr/ instead of / so It created a content duplication

#### Steps to reproduce the issue
language plugin:
Item Associations: Yes
Add Alternate Meta Tags: Yes
Add x-default Meta Tag: Yes
X-default language: Français (FR)
Remove the language code of the URL: Yes

#### System information 
Joomla! 3.5.1

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.joomla.org
