### ISSUE TITLE
reCaptcha not working for some languages (i.e. danish)

### ISSUE THREAD

**Issue by Robdebert** [joomla/joomla-cms#10809]
#### Steps to reproduce the issue
install the danish language pack
setup recaptcha as version 2.0 in the plugin
open the "password reset" page in the danish language with activated captcha

#### Expected result
recaptcha should show up and let the user "click" on "i am not a robot"

#### Actual result
displays the message: 
![image](https://cloud.githubusercontent.com/assets/1737455/16008483/7bf69dc2-3178-11e6-9902-5f0bc9a5bc7c.png)

#### System information (as much as possible)
Joomla 3.5.1

#### Additional comments
I already created a pull request for this: https://github.com/joomla/joomla-cms/compare/staging...Robdebert:fix_recaptcha_languagekey

**Comment by brianteeman** [comment]
Thanks for this. For future reference you don't need to create an issue and a pull request. When you create a pull request it is automatically created on the issue tracker.
