### ISSUE TITLE
License Manager for 3rd Party Extensions Discussion and Feature Request

### ISSUE THREAD

**Issue by designbengel** [joomla/joomla-cms#10807]
This is a discussion from the enduser perspective. I´m using some extensions, which are not using the native Joomla! updater. I don´t know why but i guess they have their own updater to add "license" options into it? - Correct me if i´m wrong...
That disturbs the usability a lot and so i want to share a solution with you i saw in a shop system.

They have a seperate option called "licence manager" - I can manage there the installed plugins and extensions with their license codes and have also an overview when the license is expiring.

Additionally i see in the update-manager if i have a current license and if the update is flagged as a feature update, bug or security release and if the extension developer marked the update as compatible to the current installed framework version.

Thanks for your thoughts!

**Comment by brianteeman** [comment]
What do you think the chances are of developers who dont use the extension updater using this - OR do you mean this is somewhere that the site owner can record "support" dates for the extensions they use

**Comment by designbengel** [comment]
I think we can argument that it´s a lot more userfriendly, and of course ask the extension developers what  features it needs to have that they would use it instead of an own environment. Extensions like RegularLabs, Plugin-installation from JCE, Jomsocial, Seblod Updater,... sure there are a lot more using their own updater instead of the Core Updater). I don´t mean it for the site owner to record something additionally.

**Comment by brianteeman** [comment]
Unless every extension used it then I don't really see how it can be useful

(Jce plans to switch to use joomla installer for its plugins)

**Comment by zero-24** [comment]
It is allready possible for the extension devs to use the core updater with non free extensions:

https://github.com/joomla/joomla-cms/pull/2508

https://github.com/joomla/joomla-cms/pull/2769

Since 3.2.x i think.

**Comment by brianteeman** [comment]
And they don't :(

**Comment by designbengel** [comment]
Would be great to know the reason and how to make them using the core updater...

**Comment by brianteeman** [comment]
I know why JCE didnt (they were not true joomla plugins) and they are now being converted so they are.

For other extensions they have many varied reasons although a common denominator for some is that they use a company wide library to support their extensions and this is a way to manage that dependency. For others I suspect its nothing more than a commercial oppotunity

**Comment by mbabker** [comment]
Presumably it's a mix of the lack of features in the update system before 3.2 and cross version compatibility (unless you're maintaining duplicate code for different Joomla versions or can do some simple if statements you typically have to limit some features to whatever the lowest version you're supporting has).  Also is probably going to be dependent on how those developers have integrated their "external" update mechanisms into their own workflows and what effort is required to make a change like converting to only using the core system.  For example the Regular Labs manager has the possibility to show all his company extensions (including not installed ones) and install them from the manager versus having to go to his site or use Install from Web to locate and install the extension.

At the end of the day, all core can really do is give folks the tools they need.  I doubt though that you'll give everyone the tools they desire that makes them abandon their own systems in favor of the single Extensions -> Update screen.

**Comment by designbengel** [comment]
Thanks for clearing this up for me. But anyway the License Manager and especially the "flag as compatible" feature are really useful for enduser...

**Comment by brianteeman** [comment]
How would you seem that working in joomla. Everything should be compatible
and we don't have licences

**Comment by designbengel** [comment]
With license i mean the updatecodes / subscription codes from the extensions - to manage them all in one place...

**Comment by brianteeman** [comment]
Which assumes that all commercial extensions work that way - many do not. You would also need a way to manage the different subscription periods

**Comment by mbabker** [comment]
The core update component just needs to be able to plug in whatever data is needed to ping the remote source, find an update, optionally validate a license or whatever extra data is necessary, and make a decision on that.  That mechanism exists.  Whether or not developers use it is entirely up to them.  There's no mandate (nor should there be) that all extension updates must go through the core update system (which it would certainly be nice if they would, but also realize there are situations where this isn't as practical).

As for license data, IMO core should not have a `com_licenses` to keep track of this stuff.  Just like the update system, it's going to rely on the extension developers to write their code in a way that's compatible with whatever interface is provided.  And considering many developers use their own systems, there's no simple way to tell it "check here for field X and show that data".

**Comment by designbengel** [comment]
okay, thank you all for your feedback and explanation!
