### ISSUE TITLE
Search Tools and Batch tool show unauthorized categories

### ISSUE THREAD

**Issue by shteevy** [joomla/joomla-cms#10802]
#### Steps to reproduce the issue

A back-end user who does not have the right to edit or view articles of a category can see this category in the drop-down "Select Category" list from "Search Tools" in the Content Manager, it can also be seen in "Batch".
#### Expected result

Hide unauthorized categories from the Search Tools and Batch. 
#### Actual result

Unauthorized categories are showed
#### Additional comments

When writing a new article, only authorized categories are displayed, this situation should be the same for the search tool and batch

**Comment by brianteeman** [comment]
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10802">issues.joomla.org/joomla-cms/10802</a>.</sub>

**Comment by shteevy** [comment]
Hello, is it planned to fix this ? i'm not a coder but if i can help.
Shteevy.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10802">issues.joomla.org/tracker/joomla-cms/10802</a>.</sub>

**Comment by andrepereiradasilva** [comment]
non coder users can always help testing Pull Requests (PR).
At the moemnt there are more than 300 that needs tests https://github.com/joomla/joomla-cms/pulls

All Pull Requests need at least:
1. A volunteer contributor wiling to submit a PR with code
2. Two tests by other users
3. Be merged into the core by the mantainers

In this case, we don't have `1.` yet

**Comment by franz-wohlkoenig** [comment]
willing to test if PR is submitted.

**Comment by rvbgnu** [comment]
Hi @shteevy I've just tested this issue with the current staging branch (Joomla! 3.7.3-dev). The issue seems resolved. Please could test again if you are still experiencing the issue?

**Comment by franz-wohlkoenig** [comment]
set Status on "Information Required".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10802">issues.joomla.org/tracker/joomla-cms/10802</a>.</sub>

**Comment by shteevy** [comment]
Hello,

I tried with 3.7.3-dev but I still can see unauthorized categories in the Search Tools and in the batch tools.

Steve.

**Comment by rvbgnu** [comment]
That's a weird one. Please could you detailed the **Steps to reproduce the issue** that you are applying to see unauthorized categories?
Then I will test it a third time ;-)

**Comment by shteevy** [comment]
Hello,

Here is the procedure to reproduce the issue with J! 3.7.2

The user is in a group authorized to create, delete, modify, modify status and modify own elements for only one category called "Valves (Pédagogique Mons)".

When the user is connected to backend and using the Search Tool (Content > Article > Search Tool), all the categories are showed into the dropdown menu.

![screen shot 2017-06-13 at 06 09 26](https://issues.joomla.org/uploads/1/ae195ad6a207a70c544b889e58d56b34.png)

The showed categories have the access right "Registered" but the user has not the right to publish into them.
Why are they showed ?

I have the same problem into "Batch Tool"

Many thanks,

Steve



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10802">issues.joomla.org/tracker/joomla-cms/10802</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@rvbgnu could you reproduce Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10802">issues.joomla.org/tracker/joomla-cms/10802</a>.</sub>

**Comment by rvbgnu** [comment]
Sorry for the late reply.

I could reproduce the issue, but I'm not sure if it is one actually!!

Please @shteevy I need more details of your user groups structure and categories permissions: this is a use case that we must checked.

For my test, using the latest joomla-3.7.4-dev with sample data, I created a Group with **Manager** as parent, to grant the specific user access to the backend, he/she automatically inherits permissions for all the categories.
![screen shot 2017-07-09 at 20 57 58](https://issues.joomla.org/uploads/1/88db0b7e168038a62fe7ce6e49714eac.png)

So with more details, we could better reproduce the same issue. You could use **Advanced Permissions Report** in the group view to check like this:
![screen shot 2017-07-09 at 20 58 08](https://issues.joomla.org/uploads/1/4a472ee41d5ecceec49f705526da5b14.png)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10802">issues.joomla.org/tracker/joomla-cms/10802</a>.</sub>

**Comment by shteevy** [comment]
Hello,
Sorry for this late reply too :)

The Group used for this test is a subgroup of "Public"

![image](https://user-images.githubusercontent.com/2981456/28108667-a2d42a40-66ec-11e7-9928-9ae34a6386a9.png)

I remark that the user can see the categories with a "Registered" level access.
This group don't have the right to write, modify or delete in these categories. It should not see these categories into Search Tools and Batch Tools. Am i wrong ?

Screenshot of the global rights of this group : 

![image](https://user-images.githubusercontent.com/2981456/28109070-18c26a86-66ee-11e7-942a-d718c3c27816.png)

Screenshot of the rights (with ACL Manager) of this group :  
![image](https://user-images.githubusercontent.com/2981456/28108996-cc27844a-66ed-11e7-95d9-347cb3f290b1.png)

Screenshot of the access rights of these categories :  
![image](https://user-images.githubusercontent.com/2981456/28108926-83010f0c-66ed-11e7-8127-31609e15b532.png)

Have a nice day,
Steve

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 17th September 2017.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10802">issues.joomla.org/tracker/joomla-cms/10802</a>.</sub>

**Comment by ghost** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened .
