### ISSUE TITLE
Admin area inconsistency in "Edit User" terminology is "Block this User" while in User Manager it is "Enabled"

### ISSUE THREAD

**Issue by beat** [joomla/joomla-cms#10812]
#### Steps to reproduce the issue

Go to Users - Manage : See that column is "Enabled"

Click on a user: See the corresponding setting in "Account Details" tab

#### Expected result

"User Enabled"

#### Actual result

"Block this user" (and the normal setting is a **red** NO, which looks really strange in red.

#### System information (as much as possible)

Any Joomla 3.5.1 installation

#### Additional comments

None.

**Comment by schnuti** [comment]
To my anderstanding it is consistent but a little confusing as in any items list. e.g. articles. A button shows the state but change to the opposite.
Click on green (action) button in the item line and it becomes disabled (blocked, unpublished).
Click on green button in the toolbar and it becomes enabled (enabled, published)      <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10812">issues.joomla.org/joomla-cms/10812</a>.</sub>

**Comment by beat** [comment]
Yes, I know that it is the same, like all Joomla users that went through the learning curve.

But all novice users have to first guess that it is the same, because of terminology inconsistency (due to historic reasons: It was "Blocked" too in User manager long time ago, then someone changed it for consistency with other article and so forth views as well as logic to have green marks when things are ok to "Enabled". But forgot to change it in user edit view. All of that was long time ago.

I see no problem in fixing that in a 3.6.0 or 3.7.0 release. Maybe not in a "patch" release. No need to wait 4.0.0.

**Comment by brianteeman** [comment]
Pull requests are welcome

**Comment by schnuti** [comment]
One small issue is that "Block a user / User is blocked" is probably understood. Not that **obvious** is, that the opposite to enabled is blocked or that disabled is the same as blocked.

I'm not against a change though.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10812">issues.joomla.org/joomla-cms/10812</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have the start of a PR for testing #11421
