### ISSUE TITLE
Versioning is not available on edit.own

### ISSUE THREAD

**Issue by pieter-groeneweg** [joomla/joomla-cms#10813]
#### Steps to reproduce the issue
created a group "authors team" with parent "registered".
administrator interface access allowed:

following permissions for articles:
Configure ACL & Options - Not Allowed.
Configure Options Only - Not Allowed.
Access Administration Interface - Allowed
Create - Allowed
Delete - Not Allowed.
Edit - Not Allowed.
Edit State - Allowed
Edit Own - Allowed

Logging in as a member of "authors team"
Go to articles manager and open an existing article
Create a new article and save
Open the same article. 

#### Expected result
Versions button to be available

#### Actual result
No versions button
though version notes field is available and entries in that field are saved. (visible when logged in as super user.

#### System information (as much as possible)
Joomla 3.5.1 "vanilla".
Apache 2.2.15-47.el6.vm.4
PHP 7.0.2
MySQL 5.5.33-20.el6.art

#### Additional comments
One would expect versioning to be available to the author "edit.own" enabled.
Now it seems it is only available for authors that can edit all content.
Though the version notes field is available to edit.own.

IMHO versioning should be available to edit.own

**Comment by infograf768** [comment]
I will make a patch, but this will not be for 3.6.0 as we are near release.

**Comment by infograf768** [comment]
Please test
https://github.com/joomla/joomla-cms/pull/10836

**Comment by brianteeman** [comment]
Closed as we have a PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10813">issues.joomla.org/joomla-cms/10813</a>.</sub>
