### ISSUE TITLE
Allow to catch user batch process event via plugin

### ISSUE THREAD

**Issue by frthjf** [joomla/joomla-cms#10825]
#### Steps to reproduce the issue

1) Go to the Joomla Backend > Users and run a Batch process for the selected users, e.g. 'Add To Group'.
2) Try to catch upon the event ``onUserBeforeSave`` or ``onUserAfterSaveGroup`` in a Plugin.

#### Expected result

The Plugin function should be triggered.

#### Actual result

No Plugin event is triggered to catch the batch process.

#### System information (as much as possible)

PHP Version 	5.6.22-1+donate.sury.org~trusty+1
Web Server 	Apache/2.4.20 (Ubuntu)
WebServer to PHP Interface 	fpm-fcgi
Joomla! Version 	Joomla! 3.5.1 Stable [ Unicorn ] 05-April-2016 22:45 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 

#### Additional comments

I don't know whether there is an efficient way to implement that for large user sets. However, in my use case I need to sync any changes made to the user groups to another application and currently I can't catch up on batch processes in the backend.

**Comment by laoneo** [comment]
This is valid for all batch actions like Articles or Contacts as the model batch function doesn't trigger any kind of event.

**Comment by dudheit** [comment]
Is this for some reason intended?

**Comment by laoneo** [comment]
I don't think so. I guess it was not implemented as it was not needed till now. The function where the events should be triggered, can be found on that file https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/model/admin.php#L186. The only thing we have to define here, are the parameters and event names. The implementation should be relatively simple.

**Comment by dudheit** [comment]
Ok, I suppose to trigger the existing events ``onUserBeforeSave`` etc., multiple times though.

**Comment by laoneo** [comment]
I would go with batch triggers.

**Comment by dudheit** [comment]
Than the plugin developer has to listen for the batch explicitly. Seems not to be a big deal, if the documentation is clear about that. What API would you propose than? ``onBatchUserBeforeSave`` etc.?

**Comment by laoneo** [comment]
For example the content events do deliver a context which is available in the batch action as well. So I would go with something more generic like `onBatchBeforeSave` and `onBatchAfterSave`.

**Comment by mbabker** [comment]
We should have batch events.  Added the new feature label, this is something anyone who is interested could work on and open a PR for at any point I feel.

**Comment by wilsonge** [comment]
Closing this as we have a PR with https://github.com/joomla/joomla-cms/pull/20213
