### ISSUE TITLE
Tags module doesn't honor multilanguage

### ISSUE THREAD

**Issue by sam-suresh** [joomla/joomla-cms#10830]
#### Steps to reproduce the issue
1. Publish Popular-Tags module in a multilanguage site to display tags in any order

#### Expected result
When a Popular-Tags module is published in a specific language page, tags belong to that language only displayed. 

#### Actual result
Tags from different languages mixed up in a module

#### System information (as much as possible)
Joomla 3.5.1
EN & MS

**Comment by infograf768** [comment]
What are your settings in the Tags component Options=>Language Filter?

**Comment by sam-suresh** [comment]
Thank you. It works. 
I think the best default value for language filter in Tags options is should be "Current" so it will honor the current language. Otherwise it will mix up tags in multilanguage sites.

**Comment by infograf768** [comment]
>I think the best default value for language filter in Tags options is should be "Current" so it will honor the current language. Otherwise it will mix up tags in multilanguage sites. 

Yes indeed.

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10830">issues.joomla.org/joomla-cms/10830</a>

**Comment by infograf768** [comment]
Closing as it is not an issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10830">issues.joomla.org/joomla-cms/10830</a>.</sub>
