### ISSUE TITLE
Problems when new install on php7

### ISSUE THREAD

**Issue by jojo12** [joomla/joomla-cms#10855]
#### Steps to reproduce the issue
on a site with php 7
normal procedure

#### Expected result
should install

#### Actual result
Warning: session_start(): open(/var/lib/php5/sess_8919etsicjbi58kj0vut8fg8v7, O_RDWR) failed: Permission denied (13) in /srv/www/vhosts/mysite.ch/httpdocs/libraries/joomla/session/handler/native.php on line 258

Warning: session_write_close(): open(/var/lib/php5/sess_8919etsicjbi58kj0vut8fg8v7, O_RDWR) failed: Permission denied (13) in /srv/www/vhosts/mysite.ch/httpdocs/libraries/joomla/session/handler/native.php on line 192

Warning: session_write_close(): Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php5) in /srv/www/vhosts/mysite.ch/httpdocs/libraries/joomla/session/handler/native.php on line 192

#### System information (as much as possible)
php7.0.7
Apache Linux Server

**Comment by mbabker** [comment]
This is an issue with your local configuration.  The install app requires read/write access to the path that your PHP configuration defines for the `session.save_path` variable to write session data.  If `session.save_path` doesn't have a value, then the path returned by `sys_get_temp_dir()` is used instead.

**Comment by jojo12** [comment]
only to say, when I change on the same place to php 5.6. it installs without any problems!

**Comment by mbabker** [comment]
Check for differences between the PHP 5.6 and 7.0 configurations.  It is not an issue of PHP version incompatibility.

**Comment by alexz18** [comment]
Same error:
-------------
PHP Warning:  session_start(): Failed to read session data: user (path: /tmp) in /var/www/html/libraries/joomla/session/session.php on line 654

**Comment by zero-24** [comment]
@alexz18 This is a very old issue. Please do not comment on such old issues.

Please check the PHP configuration as told by mbabker If there is still a issue please get in contact with your hoster or ask in the forums at https://forum.joomla.org thanks!

**Comment by wkoomson** [comment]
I am having the same issue with PHP 7, tried different directories for session.save_path, made sure the permissions were correct (directory owned by http user). Installing and enabling PHP 5.6 fixed the problem

**Comment by mbabker** [comment]
This is not an issue in the core Joomla install unfortunately; Joomla core runs correctly on all stable PHP releases.  The fact that it works on PHP 5.6 and not on PHP 7 is indicative of a server misconfiguration.

**Comment by wkoomson** [comment]
Just wanted to comment that I eventually fixed my problem by enabling mysqli.so in my php.ini for PHP7

**Comment by infograf768** [comment]
> Just wanted to comment that I eventually fixed my problem by enabling mysqli.so in my php.ini for PHP7

@mbabker 
Does that mean that we should check for the mysqli extension in core?

**Comment by brianteeman** [comment]
mysqli is enabled by default in php7 and mysql is not present at all in php 7 - to me this was just a bad install/configuration of php

**Comment by wkoomson** [comment]
Yeah I guess it's poor configuration on my part since I'm using a MariaDB database, but I will note that a fresh install of PHP 7 on Arch Linux has mysqli.so disabled. https://git.archlinux.org/svntogit/packages.git/tree/trunk/php.ini.patch?h=packages/php

**Comment by poproar** [comment]
I know this topic is closed but it has more discussion than I am finding elsewhere. I changed my tmp folder to 775 and 777 (yikes) and still no go. My php ini has this set to this dir and mysqli.so enabled. Any ideas or should I file a ticket with the host?

**Comment by mbabker** [comment]
Go to your host.  Joomla core has worked correctly with PHP 7 since Joomla 3.5.0 was released.

If you're able to consistently reproduce an issue that might look like a core bug, feel free to open a new item.

**Comment by poproar** [comment]
found it: mysqli.so is not enabled by the host :( 
Thanks  @mbabker

**Comment by NesCafe62** [comment]
For me solution was remove `:` symbol in configuration.php in `$host` variable
