### ISSUE TITLE
Updates sites not added on install if joomla "Extension" plugin is disabled

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#10857]
#### Steps to reproduce the issue

1. Go to Extensions -> Plugins
2. Disable "Extension - Joomla" extension plugin
3. Go to Extensions -> Manage -> Install and install one plugin with updates sites
4. Go to Extensions -> Manage -> Update Sites
5. Confirm the update site is not there

#### Expected result

Update site always added on install.

#### Actual result

Update site not added.

#### System information (as much as possible)

Joomla 3.6.0 beta 2 and earlier versions.

#### Additional comments

The Update sites "Rebuild" process uses the same plugin to add the update sites so it suffers from the same problem.

**Comment by mbabker** [comment]
It's how the system was designed.  The entire update site system is in that plugin when it should probably be built right into `JInstaller` and given a proper API.

**Comment by andrepereiradasilva** [comment]
i don't really understand why give user the ability to disable this ... at least the extension is locked.

**Comment by mbabker** [comment]
If you invent a time travel machine, head back to 2010 and get an answer on that one please.  I'm somewhat interested too.

**Comment by andrepereiradasilva** [comment]
let me first invent the time machine and then i'll check. :sunglasses:

**Comment by andrepereiradasilva** [comment]
the updates sites part is solved in https://github.com/joomla/joomla-cms/pull/10828

**Comment by brianteeman** [comment]
@andrepereiradasilva so what is yet to be resolved?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10857">issues.joomla.org/joomla-cms/10857</a>.</sub>

**Comment by andrepereiradasilva** [comment]
1. Go to Extensions -> Plugins
2. Disable "Extension - Joomla" extension plugin
3. Go to Extensions -> Manage -> Install and install one plugin with updates sites
4. Go to Extensions -> Manage -> Update Sites
5. Confirm the update site is not there

What is solved by https://github.com/joomla/joomla-cms/pull/10828 is the same issue when "Rebuild" update sites.

**Comment by brianteeman** [comment]
I am going to close this as without a complete rewrite of extensions installer this can not be resolved and I dont see anyone doing that any time soon and even if they were masochist enough there is better stuff to pull your hair out with<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10857">issues.joomla.org/joomla-cms/10857</a>.</sub>
