### ISSUE TITLE
Hide intro not working when article is added to menu

### ISSUE THREAD

**Issue by Treinramp** [joomla/joomla-cms#10852]
Hi - when I write an article and I want to hide the intro, this works fine. But as soon as I add this article to a menu, the intro is not hidden anymore.

#### Steps to reproduce the issue
See above. Easy to reproduce

#### System information (as much as possible)
I am using Joomla 3.5.1. 
php version 7.0
My website is www.martinrep.nl 

#### Additional comments
Pls let me know if you needmore info.

**Comment by bertmert** [comment]
Because menu settings overrule article settings here. You could use option *Use Article Settings* for *Show Intro Text* if you want to set *Hide* explicitly in article or set *Hide* in menu item directly.

**Comment by Treinramp** [comment]
That's exactly what I do: manually 'Hide intro' in article settings. (Default in article settings is Show intro.) But, as soon as I link the article to a menu, the 'hide intro' setting does not work anymore,
I do not know how to change menu settings. Still, I think the article setting ought to override this.

**Comment by bertmert** [comment]
> I do not know how to change menu settings

Please ask in a forum. These are Joomla basics.

**Comment by Treinramp** [comment]
Forgive my being persistent. I am not looking for a way how to change any settings; I am reporting a bug. And a bug this is; it has been discussed in more Joomla Forums, i.e. forum.joomla.org. Please check out yourself.

**Comment by bertmert** [comment]
It's the expected bahavior:

> menu settings overrule article settings here

Otherwise options for articles in menu items of type *Single Article* or *Category Blog* would be complete nonsense/senseless/needless.

Provide detailed testing instructions if you think it's a bug. What menu type, which settings and so on.

**Comment by Treinramp** [comment]
You were right, bertmert: no bug. thanks for helping me out.
