### ISSUE TITLE
Support "Icon" field for menu items

### ISSUE THREAD

**Issue by sanek4life** [joomla/joomla-cms#10866]
In 2016 many sites use "Icons" for menu items.

Just add "field" for "Icon". 

i mean, just add one field in database for set path to icon (for menu item).

everybody can use Font Awesome icons - https://github.com/FortAwesome/Font-Awesome

![icon path](https://cloud.githubusercontent.com/assets/3662519/16176222/7100038e-3611-11e6-958c-681cc08c1e39.png)

**Comment by brianteeman** [comment]
How is this any different to the field directly above it labeled link image and link style<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10866">issues.joomla.org/joomla-cms/10866</a>.</sub>

**Comment by sanek4life** [comment]
i mean this:

![icona](https://cloud.githubusercontent.com/assets/3662519/16177955/1f7136e0-3644-11e6-95bc-0a2ecf45050c.png)

**Comment by brianteeman** [comment]
As I said you can already do that either with link class or link image
using the fields above. That is what they are for.

**Comment by brianteeman** [comment]
In the link CSS field

**Comment by brianteeman** [comment]
Use Google you will find lots of tutorials how to do this

**Comment by sanek4life** [comment]
user-friendly cms? needs to be improved.

**Comment by ggppdk** [comment]
@brianteeman 

you are right ... almost, you see if the icon is added the way that you suggest:
```
<a class="icon-download"> ... link text ... </a>
```

Then it has the problem that icon-*  is limited to the width of a letter e.g. 14px
**Font-based icons (usually) need a separate HTML Tag** :

```
<!-- icon outside the link -->
<span class="icon-download"></span>  <a> ... link text ... </a>

<!-- or if you want the icon to be inside the link: -->
<a>  <span class="icon-download"></span>  ... link text ... </a>
```

----

Effectively this will be an option to use instead of the parameter "Link image"
(although someone could use both ...)

@sanek4life , besides the built-in menu modules that would be easy to update,  all 3rd party developers, would need to update their menu modules, which would lead to new users wondering why their menu module do not use the icon

It is possible to do via just CSS , because of menu item having class  "item-NNN", still i think this is nice to add, and more user-friendly

**Comment by brianteeman** [comment]
Sorry but that is simply not true at all

**Comment by ggppdk** [comment]
ok, but everything that i said is false or some of it ?

do you mean that this is not really needed ?

**Comment by mbabker** [comment]
This introduces more issues than it solves.

As proposed, it vendor locks to a specific icon provider, making that the third icon font family Joomla core would implicitly support (FontAwesome, Glyphicon, and IcoMoon).  It's a glorified field to add a wrapping `i|span` tag to the beginning of a menu item's label.

Next it only supports font icons and only those which work with whatever arbitrary HTML element is selected.  It doesn't support images.

Last, you can accomplish this already with custom CSS elements or if you really know what you're doing a mix of layout overrides and plugins to add the form field yourself.  Yes, it's a little bit more work, but it is the most flexible option.

**Comment by ggppdk** [comment]
1 .  "vendor lock" to specific icon provider ?
i don't understand why we should blame such a feature to cause "vendor locking"
- the user will just add an icon-class name of a font that is shipped e.g. with the web-site template
- the icon class name **will be a text input**

2 . about supporting images, there is no issue,  because there is already a parameter for using images, we don't need to touch this parameter, neither the PHP code that uses it

3 . Accomplishing this via CSS is not for end-users, a end-user will have to call the site maker to change the icon

4 . And if we indeed make this "vendor-locked" and instead of text-input we use a ... **select drop down**, to select icons of (FontAwesome, Glyphicon, and IcoMoon) (warning that the web-sites must have these installed) then i am sure many users will like it !

but i do not suggest we do the "4"

**Comment by mbabker** [comment]
1) The OP wants FontAwesome, look at the screen shot and follow on comments.  I'd say that's a pretty heavy vendor lock to a resource that's not even included in Joomla right now when people are already groaning that Joomla shouldn't be vendor locked to anything when it comes to UI.

2) Sorry, I don't see any reason to add another field to an already option bloated platform for this.  This is usually where I'm told to stop thinking like a developer, but frankly it's annoying trying to traverse the parameters tree for every possible scenario and trying to figure out where to draw the line on parameters.  And this is opening a pandora's box.  Do we only support a font icon before the text, after the text, make it user configurable, give an option that allows an icon in both spots (which means two inputs).

If you're gonna maintain a website, you have to have some minimalistic understanding of what HTML and CSS are.  If you're using one of the main CMS', add PHP and at least MySQL into the mix.  It is impractical to create a platform that makes a user completely ignorant to the absolute basics of web pages and trying to do so is how you create a user base where they just throw random sites on the internet and don't understand the effort it takes to maintain it.

**Comment by ggppdk** [comment]
@mbabker 

About FontAwesome i agree with you,
that is why i said this to be a **text input** so that it is not a vendor-locked thing

consider this, if we don't call it "Icon class"
- but call it "**Prepend empty < span > with CSS class**"  (please forgive me, for the stupid parameter name, i am not typing this name in order to annoy you),

will it still be a "vendor locking" thing ?

**Comment by mbabker** [comment]
Depends.  Do the different font vendors support a `<span>` tag?  I can't say I pay much attention to HTML semantics but every project I do with font icons seems to use the `<i>` tag.

And it's still opening a pandora's box.  You add a parameter to add font icons.  Why can't I then change that into some other kind of label (maybe I want a "new" label in front of the menu item and that prefaced span tag that supports icons would be perfect for it, I'll just add a parameter to put text inside it now).

I see a bigger picture, I see this creating more issues and more feature requests down the road and bloating up the menu modules and parameters.  I don't believe that the admin components need to support every practical configuration out of the box, they need to present generalized use cases with enough flexibility to do more specialized stuff.  I believe the support of font icon prefaced (or suffixed) images is a more specialized use case that should be done with an extension.

**Comment by ggppdk** [comment]
@mbabker 
All your arguments are valid, 

yes indeed i see why this is problematic, one would ask 
... why add a parameter for span with class ... and not add a parameter  ... "Prepend HTML to menu item title"

Last thing i can say, it is "neat" to have this at the menu item, easier to locate it / edit it

The argument that there are menu extensions that do this
- i guess this makes the need to add this to the core less important

**Comment by sanek4life** [comment]
i know, Joomla have field for "image" with weblink

i just want field, where i can write "fa fa-facebook" word for show Facebook icon with menu item.

**Comment by sanek4life** [comment]
This feature has been in the Gantry 4. but in Gantry 5 of its already removed.

![iconxs](https://cloud.githubusercontent.com/assets/3662519/16179750/fb883484-3677-11e6-865b-64e373aea258.png)

**Comment by brianteeman** [comment]
And I keep saying you can do that using the existing field and have been
able to do that for at least 5 years

(you will of course need to support it in your template)

A quick google will prove that eg

http://www.template-joomspirit.com/template-joomla/template-101/index.php?option=com_content&view=article&id=59&Itemid=221


On 19 June 2016 at 21:41, s <notifications@github.com> wrote:

> i know, Joomla have field for "image" with weblink
>
> i just want field, where i can write "fa fa-facebook" word for show
> Facebook icon with menu item.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10866#issuecomment-227019139>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8T5xoy9ye_Ky3kJD0UDoWnKyMO72ks5qNallgaJpZM4I5Hu2>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by sanek4life** [comment]
You can add a new section to JED - fonts that I can connect to the Joomla.

I choose it for example "Google fonts" or "Font Awesome" or other.

**Comment by brianteeman** [comment]
Please look before suggesting things. Just search the jed for fontawesome.
Multiple options exist.

**Comment by brianteeman** [comment]
This is now closed as it has been asked and answered multiple times.

**Comment by 4digitalworld** [comment]
A lot has changed over the past 4 years and now @Joomla officially uses [FontAwesome](https://github.com/FortAwesome/Font-Awesome) in **Cassiopeia** template.

**I think this discussion should be open again and that makes sense.**

**Comment by 4digitalworld** [comment]
![изображение](https://user-images.githubusercontent.com/3662519/74609998-4eac8380-5100-11ea-83cf-344f6f7693d8.png)

Now that definitely makes sense. I was right 4 years ago.

**Comment by 4digitalworld** [comment]
[Font Awesome](https://github.com/FortAwesome/Font-Awesome) icons for:

- Weblinks
- Menu Items
- Categories
- Tags
- Contacts
- Fields

@infograf768 @richard67 What do you think about this?

![изображение](https://user-images.githubusercontent.com/3662519/74610190-e8c0fb80-5101-11ea-9583-2dec26aad6c5.png)

These icons are already used in Joomla. Maybe expand their application at least for `menu items`? This will really help in navigating the website.
