### ISSUE TITLE
Back-end links to a SCAM website

### ISSUE THREAD

**Issue by demis-palma** [joomla/joomla-cms#10868]
#### Steps to reproduce the issue
Back-end > Extensions > Templates.
In the left column, the items "Styles" and "Templates" are present. Click on "Templates"
Search for "Hathor" template, which is bundled with Joomla.
The column "Author" (on the right side) contains a link to tarrconsulting.com, which redirects to qiwi.help, which in turns is a SCAM website.

#### Expected result
The Joomla CMS not to link to SCAM websites. 

#### Actual result
The Joomla CMS links to a SCAM website.

**Comment by brianteeman** [comment]
Looks like Andi Tarr is no longer in control of that domain. I can prepare
a PR to remove that link.

**Comment by brianteeman** [comment]
See #10869<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10868">issues.joomla.org/joomla-cms/10868</a>.</sub>
