### ISSUE TITLE
Archive View problem

### ISSUE THREAD

**Issue by VasyaV01** [joomla/joomla-cms#10864]
#### Steps to reproduce the issue

 SEO  > Search Engine Friendly URLs > YES
#### Expected result

View Archive article
#### Actual result

error 404 with patch Update router.php #10613
or empty without patch
#### System information (as much as possible)

2 system
1: 
Ubuntu 14.04  Joomla! 3.5.1 Stable MySQl 5.6.30-0 
PHP 5.6.22-1 Apache/2.4.20
2:
Localhost
Ubuntu 16.04  Joomla! 3.5.1 Stable MySQl 5.7.12  
PHP 7.0.4-7  Apache/2.4.18
#### Additional comments

router.php from joomla 3.3 works fine.

**Comment by sovainfo** [comment]
Try 3.6.0 Beta 2

**Comment by VasyaV01** [comment]
OK!
It's better with Beta 2. :) 
View archive articles OK.
But other problem coming up.
SEO off
Search can find archive articles, link to article open the list of the articles . Show in Archive Filter - Day, Month and Year. Looks like missing the archive article ID.
SEO on 
Search can find archive articles,  the link to the article -  error 404
With Joomla ver 3.3 (router.php) 
SEO On or Off - Search can find archive articles, link to article open the list of the articles   Show in Archive Filter - Day, Month. Looks like missing the archive article ID and Year.

**Comment by arraylabs** [comment]
I am seeing this issue on 3.6.5. SEO off the archive module links work, SEO on just get 404, or a page that may have an ID the same as the month selected, ie. archive/2016/8 would show article with ID 8.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10864">issues.joomla.org/tracker/joomla-cms/10864</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Tested on 3.7-staging and enabled modern Routing: got no 404 or any Error on archived Articles.

**Comment by Hackwar** [comment]
I also can't replicate this in 3.7/current staging. Can we close this then?

**Comment by franz-wohlkoenig** [comment]
@VasyaV01 can you please confirm if Issue is also in latest staging?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10864">issues.joomla.org/tracker/joomla-cms/10864</a>.</sub>

**Comment by VasyaV01** [comment]
Sorry i can't, I transfer all archived articles to normal articles. Problem gone...

**Comment by franz-wohlkoenig** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10864">issues.joomla.org/tracker/joomla-cms/10864</a>.</sub>
