### ISSUE TITLE
Fatal error: require_once(): Failed opening required 'Cache/Lite.php'

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#10862]
This issue was reported in a German forum for a webpage (Joomla3.5.1) at hoster 1&1. I'm not sure if it's an issue at 1&1 that (maybe) doesn't provide Cache/Lite.php anymore or Joomla where Cache/Lite.php doesn't exist.

```
Fatal error: require_once(): Failed opening required 'Cache/Lite.php' (include_path='.:/usr/lib/php5.6') in .../libraries/joomla/cache/storage/cachelite.php on line 79
```

Mentioned line is
```
require_once 'Cache/Lite.php';
```
in protected `function initCache($cloptions)`

**Comment by mbabker** [comment]
Joomla doesn't ship Cache_Lite.  It's a PEAR package one can install optionally on a server.  If a provider supports it, that require statement will import it.  But it should actually only get to that statement if you have set Cache_Lite as your cache provider previously (the isSupported check would prevent it from showing as an available option, so either it was set when available or the configuration.php file manually edited).

3.6 adds code that'll more gracefully fail when a selected cache provider isn't available.  That's really the best solution there is at the moment.  In the meantime, the affected user will need to manually edit configuration.php and set `$cache_handler` to 'file'.

**Comment by bertmert** [comment]
Thanks a lot!
