### ISSUE TITLE
Recaptcha is displaying both old image and new "I am not a robot" at the same time.

### ISSUE THREAD

**Issue by DiGwork** [joomla/joomla-cms#10885]
Recaptcha is displaying both old image and new "I am not a robot" at the same time.

Joomla version: Joomla! 3.5.1	

![screen shot 2016-06-20 at 18 23 01](https://issues.joomla.org/uploads/1/8cd3db15419df7553bbe39de3df914b9.jpg)

**Comment by brianteeman** [comment]
Browser version?
Recaptcha version?

**Comment by DiGwork** [comment]
Windows Chrome Version 50.0.2661.102 m

Recaptcha version 2.0

**Comment by DiGwork** [comment]
Oh and submissions fail

**Comment by brianteeman** [comment]
Just a guess but do you have any other captcha plugins installed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10885">issues.joomla.org/joomla-cms/10885</a>.</sub>

**Comment by brianteeman** [comment]
Reset priority according to standards https://docs.joomla.org/Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10885">issues.joomla.org/joomla-cms/10885</a>.</sub>

**Comment by piotr-cz** [comment]
Are you using a non-core captcha extension?

If so, can you confirm that there is similar problem when using other captcha plugin?
For example [this one](http://extensions.joomla.org/extensions/extension/access-a-security/site-security/n3t-seznam-captcha).

At first sight it looks like that extension you've used is not using dedicated Joomla API and just injects it's element under the form (plugin is not type `captcha` but `content`).

If the extension you used is _OSOLCaptcha_, you should contact it's developer and refer this issue.

**Comment by PhilETaylor** [comment]
The second captcha shown is not a core Joomla feature - thus must be another extension, and thus this is not a Joomla problem.

I strike to close this issue as "not a Joomla issue" ?

**Comment by brianteeman** [comment]
Closed due to lack of reply and evidence from screenshot pointing to it being an issue with an extension and not Joomla core.
