### ISSUE TITLE
Extending Article "Configure Edit Screen" options

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#10896]
This issue is referencing to https://github.com/joomla-projects/custom-fields/issues/148#issuecomment-227398006

The upcoming custom-field feature makes it possible to setup specific fields for creating article content.
In some cases it will be not needed or even wanted to have the general WYSIWIG Editor Field. 

Additionaly it would be appreciated to setup the editing per category and there is already a tab called
"Configure Edit Screen" in the Article Details and
"Editing Layout" in the Global configuration.

#### Suggestion:
1) unify the options and the naming  "Configure Edit Screen"
2) to add the options/tab also to the category so all articles inside a specific category apply to these settings
3) Options to add:
Hide WYSIWYG on Frontend / Backend / Both
Show Publishing Params on Frontend / Backend / Both
Show Language Params on Frontend / Backend / Both
Show Metadata Params on Frontend / Backend / Both

Changing seperated Options Frontend Images and Links and Backend Images and Links to
Show Images and Links on Frontend / Backend / Both

+ Show Custom-Fields in First Tab

IMO Image Float and Target has nothing to do with Editing Layout?

thx!!!

**Comment by brianteeman** [comment]
@designbengel it would really help if you created some mock up images<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10896">issues.joomla.org/joomla-cms/10896</a>.</sub>

**Comment by designbengel** [comment]
I will!

**Comment by bertmert** [comment]
BTW: I would prefer to not see options like this when I deactivate this custom fields feature. There are already dozens of settings everywhere in Joomla for this or that exotic case. Complete overkill for users.
Settings like this should be done in one of the custom fields extensions and/or added by plugins or so, in cases when they are needed.

It's a 1-liner in a template override to hide the editor in a form if needed.

**Comment by piotr-cz** [comment]
I'm working on a plugin that adds extra form field in the backend using `onContentPrepareForm` event to articles as described for example [here](https://docs.joomla.org/Adding_custom_fields_to_core_components_using_a_plugin/en).

At the moment only way to add new tab is to add new _fieldset_ to attribs/ params _fields_, and have the option _Show Article Options_ set to _Yes_. Unfortunately this shows whole _Options_ tab.

Template override is not a solution, because I'd have add view override in administration template which is out of scope for an extension (there are few admin templates out there).

**Comment by piotr-cz** [comment]
What I'm saying is I'd like to be able to add new tab, no matter what is set in _Show Article Options_. I could then add new field in _Configure Edit Screen_ so admin can decide if to show it or not.

**Comment by franz-wohlkoenig** [comment]
@designbengel Mockup coming?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10896">issues.joomla.org/tracker/joomla-cms/10896</a>.</sub>

**Comment by coolcat-creations** [comment]
@franz-wohlkoenig i can. Just not available for the next 2 weeks...

**Comment by brianteeman** [comment]
@coolcat-creations reminder

**Comment by franz-wohlkoenig** [comment]
If this Issue get no Response, it will be closed at 22th June 2017.

**Comment by franz-wohlkoenig** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10896">issues.joomla.org/tracker/joomla-cms/10896</a>.</sub>
