### ISSUE TITLE
Content Powerful Features

### ISSUE THREAD

**Issue by dirka35** [joomla/joomla-cms#10899]
article product specifications
content fields

article inside photos

article placements

the comments section design

article listing

seo /joomla/product.html *categories*

Powerful Features
Custom Types

Create your own custom content types to create all the items you need like articles, movies or different product types.

Content Template Manager

dont'pluging module. Comment System

Built-in nested comments with spam protection and support for Gravatar, Twitter and Facebook.

**Comment by dirka35** [comment]
Powerful Features
Custom Types

Create your own custom content types to create all the items you need like articles, movies or different product types.

Content Template Manager

dont'pluging module. Comment System

Built-in nested comments with spam protection and support for Gravatar, Twitter and Facebook.

**Comment by roland-d** [comment]
@dirka35 Please use our mailing list to discuss ideas at https://groups.google.com/forum/#!forum/joomla-dev-cms

Thank you.
