### ISSUE TITLE
Image not uploading in JA ACM 

### ISSUE THREAD

**Issue by nareshvida** [joomla/joomla-cms#10893]
Hi,
I am facing problem in uploading image in JA ACM(JoomlArt Advanced Custom module). It was working fine in Joomla 3.4 version but issue face in Joomla 3.5.1. I am using JA Platon template. Template developer are referring me to Joomla issue. What should I do? Kindly let me know.

Regards

**Comment by brianteeman** [comment]
Sorry but this issue tracker is for issues in the core of Joomla only. We
can't possibly support or debug issues in external software.

**Comment by nareshvida** [comment]
I am getting issue in default Joomla custom html modules on Joomla admin panel

**Comment by Joomstack** [comment]
Naresh If you are facing same issue with default Joomla modules and articles ,you should check the /media/js/js folder in your Joomla site folder .
Proboaly the files are missing or not updated in your Joomla update . Replace the folder with Fresh Joomla package /media/js/js folder .
This would solve the issue .
Do not forget to take backup of site .
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10893">issues.joomla.org/joomla-cms/10893</a>.</sub>

**Comment by nareshvida** [comment]
Hi JoomStack,

Problem has already been fixed. I did the same process to solve the issue. Download the fresh Joomla setup and install on local than check js file in /media/js/js folder, there was some missing JS files that uploaded to server all the file and finally got the problem solve. 

Thank you very much for the right solution!!!

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10893">issues.joomla.org/joomla-cms/10893</a>.</sub>
