### ISSUE TITLE
Notice when login on edit url

### ISSUE THREAD

**Issue by cdekok** [joomla/joomla-cms#10892]
When I am editing a menu item, then are logged out and then log back in on the same url:

http://example.comadministrator/index.php?option=com_menus&layout=edit&id=177

It throws an notice.

```
Notice: Undefined property: MenusViewMenus::$activeFilters in /site/public/layouts/joomla/searchtools/default.php on line 32
```
I guess it should redirect to the menu component? I think on other places there are checks that you cannot acces an edit link directly.

**Comment by andrepereiradasilva** [comment]
there is no activeFilters var on line 32 on current staging (there is one on line 34 but have an isset before)
See https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/searchtools/default.php#L32

Are you using latest staging or 3.6.0 beta 2?

**Comment by cdekok** [comment]
Hi I am using 3.5 seems on master it moved a line:
https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/searchtools/default.php#L34
And is fixed already with an isset 👍 

Will close the issue.
