### ISSUE TITLE
How I can get back to last old version of joomla ?

### ISSUE THREAD

**Issue by nareshvida** [joomla/joomla-cms#10898]
Hi,
I want to get back to old version of joomla without any lost of new posts etc. Is it possible manually. Which folders and files I need to change/replace. Because I have 1 month old backup and many changes and new post has done in between. So I want to get back to Joomla 3.4 from Joomla 3.5.1 manually. Kindly suggest me.

Regards

**Comment by brianteeman** [comment]
There is no supported method to do that as it would be a very bad idea leaving your site open to security vulnerabilities.

This is the issue tracker for bugs and feature development. Please use the forum for support . Http://forum.joomla.org

**Comment by nareshvida** [comment]
I am facing problem with one of module/plugin and plugin developer is saying that the problem is with joomla version that not updated completely. So it is need get back to old version and update again Joomla version. Kindly help me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10898">issues.joomla.org/joomla-cms/10898</a>.</sub>

**Comment by brianteeman** [comment]
Please use the forum for support . Http://forum.joomla.org
