### ISSUE TITLE
Let a menu id control a group of articles in /  thru a category (acting in module position) 

### ISSUE THREAD

**Issue by WilkoRietveld** [joomla/joomla-cms#10909]
###case
If you have a lot of articles and do not want to build a menu item for every single one it is great to use the category item as it will automatically generate an article index with links to the article. Downside is it will not give you control over you template layout as it is a module and has no menu item ID to control. This can become an issue if you have different registrered user-types and or using different templates (all frontend). 
###Result
The solution could be there when you would be able to add an menu ID to a category (so to say thru a category to the articles that are part of that category. As now is done on a one menu item id to one article basis. 

###Expected conflict in current architecture
The suggested structure will conflict when an article from the same category is used individually on a(nother) menu item. To overcome this conflict probably an extra setting / option would be needed to turn the "category to id on / off".

**Comment by brianteeman** [comment]
You do not need to build a menu item for every single one. 


You can already achieve exactly what you want and have been able to do so for a very very long time.You just need a single menu item eg blog category or list category. This menu item can either be in a hidden menu or can have the (new) option set to be hidden in the menu params<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10909">issues.joomla.org/joomla-cms/10909</a>.</sub>

**Comment by brianteeman** [comment]
Closed as already possible as explained above
