### ISSUE TITLE
Contact "Image" column parameter: need to save to see it in a fresh new install

### ISSUE THREAD

**Issue by stellainformatica** [joomla/joomla-cms#10901]
#### Steps to reproduce the issue
Create some contacts and assign an Image to the contacts. Create a menu item type "List Contacts in a Category". In Components > Contacts > Options > List Layouts look the parameter  "Image", it is set to Show.
Look in frontend the menu item you created and will see that the image column is not present.

#### Expected result

In frontend the image column is present.

#### Actual result

In frontend the image column is not present.

#### System information (as much as possible)
Joomla 3.6.0beta2 fresh new install

#### Additional comments
If you save the Options, the image column appears, and some other things like contact search filter and number of items to see.

**Comment by brianteeman** [comment]
Closing as we have a PR for testing #10902 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10901">issues.joomla.org/joomla-cms/10901</a>.</sub>

**Comment by AlexRed** [comment]
Please test this PR that should solve the issue
https://github.com/joomla/joomla-cms/pull/10902<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10901">issues.joomla.org/joomla-cms/10901</a>.</sub>
