### ISSUE TITLE
Push articles (also) to module positions instead of creating cotnent in html custom

### ISSUE THREAD

**Issue by WilkoRietveld** [joomla/joomla-cms#10908]
#### Expected result
Managing content in different backend area's can be confusing. (module or article)
Swapping between the two seems impossible. This could be more easy if it would be possible to (also) feed module positions articles. Probably this is available with some third party extension but seems like a structural/ straight forward, CMS function.

**Comment by brianteeman** [comment]
> This could be more easy if it would be possible to (also) feed module positions articles.

Sorry I have no idea what you mean<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10908">issues.joomla.org/joomla-cms/10908</a>.</sub>

**Comment by izharaazmi** [comment]
I think he means to publish an article at a custom html module. 

In simple terms replace mod_custom with mod_article where we just choose the article to render and rest all remain same as existing mod_custom.

Am I right @WilkoRietveld ?

**Comment by brianteeman** [comment]
Or just use a custom module and insert an article into it with the provided
button

On 29 June 2016 at 16:18, Izhar Aazmi <notifications@github.com> wrote:

> I think he means to publish an article at a custom html module.
>
> In simple terms replace mod_custom with mod_article where we just choose
> the article to render and rest all remain same as existing mod_custom.
>
> Am I right @WilkoRietveld <https://github.com/WilkoRietveld> ?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10908#issuecomment-229389645>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8elJ5cER_I5NCXbDgM4phiktGyFZks5qQozCgaJpZM4I8NDq>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
It has been a month without reply so I am closing this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10908">issues.joomla.org/joomla-cms/10908</a>.</sub>
