### ISSUE TITLE
locked out in Joomla 3.5

### ISSUE THREAD

**Issue by popindavibe** [joomla/joomla-cms#10904]
#### Steps to reproduce the issue
Unfortunately I don't know what went wrong. I was working on LDAP authentication, and then after logout I couldn't ever again log in.

I tried all the tricks, but Joomla is not moving an inch. It loops quietly to the login form no matter what I do.
I checked the database as well, joomla user is enabled, as is joomla auth :

+--------------+---------------------------+--------+---------+----------+
| extension_id | name                      | type   | enabled | ordering |
+--------------+---------------------------+--------+---------+----------+
|          400 | plg_authentication_gmail  | plugin |       0 |        0 |
|          401 | plg_authentication_joomla | plugin |       1 |        1 |

+--------------+-------------------------+-----------+---------+
| extension_id | name                    | type      | enabled |
+--------------+-------------------------+-----------+---------+
|           25 | com_users               | component |       1 |
|          216 | mod_users_latest        | module    |       1 |
|          431 | plg_user_contactcreator | plugin    |       0 |
|          432 | plg_user_joomla         | plugin    |       1 |

I tried to update to 3.5.1, still no change at all. Debug mode not changing anything. Nothing in /logs but an index.html pretty much empty.

I believe the app should tell us something at some point, but it stays mute. Website is working, but backend is completely out of reach...

#### Expected result
At least an error message!

#### Actual result
loops back to login

#### System information (as much as possible)
Debian Wheezy

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10904">issues.joomla.org/joomla-cms/10904</a>.</sub>
