### ISSUE TITLE
I can not get a single rss feed that contains all categories of my site

### ISSUE THREAD

**Issue by WillerCT** [joomla/joomla-cms#10919]
Good morning, I can not get an rss feed of the homepage. I would like a single feed that collects the last 10 articles published on the homepage, but the generated page is blank. Here is the link http://www.motonotizie.it/moto-notizie.feed?type=rss

How can I solve this problem ? Thank you.

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.joomla.org
