### ISSUE TITLE
Admin Status module

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#10910]
If you look at the module it is ordered
![screen shot 2016-06-23 at 05 18 47](https://issues.joomla.org/uploads/1/aa3fa33fb5e4b5a4920a849326dfe0d6.png)

**Icon** - View Site
**Count** - Visitors
**Count** - Administrators
Icon - **Count**
**Icon** - Logout

I think it would be more consistent if it was displayed
**Icon** - View Site
**Count** - Visitors
**Count** - Administrators
**Count** - Icon - Messages
**Icon** - Logout

**Comment by C-Lodder** [comment]
Would this be better?

![screeny](https://cloud.githubusercontent.com/assets/2019801/16307840/a4f338cc-395a-11e6-859c-ffc12ff5e411.png)

Removed the icon and added some separators.

**Comment by brianteeman** [comment]
For me yes

For others maybe have icon and messages

Also this admin module has lots of options to hide and display so best to
check that the separators are ok and you dont end up with two

On 23 June 2016 at 15:54, Lodder <notifications@github.com> wrote:

> Would this be better?
>
> [image: screeny]
> <https://cloud.githubusercontent.com/assets/2019801/16307840/a4f338cc-395a-11e6-859c-ffc12ff5e411.png>
>
> Removed the icon and added some separators.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10910#issuecomment-228076164>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8YOBAbRbkh_AEWUidyOsTcwXSQN_ks5qOp5BgaJpZM4I8qVS>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by C-Lodder** [comment]
Tested with the options already, and the dividers are fine

**Comment by brianteeman** [comment]
great

On 23 June 2016 at 16:01, Lodder <notifications@github.com> wrote:

> Tested with the options already, and the dividers are fine
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10910#issuecomment-228078269>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8ZakSUQihMdpNcaqNyOjxYQYc-Txks5qOp-3gaJpZM4I8qVS>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by C-Lodder** [comment]
will submit a PR once I've added the styling via the LESS file

**Comment by brianteeman** [comment]
See #10918<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10910">issues.joomla.org/joomla-cms/10910</a>.</sub>
