### ISSUE TITLE
Would be nice if there was a privacy mode installation option.

### ISSUE THREAD

**Issue by fbc** [joomla/joomla-cms#10929]
It would be nice if there was an installation mode that would disable all email contact and allow people to create an account with-out an email address. The site would give them a generated PDF sheet to download with 10 secret codes that could be used to recover your account. That way, there is no use of email whatsoever. The SSL keeps the communication private, and you do not have any email notifications whatsoever or trace that you belong to that website or what you do there. (Aside from IP meta-data collected by your ISP)

**Comment by PhilETaylor** [comment]
Not going to happen in Joomla core. I would put money on it. I propose this is closed.

**Comment by fbc** [comment]
@PhilETaylor I don't see why not, in our day and age; it's a logical progression. The internet is being used by companies and government to track you, so the people should respond by protecting themselves, their data and their habits.  I don't want to live in a world where someone can peruse my email and know everything about me. These codes can be split-up and placed on different devices under a pseudonym for the site.  The site apache server can be configured to keep no LOGs, and hence NO IP data; and poof! You have a server ready to host Occupy Wall-Street and other such forums, IM(UDDEim) and information sharing without any repercussions. Or being worried of becoming the target of a "random" IRS audit as we've already seen as possible.

**Comment by PhilETaylor** [comment]
Then I suggest you dont use the internet - period. 

Or I suggest you go find a CMS that is not Joomla...

**Comment by fbc** [comment]
@PhilETaylor Wow, I don't know what to say. I'm not requesting it be a mandatory config, just a possible optional one. To tell people to basically "get lost" or "kick rocks" is so unbecoming for an open-source proponent.  Are you currently intoxicated or something?

**Comment by PhilETaylor** [comment]
As I never touch alcohol, I am not intoxicated, nor will I put up with personal abuse from those demanding a project do what they want. 

What you are asking for is not found in any open source CMS out there today, and is not in the roadmap, aims or objectives of the Joomla CMS.

What you are asking for serves no purpose for the general market that Joomla is aimed at. 

Furthermore if you think that just by disabling logs in apache is going to stop your IP address being logged then you are wrong. Just to get to your server you hop over 5-10 other servers that sure as hell will be logging you. 

IMHO if you want this, then you should implement your own custom authentication layer to Joomla - which I think you might easier than you think. I dont believe it has mass appeal or would be a good feature for a mass market, low-barrier-to-entry, CMS like Joomla.

**Comment by brianteeman** [comment]
@fbc I fully understand what you mean but I just dont see how this is going to be useful for a mass market application such as Joomla. Your requirement is very specialised and I am sorry to say that I just dont see anyone spending to the time to create this customisation.

I am closing this issue at this time. It can always be re-opened if there is anyone who has some code to contribute which can be evaluated

**Comment by PhilETaylor** [comment]
Furthermore with a correctly configured Joomla site, you can use a fake email address at a localhost domain name, and bingo you have what you want out of the box with Joomla 3.6.0 today!

**Comment by fbc** [comment]
@PhilETaylor @brianteeman  You guys are right in the sense that it does not server the mass-market. @PhilETaylor Yes, the email at localhost works, however, there is no recovery mechanism. Furthermore, I was not trying to abuse you, I was just caught off guard by that response. I apologize if you took offense to it.
