### ISSUE TITLE
[com_media] media form field gives javascript error

### ISSUE THREAD

**Issue by onlinemindgem** [joomla/joomla-cms#10933]
#### Steps to reproduce the issue

On a clean installation of Joomla 3.6.0 beta 2 with sample data:

1) Go to administrator
2) Component Banners -> Banners
3) Select any of the banners (for example Shop 1)
4) On details tab remove the current value of image
5) Select a new image on the modal window and insert
6) Check you development tool in Edge:

#### Expected result

No javascript error and save banner

#### Actual result

Saves the banner update, but gives a javascript error:

SCRIPT5007: Object expected
index.php (62,206)

[screen shot 2016-06-26 at 09 30 25](https://issues.joomla.org/uploads/1/c27f9df181fb2051e246e125c112ab43.jpg)

#### System information (as much as possible)

Windows Edge browser
Joomla 3.6.0 Beta 2 

#### Additional comments

Also tested in Joomla 3.5.1 with same error

**Comment by RonakParmar** [comment]
I have checked this issue in windows 10 edge browser and able to reproduce this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10933">issues.joomla.org/joomla-cms/10933</a>.</sub>

**Comment by zero-24** [comment]
Moving to confirmed. Maybe a ja expert Can have a Look here?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10933">issues.joomla.org/joomla-cms/10933</a>.</sub>

**Comment by Fedik** [comment]
seems it is only an Edge specific bug, 
in Chrome/Firefox works fine

**Comment by OctavianC** [comment]
In IE, it seems the iframe is destroyed when calling `window.parent.jModalClose();` - it loses all references to its parent when attempting to call `window.parent.jQuery('.modal.in').modal('hide');`. I'll supply a PR soon.

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #11099
