### ISSUE TITLE
Extend attribs db-field in com_content

### ISSUE THREAD

**Issue by AlexFRAN** [joomla/joomla-cms#10939]
#### Steps to reproduce the issue

When following the documentation to create a custom content plugin to add fields to Joomla-articles:
https://docs.joomla.org/Adding_custom_fields_to_core_components_using_a_plugin
There is one pitfall: The attribs-field is a varchar with a length of about 5000.
If you add a couple of editors (maybe you have different page-types with long text (more than 5000 chars) in multiple columns / positions, then the attribs get cut.

#### Expected result

The content should be displayed, regardless if it is longer or shorter than 5000 characters

#### Actual result

Content is not being displayed correctly

#### System information (as much as possible)

Joomla 3.x, Php 5.6, Mysql 5.x
Does not depend on system

#### Additional comments

I solved the issue by manually changing the field type from varchar to text (not quite a clean solution, because it can be reverted on update..).
I recommend changing it by default to text in the next release if possible.

**Comment by laoneo** [comment]
For version 3.7 it is planed to add custom fields to the core. It doesn't depend on the attribs parameter. Would this work for you, or do you have some special requirements where custom fields can't help? If you want to give it a try you can help testing here https://github.com/joomla-projects/custom-fields.

**Comment by AlexFRAN** [comment]
That's great news!
The only thing i would miss (in the current build), are subforms / repeatable fields.
But that is just details, i really like the ability to filter new fields by category / language.
Thanks!

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10939">issues.joomla.org/joomla-cms/10939</a>.</sub>
