### ISSUE TITLE
Media Improvements

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#10946]
The CMS' inbuilt media tools should be expanded for better support of HTML5 media related improvements.  One specific example would be the use of the `srcset` attribute for images.

**Comment by brianteeman** [comment]
srscet is very cool Bruce gave a great presentation about it at JoomlaDay UK but in his own words "is not easy to create a good ui for it"

**Comment by brianteeman** [comment]
For reference https://www.youtube.com/watch?v=9Ac1Ehuu8kI&index=9&list=PLEeLLhsqY3qujiEu3WYlVnJjcPezKiiYi<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10946">issues.joomla.org/joomla-cms/10946</a>.</sub>

**Comment by dgt41** [comment]
Another one is `pattern` in fields for client side validation without javascript (still needed for the messages as some browsers fail silently)

**Comment by piotr-cz** [comment]
I think srcset attribute makes sense only when images would be resized on the fly and different dimensions saved in cache

I've created a content plugin which resizes article intro and main image but you need to specify dimensions and I think these depend on template.

**Comment by brianteeman** [comment]
I am going to close this here as this is being handled in the new media manger project.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10946">issues.joomla.org/tracker/joomla-cms/10946</a>.</sub>
