### ISSUE TITLE
Release blocker: array_column () error

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#10942]
I was using php 5.4.4 when I got this error:
>( ! ) Fatal error: Call to undefined function array_column() in /Applications/MAMP/htdocs/testwindows/trunkgitnew/plugins/system/redirect/redirect.php on line 170

When testing the PR https://github.com/joomla/joomla-cms/pull/10932

@mbabker  suggested I create this issue.

>https://github.com/joomla/joomla-cms/pull/10932#issuecomment-228726271

**Comment by brianteeman** [comment]
Looks like this was added here https://github.com/joomla/joomla-cms/pull/10670<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10942">issues.joomla.org/joomla-cms/10942</a>.</sub>

**Comment by infograf768** [comment]
Looks like we have a solution here:
https://github.com/ramsey/array_column

**Comment by wojsmol** [comment]
@mbabker sugested this package https://github.com/symfony/polyfill-php55

**Comment by rdeutz** [comment]
we shouldn't add a package only because of one use of this function

**Comment by rdeutz** [comment]
I will make a patch

**Comment by mbabker** [comment]
@rdeutz FWIW when the `joomla/registry` package gets updated again the `symfony/polyfill-php55` package will get pulled in as a dependency of it because I changed the JSON format object's `stringToObject()` method to throw an Exception on a `json_decode()` error and use `json_last_error_msg()` to get the message (function added in PHP 5.5).  So the polyfill will inherently be pulled into the CMS at some point.

**Comment by rdeutz** [comment]
@mbabker yeah might be, but pulling a new package in while in beta just to not code 5 lines of PHP code seems not right

PR #10943

**Comment by brianteeman** [comment]
Closed as we have a  PR #10943 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10942">issues.joomla.org/joomla-cms/10942</a>.</sub>

**Comment by bertmert** [comment]
There's already an API function doing the same like array_column:
ArrayHelper::getColumn($redirects, 'old_url')
