### ISSUE TITLE
Article voting in core joomla

### ISSUE THREAD

**Issue by Pradeepw** [joomla/joomla-cms#10954]
I understand Joomla already have voting system where any article can be display with this voting also people can vote for the best article. 

but what happen next?
there is no way we can find out which article received the highest vote also a report/identify list of articles which has any vote. 

There should be a component or mechanism to display this or a module to display with highest votes.

**Comment by piotr-cz** [comment]
True, there is no sorting type _Most voted_/ _Least voted_ in Article order option.

**Comment by brianteeman** [comment]
I would suggest that as the code to vote has been there for ten plus years
and no one has contributed code to do anything with it or created any
extensions then it's not something with much demand.

**Comment by Pradeepw** [comment]
I wonder no one wanted to use core features like this instead of third party components.

If there is no way to find which article has the highest votes and list of vote articles it's pointless to have that feature for nothing. 

Thanks you

**Comment by alikon** [comment]
> module to display with highest/lowest votes.
see #10989

**Comment by brianteeman** [comment]
Closing as we have a pull request for testing. See #10989
