### ISSUE TITLE
After update to Joomla 3.6 RC fails backend files path

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#10955]
#### Steps to reproduce the issue
After updating to the latest package of Joomla 3.6 RC the backend is no more accessible.
Indeed the  path for files is now wrong having a trailing'\' at the beginning.

#### Expected result
  <script src="/media/system/js/core.js"></script>
  <script src="/media/jui/js/jquery.min.js"></script>
  <script src="/media/jui/js/jquery-noconflict.js"></script>
  <script src="/media/jui/js/jquery-migrate.min.js"></script>
  <script src="/media/jui/js/bootstrap.min.js"></script>
  <script src="/media/jui/js/chosen.jquery.min.js"></script>

#### Actual result
	<script src="\/media/system/js/core.js"></script>
	<script src="\/media/jui/js/jquery.min.js"></script>
	<script src="\/media/jui/js/jquery-noconflict.js"></script>
	<script src="\/media/jui/js/jquery-migrate.min.js"></script>
	<script src="\/media/jui/js/bootstrap.min.js"></script>
	<script src="\/media/jui/js/chosen.jquery.min.js"></script>

#### System information (as much as possible)
![joomla36beta2](https://cloud.githubusercontent.com/assets/17835460/16435244/d7544d7c-3d94-11e6-9e57-10f095dbcc57.PNG)
![joomla36rc](https://cloud.githubusercontent.com/assets/17835460/16435245/d75b2f48-3d94-11e6-82df-cbb766b7b9ee.PNG)

**Comment by mbabker** [comment]
You're going to need to include a lot more system info.  I've been
developing new extensions versus the Git HEAD and have not had this issue
at all.

**Comment by joeforjoomla** [comment]
It looks like a fault of JUri, when calling JUri::root()

The static::$root['path']

seems to get now the wrong '\' path

![juri_root](https://cloud.githubusercontent.com/assets/17835460/16435601/90798d1a-3d97-11e6-8027-02cefa7192e2.PNG)

**Comment by mbabker** [comment]
Again, you're going to need to provide a lot more info than "this method
call looks like a wrong return".  JUri has not substantially changed since
3.4.6.

Is this a Windows versus Linux issue?  Is this an Apache versus nginx
issue?  Is this a PHP build issue?  Right now this says nothing that can be
debugged and so far I can't confirm it.

**Comment by joeforjoomla** [comment]
Well i can confirm it. As you can see.

Never faced a similar issue in so many years on the same machine.

It's a Windows, Apache. PHP version 5.4

**Comment by ggppdk** [comment]
I get same problem, when site is **directly under document root**
tested PHP 7.0.3

**Comment by joeforjoomla** [comment]
Finally i found the issue.

The file root/libraries/cms/application/administrator.php at line 48
has been changed in Joomla 3.6 beta 2 from:

`JUri::root(null, str_ireplace('/' . $this->getName(), '', JUri::base(true)));`

to
`JUri::root(null, rtrim(dirname(JUri::base(true)), '/'));`

so introducing the bug.

**Comment by joeforjoomla** [comment]
Please fix it

**Comment by ggppdk** [comment]
Problem seems to be only in windows servers
```
JUri::root(null, rtrim(dirname(JUri::base(true)), '/'));
```

is not "triming"  \
it should be:
```
JUri::root(null, rtrim(dirname(JUri::base(true)), '/\\'));
```

**Comment by wojsmol** [comment]
@joeforjoomla Please test https://github.com/joomla/joomla-cms/issues/10956

**Comment by joeforjoomla** [comment]
I tested the code:
JUri::root(null, rtrim(dirname(JUri::base(true)), '/\\'));

and it works at my end. Now the trimming is done correctly for the '\' character on Windows + Apache

**Comment by brianteeman** [comment]
Closed as we have a PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10955">issues.joomla.org/joomla-cms/10955</a>.</sub>
