### ISSUE TITLE
Clicking TinyMCE  "Insert Field" produces 404 error

### ISSUE THREAD

**Issue by coolman01** [joomla/joomla-cms#10950]
#### Steps to reproduce the issue

Install Joomla! 3.6.0-beta2

Click "New" Article
In the empty editor area, click the editor button "Insert Field"

#### Expected result

Options to insert field

#### Actual result

Error message in popup window with the message : 
An error has occurred.
 404 Component not found.

#### System information (as much as possible)

PHP Built On	Windows NT DESKTOP-A55DI1C 10.0 build 10586 (Windows 10) i586
Database Version	5.5.5-10.1.9-MariaDB
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.4
Web Server	Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.4
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.6.0-beta2 Beta [ Noether ] 16-June-2016 13:54 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by infograf768** [comment]
Insert field? I am not aware of this button.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10950">issues.joomla.org/joomla-cms/10950</a>.</sub>

**Comment by brianteeman** [comment]
There is no core "insert field" I am assuming this is an addon you have installed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10950">issues.joomla.org/joomla-cms/10950</a>.</sub>

**Comment by brianteeman** [comment]
After two weeks without a reply i am closing this. It can always be reopened if required<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10950">issues.joomla.org/joomla-cms/10950</a>.</sub>
