### ISSUE TITLE
[New feature suggestion] Author as hyperlink

### ISSUE THREAD

**Issue by Azot94** [joomla/joomla-cms#10966]
Would have been nice if the name of the author of the article would be linked to his articles. Similarly to the [K2 component](https://demo.getk2.org/item). 

What do you think about this new feature?

**Comment by brianteeman** [comment]
It is not a new feature. It already exists and has done for a very very very long time

In the content options is an options to display the author name and a link to the author (which must be a contact)

In the contact there is an option to link that contact to a user and to display a link to their articles n how many articles to list

Then when you click on the author name in the article you get a list of all their articles etc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10966">issues.joomla.org/joomla-cms/10966</a>.</sub>

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10966">issues.joomla.org/joomla-cms/10966</a>.</sub>

**Comment by Azot94** [comment]
> Then when you click on the author name in the article you get a list of all their articles etc

but...what if I would like to use article blog viev?
