### ISSUE TITLE
Studying the evolution of Joomla!'s project

### ISSUE THREAD

**Issue by gustavopinto** [joomla/joomla-cms#10968]
Hi there, 

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. **Joomla!** was in my list. 

To further analyze the impacts of **Joomla!**'s migration, we analyzed the git log commit history of your project in terms of _number of contributions_, _number of newcomers_, and _number of contributors per month_. The following figure presents a temporal perspective regarding these three measures. 

![joomla](https://cloud.githubusercontent.com/assets/235062/16463548/a1f5ab6c-3e0c-11e6-98b4-9b87ee2d0f63.png)

Given the numbers presented in the graphic, we would like to ask **Joomla!** developers the following questions:

1. What motivated the project to move its source code at Github? How do you evaluate the benefits of this migration?
2. Does this snapshot make sense? Did you find any inconsistency on the data?
3. Do you have any internal policy to promote/attract/retain newcomers? If so, do them succeed?
4. It seems that the number of newcomers and active contributors increased after the migration process. In your opinion, what are the reasons for this fact?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by brianteeman** [comment]
This is the issue tracker for development of Joomla. Please see developer.jpomla.org to contact development team members!

**Comment by zero-24** [comment]
developer.joomla.org ;)
