### ISSUE TITLE
TinyMCE updated to 4.4.0

### ISSUE THREAD

**Issue by Twincarb** [joomla/joomla-cms#10978]
#### Steps to reproduce the issue
Current version of TinyMCE has now reached 4.4.0

#### Expected result
Current Joomla version 4.3.12

#### System information (as much as possible)
4.4.0 changes
ADDED new inlite theme this is a more lightweight inline UI.
ADDED smarter paste logic that auto detects urls in the clipboard and inserts images/links based on that.
ADDED a better image resize algorithm for better image quality in the imagetools plugin.
FIXED bug where it wasn't possible to drag/dropping cE=false elements on FF.
FIXED bug where backspace/delete before/after a cE=false block would produce a new paragraph.
FIXED bug where list style type css property wasn't preserved when indenting lists.
FIXED bug where merging of lists where done even if the list style type was different.
FIXED bug where the image_dataimg_filter function wasn't used when pasting images.
FIXED bug where nested editable within a non editable element would cause scroll on focus in Chrome.
FIXED so invalid targets for inline mode is blocked on initialization. We only support elements that can have children.

4.3.13 changes
ADDED characters with a diacritical mark to charmap plugin. Patch contributed by Dominik Schilling.
ADDED better error handling if the image proxy service would produce errors.
FIXED issue with pasting list items into list items would produce nested list rather than a merged list.
FIXED bug where table selection could get stuck in selection mode for inline editors.
FIXED bug where it was possible to place the caret inside the resize grid elements.
FIXED bug where it wasn't possible to place in elements horizontally adjacent cE=false blocks.
FIXED bug where multiple notifications wouldn't be properly placed on screen.
FIXED bug where multiple editor instance of the same id could be produces in some specific integrations.

#### Additional comments
I would put together a PR, but have no idea how to do a comparison of the changed files.

**Comment by brianteeman** [comment]
It's ok I will do it. I've done the last few. No idea why I didn't get the
email announcing the release.

**Comment by Twincarb** [comment]
Cheers @brianteeman I had noticed you had PR'd the last couple and thought you may have signed up for the email notification. If I can get a break form work, will update my test site to test your PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10978">issues.joomla.org/joomla-cms/10978</a>.</sub>

**Comment by brianteeman** [comment]
I wont be doing it tonight ;)

Its too late for 3.6

On 30 June 2016 at 20:31, Twincarb <notifications@github.com> wrote:

> Cheers @brianteeman <https://github.com/brianteeman> I had noticed you
> had PR'd the last couple and thought you may have signed up for the email
> notification. If I can get a break form work, will update my test site to
> test your PR.
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/10978
> <https://issues.joomla.org/tracker/joomla-cms/10978>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10978#issuecomment-229764335>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8dR2a1p85efvQH3nGNiWUu_vEsbbks5qRBmmgaJpZM4JCcOS>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Closed please see #10979
