### ISSUE TITLE
PHP 7.0.8 - Admin area unusable

### ISSUE THREAD

**Issue by nikola3244** [joomla/joomla-cms#10977]
#### Steps to reproduce the issue
Install latest Joomla on PHP 7.0.8

#### Expected result
Normal admin area

#### Actual result
Admin area full of notices, unusable.
Example of notices:
```
Notice: Only variables should be passed by reference in /home/nikola/public_html/j3/administrator/modules/mod_menu/tmpl/default_enabled.php on line 22

Notice: Only variables should be passed by reference in /home/nikola/public_html/j3/administrator/modules/mod_menu/tmpl/default_enabled.php on line 23

Notice: Only variables should be passed by reference in /home/nikola/public_html/j3/administrator/modules/mod_menu/menu.php on line 94
```

#### System information (as much as possible)
Apache/2.4.20 (Unix) OpenSSL/1.0.2h PHP/7.0.8
I can post whole `phpinfo()` if needed.

**Comment by brianteeman** [comment]
There is no such version as latest. Do you mean 3.5.1 or 3.6rc1

**Comment by nikola3244** [comment]
Sorry, I meant 3.5.1

**Comment by brianteeman** [comment]
Ok. Thought so. This has been resolved for 3.6 due out next week. As it is
just a notice and not an error you can go to global config and reduce the
error reporting level until then.

**Comment by nikola3244** [comment]
Thank you. Just tested on 3.6.0-rc and issue is not there.
Closing.

**Comment by brianteeman** [comment]
Thanks for confirming. You don't k ow how many just don't bother.
