### ISSUE TITLE
Tests Validating HTML Output Are Flaky

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#10984]
For methods that output HTML and the corresponding tests checking these strings, the tests are flaky and somewhat unstable as an arbitrary whitespace change can cause the test to start failing for no valid reason.

Tests validating HTML should be rewritten in a manner which does not perform explicit string comparisons.  This was attempted in some cases with `assertTag()` but PHPUnit deprecated this feature and removed it in 5.0.

**Comment by mbabker** [comment]
See https://travis-ci.org/joomla/joomla-cms/jobs/141875477 as an example.

**Comment by dgt41** [comment]
Any suggestions?

**Comment by dneukirchen** [comment]
In my opinion most of the methods which output html, should use JLayout to support overrides. So in the tests for these methods we should only check if they call JLayout::render with the correct layout file.

Im not a friend of testing html, because it changes to often. But we could create html output tests for the important parts/dom elements of the layouts with DomDocument and assertEqualXMLStructure():
https://phpunit.de/manual/5.4/en/appendixes.assertions.html#appendixes.assertions.assertEqualXMLStructure

**Comment by dgt41** [comment]
@dneukirchen for some reason assertXmlStringEqualsXmlFile() failed here: https://github.com/joomla/joomla-cms/pull/10995
So not sure that assertEqualXMLStructure() will actually work

**Comment by dneukirchen** [comment]
We could redo those tests:

```
public function testGetInput($data, $expectedHtml)
{
    $formField = new JFormFieldUrl;
    foreach ($data as $attr => $value)
    {
        TestReflection::setValue($formField, $attr, $value);
    }
    
    $expected = new DOMDocument;
    $expected->loadXML($expectedHtml);

    $actual = new DomDocument;
    $actual-> loadXML(TestReflection::invoke($formField, 'getInput'));
    
    $this->assertEqualXMLStructure(
        $expected,
        $actual,
        'Line:' . __LINE__ . ' The field did not produce the right html'
    );
}
```

Or in that special case (we only have to check some properties/attributes and values) we could use DomDocument helpers like $this->assertTrue($actual->hasAttribute('disabled').

**Comment by dneukirchen** [comment]
Or if you wann stay with the helper (but its not so readable in my opinion)
```
public function testGetInput($data, $expectedHtml)
{
    $formField = new JFormFieldUrl;
    foreach ($data as $attr => $value)
    {
        TestReflection::setValue($formField, $attr, $value);
    }

    $expected = new DOMDocument;
    $expected->loadXML($expectedHtml);

    $actual = new DOMDocument;
    $actual->loadXML(TestReflection::invoke($formField, 'getInput'));

    $this->assertEqualXMLStructure(
        $expected->firstChild,
        $actual->firstChild,
        true, // check attributes
        'Line:' . __LINE__ . ' The field did not produce the right html'
    );
}
```

**Comment by laoneo** [comment]
In my case [assertXmlStringEqualsXmlString](https://github.com/joomla/joomla-cms/pull/10982/files#diff-f2b77f0bf25f959b0cbca3acdcccf201R450) did the job. But as soon as you add new attributes which are empty it fails. Perhaps an approach can be to add our own assertXMLStringEquals function which can compare strings and tests empty attributes.

**Comment by rdeutz** [comment]
I am not a fan of testing output in unit test, so I would simple drop them or go with David suggestion 

> the tests for these methods we should only check if they call JLayout::render with the correct parameters.

**Comment by yvesh** [comment]
Agree with Robert here, we just keep fixing them again and again, because of intended output changes with really low value.

**Comment by mbabker** [comment]
Tests are gone
