### ISSUE TITLE
Problem with category blog order.....

### ISSUE THREAD

**Issue by vihuarar** [joomla/joomla-cms#10986]
#### Steps to reproduce the issue
See the screenshots to see how is configured the categories...

#### Expected result
See the category blog in order of date creation of each articule

#### Actual result
The category blog appears without an order....(or I dont understand what order is been taked)

#### System information (as much as possible)

As you can see in the image: "asi-nos-ven-en-los-medios.png" the articles appear with not a clear order...
I dont know if the problem is because the articles are stored in subcategories of the category "Así nos ven en los medios"

I also include screenshots about how is configured every subcategory and the main category...

i created a menu item and point it to the category "Asi nos ven en los medios" and subcategories...
![asi-nos-ven-en-los-medios-blog-layout png](https://cloud.githubusercontent.com/assets/1976384/16527215/2ad8a67c-3f7b-11e6-8db8-dcdedf6a5bbf.png)
![asi-nos-ven-en-los-medios-category](https://cloud.githubusercontent.com/assets/1976384/16527217/2ada9dba-3f7b-11e6-9484-35edd0cf7e78.png)
![asi-nos-ven-en-los-medios-details](https://cloud.githubusercontent.com/assets/1976384/16527218/2adb177c-3f7b-11e6-80a1-56ded7697c5d.png)
![asi-nos-ven-en-los-medios-blog-options](https://cloud.githubusercontent.com/assets/1976384/16527205/1f3ed52a-3f7b-11e6-9426-ea97c393f647.png)
![asi-nos-ven-en-los-medios](https://cloud.githubusercontent.com/assets/1976384/16527207/1f40b7a0-3f7b-11e6-9458-40a4bfbb4af7.png)

Subcategories (All subcategories are configured the same...)

![prensa-options](https://cloud.githubusercontent.com/assets/1976384/16527208/1f41c582-3f7b-11e6-9fb0-39a850535e50.png)
![prensa-blog-layout](https://cloud.githubusercontent.com/assets/1976384/16527206/1f3f66ac-3f7b-11e6-9f1f-d013032baf7c.png)
![prensa-category](https://cloud.githubusercontent.com/assets/1976384/16527214/2ad7ae84-3f7b-11e6-8d66-97f9a79324ff.png)
![prensa-details](https://cloud.githubusercontent.com/assets/1976384/16527216/2ad93b00-3f7b-11e6-8e93-8c99b45e64e2.png)

**Comment by brianteeman** [comment]
Yes it is because they are in different categories

Please use the forum for support http://forum.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10986">issues.joomla.org/joomla-cms/10986</a>.</sub>

**Comment by vihuarar** [comment]
But I'm reporting an issue... I think they should appear in order...  
I'm creating a menu item... that shows all the articles under a category (and his categories) all articles under the category and subcategories... should appear in order...

Imaging a category called "news" and subcategories like "sports", "international", "business" etc...
If we are in a category "news" we expect that the news appear in order according to date created (or other criteria) but the should appear in order... (no matter if the article belongs to a subcategory)

**Comment by sovainfo** [comment]
Agree with @brianteeman this issue should be referred to forum.joomla.org.
Issues about the software can be posted here, issues on poor understanding of how Joomla works are for the forum. Considering nowhere in the report it is mentioned how category order is set for content options I can only conclude poor understanding!

There are many posts on the forum explaining category order must be set to: No order.
Only when that is the case you might have a software issue!

**Comment by vihuarar** [comment]
I tried a lot of times to configure the order.. but always appear in a different order... not logical... some of the articles appear in chronological order, but others dont appear in the same order (for example under the second page)

I tried with: "Article order "Most recent first" (And not working)
I tried with "Multi-column order" (I set across and down) but any of those options worked well

You can check it here:
http://portales.inder.gov.co/intranet/asi-nos-ven-en-los-medios?start=6

@sovainfo lets suppose that its a poor understanding about how joomla works... but if it happens.. it is caused maybe by a usability problem that should be improved, it is difficult to configure a menu item (Category blog)

**Comment by sovainfo** [comment]
There are many posts on the forum explaining  **category** order must be set to: No order.

Even more convinced now it is UBF!

**Comment by vihuarar** [comment]
Ok @sovainfo I agree with you... when you set "category order" to "no order" it works..

But I still think that this is a usability problem... is not right that a user should go to the forum to discover that "No order" is "Date order"

So I think that a usability improvement should be to put an option like "Date order" or "created order"

Because a normal users will think "No order" will set the articles with any order... 

if you check the definition of "order": "the disposition of things following one after another, as in space or time; succession or sequence: example: The names were listed in alphabetical order."
if you set "Not order" we should assume that the articles will be listed with not a logical order...

**Comment by brianteeman** [comment]
No order refers specifically to the order of the category - so it is
working perfectly

**Comment by sovainfo** [comment]
Normal users acknowledge their mistake and thank for pointing them to a solution!

Doubt very much there is interest in improving this, but you'll never know. Won't waste more time on it!

**Comment by vihuarar** [comment]
@sovainfo @brianteeman You are right and I'm sorry because I didnt understand immediately that No order.. means ordered by date. I thought there should be an options like "Ordered by creation date" or "order by modification date"... but I think you have more experience in this that me...

I'm very grateful for the solution you gave me.. I just wanted to help and tell you a possible improvement... but I guess I'm the only person that missunderstand that option...

Thank you for your time... I hope next time my help will be more useful...

**Comment by vihuarar** [comment]
@sovainfo @brianteeman You are right and I'm sorry because I didnt understand immediately that No order.. leave the articles ordered by date. I thought there should be an options like "Ordered by creation date" or "order by modification date"... but I think you have more experience in this that me...

I'm very grateful for the solution you gave me.. I just wanted to help and tell you a possible improvement... but I guess I'm the only person that missunderstand that option...

Thank you for your time... I hope next time my help will be more useful...

**Comment by sovainfo** [comment]
Couldn't find anything on docs.joomla.org about it, only outdated J1.5 stuff. As mentioned, you are not the only one. You might want to write an FAQ about it:
After organizing your content in categories, you create menu items for your content. Menu items Featured Articles and Category Blog allow you to present the articles from multiple categories. When you want these articles in a specific order, remember that they are ordered by category first, unless you specify to ignore the category (Category order: No Order).

**Comment by brianteeman** [comment]
Maybe we could make the language string more explicit so instead of the
field category order saying No Order it is something like "Not sorted by
Category" or "Ignore Category"

On 4 July 2016 at 04:42, sovainfo <notifications@github.com> wrote:

> Couldn't find anything on docs.joomla.org about it, only outdated J1.5
> stuff. As mentioned, you are not the only one. You might want to write an
> FAQ about it:
> After organizing your content in categories, you create menu items for
> your content. Menu items Featured Articles and Category Blog allow you to
> present the articles from multiple categories. When you want these articles
> in a specific order, remember that they are ordered by category first,
> unless you specify to ignore the category (Category order: No Order).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10986#issuecomment-230199127>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8ZKFSnpFvZi3LyFe9ZZgNONgGxiZks5qSIExgaJpZM4JDTYh>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by vihuarar** [comment]
I like the @brianteeman suggestion.. but I think that the language string should said something that the users understands that the default order is created date of the article...

I dont think that users will understand "Not sorted by Category" or "Ignore Category"... I think they could be a little more specific...

if you let me give you and advice... I think "created date" or a synonymous would be nice...

thank you for your time...

**Comment by brianteeman** [comment]
That wouldnt be true though

On 4 July 2016 at 14:01, vihuarar <notifications@github.com> wrote:

> I like the @brianteeman <https://github.com/brianteeman> suggestion.. but
> I think that the language string should said something that the users
> understands that the default order is created date of the article...
>
> I dont think that users will understand "Not sorted by Category" or
> "Ignore Category"... I think they could be a little more specific...
>
> if you let me give you and advice... I think "created date" or a
> synonymous would be nice...
>
> thank you for your time...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10986#issuecomment-230285303>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8c8kqxajU2DONN_McPmo1UH1xCAyks5qSQQcgaJpZM4JDTYh>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by vihuarar** [comment]
so.. I think its better than you take a desicion (in case you think that the language string) should be changed... or something should be changed it...

if you think its better leave this way... I think you can close this issue...

I can create a FAQ to help people that has the same problem than me... can you tell me please in which link I can create that?
thanks!

**Comment by brianteeman** [comment]
Closed. The en-gb group are looking at the string<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10986">issues.joomla.org/joomla-cms/10986</a>.</sub>
