### ISSUE TITLE
Punycode update ?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#10981]
Punycode has a new version 2.0 (we are on 1.4.1) but if I read it correctly we have to stick on 1.4.1.

If that is correct maybe we should put a note somewhere that this cannot be updated

https://github.com/bestiejs/punycode.js

**Comment by mbabker** [comment]
> Punycode.js v2.0.0 targets Node.js v6+ and nothing else.

Yep, that needs to be blacklisted against updates.

**Comment by brianteeman** [comment]
Glad I read it correctly ;)

Any suggestion how to "blacklist" - add a comment in the current version but thats modify an external library?

**Comment by brianteeman** [comment]
See #10983<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10981">issues.joomla.org/joomla-cms/10981</a>.</sub>
