### ISSUE TITLE
Feature Request: Browsertitle Options in Article Meta Options

### ISSUE THREAD

**Issue by designbengel** [joomla/joomla-cms#10999]
If you don´t have an menuitem it´s impossible to control the browsertitle of an article.
For example if you just use a lastest News Module and don´t add the items to a menu the browsertitle is always just the title of the article. For SEO it would be better to have unique browsertitles.
Can we add the browsertitle also above the meta description in Article options?

**Comment by mbabker** [comment]
See https://github.com/joomla/joomla-cms/pull/10838
