### ISSUE TITLE
date search category

### ISSUE THREAD

**Issue by ZerooCool** [joomla/joomla-cms#11004]
#### Steps to reproduce the issue
I search a word with the search tool.

I have not the creation date : 

    Éditoriaux Technologies (Catégorie)
        Informatique, sciences, dossiers non classés. ... 
Créé le  .......................................
    Éditoriaux Sciences (Catégorie)
        Information et Communication.
Créé le ............................................;

#### Expected result
How i can see the creation date ?

How i can patch the code ?

I mean, the BDD is ok. ( not sur )

#### Actual result
    Éditoriaux Sciences (Catégorie)
        Information et Communication.
Créé le NOTHING

#### System information (as much as possible)
All : )

#### Additional comments
<3

**Comment by bertmert** [comment]
If you are talking about the frontend of your page I think the best way is to ask in a forum how to create an template override that also shows the creation date of categories.

If you are talking about the backend (Joomla administration). Could you please make some screenshots where you want to see the creation date of categories (in a column? Behind the Alias:? ... ).

(What is BDD?)

**Comment by brianteeman** [comment]
I am closing this at this time due to lack of reply. It can always be reopened if updated.

**Comment by ZerooCool** [comment]
Hi, 

Example
https://www.visionduweb.eu/component/search/?searchword=science&searchphrase=all&Itemid=212

 1. Éditoriaux Technologies
    (Catégorie) 
     - Informatique, sciences, dossiers non classés.  ... 
    Créé le      

I not have the date.



BDD = base de données, = database
I have a created_time date.


I not have the date to the front end.
Thanks for your help.

**Comment by brianteeman** [comment]
Please use http://forum.joomla.fr/ or http://forum.joomla.org

**Comment by ZerooCool** [comment]
Ok, http://forum.joomla.fr/showthread.php?216948-date-ne-s-affiche-pas-apr%C3%A8s-une-recherche-qui-affiche-une-cat%C3%A9gorie&p=1104422#post1104422
