### ISSUE TITLE
How Make a Bridge - "search" content with Joomla! in media wiki data

### ISSUE THREAD

**Issue by ZerooCool** [joomla/joomla-cms#11005]
#### Steps to reproduce the issue
I search information. It's not a bogue.

#### Expected result
A Bridge, then i can search a word with Joomla! search, but,  in data media wiki.

#### Actual result
Not exist.

#### System information (as much as possible)
All.

**Comment by brianteeman** [comment]
Sorry I don't understand what the question is?

**Comment by nikitadhiman** [comment]
Joomla! have wikipedia page already and dedicated docs for too. For educational content with which wikimedia helps with, other similar sources are available too! I guess that's the point you were trying to make and if not please explain the issues in more details

**Comment by brianteeman** [comment]
Closing due to  lack of reply. It can always be reopened <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11005">issues.joomla.org/joomla-cms/11005</a>.</sub>

**Comment by ZerooCool** [comment]
I search doc, for Media Wiki, and Joomla!

I want search, with Joomla! Content in Media Wiki.

I search content, then i can read and make. I have nothing today.

**Comment by RonakParmar** [comment]
Still not getting, what is the issue? Please provide some-more clear steps to re-produce the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11005">issues.joomla.org/joomla-cms/11005</a>.</sub>

**Comment by mbabker** [comment]
If I'm getting the title of this correctly, you want to use the JMediawiki classes to bridge your Joomla install to MediaWiki by the API to do stuff.  You'll still need to write your own Joomla extensions to do that though; the library class is just an API wrapper.

**Comment by chrisdavenport** [comment]
If your intention is to search MediaWiki content from Joomla then you need to use Smart Search and write a plugin that will take content from the wiki and index it.  You can use the MediaWiki web API to do that and the JMediaWiki classes are available to help you.  You'll need to write a CLI script to pull all the content from the wiki to index it initially and then run a cron script to pull the Recent Changes feed from the wiki to keep the index up-to-date.

However, if that is what you're asking, then this is not an issue with Joomla and as this is not a support forum, this issue should be closed.

**Comment by gunjanpatel** [comment]
Set to "closed" on behalf of @gunjanpatel by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11005">issues.joomla.org/joomla-cms/11005</a>

**Comment by gunjanpatel** [comment]
Closing as request can be done though plugin or other ways. Not for core. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11005">issues.joomla.org/joomla-cms/11005</a>.</sub>

**Comment by ZerooCool** [comment]
This plugin for Joomla work, for search a word in Mediawiki :
https://github.com/rebootl/plg_search_mediawiki

Resolved
