### ISSUE TITLE
Release blocker? : Not able to see submenu items of component

### ISSUE THREAD

**Issue by RonakParmar** [joomla/joomla-cms#11013]
#### Steps to reproduce the issue
If we have many components list under "Components" menu and if our component menu is at the last we are not able to see all submenu items of our component.
![screen shot 2016-07-04 at 00 42 22](https://issues.joomla.org/uploads/1/78432933e2082917ea180975592c70b8.png)

#### Expected result
Able to see all submenu items.

#### Actual result
Not able to see all submenu items.

#### System information (as much as possible)
Joomla! Version : Joomla! 3.5.1 Stable [ Unicorn ] 05-April-2016 22:45 GMT 
PHP Version : 5.4.45-4+deprecated+dontuse+deb.sury.org~precise+1

**Comment by infograf768** [comment]
Please first install staging ( https://github.com/joomla/joomla-cms/archive/staging.zip) and apply this patch:
https://github.com/joomla/joomla-cms/pull/10987

**Comment by infograf768** [comment]
After testing on RC with ir without that patch, I confirm the issue.
This is a release blocker.

**Comment by infograf768** [comment]
To test on RC + #10987 , just modify in ROOT/administrator/language/en-GB/en-GB.com_banners.sys.ini
`COM_BANNERS="Banners"`
to
`COM_BANNERS="Zbanners"`
to force Banners to be displayed last in the Components Menu dropdown

![screen shot 2016-07-04 at 08 40 39](https://cloud.githubusercontent.com/assets/869724/16552640/06d9fc5e-41c3-11e6-9dec-f2131123ba8f.png)

**Comment by C-Lodder** [comment]
I'll have a look into this today if I have time.

**Comment by JamalTailored** [comment]
I have also checked this and able to reproduce this issue.

Joomla Version : 3.5.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11013">issues.joomla.org/joomla-cms/11013</a>.</sub>

**Comment by brianteeman** [comment]
@JamalTailored Please only test against the current staging. There have been over 400 commits since Joomla 3.5.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11013">issues.joomla.org/joomla-cms/11013</a>.</sub>

**Comment by jaytasol** [comment]
test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://192.168.5.156/jissues/www/tracker/joomla-cms/11013">192.168.5.156/jissues/www/joomla-cms/11013</a>.</sub>

**Comment by PhilETaylor** [comment]
Confirmed hours before 3.6 release on 25193c6072c81696d1a5661ebd126d8e1df328b9

**Comment by C-Lodder** [comment]
Gonna work on a fix now

**Comment by brianteeman** [comment]
Too late for the 3.6 release

**Comment by C-Lodder** [comment]
Yup that's no worries, can be for the next one

**Comment by C-Lodder** [comment]
https://github.com/joomla/joomla-cms/pull/11080

**Comment by PhilETaylor** [comment]
@brianteeman Please close in favour of testing PR #11080
