### ISSUE TITLE
 &hitcount=0 in the url of multilanguage sites

### ISSUE THREAD

**Issue by stellainformatica** [joomla/joomla-cms#11016]
#### Steps to reproduce the issue
Install a multilanguage site with the automatic installation that offers Joomla. 2 languages are enough.
In Articles Options set the parameter  Show Voting on Show.
In frontend click on an article and then look the url generated when you go over flags.

#### Expected result
The urls are normal 

#### Actual result
If you click on the english article and then click on the english flag, you will see that the url change, 
at the end  &hitcount=0 is added

#### System information (as much as possible)
Joomla 3.5.1

![screen shot 2016-07-04 at 06 36 21](https://issues.joomla.org/uploads/1/e1533de28131c616e47f579efee91c69.png)

**Comment by infograf768** [comment]
Same behaviour in 3.6.0 RC.
The link has hitcount added when hovering the flag of the Content Language displayed at the time.

**Comment by Bakual** [comment]
It's probably like this for years. The argument is generated by the voting plugin and it was added here: https://github.com/joomla/joomla-cms/commit/811e839bba8201dfeae8e4619d55755d26f961db#diff-af047d54862b5a4c88c3eda651c030f8R54

Apparently it changes the global query and if the language flag URLs are generated after the voting plugin changed the URI, it will show up there as well.

Not sure if something else changed somewhere so it only surfaced now, but there has indeed to be a better way :smile:

**Comment by mbabker** [comment]
Make a clone of the global instance and you don't have to worry about it being messed with.  The joys of having an application so tightly coupled to global state and singleton objects.

**Comment by Bakual** [comment]
See https://github.com/joomla/joomla-cms/pull/11029. Thanks @mbabker for the hint.
