### ISSUE TITLE
My Joomla website lost all the configurations I've done. How could this be? 

### ISSUE THREAD

**Issue by richardengelhardt** [joomla/joomla-cms#11025]

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.joomla.org

**Comment by richardengelhardt** [comment]
Hello Brian,

I have registered on the forum but can’t  get authorization to post in the forum. Apparently I should participate more before posting my first post? what can I do?  should I be invited to send posts on the joomla forum?

**Comment by jeckodevelopment** [comment]
@pe7er can you look at this?
