### ISSUE TITLE
J! 3.6 RC -> TinyMCE Textfilter bug

### ISSUE THREAD

**Issue by designbengel** [joomla/joomla-cms#11020]
#### Steps to reproduce the issue
Settings: 
1) Superadmin "No Filter"
2) TinyMCE - Joomla! Textfilter Settings: YES

Try to add `<span class="fa fa-phone fa-3x sr-contact“></span> <p>123-456-6789</p> ` in a module.

#### Expected result
The code should be accepted.

#### Actual result
The code is stripped out.

#### Steps to reproduce the issue
Settings: 
1) TinyMCE - Joomla! Textfilter Settings: NO
Allowed elements: class, span

Try to add `<span class="fa fa-phone fa-3x sr-contact“></span> <p>123-456-6789</p> ` in a module.

#### Expected result
The code should be accepted.

#### Actual result
The code is stripped out.

**Comment by bembelimen** [comment]
For 1:
see https://github.com/joomla/joomla-cms/issues/11022
For 2:
to prevent the TinyMCE to filter attributes, you have to add the attributes in the "valid elements" box like:
```span[class]```

**Comment by brianteeman** [comment]
Closing as we have a PR #11022
