### ISSUE TITLE
Wrong path for scripts in head

### ISSUE THREAD

**Issue by alex7r** [joomla/joomla-cms#11032]
![2016-07-06_09-45-23](https://cloud.githubusercontent.com/assets/18716997/16609691/b8620b00-435e-11e6-8de8-36817ceaba1c.png)

#### Steps to reproduce the issue
Go to admin panel "Manage section"

Also may need, but don't thinks this is related:
Update 3.6.0-alpha
To 3.6.0-rc

#### Expected result
Scripts loaded correctly

#### Actual result
Scripts not loaded as path is bad

#### System information (as much as possible)
OS Windows
Server: OpenServer
Php7
Chrome Browser

**Comment by zero-24** [comment]
@alex7r please test with this patch applyed: https://github.com/joomla/joomla-cms/pull/10956

**Comment by zero-24** [comment]
This got merged / fixed after the RC1 Release ;)

**Comment by alex7r** [comment]
@zero-24 thanks for the info
