### ISSUE TITLE
Can't Close Media Field w/ multiple WYSIWYG Editors

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#11047]
#### Steps to reproduce the issue

Add this snippet to `administrator/components/com_content/models/forms/article.xml`:

```xml
		<field name="extrafield" type="editor"
			label="An Extra Field" description="Whatever"
			filter="JComponentHelper::filterText" buttons="true" />
```

In `administrator/components/com_content/views/article/tmpl/edit.php` render the new field:

```php
<?php echo $this->form->getInput('extrafield'); ?>
```

Go to any media form field (the "Images and links" tab works for this), select an image, and try to close the modal in any available manner (the insert/cancel buttons, the X icon, or clicking outside the modal).

#### Expected result

The modal is closed.

#### Actual result

The modal does not close.  In the browser console is a "Uncaught RangeError: Maximum call stack size exceeded" message.

#### System information (as much as possible)

Clone of the CMS as of bb1010ae038f6cbaf4aa78760b394bb13b6339ad

**Comment by dgt41** [comment]
@mbabker my bad! will do a PR in few minutes

**Comment by dgt41** [comment]
Check #11048

**Comment by brianteeman** [comment]
Closed as we have a pr
