### ISSUE TITLE
Chrome does not redirect correctly on login

### ISSUE THREAD

**Issue by visualtribe** [joomla/joomla-cms#11059]
#### Steps to reproduce the issue
Use Chrome to login to site. When login menu has a redirect to page, Chrome defaults to index.php page not the redirect page. 

#### Expected result
redirect to the inputted redirect page in login menu parameters

#### Actual result
redirects to index.php page and puts error on page
Error
You are not authorised to view this resource.
Client has the right ACL to the page in question. Tested and versified through FireFox.

#### System information (as much as possible)
PHP 5.6.23 and 7.0.8
Mac and PC Chrome

#### Additional comments
Client has this issue. I have verified it with my own version of Chrome. Another person verified it with their version of Chrome. All parties deleted their browser history and cookies for site. Happens every time. If login with the same login through FireFox, page redirects properly. 

Have tried different redirect scenarios
the full url like index.php?option=com_k2&view=item&layout=item&id=7
index.php/tbt-program
tbt-program

Tried installing a component to fix issue that redirects on login. Chrome still oversteps process and defaults to index.php

**Comment by brianteeman** [comment]
I am not able to replicate this

Can you confirm this using one of the default templates?



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11059">issues.joomla.org/joomla-cms/11059</a>.</sub>

**Comment by visualtribe** [comment]
I will try to test that. Thanks for getting back to me. So when you use Chrome and you login with a redirect to another page other than index.php, it goes to that redirect page? 

I am using a default template. Do you mean Beez or Protostar template. If so, which page should have that template, the redirect page or login?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11059">issues.joomla.org/joomla-cms/11059</a>.</sub>

**Comment by brianteeman** [comment]
On 9 Jul 2016 7:32 p.m., "visualtribe" <notifications@github.com> wrote:
>
> I will try to test that. Thanks for getting back to me. So when you use
Chrome and you login with a redirect to another page other than index.php,
it goes to that redirect page?
>

Yes that's correct

> I am using a default template. Do you mean Beez or Protostar template

Yes I mean on of those two to rule out an issue with your template

. If so, which page should have that template, the redirect page or login?
>

For testing purposes it should be the entire site



> ________________________________
> This comment was created with the J!Tracker Application at
issues.joomla.org/joomla-cms/11059.

**Comment by visualtribe** [comment]
I tested Chrome on another site that I have with a different template and it redirected correctly. I will inform the template company of this and see if they can rectify the issue. Would you know what might be causing the issue. Java, php so that I may direct them in the right area.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11059">issues.joomla.org/joomla-cms/11059</a>.</sub>

**Comment by visualtribe** [comment]
I have also confirmed that it might not be the template as I have other sites with this same base template, Helix, and Chrome redirects properly here. Do you know if Joomla collects information in the database that looks at pages or sessions that might cause this issue. Not saying that it is still Joomla. I will have to look at components and plugins next.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11059">issues.joomla.org/joomla-cms/11059</a>.</sub>

**Comment by brianteeman** [comment]
Sorry I can't think of anything.

As we have now confirmed it is not an issue with the core of joomla I am
closing this.

If you need further help please use the forum at http://forum.joomla.org
