### ISSUE TITLE
Missing toolbars in backend

### ISSUE THREAD

**Issue by ihadblackwell** [joomla/joomla-cms#11055]
#### Steps to reproduce the issue
We are missing the section of tool bars between the top menus and the list of articles, article editor, etc. So I can scroll to find an article (can't search for it) and can edit it, but then am missing the buttons to Save, Save & Close, etc.

Photo attached with missing area circled in red.

#### System information (as much as possible)

This problem occurs on both PCs and Macs in our organization. I believe we are using Joomla 3.5

#### Additional comments

I'm just a basic user, updating content, and don't have any experience as a developer, so a the most detailed help you are able to provide would be great!

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.joomla.org
