### ISSUE TITLE
Incompatible data use in edit layouts

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#11054]
#### Steps to reproduce the issue

The `joomla.edit.global` and `joomla.edit.publishingdata` layouts both have a call to `$displayData->get('fields')` (a JViewLegacy instance) and if nothing is returned from that both of them specify an array of fields to be displayed.  However, both of these layouts use separate default arrays, therefore it is not possible to use the get method to specify fields to display for only one of the layouts.

Note that this may affect more layouts, however I have only looked at these two explicitly because they are the two I hit this bug with.
#### Expected result

Fields references should be unique to each layout.
#### Actual result

Fields references are global and affect multiple layouts.

**Comment by brianteeman** [comment]
Thanks. That explains the issue I had this morning as well.

**Comment by mbabker** [comment]
Fixing this requires major B/C breaks to the logic in a lot of layouts.  Closing as too disruptive.
