### ISSUE TITLE
Added syntax to load duplicate module using Content - Load Modules plugin

### ISSUE THREAD

**Issue by RonakParmar** [joomla/joomla-cms#11066]
#### Steps to reproduce the issue
There is no syntax to load duplicate module in article using Content - Load Modules plugin description.

#### Expected result
There should be syntax to load duplicate module in article.

#### Actual result
No syntax available.

#### System information (as much as possible)
Joomla Version: Joomla! 3.6.0-rc Release Candidate [ Noether ] 28-June-2016 20:34 GMT

**Comment by brianteeman** [comment]
Closed as we have a PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11066">issues.joomla.org/joomla-cms/11066</a>.</sub>
