### ISSUE TITLE
Link prefetching support for stylesheets

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#11077]
`JDocumentRendererHtmlHead` uses a hardcoded `rel="stylesheet"` attribute for CSS link elements which means the API does not have a way to set custom relation attributes such as those used for [link prefetching](https://en.wikipedia.org/wiki/Link_prefetching).  This specific portion of the API needs improvement to allow custom rel types to be added.  Note that it can be done already with `JDocumentHtml::addHeadLink()` so it's just the stylesheet portion of `JDocument` that needs attention.

**Comment by andrepereiradasilva** [comment]
actually even addHeadLink has a problem if you whant to add a link with an href that's already added.

In that case the only option is to add a addCustomTag
example https://github.com/joomla/joomla-cms/blob/staging/plugins/system/languagefilter/languagefilter.php#L732-L748

This is a problem with some JDocument methods. They also use attrib values as arrays keys, so they can't be duplicated.

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/pull/15880 for 4.0.
