### ISSUE TITLE
Articles - Category module in dynamic mode invisible when breezingforms embed code is added to article.

### ISSUE THREAD

**Issue by jvdh20** [joomla/joomla-cms#11072]
This issue is happening in Joomla 3.5.1 and most recent version Breezingforms 1.8.7 (build 889).
With the "Articles Category" module you can automatically show the correct links to other related articles when the Mode is set to Dynamic.
This works good but Breezingforms has a plugin with which you can embed a breezingsforms form in any article when you use the code 
The problem is that when you use the breezingforms plugin code in an article the "Articles Category" module dissapears when it is set to Dynamic mode. If you delete the <div>{ BreezingForms : nameOfForm, 1, 0 }</div> code al is working again.
So somewhere adding <div>{ BreezingForms : nameOfForm, 1, 0 }</div> in the article disconnects the relation with the other articles in the same category.
This shouldn't be happening because the form is simply embedded in the article.

**Comment by brianteeman** [comment]
Have you reported this to breezing forms

**Comment by bertmert** [comment]
I confirm that this is a BF issue, not a Joomla issue. The BF plugin manipulates/changes input datas (request datas) in this way:

```
JRequest::setVar('option', 'com_breezingforms');
```

And mod_articles_category reacts only on `option=com_content`

**Comment by jvdh20** [comment]
Thanks for confirming this is a BF issue Bertmert!
I've reported the bug at [https://crosstec.org/en/forums/5-bugs/112831-bf-plugin-code-disables-articles-category-module.html](url)

**Comment by brianteeman** [comment]
Closed
