### ISSUE TITLE
mod_custom didn't suport Modul-Tag

### ISSUE THREAD

**Issue by thuebschmann** [joomla/joomla-cms#11071]
#### Steps to reproduce the issue
You can choose Module-Tag (module_tag) in Backend of the mod_custom but in the template field ist an hard "div".

#### Expected result
Please use the Module-Tag parammeter.
[default.txt](https://issues.joomla.org/uploads/1/7ccee69e4b959b444d71bef483a091c9.txt)
replacement for /modules/mod_custom/tmpl/default.php

#### Additional comments

Please check file and added to the next-version

**Comment by mbabker** [comment]
The `module_tag` parameter is applied to the module chrome and isn't used internal to any module's output.  Also, this change would break the HTML output of existing sites which have set this option to anything except `<div>`.

This is expected behavior.

**Comment by brianteeman** [comment]
Closed as expected behaviour as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11071">issues.joomla.org/joomla-cms/11071</a>.</sub>
