### ISSUE TITLE
refreshIncludePaths() has been removed, not deprecated (B/C Break!)

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#11084]
Related to: https://github.com/joomla/joomla-cms/pull/8925

#### Steps to reproduce the issue
Quickest was I can think to test is to download my extension:

https://github.com/JoomJunk/shoutbox/releases/tag/8.1.4

#### Expected result

On Joomla 3.5, is works perfectly fine. The shouts are displayed. Should also work fine on Joomla 3.6

#### Actual result

On Joomla 3.6, none of the shouts are displayed. We've extended `JLayoutFile` and have the following:

```
protected function refreshIncludePaths() { ... }
```

Having looked at the `JLayoutFile` class, this function appears to be deprecated, but was instead removed.

The fix was to change the above function to:

```
public function clearIncludePaths() { ... }
```

**Comment by mbabker** [comment]
#11085 reverts #8925 which should address this assuming nothing else has changed.
