### ISSUE TITLE
Update issue: "Argument 3 passed to JClientFtp::getInstance() must be of the type array, null given, called in /var/www/site/libraries/joomla/filesystem/file.php on line 488"

### ISSUE THREAD

**Issue by addondev** [joomla/joomla-cms#11082]
#### Steps to reproduce the issue

Update Joomla! to version 3.6. 

#### Expected result

OK.

#### Actual result

Argument 3 passed to JClientFtp::getInstance() must be of the type array, null given, called in /var/www/site/libraries/joomla/filesystem/file.php on line 488

#### System information (as much as possible)

Ubuntu + Nginx + PHP-7-FPM

#### Additional comments

I use FTP layer and have strong file permissions.

**Comment by brianteeman** [comment]
Have you ever updated this site before? That specific file has not been updated for a while

**Comment by addondev** [comment]
Yes I have. I used 3.5.1 version. When i switch off the FTP layer, it updates correctly, but when the FTP layer is on, I have got this error.

**Comment by richard67** [comment]
I can confirm that, had to switch off FTP layer, too, to avoid the error.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11082">issues.joomla.org/joomla-cms/11082</a>.</sub>

**Comment by mbabker** [comment]
See #11086

**Comment by jppjpp** [comment]
I have the same issue whatever the method I use (direct, hybrid or ftp)

**Comment by ggppdk** [comment]
@jppjpp 

The fix exists in J3.6.1+, **older Joomla versions**  do not get the fix automatically, but this prevents you from running Joomla upgrade  (also setting error_reporting to 'none' has not effect on this one)

Simplest way out of this is (if you can edit the file)
- is do it and edit the file to apply the patch and then upgrading Joomla should work

At about line 488 of  libraries/joomla/filesystem/file.php   (**backup the file 1st**)
**find:**
```
$ftp = JFTP::getInstance($FTPOptions['host'], $FTPOptions['port'], null, $FTPOptions['user'], $FTPOptions['pass']);
```

**replace with:**
```
$ftp = JClientFtp::getInstance($FTPOptions['host'], $FTPOptions['port'], array(), $FTPOptions['user'], $FTPOptions['pass']);
```
