### ISSUE TITLE
REGRESSION: Login/Logout Redirect not working properly in 3.6.0 stable

### ISSUE THREAD

**Issue by carson3511** [joomla/joomla-cms#11089]
This issue affects both the Login module as well as the Logout menu item redirects.
I have tested this on development and a vanilla installation of Joomla 3.6.0 stable with same results with sites using varying versions of PHP5.6 and 7.

#### Steps to reproduce the issue
1. Create a logout menu item.
2. For the Logout menu item set a redirect page.
3. In the Login module, set a login and logout redirect page.
4. Login to the website and see if you are redirected to the proper page. 
5. Now logout of the site using the Login module's logout button.
6. Login again and then logout using the Logout menu link you previously created.

#### Expected result
Login and logout should redirect to the proper pages.

#### Actual result
Logout button in the logout module and the Logout menu item is not redirecting to the assigned pages.
The URL shows a non-SEF URL when logging out via both methods even if SEF URLs are enabled.
Example of URL shown when logging out is:
http://mysite.com/index.php?option=com_users&task=user.logout&8bbd8228ca6184b4718b255cb797e75a=1&return=aW5kZXgucGhwP0l0ZW1pZD0xMDE=

#### System information (as much as possible)
1. Tested in both PHP 5.6 and 7.0.2
2. SEF URL's are enabled. Tested with and without mod_rewrite enabled with same results.
3. Tested in development sites on localhost server as well as live hosting servers at Cloudaccess with same results in all environments.
4. Tested in a vanilla 3.6.0 Stable installation as well as multiple dev sites and one live site.

**Comment by infograf768** [comment]
Have you tested this on a 3.5.1 site?
Please use vanilla 3.5.1 and vanilla 3.6.0 and post here the redirections parameters you defined in the menu item as well as those used in the module.

**Comment by SharkyKZ** [comment]
See if reverting #10985 helps.

**Comment by carson3511** [comment]
Yes, I just did a fresh installation of 3.5.1 (no sample data) and created a few brand new articles with menu items to those articles.
1. I then created a user menu/module with a menu item to the user profile and another to the User Logout menu item type.
2. I then set the Logout menu item to redirect to the Homepage menu item.
3. I set the Login module to redirect me to the User Profile menu item after logging in, and the logout redirection to the homepage menu item. 
4. After logging into 3.5.1, I was redirected properly to the User Profile page as it should have worked.
5. When I use the logout button on the Login Module, I was properly redirected to the Homepage properly. If I use the logout menu item I was also redirected to the Homepage menu item per my settings.
So in 3.5.1 it is working properly on a vanilla install of 3.5.1.

Then I updated to 3.6.0 stable and tested it again.
1. After logging in, I am redirected to the User Profile as intended.
2. However, if I logout using the Logout menu item, I am shown a blank page with no article area content and the URL is as follows:
http://mysite.com/index.php?option=com_users&task=user.logout&241e435bfd2d08be06584c0ef60a26a3=1&return=aW5kZXgucGhwP0l0ZW1pZD0xMDE=
3. Using the Logout button on the Login Module to log me out of the system simply shows me a blank page (no article area content) but the URL is the same URL that I was viewing when I logged out. It just does not show the content area anymore. 

**Environment for this test**
Tested with vanilla installation of 3.5.1 then upgraded to 3.6.0
PHP 7.0.2
MySQL Database Version 	5.5.45-cll-lve 
Tested on live Cloudaccess.net server
SEF URL's enabled, mod_rewrite disabled in global config (default settings)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11089">issues.joomla.org/joomla-cms/11089</a>.</sub>

**Comment by infograf768** [comment]
@SharkyKZ
Indeed, https://github.com/joomla/joomla-cms/pull/10985 is the culprit.

GRRR.

**Comment by carson3511** [comment]
LOL, love you guys. 3.6.1 release tomorrow? Ha Ha!
Thanks
Mike<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11089">issues.joomla.org/joomla-cms/11089</a>.</sub>

**Comment by infograf768** [comment]
changed title<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11089">issues.joomla.org/joomla-cms/11089</a>.</sub>

**Comment by infograf768** [comment]
title<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11089">issues.joomla.org/joomla-cms/11089</a>.</sub>

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11089">issues.joomla.org/joomla-cms/11089</a>

**Comment by infograf768** [comment]
Closing, please test https://github.com/joomla/joomla-cms/pull/11093<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11089">issues.joomla.org/joomla-cms/11089</a>.</sub>

**Comment by edoorz** [comment]
Is this issue going to be fixed with a patch?  Cannot logout to the correct page from the login module since updating to 3.6.0

**Comment by brianteeman** [comment]
Yes 3.6.1 will be a release targeting approximately August 2nd/3rd

**Comment by edoorz** [comment]
Thank you.
