### ISSUE TITLE
Update issue: "The file Cache Storage is not supported on this platform"

### ISSUE THREAD

**Issue by addondev** [joomla/joomla-cms#11083]
#### Steps to reproduce the issue

Update to Joomla! 3.6. Navigate to content component in the administrator panel.

#### Expected result

OK.

#### Actual result

"The file Cache Storage is not supported on this platform"

#### System information (as much as possible)

Ubuntu + Nginx + PHP-7-FPM

#### Additional comments

if I empty a variable `public $cache_handler = 'file';` in the `configuration.php`, it works.

**Comment by mbabker** [comment]
The cache directory on your site should be writable.  If you have a custom
cache path check that otherwise check /cache.

**Comment by addondev** [comment]
It is writable -- 775. I do not use a custom cache path.

**Comment by mbabker** [comment]
Hmm.  Should be fine then.
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/cache/storage/file.php#L247
is the check.

Without a custom path defined, the path constant is relative to the app.
So /administrator/cache for admin and /cache for site.  Affecting both apps
or just one?

**Comment by addondev** [comment]
In my configuration.php file, there was not a variable `cache_path`, so I added one: `public $cache_path = '/var/www/addondev/cache';`, and now it works in the administrator panel.

**Comment by addondev** [comment]
Oh, sorry! That was my error. This is not an issue, so, i am closing this one!
