### ISSUE TITLE
Bug in Joomla 3.6.0 after update

### ISSUE THREAD

**Issue by shady717** [joomla/joomla-cms#11087]
After update from 3.5.1

In file

/libraries/joomla/access/access.php

At line 595 Offest not set Should be changed to 

foreach ($ancestors as $id)
                        {
                                if (isset(self::$assetPermissionsById[$extensionName][$id])){
                                $collected[] = self::$assetPermissionsById[$extensionName][$id]->rules;
                                }
                        }

to check for missing array offset

**Comment by infograf768** [comment]
Please give test instructions to reproduce the possible issue:
What do we get now and what we should get after your proposal (in a vanilla 3.6.0)

**Comment by shady717** [comment]
Hey I just upgraded another site of mine http://2itsupport.com

here is the page with the notice. 
http://2itsupport.com/main-content/service-plans

and another

http://2itsupport.com/it-technologies-supported/supported-it-technologies

it seams all menu item type -> single article have that issue.

Thanks,
Shady<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11087">issues.joomla.org/joomla-cms/11087</a>.</sub>

**Comment by shady717** [comment]
my links are changing as I am working on upgrading that site.. 

http://2itsupport.com/it-support-service-plans

sorry please just look around I have many single artivle pages. I have notices ON in PHP so just so we can see it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11087">issues.joomla.org/joomla-cms/11087</a>.</sub>

**Comment by shady717** [comment]
I have removed the notices from the website due to unprofessional-ism.. This can be literally replicated on all of my joomla instances BTYW<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11087">issues.joomla.org/joomla-cms/11087</a>.</sub>

**Comment by brianteeman** [comment]
So it must be something you have either done yourself or an extension you
have installed as we have no other reports of this issue

**Comment by shady717** [comment]
I doubt it. But OK we can definitely close the ticket I was just trying to make Joomla better, because I like it. I can definitely change the code so its not noticing that... most of my websites are from Joomla 2.5 -> 3.3 -> 3.5 ->3.6

It could be a bigger down the line upgrade path issue which is hard to track! 

Thanks!

**Comment by brianteeman** [comment]
Closed
