### ISSUE TITLE
Send Test Email

### ISSUE THREAD

**Issue by Jose-Sanchez-Martin** [joomla/joomla-cms#11098]
#### Steps to reproduce the issue

Login in administrator
Select Global Configuration
Server
Select SMTP in mail settings
Try to send a test mail using smtp

#### Expected result

SMTP test result showed

#### Actual result

Javascript error in console: Uncaught ReferenceError: sendtestmail_url is not defined
File: sendtestmail.js
Line: 6

**Comment by brianteeman** [comment]
Which version of Joomla?
Which web browser?
If this was after an update can you confirm that you cleared the browser cache<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11098">issues.joomla.org/joomla-cms/11098</a>.</sub>

**Comment by Jose-Sanchez-Martin** [comment]
Joomla 3.6.0
Chrome 51.0.2704.103

Clear cache solved the issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11098">issues.joomla.org/joomla-cms/11098</a>.</sub>

**Comment by brianteeman** [comment]
Closing as this would be expected behaviour that cache needs to be cleared on an update<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11098">issues.joomla.org/joomla-cms/11098</a>.</sub>

**Comment by PhilETaylor** [comment]
Cache issue - no issue to resolve. The JS is added with JFactory::getDocument()->addScriptDeclaration to the head of the admin document so it can have a CSRF token appended to it at load time.  A Cache clear after update should be a must - or Joomla should implment cache busting.. which it currently doesnt.

**Comment by mbabker** [comment]
Joomla actually started clearing its cache with the post update script - https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/script.php#L1813

Problem is that it's only clearing the frontend cache.  There's a cache for the backend too but that doesn't get flushed on update (you'd have to set the `client_id` state to "1" and trigger the clean method in the model again).

Now if you're talking about browser level cache, well, good luck...

**Comment by brianteeman** [comment]
@mbabker would you be able to do that PR please. It will save a LOT of aggravation on each update. I would do it myself if I knew how.

**Comment by rdeutz** [comment]
I can do it, it's two lines of code

**Comment by brianteeman** [comment]
Thanks - it will make a big difference
(I guess we wont need the message about clearing the cache any more then)

**Comment by andrepereiradasilva** [comment]
brian and for browser cache i proposed https://github.com/joomla/joomla-cms/pull/11289 for (among other things) allow to attach the version string when using JHtml script methods (used all over the core).

This PR will not solve the browser cache issues yet, but IMHO it's a first step.

**Comment by spetricko** [comment]
Do I clear cache, or only expired cache?

**Comment by ghost** [comment]
@spetricko i suggest to ask on [forums](https://forum.joomla.org/) as Comments on closed Issues didn't get much Notice.
