### ISSUE TITLE
TinyMCE + SqueezeBox modal close bug

### ISSUE THREAD

**Issue by OctavianC** [joomla/joomla-cms#11091]
#### Steps to reproduce the issue
- For the sake of using SqueezeBox (MooTools based) instead of the Bootstrap Modal, change the Administrator template to Hathor. It's damn ugly, I know :)
- Make sure you're using TinyMCE as your Editor.
- Go to Content > Articles > Add New Article.
- In the Publishing area, click on the "User" icon so you can select a user from the modal.
- The modal shows up. Click outside the modal or on the X button to close it.

#### Expected result
Modal is closed.

#### Actual result
Modal is not closed - Firebug shows:

```
too much recursion
SqueezeBox.close = function () {
```

#### System information (as much as possible)
Joomla! 3.6.0, Firefox 47.0.1

#### Additional comments
Seems to be caused by the code TinyMCE replaces (https://github.com/joomla/joomla-cms/pull/11048) in the `SqueezeBox.close()` function. Will take a deeper look into the code, see if I can come up with a fix and PR.

**Comment by OctavianC** [comment]
Further info: clicking on a user from the modal doesn't work either, same error but now the highlighted function seems to be:
```
jModalClose = function () {
```

**Comment by dgt41** [comment]
@OctavianC check https://github.com/joomla/joomla-cms/pull/11097

**Comment by brianteeman** [comment]
Closed as we have a PR for testing
