### ISSUE TITLE
Clear Cache button on Joomla Update page is confusing

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-cms#11090]
The **Clear Cache button** on the **Joomla Update page** is confusing.
It does not clear Joomla's cache, but Joomla's Update Channel cache.

#### Steps to reproduce the issue
On Joomla 3.5.1 (with Conservative Cache = ON), go to Components > Joomla! Update > I choose **Install the update**

![screen shot 2016-07-13 at 01 59 57](https://issues.joomla.org/uploads/1/89eb74ce067040af17c3597d8f9219e7.png)

![screen shot 2016-07-13 at 02 00 22](https://issues.joomla.org/uploads/1/3bd7bbb80278d19e0124bc324daf1c6b.png)

Everything went okay. My website was successfully updated to Joomla 3.6.0. 
As recommended I **cleared the cache** by pressing the **Clear Cache** button.

![screen shot 2016-07-13 at 02 00 31](https://issues.joomla.org/uploads/1/c030e511172602fb078bca5658e6dea9.png)

However, after pressing the **Clear Cache** button, I did not get a message "Cleared Cache" but instead "**Cleared Updates**"

![screen shot 2016-07-13 at 02 00 36](https://issues.joomla.org/uploads/1/146c6283e3b734764181cb81f488fa75.png)

#### Expected result

I expected that pressing the **Clear Cache** button on Joomla's Update page **would have cleared all cache**.

#### Actual result
It did not clear all cache, but only the Joomla Update cache?

If you go to Extensions > Manage > Install, the options for installing extensions are missing:

![screen shot 2016-07-13 at 02 00 53](https://issues.joomla.org/uploads/1/682c30e4aee571823f2c4d413ca82746.png)

But the necessary Plugins are all enabled:

![screen shot 2016-07-13 at 02 01 07](https://issues.joomla.org/uploads/1/6b3a15b1a370451938b32b03356375b3.png)

As that seemed cache related, I had to empty Joomla's cache:
System > Clear Cache > Select [**Administrator**] > **Delete All**

![screen shot 2016-07-13 at 02 01 15](https://issues.joomla.org/uploads/1/df07bd0defcc6864c7abd299e73bab12.png)

After that, the administrator cache was cleared:

![screen shot 2016-07-13 at 02 01 22](https://issues.joomla.org/uploads/1/93157fbeee4df6ff9932c3c85c0e1bc0.png)

And I was able to use the Extension installer again:

![screen shot 2016-07-13 at 02 01 27](https://issues.joomla.org/uploads/1/b9ac9f009f3f82e2791b8278ef1eb8ba.png)

**Comment by brianteeman** [comment]
I "think" the functionality of that button is the same as the "refresh cache" button in  "Extensions: Manage"

So I think we have TWO different issues to resolve here

1. The button and its message need changing to more accurately reflect what they do
2. There should be a message immediately on an update recommending to clear the cache and a direct link to the cache manager where you can do that

**Comment by DavidBoggitt** [comment]
Forgive me if this is a daft question (from a non-coder), but is it possible to build in the functionality to empty Joomla's cache after a core update?

Many thanks,

Dave.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11090">issues.joomla.org/joomla-cms/11090</a>.</sub>

**Comment by pe7er** [comment]
Good question/suggestion @DavidBoggitt 
I don't know if that is possible. 

I was thinking about changing the language file with a clickable link to the System > Clear Cache > Select [Administrator] page...

**Comment by brianteeman** [comment]
@pe7er I think thats a good start

On 13 July 2016 at 10:57, Peter Martin <notifications@github.com> wrote:

> Good question/suggestion @DavidBoggitt <https://github.com/DavidBoggitt>
> I don't know if that is possible.
>
> I was thinking about changing the language file with a clickable link to
> the System > Clear Cache > Select [Administrator] page...
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/11090#issuecomment-232310960>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8VrRztEg68OP5BI5XzqYE9MVXqvCks5qVLZsgaJpZM4JLINb>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
> I "think" the functionality of that button is the same as the "refresh cache" button in "Extensions: Manage"
> So I think we have TWO different issues to resolve here
> 1. The button and its message need changing to more accurately reflect what they do
> 2. There should be a message immediately on an update recommending to clear the cache and a direct link to the cache manager where you can do that

3.And, since joomla doesn't implement browser cache busting in all static files (js/css/etc), another message to inform to the user to clear the browser cache. Or Joomla should implement cache busting (See related issue https://github.com/joomla/joomla-cms/issues/9638).

**Comment by pe7er** [comment]
@brianteeman or what about changing the [Clear Cache] to [Clear Update Channel] 
and adding a second real [Clear Cache] button (that triggers the [Delete All] functionality) ?

**Comment by brianteeman** [comment]
I prefer Refresh to Clear Update Channel

And I prefer Clear web site cache to Clear cache

On 13 July 2016 at 11:04, Peter Martin <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> or what about changing the
> [Clear Cache] to [Clear Update Channel]
> and adding a second real [Clear Cache] button (that triggers the [Delete
> All] functionality) ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/11090#issuecomment-232312599>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8c00Fj4Eaa9iFGZJsrRUgkef6COLks5qVLgZgaJpZM4JLINb>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
can't we add that clean cache behaviour to the update script?

**Comment by mbabker** [comment]
xref to https://github.com/joomla/joomla-cms/issues/11098#issuecomment-232341213

**Comment by brianteeman** [comment]
Closing as we have a PR for testing #11423<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11090">issues.joomla.org/joomla-cms/11090</a>.</sub>
