### ISSUE TITLE
[Joomla 3.6.0 upgrade] Empty article list in mod_articles_category module

### ISSUE THREAD

**Issue by wronax** [joomla/joomla-cms#11100]
#### Steps to reproduce the issue
Set "Article Field to Order By" option to "Featured Articles Order" in the Articles Category module options

#### Expected result
Articles displayed in featured articles order

#### Actual result
Empty articles list with warning messages:
Warning: Invalid argument supplied for foreach() in \components\com_content\models\articles.php on line 577
Warning: Invalid argument supplied for foreach() in \modules\mod_articles_category\helper.php on line 235

#### System information (as much as possible)
Joomla!3.6.0 (upgraded from 3.5.1)

#### Additional comments
It force website's owners to change ordering to make the modules display any articles after upgrade Joomla to 3.6.0.

**Comment by RonakParmar** [comment]
I am able to reproduce this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11100">issues.joomla.org/joomla-cms/11100</a>.</sub>

**Comment by andrepereiradasilva** [comment]
could it be related to https://github.com/joomla/joomla-cms/pull/9161/files ?

**Comment by bertmert** [comment]
Yes, it's related to this PR. I'll try a PR.

**Comment by bertmert** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/11105

**Comment by brianteeman** [comment]
Closed as we have a PR #11105 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11100">issues.joomla.org/joomla-cms/11100</a>.</sub>
