### ISSUE TITLE
The Install from Web plugin has become obsolete and needs to be updated.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#11108]
@brianteeman A quick one for you

http://screenshot.myjoomla.io/3S380O3P0C3C

"The Install from Web plugin has become obsolete and needs to be updated."

obsolete is the wrong english word

adjective
1. no longer in general use; fallen into disuse:
2. of a discarded or outmoded type; out of date:

Implies "abandoned, discarded"

instead of "this just needs updating...."

**Comment by brianteeman** [comment]
Pull requests welcome

**Comment by PhilETaylor** [comment]
I struggle to put a sentence together :-)

**Comment by brianteeman** [comment]
Based on your screenshot the plugin doesn't work at all and has to be replaced. If that's correct then I am happy with the word obsolete.

**Comment by PhilETaylor** [comment]
not at all - the extension still loads in the tab (under the screenshot) and functions normally. The update button when pressed quickly updates the install from web plugin and reloads the page - one assumes it upgraded - and the message goes away, the tab contents remain unchanged ...

**Comment by brianteeman** [comment]
I was going by the screenshot:)

As I've never installed it I can't replicate it myself.

If its still there AND working then you are right it's not obsolete at all
but outdated or requires update or update available

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #11112
