### ISSUE TITLE
Error String could not be parsed as XML: Feed Module Issue

### ISSUE THREAD

**Issue by sajalaspl** [joomla/joomla-cms#11106]
#### Steps to reproduce the issue
Not sure, it happens randomly.

#### Expected result
Should display Feeds

#### Actual result
Site is broken with Message like "Error 0 String could not be parsed as XML"

#### System information (as much as possible)
Joomla 3.5.x

**Comment by mbabker** [comment]
1) Joomla 3.6 made a change to the module to catch more error cases like this and not "break" the site.  Suggest upgrading first.

2) Sounds as though there is an issue with fetching the remote RSS feed and processing it.  I'd suggest going to the forum for support and sharing the feed URL you're pulling from when posting to get help debugging the issue.

**Comment by brianteeman** [comment]
I am going to close this at this time. It can always be reopened if there is still an issue with 3.6

**Comment by sajalaspl** [comment]
Thanks @mbabker.
