### ISSUE TITLE
Update from 3.5.x to 3.6 shows wrong version number

### ISSUE THREAD

**Issue by Bullnados** [joomla/joomla-cms#11116]
#### Steps to reproduce the issue
I get an email, that the versoin is availible. So i went to backend and try to update with the updater

#### Expected result
New version installed

#### Actual result
Old version still installed. No "New updates availible" message

#### System information (as much as possible)
Hoster: all-inkl.com

PHP erstellt für 	Linux dd8226 3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 x86_64
Datenbankversion 	5.6.30-nmm1-log
Datenbankzeichensatz 	latin1_swedish_ci
Datenbankverbindungszeichensatz 	utf8mb4_general_ci
PHP-Version 	5.6.21-nmm1
Webserver 	Apache
PHP-Interface für den Webserver 	fpm-fcgi
Joomla!-Version 	Joomla! 3.5.1 Stable [ Unicorn ] 05-April-2016 22:45 GMT
Joomla!-Plattform-Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by brianteeman** [comment]
What happened when you tried to do the update. Did it show an update taking place?

**Comment by Bullnados** [comment]
If i remember correctly, there was a green field with "update successful"
BTW cache cleaning in backand and browser doesn't matter

**Comment by ggppdk** [comment]
This must be bad **folder permissions** or some wrong path for **tmp** folder

- check / fix folder permissions
- check your tmp / log folder paths in configuration

After doing the above, if you cannot upgrade via the UI, 
**make a site backup**,

and try to extract the Joomla package files into joomla root folder, and then go to "Extensions\Manage\Database\Fix"

Note that if you upgrade like the above
you will need to discover / enable "installer plugins" for Joomla installer to work after upgrade, and also "Install more languages" button will show an empy list ...

**Comment by Bullnados** [comment]
Okay thanks, will try that the next days. The permission and folder sounds possible, but the last updates thre update process works flawlessly. 
BTW I still receive the emails, that an update is availible

**Comment by brianteeman** [comment]
I am closing this at this time as there doesnt appear to be any core bug just a failed update. It can always be reopened if requitred<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11116">issues.joomla.org/joomla-cms/11116</a>.</sub>

**Comment by Bullnados** [comment]
OK no problem. :)
