### ISSUE TITLE
JLIB_APPLICATION_ERROR_COMPONENT_NOT_LOADING

### ISSUE THREAD

**Issue by klaaba** [joomla/joomla-cms#11114]
Hi guys, 

I am new here. I updated our Joomla!-Site from 3.5.1 to 3.6 and now there is a Error Warning "JLIB_APPLICATION_ERROR_COMPONENT_NOT_LOADING".

In addition the backend language changed from German to English.

#### System information (as much as possible)

PHP Built On	Linux lvps176-28-19-180.dedicated.hosteurope.de 3.13.0-042stab113.11 #1 SMP Fri Dec 18 17:32:04 MSK 2015 x86_64
Database Version	5.5.47-0ubuntu0.14.04.1
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.5.9-1ubuntu4.14
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17

#### Relevant PHP Settings
Setting	Value
 
Safe Mode	Off
Open basedir	/var/www/vhosts/rabeneltern.org/:/tmp/
Display Errors	Off
Short Open Tags	On
File Uploads	On
Magic Quotes	Off
Register Globals	Off
Output Buffering	On
Session Save Path	/var/lib/php5
Session Auto Start	0
XML Enabled	Yes
Zlib Enabled	Yes
Native ZIP Enabled	Yes
Disabled Functions	pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,
Multibyte String (mbstring) Enabled	Yes
Iconv Available	Yes
Mcrypt Enabled	No
Maximum Input Variables	1000

#### Folder Permissions
Folder	Status
 
administrator/components	Writable
administrator/language	Writable
administrator/language/de-DE	Writable
administrator/language/overrides	Writable
administrator/language/en-GB	Writable
administrator/manifests/libraries	Writable
administrator/manifests/packages	Writable
administrator/manifests/files	Writable
administrator/modules	Writable
administrator/templates	Writable
components	Writable
images	Writable
images/M_images	Writable
images/startseite	Writable
images/sobipro	Writable
images/sampledata	Writable
images/smilies	Writable
images/com_sobi2	Writable
images/2011	Writable
images/zitate	Writable
images/fundstuecke	Writable
images/easyblog_articles	Writable
images/logo	Writable
images/jcollection	Writable
images/banners	Writable
images/stories	Writable
images/Blog	Writable
language	Writable
language/de-DE	Writable
language/overrides	Writable
language/en-GB	Writable
libraries	Writable
media	Writable
modules	Writable
plugins	Writable
plugins/k2	Writable
plugins/editors-xtd	Writable
plugins/user	Writable
plugins/quickicon	Writable
plugins/content	Writable
plugins/jotcacheplugins	Writable
plugins/ajax	Writable
plugins/system	Writable
plugins/jsnpoweradmin	Writable
plugins/twofactorauth	Writable
plugins/finder	Writable
plugins/mijopolls	Writable
plugins/easyblog	Writable
plugins/installer	Writable
plugins/xmap	Writable
plugins/extension	Writable
plugins/everything_in_everyway	Writable
plugins/captcha	Writable
plugins/authentication	Writable
plugins/editors	Writable
plugins/search	Writable
templates	Writable
configuration.php	Unwritable
cache (Cache Folder)	Writable
administrator/cache (Cache Folder)	Writable
/var/www/vhosts/rabeneltern.org/httpdocs/log (Log folder)	Writable
/var/www/vhosts/rabeneltern.org/httpdocs/tmp (Temp folder)	Writable

**Comment by andrepereiradasilva** [comment]
Not sure, but IIRC this warning appear when there is a issue with memcache.

See https://github.com/joomla/joomla-cms/pull/10815

**Comment by brianteeman** [comment]
Also see http://forum.joomla.org/viewtopic.php?f=710&t=928772&p=3413205#p3413205

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11114">issues.joomla.org/joomla-cms/11114</a>.</sub>

**Comment by brianteeman** [comment]
Closed as a duplicate report <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11114">issues.joomla.org/joomla-cms/11114</a>.</sub>
