### ISSUE TITLE
Default List Limit issues

### ISSUE THREAD

**Issue by itfidds** [joomla/joomla-cms#11118]
#### Steps to reproduce the issue
Go to Global Configuration - Site Settings
Select one of the new values (either 200 or 500)
Save

#### Expected result
Select an item (e.g. Users - Manage)
In the top right corner, select the dropdown for selecting List Limit
Options available should be 5, 10, 15...100, 200, 500

#### Actual result
The dropdown list still shows the old List Limits 5, 10, 15...100

#### System information (as much as possible)
Database Version  5.5.47  
Database Collation  latin1_swedish_ci  
Database Connection Collation  utf8mb4_general_ci  
PHP Version  5.5.37  
Web Server  Apache/2.4.18 (Unix)  
WebServer to PHP Interface  cgi-fcgi  
Joomla! Version  Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT  
Joomla! Platform Version  Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT  
User Agent  Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko

**Comment by pieter-groeneweg** [comment]
I noticed the same. 
In addition to the above.
Values 200 and 500 are not available in list limiter in the listings. (ie Article manager)
When selecting 200 or 500 in global, the value in the list limit dropdown shows 5 but the listing may show upto 200 or 500 articles. The 5 limit is not respected.
(opposed as to when selecting 5 in global, it will show just 5 and there is some pagination at the bottom)

**Comment by andrepereiradasilva** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/11120

**Comment by Bakual** [comment]
Closing as we have a PR
