### ISSUE TITLE
Joomla 3.6 Stable - favicon auto inserted in the header

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#11111]
#### Steps to reproduce the issue
My template has an option to manually select a favicon to use png image. favicon.ico also exists in my templates/$theme root folder and the theme logic is, when no image is selected in the template settings then use favicon.ico but Joomla 3.6 changes this since it seems that it auto inserts favicon.ico after the call for $this->addFavicon().

#### Expected result
No favicon is loaded when $this->addFavicon() is not called in the template.

#### Actual result
`<link href="/templates/$theme/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon"> `
is auto inserted when favicon.icon exists in the theme folder.

**Comment by mbabker** [comment]
Joomla's always done this.  Going back at least to 3.0.0, the [JDocumentHtml::_loadTemplate()](https://github.com/joomla/joomla-cms/blob/3.0.0/libraries/joomla/document/html/html.php#L546) method automagically adds the favicon if a `favicon.ico` can be found in either the template path or at the app's base path.

**Comment by brianteeman** [comment]
Closing as expected behaviour

**Comment by frogydiak** [comment]
Seems like it never worked before v3.6, prior versions (even 3.0.0) does not insert favicon.ico in the header.
