### ISSUE TITLE
New Featured Articles Add At End of the List in Joomla 3.6, Not At Beginning 

### ISSUE THREAD

**Issue by Quibi** [joomla/joomla-cms#11127]
After upgrading to Joomla 3.6.0, whenever I set a featured article (in the list of articles), this new featured article goes to the end of the list of featured articles. It gets the highest order number (i.e., if I have 5 featured articles and add one more, it becomes the 6th featured articles).

In Joomla 3.5 and earlier, a new featured article always becomes the first featured article.

I must say that Joomla 3.6.0's behaviour is weird. As a user, I feel that if I want to feature an article, the natural behaviour must that this featured article gets the first place. (This is the reason why I feature it, don't I?)

#### Steps to reproduce the issue

Feature an unfeatured article in the articles list.

#### Expected result

The new featured article must became the first featured article. Its order number must be 1.

#### Actual result

The new feature article becomes the last featured article!!!

#### System information (as much as possible)

Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
PHP 5.6.7 
MySql 5.5.46-cll-lve
Apache via cgi-fcgi

#### Additional comments

Could it be related with #11103 ?

**Comment by andrepereiradasilva** [comment]
i think it's the same as https://github.com/joomla/joomla-cms/issues/11103

**Comment by alikon** [comment]
yes confirm please follow  #11103

**Comment by andrepereiradasilva** [comment]
@brianteeman please close this one as it's a duplicate

**Comment by brianteeman** [comment]
Closed as requested
