### ISSUE TITLE
Logout issue - no redirection

### ISSUE THREAD

**Issue by cedricdw** [joomla/joomla-cms#11129]
#### Steps to reproduce the issue
Let's say we have a fresh install with a homepage, and a second page (single articles)
1) configure login module on page
2) configuration for login module "redirection after logout" = homepage (choose in dropdown)
3) login on frontend
4) go to the second page & logout
5) Content dissapears, and page is not redirecting, only login module is visible (logout has been done)

#### Expected result

- After logout, I'll get redirected to the homepage (as configured)

#### Actual result

I am logged out (ok), but I am not redirected to the configured page; and content dissapeared on page where I logged out. (URL stays same)

#### System information (as much as possible)

Joomla 3.6.0 
PHP gebouwd op 	Linux web169 4.1.12-20151123-0935-16fafb8 #1 SMP Mon Nov 23 09:37:22 UTC 2015 x86_64
Database versie 	5.5.47-MariaDB-1~wheezy
Database collatie 	latin1_swedish_ci
Collatie van de databaseverbinding 	utf8mb4_general_ci
PHP versie 	5.6.23
Webserver 	Apache
WebServer naar PHP interface 	cgi-fcgi
Joomla! versie 	Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT
Joomla! Platform versie 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Gebruikersagent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by andrepereiradasilva** [comment]
already fixed by https://github.com/joomla/joomla-cms/pull/11093 (already merged)?

**Comment by brianteeman** [comment]
Closed as a duplicate

**Comment by infograf768** [comment]
was fixed and merged indeed. for 3.6.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11129">issues.joomla.org/joomla-cms/11129</a>.</sub>

**Comment by cedricdw** [comment]
Great, issue fixed my problem. Thank you everyone :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11129">issues.joomla.org/joomla-cms/11129</a>.</sub>
