### ISSUE TITLE
v3.6 External URL menu item not inserting into "menu item type" field of "Details" section

### ISSUE THREAD

**Issue by MikeD56** [joomla/joomla-cms#11125]
#### Steps to reproduce the issue
- New menu item
- Select External URL type from selection dialog
- Upon return to new item dialog no entry in "menu item type" field

#### Expected result
"menu item type" field updated to "external URL"

#### Actual result
"menu item type" field remains blank

#### System information (as much as possible)
PHP Built On	Linux host255.hostmonster.com 3.12.52-20160119.106.ELK6.x86_64 #1 SMP Tue Jan 19 16:53:32 CST 2016 x86_64
Database Version	5.5.42-37.1-log
Database Collation	latin1_swedish_ci
PHP Version	5.6.17
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

#### Additional comments
If menu item type is some other item and you try and change it to External URL it will not change the type. It stays in the type already set.![screen shot 2016-07-14 at 10 11 44](https://issues.joomla.org/uploads/1/6feb72a89cf233dd9336d50f461e6ee3.png)
![screen shot 2016-07-14 at 10 11 44](https://issues.joomla.org/uploads/1/0cd212f406f47edfebc417b579b9a04b.png)![screen shot 2016-07-14 at 10 11 44](https://issues.joomla.org/uploads/1/043a0dda54a3811c0e531ba7f453e1aa.png)![screen shot 2016-07-14 at 10 11 44](https://issues.joomla.org/uploads/1/f218761d621a84700074afea36c13687.png)![screen shot 2016-07-14 at 10 15 51](https://issues.joomla.org/uploads/1/918a74ffe8948623d9923f5ec08db49e.png)![screen shot 2016-07-14 at 10 15 51](https://issues.joomla.org/uploads/1/cd32b8806fb544398ad8fff4e6175cf0.png)

**Comment by brianteeman** [comment]
I can confirm this issue with the HATHOR admin template.

There is no problem with the ISIS admin template<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11125">issues.joomla.org/joomla-cms/11125</a>.</sub>

**Comment by andrepereiradasilva** [comment]
Please test https://github.com/joomla/joomla-cms/pull/11130

**Comment by brianteeman** [comment]
Closed as we have a pr
