### ISSUE TITLE
Это просто космос Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by inverser-pro** [joomla/joomla-cms#11123]
Братаны, простите за многоматов, но это просто космос!

1. Вы заебали блядь выкладывать в UpDatePackages файлы, которые нахуй не надо обновлять. Долбоебы. Если вы блядь изменяете какой-то файл для обновления, то запишите себе в список, а потом просто этот файл добавьте в пакет обновления!
2. Пиздец я злой на этих уебков, которые делают все через жопу, как им удобно и похуй, что 3 млн пользователей будут ебаться потом пол дня, чтобы обновить никому нахуй ненужные блядь функции.
3. Нахуя вы столько комментариев оставляете в коде. Пиздец. Если удалить все комментарии, то блядь она будет весить в два раза меньше. Выкладывайте код без комментариев. Блядь каким надо быть уебаном, чтобы не понять, что написано. Делайте две версии с комментариями кода и без. Кому надо, чтобы сайт грузился на полтора часа дольше - пусть с комментариями качают эту хуйню!..
4. Uncaught RangeError: Maximum call stack size exceeded — эта ебучая хрень сегодня мне проебала пол дня.
 Парни, не расстраивайтесь, если вы пытаетесь добавть ебучее изображение в этом ебучем всплывающем окне мега медиа галереи стандартной, а она блядь НЕ ЗАРКЫАВЕТСЯ из-за ебучего куска говнокода, который хер вообще кто проверяет блядь!

Файл ::::::
/libraries/cms/html/behavior.php

В JOOMLA!!!! 3.6.0

имеет конченный код:
			var oldSqueezeBox = SqueezeBox.close;
			SqueezeBox.close = function () {
				oldSqueezeBox.apply(this, arguments);
				tinyMCE.activeEditor.windowManager.close();
			};
удалитего его впизду блядь и все будет работать - ебучее всплывающее окно (НЕУЖЕЛИ НЕЛЬЗЯ БЫЛО ПО-ДРУГОМУ СДЕЛАТЬ???) будет закрываться!
Благодарю всем создателям Joomla. Ебать я еще чуть подучусь и впизду я её видел. Написать свой код, конечно, это дохуя времени, но я его найду!
Блядь выблядки тупые амриканские.

--------
И еще блядь!

Вы блядь определитесь. Одни функции вы рассчитываете на IE8, другие блядь только на сорвеменные браузеры, в итоге получается дохуя дока, который блядь как всегда никому нахуй не нужен. Ботам с IE8-10 useragent похуй какой CSS вы используете.

Определитель блядь уже. Пиздесь!

**Comment by mbabker** [comment]
Based on the code snippets and what little bit of this translated into a "readable" format, I'm going to close this as a known issue with either other issues or pull requests already open depending on what aspect of this we're talking about.
