### ISSUE TITLE
Error on https://issues.joomla.org

### ISSUE THREAD

**Issue by inverser-pro** [joomla/joomla-cms#11124]
Я не знаю как хотите - переводите сообщение на свой гребаный английский
Блядь редактировать сообщение больше не могу (предущее) ошибка выскакивает блядь я заебаляся уже с вами
![dfsg](http://f.usemind.org/2016-07-14_174901.jpg "сука заебали своими полями для ввода")

**Comment by mbabker** [comment]
Report issues (in English and preferably without the profanity) regarding the issue tracker at https://github.com/joomla/jissues
