### ISSUE TITLE
Clear the cache! 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#11133]
#### Steps to reproduce the issue

Upgrade Joomla - dont clear cache - blame Joomla for being crap 

#### Expected result

Joomla works 

#### Actual result

Joomla doesnt work 

#### System information (as much as possible)

Caching enabled, browsers cache... 

#### Additional comments

 - TODO: Implement a "Now you have upgraded CLEAR YOUR DAMN CACHE! ALL CACHES! EVERYWHERE! type notice thats in big red letters about 100px high and with a massive claxon sound going off at full volume 

 - TODO investigate better cache busting techniques

**Comment by andrepereiradasilva** [comment]
See https://github.com/joomla/joomla-cms/issues/9638
