### ISSUE TITLE
Error displaying the error page: Invalid JDocument Class: Invalid JDocument Class

### ISSUE THREAD

**Issue by Mienography** [joomla/joomla-cms#11135]
#### Steps to reproduce the issue
You can simply go to my site www.i2bad.com and it immediately comes up. It also happens on the back-end as well www.i2bad.com/administrator

#### Expected result
When i go to my site i expect to see the home page

#### Actual result
When i go to the site i immediately get the following error. Error displaying the error page: Invalid JDocument Class: Invalid JDocument Class

#### System information (as much as possible)
I am using joomla with a template called Eventum from joomshaper

#### Additional comments
I need as much help as possible i am clueless on what my next steps should be.

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.joomla.org
