### ISSUE TITLE
Add versioning to custom html modules

### ISSUE THREAD

**Issue by photodude** [joomla/joomla-cms#11136]
#### Steps to reproduce the issue

with content versioning on,

1. create a custom HTML module (save/close)
2. edit custom HTML module (save close)

the pervious version should be maintained in the content history, but no version history is maintained

#### Expected result

Version history should by maintained for custom HTML modules

#### Actual result

no version history is maintained

#### Additional comments

custom HTML modules are very much like articles, and some site owners use custom HTML modules like micro content used through out a site. These same site owners may either desire to keep a content history or are required to keep such a history for corporate or regalatory reasons.

**Comment by brianteeman** [comment]
I dont remember why but this request was denied previously https://github.com/joomla/joomla-cms/issues/7019#issuecomment-217729101<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11136">issues.joomla.org/joomla-cms/11136</a>.</sub>

**Comment by photodude** [comment]
@brianteeman could the reason be somewhere on Gilp?

If we can't find a Justification for why this request was previously denied, I suggest we move it to a RFC.

**Comment by brianteeman** [comment]
On 15 Jul 2016 8:53 p.m., "Walt Sorensen" <notifications@github.com> wrote:
>
> @brianteeman could the reason be somewhere on Gilp?
>

Unfortunately not it was a decision made at the cleanup sprint

**Comment by chrisdavenport** [comment]
@photodude I don't recall the reason either (and I was there) but I doubt it was a final "no way, ever" kind of thing, so if you would like to think through the technical and architectural issues and produce an RFC it will certainly be considered.

**Comment by mbabker** [comment]
For one you'd basically have to version all modules or hack the UCM data
structure in a way that it can work with non-component type data.  That's a
pretty big wall to get over when dealing with it.

**Comment by photodude** [comment]
Thanks @chrisdavenport, I'll consider writing up some technical and architectural solutions. 

@mbabker I agree that UCM structure is a big wall to deal with. IMO Modules should be versionable by type, and only if the module is set up to support versioning. 

For the time being my efforts are going to be focused on the [PHPCS 2.x Coding Standards](https://github.com/joomla/coding-standards/pull/109) and possibly the [HHVM testing](https://github.com/joomla/joomla-cms/issues/10220) for some time. I'll definitely come back to this at some point but it's lower on my consideration list.

**Comment by brianteeman** [comment]
I remember now that the reasoning was to do with the issues with UCM and with the roadmap for page builder which would possibly make this need redundant<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11136">issues.joomla.org/joomla-cms/11136</a>.</sub>

**Comment by photodude** [comment]
page builder is on the Joomla 4 roadmap right?

I still think this maybe worth pursuing, pending the implementation of page builder.

**Comment by brianteeman** [comment]
If you want to go ahead and write some code then fine I'm certainly not going to stop you. I am going to close this now and if/when you create some code that will be a new PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11136">issues.joomla.org/joomla-cms/11136</a>.</sub>
