### ISSUE TITLE
"Call to a member function addRecipient() on boolean" when create new user

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#11131]
#### Steps to reproduce the issue
After updating Joomla to 3.6.0 I started to create a new user. As a result, I get this error message:

> An error has occurred.
> 0 Call to a member function addRecipient() on boolean

It is happens with PHP 7.0.8.
I turn sever on PHP 5.6 and repeat creating new user. As a result, I get another error:

> The mydomain.com page isn’t working
> mydomain.com is currently unable to handle this request.
> HTTP ERROR 500

But all users have been created.

#### Expected result
There shouldn't be  such error message.

#### Actual result
Described above.

#### System information (as much as possible)
PHP Built On	Linux mydomain.com 4.4.13-1-pve #1 SMP Tue Jun 28 10:16:33 CEST 2016 x86_64
Database Version	5.5.47-MariaDB
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.23
Web Server	Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/5.4.45
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by andrepereiradasilva** [comment]
tried with php 7.0.8 and can't reproduce the issue.

**Comment by mbabker** [comment]
It's a result of https://github.com/joomla/joomla-cms/pull/9881

You'll only get that type of error if you feed invalid data into JMail.  In 3.5.1 it was throwing Exceptions, 3.6 tries to catch them in JMail and consistently return boolean false on an error case versus blissfully discarding any errors.

Long and short, validate your email addresses are valid before calling any method in JMail or PHPMailer which accepts an email address as an argument.

**Comment by PhilETaylor** [comment]
How have you configured your mail settings in Joomla Global Config - exactly - without sending the passwords here.

**Comment by Sulpher** [comment]
@mbabker @PhilETaylor thanks for the tip which way to go. I just been checked out Mail Settings in Global Configuration and found it's unable to save settings. Browser console shows this:

> JQMIGRATE: Migrate is installed, version 1.4.1
> 2sendtestmail.js:6 Uncaught ReferenceError: sendtestmail_url is not defined

Sorry for reporting about another issue(?) here.

**Comment by Sulpher** [comment]
> I just been checked out Mail Settings in Global Configuration and found it's unable to save settings
Misprinted. I unable to send test email.

**Comment by andrepereiradasilva** [comment]
Clear Browser cache (Ctrl+F5) and then save

**Comment by Sulpher** [comment]
Ahh..... My fault! Sending test mail works now after cache clearing. :-)

**Comment by PhilETaylor** [comment]
So this can be closed then ?

**Comment by brianteeman** [comment]
Closed
