### ISSUE TITLE
insert Intro Image on joomla 3.6 get uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by abmousavi** [joomla/joomla-cms#11142]
jModalClose = function () {
				oldClose.apply(this, arguments);
				tinyMCE.activeEditor.windowManager.close();
			};

**Comment by ggppdk** [comment]
Duplicate to:
#11137

**Comment by ggppdk** [comment]
My mistake, it must be different case

@abmousavi  did you click browser cache ?
Click CTRL-F5 or similar in your browser

**Comment by dgt41** [comment]
please test #11097

**Comment by brianteeman** [comment]
I am closing this as there has been no response and it would appear to have been fixed elsewhere as mentioned above. It is still an issue with the current staging release it can always be reopened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11142">issues.joomla.org/joomla-cms/11142</a>.</sub>
