### ISSUE TITLE
Module FrontEnd edit ACL

### ISSUE THREAD

**Issue by philbertphotos** [joomla/joomla-cms#11140]
#### Steps to reproduce the issue

Made a Security Group under Registered. Gave this group permission to EDIT/FrontEnd Edit a Module

#### Expected result

Supposed to display the module edit icon for that user on the FrontEnd

#### Actual result
Module Edit Icon does not exist yet I can edit module without issue via URL
Icon only shows up if I Globally set registered users editing ability makes me believe that it checks the CanEdit after the module loads.

**Comment by andrepereiradasilva** [comment]
i can't reproduce this on latest staging.

- Created a new user assigned to "Publisher" Group
- First test:
 - Changed Module options "Frontend Editing"permissions to "Allowed" for "Published" group
 - Result: User can edit all the modules on frontend 
- Second test:
 - Reset the Module options "Frontend Editing" to "Inhrited" for "Published" group
 - Changed a particular Module "Frontend Editing" permission to "Allowed" for "Published" group
 - Result: User can edit only that module on frontend

**Comment by philbertphotos** [comment]
I will do it on a CLEANED version of Joomla and update this ticket.

**Comment by philbertphotos** [comment]
Is it possible that the joomla Theme is the cause of this issue if so where do I look to fix it?

**Comment by philbertphotos** [comment]
Ok I tested "ProtoStart" and the ACL works fine but in YooEat it does not show the icon. What am I looking for in the Theme to fix this for default behavior?

**Comment by andrepereiradasilva** [comment]
Please use the forum (http://forum.joomla.org/) for issues in your environment. This is for issues with the software, not problems in your environment.

pinging @brianteeman

**Comment by brianteeman** [comment]
Closed - please use the forum or contact the maker of the template for support<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11140">issues.joomla.org/joomla-cms/11140</a>.</sub>
