### ISSUE TITLE
Two finder module make invalid HTML for W3C

### ISSUE THREAD

**Issue by SemaphoreOxalis** [joomla/joomla-cms#11155]
#### Steps to reproduce the issue
put 2 finders modules and test the page with W3C tester

#### Expected result
generate id and associate label must be unique

#### Actual result
id of form, input and label 'for' is always the same 

#### System information (as much as possible)
All versions of Joomla! I suppose ^^

#### Additional comments
we use frequently use 2 modules : one for desktop and hidden for tablet and phone and an other one for tablet and phone only for example (not a the same place in our templates)

**Comment by bertmert** [comment]
Could you please test PR https://github.com/joomla/joomla-cms/pull/11168

**Comment by brianteeman** [comment]
Close as we have a pr thanks

**Comment by SemaphoreOxalis** [comment]
Thanks fr that fix !
