### ISSUE TITLE
ACL Problem in Tags - User can create tags, even with the option disabled

### ISSUE THREAD

**Issue by avpninja** [joomla/joomla-cms#11154]
### Steps to reproduce the issue

Try with the user group **Author**

* Go to **System** > **Global Configuration** > **Tags** > **Permissions** Tab<br/>
Here change to **Denied** the option **Create**, please see the screenshot.<br/>

![screen shot 2016-07-16 at 08 55 42](https://issues.joomla.org/uploads/1/0ca81adfce25e30e6c25287df7513486.png)

<br/>
* In the front-end, if you access to the site with the Author account and you create a new article to send, in the Tab **Publishing** the user is still able to create and send successful completion of the article with the tags added.

* From here if you go to **Components** > **Tags**, you can see the new tags added.

### System information 

Tested in J3.5.1 
Tested in J3.6.0

* Joomla! Platform Version Joomla Platform 13.1.0
* Database versión 5.5.42
* PHP Version 5.5.22
* Web Server Apache/2.2.29

### Additional comments

Possible problem identified from [The Joomla! Forum](http://forum.joomla.org/viewtopic.php?f=719&t=928924).
Apologize ahead for any possible error, it's my first report here.

**Comment by andrepereiradasilva** [comment]
confirmed.

**Comment by andrepereiradasilva** [comment]
please test https://github.com/joomla/joomla-cms/pull/11211

**Comment by RonakParmar** [comment]
I have created a menu-item to submit an Article at front-end side, while creating an article at front-end site,  in "Publishing" tab I am only able to select existing tags in "Tags" field.
In above Test Instruction you have mentioned that "_create a new article to send, in the Tab Publishing the user is still able to create and send successful completion of the article with the tags added._" 
I am not able to create tag in new article creation. Please provide some more information to test the #11211 PR.

**Comment by brianteeman** [comment]
Closing as we have a PR for testing #11211
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11154">issues.joomla.org/joomla-cms/11154</a>.</sub>
