### ISSUE TITLE
Joomla Recaptcha Problem in custom registration page

### ISSUE THREAD

**Issue by shoaibrehmatburuj** [joomla/joomla-cms#11152]
Hi,
I am using the Joomla Recaptcha plugin API in my custom user registration page (my form is submitted to the joomla registration controller I didn't add user by my self). And I also have a system plugin which validate the captcha answer but the problem is if I have set the default captcha in joomla configuration or in the user registration settings then I always get the false in my system plugin as the answer of the captcha result.
#### Steps to reproduce the issue

code in my system plugin to check the answer of the recaptcha
$post = JRequest::get('post');

JPluginHelper::importPlugin('captcha');
if(JVERSION < 3)
$dispatcher = JDispatcher::getInstance();
else
$dispatcher = JEventDispatcher::getInstance();

$res = $dispatcher->trigger('onCheckAnswer',$post['recaptcha_response_field']);
if(!$res[0]){
$redirect = 1;
}

#### Expected result

true

#### Actual result

false

#### System information (as much as possible)

PHP Built On Linux dev1 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64
Database Version 5.7.12-0ubuntu1
Database Collation utf8_general_ci
Database Connection Collation utf8mb4_general_ci
PHP Version 5.6.22-3+donate.sury.org~xenial+1
Web Server Apache/2.4.18 (Ubuntu)
WebServer to PHP Interface apache2handler
Joomla! Version Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT
Joomla! Platform Version Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by brianteeman** [comment]
Sorry you didnt get a reply. Did you manage to resolve this?

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11152">issues.joomla.org/tracker/joomla-cms/11152</a>.</sub>
