### ISSUE TITLE
Installers don't work after update from 3.5 to 3.6 all 

### ISSUE THREAD

**Issue by proweb** [joomla/joomla-cms#11156]
#### Steps to reproduce the issue
1) Download Update pakage - [Joomla_3.6.0-Stable-Update_Package.zip](https://github.com/joomla/joomla-cms/releases/download/3.6.0/Joomla_3.6.0-Stable-Update_Package.zip "")

2) Extract package to folder on local

3) Transfer files by ftp(by Filezilla) to Joomla site with 3.5.1 version

4) Goes to "System information" - watching version- it's must be 3.6.0(after transfer all files from update package)
![](http://image.prntscr.com/image/c488926ad57f45fb8f37357945a56c76.png "System Information screen after FTP-update")

5)Goes to "Manage" - "Install" - and we have no one Installers except "Install from Web"

![](http://image.prntscr.com/image/49e029baa5584c0d826df99fc97d6208.png "Only one Installer")

6) In Plugin manager we also see only "Install from Web" after upgrade from 3.5 to 3.6.0

![](http://image.prntscr.com/image/e34d0469537747eeb752a4ee72b9bb4e.png "")

#### Expected result
Expected what all installers would be work after upgrade from Joomla 3.5.1 to 3.6.0

#### System information (as much as possible)
[systeminfo-2016-07-16T19-04-24+03-00.txt](https://issues.joomla.org/uploads/1/2a79f84e005e7bfcf66def89e77dcb1d.txt)

**Comment by brianteeman** [comment]
That is expected behaviour because you have not upgraded Joomla with a
supported method.

**Comment by zero-24** [comment]
Please go and discover the new Plugins. The problem is that your upgrade faild to install them.

- Acces the menu item: Joomla -> Extensions -> Manage -> Discover
- Select all discovered items (click their checkbox)
- Click on the Install button
- You should now be able to go back to your Extensions -> Manage -> Install page (see previous screenshot) and click on the Plugin Manager link (in the yellow message box) to find and enable the previously not installed plugins.

**Comment by zero-24** [comment]
Here is the doc page: https://docs.joomla.org/J3.x:Missing_Installer_Tabs

**Comment by ggppdk** [comment]
Please note that if you upgrade by extracting J3.6.0 package:

Then clicking
Extensions/Installer/Database/Fix 

- will only run the database schema-changing queries our of: 
administrator\components\com_admin\sql\updates\

that means that only "ALTER" queries are executed

e.g. **if you try to install more languages you will see that none is listed**
you will need to run manually the queries of:
administrator\components\com_admin\sql\updates\3.6.0.*.sql

- do not try to run the queries that create the installer plugins, if you have already clicked "discover" and install in plugin manager
- do not try to run the ALTER queries if you already clicked "Fix" Database
