### ISSUE TITLE
Create new Category on the fly is heavily broken

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#11162]
The new feature implemented here is heavily broken: https://github.com/joomla/joomla-cms/pull/8623

There are several issues:

1. There is no ACL check (see from @brianteeman: https://github.com/joomla/joomla-cms/pull/8623#issuecomment-163159207 and from @ggppdk: https://github.com/joomla/joomla-cms/pull/8623#issuecomment-207819082)
  - Create a new user with "manager" rights
  - Remove the "Create" permission for managers in com_content
  - => User can still create "categories on the fly"
2. If you cannot create new categories in the way described above, you run into the next bug: @ggppdk mentioned, that the article was assigned to the "ROOT" category. The reason is very easy:
   - you edit the article with ID 1.
  - https://github.com/joomla/joomla-cms/pull/8623/files#diff-9b292088b08fa3a892af0f75631302aeR179 => Here the model call does not ignore the request (parameter), so the category model takes the ID from the $_REQUEST (https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_categories/models/category.php#L145).
  - the returned ID is the ROOT ID.
3. Ofc this works with every category which has the same ID as the article...There is also a special case: the category title with the same ID as the articleID will be updated to the name of the "new category" we wanted to create
4. The category selection breaks on several combinations
  - if there is no category yet, you cannot create one
  - ...

Solutions:
1. Add proper ACL checks(!!!)
2. Add proper cleaning of request variables (ignore_request e.g.)
3. Add proper validation of request variables
4. Fix bug in select dropdown

@pe7er @wilsonge

**Comment by ggppdk** [comment]
I replied twice about proper ACL check missing, and then i got no response
- then i saw it getting merged 

But i understand now that sometimes, people are busy, to read all the comments , especially when something is marked already RTC
- **my fault, that i did not do the proper thing**, i should have posted a test-fail response , to alert people to read my comment

**Comment by ggppdk** [comment]
I see what happend now, i had replied to a PR that closed / merged already !, no wonder that most people just passed it without reading my comment

**Comment by izharaazmi** [comment]
IMO, we should consider for once reusing the categories view itself in a iframe modal to choose or create categories. The button can be added to the input field to trigger the modal.

![image](https://cloud.githubusercontent.com/assets/6706189/16914101/2b54e616-4d0d-11e6-9f4b-6c7d4063bd0e.png)

This way the ACL, parent category etc will be handled by com_categories implicitly. However, I understand that what I am saying is not same as on-the-fly. 

If this is acceptable, I can submit a PR myself.

**Comment by michael-wdd** [comment]
On a very plain install of J3.6 this does not work

When saving the new category is not created and the item is assigned to category "ROOT".

**Comment by JoshuaLewis** [comment]
@izharaazmi I love the idea, however it won't feel as on the fly. So instead I suggest having the current method but having a ACL button appear below when a new category is added so that those who want to configure the ACL can do so while not slowing down those who are content with the current setup.

**Comment by bembelimen** [comment]
> So instead I suggest having the current method but having a ACL button appear below when a new category is added

Again: the problem is NOT, that there is no ACL for the new category, the problem is, that the new function is broken and ignores the global category ACL...a Privilege Escalation Vulnerability

**Comment by izharaazmi** [comment]
If some of us thinks it would be acceptable to have little less than "on
the fly" then I'd do the PR with my 2nd approach above. Opinions please!

**Comment by JoshuaLewis** [comment]
@izharaazmi I would support the idea. However I do wonder about the "Refresh" button, is there a way to avoid adding that?

**Comment by dgt41** [comment]
@JoshuaLewis @izharaazmi yup listen for `change` event on the select and do a re-initialization, something like: https://github.com/joomla/joomla-cms/pull/11040

**Comment by izharaazmi** [comment]
@dgt41 As in #11040 we have a "position" dropdown to listen to, and act on the "other modules" dropdown refresh thing.
Here I don't see such a thing that we can listen to. [New] opens a modal to "category.add" page, that after save doesn't communicate so to the actual page (better if it did), hence the user must do some trigger to fetch the updated list of categories. 
How do you suggest this to go around?

**Comment by bertmert** [comment]
I would prefer the PR of @izharaazmi instead of creating new category "on the fly" because it would also solve annoying issues like this one https://github.com/joomla/joomla-cms/issues/11224

**Comment by dgt41** [comment]
@izharaazmi it's not a one to one exact solution but the modal close could trigger the event (or a hidden button) and then the same ajax call as the other PR will refresh the select element. I just shared that as the second part could be used (with the appropriate changes) here as well

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/pull/11244

Right this is the fix for the ACL Only - the most important part from a security perspective. Please test all the components. All the rest will need to be covered in separate PR's

**Comment by izharaazmi** [comment]
In fact I took the idea from 

![image](https://cloud.githubusercontent.com/assets/6706189/17053527/177b44b2-5020-11e6-952b-4de3a3a913e9.png)

And yes it has to be an ajax call anyway to fetch the updated list of categories. We just need to find the appropriate trigger for the call. IMO, modal close is okay but not the best one. And I think user should also have the choice to manually trigger the refresh.

**Comment by dgt41** [comment]
@izharaazmi you can also check the way modules update the infos in the menu edit page (but please lets use ajax here, as that one is way too messy javascript code)
![screen shot 2016-07-22 at 13 00 16](https://cloud.githubusercontent.com/assets/3889375/17053818/73fbad44-500c-11e6-9254-1b8c52aebc5c.png)

**Comment by izharaazmi** [comment]
Okay. Now I'll work on this this weekend. Hope a PR on or around Monday. 👍

**Comment by brianteeman** [comment]
Closing as we have #11244 and #11238 that address all three issues<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11162">issues.joomla.org/joomla-cms/11162</a>.</sub>

**Comment by bembelimen** [comment]
Hello @brianteeman the 4th point is still unresolved.

**Comment by brianteeman** [comment]
Missed that - reopening
How can you have a scenario without a single category?

**Comment by bembelimen** [comment]
Thanks,
if you have no article, you can delete all categories

**Comment by brianteeman** [comment]
Hi @bembelimen I am closing this. 
Point 4 isnt really related to the create categories on the fly feature at all. Its more fundamental than that - the category field is a required field and that is the issue not the categories on the fly feature. If you want to create a new issue to address that one specific scenario by all means do it but its certainly not a high priority to fix.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11162">issues.joomla.org/joomla-cms/11162</a>.</sub>
