### ISSUE TITLE
SSL/TLS Swtich Missleading needs renaming to just SSL

### ISSUE THREAD

**Issue by utilis** [joomla/joomla-cms#11177]
#### Steps to reproduce the issue
Install Joomla, Go to Global Configuration > Server Settings > Select SMTP 
Select SSL/TLS
Open configuration file, Check $smtpsecure = 'ssl'; 

#### Expected result
$smtpsecure = 'ssl'; 

#### Actual result
$smtpsecure = 'ssl'; 

#### System information (as much as possible)
Database Version	5.6.30
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.5.37
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.5.1 Stable [ Unicorn ] 05-April-2016 22:45 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

#### Additional comments
SSL/TLS Swtich Missleading needs renaming to just SSL

**Comment by andrepereiradasilva** [comment]
>SSL/TLS Swtich Missleading needs renaming to just SSL

that's not correct

- 'ssl' is a string used by PHP Mailer for SMTPS (with SSL or TLS protocol)
- 'tls' is a string used by PHP Mailer for SMTP+STARTTLS

You can check tooltip in "SMTP Security" field or/and see https://github.com/joomla/joomla-cms/pull/8520 for more info.

**Comment by brianteeman** [comment]
Closing as expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11177">issues.joomla.org/joomla-cms/11177</a>.</sub>
