### ISSUE TITLE
3.6.0 user registration & logout bug

### ISSUE THREAD

**Issue by chillside** [joomla/joomla-cms#11171]
#### Steps to reproduce the issue

in front or backand create new user -> field ID set 0 automaticly -> get error

#### Expected result

new user

#### Actual result

<pre>
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' 2)' at line 3 SQL=INSERT INTO `#__user_usergroup_map` (`user_id`,`group_id`) VALUES (, 2)
</pre>

#### System information (as much as possible)

Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Apache/2.4.10 (Unix)
PHP 7.0.8
mysql 5.7.12

#### Additional comments

+ if you login -  white page, logout - white page

**Comment by infograf768** [comment]
Can't reproduce here.

**Comment by widmann-it** [comment]
If the problem can also understand

**Comment by csthomas** [comment]
It may be:
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/table/user.php#L373

**Comment by csthomas** [comment]
But real problem is probably earlier:
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/table/user.php#L317

**Comment by csthomas** [comment]
@chillside
Can you change line 373 for a few seconds:
from
						->values($this->id . ', ' . $group);
to
						->values($this->id . ',, ' . $group);
 and test/try to add new user.
How it will look like the sql error/query?

**Comment by chillside** [comment]
@csthomas change 373 line

<pre>
Сохранить не удалось из-за ошибки: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', 2)' at line 3 SQL=INSERT INTO `#__user_usergroup_map` (`user_id`,`group_id`) VALUES (,, 2)
</pre>

**Comment by chillside** [comment]
UPD. User created with this error, but his User Group is empty. And if i try edit this user - all fields is empty..

**Comment by csthomas** [comment]
You have to check you #__users table. By phpMyadmin or similar. 
Try to find user id id=0.

**Comment by chillside** [comment]
user with id 0 found.. first row in #users table

**Comment by csthomas** [comment]
It may be mysql error.
Can you add row to #__users table manually. 
Add one row with random data, after success delete it.

**Comment by chillside** [comment]
add new row - user visible in admin panel and all fields ok on edit user page

**Comment by chillside** [comment]
<pre>
INSERT INTO `***_users` (`id`, `name`, `username`, `email`, `password`, `block`, `sendEmail`, `registerDate`, `lastvisitDate`, `activation`, `params`, `lastResetTime`, `resetCount`, `otpKey`, `otep`, `requireReset`) VALUES ('99999', 'name', 'username', 'ebala@ya.ru', '***********', '0', '0', '2016-07-18 00:00:00', '0000-00-00 00:00:00.000000', '', '', '0000-00-00 00:00:00.000000', '0', '', '', '0');
</pre>

**Comment by csthomas** [comment]
In Joomla Backend: 
Global Configuration->Server Database Setttings:
- check what value do you have at Database Type?
- try to change to other contains "mysql" text.

If that not help then it make take time to find a problem.

**Comment by chillside** [comment]
DBtype is MySQLi

if set MySQL (PDO):
<pre>
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' 2)' at line 3
</pre>

**Comment by csthomas** [comment]
Query which generate above error is suspicious.
Do you reversed this changed:
```
->values($this->id . ',, ' . $group);
```
If not do it.
And check again.

Back to mysqli.
* Check your plugins.  
Disable for a while all not standard from user/system group. 
May some plugin generate errors.

**Comment by csthomas** [comment]
I have forgotten to ask does a new added user by joomla has user id > 0?

**Comment by chillside** [comment]
in file /user.php#L317 i set default value

if i add user in admin user get ID 0 (visible in phpmyadmin), if add new row on phpmyadmin > id sets normal, from mysql query

**Comment by csthomas** [comment]
The other solution may be to replace libraries/joomla libraries/cms and libraries/legacy by fresh from
https://github.com/joomla/joomla-cms/releases/download/3.6.0/Joomla_3.6.0-Stable-Full_Package.zip

Copy libraries/ to libraries_old/
Then delete cms legacy and joomla directory from libraries/
Then copy from zip above directories to libraries/

**Comment by sovainfo** [comment]
Please use the forum to determine whether it is an issue with your environment or Joomla. Properly describe the issue here when it turns out to be an issue with Joomla!!

**Comment by chillside** [comment]
hmm..  what about "Reinstall Joomla core files" button in Joomal Update Page ?  Dont gives a positive result.. Now I'll try your variant

**Comment by chillside** [comment]
@sovainfo i have this problem after update Joomla to 3.6.0 version and post it here. 
I just want to find a solution..

**Comment by chillside** [comment]
lost AUTO_INCREMENT checkbox in #_users ID field. closed

**Comment by sovainfo** [comment]
So, use the proper channel for reporting issues! Again this is about Joomla! Software, not MySQL !

**Comment by Mindless999** [comment]
It looks like the update for the MySQL did not put the AUTO_INCREMENT to this table, because for some reason the ID also was not primary Key. I had this issue as well after upgrading Joomla to the latest version<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11171">issues.joomla.org/joomla-cms/11171</a>.</sub>
