### ISSUE TITLE
After 3.5.1 Update to 3.6 Module Edit (Specifically Module assignment) Not working properly

### ISSUE THREAD

**Issue by darrenalba** [joomla/joomla-cms#11170]
#### Steps to reproduce the issue
- Selected Module to update
- Select Menu  Assignment Tab
- Module Assignment : (already set to Only on the pages selected)
- Menu Selection : Select new Menu
- Tried Clicking Save and Save & Close 

#### Expected result
- It should update the module menu assignment and should not redirect to the Module Selection

#### Actual result
- They all redirect to Module homepage and the update isnt reflecting

#### System information (as much as possible)
- Current Tested Module is Custom HTML

**Comment by sovainfo** [comment]
Can't reproduce. Tried both j351 updated to j360 and clean j360.
System Information:
w10, apache 2.4.3 , php 5.4.7, mysql 5.5.27 
Learning Joomla demo data installed on j351-j360.
No demo data on j360

**Comment by dans1218** [comment]
I'm having the same issue.  Upgraded from 3.5.1 to 3.6 and can't assign modules to menu items.  The only way they appear is if I assign the module to show on all menu items.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11170">issues.joomla.org/joomla-cms/11170</a>.</sub>

**Comment by DavidBoggitt** [comment]
A bit of a long shot, but this is with the core and not Advanced Module Manager?

**Comment by andrepereiradasilva** [comment]
Can't reproduce.

**Comment by brianteeman** [comment]
Closing as this has not been replicated and no response from original poster<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11170">issues.joomla.org/joomla-cms/11170</a>.</sub>

**Comment by darrenalba** [comment]
I was only able to fix the issue by recreating the modules again. I think the issue is i have a lot of menu assignments to each modules.

Though i have followed the suggestion from brianteeman on updating the max_input_vars.. i still have the issue.
