### ISSUE TITLE
Login form is always displayed after cookie login

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#11182]
#### Steps to reproduce the issue
Login with 'Remember Me' enabled.
Delete frontend session cookie and leave remember-me cookie only to simulate session cookie expiration.
Load any page, see that user was actually auto-logged in: user in session is OK (see in debug console), user is displayed in backend logged-in users module etc.

Now visit Users->Login Form menu item, see login form instead of Log Out button

#### Expected result
Users->Login Form should display Log Out button

#### Actual result
Users->Login Form should displays login form even though the user is logged in

**Comment by bertmert** [comment]
Not confirmed with current staging (=> 3.6.1)

**Comment by brianteeman** [comment]
@Denitz are you still having this issue? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11182">issues.joomla.org/joomla-cms/11182</a>.</sub>

**Comment by Denitz** [comment]
Can't reproduce anymore.
