### ISSUE TITLE
Joomla Admin - 3.3.6 - Featured Articles blank display

### ISSUE THREAD

**Issue by AdamNZ** [joomla/joomla-cms#11188]
#### Steps to reproduce the issue
Go to (Admin) Content/Articles
Click on the "Featured Articles" link in the LH menu,

#### Expected result
Listing of Featured Articles

#### Actual result
Blank page.

#### System information (as much as possible)
Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT 
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 
PHP Version 7.0.8
Linux us502.directrouter.com 2.6.32-604.30.3.lve1.3.63.el6.x86_64 #1 SMP Sun Sep 27 06:34:10 EDT 2015 x86_64
Database Version 	5.6.30
Database Collation 	latin1_swedish_ci
Database Connection Collation 	utf8mb4_general_ci
Web Server 	LiteSpeed
WebServer to PHP Interface 	litespeed 

#### Additional comments

**Comment by AdamNZ** [comment]
Sorry, folks - this appears to be a clash with CW Multicats (3.5.18). On uninstalling that plugin all appears to be OK in Admin.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11188">issues.joomla.org/joomla-cms/11188</a>.</sub>

**Comment by infograf768** [comment]
Please close the issue.

**Comment by AdamNZ** [comment]
Closed - thank you - and apologies.
