### ISSUE TITLE
Joomla admin update articles Articles Manager with image error

### ISSUE THREAD

**Issue by james817** [joomla/joomla-cms#11185]
#### Steps to reproduce the issue

When I updated the Article, the screen shown as below and the information cannot be updated.

#### Expected result

The article content should be updated

#### Actual result

Error page as attached

#### System information (as much as possible)

Joomla 3.3.6
Apache
FLEXIcontent v2.2.1
pkg_eventgallery_light_3_4_6
Chronoforms_V5.0.9_Component

**Comment by bertmert** [comment]
> Joomla 3.3.6

This is a completely outdated Joomla version. Current version is Joomla 3.6.0. Please ask in a forum if you use older versions than current one.

**Comment by DhavalTailored** [comment]
I agree it's old version, @james817 Further I am not able to find an attachment, Have you attached it?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11185">issues.joomla.org/joomla-cms/11185</a>.</sub>

**Comment by james817** [comment]
Sorry..forgot to click the start upload button. Here you are![screen shot 2016-07-19 at 00 19 33](https://issues.joomla.org/uploads/1/3d61d01343cd86d13bb95538849ed098.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11185">issues.joomla.org/joomla-cms/11185</a>.</sub>

**Comment by DhavalTailored** [comment]
@james817 this doesn't look like joomla error, Are you trying to update joomla content article from backend? If yes then this error should be thrown by some third party plugin<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11185">issues.joomla.org/joomla-cms/11185</a>.</sub>

**Comment by james817** [comment]
yes, we are trying to update joomla content article through FLEXI content component.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11185">issues.joomla.org/joomla-cms/11185</a>.</sub>

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11185">issues.joomla.org/joomla-cms/11185</a>

**Comment by infograf768** [comment]
Closing as not a Joomla issue.

Joomla 3.3.6 is obsolete.

Last version of Flexicontent is 3.0.12

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11185">issues.joomla.org/joomla-cms/11185</a>.</sub>

**Comment by ggppdk** [comment]
Your version is very outdated and not supported
- you can ask for support in the relevant software forum if you are willing to upgrade your version, and not here
