### ISSUE TITLE
Language switch stocks in one language

### ISSUE THREAD

**Issue by boschmaHH** [joomla/joomla-cms#11181]
#### Steps to reproduce the issue
- Install fresh Joomla 3.6
- Install Sample Data = No
- Extra step: Install 1 language (in my case 'German DE')
- Activate the multilingual feature = Yes
- Install localised content = Yes
- Enable the language code plugin = No
- Default Administrator language = German
- Default Site language = German
- Finish install

- Open BE
- Global Configuration - SEO Settings:
-- Search Engine Friendly URLs = Yes
-- Use URL Rewriting = Yes
-- Adds Suffix to URL = Yes
- Enable .htaccess
- Edit Plugin: System - Language Filter - set 'Remove URL Language Code' = Yes

- Call FE
- in my case 'German' site is open
- switch to EN - works fine
- switch to DE - works fine
- switch to EN - works fine
- switch to DE - doesn't work!

#### Expected result
- switching the language on start-items should work all the time

#### Actual result
- switching the language on start-items doesn't work after 4th klick to switch

#### System information (as much as possible)
- multiple host / multiple PHP (5.6 & 7)
- multiple MySQL and MySQLi

#### Additional comments
Site still stays in EN, even if the URL is cleaned up and cache is reset.
I only can recall the DE-site (default language) when I quit the browser (ending cookie?).
Could it be a cookie-thing?
This occours most likely since update to 3.6.

!!! Courios: This occurs on MAC on FireFox, GoogleChrome, on PC as well on FireFox and IE,
but NOT on MAC Safari .... - On MAC Safari it is still working as it should do.

#### Workaround
Set within the Plugin 'System - Language Filter' -> 'Remove URL Language Code' = No

**Comment by ggppdk** [comment]
Yes, it is a confirm bug and which has already examined throughly

a fix has already been made and already included for J3.6.1
#11159
Fixed in:
#11161

**Comment by roland-d** [comment]
@boschmaHH Thank you for your report. Closing this as a fix is already in place.
