### ISSUE TITLE
Tiny MCE link to menu items or media library

### ISSUE THREAD

**Issue by pnkr** [joomla/joomla-cms#11191]
#### Steps to reproduce the issue
Open a new article and press the add link![Add Link Icon](http://www.copyist.gr/images/addlink.jpg "Add Link") button in the TinyMCE editor.

#### Expected result
The window to add link should have an extra option to select a menu item from any menu from the website or to select an item from the media library of the website.

#### Actual result

At this moment, the windows opens
![link pop up](http://www.copyist.gr/images/link-popup.jpg "Add Link")
and the user must type the link. This may lead to mistakes most of the times (especially if the user is not familiar with it). But even if the user has experience, trying to link internal content (menus etc) to the article is frustrating because the user must memorize the url and type it.

**Comment by infograf768** [comment]
You are asking here for a new feature as TinyMCE per default does not allow this customization.

**Comment by dgt41** [comment]
Part of what you asking for is already implemented with the buttons image and article, the missing one is menu's and that can be done as an XTD button

**Comment by infograf768** [comment]
@dgt41 
Would be nice btw to create such a new XTD

**Comment by cdekok** [comment]
Would be nice to add a link to a menu item and from the media manager in the same way JCE does this.

**Comment by brianteeman** [comment]
I am closing this as we now have an editor button to create the menu links you wanted. This will be in Joomla 3.7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11191">issues.joomla.org/joomla-cms/11191</a>.</sub>
