### ISSUE TITLE
TinyMCE wrong selector on init()

### ISSUE THREAD

**Issue by OctavianC** [joomla/joomla-cms#11190]
#### Steps to reproduce the issue
- Set TinyMCE as your default Editor
- Run the following code:
```php
$editor = JFactory::getEditor();
echo $editor->display( 'some[name]', '', '100%' , '20%' , '100' , '10' );
```

#### Expected result
The WYSIWYG TinyMCE editor shows up.

#### Actual result
`<textarea>` shows up, clicking on Toggle Editor will turn it into the WYSIWYG editor.

#### System information (as much as possible)
Joomla! 3.6.0

#### Additional comments
Found the resolution, will provide a PR as soon as possible.

**Comment by dgt41** [comment]
@OctavianC your code will not work, let me explain:
tinymce display needs an id:
(plugins/editors/tinymce/tinymce.php:121)
```php

	public function onDisplay($name, $content, $width, $height, $col, $row, $buttons = true, $id = null, $asset = null, $author = null)
```
If non is given then this code will be executed:
(plugins/editors/tinymce/tinymce.php:123)
```php
		if (empty($id))
		{
			$id = $name;
		}
```

and obviously an id with brackets won't be accepted

**Comment by OctavianC** [comment]
Worked before. Also, the `$id` is optional so why not clean it before using it? It shouldn't take more than a couple of lines.

**Comment by dgt41** [comment]
There was a change in tinMCE (joomla side): before the selector for tinMCE was a class `.mce-editable` and now is using the id check plugins/editors/tinymce/tinymce.php line 834

**Comment by dgt41** [comment]
This is tinyMCE limitation http://wordpress.stackexchange.com/questions/156309/wp-editor-not-displaying-tinymce-correctly-when-square-brackets-used-in-name

**Comment by OctavianC** [comment]
So, if code worked correctly on previous versions of Joomla!, then this is a B/C break. There's obviously a small oversight, because there is some filtering done to the `$id` but that variable never gets used.

The issue is NOT with TinyMCE, but with its initialization, because HTML ids are not sanitized. It's a small fix which I'll provide in a little while.

**Comment by dgt41** [comment]
NO! the code before was crap for multiple instances of tinyMCE in the same page, that was fixed with this change

**Comment by OctavianC** [comment]
I just love endless discussions without any arguments :)

**Comment by dgt41** [comment]
try this:
```php
		if (empty($id))
		{
			$id = $name;
			$id = str_replace('[', '__', $name);
			$id = str_repeat(']', '', $id);
		}
```

**Comment by brianteeman** [comment]
Closed as we have a PR for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11190">issues.joomla.org/joomla-cms/11190</a>.</sub>
