### ISSUE TITLE
Module is not being loaded in Article content

### ISSUE THREAD

**Issue by bhavikTailored** [joomla/joomla-cms#11194]
#### Steps to reproduce the issue
- Duplicate any existing module.
- Do not change title of duplicate module.
- Try to load it using Content - Load Module plugin in any article use syntax:{loadmodule mod_login,title of duplicated module}.
- Module is not loaded properly.

#### Expected result
- Module should load properly.

#### Actual result
- Module is not being loaded, instead of module there is only simple text.

#### System information (as much as possible)
Joomla 3.6.0

**Comment by brianteeman** [comment]
Please explain what you mean by " not loaded properly."<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11194">issues.joomla.org/joomla-cms/11194</a>.</sub>

**Comment by bhavikTailored** [comment]
What I have done to produce this issue was:
- Created a custom module "Test Module".
- Loaded in article using {loadmodule mod_custom} and the module was loaded properly.
- I have duplicated this module and have not changed duplicated module's title, so the module title was "Test Module (copy)".
- Trying to load this duplicate module in article using {loadmodule mod_custom,Test Module (copy)} syntax.
- This time, duplicated module was not loaded, instead of module there was simple text "{loadmodule mod_custom,Test Module(copy)}" .

Please see screen-dump.

![screen shot 2016-07-19 at 06 04 34](https://issues.joomla.org/uploads/1/6c5351d427f096a87bdce79409fd77c8.png)

![screen shot 2016-07-19 at 06 06 44](https://issues.joomla.org/uploads/1/c2b7af2085111c7f56dedf3234851df3.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11194">issues.joomla.org/joomla-cms/11194</a>.</sub>

**Comment by dgt41** [comment]
Shouldn't it be `{loadmodule mod_custom, "Test Module (copy)"} `

**Comment by chrisdavenport** [comment]
Does https://github.com/joomla/joomla-cms/pull/11065 fix it?

**Comment by bhavikTailored** [comment]
Thank you for your suggestion.

I have tried to as per your suggestion but still duplication module is not working because when we have add Module's title with "(" so problem is that.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11194">issues.joomla.org/joomla-cms/11194</a>.</sub>

**Comment by dgt41** [comment]
#11065 does solves this!

**Comment by bhavikTailored** [comment]
Sorry, I have noticed that I was not using staging version. I will close the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11194">issues.joomla.org/joomla-cms/11194</a>.</sub>
