### ISSUE TITLE
Language switch on home site does not work correctly

### ISSUE THREAD

**Issue by pixelneco** [joomla/joomla-cms#11197]
#### Steps to reproduce the issue

- make all necessary settings for multilanguage site (example: German, English); Menu, module etc.
- change the „System - Language Filter“ plugin setting „Remove URL Language Code“ to yes (German is the default site language)
- no site caching active

#### Expected result

switching between the languages 

#### Actual result

- i can switch language on homesite only once, from default german to english. it is not possible to change back
- after clearing browser cache, switching works again
- switch to english -> ok; switch back to language without language code (german) is not working -> have to clear browser cache again

#### System information (as much as possible)

- fresh Joomla 3.6 
- no extension added except Akeeba Backup

#### Additional comments

It only happens on the home site / starting site. For example on associated menu item like „about us“ to „über uns“ it works well. Also it is only a problem with the plugin setting „Remove URL Language Code: yes“. With the setting no, it is ok

Kind regards
pixelneco

**Comment by MATsxm** [comment]
Please see if it's the same as fixes that has already been made and included for J3.6.1
#11159
Fixed in:
#11161

**Comment by pixelneco** [comment]
Hi MATsxm,

sorry didn`t see that. Thx for fast reply! Closing this one

Kind regards
