### ISSUE TITLE
3.6 update produces ACL error for menu display

### ISSUE THREAD

**Issue by aschkenasy** [joomla/joomla-cms#11208]
#### Steps to reproduce the issue

1. Have a menu item that has at least two items, one with public access, one with any of the other (registered) access types. (I'll use registered for this example)
2. Have a login module that redirects to the homepage after logout.
3. Login as a registered user. (You'll see the restricted menu item)
4. Logout

#### Expected result
The registered access menu item should not be visible

#### Actual result
The registered access menu item remains visible until page refresh

#### System information (as much as possible)
updated 3.5.1 to 3.6

#### Additional comments
The login module redirect is actually not required to reproduce this but makes it even more compelling, since the redirect itself causes an inherent reload of the page.

**Comment by andrepereiradasilva** [comment]
i can't reproduce this on latest staging.
could you're problem be related to this? https://github.com/joomla/joomla-cms/pull/11093

**Comment by tomartailored** [comment]
I am agree with issue, i have tested it and faced the same<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11208">issues.joomla.org/joomla-cms/11208</a>.</sub>

**Comment by brianteeman** [comment]
@aschkenasy Please retest with staging as 3.6.0 was really busted for redirects on login/out<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11208">issues.joomla.org/joomla-cms/11208</a>.</sub>

**Comment by aschkenasy** [comment]
will do asap

**Comment by aschkenasy** [comment]
this has been resolved in 3.6.2
