### ISSUE TITLE
install language - no languages

### ISSUE THREAD

**Issue by adambako** [joomla/joomla-cms#11214]
#### Steps to reproduce the issue

i install demo package from yootheme.. its joomla 3.6.0. 
if i go to Extensions: Install Languages there are no languages.
i download joomla 3.6.0 full package from joomla.org and over-install it through backend. 
still cant install any language
i try discover
i try fix database
i clear all caches

#### Expected result

there should be a list of all languages

#### Actual result

list is empty

#### System information (as much as possible)

in attachment

**Comment by infograf768** [comment]
Do you get an error message?

The servers were out this morning early (europe time). They work fine now.

**Comment by adambako** [comment]
hi,
no errors.. even if i enable developer mode for reporting.. its just missing list of languages![screen shot 2016-07-20 at 05 00 44](https://issues.joomla.org/uploads/1/807e71b43bd3393bb04250e6a4e84687.png)[systeminfo-2016-07-20T11-52-46+02-00.txt](https://issues.joomla.org/uploads/1/0dbdad3bc165707b9da1d371d84d3e29.txt)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11214">issues.joomla.org/joomla-cms/11214</a>.</sub>

**Comment by infograf768** [comment]
Please post a screenshot of the Update Sites page.

**Comment by adambako** [comment]
second shot is after hit "rebuild".. languages still dont show.


![screen shot 2016-07-20 at 05 07 06](https://issues.joomla.org/uploads/1/8fef857a373487065edbb5f08cddca7d.png)!

[screen shot 2016-07-20 at 05 07 06](https://issues.joomla.org/uploads/1/7e05766f120a9b617d5baacf55ba6290.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11214">issues.joomla.org/joomla-cms/11214</a>.</sub>

**Comment by adambako** [comment]
if it helps i can send you somewhere logins.. ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11214">issues.joomla.org/joomla-cms/11214</a>.</sub>

**Comment by infograf768** [comment]
The database is missing stuff... I am not astonished as you are using a demo...

It should contain at least this:

![screen shot 2016-07-20 at 12 27 21](https://cloud.githubusercontent.com/assets/869724/16983515/6833d38a-4e75-11e6-8969-2badcc88ad07.png)

**Comment by ggppdk** [comment]
This is the 3rd or 4th time i see this question coming up ?
- Language are not listed because package "English (United Kingdom)'" was not created

Missing languages, is 1 of the problems of joomla installations have 
- if upgraded by extracting J3.6.0 package files into the folder, ("non-supported upgrade method")

Clicking **Extensions/Installer/Database/Fix**
will only run the database schema-changing queries our of:
administrator\components\com_admin\sql\updates\
- that means that **only "ALTER" queries are executed**

**you will need to run manually the queries of**:
administrator/components/com_admin/sql/updates/3.6.0.*.sql

1. Do not try to run the queries that create the installer plugins, if you have already clicked "discover" and install in plugin manager
2. Do not try to run the ALTER queries if you already clicked "Fix" Database


To create the needed package run file: 3.6.0-2016-04-08.sql in phpmyadmin (replace # __ with you DB prefix)
```
-- Insert the missing en-GB package extension.
INSERT INTO `#__extensions` (`extension_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `custom_data`, `system_data`, `checked_out`, `checked_out_time`, `ordering`, `state`)
 VALUES (802, 'English (United Kingdom)', 'package', 'pkg_en-GB', '', 0, 1, 1, 1, '', '', '', '', 0, '0000-00-00 00:00:00', 0, 0);

-- Change update site extension id to the new extension.
```
UPDATE `#__update_sites_extensions`
SET `extension_id` = 802
WHERE `update_site_id` IN (
			SELECT `update_site_id`
			FROM `#__update_sites`
			WHERE `name` = 'Accredited Joomla! Translations'
			AND `type` = 'collection'
			)
AND `extension_id` = 600;
```

You may notify yootheme about this to fix their packages

**Comment by ggppdk** [comment]
@mbabker 
i am not expert on joomla upgrade, is the following possible

How much effort would it be to detect upgrade via file extraction ?
- compare DB version to version returned by ? JVersion ? 

and immediately ask backend user to run the sql queries by clicking a button or something ?
or at least some backend warning ?
or something else ?

Also 1 more FAQ article for none in "Install Languages" ? like
https://docs.joomla.org/J3.x:Missing_Installer_Tabs

**Comment by andrepereiradasilva** [comment]
Again, manual upgrade method is only a valid upgrade method if you run @mbabker post upgrade script immediatly after (See https://gist.github.com/mbabker/d7bfb4e1e2fbc6b7815a733607f89281).

Among other things, a manual update does not runs the querys in sql folder (see https://github.com/joomla/joomla-cms/tree/staging/administrator/components/com_admin/sql/updates/mysql)

Yes, you can fix database schema changes with the Database -> Fix later, but the Database -> Fix will not run, for instance, the UPDATE/INSERT sql syntax and so you will have issues like this.

**Comment by adambako** [comment]
ok.. so the issue comes from joomla demo package from yootheme? they use wrong method to upgrade to j3.6.0.?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11214">issues.joomla.org/joomla-cms/11214</a>.</sub>

**Comment by ggppdk** [comment]
@adambako 
Most probably yes,

If you have not run the queries yet, you can check it like this:
- if "English" Language package is missing then "Install languages" will not be listed

![package_en](https://cloud.githubusercontent.com/assets/5092940/16984675/2faeb016-4e84-11e6-8a51-2c2883363f86.png)

**Comment by adambako** [comment]
ok.. thanks you guys.
@ggppdk your query fix my issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11214">issues.joomla.org/joomla-cms/11214</a>.</sub>

**Comment by brianteeman** [comment]
Closed as not an issue in the Joomla core<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11214">issues.joomla.org/joomla-cms/11214</a>.</sub>

**Comment by sitte** [comment]
I manually added records to database but no result (there was update server but installation wasn't successful). Solution was to find and install language package from repository: https://community.joomla.org/translations/joomla-3-translations.html
