### ISSUE TITLE
Possible nested form in com_joomlaupdate default view

### ISSUE THREAD

**Issue by nppsbh** [joomla/joomla-cms#11222]
I think there are nested forms inside com_joomlaupdate default view, getting validation error on https://validator.w3.org/ or just check HTML source code of the page. Already added my solution #11232 

In the file administrator/components/com_joomlaupdate/views/default/tmpl/default.php

line 37~40
`<?php if ($this->showUploadAndUpdate) : ?>`
`<?php echo JHtml::_('bootstrap.startTabSet', 'joomlaupdate-tabs', array('active' => 'online-update')); ?>`
`<?php echo JHtml::_('bootstrap.addTab', 'joomlaupdate-tabs', 'online-update', JText::_('COM_JOOMLAUPDATE_VIEW_DEFAULT_TAB_ONLINE')); ?>`
`<?php endif; ?>`

think should be between line 34 ~ 35
`<div id="joomlaupdate-wrapper">`
 `// think should be placed here`
 `<form enctype="multipart/form-data" action="index.php" method="post" id="adminForm" class="form-horizontal">`

Thank you

**Comment by brianteeman** [comment]
Closed as we have a PR #11232<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11222">issues.joomla.org/joomla-cms/11222</a>.</sub>
