### ISSUE TITLE
[REGRESSION] Warning on edit "Uncategorized" categories

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#11228]
#### Steps to reproduce the issue

- Install latest staging with `None (Required for basic native multilingual site creation)` in the sample data.
- After install edit any "Uncategorised" category

#### Expected result

No warning

#### Actual result

![image](https://cloud.githubusercontent.com/assets/9630530/17021165/05661726-4f3e-11e6-96c7-debe6e9d05ab.png)

#### System information (as much as possible)

Latest staging

#### Additional comments

I have no user id 42 on the database.

The user id 42 is harcoded (??) in the install sql (https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/joomla.sql#L241-L247) but it has been like that for a while, so some new check is being done in latest staging.

**Comment by alikon** [comment]
can confirm 
something is going wrong with com_categories....

**Comment by andrepereiradasilva** [comment]
ok so it's really a regression

**Comment by mbabker** [comment]
The install app is supposed to reset the user ID on all records in the sample data.  That code wasn't changed or skipped in any way, was it?

**Comment by andrepereiradasilva** [comment]
don't know i have the problem in two different test sites.
can you check?

**Comment by mbabker** [comment]
I see nothing that's changed [InstallationModelDatabase::postInstallSampleData()](https://github.com/joomla/joomla-cms/blob/staging/installation/model/database.php#L772) in some time.  Honestly the most notable changes in the install apps were JavaScript tweaks and language strings.

**Comment by andrepereiradasilva** [comment]
really don't know. need more people to check if this.

is a simple test. just enter edit mode of any "Uncategorized" category in any component.

**Comment by infograf768** [comment]
I can't reproduce on anew install. My superUser gets id 618

**Comment by andrepereiradasilva** [comment]
ok starnge so probably it's mine and nicola broken install. will also check a new install

**Comment by andrepereiradasilva** [comment]
Forget my last comment

> I can't reproduce on anew install. My superUser gets id 618
The question is not what user do you get.
The question is the categories named "Uncategorized" have in the database that they were created with user id 42 and them we get that error editing them!

Just tested in clean staging without any sample/test data and i get the user id 42 as the user who created those categories and get the warning when trying to edit the category.

IMO this is a regression.

**Comment by infograf768** [comment]
I do not get the warning at all. In database 42 is replaced by 618.
Php 5.4.4

**Comment by infograf768** [comment]
used simple sample data

**Comment by andrepereiradasilva** [comment]
in #__categories table?

just to prove i'm not crazy
![image](https://cloud.githubusercontent.com/assets/9630530/17054783/f21c4532-5000-11e6-9910-2aad6a9c7450.png)

**Comment by infograf768** [comment]
I used sampledata.sql which does not change anyhting to categories vs joomla.sql
This may be useful to find out where is the culprit.

**Comment by andrepereiradasilva** [comment]
i used a clean staging install in a new database with new prefix and did not install any sample data, nor any multilanguage. Just next, next ... next.

**Comment by infograf768** [comment]
I know what you did and I get the same warning in that case.
What I try to say is that IF I install sampledata.sql instead of nothing, and although sampledata.sql does NOT contain any change to com_categories (which therefore means normally that only the joomla.sql records are used for these), then I do not get the issue.

>This may be useful to find out where is the culprit.

**Comment by andrepereiradasilva** [comment]
You're right, if you select "Default English (GB) Sample Data" it works fine, the id gets updated.

But if you select "None (Required for basic native multilingual site creation)" the id doesn't get updated!

Please confirm you have the same issue.

**Comment by infograf768** [comment]
done above :smiley:

**Comment by andrepereiradasilva** [comment]
so do you agree this is a regression?

**Comment by infograf768** [comment]
Never tested before I must say. It should be solved indeed I guess.

**Comment by andrepereiradasilva** [comment]
i don't have this issue in alcean 3.5.1 so it's a regression IMO

**Comment by alikon** [comment]
Yes happens when you do a fresh install with multilingual

On 22 Jul 2016 12:55 pm, "infograf768" <notifications@github.com> wrote:

Never tested before I must say. It should be solved indeed I guess.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/joomla/joomla-cms/issues/11228#issuecomment-234515210>,
or mute the thread

**Comment by andrepereiradasilva** [comment]
yes, basicly all new installs multilanguage (or monolanguage without any sample data) get this issue.

**Comment by andrepereiradasilva** [comment]
i think the issue is `postInstallSampleData` https://github.com/joomla/joomla-cms/blob/staging/installation/model/database.php#L772 is not run if you don't install sample data.

which from logic perspective makes sense, but if you don't install sample data, some things need to be changed also...

in 3.5.1 the issue is there but there is no warning.
so it seems in latest staging a new warning is there (IMO correct) and this issue was previous masked because joomla didn't send a warning.

**Comment by andrepereiradasilva** [comment]
ok i found the issue check this https://github.com/andrepereiradasilva/joomla-cms/pull/58/files

**Comment by andrepereiradasilva** [comment]
please test https://github.com/joomla/joomla-cms/pull/11245
