### ISSUE TITLE
`showon` doesn't disable options

### ISSUE THREAD

**Issue by Vlasterx** [joomla/joomla-cms#11231]
#### Steps to reproduce the issue
I wanted to disable "Recommend to a friend" link in frontend and I just couldn't find the option to do it because it was enabled and hidden in the backend. This should be used with caution. 

![GIF](http://i.imgur.com/8GlyUCs.gif)

#### Expected result
All fields are disabled

#### Actual result
Only fields that are manually disabled are actually disabled and but all are hidden. This is bad from UX perspective.  

#### System information (as much as possible)
Joomla 3.6

#### Additional comments
It would be great to extend this feature with following options:
- *default* - do not change options
- `onEnable` - `default` / `value='1'` (change all values to `1` or some other value)
- `onDisable` - `default` / `value='0'` (change all values to `0` or some other value)

##### Example

`<field
name="bar"
type="text"
showon="foo:1"
onEnable="value:1"
onDisable="default"
/>`

**Comment by Vlasterx** [comment]
Or to simplify even more

- use default behavior if `onEnable` or `onDisable` are not present
- use this markup `onEnable="1"` and when button is turned on, all values of all options will be changed to `1`
- `onDisable` - same as `onEnable` but when main button is turned off.

**Comment by Devportobello** [comment]
Cross-posting: https://github.com/joomla/joomla-cms/issues/11126

**Comment by andrepereiradasilva** [comment]
IMO this is a bug.
Either the showon shouldn't be there or the frontend is rendering the link when it shouldn't (since Show icons is disabled).

**Comment by Bakual** [comment]
The `showon` shouldn't be there because the parameter "Show Icons" doesn't disable the links below, it just decides if the links should be shown as text or icons.

**Comment by brianteeman** [comment]
My bad pr i think. I'll do a fix

**Comment by brianteeman** [comment]
Closed as we have a PR that reverts the showon for this See #11233
