### ISSUE TITLE
Hide dropdown didn´t show a read background

### ISSUE THREAD

**Issue by BastianWie** [joomla/joomla-cms#11234]
#### Steps to reproduce the issue
Create a new contact in the administration panel, switch to display and change Show Category to hide.![screen shot 2016-07-21 at 13 06 06](https://issues.joomla.org/uploads/1/64914b8c4592e2e0f92d89702b411ba3.png)

#### Expected result
Would expect a red background

#### Actual result
Shows white background (see screenshot)

#### System information (as much as possible)
Joomla! 3.6.0  

#### Additional comments
Not sure if that is a real bug. However I would give it a red background as other hide options have also a red background.

**Comment by RonakParmar** [comment]
I am able to reproduce this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11234">issues.joomla.org/joomla-cms/11234</a>.</sub>

**Comment by gunjanpatel** [comment]
I am also able to reproduce it but chosen set `red` color based on `0` or `1` integer value. When show category has string as an option `<option value="hide">JHIDE</option>` so if needs to show hide in red here then have to change the same in frontend and it will be also B/C problem (not 100% sure) too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11234">issues.joomla.org/joomla-cms/11234</a>.</sub>

**Comment by gunjanpatel** [comment]
Set to "closed" on behalf of @gunjanpatel by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11234">issues.joomla.org/joomla-cms/11234</a>

**Comment by gunjanpatel** [comment]
Closing as we have PR for this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11234">issues.joomla.org/joomla-cms/11234</a>.</sub>
