### ISSUE TITLE
ReCaptcha V2.0 and Send eMail is overlapping in Beez Template

### ISSUE THREAD

**Issue by BastianWie** [joomla/joomla-cms#11236]
#### Steps to reproduce the issue
- Setup Joomla 3.6.0 Joomla
- Use Beez Template
- Configure a ReCaptcha V2.0
- Configure a Contact (with every Display Format = Sliders, Plain AND Tabs)
)
- Visit the Contact page

#### Expected result
ReCapture should not overlap the Send Email button 

#### Actual result
Send Email is overlapping the ReCaptcha (Checked with IE 11 and Firefox 47.x)

#### System information (as much as possible)
Joomla 3.6.0

![screen shot 2016-07-21 at 15 14 04](https://issues.joomla.org/uploads/1/42bca2fc2e25e84457a1829d822e1233.jpg)

**Comment by BastianWie** [comment]
Here is a screenshot which shows the issue with tabs![screen shot 2016-07-21 at 15 17 50](https://issues.joomla.org/uploads/1/98fb3482bd33f99f82b3d14e6eac700b.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11236">issues.joomla.org/joomla-cms/11236</a>.</sub>

**Comment by BastianWie** [comment]
Here is a screenshot with a plain design.![screen shot 2016-07-21 at 15 20 23](https://issues.joomla.org/uploads/1/c6aa653307828eefff9bf443e1a8a523.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11236">issues.joomla.org/joomla-cms/11236</a>.</sub>

**Comment by piotr-cz** [comment]
Confirmed, this should fix it:

```CSS
#jform_captcha {
    clear: both;
}
```

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #11424<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11236">issues.joomla.org/joomla-cms/11236</a>.</sub>
