### ISSUE TITLE
Blank homepage (404 / Component not found) after upgrading to 3.6.0

### ISSUE THREAD

**Issue by creativeprogramming** [joomla/joomla-cms#11240]
#### Steps to reproduce the issue

Upgraded to 3.6.0

#### Expected result

All working fine

#### Actual result

All is working fine, except the homepage that is the only page to show this error, no matter what component i select for it from the menu

#### System information (as much as possible)

This is the stack trace of the error i get in the logs

`Stack trace:`
`#0 /tuzzia/libraries/cms/application/site.php(193): JComponentHelper::renderComponent()`
`#1 /tuzzia/libraries/cms/application/site.php(232): JApplicationSite->dispatch()`
`#2 /tuzzia/libraries/cms/application/cms.php(257): JApplicationSite->doExecute()`
`#3 /tuzzia/index.php(...`

I upgraded from 3.4.x, php7 on ubuntu xenial

#### Additional comments

I use multi-language menu.

**Comment by gunjanpatel** [comment]
Can you please confirm that you have SEF enabled or not and have mod_rewrite enabled?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11240">issues.joomla.org/joomla-cms/11240</a>.</sub>

**Comment by creativeprogramming** [comment]
Of course i've SEF and URL rewrite enabled, a must for any production site i think, but I'm using nginx as server, so not mod_rewrite, but euquivalent nignx settings that even worked and still works fine for any url except the home one

**Comment by creativeprogramming** [comment]
Anyway I just tested to disable sef and rewrite and event at url

https://mysite.com/index.php?lang=it

that is the url i get for the home without SEF i get anyway the 404 error

maybe something went wrong with my upgrade? I did it with unzip and database fix, so please I ask other users to confirm if is a common issue or i did something wrong

**Comment by gunjanpatel** [comment]
Thanks for the info. 
https://docs.joomla.org/J3.x:Upgrading_from_Joomla_3.4.x_to_3.5 document will help you to upgrade from 3.4.x just in case if you haven't tried.

**Comment by brianteeman** [comment]
That method will not work for an upgrade.

Please use the forum for support

**Comment by brianteeman** [comment]
I meant unzip and fix will not work

**Comment by creativeprogramming** [comment]
@brianteeman are you kidding me? 

I firstly upgraded with auto-updater, but as i got this error i give it also a 'pass' with the unarchive to ensure all files are set up.

![image](https://cloud.githubusercontent.com/assets/954291/17056918/17931d3e-5017-11e6-8bee-bc7b8ea7ca5b.png)

that brings me to:

![image](https://cloud.githubusercontent.com/assets/954291/17056939/3c7d0718-5017-11e6-92eb-144eaef1ed42.png)
