### ISSUE TITLE
News Feed images

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#11270]
As can be seen in the screenshot there are two fields with identical names and descriptions for a news feed options
![tgps](https://cloud.githubusercontent.com/assets/1296369/17078432/459ff2d8-50f3-11e6-82d4-7292b56e06d5.png)

The code in https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_newsfeeds/config.xml#L103 seems to indicate that they are for the first and second images, or more accurately alternate images.

Can someone confirm if that is the case and then if needed I can either update the strngs or remove the second

**Comment by RonakParmar** [comment]
Yes, I can see two field having same label, description text and having same options.
I have checked this file https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_newsfeeds/config.xml#L103 and both fields have same label and description language variable,but name of fields are different.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11270">issues.joomla.org/joomla-cms/11270</a>.</sub>

**Comment by rdeutz** [comment]
It seems to me named wrong, one is for "image_first" and the other one is for "image_second".  Both params are used, I can't say if that makes any sense at all

**Comment by brianteeman** [comment]
Making sense is where I was struggling but if they are both used then I
will just fix the strings. Thanks for double checking.

**Comment by brianteeman** [comment]
Closed as we have a PR #11515
