### ISSUE TITLE
Warning: Invalid argument supplied for foreach() using SQL Server db

### ISSUE THREAD

**Issue by rudisten1** [joomla/joomla-cms#11278]
#### Steps to reproduce the issue
set php ini error_reporting = E_ALL
install joomla using a SQL Server db as the main database
go to "users - manage" 

#### Expected result
users managment console

#### Actual result
php warning as follow:

Warning: Invalid argument supplied for foreach() in C:\inetpub\wwwroot\joomla7sqlsrv\libraries\joomla\database\query\sqlsrv.php on line 394

#### System information (as much as possible)
php 7
sqlsrv extension 4.0 non thread safe
IIS 7
joomla 3.6
SQL Server 2014

**Comment by williamsandy** [comment]
This is because the JDatabaseQuerySqlsrv group function does not test if the $this->join array is empty before trying to use it.

**Comment by rudisten1** [comment]
And now? should we expect this to be fixed ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11278">issues.joomla.org/joomla-cms/11278</a>.</sub>

**Comment by pocketpc** [comment]
Similar to #11279, same mitigation, will probably fix at the same time. SQL Server is kind of a second-class citizen here since most Joomla installs are on MySQL, so it probably won't get fixed until I find some time to make a pull request.

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #11938
