### ISSUE TITLE
[Regression] Joomla 3.6 broke pagination

### ISSUE THREAD

**Issue by mattiaverga** [joomla/joomla-cms#11284]
#### Steps to reproduce the issue
After the update to Joomla 3.6 pagination of category blog view is broken.
For example, this page http://www.techfromthenet.it/Focus/ didn't show any pagination with Joomla 3.5, now it shows many duplicates of the same article, but in backend there aren't any duplicates.

#### System information (as much as possible)
See attached file

**Comment by mattiaverga** [comment]
[systeminfo-2016-07-24T10_35_56+02_00.txt](https://issues.joomla.org/uploads/1/a51bb6216c125453f88c433e2272cee7.txt)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11284">issues.joomla.org/joomla-cms/11284</a>.</sub>

**Comment by bertmert** [comment]
I don't think that this is a Joomla issue. Have a look at your pagination links:
`<a class="pagenav" href="/Focus/Page-2.html" title="2">2</a>`
against Joomla (SEF + Adds Suffix to URL) :
`<a class="pagenav" href="/article-category-blog.html?start=10" title="3">3</a>`
See
`....html?start=10`

So I think that's a wrong template override or something.

**Comment by mattiaverga** [comment]
I thought about that.
I set up two local copies of the site, one with a backup before the update (joomla 3.5.0) and one with the actual site (joomla 3.6.0). I've set the default Beez3 template on both. As you can see in screenshots, the old Joomla 3.5 doesn't have pagination, the new one has it.
The category only has 7 articles (they were 6 in the old backup) and category blog is set to display 2 main articles + 14 links, so in both cases it should not doing pagination.
![j3 5](https://cloud.githubusercontent.com/assets/17218209/17083383/b1fed0e6-519f-11e6-97b7-7c2f405bef5c.png)
![j3 6](https://cloud.githubusercontent.com/assets/17218209/17083384/b2048f86-519f-11e6-95b4-bd8a30ed8cee.png)

**Comment by mattiaverga** [comment]
I did some more testing: using a clean Joomla 3.6 installation, it seems that the pagination plugin doesn't take into account the number of links set on the page.
For example, if I set to display 2 main articles + 2 Intro articles + 2 links, the second page link has "?start=4" instead of "?start=6". If I change the number of main articles or intro articles, the link is changed properly, but if I change the number of links the "?start" parameter doesn't change.

**Comment by brianteeman** [comment]
The number of links has never been taken into account. That is not
something new and can be seen right back to Joomla 1.0

**Comment by jeckodevelopment** [comment]
@brianteeman i guess he would say that the "number of links" has been ignored ("take into account" is a wrong translation). 

@mattiaverga can you please explain where is the issue?

**Comment by mattiaverga** [comment]
@jeckodevelopment if you look in my comment#4 with Joomla 3.5.0 pagination is not showed. With Joomla 3.6.0 pagination is showed.
That page is set to display 2 main articles + 14 links. In that category I have only 9 articles (they were 8 in the backup taken with Joomla 3.5).

So with Joomla 3.5 I got only one page with 2 main articles + 6 links.
With Joomla 3.6 I now have the first page with 2 main + 7 links, a second page with "?limitstart=2" with 2 main (which were the first two links in the first page) + 5 links, and so on...

This happens also with the default Joomla template.
If number of links are intentionally not considered when building pagination, can someone point me to the code where I can modify this behavior?

**Comment by jeckodevelopment** [comment]
Did you change anything into the default Joomla! template? Overrides?

**Comment by mattiaverga** [comment]
Ok, I'm sorry, I see now that the different behavior was totally my error: in the backup with Joomla 3.5 pagination was NOT enabled... sorry again!

However I would like to customize that and make the limitstart parameter count also links... where should I look for that?

**Comment by jeckodevelopment** [comment]
I guess that this is not the right place to discuss this :)
Maybe you can open a dedicated topic on the foum.
I close this issue, re-open if needed.

**Comment by brianteeman** [comment]
You can't. The code does not support that.
