### ISSUE TITLE
Contacts List component Filter Field Show/ Hide not working!!

### ISSUE THREAD

**Issue by FC3D** [joomla/joomla-cms#11283]
#### Steps to reproduce the issue

Contacts list component Filter Field Show/ Hide not working!!
Components > Contacts > Options > List Layouts >  Filter Field 

#### Expected result

Hide the contacts list  Filter field 
if option is hide 
else
show

#### Actual result

even contacts list Filter field option is set to hide
but
contacts list Filter field is showing 

Joomla Version  3.6.0

**Comment by brianteeman** [comment]
Please check that you have the same setting (or use global) for the menu
item.

**Comment by tomartailored** [comment]
Please Explain the part "Expected result" in retail.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11283">issues.joomla.org/joomla-cms/11283</a>.</sub>

**Comment by tomartailored** [comment]
Detail*
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11283">issues.joomla.org/joomla-cms/11283</a>.</sub>

**Comment by JamalTailored** [comment]
@FC3D It's not an issue .

What I have done was:
 Created a menu item of contacts category.
 and the menu item options have first priority.

 So, what you have to do is, change menu item filter field option in "List Layout" tab, and check on front-end, filer works correct or not.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11283">issues.joomla.org/joomla-cms/11283</a>.</sub>

**Comment by brianteeman** [comment]
Closing as expected behaviour - you need to make sure the menu settings are correct<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11283">issues.joomla.org/joomla-cms/11283</a>.</sub>
