### ISSUE TITLE
Permissions JS create asset with parent id = 0

### ISSUE THREAD

**Issue by alex7r** [joomla/joomla-cms#11296]
#### Steps to reproduce the issue
If view named "learning_path" or "lpath"
and asset name used in JTable is `component.lp.id`

#### Expected result
I'd like to avoid issues with getting my site down every time I change permission

#### Actual result
`/media/system/js/permissions.min.js` searches for asset name `component.view.id` which results in `component.learning_path.id` instead of `component.lp.id`
and new asset record added to table with parent_id = 0

#### Additional comments
May be solution is allowing to manipulate with asset name via js, allowing to influence everything except the `component.` for security and extensions encapsulation reasons.
```JS
var asset_name_postfix_var = getUrlParam("view");
```
In /media/system/js/permissions.min.js use:
```JS
var asset_name = "component."+asset_name_postfix_var;
```

**Comment by alex7r** [comment]
# Temp solution
For those who might run into this issue here is solution for this kind of situation:
```JS
var initialgetUrlParam = getUrlParam;
getUrlParam = function(){
	if(arguments[0] == 'view'){
		return 'lp';
	}else{
		return initialgetUrlParam.apply(document, arguments);
	}
}
```
And may be
```JS
var initialGetElementById = document.getElementById;
document.getElementById = function(){
	if(arguments[0] == 'jform_title'){
		return initialGetElementById.apply(document, ['jform_c_title']);
	}else{
		return initialGetElementById.apply(document, arguments);
	}
}
```
If you have `c_title` for some reason instead of `title`.
But remember: having `anything_title` instead of `title` is a **BAD HABBIT**

**Comment by andrepereiradasilva** [comment]
IMHO, you're right. It's not correct to use the url parameters to determine the asset key.

unless i'm mistaken, it should use the `typeAlias` property of the component item model.

BTW in 3.6.0 there is no `/media/system/js/permissions.min.js` file. the files are:
- https://github.com/joomla/joomla-cms/blob/staging/media/system/js/permissions.js
- https://github.com/joomla/joomla-cms/blob/staging/media/system/js/permissions-uncompressed.js

**Comment by ggppdk** [comment]
1 . I am adding requirement in JS to have 'jform_title' a hidden empty field:
```
jform_title
```
- for forms that do no have, but you can take time to make a PR i promise to test it


2 . For the view naming issues i am manipulating the posted data ... when needed ... to work around it, i don't know if you would like to make a PR for this too, i will test too 


3 . Finally, about:
> and new asset record added to table with parent_id = 0

if 2 assets with parent_id = 0, are created then ACL no longer works, regardless of the permissions saving issues,
- there should be a check somewhere if the above happens for any reason , and e.g. delete all extra assets with parent_id = 0 and wrong name ? if you make a PR for this, i will test too

**Comment by mbabker** [comment]
> For requirement in JS to have 'jform_title', i am adding a hidden empty field:

Why?  Why is core creating hardcoded requirements to explicit form fields being present?  Why are our JavaScript APIs not open to have these things customized as needed?  We're creating a lot more JavaScript based integrations in core and we're making a lot of the same mistakes as exist with our PHP code, creating hardcoded requirements on certain conventions without introducing mechanisms to change those hardcoded values for scenarios that they don't exist in.

**Comment by brianteeman** [comment]
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed. 

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4
cc @zero-24
