### ISSUE TITLE
Com_redirect does not trash large numbers of items

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#11303]
#### Steps to reproduce the issue

Have several thousand redirects in listing.
choose view 100 ->select all ->trash = works
choose view ALL -> select trash -> trash = fails
choose "purge unpublished" = fail

#### Expected result
Listing cleared

#### Actual result
listing flickers and remains the same.

#### System information (as much as possible)
[systeminfo-2016-07-25T12-19-45-07-00.txt](https://github.com/joomla/joomla-cms/files/382304/systeminfo-2016-07-25T12-19-45-07-00.txt)

#### Additional comments
According to dash panel there was roughly 5800 items in the list.

**Comment by zero-24** [comment]
can you have a look into the PHP error log? As well as the setting max_input_vars in PHP?

**Comment by brianteeman** [comment]
I can see why delete all will fail for obvious php reasons but the purge
should work on a dB of all sizes

**Comment by roland-d** [comment]
I have tested this with almost 22,000 rows in the database. The Show all fails terribly of course as the browser can't handle it but the Purge unpublished took a second or two only. I don't see an issue with that button.

The Show all isn't really useful for any large list as such especially now we have the purge button.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11303">issues.joomla.org/joomla-cms/11303</a>.</sub>

**Comment by brianteeman** [comment]
That is exactly why I wrote the code for the purge button.

Its still uncertain why the purge failed on this site but as @n6rej hasnt replied to anyone I am closing this at this time
