### ISSUE TITLE
When you log off problems

### ISSUE THREAD

**Issue by widmann-it** [joomla/joomla-cms#11307]
#### Steps to reproduce the issue
Once you go to log off you will not be redirected to the desired page. There is a blank page.

#### System information (as much as possible)
PHP erstellt für 	Linux 2.6.32-042stab113.11 #1 SMP Fri Dec 18 17:32:04 MSK 2015 x86_64
Datenbankversion 	5.5.49-0ubuntu0.12.04.1
Datenbankzeichensatz 	utf8_general_ci
Datenbankverbindungszeichensatz 	utf8mb4_general_ci
PHP-Version 	7.0.9
Webserver 	Apache
PHP-Interface für den Webserver 	cgi-fcgi
Joomla!-Version 	Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT
Joomla!-Plattform-Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Browsererkennung 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by RonakParmar** [comment]
Please provide some more information to reproduce this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11307">issues.joomla.org/joomla-cms/11307</a>.</sub>

**Comment by RonakParmar** [comment]
May be this PR helps you #11227 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11307">issues.joomla.org/joomla-cms/11307</a>.</sub>

**Comment by brianteeman** [comment]
Thank you for reporting this it is already resolved with #11227
