### ISSUE TITLE
Upgrade from 2.5.28 to 3.6 fails on any site that was previously upgraded

### ISSUE THREAD

**Issue by maestroc** [joomla/joomla-cms#11305]
#### Steps to reproduce the issue
I have had the same thing occur with three different sites.  All were 2.5.14 up to 2.5.28.  I updated them all to 2.5.28 using the Joomla updater.  Uninstalled everything that wasn't core Joomla just to be safe, and then ran the 3.6 update via the updater.  

#### Expected result
Successful upgrade to 3.6

#### Actual result
In each case I received the same error as detailed in the forum post: http://forum.joomla.org/viewtopic.php?f=710&t=929251

#### System information (as much as possible)
Setting	Value
 
PHP Built On	Linux server1.silverdolphinsolutions.com 2.6.32-642.1.1.el6.x86_64 #1 SMP Tue May 31 21:57:07 UTC 2016 x86_64
Database Version	5.6.30
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.23
Web Server	Apache/2.4.18 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

#### Additional comments

I was eventually able to get the site mostly fixed and runing on 3.6 by following the steps shown in this forum post: http://forum.joomla.org/viewtopic.php?f=710&t=928848  however after following those steps I still have a back end control panel that only loads the text and not the template.  However if I click through any of those links the other back end pages load correctly.

**Comment by maestroc** [comment]
I should mention that I made a video of the upgrade process showing the process and the error:
http://www.straightarrowwebservices.com/joomlaupgrade.avi
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11305">issues.joomla.org/joomla-cms/11305</a>.</sub>

**Comment by zero-24** [comment]
Confirmed. It got fixed with 3.6.1 see: https://github.com/joomla/joomla-cms/pull/11282

**Comment by infograf768** [comment]
Let's close this I guess as it is solved in staging.

**Comment by roland-d** [comment]
I am going to close this as a fix is already present. Thanks all for your contribution.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11305">issues.joomla.org/joomla-cms/11305</a>.</sub>

**Comment by maestroc** [comment]
Does not seem to be fixed in 3.6.1 for the sites I have tried it on.  Still receiving same error during the upgrade.  Still breaking at the same place in the process...
