### ISSUE TITLE
Changing 'Default Access Level' in Global Config does not follow through to a new menu item

### ISSUE THREAD

**Issue by DavidBoggitt** [joomla/joomla-cms#11317]
#### Steps to reproduce the issue
Installed J3.6.0
In Global Configuration, change 'Default Access Level' to 'Registered' and Save & Close
Go to Menus -> Main Menu -> Add New Menu Item

#### Expected result
Access should be set to Registered

#### Actual result
Access is Public

#### System information (as much as possible)
PHP Built On	Linux uk601.directrouter.com 2.6.32-531.29.2.lve1.3.11.1.el6.x86_64 #1 SMP Thu Dec 18 06:49:17 EST 2014 x86_64
Database Version	5.6.30
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.8
Web Server	LiteSpeed
WebServer to PHP Interface	litespeed
Joomla! Version	Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36

**Comment by brianteeman** [comment]
I can confirm it works correctly for New content items etc but not for new menu items.
To be honest I didnt know it would work for menu items but the tooltip says it will.

So either there is a bug in the code or the tooltip is wrong<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11317">issues.joomla.org/joomla-cms/11317</a>.</sub>

**Comment by DavidBoggitt** [comment]
Many thanks for confirming.  I'm not a coder, but from a users point of view it would be hugely useful if the behaviour could follow what the tooltip says.

**Comment by DavidBoggitt** [comment]
Could I possibly beg someone to look at this for the 3.7.0 release please?  Thanks :)

**Comment by Bakual** [comment]
See https://github.com/joomla/joomla-cms/pull/11638

Closing as we have a PR.
