### ISSUE TITLE
Create a new Menuitem type "Module"

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#11319]
In order to display Modules in the mod_menu it would be great to have a new Menu-Item-Type
"Module"

This issue is related to the new Frontend-Template Project issue:
https://github.com/Digital-Peak-Incubator/tpl_tauristar/issues/88

**Comment by brianteeman** [comment]
Do you mean a menu item that contains a module? For example the last item on a content dropdown submenu displays the content of a module eg an image
If so then presumably this will only ever work on a submenu item and cant work on a top level?

**Comment by designbengel** [comment]
Would be great to have it working on a top level too for example a search box or language switcher. Of course it needs to be used wisely ;)

**Comment by brianteeman** [comment]
ok - I understand what you mean now.

**Comment by Bakual** [comment]
Aren't there already menu module in JED which offer that possibility?

While it technically should be possible to implement this into core, it will likely fail horribly in the various templates without any modification on that part.

**Comment by designbengel** [comment]
The request is in favour for the new Joomla! Frontend Template project, thats why i placed it here. (See reference in initial post)

**Comment by laoneo** [comment]
I guess, mod_menu needs to be extended, to load configurable module positions. I'm not sure but I think top level is not needed as you can place already a module at the same position as mod_menu is.

**Comment by Bakual** [comment]
I guess I miss what that new frontend template project tries to achieve. Afaik it's already possible to do such things with menu modules from JED so I don't see what it has to do with a specific new template.

Imho, mod_menu should be a simple menu module as it is today. if you need more extended features, take one of the many modules available on JED.
If you're going to load modules within a (menu-)module by core, you will get some tricky issues for sure further down :smile:

**Comment by designbengel** [comment]
But JED doesn´t help when we want to extend features for the core template. Lot of CMS offer a core "mega-menu" and i think it should be also a core feature.

**Comment by mbabker** [comment]
I dunno.  To me this is encroaching on adding a lot of complexity for the sake of added complexity.  Ya, it might be a nice to have feature, but it's one of those edge cases where does it really belong in the core?  Even if you're building a new mega menu module, what purpose does it serve to create menu items that aren't actual menu items but are instead rendering other HTML snippets?  It seems like what you want is more of a core supported mega menu module with some flexibility in telling it to render other modules, but I don't think that requires updating the menu system to allow a module to be assigned as a menu item.

**Comment by designbengel** [comment]
I thought it´s "just" adding a Menu item type "module" with a list of the Modulepositions. Like it was added to load a module in the article. Why not in the menu? I don´t think it´s very complex? Is it?

**Comment by mbabker** [comment]
Adding new menu types actually is somewhat complex because everything is directly related to a component or is a very hardcoded exception to that rule with zero flexibility.  But those exceptions still directly relate to creating items in a menu.  What's being proposed here isn't the addition of new menu items, it's in essence the ability to render rich HTML snippets in the context of a menu.  It's making the core menu manager a mega menu manager.  No CMS I'm aware of has this capability out of the box, and IMO that's for good reason.  This is exactly the type of feature that belongs in the JED; it's not a solution that is used for an overwhelming majority of websites.

I'd suggest looking at ways to make it easier to extend the menu manager to add "special types" beyond components.  Because right now both the core menu component and menu modules have very hardcoded conventions that don't make it easy to add custom types.  But I don't necessarily think that the core needs to support a feature out of the box to allow assigning modules as menu items.

**Comment by brianteeman** [comment]
I absolutely can see a role for something like this in the core. 
I can see lots of scenarios where it will never work perfectly
I believe there are two different approaches that can be taken
* Create a new menu type - difficult for the reasons Michael stated
* Create a menu module that has the ability to include other modules - so it is managed in the module not the menu - this would mean a slightly more limited approach but it is achievable (i think)
The latter is not really a megamenu per se but it offers some of the functionality

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11319">issues.joomla.org/joomla-cms/11319</a>.</sub>

**Comment by Bakual** [comment]
> I'd suggest looking at ways to make it easier to extend the menu manager to add "special types" beyond components. Because right now both the core menu component and menu modules have very hardcoded conventions that don't make it easy to add custom types.

That would be the correct approach. Allow menu modules or plugins to hook into the list of "system menuitem types" and add custom ones. Then you have the flexibility to add custom types like a module menuitem (or many other yet to invent types).

**Comment by mbabker** [comment]
To do what's being asked for now you have to hardcode it into the menu
system.  I'm honestly not a fan of that.  I don't necessarily think this
feature idea is bad for those looking for it, but I don't feel like it fits
into core as is and honestly the new module option is a bandage over a bad
wound at best.  Making the menu system (component and modules) more
flexible with hooks goes a long way toward adding flexibility to the whole
platform.  Basically if you do the same thing with the menus as was done in
the installer component with the tabs a little change opens a lot of
possibilities.

**Comment by rvbgnu** [comment]
@designbengel Is this still relevant as a feature request?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11319">issues.joomla.org/tracker/joomla-cms/11319</a>.</sub>

**Comment by coolcat-creations** [comment]
@rvbgnu for me: yes! :)

**Comment by ghost** [comment]
If this PR get no Response, it will be closed at 17th September 2017.

**Comment by ghost** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened.
