### ISSUE TITLE
Search Engine Friendly URLS cause List All Categories 404 Article not found

### ISSUE THREAD

**Issue by pintobuck** [joomla/joomla-cms#11315]
Using Joomla 3.6 on a major web hosting site. No SEO extension is installed.

Summary: If Search Engine Friendly URLS are turned on, then "Menu item type -- List All Categories" results in 404 Article not found.

Recreating the problem:
1) Add a new menu item
2) Menu item type -- List All Categories
3) Select a top level category -- choose one
4) Save and close.
5) On the front end, use the menu item, and follow it as far as it will go, which will result in 404 Article not found
6) On the back end / System / Global Configuration / Search Engine Friendly URLS. Select No.  Then the problem goes away. On the front end, use the menu item and you can follow it all the way to the article with no 404.
7) On the back end, turn Search Engine Friendly URLS back on. On the front end, use the menu item, and follow it as far as it will go, and it will result in 404 Article not found, again.

**Comment by brianteeman** [comment]
I am unable to replicate this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11315">issues.joomla.org/joomla-cms/11315</a>.</sub>

**Comment by pintobuck** [comment]
Thank you, brianteeman, for trying to replicate this and for your reply.

On Joomla.org, sozzled commented:
With or without SEF URLs enabled, the menu item [b]Articles[/b] » [b]List All Categories[/b] works under J! 3.6 without any problems for me; I even spent 15 minutes making sure that I didn't misunderstand your instructions.  Sorry but I could not generate any "404 errors".

Pintobuck commented:
Thank you for running the experiment. Based on that, I made a fresh installation of Joomla 3.6 on a test site without any extensions. The new test site worked perfectly for me without any problems.

On my production site, I'm running Joomla 3.6, Gantry 5, Hydrogen template, swMenuPro, and various other extensions. Now that I know Joomla is not the problem, I'll try to isolate the problem from the rest of my setup.  Thanks, again.

**Comment by pintobuck** [comment]
Thank you to brianteeman for trying to replicate this.

On Joomla.org, sozzled commented:
With or without SEF URLs enabled, the menu item [b]Articles[/b] » [b]List All Categories[/b] works under J! 3.6 without any problems for me; I even spent 15 minutes making sure that I didn't misunderstand your instructions.  Sorry but I could not generate any "404 errors".

Pintobuck commented:
Thanks for running the experiment. Based on that, I made a fresh installation of Joomla 3.6 on a test site without any extensions. The new test site worked perfectly for me without any problems.

On my production site, I'm running Joomla 3.6, Gantry 5, Hydrogen template, swMenuPro, and various other extensions. Now that I know Joomla is not the problem, I'll try to isolate the problem from the rest of my setup.  Thanks, again.

**Comment by pintobuck** [comment]
I found a simple solution for me. 
On the back end, go to System / Control Panel / Menus, and click on Rebuild at the top of the page.

**Comment by alequartz** [comment]
I have noticed the same thing. When the SEF URLs is on, the menu items associated with gantry5 templates give a 404 error. They work if I turn the SEF URL option off.
Unfortunately rebuilding the menus did not help in my case.
I am running on gantry 5.3.2 hydrogen template and joomla 3.6.2. 
Thank you in advance for you help.
