### ISSUE TITLE
REGRESSION - #11316

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#11327]
#11316 breaks Joomla :(

On current staging go to any content item, category item etc and try to access the tab AFTER the Associations tab (the one changed in pr #11316) it is not possible if Item Associations is set in the language plugin
See the movie below for example
![association](https://cloud.githubusercontent.com/assets/1296369/17210172/f3fb332e-54b8-11e6-9997-a786016f308b.gif)

**Comment by andrepereiradasilva** [comment]
confirmed. @jreys @infograf768

**Comment by jreys** [comment]
made PR already #11328 , sorry for any inconvenience :/

**Comment by brianteeman** [comment]
Closed as we have a PR to fix this #11328 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11327">issues.joomla.org/joomla-cms/11327</a>.</sub>

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11327">issues.joomla.org/joomla-cms/11327</a>
