### ISSUE TITLE
JFormFieldFolderList broken on windows

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#11336]
#### Steps to reproduce the issue

1. Use a windows system (with xampp)
2. Add into a Form XML a JFormFieldFolderList field and output it

#### Expected result
A List of folders, defined in the "root" folder of the field parameters

#### Actual result
Complete paths to the folders (Like C:\xampp\htdocs\joomla\images/myfolder)

#### System information (as much as possible)
Seems to be a windows bug only

#### Additional comments
Issue came from this PR: https://github.com/joomla/joomla-cms/pull/10722
Line 221: https://github.com/joomla/joomla-cms/commit/5be296a982520b865b1f343efc4ceb767e3673d5#diff-ec4b92ba2051d70bff7613c1a6199c5bR221
The replacement is not correct.
It could also be, that the "recursion output" breaks on linux, if you have the same path in your system and in your images folder, like
/home/joomla/images/myfolder/home/joomla/images/myfolder

**Comment by brianteeman** [comment]
Is this the same as #11288 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11336">issues.joomla.org/joomla-cms/11336</a>.</sub>

**Comment by bembelimen** [comment]
Yes, sorry

**Comment by brianteeman** [comment]
No problem- can you test it please - I dont have a windows machine to try
