### ISSUE TITLE
Syntax Error in libraries/vendor/joomla/string/src/phputf8/utils/ascii.php on line 189

### ISSUE THREAD

**Issue by edulemasson** [joomla/joomla-cms#11340]
In Joomla 3.6 I've got syntax error, unexpected $end, expecting ')' in /home/eduardo/public_html/libraries/vendor/joomla/string/src/phputf8/utils/ascii.php on line 189

**Comment by brianteeman** [comment]
There was a reason you were asked the following questions when you created the issue. If you want someone to help you then you have to provide some information so we can even start.

#### Steps to reproduce the issue
#### Expected result
#### Actual result
#### System information (as much as possible)
#### Additional comments



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11340">issues.joomla.org/joomla-cms/11340</a>.</sub>

**Comment by brianteeman** [comment]
Closed due to lack of response - it can always be reopened if updated<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11340">issues.joomla.org/joomla-cms/11340</a>.</sub>
