### ISSUE TITLE
[Joomla 3.6] Class Json not found in loader.php

### ISSUE THREAD

**Issue by edulemasson** [joomla/joomla-cms#11341]
Class 'Joomla\Registry\Format\Json' not found in /home/cbcmeorg/public_html/libraries/loader.php on line 546

**Comment by brianteeman** [comment]
There was a reason you were asked the following questions when you created the issue. If you want someone to help you then you have to provide some information so we can even start.

#### Steps to reproduce the issue
#### Expected result
#### Actual result
#### System information (as much as possible)
#### Additional comments



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11341">issues.joomla.org/joomla-cms/11341</a>.</sub>

**Comment by brianteeman** [comment]
Closed due to lack of response - it can always be reopened if updated<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11341">issues.joomla.org/joomla-cms/11341</a>.</sub>
