### ISSUE TITLE
unexpected $end in emailcloak.php on line 174

### ISSUE THREAD

**Issue by edulemasson** [joomla/joomla-cms#11342]
PHP Parse error:  syntax error, unexpected $end in /home/edulemasson/public_html/plugins/content/emailcloak/emailcloak.php on line 174

**Comment by mbabker** [comment]
It sounds like you had either a failed upgrade or you've had files edited.  There isn't an `$end` variable in that file nor is there a syntax error with that line in the repo.

**Comment by brianteeman** [comment]
There was a reason you were asked the following questions when you created the issue. If you want someone to help you then you have to provide some information so we can even start.

#### Steps to reproduce the issue
#### Expected result
#### Actual result
#### System information (as much as possible)
#### Additional comments



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11342">issues.joomla.org/joomla-cms/11342</a>.</sub>

**Comment by brianteeman** [comment]
Closed due to lack of response - it can always be reopened if updated<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11342">issues.joomla.org/joomla-cms/11342</a>.</sub>
