### ISSUE TITLE
Logout Redirection Page - Broken?

### ISSUE THREAD

**Issue by skegels** [joomla/joomla-cms#11349]
#### Steps to reproduce the issue
The Logout Redirection Page does not work anymore after upgrading to 3.6.0. (Login Module)
I know there was an issue with this in an earlier version but it appears to be there again.

The Logout Redirection Page is set to "home". But when a users logs out he stays at the last page and is not redirected to the home page.
I tried redirecting to other pages on my site, but after loggin out the user stays on the last visited page.

Regards.

**Comment by brianteeman** [comment]
Thanks for taking the time to report this. It has however already been reported and fixed and will be in the release of 3.6.1 shortly<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11349">issues.joomla.org/joomla-cms/11349</a>.</sub>
