### ISSUE TITLE
[regression] Template preview broken

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-cms#11356]
#### Steps to reproduce the issue
In Joomla 3.6.0 administration, if you go to 
Extensions >Templates > Templates and click on "Preview" you'll go to a page with this URL:
`index.php?tp=1&templateStyle=beez3`
and it will show position (if enabled) and the default template instead of the "selected" one.

If you go to:
Extensions >Templates > Styles and click on the "Preview" button (the one with the eye) you'll see this page: 
`/index.php?tp=1&template=4`
showing again positions (if enabled) and the default template instead of the desired one.

Practically, strings to get the URL of the preview have been inverted.

templateStyle should be followed by the ID of the Style
template should be followed by the name of the template

#### Expected result
Expected URLs should be:
`index.php?tp=1&templateStyle=4` for preview in Styles
`/index.php?tp=1&template=beez3` for preview in Templates

#### Actual result
See the description above.

#### System information (as much as possible)
Joomla 3.6.0

**Comment by Bakual** [comment]
Closing issue as we have two PRs to fix both bugs.
