### ISSUE TITLE
[J.3.6.1.RC2] Bug: JLIB_HTML_CLOAKING not working as expected

### ISSUE THREAD

**Issue by sshcli** [joomla/joomla-cms#11377]
#### Steps to reproduce the issue
1. Install J.3.6.1.RC2
2. Create a new article and insert more than 1 email in the content

#### Expected result
The user must be able to see all the emails in the article content.

#### Actual result
You will see that all emails except the last one are replaced by the following message:
This email address is being protected from spambots. You need JavaScript enabled to view it.

#### System information (as much as possible)
PHP 7.0.8
Apache 2.2.31
J.3.6.1.RC2
Chrome 52.0.2743.82 m

#### Additional comments

![screen shot 2016-07-31 at 22 05 44](https://issues.joomla.org/uploads/1/81c1eb8561556345bfe69932a2304a8b.png)
![screen shot 2016-07-31 at 22 05 44](https://issues.joomla.org/uploads/1/158e02bd5325155535b029a73d7cbdf5.png)

**Comment by Lavsteph** [comment]
I confirm have the same problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11377">issues.joomla.org/joomla-cms/11377</a>.</sub>

**Comment by dgt41** [comment]
@Lavsteph @sshcli please test #11378

**Comment by Lavsteph** [comment]
Fixed with #11378<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11377">issues.joomla.org/joomla-cms/11377</a>.</sub>

**Comment by roland-d** [comment]
Closing as we have a PR #11378 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11377">issues.joomla.org/joomla-cms/11377</a>.</sub>

**Comment by sshcli** [comment]
@dgt41 Thanks. Fixed with #11378
