### ISSUE TITLE
Article count on front-end contains a colon

### ISSUE THREAD

**Issue by n9iels** [joomla/joomla-cms#11382]
#### Steps to reproduce the issue
1) Set Protostar as default front-end template
2) Go to an "List all categories" view
3) Hover over the blue badge and notice the text of the follow tooltip
![image](https://cloud.githubusercontent.com/assets/2659866/17291284/43fbc14a-57e3-11e6-8c5a-04bd142e84c0.png)

#### Expected result
The text on this tooltip should be _Article Count_ or _Article count <number>_ without the colon (:)

#### Actual result
The tooltip text contains a colon (:), so you expect a number behind it

#### System information (as much as possible)
Latest Joomla! staging (3.6.1-rc2

#### Additional comments
I prefer the _Article Count_ in the tooltip, but language is not my cup of tea so I'am curious what other people think

**Comment by brianteeman** [comment]
Yeah thats not correct - I suspect the problem is that string is being used
in multiple places and I bet in one of those it is used with the number

**Comment by brianteeman** [comment]
I can confirm that the string is used in multiple places and in the other places it is correct to show the colon

The best fix is to create a new string for the tooltip without the : <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11382">issues.joomla.org/joomla-cms/11382</a>.</sub>

**Comment by brianteeman** [comment]
Thanks for reporting this - I created a PR for testing #11385<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11382">issues.joomla.org/joomla-cms/11382</a>.</sub>
