### ISSUE TITLE
[REGRESSION] Help system

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#11381]
#### Steps to reproduce the issue
Compare the help link on the module manager page and the content of the popup on 3.6.1rc2 and 3.6.0

#### 3.6.0 
the link will be
``` https://help.joomla.org/proxy/index.php?option=com_help&keyref=Help36:Extensions_Module_Manager ```

the output will be
![screen shot 2016-08-01 at 05 11 32](https://issues.joomla.org/uploads/1/d95cb7fb6c644e100ebe9a748f379086.png)

#### 3.6.1 RC2
the link will be 
``` https://help.joomla.org/proxy/index.php?option=com_help&amp;keyref=Help36:Extensions_Module_Manager ```
NOTE the escaped ```&amps```

The output will be
![screen shot 2016-08-01 at 05 13 29](https://issues.joomla.org/uploads/1/a891a68a3c89ea19e57bb81e0b4db397.png)

**Comment by Stevec4** [comment]
Brian
I do not have this regression on my server. The help page loads fine using RC2

`https://help.joomla.org/proxy/index.php?option=com_help&keyref=Help36:Extensions_Module_Manager`

**Comment by Lavsteph** [comment]
I confirm the problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11381">issues.joomla.org/joomla-cms/11381</a>.</sub>

**Comment by mbabker** [comment]
The escaped ampersands is a problem.  Properly decoded, it's fine.

**Comment by brianteeman** [comment]
Any idea where the bug was introduced because the link to the help sites has contained the ampersand for a long time<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11381">issues.joomla.org/joomla-cms/11381</a>.</sub>

**Comment by mbabker** [comment]
Off hand not a clue but it is definitely a change between 3.6 and 3.6.1 (the first two places I looked were the `JToolbarButtonHelp` class and the layout but neither of those had any changes).

**Comment by brianteeman** [comment]
As you have done a PR that resolves it I am going to close this
