### ISSUE TITLE
Redundant option in Mod_menu

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#11380]
As far as I can tell the Target Position option in mod_menu is redundant and can be removed (at least I couldnt see anywhere it is used or work out how to use it)

It is described in the 2.5 documentation (https://docs.joomla.org/Help25:Extensions_Module_Manager_Menu) but there is no mention of it in the 3.6 documentation https://docs.joomla.org/Help36:Extensions_Module_Manager_Menu

![7obd](https://cloud.githubusercontent.com/assets/1296369/17290336/dbd9eae0-57d5-11e6-9611-5bb2bd016777.png)

**Comment by bertmert** [comment]
One of the never used "special" features "for somebody" I think.

It's used here (`window_open`):
https://github.com/joomla/joomla-cms/blob/staging/modules/mod_menu/tmpl/default_url.php#L47

If you select `Target Window > New Without Navigation` in a menu item of type `External URL` you can add additional key value pairs for the popup window.

If it will not be removed it's not logical that it's only used in `External URL`.

> MOD_MENU_FIELD_TARGET_DESC="JavaScript values to position a popup window, eg top=50,left=50,width=200,height=300."

Description is misleading.

Example with `top=0,right=0,width=50,height=50` and `google.com`:

![01-08-_2016_12-43-27](https://cloud.githubusercontent.com/assets/11038612/17291813/6077030e-57e6-11e6-9c95-fb2aaab96d3d.jpg)

**Comment by brianteeman** [comment]
I tried that before posting and it didn't work for me. I will test again

**Comment by brianteeman** [comment]
OK I can confirm thats how it works now. Sadly we wouldnt be able to remove it as it would be a b/c break<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11380">issues.joomla.org/joomla-cms/11380</a>.</sub>
