### ISSUE TITLE
ext/mcrypt Deprecation

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#11398]
As of PHP 7.1, the mcrypt extension [has been deprecated](https://wiki.php.net/rfc/mcrypt-viking-funeral) and will stop being distributed as part of the core PHP package in a future release.  Usage of `mcrypt_*` functions emits `E_DEPRECATED` messages as seen in [this Travis-CI build](https://travis-ci.org/joomla-framework/crypt/jobs/148702240) for the Framework's Crypt package.

To prepare for this, Joomla core should begin planning for ways to replace uses of the `mcrypt` extension as practical, either by introducing new API endpoints (i.e in the `JCrypt` class chain if we keep rolling our own crypto) or introducing switches in places where `mcrypt_*` functions are used standalone.

**Comment by PhilETaylor** [comment]
I guess the start of this then would be 

- Identify the methods that implement/consume mcrypt in the Joomla code, 
- Document those, 
- unit test them in their current state
- Refactor out the use of mcrypt
- Ensure tests still run
- TEST TEST TEST TEST TEST 
- TEST
- TEST 

?

**Comment by PhilETaylor** [comment]
This will also need @nikosdion help as mcrypt appears in the updater/restore.php etc.

**Comment by nikosdion** [comment]
Um, if mcrypt is no longer supported how do we implement AES encryption in PHP? Native PHP code is orders of magnitude slower.

**Comment by PhilETaylor** [comment]
See. I knew it was important to tag @nikosdion ;-)

**Comment by nikosdion** [comment]
FWIW the restore.php only uses mcrypt out of context of the Joomla Update (extracting JPS archives). The part used during the update is native PHP code implementing AES-CTR, used to encrypt the serialized extraction engine state with a server side key and send encrypted instructions to the JavaScript side (which also implements AES-CTR in native JavaScript).

**Comment by mbabker** [comment]
> Um, if mcrypt is no longer supported how do we implement AES encryption in PHP?

According to the RFC I linked OpenSSL can handle AES encryption.  Not sure about many details beyond that but that seems to be the primary recommendation from Scott.

**Comment by nikosdion** [comment]
Hence I edited my reply (sorry; just having my first coffee of the day). While OpenSSL handles AES encryption the extension itself is not as widely deployed as mcrypt on older PHP installs. So it's not a matter of replacing code but adding if-blocks to use what is available. If you want to be very conservative we'd also need a full native implementation so the order of preference would be:
* OpenSSL 
* mcrypt
* native code (slow)
The only thing I'm not sure is whether we can find a native AES implementation compatible with GPL 2. 

On a different note, there is one place in Joomla where replacing mcrypt will be tricky: FOF2. It's obsolete and I'm not going to maintain it. The good news is that nobody seems to be using that code.

**Comment by brianteeman** [comment]
@nikosdion has updated FOF2 
> [HIGH] mcrypt is deprecated in PHP 7.1. This will cause Two Factor Authentication to fail under PHP 7.1 unless you apply this PR.

So the "tricky" bit has already been done :)

**Comment by andrepereiradasilva** [comment]
Just an aditional note, when joomla does not need mcrypt anymore i guess the two PR for info on mcrypt installed https://github.com/joomla/joomla-cms/pull/9508 and https://github.com/joomla/joomla-cms/pull/9532 should be reverted.

**Comment by mbabker** [comment]
Remaining mcrypt uses are in deprecated code or third party libraries.  Complete enough.
