### ISSUE TITLE
No login at all after updating to Joomla 3.6.1

### ISSUE THREAD

**Issue by Tuscany58** [joomla/joomla-cms#11429]
#### Steps to reproduce the issue
Direct writing update from 3.6 to 3.6.1

#### Expected result
successful update

#### Actual result
error at the end of the update process
Website is still running
Not possible to login to frontend at offline website
After some time, no login to backend aswell

Error message:
**An error has occurred.
0 Failed to start the session: already started by PHP ($_SESSION is set). 
Return to Control Panel**

#### System information (as much as possible)
Joomla 3.6
JCE on all website
RS Events Pro on all website
Advanced Module Manager at some websites
Templates from Yootheme (4), RocketTheme (1) and JoomShaper (1)

#### Additional comments
I tried to repair the database via phpmyAdmin, and deleted entries in the session table, neither helped.

**Comment by jeckodevelopment** [comment]
Can you please try to include versions of your software?
PHP? MySQL?  any other modification?

**Comment by Tuscany58** [comment]
![zdgv2_sysinfo](https://cloud.githubusercontent.com/assets/20827064/17386733/b35bde4c-59ed-11e6-8652-14c2ad613308.jpg)

Attachment is screenshot of system information of a not yet updated site

**Comment by jeckodevelopment** [comment]
@Tuscany58 are you able to update to PHP 5.4 or 5.5 from your hosting panel?

**Comment by Tuscany58** [comment]
Websites are hoted at Siteground. I don't think this is possible. At least I did not find anything regarding PHP in cpanel

**Comment by Tuscany58** [comment]
These are my components and (system)plugins on one of my websites:
![crv2_components](https://cloud.githubusercontent.com/assets/20827064/17387183/963279b2-59f1-11e6-9318-3d8a74b0f4ba.jpg)
![crv2_sysplugins](https://cloud.githubusercontent.com/assets/20827064/17387182/962f0674-59f1-11e6-9c80-4f76ccf95fed.jpg)

**Comment by wilsonge** [comment]
This seems to be a PHP 5.3 issue as #11428 has the same issue on same PHP version. Can you post this information in there please so we can have all the information on this bug in one place please! Thank you very much and apologies for this

**Comment by wilsonge** [comment]
Patch https://github.com/joomla/joomla-cms/pull/11430

**Comment by lalapo1** [comment]
go here and copy:
https://raw.githubusercontent.com/joomla/joomla-cms/cfcaac3b7bf553a33a6bced765f3b8bdcb2f41fb/libraries/joomla/session/handler/native.php

replace

in

route

public_html/libraries/joomla/session/handler/native.php

native.php

regards

**Comment by jeckodevelopment** [comment]
@lalapo1 there's already a patch for this.

**Comment by lalapo1** [comment]
@jeckodevelopment 
 is the same
to understand
the patch
regards
