### ISSUE TITLE
Incorrect SEO URLs on the archived article module

### ISSUE THREAD

**Issue by saraheagle** [joomla/joomla-cms#11422]
#### Steps to reproduce the issue
- Create fresh joomla site 
- Created the module Archived Articles 
- Created a new article as published, set it to status archived, saved & viewed it on front-end
- It shows in Archived Articles module and link ie "July 2016" works correctly
- Add a menu item "Archived Articles"
#### Expected result
- Link ie "July 2016" should go to archived article
- See http://defj36.testcms.co.uk/ 
#### Actual result
- It gives a 404 error
- As soon as SEO URLs are turned off or menu item removed links work correctly
#### System information (as much as possible)

System  Linux ukm2.siteground.biz 3.12.18-clouder0 #26 SMP Tue Jul 12 09:43:48 EEST 2016 x86_64
PHP Built On    Linux ukm2.siteground.biz 3.12.18-clouder0 #26 SMP Tue Jul 12 09:43:48 EEST 2016 x86_64
Database Version    5.6.28-76.1-log
Database Collation  utf8_general_ci
Database Connection Collation   utf8mb4_general_ci
PHP Version 5.6.24
Web Server  Apache
WebServer to PHP Interface  cgi-fcgi
Joomla! Version Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT
Joomla! Platform Version    Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent  Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by AlexRed** [comment]
I can confirm the problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11422">issues.joomla.org/joomla-cms/11422</a>.</sub>

**Comment by AlexRed** [comment]
seems related with https://github.com/joomla/joomla-cms/pull/10613/files
regress it solve the problem in the module Archived Articles but reintroduces the Issue #9566<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11422">issues.joomla.org/joomla-cms/11422</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Cannot confirm Issue on 3.7-staging and enabled modern Routing.

**Comment by franz-wohlkoenig** [comment]
@saraheagle can you confirm this Issue on latest Staging?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11422">issues.joomla.org/tracker/joomla-cms/11422</a>.</sub>

**Comment by saraheagle** [comment]
Super, it seems to be fine now.
Thank you very much for your work :)

**Comment by franz-wohlkoenig** [comment]
closed as issue is solved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11422">issues.joomla.org/tracker/joomla-cms/11422</a>.</sub>
