### ISSUE TITLE
Wrong url for the 3.6.1 update package

### ISSUE THREAD

**Issue by shamglam** [joomla/joomla-cms#11427]
#### Steps to reproduce the issue
Try to upgrade to 3.6.1 with joomla updater

#### Expected result
upgrade success

#### Actual result
upgrade fails with error "The archive file is corrupt, truncated..." 

#### System information (as much as possible)
Installed version 3.4.5

#### Additional comments
it fails because the feed at 
https://update.joomla.org/core/sts/extension_sts.xml
points to 
https://github.com/joomla/joomla-cms/releases/download/3.6.1/Joomla_3.6.1-Stable-Patch_Package.zip

which doesn't exist.

**Comment by APD183** [comment]
Same issue on attempted update from 3.5.1

**Comment by brianteeman** [comment]
The url is wrong
it should be either
Joomla_3.6.x_to_3.6.1-Stable-Patch_Package.zip
or
Joomla_3.6.1-Stable-Update_Package.zip

Not sure which - pinging the right people to get it fixed

**Comment by shamglam** [comment]
workaround is to download the patch package file manually and rename it to Joomla_3.6.1-Stable-Patch_Package.zip

**Comment by zero-24** [comment]
I have not noticed that on the review of the commit here is a fix: https://github.com/joomla/update.joomla.org/pull/13 sorry @wilsonge :(

**Comment by brianteeman** [comment]
Thanks for the awesome fast response

**Comment by wilsonge** [comment]
Thanks Tobias!

**Comment by zero-24** [comment]
we have broken it together we should fix it together :P

**Comment by wilsonge** [comment]
<3
