### ISSUE TITLE
Add new help servers via language packs or key

### ISSUE THREAD

**Issue by yild** [joomla/joomla-cms#11434]
New feature.

Add new help server (to global configurations -> system tab -> help server list) via language packs manifest file or new language key with server url.

My TT Coordinator was too through and JHELP_COMPONENTS_ strings ware translated to strings that match our language (PL) wiki with help topics. ATM there are only English and French help servers listed in "help servers" list (global configuration->system tab).

With this translation issue either of the server works, Joomla can't display correct help page and throw 

RuntimeException
Error fetching page from MediaWiki API: The page you specified doesn't exist

error.

If we could extend language pack manifest file with info about language help server it might resolve this issue but it would require install.php to add new help server to db and remove it when package is uninstalled.

Second option would be to add new key to language file i.e:
JHELP_COMPONENTS_SERVER_URL="http://wiki.joomla.pl"
If this string is empty use settings from global configuration, if set then use provided url as help server.
This option could use of key override if administrator wanted to select i.e. english help file (that is most up to date) instead of the one provided by key in language file (again if override string is empty then use global configuration setting).

**Comment by infograf768** [comment]
The ` JHELP_COMPONENTS_etc.` strings should not be translated.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11434">issues.joomla.org/joomla-cms/11434</a>.</sub>

**Comment by brianteeman** [comment]
What is the correct way for a language to be added to the helpsites.xml? I looked in the docs but didnt see anything but I might have searched wrong as i only found this https://docs.joomla.org/Help_system/Helpsites_XML_format

**Comment by yild** [comment]
I wrote this issue hastily... there are other things to consider:

Are there any docs that would explain this wiki api proxy technicalities mentioned in https://docs.joomla.org/Help_system/Help_servers ? Is there any code available ?

**Comment by mbabker** [comment]
> Is there any code available ?

https://github.com/joomla/help.joomla.org

Specifically, you'll want to look at https://github.com/joomla/help.joomla.org/blob/master/src/Model/HelpScreenModel.php which has all the code dealing with pinging the MediaWiki instance it's configured to work with.

Just for reference, the help screen system is basically a three step thing.  The CMS issues a request to the "proxy" server (right now core lists English and French) and that proxy server takes care of fetching data from MediaWiki and rendering the page.

**Comment by brianteeman** [comment]
Closing it here as there is nothing to do
