### ISSUE TITLE
[regression] Joomla 3.6.1 -  issue with emailcloak-plugin?

### ISSUE THREAD

**Issue by dirk32** [joomla/joomla-cms#11439]
#### Problem

I just upgraded Joomla from 3.6.0 to 3.6.1 and received an issue with emailcloak-plugin.

All email addresses were replaced by the string "Diese E-Mail-Adresse ist vor Spambots geschützt! Zur Anzeige muss JavaScript eingeschaltet sein!" (english: "This email address is being protected from spambots. You need JavaScript enabled to view it.").
On 3.6.0 this worked well (and is still functional at a different url on the same server and account). Clearing all caches (joomla & browser) didn't help. The only solution was to deactivate the plugin.

Is this issue linked to the described problem with CSRF token? Can you confirm the problem?

#### Additional information

looks like a problem already happened with earlier joomla-versions (as I read on the net).

**Comment by brianteeman** [comment]
is this in a content item or somewhere else?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11439">issues.joomla.org/joomla-cms/11439</a>.</sub>

**Comment by dirk32** [comment]
yes, it’s in content items only, modules are not effected.

 

 

 

              Dirk Steigemann

      TSV Loccum e.V. von 1895

                     - Admin -

 <mailto:dirk.steigemann@tsv-loccum.de> dirk.steigemann@tsv-loccum.de

           <http://www.tsv-loccum.de/> www.tsv-loccum.de

 

 

Von: Brian Teeman [mailto:notifications@github.com] 
Gesendet: Donnerstag, 4. August 2016 13:25
An: joomla/joomla-cms <joomla-cms@noreply.github.com>
Cc: dirk32 <dirk.steigemann@tsv-loccum.de>; Author <author@noreply.github.com>
Betreff: Re: [joomla/joomla-cms] Joomla 3.6.1 upgrade - issue with emailcloak-plugin? (#11439)

 

is this in a content item or somewhere else?

  _____  

This comment was created with the J!Tracker Application <https://github.com/joomla/jissues>  at issues.joomla.org/joomla-cms/11439 <https://issues.joomla.org/tracker/joomla-cms/11439> .

**Comment by brianteeman** [comment]
I cannot replicate it myself BUT that doesnt mean there isnt an issue. 

What is the exact code that you have in your article? is it a mailto link with some options for example

**Comment by dirk32** [comment]
The Code is a simple mailto link (like this one „<a href="mailto:info@tsv-loccum.de">info@tsv-loccum.de <mailto:info@tsv-loccum.de%3c/a> </a>”) , no further options.

 

 

 

              Dirk Steigemann

      TSV Loccum e.V. von 1895

                     - Admin -

 <mailto:dirk.steigemann@tsv-loccum.de> dirk.steigemann@tsv-loccum.de

           <http://www.tsv-loccum.de/> www.tsv-loccum.de

 

 

Von: Brian Teeman [mailto:notifications@github.com] 
Gesendet: Donnerstag, 4. August 2016 13:38
An: joomla/joomla-cms <joomla-cms@noreply.github.com>
Cc: dirk32 <dirk.steigemann@tsv-loccum.de>; Author <author@noreply.github.com>
Betreff: Re: [joomla/joomla-cms] Joomla 3.6.1 upgrade - issue with emailcloak-plugin? (#11439)

 

I cannot replicate it myself BUT that doesnt mean there isnt an issue. 

What is the exact code that you have in your article? is it a mailto link with some options for example

**Comment by osignell** [comment]
I'm having the same problem when showing multiple e-mail addresses in a content article. It seems to be related to the changes done in #11027 and more specifically the line
`document.onreadystatechange = function ()`
in libraries/cms/html/email.php

If i'm reading the code correctly, this onreadystatechange function gets overwritten every time a new cloaking is performed?

**Comment by brianteeman** [comment]
@dirk32 I can confirm the issue

**Comment by zero-24** [comment]
see: https://github.com/joomla/joomla-cms/pull/11378 @wilsonge maybe we should fix this with 3.6.2 too?

**Comment by dirk32** [comment]
### Amendment:

This issue is not depending on multiple mail addresses in a content item.

The problem also occured if there is text in an e-mail format (also a single one, even without any mailto-link in html!).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11439">issues.joomla.org/joomla-cms/11439</a>.</sub>

**Comment by brianteeman** [comment]
Closing it here - please  test #11378
