### ISSUE TITLE
3.6.1: Failed to start the session: already started by PHP ($_SESSION is set) on PHP 5.3

### ISSUE THREAD

**Issue by khanhlh** [joomla/joomla-cms#11431]
#### Steps to reproduce the issue
Goto login page and login.

#### Expected result
Logged in.

#### Actual result
Error page with result:
0 - Failed to start the session: already started by PHP ($_SESSION is set).

#### System information (as much as possible)
PHP 5.3

#### Additional comments
![screen shot 2016-08-04 at 11 27 59 am](https://cloud.githubusercontent.com/assets/340521/17390425/4403c916-5a37-11e6-9b4f-30d7f222410b.png)

**Comment by joomdonation** [comment]
It should be fixed by this PR https://github.com/joomla/joomla-cms/pull/11430. Could you please test and report the result back?

**Comment by khanhlh** [comment]
It works, thanks mate.

**Comment by smu77** [comment]
Thx, works fine!

**Comment by Luisriveraa** [comment]
Thanks a lot. It works fine.

**Comment by Waywardnl** [comment]
Works for me, - menas DELETE, and + menas Add

I Forgot to delete the lines ;-) at first

**Comment by sergiopalomo** [comment]
How to you apply the patch, I am not a programmer and dont know what to do, thanks in advance for your help.

**Comment by edwardvdv** [comment]
Thanks, it worked.

@segiopalomo:
change directory into <web root>/libraries/joomla/session/handler, backup the file native.php to native.php.bak, and replace native.php by retrieving the fixed native.php by doing a wget https://raw.githubusercontent.com/joomla/joomla-cms/cfcaac3b7bf553a33a6bced765f3b8bdcb2f41fb/libraries/joomla/session/handler/native.php --no-check-certificate

That should fix it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11431">issues.joomla.org/joomla-cms/11431</a>.</sub>

**Comment by edwardvdv** [comment]
Additionally, Joomla 3.6.2 fixes this:
https://www.joomla.org/announcements/release-news/5667-joomla-3-6-2-released.html<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11431">issues.joomla.org/joomla-cms/11431</a>.</sub>
