### ISSUE TITLE
J3.6.0 to J3.6.1 - Upgrade complete, but progress hangs at 0

### ISSUE THREAD

**Issue by pippo8765** [joomla/joomla-cms#11435]
#### Steps to reproduce the issue
Update J3.6.0 to J3.6.1 via Live Update
If you uninstalled beez3 (like I did on several sites), or you have forbidden writing index.php in beez3 folder, you get message in popup:
"ERROR:
Could not open /my_path/templates/beez3/index.php for writing."
Update progres seen in background is stuck at 0, also when you click ok on popup:
"Updating your Joomla files. Please wait ...
Percent complete 0.0
Bytes read 0
Bytes extracted 0
Files extracted"

#### Expected result
Joomla 3.6.0. IS NOT updated to 3.6.1.

#### Actual result
As seen in System Information:

Joomla! Version     Joomla! 3.6.1 Stable [ Noether ] 2-August-2016 22:59 GMT 

So, it IS updated, though I never saw it is happening in Joomla Update component, so I am not informed well there.
Now it's not clear to me if all files were written correctly.

#### System information (as much as possible)

Setting 	        Value
PHP Built On 	               Linux server.name 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64
Database Version 	        5.5.47-MariaDB
Database Collation 	        utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	                5.5.37
Web Server 	                Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.5.37
WebServer to PHP Interface 	apache2handler
Joomla! Version 	        Joomla! 3.6.1 Stable [ Noether ] 2-August-2016 22:59 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	                Mozilla/5.0 (Windows NT 10.0; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0 

#### Additional comments
Database is fixed using backend tool w/o problems.

**Comment by ggppdk** [comment]
So may be update title of this thread: 

Can not update to J3.6.1 if beez3 has been uninstalled

**Comment by pippo8765** [comment]
Hi Georgios, 
no, it would not reflect actual situation: update is DONE, but as user I am not sure if it passed. Notification was bad: progress bar hangs at 0, but when you go to System Info you see that it passed. Joomla update component never says 100% after I click OK in modal which informs me about beez3. It hangs at 0, but actually update is going smooth in "background" obviously. 

I use Joomla for more than decade now, but someone less experienced will not check all I do. He/she expects info in this screen. At least in my mind. 
Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11435">issues.joomla.org/joomla-cms/11435</a>.</sub>

**Comment by ggppdk** [comment]
Ok then:

Can not **complete** upgrade to new Joomla version if beez3 has been uninstalled

**Comment by pippo8765** [comment]
Maybe: "J3.6.0 to J3.6.1 - Upgrade complete, but progress hangs at 0"
Your proposal sound more like it, too, since I have to be informed by notification at the end. But still - upgrade IS COMPLETE, all files are in place, I just did not get notification, progress hangs at 0!
It describes it closer.
You decide, I don't mind at all, you have much much more experience with titling these issues :)
Thank you very much once again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11435">issues.joomla.org/joomla-cms/11435</a>.</sub>

**Comment by ggppdk** [comment]
> But still - upgrade IS COMPLETE, all files are in place

Then since you are upgraded from J3.6.0 and not from an earlier version,
you are good, 

just go to Extensions / Manager / "Database" and click "Fix"

**Comment by pippo8765** [comment]
All clear :smile: 
I'll stick then to my proposed title, since it explains it more clearly. I changed it now.
I did everything, upgrade is complete, I had no problem, apart from not being notified properly that it actually happened.
Common user will be confused. I consider myself advanced one. At the end, my case might not be single one when this happens (including beez3 template, I mean, maybe it hangs on other permissions, missing files, extensions etc...) Progress should either go to 100% and say "It's done" or if it fails or hangs at some point - upgrade is not done - and it's not done for real! Being at 0 and when I check version it says it's done - it's confuzing! That's the problem here. Again - I solved it, for me it's clear what happens, but I doubt common user will know what's the real status of upgrade.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11435">issues.joomla.org/joomla-cms/11435</a>.</sub>

**Comment by PhilETaylor** [comment]
***Unable to replicate***

I did this:

- Install Joomla 3.6.0
- Uninstall Beez Template using Extension Manager -> Manager -> Uninstall
- Use Joomla Update extension to update to Joomla 3.6.1
- (see session token message at end of update - known issue, applied database fix button) 
- Went to admin console, was running Joomla 3.6.1 with no issues

**Comment by pippo8765** [comment]
Strange... anyway, now that 3.6.2 is out, I get message again, progress bar hangs at some point, but Joomla is NOT updated. That's exactly what I expect, since it never got to 100%. All settled with 3.6.2 obviously.
Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11435">issues.joomla.org/joomla-cms/11435</a>.</sub>

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11435">issues.joomla.org/joomla-cms/11435</a>.</sub>
