### ISSUE TITLE
Lets make Joomla 3.7+ compatible with PHP 7+only. Discuss.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#11444]
Lets make Joomla 3.7+ compatible with PHP 7+only. 
========

Discuss.

Why? ***For all the right reasons! Its 2016 already...***

Maybe support the end of life of Joomla 3.6.x a little longer for those with extensions or historic sites that cannot be upgraded to PHP 7, but lets, as a project, bite the bullet and design for real world, up to date, secure, PHP versions from now on eh ?....

In 4 months time PHP 5.6 will reach end of active support - http://no2.php.net/supported-versions.php

Web hosts (the reputable ones!) seem to be deploying and keeping PHP versions up to date a lot fast nowadays, unlike the old PHP 5.3 to 5.4 cross over days.

There simply is no reason, no excuse not to use the latest PHP version available.

Lets take the lead on this and just do it... In my mind it doesn't even need discussing, just implementing!

**Comment by ggppdk** [comment]
I would say dump PHP 5.3 support in J3.7  !!

Sure we would like a faster / better PHP version,
 but you take it too far,

- also when will J3.7 be released

**Comment by brianteeman** [comment]
Please discuss this on the mailing list.

**Comment by PhilETaylor** [comment]
Which mailing list gets more views then this issue tracker?

**Comment by brianteeman** [comment]
Use joomla-cms

**Comment by mbabker** [comment]
If we were something the size of October or Grav, maybe we could get away with it.  With as big as Joomla is though, as much as I hate saying this, it'd be massively irresponsible for Joomla to abandon PHP 5 so soon.  With any luck Joomla 4 will be PHP 5.6+ (or maybe you can convince people to go PHP 7 there) and 3.x still gets supported for some time after its release.  But I think that's really the soonest you could logically push the minimum requirement that hard.  Also keep in mind basically every major PHP project has only recently (last ~12 months) gotten to a PHP 5.5 minimum.

**Comment by brianteeman** [comment]
Yes that's the list. It will reach more people as there are more
subscribers than here

**Comment by mahagr** [comment]
As for Grav (@mbabker 's comment), the main reason to set minimum PHP 5.5.9 requirement was because of more than one library we depend on (Symfony, Whoops etc) raised their own requirements and were missing PHP7 support on older versions. Question whether to keep PHP 5.4 support or go for PHP 7 support was easy in that case.

As there's still no discussion in the mailing list, I would not drop PHP 5.3 support just yet, but I would add a permanent warning into admin if your PHP version is too old (at least < 5.5.9). Many users do not update PHP just because of they aren't aware that there's a newer and better version available. Or they have had no motivation to do that. I would also recommend people upgrading to PHP 5.6 mostly because of a lot of extensions still have issues in PHP 7.

**Comment by chrisdavenport** [comment]
We will definitely be dropping 5.3 support at the earliest opportunity, but as per SemVer and our development policy, that can only be done in conjunction with a major version increment.  That is, Joomla 4.0.

**Comment by PhilETaylor** [comment]
There is no reason Joomla 4 cannot be PHP 7 only, and to increase the end of life support date for Joomla 3.... apart from no one has the balls to do it.

**Comment by chrisdavenport** [comment]
Minimum requirement for Joomla 4 might turn out to be PHP 7.x, although I think 5.6 is more likely, but the final decision on that has yet to be taken and won't be taken until closer to the release date.  The decision will be based on the data collected by the stats plugin and other sources.

The EOL date for Joomla 3.x will be as per our published policy.

**Comment by mbabker** [comment]
If you go by [the stats](https://developer.joomla.org/about/stats.html) the sane choices for 4.0 are either PHP 5.5 or 5.6.  I'd suggest PHP 7 has too low adoption to make a decision today to require that as a minimum version.

Yes, it is borderline irresponsible to release a new major Joomla version supporting unsupported PHP versions, but as much as we groan about things Joomla users go to cheap as all can be hosting who barely understand how to `./configure` and `make` a PHP installation, let alone on a version that was released this year.  It's the tradeoff to being a project as large as Joomla.

For pure PHP libraries where developers are building applications, it's a lot easier to make that call.  You aren't giving distributed downloads to people whose only technical ability is their ability to open an internet browser and check their email.

Long and short, Joomla needs to phase out old PHP version support.  But it can't just be at the drop of a dime and it can't be at a target point that less than 10% of users with CURRENT versions (rough math our stats server barely accounts for 20% of all known Joomla sites if you go by the numbers estimating there are 2.8 million installs) are able to upgrade to.

**Comment by andrepereiradasilva** [comment]
4.0 should only support 5.6.x+ IMO

**Comment by alikon** [comment]
Even if this stats maybe not so updated we should take care of what is shipped with Linux distro's
http://www.sasaprolic.com/2013/02/list-of-current-php-version-in-major.html
or
https://w3techs.com/technologies/details/pl-php/all/all

**Comment by mbabker** [comment]
And if you go by that we should basically stick to 5.3 because the Linux distros lock to a base PHP version then hack the everloving crap out of it.
