### ISSUE TITLE
[mod_logged]: Tag <a> contains duplicated `class` attribute

### ISSUE THREAD

**Issue by nvyush** [joomla/joomla-cms#11441]
#### Steps to reproduce the issue
Open a file /administrator/modules/mod_logged/tmpl/default.php and find and inspect string contained `<a class="hasTooltip"`.

#### Expected result
Tag <a> must contain a single `class` attribute: `class="hasTooltip btn btn-danger btn-mini"`

#### Actual result
Tag <a> contains duplicated `class` attribute: `class="hasTooltip"` at the start and `class="btn btn-danger btn-mini"` at the end of list of attributes.

#### System information (as much as possible)
Joomla! 3.6

#### Additional comments
This causes HTML 5 validation error.

**Comment by brianteeman** [comment]
I can confirm the issue and I will make a PR to fix it

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #11443
