### ISSUE TITLE
Improve Joomla's Accessibility

### ISSUE THREAD

**Issue by dgt41** [joomla/joomla-cms#11459]
An extremely easy task that will improve hugely the accessibility of Joomla is the removal of chosen.js from every drop down that now uses it. Chosen is really bad for accessibility and shouldn't be used no matter what the excuse.

**Comment by brianteeman** [comment]
are you recommending #9901

**Comment by dgt41** [comment]
Nope, that's just adds some specific class for chosen, what I am suggesting is to totally remove from core all instances
```php
JHtml::_('formbehavior.chosen');
```
Some additional work will be needed for tags and maybe some other scripts that expect chosen to be loaded

**Comment by brianteeman** [comment]
What specific a11y issues 

Found this https://github.com/harvesthq/chosen/issues/264

**Comment by dgt41** [comment]
try the simplest test:
move around in a page with tab till you get to a (chosen) dropdown, then try to use keys to navigate inside the selected (chosen) dropdown. Try se same test in a page without chosen. Yeah it's that bad...

**Comment by brianteeman** [comment]
didnt seem too bad to me - tested with the category list on a new item

**Comment by yild** [comment]
I also didn't found problem with lists - but I guess we don't see it as we should.

But found issue with popup window edit module settings at module assignment tab in menu item. -  can't be closed to cancel or to accept changes (especially in module assignment window).

**Comment by KITSKevinBonett** [comment]
I don't use Joomla, but I have been auditing a whole bunch of great accessibility enhancements in a fork of the "chosen" plugin - can be found at https://github.com/cooperfellows/chosen/tree/a11y-updates

See the conversation towards the end of https://github.com/harvesthq/chosen/issues/264

If it wasn't for this forked version I would be recommending that we also did not use the plugin in the project.

**Comment by brianteeman** [comment]
Hi - I am closing this here. Please create an issue directly to the a11y group here https://github.com/joomla-projects/accessibility/issues
