### ISSUE TITLE
E-Mail clocking not working with more than 1 email adresses on one page (3.6.1)

### ISSUE THREAD

**Issue by hacki65** [joomla/joomla-cms#11453]
#### Steps to reproduce the issue
1. Build an article and insert 2 or more email adresses.
2. Make a menu entry to this article
3. See on frontend

#### Expected result
With javascript enabled all emails are displayed correctly

#### Actual result
Only the last email adress is linked. The first is protected although javascript IS ENABLED.

#### System information (as much as possible)
Joomla! 3.6.1
PHP 7.0.9

#### Additional comments

![j361-email-coacking-bug](https://cloud.githubusercontent.com/assets/20481746/17413444/84f9a8ba-5a81-11e6-813a-1fc9d7026e7a.jpg)

**Comment by brianteeman** [comment]
Thank you for reporting this. There already is a fix that needs testing #11378
