### ISSUE TITLE
Class removed when Email Cloaking Plugin is enable

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-cms#11456]
#### Steps to reproduce the issue
Create an email link containing a class
For example: `<a href="mailto:toto@toto.com" class="nameofmyclass">email</a>`

#### Expected result
On frontend, the class should be applied
![](http://www.idimweb.com/images/1.png "")

#### Actual result
The class is completely removed from the HTML source code and becomes:
`<span id="cloak9b08867df87471a610f686815c73ade8"><a href="mailto:toto@toto.com">email</a></span>`
(Just a side note: my display was ok with 3.6.0)
![](http://www.idimweb.com/images/2.png "")

#### System information (as much as possible)
Test done on my localhost
Joomla! 3.6.1
PHP 7.0.4
MySQL 5.5
Apache Web server

**Comment by demis-palma** [comment]
Sandra, are you sure that this problem does not affect Joomla 3.6.0?
I'm asking this because this plugin has not been touched for 12 months and it seems strange that Joomla 3.6.0 worked as expected.

**Comment by Sandra97** [comment]
It's a website I'm currently working on evry day, it was all fine with 3.6.0 and appeared just after 3.6.1, without any other specific changes

**Comment by brianteeman** [comment]
Closed as #11460 was merged
