### ISSUE TITLE
Allow Edit after Soft deny is no longer possible (always denied) for backend articles manager

### ISSUE THREAD

**Issue by ggppdk** [joomla/joomla-cms#11463]
#### Steps to reproduce the issue
at global configuration permissions
and
at Article component

do not assign Edit and Edit.own privilege 
- neither to the usergroup **Manager** directly
- nor via their parents groups

(set everything to not-set or "inherited")
- this is soft-deny so that we allow further down 

Then give edit privelege **for a specific article to the manager usergroup** via
- either directly (edit the article as super admin and give edit to **usergroup Manager**)
- or do same for the category of the article (edit the article as super admin and give edit to usergroup Manager)

#### Expected result
If a "manager" user logins to backend and tries to edit it, then he will be able to do so

#### Actual result
The article manager indeed lists it as editable, but clicking on it , edit is denied

#### System information (as much as possible)
J3.6.1 / J3.6.2

#### Additional comments
Problem is with new code at **allowEdit()** method of **(backend) article controler**
i had made a comment directly on the code about the problem,
- but i should have opened and issue ?

Here is my comment
https://github.com/joomla/joomla-cms/commit/fd72a9fb0ee8f54513ca436c27da7c4d8fb8feed#commitcomment-18521573

Fix is obvious, 
and code seemed obviously wrong,
- just i was hesitant to insist that code is bad, without testing, so i think i opened this issue a little too late as J3.6.2 has been released

at least fix is easy

**Comment by ggppdk** [comment]
At least this is not a security issue,

Instead it is a usability issue for sites that 
- use ACL with soft deny **and allow editing specific categories**

**Comment by infograf768** [comment]
Other ACL issue: https://issues.joomla.org/tracker/joomla-cms/11466<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11463">issues.joomla.org/joomla-cms/11463</a>.</sub>

**Comment by sanderpotjer** [comment]
I can confirm the same issue, reported by several users of my extension meanwhile. 

The code change in https://github.com/joomla/joomla-cms/commit/fd72a9fb0ee8f54513ca436c27da7c4d8fb8feed#diff-64d86da3f57caa0ed222b746c070879eR89 caused this issue.

Basically it is checking for `JFactory::getUser()->authorise('core.edit', 'com_content);` and directly returning false, without taking the category or article level permissions into account. 

Not sure why `return parent::allowEdit($data, $key);` was moved from the bottom of the function to the current position.

A simple solution would be to revert to the previous situation with the check at the bottom of the function after checking the article level. But that only works if @wilsonge didn't had a specific reason to move the check?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11463">issues.joomla.org/joomla-cms/11463</a>.</sub>

**Comment by ggppdk** [comment]
Actually:

we need to do:
return parent::allowEdit($data, $key); 

Only if we do not find any asset to check
- that is the article id is zero (new article ) only then

maybe they we trying to fix the above !!

So this:
https://github.com/joomla/joomla-cms/blob/fd72a9fb0ee8f54513ca436c27da7c4d8fb8feed/administrator/components/com_content/controllers/article.php#L89-L94

```
// If we get a deny at the component level, we cannot override here.
if (!parent::allowEdit($data, $key))
{
		return false;
}
```

Should be:
```
// If we get a deny at the component level, we cannot override here.
if (!$recordid)
{
	return parent::allowEdit($data, $key);
}
```

**Comment by ggppdk** [comment]
@sanderpotjer 

please replace code with:

```
// Use component (parent permissions) if we do not have an asset for checking
// Note: in general "allowEdit" should not be used for new records, but anyway calculate it correctly
if (!$recordid)
{
    return parent::allowEdit($data, $key);
}
```

**test it should work**, and then someone can make a PR

**Comment by mbabker** [comment]
The change was in response to a reported and verified security issue so please take into consideration that even though the fix may not be 100% there is not an option to just revert it in full.

**Comment by ggppdk** [comment]
Yes tried to guess what exactly they were trying to fix

whatever it was (i have an idea)
 it is was certainly done the wrong way, since it cancels the way ACL heritage is supposed to work

**Comment by sanderpotjer** [comment]
My guess it was related to https://developer.joomla.org/security-centre/652-20160801-core-core-acl-violations.html

Not sure if there is any other information that can be shared about the security issue? So a proper solution can be found for both the security issue as the bug that is introduced now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11463">issues.joomla.org/joomla-cms/11463</a>.</sub>

**Comment by ggppdk** [comment]
ok i was guessing something like this

that someone "posts" a different owner but that is not the place to fix it, 
- the posted data should never be trusted to contain the owner !!

````
protected function allowEdit($data = array(), $key = 'id')
```

you either zero $data['created_by'] before calling allowEdit
or you
remove this line to avoid it:
```
https://github.com/joomla/joomla-cms/blob/fd72a9fb0ee8f54513ca436c27da7c4d8fb8feed/administrator/components/com_content/controllers/article.php#L106
```

**argeuably  the above line is not needed at all**, 
why it is not needed because:

- we only care for current owner of the record and not of the owner after any saving completes
- if you want to really caclculate an "edit" for new records then you should only consider current user id

**Comment by ggppdk** [comment]
So better fixes:
1. either zero $data['created_by'] before calling allowEdit() (since you are supposed to pass reliable $data)
2. or remove usage of $data['created_by'] 

and here i am still guessing what was fixed, i do not know exactly what was "fixed"

**Comment by ggppdk** [comment]
Also:

if edit is calculated on an existing article
then article already has an owner, the new owner after saving is not relevant for calculating current ACL

so can someone please comment and say when this line becomes useful ??:
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/controllers/article.php#L106

i do not use anything like it in my code and core.edit.own for existing records works fine
Again i am only guessing that this was the reason for the changes

**Comment by ggppdk** [comment]
I deleted my comments, i think better focus on a proper fix for next release,
and make a PR that can be tested

**Comment by ggppdk** [comment]
I will make a PR after i do some more studing and tests

**Comment by wilsonge** [comment]
Hey Both, grab me on my community email (george.wilson (a) community.joomla.org and I'll explain to you the issue that was fixed

**Comment by ggppdk** [comment]
Please test my PR
