### ISSUE TITLE
Captcha not appearing in contact form after update from 3.6.0 to 3.6.2

### ISSUE THREAD

**Issue by Elenchus** [joomla/joomla-cms#11464]
#### Steps to reproduce the issue
Update to 3.6.2 with 'Captcha - Recaptcha' set as the default Captcha in global configuration.

#### Expected result

The Captcha does not appear in the contact form.

#### System information (as much as possible)
Joomla 3.6.2 hosted on iPage.
EDIT: The template being used is Favourite by favthemes.

**Comment by infograf768** [comment]
Have you tested with Protostar?

**Comment by Elenchus** [comment]
Good call; I had not, and it works. I'll pass the problem on to favthemes instead.
