### ISSUE TITLE
update to 3.6.2 not possible because of backup: invalid security token

### ISSUE THREAD

**Issue by linpi1** [joomla/joomla-cms#11467]
#### Steps to reproduce the issue
if akeeba backup is installed and the plugin "backup on update" is published, often, the update process is stopped with the message:

"The most recent request was denied because it contained an invalid security token. Please refresh the page and try again." 

If one tries the update again, again a backup is made and the update process is stopped with the same message. The Joomla! update is only works when the plugin "backup on update" is disabled.

#### Expected result
Joomla! update to 3.6.2 + backup beforehand. 

#### Actual result
stop's after the backup. 

#### System information (as much as possible)
update from Joomla! 3.6.0 to 3.6.1 or to 3.6.2 with akeeba backup installed & the plugin "backup on update" enabled.

#### Additional comments
the plugin "backup on update" could check if a backup was made in the last hour, instead of continually making new backups and stopping the Joomla! update.

**Comment by andrepereiradasilva** [comment]
This repository is not for support with 3º party extensions.
Anyway update your akeeba backup before upgrading. See https://twitter.com/akeebabackup/status/761217053453758464
@brianteeman close?

**Comment by brianteeman** [comment]
Your copy of akeeba backup is out of date and you need to update it to 5.1.4 before you can update your Joomla installation

**Comment by linpi1** [comment]
in the case...yeap<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11467">issues.joomla.org/joomla-cms/11467</a>.</sub>
