### ISSUE TITLE
ACL edit.own does not work for Contacts and Newsfeeds

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#11466]
Not related to recent releases afaik. 

For Newsfeeds, it is clear. We do not even take care of `created_by` in the newsfeeds model `getListQuery()` method. This should be implemented from scratch.

But for Contacts, I was hoping it would work.

Test instructions:
Create a sub-group of Manager with the following permissions for Contacts:
![screen shot 2016-08-05 at 08 35 33](https://cloud.githubusercontent.com/assets/869724/17428277/a80918d4-5ae7-11e6-9c61-ee7213b7b5b4.png)

Access admin interface YES
Create YES
Delete NO
EDIT NO
EDIT STATE YES or NO
EDIT OWN YES

Log in back-end with a user member of that group

In Contacts Manager, create a new contact (You may not have permission to assign it to a user, but this is unrelated).
Save and Close that contact.

The contact is clickable in the Manager (Here the clickable one was created by this user)
![screen shot 2016-08-05 at 08 41 23](https://cloud.githubusercontent.com/assets/869724/17428404/7141ac8e-5ae8-11e6-9005-85865cafc7bc.png)

Result of click to edit:
![screen shot 2016-08-05 at 08 42 32](https://cloud.githubusercontent.com/assets/869724/17428426/9eadf0ce-5ae8-11e6-930c-702259850a87.png)

NOTE: It works fine for Articles with the same set of permissions. Did not test others.

**Comment by infograf768** [comment]
@ggppdk 
Can you confirm?

**Comment by ggppdk** [comment]
Yes, confirmed, tested and code review, edit not possible despite

both having core.edit.own and owning the contact record

**Comment by infograf768** [comment]
Looks like we need new permissions in the access.xml and changes in the controller for allowEdit() as it only takes care of category edit.
For newsfeeds, all code is missing. As well for weblinks.

**Comment by ggppdk** [comment]
Again in this case, it is not a security issue, but a **usability issue**,
- the owners should be allowed to edit the records, if having core.edit.own, but this is not checked

I can see why this was not added, it is because
- contacts, newsfeed, weblinks do not have individual assets

Thus you need core.edit.own checking is **a little different than e.g. articles**
1. Check core.edit.own on their category (instead of the contact, weblink, newsfeed)
2. Check owner (created_by property==current_user_id) as they do have this property

```
$recordId = (int) isset($data[$key]) ? $data[$key] : 0;
$categoryId = 0;

if ($categoryId)
{
	// The category has been set. Check the category permissions.
	return JFactory::getUser()->authorise('core.edit', $this->option . '.category.' . $categoryId);
}

// Since there is no asset tracking, revert to the component permissions.
return parent::allowEdit($data, $key);
```

Should be something like:

```
$recordId = (int) isset($data[$key]) ? $data[$key] : 0;
$categoryId = 0;

if ($categoryId)
{
	// First test if having core.edit on Category
	// If individual asset is added in the future then we need to check on the record itself)
	if ($user->authorise('core.edit', $this->option . '.category.' . $categoryId))
	{
		return true;
	}

	// Not having core.edit, test core.edit.own on the category
	if ($user->authorise('core.edit.own', $this->option . '.category.' . $categoryId))
	{
		// Now test the owner is the user,
		// NOTE: $data must be valid / secure ... otherwise should not be passed by the caller !
		$ownerId = (int) isset($data['created_by']) ? $data['created_by'] : 0;

		if (empty($ownerId) && $recordId)
		{
			// Need to do a lookup from the model.
			$record = $this->getModel()->getItem($recordId);

			if (empty($record))
			{
				return false;
			}

			$ownerId = $record->created_by;
		}

		// If the owner matches 'me' then permission is granted.
		if ($ownerId == $userId)
		{
			return true;
		}
	}
}

// Since there is no asset tracking, revert to the component permissions.
return parent::allowEdit($data, $key);
```

**Comment by infograf768** [comment]
I did not say it was a security issue. If it had been I would not have posted here.
I discovered these issues while working on the multilingual GSOC project

**Comment by infograf768** [comment]
your code does not work here.

**Comment by ggppdk** [comment]
> your code does not work here.

yes you are right,
someone should take time to make a PR and it will work, (it may need some small corrections)

i can do next days, (since this is not urgent and there are 3 controllers to patch), otherwise someone else can take time to do it now

**Comment by infograf768** [comment]
for newsfeeds, needs more work as even `created_by` is not fetched...

**Comment by ggppdk** [comment]
See the code above:

Propably code is same in all controllers:
This gets a model instance to get the owner id

```
            // Need to do a lookup from the model.
            $record = $this->getModel()->getItem($recordId);

            if (empty($record))
            {
                return false;
            }

            $ownerId = $record->created_by;
```

**Comment by infograf768** [comment]
I mean here:
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_newsfeeds/models/newsfeeds.php#L153-L160

**Comment by ggppdk** [comment]
I am not sure (without testing) but we speak of the
allowEdit() of the **singular controllers**:

components\com_contacts\controllers\contact.php
components\com_newsfeeds\controllers\newsfeed.php
components\com_weblinks\controllers\weblink.php

I think
```
$record = $this->getModel()->getItem($recordId);
```

will use:
components\com_contacts\models\contact.php
components\com_newsfeeds\models\newsfeed.php
components\com_weblinks\models\weblink.php

that already retrieve the **created_by property** ?

**Comment by infograf768** [comment]
without a correction in the model, we also get errors in the manager

**Comment by ggppdk** [comment]
> without a correction in the model, we also get errors in the manager

aaa yes you are right we need to get the created_by property to be retrieved by these plural models,
- for usage in "canEdit" calculation inside default.php of the backend lists

i see it is incomplete too only checking core.edit

e.g.
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_newsfeeds/views/newsfeeds/tmpl/default.php#L98
```
$canEdit    = $user->authorise('core.edit',       'com_newsfeeds.category.' . $item->catid);
```

should be:
````
$canEdit = $user->authorise('core.edit',       'com_newsfeeds.category.' . $item->catid) ||
	(
		$user->authorise('core.edit.edit', 'com_newsfeeds.category.' . $item->catid) &&
 		$item->created_by==$user->id
	);
```

**Comment by infograf768** [comment]
I suggest, if you can help, to solve the issue first with com_contacts with a specific PR (or first propose a .diff here). Would I guess be the same for weblinks.
Then it should be easy to go all over newsfeeds and implement it wherever needed.

**Comment by ggppdk** [comment]
Ok, this seems straghtforward, I will do today 1 PR for the 3 controllers and the 3 listing templates (i will update plurar models too), it will be more time to test this that to code it))

**Comment by andrepereiradasilva** [comment]
PR for newsfeeds is here https://github.com/joomla/joomla-cms/pull/11502 please test

**Comment by andrepereiradasilva** [comment]
PR for com_contact https://github.com/joomla/joomla-cms/pull/11503

**Comment by andrepereiradasilva** [comment]
weblinks PR https://github.com/joomla-extensions/weblinks/pull/255

**Comment by andrepereiradasilva** [comment]
cam be clsoed as there are 3 PR to test: https://github.com/joomla/joomla-cms/pull/11502 | https://github.com/joomla/joomla-cms/pull/11503 | https://github.com/joomla-extensions/weblinks/pull/255

**Comment by infograf768** [comment]
Closed as we have PRs<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11466">issues.joomla.org/joomla-cms/11466</a>.</sub>
