### ISSUE TITLE
Missing Placeholder/hint @ com_users/models/forms/registration.xml

### ISSUE THREAD

**Issue by sshcli** [joomla/joomla-cms#11479]
#### Steps to reproduce the issue
1. Go to: example.com/component/users/?view=registration
2. You will notice that there are no placeholder/hint. All fields are empty.

#### Expected result
All the fields should have a placeholder/hint.

#### Actual result
There are no placeholder/hint. All fields are empty.

#### System information (as much as possible)
Joomla 3.6.2
PHP 7.0.8
Apache 2.2.31
Google Chrome 52.0.2743.116 m

#### Additional comments
You can use a very generic text as placeholder/hint.
Joomla users can use language overrides if they want to change the text.

![screen shot 2016-08-05 at 10 21 54](https://issues.joomla.org/uploads/1/3f291e4e4c60361f3c17748e7b98681a.png)

**Comment by brianteeman** [comment]
Why? What is the purpose of adding the hints. They dont add anything for accessibility that is what the label is for <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11479">issues.joomla.org/joomla-cms/11479</a>.</sub>

**Comment by C-Lodder** [comment]
Placeholders are suppose to aid the user as to what should be entered in the input field. When there's enough space available, I always stay clear of placeholders in favour of bog standard labels, simple because placeholders can sometimes be a little deceiving. Placeholders are good if the format of the type of data isn't clear or there simply isn't enough space to add a label.

With the registration form, there's loads of space, therefore labels are already being used. The input fields for the registration form are very simple. Personally, I don't need Joomla to tell me how I need to format my name.

If you really want placeholders for a personal site, go for a Template Override.

**Comment by brianteeman** [comment]
@C-Lodder +10 plus there are lots of potential usability issues with placeholders so i dont see the need or benefit to change this in the core.

I will keep this open for a while to give @sshcli the opportunity to explain further but as @C-Lodder says if you really want this then you can create your own template override.

**Comment by dgt41** [comment]
In 3.7 you will be able to customise the fields the way you want them, as there will be on a layout file. simply copy the files from `/root/joomla/form/fields/*.`* to your `templates/your_template/html/` folder and do whatever pleases you

**Comment by sshcli** [comment]
I have my own template override.
This is only a suggestion.

Maybe google is wrong:
http://webpage.gq/google.PNG
http://webpage.gq/google2.PNG

**Comment by brianteeman** [comment]
Closing as this doesn't aid accessibility and can be achieved with template overides

**Comment by C-Lodder** [comment]
The only field I'd say that would be good to have a placeholder is the `password` field ** ONLY IF** you've set some requirements for the password, such as minimum characters, etc.

Each input on the Joomla registration form is standalone and are not split into sub-inputs (e.g First Name - Last Name). Each input has a dedicated label.

**Comment by sshcli** [comment]
Ok, understood.
No problem.
Regards,

**Comment by sshcli** [comment]
> @brianteeman said: that is what the label is for

Label should be visible when hover the mouse over the field

**Comment by brianteeman** [comment]
No thanks. Not going to reinvent the web
