### ISSUE TITLE
Back to Alias Date code doesn't work

### ISSUE THREAD

**Issue by visualtribe** [joomla/joomla-cms#11487]
#### Steps to reproduce the issue
Install and activate the plugin
See https://github.com/bertmert/plg_system_backtodatealias
Go make an Alias to a menu and don't put in date

#### Expected result
The date is added and when the Alias menu is clicked on page the date isn't shown, but the Alias menu name is shown in the url and page passes

#### Actual result
No date is added to the Alias area in the menu construction, won't let anything be created as menu already exits. If you put in the date, the menu doesn't work and wants to put in
http://sitename.com/?itemid=189
Page does not pass as this id call doesn't exist

#### System information (as much as possible)
Joomla 3.6.2

#### Additional comments
Go back to the way it was. This isn't an alias anymore. If I have several modules that should be on the page and the alias page, now I have to select all the menus and all the aliases. Before all I had to do is select the original menu items and it would also show up on the alias page. This other way is goofy and don't get why it was changed even reading the response I got. This other way is more work, more time consumed, and a waste of time.

**Comment by brianteeman** [comment]
This is the issue tracker for the core of joomla. the plugin you are referring to is not part of the core of joomla. Sorry we cant help you with it
