### ISSUE TITLE
Category list default_articles filter has no reset function, which effects permanently emptie lists!

### ISSUE THREAD

**Issue by Didldu-Florian** [joomla/joomla-cms#11499]
#### Steps to reproduce the issue
1st. Go to category list, put some filter keyword, which leads to no result.
Like: aasdasdasdasd

2nd. Than there will be no results with this message:

There are no articles in this category. 
If subcategories display on this page, they may contain articles.

#### The Problem is, 
when you go back to same category list, 
the filter is still active and the message remains.
But there´s no option to reset filter and no way, to get category list with all resuls back.
So it seems, that category list  is always without results because of filter is just active.

The only way ist, delet your cookies to get all results back.

#### Idea
The filter should be always displayed, also when no result is displayed or/and an additional reset form button ;)

#### System information (as much as possible)
Joomla! 3.6.2

**Comment by brianteeman** [comment]
Confirmed - never noticed it before but its definitely a usability error on sites that use this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11499">issues.joomla.org/joomla-cms/11499</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a pr for testing
