### ISSUE TITLE
Do not delete category on uninstalling extension

### ISSUE THREAD

**Issue by vijaykhollam** [joomla/joomla-cms#11490]
#### Steps to reproduce the issue
1. Install 3rd party extension that uses Joomla category manager.
2. Create category using that extesnsion.
3. Uninstall extension.
4. Install same extension again.
5. We can see that Category gets deleted with that extension.

#### Expected result
1. Joomla can have config at com_categories like Delete categories on uninstalling component
i.e Yes / No. By default, we can set it to YES.

**Comment by brianteeman** [comment]
Removingg data is the role of the extension. Some extensions do, some dont

**Comment by rdeutz** [comment]
Agreed that is the extensions job how it handles data and tables created by the component. Closing it because all what is needed to do it in one way or another is there for extensions developers.

**Comment by manojLondhe** [comment]
Looks like issue reported is about not removing data. I have observed this too - all extensions using Joomla's category manager face this issue.

Uninstalling that extension (for whatever reasons) results into Joomla deleting all related categories.

Consider a case - you installed some e-commerce extensions, created 100 categories. Uninstalled component for some reason, reinstall it, and you loose all category data. This could be the very frustrating experience.

**Comment by manojLondhe** [comment]
@brianteeman @rdeutz Is there a way to prevent this?

**Comment by brianteeman** [comment]
As it is a script in the extension doing that you would need to speak to
the developer of the extension. Personally I can't see a logical reason why
you would uninstall and extension and then reinstall it.

**Comment by manojLondhe** [comment]
Extensions use Joomla's category manager. When uninstalling extension Joomla removes all category data -

This is the Joomla code doing category removal -

File
`libraries/cms/installer/adapter/component.php`

Function
`public function uninstall($id)`

Code
```
// Remove categories for this component
$query->clear()
	->delete('#__categories')
	->where('extension=' . $db->quote($this->element), 'OR')
	->where('extension LIKE ' . $db->quote($this->element . '.%'));
$db->setQuery($query);
$db->execute();
```

For extension using Joomla category manager and which want to keep data after un-installation, this is a problem.

**Comment by ggppdk** [comment]
I confirm the code being there

> Removing data is the role of the extension
> Agreed that is the extensions job how it handles data and tables created by the component

So according to comments from both of you

the existing behaviour that Joomla deletes the categories is not proper,
- indeed if an extension asks you to keep data, and you say yes , and then you reinstall,
all data of the extension is there but extension's categories are gone, 

so this should be reopened, 

we need a way to set a flag for removing or not categories,
which by default it will be:  "Yes, remove" to avoid a B/C break, since current code of extensions assumes that Joomla will do the part of removing components categories

**Comment by vijaykhollam** [comment]
I think we should reopen this and discuss it.

**Comment by rdeutz** [comment]
Learned something new today. Tracked it back to 2013 and deleting categories when uninstalling a component is implemented since then. I am pretty sure that this wasn't the case at some point in history. I still think a component should be in control what data gets deleted when it get's uninstalled. As a extension developer I am in control of the database tables but as learned today not about the categories. I agree there should be an option but I think the right place is the manifest file.

**Comment by brianteeman** [comment]
Surprised and reopened

**Comment by ggppdk** [comment]
I have made a PR, we can close this and continue discussion there,
and see if my proposed way is more best choce
(i argue it is because it is more flexible than a flag at manifest file)

**Comment by parthlawate** [comment]
The category manager is a 'horizontal' infrastructure component.. The categories in there are 'owned' by components.. so it's only logical that the owner of the categories decide on its deletion.. I don't think this should be a default behavior at all.  We can provide a method that the component can use in its uninstall script if it needs to do a clean up

**Comment by eshiol** [comment]
I think the same of parthlawate.
Anyway JInstallerAdapterComponent::uninstall() has a bug. It deletes the categories but it doesn't delete the related assets.

**Comment by eshiol** [comment]
I written a workaround. Before uninstall the component, the script renames the extension field into the table #__categories, so JInstallerAdapterComponent::uninstall() doesn't delete the categories.
Before install the component, the script restores the extension field into the table #__categories, so the component finds the old categories.

class Com_MycomponentInstallerScript
{
	public function uninstall(JAdapterInstance $adapter)
	{
		$db = JFactory::getDbo();
		// Preserve categories for this component issue #11490
		$db->setQuery(
			$db->getQuery(true)
				->update('#__categories')
				->set('extension=CONCAT('.$db->q('!').',extension,'.$db->q('!').')')
				->where('extension='.$db->q('com_mycomponent'))
		)->execute();
	}

	function preflight($type, $parent)
	{
		if ($type == 'install')
		{
			$db = JFactory::getDbo();
			// Recovery categories for this component issue #11490
			$db->setQuery(
				$db->getQuery(true)
					->update('#__categories')
					->set('extension=SUBSTR(extension, 2, CHAR_LENGTH(extension) -2)')
					->where('extension='.$db->q('!com_mycomponent!'))
			)->execute();
		}
	}
}

**Comment by franz-wohlkoenig** [comment]
@eshiol can you make a PR to resolve this Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11490">issues.joomla.org/tracker/joomla-cms/11490</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened in the future if it is updated.
