### ISSUE TITLE
First menu item disappears when alias-ing invisible menu item

### ISSUE THREAD

**Issue by TheGrop** [joomla/joomla-cms#11506]
#### Steps to reproduce the issue
1. Create a menu item in the main menu
2. Set the menu item to not display in the menu (Link Type -> Display Menu - No).
3. Create another menu.
4. Add a menu item, and set its Menu Item Type to Menu Item Alias (System Links -> Menu Item Alias).
5. Set the Menu Item to the menu item created in step 1.
6. Go to the frontend, and go to the page both menu items point to.

#### Expected result
The visible menu item is set to "active", and every menu item of all menus is visible.

#### Actual result
The visible menu item is set to "active", but the first item of the first menu (the one with the invisible menu item) disappears.

#### System information (as much as possible)
Joomla   3.6.2
Apache	 2.2.16
PHP      5.6.17
MySQLi   5.5.38
Perl     5.20.2

#### Additional notes
You can work around this bug by making the invisible menu item alias the visible menu item (which is arguably more intuitive), this still is weird/unintended behaviour.

This is my first time reporting a bug, so I hope I provided enough information/chose the right priority/category. If any extra information is required, I'll be glad to provide it.

**Comment by TheGrop** [comment]
#### Addition
I ran a few other tests, and in some cases, the invisible menu item appeared, and none of the other menu items disappeared.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11506">issues.joomla.org/joomla-cms/11506</a>.</sub>

**Comment by brianteeman** [comment]
I have not been able to replicate this.

**Comment by TheGrop** [comment]
Hmm, I just created a new website and tried it again. However, it worked perfectly. I'm not sure why it works now, and didn't yesterday.

I guess this can be closed then.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11506">issues.joomla.org/joomla-cms/11506</a>.</sub>

**Comment by brianteeman** [comment]
Closed as requested
