### ISSUE TITLE
Error: Editing not allowed (ACL problem)

### ISSUE THREAD

**Issue by ggeorgg** [joomla/joomla-cms#11510]
#### Steps to reproduce the issue
I just updated my Joomla Version from 3.6.0 to 3.6.1 to 3.6.2. 
I have set up user group "leichtathletik" before who's parent group is "author".
I have put this group into the user access level "special" an created a category also called "leichtathletik" so that this user group is only able to create and edit articles in this category. 
Before these updates to Joomla 3.6.2 all worked fine but now (without changing anything else) users which are in the group "leichtathletik" are not able to edit their articles anymore and an error message is displayed. However they are still able to create articles under this category. 

#### System information (as much as possible)
Database: MySQLi
Joomla 3.6.2
PHP 7 CGI

Error Message when trying to edit an article which was created a minute ago by the same test user:
![errormessage](https://cloud.githubusercontent.com/assets/13244552/17465906/61b2df74-5d02-11e6-8898-9ee0b01b81b3.jpg)

Category Settings for leichtathletik
![categoryleichtathletik](https://cloud.githubusercontent.com/assets/13244552/17465936/533a9260-5d03-11e6-879a-5bb14b63ec8d.jpg)

Usergroup leichtathletik as child of author:
![usergroup](https://cloud.githubusercontent.com/assets/13244552/17465935/5339dcd0-5d03-11e6-8d28-f96fb0055a7d.jpg)

leichtathletik in user level special:
![userlevel](https://cloud.githubusercontent.com/assets/13244552/17465937/533b7068-5d03-11e6-8e40-50117dea6ad0.jpg)

Have there been changes in the recent updates that could affect these settings?
Can I provide more informations?

Kind regards
Georg

**Comment by ggppdk** [comment]
Probably you have this issue:

**Allow Edit after Soft deny is no longer possible (always denied) for Articles manager**

https://github.com/joomla/joomla-cms/issues/11463

there will probably be some fix in J3.6.3
you may test the PR that i will make or someone else will make for the issue

You may have to change configuration temporarily, 
- give "core.edit" at component level
- deny "core.edit" at all top level categories for users that should not have it
- give "core.edit.own" to sub-categories that users should have editable articles that they own

**Comment by ggppdk** [comment]
I have made a PR #11511 to fix the issue

you may test it,
please do not consider it a final fix or anything
it is just there for testing

**Comment by ggeorgg** [comment]
Fix works for me. Thanks a lot!

**Comment by matrix630307** [comment]
I can confirm this problem by a website that i be webmaster. I have here a lot of users, that can not work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11510">issues.joomla.org/joomla-cms/11510</a>.</sub>

**Comment by ggppdk** [comment]
@matrix630307 

please test the PR #11511
thanks

**Comment by JakubBadowski** [comment]
It works like harm!
thx a lot

Greatings from Kraków :)

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11510">issues.joomla.org/joomla-cms/11510</a>.</sub>

**Comment by zero-24** [comment]
@JakubBadowski it should be fixed with 3.6.3 that is in preperation for a release.

**Comment by JakubBadowski** [comment]
II see. I'll wait :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11510">issues.joomla.org/joomla-cms/11510</a>.</sub>

**Comment by zero-24** [comment]
if you want you can apply the chnages in https://github.com/joomla/joomla-cms/pull/11511 as this is merged it get overwritten by the next update.
