### ISSUE TITLE
Subform field not repeatable without 'min' and 'max'

### ISSUE THREAD

**Issue by n9iels** [joomla/joomla-cms#11519]
#### Steps to reproduce the issue
1. Go to mod_custom xml file (or another module, but we use mod_custom in this example), and add the following field to the parameters:
```xml
<fieldset name="test">
    <field
        name="field-name"
        type="subform"
        formsource="modules/mod_custom/example.xml"
        multiple="true"
        label="Subform Field"
        description="Subform Field Description" />
</fieldset>
```
2. Create the a file named `example.xml` in the folder `modules/mod_custom`, place this as content of that file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<form>
	<fieldset name="section1" label="Section1">
		<field name="example_text" type="text" label="Example Text" />
		<field name="example_textarea" type="textarea" label="Example Textarea" cols="40" rows="8" />
	</fieldset>
	<fieldset name="section2" label="Section2">
		<field name="example_list" type="list" default="1" class="advancedSelect" label="Example List">
			<option value="1">JYES</option>
			<option value="0">JNO</option>
		</field>
	</fieldset>
</form>
```
3. Create a new custom HTML module and go the tab "COM_MODULES_TEST_FIELDSET_LABEL". Click on the green plus button to add a new row to the custom fields. Notice it is impossible to add more than one field
4. Go back to the mod_custom xml file and change the parameter to:
```xml
<fieldset name="test">
	<field
		name="field-name"
		type="subform"
		formsource="modules/mod_custom/example.xml"
		multiple="true"
		min="0"
		max="5"
		label="Subform Field"
		description="Subform Field Description" />
</fieldset>
```
5. Go back to the Custom HTML module and notice now you can make up to 5 new rows for the subform field
#### Expected result
When there is no `min` or `max` value given, it seems logic that the numbers of rows that can be generated are infinite

#### Actual result
You can only make up to one new row for the subform field

#### System information (as much as possible)
Joomla! 3.6.2

**Comment by toniedw** [comment]
Does this solve your issue?

https://github.com/joomla/joomla-cms/pull/11158

**Comment by n9iels** [comment]
@toniedw yes that fixes my problem. I'm sorry for asking, forget to look for existing PR's.
Thanks :)

**Comment by olejenya** [comment]
hi , And what is the code to register the template in order to reach the parameters?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11519">issues.joomla.org/joomla-cms/11519</a>.</sub>

**Comment by olejenya** [comment]
Normal field type, it worked, but when I add the field type type = "modal_article", then the creation of a new slide, this type does not work. How to update the script that would work korektno dynamic types?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11519">issues.joomla.org/joomla-cms/11519</a>.</sub>
