### ISSUE TITLE
[J.3.6.2] Bug: Cannot Add Custom Module Position "example_top"

### ISSUE THREAD

**Issue by sshcli** [joomla/joomla-cms#11522]
#### Steps to reproduce the issue
1. Create a new module (Any Type)
2. Set Position to: example_topic_1 and save the module
3. Now edit the module an try to change the position to: example_top

#### Expected result
You should be able to add any custom module position.
  

#### Actual result
There is a conflict with the position name, Joomla won't let you add a new custom position if there is another with the same word at the beginning.

#### System information (as much as possible)
Joomla 3.6.2 + Protostar
PHP 7.0.9
Chrome 52.0.2743.116 m

**Comment by jeckodevelopment** [comment]
Cannot replicate.

**Steps**
1. Create a new module (eg. Custom) and assign it to a new position, called "test_1", Save & Close
2. Edit the module, changin the position to "test_2", Save & Close

It works

**System information (as much as possible)**
Joomla 3.6.2
PHP  5.6.23
Firefox 48.0

**Comment by sshcli** [comment]
@jeckodevelopment Please try with the exact example mentioned above
First: example_topic_1 
Then: example_top
In my example there is a match after the underscore: _top

**Comment by sshcli** [comment]
Ok.
Problem solved by deleting 523 trashed modules + clearing the browser cache + clearing the joomla cache + clearing the browser cookies
Thanks for your support.
Please close this item
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11522">issues.joomla.org/joomla-cms/11522</a>.</sub>

**Comment by brianteeman** [comment]
Closed as requested
