### ISSUE TITLE
Feature items filter to mod_articles_news 

### ISSUE THREAD

**Issue by nickyeoman** [joomla/joomla-cms#11539]
Created for my first pull request. 

#### Steps to reproduce the issue

When using the mod_articles_news module there isn't an option to filter featured articles (this feature exists for the mod_articles_latest module).  

#### Expected result

There should be the option to filter the featured articles.

**Comment by brianteeman** [comment]
Hi @nickyeoman you dont need to create an issue on the tracker if you are going to be creating a pull request on github. The system is clever enough to add all pull requests to the issue tracker.

**Comment by nickyeoman** [comment]
pull request here: https://github.com/joomla/joomla-cms/pull/11540<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11539">issues.joomla.org/joomla-cms/11539</a>.</sub>
