### ISSUE TITLE
force language in localize.xml doesn't work

### ISSUE THREAD

**Issue by arrowthemes** [joomla/joomla-cms#11538]
#### Steps to reproduce the issue
Unpack a new Joomla Installation
Before running the installation, open installation/localize.xml and set the following on line 3:

`<forceLang>ar-AA</forceLang>`

Run the installation

#### Expected result
The installation should run with the language of choice in <forceLang>

#### Actual result
The installation show your default Language

**Comment by brianteeman** [comment]
I just tested it with ar-AA, fr-FR, de-DE and all worked correctly

**Comment by brianteeman** [comment]
I am closing this as this time as not a bug. It can always be reopened if further information is provided to show otherwise
