### ISSUE TITLE
language switcher module problem and SEF rewrite problems J 3.6.0 --> J 3.6.2

### ISSUE THREAD

**Issue by ssnobben** [joomla/joomla-cms#11542]
#### Steps to reproduce the issue
I have a test site updated to Joomla 3.6.2 from J 3.6.0. 

After update to J 3.6.0 I have problems with the SEF rewrite multi language urls to work with a Joomla component. 

The SEFs and rewrite works in Joomla 3.6.0 with the old J 3.6.0 site.php file and I have traced down this to an error in the file in \libraries\cms\application\site.php. 

If I apply this old \libraries\cms\application\site.php file from Joomla 3.6.0 to the new J 3.6.2 site the SEFs for that Joomla component works b u t then instead the the Language Switcher module disappear.

Question: Is this a Joomla bug or what causes this behaviour that the Joomla language switcher disappears? What have changed between those two files?

#### Expected result
Language Module Switcher works and shows up as it should

#### Actual result
The Language Module Switcher doesnt show up

#### System information (as much as possible)

Joomla 3.6.0 and Joomla 3.6.2

#### Additional comments
See also #6253    #11470
Some previous things that could be related: https://www.ostraining.com/support-forum/joomla-support/language-code-url-causing-problems/

**Comment by brianteeman** [comment]
The last change to that file was in #9999 
Can you replicate the issue on a clean install with no extensions and a default template?

**Comment by brianteeman** [comment]
I cannot replicate this see the screenshot and movie below

![t bx](https://cloud.githubusercontent.com/assets/1296369/17551524/9516217c-5ef2-11e6-8248-d8df7dbd7940.png)

![mm](https://cloud.githubusercontent.com/assets/1296369/17551536/a366c114-5ef2-11e6-8cf4-139277f21196.gif)

**Comment by ssnobben** [comment]
Hi well I got this to work after some testing back and forth with changing the System - Language Filter ordering to first with the System - Language Code after it before System - SEF plg. 

So I dont know if this is a condition for the new code in J 3.6.2 that the System - Language Filter ordering to first before the System - SEF plgs. hmmm

**Comment by brianteeman** [comment]
Based on the comments on #9999 then I would agree that the changes made there have effected you

**Comment by andrepereiradasilva** [comment]
the order of the plugins is important.
the language filter now behaves like all other plugins.

See https://github.com/joomla/joomla-cms/pull/10344

**Comment by brianteeman** [comment]
Closed as expected behaviour
