### ISSUE TITLE
btn yes-no styling strange behaviour

### ISSUE THREAD

**Issue by webchun** [joomla/joomla-cms#11549]
#### Steps to reproduce the issue
![screen shot 2016-08-10 at 12 23 11](https://issues.joomla.org/uploads/1/b123621cece87fca44881dd3bb8425e6.gif)
- I'm using subform for my module parameters
- I have this code on my xml : 
```
<field name="items" type="subform" formsource="modules/mod_modulex/fields/item.xml" min="1" max="4" multiple="true" layout="joomla.form.field.subform.repeatable-table" groupByFieldset="true" label="Subform Field" description="Subform Field Description" />
```
- This is the content of the item.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<form>
<fieldset name="items_fieldset" label="Fields">
	<field
        	name="field_label"
        	type="text"
        	label="Text"
        	size="40" />
        <field name="field_is_required"
            type="radio"
            default="1"
            label="Required" class="btn-group btn-group-yesno">
                <option value="0">JNO</option>
                <option value="1">JYES</option>
            </field>
</fieldset>
</form>
```

#### Expected result
The button group yes-no styling works properly

#### Actual result

The button group yes-no styling working with the first item only. Sometimes it's working properly until the 5th child items

#### System information (as much as possible)

Joomla 3.6.2

#### Additional comments

**Comment by brianteeman** [comment]
Thank you for reporting this. It has already been reported #11299 so i am closing this here and ask that you post your findings in that issue
