### ISSUE TITLE
Tiny MCE related JS error when using ZOO

### ISSUE THREAD

**Issue by agata-wdd** [joomla/joomla-cms#11544]
#### Steps to reproduce the issue
Using YooTheme Zoo (with a related item field configured) and Joomla 3.6.2 and JCE

#### Expected result
When adding related items to an article (using a related field), a pop-up appears where you can select from among pre-configured items (for example by type) and after selecting an item, the pop-up closes and the item title appears within the field.

#### Actual result
The pop-up closes but the item doesn't get added within the field and it's accompanied by a Tiny MCE related Javascript error (in the file /components/com_jce/editor/tiny_mce/tiny_mce.js)

#### System information (as much as possible)
PHP Built On 	Darwin webdog.local 14.5.0 Darwin Kernel Version 14.5.0: Thu Jun 16 19:58:21 PDT 2016; root:xnu-2782.50.4~1/RELEASE_X86_64 x86_64
Database Version 	5.6.24-log
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.6.24
Web Server 	nginx/1.10.0
WebServer to PHP Interface 	fpm-fcgi
Joomla! Version 	Joomla! 3.6.2 Stable [ Noether ] 4-August-2016 23:41 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by brianteeman** [comment]
That's an error with the jce implementation of tinymve and not the one
provided by Joomla. They are different versions and you should contact jce
for sjpport
