### ISSUE TITLE
Showon working properly only with the first item of repeatable subform's child item

### ISSUE THREAD

**Issue by webchun** [joomla/joomla-cms#11548]
#### Steps to reproduce the issue

![screen shot 2016-08-10 at 11 33 06](https://issues.joomla.org/uploads/1/bc4bac0af7db416da9a1f86482e23a58.gif)
- I'm using subform for my module parameters
- I have this code on my xml : 

```
<field name="items" type="subform" formsource="modules/mod_modulex/fields/item.xml" min="1" max="4" multiple="true" layout="joomla.form.field.subform.repeatable-table" groupByFieldset="true" label="Subform Field" description="Subform Field Description" />
```
- This is the content of the item.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<form>
<fieldset name="items_fieldset" label="Fields">
    <field
        name="type"
        type="list"
        default="0"
        label="Type"
        description="Enter Type"
    >
        <option value="0">Small</option>
        <option value="1">Medium</option>
        <option value="2">Large</option>
    </field>

        <field name="for_large"
            type="text"
            label="Additional entry for large" showon="type:2" />
</fieldset>
</form>
```
#### Expected result

The field `for_large` is hidden until I choose 'Large' in the field `type`
#### Actual result

The field `for_large` is hidden for the first item only. When I add the second item and so on, the field is always showing up. See this gif cast attached below
#### System information (as much as possible)

Joomla 3.6.2

**Comment by webchun** [comment]
Is there any update on this issue? This issue also affects showon. Showon won't work for subform child too 
cc : @Fedik <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11548">issues.joomla.org/tracker/joomla-cms/11548</a>.</sub>

**Comment by Fedik** [comment]
nope, no update

**Comment by webchun** [comment]
it's too bad :( 
It's really hard to fix it?

**Comment by Fedik** [comment]
well, yes need some tricky changes in existing showon code,
I do not promise, but if I will have a more time I try check it

**Comment by webchun** [comment]
👍  I wish you will find a lot of time to work on joomla *pray to god ;)

**Comment by Fedik** [comment]
please test it #12511

**Comment by Fedik** [comment]
this can be closed

**Comment by brianteeman** [comment]
Closed as we have a pr
