### ISSUE TITLE
Locked out of module after error

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#11550]
#### Steps to reproduce the issue
After receiving the "your not allowed direct access to this module " error ( I was not accessing it improperly ) then click on the same module that you were denied.

#### Expected result
you will be able to continue editing the module

#### Actual result
clicking on the module to enter will simply result in a screen refresh.
no errors generated
duplicating the module allows you to edit the duplicate but not the original

#### System information (as much as possible)
[systeminfo-2016-08-10T20-37-45+00-00.txt](https://github.com/joomla/joomla-cms/files/412062/systeminfo-2016-08-10T20-37-45.00-00.txt)

**Comment by N6REJ** [comment]
clearing admin cache, relogging, all make no change.
checkmarking "edit" box and then clicking "edit" works.

**Comment by PhilETaylor** [comment]
this is part of a larger issue - browsers caching the internal redirect - discussed to death....

**Comment by ggppdk** [comment]
You can test this
https://github.com/joomla/joomla-cms/pull/10753

still what i do not like about my PR and any similar PR

is that it will **encourage server configurations that result in browser caching**,
and after accepting that PR it will be a B/C break to revert it ...

**Comment by brianteeman** [comment]
I am closing this as a duplicate
