### ISSUE TITLE
isis sub-menu items have transparent background

### ISSUE THREAD

**Issue by michwebdev** [joomla/joomla-cms#11559]
#### Steps to reproduce the issue
Navigate to a third level menu item in the administrator interface (e.g. Content -> Articles -> Add New Article).  

#### Expected result
Flyout menu link should appear with a solid background so that the underlying part of the interface does not show through it.

#### Actual result
Background, before hovering, is transparent and text is, depending on the location, unreadable or difficult to read.

#### System information (as much as possible)
Joomla:  3.6.2
Browser:  tested on Firefox (Mac/Win), Chrome (Mac), Safari
PHP Version 	5.5.14
Web Server 	Apache 

#### Additional comments
Adding a background color to the isis template.css file is a workaround. It might also be missing a background image.

File:  administrator/templates/isis/css/template.css
Either of these will do it but aren't exactly the fix:
.dropdown-menu > li > a {
	background-color: #fefefe;
}
.dropdown-menu li {
	background-color: #fefefe;
}

**Comment by brianteeman** [comment]
I can
not confirm  this or am I misunderstanding

![wmz3](https://cloud.githubusercontent.com/assets/1296369/17592272/85c14ebc-5fd9-11e6-90b6-e4bd4ac0d299.png)

**Comment by michwebdev** [comment]
Fixed:  I just did all of the updates and the one that seems to have fixed it is updating JA T3 Framework from 2.7.1  to 2.7.3.  I will test this on another site to confirm that was it.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11559">issues.joomla.org/joomla-cms/11559</a>.</sub>

**Comment by michwebdev** [comment]
I tried another site and upgrading JA T3 Framework from 2.7.2 to 2.7.3 resolved this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11559">issues.joomla.org/joomla-cms/11559</a>.</sub>

**Comment by brianteeman** [comment]
Closed as not a joomla issue
