### ISSUE TITLE
Menu item Alias generation broken in 3.6.2

### ISSUE THREAD

**Issue by Joomv** [joomla/joomla-cms#11552]
#### Steps to reproduce the issue
Create a menu item Alias with the same title as another full menu item.
Try to save

#### Expected result
Menu item alias creation creates a date stamp alias in the field and saves normally

#### Actual result
Menu item alias creation tries to create an alias based on the menu item title given, fails with warning alias already exists.
If you add a -1 or similar to the alias, the item saves and behaves like a normal menu item alias (i.e. doesn't use the alias you added.)

#### System information (as much as possible)
This happens on Joomla 3.6.0 and upwards

**Comment by brianteeman** [comment]
If I remember correctly this was a feature request

**Comment by andrepereiradasilva** [comment]
is not "broken", it now works like all the other menu items

**Comment by Joomv** [comment]
I've just found the other posts regarding it - I was searching open issues only pre-coffee.
Closing

**Comment by bertmert** [comment]
@Joomv 
A friend has published a small plugin that brings back the old behavior:
https://github.com/bertmert/plg_system_backtodatealias

**Comment by Joomv** [comment]
Thanks.  Although I can see why this was implemented, on a lot of my sites where you have multiple ACL levels and heavy use of the guest group - Aliases are essential.  Shall take a look at this plugin when I'm back next week.

**Comment by digglescreative** [comment]
Sure wish this feature change was never made. The old way is much more intuitive. The whole reason for making an alias is to take on the url of the item it points to.

@bertmert
The plug works nicely!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11552">issues.joomla.org/joomla-cms/11552</a>.</sub>
