### ISSUE TITLE
Name for Library

### ISSUE THREAD

**Issue by GeneticsPro** [joomla/joomla-cms#11567]
#### Steps to reproduce the issue
Now a name for the library, for example:
`<name>The Joomla!</name>`

And in the Extension Manager language file is ignored:
`if (!in_array($item->type, array('language', 'template', 'library')))
{
	$item->name = JText::_($item->name);
}`

#### Expected result
Library name:
`<name>lib_joomla</name>`

en-GB.lib_joomla.sys.ini:
`LIB_JOOMLA="The Joomla!"`

`if (!in_array($item->type, array('language', 'template')))
{
	$item->name = JText::_($item->name);
}`

#### Additional comments
Joomla Library - is only an example.

**Comment by zero-24** [comment]
see: https://github.com/joomla/joomla-cms/pull/11595

**Comment by zero-24** [comment]
I have completly removed that check.

**Comment by zero-24** [comment]
So both is possible using <name>My Lib Name</name> and <name>lib_joomla</name>

**Comment by zero-24** [comment]
Set to "closed" on behalf of @zero-24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11567">issues.joomla.org/joomla-cms/11567</a>

**Comment by zero-24** [comment]
Closing as there is a PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11567">issues.joomla.org/joomla-cms/11567</a>.</sub>
