### ISSUE TITLE
Tag Description Global Setting Not Working

### ISSUE THREAD

**Issue by rgblogs** [joomla/joomla-cms#11566]
#### Steps to reproduce the issue

1. Create Joomla tag (lest say XYZ) and add some description to it.
2. In the tag component options, under List All Tags -> Tag Descriptions, set to Hide.
3. Create a menu item, Tags -> List of all Tags, select parent tag as XYZ. Under options, Tag Description should be set to Global.

#### Expected result

Tag description should not be visible in list of all tags.

However, changing Menu option Tag Descriptions to Hide, works but Global does not work.

**Comment by brianteeman** [comment]
I am unable to replicate this - all works fine for me (if I understood correctly)

See https://www.dropbox.com/s/ia8e0f5008onw01/11566.mp4?dl=0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11566">issues.joomla.org/joomla-cms/11566</a>.</sub>

**Comment by rgblogs** [comment]
I have set in menu item, to Global
In tag options, Hide.

Still it is showing tag descriptions. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11566">issues.joomla.org/joomla-cms/11566</a>.</sub>

**Comment by brianteeman** [comment]
Are you testing with protostar as I did?
Do you have cache disabled?

**Comment by brianteeman** [comment]
I am closing this at this time due to lack of reply. It can always be reopened if updated
