### ISSUE TITLE
Problem in getting filtered input

### ISSUE THREAD

**Issue by hardiktailored** [joomla/joomla-cms#11569]
#### Steps to reproduce the issue

Use any existing form or create a form with a text field.
Pass input value mixed with character and integer multiple times like "test123test456" and submit.
Get input value of form field using input filtering method getInt() like below:
$integer = JFactory::getApplication->input->getInt( 'name_of_input_field' );

OR

(1) Open this file of your Joomla: components/com_search/controller.php
(2) Add below line in search() method as first line (Line: 46)
echo $this->input->getInt('searchword', null); die;
(3) Go to front-end of your joomla site and type "test123test456" in Joomla search input.
Above will show the filtered value submitted by search input.

#### Expected result

Variable should return "123456" as we have filtered integer values only 

#### Actual result

But actually it returns "123" only. Means it returns first integer value occurrence only.

#### System information (as much as possible)

Joomla! 3.6.3-dev

#### Additional comments

The problem is in clean() method of libraries/joomla/filter/input.php library file.

I found that preg_match() returns only first occurrence on line no:167 for the input value.

Alternatively we can use pattern like below:
$pattern = '/[^-+0-9]/';

and preg_match() should replace with preg_replace() like below:
$matches = preg_replace($pattern, '', (string) $source);

Same issue I found with UINT case too.

**Comment by hardiktailored** [comment]
PR for this issue #11582 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11569">issues.joomla.org/joomla-cms/11569</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a pr for testing see #11569

**Comment by hardiktailored** [comment]
@brianteeman the PR link is #11582. Please update PR link in your comment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11569">issues.joomla.org/joomla-cms/11569</a>.</sub>

**Comment by brianteeman** [comment]
Oops - done

**Comment by photodude** [comment]
Please also open an issue/PR with the Framework filter package. https://github.com/joomla-framework/filter

(the CMS has some slight differences from the Framework package that it extends).

**Comment by photodude** [comment]
@mbabker and or @wilsonge would possibly have insights into why we only match the first int substring. 

I'm sure that only match the first int substring was an intentional design choice. (as evident in the Unit tests)

**Comment by mbabker** [comment]
Don't ask me.  That API predates me.
