### ISSUE TITLE
Different domain for https

### ISSUE THREAD

**Issue by bettinz** [joomla/joomla-cms#11574]
#### Steps to reproduce the issue

Use a proxy for www cname, like cloudflare, without support for https. You have support for https only on domain without www
example: 
1. http://www.example.com -> is working
2. http://example.com -> is working
3. https://www.example.com -> is not working
4. https://example.com->is working

Now, this is the request: automatically switch between two domains, based on port request.
So, if I force https on system configuration only for joomla administration, and I wrote http://www.example.com/administrator it automatically switch to https://example.com/administrator
If I wrote https://example.com it automatically switch to http://www.example.com (if I force https only for administrator and not the whole site).

#### Expected result

Switch between different domains based on http vs https

#### System information (as much as possible)

Tested with Joomla 3.6.2

#### Additional comments

It's not a bug, it's a feature request

**Comment by brianteeman** [comment]
> You have support for https only on domain without www

how did you do that. I've only ever been able to get cf working on www

**Comment by bettinz** [comment]
this is my situation:
http://www.example.com ->point to cloudflare
http://example.com ->redirect to http://www.example.com
https://www.example.com ->doesn't work
https://example.com ->work because it doesn't use cloudflare but the certificate installed on my domain.
I don't use cloudflare dns service (full service), but I use partial dns:
https://support.cloudflare.com/hc/en-us/articles/203685674-Full-DNS-setup-versus-Partial-CNAME-setup
I think this is applicable on full service either (if you don't use the certificate provided by cloudflare)

**Comment by brianteeman** [comment]
I had to stop using cloudflare because they only really support www and
using their ssl certificate

**Comment by bettinz** [comment]
Yes, but you can use the domani without www for secure connections. I think for example to:
Pre-login:
http://www.example.com/login
Post request to 
https://example.com/login and https://example.com

I've seen an e-commerce system using for example https only for cart, login and payment and it switch between the two domains based on http or https request

**Comment by PhilETaylor** [comment]
A login page on http posting to https is insecure. You should not do this - period.

**Comment by bettinz** [comment]
Hello PhilETaylor, this is what I mean:
http://doc.prestashop.com/display/PS16/Setting+a+shop's+URL

**Comment by PhilETaylor** [comment]
@bettinz Doesn't mean its right. Doesn't mean its best practice. Doesn't mean its secure! 

Do you research (start in google) and you will see hosting a login page on http and posting to https is highly frowned upon by those of us that know better.  

"Critical Mistake #1: Non-HTTPS Login pages (even if submitting to a HTTPS page)."
https://blogs.msdn.microsoft.com/ie/2005/04/20/tls-and-ssl-in-the-real-world/

"Your login form posts to HTTPS, but you blew it when you loaded it over HTTP"
https://www.troyhunt.com/your-login-form-posts-to-https-but-you/

**Comment by mbabker** [comment]
A few things:

1) Technically `www.example.com` is a subdomain of `example.com` so it is correct that applications treat this as requests for two different domains; this is generally why most well configured sites enforce www. prefixes or remove them through .htaccess rules.

2) As Phil pointed out, this isn't secure by any measure.  When there is any endpoint in the chain that does not enforce HTTPS connections, it compromises the entire operation's security.

3) It's a bad idea in general to only use HTTPS on some pages of your site and HTTP on others.  The entire site should be one way or the other (preferably HTTPS, especially if you're collecting customer data in any form).

**Comment by bettinz** [comment]
Some ideas:
If www.site.tld is the website, and https://site.tld/login is the login page, so the form is already in an https page. I don't understand why you talking about mix http/https.
I also don't understand why is it different from the actual option to enable https only for administrator: when I write http://www.site.tld/administrator there is automatically a redirect to https://www.site.tld/administrator.

This issue wasn't about activate ssl for some website parts (it was a last minute idea in my first message). The issue was about to use https for a domain, and http for another. I don't understand why https://secure.domain.tld and http://www.domain.tld is so strange. Many sites have a subdomain with https for customer area and login things (register, password reminder, etc). 
It's a waste of resources to use https for all site: if I've a blog and I login on frontpage, why do I need https for index page and articles page?
It's perfectly accepted to use http://www.domain.tld for the website and https://domain.tld for login page. Again, the login form is already on login page, so it's not http->to ->https. We're login inside https page.

**Comment by PhilETaylor** [comment]
> It's a waste of resources to use https for all site

 /facepalm - stop living in the 1990s! 

Some bedtime reading for you.

- https://www.maxcdn.com/blog/ssl-performance-myth/

- https://googlewebmastercentral.blogspot.co.uk/2014/08/https-as-ranking-signal.html

- http://motherboard.vice.com/read/google-will-soon-shame-all-websites-that-are-unencrypted-chrome-https

**Comment by andrepereiradasilva** [comment]
one more to read
https://security.googleblog.com/2016/09/moving-towards-more-secure-web.html

**Comment by PhilETaylor** [comment]
@andrepereiradasilva that was the one I was trying to find before when trying to explain that passwords over http wrong :) thanks - I'll bookmark it now.

**Comment by andrepereiradasilva** [comment]
another one https://istlsfastyet.com/

**Comment by PhilETaylor** [comment]
thats already in my list above:)

**Comment by bettinz** [comment]
Thank you guys, I have something to read 😄

**Comment by brianteeman** [comment]
I am closing this
