### ISSUE TITLE
Trying to get property of non-object in ...\modules\mod_menu\mod_menu.php on line 20

### ISSUE THREAD

**Issue by internetovaskola** [joomla/joomla-cms#11586]
Notice: Trying to get property of non-object in ...\modules\mod_menu\mod_menu.php on line 20

**Comment by brianteeman** [comment]
There really is nothing we can do with that information

Which version of Joomla are you using?
Is this with one of the default templates?
If not which template?
Is there anything that we can do to reproduce this error<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11586">issues.joomla.org/joomla-cms/11586</a>.</sub>

**Comment by zero-24** [comment]
if you use the last version of joomla you can't hit such error in the Frontend or the backend please double check that you have all files in place. If yes please contact the forum.

**Comment by internetovaskola** [comment]
Yes, on the default Joomla Installation and with default template, there is not problem. Problem is elsewhere. Sorry for the issue.

**Comment by brianteeman** [comment]
Closed
