### ISSUE TITLE
ISIS Admin Menu ill-behaved on mobile browser

### ISSUE THREAD

**Issue by ibrentlam** [joomla/joomla-cms#11613]
#### Steps to reproduce the issue
From Android or iPhone, log into the admin area with default isis template
Select Components
Select any component, such as "news feed"

#### Expected result
New Feed Admin area displayed

#### Actual result
Menu closes back to top-level

#### System information (as much as possible)
J 3.6.2, vanilla everything:

System Information
Setting 	Value
 
PHP Built On 	Linux ip-10-230-207-138 4.4.15-25.57.amzn1.x86_64 #1 SMP Wed Jul 27 22:37:49 UTC 2016 x86_64
Database Version 	5.6.30
Database Collation 	latin1_swedish_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.6.24
Web Server 	Apache/2.4.23 (Amazon) OpenSSL/1.0.1k-fips PHP/5.6.24
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.6.2 Stable [ Noether ] 4-August-2016 23:41 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0

#### Additional comments
Reproducible on Chrome on Android and Safari on iPhone.

**Comment by brianteeman** [comment]
Thank you for reporting this. It has already been reported and we have a pull request that needs testsing https://issues.joomla.org/tracker/joomla-cms/11528
