### ISSUE TITLE
Unable to do admin login

### ISSUE THREAD

**Issue by tusharraka17** [joomla/joomla-cms#11622]
### Steps to reproduce the issue
1. Trying to login at the below address-
www.jbims.edu/administrator

It is giving error - "You need to login"
I am entering the correct username and password, still no luck.

Kindly help. It is very very urgent.

### Expected result

The login should happen and the dashboard should be visible.

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.jooml.org

**Comment by brianteeman** [comment]
Sorry I made a typo

Http://forum.joomla.org
