### ISSUE TITLE
Unable to log in to admin

### ISSUE THREAD

**Issue by HitkoDev** [joomla/joomla-cms#11620]
### Steps to reproduce the issue
Update from 3.6.0 to 3.6.2

### Expected result
Successful update

### Actual result
Joomla! updated, but after the season expires it won't let me log in any more

### System information (as much as possible)
Tried on php 5.6 and 7.0, Debian x64

### Additional comments
Got the same result on clean install

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.jooml.org
