### ISSUE TITLE
Category permission tab display incorrect string

### ISSUE THREAD

**Issue by yild** [joomla/joomla-cms#11625]
### Steps to reproduce the issue

Go to articles -> edit/new -> permission tab, check permissions note below.

There will be text 'Changes apply to this article only. (...)'.

Then go to categories -> edit/new -> permission tab, check permissions note below.

And you will see same text.

### Expected result

Category permission tab should display key JLIB_RULES_SETTING_NOTES_ITEM from xx-XX.com_categories.ini.

### Actual result

Category permission tab use key JLIB_RULES_SETTING_NOTES_ITEM from xx-XX.com_content.ini.

### System information (as much as possible)

Joomla staging ( from 20 mins ago ).

**Comment by brianteeman** [comment]
Thanks for reporting this but its already been reported see #11306

**Comment by yild** [comment]
ok :)
