### ISSUE TITLE
[tests] Bug in run test for memcache/memcached in PR #11565

### ISSUE THREAD

**Issue by csthomas** [joomla/joomla-cms#11634]
### Steps to reproduce the issue
1. Create a test env for php, php-memcached and hhvm and apply PR #11565.

2. sudo service memcached restart

3. View libraries/vendor/phpunit/phpunit/phpunit. It should start like:
`#!/usr/bin/env php`

4. Run `libraries/vendor/phpunit/phpunit/phpunit tests/unit/suites/libraries/joomla/cache/storage/JCacheStorageMemcachedTest`
> PHPUnit 4.8.24 by Sebastian Bergmann and contributors.
> Warning:        The Xdebug extension is not loaded
>                 No code coverage will be generated.
> 
> .......
> 
> Time: 5.08 seconds, Memory: 8.00MB
> 
> OK (7 tests, 17 assertions)

5. Edit `libraries/vendor/phpunit/phpunit/phpunit` and replace first like from php to hhvm.
Should be: `#!/usr/bin/env hhvm`

6. Run `libraries/vendor/phpunit/phpunit/phpunit tests/unit/suites/libraries/joomla/cache/storage/JCacheStorageMemcacheTest`
> PHPUnit 4.8.24 by Sebastian Bergmann and contributors.
> Warning:        The Xdebug extension is not loaded
>                 No code coverage will be generated.
> 
> 
> Fatal error: [] operator not supported for strings in libraries/joomla/cache/storage/memcache.php on line 194

7. Run `sudo service memcached restart`

8. (The same as point 6) Run `libraries/vendor/phpunit/phpunit/phpunit tests/unit/suites/libraries/joomla/cache/storage/JCacheStorageMemcacheTest`
> PHPUnit 4.8.24 by Sebastian Bergmann and contributors.
> Warning:        The Xdebug extension is not loaded
>                 No code coverage will be generated.
> 
> .......
> 
> Time: 9.17 seconds, Memory: 28.64MB
> 
> OK (7 tests, 17 assertions)

### Expected result

Memcache Test for HHVM should pass on PR #11565

### Actual result
 but did not pass because it was run after memcached storage did test which left empty array in memcached server.

I suggest to restart memcached server before each memcache/memcached tests.

#### Summary

Memcache storage test fails if memcached server has value from memcached tests.

https://travis-ci.org/joomla/joomla-cms/jobs/152511380

**Comment by photodude** [comment]
I agree, it doesn't make a lot of sense that we are not resetting caching servers prior to each Unit test being run. 

The suggested fix might be something to add to my PR relating to memory management of the unit tests. https://github.com/joomla/joomla-cms/pull/10685

**Comment by csthomas** [comment]
I thought it would solve the problem 
but on second thought I would not force users to reset server after change cache handler between memcache and memcached.

Then this issue may be incorrect.
I have plan to add new change to memcache storage and strict check if `$index` is array.

**Comment by photodude** [comment]
What you proposed was forcing the unit test to rest the cache handler between unit tests. 

Since unit tests should be independent and isolated, resetting the cache handler between the tests makes sense as in maintains the isolation between tests. 

(On a side note: on the user end, either a strict check for array and handling that case, or the array_push() I suggested ensures the end users don't run into a fatal error related to MEMCACHE::get.)

**Comment by csthomas** [comment]
If you want to do reset cache then please create (IMHO) a new PR for that.

I too new in unit tests.

**Comment by csthomas** [comment]
I close that  because PR #11565 fix that problem.
