### ISSUE TITLE
Search function in install from web does not return correct results

### ISSUE THREAD

**Issue by kalemanzi** [joomla/joomla-cms#11639]
### Steps to reproduce the issue
Try searching for an extension by name in the web installed tab. I searched for "JCE" , "Joomla content editor", "simple image gallery" etc. I've attached some screenshots after search was done:

![screen shot 2016-08-17 at 10 19 18 am](https://cloud.githubusercontent.com/assets/5723384/17729383/4635dada-6464-11e6-8d79-c4d02ea5b8dc.png)
![screen shot 2016-08-17 at 10 18 58 am](https://cloud.githubusercontent.com/assets/5723384/17729384/4662d864-6464-11e6-9b25-0f10d1950b71.png)
![screen shot 2016-08-17 at 10 18 14 am](https://cloud.githubusercontent.com/assets/5723384/17729385/4667ff1a-6464-11e6-983b-fd533cb36d4f.png)

### Expected result
The record which has the closest match should end up on top, eg. JCE Editors' listings as well as JCE related plugins, or something that at least contains the string. 

### Actual result
Heaps of non related extensions, with no mention of the original search string in the results.

### System information (as much as possible)
Vanilla install of Joomla 3.x. As far as I can remember, this is an issue with all the Joomla versions that has the web installer.

### Additional comments
I don't have a solution or PR for this yet, but want to get into the code and see if I can improve the search so that it actually works. 

I don't know how many people use the feature, but it has frustrated me so much in the past, especially when setting up a new site, that I just went and downloaded the extensions direct form the developer sites and did not bother to use the web installer.

**Comment by jeckodevelopment** [comment]
I can confirm the issue.

### 1st attempt
Keyword: **Simple Image Gallery**
Expected result: Simple Image Gallery extension as first result
Actual result: Akeeba Backup

![webinst01](https://cloud.githubusercontent.com/assets/733133/17734757/89b78960-647e-11e6-86c5-1cb3fcc9f045.PNG)

### 2nd attempt
Keyword: **Joomla Content Editor**
Expected result: JCE extension as first result
Actual result: Akeeba Backup

![webinst02](https://cloud.githubusercontent.com/assets/733133/17734786/aaa1041c-647e-11e6-9231-4bbeffdba62b.PNG)

### 3rd attempt
Keyword: **JCE**
Expected result: JCE extension as first result
Actual result: Easy Blog as first result. JCE mediabox is displayed as 5th result, JCE is 6th.

![webinst03](https://cloud.githubusercontent.com/assets/733133/17734793/bc062944-647e-11e6-9e1c-00306c433cd5.PNG)

**Comment by andrepereiradasilva** [comment]
i think install from web plugin has it's own github repository
https://github.com/joomla-extensions/install-from-web-client/issues

so imo this issue should be wrote there.

**Comment by kalemanzi** [comment]
@jeckodevelopment you will notice I changed the filter to sort by name but still got same result.
Thanks @andrepereiradasilva I was not aware that there is a seperate repo for that. If that is the correct place to create an issue, I will create a new one over there.

**Comment by brianteeman** [comment]
Closing here. Please create the issue on the other repo
