### ISSUE TITLE
301 redirect for language filter should be 302

### ISSUE THREAD

**Issue by chivitli** [joomla/joomla-cms#11633]
It seems there is an issue with 301 redirect for the default language. When hreflang annotations are used to indicate different language version, there is usually also x-default hreflang for the homepage. But if you 301 redirect homepage then it seems search engine is detecting a broken chain of hreflangs. Check answer at https://productforums.google.com/forum/?utm_medium=email&utm_source=footer#!msg/webmasters/BuLYKloslbc/I9BzIiYBBAAJ, specifically paragraph about redirection, the rest is not relevant here

This was already worked on in #11329 and some other prs

**Comment by andrepereiradasilva** [comment]
I read the comment and don't understand how it's related to the redirect HTTP code.

The hreflang code you're referring cames from here: https://github.com/joomla/joomla-cms/blob/staging/plugins/system/languagefilter/languagefilter.php#L770

**Comment by chivitli** [comment]
Actually, it seems the issue is because x-default should point to a page that returns http code 200, and not redirect. So in this case x-default should be example.com/default-lang-code (if it's not set to be removed). More info at https://hreflang.org/redirects-canonicals-cause-hreflang-problems/ and https://hreflang.org/redirection-and-international-seo/

**Comment by andrepereiradasilva** [comment]
so, for what i understand from your comments, the only thing is here is the x-default.

**Comment by andrepereiradasilva** [comment]
i have:
```html
	<link href="http://domain.tld/index.php/pt/" rel="alternate" hreflang="pt-PT" />
	<link href="http://domain.tld/index.php/es/" rel="alternate" hreflang="es-ES" />
	<link href="http://domain.tld/index.php/en/" rel="alternate" hreflang="en-GB" />
	<link href="http://domain.tld/index.php/en/" rel="alternate" hreflang="x-default" />
```

**Comment by andrepereiradasilva** [comment]
so, doesn't seem a issue to me?

can you check ?

**Comment by chivitli** [comment]
Issue came from another module that did the override of what language filter plugin does. Sorry for wasting your time, I will close this bug report.

**Comment by andrepereiradasilva** [comment]
ok np
