### ISSUE TITLE
Category Links are Broken with New Routing

### ISSUE THREAD

**Issue by Chraneco** [joomla/joomla-cms#11637]
While trying to implement the new routing for JoomGallery I detected this problem:

### Steps to reproduce the issue

1. Set up a site with the "Blog" sample data.
2. Create a new content menu item of type "List All Categories" and with "Root" as the category selection.
3. When clicking on that menu item you get to a page with two links ("Uncategorised" and "Blog").
4. Verify that both links work as expected.
5. Turn on the new routing for the content component.
6. Click again on the created menu item.
7. The link for "Uncategorised" is now broken as it simple references the current page you are on.

### Expected result

All links should still work as before

### Actual result

Links from the "categories" view are broken.

### System information (as much as possible)

Tested with latest code from the 3.7.x branch.

### Additional Comments

The "Blog" link still works because it is also the default menu item, I think if more categories were listed on that page all those links would be broken.

**Comment by bertmert** [comment]
Already reported here:
Please see test results of PR https://github.com/joomla/joomla-cms/pull/11320

**Comment by wilsonge** [comment]
Fixed with https://github.com/joomla/joomla-cms/commit/0553f436d6db3f51df789e13c869c357352edcdb
