### ISSUE TITLE
[/libraries/cms/application/cms.php] has non-optimal code

### ISSUE THREAD

**Issue by nvyush** [joomla/joomla-cms#11643]
### Steps to reproduce the issue
1) Open the file /libraries/cms/application/cms.php
2) Search function login($credentials, $options = array())
3) Search lines (819 - 826):
```
			$authorisations = $authenticate->authorise($response, $options);

			foreach ($authorisations as $authorisation)
			{
				$denied_states = array(JAuthentication::STATUS_EXPIRED, JAuthentication::STATUS_DENIED);

				if (in_array($authorisation->status, $denied_states))
				{
```

### Expected result
IMHO that will be better this way:
```
			$authorisations = $authenticate->authorise($response, $options);
			$denied_states = JAuthentication::STATUS_EXPIRED | JAuthentication::STATUS_DENIED;

			foreach ($authorisations as $authorisation)
			{
				if ((int)$authorisation->status & $denied_states)
				{
```

### System information (as much as possible)
Joomla! 3.6.2

### Additional comments
1) Bitwise operations more effective than array(...) and in_array().
2) `$denied_states = array(...)` is inside of the cycle, but value of $denied_states is invariable, so will be better to move the initialisation of it before of the cycle.

**Comment by zero-24** [comment]
Can you send your code change as pull request? That makes testing much more easy. If you need help please have a look here: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11643">issues.joomla.org/joomla-cms/11643</a>.</sub>

**Comment by zero-24** [comment]
Thanks :+1:

**Comment by zero-24** [comment]
Set to "closed" on behalf of @zero-24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11643">issues.joomla.org/joomla-cms/11643</a>

**Comment by zero-24** [comment]
Closing as we have a pull request https://github.com/joomla/joomla-cms/pull/11655<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11643">issues.joomla.org/joomla-cms/11643</a>.</sub>
