### ISSUE TITLE
Permissions tab is selected

### ISSUE THREAD

**Issue by BurtNL** [joomla/joomla-cms#11648]
I noticed in 3.6.3.-dev, in Global Configuration, when you click a topic such as 'Contacts', the permissions tab is selected. This counts for many - but not all - topics in the left hand column.
It would be more convinient if the first tab is automatically selected.
### Steps to reproduce the issue

Install 3.6.3-dev and have a look around in the Global Configuration.

![screen shot 2016-08-17 at 12 11 35](https://issues.joomla.org/uploads/1/9d9ae99ed63160a2e95a157bc8799fa8.png)

**Comment by brianteeman** [comment]
Clear your cache and your cookies and please try again :)

**Comment by BurtNL** [comment]
Clear the caches in Joomla and cleared my browser cache and cookies: permissions tab is still selected on some, but not all, topics.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11648">issues.joomla.org/joomla-cms/11648</a>.</sub>

**Comment by bertmert** [comment]
I confirm this issue. FF47.0.

- Closed Joomla tab after logout.
- Truncated #__session.
- Deleted all cookies.
- deleted all caches.

logged into back-end > Global Configuration > Clicked links from top on in left sidebar.
Articles OK (first tabulator active).
Banners: Permissions.

- Clicked this and that:
Several other entries: Tab Permissions. Some other entries: OK (as far as I remember e.g.menus).
Click Articles again: Now tab Permissions. > Clicked second tab (Editing Layout) > Clicked Banners in sidebar > Clicked Articles again: Now first tab (Articles)

Confusing behavior.

**Comment by brianteeman** [comment]
If i remember this correctly it is the tab-state.js that is causing this. it tries to "save" which tab you are on. Some components only have a permissions tab so as soon as you visit one like that and see the permissions tab and move to a new component you will get the same permissions tab even if it has more than one tab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11648">issues.joomla.org/joomla-cms/11648</a>.</sub>

**Comment by bertmert** [comment]
The """problem""" is that tabs are "jumping weirdly". Sometimes it's Permissions, then the first tab, then another one. Then you think "now it should be _Editing Layout_ when you'll come back or maybe Permissions" but it's the first tab. Like a lottery. I don't care who wins ;-)

**Comment by dgt41** [comment]
Please test #11658

**Comment by brianteeman** [comment]
Closed as we have a PR for testing

**Comment by brianteeman** [comment]
Reopened the issue as #11658 has been closed

**Comment by andrepereiradasilva** [comment]
please try https://github.com/joomla/joomla-cms/pull/11708 maybe this is the problem

**Comment by BurtNL** [comment]
@andrepereiradasilva You are right, that's something else and it doesn't solve this issue.
Besides that, I noticed the same problem is already visible in the current 3.6.2-version.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11648">issues.joomla.org/joomla-cms/11648</a>.</sub>

**Comment by eshiol** [comment]
PR: #12503

**Comment by andrepereiradasilva** [comment]
@brianteeman can we close this as we have a PR?
