### ISSUE TITLE
ACL article edit permissions not inherited by Category

### ISSUE THREAD

**Issue by starlingDesign** [joomla/joomla-cms#11650]
This is going to be brief because I just spent 45 minutes typing out a detailed version and this site errored and lost it

### Steps to reproduce the issue
1. New Joomla 3.6.2 install w/default sample data
2. Add new group 'sectionA' w/parent Registered
3. Edit Access Level 'Special' and add new group 'sectionA'
4. Edit Global Configuration -> Permissions and set group 'sectionA' -> Administrator Login = Allowed
5. Add new Category 'bobsBlog' and set Permissions for 'sectionA' all to Allowed (create, edit, etc)
6. Add a new article and save it in the new category 'bobsBlog'
6. Add new user 'Bob' and put him in the new group 'sectionA' (be sure to activate him)
7. Log into the administration area with Bob and try to edit the new article

### Expected result
Bob should be able to edit any article in the category.

### Actual result
Bob gets an error message "Error Edit not permitted"

### System information (as much as possible)
PHP Built On	Darwin SDC-iMac 14.5.0 Darwin Kernel Version 14.5.0: Thu Jun 16 19:58:21 PDT 2016; root:xnu-2782.50.4~1/RELEASE_X86_64 x86_64
Database Version	5.5.42
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.10
Web Server	Apache/2.2.29 (Unix) mod_wsgi/3.4 Python/2.7.8 PHP/5.6.10 mod_ssl/2.2.29 OpenSSL/0.9.8zg DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.8 Perl/v5.20.0
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.6.2 Stable [ Noether ] 4-August-2016 23:41 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

### Additional comments
Bob can create a new article, but as soon as you save it the first time, he can no longer save it again or edit it after closing.

~~edit~~
I should add that the article can be edited and saved from the front end, so the issue is only with the admin side.

**Comment by ggppdk** [comment]
Hello

> Add new Category 'bobsBlog' and set Permissions for 'sectionA' all to Allowed (create, edit, etc)

yes that will not work in J3.6.2 (it is broken), **if no edit at the component level** (soft deny)
then adding it later at a specific category  will not work
- you get an edit link in article manager but clicking it , will deny edit

Test this PR  (already merged for J3.6.3)
https://github.com/joomla/joomla-cms/pull/11511

**Comment by starlingDesign** [comment]
Thanks so much for that - I applied the 2 files in the PR and the issue is solved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11650">issues.joomla.org/joomla-cms/11650</a>.</sub>

**Comment by zero-24** [comment]
Set to "closed" on behalf of @zero-24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11650">issues.joomla.org/joomla-cms/11650</a>

**Comment by zero-24** [comment]
Closed. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11650">issues.joomla.org/joomla-cms/11650</a>.</sub>
