### ISSUE TITLE
Allow custom fields to Categories via plugins

### ISSUE THREAD

**Issue by mattillston** [joomla/joomla-cms#11669]
We need to be able to extend the standard Joomla category information, but it seems like it is not possible without hacking the core.

Is this something that is in the pipeline?

**Comment by schnuti** [comment]
This is possible as is.
1. Follow [Adding_custom_fields_to_core_components_using_a_plugin](https://docs.joomla.org/Adding_custom_fields_to_core_components_using_a_plugin)
2. For categories it's even easier in your own custom component.  You just add a file category.xml and this is added to the form. (I've used this myself)
3.  I do not know if categories are included in the planned extra fields functionality. You can read more here
[custom-fields](https://github.com/joomla-projects/custom-fields)

**Comment by brianteeman** [comment]
I am closing this as asked and answered
