### ISSUE TITLE
Typo 'com_users.user.' in "components\com_users\views\profile\view.html.php"

### ISSUE THREAD

**Issue by YHartonuk** [joomla/joomla-cms#11666]
### Steps to reproduce the issue

Typo in "components\com_users\views\profile\view.html.php" that cause not working tags for com_users profile view. In the line 79 writen "$this->data->tags->getItemTags('com_users.user.', $this->data->id);" but must be "$this->data->tags->getItemTags('com_users.user', $this->data->id);" Also in default_custom.php tmpl there is no code for tags so tags fields will not work in user profile view.

### Expected result

$this->data->tags->getItemTags('com_users.user', $this->data->id);

### Actual result

$this->data->tags->getItemTags('com_users.user.', $this->data->id);

### System information (as much as possible)

Joomla! 3.6.2

**Comment by bertmert** [comment]
@YHartonuk 
Please test https://github.com/joomla/joomla-cms/pull/11681
concerning typo.

**Comment by andrepereiradasilva** [comment]
@brianteeman i think this can be closed as we have a PR for testing

**Comment by bertmert** [comment]
@zero-24 
Could you please reopen this issue. After an additional find of @andrepereiradasilva (https://github.com/joomla/joomla-cms/pull/11681#issuecomment-241290527) I reflected to much on com_tags to be sure what I'm doing and why. In both cases I think these lines can be removed because they are unnecessary but ???
https://github.com/joomla/joomla-cms/pull/11681#issuecomment-241290527

**Comment by zero-24** [comment]
Done<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11666">issues.joomla.org/joomla-cms/11666</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@bertmert both cases seems a bug to me see https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/helper/tags.php#L386

**Comment by bertmert** [comment]
Yes I know but as I sayed I think these lines are completely unnecessary. When I fix the typo in com_content we get an **unnecessarily populated** array instead of an empty one. So, fixing the typo just to fix it and get an unnecessary overhead is not a good solution.

**Comment by bertmert** [comment]
com_users: I would prefer to remove the whole incomplete tags (un)logic from this component instead of fixing a single typo.

Means: Should be discussed (or somebody should take over).

**Comment by YHartonuk** [comment]
Please don't remove this lines from com_users because I use tags for users profile. Please just fix typo.

**Comment by bertmert** [comment]
@YHartonuk 
You can provide a PR. It's really easy:
https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

(I don't see a way to use tags in com_users without core hacks. Maybe I'm wrong.)

**Comment by YHartonuk** [comment]
I use my custom plugin for user profile and custom com_users view for my theme so I don't use any hack for joomla core

**Comment by franz-wohlkoenig** [comment]
@YHartonuk can you make a PR so this Issue get resolved?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11666">issues.joomla.org/tracker/joomla-cms/11666</a>.</sub>

**Comment by alikon** [comment]
easy pr made
maybe @YHartonuk  can test with his custom extension

**Comment by franz-wohlkoenig** [comment]
closed as PR made, thanks @alikon <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11666">issues.joomla.org/tracker/joomla-cms/11666</a>.</sub>
