### ISSUE TITLE
Bundled FOF 2.4.3 is out of date and incompatible with PHP 7

### ISSUE THREAD

**Issue by nikosdion** [joomla/joomla-cms#11672]
### Steps to reproduce the issue

Look in libraries/fof/version.txt

### Expected result

Version 2.5.4 or later, published this year (last version of FOF).

### Actual result

Version 2.4.3 from last year.

### System information (as much as possible)

Irrelevant.

### Additional comments

I only opened this issue so I can file the PR with the up to date FOF version.

**Comment by brianteeman** [comment]
> I only opened this issue so I can file the PR with the up to date FOF version.

There is no need to do that.
