### ISSUE TITLE
404 error for menu items only after Joomla 3.6.0 update and 3.6.2 update

### ISSUE THREAD

**Issue by tracylee3124** [joomla/joomla-cms#11678]
### Steps to reproduce the issue
I don't know how to reproduce the issue. I have other sites and they did not do this. It is on one site only and it did it the last time they had an update. I use the button that asks me to update when I get notified of a update, I click update after backing up my files. All seems to be well until I click the menus and I get a 404. I rebuilt the menus, I clicked the fix database. I am probably going to have to go back to the old version if I can even get that working.

**Comment by brianteeman** [comment]
I am closing this here as the best place for you to post this type of question is on the forum http://forum.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11678">issues.joomla.org/joomla-cms/11678</a>.</sub>
