### ISSUE TITLE
too many emails from plugin updatenotification

### ISSUE THREAD

**Issue by rebecca2** [joomla/joomla-cms#11707]
The plugin sends multiple update reminders per day . If the frequency of the notifications to make adjustable per backend? From daily to once a week for example ?

**Comment by brianteeman** [comment]
Yes this is configurable and the text has been made clearer to explain that #11147

**Comment by zero-24** [comment]
Yes you can but there is no reason to not update.

There are multible ways:
Go to Backend -> Extensions -> manage -> Options -> Updates Caching (in hours) => max is 24
Or you disable that Plugin => No Mails
