### ISSUE TITLE
Category blog always shows 2 columns no matters what blog/featured options are set

### ISSUE THREAD

**Issue by mlstoppa** [joomla/joomla-cms#11712]
### Steps to reproduce the issue
- create a "category blog" menu item, leaving blog layout options unset
- set blog/featured options as:
# Leading Articles: 1 (or whatever except 2)
# Intro Articles: (whatever you want)
# Columns: 3 (or whatever except 2)
# Links: (whatever you want)

### Expected result
1 leading article that fits the whole page width, 0 to many intro articles distributed over specified columns number

### Actual result
all category articles distributed over 2 columns

### System information (as much as possible)
- both Joomla version 3.5.1 and 3.6.0
- both specific template ("Meet Gavern") and Joomla standard (beez3 and protostar)
- 2 different Joomla installations on 2 different servers

### Additional comments
That's an example page:
http://www.sosdislessia-ferrara.it/joomla2/per-insegnanti-e-tutor/65-tutor-per-dsa

Thank you

**Comment by brianteeman** [comment]
Can you replicate this on a clean install of joomla?

Obviously this is a very basic feature of joomla so if it is really a bug in the core of joomla we would expect to have a considerable number of reports<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11712">issues.joomla.org/joomla-cms/11712</a>.</sub>

**Comment by jeckodevelopment** [comment]
@mlstoppa did you check the menu item settings?

**Comment by brianteeman** [comment]
I have downloaded the same template that you have and it works perfectly.

I am closing this as not a core joomla bug. Please use the forum for support http://forum.joomla.org

**Comment by mlstoppa** [comment]
Yes, I checked it and also I tried with different values.
I am wondering where else these values may arise from.
Thank you
Il 22/Ago/2016 12:37, "Luca Marzo" <notifications@github.com> ha scritto:

**Comment by mlstoppa** [comment]
Sorry, I couldn't do the try you asked before you.
I  have already tried writing to joomla forum without success, so I  will
go on with further investigation.
Thank you
Il 22/Ago/2016 12:47, "Brian Teeman" <notifications@github.com> ha scritto:
