### ISSUE TITLE
Root menu item select is paginated, doesn't load all menu items.

### ISSUE THREAD

**Issue by usematics** [joomla/joomla-cms#11734]
### Steps to reproduce the issue
Menu with more items that the current pagination limit (100 menu items, pagination at 25)
Create new menu item
Choose menu
Select root menu item

### Expected result
All menu items apear or load, so you can select any menu item as parent.

### Actual result
On selecting the root menu item, only the first 25 menu items of the chosen menu will show up, even if searching won't get elements after the 25th item. 

If you increase the pagination limit it will show more elements up to the pagination limit. 

### System information (as much as possible)
Joomla! 3.6.2

### Additional comments

I have been seeing this problems in the last week. I have a very big menus in 3 languages, and i get the problem regarding of the menu, when I increase the pagination limit I can see the rest of the items.

**Comment by brianteeman** [comment]
Assuming I have understood you correctly I can not replicate this

![menu](https://cloud.githubusercontent.com/assets/1296369/17872304/5b8af5d0-68b7-11e6-97e9-6eb070f2c99e.gif)

**Comment by usematics** [comment]
yes thats what I was saying. I didn't do it on a clean copy is a live site with other stuff installed. After trying to re-replicate, if you have the large menu selected it will show all the items, but if you select an other long menu or the same, the async call seems to use the pagination. [screen video...](https://www.opentest.co/share/be429dc068cd11e6aafc697df8fe7c98 "https://www.opentest.co/share/be429dc068cd11e6aafc697df8fe7c98")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11734">issues.joomla.org/joomla-cms/11734</a>.</sub>

**Comment by brianteeman** [comment]
I can confirm that when you change the selected menu then the entire list of menu items does not get loaded<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11734">issues.joomla.org/joomla-cms/11734</a>.</sub>

**Comment by brianteeman** [comment]
Please test #12510<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11734">issues.joomla.org/tracker/joomla-cms/11734</a>.</sub>
