### ISSUE TITLE
Hreflang Tag links mismatch

### ISSUE THREAD

**Issue by v912485** [joomla/joomla-cms#11759]
### Steps to reproduce the issue
- Create a multi language site with 2 languages
- In global config enable "Unicode Aliases"
- Create a page in 2 languages and associate both the menus and articles
- Make sure the alias of one page has a special character. For instance 'é'.
- View the html source for both pages and compare the hreflang meta tags

### Expected result
- The URLs should be identical.

### Actual result
- One URL is in UTF-8 the other is URL encoded.

### System information (as much as possible)
Joomla 3.6.2 on a Ubuntu server.

### Additional comments
The problem appears to be in the languagefilter.php file of the language filter plugin.
Different methods are used to generate the URLs, JUri::getInstance->toString and JRoute. One produces UTF-8 URLs and the other a URL encoded.

I have notice this problem when Google Webmaster Tools highlighted it. It reported the following errors:
- International Targeting | Language > 'es' - no return tags
- 29 Hreflang Tags with Errors

**Comment by infograf768** [comment]
Do you mean:
When the page displayed is in English (no accents), we get
```
<link href="http://localhost:8888/testwindows/trunkgitnew/fr/instructions-multilangue/33-ultimes-vérifications.html" rel="alternate" hreflang="fr-FR" />
<link href="http://localhost:8888/testwindows/trunkgitnew/en/multi-lingual-steps-by-steps/34-last-checks.html" rel="alternate" hreflang="en-GB" />
```

and when the page is in French (with accents)
```
<link href="http://localhost:8888/testwindows/trunkgitnew/fr/instructions-multilangue/33-ultimes-v%C3%A9rifications.html" rel="alternate" hreflang="fr-FR" />
<link href="http://localhost:8888/testwindows/trunkgitnew/en/multi-lingual-steps-by-steps/34-last-checks.html" rel="alternate" hreflang="en-GB" />
```

If this is your case, Google Webmaster Tools is an idiot as both  `33-ultimes-vérifications.html` and `33-ultimes-v%C3%A9rifications.html` are the same.

We can normalise this in Joomla, for the $base as well as the hreflang.
I will make a patch to always get `33-ultimes-vérifications.html`

**Comment by infograf768** [comment]
Please test
https://github.com/joomla/joomla-cms/pull/11769

**Comment by zero-24** [comment]
So we can close here @infograf768

**Comment by brianteeman** [comment]
Closed as we have a pr

**Comment by v912485** [comment]
@infograf768 Thank you! This is indeed the issue and I agree that Google should not report it as an error.
