### ISSUE TITLE
'Enter' in field navigates back to article manager

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#11765]
### Steps to reproduce the issue
1. Create new article in article manager
2. Enter a title
3. Click in to any field excluding the article editor (Eg. Image and Links -> Link A)
4. Hit Enter (even after adding data)

### Expected result
Nothing

### Actual result
Navigates back to article manager, losing article

### System information
Joomla 3.6.2

### Additional comments
Maybe there is a good reason for this however I am failing to see one. Out of habit it is very easy for a user to hit enter after adding data to a field. Do this after composing an article and your article will be lost. Just seems like bad UI/UX?

**Comment by brianteeman** [comment]
> out of habit it is very easy for a user to hit enter after adding data to a field. 

Maybe on a non web based form but on a web based form you would have to disable the keypress in a field for that to happen

https://www.google.co.uk/search?sourceid=chrome-psyapi2&ion=1&espv=2&ie=UTF-8&q=disable%20enter%20on%20a%20form&oq=enter%20on%20a%20form&aqs=chrome.1.69i57j0l5.6791j0j7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11765">issues.joomla.org/joomla-cms/11765</a>.</sub>

**Comment by ciar4n** [comment]
I realise disabling the keypress is a non runner. Hitting enter defaulting to cancelling the document seems questionable thou.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11765">issues.joomla.org/joomla-cms/11765</a>.</sub>

**Comment by brianteeman** [comment]
Sorry I missed that part. Thats a definite bug<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11765">issues.joomla.org/joomla-cms/11765</a>.</sub>

**Comment by ciar4n** [comment]
Strangely the issue appears to be related to the 'user' field (Publishing tab), specifically the following hidden button which is rendered from an override in the Isis template..

```
<button class="btn" data-dismiss="modal">Cancel</button>
```

You will find the issue is also present when creating a new category which also includes this field. I can create a PR removing the 'cancel' text which does resolve the issue however this points to the correct solution been elsewhere. Anyone more familiar with the Isis template I suspect would have a better solution?) If not I will go ahead and create the PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11765">issues.joomla.org/joomla-cms/11765</a>.</sub>

**Comment by brianteeman** [comment]
Good find. Let's start by creating the pr. It usually helps to reveal any
other issues.

**Comment by brianteeman** [comment]
Closed as we have a pr for testing see #11782
