### ISSUE TITLE
Can't rename file with template manager

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#11773]
### Steps to reproduce the issue
Go to the template manager and select one of the templates
On the toolbar select new file and create a new file eg brian.php
Now select the newly created file and on the toolbar select rename file and try to give it a new name eg simon.php

### Expected result
File is renamed to simon.php

### Actual result
Invalid file name. Please choose a file name containing a-z, A-Z, 0-9, - and _.

### System information (as much as possible)
Tested on 3.6.2 and current staging

**Comment by C-Lodder** [comment]
This is because you need to type in the file name only, not the extension (`.php` in this case). If you simply type in "simon", it will work.

I'll submit a PR for this

**Comment by C-Lodder** [comment]
Half done but a little stuck on passing the file name extension through `JLayoutHelper::render('joomla.modal.main', $renameModalData);`

**Comment by brianteeman** [comment]
Good spot - closing
