### ISSUE TITLE
Menu items batch selection problem

### ISSUE THREAD

**Issue by yild** [joomla/joomla-cms#11777]
### Steps to reproduce the issue

Log in to Joomla backend,
go to All menu items, select menu item(s), click 'Batch' you will see 
"To use batch processing, please first select a Menu in the manager." message in modal window.
Now add new menu item, select some items click batch - modal window will open with batch options.

Logout -> login and again select some items and open batch window, "To use batch processing, please first select a Menu in the manager." will show up.

### Expected result

Batch process modal window with batch options even if single menu item is selected.

### Actual result

Batch process modal window with batch options showing up only after adding new menu item.

### System information (as much as possible)

Joomla 3.6.2

**Comment by brianteeman** [comment]
Either I am doing something wrong or I cannot replicate your issue

It is expected behaviour that if you are on ALL MENU ITEMS ie you have not selected a menu then the batch functionality is disabled but if you have selected a MENU (not an item) then it is enabled

**Comment by yild** [comment]
ok, my mistake, nvm, closing
