### ISSUE TITLE
[PDO Mysql Strict Mode] Unable to save content if finder plugins enabled.

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#11771]
### Steps to reproduce the issue

This is similar issue as the one solved in https://github.com/joomla/joomla-cms/pull/9380, https://github.com/joomla/joomla-cms/issues/9455 and https://github.com/joomla/joomla-cms/issues/9457.

1. Use latest staging
2. Set the database driver as "PDO (MySQL)" in global configuration.
3. Set  "PDO (MySQL)" to strict mode (See note below)
4. Make sure finder plugins are enabled
5. Go to "Content" -> "Articles" and try to edit and save a content.
6. Error. can't save.

#### Set  "PDO (MySQL)" to strict mode

Replace this line: https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/database/driver/pdomysql.php#L155
With the following code:
```php
$this->connection->query("SET @@SESSION.sql_mode = 'STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';");
```

#### Expected result

Content saved,

#### Actual result

![image](https://cloud.githubusercontent.com/assets/9630530/17929146/833b91da-69f6-11e6-94c1-bc3d7e271fbc.png)

![image](https://cloud.githubusercontent.com/assets/9630530/17929149/864f9182-69f6-11e6-8867-456e7a3097f8.png)

#### System information (as much as possible)

Latest staging.

**Comment by andrepereiradasilva** [comment]
@zero-24 @alikon @waader transfered the discussion about the pdo mysql strict mode here.

> Maybe we should add a comment to the hack in the driver?

Maybe a deprecated 4.0 comment?

@mbabker what do you think? The joomla framework still uses the strict mode right?

**Comment by mbabker** [comment]
The statement is not executed at all in the Framework.

**Comment by andrepereiradasilva** [comment]
> The statement is not executed at all in the Framework.

AFAIK that means that in the framework you get the default value for strict mode in which mysql version you're using.

**Comment by mbabker** [comment]
Yep

**Comment by franz-wohlkoenig** [comment]
@andrepereiradasilva should this issue stay open?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11771">issues.joomla.org/tracker/joomla-cms/11771</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened in the future if it is updated.
