### ISSUE TITLE
JS Unit tests - incorrect jQuery UI version

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#11775]
Joomla is shipped with jQuery UI **1.9.2**.

According to the [package.json](https://github.com/joomla/joomla-cms/blob/staging/tests/javascript/package.json#L19), tests are run with **1.11.4**

**Comment by brianteeman** [comment]
confirmed

**Comment by zero-24** [comment]
Can you guys have a look here @yvesh @Ruchiranga ?

Maybe similiar issues / reasons as https://github.com/joomla/joomla-cms/issues/11602

**Comment by Ruchiranga** [comment]
The jquery-ui-bundle node package we have used does not provide the jQuery UI 1.9.2 version. So we had to go ahead with what was available.

**Comment by brianteeman** [comment]
The same comments as in #11602 - if we are running tests then they must be on the same version or the tests lose validity. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11775">issues.joomla.org/joomla-cms/11775</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a PR
