### ISSUE TITLE
[com_search] Category creation date not displaying in results

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#11783]
### Steps to reproduce the issue
Use com_search component.
Search for a word that is present in a category description and in some articles.

### Expected result
Should show date of creation of category in results.

### Actual result
Doesn't show date of creation of category. 
But displays it for articles, as expected.

### System information (as much as possible)
Joomla 3.6.2

**Comment by infograf768** [comment]
Can you test by exchanging these lines?
```
diff --git a/plugins/search/categories/categories.php b/plugins/search/categories/categories.php
index 89593ce..5613a49 100644
--- a/plugins/search/categories/categories.php
+++ b/plugins/search/categories/categories.php
@@ -155,5 +155,5 @@
 		$case_when .= ' ELSE ';
 		$case_when .= $a_id . ' END as slug';
-		$query->select('a.title, a.description AS text, \'\' AS created, \'2\' AS browsernav, a.id AS catid, ' . $case_when)
+		$query->select('a.title, a.description AS text, a.created_time AS created, \'2\' AS browsernav, a.id AS catid, ' . $case_when)
 			->from('#__categories AS a')
 			->where(
@@ -161,5 +161,5 @@
 				. $db->quote('com_content') . 'AND a.access IN (' . $groups . ')'
 			)
-			->group('a.id, a.title, a.description, a.alias')
+			->group('a.id, a.title, a.description, a.alias, a.created_time')
 			->order($order);
 
```

**Comment by ghazal** [comment]
I'd say : nickel chrome !
In other words, it works all right.
I guess you should do a PR for this.
Anyway, thanks.

**Comment by infograf768** [comment]
Please confirm patch
https://github.com/joomla/joomla-cms/pull/11802

**Comment by infograf768** [comment]
Closed as we have a patch

https://github.com/joomla/joomla-cms/pull/11802<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11783">issues.joomla.org/joomla-cms/11783</a>.</sub>
