### ISSUE TITLE
Password Options ignored when autocreating a password

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#11798]
### Steps to reproduce the issue

In the admin go to the users options and the passwords tab. Set some options such as 5 symbols, 6 digits and 7 uppercase characters

Try to create a user in the admin or front end with a simple password such as 123456 and you can not because  of the options that you set.

Now in the admin create a new user but do NOT create a password. This should create the user and email the username and password to the user
### Expected result

Password generated in the email will conform to the settings in the user component options
### Actual result

Random 9 character password

**Comment by RonakParmar** [comment]
I have follow above steps and able to reproduce this issue. Auto generated password is not as per my settings.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11798">issues.joomla.org/joomla-cms/11798</a>.</sub>

**Comment by bhavikTailored** [comment]
- I have follow above steps, auto generated password is not working as per admin settings.
- ![screen shot 2016-08-26 at 02 17 41](https://issues.joomla.org/uploads/1/b22c8dfb3549c6ed86b33cf0f33ae99d.png)
- ![screen shot 2016-08-26 at 02 18 55](https://issues.joomla.org/uploads/1/8f827df4fe63838c1298d7afedebd121.png)

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11798">issues.joomla.org/joomla-cms/11798</a>.</sub>

**Comment by zero-24** [comment]
Hmm maybe we should enable PW reset automagic if we generate a PW as well as generate a 32 char random passwort?

**Comment by brianteeman** [comment]
@zero-24 no - we should just make sure that an autogenerated password follows the same rules as defined in the options as a user created password

**Comment by jeckodevelopment** [comment]
yes, never noticed this before. But I agree with Brian.
If you setup a password policy in the backend, it must be respected if you choose to generate automatically password.

**Comment by mbabker** [comment]
It's not so easy to do that because the random passwords are coming in by way of `random_bytes()` (and appropriate PHP 5 backports).  It's somewhat hard to create random strings with certain guidelines when you don't have full control over the randomizing functions.

**Comment by jeckodevelopment** [comment]
uhm... and what about disabling the automatic password generator when a different policy for password has been configured?

**Comment by zero-24** [comment]
it never uses the config. it is just a random string.

**Comment by mbabker** [comment]
Long and short, if you've got a password policy enabled, unless you grab a massively large block of data from `random_bytes()` and keep appending characters to the string until you match policy, it's not viable to use `random_bytes()` as a password generator that has to be policy aware.

Which means changing how the user record is handled in that case.  Do you allow NULL passwords or do you cause form validation errors (which presents saving) on an empty value?

**Comment by brianteeman** [comment]
So long and farewell
