### ISSUE TITLE
Regression: #11698 prevents language load for admin mod_menu

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#11812]
### Steps to reproduce the issue
Make sure your staging is updated.
Edit a menu module.

You will get:
![screen shot 2016-08-27 at 08 56 37](https://cloud.githubusercontent.com/assets/869724/18025785/9fc8159a-6c34-11e6-8688-7bc16286572e.png)

reverting #11698 solves the issue

**Comment by brianteeman** [comment]
Confirmed

**Comment by andrepereiradasilva** [comment]
just to say i used a similiar code in https://github.com/joomla/joomla-cms/pull/11730/files for the plugins.
If there is any used with this, that one needs to be checked too.

**Comment by mbabker** [comment]
It's fine for plugins because their language files are always in `administrator/language` or the plugin's directory.  For modules it's borked because we have the notion of admin modules and site modules the same way we have admin and site components and templates.  PR incoming.

**Comment by mbabker** [comment]
See #11814
