### ISSUE TITLE
Tags field - Type gets cropped if matches existing tag

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#11835]
### Steps to reproduce the issue
1. Open article
2. Type an already existing tag (min 4 characters)
3. Pause a second and the type becomes cropped

![screen shot 2016-08-29 at 07 01 18](https://issues.joomla.org/uploads/1/d8c2529dba210492dad0b149465c00eb.jpg)

### System information (as much as possible)
Joomla 3.6.2

### Additional comments
A set width of 25px appears to be added inline to the input when you pause typing.

```
<input class="" type="text" style="width: 25px;" autocomplete="off" value="Techno">
```

**Comment by brianteeman** [comment]
I can not confirm this using chrome on osx with either the current staging or the current staging + the chosen upgrade<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11835">issues.joomla.org/joomla-cms/11835</a>.</sub>

**Comment by C-Lodder** [comment]
@ciar4n - What browser are you seeing this issue in?

**Comment by ciar4n** [comment]
@C-Lodder Seeing this issue on Firefox (48.0), Chrome (52.0) and IE Edge using Windows 7. Just checked on a 2nd machine with the same result.

**Comment by franz-wohlkoenig** [comment]
Confirm Issue.
#### Test on:
Joomla! 3.7.0-staging
macOS Sierra, 10.12.3: Firefox 50.1.0, Chrome 55, Safari 10.0.3
windows7: Firefox 47.0.1, IE11
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by stanblesk** [comment]
I've fixed this issue. Thanks to [this post](http://stackoverflow.com/questions/22258153/ajaxchosen-plugin-will-not-work "Stackoverflow post")

All you need to do is switch /media/jui/js/ajax-chosen.min.js with this [Michael Perrin's fork](https://github.com/michaelperrin/ajax-chosen/blob/master/lib/ajax-chosen.min.js "Github page for working library"): <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11835">issues.joomla.org/tracker/joomla-cms/11835</a>.</sub>

**Comment by AlexRed** [comment]
I can't confirm the problem on
Joomla! 3.7.0-staging
Linux ubuntu: Firefox 52.0.1 (64 bit) and Chrome 57.0.2987.110 (64-bit)
PHP 5.5.15 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11835">issues.joomla.org/tracker/joomla-cms/11835</a>.</sub>

**Comment by Quy** [comment]
This is not reproducible. Even the selected tags are blue (not white as seen in the screenshot) and on its own line.

**Comment by C-Lodder** [comment]
@ciar4n are you still getting the same issue on your machine?

**Comment by ciar4n** [comment]
Nope. The issue appears to have been resolved. Closing.
