### ISSUE TITLE
Feature Request: Show actual status of global settings while editing an article...

### ISSUE THREAD

**Issue by hacki65** [joomla/joomla-cms#11855]
The idea is to give the author of an article the possibility to see which global settings are actual given for articles. I think it would be helpful to know this settings on editing an article without to go to the options for articles.

This can be also improved for Categories, Menus, and all other overridable options which has global settings in Joomla.

![feature-global-status](https://cloud.githubusercontent.com/assets/20481746/18123204/22c36db0-6f6d-11e6-8f41-820f303c7ec2.jpg)

**Comment by zero-24** [comment]
Looks cool can you send you code as pull request against the staging branch? Let me know if you need help with that :+1:

**Comment by andrepereiradasilva** [comment]
i agree with this it's rather confusing but i would prefer: "Use Global (*Global Setting for the field*)" and for all fields that have "Use Global"

**Comment by hacki65** [comment]
@zero-24 : Sorry, but this is a screenshot that i have edited with PS. I'm not a coder so It makes no sense for me to open a pull request. This new feature must be realized by a developer from the Joomla Developer Team. :)

@andrepereiradasilva : I think "Status Global: Value" or "Gobal Setting: Value" would be good. But this is my opinion and can be discussed. And YES, i meant, of course, that should be realized for all fields with global settings.

**Comment by hacki65** [comment]
Is there nobody interested at this request?

**Comment by andrepereiradasilva** [comment]
i think there are lot of people interrested in having this, but not lots of people having the time to investigate and doing.

**Comment by hacki65** [comment]
Yes i know, but i hope this request will not be forgotten... :)

**Comment by Bakual** [comment]
Have a look at https://github.com/joomla/joomla-cms/pull/11911. It should do what you want.

**Comment by Bakual** [comment]
Closing as there is a PR now.
