### ISSUE TITLE
com_search on back-end: Results links opens in backend window instead of new Tab

### ISSUE THREAD

**Issue by jsubri** [joomla/joomla-cms#11852]
### Steps to reproduce the issue

administrator/index.php?option=com_search&view=searches 
click on "Show Search Results"

![capture](https://cloud.githubusercontent.com/assets/5349333/18104130/e8e04906-6ef9-11e6-951c-e0b2756f7ddb.PNG)

### Expected result
Clicking the "Results" links shall opens in a new Tab, these links are Front-End view only.

### Actual result
The Front-End view is displayed in your administrator window. 
You might be tempted to close the current tab and as such loosing your back-end. 
Using the browser back button shall be avoided while doing stuff in the console.

### System information (as much as possible)
Since 3.6.0

### Additional comments
Adding target="_blank" at 
https://github.com/joomla/joomla-cms/blob/31b7eb29d35c75902a79969982f155e313192248/administrator/components/com_search/views/searches/tmpl/default.php#L71
Feedback welcome before I can try a PR for that.

**Comment by brianteeman** [comment]
From an a11y perspective it is bad to open a new window/tab. That removes
the ability for someone using assistive technology to use the back button
to return to where they are.

In addition while it is possible to force a link to open in a new
window/tab using the ctrl key it is not possible to force a link to open in
the same window/tab

**Comment by andrepereiradasilva** [comment]
from accessibility perspective is not always bad to open in new window.

when you exchange app sessions you should, especcially if one is secure and the other not, IMHO, open in new tab/window.

> Use of the target attribute provides an unambiguously machine-readable indication that a new window will open.
> User agents can inform the user, and can also be configured not to open the new window.
> For those not using assistive technology, the indication would also be available from the link text.

> Example: <a href="help.html" target="_blank">Show Help (opens new window)</a>

https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20160317/H83

Also

> The objective of this technique is to limit the use of links or buttons that open new windows or tabs within Web content. In general, it is better not to open new windows and tabs since they can be disorienting for people, especially people who have difficulty perceiving visual content. **However there are some situations where it is preferable from an accessibility perspective to open a new window or tab**. Here are two such situations:
> [...]
> Example 2: Secure Web site
> A page on a secure Web site includes a link to an external page that is outside of the secure session. The link opens in a new window or tab since opening the link in the same window will break or destroy the secure session.

Source: https://www.w3.org/TR/WCAG20-TECHS/G200.html

**Comment by jsubri** [comment]
Thank you both for sharing your views, I was suggesting "new Tab" to distinguish back/front-end similar than the "site preview" that is a front-end view only.
- I'm trying to educate my users to never us the back button while in the back-end (as this is creating locks on items "core and 3rd party" that can be remove only by the locks creators or by the Global Check-in access rights), this view looks like an exception across the Joomla console.
What about modal?

**Comment by bertmert** [comment]
Extending the issue:
- BE > Components > Search.
- Enter a search word in search filter. Click search button.
- Click Results label > landing in FE.
- Click back button of browser. The browser will block BE with a "Document Expired" page.
- You need 2 additional clicks ("Try again" + "Resend") to come back to BE.

![31-08-_2016_09-22-35](https://cloud.githubusercontent.com/assets/11038612/18119759/8ac92f96-6f5c-11e6-8668-f62a4f90dd01.jpg)

Another find: I tested with a Search Phrase that had 1 Hits. After any click on Results label Hits is increased by 1.
![31-08-_2016_09-28-48](https://cloud.githubusercontent.com/assets/11038612/18119953/74f3655a-6f5d-11e6-8564-2d31d4a98d9a.jpg)

.

**Comment by brianteeman** [comment]
I would expect the hits to increase as clicking on the link is doing a new search<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11852">issues.joomla.org/joomla-cms/11852</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a PR for testing see #12626 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11852">issues.joomla.org/tracker/joomla-cms/11852</a>.</sub>
