### ISSUE TITLE
[4.0] Control Panel - Drag n Drop (modules)

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#11863]
Something I've mocked up today (not perfect but you get the idea).

![joomla](https://cloud.githubusercontent.com/assets/2019801/18134849/c3e1e1c0-6f97-11e6-846b-8cc5c2492b2f.gif)

Thoughts?

Is this something people would be interested in having?

@brianteeman - Nice find with LICEcap :)

**Comment by dgt41** [comment]
@C-Lodder if you are about to do this can you please use https://github.com/bevacqua/dragula ?

**Comment by C-Lodder** [comment]
Yup, can use that. Suppose it saves having to use jQuery UI

**Comment by brianteeman** [comment]
Don't really see the purpose

**Comment by C-Lodder** [comment]
@brianteeman It's so that people can change the position of the dashboard modules quickly and at ease, without having to go to the module manager which IMO is just long and tedious. For me personally, I'll never use this feature but I know a lot of people who have their dashboard stacked with module for quick access to pages and analytics/stats.

**Comment by JoshuaLewis** [comment]
I think this is a great little UX improvement. A positive change that doesn't add much weight (in terms of amount of code and time it takes to process) to the core is worth adding. Anything that makes Joomla easier to manage is something worth while. If a PR for this is made I would gladly test it out. :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11863">issues.joomla.org/joomla-cms/11863</a>.</sub>

**Comment by C-Lodder** [comment]
@dgt41 - Looked into Dragula today and it's not very well documented. Most likely won't be going with it.

**Comment by dgt41** [comment]
@C-Lodder once you're ok with the jQuery script ping me to convert it to vanilla script (dragula or any other). The only reason I pointed you to dragula is the fact that simple functionality could be done (with wide browser support) without jQuery dependency.

**Comment by micker** [comment]
it will be a great idea ... same for front !

**Comment by franz-wohlkoenig** [comment]
Thanks for Mockup, @C-Lodder, would also like to have it in Back- and Frontend.

**Comment by brianteeman** [comment]
@C-Lodder iirc you have already implemented this now in j4 and this can be closed here?

**Comment by franz-wohlkoenig** [comment]
@brianteeman in J4 its not implemented, tried to use like Mockup above.

**Comment by dgt41** [comment]
@franz-wohlkoenig you are right, the code is not merged in J4, the reason is that there were 2 different approaches for the implementation and the J4 team waits for input from the UX group (I think they promised that will have that by 1st of April)

**Comment by brianteeman** [comment]
Closing this here due to lack of activity for over a year
