### ISSUE TITLE
Multilanguage: undesired deleted associations

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#11871]
Multingual site with associations enabled.
3 content languages

Create an article in each content language and associate them.

Then edit one of these articles and change its language to ALL.
The article saves with this correct warning:
>A content item set to All languages can't be associated. Associations have not been set.

The problem is that the 2 other articles are no more associated between them.

@Bakual 
As we both worked on this a while ago, please see if you can solve.

Note: the issue is the same for all associated items.

**Comment by andrepereiradasilva** [comment]
confirmed

**Comment by Bakual** [comment]
I'm looking into it, saw already another issue :)

**Comment by Bakual** [comment]
Closing as we have a PR #11877
