### ISSUE TITLE
Tags under article

### ISSUE THREAD

**Issue by tastymousehub** [joomla/joomla-cms#11882]
### Steps to reproduce the issue

Set Position of Article Info to Below. Go to the website and you'll see the Tags under the title under the title. This happens when you choose Category Blog as Menu Item Type. The Tags are Below when you use the Featured articles as type.

### Expected result

The Tags should be Below the article in Category Blog.
### Actual result

The are Above.
### System information (as much as possible)

Joomla 3.6.2
### Additional comments

This was a bug in 3.4 and was fixed. Now it seems to be back.

**Comment by franz-wohlkoenig** [comment]
Confirm on 3.7-staging too.

**Comment by AlexRed** [comment]
I can confirm the problem in 3.7.0-stagin<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11882">issues.joomla.org/tracker/joomla-cms/11882</a>.</sub>

**Comment by N6REJ** [comment]
That explains alot!

**Comment by zero-24** [comment]
to me it not clear what the bug is?

Please explain it more detail.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11882">issues.joomla.org/tracker/joomla-cms/11882</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@zero-24 
#### Position of Tag in Menu "Home" (Type "Featured Articles"):
![bildschirmfoto 2017-04-22 um 09 35 42](https://cloud.githubusercontent.com/assets/8235763/25302472/2f8a0362-273f-11e7-9eea-fb2ec96b72e2.JPG)
#### Position of Tag in Menu "Blog" (Type "Category Blog"):
![bildschirmfoto 2017-04-22 um 09 36 54](https://cloud.githubusercontent.com/assets/8235763/25302479/3e7969b2-273f-11e7-8b69-429976dd54ac.JPG)

**Comment by zero-24** [comment]
Ah this is tags. Not article info. I'm going to check that when i'm back at home.

**Comment by zero-24** [comment]
Even it take longer than expeced. I was more focused on 3.7.0 stable. Here is a PR please test: https://github.com/joomla/joomla-cms/pull/15497
