### ISSUE TITLE
"Filter field" parameter in "List News Feeds in a Category" not working

### ISSUE THREAD

**Issue by stellainformatica** [joomla/joomla-cms#11883]
### Steps to reproduce the issue
1. Create a newsfeed in Components > News Feeds 
2. Create a menu item type News Feeds » List News Feeds in a Category
3. Look in frontend the page, there's a filter field "News Feed Filter Search"
3. In administration modify the menu item and in the tab List Layouts change the parameter " Filter Field" to Hide.

### Expected result
The filter field "News Feed Filter Search" should disappear

### Actual result
The filter field "News Feed Filter Search" doesn't disappear

### Additional comments

Also by setting to Hide in the News Feed component Options, the field doesn't disappear.
It seems that also the  Table Headings parameter doesn't work, in this case the table heading never appears.

**Comment by AlexRed** [comment]
I can confirm the issues![screen shot 2016-09-02 at 04 30 55](https://issues.joomla.org/uploads/1/dbc614d67af03557d63aff8d093e4adc.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11883">issues.joomla.org/joomla-cms/11883</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a pr for testing see #11899

**Comment by alikon** [comment]
@stellainformatica , @AlexRed please test #11899
