### ISSUE TITLE
[RFC] Article edit form layout

### ISSUE THREAD

**Issue by dgt41** [joomla/joomla-cms#11897]
#### Is there a particular reason for the edit form to be `span9` `span3` ??

So I was looking at the odd case that tags and notes are wider than the other fields on the right of the editor. (that's because they do have a class `span12` and they shouldn't)
And I thought that scrolling (not necessary on big screens) to get a full width editor might be a better option than the 9/12 of the screen.

And some screenshots will explain better the situation here:

Current state (span9 and span3):
![screen shot 2016-09-02 at 21 29 16](https://cloud.githubusercontent.com/assets/3889375/18214201/5e6b95de-7154-11e6-9c82-10c0fc948b9c.png)

Reducing the right column to span2:
![screen shot 2016-09-02 at 21 21 37](https://cloud.githubusercontent.com/assets/3889375/18214210/7061eac2-7154-11e6-9ec7-16773719a844.png)

Move the right column above the editor area:
![screen shot 2016-09-02 at 21 20 40](https://cloud.githubusercontent.com/assets/3889375/18214230/832ee63c-7154-11e6-8018-986ea2e38975.png)

There might be other options here, but these are the obvious ones.

Recap: There are some wrong classes:
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/models/forms/article.xml#L58
and 
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/models/forms/article.xml#L23

The width of the column (do we need a right column in the first place) can be smaller or eliminated altogether.

**Comment by Bakual** [comment]
I certainly wouldn't put the fields above the text field. That one is the most important one and should stay most prominent. The sidebar is imho fine for that stuff.

As for the width, I guess it's to give more room for the text fields, so you can enter (and read) a bit more characters without scrolling. But I really don't know.

**Comment by brianteeman** [comment]
Definitely don't put it on top. We had that in 2.5 and it was hated as you
had to scroll to create / edit any content

**Comment by MATsxm** [comment]
Agree with both above.

**Comment by dgt41** [comment]
> That one is the most important one and should stay most prominent.

If so then there must be visible in all tabs, or not...

**Comment by mbabker** [comment]
To me it's already big enough.  Unless we're trying to make it a full screen editor, the most I'd say to do is switch to span10/2 (ensuring it doesn't cause any funny behaviors on smaller devices along the way).

**Comment by Bakual** [comment]
> If so then there must be visible in all tabs, or not...

No, if you switch tabs you are done with editing the content itself and want to adjust its metadata.

**Comment by yild** [comment]
All wide (column) texts are hard to read so no need for a wider editor imo.

**Comment by brianteeman** [comment]
What is the problem you are trying to resolve

**Comment by dgt41** [comment]
@mbabker I guess thats one of the reasons we use bootstrap's grid.
@Bakual ok
@brianteeman the whitespace on the right of the form could be eliminated/used for something else (editor) https://cloud.githubusercontent.com/assets/3889375/18214201/5e6b95de-7154-11e6-9c82-10c0fc948b9c.png

How about span10/span2:
![screen shot 2016-09-02 at 22 39 46](https://cloud.githubusercontent.com/assets/3889375/18216322/a555b0d8-715e-11e6-8e22-0dda0c81c283.png)

**Comment by brianteeman** [comment]
I agree with @yild that's creating a very long length in the editor which
is not good.

**Comment by dgt41** [comment]
@brianteeman @yild I hope that people actually use editor.css on their sites, to get the WYSIWYG out of the editor. 
But anyway I don't want to argue on an obviously wrong implementation and try to prove that span3 should have been span2 right from the beginning. So let's stay with the random whitespace, if that works for most people
