### ISSUE TITLE
When installing Joomla! under certain conditions you are not getting to the next screen.

### ISSUE THREAD

**Issue by slibbe** [joomla/joomla-cms#11891]
### Steps to reproduce the issue
Install Joomla! 3.6.2 from the download at https://github.com/joomla/joomla-cms/releases/tag/3.6.2 

Make sure that at the Finalisation-screen after Overview, send Email Configuration is set to yes, as shown in attachment.

### Expected result
Installation succes should be independant of the setting send Email Configuration option.

### Actual result
No matter which of the install-options you choose you will be getting this same Finalisation-screen until you set the send Email Configurations to No.

### System information (as much as possible)
PHP 5.6, MySQLi, Apache, all running in a Vagrant ScotchBox.[screen shot 2016-09-02 at 10 03 09](https://issues.joomla.org/uploads/1/7ad49c1a5c5b59ce41d20da0fef71d4a.png)

**Comment by zero-24** [comment]
@slibbe works for me can you doube check that the PHP mail() function is enabled on your server?

**Comment by mbabker** [comment]
The whole point of the issue is installation shouldn't catastrophically fail just because the welcome email couldn't be sent.

**Comment by zero-24** [comment]
ok i could it reproduce but i have no idea how to fix.

To reproduce just add `$return = false;` here: https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/mail/mail.php#L133

@mbabker do you know how to catch that? If that hits the return it fails and it look i have not the right tools to debug what happen there :(.

https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/mail/mail.php#L136

**Comment by mbabker** [comment]
The mailer API correctly raises an error on a send failure.  That shouldn't change.  The install app needs to not fail on that error condition.

**Comment by zero-24** [comment]
>The install app needs to not fail on that error condition.

Yes i agree with that. But how we can catch that error? Currently we `catch (Exception $e)` which is wrong? Atleast it don't work as after the first failed call to the `$mailer->send()` it jumps back.

https://github.com/joomla/joomla-cms/blob/staging/installation/controller/install/email.php#L130-L142

If you comment the call to `$mailer->send()` out everything works. (ok no mail is send than :P)

**Comment by mbabker** [comment]
The fix is simple.  The `libraries/legacy` tree isn't being included in the install app because its code was rewritten to not be dependent on it.  Most likely this has been an issue since the PR that removed the "if JError exists use it for error handling else throw an Exception" logic from `JMail`.  The error handling is trying to call a non-existing class.

Change `installation/application/framework.php` to require `import.legacy.php` instead of `import.php`.

**Comment by zero-24** [comment]
Thanks @mbabker that works.

>Change installation/application/framework.php to require import.legacy.php instead of import.php.

see https://github.com/joomla/joomla-cms/pull/11895

@slibbe can you test the PR?

**Comment by slibbe** [comment]
Test PR11895? I will.


I think I noticed this behaviour somewhere in de 3.6 alpha/beta stage, but was too busy at that time to check. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11891">issues.joomla.org/joomla-cms/11891</a>.</sub>

**Comment by slibbe** [comment]
@zero24 The mail function was disbled on the server; however when setting on the mail-catcher (making it seem that the mail-function is available) the installation continues as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11891">issues.joomla.org/joomla-cms/11891</a>.</sub>
