### ISSUE TITLE
RFC : Ability to import export Global and extension configuration

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-cms#11904]
The Joomla configuration as well as a lot of the core extensions have a lot of settings between them. Add 3PD extensions to the mix and you are talking about 100s of configuration settings. Assuming most Joomla developers do use Joomla's prescribed way of saving 'options', building the ability to 'export' and 'import' the options or configuration settings will be very useful.

![joomla_options-import-export](https://cloud.githubusercontent.com/assets/673176/18222570/0fbd8ba8-71b9-11e6-9059-016bde742c1a.png)

**Comment by brianteeman** [comment]
@parthlawate your colleague @coolbung already created this issue and it was rejected #10993


I am closing this for the same reasons

**Comment by parthlawate** [comment]
Ah ! I didnt know it was already posted. Sorry for the duplicate. Will reply on the original one as to why i think it is relevant
