### ISSUE TITLE
Frontend article params

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#11907]
Native Protostar template - no frontend article layout overrides:

### Steps to reproduce the issue
Load form with ```<fields name="attribs">``` custom fields via ```onContentPrepareForm``` event.
Edit article in frontend, no form fields are displayed

Load form with ```<fields name="params">``` custom fields via ```onContentPrepareForm```.
Edit article in frontend, form fields are displayed
Fill in fields and save article.
No data is saved.

### Expected result
Custom ```<fields name="attribs">``` are displayed and saved in frontend - same as in backend.

### Actual result
Frontend does not display ```<fields name="attribs">``` but ```<fields name="params">``` which are not saved.

**Comment by Denitz** [comment]
In other words:

backend displays both ```params``` and ```attribs``` fields.
frontend displays ```params``` fields only.
both frontend and backend save data from ```attribs``` fields only.

**Comment by brianteeman** [comment]
Why did you close this?

**Comment by Denitz** [comment]
Yes, ```/components/com_content/view/form/tmpl/edit.php``` uses the code:
```
<?php foreach ($this->form->getFieldsets('params') as $name => $fieldSet) : ?>
```

So it displays ```params``` fields only, not ```attribs```. But these ```params``` fields will be not saved since table uses ```attribs```.

**Comment by n9iels** [comment]
I can confirm this. Now it is impossible to create a plugin that save custom fields in the parameters for front- and back-end. The only way to do it now is creating a complete new fieldset and let the plugin save data in its own database table.
If you just want to add a simple custom text field this is overkill.

For the back-end you can do something like this:
```xml
<fieldset name="params">
    <field
        name="test"
        type="text"
        label="Text field"
        description="some text field"
    />
</fieldset>
```
The content of this field will be save inside the

**Comment by brianteeman** [comment]
As the description of the option states that it is only to display them on the admin I am going to close this as expected behaviour and as it is now two years old clearly everyone else thinks it is to be expected.
