### ISSUE TITLE
Trying to uninstall a protected extension will remove it's update site

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#11908]
### Steps to reproduce the issue

- Go to Extensions > Manage > Update Site
- Confirm you have a aupddate site for joomla update component
- Go to Extensions > Manage > Manager
- Search for joomla update
- See the extension is blocked, but select it and try to unistall it
- Check you get a warning message
- Go to Extensions > Manage > Update Site
- Confirm you don't have a upddate site for joomla update component -> Bug!

### Expected result

Don't remove update sites if the you can't uninstall the extension.

### Actual result

Removes the update site!

### System information (as much as possible)

Latest staging

### Additional comments

The same happens for all protected extension with update sites, even joomla core and en-GB language package.
You can rebuild them after.

**Comment by brianteeman** [comment]
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11908">issues.joomla.org/joomla-cms/11908</a>.</sub>

**Comment by wilsonge** [comment]
PR https://github.com/joomla/joomla-cms/pull/11915

**Comment by rgtr** [comment]
Hi
bug persists in 3.9.24 with 
   FOF | Site | Library | 2.4.3 | 2015-04-22 13:15:32 | Nicholas K. Dionysopoulos / Akeeba Ltd
what does one do ???

**Comment by HLeithner** [comment]
@rgtr pelase create a new issue and reference this issue instead of comment on a 4 year old one that's closed. 

Also please give some more information since this bug should be fixed since Joomla 3.6.3.

thx

**Comment by rgtr** [comment]
Hi

Thanks for your message.

It has left a legacy that needs to be cleaned up ... it was causing me 
problems with getting one site up to j4

here is my log when updating here: http://tdocplus.co.uk/7a_AS3924/

as you can see akeeba has been a big problem.

but as it is desparately needed - one cannot think of upgrading without 
it ! must jhave used to hundred's of times.

attached my analysis of 6 of my 8 sites so far converted.

Tech Reumer's Google Maps is my biggest problem - what to replace it 
with ... linnpark.org.uk uses it extensively to show stuff in the park 
from paths to train stations !

Richard

----------------------------------------------------------------------

Restored AS 3.9.24 installation:

tdocplus.co.uk/7a_AS3924

shareddb-y.hosting.stackcp.net
AS3924-3135394334
pcxp4s4alw

settings fixed.

removed beez5
removed mavik package, plus 2
removed regular 7 plugins, 1 lib
removed System - KC Old Browser Warning - plugin
removed System - P3P Policy
removed plg_content_geshi - content
removed PLG_CONSOLE_AKEEBABACKUP
removed breadcrumbs advanced - site module

backup 3924_01_Test

removed community builder

backup fails to start
admin tools clear etc
backup 3924_02_Test

fef'ing etc
===========
removed admin tools - see pic
removed akeeba - see pic
removed files akeeba strappers x 2
removed file - file_fof30
removal tried System - Akeeba Backup Update Check plugin
     This extension requires FOF 3.0.
installed fof30
removed Akeeba Backup Update Check plugin
removed file - file_fof30
removed fof x 2 [2.4.3 refuses - protected] fof30 libs

database - removed 20 akeeba_subs tables
database - removed 14 comprofiler tables
database - removed 11 jcomments tables
datatable extensions - deleted records for FOF,library, fof
datatable extensions - deleted record for JComments_Latest
datatable extensions - deleted record for plg_sys_browserupdatewarning
datatable extensions - deleted record for F0F (NEW) DO NOT REMOVE
datatable extensions - deleted records for tabs and sliders

97 tables.

installed akeeba
backup 3924_03_AS_Test

updated to 3.10.0-alpha4

removed System - NoNumber Framework [OLD] Site    Plugin
datatable extensions - deleted record Community Builder Admin menu - module

100 tables
backup 3924_04_AS_Test

removed google maps
backup 3924_05_AS_Test

updated to 4.0.0-beta6
backup

datatable modules - deleted record for JComments_Latest
backup

-- 
*Eur Ing Richard Townsend-Rose MA CEng MICE*
Phone: 0141 237 8293
Mobile: 07770 460862

LinnPark.org.uk <http://www.linnpark.org.uk>


-- 
This email has been checked for viruses by AVG.
https://www.avg.com

**Comment by zero-24** [comment]
> but as it is desparately needed - one cannot think of upgrading without
it ! must jhave used to hundred's of times.

Upgrading without it is possible at no time of the upgrade process any 3rd party software is required.

> Tech Reumer's Google Maps is my biggest problem - what to replace it
with ... linnpark.org.uk uses it extensively to show stuff in the park
from paths to train stations !

Pleae check https://forum.joomla.org for such questions. This repo here is about issues with the Joomla Core.

Thanks for understanding

**Comment by brianteeman** [comment]
For any issue with akeeba you really should contact the developer as I am 99% sure he has done everything required for joomla 4

**Comment by brianteeman** [comment]
> Tech Reumer's Google Maps is my biggest problem 

That extension really shouldnt be used at all for at least the last 3 years
https://extensions.joomla.org/extension/maps-a-weather/maps-a-locations/google-maps-by-reumer/
