### ISSUE TITLE
Problem with contact forms after upgrading to Joomla 3.6.2

### ISSUE THREAD

**Issue by conceptodaf** [joomla/joomla-cms#11925]
Hello guys, I wanted to report this issue. My client's web hosting provider meets the minimal requirements to install Joomla (Apache 2.2, MySQL 5.1.71, PHP 5.3.29) and after the last upgrade all the forms stopped working on the site (we use Fox Contact Form and BreezingForms, both of them worked great before this upgrade). When I press the "send" button at the bottom of the forms, nothing happens. The page refreshes, the fields get clean, but the form isn't send at all and the "successfuly sent" notification isn't shown. It seems something broke when we upgraded. I know PHP 5.3 is almost obsolete but the client has a contract with his hosting provider until december, and PHP versions can't be upgraded. We're planning to migrate the site to a new server on January. 
I tried debugging but it seems there's nothing wrong, so I decided to do a clean install but I can't get through step one in the installation process. When I press the "Next" button, nothing happens. I've seen on Google that many people has this issue too, so I was wondering if there's a way to fix this.

I have a backup of the previous version, so I can downgrade. But I wanted to report this first. Thanks in advance!

**Comment by brianteeman** [comment]
Please use the forum for support. http://forum.joomla.org
