### ISSUE TITLE
Users appear as offline/guest after login

### ISSUE THREAD

**Issue by gee2803** [joomla/joomla-cms#11933]
### Steps to reproduce the issue
Since Joomla 3.6.2 I am facing the following problem: Some (not all) users log in and won't get a correct session entry in the database. They appear as offline but can use the site as a normal registered user. I am using JomSocial but the problem affects also logins via Joomla login module. I can not reproduce why and never faced the problem myself but I many users report it and I have a much higher guest count now. 

### Expected result
Users should be logged in in session table

### Actual result
Many users are just shown as offline

### System information (as much as possible)
Database Version 	5.5.5-10.0.25-MariaDB-0+deb8u1
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.6.24
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.6.2 Stable [ Noether ] 4-August-2016 23:41 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by C-Lodder** [comment]
Please test this patch: https://github.com/joomla/joomla-cms/pull/11691

**Comment by brianteeman** [comment]
Reset priority according to the documented standards https://docs.joomla.org/Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11933">issues.joomla.org/joomla-cms/11933</a>.</sub>

**Comment by gee2803** [comment]
@C-Lodder: Thank you very much. I can confirm that the patch solves my problem, too. I hope this will be in the next Joomla update.
@brianteeman: Sorry for the wrong priority setting. I am new here and it was very critical to me, because it looks to new guests like an empty community. I read the guideline now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11933">issues.joomla.org/joomla-cms/11933</a>.</sub>

**Comment by brianteeman** [comment]
closing as resolved by #11691

**Comment by brianteeman** [comment]
@gee2803 yes the fix from #11691 will be in the next release
