### ISSUE TITLE
Mssql: article can´t be created

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#11932]
### Steps to reproduce the issue

Install current staging with or without sample data and try to create a new article. You will get this error message:
8155 [Microsoft][SQL Server Native Client 11.0][SQL Server]No column name was specified for column 1 of 'A'. SQL=SELECT \* FROM ( SELECT count(id) , ROW_NUMBER() OVER (ORDER BY (select 0)) AS RowNumber FROM #__usergroups) A WHERE A.RowNumber BETWEEN 1 AND 1

**Comment by andrepereiradasilva** [comment]
could it be related to this? https://github.com/joomla/joomla-cms/commit/381b75dae2bb59b71decc8d24e237624b5a45b65

**Comment by williamsandy** [comment]
This is quite a serious issue making Joomla using MSSQL not usable with patch [381b75dae2bb59b71decc8d24e237624b5a45b65https://github.com/joomla/joomla-cms/commit/381b75dae2bb59b71decc8d24e237624b5a45b65 "381b75dae2bb59b71decc8d24e237624b5a45b65") applied.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11932">issues.joomla.org/joomla-cms/11932</a>.</sub>

**Comment by adrianfso** [comment]
Any progress on this? I'm experiencing the same issue in Joomla 3.6.4.

**Comment by adrianfso** [comment]
Thank you williamsandy, I found the update that you provided on another page and that helped resolve the problem.

**Comment by pocketpc** [comment]
I'm running into this issue on my server. Is there a PR for this yet? If not, I can put one together, it's easily patched.

**Comment by waader** [comment]
@pocketpc A patch would be most welcome.

**Comment by zero-24** [comment]
Closing as we have a PR https://github.com/joomla/joomla-cms/pull/13288

**Comment by csthomas** [comment]
Mssql patch which allows to use limit and offset are created at https://github.com/joomla/joomla-cms/pull/13262
