### ISSUE TITLE
[regression] 3.7 options

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#11949]
In 3.6 go to article options. All the values on the left eg Show and yes are in green and on the right are in red
Repeat in 3.7 and this is reversed

**Comment by laoneo** [comment]
I'v discovered the same, when playing around with #11833.

**Comment by wilsonge** [comment]
I'm pretty sure that's caused by your PR here brian? https://github.com/joomla/joomla-cms/pull/11421

**Comment by brianteeman** [comment]
If so then that was @C-Lodder code not mine

**Comment by C-Lodder** [comment]
Erm...so turns out I missed a letter in the class name so the conditional statements weren't working. Fixed so will submit a PR

**Comment by andrepereiradasilva** [comment]
3.7.x

**Comment by brianteeman** [comment]
Thanka

**Comment by C-Lodder** [comment]
https://github.com/joomla/joomla-cms/pull/11971

**Comment by brianteeman** [comment]
Thanks and closed
