### ISSUE TITLE
MA_NONUMBER_FRAMEWORK_NOT_INSTALLED MA_EXTENSION_CAN_NOT_FUNCTION

### ISSUE THREAD

**Issue by primebky** [joomla/joomla-cms#11942]
How do we fix this issue?

from developer![screen shot 2016-09-05 at 12 01 58](https://issues.joomla.org/uploads/1/467cb59de6ff9776c7ab0360faaa892c.png)
Sorry, this problem comes from code admin of joomla so we can't resolve it.

**Comment by zero-24** [comment]
Can you explain how to reproduce this bug?

**Comment by mbabker** [comment]
It's an issue with an extension depending on the NoNumber Framework.  Not a
core issue at first glance.

**Comment by primebky** [comment]
Dont get it. It shows once i logged into my administrator backend. It shows
on every page

**Comment by primebky** [comment]
Developer claims its joomla admin issue and referred me back to joomla

**Comment by zero-24** [comment]
Please disable all 3party plugins and start with the nonumber once. Btw which developer point you to the core?

**Comment by primebky** [comment]
Developer only indicated its joomla admin code issue and they cannot resolve

**Comment by mbabker** [comment]
I don't know which developer you spoke to but Joomla core neither has this
language string nor a dependency to NoNumber code.  The only way it could
be a core issue is if the check causing this issue is using a core API that
is not returning an expected value.  Without a code snippet or knowing what
extensions are in use this cannot be debugged, either as a core Joomla
issue or with an extension.

**Comment by brianteeman** [comment]
Reset the priority according to the standards https://docs.joomla.org/Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11942">issues.joomla.org/joomla-cms/11942</a>.</sub>

**Comment by brianteeman** [comment]
Which developer? Your developer or https://www.regularlabs.com/

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11942">issues.joomla.org/joomla-cms/11942</a>.</sub>

**Comment by primebky** [comment]
the template i'm using developer. trucking

**Comment by brianteeman** [comment]
Then they dont know what they are talking about.As stated before this is NOT a Joomla issue. You have an extension installed from https://www.regularlabs.com/ and it had not been installed correctly.
