### ISSUE TITLE
Joomla Update issue 3.6.0 to 3.6.2 invalid security token

### ISSUE THREAD

**Issue by limon213** [joomla/joomla-cms#11945]
### Steps to reproduce the issue

Update Joomla from 3.6.0 to 3.6.2

### Expected result
After the complete update, it is showing following error - 

> The most recent request was denied because it contained an invalid security token. Please refresh the page and try again.

When I go back to the administrator. It is up to date. 

### System information (as much as possible)

System Information
Setting	Value
 
PHP Built On	Windows NT DESKTOP-LML1IA0 10.0 build 14393 (Windows 10) i586
Database Version	5.6.30
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.5.35
Web Server	Apache/2.4.20 (Win32) OpenSSL/1.0.2g PHP/5.5.35 mod_wsgi/4.4.21 Python/3.5.1
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.6.2 Stable [ Noether ] 4-August-2016 23:41 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36

### Additional comments

I am using this update in my localhost Ampps.

**Comment by brianteeman** [comment]
Did you update com_joomlaupdate first? If not then this is expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11945">issues.joomla.org/joomla-cms/11945</a>.</sub>

**Comment by zero-24** [comment]
@limon213 you can try this on (do not do that in a production site!) https://github.com/joomla/joomla-cms/pull/11689

**Comment by limon213** [comment]
@brianteeman can you tell me how to update com_joomlaupdate ? I cleared cache from update manager and tried to get the list to update com_joomlaupdate .nothing showed up!!!

my testing Joomla version is 3.6.0.

@zero-24 i will test. 
thanks

**Comment by limon213** [comment]
Hello, @zero-24  I just tried #11689 But still the same issue - 

> The most recent request was denied because it contained an invalid security token. Please refresh the page and try again.

**Comment by andrepereiradasilva** [comment]
> Did you update com_joomlaupdate first? If not then this is expected behaviour

**Comment by limon213** [comment]
@andrepereiradasilva I cleared cache from update manager and tried to get the list to update com_joomlaupdate .nothing showed up!!!

**Comment by andrepereiradasilva** [comment]
well it seems somehow your site or server are not fetching com_joomlaupdate latest update.
Your server should be fetching this https://update.joomla.org/core/extensions/com_joomlaupdate.xml as the update server for com_joomlaupdate. Check if you have it in the update sites.

**Comment by limon213** [comment]
@brianteeman @andrepereiradasilva 
i just checked administrator/index.php?option=com_installer&view=updatesites and ifound that the update site for com joomlaupdate is not there.

can anyone tell me why it's like this? my basic Joomla version was 3.2.

thanks

**Comment by andrepereiradasilva** [comment]
So it seems problem in your installation and not with the core joomla.

you can try to rebuild update sites.
And please go to http://forum.joomla.org for additional help.

@brianteeman close this please if you agree.

**Comment by brianteeman** [comment]
Closed
