### ISSUE TITLE
admin login not possible with php7, memcached with joomla 3.6.2

### ISSUE THREAD

**Issue by pgassmann** [joomla/joomla-cms#11959]
###  issue description

After joomla update from joomla 3.6.0 to 3.6.2, administator login does not work anymore.
Following error is shown after clickin the login button.

<pre>
Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time in /var/www/joomla/libraries/joomla/session/storage/memcached.php on line 66
</pre>

I have versioned the installation in git. when going back to 3.6.0, I can login again. After login I can reinstall the files from 3.6.2 with git and remain logged in, but relogin is not possible.

### System information (as much as possible)
```
=============
Systeminformationen
=============
php: Linux test 4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64
dbversion: 5.7.13-0ubuntu0.16.04.2-log
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 7.0.8-0ubuntu0.16.04.2
server: nginx/1.10.0
sapi_name: fpm-fcgi
version: Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36
```

#### Full Info:
[systeminfo-broken.txt](https://github.com/joomla/joomla-cms/files/457643/systeminfo-broken.txt) 
Systeminfo is saved after login with 3.6.0 and then updating the files.
No difference except version and status numbers between working and broken systeminfo.

### Additional comments

Same issue is reported in the forum: http://forum.joomla.org/viewtopic.php?f=709&t=933322

The memcached.php file has not changed between the two versions.

**Comment by brianteeman** [comment]
MemcacheD does not support php 7 https://pecl.php.net/package/memcached

**Comment by brianteeman** [comment]
https://github.com/php-memcached-dev/php-memcached/issues/213

**Comment by pgassmann** [comment]
php-memcached is packaged for debian/ubuntu and it is working correctly with joomla 3.6.0 only after update to 3.6.2 it is broken. where's the difference?

**Comment by brianteeman** [comment]
It might be packaged for debian but as seen in the links it is not supported

**Comment by pgassmann** [comment]
It works in 3.6.2 with session_handler memcache and cache_handler memcached

**Comment by pgassmann** [comment]
was not a permanent solution. now session_handler is set to 'none'

**Comment by brianteeman** [comment]
Memcached does not work with php 7. Don't try to use it.

**Comment by pgassmann** [comment]
joomla system page_cache plugin is working well with php7 and memcached.

global joomla caching in configuration.php is set to 0, but page_cache plugin is enabled. this is the fastest configuration for our huge page.

**Comment by ribo72** [comment]
The same error i faced with memcache 3.0.9-dev . But after search i saw that php7 with memcache and memcached has not full support

**Comment by csthomas** [comment]
Memcached as cache storage works on php7. 
Memcached as session storage may have problem as mentioned above.

**Comment by brianteeman** [comment]
I am closing this at this time as there is nothing we can do about the external library<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11959">issues.joomla.org/tracker/joomla-cms/11959</a>.</sub>
