### ISSUE TITLE
URGENT HELP! Website blank due to failed plugin- cannot view the website from the front end. Cannot login from the back end

### ISSUE THREAD

**Issue by kited** [joomla/joomla-cms#11963]
Hello,

I am new to this forum, and need urgent help with getting my website back online. I have contacted Dreamhost who host the website, they ran a diagnostic report across the site, and discovered that a plugin failed, which has caused the whole website to go blank. 

The website cannot be accessed from the front end or backend, therefore, I cannot even login to the administration page. As I am unable to login to the admin panel, I am unable to fix the faulty plugin. 

Can someone please advise how I can fix this? 

Many thanks

### Steps to reproduce the issue
Unknown. 

### Expected result
The expected result is to make the website live, and be able to login to the website's CMS/admin

### System information (as much as possible)
I have tried logging in to the website from the following devices/operating systems, and all have the same result
MacBook Pro OSX Safari/Chrome/Firefox
iPad mini Safari
Windows Chrome/Firefox

### Additional comments
Help help help!

![screen shot 2016-09-06 at 19 53 17](https://issues.joomla.org/uploads/1/f0640112717a49d9ad83a2d0222afe30.png)![screen shot 2016-09-06 at 19 53 22](https://issues.joomla.org/uploads/1/165c449fb3e149095dddccc35746aa6f.png)

**Comment by alikon** [comment]
Please use the forum for support http://forum.joomla.org
