### ISSUE TITLE
Image edit Modal uses the wrong template

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#11967]
### Steps to reproduce the issue
Create a site using the beez template
Create an article and add it to a menu item and use the protostar template for that menu item
In the front end login and edit the article
Select the insert image from the wysiwyg toolbar to open the image select modal

### Expected result
The modal opens in an iframe and is using the assigned protostar template

### Actual result
The modal opens in an iframe and is using the default template for the site - in this case beez

**Comment by dgt41** [comment]
The url is not specifying any template:
https://github.com/joomla/joomla-cms/blob/staging/plugins/editors/tinymce/tinymce.php#L737-L740
```php
$uploadUrl     = JUri::base() . 'index.php?option=com_media&task=file.upload&tmpl=component&'
				. $session->getName() . '=' . $session->getId()
				. '&' . JSession::getFormToken() . '=1'
				. '&asset=image&format=json';
```

Was this working before (3.6)? Reverting #11826 has any effect?

**Comment by brianteeman** [comment]
did a quick test on an old site and it looks like it might always have been this way

**Comment by dgt41** [comment]
Then, we can simply add `tmpl=' . JFactory::getApplication()->getTemplate() . '` in the url

**Comment by brianteeman** [comment]
... everywhere the modal gets loaded - I just gave one example

**Comment by dgt41** [comment]
here is a solution:
/Users/dimitris/Documents/github_projects/joomla1/plugins/editors-xtd/image/image.php
after line 40
```php
		$template  = $app->getTemplate();
```
and line 55
```php
			$link = 'index.php?option=com_media&amp;view=images&amp;tmpl=component&amp;e_name=' . $name . '&amp;asset='
				. $asset . '&amp;author=' . $author . '&template=' . $template;
```

/Users/dimitris/Documents/github_projects/joomla1/administrator/components/com_media/controller.php
replace after line 32 and before `switch($vName)
``php
		$app      = JFactory::getApplication();
		$vType    = JFactory::getDocument()->getType();
		$vName    = $this->input->get('view', 'media', 'string');

		if ($app->isSite())
		{
			$template = $this->input->get('template', 'protostar', 'string');
			$app->setTemplate($template);
		}
```

This will work only for front end as `setTemplate()` is only available there!

**Comment by brianteeman** [comment]
Can you submit it as a pr please

**Comment by dgt41** [comment]
https://github.com/joomla/joomla-cms/pull/11970

**Comment by brianteeman** [comment]
Closed as we have a PR
