### ISSUE TITLE
com_language overrides does not have Search Tools

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#11976]
### Steps to reproduce the issue

Go to Extensions --> Languages --> Overrides
### Expected result

Search tools like all other backend views.
### Actual result

![image](https://cloud.githubusercontent.com/assets/9630530/18323977/08d1f532-7532-11e6-9c4c-145797de15cd.png)
### System information (as much as possible)

Latest staging.
### Additional comments

The only one left, i think.

**Comment by brianteeman** [comment]
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11976">issues.joomla.org/joomla-cms/11976</a>.</sub>

**Comment by leadingcode** [comment]
confirm too

**Comment by brianteeman** [comment]
@andrepereiradasilva will you be able to do a PR for this? ;)

**Comment by andrepereiradasilva** [comment]
working on other things, no time for this now, maybe in the future if no ones does it ...

**Comment by franz-wohlkoenig** [comment]
Issue also on 3.7-staging:
![screen shot 2017-01-31 at 11 41 24 am](https://cloud.githubusercontent.com/assets/8235763/22461623/47f7df70-e7aa-11e6-9430-a7055fd1f699.JPG)

**Comment by brianteeman** [comment]
@andrepereiradasilva hoping you will be able to fix this as we need it even more for moving forward to J4 - i did have a go but got lost in the spaghetti

**Comment by tonypartridge** [comment]
Reviewing. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11976">issues.joomla.org/tracker/joomla-cms/11976</a>.</sub>

**Comment by brianteeman** [comment]
@tonypartridge were you able to do this?

**Comment by tonypartridge** [comment]
I got partially there. But the way filtering has been enabled on this is a
bit strange and it's not a simple move of this, we need to change the
filters too. Will try and take another look.

-- 
Tony Partridge

From: Brian Teeman <notifications@github.com> <notifications@github.com>
Reply: joomla/joomla-cms
<reply@reply.github.com>
<reply@reply.github.com>
Date: 18 August 2017 at 14:19:58
To: joomla/joomla-cms <joomla-cms@noreply.github.com>
<joomla-cms@noreply.github.com>
CC: Tony Partridge <admin@xtech.im> <admin@xtech.im>, Mention
<mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [joomla/joomla-cms] com_language overrides does not have
Search Tools (#11976)

@tonypartridge <https://github.com/tonypartridge> were you able to do this?

**Comment by brianteeman** [comment]
Thanks

**Comment by ghost** [comment]
closed as having Pull Request #21695
