### ISSUE TITLE
Html broken on the new module order field

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#11984]
### Steps to reproduce the issue

Use ajax power on module order field  #11040 

@dgt41 

### Expected result
chzn-container chzn-container-single

So the style is the same as other dropdowns

error: 
````html
module-ajax-ordering""=""
````

and

````html
data-attr="class=" 
````

### Actual result
````html
<div class="module-ajax-ordering" id="parent_jform_ordering" abp="579" data-name="jform[ordering]" module-ajax-ordering""="" data-attr="class=" data-client-id="0" data-position-element="com_modules.module_0" data-ordering="0" data-element="parent_jform_ordering" data-url="index.php?option=com_modules&amp;task=module.orderPosition&amp;d7c320ae8d444f2874a1927bf9fb6967=1">
````

**Comment by dgt41** [comment]
This field was created without the chosen dependency, if you want to add chosen you need to modify the script

**Comment by dgt41** [comment]
@810 check #11992

**Comment by brianteeman** [comment]
Closed as we have a PR - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11984">issues.joomla.org/joomla-cms/11984</a>.</sub>
