### ISSUE TITLE
HTTP status codes shouldn't be localized

### ISSUE THREAD

**Issue by piotr-cz** [joomla/joomla-cms#11980]
### Steps to reproduce the issue

1) Install polish language
2) Trigger error page
3) Inspect document response **Status code** (in Chrome Inspect > Network > click on first item)
### Expected result

`404 Not Found`
### Actual result

`404 Artyku%C5%82u nie znaleziono`
### System information (as much as possible)

Tested on Joomla v3.4.8 and v3.6.2
### Additional comments

Actual translation is _Artykułu nie znaleziono_, but HTTP status messages are ASCII-only.

As @mbabker pointed out [here](https://github.com/joomla/joomla-cms/pull/10847#issuecomment-245397173), 

> The status code is using the Exception object's message, not a HTTP
> standard message.  So that's why.

There should be a map of _status code: status message_ (at least for error codes used by Joomla) and JDocumentError should pick one [here](https://github.com/joomla/joomla-cms/blob/3.6.2/libraries/joomla/document/error.php#L94)

Similar to how it's set in [Slim\Http\Response](https://github.com/slimphp/Slim/blob/3.5.0/Slim/Http/Response.php)

**Comment by andrepereiradasilva** [comment]
@piotr-cz can you make a PR?

**Comment by piotr-cz** [comment]
I'm not sure where to store the map. Should it be _JErrorPage_?

BTW: The HTTP reason phrase for 403 is `Dost%C4%99p zabroniony`

**Comment by mbabker** [comment]
Make a `Response` object that has these mappings.  To save some work, just grab the data out of [Symfony's Response object](https://github.com/symfony/http-foundation/blob/master/Response.php).  Now there's a valid map for all known standard codes.

You could easily throw it in `JResponse`; undeprecate the class (it was deprecated since we moved all of its existing logic to the web application class) and add the new logic there.

**Comment by piotr-cz** [comment]
Shouldn't the map go to JApplicationWeb then?
I just saw [there is](https://github.com/joomla/joomla-cms/blob/3.6.2/libraries/joomla/application/web.php#L83) already a $responseMap array

**Comment by mbabker** [comment]
That works too.  I didn't know if it had a hard reference to the redirect code or if it was "good enough" for general use off the top of my head.

**Comment by yild** [comment]
There are actually more instances with misc entries:

https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_redirect/models/fields/redirect.php#L38
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/application/web.php#L84
https://github.com/joomla/joomla-cms/blob/staging/libraries/vendor/joomla/application/src/AbstractWebApplication.php#L78

**Comment by piotr-cz** [comment]
I'd love to split whole phrases like `HTTP/1.1 300 Multiple Choices` in JApplicationWeb::$responseMap into _protocol version_, _code_ and _text_ just like in [Symfony\Component\HttpFoundation\Response](https://github.com/symfony/http-foundation/blob/3.1/Response.php#L125) or [Slim\Http\Response](https://github.com/slimphp/Slim/blob/3.5.0/Slim/Http/Response.php#L48), make property public static and refactor JApplicationWeb::redirect method accordingly.

As ATM it's private, are there any reasons to not to do so?

Moreover what's the workflow?
Start with Joomla Framework Application _AbstratWebApplication_
then _JApplicationWeb_
and then adjust _JDocumentError::render_ method?

**Comment by yild** [comment]
btw @piotr-cz if you search whole code for HTTP/1.1 you will find more files in which they can be found than I posted earlier but I don't know if there is need for them to be translatable (even to plain ASCII form).

**Comment by mbabker** [comment]
With https://github.com/joomla/joomla-cms/commit/e4d04513fb4a462bfdd97b85ab97e29c0ac8e758 the status header only includes the Exception message if error reporting is at maximum.
