### ISSUE TITLE
Automatically add "-" in the template override editor!

### ISSUE THREAD

**Issue by saman222** [joomla/joomla-cms#12000]
### Steps to reproduce the issue

When i edit the code in the override section of Joomla, 2 "-" added automatically after save in my code.look at the movie please:
http://screencast.com/t/7BEIiqbrK

### System information (as much as possible)

i use joomla 3.6 and i want to override the .php file.This two - added in script and javascript tag.In the movie it's compeletlly clear.
http://screencast.com/t/7BEIiqbrK

**Comment by brianteeman** [comment]
This is NOT a joomla issue. The problem is that you have RS Firewall installed and you have NOT configured it correctly - check the documentation for RS Firewall. They have covered this exact situation in their documentation
