### ISSUE TITLE
Redirect component bulk updates - add ability to set status code

### ISSUE THREAD

**Issue by astrodene** [joomla/joomla-cms#12001]
### Steps to reproduce the issue
create a custom error page such as 410.html
Set redirect component to advanced
In redirect component select multiple entries
select destination url

### Expected result
Ability to select the 410 status code to apply it to all the selected urls

### Actual result
no option to select

### System information (as much as possible)
Joomla 3.6.2

### Additional comments
You can currently bulk redirect to the new url but then have to open each url individually to set the status code

**Comment by franz-wohlkoenig** [comment]
This has been closed due to lack of response to the requests above - it can always be reopened in the future if it is updated.
