### ISSUE TITLE
Loop redirect on profile page when SEF is OFF and session expired

### ISSUE THREAD

**Issue by Fedik** [joomla/joomla-cms#12002]
### Steps to reproduce the issue
* install testing data
* turn off SEF
* login on the frontend
* open the profile page (on testing data it is `index.php?option=com_users&view=profile&Itemid=201`)
* open the browser console, and remove all cookies (imitate session expire)
* push F5

### Expected result
You redirected to the login page

### Actual result
Loop redirect

### System information (as much as possible)
Joomla! 3.6 and staging

### Additional info
All works fine when SEF is on. 
I think it something with router, it add the same `Itemid=201` for `profile` and  `login` view.

found by @gruz

**Comment by RonakParmar** [comment]
I am able to reproduce this issue, I have cleared cookies and reloaded page (F5) I got error page, please see screen dump of that page.
![screen shot 2016-09-12 at 22 50 09](https://issues.joomla.org/uploads/1/f8294843fac5297436f2473ad56b536e.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12002">issues.joomla.org/joomla-cms/12002</a>.</sub>

**Comment by AlexRed** [comment]
I can't reproduce it on 3.7.0 stagin. 
Redirect to the login page ok for me on Chrome<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12002">issues.joomla.org/tracker/joomla-cms/12002</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@Fedik @RonakParmar did you get this issue on latest Staging?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12002">issues.joomla.org/tracker/joomla-cms/12002</a>.</sub>

**Comment by Fedik** [comment]
it seems fixed, cannot reproduce it anymore
