### ISSUE TITLE
If the Login link is set to "guest" User get´s an alert that he cannot view this ressource

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#12010]
### Steps to reproduce the issue
Set the Login Link Menü item to "guest"
Login into the site as superadmin,
Everything is fine but there is a message that you are not allowed to access this resource

### Expected result
The Alert shouldn´t be there

### Actual result
Every User get´s this alert

### System information (as much as possible)
Joomla 3.6.2

**Comment by Radek-Suski** [comment]
supplement: I was able to find out that after a successful login the controller redirects back to the login page (which is set for guests only) even if "return" is provided.

**Comment by RonakParmar** [comment]
I have followed above steps but not able to see and message at front side after logged-in using superuser. Do I have to click specific page to see the message?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12010">issues.joomla.org/joomla-cms/12010</a>.</sub>

**Comment by izharaazmi** [comment]
The guest access is kind of tricky thing as it is not a real access level IMO. Any user can logout to get that access. So basically we are not denying rather hiding things to unclutter the site for registered users.
Therefore, whatever is set to 'guest' only access it should not be denied to anyone logged in. Now its a matter of decision whether to allow or internally redirect to a better substitute page, if such a page was accessed directly. IMO, this decision changes depending on context.
But one thing I am almost sure that there is no point "denying access" to it.

**Comment by brianteeman** [comment]
Sorry @izharaazmi but that is completely wrong

**Comment by franz-wohlkoenig** [comment]
@coolcat-creations do you this Issue also on latest Staging?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12010">issues.joomla.org/tracker/joomla-cms/12010</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened in the future if it is updated.
