### ISSUE TITLE
Logging in using cookie (ie via remember me) doesnt set user id in #__session table

### ISSUE THREAD

**Issue by dandpclements** [joomla/joomla-cms#12012]
### Steps to reproduce the issue

Create clean 3.6.2 install
Login to back end and create user (eg DAVE)
Exit Browser
Delete all entries in Session table
Enter URL for front end of website, logon with created user ensure remember me ticked
Browse session table - guest = 0, userid and username set correctly in session table
Exit browser
Delete all entries in Session table
Enter URL for front end of table - no need to logon as user id  remembered using cookie
Browse session table - guest = 1 , userid = 0, username blank. THIS IS INCORRECT

### Expected result

All authenticated users should have session record set with Guest = 0, userid and username set correctly

### Actual result

Authenticated user logged in using cookie has session record where Guest = 1 and userid and username not set

### Additional comments

This happened on my website after upgrading from 3.6.0 to 3.6.2. To prove it wasnt my website I did a clean install of 3.6.2 on my PC using Xampp and proved error occured

**Comment by aidanwhiteley** [comment]
Hi,

see https://issues.joomla.org/tracker/joomla-cms/11691 and https://github.com/joomla/joomla-cms/issues/11556

Sounds like the same issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12012">issues.joomla.org/joomla-cms/12012</a>.</sub>

**Comment by brianteeman** [comment]
I am closing this at it would appear to have been fixed elsewhere as referenced by @aidanwhiteley <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12012">issues.joomla.org/tracker/joomla-cms/12012</a>.</sub>
