### ISSUE TITLE
[regression] 3.7 redirect

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#12017]
### Steps to reproduce the issue
Checkout 3.7 branch and go to com_redirect

### Expected result
Message that The Redirect System Plugin is disabled. It needs to be enabled for this component to work.

### Actual result
A warning and an error that The Redirect System Plugin is disabled. It needs to be enabled for this component to work.
![lntf](https://cloud.githubusercontent.com/assets/1296369/18436881/6a6747fc-78f2-11e6-94a0-9bc58855f598.png)

**Comment by C-Lodder** [comment]
submitting a PR for this

**Comment by C-Lodder** [comment]
PR submitted: https://github.com/joomla/joomla-cms/pull/12019

@brianteeman There's also a duplicate message on `com_search`. Warning and error. I can fix this but which should we be using, warning or error?

**Comment by zero-24** [comment]
Closing as there is a PR. Thanks
