### ISSUE TITLE
Virtuemart payment plugin "Sofort" does not support custom plugin notification 

### ISSUE THREAD

**Issue by einbeinigerpeter** [joomla/joomla-cms#12027]
### Steps to reproduce the issue
This is line 455 of sofort.php:
$modelOrder->updateStatusForOneOrder($payments[0]->virtuemart_order_id, $order_history, false);
The "False" parameter disables all notifications of custom VM plugins. Furthermore the nessessary methods are not implemented, to notificate custom plugins about a payment.

### Expected result
When a customer pays by using this payment gateway, custom plugins are not notified about the action. All store-settings have to be done manually.

### Actual result
Custom plugins arent informed about payments. Paypal contains the nessessary methods and is working fine.

### System information (as much as possible)
Joomla 3.6.2
Virtuemart 3.0.16

### Additional comments
Maybe other payment plugins miss this functionality too. Paypal is working fine, the you have emplemented this feature.

**Comment by brianteeman** [comment]
This is the place for reporting issues in the core Joomla and not its extensions. You should report this issue to the virtuemart team.
