### ISSUE TITLE
Frontend: New module order field isn't displayed

### ISSUE THREAD

**Issue by Minei3oat** [joomla/joomla-cms#12031]
### Steps to reproduce the issue
Edit a module in frontend.
Try to change the module ordering.

### Expected result
There is a list for changing the position, like it is in the backend.

### Actual result
There is only the `div`.

**Comment by dgt41** [comment]
Which template are you using?
Can you state the steps to reproduce this?

**Comment by Minei3oat** [comment]
This issue appears with Protostar and Beez3.

###Steps to reproduce the issue:
 - Login into frontend
 - Click the `Edit module`-button of a module
 - Look at the field `Ordering`

**Comment by dgt41** [comment]
I can confirm that:
![screen shot 2016-09-13 at 23 40 23](https://cloud.githubusercontent.com/assets/3889375/18490646/969dd36c-7a0b-11e6-82d5-c06eb6e79bb8.png)

 Please check https://github.com/joomla/joomla-cms/pull/12032

**Comment by Minei3oat** [comment]
Closing as there is a PR.
