### ISSUE TITLE
Possibility to assign the template during Batch process

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-cms#12044]
### Steps to reproduce the issue

On a multilingual site.
Batch (Copy) some Menus from a language to another.
Params are correctly copied except you will have to reopen every articles to assign the right dedicated Template.
### Expected result

It would be great if during the batch process, it would be possible to assign also the template.

Thoughts?

**Comment by brianteeman** [comment]
Its nothing to do with it being a multilingual site. You might want to assign a menu item to a different template on a monolingual site as well

**Comment by MATsxm** [comment]
yes... this is not the point

**Comment by franz-wohlkoenig** [comment]
Workaound #13194

**Comment by franz-wohlkoenig** [comment]
closed as Duplicate of #13194 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12044">issues.joomla.org/tracker/joomla-cms/12044</a>.</sub>

**Comment by MATsxm** [comment]
@franz-wohlkoenig yes... duplicate as this was #12044
