### ISSUE TITLE
Canonical URL in subdirectory

### ISSUE THREAD

**Issue by thinkerytim** [joomla/joomla-cms#12041]
### Steps to reproduce the issue

1. Create a site that is accessed from a subdirectory (eg. using joomlabox, `joomla.box/mysite`)
2. configure SEF plugin to use "http://joomla.box/mysite" as canonical site domain

### Expected result
I'd expect to see the canonical URL say something like `<link href="https://joomla.box/mysite/index.php/categories/8-testcategory/2-test" rel="canonical">`

### Actual result
The subdomain is repeated, resulting in `<link href="https://joomla.box/mysite/mysite/index.php/categories/8-testcategory/2-test" rel="canonical">`

### System information (as much as possible)
Joomla 3.6.2 
Joomlabox VM

**Comment by brianteeman** [comment]
I would say that is the expected behaviour as the subdirectory is not part of the domain. The domain in this example is just http://joomla.box
