### ISSUE TITLE
Not the expected behavior during the batch process

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-cms#12045]
### Steps to reproduce the issue
On a multilingual site.
Go to: Menus ->All Menus Items
Select some menus and then try to batch them.

### Expected result
- Not being able to batch (then an explaination message)
- being able to batch
in no case, having the message:
![screen shot 2016-09-15 at 10 11 04](https://issues.joomla.org/uploads/1/7f26a15260df231b9e6df383c23c7161.png)

**Comment by brianteeman** [comment]
Its nothing to do with multilingual

This is the expected behaviour. As it says in the message you must have a menu selected first. You cannot do a batch process from the All Menus selection

**Comment by brianteeman** [comment]
I assume you are confusing the terms "menu" and "menu items"

**Comment by MATsxm** [comment]
look closer (I know it's dark) the menu items are selected

**Comment by brianteeman** [comment]
Look closer at what the message says and at what I wrote

**Comment by MATsxm** [comment]
see :+1:
