### ISSUE TITLE
Component variable request with "editor" form field

### ISSUE THREAD

**Issue by ghasemy50** [joomla/joomla-cms#12040]
### Steps to reproduce the issue
when i add an variable request for my component, if i select "editor" field type with this code:
&lt;field name="description" type="editor" label="Description" description="Description of product." filter="safehtml"/&gt;
or i select another filter attribute for editor , can't correctly save

### Expected result
save correctly

### Actual result
after save all break lines are convert to double underline.
for example , this code:
&lt;p&gt;Lorem Ipsum&lt;/p&gt;
&lt;p&gt;Dolor sit ammet&lt;/p&gt;
is convert to:
&lt;p&gt;Lorem Ipsum__Dolor sit ammet&lt;/p&gt;

### System information (as much as possible)
PHP Built On     Windows NT SYSTEM4 6.1 build 7601 (Windows 7 Ultimate Edition Service Pack 1) i586
Database Version     5.6.17
Database Collation     utf8_general_ci
Database Connection Collation     utf8mb4_general_ci
PHP Version     5.5.12
Web Server     Apache/2.4.9 (Win32) PHP/5.5.12
WebServer to PHP Interface     apache2handler
Joomla! Version     Joomla! 3.6.2 Stable [ Noether ] 4-August-2016 23:41 GMT
Joomla! Platform Version     Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent     Mozilla/5.0 (Windows NT 6.1; rv:48.0) Gecko/20100101 Firefox/48.0

### Additional comments
all editors in module parameter , plugin parameter , joomla article and etc... are correct,but just in this section not work.
Tested on Joomla 3.6.0 and 3.6.2

**Comment by brianteeman** [comment]
There is nothing in the core of Joomla that could do this. You probably have some extension installed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12040">issues.joomla.org/joomla-cms/12040</a>.</sub>
