### ISSUE TITLE
Getting JAuthentication: :authenticate: Failed to load plugin: plgauthenticationslogin Error

### ISSUE THREAD

**Issue by imranisquare** [joomla/joomla-cms#12054]
### Steps to reproduce the issue

after uninstalling slogin still getting this error.
I have deleted the folder as well.

### Expected result

n/a

**Comment by imranisquare** [comment]
and also not able to post a new topic in http://forum.joomla.org/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12054">issues.joomla.org/joomla-cms/12054</a>.</sub>

**Comment by brianteeman** [comment]
As this error is related to the slogin extension you must contact them for support. This tracker is just for issues with the core of joomla.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12054">issues.joomla.org/joomla-cms/12054</a>.</sub>
