### ISSUE TITLE
[beez] icons missing

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#12050]
### Steps to reproduce the issue

Enable beez3 as your template
login on the front end
click to edit an article
### Expected result

All icons on the editor toolbar to be present 
### Actual result

icons for the xtd-editor buttons are missing
### System information (as much as possible)

joomla 3.6.2

**Comment by Minei3oat** [comment]
The classes for the images are not defined.

**Comment by Minei3oat** [comment]
They must defined in [media/editors/tinymce/skins/lightgray/skin.min.css](https://github.com/joomla/joomla-cms/blob/staging/media/editors/tinymce/skins/lightgray/skin.min.css)

**Comment by Minei3oat** [comment]
Protostar imports [media/jui/less/icomoon.less](https://github.com/joomla/joomla-cms/blob/staging/media/jui/less/icomoon.less) which defines the needed classes.

**Comment by dgt41** [comment]
TinyMCE got it's own version of icomoon (named tinymce) https://github.com/joomla/joomla-cms/tree/staging/media/editors/tinymce/skins/lightgray/fonts and the buttons are using that one. The problem that exist is that tinyMCE got two versions of that font with the one having a lot less icons and Joomla is using that as default for the desktop.
To test edit tinymce.php and https://github.com/joomla/joomla-cms/blob/staging/plugins/editors/tinymce/tinymce.php#L798
 replace
```php
$smallButtons = 'toolbar_items_size: "small",';
```
with
```php
$smallButtons = '';
```

**Comment by brianteeman** [comment]
So long and farewell
