### ISSUE TITLE
Warning Field required: Title

### ISSUE THREAD

**Issue by quannv** [joomla/joomla-cms#12072]
### Steps to reproduce the issue
I created the CRUD functions for my component but I got this message "Warning  Field required: Title" even the title field is filled already.

I debug then go to the line 1933 of libraries\joomla\form\form.php

Replace 
```php
if ($required)
		{
			// If the field is required and the value is empty return an error message.
			if (($value === '') || ($value === null))
			{
```

by

```php

if ($required && !value){{

```

Then it works.

### System information (as much as possible)
Joomla 3.6.2
PHP 5.6

### Additional comments

I think need to update the form.php

**Comment by franz-wohlkoenig** [comment]
@quannv can you confirm this Issue on latest Staging?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12072">issues.joomla.org/tracker/joomla-cms/12072</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened in the future if it is updated.

**Comment by BoldNewMedia** [comment]
This issue remains in 3.7.2. I can confirm the fix outlined by @quannv resolved the problem for me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12072">issues.joomla.org/tracker/joomla-cms/12072</a>.</sub>

**Comment by dxxx** [comment]
i have this issue in 3.7.4 will test and  let you know if this works
