### ISSUE TITLE
Why is Joomla issue tracker requesting access to my GitHub repositories?

### ISSUE THREAD

**Issue by thoni56** [joomla/joomla-cms#12074]
### Steps to reproduce the issue
Register with issues.joomla.org and use GitHub as your authentication.

### Expected result
GitHub prompting for simple user info permissions ("Authorize application";"Personal User data (email only)"), as per https://developer.github.com/guides/basics-of-authentication/.

### Actual result
GitHub requesting access to repositories.

**Comment by MATsxm** [comment]
Please follow this https://github.com/joomla/jissues/issues/863 on the Isuue Tracker Repo.
Thanks

**Comment by zero-24** [comment]
Please report that to https://github.com/joomla/jissues as this in not the CMS that does anything with your Github Data. IIRC this is known and they are working on that.

**Comment by thoni56** [comment]
Sorry, was mislead by the "Please report issues here"-link.

**Comment by mbabker** [comment]
Also take a look at https://github.com/joomla/joomla-websites/issues/441 where there's a full explanation.  Until we sort out using integrations instead of OAuth to perform actions on behalf of your user account, we're stuck between a rock and a hard place on the permission scope.
