### ISSUE TITLE
Unicode E280A8 in title breaks selection of article in menu

### ISSUE THREAD

**Issue by jochendaum** [joomla/joomla-cms#12083]
### Steps to reproduce the issue
- Create a new article in the Joomla backend, not the id, example 999
- run this SQl query to ensure title contains unicode E280A8: "update #__content set title='example title\uE280A8' where id=999"
- Create a new menu item, Single Article, try to select the new article

### Expected result

The article is selected for the menu item

### Actual result

Nothing happens when clicking the article title

### System information (as much as possible)

Joomla 3.6

### Additional comments

I have found a similar issue of lack of handling unicode space characters in jSeblod: https://github.com/jochendaum/SEBLOD/pull/1#issuecomment-246608653

**Comment by zero-24** [comment]
Do you have uft8mb4 for your database? See in the Systeminformation

**Comment by jochendaum** [comment]
Yes, I think so:

Setting	Value
 
PHP Built On	Linux apache2.greentree.com 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64
Database Version	5.6.27-log
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.8-0ubuntu0.16.04.2
Web Server	Apache/2.4.18 (Ubuntu)
WebServer to PHP Interface	fpm-fcgi
Joomla! Version	Joomla! 3.6.2 Stable [ Noether ] 4-August-2016 23:41 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

**Comment by zero-24** [comment]
Please set you database collation to utf8mb4 else it is a feature of mysql to cut after a unicode char

**Comment by jochendaum** [comment]
This doesn't solve the problem. Here are my updated settings:

System Information
Setting	Value
 
PHP Built On	Linux autodesktop2 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64
Database Version	5.7.13-0ubuntu0.16.04.2
Database Collation	utf8mb4_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.8-0ubuntu0.16.04.2
Web Server	Apache/2.4.18 (Ubuntu)
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.6.2 Stable [ Noether ] 4-August-2016 23:41 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

**Comment by zero-24** [comment]
Did you resave the value?

**Comment by jochendaum** [comment]
Have just gone into article and saved.

Then retried. No change

**Comment by brianteeman** [comment]
I cannot replicate this issue 

Database Version	5.5.42
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12083">issues.joomla.org/tracker/joomla-cms/12083</a>.</sub>

**Comment by richard67** [comment]
@zero-24 Database collation is only defining the defaut to be used when newly creating tables or columns without specifying the character set and collation. It does not modify existing tables or columns. Joomla! always does specify it in their create or alter table statements, so changing datavase default collation is definitely no help. This should be commonly known, but always again I find this useless and wrong "help" here or in the forums.

**Comment by zero-24** [comment]
Thanks so we need to check the actual collation on the content table? @richard67

**Comment by richard67** [comment]
@zero-24 Yes.

**Comment by zero-24** [comment]
@jochendaum can you check that and come back to us with the actual collation on the table?

**Comment by zero-24** [comment]
Thanks @richard67 !

**Comment by brianteeman** [comment]
I am closing this at this time as it was not replicated and the original poster has not responded. If necessary it can always be reopened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12083">issues.joomla.org/tracker/joomla-cms/12083</a>.</sub>
