### ISSUE TITLE
Masking string does delete language file

### ISSUE THREAD

**Issue by idefax** [joomla/joomla-cms#12105]
### Steps to reproduce the issue
Backend > Extensions > Lanuage(S) > Overrides

Create a new language override or open an existing one. In the textarea labeled "Text" enter following string: _QQ_ 
It's underscoreQQunderscore which is used for masking special characters. Fore some reason the undersocre is not visible here.
After save it.
  

### Expected result
An new language override is created or an exiting one is updatet.

### Actual result
The override file, for example /language/overrides/en_GB-override.ini gets deleted.

### System information (as much as possible)
Problem reproduced on localhost on Windows 7 PC and on Linux Webserver. 

### Additional comments
Reproduced it with en_GB-override.ini and de_DE-override.ini.

**Comment by Bakual** [comment]
Why do you want to put QQ into it? Just write the ", the overrider will automatically do the QQ for you.

**Comment by Bakual** [comment]
I'm going to close this since there isn't a need for it. You can of course reopen it if you disagree :smile:
