### ISSUE TITLE
Per-user Editor setting affects all users

### ISSUE THREAD

**Issue by njbair** [joomla/joomla-cms#12113]
### Steps to reproduce the issue

1. In User Manager, click on a user account, click Basic Settings, and change the Editor.
2. Save & close the user account.
3. Edit another user account and change the Editor to a different setting.

### Expected result

Each user's Editor setting should be retained.

### Actual result

Each user is set to whichever editor was most recently set.

### System information (as much as possible)

Joomla 3.6.2
Apache HTTPD
PHP5 FPM
Ubuntu 14.04

### Additional comments

I noticed this following the most recent update. I do have the Switch Editor plugin installed, but I disabled it while troubleshooting the issue and the issue still occurs.

**Comment by zero-24** [comment]
@njbair can you double check your global setting? I can not confirm this on 3.6.2

**Comment by brianteeman** [comment]
I am unable to confirm this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12113">issues.joomla.org/joomla-cms/12113</a>.</sub>

**Comment by njbair** [comment]
Sorry folks, I just upgraded another Joomla installation to 3.6.2 and the problem is not present there. Looks like a misconfiguration of some kind on my end. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12113">issues.joomla.org/joomla-cms/12113</a>.</sub>

**Comment by zero-24** [comment]
Ok closing that thanks.
