### ISSUE TITLE
1064 error when opening index webpage

### ISSUE THREAD

**Issue by leslieongit** [joomla/joomla-cms#12119]
### Steps to reproduce the issue
Edit a page via SP Page Builder > Duplicate the tabs into two >Work simultaneously > Visit site >Error

### Expected result
Load index page for website, as usual

### Actual result
1064 MySQL error

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND (m.publish_up = '0000-00-00 00:00:00' OR m.publish_up <= '2016-09-21 09:30:1' at line 3 SQL=SELECT m.id, m.title, m.module, m.position, m.ordering, m.content, m.showtitle, m.params FROM #__modules AS m WHERE m.published = 1 AND m.id = AND (m.publish_up = '0000-00-00 00:00:00' OR m.publish_up <= '2016-09-21 09:30:18') AND (m.publish_down = '0000-00-00 00:00:00' OR m.publish_down >= '2016-09-21 09:30:18') AND m.access IN (1,1) AND m.client_id = 0

### System information (as much as possible)
Red Hat Enterprise Linux Platform
Dual Quad Core Intel® Xeon® processors
32 GB RAM
Dual SAS Drive (for the operating system)
RAID Mirroring (for the operating system)
Dual Power Supplies
Quad Gigabit Network Adapters

**Comment by zero-24** [comment]
Can you confirm this issue without using SP Page Builder? If not it is a SP Page Builder issue as they don't use the DB Nulldate via the API

**Comment by leslieongit** [comment]
Yes, i disabled the SP Builder (Plugin, Component and Module) and loaded the website in a Chrome incognito, but the same error still being desplayed

**Comment by zero-24** [comment]
How can you reproduce that error on the core 3.6.2 without 3party extensions?

**Comment by leslieongit** [comment]
I'm sorry, cleared my browser cache, and error disappeared. Will chick with Helix Framework page for their support.

**Comment by brianteeman** [comment]
Closed as not a Joomla issue
