### ISSUE TITLE
Show wrong Persian content in "Versions/History"

### ISSUE THREAD

**Issue by amir-armaghan** [joomla/joomla-cms#12117]
### Steps to reproduce the issue

When there is an Article with Persian (my situation) content in it.
In Content -> Articles -> [a Persian Article] -> Versions
Then click on an old version.

### Expected result

Expected to see the old version with right encoding.

### Actual result

![version/history](http://armandis.com/sjh52g/images/history-version-3-6.JPG "wrong content type encoding in joomla 3.6.2 versions")

**Comment by infograf768** [comment]
I do not get this error here:

![screen shot 2016-09-21 at 18 14 57](https://cloud.githubusercontent.com/assets/869724/18719351/59a8d5e8-8027-11e6-8b72-ed6d1bf6b554.png)

Are you sure the original article is UTF8? Can you attach here a text file containing the text of the original article?

**Comment by amir-armaghan** [comment]
Yes, it is UTF-8. I've attached a simple text file in Persian.
[temp1.txt](https://github.com/joomla/joomla-cms/files/485681/temp1.txt)
After your comment, I tested more articles and see many of them have this problem, yet some of them seems OK. For example see the following view from One article; older versions are fine but the newer versions aren't:
![wpersian2](https://cloud.githubusercontent.com/assets/4126189/18721313/64141d06-801f-11e6-8e00-d39ea87a60c4.JPG)
![wpersian3](https://cloud.githubusercontent.com/assets/4126189/18722179/57f702d2-8023-11e6-9bc5-a91e248dd2c4.JPG)

To be honest, I am not sure when this problem happens, but as I use "Versions" a few times a week, I can confirm that I haven't had this problem in Joomla! 3.6.0 and this happened after updating to Joomla 3.6.2.

If I can provide more information, please tell.

**Comment by infograf768** [comment]
The file you attached contains only 2 lines It is not the original article for which you have issues.
It is badly encoded UTF8 WITH BOM and windows CRLF. Using these 2 lines does not create issues here.
Remark that in your screenshots above the article for which you have no issue has the correct label "Intro Text" while the other has nothing.
It looks to me that the articles you have issues with are copied/paste from an original which is NOT utf8.

**Comment by infograf768** [comment]
BTW, if you have time and use the fa-IR lang pack, I need testers here https://github.com/joomla/joomla-cms/pull/12138 as I just remarked with this Issue of yours that the jalali date was not displayed in version history

**Comment by amir-armaghan** [comment]
If you have time, I can give you one username& password to check it yourself. I think this problem is not because of not being UTF-8.

I tested this problem in a few joomla 3.6.2 websites. nearly 50% of them have a similar problem and others don't (in my case) . I tried to check differences like PHP version or other settings, but the only difference that came to my mind is that the problem is in websites which are older. I mean those were originally 3.2 (at least) and then they are updated to newer versions, while others are updated from earlier versions. Maybe it is not the cause, but just wanted to notice.

Note: Typing in Persian or Copy&Paste didn't make any difference.
Note: In the source of troubled page the first lines are cut; it doesn't have:
 `<!DOCTYPE html>
<html lang="en-gb" dir="ltr">
<head>
...
<h3>`

Just starts from `<h3>`.

**Comment by infograf768** [comment]
OK, Please send a mail to me through my forum account:
http://forum.joomla.org/memberlist.php?mode=viewprofile&u=14

I will need access to your db too.
BTW, first please check collation of your db and tables.

**Comment by infograf768** [comment]
I got the same result as you did on your site until I modified the view in the browser to use Unicode.
![screen shot 2016-09-24 at 11 43 12](https://cloud.githubusercontent.com/assets/869724/18807622/56bd5210-824c-11e6-8b9a-b3733083ecf9.png)

![screen shot 2016-09-24 at 12 08 43](https://cloud.githubusercontent.com/assets/869724/18807747/bb7d2dd0-824f-11e6-8aa8-b74f8dac5919.png)


This can normally be solved also by using in the .htaccess the line:
`AddDefaultCharset UTF-8`, but it looks you have not implemented .htaccess on that site.

**Comment by infograf768** [comment]
It looks like the http header sent by your Apache are wrong:
![screen shot 2016-09-24 at 12 23 34](https://cloud.githubusercontent.com/assets/869724/18807830/e4568a9c-8251-11e6-9c84-1079f9e62b68.png)


This is what I get here for my test site:
![screen shot 2016-09-24 at 12 24 31](https://cloud.githubusercontent.com/assets/869724/18807837/f9cf1e70-8251-11e6-8a3e-028cf8cb819e.png)

So, basically, I think this is not a Joomla issue

**Comment by amir-armaghan** [comment]
Thanks for your test.
Actually if you look the source of this page, you will see there is no header for this page and as I mentioned before it is cropped. It should be start by <html> tag but starts from <h3> tag and ignores previews lines.

**Comment by infograf768** [comment]
Not really. One should look at the generated source, not at source.
Here it gives:
![screen shot 2016-09-24 at 12 35 36](https://cloud.githubusercontent.com/assets/869724/18807887/78de118e-8253-11e6-9fe8-c8f70b6daf73.png)

**Comment by amir-armaghan** [comment]
Sorry I didn't get your point exactly. I mean in troubled page there are some missing lines.
please take a look at my page:
![wr-pere2](https://cloud.githubusercontent.com/assets/4126189/18807961/e0e2b33a-8261-11e6-89b4-b963e32c3bb2.jpg)
in comparison to yours, there is no metadata or script here.
![pree](https://cloud.githubusercontent.com/assets/4126189/18807979/3c61725a-8262-11e6-8b2f-802d989f9bb9.jpg)

**Comment by infograf768** [comment]
I can see only one possible issue: your LiteSpeed V6.9 server.

**Comment by brianteeman** [comment]
I am closing this at this time at it is not a core joomla bug but a server configuration issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12117">issues.joomla.org/tracker/joomla-cms/12117</a>.</sub>
