### ISSUE TITLE
Joomla! Control Panel

### ISSUE THREAD

**Issue by fabclan1998** [joomla/joomla-cms#12111]
### Steps to reproduce the issue
![screen shot 2016-09-20 at 12 15 33](https://issues.joomla.org/uploads/1/bae1cb141e20bf699c75ce8c0474a044.png)
Hi?i have problem with my CP Joomla!

### Additional comments
Win 7 Ultimate x32

**Comment by zero-24** [comment]
Please use the forum for support http://forum.joomla.org it looks like you have issues on a outdated version (2.5) Thanks.
