### ISSUE TITLE
com_tags "Page Title" in Browser is shown from menu item, should be from single tag (SEO Issue)

### ISSUE THREAD

**Issue by seagul30** [joomla/joomla-cms#12158]
### Steps to reproduce the issue
Create content item "Test item" with tags "Test tag1" and "Test tag2"
Create menu item type "Tags - list of all tags" called "Tags list"

### Expected result
Click menu item "Tags list" in frontend --> Browser Page title is "Tags list" --> ok
Click single tag "Test tag1" in list to get tag detail view --> Browser Page title is "Test tag1"

### Actual result
Click single tag "Test tag1" in list to get tag detail view --> Browser Page title is still "Tags list"

### System information (as much as possible)
Joomla 3.6.2 (no extensions)

### Additional comments
If I don't add the menu item for tags and I only use the module "Tags - Popular", then clicking on a single tag, the browser Page title is shown correctly from the single tag.

This is an SEO issue. If I have 50 tags in a tags list, then I have 50 single tag views with the same page title.
I think it should work like with com_content.
Category blog view --> Page title from Menu item;
Category detail item --> Page title from Single item;

It comes from files:
components\com_tags\views\tag\view.html.php
and
components\com_tags\views\tags\view.html.php

**Comment by zero-24** [comment]
@seagul30 please try:

to replace https://github.com/joomla/joomla-cms/blob/staging/components/com_tags/views/tag/view.html.php#L209-L223

with

```
		if ($this->tags_title)
		{
			$this->params->def('page_heading', $this->tags_title);
			$title = $this->tags_title;
		}
		elseif ($menu)
		{
			$this->params->def('page_heading', $this->params->get('page_title', $menu->title));
			$title = $this->params->get('page_title', $menu->title);
			if ($menu->query['option'] != 'com_tags')
			{
				$this->params->set('page_subheading', $menu->title);
			}
		}
```

**Comment by zero-24** [comment]
It works on my end but I'm not sure if it handles does everything as expected after the change :)

**Comment by seagul30** [comment]
It works in my Joomla default 3.6.2 installation and in my client 3.6.2 project.

**Comment by zero-24** [comment]
Closing we have a PR at #12167
