### ISSUE TITLE
User Notes - Subject field is shown with &quot; instead of "

### ISSUE THREAD

**Issue by jsubri** [joomla/joomla-cms#12159]
### Steps to reproduce the issue
administrator/index.php?option=com_users&view=notes 
enter a Subject that contains a double quote such as: 
user priv "approval" history

### Expected result
the double quotes shall be displayed as "

### Actual result
![quote](https://cloud.githubusercontent.com/assets/5349333/18805772/9199c1ce-8216-11e6-87ec-fbecddd13359.PNG)

### System information (as much as possible)
Current staging

### Additional comments
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_users/views/notes/tmpl/default.php#L94 
The string is correctly stored in #__user_notes table.

**Comment by alikon** [comment]
@jsubri please test #12161

**Comment by brianteeman** [comment]
Closed as we have a pr for testing
