### ISSUE TITLE
Image in installation page does not show (error description will apply to administrator folder after install as well)

### ISSUE THREAD

**Issue by w6g23** [joomla/joomla-cms#12160]
### Steps to reproduce the issue
Upload 3.6.2-Full to a fresh web site, start installation

### Expected result
First installation page shows the "Joomla" image on top

### Actual result
Link to image is shown as "broken". See attachment.

### System information (as much as possible)
Joomla 3.6.2 (newest)
FreeBSD amd64 newest 10.3: 10.3-p7/10.3-p8
nginx 1.10.1
PHP 5.6.25, with FCGI
mysql 5.6.33 (not yet used when in installation pages)

### Additional comments
It seems to me that the link to the image should be relative to the installation page, but is in fact absolute so that the image below the installation folder is not found.

If I complete the installation anyway, the same applies to the administration folder for the backend. CSS will not be found, login will not work.

See http://forum.joomla.org/viewtopic.php?f=707&t=934791 for even more information.

**Comment by w6g23** [comment]
![Broken image link](http://demo2.heldvonkosmos.de/Joomla-installation1.png "Broken image link")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12160">issues.joomla.org/joomla-cms/12160</a>.</sub>

**Comment by brianteeman** [comment]
I can not confirm this

**Comment by w6g23** [comment]
As mentioned in the forum post, in the installation page is the image link `<img src="<img src="/template/images/joomla.png" alt="Joomla" />" alt="Joomla" />`, and as far as I can see, it is supposed to fetch `/installation/template/images/joomla.png`. Nginx gets the request `GET /template/images/joomla.png` and replies with 404.

What's wrong with my installation, then?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12160">issues.joomla.org/joomla-cms/12160</a>.</sub>

**Comment by w6g23** [comment]
Link in html is of course `<img src="/template/images/joomla.png" alt="Joomla" />`.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12160">issues.joomla.org/joomla-cms/12160</a>.</sub>

**Comment by brianteeman** [comment]
This is not a joomla issue it is a server config issue. Your forum post shows that the docroot is /var/customers/webs/wolfgang/demo2.heldvonkosmos.de/joomla aka http://demo2.heldvonkosmos.de/joomla
But that is responding with a 404
The install is working (with the broken images) at http://demo2.heldvonkosmos.de/

The path to the image does exist on your server. http://demo2.heldvonkosmos.de/installation/template/images/joomla.png

This suggest to me that you have a redirect or server config issue. Sorry but that means I have to close this here and leave it to your forum post for any further support<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12160">issues.joomla.org/joomla-cms/12160</a>.</sub>
