### ISSUE TITLE
Searchtools hardcoded to use "fullordering"

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#12162]
### Steps to reproduce the issue
I tried to create two selects for the ordering of the backend lists instead of the single one, one for the field (eg title, autor, date, ...) and one for the direction (ascending, descending).
Reason is that I think when we have many sorting options, the "fullordering" select (eg title ascending, title descending, autor ascending, autor descending, ...) gets out of hand. In case of com_content we get a select with 24 options. Using a splitted select we could cut the options in half, making choosing the right option easier and also reducing the work for translators.

### Expected result
Able to do that using the filter_xyz:xml by specifying the ordering and direction field instead of a fullordering field.

### Actual result
* I can select a different column ordering using the dropdown, however changing the direction doesn't have any effect.
* Changing the ordering using the table headers works fine, but the dropdowns don't reflect the changed ordering. It says on the last selected value.

### System information (as much as possible)
Not relevant

### Additional comments
I think this happens because the JS involved with SearchTools (https://github.com/joomla/joomla-cms/blob/staging/media/jui/js/jquery.searchtools.js) is always using the full ordering (eg "title asc") in one field. While we can change the name of the field it uses, we can't change the behaviour to populate two instead of one field.
It would be great if we could change that behaviour using an option that we pass to the searchtools JLayout (https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/searchtools/default.php).

**Comment by franz-wohlkoenig** [comment]
One Dropdownfield more if split select, but Joomla would benefit of your Proposal.

**Comment by brianteeman** [comment]
@bakual having a single select makes it much easier for accessibility

**Comment by Bakual** [comment]
@brianteeman I'd say it becomes a hassle for users with screenreaders and the like as well when there are so many options but I'm far from being an accessibility educated person. Is it worth having one select for accessibility when it becomes unuseable for regular users due to the amount of options?

**Comment by brianteeman** [comment]
The reason that it is better for a11y to have just one list is that all the information is in a single list - its a benefit not a disavantage

**Comment by wilsonge** [comment]
Closing this. It's just a byproduct of how search tools works.
