### ISSUE TITLE
What is the difference between $gregorian is true or false ?

### ISSUE THREAD

**Issue by mvanvu** [joomla/joomla-cms#12185]
Form file: /libraries/cms/html/html.php line 801 - 808

`if ($gregorian)
{
        return $date->format($format, true);
}
else
{
	return $date->calendar($format, true);
}`

I have followed this file: /libraries/joomla/date/date.php and the both method  `$date->format($format, true) and  $date->calendar($format, true);` look like the same
}

**Comment by Bakual** [comment]
I don't see a difference either. It's probably just stupid legacy code :smile: 
Especially since calendar ist just a proxy to format with the exact same params and default values.

**Comment by sidmishra9** [comment]
No there isn't much difference there , it seems to be the same .

**Comment by brianteeman** [comment]
Asked and answered<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12185">issues.joomla.org/joomla-cms/12185</a>.</sub>
