### ISSUE TITLE
Maybe one "return" too many in libraries/joomla/mail/mail.php

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#12181]
### Steps to reproduce the issue
Mail notification not sent after article creation.

### System information 
joomla 3.6.2, PHP7

Looks like an unexpected "return" is the culprit.

In /libraries/joomla/mail/mail.php, around line 400
```php
	public function addCc($cc, $name = '')
	{
		// If the carbon copy recipient is an array, add each recipient... otherwise just add the one
		if (isset($cc))
		{
			return $this->add($cc, $name, 'addCC');
		}

		return $this;
	}
```
After removing "return" from :
```php
return $this->add($cc, $name, 'addCC');
```
It should work OK.

**Comment by mbabker** [comment]
Nope.  It's fine.  The add method returns $this on success and a Boolean
false on failure.  So the fact something isn't sending means an address
wasn't added correctly and an error state was set.  You'll need to debug
deeper to see what data is being given to the method and fix the data
source, not change the API.

This can be closed as not a core bug.

**Comment by zero-24** [comment]
Closing than Thanks Michael

**Comment by ghazal** [comment]
Tks for the explanation.
I was not too sure about this, as I said, a "maybe".
