### ISSUE TITLE
hr system-readmore not working with additional parameter

### ISSUE THREAD

**Issue by Tomas42** [joomla/joomla-cms#12194]
### Steps to reproduce the issue
Create an article. Insert
&lt;hr id="system-readmore" style="width: 1013.75px; word-spacing: 0px;"&gt;
instead of
&lt;hr id="system-readmore"/&gt;
into an article to create an introtext.

### Expected result
ignores additional parameter and splits text into intro+fulltext

### Actual result
doesnt split, ignores hr.

### Additional comments
Dont ask me why or how they added the parameters, they did.

### possible solution
change regex-pattern in libraries/legacy/table/content.php:128 (function bind)
from
```php
$pattern = '#<hr\s+id=("|\')system-readmore("|\')\s*\/*>#i';
```
to
```php
$pattern = '#<hr\s+id=("|\')system-readmore("|\')[^>]*\/*>#i';
```

**Comment by dgt41** [comment]
Since you are providing a solution here, can you also create a pull request so people can test it?

**Comment by brianteeman** [comment]
Closed as we have a pr

**Comment by Sieger66** [comment]
Additional step to see the issue :

Chance the editor to "Editor-None" and  save a article with :
<hr id="system-readmore" style="width: 1013.75px; word-spacing: 0px;">

Show the article on front-end.
