### ISSUE TITLE
Joomla 3.3.6 Article Manager Re-ordering Not Working

### ISSUE THREAD

**Issue by bigzedd** [joomla/joomla-cms#12200]
### Steps to reproduce the issue
1. Go to Joomla Article Manager
2. Select Sort by Ordering Column
3. Try re-ordering articles by clicking and dragging the enabled 'the three dots' handle on the extreme left
4. Does not re-order

### Expected result
Article should be re-ordered in the list to the place it was dragged to.

### Actual result
No re-ordering, remains in the same position

### System information (as much as possible)
Joomla 3.3.6
Chrome Version 53.0.2785.116 (64-bit)
MacOS El Capitan 10.11.6

### Additional comments
Thanks for your help
http://joomla.stackexchange.com/questions/5498/articles-drag-n-drop-ordering-not-working

**Comment by bertmert** [comment]
> Joomla 3.3.6

The current Joomla version is 3.6.2. You are using 3.3.6, a version that is outdated for a long time now and should be updated immediately because of security issues!

Are you aware that you only can reorder articles inside the same category? Filter by category and try again.

**Comment by brianteeman** [comment]
Closing at this time - please use the forum for support if you till have issues after the previous advice<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12200">issues.joomla.org/tracker/joomla-cms/12200</a>.</sub>
