### ISSUE TITLE
"JUser: :_load: Unable to load user with ID" - Notice rised for user ID stored in "Modified By"

### ISSUE THREAD

**Issue by sevenstudio** [joomla/joomla-cms#12205]
### Steps to reproduce the issue

1. Please use fresh install of the J! 3.6.2 with the sample data - "Learn Joomla - Sample Data"
2. Please find and open an article "Upgraders"

### Expected result
Nothing should happen.

### Actual result
After opening the article notification is displayed:
Warning
<code>JUser: :_load: Unable to load user with ID: 123</code>
in sample data, in this article in field 'modifed by' there is an ID of user - 123 

### Additional comments
We can see the same notice for categories, for example category "modules" also has this user ID in sample data in "modified by" filed.

I'm not sure if this a bug or a feature :) ?

In my opinion this notice should be displayed only if there is missing user who created article/category.
Can someone confirm this, or anyone knows if there were changes in core that cause this behaviour?

Thanks!
Tomasz

**Comment by brianteeman** [comment]
Thanks for reporting this. This has been resolved for 3.6.3

**Comment by sevenstudio** [comment]
That's great! Thank's for update @brianteeman !
