### ISSUE TITLE
[4.0] Failing Travis on CS

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#12217]
### Steps to reproduce the issue

https://travis-ci.org/joomla/joomla-cms/jobs/163936333

### Expected result

No problems

### Actual result

```
FILE: ...uild/joomla/joomla-cms/plugins/system/languagefilter/languagefilter.php
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 170 | ERROR | Missing comment for param "$event" at position 1
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------
```

https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/system/languagefilter/languagefilter.php#L170

I'm not sure if travis / PHPCS just fouls us or something dirfferent is broken?

**Comment by mbabker** [comment]
Apparently we require an explanatory comment after the type and variable;
it's not optional there like it is on the return value.

**Comment by zero-24** [comment]
Thanks done :smile:
