### ISSUE TITLE
Title attribute of plugin labels can't contain html.

### ISSUE THREAD

**Issue by aschkenasy** [joomla/joomla-cms#12214]
### Steps to reproduce the issue
at a vanilla install going to any plugin (in the plugin manager) and hovering over the plugin labels (the grey label boxes under the name) show the title tags which contains html.

(currently on hover title is displayed as <strong>Plugin Type</strong><br />Category/folder of plugins this plugin belongs to.)

### Expected result

some sort of title string

### Actual result

<strong>Plugin Type</strong><br />Category/folder of plugins this plugin belongs to

### System information (as much as possible)

j3.6.2

**Comment by infograf768** [comment]
Confirmed

**Comment by infograf768** [comment]
I make a patch now.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/12215

**Comment by infograf768** [comment]
Closing as we have a patch

https://github.com/joomla/joomla-cms/pull/12215<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12214">issues.joomla.org/joomla-cms/12214</a>.</sub>
