### ISSUE TITLE
370:regression in index view of com_finder

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#12218]
Make sure the Smartsearch Content plugin is disabled
Then go to
`/administrator/index.php?option=com_finder&view=index`

The message is repeated twice, and the first one is not a correct link.
![screen shot 2016-09-30 at 11 21 15](https://cloud.githubusercontent.com/assets/869724/18987074/33272b9c-8700-11e6-8fa3-e243534ffd06.png)

It is `/administrator/%s` instead of `/administrator/index.php?option=com_plugins&task=plugin.edit&extension_id=441`

Looked at history and could not find when this code was introduced.
see: https://github.com/joomla/joomla-cms/blob/3.7.x/administrator/components/com_finder/views/index/view.html.php#L87-L105

obviously, as the string needs a sprintf, 
```
if (!$this->pluginState['plg_content_finder']->enabled)
		{
			JFactory::getApplication()->enqueueMessage(JText::_('COM_FINDER_INDEX_PLUGIN_CONTENT_NOT_ENABLED'), 'warning');
		}
```
is wrong.

But, I do not understand why the same message would anyway be repeated twice...

**Comment by zero-24** [comment]
hmm i think it is a conflict with this: https://github.com/joomla/joomla-cms/commit/379b5136208be2a960df8ba6f25934d4a01913eb and a later change. I would suggest to just remove the first check so we have the same code as in staging: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_finder/views/index/view.html.php#L95-L103 (with the link included and sprintf)

**Comment by infograf768** [comment]
can you make patch?

**Comment by zero-24** [comment]
done
