### ISSUE TITLE
[3.6.2] error in administrator/com_menus component

### ISSUE THREAD

**Issue by nvyush** [joomla/joomla-cms#12222]
### Steps to reproduce the issue

In the administrator panel:
1) Create two menuitems i.e. 'test1' and 'test2' of any types.
2) Open bouth menuitems 'test1' and 'test2' for editing simultaneously.
3) Change type of menuitem 'test1'.
4) Switch to tab of menuitem 'test2' and edit some parameters except 'Menu Item Type'.
5) Refresh the browser window (F5).
### Expected result

Values of parameters return to values stored in the database.
### Actual result

Values of parameters became as values of menuitem "test1".
### System information (as much as possible)

Joomla 3.6.2
### Additional comments

This bug is not critical.
It may be used to copy parameters values from one menuitem to another.

**Comment by andrepereiradasilva** [comment]
confirmed on latest staging and 3.7.x

**Comment by franz-wohlkoenig** [comment]
Confirm Issue on 3.7-staging.

**Comment by tonypartridge** [comment]
testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12222">issues.joomla.org/tracker/joomla-cms/12222</a>.</sub>

**Comment by tonypartridge** [comment]
Cannot confirm on latest staging. 

@franz-wohlkoenig could you please test too and if you cannot recreate close it? Thank you!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12222">issues.joomla.org/tracker/joomla-cms/12222</a>.</sub>

**Comment by tonypartridge** [comment]
Franz we have it recreated now, looking into it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12222">issues.joomla.org/tracker/joomla-cms/12222</a>.</sub>

**Comment by patjun** [comment]
I can confirm, the menutype of the second menuitem changes to the menutype of the first item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12222">issues.joomla.org/tracker/joomla-cms/12222</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
If i reload Tab "test2" got Tab "test1" so i cannot recreate or misunderstood something.

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16486<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12222">issues.joomla.org/tracker/joomla-cms/12222</a>.</sub>
