### ISSUE TITLE
[4.0] com_tags - Call to undefined method JPagination::get()

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#12232]
### Steps to reproduce the issue

Install 4.0 branch with testing sample data, navigate to the "tagged items" menu item

### Expected result

Single tag view

### Actual result

Error page with message `Call to undefined method JPagination::get()`

**Comment by wilsonge** [comment]
PR Pending https://github.com/joomla/joomla-cms/pull/12173/files#diff-ea63cf06b7cfbfb3a9b28a4ba3fc9b97R52
