### ISSUE TITLE
SQL Table rename error on update to 3.6.3-RC1

### ISSUE THREAD

**Issue by photodude** [joomla/joomla-cms#12249]
### Steps to reproduce the issue

update from J3.6.2 to J 3.6.3-RC1

### Expected result

update with no errors

### Actual result
```php
Error on rename of '.\bitnami_joomla\#sql-39ac_49.frm' to '.\bitnami_joomla\#__ucm_content.frm' (Errcode: 13 - Permission denied) SQL=ALTER TABLE `#__ucm_content` MODIFY `core_title` varchar(400) NOT NULL;
MySQL Database Upgrade failed. Please check the Database Fixer.
```

database fixer only shows the following `The Joomla! Core database tables have not been converted yet to UTF-8 Multibyte (utf8mb4).`

applying the fix 
```php
Error on rename of '.\bitnami_joomla\#sql-39ac_50.frm' to '.\bitnami_joomla\#__ucm_content.frm' (Errcode: 13 - Permission denied) SQL=ALTER TABLE `#__ucm_content` MODIFY `core_title` varchar(400) NOT NULL;
```
### System information (as much as possible)
Setting | Value
----- | -----
PHP Built On | Windows NT OFFICE13 6.2 build 9200 (Windows 8 Home Premium Edition) i586
Database Version | 5.6.33
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 5.6.26
Web Server | Apache
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 3.6.3-rc1 Release Candidate [ Noether ] 27-September-2016 21:52 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36

### Additional comments
none

**Comment by sovainfo** [comment]
Turn to forum.joomla.org for support about issues in your infrastructure. This queue is about issues on Joomla, not your infrastructure!

Suggest to close this issue, not a Joomla issue!

**Comment by photodude** [comment]
Looks like this is some kind of conflict with our firewall and mysql.

**Comment by sovainfo** [comment]
Not only that, you should wonder why the update starts converting to utf8mb4.!

**Comment by photodude** [comment]
@sovainfo I believe that the updates and database fixer will always automatically convert to utf8mb4 if the database is capable of utf8mb4

**Comment by sovainfo** [comment]
Indeed, when updating to j363 nothing is changed about that! That means it can't be that 362 hasn't converted it!

**Comment by photodude** [comment]
My setup for local is a [bitnami Joomla stack](https://bitnami.com/stack/joomla), It's likely that they have a misconfiguration in their current installer.

**Comment by techeaven** [comment]
Hello, have you solved this problem? Could you tell me the solution？

**Comment by photodude** [comment]
@techeaven all the relevant details are in the posts here. I don't remember the details or anything else as it was about 3 years ago.

Please look at the comment where this issue was closed and check if that helps you.  If you need additional help please open a topic on the Joomla forums as these issues seem to be WAMP/LAMP configuration specific and not related to Joomla.

**Comment by ghost** [comment]
@techeaven [Forum](https://forum.joomla.org/)
