### ISSUE TITLE
3.7.x : Regression new Router

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#12250]
### Steps to reproduce the issue
SEF on.
Set Articles Options to use "Modern" URL Routing.
Create an article as featured.
Create a home menu item of type Featured Articles.
Make sure to Show Category and Link Category 

**Do NOT create a menu item displaying the category or parent category of this article**
Display home page. URL is in this example `http://localhost:8888/370/infograf768/it/` (multilingual site)
In the article info block, click on the Category link for the article.

### Expected result

The page obtained should display the category concerned (list or blog depending on settings)

### Actual result
The home page is reloaded with same url.

![screen shot 2016-10-02 at 08 55 13](https://cloud.githubusercontent.com/assets/869724/19019180/0415813a-887e-11e6-8790-2e9e7d0613bc.png)

### System information (as much as possible)

PHP 5.4.4

### Additional comments

Same results on a monolanguage site.

@Hackwar 
@wilsonge

**Comment by infograf768** [comment]
Same issue when displaying Categories Module: the links for each category display the Home page.

**Comment by Hackwar** [comment]
Please merge #11320 first before reporting further issues like these. That PR solves quite a few other things, too.

**Comment by infograf768** [comment]
We get other errors there... Will post there

**Comment by infograf768** [comment]
Partly solved by https://github.com/joomla/joomla-cms/pull/11320
