### ISSUE TITLE
3.7.x : Multilingual Regression=>Can't change item language

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#12277]
@andrepereiradasilva 

Testing 3.7.0, I found out that we can't change the language of an item once saved, even when no associations have been yet selected or created.
I think this is due to the new Create functionality:
![screen shot 2016-10-03 at 10 53 04](https://cloud.githubusercontent.com/assets/869724/19031996/b23bd384-8957-11e6-849c-3b6b08e435d5.png)

see how the Language field is now greyed:
![screen shot 2016-10-03 at 10 53 21](https://cloud.githubusercontent.com/assets/869724/19032008/c40ee8ee-8957-11e6-895b-a29ef6789582.png)

**Comment by andrepereiradasilva** [comment]
confirmed

**Comment by andrepereiradasilva** [comment]
please test PR https://github.com/joomla/joomla-cms/pull/12283

**Comment by zero-24** [comment]
Thanks!
