### ISSUE TITLE
User Profile fields differ on my Account and Users - Manage

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#12307]
I don't know if this is by design, but while updating the helpscreens on docs.joomla.org I discovered that there are two ways to edit your Account (if you are allowed) in the Control Panel.
1. User icon - Edit Account
2. User - Manage - User
The number of fields displayd differs (Last Reset Date, Password Reset Count etc. is not shown in Edit Account)
### Steps to reproduce the issue
See above

### Expected result
The same screen must show up.

### Actual result
A different screen shows.

### System information (as much as possible)
Joomla 3.6.2, clean installation Isis template

**Comment by brianteeman** [comment]
Its not by design as such but it is a known issue. I forget now the reason I was given when I reported it before - I will try to search for it

**Comment by brianteeman** [comment]
Found it - i think - https://github.com/joomla/joomla-cms/issues/5162<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12307">issues.joomla.org/tracker/joomla-cms/12307</a>.</sub>

**Comment by MartijnMaandag** [comment]
Yes, this is the same and unfortunately not easy to solve.
I will close this.
