### ISSUE TITLE
Module (type: Articles - Category [Dynamic]) Does Not Work On Featured Article Pages

### ISSUE THREAD

**Issue by DreamlessDancer** [joomla/joomla-cms#12302]
### Steps to reproduce the issue:

Create a fresh, blank, Joomla installation, use Beez3 for the default template.

Create 2 or 3 categories for the site.

Create at least 2 articles for each category, set 1 of the articles to be featured in each category.

Create a menu (Jump), wrap it in a module at position-6.

In the above menu, create a menu item for each featured article, "index.php?option=com_content&view=featured".

In the main menu, (default), also set it to show 1 featured article from 1 category.
Additional information about the settings for the main menu home item, extracted from the SQL dump:
(101, 'mainmenu', 'Home', 'home', '', 'home', 'index.php?option=com_content&view=featured', 'component', 1, 1, 1, 22, 0, '0000-00-00 00:00:00', 0, 1, '', 0, '{"featured_categories":[""], "layout_type":"blog", "num_leading_articles":"1", "num_intro_articles":"3", "num_columns":"3", "num_links":"0", "multi_column_order":"1", "orderby_pri":"", "orderby_sec":"front", "order_date":"", "show_pagination":"2", "show_pagination_results":"1", "show_title":"", "link_titles":"", "show_intro":"", "info_block_position":"", "show_category":"", "link_category":"", "show_parent_category":"", "link_parent_category":"", "show_author":"", "link_author":"", "show_create_date":"", "show_modify_date":"", "show_publish_date":"", "show_item_navigation":"", "show_vote":"", "show_readmore":"", "show_readmore_title":"", "show_icons":"", "show_print_icon":"", "show_email_icon":"", "show_hits":"", "show_noauth":"", "show_feed_link":"1", "feed_summary":"", "menu-anchor_title":"", "menu-anchor_css":"", "menu_image":"", "menu_text":1, "page_title":"", "show_page_heading":1, "page_heading":"", "pageclass_sfx":"", "menu-meta_description":"", "menu-meta_keywords":"", "robots":"", "secure":0}', 41, 42, 1, '*', 0);

In modules, move the login module to position-5, this is the tabbed CSS position.

Create a new module, "Articles - Category", call it "Navigation", set it to be Dynamic, also put it in position 5. This is to show the tab in the tabbed position.

Optional, you may want to adjust the ordering of the modules to put the Navigation module ahead of the Login module.

Done with creation.

### Expected result:

On using the Jump menu links, it presents the featured article of that category, plus the other articles for that category in the Navigation module.

### Actual result:

Navigation menu remains empty until you use the article header link to select the article itself.

### System information (as much as possible):

You already have the latest Joomla version, 3.6.2.
Apache Version: 2.4.23
PHP Version: 5.6.26
MySQL Version: 5.6.33
Architecture: x86_64
Operating System: linux
Kernel Version: 3.10.0-427.10.1.lve1.4.7.el7.x86_64

### Additional comments:

Why I think this is a bug.

I'd expect to have the system populate the Navigation module with articles from the category of the featured article when you jump to one.

**Comment by franz-wohlkoenig** [comment]
@DreamlessDancer can you confirm Issue on latest Staging?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12302">issues.joomla.org/tracker/joomla-cms/12302</a>.</sub>

**Comment by brianteeman** [comment]
i am closing this issue at this time as there has been no response. It can always be reopened in the future if required
