### ISSUE TITLE
ACL setting in backend not responding

### ISSUE THREAD

**Issue by grillkoning** [joomla/joomla-cms#12314]
### Steps to reproduce the issue

made a fresh new extension (on a fresh Joomla install version 3.6.2), either following the documentation:
https://docs.joomla.org/J3.x:Developing_an_MVC_Component/Adding_ACL
or using JDeveloper to create an (otherwise empty) extension gives the same issue:

- set ACL on component level: OK
- set ACL on category level: OK
- set ACL on item level: inherits as expected but freezes on edit

## result:

![screen shot 2016-10-05 at 05 58 02](https://issues.joomla.org/uploads/1/87c85e71337a1dea639c486dc480daf1.png)

**Comment by andrepereiradasilva** [comment]
Did you try to refresh the browsercache (Ctrl + F5)
also can you check the chrome developer console  to see what js error you have

**Comment by grillkoning** [comment]
Refreshing the browser (or using a different browser) makes no difference.
The console gives error 
"permissions.js:1 Uncaught TypeError: Cannot read property 'value' of null"
the apache log gives no error<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12314">issues.joomla.org/tracker/joomla-cms/12314</a>.</sub>

**Comment by grillkoning** [comment]
![screen shot 2016-10-05 at 12 49 56](https://issues.joomla.org/uploads/1/7229bef295db3e9bb8c0aef2856af6fc.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12314">issues.joomla.org/tracker/joomla-cms/12314</a>.</sub>

**Comment by brianteeman** [comment]
I see in your screenshot that it is not a core component. To remove the possibility that there is a bug in that component can you replicate this issue with any of the core components

**Comment by grillkoning** [comment]
no I couldn't ; tested with com_content which works just fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12314">issues.joomla.org/tracker/joomla-cms/12314</a>.</sub>

**Comment by brianteeman** [comment]
Sounds like an issue with that component then and not the core

**Comment by andrepereiradasilva** [comment]
that's probably because your component does not have a 'title' field.

See https://github.com/joomla/joomla-cms/issues/11296#issuecomment-234943345 for more info

**Comment by grillkoning** [comment]
check; that indeed solves the problem. Thanks; i would have NEVER guessed that<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12314">issues.joomla.org/tracker/joomla-cms/12314</a>.</sub>

**Comment by brianteeman** [comment]
Closed
