### ISSUE TITLE
PHP 7.1 Notice: A non well formed numeric value encountered

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#12310]
### Steps to reproduce the issue

PHP 7.1 RC3
Joomla 3..6.x

### Expected result

No notice message on joomla update page

### Actual result

Notice: A non well formed numeric value encountered in C:\wamp\www\develop\administrator\components\com_installer\models\warnings.php on line 45

**Comment by zero-24** [comment]
Can you post your memory limit config in PHP?

**Comment by brianteeman** [comment]
Closed as you created a PR - you do NOT need to create an issue if you are going to create a PR

**Comment by 810** [comment]
@zero-24 memory_limit 256M 

@brianteeman i just found the solution, after google search
