### ISSUE TITLE
Global Configuration for Components have a curious behaviour

### ISSUE THREAD

**Issue by hacki65** [joomla/joomla-cms#12316]
### Steps to reproduce the issue
1. Go on Global Configuration e.g. the options for "Banners"
2. Switch between any Component you like and see what's happend
Before switching keep in mind wich tab was open!

### Expected result
If i switch (with or without saving) to another component option, the first tab should be opened.

### Actual result
In many cases the last tab "Permissions" is active. And then again the first tab. And then ???

### System information (as much as possible)
Joomla 3.6.2
PHP7
Linux Server Ubuntu 14.04 LTS

### Additional comments
I have an older Joomla 3.5.0 Installation that has not this curious behaviour...
I think this come with 3.6.0 because an change in com_config. I don't know the PR :)

![joomla-com_config-bug](https://cloud.githubusercontent.com/assets/20481746/19118534/f26e613a-8b1c-11e6-9ce7-9e433664224b.jpg)

**Comment by zero-24** [comment]
@hacki65 can you try the 3.6.3-rc2? https://github.com/joomla/joomla-cms/releases/tag/3.6.3-rc2

**Comment by hacki65** [comment]
Done. Tested. Same behaviour on 3.6.3-rc2 ...

![joomla-com_config-bug_363](https://cloud.githubusercontent.com/assets/20481746/19120747/30a15abe-8b24-11e6-879a-9c0f973f4034.jpg)

**Comment by hacki65** [comment]
Sometimes another curious behaviour occured also on Global Configuration or if you go to install an extension.

![joomla-com_config-bug_363b](https://cloud.githubusercontent.com/assets/20481746/19121295/3905f1f4-8b26-11e6-8dd4-1614d5eefc9a.jpg)

**Comment by brianteeman** [comment]
Yes I often get the no active tab - especially on the installer

**Comment by zero-24** [comment]
@dgt41 can you take a look? Maybe it is a JS hickup?

**Comment by andrepereiradasilva** [comment]
i also have that issue

**Comment by dgt41** [comment]
Can you test https://github.com/joomla/joomla-cms/pull/11922 ?

**Comment by dgt41** [comment]
PR: https://github.com/joomla/joomla-cms/pull/12503
