### ISSUE TITLE
User Notes - List Order button contains category order, which is not visible in the view

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#12325]
### Steps to reproduce the issue
Go to the list of User Notes.
Go to the 'Sort Table by:' button (default Review Date descending)
Open the 'Sort table by' 
You will find 'Category ascending' and 'Category descending'
They are not part of the view.

### Expected result
No 'Category ascending' and 'Category descending' as posible sort order.

### System information (as much as possible)
Joomla 3.6.3 rc2

**Comment by brianteeman** [comment]
???

![usernotes](https://cloud.githubusercontent.com/assets/1296369/19160016/482727dc-8be6-11e6-82d7-eedb39b30c09.png)

**Comment by MartijnMaandag** [comment]
I was looking for the colomn headers.
I will close this ;-)

**Comment by brianteeman** [comment]
it is the same elsewhere ;)

**Comment by MartijnMaandag** [comment]
Maybe change the colomn header from 'Subject' into 'Subject/Category'?

**Comment by andrepereiradasilva** [comment]
look at all other views in the backend ... it must be consistent

**Comment by MartijnMaandag** [comment]
Yes, so also 'Title/Category' in Articles etc.
That is why I did not reopen this issue, first discuss.
And.. it is not a big point.
