### ISSUE TITLE
Regression 3.6.3? Fatal error when logout when editing an article

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#12322]
To test, login frontend and edit an article.
Without saving the article, use the login module to logout

I have the same issue on a 3.7.x site. In fact I tested on 3.6.3 and 3.7.x both a multingual site and a monolanguage site. The results are weird.

**3.6.3-dev**
A monolanguage site: on logout I get
`( ! ) Strict standards: Non-static method JPlugin::loadLanguage() should not be called statically in /Applications/MAMP/htdocs/trunkgitnew/plugins/system/logout/logout.php on line 90`
`Fatal error: Using $this when not in object context in /Applications/MAMP/htdocs/trunkgitnew/libraries/cms/plugin/plugin.php on line 136`

On a multilingual site I get a 403 page. URL is
`http://localhost:8888/testwindows/trunkgitnew/en/english-poets.html?view=form&layout=edit&a_id=7&catid=8&return=aHR0cDovL2xvY2FsaG9zdDo4ODg4L3Rlc3R3aW5kb3dzL3RydW5rZ2l0bmV3L2VuLw==`

**3.7.x**
On a multingual site, I get
`Strict standards: Non-static method JPlugin::loadLanguage() should not be called statically in /Applications/MAMP/htdocs/370/infograf768/plugins/system/logout/logout.php on line 92`
and same fatal error
` Fatal error: Using $this when not in object context in /Applications/MAMP/htdocs/370/infograf768/libraries/cms/plugin/plugin.php on line 136`

while on a fresh monolanguage site with only one article, I get when logout a login form. If I login then, I am not redirected to the article edited but to a 403 page.

**Comment by andrepereiradasilva** [comment]
See https://github.com/joomla/joomla-cms/pull/12323 Please test
