### ISSUE TITLE
370 Regression: Modals do not close

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#12335]
Apply https://github.com/joomla/joomla-cms/issues/12321 or test in back-end using the xtd editors when editing an article: Insert article, insert menu, insert pagebreak.

The modals should close after selecting or Inserting.
They don't.

JS error: `ReferenceError: jModalClose is not defined`

It is specially weird for Pagebreak where it displays the site page in the modal after inserting

![screen shot 2016-10-07 at 08 13 31](https://cloud.githubusercontent.com/assets/869724/19181054/b6a67e22-8c6a-11e6-8a6c-37f23665102b.png)

**Comment by zero-24** [comment]
Did you try: https://github.com/joomla/joomla-cms/pull/12324 ?

**Comment by infograf768** [comment]
will do...

**Comment by infograf768** [comment]
It solves it indeed. Closing
