### ISSUE TITLE
[4.0] Work on a plan for removing support for passwords with a SHA 256 Hash

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#12333]
## The problem
- We can't reset passwords because that involves validation of the old password
- Sending emails to reset passwords (like current frontend email to reset passwords COULD lead to server resource issues on some shared hosts).
- We don't want to support SHA's forever as they represent users who have had accounts from 3 years ago (Joomla 3.2.0) on servers between 5.3.1 and 5.3.7 and who haven't logged in since the upgrade to 3.3...

## Possible resolution to the problem
- Component to flag to super admins users whose passwords fail SHA before upgrade and 'just' drop support
- Send emails and hope for the best with server resources
- Let a limited number of users find out the hard way and have them frontend reset their passwords

**Comment by mbabker** [comment]
> We don't want to support SHA's forever as they represent users who have had accounts from 3 years ago (Joomla 3.2-3.3) on servers between 5.3.3 and 5.3.9 and who haven't logged in since the upgrade to 3.3...

Even more specificity here.  Only user accounts created on a server running PHP 5.3.1 through 5.3.6 (IIRC 5.3.7 was fine thanks to support from the password_compat polyfill) on a Joomla 3.2.0 installation (3.2.1 brought in PHPass and 3.3.0 the "proper" PHP 5.5 password API).

**Comment by wilsonge** [comment]
Yup 5.3.7 and higher seem ok https://github.com/joomla/joomla-cms/commit/c6a24617aeb684a68307cc7cfc1481d3f72a0d9c - updated as appropriate - thanks!

**Comment by PhilETaylor** [comment]
Joomla currently allows md5 passwords too... try it if you dont believe me ;-) 21232f297a57a5a743894a0e4a801fc3 :)

**Comment by mbabker** [comment]
That's because the core API still supports authenticating users who have those hashes and those hashes are properly rehashed to bcrypt when encountered.  It's also much more plausible to have active user accounts with those hashes (sites are still being migrated from versions earlier than 2.5.17 and 3.2.0).  This whole issue debates a hash that was only used by core in one release for a 6 week period and only in an explicit configuration.

**Comment by PhilETaylor** [comment]
ah ok then -so the plan is to still allow the md5 hash login (which I know instantly gets converted) ?

**Comment by mbabker** [comment]
I would suggest re-evaluating that one (and possibly PHPass) for 5.0 at the earliest.

**Comment by PhilETaylor** [comment]
Cool, maybe another thought is a lot of other web apps now provide a PHP CLI to hash a pw ... (http://symfony.com/blog/new-in-symfony-2-7-security-improvements)

**Comment by mbabker** [comment]
Joomla have a proper CLI interface?  Excuse me while I go laugh heartily because that'll be blocked as long as we keep focusing on Joomla only being usable through the UI then get back to work on my current Symfony project.

**Comment by PhilETaylor** [comment]
There is a /cli folder though, thats a start, took years for that to happen :)

**Comment by mbabker** [comment]
It doesn't do anything useful (well, OK, the Smart Search indexer can be useful to the 15 sites big enough to need it over being able to use the UI for that).  And IIRC most proposals to do anything with a CLI structure got blocked or withdrawn, and I gave up on https://github.com/joomla/joomla-cms/pull/7783

**Comment by weeblr** [comment]
#jab17 bug squad here, is this still a concern?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12333">issues.joomla.org/tracker/joomla-cms/12333</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
set Status on "Information Required".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12333">issues.joomla.org/tracker/joomla-cms/12333</a>.</sub>

**Comment by mbabker** [comment]
It basically comes down to a decision of what hashing support do we deprecate and when.  But yes it is still a proper concern.

**Comment by ghost** [comment]
closed as having Pull Request #18364
