### ISSUE TITLE
"page break" button in frontend can't be used by an "Author"

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-cms#12338]
![screen shot 2016-10-07 at 03 50 42](https://issues.joomla.org/uploads/1/73c2e5c4d7fbc50b419645d3463b9b84.png)

### Steps to reproduce the issue
Use "page break" button in frontend  with an "Author" user

### Expected result
"Author" user can insert a Page Break

### Actual result
Warning
You are not authorised to view this resource.

### System information (as much as possible)
In Joomla 3.6.2 and also in Joomla 3.6.3Rc2

**Comment by infograf768** [comment]
Looks like the permissions are only set to edit and not create.
```
if ($input->get('view') === 'article' && $input->get('layout') === 'pagebreak')
{
	if (!$user->authorise('core.edit', 'com_content'))
	{
		JFactory::getApplication()->enqueueMessage(JText::_('JERROR_ALERTNOAUTHOR'), 'warning');

		return;
	}
}
```
That should be easy to correct

**Comment by AlexRed** [comment]
the problem is also for "Article" button in the editor

**Comment by infograf768** [comment]
yes
```
elseif ($input->get('view') === 'articles' && $input->get('layout') === 'modal')
{
	if (!$user->authorise('core.edit', 'com_content'))
	{
		JFactory::getApplication()->enqueueMessage(JText::_('JERROR_ALERTNOAUTHOR'), 'warning');

		return;
	}
}
```
in the same file
ROOT/components/com_content/content.php

**Comment by infograf768** [comment]
You do PR or I do?

**Comment by infograf768** [comment]
hmm, wondering now if that was on purpose...
Did it work OK before 3.6.2?

**Comment by infograf768** [comment]
This code was added in 3.4.5
https://github.com/joomla/joomla-cms/commit/dca641f67e8e341bf0ef74f775a5e81ad3ccf384#diff-35390bcd97e9f612d6fc06ea874aa22a

**Comment by infograf768** [comment]
@wilsonge
As you did that commit, could you give us some infos?

**Comment by andrepereiradasilva** [comment]
I think it should be like this:
- allowed to `core.edit` and item id different than 0: Allowed
- allowed to `core.edit.own`, item created by user and item id different than 0: Allowed
- allowed to `core.create` and item id equal to 0: Allowed
- else not allowed

and IMHO this should be applied to all components with modals.

But it's better for @wilsonge to confirm there is no problem with that.

**Comment by infograf768** [comment]
For your info, that code was added for security reasons at the time.
One of the issues with letting people display the modals with Create or Edit own only is that they will be able to see in the modals titles of stuff they may not be allowed to see (access restricted): Articles, menu items, contacts.
For pagebreak, indeed, no use imho  to restrict to edit.

**Comment by ggppdk** [comment]
> For pagebreak, indeed, no use imho to restrict to edit.

Yes, and this is issue is a kind of duplicate,

There is already a discussion here:
https://github.com/joomla/joomla-cms/pull/10653

Please see my comment:
https://github.com/joomla/joomla-cms/pull/10653

**Comment by infograf768** [comment]
Please see also
https://github.com/joomla/joomla-cms/pull/12321#issuecomment-252414048

**Comment by infograf768** [comment]
See PR here
https://github.com/joomla/joomla-cms/pull/12353

**Comment by brianteeman** [comment]
Closed as we have a PR - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12338">issues.joomla.org/tracker/joomla-cms/12338</a>.</sub>
