### ISSUE TITLE
[3.7.x][isis] Remove shadows in label and messages

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#12343]
### Steps to reproduce the issue

Update to latest 3.7.x branch
Notice the new clean isis flat design!

Labels and also the message system (Error, Warning, Notice, Message) still have text shadows

![image](https://cloud.githubusercontent.com/assets/9630530/19191852/0d0d5ff2-8c9c-11e6-8739-e89ca6f4209b.png)
![image](https://cloud.githubusercontent.com/assets/9630530/19191958/6091a85e-8c9c-11e6-8a4c-6d2113b1d70e.png)

### Expected result

No text shadows

### Actual result

text shadows

### System information (as much as possible)

latest 3.7.x branch

### Additional comments

None.

**Comment by zero-24** [comment]
@ciar4n @C-Lodder can you take a look here?

**Comment by C-Lodder** [comment]
sure, just need to clone again

**Comment by andrepereiradasilva** [comment]
just notice some more shadows
![image](https://cloud.githubusercontent.com/assets/9630530/19193343/a5871c96-8ca1-11e6-9275-fbdf5fb7edd8.png)

**Comment by C-Lodder** [comment]
Ok I've had a look at the text shadows and Bootstrap 2 also uses them in the same place, apart from the button screenshot that @andrepereiradasilva showed above.

If you want to just remove the text-shadow from the buttons, then simply add the following to the `template.less` file:

```
.btn {
    text-shadow: none;
}
```

If you want to completely remove every text-shadow in all selectors, you can either find all selectors that use them and add:

```
.selector1, .selector2, .etc {
    text-shadow: none;
}
```

OR:

```
* {
    text-shadow: none;
}
```

**Comment by ciar4n** [comment]
Following is the full list elements with text-shadow applied in the Isis BS 2.3..

```
.alert,
.close,
.alert-options,
.nav-header,
.input-append .add-on,
.input-prepend .add-on,
.nav-list > li > a,
.nav-list .nav-header,
.nav-list > .active > a,
.nav-list > .active > a:hover,
.nav-list > .active > a:focus,
.navbar .brand,
.navbar .nav > li > a,
.navbar-inverse .brand,
.navbar-inverse .nav > li > a,
.navbar-inverse .navbar-search .search-query:focus,
.navbar-inverse .navbar-search .search-query.focused,
.breadcrumb > li,
.label,
.badge,
.progress .bar,
.nav-tabs.nav-dark,
.subhead {
  text-shadow: none;
}
```

I think the select all method is probably best as I can't imagine any use for text-shadow in a flat design. At least until we move away from BS 2.3

```
* {
    text-shadow: none;
}
```

**Comment by andrepereiradasilva** [comment]
one more little think
![image](https://cloud.githubusercontent.com/assets/9630530/19208449/d395eb8a-8cf1-11e6-8ee5-e6dfb61a2d00.png)

the modals Svae button mouseover

**Comment by C-Lodder** [comment]
The PR for this was merged so can we close this?

**Comment by wilsonge** [comment]
Closed. Let's open specific issues for any other work that needs to be done on top of that PR :)
