### ISSUE TITLE
Server error 500 when joomla project cache folder do not have write permissions (it seamed it must have 770 instead of 750)

### ISSUE THREAD

**Issue by BastianWie** [joomla/joomla-cms#12374]
### Steps to reproduce the issue
- Setup a fresh Joomla 3.6.2
- Do not use a FTP account during the setup
- Do not install basic config
- upload a configuration.php and give write access
- finish joomla configuration
- delete the installation folder
- try to open the joomla main website
-> You will get an error 500 (at least in my case)

### Expected result
I would expect the default joomla website. I mean this isn´t my first joomla installation. Over the past years I have done multiple on the same 3rd party hosted webspace (mostly for development reasons).

### Actual result
An error Server 500 (when I give 770 instead of 750 on the joomla project cache folder everything is working as expected)

### System information (as much as possible)
see attachment (systeminfo.txt)

### Additional comments

When I try to login into the Admin Panel I got the joomla error:

An error has occurred.
0 The file Cache Storage is not supported on this platform.

This joomla error was solved with giving write permissions as well to administrator/cache as mentioned here: http://forum.joomla.org/viewtopic.php?t=928829

Now i can work with the Joomla installation. No additional files where created in the cache folder. When I remove the permissions again, I will get the error messages again.

**Comment by brianteeman** [comment]
Without knowing what is in the configuration file you uploaded it is impossible to say. It is probably an error in that file - which is why it is always recommended to install Joomla through the installer and let joomla create that file

**Comment by sovainfo** [comment]
What makes you think this is an issue with the software instead of your poor understanding of the infrastructure used. Suggest you return to the forum to get educated or provide the details to show it is Joomla not dealing properly with the situation.

**Comment by brianteeman** [comment]
From everything you have said it suggests that you have file cache setup in your configuration file so it is perfectly expected that you will get an error if that folder does not exist or is not writeable.

Please use the forum for support http://forum.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12374">issues.joomla.org/tracker/joomla-cms/12374</a>.</sub>
