### ISSUE TITLE
com_content router does not allow numeric category names

### ISSUE THREAD

**Issue by JamesShaver** [joomla/joomla-cms#12388]
### Steps to reproduce the issue
Create a numeric category name, for example 2016. With SEF turned on, this will be seen as an article ID, and returns a 404 error.  This can be worked around by aliasing the name as 'year2016'.

### Expected result
The router should be able to tell the difference between category names and article IDs.

**Comment by brianteeman** [comment]
The same is true for an article alias that begins with a number.

**Comment by dgt41** [comment]
Then, I guess, the field shouldn't validate with invalid data...

**Comment by mbabker** [comment]
Who says it's invalid?

**Comment by dgt41** [comment]
Hypothesis...

**Comment by JamesShaver** [comment]
Invalid, meaning that we need to instruct authors, "don't create articles or categories that start with a number... because Joomla can't understand it"?  If that's the way it works, then they shouldn't be able to create them that way.

**Comment by brianteeman** [comment]
That's where it gets tricky. If you have a single article called "2016
news" the alias will be "2016-news" which CAN cause issues but will not
always cause issues. For example it won't cause an issue if it is displayed
as a single article menu item because the alias will then come from the
menu. So not a simple thing.

**Comment by xtech86** [comment]
This is the same issue I've been having. Joomla! Shouldn't allow numeric starts to aliases. And instead send it to the end of the alias because it's too patchy otherwise.

**Comment by brianteeman** [comment]
As I stated above it all depends

**Comment by xtech86** [comment]
But it shouldn't be an if then maybe well kinda works solution. Adding it to the end solves the problem completely? Or failing validation for the user to edit, maybe saying alias cannot start with numeric values.  This solves the problem once and all.

**Comment by mbabker** [comment]
Imposing an arbitrary restriction because our code doesn't know how to handle the situation isn't a solution IMO.

**Comment by brianteeman** [comment]
Tony if you can come up with a solution that prevents those problematic
URLs without breaking sites with the ones that work then go for it. Its not
not being fixed because anyone is lazy

**Comment by Hackwar** [comment]
This has been fixed in the modern routing in 3.7. Please test there and then close this. 😄

**Comment by brianteeman** [comment]
With the current status of the modern aka experimental router being uncertain please keep this open for now

**Comment by JamesShaver** [comment]
Agreed, this should remain open until a stable release is established.

**Comment by brianteeman** [comment]
I am closing this as resolved in 3.8 which has the referenced router code
