### ISSUE TITLE
PHP Deprecated notice on restore.php Akeeba_Services_JSON

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#12380]
### Steps to reproduce the issue

run PHP -l against the CMS or see https://travis-ci.org/joomla/joomla-cms/jobs/166466458

### Expected result

No `PHP Deprecated` error

### Actual result

```
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Akeeba_Services_JSON has a deprecated constructor in ./administrator/components/com_joomlaupdate/restore.php on line 263
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Akeeba_Services_JSON_Error has a deprecated constructor in ./administrator/components/com_joomlaupdate/restore.php on line 925
```

### Additional comments

Or should this be considered as 3party code that can be ignored?

**Comment by mbabker** [comment]
Report it upstream, ignore it in our linter.

**Comment by zero-24** [comment]
is there a upstream for `restore.php`?

**Comment by mbabker** [comment]
Wherever Nic takes reports on that stuff?

**Comment by zero-24** [comment]
Hmm i cant find a upstream repo for the restore.php maybe @nikosdion can take a look here ;)

**Comment by nikosdion** [comment]
I had actually already removed that class from restore.php. Please find attached the latest build of Akeeba Restore. If you want me to make a PR with it instead let me know.

[restore.php.zip](https://github.com/joomla/joomla-cms/files/521060/restore.php.zip)

FWIW this class was not really used. It would only be used if you were to run Joomla! Update on a server which doesn't support json_encode / json_decode. That was a remnant of the Joomla! 1.6 era where it was actually possible to run Joomla! without JSON support in PHP. This has not been the case for years so I removed that class a couple of months ago.

**Comment by mbabker** [comment]
See https://github.com/joomla/joomla-cms/issues/12385 for restore.php update

**Comment by wilsonge** [comment]
Closing as we have a PR
