### ISSUE TITLE
[hathor] Joomla Update

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#12406]
The hathor template does not show the new Joomla Upload and update tab

**Comment by infograf768** [comment]
Closing as we have a patch. https://github.com/joomla/joomla-cms/pull/12454

Please test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12406">issues.joomla.org/tracker/joomla-cms/12406</a>.</sub>
