### ISSUE TITLE
[3.7.x] Regression Hathor Module manager

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#12407]
### Steps to reproduce the issue
Switch to the hathor admin template
Go to the Admin Module Manager
You will get 
500 - An error has occurred.

Layout default_batch not found.

**Comment by brianteeman** [comment]
This was caused by my PR #11762

**Comment by infograf768** [comment]
Same issue for com_users.

All comps should be tested.

**Comment by brianteeman** [comment]
Looking into it. Either the files were being used and the docblocks were
wrong or there is a call to the files even though they're not in use

**Comment by RonakParmar** [comment]
com_users and com_modules are not working with Hathor template, otherwise I can access other components, having no issue in my local setup.

**Comment by infograf768** [comment]
I found the issue

the Hathor default.php use
```php
<?php echo $this->loadTemplate('batch'); ?>
```
Changing it to the same code as core, it is solved, i.e.

```php
<?php // Load the batch processing form if user is allowed ?>
			<?php if ($loggeduser->authorise('core.create', 'com_users')
				&& $loggeduser->authorise('core.edit', 'com_users')
				&& $loggeduser->authorise('core.edit.state', 'com_users')) : ?>
				<?php echo JHtml::_(
					'bootstrap.renderModal',
					'collapseModal',
					array(
						'title' => JText::_('COM_USERS_BATCH_OPTIONS'),
						'footer' => $this->loadTemplate('batch_footer')
					),
					$this->loadTemplate('batch_body')
				); ?>
			<?php endif;?>
```

**Comment by infograf768** [comment]
Therefore we can solve the issue I think in 3.7

**Comment by RonakParmar** [comment]
Yes, I have replaced this code in my local setup now I can access com_users with Hathor template. Please generate a PR so we can test it. 
Thank you.

**Comment by RonakParmar** [comment]
Do I have to create a new branch with reference of 3.7.x branch for this fix?

**Comment by wilsonge** [comment]
That PR was merged into staging ;) so needs to be solved in staging not 3.7!

**Comment by RonakParmar** [comment]
I got it, I am asking to generate PR for above code. 
If I want to generate PR for joomla 3.7-dev, Do I have to create new branch with reference of 3.7.x branch instead of staging?

**Comment by infograf768** [comment]
the patch should also inlude the part for modules

**Comment by infograf768** [comment]
@RonakParmar 
if you do not feel confident, will make the pr a bit later.

**Comment by RonakParmar** [comment]
I know how to make a PR, just want to know for 3.7.x which branch I have to refer.
It is okay if someone else will generate PR for this fix, and I'll test that PR. :)

**Comment by infograf768** [comment]
This PR has to be done towards staging not 3.7. I make it now as it is a release blocker for 3.6.3.

**Comment by infograf768** [comment]
In fact, @wilsonge  https://github.com/joomla/joomla-cms/pull/11762 was merged into 3.7 and NOT staging. See your merge https://github.com/joomla/joomla-cms/commit/2ece1a792aede0a90642babb5c889cffbe295fdd
The files in question are still in staging.
Therefore, the PR has to be done towards 3.7 indeed... On it now.

**Comment by infograf768** [comment]
Closing as we have a PR https://github.com/joomla/joomla-cms/pull/12412<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12407">issues.joomla.org/tracker/joomla-cms/12407</a>.</sub>

**Comment by infograf768** [comment]
@RonakParmar @brianteeman @wilsonge
Thanks for testing
