### ISSUE TITLE
Improve Confirm Email Address Field

### ISSUE THREAD

**Issue by sshcli** [joomla/joomla-cms#12416]
### Steps to reproduce the issue
example.com/component/users/?view=registration

### Expected result
Copy & Paste shouldn't be allowed in the "Confirm email Address" field

### Actual result
When use Copy & Paste, a typo in the "Email Address" is also made in "Confirm email Address" field.

### System information (as much as possible)
Joomla 3.6.2
PHP 7.0.11
MySQL 5.6.33
Apache 2.4.23

**Comment by brianteeman** [comment]
I disagree with this idea. Although to be honest I think the days of asking
people to confirm their email address is nearly over. I use a library on
some site that checks for common typos and silently corrects them.

**Comment by zero-24** [comment]
Hmm how you disallow c&p or do you mean auto completion?

**Comment by brianteeman** [comment]
It can be done with some JavaScript which only allows one character at a
time and you could probably also disable the common paste keystrokes.

Still a crazy idea!

**Comment by sshcli** [comment]
I am just saying, 
A 27% of my visitors attempting to create an account couldn't make it, just because a typo in the email.

We need a solution to reduce that 27% to <5%

Not necessary to block Copy & Paste, could be something else.

**Comment by brianteeman** [comment]
Wow that's a crazy %

I use this https://github.com/mailcheck/mailcheck and its only correcting
<5% last time I looked

**Comment by mbabker** [comment]
Some of that could possibly be helped if we were doing simple client side validations before submitting to the server (i.e. if the typo results in an improperly formatted email address; and if we are, cool, I don't run sites with user registration so it's not an area I've paid attention to).

I doubt we could do much to deal with typos like if I missed the `.` in one of my `michael.babker@` addresses.

**Comment by sshcli** [comment]
> Wow that's a crazy %

It's no crazy % for a mobile friendly website where most of traffic comes from mobile devices.
The fact is that mobile is taking the lead on the industry, it's already above desktop in some places and websites.
Which means, typo are more frequent on mobile devices than desktop due to the use of big finger in a small screen.

**Comment by brianteeman** [comment]
I doubt copy paste prevention will have much effect on a mobile device as
its almost harder to copy paste than it is to mistype.

**Comment by gaelicwinter** [comment]
I've encountered this in other projects and its one of those six of one vs
half a dozen of the other problems.  The best answer I've seen is this:

http://ux.stackexchange.com/questions/21062/preventing-a-user-from-pasting-from-the-clipboard-into-a-mandatory-form-field

Basically stating that rather than use a confirmation field and then deny
c&p, just avoid the problem by confirming the email address as the last
step of registration or checkout, as in "To confirm, we will send an email
to someone@somplace.com".  Think outside the box :-)

=============================================

**Comment by sshcli** [comment]
It sounds good.

@devs
If you feel this is a risky change, then add the feature as an option in the backend (Not default).

**Comment by brianteeman** [comment]
I am closing this. It's really not something for the core. There may be extensions that will help (I don't know,) but as i said above its unlikely to resolve your specific issue. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12416">issues.joomla.org/tracker/joomla-cms/12416</a>.</sub>
