### ISSUE TITLE
Folderlist type wrong path on Windows

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#12423]
### Steps to reproduce the issue
Check the field type 'folderlist' in a generic extension parameters:

<field name="pathfolder" type="folderlist" directory="images" hide_none="1" label="Images folder" description="Custom folder" />

### Expected result
All dropdown values are the names of the folders as always been

### Actual result
All dropdown values includes the full path to the folders on Windows

### System information (as much as possible)
Joomla 3.6 and later is affected, due to changes in the file root/libraries/joomla/form/fields/folderlist.php

The line 189:
$path = JPATH_ROOT . '/' . $path;

works only for Unix paths, fails on Windows. It should be:

$path = JPATH_ROOT . '\\\' . $path;

but should be fixed as:

$path = JPATH_ROOT . DIRECTORY_SEPARATOR . $path;

### Additional comments

![correct_path](https://cloud.githubusercontent.com/assets/17835460/19412914/4e6c0e50-9320-11e6-81b1-8d7686f75848.jpg)
![wrong_paths](https://cloud.githubusercontent.com/assets/17835460/19412916/51f10ab2-9320-11e6-82ae-793843e0b43d.jpg)

**Comment by joeforjoomla** [comment]
Assign to 3.6.3 branch and fix it before the release

**Comment by brianteeman** [comment]
sent from my phone so cant search but 
99% certain there is at least one if not two Pr for this already

**Comment by mbabker** [comment]
SIR YES SIR!

**Comment by ggppdk** [comment]
@joeforjoomla 
Searching for "folderlist" in PRs (from my desktop):
https://github.com/joomla/joomla-cms/pulls?utf8=%E2%9C%93&q=folderlist

You can find a relative recent PR https://github.com/joomla/joomla-cms/pull/11288,
which has several responces and title:
> folderlist form field returning full paths on Windows (issue #11102)
