### ISSUE TITLE
[3.7.x] Missing red border in input validation

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#12438]
### Steps to reproduce the issue

Use 3.7.x and changge the session to a non integer number: ex: 0.1

### Expected result

red text with **red border**

### Actual result

red text with **blue border**
![image](https://cloud.githubusercontent.com/assets/9630530/19418989/2edd234c-93c7-11e6-876f-0327e017e440.png)

### System information (as much as possible)

3.7.x

### Additional comments

After https://github.com/joomla/joomla-cms/pull/12319

@ciar4n @C-Lodder please check this one too

**Comment by ciar4n** [comment]
Thank you @andrepereiradasilva 

PR created. #12443

**Comment by andrepereiradasilva** [comment]
closed as we have a PR
