### ISSUE TITLE
[3.7.x] Isis admin login language dropdown

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#12436]
### Steps to reproduce the issue

install 3.7.x
install an additional language
see the login screen

### Expected result

the dropdown should not be smaler than the help button ;)

### Actual result

![image](https://cloud.githubusercontent.com/assets/2596554/19418878/889febde-93cd-11e6-979d-c11addb7aea2.png)

@ciar4n can you take a look?

**Comment by ciar4n** [comment]
Thank you @zero-24 

PR opened #12442

**Comment by zero-24** [comment]
Thanks!
