### ISSUE TITLE
TinyMCE templates are accessable without login

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#12439]
### Steps to reproduce the issue

https://www.joomla.org/media/editors/tinymce/templates/layout1.html

### Expected result

If we are not logged in this should not be possible?

### Actual result

You see the html output

**Comment by mbabker** [comment]
You're directly accessing a HTML file in the filesystem.  The .htaccess file doesn't rewrite requests to trigger Joomla for files that exist in the filesystem.

**Comment by zero-24** [comment]
Ahhhhhhh ... I can re-using your meme now :P

<img src="http://s2.quickmeme.com/img/a6/a640b366b02fb81d1c67b8b0385020a7316f700e8708d8ca77f0db9c1b077f14.jpg">
