### ISSUE TITLE
Media query issue on appended input fields

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#12448]
### Steps to reproduce the issue
Effects all appended input fields. Eg. Navigate to a single article menu item (Menus -> MainMenu -> Home) and resize the screen below 767px. Input fields extend outside the viewport.

### Expected result
![screen shot 2016-10-17 at 11 55 13](https://issues.joomla.org/uploads/1/ce245bdb1ca5ba3f3973b1b69949288e.png)

### Actual result
![screen shot 2016-10-17 at 11 55 39](https://issues.joomla.org/uploads/1/65e0447f768325e4a2b2cdc77c34ef8d.png)

### Additional comments
A fluid width on these fields is difficult due to the appended buttons. We could set various sizes for each width however I feel the best solution is to use the same size on all screen sizes (removing the media query currently extending their width on smaller screen sizes).

**Comment by franz-wohlkoenig** [comment]
similaer #13768

**Comment by AlexRed** [comment]
I can't reproduce the problem on 3.7.0stagin. Seems ok now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12448">issues.joomla.org/tracker/joomla-cms/12448</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
between 631 and 481 looks messed:
![screen shot 2017-04-05 at 17 09 13](https://issues.joomla.org/uploads/1/5c9e2c27698c62655a49120ac23598c3.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12448">issues.joomla.org/tracker/joomla-cms/12448</a>.</sub>

**Comment by brianteeman** [comment]
Please test #21257
