### ISSUE TITLE
Tiny issue in property comment in JDate

### ISSUE THREAD

**Issue by GeoTimber** [joomla/joomla-cms#12440]
in 
joomla-platform/libraries/joomla/date/date.php
on line 29 it reads

@property-read string $week W - Numeric representation of the day of the week.
It think it should read

@property-read string $week W -ISO-8601 week number of year, weeks starting on Monday
it confused me for a second or two.
thanks for everything! Joris

**Comment by andrepereiradasilva** [comment]
@GeoTimber you can propose a Pull Request yourself

Go to https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/date/date.php and press the edit (pencil) button, do the changes you think are needed and submit the pull request.

**Comment by GeoTimber** [comment]
thanks for your explanation :)

**Comment by andrepereiradasilva** [comment]
you can close this as there is a PR now  https://github.com/joomla/joomla-cms/pull/12441

**Comment by brianteeman** [comment]
Closed
