### ISSUE TITLE
Administrator modules empty in template Isis after update to 3.6.3

### ISSUE THREAD

**Issue by Wilma999** [joomla/joomla-cms#12457]
After updating to 3.6.3 modules in the administrator are not working when using the template Isis.

Normally when you open a module (or make a new one) in the administrator and you get a screen to fill in the options.

Now there is a white screen with only 1 dropdown field (looks like choosing the category) on the top left.
It looks like the screen is showing (all) the options very fast and then the screen change to only the 1 field.
Sometimes the webpage also keeps loading.
Whith the hathor template it seems fine, so the problem is with the isis-template.

![screen shot 2016-10-18 at 11 50 23](https://issues.joomla.org/uploads/1/ae41baa733221d0f61ad18aa4880941f.jpg)

**Comment by zero-24** [comment]
Please clear all caches and try again

**Comment by mbabker** [comment]
Closing, consolidating into #12456
