### ISSUE TITLE
Fatal error: Call to undefined method JComponentHelper::getComponents() in /libraries/cms/router/site.php on line 119

### ISSUE THREAD

**Issue by stAn47** [joomla/joomla-cms#12459]
### Steps to reproduce the issue
visiting FE frontpage

Fatal error: Call to undefined method JComponentHelper::getComponents() in /libraries/cms/router/site.php on line 119

right after updating to joomla 3.6.3 and visiting the frontedn i got this fatal error. 

i got quite many 3rd party software installed and i can provide more info a bit later. it's on a t3-framework template.

**Comment by mbabker** [comment]
The method was added in 3.6.3.  Could be server caching not reading the new
file.

**Comment by stAn47** [comment]
no - i am running 4 different php versions at once with no cache (opcode cache disabled, no xcache, no apc) and i get the fatal on all of them. i will try to find out more. i use php-fpm for this. 
stan<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12459">issues.joomla.org/tracker/joomla-cms/12459</a>.</sub>

**Comment by mbabker** [comment]
Well, the only ways you'd get that error would be a packaging error, the
update not overwriting files correctly, or the file's new contents not
being read.  I haven't seen the error anywhere so I'd say it's safe to rule
out the packaging error.

**Comment by stAn47** [comment]
i apologize for the spam, it was caused by one of the overrides which i could not locate easily

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12459">issues.joomla.org/tracker/joomla-cms/12459</a>.</sub>
