### ISSUE TITLE
quickicon joomla update doesn't check the right version

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#12466]
### Steps to reproduce the issue

update to new dev version.

On the dashboard the quickicon, showed update message + system message

### Expected result

No message

### Actual result

Joomla! 3.6.3 is available

### System information (as much as possible)

j3.6.4-dev

Joomla update component showed no update available.

### Additional comments

Also tried bump: `php build/bump.php -v 3.6.4-dev` and `php build/bump.php -v 3.6.4`

**Comment by zero-24** [comment]
Which updateserver do you use?

**Comment by 810** [comment]
ok, the mesage is now gone.

**Comment by zero-24** [comment]
Please also check the version in the database (fix button) and if the update is cached. If you use the build in update servers there should not such message. As it is gone now for you i'm closing here. Reopen if the error comes again 👍

**Comment by andrepereiradasilva** [comment]
shouldn't joomla clear the updates table cache after update?

**Comment by zero-24** [comment]
Yes. :)

**Comment by 810** [comment]
Ok, found the problem, i need to delete my browser cache.

**Comment by zero-24** [comment]
:+1:
