### ISSUE TITLE
.drone.yml in 3.6.3 Update packge

### ISSUE THREAD

**Issue by Fedik** [joomla/joomla-cms#12477]
### Steps to reproduce the issue
Update Joomla 3.6.2 => 3.6.3

### Expected result
.drone.yml do not exist

### Actual result
.drone.yml exists

**Comment by andrepereiradasilva** [comment]
already solved by @mbabker 
https://github.com/joomla/joomla-cms/commit/481181d053b8b9a613539be5098e15da7f56d9b4

**Comment by dgt41** [comment]
it's already being added to the exclusion files in the build

**Comment by Fedik** [comment]
thanks 😄

**Comment by andrepereiradasilva** [comment]
fastest issue close ever :wink:

**Comment by dgt41** [comment]
fastest response ever 😄

**Comment by dgt41** [comment]
45 sec! New record!

**Comment by mbabker** [comment]
I saw it on the forum yesterday and just committed it while I was thinking about it.
