### ISSUE TITLE
 0 Must match character set

### ISSUE THREAD

**Issue by maxibanki** [joomla/joomla-cms#12487]
### Steps to reproduce the issue

Activate 2 Factor Auth
Login on another Device with the 2 Factor Auth Key
Error:  0 Must match character set

### Expected result

Logged in

### Actual result

Error:  0 Must match character set

### System information (as much as possible)

Joomla! 3.6.3
Apache Server
PHP Version 5.6.27

### Additional comments

Used another Account without 2 Factor Auth, which was working fine.
Never had this issue before the Joomla Version 3.6.3.

**Comment by brianteeman** [comment]
Thank you very much for reporting this. It has however already been reported here #12460 so I will close this

**Comment by andrepereiradasilva** [comment]
@brianteeman actually is this one https://github.com/joomla/joomla-cms/issues/12458 :wink:

**Comment by zero-24** [comment]
> Used another Account without 2 Factor Auth, which was working fine.

To be complete there is also doc page: https://docs.joomla.org/index.php?title=J3.x:Unable_to_login_with_2fa_enabled_after_3.6.3 if anyone find this per google ;)

**Comment by maxibanki** [comment]
Yep, but when you are to stupid to google :laughing: 
![image](https://cloud.githubusercontent.com/assets/17984549/19558515/409a251a-96cb-11e6-93c4-acc1d99c0f7d.png)

**Comment by zero-24** [comment]
No problem :smile: ;) I just want to be sure that also somone how find this one can find the docs page. Thanks!

**Comment by infograf768** [comment]
Please test this PR
https://github.com/joomla/joomla-cms/pull/12497
