### ISSUE TITLE
contact form ignores setting to not show "send a copy", mail is also sent regardless

### ISSUE THREAD

**Issue by chconnor** [joomla/joomla-cms#12480]
### Steps to reproduce the issue

Contacts -> Single Contact, Mail Options -> "Send Copy to Submitter" set to "Hide", but the checkbox shows anyway, and mail is allowed to be sent anyway

### Expected result

* No checkbox should be shown
* if set to "hide", no email should be sent even if the checkbox was shown and used
* if set to "hide", no email should be sent even if malicious actor submitted with the checkbox parameter present

### Actual result

Checkbox is shown, email is sent

### System information (as much as possible)

Joomla 3.6.3

### Additional comments

I notice in components/com_contact/views/contact/tmpl it does:

<?php if ($field->name === 'contact_email_copy' && !$this->params->get('show_email_copy')) : ?>
   <?php continue; ?>

...but if I echo $field->name it shows as "jform[contact_email_copy]". Just wanting to make the checkbox go away, I changed this to:

<?php if ($field->name === 'jform[contact_email_copy]') : ?>
   <?php continue; ?>

...and that worked. I also commented out the final section in components/com_contact/controllers/contact.php to prevent mailing a message in any circumstances.

Spammers have been using this form as an open relay.

**Comment by brianteeman** [comment]
Are you using one of the default templates or your own template with an override as I cannot replicate this in the core. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12480">issues.joomla.org/tracker/joomla-cms/12480</a>.</sub>

**Comment by chconnor** [comment]
Sorry - I am using a template. I came to the erroneous assumption that the code I was 'fixing' couldn't be affected by a template, so given my mistake and your testing, you can probably close this bug.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12480">issues.joomla.org/tracker/joomla-cms/12480</a>.</sub>

**Comment by brianteeman** [comment]
Closed as this iw not an issue with Joomla but once again a badly coded tempalte
