### ISSUE TITLE
[RFC] 4.0 Mysql drivers (MySqli, PDO MySql) in strict mode

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#12491]
Because of some errors generated by the core when mysql 5.6.6+ (i think) is in it's default sql mode, joomla modifies the sql mode to none (see, for instance, https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/joomla/database/driver/mysqli.php#L187).

You can also see this was done for PDO Mysql driver here https://github.com/joomla/joomla-cms/pull/9485/files

See, for more info about the sql modes (ex: it's default values):
- http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html
- http://dev.mysql.com/doc/refman/5.6/en/sql-mode.html

The problem with this no sql mode, is that it silently ignore some db consistency problems.

So, as talked when the problem was discovered, should 4.0 only allow mysql strict mode?
And if so, which parameters should joomla use for this sql mode?

anyway this of course will be a B/C break, since core and extensions which don't have the tables/queries in accordance to the sql mode will give errors.

**Comment by mbabker** [comment]
💯 👍

**Comment by Hackwar** [comment]
I'm all for stricter modes almost everywhere, but could you explain (or link to) what this means in reality? Maybe give an example of what is accepted right now and will fail in the future?

**Comment by dgt41** [comment]
👍

**Comment by andrepereiradasilva** [comment]
some example of core problems in strict mode https://github.com/joomla/joomla-cms/issues/11771

**Comment by Hackwar** [comment]
:+1:  from me, too.

**Comment by wilsonge** [comment]
:+1: from me. Go do a PR :)

**Comment by andrepereiradasilva** [comment]
close. See PR https://github.com/joomla/joomla-cms/pull/12494
