### ISSUE TITLE
security question related to addattachment

### ISSUE THREAD

**Issue by mdmamde** [joomla/joomla-cms#12498]
i need to know about addAtachment in custom mail form using Jmail

is there some Joomla file check inside this function? Allowed types?
how to sanityce files for example doc, pdf, xls, images only 

what problems with security are to be expected, what is already avoided by default:

Any recommendation for using this and stay secure,

Or should better be used for example a plugin like DPattachment, or a Form-component.

### System information (as much as possible)

J3.6.3

**Comment by brianteeman** [comment]
Please use the developer mailing list for this question https://groups.google.com/forum/#!forum/joomla-dev-general

**Comment by mdmamde** [comment]
thank you, already posted there 4days ago...
