### ISSUE TITLE
Cache issues with J3.6.3

### ISSUE THREAD

**Issue by acs-ferreira** [joomla/joomla-cms#12496]
After upgrading from 3.6.2 to 3.6.3, without changing my configuration, i have cache issues probelms. When enabling the cache (`conservative` or `progressive`, on `File (RamDisk)` or `APCu`), i have issues like blank pages, cache not filled Up (APCu) or Internal Server Error 500.

Please note that both systems use RAM (Ramdisk or APCu)

**After disabling the cache, no more problems.**

One exact same copy of this site on the same server, under 3.6.2, works just fine.
### Steps to reproduce the issue

Enable the cache on RamDisk (file) or APCu.
### Expected result

Cache should work like 3.6.2
### Actual result

Sometimes cache is not filled up (some page), causing blank pages on browser or even 500 ERROR.
Nothing on PHP or Apache error log files.

![Screenshot](https://www.site24x7.com/app/screenshot/s6E++m/GLw6PdmPW1mWxso5LrDJnWNlawTaWyvn+O06/7UilZPEHOczRP6KL2qXOtwX8yQrz9J5jUuRnBgbgL8DsPzWKfpgYq61Ky4SrDwWoz1fmq8hQ7Mev/i9f4UQULrWDFJujXgEw0AhNnVrS3w==)
### System information (as much as possible)
- Linux 3.13.0-83
- Database Version 5.6.33
- PHP Version 7.0.12
- APCu 5.1.6
- Web Server Apache/2.4.18 (Unix) OpenSSL/1.0.1f
- WebServer to PHP Interface fpm-fcgi
- Joomla! Version Joomla! 3.6.3 Stable [ Noether ]
- Joomla! Platform Version Joomla Platform 13.1.0 Stable [ Curiosity ]

**Comment by acs-ferreira** [comment]
I've just tested with `file` cache (no Ramdisk) **same result**.

Only **Cache Disabled** works fine.

Also, `Page Cache Plugin` is **disabled**.

**Comment by mbabker** [comment]
I'm going to suggest this is something very platform specific.  If there were indeed a problem in the cache API, `joomla.org` itself would've crashed once it was updated.

**Comment by acs-ferreira** [comment]
After disabling and re-enabling all backend (server) services, all seems good.

**Comment by acs-ferreira** [comment]
My problem is exactly described here: http://www.itoctopus.com/yet-another-reason-for-a-blank-page-on-a-joomla-website

**Comment by mbabker** [comment]
It's tricky to deal with this, contrary to what the blog post says.

The `unserialize()` function emits a notice and returns a boolean false on failure.  Yet it's possible for a boolean false value to be cached, so that alone can't be the check.  At best, maybe a [custom error handler](https://secure.php.net/manual/en/function.set-error-handler.php) could be set (and reverted) with each use of the function.

**Comment by csthomas** [comment]
If the problem occurs in the write cache, then that probably something wrong with using `flock` function.
If the problem back a lots of time then I suggest to test PR https://github.com/joomla/joomla-cms/pull/10767

It may help to not generate errors, 
after error occurs only restart (if RAM) or clear all /cache folder can help.

If error still occurs after you apply #10767 then the error is somewhere else.

IMHO Joomla does not use `flock` properly and data is written without any locking.

Someone tried to check integrity at https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/cache/storage/file.php#L135
but this is not the best way (in my opinion).

**Comment by acs-ferreira** [comment]
This PR mentions file cache system, could this be applied to APCu cache system too ?

**Comment by mbabker** [comment]
APC(u) caching uses PHP's native functions so some stuff is covered by that.  Using the filesystem as the cache handler, we have to implement some things ourselves that would otherwise be covered by a dedicated caching engine.

**Comment by csthomas** [comment]
I do not know if my PR #12556  can help but it fixes an error which may be related to your issue.

**Comment by acs-ferreira** [comment]
@csthomas i've tried your PR #12556 and it seems that it solves my problem !

Before apply the PR, one of my pages was always a blank page, after the PR, no more blank page.

Also, no more `500 Internal Server Error` at this time.

Thanks!!

My setup is, for the record:

- Joomla 3.6.4
- Ubuntu 14.04 (VPS w/ 2 vCores + 4Gb RAM)
- Apache/2.4.18 + nGinx/1.11.5 (reverse proxy)
- PHP-FPM 7.0.12 w/ opCache enabled
- APCU 5.1.7

**Comment by brianteeman** [comment]
I am closing this here then

@acs-ferreira please mark a successful test at https://issues.joomla.org/tracker/joomla-cms/12556

**Comment by acs-ferreira** [comment]
@brianteeman i've edited my post, full tests aren't conclusive at this time.
This should be re-opened.

**Comment by acs-ferreira** [comment]
Same problem with #12312.

**Comment by csthomas** [comment]
If you want to test #12312 please test it together with #12556 which is current only for APC.

Your problem is currently more wide than one PR.
There are other issues in joomla that can generate the blank pages.

 For more details you should set `Global Configuration` -> `Server Settings` -> `Error Reporting` as  `Maximum` and then check php error file, ex. error_log

**Comment by acs-ferreira** [comment]
That's what i've done, one PR, other PR, both PR.

My error_log (Apache and PHP) are empty.

**Comment by csthomas** [comment]
Then it may be related to your environment. I would suggest to check php-fpm server logs.

**Comment by acs-ferreira** [comment]
No doubt, what i can't understand is, why the same environment, BUT with j3.6.3, has no problems at all...
Still investigating on my side.
