### ISSUE TITLE
What's the idea with 3.6.4 disappearing

### ISSUE THREAD

**Issue by killerog** [joomla/joomla-cms#12495]
Until recently 3.6.4 was in the milestones list: https://github.com/joomla/joomla-cms/milestones but has now since disappeared.
So this would suggest there would be no 3.6.4, but the 3.6.3 branch did was renamed recently to 3.6.4. So can anybody shed some light on what's the current status?

**Comment by brianteeman** [comment]
It's quite simple. There was no plan to release a 364 so the milestone was removed. It was then decided that there "might" be a 364

**Comment by killerog** [comment]
So, what happened to the issues that were tagged 3.6.4?

**Comment by zero-24** [comment]
They are moved to the next release called 3.7.0 ;)

**Comment by brianteeman** [comment]
They were all moved to 3.7
