### ISSUE TITLE
Bad code in defines

### ISSUE THREAD

**Issue by Poznakomlus** [joomla/joomla-cms#12502]
Files https://github.com/joomla/joomla-cms/blob/staging/includes/defines.php
replace code in

`<?php
/**
 * @package     Joomla.Site
 * @subpackage  Application
 * @copyright   Copyright (C) 2005 - 2014 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

// No direct access.
defined('_JEXEC') or die;

/**
 * Joomla! Application define.
 */

//Defines.
/**
 * @deprecated  JPATH_ROOT is deprecated and will be removed in a future version.
 */
define('JPATH_ROOT', JPATH_BASE);
/**
 * @deprecated  JPATH_SITE is deprecated and will be removed in a future version.
 */
define('JPATH_SITE', JPATH_ROOT);
/**
 * @deprecated  JPATH_CONFIGURATION is deprecated and will be removed in a future version.
 */
define('JPATH_CONFIGURATION', JPATH_BASE);
define('JPATH_ADMINISTRATOR', JPATH_BASE . '/administrator');
define('JPATH_LIBRARIES', JPATH_BASE . '/libraries');
define('JPATH_PLUGINS', JPATH_BASE . '/plugins');
define('JPATH_INSTALLATION', JPATH_BASE . '/installation');
define('JPATH_THEMES', JPATH_BASE . '/templates');
define('JPATH_CACHE', JPATH_BASE . '/cache');
define('JPATH_MANIFESTS', JPATH_ADMINISTRATOR . '/manifests');
`

**Comment by Fedik** [comment]
there all are fine, I guess you have mixed up something 😄

**Comment by brianteeman** [comment]
What is the "bad code" you are identifying?

**Comment by Poznakomlus** [comment]
https://groups.google.com/forum/?hl=ru#!topic/joomla-dev-general/MyDGdObQ4P4

**Comment by mbabker** [comment]
Sure, let's just go ahead and majorly break Joomla by deprecating the root path constants for no reason.

**Comment by Poznakomlus** [comment]
why you do here explode and implode
you duplicates constants

**Comment by mbabker** [comment]
Ahh, back to this argument again.

There is no reason to deprecate the constants at this time.  If you think you can optimize the code without removing functionality, as you were told months ago, you are welcome to submit a pull request.

But flat out deprecating them because they appear duplicated?  That's going to go nowhere fast.

**Comment by Poznakomlus** [comment]
let's add 10 more constants
you can tell why this code
`$parts = explode(DIRECTORY_SEPARATOR, JPATH_BASE);

//Defines.
define('JPATH_ROOT',			implode(DIRECTORY_SEPARATOR, $parts));`
why transformations explode and implode?

**Comment by brianteeman** [comment]
As was stated six months ago. Feel free.to submit a.pull request. It doesn't need to be discussed any further.

**Comment by brianteeman** [comment]
This is.now closed

**Comment by Poznakomlus** [comment]
when you write Joomla5 I will remind you :-)
