### ISSUE TITLE
3.7.dev Français incorrectly rendered (accents)

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#12515]
### Steps to reproduce the issue

Install plain Joomla 3.7 from dev branch
Login to admin as super admin -> top tight click profile icon and click Edit Account
Click Basic Settings tab -> dropdown help sites 

### Expected result

English
French (as Français)

### Actual result

<img width="511" alt="screen shot 2016-10-22 at 17 11 40" src="https://cloud.githubusercontent.com/assets/400092/19620718/eda63e1e-987a-11e6-822e-d20b7e8cf750.png">

### System information (as much as possible)

https://gist.github.com/PhilETaylor/3be36d59cd676fe36eda4f5520cae7a8

**Comment by andrepereiradasilva** [comment]
@PhilETaylor i think this is solved in https://github.com/joomla/joomla-cms/pull/12507

**Comment by PhilETaylor** [comment]
yup that fixed it for me when manually changed locally
