### ISSUE TITLE
Requires option in JFormFieldList is hardcoded

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#12517]
### Steps to reproduce the issue

Review https://github.com/joomla/joomla-cms/blob/3.6.3/libraries/joomla/form/fields/list.php#L106-L120

### Expected result

This should be a flexible option, like every other

### Actual result

This option is hardcoded and only allows explicitly configured associations

**Comment by andrepereiradasilva** [comment]
you about using something like
```php
requires="plg_system_languagefilter"
requires="plg_system_languagefilter[item_associations:1]"
requires="plg_content_vote"
requires="com_banners"
```
And them in that line check if the component/plugin, etc is installed, enabled and user has acess level view right to it? If yes shown the option, if not don't show it.

if ok i can work on that

**Comment by mbabker** [comment]
Looks fine to me.

**Comment by mbabker** [comment]
> We need to preserve B/C tough

Since the value's converted to an array, first thing I can think of is do this:

```php
foreach ($requires as $require) {
    switch ($require) {
        case 'multilanguage':
            // Do existing stuff
            break;
        case 'associations':
            // Do existing stuff
            break;
        default:
            // Do new stuff
            break;
    }
}
```

**Comment by andrepereiradasilva** [comment]
just waht i was doing right now ;)

**Comment by andrepereiradasilva** [comment]
please test https://github.com/joomla/joomla-cms/issues/12517

**Comment by zero-24** [comment]
Closing as we have a PR
