### ISSUE TITLE
Featured Articles no display order input field

### ISSUE THREAD

**Issue by Mategm** [joomla/joomla-cms#12526]
Go to backend -> Content -> Featured Articles
Switch the list by ordering.

The Drag & Drop icon beside no display the input field for numbers

Its field needed for large number of articles ordering!![screen shot 2016-10-23 at 09 51 27](https://issues.joomla.org/uploads/1/5ef54a268fdda9e5f43e795235ecda02.png)![screen shot 2016-10-23 at 09 51 24](https://issues.joomla.org/uploads/1/8e16715b9d15749c74b00400a49905c9.jpg)

**Comment by ggppdk** [comment]
There is already an issue open for this , see here: https://github.com/joomla/joomla-cms/issues/11200

**Comment by zero-24** [comment]
Closing as dublicate
