### ISSUE TITLE
Not permitted error when Expires Headers enabled

### ISSUE THREAD

**Issue by n9iels** [joomla/joomla-cms#12522]
### Steps to reproduce the issue
1. Enable ExpriresHeaders in you htaccess
2. Use Google Chrome or Safari and go to the administrator area.
3. Go to the article manager and click on a article title to edit this article
4. Press the 'cancel' button
5. Click on the samen article again. You will now receive the following error
![image](https://cloud.githubusercontent.com/assets/2659866/19625885/09ca0e22-9925-11e6-9f93-c44bd1634dac.png)
6. Try to edit the article with help of the "Edit" button in toolbar. You can edit this article now for the second time without any problems.
7. Try to edit the article again with help of the article title. You will receive the same error again

### Additional System information
- Joomla! 3.6.3
- Latest version of Google Chrome and Safari
- I cleared my browsers cache and cookies
- I applied these settings to my htaccess: https://www.siteground.com/tutorials/joomla/joomla-speed.htm#htaccess

**Comment by Joomv** [comment]
Have you got ExpiresDefault enabled in your htaccess?  This will cause this.  It stopped doing it for a while in 3.0 but started again in 3.5. All the other Expires settings are fine, just the default causes the issue.

**Comment by n9iels** [comment]
@Joomv Yes! I had ExpiresDefault enabled because it is better for performance in combination with caching. I removed these headers and the problem is solved now. Thanks for that!

But... It still is an serious problem. On a Dutch Joomla! Support Form (joomlacommunity.eu) are many people with the same issue.
So is this a problem caused by that server settings or is there anything we can do to prevent it?

**Comment by ggppdk** [comment]
@n9iels 
Please read this PR:
https://github.com/joomla/joomla-cms/pull/10753

and also you may want to read this issue: #8757

**Comment by PhilETaylor** [comment]
here we go again...

**Comment by brianteeman** [comment]
@PhilETaylor at least when you have this directive enabled it can be confirmed 100% of the time (or at least I could today)

The bit I dont understand is that I can confirm it 100% of the time if I click on the article title in the manager list and I can confirm it 0% of the time when I select the article from the toolbar<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12522">issues.joomla.org/tracker/joomla-cms/12522</a>.</sub>

**Comment by PhilETaylor** [comment]
@brianteeman POSTS (like the tool bar buttons) are not cached in browsers - GETs (like clicking a link of an article title) are...

**Comment by brianteeman** [comment]
This should have been resolved by #13516 and can be closed

**Comment by PhilETaylor** [comment]
@brianteeman (welcome back) do you no longer have close permissions?

**Comment by brianteeman** [comment]
@PhilETaylor i have no permissions

**Comment by PhilETaylor** [comment]
@brianteeman Nor me :(
