### ISSUE TITLE
Add support for AMP-HTML to Joomla! CMS

### ISSUE THREAD

**Issue by jwiesel** [joomla/joomla-cms#12520]
### Improvement idea

Google and Facebook introduced new technologies to improve loading times of content on mobile devices. The Google approach is called AMP (Accelerated Mobile Pages).
This is a special kind of HTML structure with a small javascript file which avoids loading unnecessary files to a mobile device and therefore improves the page-loading speed.
It would be great, being able to provide AMP pages with Joomla for different reasons:
1. Better user experience through faster page loads
2. Google just announced to show, if a page supports AMP-HTML in their search results. (find more details here: http://www.forbes.com/sites/jaysondemers/2016/08/09/google-is-expanding-amp-in-search-results-heres-what-it-means-for-seo/#7f25451733e0)

How AMP-HTML works can be found here: https://www.ampproject.org/

My first though was maybe to create a new view format next to the normal one and the "raw" one.
What do you think?

**Comment by Dade88** [comment]
I am not sure how far you want to go with this feature, but there is already a plugin for this: https://weeblr.com/joomla-accelerated-mobile-pages/wbamp

It has a free Community Edition and a paid version with the following extras https://weeblr.com/frequent-questions/wbamp#community

**Comment by mbabker** [comment]
Good luck finding someone skilled enough and willing to deal with the politics of it to do the implementation for core.  Considering when the topic came up last year pretty much anyone associated with it was hung out to dry because of conspiracy theories, I for one won't go near it again with a 50 foot pole and would rather just use Yannick's plugin when I need it.

**Comment by tonypartridge** [comment]
@jwiesel the problem with this is the whole need to support different setups and configurations. 

You'd probably be better of rendering a new template if AMP. But as @mbabker states, it would require a huge effort to make it CMS ready. Whereas Yanicks or even JAmp handle it pretty well.

**Comment by jwiesel** [comment]
Hi there, thanks for pointing that out. I don't want Joomla to be dragged into politics. Having a component available for AMP-HTML totally does the job :-)
