### ISSUE TITLE
J3.6.3 Script Error when Editing a Module in the Frontend

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#12538]
### Steps to reproduce the issue

Edit a module in the front end and you'll see the Position is empty there's a script error. Please see attached.![screen shot 2016-10-24 at 11 56 00](https://issues.joomla.org/uploads/1/416b31902217746d94cc41f778295345.jpg)
### System information (as much as possible)

Joomla 3.6.3
Php 7
nginx
SEF enabled
SH404SEF installed

**Comment by brianteeman** [comment]
What template are you using? Can you replicate this with one of the default templates eg protostar<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12538">issues.joomla.org/tracker/joomla-cms/12538</a>.</sub>

**Comment by brianteeman** [comment]
Reset priority according to the documented standards https://docs.joomla.org/Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12538">issues.joomla.org/tracker/joomla-cms/12538</a>.</sub>

**Comment by andrepereiradasilva** [comment]
Clear the browser cache.

**Comment by andrepereiradasilva** [comment]
@brianteeman i tihknk this can be closed

**Comment by brianteeman** [comment]
I am closing this as there has been no update since the original report. it can always be reopened if updated.
