### ISSUE TITLE
Delete "Position" not work 3.6.3

### ISSUE THREAD

**Issue by JoomExpertNo** [joomla/joomla-cms#12530]
Hi

I cant delete a module-position in 3.6.3. 
In Joomla 3.6.2 i have a "x".

I work with bootstrap and need a free position for one module.

![23-10-_2016_16-27-08](https://cloud.githubusercontent.com/assets/23015989/19628077/1fbfad28-9956-11e6-9056-da50149b5d12.jpg)

**Comment by Bakual** [comment]
Confirmed, but no clue where it comes from.

**Comment by brianteeman** [comment]
That icon did NOT delete a module position. All it did was to reset the select list to have no module selected and then you could select a new position. There is no need for this <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12530">issues.joomla.org/tracker/joomla-cms/12530</a>.</sub>

**Comment by dgt41** [comment]
@brianteeman is right, but I guess we can easily add this functionality. All it needs is an ajax call and if the user just typed a new position (not saved in db) then when clicking will disappear... Magic. Not 😛

**Comment by Bakual** [comment]
> That icon did NOT delete a module position. 

I think that was what he meant, reset the list to have no selection.
SInce the parameter is optional and initially has no value it should be possible to reset the list.
The question is why it suddenly isn't possible anymore. And maybe the issue also exists in other places where it could have an impact?

**Comment by JoomExpertNo** [comment]
Yes, i need "no selection" for one module. In moment i have to delete this module and create a new... then i have "no selection". But thats crazy.

For example:
I need bootstrap and set the position there. One module is only working with "no selection". In the German Joomla forum, there are some with modules that need "no selection" to work correct.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12530">issues.joomla.org/tracker/joomla-cms/12530</a>.</sub>

**Comment by hrtrulz** [comment]
We use to be able to set the module position back to 'none' now with the removal of the 'x' in the dropdown you can't. On our site sometime we need to embed the module in a page so it need no position but for testing we put in a position to display on the test page. Now we can't remove the position.

**Comment by nikiedev** [comment]
Yeah, it's uncomfortable after the release of 3.6.3 and there is no icon in version 3.6.4 also. I hoped that removing icon is planned to be add but now I see that the develop team didn't think about this problem. Please, in the next Release, if it is 3.7 - Please, make it to be there again. But of caurse it would be greate if joomla team fix it as soon as possible, in Release 3.6.5 if such one will be.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12530">issues.joomla.org/tracker/joomla-cms/12530</a>.</sub>

**Comment by infograf768** [comment]
Please test ins staging. The icon is present and I have the possibility to set it to none here.

**Comment by Bakual** [comment]
Confirming that it is working again in current staging.
Looks like it was fixed elsewhere.

**Comment by Dtorr1981** [comment]
Hi Guys, I have a site on 3.6.5 and this issue has not been resolved? I cannot reset the module position to 'Null'.
Regards
Donna<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12530">issues.joomla.org/tracker/joomla-cms/12530</a>.</sub>

**Comment by nikiedev** [comment]
Yeah, it seems that they are planning to fix it on 3.7 version, but of course, it would be great if they fix it earlier.
