### ISSUE TITLE
 catch the play afterwards. sadly, not only is

### ISSUE THREAD

**Issue by theclubrock** [joomla/joomla-cms#12549]

**Comment by theclubrock** [comment]
play are already all sold out until next year. ..ln cursed child, the story revolves round harry’s second child, albus severus, with whom harry has a difficult relationship, especially after the boy ends up in hogwart’s slytherin house, and befriends scorpius malfoy,

**Comment by zero-24** [comment]
hmm it looks like you create a issue for the wrong repo?

**Comment by brianteeman** [comment]
its spam!!
