### ISSUE TITLE
[3.7.x] Enter key triggering cancel button on forms

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#12563]
This issue was fixed in 3.6.x (#11787) however appears to be back in 3.7.x

### Steps to reproduce the issue
1. Create new article in article manager
2. Enter a title
3. Click in to any field excluding the article editor (Eg. Alias)
4. Hit Enter (even after adding data)

### Expected result
Nothing

### Actual result
Navigates back to article manager, cancelling the article

**Comment by ciar4n** [comment]
@dgt41 Could you have a look at this?

**Comment by dgt41** [comment]
@ciar4n what was your editor?

**Comment by ciar4n** [comment]
Using TinyMCE

**Comment by dgt41** [comment]
can you clear your browser's cache and retry?

**Comment by ciar4n** [comment]
No change. Tried a fresh installation with the same result. Possibly just me but I'll leave this open for the time been and maybe someone else can replicate the issue.

**Comment by dgt41** [comment]
What browser OS are you using?

**Comment by ciar4n** [comment]
Windows (Firefox & Chrome)

**Comment by dgt41** [comment]
I can replicate it wit FF

**Comment by dgt41** [comment]
might be related to the categories on the fly @pe7er can you check this?

**Comment by 810** [comment]
im also not getting this issue with ff and chrome

**Comment by brianteeman** [comment]
I can confirm this with Chrome on OSX<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12563">issues.joomla.org/tracker/joomla-cms/12563</a>.</sub>

**Comment by PhilETaylor** [comment]
I can confirm this with Chrome on OSX

**Comment by franz-wohlkoenig** [comment]
Confirm on
Joomla! 3.7.0-staging
macOS Sierra, 10.12.3
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by brianteeman** [comment]
The same is true when creating menus

**Comment by ciar4n** [comment]
The issue appears to be related to the media field type. Removing these fields in article edit appears to resolve the issue.

@brianteeman Great to see you back!) You've certainly been missed.

**Comment by dgt41** [comment]
@ciar4n can you describe the steps that you followed? Is the modal open? Which element is in focus?

**Comment by dgt41** [comment]
@ciar4n Found it:
https://github.com/joomla/joomla-cms/blob/staging/media/media/js/mediafield.js#L119
change it to 
`return false;`

Can you make a PR for this?

**Comment by ciar4n** [comment]
@dgt41 Admin -> Content -> Articles -> [AnyArticle]. Click the 'Alias' field. Hit Enter key.

**Comment by ciar4n** [comment]
Sure.

**Comment by infograf768** [comment]
Has also to be changed in the compressed file. :)

**Comment by dgt41** [comment]
https://github.com/joomla/joomla-cms/issues/12563

We need to replace all the buttons in the modals...

**Comment by infograf768** [comment]
Close?

**Comment by dgt41** [comment]
Someone needs to take care all the modal buttons and change them to `a`, but yes close

**Comment by franz-wohlkoenig** [comment]
Please don't close until we know who "Someone" is.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/14483#issuecomment-285855181 for what remains

**Comment by brianteeman** [comment]
Closed as I have completed the remaining places identified by @infograf768 with #16156
