### ISSUE TITLE
J3.6.4 Invalid security token on frontend login

### ISSUE THREAD

**Issue by stefanpoensgen** [joomla/joomla-cms#12566]
### Steps to reproduce the issue
If i try to login in frontend i get "The most recent request was denied because it contained an invalid security token. Please refresh the page and try again"

The only way i get the login to work is to empty the session table while i'm on the login form.
When i now click login i will get the warning that my session run out.
Now i can click login and everything works as expected

### Expected result
Login and redirect

### Actual result
The most recent request was denied because it contained an invalid security token. Please refresh the page and try again

### System information (as much as possible)
PHP 7.0.6
MySQL 5.6.19

### Additional comments
Installed components
sh404SEF
yoo theme template
Jot Cache

**Comment by stefanpoensgen** [comment]
If i deactivate the "System - Page Cache" plugin everything works fine

**Comment by 810** [comment]
You need to clear your browser cache, to fix this issue.

**Comment by brianteeman** [comment]
I would also look and see what the effect of disabling JOT cache is<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12566">issues.joomla.org/tracker/joomla-cms/12566</a>.</sub>

**Comment by joomlabeat** [comment]
I am also getting this issue with front-end login - It works on my localhost but when uploading online it keeps giving me this issue. I have no cache enabled.

**Comment by joomlabeat** [comment]
My case is resolved. It was an htaccess directive that was causing this.

**Comment by gagnonjeanfrancois** [comment]
@stefanpoensgen 
I just had the same trouble, for ma case it's have nothing to do with Joomla 3.6.4... Make sure that System - Page cache plug-in is disabled or set an exception for your login menu.

**Comment by stefanpoensgen** [comment]
Cache Plugin is disabled.

**Comment by joomlabeat** [comment]
For anyone that reaches to this page with this issue, I have noticed that using some login modules for front-end login may produce the above issue. 
In this case make sure your login modules have their cache setting to No-Caching (disabled).

I am not sure for the core login module - but have seen this with 3rd party ones.
