### ISSUE TITLE
Front-end module edit button

### ISSUE THREAD

**Issue by rrrpl** [joomla/joomla-cms#12568]
Front-end module edit button not show when module_tag is section, aside, address or article. Please add this tags in layouts/joomla/edit/frontediting_modules.php

**Comment by eshiol** [comment]
In Joomla! 3.6.3 the front-end module button is shown with all module tags. 
The code in layouts/joomla/edit/frontediting_modules.php seems to be correct.
Which version of Joomla! are you using? Which module?

**Comment by brianteeman** [comment]
This was fixed in 3.6.3  ( #11417) 
Either your joomla web site has not been updated yet (you really must) OR you are using a site template that overrides the front end module editing and this has NOT been updated with the changes from 3.6.3

**Comment by rrrpl** [comment]
Ok. My fault. I have older version. 
Thx<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12568">issues.joomla.org/tracker/joomla-cms/12568</a>.</sub>
