### ISSUE TITLE
how to get automatic security update emails?

### ISSUE THREAD

**Issue by agreif** [joomla/joomla-cms#12565]
Hi,
I am subscribed to Feedburner “Joomla! Security News” mailing list.
In former times I got emails from there, but nowadays no emails are sent. Especially for 3.6.4 no Email came. It seems that Feedburner is not working the expected way.

What is the best way to get notified about security update annoncements via email?

thanks,
Alex.

**Comment by brianteeman** [comment]
Thank you for taking the time to post this. Unfortunatley its not the best place. So can you please post the question here https://github.com/joomla/joomla-websites/issues/new?title=[joomla.org]%20&body=Please%20describe%20the%20problem%20or%20your%20issue
