### ISSUE TITLE
Please revert master branch to j3.6.4

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#12572]
### Steps to reproduce the issue

Travis is now failing because of the changes on J3.7
See: https://github.com/joomla-projects/joomla-browser/pull/121

I suggest to revert the stage on the master branch so 3rt party can use the unittests.
Just change it back to J3.6.4

### Expected result

No errors

### Actual result

`CSS or XPath element with xpath '//div[@id='jform_language_chzn']//li[text()='English (United Kingdom)']' was not found`

**Comment by mbabker** [comment]
The next release will be 3.7 short of another major security issue.  Therefore it's appropriate the branch has been merged.  Tooling broken by changes in 3.7 will need to be adapted.
