### ISSUE TITLE
[4.0] Refactor Schema Validation and Management

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#12578]
The `JSchemaChange*` API and its schema validation right now relies on the update SQL files to ensure the database is in an expected state.  This API cannot work with a base SQL file which should have the full schema (for an extension this would be their `install.sql` type files, for core this would be `joomla.sql`).

Core cannot use `joomla.sql` for validation because it mixes data and schema, and this SQL lives only in the installation directory so it is not persistent on a site.

Therefore, I propose several things if someone can find time and interest:

1) Splitting `joomla.sql` into the base schema itself and data statements
2) Moving the schema only version of `joomla.sql` to a location that persists on a site
3) Improving the schema validation API to be able to take into consideration a base schema file in addition to change deltas as a means for validating the schema is in an expected state

**Comment by andrepereiradasilva** [comment]
> 1) Splitting joomla.sql into the base schema itself and data statements
> 2) Moving the schema only version of joomla.sql to a location that persists on a site

Propose moving the joomla db schema part to `/administrator/components/com_admin/install/<dbdriver>/schema.sql`

**Comment by mbabker** [comment]
Already spending too much time on prepared statement on my own, not interested in adding more database tooling in my workload and don't see much interest otherwise.

**Comment by alikon** [comment]
sorry for not demonstrating interest before now, but this goes out of my radar till now like many others i'm afraid
but yes, it seems like 4 is only focused on frontend stuff no one cares about schema/db's  and backend stuffs
