### ISSUE TITLE
Add "Install from Web" option not enabling

### ISSUE THREAD

**Issue by nikitadhiman** [joomla/joomla-cms#12586]
### Expected result
An install from web options in tab at extension install page

### Actual result
Refer the screen shot

### Additional comments
I tried doing this many times, still the same result
![web](https://cloud.githubusercontent.com/assets/8037750/19756294/2c0b6fe6-9c39-11e6-9f9c-938752050daa.png)

**Comment by zero-24** [comment]
Please report this to the webinstaller repo https://github.com/joomla-extensions/install-from-web-client it is not a core issue :)

**Comment by nikitadhiman** [comment]
thanks :)
