### ISSUE TITLE
Error on modules after updating from Joomla 3.6.2 to 3.6.4

### ISSUE THREAD

**Issue by jordan-chang** [joomla/joomla-cms#12583]
### Steps to reproduce the issue
After updating to Joomla 3.6.4 from J3.6.2, there was an error message appearing at the top of every modules i have selected.
![](http://i.imgur.com/6J2Gy15.png "")

### Expected result
Resolve the error message.

**Comment by barrycox** [comment]
on 2 different sites, after an upgrade from 3.6.2->3.6.4, whenever i click on a module on admin, i get the module appearing briefly, then the web browser spins and the screen goes white except for a dropdown.
![screen shot 2016-10-26 at 20 00 04](https://issues.joomla.org/uploads/1/a29cd8b05808f810e793b3f2d42cf406.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12583">issues.joomla.org/tracker/joomla-cms/12583</a>.</sub>

**Comment by mahagr** [comment]
See #12460 and https://github.com/robwent/joomla-json-db-check

**Comment by dgt41** [comment]
@barrycox just clear your browser's cache and any cache in your website

**Comment by advancn** [comment]
I have tried the cache clear. it does not work - my install plugin are enabled. I feel like i'm back at Joomla 1.5. Nor can I use the search tool button for modules.

**Comment by barrycox** [comment]
i thought cache clearing wasn't working also, but it did finally start 
working when i cleared the joomla cache, hard cleared my browser cache 
(not ctrl+f5, but using the browser options to clear cache).  i also 
rebooted by pc for good measure... and then waited overnight to try 
again after giving up late one night and starting the reboot before 
giving up.  and one or more of those 4 things cleared it up the next 
morning...

i didn't see any issues on the front end for users (which is great...)  
only on the module manager on the backend.

sorry it's not working for you, but wanted to mention a process that did 
work for me in case that's helpful.

and a note of thanks to everyone that works so hard on joomla and 
3.6.4.  i don't feel remotely like i'm at 1.5.

Barry Cox, CEO
SkyRun Vacation Rentals
970-660-4422 or 877-SKYRUN-1 x801
barry@skyrun.com | biz.SkyRun.com | www.SkyRun.com
