### ISSUE TITLE
Scroll to TOP when open modal

### ISSUE THREAD

**Issue by CB9TOIIIA** [joomla/joomla-cms#12587]
### Steps to reproduce the issue

Click on every part of core Joomla (pick author or insert image)

### Expected result

Open modal core and stay scroll position

### Actual result

Open modal core and scroll to top

### System information (as much as possible)

Joomla! 3.6.4

### Additional comments

Can you fix this bug? When click to change author or another (insert image from mediamanager) - site scroll slide to top, but must stay on current position.

**Comment by brianteeman** [comment]
Is this in the admin or the front end?
If it is the front end can you replicate this with the default protostar template

It is a little hard to understand exactly what you are describing. It would be really helpful if you could record a small video to explain it.
You can use http://www.cockos.com/licecap/ which is a free tool to create gif movies and is very easy to use.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12587">issues.joomla.org/tracker/joomla-cms/12587</a>.</sub>

**Comment by CB9TOIIIA** [comment]
Sorry, my bad. Bug turn up not core Joomla!  It in Zoo: 


![gifj3](https://cloud.githubusercontent.com/assets/1074710/19763695/f1949b44-9c47-11e6-9a0e-c7dd85568187.gif)

**Comment by brianteeman** [comment]
As it is not core Joomla I am closing this here. Please contact the developers of Zoo regarding this
