### ISSUE TITLE
Blog category view messed up after upgrade to 3.6.4

### ISSUE THREAD

**Issue by perianjs** [joomla/joomla-cms#12590]
Hi,

I've upgraded my 3.6.2 site (https://benedekszerelveny.hu)  to 3.6.4

After it the blog category view has messed up.
Please see attachements.

By "category -blog problem_settings.jpg" settings the result was: category -blog problem_view.jpg

I use RocketTheme's Callisto template. (On the screenshot the gray column is a side modlue position.)

### System information (as much as possible)

System Information
Setting 	Value
 
PHP Built On 	Linux webshop.benedekszerelveny.hu 3.10.0-327.36.1.el7.x86_64 #1 SMP Sun Sep 18 13:04:29 UTC 2016 x86_64
Database Version 	10.0.27-MariaDB
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.6.26
Web Server 	Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/5.6.26 mod_python/3.5.0- Python/2.7.5
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.6.4 Stable [ Noether ] 21-October-2016 16:33 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0 

### Additional ![screen shot 2016-10-27 at 03 59 40](https://issues.joomla.org/uploads/1/ec5e4b942fe8a3a638e6e74307b2e5cf.jpg)comments

![screen shot 2016-10-27 at 03 59 43](https://issues.joomla.org/uploads/1/63fc8f4b02a176420f71ca621180c98f.jpg)

**Comment by brianteeman** [comment]
Can you replicate this with one of the core joomla templates eg protostar?

If you can please confirm it here

If you can not then this is an issue with your template and you should contact RocketTheme directly and close this here

**Comment by perianjs** [comment]
I've contated RocketTheme and the problem was solved.
Please remove this ticket from the list.
Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12590">issues.joomla.org/tracker/joomla-cms/12590</a>.</sub>

**Comment by zero-24** [comment]
Closing than Thanks!
