### ISSUE TITLE
Username is case sensitive in com_joomlaupdate login

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#12593]
### Steps to reproduce the issue

Upload a Joomla! package in com_joomlaupdate. When it asks for credential, enter correct credentials but use different case for username (e.g. if your username is admin, enter Admin)
### Expected result

Confirmation successful, installation proceeds.
### Actual result

403 Access Forbidden error.
### System information (as much as possible)

Joomla! 3.6.4, PHP 7.0.9.
### Additional comments

I'm not sure if this is intentional or not but it is inconsistent with other login forms. If this is intentional, case-sensitive requirement should at least be indicated in the form.

**Comment by zero-24** [comment]
I'm not 100% sure but please try this: https://github.com/joomla/joomla-cms/compare/staging...zero-24:username_login I can make a PR if that works. Thanks!

**Comment by infograf768** [comment]
I rather think we should solve the issue for the other login forms, i.e. never accept differences in lower-upper case as this would be contradictory to our Configuration:

![screen shot 2016-10-27 at 17 47 16](https://cloud.githubusercontent.com/assets/869724/19774471/786d646e-9c6d-11e6-9362-05b62ea55d1f.png)

Why would we impose a minimum number of UpperCase if this is not implemented?

**Comment by infograf768** [comment]
EDIT:
Sorry, this concerns passwords, not User name

**Comment by brianteeman** [comment]
lol - you had me confused there

**Comment by infograf768** [comment]
I am still extremely confused: why do we accept lower and upper entries for the username in the other login forms (just tested and indeed, one can login).
This looks wrong to me.

**Comment by brianteeman** [comment]
fairly common for usernames not to be case sensitive.

**Comment by yvesh** [comment]
But SharkyXz is right on the updater (captive login) we are case sensitive for usernames on the login not.

**Comment by infograf768** [comment]
@yvesh 
Indeed joomlaupdate does not behave the same as other login forms but I wonder if it should not be safer to enforce a case-sensitive user name elsewhere instead of modifying the one in joomlaupdate.

**Comment by yvesh** [comment]
@infograf768 yep that's true. But in the first case the behavior should be equal on all areas.

@zero-24 Any reason you don't use `strcasecmp` ?? :-)

**Comment by zero-24** [comment]
@yvesh no i just want to be sure the issue comes from that part of the code ;)

**Comment by infograf768** [comment]
Folks, I just tested a new install and I confirm that sql does NOT accept case-insensitive Username.
Why would Joomla accept?

**Comment by brianteeman** [comment]
Not just Joomla - any system that uses an email address as the username for example will be case insensitive

**Comment by SharkyKZ** [comment]
@zero-24 your solution works.

**Comment by tonypartridge** [comment]
I'm with Brian it is extremely common from a user perspective to allow upper and lower case in username which can be used for login. Many times the user may start with a capital for example if writing on an iPhone and so on. It's accepted because users can be stupid (I know way too much after seeing this first hand after laughing a website for a client recently and they didn't even read the bright login they click to continue before logging in).

I would use @zero-24 solution too.

**Comment by Bakual** [comment]
>  It's accepted because users can be stupid 

The reason is more that the username isn't considered a secret element. It's also not saved encrypted in the database and sometimes even is shown on the page. Thus case sensitivity isn't of concern.
Only the password is considered a secret and thus it has to match exactly.

**Comment by mbabker** [comment]
Either way it's a major inconsistency.  This is the only part of the system that seems to have a case sensitive requirement so should be adjusted (it looks like Tobias' patch would do the trick).

**Comment by zero-24** [comment]
Done. looks like i have forgotten this over the time. Thanks for the reminder.

**Comment by zero-24** [comment]
PR is #16167
