### ISSUE TITLE
mod_articles_category - default.php - multi line - layout failure

### ISSUE THREAD

**Issue by TorstenE** [joomla/joomla-cms#12598]
![screen shot 2016-10-27 at 12 17 55](https://issues.joomla.org/uploads/1/15f6de142d84038490f61192f5b247dd.jpg)

if title is longer than one line
after deleting all tab and linebreak between [a] and [/a] in source code it works correctly

**Comment by PhilETaylor** [comment]
PR #12561 now available for you to test @TorstenE
