### ISSUE TITLE
Joomla menu item controller in BE

### ISSUE THREAD

**Issue by franzpeter** [joomla/joomla-cms#12596]
### Steps to reproduce the issue
file administrator/components/com_menus/controllers/item.php
Is that correct in line 530?
$menutype = $this->input->get->get('menutype');
I mean the double get?
### Expected result
$menutype = $this->input->get('menutype');

### Actual result
$menutype = $this->input->get->get('menutype');

### System information (as much as possible)
Joomla 3.6.4

**Comment by mbabker** [comment]
It's correct.  This value will be read from the `$_GET` superglobal.

**Comment by zero-24** [comment]
Closing as expected behavior thanks :smile:
