### ISSUE TITLE
2Fa handling : Akeeba restore: Fatal error: Class 'FOFUtilsPhpfunc' not found 

### ISSUE THREAD

**Issue by pmleconte** [joomla/joomla-cms#12591]
### Steps to reproduce the issue

Add a user and add either of the 2fa
check it works
backup your site with akeeba 5.2.3 
restore your site using kickstart version 5.0.0

### Expected result
a nice copy of your site

### Actual result
 Fatal error: Class 'FOFUtilsPhpfunc' not found in C:\UwAmp\www\conseil\libraries\fof\encrypt\aes.php on line 167
Cannot restore your site

### System information (as much as possible)
Joomla Version 3.6.4
php 5.6.18 and php 7.0.4
mysql 5.7.11

**Comment by brianteeman** [comment]
Reference 
https://www.akeebabackup.com/support/akeeba-backup-3x/26371-fatal-error-class-fofutilsphpfunc-not-found-in-homepages-libraries-fof-encrypt-aes-php-on-line-154.html

**Comment by pmleconte** [comment]
thank you for this answer. I saw it before creating this issue. 

The problem is that this error is in the fof library which is part of the Joomla 3.6.4 package.

Pascal

**Comment by PhilETaylor** [comment]
> "This looks like a partial installation or upgrade, one or more files are missing."

Sounds more like an akeeba backup and kickstart restore issue than a Joomla issue.

Sounds like you did not backup/extract your site perfectly - try uploading a fresh copy of the Joomla core files. 

Check backup folder exclusions too.

100% nothing to fix in Joomla here.

**Comment by zero-24** [comment]
Closing as non core issue. Thanks!
