### ISSUE TITLE
Extentions >>> Manage ... fails with Hathor admin Template

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#12609]
### Steps to reproduce the issue
Set the admin Template to Hathor
Navigate to Extentions >>> Manage

### Expected result
The module manager should display

### Actual result
Error 500
"Layout default_batch not found."

**Comment by brianteeman** [comment]
Closed as a duplicate report if something we already have a pull request for #12412
Please test that PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12609">issues.joomla.org/tracker/joomla-cms/12609</a>.</sub>
