### ISSUE TITLE
Mod_login URL (normal and legacy router)

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#12606]
### Steps to reproduce the issue

I don't know exactly if this is a bug with the new routing, but is something i detected.

- Use latest staging
- Multilanguage (didn't check with no multilanguage)
- Look at mod_login  remind and reset links in any page

![image](https://cloud.githubusercontent.com/assets/9630530/19808403/995b05b4-9d1c-11e6-9f27-a20bba40e13e.png)

Note those links seems different URL than 3.6.4, now they have an `&Itemid=xxx`

- the same happens in `/en/component/users/` page.

### Expected result

The same links as 3.6.4

```
/en/component/users/?view=remind
/en/component/users/?view=reset
```

### Actual result

```
/en/component/users/?view=remind&Itemid=103
/en/component/users/?view=reset&Itemid=103
```

### System information (as much as possible)

Latest staging

#### SEO settings

![image](https://cloud.githubusercontent.com/assets/9630530/19808445/d57a9e60-9d1c-11e6-8d59-5b2bfac63795.png)

#### Users routing settings

Same if you use normal or legacy router.

#### Menu with 103 id (english home)

![image](https://cloud.githubusercontent.com/assets/9630530/19808499/115704fa-9d1d-11e6-8153-5667bba53872.png)

**Comment by mbabker** [comment]
I'd call that expected for the same reasons argued elsewhere.  Looks like the default menu item is being taken into consideration while routing, including appending it to the URL, versus whatever other black hat magic was happening before.

**Comment by andrepereiradasilva** [comment]
ok then. closed.

**Comment by brianteeman** [comment]
Agreed
