### ISSUE TITLE
Contacts urls issue (legacy and modern routers)

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#12603]
### Steps to reproduce the issue
Create a contact for the super user
Create some articles
Create a menu item to display one or multiple articles, do NOT make it the home page.
Create a menu item displaying the Contact category to which belongs the super user contact: alias is `english-contacts` in this case.
Do NOT create a menu item displaying the single contact.

Display the article in frontend.
![screen shot 2016-10-28 at 08 14 06](https://cloud.githubusercontent.com/assets/869724/19796712/8d9581cc-9ce6-11e6-85f1-268133a8e1fd.png)

Click on the Super User link in the article intro

### Expected result
We should imho get an url containing the alias of the menu item for the contact category and using its Itemid.
Something in my case like:
`/english-contacts/1.html`

Testing that url DOES display the contact correctly.

### Actual result
When using legacy router for the contact component, we get:

`/component/contact/contact/1.html?Itemid=103`

When using the Modern router (Ids off), we get

`/component/contact/contact/1-contact.html?Itemid=103`

In both cases 
1.html or 1-contact.html correspond to the id of the contact
Itemid= 103 corresponds to the Home page Itemid, not even to the Article menu item...

Note: the example here is from a multilingual site but we get the same on a monolanguage one.

**Comment by infograf768** [comment]
@Hackwar  and other routers specialists

**Comment by Hackwar** [comment]
I agree, the URL should look the way you wrote. Can you make sure that menu item and category have the right permissions and that they are published? I will try to replicate this on my end.

**Comment by infograf768** [comment]
yes, correct permissions and published.

**Comment by Hackwar** [comment]
Found the issue and fixed it. See #12616

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #12616 thanks @Hackwar hackwar
