### ISSUE TITLE
Fatal error when try to edit the module

### ISSUE THREAD

**Issue by Fedik** [joomla/joomla-cms#12619]
### Steps to reproduce the issue
Try to open any module to edit 

### Expected result
you got the form

### Actual result
you got the error:
`Fatal error: Access level to ModulesViewModule::$form must be public (as in class JViewLegacy) in <root>/administrator/components/com_modules/views/module/view.html.php on line 17`

### System information (as much as possible)
Latest staging
PHP 7.0.8

**Comment by infograf768** [comment]
@Fedik 
already posted here:
https://github.com/joomla/joomla-cms/pull/12242#issuecomment-257100815
;)

**Comment by Fedik** [comment]
@infograf768 so I close current issue, or better keep?

**Comment by infograf768** [comment]
Leave it open and refer to it in #12442 @mbabker

**Comment by mbabker** [comment]
It's removed.  Which is a BS response but it's going to break more than it's worth.  Yay for more undocumented stuff in core.

**Comment by Fedik** [comment]
@mbabker that was quick 😄

**Comment by mbabker** [comment]
Funny what I can do when I'm annoyed 😉
