### ISSUE TITLE
Date to unfeature an article

### ISSUE THREAD

**Issue by arbindbhagat** [joomla/joomla-cms#12620]
It would be a good feature to add a date setting to an article for automatically unfeaturing the article at that particular date. It would be similar to how "finish publishing" date works, but this would be for "finish featuring" .

**Comment by brianteeman** [comment]
Unfortunately that is not possible with the current architecture<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12620">issues.joomla.org/tracker/joomla-cms/12620</a>.</sub>
