### ISSUE TITLE
[4.0] Error in installed languages

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#12638]
### Steps to reproduce the issue

Go to Extensions > Languages > Installed.

### Expected result

Normal view.

### Actual result

![image](https://cloud.githubusercontent.com/assets/9630530/19836138/a299d64a-9e8f-11e6-98b9-7044a0820c0c.png)

### System information (as much as possible)

Latests 4.0

### Additional comments

None.

**Comment by zero-24** [comment]
Closing as ther is a PR by @mbabker here #12644
