### ISSUE TITLE
[com_fields] - mysql dialect used FIND_IN_SET()

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#12636]
### Steps to reproduce the issue
visit home page in postgresql

### Expected result

all works as before

### Actual result

Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\j364\administrator\components\com_fields\helpers\fields.php on line 115

### System information (as much as possible)
latest staging
postgresql 9.4.5

### Additional comments
mysql dialect used `FIND_IN_SET() ` is only mysql no equivalent in postgresql nor MSSQL

**Comment by laoneo** [comment]
I guess this can be closed as we have a PR.
