### ISSUE TITLE
Too many Joomla! update emails.

### ISSUE THREAD

**Issue by deanemorris** [joomla/joomla-cms#12647]
### Steps to reproduce the issue
Have a Joomla site that is less than the current version; in this case, I have Joomla! 3.6.2.  The current latest version is Joomla! 3.6.4.  Have the System - Joomla! Update Notification plugin enabled.

### Expected result
With the plugin enabled, I should be notified that an update is available, but not twice a day, every day.  Perhaps once a week, or once a month, or once a week until I press a button to say, "I know, stop bugging me for this version."

### Actual result
I am sent an email twice a day, every day — which is ridiculous — And, since I have at least 10 Joomla sites, I am receiving 20 emails a day — 140 emails a week, 640 emails a month nagging me to update.  

### System information (as much as possible)
Not relevant.  These are all CentOS 6 sites running apache.  This problem occurs on all systems, since it's a feature of your plugin.  And I've seen other people having this problem, and even report it, only to be dismissed as a non-issue and closed.  That is just not cool.

### Additional comments
I have plugins and extensions that require cautious updating because I can't have my extensions break, and my site break just because I updated Joomla to the latest version, so I have to clone the site to a test server, update there, verify that everything works and then update the live site.  
So, I can't update right when the new version comes out.  I have to do it on my own time.
You have got to program your system to stop nagging me.
How about a little pull-down in the plugin that says "Once Only, Daily, Weekly, Monthly" so we can choose the frequency of notification.
Until you fix this, I'm going to have to disable the plugin... which I believe everyone else is doing given what I'm reading online.  Isn't that defeating the purpose and accomplishing the exact opposite result you intend?

**Comment by brianteeman** [comment]
Sorry but this is not going to be changed.

Because you have not updated your site is wide open to being hacked. Yes
the vulnerability is that serious.

If you choose not to update then you also choose to receive those notices.

Any change by Joomla would be irresponsible of us.

**Comment by zero-24** [comment]
> so I have to clone the site to a test server, update there, verify that everything works and then update the live site

This is the reason for RC versions so you can test before the final update is out and can update at the day of the release. And you can report issues if you found some ;)

**Comment by deanemorris** [comment]
Brian, 

Self-righteous much?

If you think emailing admins twice a day, every day, is necessary, then there's obviously no reasoning with you.   

You're just annoying people to the point that they turn off their notification plugin.  (That's what the solution seems to be on the forums)
  
If your goal is to have people keep their Joomla updated, then I suspect your current strategy is poorly conceived.

**Comment by mbabker** [comment]
Locked to prevent further responses that are "personal" in nature.
