### ISSUE TITLE
break-word class breaks too much

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#12648]
### Steps to reproduce the issue

Set some longer article titles, add the popular articles module to the admin control panel with a `span6` width

### Expected result

Words break correctly

### Actual result

Words break in the middle

<img width="491" alt="screen shot 2016-10-30 at 3 21 50 pm" src="https://cloud.githubusercontent.com/assets/368545/19839717/07a30bf4-9eb5-11e6-8f09-da779ee2a329.png">

### System information (as much as possible)

Joomla! 3.6.4

**Comment by brianteeman** [comment]
Iirc break word was introduced to resolve the non existent issue of having
long titles with no spaces in them

**Comment by mbabker** [comment]
I can see it being an issue with other languages that make it difficult to play Scrabble (`*cough*` German `*cough*`), but I don't think that's a good default behavior because as seen here it's now causing undesired breaks in other ways.

**Comment by brianteeman** [comment]
Agreed. It wasn't introduced by a native English speaker

**Comment by zero-24** [comment]
>  (*cough* German *cough*)

I don't have this issue on my german site. ;)

> Agreed. It wasn't introduced by a native English speaker

I'm not sure it was declared as quick fix https://github.com/joomla/joomla-cms/pull/5525 ;)

**Comment by brianteeman** [comment]
The break-word class has been applied to pretty much everywhere that we display a title. If its going to be "reverted" here then it needs to be reviewed in all the other uses<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12648">issues.joomla.org/tracker/joomla-cms/12648</a>.</sub>

**Comment by brianteeman** [comment]
Setting to needs review. can someone make a decision if we should revert the addition of adding the break-word class<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12648">issues.joomla.org/tracker/joomla-cms/12648</a>.</sub>

**Comment by tonypartridge** [comment]
What about... wait for it.. we add the language code to the title class? Then the languages with super long words can have CSS applied to break on that scenario. As I agree with @mbabker with English being default it looks a bit of a mess.

**Comment by tonypartridge** [comment]
We do do hyphens as another option, checkout:

https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/

**Comment by zero-24** [comment]
Which language have very long words and who decide that?

**Comment by zero-24** [comment]
And which language take affect? Conten language the admin language the user language the language of the content item th default language? How we handle "all" language?

**Comment by mbabker** [comment]
It can't be language specific.  As displayed, that's a default single language English Joomla install.

**Comment by tonypartridge** [comment]
But in which scenario would you have an english word that long? by default it shouldn't break english words and should return the word down a line surely? my suggest was just if it was effecting certain languages we could allow a word around by adding a break class for that language.

**Comment by mbabker** [comment]
It's not affecting certain languages though, as displayed by the screenshot.  The CSS declaration is too "eager" and it's causing inappropriate breaks in the middle of words.  I get the intent of the PR adding it, but it has introduced unwanted side effects.

I don't think locale specific CSS is the appropriate fix.

**Comment by tonypartridge** [comment]
No what I am saying is we revert the change so it doesn't force a line break. But we could add a language class based on the used language code to the titles so for the user who implemented the break-word css we could still apply it for any specific language where it might apply that the word it too long.

But in any case, the main thing is to revert the break word css.

**Comment by mbabker** [comment]
It's still making an arbitrary decision based on a language code, that seems like a bad idea to me.

**Comment by Bakual** [comment]
Imho, that PR should be reverted. As of today, users can add a user.css to add such CSS rules if they need it. Having it by default makes things worse for more users than it helps for the few cases.

@mbabker What's wrong with "Binnenseedampfschiffahrtsgesellschaft"? 😄

**Comment by Bakual** [comment]
As for adding the language code as a class to the title, that is unneeded. We already have a language tag in the header and CSS is able to act on that using `:lang()`

**Comment by mbabker** [comment]
> @mbabker What's wrong with "Binnenseedampfschiffahrtsgesellschaft"? 😄

Well, according to Google Translate it's missing a space character.  And if that's correct, I see no issues with a "Inland waterways steamship company" other than their title is too damn long.

**Comment by severdia** [comment]
Why not just keep it on one line and  truncate with ellipsis?

https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

Then add the full value to the title attribute so it can be seen on hover.

**Comment by Quy** [comment]
@mbabker Close per #16257

**Comment by brianteeman** [comment]
Closed
