### ISSUE TITLE
[com_fields] Wrong message after saving a field group

### ISSUE THREAD

**Issue by smehrbrodt** [joomla/joomla-cms#12652]
### Steps to reproduce the issue

Save a field group

### Expected result

Message "Field group successfully saved." is shown

### Actual result

Message "Category successfully saved." is shown

### System information (as much as possible)

Latest staging (commit 0521c6c03dddcb25b9dbf5ff7a7d319ea6db1913 )

**Comment by infograf768** [comment]
Let's go little by little on this new comp
Can you test both:
https://github.com/joomla/joomla-cms/pull/12646
and
https://github.com/joomla/joomla-cms/pull/12653

**Comment by smehrbrodt** [comment]
Those tickets are unrelated?!

**Comment by infograf768** [comment]
They are indeed unrelated. We have many things to check/change in this new comp.
Let's go little by little...

**Comment by tonypartridge** [comment]
@smehrbrodt I've looked into this and it's a fundemental issues of how com_fields is implemented. We are using com_categories to handle the field groups. And we are loading the category.xml file to handle this. 

I suspect we need to devise a way to load a field_groups.xml file within the category component, as the naming for groups is wrong as it's listed as 'Category'. 

Unless of course we don't do the extra development work and instead name it 'Field Categories' opposed to groups.

@brianteeman thoughts on this? Do you think the re-naming would be sufficient?

**Comment by Bakual** [comment]
@tonypartridge and @smehrbrodt See https://github.com/joomla/joomla-cms/pull/13019. That should fix this issue as well since we no longer use com_categories.

**Comment by tonypartridge** [comment]
@Bakual good work! I'll test the patch now :-)

**Comment by laoneo** [comment]
So then this one can be closed?
