### ISSUE TITLE
Module Position parameter not working with admin template Hathor

### ISSUE THREAD

**Issue by stellainformatica** [joomla/joomla-cms#12654]
### Steps to reproduce the issue
Set Hathor as admin template. Edit or create a module and try to set a module position.

### Expected result
Opens a drop down menu to select the position

### Actual result
The drop down of the parameter Position doeasn't open. If you click on Select a list of module positions appears, but if you click on the position links nothing happens.

**Comment by dgt41** [comment]
PR: https://github.com/joomla/joomla-cms/pull/12621
