### ISSUE TITLE
[4.0] Cannot Find Languages

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#12662]
### Steps to reproduce the issue

Use 4.0 latest go to Extensions -> Manage > Install Languages

### Expected result

List of available languages 

### Actual result

No languages.

### System information (as much as possible)

Latest 4.0

### Additional comments

None.

**Comment by mbabker** [comment]
To be expected.  There aren't any language packages for the 4.0 branch.

The language packages are set up to only offer packages for each major version series, so the backend won't offer 3.x packages to 4.0 (same went for 2.5 and 3.x).

**Comment by brianteeman** [comment]
Closed as expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12662">issues.joomla.org/tracker/joomla-cms/12662</a>.</sub>

**Comment by andrepereiradasilva** [comment]
LOL, right, sorry for the false allarm guys.
