### ISSUE TITLE
js/custom.js ignored in ISIS template - other templates may have same issue.

### ISSUE THREAD

**Issue by brainforgeUK** [joomla/joomla-cms#12683]
### Steps to reproduce the issue

In templates/isis/js add file custom.js

### Expected result

custom.js will be used if it exists.

### Actual result

custom.js is ignore

### System information (as much as possible)

Joomla 3.6, PHP 5, PHP 7

### Additional comments

In index.php need to add the following lines after template.js

if (file_exists(__DIR__ . '/js/custom.js')) {
  $doc->addScriptVersion($this->baseurl . '/templates/' . $this->template . '/js/custom.js');
}

Other templates should be checked. All of them should support custom.js

**Comment by brianteeman** [comment]
Please test #12684

**Comment by adambako** [comment]
hi. i just create js/custom.js and the file is not loaded.. 
it was not solve?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12683">issues.joomla.org/tracker/joomla-cms/12683</a>.</sub>

**Comment by brianteeman** [comment]
it should be user.js

**Comment by adambako** [comment]
ok. i created isis/js/user.js and its also not loaded.. can you check if its work for you?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12683">issues.joomla.org/tracker/joomla-cms/12683</a>.</sub>

**Comment by brianteeman** [comment]
Sorry I realise now that you meant isis and the answer I gave you was for protostar

try adding this code to the isis template

```
// Check for a custom js file
JHtml::_('script', 'user.js', array('version' => 'auto', 'relative' => true));
```

**Comment by adambako** [comment]
ok, thanks.. i can do that and its working..  
for the admin templates are no updates released? i tried to use override function, but it not working for isis/html/index.php 
i hope some update will not override this.
thx<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12683">issues.joomla.org/tracker/joomla-cms/12683</a>.</sub>
