### ISSUE TITLE
Error occured while fetching the JSON data: HTTP 404 status code.

### ISSUE THREAD

**Issue by jordan-chang** [joomla/joomla-cms#12689]
This happens when updating from Joomla 3.6.2 to Joomla 3.6.4. An error occurred displayed when you click on each modules in it. See screenshot below for better picture:
![](http://i.imgur.com/6J2Gy15.png "")

**Comment by zero-24** [comment]
Did you clean your JS Cache after the update?

**Comment by bullgator2k** [comment]
In response to the comment above I have cleaned the cache but the problem persists.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12689">issues.joomla.org/tracker/joomla-cms/12689</a>.</sub>

**Comment by andrepereiradasilva** [comment]
404 is page not found, is means an ajax page request has not found.
check your debug console for errors (F12 in chrome)

**Comment by jordan-chang** [comment]
@zero-24, i have clean all my cache in Joomla and nothing seems to work. Error is still there.
@andrepereiradasilva, screenshot below is what i get from the debug console:

![](http://i.imgur.com/G3LP0Na.png "")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12689">issues.joomla.org/tracker/joomla-cms/12689</a>.</sub>

**Comment by jordan-chang** [comment]
Hi All,

This issue has been rectified. The resolution for this is to Go to Manage > Update > Find Advanced Module Manager. Alternatively go to Modules Manager and you should be download the latest version of Advanced Module Manager. JUST UPDATE THE PLUGIN and the error message will be gone. Hope this helps.

![](http://i.imgur.com/aO2gOzC.png "")

![](http://i.imgur.com/HCc715u.png "")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12689">issues.joomla.org/tracker/joomla-cms/12689</a>.</sub>

**Comment by zero-24** [comment]
Glad you solved it. Closing

**Comment by ememumoh** [comment]
jordan-chang I want to specially thank you, that is what solve the problem.

**Comment by vdmerwe** [comment]
Solved :¬) Thank you!

**Comment by gboscher** [comment]
Very helpfull. Thanks a lot ! @jordan-chang<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12689">issues.joomla.org/tracker/joomla-cms/12689</a>.</sub>
