### ISSUE TITLE
[com_fields] Fields Batch Notice

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#12691]
### Steps to reproduce the issue
Create some field groups
Create a Content field.
Select this Content field and Batch copy or move

We get a Notice:
`PHP Notice:  Undefined index: tag in ROOT/libraries/legacy/model/admin.php on line 257`

**Comment by laoneo** [comment]
Does the PR #12695 solves it?

**Comment by infograf768** [comment]
Nope.

**Comment by brianteeman** [comment]
I can confirm this issue

**Comment by brianteeman** [comment]
After applying #12695 I no longer have the notice

**Comment by laoneo** [comment]
I guess we can close this one as we have a PR.
