### ISSUE TITLE
[com_fields] Unpublishing Field Groups has no effect on Field

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#12692]
### Steps to reproduce the issue
Create a Field Group for Articles.
Create a Field and assign it to that group

Unpublish the Field Group.

### Expected result

The field should not be proposed in the edit form as its Group is unpublished.

### Actual result
The field is still proposed under the tab of its Field Group when editing an article

**Comment by laoneo** [comment]
See #12696.
