### ISSUE TITLE
[3.7.x] CSS tidy up to align the Help Server button and the chosen dropdown

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#12705]
### Steps to reproduce the issue

Global Config -> system tab

needs some CSS tidy up to align the button and the chosen dropdown

<img width="527" alt="screen shot 2016-11-02 at 15 38 23" src="https://cloud.githubusercontent.com/assets/400092/19935588/7f4308a8-a112-11e6-9ac5-7fada7c55468.png">

**Comment by zero-24** [comment]
@ciar4n can you take a look in the button CSS?

**Comment by brianteeman** [comment]
Closed as we have a PR for testing see #12722
