### ISSUE TITLE
[3.7.x] Include Site Name in Page Titles Alignment

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#12706]
### Steps to reproduce the issue

Global Config -> Site Tab -> see this:

<img width="485" alt="screen shot 2016-11-02 at 15 40 20" src="https://cloud.githubusercontent.com/assets/400092/19935641/aeb8d4f0-a112-11e6-822e-503552f248d6.png">

### looks even worse in smaller screen resolutions 

<img width="878" alt="screen shot 2016-11-02 at 15 40 52" src="https://cloud.githubusercontent.com/assets/400092/19935675/cb4da5dc-a112-11e6-898c-6b4dc5bc3b91.png">

<img width="1020" alt="screen shot 2016-11-02 at 15 41 20" src="https://cloud.githubusercontent.com/assets/400092/19935682/d24cfebe-a112-11e6-8f0a-84164d4ce9f8.png">

**Comment by brianteeman** [comment]
Only quick fix I can think if is to remove the word. Include.

Won't help the smaller views which is a bigger issue and won't help if the
translation is long

**Comment by brianteeman** [comment]
Closing as we have a PR for testing #12708
