### ISSUE TITLE
com_redirect - terms

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#12700]
### Steps to reproduce the issue
If i am correct then we are using different terms for the same thing

Here
New URL and Destination URL are the same

![ditq](https://cloud.githubusercontent.com/assets/1296369/19932751/0543e904-a109-11e6-8d34-0f4b8076d7e1.png)

Here 
Source URL and Destination URL refers to Expired URL and New URL in the manager screen
![image](https://cloud.githubusercontent.com/assets/1296369/19932780/20b67b02-a109-11e6-99f9-b5b10169a308.png)

Have I got that right? If so then we need to be consistent and just use one term for the same thing

**Comment by brianteeman** [comment]
Also source URL and expired URL are the same thing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12700">issues.joomla.org/tracker/joomla-cms/12700</a>.</sub>

**Comment by brianteeman** [comment]
Also source URL and expired URL are the same thing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12700">issues.joomla.org/tracker/joomla-cms/12700</a>.</sub>

**Comment by tonypartridge** [comment]
Yes that's right, we have always used source URL and destination URL but that is a little confusing. I suggest we us:

Expired URL:
New URL:

Since it has to be a 404 to redirect.

**Comment by zero-24** [comment]
Can you send a PR for that change than?

**Comment by tonypartridge** [comment]
Sure will do

**Comment by tonypartridge** [comment]
PR sent: #13090

**Comment by brianteeman** [comment]
Closed as we have a pr
