### ISSUE TITLE
[com_fields] Captcha field

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#12703]
### Steps to reproduce the issue

Clean install
Add a single field (just one) - A CAPTCHA - save and close
Edit a content item

### Actual result

A tab entitled Fields which is totally blank, confusing..

<img width="938" alt="screen shot 2016-11-02 at 15 25 30" src="https://cloud.githubusercontent.com/assets/400092/19935216/22f18878-a111-11e6-9d85-f5913f3aea1e.png">

### Expected result

Either the tab should not be there at all, or the blank page should tell me im an idiot and how to fix the problem. 

### System information (as much as possible)

Latest commit e76aa02  tested

**Comment by brianteeman** [comment]
You can't fix stupid

**Comment by andrepereiradasilva** [comment]
i agree with @PhilETaylor

**Comment by infograf768** [comment]
I can't reproduce your issue.
Just did a clean install and the single text field is displayed under the Fields tab.
It also shows when one creates a new article.

![screen shot 2016-11-02 at 18 22 47](https://cloud.githubusercontent.com/assets/869724/19939460/64d8068c-a129-11e6-9251-4874a773a149.png)

**Comment by PhilETaylor** [comment]
Ok I have replicated your not replicating :) 

The "trick" is to create the field as a CAPTCHA field... not a text field

This then gives a blank tab... instead of no tab.

**Comment by brianteeman** [comment]
The reason is that this field is front end only for obvious reasons. There
should be an indicator of this in the admin. I did come across this in
earlier testing.

**Comment by brianteeman** [comment]
Additionally there is a bug in that the option to display this field in the admin is still available
![image](https://cloud.githubusercontent.com/assets/1296369/19940348/41540b52-a124-11e6-9e61-a90e2ad7de7f.png)

**Comment by brianteeman** [comment]
Also there is zero point in having the required option as who wants a captcha without it being required

I am not even sure if that option will work anyway see
https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/form/field/captcha.php#L110

**Comment by brianteeman** [comment]
Changed the title to show that this is an issue with the captcha field in com_fields

**Comment by brianteeman** [comment]
Maybe captcha shouldnt even be a field type available in com_fields as com_users and com_contact already support captcha natively

**Comment by alikon** [comment]
+com_content  submit an article
+com_weblinks submit a weblinks

**Comment by laoneo** [comment]
I never used the captcha field when I was working with DPFields, so probably it would make sense to remove it completely from com_fields.

**Comment by zero-24** [comment]
As this is a captcha only problem it is solved by #12719 so we can close here @PhilETaylor ?

**Comment by PhilETaylor** [comment]
tested #12719
