### ISSUE TITLE
hide category

### ISSUE THREAD

**Issue by Ziracul** [joomla/joomla-cms#12710]
how to hide category in Breadcrumbs ?

**Comment by brianteeman** [comment]
Hi

this is the issue tracker where we look at bugs and new features. For support please use the forum http://forum.joomla.org

Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12710">issues.joomla.org/tracker/joomla-cms/12710</a>.</sub>
