### ISSUE TITLE
Most Complicated issue of Joomla 

### ISSUE THREAD

**Issue by nishwenith** [joomla/joomla-cms#12724]
Suddenly My website started showing this. I updated joomla. But no point. Any solutions??![screen shot 2016-11-03 at 04 13 56](https://issues.joomla.org/uploads/1/a1848ffeaf63853110cbeaaec92c159e.jpg)![screen shot 2016-11-03 at 04 16 15](https://issues.joomla.org/uploads/1/019b1c7f031d9e405802da3415dcbeae.jpg)![screen shot 2016-11-03 at 04 16 23](https://issues.joomla.org/uploads/1/33d738ed9d314d7a9abe391cced19b20.jpg)![screen shot 2016-11-03 at 04 16 29](https://issues.joomla.org/uploads/1/65f58a76b60d90d4c3201aabdbc5af83.jpg)

**Comment by brianteeman** [comment]
Please use the forum for support - this is the issue tracker for bugs in the core code and the development of new features.

https://forum.joomla.org
