### ISSUE TITLE
[com_fields] List field options don't work correct

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#12725]
### Steps to reproduce the issue
Create a field with the type "list".
Create some options for it. Eg
![options](https://cloud.githubusercontent.com/assets/1018684/19960758/08861b2c-a1af-11e6-8e00-5ac4459fefe1.PNG)

### Expected result
A list with the created options, showing the name part

### Actual result
A list with the created options, showing the name part for the first option and the value for the remaining.
![list](https://cloud.githubusercontent.com/assets/1018684/19960788/35f8cfd2-a1af-11e6-8ebf-0f182f858d65.PNG)

### Additional comments
There is also an issue with the default value which seems to have to match the "name" part and not the "value". So in the example above I would have to enter "Three" as the default value for it to work. Which obviously would be wrong.

**Comment by laoneo** [comment]
You need to put them the opposite. The labels have been different but on some point we changed them to what we have now.

@brianteeman we were discussing this already. Can't find the issue.

**Comment by Bakual** [comment]
> You need to put them the opposite. The labels have been different but on some point we changed them to what we have now.

That is crazy if you ask me. The value should be the value attribute of the option as it appears in HTML (`<option value="0">Foo</option>`) and the "name" (or better "text"?) would be the user friendly name/text of the option.

There is still an issue that when the "Name" is 0, the "value" is used instead. But that seems to be an issue of the list formfield itself.

**Comment by laoneo** [comment]
Make PR how you would label them.

**Comment by Bakual** [comment]
If you can give me a hint where the code is, I can do it. I haven't looked that deep into where those are generated.

**Comment by laoneo** [comment]
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/parameters/list.xml

Don't forget to adapt checkboxes and radios when you change something in the XML structure and not just the labels.

**Comment by brianteeman** [comment]
I agree with Thomas<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12725">issues.joomla.org/tracker/joomla-cms/12725</a>.</sub>

**Comment by brianteeman** [comment]
@laoneo are you referring to https://github.com/joomla-projects/custom-fields/issues/121

**Comment by laoneo** [comment]
Exactly, perhaps we need also the opinion of @coolcat-creations .

**Comment by ggppdk** [comment]
@Bakual 
> If you can give me a hint where the code is, I can do it. I haven't looked that deep into where those are generated.

It is not the XML file it is method JFormAbstractlist::getOptionsFromField that is doing the reversing for both cases of editing (form), and viewing 

https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/abstractlist.php#L178-L181
```php
			foreach ($options->value as $index => $key)
			{
				$data[$key] = $options->name[$index];
			}
```

Also method JFormAbstractlist::getOptionsFromField , expects name="name", but radio and checkboxes are using name="key" thus they do not show in the form 

I have made a PR, 
- also i noticed that  value: 0 is usable in the form but not showing in frontend when viewing the field values, it seems that it is consider as no value, we need to use strlen() somewhere

**Comment by Bakual** [comment]
@ggppdk Thanks, just came to the same conclusion as well. I did the code a bit different but in the end it would do the same.
Closing here as we have a PR: https://github.com/joomla/joomla-cms/pull/12739
