### ISSUE TITLE
Error refreshing the OAuth2 token, message "{ "error" : "invalid" }"

### ISSUE THREAD

**Issue by jordan-chang** [joomla/joomla-cms#12721]
As soon as i login to the Admin panel. Error below showed up on my screen:

![](http://i.imgur.com/9pSvVCq.png "")

**Comment by mbabker** [comment]
There isn't anything in core using OAuth in this manner.  This suggests there is an extension causing the issue.

**Comment by jordan-chang** [comment]
Hi,

This is resolved as i have disabled Google Analytics Dashboard and then control panel works like normal now.
![](http://i.imgur.com/skZHQPP.png "")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12721">issues.joomla.org/tracker/joomla-cms/12721</a>.</sub>
