### ISSUE TITLE
Serialization of 'JXMLElement' is not allowed j3.6.4

### ISSUE THREAD

**Issue by csiteru** [joomla/joomla-cms#12738]
### Steps to reproduce the issue
Joomla 3.6.4 + Jomsocial 4.2.5
1. if you login to site please logout.
2. after logout, or if you view site in "private view" in my browser, youe can see this Error.

Serialization of 'JXMLElement' is not allowed

Call stack	
#		Function		Location	
1 JApplicationCms->execute()		/index.php:49	
2 JApplicationSite->doExecute()		/libraries/cms/application/cms.php:261	
3 JApplicationSite->dispatch()		/libraries/cms/application/site.php:230	
4 JComponentHelper::renderComponent()		/libraries/cms/application/site.php:191	
5 JComponentHelper::executeComponent()		/libraries/cms/component/helper.php:380	
6 require_once()		/libraries/cms/component/helper.php:405	
7 CommunityBaseController->execute()		/components/com_community/community.php:145	
8 CommunityFrontpageController->display()		/components/com_community/controllers/controller.php:326	
9 CommunityView->get()		/components/com_community/controllers/frontpage.php:52	
10 CommunityViewFrontpage->display()		/components/com_community/views/views.php:251	
11 CommunityViewFrontpage->showLatestActivities()		/components/com_community/views/frontpage/view.html.php:119	
12 CActivities::getActivitiesByFilter()		/components/com_community/views/frontpage/view.html.php:301	
13 CActivities->getHTML()		/components/com_community/libraries/activities.php:1494	
14 CActivities->_getData()		/components/com_community/libraries/activities.php:1088	
15 CActivities::getActivityContent()		/components/com_community/libraries/activities.php:649	
16 serialize()		/components/com_community/libraries/activities.php:278

**Comment by brianteeman** [comment]
From that stack trace it would indicate an issue with Jomsocial and not the core of Joomla and you should report the issue to them.
