### ISSUE TITLE
Field type media with Home Directory checked create images folder

### ISSUE THREAD

**Issue by ketihar** [joomla/joomla-cms#12734]
### Steps to reproduce the issue
Go to Content->Articles->Fields
Create a Field with type media
On field settings check to "yes" Home Directory and leave empty the field Directory

### Expected result
Username folders created inside images folder

### Actual result
Username folders created on new images folder that created inside images folder

### System information (as much as possible)
Database Version 5.7.14
Database Collation utf8_general_ci
Database Connection Collation utf8mb4_general_ci
PHP Version 7.0.10
Web Server Apache/2.4.23 (Win64) PHP/7.0.10
WebServer to PHP Interface apache2handler
Joomla! Version Joomla! 3.7.0-dev Development [ Noether ] 18-October-2016 16:37 GMT
Joomla! Platform Version Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments
There is no way to create folders directly inside images folder, even if you enter "images" on directory field

**Comment by franz-wohlkoenig** [comment]
@ketihar can't find 
> on field settings check to "yes" Home Directory

can you please give me a Hint how to reproduce Issue?

**Comment by ketihar** [comment]
On media field settings you will see "Home Directory" select list. Choose "Yes". <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12734">issues.joomla.org/tracker/joomla-cms/12734</a>.</sub>

**Comment by ketihar** [comment]
![screen shot 2017-02-02 at 15 31 18](https://issues.joomla.org/uploads/1/5a905976bb83e71158082186d300eb14.jpeg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12734">issues.joomla.org/tracker/joomla-cms/12734</a>.</sub>

**Comment by ketihar** [comment]
Now it will create a folder images/username inside images folder. This is wrong. It must save username folders directly inside joomla images folder.folder <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12734">issues.joomla.org/tracker/joomla-cms/12734</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
similar PR: #13893
