### ISSUE TITLE
Field Group permission tab has no settings

### ISSUE THREAD

**Issue by ketihar** [joomla/joomla-cms#12730]
### Steps to reproduce the issue
Install Joomla! 3.7.0-dev Development
Go to Content->Articles->Field Groups
Create a Field Group and go to Permissions tab

### Expected result
Settings that i can change

### Actual result
There is no permission settings

### System information (as much as possible)
Database Version	5.7.14
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.10
Web Server	Apache/2.4.23 (Win64) PHP/7.0.10
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.7.0-dev Development [ Noether ] 18-October-2016 16:37 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by Bakual** [comment]
The way it is done currently it would need the following code in the access.xml of the reuqested component. Eg if you create field groups for com_content, you need something like
````
	<section name="category.article">
		<action name="core.create" title="JACTION_CREATE" description="COM_CATEGORIES_ACCESS_CREATE_DESC" />
		<action name="core.delete" title="JACTION_DELETE" description="COM_CATEGORIES_ACCESS_DELETE_DESC" />
		<action name="core.edit" title="JACTION_EDIT" description="COM_CATEGORIES_ACCESS_EDIT_DESC" />
		<action name="core.edit.state" title="JACTION_EDITSTATE" description="COM_CATEGORIES_ACCESS_EDITSTATE_DESC" />
		<action name="core.edit.own" title="JACTION_EDITOWN" description="COM_CATEGORIES_ACCESS_EDITOWN_DESC" />
	</section>
````
in https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/access.xml

**Comment by brianteeman** [comment]
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12730">issues.joomla.org/tracker/joomla-cms/12730</a>.</sub>

**Comment by brianteeman** [comment]
@zero-24 this can be closed as it was fixed here https://github.com/joomla/joomla-cms/pull/13019/files#diff-2f89d1829941ad2925fcb5cafff47fce

**Comment by zero-24** [comment]
Thanks @brianteeman
