### ISSUE TITLE
Field type List  0 Class 'JFormFieldList' not found on frontend

### ISSUE THREAD

**Issue by ketihar** [joomla/joomla-cms#12743]
### Steps to reproduce the issue
Create one article
Create one field type list and put some names and values
Go to article and select one item from the list field
Save the article
Go to frontend and open article

### Expected result
Article with list value

### Actual result
Error   0 Class 'JFormFieldList' not found

### System information (as much as possible)
Έκδοση βάσης δεδομένων	5.7.14
Ευρετηρίαση βάσης δεδομένων	utf8_general_ci
Σύνθεση σύνδεσης βάσης δεδομένων	utf8mb4_general_ci
Έκδοση PHP	7.0.10
Διακομιστής ιστοσελίδων	Apache/2.4.23 (Win64) PHP/7.0.10
Διεπαφή Διακομιστή Ιστοσελίδων με την PHP	apache2handler
Έκδοση Joomla!	Joomla! 3.7.0-dev Development [ Noether ] 18-October-2016 16:37 GMT
Έκδοση Joomla!	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by ggppdk** [comment]
Fixed in this PR: #12739
