### ISSUE TITLE
Undefined variables in ConfigControllerModulesSave

### ISSUE THREAD

**Issue by izharaazmi** [joomla/joomla-cms#12768]
https://github.com/joomla/joomla-cms/blob/staging/components/com_config/controller/modules/save.php#L84

The variables $app and $data aren't defined in scope. I don't know the context hence could not attempt a fix. May be someone can do that.

PS: Code review based only.

**Comment by mbabker** [comment]
`$app` should be `$this->app`.

As for `$data`, because of how this task chains into a `com_modules` controller and looking at that method's code, it looks like that should be replaced by `$this->input->post->get('jform', array(), 'array');`.

**Comment by ghost** [comment]
@izharaazmi any Update on above Comment?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12768">issues.joomla.org/tracker/joomla-cms/12768</a>.</sub>

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 26th December 2017.

**Comment by ghost** [comment]
closed as having Pull Request #19003
