### ISSUE TITLE
SQL exception happens when editing a menu (SQL Server)

### ISSUE THREAD

**Issue by freegink** [joomla/joomla-cms#12761]
### Steps to reproduce the issue
1. Go to "Menu->Manage"
2. Select a menu
3. Click "Edit"

 

### Expected result
Editing menu interface should appear.

### Actual result
An SQL exception happens:
[Microsoft][ODBC Driver 11 for SQL Server][SQL Server]No column name was specified for column 1 of 'A'. SQL=SELECT * FROM ( SELECT count(id) , ROW_NUMBER() OVER (ORDER BY (select 0)) AS RowNumber FROM #__usergroups) A WHERE A.RowNumber BETWEEN 1 AND 1 

### System information (as much as possible)
Joomla 3.6.4
Windows Server 2008 R2
IIS 7
SQL Server 2008 R2

### Additional comments
This exception is caused by below code in "/libraries/cms/helper/usergroups.php". setQuery shouldn't pass "limit" and "offset" parameters because an alias is required for aggregation "count(id)" in subquery.
```php
        public function total()
	{
		if (null === $this->total)
		{
			$db = JFactory::getDbo();
			$query = $db->getQuery(true)
				->select('count(id)')
				->from('#__usergroups');
			$db->setQuery($query, 0, 1);
			$this->total = (int) $db->loadResult();
		}
		return $this->total;
	}
```

**Comment by zero-24** [comment]
Closing as there is a PR at #12762
