### ISSUE TITLE
Some issues with ACL system

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#12765]
### Steps to reproduce the issue

As talked in https://github.com/joomla/joomla-cms/pull/12069 there are some otimization that can be done in the ACL system

- Review ACL in installation files
- When creating new item don't hardcode the parent ACL rules. It should be empty `{}` if no permissions are set. ACL system should inherits from parent so we should not hardcode the parent rules in the child.
- The ACL between installation, saving an item editing an item should be consistent.

### System information (as much as possible)

Latest staging

### Additional comments

Some relevant parts of the ACL system:
- Rules form field: https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/fields/rules.php#L137
- AJAX rules save: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_config/model/application.php#L400
- JTable asset Save: https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/table/table.php#L798
- JTableAsset: https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/table/asset.php
- JAccess libraries: https://github.com/joomla/joomla-cms/tree/staging/libraries/joomla/access

As discussed, @sanderpotjer please review if this is what is needed.

**Comment by sanderpotjer** [comment]
@andrepereiradasilva thanks, it indeed is a summary of what is needed. The only thing I would add is that only the actions relevant to the item are being stored in the database once just one of the actions is set for an item. So make sure the `core.admin`, `core.options` and `core.manage` are not stored when setting one of the actions for a category for example, as these actions only apply to the component section, not the category.

**Comment by andrepereiradasilva** [comment]
ok so for what i see, we need at leaset the following PR:
1. Review installation ACL sql
2. Review save permissions trough AJAX
3. Review save permissions when creating an item.

Also i noticed languages and ucm content create a strange ACL name with the db table name. IMHO that should be reviewed too in another PR (4.).

I am working on `2.` and, if i have time, will try to work on `3.` after.

**Comment by ggppdk** [comment]
Please do ping me when you make PR that changes core ACL stuff, like JAccess class and AJAX saving

**Comment by andrepereiradasilva** [comment]
sure thanks!

**Comment by mbabker** [comment]
What from this issue does https://github.com/joomla/joomla-cms/pull/14268 not cover?

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 26th December 2017.

**Comment by ghost** [comment]
Closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12765">issues.joomla.org/tracker/joomla-cms/12765</a>.</sub>
