### ISSUE TITLE
04 January 2012 - default demo dates

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#12772]
### Steps to reproduce the issue

Install Joomla 
Look at front page 

### Expected result

A recent created date nearer to the release date, to give the impression that Joomla is not stuck in 2012 and a dead project.... 

### Actual result

<img width="318" alt="screen shot 2016-11-05 at 14 30 57" src="https://cloud.githubusercontent.com/assets/400092/20030817/7daf3eb8-a364-11e6-939d-58cb16ede1aa.png">

### System information (as much as possible)

https://gist.github.com/cef0b6b329c90eeb3cdd9bfe937b8160

**Comment by PhilETaylor** [comment]
Could also change the "Written by Joomla" to be something else, or at an explanation mark?

**Comment by andrepereiradasilva** [comment]
see https://github.com/joomla/joomla-cms/pull/11577

**Comment by PhilETaylor** [comment]
Great minds think alike :)
