### ISSUE TITLE
[com_fields] aliastag

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#12778]
What is this field type - its at the top of the list but I dont see anything about this fieldtype in the docs?

**Comment by Bakual** [comment]
Imho it is one of the useless fields. Alias is usually used for generating SEF URLs. Since we never ever generate a SEF URL to a single field, the alias is useless here.

See also https://github.com/joomla/joomla-cms/issues/12733 for other (imho) useless parameters in fields.

**Comment by brianteeman** [comment]
I guess its a different case to #12733 as that is for params for com_fields and this is about one of the field types being offered<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12778">issues.joomla.org/tracker/joomla-cms/12778</a>.</sub>

**Comment by brianteeman** [comment]
Closed see #12779

**Comment by Bakual** [comment]
Ah sorry, misread it then.
