### ISSUE TITLE
[j4] Table 'tozyj_user_keys' should not have column 'invalid'. (From file 4.0.0-2016-10-02.sql.)

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#12773]
### Steps to reproduce the issue

Install 4.0-dev
Admin -> Extensions ->Manage ->database

### Expected result

An up to date database as I just installed Joomla!

### Actual result
<img width="790" alt="screen shot 2016-11-05 at 14 44 03" src="https://cloud.githubusercontent.com/assets/400092/20030911/56a8c35a-a366-11e6-8ca3-8c6bbb5be979.png">

### System information (as much as possible)

https://gist.github.com/cef0b6b329c90eeb3cdd9bfe937b8160

**Comment by PhilETaylor** [comment]
Also when clicking fix I get

```
An error has occurred.
0 Class 'JControllerLegacy' not found

```

**Comment by brianteeman** [comment]
Updated title to show j4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12773">issues.joomla.org/tracker/joomla-cms/12773</a>.</sub>

**Comment by csthomas** [comment]
Take a look at https://github.com/joomla/joomla-cms/issues/12926

**Comment by mbabker** [comment]
Fixed via https://github.com/joomla/joomla-cms/commit/3e4fbf9623986ba3ff522d4167bec2c65dd8bc03
