### ISSUE TITLE
Regression 3.7: menu item params loaded incorrectly

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#12787]
### Steps to reproduce the issue
Use JApplicationSite getParams('com_mycomponent') method for a certain component in the frontend, having a valid routed menu item.

### Expected result
All component params are merged with the specific menu item parameters in the same JRegistry object
If you have a menu item parameter 'myparam' and you call:
$registry = $this->app->getParams('com_mycomponent') ;

You always had:
$myParam = $registry->get('myparam');

### Actual result
Menu item parameters are not merged as properties of the JRegistry object that can be obtained using the JRegistry 'get' method, but instead menu items parameters are all included in an array property named 'data'. 
If you have a menu item parameter 'myparam' and you call:
$registry = $this->app->getParams('com_mycomponent') ;

You have:
$menuParameters = $registry->get('data');
$myParam = $menuParameters['myparam'];

### System information (as much as possible)
Issue is due to the change at root/libraries/cms/application/site.php line 355 from: 
`$temp = new Registry;
$temp->loadString($menu->params);`

to

`$temp = new Registry($menu->params);`

**Comment by zero-24** [comment]
Please send changes as pull requests that made it easy for tests. Thanks..

**Comment by joeforjoomla** [comment]
Ok PR opened
