### ISSUE TITLE
Regression J3.7. Access inheritance broken on non core actions

### ISSUE THREAD

**Issue by Fedik** [joomla/joomla-cms#12785]
### Steps to reproduce the issue
To demonstrate the problem try to edit `administrator/components/com_content/access.xml`
In section `<section name="article">` add custom rule:
`<action name="com_content.foobar" title="foobar" description="foobar" />`
so it looks like:
```xml
<section name="article">
 <action name="core.delete" title="JACTION_DELETE" description="COM_CONTENT_ACCESS_DELETE_DESC" />
 <action name="core.edit" title="JACTION_EDIT" description="COM_CONTENT_ACCESS_EDIT_DESC" />
 <action name="core.edit.state" title="JACTION_EDITSTATE" description="COM_CONTENT_ACCESS_EDITSTATE_DESC" />
 <action name="com_content.foobar" title="foobar" description="foobar" />
</section>
```

Then edit the article, and set for **Public** group `foobar` action to **allowed** and Save:
![screen 2016-11-06 16 40 44 854x256](https://cloud.githubusercontent.com/assets/1568198/20038643/e2bbb08a-a43f-11e6-91f1-23473f7d27a3.png)

Then check access for Guest group.

### Expected result
Access for `foobar` rule **inherit** and **allowed**
![screen 2016-11-06 16 43 16 854x256](https://cloud.githubusercontent.com/assets/1568198/20038665/3e52bace-a440-11e6-9f75-45b7cf5d7f9e.png)

### Actual result
Access for `foobar` rule **inherit** and **NOT allowed**
![screen 2016-11-06 16 45 10 854x256](https://cloud.githubusercontent.com/assets/1568198/20038675/78b6b95e-a440-11e6-8f70-acc8472c1dc5.png)

### System information (as much as possible)
Joomla staging. php 7.0.8

### Additional comments
It do not affect core extension, but can make **huge** problem for 3rd extension which use custom actions.
All works fine on Joomla! 3.6.4
I think it somehow related to #12028 , because `JAccess::getAssetRules` return different result between J3.6 and  J3.7

**Comment by zero-24** [comment]
@andrepereiradasilva can you take a look into this?

**Comment by Fedik** [comment]
ok, it also affect `com_module` for `module.edit.frontend` action.

Try set for any module, for "Manager" group "Frontend Editing" => "allowed" , save 
and check "Administrator" group "Frontend Editing" should be **Inherited (Allowed)** but it **Inherited (NOT Allowed)**

**Comment by andrepereiradasilva** [comment]
@Fedik will check if this

**Comment by andrepereiradasilva** [comment]
ok so i found the issue, now i have to solve it and do A LOT of tests ...

**Comment by andrepereiradasilva** [comment]
please check https://github.com/joomla/joomla-cms/pull/12809

**Comment by Fedik** [comment]
@andrepereiradasilva thanks! I try to test it this evening
