### ISSUE TITLE
[lang] JGLOBAL_USE_GLOBAL_VALUE key contains brackets

### ISSUE THREAD

**Issue by nvyush** [joomla/joomla-cms#12805]
### Steps to reproduce the issue
The files
`/administrator/language/en-GB/en-GB.ini`
`/language/en-GB/en-GB.ini`
contain new key ```JGLOBAL_USE_GLOBAL_VALUE="Use Global (%s)"``` with brackets (from pull request #11911).
This can lead to problems when translated into some languages. May be better to replace the brackets with mdash or colon?

### System information (as much as possible)
Current staging version.

**Comment by Bakual** [comment]
> This can lead to problems when translated into some languages.

I don't understand the issue. The brackets are part of the translateable string. If some languages prefer some other display, just change it in that language. It's only the "%s" which gets replaced by the global value.

**Comment by nvyush** [comment]
Ok
