### ISSUE TITLE
[com_fields] list with "multiple" enabled can't remove all options

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#12812]
### Steps to reproduce the issue
1. Create a custom field with at least two options and set the "Multiple" parameter to "Yes"
2. Open an item and see the empty box for the field. Select one or more options and save.
3. Open the item again and see the selected options. That should work fine.
4. Now try to remove all selected options, making the box empty again and save the item.
5. Check the item item again

### Expected result
The box should stay empty

### Actual result
The box keeps the last saved options, making it impossible to reset the field to "nothing selected"

**Comment by ralain** [comment]
Confirming this. There's a similar issue with the Gallery field type, although in that case you can choose "- None Selected -" to force an empty value.

**Comment by laoneo** [comment]
Can be closed now as we have a PR #12967. Can you guys please test it.
