### ISSUE TITLE
Update 3.6.2 to 3.6.4 seems broken in Windows environment

### ISSUE THREAD

**Issue by milux** [joomla/joomla-cms#12816]
### Steps to reproduce the issue

Setup test environment with XAMPP on Windows, using Joomla 3.6.2.
Try to update to latest version using the built-in updater.

### Expected result

Successful update to 3.6.4

### Actual result

With "simple" error output:
Warning: file_put_contents(C:\xampp\htdocs\straug\tmp\joomla_3-6-4-stable-update_package-zip?format=zip&jcompat=my.zip): failed to open stream: No such file or directory in C:\xampp\htdocs\straug\libraries\joomla\filesystem\file.php on line 435

### System information (as much as possible)

XAMPP test environment with PHP 7.0.10 on Windows 10 x64.

### Additional comments

The problem is likely caused by "?" of the query string, being an invalid character for filenames on Windows.
I will submit a pull request which fixes this by resolving the actual filename, following the "Location" HTTP headers to the real download location on AWS.

**Comment by mbabker** [comment]
Additional context: https://github.com/joomla/joomla-websites/issues/742

**Comment by milux** [comment]
@mbabker: Thanks, thought that I surely wasn't the first person to face this issue, but overlooked this issue when searching.

**Comment by jeckodevelopment** [comment]
Closed since we have a PR for this: #12817
