### ISSUE TITLE
[com_fields] Checkboxes don't show a stored 0 value option

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#12810]
### Steps to reproduce the issue
1. Create a custom field of the type checkboxes and assign two options, one of them with a 0 value. Eg:
![yesno](https://cloud.githubusercontent.com/assets/1018684/20058361/e5bd7870-a4f0-11e6-9314-72ae0ec6d9b5.PNG)
2. Select only the 0 value ("No" in my example) and save
3. Reopen the form and check the value. Check the item in frontend.

### Expected result
The selected 0 value is shown in both places

### Actual result
The selected 0 value is ignored in both places

### Additional comments
This is an issue with how com_fields sets up the fields.
If I specify a checkboxes field in the form XML with the same options, it works fine. So it's not the JFormFieldCheckboxes that is buggy.
When debuging I saw that when the form is defined in the XML, the value in https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/fields/checkboxes.php#L153 is an array (even with only one option) and the `$hasValue` passes. However if it is coming from com_fields, the value is a string if it's only one selected option and thus the check fails.

Now we could adjust the formfield to take care of strings as well, but I don't know the side effects as checkboxes are really a strange thing to handle.

I'd prefer to fix it in com_fields, but I haven't found yet where we could do it.
Also it may be related to the `$forceMultiple` property that is set in the checkboxes field. Maybe com_fields need to read that one and act accordingly.

**Comment by laoneo** [comment]
Added a callback to the field to prepare the value in #12886.

**Comment by laoneo** [comment]
Can be closed as we have a PR #12886.
