### ISSUE TITLE
 Fatal error: Cannot use Joomla\String\String as String because 'String' is a special class name in /var/www/falckcc.dk/public_html/administrator/components/com_weblinks/models/weblink.php on line 13

### ISSUE THREAD

**Issue by majaelleby** [joomla/joomla-cms#12837]
Upgraded Joomla from earlier version (3.6.2) 

### Expected result
Component: weblinks working

### Actual result
Follow error message, when creation a new web link:

Fatal error: Cannot use Joomla\String\String as String because 'String' is a special class name in /var/www/falckcc.dk/public_html/administrator/components/com_weblinks/models/weblink.php on line 13

### System information (as much as possible)
Joomla version: 3.6.4
PHP version: 7.0.12
URL: Fakckcc.dk
MySQL: 5.6.32
Site hosted at: unoeuro.com

### Additional comments
I thought this issue was solved in an earlier Joomla version, but it seems to have returned. What to do?

**Comment by mbabker** [comment]
Ensure you've updated weblinks to the current version.  If it's still an issue file a report at https://github.com/joomla-extensions/weblinks
