### ISSUE TITLE
Nested Subforms not saving values

### ISSUE THREAD

**Issue by hennysmafter** [joomla/joomla-cms#12838]
### Steps to reproduce the issue
Create a module. Add a repeatable subform(lvl1). Inside this subform add another subform(lvl2).

### Expected result
It should load the subforms from lvl1 & lvl2 and save the values from both subforms.

### Actual result
It loads alright but it does not save any value from lvl2 or any deeper lvl if you created those (lvl3, 4, 5). 

### System information (as much as possible)
Latest Joomla, PHP 7.10

### Additional comments
This happens whenever you include a subform from the same module and even when you grab them out of another module. Especially with the latest you quickly get into trouble because whenever you pick a module that already has a subform init then it won't work. Which I believe one of the reason the subform was created in the first place.

Don't get me wrong I love the subform and the functionality but I also think that nested subforms should work!

### Stackoverflow Issue
I created a SO issue before I posted in here: https://joomla.stackexchange.com/questions/18285/joomla-3-6-nested-subforms-not-saving

It might hold some more valuable information.

**Comment by Fedik** [comment]
nested subform not supported for now,
there already opened issue for it #11551

**Comment by brianteeman** [comment]
Thanks for reporting this but as we have an existing issue for this I am going to close this here. Please comment on the existing issue

**Comment by hennysmafter** [comment]
@Fedik @brianteeman Ahhh. Now I see I hadn't searched for Multi level. I should have searched on subform alone. Thanks for pointing me towards it.
