### ISSUE TITLE
problemas con el gestor de modulos

### ISSUE THREAD

**Issue by sebamasaguer** [joomla/joomla-cms#12849]
### Steps to reproduce the iss
despues de la ultima actualización![screen shot 2016-11-09 at 07 52 02](https://issues.joomla.org/uploads/1/35ee18806321e2c9f3c3a6e7da6ea727.jpg) no puedo entrar al gestor de módulos. adjunto imagen

**Comment by andrepereiradasilva** [comment]
clear or browser cache.

**Comment by sebamasaguer** [comment]
no funciona.. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12849">issues.joomla.org/tracker/joomla-cms/12849</a>.</sub>

**Comment by brianteeman** [comment]
I am closing this as it will be resolved as @andrepereiradasilva says by clearing your browser cache. Note that if you have a server level cache as well such a cloudflare or from your web host then you will have to clear that as well.

If you still have difficulties then please use the forum for support https://forum.joomla.org

**Comment by sebamasaguer** [comment]
Clean and continue the same problem
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12849">issues.joomla.org/tracker/joomla-cms/12849</a>.</sub>
