### ISSUE TITLE
Custom Fields in component Articles - Joomla 3.6.4

### ISSUE THREAD

**Issue by javimata** [joomla/joomla-cms#12853]
### Steps to reproduce the issue
i need add 2 fields to the component content (articles), need add 2 images and try some examples but don't work :-( have a github with the last try

https://github.com/javimata/plg_addfield

Can help me to check what happend? what i do wrong?

### Expected result
View 2 fields new in the component

### Actual result
I don't see the fields

### System information (as much as possible)
Nothing

### Additional comments
I try the example in the official documentation and i use it but dont work

**Comment by zero-24** [comment]
This is a issue tracker and not a support forum. Please try to ask here: https://groups.google.com/forum/m/#!forum/joomla-dev-cms/

Maybe you can also try the new custom fields features in the comming 3.7.x: https://developer.joomla.org/nightly-builds.html
