### ISSUE TITLE
Cache group in extension XML file

### ISSUE THREAD

**Issue by pioada** [joomla/joomla-cms#12860]
### Steps to reproduce the issue
Joomla! Core

### Expected result
There should be possible to set cache group in extension XML file, similar to eg. 'cachemode' in administrator/modules/mod_stats_admin/mod_stats_admin.xml.

### Actual result
There is not possible to store cache in other group then extension that create cache file.

### System information (as much as possible)
-

### Additional comments
I need it for my menu module. Only way to clear this module cache file is to place it in 'com_modules' or 'mod_menu'. Check administrator/components/com_menus/models/item.php function 'cleanCache'.

**Comment by franz-wohlkoenig** [comment]
This has been closed due to lack of response to the requests above - it can always be reopened in the future if it is updated
