### ISSUE TITLE
new menu item check

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#12862]
### Steps to reproduce the issue
It is not allowed that a menu item alias is the same as a sub-folder in your Joomla installation.
The message will be: "Save failed with the following error: A first level menu item alias can't be 'tmp' because 'tmp' is a sub-folder of your joomla installation folder."
My problem is that when you enter a new menu item this check is not done, before creating the menu item.
So you can create a menu item with the name of a sub-folder. The moment the item is creacted you can't save it again.
### Expected result
Check before the item is created.
### Actual result
No check and an error on the frontend of the site because your not allowed to browse a sub-folder.

**Comment by brianteeman** [comment]
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12862">issues.joomla.org/tracker/joomla-cms/12862</a>.</sub>

**Comment by infograf768** [comment]
On it.

**Comment by infograf768** [comment]
Please test
https://github.com/joomla/joomla-cms/pull/12871

**Comment by infograf768** [comment]
Closing as we have a patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12862">issues.joomla.org/tracker/joomla-cms/12862</a>.</sub>
