### ISSUE TITLE
Small graphic issue in popovers

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#12873]
### Steps to reproduce the issue

Just mouseover some options and notice the popovers with just one line of text get a blank line after the text.

### Expected result

no one line of space after text. works like popovers with two or more lines of text

![image](https://cloud.githubusercontent.com/assets/9630530/20237077/3002824a-a8c0-11e6-85c4-051cd387ee57.png)

### Actual result

![image](https://cloud.githubusercontent.com/assets/9630530/20237066/e5628e60-a8bf-11e6-9c68-3285f6b1e4d4.png)

### System information (as much as possible)

latest staging

### Additional comments

none

**Comment by brianteeman** [comment]
This is coming from the change I made to address #11256<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12873">issues.joomla.org/tracker/joomla-cms/12873</a>.</sub>

**Comment by brianteeman** [comment]
If I remember correctly we can either have the blank line you report here or the display issue reported in #11256 - I dont see a solution to both. 

If thats the case then I would live with this one as it effects just a % of popover whereas 11256 effects almost all popovers.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12873">issues.joomla.org/tracker/joomla-cms/12873</a>.</sub>

**Comment by C-Lodder** [comment]
This should be a tooltip anyway, not a popover. There's a difference ;)

**Comment by franz-wohlkoenig** [comment]
Issue stay on latest 3.7-staging.

**Comment by Quy** [comment]
I am fine with the blank line. Another option is to display the popover without the title like a tooltip.

![popover-line1](https://user-images.githubusercontent.com/368084/32402539-70288478-c0e3-11e7-9b8f-a18225fd7fe0.jpg)
![popover-line2](https://user-images.githubusercontent.com/368084/32402540-72fcebee-c0e3-11e7-8c48-a9c9ad9bb9f9.jpg)

**Comment by brianteeman** [comment]
Making that change would require all screenshots in the help to be redone and I really dont see the need for that

**Comment by Quy** [comment]
It is a minor issue affecting a few tooltips. Is it even worth fixing?

**Comment by brianteeman** [comment]
Closing - such a low priority item and https://github.com/joomla/joomla-cms/issues/12873#issuecomment-260292854
