### ISSUE TITLE
Recaptcha on Registration Page

### ISSUE THREAD

**Issue by clumsden** [joomla/joomla-cms#12872]
### Steps to reproduce the issue
Create Account (Registration) page of Joomla site
attempted registration / create new user does not work as ReCaptcha returns no result (from not being visible)

### Expected result
able to see ReCaptcha module

### Actual result
no recaptcha visible on Registration page
***ReCaptcha IS VISIBLE on "Forgot Username" and "Forgot Password" pages.***

### System information (as much as possible)
Joomla 3.6.4
Purity III template v1.1.7
Recaptcha 2.0
fresh keys
cache cleared / purged

### Additional comments
see website:
https://chemistry.lumsdenweb.com/home/registration

odd that it works on two out of three pages.

**Comment by brianteeman** [comment]
Can you test and make sure it work with one of the default templates eg
protostar. This will remove the possibility that it's a bug in your
templates overrides.

**Comment by clumsden** [comment]
Hi Brian,

Thanks - I had to make a new site to test it - it seems that it must be a template issue - shall I cancel the ticket or can you do that?

Cameron


Cameron Lumsden
Auenstrasse 29, 
80469 Munich, GERMANY
Home: +49 89 2020 9299 | Mobile: +49 171 629 1969 | Email: cameron@lumsdenweb.com

**Comment by brianteeman** [comment]
Closing this as it not a core issue

**Comment by ZerooCool** [comment]
Not necessarily a template problem.
This can also be a server problem if a security policy has been implemented (CSP).

The captcha is not displayed?
Wait a few minutes for Google to consider your site.

If your server has a CSP security policy, the connection to Google may not be allowed.
Add the address https://www.google.com and https://www.gstatic.com in the allowed script-src values of your CSP.
Add the https://www.google.com address to the allowed frame-src values of your CSP.

https://www.visionduweb.fr/blog/18-joomla/127-ajouter-un-captcha-pour-proteger-joomla
