### ISSUE TITLE
ACL permission group left tab is not preselected

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#12878]
### Steps to reproduce the issue

- Logout and clear your browser cache (or use a private browser window)
- Login in admin
- Go directly to global config and permissions tab
- Notice the "Public" permissions left tabs (groups) are not selected.

### Expected result

Tab preselected

### Actual result

![image](https://cloud.githubusercontent.com/assets/9630530/20246244/e4d9a51e-a9aa-11e6-94c4-407ab41bd8fe.png)

### System information (as much as possible)

latest

### Additional comments

none

**Comment by andrepereiradasilva** [comment]
@dgt41 since you fixed the other tabs, pinging you on this 😄

**Comment by dgt41** [comment]
I'll give it a try...

**Comment by franz-wohlkoenig** [comment]
Issue looks resolved on latest 3.7-staging.

**Comment by Bakual** [comment]
> Logout and clear your browser cache (or use a private browser window)

My guess is you need to not only clear the cache, but also the localStorage. That's what I try to fix with using sessionStorage for the tabs state (https://github.com/joomla/joomla-cms/pull/13572). This may be the same or similar thing.

**Comment by brianteeman** [comment]
Looks like this can be closed as it has been solved elsewhere @zero-24
