### ISSUE TITLE
Is there any interest for implementing assets preload?

### ISSUE THREAD

**Issue by dgt41** [joomla/joomla-cms#12870]
### Steps to reproduce the issue
Preload is a tag that dictates the browser to fetch immediately the resource instead of waiting to parse the HTML and then initiate the calls for the relative resource. 
It's super handy for mobiles (3G connections etc)

Implementations is straight forward allowing the docs: https://w3c.github.io/preload/

PS: I won't spend time creating a PR if there's no interest (already have a few of them)

**Comment by mbabker** [comment]
Yes.  Related, https://github.com/joomla/joomla-cms/issues/11077
