### ISSUE TITLE
Alignment of fields on Article Edit Page

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#12880]
### Steps to reproduce the issue

git clone git@github.com:joomla/joomla-cms.git
HEAD is now at 1a21f17 com_fields: allowing custom field Label to be translated by a string
php -S 127.0.0.1:8888
Install Joomla in web browser (with Default English (GB) Sample Data)
Login to Joomla Admin 
Content -> Articles -> Edit Getting Started article
->Configure edit Screen Tab

### Expected result

Nicely aligned dropdowns

### Actual result
<img width="543" alt="screen shot 2016-11-13 at 20 07 30" src="https://cloud.githubusercontent.com/assets/400092/20248476/dffbb00a-a9dc-11e6-97ea-32313ab9e394.png">

### System information (as much as possible)

https://gist.github.com/b5c59df75d1de2ff08922c46796cae3e

**Comment by PhilETaylor** [comment]
Some more realignment needed on the Images and Links tab too. 
<img width="464" alt="screen shot 2016-11-13 at 20 09 09" src="https://cloud.githubusercontent.com/assets/400092/20248491/15abdc70-a9dd-11e6-9912-21ecc39af70d.png">

**Comment by PhilETaylor** [comment]
and the publishing tab :( 
<img width="532" alt="screen shot 2016-11-13 at 20 09 55" src="https://cloud.githubusercontent.com/assets/400092/20248495/2c0f9c68-a9dd-11e6-9029-fa790bb4bded.png">

**Comment by dgt41** [comment]
It gets even worst for non english languages, e.g. Greek:
![screen shot 2016-11-13 at 22 10 33](https://cloud.githubusercontent.com/assets/3889375/20248507/2b26c964-a9ee-11e6-8d07-288dc0252599.png)

**Comment by PhilETaylor** [comment]
thats why I closed it - dont want to open a can of worms even though you have the WHOLE WIDTH of the page to use, for some reason Joomla likes the first column to be as wide as a postage stamp :(

**Comment by dgt41** [comment]
@PhilETaylor But YOU ARE RIGHT. And someone has to point all these crap otherwise will never be fixed

**Comment by brianteeman** [comment]
Isn't this exactly what the ux team is for?

**Comment by dgt41** [comment]
@brianteeman can you show me one (1) PR from that group?

**Comment by PhilETaylor** [comment]
> Isn't this exactly what the ux team is for?

Now where have I heard that before... 

Doesn't mean that people without a badge or team membership cannot comment or hold people to account ... hell, Trump is President(elect) now... anything is possible...

**Comment by ggppdk** [comment]
And ... i was going to say that for translations e.g. german or greek this effect appears more often

and it will always be not aligned,
- unless it is decided to limit their width and allow wrapping of long labels

opinion, limiting labels width is a lot better than this miss-alignment effect

**Comment by brianteeman** [comment]
No. I was merely pointing out that we have such a group led by cliff and I
would expect it to be something thry would be looking at.

**Comment by dgt41** [comment]
@brianteeman that was rhetorical question, I already know the answer. Said that shouldn't be a way to evaluate group/people's work and either assign or remove badges/memberships etc? This is supposed to be open source and I would expect some some clarity on such matters. I am dreaming again...

**Comment by dgt41** [comment]
> unless it is decided to limit their width and allow wrapping of long labels

I won't say I like this

> or it is decided to use a different placement, e.g. placing the label on top of the field

@ggppdk this would be fine for me, also it's an easy change
