### ISSUE TITLE
Deleting submitter user objects breaks message counts in admin

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#12883]
### Steps to reproduce the issue

Forked issue from #12881

Create an admin and a frontend user with article submission rights on frontend (like Author)

On my site I have an admin and a Front End Author 

The front end author submits 3 articles on the front end - this generates 3 messages in my private inbox in Joomla Admin.

If someone then deletes that "front end author" then I'm now suck with "(3) Messages" in my admin footer but no messages in my com_messages screen

### Expected result

0 Messages in footer... 
or
3 messages viewable in mailbox

### Actual result
<img width="715" alt="screen shot 2016-11-13 at 20 56 14" src="https://cloud.githubusercontent.com/assets/400092/20248811/a8750e2c-a9e3-11e6-9f5b-9a28adab224a.png">

### System information (as much as possible)

https://gist.github.com/b5c59df75d1de2ff08922c46796cae3e

**Comment by tonypartridge** [comment]
Replicated the issue. 

I would advise we add a delete messages query to onUserAfterDelete function within PlgUserJoomla to clear up the orphaned messages given messages is a core component. 

In fact, going back to your first post to an extent. We could look at having the plugin look for certain 'deletion' files within components to avoid developers having to write multiple plugins to manage this.

**Comment by alikon** [comment]
> Expected result
> 
> 0 Messages in footer...
> or
> 3 messages viewable in mailbox
> 

delete the messages items from that user ,
for test #13052
