### ISSUE TITLE
Typo in Chinese Traditional Site Package

### ISSUE THREAD

**Issue by kenleegit** [joomla/joomla-cms#12884]
### Steps to reproduce the issue

Upgraded Chinese Traditional Site Package from 3.6.0.1 to 3.6.3.1 using Extension Update at back-end.

### Actual result
/language/zh-TW/zh-TW.lib_joomla.ini
Line 643: JJLIB_MAIL_INVALID_EMAIL_SENDER=.....
JJLIB should be a typo error.
### System information (as much as possible)
Joomla! 3.6.4 Stable [ Noether ] 21-October-2016 16:33 GMT

**Comment by infograf768** [comment]
Please contact the Traditional Chinese Translation Coordinator:
Eddy Chang at http://forum.joomla.org/memberlist.php?mode=viewprofile&u=1604
In the mean while, I suggest to use Languages->Overrides to solve the issue on your site.

**Comment by brianteeman** [comment]
Closed as this is not something that can be handled on this issue tracker as stated above.
