### ISSUE TITLE
Submit Web Link menu item with Access Guest or Public results in requested page can't be found

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#12889]
Maybe this is a weblinks (ACL) issue? Then it must switch to the Weblinks Issues Tracker.

### Steps to reproduce the issue
Add a menu item "Submit a Web Link" (official WebLinks component).
Keep the Access of the menu item "Public".
Go to the fronend (no login).

### Expected result
The possibility to add a weblink for everybody on the site.

### Actual result
Message: "The requested page can't be found."

### System information (as much as possible)
Clean install J 3.6.4.

### Additional comments
Turning the Access of the menu item into "Registered" makes the menu item vissible or the message "Please login first."

**Comment by brianteeman** [comment]
Thanks for reporting this but as weblinks is decoupled you will need to submit this to the weblinks tracker - sorry

https://issues.joomla.org/tracker/weblinks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12889">issues.joomla.org/tracker/joomla-cms/12889</a>.</sub>
