### ISSUE TITLE
[j3.7] a11y Regression outline on toolbar

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#12894]
#11724 This PR added visible highlights when tabbing through the ui

Something - probably the flat paint - is preventing that now although the css from #11724 is still present

@ciar4n could you take a look please - its beyond my css skill level - ie its more than !important ;) ;)

**Comment by ciar4n** [comment]
@brianteeman  :).. nothing wrong with the occasional brute force!

With your PR should did the blue outline appear on :hover or just :focus?

**Comment by brianteeman** [comment]
its for keyboard nav so really only needs to be on :focus although I suspect I probably did it on :hover as well as thats my preference for a11y for not just keyboard users

**Comment by brianteeman** [comment]
closed as we have a PR #12896<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12894">issues.joomla.org/tracker/joomla-cms/12894</a>.</sub>
