### ISSUE TITLE
[mod_menu] Menu module adds parent class even if all subitems are set not to display

### ISSUE THREAD

**Issue by tomekomel** [joomla/joomla-cms#12890]
### Steps to reproduce the issue
Create menu with some subitems for some postion.
Set to all subitems property Display in Menu to No.

### Expected result
Subitems are not displayed and parent element has no "parent" class added.

### Actual result
Those subitems are not displayed as expexted but parent item has css class "parent".
It causes some issues with dropdown menu systems for example.

### System information (as much as possible)
Jooma 3.6.4.

**Comment by brianteeman** [comment]
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12890">issues.joomla.org/tracker/joomla-cms/12890</a>.</sub>

**Comment by brianteeman** [comment]
closed as we have a PR for testing - see #12941 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12890">issues.joomla.org/tracker/joomla-cms/12890</a>.</sub>
