### ISSUE TITLE
Add a "contains" type method to cache API

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#12893]
The [PSR-6 spec](http://www.php-fig.org/psr/psr-6/) for a cache item pool (very loosely translated to our `JCacheStorage` adapters) includes a `public function hasItem($key);` method in its interface which is a way to check if the cache contains an item with that key.  `JCache` doesn't have a comparable interface method.

This can be useful for checking the presence of a cache item before making a get call, especially as many adapters have more efficient methods corresponding to this intent.

**Comment by franz-wohlkoenig** [comment]
cause of #13452 this Issue can be closed?
