### ISSUE TITLE
Fatal error: Class 'ContentHelperRoute' not found in /tmp/tmp?????? on line 13

### ISSUE THREAD

**Issue by HousInfo** [joomla/joomla-cms#12902]
### Steps to reproduce the issue

http://www.jnsciences.org/component/contact/contact/1.html 

### Actual result

Fatal error: Class 'ContentHelperRoute' not found in /tmp/tmp?????? on line 13

### Additional comments
Hi,

After upgrade to joomla 3.6.4 i have this issue for every component like
http://www.jnsciences.org/component/contact/contact/1.html 
have you any idees please?

Thanks

**Comment by brianteeman** [comment]
Please use the forum for support https://forum.joomla.org

The fact that its looking in a non existent folder indicates that this is not a core bug<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12902">issues.joomla.org/tracker/joomla-cms/12902</a>.</sub>

**Comment by HousInfo** [comment]
it's a K2 Tools issue
solved by add this line 

if(!class_exists('ContentHelperRoute')) require_once (JPATH_SITE . '/components/com_content/helpers/route.php');

in components/com_k2/helpers/route.php

Thanks brianteeman<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12902">issues.joomla.org/tracker/joomla-cms/12902</a>.</sub>
