### ISSUE TITLE
No Access to Modules

### ISSUE THREAD

**Issue by calvaryumc** [joomla/joomla-cms#12900]
I installed the new updates.  Now I cannot access my modules.  When I click on slide show, for example, the screen is blank except for a small box in the upper left hand corner that says slide show.  There is a message on my homepage that says an error has occurred, but there is no option to fix the error.  Help please.

**Comment by Bakual** [comment]
See https://docs.joomla.org/J3.x:Can%27t_edit_modules_after_update_to_3.6.3
