### ISSUE TITLE
User groups ordered by "group title" results in warnings

### ISSUE THREAD

**Issue by beni71** [joomla/joomla-cms#12903]
### Steps to reproduce the issue

1. In the backend navigate to Users > Groups
2. Sort the list by "Group Title"

### Expected result
The list would be sorted asc/desc without a warning.

### Actual result
The list is sorted, but there are some notices and warnings showing like:

- Notice: Undefined property: stdClass::$path in <joomla_home>\libraries\cms\helper\usergroups.php on line 311
- Warning: array_merge(): Argument <hash_tag>1 is not an array in <joomla_home>\libraries\cms\helper\usergroups.php on line 311

### System information (as much as possible)
OS Windows
PHP 7.0.9
MySQLi 5.5.5-10.1.16-MariaDB
Caching Disabled
Gzip Disabled

### Additional comments
- Code actually pulled from staging branch.
- Install Sample Data: Test English (GB) Sample Data
- Debug configuration is set to joomla default.
- The same problem is also in the actual 3.7.x branch.

**Comment by brianteeman** [comment]
Confirmed in current 3.7 staging<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12903">issues.joomla.org/tracker/joomla-cms/12903</a>.</sub>

**Comment by phproberto** [comment]
Patch sent:
https://github.com/joomla/joomla-cms/pull/12904

**Comment by brianteeman** [comment]
Closing as we have a PR for testing See #12904<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12903">issues.joomla.org/tracker/joomla-cms/12903</a>.</sub>

**Comment by StefanSTS** [comment]
On update of J 3.7.2 to J 3.7.5 I got an internal server error when opening the user list.
Google led me here and I deactivated the newly introduced line 313 within the new if:
$parentGroup = $this->populateGroupData($parentGroup);

After this, the internal server error was resolved and it showed Warnings and Notices like in J 3.7.2 only in the user details view:
Notice: Undefined property: stdClass::$path in .../joomla/libraries/cms/helper/usergroups.php on line 316
Warning: array_merge(): Argument #1 is not an array in .../joomla/libraries/cms/helper/usergroups.php on line 316
Warning: array_merge(): Argument #1 is not an array in .../joomla/libraries/cms/helper/usergroups.php on line 316

Never got that in any other installation.
I will try to get the server logs from the customer.
PHP 7.0.20

**Comment by StefanSTS** [comment]
No error logs available yet.
The temporary solution was to set $parentGroup->path to an array which helped with the array_merge().
Everything is working without errors or warnings, but this will be overridden in the next J update, so I guess I open a new issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12903">issues.joomla.org/tracker/joomla-cms/12903</a>.</sub>
