### ISSUE TITLE
Cannot put two content languages with "No image"

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#12907]
### Steps to reproduce the issue

Add two content languages with no image.

### Expected result

Two content languages with no image.

### Actual result

SQL Error
![image](https://cloud.githubusercontent.com/assets/9630530/20330690/7100706a-ab98-11e6-835f-331947190cdc.png)

### System information (as much as possible)

latest

### Additional comments

there seems to be an unique index idx_image for image field in #__languages table

probably a missing part from https://github.com/joomla/joomla-cms/pull/12051

**Comment by brianteeman** [comment]
I can confirm this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12907">issues.joomla.org/tracker/joomla-cms/12907</a>.</sub>

**Comment by brianteeman** [comment]
Removing the unique index resolves it - does this even need an index?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12907">issues.joomla.org/tracker/joomla-cms/12907</a>.</sub>

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/table/language.php#L71

The code requires a unique image per language.  It's not just the table indexes.  I never understood it but for whatever reason I got conned to adding it onto https://developer.joomla.org/joomlacode-archive/issue-27196.html

**Comment by brianteeman** [comment]
The argument for it being unique is to prevent a user being stupid and
having two or more languages with the same image. You can't fix stupid. If
you accidentally select the same image you will quickly see you've been
stupid and change it.

**Comment by andrepereiradasilva** [comment]
Imho It can still check for the same image except when no image.

**Comment by andrepereiradasilva** [comment]
please test https://github.com/joomla/joomla-cms/pull/12949
