### ISSUE TITLE
Exit links all classified as dangerous

### ISSUE THREAD

**Issue by juggielee** [joomla/joomla-cms#12914]
### Steps to reproduce the issue
the site has jooomla 3.6.4
the site is a directory and all pages are https
when users click on links to listed businesses all links give the warning of privacy error because the linked site is not https. Is there anything i can do to make this transition happen without the warning?

**Comment by brianteeman** [comment]
This is the issue tracker for bugs and new features in the core of Joomla. For support please use the forum https://forum.joomla.org
