### ISSUE TITLE
Module/Article edit.

### ISSUE THREAD

**Issue by Martinis** [joomla/joomla-cms#12912]
### Steps to reproduce the issue
After updating to newest version of Joomla (3.6.4) I started having problems with module, articles, menu editing. After logging in to the backend I edit e.g. module, save and exit it and when i want to edit anything else, module, article, menu, joomla breaks.(included gif). 
Also sometimes it doesn't even go to that broken page and just reloads the same page. I don't have any caching enabled or any other plugins/components installed. 
Cleaning browser cache doesn't help. This problem started after the update in all of my websites.
Only fix i noticed is to log out of back end and log in using incognito mode. However it breaks after a few edits and I have to log out and login all over again.

![screen shot 2016-11-16 at 09 46 24](https://issues.joomla.org/uploads/1/c9109ba9171a0609424c5332e0bd8ebe.gif)

**Comment by brianteeman** [comment]
You mention an included gif but there isnt one so its hard to guess what you mean by breaks
You mention you have no cache enabled but do you have any htaccess modifications and does your host have any caching<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12912">issues.joomla.org/tracker/joomla-cms/12912</a>.</sub>

**Comment by Martinis** [comment]
Well, i see that gif is showing after my text :) 
Like i said, this problem started happening after the update. Previous versions worked perfectly.
This problem happens on 3 different hosts. One of them is GoDaddy. 
htaccess is clean.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12912">issues.joomla.org/tracker/joomla-cms/12912</a>.</sub>

**Comment by brianteeman** [comment]
Weird the gif is displaying now

This issue shown is exactly the already documented known issue and it is 100% cache related

Dont forget that if your host provides caching then you will need to clear that as well.

For example Siteground has something called supercacher and if you are hosting with them then you will need to log in to your hosting control panel and flush the cache. The same is true if you are using a caching service such as cloudflare - Neither of these should be caching anything in the admin of your site but they do and its beyond our control. The same may be true of other services and hosts.

Note that incognito mode is not browsing without cache

**Comment by brianteeman** [comment]
As this is not an issue with the core (its annoying though and steps have been taken to ensure this browser and cache refresh isnt needed in the future) I am closing this here. If you still have issues please can you use the forum for support https://forum.joomla.org
