### ISSUE TITLE
[com_fields] SQL files for sqlazure missing

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#12910]
### Steps to reproduce the issue
Check folders 
* https://github.com/joomla/joomla-cms/tree/staging/installation/sql/sqlazure
* https://github.com/joomla/joomla-cms/tree/staging/administrator/components/com_admin/sql/updates/sqlazure

### Expected result
Find commands to create tables

### Actual result
No commands found

### Additional comments
Looks like it was only done for MySQL and PostgreSQL.

**Comment by laoneo** [comment]
Had a chat with @matrikular, probably he will help here out.

**Comment by alikon** [comment]
See #12660

**Comment by brianteeman** [comment]
Closing as this has already been done by @alikon in #12660 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12910">issues.joomla.org/tracker/joomla-cms/12910</a>.</sub>

**Comment by Bakual** [comment]
Sorry for not seeing that one.
