### ISSUE TITLE
Joomla Access Control Frontend

### ISSUE THREAD

**Issue by D4nzi** [joomla/joomla-cms#12924]
After updating the Joomla Version 3.6.x to 3.6.4, i do run into a big trouble, because literally every Site do now seems to be logged in as "SUPER USER". So i do see everything in Frontend without even log in. So JEvents shows me the possibillity to add Events, Menues that are only be visible while logged in, are now permanent visible without logging in.

### Steps to reproduce the issue
updating the Joomla 3.6.x Version to Joomla 3.6.4

### Expected result
New update without a kill of the ACL

### Actual result
ACL seems to be deactivated

### System information (as much as possible)
Joomla!-Version 	Joomla! 3.6.4 Stable [ Noether ] 21-October-2016 16:33 GMT
Joomla!-Plattform-Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 
Datenbankversion 	5.7.16
Datenbankzeichensatz 	latin1_german1_ci
Datenbankverbindungszeichensatz 	utf8mb4_general_ci
PHP-Version 	5.3.29
Webserver 	Apache 

### Additional comments
Failure is actual on 6 sites from me.

**Comment by brianteeman** [comment]
Go to the users component. Go to the options. There you will find a setting for the default guest user level. It should be set to public or guest.

**Comment by D4nzi** [comment]
Wow ok, that seems to work. Now i feel stupid XD because i didn't know that option there. But Thank you very very much.


------TOPIC closed-----<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12924">issues.joomla.org/tracker/joomla-cms/12924</a>.</sub>
