### ISSUE TITLE
[3.7]: Judder in selection field

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#12930]
### Steps to reproduce the issue
Open selection field (i.e. Weblinks > Select Tag) and scroll.

### Expected result
Curser moves smooth.

### Actual result
![touchpad](https://cloud.githubusercontent.com/assets/8235763/20404181/1de8de54-ad04-11e6-8771-52e823b257a6.gif)
Curser judder

### System information (as much as possible)
Tested on MacOs Sierra, Firefox 50.0, Touchpad. 

### Additional comments
Curser moves smooth in Joomla! 3.6.4 in Firefox 50.0. In Safari 10.0.1 Curser move smooth in Joomla! 3.7.0-dev

**Comment by cpfeifer** [comment]
@franz-wohlkoenig Is this only happening in Weblinks, or in other places as well? If it's only weblinks this PR might be better suited elsewhere since it's been decoupled, but I'm not entirely sure and I'm not seeing this issue anywhere else. Let me know.

**Comment by franz-wohlkoenig** [comment]
@cpfeifer weblinks was Example. Tried in "Article > Tag", "Contacts > Tag" there is a Judder. 

Its not in an Lightbox like "Select Menu Item Type".

**Comment by cpfeifer** [comment]
Thank you for the clarification, I wasn't seeing what you were describing. Are you testing on the most current version? The interface fields and display have been updated and look different from what is seen in your post. I am not experiencing the issue in the tag selection or any other selection in the alpha release. Can you please take another look and let me know. Thank you.

![tag-select](https://cloud.githubusercontent.com/assets/3790835/21460739/beda7960-c908-11e6-9fee-c1bf979855e2.gif)

**Comment by franz-wohlkoenig** [comment]
I'm on Joomla! 3.7.0-alpha1, Firefox 50.1, mac=S Sierra (10.12.2) with this Result:
![judder](https://cloud.githubusercontent.com/assets/8235763/21461706/7b3b992c-c954-11e6-9aca-b305165db0ef.gif)

**Comment by cpfeifer** [comment]
Thanks for clarifying again. It appears to be isolated to Firefox. I'm seeing the issue there and getting this in the console. 

```
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:542
Use of getAttributeNode() is deprecated. Use getAttribute() instead. jquery-migrate.min.js:2:1714

This site appears to use a scroll-linked positioning effect. 
This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects 
for further details and to join the discussion on related tools and features!
```
At least we have some clues to help us solve the issue. I'm sure it's fixable but I'll need to look into the code a bit.

**Comment by franz-wohlkoenig** [comment]
Thanks for Answers Cliff, hope the Issue get solved.

**Comment by cpfeifer** [comment]
@dgt41 - Is this something you can help with?

**Comment by dgt41** [comment]
@cpfeifer you need a CSS expert here, I think

**Comment by cpfeifer** [comment]
@dgt41 There is a jQuery error in Firefox. I'm sure I can figure it out but maybe you know how to fix it faster.

`JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:542
Use of getAttributeNode() is deprecated. Use getAttribute() instead. jquery-migrate.min.js:2:1714

This site appears to use a scroll-linked positioning effect. 
This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects 
for further details and to join the discussion on related tools and features!`

**Comment by dgt41** [comment]
That's from jquery-migrate.js and is not an error it's a notification about deprecated code. Joomla 4 will drop this script

**Comment by cpfeifer** [comment]
Thank you. JS is not my strong point, but I think it's related to the issue at hand. Just wondering if you had any ideas, I don't think it's CSS in this case.

**Comment by dgt41** [comment]
Try the original CSS from chosen. Is scrolling smooth with that CSS? If not open an issue to chosen's repo

**Comment by cpfeifer** [comment]
It's the same with the original CSS, and on their demo page. https://harvesthq.github.io/chosen/

It appears to be a general Firefox issue, they have a lot of docs about janky scrolling with suggestions leading to this doc: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior 

None of the fixes I tried had any effect. I'm not sure what we can do, but it's definitely not an issue with our code.

**Comment by franz-wohlkoenig** [comment]
@cpfeifer As this Issue don't depend on Joomla i close.
