### ISSUE TITLE
Media Manager Maximum Size tool tip has incorrect text in it

### ISSUE THREAD

**Issue by brianpeat** [joomla/joomla-cms#12936]
### Steps to reproduce the issue
Go into the Media Manager, then click upload. Notice that below the Upload File block, there is a bit of text telling you the maximum size in MB.

Now click Options at the top right and on the Component tab, look at the Maximum Size field. That number should match what you saw earlier (for example if you saw 32MB earlier, you should see 32 in this field).

Now hover over Maximum Size to show the tool top. Notice the tool tip says the field is "in bytes" when it really should say "in MB".

### Expected result
The tool tip should say "in MB" not "in bytes" since the field is later referenced in MB not bytes

### Actual result

As a test I pasted in 33554432 which in bytes would be 32MB, but when viewing the upload screen again, it now showed 33554432MB

### Additional comments
I'm not sure if this is in any other language, but I suspect it's in both the US and the GB language files.

**Comment by brianteeman** [comment]
Tested both en-gb and en-us and cannot confirm this. Perhaps you have old language files installed for en-us installed and you haven't updated. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12936">issues.joomla.org/tracker/joomla-cms/12936</a>.</sub>

**Comment by brianpeat** [comment]
YOu're correct, it's fine in the stock install. So we can close this.

Now I just have to figure out why it's NOT fine in most of my sites, even though they show the en-GB as October 2016 and 3.6.4.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12936">issues.joomla.org/tracker/joomla-cms/12936</a>.</sub>
