### ISSUE TITLE
Register to Read More redirects to the Login Menu item redirect if set

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#12945]
### Steps to reproduce the issue
Install a clean staging.
Create an article set to registered with a Read More and set  Show Unauthorised Links to Yes.
Create a menu item to display that article and set Show Unauthorised Links to Yes.
Create a Login Menu item which will display on the same page as the single article menu item.
Add a login redirection to that login menu item to anything else that the single article menu item created above.
Display the article in frontend.
Click on the "Register to Read More..."

### Expected result
After login, it is expected to be redirected to the full article.

### Actual result

One is redirected to the redirection set in the Login Menu item

### Additional comments
This happens on mono as well as multilingual sites.

**Comment by tonypartridge** [comment]
@brianteeman should we close this now it has been merged?

**Comment by infograf768** [comment]
Nothing has been merged concerning this bug.
#12932 addresses a specific multingual login redirect.
This bug here is general, mono or multingual.
Please test for your self.

**Comment by infograf768** [comment]
Please @brianteeman reopen. I get an error on issues.joomla.org when I try to.

**Comment by infograf768** [comment]
Closing as we have a PR thanks to Bakual
https://github.com/joomla/joomla-cms/pull/13089
