### ISSUE TITLE
[RFC] Protected/Unprotected core components

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#12957]
There are several protected core components and several not protected

i have checked the installaiton files and it looks like this:

- com_mailto: Protected
- com_wrapper: Protected
- com_admin: Protected
- com_banners: **Not protected**
- com_cache: Protected
- com_categories: Protected
- com_checkin: Protected
- com_contact: **Not protected**
- com_cpanel: Protected
- com_installer: Protected
- com_languages: Protected
- com_login: Protected
- com_media: Protected
- com_menus: Protected
- com_messages: Protected
- com_modules: Protected
- com_newsfeeds: **Not protected**
- com_plugins: Protected
- com_search: **Not protected**
- com_templates: Protected
- com_content: Protected
- com_config: Protected
- com_redirect: Protected
- com_users: Protected
- com_finder: **Not protected**
- com_joomlaupdate: Protected
- com_tags: Protected
- com_contenthistory: **Not protected**
- com_ajax: Protected
- com_postinstall: Protected
- com_fields: **Not protected**

I think we all understand why some components need to be protected.

But the question is: why can a user disable `com_search` or `com_contact`, but cannot disable `com_redirect` or `com_messages` or even `com_tags`?

**Comment by brianteeman** [comment]
I think the logic was that they are integrated with other components

**Comment by mbabker** [comment]
> But the question is: why can a user disable com_search or com_contact, but cannot disable com_redirect or com_messages or even com_tags?

Anything that's protected can't be disabled (annoyingly).

**Comment by andrepereiradasilva** [comment]
> Anything that's protected can't be disabled (annoyingly).

i know that :wink: 

But why is com_messages or com_redirect protected ?

**Comment by mbabker** [comment]
Grab a time machine, fine the person(s) involved in making those decisions, and ask them.  I doubt you'll find that answer with today's active crew.

**Comment by andrepereiradasilva** [comment]
i will make a PR instead ... :wink:

**Comment by andrepereiradasilva** [comment]
PR https://github.com/joomla/joomla-cms/pull/12961
