### ISSUE TITLE
Smart Search Module - OpenSearch Not Implemented

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#12974]
https://github.com/joomla/joomla-cms/blob/staging/modules/mod_finder/mod_finder.php#L25-L39

OpenSearch support in the Smart Search module isn't fully implemented.  As seen in the code, the entire functionality is commented out.  I remember Rouven purposefully commenting this out in the old Finder Integration repo (deleted long ago), but I don't remember the reason why.  This should either be fully implemented (the corresponding view class is in the component, we did add it trying to model from "legacy" Search's implementation) or removed in full.

**Comment by franz-wohlkoenig** [comment]
> we did add it trying to model (...) or removed in full.

+1

**Comment by rvbgnu** [comment]
@mbabker what is the decision about this?

**Comment by mbabker** [comment]
One hasn't been made yet.  I wish I could remember the reason it was disabled, but it seems like we should be looking to get it enabled.

**Comment by Hackwar** [comment]
Can you assign this issue to me, so that I can tackle this on my list of finder issues, which is getting longer and longer...? :smile:

**Comment by brianteeman** [comment]
@Hackwar we can only assign people who are part of the maintainers team - limitation of github :(

**Comment by Hackwar** [comment]
This is now fixed in #20936
