### ISSUE TITLE
Navigateurs incompatibles avec Joomla 3.6.4

### ISSUE THREAD

**Issue by zaczeksob** [joomla/joomla-cms#12978]
### Steps to reproduce the issue
- website is created with CMS Joomla 3
- upgrade joomla 3.6
- testing with Safari browser 10.0.1
- url for testing : https://bethyeshoua.org
- url for testing : http://www.bethyeshoua.org

### Expected result
every links are ok with this browser safari but many links are broken with others browsers

### Actual result
the testing is with 2 others browsers
if using browser Chrome on MAC OS = BROKEN LINKS

if using browser firefox on MAC OS = BROKEN LINKS

if using browser INTERNET EXPLORER on WINDOWS OS : ALL LINKS ARE OK

1st example on main pages 
https://bethyeshoua.org 
testing  payments with PayPal Plugin
IS working on Safari
IS working on IE
IS NOT WORKING on Chrome 
IS NOT WORKING on FIREFOX

2nd example for subscribe : 
http://bethyeshoua.org/index.php?option=com_formmaker&view=formmaker&id=12&Itemid=1244
IS working on Safari
IS working on IE
IS NOT WORKING on Chrome 
IS NOT WORKING on FIREFOX

### System information (as much as possible)
Mac OS Sierra 10.12.1
Process 2,9 GHz Intel Core I7
RAM 16 Go  1600 MHZ DDR3

### Additional comments
subscribed members can't use all this website because incompatibility between joomla 3.6 and Browsers Chrome, Firefox aso.

**Comment by mbabker** [comment]
You've got CSS issues on the site.  When I correct them in my Chrome dev console your links work fine.

If you need assistance troubleshooting your issues, please use https://forum.joomla.org for support.

Closing as not a core bug.
