### ISSUE TITLE
the module edit  button  overlap  the flag of languages

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#12998]
### Steps to reproduce the issue
Login in frontend (like a superuser) in a multilingual site 

try to click on the en-GB flag (or to the leftmost flag) to switch language

### Expected result
you are able to switch to all available languages

### Actual result

![module_edit_button](https://cloud.githubusercontent.com/assets/181681/20589636/fcfe8ea4-b21d-11e6-884b-f06c4863588e.png)

you are not able to switch to en-GB in this case

### System information (as much as possible)
Latest staging multilingual

**Comment by infograf768** [comment]
Confirmed. That's why I always disable frontend module edit....

**Comment by brianteeman** [comment]
There really is nothing that can be done about this in the current design. It only effects Super Admins<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12998">issues.joomla.org/tracker/joomla-cms/12998</a>.</sub>

**Comment by alikon** [comment]
closing  as we have a PR  

> always disable frontend module edit..

**Comment by brianteeman** [comment]
Where is the pr?

**Comment by alikon** [comment]
I mean we have a workaround.....
