### ISSUE TITLE
joomla 3.6.4 dropdown-menu problems

### ISSUE THREAD

**Issue by LelaIt** [joomla/joomla-cms#13007]
### Steps to reproduce the issue
Hello, i've got a dropdown-menu problems since started ribilding the site in last a joomla 3.6.4 version.
By activating the "show sub-menu Items' option at the module level, submenus always stay expanded - meanwhile they should be closed and should expand only with the mouse-over or click, then close again when navigate to another page.
Do anyone can help please?
THanks!

### Expected result
submenus should stay closed and should expand only with the mouse-over or click, then close again when navigate to another page.

### Actual result
submenus always stay expanded 

### System information (as much as possible)
joomla 3.6.4, protostar, linux hosting

**Comment by brianteeman** [comment]
Hi Please use the forum for support https://forum.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13007">issues.joomla.org/tracker/joomla-cms/13007</a>.</sub>
