### ISSUE TITLE
foreach warning on search query using sql server

### ISSUE THREAD

**Issue by sweco-semhul** [joomla/joomla-cms#13002]
### Steps to reproduce the issue
Setup Joomla against SQL Server
Update search index
Make a search on the website

### Expected result
No warning

### Actual result
Warning: Invalid argument supplied for foreach() in ...\libraries\joomla\database\query\sqlsrv.php on line 394

### System information (as much as possible)
Tested on latest Joomla in staging branch, commit 81142af
Windows Server 2012 R2
SQL Server 2008 R2
IIS 8.5

**Comment by brianteeman** [comment]
There is no version of Joomla called **Latest** - please confirm the **exact** version

Sorry if this seems pedantic or irrelevant but from experience users often report they are suing the latest version when they are not and this can waste a lot of time for everyone

**Comment by sweco-semhul** [comment]
Sorry updated it and added the exact commit Im running

**Comment by alikon** [comment]
can be closed as we have  a PR  to test #13003

**Comment by brianteeman** [comment]
Closed as requested
