### ISSUE TITLE
Cannot save or change anything

### ISSUE THREAD

**Issue by info-skonline** [joomla/joomla-cms#13001]
I can't save or change anything on my website. Articles, users, templates, menu's nothing!
I'm the administrator and there are no other users.
I've never had this issue before.
I've checked if I have all the rights and that seems to be in order, but even if I don't change anything none of the 'save buttons' work. I don't know what I did wrong or if it's some bug from the installation.

**Comment by brianteeman** [comment]
Please use the forum for support. https://forum.joomla.org
