### ISSUE TITLE
Deleting links from smart search returns an error when using SQL Server

### ISSUE THREAD

**Issue by sweco-semhul** [joomla/joomla-cms#13005]
### Steps to reproduce the issue
Setup Joomla against SQL Server
Go to "smart search"
Reindex
Select any link in the list and click Delete

### Expected result
Link deleted and system happy

### Actual result
Error:
 156 [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near the keyword 'AS'. SQL=UPDATE t SET t.links = t.links - 1 from #__finder_terms AS t INNER JOIN #__finder_links_terms0 AS AS m ON m.term_id = t.term_id WHERE m.link_id = '34'

### System information (as much as possible)
Tested on latest Joomla in staging branch, commit 81142af
Windows Server 2012 R2
SQL Server 2008 R2
IIS 8.5

**Comment by brianteeman** [comment]
Closed as we have a pr for testing #13006
