### ISSUE TITLE
Corrupt main menu

### ISSUE THREAD

**Issue by avandalen** [joomla/joomla-cms#13012]
### Steps to reproduce the issue
The main menu become corrupted since version 3.6.4, and probably after changing the order of submenu items.
### Expected result
See the website in the Arduino main menu [http://www.avdweb.nl/
](http://www.avdweb.nl/ "http://www.avdweb.nl/")
### Actual result
Suddenly there arised double submenu items in the arduino main menu , thus the old correct submenu item in submenus, and the double spooky submenu items in the parent menus.
In the administrator menu editor:
1 selecting and editting the old submenu item in the submenu is ok
2 selecting the double submenu item in the mainmenu result in the error
0 Error decoding JSON data: Syntax error
### System information (as much as possible)
PHP Built On	Linux linux91.webawere.nl 2.6.32-673.8.1.lve1.4.3.1.el6.x86_64 #1 SMP Thu May 5 16:06:47 EDT 2016 x86_64
Database Version	5.6.29
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.3.29
Web Server	Apache/2
WebServer to PHP Interface	litespeed
Joomla! Version	Joomla! 3.6.4 Stable [ Noether ] 21-October-2016 16:33 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36

**Comment by brianteeman** [comment]
Hi

Please use the forum https://forum.joomla.org for support on your issue. If you search for the error message you will find the answer.
