### ISSUE TITLE
User registration error

### ISSUE THREAD

**Issue by Sschaeffer99** [joomla/joomla-cms#13014]
### Steps to reproduce the issue
open http://www.schuetzenverein-thierhaupten.de
Go to "Login" and "Registrieren"
Type in your choosen login-data, check recaptcha and submit

### Expected result
New User should be created and Login should be possible

### Actual result
following (german) error-message appears:
"Die Anfrage wurde zurückgewiesen, da der Sicherheitstoken ungültig ist"
Also in the backend, it is not possible to create a new user.

Maybe, as a further result of this issue, it is not possible to create any new event in JEvents

### System information (as much as possible)
Joomla 3.6.4
Template JoomlaShine, Solid PRO STANDARD v2.1.0 
JEvents, latest version

### Additional comments
Error occured first after updating from Joomla 3.6.2 to 3.6.4

**Comment by jolliemar** [comment]
Perhaps, you can check on these. They are related tickets.

[Invalid security token after update from joomla 3.4.8 to joomla 3.5 #9568](https://github.com/joomla/joomla-cms/issues/9568)

[Clear Cache on Update #9626](https://github.com/joomla/joomla-cms/issues/9626)

**Comment by Sschaeffer99** [comment]
Thanks for your reply.
I checked theese tickets, but it doesn't work.
Cache is deactivated at site-configuration and also the plugin system-cache is deactivated - but still the message "invalid security token" appears.
This happens only at new registration of a new user, Login of existing users works fine.

**Comment by zero-24** [comment]
@Sschaeffer99 please move this issue to a Joomla Forum. It is no issue with the core system but maybe with your setup. As you come from germany you can take a look here: https://forum.joomla.de/ for support. I'm closing here now.
