### ISSUE TITLE
Cache problems in backend -  can't open articles

### ISSUE THREAD

**Issue by deltapapa01** [joomla/joomla-cms#13016]
### Steps to reproduce the issue
Only in Backend:
Open an article- > Save -> Open again with click on the article headline -> i get an error messages
Only way to open: Click the Checkbox from the article and click Edit or
logout from backend and login again (but it works not every time)
I get the same problem when i edit the template styles.
I have 20 J! Sites on the same Server, 18 works fine and two have the issue.

When i disable the browser cache in the browser (via DevTools), it works fine without any prob.
I have the issue from 3.5.1, i wait the long time in hope that the next release fix the bug.
I have a screencast from the bug: https://www.petersen-webdesign.de/blog/37-screencast-test

We talk in the german FB group, and i get the feedback that other people have the same error. Not ervery time but sporadic

### System information (as much as possible)
 J!3.6.4
 OS Linux
 PHP 7.0.13
 MySQLi 5.5.53
 Cache Deaktiviert
 Gzip Aktiviert

 Browser: FF 50 and Chrome 54

**Comment by brianteeman** [comment]
please check and ensure they are using the default joomla htaccess file

**Comment by deltapapa01** [comment]
Hi Brian, thank you, inside the the htaccess was the prob. I change it with the core htaccess and every thing works great.I will also check, maybe i have make only in these two sites changes to the htaccess to make this happend.
Thank you very much, for me it is solved :-)
