### ISSUE TITLE
Installer Plugins Not Found Post Update

### ISSUE THREAD

**Issue by mackenj** [joomla/joomla-cms#13017]
### Steps to reproduce the issue
After updating Joomla, I received the following error message

JInstaller: :Install: Error SQL Duplicate entry '453' for key 'PRIMARY' SQL=INSERT INTO `#__extensions` (`extension_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `custom_data`, `system_data`, `checked_out`, `checked_out_time`, `ordering`, `state`) VALUES (453, 'plg_editors-xtd_module', 'plugin', 'module', 'editors-xtd', 0, 1, 1, 0, '', '', '', '', 0, '0000-00-00 00:00:00', 0, 0);
Files Update: SQL error file DB function failed with error number 1062
Duplicate entry '453' for key 'PRIMARY' SQL=INSERT INTO `#__extensions` (`extension_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `custom_data`, `system_data`, `checked_out`, `checked_out_time`, `ordering`, `state`) VALUES (453, 'plg_editors-xtd_module', 'plugin', 'module', 'editors-xtd', 0, 1, 1, 0, '', '', '', '', 0, '0000-00-00 00:00:00', 0, 0);
SQL =

INSERT INTO `#__extensions` (`extension_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `custom_data`, `system_data`, `checked_out`, `checked_out_time`, `ordering`, `state`) VALUES
(453, 'plg_editors-xtd_module', 'plugin', 'module', 'editors-xtd', 0, 1, 1, 0, '', '', '', '', 0, '0000-00-00 00:00:00', 0, 0);

The installer plugins are now not showing up (only Installer - Install from Web shows up as a plugin)

### Expected result

Please advise how to fix

**Comment by zero-24** [comment]
Please use the forum for support https://forum.joomla.org

Please include the SQL Dump for the #__extensions table in your report there so they can check the extension that blocks the ID 453 ;)

For the installer plugins please check the `Fix database` button in the backend.
