### ISSUE TITLE
How to reinstall tag again for a clean and up-to-date installation ?

### ISSUE THREAD

**Issue by ZerooCool** [joomla/joomla-cms#13020]
### Steps to reproduce the issue
When I save an article with a tag, it does not register, with an error.

### Expected result
Save the article with a tag.

### Actual result
Error
The record failed with the following error:
(But nothing more, and, I have little / no log.)

### System information (as much as possible)
php 5.6
Last stable version of Joomla.

### Additional comments
How to reinstall tag again for a clean and up-to-date installation

**Comment by brianteeman** [comment]
Please use the forum for support https://forum.joomla.org
