### ISSUE TITLE
[4.0] SQL error when saving modules

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#13031]
### Steps to reproduce the issue

Edit a module and try to save it

### Expected result

Module saved

### Actual result

![image](https://cloud.githubusercontent.com/assets/9630530/20640604/9f9d61cc-b3da-11e6-8fc2-bbe1c27508dd.png)

### System information (as much as possible)

latest 4.0

### Additional comments

Probably related to more strict sql_mode since it seems we are trying to save a datetime field with `''`

https://github.com/joomla/joomla-cms/pull/12494

**Comment by tonypartridge** [comment]
Replicated too, from what I can gather on saving in J3 we insert 00:00:00 00:00:00 or along them lines, where's in J4 we are not doing this and thus the save fails.

**Comment by wilsonge** [comment]
Fixed with https://github.com/joomla/joomla-cms/pull/14073
