### ISSUE TITLE
Hidden menu item to connect broken links in search engines to the new link/menu-item

### ISSUE THREAD

**Issue by GerardBol** [joomla/joomla-cms#13044]
### Steps to reproduce the issue
I changed different menu aliasses to a new nicer alias but the searchengines still have the old one.

i want to put in menu-item with the old alias but dont want them to be seen in the menu on the website.
so i want functional hidden menu-item that will be link thru the menu-item alias option to the new menu alias.

**Comment by brianteeman** [comment]
There are many ways to do this. Hidden menus. The redirect component. Updating Google. 

This is not the place to find support. Please use the forum https://forum.joomla.org
