### ISSUE TITLE
Website admin panel doesn't work after trying to upload a new version of Joomla

### ISSUE THREAD

**Issue by JaneZhilina** [joomla/joomla-cms#13055]
### Steps to reproduce the issue
Installed Joomla template
Started building the website atmdance.ru
Couldn't install the needed language to change the text in the website template
Saw, that Joomla needed an upgrade to Joomla 3.6
Clicked to upgrade
Waited for 5 minutes but there was no progress in downloading a new version of Joomla
Closed the window atmdance.ru/administrator

### Expected result
Expected to enter the control panel atmdance.ru/administrator

### Actual result
The control panel of Joomla doesn't open. URL atmdance.ru/administrator shows HTTP ERROR 500

### System information (as much as possible)
Template S5
URL atmdance.ru
Browser Chrome
![tq8lykeyfdo](https://cloud.githubusercontent.com/assets/24311592/20826471/32a7f496-b87c-11e6-9a6e-835d10e7c56e.jpg)

**Comment by tonypartridge** [comment]
This isn't a fault with a Joomla! It's likely down to your hosting depending what version you were upgrading from.

In future for these please submit a forum support request. 8' the interim check what version of php you are on and also enable maximum error reporting in the Joomla! Configuration.php. Also check out the error_log files.

Many thanks
Tony

**Comment by zero-24** [comment]
Closing. Please use the forum at https://forum.joomla.org
