### ISSUE TITLE
com_config does not facilitate help system usage for component authors

### ISSUE THREAD

**Issue by ron4mac** [joomla/joomla-cms#13059]
### Steps to reproduce the issue
Select a non-core component that has configuration provided by config.xml
Choose 'Options' from the toolbar.
Choose 'Help' from the toolbar.

### Expected result
Component is able to provide help via a link provided by a combination of parameters in config.xml and language file(s)

### Actual result
RuntimeException
Error fetching page from MediaWiki API: The page you specified doesn't exist

### System information (as much as possible)
Joomla! 3.6.4 Stable [ Noether ] 21-October-2016 16:33 GMT

**Comment by PhilETaylor** [comment]
Confirmed.

E.g. Install @nikosdion Akeeba Backup using Isntall from web

Go to /administrator/index.php?option=com_config&view=component&component=com_akeeba

Click Help

Get a popup with url of

https://help.joomla.org/proxy/index.php?keyref=Help37:JHELP_COMPONENTS_com_akeeba_OPTIONS

which is a 404 error page really as the help site has no data for 3rd party extensions.

Ideally extensions xml could have helpUrl published in their xml that could be used, or the help button removed if none available.

**Comment by Bakual** [comment]
As far as I know it is possible for 3rd parties to provide such a help URL (using language strings if I remember right). But it is not that straight forward. I think @chrisdavenport knows more about that system.

**Comment by mbabker** [comment]
See also https://github.com/joomla/joomla-cms/issues/6627 and referenced items.

**Comment by chrisdavenport** [comment]
In particular, see https://docs.joomla.org/Help_system/Adding_a_help_button_to_the_toolbar

If that mechanism has stopped working, then it's a bug.  Otherwise, it's not.

**Comment by PhilETaylor** [comment]
I wish people would actually read issues before responding. 

**This is NOT about adding a help button within someone's extension, in their own toolbar**

This is about the help button that is rendered on the com_config view, this is a core view

E.g. URL /administrator/index.php?option=com_config&view=component&component=com_akeeba

Therefore the information on the page  https://docs.joomla.org/Help_system/Adding_a_help_button_to_the_toolbar is 100% NOT RELAVANT here. 

Even with https://github.com/joomla/joomla-cms/issues/6627#issuecomment-88971362 I dont see why the help popuop should be proxied through help.joomla.org for custom extensions.

**Comment by PhilETaylor** [comment]
#6627 solved nothing, but still accurately describes the problem.

If I develop a com_whatever, which has a configuration screen powered by com_config, then currently all I can do is append  text to this url:

https://help.joomla.org/proxy/index.php?keyref=Help37:

by setting my JHELP_COMPONENTS_COM_WHATEVER_OPTIONS string in my language file.

I cannot make that help button link direct to https://whatever.com/help

**Comment by PhilETaylor** [comment]
#6639 attempted to fix this - but was closed as it broke all core links apparently.

**Comment by chrisdavenport** [comment]
As I said, if that mechanism isn't working, then it's a bug.

**Comment by mbabker** [comment]
Chris, that process works fine everywhere BUT com_config for a component's config, for non core extensions.  That's what the old issue and PR tried to address and it's still not fixed.

**Comment by chrisdavenport** [comment]
I have some holiday time coming up so I'll take a look at it then.  Unless someone can get to it faster than me.

**Comment by ron4mac** [comment]
I think using a helpUrl element in the xml is the way to go. However, if there is no helpUrl element and the translation string is present, a link to local help file(s) should be provided. If there is no translation string at all ... no help button.

I may have some time to see if I can come up with an acceptable implementation.

**Comment by ron4mac** [comment]
Excuse any less-than squeaky clean logic or coding, but this is what seems to work okay for my needs:

In config.xml
`<config helpURL="http://myserver.net/joomladev/mycomponent">`
or
`<config helpURL="local">`

Adjust _addToolBar_ in com_config/view/component/html.php
```
$helpUrl = (string) $this->form->getXML()->config['helpURL'];
$local = ($helpUrl==='local');
JToolbarHelper::help('JHELP_COMPONENTS_' . $this->currentComponent . '_OPTIONS', $local, ($local?null:$helpUrl), $this->currentComponent);

```

**Comment by Bakual** [comment]
I guess it just has to check for a component specific string in com_config. That's likely the only issue.

**Comment by mbabker** [comment]
#13286 is the PR for this item.
