### ISSUE TITLE
class naming in com_fields when adding a new field

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#13051]
### Steps to reproduce the issue

Create a new custom field see:

<img width="190" alt="screenshot 2016-12-01 00 18 31" src="https://cloud.githubusercontent.com/assets/1400982/20776983/dc1dfc7c-b75b-11e6-8696-0c54738a73e9.png">

Seeing the 'Class' label I would naturally assume it applies to the class everywhere, it is only used in the edit form. 

I suggest changing it from:

Class

to:

Class in edit form

**Comment by brianteeman** [comment]
Isnt Render class for the display of the field?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13051">issues.joomla.org/tracker/joomla-cms/13051</a>.</sub>

**Comment by tonypartridge** [comment]
To me the render class is the classes applied to the rendered containers. A class naming to me atleast means applying it to the input / field itself.

**Comment by laoneo** [comment]
I would rename it to form class- You need to have a class attribute you can apply on the form as well, length for example to define the textfield.

**Comment by tonypartridge** [comment]
@laoneo but the 'Class' attribute only applies to the input class on a text field for example.

**Comment by laoneo** [comment]
Didn't saw your latest sentence on the issue description. Guess we all agree here on a better label. "Class in edit form" is IMO a bit long. But I leave it up to the en-GB team to come up with a better name :wink:.

**Comment by brianteeman** [comment]
Remind me this weekend

**Comment by brianteeman** [comment]
Closed - please see #13068<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13051">issues.joomla.org/tracker/joomla-cms/13051</a>.</sub>
