### ISSUE TITLE
content emailcloak plugin did not cloak umlaut email addresses. SPAM risk!

### ISSUE THREAD

**Issue by Didldu-Florian** [joomla/joomla-cms#13065]
### Steps to reproduce the issue
add an umlaut e-mail adress like "info@umlaut-äöü.net" to any frontend contect

### Expected result
should be outputed in html as javascript protected email

### Actual result
Not protected! E-Mail in cleartext. SPAM risk

### System information (as much as possible)
PHP Built On 	Linux h2138315.stratoserver.net 3.14.79-9.1.x86_64 SMP PREEMPT Mon Oct 24 19:21:31 CEST 2016 x86_64
Database Version 	5.5.50-MariaDB
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.3.29
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.6.4 Stable [ Noether ] 21-October-2016 16:33 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0 

### Additional comments
SPAM risk! SPAM risk! SPAM risk!

**Comment by brianteeman** [comment]
Is that a valid domain?

**Comment by Didldu-Florian** [comment]
No, but umlaut domains and emails are now common. 
Have seen the problem today for the first time live.
Might affect several websites, especially in countries like germany!

**Comment by ot2sen** [comment]
Interesting if the cloaking do not currently support IDNs, we probably
should look into extending the cloaking to the allowed non-ASCII characters
that are legit in International domain names.

This describe which characters are valid:
https://eurid.eu/en/register-a-eu-domain/domain-names-with-special-characters-idns/
and in more details in the linked pdf:
https://eurid.eu/media/filer_public/8d/18/8d18473b-ed9b-4fba-abe7-947d235f25b1/idna2008and_homoglyph_bundling_tables.pdf

**Comment by ggppdk** [comment]
At least the line that matches the emails is easy to find:
https://github.com/joomla/joomla-cms/blob/staging/plugins/content/emailcloak/emailcloak.php#L119

**Comment by brianteeman** [comment]
Umlaut in a domain name are done with punycode so presumably all punycode
domains face this issue

**Comment by infograf768** [comment]
Tested here in article and a contact an idn mail: it is automatically saved punycode encoded in the db and mailcloak does work on it.

Example for contact

![screen shot 2016-12-03 at 08 49 18](https://cloud.githubusercontent.com/assets/869724/20857741/79bf17ba-b935-11e6-9983-30a7433881a9.png)

Frontend display
![screen shot 2016-12-03 at 08 51 07](https://cloud.githubusercontent.com/assets/869724/20857752/b13f03da-b935-11e6-9a6b-9d61d7e8a2f5.png)

Source when displayed in frontend

```html
<span class="contact-emailto">
			<span id="cloakd2c3a3e11b6dc35e6ae677ac02779bb6">This email address is being protected from spambots. You need JavaScript enabled to view it.</span><script type='text/javascript'>
				document.getElementById('cloakd2c3a3e11b6dc35e6ae677ac02779bb6').innerHTML = '';
				var prefix = '&#109;a' + 'i&#108;' + '&#116;o';
				var path = 'hr' + 'ef' + '=';
				var addyd2c3a3e11b6dc35e6ae677ac02779bb6 = 'j&#111;&#111;ml&#97;t&#101;st' + '&#64;';
				addyd2c3a3e11b6dc35e6ae677ac02779bb6 = addyd2c3a3e11b6dc35e6ae677ac02779bb6 + 'xn----7sblgc4&#97;g8bhcd' + '&#46;' + 'xn--p1&#97;&#105;';
				var addy_textd2c3a3e11b6dc35e6ae677ac02779bb6 = 'j&#111;&#111;ml&#97;t&#101;st' + '&#64;' + 'джумла-тест' + '&#46;' + 'рф';document.getElementById('cloakd2c3a3e11b6dc35e6ae677ac02779bb6').innerHTML += '<a ' + path + '\'' + prefix + ':' + addyd2c3a3e11b6dc35e6ae677ac02779bb6 + '\'>'+addy_textd2c3a3e11b6dc35e6ae677ac02779bb6+'<\/a>';
		</script>		</span>
```

**Comment by infograf768** [comment]
Evidently, if a 3rd party extension does not save a mail punyencoded, it will not work.
One has to use (example here for contacts):
`// Store utf8 email as punycode`
`$this->email_to = JStringPunycode::emailToPunycode($this->email_to);`

**Comment by brianteeman** [comment]
@infograf768 so are you saying this is not an issue with the core?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13065">issues.joomla.org/tracker/joomla-cms/13065</a>.</sub>

**Comment by Didldu-Florian** [comment]
@infograf768 the problem is as described with umlaut emails like (ä,ö,ü) characters and not with alphanumeric cyrillic characters!

**Comment by brianteeman** [comment]
Floran- the point is that to have an umlaut in your domain name then it is
an IDN domain name (punycode) exactly as a cyrillic domain is

**Comment by Didldu-Florian** [comment]
That´s trure, but umlauts are currently not protected.

**Comment by brianteeman** [comment]
they are if it is stored as punycode.
the punycode (idna) for Häusler.de is xn--husler-bua.de

See the screenshot showing a mailto link created in com_content just using mail@Häusler.de as an example and the generated output. You can see it is working

![ay3s 1](https://cloud.githubusercontent.com/assets/1296369/20858402/a983561e-b944-11e6-8616-ac5776ad0d03.png)

**Comment by Didldu-Florian** [comment]
That's interessting, good to know.
Then the problem exists just with text in Article like "embedded e-mail in content", such as imprint, etc..

**Comment by infograf768** [comment]
umlauts are as any utf8 characters and are treated indeed the same way as cyrillic.

> Then the problem exists just with text in Article like "embedded e-mail in content", such as imprint, etc..

In an article it works the same as for contacts. If the imprint is proposed as a custom module, it should also work the same.

**Comment by infograf768** [comment]
I guess this can be closed.

**Comment by Didldu-Florian** [comment]
Try to input this:
![test](https://cloud.githubusercontent.com/assets/12803406/20858552/497bb0f6-b947-11e6-9fca-61b366b16abe.jpg)

**Comment by brianteeman** [comment]
That doesnt show me anything. The only thing that matters is how this is displayed on the front end.

**Comment by Didldu-Florian** [comment]
This is frontend
![frontend](https://cloud.githubusercontent.com/assets/12803406/20858619/71e49614-b949-11e6-9542-83434cbffa7e.jpg)

**Comment by infograf768** [comment]
A mail entered in text (without a mailto:) will not indeed pass through JStringPunycode::emailToPunycode() and thus idn will not get mailcloaked.

**Comment by Didldu-Florian** [comment]
![plugin](https://cloud.githubusercontent.com/assets/12803406/20858704/b56228b4-b94b-11e6-9a1a-ecd1e95d38bc.jpg)

**Comment by infograf768** [comment]
yes, as I said, a non IDN mail entered like this will be mailcloaked, but NOT an idn mail.
One could consider this as a bug. Not sure how to solve.

**Comment by infograf768** [comment]
Code is here:
https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/component/helper.php#L124-L135
and
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/filter/input.php#L454-L477

**Comment by infograf768** [comment]
Closing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13065">issues.joomla.org/tracker/joomla-cms/13065</a>.</sub>
