### ISSUE TITLE
After update from 3.4 to 3.6

### ISSUE THREAD

**Issue by AFEH2016** [joomla/joomla-cms#13063]
Hello,

After i updated Joomla from 3.4 -> 3.6.4 my homepage doesn't work anymore.

If i want to reach www.alp-fliesen.de there appers an error.

Please help me because my Homepage is down since yesterday i don't know what to do :astonished: 

An other thing: When i want to edit my main article i can't press on the button "Save" or "Save and new" or other things. I can only press "close" & "versions" :angry:

**Comment by ggppdk** [comment]
Login to backend (if you can) and in Joomla global configuration
- enable Debug option
- set error reporting to "Maximum"

visit home page, and error message(s) will (probably) appear in frontend,

Then (since this issue tracker is not meant for providing support)
use the error message to **first search** and then post here:
https://forum.joomla.org/

**Comment by AFEH2016** [comment]
thank you very much 
just found the debug thing and enabled (system & language) debug

where to find the error reporting thing?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13063">issues.joomla.org/tracker/joomla-cms/13063</a>.</sub>

**Comment by AFEH2016** [comment]
thank you very much
just found the debug thing and enabled (system & language) debug

where to find the error reporting thing?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13063">issues.joomla.org/tracker/joomla-cms/13063</a>.</sub>

**Comment by zero-24** [comment]
Hi this is a tracker for bugs in the core code not for site individual problems. Please use the forum at https://forum.joomla.org or https://forum.joomla.de with all needed infos thanks
