### ISSUE TITLE
[com_fields] type "checkboxes" wrong behavior with value "0"

### ISSUE THREAD

**Issue by beni71** [joomla/joomla-cms#13078]
I noticed two mistakes:

1. The Select modal view of the type "checkboxes" shows near to the top right corner a green (-). But when you click on this, then a new selector is adding. In my opinion this must better be a green plus (+):
![checkboxes-minus](https://cloud.githubusercontent.com/assets/8353850/20865041/fd7f8d74-ba06-11e6-8d0b-71f7d2cf1777.PNG)

2. On a field type "checkboxes", when you have a value = 0, then this checkbox can never be choosen. See the following steps to reproduce this bug:

### Steps to reproduce the issue

1. Install joomla from staging fresh, with some example articles (on the installer, have choosen the last option).
2. Login as administrator (on the back end)
3. Navigate to Content > Fields
4. Click New.
5. Choose type "checkboxes"
6. Set the title to (for example): Hardness
6. Click on select (last field) and add the following three selectors (or options):
    Text, Value
    Easy, 0
    Medium, 1
    Powerful,2
7. Save the created selectors and save the field.
8. Opens an article and navigate to the tab fields
9. You can see now three checkboxes.
10. Click/set/check into the first checkbox.
11. Save the article.

### Expected result
The checkbox should be set.

### Actual result
The checkbox is always empty/unset.

### System information (as much as possible)
Source code synchronized from staging branch
OS Windows
PHP 7.0.13
MySQLi 5.5.5-10.1.19-MariaDB

### Additional comments
From my point of view, the value "0" may be the problem. The other checkboxes in the described example work correctly.

**Comment by ggppdk** [comment]
Same thing for radio and and list
for checkboxes it happens when you select only 1 value (the value with zero)

There is already a PR:
https://github.com/joomla/joomla-cms/pull/12807
go ahead and test it

**Comment by beni71** [comment]
Uh, first sorry, i forgot to search in the pull request list... but...

@ggppdk: I have now tested both "mistakes" based on the code of PR #12807. You are right, the behavior is exactly as you described. And you already has commented this. Thank you for your help. The other thing with the green minus (-) still exists.

**Comment by Bakual** [comment]
See https://github.com/joomla/joomla-cms/pull/12886 for the fix for this issue here.

**Comment by laoneo** [comment]
@beni71 can you please test if the fix in #12886 is solving the issue. If yes, then please set it as test success. Thanks.
