### ISSUE TITLE
Upgrade to 3.6.4 from 3.6.2 Glitches

### ISSUE THREAD

**Issue by advancn** [joomla/joomla-cms#13076]
1) My install plugins are enabled.  
I am not able to see installation plugins. I have tried the cache clear, it does not work.
Nor can I use the search tool button for modules. 

2) After transferring to AWS cloud from godaddy, I also have K2 and HikaShop glitches on the front and back end. Any suggestions would be appreciated. 

Thanks
![image](https://cloud.githubusercontent.com/assets/9293817/20862748/07bcd94c-b979-11e6-8c71-bfb53083a39d.png)

### Steps to reproduce the issue
1) Selected update site.
2) transferred files using binery, site is fine expect the  raw data field on the front end and admin panel. 

### Expected result
1) I would like to be  able to upload comps and filter/search through comps
2) I would like to have the rawfield not display on the front end.

### System information (as much as possible)
Hosting on  Ubuntu Linux 14.04.3 LTS (rev. 51, hvm) AWS EC2 Server
Upgrade from 3.6.2 to 3.6.4

**Comment by brianteeman** [comment]
Please use the forum for support https://forum.joomla.org
