### ISSUE TITLE
TOKEN RESET PASSWORD TABLE

### ISSUE THREAD

**Issue by cryptoky** [joomla/joomla-cms#13084]
Hello, what is the table of token to reset password saved? and how it is generated the token?

**Comment by brianteeman** [comment]
This is the tracker for managing bug fixes and new features

Your question would be better on either the forum https://forum.joomla.org or the mailing list https://groups.google.com/forum/#!forum/joomla-dev-general<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13084">issues.joomla.org/tracker/joomla-cms/13084</a>.</sub>

**Comment by cryptoky** [comment]
fuck off
