### ISSUE TITLE
[com_fields] Postgres install/update scripts missing for field groups

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-cms#13088]
This line is missing in the Postgres installer script
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/sql/updates/mysql/3.7.0-2016-11-16.sql#L28

The Postgres field_groups table install code is missing completely.

I was just about to write the comment before #13019 got merged.

**Comment by Bakual** [comment]
We also still need to do the SQLAzure stuff.

I was also wondering if we should do all the fields stuff in one update file instead of the two (or more) we have now. Since it's not released yet it probably would make more sense.

**Comment by Bakual** [comment]
See https://github.com/joomla/joomla-cms/issues/13091

Closing as we have a PR.
