### ISSUE TITLE
Show non-updatable extensions in updates list

### ISSUE THREAD

**Issue by Spudley** [joomla/joomla-cms#13095]
This is more of a feature suggestion than an issue. I hope it will be considered.

As a administrator of a Joomla site, I would like the extension updates list to also show me a list of third-party extensions that do not have update notifications, so that I can be reminded to manually check their sites for new releases.

### Steps to reproduce the issue

In Joomla admin panel, go to Extensions -> Manage -> Update. Or click the "View Updates" button on the control panel where it says "X Extension Update(s) are available"

### Expected result

In addition to the current list of extensions that have update servers and are shown here if an update is available, I would also like to see a list of all the third-party extensions that do not have an update server.

### Actual result

At the moment, only the extensions with update servers that have an update available are listed.

### System information (as much as possible)

This applies to the latest Joomla release (3.6.4).

### Additional comments

I am raising this ticket because one of my system owners has expressed frustration at not having any visibility about version updates for several of his extensions.

In an ideal world, of course, all extensions would provide update information to Joomla. But a lot of extensions do not, and in the absence of this, it would be really helpful if Joomla could provide a list of these extensions. This will at least give the site administrator a clear visual reminder at a regular interval of what needs to be checked.

This list doesn't have to be shown on the extension updates page, but it seems like a logical place to put it to me, as the administrator will be thinking explicitly about updates when he goes there, so it will be a timely reminder.

As things stand, it is very easy to neglect doing updates on these extensions. And even if you are keeping an eye on it, it's easy to simply to forget about one of them, which in turn opens up the possibility of security holes on one's site even though you think you're fully up-to-date.

**Comment by PhilETaylor** [comment]
This complements https://extensions.joomla.org/blog/item/a-reminder

**Comment by Bakual** [comment]
The amount of extensions using the Joomla Update system should raise with the JED requirement for new listings. So over the time the need hopefully goes down.

I wouldn't show them on the regular "update available" list by default. That would become confusing.
But maybe a filter somewhere (either manage or update view) makes sense. So it is available if needed.

**Comment by mbabker** [comment]
TBH, the code to support this would have a lot of core specific hacks.  The only of core's extensions providing an update channel are the files extension to update Joomla itself and the language package, so all the components/modules/plugins/templates would show on that list without said hacking.

**Comment by Bakual** [comment]
Or you would have to add all core extensions to the updateserver mapping table. But that's not ideal either.

**Comment by brianteeman** [comment]
I am going to close this one. Seems a nice idea to have but as @mbabker its not going to work without a 'lot of core specific hacks'

**Comment by Spudley** [comment]
That's okay. Thanks for considering it.

To be fair, with the changes to JED that now requires update notifications, this should become less of an issue.
