### ISSUE TITLE
Can't restrict browsing folders in media manager

### ISSUE THREAD

**Issue by alex7r** [joomla/joomla-cms#13104]
### Steps to reproduce the issue
Set up media manager field with .xml like 
```XML 
<field name="myimage" type="media" directory="stories" />
```

### Expected result
I wont to allow users that manipulates this form to be able to see only the `stories` folder.

### Actual result
User can navigate between folders with no issue.

### Additional comments
I would be great to have something like 
```XML
<field name="myimage" type="media" directory="stories" restrict_browsing="true"/>
```

**Comment by brianteeman** [comment]
This is not possible with the current media manager. A team is working on a new media manager and this type of ACL is part of their roadmap https://github.com/joomla-projects/media-manager-improvement/wiki

**Comment by dgt41** [comment]
> This is not possible with the current media manager

@brianteeman I think you got @alex7r wrong here. He's asking for a folder lock-in (similar to jce) not external access to media folder. Also I think this is possible with the current codebase
