### ISSUE TITLE
Smart Search Indexes Categories for Disabled Components

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#13118]
### Steps to reproduce the issue

Enable Smart Search, disable com_banners, index the site content

### Expected result

No categories from com_banners should be indexed; the component is disabled so all of its content shouldn't be accessible

### Actual result

The component's categories are indexed

### System information (as much as possible)

Validated on 3.6.4

### Additional comments

N/A

**Comment by brianteeman** [comment]
Closed as we  have a pr for testing see #13125
