### ISSUE TITLE
Global Configuration inaccessible

### ISSUE THREAD

**Issue by jordan-chang** [joomla/joomla-cms#13110]
### Steps to reproduce the issue
Login to the admin page and tried to navigate to Global Configuration.
The Global Configuration is not showing instead it shows this error

![](http://i.imgur.com/cx6xG63.png "")

**Comment by infograf768** [comment]
The layout default_cookie is no more in core since 3.4.1.
I guess you have to update your installation.

**Comment by zero-24** [comment]
Please move any other site specific issues to https://forum.joomla.org as this is the tracker of bugs :)
