### ISSUE TITLE
index 'idx_image' from file 3.7.0-2016-11-21.sql

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#13122]
### Steps to reproduce the issue

Install from joomla-cms rev 2a375e3dacab1448be3727be4e279005a01f1094

### Expected result

Database is up to date 

### Actual result

Table 'havxz_languages' should not have index 'idx_image'. (From file 3.7.0-2016-11-21.sql.)
Click Fix button
Table 'havxz_languages' does not have index 'idx_image'. (From file 3.7.0-2016-11-21.sql.)
Click Fix button
Table 'havxz_languages' should not have index 'idx_image'. (From file 3.7.0-2016-11-21.sql.)
Click Fix button
Table 'havxz_languages' does not have index 'idx_image'. (From file 3.7.0-2016-11-21.sql.)
Click Fix button
Table 'havxz_languages' should not have index 'idx_image'. (From file 3.7.0-2016-11-21.sql.)

### System information (as much as possible)

https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/sql/updates/mysql/3.7.0-2016-11-21.sql

https://gist.github.com/8432669637672974c903498a12efaf81

**Comment by Bakual** [comment]
Might be related to https://github.com/joomla/joomla-cms/pull/12949

**Comment by andrepereiradasilva** [comment]
Hum it seems the database schema checker does not take into account that a new index with the same name is created after.

this can be resolved if we change the new index name to, for instance, `#__language_image`.
```sql
ALTER TABLE `#__languages` DROP INDEX `idx_image`;
ALTER TABLE `#__languages` ADD INDEX `idx_language_image` (`image`);
```

But maybe there is another way, but i'm no db expert.
it would be nice to have @alikon option on this.

**Comment by sovainfo** [comment]
The DROP INDEX and ADD INDEX need to be in the same statement.

**Comment by andrepereiradasilva** [comment]
Yes, but how we do that in the 3 db system? Suggestions?

**Comment by alikon** [comment]
@andrepereiradasilva can you test adding a `COMMIT;` between the 2 `ALTER` statments ?

**Comment by andrepereiradasilva** [comment]
tested. doesn't work also.

**Comment by sovainfo** [comment]
ALTER TABLE #__languages DROP INDEX idx_image , ADD INDEX idx_image ;

Replace INDEX with CONSTRAINT for PG and MS SQL.
Obviously the names are different and these subcommands aren't recognized by schema checker.
They shouldn't cause the problems mentionedhere.

**Comment by andrepereiradasilva** [comment]
@sovainfo nice, tested in mysql and works. will make a PR

**Comment by andrepereiradasilva** [comment]
please test https://github.com/joomla/joomla-cms/pull/13128

**Comment by Bakual** [comment]
Closing as we have a PR.
