### ISSUE TITLE
Postgres: Installation fails with "fields_groups" doesn´t exist error

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#13135]
### Steps to reproduce the issue
Install current staging on postgresql.

Error: Relation »xxild_fields_groups« doesn´t exist
Error: syntax error »'1970-01-01 00:00:00'« LINE 11: "checked_out_time" timestamp without time zone '1970-01-01... ^

**Comment by Bakual** [comment]
Aww, it misses the "DEFAULT" keyword I think. Will do a PR.

**Comment by Bakual** [comment]
Closing as we have a PR: #13136
