### ISSUE TITLE
Postgres: Inserting an image field fails with an error

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#13137]
### Steps to reproduce the issue
I installed latest staging on postgres and tried to add an image type field to the articles field. On save I get the following error:

Save failed with the following error: FEHLER: NULL-Wert in Spalte »group_id« verletzt Not-Null-Constraint DETAIL: Fehlgeschlagene Zeile enthält (2, 0, com_content.article, null, , Picture, picture, Picture, , imagelist, , , , 1, 0, 0, 1970-01-01 00:00:00, 0, {"hint":"","image":"","image_alt":"","render_class":"","class":"..., {"directory":"\/","multiple":"0","image_class":""}, , *, 2016-12-08 20:20:42, 82, , 1970-01-01 00:00:00, 0, 1970-01-01 00:00:00, 1970-01-01 00:00:00, 1).

**Comment by alikon** [comment]
can you test #13155
