### ISSUE TITLE
S5 Template on Vertex doesn't show images on the website

### ISSUE THREAD

**Issue by JaneZhilina** [joomla/joomla-cms#13131]
### Steps to reproduce the issue

Uploaded images into Joomla Media
In the template interface I wrote the uploaded image name
Went back to Joomla Media and then it showed Invalied token

### Expected result
The image to be shown on the website

### Actual result
No image, template doesn't work correctly

### System information (as much as possible)

Template S5 on Vertex
Joomla 3.4.3

### Additional comments
Didn't upgrade to a newer version of Joomla, because the template won't work

**Comment by brianteeman** [comment]
This is the place to report issues with the core of joomla. If you have an issue with the template you must contact the maker of the template.
