### ISSUE TITLE
No calendar setup found for subform fields

### ISSUE THREAD

**Issue by n9iels** [joomla/joomla-cms#13144]
### Steps to reproduce the issue
1. Create a subform field with a calendar, see example code below
2. Load the page, the following alert appears:
  ![image](https://cloud.githubusercontent.com/assets/2659866/21046417/e76c6168-be04-11e6-91cc-eaa65f3247bd.png)

**subform.xml**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<form>
		<field
				name="date"
				type="calendar"
				label="JDATE"
				format="%d-%m-%Y"
				filter="user_utc"
		/>
</form>
```
**Joomla! field (assuming we use mod_custom)**
```xml
<field
		name="my-field"
                type="subform"
                formsource="modules/mod_custom/forms/subform.xml"
                multiple="true"
                min="1"
                layout="joomla.form.field.subform.repeatable-table"
                label="my subform field"
/>
```
### Expected result
The calendar field is load after the subform field. So the calendar is working.

### Actual result
The Calendar setup is load before the subformfield, so the alert that the field can't be found is triggered. When click on the "oke" button the subform is load and the calendar field is working.

### System information (as much as possible)
Joomla! 3.6.4
Latest version of Google Chrome

### Additional comments
Why do we even trigger a alert? Why not just a simple `console.log`?

**Comment by Fedik** [comment]
the calendar field from 3.6.4 does not made to work in the subform field,
a new calendar field in 3.7.x by @dgt41  should be fine, in theory

**Comment by brianteeman** [comment]
I am going to close this here. Thanks for the report but as stated above the current calendar field wont work and as of 3.7 we have a completely different calendar field<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13144">issues.joomla.org/tracker/joomla-cms/13144</a>.</sub>
