### ISSUE TITLE
Calendar date today identity triangle displaced 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#13166]
### Expected result

The green triangle to be correctly aligned

### Actual result

<img width="477" alt="screen shot 2016-12-11 at 15 46 25" src="https://cloud.githubusercontent.com/assets/400092/21081177/176bc04c-bfb9-11e6-9508-ba7e1a97d1ff.png">

### System information (as much as possible)

https://gist.github.com/7cfba5d9aee173fec1e4d282ac2ff59c

**Comment by PhilETaylor** [comment]
Actually I think the Sunday column is a bit wider than the rest, that being the root issue here.

**Comment by dgt41** [comment]
https://github.com/joomla/joomla-cms/blob/staging/media/system/js/fields/calendar-vanilla.js#L743
Should be 3 : 2

**Comment by PhilETaylor** [comment]
nope, changes made in #13167 made no difference :(

**Comment by dgt41** [comment]
@PhilETaylor check #13181

**Comment by Bakual** [comment]
Closing as we have a PR
