### ISSUE TITLE
[3.6.5 Regression] Install the install from web fails to load on page load

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#13165]
### Steps to reproduce the issue

Install from github joomla-cms master at revision 351b778254893d1ebbd734a88e3ad2a33b386aff

Login to admin 

Install the install from web with the button provided 

see that it fails to load the content all the time

<img width="926" alt="screen shot 2016-12-11 at 15 28 57" src="https://cloud.githubusercontent.com/assets/400092/21081078/df91d118-bfb6-11e6-8de9-c157d922dc40.png">

To make it load this correctly you can click another tab and then click the Install from web tab

<img width="902" alt="screen shot 2016-12-11 at 15 32 04" src="https://cloud.githubusercontent.com/assets/400092/21081085/fba99ec6-bfb6-11e6-9d65-9f6e1fdb4418.png">

### Expected result

Page should load correctly on first page load and after install 

### Actual result

remote content not loaded until reactivating the tab by clicking away and back

### System information (as much as possible)

https://gist.github.com/7cfba5d9aee173fec1e4d282ac2ff59c

### Additional comments

Cross posted to https://github.com/joomla-extensions/install-from-web-client/issues/50

**Comment by AlexRed** [comment]
I can confirm the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13165">issues.joomla.org/tracker/joomla-cms/13165</a>.</sub>

**Comment by PhilETaylor** [comment]
This is broken in Joomla 3.6.5 too.

**Comment by vietvh** [comment]
I can also confirm this issue, not sure when it started happening, may be even before 3.6.4 AFAIK

**Comment by Bakual** [comment]
There was a change related tp tab states which maybe  could play a role here.

**Comment by franz-wohlkoenig** [comment]
tested on 3.6.5 without Issue, Tab "Install from Web" is on 4. Place.

**Comment by PhilETaylor** [comment]
This is still an issue in 3.7.0 beta 1

**Comment by AlexRed** [comment]
yes, I can confirm.
Also reopen the tab and a message: "Cannot find any extensions for your version of Joomla. Please try a different search word or another category."

**Comment by PhilETaylor** [comment]
@AlexRed I have already raised that as https://github.com/joomla-extensions/install-from-web-client/issues/51

**Comment by zero-24** [comment]
Cosied as upstream issue :smile:

**Comment by PhilETaylor** [comment]
> There was a change related to tab states which maybe could play a role here.

are you sure this is an upstream issue? @zero-24

**Comment by mbabker** [comment]
Unless there's a B/C break, whatever fixes are required belong in the install from web repo.  If there's a provable B/C break, the issue belongs here.

**Comment by PhilETaylor** [comment]
Sorry Im in daddy mode until Monday - hence my limited replies all day today and inability to check the code to find the triggers

**Comment by doktornotor** [comment]
May I ask why's this closed when there's nothing fixed anywhere? WTH is "install from web repo"?

**Comment by Bakual** [comment]
@doktornotor https://github.com/joomla-extensions/install-from-web-client

**Comment by doktornotor** [comment]
Thanks, I assume this functionality is just dead. (That thing is completely unmaintained, hasn't seen a release for over a year, why are you pointing people there for bug fixes?)

**Comment by Bakual** [comment]
Please comment there, not here.

**Comment by mbabker** [comment]
Because that's the repository where the feature is maintained.  Whether it's dead or not is another debate.

**Comment by doktornotor** [comment]
Geeez... So, Joomla has a website with extensions. Joomla has a feature to install from that website. That feature gets broken with a new release and you are pointing people to some whacky "extension" repo where you punted that feature for god knows what reason, leaving it with a completely unresponsive "maintainer"... Schizo, anyone?

You have broken a feature, fix it, stop playing ping-pong with people reporting the breakage.

**Comment by Bakual** [comment]
> You have broken a feature, fix it, stop playing ping-pong with people reporting the breakage.

It's an extension and the repo for it is where we pointed you. It can be solved here, it has to be solved there.
That being said, it isn't completely broken (at least not to me). For me it works fine when I just activate another tab and then again the install from web one, or if I just click on the "loading" banner.
I honestly have no clue why that is but it is something which has to be solved (or at least figured out) in that repo we pointed you.

In the end, you could actually help get it solved. Joomla is a community driven thing. Every help counts.

I'm going to lock this conversation here as it is a closed issue and the thread should live in another repo anyway.
