### ISSUE TITLE
[4.0] use sql union in search plugins

### ISSUE THREAD

**Issue by alxcube** [joomla/joomla-cms#13174]
maybe it is good idea that search plugins would return subquery that will be used in main union query? 
this would help to show all search results with normal pagination

**Comment by nibra** [comment]
It indeed is. It would allow to actually get 20 results in summa, if you request 20 resukts, and not 20 results per search plugin.

As it changes behaviour, such a change nis not suitable for Joomla 3.x. But it could go into 4.0.

/cc @wilsonge @mbabker

**Comment by mbabker** [comment]
Added to RFC card on the general 4.0 board.  No guarantees on it being included, but we have this in a visible spot tracking potential 4.0 work.

**Comment by franz-wohlkoenig** [comment]
changed Title to show its about 4.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13174">issues.joomla.org/tracker/joomla-cms/13174</a>.</sub>

**Comment by Hackwar** [comment]
Just want to say that the right way to go would be to use com_finder instead. com_search isn't really able to handle this in any way. Even if we were to use UNION, we would need some attribute to sort by, otherwise you will still just have the results from the first plugin before the results of the second plugin, etc.

**Comment by Hackwar** [comment]
As I wrote above, this feature request is not really a solution AND would prevent current customisations. I'm voting against this, whatever effect that has. Considering that this request is over 2 years old and we have a better solution in 4.0, I'm proposing to close this.

**Comment by HLeithner** [comment]
Still a valid issue, maybe not with union but a way to inject sort and paginationable results.

Afaik there is not solution in com finder for this.

**Comment by Hackwar** [comment]
Finder is all about exactly that. 

There is no way to get what you want with com_search in a even remotely B/C way. Everything would mean that you have to either re-implement com_finder or make such an effort as a 3PD, that you might as well create a finder plugin instead.

**Comment by Quy** [comment]
Closing as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13174">issues.joomla.org/tracker/joomla-cms/13174</a>.</sub>
