### ISSUE TITLE
Images opened in modal popup are stretched in mobile

### ISSUE THREAD

**Issue by htmgarcia** [joomla/joomla-cms#13172]
### Steps to reproduce the issue
Make sure Protostar is your default template, and loads modal library. 

You can do this by adding a line of code to `templates/protostar/index.php` (or to a duplicated template based on protostar):
`JHtml::_('behavior.modal');`
<img width="485" alt="screen shot 2016-12-12 at 2 56 41 pm" src="https://cloud.githubusercontent.com/assets/4999794/21116450/3b6e76de-c07b-11e6-8e6a-5f64894f8574.png">

In a module or an article insert a link pointing to a big image (ideally wider than high) and with _**modal**_ class:
`<a class="modal" href="path/to/image.jpg">Modal link</a>`

### Expected result
In mobile devices, when you click the link to open the image, it should load fine keeping the aspect ratio.

### Actual result
The image loads with 100% height and width, losing the proportions (the image is stretched):
<img width="500" alt="screen shot 2016-12-12 at 3 02 41 pm" src="https://cloud.githubusercontent.com/assets/4999794/21116671/0ef2d3e2-c07c-11e6-97ac-62e63efcf9ed.png">

### System information (as much as possible)
Firefox 50.0.2
MacOS Sierra

**Comment by htmgarcia** [comment]
This seems to be the code involve: https://github.com/joomla/joomla-cms/blob/staging/media/system/css/modal.css#L74

Changing to `height: auto;` may partially solve the issue.

**Comment by C-Lodder** [comment]
I don't see why this should be fixed personally. `JHtml::_('behavior.modal');` is deprecated.

Instead, you should use `JHtml::_('bootstrap.renderModal');`

**Comment by htmgarcia** [comment]
@C-Lodder thanks for the clarification!

**Comment by franz-wohlkoenig** [comment]
@htmgarcia is this Issue resolved?

**Comment by htmgarcia** [comment]
@franz-wohlkoenig please see @C-Lodder reply.
Regards
