### ISSUE TITLE
com_joomlaupdate/restore.php, 3.6.5 & PHP 7.1

### ISSUE THREAD

**Issue by freshweb** [joomla/joomla-cms#13197]
### Steps to reproduce the issue
Set PHP to 7.1
Joomla 3.6.4

Login to Joomla Admin & install core upgrade to 3.6.5

### Expected result

Joomla to upgrade to 3.6.5

### Actual result
Presented with ajax error & update hangs. Error erroneously attributes cause to Akeeba backup.
See this Akeeba forum response : https://www.akeebabackup.com/support/akeeba-backup-3x/26726-akeeba-stopping-core-j-upgrade.html

[screen shot 2016-12-14 at 05 20 08](https://issues.joomla.org/uploads/1/bb6f296a0e32c12518fdc0728089a613.png)

### System information (as much as possible)
Joomla 3.6.4
PHP 7.1
Akeeba Backup Professional 5.2.5

### Additional comments
Downgrade PHP to 7.0 & upgrade performed as expected.

Same outcome on 5 sites running PHP 7.1. All upgraded when reverted to PHP 7.0

**Comment by mbabker** [comment]
FWIW the restore.php file is updated in staging (so fixed for 3.7).

**Comment by freshweb** [comment]
Thanks for the update.

**Comment by franz-wohlkoenig** [comment]
is this Issue solved, @freshweb?

**Comment by freshweb** [comment]
Not sure. Presumably is fixed in 3.7 as @mbabker says.

**Comment by franz-wohlkoenig** [comment]
thanks for Answer, @freshweb

**Comment by brianteeman** [comment]
This can be closed as fixed @zero-24

**Comment by zero-24** [comment]
Thanks
