### ISSUE TITLE
Menu manager: Allow to batch change template style

### ISSUE THREAD

**Issue by smehrbrodt** [joomla/joomla-cms#13194]
The menu manager has the following batch operations: set langauge, set access level and copy/move to different menu.

I suggest adding a batch operation for **set template style**. This is useful if you want multiple items to have a different template style.

**Comment by joo7** [comment]
+1 for this feature request 👍

**Comment by smehrbrodt** [comment]
I found out you can do it the other way round: When going to template styles, it's possible to assign multiple menu entries to that template style.
However, I still think it'd be good to do it as described above.

**Comment by joo7** [comment]
Great! Thanks for the info! :) I rate the need for this feature lower now, still it would be nice. 
Maybe some info is sufficiant for now, like:
"To assign multiple menu items to different template styles, 
create or select desired style here and use the 'Menu Assignment'-tab"
and link it to "index.php?option=com_templates&view=styles"?

**Comment by brianteeman** [comment]
I am going to close this. We cant have batch options for everything and as @smehrbrodt this functionality can already be achieved
