### ISSUE TITLE
com_media - impossible to reach items on sidebar menu

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-cms#13195]
### Steps to reproduce the issue
Go to the media manager

### Expected result
even with a long list of items in the sidebar menu (position icon), we should be able to reach items scrolling down.

### Actual result
![screen shot 2016-12-14 at 05 11 58](https://issues.joomla.org/uploads/1/c0d0374527c720b1ce3113e74185dbbd.png)

### System information (as much as possible)
3.6.5 tested on FF and Chrome

**Comment by infograf768** [comment]
Confirmed in staging

**Comment by infograf768** [comment]
@Fedik @dgt41 
can you have a look at this?

**Comment by Fedik** [comment]
it is just a styling thing, 
on quick test enough just set `margin-bottom: 100px;` to `.j-sidebar-container`

**Comment by ggppdk** [comment]
> on quick test enough just set margin-bottom: 100px; to .j-sidebar-container

yes i am using same thing already to avoid problems in various views, 
but why 100px , is not 100px too much ? i am using 36px

**Comment by Fedik** [comment]
@ggppdk just for "to be sure" 😄 
can be smaller of course 😉

**Comment by wilsonge** [comment]
Fixed with #13593
