### ISSUE TITLE
Update Database error (Update 3.6.4 to 3.6.5)

### ISSUE THREAD

**Issue by funky123** [joomla/joomla-cms#13192]
### Steps to reproduce the issue

Update Joomla Version 3.6.4 via OneClick to 3.6.5

### Expected result

No error message

### Actual result

Error Message:
    JInstaller: :Install: SQL-Fehler Duplicate entry '453' for key 'PRIMARY' SQL=INSERT INTO `#__extensions` (`extension_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `custom_data`, `system_data`, `checked_out`, `checked_out_time`, `ordering`, `state`) VALUES (453, 'plg_editors-xtd_module', 'plugin', 'module', 'editors-xtd', 0, 1, 1, 0, '', '', '', '', 0, '0000-00-00 00:00:00', 0, 0);
Dateien-Update: SQL-Fehlerdatei DB-Funktion mit Fehlercode 1062 fehlgeschlagen!
Duplicate entry '453' for key 'PRIMARY' SQL=INSERT INTO `#__extensions` (`extension_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `custom_data`, `system_data`, `checked_out`, `checked_out_time`, `ordering`, `state`) VALUES (453, 'plg_editors-xtd_module', 'plugin', 'module', 'editors-xtd', 0, 1, 1, 0, '', '', '', '', 0, '0000-00-00 00:00:00', 0, 0);
SQL =
INSERT INTO `#__extensions` (`extension_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `custom_data`, `system_data`, `checked_out`, `checked_out_time`, `ordering`, `state`) VALUES
(453, 'plg_editors-xtd_module', 'plugin', 'module', 'editors-xtd', 0, 1, 1, 0, '', '', '', '', 0, '0000-00-00 00:00:00', 0, 0);

### System information (as much as possible)

See Systeminfo.txt from Joomla.

**Comment by infograf768** [comment]
Just updated a 3.6.4 to 3.6.5 and id not get any error.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13192">issues.joomla.org/tracker/joomla-cms/13192</a>.</sub>

**Comment by PhilETaylor** [comment]
> See Systeminfo.txt from Joomla. 

???

What is row 453 in your #__extensions table?

**Comment by zero-24** [comment]
This looks like a error on your site as no non-core plugin are allowed to be installed in that number range.

Please remove the row 453 in your `#__extensions` table. If you need more help please request it on the forum at https://forum.joomla.org

**Comment by PhilETaylor** [comment]
> Please remove the row 453 in your #__extensions table

Not until it is certain that its not required by the site!

**Comment by zero-24** [comment]
Ahh i want to write "**check** the row 453" thanka for fixing my typo :smile: :+1:
