### ISSUE TITLE
Joomla update from old versions fail on missing CONST

### ISSUE THREAD

**Issue by mahagr** [joomla/joomla-cms#13201]
### Steps to reproduce the issue

Install Joomla 3.4 and update it from admin.

### Expected result

Update should succeed.

### Actual result

Fatal error: Undefined class constant 'PRODUCT' in libraries/joomla/updater/update.php on line 300

### Additional comments

Replacing above line with something like this should fix the issue:

```php
if (defined('JVersion::PRODUCT')) {
    $product = JVersion::PRODUCT;
    $release = JVersion::RELEASE;
    $dev_level = JVersion::DEV_LEVEL;
} else {
    // Compatible with older Joomla versions.
    $ver = new JVersion;
    $product = $ver->PRODUCT;
    $release = $ver->RELEASE;
    $dev_level = $ver->DEV_LEVEL;
}
```

... and then use the new variables...

**Comment by mahagr** [comment]
Workaround: 

Before updating Joomla, edit `libraries/cms/version/version.php` and add these into the class:

```php
	/** @var  string  Product name. */
	const PRODUCT = 'Joomla!';

	/** @var  string  Release version. */
	const RELEASE = '3.4';

	/** @var  string  Maintenance version. */
	const DEV_LEVEL = '8';
```

Just remember to update the version information and save the file. After that upgrade works from admin.

**Comment by tonypartridge** [comment]
Do you want to send a pull request so we can review?

**Comment by zero-24** [comment]
how can you reproduce that?

If you are on 3.4.x at this place the old code from 3.4 is executed => no problem.
If you updated to 3.6.x the new codse is used and worked (as the constants exists)

**Comment by zero-24** [comment]
Btw the code change (https://github.com/joomla/joomla-cms/commit/4c4d6262f9fcf2c90ce82c537190d473397e46f5) is and work there since 3.5.0 so the same problem needs to popup also on 3.4.8 -> 3.5.0 but it don't do?

**Comment by zero-24** [comment]
I have just double checked that and can't reproduce it by updating from 3.4.8 -> 3.6.5 => No issues.

Can you please double check your introducions to reporduce the issue?

**Comment by mahagr** [comment]
I had to step into another task, but I've not forgotten this one. What seems to happen to me is that the old version of JVersion gets used with the new version of the updater script.

I'm using phpbrew with default php.ini (except for small tweak in download size) with `opcache.revalidate_freq=2`, which may cause the issue.

I think the issue may be related to above setting, I do now remember that there was issue with revalidate_freq which caused a long discussion on how to fix it.

The issue happens to me every time on a clean Joomla install. I may have an idea how to fix it, though -- I will get back to you shortly on this.

**Comment by zero-24** [comment]
If the 3rd Party Code is not broken this script should clear that kind of cache (if your setting not ignore this) https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_joomlaupdate/restore_finalisation.php

The only szenario i know that 3rd Party script don't trigger that file is when you come from 2.5 as a very old version gets expected.

**Comment by franz-wohlkoenig** [comment]
@mahagr is there a PR coming?

**Comment by mahagr** [comment]
I was again reallocated to another project and because of it I never had time to look into this one.

I did confirm, though, that the issue comes from `opcache.revalidate_freq` > 1, which means that some of the classes (like JVersion) were cached from the previous request and is affecting the update script.

There are a few ways that this could be worked around. One way would be to detect if JVersion comes from the old version, attempt to clear opcache and redirect to a page, which asks you to complete the installation with some explanation of what is going on.

**Comment by franz-wohlkoenig** [comment]
@mbabker have done PRs about Cache, one is #13357

**Comment by mahagr** [comment]
This issue has nothing to do with cache, but PHP using an old version of the class.

**Comment by franz-wohlkoenig** [comment]
to high for me, read `opcache` and thought "Cache"...

**Comment by mbabker** [comment]
There is no way to detect if the JVersion class comes from an old request or whatever without explicitly flushing all the caches and reloading the file first.  Which kinda defeats the point of having a cache at that point.

As long as you're updating with the update component, its finalization step (the last thing it does before moving from `restore.php` back to the Joomla environment) [tries to clear byte code cache](https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_joomlaupdate/restore_finalisation.php#L180).

**Comment by mahagr** [comment]
Can someone try updating some older version (3.3 or below) with `opcache.revalidate_freq=600`?

**Comment by nibra** [comment]
This seems to be nothing, we can fix from Joomla's side. The problem needs to be documented together with a description on how to solve it through correct server settings.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13201">issues.joomla.org/tracker/joomla-cms/13201</a>.</sub>

**Comment by zero-24** [comment]
Thanks for the update @nibra please dokument that behavior and link it back here. 😄

**Comment by nibra** [comment]
Should not be closed before the documentation is created / updated. Otherwise, it will go lost.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13201">issues.joomla.org/tracker/joomla-cms/13201</a>.</sub>

**Comment by zero-24** [comment]
There for we have the doc label (that i have just added)? But you are the leader so you can decide. Thanks.

**Comment by nibra** [comment]
Added **caveat** to documentation, see https://docs.joomla.org/J3.x:Upgrading_from_Joomla_3.4.x_to_3.5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13201">issues.joomla.org/tracker/joomla-cms/13201</a>.</sub>

**Comment by mahagr** [comment]
True, I didn't find a proper solution for this even after a few tries. It is nice to see it documented, though!

**Comment by mahagr** [comment]
@nibra Can you fix the documentation, though.. The value needs to be 0 (turned off) instead of 1 second.

**Comment by nibra** [comment]
Fixed documentation.
