### ISSUE TITLE
Could not open URL: http://update.joomla.org/jed/list.xml

### ISSUE THREAD

**Issue by acs-ferreira** [joomla/joomla-cms#13205]
When searching for Extension updates at `administrator/index.php?option=com_installer&view=update` i get a message:

`Update: Could not open update site #61 "Update site for joomla file", URL: http://update.joomla.org/jed/list.xml`

Actually, JED Updates website is returning a 404 : http://update.joomla.org/jed/list.xml

Joomla 3.6.4 or 3.6.5

**Comment by zero-24** [comment]
i have allready requested the revert of the change in: https://github.com/joomla/update.joomla.org/pull/31 by @wilsonge

**Comment by wilsonge** [comment]
Change reverted
