### ISSUE TITLE
Tags sort dont work with menu params

### ISSUE THREAD

**Issue by tiagovtg** [joomla/joomla-cms#13202]
### Steps to reproduce the issue
Create a menu item, List of all tags and try modify order to publish date in options

### Expected result
Lits of all tags, or tag child, in publish date order

### Actual result
Always get list in title order

### System information (as much as possible)
Bug in list, dont get write params of menu.

Sold problem with add two lines and override in function getListQuery() of \components\com_tags\models\tag.php

$orderByOption = "c.core_" . $this->state->params->get('all_tags_orderby', 'c.core_title');
$orderDir = $this->state->params->get('all_tags_orderby_direction', 'ASC');

**Comment by andrepereiradasilva** [comment]
if you can solve it please open a PR for it
https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by tiagovtg** [comment]
Thank you, i open a PR.
Obrigado Andre.

**Comment by franz-wohlkoenig** [comment]
@tiagovtg can you please post the PR-Number?

**Comment by zero-24** [comment]
hmm there is no pull request by your user can you double check that?
https://github.com/joomla/joomla-cms/pulls/tiagovtg

**Comment by franz-wohlkoenig** [comment]
true, no PR found, @zero-24

**Comment by Quy** [comment]
It is not possible to set the Published Date in the Tags component (published date equals created date). Yet under Configurations>Tags, it is an option under Order drop down.

To be B/C, I assume removing it in the the Order drop down is not an option.

**Comment by Quy** [comment]
Not reproducible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13202">issues.joomla.org/tracker/joomla-cms/13202</a>.</sub>
