### ISSUE TITLE
No Git Release for 3.6.5?

### ISSUE THREAD

**Issue by acs-ferreira** [joomla/joomla-cms#13204]
**Not an issue**, but as i follow Git Releases, i can't see a release for the latest version on https://github.com/joomla/joomla-cms/releases

Is it normal?

**Comment by mbabker** [comment]
Yes.

Before using GitHub as the download provider for the packages, security releases would not have their release tags (and inherently the code diff showing the patched security issues) published for 1 or 2 days.  Now that we have the download site and don't rely on GitHub to provide a space to host the packages, this practice is being used again.

**Comment by acs-ferreira** [comment]
Ok thanks.
