### ISSUE TITLE
Since Update to 3.6.5 > All User registration fields are "optional" although they are set as required

### ISSUE THREAD

**Issue by wunderl** [joomla/joomla-cms#13218]
### Steps to reproduce the issue
Set up a Joomla 3.6.4 Website. Activate the Plugin "User - Profile". Set some fields as "required". Test a user registration in frontend and backend >> Everything ok.

Update to 3.6.5.
Test again > All fields are marked as "(optional)".
Same happens when you create an user as admin via Backend!![screen shot 2016-12-15 at 00 23 06](https://issues.joomla.org/uploads/1/87a7f18e4a4658f30961c72927862e11.jpg)

### System information (as much as possible)
Tested with 2 Installations. One was an raw 3.6.4 installation. Tested with PHP 5.3 / 5.6 / 7.0 un Linux/Apache.

### Additional comments
This is my first reported issue, so if I made sth. wrong with this, please guide me.

**Comment by PhilETaylor** [comment]
Ive not tested, but can you try this in English and see if its a language translation issue? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13218">issues.joomla.org/tracker/joomla-cms/13218</a>.</sub>

**Comment by wunderl** [comment]
No translation issue. Same problem in original English language!

Additional information:
Same error occurs on an not modiified Joomla 3.6.5 installation (not only on updated sites)!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13218">issues.joomla.org/tracker/joomla-cms/13218</a>.</sub>

**Comment by Spudley** [comment]
This seems to be the same issue that [I've just reported](https://github.com/joomla/joomla-cms/issues/13231).

**Comment by AlexRed** [comment]
I can confirm the problem.
In Joomla 3.6.5 the required field in the Plugin "User - Profile" appear like "optional" in the form text, but it is rightly required for the system.

**Comment by infograf768** [comment]
Yes, we have found where this comes from.
Checking now with JSST

**Comment by zero-24** [comment]
Please see: https://github.com/joomla/joomla-cms/pull/13254
