### ISSUE TITLE
JArchive::extract fails because of warnings (from JFolder::create)

### ISSUE THREAD

**Issue by jonathan00** [joomla/joomla-cms#13214]
### Steps to reproduce the issue
openbase_dir enabled (from apache config): php_admin_value open_basedir /srv/www/domain/htdocs
extension from https://www.joomlashowroom.com/products/auto-update-for-joomla tries to unzip a joomla-update-zip-file to
/srv/www/domain/htdocs via  JArchive::extract which is using JFolder::create.

in JFolder::create

[...]
// Check if parent dir exists
        $parent = dirname($path);
        if (!JFolder::exists($parent)) {
[...]

the parent folder (/srv/www/domain/) is checked but this is not allowed because of open_basedir ->Warnings

But it seems JArchive::extract (libraries/joomla/archive/zip.php::extractNative()) is failing because of this warnings (line 291)

### Expected result
return true

### Actual result
with debugging enabled
somethings with "loop detected"

then JArchive::extract is failing (can't create destination)

After is disabled this code from libraries/joomla/archive/zip.php::extractNative()
                // Make sure the destination folder exists
                if (!JFolder::create($destination))
                {
                        return $this->raiseWarning(100, 'Unable to create destination');
                }

everything was working fine

**Comment by franz-wohlkoenig** [comment]
@jonathan00 can you please give System Informations?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13214">issues.joomla.org/tracker/joomla-cms/13214</a>.</sub>

**Comment by jonathan00** [comment]
hi,
what do you need?

running ubuntu 14.04 with apache 2.4 and php 5.5
in my apache conf:
...
php_admin_value open_basedir /srv/domain/htdocs
...

so php doesn't have/can access to /srv/domain/ (parentpath), JFolder::create will fail, see above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13214">issues.joomla.org/tracker/joomla-cms/13214</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
have now seen on Issue Tracker its about Joomla 3.6.5

**Comment by jonathan00** [comment]
still exists with joomla 3.7.4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13214">issues.joomla.org/tracker/joomla-cms/13214</a>.</sub>

**Comment by rvalitov** [comment]
Still exists in Joomla 3.8.1

**Comment by ghost** [comment]
@rvalitov do you mean #17349 is a Duplicate?

**Comment by rvalitov** [comment]
@franz-wohlkoenig no it's not. #17349 is necessary, but solves only one problem, and it's not enough for fixing current issue, because JArchive::extract still tries to create destination folder which already exists. But I think the core reason of both issues is the same: the open_basedir should be processed more carefully.

**Comment by roland-d** [comment]
I am going to close this as we have a PR #20280
