### ISSUE TITLE
[com_fields] New methods in library have no unittests

### ISSUE THREAD

**Issue by Hackwar** [joomla/joomla-cms#13226]
The new field feature added at least 3 methods to JFormField and maybe there are even more. Neither of those methods has unittests. We should actually have unittests for both the methods in /libraries and the fields plugin, since these interact with third party code, similar to the finder code. But I could live without covering the plugins code. The methods in /libraries are a must however.

This is part of a code review of the fields feature. See #13222, #13223, #13224, #13225 and other connected issues.

**Comment by laoneo** [comment]
The new functions in JFormField will get removed with pr #13319. So I guess we can close this one then.

**Comment by Bakual** [comment]
Closing as we have a PR that deals with it.

@Hackwar If you feel it is still valid, feel free to reopen.
