### ISSUE TITLE
[com_fields] Groups should be categories

### ISSUE THREAD

**Issue by Hackwar** [joomla/joomla-cms#13223]
The groups feature of the fields component should be implemented by using com_categories. Right now, this is simply duplicating the code of com_categories, including the database structure. Yes, the groups code currently has less features than the categories code, which is another reason to use that instead. Use the categories table with a proper context and you will already be able to nest the groups arbitrarily deep, which will be a requested feature the moment this gets released.

This is part of a code review of the fields feature. See #13222 and other connected issues.

**Comment by Bakual** [comment]
Nah, it was categories and had issues. We changed to to field groups.
See https://github.com/joomla/joomla-cms/pull/13019

**Comment by Hackwar** [comment]
I disagree. DRY applies here. See my other comment in #13222

**Comment by Bakual** [comment]
I understand you, but there were to many issues and having com_fields specific code in com_categories is not acceptable. Also com_categories really is overkill for what we need here.
That's why it has been decided by PLT/Maintainers to change it.

**Comment by laoneo** [comment]
@Hackwar I was also fighting for it to leave it as categories (#12693 and #12681). But there is one valid argument against the use of categories. When com_fields will grow in the future to become really powerful then it can hinder us when we depend on com_categories.

**Comment by infograf768** [comment]
Closing as the decision has been taken.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13223">issues.joomla.org/tracker/joomla-cms/13223</a>.</sub>
