### ISSUE TITLE
Update to 3.6.5: Problems with user profile plugins

### ISSUE THREAD

**Issue by Spudley** [joomla/joomla-cms#13231]
### Steps to reproduce the issue

* Start with a Joomla 3.6.4 site, with both the User Profile and Multi Usergroup registration plugins installed and active. User Profile plugin should have some fields disabled; Multi Usergroup Registration should be configured with some usergroups to select.
* Observe the registration form looks correct.
* Upgrade to Joomla 3.6.5.
* Observe the registration form now looks broken.

### Expected result

The registration form should remain unchanged.

### Actual result

The registration form is now broken as follows:
* The main registration fields are missing entirely.
* The user profile section shows all fields, including those that have been disabled.

### System information (as much as possible)

Joomla 3.6.5 running on a Centos box.

### Additional comments

More detailed notes, with the results of my investigations so far:

I have a site that I've just updated to Joomla 3.6.5, and my user registration page has gone completely haywire.

With the change in place, I have two problems on my user registration form:

- The User Profile plugin is displaying all of its fields, even though I've set most of them to 'Disabled'. (This plugin is provided as a core plugin with Joomla but not enabled by default; I'm using it because I need users to accept T&Cs before registering, but I've disabled all the other fields)
- The main registration fields (username, email, password, etc) are not being displayed. This seems to be related to the fact that I have the [Multi Usergroup registration](https://www.joomapp.com/extension/joomla-frontend-usergroup-registration/) plugin installed. Deactivating this plugin resolves the issue with the registration fields, but not the profile fields issue, so I guess they're two separate problems.

I've spent a couple of hours digging into it this afternoon, and I've isolated it to the change in com_users/models/registration.php.

The call to `$this->getForm()` that has been added here for 3.6.5 seems to be triggering both these plugins to go haywire.

For the moment, I have been forced to revert the changes in this file, in order for my registration form to work.

I don't know whether this is a regression that's been introduced in the core or whether the plugins are at fault, but I guess I need to raise it here either way, as the User Profile plugin is provided with the core.

I've also notified the maintainer of the Multi Usergroup registration plugin in case there's anything he can do from his end to fix it.

**Comment by mbabker** [comment]
It might be a regression but that specific change is in response to one of the security issues addressed with the release so I would highly advise finding another workaround.

**Comment by Spudley** [comment]
@mbabker - I appreciate that, and I am looking for other workarounds right now. However I don't have the luxury of allowing the registration form to be non-functional in the meanwhile.

**Comment by zero-24** [comment]
See: https://github.com/joomla/joomla-cms/pull/13254
