### ISSUE TITLE
Delete "Position" in modules not working 3.6.5

### ISSUE THREAD

**Issue by Witchypaws** [joomla/joomla-cms#13243]
### Steps to reproduce the issue

Go to modules

edit previously created module that was assigned to a template position

try to delete the position so the module can be used as an instance in a page or template instead of in a position

### Expected result

the position bar will have an X on it allowing you to reset it to none 

### Actual result

This is not there in the latest upgrade, see screenshot

![screen shot 2016-12-16 at 03 00 48](https://issues.joomla.org/uploads/1/45c50ba75446861a3557ea51fa15672e.png)

### System information (as much as possible)

Joomla 3.6.5

### Additional comments

this is required when clients want to rearrange their website and move modules to different places/functionalities

As a custom web designer, I am moving modules around all the time and sometimes they need to be removed from a position and added to a menu or embedded in a page or module instance instead after review of initial setup

Currently I have to delete the module and recreate it and this can be time consuming when it requires extensive configuration

**Comment by Bakual** [comment]
That should be fixed in staging. Can you verify?

**Comment by Witchypaws** [comment]
If I knew what staging was, I could attempt to verify :). 

However I don't.

I am using a live site which is fully delegated sitting on a commercial shared hosting server using Joomla 3.6.5

The is no delete button (X) on the position dropdown in modules

Unfortunately, in the commercial environment, clients want changes to templates on the fly after the sites are launched and sometimes you need to amend the position to zero on a live site

If you could tell me about staging, I will look at that

Thanks

Jacqui

**Comment by Bakual** [comment]
Staging is the current developing code here in this repo. There is a download button on https://github.com/joomla/joomla-cms which gets you the current developing version. It can be installed like a regular package you download from www.joomla.org.

**Comment by hacki65** [comment]
I can confirm this bug - for 3.6.4 too. In 3.7 dev it is fixed.

**Comment by Bakual** [comment]
Closing as it is fixed in staging as expected.

**Comment by Witchypaws** [comment]
Thanks guys nice to know it is fixed, will await the rollout and then stop muttering to myself when I am playing with modules :)

**Comment by boomsya** [comment]
bug returned in 3.9.0
The is no delete button (X)

in HTML I have see:
"allow_single_deselect":true
but is no X button

**Comment by boomsya** [comment]
![111111](https://user-images.githubusercontent.com/8008462/49079801-4988bd80-f24a-11e8-91aa-202c5d9dfa36.jpg)

but in 3.8.13 all OK

**Comment by Bakual** [comment]
I think there is already an issue open about this. But anyway - commenting on closed issues will not get anything solved. You need to open a new one.

**Comment by infograf768** [comment]
It normally has been solved in the just released 3.9.1
See https://github.com/joomla/joomla-cms/pull/23052
