### ISSUE TITLE
mod_articles_category -> helper.php -> delete function _cleanIntrotext

### ISSUE THREAD

**Issue by webman85** [joomla/joomla-cms#13253]
### Steps to reproduce the issue

Please provide as the user to choose the option to remove or not tags.

I read the forums, it gives a lot of inconvenience.

**Comment by zero-24** [comment]
I have read your report twice now and i have no idea what do you want or what do you mean. Can you please explain or show (e.g. screenshot) what is wrong and what do you want us to change?

Thanks

**Comment by webman85** [comment]
now
`
	public static function _cleanIntrotext($introtext)
	{
		$introtext = str_replace('<p>', ' ', $introtext);
		$introtext = str_replace('</p>', ' ', $introtext);
		$introtext = strip_tags($introtext, '<a><em><strong>');
		$introtext = trim($introtext);

		return $introtext;
	}
`
i want change on
`
	$introtext = strip_tags($introtext, '<a><em><strong><img><div><span><br>');
`	
because after all update resets

**Comment by zero-24** [comment]
Hmm it looks like the importend part is missing (github cuted them out :) can you please told us which tags you want to filter with strip_tags?

**Comment by webman85** [comment]
No, I want to cancel the filter or change the filter options.

**Comment by zero-24** [comment]
Why do you want to have img div span and br tag in there? As it is a module i think it would be a mess with the tags in there (e.g. A image one a module position in the intro text may break the layout same for div and br. For span i'm not sure i think this can be added as i can't see any issues with that.

Can you show us examples where this tags (e.g. img div and br) are useful to use in that context?

**Comment by webman85** [comment]
`http://unik.place-testing.ru/` for print all objects on front page
if I can use my desired tags will not have problems with the layout for different devices

I agree that it is sometimes necessary to display a text, but the use of the module in this embodiment is also very convenient and does not require the invention of crutches

it would be nice to give the possibility to determine the necessary tags from the admin panel for this module

**Comment by Bakual** [comment]
I don't really understand your request, but wonder if you can't achieve what you want with a template override or another template style (eg "none" adds nothing around the output).

**Comment by sovainfo** [comment]
The request is very simple. Whatever is stripped should be configurable at the module instead of hardcoded!

No, that is not something you can do with overrides or style. It would require a clone.

**Comment by ggppdk** [comment]
> The request is very simple. Whatever is stripped should be configurable at the module instead of hardcoded!

The usage of method **_cleanIntrotext()**, should be moved to be inside the template / layout files and not inside the code of the Module Helper class

But before the above is done, 
- the above mentioned method should be replaced by an API method living inside **StringHelper class**, to do things done by _cleanIntrotext(), but with more flexible configuration

thus it will be reusable to more places

**Comment by Bakual** [comment]
You probably can't just move it to the layouts because it would break existing overrides.
But you can store the raw introtext into a $item->introtextRaw before cleaning it. Then an override could use that and do its own cleaning instead.

**Comment by pdreyn** [comment]
I am looking to do the same (change the tags that are allowed in introtext).  Forgive what may be a naive question, but is the comment:

 "But you can store the raw introtext into a $item->introtextRaw before cleaning it. Then an override could use that and do its own cleaning instead." 

a suggestion for how helper.php should be enhanced, or is there some way  to do so ( store the raw introtext into a $item->introtextRaw ) as an override within a template?

**Comment by Bakual** [comment]
You need to do that in the helper.

**Comment by pdreyn** [comment]
So second stupid question.  Is there a way to override the existing helper.php or do I need to create a new module?

**Comment by Bakual** [comment]
No, there is no way. Either copy the module or submit a PR to change the existing one.
See https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by pdreyn** [comment]
thx.

**Comment by anjahage** [comment]
@webman85 Is this issue still relevant?

Otherwise @nibra will look at it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13253">issues.joomla.org/tracker/joomla-cms/13253</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
set Status on "Information Required".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13253">issues.joomla.org/tracker/joomla-cms/13253</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
If this PR get no Response, it will be closed at 23th July 2017.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13253">issues.joomla.org/tracker/joomla-cms/13253</a>.</sub>
