### ISSUE TITLE
Test JDatabaseQuery::findInSet with MSSQL

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#13263]
Part of the work to make custom fields cross database compatible involved porting the `findInSet` function to all database types. This was done for Mysql and Postgres in #12642 however MSSQL testing proved hard due to other MSSQL issues. This issue is a placeholder to test the MSSQL resolution before release of 3.7

**Comment by photodude** [comment]
Now that we have AppVeyor testing where do we stand on this?

**Comment by csthomas** [comment]
`findInSet` is not the best function in general for sql.
For now it is not used by any code. In `Custom Fields` code has been changed in favour to use join syntax. 
We may also consider to remove/revert it.

**Comment by wilsonge** [comment]
If that is the case go for removing it. I'd rather not cause us unnecessary problems

**Comment by wilsonge** [comment]
Removed with #14020
