### ISSUE TITLE
onChangeState for Extension Manager not present.

### ISSUE THREAD

**Issue by UWiX-nl** [joomla/joomla-cms#13278]
### Steps to reproduce the issue
1. Go to Backend->Extensions->Manage->Manage and (un)publish an Extension item e.g. "Articles - Archived".
2. Try to catch the event using OnContentChangeState in a Plugin (why this event? 'cause every other changestate works through this event - so it's expected to use this one ;-) ).

### Expected result
The plugin function should be triggered.

### Actual result
No result because the trigger does not exists for (un)publishing extensions.

### System information (as much as possible)
PHP Version 7.0.9
Web Server Apache 2.4.23 (Win32)
Joomla! version 3.6.5
User Agent Mozilla/5.0 (Windows NT 6.3; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0 

### Additional comments
Suggestion to add a trigger event to administrator/components/com_installer/models/manage.php called OnExtensionChangeStage. Add the following code at line 140:

  $context = $this->option . '.' . $this->name;
  JEventDispatcher::getInstance()->trigger('onExtensionChangeState', array($context, $eid, $value));

The event name onContentChangeState is not logical because this event must be started from within a System plugin (if I am right).

**Comment by rvbgnu** [comment]
Hi @UWiX-nl is this still relevant?
@nibra

**Comment by franz-wohlkoenig** [comment]
set Status on "Information Required"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13278">issues.joomla.org/tracker/joomla-cms/13278</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
If this PR get no Response, it will be closed at 23th July 2017.

**Comment by mbabker** [comment]
This issue is still relevant because nobody has implemented the requested feature.

**Comment by franz-wohlkoenig** [comment]
@mbabker how to manage this?

**Comment by mbabker** [comment]
Leave it open.  It's a valid outstanding feature request.  Either someone will implement it, or a leadership decision gets made at some point that says "sorry, we aren't interested in this" and we close it, or it just sits here collecting dust.

**Comment by franz-wohlkoenig** [comment]
i'm no Fan of closing Issues and sure it stays open. It's more about how to manage to get a Decision.

**Comment by mbabker** [comment]
Nobody from leadership has closed it as a "sorry, we aren't interested" item.  So it's up for grabs if someone wants to write the code for this.

**Comment by ghost** [comment]
closed as having Pull Request #21693
