### ISSUE TITLE
Custom Fields PR merge downgraded some vendor libs

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#13270]
### Steps to reproduce the issue

Custom Fields PR merge downgraded some vendor libs.

Example: phpMailer 5.2.16 -> 5.2.14 https://github.com/joomla/joomla-cms/commits/staging/libraries/vendor/phpmailer/phpmailer/VERSION

Merged PR: https://github.com/joomla/joomla-cms/commit/2570285679ddd9174694687d2dca87f1f2581c04

**Comment by laoneo** [comment]
Can be closed as we have a PR #13303 for it.
