### ISSUE TITLE
[PostgreSQL] Search - Content plugin SQL error

### ISSUE THREAD

**Issue by ralain** [joomla/joomla-cms#13285]
### Steps to reproduce the issue

In Joomla running on PostgreSQL, search for a word that you know is present in an article, using the old search (not smart search.)

### Expected result

At least one article hit in search results and no error.

### Actual result

Zero article hits in search results.
Error message: An error has occurred.

### System information (as much as possible)

Latest Staging.
PHP 7.1
PostgreSQL 9.6.1

### Additional comments

The issue appears to arise because the GROUP_CONCAT() function is not available in PostgreSQL.

<img width="1356" alt="screen shot 2016-12-19 at 14 58 42" src="https://cloud.githubusercontent.com/assets/3478897/21315381/2ff79cd2-c5fc-11e6-9224-cf78e4fc4211.png">

**Comment by ralain** [comment]
Closing as we have a PR: #13291

**Comment by alikon** [comment]
@ralain please reopen  cause #13291 is not enough it fix the `GROUP_CONCAT()` issue,
but, there is another issue to solve with search plugin we joining on different field type....

**Comment by ralain** [comment]
Yep, I noticed that and was just about to post a new issue.

**Comment by ralain** [comment]
@alikon see #13308
