### ISSUE TITLE
Undefined property: stdClass::$package_id 

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#13287]
### Steps to reproduce the issue

administrator/index.php?option=com_installer&view=manage

### Actual result

Notice: Undefined property: stdClass::$package_id in C:\wamp\www\develop\administrator\components\com_installer\views\manage\tmpl\default.php on line 128

### System information (as much as possible)

nightly build 3.7.0

**Comment by mbabker** [comment]
If you've been updating a build make sure the https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/sql/updates/mysql/3.7.0-2016-11-24.sql migration is applied.

**Comment by 810** [comment]
yes, that did the trick
