### ISSUE TITLE
Mysql native data type

### ISSUE THREAD

**Issue by michelollivier** [joomla/joomla-cms#13299]
Hello,

In j3.6 + php7 following return a list of strings. Columns data types are not rendered.

```
<?php 
$db = JFactory::getDbo();
$query = $db->getQuery(true);
$query->select('*');
$query->from($db->qn('#__users'));
$db->setQuery($query);
?>
<pre><?php echo var_dump( $db->loadObjectList()); ?></pre>
```

More problematic is 

```
<?php 
$user = JFactory::getUser();
$user_id = $user->id;
?>
```

$user_id is not recognized as an integer.

Do you know how to return data with their native type?

Regards
Michel

**Comment by mukul11** [comment]
ok  let me check i will let you know soon.

http://breakingnewstoday.in/natural-red-lips<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13299">issues.joomla.org/tracker/joomla-cms/13299</a>.</sub>

**Comment by Bakual** [comment]
I don't think you can return them in the native type. They always come back as strings.
Just use this:
````
$user = JFactory::getUser();
$user_id = (int) $user->id;
````
