### ISSUE TITLE
com_fields breaks Search plugin on PostgreSQL

### ISSUE THREAD

**Issue by ralain** [joomla/joomla-cms#13308]
### Steps to reproduce the issue

Apply PR #13291 which fixes another search related issue.
Add a Search module (not Smart Search) and use it to search for any word.

### Expected result

No error.

### Actual result

<img width="724" alt="screen shot 2016-12-20 at 16 06 14" src="https://cloud.githubusercontent.com/assets/3478897/21360687/39540884-c6e1-11e6-9489-74765ade8b0b.png">

### Additional comments

Examining the debug information we see that the error is caused by comparing two column of different types, #__fields_values.item_id (varchar) and #__content.id (integer), which can't be done on PostgreSQL without typecasting.

@laoneo I presume there was a reason for making #__fields_values.item_id column a varchar, like enabling support for third party extensions with non-numerical ids?

<img width="1128" alt="screen shot 2016-12-20 at 16 04 09" src="https://cloud.githubusercontent.com/assets/3478897/21361027/92ef6fcc-c6e2-11e6-9dbe-be7bb4d52fda.png">

**Comment by alikon** [comment]
reviewing the query as is issued only for the context `context = 'com_content.article'`
the fast fix should be a cast....

**Comment by alikon** [comment]
@ralain now #13291 fix with typecasting can you test...
