### ISSUE TITLE
Batch modals css issue

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#13305]
### Steps to reproduce the issue

Open a batch modal.

### Expected result

all fine.

### Actual result

![image](https://cloud.githubusercontent.com/assets/9630530/21356888/230ef55e-c6cb-11e6-94ac-166ee15a5843.png)

### System information (as much as possible)

latest staging

### Additional comments

@ciar4n maybe related with https://github.com/joomla/joomla-cms/pull/13261 ?

**Comment by ciar4n** [comment]
Thank you @andrepereiradasilva 

It certainly is. PR created #13307
