### ISSUE TITLE
Cannot reset a modules position to 'Null' after assigning it - Issue previously closed under [#12530]  but still apparent in 3.6.5

### ISSUE THREAD

**Issue by Dtorr1981** [joomla/joomla-cms#13317]
### Steps to reproduce the issue

1: Assign module position to a module
2: Save module
3: No option to remove module position - the 'x' is missing in the right hand corner of the module selection dropdown

### Expected result

Reset to the module position to 'Null' or empty

### Actual result

No option to reset - the 'x' is no longer showing.

### System information (as much as possible)

Joomla 3.6.5 running Virtuemart 3.0.16

**Comment by mbabker** [comment]
As noted it has already been fixed in the staging branch which will be 3.7.0.  Short of a major security issue that will be the next release.  If and only if that happens the JSST will evaluate any "critical" bug fixes and include them in the release (as was done with 3.6.5).

**Comment by Bakual** [comment]
Closing as fixed already
