### ISSUE TITLE
[com_fields] When a field is deleted the categories associations still exist

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-cms#13312]
### Steps to reproduce the issue
- Create a field and assign it to one or multiple categories of an article.
- Trash and delete the field

### Expected result
Table #__fields_categories should be empty.

### Actual result
The associations do still exist.

### System information (as much as possible)
Latest staging.

### Additional comments
@Bakual it is a regression from #13246.

**Comment by Bakual** [comment]
I'll have a look today, makes sense :)

**Comment by Bakual** [comment]
See #13315 
Closing as we have a PR
