### ISSUE TITLE
No error is generated 404 articles in the blog category

### ISSUE THREAD

**Issue by Arahort** [joomla/joomla-cms#13318]
### Steps to reproduce the issue
Create a page
site.ru/article
site.ru/blog/article
Add to the URL address of a non-existent
site.ru/article-123
site.ru/blog/article-123
site.ru/blog/article/123

### Expected result
site.ru/article-123 = 404 Error
site.ru/blog/article-123 404 Error
site.ru/blog/article/123 404 Error

### Actual result

site.ru/article-123 = 404 Error
site.ru/blog/article-123 The page reloads, open the same article, the wrong URL
site.ru/blog/article/123 404 Error

### System information (as much as possible)
Tested in Joomla! 3.5.1, 3.6.5
SEF = on

**Comment by tonypartridge** [comment]
Can you confirm which sef options you have enabled?

**Comment by tonypartridge** [comment]
Also,

Do you have articles or categories with the same id? If so they will always load since this is how the router is coded. Nothing they can do about it.

Many thanks
Tony

**Comment by Arahort** [comment]
SEO Options http://prntscr.com/dmhl3x

Example:
http://arahort.pro/contacts/ -> http://arahort.pro/contacts-123/ = 404
http://arahort.pro/blog/53-samoskryvayushchiesya-yakorya-s-plavnoj-animatsiej-jquery/ -> http://arahort.pro/blog/53-samoskryvayushchiesya-yakorya-s-plavnoj-animatsiej-jquery-123/ = not 404
blog - blog category "Блог"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13318">issues.joomla.org/tracker/joomla-cms/13318</a>.</sub>

**Comment by infograf768** [comment]
This is an old issue, also present in staging.

**Comment by tonypartridge** [comment]
Agreeded. The solution will be Joomla! 3.7 with the new SEF system which IMHO should be enabled by default for new Joomla! Installations, this would prevent the above type of issues occurring again.

**Comment by infograf768** [comment]
Sorry, but not. 3.7. does not solve the 404 issue.
see https://github.com/joomla/joomla-cms/issues/12822

**Comment by tonypartridge** [comment]
Actually it should since the numbering won't be in the urls by default. I know it won't solve it for previous sites and it can't since the way the routers work.

But if there is no id in the URL in the first place i.e. the new routing system then the issue can't occur.

**Comment by tonypartridge** [comment]
Bringing this backup, still a big issue here. New router doesn't seem to pickup 404's in the com_redirects component and always loads 404's to the homepage without showing any error. 

Example. Enabled new router and remove ids from URLS. visit your new menu item which is linked to say a single article. remove 1 character from the url. Your site just loads the homepage. Fresh base Joomla! install. This is an issue.

**Comment by franz-wohlkoenig** [comment]
shouldn't that be resolved before release?

**Comment by tonypartridge** [comment]
Yes it should have, turns our the new router needs quite a bit of work :-(

**Comment by franz-wohlkoenig** [comment]
@wilsonge had a PR for testing, maybe there is work ongoing.

**Comment by tonypartridge** [comment]
yep @franz-wohlkoenig I've been chatting with George the last couple of days. It's a complex issue :-(.

**Comment by Hackwar** [comment]
You can not fix this issue by default for everyone without breaking backwards compatibility. It is fixed in 4.0-dev

**Comment by Hackwar** [comment]
Since this is the same issue as in #12822, can we please close this one?

**Comment by wilsonge** [comment]
Yup :)
