### ISSUE TITLE
Feature Request: Brotli support

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#13311]
### Information

The Brotli is the new compression by google, and has now support of 4 browsers (Chrome, Firefox, Edge, Opera)

its like gzip only quicker and smaller compressions. 

### Extra info
https://en.wikipedia.org/wiki/Brotli
https://blogs.windows.com/msedgedev/2016/12/20/introducing-brotli-compression/#8Cm1jMwZZgyCWYhW.97
https://blog.cloudflare.com/results-experimenting-brotli/

**Comment by ggppdk** [comment]
> its like gzip only quicker and smaller compressions.

Smaller yes, but quicker, on decompression it is a little slower, so it is fine,
but it is multiple times slower when compression, 
-- in fact from what i have read it is silly slow e.g. 25x slower than gzip, 
and thus not suitable for dynamic pages

Enabling it on web-sites that only have a few pages and combine it with Joomla page caching, then maybe

but on sites with filter forms and a lot of content, it will eat your CPU resources fast

If this is added it should be configurable to use it only on specific pages for which page caching is enabled too

**Comment by 810** [comment]
see: https://quixdb.github.io/squash-benchmark/

its slower yes, but not 25x

**Comment by ggppdk** [comment]
> its slower yes, but not 25x

Right,
my comment was partly incorrect, it is 25x at its maximum compression ratio

-- when targeting  a double compretion ratio than gzip it is only 15%-30% slower than gzip

so yes, it is worthwhile using it instead of gzip

**Comment by andrepereiradasilva** [comment]
yes, it seem brotli is going to get wide use but not yet supported by every venfors, for instance, nginx does not support it yet in the core, edge still does nto support it neither safari.

But IETF published an information RFC (https://tools.ietf.org/html/rfc7932) and many vendors are moving in to support it. So it's problable that it will be a gzip/deflate alternative soon.

**Comment by piotr-cz** [comment]
I think it's responsibility of server (apache/ ngix/ iis), not an application.

Although at this moment we have an option in global configuration to enable gzip compression for html output, I prefer to set it in the `.htaccess` file because I can configure there compression of other resources too.

Compression of html output makes relatively small impact compared to other resources (js/ css/ images) which must be configured outside application anyway.

**Comment by andrepereiradasilva** [comment]
> I think it's responsibility of server (apache/ ngix/ iis), not an application.

Agree, but ... the same is valid for gzip ... which joomla supports ...
![image](https://cloud.githubusercontent.com/assets/9630530/21547130/fc3c3c8a-cddb-11e6-9133-43676b862102.png)

**Comment by rdeutz** [comment]
Closing this here because there is a RFC for 4.0 #15804 and we don't need two open issues.
