### ISSUE TITLE
[com_fields] Unclear Permissions...

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#13327]
The new Permission Label and tip are very unclear.
Edit Value
Allows users in the group to edit any value of an item in any extension.
and
Allows users in the group to edit any value of an item they submitted in this extension.

Basically, except for people who are aware of the development of com_fields, it is impossible to even guess what this permission is about.

@laoneo @Bakual

**Comment by Bakual** [comment]
Agreed that this needs to be improved.
The idea of this permission is so you can allow certain groups to edit values of custom fields (can be set per field and group), but not allow them to edit the field itself.

**Comment by infograf768** [comment]
i guess these need to include the term "custom fields"

**Comment by laoneo** [comment]
Just thinking loud. Perhaps in the future other extensions are going to use that permission for other use cases as well?

**Comment by cpfeifer** [comment]
I think simply saying "custom field" instead of "field" is enough to clarify and it's consistent with the other core labels. I'll look at it right now and start a PR.

**Comment by cpfeifer** [comment]
Please check PR

**Comment by infograf768** [comment]
See comments there.

**Comment by laoneo** [comment]
Can we close this one as debate is fully going on #13336.

**Comment by infograf768** [comment]
I suggest to change in en-GB.ini
`JACTION_EDITVALUE="Edit Value"`
to
`JACTION_EDITVALUE="Edit Custom Fields Value"`
and 
`JACTION_EDITVALUE_COMPONENT_DESC="Allows users in the group to edit any value of the item they submitted in this extension."`
to
`JACTION_EDITVALUE_COMPONENT_DESC="Allows users in the group to edit any custom field value of the item they submitted in this extension."`
Which would give

![screen shot 2016-12-23 at 08 22 29](https://cloud.githubusercontent.com/assets/869724/21449054/898043ea-c8e9-11e6-8f9f-8cb1ec998e5a.png)

and in en-GB.com_config.ini
`COM_CONFIG_ACTION_EDITVALUE_DESC="Allows users in the group to edit any value of an item in any extension."`
to
`COM_CONFIG_ACTION_EDITVALUE_DESC="Allows users in the group to edit any custom field value of an item in any extension."`
which would give

![screen shot 2016-12-23 at 08 25 55](https://cloud.githubusercontent.com/assets/869724/21449066/9b209da2-c8e9-11e6-9c5e-aec133540159.png)

**Comment by dparul** [comment]
you only need to include the term custom field from my piont of view.[ ](https://breakingnewstoday.in/tag/sexless-marriage/)

**Comment by cpfeifer** [comment]
I found a few custom field specific language strings that need adjustment in the integration options, I'll be working on all of it this weekend. 

It is possible to remove [com_fields] from the title of this thread since the issue in question applies to en-GB.ini and will affect many other components? It's a little confusing.

**Comment by Bakual** [comment]
The permission in question was added with com_fields, that's why it has this title.

**Comment by cpfeifer** [comment]
I understand, but the proposed fix will change the value in other components as well as here because it's a global string. 

Is there a way to override the global language strings for the permissions tab on a per component basis?

**Comment by cpfeifer** [comment]
It works as an override if I put the global string in the com_fields language file, like so:

`JACTION_EDITVALUE="Edit Custom Field Value"
COM_FIELDS_FIELD_PERMISSION_EDITVALUE_DESC="Who can edit the Custom Field value in the form editor."`

It works but it doesn't seem like an ideal solution. It could be confusing or cause issues during translation. Is there a better way to isolate the custom field labels?

**Comment by cpfeifer** [comment]
I agree, I'm just trying to figure out the best way to do this.

So, if we change the label string in en-GB.ini it works
![field-label-cf](https://cloud.githubusercontent.com/assets/3790835/21504660/269767ee-cc1e-11e6-8646-4a4f076d7aa3.jpg)

But it also affects a few other places so I'm not sure this is the best way to do it either. Contacts and Users will also inherit the text, like so, which could create confusion in those components
![cf-label-users](https://cloud.githubusercontent.com/assets/3790835/21504657/1f34ee5e-cc1e-11e6-9588-1f686bb6c167.jpg)

The strings are only used in a handful of files, we could easily create specific strings for each component or just for custom fields. Any thoughts on which approach is the best?

**Comment by cpfeifer** [comment]
Actually, I just realized this is a new string to 3.7. I understanding correctly that this particular string is only used for Custom Fields?

If so, my apologies for all the questions. Just want to make sure I'm thoroughly investigating the options and impact of the suggested changes :)

**Comment by Bakual** [comment]
> Actually, I just realized this is a new string to 3.7. I understanding correctly that this particular string is only used for Custom Fields?

Yep, it has been introduced for Custom Fields and currently is only used for that.

**Comment by cpfeifer** [comment]
Thanks, check out the new PR.

Apologies for the confusion, I've had my head stuck in 3.7 for so long I didn't realize this was completely new. Thanks for your patience :)

**Comment by Bakual** [comment]
Closing this issue as we have a PR

**Comment by dparul** [comment]
you only need to include the term custom field from my piont of view[.](https://www.todaypk.lol/tag/gomovies "")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13327">issues.joomla.org/tracker/joomla-cms/13327</a>.</sub>

**Comment by brianteeman** [comment]
@dparul please do not comment on a closed issue - no one will see it. If you want to raise an issue please create a new one and reference this if it is relevant

**Comment by dparul** [comment]
ok sure thanks for telling.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13327">issues.joomla.org/tracker/joomla-cms/13327</a>.</sub>

**Comment by dparul** [comment]
@brianteeman Can u help me i have one question?   [](https://www.todaypk.lol/the-mummy-2017-watch-online-free.html "") <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13327">issues.joomla.org/tracker/joomla-cms/13327</a>.</sub>

**Comment by Bakual** [comment]
@dparul Please stop posting hidden links in your comments. I've reported you for this behavior.
