### ISSUE TITLE
[3.7 com_fields] Two fields with the same alias

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#13335]
### Steps to reproduce the issue
Create a field from type image with the name NewImageField.
Create another field from type image with the name NewImageField.

### Expected result
The two field will be created with different aliases. 

### Actual result

The two fields are created with the same alias. The two fields are shown in the field manager. But if you you edit an article, the is only one field visible. 

But it is not possible to select an image and I cant see the field in the frontend.

![bildschirmfoto vom 2016-12-22 22-25-35](https://cloud.githubusercontent.com/assets/9974686/21440975/11590e68-c896-11e6-8a7a-72199d0eada1.png)
![bildschirmfoto vom 2016-12-22 22-26-12](https://cloud.githubusercontent.com/assets/9974686/21440976/115b2ea0-c896-11e6-8d04-6ff2dfd5ee1d.png)
![bildschirmfoto vom 2016-12-22 22-26-27](https://cloud.githubusercontent.com/assets/9974686/21440977/115b4a7a-c896-11e6-91df-35c5b2107fc9.png)

**Comment by Bakual** [comment]
That's one reason why I proposed to get rid of alias completely and use the ID instead for the name. That would be unqiue by its definition.
See https://github.com/joomla/joomla-cms/pull/13182

If we keep the alias, we need to make sure the alias is unique.

**Comment by zero-24** [comment]
Closing as there is a PR to test ;)
