### ISSUE TITLE
[com_fields] empty dropdown if no groups are created.

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#13337]
### Steps to reproduce the issue

When adding a new field, you have an option to assign it to a group. If no groups have been created, the dropdown still exists but has no options. 

### Expected result

A message should be displayed instead of a empty dropdown, saying something along the lines of: 

`Please create a group if you wish to assign the field to one`

![screeny](https://cloud.githubusercontent.com/assets/2019801/21441316/643da618-c88f-11e6-99f7-e08aa7c3fbce.gif)

### Actual result

Empty dropdown

### System information (as much as possible)

Joomla 3.7-aplha 1

**Comment by Bakual** [comment]
In staging, it already looks different:
![group](https://cloud.githubusercontent.com/assets/1018684/21442072/df5bc09e-c89b-11e6-84ac-ff82ff99194d.PNG)

That should fix that issue as well, right?

**Comment by zero-24** [comment]
Should be fixed in staging with https://github.com/joomla/joomla-cms/pull/13155 ;)
