### ISSUE TITLE
[3.7 com_fields] Field content doesn't appear under Title

### ISSUE THREAD

**Issue by brianpeat** [joomla/joomla-cms#13332]
### Steps to reproduce the issue
Create a new Field Group
Create a new Field and assign it to one or more categories and assign it to the Field Group you made in step 1.
Set the Field Automatic Display to Under Title
Go to an article in the 3.7 demo such as First Blog Post and fill in the field with some content and save the article
Now view the article on the front end. It should be at something like:

http://yourdomain/joomla-cms/index.php/article-category-blog/17-first-blog-post
or use the "All Front End Views" side bar and click "Article Category Blog" and then click on First Blog Post.

### Expected result
You should see the custom field content under the article title

### Actual result
Custom field content does not appear under the title.

### System information (as much as possible)
Running 3.7 alpha 1 on Mamp and php 7.0.10

### Additional comments
If you make the field appear Before Display or After Display, it DOES appear, just not under the title.

**Comment by Bakual** [comment]
The code to show the field is https://github.com/joomla/joomla-cms/blob/staging/components/com_content/views/article/tmpl/default.php#L91
`<?php if (!$params->get('show_intro')) : echo $this->item->event->afterDisplayTitle; endif; ?>`

I have honestly no clue why there is an if clause around that.

If you set the option "Show Intro Text" to "Hide", the field will show. But also not under the title as expected but between info block and content. So this is fishy 😄

**Comment by laoneo** [comment]
As I did that feature, I saw that as well, but was to shy to ask because I tough it has to be like that. But unfortunately I'm not the only one. IMO it should be placed on line 66. Like here #13345. What you guys think?

**Comment by Bakual** [comment]
From a fist glance looks fine. At least it does what it says now and doesn't show up in the same place as the other event. :+1: 

It may be worth looking at the other places that event content is shown and make sure it's halway consistent :smile:

**Comment by Bakual** [comment]
Closing as we have a PR
