### ISSUE TITLE
REGRESSION: TinyMCE automatic language detection is broken

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#13343]
Some recent PRs changed the parameters in TinyMCE

When editing the plugin itself, the TinyMCE toolbar buttons are translated by a bunch of new ini files. Example: 
`PLG_TINY_TOOLBAR_BUTTON_PRINT="Print"`

Here, the back-end is set to French and I added in fr-FR tiny lang strings the string
`PLG_TINY_TOOLBAR_BUTTON_PRINT="Imprimer"`
![screen shot 2016-12-23 at 09 35 34](https://cloud.githubusercontent.com/assets/869724/21450014/5711a908-c8f3-11e6-9cd5-ce67a9e8caa2.png)

Until there, no issue.

But when using the editor, automatic language detection is broken. The lang js files ( in `ROOT/media/editors/tinymce/langs/` are not used anymore.
Example when admin is set to French language:

![screen shot 2016-12-23 at 09 34 43](https://cloud.githubusercontent.com/assets/869724/21449991/17a4ed34-c8f3-11e6-9c6c-bed18502371b.png)

THis is a release blocker

**Comment by AlexRed** [comment]
I can confirm the language problem after you save for the first time the editor plugin settings.

**Comment by Fedik** [comment]
@infograf768 thanks for ping, I try check it tomorrow

**Comment by infograf768** [comment]
@jeckodevelopment
Please mark this as Release Blocker. Thanks.

**Comment by infograf768** [comment]
@Fedik 
can't you use the existing .js lang files instead of adding all these new ini strings?
When editing the plugin itself, the lang would be forced, if it exists, to the admin language used, and default to English.
And we would recover the automatic language change as well as the forced language when using the editor.

**Comment by Fedik** [comment]
In the plugin editor hard to use existing TinyMCE js, because it not a real TinyMCE, it a **fake** TinyMCE panel. That why I have added all these new ini strings.

**Comment by infograf768** [comment]
Although it is a fake, is'nt it possible to use the js files and replace the method `public static function getKnownButtons()` by the values from these files + check which admin language is used?
That would really help by not maintaining 2 groups of translations with same values.

**Comment by Fedik** [comment]
It is not impossible, but complicated 😉 
And I thought about it first, but the problem in the language file structure, it not just a JSON string. So for use it need to do some "hacks", and this gives no guarantee that it will work good in the future, after some TinyMCE upgrade or something.

**Comment by infograf768** [comment]
Although it is complicated, I guess something has to be done. And it has to be done out of Tiny itself to indeed let modify as fit for future Tiny upgrades.
By curiosity, I tried to find strings for the fake editor Heading
Edit  Insert View Format Table Tools 
are not Translatable

**Comment by ggppdk** [comment]
The problem is only when editing the tinyMCE 'editor' plugin
(and in it, only at its toolbar layout configuration)

This new feature of **graphical** toolbar editing is great. The alternative is not having it ?

Maybe this is acceptable to add an inline message:

_Drag and drop the buttons below to configure the toolbar layouts of tinyMCE,
There are 3 toobar (sets) that can be configured, each can be have a different access: e.g public, registered
Please note the the display of the layout is currently not translated_

Then remove the release blocker,
and leave this for the future implementation without a "release blocker" label
when someone has time to implement translation file usage

**Comment by AlexRed** [comment]
For the inline message,

"There are 3 toolbar (sets)" but you can add more in the advanced setting.
Also I suggest to write the toolbar layouts of tinyMCE is a DEMO and the setting below have no effect on this but only in the real tinyMCE editor interface.

But for me the automatic language detection is broken also in the real tinyMCE editor interface after you save for the first time the editor plugin settings.

**Comment by ggppdk** [comment]
> But for me the automatic language detection is broken also in the real tinyMCE editor interface after you save for the first time the editor plugin settings.

aaa, i confirm it, after saving the tinyMCE editor plugin,
the editor toolbar of tinyMCE in all forms (article form, category form, etc) is no longer tranlated,

This last one , is a real issue, hopefully it is a lot easier / less work to fix that the toolbar translation inside tinyMCE editor plugin

**Comment by infograf768** [comment]
Always believe Grand'Pa :)

**Comment by Fedik** [comment]
please test #13366

**Comment by AlexRed** [comment]
#13366 ok for me for the language in the real editor, but not in the demo editor in the plugin setting

**Comment by Fedik** [comment]
for the translation of the buttons in the TinyMCE builder, please test #13368
