### ISSUE TITLE
Summary of Changes

### ISSUE THREAD

**Issue by alkarana** [joomla/joomla-cms#13341]
This PR intends to normalize config global default options in com_tags.

The method used was:

Review cs of the config.xml file - also add missing default values
Check the current params in installation joomla.sql mysql
Add missing defaults to install sql
Testing Instructions

Code review
Apply patch
Delete configuration.php
Install Joomla (no sample)
Create tag menu items and check all "Use Global" have the global value.
Documentation Changes Required

None.

Added/changed defaults in the xml

changed:

history_limit: 10 (was 5 - uniformize with articles)
tag_list_orderby: c.core_title (was title - which doesn't exist)
added:

tag_list_image: empty
tag_list_show_item_description: 1 (the first option of the list)
tag_list_item_maximum_characters: 0 (not sure about this one please confirm)
all_tags_tag_maximum_characters: 0 (not sure about this one please confirm)
Note: also correct the parameter all_tags_show_tag_descripion[](http://breakingnewstoday.in/natural-red-lips/ "") by all_tags_show_tag_description this was nto working because the parameter was badly named in the xml files

**Comment by Bakual** [comment]
> This PR intends to normalize config global default options in com_tags.

I'm not sure what you intended to do here but this isn't a PR as there is no code attached.
I'm closing this for now.
