### ISSUE TITLE
REGRESSION: TinyMCE automatic language detection is broken

### ISSUE THREAD

**Issue by alkarana** [joomla/joomla-cms#13346]
Some recent PRs changed the parameters in TinyMCE

When editing the plugin itself, the TinyMCE toolbar buttons are translated by a bunch of new ini files. Example:
PLG_TINY_TOOLBAR_BUTTON_PRINT="Print"

Here, the back-end is set to French[](https://breakingnewstoday.in/tag/sexless-marriage/ "") and I added in fr-FR tiny lang strings the string
PLG_TINY_TOOLBAR_BUTTON_PRINT="Imprimer"
Until there, no issue.

But when using the editor, automatic language detection is[](https://breakingnewstoday.in/tag/vitamin-d-benefits/ "") broken. The lang js files ( in ROOT/media/editors/tinymce/langs/ are not used anymore.
Example when admin is set to French language:

**Comment by zero-24** [comment]
closing as dublicate of https://github.com/joomla/joomla-cms/issues/13343
