### ISSUE TITLE
An invalid default value breaks article view

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#13340]
### Steps to reproduce the issue
Create a new field from type calendar and set in a default value, which is not possible. For example: mydefault

### Expected result
The not possible default value should be ignored or I should see an error message

### Actual result
The field is saved. But if i open an article for editing, the view is broken.
![bildschirmfoto vom 2016-12-23 07-44-43](https://cloud.githubusercontent.com/assets/9974686/21448571/99aaab98-c8e4-11e6-8d20-7e02e7fecf85.png)
![bildschirmfoto vom 2016-12-23 07-45-25](https://cloud.githubusercontent.com/assets/9974686/21448572/99ac12d0-c8e4-11e6-938d-53a155a200f2.png)

**Comment by dgt41** [comment]
@astridx what's the browser's console error here?
BTW text is not acceptable for the calendar, the value needs to adhere to the given format, e.g. for `%Y-%m-%d` an acceptable value could be `2016-01-01`

**Comment by Bakual** [comment]
The formfields that are used here don't check the validity of a default value. The code just assumes that the person who set the value knew what he did. Until now, that was the extension developer who set the default value. Now an admin can do the same.

Imho, it is up to the administrator to make sure the default values work.

**Comment by ggppdk** [comment]
Most fields will not break with a wrong default value
-- if a field should validate the default value, it is a thing of every field atomically,

It could be added to form field creation and show a warning
-- thus configuration can be fixed

It should never be added when the field values are viewed / rendered
- because the warning during form field creation should have pointed into fixing the configuration
- because you may be displaying 200 articles / records, and the validation will run 200 times ... without real need for it

**Comment by dgt41** [comment]
> Most fields will not break with a wrong default value
-- if a field should validate the default value, it is a thing of every field atomically,

Actually the calendar (the js part) will default to today if the specified value is bad AFAIK
Maybe the com_fields is not utilising the new calendar yet?

**Comment by laoneo** [comment]
@dgt, it just creates a calendar form field. So the new calendar should be loaded automatically, or?

**Comment by astridx** [comment]
> Imho, it is up to the administrator to make sure the default values work.
Yes, for me it is no problem. And I am very happy with the custom fields like this.
But I think there are many administrators who do not know the syntax. And Joomla! has the problem that people say it is not user friendly. 
That is why I opened this issue.

**Comment by Bakual** [comment]
A wrong default value in calendar likely produces an error on server side already, way before JS got a chance to fix it :)

**Comment by Bakual** [comment]
If it's is only the calendar formfield that is affected, we may add some checks to that. It's certainly as @ggppdk says that this should be done in the formfield itself if we want to do it.

**Comment by dgt41** [comment]
@Bakual yup, here is an example: http://codepen.io/dgt41/pen/BQEgvp

@laoneo you can discard my previous comment, fields are extending Joomla fields so...

**Comment by franz-wohlkoenig** [comment]
Issue stay on latest 3.7-staging, wrong default Value breaks View.

**Comment by dgt41** [comment]
@Bakual can we do something similar to http://codepen.io/dgt41/pen/BQEgvp in the php part of the date? 
If value is bad => value = now ??

**Comment by Bakual** [comment]
Either "now" or "empty value" would work for me, I don't care. Is it only on JS side where it breaks currently?

**Comment by laoneo** [comment]
This issue can be closed as we have a pr #15032.
