### ISSUE TITLE
Bootstrap Thumbnails broken in Isis

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#13349]
### Steps to reproduce the issue
Take any extension which uses the Bootstrap Thumbnails feature (http://getbootstrap.com/2.3.2/components.html#thumbnails) and see how ugly that looks in staging.

As an example you can use my component SermonSpeaker (eg http://www.sermonspeaker.net/download/sermonspeaker-component/sermonspeaker-component-5-5-4.html) and in backend go to "Extensions -> SermonSpeaker). That brings you to a "dashboard" view using Thumbnails.

### Expected result
![old](https://cloud.githubusercontent.com/assets/1018684/21453138/90c0d03e-c90c-11e6-9237-620e79167796.PNG)

### Actual result
![new](https://cloud.githubusercontent.com/assets/1018684/21453141/935dfd8a-c90c-11e6-8eb6-a86784eab045.PNG)

### System information (as much as possible)
Joomla 3.6.5 vs staging

### Additional comments
I think this comes from https://github.com/joomla/joomla-cms/pull/12643. 
That PR added a block to restyle thumbnails here: https://github.com/joomla/joomla-cms/blob/staging/administrator/templates/isis/less/template.less#L1523-L1692

I think those rules need a id or class prefix so they only apply to media manager related output and not all thumbnails in any extension.

**Comment by Bakual** [comment]
@ciar4n Can you have a look at this?

**Comment by ciar4n** [comment]
Thanks @Bakual I'm off the radar for the christmas but will sort this out in a few days. As suggested I'll give the media manager a unique class regarding #12643.

**Comment by Bakual** [comment]
See also https://github.com/joomla/joomla-cms/issues/13383 (Install from Web) where this is broken as well. So we even have a place in core.

**Comment by zero-24** [comment]
There is a PR thanks @ciar4n at #13406
