### ISSUE TITLE
Catch Exceptions

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#13357]
The API fails to catch Exceptions in a lot of cases which causes Joomla to hit an error page when it could gracefully degrade and continue.  Two of the worst offenders with this are in using the cache and logging libraries; generally callers to those libraries should be able to continue even if performing CRUD operations on the cache or writing a log message fails.

An effort should be made to catch Exceptions from these libraries and try to gracefully handle the error and continue the request cycle instead of these going uncaught and triggering an error page.

**Comment by brianteeman** [comment]
@mbabker looks like we have had quite a few PR to address this - are there any other areas that need to be addressed or is this now complete?

**Comment by mbabker** [comment]
Probably complete enough.
