### ISSUE TITLE
Robots follow no follow

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#13364]
### Steps to reproduce the issue
Install Joomla with sample data
visit the front end and view page source

### Expected result
meta tag for robots follow, no follow etc. should be in the head

### Actual result
Robots meta is missing

**Comment by bertmert** [comment]
That's the expected behavior. `follow,index` is the default standard value for attribute `robots`. It's not needed to set it explicitly.

**Comment by infograf768** [comment]
See http://www.robotstxt.org/meta.html<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13364">issues.joomla.org/tracker/joomla-cms/13364</a>.</sub>

**Comment by DaveOzric** [comment]
Actually, I believe this was for the weblinks component. I need to run a test on a new install to verify it's not an upgrade issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13364">issues.joomla.org/tracker/joomla-cms/13364</a>.</sub>

**Comment by DaveOzric** [comment]
Just to be clear there is no setting outside of the module to set a follow/nofollow option.

I am 99.9% sure it used to be in each link and in the global options and menu items settings. This is not the same as index follow settings as a html link would not have a index. It's a link attribute and it's gone.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13364">issues.joomla.org/tracker/joomla-cms/13364</a>.</sub>

**Comment by bertmert** [comment]
I don't understand. I followed testing instructions and all worked like expected. META robots: all fine.

If you think that there are other issues concerning META-Robots-Tag please provide some more detailled testing instructions.

**Comment by DaveOzric** [comment]
@bertmert The original post is not correct. It's not a meta tag issue. It's a rel=nofollow issue.

Install, add a menu item of weblinks and try and set one to rel=follow. You won't be able to do this. Only a module of weblinks can be set to follow.

**Comment by DaveOzric** [comment]
Once you have a menu item of weblinks check the html of the link and see it's forced as rel=nofollow which used to be an option in each link or in global settings. Now only a module has such a setting in it.

**Comment by franz-wohlkoenig** [comment]
is this still an Issue?

**Comment by DaveOzric** [comment]
I believe it is.

**Comment by DaveOzric** [comment]
A menu item called Weblinks is hard coded as rel=nofollow. A weblinks module has the setting in it for follow or nofollow.

http://aspiralmind.com/

**Comment by franz-wohlkoenig** [comment]
@bertmert [suggested](https://github.com/joomla/joomla-cms/issues/13364#issuecomment-269604762) to open a Issue at <a href="https://github.com/joomla-extensions/weblinks">https://github.com/joomla-extensions/weblinks</a> (com_weblinks has been decoupled from Joomla core)

**Comment by brianteeman** [comment]
As this is related only to weblinks then please can you close this here @zero-24
