### ISSUE TITLE
[3.7.0] Warning JUser: :_load: Unable to load user with ID: 713

### ISSUE THREAD

**Issue by shur** [joomla/joomla-cms#13361]
### Steps to reproduce the issue
Joomla 3.7.0 fresh installation with sample data: Blog
Go to Content > Articles > Working on Your Site
and you see the warning:

> JUser: :_load: Unable to load user with ID: 713

### Actual result
![unable to load user with id 713](https://cloud.githubusercontent.com/assets/1245155/21466727/a413f66e-c9e5-11e6-8f33-82e4a48c00a5.png)

### Additional comments
Is it possible to leave the field "Modified by" empty in sample date sql files?

**Comment by Bakual** [comment]
The User ID is shown on purpose but there is already at least one PR around to deal with the message. Just can't find it at the moment.

**Comment by andrepereiradasilva** [comment]
https://github.com/joomla/joomla-cms/pull/12947

**Comment by shur** [comment]
@andrepereiradasilva thanks for PR

**Comment by vijaykhollam** [comment]
Sometimes if any extension has not handled action "onUserAfterDelete".
like, delete/update user id from the created_by column from extensions database table, then the Joomla throws following warning message. 
Message : "JUser: :_load: Unable to load user with ID: %s"
Ideally, the extension should handle this but message looks messy to end user ( frontend ) and may lose trust on site. Can we do something here?

I found this from joomla
language/en-GB/en-GB.lib_joomla.ini:
JLIB_USER_ERROR_UNABLE_TO_LOAD_USER="JUser: :_load: Unable to load user with ID: %s"

libraries/src/User/User.php 
\JLog::add(\JText::sprintf('JLIB_USER_ERROR_UNABLE_TO_LOAD_USER', $id), \JLog::WARNING, 'jerror');

**Comment by ghost** [comment]
@vijaykhollam Can you please open a new Issue as Comments on closed Issues didn't get much Notice.

> Sometimes if any extension has not handled action "onUserAfterDelete".

but i'm not sure if you write about Core.

**Comment by vijaykhollam** [comment]
Thanks, @franz-wohlkoenig 
I have added the new issue. i.e https://github.com/joomla/joomla-cms/issues/20689
