### ISSUE TITLE
Menuitem type Tagged items: No Browser Page Title

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#13365]
### Steps to reproduce the issue
- Tested with 3.6.5 and confirmed twice in a German forum: http://www.joomlaportal.de/joomla-3-x-allgemeine-fragen/327658-problem-mit-schlagwort-und-seitenanzeige-seitentitel-im-browser.html

- Additionally tested with 3.7.0-alpha1 

- Create some tags.
- Tag some articles.
- Create a menu item of type `Tagged items`.
- - Select one or more tags.
- - Set `Page Display` > `Browser Page Title`: "Hello World!"
- - Save
- Open menu in front end
- Browser `TITLE` is not "Hello World!" but tag titles

### Additional comments
@zero-24 

It looks like PR https://github.com/joomla/joomla-cms/pull/12167/files#diff-3f7bd61459465d483eb2e4ac6b359d93R209 is the reason for this behavior.

**Comment by franz-wohlkoenig** [comment]
Issue also on latest 3.7-staging.

**Comment by brianteeman** [comment]
Agree with @bertmert about the cause of this broken behaviour

https://github.com/joomla/joomla-cms/blob/staging/components/com_tags/views/tags/view.html.php#L189

**Comment by AlexRed** [comment]
I can confirm the problem on Joomla! 3.7.2-Dev (nightly Build)

**Comment by franz-wohlkoenig** [comment]
I guess this Issue is the one with the most duplicated Reports.

**Comment by cs100675jvv** [comment]
Well. Maybe someone can tell me how to fix this issue?

**Comment by bertmert** [comment]
Please test https://github.com/joomla/joomla-cms/pull/16773

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16773<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13365">issues.joomla.org/tracker/joomla-cms/13365</a>.</sub>
