### ISSUE TITLE
Please update PHPMailer

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#13373]
### Additional comments
Please update vendor class PHPMailer to version > 5.2.16 in Joomla 3.x.
(You know better than me if it's an urgent issue concerning Joomla core.)

**Comment by mbabker** [comment]
It's already included in another Composer PR.

**Comment by bertmert** [comment]
I only find a composer update to version 5.2.16 but not > version 5.2.16.

(And an update to version 6 for Joomla 4.)

**Comment by mbabker** [comment]
There isn't a PR specifically updating only PHPMailer, there's one open updating all of the Composer dependencies.  That's what I was referring to.

**Comment by bertmert** [comment]
Now I see. Thanks!
