### ISSUE TITLE
[3.7] Links on Statistics Module Backend

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#13386]
### Steps to reproduce the issue
On Statistics Module in Backend are no Links (i.E. "Users" and "Weblinks"):
![2](https://cloud.githubusercontent.com/assets/8235763/21518783/f8921422-cce8-11e6-842f-73e12f6d8520.JPG)
### Expected result
Links to Users, Weblinks, PHP-Settings (on "System Information")
### System information (as much as possible)
Joomla! 3.7.0-alpha1
macOS Sierra, 10.12.2
PHP 7.0.4
MySQLi 5.5.53-0+deb7u1

**Comment by andrepereiradasilva** [comment]
Don't quite understand why there should be links there, is just a counter.

**Comment by franz-wohlkoenig** [comment]
Its easier to click on "Weblinks" than to learn to go up to "Menu > Components" and there down to "Weblinks".

**Comment by andrepereiradasilva** [comment]
think you can close this now as there is a PR https://github.com/joomla/joomla-cms/issues/13396
