### ISSUE TITLE
Custom Fields Home Directory Function shows route but should show Userfolder

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#13397]
### Steps to reproduce the issue
Create a new Media Field, set Home Directory to "yes"

### Actual result

If you click on select the Media manager opens at the "/" root and says: 
"No Images Found"

![image](https://cloud.githubusercontent.com/assets/828371/21543776/b6576670-cdc9-11e6-9c78-eb323e663f3f.png)

actually when you upload there an image you see it´s uploaded in a directory with the username
"Elisa" but still showing "/"
![image](https://cloud.githubusercontent.com/assets/828371/21543806/f1bfd44a-cdc9-11e6-8b59-f39a6b9b85db.png)

**Comment by laoneo** [comment]
I guess that's more of a media manager issue than custom fields, or? It points to the right directory, just the wrong directory is selected in the drop down?

**Comment by franz-wohlkoenig** [comment]
Issue also on latest 3.7-staging.

**Comment by AlexRed** [comment]
Sorry...  but where can I set Home Directory to "yes"  ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13397">issues.joomla.org/tracker/joomla-cms/13397</a>.</sub>

**Comment by laoneo** [comment]
This issue can be closed as the home option got removed with pr #13893.

**Comment by brianteeman** [comment]
Closed as requested
