### ISSUE TITLE
[com_fields] Missing Outout in Custom Fields

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#13394]
![image](https://cloud.githubusercontent.com/assets/828371/21543463/e3a08cfe-cdc6-11e6-887f-b4038d06747e.png)

The image and image alt fields seem to do nothing. Tested in frontend-output, frontend-input, and backend-input.

**Comment by Bakual** [comment]
I have a list of unused fields here: https://github.com/joomla/joomla-cms/issues/12733

I planned to remove them if but didn't come around yet.

I'm closing this as a duplicate so we can keep the discussion in one place. But thanks for the report - it shows I'm not the only one seeing that 👍
