### ISSUE TITLE
[com_fields] Custom Fields Home Directory Folder is created by Username

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#13399]
### Steps to reproduce the issue

Setup a Media Field with Home Directory function
Create a User with a username such as: Ümit Meßfelder-Gèdon
Login as this User and upload an Image, the userfolder will be created with a non webcompliant name (Spaces and Special Characters). Same happens with hebrew characters.

![image](https://cloud.githubusercontent.com/assets/828371/21543877/88f80a80-cdca-11e6-8231-a2e89607721b.png)

Additionally the Media manager has issues to call this directory then properly:

![image](https://cloud.githubusercontent.com/assets/828371/21543936/1d841e00-cdcb-11e6-8c2c-787ed27fa2ce.png)
![image](https://cloud.githubusercontent.com/assets/828371/21543939/24d12770-cdcb-11e6-9236-711524a076da.png)

which doesn´t happen with webcompliant characters

![image](https://cloud.githubusercontent.com/assets/828371/21543944/32dc1b22-cdcb-11e6-960b-baed872a3f9d.png)

**Comment by n9iels** [comment]
I can confirm this issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13399">issues.joomla.org/tracker/joomla-cms/13399</a>.</sub>

**Comment by Bakual** [comment]
@laoneo Do you think that is an issue with the com_fields integration or is that an issue in the media manager (or the media formfield) itself?

**Comment by zero-24** [comment]
Please try: https://github.com/joomla/joomla-cms/compare/staging...zero-24:makesave?expand=1 i have not tested it yet.

**Comment by n9iels** [comment]
@zero-24 @Bakual @coolcat-creations I just created a PR for this

**Comment by Bakual** [comment]
Closing as there is a PR
