### ISSUE TITLE
[com_fields] Tooltip for the Field "Hint"

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#13393]
![image](https://cloud.githubusercontent.com/assets/828371/21543400/3dbf02ca-cdc6-11e6-864a-f13f0ff1a52c.png)

The tooltip for the hint field is actually saying how this Field should be named.

I´d propose to name it "Placeholder" and write in the Tooltip "This is a Placeholder text which will appear in the field as a hint for the user"

If someone can help with the native english i can make a PR.

**Comment by jeckodevelopment** [comment]
I prefer "placeholder" instead of "hint" and iirc we use placeholder in other locations

**Comment by coolcat-creations** [comment]
@tonypartridge but this is a Placeholder, not a tooltip.

**Comment by tonypartridge** [comment]
@coolcat-creations this is a place holder:
<img width="892" alt="screenshot 2016-12-30 12 07 54" src="https://cloud.githubusercontent.com/assets/1400982/21564844/a3b3693c-ce88-11e6-98ba-3992edf44b3b.png">

from a coding aspect. In your screenshot it is a Tooltip or a hint since it's providing information on the field. Placeholders are only there for a short while and are replaced when text is entered.

**Comment by dgt41** [comment]
Hint is a Joomla invented term, let's use the W3C term which is placeholder!

**Comment by coolcat-creations** [comment]
@tonypartridge you misunderstood my report. Of course i made a screenshot of the tooltip too because in my issue i report the text in there too. But the issue is about the label "Hint" used for something that is a "Placeholder"

**Comment by tonypartridge** [comment]
Ahh sorry :-(. Yes I agree but also we should refactor jform since the xml requires hint for placeholders too :-(

**Comment by dgt41** [comment]
@tonypartridge unfortunately that can't happen before Joomla 4 due to B/C promises

**Comment by laoneo** [comment]
Can we close this one as the PR got merged which made the text more clear?

**Comment by brianteeman** [comment]
@zero-24 this should be closed
