### ISSUE TITLE
[com_fields] Custom Fields - If all Fields are shown on Frontend the Fields Tab remains in backend

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#13395]
### Steps to reproduce the issue
Setup just one field and show it on the Frontend. Or setup all fields to be shown only on frontend.

### Expected result
In backend there should not be a fields tab

### Actual result
the backend shows an empty fields tab

![image](https://cloud.githubusercontent.com/assets/828371/21543532/98eb9360-cdc7-11e6-8bee-639a8fed23e9.png)

**Comment by cpfeifer** [comment]
I can confirm this and I agree it should not appear if there are no fields.

@laoneo can you tell me where (which file) the Field Group tab gets inserted into the article editor? The fields are rendered through the layout file, but I'm having a hard time finding where the layout file gets called in from Fields. We just need to add a conditional / check for "show_on" status before the layout call.

**Comment by laoneo** [comment]
Please test pr #13456 which should fix the issue. I think we can close this one as we have a pr.
