### ISSUE TITLE
[com_fields] Improving Custom Fields - Tooltip for the Field "Description"

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#13392]
![image](https://cloud.githubusercontent.com/assets/828371/21543360/d104c430-cdc5-11e6-99ed-8fb3d0264125.png)

The tooltip for the description doesn´t tell the User really what happens with this input.
I´d rather say here it´s "The description which will appear in a tooltip when a user hovers the label".

If someone tells me this sentence in clean english i can make a PR.

**Comment by cpfeifer** [comment]
How about "A description of the field which will appear in the label tooltip"

**Comment by zero-24** [comment]
PR #13557
