### ISSUE TITLE
[com_fields] Custom Fields Media Field if class is empty still class is shown as attribute

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#13400]
### Steps to reproduce the issue
Create an media field and don´t fill the image class field.

There is an empty class attribute shown in the Source code
![image](https://cloud.githubusercontent.com/assets/828371/21544078/641d240a-cdcc-11e6-93ec-d3e7974cf5e2.png)

**Comment by zero-24** [comment]
please test #13462
