### ISSUE TITLE
URL form field type Schemecheck issue / Custom Fields

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#13401]
### Steps to reproduce the issue
Create an URL Field with allowed schemes http and https
Use the field and write just test in it.

The "field" is supposing that if no one inputs http or https it might be an internal link then
Link which will be created 
![image](https://cloud.githubusercontent.com/assets/828371/21544148/f5110576-cdcc-11e6-8f0e-9115304d71f5.png)

![image](https://cloud.githubusercontent.com/assets/828371/21544153/fcc259fa-cdcc-11e6-9667-558f84514eb1.png)
 
only if you input "another scheme" like ftp:// it will throw an error

![image](https://cloud.githubusercontent.com/assets/828371/21544169/1a396de8-cdcd-11e6-8db2-4d8a7f745ccb.png)

We should consider that people don´t know about this "scheme" and might write in the www. Adress. But then it´s considered as an internal link, and that happens:

![image](https://cloud.githubusercontent.com/assets/828371/21544201/5d3fc2b8-cdcd-11e6-83db-baa182a9e513.png)

This issue is only more visible with custom fields, but is actually an UX issue of the Form Fieldtype itself.

**Comment by ralain** [comment]
This is a tricky one to get around if you allow relative links, but if you set Relative to No the scheme will be validated strictly.

**Comment by laoneo** [comment]
I think, the same happens when you put in that urls into the url properties of an article.

**Comment by brianteeman** [comment]
Can I ask why this has been closed - i dont see any fix?
