### ISSUE TITLE
Custom Fields Batch Process layout issue

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#13405]
1) The options can´t be selected
2) the margin/padding to the border is too small

![image](https://cloud.githubusercontent.com/assets/828371/21544527/f68550ee-cdcf-11e6-881a-e89eadf44e27.png)

Current Browser: Chrome

**Comment by zero-24** [comment]
Can you check https://github.com/joomla/joomla-cms/pull/13307 ?

**Comment by coolcat-creations** [comment]
done, thanks - issue remains here partly 
![image](https://cloud.githubusercontent.com/assets/828371/21544742/18068128-cdd2-11e6-95b6-f467c26f1891.png)

**Comment by jeckodevelopment** [comment]
Closing since we have a PR to test.
Thank you both @coolcat-creations and @ciar4n
