### ISSUE TITLE
[PostgreSQL] Database warning for #__session table after fresh install

### ISSUE THREAD

**Issue by ralain** [joomla/joomla-cms#13416]
### Steps to reproduce the issue

Install latest staging on PostgreSQL and check for database issues.

### Expected result

No warning for the #__session table.

### Actual result

<img width="693" alt="screen shot 2016-12-29 at 23 33 14" src="https://cloud.githubusercontent.com/assets/3478897/21556897/321448fe-ce25-11e6-8e23-4a0f02f3191d.png">

### Additional comments

Pressing the "Fix" button does not clear the warning.
The client_id column appears to be properly defined when checking it in pgAdmin.

**Comment by andrepereiradasilva** [comment]
prabably because of this https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/sql/updates/postgresql/3.7.0-2016-10-02.sql

The database schema checker has some issues with that.
@alikon can you check?

**Comment by alikon** [comment]
you can test  #13419

**Comment by ralain** [comment]
Closing again as we have a PR, thanks @alikon.
