### ISSUE TITLE
[com_fields] Search filter criteria not passed to new items

### ISSUE THREAD

**Issue by cpfeifer** [joomla/joomla-cms#13429]
### Steps to reproduce the issue
In Fields, click search tools and select a field group to filter the list by field group. Click new to create a new field.

### Expected result
The field group should be populated with the filter selection as it is in Articles, Menus, etc.

### Actual result
The field group is empty in the edit screen of the new item

### System information (as much as possible)
Current build

### Additional comments
Video of article behavior and fields behavior
![com_fields_filter](https://cloud.githubusercontent.com/assets/3790835/21572447/2c250e62-ce96-11e6-9726-0b9bc23fc2d7.gif)

**Comment by laoneo** [comment]
@Bakual I leave this one for you as it is a regression from #13019 :wink:

**Comment by Bakual** [comment]
I'm not sure if that really worked before, but there you go: #13460 :smile: 

Closing as we have a PR.
