### ISSUE TITLE
Joomla Update "Find Updates" Issue

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#13428]
### Steps to reproduce the issue

Install a load of crap extensions (or just Virtuemart and a load of other crap). Or a site with 100 update sites... 

(or be on a crap server that is blocking outgoing traffic in such a way that an outgoing http request hangs instead of getting a connection denied message)

Go to Extensions -> Update -> Find Updates

Note that if any one update site is slow or never ends then the page times out eventually or hangs for ever and ever. 

### Expected result

Expect a list of updates available

### Actual result

Page just hangs because one or more update sites are pathetically slow or dead. 

### System information (as much as possible)

Joomla 3.6.5 

### Additional comments

Each update site check should be time boxed, or run in isolation (maybe in a separate ajax thread) so that one doesnt effect all.

**Comment by PhilETaylor** [comment]
This method needs a lot of reworking https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/updater/updater.php#L115

**Comment by PhilETaylor** [comment]
Also a time out of 20 seconds per update site... really? 
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/updater/updateadapter.php#L246

Thats far far too long....

**Comment by PhilETaylor** [comment]
reducing the time out to 2 seconds I see the root issue with VirtuCrap, however their 404's are just highlighting the root issue in Joomla installer as described in the opening statement of this issue.

![screen shot 2016-12-30 at 20 53 00](https://cloud.githubusercontent.com/assets/400092/21572547/10acd82c-ced2-11e6-9395-1a40198612a2.png)

**Comment by nibra** [comment]
> their 404's are just highlighting the root issue in Joomla installer

@PhilETaylor, what behaviour would you expect instead (beside waiting 2 seconds instead of 20)?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13428">issues.joomla.org/tracker/joomla-cms/13428</a>.</sub>

**Comment by RedEvo** [comment]
I would expect that all updates would be run in isolation and even maybe in parallel, with individual timeouts, per update, one per http request to avoid timeouts on servers

**Comment by dgt41** [comment]
In J4 we can use promises and chain all these requests, so they would be async and the failures could be handled much better

**Comment by PhilETaylor** [comment]
So there is no appetite to change this behaviour at present?

**Comment by dgt41** [comment]
I'll test the PR if you create it :)

**Comment by PhilETaylor** [comment]
Now where have I heard that before. 

Speculative PRs are a waste of time if they are never going to be merged - gauging interest is the best way to start, if there is no interest at the start, there will be no interest in a PR.

This is a big usability bug, I see no reason this issue should not remain open until its fixed.

**Comment by mbabker** [comment]
Nobody's saying it's not an issue.  But for those who do PRs, either this isn't an "interesting" issue they want to tackle or they don't have the technical skill set to do anything with it.

**Comment by dgt41** [comment]
or too busy with other 💩

**Comment by PhilETaylor** [comment]
Exactly my point... 

Unfortunately Github doesn't have a 💩 list category, so I'll just close it...

**Comment by mbabker** [comment]
If you keep closing legitimate issues then they're never going to be tackled to begin with.

**Comment by PhilETaylor** [comment]
Im just working through my list of open issues - trying to prune the ones that will never get done, and leaving the ones that might.

**Comment by PhilETaylor** [comment]
Some issues are so big that they will keep cropping up until they are resolved, they dont need an open issue clogging up the Github stats for that...

Its in a book somewhere....

**Comment by mbabker** [comment]
The book is here on GitHub.  There isn't a magical list elsewhere of known issues that might get tackled one day if someone is interested.

**Comment by PhilETaylor** [comment]
by book I mean the one by 37Signals
https://gettingreal.37signals.com/ch15_All_Bugs_Are_Not_Created_Equal.php
and in their follow up book they say something about ignoring bug reports that are blatantly obvious because if its really a big enough but it will come back and back and hit you in the face enough that you fix it without users telling you to. 

If we were to list all of our annoyances with Joomla in GH then the issues list would be huge ;-)

**Comment by mbabker** [comment]
> If we were to list all of our annoyances with Joomla in GH then the issues list would be huge ;-)

That sounds like someone I groan at every time they publish a blog or tweet stream groaning about Joomla performance, they shut up every time I tell them to log an issue instead of groaning 😉
