### ISSUE TITLE
Blank registration form page after upgrading to 3.6.5

### ISSUE THREAD

**Issue by Frostbourn** [joomla/joomla-cms#13423]
Registration form just dissapeared after upgrading from 3.6.4 to 3.6.5. 

> /component/users/?view=registration

There was only blank page, no errors (error_reporting set to maximum in the backend and turned on in php.ini). I solved this issue by replacing:  

> components/com_users/models/registration.php

from 3.6.4 release.

**Comment by bertmert** [comment]
I don't know if it's really related but did you test this change already:
https://github.com/joomla/joomla-cms/commit/37222604e2ce92f00072f554f44b6a97cfc66756

**Comment by Frostbourn** [comment]
+1, thank you bertmert.

**Comment by Frostbourn** [comment]
+1, thank you bertmert.

**Comment by tonypartridge** [comment]
Did the fix by mbabker solve your issue?

Do you have a template override in place?

**Comment by franz-wohlkoenig** [comment]
@Frostbourn is this still an Issue?

**Comment by Quy** [comment]
Unable to reproduce.
Installed Joomla 3.6.4.
Upgraded to Joomla 3.6.5.
Registration form appears and works as expected.

**Comment by zero-24** [comment]
Closing again. As this is fixed by the change posted above.
