### ISSUE TITLE
Attempting to apply many (large amount, or slow updates) updates at once fails

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#13430]
### Steps to reproduce the issue

Find a site with a lot of updates available (or mock it with a lot of slow update sites and large crap extensions)

Joomla Admin -> Extension -> Updates -> Find Updates -> Select All (a large number) click Update 

### Expected result

Joomla successfully applies all updates for extensions - regardless on how many selected. 

### Actual result

Joomla bombs out when it hits server/php/apache/nginx timeouts after only running some updates. 

### System information (as much as possible)

Joomla 3.6.5

**Comment by frankmayer** [comment]
@PhilETaylor I can confirm this. It has happened from time to time. 
From a quick look at the installer/updater classes and the way they work together, I think they should be completely refactored, so they can be easier re-used, tested and debugged, to make it easier to implement a better solution. That's a bigger task though, if backwards compatibility has to be maintained (Though it could definitely be broken in 4.0).

**Comment by ghost** [comment]
Status is set on "Needs Review".

**Comment by wilsonge** [comment]
I don't think this is really fixable and there's been no interest on the issue so I'm going to close it at this time. Joomla can't guess how long each extension update is going to take so I don't think we can even stop users updating multiple extensions at a time...

**Comment by HLeithner** [comment]
If the updatr process is done per ajax call per component you have at least the full timeout and a progressbar like com_finder while indexing.

But i don't of its really needed

**Comment by PhilETaylor** [comment]
> If the updatr process is done per ajax call per component 

like WP ;-)

**Comment by HLeithner** [comment]
Is this a problem?

**Comment by brianteeman** [comment]
If a developer wants to write the code no one will stop them otherwise this will stay closed.
