### ISSUE TITLE
[3.7] Change ordering in "Cache Setting"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#13443]
### Steps to reproduce the issue
In "Global Configuration > Cache Setting" Option "System Cache" is shown at last. Options "Cache Handler", "Cache Time" and "Platform Specific Caching" are shown before.
![bildschirmfoto 2017-01-01 um 13 42 24](https://cloud.githubusercontent.com/assets/8235763/21581244/b8a51686-d029-11e6-9ebb-4f0f59285abf.JPG)
### Expected result
Show only "System Cache", if "OFF" is in use. 
If "ON" is select, show other Options below.

**Comment by bertmert** [comment]
See:
https://github.com/joomla/joomla-cms/pull/12742
and issue
https://github.com/joomla/joomla-cms/issues/12492

**Comment by franz-wohlkoenig** [comment]
Thanks @bertmert, haven't found this Issues.
