### ISSUE TITLE
Session problem

### ISSUE THREAD

**Issue by alex7r** [joomla/joomla-cms#13444]
### Steps to reproduce the issue
Setup multi-language site (option hide default language is enabled, sef + rewriting is enabled)
go to administrator, 
try to login

### Expected result
Successful login

### Actual result
Nothing happens, even no error message.
Caused by token check, and somehow session token is not matching.

### Additional comments
May be related with cookie settings or something?
Deployed site with akeeba kickstart.

**Comment by zero-24** [comment]
> Deployed site with akeeba kickstart.

Can this be reproduced with a clean install of staging / 3.7.0alpha? A site that comes from everything else than the normal installer is no clean install ;)

**Comment by zero-24** [comment]
And which exact version is that you handle. stable or alpha or staging?

**Comment by zero-24** [comment]
hmm that would mean something is changed between 3.6.4 and 3.6.5
https://github.com/joomla/joomla-cms/compare/3.6.4...3.6.5?expand=1

But I can't see any change that can cause such issue :(

Can you reproduce this issue using a clean install of 3.6.5? And an update from 3.6.4 -> 3.6.5 (without akeeba)

**Comment by alex7r** [comment]
I'll check and will get back with results within 2 days.4:09 PM, January 2, 2017, "zero-24" <notifications@github.com>:hmm that would mean something is changed between 3.6.4 and 3.6.5https://github.com/joomla/joomla-cms/compare/3.6.4...3.6.5?expand=1But I can't see any change that can cause such issue :(Can you reproduce this issue using a clean install of 3.6.5? And an update from 3.6.4 -> 3.6.5 (without akeeba)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.    ----I'm on a roadCall or vibe me:+375 (29) 561-91-12

**Comment by PhilETaylor** [comment]
What exact PHP versions? some session changes have been made in PHP 7.1

**Comment by alex7r** [comment]
@PhilETaylor PHP 7.0 on both installations.
Also could PHP version even be a reason? I mean there was no PHP version update between working/not working moment.

**Comment by mbabker** [comment]
If it were PHP 7.1, yes that could be related as there were a few session RFCs that passed and merged to that branch.  Otherwise after the changes in 5.4 the PHP session extension hadn't changed much.

And FWIW we have this same configuration on https://downloads.joomla.org and from what I can see there has been no issue with it.

**Comment by PhilETaylor** [comment]
PHP 7.1 session changes (along with Redis as a SaveHandler) has wasted my last 2 days ... I know lots more about sessions as a result :-( 

Do you have any values in your configuration.php for the cookie domain and path?

**Comment by alex7r** [comment]
```PHP
class JConfig {
	public $MetaAuthor = '1';
	public $MetaDesc = '***';
	public $MetaKeys = 'joomla, Joomla';
	public $MetaRights = '';
	public $MetaTitle = '1';
	public $MetaVersion = '0';
	public $access = '1';
	public $cache_handler = 'file';
	public $cachetime = '15';
	public $caching = '0';
	public $captcha = '0';
	public $cookie_domain = '.';
	public $cookie_path = '/';
	public $db = '***';
	public $dbprefix = '***';
	public $dbtype = 'mysqli';
	public $debug = '0';
	public $debug_lang = '0';
	public $display_offline_message = '1';
	public $editor = 'tinymce';
	public $error_reporting = 'default';
	public $feed_email = 'none';
	public $feed_limit = '10';
	public $force_ssl = '0';
	public $fromname = '***';
	public $ftp_enable = '0';
	public $ftp_host = '';
	public $ftp_pass = '';
	public $ftp_port = '21';
	public $ftp_root = '';
	public $ftp_user = '';
	public $gzip = '0';
	public $helpurl = 'https://help.joomla.org/proxy?keyref=Help{major}{minor}:{keyref}&lang={langcode}';
	public $host = 'localhost';
	public $lifetime = '15';
	public $list_limit = '20';
	public $live_site = '';
	public $log_path = '***';
	public $mailer = 'mail';
	public $mailfrom = '***';
	public $memcache_compress = '0';
	public $memcache_persist = '1';
	public $memcache_server_host = 'localhost';
	public $memcache_server_port = '11211';
	public $offline = '0';
	public $offline_image = '';
	public $offline_message = 'This site is down for maintenance.<br /> Please check back again soon.';
	public $offset = 'UTC';
	public $offset_user = 'UTC';
	public $password = '***';
	public $robots = '';
	public $secret = '***';
	public $sef = '1';
	public $sef_rewrite = '1';
	public $sef_suffix = '0';
	public $sendmail = '/usr/sbin/sendmail';
	public $session_handler = 'database';
	public $sitename = '***';
	public $sitename_pagetitles = '0';
	public $smtpauth = '0';
	public $smtphost = 'localhost';
	public $smtppass = '';
	public $smtpport = '25';
	public $smtpsecure = 'none';
	public $smtpuser = '';
	public $tmp_path = '***';
	public $unicodeslugs = '0';
	public $user = '***';
	public $cache_platformprefix = '0';
	public $memcached_persist = '1';
	public $memcached_compress = '0';
	public $memcached_server_host = 'localhost';
	public $memcached_server_port = '11211';
	public $redis_persist = '1';
	public $redis_server_host = 'localhost';
	public $redis_server_port = '6379';
	public $redis_server_auth = '';
	public $redis_server_db = '0';
	public $proxy_enable = '0';
	public $proxy_host = '';
	public $proxy_port = '';
	public $proxy_user = '';
	public $proxy_pass = '';
	public $mailonline = '1';
	public $massmailoff = '0';
	public $session_memcache_server_host = 'localhost';
	public $session_memcache_server_port = '11211';
	public $session_memcached_server_host = 'localhost';
	public $session_memcached_server_port = '11211';
	public $frontediting = '1';
	public $asset_id = '1';
```

**Comment by PhilETaylor** [comment]
remove the / in 

> `public $cookie_path = '/';`

**Comment by PhilETaylor** [comment]
and remove the . in the 

> `public $cookie_domain = '.';`

**Comment by PhilETaylor** [comment]
@Kubik-Rubik One for you to laugh at following https://twitter.com/viktorvogel/status/815927595535597568

**Comment by alex7r** [comment]
Ok, this fixes the problem.
But according to the tips it should work with "." and "/" configurations, shouldn't it?

**Comment by PhilETaylor** [comment]
> But according to the tips

What tips? The web is full of "so called experts" and bad advice. 

Best practice is never to set these unless you 

1) Know what you are doing
2) Know why you are doing it
3) Know exactly what it means 
4) Know exactly what it will break.

**Comment by alex7r** [comment]
Joomla tips.
https://yadi.sk/i/f8Fpzzd736j8hj
https://yadi.sk/i/lWNJQbjx36j99A

**Comment by PhilETaylor** [comment]
"Preceed" meaning  https://en.oxforddictionaries.com/definition/precede

Therefore a valid value with a preceeding period would be

`.example.com`

Not simply putting a period like you did.

**Comment by alex7r** [comment]
OK, my bad. Didn't pay attention to it.

But I believe this tip can be improved, maybe with `example.com`, or by passing domain from JURI to JText.
