### ISSUE TITLE
System language Code Plugin

### ISSUE THREAD

**Issue by senolv** [joomla/joomla-cms#13445]
### Steps to reproduce the issue
Installation on localhost xampp - zip-data
configurations made in 3 stepps over \localhost\joomla\
install languages - ok
some configs for languages in 2 steps;
Step 2 choose default language - third field - Enable the language code plugin - set to yes (enable)

After installation - go to backend - plugins

### Expected result

language code plugin should be active

### Actual result
it is not :smile: 

### System information (as much as possible)
anything up-to-date

**Comment by infograf768** [comment]
The languagecode plugin can be enabled during joomla installation only when activating multilanguage.

**Comment by infograf768** [comment]
As it is now, the field should not show in that case in staging, but it does. Making a patch now.

**Comment by infograf768** [comment]
Please test on staging after patching with https://github.com/joomla/joomla-cms/issues/13450

**Comment by senolv** [comment]
Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13445">issues.joomla.org/tracker/joomla-cms/13445</a>.</sub>

**Comment by rdeutz** [comment]
closing because we have a PR
