### ISSUE TITLE
[3.7] Wrong Alignment in Menu > Link Type > Link Image

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#13454]
### Steps to reproduce the issue
![bildschirmfoto 2017-01-03 um 08 31 29](https://cloud.githubusercontent.com/assets/8235763/21601904/82730426-d18f-11e6-831c-6f212be9ad17.JPG)
### System information (as much as possible)
Joomla! 3.7.0-alpha1
PHP 7.0.4
MySQLi 5.5.53-0+deb7u1
Firefox 50.1.0, Chrome 55.0, Safari 10.0.2
macOS 10.12.2

**Comment by tonypartridge** [comment]
Hello,

I cannot re-create this. Did you clear your browsers cache and also can you try with alpha2? 
![screen shot 2017-01-03 at 21 05 31](https://cloud.githubusercontent.com/assets/1400982/21623077/9f16f664-d1f8-11e6-9ec4-2e6e40dc67d1.jpg)

Many thanks
Tony

**Comment by zero-24** [comment]
Where do you add that field? In the frontend?

**Comment by tonypartridge** [comment]
@zero-24 

From the title it is:
Backend -> Menu Items -> Edit Menu Item -> Link Type

But I cannot recreated.

**Comment by franz-wohlkoenig** [comment]
Sorry @tonypartridge and @zero-24, i found now out this behaviour is caused by k2.
