### ISSUE TITLE
Extensions manager Refresh Cache button not working

### ISSUE THREAD

**Issue by xpallicer** [joomla/joomla-cms#13459]
### Steps to reproduce the issue

Navigate to administrator/index.php?option=com_installer&view=manage. Edit a extension xml file to change version number. Select the extension and click the Refresh Cache button.

### Expected result

Extension info gets updated.

### Actual result

Nothing happens

### System information (as much as possible)

joomla 3.5

**Comment by Bakual** [comment]
> joomla 3.5

Can you please verify that with Joomla 3.6.5.
Using current staging, I can't reproduce this issue.

**Comment by xpallicer** [comment]
Sorry,

I didn't test properly. It is working correctly.
