### ISSUE TITLE
JForm Required field message placement

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#13453]
More of a question than an issue for the JForm experts. 

When using a super long form JForm client side validation shots you to the top of the page displaying an error message required field in the system messages container.

IS there a way out of the box to append the message to a field individually? Obviously I can do this via JS on a per field basis, but ideally it would be great if Joomla! allowed this and I'm just not seeing how to add it or override it.

**Comment by PhilETaylor** [comment]
This is not the place for support. Please post to the Joomla Forums.

**Comment by tonypartridge** [comment]
As always a helpful response from your phil.

It's more of an issue if it doesn't exist hence the question since I cannot find the functionality and thus don't believe it to exist. Which then becomes and issue for discussion. 

Unless you have something helpful to add, please do not comment on my issues.

**Comment by PhilETaylor** [comment]
The ISSUES section of Github is NOT for support - you will get the same answer from others.

**Comment by zero-24** [comment]
There is no way I know to do this without custom JS.

Please move that kind of questions to the forum, the Google Group (https://groups.google.com/forum/m/#!forum/joomla-dev-cms) or the Joomla Stackexchange (http://joomla.stackexchange.com/)
Thanks 👍

**Comment by tonypartridge** [comment]
I am not asking for support Phillip and never would on a github issues, I am asking if the Joomla! Code base supports a method. I cannot see it does and wish for clarification of people who know the CMS better than myself. 

If it does not exist then it is upfor discussion to be added.

If it does exist then we need to document it which I am happy to do once I know if it exists.

Again helping the project. Your reply is negative and to reply with such a response to myself who has been contributing to the project and fully understand what GitHub is for is just provocative. 

I won't be responding to anymore of your comments.

**Comment by tonypartridge** [comment]
@zero24 I know how to do it with JS thanks.

So it's up for discussion then, should it be added to the core? With long forms, adding it to the top of the page is certainly a very poor UX and not at all helpful.

**Comment by tonypartridge** [comment]
@zero-24 thanks for your helpful responses, always nice when someone else is helpful. 

I've implemented it in a ruff way only valid for the form I am doing it with. But I'll put it to the UX team for discussion in J4UX then :-). 

Thanks again @zero-24 for clarification.

**Comment by dgt41** [comment]
@tonypartridge the current validation script in the isValid function checks the value against a regEx and returns either true or false. Even if you add an extra check for null (before that function), you still have only 3 possible outcomes for the end user:
- is required but is empty
- the data is not valid
- the data is valid
 
And then there is the other B/C problem: if you want to append a message (lets say under the input) you have to do it with Bootstrap 2 notation and that will break for anyone using BS3 or another framework. No easy solution here I'm afraid, but we'll tap this in J4 (hopefully)

**Comment by zero-24** [comment]
> But I'll put it to the UX team for discussion in J4UX then :-).

:+1:

**Comment by tonypartridge** [comment]
@dgt41 perfect, thank you the exact response I was expecting to get. I'll follow up in the J4UX repo.

**Comment by dgt41** [comment]
@tonypartridge is there a J4UX repo or you are referring to the template one?

**Comment by tonypartridge** [comment]
@dgt41 the template one, sorry for the confusion.
