### ISSUE TITLE
Media Manager - Multiple IDs

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#13474]
### Steps to reproduce the issue
Navigate to Media Manager and inspect toolbar buttons.

### Expected result
Unique IDs on each button (containing div)

### Actual result
Buttons using the same ID (toolbar-upload)

### System information (as much as possible)
3.7

### Additional comments
No apparent consequences however would be considered bad practice.

**Comment by andrepereiradasilva** [comment]
> No apparent consequences however would be considered bad practice.

And an HTML error IIRC

**Comment by Bakual** [comment]
Closing as we have a PR: #13477
