### ISSUE TITLE
Styling issue in image modal

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#13489]
### Steps to reproduce the issue
With current staging and current firefox: from TinyMce-Editor open the image modal. It will looks like this:
![joomla37_image_modal](https://cloud.githubusercontent.com/assets/9270310/21718734/9bb43932-d419-11e6-8cbc-8ded337c16b0.png)

**Comment by franz-wohlkoenig** [comment]
Got this:
![bildschirmfoto 2017-01-06 um 14 30 22](https://cloud.githubusercontent.com/assets/8235763/21719228/d9215216-d41c-11e6-87c3-c7238e0c5493.JPG)
### System Informations
Joomla! 3.7.0-alpha2 | PHP 7.0.4 | MySQLi 5.5.53-0 | Firefox 50.1.0 | macOS Sierra 10.12.2

**Comment by waader** [comment]
I forgot to mention that I did test under Win7. Maybe that makes the difference.

**Comment by jeckodevelopment** [comment]
@waader you should include some system information.
Which version of Joomla! are you using?

**Comment by PhilETaylor** [comment]
@jeckodevelopment he said: 
>Joomla! 3.7.0-alpha2

**Comment by waader** [comment]
As I wrote I am using current staging. System informations shows indeed Joomla! 3.7.0-alpha2 dev. Also php 5.6.25 (only for testing), mysql 5.6.31, apache 2.4.23, firefox 50.1. Operating system is Win7.

**Comment by ciar4n** [comment]
A Bootstrap 'well' is not designed to contain a grid which is the case in the image modal. The well padding causes the spans to wrap to a second line.

**Comment by ciar4n** [comment]
This issue can be closed as it is resolved with #13845
