### ISSUE TITLE
 Notice: Undefined property: stdClass::$showon

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#13487]
### Steps to reproduce the issue
With current staging go to Content > Articles > Options and you will get this notice error:

 Notice: Undefined property: stdClass::$showon in ...joomla37\administrator\components\com_config\view\component\tmpl\default.php on line 60

**Comment by Bakual** [comment]
@andrepereiradasilva Related to https://github.com/joomla/joomla-cms/pull/13476?

**Comment by joomdonation** [comment]
Yes. it is related. Reverted that PR and the notice is gone. Didn't test that yesterday, sorry

**Comment by joomdonation** [comment]
@andrepereiradasilva Changes the code in this line https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_config/view/component/tmpl/default.php#L60 to 

```php
<?php if (!empty($fieldSet->showon)) : ?>
```

seems solve the issue

However, do we really need this block of code https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_config/view/component/tmpl/default.php#L60-L64 ? Are we support show on for fieldsets, too ?

**Comment by andrepereiradasilva** [comment]
See https://github.com/joomla/joomla-cms/pull/13490

**Comment by jeckodevelopment** [comment]
Closing as we have a PR for that.
Please test #13490
