### ISSUE TITLE
Default admin backend / Administrator language ignored

### ISSUE THREAD

**Issue by kofaysi** [joomla/joomla-cms#13484]
### Steps to reproduce the issue

* install Czech or Hungarian languages for frontend and backend
* set site and Administrator language to default different from English
* make sure your admin account or other administration login account have "default" Administrator language enabled
* log out, clear caches, log in

The same behavior is experienced when 
* your admin account or other Administrator login account have "different-from-English" Administrator language enabled

### Expected result

Administrator language will be non-English.

### Actual result

Administrator language is still English.

### System information (as much as possible)
PHP Built On 	Linux h90-w15.hosting90.cz 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64
Database Version 	5.5.52-MariaDB
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.0.14
Web Server 	Apache/2.4.6 (CentOS) mpm-itk/2.4.7-01
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0 

### Additional comments

The Administratior language can be switched by
* choosing specific language at the login window
* selecting language and applying "Switch languages" command at Extensions > Languages > Installed > Administrator

**Comment by kofaysi** [comment]
The same issue a year ago described here: https://forum.joomla.org/viewtopic.php?t=904639<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13484">issues.joomla.org/tracker/joomla-cms/13484</a>.</sub>

**Comment by zero-24** [comment]
hmm i can not confirm any kind of issues:

![image](https://cloud.githubusercontent.com/assets/2596554/21722518/4763f084-d42d-11e6-84a7-74aef1042705.png)

Can you please confirm this issue on a clean install without any 3rd Party Extensions?

**Comment by kofaysi** [comment]
Yeap, I confirm this issue on a clean install without any 3rd party extension. Well, to be true there is one: Czech language v3.6.5.1 dated 2016-12-14 by the Joomla! Czech Translation Team admin@joomla.cz id#10000.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13484">issues.joomla.org/tracker/joomla-cms/13484</a>.</sub>

**Comment by zero-24** [comment]
Can you show us a screenshot of the backend with the default star? Can you double check the dropdown left to the seach box Is this "Administrator" or Site?

**Comment by kofaysi** [comment]
I'm uploading three screenshots:
* after changing the administrator language
* (after logging off and logging in) the settings for the admin account
* the settings for the administrator language again

![screen shot 2017-01-15 at 13 24 57](https://issues.joomla.org/uploads/1/df1c2dbe3df81b2682cc95e2ce1e0994.png)![screen shot 2017-01-15 at 13 24 57](https://issues.joomla.org/uploads/1/4965be31294840905a0bde0285cdd35f.png)![screen shot 2017-01-15 at 13 24 57](https://issues.joomla.org/uploads/1/1f53808ded696aa129e2a9bb379ecb4c.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13484">issues.joomla.org/tracker/joomla-cms/13484</a>.</sub>

**Comment by zero-24** [comment]
hmm this sounds strange. Can you please enable the language debug and told me if you have any errors reported there?

**Comment by kofaysi** [comment]
Debugging has been allowed. All the commands are surrounded by double-asterisks. The debug report is attached.![screen shot 2017-01-15 at 15 21 10](https://issues.joomla.org/uploads/1/7c970105ab876fa2d7c093c001769007.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13484">issues.joomla.org/tracker/joomla-cms/13484</a>.</sub>

**Comment by kofaysi** [comment]
That is unexpected: The login window is in Czech, but after login in, the administrator site is in English.![screen shot 2017-01-17 at 14 07 29](https://issues.joomla.org/uploads/1/740016c994a58bb3ef19d7dbb89db193.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13484">issues.joomla.org/tracker/joomla-cms/13484</a>.</sub>

**Comment by zero-24** [comment]
@kofaysi can you send me a backup with the problem (zip + database) to tobias.zulauf<at>community.joomla.org ? I still can not replicate this issue on my side.

**Comment by kofaysi** [comment]
@zero-24 Hi, the e-mail address tobias.zul at community.joomla.org is not responding (undelivery message). May I install Akeeba Backup and send you the jpa backup file? Is there any user to user chat on GitHub?

**Comment by zero-24** [comment]
> the e-mail address tobias.zul at community.joomla.org is not responding

tobias.zulauf<at>community.joomla.org you missed some thing from my seccound name.

>  May I install Akeeba Backup and send you the jpa backup file? 

please don't do that. Just a zip with the files and the DB dump.

**Comment by franz-wohlkoenig** [comment]
Can't confirm, test on Multilingual Site (4 Lang.). Changed to french in Back- and Frontend, made Steps to reproduce issue – all works fine.
#### Test on:
Joomla! 3.7.0-latest staging
macOS Sierra, 10.12.3
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by zero-24** [comment]
This is how it looks like for me on my server (using a restored backup provided by @kofaysi ):
![cz_backend](https://cloud.githubusercontent.com/assets/2596554/22629663/97a4d1f6-ebea-11e6-9665-0d8e3394fd49.gif)

So for me it looks like a server or browser issue i can't understand :(

**Comment by kofaysi** [comment]
After disabling and re-enabling all the extension in my Firefox profile, the suspicious behavior vanished. No user change has been made to any of the extensions or their setting.

**Comment by infograf768** [comment]
Shall we therefore consider this as solved? If yes, please close this issue.

**Comment by kofaysi** [comment]
The KeeFox plugin is blocking the language switching. Disabling the plugin, restarting the browser, logging off and on, displays the Administrator site (backend) in chosen language.

Thank you all for participating and pushing me towards trying to debug differently.
