### ISSUE TITLE
[3.7] Breadcrumbs float if "Advances Search" is clicked & "Search Terms" empty

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#13486]
#### Menu Item Type "Search" without "Advanced Search" clicked:
![1](https://cloud.githubusercontent.com/assets/8235763/21716401/9b1bc486-d40a-11e6-905c-65e27c714157.JPG)
#### Menu Item Type "Search" with "Advanced Search" clicked:
![2](https://cloud.githubusercontent.com/assets/8235763/21716420/b1402cb6-d40a-11e6-9c6f-7892dafb2d95.JPG)
### Expected result
Breadcrumbs-Module stay in Position
### System information
Joomla! 3.7.0-alpha2 | PHP 7.0.4 | MySQLi 5.5.53-0 | Firefox 50.1.0 | macOS Sierra 10.12.2

**Comment by Bakual** [comment]
See https://github.com/joomla/joomla-cms/pull/13488
