### ISSUE TITLE
Call to a member function setFieldAttribute()

### ISSUE THREAD

**Issue by alexgru** [joomla/joomla-cms#13496]
### Steps to reproduce the issue
Example code:
```php
            $regmodel = $this->getModel('Registration', 'UsersModel');
            $regdata = array(
                "name" => $data['name'],
                "username" => $data['username'],
                "password2" => $data['password2'],
                "password1" => $data['password1'],
                "email1" => $data['email1']
            );
            $return_uid = $regmodel->register($regdata);
```
### Expected result
true

### Actual result
Fatal error: Call to a member function setFieldAttribute() on boolean in components\com_users\models\registration.php on line 307

### System information (as much as possible)
Start at version Joomla CMS 3.6.5

### Additional comments

When I create a custom registration form with multi languages support I have this error.
Error only in latest version Joomla CMS 3.6.5 and only with multi languages support.
I think problem with this code(file components\com_users\models\registration.php):
a)Line 245
```php
$form = $this->getForm(array(), false);
```
b)Line 305 - 308
```php
if (JLanguageMultilang::isEnabled())
		{
			$form->setFieldAttribute('language', 'type', 'frontend_language', 'params');
		}
```

Sorry for my English !

**Comment by joomdonation** [comment]
Hi

This issue was fixed with this PR https://github.com/joomla/joomla-cms/pull/13472 and will be available in Joomla 3.7.0
