### ISSUE TITLE
Mssql: Preview and Compare in Article Versions do not work

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#13507]
### Steps to reproduce the issue
You are getting several warning like this one:
Warning: Invalid argument supplied for foreach() in joomla37\administrator\components\com_contenthistory\helpers\contenthistory.php on line 32

**Comment by RonakParmar** [comment]
@waader Please provide more information to reproduce this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13507">issues.joomla.org/tracker/joomla-cms/13507</a>.</sub>

**Comment by zero-24** [comment]
#13534 closing please provide the test instructions in the PR thanks 👍
