### ISSUE TITLE
Mssql: error when creating a category on the fly

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#13506]
### Steps to reproduce the issue
Go to an article and create a category on the fly. You should get this error:
515 [Microsoft][SQL Server Native Client 11.0][SQL Server]Cannot insert the value NULL into column 'description', table 'joomla35.dbo.#__categories'; column does not allow nulls. INSERT fails.

**Comment by andrepereiradasilva** [comment]
similar solution to https://github.com/joomla/joomla-cms/issues/13510

**Comment by waader** [comment]
These fields need default values in order to make this work for mssql:

	[description] [nvarchar](max) NOT NULL DEFAULT '',
	[params] [nvarchar](max) NOT NULL DEFAULT '',
	[metadesc] [nvarchar](1024) NOT NULL DEFAULT '',
	[metakey] [nvarchar](1024) NOT NULL DEFAULT '',
	[metadata] [nvarchar](2048) NOT NULL DEFAULT '',

**Comment by andrepereiradasilva** [comment]
yes we need to make a similair PR of https://github.com/joomla/joomla-cms/pull/13513 but for the `#__categories` table.

**Comment by andrepereiradasilva** [comment]
working on it

**Comment by andrepereiradasilva** [comment]
please test https://github.com/joomla/joomla-cms/pull/13514
