### ISSUE TITLE
Mssql: Syntax error when installing a language in backend

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#13508]
### Steps to reproduce the issue
You will get:
[Microsoft][SQL Server Native Client 11.0][SQL Server]Incorrect syntax near the keyword 'use'.

**Comment by zero-24** [comment]
do you have the failing SQL query?

**Comment by waader** [comment]
Most likely it is this query:

SELECT [us].[location]
   FROM [jz8km_extensions] AS [e]
   LEFT JOIN [jz8km_update_sites_extensions] AS [use] 
  ON use.extension_id = e.extension_id
   LEFT JOIN [jz8km_update_sites] AS [us] 
  ON us.update_site_id = use.update_site_id

Reason is, that use is a reserved word.

**Comment by andrepereiradasilva** [comment]
and that why we always need to quote the db fields 😉

**Comment by andrepereiradasilva** [comment]
https://github.com/joomla/joomla-cms/pull/13512

**Comment by zero-24** [comment]
Thanks
