### ISSUE TITLE
Mssql: Adding a tag doesn´t work

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#13509]
### Steps to reproduce the issue
On saving a new tag you get:
515 [Microsoft][SQL Server Native Client 11.0][SQL Server]Cannot insert the value NULL into column 'term_id', table 'joomla35.dbo.#__finder_tokens_aggregate'; column does not allow nulls. INSERT fails.

**Comment by andrepereiradasilva** [comment]
similar solution to https://github.com/joomla/joomla-cms/issues/13510

**Comment by andrepereiradasilva** [comment]
i have submitted a PR to normalize finder tables.
Please test https://github.com/joomla/joomla-cms/issues/13517
