### ISSUE TITLE
Mssql: Adding a tag to a catetory fails with an error

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#13510]
### Steps to reproduce the issue
You will get:
515 [Microsoft][SQL Server Native Client 11.0][SQL Server]Cannot insert the value NULL into column 'core_xreference', table 'joomla35.dbo.#__ucm_content'; column does not allow nulls. INSERT fails.

**Comment by andrepereiradasilva** [comment]
this https://github.com/joomla/joomla-cms/blob/staging/installation/sql/sqlazure/joomla.sql#L2883 needs a defaultt value.
Similiar to this one https://github.com/joomla/joomla-cms/pull/13035/files (in this case was mysql).

bottom line is **all db systems** (mysql, postgresql, sqlazure) need to have a default value in the db table columns when they are set as `NOT NULL`, normally `DEFAULT ''` for strings and `DEFAULT 0` for integers.

What needs to be done in this cases:
- Add the default value to the joomla.sql installation file for each of the 3 database systems (if they all need)
- Add 1 update files for each of the 3 database systems (if they all need)

This particular case:
- sqlazure (**NOT OK**): https://github.com/joomla/joomla-cms/blob/staging/installation/sql/sqlazure/joomla.sql#L2883
- mysql (**NOT OK**): https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/joomla.sql#L1821
- postgresql (**OK**): https://github.com/joomla/joomla-cms/blob/staging/installation/sql/postgresql/joomla.sql#L1738

So you need to change the mysql and sqlazure joomla.sql file to have `DEFAULT ''` in the core_xreference and make update sqls for mysql and sqlzaure.

**Comment by waader** [comment]
Thanks for your explanation: With this default value it would work:
	[core_xreference] [nvarchar](50) NOT NULL DEFAULT '',

**Comment by andrepereiradasilva** [comment]
Please test https://github.com/joomla/joomla-cms/pull/13513
