### ISSUE TITLE
email cloaking problem within introtext

### ISSUE THREAD

**Issue by jsubri** [joomla/joomla-cms#13522]
### Steps to reproduce the issue
- Add an "Articles Category" module on the sample site
- Under "Display Options" tab: everything on Hide, except "Introtext= show" and "Show Read More=show"
- Create an article with the below html:
```
<p>Intro text <a href="mailto:sample@example.com">sample@example.com</a> - more more more</p>
<hr id="system-readmore" />
<p><br />Paragraph 1<br />1<br />2<br />3<br />4<br />5</p>
<p>Paragraph 2<br />1<br />2<br />3<br />4<br />5</p>
<p>Paragraph 3<br />1<br />2<br />3<br />4<br />5</p>
<p>End</p>
```
### Expected result
Introtext shows the email address

### Actual result
This email address is being protected from spambots. You need JavaScript enabled to... 

![capture](https://cloud.githubusercontent.com/assets/5349333/21753624/3d2fe40e-d5f1-11e6-9738-3be96abcd469.PNG)

### System information (as much as possible)
current staging and 3.6.5, older versions probably

### Additional comments
n/a

**Comment by dgt41** [comment]
@jsubri There a few things that make this functionality fail:
- The module will strip out span and script tags
- The length of the introtext is trimmed (removing vital javascript)

To make it work just replace https://github.com/joomla/joomla-cms/blob/staging/modules/mod_articles_category/helper.php#L325-L332 with:
```php
	public static function _cleanIntrotext($introtext)
	{
		$introtext = str_replace(array('<p>','</p>'), ' ', $introtext);
		$introtext = strip_tags($introtext, '<a><em><strong><span><script>');
		$introtext = trim($introtext);

		return $introtext;
	}
```
And increase the allowed characters (in my test case 1000)

![screen shot 2017-01-09 at 00 19 40](https://cloud.githubusercontent.com/assets/3889375/21754105/00dd7f5a-d602-11e6-98f2-c5f8ed62aa12.png)

And the million dollar question: can this be patched without this hack? 
- well someone needs to spend sometime, I guess

**Comment by jsubri** [comment]
Thank you for the workaround and yes $introtext is easily above 600 characters long.
Low priority anyway.

**Comment by PhilETaylor** [comment]
Does not this solution have security implications in so much as now the _cleanIntrotext method would allow script to be output?

**Comment by dgt41** [comment]
@PhilETaylor I think I should redo https://github.com/joomla/joomla-cms/pull/11027, will make patching this a lot easier (but I don't remember the reason we end up reverting it in the first place)

**Comment by jwaisner** [comment]
@jsubri Is this issue still present in the latest J3?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13522">issues.joomla.org/tracker/joomla-cms/13522</a>.</sub>

**Comment by jsubri** [comment]
I didn't checked recently, the workaround was good enough for me and I've advised my customer (NGO) to refrain adding email address in the introtext. Very high probability the javascript code is still present in the $introtext in current staging. I've not test with J4.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13522">issues.joomla.org/tracker/joomla-cms/13522</a>.</sub>

**Comment by ReLater** [comment]
> Is this issue still present in the latest J3?

Yes.

**Comment by ReLater** [comment]
Is this issue still present in latest Joomla **4** ?

Yes.

**Comment by brianteeman** [comment]
This is a bug that should be fixed in J3

**Comment by alikon** [comment]
please test #36602  for j4

**Comment by alikon** [comment]
still an issue on j3

**Comment by alikon** [comment]
the j3 pr #36603
