### ISSUE TITLE
[3.7] Less Margin-right on "New Category"-Lightbox

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#13529]
### Steps to reproduce the issue
Create from `Menus: Edit Item` a new Category (same at `Edit Category`):
![bildschirmfoto 2017-01-09 um 14 56 19](https://cloud.githubusercontent.com/assets/8235763/21768928/6a64a64a-d67c-11e6-998f-b804c31d0128.JPG)
### System information (as much as possible)
Joomla! 3.7.0-alpha2
macOS Sierra, 10.12.2
Firefox 50.1.0, Chrome 55, Safari 10.0.2
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by utkarshshukla2912** [comment]
i dont seem to understand the problem could you please explain me <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13529">issues.joomla.org/tracker/joomla-cms/13529</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Right Side of Lightbox (Parent, Staus, …) needs more Space.

**Comment by ciar4n** [comment]
At what screen resolution are you seeing this issue?

Navigating to Menus -> [Menu] -> New -> Category Blog -> Create...

![cat](https://cloud.githubusercontent.com/assets/2803503/21866374/db1d26f2-d841-11e6-9ebe-e3c29c22e1e7.png)

**Comment by franz-wohlkoenig** [comment]
It starts at 960 till 1100.

**Comment by utkarshshukla2912** [comment]
@franz-wohlkoenig @ciar4n where can i find the css code for this

**Comment by ciar4n** [comment]
@utkarshshukla2912 No specific css. Ideally the right column fields need to have a fluid width so they reduce in size when the space isn't available.

**Comment by utkarshshukla2912** [comment]
@ciar4n I guess making a change within the  **/joomla-cms/administrator/templates/isis/css/template.css**  shall rectify the problem

**Comment by utkarshshukla2912** [comment]
@ciar4n i do understand the fields need to be fluid type my problem is any changes i make is not at all reflected in the site

**Comment by ciar4n** [comment]
@utkarshshukla2912 You must edit the LESS files and then compile them. For details on compiling your LESS files in Joomla check out https://docs.joomla.org/Joomla_LESS

Note that there is already a merged PR fixing this issue  #13586

This issue can be closed!

**Comment by franz-wohlkoenig** [comment]
Issue resolved, thanks.
