### ISSUE TITLE
[com_fields] Batch Field Group does not display options 

### ISSUE THREAD

**Issue by cpfeifer** [joomla/joomla-cms#13533]
### Steps to reproduce the issue
Create 2 or more Field Groups
Create a few fields
Select Fields and click Batch

### Expected result
The created field groups should appear as options in the group batch selection dropdown

### Actual result
The created field groups do not appear as options in the group batch selection dropdown
![fields_batch_group](https://cloud.githubusercontent.com/assets/3790835/21784757/23f3bc3e-d67a-11e6-8510-e0b1f1004d71.png)

### System information (as much as possible)
Latest

**Comment by laoneo** [comment]
Calling @Bakual as this is another regression from #13019.

**Comment by Bakual** [comment]
See https://github.com/joomla/joomla-cms/pull/13538.
Closing this issue as we have a PR.

> Calling @Bakual as this is another regression from #13019.

@laoneo Actually it's a regression from #13175 :smile:

**Comment by laoneo** [comment]
Outch 😌
