### ISSUE TITLE
[3.7] "Global Articles Options" are hidden, if Frontend- or Administrator-"Images and Links" are set to "Hide"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#13531]
### Steps to reproduce the issue
In `Articles: Options` Images- and Links-Options are hidden, if `Frontend Images and Links` or `Administrator Images and Links` are hidden:
![1](https://cloud.githubusercontent.com/assets/8235763/21781611/831f3db0-d6b0-11e6-9433-58207e843f1c.JPG)
Only if both (Frontend and Administrator-Images and Links) are shown, Global Options are shown:
![2](https://cloud.githubusercontent.com/assets/8235763/21781659/bf5b2bae-d6b0-11e6-8a0a-2050000ce847.JPG)
### Expected result
Global Options are shown if Frontend- or Administrator-Images and Links set to `Hide`.
### System information (as much as possible)
Joomla! 3.7.0-alpha2
macOS Sierra, 10.12.2
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by jsubri** [comment]
For me this Editing Layout as a lot to do with "back end", the doc https://help.joomla.org/proxy/index.php?keyref=Help36:Components_Article_Manager_Options is mentioning at multiple occasion "back-end users will not be able...".
For example "Show Publishing Option = Hide" means displayed on front-end and hidden in back-end. Which was a surprise to me that front-end can do more than back-end with the same priv. The doc is somehow more verbose on the back-end than front-end behavior.

**Comment by frankmayer** [comment]
Don't know about the docs but there surely is an issue with showon. I am investigating.

**Comment by frankmayer** [comment]
Fixed (#13535)
