### ISSUE TITLE
Menu access levels - Please delete!

### ISSUE THREAD

**Issue by onlinemindgem** [joomla/joomla-cms#13530]
![screen shot 2017-01-09 at 11 16 20](https://issues.joomla.org/uploads/1/b5ba3278f4419193efb882da13712688.jpg)### Steps to reproduce the issue

1. Install clean Joomla 3.6.5
2. Publish a menu item to main menu with access level 'Guest'. For example a link to the login form
3. Login in frontend with your account
4. Notice the menu displaying correctly the menu without a link to the login form
5. Close all browser windows
6. Go back to your joomla installation frontend
7. Notice the menu containing a link to the login form

### Expected result

- Guest level respected in menu

### Actual result

- Guest links shown for registered users after returning to the website

### System information (as much as possible)

- Joomla 3.6.5
- PHP 7

### Additional comments

See screenshots

![screen shot 2017-01-09 at 11 16 22](https://issues.joomla.org/uploads/1/09735534d4600e03b31d2c2b86fb3634.jpg)

**Comment by Bakual** [comment]
Hmm, works fine for me so far.
Can you check what is set for the "Guest User Group" in the user manager options? Maybe there isn't "Guest" set?

**Comment by onlinemindgem** [comment]
I checked it and it is set to Guest.

Looking at my install I saw I have Jomsocial in this. 

Then I disabled the jomsocial 'User - Jomsocial User' plugin and everything is correct. So heading there again for a bug. 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13530">issues.joomla.org/tracker/joomla-cms/13530</a>.</sub>
