### ISSUE TITLE
Required attribute of optional user profile fields gets lost

### ISSUE THREAD

**Issue by joomlawatch** [joomla/joomla-cms#13536]
### Steps to reproduce the issue

Enalbe the plugin "User profile" 
Set address 1 to required

### Expected result

Address1 should be of class "required" having the required star (server side validation may also be corrected)

### Actual result

Address 1 is shown as optional

### System information (as much as possible)

Joomla! 3.6.5
php 5.6

**Comment by bertmert** [comment]
@joomlawatch 
I think this isuue is solved already (Joomla 3.7.0).
Could you please test https://github.com/joomla/joomla-cms/pull/13254
