### ISSUE TITLE
Showon broken for Plugins, Modules and Templates

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#13540]
### Steps to reproduce the issue
Try for example the reCaptcha plugin. The parameters should change when you switch between version 1.0 and 2.0.
For modules one could test the login module (show greeting) and for templates the protostar template (use Google font)

### Expected result
Available parameters change

### Actual result
Nothing happens.

### System information (as much as possible)
Current staging

### Additional comments
Pinging @andrepereiradasilva since there were recently some PRs merged from that deal with showon.

**Comment by Bakual** [comment]
Looks like a regression from https://github.com/joomla/joomla-cms/pull/13476.

**Comment by andrepereiradasilva** [comment]
yes it's a regression the showon json is now `data-showon="[{"field":"jform[version]","values":["1.0"],"sign":"=","op":""}]"` when it should be `jform[params][version]`

**Comment by Bakual** [comment]
Can you fix it?

**Comment by andrepereiradasilva** [comment]
not today. but i can have a look as soon as i have time.

**Comment by infograf768** [comment]
@rdeutz 
Can you mark this as Release Blocker?

**Comment by Bakual** [comment]
See #13549
