### ISSUE TITLE
Forgotten com_massmail ACL rule?

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#13551]
### Steps to reproduce the issue

In installation sql there is an com_massmail ACL rule.
https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/joomla.sql#L47

with `egrep -n -R "com_massmail" /path/to/joomla-staging/` didn't find any reference in the code base to this ACL rule ... also when i click option in "Mass mail users" it goes to com_users options/permissions.

So is this used anywhere? Or is just leftovers? Or is there a plan for this?

**Comment by zero-24** [comment]
hmm it is there since 02. Oct 2009: https://github.com/joomla/joomla-cms/commit/9de039f3a1508b00aa7c4d22598541284786e8ad -> the initial `new` ACL commit.

At this time there was a extension called com_massmail. Now we don't have that so i guess we can remove it.

**Comment by jajodiaraghav** [comment]
Should the 'id' of the rules following com_massmail be decremented by one?

**Comment by wilsonge** [comment]
Closing here as we have a PR with #13587
