### ISSUE TITLE
[com_admin] System info fail

### ISSUE THREAD

**Issue by n3t** [joomla/joomla-cms#13552]
### Steps to reproduce the issue
This is specific configuration issue.
Setup your site as following example
HTTP Root: /var/www/site1/
Images: /var/images
create symlink /var/www/site1/images pointing to /var/images
Setup PHP open basedir restriction: /var/www/site1/:/var/images/

Open System info in Joomla Administration.

### Expected result
See System info

### Actual result
```
SplFileInfo::isDir(): open_basedir restriction in effect. File(/var/www/site1/images/..) is not within the allowed path(s): (/var/www/site1/:/var/images/:)
```
### System information (as much as possible)
PHP 7.0.13, Linux system

**Comment by n3t** [comment]
Pull request https://github.com/joomla/joomla-cms/pull/13553

Sorry for duplication, I didn't realize that pull request will create also issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13552">issues.joomla.org/tracker/joomla-cms/13552</a>.</sub>

**Comment by zero-24** [comment]
No Problem
