### ISSUE TITLE
[com_fields] Checkboxes/List/Radio fields merge options from plugin with field params

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#13558]
### Steps to reproduce the issue
* Set some "Radio Values" in the "Fields - Radio" plugin. Eg like this:
![radio](https://cloud.githubusercontent.com/assets/1018684/21841665/80a325f4-d7e3-11e6-9b16-47ac4ec552df.PNG)
* Create a new radio field and set some Radio Values there as well. Eg
![radio2](https://cloud.githubusercontent.com/assets/1018684/21841712/b802b488-d7e3-11e6-985a-6cadb2f3b35e.PNG)
* Edit an article and check the radio field options
![radio3](https://cloud.githubusercontent.com/assets/1018684/21841731/d932fc3a-d7e3-11e6-8276-601d62ca56d2.PNG)

### Expected result
Personally I would expect the settings from the field override the ones from the plugin, getting a radio with only "Foo" in my case.

### Actual result
The values from the field and plugin are merged together, resulting in three options (No, Yes, Foo).

### System information (as much as possible)
Current staging

### Additional comments
Of course this is somewhat a subjective view based on what the use case will be.
I imagined one would create generic Yes/No values in the plugin options which will fit for most radio (checkboxes and list) fields. If I need a field with different options I can then just specify them in the field and replace the ones from the plugin.

Pinging @laoneo

**Comment by utkarshshukla2912** [comment]
i didn't the error could you please help me out with this
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13558">issues.joomla.org/tracker/joomla-cms/13558</a>.</sub>

**Comment by laoneo** [comment]
Honestly I prefer the way it is done now, merging the options. But if people expect it differently, then I'm up to change it.

**Comment by Bakual** [comment]
See #13578 for the PR.

Closing this issue as there is a PR.
