### ISSUE TITLE
Missing Buttons on Editing User (Buttons missing Save - Save & Close -  Save & New

### ISSUE THREAD

**Issue by Redsystemsplus** [joomla/joomla-cms#13562]
### Steps to reproduce the issue
![joomla missing save buttons2](https://cloud.githubusercontent.com/assets/25059195/21853472/8cd3dcea-d817-11e6-9be1-fc8213f1b9e9.jpg)

### Expected result
![joomla missing save buttons](https://cloud.githubusercontent.com/assets/25059195/21853370/1c4046f8-d817-11e6-85b9-0fd5c8ef93ce.jpg)

The other site is working fine.

### Additional comments

Many thanks.

**Comment by zero-24** [comment]
can you please disable all 3rdparety extensions (e.g. plugins) What happen if you set the error reporting to maximum?

**Comment by Redsystemsplus** [comment]
Hi zero-24,  I disabled all plug-ins and tested each.  It appears the "USER - UE Man" plugin is causing the error.

Thank you so much :)
