### ISSUE TITLE
Proper setting of margins 

### ISSUE THREAD

**Issue by utkarshshukla2912** [joomla/joomla-cms#13579]
### Steps to reproduce the issue
installing the akeeba backup plugin -> create a backup -> after the backup is made -> manage backup -> popup of "how do i restore my backup" 

### Expected result
proper left margin needs shifting of the left margin ![screen shot 2017-01-12 at 15 57 57](https://issues.joomla.org/uploads/1/2fb3eac28bb9c1bf422bf5ef607aa29e.png)

**Comment by infograf768** [comment]
Akeeba is not part of core. Please contact them.
