### ISSUE TITLE
Warning Error Messages on front end of website in Joomla 3.6.3

### ISSUE THREAD

**Issue by adjd82016** [joomla/joomla-cms#13577]
### Steps to reproduce the issue
After installing Mobile Joomla extensions and plugins, DSC (mobile extension), Mobile extension - All free versions - and attempting an Akeeba backup in Mozilla Firefox (which failed) and in Internet Explorer (which failed as well) - The following error messages are displaying. The attached screen snipit of the error message displays on the front end interface. 
Please advise what the correct fix is for this issue. I am new to Joomla and would like this to be something that is easily resolved. 

Best Regards, 

April ![screen shot 2017-01-12 at 09 01 31](https://issues.joomla.org/uploads/1/bab414782090c25378f465e4748569a6.jpg)

**Comment by utkarshshukla2912** [comment]
@adjd82016 didn't see the error in safari/chrome could you please tell me some other way to reproduce the issue

**Comment by bertmert** [comment]
@adjd82016 
In my opinion the combination of 1) insecure and outdated Joomla version, 2) warning texts, 3) line numbers and mentioned file (framework.php) look like your site has been hacked.

**Comment by wilsonge** [comment]
As has been said. That file is critical for the entire of Joomla to run. Without it nothing is going to happen. I would agree with @bertmert that there's a decent probability your site has been hacked - note there are multiple critical vulnerabilities in 3.6.3 (https://www.joomla.org/announcements/release-news/5678-joomla-3-6-4-released.html). If you need support the best place for you to go is the forum http://forum.joomla.org/ and posting there. There are lots of site administrators there who will be in a better position to help you :)
