### ISSUE TITLE
Searched item highlighted isn't always highlighted properly in search results

### ISSUE THREAD

**Issue by izzzy12k** [joomla/joomla-cms#13580]
Do a search via the search tool on a site and the highlighted word in the search results is always highlighted properly.. it's off by one character.

but it only seems to happen on certain words, not sure if it's due to length.

it's not affected by browser, got the same issue with IE and Firefox.

I attached a screenshot. (please excuse the content bluring)

**Comment by izzzy12k** [comment]
screenshot![screen shot 2017-01-12 at 19 44 58](https://issues.joomla.org/uploads/1/ab002b71bc985fba5dca260a8eda7915.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13580">issues.joomla.org/tracker/joomla-cms/13580</a>.</sub>

**Comment by jsubri** [comment]
Test patch https://github.com/joomla/joomla-cms/pull/13498

**Comment by jeckodevelopment** [comment]
Closed since we have a patch for this.
Please test #13498
