### ISSUE TITLE
[com_fields] In "Show User Custom Field" only "All"-Groups selectable

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#13595]
### Steps to reproduce the issue
"Contacts: Edit" > Tab "Display": Field "Show User Custom Field": Only "All"-Groups are selectable.
### Expected result
Select one, more or all Field Groups.
### System information (as much as possible)
Joomla! 3.7.0-alpha2-nightly
macOS Sierra, 10.12.2
Firefox 50.1.0, Chrome 55, Safari 10.0.2
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by laoneo** [comment]
Please test pr #13607. Guess this issue can be closed.
