### ISSUE TITLE
[com_fields] Type "List" missing in Dropdown

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#13599]
### Steps to reproduce the issue
Create new Field, in "Type" no "List" is shown (there are 15 Types):
![11](https://cloud.githubusercontent.com/assets/8235763/21963273/1e8ce848-db38-11e6-862b-133c5901727d.JPG)
In "Extensions > Plugins" between "Integer" and "Media" is "Fields - List" (there are 16 Fields - *)
![12](https://cloud.githubusercontent.com/assets/8235763/21963275/2141b9b0-db38-11e6-89cb-6b7ca0eaa687.JPG)
### System information (as much as possible)
Joomla! 3.7.0-alpha2-nightly
macOS Sierra, 10.12.2
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by infograf768** [comment]
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13599">issues.joomla.org/tracker/joomla-cms/13599</a>.</sub>

**Comment by Bakual** [comment]
PR is already open to fix that: https://github.com/joomla/joomla-cms/pull/13546

Closing as there is a PR
