### ISSUE TITLE
[4.0]TAGS: router doesn't reuse exsting routes

### ISSUE THREAD

**Issue by pulsarinformatique** [joomla/joomla-cms#13598]
### Steps to reproduce the issue
create some menu items pointing to either an article or a category blog
attach some tags to the articles
then create a tagged menu item
check the results: 
### Expected result
the routes on each result should reuse the routes from the menu items we have created 

### Actual result
the routes generated look like id-category/id-alias instead of using existing routes

### System information (as much as possible)
J3.6.5

**Comment by franz-wohlkoenig** [comment]
Can't confirm on latest 3.7-staging using legacy Routing.

**Comment by nibra** [comment]
@pulsarinformatique could you elaborate the issue a little bit more? Especially the step "then create a tagged menu item" is unclear.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13598">issues.joomla.org/tracker/joomla-cms/13598</a>.</sub>

**Comment by pulsarinformatique** [comment]
Hi

I just meant: create a "Tagged Items" menu item, this is a menu item type, no more :)

just fill the field "tag" with one of the existing tags you used on the articles above.

cyril

**Comment by csthomas** [comment]
Routing in tags has been a little changed in 3.7. Can you repeat it on 3.7 beta3?

Changed file `https://github.com/joomla/joomla-cms/blob/3.7.0-beta3/components/com_tags/router.php`

**Comment by pulsarinformatique** [comment]
Hi

I just re tested with Joomla 3.7 beta3. The issues remains.

here is an example:

1- create category CAT1
2- create article ART1 inside CAT1. Add TAG1 to art1
3- create a single article menu item pointing to art1 "link to art1"
4- create a tagged item 'articles with tag1" menu item with 'tag1' as filter

When you click on  'articles with tag1" menu item art1 shows up (normal!)
but when you click on the art1 title you are redirected to 
link-to-art1/8-cat1/1-art1

instead of

link-to-art1

thanks

cyril

**Comment by brianteeman** [comment]
Purely as an experiment on a clean site can you do the same test but this time in the order 1,2,4,3 and then report back. Thanks

**Comment by pulsarinformatique** [comment]
Yes Brian
exactly the same result. it doesn't seem to depend on the order you create the menu items.

Cyril

**Comment by brianteeman** [comment]
I was checking to see if the ID of the menu item made a difference or not

**Comment by pulsarinformatique** [comment]
Hi 

Still not solved in J 3.7beta4

Cyril

**Comment by radioagent** [comment]
Hello!
I see same problem in latest version of Joomla.
I have category with many tagged articles. 
I have menu item to category blog with such link: /en/flowvision-applications
In this category blog If i click on article header link i see such link: 
/en/flowvision-applications/science-applications/nreal-validation

But this article is not located into science-applications category! It is located in flowvision-applications category.

I found this problem when created several menu items with category /flowvision-applications but with specified tags. 
menu item with alias /science-applications is latest from tagged menu items.

Is it same error or i should create new bug report?

This error make problems with seo , i think.

Thank you

**Comment by ghost** [comment]
@Hackwar Hannes, you are working on Router, but only for J4 i guess?

**Comment by Hackwar** [comment]
I've stopped touching the tags router a long time ago. The router can not be fixed in a backwards compatible way in Joomla 3.x. I've not fixed it in 4.0 yet. I don't know what to do in this case here.

**Comment by ghost** [comment]
Thanks for Info @Hackwar, so Issue stay open.

**Comment by ghost** [comment]
Issue confirmed.
@Hackwar So this is very big joomla tags bug and its imposible make Joomla tag this way yes?

After you create a menuitem for the tag you still get /component/tags/tag/tag-name when you click on article and scrool down to the tag.

What are your steps to reproduce /tags/tagname instead of /component/tags/tag/tag-name ?

**Comment by Hackwar** [comment]
I have a wish list for Joomla 4.0 and reworking the tags is one of the tasks on that list. Fixing the routing would be a part of that. I'm doing my best to work on that, but I'm not going to promise anything, since it depends on my available time and when the project wants to release 4.0. Doing my best to get it done.

**Comment by brianteeman** [comment]
Issue confirmed - definite bug
Steps I took to replicate the issue
Created 10 articles with approx 20 tags
Created 1 menu item to the articles list
Created 1 menu item to the tags list called "collections"

Tested the tags list and the links to each of the tags is correctly `/collections/food`
Tested the tag when displayed in the article and the link is `/component/tags/tag/food`

The same problem is true for the tags modules
Tested the module links when the module is displayed on the tags menu page it is correctly  `/collections/food`
Tested the module links when the module is displayed on any other page than the tags menu page `/component/tags/tag/food`

**Comment by AndySDH** [comment]
Is there any update on the Tags Router being improved for Joomla 4?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13598">issues.joomla.org/tracker/joomla-cms/13598</a>.</sub>

**Comment by brianteeman** [comment]
Could someone change the label on this to J4 Issue please

**Comment by zero-24** [comment]
Label changed.

**Comment by Hackwar** [comment]
#39114 should fix this. Please help testing that.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39114 . Thanks in advance.
