### ISSUE TITLE
"404 - Article not found" for new articles

### ISSUE THREAD

**Issue by tehribo** [joomla/joomla-cms#13609]
### Steps to reproduce the issue

Creating new article after 06.01.2017

### Expected result

To open the article normally

### Actual result

"404 - Article not found"

### System information (as much as possible)

Setting	Value
 
PHP Built On	Linux giga.superhosting.bg 2.6.32-531.29.2.lve1.3.11.1.el6.x86_64 #1 SMP Thu Dec 18 06:49:17 EST 2014 x86_64
Database Version	5.5.52-cll
Database Collation	cp1251_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.3.28
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

### Additional comments
Today I had to add new article, but when I save it and tried to open "404 - Article not found" error appeared.
No matter in which category or menu I move the article - the result is 404.

When I stop the "Search Engine Friendly URLs" option in the Site Settings the article loads normally.

All older articles opens normally.
My last successfully added article was added on 06.01.2017.

My site is in Bulgarian language.

Thank you in advance for your help!

**Comment by tehribo** [comment]
Today the strange saga continues...

If I add a dash " - " in the article Alias the problem is solved and the article can be opened 

Thank you in advance for your support!

**Comment by skouf** [comment]
Today I just downloaded the Alpha version to test the new routing system.

When I create a new article and publish it as Featured (so it become visible on protostar front page), i got a 404 error.
If I enable the Modern routing system, I have no more the 404 Error page and it displays the article but with a strange URL : 
www.mysite.com/?view=article&id=1:mon-article

So I have created a new menu item that lists all articles in my new category.

The new URL should be ww.mysite.com/ma-categorie/1-mon-article.html but when I click on it I have a 404 not found. To make that test work I have to switch back to Legacy for the routing system.

Any ideas ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13609">issues.joomla.org/tracker/joomla-cms/13609</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@skouf looks similar #13633

**Comment by brianteeman** [comment]
I am closing this at this time as the new routing code referred to has now been removed for review/
