### ISSUE TITLE
[com_fields] User custom field does display only when editing user

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#13601]
### Steps to reproduce the issue
Create a User custom field.
Then when editing the user in back-end, a new tab is present with the new field. (122 here is the user id)
`index.php?option=com_users&view=user&layout=edit&id=122`
![screen shot 2017-01-15 at 17 51 52](https://cloud.githubusercontent.com/assets/869724/21964393/594d73cc-db4b-11e6-857e-e20606d8e5a0.png)

That is fine. Frontend is also fine.

Now edit your own profile in backend (Edit Account menu item top right)
`index.php?option=com_admin&view=profile&layout=edit&id=122`

### Expected result
The new tab and Custom field should display. At least it is my expectation.

### Actual result
It does not display.
![screen shot 2017-01-15 at 17 54 38](https://cloud.githubusercontent.com/assets/869724/21964413/b781bafc-db4b-11e6-950a-54a287e3e75e.png)

@Bakual 
@laoneo 

What do you think?

**Comment by Bakual** [comment]
Confirming the bug.
Profile edit works in frontend but not in backend.

**Comment by laoneo** [comment]
Is there any reason why this view is loaded by com_admin and not com_users? That's the issue here as we are editing a user in a different component, so the events are loaded with a totally different context.

**Comment by Bakual** [comment]
Wow, didn't even notice that.
Imho, that should move to com_users. The model already extends from a user model anyway.

**Comment by laoneo** [comment]
I can create a pr, so it would be ok for the 3 series to move it to com_users, no BC issue here?

**Comment by Bakual** [comment]
Theoretically there are no B/C issues, practically there most likely will be.
I would copy the code from com_admin to com_users, change the links but still leave the profile view working (but deprecated) in com_admin as well. Possibly by extending the new classes in com_users to avoid duplicate code where possible.

**Comment by laoneo** [comment]
Same issue as here #5162 (thanks brian teeman for the hint).

**Comment by laoneo** [comment]
So we are not the first ones with this issue. Looks like nikolas has it investigated extensively. If we can leave it as it is would be nice as I'm basically running out of time to do it.

**Comment by Bakual** [comment]
I'd leave the issue open but it is certainly not a release blocker and could be done later.

**Comment by AlexRed** [comment]
I can confirm the problem on Joomla! 3.7.1-dev (nightly Build)

**Comment by brianteeman** [comment]
@AlexRed as this is still open then of course nothing has magically changed

**Comment by rdeutz** [comment]
This problem will not be fixed in 3.7.1.

**Comment by brianteeman** [comment]
@laoneo I am guessing that this is because the context is not correct. Those fields are for 			
 context="com_users.user"

**Comment by laoneo** [comment]
Yes exactly.

**Comment by brianteeman** [comment]
pinging @laoneo 

Really no need for this to stay open forever

**Comment by laoneo** [comment]
We will address this issue in the Enhance User GsoC 2018 project. Please leave it open.

**Comment by brianteeman** [comment]
@laoneo As far as I can see this has not been addressed in the GSOC project?

**Comment by laoneo** [comment]
No as we didn't came that far as it was planed.

**Comment by brianteeman** [comment]
This is resolved for J4

**Comment by ghost** [comment]
> This is resolved for J4

@brianteeman Does this mean to close the Issue?

**Comment by Quy** [comment]
Please test PR #29251 for J4.

**Comment by SharkyKZ** [comment]
This is fixed in #29251 for 4.0 but I can see now it's not the correct solution. Shame I realize this after beta was released. `Joomla\CMS\Fields\FieldsServiceInterface::validateSection()` should have been changed or replaced to allow properly mapping contexts, not just sections.

As an alternative we could also use `com_users.user` or `com_users.profile` context in `com_admin` but this would break plugins that are meant to run on these contexts but not on `com_admin.profile` and vice versa.
