### ISSUE TITLE
[com_fields] MSSQL fieldplugins

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-cms#13616]
### Steps to reproduce the issue
On a MSSQL installation, go to Plugin Manager and filter for the fields type.

### Expected result
Get the same list of fields as when installing on MySQL.
![image](https://cloud.githubusercontent.com/assets/251072/22012039/794f6e62-dc92-11e6-8acc-4e7361933bac.png)

### Actual result
Only the gallery field is listed.

### System information (as much as possible)
Latest Joomla staging.

### Additional comments
This is a missing update from PR #13319. Calling here the people from #12660 @alikon, @waader and @csthomas for help.

**Comment by alikon** [comment]
@laoneo , @waader , @csthomas   please test #13626

**Comment by csthomas** [comment]
Take a look at https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/sql/updates/sqlazure/3.7.0-2016-08-29.sql

ID 462 is taken. Probably it would be good to do changes in above file.

**Comment by alikon** [comment]
good catch @csthomas  see #13627

**Comment by laoneo** [comment]
CLosing this as we have a pr.
