### ISSUE TITLE
[3.7] Tab "Module Assignment": "Show|Hide"-Button looks different

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#13625]
### Steps to reproduce the issue
Open "Menu: Edit Item" > Tab "Module Assignment":
![bildschirmfoto 2017-01-17 um 21 01 02](https://cloud.githubusercontent.com/assets/8235763/22037780/efbf7694-dcf8-11e6-8f78-4848088aff9c.JPG)
### Expected result
Button-Style similar to "Yes|No"-Buttons:
![bildschirmfoto 2017-01-17 um 21 08 48](https://cloud.githubusercontent.com/assets/8235763/22037833/2bbeb308-dcf9-11e6-8c9a-57f753850141.JPG)
### System information (as much as possible)
Joomla! 3.7.0-alpha2-nightly
macOS Sierra, 10.12.2
Firefox 50.1.0, Chrome 55, Safari 10.0.2
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by alikon** [comment]
confirmed on current staging

**Comment by ciar4n** [comment]
This can be closed as we have a PR (#13698)

**Comment by franz-wohlkoenig** [comment]
thanks for reminding, @ciar4n
