### ISSUE TITLE
PHPMailer vulnerability

### ISSUE THREAD

**Issue by htmgarcia** [joomla/joomla-cms#13628]
Envato reported this vulnerability:
<img width="609" alt="screen shot 2017-01-17 at 10 06 05 pm" src="https://cloud.githubusercontent.com/assets/4999794/22050537/5a41b9b6-dd01-11e6-99e2-2456632fd1d8.png">

Update to [PHPMailer 5.2.22](https://github.com/PHPMailer/PHPMailer/releases/tag/v5.2.22)

Already reported from: https://developer.joomla.org/security-centre/668-20161205-phpmailer-security-advisory.html

Just posting here to make it a higher priority.

**Comment by zero-24** [comment]
Hmm did you read the report from the JSST?
The Joomla Core is not affected by this issue and the next update is going to fix that see: https://github.com/joomla/joomla-cms/blob/staging/libraries/vendor/phpmailer/phpmailer/VERSION

Or do i miss something?

**Comment by ot2sen** [comment]
Valentin, when you include 3rd party extensions in your packages, you would
need to update some newsletter extensions among other extensions that
include PHPMailer on their own.
These are not covered by the core checks. Several of these extensions
released new versions since that vulnerability got known.

**Comment by mbabker** [comment]
> Or do i miss something?

Nope.  Pretty normal "hey, these guys issued a security release, you should do something" issue report.  Happens with most repos.

Closing though.  No action required, core has already updated the library.

**Comment by htmgarcia** [comment]
Thanks @zero-24!
I missed that. Checked 3.7.0 alpha1 and didn't saw that update.

@ot2sen thanks! That's a good point to consider.

@mbabker it will be included with Joomla 3.7.0?

**Comment by mbabker** [comment]
Alpha 1 was tagged before the PHPMailer vulnerabilities were disclosed/patched, kinda hard to include something from the future 😉

**Comment by htmgarcia** [comment]
@mbabker I value the time you take to answer my "silly" questions; however may you try to be a little humble when replying? 

This part wasn't necessary.
> kinda hard to include something from the future
