### ISSUE TITLE
Override Joomla's core image - tooltip.png not working

### ISSUE THREAD

**Issue by saraheagle** [joomla/joomla-cms#13629]
### Steps to reproduce the issue
Insert <?php  echo JHTML::tooltip('This is the tooltip text', 'Tooltip title', 'tooltip.png', '', 'http://www.joomla.org'); ?> into code, as per https://docs.joomla.org/J3.x:How_to_add_tooltips_to_your_Joomla!_website

Add own tooltip.png image into /templates/*template_name*/images/system as per https://docs.joomla.org/How_to_override_the_output_from_the_Joomla!_core#Further_tips

### Expected result
Own image should show instead of Joomla default blue one.
<img src="/templates/*template_name*/images/system/tooltip.png" alt="Tooltip">

### Actual result
Joomla default image still shows.
<img src="/media/system/images/tooltip.png" alt="Tooltip">

### System information (as much as possible)
PHP Built On	Linux ukm2.siteground.biz 3.12.18-clouder0 #26 SMP Tue Jul 12 09:43:48 EEST 2016 x86_64
Database Version	5.6.28-76.1-log
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.3.29
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

### Additional comments
I am happy to take a look to see if I can see anything obvious that is stopping it from working, but I would need pointing to the correct file.

**Comment by bertmert** [comment]
I think what you describe is the expected bahavior.

If you use system/tooltip.png in

`
echo JHTML::tooltip('This is the tooltip text', 'Tooltip title', 'system/tooltip.png', '', 'http://www.joomla.org');
`
then the override path is
`/templates/your_template_name/images/system/tooltip.png`

If you use only tooltip.png

`
echo JHTML::tooltip('This is the tooltip text', 'Tooltip title', 'tooltip.png', '', 'http://www.joomla.org');
`
then the override path is
`/templates/your_template_name/images/tooltip.png`

So,

**Comment by saraheagle** [comment]
Doh, I put the image into /images/tooltip.png and it worked, although I am sure I tested this a least 20 times on 2 different sites. Obv. I did not do it properly at all.
Thank you very much for your time.
