### ISSUE TITLE
No email on admin registration approval in some cases

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#13620]
## Enable user registration and set the following options

 -   Allow User Registration - YES
 -   New User Account Activation - ADMIN

## Register as a new user

 -   Email will be sent to the user to confirm registration
 -   User confirms registration
 -   This triggers an email to the admin
 -   Admin receives an email with a link to approve the user (a front end lnk)
 -   Admin click on link and user is automatically aproved
 -   This triggers an email to the user telling them they have been approved
 -   Check com_users in the admin and you will see it shows the user is enabled and activated

Repeat the process but do not click the link in the admin email

Go to the admin and look at the users registration so that you can make a decision if you want to approve the user or not (maybe you are using the user profile plugin and you only allow users who say theyare from London)

Open the user record and you will see there is ONLY an option to "Block this user" - there is no option to activate. You can only toggle the activate in the list view of all users

Set the user to be enabled and active from the list view

## EXPECTED behavior

User recieves the email from step 6 above that their account has been approved

## ACTUAL behaviour

No email is sent but the account is active

## WHY THIS MATTERS

Users dont know they have been approved unless you approved them from the link in the admin email This link only contains the name, username and email - it doesnt contain any info from the user profile plugin so it only usable sites with simple approval rules

(copied from https://gist.github.com/brianteeman/636f36329b9e10021a19b334a9ccfe57 )

**Comment by ghost** [comment]
closed as having Pull Request #20282.

**Comment by brianteeman** [comment]
@richard67 please can this be re-opened

**Comment by joomdonation** [comment]
Re-open because the PR https://github.com/joomla/joomla-cms/pull/20282 for this issue was closed.

**Comment by brianteeman** [comment]
Thanks

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39650 . Thanks in advance.
