### ISSUE TITLE
Admin menu: batch process move to submenu impossible

### ISSUE THREAD

**Issue by nikosdion** [joomla/joomla-cms#13632]
### Steps to reproduce the issue
* Create a new custom menu
* Create a top level Header called "Tree One"
* Create a top level Header called "Tree Two" 
* Create a new menu item, e.g. Articles, as a sub-item of "Tree One"
* Select the new menu item and click on Batch in the toolbar.

### Expected result

Under "To Move or Copy your selection please select a Menu or parent item. " I can select "Tree Two" so I can move my menu item(s) into a different subtree, i.e. exactly as I can for front-end menu items.

Moreover, I expect that front-end menus (which are so obviously incompatible with my selection) are NOT displayed.

### Actual result

I see *neither* Tree One  *nor* Tree Two in the drop down. I only see "Add to this menu" which is quite useless for my intent.

I do, however, see the front-end menus and their items. But that's just plain wrong since my BACKEND menu items are INVALID in the FRONTEND.

### System information (as much as possible)

Irrelevant.

**Comment by nikosdion** [comment]
Pinging @izharaazmi

**Comment by izharaazmi** [comment]
@nikosdion Please test the PR at your convenience. Thanks.
