### ISSUE TITLE
Admin menu:  header with Component Menu Container flag doesn't list all components

### ISSUE THREAD

**Issue by nikosdion** [joomla/joomla-cms#13630]
### Steps to reproduce the issue
* Check out the latest staging branch (must have https://github.com/joomla/joomla-cms/pull/13036 applied)
* Create a new custom admin menu
* In it create a top level menu item Foobar of type Header
* Inside the Foobar menu item create a new menu item All Components of type Header with the Component Menu Container flag set to Yes
* Use your custom menu as your admin menu

### Expected result

Clicking on Foobar, All Components lists all installed components (or at least everything listed in the system default Joomla's Components menu)

### Actual result

Only Joomla! Update is listed.

### System information (as much as possible)

Irrelevant. I can reproduce it no matter the PHP version.

### Additional comments

If I install third party extensions the *third party* extensions *are* listed. So _either_ Joomla! Update should NOT be displayed in the menu item _or_ all core components should be listed, at least those listed in the Components menu of stock Joomla. I would personally prefer the latter option because, as a user, I was caught completely off guard when my All Components menu item behaved _completely differently_ than the default Component menu, even though the Component Menu Container is described as making me header behave exactly like the default Components menu.

Ping @izharaazmi

**Comment by nikosdion** [comment]
I want to clarify that I do understand that that menu item displays the combined Main (protected) and Menu (protected) menu items. However my comment on how it looks from a user's perspective does stand. We have to provide the user with defaults which don't throw her off-guard. Don't make the user feel stupid.

**Comment by izharaazmi** [comment]
Thanks @nikosdion for pointing out that issue. Please make sure that those menu items are in "published" state. This point is covered in the other PR (quoted below)

> **How can I remove an auto created component menu item from the Component Root parent after I have created my own menu item for it at desired location?**  
>
> In the menu items list view, set the menu type filter to "Main (Protected)". You will see all those automatically generated menu items there. Just unpublish the desired items. If the component root has not children to show, the component root will also be hidden automatically.
>
> Deleting them should not cause any side effect, however its not recommended to do so. Editing these items is disabled to avoid undesirable consequences.
>
> Please note that if you decide to switch back to the "preset" menu anytime, these auto-generated Menu items will show up under "components" again. Due to B/C reasons preset menu does not obey published/unpublished state.

Do let me know if the problem still persists.

**Comment by izharaazmi** [comment]
I just tested it via clean install as well as upgrade from 3.6.5, both ways those menu items were automatically published and the container works as expected.
I am curious about the use case where it failed so that I can fix it. Please advise.

**Comment by nikosdion** [comment]
All I did was:
* check out the latest staging branch
* export to zip with `git archive --format=zip -o /path/to/my.zip staging`
* unzip to a new folder
* create a new database
* run the installer, creating a new site, with the default English content
* the instructions I mentioned above

The result was that my All Components menu only shows com_joomlaupdate. I checked the Main (protected) and Menu (protected) and the only thing published is Joomla! Update.

I installed Akeeba Backup and it was also displayed above Joomla! Update as it should.

This is exactly why I'm worried. Someone who creates a custom admin menu will only see 3PD software in his custom components menu, therefore think that the 3PD components are somehow related to this issue. We 3PDs don't fancy getting yelled at by clueless people about something that's not our fault.

**Comment by izharaazmi** [comment]
I did exactly the same thing (clean install of staging) but for me it worked as expected. I'd like to wait for someone to confirm this issue or until I can reproduce it.

PS: If that matters I have only tested with MySQL database.

**Comment by rdeutz** [comment]
@nikosdion could you execute the statement in this PR https://github.com/joomla/joomla-cms/pull/13619

I did some cleanup because some items had menu some main and the client Id needs to be set right

**Comment by rdeutz** [comment]
@nikosdion ah forget my comment, it is only for updating a site

**Comment by nikosdion** [comment]
Are we all running the latest *staging* branch? Because I'm trying with staging and I can reproduce this. I am thinking that maybe @izharaazmi is using his branch but there was some merge issue gone unnoticed in staging?

**Comment by izharaazmi** [comment]
I am using commit b9d0d32defe49a890b0130432c4e08151c4b34aa on staging.

**Comment by rdeutz** [comment]
Tried it with the latest staging (100c5a4e49f278af3ceae13695014fbe7d2ee2f5) looks good to me when I do a clean install. 
![menufoobar](https://cloud.githubusercontent.com/assets/467356/22066065/6bd97efe-dd8b-11e6-9d5c-e1e904580f20.png)

Can reproduce the issue when I use the test content shipped with Joomla!, spotted the part "with the default English content" not directly. :-)

Tbh, our test content is not in such a good shape that I would spend too much time at this state of the release process for it. I think it is important that an update and a clean installation are working

**Comment by nikosdion** [comment]
The default English content is the pre-selected option in the Joomla! web installer. It's also what third party installers (hosting control panel, Microsoft Web Platform Installer, etc) use by default. Therefore the recommended default on a new installation is NOT what the user expects, it's something broken.
Based on Robert's comments I think that we have two choices: either fix that blasted content or remove it altogether. I'm all for the latter. Ship Joomla! with no content and use the existing multilingual code to create one article in as many languages as the user wants, even if it's exactly one (English UK).

Whatever the decision, it seems that something is broken after all and needs to be fixed one way or another.

**Comment by rdeutz** [comment]
just to be sure:

![joomla web installer](https://cloud.githubusercontent.com/assets/467356/22067359/35b8e462-dd91-11e6-827c-74df59e4ac5a.png)

**Comment by nikosdion** [comment]
Correct.

**Comment by izharaazmi** [comment]
You are right @nikosdion. All sample data sql needs to be updated.There are 3x4=12 of them pending a fix. I'd do that but too busy right now. Will get back asap if nobody else does it till then. Thanks.

**Comment by nikosdion** [comment]
gh-13640 is an acceptable solution to this issue.
