### ISSUE TITLE
By copying an article creation date is copied too

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#13645]
### Steps to reproduce the issue

If you copy an item the creation date is also copied.

### Expected result

IMO the creation of the item is to be set at the current date, because it was created then...

### Actual result

The creation date is copied too.

### System information (as much as possible)

Joomla 3.6.5

**Comment by mbabker** [comment]
This has come up repeatedly in the past.  The creation date is a configurable item and as such it is appropriate to copy it as well.  Your expectation might be that it changes but mine in most cases is to retain it unless I explicitly change it.

**Comment by rdeutz** [comment]
expected behaviour, not a bug
