### ISSUE TITLE
Alternative Layout Parameter for Tags Not Working?

### ISSUE THREAD

**Issue by justinherrin** [joomla/joomla-cms#13641]
Hello all. I think I may have stumbled across a bug with the Alternative Layout parameter for Tags. Basically what I'm noticing is that the layout of a single Tag view can not be set via the Alternative Layout parameter for a Tag, but has to be set in the Tags Component Options instead.

### Steps to reproduce the issue
1. Create a new tag in Components->Tags.
2. Set the Alternative Layout parameter on the Options tab to be "Compact layout".
3. Assign the new tag to some content items and view the Tag layout in the frontend.
4. You might notice that the items assigned to that Tag are listed in the Default Tag Layout, not the "Compact layout" you chose in the parameters.
5. Navigate to Components->Tags->Options and set the "Default Tagged Items Layout" parameter to be "Compact layout".
6. Refresh the frontend and finally the list of tagged items will be in the Compact Layout.

### Expected result
I would assume that the intended behavior of the Layout parameter set at the specific Tag level would take higher priority than the Global Tags Component Options.

### Actual result
Global Tags Component Options takes higher priority than the Alternative Layout parameter set at the single Tag level.

### System information (as much as possible)
Using Joomla 3.6.5 on MAMP Localhost as well as a live Apache server.

### Additional Comments
I tried searching for an existing open or closed issue to see if this was reported already but didn't see anything immediately. Sorry in advance if it's a duplicate.

**Comment by Bakual** [comment]
Have a look at https://github.com/joomla/joomla-cms/pull/13643
