### ISSUE TITLE
Error on inbuilt help pages

### ISSUE THREAD

**Issue by ot2sen** [joomla/joomla-cms#13644]
### Steps to reproduce the issue
Visit 'Help->Joomla! Help' and you get an error: RuntimeException

Error fetching page from MediaWiki API: The page you specified doesn't exist

### Expected result
Help pages to be shown

### Actual result
RuntimeException

Error fetching page from MediaWiki API: The page you specified doesn't exist

### System information (as much as possible)
3.7.0 Alpha 2, PHP 5.6.8![screen shot 2017-01-18 at 20 53 28](https://issues.joomla.org/uploads/1/b966f4d0e80e73c95875d12ffdec7cce.png)

**Comment by zero-24** [comment]
@ot2sen this is a known issue as there is no namespace for 3.7.0 alpha help screens. They are going to be enabled / created if there is a 3.7.0 stable release. :smile:

**Comment by ot2sen** [comment]
@zero-24 Ah, makes sense. Thanks :)
