### ISSUE TITLE
Admin menu editor: doesn't detect Module Manager and Menu Manager menu items

### ISSUE THREAD

**Issue by nikosdion** [joomla/joomla-cms#13648]
### Steps to reproduce the issue

* Create a new custom admin menu
* Remember to create two menu items to Menus, Menus and Modules, Modules
* Publish the menu, making sure that the "Check Menu" option in the module is enabled.

### Expected result

Joomla does not complain because I've created links to the Menu Manager and Module Manager

### Actual result

Joomla complains with the message "The active administrator menu does not contain links to Module Manager and Menu Manager. Click to turn on the menu recovery mode." Joomla is drunk.

### System information (as much as possible)

Running staging on Windows 10, stock Apache server environment with latest PHP 7.0 build downloaded from php.net.

### Additional comments

Pinging @izharaazmi 

I'm so sorry for being a royal pain in the butt. I'm currently using and abusing this feature as I'm already adding support for it in my software. I will be filing bugs as I run into them. On the plus side, this feature has a fighting chance of being stable by the time Joomla! 3.7 is released, an absolute first for any new feature in Joomla! :D

**Comment by izharaazmi** [comment]
I absolutely appreciate your patience and I'm thankful for your efforts. I
am already working for your another reported issue. I'll try to fix all of
them very soon,

**Comment by nikosdion** [comment]
Duplicate of gh-13650. I'm closing this one in favor of your issue which better describes what's going on and why. Thank you :)
