### ISSUE TITLE
phpMailer vulnerability 

### ISSUE THREAD

**Issue by didiandalucia** [joomla/joomla-cms#13655]
### Steps to reproduce the issue

Critical Vulnerability in PHPMailer, see https://www.wordfence.com/blog/2016/12/phpmailer-vulnerability/

it comes from Joomla in folder: libraries/vendor/phpmailer/phpmailer/class.phpmailer.php

**Comment by ot2sen** [comment]
Known issue, and core is projected. Updated for 3.7 too
See https://developer.joomla.org/security-centre.html
