### ISSUE TITLE
Users can be registered without assigned usergroup

### ISSUE THREAD

**Issue by renekreijveld** [joomla/joomla-cms#13653]
### Steps to reproduce the issue

Go to the Joomla user manager and click New to create a new user.
On the tab Account Details input all required information.
On the tab Assigned User Groups **uncheck** all groups, so **no group** is checked.
Click Save & Close.
The user is now created with no usergroup assigned to the account.

### Expected result

When creating a new user at least one selected usergroup should be required.

### Actual result

A user can be created with no usergroup assigned to the account.

### Additional comments

This should not be possible. The result could be that the user receives an email with the account details and the user could even login into the website. But as the account is not assigned to any group, the user cannot do anything, possibly not even logout or edit the profile.

**Comment by renekreijveld** [comment]
Also tested on Joomla 3.7 Alpha 2 a user can be created without a group assigned.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13653">issues.joomla.org/tracker/joomla-cms/13653</a>.</sub>

**Comment by joomdonation** [comment]
What should be right behavior? Throw warning and prevent the account being created or assign the new user to default user group configured in com_users options?

**Comment by renekreijveld** [comment]
Throw warning and prevent the account being created. The same as if no username was entered.
For some reason the administrator unchecked all groups. By showing an warning the administrator can select the right usergroup(s).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13653">issues.joomla.org/tracker/joomla-cms/13653</a>.</sub>

**Comment by joomdonation** [comment]
OK. I made the PR https://github.com/joomla/joomla-cms/pull/13656 to fix it. Please help testing to get the issue fixed

**Comment by renekreijveld** [comment]
Tested succesfully!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13653">issues.joomla.org/tracker/joomla-cms/13653</a>.</sub>

**Comment by Bakual** [comment]
Closing as we have a PR
