### ISSUE TITLE
Administrator pages not displayed when Error Reporting is set to 'Development'

### ISSUE THREAD

**Issue by kanich** [joomla/joomla-cms#13651]
### Steps to reproduce the issue
1. Set in administrator Global Configuration / Error reporting = 'Development'
2. In Joomla 3.7.0.a2 administrator (when Error Reporting is set to 'Development') following errors are shown :

 Notice: Undefined property: stdClass::$client_id in joomla/libraries/vendor/joomla/utilities/src/ArrayHelper.php on line 521
 Notice: Undefined property: stdClass::$client_id in joomla/libraries/vendor/joomla/utilities/src/ArrayHelper.php on line 522
3. Entire backend is blocked (it is not possible to continue)

### Expected result
No error messages have to be shown

### Actual result
In Joomla 3.7.0.a2 administrator (when Error Reporting is set to 'Development') following errors is shown :

 Notice: Undefined property: stdClass::$client_id in joomla/libraries/vendor/joomla/utilities/src/ArrayHelper.php on line 521
 Notice: Undefined property: stdClass::$client_id in joomla/libraries/vendor/joomla/utilities/src/ArrayHelper.php on line 522

and it is not possible to continue with any administrator tasks.

### System information (as much as possible)
Problem was located in :
administrator/modules/mod_menu/preset/enabled.php
line 164 $menuTypes = ModMenuHelper::getMenus();
line 165 $menuTypes = ArrayHelper::sortObjects($menuTypes, array('client_id', 'title'), 1, false);

where ModMenuHelper::getMenus() is not returning class field 'client_id'.

Problem can be solved with including 'client_id' in SQL query in administrator/modules/mod_menu/helper.php after line 36 :

->select('b.client_id')

**Comment by zero-24** [comment]
@kanich can you send a pull request with the needed change against the staging branch?

**Comment by bertmert** [comment]
I can not confirm this issue with a nearly untouched Staging installation of yesterday.

**Comment by kanich** [comment]
@bertmert My observation was made on new upgrade Joomla 3.7.0-alpha2 installed over old Joomla 3.7.0-alpha1.
OS : Linux Ubuntu 14 (64 bit)
PHP : 7.0.14

**Comment by bertmert** [comment]
I compared database of 3.6.5 with Staging 3.7.0 of yesterday and I found a new column client_id in table #__menu_types.

Concerning updates I think this PR of yesterday is important, too. (Meged yesterday): https://github.com/joomla/joomla-cms/pull/13619/files

Maybe that's the reason? Somewhere, somehow, ....? We will see...

**Comment by kanich** [comment]
I used fresh installation 3.7.0-alpha1 (with appropriate database sql) and then upgrade to 3.7.0-alpha2 with database fix for this version. Please find enclosed browser snapshot with error messages (on the page is then nothing more, no menu, links, buttons!)
![Uploading issue_13651_browser_snapshot.png…]()

**Comment by kanich** [comment]
![issue_13651_browser_snapshot](https://cloud.githubusercontent.com/assets/6680688/22123379/b15987fc-de8b-11e6-88e3-8b93ce6c4695.png)

**Comment by infograf768** [comment]
The update sql was not run properly from alpha to alpha. See https://github.com/joomla/joomla-cms/issues/13660

Closing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13651">issues.joomla.org/tracker/joomla-cms/13651</a>.</sub>

**Comment by RevoLion** [comment]
So how do I fix the error for Joomla! 3.7.0-alpha2. This error "1054 Unknown column 'client_id' in 'field list'" occurs only when I click on a menu in the menu manager.

JT<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13651">issues.joomla.org/tracker/joomla-cms/13651</a>.</sub>

**Comment by kanich** [comment]
@RevoLion This error is caused by uninitialised variable which should contain value of  new column 'client_id' (added in Joomla 3.7) to database table. It is necessary to find part of code where menu variables are initialised and there include 'client_id' variable to correct initial value.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13651">issues.joomla.org/tracker/joomla-cms/13651</a>.</sub>

**Comment by RevoLion** [comment]
So does this correction look right, because I can not get it to fix.
{
		$db     = JFactory::getDbo();
		$query = $db->getQuery(true)
			->select('a.*, SUM(b.home) AS home')
			->from('#__menu_types AS a')
			->join('LEFT', '#__menu AS b ON b.menutype = a.menutype AND b.home != 0')
			->select('b.language')
			->select('b.client_id')
			->join('LEFT', '#__languages AS l ON l.lang_code = language')
			->select('l.image')
			->select('l.sef')
			->select('l.title_native')
			->where('(b.client_id = 0 OR b.client_id IS NULL)');<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13651">issues.joomla.org/tracker/joomla-cms/13651</a>.</sub>

**Comment by RevoLion** [comment]
Previous code correction was made in administrator/modules/mod_menu/helper.php <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13651">issues.joomla.org/tracker/joomla-cms/13651</a>.</sub>
