### ISSUE TITLE
403 Forbidden in Microsoft Edge browser

### ISSUE THREAD

**Issue by rgmears** [joomla/joomla-cms#13658]
### Steps to reproduce the issue
I am not able to reproduce this. I do not have access to Microsoft's Edge browser. However, two different people have reported the same thing: when they visit my websites using Edge they get 403 Forbidden.

### Expected result
Web page should open.

### Actual result
403 Forbidden instead.

### System information (as much as possible)
Both sites are Joomla 3.6.5

### Additional comments
These websites have been reported:
[GW DESIGN](http://www.gwdesign.studiofive.biz/)
[SILVER PLAINS PROJECT](http://www.silverplains.ca/)

**Comment by zero-24** [comment]
I can not confirm this using MS Edge on Windows 10. Do you have any more informations about the browser / os setup?

Do you have any htaccess rules?

**Comment by rgmears** [comment]
Yes I have htaccess rules. Some of them include blocking specific IP addresses. But I've checked those; they are not the problem. I can post my htaccess file if you want. Or PM it to you.
The first person was a visitor to the Silver Plains site. He said he had just made some security settings in Edge; which, to him, implied my site was insecure. He was rather snoughty about it.
The other person was using Edge's default settings. She subsequently visited the GW DESIGN site with Chrome.
Both were on Windows 10.

**Comment by zero-24** [comment]
> The first person was a visitor to the Silver Plains site. He said he had just made some security settings in Edge; which, to him, implied my site was insecure.

Which sec settings? The Edge does not have any special sec settings :smile: Just some basic settings.

**Comment by zero-24** [comment]
> I can post my htaccess file if you want. Or PM it to you.

send it to tobias.zulauf<at>community.joomla.org

**Comment by rgmears** [comment]
I don't know. It's what he said on FB:

> I suspect that the problem might be that I upgraded my security levels recently because of some unwanted activity. Not sure that I want to lower my guard.

**Comment by Bakual** [comment]
Can we please take this to the forums? You can open an issue again if you verified it's a bug in Joomla (which I doubt).

**Comment by rgmears** [comment]
Posted to forum:
[403 Forbidden in Microsoft Edge browser](https://forum.joomla.org/viewtopic.php?f=714&t=946030)

**Comment by N6REJ** [comment]
replied in forum
Bear

**Comment by rgmears** [comment]
Thanks. Unfortunately, the moderator removed the links to the websites in question.
