### ISSUE TITLE
[com_fields] What can be done with the field images in com_fields?

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#13668]
### Steps to reproduce the issue

Create a new field and apply an image to the field.
![articles new field joomla cms test administration](https://cloud.githubusercontent.com/assets/9974686/22173757/93a3607e-dfcc-11e6-89c4-92b2e8b1c3ab.png)

### Expected result
The image is displayed either in the frontend or in the backend near the field.

### Actual result
I do not see the picture anywhere

**Comment by Bakual** [comment]
It's not used at all. That's why I created https://github.com/joomla/joomla-cms/pull/13621

imho it either has to be used somewhere, or we remove the option.

**Comment by laoneo** [comment]
I would remove it as in pr @Bakual.

**Comment by astridx** [comment]
That's why I created #13621 solves this issue. This PR is merged now.
