### ISSUE TITLE
client_id not fixed in database fix

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#13664]
Updated branch from previous 3.7.x staging to 3.7.x staging with alpha 2. Whilst I appreciate this isn't a big usage case, I would then go to database Fix. It fixes the schema, however! it seems to be missing the client_id column of in the menu_types table causing the menu manager to be un-usable.

Anyone who manually updates by replacing the core files, which I had to do the other day for a client will be prompted with the same error. unknown column client_id

**Comment by Bakual** [comment]
Updating from staging to alpha isn't supported. There is already an issue open which discusses if that should be changed but for the time being this is the case.
Thus I'm closing this issue as expected behavior.
