### ISSUE TITLE
Text in administrator\language\en-GB\en-GB.com_languages.sys.ini

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#13669]
COM_LANGUAGES_OVERRIDE_VIEW_DEFAULT_DESC="Here you assign custom text for a language key that you want to used instead of language pack default text."
Change into:
COM_LANGUAGES_OVERRIDE_VIEW_DEFAULT_DESC="Here you assign custom text for a language key that you want to use instead of language pack default text."

**Comment by MATsxm** [comment]
@MartijnMaandag 
it is time to push your PR 😉 
you will find everything needed in the Doc...

**Comment by Bakual** [comment]
See https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests if you want to try it. It's really simple. Otherwise I can do it.

**Comment by MartijnMaandag** [comment]
I will try and learn and answer here.

**Comment by MATsxm** [comment]
@MartijnMaandag it is easier than tagging/marking a JDoc article 😉 
do not hesitate if you need some help

**Comment by MartijnMaandag** [comment]
Well, I did my first changes on Joomla core. What comes next? code ;-)
No.

**Comment by MATsxm** [comment]
Great job @MartijnMaandag 
Thank you !
waiting for the next one ;)
