### ISSUE TITLE
[com_fields] Custom Fields not working on registration form

### ISSUE THREAD

**Issue by ManfredHuebner** [joomla/joomla-cms#13662]
### Steps to reproduce the issue
Blank installation of J3.7 alpha
Create field group "test"
Create fields for users (2 textfields, 1 color field) and add to field group
Enable user registration

### Expected result
Added fields should be ready for input

### Actual result
Try to register new user: added fields are not enabled, no input possible. Color field is working. Same problem with textarea field. Editor field is working correctly.

### System information (as much as possible)
Setting	Value
 
PHP Built On	Windows NT MANFRED-PC-LM 10.0 build 14393 (Windows 10) i586
Database Version	5.7.17-log
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.8
Web Server	Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.8
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.7.0-alpha2 Alpha [ Amani ] 18-January-2017 19:23 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments

In Profile edit form the custom fields work as expected.

**Comment by Bakual** [comment]
Make sure the "Guest" Usergroup is allowed for the "Edit Custom Field Value" action. Please check the permissions tab of either the field or field group.

**Comment by ManfredHuebner** [comment]
@Bakual 
Sorry, I tried but that doesn't change the behavior. Also, if it would work, it would be inconsistent as others fields wouldn't require that permission setting.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13662">issues.joomla.org/tracker/joomla-cms/13662</a>.</sub>

**Comment by Bakual** [comment]
> Also, if it would work, it would be inconsistent as others fields wouldn't require that permission setting.

Actually, you have a special case here because the registration form can be filled out by visitors not logged in, similar to the contact form. So you need to make sure "Guest" can edit the value. I think by default ACL only allows Super Users to set it. That's how our ACL works, deny everything until it's explicitely allowed.

> Sorry, I tried but that doesn't change the behavior.

I need to check why exactly it doesn't seem to work there then.

**Comment by ManfredHuebner** [comment]
> Actually, you have a special case here because the registration form can be filled out by visitors not logged in, similar to the contact form. So you need to make sure "Guest" can edit the value. I think by default ACL only allows Super Users to set it. That's how our ACL works, deny everything until it's explicitely allowed.

I got it. I have to set the permissions in the field. But why isn't it working with default permissions set? Doesn't mean default "default"?

Also, why are some fields working without the permissions set right? This seems to be an UI issue. As I can't find the correct way to get this thing done, I wonder how many users will face the same issues.

**Comment by Bakual** [comment]
There is another issue open that "color" and "editor" fields can't be set to disabled. So those always allow to be edited. That may be what you saw.

> I got it. I have to set the permissions in the field. But why isn't it working with default permissions set? Doesn't mean default "default"?

It should work also with field groups and global permissions. Sounds like a bug sneaked in with the inheritance of those settings. Thanks for that finding, that helps. I know where to look now. Just have to find the time for it :)

**Comment by Bakual** [comment]
Please test #13676

Closing as we have a PR
