### ISSUE TITLE
Small CSS issue

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#13663]
Good evening all, 

Just a small inconsistency with paddings in my opinion. See attached screenshot:

![screen shot 2017-01-20 at 19 56 56](https://cloud.githubusercontent.com/assets/1400982/22163479/dc789166-df4a-11e6-8437-ae25d516dfef.jpg)

the buttons on the right are around 5px padded from the right. than the lower container and the buttons on the left and menu. 

The above is in the article manager.

**Comment by ciar4n** [comment]
Thank you @tonypartridge 

PR created: #13823
