### ISSUE TITLE
Plugin Event missing property

### ISSUE THREAD

**Issue by flyingwombats** [joomla/joomla-cms#13674]
### Steps to reproduce the issue
Look at `onExtensionBeforeUpdate`. It doesn't contain the extension ID that is about to be updated!!

### Expected result
I have the extension ID to manipulate anything I need to

### Actual result
I don't have the extension ID and I feel sadness

### System information (as much as possible)
Joomla 3.7

### Additional comments
N/A. Report by @wilsonge

**Comment by wilsonge** [comment]
Confirmed at London super sprint

**Comment by zero-24** [comment]
https://github.com/joomla/joomla-cms/blob/6e07ca6fadd8a5d1db3337cf0357d782646f5411/libraries/cms/installer/installer.php#L714

This is the line that needs to be changed :)

**Comment by franz-wohlkoenig** [comment]
> This is the line that needs to be changed :)

by?

**Comment by ReLater** [comment]
As far as I see the extension id is unknown yet when `onExtensionBeforeUpdate` is triggered. Thus it must be calculated in the plugin itself based upon the manifest data with a db query OR the logic of the core Installer/Update process must be changed significantly.

I just flew over the code and don't see a practicable/acceptable way.
Objection welcome ;-)

With other words: I would close tis issue but I'm not sure.

**Comment by ghost** [comment]
closed as stated above as it can always reopened if needed. thanks @ReLater
