### ISSUE TITLE
Mod_Language css (small) annoying issue on Protostar

### ISSUE THREAD

**Issue by gwsdesk** [joomla/joomla-cms#13678]
**Joomla 3.7-Alpha2**

![screen shot 2017-01-22 at 07 15 04](https://issues.joomla.org/uploads/1/5803bf75fed081caff46eced4051df59.jpg)
This can be resolved by changing (media/mod_languages/css) the css on line 1 to 

div.mod-languages ul 
{ list-style: outside none none; margin: 5px; padding: 0 0 5px; } and you see than

![screen shot 2017-01-22 at 07 16 27](https://issues.joomla.org/uploads/1/6c67c075b746f8e27930c4ed917b533e.jpg)

**Comment by zero-24** [comment]
Can you send your changes as PR than?

**Comment by gwsdesk** [comment]
Never done a PR, I test not code ;-)

**Comment by zero-24** [comment]
It is not that complicated as you might think. This way the change is also linked to your github history https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

It is easy and simple feel free to contact me on any issues e.g. via Glip :)

**Comment by infograf768** [comment]
I do not agree with changing this in core.
Not everyone is using the flags over a search box and it is easy to adapt these core css to your needs by overriding them in a custom.css by eventually adding a class or not.
The other aspect is that you define a padding for LTR which would not work for RTL

**Comment by infograf768** [comment]
BTW, when displaying the module for example in the right column in protostar, this is what I get.
Left is before, right after the proposal:

![screenshot](https://cloud.githubusercontent.com/assets/869724/22183543/3b423086-e0c1-11e6-9891-3de397ceb523.png)

Now you certainly understand why we should not change the default css.

**Comment by gwsdesk** [comment]
I see what you mean but it works well when you just change the padding 
but not the spacing indeed. That avoids the effect what you (correctly) 
show

**Comment by franz-wohlkoenig** [comment]
It looks better using `Use Image Flags: No`, but its not a Solution.
![screen shot 2017-02-05 at 11 27 00 am](https://cloud.githubusercontent.com/assets/8235763/22625414/27539d3c-eb96-11e6-81b8-e073177a0866.JPG)

**Comment by franz-wohlkoenig** [comment]
better look using smart-search:
![screen shot 2017-02-05 at 12 52 42 pm](https://cloud.githubusercontent.com/assets/8235763/22625946/42e7738c-eba2-11e6-9d73-f7f526a79429.JPG)
![screen shot 2017-02-05 at 12 53 17 pm](https://cloud.githubusercontent.com/assets/8235763/22625947/4866f332-eba2-11e6-89fc-b36acfbc1fbf.JPG)
no solution if wanna use "Search".

**Comment by ghost** [comment]
closed as having Pull Request #21254
