### ISSUE TITLE
[com_fields] Context is lost when adding a new field group

### ISSUE THREAD

**Issue by Joe-Palmer** [joomla/joomla-cms#13675]
### Steps to reproduce the issue

Go to a field group overview, eg:

/administrator/index.php?option=com_fields&view=groups&context=com_users.user
/administrator/index.php?option=com_fields&view=groups&context=com_content.article

Click **New**

### Expected result

The context is still in the URL.

### Actual result

It is not in the URL 😭 

### System information (as much as possible)

Tested on Joomla 4.0-dev and staging.

### Additional comments

This causes an ACL error if trying to login with a com_fields URL without a context.

**Comment by Bakual** [comment]
It doesn't have to be in the URL. It is set in a userstate and taken from there afterwards.

> This causes an ACL error if trying to login with a com_fields URL without a context.

If you want to use a direct link, you need to copy the initial link (eg the one from the sidebar). That is correct.

**Comment by Bakual** [comment]
Closing as expected behavior

**Comment by laoneo** [comment]
Please reopen this one as it absolutely makes sense to have the context in the url similar to the fields or the extension parameter in com_categories.

**Comment by Bakual** [comment]
> similar to the fields

For fields, the context (and for categories, the extension) isn't in the URL anymore as soon as you reload the list eg by applying sorting or filtering.
It's there for the create and edit tasks though. However those links don't work when used directly. You will get a "You're not allowed to access this page directly" error.

You can put it into the URL but I don't see the point having it there.

**Comment by franz-wohlkoenig** [comment]
@SoftForge needs this Issue to stay open?

**Comment by Bakual** [comment]
Imho not, but I'm not going to close it (again) 😄

**Comment by SoftForge** [comment]
I would say this is worth fixing. The reason is that you can click on link (rather then posting a sort of filter) to get to this page. If you session has timed out, you actually get this login page which is good. However, when you login you get a nasty ACL error as the context is no longer in the userstate. I don't think you can create this situation by sorting or filtering (correct me if I'm wrong).

**Comment by Bakual** [comment]
Easiest would be to implement a fallback to com_content.article as context if none is given. Then it would never fail.
Adding the URL in all cases would be more work.

**Comment by SoftForge** [comment]
That would be an improvement, although potentially confusing if you timed out adding fields to com_users and logged back in to arrive at a different set of fields.

**Comment by Bakual** [comment]
Yep sure. But it would be kind of a similar behavior with how filtering works (where filters are reset when your session times out).

**Comment by brianteeman** [comment]
@laoneo any thoughts on how to resolve this?

**Comment by laoneo** [comment]
If I'm allowed to, then I would like to forward this issue to @Bakual, as he did the whole groups move from categories to their own entities.

**Comment by Bakual** [comment]
I'm going to quote my statement from earlier:

> You can put it into the URL but I don't see the point having it there.

I already closed this issue as expected behavior. It's the same behavior com_categories has except that there is no fallback to com_content like com_categories seems to have.
Do you want that fallback? Even if it may be confusing to suddenly have com_content fields?

**Comment by ghost** [comment]
If this PR get no Response, it will be closed at 17th September 2017.

**Comment by ghost** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened.
