### ISSUE TITLE
Blog menu item: allowing multiple tags

### ISSUE THREAD

**Issue by pulsarinformatique** [joomla/joomla-cms#13680]
### Steps to reproduce the issue
In a category blog menu item you only can select one tag whereas it is written "tagS". I think we should allow the selection of multiple tags

**Comment by franz-wohlkoenig** [comment]
or correct as first Step Lang-String on `Tag` @infograf768?

**Comment by pulsarinformatique** [comment]
Hi
Is any chance J 3.7 includes the multi tag filter on the menu items ? There are many cases filtering on only one tag is just not enough

thanks

cyril

**Comment by pulsarinformatique** [comment]
Hi, any answer here please ?

**Comment by franz-wohlkoenig** [comment]
set Issue on Category "Feature Request".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13680">issues.joomla.org/tracker/joomla-cms/13680</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #18234
