### ISSUE TITLE
Again issues with the backend login form (languages dropdown)

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#13693]
### Steps to reproduce the issue

install latest 3.7.x package
install an extra language
go to the admin login

### Expected result

A login form with the languages dropdown agline to the other input fields

### Actual result

![image](https://cloud.githubusercontent.com/assets/2596554/22196547/f92a46f6-e14d-11e6-8846-8cc002b42f08.png)

### Additional comments

IIRC we had a similiar issue in the past and it looks like this change is reverted now?

**Comment by zero-24** [comment]
@ciar4n it looks like you changes here are missing in staging: https://github.com/joomla/joomla-cms/pull/12442/files

Can you take a look?

**Comment by ciar4n** [comment]
Thank you @zero-24 

PR created #13693
