### ISSUE TITLE
Account is getting activated automatically before email activation

### ISSUE THREAD

**Issue by AiswaryaShivan** [joomla/joomla-cms#13694]
### Steps to reproduce the issue
Hi,

We have an issue with registration..on succesfull registration to site, user gets an activation email to activate the account but user is getting activated without mail activation. Somehow account is getting activated. please help me to solve this.
These are global configuration settings
Allow User Registration = Yes
New User Account Activation = Self

### Expected result
User accounts has to be activated only via email activation

### Actual result
Accounts are activated before mail activation, that is right after registration

**Comment by infograf768** [comment]
On which version of Joomla are you testing this?

**Comment by AiswaryaShivan** [comment]
Testing on  
Joomla! Version	Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by infograf768** [comment]
please update to 3.6.5 first

**Comment by AiswaryaShivan** [comment]
Is that an issue with 3.3.6? Please explain why you said to update version

**Comment by infograf768** [comment]
Because we do not test anymore on obsolete versions which have vulnerabilities.
https://developer.joomla.org/security-centre.html

**Comment by tonypartridge** [comment]
Joomla! 3.3.6 was released in Oct 2014. As infograf768 has stated you need to update your core. 

Furthermore, please replicate it on a base Joomla! Install as I suspect you have plugins and components installed which could causing the above behaviour.

**Comment by jeckodevelopment** [comment]
Closing because it's a known issue already fixed and we can't support old, bugged versions.
Please update quickly to the latest Joomla! stable version: 3.6.5
