### ISSUE TITLE
Admin menu items still visible after unpublishing them

### ISSUE THREAD

**Issue by wschaapman** [joomla/joomla-cms#13696]
### Steps to reproduce the issue
I tested to skip some items in my admin menu. I unpublished them in the menu items (main protected).
Did a logout and a login, but items are still visible.

### System information (as much as possible)
Joomla 3.7 Alpha 2
Xampp, localhost, php5.6

**Comment by zero-24** [comment]
Closing as dublicate of https://github.com/joomla/joomla-cms/issues/13689
