### ISSUE TITLE
[CI] Integrate AppVeyor Support

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#13690]
This is mainly a placeholder for discussion before opening an actual PR.

AppVeyor support should be added to this repository.  AppVeyor is another continuous integration platform which offers testing support for GitHub repositories, except this platform specializes in supporting the Windows environment.  This would enable the test suite to be ran on a Windows environment and include test coverage for the Microsoft SQL Server database driver.  Even though SQL Server support will be phased out of the CMS in 4.0, it would still be beneficial to consistently run the test suite on the Windows platform and hopefully better be able to support it and address Windows specific items.

This is currently being integrated into the Framework's Database package, see https://github.com/joomla-framework/database/pull/72 for the current progress.

**Comment by Bakual** [comment]
Given the issues we get repeatedly on Windows systems, it sure makes sense to use that service

**Comment by mbabker** [comment]
After some trial and error we've finally got the database package's environment provisioned and executing properly - https://ci.appveyor.com/project/joomla/database/build/1.0.77

There are two issues to address now, both of which at first appearance seem to be more environmental/configuration related than code issues:

- https://github.com/joomla-framework/database/issues/74
- https://github.com/joomla-framework/database/issues/75

If anyone can help with solutions there that'll be helpful here too as most likely the same problems will need to be addressed.

**Comment by mbabker** [comment]
PR opened.
