### ISSUE TITLE
Disable 'hits' on articles, weblinks, etc.

### ISSUE THREAD

**Issue by xaddict** [joomla/joomla-cms#13695]
### Steps to reproduce the issue
- Start a site
- Test some pages, walk through them, have a crawler inspect missing alt tags, etc.
- Put the site in production
- Articles have hits on them already, bots count as hits, ddos count as hits...

### Expected result
A way to enable/disable activity tracking (hits) for the site
A way to reset hits.
A way to not use hits at all (preferable during the installation so not a single hit gets registered)

### Actual result
There's no way (outside of DB queries or third-party extensions) to remove the hit tracking, to enable/disable it for a while.

### System information (as much as possible)
Every Joomla that has hits
Every server
Every config

### Additional comments
In a time where almost every big site uses GA or equivalents the "just hit tracking" seems obsolete. It may be handy for small sites that don't want to use JS or tracking scripts, but for bigger sites it means more DB queries than necessary, and weird counters in the back don't represent actual people visiting the site.![screen shot 2017-01-23 at 09 44 39](https://issues.joomla.org/uploads/1/89e4318ce1401c34a17adeae728fc8c6.png)

**Comment by PhilETaylor** [comment]
I agree - I have actually stated many times that hit counting should be completely removed from Joomla - or at least be a global config setting

Hit counting to a database row invalidates mysql caching layers and can be resource intensive 

There are far better ways of hit counting in 2017...

**Comment by brianteeman** [comment]
closing this here so we have discussion in just one place and there are more comments at #15771
