### ISSUE TITLE
[com_fields] show up by default for example in mod_articles_news

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#13699]
### Steps to reproduce the issue
Create an article with custom fields and fill out one or more of these
Publish a newsflash module containing this article

### Expected result
Default should be to show up without custom fields + an option added to show them if wanted

### Actual result
- Custom fields will show up here and probably in all other modules, don´t know about 3rd party

### System information (as much as possible)
Joomla 3.7.0 Alpha 2

**Comment by Bakual** [comment]
Looking over the code, that module seems to be the only one supporting the onContentAfterTitel/BeforeDisplay/AfterDisplay events.
It should be simple to add a parameter which disables those events.

What I find more troubling is that the output uses an ID which will be the same eachtime that field is shown, eg `field-entry-14` for the field with the ID 14. So you get multiple IDs on your site, one for the article shown and again for the module.
Thus we need to get rid of the IDs when the field is shown in frontend (outside a form). They shouldn't be there to begin with.

**Comment by Bakual** [comment]
See #13703 for the new parameter and #13702 for the duplicate ID issue.

Closing as we have PRs.
