### ISSUE TITLE
[com_fields] no "real" global options available

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#13700]
### Steps to reproduce the issue
Navigate to
 /administrator/index.php?option=com_fields&context=com_content.article
or
/administrator/index.php?option=com_fields&view=groups&context=com_content.article

### Expected result
You should have some global options for custom fields there, for example:
- where they appear (Article, Blog, Intro, Detail, Modules) 
- If labels are shown by default or not

### Actual result
there is just one Option below the "Integration" Tab for enabling Custom Fields or not...

### System information (as much as possible)
Joomla 3.7.0  alpha 2

**Comment by Bakual** [comment]
There are no global component configs for com_tags, similar to com_categories.
The only "global" setting is coming from the "System - Fields" plugins. There you can specify the default appearance for the fields.

> there is just one Option below the "Integration" Tab for enabling Custom Fields or not...

That one is actually an option from com_content.

If we want to add global options to the com_fields component, it means we have to rewrite the component a bit so it can work standalone (eg it needs a menu item and you can switch between extensions from within it).
As it is now it tries to blend in with the "parent" extension (eg com_content). Similar to com_categories.

So it's basically an UX question in the end. Technically, it's possible to change it.

**Comment by coolcat-creations** [comment]
Either we would have to remove the Options there then or solve it like you propose... I´d prefer the second to have consistency in the CMS.

**Comment by laoneo** [comment]
I think this proposal would more confuse people. You are also not able to enable the images fields of an article for specific modules or menu items.

**Comment by Bakual** [comment]
> Either we would have to remove the Options there then or solve it like you propose... I´d prefer the second to have consistency in the CMS.

Actually, the current state is consistent with how it is done for categories. They are done by com_categories but the options button goes to the respective extension (eg com_content).

As Allon said, you would not be able to say where fields should appear (eg not in modules). Com_fields doesn't have any knowledge about that.
That's the job of setting up the fields correctly and having the right overrides in place.

**Comment by franz-wohlkoenig** [comment]
closed as Expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13700">issues.joomla.org/tracker/joomla-cms/13700</a>.</sub>
