### ISSUE TITLE
[com_fields] [feature request] Ability to hide field label on front end

### ISSUE THREAD

**Issue by brianpeat** [joomla/joomla-cms#13707]
### Steps to reproduce the issue
Because the field label is required, the best you can do to not show the label is put a space in the label field.

### Expected result
A check box that lets you remove the label from the front end render (leaving it showing in the fields tab in the article editor).

### Actual result
If you put a space in the label field, the label still renders the space and the : mark after it, making the output look really odd.

### System information (as much as possible)
I'm using the JUX dev install, PHP 7.1.0, MySQL 5.6.28-76.1-log

### Additional comments
The goal here is to make custom fields as flexible as possible before resorting to overrides and custom css. To give users more out of the box functionality.

**Comment by brianpeat** [comment]
Here's a screen shot of putting a space in the label for a Text-area type field:![screen shot 2017-01-23 at 14 39 56](https://issues.joomla.org/uploads/1/8b9728c527b7890b73b33f7e3628cca9.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13707">issues.joomla.org/tracker/joomla-cms/13707</a>.</sub>

**Comment by brianpeat** [comment]
Okay, I figured this out tonight and added it to my build. Tomorrow I'll sort out a pull request. There's a change to the DB so I have to figure out how that works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13707">issues.joomla.org/tracker/joomla-cms/13707</a>.</sub>

**Comment by Bakual** [comment]
Before you do a PR. Did you try creating a user.css with the following rule
````
.hidelabel .field-label {
  display:none;
}
````
and then add `hidelabel` as the renderclass into the field?

**Comment by laoneo** [comment]
@brianpeat if you put the hide label option into params, then you don't need to change the table layout.

**Comment by brianpeat** [comment]
@Bakual I don't want the user to have to put in a class to hide the label. That's like the worst user experience ever. :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13707">issues.joomla.org/tracker/joomla-cms/13707</a>.</sub>

**Comment by Bakual** [comment]
> I don't want the user to have to put in a class to hide the label. That's like the worst user experience ever. :)

Imho, Joomla suffers from to many parameters where the same thing could be achieved with a CSS class and some simple CSS rules.

**Comment by franz-wohlkoenig** [comment]
@Bakual It depends: Knowing CSS is easy to manage a Site, if not (like me Years ago) all is "complicated". So if Joomla wants Users with less Experience it is easier to work with parameters (if they work).

**Comment by brianpeat** [comment]
I love css, but I'd much rather have one more switch in there than have to remember to use a class. It also means users with no css experience will have to google how to hide the label. To me that's a bad experience.

**Comment by Bakual** [comment]
One option would be what we did for the "Caption Class" in the editor image plugin. There we suggest some classes which are supported by most templates using a datalist. Of course then the CSS rules would have to be in our templates to work.

**Comment by Bakual** [comment]
Closing as we have a PR
