### ISSUE TITLE
[com_fields] Warnings on Type "Gallery"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#13706]
### Steps to reproduce the issue
Tested Field-type `Gallery` on Article got on different Paths using Front- or Backend: 
- `Warning: JFolder: :files: Path is not a folder. Path: __/images/images/sampledata/fruitshop` 
- and ` Picture-Gallery: Warning: Invalid argument supplied for foreach() in /plugins/fields/gallery/tmpl/gallery.php on line 50`
![1](https://cloud.githubusercontent.com/assets/8235763/22207442/75e92ec4-e17f-11e6-8933-34311cab7738.JPG)
### System information (as much as possible)
Joomla! 3.7.0-beta1-nightly
macOS Sierra, 10.12.2
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by Bakual** [comment]
See #13726
