### ISSUE TITLE
[4.0] CS tests fails ..

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#13719]
### Steps to reproduce the issue

https://travis-ci.org/joomla/joomla-cms/jobs/194531446

### Expected result

Cs test passes

### Actual result

CS tests fails ...

**Comment by C-Lodder** [comment]
tests need to be re-written to cater for BS4

**Comment by zero-24** [comment]
> tests need to be re-written to cater for BS4

? Should have been done before we merge it into the core?

First Part: https://github.com/joomla/joomla-cms/pull/13723

**Comment by zero-24** [comment]
Seccond part: https://github.com/joomla/joomla-cms/pull/13724

@wilsonge please review and merge so we can be sure we are ok.

**Comment by photodude** [comment]
@C-Lodder What in the Code standards need to be rewritten?

I'm not seeing anything other than files that are no longer excluded that have code style issues. (some of these can be fixed with the auto fixers in the PHPCS 2 version of the coding standards See https://github.com/joomla/coding-standards/issues/143 for items relating to the upcoming Alpha release)

**Comment by C-Lodder** [comment]
@photodude - Code Standards for Bootstrap?

Were there any for BS2? If so, could I have a link please to get a better idea

**Comment by photodude** [comment]
@C-Lodder our current (needing revision) code standards for JS are here in the manual (until the gh-pages find a new home) http://joomla.github.io/coding-standards/?coding-standards/chapters/javascript.md

but JS files and mixed php/html files are not CI checked for code standards. We currently only check pure PHP files (and not all of them).

**Comment by C-Lodder** [comment]
Ah didn't know the CS page had requirements for CSS. I'll make the necessary updates for the SCSS tomorrow.

**Comment by photodude** [comment]
Yep we have CS items for 
PHP Code
XML
and the Clientside Syntaxs
HTML
CSS
JavaScript

**Comment by C-Lodder** [comment]
@photodude : https://github.com/joomla/coding-standards/pull/146
