### ISSUE TITLE
Fix Class Names & Doc Blocks from Namespacing

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#13721]
Not urgent, but the now namespaced MVC classes shouldn't use the aliases otherwise when we run the job to build https://api.joomla.org it'll make some of the navigation not work right (i.e. it won't link to the class it extends if it's using an alias without creating a stub class when running the job).  So at some point this should use the "correct" class names.

Also, the file doc blocks don't need the package/subpackage tags in namespaced classes.  Those are really only there to be able to group stuff for the API documentation output (which has been semi-broken in phpDocumentor for a while anyway unfortunately).  See https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Cms/Session/Storage/JoomlaStorage.php for an example of a file doc block being used on the namespaced code in the 4.0 branch (I think we had to make a change to the PHPCS ruleset to make it work right there, check that directory and backport the change if necessary).

**Comment by laoneo** [comment]
It should be changed as with the merge of Views and Models. Can you have a lok please, I guess it is solved.

**Comment by mbabker** [comment]
The class extensions are fine, just needs the file doc block updates now.

**Comment by laoneo** [comment]
I'v adapted them to the doc block in the 4 branch directly in this PR #13765 with commit https://github.com/joomla/joomla-cms/pull/13765/commits/2aba65c7439937a610f2d18ac135064342fc64ea
