### ISSUE TITLE
[com_fields] Easier implementation in Overrides and Alternate Layouts

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#13735]
If you want to include a custom field in your Override you have to use following code:

`<?php

// Article-Fields Mapping

foreach ($item->fields as $field) {
	$item->fieldalias[$field->alias]=$field->id;
}

$itemfield = $item->fieldalias;

echo $user->fields[$userfield['authorinfo']]->value; ?>`

Would be great if it´s possible to call the fields in com_content, com_contact and the core modules with a simpler syntax. At least without the need to map it everywhere? Is this possible?

Thanks!

**Comment by laoneo** [comment]
You don't really have to do that. Just use `$item->fields[43]` when you know the id and all is good.

**Comment by coolcat-creations** [comment]
thanks... i close it then ;)
