### ISSUE TITLE
[com_fields] com_contact: field is disabled within a field group if you extend the Formular

### ISSUE THREAD

**Issue by ufuk-avcu** [joomla/joomla-cms#13753]
### Steps to reproduce the issue
Install a clean Joomla 3.7 Alhpa 2
Go to Joomla Backend -> com_contact -> Fields -> Choose "Mail" (left from the search) -> New -> Choose Type "Text" -> Title e.g. "Test input field"
If you do this steps correctly, then everything works a excepted and you have an additional field in your Contact Form(please don't forget to fill out the Mail Field, to see the Contact Form in the Frontend).

If you now Create a Field Group with in com_contact and Assign my Field "Test input field" to this new Group, then the Additional input field is disabled and you can't type your text in this field in the frontend anymore.

![fireshot capture 10 - kontakt - http___projekte joomla-agentur de_37_en_kontakt](https://cloud.githubusercontent.com/assets/13818234/22298969/a3bfe2e4-e322-11e6-9611-7f5f5c4b6dfb.png)

### System
Joomla 3.7 Alpha 2
PHP 7.0.9
MariaDB

**Comment by Bakual** [comment]
This should already be fixed with https://github.com/joomla/joomla-cms/pull/13676. Can you try with a current staging?

**Comment by laoneo** [comment]
@ufuk-avcu is this fixed with the pr #13676? Can you please test it again with the latest staging. Thanks.

**Comment by franz-wohlkoenig** [comment]
Tested with latest staging and master, Issue isn't fixed.

**Comment by Bakual** [comment]
Looks fine to me:
![mail](https://cloud.githubusercontent.com/assets/1018684/22384146/5647d34e-e4cd-11e6-81bb-3abb66af8360.PNG)

Make sure to create new groups and fields. Don't test with existing ones as the asset entry may be borked there.

**Comment by franz-wohlkoenig** [comment]
My fault: Permissions "Public > Edit Custom Field Value" was Default on "Not Allowed". Changing on "Allowed" now works.

**Comment by ufuk-avcu** [comment]
Tested it again with the staging from today. After i changed the Permissions like @franz-wohlkoenig suggested, the frontend submission works now. Maybe we should consider, to change this default setting...

**Comment by laoneo** [comment]
In DPFields I'v defaulted it to allowed. Don't know if this behavior should be done for the core as well?

**Comment by Bakual** [comment]
ACL settings always have to default to disallow if not explicitely allowed.
By default, fields rightfully should not be allowed to be changed in most cases. At least for public.
You will want it only for the mail in com_contact and in the registration of users. In all other cases, there should be at least a registered user or even hight (eg author).
But then, you can't even set com_contact to allow it for public, because you don't want that for the contacts itself, only for the mail.
Good luck trying to set sane default values for that. 😄

**Comment by franz-wohlkoenig** [comment]
There are now Issues about "field not editable" by experienced two People. Expecting more after 3.7-Release default should be allowed.

**Comment by laoneo** [comment]
Can we close this issue as it looks like it is fixed, or?
