### ISSUE TITLE
Search results show wrong link to archives articles - result in 404

### ISSUE THREAD

**Issue by wezetel** [joomla/joomla-cms#13757]
### Steps to reproduce the issue
Create article
set article to archived
do a Joomla search for article
click on search result

### Expected result
article shows up

### Actual result

404 error

### System information (as much as possible)

Joomla 3.6.5

### Additional comments
Using standard Joomla search, not archive modul

**Comment by franz-wohlkoenig** [comment]
cannot confirm issue, archived Article is shown, no 404, tested on Joomla 3.6.5.

**Comment by wezetel** [comment]
1.
Look at http://starzach.de
enter in search box 'christkindlesexpress'
One result ist shown 'Eyachtäler Christkindlesexpress ' (http://starzach.de/aktuell/archiv/2016/12)
Clicking on result link shows 404 error

2.
Go to Aktuell->Archiv
Filter with date Dezember 2016
Article is shown
Link is working (http://starzach.de/aktuell/aktuell/638-eyachtaeler-christkindlesexpress)

**Comment by stellainformatica** [comment]
I confirm the issue. 
There's the issue only if you create a menu item type Articles » Archived Articles
In my case I don't see a 404 error page, but another article when I click on the link on the results page<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13757">issues.joomla.org/tracker/joomla-cms/13757</a>.</sub>

**Comment by Hardyst** [comment]
I can confirm this issue.
Go to [http://bibliothek.hammelburg.de/archiv](http://bibliothek.hammelburg.de/archiv)
Set filter to Nov 2016
You will see a article "Alle meine Schätze: Hannes sammelt Traktoren " and the link on the title is working.
Now when you search for "traktoren" in the site search you got a link to this article but when you click you get a 404
[http://bibliothek.hammelburg.de/component/search/?searchword=Traktoren&searchphrase=all&Itemid=149](http://bibliothek.hammelburg.de/component/search/?searchword=Traktoren&searchphrase=all&Itemid=149)

**Comment by kortex123** [comment]
Same issue to my website. Is there a fix?

**Comment by franz-wohlkoenig** [comment]
set Status "Needs Review" on Issue Tracker.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13757">issues.joomla.org/tracker/joomla-cms/13757</a>.</sub>

**Comment by teokolo** [comment]
I confirm the issue (Joomla 3.6.5) and I found another router problem (bug or wrong design).

I had a category menu item showing articles in MYCAT category, urls were like:

/news/33-my-first-news
/news/38-another-news

I archived all articles in MYCAT category, created archived articles menu item, now urls are:

/news/12-MYCAT/33-my-first-news
/news/12-MYCAT/38-another-news

This leads to duplicate content problem since article can be accessed by both urls.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13757">issues.joomla.org/tracker/joomla-cms/13757</a>.</sub>

**Comment by wezetel** [comment]
I upgraded to Joomla 3.7 and the issue is still open, **but the symptoms have changed**.

In 3.6.5. the link to an archived article in the search result list led to an 404 error or (as some reported) to the incorrect article.

In 3.7. the link to an archived article in the search result list opens the archive filtered by the month of the found article. **And it's really just the month**!

So take the example I gave in the third post in this thread: the search shows the archived article, but clicking the link opens up the archive filtered by December of all years (2016, 2015, 2014,...)!

I would expect the link in the search result list will take me directly to the archived article and not open up the archive view.

**Comment by stellainformatica** [comment]
Hi wezetel,
have you tried in a fresh install of Joomla 3.7?
I tested, but can't reproduce the issue, now for me it's working correctly

**Comment by wezetel** [comment]
Hi stellainformatica,
no, I didn't try on a fresh install (btw.: this is not an option for my production site). When I find some time I will clean up a test site and try a virgin joomla install.
Not sure, if you have had a look at the example I mentioned. You can also check the example @Hardyst  mentioned on the 3rd of March. Same behaviour as on my site.

**Comment by Quy** [comment]
@csthomas You are very knowledgeable with router. Would you look into this? Thank you!

- Install `Test English (GB) Sample Data`.
- In the front end, search for `What's New in 1.5?`.
- Click on the link. See the URL `http://localhost/joomla-cms-staging/index.php/archived-articles/2011?view=archive&month=1`
- View page source. Find `<base href="http://localhost/joomla-cms-staging/index.php/archived-articles/2011" />`. This link cannot be found. `2011` should not be in the URL.

Reported before: https://github.com/joomla/joomla-cms/issues/7084#issuecomment-134155328

If the URL is changed to: `localhost/joomla-cms-staging/index.php/archived-articles/2011/01?view=archive`

```
Warning: array_diff(): Argument #1 is not an array in C:\xampp\htdocs\joomla-cms-staging\components\com_content\models\archive.php on line 87

Warning: array_values() expects parameter 1 to be array, null given in C:\xampp\htdocs\joomla-cms-staging\components\com_content\models\archive.php on line 87
```

**Comment by csthomas** [comment]
I see two issues:
1. I do not understand the behaviour of the search plugin. When the plugin found a published article then generates a link to the article but when the article is archived then generates link to list of archived articles based on year and month.
This is very old commit, which changed that.
`e92eaa53ce 2010-12-14   # [#23764] Search Results have issues with SEF (Error: 500)`
\
I can fix it by changing link to the article, I mean revert the above. But it may break somehow B/C.
When I leave Itemid of archive view then the article may have two different (duplicated) URLs:
as published `/category-alias/id-article-alias` 
and as archived `archived-articles/category-alias/id-article-alias`
\
The second one for me is wrong.

2. Parse and building of URL routing for the archived view are inconsistent.

**Comment by Quy** [comment]
If the URL in the search results,
```
http://localhost/joomla-cms-staging/index.php/archived-articles/2011?view=archive&month=1
```
can be changed so that the year is in the query
```
http://localhost/joomla-cms-staging/index.php/archived-articles/?view=archive&month=1&year=2011
```
then it will omit/fix the year in the URL:
```
<base href="http://localhost/joomla-cms-staging/index.php/archived-articles/2011" />
```

The duplicate URLs is [mentioned here](https://github.com/joomla/joomla-cms/issues/13757#issuecomment-294707515) 4 postings up.

**Comment by Quy** [comment]
See #19397<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13757">issues.joomla.org/tracker/joomla-cms/13757</a>.</sub>

**Comment by wezetel** [comment]
The pull request 19397 doesn't fix the original problem, but at least the omitted year in the search result is solved.
But I would expect to have a direct link in the search result, even if the found article is in the archive. 
At the current point in time the (archived) article is shown in the search result, but links to the archive and there you need to manually search for the article (could be annoying, if you have big archives). So no real search function.
I have to admitt: so the user should be aware that the found article is in the archive.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13757">issues.joomla.org/tracker/joomla-cms/13757</a>.</sub>

**Comment by BlackBrix** [comment]
I can confirm wezetel's last comment even with Joomla 3.9.4 it's still the same issue:
- why in the search result list the links to archived articles only leads to the archive month (where can be dozens of articles then) -> instead it should link directly to the archived article like it is the way with all other search results too ....

this is extremely annoying.

----

beside of that: the mentioned pull request 19397 addresses a completely different problem,
and even this problem is still there in 3.9.4 when you looking on the search result list:
the links to the archive month are still built without the "year" as the correct parameter -> so the archive month of all existing years opens ... 
this last issue with the missing year occurs only when you have SEO turned ON
