### ISSUE TITLE
Bootstrap grid - Spans wrapping between 768px - 979px

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#13768]
The Bootstrap responsive grid has some issues between 768px and 979px browser width. Spans/columns wrap when they should remain inline.

The issue appears to be due to an incorrect margin-left calculation (@fluidGridColumnWidth768)...  https://github.com/joomla/joomla-cms/blob/staging/media/jui/less/variables.less#L273-L300

In Isis, commenting out each of the following does resolve the issue however before I go creating a PR, I would appreciate some further thoughts from anyone with a better understand of each of these less files. I realise they are changing the gutter width however they appear to be doing so incorrectly for this instance. If they can't be fixed maybe it would be best to remove them..

https://github.com/joomla/joomla-cms/blob/staging/administrator/templates/isis/less/template.less#L62
https://github.com/joomla/joomla-cms/blob/staging/administrator/templates/isis/less/template.less#L64

**EDIT**: On further inspection, comparing versions compiled by lessc and an alternative compiler, it is the span widths that are incorrect rather than the margin-left.. https://github.com/joomla/joomla-cms/blob/staging/administrator/templates/isis/css/template.css#L352-L399

### Steps to reproduce the issue
Navigate to article edit and reduce the browser window. Columns wrap prematurely..

### Expected result
![grid2](https://cloud.githubusercontent.com/assets/2803503/22330408/00940a22-e3be-11e6-9082-10f9ea67f98e.gif)

### Actual result
![grid1](https://cloud.githubusercontent.com/assets/2803503/22330460/42f86eee-e3be-11e6-8d90-e3138a18b0d8.gif)

**Comment by mbabker** [comment]
I don't think it's the LESS files.  I think it's the compiler.  I have fought with similar grid related issues on the `joomla.org` site template and ultimately said "screw it" and changed to using Bootstrap's old recess compiler versus the lessc library.  Fixed all of my issues.

**Comment by ciar4n** [comment]
You have mentioned this before but only now checking it out for myself.. using an alternative compiler does indeed resolve the issue. Considering this and presuming changing the compile method won't fly maybe getting Isis to load it's own version of [responsive-768px-979px.less](https://github.com/joomla/joomla-cms/blob/staging/media/jui/le) might be the best option. We can replace the calculated variables with the correct static values, making it less likely for `lessc` to mess up?

**Comment by Bakual** [comment]
Can't we fix the lessc compiler upstream then? I have no clue where the issue comes from but sounds like the right approach to fix it :smile:

**Comment by C-Lodder** [comment]
It's over 2 years old. Perhaps consider using a more modern solution?

**Comment by dgt41** [comment]
I could write a small grunt script for compiling less to CSS and .min.css if that's ok for 3.x

**Comment by C-Lodder** [comment]
That would mean everyone having to download Node. I wouldn't suggest that for a minor update. It also doesn't really help the end user who may want to make LESS changes via the Template Manager

**Comment by dgt41** [comment]
The other option is to switch to https://github.com/oyejorge/less.php which apparently also seems outdated...

**Comment by C-Lodder** [comment]
or a JS library

**Comment by mbabker** [comment]
That `less.php` library doesn't have a compatible license for us to ship it.  We got away with it for Bootstrap but I doubt it would fly for a PHP library.

**Comment by ciar4n** [comment]
I think the issue with lessc is what is suggested here.. https://github.com/leafo/lessphp/issues/352 

Personally I think compiling with Node (for Isis at least) is the way to go. If a user is familiar with LESS, the chances are they are also familiar with using Node.

**Comment by C-Lodder** [comment]
I wouldn't agree with making people have to use Node to compile in a minor version update. Should stick to 4.x for that

**Comment by ciar4n** [comment]
After that then the only likely alternative is to override the lessc output with a corrected version in the  template.less?

**Comment by mbabker** [comment]
I don't know what's being cached by lessc, but I know something is.  Whether it's the mixin results, variable values, or something else, I have no idea.  But I know it has resulted in me labeling that library as unusable.

**Comment by ciar4n** [comment]
PR replacing the values calculated by lessc with the correct values.. #13845
