### ISSUE TITLE
Logout menu item redirect problems

### ISSUE THREAD

**Issue by fdesanto** [joomla/joomla-cms#13764]
### Steps to reproduce the issue
- Joomla Fresh Installation
- Create a menu item of type Users->Logout from backend and set redirect to "Home Page"
- Enable "Allow user registration" in com_user options from backend
- CASE1: Into frontend try to put wrong credentials
- CASE2: From a login module, click to link "Create an Account"

### Expected result
- RESULT1: Redirect to login page with wrong credentials message
- RESULT2: Redirect to registration page

### Actual result
- RESULT1: Redirect to home page
- RESULT2: Redirect to home page

### System information (as much as possible)
This problem happen because functions like: `JRoute::_('index.php?option=com_users&view=login')` or `JRoute::_('index.php?option=com_users&view=registration')` inherits Itemid of logout menu item (when missing menu item of type Users->Login or Users->Registration).

**Comment by infograf768** [comment]
Have you tested this on staging/3.7. alapha2?

**Comment by fdesanto** [comment]
Hi,
I have tested on 3.7.0-dev and 3.6.5

**Comment by fdesanto** [comment]
Redirect to home page happen also when you try to use the link to create an account from login page:
### How to reproduce
- Go to index.php?option=com_users&view=login (not SEF)
- You will show a login form
- Click to link "Don't have an account?"
RESULT: Redirect to home page

**Comment by fdesanto** [comment]
Hi,
confirmed, this happen also on staging/3.7. alpha2

**Comment by franz-wohlkoenig** [comment]
Cannot confirm Issue. On latest staging tested on 

- Login-Menu (Login-Module disabled): Click on `Don't have an account` opens `/index.php/login?view=registration` 
- Login-Module (Login-Menu disabled): Click on `Create an account` opens `/index.php/component/users/registration?Itemid=101`

**Comment by fdesanto** [comment]
Hi @franz-wohlkoenig,
of course, 
**your first case**: you have a menu item of type Users->Login, the bad behavior happen when you does not have any other menu item from com_users (only logout menu item).
**your second case**: seems that you not have a menu item of type Users->logout (with redirect url), otherwise you will have a link like "/logout/?view=registration"

with only logout menu item you have this routing (with SEF)
profile page: /logout/?view=profile
edit profile: /logout/?view=profile&layout=edit
registration: /logout/?view=registration
login:  /logout/?view=login

but if is set also a redirect parameter for logout menu item then above links go to redirect Url

**Comment by franz-wohlkoenig** [comment]
> CASE1: Into frontend try to put wrong credentials

What happens if Logout-Menu is set on `public`:
#### Legacy Router
- no SEF:
Redirect to login page with `Warning: Username and password do not match or you do not have an account yet.`
- SEF, no URL-Rewriting / SEF, URL-Rewriting:
Redirect to Homepage page with `Warning: Username and password do not match or you do not have an account yet.`
#### Modern Router (with and without `Remove IDs from URLs`)
- no SEF:
Redirect to login page with `Warning: Username and password do not match or you do not have an account yet.`
- SEF, no URL-Rewriting / SEF, URL-Rewriting:
Redirect to Homepage page with `Warning: Username and password do not match or you do not have an account yet.`

Change Access of Logout-Menu on `Registered` got expected Result: Redirect to login page with `Warning: Username and password do not match or you do not have an account yet.`

**Comment by fdesanto** [comment]
Thanks franz,

> Change Access of Logout-Menu on Registered got expected Result: Redirect to login page with Warning: Username and password do not match or you do not have an account yet.

Yes, it did the trick, I think that is better to add some check in the function **menulogout** in file /components/com_users/controllers/user.php like
```
public function menulogout()
{
     if(JFactory::getUser()->id)
     {
         // HERE CODE FROM menulogout
     }
}
```

**Comment by franz-wohlkoenig** [comment]
@fdesanto can you please confirm Issue on latest Staging?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13764">issues.joomla.org/tracker/joomla-cms/13764</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened in the future if it is updated.
