### ISSUE TITLE
Joomla component is been triggered twice when a module is assigned to its menu item

### ISSUE THREAD

**Issue by codeChap** [joomla/joomla-cms#13771]
### Steps to reproduce the issue
1. Take the article component and add the following log code to the end of the content.php file.
		$string = time() . PHP_EOL;
		$resource = fopen(__DIR__.DIRECTORY_SEPARATOR."test.log", "a");
		fwrite($resource, $string);
		fclose($resource);

2. Create an article and assign a menu item to it
3. Create a module and assign it to the same menu item
4. View the article you created, you will notice that the timestamp is created twice.
5. Un-publish the module and it will be triggered once.

### Expected result
There should only be one timestamp log per view of the article.

### Actual result
Timestamp logs are produced twice on each view of the article

### System information (as much as possible)

- Joomla 2.6.5
- Same results on PHP 5.6 and 7
- Mac OS
- Nginx
- Mysql 5.5.53

### Additional comments
While the content is not reproduced. If you were pulling from an API, that provided something large like images. You dont want to be running the same query twice.

**Comment by codeChap** [comment]
![screen shot 2017-01-26 at 22 49 12](https://cloud.githubusercontent.com/assets/451621/22349740/bc3ab298-e419-11e6-9227-88931ccfa119.png)

**Comment by codeChap** [comment]
Oops

**Comment by bertmert** [comment]
I cannot reproduce the issue as described with Joomla 3.7.0. Which module type did you use? Any special settings in article, menu item, module?

**Comment by codeChap** [comment]
It did not matter what module was used, I'll test against 3.7 and get back to you.

**Comment by Bakual** [comment]
Can't reproduce it either on staging.

Maybe check if there is a redirect happening for some reason, then that would explain the double loading.

**Comment by codeChap** [comment]
I can't reproduce this on a fresh installation of 3.7, I can when I install the template used. So not a Joomla issue. Thanks for looking guys. Sorry for any time waisted.

**Comment by codeChap** [comment]
In the template when you use the countModules or getModules i.e.:
JModuleHelper::getModules('left')
  or
$this->countModules('left');

The component is triggered twice.
