### ISSUE TITLE
Module Menu Assignment shows custom admin menus

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#13783]
### Steps to reproduce the issue
* Create a custom administrator menu
* Edit a module and change the "Module Assignment" in the "Menu Assignment" tab to "Only on the pages selected"

### Expected result
A list of frontend menus

### Actual result
All menus are listed, front- and backend:
![menu assignment](https://cloud.githubusercontent.com/assets/1018684/22388296/29e2ca8a-e4e0-11e6-96c0-fd3c17a084a9.PNG)

### System information (as much as possible)
Current Staging (2017-01-27)

### Additional comments
None

**Comment by infograf768** [comment]
Closing as we have a patch

https://github.com/joomla/joomla-cms/pull/13788<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13783">issues.joomla.org/tracker/joomla-cms/13783</a>.</sub>

**Comment by Bakual** [comment]
See #13791 for a better fix (imho).
