### ISSUE TITLE
How to build zip installer from Pull Request of Staging?

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [joomla/joomla-cms#13781]
I'm having some disagreements with Travis and I need to build an installer using my branch where I'm making changes, but I don't know how to do this.  Can someone please enlighten me?

**Comment by mbabker** [comment]
https://docs.joomla.org/Build_Test_Packages_From_A_Release_Branch

**Comment by Napoleon-BlownApart** [comment]
Thanks, done.
But, how do I trick Joomla into accepting a core update package from a local URL (or file)?  So I can test the update installer.

**Comment by Bakual** [comment]
Components -> Joomla Update -> "Upload & Update" tab -> Select your zipfile and hit the button. That should do the update.

**Comment by rdeutz** [comment]
not a bug

**Comment by Napoleon-BlownApart** [comment]
I don't have a "Upload & Update" tab in the 3.4.8 version I'm upgrading from.

**Comment by Bakual** [comment]
Yep, that doesn't exists in that version. Try updating from a 3.6.5.
YOur 3.4.8 installation should be updated to 3.6.5 anyway.

**Comment by Napoleon-BlownApart** [comment]
I updated to 3.6.5 and that has the tab.  My 3.4.8 install is on a dev server virtual host that I could sacrifice.
