### ISSUE TITLE
[custom_fields] com_users registration FE. field not editable. form forgets entered datas.

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#13796]
### Steps to reproduce the issue

Install current staging (2017-01-29) 

##### Backend:

- Users > Manage > Fields > New

Title: City
Type: Text
Label: City

Required: Yes
Disabled: No
Read-Only: No

- Save

- Users > Manage > Options button > Allow User Registration > Yes

- Save

##### Frontend: 

- Scroll down to login module > Click on Create an account

###### Actual result

**Required field city is disabled!** It's not possible to enter something.

![29-01-_2017_12-19-43](https://cloud.githubusercontent.com/assets/11038612/22403729/8e613f82-e620-11e6-96ec-46d799c2d48b.jpg)

- Fill registration form and click Register button:

###### Actual result

- Above a warning (which should be a red error, I think)

- All fields are empty now and user must fill them again.

![29-01-_2017_12-22-02](https://cloud.githubusercontent.com/assets/11038612/22403731/9ff8bd38-e620-11e6-99db-a920a593abfe.jpg)

### Expected result

- Try again without custom field: 

![29-01-_2017_12-31-46](https://cloud.githubusercontent.com/assets/11038612/22403742/f7312edc-e620-11e6-86cb-507fe1659ff7.jpg)

- Try again without custom field but with activated plugin User - Profile and a required field:

![29-01-_2017_12-33-42](https://cloud.githubusercontent.com/assets/11038612/22403743/01de1c28-e621-11e6-9a17-eb7d57196c15.jpg)

### System information (as much as possible)

PHP Built On 	
Linux dd1620 3.13.0-107-generic #154-Ubuntu SMP Tue Dec 20 09:57:27 UTC 2016 x86_64
Database Version 	
5.5.52-nmm1-log
Database Collation 	
utf8_general_ci
Database Connection Collation 	
utf8mb4_general_ci
PHP Version 	
7.0.14-nmm1
Web Server 	
Apache
WebServer to PHP Interface 	
fpm-fcgi
Joomla! Version 	
Joomla! 3.7.0-beta1 dev [ Amani ] 18-January-2017 20:28 GMT
Joomla! Platform Version 	
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by franz-wohlkoenig** [comment]
Permissions of Field set on "Allowed"? Similar #13753

**Comment by bertmert** [comment]
No.
Sounds like a bad joke. Users have to set Status, then **Access** and additionally tricky Permissions. If these permissions don't match for context in frontend (even if Access matches) forms are displayed but blocked... Joomla ACL is complicated enough for stupid users like me yet...

**Comment by franz-wohlkoenig** [comment]
@bertmert so Permissions are set correct, but field is not editable?
