### ISSUE TITLE
Fields received from $form->getFieldset('name') and $form->getField('name', 'group') are different

### ISSUE THREAD

**Issue by tgv604** [joomla/joomla-cms#13807]
There's a plugin that adds a bunch of user profile fields and also dynamically changes fields visibility depending on current layout (i.e. makes certain fields hidden on registration layout). After a recent upgrade the dynamically set "hidden" attribute stopped working the way it did. 

### Steps to reproduce the issue

- Enable existing "profile" plugin,
- within `onContentPrepareForm()` function, apply "hidden" attribute to some field, e.g. 
```
$form->setFieldAttribute('dob', 'type', 'hidden', 'profile');
```

in my case, it's conditional
```
if ($form->getName() == 'com_users.registration') {
    $form->setFieldAttribute('dob', 'type', 'hidden', 'profile');
}
```

### Expected result

a field would become hidden (on registration if conditional)

### Actual result

it is still visible in case the field is received through iteration:
```
foreach ($this->form->getFieldsets() as $fieldset) { // Iterate through the form fieldsets and display each one.
	$fields = $this->form->getFieldset($fieldset->name);
...
	foreach ($fields as $field) {// Iterate through the fields in the set and display them.			
		if ($field->hidden) {
			echo $field->input;
		} else echo $field->renderField();
	}
}
```
But it is hidden if I add an extra step:
```
foreach ($this->form->getFieldsets() as $fieldset) { // Iterate through the form fieldsets and display each one.
	$fields = $this->form->getFieldset($fieldset->name);
...
	foreach ($fields as $f) {// Iterate through the fields in the set and display them.			
		$field = $this->form->getField($f->fieldname, $f->group);
		if ($field->hidden) {
			echo $field->input;
		} else echo $field->renderField();
	}
}
```

### System information (as much as possible)

PHP 5.6.28

### Additional comments

I believe the bug was introduced with J3.6.5 update

**Comment by franz-wohlkoenig** [comment]
@tgv604 can you confirm this Issue in latest staging?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13807">issues.joomla.org/tracker/joomla-cms/13807</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened in the future if it is updated.
