### ISSUE TITLE
[com_finder] Advanced Search: Add more Space at Bottom of "Search by *"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#13811]
### Steps to reproduce the issue
Open Menu "Search" with advanced Search enabled:
![1](https://cloud.githubusercontent.com/assets/8235763/22434960/787848ba-e71e-11e6-8a5b-6217658803bc.JPG)

Needs more Space at Bottom of "Search by Author", "Search by Category",… to see Title and Dropdown-Field as Unit.
#### Test on:
Joomla! 3.7.0-staging
macOS Sierra, 10.12.3
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by franz-wohlkoenig** [comment]
@ciar4n can you please have a look on this Issue?

**Comment by ciar4n** [comment]
PR created: #13927
