### ISSUE TITLE
“Image Title” not shown in Tiny MCE “Insert/Edit Image” Dialogue

### ISSUE THREAD

**Issue by michaelhq** [joomla/joomla-cms#13818]
When an image is added with the «Image» dialogue in TinyMCE, there are input fields for “Im-age Description” and “Image Title” (cf. figure 1).

The image title pops up when on the webpage the mouse cursor is hovering over the image. The image description is used, when the image is not displayed e.g. in a text based browser like lynx or for barrier-free display of the webpage.

![screen shot 2017-01-31 at 10 25 44](https://issues.joomla.org/uploads/1/b5d7a45b856b90e53235889085e8435c.png)

The source code generated by the editor for the example in figure 1:

```
<figure><img title="Powered By - Image Titel" src="images/powered_by.png" alt="Powered By - Image Description" />
<figcaption>Powered By - Image Caption</figcaption>
</figure>
```

The following problem occurs only, when in the TinyMCE editor setting the “Functionality” is set to “Extended”. With the setting on “Extended” (the only useful mode in my honest opinion), there is a function to edit the image of an already inserted in an article (menu “Insert” -> “Insert/edit image” or button with image icon). There the image description is displayed, but not the image title (figure 2).

![screen shot 2017-01-31 at 10 25 44](https://issues.joomla.org/uploads/1/dbb2d135942d8a46677ea61501b92196.png)

However, TinyMCE supports to edit the image title: https://www.tinymce.com/docs/plugins/image/#image_title

It is only not enabled in the Joomla implementation of TinyMCE.

If the following line is added after line 926 in “plugins/editors/tinymce/ tinymce.php” (version from joomla 3.6.5), the image title is displayed and can be edited (cf. figure 3).

```
924			image_advtab: $image_advtab,
925			height : \"$html_height\",
926			width : \"$html_width\",
			image_title: true,
927		});
928		";
929				break;
```

![screen shot 2017-01-31 at 10 25 44](https://issues.joomla.org/uploads/1/84089c5d2f84085f392f733a0fcca48a.png)

Would be nice to have this code changed in future Joomla versions.

**Comment by infograf768** [comment]
@Fedik 
I think it's easy enough to add line 1982 in staging. Can you look at it?

**Comment by michaelhq** [comment]
I have formatted the code correctly in the description.

Thank you for looking into it! :-)

Best regards
Michael <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13818">issues.joomla.org/tracker/joomla-cms/13818</a>.</sub>

**Comment by Fedik** [comment]
please test #13833

**Comment by infograf768** [comment]
Closed as we have a patch https://github.com/joomla/joomla-cms/pull/13833<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13818">issues.joomla.org/tracker/joomla-cms/13818</a>.</sub>
