### ISSUE TITLE
backend article manager: filtering the categories dropdown list according to the ACLs

### ISSUE THREAD

**Issue by pulsarinformatique** [joomla/joomla-cms#13815]
In the joomla backend, in the article manager, the categories dropdown filter is not filtered according to the ACLs.
whoever you are, whatever group you are in, you will be shown all the categories.

We should modify the libraries/cms/html/category.php file

Please locate the two occurences with the following lines:
$query->order('a.lft');

just before these two lines please add the following block:

$user = JFactory::getUser();
$query->where('a.access IN (' . implode(',', $user->getAuthorisedViewLevels()) . ')');

**Comment by pulsarinformatique** [comment]
I must add I'm NOT talking about the categories manager but the categories dropdown filter in the ARTICLE manager
thanks

cyril<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13815">issues.joomla.org/tracker/joomla-cms/13815</a>.</sub>

**Comment by marrouchi** [comment]
@pulsarinformatique I was unable to reproduce to issue. Can you tell us which Joomla version your are using ?

**Comment by pulsarinformatique** [comment]
Very easy to reproduce with Joomla 3.6.5

Create two sub manager groups: managers1 and managers2

Create two ACLs : manager1 access and manager2 access. for both ACL only select the designated group (manager1 and manager2)

Create a manager account you put only in the manager1 group

Create a category with the manager2 access to it. let's name it 'manager2 acl cat'

disconnect and reconnect as manager1

Go to the CATEGORY manager: you don't see the 'manager2 acl cat' which is normal since you are now allowed to see it (you don't belong to the manager2 group)

NOW go to the ARTICLE manager and display the category dropdown filter: SURPRISE: you still see the 'manager2 acl cat' ! you should'nt 

see ?

cyril

**Comment by marrouchi** [comment]
I think there's one detail your forgot to make : you must create two access levels assigned to it's corresponding user group. After that, you must specify these access levels when you create categories. If not, categories will remain with "Public" access level and will be displayed regardless of the user access level.

**Comment by pulsarinformatique** [comment]
Hi

no marrouchi we DID create those two access levels and we assigned them to the categories. the categories I mentioned in my post are not public !

please test the scenario I wrote you will see the issue

thanks

cyril

**Comment by alikon** [comment]
should be solved in staging #12931 
@pulsarinformatique can you test with latest staging

**Comment by pulsarinformatique** [comment]
Hi alikon, 

yes this is the same issue! and I confirm your solution works!

cyril

**Comment by franz-wohlkoenig** [comment]
@pulsarinformatique this Issue can be closed?

**Comment by pulsarinformatique** [comment]
yes, thanks!
