### ISSUE TITLE
Getter and Setter methods in class JAuthenticationResponse

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#13824]
Is there a reason why there are no getter and setter methods in the class JAuthenticationResponse:
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/authentication/response.php

Is there a reason why these methods should not be inserted afterwards?

**Comment by mbabker** [comment]
It's a value object.  Basically it's just the same as a plain `stdClass` object at this point just with a defined structure.  Is there really a need for getter/setter methods?

**Comment by franz-wohlkoenig** [comment]
closed as "No Reply"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13824">issues.joomla.org/tracker/joomla-cms/13824</a>.</sub>
