### ISSUE TITLE
[plg_tinymce] message in 3.7 Warning

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#13827]
Shouldn´t that be just an "after installation message" ... instead of a warning?

![image](https://cloud.githubusercontent.com/assets/828371/22470310/23e09486-e7cf-11e6-8c2a-5bffee12cfdb.png)

**Comment by AlexRed** [comment]
Hello,
from comment  https://issues.joomla.org/tracker/joomla-cms/13344#event-235553  
"

Can we change the warning message? It is not clear that all your 'legacy settings" will be lost the moment you change settings. We might have a warning such as

The TinyMCE Editor Plugin has been updated. At the moment, it uses your legacy configuration. By editing the sets of the TinyMCE panel plugin, you can now assign various layouts to specific user groups but be aware that with editing you will need to redo all settings in the plugin"
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13827">issues.joomla.org/tracker/joomla-cms/13827</a>.</sub>

**Comment by coolcat-creations** [comment]
I really think it should be a after-Installation Message instead of a nagging Warning everywhere?

![image](https://cloud.githubusercontent.com/assets/828371/23331066/3fb68812-fb5e-11e6-8a87-ea4d9a2fe853.png)

**Comment by brianteeman** [comment]
~This message is very wrong. Not only does it appear everywhere there is no information about how to remove the message, There is no way for a user to discover that if they simply go to the plugin and save the settings without making any change then the message will disappear.~

~**This is currently a very bad user experience. I agree that it should be a post install message and not present everywhere.**~

~_Also if the user who performs the update is NOT using tinymce then they will never see the message at all. Only the regular users will see it and they might not even have the permissions to do anything about it_~

**Comment by AlexRed** [comment]
please also explains that editing the plugin you lose all your previous tinymce setting.

**Comment by franz-wohlkoenig** [comment]
set Stauts on "Needs Review" on issue Tracker.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13827">issues.joomla.org/tracker/joomla-cms/13827</a>.</sub>
