### ISSUE TITLE
[Tiny MCE] Button "Image"-Popup messed

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#13820]
### Steps to reproduce the issue
Click in Tiny MCE on editors-xtd-Button `Image` and scroll down to `Image URL`:
![screen shot 2017-01-31 at 11 57 49 am](https://cloud.githubusercontent.com/assets/8235763/22462479/b6fc9552-e7ad-11e6-9625-ab9a25c2fdd8.JPG)
Fields ar aligned left or right.
#### Test on:
Joomla! 3.7.0-staging
macOS Sierra, 10.12.3: Firefox 50.1.0 Safari 10.0.3
windows7: Firefox 45
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by infograf768** [comment]
I confirm the issue. See also https://issues.joomla.org/tracker/joomla-cms/13831

@ciar4n can you look at this? Looks like we have a wrong margin-left.

**Comment by ciar4n** [comment]
The problem here is two-fold..

1. Firstly Bootstrap 2.3 wells are not designed to contain a grid

2. The LESS compiler used in Joomla breaks the grid on smaller screen sizes (#13768). As this is within an iframe the same issues apply.

**Comment by franz-wohlkoenig** [comment]
@ciar4n your Info belongs #13831?

**Comment by infograf768** [comment]
This Issue here is the same as #13831
I closed #13831 as duplicate.

**Comment by ciar4n** [comment]
Ideally the compiler issue should be fixed which would also fix this issue. How best to do that is questionable. We could either fix the current compiler (seems unlikely) or replace the compiler. Failing that we can simply override the current compiled grid with a correct version. The later I can do however would be the least ideal solution as we would be duplicating CSS.

**Comment by franz-wohlkoenig** [comment]
@ciar4n thanks for Info.

**Comment by ciar4n** [comment]
PR: #13845

**Comment by franz-wohlkoenig** [comment]
@ciar4n thanks for your Work.
