### ISSUE TITLE
[com_fields] [4.0] Fatal error when trying to save field

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#13839]
### Steps to reproduce the issue

- Fresh installation of the 4.0-dev branch
- Go to create a new field
- Attempt to save

### Expected result

Field should get saved

### Actual result

```
Fatal error: Class 'Joomla\Cms\Model\JFactory' not found in \libraries\src\Cms\Model\Admin.php on line 1158
```

### System information (as much as possible)

- Joomla 4.0-dev branch
- PHP 5.6.25 (also tested on PHP 7.0.10)

**Comment by laoneo** [comment]
PR #13840 should fix the issue.
