### ISSUE TITLE
Siteground (and others will follow) has disabled file_get_contents($url)

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#13847]
### Steps to reproduce the issue

Find a Siteground server configured under their "new way"... 

E.g. m30.siteground.biz

Attempt to run code like:

`$body = file_get_contents('https://example.com/file.txt');`

We do this in core like these examples:

https://github.com/joomla/joomla-cms/blob/6e07ca6fadd8a5d1db3337cf0357d782646f5411/components/com_users/controllers/profile_base_json.php#L34

### Expected result

That $body now contents the content of file.txt

### Actual result

$body is empty

### System information (as much as possible)

m30.siteground.biz

### Additional comments

The correct way is to code in defense - if file_get_contents is not working then fallback to CURL (which is x15 more code than a single file_get_contents line of code) - we could implement calls to `FOFDownload` which is in core Joomla ?

**Comment by Bakual** [comment]
I don't think you need FOFDownload. JHttp should be able to do that as well. Or do I miss something?

**Comment by PhilETaylor** [comment]
I was in a rush and did not scratch too deep - I know FoFdownload has curl and other adapters - I guess JHttp also does :)
