### ISSUE TITLE
Errors in Smart search component on PostgreSQL

### ISSUE THREAD

**Issue by csthomas** [joomla/joomla-cms#13848]
### Steps to reproduce the issue

After applied PR #12313 there appears new errors.

Click on index and wait until indexing complete.

1. Then try to search some word in search field.
  * `ERROR: operator does not exist: timestamp without time zone ~ unknown LINE 4: ...e%' OR "l"."url" LIKE '%lime%' OR "l"."indexdate" LIKE '%li... ^ HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts`

2. Click on Content Maps on the left panel. `administrator/index.php?option=com_finder&view=maps`
* `ERROR: column "s.count_published" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: SELECT a.,s.count_published,s.count_unpublished,COUNT(b.id)... ^ ERROR: column "s.count_published" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: SELECT a.,s.count_published,s.count_unpublished,COUNT(b.id)... ^ ERROR: column "s.count_published" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: SELECT a.*,s.count_published,s.count_unpublished,COUNT(b.id)... ^`

### Expected result
No errors.

### Actual result
As above.

### System information (as much as possible)
 PHP 7.0.13-0ubuntu0.16.04.1
PostgreSQL 9.5.5

**Comment by csthomas** [comment]
I'm working on 2 point.

**Comment by alikon** [comment]
for let com_finder work on postgresql we need to fis some more  issues  i'm afraid
#12348 , #12417

**Comment by alikon** [comment]
@csthomas #12348 should solve point 1.

**Comment by csthomas** [comment]
I have a ready PR #13854 to test.
