### ISSUE TITLE
Routers create wrongly accepted URL's

### ISSUE THREAD

**Issue by xaddict** [joomla/joomla-cms#13849]
Somehow when Google came by and indexed a site of mine they started indexing pages that weren't mentioned anywhere, weren't in menus or anywhere else but still worked in Joomla somehow...

When this happened I first thought it was the site but after testing I found out it happens on every Joomla! site.

So for example the following:
https://extensions.joomla.org/category/access-a-security/site-access/2/
https://extensions.joomla.org/category/access-a-security/site-access/
is accepted even though the /2 URL leads to a random page with no real clue as to what the /2 did to the page. The page is however always the same when this same 'suffix' is used.

The same concept can be used to add arbitrary words in between slashes to real URLs:
https://community.joomla.org/blogs/leadership/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z/3095
https://community.joomla.org/blogs/leadership/something/something/somethingelse/3095
https://community.joomla.org/blogs/leadership/you/are/foxy/3095
https://community.joomla.org/blogs/leadership/ri/di/cu/lo/us/3095
https://community.joomla.org/blogs/leadership/3095
https://community.joomla.org/blogs/3095

This 'hack' works on every Joomla! site for as far as I can go back. This includes everything up from 2.5. I have tried to find out what triggers this behavior. It seems to be possible with everything article related as third-party components sometimes block it. Other, probably less maintained or lesser quality, components accept it the same way Joomla! Core does.

**Comment by infograf768** [comment]
AFAIK, this is a known issue with current router. Changing status.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13849">issues.joomla.org/tracker/joomla-cms/13849</a>.</sub>
