### ISSUE TITLE
Changing menu Item Alias causes 404's

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#13851]
So if you change a menu item Alias it causes a 404 of course because the Alias no longer exists and we technical people know this. 

Other people don't so much and yes we must cater for everyone imho. 

What about on changing the alias we prompt saying 'Redirect old alias to this menu item?' if checked we insert a redirect into the Joomla! redirect component?

**Comment by marrouchi** [comment]
Hi, very interesting issue ! This may cause problems when links are well positioned in search engines.
I've just created a PR for this : #13856 

Can you test it please ?

**Comment by brianteeman** [comment]
This can be closed as there is a pr @zero-24
