### ISSUE TITLE
[3.7.0b1] JUser: :_load: Unable to load user with ID: 849

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#13864]
### Steps to reproduce the issue

Install 3.7.0.b1 with default content (which is one article) 

Restore the "initial content" of that article using the versions button

### Expected result

No error 

### Actual result

JUser: :_load: Unable to load user with ID: 849
<img width="968" alt="screen shot 2017-02-02 at 21 36 03" src="https://cloud.githubusercontent.com/assets/400092/22569489/9dd5d5a0-e98f-11e6-93d5-c7ec9cf16107.png">

**Comment by Bakual** [comment]
The warning is because you have set a non-existant user in the form. So the warning makes sense, but may of course be more helpful if it would say which field it was.

**Comment by PhilETaylor** [comment]
No - this is because the restored version has a hard coded non existent user id!

**Comment by Bakual** [comment]
Ah, I think Joomla now resets the user ID during the installation to a valid user to avoid this warning. I'm not sure how it's done excatly, I just remember reading something like this. Maybe that triggers a new versioning entry then?

**Comment by AlexRed** [comment]
I can confirm.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13864">issues.joomla.org/tracker/joomla-cms/13864</a>.</sub>

**Comment by shur** [comment]
Looks similar #13361

**Comment by franz-wohlkoenig** [comment]
Depends on 

> The example date sets are not updated, please test only the default installation or updates

([Release-Notes](https://github.com/joomla/joomla-cms/releases/tag/3.7.0-beta1))?

**Comment by PhilETaylor** [comment]
> please test only the default installation

@franz-wohlkoenig This is exactly what I did!

**Comment by infograf768** [comment]
indeed user # 849 is harcoded in sample data
The patch for it 
https://patch-diff.githubusercontent.com/raw/joomla/joomla-cms/pull/12947.diff

does not take versioning into account. Therefore I guess that when updating the table it also creates a version, thus the error encountered

**Comment by PhilETaylor** [comment]
So this is left over from https://github.com/joomla/joomla-cms/pull/12947 ....

**Comment by franz-wohlkoenig** [comment]
set Status "Needs Review" on Issue Tracker.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13864">issues.joomla.org/tracker/joomla-cms/13864</a>.</sub>

**Comment by PhilETaylor** [comment]
Still issues in Joomla 4 alpha1
