### ISSUE TITLE
[3.7.0b1] [com_fields] URL Validation of default value not happening

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#13869]
### Steps to reproduce the issue

Create a field of type URL
Set the Scheme to be https only
Set a default value that is not http:// prefixed 

### Expected result

Validation error on save as the default value doesnt match the validation 

### Actual result

<img width="683" alt="screen shot 2017-02-02 at 21 52 39" src="https://cloud.githubusercontent.com/assets/400092/22570112/f4ea49b4-e991-11e6-92b0-eb35c3586136.png">

**Comment by Bakual** [comment]
Default values aren't sanitised for any custom field. That is true.
It's assumed that the admin knows what he does when he sets up a new field. Similar to the extension developer when they specify a default value in the XML file (which isn't sanitised as well).

Imho if we want to sanitise those values, it would have to be done in the respective formfields, not in the custom fields plugins.

**Comment by PhilETaylor** [comment]
so a "wont fix" then?
