### ISSUE TITLE
[3.7.0b1] [com_fields]  modified date/time missing accurate seconds

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#13865]
### Steps to reproduce the issue

Edit a field group in com_fields
Click save

### Expected result

The modified date/time is accurate with seconds 

### Actual result

When clicking save, some javascript is updating the value of the disabled form field with the date/time that the save button was clicked, the page reloads, and the modified date/time is set to the new time but with 00 as the seconds...

**Comment by dgt41** [comment]
There was a reason to set the secs to 00 (if I remember correctly had to do with the alt-data data attribute). I will review the code once more tomorrow

**Comment by PhilETaylor** [comment]
Not acceptable - no where else in Joomla does this happen.

**Comment by laoneo** [comment]
Thanks @dgt41 for help on this issue.

**Comment by PhilETaylor** [comment]
[3.7.0b3] Still happening

**Comment by PhilETaylor** [comment]
No longer happening in joomla-cms/staging@d7caa77133e8936574fa32f55690b95d0a2d55fc
