### ISSUE TITLE
To many elements to index from tags

### ISSUE THREAD

**Issue by tomekstach** [joomla/joomla-cms#13866]
### Steps to reproduce the issue

Use `php cli/finder_indexer.php` to check if the number of tags is the same as number of items to index.

### Expected result

I think that the number of tags should be the same as the number of items for index.

### Actual result

For 1100 tags I have more than 1233000 items to index.

### System information (as much as possible)

Joomla! 3.6.5

**Comment by franz-wohlkoenig** [comment]
@tomekstach can you confirm Issue on latest Staging?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13866">issues.joomla.org/tracker/joomla-cms/13866</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened in the future if it is updated.
