### ISSUE TITLE
URL Field doesnt validation if the URL supplied is valid URL

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#13876]
### Steps to reproduce the issue

install 3.7.0b1
create Url(Url) custom field
Set scheme to be http://
edit content on FRONTEND
attempt to bypass validation 

### Expected result

`http:// this is & not & a VALID url` should not be saveable and should error

### Actual result

`http:// this is & not & a VALID url` saves as a valid url and is hyperlinked on rendering

### Additional comments

If there is no validation on the URL then this custom field type is nothing more than a text field with "validate the first few char" and not a URL field!!! Either name it correctly or implement correct validation of the input !

**Comment by Bakual** [comment]
That is actually not related to com_fields as the same happens when you enter it into the link fields in an article. So I think the JFormFieldUrl itself would need to be fixed here.

**Comment by PhilETaylor** [comment]
Actually - if you are going to provide a URL field - it MUST validate as a url else whats the point. So it is related to com_fields in that respect.

**Comment by Bakual** [comment]
The URL field extends JFormFieldUrl. So you don't need to fix it in the field plugin, you need to fix it in the old and existing formfield.
![link](https://cloud.githubusercontent.com/assets/1018684/22571305/8462258c-e99f-11e6-9582-c6e7fd7b9942.PNG)

It's an old bug you found here 😄

**Comment by PhilETaylor** [comment]
The only thing that makes a URL field different to a TEXT field, is that is SHOULD only accept a URL, effectively it should be a TEXT field with validation.... 

So is the correct course of action to remove the URL field type completely - losing yet another new feature?

or fix the fact that validation has been broken for years?

**Comment by franz-wohlkoenig** [comment]
set Staus on "Needs Review" on issue Tracker.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13876">issues.joomla.org/tracker/joomla-cms/13876</a>.</sub>
