### ISSUE TITLE
[3.7.0b1] [com_fields] Fields are not orderable

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#13871]
Fields are not orderable on the front end - they are ordered by label A->Z but you cannot specify the order other than that. 

In fact Im not even sure they are a-z...

**Comment by Bakual** [comment]
Works for me when I order the fields in the fields manager.
The fields follow the ordering in both forms (front- and backend) and also when set to automatic display in the item.

**Comment by laoneo** [comment]
Works for me too, in the edit form and the front end display.
