### ISSUE TITLE
[3.7.0b1] [com_fields] Frontend URL Validation of field not helpful

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#13870]
### Steps to reproduce the issue

Create a field of type URL 
set the scheme required to https://
edit article on frontend
enter example.com as the url - because it doesnt tell you what it expects
click save 

### Expected result

Validation fails and tells you why - example.com IS A VALID URL, but the scheme is required

### Actual result
validation fails - but doesnt tell you why
<img width="617" alt="screen shot 2017-02-02 at 21 54 54" src="https://cloud.githubusercontent.com/assets/400092/22570224/71dbf0a8-e992-11e6-9d25-c4fc66aa1973.png">

**Comment by Bakual** [comment]
Same as in the other one. That needs to be fixed in JFormFieldUrl or in the respective validate/filter methods. com_fields doesn't do anything special here.

**Comment by marrouchi** [comment]
I've made a PR for this #13885. Is it okay ?

**Comment by zero-24** [comment]
Thanks!
