### ISSUE TITLE
[3.7.0b1] [com_fields] Calendar not rendering right on frontend in default template

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#13872]
### Steps to reproduce the issue

install 3.7.0b1
create calendar custom field
edit content on frontend 
click calendar popup field

### Expected result

Nice and neat calendar 

### Actual result

<img width="438" alt="screen shot 2017-02-02 at 22 03 13" src="https://cloud.githubusercontent.com/assets/400092/22570520/90c6260e-e993-11e6-811b-7420162f5830.png">

### System information (as much as possible)

Google Chrome

**Comment by dgt41** [comment]
There's a PR for that: https://github.com/joomla/joomla-cms/pull/13181

**Comment by PhilETaylor** [comment]
That PR looks like its for the ADMIN SIDE 

This issue is on the frontend

**Comment by dgt41** [comment]
There shouldn't be any difference between front end back end as the calendar uses its own CSS file for both

**Comment by brianteeman** [comment]
Can this be closed @zero-24
