### ISSUE TITLE
[3.7.0b1] [com_fields] User field doesnt render on the frontend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#13873]
### Steps to reproduce the issue

install 3.7.0b1
create User(user) custom field
edit content on *FRONTEND*

### Expected result

Expect to see a selector to select a user object

### Actual result

Nothing rendered for this custom field

**Comment by Bakual** [comment]
Confirmed, works in backend forms but not in frontend.

**Comment by laoneo** [comment]
The user field is not available on the front end, probably because of security reasons or lack of resources. So should we do some kind of warning when it is not available on the front or what do you guys suggest?

**Comment by brianteeman** [comment]
Not sure why its not available on the front end - that sounds like a bug to me BUT even without addressing that if a field can not be used in the frontend or inn the admin then there shouldnt be the option to set it to display there at all. The option should be disabled in the field creator. That woudl be the correct way to do it - not displaying a message

**Comment by laoneo** [comment]
Pr #14500 removes the show on option when editing the field. Implementing the user field for the front can be done in another pr.

**Comment by zero-24** [comment]
So we can close here @PhilETaylor @laoneo ?

**Comment by laoneo** [comment]
I don't know if somebody will ever volunteer to make the user field available on the front. But the issue itself is not solved. @PhilETaylor should decide.

**Comment by PhilETaylor** [comment]
Well it comes down to expectation and documentation - like most of com_fields, its inconsistent, has no defined structure or documented goals...

Therefore its hard to know if this is a bug, a feature, an oversight, or just plain wrong.

If only there were some documentation or design document, or ux team that could be consulted...

**Comment by PhilETaylor** [comment]
Also as the "User" custom field has configuration:

<img width="574" alt="screen shot 2017-03-12 at 18 34 37" src="https://cloud.githubusercontent.com/assets/400092/23834695/98239616-0752-11e7-8b79-3da228c84281.png">

One can quite rightly expect that it could be rendered on the frontend...

**Comment by mbabker** [comment]
> Not sure why its not available on the front end

The field (`JFormFieldUser`, not the com_fields thing) requires a view that is only available in the backend component.  If it is desired to support this field on the frontend then proxy support used in other components must be added.

**Comment by franz-wohlkoenig** [comment]
@PhilETaylor please have a Look at #14500 which removes "Show on" at "User" custom field.

**Comment by PhilETaylor** [comment]
I already left my thoughts here 

https://github.com/joomla/joomla-cms/pull/14500#issuecomment-285964922 <https://github.com/joomla/joomla-cms/pull/14500#issuecomment-285964922>

**Comment by PhilETaylor** [comment]
So this one is a "wont fix"
