### ISSUE TITLE
Improvements to backend CSS with well and row-stripped

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#13879]
See:
![module_side_by_side](https://cloud.githubusercontent.com/assets/1400982/22571713/ca830bc8-e998-11e6-842a-f168419b00c4.jpg)

Left is styled the way I propose it should be, the right is the current view.

Thoughts on this? I think the way it is at the moment is unfinished.

**Comment by brianpeat** [comment]
Yeah, the border and fixed margins are MUCH better with your change.

**Comment by ciar4n** [comment]
PR:  #13890
