### ISSUE TITLE
[3.7.0b1] [com_fields] Radio field doesnt render on frontend at all 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#13877]
### Steps to reproduce the issue
install 3.7.0b1
create Radio (radio) custom field with valid configuration
edit content on FRONTEND

### Expected result

Expect to see the radio list

### Actual result

Nothing is rendered

### System information (as much as possible)

Google Chrome

**Comment by Bakual** [comment]
Works for me:
![radio](https://cloud.githubusercontent.com/assets/1018684/22571135/bd6650f2-e99e-11e6-8ea2-533f2f99873a.PNG)

**Comment by PhilETaylor** [comment]
yup - works for me too - this "random ordering" of fields meant it was not where I looked for it :)
