### ISSUE TITLE
Several articles refer not to the correct categories and subcategories.

### ISSUE THREAD

**Issue by 11john** [joomla/joomla-cms#13880]
Two new joomla site installations.

Both websites, menu not created.
Create categories and subcategories.
Articles created and directed to the appropriate category to which the subject is about.

Creating a sitemap.xml, shows a completely different picture. All items are placed in the wrong categories.

### Expected result
Remove categories and subcategories and recreate it, a solution may indicate that the items will be placed correctly in the categories and subcategories.

This operation sometimes one has to repeat 4 times, until the items are in the correct categories and subcategories.

### Actual result

This means that the creation of categories and subcategories are not stored properly or there is a total further problem that the products do not refer to the appropriate categories.

Look after your own sitemap.xml that if your articles have been placed in the appropriate categories and subcategories.

**### System information**

Joomla version 3.6.5
Aimy Sitemap PRO version 3.19.1
Used also Online sitemap generators
CentOS 6.0 64-Bit
Apache 2.4.25
DirectAdmin 1.50.1
Exim 4.87
MySQL 5.5.31
Named 9.8.2rc1
sshd
dovecot 2.2.27
pure-ftpd 1.0.43
Php 5.6.30

**Comment by infograf768** [comment]
As we can see, you are using a 3rd party extension to create your sitemap. Please contact them as this does not look related to core.

Also I changed the status. Critical is only used when Joomla is totally broken.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13880">issues.joomla.org/tracker/joomla-cms/13880</a>.</sub>

**Comment by 11john** [comment]
As I have described, online website sitemap generators.
Also same problem with sitemap generator Aimy Sitemap Pro version.

This is truly described in the notification., And joomla itself has no sitemap generator sitting in joomla. You are therefore dependent on 3rd party extension.

I mention only a big problem, when all items are in the wrong categories. And that is it, all people want to do something different from, is their problem.

I've said now, and it's up to Joomal and managers of a joomla website itself, to see after their own sitemap.xml.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13880">issues.joomla.org/tracker/joomla-cms/13880</a>.</sub>

**Comment by 11john** [comment]
This is also the last post on this.

It concerns on the production of categories and the article references to the relevant categories.

This will you as the developer boot totally not like what I have discovered. I believe that there is now a pretty big problem for more than 99.9% of all Sitemaps are created. Beyond that fact that all items be referred to the relevant categories, all of them are wrong.

I will describe it as best as possible, if you can not come out, ask if you blieft.

The categories are not created in joomla.

When one refers to a product category that is not properly created, will be placed somewhere else in a category. The reference of the article, so state without being aware of this, so in the wrong category or categories.

I think I have still incredible mazel that I use Aimy Site Map Pro which gives a total result after scanning.
From this scan, I was so behind the map, totally was wrong created because the items were in the wrong categories.

Well now the solution really totally nobody will like, given that it is wrong a lot of work.

implementation recovery

Everything that has to do with creating a site map should be turned off.
All sitemap xml files should be removed from the server.
All links that link to a site map should also be removed.

It is incredibly important next step.

If people have the component Aimy sitemap generator, they must make a copy of what their screen after scanning emerges.
That should really be kept very good, considering that you have to desperately needed then in the next step.

The next step

To remove one category, one first course, the content description as the header just copy it to a scrapbook.
Then remove the category indicates a problem, and that we can look back which items are wrong in the assigned category.

After first removing happen to the menu system> Clear Cache> Clear Cache (Management section)

To be absolutely certain of being that everything is cleared, this will also be carried out for the website section.

Recreate the same category with the same name and content. Of course assign this category as the old category that was removed.

articles
Now comes the earlier copy of the map, scan only, it is namely all items under the category which were removed.
All articles how bad this sounds, must be totally reset, the category to which they were previously referred to.

All items are namely suddenly in the category Uncategorised (Alias: uncategorised)

After all again correctly to have referred to the appropriate category, a sitemap scan again will have to be implemented. Only then will it be clear that the articles are in the right category.

How so to see if all joomla have the same problem that I have learned.
By scanning with Aimy sitemap generator, and everything good Fed where they stand referred. Everyone has his own website best how everything is laid out, and where it should be.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13880">issues.joomla.org/tracker/joomla-cms/13880</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@11john canyou confirm issue on latest Staging?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13880">issues.joomla.org/tracker/joomla-cms/13880</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened in the future if it is updated.
