### ISSUE TITLE
[3.7] Breadcrumbs on wrong Position if "Full Article Image" float

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#13887]
### Steps to reproduce the issue
Set a `Full Article Image` float left or right:
![1](https://cloud.githubusercontent.com/assets/8235763/22585446/2f684b2a-e9f8-11e6-928a-4abed52116aa.JPG)

### Expected result
Breadcrumbs stay at bottom
#### Test on:
Joomla! 3.7.0-beta1
macOS Sierra, 10.12.3
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by mbabker** [comment]
You need to add clearfixes in your template if you want whatever module position(s) are below the component area to always be below and not be affected by a case where an image is taller than the content its associated with.

**Comment by franz-wohlkoenig** [comment]
@mbabker Template is protostar, so i thought its an Issue.

**Comment by brianteeman** [comment]
I agree that a clearfix should be present in the protostar template

**Comment by franz-wohlkoenig** [comment]
If `Navigation` is set on `Show` Breadcrumbs stay at Bottom, but if User don't wan't Navigation?
![bildschirmfoto 2017-03-14 um 21 57 06](https://cloud.githubusercontent.com/assets/8235763/23922116/73dadc1e-0901-11e7-9cc9-a24afacdb21a.JPG)

**Comment by franz-wohlkoenig** [comment]
Issue still exists:
### System information
Joomla! 3.7.0-beta4 (nightly Build)
macOS Sierra, 10.12.4
Firefox 52 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by ghost** [comment]
closed as having Pull Request #18210<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13887">issues.joomla.org/tracker/joomla-cms/13887</a>.</sub>
