### ISSUE TITLE
Missing Core Components in J37-beta1 and latest Nightly build

### ISSUE THREAD

**Issue by allrude** [joomla/joomla-cms#13892]
### Steps to reproduce the issue

install the J37 beta1 or latest nightly build, (during install choose to install sampledata)

### Expected result

Click on components and see core components as banners, contacts, smart search etc

### Actual result

see only, post installation and tags

### Additional comments

if you choose to install without sample data all works as expected

**Comment by mbabker** [comment]
Known issue as noted on the 3.7 release page.

https://github.com/joomla/joomla-cms/releases/tag/3.7.0-beta1

**Comment by allrude** [comment]
Thanks Michael, did see that

**Comment by zero-24** [comment]
https://github.com/joomla/joomla-cms/pull/13894  @allrude should fix the issue
