### ISSUE TITLE
Default htaccess

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#13899]
One for discussion really, the default htaccess being shipped by Joomla! since 1.6? change from that of 1.5. Now for every image that doesn't exist we are loading valuable php resources of the server. Shouldn't we be excluding images from with an exception.

Yes I know I can do this myself manually, but this is more for default installs where people do not know how to fine tune the htaccess.

example, 

https://www.joomla.org/sdfsd.png

Loads a Joomla! 404. It shouldn't, it should be a server side 404 like we did on J1.5.

**Comment by mbabker** [comment]
One of the features of Joomla and PHP is to serve more than HTML (sadly Joomla seems stuck on the HTML bit).  You can serve images through PHP scripts (think dynamic trackers or ACL restricted stuff).  So if a change is made, it should be based on file paths and not file extensions (so don't redirect requests for the images directory if a file doesn't exist versus not rewriting .png requests).  Such a change also needs to be clearly documented or communicated to ensure developers using such a behavior aren't bitten in the backside).

**Comment by brianteeman** [comment]
Are you going to submit a PR @tonypartridge or shall we treat the lack of comments as meaning no interest in making a change and it can be closed

**Comment by tonypartridge** [comment]
I'm no
