### ISSUE TITLE
[3.7.0b1] No items in Components menu on clean install

### ISSUE THREAD

**Issue by obuisard** [joomla/joomla-cms#13905]
### Steps to reproduce the issue

Just install beta 1

### Expected result

Menu items in the components menu such as 'contacts...

### Actual result

![image](https://cloud.githubusercontent.com/assets/5964177/22619917/2ca1600e-eacd-11e6-8f85-2071f18261e1.png)

### System information (as much as possible)

PHP 5.6.25 MySql 5.7.14 Apache 2.4.23

**Comment by zero-24** [comment]
Please try this one https://github.com/joomla/joomla-cms/pull/13894. And make sure it is a complete new install.

**Comment by obuisard** [comment]
That is fixed in the version presented in #13894.
Thank you!

**Comment by zero-24** [comment]
Ok so i'm closing here.
