### ISSUE TITLE
[4.0] Select Widths Inconsistent

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#13908]
This screen cap demonstrates the issue.  I'm not focused here on the jump as the page loads, but rather how the width changes when I choose a value.

https://cl.ly/0r2k2g2u0J15

**Comment by C-Lodder** [comment]
I didn't set a max width on purpose. Take the following example:

![screeny](https://cloud.githubusercontent.com/assets/2019801/22824803/8fcf3c74-ef81-11e6-9623-990d5a90f92b.png)

**Select Registration Date**. If I set a max-width of `150px`, it's not enough space. On multilingual sites, I have no idea what width may be required.

If I set the max width to `300px`, then some o the dropdowns will simply be too wide, like **Select State**. The difference between J3 and J4, is that J4 uses a large default font size, thus taking up more space, but much easier for people to read.

**Comment by dgt41** [comment]
@mbabker `select` element is controlled by the browser, why shall we override the default behaviour with some hardcoded width (which most probably will bring more problems than the one supposed to solve)?

**Comment by mbabker** [comment]
It's not the lack of a max width that's the issue to me.  Watch the video please, the element changes size depending on what you have selected; the native `<select>` doesn't do that.

**Comment by C-Lodder** [comment]
This only applies to the chosen select boxes which you're using in com_patchtester, which we've nearly completely removed in J4.

We're still waiting for `choises.js` to release a beta with the feature that Dimitris requested.

I'd suggest you use the `custom-select` class for your select boxes

**Comment by mbabker** [comment]
I copied the markup direct from a rendered com_content page (patch tester doesn't use legacy MVC so it doesn't use native search tools stuff).  https://github.com/joomla-extensions/patchtester/blob/master/administrator/templates/atum/html/com_patchtester/pulls/default.php

Looking again, it looks like I'm still loading some extra JavaScript though and that might just be the only problem to fix for my case here.

**Comment by C-Lodder** [comment]
Replace:

```
\JHtml::_('formbehavior.chosen', 'select');
```

with:

```
\JHtml::_('formbehavior.chosen', '.advancedSelect');
```

**Comment by mbabker** [comment]
Chosen's gone completely.  I just hadn't removed the JavaScript loader for it is all.  Works fine without it.
