### ISSUE TITLE
[4.0] Login Screen Using Old Color Scheme

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#13913]
After the merge of https://github.com/joomla/joomla-cms/pull/13900 the login page and the rest of the admin panel use a different base color scheme.

**Comment by dgt41** [comment]
@ciar4n can you check this?

**Comment by ciar4n** [comment]
@mbabker Thank you

PR created.. #13921

**Comment by C-Lodder** [comment]
Closing for PR
