### ISSUE TITLE
[4.0] Component Subnav Missing

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#13911]
Can't navigate to the other views that are part of Smart Search, this sub navigation is missing.

**Comment by dgt41** [comment]
@C-Lodder @ciar4n we discussed this in London, so shall we provide the old code for the time being?

**Comment by ciar4n** [comment]
Yes I think so. Similar to the current 'Global Config'. A temporary solution until something better comes up.

**Comment by C-Lodder** [comment]
Yup, I think I started re-adding this but got side tracked. Will push a PR tomorrow or Monday.

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/13998
