### ISSUE TITLE
[4.0] Access Level Edit Page Unstyled

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#13914]
`administrator/index.php?option=com_users&view=level&layout=edit&id=1`

<img width="1440" alt="screen shot 2017-02-04 at 12 27 54 pm" src="https://cloud.githubusercontent.com/assets/368545/22620627/64ce5d58-ead5-11e6-8c3b-25c655bb834b.png">

**Comment by C-Lodder** [comment]
Joomla 3.x is not really different.

![untitled](https://cloud.githubusercontent.com/assets/2019801/22621723/351e7bae-eb22-11e6-8abd-a9512be2ada9.png)

**Comment by mbabker** [comment]
Well, it stands out more with the new template.  Your call either way, it just didn't look right to me when I pulled it up.

Comparing it side by side, it does show the level indentions are gone.

**Comment by C-Lodder** [comment]
Ah didn't even notice the indentations

**Comment by C-Lodder** [comment]
PR here: https://github.com/joomla/joomla-cms/pull/14009
