### ISSUE TITLE
[4.0] Smart Search Indexer Fails

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#13912]
Try to run the indexer, get a `Call to undefined method JRouterSite::setMode()` error.

The method is marked deprecated in 3.x and appears to have already been removed in the 4.0 branch.  However, the doc block doesn't indicate whether the method has been replaced with something else or the functionality dropped in full.  Hence the reason I just don't do a PR.

**Comment by wilsonge** [comment]
Fixed with https://github.com/joomla/joomla-cms/commit/b1e3ed8d547fe48ebc1158003aa5f35555cd94cb

Functionality got dropped in full as we've moved to rules which are done in `JRouterSite`'s constructor and therefore no longer use router modes
