### ISSUE TITLE
[4.0] Debug User/Group Views Not Working Well

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#13910]
`administrator/index.php?option=com_users&view=debuguser&user_id=<your_user_id>` (for your user)
`administrator/index.php?option=com_users&view=debuggroup&group_id=8` (for super user group)

<img width="1440" alt="screen shot 2017-02-04 at 12 15 36 pm" src="https://cloud.githubusercontent.com/assets/368545/22620529/abd45588-ead3-11e6-934b-55650dc056c0.png">

**Comment by ciar4n** [comment]
PR created.. #14255
