### ISSUE TITLE
[com_user] possible cache issue

### ISSUE THREAD

**Issue by svenbluege** [joomla/joomla-cms#13926]
### Steps to reproduce the issue

- open the front end
- login 
- call JUser::setParam('foo', 'bar')
- call JUser::save()
- call JUser::setParam('foo2', 'bar2')
- call JUser::save()
- check the database. The column param will contain only foo=bar

### Expected result

the last version of the user object is represented in the database

### Actual result

an older version ends up in the database

### System information (as much as possible)

Joomla! 3.7 - Beta 1

### Additional comments

It seems like the JUser::getInstance method caches the user by id. If you do save an user by using JUser::save some onUserAfterSave methods are executed. On of them belongs to the plgSystemFields. It tries to get the user by id. This works for the first time. After you modified the user object a second time somewhere else, it retrieves the old version from the cache and pushes it to the database. 

May screenshot shows an example. The first step tries to save some basic data to the user and the second the address data. The latter is missing in the database afterwards. 

![image](https://cloud.githubusercontent.com/assets/3834825/22625543/3e4922f6-eb9a-11e6-808c-27ab21af4caa.png)

**Comment by franz-wohlkoenig** [comment]
@svenbluege can you please confirm Issue on latest Staging?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13926">issues.joomla.org/tracker/joomla-cms/13926</a>.</sub>

**Comment by svenbluege** [comment]
@franz-wohlkoenig seems like this issue was resolved. 

Here is my test code: 
```
$user = JFactory::getUser();

echo "<br>foo=" . $user->getParam('foo');
echo "<br> foo2=". $user->getParam('foo2');

$user->setParam('foo', 'bar');
$user->save();
$user->setParam('foo2', 'bar2');
$user->save();
```

The second run renders both values as expected.
