### ISSUE TITLE
[3.7.0b1] [com_fields] duplicate Alias - no validation

### ISSUE THREAD

**Issue by pepperstreet** [joomla/joomla-cms#13925]
### Steps to reproduce the issue (_UPDATED_)
Create at least 2 Calendar fields.
Fields have to be in the same field group. 
Accidentally, my fields got the same ALIAS!

### Expected result
Both fields in the same group should display on form / edit view.

### Actual result
Only 1 Calendar field displays. It is the first Calendar field, according to fields manager ordering. 

### System information (as much as possible)
Joomla 3.7 BETA 1, MAMP3 , PHP 5.6.x

### Additional comments  (_UPDATED_)
The auto-generated or manual **ALIAS is not validated**. So it's possible to have duplicated Aliases. 
This is not a problem, if the fields are in different groups, but the issue might occur later on, if you move fields from one group to another. 

I assume there should be a validation in any case. Makes sense to require a unique Alias, like we have for core articles.

**Comment by franz-wohlkoenig** [comment]
Can't confirm, 2 Calendar fields are shown in Back- and Frontend, changed Values are saved.
#### Test on:
Joomla! 3.7.0-latest staging
macOS Sierra, 10.12.3
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by pepperstreet** [comment]
@franz-wohlkoenig 
Thanks for checking the issue. I guess, I have found the actual culprit. I have updated my initial post and title. 

**Short summary**: Fields can get the same ALIAS. This results in the display issue, inside the same field group.

**Comment by Bakual** [comment]
See https://github.com/joomla/joomla-cms/pull/13576 which should solve this issue. Please test and report your findings there.

I'm closing this issue since we have a PR that should deal with it.
