### ISSUE TITLE
Missing HTML entity support for com_search

### ISSUE THREAD

**Issue by SniperSister** [joomla/joomla-cms#13930]
### Steps to reproduce the issue
Create a new article with the following HTML markup:
> This is a test sentence with an HTML \&auml;ntity

`&auml;` is a HTML entity that is used in the german language to encode the Umlaut ä

After creating the article, go ahead and create a menu item for com_search and run a search for äntity in the frontend.

### Expected result
The created article is supposed to be found by com_search.

### Actual result
The article isn't found because the input in the search module (`äntity`) doesn't match the value in the database table (`&auml;ntity`)

### Additional comments
I'm aware that this is an edge case and can easily be worked around by disabling the conversion of Umlauts to entities (i.e. JCE has an option for this that switch to off by default anyway), so I'm not sure if this should be covered by the CMS at all.

**Comment by ot2sen** [comment]
Have seen this specific to the Microsoft Edge browser too. Danish special characters æ ø å Æ Ø Å do not return a search result in Edge, but do in IE11, Chrome, FF, etc.
For example Å become Ã¥ when having hit search button and no result is then returned.

![05-02-2017_ae_oe_aa_danish_chars_edgebrowser](https://cloud.githubusercontent.com/assets/790445/22625848/fdab8602-eb9f-11e6-8ca6-508789d9f398.png)

**Comment by ot2sen** [comment]
Can see my follow up wasn´t exactly same as reported case.
Didn´t enter entity code to present the special character. Have keyboard support for those extended characters. But still, it is an issue in Edge and also reported by other Danish users.

**Comment by SniperSister** [comment]
@ot2sen can you open a separate issue for your report? Don't think they are connected to each other.

**Comment by infograf768** [comment]
@SniperSister 
Do you mean that you enter in the textarea
`&auml;entity` instead of `äentity`
?

**Comment by SniperSister** [comment]
I enter &auml;ntity into the article body with disabled WYSIWYG editor. This gets converted into äntity on display by the web browser.

**Comment by infograf768** [comment]
Please use ` before and after what you enter exactly as `&auml;` is transformed to `ä` here.

**Comment by infograf768** [comment]
I mean
![screen shot 2017-02-07 at 09 26 21](https://cloud.githubusercontent.com/assets/869724/22683278/8b2de902-ed17-11e6-898c-5804398e0a73.png)

**Comment by infograf768** [comment]
@SniperSister 
The issue can be solved easily depending if you enter in the search box the htmlentity `&auml;` or directly `ä`

**Comment by infograf768** [comment]
Exemple: the `ä` has been saved in the database as htmlentity, i.e. as `&auml;` and you entered in the Search box `ä` :
![screen shot 2017-02-07 at 09 33 41](https://cloud.githubusercontent.com/assets/869724/22683529/91189cda-ed18-11e6-8ab3-7f3dec7d5454.png)

I can make a patch for that.

**Comment by infograf768** [comment]
Forget it. I thought is would be easy by using `$text = htmlentities($text, ENT_NOQUOTES, 'UTF-8');`
It would work in your special case, but it would break when a text is saved as pure UTF8 (without htmlentities), which is the normal way to do in J!

**Comment by SniperSister** [comment]
Sorry folks, I just realized that Github converted my \&auml; automatically because I didn't escape, updated my description to make it more clear

**Comment by brianteeman** [comment]
As you have stated that its an edge case (lol I thought you meant the browser) and it's been sat here for 18 months I am going to close it
