### ISSUE TITLE
Cannot select existing Category when creating/editing Article

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [joomla/joomla-cms#13945]
vanilla staging
commit:  d151ef4ce7cb68898bc56eb25d8e888647aea9a9
Date:   Tue Jan 24 09:18:20 2017 +0100
_FYI: I have Akeeba pkg_akeeba-5.2.4-core.zip installed._

### Steps to reproduce the issue
Setup a User Group called "Employee" that inherits from "Registered".  Create sub-groups of Employee as '<>-Author', '<>-Editor', '<>-Publisher' (A/E/P).
Setup an Access Level 'Employee' that allows all the User Group 'Employee'.
_I don't think all of this is relevant to the problem, but just to be sure._

Create a Category "Employee", set access to 'Employee' and set permissions to allow Employee A/E/P in the normal way.

Create an article called "Employee Article" attempt to select the "Employee" category.  It will not be visible in the drop-down list.  Type "Employee" into the search field and press enter. The text "Employee" will appear in the drop-down.  Save your aticle and you will see, on the Article list, that the Category of the article is blank.  Edit your article and the category will be "- Uncategorised", and the drop-down does not have the "Employee" entry in it.

In addition, the menu item that displays articles for a category (Categoty List) does not display any articles.

An Akeeba backup can be downloaded from [my website](https://www.abms.net.au/public/site-jmstaging.int-20170206-040031_Category_Problem.jpa).  All passwords are `test`.  I have done considerably more configuration steps than described above.

**Comment by infograf768** [comment]
I do not confirm this when all permissions are set correctly for a user belonging to, for example, Employee->Author group, logged in frontend and creating an article through a Create article menu with access set to Employee.

![screen shot 2017-02-07 at 08 21 46](https://cloud.githubusercontent.com/assets/869724/22681620/8193e7d8-ed0e-11e6-937a-bc29f943809e.png)

**Comment by Napoleon-BlownApart** [comment]
@infograf768 :  Thanks for looking at this.  It appears that I should have mentioned that I had this problem while setting up the articles in the backend whilst logged in as the Super User.

**Comment by franz-wohlkoenig** [comment]
@Napoleon-BlownApart can you please confirm this issue on latest Staging?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13945">issues.joomla.org/tracker/joomla-cms/13945</a>.</sub>

**Comment by Napoleon-BlownApart** [comment]
@franz-wohlkoenig sorry I didn't see this until today.  I will check with the latest Staging branch if this still occurs.

**Comment by Napoleon-BlownApart** [comment]
I downloaded the staging branch zip file today from: https://github.com/joomla/joomla-cms/archive/staging.zip. Unfortunately, nothing has changed.

Having created the Employee group hierarchy, the Employee View Access Level and an Employee category, article creation is still now working as required.  When the employee article is created, the 'Employee' category does not appear in the Category drop-down list and needs to be typed in.   If Access is left as Public (which is incorrect), the employee article has an empty category in the Articles list after the article is saved (as per the image below).
![Article Empty Category](https://www.abms.net.au/public/joomla_staging_3.7_article_empty_category.png)
If the Access for the article is set to Employee, then the displayed category on the Articles list is 'Uncategorised' (as per the image below).
![Article Uncategorised](https://www.abms.net.au/public/joomla_staging_3.7_articles_uncategorised_category.png)

Article creation with 'Employee' typed into the category seach box:
![Article Employee typed](https://www.abms.net.au/public/joomla_staging_3.7_article_employee_typed.png)

Yes, the newly typed category shows in the drop-down list:
![Article Employee new](https://www.abms.net.au/public/joomla_staging_3.7_article_employee_new.png)

But returning to edit the same article shows the article in the uncategorised category:
![Article after refresh](https://www.abms.net.au/public/joomla_staging_3.7_article_after_refresh.png)

And the category does not appear in the drop-down list:
![Article no Employee Category](https://www.abms.net.au/public/joomla_staging_3.7_article_no_employee_category.png)

Creation of the Category List menu item:
![Category List Menu Item](https://www.abms.net.au/public/joomla_staging_3.7_category_list_menu_item.png)

But, for a logged in employee user, the category shows an empty listing:
![Category List without Entries](https://www.abms.net.au/public/joomla_staging_3.7_category_wo_entries.png)

**Comment by ghost** [comment]
@Napoleon-BlownApart thanks for info, set Status on "Needs Review" on Issue Tracker.

**Comment by Quy** [comment]
@Napoleon-BlownApart I am unable to reproduce with your backup that was upgraded to v3.8.3. Is this still an issue?

**Comment by Quy** [comment]
Closing for now since no response from OP and not reproducible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13945">issues.joomla.org/tracker/joomla-cms/13945</a>.</sub>
