### ISSUE TITLE
[com_fields] Field-Button in Frontend "View not found"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#13947]
### Steps to reproduce the issue
Click in Frontend on Button "Fields":
![screen shot 2017-02-06 at 10 03 09 am](https://cloud.githubusercontent.com/assets/8235763/22640671/f2d4f51a-ec53-11e6-8ff6-edd8b04f3c33.JPG)
### System information (as much as possible)
Joomla! 3.7.0-latest staging
macOS Sierra, 10.12.3
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by zero-24** [comment]
@Bakual can you take a look here?

**Comment by infograf768** [comment]
Please test again after patching with https://github.com/joomla/joomla-cms/pull/13946

**Comment by infograf768** [comment]
I confirm

**Comment by Bakual** [comment]
See #13951 

Closing as we have a PR.
