### ISSUE TITLE
Limit Persistent Anonymous Data Collection Prompt To Control Panel

### ISSUE THREAD

**Issue by cpfeifer** [joomla/joomla-cms#13943]
### Steps to reproduce the issue
Install Joomla
Log In
Do not make a selection for Anonymous Data from the prompt
Navigate to some other pages
Message is unnecessarily persistent all screens.
It's annoying and has a negative impact UX on all screens outside the control panel.

### Actual result
![admin-prompt](https://cloud.githubusercontent.com/assets/3790835/22632296/4e6b18fc-ebd5-11e6-84e6-bee34926cbbb.gif)

User Feedback:
_"Given that I have clients using the back end, if they see the messages it confuses them, and scares them."_

### Additional comments
I support the option to allow people to submit this data and it is very useful to our process, but there is no reason for it to be persistent across all screens unless our intent is to force users to make a decision, which it should never be. 

This option is presented to our users as a way to help improve Joomla, but the persistent message essentially destroys UX everywhere outside the control panel by popping up and pushing all features down the screen considerably until they make choice. The choice they make may be out of frustration or a desire to make the message go away, and this potentially skews the data regarding the choices users are making.

If it's limited to being persistent on the dashboard, they'll see it when they login, which I still don't like but it's better than the way it is now. I think the presentation of this option should be completed revisited in J4, but I feel limiting it to the control panel is a fair compromise for now. I hope we can do something about this sooner than later.

**Comment by zero-24** [comment]
see #13948 for the code.
