### ISSUE TITLE
Accidentally deleted default language permanently, results in missing menus, submenus, articles, modules, extensions

### ISSUE THREAD

**Issue by vneelu** [joomla/joomla-cms#13959]
Hello
while working on multilingual settings, i accidentally deleted main default language(en-GB) permanently, 
then i checked menus, found menus are disappeared, trying to check articles sub menus, modules, extensions found that everything disappeared,
I tried to reinstall en-GB and added it to content language and marked it as default language, still no luck.
Also tried to replace Joomla project folder with fresh backup folder, but it seems language settings changed all over the server, so no luck
 

i have recently upgraded to Joomla 3.6.4. on our local server.

please advice
thanks

**Comment by infograf768** [comment]
Please ask help on the forums. This repository concerns Joomla coding.

**Comment by infograf768** [comment]
Closing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13959">issues.joomla.org/tracker/joomla-cms/13959</a>.</sub>
