### ISSUE TITLE
Installation Does Not Set Language/Install Language As Expected

### ISSUE THREAD

**Issue by gsexton** [joomla/joomla-cms#13955]
### Steps to reproduce the issue

Do a new installation of Joomla. On page 1, when I access it, it asks me to confirm my language is English (United States).

Accept the default, complete the installation and login.

### Expected result

English (en-US) should be installed and configured as the default language.

### Actual result

The default language, and the only language installed is English (en-GB).

### System information (as much as possible)

OpenSUSE Linux Leap 42.2 with PHP 5.5.x

**Comment by zero-24** [comment]
Yes this is expected behavior if you want to have en-US as default language you need to install it using the `install additional languages` button at the end of the install prozess.

**Comment by gsexton** [comment]
While I suppose you're technically correct, not using the selected language by default IS a usability. It doesn't do what users expect. If I pick my language for the install, then that's what things should default to.
