### ISSUE TITLE
[com_search] PHP Notice:  Trying to get property of non-object

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#13960]
[07-Feb-2017 10:42:38 UTC] PHP Notice:  Trying to get property of non-object in ROOT/components/com_search/controller.php on line 89
### Steps to reproduce the issue
Do not create a Search menu item.
Use the Search Module and do a search.
The results display in the page.

Now use the Search field in the page (not the module).
Result: the Notice is logged in the php logs.

Only way to solve this is to create a Search Menu item, published, hidden or not.

**Comment by zero-24** [comment]
Closing as there is a PR at #13961
