### ISSUE TITLE
Language - switch back

### ISSUE THREAD

**Issue by anfo7** [joomla/joomla-cms#13966]
### Steps to reproduce the issue

I open the home page of my website and change the language from german to italian using the link displayed by the language module. Now I close the browser tab an reopen my website in a new tab. The website appears immediately in italian, as this is the language I had selected before.

Now, if I want to change the language back to german, this isn't working anymore. Even if I manually type in www.domain.com/de I always get redirected to www.domain.com/it. 

However, it works if I type in the address www.domain.com/de/index.php. This behaviour apperas only on the home page and only if in the System - Language Filter-settings I set Remove URL Language Code to Yes (URL-Rewrite with standard .htaccess-file is activated)

### System information (as much as possible)

Webserver: Apache/2.2.15 (CentOS)
Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
PHP-Version 7.0.15
Database: 5.5.54-MariaDB
PHP-Interface: cgi-fcgi
Tested in Chrome and Firefox, on two different server
No external plugins installed

**Comment by infograf768** [comment]
I can't reproduce your issue.
What is your site default language?
Is the user logged in? In this case, what is the site default language for the user?

Is SEF on?
Is Use URL Rewriting on?
Are you using .htaccess ?

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13966">issues.joomla.org/tracker/joomla-cms/13966</a>.</sub>

**Comment by anfo7** [comment]
Thanks for your reply!

Default language is german (de-DE)
No, the user is not logged in.
SEF is on, as well as URL Rewriting with Joomlas standard .htaccess-file
Adds Suffix to URL is set to NO
Unicode Aliases is set to NO

System languagefilter-Plugin:
Language selection for new visitors: Site language
Automatic language change: Yes
Item Associations: Yes (problem persists even if set to NO)
Alternate Meta-Tag: Yes
Add x-default Meta Tag: Yes
x-default Language: German
Remove URL Language Code: Yes **(if set to NO, everything works fine)**
Cookie Lifetime: session

The problem happens only when I change the language on the start page (www.domain.com/it back to www.domain.com). On all other pages (www.domain.com/it/example to www.domain.com/example) the switching works fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13966">issues.joomla.org/tracker/joomla-cms/13966</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@anfo7 Can't confirm Issue. Used same Settings you wrote. Difference: Testing on 3.7. Does it happen also on different Browsers/OS?
#### Test on:
Joomla! 3.7.0-latest staging
macOS Sierra, 10.12.3
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by anfo7** [comment]
Thank you for testing. Strange. Yes, the problem occurs on Firefox 51 (32-Bit), Chrome 56 and Opera. I tested it on two different templates (including Beez3), on two different server and on two different PCs with different operating systems (Windows 8.1 and Windows 10). There are no external plugins installed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13966">issues.joomla.org/tracker/joomla-cms/13966</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
close as unconfirmed Report. @anfo7 please reopen if further Discussion is needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13966">issues.joomla.org/tracker/joomla-cms/13966</a>.</sub>
