### ISSUE TITLE
New 3.7 Router Testing Results

### ISSUE THREAD

**Issue by hypeitinc** [joomla/joomla-cms#13983]
### Actual result
I made a clone of my Joomla 3.6.5 site
I tested all the urls before updating to Joomla 3.7 Beta 1 and they were all OK
I updated to Joomla 3.7 beta 2 and tested all the urls and they were all OK
I enabled the Modern Router and tested all the urls and they were all OK
I changed Remove IDs from URLs from No to Yes and tested all the urls and they were all OK

**Comment by wilsonge** [comment]
Awesome. Thankyou so much for your report @hypeitinc :) I'm glad you've found it a positive experience :)
