### ISSUE TITLE
New 3.7 Router Testing Results

### ISSUE THREAD

**Issue by bayareajenn** [joomla/joomla-cms#13984]
### Steps to reproduce the issue
https://brian.teeman.net/joomla/874-first-looks-joomla-3-7-router

### Actual result
I made a clone of my Joomla 3.6.5 site
I tested all the urls before updating to Joomla 3.7 Beta 2 and they were all OK
I updated to Joomla 3.7 beta 2 and tested all the urls and they were all OK
I enabled the Modern Router and tested all the urls and they were all OK
I changed Remove IDs from URLs from No to Yes and tested all the urls and they were all OK

### System information (as much as possible)
Windows 7, FF, Rochen, PHP 5.6.x

### Additional comments
This worked really well.

**Comment by zero-24** [comment]
Thanks for your feedback. As everything looks ok for you i'm going to close this issue. Thanks for testing!
