### ISSUE TITLE
New 3.7 Router Testing Results

### ISSUE THREAD

**Issue by asiewert61** [joomla/joomla-cms#13985]
### Steps to reproduce the issue

Did steps at:

https://brian.teeman.net/joomla/874-first-looks-joomla-3-7-router

Set up clone of working site

### Actual result

I made a clone of my Joomla 3.6.5 site Beta 2
I tested all the urls before updating to Joomla 3.7 Beta 1 and they were all OK
I updated to Joomla 3.7 beta 1 and tested all the urls and they were all OK
I enabled the Modern Router and tested all the urls and they were all OK
I changed Remove IDs from URLs from No to Yes and tested all the urls and they were all OK

### System information (as much as possible)

MacOS Sierra ver. 10.23.3
Safari 10.0.3
used Integrity v6 to test links

**Comment by zero-24** [comment]
Thanks for your feedback. As everything looks ok for you i'm going to close this issue. Thanks for testing!
