### ISSUE TITLE
[multilingual] In Frontend "Show Associations" isn't translated

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#13987]
### Steps to reproduce the issue
Articles > Options, Tab "Articles": Set `Show Associations` to `Show`.

In Frontend lang.-String isn't translated, in all 4 tested Languages its english:
![1](https://cloud.githubusercontent.com/assets/8235763/22772202/a2c40d96-ee9b-11e6-9c97-39574fb46768.JPG)
#### Test on:
Joomla! 3.7.0-latest staging
macOS Sierra, 10.12.3
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by infograf768** [comment]
This is to be expected as the 3.7.0 lang packs will only be released after 3.7.0 final release.

**Comment by infograf768** [comment]
Closing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13987">issues.joomla.org/tracker/joomla-cms/13987</a>.</sub>

**Comment by infograf768** [comment]
You can test by installing this French pack which should be up-to-date with beta2
https://github.com/infograf768/fr-FR-3.x/releases/download/v3.7.0.1.beta2/fr-FR_joomla_lang_full_3.7.0v1.zip

**Comment by franz-wohlkoenig** [comment]
thanks @infograf768 haven't known its a new 3.7-Lang.-string.
