### ISSUE TITLE
[Installation] Fix Postrgres and mssql sample data for #__menu

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#13981]
### Steps to reproduce the issue

We need a similiar PR like #13979 for mssql and postgressql

### Additional comments

- Install joomla without any sample data (the first option)
- login and hit the menu rebuild button
- go to the databse
- download the #__menu and #__menu_types table
- Sync the entrys with that in the sample data

This needs to be done for all sample data by repeating the steps above.

**Comment by zero-24** [comment]
This also needs to include the syncing of the #__menu entry for the backend menu like this: #13939

**Comment by csthomas** [comment]
There is a PR #14223

**Comment by zero-24** [comment]
Thanks 👍
