### ISSUE TITLE
tags not filtered on the current language

### ISSUE THREAD

**Issue by pulsarinformatique** [joomla/joomla-cms#13996]
### Steps to reproduce the issue
Create a multi language site as usual

Set up the tag language filter (in the tag component options) to CURRENT

Login (as an administrator) on the front end 

Edit an article in the front en

### Expected result
the article TAG field should display only  the tags on the current language

### Actual result
BUT the article TAG field displays ALL the tags whatever langage they are assigned to.

### System information (as much as possible)
3.7.0 beta 2

**Comment by franz-wohlkoenig** [comment]
Confirmed on Joomla! 3.7.0-beta3. But: Displayed on Frontend is correct Language-Tag.

**Comment by infograf768** [comment]
Maybe we could just do something like:

```php
diff --git a/libraries/cms/form/field/tag.php b/libraries/cms/form/field/tag.php
index 818c46b..56d21f4 100644
--- a/libraries/cms/form/field/tag.php
+++ b/libraries/cms/form/field/tag.php
@@ -112,4 +112,6 @@
 	{
 		$published = $this->element['published']?: array(0, 1);
+		$app       = JFactory::getApplication();
+		$tag       = $app->getLanguage()->getTag();
 
 		$db    = JFactory::getDbo();
@@ -134,4 +136,9 @@
 		}
 
+		if ($app->isClient('site') && JLanguageMultilang::isEnabled())
+		{
+			$query->where('a.language in (' . $db->quote($tag) . ',' . $db->quote('*') . ')');
+		}
+
 		$query->where($db->qn('a.lft') . ' > 0');
```
This would filter the Options list in frontend to show only the tags assigned to the current language as to All languages.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/issues/14006

**Comment by infograf768** [comment]
Closed as we have a patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13996">issues.joomla.org/tracker/joomla-cms/13996</a>.</sub>
