### ISSUE TITLE
3.6.5 SMTP Mail not working PHP Version 7.0.13-0ubuntu0.16.04.1

### ISSUE THREAD

**Issue by blackdoginet** [joomla/joomla-cms#13993]
### Steps to reproduce the issue 
Fresh install 3.6.4 on PHP Version 7.0.13-0ubuntu0.16.04.1
Configure mail
send Mail Yes , Disable mass mail No, From me@mydomain.net Name me 
Mailer SMTP
smtp host smtp.mydomain.net
port 587
encryp STARTTLS
auth req YES
Username me@mydomain.net
passwd mypasswd
Save configuration
Sent test email 
Add contact form to menu
Send message via contact form
Repeat all exactly above on PHP Version 5.6.29-0+deb8u1 and all works as expected
### Expected result
The email was sent successfully to me@mydomain.net using SMTP. You should check that you've received the test email.

### Actual result
Notice
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Error
Test mail could not be sent.

Contact form hangs!

### System information (as much as possible)
PHP Built On 	Linux mail 2.6.32-042stab111.12 #1 SMP Thu Sep 17 11:38:20 MSK 2015 x86_64
Database Version 	5.5.5-10.1.21-MariaDB-1~xenial
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.0.13-0ubuntu0.16.04.1
Web Server 	Apache/2.4.18 (Ubuntu)
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0 
Full sysinfo attached[systeminfo-2017-02-09T08_08_07-05_00.txt](https://issues.joomla.org/uploads/1/591013010c9fd5f33080d2378bcd66e8.txt)

### Additional comments
Openssl Check performed openssl s_client -starttls smtp -crlf -connect smtp.mydomain.net:587
returns code 0, which indicates successful verification

**Comment by zero-24** [comment]
@blackdoginet Please set your site in debugging mode than we should be able to see more detailed information. You may not be on GoDaddy?
https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#godaddy

**Comment by blackdoginet** [comment]
I am not on GoDaddy its my own VPS 
Debugging switched on. 
FYI PHPmailer V 5.6.2 SMTP also fails on this machine but runs on PHP 5.6

**Comment by blackdoginet** [comment]
Further last few lines from output from
openssl s_client -starttls smtp -crlf -connect smtp.mydomain.net:587

 Start Time: 1486712119
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
250 DSN
quit
221 2.0.0 Bye
closed
show there is no problem with certificates or firewalls

**Comment by zero-24** [comment]
hmm the last guess i have is:

> Openssl Check performed openssl s_client -starttls smtp -crlf -connect smtp.mydomain.net:587

Here you use 587 as port number.

In Your Configuration you uploaded it is 25

`smtpport: 25`

If this is not the problem i suggest to move this issue with sending mails to a server forum or the joomla forum (forum.joomla.org) as you are the only one who reports such issues and i got some feedback that it is working fine on other sites with SMTP & PHP7.

**Comment by blackdoginet** [comment]
It is an issue I switched to port 25 to use SSL. My mail server uses STARTTLS so I originally used 587 that. **NEITHER** work

**Comment by blackdoginet** [comment]
It is reported multiple times on extension forums see http://www.fox.ra.it/forum/5-support/11835-php-7-error.html?start=10 and also last 2 comments in  phpmailer issue https://github.com/PHPMailer/PHPMailer/issues/953
It is not my configuration

**Comment by blackdoginet** [comment]
Deepest Apologies. Was my config. Fail2Ban running on mail server blocking smtp login
Issue closed.
Sorry

**Comment by zero-24** [comment]
Glad you solved it. Thanks for the update :+1:

**Comment by ZerooCool** [comment]
**I have a exemple with my full noob configuration with Debian 9.5 and PHP7.2 and, before, PHP7.0 and, the same bog, SMTP doesn't work correctly.**

1) My light serveur for test : https://github.com/ZerooCool/Linux-Search-Engine-Optimisation/blob/master/installation/3-installer-le-serveur-dans-le-conteneur.sh
2) My light installation with Joomla (last version) https://github.com/ZerooCool/Linux-Search-Engine-Optimisation/blob/master/installation/4-installer-joomla.sh

Option SMTP on Joomla, with port 587 and SSL/TLS or STARTTLS, with identification.

**I have this message in french, and, mail doesn't work**
Annonce
Impossible de connecter par SMTP https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Erreur
Le test d'e-mail n'a pu être envoyé.

cd /var/log/user.log
Jul 31 17:17:42 : [31-Jul-2018 17:17:42 Europe/Berlin] mail() on **[/var/www/html/libraries/vendor/phpmailer/phpmailer/class.phpmailer.php:702]**: To: mail@domain.com -- Headers: Date: Tue, 31 Jul 2018 17:17:42 +0200 From: =?utf-8?Q?Green_NRJ_-_Alternatives_pour_une_soci=C3=A9t=C3=A9_collaborati?= =?utf-8?Q?ve_et_=C3=A9cologique=2E?= <mail@domain.com> Message-ID: <... ...@... ...> MIME-Version: 1.0 Content-Type: text/plain; charset=utf-8 Content-Transfer-Encoding: 8bit

Now, more info,
1) I don't have SSL with my website. You have my config on the top.
2) 2/3 mails SMTP never work (smtp.visionduweb.com and ns0.ovh.com not work)
    1/3 work. SMTP with SSL/TLS and Gmail on the 465 port work good.

3) I don't use Fail2ban.
4) I don't have enable “Less Secure Apps” on my Gmail account and mail work good.

Mail don't work with 2 other smtp serveur (smtp.visionduweb.com and ns0.ovh.com not work)
I can use this SMTP with redmine, or, mediawiki, and, work good.

For this test, i have use my VPS OVH with Debian 9.5, and, Virtualbox with Debian 9.5.
Exactly the same result, with the same config.

**Comment by ghost** [comment]
@ZerooCool Thanks for your Comment, but please open a new Issue as Comments on closed Issues didn't get much Notice.
