### ISSUE TITLE
Can't check-in a Multilingual Association item

### ISSUE THREAD

**Issue by htmgarcia** [joomla/joomla-cms#13999]
### Steps to reproduce the issue

- Go to Components > Multilingual Association
- Filter by articles and english language (it can be another component and/or language)
- Open a Multilingual Association from the results
- Don't click close button, just open a new tab and go to Components > Multilingual Association, so the association will be locked and you will see the lock icon:

![checkin](https://cloud.githubusercontent.com/assets/4999794/22793722/4d12b5bc-eeb6-11e6-82e1-9e81be94f4f7.jpg)
If you click on check-in icon, nothing happens

Console makes reference to an empty string passed for `getElementById()` in every click on the lock icon (*the error attached is in spanish).
![jserror](https://cloud.githubusercontent.com/assets/4999794/22793885/c78737aa-eeb6-11e6-970c-96987d568016.jpg)

### Expected result
The Multilingual Association should be checked-in after doing click on the lock icon

### Actual result
Nothing happens. The Multilingual Association remains locked.

### System information (as much as possible)
Joomla 3.7 Alpha 2
Firefox 50.1.0
MacOS Sierra 10.12.2

**Comment by htmgarcia** [comment]
Thanks for checking into this @franz-wohlkoenig!

**Comment by infograf768** [comment]
@rdeutz 

Can you have a look?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13999">issues.joomla.org/tracker/joomla-cms/13999</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
ping @rdeutz as Issue is also on latest Staging.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13999">issues.joomla.org/tracker/joomla-cms/13999</a>.</sub>

**Comment by rdeutz** [comment]
closing because we have a PR #15873

**Comment by htmgarcia** [comment]
Thanks guys!

**Comment by rdeutz** [comment]
@htmgarcia could you test my PR so that we can get two successful tests and we can merge it
