### ISSUE TITLE
[J4.0] [com_finder] SQL error on "maps" view

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#13997]
### Steps to reproduce the issue

Visit: `administrator/index.php?option=com_finder&view=maps`

### Expected result

A visible view

### Actual result

> 500 - An error has occurred.

> Expression #7 of SELECT list is not in GROUP BY clause and contains nonaggregated column 's.count_published' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by Expression #7 of SELECT list is not in GROUP BY clause and contains nonaggregated column 's.count_published' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by Expression #7 of SELECT list is not in GROUP BY clause and contains nonaggregated column 's.count_published' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

### System information (as much as possible)
- Joomla 4.0-dev
- PHP 7 and 5.x

**Comment by csthomas** [comment]
Try this one https://github.com/joomla/joomla-cms/pull/13854

**Comment by C-Lodder** [comment]
Closing with PR
