### ISSUE TITLE
Showon stopped working with multilevel field groups

### ISSUE THREAD

**Issue by tassosm** [joomla/joomla-cms#14002]
### Steps to reproduce the issue
Consider the following form

```
      <fieldset name="settings" label="LABEL">
        <fields name="fruites">
            <fields name="apple">
                <field name="enabled" type="radio" 
                    label="JENABLED" 
                    default="1">
                    <option value="1">JYES</option>
                    <option value="0">JNO</option>
                </field>
                <field name="price" type="text" 
                    showon="enabled:1" 
                    label="label1"
                />
            </fields>
        </fields>
    </fieldset>
```

### Expected result
The price should be shown when we choose Yes on the enabled field

### Actual result
The price field never shows up

### System information (as much as possible)
Joomla! 3.7.0-beta2
PHP 7.0.15

### Additional comments
Here's the produced showon attribute on Joomla 3.7.0-beta2
`data-showon='[{"field":"jform[fruites.apple][enabled]","values":["1"],"sign":"=","op":""}]'`

And here's the produced showon attribute on Joomla 3.6.5 which works
`data-showon='[{"field":"jform[fruites][apple][enabled]","values":["1"],"op":""}]'`

**Comment by Bakual** [comment]
I fixed something related to groups lately: https://github.com/joomla/joomla-cms/pull/13549
But I wasn't aware that there can be more than one group. Then the groups parameter here liklely needs to be exploded and added for each group here: https://github.com/Bakual/joomla-cms/blob/staging/libraries/joomla/form/helper.php#L343

**Comment by tassosm** [comment]
@Bakual, thanks. I've seen your fix and it didn't help.
Exploding the groups param should solve the issue indeed.

**Comment by Bakual** [comment]
You want to do the PR?

**Comment by jeckodevelopment** [comment]
Closing as we have a PR to test: #14007
