### ISSUE TITLE
Browser Page Title Not Working with Tags Component

### ISSUE THREAD

**Issue by rgblogs** [joomla/joomla-cms#14003]
### Steps to reproduce the issue

1. Create a new tag in Tags component (example JOOMLA)
2. Create a menu item with compact list of tagged item. Set menu title to JOOMLA. Select tag JOOMLA
3. Under page display, set Browser Page Title to: JOOMLA TUTORIALS
4. Open the menu item from the front-end of the website. 

### Expected result

The browser page title should be JOOMLA TUTORIALS

### Actual result

The page title in browser is JOOMLA (name of the tag)

**Comment by franz-wohlkoenig** [comment]
known Issue #13365

**Comment by jeckodevelopment** [comment]
Closing as dupblicate of #13365
