### ISSUE TITLE
Login-Form: Username-, Password-Field-Length

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14010]
### Steps to reproduce the issue
Default Field-Length in Protostar are to small:
![bildschirmfoto 2017-02-10 um 13 34 23](https://cloud.githubusercontent.com/assets/8235763/22827157/ac5d0c44-ef96-11e6-9f6f-68cb3ae6fc5f.JPG)
### Expected result
Length of Field till right Module-Side, similar here:
![1](https://cloud.githubusercontent.com/assets/8235763/22827250/075b682a-ef97-11e6-99bc-b8d4cc567527.JPG)
#### Test on:
Joomla! 3.7.0-latest staging
macOS Sierra, 10.12.3
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.54-0

**Comment by PhilETaylor** [comment]
However: :-) 

![screen shot 2017-02-11 at 16 15 17](https://cloud.githubusercontent.com/assets/400092/22855266/56383156-f075-11e6-8a0a-0b2942d1bfe2.png)

**Comment by franz-wohlkoenig** [comment]
or ...
![1](https://cloud.githubusercontent.com/assets/8235763/22855333/501eee90-f07f-11e6-8595-a95819b3f73c.png)

**Comment by dgt41** [comment]
@ciar4n can you take a look at his one?

**Comment by ciar4n** [comment]
PR created.. #14027
