### ISSUE TITLE
lack of proper margin in modal 

### ISSUE THREAD

**Issue by utkarshshukla2912** [joomla/joomla-cms#14016]
### Steps to reproduce the issue

login to admin -> templates in the left panel - >again templates in the left panel -> Protostar Details and Files - > click copy template from the top -> improper spacing is witnessed 
![screen shot 2017-02-11 at 2 23 10 am]

### Expected result
proper margin in the modal

### Actual result
improper margin
(https://cloud.githubusercontent.com/assets/20442398/22843959/e2edf474-f001-11e6-987b-2d0f5560a7ad.png)
![Uploading Screen Shot 2017-02-11 at 2.23.10 AM.png…]()

**Comment by franz-wohlkoenig** [comment]
@ciar4n can you have a look please?

**Comment by ciar4n** [comment]
PR created... #14028
