### ISSUE TITLE
Cache page file sizes are incorrect

### ISSUE THREAD

**Issue by drewgg** [joomla/joomla-cms#14014]
### Steps to reproduce the issue

- Turn caching on
- Visit a few pages until any cache group has more than 1Mb of files cached
- Check the Size column in System > Clear Cache

### Expected result

- The size should grow fairly large (10's or 100's of megs) for some cache groups as more and more files are cached.

### Actual result

- The size values never go above 999Kb.

### System information (as much as possible)

Joomla 3.6.5
PHP 5.6
Apache/Lightspeed

### Additional comments

This bug was fixed in #1872 but reintroduced in #3202 . 

/libraries/joomla/cache/storage/helper.php

The working code was:

`$this->size = number_format((float) $this->size + (float) $size, 2, '.', '');`

This was changed to the current code:

`$this->size = number_format((float) $this->size + (float) $size, 2, JText::_('DECIMALS_SEPARATOR'), JText::_('THOUSANDS_SEPARATOR'));`

This change was done for numeric localization reasons, however, the number at this point is not an end-user facing number. It's just a numeric value being stored/modified. Because of the casting from`(float) $this->size` there will be issues...

This is the issue with using the thousands separator, the number will get cut off at the first comma found:

`$this->size = "1,234.56"; // number with a thousands separator`
`$this->size = (float)$this->size;`
`echo $this->size; // outputs: 1`

This is the issue for the decimal separator: 

`$this->size = "1.234,56"; // localized number format`
`$this->size = (float)$this->size;`
`echo $this->size; // outputs: 1.234`

For the second issue, I believe this is the case because the (float) casting does not take the localization into account (ie, I believe it always assumes the decimal separator is a period). See http://php.net/manual/en/language.types.float.php (particularly the "formal" definition near the top that has the algorithm). That could just be a simplified definition though and there is in fact localization support in the underlying code, I don't know.

For those reasons I believe the code should go back to:

`$this->size = number_format((float) $this->size + (float) $size, 2, '.', '');`

I'm not really sure why number_format() is even being used here. It might actually be better to change it to `$this->size += $size`.

The place for localization of the value should be when being outputted:

`<?php echo JHtml::_('number.bytes', $item->size*1024); ?>`

number.bytes does not do the localization either but that is the logical place for it (IMO); Final calculations on the value are being done and then the value is formatted to a string for display.

I can make a pull request for both files/issues but I wanted input first. If someone else wants to do it that's fine too.

**Comment by franz-wohlkoenig** [comment]
@drewgg can you please confirm Issue on latest staging?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14014">issues.joomla.org/tracker/joomla-cms/14014</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened in the future if it is updated.

**Comment by Melvine9** [comment]
same issue when i removed a component 

[picture](https://img15.hostingpics.net/pics/781546cachejoomla.jpg)
php 7.1.5
Joomla 3.7.2
Best Regards
Melvine
