### ISSUE TITLE
Blank white 404 error page due to the rules which were added by Joomla in the .htaccess file. What rules should be used?

### ISSUE THREAD

**Issue by GODpleasers** [joomla/joomla-cms#14018]
Blank white 404 error page due to the rules which were added by Joomla in the .htaccess file. 

### Steps to reproduce the issue

 :-[ You can see the weird looking page here..

http://www.godspeaksinternetradio.com/phpio.php

### Expected result

Load that and you will see a blank white 404 page.

### System information (as much as possible)

PHP Built On 	Linux whm.godspeaksinternetradio.com 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64
Database Version 	5.6.35
Database Collation 	latin1_swedish_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.0.15
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0 

Configuration File
Setting 	Value
 
MetaAuthor 	1
MetaDesc 	Powered by the Holy Spirit :-)
MetaKeys 	
MetaRights 	
MetaTitle 	1
MetaVersion 	0
access 	1
cache_handler 	file
cachetime 	15
caching 	0
captcha 	0
cookie_domain 	
cookie_path 	
db 	godspeak_godspk
dbprefix 	jos_
dbtype 	mysqli
debug 	0
debug_lang 	0
display_offline_message 	0
editor 	tinymce
error_reporting 	simple
feed_email 	author
feed_limit 	10
force_ssl 	0
fromname 	GOD Speaks internet radio
ftp_enable 	0
ftp_host 	127.0.0.1
ftp_pass 	xxxxxx
ftp_port 	21
ftp_root 	
ftp_user 	xxxxxx
gzip 	0
helpurl 	https://help.joomla.org/proxy?keyref=Help{major}{minor}:{keyref}&lang={langcode}
host 	xxxxxx
lifetime 	15
list_limit 	20
live_site 	
log_path 	/home/godspeaksinterne/public_html/administrator/logs
mailer 	smtp
mailfrom 	stationowners@godspeaksinternetradio.com
memcache_compress 	1
memcache_persist 	1
memcache_server_host 	localhost
memcache_server_port 	11211
offline 	0
offline_image 	
offline_message 	
offset 	UTC
offset_user 	UTC
password 	xxxxxx
robots 	noindex, nofollow
secret 	iFz6sL6ukBtjGA30hksPABjQxB7fqHvo
sef 	1
sef_rewrite 	1
sef_suffix 	1
sendmail 	/usr/sbin/sendmail
session_handler 	database
sitename 	GOD Speaks internet radio
sitename_pagetitles 	2
smtpauth 	1
smtphost 	whm.godspeaksinternetradio.com
smtppass 	xxxxxx
smtpport 	465
smtpsecure 	ssl
smtpuser 	xxxxxx
tmp_path 	/home/godspeaksinterne/public_html/tmp
unicodeslugs 	0
user 	xxxxxx
memcached_persist 	1
memcached_compress 	0
memcached_server_host 	localhost
memcached_server_port 	11211
redis_persist 	1
redis_server_host 	localhost
redis_server_port 	6379
redis_server_auth 	
redis_server_db 	0
proxy_enable 	0
proxy_host 	
proxy_port 	
proxy_user 	
proxy_pass 	
mailonline 	1
massmailoff 	0
session_memcache_server_host 	localhost
session_memcache_server_port 	11211
session_memcached_server_host 	localhost
session_memcached_server_port 	11211
frontediting 	0
asset_id 	1
cache_platformprefix 	0 

### Additional comments

Im guesing that is thje right category not sure.

**Comment by PhilETaylor** [comment]
> due to the rules which were added by Joomla in the .htaccess file.

What EXACTLY is the content of your .htaccess file? 

Joomla doesnt "add" rules to a .htaccess file! It distributes a htaccess.txt file which you can use as a basis for your own .htaccess file - but thats up to you.

**Comment by PhilETaylor** [comment]
this is more likely a PHP Fatal Error that is not being displayed to the screen - a Blank Screen *is* an error page...

**Comment by Bakual** [comment]
As this doesn't look like a core issue but a specific issue on that server, may I ask you to use the forums (https://forum.joomla.org/) for further assstance?

I'm closing this issue.

**Comment by GODpleasers** [comment]
> due to the rules which were added by Joomla in the .htaccess file.

Sorry if we are wrong but this is what WHM/CPanel support thought after spending more that an hour trying to help.

> What EXACTLY is the content of your .htaccess file?

Our .htaccess says (Please see attached)...
[htaccess.txt](https://github.com/joomla/joomla-cms/files/768750/htaccess.txt)


> Joomla doesnt "add" rules to a .htaccess file! It distributes a htaccess.txt file which you can use as a basis for your own .htaccess file - but thats up to you.

Ok, sorry did not know that before this thread but at any it started doing this when we moved to a VPS.

**Comment by GODpleasers** [comment]
> As this doesn't look like a core issue but a specific issue on that server, may I ask you to use the forums (https://forum.joomla.org/) for further assstance?
I'm closing this issue.

OK We have bean.

**Comment by PhilETaylor** [comment]
`
# php -- BEGIN cPanel-generated handler, do not edit
# Set the ìea-php70î package as the default ìPHPî programming language.
<IfModule mime_module>
  AddType application/x-httpd-ea-php70 .php .php7 .phtml
</IfModule>
# php -- END cPanel-generated handler, do not edit
`

These lines are added by the cPanel Easy Apache PHP chooser feature of Web Host Manager/cPanel servers. 

This would not effect the correct operation of Joomla 3.6.5 which is fully compatible with PHP 7

**Comment by GODpleasers** [comment]
> As this doesn't look like a core issue but a specific issue on that server, may I ask you to use the forums (https://forum.joomla.org/) for further assstance? I'm closing this issue.

Sorry to bring this up again but why does it work fine on a didcated or shared server but not on a VPS?

**Comment by PhilETaylor** [comment]
It depends on what the error message is! And at the moment your new server is "hiding" that message by just outputting a "white screen of death" - google that with Joomla and you will find lots of advice on how to enable error reporting/disable_errors to show the error message - once you have an error message, the solution is normally very evident.

Dedicated and VPS are just different marketing terms for the term "server" - they are meaningless in this conversation.

**Comment by GODpleasers** [comment]
> Since it was brought up again on we now have an error.

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; plgSystemLivingWord has a deprecated constructor in /home/godspeaksinterne/public_html/plugins/system/livingword/livingword.php on line 31

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; plgSystemPrayerCenterEmail has a deprecated constructor in /home/godspeaksinterne/public_html/plugins/system/prayercenteremail/prayercenteremail.php on line 10

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; CApplications has a deprecated constructor in /home/godspeaksinterne/public_html/components/com_community/libraries/core.php on line 1093

**Comment by PhilETaylor** [comment]
Those are NOT "errors", they are "Deprecated warnings" - totally different things! 

Errors start with "Fatal Error".

**Comment by GODpleasers** [comment]
> Those are NOT "errors", they are "Deprecated warnings" - totally different things!
Errors start with "Fatal Error".

Hmm the only other errors are in cpanel errors...
[Sat Feb 11 04:23:42.437838 2017] [core:alert] [pid 20036:tid 140287993116416] [client 24.119.180.11:60943] /home/godspeaksinterne/public_html/.htaccess: Invalid command '172.16.9.5172.16.9.5ng', perhaps misspelled or defined by a module not included in the server configuration, referer: http://www.godspeaksinternetradio.com/
[Sat Feb 11 04:23:42.437724 2017] [core:alert] [pid 20036:tid 140287993116416] [client 24.119.180.11:60943] /home/godspeaksinterne/public_html/.htaccess: Invalid command '172.16.9.5172.16.9.5ng', perhaps misspelled or defined by a module not included in the server configuration, referer: http://www.godspeaksinternetradio.com/
[Sat Feb 11 04:23:38.650039 2017] [core:alert] [pid 19947:tid 140288009901824] [client 63.142.218.225:50325] /home/godspeaksinterne/public_html/.htaccess: Invalid command '172.16.9.5172.16.9.5ng', perhaps misspelled or defined by a module not included in the server configuration
[Sat Feb 11 04:23:38.649929 2017] [core:alert] [pid 19947:tid 140288009901824] [client 63.142.218.225:50325] /home/godspeaksinterne/public_html/.htaccess: Invalid command '172.16.9.5172.16.9.5ng', perhaps misspelled or defined by a module not included in the server configuration
[Sat Feb 11 04:23:38.403513 2017] [core:alert] [pid 20007:tid 140288018294528] [client 63.142.218.225:50322] /home/godspeaksinterne/public_html/.htaccess: Invalid command '172.16.9.5172.16.9.5ng', perhaps misspelled or defined by a module not included in the server configuration, referer: http://www.godspeaksinternetradio.com/
'
Would not know where to find a fatal error.

**Comment by Bakual** [comment]
Please use the forums for support requests.
This is an issue tracker for the core itself.

I'm going to lock this conversation now.
