### ISSUE TITLE
[4.0] [com_fields] Sample data

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-cms#14019]
Would be nice to have some sample data for custom fields as well.

**Comment by Bakual** [comment]
Sure, but please don't add it to the current sample data. They are generally in such a bad state, it doesn't really help to add more to it.
Imho we should first figure out how to handle them in future (eg 4.0) and shift to a new system before adding more.

**Comment by Quy** [comment]
Is the plan to do this in v4 and not in v3?

**Comment by laoneo** [comment]
Guess there is no plan yet. I opened it as a reminder.

**Comment by brianteeman** [comment]
We have the sample data as plugins now so it should be easier for you to create - not sure I see the point myself

**Comment by brianteeman** [comment]
@franz-wohlkoenig please retag j4

**Comment by Quy** [comment]
Consolidate under #25777<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14019">issues.joomla.org/tracker/joomla-cms/14019</a>.</sub>
