### ISSUE TITLE
Incorrect datetime/incorrect default value in MySQL 5.7.14

### ISSUE THREAD

**Issue by sural98** [joomla/joomla-cms#14012]
### Steps to reproduce the issue
Upgrade wampserver (Windows) with MySQL 5.7.14
Try to import into/duplicate a table having checked_out_time field (with default 0000-00-00 00:00:00)

### Actual result
MySQL outputs incorrect datetime/incorrect default value errors and the operation fails.

### System information (as much as possible)
Windows 10
WampServer Version 3.0.6 64bit
Apache 2.4.23 - PHP 5.6.25 - MySQL 5.7.14
PHP 5.6.25 for CLI (Command-Line Interface)

**Comment by csthomas** [comment]
Before you run a query which create/copy table you should add a line:
```sql
SET @@SESSION.sql_mode = '';
```
which turns off restricted mode on mysql 5.7 per connection.

You can also disable that in global mysql configuration.

**Comment by sural98** [comment]
Turning off restricted mode in my.ini solved the problem.
Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14012">issues.joomla.org/tracker/joomla-cms/14012</a>.</sub>
