### ISSUE TITLE
Wrong menu item id is assigned to article links

### ISSUE THREAD

**Issue by lucaspottersky** [joomla/joomla-cms#14013]
### Steps to reproduce the issue
1- create an Article ("article A") that has NO MENU ITEM assigned
2- create a new Article ("article B") with a link to "article A". 
3- create a Menu Item for "article A"
4- go to "article B" and try to create a link to "article A"

See this gif for the bug: ![reproducing bug](https://issues.joomla.org/uploads/1/ea100fd526b31017ef920d0d49987e50.gif "bug animation")

### Expected result
- On Step2, Joomla should generate a Link that points to the correct Article (ItemId)? Just like Step 4. This way, when I go to the frontend, I'm redirect to the corresponding Article.

### Actual result
- On Step 2, Joomla generates a URL ending with "ItemId=101". If I go to the frontend and click this link, I'm redirected to the homepage.

### System information (as much as possible)
- Joomla! 3.6.5
- System - Language Filter is DISABLED.
- I used to have 2 Content Languages. I deleted the original one (english-GB, Id 1) and I'm left with only 1 (portuguese-BR, id: 2). ![content language tab](https://issues.joomla.org/uploads/1/de8f3c108e081d16514a2d3dda94feef.png "content language tab")

### Additional comments
I would like to know if there's a workaround for this. The same/similar issue has been discussed on the old issues tracker ([[#33132] - Wrong menu item id is assigned to article links when language filter enabled.](https://developer.joomla.org/joomlacode-archive/issue-33132.html "Wrong menu item id is assigned to article links when language filter enabled")).

OBS: how the hell you make the "BUILD" input MANDATORY and Joomla has no easy way to tell which BUILD it's running? :heart:

**Comment by zero-24** [comment]
What happen if you remove the ItemId=101?

For me it looks like a issue in the JCE link manager than.

**Comment by zero-24** [comment]
Btw the build is the version you are running:

![wp_ss_20170210_0001](https://cloud.githubusercontent.com/assets/2596554/22841082/71cd1b84-efd0-11e6-8389-a46b952cc01b.png)

**Comment by lucaspottersky** [comment]
> What happen if you remove the ItemId=101? 
The link does work.

> For me it looks like a issue in the JCE link manager than.
I don't think so. I forgot to mention that I did the same tests with TinyMCE. Aditionally, the plugin I want to use for a image gallery (BT Content Slider) is also generating the wrong links. :(

I tried to reproduce this bug on a pristine installation, but I couldn't. So I don't know what caused Joomla to behave like this.

**Comment by infograf768** [comment]
>  I forgot to mention that I did the same tests with TinyMCE.

Using the article button in TinyMCE, one will never get an itemid.
We will get one when choosing a menu item (new in 3.7.0)
Toggling editor one will get
```html
<p>text article B</p>
<p> </p>
<p><a href="index.php?option=com_content&amp;view=article&amp;id=2&amp;catid=8">Article A</a></p>
<p>New after creating menu item to article A<br /><br /><a href="index.php?option=com_content&amp;view=article&amp;id=2&amp;catid=8">Article A</a></p>
<p>Link to a article A menu item<br /><a href="index.php?Itemid=108">link to article A</a></p>
```

Then it is just a matter of router.

**Comment by lucaspottersky** [comment]
> Using the article button in TinyMCE, one will never get an itemid.

Here's a gif I recorded this morning, TinyMCE does seem to also add "ItemId=101", just like any other editor/plugin that needs to render links to Articles.

![TinyMCE creating wrong link to Article](http://i.imgur.com/zcKdfP4.gif "TinyMCE creating wrong link to Article")

**Comment by infograf768** [comment]
you do not use a 'pure' tinymce instance. as can be seen, you have 2 article buttons in its toolbar.
likely because of a 3rd party extension

**Comment by infograf768** [comment]
I suggest you install https://github.com/joomla/joomla-cms/archive/staging.zip and test with TinyMCE

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14013">issues.joomla.org/tracker/joomla-cms/14013</a>.</sub>

**Comment by Hackwar** [comment]
as @infograf768 wrote, TinyMCE does not add the Itemid (anymore). This issue is not one of core Joomla, but of the extension that you are using.

**Comment by Hackwar** [comment]
That said, this one should be closed.
