### ISSUE TITLE
build/build.php $release has non-numeric value

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [joomla/joomla-cms#14017]
When building Joomla in my branch derived from staging, I'm getting a notice that complains about the contents of `$release`.

Perhaps my php7.1 isn't set up quite like it should be for Joomla, or I have misunderstood the purpose of the `$release` variable.  The notice I'm getting is:  

    Notice: A non well formed numeric value encountered in /home/user/Downloads/Joomla/joomla-cms/build/build.php on line 138

My Line 138 is:  

    for ($num = $release - 1; $num >= 0; $num--)

The build continues, but I'm not sure what the value should be here because when I echo `$release`, it contains the string `0-beta3`.  Should it be 0 or 3, or something else in certain cases?  During my build, the string is evaluated to 0 and the for loop is bypassed.

**Comment by PhilETaylor** [comment]
This is a PHP 7.1 issue... 

See other issues:
https://github.com/joomla/joomla-cms/pull/12311
https://github.com/joomla/joomla-cms/pull/13251
https://github.com/joomla/joomla-cms/issues/12310

**Comment by Napoleon-BlownApart** [comment]
@PhilETaylor : Right.  Should I (or you) close this issue then?

**Comment by franz-wohlkoenig** [comment]
closed as this Issue is not an Core-Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14017">issues.joomla.org/tracker/joomla-cms/14017</a>.</sub>

**Comment by mbabker** [comment]
It is a core issue.  The build script lives in the repository and is how we build release packages.  So someone needs to confirm the build script works correctly on PHP 7.1 and if not fix it.

**Comment by brianteeman** [comment]
i can confirm that the build script is NOT working correctly on php 7.1.1 so someone with better skills than me needs to fix it ;)

**Comment by mbabker** [comment]
We probably need to restructure our internal constants in `JVersion` so they are always consistently strings or integers, not mixed.  The way Symfony does it, each of their version constants in the Kernel is a fragment of the full version string, then they have a constant which is the full version string.  https://github.com/symfony/http-kernel/blob/3.4/Kernel.php#L64-L69

**Comment by brianteeman** [comment]
Closed please see #16169
