### ISSUE TITLE
[Installation] 2 times "English (Australia)"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14023]
### Steps to reproduce the issue
Install latest staging, got on Tab 1 "Configuration":
![1](https://cloud.githubusercontent.com/assets/8235763/22854451/2a060280-f06f-11e6-92a4-b224fe6c492f.JPG)
#### Test on:
Joomla! 3.7.0-beta3
macOS Sierra, 10.12.3
Firefox 51.0.1
PHP 7.0.4
MySQLi 5.5.54-0

**Comment by Bakual** [comment]
Good catch, should be English (Canada). See https://github.com/joomla/joomla-cms/blob/staging/installation/language/en-CA/en-CA.xml where it is wrong 😄 

Going to fix it directly.
