### ISSUE TITLE
[4.0] Module saved failed "Incorrect datetime"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14022]
### Steps to reproduce the issue
Open and save Module:
![bildschirmfoto 2017-02-11 um 15 10 31](https://cloud.githubusercontent.com/assets/8235763/22854346/c919f1a4-f06c-11e6-80e9-40255ef6567d.JPG)
### System information (as much as possible)
Joomla! 4.0-nightly builds
macOS Sierra, 10.12.3
Safari 10.0.3
PHP 7.0.15
MySQLi 5.6.35
Mamp 4.1.1

**Comment by tonypartridge** [comment]
This is the same issue as #13031 I believe. Are you up to date?

**Comment by franz-wohlkoenig** [comment]
looks similar, todays Joomla! 4.0-nightly builds.

**Comment by franz-wohlkoenig** [comment]
Works now.
