### ISSUE TITLE
sample data: URL "Joomla.org" in Menu "Top" should open in new Tab

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14038]
### Steps to reproduce the issue
Installing sample data set in Menu "Top" the URL "Joomla.org", which opens in same Tab, should open in new Tab (Source #14032).
### System information (as much as possible)
Joomla! 3.7.0-beta3
macOS Sierra, 10.12.3
Firefox 51.0.1
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by mbabker** [comment]
Accessibility standards discourage forcing a new tab/window to be opened with links.

**Comment by franz-wohlkoenig** [comment]
thanks for Info.

**Comment by mbabker** [comment]
If you search through the issue history, there's been more references to the relevant documentation posted here in the past.  Unfortunately, I've never actually read it, but the person (who is blocked from participating here at the moment) who has shared that info has posted references a few times as well.

**Comment by franz-wohlkoenig** [comment]
its a personal view: i like external Urls in an external tab (learned long time ago so). But Accessibility beats.
