### ISSUE TITLE
[4.0] "Edit Account" > Unknown column 'profile.%' in 'where clause'

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14040]
### Steps to reproduce the issue
Click "Edit Account"
![bildschirmfoto 2017-02-12 um 18 03 16](https://cloud.githubusercontent.com/assets/8235763/22864245/3f300e00-f14e-11e6-80a9-197170037a82.JPG)
got
![bildschirmfoto 2017-02-12 um 18 03 56](https://cloud.githubusercontent.com/assets/8235763/22864248/473be60a-f14e-11e6-8d85-085c2598e69b.JPG)
#### Test on:
Joomla! 4.0-nightly builds
macOS Sierra, 10.12.3
Safari 10.0.3
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
hmm, I can't reproduce this issue.

**Comment by joomdonation** [comment]
@C-Lodder Enable User - Profile plugin and you will see the issue

**Comment by joomdonation** [comment]
I made PR https://github.com/joomla/joomla-cms/pull/14050 to fix it. Please test so that we can get the issue fixed.
