### ISSUE TITLE
[4.0] Notice at Post-Installation Messages

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14042]
### Steps to reproduce the issue
Components > Post-Installation Messages:
![bildschirmfoto 2017-02-12 um 20 42 41](https://cloud.githubusercontent.com/assets/8235763/22865416/35ae2590-f164-11e6-87ac-26f1ab8bd95e.JPG)
#### Test on:
Joomla! 4.0-nightly builds
macOS Sierra, 10.12.3
Safari 10.0.3
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by zero-24** [comment]
This is third party code that should be removend before 4.0 stable. So i guess we should better try to replace the code than to fix the bug in the third party code ;)

**Comment by zero-24** [comment]
I think we should let this open as reminder to remove the now broken code from 4.0 :smile:

**Comment by wilsonge** [comment]
I've fixed this for now so I'm closing but we do need to remove FOF

**Comment by franz-wohlkoenig** [comment]
thanks @wilsonge
