### ISSUE TITLE
Uncaught ReferenceError

### ISSUE THREAD

**Issue by jordan-chang** [joomla/joomla-cms#14059]
I have heaps of JS error on my browser console. When i login to the Joomla Administrator page, none of the button seems to work. Not even clearing the cache or update.

Below are the JS error received:

![](http://i.imgur.com/xKDOPUJ.png "")

**Comment by marrouchi** [comment]
It's seems that there are some missing files. Are you sure you uploaded everything ?

**Comment by jordan-chang** [comment]
I'm not sure but is there a way i can upgrade Joomla 2.5.28 manually because i literally press any SAVE or CLOSE button. Any help would be much appreciated.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14059">issues.joomla.org/tracker/joomla-cms/14059</a>.</sub>

**Comment by jordan-chang** [comment]
I'm not sure but is there a way i can upgrade Joomla 2.5.28 manually because i literally cannot press the SAVE or CLOSE button at all. Any help would be much appreciated.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14059">issues.joomla.org/tracker/joomla-cms/14059</a>.</sub>

**Comment by rdeutz** [comment]
not a bug, please use the forum for support
