### ISSUE TITLE
Wrong button action when trying to change menu item article

### ISSUE THREAD

**Issue by sh-si** [joomla/joomla-cms#14058]
### Steps to reproduce the issue
* open joomla backend
* navigate to menu-configuration
* create new menu item
* select type "article"
* select "article" for menu item
* save menu item 
* try to change previously selected article

### Expected result
There should be a button with functionality "select article" as in 3.6.5 and previous.

### Actual result
There is a button with functionality "edit article".

### Additional comments
Please have a look at the screenshots in german language:

![screenshot-edit-menu-item_3 6 5](https://cloud.githubusercontent.com/assets/392563/22907054/917460ea-f247-11e6-9aef-dfbed8439086.png)
![screenshot-edit-menu-item_3 7 0](https://cloud.githubusercontent.com/assets/392563/22907053/9171efd6-f247-11e6-9ac2-d7322a064752.png)

**Comment by infograf768** [comment]
If you want to choose another article, you first have to Clear the existing one.

**Comment by sh-si** [comment]
Uh! Got it. I think, that i'm not the only one who stumbles upon this.
