### ISSUE TITLE
Joomla 3.7 beta1 - Custom field "Gallery" error

### ISSUE THREAD

**Issue by ketihar** [joomla/joomla-cms#14056]
### Steps to reproduce the issue
1.Create article.
2.Create custom field type gallery
3.On article gallery field select one folder to show the images, for example sampledata
4.Open article on frontend

### Expected result
Article with photo gallery

### Actual result
Error message without gallery

### System information (as much as possible)
7.0.10
Web Server	Apache/2.4.23 (Win64) PHP/7.0.10
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.7.0-beta1 Beta [ Amani ] 2-February-2017 18:53 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36![screen shot 2017-02-13 at 18 30 37](https://issues.joomla.org/uploads/1/ee7538fca9aa8a5a15ba9f69e9b3b487.jpeg)

**Comment by obuisard** [comment]
The solution is to change (line 71 in beta 2):
$localPath = str_replace(JPATH_ROOT . '/' . $root . '/', '', $file);
with		
$localPath = str_replace(JPATH_ROOT . DIRECTORY_SEPARATOR . $root . DIRECTORY_SEPARATOR, '', $file);

**Comment by zero-24** [comment]
Can you send that changes as PR against staging?
