### ISSUE TITLE
User - Profile plugin: required fields are marked as optional

### ISSUE THREAD

**Issue by Marvino-il-Marziano** [joomla/joomla-cms#14051]
### Steps to reproduce the issue
Install new blank Joomla (3.6.5 downloaded, new database made; installed with no demo content)
Allow user registration
Activate 'User - Profile' plugin and make one of the fields required (e.g., 'favourite book') in the 'Registration and administrator' form.

### Expected result
All fields marked with a '*' in the User Registration section, all fields marked '(optional)' in the User Profile section EXCEPT the one toggled to required.

Filling in all User Registration fields and none of the User Profile fields throws 'Warning Field required: Favourite Book:' and failure to register new user.

### Actual result
All as expected (including warning and non-registration), except the required field(s) marked as '(optional)'!

### System information (as much as possible)
MacOS 10.11.6 (El Capitan)
MAMP 4.1.1
Joomla 3.6.5

### Additional comments
This makes very irritating user registration, where the user must guess which fields are required (and each time re-type the desired password).

!!Just found out:!! My webhost has a slightly outdated Joomla install script on its CPanel, so I followed the above instructions with them: This installed Joomla 3.6.4, and all works as expected ['*' with the required field, when trying to save this field gets focus so it highlighted red]. When updating that to 3.6.5, the bug immediately appears.

Before that, I distinctly remembered this working correctly around 3.6.0. I used the User-Profile plugin as template for my own plugin; that used to work correctly, and now has the same issue (so the problem should be not inside the User-Profile plugin, but somewhere else not checking correctly when adding the '(optional)' instead of the '*'?).

**Comment by infograf768** [comment]
please test with staging<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14051">issues.joomla.org/tracker/joomla-cms/14051</a>.</sub>

**Comment by Marvino-il-Marziano** [comment]
Tested with staging version: Works correctly, '*' instead of '(optional)' appears next to required fields.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14051">issues.joomla.org/tracker/joomla-cms/14051</a>.</sub>

**Comment by zero-24** [comment]
Staging is the code for the next planed version so im going to close this as fixed in next update. Thanks.
