### ISSUE TITLE
Joomla 3.7 beta1 - Article Link Author does not work

### ISSUE THREAD

**Issue by ketihar** [joomla/joomla-cms#14055]
### Steps to reproduce the issue
1.Create a user.
2.Create a contact for this user.
3.Create one article with this user.
4.Go to content options and enable "Link Author" option.
5.On frontend go to article and click on author link.

### Expected result
You must see author contact form

### Actual result
You dont see author contact form. I see only contact categories and when i click to them nothing happens.

### System information (as much as possible)
PHP Version	7.0.10
Web Server	Apache/2.4.23 (Win64) PHP/7.0.10
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.7.0-beta1 Beta [ Amani ] 2-February-2017 18:53 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36![screen shot 2017-02-13 at 17 42 27](https://issues.joomla.org/uploads/1/42990d920b36bb82cc7bfa3067b3bfa7.jpeg)

### Additional comments

![screen shot 2017-02-13 at 17 42 29](https://issues.joomla.org/uploads/1/e1f04f9c9cd24195660bfb101e12f7d9.jpeg)![screen shot 2017-02-13 at 17 42 32](https://issues.joomla.org/uploads/1/1a3f18a957a52672542a68deb82d551e.jpeg)

**Comment by zero-24** [comment]
@ketihar can you please confirm that you using the legacy router? (you can find the switch in the com_contact options in the backend.)

**Comment by ketihar** [comment]
I use modern router on com_content, com_users and com_contact. When i change to legacy router on com_contact the problem is still there. But when i use legacy router on com_content everything is working. This is weird. Modern router is not supported from all joomla components?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14055">issues.joomla.org/tracker/joomla-cms/14055</a>.</sub>

**Comment by AlexRed** [comment]
I can't reply the problem using Routing legacy and also using modern Routing.
Joomla 3.7.0 Beta3 dev

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14055">issues.joomla.org/tracker/joomla-cms/14055</a>.</sub>

**Comment by zero-24** [comment]
> Modern router is not supported from all joomla components?

I just want to be sure that is a problem of the modern router and not of the legacy router too :smile:

**Comment by ketihar** [comment]
Yes, i get this problem only when i check modern router on com_content.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14055">issues.joomla.org/tracker/joomla-cms/14055</a>.</sub>

**Comment by bertmert** [comment]
I don't know if this is related anyhow or if it's because of my settings.

While testing this issue: I don't see the articles with legacy router.

- Multilingual installation of current staging without sample data. All multilang features enabled while install. Just made these settings:

- Logged in as `Super User`.
- Created a content category: `Language`: All.
- Created a content article assigned to this category. `Language`: All.

- Created new menu (Site).
- Added Blog view for category above. `Language`: All.  
- - `Link Author`: Yes
- Created navigation module.  `Language`: All.

- Created contact. 
- - Assigned `Super User`.
- - `Show User Articles`: Show.

- Opened Blog view in FE. Clicked linked `Super User`.  
 
- No articles in contact view.
`$this->contact->articles` is empty

I would expect that I see the articles when all `Language` settings are `All`

**Comment by bertmert** [comment]
I deactivated all multilang extensions and deleted all menus that were assigned to a langugae.
Still the same: No articles in contact view of Super User.

**Comment by infograf768** [comment]
If you do not have a menu item for the contact, it is suggested to set Contact component Options to Show articles.

As you can see here https://github.com/joomla/joomla-cms/pull/14188 it works fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14055">issues.joomla.org/tracker/joomla-cms/14055</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
closed as known Issue #14919<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14055">issues.joomla.org/tracker/joomla-cms/14055</a>.</sub>
