### ISSUE TITLE
Administrator, Global Configuration, Site, Site Offline no is green yes is red

### ISSUE THREAD

**Issue by brianeg** [joomla/joomla-cms#14068]
### Steps to reproduce the issue
Administrator, Global Configuration, Site, Site Offline no is green yes is red

### Expected result
Administrator, Global Configuration, Site, Site Offline no is red yes is green

**Comment by Twincarb** [comment]
The logic is under normal circumstances a site is online which is what we all want, good is green in this case.

If there is a problem we take the site offline and it's red not normal.

I guess under UX all the reds on other options would be better being another colour which would allow red to be a fault condition or a non normal condition.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14068">issues.joomla.org/tracker/joomla-cms/14068</a>.</sub>

**Comment by bertmert** [comment]
If you want to test PR: https://github.com/joomla/joomla-cms/pull/14070

I think `Yes, it's offline` should be green and `No, it's not offline` should be red. But I don't think that it's worth to be discussed too long. "I don't care who wins."  ;-)

**Comment by franz-wohlkoenig** [comment]
Freen Yes, red No was behavior like 3.6.5. Don't know if this change in 3.7 was a Decision.

**Comment by rdeutz** [comment]
closing because we have a PR #14070
