### ISSUE TITLE
Backend Multilingual Associations: Warning on php 5.3   

### ISSUE THREAD

**Issue by csthomas** [joomla/joomla-cms#14063]
### Steps to reproduce the issue

Run joomla on php 5.3.
Go to joomla backend to Multilingual Associations

### Expected result

No warning.

### Actual result

Backend:
Multilingual Associations
Warning: ksort() expects parameter 2 to be long, string given in C:\Program Files (x86)\Ampps\www\joomla37\administrator\components\com_associations\models\fields\itemtype.php on line 57

Please see http://php.net/manual/en/function.sort.php
SORT_NATURAL flag was introduced in php 5.4

### Additional comments
The issue was original reported by @waader at https://github.com/joomla/joomla-cms/pull/13262#issuecomment-279690569

**Comment by zero-24** [comment]
Closing as we have a PR.
