### ISSUE TITLE
Error when switching languages on Microsoft Edge with greek aliases

### ISSUE THREAD

**Issue by mstrigkos** [joomla/joomla-cms#14062]
### Steps to reproduce the issue
This occurs on multilanguage sites when switching between languages that have unicode urls and only when we use Microsoft Edge browser.
The system is updated on version 3.6.5 
On "System - Language Filter" plugin the option "Remove URL Language Code" is enabled. If I disable this option the language switch is working as expected.

### Expected result
On language switch we expect to be directed a url like this:
/ενδοσκόπηση/λαπαροσκόπηση

### Actual result
But we get the url:
/ΞµΞ½Ξ΄ΞΏΟƒΞΊΟΟ€Ξ·ΟƒΞ·/Ξ»Ξ±Ο€Ξ±ΟΞΏΟƒΞΊΟΟ€Ξ·ΟƒΞ·
which results a 404 error.

**Comment by infograf768** [comment]
ah... microsoft...

**Comment by dgt41** [comment]
@mstrigkos make sure that your template index.php uses `<meta charset="UTF-8">` in the head section

**Comment by mstrigkos** [comment]
@dgt41 It is set to the proper charset but that;s irrelevant because meta tags affect the content of the website. This is not a content issue.
This issue is global, it does not affect only my websites.  If you check every joomla website on Microsoft Edge as described on "Steps to reproduce the issue" will reproduce it.

**Comment by franz-wohlkoenig** [comment]
@mstrigkos can you please confirm Issue exists on latest Staging?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14062">issues.joomla.org/tracker/joomla-cms/14062</a>.</sub>

**Comment by mstrigkos** [comment]
@franz-wohlkoenig It seems like this was (in the end) an Edge issue. It was solved after Microsoft updated the browser.

**Comment by franz-wohlkoenig** [comment]
thanks @mstrigkos Issue closed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14062">issues.joomla.org/tracker/joomla-cms/14062</a>.</sub>
