### ISSUE TITLE
joomla 3.7 beta 1 - Field type "List of images" problem

### ISSUE THREAD

**Issue by ketihar** [joomla/joomla-cms#14075]
### Steps to reproduce the issue
1.Create article
2.Create field type "List of images"
3.Select images Directory, for example banners
3.On frontend try to edit this article

### Expected result
On frontend you see the list of images

### Actual result
On frontend you get no list of images and if you try to edit article you get warning message

### System information (as much as possible)
7.0.10
Web Server	Apache/2.4.23 (Win64) PHP/7.0.10
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.7.0-beta1 Beta [ Amani ] 2-February-2017 18:53 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

### Additional comments
On field type "List of images" , on directory option if you select "Use from plugin" and try to edit the article i get some images i really don't know were they come from...
![screen shot 2017-02-14 at 23 06 49](https://issues.joomla.org/uploads/1/d58bcaccca899e0685843446d54453b9.jpeg)![screen shot 2017-02-14 at 23 06 59](https://issues.joomla.org/uploads/1/c194e75482b41824b925a2f3ec9a3737.jpg)

**Comment by joomdonation** [comment]
It causes by a bug in FolderList form field. I made PR https://github.com/joomla/joomla-cms/pull/14139 to solve it, please test that PR so that we can get the issue fixed
