### ISSUE TITLE
com_contact. Menu itemList All Contact Categories. Settings SHOW not green

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#14074]
### Steps to reproduce the issue
- Current staging.
- Create a contact.
- Go to tab `Display`.
- Switch some options to SHOW. All green now. OK.

![14-02-_2017_23-56-13](https://cloud.githubusercontent.com/assets/11038612/22953494/bb617846-f311-11e6-88b0-7c5f0b2975e2.jpg)

- Create a menu item of type `Contacts » List All Contact Categories`.
- Go to tab `Contact Display Options`.
- Switch some options to SHOW. All uncolored instead of green.

![14-02-_2017_23-58-57](https://cloud.githubusercontent.com/assets/11038612/22953551/f399a44a-f311-11e6-866d-8587d95e6063.jpg)

**Comment by franz-wohlkoenig** [comment]
Issue confirmed:
### System information
Joomla! 3.7.0-beta4 (nightly Build)
macOS Sierra, 10.12.4
Firefox 52 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
it is not just contacts - it is the same for content etc I am working on a PR for this

**Comment by ghost** [comment]
closed as having Pull Request #18223<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14074">issues.joomla.org/tracker/joomla-cms/14074</a>.</sub>
