### ISSUE TITLE
Joomla 3.7 beta 2 - Directory of media custom field not taken into account

### ISSUE THREAD

**Issue by obuisard** [joomla/joomla-cms#14076]
### Steps to reproduce the issue

Create a custom field of type 'media'.
Set the directory to /directorytest or /images/directorytest.
Edit a contact, access the new field and click on 'select' to open the media window.

### Expected result

The media modal popup should open in the directory set in the new media field.

### Actual result

The media modal popup opens at the root of the /images folder.

### System information (as much as possible)

Joomla 3.7 beta 2
PHP 5.6.25

**Comment by franz-wohlkoenig** [comment]
similar #13397 #13582 #13878 @Bakual @laoneo ?

**Comment by laoneo** [comment]
It's not related to the home directory setting. Looks like it is a general problem.

**Comment by rdeutz** [comment]
@zero-24 seems to me "fixed" with #13582, so we can close this?

**Comment by zero-24** [comment]
@rdeutz #13582 is about the home folder not the media field?

I have just done a similiar PR for the media field that i have done for the gallery field: https://github.com/joomla/joomla-cms/pull/14241
