### ISSUE TITLE
[4.0] Username-Field in backend not Autofocus

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14071]
### Steps to reproduce the issue
If open Backend in Joomla3 Cursor is in `Username`, in J4 User has to click in Field to get Focus.
### System information (as much as possible)
Joomla! 4.0-nightly builds
macOS Sierra, 10.12.3
Safari 10.0.3
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
Working in:
- Chrome
- Edge
- IE11

Not working in:
- Firefox

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/14081

**Comment by franz-wohlkoenig** [comment]
thanks @C-Lodder (can't test cause Patchtester wont fetch data).

**Comment by zero-24** [comment]
@franz-wohlkoenig did you enter your github account data to the pachtester?

**Comment by franz-wohlkoenig** [comment]
append token, works in j3

**Comment by mbabker** [comment]
If someone would give me a JavaScript migration guide maybe I can have a functional patch tester for the new 4.0 structure.  https://github.com/joomla-extensions/patchtester/issues/187#issuecomment-280010546
