### ISSUE TITLE
[4.0] Save User-Profile > "Call to undefined method JUser::getParameters()"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14072]
### Steps to reproduce the issue
`Save` or `Save & Close` a Profile, got
![bildschirmfoto 2017-02-14 um 22 24 08](https://cloud.githubusercontent.com/assets/8235763/22950243/4031374e-f305-11e6-954f-038041ed4bb6.JPG)

`Close` works without Failure.
### System information (as much as possible)
Joomla! 4.0-nightly builds
macOS Sierra, 10.12.3
Safari 10.0.3
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/14082
