### ISSUE TITLE
Joomla 3.7 "Home directory" option on Gallery field

### ISSUE THREAD

**Issue by ketihar** [joomla/joomla-cms#14085]
### Steps to reproduce the issue
1.Create article
2.Create field type "Gallery"
3.Try to let users from frontend upload files and create gallery only on their own directory

### Expected result
A "Home directory" option like the option exist on field type "Media" should be there to let the user choose if he want to restrict files upload only on user directory

### Actual result
There is no option "Home directory" to change if you want to point to user directory

### System information (as much as possible)
PHP Version	7.0.10
Web Server	Apache/2.4.23 (Win64) PHP/7.0.10
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.7.0-beta1 Beta [ Amani ] 2-February-2017 18:53 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

### Additional comments
It is very important to implement this feature on field type "Gallery" .This feature already exist on field type "Media".

**Comment by zero-24** [comment]
Currently there is the plan to remove that feature in the stable release of 3.7 because of security issues. But there is no decision yet.

**Comment by ketihar** [comment]
Well, the security part is important... But this feature has a lot of practical uses on site development and will give joomla a big step forward. Restrict file upload to specific user directory, using custom fields is very logical because this way you can create sites that actually different users can upload files without permission to see others files.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14085">issues.joomla.org/tracker/joomla-cms/14085</a>.</sub>

**Comment by zero-24** [comment]
i know the usecase.

The other issues / PRs are:
https://github.com/joomla/joomla-cms/pull/13893
https://github.com/joomla/joomla-cms/issues/13878
https://github.com/joomla/joomla-cms/pull/13582

**Comment by zero-24** [comment]
Closing as the feature is removed from the core now.

**Comment by davidglass** [comment]
> Well, the security part is important... But this feature has a lot of practical uses on site development and will give joomla a big step forward. Restrict file upload to specific user directory, using custom fields is very logical because this way you can create sites that actually different users can upload files without permission to see others files.
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/14085](https://issues.joomla.org/tracker/joomla-cms/14085).

It is unfortunate what you are doing with Joomla, supposedly to improve "security" But you know what? When it is well dead in its box it will be truly safe.

**Comment by zero-24** [comment]
Please checkout: https://github.com/Bakual/CustomFieldGallery that contains the gallery field that was removed from core.

**Comment by zero-24** [comment]
Feel free open new issues with feature requests and not comment on closed issue. Please be aware that we can not implement any potential use case in the core and we have a great list of extensions adding additional features. 

https://extensions.joomla.org/
https://extensions.joomla.org/tags/custom-fields/
