### ISSUE TITLE
new category can only be created from article editor if less than 10 categories exist

### ISSUE THREAD

**Issue by Supersonic112** [joomla/joomla-cms#14089]
### Steps to reproduce the issue
1. go to a current Joomla installation (I'm using 3.6.5) that has 10 or less article categories available (as it is the case with a fresh, empty installation) and log in as a user who may create new articles
2. click "Submit an Article" to open the article editor
3. open the drop down menu to choose a category for the article (in the protostar template, this menu can be found in the "publish" tab for example)

### Expected result
There should be some way to create a new category from this location. As soon as more than 10 categories exist, there will be a search bar in which the name for a category can be entered and if it does not exist yet, there will be a button that offers to create and add it automatically.

### Actual result
Since there are 10 or less categories, the aforementioned search bar will not be displayed and there is no (obvious?) way to create a new category except through the administrator interface.

### System information (as much as possible)
Ubuntu 16.04 LTS with the standard packages of Apache2, MySQL, PHP7, and a fresh installation of Joomla 3.6.5.

### Additional comments
The last message in https://groups.google.com/forum/#!topic/joomla-dev-general/zGdnnN6ROgs mentions that the search bar will appear as soon as more than 10 categories exist, which I could verify by trying it in a test installation.

Thus the problem can be circumvented by creating (up to) 11 dummy categories, but that may not be too obvious for people who don't find it out by accident.

**Comment by bertmert** [comment]
Pleas test PR https://github.com/joomla/joomla-cms/pull/14094
