### ISSUE TITLE
[4.0] `User: New`: Could not instantiate mail function.

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14091]
### Steps to reproduce the issue
After created a new User got Error: `Save failed with the following error: Could not instantiate mail function.`

Tried `Send Test Mail` in `Global Configuration, Tab Server` also fails. If necessary, i open a new Issue

### System information (as much as possible)
Joomla! 4.0-nightly builds
macOS Sierra, 10.12.3
Safari 10.0.3
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by PhilETaylor** [comment]
Do you have a mail server installed on your mac? 

What Mail Settings are you using? 

what happens on your MAMP if you try a standard mail test.php ?

`<? mail('me@example.com','test','test'); `

**Comment by franz-wohlkoenig** [comment]
@PhilETaylor thanks for hint, i have no Mail-Server local.
