### ISSUE TITLE
com_content/view/article gets article tags without ordering

### ISSUE THREAD

**Issue by peterpeter** [joomla/joomla-cms#14098]
### Steps to reproduce the issue
Create some tags - not in a alphabetical order - create an article and assign these tags. Let the article view show these tags. On Forntpage, on this article the tags seemed ordered by id. 

Now go to com_tags configuration, tab 'tagged items', set the order option to 'Title'. Go to the frontend again, and reload the article.

### Expected result
The assigned tags should displayed alpha-ordered by the title-colummn.

### Actual result
Nothing has changed, tags are still id-orderd.

### Additional comments
The article view (single article) gets the article tags by libraries\joomla\helper\JHelperTags::getItemTags - wich gets and returns the tags by querying the tags-table directly, without a order clause. PHPStorm 'tells' me, that this method is used by com_contact, com_newsfeeds too.

The correct way getting tags should be through a tags-model instead of a helper class, I guess. No?

**Comment by franz-wohlkoenig** [comment]
set "confirmed" at Issue Tracker.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14098">issues.joomla.org/tracker/joomla-cms/14098</a>.</sub>

**Comment by brianteeman** [comment]
It is the order of the items that have been tagged NOT the order of the tags

**Comment by franz-wohlkoenig** [comment]
thanks @brianteeman so the Order of Tag in an Article can't changed?

**Comment by peterpeter** [comment]
Ah, I see, my fault. Because![screen shot 2017-04-05 at 09 54 35](https://issues.joomla.org/uploads/1/73311b5be6607059f090b20fe29a68d6.jpg) I'm managing this site with tags in german language, switched to english just to post the right labels, and overlocked the meaning. Because the german translation is a little misleading, in my opinion (Screenshot).

But a order parameter for the tags would be a useful feature, as in my case I use the tags as available languages of libraries, e.g.
http://interbiblio.ch/en/member-libraries/29-englisch/mitgliedsbibliotheken/151-monthey-a-tous-livres

But I guess that's stuff for another issue/request, so this one can be closed, I guess.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14098">issues.joomla.org/tracker/joomla-cms/14098</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
closed as Expected Behaviour. @peterpeter can you please open a Issue for ordering Tags?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14098">issues.joomla.org/tracker/joomla-cms/14098</a>.</sub>
