### ISSUE TITLE
[4.0] `User: New`: Automatic contact creation failed.

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14090]
### Steps to reproduce the issue
After created a new User got Error: `Automatic contact creation failed. Please contact a site administrator.`

Plugin `User - Contact Creator` is enabled.

### System information (as much as possible)
Joomla! 4.0-nightly builds
macOS Sierra, 10.12.3
Safari 10.0.3
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by wilsonge** [comment]
Error being thrown by `ContactTableContact` is `Field 'params' doesn't have a default value`
