### ISSUE TITLE
[4.0] Backend > Multilingual-Status: 1055 - Error

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14095]
### Steps to reproduce the issue
Click in Backend on `Multilingual-Status` (Position Status) > get:
![bildschirmfoto 2017-02-15 um 18 32 27](https://cloud.githubusercontent.com/assets/8235763/22986950/7e7ee368-f3ad-11e6-84ac-0cf44084559a.JPG)
### System information (as much as possible)
Joomla! 4.0-nightly builds
macOS Sierra, 10.12.3
Safari 10.0.3
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by franz-wohlkoenig** [comment]
should this Issue be closed as expected behavior cause there are no Lang.-Packs now?

**Comment by joomdonation** [comment]
Please leave it open as it looks like an SQL error (not related to lang-packs)

**Comment by joomdonation** [comment]
@franz-wohlkoenig I made PR https://github.com/joomla/joomla-cms/pull/15051 which should fix the issue, so you can close this issue now

**Comment by infograf768** [comment]
Folks, how do you want we test anyhting multilang related when it is still impossible to install a language pack?
I am not talking about using the EXtensions=>Install Languages as it iss normal to not be able to install from there as the script does not take into account version4, but of simply installing a 3.7 pack from Installation=>Install.

**Comment by joomdonation** [comment]
I just enable Language filter plugin, and the module, then click on the link, see the error (the error can be seen even with just one language installed)

If it is not valid, then I will close that PR
