### ISSUE TITLE
User Custom Fields are not being saved properly

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#14092]
### Steps to reproduce the issue
1. Create user custom field, can be a simple text file
2. Login to backend of your site using a super admin account, edit your account, try to enter value for the custom field you created

### Expected result
Custom field data being saved properly

### Actual result
The field data look like saved properly but it is not. If you try to view your profile from frontend, you won't see the data you entered

### System information (as much as possible)
Joomla 3.7, updated from stagging today

### Additional comments

While trying to look at the code, I see that while saving user data, after this line https://github.com/joomla/joomla-cms/blob/staging/plugins/system/fields/fields.php#L111 , $fieldData is not an array (as the plugin code expect), it is actually a json string (maybe it is loaded directly from params fields in #__users table)

@Bakual , @laoneo Please check as you two probably understand custom fields system better than most of us here

**Comment by Bakual** [comment]
Check this one: https://github.com/joomla/joomla-cms/pull/13956

**Comment by Bakual** [comment]
Closing as there is a PR already
