### ISSUE TITLE
downgrade problem

### ISSUE THREAD

**Issue by oba4me** [joomla/joomla-cms#14100]
### Steps to reproduce the issue
I updated to 3.5  and discovered my site went off so i decided to roll back but discovered that my serve immediately on update override the back to new back installation. I used information here: https://docs.joomla.org/How_to_restore_a_Joomla_2.5_site_if_you_accidentally_migrate_to_Joomla_3.x.x to guide me to roll back but on completion have this error with the site : Fatal error: Call to undefined function utf8_strpos() in /home/energyplatformni/public_html/libraries/joomla/string/string.php on line 171. i really dont no what to do hadd sleepless night. The administrator loads but when i click on configuration to set error message or some other link i get this message too: Fatal error: Call to undefined function utf8_strlen() in /home/energyplatformni/public_html/libraries/phputf8/ucfirst.php on line 21
Please help how do i go about it

### Expected result
my site backup to the old 2.5 but i get this error: Fatal error: Call to undefined function utf8_strpos() in /home/energyplatformni/public_html/libraries/joomla/string/string.php on line 171

### Actual result
Fatal error: Call to undefined function utf8_strpos() in /home/energyplatformni/public_html/libraries/joomla/string/string.php on line 171

### System information (as much as possible)
Linux sens.websitewelcome.com 3.12.65-188.ELK6.x86_64 #1 SMP Thu Oct 20 23:27:48 CDT 2016 x86_64
Database Version 	5.5.51-38.2
Database Collation 	utf8_general_ci
PHP Version 	5.4.45
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 2.5.28 Stable [ Ember ] 10-December-2014 15:00 GMT
Joomla! Platform Version 	Joomla Platform 11.4.0 Stable [ Brian Kernighan ] 03-Jan-2012 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by infograf768** [comment]
Are you sure you have all files and folders in libraries/phputf8/  ?

Best way is to delete that folder and upload a clean one from a 2.5.28 pack.



As this is not a Joomla bug, It is suggested to create a Topic in the forums.

Closing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14100">issues.joomla.org/tracker/joomla-cms/14100</a>.</sub>
