### ISSUE TITLE
[4.0] Template instalation

### ISSUE THREAD

**Issue by cr2a-graphique** [joomla/joomla-cms#14105]
### Steps to reproduce the issue
Joomla4 installed, create a basic template, try to install it by the folder tmp

### Expected result
template correctly installed

### Actual result
error : 
Extension Install: Field 'system_data' doesn't have a default value

### System information (as much as possible)
Folder are writable, configuration.php correctly completed (for temp and log)

### Additional comments
How to add default value to Field 'system_data'.

**Comment by tonypartridge** [comment]
Issues not replicable current 4.0-dev branch. 

Copied protostar changed naming to: test

Install via tmp folder. Install success and can access and edit the template. 

@wilsonge please can we close?

**Comment by wilsonge** [comment]
This was fixed by https://github.com/joomla/joomla-cms/pull/14750

**Comment by cr2a-graphique** [comment]
thanks, you can bypass when duplicate the BDD line and create a same name template in template folder.
