### ISSUE TITLE
Overly verbose and confusing text on Super Users Account Details in install

### ISSUE THREAD

**Issue by efduggan** [joomla/joomla-cms#14106]
### Steps to reproduce the issue

Run the 3.7 beta 3 installer - the first step shows on the right  dialog and directions on setting up a "Super User Administrator" which is confusing (what's a Super User? and why doe the text box labels say Administrator?)

Also there is way too much verbiage of little or no use in this step. The more text on the screen means the less read it will be, the more confusion introduced and the more translation needs to be done.

![3 7 beta 3 installer initial screen](https://cloud.githubusercontent.com/assets/25716272/23033333/83a0d048-f42c-11e6-94c1-2666d6d83fa3.png)
### Expected result

I would expect that the account be clear and concise and only contain the necessary words. I've created a sample mock-up  which is clear concise but not cryptic.

![updated config step1](https://cloud.githubusercontent.com/assets/25716272/23033563/64606346-f42d-11e6-97dd-b4f185510470.png)

### Actual result

see above

### System information (as much as possible)

N/A

### Additional comments

I do realize that this is the first step of the process and the first screen that new users see in their Joomla! journey, but what is there is confusing and verbose.

**Comment by franz-wohlkoenig** [comment]
Can't confirm in most Parts:
![bildschirmfoto 2017-02-18 um 07 12 58](https://cloud.githubusercontent.com/assets/8235763/23090911/caead72c-f5a9-11e6-9d83-fdc65e688e3e.JPG)
About the Text below Fields Maintainers should decide. I'm with you, less is more, the Text have to be clear.

**Comment by efduggan** [comment]
That's a good start - thanks!

**Comment by franz-wohlkoenig** [comment]
closed as issue is solved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14106">issues.joomla.org/tracker/joomla-cms/14106</a>.</sub>
