### ISSUE TITLE
Some unused new strings in the admin menu manager?

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#14118]
### Steps to reproduce the issue
```
+COM_MENUS_ITEM_FIELD_CLIENT_ID_DESC="Choose the client application menu"
+COM_MENUS_ITEM_FIELD_CLIENT_ID_LABEL="Client"
```
from here: https://github.com/joomla/joomla-cms/commit/4e156fa0ad46cfcbc089311a66fe8b99d21b49eb#diff-466f186f3ec7a5fe2a6e5e292a112b86R84

### Expected result

Not used?

### Actual result

Used or removed so there is no need to translate something that is not used.

### Additional information

For me it looks like a dublicate of:
```
+COM_MENUS_MENU_CLIENT_ID_LABEL="Client"
 +COM_MENUS_MENU_CLIENT_ID_DESC="Choose the client for which this menutype will be used."
```

wich are used btw. @izharaazmi can you help here?

**Comment by infograf768** [comment]
These 2 strings can be safely deleted indeed.

**Comment by zero-24** [comment]
done with #12140
