### ISSUE TITLE
Backend article list is not optimized for viewports >= 768px -

### ISSUE THREAD

**Issue by dneukirchen** [joomla/joomla-cms#14114]
### Steps to reproduce the issue
Open the article list in the backend and Resize your browser window to 768px width.

### Expected result
A responsive, usable article list and toolbar.
Unimportant columns should be hidden.
The toolbar collapse breakpoint should be increased.

### Actual result

The article list is not responsive and not very user friendly.

<img width="763" alt="bildschirmfoto 2017-02-17 um 12 14 58" src="https://cloud.githubusercontent.com/assets/1134007/23063565/8bd44102-f50b-11e6-9aeb-64471d350175.png">

### System information (as much as possible)
joomla 3.7 beta 1, latest chrome, mac

**Comment by zero-24** [comment]
@dneukirchen do you know if that is catched by hidden-tablet css class?

**Comment by dneukirchen** [comment]
Yes. it will be catched by .hidden-tablet.

**Comment by dneukirchen** [comment]
The solution should also be applied to the featured article list, where we have the same issue.

**Comment by Bakual** [comment]
The toolbar collapses on small viewports. SO I guess we can just adjust the breakpoint for that behavior?
![collapsed](https://cloud.githubusercontent.com/assets/1018684/23065143/4df1c630-f514-11e6-8bd2-b8c8ac132381.PNG)
![toolbar](https://cloud.githubusercontent.com/assets/1018684/23065147/4fdb817a-f514-11e6-8ae5-d7508eb80a5e.PNG)

**Comment by dneukirchen** [comment]
@Bakual that would be the quick (and dirty) solution, but its not optimal, because then you have the toolbar collapse button with 100% width on viewports >768px.

I think a nicer solution for the responsive toolbar is to create a "more" dropdown btn-group and wrap the not so often used actions in a dropdown. I personally only use the create and delete buttons most of the time. The rest of the actions (or at least most of them) can be presented in a dropdown. This would increase usablity and responsiveness and results in a clearer/easier to understand overall user interface.

Possible related PR for responsive tables: https://github.com/joomla/joomla-cms/pull/13835

**Comment by Bakual** [comment]
The breakpoint for the toolbar seems not to be the same as for "hidden-phone" as they trigger ealier. I don't know where it is specified but it seems to be independant.

**Comment by infograf768** [comment]
We at least already corrected the Title column in 3.7. (this to reply to the original screenshot)
See https://github.com/joomla/joomla-cms/pull/13785

**Comment by franz-wohlkoenig** [comment]
closed PR #13785 solved issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14114">issues.joomla.org/tracker/joomla-cms/14114</a>.</sub>
