### ISSUE TITLE
[RFC] Module `User Status`: Default `Yes` on `Show View Administrator`

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14129]
### Steps to reproduce the issue
Open Module `User Status` in Backend, `Show View Administrator` is set by Default to `No`.

Should be by Default:
![bildschirmfoto 2017-02-18 um 08 34 05](https://cloud.githubusercontent.com/assets/8235763/23091385/16f7ec76-f5b5-11e6-9fb3-8ee090986bbe.JPG)

### System information (as much as possible)
Joomla! 3.7.0-beta3
macOS Sierra, 10.12.3
Firefox 51.0.1
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35
### Additional comments
`Show View Administrator` helps working in Backend.

**Comment by Bakual** [comment]
That is disabled by design because the link isn't that useful for most people.
See https://github.com/joomla/joomla-cms/pull/7195

**Comment by infograf768** [comment]
I agree this would be real handy.
Changes have to be made in the sqls and also in the module field default.

**Comment by Bakual** [comment]
As I wrote already in the initial PR, I think that link is completely useless (as well as the older "View Site") since there are already links to the same place in the header. The Joomla icon on the top left is a link to the admin and on the top right you have one to the site. Ctrl-Clicking (on Windows) the icon brings you a new tab with the admin.  Those links technically also don't belong to a status module. But that is my personal opinion.

Imho it's fine to have the option disabled by default as it is currently.

**Comment by franz-wohlkoenig** [comment]
You're right, @Bakual ... if it works.

But one difference: Open a Backend-Link using cmd (Mac) opens new Tab, but sometimes loads the new Tab-Value also in old Tab. 

#### Example: 

1. Open Backend Tab `Control Panel`
2. cmd-Click on `Users > Manage`

what happens:

1. new Tab showing `Users` open
2. Tab `Control Panel` loads also `Users`.

This happens in some Menues, in most not.
### Test on
Joomla! 3.7.0-beta3
macOS Sierra, 10.12.3
Firefox 51.0.1
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by Bakual** [comment]
I'm not talking about Ctrl-Clicking the menus. I'm talking about the Joomla Icon which is a link to administrator homepage (usually the control panel). It's the exact same link as with the "View Administrator" link, only without a target specified. So Ctrl-Clicking (or Cmd-Clicking) it will do the exact same thing.

**Comment by Bakual** [comment]
This one:
![icon](https://cloud.githubusercontent.com/assets/1018684/23093428/628089e0-f5e3-11e6-90e6-b22ae2dfc017.PNG)

**Comment by franz-wohlkoenig** [comment]
got it. Thanks.
