### ISSUE TITLE
[RFC] Deprecate "dynamic" JPATH_CACHE constant

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#14135]
Presently, the `JPATH_CACHE` path constant is a "dynamic" constant based on the running application; it is always defined as `JPATH_BASE . '/cache` resulting in separate filesystem caches for the frontend, backend, and installation applications.  This is the only cache store to create separate cache storage locations based on the active application; using any other handler stores all data in a single store regardless of application.  Additionally, this behavior is inconsistent with the `$cache_path` configuration value that is now exposed in 3.7 which uses a single path for all filesystem related caching if set.

I propose that as of 4.0, `JPATH_CACHE` has a constant value of `JPATH_ADMINISTRATOR . '/cache` resulting in the filesystem cache using a single storage location for all data, removing the need for some conditional behaviors, and in general making this configuration more consistent with other adapters.

**Comment by yvesh** [comment]
+1 for j4

**Comment by nibra** [comment]
All in to reduce the number of 'dynamic' constants (which should be environment variables instead, BTW)..

**Comment by mbabker** [comment]
#14262 is the PR for this.
