### ISSUE TITLE
[RFC ] Less Redundance in `User Status`

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14130]
### Steps to reproduce the issue
Open Administrator-Module `User Status`, Tab `Module` and view Redundances (`Show`, `View`):
![bildschirmfoto 2017-02-18 um 11 31 39](https://cloud.githubusercontent.com/assets/8235763/23092597/7852e19c-f5ce-11e6-9447-f3d194881993.JPG)

A simple Structure (Layout of Font and buttons stay):

Show View | -
------------ | -------------
Site | [Yes] [No]
Administrator | [Yes] [No]

Show Logged-in | -
------------ | -------------
Users | [Yes] [No]
Backend-Users | [Yes] [No]

Show Messages | [Yes] [No]
### System information (as much as possible)
Joomla! 3.7.0-beta3
macOS Sierra, 10.12.3
Firefox 51.0.1
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by franz-wohlkoenig** [comment]
Update after merged #14570:
![00 module user status](https://cloud.githubusercontent.com/assets/8235763/23889116/b24fcffc-088b-11e7-91b4-d1aa3887059e.JPG)

**Comment by dgt41** [comment]
@franz-wohlkoenig make a PR

**Comment by franz-wohlkoenig** [comment]
@dgt41 I have no Skills and Knowledge in php, css, ... i can test and report Issues.
