### ISSUE TITLE
[4.0] Notice in authentication.php

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#14147]
[20-Feb-2017 09:26:18 Europe/Paris] PHP Notice:  Only variables should be passed by reference in ROOT/libraries/joomla/authentication/authentication.php on line 150

**Comment by C-Lodder** [comment]
Am I right in assuming this:

```
if (class_exists($className))
{
	$plugin = new $className($this->getDispatcher(), (array) $plugin);
}
```

should be this:

if (class_exists($className))
{
        $dispatcher = $this->getDispatcher();
	$plugin = new $className($dispatcher, (array) $plugin);
}

??

**Comment by joomdonation** [comment]
@C-Lodder Your proposed fixed the issue. Please go ahead to make a PR for it. I think moving $dispatcher = $this->getDispatcher(); outside the foreach loop would be better

**Comment by C-Lodder** [comment]
@joomdonation PR: https://github.com/joomla/joomla-cms/pull/14149

**Comment by wilsonge** [comment]
Closed as we have a PR
