### ISSUE TITLE
[com_fields] Default params are being override

### ISSUE THREAD

**Issue by n3t** [joomla/joomla-cms#14146]
### Steps to reproduce the issue
1. Create new field for users, give it name Test, alias language, type text 
2. Open user form, navigate to Basic settings page

### Expected result
There should be 'Frontend language' field with selection of user language

### Actual result
There is plain text 'Test' field

### Additional comments
com_fields is using params for its values, and alias of the field as field name, so the name in html form is jform[params][field_alias], this overrides original field from component itself, causing this issue.

Same situation is for com_categories fields implementation (image field for example), only articles are unaffected, as there is no original params.

**Comment by Bakual** [comment]
See https://github.com/joomla/joomla-cms/pull/13353 for the fix.
Closing this as there is a PR which solves this.
