### ISSUE TITLE
[com_fields] unused language strings ?

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14148]
Hi there,
Found these language strings but i can´t find an usage anywhere.
Can anyone confirm?

en-GB.com_content.ini
; Fields overrides
COM_CONTENT_ARTICLE_CATEGORIES_TITLE="Articles: Field Groups"
COM_CONTENT_ARTICLE_CATEGORY_ADD_TITLE="Articles: New Field Group"
COM_CONTENT_ARTICLE_CATEGORY_EDIT_TITLE="Articles: Edit Field Group"

en-GB.com_contact.ini
; Fields overrides
COM_CONTACT_CONTACT_CATEGORIES_TITLE="Contacts: Field Groups"
COM_CONTACT_CONTACT_CATEGORY_ADD_TITLE="Contacts: New Field Group"
COM_CONTACT_CONTACT_CATEGORY_EDIT_TITLE="Contacts: Edit Field Group"

en-GB.com_users.ini
; Fields overrides
COM_USERS_USER_CATEGORIES_TITLE="Users: Field Groups"
COM_USERS_USER_CATEGORY_ADD_TITLE="Users: New Field Group"
COM_USERS_USER_CATEGORY_EDIT_TITLE="Users: Edit Field Group"

thanks!

**Comment by infograf768** [comment]
Indeed, it looks like they were replaced by

COM_FIELDS_VIEW_GROUPS_TITLE="%s: Field Groups"
COM_FIELDS_VIEW_GROUP_ADD_TITLE="%s: New Field Group"
COM_FIELDS_VIEW_GROUP_EDIT_TITLE="%s: Edit Field Group"

Any volunteer to delete the obsolete strings (and the comment above) ?

**Comment by infograf768** [comment]
Closed as we have PRs.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14148">issues.joomla.org/tracker/joomla-cms/14148</a>.</sub>
