### ISSUE TITLE
Error updating beta2 -> beta 3

### ISSUE THREAD

**Issue by zebrahosting** [joomla/joomla-cms#14168]
### Steps to reproduce the issue

Upgrade 3.7 beta 2 with the Joomla updater to beta 3

### Actual result
error:
Component Install: The alias multilingual-associations is already being used by com_associations menu item in the menu (remember it may be a trashed item).

### System information (as much as possible)

We have the new router and some fields active while updating
Multi language setup with Dutch and English and a a few articles, menu's associated.

**Comment by twdjo** [comment]
I have the same issue except that it's a Warning instead of an Error.

**Comment by zero-24** [comment]
We are working on that here: https://github.com/joomla/joomla-cms/issues/14190
