### ISSUE TITLE
 Admin Menu Manager: Problem with permissions

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#14161]
### Steps to reproduce the issue
1. Create two admin menus. One that uses the system preset and one that contains only one (I called it Second Admi Menu ) menu item for creating an article.

![modules administrator test administration 1](https://cloud.githubusercontent.com/assets/9974686/23156308/a82d5952-f816-11e6-8deb-e2e52d7a9e21.png)

2. Set the permission so, that an administrator can only access the "Second Admin Menu" with the one menu item for creating an article.

![modules administrator menu test administration 1](https://cloud.githubusercontent.com/assets/9974686/23156307/a82c8a68-f816-11e6-8aea-7e5ef1e212fc.png)
![modules administrator menu test administration](https://cloud.githubusercontent.com/assets/9974686/23156309/a82d7fea-f816-11e6-9a40-167d387b306b.png)

### Expected result
A super admin can see both menus. A normal administrator can only access the admin menu with the name "Second Admin Menu" and the one menu item for creating an article

### Actual result
The super admin **and the administrator** can access both admin menus. And they both see the warning: "The active administrator menu does not contain links to Module Manager and Menu Manager. Click to turn on the menu recovery mode."
![control panel test administration 1](https://cloud.githubusercontent.com/assets/9974686/23156634/19983a8e-f818-11e6-9c9f-781e7e1f9975.png)

**Comment by infograf768** [comment]
Looks like you are confusing permissions and Access levels for these menu modules.

On all cases: each custom admin menu should have at least 3 menu items (menu items manager, modules manager, and component). If one does not have these, the Warning will display. Their display will depend on the permissions for each component concerned and Global permissions.

The menu modules access is another story. It is a bit complex as Joomla per default is setting all backend modules (except Login) to `Special` access.

That `Special` access is also used in frontend.
Therefore one has to carefully craft the access levels in order for example to not display all custom admin menus for Manager or Administrator, etc.

**Comment by astridx** [comment]
@infograf768 Yes you are right. I want to use the admin menu for restrincting permissons. But that is not the intention of this. Thank you
