### ISSUE TITLE
[4.0] Summary view in installation looks a bit ugly

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#14179]
### Steps to reproduce the issue
Install Joomla from the 4.0-dev branch

### Expected result
The alerts should span the whole with

### Actual result
![summary](https://cloud.githubusercontent.com/assets/1018684/23204557/55977516-f8e7-11e6-817e-b9b994acebe7.PNG)

### Additional comments
I think the alert divs need a "width: 100%" here, but I don't know the new Bootstrap version stuff yet, so there may be just a missing class

**Comment by C-Lodder** [comment]
Same comment here applies https://github.com/joomla/joomla-cms/issues/14178#issuecomment-281618741

**Comment by mbabker** [comment]
Isn't there still a plan to update the install app's template anyway?  This and the frontend are still 3.x based I thought.

**Comment by C-Lodder** [comment]
@mbabker - In J4, yes. The installation template and steps process is being worked on. Frontend template I haven't started on yet.

**Comment by wilsonge** [comment]
I'm going to close the installation issues for now until the new installation template comes along.
