### ISSUE TITLE
com_banners: Tracks Clicks when Click tracking is Disabled

### ISSUE THREAD

**Issue by TrueLine** [joomla/joomla-cms#14173]
### Steps to reproduce the issue
I have the Global Config for the Banners Component set to disable for both clicks and impressions. Its also set within each banner. 

### Expected result
Banners should not track clicks or impressions  

### Actual result
Banners are tracking things 

### System information (as much as possible)
Joomla 3.6.4

Platform Type:Debian
MySQL Version:5.6.32
PHP Version:5.6.6

### Additional comments
I updated the system from 3.3.x to 3.6.4, any suggestions would be welcomed.

**Comment by TrueLine** [comment]
In addition: On the front page, the URL on the banner is  "*mydomain.com/component/banners/click/21" which goes to a blank page and then to the URL specified. I just want the direct link with out opening a new page? 

Anyone know how I can accomplish this?

**Comment by franz-wohlkoenig** [comment]
Can confirm both Issues on 3.6.5

**Comment by franz-wohlkoenig** [comment]
Can confirm both Issues on 3.7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14173">issues.joomla.org/tracker/joomla-cms/14173</a>.</sub>

**Comment by eshiol** [comment]
The component always increases the fields impmade and clicks in the table #__banners
The component populates the table #__banner_tracks using track_type=1 only when Track impressions is enabled
The component populates the table #__banner_tracks using track_type=2 only when Track clicks is enabled

Are you sure this is not the right behavior? 
Why would you want to disable impressions and clicks counting?

**Comment by Quy** [comment]
This is the expected behavior as stated by eshiol.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14173">issues.joomla.org/tracker/joomla-cms/14173</a>.</sub>
