### ISSUE TITLE
[4.0] Unable to install language pack

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#14170]
### Steps to reproduce the issue
Try to install this pack through Extensions=>Install=>Upload Package file
https://github.com/infograf768/fr-FR-3.x/releases/download/v3.7.0.1.beta2/fr-FR_joomla_lang_full_3.7.0v1.zip

### Expected result
Installation goes OK

### Actual result

Too few arguments to function JInstallerAdapterPackage::onExtensionAfterInstall(), 1 passed and exactly 2 expected

**Comment by wilsonge** [comment]
This fixes the too few arguments error: https://github.com/joomla/joomla-cms/commit/8744332ac2c93a66fc518aec36ee2c1e21a02cec. But installing that package is giving another error which I'm still working on fixing.

**Comment by infograf768** [comment]
Indeed, we now have
`Call to undefined method JInstallerAdapterLanguage::set()`

Note: Discover is also broken (for languages at least).

**Comment by infograf768** [comment]
@wilsonge
Tested changing from
```
		if (!file_exists($this->parent->getPath('extension_site')))
		{
			if (!$created = JFolder::create($this->parent->getPath('extension_site')))
			{
				$this->parent
					->abort(
					JText::sprintf(
						'JLIB_INSTALLER_ABORT',
						JText::sprintf('JLIB_INSTALLER_ERROR_CREATE_FOLDER_FAILED', $this->parent->getPath('extension_site'))
					)
				);

				return false;
			}
		}
```
 to
```
		if (!file_exists($this->parent->getPath('extension_site')))
		{
			if (!$created = JFolder::create($this->parent->getPath('extension_site')))
			{
				throw new RuntimeException(
					JText::sprintf(
						'JLIB_INSTALLER_ABORT',
						JText::sprintf('JLIB_INSTALLER_ERROR_CREATE_FOLDER_FAILED', $this->parent->getPath('extension_site'))
					)
				);

				return false;
			}
		}
```

And I do get this:
![screen shot 2017-02-22 at 09 25 22 1](https://cloud.githubusercontent.com/assets/869724/23203108/53974f76-f8e1-11e6-8ce9-a701af50a1bb.png)

**Comment by infograf768** [comment]
OK, I get it to install by adding the missing 
```
$row->set('custom_data', '');
$row->set('system_data', '');
``` 
Still remaining the asset_id for the content language which could not be created.

**Comment by infograf768** [comment]
Uninstalling a language (installed after modifying the adapter as posted above) gives

`Too few arguments to function PlgExtensionJoomla::onExtensionAfterUninstall(), 2 passed in /Applications/MAMP/htdocs/joomla_400/libraries/cms/plugin/plugin.php on line 322 and exactly 3 expected`

**Comment by wilsonge** [comment]
Hmm I don't see why `onExtensionAfterUninstall` would only be getting two params https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/cms/installer/installer.php#L754 This passes 3 in. I'll look into this in a little bit!

**Comment by infograf768** [comment]
It looks anyhow (I let you make the patch with what I already proposed above) that the entire installer needs love and care: Install, Uninstall, Update, Discover. All fails on one type of extension or the other.

**Comment by wilsonge** [comment]
@mbabker can you just check JM's proposed patch for the set method. If abort is failing seems like there might be a deeper problem (that throwing the exception just covers up)

There probably will be. There's been some tidying up done of the installer code AND we rebuilt the plugin system. There's going to be lots of bugs. Just keep reporting them and I'll keep fixing them :)

**Comment by wilsonge** [comment]
I've fixed the plugin event. @csthomas can you look into the database queries here. there's a few places that is affected by `custom_data` and `system_data` (such as in https://github.com/joomla/joomla-cms/issues/14409)

**Comment by C-Lodder** [comment]
@infograf768 - Just tested installing the language pack from the link you provided and it seems to be working now.

Ok to close?

**Comment by infograf768** [comment]
They install OK indeed. Will test again uninstall, etc.

**Comment by infograf768** [comment]
They uninstall OK here too.

**Comment by C-Lodder** [comment]
This may need to be re-opened. You can install the zip via the extension manager, but can't via the langage manager.

> Unable to find install package

**Comment by infograf768** [comment]
You mean through the Install Languages Manager.
That is normal.
The update site credentials are aimed at 3.x maxi and will not present any packs for a 4.x version.
We will have to create a new xml for that as well as a new repository for 4.x packs.

**Comment by C-Lodder** [comment]
Ah fair enough. Thanks for clarifying
