### ISSUE TITLE
[4.0] Buttons misplaced in installation

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#14178]
### Steps to reproduce the issue
Install Joomla from the 4.0-dev branch

### Expected result
Buttons aligned right to eachother on same line

### Actual result
buttons aligned below eachother
![offline](https://cloud.githubusercontent.com/assets/1018684/23204394/bb100238-f8e6-11e6-90d2-dc3de7634511.PNG)
![database](https://cloud.githubusercontent.com/assets/1018684/23204401/bf4e3ce8-f8e6-11e6-8caa-9a16936759f3.PNG)
Same for other buttons in the next steps.

### System information (as much as possible)
Not relevant.

**Comment by C-Lodder** [comment]
Not sure why those are radio buttons, should be switchers. Either way, they'll be fixed when we do the redesign and revamp of the installation

**Comment by Bakual** [comment]
> Not sure why those are radio buttons, should be switchers. 

I don't know what a "switcher" is. Probably because there are no switchers in HTML and Bootstrap2.3 :smile: 
Radios are the proper HTML element for such a selection and we (or Bootstrap 2.3) styled them as buttons.

**Comment by C-Lodder** [comment]
Switcher: https://gyazo.com/dabee6bfc0f063aa0449cc5b609a5048

**Comment by Bakual** [comment]
those are radios as well, right? Just styled differently. That style will work fine for yes/no type answers, but imho not for a backup/delete one. And I'm not so sure if we should try to mimic OS settings (those look like Apple, right?) in a web app. But I don't care much as long as it doesn't look broken like the current stuff :smile:

**Comment by C-Lodder** [comment]
No, they're switchers.....different to radio buttons :)

They're only used for fields with 2 options. Anything above that, I've moved to a list dropdown or in some cases stuck with the radio toggle.

They did look more like iOS before, but having debated with Brian for a good coupe of weeks, we went with a more square approach :)

**Comment by Bakual** [comment]
> No, they're switchers.....different to radio buttons 

I just checked in component options. They're just different styled radios :smile:

**Comment by wilsonge** [comment]
Anything that isn't the backend is going to have dodgy styling at this point. Installation has a rudimentary bs4 conversion but there's a full redesign in the works

**Comment by C-Lodder** [comment]
@Bakual ah you mean the actual form field

**Comment by Bakual** [comment]
>  Installation has a rudimentary bs4 conversion but there's a full redesign in the works

That's fine. I just saw that it already uses the BS4 stuff and has some changes and most of it actually works fine.

> ah you mean the actual form field

Yep :smile:

**Comment by dgt41** [comment]
> those are radios as well
This is a good example where custom elements could be used and transform the radios (if there are only 2 and have the appropriate labels) to the switcher style. By the way using custom elements we could transform all the radios to something more interesting (e.g. if less than 5, make  then grouped buttons, which is a recommended pattern, or lay them out as multiple columns or anything else)

**Comment by Bakual** [comment]
I get your enthusiasm about custom elements as they sound promising, but honestly when I look at http://caniuse.com/#search=Custom%20Elements, it is basically only working on Chrome and Opera. The rest would need some polyfill or fallback scenario. Imho as long as the other major browsers (Edge, IE, Firefox) don't support it yet, there is no point using it if the same can be done with CSS.

**Comment by mbabker** [comment]
If you constantly only write for the lowest supported engine without even looking at polyfills, you constantly are missing out on ways to adapt newer technologies.  Joomla already polyfills a good chunk of functionality both server side and client side (how many PHP 5.5+ functions are used in core even though there's a 5.3.10 minimum?).  You have to play a balancing act between the new technology thing and how much added maintenance comes from it.

**Comment by dgt41** [comment]
Next version of safari and ff is supporting them and edge is coming later this year, so (with a possible release date for J4 next year) we should be ok...

**Comment by Bakual** [comment]
> You have to play a balancing act between the new technology thing and how much added maintenance comes from it.

That's why I wrote "**if the same can be done with CSS.**", which is the case here.

**Comment by C-Lodder** [comment]
@Bakual - I've already tested Dimitris's first prototype custom element thoroughly on FF, Chrome, Edge, Opera and IE11. Everything was working perfectly fine ;)

**Comment by wilsonge** [comment]
I'm going to close the installation issues for now until the new installation template comes along.
