### ISSUE TITLE
Modern routing fails wo category menu item

### ISSUE THREAD

**Issue by volandku** [joomla/joomla-cms#14175]
When there is no any blog category menu item for category, then url is 
/?view=article&id=1:article-alias

### Expected result
/category-alias/artile-alias

### Actual result
/?view=article&id=1:article-alias

### System information (as much as possible)
Joomla 3.7.beta3

**Comment by franz-wohlkoenig** [comment]
Known Issue like #13978 ([comment](https://github.com/joomla/joomla-cms/issues/13978#issuecomment-278542166))

**Comment by franz-wohlkoenig** [comment]
@volandku wan't you close this Issue?

**Comment by volandku** [comment]
Sorry, I cant check it now

**Comment by volandku** [comment]
But I also found main page instead 404!!!

**Comment by franz-wohlkoenig** [comment]
as known Issue there are a few Threads like #13133
