### ISSUE TITLE
[4.0] (Un)publish or Save Article > Error

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14180]
### Steps to reproduce the issue
(Un)publish Article by Click on green Icon in Column "Status", got:
![bildschirmfoto 2017-02-22 um 11 18 09](https://cloud.githubusercontent.com/assets/8235763/23207342/45ded9fc-f8f1-11e6-82cd-119d046300d5.JPG)

### System information (as much as possible)
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Safari 10.0.3
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by joomdonation** [comment]
For some reasons, I could re-procedure the issue (my Joomla 4 installation was updated two days ago)

**Comment by franz-wohlkoenig** [comment]
i use custom path on nightly builds to stay update, so its on latest staging.

**Comment by joomdonation** [comment]
I tried to synchronize with 4.0-dev but still could not see the issue, maybe something needs to be enabled to see this issue

**Comment by wilsonge** [comment]
`term_id` is a finder table. So you probably need to turn on smart search

**Comment by franz-wohlkoenig** [comment]
@wilsonge Plugins "Smart Search" are turned on. Starting Index got:
![bildschirmfoto 2017-02-24 um 07 27 43](https://cloud.githubusercontent.com/assets/8235763/23292875/f27c07e4-fa62-11e6-90df-8b83e354f73b.JPG)

**Comment by franz-wohlkoenig** [comment]
Same happens if save an Article:
![bildschirmfoto 2017-03-09 um 10 54 14](https://cloud.githubusercontent.com/assets/8235763/23744978/c346203c-04b6-11e7-9c5b-30ea90028693.JPG)

**Comment by tonypartridge** [comment]
Cannot replicate on current branch. 

I suspect there is an issue with your repo / install. Please close.

**Comment by franz-wohlkoenig** [comment]
will try on a fresh installed nightly build.

**Comment by franz-wohlkoenig** [comment]
Works on fresh Install.
