### ISSUE TITLE
[4.0] Cancel new Field (Group) > Error

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14181]
### Steps to reproduce the issue
Add new Field (Group), cancel, got:
![bildschirmfoto 2017-02-22 um 11 30 08](https://cloud.githubusercontent.com/assets/8235763/23207835/fd8db66c-f8f2-11e6-856d-41bfa758756e.JPG)

#### Test on:
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Safari 10.0.3
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by joomdonation** [comment]
It is just small typo on the code. See https://github.com/joomla/joomla-cms/pull/14182 for the fix
