### ISSUE TITLE
[3.7] Users component does not support https

### ISSUE THREAD

**Issue by sshcli** [joomla/joomla-cms#14185]
### Steps to reproduce the issue
1. Migrate your website to HTTPS
2. Go to the login form module and click on "Forgot your username?"
3. Enter the email for your account

### Expected result
You should receive an email with a HTTPS URL

### Actual result
You will receive an email with a HTTP URL (Non HTTPS)

### System information (as much as possible)
Joomla 3.7.0.Beta3
PHP 7.09
MYSQL 5.6.35

### Additional comments
The same happens for other features in the user component like reset password, register, etc..

**Comment by ot2sen** [comment]
@test Can not confirm. Works with https here using 3.7.0 b3

![screen shot 2017-02-22 at 15 17 21](https://issues.joomla.org/uploads/1/be0eae8614fa530d7366fef5c5103c11.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14185">issues.joomla.org/tracker/joomla-cms/14185</a>.</sub>

**Comment by sshcli** [comment]
besides the steps mentioned before, did you perform an additional tweak?
An additional step that I could be missing?

**Comment by ot2sen** [comment]
Can only guess on that part.
Step 1 did include setting URL rewrite in configuration to yes, combined with renaming htaccess.txt to .htaccess in root of site and also setting the force https to 'entire site' in configuration.

Beside that I didn´t do anything special.

**Comment by sshcli** [comment]
Yes, you are right.
Problem solved by setting "Force HTTPS = Entire Site"
I'm closing this issue now.
Sorry for any inconvenience
