### ISSUE TITLE
Global Configuration SIte Offline

### ISSUE THREAD

**Issue by rgblogs** [joomla/joomla-cms#14197]
### Steps to reproduce the issue

Login to back-end.
Go to System -> Global Configuration

### Actual result

Site offline option gives red color to Yes and Green color to No.

**Comment by franz-wohlkoenig** [comment]
known Issue, please see [comment](https://github.com/joomla/joomla-cms/pull/14070#issuecomment-281730578). At this Point Isssue can be closed.
