### ISSUE TITLE
Calendar css is broken

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#14195]
### Steps to reproduce the issue

Open a calendar supported extension, like for us: kunena 
Then go to statistics- select calendar icon

### Expected result

![screenshot 4](https://cloud.githubusercontent.com/assets/876623/23239699/0c0e2b92-f969-11e6-8280-468a337b74cc.png)

### Actual result

![screenshot 3](https://cloud.githubusercontent.com/assets/876623/23239701/0f77ce32-f969-11e6-9158-5a368cabfbb6.png)

### System information (as much as possible)

Joomla! 3.7.0-rc1

**Comment by wilsonge** [comment]
@dgt41

**Comment by wilsonge** [comment]
How are you loading the calendar?

**Comment by 810** [comment]
````
<div class="btn-group pull-left">
	<?php echo JHtml::calendar($this->filterTimeStart, 'filter_time_start', 'filter_time_start', '%Y-%m-%d', array('class' => 'filter input-small btn-wrapper', 'placeholder' => JText::_('COM_KUNENA_STATISTICS_START_DATE'))); ?>
	<?php echo JHtml::calendar($this->filterTimeStop, 'filter_time_stop', 'filter_time_stop', '%Y-%m-%d', array('class' => 'filter input-small btn-wrapper', 'placeholder' => JText::_('COM_KUNENA_STATISTICS_END_DATE'))); ?>
</div>
````

**Comment by dgt41** [comment]
What happens if you remove the class input-small?

**Comment by 810** [comment]
the width is ok, but i can't see any numbers, and there is no style on the title

**Comment by 810** [comment]
ok found the issues:

1) missing font-size on .calendar-container table tbody td.day (C:\wamp\www\develop\media\system\css\fields\calendar.css)
2) please convert em to px on C:\wamp\www\develop\media\system\js\fields\calendar.js and C:\wamp\www\develop\media\system\js\fields\calendar.min.js

**Comment by zero-24** [comment]
Closing as there is a PR: https://github.com/joomla/joomla-cms/pull/14219
