### ISSUE TITLE
[com_fields] Gallery Field Recursive option not used.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#14205]
### Steps to reproduce the issue

When creating a gallery custom field you can set Recursive On/Off

### Expected result

That this will be honoured 

### Actual result

This is not honoured as the code is:

```
		// Get a list of folders in the search path with the given filter.
		$folders = JFolder::folders($path, '.', true, true);
```
the first "true" means Recursion = On - so its hardcoded at the moment and not using the param

### System information (as much as possible)

Joomla! 3.7.0-beta3 Beta [ Amani ] 21-February-2017 15:03 GMT

**Comment by Bakual** [comment]
I think the recursive option currently is used when it comes to returning the files from the selected folder(s).
I don't say that it's correct behavior now 😆

**Comment by franz-wohlkoenig** [comment]
if Plugin Gallery is skipped (#14238 ), this Issue can be closed.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/14309

**Comment by zero-24** [comment]
Field is removed from core.
