### ISSUE TITLE
[com_fields] [3.7b3] [SECURITY] The Gallery Fields 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#14207]
### Steps to reproduce the issue

Add a Gallery field with a directory setting outside of the Joomla root

<img width="456" alt="screen shot 2017-02-23 at 17 16 30" src="https://cloud.githubusercontent.com/assets/400092/23270490/dc7c3e36-f9eb-11e6-8d3e-abea2bc7d786.png">

### Expected result

I expect that Joomla should not be able to go outside its webspace

### Actual result

Time out on my local machine as ../../../ eventually gets to the / and tries to list all folders on my mac

With different values of "directory" I can access different places on the server

**Comment by PhilETaylor** [comment]
Also if I set the folder to be (outside of the joomla root) /Users/phil/Sites/remotebfb/Users/phil/Dropbox/CameraUploads

And then select "One"., the folder name that is at /Users/phil/Sites/remotebfb/Users/phil/Dropbox/CameraUploads/One

And then render on the frontend I get: 

<img width="777" alt="screen shot 2017-02-23 at 17 26 50" src="https://cloud.githubusercontent.com/assets/400092/23270882/479989fc-f9ed-11e6-8c75-e0376138913e.png">

**Comment by zero-24** [comment]
see #14216
