### ISSUE TITLE
[com_fields] [3.7b3] Gallery Field directory help text

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#14208]
### Steps to reproduce the issue

Edit a Gallery Plugin, or Gallery Field - see:
<img width="466" alt="screen shot 2017-02-23 at 17 30 42" src="https://cloud.githubusercontent.com/assets/400092/23271029/de04acdc-f9ed-11e6-84c1-1e1d1f8d4dec.png">

### Expected result

**"Root is pointing to images"** ???? That doesnt make sense to me, its not a sentence, "root" is not defined or explained, and "images" is a folder name(?) rather than the actual images?! 

This is way too open for confusion. Im just an educated idiot and it confuses me.

**Comment by zero-24** [comment]
you are a native speaker maybe you can suggest a better wording? It would be may times better than my denglisch 😄

**Comment by PhilETaylor** [comment]
I wish I actually understood what it meant to say... :(

**Comment by zero-24** [comment]
That folder (you enter into that field) points to a folder under the images folder so the "starting point => root" is the images folder 😄

**Comment by PhilETaylor** [comment]
That is NOT what I thought it meant !!! :) :) :) 

so something like 

> Type the name of the folder within your /images folder, without a preceding or trailing slash (or path to a sub-folder in images like "sampledata/parks") containing the image files to be listed, this will be appended to example.com/images/ to build the list of images used in the gallery

**Comment by zero-24** [comment]
Ah and we need to change that too because we have moved this to folder list so we are selecting the folder here. 😄

**Comment by franz-wohlkoenig** [comment]
if Plugin Gallery is skipped (#14238 ), this Issue can be closed.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/14309

**Comment by zero-24** [comment]
Field is removed from the core now.
