### ISSUE TITLE
[tpl_isis] Language Overrides Filter is cut off

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14201]
The location filter is quite cut off in the overrides:

![image](https://cloud.githubusercontent.com/assets/828371/23263330/3755a4e0-f9de-11e6-8064-1f0536bd1c43.png)

**Comment by franz-wohlkoenig** [comment]
Can't confirm (also not in german/austrian Lang.):
![bildschirmfoto 2017-02-23 um 16 22 30](https://cloud.githubusercontent.com/assets/8235763/23265257/65f17e04-f9e4-11e6-99a2-b3362454df7a.JPG)

**Comment by coolcat-creations** [comment]
@franz-wohlkoenig i see... resize the page to a minimum and expand again without reloading...

**Comment by coolcat-creations** [comment]
1) resizing
https://gyazo.com/b822ce3e17dfa4ea42ebd067af0ac5fd

2) open in smaller size and then resizing
https://gyazo.com/f7a4b284684782b052abc9e03cdb3cd7

**Comment by franz-wohlkoenig** [comment]
confirmed, also:
![bildschirmfoto 2017-02-23 um 16 52 09](https://cloud.githubusercontent.com/assets/8235763/23266585/7fdab2b4-f9e8-11e6-8207-62d37266af7f.JPG)

**Comment by AlexRed** [comment]
I can confirm the problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14201">issues.joomla.org/tracker/joomla-cms/14201</a>.</sub>

**Comment by infograf768** [comment]
@ciar4n
Another one for you?

**Comment by ciar4n** [comment]
This should only be an issue when resizing the browser window. The issue should not be present on load with smaller screens (eg. resize the browser window and then refresh). I am not sure if browser resizing is considered normal behavior and should be considered?

I could extend #13586 to include this field however that comes with it's own issues (#14975).

**Comment by franz-wohlkoenig** [comment]
@ciar4n #14975, #13586 doesn't solve issue.

**Comment by ciar4n** [comment]
I'm not suggesting #13586 solves this issue. I just question is it really an issue if only present when resizing the browser window.

**Comment by franz-wohlkoenig** [comment]
closed as expected Behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14201">issues.joomla.org/tracker/joomla-cms/14201</a>.</sub>

**Comment by dgt41** [comment]
@coolcat-creations @infograf768 @ciar4n someone needs to remove the filter from the left pane and make it consistent with all the other filters in joomla. That also solve correctly this problem, the filters should be on the top not on the left pane

**Comment by brianteeman** [comment]
@dgt41 there is an open issue from Andre that searchtools etc. needs to be added to this viee

**Comment by brianteeman** [comment]
Yes

**Comment by AlexRed** [comment]
I can confirm the problem on Joomla! 3.7.1-dev (nightly Build)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14201">issues.joomla.org/tracker/joomla-cms/14201</a>.</sub>

**Comment by brianteeman** [comment]
@AlexRed as this is still open then of course nothing has magically changed

**Comment by brianteeman** [comment]
I am closing this as we have another open issue #11976 which will resolve this as well
