### ISSUE TITLE
[3.7b3] Creating new object inherits search scope

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#14211]
### Steps to reproduce the issue

Go To the Articles List
Click Search Tools, Select Trashed.
Click New

### Expected result

A new empty Article form is shown with SENSIBLE defaults 

### Actual result

A new empty Article form is shown with TRASHED as the status prefilled

### System information (as much as possible)

[3.7b3] PHP 7.1.2

(Same happens with other views, like the Modules List and creating a new Module after selecting trashed in the list creates a module with status = trashed as default)

**Comment by zero-24** [comment]
I think this is expected behavior and similiar to: https://github.com/joomla/joomla-cms/issues/14193 as the state is saved to the session and reused there. This should also be the case in 3.6.5

**Comment by PhilETaylor** [comment]
I disagree. 

A List of articles should have a different stored scope/session than the defaults used to create an article. The defaults used at article creation should be sensible defaults and not linked in anyway to to the filtering of the list of articles last done.

**Comment by mbabker** [comment]
The filtering state is used in creation for shortcuts like creating an article with a given category when that filter is active.  Not saying all of the filters should be used in that process, but the logic behind it has merit.

**Comment by PhilETaylor** [comment]
In that case it has merit as its setting sensible defaults...

However setting the Status=Trashed on a new article juts because the last filter in a list was trashed, is not a sensible default.

**Comment by franz-wohlkoenig** [comment]
closed as Discussion seems ended.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14211">issues.joomla.org/tracker/joomla-cms/14211</a>.</sub>
