### ISSUE TITLE
[com_fields] [3.7b3] [SECURITY] SQL Field by default lists User Id's and User Names

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#14210]
### Steps to reproduce the issue

Create a new SQL field, without specifying a SQL query. Save it (cause you are a dumb admin, or busy, or any other reason you dont know what you are doing) 

A visitor on the front end, logs in, (with permission to edit/contribute/author kind of perms) edits an article 

The SQL is hard coded here:
https://github.com/joomla/joomla-cms/blob/staging/plugins/fields/sql/sql.php#L48
and here:
https://github.com/joomla/joomla-cms/blob/staging/plugins/fields/sql/tmpl/sql.php#L32

### Expected result

That Joomla doesn't hand that frontend user (could be a hacker!) a complete list of all user id integers and their associated user Name's

### Actual result

A dropdown list is provided of the user id and user name of each and EVERY user registered in the Joomla site. With No limit on the number either!

**Comment by Bakual** [comment]
Agreed, it actually shouldn't have any default values at all. Not sure why it has one.

**Comment by zero-24** [comment]
i'm on a PR that makes the query parameter required and removing the default values.

**Comment by PhilETaylor** [comment]
Probably because I complained that without a SQL query it gave an error message last time ;-)

**Comment by Bakual** [comment]
So you're the guilty one 😆

**Comment by PhilETaylor** [comment]
yup https://github.com/joomla/joomla-cms/issues/13867

**Comment by zero-24** [comment]
see here @PhilETaylor https://github.com/joomla/joomla-cms/pull/14214
