### ISSUE TITLE
Joomla 3.6.5 -> mod_menu -> helper.php -> Undefined offset: 2

### ISSUE THREAD

**Issue by simkea** [joomla/joomla-cms#14218]
### Steps to reproduce the issue
i have a menu from level1 to level 4 and i have placed an module mod_menu 
only for level 4 -> FirstLevel 4 and LastLevel 4

if the menu closed in frontend, i get now this notice...

### Expected result
No Notice Message and no Menuitem is shown... 

### Actual result

Notice: Undefined offset: 2 in /modules/mod_menu/helper.php on line 60
 [SOLUTION] add an check for this:     isset($item->tree[$start - 2]) on line 60

thx

**Comment by zero-24** [comment]
@simkea can you send your changes as pul request against staging?

See here if you need help https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by infograf768** [comment]
code has changed a bit in 3.7.0. Please test with staging (which you would need anyway to patch if still necessary.)

**Comment by franz-wohlkoenig** [comment]
@simkea i don't get what "if the menu closed" means, so i guess change to another Menu. This tested on 3.7, Error Reporting on `Development` don't get a Notice.

**Comment by brianteeman** [comment]
After several months without reply and because the relevant code has changed I am closing this at this time  - it can always be reopened
