### ISSUE TITLE
Unpublished tags still active by URL

### ISSUE THREAD

**Issue by kenleegit** [joomla/joomla-cms#14222]
### Steps to reproduce the issue
I made some Tag and tagged them on articles or whatever supported items.
Then I unpublished the tag. The tag now disappear from the Tags module. It is fine.

Also, tags set access levels to higher, e.g. Managers, are accessible to non-logged in users. 
It appears that tags respect Publish and Access Level only in showing or hiding of tags on the Tags modules, but not the underlying listing logic.

### Expected result
It should show a tag-not-found (or permission denied) error.

### Actual result
The items tagged with the UNpublished tag (or not permitted as per Access Level) listing still accessible at http://mysite/component/tags/tag/2

### System information (as much as possible)
PHP 5.4.16
Webserver Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.4.16
Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by franz-wohlkoenig** [comment]
@kenleegit is this similar to #8569?

**Comment by Bakual** [comment]
Sounds at least related, but not the same.
Apaprently (and I can confirm) the "single" tag view doesn't respect published status and ACL rules at all.

**Comment by Bakual** [comment]
Please test https://github.com/joomla/joomla-cms/issues/14227

Closing this issue as we have a PR.
