### ISSUE TITLE
Request: Custom Field - Geolocation field for 3.7.+

### ISSUE THREAD

**Issue by bubi-luka** [joomla/joomla-cms#14221]
As I find out Custom Fields is a reality for 3.7 or in worst case any other near future releases. But as far as I looked there is no field for adding Geolocation coordinates. It would be a nice addition to the fields, as many articles on the web are about places (news sites, tourist agencies and sports pages just to name a few). It would be helpful to have a unified way in the core to link an article to a coordinates and plugins do the rest. That way if a plugin gets obsolete a migration will be hassle free.

Basic requirements for the field:

- basic coordinates validation for common typing mistakes,
- basic coordinates conversion to a unified back-end style.

Optional features:
- selecting coordinates from a map,
- getting coordinates from a street address,
- getting coordinates from a location of a user/browser.

Regards; Luka

**Comment by Bakual** [comment]
I don't think this is something that has to be in core. It could be easily done as a 3rd party plugin which lives on JED.

**Comment by bubi-luka** [comment]
That is also true for all of the fields included in the core. As I pointed out the problems with 3rd party plugins is consistency of data. In my opinion it is better to have a unified way of storing geolocation data in the database and be able to move from one plugin to another (or have multiple plugins use the same data), as have to use obsolete plugin just because you have to copy the same data to another table every time you switch to another plugin.

**Comment by Bakual** [comment]
> That is also true for all of the fields included in the core.

Except the gallery one, the ones included in core are those which are already present in core as regular FormFields. They are just exposed as custom fields through the plugin.

The argument about having to rely on a 3rd party plugin and its developer is a moot point for me. You could bring that argument for any extension that lives out there. Just look for a trusted developer, maybe even pay him something for his work and you will not face that issue.

**Comment by bubi-luka** [comment]
> You could bring that argument for any extension that lives out there.

I agree.

> The argument about having to rely on a 3rd party plugin and its developer is a moot point for me.

I understand your point of view, but do not agree.

Again I think this field has broad application from a way to enter the home/work address to link an article to a location and it is a feature I would love to have if it is not too difficult to implement and maintain. I am talking only about a field to enter the data in a unified way so the other extensions can use that data in any way they like.

---
Just to clarify that although I "own" only a small personal web page I have paid and will pay for many of the extensions and templates that I use. I am willing to do that but even with a donation or paying for the extension there is no guaranty the extension will not eventually reach EOL, became unsupported with the next version of Joomla and there will be no migration path to another extension. That is the risk with all of the themes and extensions, no matter if they are free or paid ones. That is why I see a benefit for having this kind of field included and maintained by the Joomla developers and not by the 3rd party ones.

**Comment by zero-24** [comment]
What about using two text field custom fields and wrote a override for the single article view that call google maps and show the map if the values are filled?

**Comment by bubi-luka** [comment]
I guess it is possible to solve the thing I asked for on multiple ways.

I am aware of creating article override and link a text field to any kind of maps. But I am asking only for a unified field to enter coordinates with data validation and simple conversion. As I wait for v3.7 stable, I do not have a way to test if text field has an option to do custom data format validation.

Well, I guess this function is not interesting for developers or too difficult to implement and maintained. Perhaps in time there will be a plugin doing that.

Is there a way to ask for a user to ask for a new function or implementation for the project other than GitHub Issues?

**Comment by zero-24** [comment]
> As I wait for v3.7 stable, I do not have a way to test if text field has an option to do custom data format validation.

You can install the lastest beta of 3.7 from here and test like you want: https://github.com/joomla/joomla-cms/releases/tag/3.7.0-beta3

If you need such a feature for your webseite a idea could be to pay a developer to build that kind of plugin.

As everything is cleared up i'm going to close this issue here. Thanks 👍

**Comment by Bakual** [comment]
> Is there a way to ask for a user to ask for a new function or implementation for the project other than GitHub Issues?

It's fine to ask here or on the forums.

> I do not have a way to test if text field has an option to do custom data format validation.

The text field doesn't do any validation at all. You can't add custom validation to it. That's what you would do in an own plugin.

> Well, I guess this function is not interesting for developers or too difficult to implement and maintained. Perhaps in time there will be a plugin doing that.

It's not dificult at all to implement a field which takes a coordinate. As said just use the text field for that. 
Validation will be impossible since there are various coordinate systems. Are we talking about long/lat or the coordinates system we use here in Switzerland (just to name an alternative one)? Displaying a map also will be tricky since you basically need two fields which are coupled together.

**Comment by bubi-luka** [comment]
Thank you all for your opinions about my request. Too bad others do not find it as useful as I do.

**Comment by N6REJ** [comment]
actually, if the geocode was taken from contact data I can see how this would be immensely useful

**Comment by helpwise** [comment]
It is useful. And its also a valid core field in my view. Lattitude Longtitude stored,  and a parser to go from an address into those values would be immensely useful.
