### ISSUE TITLE
Chrome and Safari are ignoring custom.css

### ISSUE THREAD

**Issue by visualtribe** [joomla/joomla-cms#14220]
### Steps to reproduce the issue
start Chrome or Safari
On Chrome right click on mouse and choose inspect
Look at css and note that it does not care about custom.css only template.css

### Expected result

run custom.css over template.css for adjustments

### Actual result

ignores custom.css

### System information (as much as possible)

Newest versions of browsers

### Additional comments
Firefox runs custom.css with no issues. Don't know if there is a fix for this. This seems to be something new as I use to be able to use custom for Safari and Chrome.

**Comment by Bakual** [comment]
What custom.css? The templates support a "user.css", not a "custom.css".

Also I don't think the browsers should play a role here. Except if they have the output cached.

**Comment by bertmert** [comment]
If you're talking about templates Protostar or Beez3 then the custom CSS file is user.css (not custom.css).

**Comment by visualtribe** [comment]
Ok. Helix templates supposedly use a custom.css as do some others. Thanks for the information I will try user.css instead and see if that works, and / or will go to template creator and see what they say. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14220">issues.joomla.org/tracker/joomla-cms/14220</a>.</sub>

**Comment by mbabker** [comment]
For reference a custom or user defined CSS has to be supported by the template.  There isn't an arbitrary file that is automagically loaded by Joomla.

**Comment by Bakual** [comment]
I'm closing this for now as it looks like related to 3rd party anyway.
