### ISSUE TITLE
changing Created by article author

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#14243]
Hi guys, 
I write an article and set the "Created by" article author. Save it. All is OK.
Now, I need to change the article author, so:
- I edit the article
- select the "Created by" filed
- the pop-up window search is opened 
- search and look for a new user
- select on a new user
- but when I click on the new user the pop-up window is closed and nothing happen.

I have to repeat that a second time and the user is finally changed and I can save it.
Be careful, the last user search is always prefilled, so in the case I need the same new user for another article, when I select the "Created by" filed the new user into the pop-up window is prefilled. In this case the window is closed and the user is changed correctly.

### System information (as much as possible)
last joomla 3.6.5 and PHP 5.6.x

### Additional comments
Community confirmed the Bug here: https://forum.joomla.org/viewtopic.php?f=728&t=944655&p=3462518#

**Comment by zero-24** [comment]
Please apply this patch: https://github.com/joomla/joomla-cms/commit/ebb15561923af07563240f29c8114ed53225528f this fixes the issue and is included in the upcomming release 3.7.0. Thanks for reporting 👍

**Comment by joomleb** [comment]
Thank you very much!
