### ISSUE TITLE
[4.0]The template for this display is not available.

### ISSUE THREAD

**Issue by roland-d** [joomla/joomla-cms#14252]
### Steps to reproduce the issue
1. Install Joomla 4
2. Open Administrator login page

### Expected result
No error message

### Actual result
Error message The template for this display is not available. is shown.
![image](https://cloud.githubusercontent.com/assets/359377/23333095/ecf403e8-fb85-11e6-9958-374b415cf081.png)

The error persists after logging in.

### System information (as much as possible)
Joomla 4.0 branch
MySQL 5.7
PHP 7.0.10

**Comment by dgt41** [comment]
Known issue, the update sql files are not up to the task, something is missing (renaming isis to atum, or something like that)

**Comment by wilsonge** [comment]
Did you install Joomla 4 on top of Joomla 3? Or as a fresh install?

**Comment by roland-d** [comment]
@wilsonge This was a clean install from a while ago.

**Comment by wilsonge** [comment]
Can you still replicate? Because I currently cannot

**Comment by mbabker** [comment]
If a while ago was more than a month ago (when the template was merged), that'd make sense as you'd basically still have the 3.x template config in place.

**Comment by yvesh** [comment]
Can't confirm this, with current version atum is in place.

**Comment by roland-d** [comment]
So I did a new clean install and the error is gone. Thanks for checking.
