### ISSUE TITLE
[3.7 b3] Problem with Hikashop

### ISSUE THREAD

**Issue by fgonc124** [joomla/joomla-cms#14259]
### Steps to reproduce the issue
Install V 3.7 and then Hikashop
Create a menu item with type Hikashop product listing

### Expected result
As soon as you select a Hikshop menu item type it should appear a Tab with Hikashop options.

### Actual result
As soon as you select a Hikshop menu item type, all tabs, disappear ( Lynk type , Page display, metadata and module assignment)

### System information (as much as possible)
Windows, PHP 7.1 , Joomla 3.7 b3 , Mysql 5.7

### Additional comments
The problem surges also with PHP 5.6

Hikashop version:3.0.0
![hikashop_nok](https://cloud.githubusercontent.com/assets/26040543/23340819/a48df1b8-fc34-11e6-8753-1f4ad3aeaef4.JPG)
![hikashop_ok](https://cloud.githubusercontent.com/assets/26040543/23340820/a48ebfda-fc34-11e6-8916-58760f54e3b5.JPG)
![hikashop_type](https://cloud.githubusercontent.com/assets/26040543/23340818/a48a3c30-fc34-11e6-9602-4a14bf2cbfd0.JPG)

I tried with Hikashop V 2.6.1 + PHP 7.1 and everything was ok.
I tried with Hikashop V 2.6.1 + php 5.6 and everything was ok.

Looks like that is a problem with joomla3.7b3 and hikashop 3

**Comment by Bakual** [comment]
Are you doing something special with your hikashop menu item? Can you elaborate a bit?

**Comment by fgonc124** [comment]
Nothing special
Just want to select a menu and want hikashop to list some products.

Check live site http://lojadocaopreto.com/index.php/livros/novidades

I want roplicate this

Thanks

Cumprimentos

Fernando Goncalves

Em 26/02/2017 13:38, "Thomas Hunziker" <notifications@github.com> escreveu:

**Comment by fgonc124** [comment]
See the diference between the first and second picture.

All those tabs disappear when install hikashop 3

**Comment by Fedik** [comment]
it looks like there a javascript error, which happens before the tabs rendering
@fgonc124 please check the Browser console, and check is there any error

**Comment by fgonc124** [comment]
Hi Fedik

You were wright. There's a javascript error.
![hikashop_type](https://cloud.githubusercontent.com/assets/26040543/23341304/a26795a8-fc3c-11e6-85a4-88c4f80cb449.JPG)

**Comment by Fedik** [comment]
@fgonc124 your screenshot is broken

**Comment by fgonc124** [comment]
I posted another screenshot

**Comment by dgt41** [comment]
Adding 
```php
JHtml::_('bootstrap.tooltip');
```
in your form will solve the problem?

**Comment by fgonc124** [comment]
Sorry but I don't know how to do it.

My form is a standard form of Joomla. It's the form you get when creating a menu item.

**Comment by dgt41** [comment]
Please ask support from the developer

**Comment by fgonc124** [comment]
So you think the problem is with Hikashop?

**Comment by Bakual** [comment]
Probably yes, since it apparently works with core.
That's why I asked if there is something special Hikashop is doing there.

**Comment by hikashop-nicolas** [comment]
It looks like Joomla 3.7 now has a dedicated "jquery tooltip" library (media/jui/js/bootstrap-tooltip-extended.min.js) which is, unfortunately, in conflict with the official jquery-ui library that HikaShop uses for some of its display.
Joomla should use a different name for its jquery tooltip if it's not compatible with the standard jquery tooltip as it will break each time an extension needs to load jquery-ui and the tooltip library of Joomla is loaded on the page.
On our end, we'll remove the tooltip library from the jquery-ui we're using in HikaShop for the next release as we don't need that piece and that will fix the problem for us but I would suggest fixing that in Joomla.

**Comment by fgonc124** [comment]
Thanks for your help

**Comment by Fedik** [comment]
@hikashop-nicolas thanks for investigation 

> Joomla should use a different name for its jquery tooltip

nice joke 😄 
it actually the bootstrap tooltip, Joomla nothing to do with it 😉 

Not sure what we can do here, to avoid possible conflict. 
Maybe remove tooltip from the media field, because there already popover.

**Comment by Bakual** [comment]
PR for reference which introduced that library: https://github.com/joomla/joomla-cms/pull/10237
Pinging @JoomliC since it was his PR.

**Comment by Bakual** [comment]
> it actually the bootstrap tooltip, Joomla nothing to do with it 

That's actually not true :smile:

**Comment by Fedik** [comment]
> That's actually not true

so, is it someone made it for Joomla?
sorry then 😄

**Comment by C-Lodder** [comment]
@fgonc124 - can you inspect the source code and see the ordering the script are loaded. jQury UI **should** be loaded first.

**Comment by hikashop-nicolas** [comment]
Our jQuery UI is indeed loaded after bootstrap-tooltip-extended.min.js :
https://monosnap.com/file/qF5SJYOWavwvhFmaCYCawBUO15M5F6Our 

on our end, jQuery UI cannot be loaded before since HikaShop is called by a menu item XML element when Joomla creates the edition interface fo the menu item and thus it has already loaded its tooltips.

**Comment by C-Lodder** [comment]
@hikashop-nicolas sorry but you're absolutely wrong. The issue lies with Hikashop. You're importing jQuery and jQuery UI using JDocument. You should be using:

```
JHtml::_('jquery.framework');
JHtml::_('jquery.ui');
```

tested and working

**Comment by hikashop-nicolas** [comment]
We have to use our own jQuery and jQuery UI in order to mitigate compatibility issues with templates and other extensions.

**Comment by hikashop-nicolas** [comment]
Now I don't want to open a debate whether who is right or wrong. As I said, we'll deal with that on our end.  I was just trying to help :)

**Comment by Bakual** [comment]
Closing this issue then as it has ties to Hika loading their own jQuery stuff and not using the API.

**Comment by JoomliC** [comment]
@hikashop-nicolas Just to mention that tooltip extended script is already there since 3.6.0 ! (so the current issue should be related to another change introduced in 3.7-dev, but not directly with BS tooltip extented ;-) )

**Comment by Yves-K** [comment]
Well, its really not the same script and not in the same call order...
However before 3.7 you could **bridge** to avoid conflict between bootstrap and jquery-ui and keep using them both

**$.widget.bridge('newToolTip', $.ui.tooltip);**

https://api.jqueryui.com/jQuery.widget.bridge/

Now it's broken by call of "destroy" on unchecked 'undefined' elements (mediafield.js line 139)
The error message is "cannot call methods on tooltip prior to initialization; attempted to call method 'destroy'"
Even if the code might be cleaned (realy), just using a try... or test ===undefined might do the job !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14259">issues.joomla.org/tracker/joomla-cms/14259</a>.</sub>

**Comment by Bakual** [comment]
@Yves-K If you think there is a legitimate issue, please open a new issue. Commenting on a closed one will not do anything.

**Comment by oxido21** [comment]
I have the same problem now with this configuration:
Joomla 3.8.3
HikaShop Business: 3.2.2
HikaMarket v2.0.1

This problem show up in google chrome, in edge it works fine...

**Comment by brianteeman** [comment]
Please ask for support with Hikashop

**Comment by oxido21** [comment]
@brianteeman  **Problem solved** for me.
I opened the console in chrome ( F12) and pres and hold on refresh button > Empty Cache and Hard Reloade . That worked for me.

**Comment by fgonc124** [comment]
My problem was solved with the release of new version of Hikashop

2018-01-01 21:47 GMT+00:00 oxido21 <notifications@github.com>:
