### ISSUE TITLE
showon sign '!:' does not work

### ISSUE THREAD

**Issue by cn-tools** [joomla/joomla-cms#14257]
### Steps to reproduce the issue
```
<field name="masterfield" type="radio" default="1" class="btn-group btn-group-yesno" label="MasterField" >
	<option value="0">unknown</option>
	<option value="1">value 1</option>
	<option value="2">value 2</option>
</field>
<field name="subfield" type="radio" default="1" showon="masterfield!:0" class="btn-group btn-group-yesno" label="SubField" >
	<option value="1">Show text field</option>
	<option value="2">Show URL field</option>
</field>
<field name="subText" showon="masterfield!:0[AND]subfield:1" type="text" default="" label="Text" />
<field name="subURL" showon="masterfield!:0[AND]subfield:2" size="20" type="url" default="" label="URL" />
```

### Expected result
the subfield AND subText/subURL should only displayed if value of masterfield is not 0.

### Actual result
the subfield is shown always and the fields subText and subURL ignore value of masterfield also.

### System information (as much as possible)
v3.7.0-beta3

### Additional comments
i add a demo plug-in to reproduce the issue easy
[plg_issue_showon_sign.zip](https://github.com/joomla/joomla-cms/files/801885/plg_issue_showon_sign.zip)

**Comment by jjaracz** [comment]
Hi @cn-tools 

At this time there is no support for "!:" expression.
Have a look of that line of code :)
https://github.com/chivitli/joomla-cms/blob/99421f335e6667c1473562c8d5ab3f503fda8d5d/libraries/joomla/form/field.php#L919

Before ":" could be only name of field. For resolve your problem, this should work :)
`showon="masterfield:1,2[AND]subfield:1"`

**Comment by franz-wohlkoenig** [comment]
Closed as expected Behaviour (comment above)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14257">issues.joomla.org/tracker/joomla-cms/14257</a>.</sub>
