### ISSUE TITLE
[com_fields] Unable to set field values in batch

### ISSUE THREAD

**Issue by JurgenG** [joomla/joomla-cms#14261]
### Steps to reproduce the issue
- Select a given set of articles
- Click on the "batch" tool

### Expected result
- Find a list of fields
- Select a field
- Assign a value
- Process

### Actual result
- No field parameters in the batch tool

### System information (as much as possible)
As this is a feature request, I don't think system information is very relevant.

### Additional comments
This feature would come in really handy, especially after adding a new field when there is already existing content.

**Comment by Bakual** [comment]
Given how custom fields work, I don't think it will be possible to implement a batch function for it.

**Comment by franz-wohlkoenig** [comment]
@JurgenG do you wan't to close this Issue?

**Comment by franz-wohlkoenig** [comment]
as @Bakual wrote closing this Issue. @JurgenG please feel free to reopen Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14261">issues.joomla.org/tracker/joomla-cms/14261</a>.</sub>

**Comment by JurgenG** [comment]
Sorry, I missed the question. As I'm not much of a  coder, I won't be contributing. So thanks for looking into it and for the great option of custom fields all together.

I guess the custom fields will be opening a new realm of possibilities for extension developers. Looking forward to see how these creative people will surprise us...
