### ISSUE TITLE
Joomla Menu Item Alias Create exception

### ISSUE THREAD

**Issue by ztj1993** [joomla/joomla-cms#14264]
Multiple save data causes Itemid to repeat, and Itemid is not correct.

The above content comes from the translation.

Joomla_3.7.0-beta3-Beta-Full_Package.

![screen shot 2017-02-27 at 03 40 56](https://issues.joomla.org/uploads/1/7b7235240105a35dec20f10b3e2c8a47.png)
![screen shot 2017-02-27 at 03 40 58](https://issues.joomla.org/uploads/1/7e51f63d01fc17dfa81cf6594b57c279.png)

**Comment by izharaazmi** [comment]
@ztj1993 Please state how to reproduce the issue. It would help resolve this faster.

**Comment by infograf768** [comment]
I confirm the issue.
Create a menu item of type Menu Item Alias.
Save, then Save again, then Save again. The link displayed in the readonly field gets its ItemId modified by adding the same value after the original one.

It does not look like it has any effect in frontend here.

**Comment by infograf768** [comment]
Issue comes from this patch
https://github.com/joomla/joomla-cms/pull/13776

**Comment by Bakual** [comment]
Closing as the faulty PR has been reverted.
