### ISSUE TITLE
3.7b3 update Notice: Undefined property: stdClass::$client_id in libraries\vendor\joomla\utilities\src\ArrayHelper.php on line 521 and 522

### ISSUE THREAD

**Issue by jsubri** [joomla/joomla-cms#14271]
### Steps to reproduce the issue
I took a 3.6.5 site and tried to update to 3.7b3 over the test channel, the update didn't completed, similar than https://github.com/joomla/joomla-cms/issues/13624 

### Expected result
Successful update.

### Actual result
During update process:
Notice: Undefined property: stdClass::$client_id in D:\www\htdocs\upgrade-to-j37b3\libraries\vendor\joomla\utilities\src\ArrayHelper.php on line 521
Notice: Undefined property: stdClass::$client_id in D:\www\htdocs\upgrade-to-j37b3\libraries\vendor\joomla\utilities\src\ArrayHelper.php on line 522

Navigating in com_menus showed briefly the below screen shot.
![j37b3-upgrade](https://cloud.githubusercontent.com/assets/5349333/23384840/d1103aca-fd4c-11e6-9dc9-056f8865dd63.png)

### System information (as much as possible)
Windows7, php5.4, mysql (using mysli), multi-langage (3) with "Menu Type: mainmenu" assigned to all languages and the 3 corresponding "Menu Type: mainmenu-en" + "Menu Type: mainmenu-nl" + "Menu Type: mainmenu-fr"

### Additional comments
found a missing column in #__menu_types
alter table `#__menu_types` add COLUMN `client_id` int(11) NOT NULL DEFAULT '0';  helped to progress  a bit. Might be missing in administrator/components/com_admin/sql/updates/mysql/

**Comment by zero-24** [comment]
@jsubri please double check that you come from 3.6.5 and not any other beta version of 3.7.0.

As the line you mention is there see: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/sql/updates/mysql/3.7.0-2016-11-19.sql#L1

**Comment by jsubri** [comment]
Starting point was a 3.6.5. I found out the site was initially created with 3.6.3-dev, 3.6.3 was applied then migrated to 3.6.4, 3.6.5. Fix button used each time. I fixed the issue by creating the column manually, I don't understand the reason the upgrade failed. Just noted the optional word "COLUMN" is not in the sql file, 
Going to close this. Thank you

**Comment by wojsmol** [comment]
@jsubri `COLUMN` is not optional in the Joomla! SQL parser (see https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/schema/changeitem/mysql.php#L79)

**Comment by wojsmol** [comment]
@jsubri @zero-24 Plese test https://github.com/joomla/joomla-cms/issues/14312
