### ISSUE TITLE
link of module lastest article doesn't display the page article of categorie.

### ISSUE THREAD

**Issue by dpieces** [joomla/joomla-cms#14270]
### Steps to reproduce the issue
Extension module > new module > lastest article module. than i parameter the module for 4 articles onder one categories .

### Expected result
If i clic op the link it must be redirect to the article page of the categorie

### Actual result
It open the home page

### System information (as much as possible)
PHP exécuté sur 	Linux hp60.hostpapa.com 2.6.18-508.el5.lve0.8.89 #1 SMP Sat Oct 22 13:01:40 EDT 2016 x86_64
Version de la base de données 	5.5.52-cll
Interclassement de la base de données 	latin1_swedish_ci
Collation de la connexion à la base de données 	utf8mb4_general_ci
Version de PHP 	5.6.28
Serveur web 	Apache
Serveur web pour interface PHP 	cgi-fcgi
Version de Joomla 	Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Version de la plateforme Joomla! 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Navigateur 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0 

### Additional comments
I get the same result with other brouwers and i have already clean cache admin and brouwers

**Comment by franz-wohlkoenig** [comment]
Cannot confirm Issue on 3.6.5. 

Using Module "Articles - Latest" to show 4 Articles of one Categorie, which is appended to a Menu Item Type `Category Blog` after click on Article redirected to Categorie-Page.

**Comment by dpieces** [comment]
Thank to have chech, but the probleem look like in de link:

It must be : https://www.mysite/category/my-article.html 
but i get: https://www.mysite/my-article.html  and it redirect to index page

**Comment by franz-wohlkoenig** [comment]
closed as unconfirmed Report. If this Issue stay for you or other, please reopen.
