### ISSUE TITLE
Usability improvement on uploader

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#14280]
### Steps to reproduce the issue

Go into ISIS template administration
Click on the select button to upload a new logo image
Drag an image into the window that opens

### Expected result
Uploads image

### Actual result
Image is displayed in browser.

### System information (as much as possible)
[systeminfo-2017-02-28T11-55-26-06-00.txt](https://issues.joomla.org/uploads/1/e626bff8107af44fb0cd922169555d2f.txt)

### Additional comments
If you click on "upload image" then another window opens which allows you to drag the image in.  This is an unecessary step and the original window should allow this.  The reason I took this behaviour is (a) I see the "upload button" so subconciously I believe I can upload in this window and (b) this is behaviour I experience on other websites, including this issue tracker.  Usually the upload button is an alternative to dragging into the window.

**Comment by dgt41** [comment]
Currently the drop area is the button itself, this will be improved with the new media manager

**Comment by uglyeoin** [comment]
But if you click the button a new window opens with the drop area as the window.  Could we not improve that and make the original window the drop area?  It removes a step and improves accessibility as the drop area being the button itself is a small target.  @cpfeifer what are your thoughts?

**Comment by cpfeifer** [comment]
@uglyeoin I agree with you that it should work this way and many users agree as well. The drag & drop functionality introduced in J3.5 is a feature of the TinyMCE editor. While it works well in that context, it doesn't apply to any other backend image inputs, which is what many users expected.

Not sure if there is a short term fix, but a long term solution is being developed right now. In my opinion, addressing this properly starts with improving the Media Manager system so the functionality can better integrate throughout the core. The new media manager development team is working on it, and improving the overall drag & drop functionality is a primary goal.

**Comment by dgt41** [comment]
> The drag & drop functionality introduced in J3.5 is a feature of the TinyMCE editor.

Hell NOOOO! I wrote that thing!

**Comment by cpfeifer** [comment]
What I'm saying is the functionality is only available in within the default editor and it should be available everywhere. Apologies if that wasn't clear :)

**Comment by uglyeoin** [comment]
Excellent, it's not unusable, it's just that we need to get everything to be great not good.  I'd love to see a media manager that accepts plugins, but I guess that's a whole other conversation.  Thanks for your work so far @dgt41 :D

**Comment by brianteeman** [comment]
Closed as we have a PR see #14905

**Comment by brianteeman** [comment]
Sorry. Re-opening as this was for images not files.

**Comment by uglyeoin** [comment]
@dgrammatiko did this get fixed in the new media manager?

**Comment by dgrammatiko** [comment]
This should be closed as it's fixed for J4

**Comment by HLeithner** [comment]
> This should be closed as it's fixed for J4

Closing this. thanks
