### ISSUE TITLE
Release Blocker: Templates Create Overrides has disappeared

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#14281]
### Steps to reproduce the issue
Go into Templates > Templates > Select a template

### Expected result
Can see a button called "create overrides"

### Actual result
Can no longer find the button anywhere.  Has it moved?  Surely this is an error on my part?  

### System information (as much as possible)

see attached [systeminfo-2017-02-28T15-43-24-06-00.txt](https://issues.joomla.org/uploads/1/1dbb268f0873c25af5576ea71c074c2f.txt)

### Additional comments
Wasn't sure whether to submit this as it could have been moved, is there a correct procedure to follow in situations like this?

**Comment by infograf768** [comment]
I confirm. Release Blocker.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14281">issues.joomla.org/tracker/joomla-cms/14281</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Confirm:
#### 3.7-rc1:
![2](https://cloud.githubusercontent.com/assets/8235763/23449410/b0e1e202-fe56-11e6-81e5-1fbe1f0b3e7f.JPG)
#### 3.6.5:
![1](https://cloud.githubusercontent.com/assets/8235763/23449418/bb0ed7a8-fe56-11e6-8d54-d533daeaf233.JPG)

**Comment by infograf768** [comment]
The issue comes from this PR
https://github.com/joomla/joomla-cms/pull/14052

**Comment by zero-24** [comment]
> Wasn't sure whether to submit this as it could have been moved, is there a correct procedure to follow in situations like this?

I'm not sure what you mean? This is a issue you found and reported it back to the CMS so everything is fine? What do you mean with moved? The correct procedure is to report any issues you found on testing the core cms so you have done it correct. Thanks 👍

**Comment by uglyeoin** [comment]
@zero-24 I assumed I was doing something wrong but it looks like it is a bug.  Glad it is useful. 
@infograf768 thanks for discovering the origin

**Comment by dgt41** [comment]
Please test: #14287

**Comment by wilsonge** [comment]
Closing as we have a PR
