### ISSUE TITLE
JMail::addAttachment() doesn't respect file name from array of attachments

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#14285]
### Steps to reproduce the issue
```php
$mailer = JFactory::getMailer();
$mailer->addAttachment([
    $filename => $filepath,
]);
```
or send email with array of attachments via ```JFactory::getMailer()->sendMail()```

### Expected result
Email should have attachment named `$filename`

### Actual result
Email has attachment named `$filepath`

### Additional comments

It's also logical to use array with `path=>name` pairs but not `name=>path` because file name can be same for different attachments while sending same file is ridiculous.

**Comment by mbabker** [comment]
It doesn't work as an associative array.  You have to pass the file path as the first argument and the name as the second, these can either be a single string or an array (and if an array they must both contain the same number of elements).

So...

```php
$mailer = JFactory::getMailer();
$mailer->addAttachment($filepath, $filename);
```

Or

```php
$mailer = JFactory::getMailer();
$mailer->addAttachment([$filepath], [$filename]);
```

**Comment by Denitz** [comment]
Bad, it limits sending multiple attachments via JFactory::getMailer()->sendMail() shortcut method :(

**Comment by wilsonge** [comment]
I agree it's not the most optimal design but it is there now and would be a b/c break to modify. I've added a commit to improve the documentation around this so it should be clearer what the intention is. Closing.
