### ISSUE TITLE
[com_fields] error with gallery on windows localhost

### ISSUE THREAD

**Issue by ChrisHoefliger** [joomla/joomla-cms#14283]
### Steps to reproduce the issue
create a field type gallery
create an article
add a field type gallery and choose a folder with images (e.g. banners)
save the article

### Expected result
Front end displays gallery as expected

### Actual result
On a windows machine (using win 10 and wampserver 64 on drive W:\wampserver64\) there is an error message saying
"Warning
JFolder::create: Could not create folder.Path: W:\wamp64\www\joomla37\cache\plg_fields_gallery\gallery\4\150\W:"
Note that the drive letter of wampserver gets added to the end of the string, including the colon, which is forbidden in a path. The gallery remains empty, as there is nothing to display apart from the title (is that's enabled).

I have a second installation on a Macbook using MAMP, and there the gallery field works as expected.

### Additional comments
![screen shot 2017-03-01 at 09 03 17](https://issues.joomla.org/uploads/1/169defddcf821ed35c23e1ab89c279f5.png)

**Comment by zero-24** [comment]
Can you double check that you are on the lastest staging code aka nightly build?

**Comment by zero-24** [comment]
Thanks for the update.
