### ISSUE TITLE
Since 3.6.4 Cache -> Page Cache Files disappear

### ISSUE THREAD

**Issue by Flocke28** [joomla/joomla-cms#14286]
### Steps to reproduce the issue
Since Joomla 3.6.4 all Page Cache Files disappear randomly on the top of a hour. I checked all 3rd Party Extensions but no one cleared the files. No cron job delete the files. The Page folder and index.html is still present. Only the php files disappear before lifetime ended. 

Bug is after update to 3.6.5 still present.

**Comment by franz-wohlkoenig** [comment]
is this Issue still present?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14286">issues.joomla.org/tracker/joomla-cms/14286</a>.</sub>

**Comment by Flocke28** [comment]
Yes. :-(<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14286">issues.joomla.org/tracker/joomla-cms/14286</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Set on "Needs Review" on Issue Tracker, so Maintainers can decide how to handle Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14286">issues.joomla.org/tracker/joomla-cms/14286</a>.</sub>

**Comment by Flocke28** [comment]
Ticket can be closed.. It was a issue of the hosting provider.. Max count of files was reached. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14286">issues.joomla.org/tracker/joomla-cms/14286</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
closed as no Core Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14286">issues.joomla.org/tracker/joomla-cms/14286</a>.</sub>
