### ISSUE TITLE
Adding Facebook Group like from a web page

### ISSUE THREAD

**Issue by calgrigio56** [joomla/joomla-cms#14298]
### Steps to reproduce the issue
When adding a module to include a Facebook like display, it saves ok but when viewed on the page it comes up with "Error: Not a valid Facebook Page URL." - note that the link to Facebook is to a group name which works ok in a browser [the URL is https://www.facebook.com/groups/mandurahvolleyball/]

### Expected result
Displays a rolling Facebook page on the front of mandurahvolleyball.com
This works ok with a Facebook page of the same name, i.e. Mandurahvolleyball... [the URL is https://www.facebook.com/Mandurah-Volleyball-Association-Inc-214292481923948/]

### Actual result
Receive this message on the web page... Error: Not a valid Facebook Page URL.

### System information (as much as possible)
Joomla Platform 13.1.0
The Joomla site is 3.6.5
PHP Version	5.4.43
PHP Built On	Linux ub007lcs01
Web Server	Apache

### Additional comments
See attached image for results...the top part has the error and the next component shows Facebook![screen shot 2017-03-01 at 23 54 35](https://issues.joomla.org/uploads/1/8f4df17edd4891f4e6c7365c6a1dd632.png)

**Comment by Bakual** [comment]
Core doesn't have any Facebook integration. Please contact either the developer of your Facebook module or use the forums to get support.
