### ISSUE TITLE
mod_fcgid: stderr: PHP Notice:  Undefined property: stdClass::$Array in /plugins/system/keycaptcha/keycaptcha.php on line 412

### ISSUE THREAD

**Issue by gundestrup** [joomla/joomla-cms#14299]
### Steps to reproduce the issue

Just access the site and see in the error log.

### Expected result
No error in the log

### Actual result
Error in the log
[Thu Mar 02 05:12:41.042432 2017] [fcgid:warn] [pid 5992] [client
66.249.76.18:37760] mod_fcgid: stderr: PHP Notice:  Array to string
conversion in /home/lungemedicin/public_html/plugins/system/keycaptcha/keycaptcha.php
on line 412
[Thu Mar 02 05:12:41.042439 2017] [fcgid:warn] [pid 5992] [client
66.249.76.18:37760] mod_fcgid: stderr: PHP Notice:  Undefined
property: stdClass::$Array in
/home/lungemedicin/public_html/plugins/system/keycaptcha/keycaptcha.php
on line 412

### System information (as much as possible)

Use Joomla 3.5.6
System info:
PHP Built On	Linux web18 4.4.0-45-generic #66~14.04.1-Ubuntu SMP Wed Oct 19 15:05:38 UTC 2016 x86_64
Database Version	5.6.33-0ubuntu0.14.04.1
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.1.1
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36

System	Linux web18 4.4.0-45-generic #66~14.04.1-Ubuntu SMP Wed Oct 19 15:05:38 UTC 2016 x86_64
Build Date	Feb 3 2017 13:50:31
Configure Command	'./configure' '--sysconfdir=/etc' '--with-config-file-path=/etc/php5/cgi' '--disable-debug' '--enable-static' '--enable-inline-optimization' '--enable-bcmath' '--enable-calendar' '--enable-exif' '--enable-ftp' '--enable-gd-native-ttf' '--enable-mbstring' '--enable-opcache' '--enable-phar' '--enable-posix' '--enable-shmop' '--enable-soap' '--enable-sockets' '--enable-sysvmsg' '--enable-sysvsem' '--enable-sysvshm' '--enable-zip' '--enable-memcache' '--with-jpeg-dir=/usr' '--with-pspell' '--with-bz2' '--with-curl' '--with-gd' '--with-gdbm' '--with-gettext' '--with-gmp' '--with-mcrypt' '--with-mhash' '--with-mysql' '--with-mysql-sock=/var/run/mysqld/mysqld.sock' '--with-mysqli=mysqlnd' '--with-openssl' '--with-pcre-regex' '--with-pdo' '--with-pdo-mysql=mysqlnd' '--with-pdo-obc=unixOBC,/usr' '--with-pdo-sqlite' '--without-snmp' '--with-sqlite3' '--with-tidy' '--with-unixOBC=/usr' '--with-xmlrpc' '--with-zlib' '--with-pic' '--with-xsl' '--with-freetype-dir' '--with-imap' '--with-imap-ssl' '--with-t1lib' '--with-gd-jis-conv' '--with-kerberos' '--without-pgsql' '--without-pdo-pgsql' '--prefix=/opt/rh/php71' '--enable-intl' '--enable-imagick'
Server API	CGI/FastCGI
Virtual Directory Support	disabled
Configuration File (php.ini) Path	/etc/php5/cgi
Loaded Configuration File	/home/lungemedicin/etc/php7.1/php.ini
Scan this dir for additional .ini files	(none)
Additional .ini files parsed	(none)
PHP API	20160303
PHP Extension	20160303
Zend Extension	320160303
Zend Extension Build	API320160303, NTS
PHP Extension Build	API20160303, NTS
Debug Build	no
Thread Safety	disabled
Zend Signal Handling	enabled
Zend Memory Manager	enabled
Zend Multibyte Support	provided by mbstring
IPv6 Support	enabled
DTrace Support	disabled
Registered PHP Streams	https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip, koowa-buffer
Registered Stream Socket Transports	tcp, udp, unix, udg, ssl, sslv3, tls, tlsv1.0, tlsv1.1, tlsv1.2
Registered Stream Filters	zlib.*, bzip2.*, convert.iconv.*, mcrypt.*, mdecrypt.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk

### Additional comments
When the error log builds up, the site fails.
Only way to fixing it is to manually clean tmp and cache folders.

[Thu Mar 02 05:12:41.049942 2017] [fcgid:warn] [pid 5992] [client
66.249.76.18:37760] mod_fcgid: stderr: PHP Warning:
session_write_close(): write failed: Disk quota exceeded (122) in
/home/lungemedicin/public_html/libraries/joomla/session/handler/native.php
on line 193
[Thu Mar 02 05:12:41.049994 2017] [fcgid:warn] [pid 5992] [client
66.249.76.18:37760] mod_fcgid: stderr: PHP Warning:
session_write_close(): Failed to write session data (files). Please
verify that the current setting of session.save_path is correct
(/home/lungemedicin/tmp) in
/home/lungemedicin/public_html/libraries/joomla/session/handler/native.php
on line 193
[Thu Mar 02 05:13:00.244551 2017] [log_confi[Thu Mar 02
06:18:02.035855 2017] [fcgid:warn] [pid 26086] [client
192.168.0.118:60400] mod_fcgid: stderr: PHP Notice:  unserialize():
Error at offset 20358 of 20447 bytes in
/home/lungemedicin/public_html/libraries/joomla/cache/controller/view.php
on line 63
[Thu Mar 02 06:18:02.035976 2017] [fcgid:warn] [pid 26086] [client
192.168.0.118:60400] mod_fcgid: stderr: PHP Warning:
session_write_close(): write failed: Disk quota exceeded (122) in
/home/lungemedicin/public_html/libraries/joomla/session/handler/native.php
on line 193
[Thu Mar 02 06:18:02.035992 2017] [fcgid:warn] [pid 26086] [client
192.168.0.118:60400] mod_fcgid: stderr: PHP Warning:
session_write_close(): Failed to write session data (files). Please
verify that the current setting of session.save_path is correct
(/home/lungemedicin/tmp) in
/home/lungemedicin/public_html/libraries/joomla/session/handler/native.php
on line 193
[Thu Mar 02 06:18:02.036242 2017] [log_config:warn] [pid 26086]
(122)Disk quota exceeded: [client 192.168.0.118:60400] AH00646: Error
writing to /var/log/virtualmin/lungemedicin.dk_access_log

**Comment by Bakual** [comment]
"keycaptcha" isn't a core plugin. You need to contact the developer of that plugin to get that fixed.
