### ISSUE TITLE
Change language debug mode to allow it to show the language constants

### ISSUE THREAD

**Issue by Spudley** [joomla/joomla-cms#14304]
I would like to propose an additional feature for the language debugging mode.

Go to the Joomla admin panel, global configuration page and turn on the Language debugging mode.

Currently, turning language debugging on results in strings on the site being displayed either surrounded by asterisks (if they are translatable) or question marks (if they are not).

I would like to have an additional mode for the language debugging, so that it can show the language constants instead. These could be enclosed in an alternative notation rather than asterisks or question marks (maybe hash signs?).

This mode would be useful for cases where you want to find out what language constant is being used at a particular point on the page.

This can currently be found out by searching for the string in the search box on the language override page, but having it in the debug mode would be good as well because:

- It would give more confidence that you're overriding the correct term, because you'd be able to see it in place on the site.
- It would allow you to see all the relevant constants on a page at once. Currently you'd have to search for each term separately.
- Being able to see it in place will help gives you context so you can be sure you're translating it correctly.
- You currently have to click to create a new override in order to get to the search form. This isn't ideal if you're not doing overrides.

**Comment by franz-wohlkoenig** [comment]
any comment @infograf768?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14304">issues.joomla.org/tracker/joomla-cms/14304</a>.</sub>

**Comment by brianteeman** [comment]
Its a good idea and not hard to implement BUT because of the length of the constants etc it really becomes pretty ugly and actually quite hard to use

<img width="1201" alt="chrome_2018-05-29_09-28-44" src="https://user-images.githubusercontent.com/1296369/40647059-dbd17f68-6322-11e8-9af0-d899d17f1cfd.png">

**Comment by Quy** [comment]
I don't think it looks bad at all considering its usefulness.

**Comment by Spudley** [comment]
It doesn't matter how ugly or pretty it is -- it's a tool for debugging purposes and testing purposes. Nobody is ever going to actively use the system with this switched on; you switch it on, find out what you need to know, and switch it back off again.

**Comment by dgrammatiko** [comment]
@brianteeman @Spudley we can wrap them in a hidden span. Thus you can still search or view them in the DOM but not mess up the layout too badly. just an idea...

**Comment by infograf768** [comment]
FYI, there is a system plugin that almost just exactly does that.
Can't remember right now who wrote it.

[jtext.zip](https://github.com/joomla/joomla-cms/files/2074866/jtext.zip)

**Comment by infograf768** [comment]
It gives

<img width="1277" alt="screen shot 2018-06-06 at 07 28 18" src="https://user-images.githubusercontent.com/869724/41018700-608874e4-695b-11e8-9929-a09084f9e09f.png">

**Comment by Quy** [comment]
Since there is a plugin for this, can this be closed?

**Comment by brianteeman** [comment]
it is not a published plugin on the jed

**Comment by Bakual** [comment]
> FYI, there is a system plugin that almost just exactly does that.
Can't remember right now who wrote it.

It was me 😄 
I hacked this together a year ago or so. It overrides the JText class with the one in the plugin which then returns the key instead of the translated value.
It isn't published anywhere as it was a request from one translator and it was shared in the translator forum only.
I think you can't put it on JED since it overrides the core class, which imho isn't allowed on JED.

**Comment by Bakual** [comment]
Btw: There is also a plugin which allows to translate to Crowdin directly from your Joomla installation. You can click the text you want to translate, change it inline where it appears and it sends the translation as suggestion to Crowdin.
That one would be on GitHub: https://github.com/Bakual/crowdinachug

**Comment by ghost** [comment]
closed as having Pull Request #21691
