### ISSUE TITLE
 Undefined index: q in file: /components/com_finder/router.php line: 67 

### ISSUE THREAD

**Issue by stAn47** [joomla/joomla-cms#14301]
current code uses @ to suppress the error message, but i would rather suggest to use a faster function which does not produce any internal error messages such as "isset" or "empty". errors caught with @ still get processed by custom and default error handlers and thus it may be much slower in many cases. 

original code at line 67:

	if ($item && @$item->query['q'] === @$query['q'])

the problem is that this line is reached also from within other extensions, not just the com_finder and thus it would be nice if it was optimized for best performance. 

8 Undefined index: q in file: /web/vm2/purity/components/com_finder/router.php line: 67 
8 Undefined index: view in file: /web/vm2/purity/components/com_finder/router.php line: 55 
8 Undefined index: f in file: /web/vm2/purity/components/com_finder/router.php line: 61 

best regards,stan

**Comment by zero-24** [comment]
Closing as there is a PR https://github.com/joomla/joomla-cms/pull/14323

**Comment by Hackwar** [comment]
I've implemented your code in #14323 Thanks for your contribution.
