### ISSUE TITLE
J3.7.x Sticking tabs

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#14302]
### Steps to reproduce the issue
Create a new article select another tab than the default
Save and Close
Create another new article, it opens on the last tab you selected for the last new article. 
### Expected result
A new article shouldn't have any tab selections from a previously created article.
### System information (as much as possible)
Joomla! 3.7 Beta3

**Comment by csthomas** [comment]
This PR #13572 is a little related but not exactly what you want.

**Comment by PhilETaylor** [comment]
There are many duplicates of this in the issues elsewhere.. its been a pain for a very long time in 3.x.x

**Comment by Bakual** [comment]
Since https://github.com/joomla/joomla-cms/pull/13572 is now merged it will be much less painful. Closing the browser will reset the tab states unlike today where the state was saved forever.
It's still not perfect and can still be improved but it is a lot less disturbing.

**Comment by franz-wohlkoenig** [comment]
@tonypartridge can this Issue be closed cause #13572?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14302">issues.joomla.org/tracker/joomla-cms/14302</a>.</sub>

**Comment by PhilETaylor** [comment]
Please test https://github.com/joomla/joomla-cms/pull/15748
