### ISSUE TITLE
[mod_feed] Add date to layout & options

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#14300]
The `mod_feed` module's default layout and options do not support displaying a published date when displaying RSS feeds.  This really seems like it should be supported by the module out-of-the-box.

**Comment by franz-wohlkoenig** [comment]
is a PR coming or mark as "Feature Request"?

**Comment by ghost** [comment]
closed as having Pull Request #18213<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14300">issues.joomla.org/tracker/joomla-cms/14300</a>.</sub>
