### ISSUE TITLE
[3.7] Extension installation grid margin issue

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#14318]
### Steps to reproduce the issue

When installing an extension, the title, copyright and license are put in 1 `<div class="span12"></div>`, then the description is put in another `<div class="span12"></div>`, resulting in the following:

```
<div class="span12">
    <h1>Title</h1>
    <p>Copyright</p>
    <p>license</p>
</div>
<div class="span12">
    <p>description</p>
</div>
```

This then result in the 2nd `<div class="span12"></div>` getting a left margin and pushing the container outside the viewport:

![screeny](https://cloud.githubusercontent.com/assets/2019801/23551193/03ed9a24-000d-11e7-8ebd-4faf4e5f745c.png)

### Expected result

The `span12` div's should be wrapped by `<div class="row-fluid"></div>` like so:

```
<div class="row-fluid">
    <div class="span12">
        <h1>Title</h1>
        <p>Copyright</p>
        <p>license</p>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <p>description</p>
    </div>
</div>
```

### System information (as much as possible)

- Joomla staging

**Comment by brianteeman** [comment]
cannot confirm. All the extensions I tested just displayed the titlle. Can you supply a sample extension that displays this issue

**Comment by C-Lodder** [comment]
@brianteeman - my bad, I should have mentioned, it only seems to occur when you use the following in in your `script.php`

```
public function install($parent)
{
	echo JText::_('SOME_LANGUAGE_STRING');
}
```

**Comment by brianteeman** [comment]
See #14453 for PR
