### ISSUE TITLE
UX To install extension, in Joomla! 3.x you need 2 CLICKS, in Joomla! 4 you need 3 CLICKS and additional scrolling

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#14328]
### Steps to reproduce the issue
To install extension, in Joomla! 3.x you need 2 CLICKS, in Joomla! 4 you need 3 CLICKS and additional scrolling

![Additional clicks on menu](https://pbs.twimg.com/media/C4T8k3nWAAA5k1J.jpg)

### Expected result
Minimize clicks to do some action. Now you need 3 clicks to install extensions in Joomla! 4. In Joomla! 3.x it is only 2. Expected will be at least only 2.

### Actual result
You need 3 clicks to install extensions in Joomla! 4

### System information (as much as possible)
Joomla! 4, PHP 7, MySQL 5

**Comment by C-Lodder** [comment]
again, the sidebar is going to be completely re-written, so this can be closed.

**Comment by franz-wohlkoenig** [comment]
closed for Reason above commented.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14328">issues.joomla.org/tracker/joomla-cms/14328</a>.</sub>
