### ISSUE TITLE
MySQL error "isn't in GROUP BY" - strict mode for MYSQL (ONLY_FULL_GROUP_BY)

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#14329]
### Steps to reproduce the issue
Install some extension where some SQL query uses "group by" but does not have listed all the columns they are asked in SELECT

### Expected result
Not sure if expected, but I think, this strict mode (only full group by) can break a lot of extensions installed in Joomla! 4

### Actual result
MySQL error "isn't in GROUP BY" by every GROUP BY which does not list complete asked columns

### System information (as much as possible)
Joomla! 4, PHP 7, MySQL 5

### Additional comments
Be aware: See this issue from Joomla! perspective not from MySQL Strict Mode perspective. Such option can eliminate running of a lot Joomla! extensions.

**Comment by infograf768** [comment]
@PhocaCz Please look my findings at
https://github.com/joomla/joomla-cms/pull/14321

**Comment by PhocaCz** [comment]
Hi, thank you for the link. Yes, this is the same case you have described.

The question is: Will Joomla! 4 use strict MySQL (ONLY_FULL_GROUP_BY) or not?

(I saw similar discussions in other projects like e.g. Laravel.)

If yes, I think, extension developers need to be informed because this means, overwriting a lot of code (sql queries) for each extension (in case group by - to write all the selected columns into the group by clause).

**Comment by mbabker** [comment]
Yes, 4.0 will use strict MySQL, see https://github.com/joomla/joomla-cms/pull/12494 for the PR introducing the change.

The page is still being built but the information will eventually make its way onto https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4.

Pending further questions, this item can be closed.

**Comment by PhocaCz** [comment]
Thank you for the info.
