### ISSUE TITLE
[com_fields] (com_contact) List Field in Contactform is disabled

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14336]
### Steps to reproduce the issue
Create a list Field for Client= Mail
![image](https://cloud.githubusercontent.com/assets/828371/23581988/be5a23be-0120-11e7-9978-bacb87d067ac.png)

### Expected result

Field should be shown in the contactform for the user to chose from the values

### Actual result
Field is disabled (cursor shows disabled icon)
![image](https://cloud.githubusercontent.com/assets/828371/23582010/f4efa8cc-0120-11e7-92de-0b45ae226f7d.png)

**Comment by franz-wohlkoenig** [comment]
is this same like #13753

**Comment by coolcat-creations** [comment]
Yes, thanks. Then issue solved... 
Bad UX though... :/

**Comment by franz-wohlkoenig** [comment]
@Bakual so theres one more Issue reported. We will have more;-) We talked about chnging default behavior, we should do it but i don't remember arguments against it.

**Comment by Bakual** [comment]
>  i don't remember arguments against it

Simple, you can't 😄 
ACL always defaults to NO and you can't differentiate between the contact itself (where public should be disallowed) and the contact form (where public should be allowed). You need to do that on field (or group) level.

So it's a question of documentiing it properly.

**Comment by franz-wohlkoenig** [comment]
i will copy the Link to Documentation on my Clipboard

**Comment by franz-wohlkoenig** [comment]
so this cluld be closed, @coolcat-creations ?

**Comment by coolcat-creations** [comment]
Still i think it will be a huge issue. So my ideas for a solution: 
1) Can the ACL be displayed in the Fields Overview somehow? **OR**
2) Can there be a help box, like it´s in the Language overrides that explains not to forget to set the permissions **OR**
3) Can the permission be displayed in the first tab? Something like: This field is editable for: Super Admin. If you want to change permissions open the ACL tab.

something like this?

**Comment by Bakual** [comment]
I don't think that is doable easily. As you know there can be a lot of usergroups and you would have to show that setting for each of them. And honestly, it's likely only an issue for the contact form fields.
I think that is a task for documentation, the code already shows the calculated permissions for each usergroup when you edit the field. You just need to look at the permission tab.
