### ISSUE TITLE
[com_fields] (com_contact) List Field Placeholder Parameter is not used

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14335]
![image](https://cloud.githubusercontent.com/assets/828371/23581891/5c5180ba-011e-11e7-9c4a-681ada200c34.png)

### Expected result
In the list field i wrote the text "Please select"
Expected Behaviour for a list field would be to have this in the Dropdown as a select text.

But in com_contacts, where i edit this field the first value is shown as default instead of a placeholder.

![image](https://cloud.githubusercontent.com/assets/828371/23581919/d75e5788-011e-11e7-9d07-defd7fa4175b.png)

The problem is also that this field is saved with the first value even if the user makes no selection ...

**Comment by franz-wohlkoenig** [comment]
on which Field-Type you get this issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14335">issues.joomla.org/tracker/joomla-cms/14335</a>.</sub>

**Comment by coolcat-creations** [comment]
On all "list" fields.

Sorry - i try to reply to all the issues you mentioned me, but i´m currently not so good available...

**Comment by franz-wohlkoenig** [comment]
issue confirmed, test on Field-Type `List (list)`.
### System information
Joomla! 3.7.0-beta4 (nightly Build)
macOS Sierra, 10.12.4
Firefox 52 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by coolcat-creations** [comment]
This is still happening and the first entry of the dropdown is saved even if the user did not select anything.

**Comment by Bakual** [comment]
The list field doesn't support placeholders. You need to add your "Please Select" as an entry of the list itself.

@laoneo Cann we remove the placeholder parameter for list views? I lost track of what we can and cannot override by now :)

**Comment by laoneo** [comment]
@Bakual did you had a look, is the list field even using the placeholder?

@coolcat-creations is it not possible to just create an empty list entry as first one? The you have the empty first selection.

**Comment by Bakual** [comment]
>  did you had a look, is the list field even using the placeholder?

I haven't looked at the formfield itself, but I doubt it does support a placeholder as it's not a valid attribute in HTML5 (and doesn't make sense in that context). But I may be wrong of course 😄

**Comment by brianteeman** [comment]
Placeholder is not a valid attributed for a list field (and probably many others)

Do we have a method to remove a field from the options?

If not then it might be better to remove it from the options globally and just add it to the basic params for each field type that supports it

**Comment by ghost** [comment]
closed as having Pull Request #18212<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14335">issues.joomla.org/tracker/joomla-cms/14335</a>.</sub>
