### ISSUE TITLE
Postgresql: Warning: Database is not up to date!

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#14331]
### Steps to reproduce the issue

With latest staging go to Manage > Database. You will find these 2 problems.

Database update version (3.7.0-beta3) does not match CMS version (3.7.0-rc1).
Table 'gblq8_updates' does not have column 'data' with type IS NOT NULL. (From file 3.1.0.sql.)

There is also a notice message:
Notice: Undefined offset: 8 in /var/www/html/joomla34p/libraries/cms/schema/changeitem/postgresql.php on line 111

**Comment by alikon** [comment]
@waader  can be closed for the same reason of #14332

**Comment by zero-24** [comment]
@alikon what is about the #__updates error and the offset error message?

**Comment by alikon** [comment]
i'm unable to reproduce  problem 1)

> Database update version (3.7.0-beta3) does not match CMS version (3.7.0-rc1).
Table 'gblq8_updates' does not have column 'data' with type IS NOT NULL. (From file 3.1.0.sql.)

i'm able to reproduce the notice the fix is #14423

**Comment by zero-24** [comment]
Thanks for checking 😄

**Comment by waader** [comment]
With latest staging I didn´t get Table 'gblq8_updates' -Error
And while I am typing @alikon has a patch for the other problem. I will test that.
