### ISSUE TITLE
[com_fields] Calendar Field Plugin options, Language string is missing

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14339]
PLG_FIELDS_CALENDAR_PARAMS_FORMAT_LABEL

![image](https://cloud.githubusercontent.com/assets/828371/23582411/d807a558-0129-11e7-9c76-aedb486a2a21.png)

**Comment by Bakual** [comment]
Confirmed

**Comment by zero-24** [comment]
see #14343

**Comment by Bakual** [comment]
See https://github.com/joomla/joomla-cms/pull/14344 which removes that useless parameter.
