### ISSUE TITLE
[com_fields] (request) Multiple Option Use from Plugin - unclear value / UX

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14334]
![image](https://cloud.githubusercontent.com/assets/828371/23581849/965bae62-011d-11e7-93d6-ff9c0d8c9c52.png)
Is it possible to display somehow the plugin value ? How should the user know affront if it´s multiple or not?

Thanks

**Comment by Bakual** [comment]
The existing feature to look up the global value doesn't work here because the global value here comes from a plugin. But it could be done by customising the formfield used for the "Multiple" option.
Just needs someone to do it 😄

**Comment by jwaisner** [comment]
As features are not available for J3 any more this is being closed. Please check J4 to see if this feature still may be applicable.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14334">issues.joomla.org/tracker/joomla-cms/14334</a>.</sub>
