### ISSUE TITLE
Mysql: Warning: Database is not up to date!

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#14332]
### Steps to reproduce the issue
With latest staging go to Manage > Database. You will find this problem.
Database update version (3.7.0-beta3) does not match CMS version (3.7.0-rc1).

**Comment by zero-24** [comment]
how did you update to the last staging? Or did you a new install of staging?

**Comment by waader** [comment]
I did a new install of staging.

**Comment by zero-24** [comment]
Please try to change this value: https://github.com/joomla/joomla-cms/blob/staging/administrator/manifests/files/joomla.xml#L9 to 3.7.0-rc1 and hit the "refresh mainfest cache" button in com_installer 😄

**Comment by waader** [comment]
That helps!

**Comment by zero-24** [comment]
So this is expected behavior than as we only update that xml file on a real release 😄

**Comment by zero-24** [comment]
Thanks for checking.
