### ISSUE TITLE
Create a media directory from an article for Joomla! 3.7

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#14348]
With Joomla! 3.7 we can create an article, a category, since the creation of a menu link. Can you do the same for the creation of a directory of the media manager since the creation of an article?

créer un répertoire média depuis un article pour Joomla! 3.7

Avec Joomla! 3.7 nous pouvons créer un article, une catégorie, depuis la création d'un lien de menu. Pouvez-vous en faire autant pour la création d'un répertoire du média manager depuis la création d'un article ?

**Comment by zero-24** [comment]
I don't understand your request can you be a bit more spezific?

**Comment by Magnytu2** [comment]
I forgot to insert an image

Pardon j'ai oublié d'insérer une image![screen shot 2017-03-05 at 09 55 12](https://issues.joomla.org/uploads/1/006fd0df6a83971b0fb17d6157eb9d23.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14348">issues.joomla.org/tracker/joomla-cms/14348</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@laoneo comes this or is planned with new media manager?

**Comment by franz-wohlkoenig** [comment]
@laoneo added in Tracker to "Feature Request", "UI/UX".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14348">issues.joomla.org/tracker/joomla-cms/14348</a>.</sub>

**Comment by laoneo** [comment]
Yes this is planed for the media manager in 4. Guess we can close this one.

**Comment by franz-wohlkoenig** [comment]
closed as Feature is planned on new Media Manager.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14348">issues.joomla.org/tracker/joomla-cms/14348</a>.</sub>
