### ISSUE TITLE
[com_fields] Calendar Field Design Issues when using with other languages

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14341]
When you use the Calendar-Field with German Language the Word "Uhrzeit" is cut off, as well as the Close Button (Schließen) is too close to the edge.
The Dayshortener with 3 Letters are rather uncommon IMO. (We use rather 2 letter)

![image](https://cloud.githubusercontent.com/assets/828371/23582473/206ca41e-012b-11e7-8557-5b3c9d94d0f6.png)

**Comment by dgt41** [comment]
@ciar4n can you have a look at this one?

**Comment by dgt41** [comment]
> The Dayshortener with 3 Letters are rather uncommon IMO. (We use rather 2 letter)

Well have a talk with the German translators, this is what they commit:
https://github.com/joomla/joomla-cms/blob/staging/media/system/js/fields/calendar-locales/de.js#L7

**Comment by zero-24** [comment]
@coolcat-creations about the german translation you can check this: https://github.com/joomlagerman/joomla/blob/master/media/system/js/fields/calendar-locales/de.js and PR there for Jan 😄

**Comment by franz-wohlkoenig** [comment]
@coolcat-creations can this Issue be closed?

**Comment by coolcat-creations** [comment]
I think the issue with the overlay (Uhrzeit) is not solved, yet - or is there a PR?
Can be in other languages even longer so the timefield has to move if the string needs space :)

**Comment by franz-wohlkoenig** [comment]
okay, i thought it depends on translation like @zero-24 wrote.

**Comment by ciar4n** [comment]
These buttons are within the table which offers little freedom regarding changing their width. 

The solutions available that I can think of..

- Replace button text with icons
- Increase the entire width of the calendar
- Move the buttons outside of the table. @dgt41 is this possible?

**Comment by dgt41** [comment]
@ciar4n these buttons have some event listeners and moving them out of the table means a bit of refactoring...
If this is the best solution here then I need to find some time to do it, let me know

**Comment by ciar4n** [comment]
Ideally yes. Even moving all the buttons into a single cell spanning the entire width of the table would allow us to give the buttons equal widths.

**Comment by franz-wohlkoenig** [comment]
closed as PR #14484
