### ISSUE TITLE
Viewing fields in blog joomla 3.7

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#14346]
Hello, I would like to be able to choose to display or not the new fields of Joomla! 3.7 in blog mode. Is it possible to choose?

Affichage des champs en blog joomla 3.7

Bonjour, j'aimerai pouvoir choisir d'afficher ou pas les nouveaux champs de Joomla! 3.7 en mode blog. Est-ce possible de choisir ? 

![screen shot 2017-03-05 at 09 16 59](https://issues.joomla.org/uploads/1/9f42d7098fff9fe773484cddd0d55165.jpg)

**Comment by zero-24** [comment]
Please explain in a bot more detail what you want or what is happening. I don't understand your request?

**Comment by Magnytu2** [comment]
I would not like to show the new fields or group of fields of an article in blog view. Only when displaying the complete article.

Je souhaiterais ne pas faire apparaitre les nouveaux champs ou groupe de champs d'un article en affichage blog. Uniquement lors de l'affichage de l'article complet.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14346">issues.joomla.org/tracker/joomla-cms/14346</a>.</sub>

**Comment by Bakual** [comment]
That's not possible without overrides.

**Comment by franz-wohlkoenig** [comment]
@Magnytu2 Workaround: Set Field in Tab `Options > Automatic Display: No` and append in Content {field ID}

**Comment by Magnytu2** [comment]
Hello, thank you very much for the tip. It works and it's great. Too bad this is not more intuitive but it is already a huge step.

Bonjour, merci beaucoup pour l'astuce. Cela fonctionne et c'est génial. Dommage que ce ne soit pas plus intuitif, mais c'est déjà un énorme pas.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14346">issues.joomla.org/tracker/joomla-cms/14346</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@Magnytu2 its a step-by-step-Process. So maybe next Release work more People and make it happen.

**Comment by franz-wohlkoenig** [comment]
@Magnytu2 can you close issue?

**Comment by Magnytu2** [comment]
Yes thank you very much<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14346">issues.joomla.org/tracker/joomla-cms/14346</a>.</sub>
