### ISSUE TITLE
[com_fields] Editor Field, Show Editor icons (from plugin, yes, no) Hide Buttons unclear UX

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14342]
This one is quite bad UX, at least the tooltips should explain better what is meant with it.
Also if i have to name Buttons that should be hidden, there should be a Tooltip that tells me what is the exact value i have to type in this field.

![image](https://cloud.githubusercontent.com/assets/828371/23582538/c5df0bc0-012c-11e7-8e89-ee95c7ed4279.png)

![image](https://cloud.githubusercontent.com/assets/828371/23582553/32db36ae-012d-11e7-923e-71462bd8f5f0.png)

**Comment by franz-wohlkoenig** [comment]
Also don't know how to list Buttons.

**Comment by coolcat-creations** [comment]
It´s pagebreak,readmore  and so on - but the explanation it quite weak.

**Comment by franz-wohlkoenig** [comment]
an Example would help and non-dev haven't to figure out if `Button - Page Break` or `pagebreak` or … is meant.

**Comment by laoneo** [comment]
Probably we should remove this option as it needs knowledge how the names are of the button plugins.

**Comment by franz-wohlkoenig** [comment]
@laoneo an Example (use name of plugin like `pagebreak`) would help.

**Comment by Bakual** [comment]
> Can be a list of buttons plugins instead with multiple=true. @Bakual would that work?

Should work I think. But I'm not really an expert with the editor.

**Comment by laoneo** [comment]
Please check pr #14390. It should a list of editors instead of a text field.

**Comment by Bakual** [comment]
Closing as we have a PR
