### ISSUE TITLE
Joomla 3.6 installer

### ISSUE THREAD

**Issue by jb-neubauer** [joomla/joomla-cms#14345]
### Steps to reproduce the issue
When trying to install extensions via the **Extensions > Manage > install** I receive the warning 
"No installation plugin has been enabled. At least one must be enabled to be able to use the installer. Go to the Plugin Manager to enable the plugins."

I followed some of the other posts and they suggested going to the **Discover** tab to discover the uninstalled plugins needed but that also came up with nothing found.  I have also tried to manually download the zip file to my server and install the installation folder on the server side.  That didn't work either.  

### Expected result
Joomla to allow the installation of plugins

### Actual result

Warning

No installation plugin has been enabled. At least one must be enabled to be able to use the installer. Go to the Plugin Manager to enable the plugins.

### System information (as much as possible)

PHP 7, Joomla 3.6.5, mysql 5

**Comment by zero-24** [comment]
Please go to the Plugin Manager to enable the installer plugins. ;)

This should only be happen if you update using a not supported update path.
This is not a bug in the core. Please ask such questions in the forum: https://forum.joomla.org
