### ISSUE TITLE
[3.7.0] mod_articles_categories. Newly created category stays checked-out/locked

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#14350]
### Steps to reproduce the issue
- Install current Staging (3.7.0).

- See that all categories (com_content) are checked-in (not locked).

- Module Manager > New > "Articles - Categories"

- Enter Title

- Field "Parent Category" > Click on button "Create" and create a new category > Save & close category

- Save & close module.

- Go to Category Manager (com_content): Newly created category is checked-out/locked

![05-03-_2017_11-40-16](https://cloud.githubusercontent.com/assets/11038612/23586639/7d09e0ec-0199-11e7-8d66-5d370993f4c8.jpg)

**Comment by franz-wohlkoenig** [comment]
Confirmed. Similar #14192

**Comment by bertmert** [comment]
The issue is only present when I use button "Save & Close". Not when I first "Save" and then "Close".
With "Save & Close" I see for a short moment a nearly empty modal (no form, just headline) that closes. Afterwards I see just for a short moment that a new modal appears (complete edit form for created category).

**Comment by franz-wohlkoenig** [comment]
there are now 3 different Issues about locked Items created in Modal.

**Comment by bertmert** [comment]
Any chance to get a "release-blocker" label then here or there? In a multi user Joomla there will be too many locked items that cannot be unlocked by some user groups.

**Comment by mbabker** [comment]
While annoying, this does not constitute a release blocker IMO.  If it were consistently reproducible every time someone used the feature, maybe.  But as it seems to be limited to the use of one browser, its severity is downgraded massively.

**Comment by tonypartridge** [comment]
@bertmert do you have any errors in your error logs that could help us pin point the issue?

**Comment by franz-wohlkoenig** [comment]
@tonypartridge Test new Article in Modal at Menu Item Type "Single Article":

- Click `Read-more`-Button: `TypeError: b is undefined. admin-article-readmore.min.js:1:160`
- Click `Save`-Button: `Use of getAttributeNode() is deprecated. Use getAttribute() instead.  jquery-migrate.min.js:2:1714`
- Click `Save & Close`-Button: `TypeError: n.getComputedStyle(...) is null. tinymce.min.js`

![bildschirmfoto 2017-03-09 um 08 04 36](https://cloud.githubusercontent.com/assets/8235763/23739438/18399ad2-049f-11e7-8d42-7dce446aef66.JPG)

**Comment by infograf768** [comment]
I confirm the issue for all modals displayed after using a Create and it is consistent. (Firefox)
@Fedik @dgt41
This looks related to the modals themselves. The fact that the modal is limited to the buttons once using Save and Close is a totally new behavior. That aspect is also the case for Safari, although Safari does not save the item as locked.

**Comment by infograf768** [comment]
@mbabker 
We have the same issue when Edting an existing category or article through the modal, etc, not only when creating.
It's quite serious.

**Comment by dgt41** [comment]
The modal approach has a few problems:
- tinyMCE sets up a listener for form submit, this is not removed when the modal is closed
- This could be true for any script that's loaded in the iframe
- the code is a bit weird for me:
```js
				// For Save & Close (save task) when creating we need to replace the task as apply because of redirects after submit and hide the iframe.
				if (task === 'save')
				{
					submittedTask = 'apply';
					jQuery('#' + modalId + ' iframe').addClass('hidden');
				}

				document.getElementById('Frame_' + modalId).contentWindow.Joomla.submitbutton(itemType.toLowerCase() + '.' + submittedTask);
```

So to prevent the redirect you have this odd behaviour...

**Comment by infograf768** [comment]
I think we HAVE to solve this in 3.7.0. It's really bad.

**Comment by tonypartridge** [comment]
I agree with @infograf768 it's a UX pain and can come across as buggy from an end users perspective.

**Comment by Fedik** [comment]
please test #14537

**Comment by bertmert** [comment]
Closed as we have a PR
