### ISSUE TITLE
[com_fields] Feature Request for Text field - custom filters

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14359]
In the text field there is only the possibility to chose from No and Raw. Would be great if the other possible filters could be added such as:

rules
unset
raw
int_array
safehtml
server_utc
user_utc
url
tel
text

Not sure if my list ist correct and if it´s complete...

![image](https://cloud.githubusercontent.com/assets/828371/23587587/2ac78818-01b0-11e7-9bf7-8ebeaa89219b.png)

**Comment by franz-wohlkoenig** [comment]
@maintaners: at this Point this kind of issue should get a Label "Enhancement" for 3.8 to have Energy on getting 3.7 solid and out.

**Comment by laoneo** [comment]
Please test pr #14403 which adds filters for text, textarea and the editor field.
