### ISSUE TITLE
[com_fields] Editor field Settings are not applied to field

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14354]
Set the Editor to 400 x 300 pixel and Show Buttons to "No"
![image](https://cloud.githubusercontent.com/assets/828371/23586833/3d61fd26-019e-11e7-8651-6b29dbcd2012.png)
 Editor is still Fullwidth and 750px height and the Buttons are still there
![image](https://cloud.githubusercontent.com/assets/828371/23586841/64c31080-019e-11e7-9c5f-94ca7df6eb04.png)

**Comment by franz-wohlkoenig** [comment]
Confirmed. Changing Setting in TinyMCE doesn't change Setting in Field.

**Comment by joomdonation** [comment]
There is a PR fixes this issue, see https://github.com/joomla/joomla-cms/pull/14033

We requested a small change to the code of that PR but the author hasn't made change yet. Once that PR merged, this issue should be fixed

**Comment by franz-wohlkoenig** [comment]
@joomdonation using #14033 got in Articles > Tab `Content` none-Editor.

**Comment by franz-wohlkoenig** [comment]
But this Issue (14354) is solved.

**Comment by brianteeman** [comment]
Closed as there is a PR as referenced above
