### ISSUE TITLE
[com_fields] Field Ordering wrong at editing

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14355]
I created a new Field for the imagelist as you see at the bottom of the first screenshot. It´s ordered at the bottom of the list. However it´s displayed suddendly at the top of the Field tab.

![image](https://cloud.githubusercontent.com/assets/828371/23586899/98658c50-019f-11e7-84fa-43248c702f33.png)

![image](https://cloud.githubusercontent.com/assets/828371/23586902/aa1e71a0-019f-11e7-844d-11f08c777a21.png)

**Comment by Bakual** [comment]
Can't replicate this. For me the order follows exactly how I have set them in the fields manager.

**Comment by coolcat-creations** [comment]
Happened again:
![image](https://cloud.githubusercontent.com/assets/828371/23587672/c4b28260-01b1-11e7-96d4-86889e0987bb.png)

![image](https://cloud.githubusercontent.com/assets/828371/23587674/ca6da86a-01b1-11e7-8a63-eecc6389b697.png)

**Comment by coolcat-creations** [comment]
I can replicate now:
Open the article and leave it open. 
Open a field from the ones that should appear at the bottom and save it (leave it open). 
Reload the article.
Close the field and see that is should be still at the bottom from the ordering...

**Comment by Bakual** [comment]
Still can't replicate, but maybe someone else can?

**Comment by coolcat-creations** [comment]
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/828371/23587760/404504ce-01b3-11e7-8194-5cb8bbc26216.gif)

**Comment by franz-wohlkoenig** [comment]
Can't conform Issue. Fields stay in Order they have in Fields-View. Changing order is correct reflected at Article-Tab.

**Comment by coolcat-creations** [comment]
@franz-wohlkoenig but thats not what i described. can you follow the clicks i made? I mean leave both open...

https://youtu.be/hzU5ZIMEJeA

**Comment by franz-wohlkoenig** [comment]
tested again, also leave Article- and Fields-Tab open: Change Field and save, reload Article > no Chance.

Difference are Count of Fields (at my end 4) and Type (Gallery, Media, 2 Integer) and maybe this causes different Behaviour.

**Comment by coolcat-creations** [comment]
I tested with any field and it always happened... hmmm

**Comment by franz-wohlkoenig** [comment]
would help if others can test

**Comment by franz-wohlkoenig** [comment]
test again using new Article, new Field – no (randomly) wrong order.

**Comment by coolcat-creations** [comment]
For me it´s not randomly, every field i edit... I´m testing with Chrome, does this matter ?

**Comment by franz-wohlkoenig** [comment]
will test on Chrome – are you on Mac/Win/Linux?

**Comment by coolcat-creations** [comment]
I am on Mac, Chrome Version Version 56.0.2924.87 (64-bit) (latest)

**Comment by franz-wohlkoenig** [comment]
also Mac, Chrome 56.0.2924.87 (64-bit) (latest) - no changes, every Field stay in order.

**Comment by laoneo** [comment]
I'v tested it as well and con't reproduce the issue.

**Comment by franz-wohlkoenig** [comment]
@coolcat-creations did Issue still happen?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14355">issues.joomla.org/tracker/joomla-cms/14355</a>.</sub>

**Comment by Quy** [comment]
Unable to reproduce with RC4 on MacBro Pro and Chrome 58.0.3029.81

**Comment by Quy** [comment]
This is reproducible. 

In your browser, open 2 tabs. Tab #1 for Fields and Tab #2 for Articles.
In Tab #2, edit an article and go to the Fields tab within the article.
In Tab #1, edit a custom field (not the first one). Click `Save` and not `Save & Close` button.
Switch to Tab #2 and refresh the page. The edited custom field will be the first one listed.

**Comment by franz-wohlkoenig** [comment]
Confirmed what @Quy wrote.
### System information
3.7.0-rc4
macOS Sierra, 10.12.4
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
Can you please check if this is still an issue as it appears there was a PR addressing this.

**Comment by ghost** [comment]
This is still an Issue.
### System information
3.8-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by laoneo** [comment]
I will give it another try next week to replicate the issue.

**Comment by jwaisner** [comment]
Closing as the conditions required to reproduce are extremely specific and only happen under that condition.

**Comment by coolcat-creations** [comment]
But why would you close it if it's stil a bug?

**Comment by nibra** [comment]
"Closing as the conditions required to reproduce are extremely specific and only happen under that condition."
That seems not to be a valid reason to close the issue. It may cause a low priority,and maybe the bug only has low impact, however, this is the wrong way to clean up the tracker.
Please re-open.

**Comment by SniperSister** [comment]
@coolcat-creations do you still have a site where you can reproduce the issue? If so, could you please check the values of the "ordering" column in the __fields table?

**Comment by Bakual** [comment]
Reopening since the bug apparently exists

**Comment by coolcat-creations** [comment]
I checked again and can't be reproduced anymore - Thank you
