### ISSUE TITLE
[com_fields] Field Image list Multiple select - If values are deleted, values come back after saving

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14357]
### Steps to reproduce the issue
Create a image list Field with multiple selection.
Select some images in the Article and save.
Delete all images and save. 
Values come back to say hello...

https://gyazo.com/c2fb1542f52c75a6811c14cb3d229091

**Comment by Bakual** [comment]
@laoneo I remember that we had this issue with chechboxes as well, but don't remember what we did to solve it.

**Comment by laoneo** [comment]
Yes it has something to do that the data is not sent to the server when it is empty I guess, but not sure.

**Comment by laoneo** [comment]
Please test #14795 which should solve this issue. Guess this issue can be closed as we have a pr.
