### ISSUE TITLE
[com_fields] Feature Request for Colour field

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14353]
In the Colour Field it´s only possible to select Hex values. Would be great to have the possibility to select also rgba and define this in the plugin settings.

![image](https://cloud.githubusercontent.com/assets/828371/23586810/d6b6d29a-019d-11e7-9a8b-050454ba79df.png)

**Comment by franz-wohlkoenig** [comment]
@maintaners: at this Point this kind of issue should get a Label "Enhancement" for 3.8 to have Energy on getting 3.7 solid and out.

**Comment by laoneo** [comment]
Guess this would require a new color field.

**Comment by ciar4n** [comment]
There is an existing option with the color field to set to an RGBA format... https://github.com/joomla/joomla-cms/pull/10129

**Comment by laoneo** [comment]
I would not close this one as the pr #14427 does default the $changeFormat field to false. So this must be activated in the color custom field then explicitly, which needs a code change.

**Comment by jjaracz** [comment]
@laoneo
I do it in that way because extensions which use only hex format and parse it, could crush when you try to set rgb or rgba format. It's suggestion from @Bakual (see comments in pr) and I agree with him :slightly_smiling_face:

**Comment by laoneo** [comment]
@jjaracz that's absolutely fine. But to properly integrate it into com_fields, we need to make some code changes in the color custom field plugin. That's why this issue will not be solved when your pr got merged. There is then still work needed on the com_fields side. That's why this issue should stay open.

**Comment by jjaracz** [comment]
@laoneo 
What changes ? Maybe I could do it in this pr.

**Comment by Bakual** [comment]
>  extensions could crush, what i mention before.

We are talking about a custom field here, not an extension setting (as specified in the XML file). We should add the option to allow more formats to the custom field so the administratpor setting up that field can decide if the picker should allow different formats or not.

**Comment by uglyeoin** [comment]
Should it/does it also accept HEX with transparency? https://gist.github.com/frankyonnetti/9400858

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 17th September 2017.

**Comment by laoneo** [comment]
This issue needs to stay open till #14427 is merged and then we can do this one here.

**Comment by dgrammatiko** [comment]
FWIW @C-Lodder is working on a new color field based on custom elements and probably this https://codepen.io/dgt41/pen/LjXQoP for joomla 4.

**Comment by dgrammatiko** [comment]
@laoneo merging #14427 might not be a great idea looking forward

**Comment by laoneo** [comment]
I don't mind. Will this color picker then have more output formats? If yes then this issue can stay open, if not we can close it.

**Comment by dgrammatiko** [comment]
It should support all the formats, RGB, RGBA, HEX, HSV, basically everything

**Comment by C-Lodder** [comment]
@laoneo - yes, it will.

**Comment by laoneo** [comment]
The lets close #14427 and we wait for Charlie's one. Whats the pr?

**Comment by C-Lodder** [comment]
There is no PR and won't be till probably next year. Bare in mind my PR will be for J4, not 3.x

**Comment by ghost** [comment]
#14427 should be closed?

**Comment by laoneo** [comment]
If @C-Lodder is going to create a new one, then yes. Here is the issue for the new one https://github.com/joomla-projects/custom-elements/issues/17.

**Comment by ghost** [comment]
thanks @laoneo

**Comment by brianteeman** [comment]
This should be closed. New features are not going in to J3 any more
