### ISSUE TITLE
[com_fields] Typo in plg_field_colour Field Description

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14352]
There is a u missing here:
Colo**u**r

![image](https://cloud.githubusercontent.com/assets/828371/23586786/2d0d2bea-019d-11e7-93d0-4d9a2f323716.png)

i can fix it later but i have actually to write something about that stuff, so just dropping everything in here until i´m finished with writing ;)

**Comment by Bakual** [comment]
The type of the field is "color", not "colour", so it's correct without "u".

**Comment by coolcat-creations** [comment]
I thought Joomla ist in en-GB and not en-US ?
If it´s really true that it´s color then all the coloUr have to be changed then?

**Comment by Bakual** [comment]
The language strings are en-GB, the code itself is whatever the develoepr wrote at that time. The color (form-)field exists for quite some time already and I think was the result from a GSoC project (done by some indian guy afair).
So there may be differences in spelling within code.

**Comment by mbabker** [comment]
The HTML5 form field is named "color" and IMO any reference to a color form field should follow the HTML5 specification, not your choice of English variation.

**Comment by infograf768** [comment]
Closing as expected behaviour. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14352">issues.joomla.org/tracker/joomla-cms/14352</a>.</sub>
