### ISSUE TITLE
[com_fields] Radio Field is designwise a "Switcher" UX

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14358]
https://gyazo.com/744f99b920ce81bab3d76d48be8bd6d5

The Radiofield does not that what a User expects. It´s of course nice Design and comes from all the Joomla fields. But then it should be maybe named switcher?

Also no idea how to define the red and green colors. There is noting in the Languagestring? Can someone lead me where to define it? Or can the colors be added into the radio/switcher options?

**Comment by Bakual** [comment]
The value "0" is red and the value "1" is green, the others blue I think. That is done somewhere in the template CSS.

**Comment by Bakual** [comment]
The styling itself comes from the edit class "btn-group" which is applied by default. If you change that to something else you get regular radio fields. Unfortunately removing the class doesn't work as it is specified as a default value which will come back next time you edit it.
We may remove that default value so by default it is a real radio if itis more helpful. I think that default value is there so the radios look like most other radios in the form.

**Comment by coolcat-creations** [comment]
Well, i like the design very much - just the User might expect something different. Please don´t remove the class. .... But: Can it be overridden somewhere by the user if he doesn´t use BS in Frontend?

**Comment by Bakual** [comment]
The class is specified in the field. Look at the "Options" tab. There is an "Edit Class" which by default contains "btn-group". This is the class used in the forms. The user can adjust that class to his needs.

**Comment by franz-wohlkoenig** [comment]
3rd button is blue in Fields (move Field).
![bildschirmfoto 2017-03-06 um 08 06 30](https://cloud.githubusercontent.com/assets/8235763/23599860/e036ddd2-0243-11e7-8910-3e5120042280.JPG)

To get 3rd Button blue template.css of protostar must be changed?

**Comment by Bakual** [comment]
I think that comes from the template.css, yes.

**Comment by franz-wohlkoenig** [comment]
@coolcat-creations let Issue open?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14358">issues.joomla.org/tracker/joomla-cms/14358</a>.</sub>

**Comment by brianteeman** [comment]
I am closing this as it appears to have been answered. If that is not correct it can always be re-opened
