### ISSUE TITLE
Router - links to ANOTHER Joomla Site

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14361]
Ok... here comes a really weird issue.
I have a lot of Joomla Installations to test on my localhost.
One is the pure joomla-cms staging repo and the other one is an installation where i make tests for my bookchapters. 

The one installation is called **Joomla CMS** the other one is called **Mein Template** 
On both sites there are articles that are called test. 

Now watch this Screen what is happening there...

https://youtu.be/if0U5_rYbvI

**Comment by coolcat-creations** [comment]
Turns out that no matter which alias the articles or the menuitems have, i cant use the installation joomla-cms anymore because i am always redirected to the other Joomla installation 👎

**Comment by Hackwar** [comment]
I can not confirm this. I have about 150 Joomla installations in paralell on my localhost and they all work fine. I'd guess that your host is somehow misconfigured.

**Comment by zero-24** [comment]
@coolcat-creations can you contact me via mail so we can look into the problem using skype or hangout? I can not confirm this too and i'm have also a lot of test installs ;)

**Comment by coolcat-creations** [comment]
Trying to figure out with @zero-24 what it was. I had to reinstall both Joomla! Sites to make it work again. Closing for now.
