### ISSUE TITLE
Automatic Core Updates

### ISSUE THREAD

**Issue by Simon-Davies** [joomla/joomla-cms#14367]
Could you please add the ability to perform core automatic updates to Joomla. Wordpress has this feature and it's something I feel would be beneficial to add to the CMS itself.

I know there are drawbacks to it but having the option would be nice, I've never personally had any issues with updates breaking my website or third party plugins in the last 3 years.

**Comment by photodude** [comment]
I suggest you read this thread on the CMS dev mailing group.
https://groups.google.com/d/msg/joomla-dev-cms/LlSaoXsksQM/1q1TdYKSAwAJ

**Comment by rdeutz** [comment]
often discussed, closing as duplicate

**Comment by photodude** [comment]
Some of the duplicate issues
https://github.com/joomla/joomla-cms/issues/11937
https://github.com/joomla/joomla-cms/issues/8749
