### ISSUE TITLE
[com_fields] label is not translateable when 2 or more Words

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14363]
Maybe i just miss something. At Joomladay Germany we tested successfully to translate the Labelstrings into other languages. The documentation says it´s not possible but i doubt because it worked once.

I tried UEBERSETZUNG_IST_TOLL, COM_FIELDS_UEBERSETZUNG_IST_TOLL, COM_CONTENT_FIELD_UEBERSETZUNG_IST_TOLL but nothing worked?

![image](https://cloud.githubusercontent.com/assets/828371/23589189/fec31ea8-01c8-11e7-9ff5-342ed33ba48b.png)

the language debug mode says UEBERSETZUNG_IST_TOLL would be the right value.
![image](https://cloud.githubusercontent.com/assets/828371/23589208/38dcfa14-01c9-11e7-8f1d-d5b5a5aefd22.png)

thanks

**Comment by Bakual** [comment]
Both label and description are translateable. Just tried with JYES and JNO as values for those fields (because that were the first strings I know exist for sure *gg*)

**Comment by coolcat-creations** [comment]
Thank you @Bakual i tested with one word and it works. 
If i test with two words and replace the spaces with underscores for the translation t´s not working. If i type in the Label with underscores it works also correctly. 

I thought that blanks would be normaly replaced with underscores. If not then i can close the issue.

**Comment by Bakual** [comment]
I think it has to be one work without spaces. Ideally ALL_UPPERCASED 😄 

I'm closing this then.
