### ISSUE TITLE
Double Translation of Fields Tab Label

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#14366]
### Steps to reproduce the issue

Enable language debug, go to the article edit page, view the fields tab's label

### Expected result

`**Fields**`

### Actual result

`??**Fields**??`

### System information (as much as possible)

N/A

### Additional comments

From the debug console, this appears to be where the second translation is happening:

```sh
# JROOT/libraries/cms/layout/file.php

FIELDS="**Fields**"
```

**Comment by infograf768** [comment]
Will make patch.

**Comment by infograf768** [comment]
Closing as we have a patch

https://github.com/joomla/joomla-cms/pull/14369<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14366">issues.joomla.org/tracker/joomla-cms/14366</a>.</sub>

**Comment by infograf768** [comment]
@mbabker 
Alas, the debug Console is not very helpful.
