### ISSUE TITLE
[com_fields] Field URL Misleading error Message when typing in wrong URL scheme

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14360]
This Error message needs improvement since the solution is not to type in url in the beginning of the field... + i think it should be Scheme not Schema ?

![image](https://cloud.githubusercontent.com/assets/828371/23587822/1af98d38-01b4-11e7-9da7-dcd19c690d63.png)

**Comment by zero-24** [comment]
@coolcat-creations what did you choose in the plugin / field params as schema?

**Comment by coolcat-creations** [comment]
The selected scheme is url... But for https ftp etc it´s right that https has to be in the beginning of the field. For url scheme this error message does not apply.

**Comment by brianteeman** [comment]
Found the problem
url is not a valid scheme type and should not have been an option

I will prepare a PR for this and close here when i have done it

**Comment by brianteeman** [comment]
Closed see #17631
