### ISSUE TITLE
Getting Error for Login after upgrade 3.4.8 to 3.6.5

### ISSUE THREAD

**Issue by ismaelhaider** [joomla/joomla-cms#14365]
### Steps to reproduce the issue
After login it shows Too many redirects and show me url

https://qatar333.com/index.php?option=com_users&task=user.login&Itemid=1

I am using multilangage site, I am stuck in critical situation, Please help me to fix this

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding.
