### ISSUE TITLE
[com_fields] Automatic Display in User Context doesn´t apply in this context

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14377]
![image](https://cloud.githubusercontent.com/assets/828371/23604755/57e8bee8-025a-11e7-9c61-7252de301746.png)

Maybe i´m missing something but there is no after Display, before Display and After Title in User?
Can this field be removed in User-Context?

Also if i set this option to no, the field is still displayed.

**Comment by laoneo** [comment]
Difficult to solve.

**Comment by coolcat-creations** [comment]
Idea from a nondev :) can the showon parameter help?

**Comment by laoneo** [comment]
Not really, we need to do some kind of callback to the extension if it supports the automatic display events. Another thing the extension dev needs to take care of when she wants to integrate com_fields into their extension.

**Comment by AlexRed** [comment]
Same problem also for Contact Field.
For me we need at least write in the tooltip that it is only for article and not for Users and Contact.

**Comment by mbabker** [comment]
The tooltip shouldn't say that.  To "really" fix this the field would have to be aware of the supported plugin events for a context.  It is not restricted/available to articles only, it just so happens if the core components only articles supports all of the listed contexts.

**Comment by AlexRed** [comment]
Fantastic, can your fix hide the "Automatic Display" parameter only in user and contact field ?

**Comment by mbabker** [comment]
It's basically what @laoneo last comment says.  When generating that field, it would have to be smart enough to call into the "owning" extension for a context to figure out what events it displays and build the list that way versus the current hardcoded list that exists now.  So programmatically once the callback thing is sorted out it's an easy fix, problem is getting to that point isn't easy.

**Comment by AlexRed** [comment]
And in this mode I hope we can set different default "permission" for a context. 
Allowed "Edit Custom Field Value" for User and Contact Mail fields  :)

**Comment by laoneo** [comment]
You can change the install script, that com_contact will have different default permissions. That's doable.

**Comment by AlexRed** [comment]
Please @laoneo help me to change the install script, that com_contact will have Allowed "Edit Custom Field Value" default "permission" and help me to set the contact field for "Mail" by default. If we fix it for me we can keep contact custom field in Joomla 3.7.0.
But for me we need to hide in Joomla 3.7.0 the users custom field (like for the new router problems), the bugs 15194 and 13601 make it unusable. And restore it in Joomla 3.7.1 if we fix it.

**Comment by joeforjoomla** [comment]
@AlexRed proposed a quite dramatic solution... however i agree with him that the release can't take place until everything is stable. Me and other people can't understand why the RC1 and RC2 is going on to be released even if problems are still present. It's still not time of an RC at all!

**Comment by rdeutz** [comment]
because software is never bug free, you will never release anything when you wait till all problems are fixed

**Comment by AlexRed** [comment]
Nobody ever said that must be resolved before all problems. But the most important yes. When the administrator active the user all the data in the profile custom field are erased, and also the user can't find the profile custom field in the edit profile page in control panel. For me make it unusable.
The other problems in custom field can remain (14049, 15173, 14377, 15294, ecc..)

**Comment by laoneo** [comment]
@AlexRed the problem with com_users is that it behaves in many places totally different, then any other extension. Rewriting that takes a big amount of time.

**Comment by AlexRed** [comment]
Please @laoneo help me to change the install script, that com_contact will have Allowed "Edit Custom Field Value" default "permission" and help me to set the contact field for "Mail" by default.
About the com_users  we can hide in Joomla 3.7.0 the users custom field (like for the new router problems) if rewriting that takes a big amount of time. And restore it in Joomla 3.7.1 or later if we fix it.

**Comment by mbabker** [comment]
Please stop comparing the handling of the router to any other action.  To be blunt, that decision was more politically driven than a code functionality decision.  The fix for any issue is not "hide the feature and re-enable when working", that should only be an option considered for critically broken code and unless I'm mistaken this is not critically broken.

**Comment by laoneo** [comment]
Agree @mbabker.

@AlexRed honestly I don't understand what you want to achieve. com_contact has that permission already, so there is no change needed.

**Comment by AlexRed** [comment]
Sorry for my bad english, now I try with some images to explain:

have Allowed "Edit Custom Field Value" default "permission"
![default-mail](https://cloud.githubusercontent.com/assets/1362388/25062127/de7f122c-21bd-11e7-9dcf-d264f7c3ddcd.png)

set "Mail" by default
![default-mail](https://cloud.githubusercontent.com/assets/1362388/25062125/d73bed50-21bd-11e7-94be-afccdfdb19b6.png)

**Comment by Bakual** [comment]
@laoneo I think he wants to have different default behaviors for the com_contact.mail and com_contact.contact contexts. Eg the mail one should be allowed to edit by default and the contact one should not.

But the way our permission system works, that is not something we can or even should do.

**Comment by laoneo** [comment]
@Bakual I guess this is possible, with more sections in the access.xml file.

@AlexRed now I got the use case, you want to enable it initially for the Public user groups. It makes sense for first time users, but I'm not sure if this would be a good decision from security point of view.

**Comment by AlexRed** [comment]
and set "Mail" by default ?

**Comment by laoneo** [comment]
That can be done, but when I would go to the contacts component, I personally would expect that custom fields are shown for the contacts by default and not the form. But this is my personal opinion.

**Comment by AlexRed** [comment]
can add new custom fields in the mail form is a fantastic solutions now. For me the users want it and it is not so simple to understand the we need to change the dropdown. All the users I ask to do a new contact form with some new field have failed.

**Comment by brianteeman** [comment]
And if you change the default to mail you will say
All the users i asked to do a new contact details with some new field have failed.

The problem is not what is the default. The problem is that switching the context is not obvious at all and is a new concept for Joomla so it is unfamiliar

**Comment by laoneo** [comment]
What can we do to make it more obvious?

**Comment by brianteeman** [comment]
I really don't know. I've been thinking about it for a while.

The only thing i came up with (which is not great) is to display a message
at the top (below the filters) to indicate which context you are in and
that you can change it from the filter box. Something like the blue message
you get at the top of some of the option tabs.

(Not at my computer for a few hours to do a test mockup)

**Comment by AlexRed** [comment]
for example split out in TAB, like in the new Editor - TinyMCE settings for the 3 SET.
The 3 tab would be visible with the 3 options

**Comment by brianteeman** [comment]
I am not convinced changing a drop down select to a tab is much better but it is more consistent with other UI  patterns in Joomla.

**Comment by Bakual** [comment]
> I guess this is possible, with more sections in the access.xml file.

I fear that would break more stuff than it helps. And you still would have to set public to default for that section and action which really isn't something I would do. ACL should be denied by default in all cases, that's how ACL works.

**Comment by laoneo** [comment]
I was talking about having different permissions per context and not just from component to the field.

**Comment by Bakual** [comment]
> I was talking about having different permissions per context and not just from component to the field.

That's how I understood you, yes. But it's not as easy as it may sound and would need several adjustments all around the (com_field) code to take care of that special case.

**Comment by laoneo** [comment]
Please test #15915 which should fix that issue. At the end of the day it was not so a hard and opens the door for new possibilities.

**Comment by laoneo** [comment]
Guess can be closed?
