### ISSUE TITLE
[com_fields] Editorbutton Modal shows fields that are not assigned to this Article

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14379]
![image](https://cloud.githubusercontent.com/assets/828371/23605912/d8466f1e-025e-11e7-8b46-1f3f2ae75780.png)
or
The Modal also shows fields that don´t belong to the article category. 

This is maybe a known issue, but can here only be fields shown that can be really displayed in the article? If not feel free to just close this.

**Comment by Bakual** [comment]
The view supports filtering for fields assigned to a specific category, but would then hide all fields that are shown in all categories. Which isn't what you need.

It's certainly possible to do somehow and I see that it could be helpful but it's probably not a simple request as it needs changes in the fields model.

**Comment by laoneo** [comment]
I leave that up to you @Bakual :smile:

**Comment by franz-wohlkoenig** [comment]
reminder @Bakual <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14379">issues.joomla.org/tracker/joomla-cms/14379</a>.</sub>

**Comment by Bakual** [comment]
I don't have that on my to-do list. So if someone wants to take a go at it...

**Comment by pepperstreet** [comment]
Following... 
Makes sense from a UX point-of-view. Probably there is a technical way to get and pass the current article's category to the search filter!? So the initial filter is applied automatically.

**Comment by jwaisner** [comment]
As feature additions are not available for J3 now, closing this. Please check J4 to see if this feature request may apply.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14379">issues.joomla.org/tracker/joomla-cms/14379</a>.</sub>
