### ISSUE TITLE
[com_fields] Useless Fieldset description?

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#14371]
@laoneo @Bakual 

While making the PR https://github.com/joomla/joomla-cms/pull/14369 I found out that although the Label is useful for the tabset, I could not find a usage for the Description.

Do we really need to keep that in? It looks to me that Note is enough here.
xml, db column + code in the helpers/fields.php

**Comment by coolcat-creations** [comment]
Yes, it´s the tooltip of the field

**Comment by infograf768** [comment]
The only usage I could see is adding in the tmpl as translatable (as Note is not).
```php
									<span class="small break-word">
										<?php if ($item->note) : ?>
											<?php echo JText::sprintf('JGLOBAL_LIST_NOTE', $this->escape($item->note)); ?>
										<?php endif; ?>
									</span>
									<?php if ($item->description) : ?>
										<div class="small">
											<?php echo JText::_($this->escape($item->description)); ?>
										</div>
									<?php endif; ?>
```

to get something like

![screen shot 2017-03-06 at 09 50 39](https://cloud.githubusercontent.com/assets/869724/23602783/67b3dd24-0252-11e7-9199-7ad646c65f1f.png)

when the description is a lang string constant and we do have that string in the language.
For above:
![screen shot 2017-03-06 at 09 51 56](https://cloud.githubusercontent.com/assets/869724/23602822/95d18dd2-0252-11e7-9813-28ac698dcc7a.png)

string:
`COM_CONTENT_FIELDS_ARTICLE_DESC="Description du champ"`

**Comment by infograf768** [comment]
> Yes, it´s the tooltip of the field

Nope. I am talking about the Field Group `Fieldset` and not the field.

**Comment by coolcat-creations** [comment]
Yes i edited my reply immediately when i saw it, can you recheck my post above?

**Comment by infograf768** [comment]
Ah... Well hidden feature... Closing.
