### ISSUE TITLE
[com_fields] Fieldset (Group) Description for User doesn´t appear in frontend

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14372]
When you type in a Description of a Fieldgroup:
![image](https://cloud.githubusercontent.com/assets/828371/23605453/11193ad0-025d-11e7-8488-2201b29d9c24.png)

this description appears in the Backend:
![image](https://cloud.githubusercontent.com/assets/828371/23605477/267a4cfc-025d-11e7-91f1-8b03c5a5fa0f.png)

But in Frontend the Description does not appear:
![image](https://cloud.githubusercontent.com/assets/828371/23605497/3d8e9920-025d-11e7-8a6a-789dfc94125a.png)

Edit: for Article it´s working

**Comment by laoneo** [comment]
For me it appeared when I edit a user on the front
![image](https://cloud.githubusercontent.com/assets/251072/23659346/20d533b8-0346-11e7-9826-0ca0b52cffe9.png)

But the description is not shown on the profile page. I fixed that in pr #14406.
