### ISSUE TITLE
[com_fields] submenu is missing for com_contact

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14376]
![image](https://cloud.githubusercontent.com/assets/828371/23604034/b693f938-0257-11e7-8f06-3c66d69b5cae.png)

Since the fields are shown in the Admin Menu for com_user and com_content they should be shown also in the contact submenu.

**Comment by mbabker** [comment]
Duplicate of https://github.com/joomla/joomla-cms/issues/12658

**Comment by laoneo** [comment]
Is this a duplicate of #12658?
