### ISSUE TITLE
[com_fields] Category doesn´t apply to Fields in Usermanager

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14373]
While Fields in com_content and com_contact could be assigned to specific Categories this is not possible in User. The Subline "Category:All" below the title should be removed here.

![image](https://cloud.githubusercontent.com/assets/828371/23605391/d3e5f6a8-025c-11e7-85c1-3f753a0a3967.png)

**Comment by laoneo** [comment]
Please test #14405, which should fix that issue.
