### ISSUE TITLE
[com_fields] Feature Request for text and textarea fields

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14374]
Can here a max-lenght field be added easily ? I think it´s very useful for any usecase...

thanks!

**Comment by laoneo** [comment]
Just to confirm, it is the maxlength parameter here https://docs.joomla.org/Text_form_field_type?

**Comment by coolcat-creations** [comment]
Yes i think so! thanks! :-)

**Comment by coolcat-creations** [comment]
is this possible @laoneo ? :)

**Comment by laoneo** [comment]
Yes it is.

**Comment by coolcat-creations** [comment]
@laoneo just tried to help and add it myself, but no idea which files has to be changed.
For  now i added the parameter here: /plugins/fields/text/params/text.xml
But where do i call it?

**Comment by laoneo** [comment]
You was on the right track. The parameters from the core form fields can be added on the params and the plugin xml file.

Check out pr #14458 which adds the max length parameters to the text and textarea fields. If you want to add more parameters by yourself you can use that pr as template. Just ping me on glip when you need help for another parameter.

Guess this issue can be closed as we have a pr.
