### ISSUE TITLE
[com_fields] Field that is assigned to a category in context category is shown everywhere

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14375]
The first field is assigned to the Category "Bildauswahl"

![image](https://cloud.githubusercontent.com/assets/828371/23603576/0e8c2518-0256-11e7-8463-93a2c7f595ee.png)

By creating a Category with another Parent the field ist still shown:
![image](https://cloud.githubusercontent.com/assets/828371/23603636/3b53df50-0256-11e7-871d-bc36f5774237.png)

![image](https://cloud.githubusercontent.com/assets/828371/23603690/67f9f09e-0256-11e7-8217-a206f2895e6b.png)

**Comment by franz-wohlkoenig** [comment]
Can't confirm: Using Fields in Fields-Group or not Fields are shown in all Categorys (if set so) or a specific Categorie.

**Comment by coolcat-creations** [comment]
I just explain my Clickflow more detailed:
1) Create Field A  in context category and assign it to Category A
2) Create Field B in context  category and assign it to all categories
3) Create Category B - both fields are shown in the category

**Comment by franz-wohlkoenig** [comment]
Confirmed (was on "Article" not "Category"-Dropdown).

**Comment by Bakual** [comment]
@laoneo Can you have a look at this? You know best how the category implementation is done.

**Comment by laoneo** [comment]
Yes will have a look, probably tomorrow.

**Comment by coolcat-creations** [comment]
thanks! @laoneo - Same for Contact Categories by the way

**Comment by laoneo** [comment]
Please test #14399, which should fix it.
