### ISSUE TITLE
[com_fields] Location of Field Layouts - is it possible to move to JLayouts?

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14381]
If you want to override how fields are rendered you have to move the file from the component folder instead of the layout folder

![image](https://cloud.githubusercontent.com/assets/828371/23608578/50c02e20-026a-11e7-9ce0-b0b476d08b9a.png)

Is it possible to move it into the layouts folder to be consistent in the way where the user finds the layouts?

**Comment by mbabker** [comment]
Not all layouts belong in the global `/layouts` folder.  The same as not all component layouts belong in a single global directory.

There is actually a default logic to this.  It enables component specific overrides of layouts within the template, followed by global overrides of layouts in the template, then component specific overrides of layouts within the component directory, then finally using the default `/layouts` directory.

If the `com_fields` component is doing the actual layout rendering, the layouts are in the correct place.  If the layout rendering is coming from a library class (something in the `/libraries` directory), then they should be moved.

**Comment by coolcat-creations** [comment]
Ok thank you @mbabker for explaining it detailed. Then i close this issue.
