### ISSUE TITLE
[com_fields] While content fields uses layout of com_fields, user has it´s custom output

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14382]
The field Layout is here: /components/com_fields/layouts

But it doesn´t apply to the Fields that are shown in the Userprofile.
The code, that defines how the fields are rendered is directly written in the view here: /templates/protostar/html/com_users/profile/default_custom.php

Is this correct?
_Please close this issue directly if you think it´s ok like that. ;)_

**Comment by laoneo** [comment]
Yes, the user component works differently than the rest. If it is ok, I don't think so. But it would basically require a whole rewrite of com_users where I don't think so somebody does volunteer to do that. Similar problem to #13601.

**Comment by brianteeman** [comment]
For the reasons stated above I am closing this
