### ISSUE TITLE
[com_fields] Show User Custom Fields parameter in Contact is empty but fields are shown

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14392]
There is an Option in the Menuitem and in the contact If **USER** custom fields should be shown.
When the contact is connected to the user the custom fields of the user are automatically shown in a slider. But there is no possibility to turn it off.

The Parameterfield "Show user custom fields" is not filled. But despite that, the user customfields are displayed.

![image](https://cloud.githubusercontent.com/assets/828371/23626385/fca0be84-02ac-11e7-88bb-952dc097c9ef.png)

![image](https://cloud.githubusercontent.com/assets/828371/23626408/170a5910-02ad-11e7-9b18-e8f8edc725ac.png)

**Comment by laoneo** [comment]
Please test #14392 which removes the default value All in the contact options.

**Comment by franz-wohlkoenig** [comment]
@laoneo #14392 is this Issue.

**Comment by jeckodevelopment** [comment]
He means https://github.com/joomla/joomla-cms/pull/14407.
Closing as we have a PR to test.
Thanks
