### ISSUE TITLE
Frontend: Insert Image don't work

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14397]
### Steps to reproduce the issue
Select a Intro- or Full-Article-Image at Frontend, after Click on Image nothing happens.
### System information (as much as possible)
Joomla! 3.7.0-rc1
macOS Sierra, 10.12.3
Firefox 51.0.1, Safari 10.0.3
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by dgt41** [comment]
@franz-wohlkoenig is there any error logged in browsers console?

**Comment by franz-wohlkoenig** [comment]
All empty:
![bildschirmfoto 2017-03-07 um 07 26 14](https://cloud.githubusercontent.com/assets/8235763/23644382/657be884-0307-11e7-9c66-59776a392ab9.JPG)

**Comment by franz-wohlkoenig** [comment]
After Click on `Insert` Image is loaded. So the green Symbol is missed.

**Comment by franz-wohlkoenig** [comment]
Modal looks different:

#### Frontend:
![fe](https://cloud.githubusercontent.com/assets/8235763/23644538/146f2b80-0308-11e7-9cc7-ab6526aa39de.JPG)
#### Backend:
![bildschirmfoto 2017-03-07 um 07 31 17](https://cloud.githubusercontent.com/assets/8235763/23644548/20e926ea-0308-11e7-81a3-744b8ccfbdc2.JPG)

**Comment by dgt41** [comment]
Ok, I got it now.
@ciar4n can you copy the styles changes you've made for the com_media also to `/media/media/css/popup-imagemanager.css`

**Comment by ciar4n** [comment]
@franz-wohlkoenig @dgt41 Thank you!

PR created.. #14398
