### ISSUE TITLE
[com_fields] Fieldgroup delete bugs.

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14394]
### Steps to reproduce the issue
1) Create a Fieldgroup in com_contact for each context
2) Create a Field for each context and assign it to the Fieldgroup
3) Delete the Fieldgroups one by one and see what happens

### What happened at my test:
1) Deleted a Fieldgroup from Context "Mail" - The Field is still there (good) but the Field Overview displays still the old Fieldgroup:
Mind that the displayed group is deleted:
![image](https://cloud.githubusercontent.com/assets/828371/23627465/3442856c-02b1-11e7-875f-6e9c517a4d1d.png)

2) Wanted to reproduce the issue and deleted the Fieldgroup from Contact context. It seemed first that the Field was deleted as well (Message: No Results)

3) Since i had two different behaviours i tested and deleted the Fieldgroup from Contactcategory context. Same happened as in Step 1)

4) Created a new fieldgroup to test again behaviour in step 2 and then the old field, which first seemed to be deleted, appeared again - Mind that More Information is the only existing group.

![image](https://cloud.githubusercontent.com/assets/828371/23627573/9efaee80-02b1-11e7-94c1-77b165f3c1ae.png)

5) Deleting Trash solves it but i think that the trashed fieldgroup should not be shown in the Field overview

**Comment by Bakual** [comment]
As long as the group is only trashed and not deleted, the assignment is still intact. We can discuss to somehow mark the group as deleted in that list (eg use strikethrough or put an icon to it), but I wouldn't remove the name.

**Comment by Bakual** [comment]
I'll have to see how that is done there.

**Comment by laoneo** [comment]
When you trash a category, the articles which belong to the category do still show the category they are assigned to. So the current behavior is similar to articles.

**Comment by franz-wohlkoenig** [comment]
@coolcat-creations hold Issue still open?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14394">issues.joomla.org/tracker/joomla-cms/14394</a>.</sub>

**Comment by Quy** [comment]
@coolcat-creations OK to close?

**Comment by coolcat-creations** [comment]
If possible it would be good to show the category in a different style.

**Comment by jwaisner** [comment]
Closing at it has been noted as expected behavior. If there is a change you would like to see it will need to be in J4. Please review J4 to see if it will meet the ask you have for a feature.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14394">issues.joomla.org/tracker/joomla-cms/14394</a>.</sub>

**Comment by widmann-it** [comment]
Sorry, I don't understand why the issue was closed. This is a bug in version 3.x . Version 4.x is not even visible on the horizon. It makes no sense to simply close the 3.x issues here. 
It would rather move the issue as a 4.x milestone.

**Comment by coolcat-creations** [comment]
I think the biggest objective for Joomla 4 should be to increase User Experience. Please do not trash such reports, they might be helpful to work on those bugs.
