### ISSUE TITLE
[4.0] Add new module > SQL error

### ISSUE THREAD

**Issue by JanKrohn-Khalibre** [joomla/joomla-cms#14401]
### Steps to reproduce the issue

Testing on the 4.0.0-dev nightly branch.

New module: footer (can be replicated on other modules as well, but not all of them)

Title: Footer
Position: footer

Screenshot attached![screen shot 2017-03-07 at 10 54 40](https://issues.joomla.org/uploads/1/4086c5bc81481cb6313559750a1b23cc.png)

### Expected result

New footer module added

### Actual result

Error
Save failed with the following error: Field 'content' doesn't have a default value

### System information (as much as possible)

PHP Built On	Linux server.heidoc.net 2.6.32-042stab112.15 #1 SMP Tue Oct 20 17:22:56 MSK 2015 x86_64
Database Version	5.5.5-10.1.21-MariaDB
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.1.2
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 4.0.0-dev dev [ Amani ] 8-February-2017 14:11 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

### Additional comments

Fresh installation, not updated

**Comment by C-Lodder** [comment]
@yvesh @laoneo any ideas on this?

**Comment by zero-24** [comment]
It should be about this line: https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/joomla.sql#L1474 as there is no value for `content` in that module and the strict mode of mysql fires here. I would expect that we need to set a default value for the `content` field on the save method.

**Comment by laoneo** [comment]
I got similar errors when discovering extensions in Joomla. Should the default value not being defined in the table schema?

**Comment by franz-wohlkoenig** [comment]
Can't confirm:
![bildschirmfoto 2017-03-09 um 09 48 17](https://cloud.githubusercontent.com/assets/8235763/23742573/aeb02d6a-04ad-11e7-8ce2-e182f3d62b6a.JPG)
### System information (as much as possible)
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by joomdonation** [comment]
Could not re-procedure the issue. The error message indicate that the content field of #__modules doesn't have default value. However, looking at this https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/sql/mysql/joomla.sql#L1472 , I see that the content field has default value already, so this issue should not happen

**Comment by JanKrohn-Khalibre** [comment]
Interesting... In my db the content field has no default value.

![image](https://cloud.githubusercontent.com/assets/5867975/23825412/060853e8-06bc-11e7-8520-9e7ffc8a39d5.png)

I've certainly not tampered with the db after the initial installation.

**Comment by ciar4n** [comment]
I can confirm this.

Only on modules discovered. Same modules save fine if installed via installer.

**Comment by csthomas** [comment]
In mysql "BLOB/TEXT" column can't have a default value, except NULL:).

https://stackoverflow.com/questions/3466872/why-cant-a-text-column-have-a-default-value-in-mysql

Default value does not work.
The solution is to add empty string in php code or allow column to be NULL.

**Comment by C-Lodder** [comment]
This doesn't appear to be an issue anymore. Saving a new module or discovering one both work.

@franz-wohlkoenig

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14401">issues.joomla.org/tracker/joomla-cms/14401</a>.</sub>

**Comment by ciar4n** [comment]
Note this issue still existed up to a few days ago. The issue is only present on 'Discovered' extensions.

**Comment by ciar4n** [comment]
I'm still getting this issue with discovered modules

**Comment by ghost** [comment]
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14401">issues.joomla.org/tracker/joomla-cms/14401</a>.</sub>

**Comment by brianteeman** [comment]
I cannot replicate this on new or discovered modules

@ciar4n It seems to be only you. Maybe it is an issue with the module. I am going to close this for now but if you still have an issue can you please re-open it and share the module

**Comment by laoneo** [comment]
Does this pr help https://github.com/joomla/joomla-cms/pull/19836 ?

**Comment by ghost** [comment]
J4 alpha 3  I solved this in a simple way

ALTER TABLE `#__modules` CHANGE `content` `content` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '';<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14401">issues.joomla.org/tracker/joomla-cms/14401</a>.</sub>
