### ISSUE TITLE
[com_fields] Restrictions of the group are not inherited to the fields

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14419]
The Field Group Permissions are all set to disabled (while the fields are set to allowed). Seems that the Fields don´t inherit the Field Group Permissions. 

![image](https://cloud.githubusercontent.com/assets/828371/23679868/8027d8a0-0389-11e7-8e48-e7ea439f942a.png)

![image](https://cloud.githubusercontent.com/assets/828371/23679807/54441ee2-0389-11e7-95f5-a86557423f5a.png)

**Comment by Bakual** [comment]
> The Field Group Permissions are all set to disabled 

They aren't set to "Denied". They are set to "Inherited". Which means it's still possible to set children (the fields) to "Allowed".
If you set the fieldgroup to "Denied", then the field can't be "Allowed" anymore.

That's how the ACL works.

**Comment by coolcat-creations** [comment]
Same issue with Denied:

![image](https://cloud.githubusercontent.com/assets/828371/23681055/b844f264-038d-11e7-9c68-e2b39ebd8991.png)

![image](https://cloud.githubusercontent.com/assets/828371/23681071/ca72c3a8-038d-11e7-8a0c-d900485d70a8.png)

**Comment by Bakual** [comment]
Hmm, that sounds like a broken asset relation or something. When I try it, it works as expected.
Are those fields "old" ones you created like a month ago? Or did you create field and fieldgroups just recently for that test? I ask because ACL was broken and got fixed with https://github.com/joomla/joomla-cms/pull/13676 on 2017-01-22. If your fields are from that time, they may have broken ACL assets and you would need to recreate them.

**Comment by coolcat-creations** [comment]
I had to reinstall everything 3 days ago due to the strange Routing error... It´s all fresh :) I try if it happens only there...

**Comment by Bakual** [comment]
The only ACL setting which matters (or at least should matter) in that context is the "Edit Custom Field Value" one. The others are used when it comes to creating or editing the field itself, not its value.
That should make testing a bit easier.

What does the calculated settings column show for the field?

**Comment by franz-wohlkoenig** [comment]
@coolcat-creations @Bakual keep this issue open?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14419">issues.joomla.org/tracker/joomla-cms/14419</a>.</sub>

**Comment by Bakual** [comment]
I couldn't replicate it, so I have no clue where that may come from.

**Comment by brianteeman** [comment]
I am closing this at this time as it has not been replicated. It can always be reopened if required
