### ISSUE TITLE
Problem with new jalali calendar in joomla 3.7 beta

### ISSUE THREAD

**Issue by ghasemy50** [joomla/joomla-cms#14411]
### Steps to reproduce the issue
you can check all sections that have calendar in persian language.
install Persian language and test a section that have calendar, like modules

### Expected result
show jalali calendar correctly

### Actual result
show jalali calendar not correctly

### Additional comments
before release stable version of joomla 3.7 please resolve this problem.
thank you

**Comment by Bakual** [comment]
@dgt41 Can you have a look? It looks indeed broken a lot.

**Comment by dgt41** [comment]
the css part you mean or the functional?

**Comment by Bakual** [comment]
I think there is at least some functional stuff broken:

![persian](https://cloud.githubusercontent.com/assets/1018684/23677548/db5bb56a-0380-11e7-9332-20722415e6f5.PNG)

**Comment by dgt41** [comment]
Do they have in their language file the translate options?

**Comment by Bakual** [comment]
I tested with the one available from the backend. I have no clue what they have in their 3.7.0. Maybe @infograf768 knows more.

But even if that is missing in their pack, shoudn't it then fall back to the english format? That's how our language strings usually work.

**Comment by dgt41** [comment]
Ok found it: their missing the `<calendar>jalali</calendar>` in their xml file. After that everyhting works as usual. Can you ask them to release a new version of their language with the update values for the xml?

![screen shot 2017-03-07 at 23 37 39](https://cloud.githubusercontent.com/assets/3889375/23679056/38ab1b4e-038f-11e7-84e5-f98c81d0f540.png)

**Comment by dgt41** [comment]
@zero-24 there is nothing wrong with the calendar, the error comes from their old localisation files, so no release-blocker here. Maybe force them to release an update with only the missing part of the xml to make sure that people won't get into this screen ever!

**Comment by zero-24** [comment]
I have just removed the label and the milestone ;)

![image](https://cloud.githubusercontent.com/assets/2596554/23679700/09ffb4cc-0389-11e7-91dd-9ed1e696d119.png)

So we can close here if we hear back from Thomas / the TT ;)

**Comment by dgt41** [comment]
It's getting late...
I really like the idea that they would release a minor update to their language pack with only the missing part of the xml, but up to them and Thomas

**Comment by Bakual** [comment]
They will release it when 3.7.0 is released. That is standard procedure. Doesn't make much sense to release it now since nothing is broken on a released version yet. 😄 

@ghasemy50 Can we close this issue as it is something that has to be done on language pack side?

**Comment by ghasemy50** [comment]
thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14411">issues.joomla.org/tracker/joomla-cms/14411</a>.</sub>

**Comment by ghasemy50** [comment]
i'm tested it ,but after save , date has been deleted from date field.

in previous versions of joomla , date field value was converted to gregorian , then it was saving.

i think now it is saving jalali date and have problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14411">issues.joomla.org/tracker/joomla-cms/14411</a>.</sub>

**Comment by dgt41** [comment]
@ghasemy50 the new calendar is also doing the same, converts the date to gregorian just before the form submit. what was your component that failed?

**Comment by ghasemy50** [comment]
![jalali calendar problem](https://cloud.githubusercontent.com/assets/11821038/23703272/571ea61a-0414-11e7-957e-f099fd38bfa9.png)
all readonly fields are correctly work. 
but all date fields that have calendar box on save, not convert to gregorian date and after save are show field blank.
thanks.

**Comment by infograf768** [comment]
> I really like the idea that they would release a minor update to their language pack with only the missing part of the xml, but up to them and Thomas

mig already asked them. will make sure a new pack is released to cover the issue in the mean while

**Comment by dgt41** [comment]
@ghasemy50 I'm guessing that it fails due to missing strings in your language:
```php
DATE_FORMAT_CALENDAR_DATE="%Y-%m-%d"
DATE_FORMAT_CALENDAR_DATETIME="%Y-%m-%d %H:%M:%S"
DATE_FORMAT_FILTER_DATE="Y-m-d"
DATE_FORMAT_FILTER_DATETIME="Y-m-d H:i:s"
```
PS. These are from en-GB, and should reflect the local settings for Persia.

**Comment by infograf768** [comment]
@dgt41 
i don't think so. will test later

**Comment by ghasemy50** [comment]
i added it in fa-ir.ini file but not solved.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14411">issues.joomla.org/tracker/joomla-cms/14411</a>.</sub>

**Comment by ghasemy50** [comment]
this code not need to convert to jalali date.
thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14411">issues.joomla.org/tracker/joomla-cms/14411</a>.</sub>

**Comment by dgt41** [comment]
@ghasemy50 can you test this: https://gist.github.com/dgt41/c970c43037303da465996acc94f2c5c4

**Comment by ghasemy50** [comment]
thanks , Where do I put it?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14411">issues.joomla.org/tracker/joomla-cms/14411</a>.</sub>

**Comment by dgt41** [comment]
Just replace `media/system/js/fields/calendar.min.js` and try it

**Comment by ghasemy50** [comment]
thank you very much,
it's ok.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14411">issues.joomla.org/tracker/joomla-cms/14411</a>.</sub>

**Comment by infograf768** [comment]
@Fedik @dgt41 
I confirm the issue.
After save whatever was entered in "Finish Publishing" and "Created date" displays the field empty.

**Comment by infograf768** [comment]
Release Blocker!

**Comment by dgt41** [comment]
@infograf768 can you try https://github.com/joomla/joomla-cms/issues/14411#issuecomment-285046173

**Comment by infograf768** [comment]
On it

**Comment by infograf768** [comment]
It solves the issue here. :
I am now uploading an improved Persian pack with the right xml

**Comment by dgt41** [comment]
Excellent, I'll try to fix also https://github.com/joomla/joomla-cms/issues/14341 and then do a PR for both.

**Comment by ghasemy50** [comment]
hi again
just a tip:
'fa-ir.js' file in `\media\system\js\fields\calendar-locales` have a bad translate.
exit parameter is translated to 'ستن' , good translate is 'بستن'.
please correct it in joomla 3.7 stable , thank you
