### ISSUE TITLE
Postgresql: invoking the styles menu in backend shows an error

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#14425]
### Steps to reproduce the issue
In backend go to extensions > template > styles and you will get this error:

FEHLER: Spalte »l.sef« muss in der GROUP-BY-Klausel erscheinen oder in einer Aggregatfunktion verwendet werden LINE 1: ..._id, l.title AS language_title, l.image as image, l.sef AS l... ^ FEHLER: Spalte »l.sef« muss in der GROUP-BY-Klausel erscheinen oder in einer Aggregatfunktion verwendet werden LINE 1: ..._id, l.title AS language_title, l.image as image, l.sef AS l... ^ FEHLER: Spalte »l.sef« muss in der GROUP-BY-Klausel erscheinen oder in einer Aggregatfunktion verwendet werden LINE 1: ..._id, l.title AS language_title, l.image as image, l.sef AS l... ^

**Comment by wilsonge** [comment]
Closing as we have a PR
