### ISSUE TITLE
User profile plugin: Empty tab in admin when all fields except TOS are disabled

### ISSUE THREAD

**Issue by Spudley** [joomla/joomla-cms#14420]
I am using the User Profile plugin to give me a TOS checkbox, but I am not using any of the other profile fields so I have disabled them.

### Steps to reproduce the issue

* Enable the User Profile plugin.
* In the plugin config, disable all the fields except for Terms Of Service.

### Expected result

* The user edit form on the admin panel does not need to display the "User Profile" tab, since there are no profile fields.

### Actual result

* The "User Profile" tab is displayed, but is completely empty.

### System information (as much as possible)

* Joomla 3.6.5
* Centos 7
* PHP 5.6

### Additional comments

Ideally the solution to this will be to drop the tab if there are no displayable profile fields.

An alternative solution would be to add a text/read-only field to the tab showing that the user has accepted the Terms of Service.

**Comment by franz-wohlkoenig** [comment]
#### Confirmed Issue on
Joomla! 3.6.5
PHP 7.0.4
MySQLi 5.5.54-0+deb7u2
macOS Sierra, 10.12.3
Firefox 51.0.1

**Comment by brianteeman** [comment]
Closed as you have now created a pr
