### ISSUE TITLE
Postgresql: Notice message in Multilingual Associations

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#14424]
### Steps to reproduce the issue
Install latest stageing with testing data and one additional language. Go to Multilingual Associations and select as item type "articles" and "english" as language. You should get this notice:

Notice: Undefined index: link in /var/www/html/joomla34p/layouts/joomla/content/associations.php on line 18

**Comment by infograf768** [comment]
testing data is not fit to multilingual testing. 
please use no sample data and follow up

**Comment by waader** [comment]
Thanks infograf! This can be closed.

**Comment by brianteeman** [comment]
Closed as requested
