### ISSUE TITLE
Feature Request - Select Editor per Usergroup

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14438]
For now you can select a default-Editor per User or a default Editor for all Users. But what if the registered Users should not have an Editor but the Administrators? Then you would need to set up the default Editor to none and assign tinyMCE to each Admin. I think it could be nice to have an Default Editor Setting in the Group Params for each Group. 
Any thoughts?

**Comment by mbabker** [comment]
> But what if the registered Users should not have an Editor but the Administrators

This would mean you're giving users a plain text area and basically forcing them to write in HTML versus having a WYSIWYG option available to them.  At that point, I'd question why you're not just using a `<textarea>` form element or hardcoding the form to only use the none editor if you really need this type of configuration.

I don't think this should be changed on a per-group basis.  Also remember here that a user > group > global hierarchy for any parameter introduces a lot of problems in general.  When a user is assigned to multiple groups, what should the parameter value be?  If you say "most privileged", how do we know what that means in a given context?

**Comment by brianteeman** [comment]
Don't forget that in 3.7 you can completely customise tinymce per usergroup. That should cover most real world examples

**Comment by coolcat-creations** [comment]
@brianteeman yes, but i can´t remove the buttons there :( I would need to set ACL for each button seperately...

**Comment by coolcat-creations** [comment]
An alternative Layout for EDITING an Article inside a specific Category would solve this issue too. It´s just like the plugin from @dgt41 but seeing something like that in core would be great.

**Comment by brianteeman** [comment]
iirc The buttons are not the editor they afre plugins that are being displayed in the editor

**Comment by dgt41** [comment]
@brianteeman true, but specifically for tinymce we render those button inside the editor, in other words they are part of the tinymce configuration parameters

**Comment by SharkyKZ** [comment]
For what it's worth, this is super simple to do with a plugin.
