### ISSUE TITLE
[4.0] Notices at opened Modules "Menu", "Login"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14434]
### Steps to reproduce the issue
Open Module "Menu" got:
![bildschirmfoto 2017-03-09 um 10 48 06](https://cloud.githubusercontent.com/assets/8235763/23744857/327e595c-04b6-11e7-9f15-8711da1ecac5.JPG)

Same on Module "Login".
### System information (as much as possible)
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/14436
