### ISSUE TITLE
Calendar date at greek language locale

### ISSUE THREAD

**Issue by pnkr** [joomla/joomla-cms#14432]
### Steps to reproduce the issue
From Extensions > Plugins > Fields - Calendar
There is a format to show the calendar date. The default is this:
![screen shot 2017-03-09 at 08 40 33](https://issues.joomla.org/uploads/1/4fa9e93e45903bcedd8d05bdbe75e8ec.png)

In Greek Language we use it in another format, i did the change
![screen shot 2017-03-09 at 08 40 36](https://issues.joomla.org/uploads/1/2a36c9f43dfa26bcaf7aa514aa074d00.png)

### Expected result

Expected result will be the date to show in the new format.
for example 31-3-2017

### Actual result

But custom field calendar shows always the default format, when user set a date
![screen shot 2017-03-09 at 08 55 30](https://issues.joomla.org/uploads/1/27b8f31e044e7b092846ecddb8b1d70d.png)

**Comment by infograf768** [comment]
This parameter does not show in the plugin as of latest staging

**Comment by infograf768** [comment]
the calendar will follow (When Greek language is updated to 3.7.0) the preferred format used in the language pack.
For French, I used the same as for Greek
```ini
DATE_FORMAT_CALENDAR_DATE="%d-%m-%Y"
DATE_FORMAT_CALENDAR_DATETIME="%d-%m-%Y %H:%M:%S"
DATE_FORMAT_FILTER_DATE="d-m-Y"
DATE_FORMAT_FILTER_DATETIME="d-m-Y H:i:s"
```
and it rightfully displays:
![screen shot 2017-03-09 at 10 30 50](https://cloud.githubusercontent.com/assets/869724/23744171/831bf764-04b3-11e7-9a08-57c104e9ca44.png)

**Comment by infograf768** [comment]
@laoneo @Bakual 
the  showtime field parameter present in
https://github.com/joomla/joomla-cms/blob/staging/plugins/fields/calendar/params/calendar.xml
does not display anywhere it seems.

**Comment by pnkr** [comment]
@infograf768 Thank you very much. Indeed it was not a Joomla Issue but a translation issue after all.

Worked fine, case closed
