### ISSUE TITLE
[4.0] Modules: More Space for Switch "Site/Administrator"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14430]
### Steps to reproduce the issue
Modules, click on Button `Site/Administrator`, there is less Space:
![bildschirmfoto 2017-03-09 um 09 30 49](https://cloud.githubusercontent.com/assets/8235763/23742002/6b86945e-04ab-11e7-8308-35ddcb14bb56.JPG)
### Test on:
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by franz-wohlkoenig** [comment]
Less Space is in all Dropdowns.

**Comment by franz-wohlkoenig** [comment]
Looks like this is a global Change on all Dropdowns, @C-Lodder?

**Comment by C-Lodder** [comment]
Also getting this issue with Windows Chrome on the official BS docs, so believe this may be a BS issue. I remember they made some `custom-select` changes for the beta version so I'll wait till this has been released.

**Comment by franz-wohlkoenig** [comment]
thanks for Info, @C-Lodder

**Comment by brianteeman** [comment]
I am closing this as it appears to be resolved. Feel free to reopen it if you feel its is still an issue

<img width="272" alt="screenshotr20-00-23" src="https://user-images.githubusercontent.com/1296369/28183052-f80d2cd6-6805-11e7-83c4-b9549810e6e2.png">

**Comment by ghost** [comment]
Reopened as Issue isn't solved using:
### System information
4.0.0-dev
macOS Sierra, 10.12.5
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14430">issues.joomla.org/tracker/joomla-cms/14430</a>.</sub>

**Comment by C-Lodder** [comment]
Cannot be closed until BS4-beta.1 is released. Appears to be a browser specific issue

**Comment by brianteeman** [comment]
ah didnt realise it was a " a browser specific issue"

**Comment by ghost** [comment]
can't reopen, get `422 RuntimeException – Invalid response from GitHub`

**Comment by brianteeman** [comment]
Reopened directly on github

**Comment by ghost** [comment]
thanks @brianteeman

**Comment by brianteeman** [comment]
As bootstrap beta has now been merged please can you retest and see if the issue still occurs for you

**Comment by ghost** [comment]
Issue still occurs:
![bildschirmfoto 2017-08-25 um 20 28 44](https://user-images.githubusercontent.com/8235763/29727408-0d2d5524-89d4-11e7-8d15-3299af1c2cdd.jpg)

### System information
4.0.0-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by ghost** [comment]
Test using Firefox 57 still valid Issue:

![bildschirmfoto 2017-11-21 um 14 56 45](https://user-images.githubusercontent.com/8235763/33076158-3b3e7bc2-cecc-11e7-9a31-d709e7cddc1a.jpg)
### System information
4.0.0-dev
Multilanguage Site (4 Lang.) & Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
@franz-wohlkoenig now that I've updated to BS4-beta.3, can you re-test please?

**Comment by ghost** [comment]
i use 4.0-dev from github?
![bildschirmfoto 2017-12-29 um 18 32 57](https://user-images.githubusercontent.com/8235763/34443056-bb3a5338-ecc6-11e7-88d1-c858b762b800.jpg)

**Comment by C-Lodder** [comment]
Yeah

**Comment by ghost** [comment]
~~After Database-Conncetion-Screen got white Screen~~:

![bildschirmfoto 2017-12-29 um 18 40 17](https://user-images.githubusercontent.com/8235763/34443524-0e97a4a8-ecc8-11e7-8db0-167e6df980f3.jpg)

Sorry, haven't seen i'm on wrong Driver.

**Comment by ghost** [comment]
Retest done, Issue is same:

![bildschirmfoto 2017-12-29 um 18 44 01](https://user-images.githubusercontent.com/8235763/34443667-fa21cb88-ecc8-11e7-9732-9105bcf34998.jpg)
### System information
4.0.0-dev
Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
FF
<img width="271" alt="screenshotr18-00-24" src="https://user-images.githubusercontent.com/1296369/34443907-392d15fa-ecc2-11e7-8b81-c381a8c989c1.png">

Chrome
<img width="272" alt="screenshotr18-00-32" src="https://user-images.githubusercontent.com/1296369/34443911-3c933742-ecc2-11e7-8a33-ac8517f36aae.png">

**Comment by C-Lodder** [comment]
@franz-wohlkoenig do you have the same issue here: https://getbootstrap.com/docs/4.0/components/forms/#select-menu ?

If so, would you mind closing this and opening an issue on the BS tracker

**Comment by brianteeman** [comment]
Yes the issue is a bootstrap issue see this FF screenshot
<img width="344" alt="screenshotr18-06-24" src="https://user-images.githubusercontent.com/1296369/34444033-0bc3bd20-ecc3-11e7-9087-cbfa3f1b5cce.png">

**Comment by brianteeman** [comment]
I am closing this as it was a BS error that appears to have been resolved by BS. It can always be re-opened if that's not the case

**Comment by ghost** [comment]
@brianteeman can you please reopen this directly on Github? I want to comment that a Part works like expected.

**Comment by ghost** [comment]
~~@brianteeman can you please reopen this directly on Github? I want to comment that a Part works like expected.~~
False Thinking of me, please ignore Comment above.

**Comment by ghost** [comment]
@brianteeman can you please reopen this directly on Github? Now found a Part (in Articles) working as expected which i want to comment:
![screen shot 2018-07-14 at 08 28 56](https://user-images.githubusercontent.com/8235763/42722655-1722b054-8750-11e8-90ac-5faddcc3f212.jpg)

**Comment by ghost** [comment]
thanks @infograf768

**Comment by infograf768** [comment]
@franz-wohlkoenig 
We have to keep in mind though that the backend template is WIP.

**Comment by ghost** [comment]
@infograf768 true, Discussion was "bug in bs4" so i was surprised that one Select (i haven't searched more) works. So there must something different than other Select.

**Comment by brianteeman** [comment]
the category select is still using "chosen" which is supposed to be replaced
