### ISSUE TITLE
Custom field: Generate view over Menu?

### ISSUE THREAD

**Issue by DevelPott** [joomla/joomla-cms#14448]
### Steps to reproduce the issue
Not possible to show articles with specifeid custom field entrys?

e.g. 3 Checkboxes with topics choose. Only show for example all articles with defined checkbox/topic 1 choose?

**Comment by laoneo** [comment]
Do you mean assigning a custom field to a specific article?

**Comment by DevelPott** [comment]
No, generate Category listings (article overview) with specified custom field. Show all article with checkbox value xy

**Comment by coolcat-creations** [comment]
I think he means something like a hidden search. Showing Articles from Category X but only those which have checked Mercedes in the Car-Custom fields.

**Comment by DevelPott** [comment]
Use now a component (jreviews) for this feature, but now with the custom fields we get the option with the joomla core

**Comment by coolcat-creations** [comment]
Actually this would mean that after selecting the Menutype Article or Categoryblog and assigning a Category or Article which has fields, the Fieldtab appears in the Menutype. Then you can select options there and only Articles will be shown that match this option. 

So this could be a nice Feature Request for 3.8 ?

**Comment by Bakual** [comment]
The search will find items with sepcific field values. But other than that, it was decided to not allow to filter a list based on custom field values. It basically would mean that the fields plugin has to alter queries and we get into devils kitchen doing that. Or each extension has to add filters into their list queries, which makes the whole plugin architecture kinda useless.
If you need such a functionality, you will still have to use a full CCK solution.
