### ISSUE TITLE
[4.0] No Progress-Bar at Update

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14441]
### Steps to reproduce the issue
Joomla Update > Tab Upload & Update: After click on "Install" there is no Progress-Bar like 3.*.
### System information (as much as possible)
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/14455
