### ISSUE TITLE
[4.0] Missing "Reinstall package URL" (nightly builds)

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14457]
### Steps to reproduce the issue
Joomla Update in 3.* got a `Reinstall package URL`
![bildschirmfoto 2017-03-10 um 12 57 07](https://cloud.githubusercontent.com/assets/8235763/23794603/3e9d2106-0591-11e7-9c60-ad14bbf27cba.JPG)
in Joomla4 its missing:
![bildschirmfoto 2017-03-10 um 12 58 48](https://cloud.githubusercontent.com/assets/8235763/23794620/54ee829c-0591-11e7-821c-f30d0f2daf14.JPG)
### System information (as much as possible)
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
Perhaps this hasn't been merged in yet. @wilsonge when was the last merge from staging to 4.0?

**Comment by zero-24** [comment]
@franz-wohlkoenig reinstall should be on the `Live Update` Tab. Can you double check that?

**Comment by wilsonge** [comment]
About 8 days ago. I desperately need to find time to do an update

**Comment by franz-wohlkoenig** [comment]
@zero-24:
![bildschirmfoto 2017-03-10 um 16 19 06](https://cloud.githubusercontent.com/assets/8235763/23800630/71831c26-05ad-11e7-80ef-0ee52aaab8da.JPG)

**Comment by zero-24** [comment]
@franz-wohlkoenig @C-Lodder it has nothing to do with a not uptodate 4.0 vs staging (that can be checked too but it should not be a problem) as the feature is included since 3.6.x it looks like the complete updater is broken in 4.0.. i have opend a issue with my findings: https://github.com/joomla/joomla-cms/issues/14471

**Comment by franz-wohlkoenig** [comment]
@zero-24 is there a way to get daily update of nightly-builds by click on Joomlaupdate without have them manually downloaded and installing?

**Comment by zero-24** [comment]
As the updater is broken in 4.0 no. ;) in 3.7 you can use the reinstall button as it does the same ;)

**Comment by franz-wohlkoenig** [comment]
Using Button `Reinstall Joomla core files` updates to latest nightly builds? Thanks, this Info i missed.

**Comment by zero-24** [comment]
Yes if you set the correct update server and the url points to the nightly build. ;)

**Comment by zero-24** [comment]
please test #14540 and please manuall apply the changes to 4.0 if you test there as the PR is against staging.
