### ISSUE TITLE
[4.0] PHP fatal error on password reset view

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#14467]
### Steps to reproduce the issue

In the frontend, on the login form, click `forgot username` or `password reset`

### Expected result

A form allowing me to reset my password

### Actual result

```
Fatal error: Interface 'JFormDomfieldinterface' not found in \libraries\cms\form\field\captcha.php on line 17
```
![screeny](https://cloud.githubusercontent.com/assets/2019801/23801343/be8ea568-05a7-11e7-9cbc-668dfe1f8888.png)

### System information (as much as possible)

- Joomla 4.0-nightly
- PHP 7.0.10

**Comment by dgt41** [comment]
@laoneo can you check that this field is extended correctly in 3.x as well?

**Comment by dgt41** [comment]
@C-Lodder I think the correct is `Fatal error: Interface 'JFormFieldinterface'`

**Comment by laoneo** [comment]
That interface was abandoned long time ago. Will have a look.

**Comment by joomdonation** [comment]
I created a PR https://github.com/joomla/joomla-cms/pull/14481 to remove implements from class definition. Could @laoneo takes a look at it to see whether it is OK?

**Comment by zero-24** [comment]
Closing as there is a PR thanks @joomdonation
