### ISSUE TITLE
[4.0] PHP notice on com_menus

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#14468]
### Steps to reproduce the issue

In the backend, go to:
- `Menus` >> `All menu items`
- Then click `Menu Items` on the subnav (sidebar)

### Expected result

- A normal view

### Actual result

```
Undefined variable: saveOrderingUrl in \administrator\components\com_menus\views\items\tmpl\default.php on line 104
```

### System information (as much as possible)

- Joomla 4.0-nightly
- PHP 7.0.10

**Comment by franz-wohlkoenig** [comment]
Can't confirm,  Error Reporting is set on `Maximum`, also tested on `Development`

**Comment by joomdonation** [comment]
@franz-wohlkoenig Make sure you don't select a Menu in Select Menu dropdown, see this screenshot 

![menus- all menu items - joomla cms 4 0 - administration](https://cloud.githubusercontent.com/assets/977664/23821554/83788fea-0668-11e7-9278-b524b0d8c8fa.png)

**Comment by franz-wohlkoenig** [comment]
Select `Menu Items`, no Error shown:
![bildschirmfoto 2017-03-11 um 08 50 58](https://cloud.githubusercontent.com/assets/8235763/23821610/05f0db70-0638-11e7-8242-8325b84f3046.JPG)

**Comment by joomdonation** [comment]
@franz-wohlkoenig At the right, there is a a dropdown Sort Table By. Select **Ordering ascending** and you should see the notice

**Comment by franz-wohlkoenig** [comment]
Changed ordering in `Sort Table By:`, no Notice.

**Comment by joomdonation** [comment]
Don't know why you don't see this error :(

**Comment by franz-wohlkoenig** [comment]
Tried Safari instead Firefox, same Result. But other see Notice, PR works, all fine.

**Comment by yasirunilan** [comment]
I also tried, can't confirm

**Comment by joomdonation** [comment]
That's so strange to me. Could you please:

1. Try to check it using a nightly build installation https://developer.joomla.org/nightly-builds.html

2. Access to Menus -> All Menu Items (the URL looks like this http://localhost/cms40/administrator/index.php?option=com_menus&view=items&menutype=)

3. In the Sort Table By dropdown, set it to Ordering ascending

(See this screenshot, the selected value of the two dropdowns is important)


![menus- all menu items - joomla cms 4 0 - administration 1](https://cloud.githubusercontent.com/assets/977664/23829119/d322be46-071a-11e7-8b99-62c4cb0d8c44.png)

**Comment by franz-wohlkoenig** [comment]
@joomdonation, done like you wrote, same Result (no Notice):
![bildschirmfoto 2017-03-12 um 07 19 40](https://cloud.githubusercontent.com/assets/8235763/23829536/7e3efc58-06f4-11e7-94f6-212bc5432b71.JPG)

**Comment by joomdonation** [comment]
Final try: Go to System -> Global Configuration, look at Server tab, set the config option **Error Reporting** to **Maximum**, then try again

If still no notices, I don't have any other clues

**Comment by franz-wohlkoenig** [comment]
"Error Reporting" is set on `Maximum` or on `Development`: No Notice.

**Comment by joomdonation** [comment]
Strange. I can see the error, both from the test and from reading the source code. We will have to wait for others to test it, then

**Comment by franz-wohlkoenig** [comment]
i tried also with branch https://github.com/zero-24/joomla-cms/archive/indexphp-40.zip – no Notice. Wait on other Testers.

**Comment by C-Lodder** [comment]
I'll try reinstalling J4 later on.

**Comment by mbabker** [comment]
`$saveOrderingUrl` is only defined if both `$saveOrder` and `$menuType` evaluate to true, but is only used if `$saveOrder` is true.  Just on reading the code, @joomdonation instructions are correct for reproducing the error.  If nothing else, it shows there's a logic error in the layout.

**Comment by wilsonge** [comment]
Fxied
