### ISSUE TITLE
Turning off cache doesnt ignore cache files

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#14461]
### Steps to reproduce the issue

**Can anyone replicate this  - or is it just me?**

Enable cache
generate cache files by visiting the site - then turn the site offline in Joomla global config
visit the site and see it offline 
enable the site online again in Joomla config

reload the home page... 

### Expected result

Expect that I see the site online again

### Actual result

I see the site offline again, until I manually delete the files in the /cache folder, and then the site comes online again. 

### System information (as much as possible)

Joomla 3.6.5 - PHP 7.0.1
Gantry type framework template

**Comment by brianteeman** [comment]
> Expect that I see the site online again

I would not expect that until the cache has expired

**Comment by PhilETaylor** [comment]
If you turn off the cache then its reasonable to expect Joomla NOT to use cached files (Im not talking browser cache here)

**Comment by mbabker** [comment]
Nowhere in your report have you given instruction to turn off the cache.  Just changing the offline option.  So, as written, the cache is correctly used.

**Comment by PhilETaylor** [comment]
Its friday...... doh...

**Comment by PhilETaylor** [comment]
Although one could argue that enabling the site online, should clear the "site offline" caches ;-)

**Comment by mbabker** [comment]
Feel free to  submit a PR 😉
