### ISSUE TITLE
 [4.0] Control Panel: `Joomla is up to`

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14478]
### Steps to reproduce the issue
Open Control Panel, after checking Joomla Message ist cutted:
![bildschirmfoto 2017-03-11 um 07 50 16](https://cloud.githubusercontent.com/assets/8235763/23821348/cd3bd72e-062f-11e7-89d0-e150db341cf0.JPG)
It depends on Browser-Window-Size.
### System information (as much as possible)
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by ciar4n** [comment]
PR created.. https://github.com/joomla/joomla-cms/pull/14507
