### ISSUE TITLE
[4.0] [3.7] Control Panel: Joomla! vs Joomla

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14479]
### Steps to reproduce the issue
Load Control Panel,Message at checking Joomla:
![bildschirmfoto 2017-03-11 um 08 00 21](https://cloud.githubusercontent.com/assets/8235763/23821389/e7e80d58-0630-11e7-9f46-2ae68e5859c8.JPG)
After Check:
![bildschirmfoto 2017-03-11 um 08 00 34](https://cloud.githubusercontent.com/assets/8235763/23821392/0b826f4c-0631-11e7-90e0-ee7290040609.JPG)
### Expected result
Same Wording.
### System information (as much as possible)
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by tonypartridge** [comment]
Last time I checked it should be Joomla! @brianteeman can you confirm?

**Comment by brianteeman** [comment]
https://developer.joomla.org/en-gb-user-interface-text-guidelines/joomla-name.html

**Comment by C-Lodder** [comment]
It shouldn't contain a `!` but this is an issue for 3.x, not 4.0

**Comment by franz-wohlkoenig** [comment]
changed Issue-Title for 3.7 too.

**Comment by franz-wohlkoenig** [comment]
closing cause PR
