### ISSUE TITLE
[4.0] com_users routing

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#14480]
### Steps to reproduce the issue
1. Install Joomla 4.0, no sample data.
2. Go to homepage http://localhost/cms40
3. Click on Forgot Password and Forgot Username links
- Forgot password link is http://localhost/cms40/index.php/remind?Itemid=101
-Forgot username link is http://localhost/cms40/index.php/reset?Itemid=101

### Expected result
The links work

### Actual result
Receiving 404 error URL invalid

### System information (as much as possible)
Joomla 4.0 nightly build

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.

**Comment by tonypartridge** [comment]
Thanks for confirming and raising. 

George has a pull in now: #14542

**Comment by joomdonation** [comment]
@tonypartridge Might not be the same. As I understand, the PR George made fix invalid URL doesn't throw 404 error while this issue is something wrong with router, the links throw 404 error for some reasons

**Comment by franz-wohlkoenig** [comment]
@tonypartridge same behaviour with #14542: Click on both links, no redirect (Menu for both Links exists).

**Comment by tonypartridge** [comment]
Sorry it's the wrong one. @wilsonge did you submit a pull from our work yesterday? Or is more needed?

**Comment by joomdonation** [comment]
The issue was solved somewhere. I could not re-procedure the issue in nighty build, so close this issue.
