### ISSUE TITLE
[4.0] Better Breakpoints for "Global Configuration"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14487]
### Steps to reproduce the issue
Resize Browserwindow in "Global Configuration":
![bildschirmfoto 2017-03-11 um 12 37 17](https://cloud.githubusercontent.com/assets/8235763/23822951/c8d392c6-0657-11e7-8d08-a1b4f06943eb.JPG)
### System information (as much as possible)
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by ciar4n** [comment]
PR created... #14487 (Step 1 of 2)

**Comment by ciar4n** [comment]
PR created... #14487 (Step 2 of 2)
