### ISSUE TITLE
[4.0] Add Menu: Error > Field `asset_id` has no default Value

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14482]
### Steps to reproduce the issue
Add new Menu, after `Save` get:
![bildschirmfoto 2017-03-11 um 09 25 10](https://cloud.githubusercontent.com/assets/8235763/23821767/f86479f8-063c-11e7-9c14-dac5d11a28d1.JPG)
### System information (as much as possible)
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by joomdonation** [comment]
Confirm the issue. The asset_id field in __menu_types must has default value set to 0 like in other tables. @csthomas could you take a look ?

**Comment by csthomas** [comment]
I it done in https://github.com/joomla/joomla-cms/pull/14321

**Comment by brianteeman** [comment]
this can be closed as it is resolved by #14321

**Comment by joomdonation** [comment]
Great. Thanks for the info

**Comment by csthomas** [comment]
I can not test it on the latest 4.0-dev joomla because after installation I get `Class 'JAuthenticationHelper' not found`.

**Comment by franz-wohlkoenig** [comment]
thanks for resolving Issue @csthomas
