### ISSUE TITLE
[com_fields] Calendar with onchange=this.form.submit: Time selection is not possible

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#14486]
### Steps to reproduce the issue
Add the attribute onchange="this.form.submit" to a calendar field or make a calendar like this:

echo JHtml::_('calendar', JFactory::getDate()->format('Y-m-d'), 'date', 'date', '%Y-%m-%d', array('onChange' => 'this.form.submit();'));

Try to select a Time with hours and minutes.
This is not possible. You can select either a hour or minutes, but not both, as the onChange event is triggered with the first selection.

**Comment by dgt41** [comment]
Hmm, that's tricky, onChange fired when something is changed (basically this event makes sense for inputs and selecting a date, time has 2 or 3 inputs [hour, mins, am/pm as select elements] so it correctly fires when **only one of these is changed**)

**Comment by dgt41** [comment]
Said that, what you can do is do some checking before submitting the form.

**Comment by chmst** [comment]
I'll find a solution for me :) but maybe others will find this issue too. 
We could say - if onChange is in the attributes: Or make a submit button when rendering the calendar and remove the attribute? 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14486">issues.joomla.org/tracker/joomla-cms/14486</a>.</sub>
