### ISSUE TITLE
Multilingual Associations - innaccurate info

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14490]
### Steps to reproduce the issue
Install a second language
Ensure that the System - Language Filter plugin is enabled with item associations
Create a new article in English - do not associate it with any other language
Open Multilingual Associations component
Select Articles as type and English as reference language

### Expected result
Newly created article is listed and associations column is empty

### Actual result
Associations column indicates the english article is associated in the other installed language

<img width="476" alt="screenshotr15-27-01" src="https://cloud.githubusercontent.com/assets/1296369/23824461/38bd833c-066f-11e7-8719-dbdde7bfea7a.png">

**Comment by infograf768** [comment]
it is associated when the icon is grey. as one may directly click on the icons, one will get in the side by side an empty item already tagged to the chosen language when it is orange.

**Comment by brianteeman** [comment]
That's a MASSIVE accessibility fail. You should NEVER just use a colour to
indicate anything.

**Comment by infograf768** [comment]
i would not use UPPERCASE like this, but, anyway, the intent was to show if an item was already associated or not in the available content languages.
To keep this information (which is important), i am sure it would be possible to display another column titled something like 'Not yet Associated' to separate them.

**Comment by brianteeman** [comment]
This code is an accessibility fail. It can't be released like this. We
should take accessibility seriously.

**Comment by infograf768** [comment]
cool. i will,look at this tomorrow.

**Comment by infograf768** [comment]
@brianteeman 
would that be OK for you?

![screen shot 2017-03-12 at 12 31 32](https://cloud.githubusercontent.com/assets/869724/23831384/3d7fbbae-0720-11e7-9d1e-8665d4161850.png)

**Comment by brianteeman** [comment]
1. Technically this will still fail accessibility rules as you are still using colour to indicate a meaning. 
>  1.4.1. Use of Color: Color is not used as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element. (Level A)

2. What is the purpose of even showing the not associated languages? The list of languages you are generating it the list of installed site languages. NOT the content languages. On a site at joomla.com for example where all the available joomla languages are installed you would have a list of 60+ languages here.

So surely you only need to be using content languages not installed languages and I still dont see the use case for showing languages that do not have associations. But if you have a use case for that then you must find a way not to only use color as the sole meansd of conveying information

**Comment by infograf768** [comment]
I was opposed to the fact that Content languages were created at the same time as languages was installed. And that is indeed what would happen now if more languages than necessary are installed...
In any case, I doubt that users would install more languages than they need. The multilang feature in core is not designed to take care of big sites with dozains of languages and thousands of items

The column heading in this proposal indicates clearly that there is no associations for these content languages. The color is only added to differentiate easily.
Clicking on one of them displays directly the Target for the language instead of multiple clicks once in the side by side.

If no one agrees with the GSOC group on this matter, it is very simple to only show the languages which do have associations. Using a false instead of true in the tmpl.

@alikon @rdeutz @dgt41 
What do you think? In both cases, I can patch easily.

**Comment by dgt41** [comment]
> The multilang feature in core is not designed to take care of big sites with dozains of languages and thousands of items

Hmmm, com_assosiations, com_fields and com_tags fall in the same category. The idea of adding more functionality with a high price tag on performance makes the cms a toy...
Let's go back to the idea of modularising the system, there are better solutions for tags, fields and multilingual from 3PDs

**Comment by infograf768** [comment]
@dgt41
That was not the question here. 😄 
Shall we present only the associated items in one column or use 2 columns as Brian is opposed to the present situation?

**Comment by zero-24** [comment]
:+1: for the two colums.

**Comment by brianteeman** [comment]
My comments are nothing to do with one or two columns

My comments are threefold - 
1. accessibility - current one column and two column proposals both fail
2. what is the purpose of showing languages that do not have an association
3. why are we showing installed languages as opposed to content languages. Remember as I stated that joomla.com is preinstalled with all languages

**Comment by infograf768** [comment]
3. We are showing Content Languages and not Installed languages.
You can see that easily by deleting one of the automatically created Content Languages.

2. The purpose of showing languages that do not have an association is clear: it is a very important information and I already explained that it saves clicks.

1. I do nit see why using 2 columns changes accessibility: it is a list.

Making PR now.

**Comment by brianteeman** [comment]
> We are showing Content Languages and not Installed languages.
>>You can see that easily by deleting one of the automatically created Content Languages.

Ah so it is using content languages but completely ignoring if the content language is published?

**Comment by brianteeman** [comment]
it also ignores if the content language is trashed

**Comment by infograf768** [comment]
The system we have and had since 1.6 is that one can prepare a full Content Language and publish it only when ready. 
As for Trashed, it is as everything in J!: if not deleted it still exists.

**Comment by brianteeman** [comment]
We dont display categories that are trashed ;)

**Comment by brianteeman** [comment]
(now that I know it is referring to content and not installed languages  we can ignore the joomla.com comments

**Comment by infograf768** [comment]
https://github.com/joomla/joomla-cms/pull/14530

**Comment by infograf768** [comment]
Closed as we have a patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14490">issues.joomla.org/tracker/joomla-cms/14490</a>.</sub>

**Comment by rdeutz** [comment]
just one note as I worked on it, I saw that to show a status with only one indicator is not a brillant idea but I was focused on the functionality. It is something we should look at.

**Comment by brianteeman** [comment]
reopened as we no longer have a patch

**Comment by brianteeman** [comment]
closing again as the patch has been re-opened
