### ISSUE TITLE
[fields] calendar plugin missing strings

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14495]
### Steps to reproduce the issue
Open the fields plugin in the plugin manager

### Expected result
all language keys have value

### Actual result
PLG_FIELDS_CALENDAR_PARAMS_FORMAT_LABEL
PLG_FIELDS_CALENDAR_PARAMS_FORMAT_DESC

These are both missing from the language file

I am not sure what they are supposed to be or I would have submitted a PR @laoneo 
***

**Comment by zero-24** [comment]
Do you have the last version of staging? This option should be removed ;)

**Comment by Bakual** [comment]
It's taken care of by https://github.com/joomla/joomla-cms/pull/14344

**Comment by brianteeman** [comment]
Ah. I will check later.
