### ISSUE TITLE
[com_fields] hathor needs an override

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14491]
### Steps to reproduce the issue
try to create a field or field group with the hathor admin template

### Expected result
template looks ok

### Actual result
See movie

![fields](https://cloud.githubusercontent.com/assets/1296369/23824543/661072b2-0670-11e7-9941-c558677fcead.gif)

**Comment by brianteeman** [comment]
The same is true for Field groups where the layout is unusable and also is using the ISIS stlye for search tools and selects

<img width="1254" alt="screenshotr15-00-00" src="https://cloud.githubusercontent.com/assets/1296369/23860138/f19af8c8-07fd-11e7-90d1-0af5a5ec03f6.png">

**Comment by brianteeman** [comment]
ping @laoneo

**Comment by laoneo** [comment]
I'm not familiar with the hathor overrides, so I can't help here much. Also I'm short of time actually, hope somebody else from the community can do them.

**Comment by brianteeman** [comment]
ok I will see what I can do. wont be perfect but will be better than now

**Comment by brianteeman** [comment]
ok - i give up - beyond me how to do it

**Comment by brianteeman** [comment]
awaiting decision on #15079

**Comment by franz-wohlkoenig** [comment]
closed by decision on #15079<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14491">issues.joomla.org/tracker/joomla-cms/14491</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
reopened cause misunderstood Decision about Hathor.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14491">issues.joomla.org/tracker/joomla-cms/14491</a>.</sub>

**Comment by laoneo** [comment]
I guess this one can be closed now as @infograf768 is working on that issue?

**Comment by brianteeman** [comment]
No. @infograf768 specifically said he wasn't working on this view

**Comment by zero-24** [comment]
JM Just fixed the article and contact view not displaying the fields tabs.

**Comment by franz-wohlkoenig** [comment]
@zero-24 correct, but not working on Categories ([comment](https://github.com/joomla/joomla-cms/pull/15227#issuecomment-293306707)), where is same Issue.

**Comment by zero-24** [comment]
please check https://github.com/joomla/joomla-cms/pull/15240 but this issue is about the fields edit page. And this is still broken in hathor :smile:

**Comment by infograf768** [comment]
I will look again at that one but it looks real complex

**Comment by infograf768** [comment]
Please test patch here:
https://github.com/joomla/joomla-cms/pull/15247

**Comment by brianteeman** [comment]
Closed a we have a PR - thanks @infograf768
