### ISSUE TITLE
Editor field Joomla! 3.7

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#14508]
Hello, I have just done several tests, but I notice that the 4 options of the general tab for the editor field does not work. Whether for the buttons or the dimensions of the editor. Also in the description it is written that the width adjustment is done in pxel and the picture shows a % ?
Thank you for your help.

"This is the result of my personal tests, if you notice any anomaly, error, ..., thank you for informing me"

Bonjour, je viens de faire plusieurs test, mais je constate que les 4 options de l'onglet général pour le champ éditeur ne fonctionne pas. Que ce soit pour les boutons ou les dimensions de l'éditeur. De plus dans le descriptif il est écrit que le réglage de largeur se fait en pxel et la photo montre un % ?
Merci pour votre aide.

**Comment by franz-wohlkoenig** [comment]
Similar #15059
