### ISSUE TITLE
[4.0] Notice tinymce after save Plugin, Editor not loaded

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14512]
### Steps to reproduce the issue
After saving Plgin TinyMCE (opened and saved, no Set changed) got:
![bildschirmfoto 2017-03-12 um 12 50 52](https://cloud.githubusercontent.com/assets/8235763/23831487/d3467a22-0722-11e7-84cb-003d697f0d12.JPG)
Console:
![bildschirmfoto 2017-03-12 um 12 54 09](https://cloud.githubusercontent.com/assets/8235763/23831496/05116de6-0723-11e7-9e73-5b45aeb59570.JPG)
### System information (as much as possible)
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by wilsonge** [comment]
@dgt41 this is probably from your multiple tinymce instances pr - i had lots of conflicts to solve can you review?

**Comment by dgt41** [comment]
Ok

**Comment by wilsonge** [comment]
@franz-wohlkoenig can you please test #14575
