### ISSUE TITLE
More flexible user registration

### ISSUE THREAD

**Issue by pot1906dk** [joomla/joomla-cms#14515]
## Problem
When User Account creation is set to Admin verification, Joomla sends a mail to user when his account has been created.
And when an admin has activated the account, user get another mail about this.

## Reason
These mails are hardcoded in the language file, and it is hard or impossible to ensure that the activation link in the mail leads to a page using the correct template.

## Suggestion
It should be possible to set up customized verification pages per user group. 
And these mails should be editable in the editor and be sent as HTML posts to facilitate images and styling.

## Reason
We may have (I do) different user groups (members, customers, clients) and they all need different information when signing up.

**Comment by zero-24** [comment]
> And these mails should be editable in the editor and be sent as HTML posts to facilitate images and styling.

You can do this using language overrides: https://docs.joomla.org/J3.x:Language_Overrides_in_Joomla

**Comment by pot1906dk** [comment]
Overrides only allow me to create another mail, but how can I make different mails for different groups?
I don't think overrides can do that?

And I still cannot make HTML mails that look nice.

**Comment by zero-24** [comment]
Confirmed.

We need to move the mail part from this:
https://github.com/joomla/joomla-cms/blob/staging/components/com_users/models/registration.php#L54

and this:
https://github.com/joomla/joomla-cms/blob/staging/components/com_users/models/registration.php#L387

methods out to plugins. So you can just disabled that plugin and implement your own registration mail handling.

**Comment by brianteeman** [comment]
There are extensions available that will do this. As we aim to keep the core light I am going to close this.
