### ISSUE TITLE
[fields] media and image list paths

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14519]
The tooltip says
The filesystem path to the directory containing the image files to be listed.
but it starts the display at  /
Which implies to the user that it is pointing to the root folder
It is actually displaying the filesystem path AFTER the "Path to Images Folder" as defined in the Media component options

Either the code needs to be updated to include the Path to Images Folder or the tooltip needs to be updated

**Comment by brianteeman** [comment]
@laoneo ping

**Comment by laoneo** [comment]
IMO it is enough to change the tooltip. It will probably crash the form when all folders will be fetched in the medialist plugin when it will be possible to point to root.

**Comment by brianteeman** [comment]
OK I will do a PR for the tooltip

**Comment by brianteeman** [comment]
Closed as we have a PR #14823
