### ISSUE TITLE
Admin Menu - Categories

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14524]
The new ability to add Admin menus allows you to create a menu link to Categories for the elected component. In the list of available components is Users. But users doesnt have categories

<img width="754" alt="screenshotr13-37-30" src="https://cloud.githubusercontent.com/assets/1296369/23832268/4e2d9832-0729-11e7-8619-f827fdb141a4.png">

**Comment by brianteeman** [comment]
In addition some components already have an option to create a category link - eg banners and contacts but some do not eg articles

It really should be consistent. Either there is a category link for each component or there is no link and you have to use the categories link as shown in the screenshot above

**Comment by brianteeman** [comment]
@izharaazmi can you take a look please

**Comment by izharaazmi** [comment]
In the initial feature PR I decided to display all components irrespective that they use categories or not. later in another PR it was modified to show only the components that have at least one category in the database.  Please confirm this situation in your test environment.

@infograf768 Please have a look

**Comment by brianteeman** [comment]
Users doesnt have categories ;)

Also I am not convinced if we should have a separate categories type at all if we have it already in the component (sometimes). whatever is decided it must be consistent. As you can see from the screenshot below there is a category option in the Banners but not in the Articles for example

<img width="265" alt="screenshotr13-18-42" src="https://cloud.githubusercontent.com/assets/1296369/23950199/0f1e145e-0982-11e7-8096-b4051eb28414.png">

**Comment by izharaazmi** [comment]
Users ~doesnt~ have categories ;)

![image](https://cloud.githubusercontent.com/assets/6706189/23950399/deaf5542-09b0-11e7-9843-3fd2a08d6de6.png)

**Comment by izharaazmi** [comment]
@brianteeman. See also #13902

**Comment by izharaazmi** [comment]
Btw, user categories are used as notes categories, as I remember.

**Comment by brianteeman** [comment]
Then it needs to be clear it is notes categories and not categories of
users

**Comment by izharaazmi** [comment]
I want to address this type of things with my said PR. Please see if my
approach is acceptable and feasible or not.

**Comment by tonypartridge** [comment]
@izharaazmi did you make a PR?

**Comment by izharaazmi** [comment]
Yes, #13902 it is.

**Comment by tonypartridge** [comment]
@brianteeman can we close as we have a PR?

**Comment by zero-24** [comment]
Done

**Comment by izharaazmi** [comment]
I think before closing an issue on behalf of a PR we need to evaluate
whether the PR is essentially related and fixes/covers all aspects of the
issue.

**Comment by tonypartridge** [comment]
@izharaazmi that's why I tagged @brianteeman to review it :-)
