### ISSUE TITLE
[4.0] Improve admin menu ordering

### ISSUE THREAD

**Issue by Fedik** [joomla/joomla-cms#14539]
New aside menu looks cool. 
But the ordering need to improve, from the often used items to the less used items.

I would suggest, next ordering:
- Content
- Media
- Components
- Menu
- Users
- Extensions
- System
- Help

**Comment by franz-wohlkoenig** [comment]
1. Content
2. Media
3. Users
4. Menu
5. Components
6. Extensions
7. System
8. Help

**Comment by C-Lodder** [comment]
As mentioned in a previous issue, the sidebar menu is going to be revamped again, which includes changing the ordering and structure.

**Comment by brianteeman** [comment]
I am going to close this for now. Lets wait until the new admin template being developed here https://github.com/joomla/40-backend-template has been merged
