### ISSUE TITLE
Admin menu recovery mode

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14532]
### Steps to reproduce the issue
Create a new admin menu with just a single item in it and make sure you have create a module for it. Publish the module and unpublish the default admin menu module

You will get a Recovery menu with mulltiple dropdowns - all good

Now publish the default admin menu module as well. 

Expected result the Recovery menu displays as before - it doesnt - see menu

Yes I know I can disable the recovery mode check if needed but it seems wrong that the recovery mode dropdown is able to determine that it is not needed (thats why I am assuming it is not showing the dropdown) and yet the recovery mode is still displayed.

I expected either the recovery stuff not to display in this eample OR for it to be displayed with full dropdown contents

See movie
![Uploading recovery.gif…]()

**Comment by brianteeman** [comment]
oops

**Comment by zero-24** [comment]
@brianteeman it looks like your gif is broken?

![image](https://cloud.githubusercontent.com/assets/2596554/23833489/e2105cf2-0746-11e7-8d8c-1dacc59fef15.png)

**Comment by brianteeman** [comment]
@zero-24 better?

![recovery](https://cloud.githubusercontent.com/assets/1296369/23833516/e1cb6924-073e-11e7-8930-9e128555eba3.gif)

**Comment by zero-24** [comment]
Yes.

**Comment by brianteeman** [comment]
@izharaazmi can you take a look please

**Comment by brianteeman** [comment]
Closing as we have a PR for testing see #14640
