### ISSUE TITLE
truncated placeholders

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#14549]
### Steps to reproduce the issue

Install https://github.com/akeeba/loginguard

Go to the Joomla Global Configuration Page for that extension

url: http://example.com/administrator/index.php?option=com_config&view=component&component=com_loginguard&path=

### Expected result

non truncated placeholders

### Actual result

<img width="477" alt="screen shot 2017-03-12 at 17 53 46" src="https://cloud.githubusercontent.com/assets/400092/23834336/e5ac72b4-074c-11e7-85e8-c9c1c5285d12.png">

truncated placeholders until you click to select and then click out of the text box

### System information (as much as possible)

mac/chrome

### Additional comments

https://github.com/akeeba/loginguard/issues/21#issuecomment-285964977

**Comment by PhilETaylor** [comment]
`<input type="text" value="Type or select some options" class="default" autocomplete="off" style="width: 90px;">`

Its the 90px width thats killing it I think... Im no frontend guru though

**Comment by brianteeman** [comment]
sounds about right - i saw this earlier today with another field (cant remember which now) and it either "fixed itself" when i clicked in the field or on refresh - dont remember that either)

**Comment by franz-wohlkoenig** [comment]
similar Issue #13594

**Comment by PhilETaylor** [comment]
Diplicte

**Comment by brianteeman** [comment]
thanks @franz-wohlkoenig thats exactly where I saw it
