### ISSUE TITLE
Form field parameter "required" doesn't follow showon

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#14551]
### Steps to reproduce the issue
create a pair of fields, one creating a showon the other a text box.
add showon and required to the textbox.
turn off showon
go to form in admin and attempt to save.

### Expected result
required will not be tested since showon is false.

### Actual result
required error is thrown.

### System information (as much as possible)
```
			<fieldset name="SERENITY_FONTS">
				<field
					name="googleFonts"
					type="radio"
					class="btn-group"
					default="0"
					label="TPL_SERENITY_FONTS_LABEL"
					description="TPL_SERENITY_FONTS_DESC"
				>
					<option value="1">JYES</option>
					<option value="0">JNO</option>
				</field>
				<field name="Font"
					   label="TPL_SERENITY_GET_FONTS_NAME_LABEL"
					   description="TPL_SERENITY_GET_FONTS_NAME_DESC"
					   class="medium-input"
					   filter="raw"
					   showon="googleFonts:1"
					   type="text"
					   default=''
					   required='1'
				/>
				<field name="Css"
					   label="TPL_SERENITY_GET_FONTS_CSS_LABEL"
					   description="TPL_SERENITY_GET_FONTS_CSS_DESC"
					   class="medium-input"
					   type="text"
					   filter = "html"
					   showon="googleFonts:1"
					   default=''
					   required='1'
				/>
</fieldset>
```

### Additional comments
![image](https://cloud.githubusercontent.com/assets/1850089/23835316/2087ae2c-0733-11e7-8bf3-4c8ea7a67a30.png)

**Comment by mbabker** [comment]
`showon` is a UI parameter only, it isn't altering other attributes of the form such as `required`.

Further explained in https://github.com/joomla/joomla-cms/issues/11243 why this is how the system is designed.

**Comment by N6REJ** [comment]
ugh.... ok.. I'll just have to check for empty field..  ty... sorry for false report.
