### ISSUE TITLE
Cannot login with neither MS IE nor MS Edge

### ISSUE THREAD

**Issue by EBAMAN** [joomla/joomla-cms#14553]
### Steps to reproduce the issue
I cannot login to Joomla 3.6.5 with neither Internet Explorer nor MS Edge.
This applies for both backend and frontend
After filling in username and password and press the login-button, the login-form is cleared and no login is performed.
FF and Chrome works ok.
The similar happens when trying to install from IE or EDGE, it stays on step 1 nothing more happens 

### Expected result
I should be able to login

### Actual result
Login does not work

### System information (as much as possible)
site is www.ebaman.scom

### Additional comments
I have tried to login from IE installations where IE never had been used before, with the same result, so it is not an IE/cache/temporary files problem

**Comment by zero-24** [comment]
I can not reproduce this behavior on my end.

**Comment by zero-24** [comment]
It sounds like a local problem. Did you try a different PC?

btw. your link could not be resolved ;)

Please also check this warning:
![image](https://cloud.githubusercontent.com/assets/2596554/23836316/6f5bb758-0776-11e7-9db0-424628105305.png)

Please move any other questions to https://forum.joomla.org/

I'm closing that than as not a core bug.

**Comment by EBAMAN** [comment]
I Have tried it on 10 different PCs, the issue is the same<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14553">issues.joomla.org/tracker/joomla-cms/14553</a>.</sub>

**Comment by zero-24** [comment]
Please fix the server warning i have showed you with your hoster. ;) If you have more questions please ask to the forum :)

**Comment by EBAMAN** [comment]
I don’t get those warnings, in any browser, neither FF nor Chrome or IE/Edge.

I have tried to login with IE and EDGE from at least 10 different PCs and servers, A mix of XP/W7/W10 and Server 2k8R2.

All showing the same problem.

Some of them was fresh installs where IE/Edge hasn’t been used.

So obviously It cannot be a local PC-problem, but rather a JOOMLA problem

 

With best regards

 

Tomas Larsson

 

Från: zero-24 [mailto:notifications@github.com] 
Skickat: den 12 mars 2017 23:38
Till: joomla/joomla-cms
Kopia: Tomas Larsson; Author
Ämne: Re: [joomla/joomla-cms] Cannot login with neither MS IE nor MS Edge (#14553)

 

Please fix the server warning i have showed you with your hoster. ;) If you have more questions please ask to the forum :)

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding.

**Comment by K2Joom** [comment]
I have had a report from a user, that they could not login to a clients website.

Using their account, I was able to login first time in Google Chrome, but in MS Edge, when logging in, nothing happens other than the page refreshes.
When I check site admin, I see that the user is shown as logged in.

I shall be doing some more tests, before submitting a report.

**Comment by K2Joom** [comment]
I have other 3.6.5 sites, which do allow me to login using Edge, which would lead me to believe, it is not a browser or J! version issue.
Instead, it would lead me to think it to be a site config issue, but not sure why it is only seen on some 3.6.5 sites on IE/Edge.

**Comment by franz-wohlkoenig** [comment]
@K2Joom can you please open a new Issue?
