### ISSUE TITLE
Multilingual associations copy reference

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14561]
### Steps to reproduce the issue
Using multilingual associations select an article and then Copy Reference to Target and save the target

### Expected result
Target has been in saved as an identical article but in the new language

### Actual result
Target article has been saved but it is not published

**Comment by alikon** [comment]
it will be saved as published if you set the published status in the target item.

as default is setted to unpublished , cause usually you need to do "some changes" before  to publish it.

for me is correct behaviuor , @infograf768  any comments

**Comment by brianteeman** [comment]
As default it is set to unpublished on a copy
As default is is set to published on a new

This inconsistency is confusing and wrong imho

**Comment by infograf768** [comment]
The behavior is exactly the same as when you deal with articles or other type of items in core where you have Save as Copy.

Save as Copy set the copied item to unpublished by default (can be modified to published before saving).
New is published by default.

Not sure we should change that specifically in com_associations.
