### ISSUE TITLE
Multilingual Associations and Flags

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14560]
### Steps to reproduce the issue
Setup multilingual associations and in the content language setting make sure that you set the image to none. now go to multilingual associations and check the tooltips.

### Expected result
The tooltip will display the name of the language only - and not the language and the image (flag)

### Actual result
The tooltip displays the name of the language and we have a missing image and a displayed alt tag

`<img src="" alt="Afrikaans" title="Afrikaans" /> Afrikaans <br/>
`

**Comment by brianteeman** [comment]
the same is true for the list view where the missing image and alt tag are still used in the languages column

**Comment by infograf768** [comment]
I confirm.
The GSOC project was done before the PR which allowed content languages to have no image and the other PR using boostrap.popover for the tips in the Managers Associations Column.

@Bakual 
As you coded this last one (which uses no flags), can you see what you can do to change the code in com_associations helper?

For the Language column, it is pretty simple:
Change in the default.php and modal.php to:
`<?php echo JLayoutHelper::render('joomla.content.language', $item); ?>`
will display the flag and language name when there is a flag, the name only if no flag.

Concerning the tip it is a bit more complex. I am looking into it though.

**Comment by brianteeman** [comment]
See #14563 for a PR

**Comment by infograf768** [comment]
Patch is not good.
