### ISSUE TITLE
[fields] sort order and error

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14573]
### Steps to reproduce the issue
Open fields and compare the order of the Sort table filters with the order of the columns and they all work

### Expected result
Sort filters will match the order of the columns as they do throughout Joomla and that they will all have an Ascending and Descending option

### Actual result
A sort filter for Field Group appears at the end of the list and without an Ascending or Descending selector

A sort filter for Field Group also appears in the correct place in the list but again without Ascending or Descending selectors

In addition if you select either of these two selectors you will get an error message
> Unknown column 'category_title' in 'order clause'

<img width="259" alt="screenshotr13-30-50" src="https://cloud.githubusercontent.com/assets/1296369/23856368/4db40fee-07f1-11e7-857d-cb412586c9ba.png">

**Comment by shivamdiehard** [comment]
Hi,I tried testing this. After selecting sort filter for Field group it is displaying the error "Unknown column "category_title" in "order_clause".
But after that when I am trying to open again fields from content dropdown, the sort filter page is not displaying, it is showing just and nothing else.
Now there is no display of field view, any idea how to get it back? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14573">issues.joomla.org/tracker/joomla-cms/14573</a>.</sub>

**Comment by brianteeman** [comment]
That's why it's a nasty bug. You need to clear local browser storage iirc

On 13 Mar 2017 6:00 p.m., "Shivam" <notifications@github.com> wrote:

Hi,I tried testing this. After selecting sort filter for Field group it is
displaying the error "Unknown column "category_title" in "order_clause".
But after that when I am trying to open again fields from content dropdown,
the sort filter page is not displaying, it is showing just and nothing else.
Now there is no display of field view, any idea how to get it back?
------------------------------
This comment was created with the J!Tracker Application
<https://github.com/joomla/jissues> at issues.joomla.org/tracker/
joomla-cms/14573.

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub
<https://github.com/joomla/joomla-cms/issues/14573#issuecomment-286191359>,
or mute the thread

**Comment by brianteeman** [comment]
Can we have a Release Blocker on this please as it kills the component on your site if you select the broken selector and is a pia to get your site usable again

**Comment by infograf768** [comment]
@laoneo Please look.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14573">issues.joomla.org/tracker/joomla-cms/14573</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a Pr for testing
