### ISSUE TITLE
Missing translation for the new 'Components menu container' menu item type

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#14577]
### Steps to reproduce the issue
Install an extension such as Virtuemart

### Expected result
All values in 'Show or Hide Menu Items' are translated as the standard Joomla admin menu

### Actual result
Only item marked as <name>COM_XXX</name> in the XML manifest file are translated, none of the <name>XXX</name> are translated
![menu_container_translation](https://cloud.githubusercontent.com/assets/17835460/23857450/a7c31046-07fd-11e7-9a5c-857b66a7bba2.PNG)

### System information (as much as possible)
In the file root/administrator/components/com_menus/views/item/tmpl/edit_container.php
the language file loading is based in the component name, it should be based on the admin menu item value as for the standard admin menu:

`if ($extension = $link->componentname):
							$lang->load("$extension.sys", JPATH_ADMINISTRATOR, null, false, true)
							|| $lang->load("$extension.sys", JPATH_ADMINISTRATOR . '/components/' . $extension, null, false, true);
						endif;`

**Comment by zero-24** [comment]
@joeforjoomla please send the change as PR than :smile:

**Comment by joeforjoomla** [comment]
Done: https://github.com/joomla/joomla-cms/pull/14584

**Comment by zero-24** [comment]
Looks like you closed the pr?

**Comment by joeforjoomla** [comment]
Sorry just created a new one https://github.com/joomla/joomla-cms/pull/14585

**Comment by joeforjoomla** [comment]
Closing this issue hence we have a PR https://github.com/joomla/joomla-cms/pull/14585
