### ISSUE TITLE
Create admin menu item Hathor

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14581]
In Hathor it is not possible to create an admin menu item because there is no client selector.

(I tried but failed to code it)

**Comment by brianteeman** [comment]
@izharaazmi could you take a look please

**Comment by izharaazmi** [comment]
Sorry, I totally overlooked hathor. I'll see what can be done.

Btw, are we getting rid of this template any sooner? 😄

**Comment by zero-24** [comment]
@izharaazmi 

> Btw, are we getting rid of this template any sooner? 

Not before 4.0 ;)

**Comment by brianteeman** [comment]
awaiting decision on #15079

**Comment by brianteeman** [comment]
Closing because of

> Important information: We strongly recommend all users to use the Isis template. The Hathor template has not been updated to work with the new features shipping with this release. When we released Hathor it was built with accessibility in mind, but over the years the Isis template has been improved in terms of accessibility and supporting technologies. We now believe that the Isis template is as good as or possibly better than Hathor.
