### ISSUE TITLE
[4.0] Wrong Cursertyp if moving Menu-Items

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14595]
### Steps to reproduce the issue
If moving Menu-Items a Text-Curser is shown instead a 4-Side-Arrow like in 3.*:
![menu-wrong-curser](https://cloud.githubusercontent.com/assets/8235763/23890563/b3ce3952-0892-11e7-83ba-18bcde002a12.gif)
### System information (as much as possible)
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/14600

**Comment by zero-24** [comment]
Closing as we have a PR thanks @C-Lodder
