### ISSUE TITLE
Remove Article/Category dropdown in search under Fields and Field Groups?

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#14591]
Under `Fields` and `Field Groups`, why is there a dropdown to select `Articles` or `Category` when searching?

**Comment by laoneo** [comment]
You can create fields for articles or categories.

**Comment by infograf768** [comment]
Closing as there was a correct reply<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14591">issues.joomla.org/tracker/joomla-cms/14591</a>.</sub>

**Comment by Quy** [comment]
I tried different searches when `Category` is selected in the dropdown and always `No Matching Results `. I don't understand what it is searching for. Please provide example.

**Comment by laoneo** [comment]
Try to create a field when you have selected Categories. Now go to edit a category. You will see the field there.

**Comment by Quy** [comment]
Ahh, I misunderstood the dropwdown. It is to switch between Articles and Categories and not for the Search field adjacent to it. Thanks!
