### ISSUE TITLE
[com_fields] & causes unterminated entity reference warning with List type field

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#14609]
### Steps to reproduce the issue
Create a `List` type field.
Add `R&B` for a list value.
Save and close.
Edit an article to see the following warning:
```
Warning: DOMElement::__construct(): unterminated entity reference B in C:\xampp\htdocs\joomla-cms-staging\administrator\components\com_fields\libraries\fieldslistplugin.php on line 44

Warning: FieldsListPlugin::onCustomFieldsPrepareDom(): unterminated entity reference B in C:\xampp\htdocs\joomla-cms-staging\administrator\components\com_fields\libraries\fieldslistplugin.php on line 45
```

**Comment by franz-wohlkoenig** [comment]
@Quy what is R&B?

**Comment by Quy** [comment]
R&B stands for Rhythm And Blues. It is only an example. It appears that the `&` is the culprit for the warning.

**Comment by franz-wohlkoenig** [comment]
Confirmed:
![bildschirmfoto 2017-03-14 um 15 41 53](https://cloud.githubusercontent.com/assets/8235763/23905916/d520d9ae-08cc-11e7-9fdf-2f11cba8f257.JPG)

**Comment by franz-wohlkoenig** [comment]
@Quy can you please append in front of Title: [com_fields] – thanks.

**Comment by laoneo** [comment]
Please test pr #14797 which should eliminate the error. Guess this issue can be closed.

**Comment by zero-24** [comment]
Closing as therevis a PR thanks
