### ISSUE TITLE
[4.0] Arrows in `Menus: Items` like in `Modules > Menu Assignment`

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14606]
### Steps to reproduce the issue
in `Modules > Menu Assignment` are Arrows to expand and hide Menu-Levels:
![bildschirmfoto 2017-03-14 um 14 01 53](https://cloud.githubusercontent.com/assets/8235763/23902050/f8473872-08bf-11e7-9e8a-5fa2a92e0c16.JPG)
![bildschirmfoto 2017-03-14 um 14 02 17](https://cloud.githubusercontent.com/assets/8235763/23902067/0925b66e-08c0-11e7-9125-5adf20dd3946.JPG)
in `Menus: Items` is this not:
![bildschirmfoto 2017-03-14 um 14 11 09](https://cloud.githubusercontent.com/assets/8235763/23902108/353b1a8c-08c0-11e7-8eec-adc097773713.JPG)
If possible please enhance.
### System information
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
Not really sure what you are asking for. Is it that the menu tree in the list of menu items will expand/collapse like in the module assignments?

That would be impossible to achieve because you can sort the menu items by other criteria
