### ISSUE TITLE
[4.0] Modules > Menu Assignment: More Space on Select-Row

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14605]
### Steps to reproduce the issue
In Select-Row are on 2 Parts less Space:
![1](https://cloud.githubusercontent.com/assets/8235763/23901883/6ed87dc6-08bf-11e7-9550-5451874aa011.png)
### System information (as much as possible)
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
@ciar4n - could you take a look at this when you get a mo please?

**Comment by yasirunilan** [comment]
Issue can be confirmed.

**Comment by yasirunilan** [comment]
How about this sort of a fix? any feedback?


![3](https://cloud.githubusercontent.com/assets/9814784/24073727/f72a7ba6-0c21-11e7-8f79-f4ff38e7b09b.PNG)

**Comment by franz-wohlkoenig** [comment]
@yasirunilan can you please make a PR?

**Comment by ciar4n** [comment]
PR created.. #15276

**Comment by franz-wohlkoenig** [comment]
closed having PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14605">issues.joomla.org/tracker/joomla-cms/14605</a>.</sub>
