### ISSUE TITLE
Errors in administrator after clean installation using MSSQL server as DB.

### ISSUE THREAD

**Issue by Maartinsh** [joomla/joomla-cms#14608]
### Steps to reproduce the issue
Installing joomla 3.6. After installation -> administrator -> global configuration

### Expected result

Global configuration interface.

### Actual result

 Warning: Invalid argument supplied for foreach() in ..\libraries\joomla\database\query\sqlsrv.php on line 394

### System information (as much as possible)

Joomla 3.6
PHP 5.6
Wamp 3.2
MSSQL SERVER 2016

### Additional comments

This type of errors are alot of places in administrator. For instance, when trying to add articles -> Error occures (Microsoft][ODBC Driver 11 for SQL Server][SQL Server]No column name was specified for column 1 of 'A'. SQL=SELECT * FROM ( SELECT count(id) , ROW_NUMBER() OVER (ORDER BY (select 0)) AS RowNumber FROM #__usergroups) A WHERE A.RowNumber BETWEEN 1 AND 1
 Return to Control Panel)

**Comment by zero-24** [comment]
@Maartinsh Which exact version of Joomla do you use? Can you try the last beta release of 3.7 and confim that it is still a issue?

**Comment by Maartinsh** [comment]
@zero-24 Thank you! 3.7 works flawless! 👍

**Comment by franz-wohlkoenig** [comment]
@Maartinsh if Issue is solved please close it.

**Comment by zero-24** [comment]
Thanks for cheking. As 3.7 is the next release i'm going to close here.
