### ISSUE TITLE
[4.0] Menu Items > Layout: `Select Categories` looks messed

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14610]
#### Open a `Menu Item`, Type `Featured Articles` Tab `Layout`:
![1](https://cloud.githubusercontent.com/assets/8235763/23906185/89f35eb0-08cd-11e7-83e5-3738df2d9a9d.png)
#### Compare Joomla 3:
![j3](https://cloud.githubusercontent.com/assets/8235763/23906203/9558eeaa-08cd-11e7-8060-3b0b78b194bc.JPG)
### System information
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
@dgt41 isn't this the one we're waitng for awsomeplete to be updated for?

**Comment by dgt41** [comment]
Yup! the pull request is already in the other repo
