### ISSUE TITLE
Popular & Latest Articles - admin modules

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14619]
The category selector for both of these modules is a single select but the tooltip implies it should be a multi select.

This is either a copy & paste error from the equivalent front end modules which are multiple select or an error in the module xml where they should be defined as multiples.

Any suggestion what the correct behaviour should be so it can be fixed

MOD_LATEST_FIELD_CATEGORY_DESC="Select Articles from a specific Category or set of Categories."

MOD_POPULAR_FIELD_CATEGORY_DESC="Select Articles from a specific Category or set of Categories."

**Comment by bertmert** [comment]
After code review (helper.php) of both modules:
Description should be something like "Select only articles from one specific Category.".  Otherwise from all categories.
Multiple categories is not intended in helper.php

```
// Set Category Filter
$categoryId = $params->get('catid');
if (is_numeric($categoryId))
{
 $model->setState('filter.category_id', $categoryId);
}
```

**Comment by brianteeman** [comment]
Ok thanks for  confirming that the code only supports a single select

**Comment by brianteeman** [comment]
See #14621
