### ISSUE TITLE
Statistics plugin - debug options

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14614]
do we need the debug option? It says this is to send a report on every page load? Is that of any use to us at all @mbabker or is this a remnant code block that should have been removed

<img width="454" alt="screenshotr15-48-52" src="https://cloud.githubusercontent.com/assets/1296369/23909157/e4094784-08cd-11e7-8e0d-470f15f2900b.png">

**Comment by mbabker** [comment]
Guess it's easier than hacking around the code or database if you're doing something that needs to trigger a send on every request.  But there's no practical use for it for all but like 3 or 4 people I'd guess.

**Comment by brianteeman** [comment]
Yeah thats what I was thinking - dont really see the need for this in core

**Comment by brianteeman** [comment]
Should I remove it?

**Comment by zero-24** [comment]
:+1: @brianteeman

**Comment by mbabker** [comment]
I'm impartial either way.  On the one hand if you ever have to work on the plugin it's going to be a useful thing to have, on the other hand it's not something most anyone would ever have a legitimate use for.

**Comment by zero-24** [comment]
What about make it use JDEBUG? or something like we have in the update mail plugin? ;)

**Comment by zero-24** [comment]
https://github.com/joomla/joomla-cms/blob/staging/plugins/system/updatenotification/updatenotification.php#L12

**Comment by brianteeman** [comment]
If you ever have to work on the plugin then the two or three people that will need to will be more than cpaable of adding the required code manually

**Comment by brianteeman** [comment]
Closed as we have a PR see #14634
