### ISSUE TITLE
[3.7] Warning in `Multilingual Associations: Edit Associations`

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14624]
### Steps to reproduce the issue
Open Reference and Target in Multilingual Associations:
![bildschirmfoto 2017-03-14 um 20 05 25](https://cloud.githubusercontent.com/assets/8235763/23918068/cab90994-08f1-11e7-9a9c-a6745ae572db.JPG)
### System information
Joomla! 3.7.0-rc1
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by zero-24** [comment]
@franz-wohlkoenig do you still have the field with R&B from https://github.com/joomla/joomla-cms/issues/14609 ?

**Comment by franz-wohlkoenig** [comment]
Shame on me, thanks @zero-24

**Comment by zero-24** [comment]
No problem 😄
