### ISSUE TITLE
[4.0] CodeMirror broken on Custom HTML module

### ISSUE THREAD

**Issue by JanKrohn-Khalibre** [joomla/joomla-cms#14629]
### Steps to reproduce the issue

* Select CodeMirror as the default editor
* add a new Custom HTML module or edit an existing one

### Expected result

I can edit the custom HTML code in CodeMirror

### Actual result

I can see the custom HTML code in a textbox, but can't save any changes.

### System information (as much as possible)

PHP Built On	Linux server.heidoc.net 2.6.32-042stab112.15 #1 SMP Tue Oct 20 17:22:56 MSK 2015 x86_64
Database Version	5.5.5-10.1.21-MariaDB
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.1.2
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 4.0.0-dev dev [ Amani ] 8-February-2017 14:11 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

### Additional comments

* Other editors work just fine
* CodeMirror works just fine on other screens

![screen shot 2017-03-15 at 02 13 49](https://issues.joomla.org/uploads/1/ec222ef71b05990058e38f3af89755ae.png)

**Comment by franz-wohlkoenig** [comment]
Can't confirm:
![bildschirmfoto 2017-03-15 um 07 53 07](https://cloud.githubusercontent.com/assets/8235763/23936830/7c55194c-0954-11e7-8290-0a592c4ef97b.JPG)
### System information
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
Can't confirm either.

Please try fetching the latest code from the repo, reinstalling Joomla 4 and trying again.

**Comment by JanKrohn-Khalibre** [comment]
I'm testing on a fresh installation from the nightly build. Is the code in the repo any different?

**Comment by JanKrohn-Khalibre** [comment]
I'll also test different browsers.

**Comment by dgt41** [comment]
@JanKrohn-Khalibre you can try also applying this patch: https://github.com/joomla/joomla-cms/pull/14575

**Comment by JanKrohn-Khalibre** [comment]
Issue still occurring after fresh installation, both on Chrome and Edge.

![image](https://cloud.githubusercontent.com/assets/5867975/24028837/dfaa2116-0b04-11e7-806f-575db4ef4820.png)
![image](https://cloud.githubusercontent.com/assets/5867975/24028845/f1cfa58c-0b04-11e7-96f9-133d812fec39.png)

I wonder why this error happens on the edit module screen, and not on the edit article screen. I'll keep researching.

**Comment by C-Lodder** [comment]
@JanKrohn-Khalibre did you try with the patch mentioned above?

**Comment by wilsonge** [comment]
This is now working again for me in the 4.x branch after doing some fixes today. Please post here if it's still an issue for you :)
