### ISSUE TITLE
[com_tags] Teaser-Image: `Caption` is `Title`

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14636]
### Steps to reproduce the issue
Tab `Images`: Append `Caption`-Text for `Teaser Image`:
![1](https://cloud.githubusercontent.com/assets/8235763/23946941/ca4b6c3c-097c-11e7-996a-7f9c4119c7f8.png)

### Expected result
Caption-Text is shown near Image.

### Actual result
Text is shown if you hover the Image, so its a `Title`.
![2](https://cloud.githubusercontent.com/assets/8235763/23947171/dbe8a9fe-097d-11e7-9e6b-e71a24814206.png)

### System information
Joomla! 3.7.0-rc1
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by Bhola-B2C** [comment]
How to produce this issue ?
Complete link.... i.e, from where Administrator ?

**Comment by franz-wohlkoenig** [comment]
- Backend: Open a Tag, Tab `Images` (Screenshot above). 
- Frontend: Move Curser over Teaser Image and wait till Title is shown.

**Comment by brianteeman** [comment]
Yes that is the correct behaviour - look at the generated source<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14636">issues.joomla.org/tracker/joomla-cms/14636</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@brianteeman in Backend its called `Caption`, so this is something at ie. Bottom of Picture to show user additional Infos without hover. Mean: The Fieldname `Caption` is wrong.

**Comment by wilsonge** [comment]
PR https://github.com/joomla/joomla-cms/pull/13906

**Comment by brianteeman** [comment]
@wilsonge that PR is not related

**Comment by dgt41** [comment]
@wilsonge @brianteeman we need to rethink the caption implementation for J4, esp since tinyMCE is using `<figure>` we should consider moving there as well

**Comment by brianteeman** [comment]
... and get rid of the stupid caption js

**Comment by SharkyKZ** [comment]
How to proceed here? Fix 3.x by adding missing `JHtml::_('behavior.caption');` or fix 4.0 only? Or separate PRs against both branches?

**Comment by ghost** [comment]
i suggest to fix 3.x too as this Version has few Years of Live.

**Comment by SharkyKZ** [comment]
See PR #20648.
