### ISSUE TITLE
[com_tags] Alt-Text of Teaser Image isn't shown in Sourcecode

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14635]
### Steps to reproduce the issue
Tab `Images`: Append `Alt`-Text for `Teaser Image`:
![1](https://cloud.githubusercontent.com/assets/8235763/23946700/bc156bf0-097b-11e7-8123-26a87ac0b1e3.png)
### Expected result
`Alt`-Text is shown in Sourcecode
### Actual result
![2](https://cloud.githubusercontent.com/assets/8235763/23946721/d4ce2826-097b-11e7-9d87-57e0469b15dd.JPG)
### System information
Joomla! 3.7.0-rc1
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
What is the front end menu item view you are using? Looks like the same is true for the full images as well but I am struggling to find the view used to show the teaser image - i rarely if ever use com_tags ;)

**Comment by franz-wohlkoenig** [comment]
index.php/en/component/tags/

No Menu to get only Tags-Issues. Using Protostar.

**Comment by franz-wohlkoenig** [comment]
@brianteeman Full-Image-Alt & Sourcecode: #14660

**Comment by brianteeman** [comment]
Closed as we have a PR ##14665
