### ISSUE TITLE
[com_associations] Newsfeeds Notice displayed

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14647]
### Steps to reproduce the issue
In the multilingual associations component and select Newsfeeds as the Item type and any language (not all)

### Expected result
No errors

### Actual result
Notice displayed
> Notice: Trying to get property of non-object in administrator\components\com_associations\helpers\associations.php on line 523

<img width="1044" alt="screenshotr18-41-07" src="https://cloud.githubusercontent.com/assets/1296369/23965259/4f8b5ba0-09af-11e7-9e54-a0bfd0b01a65.png">

**Comment by zero-24** [comment]
hmm can you double check that you are on the last staging as the error just points to a opening `{`. ?

https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_associations/helpers/associations.php#L523

**Comment by brianteeman** [comment]
Updated staging and it show line 531

**Comment by brianteeman** [comment]
closed as we have a Pr
