### ISSUE TITLE
Showon looks a little 'trippy' with nultiple fields

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#14645]
### Steps to reproduce the issue
Have multiple showon fields.

Eg. 

```
<field name="sample_sw" type="radio" label="Sample Switch" default="1" 
	checked="checked" 
	class="btn-group">
<option value="0">JNO</option>
<option value="1">JYES</option>
</field>
<field name="sitetitle1"  type="text" default="" label="Sample Field" showon="sample_sw:1"/>
<field name="sitetitle2"  type="text" default="" label="Sample Field" showon="sample_sw:1"/>
<field name="sitetitle3"  type="text" default="" label="Sample Field" showon="sample_sw:1"/>
<field name="sitetitle4"  type="text" default="" label="Sample Field" showon="sample_sw:1"/>
<field name="sitetitle5"  type="text" default="" label="Sample Field" showon="sample_sw:0"/>
<field name="sitetitle6"  type="text" default="" label="Sample Field" showon="sample_sw:0"/>
<field name="sitetitle7"  type="text" default="" label="Sample Field" showon="sample_sw:0"/>
<field name="sitetitle8"  type="text" default="" label="Sample Field" showon="sample_sw:0"/>
```

### Expected result
Possibly have the fields fade in/out after slideDown and before slideUp

### Actual result
![showon1](https://cloud.githubusercontent.com/assets/2803503/23962014/aa6583a8-09a4-11e7-8d5d-26dcd65a5e4f.gif)

![showon2](https://cloud.githubusercontent.com/assets/2803503/23962118/fe9be80e-09a4-11e7-8f3f-fea5de341417.gif)

### Additional comments
I have tried fixing this however ran in to trouble with certain variations (eg. the above XML where fields are both displayed and hidden with a switch).

**Comment by brianteeman** [comment]
Not as "trippy" as this

![trippy](https://cloud.githubusercontent.com/assets/1296369/24042896/f415e19c-0b0b-11e7-8139-4cc71a3bb2b0.gif)

**Comment by brianteeman** [comment]
I think we are just going to have to close this as "one of those weird  things if you do weird things" issues
