### ISSUE TITLE
[4.0] Joomla Update: File-Name too long

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14657]
### Steps to reproduce the issue
Joomla Update > Joomla Package File: Append a nightly-Build:
![bildschirmfoto 2017-03-16 um 07 31 57](https://cloud.githubusercontent.com/assets/8235763/23984707/3f744cce-0a1b-11e7-9830-ed6df1e65f00.JPG)
### System information
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/14673
