### ISSUE TITLE
Global configration Error Reporting settings

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14650]
In global configuration the tooltip for the Error Reporting settings says
> COM_CONFIG_FIELD_ERROR_REPORTING_DESC="Select the level of reporting. See the Help Screen for full details."

But when you open the help screen by clicking on the help button in the toolbar and the page https://help.joomla.org/proxy/index.php?keyref=Help37:Site_Global_Configuration is loaded in a popup the only information about the error reporting says is 

> Error Reporting: (System Default/None/Simple/Maximum/Development). Select the appropriate level of reporting from the drop down list. See the Help Screen for full details.

paging @MATsxm

**Comment by MATsxm** [comment]
@brianteeman 
Is this could be ok?
(if I understand well what you want)

> Error Reporting. This parameter sets the level of error reporting to be used by PHP on the Joomla site. It has five options: System Default, None, Simple, Maximum and Development. “System Default” leaves the level of PHP error reporting to that set up in the server (usually in the php.ini file). “None” switches off PHP error reporting, and “Simple”, “Maximum” and “Development” override the server setting to give a basic level of reporting (for “Simple”) and the reporting of all errors (“Maximum” and “Development”).

**Comment by MATsxm** [comment]
Updated here and forced FuzzyBot to crawl the page.
https://docs.joomla.org/Help36:Site_Global_Configuration
I guess we will need time for the "help proxy" and/or caches but the Helpscreen called is ok (https://docs.joomla.org/Help36:Help_screens)

**Comment by brianteeman** [comment]
great thanks - I can close this here then :)
