### ISSUE TITLE
[com_tags] Menu `List of all tags`: `Maximum Characters` not respected

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14667]
#### Set `Maximum Characters` to "4":
![bildschirmfoto 2017-03-16 um 14 57 23](https://cloud.githubusercontent.com/assets/8235763/23999680/62772d84-0a59-11e7-9aa4-7621e57e060f.JPG)
#### In Frontend full Description is showed:
![bildschirmfoto 2017-03-16 um 14 59 07](https://cloud.githubusercontent.com/assets/8235763/23999775/96c3d2a4-0a59-11e7-995c-9823c112bac5.JPG)
### System information
Joomla! 3.7.0-rc1
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
if i am correct then the option to hide the tags also doesnt work - can you confirm

**Comment by franz-wohlkoenig** [comment]
@brianteeman which Option you mean? It's the Menu item Type `List of all Tags` without Option hiding Tags. You can hide `Tag Descriptions`, which works.

**Comment by yasirunilan** [comment]
For what is this maximum character amount is given? is it for the description?

**Comment by franz-wohlkoenig** [comment]
@yasirunilan Characters count for Discreption, point Curver above `Maximum Characters` you get Tooltip.

**Comment by yasirunilan** [comment]
The word maximum characters doesn't give that idea, isn't it?

**Comment by franz-wohlkoenig** [comment]
Thats what Tooltips are for but a polished UI would reduce looking at Tooltips.

**Comment by rdeutz** [comment]
Does this option makes sense at all?

**Comment by franz-wohlkoenig** [comment]
@rdeutz makes no Sense. If Tag-Names are too long its better to reduce the Number of Columns than truncate Tags.

**Comment by rdeutz** [comment]
I made a PR for fixing the issue #16929
