### ISSUE TITLE
[com_tags] Alt-Text of Full Image isn't shown in Sourcecode

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14660]
#### 1. Select an Full-Image and append Alt-Text:
![1](https://cloud.githubusercontent.com/assets/8235763/23988351/2408cf2e-0a2e-11e7-8978-ffb69e6c9e8c.JPG)
#### 2. Display in Frontend is correct:
![2](https://cloud.githubusercontent.com/assets/8235763/23988364/3c233e46-0a2e-11e7-8f2d-4d5896cffaab.JPG)
#### 3. Sourcecode don't show Alt-Text:
![3](https://cloud.githubusercontent.com/assets/8235763/23988375/4e99b6b8-0a2e-11e7-8d10-5df0cddded3d.JPG)
### System information
Joomla! 3.7.0-rc1
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
Closed as we have a PR ##14665
