### ISSUE TITLE
Categories on the issue tracker

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14664]
is there a reason that Issues are no longer being categorised on the Issue tracker? it was very useful

**Comment by mbabker** [comment]
Auto categories or someone manually doing it?

**Comment by brianteeman** [comment]
Autocategories is only for PR not issues

I used to do it manually - I assume others that  had access used to do it as well. 

There used to be zero issues without category - now there are 5 pages

It was particularly useful during sprints

**Comment by mbabker** [comment]
Nudging @nibra

**Comment by nibra** [comment]
Can't see an option to add categories. /me being blind? Missing permissions? My username on the tracker is nibra.

**Comment by mbabker** [comment]
It looks like you weren't in the JBS group on the tracker to do it yourself, added you now.

Users in JBS group:

- MAT978
- vdespa
- SniperSister
- Hackwar
- infograf768
- pjwiseman
- Harmageddon
- nibra
- chrisdavenport
- richard67
- dgt41
- gunjanpatel
- PhilETaylor
- andrepereiradasilva

Users in the maintainer group (adds manage permission on the tracker, which IIRC lets them manage the ACL basically)

- wilsonge
- Bakual
- javigomez
- zero-24
- roland-d
- chrisdavenport
- rdeutz
- Kubik-Rubik
- jeckodevelopment

**Comment by nibra** [comment]
Thank you, Michael!

**Comment by brianteeman** [comment]
sorry my message above must have crossed out of sync so it made no sense and i have deleted it

**Comment by nibra** [comment]
@mbabker Can't edit/remove Joomla! CMS #13208 since the GitHub entry is gone. How should that be handled?

**Comment by mbabker** [comment]
Deleted it in the database.

**Comment by nibra** [comment]
Made the JBS Team aware (call to action), also working on it myself. This can be closed.
