### ISSUE TITLE
Install from Web message

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14672]
> Joomla! Extensions Directory™ (JED) now available with Install from Web on this page.	By selecting "Add Install from Web tab" below, you agree to the JED Terms of Service and all applicable third party license terms.

I was going to do a PR to change NOW to IS as it has now been available for a long time. But then I saw 
>  all applicable third party license terms.

I have no idea what those terms are or how you can legally agree to a term that you cannot see first.

**Comment by jeckodevelopment** [comment]
Not sure about which terms we're talking about.
Third party licenses for code included in IFW?

**Comment by brianteeman** [comment]
Whatever they are you cannot agree to them without seeing them

**Comment by Bakual** [comment]
By installing the IFW tab, you don't have to agree to any 3rd party terms anyway.
If you install any software **using** that IFW tab, **then** you may have to agree to terms of the extension you're installing, but that's a completely different story.

I would just remove that part of the string.

**Comment by zero-24** [comment]
> If you install any software using that IFW tab, then you may have to agree to terms of the extension you're installing, but that's a completely different story.

Yes but is there a check or message that you need to check / agree on that?

**Comment by alikon** [comment]
imo should be managed like all plugins no message at all 
guess defualt disabled ?

**Comment by Bakual** [comment]
> Yes but is there a check or message that you need to check / agree on that?

For downloading/installing an extension? There is no check or message of course. Similar to how there is none if you download it using JED itself.

**Comment by jeckodevelopment** [comment]
imho we can change this message.
@brianteeman can you do it, please?

**Comment by brianteeman** [comment]
closed as we have a PR #14682
