### ISSUE TITLE
[com_fields] Parameter "Default Users" in Custom Fields

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#14674]
The Parameter Field "Default value" changed into "Default Users". I think this was done in this PR: https://github.com/joomla/joomla-cms/pull/14404
But I do not understand why?

If I create a Custom Field of the Type Media and insert into the Parameter Field "Default Users" a comma separeted list of User IDs I see no result.

If I create a Custom Field of the Type Media and insert into the Parameter Field "Default Users" an image, this image is the default of the field.

![articles edit field a administration](https://cloud.githubusercontent.com/assets/9974686/24006945/768655de-0a6d-11e7-98e6-7b9909d2e718.png)

**Comment by brianteeman** [comment]
Yes it looks like the PR was wrong as it was intended to just solve an issue with the User field type but seems to have effected them all.

@laoneo can you take a look please

@zero-24 @rdeutz can we have a release blocker?

**Comment by zero-24** [comment]
> @zero-24 @rdeutz can we have a release blocker?

@brianteeman can't you do it yourself? I'm in the same team on gitthub than you are 😄 

-> Done 😄

**Comment by laoneo** [comment]
Please check #14679, which should show only on the user field the specific text.

**Comment by zero-24** [comment]
Thanks @laoneo
