### ISSUE TITLE
Login robots tag not present

### ISSUE THREAD

**Issue by alvarodp** [joomla/joomla-cms#14686]
### Steps to reproduce the issue

1. Create menu item for "Login form" (alias: login)
2. In "Metadata" tab, set "Robots" field to "No index, no follow"
3. Go to http://www.example.com/login (Created item)
4. View source

### Expected result

`<meta robots=robots content="noindex, nofollow"/>` should be present.

### Actual result

It is not.

### System information (as much as possible)

- Multilingual enviroment
- PHP 7.1.2
- Apache 2.4.6
- Joomla 3.6.5
- SEF URLs: yes
- URL rewriting: yes
- Unicode Aliases: yes
- Cache: On - Progressive

### Additional comments

It's solved by modifying line 128 of  "components/com_users/views/login/view.html.php":

`$this->document->setMetaData('robots', $this->params->get('robots'), 'robots');`

**Comment by brianteeman** [comment]
I could not replicate this when testing with the current staging

**Comment by franz-wohlkoenig** [comment]
On 3.6.5 `<meta name="robots" content="noindex, nofollow" />` is shown in Source.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14686">issues.joomla.org/tracker/joomla-cms/14686</a>.</sub>
