### ISSUE TITLE
Configuración de componente easy Staging version 1.2.2 en joomla 3.6.5

### ISSUE THREAD

**Issue by maxidabid** [joomla/joomla-cms#14693]
### Steps to reproduce the issue
Al ingresar a la interfaz del componente y configurar los parámetros que son necesarios al presionar el botón de tes sobre el Rsync, se visualiza lo siguiente:

### Expected result
![screen shot 2017-03-17 at 15 18 31](https://issues.joomla.org/uploads/1/997d3e25a4d3fcaa7e4b49f14951e2ba.png)

### Actual result
Con lo cual esto queda en un loop infinito  en el cual no esposible realizar dicho test.

### System information (as much as possible)
Necesitaria saber si tuvieron un inconveniente similiar ya que no logramos resolverlo.

Muchas gracias
Saludos!!

**Comment by jeckodevelopment** [comment]
Hi,
This repository is ONLY for reporting issues with the Joomla! CMS.

For user support issues, please go to: https://forum.joomla.org/ or to the developer of the extension you're using.
Thanks!
