### ISSUE TITLE
User Profiles plugin creates "dob" records, even when the DB field is not active

### ISSUE THREAD

**Issue by Spudley** [joomla/joomla-cms#14691]
I was looking at the records in my `##__user_profile` table recently and noticed there were records there for the dob field, even though that field has always been disabled on my system.

### Steps to reproduce the issue

* Set up the user profile plugin and disable all fields except Terms Of Service.
* Now create a few user accounts.

### Expected result

The new accounts should only have a single record in the user_profile table, being "profile.tos", with a value of "1".

### Actual result

The new accounts actually have two records in user_profile table, "profile.tos" as expected, and also "profile.dob", with a blank value. This dob record should not be getting created.

### System information (as much as possible)

This is on a Joomla system that is currently on v3.6.5, having been upgraded regularly since v3.4.8 as new versions were released.

### Additional comments

The spurious dob record doesn't have any negative effect, other than wasting space in the database, so this isn't a particularly serious bug, but I do consider it a bug nevertheless.

**Comment by Quy** [comment]
It is auto created from this line https://github.com/joomla/joomla-cms/commit/c62bf8ba67bbf01a12e2f7cbd94261bd497679a7#diff-23e0a7ef508c9ce6eac98c42767a6077R327

Removing it fixes this issue. I can do a PR once I get confirmation that it is safe to do.

**Comment by brianteeman** [comment]
@quy can you make the PR and then it can be tested

**Comment by ghost** [comment]
@Quy can you make the Pull Request?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14691">issues.joomla.org/tracker/joomla-cms/14691</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #18224<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14691">issues.joomla.org/tracker/joomla-cms/14691</a>.</sub>
