### ISSUE TITLE
Frontend Submission form: Predefined Category is not selected

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14697]
### Steps to reproduce the issue
- Create Category "A"
- Create a Field Group "Example" for Articles
- Create Field "Testfield" assigned to Group "Example" and to Category "A"
- In Joomla! Global config allow Article Content Creation and Editing Custom Fields for Registered Users.
- Create a Menüitem for submitting Content and it´s set in the options of the menütype to automatically post into Category "A".
- The Category Uncategorised is preselected instead of Category A...
- Custom Fields are not shown

![image](https://cloud.githubusercontent.com/assets/828371/24051086/414170b0-0b31-11e7-83dc-daf89bf5c40b.png)

![image](https://cloud.githubusercontent.com/assets/828371/24051105/4d31d090-0b31-11e7-9ce8-155480b58af5.png)

### Expected result
The category "Stellenangebote" should be shown.

### System information (as much as possible)
Joomla 3.7.0 rc1

**Comment by brianteeman** [comment]
Cannot confirm with current staging

<img width="353" alt="screenshotr16-04-58" src="https://cloud.githubusercontent.com/assets/1296369/24051899/89aaeb84-0b2b-11e7-8d58-af7b53786483.png">
<img width="564" alt="screenshotr16-05-06" src="https://cloud.githubusercontent.com/assets/1296369/24051900/89bfe73c-0b2b-11e7-8149-366bec260511.png">

**Comment by brianteeman** [comment]
Sorry @coolcat-creations i didnt mean to close it. please can you confirm it is indeed fixed in current staging

**Comment by coolcat-creations** [comment]
Maybe it has something to do with the Usergroup then. I have the Usergroup Registered and creation allowed?

**Comment by brianteeman** [comment]
My test was with the super user. But i expect that it's something that has
already been fixed so please can you test with current staging to remove
that possibility.

**Comment by coolcat-creations** [comment]
I have different behaviours on staging and on nightly build. None of them works for me like expected.

Let´s speak about staging:
1) Field Group "Example"
2) Field Testfield assigned to Group Example and to Category "A"
1) In Joomla! Global config allow Article Content Creation and editing Custom Fields for registered Users.
2)  I have a Menüitem for submitting Content and it´s set to automaticly post into Category "A". 

I can confirm now that with latest staging it´s posted in the right Category but absolutely no custom fields are displayed.  Either i miss a configuration step or this is a bug?

**Comment by coolcat-creations** [comment]
@brianteeman for me it also does not work for Superuser with these steps ;(

**Comment by brianteeman** [comment]
Your new instructions are different to the original report

**Comment by coolcat-creations** [comment]
I know, didn´t think that it´s connected to custom fields... still don´t think so but i described now better what i did... :) i update the instructions above.

**Comment by dgt41** [comment]
> The Category Uncategorised is preselected instead of Category A...

Custom fields are using some javascript for the category selection, maybe that part is failing
e.g. fails to reload the form with the preselected category 
@laoneo any chance my theory is right?

**Comment by laoneo** [comment]
@dgt41 good catch. Please test pr #14800 which should fix the issue.

**Comment by brianteeman** [comment]
Closed as there is a PR
