### ISSUE TITLE
contact form with email address containing apostrophe doesn't work

### ISSUE THREAD

**Issue by ptrouw** [joomla/joomla-cms#14695]
We have a user with following valid email address with apostrophe: jean.o’malley@xyz.com
This email address is not allowed in Joomla. I think the code should be changed to accept this.
I did fix it temporarily in core file, but this should be changed in a next release I think!

/libraries/joomla/mail/helper.php and replace:
$allowed = 'a-zA-Z0-9.!#$%&’*+\/=?^_`{|}~-';
..with:
$allowed = 'a-zA-Z0-9.!#$%&’*+\/=?^_`{|}~\'-';

Using J3.5.6

**Comment by infograf768** [comment]
Please read

https://en.wikipedia.org/wiki/Email_address#Local-part<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14695">issues.joomla.org/tracker/joomla-cms/14695</a>.</sub>

**Comment by ptrouw** [comment]
Yes I have read it. But what should I notice. So the apostrophe is allowed. Valid email addresses are: #!$%&'*+-/=?^_`{}|~@example.org
So back to my original remark, Joomla should accept this apostrophe on email form.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14695">issues.joomla.org/tracker/joomla-cms/14695</a>.</sub>

**Comment by brianteeman** [comment]
Yes an apostrophe is allowed. However that means the correct asci key for an apostrophe and not just a key that looks like it. 

```
Char	Dec	Hex	Oct
`	96	60	140
'	39	27	47
’	146	92	222
´	180	B4	264

```

Here we can see four different characters that look like an apostrophe. The one you used in your example was 146

The only one that is an apostrophe is 39 and that is what Joomla is allowing as a valid character
