### ISSUE TITLE
If custom field is added in the backend with option "required", then adding/editing an article in frontend becomes impossible - on submit we get en error message "Warning Field required: NameOfField"

### ISSUE THREAD

**Issue by ysrostov** [joomla/joomla-cms#14692]
### Steps to reproduce the issue
http://take.ms/UELYZ
https://monosnap.com/file/ro44ho1KFf21uwugs7lL51kRoHcZFu

the custom field in this case is a newly added field when some articles are already published

**Comment by AlexRed** [comment]
you need to see the "Fields" Tab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14692">issues.joomla.org/tracker/joomla-cms/14692</a>.</sub>

**Comment by laoneo** [comment]
Can you please updated the description with steps that we can reproduce the issue. I can't reproduce it.

**Comment by ysrostov** [comment]
I'm sorry, guys. It seems that the template I was testing in the new installation of 3.7. beta3 by some reason didn't display the Field TAB in frontend editing. I tested this on a new clear installation with the Protostar template and indeed found the Field tab in frontend. Everything seemed fine. 
Thank you for your contribution and effort! Custom fields imo can bring Joomla to a new level in terms of content management scenarios for end users.
I think the issue can be closed by now.
