### ISSUE TITLE
UX - Misleading delete button text

### ISSUE THREAD

**Issue by marcochirienti** [joomla/joomla-cms#14703]
The JToolbarHelper::deleteList method uses as default text the JTOOLBAR_DELETE language key.
The language key JTOOLBAR_DELETE is translated as "Delete".

In core components the language key used for deleteList buttons is JTOOLBAR_EMPTY_TRASH.
The language key JTOOLBAR_EMPTY_TRASH is translated as "Empty trash".

As a non-native English speaker, I think "Empty trash" is misleading.
It sounds to me like "permanently delete all items from the trash". 
And that's not what the button actually do.

The button allows the user to delete selected items, so why don't we use the default "Delete" text?

**Comment by infograf768** [comment]
As far as I know we do have  a difference.
We use `JTOOLBAR_DELETE` when there is no trash for the items i.e. deleting directly.
Example: `administrator/index.php?option=com_installer&view=updatesites`
or
`administrator/index.php?option=com_languages&view=overrides`

**Comment by marcochirienti** [comment]
I think that the difference between items that can be trashed and items that can't be trashed is already clear.

For items that can be trashed, there is another button and is the "Trash" button (JToolbarHelper::trash).
The JToolbarHelper::trash method uses the JTOOLBAR_TRASH language key.
The language key JTOOLBAR_TRASH is translated as "Trash".

In core components the default behaviour in list views is to display only published and unpublished items (archived and trashed items are generally hidden).
If the state filter is set to "trashed" the list view displays the trashed items and the "Empty trash" button in the toolbar. Once an item has been trashed, can be permanently deleted.

What the "Empty trash" does is exactly what the "Delete" button does: permanently deletes an item or a list of items. It does not empty the "trash bin".

For this reason I assume they can have the same text.

**Comment by yasirunilan** [comment]
For this one can we have the same text or a change is required?

**Comment by Quy** [comment]
PR #14954

**Comment by franz-wohlkoenig** [comment]
closed as having PR #14954<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14703">issues.joomla.org/tracker/joomla-cms/14703</a>.</sub>
