### ISSUE TITLE
[com_fields] Usergrouplist params issue

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#14701]
This screenshot explains it more than a thousand words

![screen shot 2017-03-17 at 17 58 12](https://cloud.githubusercontent.com/assets/869724/24054181/9d1c83c0-0b3b-11e7-89d1-3b58e3dbe169.png)

Multiple can't apply here and we need specific Default Usergroups I guess a bit similar to the User field.

@laoneo @Bakual

**Comment by brianteeman** [comment]
why cant it be multiple?

**Comment by infograf768** [comment]
you don't choose Yes and No And sUse plugin together.

We should have a field where we list usergroups ids and no default value: look at user field

**Comment by dgt41** [comment]
@infograf768 the label refers to the field not the select tag next to it, so yes you can have multiple usergroups (it's not multiple values like: yes, no,none)

**Comment by infograf768** [comment]
EDIT:
In fact it is only the DEFAULT VALUE which should be changed as done in User field.
It indeed can be multiple.

**Comment by infograf768** [comment]
![screen shot 2017-03-17 at 18 42 11](https://cloud.githubusercontent.com/assets/869724/24055721/79f8eb30-0b41-11e7-9cf6-d770e250796e.png)

**Comment by infograf768** [comment]
And in this case (when corrected as User), and looking at the code, Multiple is useless. It is no use in the params in the plugin as in the specific created field.

We should have instead of the 2 fields, something like
```
<?xml version="1.0" encoding="utf-8"?>
<form>
	<field
		name="default_value"
		type="textarea"
		filter="raw"
		label="PLG_FIELDS_USERGROUPS_DEFAULT_VALUE_LABEL"
		description="PLG_FIELDS_USERGROUPS_DEFAULT_VALUE_DESC"
	/>
</form>
```
and
```ini
PLG_FIELDS_USERGROUPS_DEFAULT_VALUE_LABEL="Default Usergroups"
PLG_FIELDS_USERGROUPS_DEFAULT_VALUE_DESC="A comma separated list of usergroups ids."
```

**Comment by brianteeman** [comment]
Multiple refers to the USER selecting multiple usergroups when this field is displayed

**Comment by brianteeman** [comment]
<img width="565" alt="screenshotr18-13-08" src="https://cloud.githubusercontent.com/assets/1296369/24056930/65b9e204-0b3d-11e7-8e6b-20329578f39e.png">

**Comment by infograf768** [comment]
ok. now what is the default value for?

**Comment by laoneo** [comment]
The default value preselects some ustegroups when the field is the first time visible when editing an article. If the field got emptied on an article save, then it reverts to the default value. Same behavior as everywhere in Joomla.

**Comment by infograf768** [comment]
Ok, this is what I found.
If one usergroup id is entered in default value, then the chosen usergroup is indeed showing whether Multiple is set to Yes or No.

So, one can't enter in the default value more than one id.

My suggestion is to use specific strings for the default value explaining this.

**Comment by infograf768** [comment]
@laoneo 
Is it worth adding a custom Default Value with a tip to explain what that field may do?

**Comment by laoneo** [comment]
I guess it is not a bad idea. Then another question pops up. Should we then build in better support to override the default label and description, otherwise we always need to define the whole default field as in #14679? When we want to change some parameters in that field, then we need also update all the overrides as well.

**Comment by infograf768** [comment]
If we have time for that, why not indeed.
if not, let's just do it the same way you did for the User field. In both cases, we will need at least one more language string.

**Comment by laoneo** [comment]
Please check #14793 for a label and description override functionality.

**Comment by laoneo** [comment]
Guess we can close this one then.

**Comment by infograf768** [comment]
Closed as we have a patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14701">issues.joomla.org/tracker/joomla-cms/14701</a>.</sub>
