### ISSUE TITLE
ReCaptcha fails behind proxy

### ISSUE THREAD

**Issue by leifneve** [joomla/joomla-cms#14707]
### Steps to reproduce the issue
Configure host with a proxy server.

### Expected result
ReCaptcha should still work normally.

### Actual result
ReCaptcha fails. The JHttpResponse->body method strips off the proxy server headers but leaves intact the headers from the originating server. So ReCaptcha, which needs a clean JSON response in the body is unable to parse the response and fails. 

### System information (as much as possible)
PHP Built On 	Linux orbit 2.6.32-642.15.1.el6.x86_64 #1 SMP Mon Feb 20 02:26:38 EST 2017 x86_64
Database Version 	5.1.73
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8_general_ci
PHP Version 	5.6.9
Web Server 	Apache
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0

### Additional comments
I suspect this is also why the updater has never worked for me behind the proxy, but works elsewhere. A brief glance at the updater reveals that it also relies on the XML returned from the JHttpResponse->body method.

**Comment by brianteeman** [comment]
Did you set the proxy in joomla global configuration?

**Comment by mbabker** [comment]
This is fixed for curl in 3.7... https://github.com/joomla/joomla-cms/pull/13221

**Comment by leifneve** [comment]
Yes.

In Global Configuration -> Server:

Enable Proxy: Yes

Proxy Host: 130.14.55.36

Proxy Port: 3128

**Comment by brianteeman** [comment]
As @mbabker has pointed out this has been solved for the next release 3.7

**Comment by leifneve** [comment]
Why did you guys close this? This has nothing to do with curl. How do I reopen it?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14707">issues.joomla.org/tracker/joomla-cms/14707</a>.</sub>

**Comment by mbabker** [comment]
The cURL transport that populates the body was adjusted as noted in the linked item to better handle proxy responses.

**Comment by leifneve** [comment]
I guess what you are saying is that curl is used to implement JHttpGet and so this problem should be fixed. That's great news if so.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14707">issues.joomla.org/tracker/joomla-cms/14707</a>.</sub>
