### ISSUE TITLE
[4.0] - Send Test email button

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#14738]
Given the 'Send Test Mail' button in the Joomla! Global config is an action to run a test I suggest we make it btn-primary i.e. blue. 

Currently looks like:
![screen shot 2017-03-18 at 17 36 24](https://cloud.githubusercontent.com/assets/1400982/24074489/a77a8328-0c01-11e7-97e3-a1bd3b8b40f5.jpg)
It would look like:
![screen shot 2017-03-18 at 17 36 12](https://cloud.githubusercontent.com/assets/1400982/24074488/a60e9c7c-0c01-11e7-84ce-1e94e90e9914.jpg)

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/14751

**Comment by tonypartridge** [comment]
Closed thanks @C-Lodder
