### ISSUE TITLE
[4.0] Tags: Switch `Match Type` blue Color instead green

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14736]
### Steps to reproduce the issue
Switch `Match Type` has blue Color instead green:
![bildschirmfoto 2017-03-18 um 17 55 25](https://cloud.githubusercontent.com/assets/8235763/24074208/4c6b1774-0c04-11e7-9117-658f1aca8211.JPG)

### System information
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by tonypartridge** [comment]
Hi @franz-wohlkoenig ,

Thanks for pointing this out. But to make it green would indicate it would then be 'Right' and therefore grey is 'Wrong'. But actually this is a choice selection. That's the idea behind it. But there is a debate from both sides.

Many thanks
Tony
