### ISSUE TITLE
Default ReCaptcha

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#14734]
### Steps to reproduce the issue
View: Global Config -> Site -> Default ReCaptcha. If no plugins are enabled it shows - None Selected -. This is misleading since they cannot select a ReCaptcha Plugin. 

I suggest we also override the getInput method and change noticed, do not render a list and instead output a message:

No ReCaptcha plugins enabled/installed.

Or similar. 

Thoughts?

#UX ?

**Comment by brianteeman** [comment]
It's selected in the plugin. Also see the toolkit

**Comment by brianteeman** [comment]
Tooltip

**Comment by tonypartridge** [comment]
@brianteeman No, you set the Captcha in the global config as per my notes above see:

![screenshot 2017-03-17 09 37 28](https://cloud.githubusercontent.com/assets/1400982/24074090/15ecf776-0bfa-11e7-9311-75ebc10ef36b.jpg)


This produces a select list which is indicating the to user they can select something. Nothing is selectable since no Captcha plugins are enabled by default. Furthermore, the ReCaptcha plugin lets you choose between two versions of ReCaptcha.

**Comment by brianteeman** [comment]
@tonypartridge would you be happy with a quick fix of just changing the string from "none selected" to just "none"

**Comment by tonypartridge** [comment]
Closing as we have a PR.
