### ISSUE TITLE
[4.0] - Debug mode needs review

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#14735]
@C-Lodder see:
![screen shot 2017-03-18 at 16 55 17](https://cloud.githubusercontent.com/assets/1400982/24074211/f0f3414e-0bfb-11e7-89b8-d8346d587fc3.jpg)

Thoughts about setting it fixed at the bottom in the right pane. So it respect the left sidebar

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/14739

**Comment by brianteeman** [comment]
closed as we have a pr
