### ISSUE TITLE
[4.0] [com_fields] Articles-Dropdown misalignment

### ISSUE THREAD

**Issue by yasirunilan** [joomla/joomla-cms#14742]
### Steps to reproduce the issue
Main Menu -> Content -> Fields

### Expected result
Articles drop down aligned in a row with other search and search tools components.

### Actual result

![align](https://cloud.githubusercontent.com/assets/9814784/24078225/1bd4ae4c-0c8e-11e7-8de2-25712fcffb67.PNG)

### System information (as much as possible)

Joomla! 4.0.0-dev
Windows 10
Chrome 57.0.2987.110 (64-bit) 
PHP 5.6

**Comment by franz-wohlkoenig** [comment]
known Issue #14183

**Comment by yasirunilan** [comment]
@franz-wohlkoenig can I create a PR for this?

**Comment by franz-wohlkoenig** [comment]
please do a PR.

**Comment by yasirunilan** [comment]
Okay, I'm working on it

**Comment by yasirunilan** [comment]
is this okay?

![align 2](https://cloud.githubusercontent.com/assets/9814784/24079081/b7d90466-0ca5-11e7-9bfa-d22b25728c06.PNG)

**Comment by franz-wohlkoenig** [comment]
looks fine. Can you make a PR for Tests?

**Comment by yasirunilan** [comment]
okay (Y)

**Comment by franz-wohlkoenig** [comment]
@yasirunilan can you please make a PR?

**Comment by franz-wohlkoenig** [comment]
closed as having PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14742">issues.joomla.org/tracker/joomla-cms/14742</a>.</sub>
