### ISSUE TITLE
Recently added articles sorting admin panel

### ISSUE THREAD

**Issue by frostmakk** [joomla/joomla-cms#14749]
### Steps to reproduce the issue
Set up clean bare bones installations of 3.6.5 and 3.7.0 on Wamp localhost.
Create five articles in each installation.
Go to admin controlpanel.

### Expected result
Latest articles should be sorted equal in both versions

### Actual result
Recently added articles sorted correctly in 3.6.5 but not in 3.7.0

### System information (as much as possible)
Tested with PHP 5.6 and 7.1 
Error reporting maximum, but no errors observed.
### Additional comments
Tried replacing template and \administrator\modules\_mod_latest with 3.6.5's versions, but no change.
Another observation that may be related: When opening articles in backend, the default sorting order is ID descending.
With 3.6.5 the articles are sorted correctly, but 3.7.0 opens with the articles in ascending order.
If you change anything that triggers a page refresh, like changing the number of articles shown, the sorting is done correctly.
Can it be some sort of "on open" event not beeing triggered?

**Comment by AlexRed** [comment]
I can confirm the problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14749">issues.joomla.org/tracker/joomla-cms/14749</a>.</sub>

**Comment by frostmakk** [comment]
Looks like this one broke it.
#13123 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14749">issues.joomla.org/tracker/joomla-cms/14749</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a PR #14943
