### ISSUE TITLE
[4.0] Layout issue in Media

### ISSUE THREAD

**Issue by yasirunilan** [joomla/joomla-cms#14741]
### Steps to reproduce the issue
In the main menu select Media and click it.

### Expected result
Items in the page should be in a order with spacing

### Actual result
![layout](https://cloud.githubusercontent.com/assets/9814784/24078171/5ca72e24-0c8c-11e7-8ab0-8506f109a2f2.PNG)

### System information (as much as possible)
Joomla! 4.0.0-dev
Windows 10
Chrome 57.0.2987.110 (64-bit)
PHP 5.6

**Comment by franz-wohlkoenig** [comment]
known Issue #14039

**Comment by Bakual** [comment]
@wilsonge Maybe it would be great to have a "Known issue" list somewhere public. So people know what to expect when trying out J4.
Eg "Template still work in progress" and "MediaManager gets a complete redesign".

**Comment by franz-wohlkoenig** [comment]
@Bakual would show a Message in 4.0 like Patchtester shows.

**Comment by mbabker** [comment]
Patch tester is easy to put a message in.  And I honestly put it there not because the code is broken now, but because since it is a moving target still, there's no guarantee it won't be broken.

Putting those messages in core would add a lot of maintenance overhead.  Any known issues should easily be found with either GitHub's or our own issue tracker's search/filters.

**Comment by franz-wohlkoenig** [comment]
@mbabker less People search before report an issue. Is an Info at "Media" an easy Solution?
![bildschirmfoto 2017-03-19 um 09 08 44](https://cloud.githubusercontent.com/assets/8235763/24079262/de2a7c48-0c83-11e7-9bef-0883ccc6cd73.JPG)

**Comment by yasirunilan** [comment]
@franz-wohlkoenig I think that's better.

**Comment by mbabker** [comment]
It is easy to put whatever notifications we want into core, but that doesn't mean it's appropriate.  And to be honest it is not appropriate to ever check into the code a warning mechanism that essentially says "this section is a work in progress, see X issue for more details".

**Comment by franz-wohlkoenig** [comment]
@mbabker i understand, on other Hand we get known Issues reported. If an "Known issues"-List is the easy Solution, i'm fine with it.

**Comment by C-Lodder** [comment]
The new media manager has not yet been merged, so I'm not going to bother styling something that'll be replaced. 

This can be closed.

**Comment by wilsonge** [comment]
I'm going to leave this open. But don't expect much progress, there's no need to do this for now whilst @laoneo 's team is working on the revamped media manager. If it looks like that won't make it for J4 for whatever reason it's not a huge amount of work to go back style that

**Comment by franz-wohlkoenig** [comment]
@wilsonge shouldn't this be closed cause of https://developer.joomla.org/roadmap.html?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14741">issues.joomla.org/tracker/joomla-cms/14741</a>.</sub>

**Comment by mbabker** [comment]
No.  Legitimate issues should not be closed just because something is a known work in progress or planned to be replaced.  Because if the plan to replace it doesn't get followed up on for whatever reason, then this has to be acted upon.  It's a low priority issue, but one nonetheless.

**Comment by franz-wohlkoenig** [comment]
thanks for Info, @mbabker

**Comment by C-Lodder** [comment]
@franz-wohlkoenig  - The new Media Manager is now gradually being merged into J4, so this can be closed

**Comment by brianteeman** [comment]
Closed as requested
