### ISSUE TITLE
Tags are not displayed if no other details are set to be displayed

### ISSUE THREAD

**Issue by alve89** [joomla/joomla-cms#14754]
Hey guys,

is this a bug or a feature:
In "main article" view ("Home"): If I set all displayable details of an article to "not displayed", the assigned tags aren't shown neither.

**The publishing date is set to be displayed -> tags are shown**
![bildschirmfoto 2017-03-19 um 12 05 13](https://cloud.githubusercontent.com/assets/11487054/24080297/52bff71e-0c9c-11e7-951c-76bd776a444d.png)

**The publishing date is set to be hidden -> tags are not shown**
![bildschirmfoto 2017-03-19 um 12 04 26](https://cloud.githubusercontent.com/assets/11487054/24080289/37dd5982-0c9c-11e7-8d43-61f813d5455d.png)

This issue only appears in "main articles" view, not in the article view itself. I'd like the tags to be shown always...

**Comment by franz-wohlkoenig** [comment]
if you are on 3.6.5, its a known Issue. Tested on 3.7 it works well.

**Comment by alve89** [comment]
Yes, 3.6.5. Sorry, I should have mentioned this. Thank you, I'll wait for the update. :)
