### ISSUE TITLE
[4.0] Improved workflow RFC

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14757]
### Steps to reproduce the issue
In J4 we have all the Save buttons combined together - great

<img width="146" alt="screenshotr11-27-09" src="https://cloud.githubusercontent.com/assets/1296369/24080432/01f5b968-0c97-11e7-8438-92ef38260870.png">

This gives us the opportunity to reconsider what the correct options should be. On a site with an advanced workflow you might need to save all articles as unpublished first until they are approved.

Currently to do that you have to change the state to Unpublish and then Save
Why not add a new Save option - Save as Unpublished - see screenshot

<img width="213" alt="screenshotr11-24-53" src="https://cloud.githubusercontent.com/assets/1296369/24080447/54d30532-0c97-11e7-98ee-073d49d06d2d.png">

If we do this the we have made the first step towards having advanced workflow for creating,, editing and approving articles directly in the UI

**Comment by tonypartridge** [comment]
Agreed @brianteeman this is then the actions system for our users to action exactly how they want to save the article in many states. Great idea.

**Comment by franz-wohlkoenig** [comment]
and width of Dropdown-Field is same as green Save-Button+v.

**Comment by dgt41** [comment]
For starters let's make default the action `save and close` as for save there is also a hotkey ctrl + S

**Comment by brianteeman** [comment]
absolutely yes - although thats ot what this RFC was about ;)

**Comment by rjcf18** [comment]
Regarding this improvement will this only be approached after the UX update? Or there can be a PR implementing this befor that?

**Comment by tonypartridge** [comment]
The UX update might be a little way away yet. What about someone @C-Lodder doing a PR then we can ask users to test on the new system and the J4 research could contain questions and comments on this.

**Comment by C-Lodder** [comment]
There are 2 options:

1. There is now a UX survey out and one of the questions asks which button you use the most in the toolbar. We can wait for that.

2. Just go ahead and make the default `Save & Close`

As for the `Save as Unpublished`, this is a nice idea.

**Comment by C-Lodder** [comment]
Sounds good. In which case we can ditch the dropdown and display a single button, in this case.

**Comment by brianteeman** [comment]
No we still need a dropdown for the other options "save as copy" etc just that my proposal for save as unpublished wouldnt be needed unless the workflow scenario matched

**Comment by C-Lodder** [comment]
Ah does `Save as Copy` set the item to unpublished too?

**Comment by tonypartridge** [comment]
Yes

Thanks
Tony
