### ISSUE TITLE
Install from web not loading correctly

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#14759]
### Steps to reproduce the issue
Activate the 'Install from web' plugin
Install an extension

### Expected result
Success message displays and extensions are shown again

### Actual result
Success message displays but extensions are not shown again

### Additional comments

![loading 01](https://cloud.githubusercontent.com/assets/1115202/24080512/0707c28c-0c99-11e7-9c3f-fc1298874f30.JPG)

**Comment by C-Lodder** [comment]
Joomla 3.6 or 3.7?
Console log errors?
PHP version?

**Comment by Webdongle** [comment]
Staging currently 3.7.0 beta 3 ... also 3.6.5.  Several users have also reported a similar issue https://forum.joomla.org/viewtopic.php?f=708&t=947822

Tested on localhost xampp
PHP Built On 	Windows NT MY-COMPUTER 10.0 build 14393 (Windows 10) i586
Database Version 	5.5.5-10.1.16-MariaDB
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.0.9
Web Server 	Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/7.0.9
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.7.0-beta3 Beta [ Amani ] 21-February-2017 15:03 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14759">issues.joomla.org/tracker/joomla-cms/14759</a>.</sub>

**Comment by tonypartridge** [comment]
This is usually caused when your host has an outdated SSL library it fails to authenticate the Install from web SSL Cert.

Not really an issue but a server configuration issue.

**Comment by Webdongle** [comment]
If it was ssl cert problem then why does it work when navigating away and back again ?

**Comment by tonypartridge** [comment]
Well then that's not an SSL error. But you haven't stated it does that in your issue, hence my point 'Usually'. And I didn't look at the forum post.

Sounds like a possible cache issue and reading on the fly on windows systems maybe but just a guess. I've asked on the forum for more details from the other users to.

**Comment by Webdongle** [comment]
My best guess is cache but this is probably one that will be hard to locate so maybe not worth the bother of chasing to far ?

**Comment by Fedik** [comment]
there already opened issue for it, cannot find

**Comment by Webdongle** [comment]
Thanks.  Will close this tracker
