### ISSUE TITLE
[4.0] Missing Lang.-String in Installtion

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14761]
### Steps to reproduce the issue
![1](https://cloud.githubusercontent.com/assets/8235763/24080551/1f9b1188-0ca2-11e7-8319-9884d69a5fd0.JPG)
### System information
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by wilsonge** [comment]
Fixed with e7ce3504d7e84666781ba44863565a46e813bd58
