### ISSUE TITLE
[4.0] atum toggles

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14766]
I get the reasoning to move away from the j3 style especially the red/green etc But it doesnnt work in all cases and the use of grey makes it look disabled.

See images below for the  menu client - it looks ok when you have selected admin but it looks like its a disabled option when you have selected site

### Admin selected
<img width="385" alt="screenshotr12-14-39" src="https://cloud.githubusercontent.com/assets/1296369/24080783/a409b14a-0c9d-11e7-9463-7435621988c8.png">

### Site selected
<img width="406" alt="screenshotr12-14-27" src="https://cloud.githubusercontent.com/assets/1296369/24080784/a91a0e46-0c9d-11e7-9c56-1484da785501.png">

**Comment by C-Lodder** [comment]
I can make the grey darker so it doesn't look disabled. May add a slight box shadow to give it some depth.

**Comment by tonypartridge** [comment]
I did suggest yesterday that it could be a dropdown @C-Lodder you love drop downs don't you ;-)

**Comment by mbabker** [comment]
You really shouldn't use dropdowns when you only have a choice of two items.  Radio options (or something emulating it with a "fancy" UI like this toggle) are better for that.

**Comment by tonypartridge** [comment]
@mbabker where do you see that though? This is an option so until you switch you don't know what you are switching to and thus it looks like you are turning on / off. But this is actually and this or that? 

It would need to display the value of both options which it doesn't. and if you use red/green that means right/wrong. Not this or that.

**Comment by dgt41** [comment]
A UX good practice is that for options up to 5 you should get toggable behaviour (what @mbabker said)

**Comment by tonypartridge** [comment]
So we need to rebuild how the toggles work so it displays the values which it currectly doesn't do. and instead it's currently more like and on/off.

**Comment by brianteeman** [comment]
unless its an obvious binary such as on/off and show/hide using toggles is not good usability as you cant see what the other options are without toggling. I did point this out back in october or november

**Comment by tonypartridge** [comment]
exactly. In J3.7 we use btn-group and group multiple buttons for a single selection with the text shown. We need this for all these types of radios, that are more than yes/no.

**Comment by brianteeman** [comment]
closing for now see #14838
