### ISSUE TITLE
[4.0] Dashboard boxes

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#14765]
So, when viewing the dashboard boxes we have empty space. See:

![screen shot 2017-03-19 at 13 02 18](https://cloud.githubusercontent.com/assets/1400982/24080724/c023eb62-0c9c-11e7-92a3-31e4736b2cd4.jpg)

Rather than having rows and cols of 6. What about having Cols of 6 left and right. Maybe even a new module position left / right. Then it will fill all space maximising use of the area.

@C-Lodder ?

**Comment by C-Lodder** [comment]
Dashboard is something we're waiting for the UX team to give us survey results for. Well, firstly to send out the survey

**Comment by tonypartridge** [comment]
Can someone apply the UX label?

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/17203

**Comment by ghost** [comment]
closed as having PR #17203<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14765">issues.joomla.org/tracker/joomla-cms/14765</a>.</sub>
