### ISSUE TITLE
invalid security token using cache+form

### ISSUE THREAD

**Issue by ch2856** [joomla/joomla-cms#14762]
### Steps to reproduce the issue
Use a form (simple contact form) in an article and turn on joomla cache (general or general+system plugin)

### Expected result
Form to work with no token issue

### Actual result
invalid security token, form dose not work. 

### System information (as much as possible)
j3.6.5
php 5.4.45

### Additional comments
Not sure if it's developer issue but that issue is a live since j3.6.2.

**Comment by tonypartridge** [comment]
Hello,

How are you loading a simple contact form into the page? you likely are caching it since 'Articles' are static content and the whole content is cached.

I suggest you use a contact form component and not articles for contact forms.

**Comment by franz-wohlkoenig** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened in the future if it is updated.
