### ISSUE TITLE
[4.0] Joomla Update: "Channel" not saved

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14767]
### Steps to reproduce the issue
In `Joomla Update: Options` the `Update Channel` and `Custom Url` is not saved.
### System information
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by wilsonge** [comment]
@dgt41 this is related to the inline scripts issue. There's console errors for this one

**Comment by dgt41** [comment]
@wilsonge but the code is not merged yet: https://github.com/joomla/joomla-cms/pull/14594

**Comment by wilsonge** [comment]
It's from https://github.com/joomla/joomla-cms/pull/14710

**Comment by tonypartridge** [comment]
@wilsonge can you close this please it's been fixed.

**Comment by wilsonge** [comment]
Thanks!
