### ISSUE TITLE
[4.0] Patch Tester Component Settings not saved

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14769]
### Steps to reproduce the issue
Patch Tester component settings (com_config) > GitHub Authentication > Github Token: Insert Token and Save: Not saved and Error:
![bildschirmfoto 2017-03-19 um 13 22 00](https://cloud.githubusercontent.com/assets/8235763/24080838/0f969582-0ca7-11e7-9dda-262a3dc380d9.JPG)
### System information
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by tonypartridge** [comment]
Please use:

https://github.com/joomla-extensions/patchtester/releases

For patch tester issues. It won't have been tested in V4.x yet sinces it's  still going under a lot of work.

Can you close this and open it at the patch tester repo please?

**Comment by franz-wohlkoenig** [comment]
done [#188](https://github.com/joomla-extensions/patchtester/issues/188)

**Comment by mbabker** [comment]
Reopening.  This is com_config (the component config page is what's being referenced), not com_patchtester.

FWIW I don't have that specific JS error, but I am getting this one:

```
Uncaught TypeError: Cannot read property 'task' of null
    at Object.a.submitform (core.min.js?1560820…:1)
    at Object.a.submitbutton (core.min.js?1560820…:1)
    at HTMLButtonElement.onclick (index.php?option=com_config&view=component&component=com_patchtester&path=&return=aHR0cDovL2pjbXMvY…:266)
```

**Comment by tonypartridge** [comment]
Ok will look into it @mbabker

**Comment by tonypartridge** [comment]
Fixed, will send a pull in a minute.
