### ISSUE TITLE
[4.0] Input select padding

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14777]
Not sure if this is a chosen issue or something else but in j4 we have an issue with the label being directly against the select

See this example in post installation messages

### J3
<img width="1098" alt="screenshotr15-35-32" src="https://cloud.githubusercontent.com/assets/1296369/24082231/fc2c376e-0cb9-11e7-8024-682c0f5f287a.png">

### J4
<img width="829" alt="screenshotr15-35-19" src="https://cloud.githubusercontent.com/assets/1296369/24082232/02eef9d8-0cba-11e7-9dfc-1d1eff7ea613.png">

**Comment by yasirunilan** [comment]
Yes it's there in J4. Adding some padding will help. I will do a PR.

**Comment by C-Lodder** [comment]
@yasirunilan - please dont, padding should not be used in this case.

**Comment by yasirunilan** [comment]
@C-Lodder what can be done here then?

**Comment by C-Lodder** [comment]
I'll do the PR

**Comment by yasirunilan** [comment]
okay

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/14780

**Comment by brianteeman** [comment]
Closed as we have a pr
