### ISSUE TITLE
[4.0] Admin: consistency issue in toggles

### ISSUE THREAD

**Issue by yasirunilan** [joomla/joomla-cms#14775]
### Steps to reproduce the issue
Go to Menus and select one, then menus will be listed in a table. there is a column named "Linked modules". For each row it is a select option.From the select option select one option. Then a modal will open. In that Modal under the tab Module there is a toggle for "Show Sub-menu Items". The sides of Yes and No of the toggle are changes so that it doesn't have consistency with the other places.

### Expected result
Normally it's Yes on right side and No on Left side in other places of Yes/No toggles.

![toggle 2](https://cloud.githubusercontent.com/assets/9814784/24081879/f5c0f13a-0ce1-11e7-9878-f4b4bd8c2697.PNG)

### Actual result
Sides are changed and consistency is not there.
![toggle 1](https://cloud.githubusercontent.com/assets/9814784/24081887/15acfdae-0ce2-11e7-9484-662d26ede997.PNG)

### System information (as much as possible)
Joomla! 4.0.0-dev
Windows 10
Chrome 57.0.2987.110 (64-bit)
PHP 5.6

**Comment by C-Lodder** [comment]
With the switchers, there's no left or right position, depending on what is selected.

The label will always be on the right hand side and will simply select your selection, be it `yes` or `no`

**Comment by wilsonge** [comment]
Fixed with #14779
