### ISSUE TITLE
[4.0] Frontend: "Icon" don't open "Edit"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14774]
### Steps to reproduce the issue
Login at Frontend, click on Icon-Symbol > it don't open, so can't "edit" Article.
### System information
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by tonypartridge** [comment]
@franz-wohlkoenig please do not test the frontend. It's BS2 html but we are loading BS4 framework at present. 

Once the backend is done @C-Lodder can do a front end ;-). 

this can be closed.

**Comment by franz-wohlkoenig** [comment]
@mbabker one more for the "do not test now"-list.
