### ISSUE TITLE
[3.7] After the update to 3.7 nightly the TinyMCE is broken.

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#14788]
### Steps to reproduce the issue

- Install 3.6.5
- Apply this as update server `https://update.joomla.org/core/nightlies/next_minor_list.xml`
- install the update
- go to the edit sreen

### Expected result

TinyMCE

### Actual result

![image](https://cloud.githubusercontent.com/assets/2596554/24084218/3e6a8bae-0ce6-11e7-91fe-afa2469d88a9.png)

### System information (as much as possible)

PHP 7.1.1

### Additional comments

None.

**Comment by AlexRed** [comment]
I can confirm the problem

**Comment by zero-24** [comment]
it looks like the editor is toggled by default? If i hit the toggle editor the tinymce comes back 😄

**Comment by AlexRed** [comment]
yes, of if you save the plugin setting then it is ok

**Comment by AlexRed** [comment]
seems ok now for me in 3.7.0 stagin

**Comment by franz-wohlkoenig** [comment]
@zero-24 successfully Test?

**Comment by zero-24** [comment]
looks like this is also fixed. i can't reproduce this anymore. Thanks!
