### ISSUE TITLE
[3.7] UX Error for TinyMCE settings page

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#14789]
### Steps to reproduce the issue

- Install 3.7.0
- go to the tinymce settings

### Expected result

Any settings you made are done for all users. Or at least a better default is used. 

### Actual result

It depends on the `Set`. If you use the default selected `Set 1` all changes are just for public (in 99% of the site public should not have access to add any content).
You need to select `Set 0` for SuperAdmins per default

### System information (as much as possible)

PHP 7.1.1

### Additional comments

None.

**Comment by AlexRed** [comment]
I can confirm the issue. For me the default "open" SET need to be SET 0 for super user<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14789">issues.joomla.org/tracker/joomla-cms/14789</a>.</sub>

**Comment by schnuti** [comment]
It depends on the user groups you have. You'll probably set up SET0 for the superuser and maybe some more groups at the beginning of a project. If you later set up new usergroups in new SETs it's probably better to open the latest SET i.e. SET4. 
If you only have one SET, as up to now with tinyMCE,  you can use SET3 for all usergroups that are using the editor. So it's flexible! and up to you.

**Comment by AlexRed** [comment]
Sorry but no schnuti :(
Do not depends on the user groups I have. The user group and the 3 SET are here by default. For me the default "open" SET need to be SET 0 (super user) and not SET 2 (public)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14789">issues.joomla.org/tracker/joomla-cms/14789</a>.</sub>

**Comment by schnuti** [comment]
@AlexRed  Your opinion. It's flexible. SET 0 ( is not =super user) and SET 2 (is not = public) if you edit it at least once. public is rarely used for the editor.

**Comment by AlexRed** [comment]
Thanks, 
how can I change it in the Joomla code ?

Public is used now in all the custom field editor (contact mail or registration form)

**Comment by schnuti** [comment]
@AlexRed If you want to propose a change you have to find where the tabs are built. I think I saw it in tinymce-builder.js  It shouldn't be very hard to e.g. revert the order of the tabs from x->0 to 0->x but I'm not a Javacript expert.
Personally I prefer it as is. Latest created tab active by default.

You are right about the use cases for public use!

Do you know if there is a documentation of the new possibilities for tinyMCE with Joomla? As said, I'm not a Javascript guru but I've hunted down a couple of useful modifications of tinyMCE. i.e. add  custom styles, formats and buttons that I add in a Joomla plugin. tinyMCEs documentation is no better than Joomlas and a web search gives a lot for WP that is not very helpful.

**Comment by schnuti** [comment]
Explained: I  would add some how-to examples to the documentation.

**Comment by zero-24** [comment]
> I would add some how-to examples to the documentation.

Great let me know when you are done than we can link it from here 😄

**Comment by zero-24** [comment]
Any update with the doc pages so we can close here? @schnuti

**Comment by AlexRed** [comment]
Please do not close but fix it.

**Comment by brianteeman** [comment]
Looks ok to me. I am in the Set 1 tab so the options are for set 1. I am in the Set 2 tab so the options are for Set 2.

**Comment by brianteeman** [comment]
@coolcat-creations this is the ti ymce ux issue we talked about.it would be great if you could take a look

**Comment by ghost** [comment]
@coolcat-creations gently reminder<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14789">issues.joomla.org/tracker/joomla-cms/14789</a>.</sub>

**Comment by coolcat-creations** [comment]
I would change it following:

In the first tab setup the general options which is most likely only the number of **Additional sets**.
Additional, because if you set the Number of Sets below 3 it shows an error and is not possible. So 3 Sets are default anyway. 

We can discuss if the width and height should be here or in each of the sets.

The Set Names should not be Set 0, Set 1, Set 2 but Advanced, Medium and Simple. The additional sets can get a number (if it´s not possible to name them)

![image](https://user-images.githubusercontent.com/828371/30520548-3e293592-9bb0-11e7-9aee-c81e488e8a88.png)

Each Set has an **own tab**. In the main settings of the set you can drag and drop the elements.
For a better understanding we give the Available elements set a white background. We **remove** the preset buttons as that´s a feature that just clutters the overview. If needed, we can add a link "reset to default" which will reset to the Advanced Set.

The editor settings for each set are grouped in tabs for a better overview. I see that currently the settings are quite mixed and the overview is quite bad.

![image](https://user-images.githubusercontent.com/828371/30520591-f5d8d45e-9bb0-11e7-9631-8b9d9150390e.png)

Feedback on this? Thanks!

**Comment by Fedik** [comment]
small note:

> Each Set has an own tab.

This is not possible, unless someone have a time for hard coding,
And I would prefer to have it in the first tab (as it is now), because it is a main part of the plugin configuration

**Comment by coolcat-creations** [comment]
@Fedik - Why is that not possible? it´s possible in the tabs below, so somehow it should be possible. I tried to create a better overview here.

**Comment by Fedik** [comment]
@coolcat-creations programmatically it is another level of tabs inside the toolbar builder, they cannot be moved outward. 
So it will be hard to do without hard re-coding of the toolbar builder.

**And some more notes about suggested overview:**
Imagine an User who open this page first time, beginner.

**Current idea:**
```
[tab Plugin]
  [Available elements] > common for all Sets
  [Set 0] > tabs of sets
  ...
  [Set X]
[/tab end]
[tab Advanced] > contain some rarely used fields
```
User open the plugin configuration and see the builder immediately. 
He/she see "Available elements", and can use it, can try drag some stuff around and see how it work.

**Your:**
```
[tab Plugin] > contain some rarely used fields
[tab Advanced] > contain the builder 1
[tab Medium] > contain the builder 2
[tab Set X] ...
```
User open page, and do not see important thing immediately. But rather he/she confused by what is "Advanced", "Medium" etc. (btw, a lot of beginner's just afraid of word "Advanced" 😉 )

So from my point of view:
I agree, maybe Set 0, Set X, not very clear naming, it was quick solution. And it seems most confusing part of it, and main reason of opened issue.
An idea about renaming first 3 sets to Advanced, Medium and Simple is good.
But moving the tabs around, not very good 😉

**Comment by Fedik** [comment]
and, just got an idea, maybe would be more clear, not Advanced, Medium and Simple, 
but something that explain for what is it, 
something like: "For admin", "For manager", "For public users"

**Comment by schnuti** [comment]
@coolcat-creations 
What does Advanced, Medium and Simple stand for? It is not relevant any more. The settings are related to user groups and not to the editor plugin.

As I described somewhere else the html height and width has no relevance and should be removed.

**Comment by schnuti** [comment]
@Fedik 
You can´t really "pregroup" the user groups . It is up to the administrator to "group the user groups" for the editor. There might even be cases where admins and managers do not use tinyMCE as editor at all but writers, editors, publishers and some new groups each need different settings.
You could store those names as user-set-parameters but then there is a translation problem.   

Edit. Of course you have to "pregroup" at J! version update and installation but that's another thing.

**Comment by Fedik** [comment]
@schnuti yes that also true,
maybe as starting point, and as example how to organise the Sets,
well, was just an idea

**Comment by schnuti** [comment]
@Fedik What's the reason for the 3 obligatory  alternative sets? Only needed as exampel? I agree that it would be hard to find the new possibilities without those examples but why not allow the administrator to set the number to 1 (or somehow remove/delete set 1 and 2) after the update / installation? I think that could satisfy the original issue in this thread. Set 0 can be used as default for user groups not specified in any "active" set. 

I also have another idea for the names. The one obligatory as above = Default, for any other a language string PLG_TINY_SET_TITLE="Alternativ %s"  instead of "Set %s".

Only my quick ideas.

**Comment by brianteeman** [comment]
Because prior to this there were three levels for tinymce.

**Comment by coolcat-creations** [comment]
Ok, let me do a new design proposal without width / height and with the tabs below...

**Comment by schnuti** [comment]
@brianteeman 
If I remember it correctly there was only 1 set of parameters available with a possibility to use 1 out of 3 different "levels" (simple, advanced and extended mode). In addition it was possible to play with accesslevels for some functionlity after choosing Extended mode. If you understood how to use the accesslevels and really used them I do not see how you can transfer those settings to the new user group based settings with an automated update.
The simple and advanced modes had own defined presets.

**Comment by coolcat-creations** [comment]
Due to B/C we have to keep them anyway. @schnuti

**Comment by coolcat-creations** [comment]
In this proposal i named the System Presets Preset 1 to 3, removed width and height settings, the **Available menus and buttons** section is repeated in each tab to have it closer to the Element where it´s dragged to and to have a better and cleaner overview. To prevent having a tab in a tab in a tab i dissolved the settings tabs from the first proposal and the settings would appear below, but should be ordered logically with a headline.
 
![image](https://user-images.githubusercontent.com/828371/30547218-f88a5c84-9c8e-11e7-9001-05b524ae78cf.png)

**Comment by schnuti** [comment]
@coolcat-creations 
I think we are on different trains atm. What is Preset, Preset 2 and Preset 3?
As is, there are 4 buttons to quickly fill new (or old) sets with some values. Use simple preset / Use medium preset / Use advanced preset / clear. I guess those preset values are hardcoded based on the old code. After clicking one of the presets you modify the details of the set to your needs.. 
Are you going to make those **Presets** modifiable?

**Comment by coolcat-creations** [comment]
@schnuti Preset 1 Preset 2 Preset 3 are the default sets from the system that you can customize of course (Now their name is Set 0, Set 1, Set 2) The 4 Buttons to quickly fill new sets are not needed IMHO and just clutter the view. As suggested in the first draft we can add a link "Reset to default" to prefill it with a medium set.

**Comment by ghost** [comment]
@mbabker can Maintainer make a Decision on this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14789">issues.joomla.org/tracker/joomla-cms/14789</a>.</sub>

**Comment by ghost** [comment]
Status is set on "Needs Review".

**Comment by zero-24** [comment]
Nearly one year without any more information I'm going to close here. Thanks.
