### ISSUE TITLE
[4.0] atum toolbar not responsive

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14784]
I assume it is known but documenting it anyway (just in case)
The toolbar is not responsive.

Depending on the number of buttons in the toolbar instead of wrapping (as it did in J3) instead the buttons break out of the container

<img width="849" alt="screenshotr17-23-59 - copy" src="https://cloud.githubusercontent.com/assets/1296369/24083098/e13cba1e-0cc8-11e7-8a6c-fc3122d6e9c3.png">

<img width="637" alt="screenshotr17-22-58 - copy" src="https://cloud.githubusercontent.com/assets/1296369/24083099/e140de14-0cc8-11e7-8b5f-6fd62d90ba50.png">

**Comment by C-Lodder** [comment]
another one we're **waiting** for surveys on :)

**Comment by brianteeman** [comment]
Closing for now see #14838
