### ISSUE TITLE
Debug Language failing when no ini file for the extension

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#14796]
### Steps to reproduce the issue
Install a default multilingual site with associations.
Among the language installed, use a 3.6.5 pack and set it as default Administrator language.
Enable Debug Language in Global Configuration.
Display the Multilingual Associations component. 
Choose article type and a language.

### Expected result
As the 3.6.5 pack does not contain the com_associations.ini, a string like
COM_ASSOCIATIONS_HEADING_ASSOCIATION should be displayed in the header of the list as
??COM_ASSOCIATIONS_HEADING_ASSOCIATION??

### Actual result
The English value is used which is
COM_ASSOCIATIONS_HEADING_ASSOCIATION="Associations"

Example with Italian pack:
![screen shot 2017-03-20 at 09 16 30](https://cloud.githubusercontent.com/assets/869724/24092337/fd9859cc-0d4d-11e7-89ff-6816e9a42eea.png)

**Comment by infograf768** [comment]
EDIT:
We have the same issue for other extensions. If no ini file for that extension in the language, it is replaced by en-GB and the strings are marked as translated.

**Comment by zero-24** [comment]
Is this not a feature we have also backported to 2.5 these days? That we use the en-GB value if there is no language file? Can you try to create the file for the language without any content and try again?

**Comment by infograf768** [comment]
If we have an existing ini file and no content, we will get ??CONSTANT?? and this is OK.
When debug is off, it rightfully uses en-GB.
The problem is that we do not have this information **when debug is on** and the file is absent from the language. It also loads en-GB, therefore we lose a correct debug.

**Comment by infograf768** [comment]
The code is here:
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/language/language.php#L715-L720

**Comment by infograf768** [comment]
Please see https://github.com/joomla/joomla-cms/pull/14801

**Comment by infograf768** [comment]
Closed as we have a patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14796">issues.joomla.org/tracker/joomla-cms/14796</a>.</sub>
