### ISSUE TITLE
[3.7] TinyMCE is not using the old settings

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#14790]
### Steps to reproduce the issue

- Install 3.6.5
- check the default tinymce
- update to 3.7.0
- see the changed default

### Expected result

![image](https://cloud.githubusercontent.com/assets/2596554/24084552/8765013a-0cec-11e7-9314-8b71df4e2b45.png)

### Actual result

![image](https://cloud.githubusercontent.com/assets/2596554/24084502/a04e9536-0ceb-11e7-99fb-bdb4e835838d.png)

**Comment by AlexRed** [comment]
but why you can see the alert message ? 
Do you save the editor plugin after update ?
In my test I can see the message "The TinyMCE Editor Plugin has been updated. At the moment, it uses your legacy configuration. By editing the plugin, you can now assign various layouts to specific user groups." and the settings are ok.
But the alert message in the 3.7.0 update don't explains that editing the plugin you lose all your previous setting.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14790">issues.joomla.org/tracker/joomla-cms/14790</a>.</sub>

**Comment by tonypartridge** [comment]
The only answer to a solution would be to setup the new default profile for TinyMCE to be the same as the legacy options?

**Comment by zero-24** [comment]
I guess so. The legacy options also need too apply for any user until the plugin is saved.

**Comment by Fedik** [comment]
what user role did you use for testing,
you tested as admin, super admin or manager?

**Comment by tonypartridge** [comment]
@Fedik I've replicated the issue. 

default Joomla! 3.6.5 installation install sample data don't touch anything. Upgrade to 3.7 nightly.

Toggle is always off on load. 

And it results to a really basic editor as per @zero-24 screenshots.

Why are we not just outputting a legacy layout by default. I know the notice is to allow users to see the new features etc. But still it's wrong the editor layout shouldn't change, it's a UX nightmare for the users of the CMS.

**Comment by Fedik** [comment]
there already code for display legacy options, `onDisplayLegacy`

> default Joomla! 3.6.5 installation install sample data don't touch anything. Upgrade to 3.7 nightly.

I think this 'don't touch anything' is a reason of this issue. 
It cannot be as test for "old **user** configuration", because you actually test "old **default**".

But strange behavior anyway.

**Comment by tonypartridge** [comment]
I had a look through the option. But why not call the new editor but with legacy configuration of buttons? surely it would be much easier?

**Comment by mbabker** [comment]
Remember something too.  A new installation does not always set all parameters for all of our core extensions into the database, so there are cases where a user is running purely on the coded PHP defaults.

So you have to test two upgrade paths basically here.  One where you are installing 3.6.5 then immediately upgrading to 3.7 without having touched anything on the site.  And one where you are installing 3.6.5, doing various configurations (including the TinyMCE plugin), then upgrading to 3.7.

**Comment by AlexRed** [comment]
seems ok now for me in 3.7.0 stagin

**Comment by franz-wohlkoenig** [comment]
@AlexRed successfully test?

**Comment by AlexRed** [comment]
I try it also in 3.7.0 Beta 4 and I can't confirm the problem now.
And for you ?

**Comment by zero-24** [comment]
Looks like this is fixed using the last beta package. Thanks
