### ISSUE TITLE
[4.0] ReCaptcha on Login

### ISSUE THREAD

**Issue by YoKoGFX** [joomla/joomla-cms#14791]
It would be great if Joomla 4.0 would have an Option to Activate ReCaptcha on the Administrator Loginscreen! This would make the Login more secure and prevent ( make it harder ) that bots acess the Adminpage!

Feature Request:
- ReCaptcha on the Login Screen
- Option to make the ReCaptcha always vissible or just after some failed Logins.

**Comment by tonypartridge** [comment]
+1 for this

**Comment by Simon-Davies** [comment]
Great idea from a security perspective. It would allow me to ditch Google Two Factor Authentication to prevent brute force attacks on the backend

**Comment by brianteeman** [comment]
@Simon-Davies no it wont as captcha can be defeated

**Comment by Simon-Davies** [comment]
I was thinking that may be the case although I thought the new Recaptcha couldn't?

**Comment by brianteeman** [comment]
yet

**Comment by tonypartridge** [comment]
@simon-Davies no you are semi right. Recaptcha has a massively reduced attacks. It's a benefit to include It regardless.

**Comment by Simon-Davies** [comment]
Interesting: https://www.scmagazineuk.com/security-researchers-defeat-recaptcha/article/531691/

**Comment by brianteeman** [comment]
The best way to protect your admin is with htaccess. As this doesn't use php but is at the server level it is far more efficient  on server resources etc

**Comment by tonypartridge** [comment]
Of course it is @brianteeman there is no question on that.

This is a further improvement against random bots that's all.

**Comment by alikon** [comment]
instead of recaptcha you prefer to  use 2FA on admin login

**Comment by cokencorn** [comment]
I'm planning to implement Google's recent invisible recaptcha on the login button, you will still be able to turn it off or set failed login count for it to start checking. What do you think? I believe it's a good alternative to 2FA. (NOT A REPLACEMENT)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14791">issues.joomla.org/tracker/joomla-cms/14791</a>.</sub>

**Comment by Simon-Davies** [comment]
I personally think implementing Google's invisible recaptcha is a great idea especially if it can be toggled on and off for those who do not want to use it.

**Comment by YoKoGFX** [comment]
Yeah, the new invicible recaptcha would be great for that :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14791">issues.joomla.org/tracker/joomla-cms/14791</a>.</sub>

**Comment by ChathuraT** [comment]
Hello, I am going to implement this feature on the Administrator login screen. Found out that google Invisible reCAPTCHA with internal on off functionality would be a great solution. Do any one have more better ideas?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14791">issues.joomla.org/tracker/joomla-cms/14791</a>.</sub>

**Comment by alikon** [comment]
look at #16599, 
i still prefer 2fa for admin login

**Comment by 4digitalworld** [comment]
Please add this feature so that after 3 or 5 or 10 failed attempts ReCaptcha is shown!

[ReCaptcha Invisible](https://www.google.com/recaptcha/intro/comingsoon/invisible.html)

**Comment by RichardEb** [comment]
+1

**Comment by RichardEb** [comment]
I still would prefer captcha instead of 2fa. And I think a huge amount of websites don't use 2fa. If you don't belive me check your telemetry.

Of course you can say: "This people are all idiots and it's their fault." But this won't help anyone. Or you do something! You won't change the peoples behaviour by repeating the same thing. Mine neither.

I want this feature even if it's an optional one.

If you plan to enable this by default you could add an additional Captcha-Plugin that works without google. (This would be a nice thing anyway) Or you can continue contributing an insecure software and blame the user for it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14791">issues.joomla.org/tracker/joomla-cms/14791</a>.</sub>

**Comment by Simon-Davies** [comment]
Invisible ReCAPTCHA should definitely be an option in Joomla 4. There is a free plugin that activates it for WordPress.

I use 2FA but still believe that Invisible ReCAPTCHA should be used by default to prevent bruteforce attacks with tools such as Burp Suite Pro as many people don't enable 2FA.

I'm speaking as a Web Application Penetration Tester for one of the big three and a Security Researcher.

**Comment by skyscr** [comment]
in Joomla 3.xxx  enable # **standart plugin - Google 2fa auntification** 
plug it to ON and open user manager -> tap "admin user" -> open tab 2fa and make 2fa for admin user

**Comment by RichardEb** [comment]
No one want to use 2fa. 2fa is shit

**Comment by RichardEb** [comment]
2fa is shit

**Comment by brianteeman** [comment]
@RichardEb please stop with these posts - they are not helpful

**Comment by tonypartridge** [comment]
I use 2FA where it needs to be secure.

**Comment by RichardEb** [comment]
I said that I dislike 2fa and dont find at an improvment and I dont want to use it. But for you 2fa seems to solv every Problem of the World.

**Comment by Simon-Davies** [comment]
Both 2FA and Invisible reCAPTCHA should be implemented. They could both be optional. Let the user decide.

**Comment by skyscr** [comment]
custom [recaptcha plugin](http://inet-reklama.com/plaginy/plagin-dlya-zashchity-avtorizatsii-v-administrativnuyu-chast-sajta-cherez-kapchu.html) for joomla 2.5 & 3
download 33.99 kB

**Comment by stutteringp0et** [comment]
If you want to stay away from 3rd party services - I did the same thing (invisible captcha) years ago - it's in the JED as HashCash 

I think it would be super cool if it was included in the core.

Before I get accused of advertising - that's one of my free extensions, and I'm offering it to the project.

**Comment by gersteba** [comment]
I am sure, Joomla would not provide users with captcha in contact and registration forms, if there was no sense to do that. The only problem is, that Joomla still is leaving out its login form.
So, please, add captcha to the login form, too!
Thank you very much in advance!

**Comment by RichardEb** [comment]
I still think this is a must have. I really don't know why avoid this feature at all costs. An optional feature wouldn't harm anyone. On the other hand you already added a lot of functions to joomla that I wish you hadn't.

There are a lot of plug ins to archieve a better login protection and they have a lot of users. So why don't add an (optional) feature to joomla?

**Comment by SniperSister** [comment]
> On the other hand you already added a lot of functions to joomla that I wish you hadn't.

Exactly that’s the point. You have to decide per case if I feature is useful enough for the majority of users  to be added to core - what’s a must have for you is pointless to a lot of other people.

**Comment by RichardEb** [comment]
There are a lot of plug ins to add protection to the login. If you say no one wants them why there are a lot of them?

Search for Brute Force protection
https://extensions.joomla.org/instant-search/?searchall=Bruteforce&filter%5Btags%5D%5B%5D=&filter%5Bcore_catid%5D=&filter%5Bincludes%5D=&filter%5Bversions%5D=&filter%5Btype%5D=&filter%5Bhasdemo%5D=&order=&filter%5Bnewupdated%5D=&filter%5Bscore%5D=&filter%5Bfavourites%5D=&q=Bruteforce

The  Brute Force Stop plug in has 40 five star ratings. The ECC+ Plug-in has 168 five star ratings. Rsfirewall 110.

Obviously there are people who want to secure their login. Or are this all idiots who can't use Joomla properly?

**Comment by ghost** [comment]
@RichardEb can you please stay on issue and respect other Volunteers comments?

**Comment by SniperSister** [comment]
> If you say no one wants them

I didn’t say that „no one“ wants them. I tried to point out that the existence of plugins and/or a commenters individual usecase not necessarily means that a majority of users need a feature.

**Comment by BkrBkr** [comment]
I followed your discussion a long time and decided to make a small simple plugin to add a captcha to all login forms. Please feel free to use it, It's free and open source (GPLv3)

https://github.com/BkrBkr/JoomlaAuthCaptcha 

It's an alpha version at the moment

**Comment by brianteeman** [comment]
I am closing this. It has sat here for a year and its not going to move forward.
