### ISSUE TITLE
[4.0] Update on Nightly Builds fail: `Unknown column 'namespace' in 'field list'`

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#14794]
### Steps to reproduce the issue
Download latest Nightly Build & Update on `Joomla Update > Upload & Update`:
![bildschirmfoto 2017-03-20 um 08 57 31](https://cloud.githubusercontent.com/assets/8235763/24091894/46fc83fc-0d4b-11e7-8459-f2b1b0439a6a.JPG)
### System information
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_admin/sql/updates/mysql/4.0.0-2016-19-03.sql The update file is present. Does anyone have any thoughts here?

**Comment by zero-24** [comment]
This file is not executed (as explained many times now) if you are on 4.0.0-whatever you need a file starting with 4.0.1 that it is called. Else we asume this file is already loaded asyou are technical already on 4.0.0. So this file is only triggert if you are on a version lower than 4.0.0 or the file is targeted for 4.0.1 ;)

**Comment by franz-wohlkoenig** [comment]
closing as expected Behaviour (not in my Eyes cause Update is easier than fresh Install).

**Comment by mbabker** [comment]
The version part of that string shouldn't matter since we're using dated diffs.  We need a system that can work independent of version numbering so it ultimately becomes clear that when performing an install or update that there has been a change that needs to be applied.

Reopening.  This is an item that needs attention.  Period.  This and https://github.com/joomla/joomla-cms/issues/13661

**Comment by wilsonge** [comment]
Then can we create a specific item that targets the real issue that the version file is not recognised rather than the this specific namespace issue

**Comment by mbabker** [comment]
All it takes is updating the issue title/description.  I wouldn't change much in the description though because then it changes the context of the follow-up discussion thus far.
