### ISSUE TITLE
Profile plugin fields at registration not validated via ajax

### ISSUE THREAD

**Issue by blanderson22** [joomla/joomla-cms#14806]
### Steps to reproduce the issue
Enable profile plugin. Set fields to required during registration. We used Phone, Company, and Website fields.

### Expected result
Required profile plugin fields will work in the same way during registration as the core fields work, in that they validate dynamically when the field is given focus and then left empty. The required profile plugin fields would also be validated when the 'register' button is clicked and core and profile plugins fields are empty. 

### Actual result
Profile plugin fields are not validated dynamically and they are only validated if all core fields are completed correctly.

### System information (as much as possible)
Joomla 3.6.5

**Comment by franz-wohlkoenig** [comment]
Can't confirm: Set Postal-, Phone- and Website-Field required:
![bildschirmfoto 2017-04-03 um 09 30 39](https://cloud.githubusercontent.com/assets/8235763/24599427/6f5396be-1850-11e7-96fb-46c27a8964ad.JPG)

**Comment by blanderson22** [comment]
Please test by leaving a required core field empty. Also, my description
specifies that this is an issue during registration, not edit.

**Comment by blanderson22** [comment]
Regarding "leaving a required core field empty", example: leave username or
email empty as well as a profile plugin field during registration. You'll
see that only username and email are validated. The profile plugin fields
are only validated in the case that all other non-plugin required fields
are completed. It seems profile plugin field validation is only triggered
if the first validation process doesn't find errors.

**Comment by franz-wohlkoenig** [comment]
@blanderson22 thanks for Hint. Can confirm Issue:
![bildschirmfoto 2017-04-04 um 07 42 00](https://cloud.githubusercontent.com/assets/8235763/24642800/4719e846-190a-11e7-9dc1-a3b4c427d130.JPG)

**Comment by Quy** [comment]
@franz-wohlkoenig Not reproduceable in v3.8.5

**Comment by ghost** [comment]
@blanderson22 can you please check the Issue on 3.8.5? In the Meantime closing this Issue. Thanks for Hint @Quy.
