### ISSUE TITLE
[4.0] Saving article error

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#14808]
### Steps to reproduce the issue
Sorry if this issue reported before, I just saw it while testing something today
1. Install Joomla 4.0 with sample data
2. Try to edit an article, look at Publishing tab, clear the value of Finish Publishing
3. Save the article

### Expected result
Article saved

### Actual result
There is an error **Save failed with the following error: Incorrect datetime value: '' for column 'publish_down' at row 1**

![articles- edit - joomla 4 0 namespace mvc - administration](https://cloud.githubusercontent.com/assets/977664/24105601/f7f3197a-0db7-11e7-9242-d6a168573819.png)

**Comment by tonypartridge** [comment]
Please can you clear this cache it was fixed yesterday again

**Comment by franz-wohlkoenig** [comment]
@joomdonation cannot confirm Issue, Article is saved with cleared `Finish Publishing`.

**Comment by joomdonation** [comment]
Hmm.  Maybe my installation was broken. I will close the issue for now
