### ISSUE TITLE
Language cannot be "default"

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14816]
In some circumstances (currently shown in #14562) it is possible to save a content item with "default" in the language field which makes no sense as we dont have any meaning when it is saved as "default". As far as I can tell it should always be either "*" or a language code

The _offending_ code is https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/content/language.php#L14

**Comment by infograf768** [comment]
we also have 'undefined' which is used when a content language has been deleted and some items were tag ged to it.

so it is jus a matter of changing the lang string. will do pr

**Comment by infograf768** [comment]
Closed as we have a PR https://github.com/joomla/joomla-cms/pull/14834<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14816">issues.joomla.org/tracker/joomla-cms/14816</a>.</sub>

**Comment by brianteeman** [comment]
Reopening as the proposed PR simply changes the word Default to Undefined which also should never happen. The issue is not the WORD but that you can save an article without any language whatsoever

**Comment by infograf768** [comment]
ridiculous<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14816">issues.joomla.org/tracker/joomla-cms/14816</a>.</sub>

**Comment by infograf768** [comment]
@Bakual 
You created this layout in https://github.com/joomla/joomla-cms/pull/12051

I think we just do not need at all that part of the code. It should display "Undefined" when there was a problem saving an item and the language is empty, which is in fact done at the end of the layout code.

My patch changed it to undefined, but we may just need imho to Delete the first conditional.

**Comment by Bakual** [comment]
I just put it into the JLayout because it was used in com_menus and com_modules before my PR:
* administrator/components/com_menus/views/items/tmpl/default.php
* administrator/components/com_modules/views/modules/tmpl/default.php
* administrator/components/com_modules/views/modules/tmpl/modal.php
* administrator/templates/hathor/html/com_menus/items/default.php
* administrator/templates/hathor/html/com_modules/modules/default.php

I just assumed there was a reason for it without checking further.
"Undefined" works for me for sure, just remove the first conditional and it should do that.

**Comment by infograf768** [comment]
OK, will make a specific PR.

**Comment by infograf768** [comment]
Closed again as we have a specific patch. Thanks @Bakual for confirming.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14816">issues.joomla.org/tracker/joomla-cms/14816</a>.</sub>
