### ISSUE TITLE
JMail addAttachment does not pass disposition to parent class PHPMailer

### ISSUE THREAD

**Issue by brandtOSS** [joomla/joomla-cms#14818]
### Steps to reproduce the issue
Use JMail's `addAttachment` method's parameter $disposition
For example:

> $mail2send = JFactory::getMailer();
> $mail->addAttachment($filePath, $fileName, 'base64', 'image/jpeg'. 'inline');

The last parameter is `$disposition`  (here: _'inline'_).
This parameter never has an effect because JMail does not pass this parameter to the parent class PHPMailer's `addAttachment` method.

### Expected result
The disposition should have an effect.

### Actual result
The disposition never has an effect.

### System information (as much as possible)
Joomla 3.6.5

### Additional comments
None

**Comment by brianteeman** [comment]
If you are submitting a pull request you don't need to create an issue at the same time.
