### ISSUE TITLE
Minimum php version check

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14820]
We have code in 3.7 still that runs postinstall and checks that you are on a version of php > 5.3.10 and if not gives the following message
> Your PHP Version Will Be Unsupported in Joomla! 3.3

> Beginning with Joomla! 3.3, the version of PHP this site is using will no longer be supported. Joomla! 3.3 will require at least <a href="_QQ_"https://community.joomla.org/blogs/leadership/1798-raising-the-bar-on-security.html"_QQ_">PHP version 5.3.10 in order to provide enhanced security features to its users</a>."

pretty sure this is now redundant and both the strings and the code \administrator\components\com_admin\postinstall\phpversion.php can be removed now as it is no longer possible to ever get that scenario

If someone can confirm that I can remove the code and deprecate the strings in 3.7 and remove the strings in 4

**Comment by zero-24** [comment]
:+1: @brianteeman

**Comment by brianteeman** [comment]
Thanks @zero-24 created a PR #14821
