### ISSUE TITLE
Contact list parameter in frontend with a comma

### ISSUE THREAD

**Issue by stellainformatica** [joomla/joomla-cms#14825]
### Steps to reproduce the issue
Create some contacts and fill in the parameter "City or Suburb", without filling the parameters State or Province and Country
Create a menu item type Contacts » List Contacts in a Category

### Expected result
The City or Suburb in the list is displayed without a comma following 

### Actual result
The City or Suburb in the list is displayed with a comma following 
![screen shot 2017-03-21 at 12 11 38](https://issues.joomla.org/uploads/1/c595b7118684fe13648f1c1ad64331ac.png)

### System information (as much as possible)
Joomla 3.7.0beta3

**Comment by AlexRed** [comment]
I can confirm the issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14825">issues.joomla.org/tracker/joomla-cms/14825</a>.</sub>

**Comment by brianteeman** [comment]
Please try #14827

**Comment by brianteeman** [comment]
Closed as we have a PR
