### ISSUE TITLE
Logout button of com_login not working properly in frontend

### ISSUE THREAD

**Issue by stellainformatica** [joomla/joomla-cms#14826]
### Steps to reproduce the issue
In localhost, create a joomla site in a subfolder.
Create a menu item type Users » Login Form
Login in frontend, click on this menu item and click on Log out button

### Expected result
The user is correctly logged out

### Actual result
The user is not correctly logged out, clicking on the button he is redirected to the localhost.

### System information (as much as possible)
Joomla 3.7.0beta3

**Comment by AlexRed** [comment]
I can confirm the issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14826">issues.joomla.org/tracker/joomla-cms/14826</a>.</sub>

**Comment by brianteeman** [comment]
Confirmed -

**Comment by joomdonation** [comment]
Users is still logged out, just being redirected to wrong page. Will redirect to homepage of the site is expected behavior?

**Comment by AlexRed** [comment]
yes

**Comment by brianteeman** [comment]
You are not being redirected to the home page but to the homepage of the
domain which is wrong and unexpected behaviour as that is a different web
site

**Comment by joomdonation** [comment]
@brianteeman I meant the homepage of the site, not the domain. Anyway, PR created https://github.com/joomla/joomla-cms/pull/14836

**Comment by rdeutz** [comment]
closed as we have a PR #14836
