### ISSUE TITLE
xrdp 0.9.1 calls the PAM function auth_start_session() in an incorrect location, leading to PAM session modules not being properly initialized

### ISSUE THREAD

**Issue by road2one** [joomla/joomla-cms#14828]
### Steps to reproduce the issue
https://github.com/neutrinolabs/xrdp/issues/350

joomla! -- joomla!
 	

### Expected result
xrdp 0.9.1 calls the PAM function auth_start_session() in an incorrect location, leading to PAM session modules not being properly initialized, with a potential consequence of incorrect configurations or elevation of privileges, aka a pam_limits.so bypass.	2017-03-17

**Comment by brianteeman** [comment]
Closed - please follow the instructions Report security issues to the Joomla! Security Strike Team (JSST) at security@joomla.org or use the [JSST contact form](https://developer.joomla.org/contact-security-team.html). **_Please do not use the public tracker for security issues._**
