### ISSUE TITLE
TinyMCE "HTML Width" parameter not work

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-cms#14835]
### Steps to reproduce the issue
In plugin TinyMCE setting page the advanced parameter "HTML Width" not work

![http://alexred.com/joomla/html-width.png](http://alexred.com/joomla/html-width.png "http://alexred.com/joomla/html-width.png")

### Actual result
The editor HTML Width remains 100%

### System information (as much as possible)
3.7.0 nightly

**Comment by C-Lodder** [comment]
The width and the height parameter seriously need to be removed. Editors should have a width of about 80 characters for optimum usage as mentioned by Ciaran a while back

The editor has a fullscreen mode, so these 2 parameters are pointless

**Comment by AlexRed** [comment]
the height parameter for me is useful,
ok to remove width

**Comment by franz-wohlkoenig** [comment]
Width is helpfull for hyphination Words.

**Comment by joomdonation** [comment]
There was a PR supposed to fix this https://github.com/joomla/joomla-cms/pull/14033 . Unfortunately, there was one point not agreed between the owner and some of us and it is still remain open

**Comment by N6REJ** [comment]
sizing also doesn't work in form fields.

**Comment by Fedik** [comment]
the main issue here that the size can come from 100 places, and hard to decide what should be used in final

**Comment by N6REJ** [comment]
admin should overwrite core tinymce

**Comment by Quy** [comment]
Please test PR #26755<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14835">issues.joomla.org/tracker/joomla-cms/14835</a>.</sub>
