### ISSUE TITLE
[4.0] UI - No space between table border and text

### ISSUE THREAD

**Issue by yasirunilan** [joomla/joomla-cms#14839]
### Steps to reproduce the issue
Go to the menu Extensions -> Manage -> Discover

### Expected result
The text "Discover extensions that have not gone through the normal installation process." is too much left aligned. Better to have some space between the table boarder and the text.
![101](https://cloud.githubusercontent.com/assets/9814784/24164825/c83dc5b2-0e94-11e7-833f-53918cfe4832.PNG)

### Actual result
No space between text and table boarder.
![102](https://cloud.githubusercontent.com/assets/9814784/24164844/dcc6880c-0e94-11e7-818a-0d15c33ed9bd.PNG)

### System information (as much as possible)
Joomla! 4.0.0-dev
Windows 10
Chrome 57.0.2987.110 (64-bit)
PHP 5.6

**Comment by yasirunilan** [comment]
I'll make a PR for this

**Comment by franz-wohlkoenig** [comment]
please have a Look #14838

**Comment by C-Lodder** [comment]
@franz-wohlkoenig this issue is perfectly fine.

@yasirunilan you can make a PR if you want

**Comment by yasirunilan** [comment]
@C-Lodder okay I'll do the PR.

**Comment by zero-24** [comment]
Closing as we have a PR https://github.com/joomla/joomla-cms/issues/14842

**Comment by zero-24** [comment]
Thanks

**Comment by yasirunilan** [comment]
Con somebody review and give a feedback?
