### ISSUE TITLE
[4.0] [UI] Joomla 4.x Roadmap

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#14838]
### Summary

With Joomla 4 still is relatively early stages, we're still making a lot of UI (User Interface) improvements or potentially re-writing some pages.

With this in mind, we please ask that you don't report any UI or UX related bugs for the following pages, extensions, or blocks:

- **Installation** (the UI is being completely re-written)
- **Dashboard** (waiting for UX team's survey feedback)
- **Toolbar** (waiting for UX team's survey feedback)
- **Articles List** (waiting for UX team's survey feedback)
- **Sidebar menu** (waiting for UX team's survey feedback)

We have been promised results for 3 surveys from the UX team by **April 1st** so issues can wait till then

**Comment by brianteeman** [comment]
lol @mbabker I was just making the same edit

**Comment by dgt41** [comment]
So no UX input for the **installation**?

**Comment by C-Lodder** [comment]
it's not on the "to-do" list at the moment. We'll get UX input once you and Ciaran have finished

**Comment by brianteeman** [comment]
Can this be publihsed on the developer.joomla.org web site. It will be easier to find and is also the obvious place to look for it

**Comment by mbabker** [comment]
If I remember (or someone else with access beats me to it), we can get a section added in the next day or two.  Otherwise this is the type of thing that https://github.com/joomla/joomla-websites/issues/897 is aiming to include.

**Comment by brianteeman** [comment]
great news - a single canonical location is perfect - crazy that we had more than one and even crazier that they were not compatible with each other

**Comment by franz-wohlkoenig** [comment]
as [Comment](https://github.com/joomla/joomla-websites/issues/897#issuecomment-290738180) says, can this Issue be closed?
