### ISSUE TITLE
New router for com_newsfeeds and com_contact need new router enabled also in com_content

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-cms#14833]
### Steps to reproduce the issue
if I enabled new router (remove ID) in com_newsfeeds or in com_contact and it is disabled (default) in com_content the ID in the URL in com_newsfeeds and com_contact are still present. It is ok in com_newsfeeds and com_contact if I also enable new router (remove ID) in com_content

### Expected result
if I enabled new router (remove ID) in com_newsfeeds and com_contact the ID in the URL in com_newsfeeds and com_contact are not present also if new router is disabled in com_content

### System information (as much as possible)
3.7.0 nightly

**Comment by brianteeman** [comment]
I have tested and confirmed this with com_contact 
Set Experimental router and remove ID on for com-contact and leave Stable router on for com_content


**Result**
`http://127.0.0.1/joomla-cms-staging/joomla-cms-staging/index.php/en/contact-us/4-buyer
`
Set Experimental router and remove ID on for com-contact and for com_content

**Result**
`http://127.0.0.1/joomla-cms-staging/joomla-cms-staging/index.php/en/contact-us/buyer`

You should get the second result in both cases. the settings for com-content router should have zero effect on com-contact router

Setting to Release Blocker

**Comment by wilsonge** [comment]
I'm just getting off the plane but if anyone wants to solve it in all the core components 

https://github.com/joomla/joomla-cms/blob/staging/components/com_users/router.php#L39

**Comment by brianteeman** [comment]
Closed as we have a PR #14841

**Comment by brianteeman** [comment]
Hope I found them all
