### ISSUE TITLE
[Joomla!3.7.beta3] value of the color field in rgb/rgba format can't be saved

### ISSUE THREAD

**Issue by wronax** [joomla/joomla-cms#14837]
### Steps to reproduce the issue
1. Go to /templates/protostar/templateDetails.xml
2. Add rgba format attribute to the templateColor field (line 55)
<field name="templateColor" class="" type="color" default="#08C" **format="rgba"**
3. Go to Protostar default template style options
4. Changed Template Colour and Save options

### Expected result
Template Colour should be saved in rgba format.

### Actual result
Template Colour is cleared (empty value).

### System information (as much as possible)
Joomla!3.7.beta3 release

### Additional comments
The color field was modified for J!3.7.x and now color validation seems to be applied automatically to this field type. However the color rule test function return true only for colors in HEX format while color field types allows to set colors in HEX, RGB and RGBA formats.

**Comment by wronax** [comment]
This bug still persists in stable Joomla!3.7 version.

**Comment by marcorensch** [comment]
i can confimr i have the same issue with my module. Any solution or workaround would be nice.

**Comment by wronax** [comment]
I've fixed it by creating my own color field in our extension simply by copying and renaming the color field from Joomla!3.6.x, because I think it won't be repaired soon.

**Comment by marcorensch** [comment]
yep thats an easy solution...

**Comment by N6REJ** [comment]
What happen to the new color picker?

**Comment by marcorensch** [comment]
It does not take rgba values... u have to create a temp workaround as wronax mentioned

**Comment by Quy** [comment]
Relate PR #15754 ???

**Comment by Quy** [comment]
@franz-wohlkoenig Closed as having pr #15754.
