### ISSUE TITLE
Joomla Color Picker unable to use transparent

### ISSUE THREAD

**Issue by jayblaq** [joomla/joomla-cms#14843]
### Steps to reproduce the issue

Test with any color picker in Joomla such as the Protostar Template and try to add the word transparent.   Transparent is a CSS color value for background-color and should work.  In other frameworks etc custom color pickers are used to get over this issue.

### Expected result

Color value saved as transparent

### Actual result

Defaults to last saved value

### System information (as much as possible)

Joomla 3x 3.7 etc

### Additional comments

Adding this would be part of enabling 3rd party developers to conform to Joomla's API and features.

**Comment by pepperstreet** [comment]
Good point. Just had a quick look in my local installation. The visual appearance of the form field implies to support "transparent", because it shows the typical "checkerboard". My first thought was, it might be some build-in functionality. 
What about using the default value parameter instead? The output is just the field value. So, you might work with that value "transparent".

PS: On the other hand, it results in a "never-empty" field, right? Maybe a related and general question how to deal with the basic field logic for "empty" and "filled" fields. Wouldn't it make sense to display labels of empty fields?

**Comment by brianteeman** [comment]
Pretty sure transparency was added to the color picker.some time ago but
not at computer to double check.

**Comment by pepperstreet** [comment]
Right. There are many other related issues and the following PR 
#14427 
But the new "format" option seem to have issues as well: 
#14837

**Comment by N6REJ** [comment]
I can confirm this issue.  Values returned are either color value or "" .
I'm sure this was fixed in a previous PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14843">issues.joomla.org/tracker/joomla-cms/14843</a>.</sub>

**Comment by butlerps** [comment]
Just come across this issue however my results are slightly different.
`<field name="navbar_bg" type="color" default="#f8f8f8" keywords="transparent,initial,inherit" label="TPL_NAVBAR_BACKGROUND_COLOR_LABEL" description="TPL_NAVBAR_BACKGROUND_COLOR_DESC" />`
The above allows me to enter 'transparent' and when I click save the value is stored and can be used in my module view.  However the word 'transparent' is not loaded back into the template xml file so when I click 'save' again the default value of #f8f8f8 is stored.

**Comment by N6REJ** [comment]
idk if this is relevant but I discovered an issue today with it changing colors automatically...
I have two fields in my template...

<field name="hoverbackgroundColor"
                               class="small-input"
                               label="TPL_SERENITY_FONTS_HOVER_BACKGROUND_COLOR_LABEL"
                               description="TPL_SERENITY_FONTS_HOVER_BACKGROUND_COLOR_DESC"
                               type="color"
                               default=''
                        />
                        <field name="hoverColor"
                               class="small-input"
                               label="TPL_SERENITY_FONTS_HOVER_COLOR_LABEL"
                               description="TPL_SERENITY_FONTS_HOVER_COLOR_DESC"
                               type="color"
                               default=''
                        />
you've got 2 fields
if you put color in the 2nd and save it returns empty
if you put color in the 1st it saves
if you put color in the 1st and 2nd it changes 2nd to match first!!!

craziest thing I've ever seen.

**Comment by butlerps** [comment]
Okay, so I'm extending my module so as the user can select one or more background colours to utilise the CSS linear-gradient style.
My fix above no longer works within a repeatable field, in fact as soon as you type 'transparent into the color field, the word immediately gets replaced with #14427 
`				<field
					name="bg_color2"
					label="Background Color 2"
					description="Background colour, other options include transparent, initial &amp; inherit"
					type="repeatable"
					icon="list"
				>
					<fieldset hidden="true" name="bg_color2_modal" repeat="true">
						<field name="bg_color2a"
							type="color"
							keywords="transparent,initial,inherit"
							default=""
							label="Background Color"
							description=""
						/>
					</fieldset>
				</field>
`
Why would this be different from my first example?

**Comment by N6REJ** [comment]
due to the insane age of this issue its now dependant on #15754 & #14427 since both of those will most likely completely change this issue.

**Comment by ghost** [comment]
@N6REJ what does this mean for this Issue?

**Comment by alikon** [comment]
hold on please
it's just another very old one but it still deserve some more investigation
...unfortunately

**Comment by alikon** [comment]
time to close it
