### ISSUE TITLE
[Isis] Chzn 'trashed' color

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14855]
unfortunately [#14850] - [Isis] Chzn 'unpublished' color was merged before i could comment

1. we also need trashed to have the red colour
2. not sure why this status field has been changed to use chosen - it wasnt before and its hardly needed when you only have 4 or 5 options

**Comment by ciar4n** [comment]
PR created... #14856

I suspect the reason for using chosen here was to allow consistent styling with other fields. Basic select fields are very limited to style. It is not possible to style in the same manner as chosen fields. There is some examples of selects been used. See.. #13904

**Comment by brianteeman** [comment]
closing as there is a pr
