### ISSUE TITLE
Missing help page - associations

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14853]
@MATsxm as discussed can you create a stub help page for the new Multilingual Associations component and then I can make the code changes required to use it and to close off an @todo from the code

`administrator/index.php?option=com_associations`

**Comment by Sandra97** [comment]
I created a week ago the 3 needed help screens for this component and prepared yesterday the PR. MAT will post it today.
https://docs.joomla.org/Help36:Components_Associations
https://docs.joomla.org/Help36:Components_Associations_Edit
https://docs.joomla.org/Help36:Components_Associations_Manager_Options

**Comment by brianteeman** [comment]
That's great - thanks - i will leave this open until @MATsxm posts

**Comment by brianteeman** [comment]
Closed as we have a PR
