### ISSUE TITLE
Can Joomla distributed as Phar package?

### ISSUE THREAD

**Issue by sajalaspl** [joomla/joomla-cms#14857]
I was just wondering if Joomla can be distributed as Phar package, any challanges?

**Comment by brianteeman** [comment]
Simple answer is no it cant - its not appropriate to be used as a phar package

**Comment by Bakual** [comment]
To my knowledge, it makes no sense.
See https://github.com/joomla/joomla-cms/pull/4091#issuecomment-51773341 which should still be valid.

**Comment by sajalaspl** [comment]
Thanks @Bakual and @brianteeman.
