### ISSUE TITLE
[4.0] Articles : Edit page "Category"select option disappeares

### ISSUE THREAD

**Issue by yasirunilan** [joomla/joomla-cms#14867]
### Steps to reproduce the issue
In the Main side menu go to Content -> Articles
A new page will be loaded. In that page there is a panel on the right side of the page. In that panel there is an a select option labeled as Category. Click it and now click outside. 

### Expected result
Select option should not be disappeared

### Actual result
Select option disappears 

### System information (as much as possible)
Joomla! 4.0.0-dev
Windows 10
Chrome 57.0.2987.110 (64-bit)
PHP 5.6

**Comment by brianteeman** [comment]
Updated title to make it clear it is for j4

**Comment by dgt41** [comment]
Known problem. Chosen has been removed without implementing (yet) the replacement...
There is a PR in the backend-template repo, but not yet production ready.
This (https://github.com/jshjohnson/Choices/issues/39) needs to be fixed upstream before we include that script
