### ISSUE TITLE
Check-in button tool-tip displays time using system time.

### ISSUE THREAD

**Issue by marcochirienti** [joomla/joomla-cms#14860]
### Steps to reproduce the issue

In com_content, when an item is checked out, a check-in button is added near the article title.
The button has a tool-tip with information about the checked out user ad checked out date and time.
The tool-tip displays the date using system time and this is misleading for a user using a different time zone.

### Expected result

The tool-tip should display the date using local user time.

### Actual result

The tool-tip displays the date using system time.

### System information (as much as possible)

- Joomla 3.7 

### Additional comments

This behaviour is shared by many components (maybe all?!).

**Comment by brianteeman** [comment]
If this change was to be done then we need to change every date everywhere to use local time.

I think k it is wrong to make this change. It creates more confusion not less.

**Comment by marcochirienti** [comment]
Many dates are already displayed using user time zone.
The point is that the tool-tip should give the user an information about the time the item has been checked out and actually this information is not clear at all.
I do look at checked out time. before I press the check-in button, if I'm operating in a context where there are different users accessing the back-end of a website. But I have to remember that my time zone is not the same of the system and that the time displayed is not correct.

**Comment by brianteeman** [comment]
Closed as related to pr #17823

**Comment by infograf768** [comment]
BTW, I tested that. The date/time displays corresponds to the user time zone i.e. it is saved as UTC in the db and customized in the display. Therefore if multiple users have access to back-end and use different time zones, they will see the checked out date/time corresponding to their time zone, NOT the system time of their OS at all.
Users may have set their time zone to the same as their OS (usually it's a normal setting), thus the confusion.
