### ISSUE TITLE
Tabstate block page scroll if tab in modal

### ISSUE THREAD

**Issue by Globulopolis** [joomla/joomla-cms#14869]
### Steps to reproduce the issue
Add `JHtml::_('behavior.tabstate');`
Add tabs on page
```html
<div>
	<?php echo JHtml::_('bootstrap.startTabSet', 'upload_tab', array('active' => 'local')); ?>
	<?php echo JHtml::_('bootstrap.addTab', 'upload_tab', 'local', JText::_('LOCAL')); ?>
		... Content
	<?php echo JHtml::_('bootstrap.endTab'); ?>
	<?php echo JHtml::_('bootstrap.addTab', 'upload_tab', 'remote', JText::_('REMOTE')); ?>
		... Content
	<?php echo JHtml::_('bootstrap.endTab'); ?>
	<?php echo JHtml::_('bootstrap.endTabSet'); ?>
</div>
```

When add modal with tabs to the same page
```php
echo JHtml::_(
	'bootstrap.renderModal',
	'selectPhotoModal',
	array(
		'title'  => JText::_('NOTICE'),
		'modalHeight' => '50%'
	),
	JLayoutHelper::render('layouts.edit.select_image')
);
```
Layout file contain tabs too.

### Expected result
Previously selected active tab after page refresh/reload.

### Actual result
Activated tab after page refresh/reload but without window scroll. And when I try to scroll page with mouse it's not working. Only by buttons or PageUp/PageDown.

### System information (as much as possible)
Joomla 3.6.4
Firefox 52
Chrome 54

### Additional comments
Looks like the tabstate trying to activate hidden tab in modal and call something in Bootstrap modal which hide/block page scroll.

**Comment by alikon** [comment]
after more than 2 years without any follow-up
i'm going to close it.
it can be always reopened if needed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14869">issues.joomla.org/tracker/joomla-cms/14869</a>.</sub>
