### ISSUE TITLE
Unable to use USER EXTRA FIELDS in content

### ISSUE THREAD

**Issue by jayblaq** [joomla/joomla-cms#14870]
### Steps to reproduce the issue

Create a new extra field under the USERS area.  As an example a Media Field to allow users to add a profile image.  Next copy the field ID and try to place it in content such as {field 1}

### Expected result

The field should show in the content

### Actual result

It only shows the tag

### System information (as much as possible)

Joomla 3.7

### Additional comments

I understand this might not be the way the extra fields were built, but since they all have their own assigned ID across the components it will be highly useful.

**Comment by brianteeman** [comment]
Sorry I'm a little confused about this issue from your description. Are you saying you have a field for com_users that you want to display in com_content? If thats the case how are you expecting the two components to be linked? Maybe I completely misunderstand what you are talking about

**Comment by jayblaq** [comment]
Well it seems that all the fields get their own id such as if I add 3 fields to com_users they are fields 1-3 and then if I add 3 to content they are 4-6.  This lead me to believe they were all stored together or something.   I understand the fields might be dependent on each com, but if there was a way to use them together it will be powerful for certain scenarios.  Perhaps there could be some logic such as if I want USER fields it would be {com_users field 2} or something.   Just some ideas.

**Comment by brianteeman** [comment]
The field may have an id but that is the field not the stored value of the field.

Its not about knowing if it is a user or a content field. its about knowing which value to display

Do you want to display the value of fieldid2 for userbrian or userjay

When you say fieldid3 inside an item then it obviously looks for the value of that field for that specific item. Doesnt matter what type of item it is.

In your example you seem to be trying to grab the value of a completely unrelated field - or at least without somehow defining the relationship between the content item you are editing and and the user details that you want to display

**Comment by jayblaq** [comment]
Yes, I understand that - it would be a nice feature update at some point to be able to grab other fields from other coms too!

Before we close this - I showcased Extra Fields to our Tampa User Group last night and everyone was quite excited.  One ? that came up is will Extra Fields be added to Contacts?   Many people have to use other extensions for the contact page to add more fields.

**Comment by brianteeman** [comment]
As I said you would need to create a way of making the connection between the two different components. I havent checked but you could probably do that using the SQL field type


As for your request to add fields to the contacts component. That would be almost impossible to add at this time.







It's already there ;)

**Comment by jayblaq** [comment]
Thank you!

Jason Nickerson

Monev Software LLC / JoomlaXTC.com
Open Source Florida / JoomlaDay Florida
TampaBay Joomla User Group
JED QC Tester
Joomla Site Showcase Team
