### ISSUE TITLE
[RFC] nofollow links #14881

### ISSUE THREAD

**Issue by chriswagner0815** [joomla/joomla-cms#14888]
Dear colleagues - 
discussed in the ticket: https://github.com/joomla/joomla-cms/pull/14881 there is a question about the use of rel="nofollow" links in our code. 

I am an SEO, no coder, so I ask for your help and quotes in understanding the code. Generally speaking, it has been raised that a search engine will not "follow" a link that is marked with "nofollow". This is wrong. Search engines will follow. However, links marked as "nofollow" will not pass "pagerank". In "laymen's" terms this means: "Yeah, I will follow the link and see what is there, but I will not pass trust". Generally, Google suggests doing this, if you have page linking to another that is an ad or advertorial (violation of guidelines). 

I would like to understand how we treat that on a live-site and for which cases we are doing that and why.

Please advise
Chris :)

Discussion can also be found here: https://github.com/joomla/joomla-cms/pull/14881

**Comment by brianteeman** [comment]
_To anyone reading this there is absolutely no need to read the other issue linked to as it is absolutely nothing to do with nofollow on links at all. (I am not saying there is no issue about nofollow links just that the referenced issue has nothing to do with it)_

**Comment by brianteeman** [comment]
For reference there are exactly TWO places where nofollow is hardcoded to external links in the core. Thats all.

**Comment by chriswagner0815** [comment]
To anyone reading Brian's comment, I suggest to read the code!

**Comment by brianteeman** [comment]
Chris if you did read the code then you would see you are making a mountain out of a very very tiny molehill as already stated there are TWO places with nofollow. Surely there are better things you can do with your time

**Comment by chriswagner0815** [comment]
Brian,
I asked you to help me understand. You chose **not** to. Here we are. 
Now I have to ask other colleagues. That happens, when our Chris has questions and doesnt get them answered. :-) 

Back to topic:
1. Where does that happen on a live site? 
2. Can I see an example so I can understand in "laymen's" terms?

Chris :)
Brian: I hope that hence you will not answer, you leave the stage to colleagues who will. Feel hugged! :)

**Comment by C-Lodder** [comment]
Taken from [Google](https://support.google.com/webmasters/answer/96569?hl=en):

> "Nofollow" provides a way for webmasters to tell search engines "Don't follow links on this page" or "Don't follow this specific link."

**Comment by brianteeman** [comment]
The two places are
https://docs.joomla.org/Help36:Content_Article_Manager_Edit#Images_and_Links
and
The new URL field type

**Comment by chriswagner0815** [comment]
Charlie: https://support.google.com/webmasters/answer/96569?hl=en provide where you are quoting from. What I said is there.

**Comment by chriswagner0815** [comment]
Charlie:
"In general, we don't follow them. This means that Google does not transfer PageRank or anchor text across these links. Essentially, using nofollow causes us to drop the target links from our overall graph of the web. However, the target pages may still appear in our index if other sites link to them without using nofollow, or if the URLs are submitted to Google in a Sitemap. Also, it's important to note that other search engines may handle nofollow in slightly different ways."

**Comment by chriswagner0815** [comment]
Brian: 
So I am looking at an article that has an image that links to something. Why would we add the nofollow attribute to that?

Where can I find info about the new URL field type?
Chris

**Comment by brianteeman** [comment]
Thats not what the link I provided says and sorry this is not the place for Joomla 101. I tried to give you the answer requested. I clearly failed to do that so I will not bother any more. There are for more important things to do

**Comment by chriswagner0815** [comment]
Brian,
I am happy that you attend to more important things. I would have suggested an RFC about "Brian and Chris and Chris and Brian reading their code" but since you chicken out now ...

**Comment by bertmert** [comment]
Joomla 3.7, Protostar

1) 
- Go to
`administrator/index.php?option=com_fields&context=com_content.article`
and create a new custom field of type `URL`. Title "URL for articles"
- Edit an article and fill field "URL for articles". Enter an external URL.
- Go to FE and inspect the HTML-output:
`<a href="https://github.com" rel="nofollow" target="_blank">https://github.com</a>`
==> hard-coded `_blank` and `nofollow`.
BUT: You can override it if you want:
https://github.com/joomla/joomla-cms/blob/3.7.0-beta2/plugins/fields/url/tmpl/url.php#L20-L23

2) 
- In FE inspect Email and Print icons. Both use hard coded `rel="nofollow"` which minimizes stupid URLs in (some) search engines. Because you say you're using Joomla since version 1.5 you know that this is a good thing. Maybe you and you're team will find a better solution because not only Google rules and there are search engines that still ignore this nofollow in Print and Email.

3) 
- eDIT AN article. Enter a `Link A`. Go to FE and inspect the anchor concerning `rel="nofollow"` depending on option `URL target window`. 2 cases with hard coded nofollow.

4)
- Discuss with your team if there are any SEO preferences concerning order of `rel` attribute values like `nofollow`, `noorder`, `nowhocares` ... if several of them are used 

That's all. 

Only 4) is slightly relevant for Brian's PR (again: that doesn't add or remove a nofollow). 

1) to 3): You have to explain in a new issue each with testing instructions why this or that is bad SEO practice and should be changed.

(Normally these simple investigations should be done by the SEO team.)

**Comment by brianteeman** [comment]
which are either 
1. to our own site but the type of page that you would not want to be indexed (print and email)
2. to external sites where because of the type of link (advert) it should be nofollow
3. user created links which because they are untrusted links should be nofollow

**Comment by chriswagner0815** [comment]
Hi Bertmert,
thank you for taking the time to help me out in understanding where to go and where to look. Thank you Brian for your links as well, unfortunately this was too short for me to understand where this was happening.

Essentially, where we don't need to fear that links are "advertorial", I suggest we do not need to add a nofollow attribute. I also would like us to keep in mind that users could use the external link url to link to their own page (if there is no check from the system in place) thus killing page rank flow on the site internally. 

Places like banners or mail addresses or the pint icon are logic places where adding this is reasonable, the image ABC fields and additional field sets, I find excessive.

Towards the order of attributes I have nothing to add and I would hope that the order will not matter. 

Additional information:
(old but relevant information)
https://moz.com/blog/google-maybe-changes-how-the-pagerank-algorithm-handles-nofollow
https://seo-hacker.com/pagerank-sculpting/
(Google's information about when to use nofollow links: Hint to Brian, article editors are not creators of comments or foum posts or guestbook-posters - they are trusted people of the website and have a login. Login for content edition = trust indication = ability to set follow links)
https://support.google.com/webmasters/answer/96569?hl=en

If you have questions, Brian, please do let me know. I am happy to discuss with you the pro's and con's of your views. 
Have a great start into the new week all! 
Chris

**Comment by chriswagner0815** [comment]
Hi guys,
for better understanding, I would also make you aware of what Googles webmaster trends analyst said about the general issue of the nofollow use of links to other pages (in general) for your information:

https://youtu.be/GVKcMU7YNOQ?t=50m48s

**Comment by matchamochi** [comment]
[solid gold](http://inovasisolution.com "") ~<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by matchamochi** [comment]
[detik com](http://www.bangnapi.com "detik com") Membaca berita sudah bisa dilakukan dengan cara yang sangat mudah, kapan pun dan di mana pun Anda berada. Anda hanya perlu membawa sebuah handphone tanpa ribet membeli koran atau surat kabar, karena di internet banyak situs-situs berita yang selalu update informasi yang hot dan aktual. Di Indonesia sendiri, ada banyak sekali situs berita yang bisa Anda kunjungi. Dan tentu saja Anda bisa mendapatkan berita hangat dari berbagai macam topik, mulai dari berita kesehatan, politik, sports, pendidikan, ekonomi, sosial, dan lain sebagainya. Selain itu, berita yang tersaji online tidak hanya sebatas berita nasional, tetapi juga banyak berita internasional yang akan Anda temukan. Nah, apa sih Situs Berita seperti detik com ? bangnapi.com        
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by matchamochi** [comment]
[detiknews](http://www.newsdetik.net/ "detiknews") Membaca berita sudah bisa dilakukan dengan cara yang sangat mudah, kapan pun dan di mana pun Anda berada. Anda hanya perlu membawa sebuah handphone tanpa ribet membeli koran atau surat kabar, karena di internet banyak situs-situs berita yang selalu update informasi yang hot dan aktual. Di Indonesia sendiri, ada banyak sekali situs berita yang bisa Anda kunjungi. Dan tentu saja Anda bisa mendapatkan berita hangat dari berbagai macam topik, mulai dari berita kesehatan, politik, sports, pendidikan, ekonomi, sosial, dan lain sebagainya. Selain itu, berita yang tersaji online tidak hanya sebatas berita nasional, tetapi juga banyak berita internasional yang akan Anda temukan. Semuanya bisa Anda temukan hanya di newsdetik.net<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by matchamochi** [comment]
[klasemen liga inggris](http://www.sports-kompas.com "klasemen liga inggris") Kunjungi sports-kompas.com untuk berita klasemen Liga Inggris, hasil pertandingan, dan berita sepakbola terkini lainnya.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by matchamochi** [comment]
[sport okezone](http://www.sports-okezone.com "sport okezone")Kunjungi sports-okezone.com untuk berita olahraga terlengkap dan terupdate seperti sepak bola, F1, MotoGP dan lainnya. Simak berita terkini lainnya hanya di sport okezone<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by matchamochi** [comment]
[liputan6](http://http://www.sports-liputan6.com "liputan6") Membaca berita sudah bisa dilakukan dengan cara yang sangat mudah, kapan pun dan di mana pun Anda berada. Anda hanya perlu membawa sebuah handphone tanpa ribet membeli koran atau surat kabar, karena di internet banyak situs-situs berita yang selalu update informasi yang hot dan aktual. Di Indonesia sendiri, ada banyak sekali situs berita yang bisa Anda kunjungi. Bagi Anda pecinta bola dan ingin selalu update dengan berita bola terkini, liputan6 lah tempat yang pas untuk Anda. Hanya di sports-liputan6.com<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by matchamochi** [comment]
[solid gold](http://www.inovasisolution.com "solid gold") Berita dan Informasi Terbaru Bisnis, Finansial, Ekonomi, Perbankan, Investasi, Market Research dan Keuangan. Harga Emas Hari Ini, Berita Investasi Emas, Logam Mulia, Gold Price, Solid Gold, Solid Gold berjangka, PT. Solid Gold Berjangka, inovasisolution.com<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by matchamochi** [comment]
[cerita dewasa](http://www.wisatalendir.com "cerita dewasa") Situs wisatalendir.com memberikan perjalanan pornografi seperti cerita dewasa, cerita sex, cerita hot, tante girang, video bokep, cerita sedarah, cerita abg, foto bugil. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by matchamochi** [comment]
[detik sport](http://www.detik-sport.com/ "detik sport") Informasi Berita Seputar Dunia Olahraga Terupdate • Informasi Berita Olahraga Terbaru, Hasil Pertandingan, Klasemen, Jadwal Pertandingan, Gosip Lapangan Detik Sport<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by matchamochi** [comment]
[solid gold berjangka](https://www.diigo.com/item/note/656od/q9wr?k=f58cec48f764bcfabae98e87d14d8bd2 "solid gold berjangka") Berita dan Informasi Terbaru Bisnis, Finansial, Ekonomi, Perbankan, Investasi, Market Research dan Keuangan. Harga Emas Hari Ini, Berita Investasi Emas, Logam Mulia, Gold Price, Solid Gold, Solid Gold berjangka, PT. Solid Gold Berjangka<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by matchamochi** [comment]
[solid gold berjangka](https://disqus.com/by/solidgoldberjangka/ "solid gold berjangka") Berita dan Informasi Terbaru Bisnis, Finansial, Ekonomi, Perbankan, Investasi, Market Research dan Keuangan. Harga Emas Hari Ini, Berita Investasi Emas, Logam Mulia, Gold Price, Solid Gold, Solid Gold berjangka, PT. Solid Gold Berjangka<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by matchamochi** [comment]
[solid gold berjangka](http://sgberjangka.edublogs.org/2017/08/08/solid-gold-berjangka/ "solid gold berjangka") Berita dan Informasi Terbaru Bisnis, Finansial, Ekonomi, Perbankan, Investasi, Market Research dan Keuangan. Harga Emas Hari Ini, Berita Investasi Emas, Logam Mulia, Gold Price, Solid Gold, Solid Gold berjangka, PT. Solid Gold Berjangka<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by matchamochi** [comment]
[solid gold berjangka](http://solidgoldberjangka.kinja.com/selamat-datang-di-solid-gold-berjangka-1797623641 "solid gold berjangka") Berita dan Informasi Terbaru Bisnis, Finansial, Ekonomi, Perbankan, Investasi, Market Research dan Keuangan. Harga Emas Hari Ini, Berita Investasi Emas, Logam Mulia, Gold Price, Solid Gold, Solid Gold berjangka, PT. Solid Gold Berjangka<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by matchamochi** [comment]
[solid gold berjangka](http://www.purevolume.com/listeners/solidgoldberjangka "solid gold berjangka") Berita dan Informasi Terbaru Bisnis, Finansial, Ekonomi, Perbankan, Investasi, Market Research dan Keuangan. Harga Emas Hari Ini, Berita Investasi Emas, Logam Mulia, Gold Price, Solid Gold, Solid Gold berjangka, PT. Solid Gold Berjangka<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by matchamochi** [comment]
[solid gold berjangka](https://dzone.com/users/3070877/solidgoldberjangka.html "solid gold berjangka") Berita dan Informasi Terbaru Bisnis, Finansial, Ekonomi, Perbankan, Investasi, Market Research dan Keuangan. Harga Emas Hari Ini, Berita Investasi Emas, Logam Mulia, Gold Price, Solid Gold, Solid Gold berjangka, PT. Solid Gold Berjangka
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by matchamochi** [comment]
[solid gold berjangka](https://www.kiwibox.com/sgberjangka/mypage/ "solid gold berjangka") Berita dan Informasi Terbaru Bisnis, Finansial, Ekonomi, Perbankan, Investasi, Market Research dan Keuangan. Harga Emas Hari Ini, Berita Investasi Emas, Logam Mulia, Gold Price, Solid Gold, Solid Gold berjangka, PT. Solid Gold Berjangka
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by matchamochi** [comment]
[solid gold berjangka](https://www.hr.com/en/app/blog/2017/08/solid-gold-berjangka_j64b1zlm.html "solid gold berjangka") Berita dan Informasi Terbaru Bisnis, Finansial, Ekonomi, Perbankan, Investasi, Market Research dan Keuangan. Harga Emas Hari Ini, Berita Investasi Emas, Logam Mulia, Gold Price, Solid Gold, Solid Gold berjangka, PT. Solid Gold Berjangka<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by brianteeman** [comment]
Closed as the comments have not been updated for many months

**Comment by actualthemes** [comment]
Hi guys,
for better understanding,I made an article on https://www.actualthemes.com Greetings<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by annetorresss** [comment]
Hi guys! Do you mind visiting my website :) Thanks a lot you will gain a lot of information there special about seo. Thanks again. Link below.
[https://www.myoptimind.com/](https://www.myoptimind.com/ "https://www.myoptimind.com/")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by vdesignweb** [comment]
Which link contain attribute like rel="nofollow" so this is nofollow links. And others are dofollow links. Nofollow and dofollow both kind of links are helpful for getting traffic to website. But only the difference is that nofollow links will not consider for assigning weightage of the page from which we got link. I am  using huge nofollow link to my website [https://www.bismatrimony.com](https://www.bismatrimony.com "Bis Matrimony") so iam getting good traffic for my website..
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by vdesignweb** [comment]
Dofollow links will be counted by google and give you credit for your website and also help to improve your website rankings.

Nofollow will be dropped out of the google and not get help for your rankings on google.
https://www.bismatrimony.com<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by infoanilps** [comment]
I am getting this error on this Comments system. I have not changed anything but the db name, password and username. Best [Kerala Matrimony](https://www.bismatrimony.com/ "Kerala Matrimonial") Site<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by toliviaimmons** [comment]
so it's still possible for nofollow links to be [crawled by Google](https://www.myoptimind.com/seo-philippines/ "seo philippines") even now? Because sometimes I check on tools like search console or analytics for some of the nofollows and it's inconsistent because not all of them do and don't show up. Although I think I remember Google updating some of their rules for different seo capabilities and stats on websites.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14888">issues.joomla.org/tracker/joomla-cms/14888</a>.</sub>

**Comment by brianteeman** [comment]
please delete the spam and block the spammer
