### ISSUE TITLE
README.txt minior spelling error

### ISSUE THREAD

**Issue by NanoCaiordo** [joomla/joomla-cms#14897]
### Steps to reproduce the issue
Open README.txt at line 39 says

### Actual result
* How do you install Joomla - hhttps://docs.joomla.org/J3.x:Installing_Joomla

### Expected result
* How do you install Joomla - https://docs.joomla.org/J3.x:Installing_Joomla

### Additional comments
hhttps vs. https

**Comment by C-Lodder** [comment]
This has already been fixed: https://github.com/joomla/joomla-cms/commit/589acb6463a1ee684b866bbb9a4e8dbf240a3d4f

**Comment by zero-24** [comment]
closing Thanks.
