### ISSUE TITLE
Banner module is not adding spaced between elements

### ISSUE THREAD

**Issue by BastianWie** [joomla/joomla-cms#14893]
### Steps to reproduce the issue
1.) Do not a template overwrite for the banner
2.) create a banner module in joomla, add a banner to it, add the width & height
3.) Check the source generated here, it will be something like:

img src="banners/banner_example_468x60.gif" alt="486x60"width ="486"height ="60"/

### Expected result

img src="banners/banner_example_468x60.gif" alt="486x60" width="486" height="60"/

### Actual result

img src="banners/banner_example_468x60.gif" alt="486x60"width ="486"height ="60"/

### System information (as much as possible)

Joomla 3.6.5

**Comment by franz-wohlkoenig** [comment]
Please close as there is a PR.

**Comment by brianteeman** [comment]
If you are creating a Pull Request then you dont need to create an issue at the same time  ;)

**Comment by BastianWie** [comment]
@brianteeman thanks. It was my first pull request since a very long time and I wasn´t sure if i got the process to create a pull request correctly. The Joomla [howto](https://docs.joomla.org/My_first_pull_request_to_Joomla!_on_Github) is a little bit outdated and for a first time user not very easy to follow and understand (as we normally do not use a local installed software, such small changes could be easily be done online). So I picked that way to ensure its covered regardless if I manage to cover the pull request correctly ;-).

**Comment by brianteeman** [comment]
For a small change like this you can indeed do it online directly at github but I cant find a good tutorial for that right now - sorry

I took a quick look at your changes and they look fine - but I will take a more detailed look later today if others have not beaten me to it

**Comment by brianteeman** [comment]
Found one
https://help.github.com/articles/editing-files-in-another-user-s-repository/

I will try to find some time to expand it a little as you can also use this method to edit multiple files

**Comment by BastianWie** [comment]
sure its not very urgent and thanks for the link.

**Comment by Bakual** [comment]
There is a good one on JDocs: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests
