### ISSUE TITLE
Menu Editor-XTD plugin broken

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14890]
### Steps to reproduce the issue
Inside an article use the menu button to insert a link to a menu item in an article

### Expected result
When viewed on the front end the article will contain a working link to the menu item

### Actual result
The link is `<a href="null">link name</a>`

### System information (as much as possible)
current staging

**Comment by AlexRed** [comment]
I can't reproduce the problem. For me is ok the "Article" button in the TinyMCE editor work.
What menu item type you select ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14890">issues.joomla.org/tracker/joomla-cms/14890</a>.</sub>

**Comment by brianteeman** [comment]
Not the article button the menu button

I tried multiple including single article, single contact, tagged items. All produced an href of null

**Comment by AlexRed** [comment]
ooppss...  Sorry. Yes, I can confirm the problem for the menu button

![menu-button](https://cloud.githubusercontent.com/assets/1362388/24324238/b4f9648c-117a-11e7-91ea-9ece9421f1f2.png)

**Comment by infograf768** [comment]
grr, who the h... touched at that?

**Comment by brianteeman** [comment]
Guessing it is #12561

**Comment by dgt41** [comment]
Please test #14902

**Comment by brianteeman** [comment]
closed as we have a pr
