### ISSUE TITLE
[4.0] Menus: Buttons not working

### ISSUE THREAD

**Issue by yasirunilan** [joomla/joomla-cms#14904]
### Steps to reproduce the issue
Main Side Nav -> Menus -> Manage -> There is a column named "Linked Modules" -> select an option from it. A modal opens. In that modal under the Module tab there is a field named "Base item". Click on the "Create" button. Then another modal opens. Try to close it by clicking on following three buttons in the new modal. "Close" , "Save &Close", "Save"

### Expected result
An action should be there upon clicking the buttons. If click on "Close", modal should be closed.

### Actual result
Nothing Happens
![button not working](https://cloud.githubusercontent.com/assets/9814784/24329508/745e0f2a-1226-11e7-8b2c-fed9c71fbc96.PNG)

### System information (as much as possible)
Joomla! 4.0.0-dev
Windows 10
Chrome 57.0.2987.110 (64-bit)
PHP 5.6

**Comment by franz-wohlkoenig** [comment]
confirmed.
### System information
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
@dgt41 - think you fixed this 5 months ago. Probably an error in `core.js`?

**Comment by dgt41** [comment]
Will take a look, although I don't remember anymore and there is a curse with these modals: they keep breaking

**Comment by brianteeman** [comment]
This would appear to be resolved in the current branch of J4 so I am closing this. It can always be reopened
