### ISSUE TITLE
[4.0] Menus: Input fields not shown completely

### ISSUE THREAD

**Issue by yasirunilan** [joomla/joomla-cms#14903]
### Steps to reproduce the issue
Main Side Nav -> Menus -> Manage -> There is a column named "Linked Modules" -> select an option from it. A modal opens. In that modal there are input fields on the right side of the modal. 

### Expected result
Input fields should be shown completely.

### Actual result
Some input fields are shown a part only
![incomplete inputbox](https://cloud.githubusercontent.com/assets/9814784/24329435/bd5030ca-1224-11e7-8029-045bb506aad8.PNG)

### System information (as much as possible)
Joomla! 4.0.0-dev
Windows 10
Chrome 57.0.2987.110 (64-bit)
PHP 5.6

**Comment by franz-wohlkoenig** [comment]
confirmed.
### System information
Joomla! 4.0.0-dev
macOS Sierra, 10.12.3
Firefox 52.0.1 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
Closed as this has been resolved in the current branch for J4
