### ISSUE TITLE
com_content - missing link to edit form for non author

### ISSUE THREAD

**Issue by marcochirienti** [joomla/joomla-cms#14916]
In com_content the articles list view does not display the link to the edit view if the user does not have edit permissions.

![no author tool-tip](https://cloud.githubusercontent.com/assets/23710150/24348607/934b25ce-12dc-11e7-9a2c-4158c1f560ef.jpg)

If the user does not have edit permissions on an item, is still able to save the item as a copy.

![save as copy article](https://cloud.githubusercontent.com/assets/23710150/24348637/ad97e03e-12dc-11e7-9622-b3f5ee3b718d.jpg)

The tool-bar buttons are set accordingly to this logic, but the link to the edit view is not displayed, so the user have to insert the URL manually to access the edit form.

### Steps to reproduce the issue

- create an article with an user assigned to the "Super Users" group;
- inside the article, disable all permissions for the "Administrator" group;
- log in with a user assigned to the "Administrator" group and access the com_content component;
- check the article in the articles view;

### Expected result

The user should be able to access the edit view from the list view.

### Actual result

The user can access the edit view typing the URL manually, but the link in the list view is not displayed.

### System information (as much as possible)

Joomla <= 3.7

### Additional comments

Other components share the same behaviour.
If you think this is an issue, I can make a pull request to fix this for com_content.
If everything works fine, I can do it for other components too.

**Comment by AlexRed** [comment]
I can't confirm the problem in Joomla 3.7.0 nightly. 
Your screenshot are not from Joomla 3.7.0.
Please try also in Joomla 3.7.0 stagin or nightly builds<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14916">issues.joomla.org/tracker/joomla-cms/14916</a>.</sub>

**Comment by marcochirienti** [comment]
I'm sorry, i made a mistake. I wrote Joomla < 3.7 but actually the issue impacts either 3.8 and 4.0.
Yes, images are from a Joomla 3.6 install but i checked the code and it's the same in 3.6, 3.7, 3.8 and 4.0

Anyway this is the screenshot from a clean 3.7 install.

![3 7 0](https://cloud.githubusercontent.com/assets/23710150/24364550/66c485ae-1313-11e7-867a-7138595c654f.jpg)

And for the sake of completeness, when the item is displayed as simple text the span title is set to a meaningless "Alias"...

![3 7 0 alias tool-tip](https://cloud.githubusercontent.com/assets/23710150/24364910/7d191f1c-1314-11e7-8a7a-33e1c771c074.jpg)

**Comment by AlexRed** [comment]
I can confirm the "Alias" title if no link

**Comment by marcochirienti** [comment]
And, you are right about the edit form. It is not accessible in 3.7 by direct link.

**Comment by marcochirienti** [comment]
I'm sorry, maybe I  screwed up something with my 3.6 installation.
I repeated the test on a 3.6 clean install and the item is not accessible by direct link.

**Comment by franz-wohlkoenig** [comment]
@marcochirienti is this Issue solved and can be closed?

**Comment by zero-24** [comment]
I'm closing here. If this is sill a problem @marcochirienti can just reopen it.

**Comment by marcochirienti** [comment]
It's OK, it was just a problem of my test installation.
