### ISSUE TITLE
[com_fields] media field look and feel after scrolling down

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#14927]
### Steps to reproduce the issue

Install joomla-cms/staging@1c52ed38516f2406fe63dbb762242ae3b82cfcb2

Create media field, only completing the required fields such as: 

<img width="727" alt="screen shot 2017-03-27 at 14 26 39" src="https://cloud.githubusercontent.com/assets/400092/24358554/68fdd312-12f9-11e7-93af-1175cc987fc6.png">

Go to front end and edit article - click select on the media field

### Expected result

Nice model with a good look and feel

### Actual result

I get this:
<img width="1074" alt="screen shot 2017-03-27 at 14 27 07" src="https://cloud.githubusercontent.com/assets/400092/24358584/84d0fb00-12f9-11e7-8d76-d56194f27a95.png">

In addition to #14926 the model, even on half my 27" screen, gives no indication that you can scroll down....

When you scroll down you get: 

<img width="1054" alt="screen shot 2017-03-27 at 14 30 51" src="https://cloud.githubusercontent.com/assets/400092/24358742/04055e8e-12fa-11e7-9c82-c5872242e382.png">

Note there is no help text on the image URL or upload wells - this all makes no sense - could it not be three simple tabs like the Extensions Installer page? 

### System information (as much as possible)

https://gist.github.com/PhilETaylor/b1ff259a06518f903339950ca81e35d7

**Comment by brianteeman** [comment]
This isnt a com_fields issue. This is a com_media manager as it is the same wherever the media manager is used

**Comment by PhilETaylor** [comment]
its both - this view is used by the new com_fields media field type...

**Comment by laoneo** [comment]
> the user experience will be crap

As @brianteeman already said, this media manager view is loaded also when you edit an article and want to change the images of an article, so the user experience is crap there as well. But there is some hope. For Joomla 4 we are going to revamp the media manager and are working close with the UX team (by the way, UX is looking for some people, perhaps you might consider to join them), so hopefully we can then do better. I guess in the meantime we have to live with what we have right now, even tough you don't want to hear that.

**Comment by PhilETaylor** [comment]
> For Joomla 4 we are going to revamp the media manager 

Yeah, I heard the same story for Joomla 3, never happened... 

>working close with the UX team

The same UX team headed by @cpfeifer who told me I was "expecting too much of him" to make simply timely decisions about "basic" UX issues months ago... yeah, I've lost all hope in that team - the real people that know about UX have already abandoned that team, like @

> perhaps you might consider to join them

Absolutely no chance. I'm a developer, not a UX expert. Although I know when an experience is crap, I don't have all the answers on making it better.
