### ISSUE TITLE
DTD in TemplateDetails.xml

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14921]
What is the purpose of this line (and similar) in all the core templatedetails.xml files

`<!DOCTYPE install PUBLIC "-//Joomla! 1.6//DTD template 1.0//EN" "https://www.joomla.org/xml/dtd/1.6/template-install.dtd">`

`<!DOCTYPE install PUBLIC "-//Joomla! 2.5//DTD template 1.0//EN" "https://www.joomla.org/xml/dtd/2.5/template-install.dtd">`

If you follow those links you will be redirected to the joomla home page

**Comment by dgt41** [comment]
XML validation: http://www.xmlfiles.com/dtd/dtd_intro.asp

**Comment by brianteeman** [comment]
@dgt41 if that is the case and it would appear to be so then its not much good that
> If you follow those links you will be redirected to the joomla home page

**Comment by dgt41** [comment]
@brianteeman someone started some work on these: https://github.com/joomla/schemas
