### ISSUE TITLE
Better Archived Article Support

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#14923]
Two things would improve support for archived articles.

1) In the existing category views being able to set an option to include archived articles.
2) In the existing archived view being able to filter to a given category.

**Comment by franz-wohlkoenig** [comment]
make an Article in 3 Days as Example atomatically archived (theres a Issue open which i search).

**Comment by brianteeman** [comment]
Before making any changes we really should define what an archived article actually is

**Comment by mbabker** [comment]
That would be good too.  My two ideas really were things I would have appreciated being able to do while hiding the old Team News content on .org.

**Comment by brianteeman** [comment]
Which still depends on what you expect the archived state to mean.

**Comment by Bakual** [comment]
Second one makes sense to me.
First one not so much imho, what would be the difference to a published article when archived appears in category lists?

**Comment by franz-wohlkoenig** [comment]
Archived Article: Not show on Homepage, but showed for Search-Index (iE for gone Meeting-Annonces).

**Comment by mbabker** [comment]
The problem is though archived articles are in essence only accessible through search, they fall off the site navigation.  That might be the behavior you want in some cases but not all.

Going back to that Team News change, I actually tried archiving the category first leaving the articles published.  That broke the routing (that's a bug on its own IMO).  Re-published the category, archived articles.  Now its parent menu item is set to hide empty categories; that was the only way to get that category to stop showing in the navigation.  So far so good?  Except for https://www.joomla.org/announcements/team-news.html now shows as an empty category page instead of listing the (now archived) articles within it.  And that link is still active at least in the breadcrumb.

We can't change that to an archived article view.  There are more articles archived on the site than just that category.  And since the view lacks a category filter...

See our issue in this specific use case?  I'm happy with any change that improves management and user experience related to archived articles, but this change we made demonstrates that there is a case for redefining the archived state and how it is integrated into various views.

**Comment by brianteeman** [comment]
And yes I think it is another bug that the archive view doesnt have any category filters

**Comment by Hackwar** [comment]
As I said already for Joomla 1.6: Archived articles are not properly defined, they don't fill a special void right now and from my perspective should be removed asap. Define a behavior, and especially one that is consistent to all our other views, and then we can implement something that we can call archived articles, but right now those are pretty useless.

To be honest, the longer I think about this, the more I don't see a use for this feature. The only thing that I think would be usefull would be a change to routing to introduce a real canonical URL for content items. Make it possible to move articles to other categories/menu items and they still retain their canonical URL and we should be fine.

**Comment by brianteeman** [comment]
There are several use cases for them

1. Keep content on the site (prevents 404s etc) but exclude it from the blog and list views and/or exclude it from the search (through the plugin setting)
2. Have a date based display of content such as old press releases or announcments

Those are just two use cases that I regularly see

**Comment by Bakual** [comment]
Archived state makes sense as it is. Think about the real world equivalent of putting an item into an archive (eg in a museum). It will not be shown in the vitrines but it is still available for those searching explicitely for it and it is listed in the inventory.
Same is true for archived articles in Joomla. They don't show in general list views but can be found when using searches or when you know the URL or when you use the special archived list.

It can be improved of course, but it is certainly not unuseable as @brianteeman also pointed out.

**Comment by franz-wohlkoenig** [comment]
what i remembered in [comment](https://issues.joomla.org/tracker/joomla-cms/14923#event-254624 "comment") was #14863<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14923">issues.joomla.org/tracker/joomla-cms/14923</a>.</sub>

**Comment by alikon** [comment]
i've tryied to fix the 2nd one #15184

**Comment by brianteeman** [comment]
And didnt this lack of a written and agreed definition just  hit us in the backside with workflows

**Comment by mbabker** [comment]
Yup.

**Comment by mbabker** [comment]
Not much is going to change in 3.x at this point and the discussion around this feature in 4.0 is a moot point with workflows.
