### ISSUE TITLE
RTL: sidebar issue on smaller screens less than 600 wide

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#14934]
Just set the admin language to RTL and display at small sizes.
(one can just change en-GB.xml to `<rtl>1</rtl>`)

![screen shot 2017-03-27 at 16 52 05](https://cloud.githubusercontent.com/assets/869724/24362777/0b762e5a-130e-11e7-977b-f8368a54b47e.png)

**Comment by dgt41** [comment]
@ciar4n can you take a look at this one?

**Comment by brianteeman** [comment]
Confirmed the issue

**Comment by ciar4n** [comment]
PR created...  #14939

**Comment by infograf768** [comment]
Closed as we have a PR https://github.com/joomla/joomla-cms/pull/14939<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14934">issues.joomla.org/tracker/joomla-cms/14934</a>.</sub>
