### ISSUE TITLE
com_fields value saving to db but then not being retrievable 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#14932]
### Steps to reproduce the issue

Install joomla-cms/staging@1c52ed38516f2406fe63dbb762242ae3b82cfcb2

Create imagelist custom field, only completing the required fields such as: 

<img width="440" alt="screen shot 2017-03-27 at 15 06 26" src="https://cloud.githubusercontent.com/assets/400092/24360334/f79e1eec-12fe-11e7-939d-923b4840faf6.png">

Go to front end and edit article to see the dropdown, select an image and click save
or
Go to back end and edit article to see the dropdown, select an image and click save

### Expected result

The selected value of the dropdown is saved.

### Actual result

The selected value of the dropdown is **NOT** saved.

see: http://screenshot.myjoomla.io/2M2d1S0C3t15

### System information (as much as possible)

https://gist.github.com/PhilETaylor/b1ff259a06518f903339950ca81e35d7

**Comment by brianteeman** [comment]
Couldnt get your recording to load :(

Can not confirm on the admin see 
![phil2](https://cloud.githubusercontent.com/assets/1296369/24360679/f16f1c14-12ff-11e7-9240-026c1e29c6de.gif)

**Comment by brianteeman** [comment]
And cannot confirm on frontend either

![phil3](https://cloud.githubusercontent.com/assets/1296369/24360900/7856ef54-1300-11e7-94c9-c2a7aede3dae.gif)

**Comment by PhilETaylor** [comment]
Thats because you are superman and every one else is just an idiot.

**Comment by PhilETaylor** [comment]
Infact at the current git revision NONE OF THE CUSTOM FIELDS SAVE!!!

**Comment by PhilETaylor** [comment]
Full video: https://www.youtube.com/watch?v=FveVUozZMPc

**Comment by AlexRed** [comment]
I can't confirm the issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14932">issues.joomla.org/tracker/joomla-cms/14932</a>.</sub>

**Comment by PhilETaylor** [comment]
Changed title to be 

> **com_fields value saving to db but then not being retrievable** 

Im still testing but I think this commit broke it 1c52ed38516f2406fe63dbb762242ae3b82cfcb2 which is from PR #14558

**Comment by PhilETaylor** [comment]
@AlexRed Can you confirm your PHP version and the EXACT COMMIT that you are testing against?

**Comment by brianteeman** [comment]
Probably #14558

**Comment by brianteeman** [comment]
i can confirm this on current staging (nightly wont show it as #14558 was merged today)

**Comment by PhilETaylor** [comment]
> Probably #14558

Like I said... 

This is why testing should be done on the very latest code available - not nightly.... 

So Im not an idiot after all.....

**Comment by brianteeman** [comment]
No you are still an idiot

**Comment by infograf768** [comment]
I confirm that a Text custom field duely filled in admin does not display in frontend

**Comment by AlexRed** [comment]
Also my test in nightly.

**Comment by PhilETaylor** [comment]
> @infograf768 I confirm that a Text custom field duely filled in admin does not display in frontend

or backend you will find

> @AlexRed Also my test in nightly.

Thanks - thats what I guessed. 

> @brianteeman No you are still an idiot

Personal attacks (should) not be tolerated by the Joomla project. Even in jest (if such). Being an active contributor doesn't give you a right to issue personal attacks. Even those in power can be removed... repeatedly.

**Comment by allrude** [comment]
What You Give Is What You Get

**Comment by joomdonation** [comment]
In my test, the custom fields data is not being saved. Checked the code and found typo. I made the PR https://github.com/joomla/joomla-cms/pull/14941 which should solve this issue.

**Comment by PhilETaylor** [comment]
Fixed by #14941
