### ISSUE TITLE
console.log(c) statement in tinymce.min.js

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#14937]
### Steps to reproduce the issue

Before addressing this issue, see #14936

Install joomla-cms/staging@1f89fb09d941d3c7d14b366ffe84d880f9347cf7

Edit content on the back end.

### Expected result

No Javascript console messages

### Actual result

Javascript console messages

<img width="738" alt="screen shot 2017-03-27 at 16 35 15" src="https://cloud.githubusercontent.com/assets/400092/24364655/5ed1b66c-130b-11e7-8748-2e9a76eb0129.png">

### Additional comments

This results from a console.log(c) in tinymce.min.js - that certainly could and should be removed.

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/14938

**Comment by PhilETaylor** [comment]
Thanks but do we know why this min file is not a minified version of its source file?

> Before addressing this issue, see #14936

**Comment by C-Lodder** [comment]
I've also minified based on the uncompressed version.
