### ISSUE TITLE
Inconsistent button's tooltips

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#14949]
### Steps to reproduce the issue
![loggedinusers](https://cloud.githubusercontent.com/assets/368084/24382038/ab5f8200-1308-11e7-95a6-2ebe9738908e.jpg)

Log in the frontend.
Log in the backend.
Go to Control Panel.
Move cursor over the red X button.
See 2 tooltips with different spellings.

Which one to use? Do we need both tooltips? If no, should the one in the `span` tag be removed?

In \administrator\modules\mod_logged\tmpl\default.php:
```
<?php if ($user->client_id == 0) : ?>
	<a title="<?php echo JHtml::_('tooltipText', 'MOD_LOGGED_LOGOUT'); ?>" href="<?php echo $user->logoutLink; ?>" class="btn btn-danger btn-mini hasTooltip">
		<span class="icon-remove icon-white" title="<?php echo JText::_('JLOGOUT'); ?>"></span>
	</a>
<?php endif; ?>
```

**Comment by brianteeman** [comment]
The one in the span should be changed to aria-hidden

**Comment by nileshprasad137** [comment]
@brianteeman adding` aria-hidden="true" `doesn't seem to work. So, i remove title form the` span `tag.
That should work.

**Comment by brianteeman** [comment]
aria-hidden=true is needed to prevent screenreaders reading out the value of the icon font.

closing here as we have a PR
