### ISSUE TITLE
advanced permissions reports ACL - completely foobar

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14959]
### Steps to reproduce the issue
Go to the advanced permissions report for user groups and it will look like this
<img width="1245" alt="screenshotr10-19-51" src="https://cloud.githubusercontent.com/assets/1296369/24398059/1caf8814-13a0-11e7-829e-b3f64e241e27.png">

### Expected result
A list of the actions for the component or code actions
See
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_users/helpers/debug.php#L64

So for example as com_cache only has actions for core.admin and core.manage no other columns should have any data.

something like
<img width="811" alt="screenshotr10-26-39" src="https://cloud.githubusercontent.com/assets/1296369/24398341/10b124f4-13a1-11e7-8017-96b8167f3acb.png">

### Actual result
Instead of there being information for the asset the columns are coming from 
Use default actions from configuration if no component selected or component doesn't have actions
components/com_config/model/form/application.xml'
See https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_users/helpers/debug.php#L90

**Comment by klas** [comment]
Confirmed with staging 8215b36df509fbcb1c8c8b05002c883f9520d442<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14959">issues.joomla.org/tracker/joomla-cms/14959</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Closed as having PR #15524<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14959">issues.joomla.org/tracker/joomla-cms/14959</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Re-opened as PR doesn't solve all Issues.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14959">issues.joomla.org/tracker/joomla-cms/14959</a>.</sub>

**Comment by alikon** [comment]
these 3 components (for example) are a special case they don't have "actions"
- com_ajax
- com_contenthistory
- com_categories

so these should be not listed in the component select list of items ?

i'm thinking correctly ?
