### ISSUE TITLE
Undefined variable: ntext

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#14951]
### Steps to reproduce the issue

![menu](https://cloud.githubusercontent.com/assets/368084/24384000/93c9db42-1315-11e7-87d9-9910c72f8aa2.jpg)
Create a menu with a menu item.
Disable this menu.
Try to enable the menu item under this menu.
An error message is displayed:
```
Error
Failed publishing 1 menu item as at least one of its parents is unpublished or one of its children is checked out.
```

In the PHP error log:
> PHP Notice:  Undefined variable: ntext in \administrator\components\com_menus\controllers\items.php on line 248

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #14955

**Comment by macproflex** [comment]
im facing a problem with Error

Failed publishing 1 menu item as at least one of its parents is unpublished or one of its children is checked out.
create a new item
try to publish
always same error and unpublished menu
need some help here please<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14951">issues.joomla.org/tracker/joomla-cms/14951</a>.</sub>

**Comment by brianteeman** [comment]
Please dont comment on closed issues - no one will see them.

For support please use the forum https://forum.joomla.org
