### ISSUE TITLE
Memcached AWS Auto-discovery Support

### ISSUE THREAD

**Issue by jdolinski** [joomla/joomla-cms#14950]
AWS [Elasticache Memcached support allows auto-discovery](http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/AutoDiscovery.html "") to dynamically manage memcached nodes in the cluster. Amazon ElastiCache Cluster Client is an enhanced PHP library to connect to ElastiCache clusters. This client library has been built upon libmemcached and is released under the Apache License. https://github.com/awslabs/aws-elasticache-cluster-client-memcached-for-php/releases

Current Joomla release as of today (3.6.5) does not support AWS's autodiscovery of nodes and design is based on configuring static nodes in a multi memcached cluster. As of today, the static feature is not fully implemented and will require you to update your configuration if new nodes or failures occur in your cluster. This is a new feature request to support the PHP autodiscovery fork.

**Comment by jdolinski** [comment]
Client installation: http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/Appendix.PHPAutoDiscoverySetup.html
Using Autodiscovery (PHP example): http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/AutoDiscovery.Using.html<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14950">issues.joomla.org/tracker/joomla-cms/14950</a>.</sub>

**Comment by brianteeman** [comment]
Closing as we now have a PR for testing - thanks see #14993

**Comment by jdolinski** [comment]
@brianteeman Thanks - the Travis CI failed because of the dependency on AWS memcached module. Do you need me to work through that? This made me realize I also need to test this pull on a server using the standard PHP memcached module. I will do this tomorrow.
