### ISSUE TITLE
Content save doesn't get saved in joomla website (used to work before)

### ISSUE THREAD

**Issue by careerscale** [joomla/joomla-cms#14969]
### Steps to reproduce the issue
Hi,

our NGO website (http://tmad.org) has intesting problem last one week or more. 

I login to the admin and try to edit an article, it doesn't save, it doesn't show error also but just exits and shows the home page of the website.

I couldn't find what is the problem. it used to work before.

### Expected result
Save content and let admin user to do other activities in the admin site.

### Actual result
doesn't save the data and exits to home page

### Additional comments
Joomla! 2.5

**Comment by Bakual** [comment]
Closing since there is no information given.

**Comment by careerscale** [comment]
sorry, I didn't know it got saved automatically, updated information

**Comment by careerscale** [comment]
@Bakual  should I report another one or can is this good now with data?

**Comment by Bakual** [comment]
Reopened it :smile:

**Comment by Bakual** [comment]
Hmm, reading your issue, it is about Joomla 2.5 which is out of date by a few years and not supported anymore. So I will close this issue again.
You can use the forums (http://forum.joomla.org/) to get some help and **you really should upgrade the site to Joomla 3.x**

**Comment by careerscale** [comment]
Ok, will do upgrade. thanks


Thanks
Harinath Mallepally
harinath@careerscale.in
Careerscale IT Consulting LLP
