### ISSUE TITLE
[com_fields] Calendar.js typo

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#14967]
I am assuming that this should be button not button ?
https://github.com/joomla/joomla-cms/blob/staging/media/system/js/fields/calendar.js#L1107

@dgt41

**Comment by dgt41** [comment]
It is singular button as `element.getElementsByTagName('button')` is an array BUT the last part`[0]` forces to the first element of the array

**Comment by brianteeman** [comment]
what a terrible attempt by me at a bug report when it refers to a typo and i had autocorrect on ;)
The typo is that
`buttton  = element
`
has three letter t

**Comment by dgt41** [comment]
Actually those two lines (input and button) might not be used at all from that part of the code so we can drop them

**Comment by brianteeman** [comment]
@dgt41 whether it is fixing the typo or removing the lines can you do a PR for it please

**Comment by brianteeman** [comment]
Closed as resolved elsewhere
