### ISSUE TITLE
Can we create a menu item to show all articles?

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#14972]
### Steps to reproduce the issue
Currently I can choose a blog view from 1 category (including subcategories).  To show all article I need to create a work around where I create a root category and select it and show all subcategories.  This is not ideal, and potentially messes with SEO.  Ideally if we could have an option "all categories" in the menu item, or as a second suggestion a separate menu item for all categories (I prefer the first).  On some websites the current implementation is fine, but for a blog type of website it would be preferable to have the implementation I am suggesting.

I'm not entirely sure how to achieve this, but I think it's within the view.html.php file that I need to be.

### Expected result
It works, I am asking for a new feature.

**Comment by brianteeman** [comment]
This can already be done using the Articles - Category module. Just embed it in an article and you are good to go. See https://brian.teeman.net/site-map as an example

**Comment by brianpeat** [comment]
While I don't have a need for this, I could see it as handy for a 100% blog type site where you want the front page to display ALL articles. I think all this would take is to modify the blog menu item to allow for multiple categories or All. This would be similar to the way the category function works in the new custom fields. It allows you to choose All or pick specific categories. Not sure if you'd just remove the subcategory levels option (since the admin could just add all the subs to the option) or if you'd leave it in since some sites may have dozens of subcategories.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14972">issues.joomla.org/tracker/joomla-cms/14972</a>.</sub>

**Comment by brianteeman** [comment]
Again you can do this already - you just need to have a parent category - this is exactly what I do on https://brian.teeman.net

**Comment by brianpeat** [comment]
True, but it forces you to now have another directory in the url structure (unless you use something like sh404SEF). Seems like it would be a handy feature in my opinion. Saves an extra (and forced) structure layer.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14972">issues.joomla.org/tracker/joomla-cms/14972</a>.</sub>

**Comment by mbabker** [comment]
A plain "show all articles" menu item is not feasible with the way Joomla handles routing.  That will create more issues than it will bring improvements.

**Comment by mbabker** [comment]
Because a module doesn't have routing capabilities.  By creating a menu item with the same configuration, that menu item would then get accounted for when generating URIs.

**Comment by brianteeman** [comment]
So can this be closed then?

**Comment by brianteeman** [comment]
> True, but it forces you to now have another directory in the url structure 

@brianpeat no not really. On my site the content is in the following category structure
blog
--joomla
--web

But you won't see the "blog" anywhere in the url

**Comment by brianpeat** [comment]
@brianteeman ah, I suppose it's because blog is the same as home in this scenario so it never appears?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14972">issues.joomla.org/tracker/joomla-cms/14972</a>.</sub>

**Comment by brianteeman** [comment]
Exactly. So the initial comment that this is not ideal for SEO was incorrect.

**Comment by brianpeat** [comment]
That makes sense. I still think it would be nice to be able to pick and choose categories for the blog, but honestly if you just stick the ones you want under a parent it works the same anyway, so yeah, I'd say close this one.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14972">issues.joomla.org/tracker/joomla-cms/14972</a>.</sub>

**Comment by brianteeman** [comment]
and you still can pick and chose the categories for the blog. If you dont want a category in the blog dont put it in the parent blog category ;)

**Comment by uglyeoin** [comment]
In some cases the site is a blog, so in that instance you would not want a root category called blog.  It can remain closed as I do not have a better solution, but in terms of UX this is a pretty big fail in my opinion.

**Comment by brianteeman** [comment]
Please explain why this is a fail.

**Comment by uglyeoin** [comment]
I don't believe a new user will intuitively be able to work this out.  I have been using Joomla! since 2008 and I didn't know this.  Perhaps I am wrong, but I think a user would expect to be able to choose "all categories" from their menu item.  Maybe it is something for @cpfeifer to look at and do some user research as 1 persons [my] opinion is hardly evidence.  

My point is that it doesn't matter how easy it is, if it "feels" like a hack or workaround, and feels difficult to a new user, then that's the reputation we'll get.  A lot of this stuff is just perception.

**Comment by cpfeifer** [comment]
What is the real world usage for this? Why it is important to have this feature and who is it important to? Those are the questions we need to ask for any new feature concept. 

I hear what you're saying, but I don't think this is the solution. It would be better to address the category / article / menu item workflow, the number of steps, options and screens required to do this is the real reason it's so difficult for users to understand.

**Comment by uglyeoin** [comment]
I'm not sure I understood your answer, but happy to discuss, in private if you prefer.  The use case for me would be blog style websites only.  The only time it could work is when you want to show all of your content on one page.  Even then there's a chance you have Ts & Cs that you don't really want on your blog page.  It might be preferable in that instance to show all articles except category X

**Comment by cpfeifer** [comment]
I understand what you're saying. The question we need to find an answer to is how many users want this and how badly do they want it. 

There are many features in Joomla that let you select "All Categories" or pick them individually, but not in a menu item. I personally have never thought of this or ever had the need to do it, but after thinking about this a bit it could be very useful and used in many different ways. I think it's an idea worth exploring.

**Comment by mbabker** [comment]
Again, I'm just going to warn that attempting to do this as a component view has ramifications that loading the data in a module doesn't.  Item routing being the main one.  So anyone considering attempting this MUST tackle that issue as well.  It's not as simple as "copy what this module can do into a component view and done".

**Comment by brianteeman** [comment]
I still dont see the usecase for this that can not already be achieved.

PS Please dont fall into the trap of making Joomla into another CMS.

**Comment by cpfeifer** [comment]
I don't believe it's a priority, but it's worth exploring in my opinion. That does not mean anything more than it says.

**Comment by uglyeoin** [comment]
It seems like a big job, I found it a little unintuitive but I don't have the skills to fix it.  @mbabker makes a good point, it would need some way of routing it and copying the module won't work.  

@brianteeman I don't believe in thinking like that.  If something is useful and another CMS can do it then I have no problem with Joomla! also doing it.  I'm not in the camp of "we can't do that, we're not them".  I do think it would be better to move towards content as "items" not necessarily articles, but then I'm starting to sound like that other CMS instead ha ha.

@cpfeifer clear as day ha ha.  

If you want to close this go ahead, at the moment I don't have the time or the skills to fix.
