### ISSUE TITLE
Spelling mistake in default content for sample blog.

### ISSUE THREAD

**Issue by RenniePet** [joomla/joomla-cms#14979]
### Steps to reproduce the issue

Install Joomla and request the sample blog setup.

### Actual result

In the section "About your home page" it says, "Then there are links to the 4 nest oldest articles." Should be "neXt oldest articles".

**Comment by brianteeman** [comment]
Thank you for reporting this I will do a Pull Request to fix it

**Comment by brianteeman** [comment]
Close as we have a PR #14980
