### ISSUE TITLE
Problem in viewing custom modules: View not found [name, type, prefix]: advancedmodules, html, advancedmodulesView

### ISSUE THREAD

**Issue by TungTh** [joomla/joomla-cms#14977]
### Steps to reproduce the issue
In the administrator page, go to "Extensions / Modules".
Select any module, get error message 
" Error
An error has occurred while fetching the JSON data: HTTP 500 status code."

### System information (as much as possible)

Jomala 3.6.5

### Additional comments
Error from Chrome console: 
![screen shot 2017-03-28 at 17 36 29](https://issues.joomla.org/uploads/1/eec7eacf5a08588fa7f7383146d6aefe.png)
Failed to load resource: the server responded with a status of 500 (View not found [name, type, prefix]: advancedmodules, html, advancedmodulesView)

**Comment by infograf768** [comment]
advancedmodules is a third party extension. Not joomla core.

You should be able to solve your issue by reinstalling the extension.

Closing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14977">issues.joomla.org/tracker/joomla-cms/14977</a>.</sub>
