### ISSUE TITLE
Composant Factsheets Joomla! 4

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#14978]
Hello, with the important evolution of Joomla! 3.7 with fields. Could not one imagine that for Joomla! 4, the component "contact cards" simply becomes "plugs". We could keep the layout, the management of the links to make recipe books, catalogs, directories ... We should simply get our hands on some title of fields of the component.

Bonjour, avec l'évolution importante de Joomla! 3.7 avec les champs. Ne pourrait-on imaginer for Joomla! 4 que le composant "fiches de contact" devient tout simplement "fiches". Nous pourrions garder la mise en pages, la gestion des liens pour réaliser des livres de recette, catalogues, annuaires... Il faudrait simplement nous donner la main sur certains titre de champs du composant.

**Comment by C-Lodder** [comment]
I have no idea what you mean

**Comment by Magnytu2** [comment]
Simply release the "contact plug" component. Make it more flexible to make other types of cards. Example: recipe cards, catalogs, etc ...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14978">issues.joomla.org/tracker/joomla-cms/14978</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
If this Issue get no Response, it will be closed at 22th June 2017.

**Comment by franz-wohlkoenig** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14978">issues.joomla.org/tracker/joomla-cms/14978</a>.</sub>
