### ISSUE TITLE
[com_fields] MySQL migration file 3.7.0-2016-08-29 missing if exists clause

### ISSUE THREAD

**Issue by nikolayt** [joomla/joomla-cms#14987]
The file 3.7.0-2016-08-29.sql is missing IF EXISTS clause on CREATE TABLE #__fields_categories

**Comment by zero-24** [comment]
@nikolayt can you send this change as pull request? Than this change is linked to your account :smile: 

https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by brianteeman** [comment]
Are you sure? That was the sql where the table was first introduced  wasnt it?

**Comment by alikon** [comment]
can be closed as we have #15171 already merged

**Comment by franz-wohlkoenig** [comment]
closed as written above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14987">issues.joomla.org/tracker/joomla-cms/14987</a>.</sub>
