### ISSUE TITLE
Fatal error: Call to undefined method Joomla\Registry\Registry::loadJSON() in /hermes/walnaweb02a/b1950/pow.kttcadmin/kttc.ac.ke/plugins/system/jdownloads/jdownloads.php on line 39 

### ISSUE THREAD

**Issue by Jnyawira** [joomla/joomla-cms#14984]
Hello

I was trying to upgrade my joomla cms from version 2.5.28 to 3.5.1 and in the process this message came up upon completion.Kindly any assistance to resolve this as I have not really been able to sort this out.I can't access my joomla back end to disable the mention plugin.

Any assistance will be be of great help for me to resume normalcy.

Note: I am partly new to this.

**Comment by brianteeman** [comment]
You will need to disable the plugin directly in the database.

I am closing this here as it is not the correct place to ask for support. Please use the forum https://forum.joomla.org

**Comment by Jnyawira** [comment]
thanks
