### ISSUE TITLE
[4.0] com_banners ordering by drag

### ISSUE THREAD

**Issue by NunoLopes96** [joomla/joomla-cms#14992]
### Steps to reproduce the issue

Administrator -> Sidebar menu -> Component -> Banners -> Banners

If you have more than 1 banners and try to order them by drag an error will pop in the console, although this saves the order and there is no errors visible.

### Expected result

No error in console

### Actual result

![screenshot from 2017-03-29 18-16-20](https://cloud.githubusercontent.com/assets/20955884/24467316/eee6bb52-14ab-11e7-8909-1e23f4c100a1.png)

### System information (as much as possible)

Chrome
ApricityOS - Arch based Linux 64 bits
Joomla4

**Comment by zero-24** [comment]
@NunoLopes96 did you close this for a reasone or because you fixed the problem?

**Comment by zero-24** [comment]
or accidentally?

**Comment by NunoLopes96** [comment]
Hello @zero-24 ! I found this issue with outdate files, after pulling files and updated my branch i got a bigger error:

![screenshot from 2017-03-29 21-15-15](https://cloud.githubusercontent.com/assets/20955884/24474536/d67d6174-14c4-11e7-8364-ada9217a4526.png)

This is happening because there is no banners.php in administrator/component/com_banners

I'm looking more on this issue and will report it asap

**Comment by dgt41** [comment]
You have to reinstall Joomla

**Comment by NunoLopes96** [comment]
@dgt41 I reinstalled and still have the same problem, can you check?

**Comment by C-Lodder** [comment]
@laoneo @yvesh any idea?

**Comment by joomdonation** [comment]
This issue happens because there was some changes in component dispatcher implement. Basically, with the current implement, if a component has file dispatcher.php, it must be a namespaced component

Why waiting for namespacing banner component, the easiest fix would be restore original banners.php file and remove the file administrator\components\com_banners\dispatcher.php

**Comment by joomdonation** [comment]
OK. I made PR https://github.com/joomla/joomla-cms/pull/15009 which should fix this issue for now.

**Comment by yvesh** [comment]
Thank you @joomdonation

**Comment by zero-24** [comment]
closing as we have a PR thanks @joomdonation
