### ISSUE TITLE
[Proposal] A new Joomla.Http client script

### ISSUE THREAD

**Issue by asika32764** [joomla/joomla-cms#14994]
A new idea when I'm writing https://github.com/joomla/joomla-cms/pull/14952 , it is a proposal to try creating a `Joomla.Http` object to make our frontend programming more modern.

I dont't think it is necessary for Joomla CMS now since our controller didn't handle PUT and DELETE methods, but I still note a new idea here to consider maybe some developers may need this to call 3rd party APIs.

## Interface

Use `sendRequest()` as main entry, it is similar to HttpPlug's [`HttpClient` interface](https://github.com/php-http/httplug/blob/master/src/HttpClient.php)

``` js
Joomla.Http.sendRequest('GET', url, data, headers, options);

// Or use object options

Joomla.Http.sendRequest(requestOptions);
```

Should return a `Promise` object.

``` js
Joomla.Http.sendRequest(...).then(res => console.log(res.body));
```

> For IE8, we can simply include a `promise-polyfill.js` or adapt jQuery.Deferred to Promise A/+ like [this](https://github.com/asika32764/sparrow/blob/master/src/promise/promise.js)

Simple shortcuts

``` js
Joomla.Http.get(url, headers, options).then();
Joomla.Http.post(url, data, headers, options).then();
Joomla.Http.put(url, data, headers, options).then();
Joomla.Http.delete(url, data, headers, options).then();
Joomla.Http.head(url, data, headers, options).then();
```

Support auto inject the CSRF token:

``` js
Joomla.Http.defaultOptions.headers.post['X-CSRF-Token'] = token;
```

## Extra Functions

These are not required but also list here.

Maybe support `X-HTTP-Method-Override` or `_method=PUT` query:

``` js
Joomla.Http.sendRequest({ emulateHTTP: true });
```

Or `application/x-www-form-urlencoded`

``` js
Joomla.Http.sendRequest({ emulateJSON: true });
```

> By default, Joomla.Http should send all request as `application/x-www-form-urlencoded` because it is similar to `jQuery.ajax()` and we don't need to change the backend code.

### Updated 2017-09-17

Another suggestion is that we can consider simply wrap [axios](https://github.com/mzabriskie/axios) or just include it in as js vendor since it is popular in frontend developers.

**Comment by ghost** [comment]
Opinion of @Production Department?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14994">issues.joomla.org/tracker/joomla-cms/14994</a>.</sub>

**Comment by ghost** [comment]
@mbabker any Statement?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14994">issues.joomla.org/tracker/joomla-cms/14994</a>.</sub>

**Comment by ghost** [comment]
@mbabker can Maintainer make a Decision on this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14994">issues.joomla.org/tracker/joomla-cms/14994</a>.</sub>

**Comment by ghost** [comment]
Status is set on "Needs Review".

**Comment by brianteeman** [comment]
Sorry but I am going to close this - there clearly is no interest from any o the maintainers
