### ISSUE TITLE
[com_fields] Notice in system fields plugin when deleting a Content Language

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#15004]
As title says:
If I delete a content language, I get:
[30-Mar-2017 14:18:24 UTC] PHP Notice:  Undefined property: JTableLanguage::$id in ROOT/plugins/system/fields/fields.php on line 149

@laoneo @Bakual

**Comment by laoneo** [comment]
Please check #15006.

**Comment by infograf768** [comment]
Closing as we have a patch <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15004">issues.joomla.org/tracker/joomla-cms/15004</a>.</sub>
