### ISSUE TITLE
Field in Fields Calendar type giving error in display Article TABs when typo in Default Date

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#15005]
### Steps to reproduce the issue
Create a new Field with Type 'Calendar'
Enter 'nu' instead of 'now' in the Default Date field.
Save & Close.
Go to an article and go to the 'Fields' TAB.
All the TABs will disappear.

### Expected result
Prevent that you can enter an invalid value OR show the TABs.

### Actual result
Article TABs disappearing.

### System information (as much as possible)
Nightly build Joomla 3.7

**Comment by AlexRed** [comment]
I can confirm in Joomla! 3.7.0-staging<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15005">issues.joomla.org/tracker/joomla-cms/15005</a>.</sub>

**Comment by Bakual** [comment]
Unfortunately that's not that easy as you can see in the discussion at https://github.com/joomla/joomla-cms/pull/14368.

**Comment by laoneo** [comment]
I guess I have an idea, give me a day or two. I guess it can be solved with rules.

**Comment by laoneo** [comment]
Please check #15032 which adds a default value check based on JFormRules. It should fix this issue.
