### ISSUE TITLE
[3.7] Multi.-Lang: Unable to install Chinese Simplified Lang.

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#15001]
### Steps to reproduce the issue
Warning after install Muliti-Lang.:
![bildschirmfoto 2017-03-30 um 13 09 27](https://cloud.githubusercontent.com/assets/8235763/24501953/fa180a1c-154b-11e7-97c7-b53548fd6100.JPG)
### System information
Joomla! 3.7.0-rc1
macOS Sierra, 10.12.3
Firefox 52.0.1 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by alikon** [comment]
did yuo experieneced this issue  only with "Chinese Simplified Lang" ?

**Comment by franz-wohlkoenig** [comment]
Yes, also installed english-gb, german-at and french

**Comment by Bakual** [comment]
Apparently, the chinese package is corrupt.
@infograf768 Do you know where that comes from?

**Comment by infograf768** [comment]
I found the issue.
The install.xml <name> should not contain Chinese characters in 3.7.0
<name>简体中文</name>
That was apparently not a problem before as more than 14500 downloads on joomlacode
Will upload a new pack.

**Comment by infograf768** [comment]
@Bakual
It is a weird error though. I suggest to look into it.

**Comment by Bakual** [comment]
Maybe the name is sanitised now and invalid characters get stripped, leaving nothing?

**Comment by infograf768** [comment]
@franz-wohlkoenig 
New Chinese Simplified pack is now available through install languages and I guess when installing a clean multingual site.

**Comment by franz-wohlkoenig** [comment]
New Chinese Simplified pack is now installed by "Install Languages". Will reinstall and close if works.

**Comment by franz-wohlkoenig** [comment]
Works at Installation.
