### ISSUE TITLE
Redis failed connection infinite loop

### ISSUE THREAD

**Issue by Rakeshmvd** [joomla/joomla-cms#15008]
### Steps to reproduce the issue

Activate Redis in Cache settings
add all settings

### Expected result

save config settings
Redis::pconnect(): connect() failed: Connection timed out

### Actual result

infinite loop cycle
can't save setting adjustments

**Comment by Rakeshmvd** [comment]
Even tho I have Cache settings to OFF, it is still trying to connect with Redis server. Creating an extreamly long load time or timed out.

**Comment by alikon** [comment]
please add more details, like redis version , joomla version etc.....

**Comment by franz-wohlkoenig** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened in the future if it is updated.
