### ISSUE TITLE
double backslash in configuration.php

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#15018]
Just noticed on my windows machine that the paths in configuration.php are being written with a double slash. Not sure but doesnt seem to be a problem

```
	public $log_path = 'C:\\Apache24\\htdocs\\joomla-cms-staging\\administrator/logs';
	public $tmp_path = 'C:\\Apache24\\htdocs\\joomla-cms-staging/tmp';


```

**Comment by C-Lodder** [comment]
If I remember rightly, Windows ignores double baskslashes, so shouldn't be an issue.

**Comment by brianteeman** [comment]
Yeah as I said it seems to work fine it just looks odd

**Comment by joomdonation** [comment]
I think the reason is because backslash is a special character in PHP, so to prevent it in a string, we will have to have double backslash. So there is no problem with it and actually, double backslash is needed

**Comment by mbabker** [comment]
PHP has all sorts of goofy behaviors with the backslash and it gets more goofy depending on the type of quoting wrapping the string.  `echo "\t"` will print a tab character while `echo '\t'` prints out "\t" literally.

You'll see that double backslash notation a lot in code, especially dealing with namespaced classes (i.e. https://github.com/joomla/joomla-cms/blob/staging/libraries/vendor/joomla/registry/src/Factory.php#L49-L51).  So it's perfectly fine.

**Comment by brianteeman** [comment]
thanks for clarifying and confirming
