### ISSUE TITLE
hathor - com_installer's drag'ndrop not working

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#15026]
### Steps to reproduce the issue
Select hathor admin template.
Go to Extensions->Manage->Install
Try to install any extension

### Actual result
Impossible to install any extension

### System information (as much as possible)
Last build with the shiny new Drag'nDrop feature in com_installer

### Additional comments
Tried on 2 options : 
Updated install 3.7.0-rc1
Newly installed 3.7.0-rc1

**Comment by franz-wohlkoenig** [comment]
JS-Error:
![bildschirmfoto 2017-03-31 um 14 30 34](https://cloud.githubusercontent.com/assets/8235763/24550514/ac5903a2-161e-11e7-8ed5-c729e68f8978.JPG)

**Comment by ghazal** [comment]
Good catch. 
The pb is that the new com_installer default.php (in views/install/tmpl) has not been included in Hathor's html override files in com_installer

**Comment by AlexRed** [comment]
I can confirm the problem on 3.7.0 Beta4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15026">issues.joomla.org/tracker/joomla-cms/15026</a>.</sub>

**Comment by infograf768** [comment]
Folks, many of the new features we got into 3.7.0/staging were just not pushed to Hathor:
For example, admin menus, Associations, etc.
I have asked PLT what we should do with these.

**Comment by AlexRed** [comment]
I can confirm the problems, Hathor not support the new Plugins Editor - TinyMCE setting, Fields, media manager, Advanced Permissions Report, etc.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15026">issues.joomla.org/tracker/joomla-cms/15026</a>.</sub>

**Comment by Bakual** [comment]
The problem is that Hathor needs overrides for almost each view. Which means Hathor still isn't really a J3 admin template.
We should just remove it... Nobody in their right mind is using it anyway.

**Comment by ghazal** [comment]
I would not care if Hathor was removed. 
As Bakual said ... Nobody ...
But if it remains in the distribution, it has to be dealt with.
Otherwise, get rid of it.

**Comment by brianteeman** [comment]
awaiting decision on #15079

**Comment by ghazal** [comment]
Pls read #15079: 
[RFC] Freeze Hathor backend template in the current state
