### ISSUE TITLE
Popover hidden behind modal header

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#15028]
### Steps to reproduce the issue
Edit article.
Under Publishing, click blue button to Select User.
Hover mouser over a column header.
![popover](https://cloud.githubusercontent.com/assets/368084/24555040/801e1564-15e4-11e7-86a4-650b4acaffff.jpg)

### Expected result
See entire popover.

### Actual result
Popover hidden behind modal header.

**Comment by franz-wohlkoenig** [comment]
Confirmed on 
Joomla! 3.7.0-beta4
macOS Sierra, 10.12.4
Firefox 52.0.2 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
Believe it's due to the modal content being part of an iframe. The `z-index` stacking is then lost.

**Comment by ghost** [comment]
@C-Lodder is this similar to #18469?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15028">issues.joomla.org/tracker/joomla-cms/15028</a>.</sub>

**Comment by C-Lodder** [comment]
Different issue. Other is template related

**Comment by ghost** [comment]
thanks for Info, @C-Lodder

**Comment by ghost** [comment]
closed as having Pull Request #18581
