### ISSUE TITLE
Error on installing Joomla:staging on MySQL database

### ISSUE THREAD

**Issue by euismod2336** [joomla/joomla-cms#15029]
### Steps to reproduce the issue
Use staging image as basis to install a new Joomla site. Proceed with installation as normal.

### Expected result
Successful installation of Joomla.

### Actual result
Returns to step 2 with the message: `Error: Index column size too large. The maximum column size is 767 bytes.`

### System information (as much as possible)
MySQL server 5.5-5.7 with `innodb_large_prefix` and `innodb_file_format` set to their respective default value (non-default values will result in the index keys to be silently truncated)

### Additional comments
https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix for details.

**Comment by zero-24** [comment]
@euismod2336 there is no need to open a issue if you have code to fix the issue 😄 I'm closing here. becuase of the PR #15030
