### ISSUE TITLE
Installation field password

### ISSUE THREAD

**Issue by NunoLopes96** [joomla/joomla-cms#15037]
### Steps to reproduce the issue

When trying to install joomla, if you write 1/2 or 3 characters on passwords this will appear:

![screenshot from 2017-04-01 02-25-24](https://cloud.githubusercontent.com/assets/20955884/24573917/aef29718-1682-11e7-8d0e-e922a1a21397.png)

But as we can see, it is not empty, this message only dissapears when the password is accepted ( for what I have saw the password strenght is only calculated by the number of characters it has (after 4 the password its accepted))

### Expected result

Appearing that the field it's empty when its not

No message

### Actual result

Appearing that the field it's empty when its not

### System information (as much as possible)

LeMint 64x
Chromium
Joomla4

**Comment by NunoLopes96** [comment]
I made a PR to fix this here:
https://github.com/joomla/joomla-cms/pull/15038

**Comment by brianteeman** [comment]
Closed as we have a PR
