### ISSUE TITLE
Registration form doesn't work

### ISSUE THREAD

**Issue by omilen** [joomla/joomla-cms#15039]
Registration form doesn't work on this page: https://gorizont-optika.ru/component/users?view=registration
After Register button is clicked I get message **"The most recent request was denied because it contained an invalid security token. Please refresh the page and try again."**

The same issue for Reset password page https://gorizont-optika.ru/component/users?view=reset 

Probably, the issues  appeared after updating Joomla! to 3.6.5 version. My current PHP version is 5.4.45. Selecting other PHP versions did not solve the issues.
![screen shot 2017-04-01 at 10 25 55](https://issues.joomla.org/uploads/1/4c8a74a022909714a321577beeeaaab2.jpg)![screen shot 2017-04-01 at 10 26 00](https://issues.joomla.org/uploads/1/2797362e19787e8f75de8deb53f8a23f.jpg)

**Comment by zero-24** [comment]
Please disable the output changer and try again. Maybe it is also server side cache.

I'm closing this as this looks mor like one of the reasons above. If you can confirm this with a vanila 3.6.5 you can reopen here.

If this issue is still there please ask for help in the forums: https://forum.joomla.org

Thanks.

**Comment by omilen** [comment]
Would you be so kind to explain me how to  disable the output changer (with a screenshot if it possible)?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15039">issues.joomla.org/tracker/joomla-cms/15039</a>.</sub>

**Comment by zero-24** [comment]
> Would you be so kind to explain me how to disable the output changer (with a screenshot if it possible)?

Please disable any plugin with ID < 10000 you can also try to change the template back to protostar and check if the error is gone as it can also be a broken override.

But i think the real reason could be a wrong configured cache.

But this is not something we should discuss here please open an question on https://forum.joomla.org Thanks!
