### ISSUE TITLE
[com_tags] Undefined index: tag

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#15036]
### Steps to reproduce the issue
Go to Components > Tags
Click `Check All` checkbox.
Click `Batch` button.
Click `Process` button.

In PHP error log:
> PHP Notice:  Undefined index: tag in \joomla-cms-staging\libraries\legacy\model\admin.php on line 258

**Comment by franz-wohlkoenig** [comment]
Confirmed on:
### System information
Joomla! 3.7.0-beta4 (nightly Build)
macOS Sierra, 10.12.4
Firefox 52.0.2 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by AlexRed** [comment]
I can confirm the problem on Joomla! 3.7.0-beta4 (nightly Build)
seems similar to #14995  by @laoneo

**Comment by bertmert** [comment]
Pls test PR https://github.com/joomla/joomla-cms/issues/15040
