### ISSUE TITLE
Custom fields for users seem not to be language specific

### ISSUE THREAD

**Issue by nikslor** [joomla/joomla-cms#15043]
### Steps to reproduce the issue

You need Joomla 3.7 (beta 4 in my case) and at least two languages installed/enabled.
Add a custom field to the user and assign it to one of the languages, then add a second field and assign this field to the second language.

### Expected result

If I open the the user profile page in the frontend I expect to only see the field I assigned to the current language.

### Actual result

I see both fields on my profile page.

### System information (as much as possible)

PHP 7.0.15, Joomla Version 3.7.0-beta4, Joomla Platform Version 13.1.0

### Additional comments

Let me know if I can help with more information.

Thanks for having a look at this.

**Comment by franz-wohlkoenig** [comment]
@nikslor can you please look if #14865 is same Issue?

**Comment by nikslor** [comment]
@franz-wohlkoenig jep, you're right, sorry for the noise, I'll close my issue in that case!

Thanks for you support!

All the best,
Nicolas

**Comment by franz-wohlkoenig** [comment]
thanks for Report @nikslor If you find another Issue, please report also.
