### ISSUE TITLE
[4.0] Namespace 'format' controller

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#15049]
Our legacy MVC allows creating separate controller class for each format (raw, json...) like in this class https://github.com/joomla/joomla-cms/blob/staging/components/com_users/controllers/profile.json.php

We need to decide how we want handle it in in namespace MVC for Joomla 4.. Some possible class names:

- Joomla\Component\Content\Site\Controller\Json\Profile
- Joomla\Component\Content\Site\Controller\JsonProfile
- Joomla\Component\Content\Site\Controller\ProfileJson

Once decision image, we will need to implement the change in component dispatcher to support this naming convention

**Comment by mbabker** [comment]
What is the need for separate controller classes based on the request format?  The only classes that should have an architectural need for variants based on request format should be views.

**Comment by joomdonation** [comment]
I don't really know as I haven't checked the code carefully yet. Saw it in legacy MVC and in the code of com_users as the link I posted above

**Comment by mbabker** [comment]
I know the code is doing it now, what I'm basically asking is why do we need to carry that behavior forward?  Is this a behavior we can deprecate?

**Comment by joomdonation** [comment]
To have the answer, I will have to look at the current code/ function to see whether we need it in namespace controller. As I said, I haven't looked at that part of code carefully yet. Will update here once I looked at it and understand the purpose of the current code

**Comment by joomdonation** [comment]
While you are here, could you please take a look at the other question https://github.com/joomla/joomla-cms/issues/15041 ?

**Comment by brianteeman** [comment]
@joomdonation is this still an open issue. The last comment suggests you were going to come back with an answer to @mbabker question

**Comment by joomdonation** [comment]
Sorry, I forgot to close this one. Closing it now.

**Comment by izharaazmi** [comment]
I agree with @mbabker here. Supporting this behaviour encourages people to do something like this: https://groups.google.com/d/msg/joomla-dev-cms/WsC0nA9Fixo/Ur-gPqpqh-EJ. This is also referenced in `com_ajax` as the **best way** for JSON output.

Though they can do the same with a normal controller class but at least we should not encourage this. The output should be the job of  `view`s not `controller`s.

Though I should not be commenting on a closed issue, this is what I needed to add. May be we should start a new thread?
