### ISSUE TITLE
[com_fields] values are saved without context

### ISSUE THREAD

**Issue by obuisard** [joomla/joomla-cms#15048]
### Steps to reproduce the issue
Create a custom field of type 'checkboxes' in the 'contact' context. Do not assign it to a group.
Edit a contact, check a couple values of the created custom field. Save

### Expected result
In the database table #__fields_values, the values are stored with the context column filled up

### Actual result
In the database table #__fields_values, the values are stored without the context column filled up

### System information (as much as possible)
Joomla 3.7 beta 4
PHP 5.6
MySQL 5.7.14

### Additional comments
I have tried a simple text field, added to a group or not, and the behavior is identical.

**Comment by franz-wohlkoenig** [comment]
Confirmed, but the Values are saved.

**Comment by Bakual** [comment]
The context is ŕemoved from that table. It is no longer used.

**Comment by laoneo** [comment]
This was changed with #14558 as it is redundant data. On a new install, this column will not exist anymore.

**Comment by obuisard** [comment]
Thank you!

**Comment by RobertKza** [comment]
Hi I'm trying to use Fabrik extension on the Joomla site. I would have liked to have used the Joomla custom fields as elements of the Fabrik list but don't know where to find the database table. I can get the registered joomla user fields on table  hno7r_users. Any idea ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15048">issues.joomla.org/tracker/joomla-cms/15048</a>.</sub>

**Comment by Bakual** [comment]
Don't mess with the table, use the API.

**Comment by RobertKza** [comment]
Thanks :-)
Regards

-- Robert
    Robert Bruce Kydd
    PO Box 304 | Gordons Bay | 7151 | South Africa
    Tel  +27 (0)82 826 1324 | Fax +27 (0)86 607 1596
