### ISSUE TITLE
Can't add "Install from Web" tab, 504 gateway time out.

### ISSUE THREAD

**Issue by reygoch** [joomla/joomla-cms#15053]
### Steps to reproduce the issue

Try to enable "Install from Web" tab, or visit :
https://appscdn.joomla.org/webapps/jedapps/webinstaller.xml

### Expected result

Joomla successfully enables "Install from Web" feature, or browser (if visiting url with browser) returns xml file

### Actual result

In Joomla :

```
Warning

Update: :Extension: Could not open https://appscdn.joomla.org/webapps/jedapps/webinstaller.xml
Error connecting to the server: 504
×
Error

Invalid URL
Unable to find install package
```

In chrome when visiting url :

```
504 Gateway Time-out

nginx
```

### System information (as much as possible)

Windows 10, EasyPHP dev server

Chrome web browser

### Additional comments

Seems like there is some misconfiguration on Joomla cdn server.

**Comment by zero-24** [comment]
Thanks for your report. I have just posted that to the internal channel where the sys admin can take a look into that.

**Comment by reygoch** [comment]
Why exactly is this closed? Issue still persists. I'm still getting 504 gateway time out.

**Comment by franz-wohlkoenig** [comment]
Cause @zero-24 comment. 

But no Problem to reopen.

**Comment by reygoch** [comment]
Well... @franz-wohlkoenig I like to keep the issue open until it is resolved, just in case ;D

**Comment by brianteeman** [comment]
Are you still having problems @reygoch 
If you are then it is a server issue and not a joomla software issue

**Comment by zero-24** [comment]
It is still an issue. I have been told it is a CDN issue. But maybe michael or someone from the webmasters team can tell us the current status as i have no access to that Information / tickets

**Comment by zero-24** [comment]
@reygoch are you from germany too? Or a different country?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15053">issues.joomla.org/tracker/joomla-cms/15053</a>.</sub>

**Comment by reygoch** [comment]
@zero-24 I'm from Croatia<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15053">issues.joomla.org/tracker/joomla-cms/15053</a>.</sub>

**Comment by zero-24** [comment]
Thanks for the feedback.

**Comment by zero-24** [comment]
@mbabker opend a ticket with the CDN hoster.

**Comment by rdeutz** [comment]
@reygoch can you check again, they made a change and I can now access the file

**Comment by reygoch** [comment]
@rdeutz it works!

**Comment by zero-24** [comment]
Thanks. So I'm closing here.
