### ISSUE TITLE
Bug: password is always sent via email / class Registry::get default handling

### ISSUE THREAD

**Issue by Hg347** [joomla/joomla-cms#15060]
### Steps to reproduce the issue
1) In admin backend goto System;Global config;Users
2) set `Send Password=No`

But the password is always sent!

### Expected result
The password does not appear in email.

### Actual result
The password does appears in email.

### System information (as much as possible)
Joomla! 3.6.5 Stable [
OS Linux l
PHP 7.0.7
MySQLi 5.5.5-10.0.29-MariaDB

### Additional comments
I assume the bug is in libraries/vendor/joomla/registry/src/
The way  class Registry::get() is handling default values.
If sendpassword field in DB is 0, the final check 
    `if (!$found || $node === null || $node === '')`
fails since `$node=0` and `$node === null || $node === ''` proably returns true.
In any case that final check is a problem. If the string in the database is set empty `$node === ''`
for a reason, the default value is returned, which is likely a bug too.

**Comment by AlexRed** [comment]
I can confirm the problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15060">issues.joomla.org/tracker/joomla-cms/15060</a>.</sub>

**Comment by flyingwombats** [comment]
Tested in nightly on 5 April 2017 and its now working correctly with no not sending the password and yes sending it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15060">issues.joomla.org/tracker/joomla-cms/15060</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@Hg347 @AlexRed can you confirm @flyingwombats so this Issue can be closed?

**Comment by AlexRed** [comment]
yes, now is ok. Joomla! 3.7.0-beta4 (nightly Build)

**Comment by franz-wohlkoenig** [comment]
closed as Issue is resolved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15060">issues.joomla.org/tracker/joomla-cms/15060</a>.</sub>
