### ISSUE TITLE
[com_smartsearch] Toggle selection does not toggle in accordion

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#15063]
### Steps to reproduce the issue
Go to Components > Smart Search > Search Filters
Click `New` button.
Click on an accordion.
Click `Toggle Selection` button.
Checkbox(es) within not toggled.
Also `class` attribute declared twice (see highlighted).

![smartsearch](https://cloud.githubusercontent.com/assets/368084/24590948/7ce9bf2e-17ab-11e7-91c6-942524ad6700.jpg)

**Comment by franz-wohlkoenig** [comment]
Can you give more Information about iE. Joomla-Version?

**Comment by Quy** [comment]
Latest staging version.

**Comment by franz-wohlkoenig** [comment]
@Quy after click on "New"-Button:
![bildschirmfoto 2017-04-03 um 15 37 32](https://cloud.githubusercontent.com/assets/8235763/24611800/8f8c6db0-1883-11e7-8a64-a96fc18feed3.JPG)
where to "Click on an accordion"

**Comment by Quy** [comment]
Sorry. Updated testing instructions.

**Comment by infograf768** [comment]
JS error:
"SyntaxError: unterminated string literal"

**Comment by infograf768** [comment]
@dgt41 
Dimitri, you did that code a loong time ago.
` 					<button class="btn btn-default" type="button" class="jform-rightbtn" onclick="jQuery('.filter-node').each(function () { this.click(); });"> `

Can you look?

**Comment by dgt41** [comment]
Try `jQuery('.filter-node').each(function (i, el) { el.click(); });`

**Comment by Quy** [comment]
The mention button works. The issue is with this button: 
`<button class="btn" type="button" class="jform-rightbtn" onclick="jQuery('[id="tax-4"]').each(function(){this.click();});">`

**Comment by dgt41** [comment]
This code will never work due to double quotes mess:
`onclick="jQuery('[id="tax-4"]').each(function(){this.click();});"`

**Comment by infograf768** [comment]
Yep, in fact, looks like it comes from
ROOT/components/com_finder/helpers/html/filter.php

**Comment by infograf768** [comment]
I guess I found the issue. Will make PR.

**Comment by infograf768** [comment]
Please test
https://github.com/joomla/joomla-cms/pull/15092

**Comment by infograf768** [comment]
Closed as we have a patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15063">issues.joomla.org/tracker/joomla-cms/15063</a>.</sub>
