### ISSUE TITLE
namespace

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#15072]
Maybe its just me but everytime i see something like
`\\Joomla\\Cms\\Helper\\AuthenticationHelper',`

I want to scream USE UPPERCASE
`Use all capitals if an abbreviation is pronounced as the individual letters (an initialism): HTML, CSS
`

**Comment by mbabker** [comment]
Nope, not just you.  Personal preference with namespaced code is to use uppercase for acronyms unless there's a technical reason not to.  Composer's autoloader doesn't have that reason, I sure hope JLoader doesn't too.

**Comment by brianteeman** [comment]
So can we change it then to CMS ??

Now is the time to get it right - we wont be able to change it later (I think)

**Comment by brianteeman** [comment]
If its ok to change to CMS I am happy to make the changes

**Comment by mbabker** [comment]
I'm good with it personally.  Just know you'd need to fix the casing in the filesystem too and that always gets a little tricky (luckily we aren't dealing with anything that's been released yet).

**Comment by brianteeman** [comment]
so you are or are not in favour of me spending the time to address this.

**Comment by mbabker** [comment]
I am in favor.

**Comment by brianteeman** [comment]
OK - will close this and will try to work on a PR for 3.8 branch I assume and I need to find where in the filesytem it is defined

**Comment by dgt41** [comment]
@brianteeman it's the first folder in libraries: https://github.com/joomla/joomla-cms/tree/staging/libraries

**Comment by brianteeman** [comment]
yeah - got it - just doing the rename in git

**Comment by brianteeman** [comment]
OK gave it a go see #15081

**Comment by dgt41** [comment]
how about dropping the `Cms` or `CMS` in favour of `Core`? It makes more sense to me
