### ISSUE TITLE
problem setFieldAttribute on com_users.registration Form

### ISSUE THREAD

**Issue by rolandalsace** [joomla/joomla-cms#15077]
On J 3.6.5 it's not possible to change form attribute (Jform setFieldAttribute) on com_users.registration Form (and only on this one).

You can test it on  user plugin 'profile'.

Regards.

**Comment by franz-wohlkoenig** [comment]
do you mean #14806 or is this another Issue?

**Comment by rolandalsace** [comment]
I don't realy understand the problem of #14806 issue, but it's possible.

I discover à 2nd problem wich seems linked.

Alway with con_user.registration context.

On onContentPrepareData, you cannont save data on profil form.

It's seems that the on_user.registration form data and attribute are reseted before displayed.
(Attributes are reseted to profile form description).

So after a onUserBeforeSave with false retrun, the profile form ara blank, all data ara lost even if i store it correctly in $data (2nd parameter of onContentPrepareForm).
On others contexts (com_user.user, com_user.profile,..) it's good.

But a removeField run on all contexts.

**Comment by brianteeman** [comment]
Is this still a problem? If so please provide detailed instructions how a tester can replicate this.

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 26th November 2017.

**Comment by rolandalsace** [comment]
Sorry, I do not really have the opportunity to test it right now.
Cordially.
