### ISSUE TITLE
Alternate hreflang for the current language

### ISSUE THREAD

**Issue by mediafish** [joomla/joomla-cms#15071]
### Steps to reproduce the issue
I have a [website ](http://www.mediafish.es/)available in 3 languages: Spanish (default), English & German.
If you check the source code of the Spanish version (as an example but behaviour is the same on all) [homepage](view-source:http://www.mediafish.es/) you can see the alternate hreflang for:  Spanish, English and German but:

### Expected result
I expect on the Spanish Version to show only the equivalent pages in their languages so on the Spanish version it should show:
```
	<link href="http://www.mediafish.es/de/" rel="alternate" hreflang="de" />
	<link href="http://www.mediafish.es/en/" rel="alternate" hreflang="en" />
```

### Actual result
It also shows the Spanish Version as alternate hreflang which is not correct as we are already on the Spanish version so it should only link to the alternate versions English & German...

```
	<link href="http://www.mediafish.es/de/" rel="alternate" hreflang="de" />
	<link href="http://www.mediafish.es/" rel="alternate" hreflang="es" />
	<link href="http://www.mediafish.es/en/" rel="alternate" hreflang="en" />
```

### System information (as much as possible)
Joomla 3.6.5

**Comment by SharkyKZ** [comment]
This behavior is correct as per Google guidelines:
>If you have multiple language versions of a URL, each language page should identify different language versions, including itself.  For example, if your site provides content in French, English, and Spanish, the Spanish version must include a rel="alternate" hreflang="x" link for itself in addition to links to the French and English versions. Similarly, the English and French versions must each include the same references to the French, English, and Spanish versions.
https://support.google.com/webmasters/answer/189077?hl=en

**Comment by Bakual** [comment]
Closing as expected behavior.

**Comment by mediafish** [comment]
well ok but they write:

>  ...the Spanish version must include a rel="alternate" hreflang="x" link... 

why do they use X and not es?

**Comment by Bakual** [comment]
> why do they use hreflang="x" and not hreflang="es" if they talk about the Spanish version?

It's a placeholder for the language, like back in school when you had algebra :smile: 
In the examples on the page it's clear that "x" isn't a valid value.

**Comment by mediafish** [comment]
Well ok you know that because of your experience and thanks for pointing that out :-)

...but if you start talking about algebra; at school we only used placeholders if we were talking about unknown values - but  here the value is Spain so no need for "x "but "es" ;-)
