### ISSUE TITLE
[RFC] Freeze Hathor backend template in the current state

### ISSUE THREAD

**Issue by rdeutz** [joomla/joomla-cms#15079]
# Situation today
We are shipping two backend templates with Joomla! 3.x: Isis and Hathor. While Isis is widely used and the first template we test and implement functionality Hathor is badly supported and has a lot of issues.

# Plans for the future
It is already decided to remove Hathor in Joomla 4.

# Proposal
For Joomla 3.7 we are not adding the new features we have implemented into Joomla and make available over the backend to Hathor. We will ship Hathor with the package but we not feel bound to implement any new feature into Hathor for the future.

# Effects on accessibility
Hathor was build to increase the accessibility, it served the purpose for a while but over the time Isis got better and better and technology also got better so that Hathor is not really a more accessible template. It is possible that it is not even used.  

# Summery
Make anything we have added to Joomla! also run under Hathor becomes a burden and stops innovation. Removing it would be the clearer message but we need to keep it because of B/C. Anyone who is using Hathor can do this in the future and as long as we have a 3.x but maybe he/she in not able to use all new features.

**Comment by brianteeman** [comment]
Fine by me - in some ways hathor is already less accessible than isis anyway

**Comment by dgt41** [comment]
Haha, I read that as Heathrow...

**Comment by izharaazmi** [comment]
I'm all in for this. However, it would be bad if things break while using Hathor. As far I'm aware, the Admin Menu Manager feature breaks the Menu Manager in Hathor very badly.

Not implementing further features is fine. But not taking care of what already is there would be a fake B/C. In that case removing it would be way better option.

In case we decide to keep it for now, I'd suggest fixing broken things at least. From my end I can attempt to fix Menu Manager at priority. Please let me know if I should.

**Comment by puneet0191** [comment]
I agree with the proposal.  :+1:

**Comment by laoneo** [comment]
I agree here with @izharaazmi. If we don't support all features, then it is broken and thus needs to be removed from the installation package. The sites who do upgrade will still have it installed, so no change (despite the fact that not all features do work). But it should not be there on new installs. We need to clearly communicate that in the release notes that hathor is broken for upgrades and that it will not be available from 3.7 onwards.

**Comment by alikon** [comment]
IMHO  should be removed  ....... who is still using Hathor ?

**Comment by infograf768** [comment]
Not only Admin menus, Multilingual associations have also issues.
Basically all modals have issues as they use Search Tools.

**Comment by AlexRed** [comment]
maybe we should be inserted an alert message in the control panel (like for the old PHP version or for the editor update ecc..) to display if the template Hathor is set to default.

**Comment by brianteeman** [comment]
@alexred suggestion is a good one

Something like

"We have detected that you are using the Hathor Admin template. This may not work well with some Joomla features and we recommend that you switch to use the Isis template <link>"

**Comment by infograf768** [comment]
Just did a test creating a menu item with Hathor... Then I switched to Isis and tried to create a menu item: I got a Fatal Error:

`Fatal error: Cannot use object of type stdClass as array in /administrator/components/com_menus/models/item.php on line 603`

**Comment by infograf768** [comment]
My conclusion is that I think that we have at least to solve the menu issue and indeed display the Alert proposed above.

**Comment by Gavakshi** [comment]
@izharaazmi I hope if things can be fixed then what else can be a better option.

**Comment by Bakual** [comment]
> maybe we should be inserted an alert message in the control panel (like for the old PHP version or for the editor update ecc..) to display if the template Hathor is set to default.

That would have to be a postinstall message. Please don't do messages in the cPanel itself.

**Comment by infograf768** [comment]
I have to insist that Hathor not being able to handle menus is a big issue as I posted above. Basically, if this is not corrected, we should delete hathor and redirect to Isis for ALL users.

**Comment by infograf768** [comment]
Basically, if we do not do it, this is a release blocker.

**Comment by laoneo** [comment]
I'm with @infograf768. We should not ship something which is broken and we have no intention to fix it.

**Comment by izharaazmi** [comment]
I am trying to spare some time to fix it myself, though its likely not
possible before this weekend I guess.

However, I vote for removing hathor as menu manager is not the only issue
with it, and I don't know much about others.

**Comment by mbabker** [comment]
If the 3.6.5 Hathor can work with 3.7, I'd say move it to a `joomla-extensions/hathor` repo and pull it from the distro with 3.7.  Then if it ever gets functionally updated to work with 3.7 an update can be pushed out separate from the main release schedule (decoupled extension style).  Otherwise it can sit there like the GeSHI content plugin and never get updated if there's no interest.  But in the interest of fulfilling our B/C promises, we at least have to make it look like we're making an effort unless things are really just fatally broken (that same joke about there being 3 SQL Server users probably applies to Hathor too).

**Comment by izharaazmi** [comment]
The problem is that unfortunately 3.6.5 state of Hathor too won't work with
3.7, as far as I know.

**Comment by izharaazmi** [comment]
I tried fixing Menu manager but searchtools is heavily broken in hathor.
Can't do much about that.

I am doing a PR now to remove Hathor as a separator repo. Rest is on the
teams decision to accept it or close.

**Comment by laoneo** [comment]
Fyi https://twitter.com/laoneo/status/849625687338221569, there are people using hathor so we need a proper way to migrate them.

**Comment by alex7r** [comment]
Sounds like "migrating not working feature". )
p.s. from my personal experience with Hathor only

**Comment by Bakual** [comment]
Migrating isn't hard. If Hathor isn't available anymore, they are migrated automatically to Isis (an error is shown that "the template isn't available for this view" and Isis is the fallback) :p

**Comment by N6REJ** [comment]
Is there anyone like Andy that can test accessibility anymore?  @brianteeman aren't you well versed in that?

**Comment by brianteeman** [comment]
No idea what you are aksing @N6REJ but the reality from an a11y perspective is that hathor really isnt much better (if at all) than isis

**Comment by brianteeman** [comment]
Has there been a decision made about this?

**Comment by rdeutz** [comment]
not yet

**Comment by brianteeman** [comment]
I asked because of this comment by @franz-wohlkoenig


https://github.com/joomla/joomla-cms/issues/14491#issuecomment-292472810

**Comment by rdeutz** [comment]
as I said no decision is made

**Comment by wilsonge** [comment]
There has been a decision made. Hathor will continue to ship with J3.x however we do not guarantee feature parity of all Joomla features (i.e. everything that works now should continue to work but we don't guarantee new features like fields and associations etc will continue to work fully - although we won't obviously reject any PR's if they come in)
