### ISSUE TITLE
keep media on the same path for article editing

### ISSUE THREAD

**Issue by ch2856** [joomla/joomla-cms#15088]
### Steps to reproduce the issue
Not an "issue" but an important usability feature.  When ever a user want to end images to an article body, a click on "add image" opens the root to the media directory (images/ or images/stories) so if I want to add 10 images to an article, I need to, again and again, navigate from the root folder to the folder where I uploaded the image (to keep things organized) so for for example, I need to navigate again and again to images/stories/audi/a3/2017/a3-2017..... long process to update an article. 

### Expected result

As long as the user editing the article, the media popup will be open at the same place where the user last visited. So in my example, if I edit article X and my images for this article are at images/A/B/C I will always be back to the same folder as along as I edit this article. 

### System information (as much as possible)
3.6.5

**Comment by franz-wohlkoenig** [comment]
@dgt41 can you please have a look (we talked about)

**Comment by dgt41** [comment]
@ch2856 you can use: https://github.com/dgt41/imageUploaderHelper and have the custom structure  that you need.

**Comment by dgt41** [comment]
@ch2856 discard my last comment, I misunderstood your issue. We can easily implement that. If no PR the coming days ping me back

**Comment by brianteeman** [comment]
@dgt41 pinging you back as requested

**Comment by brianteeman** [comment]
@dgt41 pinging you again as requested

**Comment by dgrammatiko** [comment]
@brianteeman this is already implemented in J4, in J3 is a bit more difficult to do, I;ll have a look at it this weekend

**Comment by dgrammatiko** [comment]
I was about to do a PR today, the code is quite simple, but I figure out when testing it that there might be a very serious implication since the field could have a predefined path:

```html
directory (mandatory) is the directory from which the user will be able to choose a file. This attribute should be relative to the top level /images/ folder.
```

So the question is in case such an option is defined what should be the expected behaviour:
- keep the original folder (disregard any user selection)
- override the path and set the one in session storage
- check if the session stored path is deeper level from the predefined path and either use it or disregard it

**Comment by ghost** [comment]
Status is set on "Needs Review".

**Comment by coolcat-creations** [comment]
Tested in Joomla 4 and it works there

**Comment by laoneo** [comment]
I would close this issue as we fixed it in J4 and in J3 we will never do it anyway as it needs a bigger change.

**Comment by dgrammatiko** [comment]
This should be closed as the Media Manager keeps the last opened directory
