### ISSUE TITLE
Feature request: Remove the "Forgot your password?" link via GUI

### ISSUE THREAD

**Issue by BastianWie** [joomla/joomla-cms#15089]
### Actual result
If you are using Joomla with an LDAP implementation you do not need the "Forgot your password" or "forgot your username". However its not possible to disable these features without doing a "hack" which might cause security issues as the modules aren´t then updated. There seamed to be huge need as you can find multiple handouts in the internet how to do that with an "hack".

### Expected result
The expected result would be if we can disable these features either in:

- Users: Options
- Login Module
- Link to the Login Module

**Comment by brianteeman** [comment]
You don't need a hack. Just do a regular override in your template

**Comment by zero-24** [comment]
you can take a look here:
https://www.j-over.de/en/overrides/mod_login/login-module-without-links.html
https://www.j-over.de/en/overrides/com_users/login-component-without-links.html

Where i have documented the needed things about the overrides. (wich is not a hack ;))

**Comment by BastianWie** [comment]
Maybe I wasn´t clear here. I´m not searching for a way to hide the visible appearance from the links. I´m searching for a way to BLOCK this feature so that a bot isn´t able to put in random email addresses or usernames. Removing the visual appearance from the links will not help here :). The issue is that on some of my joomla installations the users got a VERY large amount of "do you wish to reset your password" emails due to the reason that some spam bots try multiple email address combinations into the fields.

The only way to stop that is to remove this feature :)

**Comment by brianteeman** [comment]
I am closing this as the main issue reported  being
> on some of my joomla installations the users got a VERY large amount of "do you wish to reset your password" emails due to the reason that some spam bots try multiple email address combinations into the fields.
and as stated there is nothing in the joomla core that will do this
