### ISSUE TITLE
[3.7] com_search: Unknown column 'fv.context' in 'where clause'

### ISSUE THREAD

**Issue by jsubri** [joomla/joomla-cms#15080]
### Steps to reproduce the issue
staging or 3.7b4
http://localhost/staging-3.7/index.php/search?searchword=fruit&ordering=newest&searchphrase=all

### Expected result
search to return results without error

### Actual result
Unknown column 'fv.context' in 'where clause'

### System information (as much as possible)
context is from the #__fields table and not from #__fields_values
https://github.com/joomla/joomla-cms/blob/staging/plugins/search/content/content.php

**Comment by Bakual** [comment]
Please test https://github.com/joomla/joomla-cms/pull/15086

I'm closing this issue since we have a PR.
