### ISSUE TITLE
Custom field layout

### ISSUE THREAD

**Issue by maz001** [joomla/joomla-cms#15084]
At the moment in joomla you can add anything to an item page - Text, images and even modules using the LOADPOSITION plugin, and arrange the layout of the page as you like. Thats the beauty of joomla!

From an example I have seen, the new joomla 3.7 custom fields are  'automatically' placed at the top (or bottom) of a standard joomla item page. This is very limiting.

I am creating a site with hundreds of categories and documents. Each will have its own set (groups) of custom fields. Because I have different categories, I need the item pages to look slightly different in each. So, I need to create pages with different layouts (AGAIN...NOTHING TO DO WITH ANY PARTICULAR TEMPLATE, individual page layouts are already possible using the text editor in joomla backend). So i need to add different groups of custom fields at different positions on the page. Some custom fields just after a piece of text, some just after the image, some in between text and so on. If there was a plugin similar to LOADPOSITION, or a snippet of code as in K2, this could be done.

If you use K2 and create pages you can associate custom fields there too. PLUS for every single page, you can associate custom fields precisely and place them anywhere on a page. There is a bit of code where you add the custom field id and that custom field then appears at that position.

For standard joomla voting stars I guess its fine having them at the top. BUT, if you have 8 or 9 custom fields associated with an item page, it kind of looks silly all these appearing randomly at the top of the page.

Perhaps I am being a little impatient and joomla 3.7 actually does all this. Its just I am planning my site pre-joomla 3.7 and panicking a little in that I may be wasting my time. I am sure the super guys have already thought of this and there is a simple solution? Would be ideal if custom fields could be placed on a page using either a custom field ID or alias. Is this possible?

**Comment by franz-wohlkoenig** [comment]
At the Moment you can set Display:
![bildschirmfoto 2017-04-04 um 07 54 33](https://cloud.githubusercontent.com/assets/8235763/24643110/fa68c1aa-190b-11e7-97bf-2fb8c7cd9034.JPG)
and also (like loadposition) Fields in Content (don't know syntax now).

**Comment by maz001** [comment]
Its the syntax for 'Fields In Content' which I think is vital to have full control over layout. Does anyone know this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15084">issues.joomla.org/tracker/joomla-cms/15084</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
there's also a Button #13875

**Comment by franz-wohlkoenig** [comment]
there you find: {fieldgroup 17823} {field 123312}

**Comment by maz001** [comment]
Thank you so much!!! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15084">issues.joomla.org/tracker/joomla-cms/15084</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
if this is solved, please close Issue.
