### ISSUE TITLE
appscdn.joomla.org Down

### ISSUE THREAD

**Issue by tschechniker** [joomla/joomla-cms#15096]
Hi,

the appscdn.joomla.org is broken.

Example: https://appscdn.joomla.org/webapps/jedapps/webinstaller.xml --> HTTP 504

**Comment by mbabker** [comment]
Fine here (Minnesota, USA).  Probably a CDN related issue.  What's the location where you're experiencing issues?

**Comment by zero-24** [comment]
Yes. This is a know CDN Problem maybe @mbabker can give us a status here?

**Comment by zero-24** [comment]
From Germany i can confirm it too ;)

**Comment by mbabker** [comment]
I don't have a status because we generally don't open tickets with hosting for a single reported outage from a single user.  So if there is a CDN issue, we need confirmation from more than one or two individuals, preferably in different geographic regions so we can determine if it is indeed CDN or something else.

**Comment by zero-24** [comment]
Same issue is also reported here: https://github.com/joomla/joomla-cms/issues/15053

**Comment by mbabker** [comment]
So far that makes 3 individuals, only one of whom we have any kind of location info from.  Not enough info to submit an adequate ticket yet, unless you like the kinds of tickets that say "hey, some people can't get to this site, we don't know why, but fix it" 😉 

Not trying to write this off as not an issue, but right now we don't have adequate reports/information to process this any further.

**Comment by tschechniker** [comment]
I'm also from Germany

**Comment by mbabker** [comment]
Ticket in.

**Comment by zero-24** [comment]
As there is a ticket I'm goint to close here and we update the first issue #15053 with all new infos please.

Thanks!
