### ISSUE TITLE
[3.7] Beta 4 - Fresh Install Menu hides sub items

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#15094]
It's a slight UX issue, if the user does a fresh install the pre-setup menu block is set to hide sub menu items. Which can cause confusion when they create sub menu items as to why they are not being displayed. 

We should set this to show sub menu items by default as we do if we create a new menu module.

**Comment by franz-wohlkoenig** [comment]
Confirmed.

**Comment by infograf768** [comment]
Patch is easy to do.

Remains to decide if we do it for all sample data or only for the basic joomla.sql

@rdeutz @mbabker 

What do you think?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15094">issues.joomla.org/tracker/joomla-cms/15094</a>.</sub>

**Comment by rdeutz** [comment]
We are talking about the frontend menu modules, right?

**Comment by franz-wohlkoenig** [comment]
Yes, Frontend-Modules

**Comment by rdeutz** [comment]
So then we should use the default value, where ever it makes sense.

**Comment by infograf768** [comment]
OK, will do patch for ALL frontend menu modules in all sql<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15094">issues.joomla.org/tracker/joomla-cms/15094</a>.</sub>

**Comment by infograf768** [comment]
Please test
https://github.com/joomla/joomla-cms/pull/15099
