### ISSUE TITLE
[3.7] Additional fields

### ISSUE THREAD

**Issue by Anmast** [joomla/joomla-cms#15098]
Делаю проект на Joomla 3.7.0-beta4. Использую огромное количество доп полей. Понимаю что это beta и заметил недоработку. Дело в том что если создавать поля с одинаковыми именами в разных группах полей. То при записи данных в одно из полей, они будут перезаписанными из поля созданного в первую очередь. Это из за того что алиасы сохраняются одинаковые. А по идее должно проверять и не давать сохранить если такой alias присутствует в БД. 
Так же не удобно то что все типы полей идут в один список.
Хорошо бы записывать разные типы полей в разные блоки и так же разные группы полей записывались в разные блоки и при создании группы полей необходимо сделать возможным добавлять классы блоку. 
Это будет полезно например для создания табов.

**Comment by zero-24** [comment]
@Anmast please just write in englisch here.

I have just used GT to translate it:

```
I'm doing the project on Joomla 3.7.0-beta4. I use a huge number of additional fields. I understand that this beta and noticed the flaw. The fact is that if you create fields with the same name in different groups of fields. When you write data to one of the fields, they will be overwritten from the field created first. This is because the aliases are kept the same. And on idea should check and not give to save if such alias is present in a DB.
It is also not convenient that all types of fields go to the same list.
It would be nice to write different types of fields in different blocks and also different groups of fields were written to different blocks and when creating a group of fields it is necessary to make it possible to add classes to the block.
This will be useful for example to create tabs.

```

**Comment by zero-24** [comment]
And for the record you can do this using field Groups.

Did you try that?

**Comment by Anmast** [comment]
Не понял Ваш вопрос. К сожалению я плохо знаю английский. Извините(

**Comment by zero-24** [comment]
И для записи вы можете сделать это, используя Группы полей.

Вы пробовали это?

Вы можете использовать Google Translate для перевода английского языка на русский

https://translate.google.com

**Comment by Anmast** [comment]
Вот что у меня получилось при создании полей.
это не реклама, извините за ссылку. 
http://barysh-jkh.ru/r-p-starotimoshkino/18-obl-ulyanovskaya-r-n-baryshskij-rp-starotimoshkino-ul-mikrorajon-d-19.
У меня созданы группы полей. Но всё идёт в один список. Они не разделены по блокам. Для того, чтобы мне их распределить по табам  я использовал jQuery.

Ещё при создании полей в разных группах полей с одинаковым названием, алиасы записывались одинаковые. Это неправильно. Из-за этого на сайте не выводилось второе поле из другой группы. 
Вот несколько скриншотов - примеров. Вы поймёте. Спасибо! 
1. http://prntscr.com/esi3mx
2. http://prntscr.com/esi429
3. http://prntscr.com/esi4d1
4. http://prntscr.com/esi5au
5. http://prntscr.com/esi6tc
6. http://prntscr.com/esi6zk
7. http://prntscr.com/esi7rx

Извините за множество ссылок.

**Comment by zero-24** [comment]
Спасибо, у меня проблема сейчас. Но в основном это должно быть то, что вы можете сделать с помощью переопределений

Thanks i got the problem now. But basically this should be something you can do via overrides

### for the not russian

The Problem is that the field grups are rended in the backend and frontend but in the normal article there is not distiction in which field group the field is.
I personaly think this should be done using overrides any other opionions? Maybe @laoneo

**Comment by ysrostov** [comment]
OK, here is the **steps to reproduce the issue:**
Я воссоздал сценарий на примере двух групп и двух полей

1. Create custom field group with title Group1
2. Create custom field group with title Group2
3. Create text custom filed titled "Field" and assign it to Group1
4. Create text custom field titled also "Field" and assign it to Group2
5. Go to any article and put in the values for the fields, for exsmple "This is field in group1" and "This is field in group2"
6. Hit Save button

**Expected resalt**
too diferent values in two different groups' fields

**Actual result**
The value from the field in group2 overwrites the value in the field in group1 - you can't got them showing two different values

**Comment by Bakual** [comment]
For the issue with duplicate name/alias, see (and test) https://github.com/joomla/joomla-cms/pull/14554.

I'm closing here as we have a PR.

**Comment by ysrostov** [comment]
I've tested the update - the issue seems resolved, now the checking for duplicate alisses is implemented and works fine.
Я протестировал обновление - проблема, похоже, решена, теперь проверка дублирующихся алиасов выполняется.
