### ISSUE TITLE
[3.7] Isis: `Collapse Administrator Menu` on `No` messed Menu

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#15093]
### Steps to reproduce the issue
Set Isis-Style, Tab "Advanced" Field `Collapse Administrator Menu` on `No`:

set Field `Collapse Administrator Menu` on `Yes`:

**Comment by brianteeman** [comment]
Confirmed - although to be perfectly honest I never saw that point of that option anyway ;)

**Comment by franz-wohlkoenig** [comment]
me too - was testing another Issue.

**Comment by franz-wohlkoenig** [comment]
closing this Issue as i can't remeber or reproduce.

**Comment by brianteeman** [comment]
I can still replicate it.

Go to the ISIS template options and set Collapse Administrator Menu to No and save

Now look at the drop down for the menu and you will see that SITE is misaligned

<img width="433" alt="screenshotr15-22-05" src="https://cloud.githubusercontent.com/assets/1296369/25091539/a6ae3f10-2381-11e7-8223-9c6ee1b0e339.png">

**Comment by franz-wohlkoenig** [comment]
thanks @brianteeman

**Comment by brianteeman** [comment]
Closed as we have a PR #19140
