### ISSUE TITLE
Smart search - Suggestion function - reduce only to some desired elements

### ISSUE THREAD

**Issue by alan8585** [joomla/joomla-cms#15100]
### Steps to reproduce the issue

Smart Search module has a Suggest function. 
For example if I have the following statement in an article: "This is a test article."

When I start typing "test" in the search module, it starts to suggest other items that are not in my article. For example: test 1, test 2 or other.

### Expected result
In above example. Only "test".

I would like to be able to select what suggestions will be displayed to users.

### Actual result
test 1, test 2 

### System information (as much as possible)

Joomla! 3.6.2	
Smart Search 

### Additional comments
Just to give you more details, I want to be able to edit the suggestions list because I would like to associate a suggestion only to a specific article. As a second step, when a client will select the respective suggestion, he/she will be redirected directly to the article and not to the search result page.

**Comment by brianteeman** [comment]
Sorry but thats not going to be possible, If the search term exists somewhere and has been indexed then it will be suggested. Think of it like google making suggestions to you. you cant control those suggestions. Much as google would like to and thus avoid embarrassing suggestions

Also please update your installation of Joomla immediately

**Comment by alan8585** [comment]
Thanks brianteeman for swift reply

**Comment by franz-wohlkoenig** [comment]
closed as Expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15100">issues.joomla.org/tracker/joomla-cms/15100</a>.</sub>
