### ISSUE TITLE
Metadata priority changed?

### ISSUE THREAD

**Issue by alex7r** [joomla/joomla-cms#15102]
### Steps to reproduce the issue
I really do not know if that's really the case, so I'm looking for some to verify.
But as far as I remember at 3.3 (may be even 3.4-5) and prior the metadata priority was always different from what it is now.

### Expected result
Menu item meta-params are used in priority to article meta-params (like description)

### Actual result
Article meta-params are used in priority to menu item meta-params (like description)

### System information (as much as possible)
Joomla 3.6.5

**Comment by brianteeman** [comment]
Closing as there has been no response
