### ISSUE TITLE
No message on install with drag and drop

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#15119]
When you install an extension using the browser and upload you get a success message - see screenshot below

When you install using drag and drop you get no feedback that the extension has been installed

<img width="804" alt="screenshotr22-55-43" src="https://cloud.githubusercontent.com/assets/1296369/24728721/06bce3c6-1a53-11e7-9bd0-a600114442b3.png">

**Comment by AlexRed** [comment]
I can confirm the problem on Joomla! 3.7.0-beta4 (nightly Build)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15119">issues.joomla.org/tracker/joomla-cms/15119</a>.</sub>

**Comment by ghazal** [comment]
Problem confirmed.
I do admit that it is a bit unsettling.

**Comment by infograf768** [comment]
It also could be the same issue for eventual errors as these are in the install.php code


@asika32764 
could you please look into this?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15119">issues.joomla.org/tracker/joomla-cms/15119</a>.</sub>

**Comment by asika32764** [comment]
I guess it is the message session issue since new drag n drop installation use ajax instead form submit.

I will take a look to the code later.

**Comment by asika32764** [comment]
Fixed in https://github.com/joomla/joomla-cms/pull/15135

**Comment by brianteeman** [comment]
Closed as we have a PR
