### ISSUE TITLE
Remove .row0 and .row1

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#15114]
If/when Hathor is removed, `.row0` and `.row1` can be removed because of `.table-striped`.

To be removed: `class="row<?php echo $i % 2; ?>"`

**Comment by brianteeman** [comment]
Even if it is removed from core we shouldn't do stuff to prevent people using it today from using it in the futurem

**Comment by mbabker** [comment]
We can drop that convention in 4.0.  But for 3.x it'd need to stay as removing the class could potentially alter the appearance of someone's site using those classes.

**Comment by brianteeman** [comment]
Closed as stated above

**Comment by barsan-md** [comment]
Shuldn't this be discussed prior to releasing 4.0? It is still used extensively in every component.

**Comment by brianteeman** [comment]
which is why it was closed and not implemented

**Comment by barsan-md** [comment]
I don't understand if it is a yes or a no answer, with yes meaning it is better to drop that class and no meaning we will leave things as they are now.

**Comment by brianteeman** [comment]
The initial comment was to remove them
That was rejected and the issue was closed
Therefore they are still there and used
