### ISSUE TITLE
[3.7] TinyMCE - unable to configure the simplest setup

### ISSUE THREAD

**Issue by ysrostov** [joomla/joomla-cms#15112]
I apologise in advance if I'm missing something here, but I'm stuck in attempts  to configure tinyMCE for frontend editing with simple buttons setup without result.

### Steps to reproduce the issue
(Fresh installation)
1.In Options for Users choose "Allow User Registration - Yes" and "New User Registration Group - Author"
2. Go to Plugins -> TinyMCE and configure it so the Simple set №2 with minimum number of buttons is assigned to "Author" group (see the screenshot attached). I've also removed for clarity of experiment "Registered" group from any sets (0,1,2)   -  http://take.ms/CTmVw
3. Register, activate a new user via frontend and try to create a new article in frontend with a default editor - TinyMCE

### Expected result
Minimum number of buttons in UI of the editor as the setting implies

### Actual result
Chosen setup plus other buttons - Module, Menu, Contact, Article, Image
An ordinary "Author" by default has access to a good number of internal site elements to see and even insert into his/her post which is wrong imo. Besides I couldn't figure out how to disable these buttons and appreciate it if you let me know.
http://take.ms/EWSvAI

**Comment by dgt41** [comment]
@ysrostov those buttons are not controlled by tinyMCE, you can disable the relative plugins in the  plugin manager

**Comment by ysrostov** [comment]
@dgt41  thanks a lot! I should've guessed. So we only can turn them website-wide back&front ON or OFF...   Not much of a choice)

**Comment by Bakual** [comment]
@ysrostov You can use the view levels to specifiy which editor buttons show for each usergroup.

**Comment by ysrostov** [comment]
Thank you @Bakual , sorry am not good at solving this quest)) I see now how I can turn them on only for a super user. 
As far as the issue is concerned I would still consider to switch showing of some these buttons by default OFF for a any other ACL group but Super User...  Module, Menu, Contact buttons for sure

**Comment by Bakual** [comment]
That depends a lot on the use case.

**Comment by brianteeman** [comment]
Closed as answered
