### ISSUE TITLE
[com_menus] Undefined index: assetgroup_id & Undefined index: language_id

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#15123]
### Steps to reproduce the issue
Create an Administrator menu.
Create a menu item under this Administrator menu.
Click `Save & Copy` button.
Click `Check All` button.
Click `Batch` button.
Click this menu item under `- Don't copy or move-` dropdown.
Click the `Move` radio button.
Click `Process` button.

In the PHP error log:
```
Undefined index: assetgroup_id in \joomla-cms-staging\libraries\legacy\model\admin.php on line 258
Undefined index: language_id in \joomla-cms-staging\libraries\legacy\model\admin.php on line 258
```
### Additional comments
Latest staging version

**Comment by franz-wohlkoenig** [comment]
closed cause PR #15132 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15123">issues.joomla.org/tracker/joomla-cms/15123</a>.</sub>

**Comment by bertmert** [comment]
@Quy 
Could you please split your issue https://github.com/joomla/joomla-cms/issues/15123
to make clear that it contains 2 different issues (see comment https://github.com/joomla/joomla-cms/pull/15132#issuecomment-292251478) .

@franz-wohlkoenig 
https://github.com/joomla/joomla-cms/pull/15132 just solves the second part of this issue. Could you please re-open here.

Thank you!

**Comment by Quy** [comment]
Separated the 2nd issue into its own.
