### ISSUE TITLE
[3.7] Joomla Update: 1054 Unknown column 'hathor' in 'where clause'

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#15124]
### Steps to reproduce the issue
After Update on nightly Builds:
![bildschirmfoto 2017-04-06 um 07 11 15](https://cloud.githubusercontent.com/assets/8235763/24738801/79c8778c-1a98-11e7-8ea5-583614dc7efd.JPG)
### System information
Joomla! 3.7.0-beta4 (nightly Build)
macOS Sierra, 10.12.4
Firefox 52 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by zero-24** [comment]
See the comments by Brian here: https://github.com/joomla/joomla-cms/commit/4e825aadb6e5811c2f11c8d9366e6b59f8878e1b

**Comment by franz-wohlkoenig** [comment]
closed as known Issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15124">issues.joomla.org/tracker/joomla-cms/15124</a>.</sub>

**Comment by zero-24** [comment]
This needs fixing. Please let that open until it is fixed by @rdeutz ;)

**Comment by franz-wohlkoenig** [comment]
reopened for fixing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15124">issues.joomla.org/tracker/joomla-cms/15124</a>.</sub>

**Comment by infograf768** [comment]
This has been solved. Can be closed.
See https://github.com/joomla/joomla-cms/commit/5fde9a8b17d95f2cb25e085cb0585ad00c71a1c1

**Comment by infograf768** [comment]
Closed as solved in codebase<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15124">issues.joomla.org/tracker/joomla-cms/15124</a>.</sub>
