### ISSUE TITLE
"Use Global" in Menu Options should be changed to "Inherit"

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-cms#15127]
### Steps to reproduce the issue
So, we know that the priority order for Articles is "Menu Options > Article Options > Global Options".

You can try with any Article Setting. Let's use "Show Category" as an example.

LEVEL 1 - Global Options: SHOW
LEVEL 2 - Article Options: HIDE
LEVEL 3 - Menu Options: USE GLOBAL

### Actual result in the Menu Item

The result is that the Category is SHOWN (takes the setting from LEVEL 1)

### Expected result in the Menu Item

I would expect the Category to be HIDDEN (should take the setting from LEVEL 2)

### System information (as much as possible)

Joomla 3.6.5

### Additional comments

It doesn't make sense for the "Use Global" setting in Menu Options to simply skip and ignore the "parent" Article Options and just go ahead and use the "grandparent" Global Options. 

I understand that for Category Blog Menu Items there is an option called "Use Article Options", but I think it's redundant and unnecessary. Infact, I think this option should be removed, and instead, using the article options should be the expected behavior when selecting "Use Global". 

Here's another reason why I think that:

The fact that "Use Global" skips the Article Options and goes straight to the Global Options is also incosistent with how the permission levels work for example. Their "equivalent" of "Use Global" (which is "Inherit") inherit the setting from the closest parent option, it doesn't skip them all and use the main grandparent settings.

So I believe this behavior should be the same. The "Use Global" in Menu Options should be treated (or even renamed, for consistency?) in "Inherit" and should inherit the setting from the closest parent.

This example relates to Article Options but it could apply to other components that have a similar hierarchy.

These are my 2 cents. Feel free to rip it to shreds if you feel like it, lol. I think it should at least be considered/discussed.

**Comment by Bakual** [comment]
> So, we know that the priority order for Articles is "Menu Options > Article Options > Global Options".

Just to be precise, this depends on what the menu item type is.
If the active menu item is an "Single Article" pointing to that exact article, then it is as you wrote, Menu takes precedence over article.
If the menu item is something different (eg "Single Article" but for another article or a category view), then it is "Article Options > Menu Options" > Global Options". Article settings take precedence over menu settings.

**Comment by AndySDH** [comment]
Oh, well, in that case, this causes way less issues than I thought. So from problematics standpoint, we're good. For consistency, however, I guess it could improved anyway?
What is the purpose of "Use Article Options" if, as you way:
[quote]If the menu item is something different (eg "Single Article" but for another article or a category view), then it is "Article Options > Menu Options" > Global Options". Article settings take precedence over menu settings.[/quote]
Doesn't that make "Use Article Options" effectively redundant, since they take precedence anyway?

**Comment by Bakual** [comment]
Honestly, I don't know that. You would have to ask the one who implemented it :smile:

**Comment by brianteeman** [comment]
Closed due to lack of interest

**Comment by AndySDH** [comment]
Well, I guess you can say there was lack of interest, in the sense that it's not a big deal in the grand scheme of things and I won't kill myself if it doesn't get added - it's a small tweak, but if all small tweaks were ruled out for "lack of interest" then Joomla wouldn't be as comprehensive as it is, right? #LittleThingsMatter

**Comment by brianteeman** [comment]
It reallys inst a small thing though as it will effect all existing sites

**Comment by AndySDH** [comment]
I see, that's a good point too, well, let's leave it then :)
