### ISSUE TITLE
[4.0] Session cookie does not get updated

### ISSUE THREAD

**Issue by dneukirchen** [joomla/joomla-cms#15131]
### Steps to reproduce the issue

Go to homepage
Open dev tools
Go to "Application" tab
Select domain cookies
See expires_at/max-age of the session cookie
Refresh the page

### Expected result

The max-age of the cookie should get updated on every request.

### Actual result

The cookie does not get updated. If the user was logged in, he gets logged out after expiration.

### System information (as much as possible)

Branch 4.0-dev

**Comment by ghost** [comment]
@mbabker should this be applied to a [Project](https://github.com/joomla/joomla-cms/projects)?

**Comment by ghost** [comment]
@dneukirchen can't get Behaviour:

- set "Session Lifetime" on 1 minute, logout  and -in in Backend
- login in Frontend, wait 2 Minutes
- reload Frontend: User is logged in as before.
