### ISSUE TITLE
[com_menus] Hide options until an Administrator menu/parent item is selected in Batch mode

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#15133]
### Steps to reproduce the issue
Create an Administrator menu.
Create a menu item under this Administrator menu.
Click this menu item.
Click `Batch` button.

### Expected result
Copy/Move radios to display only after a menu/parent item is selected.

### Actual result
![batchmenu](https://cloud.githubusercontent.com/assets/368084/24759500/845c17e2-1a9a-11e7-95af-26cc18793cd7.jpg)

**Comment by brianteeman** [comment]
Confirmed. It should be the same as for site menu items

**Comment by bertmert** [comment]
The relevant JS is part of JLayout `/joomla/html/batch/language.php` that is not included in batch modals for  Administrator menu items.
https://github.com/joomla/joomla-cms/blob/3.7.0-rc1/layouts/joomla/html/batch/language.php#L18-L36

I don't know where to move this script block. In a custom JLayout? A JHtml methode? ...?

**Comment by Quy** [comment]
This dropdown works on the Site menus, but not on the Administrator menus.

**Comment by bertmert** [comment]
> This dropdown works on the Site menus, but not on the Administrator menus.
Yes, because Site menus have a language field but Administrator menus not.
The JS is loaded with the language field. Why ever.

**Comment by brianteeman** [comment]
@Quy This looks to have been fixed elsewhere - can you confirm that this is no longer an issue?

**Comment by Quy** [comment]
It is still reproducible.

**Comment by brianteeman** [comment]
Sorry I was misunderstanding the issue

**Comment by ghost** [comment]
closed as having Pull Request #18216<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15133">issues.joomla.org/tracker/joomla-cms/15133</a>.</sub>
