### ISSUE TITLE
[com_menus] Hide Process button when in Trashed status (Admin menu)

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#15134]
### Steps to reproduce the issue
Create an Administrator menu.
Create a menu item in this Administrator menu.
Trash this menu item.
Click `Search Tools` button.
Select `Trashed` in `- Select Status -` dropdown.
Select the Administrator menu in `- Select Menu -` dropdown.
Click `Select All` checkbox.
Click `Batch` button.

### Expected result
Cancel button only.

### Actual result
![hide-process-button](https://cloud.githubusercontent.com/assets/368084/24762083/24eafaaa-1aa2-11e7-8bc4-188e20869f02.jpg)

**Comment by brianteeman** [comment]
Confirmed - it is cancel only when on site menus so should be cancel only when on admin menus.

**Comment by brianteeman** [comment]
@quy I assume it is this check here that just needs to remove the clientid
https://github.com/joomla/joomla-cms/blob/d3b7151989ba4cce0d64d7a8de8ea5a5625e86ba/administrator/components/com_menus/views/items/tmpl/default_batch_body.php#L61

**Comment by ghost** [comment]
closed as having Pll Request #18195<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15134">issues.joomla.org/tracker/joomla-cms/15134</a>.</sub>
