### ISSUE TITLE
Unknown column 'a.name' in 'field list'

### ISSUE THREAD

**Issue by mihailnovak** [joomla/joomla-cms#15142]
### Steps to reproduce the issue
After update Joomla 3.7.0 beta4 to Joomla! 3.7.0-rc1

### Expected result
Unknown column 'a.name' in 'field list'

**Comment by mbabker** [comment]
Known issue with how database upgrades are managed for non-stable releases, see https://github.com/joomla/joomla-cms/issues/13661

In your `#__fields` table, rename the alias column to name and you'll be good.

**Comment by mihailnovak** [comment]
No access to custом fields in administration.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15142">issues.joomla.org/tracker/joomla-cms/15142</a>.</sub>

**Comment by mbabker** [comment]
You have to do it in the database.

**Comment by mihailnovak** [comment]
Thank you mbabker!!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15142">issues.joomla.org/tracker/joomla-cms/15142</a>.</sub>

**Comment by ghazal** [comment]
For reasons linked to my DB settings, I had to remove my fields table and re-insert it with:
SET sql_mode = '';

```
SET sql_mode = '';
CREATE TABLE `xxxx_fields` (
  `id` int(10) UNSIGNED NOT NULL,
  `asset_id` int(10) NOT NULL DEFAULT '0',
  `context` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `group_id` int(10) NOT NULL DEFAULT '0',
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',

...... etc ....
```
to rename "alias" to "name".

**Comment by ymages** [comment]
ALTER TABLE `prefix_fields` CHANGE `alias` `name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '';
