### ISSUE TITLE
Child categories not published back

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#15148]
### Steps to reproduce the issue
Create a parent - child categories tree
Unpublish the top level category -> all categories get unpublished as expected

Now publish back the top level category

### Expected result
All child categories get published as in the current 3.6.5

### Actual result
Only the top level category is published back, but all subcategories still stays unpublished

### System information (as much as possible)
Joomla 3.7 RC1

**Comment by brianteeman** [comment]
I might be wrong but I think this was a deliberate change to address the following scenario

Parent menu with 10 children menu of which 5 are unpublished

**Comment by mbabker** [comment]
The way it is now is the correct behavior.  A child cannot be published when its parent is unpublished, but it can be unpublished when the parent is published.  Without tracking states in a history like manner, there isn't a way to put things back if you were to republish an item for exactly the scenario Brian pointed out above, doing so may publish items that were deliberately unpublished.

**Comment by joeforjoomla** [comment]
Perfect, closing thus this is expected behaviour
