### ISSUE TITLE
[com_banners] Undefined variable: canDo & Call to a member function get() on null in Hathor

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#15147]
### Steps to reproduce the issue
Install demo.
Go to Components > Banners > Clients.
Edit a client.

![banner-clients](https://cloud.githubusercontent.com/assets/368084/24785571/fd4ffaae-1b0f-11e7-9325-b000dd04b6a6.jpg)

```
PHP Notice:  Undefined variable: canDo in C:\xampp\htdocs\joomla-cms-staging\administrator\templates\hathor\html\com_banners\client\edit.php on line 42

PHP Fatal error:  Call to a member function get() on null in C:\xampp\htdocs\joomla-cms-staging\administrator\templates\hathor\html\com_banners\client\edit.php on line 42
```

**Comment by AlexRed** [comment]
I can confirm the problem on Joomla! 3.7.0-rc1 (nightly Build)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15147">issues.joomla.org/tracker/joomla-cms/15147</a>.</sub>

**Comment by joomdonation** [comment]
Change this line https://github.com/joomla/joomla-cms/blob/staging/administrator/templates/hathor/html/com_banners/client/edit.php#L42 of code to the code below should solve the issue

```php
<?php if ($this->canDo->get('core.edit.state')) : ?>
```

**Comment by Quy** [comment]
PR #15168
