### ISSUE TITLE
smart tags search

### ISSUE THREAD

**Issue by Ssupreme** [joomla/joomla-cms#15141]
### Steps to reproduce the issue
1. open "tags" component and create tags simular to following:
йцукен 
йцукенг
йцукенгш
фывапрол
фывапролдж
фывапр
ячсмитьб
ячсми
ячсмитьбю.
qwertyuiop
qwerty
qwert
asdfghjkl
asdfgfgh
zxcvbnm,.
zxcvbn
2. go to article editor and in tags selector, try to type 3 first chars from non-latin language tags.  

### Expected result
smart search displays list of tags, which has 3 first chars in common.

### Actual result
smart search drops list of found tags after 1 sec, it doesn't work for latin tags.

### System information (as much as possible)
any system, tried even on 90 mins Joomla demo version. 

### Additional comments
I wasn't able to find what caused the issue, but after removing ajax-chosen.min.js from media/jui/js issue disappear, obviously other functionalities too.
I had the issue a year ago, there was a topic related to this issue regarding arab chars, cannot find it now. It was solved by changing timeout. After upgrade nothing works.

**Comment by franz-wohlkoenig** [comment]
Can't confirm: Create Teg "йцукен", copy "йцу" in "Tags"-Field, Tag is found.
### System information
3.7.0-rc4
macOS Sierra, 10.12.4
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by franz-wohlkoenig** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened in the future if it is updated.
