### ISSUE TITLE
[com_fields] Joomla 3.7.0. RC1: Description of option hide buttons in editor field

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#15159]
### Steps to reproduce the issue
Create an editor field an open the description for the option hide button

### Expected result
The description should describe the drop down

### Actual result
The old behavior - comma separeted list - is described.

![bildschirmfoto vom 2017-04-07 21-54-35](https://cloud.githubusercontent.com/assets/9974686/24817556/30a37e94-1bdd-11e7-8e08-0ef96aa1110f.png)

I could change this, but I am not sure if I can: RC1 is released and that also means language freeze is in effect now, right?

**Comment by Bakual** [comment]
>  RC1 is released and that also means language freeze is in effect now, right?

Yes. But it can be changed for 3.7.1.

**Comment by astridx** [comment]
OK, thank you for your answer. 
Then I will do that in the next days. Unless someone with better English skills does it before me :)

**Comment by brianteeman** [comment]
How about using the existing string
JGLOBAL_SELECT_SOME_OPTIONS

**Comment by astridx** [comment]
In this case we do not need to change language strings and it would be Ok in 3.7.0. I would like it.

**Comment by brianteeman** [comment]
If you do a PR to change to use this string you can also remove the now unused string from fields

**Comment by astridx** [comment]
I made the PR #15164 for the change of the language string in the plugin. 
How should I delete the no unused string. Which branch should I select? I do not find 3.7.1.
Should I select dev-3.8?

**Comment by brianteeman** [comment]
you can delete them from 3.7
As they are new strings its ok to remove them

**Comment by franz-wohlkoenig** [comment]
closed cause having PR #15164 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15159">issues.joomla.org/tracker/joomla-cms/15159</a>.</sub>
