### ISSUE TITLE
Create category on the fly

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#15151]
@pe7er added the ability to create categories when you are creating an article which is very useful. However it wont work unless you have at least on category already created on the system

![ca](https://cloud.githubusercontent.com/assets/1296369/24800459/2d68e11e-1b98-11e7-9117-d7f82049bb07.gif)

**Comment by AlexRed** [comment]
I can confirm the problem on Joomla! 3.7.0-RC2 (nightly Build)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15151">issues.joomla.org/tracker/joomla-cms/15151</a>.</sub>

**Comment by yasirunilan** [comment]
I can confirm the problem on Joomla! 3.7.0-RC2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15151">issues.joomla.org/tracker/joomla-cms/15151</a>.</sub>

**Comment by rjcf18** [comment]
I confirm this problem on Joomla! 3.7.0-RC2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15151">issues.joomla.org/tracker/joomla-cms/15151</a>.</sub>

**Comment by tonypartridge** [comment]
I can confirm this issue is present Joomla! 3.7.2. However, is it an issue? Since Joomla! ships with uncategorized as a default category anyway?

**Comment by brianteeman** [comment]
yes it is an issue if a user then goes and deletes that category before starting building the site

**Comment by tonypartridge** [comment]
PR coming soon.

**Comment by brianteeman** [comment]
woohoo

**Comment by brianteeman** [comment]
Closed as we have a PR #16323
