### ISSUE TITLE
[37] Intermitent 500 with JForm::getInstance could not load file

### ISSUE THREAD

**Issue by jsubri** [joomla/joomla-cms#15153]
### Steps to reproduce the issue
Intermittent. I can't reproduce however I had this issue on various laptops.
37RC1, back-end navigation such as Content Categories
When reloading the page everything is ok

### Expected result
No error on screen, no error in log file

### Actual result

Error on screen and in log file in /administrator/log/everything.php 

http://localhost/37RC1/administrator/index.php?option=com_categories&extension=com_content
Warning: simplexml_load_file(): I/O warning : failed to load external entity "D:\www\htdocs\37RC1\administrator/language/fr-FR/fr-FR.xml" in D:\www\htdocs\37RC1\libraries\joomla\language\helper.php on line 576
 JForm::getInstance could not load file

2017-04-07T14:31:59+00:00	ERROR 127.0.0.1	jerror	The com_content component's ACL configuration file is either missing or improperly structured.
2017-04-07T14:31:59+00:00	CRITICAL 127.0.0.1	error	Uncaught Exception of type JException thrown. Stack trace: #0 D:\www\htdocs\37RC1\libraries\legacy\error\error.php(277): JError::raise(1, 500, 'JForm::getInsta...', NULL, true)
#1 D:\www\htdocs\37RC1\administrator\components\com_categories\views\category\view.html.php(73): JError::raiseError(500, 'JForm::getInsta...')
#2 D:\www\htdocs\37RC1\administrator\components\com_categories\controller.php(95): CategoriesViewCategory->display()
#3 D:\www\htdocs\37RC1\libraries\legacy\controller\legacy.php(709): CategoriesController->display()
#4 D:\www\htdocs\37RC1\administrator\components\com_categories\categories.php(27): JControllerLegacy->execute(NULL)
#5 D:\www\htdocs\37RC1\libraries\cms\component\helper.php(394): require_once('D:\www\htdocs\b...')
#6 D:\www\htdocs\37RC1\libraries\cms\component\helper.php(369): JComponentHelper::executeComponent('D:\www\htdocs\b...')
#7 D:\www\htdocs\37RC1\libraries\cms\application\administrator.php(98): JComponentHelper::renderComponent('com_categories')
#8 D:\www\htdocs\37RC1\libraries\cms\application\administrator.php(156): JApplicationAdministrator->dispatch()
#9 D:\www\htdocs\37RC1\libraries\cms\application\cms.php(265): JApplicationAdministrator->doExecute()
#10 D:\www\htdocs\37RC1\administrator\index.php(51): JApplicationCms->execute()
#11 {main}

### System information (as much as possible)
Windows: 3.7RC1 with PHP 5.4 & 5.6

### Additional comments

https://github.com/joomla/joomla-cms/blob/b828e00f10ec1b0bf1b1141fa5fa6a37a1aaee14/libraries/cms/helper/content.php#L121

**Comment by fmsd91** [comment]
Why was this closed? I have the same issue and drives me crazy... very annoying...

**Comment by ghost** [comment]
@fmsd91 please open an new Issue. Comments on closed Issues didn't get much Notice.

**Comment by ggppdk** [comment]
You are in windows
maybe you are using symbolic links to somewhere in the path,
if you do , i think it is related to this intermittent error
