### ISSUE TITLE
[com_fields] Joomla 3.7.0. RC1: Default value in calendar field

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#15156]
### Steps to reproduce the issue
Create a new calendar field and set the default value to 2017-01-01

### Expected result
In frontend I will see no time 

### Actual result
In front there is a time displayed.

###System Info
Joomla! 3.7.0-rc1

### Additional comments
![calendar_field_frontend](https://cloud.githubusercontent.com/assets/9974686/24815007/fa601256-1bd3-11e7-9734-de6b45d4e61c.png)
![calendar](https://cloud.githubusercontent.com/assets/9974686/24815008/fa632efa-1bd3-11e7-93ce-41a77ead1fc2.png)
![calendar_field_create-en](https://cloud.githubusercontent.com/assets/9974686/24815009/fa646572-1bd3-11e7-8d5d-0a6a01bcc30d.png)

**Comment by Bakual** [comment]
If the time is shown or not depends on you "Show Time" setting right below the default value parameter.
I'd say it is expected behavior

**Comment by astridx** [comment]
OK, thank you for explaining.
