### ISSUE TITLE
Media Manager Uploading Images with 2-3 clicks instead of drag and drop

### ISSUE THREAD

**Issue by lenusch** [joomla/joomla-cms#15162]
Sometimes i use Wordpress for Projects but mainly Joomla. 
As i read that the Media Manager has some improvements i was missing the drag and drop feature as it is now with installing new componnents. 

Can't you make whole Media Manager field recognizing you if you pull some images inside of the Media Manager?

**Comment by brianteeman** [comment]
The media manager has NOT had any changes yet (other than a few css styles)

You can drag and drop images directly into the tinymce editor,

**Comment by dneukirchen** [comment]
Drag and Drop Upload is a planend Feature of the new Media Manager. We are currently working on it. You Can See the current State Here: https://github.com/joomla-projects/media-manager-improvement

**Comment by brianteeman** [comment]
Closing as this will be addressed in the new media manager for j4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15162">issues.joomla.org/tracker/joomla-cms/15162</a>.</sub>
