### ISSUE TITLE
[com_fields] Feature request - Icon field parameter

### ISSUE THREAD

**Issue by TLWebdesign** [joomla/joomla-cms#15163]
A great addition to the new fields function would be the ability to assign a font-awesome icon to the field to replace the label. 
A field where you could specify the icon like "fa-home" would suffice. Unfortunately i'm not smart enough to write code for this to be implemented. 

Regards
Tom

**Comment by Bakual** [comment]
Since we don't have "font-awesome" included in core, such a function wouldn't make much sense in core imho.
However using template overrides, it should be possible to do something like that for sure.

**Comment by TLWebdesign** [comment]
Is there an icon font that is included? I see iconmoon in the backend. With template overrides you mean the template view of the com_fields and use the "label" field as the value for the icon then?

**Comment by Bakual** [comment]
IcoMoon is included, yes. (https://docs.joomla.org/J3.x:Joomla_Standard_Icomoon_Fonts)
However it is not supported by all frontend templates. It's mainly used in the backend by extension devs.

With template overrides I mean that the rendering uses a JLayout (https://github.com/joomla/joomla-cms/blob/staging/components/com_fields/layouts/field/render.php) which can be overriden by templates. In that override you could do whatever you like. Eg use the label value as a class attribute (or only if it starts with "icon-"). Or you could use the "render class" as label class. Whatever suits your needs.

**Comment by franz-wohlkoenig** [comment]
@TLWebdesign should this Issue stay open?

**Comment by TLWebdesign** [comment]
No it shouldn't but i'm not familiar with the github etiquette ;)
