### ISSUE TITLE
[RFC] Updating Various Modules' Parameters to be Number Fields

### ISSUE THREAD

**Issue by justinherrin** [joomla/joomla-cms#15167]
**Request for comment...**

When using the various core modules there are quite a few of them that have parameters that require numbers to be entered into their input fields. I do not see `input type="number"` fields in those various modules (for example, the Count field in the Articles - Latest module).

Would updating those random module parameters fields to use type="number" be something beneficial to Joomla?

Figured I would make a request for comments/discussion before going through and spending time making a PR.

Thanks

**Comment by franz-wohlkoenig** [comment]
@maintainers: can you please answer the Offer by @justinherrin?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15167">issues.joomla.org/tracker/joomla-cms/15167</a>.</sub>

**Comment by brianteeman** [comment]
Seems to make sense to me

**Comment by ghost** [comment]
Opinion @mbabker?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15167">issues.joomla.org/tracker/joomla-cms/15167</a>.</sub>

**Comment by brianteeman** [comment]
Closing this as i have done the PRs
