### ISSUE TITLE
Undefined language string in Versions

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#15166]
### Steps to reproduce the issue
Under the following section, edit an entry and preview a version to see text without translation (highlighted in yellow).

Users > User Note Categories:
![user-notes](https://cloud.githubusercontent.com/assets/368084/24821780/7c9546f8-1ba5-11e7-83a9-b41bc6fd0f34.jpg)

**Comment by PhilETaylor** [comment]
Please test #15840

**Comment by zero-24** [comment]
Closing as there is a PR now.
