### ISSUE TITLE
Default category error on saving 'create article' menu item type

### ISSUE THREAD

**Issue by Gavakshi** [joomla/joomla-cms#15172]
### Steps to reproduce the issue
* Create a menu item of type:create article
* Tab 'options' > default category set to NO

### Expected result
The menu item should be saved

### Actual result
Error is displayed: Invalid field:Choose a category
![category](https://cloud.githubusercontent.com/assets/25766557/24826845/ab19476a-1c5c-11e7-8d2c-7024b4e931ed.png)

### System information (as much as possible)
Joomla -current-staging
Chrome
Windows7

**Comment by infograf768** [comment]
I can't reproduce your issue:
![screen shot 2017-04-08 at 09 52 59](https://cloud.githubusercontent.com/assets/869724/24826915/39dd9008-1c41-11e7-8eeb-c42113936e64.png)

**Comment by brianteeman** [comment]
This issue did exist but it was fixed by 15087

**Comment by Gavakshi** [comment]
I wish if there were a feature like "required if"

**Comment by Gavakshi** [comment]
closed as fixed in #15087.
Thanks @brianteeman
