### ISSUE TITLE
[3.7] Installation. Password fields display list

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#15179]
### Steps to reproduce the issue
- Newest Staging.
- Firefox 52.0.2.
- Start installation (Step 1) on a subdomain that I have used several times before for Joomla installations and where I logged in with several Usernames/Passwords in the past that are saved in FF.
- Click/focus on fields `Password` or `Confirm pw` displays a list of Usernames 
- Click/focus on field `Username` => No list.

![08-04-_2017_13-18-10](https://cloud.githubusercontent.com/assets/11038612/24828633/87c2ca16-1c61-11e7-843a-1a0f75a4281f.jpg)

### Additional comments
Behavior is irritating me a bit.

**Comment by zero-24** [comment]
Isn't this than a FF bug? What is expected to be shown behind the key symbol? the username or the actual pw? expecial as we have IIRC no browser spezific code there and the whole pw thing is done and saved in the browser.

**Comment by franz-wohlkoenig** [comment]
Username is to type in Field, click on Key-Symbol bring Password for User.

**Comment by zero-24** [comment]
but anyway this is a browserspecific thing than? that it saves two PW/username combinations with the same name?

**Comment by bertmert** [comment]
Normally I get some recommendations for Username. When I select one then the Password field is filled automatically with matching password.

When you set focus on password field there should be never a list expanding.

> that it saves two PW/username combinations with the same name?

If you're talking about "blubber" in my image. One was " blubber", other one "blubber".

> Isn't this than a FF bug?

Looks like you're right. Tested some other log-in masks (not Joomla) and they show a senseless **Username** list inside Password fields. Strange...
