### ISSUE TITLE
[com_fields] What can I insert as the default value of the field imagelist

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#15173]
### Steps to reproduce the issue
Create a field of the type image list and try to insert a default value. 

### Expected result
I can insert the file name of an image. I tried every combination of 
images/sampledata/fruitshop/apple.jpg.

### Actual result
It is not possible for me to insert any default value. I all the time get the message: 
Save failed with the following error: The default value is invalid.

![articles edit field joomla cms test administration 1](https://cloud.githubusercontent.com/assets/9974686/24827172/fa5c5072-1c45-11e7-8fe5-91d920c4c7c5.png)

**Comment by franz-wohlkoenig** [comment]
Issue confirmed. Tried verious Settings without Success.

**Comment by laoneo** [comment]
Guess a path to an image or folder.

**Comment by astridx** [comment]
@laoneo  Yes, but what syntax do we need to insert? No one of my tries works.

**Comment by brianteeman** [comment]
@laoneo I tried that :( doesnt work

**Comment by laoneo** [comment]
It should be one which maxhes an option value of the list. If it doesn't work, then it looks like a bug.

**Comment by brianteeman** [comment]
I tried
images
/images/
/images

etc - all fail

**Comment by joomdonation** [comment]
By reading the code. It should be the file name of the image you want to be selected by default. For example banner.jpg, osmbanner1.png.... in case you set Directory parameter to banners folder

**Comment by franz-wohlkoenig** [comment]
tried setting Path in PlugIn and only name in Field – no Luck.

**Comment by joomdonation** [comment]
1. Here is setting of field (note the value of Directory and Default Value)

![articles- edit field - joomla - administration](https://cloud.githubusercontent.com/assets/977664/24828777/6ca57188-1c8f-11e7-9673-265f49d2ee03.png)

2. Here is the add article form (note the file name you entered in Default value is selected)

![articles- new - joomla - administration](https://cloud.githubusercontent.com/assets/977664/24828785/96013152-1c8f-11e7-9c2a-d22082f9066d.png)

So it works well to me (maybe the Joomla installation I am having a bit outdated). Could you please try the same settings?

**Comment by astridx** [comment]
@joomdonation  Whitch Joomla Version do you use?

**Comment by joomdonation** [comment]
I am using Joomla! 3.7.0-rc1 dev, so it is outdated. I can try to update to stagging to check if needed

**Comment by franz-wohlkoenig** [comment]
![bildschirmfoto 2017-04-08 um 14 31 14](https://cloud.githubusercontent.com/assets/8235763/24828916/1811cbac-1c68-11e7-88c1-083c39ce973b.JPG)

**Comment by joomdonation** [comment]
A bug with validate default value of the field, then. I was able to edit code to bypass the check and confirm that default value is **the file name of the image you want to be selected by default** is correct, only field name, not contains path.

Maybe we can open a separate issue with this validation error?

**Comment by AlexRed** [comment]
I can confirm the problem on Joomla! 3.7.2-Dev (nightly Build)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15173">issues.joomla.org/tracker/joomla-cms/15173</a>.</sub>

**Comment by jakeinnh** [comment]
This issue still exists - can not save imagelist field with default value - name of image in selected folder.  Any suggested work-arounds?

Joomla 3.7.4
Windows 7.0 Ultimate SP1
IE 11.0.9600.18762 / Update Versions 11.0.45

PHP 7.0.22
MySQL 5.6.31

**Comment by newyenjay** [comment]
Wondering if there's been any progress on this? I'm still getting this error as well on Joomla 3.7.3

**Comment by brianteeman** [comment]
please upgrade to the latest release 3.8.5

**Comment by miggland** [comment]
Similar behaviour is observed with the sql field. If entering an ID (corresponding to value) or the text does not matter, same error appears.
When entering the default directly into the database via phpMyAdmin, the expected behaviour is observed, and the default is shown on the "Edit field" page in Joomla Administrator. However, changes can no longer be saved because of the error.

**Comment by ReLater** [comment]
Because the issue is still present in J3.9.5 I've created a pr https://github.com/joomla/joomla-cms/pull/24643

Experts should check the code changes there in detail.

**Comment by ghost** [comment]
Closed as having Pull Request.

**Comment by ReLater** [comment]
@franz-wohlkoenig 
Please reopen. Thank you!

**Comment by Quy** [comment]
Fixed #26352<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15173">issues.joomla.org/tracker/joomla-cms/15173</a>.</sub>
