### ISSUE TITLE
Problem of  installation freezing

### ISSUE THREAD

**Issue by Supun94** [joomla/joomla-cms#15189]
### Steps to reproduce the issue
During final step of Joomla 3.7.0-staging installation locally, using XAMPP faced this issue. The installation is not stopping and running...  
![screen shot 2017-04-09 at 17 32 02](https://issues.joomla.org/uploads/1/8cefabae83a8f2d8f239853cd59508b6.png)

### Expected result
Joomla landing page (display extra languages installation details, remove installation folder and Administration login details).  

### Actual result
The installation process is not stopping..

### System information (as much as possible)
Joomla 3.7.0-staging 
XAMPP v7.1.1 / PHP 7.1.1 (XAMPP Control Panel 3.2.2)
MariaDB 10.1.21 (In new version of XAMPP, MariaDB is a binary drop in replacement of the same MySQL version)

### Additional comments
The reason is Joomla can't create table in selected database. Latest XAMPP version not using MySQL and MariaDB is a drop-in replacement for MySQL. If it doesn't complete the installation, it should be a bug.

For locally fix this issue: Open **joomla.sql** in **_xampp\htdocs\\{joomla-cms_folder}\installation\sql\mysql_** folder. Find **"ENGINE=InnoDB"** and replace with **"ENGINE=MyIsam"**.

**Comment by mbabker** [comment]
You need to enable InnoDB support in your database platform.  Hacking the core database schema, while it might get you running, isn't a proper long term fix.

**Comment by zero-24** [comment]
Closing as expected behavior as InnoDB is a requirement to run joomla see: https://downloads.joomla.org/technical-requirements -> point `Mysql` => `(InnoDB support required)`

**Comment by zero-24** [comment]
Even if the error could also be a max_execution_time issue (to low value) in xampp
