### ISSUE TITLE
Front-end Admin Template missing field

### ISSUE THREAD

**Issue by donsiders** [joomla/joomla-cms#15183]
Log in to the front-end as the site admin.
Select the Home > Template option.

Fields listed include use Google Font toggle... but the Font name cannot be set.

![screen shot 2017-04-09 at 01 53 28](https://issues.joomla.org/uploads/1/b804955820fa05477a6f733c751e7135.png)

**Comment by franz-wohlkoenig** [comment]
Confirmed.
### System information
3.7.0-rc1 (nightly Build)
macOS Sierra, 10.12.4
Firefox 52 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by bertmert** [comment]
Same issue with `showon` attribute in FE with template Beez3 and setting `Template Colour`. After setting option to `Custom` an image selection field and color field should appear but do not.

### Backend
![09-04-_2017_12-18-27](https://cloud.githubusercontent.com/assets/11038612/24836543/0db82c34-1d1f-11e7-83f6-89595aacc96b.jpg)

### Frontend
![09-04-_2017_12-19-44](https://cloud.githubusercontent.com/assets/11038612/24836545/15a3e15e-1d1f-11e7-9a68-dabc35b96eaf.jpg)

**Comment by brianteeman** [comment]
Looks like the bug is with the showon code

If you remove
`					showon="googleFont:1" />
`
from
`templates\protostar\templateDetails.xml`

then it works

**Comment by infograf768** [comment]
afaik showon has never worked in frontend since it was implemented.

**Comment by brianteeman** [comment]
its odd as the js with the showon code is loaded but not triggered

js is beyond me

**Comment by Bakual** [comment]
> its odd as the js with the showon code is loaded but not triggered

The identifier is wrong calculated and not taking into account the field group ("params").

Please try #15202
