### ISSUE TITLE
[4.0] Field Calendar Size

### ISSUE THREAD

**Issue by NunoLopes96** [joomla/joomla-cms#15182]
### Steps to reproduce the issue

Currently when the field type is a calendar it has a fixed width that can cause it going out of the window, you can see that in Modules -> Select one Module -> Right side the "Start Publishing" and "Finish Publishing" fields

### Expected result

![screenshot from 2017-04-08 18-04-30](https://cloud.githubusercontent.com/assets/20955884/24830859/d4b6e68a-1c85-11e7-80d9-3e3ea9fe60eb.png)

### Actual result

![screenshot from 2017-04-08 17-58-38](https://cloud.githubusercontent.com/assets/20955884/24830861/dbb88aec-1c85-11e7-9fb0-8834bb496e86.png)

![screenshot from 2017-04-08 17-58-26](https://cloud.githubusercontent.com/assets/20955884/24830862/def04ee8-1c85-11e7-975c-78d1e6c56a7e.png)

### System information (as much as possible)

Chrome
ApricityOs 64bits

**Comment by franz-wohlkoenig** [comment]
1/2 – Confirmed (but no Problem as i see):
![1](https://cloud.githubusercontent.com/assets/8235763/24834949/c0f9147e-1cf3-11e7-8a55-005e5a0cc0bd.JPG)
2/2 – Not confirmed, but look at missing right-borderline of Dropdownfield:
![2](https://cloud.githubusercontent.com/assets/8235763/24834951/edbe0dd4-1cf3-11e7-8c43-9d35a48ce7fd.JPG)

**Comment by ghost** [comment]
@C-Lodder any Suggestion?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15182">issues.joomla.org/tracker/joomla-cms/15182</a>.</sub>

**Comment by ghost** [comment]
@C-Lodder can this be closed in Favor of new Backend-Template?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15182">issues.joomla.org/tracker/joomla-cms/15182</a>.</sub>

**Comment by C-Lodder** [comment]
@franz-wohlkoenig - let's leave this open for now. @ciar4n and myself will sift through 4.0-UI related issues once we've completed the work for the new backend template to see if they still apply.

**Comment by brianteeman** [comment]
Closing this as it would appear to be resolved in the current version of the admin template
