### ISSUE TITLE
The JavaScript for repeatable subforms produces wrong id attributes

### ISSUE THREAD

**Issue by saimiri** [joomla/joomla-cms#15187]
I noticed a bug in the way the `id` attributes are created for repeatable subform fields in the JavaScript. On line 163 in `subform-repeatable.js` there is this:

`id = name.replace(/(\]|\[\]$)/g, '').replace(/\[/g, '_')`

which in the end produces id attributes like `jform_contacts_contacts3_is_primary0`. Unfortunately, the id attributes in the subform templates are in the format of `jform_contacts__contactsX__is_primary`, so the correct result should be something like `jform_contacts__contacts3__is_primary0`, with double underscores.

Because the `id` attribute doesn't match what is in the templates, the label elements get broken because their `for` attribute ends up being `jform_contacts__contactsX__is_primary0` or similar, that is, the X does not get replaced.

A quick and dirty fix is to replace aforementioned line with

`id = name.replace(/(\]\[)/g, '__').replace(/(\[)/g, '_').replace(/(\]$)/g, '')`

but I'm sure there is a smarter way, too.

**Comment by Fedik** [comment]
I can confirm the issue, 
Additionally: `<fieldset>` of radio buttons, also has "unfixed" id

**Comment by Fedik** [comment]
@saimiri please test #16480

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16480<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15187">issues.joomla.org/tracker/joomla-cms/15187</a>.</sub>
