### ISSUE TITLE
scss is not visible in the backend

### ISSUE THREAD

**Issue by josflachs** [joomla/joomla-cms#15197]
It's not possible to modify or even see .scss files in the backend. Less files no problem, css, excellent. But scss files are not visible. 

Add a scss folder in a template, place some .scss files in that folder, also .sass, .css and .less files to see the difference. Empty files is good enough to spot the problem. 

You will see all the folders in the scss folder, and in those folders the .less and .css files. But not .sass and .scss files. 
![screen shot 2017-04-10 at 08 27 26](https://issues.joomla.org/uploads/1/3fc11b216a5796d9529f26a07d879b45.jpg)![screen shot 2017-04-10 at 08 27 29](https://issues.joomla.org/uploads/1/2061448c23d1c5b47df4afe292ec44f3.jpg)

**Comment by josflachs** [comment]
Screen 2 is Protostar, the screen below is the template I'm building. Problem is Joomla itself. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15197">issues.joomla.org/tracker/joomla-cms/15197</a>.</sub>

**Comment by brianteeman** [comment]
Please go to the template options and confirm that both scss and sass are in the list of source formats (as shown below)

<img width="396" alt="screenshotr09-33-23" src="https://cloud.githubusercontent.com/assets/1296369/24852812/c43b2054-1dd0-11e7-9be1-2f787590ad9e.png">

**Comment by brianteeman** [comment]
As of Joomla 3.7 scss and sass are listed by default as Valid Source Formats - this was added in PR #10186

Before Joomla 3.7 you will need to add them yourself.

**Comment by dgt41** [comment]
Also you might need https://github.com/joomla/joomla-cms/pull/14485 to beautify the code

**Comment by josflachs** [comment]
Okay, that works. Problem solved!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15197">issues.joomla.org/tracker/joomla-cms/15197</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
closed as Issue solved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15197">issues.joomla.org/tracker/joomla-cms/15197</a>.</sub>
