### ISSUE TITLE
Error 500 on custom fields in 3.7.0.rc1

### ISSUE THREAD

**Issue by JurgenG** [joomla/joomla-cms#15195]
### Steps to reproduce the issue
Not sure. This site started as 3.7.0.beta3 and followed the upgrade path up to current 3.7.0.rc1
I created a few fields and a field group back at beta3. (not certain if this is relevant)
I created an empty field group (not certain if this is relevant).
I go to Content >> Fields

### Expected result
Custom fields list view.

### Actual result
Raising error 500: Unknown column 'a.name' in 'field list' 

### System information (as much as possible)
Here is the debug information when parsing the error:

```
Call stack
	Function 	Location
1 	JError::raise() 	JROOT/libraries/legacy/error/error.php:277
2 	JError::raiseError() 	JROOT/administrator/components/com_fields/views/fields/view.html.php:81
3 	FieldsViewFields->display() 	JROOT/libraries/legacy/controller/legacy.php:671
4 	JControllerLegacy->display() 	JROOT/administrator/components/com_fields/controller.php:57
5 	FieldsController->display() 	JROOT/libraries/legacy/controller/legacy.php:709
6 	JControllerLegacy->execute() 	JROOT/administrator/components/com_fields/fields.php:29
7 	require_once() 	JROOT/libraries/cms/component/helper.php:394
8 	JComponentHelper::executeComponent() 	JROOT/libraries/cms/component/helper.php:369
9 	JComponentHelper::renderComponent() 	JROOT/libraries/cms/application/administrator.php:98
10 	JApplicationAdministrator->dispatch() 	JROOT/libraries/cms/application/administrator.php:156
11 	JApplicationAdministrator->doExecute() 	JROOT/libraries/cms/application/cms.php:265
12 	JApplicationCms->execute() 	JROOT/administrator/index.php:51 

```

**Comment by brianteeman** [comment]
Can you please test on a clean install of 3.7 or a direct upgrade from 3.6.5

**Comment by infograf768** [comment]
The table has been modified. It will not happen with a clean update or new install.

To solve this, I deleted the 4 fields tables in the db, then applied the query:
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/sql/updates/mysql/3.7.0-2016-08-29.sql

And then Went to Extensions=>database and used the Fix button

**Comment by Bakual** [comment]
You can just renamed the "alias" column in the #__fields table to "name" and the error is gone.

It's a known issue for an unsupported upgrade path (from a beta to rc).
