### ISSUE TITLE
Joomla 3.7.0 RC1 - chosen.css overrides chosen.css of component extension

### ISSUE THREAD

**Issue by Gitjk** [joomla/joomla-cms#15190]
### Question:
Apparently the isis template has been changed with some chosen.css, which now overrides the chosen.css of third party components. In my test installation it overrides the chosen.css of VirtueMart,killing the button design.

Is it possible for you guys to implement the chosen.css in isis in a way that it doesn't override the chosen.css of Joomla extensions?

![screen shot 2017-04-09 at 19 13 02](https://issues.joomla.org/uploads/1/8a3318d756642c8cd24d0097b13a064b.png)

**Comment by demis-palma** [comment]
There is a PR https://github.com/joomla/joomla-cms/pull/14975 that could solve the width problem.
However, the 3D style has been removed intentionally.

**Comment by franz-wohlkoenig** [comment]
@Gitjk have you test PR like @demis-palma wrote?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15190">issues.joomla.org/tracker/joomla-cms/15190</a>.</sub>

**Comment by Gitjk** [comment]
@franz-wohlkoenig 

>  have you test PR like @demis-palma wrote?
No, I only tested the PR using the 'Joomla Patch Tester', which resulted in plenty of chosen.css and js errors.

**Comment by demis-palma** [comment]
Is it a problem of visual glitches, or just the 3D style that has become flat?

**Comment by Gitjk** [comment]
> Is it a problem of visual glitches, or just the 3D style that has become flat?

As you can see in the second screenshot above, the last characters of Yes/No are too close to the border in some configuration views. However, VirtueMart developers came up with a solution for that. Just requires to change 3 lines in the chosen.css used by VirtueMart. (If I want the 3D style back, I can simply replace the current chosen files with the original Chosen 1.7.0 files).

**Comment by franz-wohlkoenig** [comment]
@Gitjk if this Issue is solved, please close it, thanks.

**Comment by Gitjk** [comment]
Don't know if other extensions which use chosen are affected. But so far I have not seen any similar reports by others. So I'll close this issue.
