### ISSUE TITLE
[com_fields] User Activation by Admin empties custom fields from Registration

### ISSUE THREAD

**Issue by gwsdesk** [joomla/joomla-cms#15194]
Using custom fields in Registration. One type "text" field and one type "list" 

Users are being activated by the Administrator. Upon activation of the user by an Administrator all entries of the custom fields are being deleted

Issue confirmed by me upon testing after a [post on the forums](https://forum.joomla.org/viewtopic.php?f=708&t=948961&p=3469027#p3469027 "Post on the forums")

**Comment by AlexRed** [comment]
I can confirm the problem on Joomla! 3.7.0-RC2 (nightly Build)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15194">issues.joomla.org/tracker/joomla-cms/15194</a>.</sub>

**Comment by AlexRed** [comment]
it is similar to https://issues.joomla.org/tracker/joomla-cms/9129

**Comment by rdeutz** [comment]
closed because we have a PR #15308

**Comment by IlCallo** [comment]
Hi guys,
I'm on Joomla 3.7.2 and I have what seems to be the same problem descripted here.
I added a custom field (phone number) upon registration.
When I change assigned group to the user, the value of the custom field gets wiped out for apparently no reason.
Hints?

**Comment by franz-wohlkoenig** [comment]
I guess few People read on closed Issues so please ask help on the [forums](https://forum.joomla.org/).
