### ISSUE TITLE
[com_fields] Automatic Display of Custom Fields.

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#15204]
### Steps to reproduce the issue
We have the options "After Title", "Before Display","After Display" and "No". Translating this into Dutch I do think it is better to use "Not" instead of "No". I am not native English, but in Dutch it is better. Because of the use of JNO as string I don't have the option to change it in the Dutch translation.
### System information (as much as possible)
J 3.7 RC1

### Additional comments
If this is not changed it is not a problem for the Dutch language, everybody will understand.

**Comment by brianteeman** [comment]
Even better would be to change it to 
Do not automatically display

It is indeed too ambiguous right now even in english

**Comment by brianteeman** [comment]
Closed as we have a PR #17607
