### ISSUE TITLE
sendPermissions() not working with custom form or control name

### ISSUE THREAD

**Issue by Globulopolis** [joomla/joomla-cms#15203]
### Steps to reproduce the issue
Add custom form
```xml
<?xml version="1.0" encoding="utf-8"?>
<form>
	<fields name="name">
		<fieldset name="edit">
			<field name="rules" type="rules" label="JGLOBAL_ACTION_PERMISSIONS_LABEL" class="inputbox" filter="rules"
				   component="com_my" section="name" validate="rules"/>
		</fieldset>
	</fields>
</form>
```
Load form from model via
```php
public function getForm($data = array(), $loadData = true)
{
	$form = $this->loadForm('com_my.name', 'name', array('control' => 'form', 'load_data' => $loadData));

	if (empty($form))
	{
		return false;
	}

	return $form;
}
```

On rules matrix change selected value.
### Expected result
Ajax request to Com-Config Application Controller

### Actual result
Javascript error in console.
![clipboard03](https://cloud.githubusercontent.com/assets/740757/24859906/00783974-1dfb-11e7-905b-93a5c927bcc3.jpg)

### System information (as much as possible)
Joomla 3.6.4
Firefox 52

### Additional comments
Problem in hard-coded field names for title and rules. Of course if we're planing to use rules field in custom component w/o title field or with different form name controls we will got same error.

**Comment by franz-wohlkoenig** [comment]
do you have this Issue on latest Staging too?

**Comment by Globulopolis** [comment]
@franz-wohlkoenig yes. Same error on line https://github.com/joomla/joomla-cms/blob/staging/media/system/js/permissions-uncompressed.js#L47

**Comment by zero-24** [comment]
@Globulopolis can you think of a patch that handle both cases and send it against the staging branch than?

**Comment by Globulopolis** [comment]
@zero-24 my knowledge in javascript very bad.

**Comment by brianteeman** [comment]
Closed as expected behaviour
