### ISSUE TITLE
[com_fields] Hathor never displays fields

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#15205]
Add a field to any of the supported components eg Users, Contact or Content

### Expected Result

Input for the field is available when editing or creating an item

### Actual Result

No input fields presented

**Comment by Bakual** [comment]
As a background if someone wants to take a stab at this. The fields are loaded usually by a JLayout using this call:
`<?php echo JLayoutHelper::render('joomla.edit.params', $this); ?>`
That JLayout just iterates over each fieldset and renders it.
With `$this->ignore_fieldsets = array('jmetadata', 'item_associations');` one can exclude some fieldsets from being rendered by that JLayout.
Something similar needs to be done for Hathor for it to support custom fields in the forms.

**Comment by jbreeding** [comment]
I was testing my custom fields, then switch to Hathor [Joomla! 3.7RC1).
I can see all my customs fields in [Fields Tab], and also User Custom fields.
![screen shot 2017-04-10 at 14 57 09](https://issues.joomla.org/uploads/1/19c116dd70d354cf68ffa1abd45d404b.jpeg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15205">issues.joomla.org/tracker/joomla-cms/15205</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@jbreeding Articles > Edit Field:
![bildschirmfoto 2017-04-10 um 17 25 47](https://cloud.githubusercontent.com/assets/8235763/24869226/d5f88e02-1e12-11e7-8908-fc7d29780465.JPG)
### System information
3.7.0-rc1 (nightly Build)
macOS Sierra, 10.12.4
Firefox 52 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by jbreeding** [comment]
![screen shot 2017-04-10 at 15 49 39](https://issues.joomla.org/uploads/1/d09870a609a42993b90eef0c55f67285.jpeg)

### System Information
 Joomla! 3.7.0-rc1 [ Amani ]
 Apache/2.4.20 (Ubuntu)
 Version 53.0.2785.143 running on Ubuntu 14.04 (64-bit)

### Apache/2.4.20 (Ubuntu)

 PHP 7.0.17
 MySQLi 5.5.54

It seems good ?

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15205">issues.joomla.org/tracker/joomla-cms/15205</a>.</sub>

**Comment by brianteeman** [comment]
Sorry it does work on users - it doesnt work on content or contacts

**Comment by jbreeding** [comment]
Ok, got it.

User => OK
Contact => NOK
Content => NOK

you right for both.

### Edit Content:
![screen shot 2017-04-10 at 16 58 08](https://issues.joomla.org/uploads/1/df1301ff4b2b885837a27fccf13e48ad.jpeg)

### Edit Contact:
![screen shot 2017-04-10 at 16 59 24](https://issues.joomla.org/uploads/1/d2a015e7af18c348635c581206ddf0cd.jpeg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15205">issues.joomla.org/tracker/joomla-cms/15205</a>.</sub>

**Comment by infograf768** [comment]
I am on it. Patch will be ready this afternoon.

We will get (here for articles):
![screen shot 2017-04-11 at 13 03 47](https://cloud.githubusercontent.com/assets/869724/24906279/6189f240-1eb7-11e7-8d42-4ffed7c59602.png)

**Comment by brianteeman** [comment]
Thanks - dont forget that "Fields" is just for fields that are not in a group and you would need a new slider for each group

**Comment by infograf768** [comment]
Closed as we have a patch https://github.com/joomla/joomla-cms/pull/15227<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15205">issues.joomla.org/tracker/joomla-cms/15205</a>.</sub>

**Comment by brianteeman** [comment]
Thanks @infograf768
