### ISSUE TITLE
[newsfeeds] Hits not display in Isis and no value display in Hathor

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#15212]
### Steps to reproduce the issue
Edit a news feed.
Go to Publishing in Isis.
Go to Metadata in Hathor.

* In Isis, Hits is missing.
![hits-isis](https://cloud.githubusercontent.com/assets/368084/24883798/5bb0fc04-1dfb-11e7-920a-b4ff9b988b22.jpg)
* In Hathor, Hits has no value. I manually added a value to `hits` column in the db for testing purpose.
![hits-hathor](https://cloud.githubusercontent.com/assets/368084/24883807/657dccf8-1dfb-11e7-8b64-ca00e1354a96.jpg)

**Comment by franz-wohlkoenig** [comment]
Confirmed on both Templates. No Difference if Newsfeed is clicked on Frontend or not.
### System information
3.7.0-rc1 (nightly Build)
macOS Sierra, 10.12.4
Firefox 52 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by zero-24** [comment]
closing as there is a PR at #15464

**Comment by zero-24** [comment]
Would be great to get your feedback on that one. Thanks!
