### ISSUE TITLE
Component dropdown does not get the ??MISSING_LANGUAGESTRING??

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#15211]
### Steps to reproduce the issue

- install staging
- install e.g german (or any other 3.6.5 language pack)
- switch to that language in the backend

### Expected result

??COM_ASSOCIATIONS?? in the components dropdown

### Actual result

"Multilingual Associations" (even without the ** arround it)
![image](https://cloud.githubusercontent.com/assets/2596554/24877080/4abb570e-1e2e-11e7-9e01-2e0d26953b46.png)

### Additional comments

It work for the other dropdowns but not for the component dropdown?
![image](https://cloud.githubusercontent.com/assets/2596554/24877058/377f23c8-1e2e-11e7-9829-0c7d9825e7dc.png)

**Comment by alikon** [comment]
work for @infograf768 ?
:smile:

**Comment by AlexRed** [comment]
I can confirm the problem on Joomla! 3.7.0-RC2 (nightly Build)

I think you need to add in the "Steps to reproduce the issue" enable Debug Language in global configuration
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15211">issues.joomla.org/tracker/joomla-cms/15211</a>.</sub>

**Comment by infograf768** [comment]
Interesting...
You will remark that we do now get the correct ?? when the ini file does not exist at all grace to my PR https://github.com/joomla/joomla-cms/pull/14801
i.e.
![screen shot 2017-04-11 at 10 12 03](https://cloud.githubusercontent.com/assets/869724/24899090/5f4dba9c-1e9f-11e7-8e95-7dda21b7e41c.png)

But not for the admin menu where the alias set in the db ( https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/script.php#L143) created by the script is used.

Let's see what we can do.

**Comment by infograf768** [comment]
Looks like it is due to the /administrator/modules/mod_menu/helper.php

If I change to
```
					if (!JFactory::getConfig()->get('debug_lang'))
					{
						$component->text = $lang->hasKey($component->title) ? JText::_($component->title) : $component->alias;
					}
					else
					{
						$component->text = $lang->hasKey($component->title) ? JText::_($component->title) : JText::_(strtoupper($component->element));
					}
```

I would get:
![screen shot 2017-04-11 at 10 53 14](https://cloud.githubusercontent.com/assets/869724/24900837/758a41a8-1ea5-11e7-9a2a-4a0929496f60.png)

Would that be satisfactory?

**Comment by infograf768** [comment]
or we could use `JText::_(strtoupper($component->alias))` instead of `element`

**Comment by zero-24** [comment]
Thanks @infograf768 i have done a PR #15231 which just uses the magic in Joomla. As there is no fallback needed ;)

Closing here.
