### ISSUE TITLE
A security vuln of joomla report to security@joomla.org but get no response after almost 5 days

### ISSUE THREAD

**Issue by kevinoclam** [joomla/joomla-cms#15218]
I have found a vuln of joomla and report the detail to security@joomla.org.
According to https://developer.joomla.org/security.html , I should get acknowledged response already ,but actually , I didn't get anyone.
My email address is chenruiqi@b.360.cn
In the email, I test joomla 3.6.5 , just now , I test Joomla! 3.7.0 Release Candidate 1 and it works.
I just want to know whether you have get the mail.

**Comment by jeckodevelopment** [comment]
@SniperSister can you check please?

**Comment by gwsdesk** [comment]
Just in general to get the fastest reply I guess the best way is to use the VEL Reporting tool https://vel.joomla.org/submit-vel<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15218">issues.joomla.org/tracker/joomla-cms/15218</a>.</sub>

**Comment by demis-palma** [comment]
VEL is for the extensions, while @kevinoclam reported a Joomla issue. Please wait until we got a reply from David.

**Comment by gwsdesk** [comment]
@demis-palma that is incorrect and I quote "We accept reports of security vulnerabilities for Joomla and Joomla extensions"

**Comment by zero-24** [comment]
@kevinoclam i have just checked the internal mailing list and i can not find any messages. Did you get any kind of auto responder to your message?

To be sure please use this form to get in contact with the JSST: https://developer.joomla.org/security/contact-the-team.html

**Comment by kevinoclam** [comment]
Thanks a lot.
@zero-24 I didn't use the form because I don't know how to attach a picture, and I didn't get any auto response. I send the email directly with outlook. Now I have used the form to send the report.
@gwsdesk Thanks a lot too, I also send a report via the VEL Reporting tool .

**Comment by zero-24** [comment]
@kevinoclam hmm I still can't see it in the list. Please send it to my community account so I can share it with the other members of the JSST. Thanks.

**Comment by mbabker** [comment]
It's in the security@ email.  Unfortunately Google's mail filters flagged it as spam so our ticketing system didn't receive it.

**Comment by jeckodevelopment** [comment]
So since it has been received properly, i guess we can close this issue.
Thanks Tobias and Michael ;)
