### ISSUE TITLE
Random Order in articles

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#15220]
### Steps to reproduce the issue
When you create a menu item for Category Blog, in the Tab Blog layout, in Article Order, it's possible to choose Random order, ok, but when you create a menu item for Featured articles, in the Tab Blog layout, in Article Order, NOT is possible to choose Random order.

### Expected result
Show ramdom order article in Featured Articles

### Actual result
No option available for Featured Articles

### System information (as much as possible)
Joomla 3.6.x

### Additional comments
I think that a serious improvement of usability and functionality, is more common a random order in featured articles than in the blog view.

**Comment by brianteeman** [comment]
If i remember correctly "random" is a very new addition

**Comment by alikon** [comment]
if it is considered a valuable option , i'll look at it, till now i've always considered "featured" use case with a fixed order only, but obviusly i'm wrong....

**Comment by Open2logic** [comment]
Yes Brian, is very new and we were excited about this option (random
order), but ooops, it is not enabled on featured articles.

Hello Nicola, on news websites, directories, classified ads, etc. sort
categories by date but featured articles in random.
In this way they do not give more relevance to one announcement or
news than another.
Sorry for my english.
Thanks for the quick reply




2017-04-11 14:51 GMT+02:00 Nicola Galgano <notifications@github.com>:

**Comment by alikon** [comment]
@Open2logic  can you test #15232

**Comment by zero-24** [comment]
Closing as there is a PR Thanks @alikon
