### ISSUE TITLE
[com_fields] Fields do not delete from the database when deleted from the back end

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#15230]
### Steps to reproduce the issue
Create a new field
Delete the field

### Expected result
Cannot see the field in the database

### Actual result
The field remains

### System information (as much as possible)
[systeminfo-2017-04-11T12-32-41-05-00.txt](https://issues.joomla.org/uploads/1/5ba883a7f314479ec4daedf713ae48c8.txt)

### Additional comments
I don't know if this was present before RC-1 it's not the sort of thing I would notice ordinarily.

**Comment by uglyeoin** [comment]
This was present before rc-1 because I see fields that I created when on beta.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15230">issues.joomla.org/tracker/joomla-cms/15230</a>.</sub>

**Comment by zero-24** [comment]
Confirmed please try this out: https://github.com/joomla/joomla-cms/pull/15233

**Comment by zero-24** [comment]
Closing as there is a patch

**Comment by uglyeoin** [comment]
Please reopen.  Tested and I get the same result.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15230">issues.joomla.org/tracker/joomla-cms/15230</a>.</sub>

**Comment by zero-24** [comment]
Can we please move that to the PR? What exactly fail? Did you apply the patch? etc so i can fix my Pr if needed. Thanks.
