### ISSUE TITLE
Notice in the TinyMCE after update 3.6.5 to 3.7.0Rc2

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-cms#15243]
### Steps to reproduce the issue
after update 3.6.5 to 3.7.0Rc2 try to create a new article or category, 
Notice: Undefined property: stdClass::$readonly in /opt/lampp/htdocs/Joomla_3.6.5_ita-Stable-ok/layouts/joomla/tinymce/textarea.php on line 22
inside the TinyMCE editor

### Actual result
![error-update-rc2](https://cloud.githubusercontent.com/assets/1362388/24952309/f2fa4038-1f6e-11e7-9590-e0c525727f7d.png)

**Comment by zero-24** [comment]
@Bakual can you check this please. As this line comes from https://github.com/joomla/joomla-cms/pull/15157 ;)

**Comment by Bakual** [comment]
Can you test https://github.com/joomla/joomla-cms/pull/15254
