### ISSUE TITLE
[com_fields] Automatic Display lost parameter for User registration Field

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-cms#15244]
### Steps to reproduce the issue
Create a new user registration Field, in TAB "Options" you can select the parameter "Automatic Display" but it is irrelevant. For me it is ok only for articles field and not for user registration or contact.

### Expected result
No Automatic Display

### Actual result
Automatic Display can be set but not work and no sense (after title?)

### System information (as much as possible)
![automatic-display](https://cloud.githubusercontent.com/assets/1362388/24953133/1a5b17da-1f72-11e7-9941-a9d7740c9d75.png)

**Comment by gwsdesk** [comment]
Issue replicated by me so confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15244">issues.joomla.org/tracker/joomla-cms/15244</a>.</sub>

**Comment by laoneo** [comment]
Duplicate of #14377, or?

**Comment by franz-wohlkoenig** [comment]
Closed: Duplicated Report #14377 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15244">issues.joomla.org/tracker/joomla-cms/15244</a>.</sub>

**Comment by laoneo** [comment]
Please test #15915 which should fix that issue.
