### ISSUE TITLE
Applying an article layout from a category menu Item

### ISSUE THREAD

**Issue by SemaphoreOxalis** [joomla/joomla-cms#15259]
### Steps to reproduce the issue
From ages Joomla! don't offer an out-off-box solution for applying an article alternative layout on a category without a article link menu or directly in the article params. We have to test the cat ID in article/default.php override. 
I think the right way of thinking was to apply a article alternative layout from a category item menu for example.

Create an alternative article view
Create a Blog view
We can't select an article alternative view only alternative category

### Expected result

Having the possibility to select an alternative article view

### Actual result
Nothing to select

### System information (as much as possible)

J3.6.5

### Additional comments
After reading the article/view.html.php we see the controller just check for the article_layout params in **ANY** type of menu item including category item menu !
We just have to add the `<field name="article_layout" type="componentlayout" extension="com_content" view="article"...` fields in the menu item XML (blog.xml if we use the default menu item) et voilà ! We can select an article alternative layout
Our main question is why is it's so simple why Joomla! don,'t use it actually ? What we are missing ?

**Comment by mbabker** [comment]
See https://github.com/joomla/joomla-cms/pull/14802

**Comment by SemaphoreOxalis** [comment]
Sorry for that duplicate post we use this for a long time ago in our office and wait too long for posting this...
