### ISSUE TITLE
Unpublish categories - Create article in frontend

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#15252]
### Steps to reproduce the issue
Menu item in Create article
In the list of categories (backend) the are published categories  and unpublished categories 
![unpublished](https://cloud.githubusercontent.com/assets/9007607/24956754/614778b6-1f89-11e7-9f3e-e4c1c07585d8.JPG)

In the frontend in the create article form show all categories, published and unpublished
![all-categories](https://cloud.githubusercontent.com/assets/9007607/24956797/9bfea812-1f89-11e7-85f7-0810a68e83e4.JPG)

### Expected result
Show only the published categories

### Actual result
Show all categories, published and unpublished

### System information (as much as possible)
Joomla 3.7

### Additional comments
If a website has a lot of unpublished content this view is annoying to the user

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.
### System information
3.7.0-rc2 (nightly Build)
macOS Sierra, 10.12.4
Firefox 52 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by alikon** [comment]
i'm not so sure to consider this like an issue

**Comment by Bakual** [comment]
The unpublished ones are marked with `[ ... ]` as you see in your screenshot.
If there is a lot of unpublished content, then one should maybe better trash them instead.

Anyway, this is working as expected because there are use cases to create articles in unpublished categories.

**Comment by Open2logic** [comment]
It's understandable.

I've been looking for days, how to improve the usability and user
experience.

thanks!



2017-04-12 15:58 GMT+02:00 Thomas Hunziker <notifications@github.com>:
