### ISSUE TITLE
B/C break in the Calendar Field

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#15251]
In an Application where the Calendar is used in the frontend, I replace Data via Ajax.
This requires inizialisation of the calendar in js. 
It works fine in 3.6, but not in 3.7 because the name and params have changed.

**Comment by zero-24** [comment]
@dgt41 can you take a look here?

**Comment by dgt41** [comment]
@chmst can you create a codepen with the code you are using?

**Comment by chmst** [comment]
https://gist.github.com/chmst/a825bf5edb86b04de6b865e7a112f680 hope you can see this.

**Comment by wilsonge** [comment]
@dgt41 any updates on your side here?

**Comment by dgt41** [comment]
Nope
@chmst can you provide some more info here?
like do you initiate the calendar with JHtml?
What options are you using?

One simple way to force initialising the calendar on the success of your javascript is to 
- have a dummy class in the dom Loaded e.g. `.field-unused-calendar`
- on success execute `JoomlaCalendar.init(".field-unused-calendar");`

Or you can replicate what @Fedik is doing for the subforms: https://github.com/joomla/joomla-cms/blob/staging/media/system/js/fields/calendar.js#L1127-L1129

Joomla doesn't have control over the javascript events so we need to improvise here :(

@wilsonge I don't see we can do something more here

**Comment by bembelimen** [comment]
1. Create a JForm XML file with a calendar field
2. Output the calendar field (=> The calendar JS will be initialized)
3. now inject a complete jform calendar field html into your document
4. initialize the calendar via JS code (=> see @chmst code)

The 3.6.5 code does not work in 3.7 anymore

**Comment by dgt41** [comment]
@bembelimen the calendar initialises itself on the event 'DOMContentLoaded', @chmst 's code will not work as there's no setup function anymore...

**Comment by bembelimen** [comment]
as I said, the first input field is initialized, but the second have to be initialized manually, because it's injected after dom loaded

**Comment by zero-24** [comment]
Closing as there is a PR by @dgt41 #15487 Please test there!
