### ISSUE TITLE
[4.0] [Dashboard] Call to a member function setState()

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#15255]
### Steps to reproduce the issue

Go to the Joomla 4.0- dashboard

### Expected result

Working dashboard

### Actual result

> Fatal error: Call to a member function setState() on null in C:\dev\joomla4\administrator\modules\mod_latest\helper.php on line 38

![untitled](https://cloud.githubusercontent.com/assets/2019801/24958849/b557fb7a-1f88-11e7-8bab-e16cbfe8e255.png)

### System information (as much as possible)

- Joomla 4
- PHP 5.6 and 7.0

@laoneo @yvesh

**Comment by laoneo** [comment]
This is fixed5 with #15256.

**Comment by joomdonation** [comment]
But broken now after https://github.com/joomla/joomla-cms/pull/15176 merged. Please wait until https://github.com/joomla/joomla-cms/pull/15253 merged before testing again

**Comment by wilsonge** [comment]
Fixed in J4 again with #15253
