### ISSUE TITLE
[4.0] PHP Fatal error on com_content

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#15256]
### Steps to reproduce the issue

Go to `example.com/administrator/index.php?option=com_content`

### Expected result

List of articles

### Actual result

> Fatal error: Class '\Administrator\Controller\Content' not found in \libraries\src\CMS\Dispatcher\Dispatcher.php on line 185

### System information (as much as possible)

- Joomla 4
- PHP 5.6 - 7.0

@laoneo @yvesh

**Comment by franz-wohlkoenig** [comment]
can't confirm.
### System information
Joomla! 4.0.0-dev (nightly Build)
macOS Sierra, 10.12.4
Firefox 52 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
Must have been fixed in a recent merge. Closing
