### ISSUE TITLE
Admin menu items render horizontally and warning

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#15261]
### Steps to reproduce the issue
What am I doing wrong with setting up Admin menu? The admin menu items render horizontally and the following warning:
> The administrator menu MyAdmin does not contain - Menu Manager, Components Container. Click to turn on the menu recovery mode.

![admin-menu](https://cloud.githubusercontent.com/assets/368084/24969454/bb597846-1f65-11e7-9a8d-585f924da1b0.jpg)

Menu is selected for the position.
![admin-module](https://cloud.githubusercontent.com/assets/368084/24969462/c15dc0a8-1f65-11e7-8f9a-19ea6dfa7b49.jpg)

In Firefox, I get this dialog upon exiting from editing module settings.
![confirm](https://cloud.githubusercontent.com/assets/368084/24969701/766062ee-1f66-11e7-94cd-91e2ead914fb.jpg)

### Additional comments
Latest staging

**Comment by infograf768** [comment]
1. the warning tells you you have to create at minimum 3 types of admin menu items:
Modules Manager, Menu Manager and Components Container (That one is available in the System Links slider in the modal)
2. The menu items will not show horizontally if they are set as submenus.

Example:
![screen shot 2017-04-13 at 09 46 58](https://cloud.githubusercontent.com/assets/869724/24995204/364f12b8-202e-11e7-9f65-9d7f15040432.png)

**Comment by franz-wohlkoenig** [comment]
closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15261">issues.joomla.org/tracker/joomla-cms/15261</a>.</sub>

**Comment by uglyeoin** [comment]
Kind of annoying if you don't want that administrator to have access to the components.

**Comment by brianteeman** [comment]
@uglyeoin please dont comment on closed issues as hardly anyone will see them
If  you had searched you would also have seen that if you check the menu module options and you will be able to disable the message

**Comment by uglyeoin** [comment]
@brianteeman thanks I couldn't see it I will look again
