### ISSUE TITLE
Can't set renderLayout property of JFormField

### ISSUE THREAD

**Issue by waveywhite** [joomla/joomla-cms#15263]
### Steps to reproduce the issue

with a formfield object try:

$field->renderLayout = "adifferent.layout.path"

Where the file exists in the template "addifferent/layout/path.php"

### Expected result

Switch to the custom renderer

### Actual result

Error logged in JLog that the property is protected

### System information (as much as possible)

Joomla 3.6

### Additional comments

The problem is that renderLayout isn't included in the __set function of JFormField and so the parameter isn't writable. It would be very useful to set this parameter so that I can swap renderer for a specific context. What I am trying to do is use bootstrap form-inline styling for a specific view without upsetting existing form views.

Also, the renderLabelLayout should be writable.

**Comment by franz-wohlkoenig** [comment]
@waveywhite is this Issue also on latest Staging?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15263">issues.joomla.org/tracker/joomla-cms/15263</a>.</sub>

**Comment by ghost** [comment]
closed due lack of Response.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15263">issues.joomla.org/tracker/joomla-cms/15263</a>.</sub>
