### ISSUE TITLE
Read more and Custom Fields

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#15265]
### Steps to reproduce the issue
Create an article with the function read more.
Creatae a custom field After display
![screen shot 2017-04-12 at 19 08 23](https://issues.joomla.org/uploads/1/e2a6f6cd7ea93d13b53da9450e4cc4fa.jpg)

In the blog view, the custom field is displayed after read more.
![screen shot 2017-04-12 at 19 10 44](https://issues.joomla.org/uploads/1/cbb9176ec41332697277424a7f7a4b3a.jpg)

### Expected result
The custom fields must be displayed in the full article, not below Read more in view Blog, because there is a read more.

### Actual result
The custom fields are shown below Read more in view Blog

### System information (as much as possible)
Joomla 3.7 RC2

**Comment by Bakual** [comment]
Imho it depends on the use case where you would expect it to appear.
You can adjust that in a template override. Just move this line: https://github.com/joomla/joomla-cms/blob/staging/components/com_content/views/category/tmpl/blog_item.php#L82 above the readmore stuff in your override.

**Comment by Open2logic** [comment]
Ok for us, but and for the users of basic knowledge?, users whose profile is to enable or disable administration options.
I want that Joomla 3.7 has a good UX, people expect that under the read more nothing is shown, neither the custom fields, is logical, that is just my opinion, the new version Joomla must be usable for all people, better an option than a override.

Simply add in custom field options:
After title
Before Display
After Display
and.......After Redmore


Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15265">issues.joomla.org/tracker/joomla-cms/15265</a>.</sub>

**Comment by mbabker** [comment]
That's not feasible at the moment.  Those display options are based on plugin events that already exist in layouts.  There isn't a plugin event that can put content anywhere else into the layout without having to resort to parsing the rendered HTML and hoping the right spot is found.

**Comment by Open2logic** [comment]
I understand that at this moment any addition can be very complex.
All CCK components allow custom fields with control in view blog and view full article.
It would be very functional to control the custom fields after reading more.
Now, without that control the new functionality of custom fields will breaks the view blog, where users thought could add custom content, they not control the view blog. I do not think they like blogging websites, classifieds, directories and websites of news.
I hope to be wrong.

Thanks, very thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15265">issues.joomla.org/tracker/joomla-cms/15265</a>.</sub>

**Comment by Open2logic** [comment]
And adding a class to the blog view?

.custom-fields-hide > div > div > dl {
display: none;
}

Now the custom fields no show in blog view but show in full article.

A class to be executed when enabled from the options of the custom fields:
![screen shot 2017-04-13 at 00 13 31](https://issues.joomla.org/uploads/1/83a895945770d77d7398d3ae8a7685e6.jpg)

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15265">issues.joomla.org/tracker/joomla-cms/15265</a>.</sub>

**Comment by Bakual** [comment]
"After Readmore" would only make sense in the context of com_content. All other components don't have this feature. So that is not an option at all.
As said, it is a simple change in the view layout. That's what overrides exist for.
Where it appears depends a lot on the use case. For example comments should appear below the read more button.

**Comment by Open2logic** [comment]
You're right
Would have to be general options of the articles or in menu item for blog layout no of custom fields, Is more logical.
![screen shot 2017-04-13 at 06 57 01](https://issues.joomla.org/uploads/1/2bf54dc50dd2460687520cf82b5e7ec3.jpg)

If you try a blog view with many custom fields it's not very pretty, with few custom fields the look is a bit better because it is more symmetric, question of design, i know it, but for user experience, after read more, nothing should be shown.
I wish you could find some solution.

Thanks, very thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15265">issues.joomla.org/tracker/joomla-cms/15265</a>.</sub>

**Comment by brianteeman** [comment]
> For example comments should appear below the read more button.

As i stated before I would never expect to see anything below the readmore button. I cant think of any current example where this is the case.

**Comment by Bakual** [comment]
> As i stated before I would never expect to see anything below the readmore button. I cant think of any current example where this is the case.

It would be a simple PR if someone feels like it should always be on top of the readmore link.
The lines in question are linked above.

**Comment by brianteeman** [comment]
@bakual for me 
> If something is set to "after" then I expect it at the very end.of the article. Not at the end of the intro.
 so it would not appear on the blog view at all

**Comment by brianteeman** [comment]
Actually I realise that is not always the case as there may not be a readmore. ;)

See #15277 for a PR that moves the blog and features to before the readmore

**Comment by Bakual** [comment]
Closing since we have a PR
