### ISSUE TITLE
Add article form - Non multi-language websites

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#15264]
### Steps to reproduce the issue
Website no multi-language, only english installed.
Menu iten for add article, in the form the label language is enable
![screen shot 2017-04-12 at 18 23 57](https://issues.joomla.org/uploads/1/a8f884407aa06b16f50f9605afda8f8b.jpg)

### Expected result
Do not show the language tab

### Actual result
Has no sense
There is only one language, for usability and UX, it is not necessary to display the language tab
![screen shot 2017-04-12 at 18 28 26](https://issues.joomla.org/uploads/1/2fa8ec2f0112806b1ef0f1c8b4e84374.jpg)

### System information (as much as possible)

Joomla 3.7 RC2

### Additional comments

It would be interesting in Article options put an optino to hide this tab![screen shot 2017-04-12 at 18 33 50](https://issues.joomla.org/uploads/1/a05a8cef049fec2e7fed5e6bfe541fb7.jpg)

**Comment by infograf768** [comment]
We have discussed this matter multiple times since 1.6.

This is the situation: some people have used the Content Language column for other purposes than multilingual sites (wrong usage but they did...) Therefore we can't display or not the field depending on the multilingual settings (I.e. Language filter enabled or not).

Concerning your suggestion: there is no reason to create a parameter that would only deal with article or menu item, or whatever single type of item. 
It should be a global parameter for the whole site, separated from the language filter setting, as we also need to let a user prepare the change from a monolanguage site to a multingual site and therefore have full access to the language field all over J.
 
Obviously enabling the language filter plugin should make sure that this Global param is set.
 IMHO, this can only be done in 4.0

Let me also correct a common misunderstanding: one can have multiple languages installed and NOT use the site as multilingual. 
In that case, as a registered user may choose its language, the UI will be presented in the language chosen when the user is logged in.
Multilingual sites do not only deal with installed language but of the existence of Content Languages.

In your case, just delete the en-GB Content language and the language field will only propose All languages as default.

**Comment by Open2logic** [comment]
Hello, thanks for the info, i konw the confusion you are talking about ( multilanguage website  with multilanguage content with multilanguage profile), i develop some website with these functions, and users find it difficult to understand the possible situations of the website language of and the content language must be different, ok, we forgot hide the tab automatically recognizing that it is not a multi-language joomla website, but i'm talking about usability and UIX, i teach Joomla classes, one of the questions that all students ask me is:
¿ If the website only has one language because that tab is displayed?
No matter what All languages as default, the people do not understand because they can not hide that tab, they say "My website only has one language I do not want that tab".

The UIX is a question of percentages:
65% websites whit one language
25% websites multi-language
10% websites that the user can change their profile language

Yo say: In your case, just delete the en-GB Content language.
For me is very important the opinion of users, in my websites i have to hide the tab 80% of the time, with a simple code.

	if($this->params->def('Tab language') == HIDE){
				$js .= 'jQuery("#adminForm ul li a").each(function(){
						if(jQuery(this).attr("data-toggle") == "tab"){
							if(jQuery(this).attr("href") == "#language"){
								jQuery(this).parents("li").addClass("hidden");
								jQuery(this).parents("li").attr("style", "display:none");	
							}
						}
					});';			
			}

I only say:
¿Can this group to add a global configuration parameter for users to decide whether or not to display that tab?

It's not a matter of my case or your case, we all want the same, a Joomla 3.7 with the best UIX, a simple button for HIDE/SHOW the language tab in the general parameters.

In my case, in my joomla websites, i dont have that problem, i care about users, it is not logical to display this option in a single language website.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15264">issues.joomla.org/tracker/joomla-cms/15264</a>.</sub>

**Comment by mbabker** [comment]
The only suitable way for core to deal with hiding tabs would be to decide to display it based on the available data (i.e. if site isn't configured for multi-language, hide it, else show it).  A display parameter actually worsens user experience, imagine a case where you do have a multi-language site and the parameter is hidden because of someone else's awkward global configuration setting.

This is in part why a toggle for simple/advanced edit screens would never work all that well either.

**Comment by Open2logic** [comment]
But if the parameter is hidden and the website is multi-language, simply in admin show a warning and a link to this parameter:
_"Remember to activate this option in SHOW if your website is muliti language"_
 
Joomla uses this resource in other cases:
Notice and activate a plugin in the Redirects component.
Notice and activate a plugin in the functionality of install from JED, etc.
This way works for other functions and for activate one simple tab not?

For exemple, for the user is more complicated to learn to use the banner component to understand that on a multi-language website should activate the tab.

I do not share that explanation:
_This is in part why a toggle for simple/advanced edit screens would never work all that well either._
really?
The users always prefers to can to decide which shows, the users always prefers simpple viewws, the users do not want to see things that are not used, the users always think with basic logic: no multilanguage website, they do not understand why that option is displayed.

I think that we are thinking as programmers for advanced websites, not for the 75% of simples websites not multilanguage, this is called UIX. 
This is not a discussion, i'm by your side in this, but i speak for 7 years experience giving Joomla class, nobody wants this tab in website single language, whatever you decide i'll see it right, i simply point out what is not logical to try to help Joomla be the best.


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15264">issues.joomla.org/tracker/joomla-cms/15264</a>.</sub>

**Comment by mbabker** [comment]
I'm not saying we can't improve the logic behind displaying the fields.  But having a set of UI parameters to determine whether other UI parameters is to me a major UX issue.  You have to remember which parameters are enabled to be able to work with certain data.  Having a notification on all edit screens saying "enable this option to see X field" would also worsen UX for me.

The message in the redirects component relates to functionality, explicitly telling the user that without a dependency enabled that it lacks certain functionality.  It is a much different use case than a toggle to toggle toggles.

**Comment by Open2logic** [comment]
I understand it, although many users prefer to have the option of show/hide Language Tab, from your position that implies other things that must be taken into account, the 75% of website they would be happy with this option, but we do not want to bother to the other 25%, or worsen the UIX of another place of the Admin view.

I hope we can please everyone.

Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15264">issues.joomla.org/tracker/joomla-cms/15264</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@Open2logic should this Issue stay open?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15264">issues.joomla.org/tracker/joomla-cms/15264</a>.</sub>

**Comment by Open2logic** [comment]
It is low priority, but i think we have advanced in to see that if the website has a single language the tab should be hidden automatically, 
i imagine you would try joomla 4, i do not know. If the team believes it should be closed, for me ok.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15264">issues.joomla.org/tracker/joomla-cms/15264</a>.</sub>

**Comment by infograf768** [comment]
> It is low priority, but i think we have advanced in to see that if the website has a single language the tab should be hidden automatically,

Nope. Again, someone may prepare a multilingual site AND therefore need the Language field.

The only case where it could be automatically hidden is if there is no Content Languages at all. In this case the language should still be saved as ALL all over.

**Comment by khikmatullaev** [comment]
Should we close the issue?

**Comment by Open2logic** [comment]
I imagine that will take into account this improvement for the joomla 4
