### ISSUE TITLE
New Contact CSS Issue

### ISSUE THREAD

**Issue by essiele** [joomla/joomla-cms#15271]
### Steps to reproduce the issue

**Main Menu** > **Add Menu Item** > **Menu Item Type:** Single Contact > **Select Contact:** Create Contact button

### Expected result

Modal window with 3 columns, side by side, in a maximized browser window (1366 x 768).

### Actual result

**Overlapping columns when window.innerHeight > 1224px**

### System information (as much as possible)

OS Linux u
PHP 7.1.3
MySQLi 5.6.28-76.1-log
Caching Disabled
Gzip Disabled
Windows 7
Firefox 52.0.1

### Additional comments

![screen shot 2017-04-13 at 02 11 48](https://issues.joomla.org/uploads/1/3f5f1081f77c43f2709e697abaaf3045.jpg)

**Comment by franz-wohlkoenig** [comment]
Confirmed in Parts, got Issue at 1225px:
![bildschirmfoto 2017-04-13 um 08 36 44](https://cloud.githubusercontent.com/assets/8235763/24992987/853c53c2-2024-11e7-9170-ee7d3a8e5b83.JPG)
### System information
3.7.0-rc2 (nightly Build)
macOS Sierra, 10.12.4
Firefox 52 (64-bit), Chrome 57, Safari 10.1
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
Closed as we have a PR for testing see #17764
