### ISSUE TITLE
Error When Trying to Update from 3.7.0 RC1 to 3.7.0 RC2

### ISSUE THREAD

**Issue by essiele** [joomla/joomla-cms#15272]
### Steps to reproduce the issue

**Joomla Update** > **Upload & Update:** Browse button > Joomla_3.7.0-rc2-Release_Candidate-Update_Package.zip >
**Installation Method:** Write files directly > Upload & Install button

### Expected result

3.7.0 RC1 updated to 3.7.0 RC2

### Actual result

![screen shot 2017-04-13 at 02 23 18](https://issues.joomla.org/uploads/1/d323f9f1376659fc66fdbcb3a28ba26b.png)

### System information (as much as possible)

OS Linux u
PHP 7.1.3
MySQLi 5.6.28-76.1-log
Caching Disabled
Gzip Disabled
Windows 7
Firefox 52.0.1

**Comment by franz-wohlkoenig** [comment]
Update from Beta/rc to beta/rc isn't possible. You have to make a clean Install for beta/rc.

**Comment by franz-wohlkoenig** [comment]
closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15272">issues.joomla.org/tracker/joomla-cms/15272</a>.</sub>
