### ISSUE TITLE
Wrong redirect after editing and saving userprofile in frontend

### ISSUE THREAD

**Issue by Klipper** [joomla/joomla-cms#15270]
In Joomla 3.6.5 and before, when saving an edited userprofile in the frontendform I got redirected to the editform again. But now in Joomla 3.7rc2 after saving the form I get the userprofile page returned instead of the form I saved.

Why this is not OK: Users who edit their profile for adding 2 Factor Authorisation (2FA) to their profile are redirected after saving to their profilepage, but they need to go back to the bottom of the editform because they should save the 2FA 'One time emergency passwords'. Instead after saving the form there should be a autoredirect to the bottom of the editform so users can save the One time emergency passwords.

### Steps to reproduce the issue
Edit your userprofile on the frontend by adding 2FA to your profile. You now need to navigate back to the 'edit your profile' form and scroll to the bottom to see and save the generated 'One time emergency passwords'.

### Expected result
After saving 2FA to your profile you should immediately get the 'One time emergency passwords' in view, or at least you need to be redirected to the same page with the form so you can save the 'One time emergency passwords'

### Actual result
You get redirected to the profilepage, without the 'One time emergency passwords'.

### Additional comments
Would be very nice if the 'One time emergency passwords' could be showed on the profilepage too.

**Comment by brianteeman** [comment]
I just tried to add both a yubikey and a google 2fa to my user account using the edit profile form on the front end. In both cases After pressing submit at the bottom of the form I was presented with the one time emergency codes.

**Comment by Klipper** [comment]
Brian did you test with Joomla 3.6.5 or with Joomla 3.7rc2? 

I ask because in Joomla 3.6.5 this works correct. Or at least you arrive on the page containing the 'One time emergency passwords'!

I have test this on a fresh installation of Joomla 3.7rc2 and there you get redirected to the profile page, NOT to the edit profile formpage which contain the One time emergency passwords at the bottom.![screen shot 2017-04-13 at 19 44 24](https://issues.joomla.org/uploads/1/05c1035846e66de3b44cfe28b99f2c3a.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15270">issues.joomla.org/tracker/joomla-cms/15270</a>.</sub>

**Comment by brianteeman** [comment]
Rc2

**Comment by Klipper** [comment]
So this is very strange. You are redirected to the editprofile form and I get redirected to the profile page.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15270">issues.joomla.org/tracker/joomla-cms/15270</a>.</sub>

**Comment by brianteeman** [comment]
I didn't say i was redirected

**Comment by Klipper** [comment]
Also when I disable 2FA again in my profile and save the form I get redirected to the profile page.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15270">issues.joomla.org/tracker/joomla-cms/15270</a>.</sub>

**Comment by Klipper** [comment]
Brian, so you mean you stayed on the edit-profileform after saving the edit-profileform.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15270">issues.joomla.org/tracker/joomla-cms/15270</a>.</sub>

**Comment by brianteeman** [comment]
Ah - can you check this

1. Create a menu item "User profile"
2. Log in - select profile menu item and then edit
3. I think this does the redirect

now 
1. delete that menu item and empty the trash
2. Create a menu item "edit user profile"
3. log in and select the menu item
4. I think this way it doesnt redirect

**Comment by Klipper** [comment]
Ok I will try. Hold on.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15270">issues.joomla.org/tracker/joomla-cms/15270</a>.</sub>

**Comment by Klipper** [comment]
Brian, I followed your instructions as described. Cleared cache, trash, browsercache, restarted laptop with localhost, tried in Firefox and Google Chrome.
In all situations saving the edit profile form returns the profile page instead of the edit profile formpage containing the One time emergency passwords.
So this is really wierd...
I cannot find explanation why you get the correct page returned and I not.
BTW, I'm using php 7.1.2, mysql 5.7.11 and Apache 2.4.18 (Localhost)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15270">issues.joomla.org/tracker/joomla-cms/15270</a>.</sub>

**Comment by brianteeman** [comment]
![profile](https://cloud.githubusercontent.com/assets/1296369/25024283/30b420b6-2095-11e7-9f67-7c3e0fcf09d9.gif)

**Comment by Klipper** [comment]
Yes I belief you get return to the correct page, but with me in all tested situations I get redirected to the profile page instead to the edit-user-profile-form containing the One time emergency passwords.

value of the action attribute via menu-item: Edit user profile: /joomla37rc2/edit-profile?task=profile.save
value of the action attribute via button Edit Profile:  /joomla37rc2/using-joomla/extensions/components/users-component/user-profile?task=profile.save

returnpage in both forms is the same redirection. :-(<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15270">issues.joomla.org/tracker/joomla-cms/15270</a>.</sub>

**Comment by brianteeman** [comment]
@Klipper did you resolve this? No one else has reported this problem so I am going to close it at this time - it can always be reopened if required
