### ISSUE TITLE
[4.0] Error loading Control Panel

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#15273]
### Steps to reproduce the issue
After Update Yesterday on nightly Builds got Today:
![bildschirmfoto 2017-04-13 um 07 20 50](https://cloud.githubusercontent.com/assets/8235763/24991311/1aad59c0-201a-11e7-97b0-6091a6a112ca.JPG)
All Links like "New Article" work except "Edit Logged-In Users"
### System information
Joomla! 4.0.0-dev (nightly Build)
macOS Sierra, 10.12.4
Firefox 52 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by laoneo** [comment]
Is it a fresh install or an upgrade from J3?

**Comment by franz-wohlkoenig** [comment]
Fresh Install i update every Day with nightly Builds since a few Days.

**Comment by C-Lodder** [comment]
hmm, I've just fetched from upstream and I can't replicate the error

**Comment by franz-wohlkoenig** [comment]
so no Issue, will install a fresh J4
