### ISSUE TITLE
Can we add bulk upload option for every component via CSV file ?

### ISSUE THREAD

**Issue by bhaskarGit12345** [joomla/joomla-cms#15296]

**Comment by esedic** [comment]
You already have plenty of extensions doing this,

**Comment by franz-wohlkoenig** [comment]
closed as no Core-Issue. @bhaskarGit12345 please feel free to reopen for further Discussion.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15296">issues.joomla.org/tracker/joomla-cms/15296</a>.</sub>
