### ISSUE TITLE
Installed Languages Filter

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#15298]
### Steps to reproduce the issue
Install multiple languages and go to Languages->Installed

### Expected result
All columns are clickable as sort and display the direction icon
Filters in the dropdown match the column order and all have ascending and descending options

### Actual result
Native Title column does not have direction arrows
Native Title is at the end of the filters dropdown list and doesnt have ascending or descending options
<img width="1081" alt="screenshotr11-14-40" src="https://cloud.githubusercontent.com/assets/1296369/25040851/e54fcb92-2103-11e7-9330-bdf55d50f51f.png">

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.
### System information
3.7.0-rc2 (nightly Build)
macOS Sierra, 10.12.4
Firefox 52 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
Closed as we have a pr
