### ISSUE TITLE
An error has occurred while fetching the JSON data: HTTP 500 status code

### ISSUE THREAD

**Issue by nbjed** [joomla/joomla-cms#15295]
This happens when sending email. See screenshot below for better picture:
### Steps to reproduce the issue

![screen shot 2017-04-14 at 00 59 26](https://issues.joomla.org/uploads/1/01f7e26e1d21403c690c2587acdaa497.jpg)

**Comment by franz-wohlkoenig** [comment]
@nbjed can you give System Informations? Did Issue happen on a clean Install?

**Comment by nbjed** [comment]
![screen shot 2017-04-14 at 05 12 22](https://issues.joomla.org/uploads/1/90b7d6f87007d5be55ac725ec00f7e3f.jpg)![screen shot 2017-04-14 at 05 12 22](https://issues.joomla.org/uploads/1/7863f25ee6d212c2ac8680cb67b2917a.jpg)![screen shot 2017-04-14 at 05 12 23](https://issues.joomla.org/uploads/1/b21596af7e2a8c1b24802f924174d23b.jpg)

and there is ok in acymailin email running.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15295">issues.joomla.org/tracker/joomla-cms/15295</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Joomla 3.6.5
PHP 7.0.17<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15295">issues.joomla.org/tracker/joomla-cms/15295</a>.</sub>

**Comment by esedic** [comment]
What are your Mail Settings in Global Configuration?

**Comment by nbjed** [comment]
I have solve the problem. it's the acymailing module's bug.
thank you for your help.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15295">issues.joomla.org/tracker/joomla-cms/15295</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Closed as Issue not in Core.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15295">issues.joomla.org/tracker/joomla-cms/15295</a>.</sub>
