### ISSUE TITLE
Extensions: Install Languages - ALL

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#15290]
### Steps to reproduce the issue
 Extensions: Install Languages and set the filter to display ALL

### Expected result
All available languages will be listed with no pagination

### Actual result
No languages are displayed

### System information (as much as possible)
RC2

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.
### System information
3.7.0-rc2 (nightly Build)
macOS Sierra, 10.12.4
Firefox 52 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
Closed as we have a PR
