### ISSUE TITLE
Best UIX for websites without Tags

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#15306]
### Steps to reproduce the issue
We do not have tags created
In the article create form, in the tab Publishing, the Add Tags field is displayed.
The user can create tags in flight simply by typing a word tag, but the webmaster not want a tags page. which was created automatically and accessed by clicking from the article tag that the user created.

### Expected result
Do not see this field

### Actual result
t shows

### System information (as much as possible)
Joomla 3.7 RC2

### Additional comments
A simple button in general opcions for hide this tab would improve the UIX and better control for the website pages.

**Comment by mbabker** [comment]
Again, UI parameters to show/hide fields are not a good UX option.

Tags right now is tightly integrated into core and cannot be disabled or conditionally hidden on edit pages without a layout override.

**Comment by Open2logic** [comment]
Sorry, I do not open this type of request any more, i have now read your other comment.

**Comment by franz-wohlkoenig** [comment]
closed as Request is cleared.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15306">issues.joomla.org/tracker/joomla-cms/15306</a>.</sub>
