### ISSUE TITLE
[com_fields] Incorrect path to ajax-loader.gif when editing an article that has 1+ custom fields

### ISSUE THREAD

**Issue by nordmograph** [joomla/joomla-cms#15305]
### Steps to reproduce the issue
Create a com_content custom field and edit an article from the front end.

### Actual result
The browser console reports this error:
jquery.min.js?b2ad6c9…:3 GET http://localhost/media/jui/images/ajax-loader.gif 404 (Not Found)

### Expected result
Path misses (in my case) the j37  folder element as in: http://localhost/j37/media/jui/images/ajax-loader.gif

**Comment by AlexRed** [comment]
I can confirm in Chrome console<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15305">issues.joomla.org/tracker/joomla-cms/15305</a>.</sub>

**Comment by zero-24** [comment]
I guess it is about this: https://github.com/joomla/joomla-cms/blob/staging/media/system/js/core-uncompressed.js#L731 But I have no idea about JS Code. But I guess we need to set somewhere `data-basepath` as `body` attribute.

**Comment by zero-24** [comment]
cc @dgt41 proposed a solution.

**Comment by Bakual** [comment]
On a sidenote, does anyone know why we have the ajax-load.gif two times? Once in /media/jui/images and another one in /media/jui/img. We should probably use the one in /img and get rid of the other with J4 😄

**Comment by dgt41** [comment]
@Bakual I did that already ;)

**Comment by franz-wohlkoenig** [comment]
closed as having PR #15529<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15305">issues.joomla.org/tracker/joomla-cms/15305</a>.</sub>
