### ISSUE TITLE
Component com_fields not working

### ISSUE THREAD

**Issue by sshcli** [joomla/joomla-cms#15310]
### Steps to reproduce the issue
Upgrade from 3.6.5 to 3.7.0-rc3 

### Actual result
![error1](https://cloud.githubusercontent.com/assets/12942731/25050368/1fe5fa4a-2115-11e7-932f-6cc9545733ff.PNG)

![warning1](https://cloud.githubusercontent.com/assets/12942731/25050371/23eed49a-2115-11e7-8843-4986d9e88deb.PNG)

### System information (as much as possible)
Joomla! 3.7.0-rc3
PHP 7.1.3
MySQL 5.6.35

**Comment by zero-24** [comment]
@sshcli please double check that you updated from 3.6.5. The error looks like you updated from beta or other dev version.

**Comment by mbabker** [comment]
Rename the alias column in the `#__fields` table to name and you're good.  Closing as a known issue since maintenance team has elected to not support non-stable updates.

**Comment by zero-24** [comment]
This is why i have asked to double check if he direct updated from 3.6.5 if yes than this is a valid issue.

**Comment by sshcli** [comment]
> @zero-24 **said**: sshcli please double check that you updated from 3.6.5. The error looks like you updated from beta or other dev version.

I have tested with both:
Update from 3.6.5 and got the warning
Update from 3.7.0-rc1 and got the error




> @mbabker said: Rename the alias column in the #__fields table to name and you're good.

The "Alias" column doesn't exist in my installation. (Updated from 3.6.5 to 3.7.0-rc3)
I only have the column "name"
![name](https://cloud.githubusercontent.com/assets/12942731/25064488/0eebad84-21c9-11e7-82c8-4fd9532b1af2.PNG)


Maybe we are facing another bug, very similar but different

**Comment by zero-24** [comment]
I can not confirm this kind of errors on my installation. I have just tryed 3.6.5 -> 3.7rc3-dev

**Comment by sshcli** [comment]
> @mbabker said: Rename the alias column in the #__fields table to name and you're good. 

Yes, it works, Thanks

> @zero-24 said: I can not confirm this kind of errors on my installation. I have just tryed 3.6.5 -> 3.7rc3-dev

I think you could reproduce the issue by making a clean installation of 3.6.5 and then unzip 3.7.0-rc4 in the root directory of your server.
