### ISSUE TITLE
Content in backend only for my language profile

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#15318]
### Steps to reproduce the issue

Create a website with articles in various languages, diferent content for diferent countries.
Company with offices in various  countries, all employees have the language of your country in their user profile for administration and webite.

In the frontend, all employees see only the content of your country (plugin language filter/automatic language change), but in the backend, they see the content of the others countries.

Why in the frontend they only see content of language profile and in the backend not?
Ok, there is a filters, but are not very functional for sites with a lot of content in various languages.

### Expected result
If i have a language in my profile i should only see Joomla options and content of my language in frontend and in the backend.
In the profile would be to assign for see only the content of my language or all the content.

### Actual result
Employees see unnecessary content

### System information (as much as possible)
Joomla 3.7 Rc2

### Additional comments

First proposal)
Global parameter
![screen shot 2017-04-15 at 01 11 08](https://issues.joomla.org/uploads/1/f37ee026da8dd3a1e376d7155be3e368.jpg)

Second proposal)
Selection in the admin main menu
![screen shot 2017-04-15 at 01 29 45](https://issues.joomla.org/uploads/1/dda2ce6211b3d5854f3e3548ef7eb5d3.jpg)

**Comment by zero-24** [comment]
Hmm i think you can do that using a plugin that sets the filter per language automatically see the language dropdown in the search tools. But I don't think this needs be a core functionally.
As in the most cases the backend is the place where the user should see all content. Maybe (i have not checked it yet) you can also handle that via categories and permissions.

**Comment by mbabker** [comment]
The backend is a management interface that explicitly has a different behavior than the frontend.  The backend does not filter content based on language nor should this be a default behavior.

If you need to restrict access to content in the backend, you should be using the ACL system.

**Comment by infograf768** [comment]
@mbabker 
Out of curiosity, I tried to do it via batch and access levels (After creating some specific access levels for specific groups which are subgroups of Manager). But this dis not work as Edit/Create/etc. are common to Manager and its subgroups.

What could be useful (New Feature) is a batch function that would allow to set permissions to specific user groups for a group of items. It would not prevent to display the items (that still needs the Search Tools Filters), but it would prevent editing the ones a special group has no right to edit.

**Comment by brianteeman** [comment]
Acl should be the route to go to achieve this.   I see the use case but it's an edge case not a common scenario.
> . But this dis not work as Edit/Create/etc. are common to Manager and its subgroups
Surely you can set explicit permissions for each subgroup?

Also don't forget acl doesn't have to be hierarchical. It was a mistake we made to set the example acl as hierarchical.

Still not sure this idea is a good one as it will also effect things like associations

**Comment by infograf768** [comment]
> Surely you can set explicit permissions for each subgroup?

Not in this case: Edit/Create/etc. are not item specific, so the subgroup should have these implemented globally (indeed it does not have to be a subgroup for that) but there is no way to reach the said goal except doing it item per item (or, better with a new batch function).

**Comment by Open2logic** [comment]
We can not imagine it, we need a real demo with this case, as @mbabker has tried, (every time there is more websites with various languages), currently the proposal is not viable with acl, a international website of news, a social networks, this websites have exclusive content of the country, international news and shared content, is a question of usability not of permissions, in the example, for work convenience an employee with a selected language in the profile should be able to choose to see all the content or only that of his country, is important to understand that i'm talking about very big websites with lots of content, then i expose user experience:

In this caoture, the user perceives that the clear button erases the words written in the text area of ​​the search engine, IMPORTANT 
FILTERS NOW ARE HIDDEN.
![screen shot 2017-04-15 at 11 51 25](https://issues.joomla.org/uploads/1/6278bf3372a41d7a608864a74cfc74a3.jpg)



I do not know any search engine that has a button to CLEAR the written word, normaly the user simply selects the word and erase it with the delete button of the keyboard, or select the word and directly writes the new word, but ok, in admin the user is accustomed to use the CLEAR button for the words, but there is a problem, the CLEAR button also resets the filters, Why if the filters are not watching?, with the time experience the user starts using the filters, but then the user can not use the button to delete the word written in the search engine, also delete filters, ummmmm, it is not better to rename the button to CLEAR FILTERS and that only affects the filters, with this simple solution, you can set the filters you want and do not use the delete button to delete the written word.
Or if the button CLEAR currently restarts the filters, it should be displayed if the SAEARCH TOOLS tools button was clicked.

Solution: rename the buttom CLEAR to CLEAR FILTERS and move your position.

![screen shot 2017-04-15 at 11 49 11](https://issues.joomla.org/uploads/1/3faed9f6d3021b08a817919dcefabd32.jpg)

Now the user select filters for to work comfortably, now the user leaves his operational selection and he can hide the filters by clicking on the button SEARCJ TOOLS again.

Another solution would be to leave a selection fixed in the filters, for example with a check.
![screen shot 2017-04-15 at 11 56 52](https://issues.joomla.org/uploads/1/02fd311ec3bde4bfd19c2645b93116da.jpg)

But I think the error of usability is to have a only visible button that erases both, words and filters.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15318">issues.joomla.org/tracker/joomla-cms/15318</a>.</sub>

**Comment by brianteeman** [comment]
@coolcat-creations is this the same as you were asking me today?

**Comment by coolcat-creations** [comment]
@brianteeman yes quite similar. I thought more of having a language selected in the top toolbar so I can switch between language "profiles" - This feature would improve the Usability of multi language content a lot because you don´t have to filter over and over again and can focus on your stuff.

**Comment by brianteeman** [comment]
Closed for the reasons stated by @mbabker above

**Comment by coolcat-creations** [comment]
I would like to reopen as there are valid usecases. Someone wants to focus on editing the english site for example but is allowed to edit also everything else. Usability is poor when you have to filter everything all the time and if you see all the time all the other languages. I understand that you don't feel the pain in english speaking countries but if you would have to manage sites with 5+ languages and over 1000 Menuitems you would probably understand that need. Multilanguage is one of Joomlas USPs we have to do everything possible to make it even better.

**Comment by brianteeman** [comment]
I agree with Michael's comment and reasoning however of course if there is code to review that will achieve your aim I  will as always be happy to be one of the testers.

**Comment by coolcat-creations** [comment]
Can this issue then be opened to have a better possibility to find developers that can help to solve to improve usability on Multilanguage sites?

**Comment by brianteeman** [comment]
It was open for 18 months without any interest

**Comment by coolcat-creations** [comment]
Here is the interest. Still. After 18 Months.

**Comment by Open2logic** [comment]
I do not know any cms that works better than Joomla the multi-language and the acl.
I think we should strengthen the usability in the administration for multi-language sites.
Maybe in Joomla 4?
