### ISSUE TITLE
Update extension instead installs random language pack

### ISSUE THREAD

**Issue by fr56** [joomla/joomla-cms#15312]
### Steps to reproduce the issue
Choose an extension in the Extensions updater, then click Update.

### Expected result
The chosen extension gets updated.

### Actual result
A random Joomla language pack gets installed.

### System information (as much as possible)
Joomla 3.6.5
PHP 5.4.45

### Additional comments
This only happens from time to time, not frequently. And it happens with different extensions each time.  We have done Rebuild on Update Sites several times, doesn't help.

**Comment by zero-24** [comment]
hmm I have never expirienced something like that. Can you also confirm that on a clean install just using the extension you mention?

**Comment by fr56** [comment]
No, I can not confirm this on any other install. We have several sites, mostly for testing, and it's never happened there. 

And it's no particular extension, I have seen this when trying to update e.g. jQuery Easy, JDownloads, iCagenda and other extensions. After the random language pack is installed, updating the extension works fine. It's no big problem, I just uninstall the language pack, but definetly a bug.

The site has en-GB and nb-NO (Norwegian) languages installed, and it's "old" in the sense that it was migrated from a Joomla 1.5 site, and later upgraded from 2.5 to 3.5 and 3.6.

**Comment by zero-24** [comment]
Please send me a backup of the site the only reason i could think of is a 3rd Party Extension / Plugin that misuses an updater event. But i don't see any place where the core (without a broken 3rdparty extension) would do this.

**Comment by brianteeman** [comment]
I am closing this at this time as a non-core issue - it can always be re-opened if required
