### ISSUE TITLE
[com_fields] Category Blog: After Display is "displaying"

### ISSUE THREAD

**Issue by JUG-FN** [joomla/joomla-cms#15319]
**### Steps to reproduce the issue**

1. Menu Item Type: Category Blog (Columns: 4) created
2. New Fields: Editor with AFTER DISPLAY created
3. Front End: it Shows the Field in the blog overview

When I use "After title" or "Before Display": NO Field in Frontend, only in Artcle! (= OK)

**### Expected result**
When i use "AFTER DISPLAY" the field should also NO show in the blog overview, only in the article.

**### Actual result**
WRONG: The field show in the blog overview with "AFTER DISPLAY"
OK: The field don't show in the blog owerview with: "BEFORE DISPLAY" and "AFTER TITLE"

[screen shot 2017-04-15 at 05 40 05](https://issues.joomla.org/uploads/1/1070aa99ef9c838201a8c7078128730f.png)

**### System information (as much as possible)**
 
PHP Built On 	Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
Database Version 	5.5.54-0+deb7u2-log
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.1.3
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.7.0-rc2 Release Candidate [ Amani ] 12-April-2017 08:18 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0 

**### Additional comments**

**Comment by brianteeman** [comment]
I agree and it's also true for the featured view

We have three options. 

1. Move displayaftercontent to before the readmore as i did in another pr
2. Leave it to users to create an override that deletes the displayaftercontent from the blog and featured views
3. Change the code so that fields are only displayed on article views and not blog views. I am guessing this is what comment plugins do.

**Comment by ghost** [comment]
@brianteeman how to go on with this Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15319">issues.joomla.org/tracker/joomla-cms/15319</a>.</sub>

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 26th January 2018.
