### ISSUE TITLE
[4.0] Errors in user selection fields in several components

### ISSUE THREAD

**Issue by rjcf18** [joomla/joomla-cms#15325]
### Steps to reproduce the issue

Either go to Users -> User Notes -> New and select a User or go to Content -> Articles -> New,  go to the Publishing tab and Created By, click on the modal button and then try to select a User for the field. There is the same problem when selecting a user in a custom component. When the modal window for selecting a user comes up a couple of errors occur and another error after clicking on the user to select it and nothing happens forcing to close the modal window not allowing to choose a user.

In the next figure you can see above the black line the two errors when the modal window pops up and below the line the error when clicking the user.
![deepinscreenshot20170415220057](https://cloud.githubusercontent.com/assets/6710380/25066835/d100e8d4-2229-11e7-8c1c-360fef452f6c.png)

The next 3 screenshots's are to show the problem occurring while adding/editing an article, a user note and a record in an installed custom component. 

![deepinscreenshot20170415215625](https://cloud.githubusercontent.com/assets/6710380/25066845/fea97c10-2229-11e7-8aab-c146d3ad55e4.png)

![deepinscreenshot20170415215825](https://cloud.githubusercontent.com/assets/6710380/25066846/fec5543a-2229-11e7-9467-866970157443.png)

![deepinscreenshot20170415215934](https://cloud.githubusercontent.com/assets/6710380/25066847/ff1ef6a2-2229-11e7-8ed6-51f337aa9e22.png)

### Expected result

Selecting the user successfully in the modal window returning to the edit view with user already selected. 

### Actual result

Creates errors and doesn't allow choosing a user for the field in the add/edit view.

### System information (as much as possible)

Joomla! 4.0.0-dev
OS: Linux Deepin 15.3
Kernel: 4.4.0-3-deepin-amd64
Google Chrome: 56.0.2924.76 (64 bit)
PHP: 7.0.12-2
MySQLi 5.7.15-1

**Comment by C-Lodder** [comment]
Could you try reverting back to jQuery 2.2.4 and see if this fixes the issue?

**Comment by rjcf18** [comment]
It's just replacing the jquery.min.js in the media/vendor/jquery/js path with the 2.2.4 one right? I've tried your sugestion and the same problem occurs.

**Comment by C-Lodder** [comment]
ok no worries, just wanted to double check

**Comment by ghost** [comment]
@C-Lodder is this an issue for @dgt41?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15325">issues.joomla.org/tracker/joomla-cms/15325</a>.</sub>

**Comment by dgrammatiko** [comment]
The multiselect.js is not compatible with the changes for no user!

**Comment by ghost** [comment]
@rjcf18 can you please retest? I didn't get the Issue now.
### System information
4.0.0-dev
Multilanguage Site (4 Lang.) & Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by rjcf18** [comment]
I retested the issue both in firefox and chrome and it seems that the issue is gone entirely 👍 

![deepinscreenshot_select-area_20171212005720](https://user-images.githubusercontent.com/6710380/33861844-d54ed106-ded7-11e7-943f-37315e8c9f43.png)

![deepinscreenshot_select-area_20171212005742](https://user-images.githubusercontent.com/6710380/33861845-d5713c6e-ded7-11e7-87b2-ce1b19a3f571.png)

So I guess this issue can be closed since the problem is solved :)

### System information

Joomla! 4.0.0-dev
OS: Linux Deepin 15.4
Kernel: 4.9.0-deepin12-amd64
Google Chrome: 60.0.3112.78 (64 bit)
Firefox: 57.0.1 (64 bit)
PHP: 7.0.20-2
MySQLi 5.6.30-1

**Comment by ghost** [comment]
closed as stated above.

Thanks for re-Test @rjcf18<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15325">issues.joomla.org/tracker/joomla-cms/15325</a>.</sub>

**Comment by rjcf18** [comment]
No problem ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15325">issues.joomla.org/tracker/joomla-cms/15325</a>.</sub>
