### ISSUE TITLE
A filter outside of the Search tools

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#15335]
### Steps to reproduce the issue
In the modules view
There is a filter that shows Site
![screen shot 2017-04-16 at 18 38 42](https://issues.joomla.org/uploads/1/ad94a5ea89e8c3598bc190d543258be9.jpg)

### Expected result
In a view (users or articles), when you use Search tools, Joomla memorizes the filters.
Activate in the Articles view the Access filter (For example put it in register), then go to another place of the administration, you return to the article view and the filter is still active, this is ok, show the items for regiiter access.
But in the module view the behavior is different because there is a filter outside, the filter SITE / ADMINISTRATOR
Activate in the MODULES SITE view the Access filter (For example put it in register), now change the SITE filter and put it in ADMINISTRATOR, but here you want to see the special items, change it en the Search tools.
We return to put the filter to SITE and the items for registered users are no longer displayed, they are shown for the specials. And if we clear the filters for the SITE view, it affects the ADMINISTRATOR view.

![screen shot 2017-04-16 at 18 42 43](https://issues.joomla.org/uploads/1/fbe5d9f1cbce27eaabe2f5bfdc7ef107.jpg)

### Actual result
SITE / ADMINISTRATOR Is not a separate view is a filter and should be seen when you click Search tools

![screen shot 2017-04-16 at 18 43 55](https://issues.joomla.org/uploads/1/f573098f25821a4d4f7fa76e1dab5bb0.jpg)

### System information (as much as possible)
Joomla 3.7 Rc2

### Additional comments
Although displayed in the Search tools, given the importance of this button (SITE / ADMINISTRATOR) could be displayed with another design or color

**Comment by Open2logic** [comment]
As additional information in this scenario the SITE / ADMIN filter are in the Search Tools.

Extensions / Manage
![screen shot 2017-04-17 at 19 26 42](https://issues.joomla.org/uploads/1/1f94714acc3fb50d828c04a07e2607e7.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15335">issues.joomla.org/tracker/joomla-cms/15335</a>.</sub>

**Comment by brianteeman** [comment]
You are trying to compare two things that are not the same

**Comment by Open2logic** [comment]
I am looking to unify behaviors and views, if i see something strange i tell you, then you value it, all the cases look the same for me, a list of admin items and a list of site items, but i repear, i inform you if something seems strange to me, i understand that in this case it may be different.

thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15335">issues.joomla.org/tracker/joomla-cms/15335</a>.</sub>
