### ISSUE TITLE
Unnecessary statement of the edit button

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#15333]
### Steps to reproduce the issue
In the Article view select several articles by checkbox
![screen shot 2017-04-16 at 17 05 24](https://issues.joomla.org/uploads/1/f15213a95c6da6b118c160c0fa20600b.jpg)

Then click in the Edit button.

### Expected result
If the interface shows an edit button in a list with check, 
Can I edit several articles at once?

### Actual result
Logicaly only opens the first selected item

### System information (as much as possible)
Joomla 3.7 Rc2

### Additional comments
The edit button should not be
Nobody click in the check article and then gives the edit button
To edit an article everybody clicks in the article title
Rename the column named Title by Title / Edit

Are too many buttons and options visibles.

**Comment by AlexRed** [comment]
For me, like the "popup message" if you do not select articles but use the edit button, is necessary a "popup message" if you select more than one articles an use the edit button.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15333">issues.joomla.org/tracker/joomla-cms/15333</a>.</sub>

**Comment by yasirunilan** [comment]
If you select more than one article isn't it better to disable the "Edit" button?

**Comment by brianteeman** [comment]
This is a long standing issue. In the same way if you select an item you can still use the new button and if you do not have any items selected then the other buttons are not disabled. And there are other places where a button is enabled but doesnt work if you have more than one item checked. Every attempt to change the UI for this has been rejected in the past sadly

**Comment by Open2logic** [comment]
A resource in usability is group by design similar behaviors,  if NEW and EDIT can not act with several selections of items and the rest of the buttons yes do it, 
Change the design of the EDIT button.

![screen shot 2017-04-17 at 18 17 44](https://issues.joomla.org/uploads/1/b40eb476dcacafe283a78ede645cdcdd.png)

In this way the user understands that the gray buttons behave similarly.

But my vote is to remove the EDIT button.
Nobody click in the check item and then click in the EDIT button, all people clic in the item title.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15333">issues.joomla.org/tracker/joomla-cms/15333</a>.</sub>

**Comment by brianteeman** [comment]
> Nobody click in the check item and then click in the EDIT button, all people clic in the item title.

You have no way of being qualified or to posses the knowledge to make such an absolute statement

**Comment by Open2logic** [comment]
Love Joomla is a great qualification, but we all want in Joomla the best UIX, all people or the 80% of the people in terms of usability is the same, obviously i speak in absolute terms (exaggeratedly), there is a lot of expectation by Joomla 3.7 for UIX and the Custom fields, sorry for my way of expressing myself, but Brian, we want the same.

I ask you not to value as i express, the important is identify an improvement, i do not speak any English and the translator of Google is a sucks.
Sorry another time for my exaggeration.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15333">issues.joomla.org/tracker/joomla-cms/15333</a>.</sub>

**Comment by brianteeman** [comment]
Closed as this has been addressed in J4
