### ISSUE TITLE
Different titles in the same circumstances

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#15334]
### Steps to reproduce the issue
Admin menu,
There are buttons that change your name: Users, Menus, Content & Extensions

### Expected result
Same criteria, usability, cognitive learning of the interface for the users

This is logial:
![screen shot 2017-04-16 at 17 42 36](https://issues.joomla.org/uploads/1/4361336979a15c684287af79ce12132a.jpg)
![screen shot 2017-04-16 at 17 42 39](https://issues.joomla.org/uploads/1/5a19c28be9a21ce37d006077aa78a725.jpg)
![screen shot 2017-04-16 at 17 43 44](https://issues.joomla.org/uploads/1/b61db6b552316d0b82aa7bc45bfc9413.jpg)
![screen shot 2017-04-16 at 17 43 58](https://issues.joomla.org/uploads/1/1539d1f104d1b4518fc45091cde9a669.jpg)

### Actual result
![screen shot 2017-04-16 at 17 42 36](https://issues.joomla.org/uploads/1/4361336979a15c684287af79ce12132a.jpg)
![screen shot 2017-04-16 at 17 42 39](https://issues.joomla.org/uploads/1/5a19c28be9a21ce37d006077aa78a725.jpg)
![screen shot 2017-04-16 at 17 42 41](https://issues.joomla.org/uploads/1/93e4e77bb0e5f2deca19da4e433545f3.jpg)
![screen shot 2017-04-16 at 17 42 43](https://issues.joomla.org/uploads/1/cff38e26ade318540faedbacc74c903e.jpg)

### System information (as much as possible)
Joomla 3.7 Rc2

### Additional comments
The same situation

Now
![screen shot 2017-04-16 at 17 51 41](https://issues.joomla.org/uploads/1/f45762c35cf08458f969148b16ccdee0.jpg)
![screen shot 2017-04-16 at 17 51 50](https://issues.joomla.org/uploads/1/a7f92f59f9fb97f5565c6a476a174208.jpg)
![screen shot 2017-04-16 at 17 52 07](https://issues.joomla.org/uploads/1/30b29f0c53ee0cc8ad449bc47fe7c0ad.jpg)
![screen shot 2017-04-16 at 17 52 16](https://issues.joomla.org/uploads/1/adc0325d546819d6e84680e6058daf83.jpg)

The logical
![screen shot 2017-04-16 at 17 51 41](https://issues.joomla.org/uploads/1/f45762c35cf08458f969148b16ccdee0.jpg)
![screen shot 2017-04-16 at 17 51 50](https://issues.joomla.org/uploads/1/a7f92f59f9fb97f5565c6a476a174208.jpg)
![screen shot 2017-04-16 at 17 53 37](https://issues.joomla.org/uploads/1/8559ca0f7e566b6585d633dd79bcade0.jpg)
![screen shot 2017-04-16 at 17 52 16](https://issues.joomla.org/uploads/1/adc0325d546819d6e84680e6058daf83.jpg)

**Comment by mbabker** [comment]
This is just confusing IMO.

**Comment by Open2logic** [comment]
For everything i'm seeing does not seem like a IMO problem, is a order problem.
Amin menu / extensions

The capture that is proposed as correct copies its order and logic of the other buttons of the admin menu

![screen shot 2017-04-17 at 22 16 39](https://issues.joomla.org/uploads/1/36bfd7b07b575894df7dd88b3d3b2125.png)


![screen shot 2017-04-17 at 22 16 54](https://issues.joomla.org/uploads/1/afc2f3d08c05855d2e1df25fd17785a2.png)


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15334">issues.joomla.org/tracker/joomla-cms/15334</a>.</sub>

**Comment by Open2logic** [comment]
The user can learn that in most cases the first button is Manage (like in Users, Menus, Content or Extensions), and the filters can always are the last buttons, i consider that the line of separation also helps.

Now is diferent order, and it seems that filters are for user notes
![screen shot 2017-04-17 at 22 40 04](https://issues.joomla.org/uploads/1/35dbd361c831f44bf4ce5514669dc3f9.png)

![screen shot 2017-04-17 at 22 40 23](https://issues.joomla.org/uploads/1/e44b400ba472032673ae276510896a9a.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15334">issues.joomla.org/tracker/joomla-cms/15334</a>.</sub>

**Comment by Open2logic** [comment]
Sorry put filters but should put fields<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15334">issues.joomla.org/tracker/joomla-cms/15334</a>.</sub>

**Comment by Open2logic** [comment]
If I do not open the side slider I do not know what to do in the Extension view
![screen shot 2017-04-17 at 23 03 36](https://issues.joomla.org/uploads/1/58189f6f6914aff6eeadf4fee52d15e1.png)





The user's cognitive learning shows that at first view he can add a new 
![screen shot 2017-04-17 at 23 10 35](https://issues.joomla.org/uploads/1/cc359cf4bf16a0b4c68b87066bb1d433.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15334">issues.joomla.org/tracker/joomla-cms/15334</a>.</sub>

**Comment by Open2logic** [comment]
With renaming buttons and reordering, I think it increases usability, but is only an opinion.

In this capture.
Is the buttom named Database only for view the database of the extensoions or is for view the database of the Joomla (user, content, extensions, etc.) and the Warning button is not for systems alerts?

![screen shot 2017-04-18 at 13 18 27](https://issues.joomla.org/uploads/1/9fec7433bdd257f5aaee7514d7e30e70.jpg)

And tht "Install languages" should be a son of the parent Language and rename it to "Install· like the rest of admin
![screen shot 2017-04-18 at 13 29 37](https://issues.joomla.org/uploads/1/1ea9895b8918b3d6c1505c59f6bdc43a.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15334">issues.joomla.org/tracker/joomla-cms/15334</a>.</sub>

**Comment by Open2logic** [comment]
mbabker 

I close this issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15334">issues.joomla.org/tracker/joomla-cms/15334</a>.</sub>

**Comment by zero-24** [comment]
@Open2logic i have done a smal peace ot of this: https://github.com/joomla/joomla-cms/pull/15468 Please test. I'm not sure about the other changes. Maybe this can be done with 4.0 as this would be a massive UI change.

**Comment by Open2logic** [comment]
@zero-24 , It is true that there are many changes, but they are very simple, and obvious affect directly usability, but, Why wait until 4.0?.
Many small things make the user not have a good experience, and the people expect more usability in 3.7

Thanks for advancing in one point.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15334">issues.joomla.org/tracker/joomla-cms/15334</a>.</sub>

**Comment by zero-24** [comment]
I'm thinking about the changes you suggestes as this is a very good known UI. If you want do do something like this for a client you can do this using the new admin menu feature. But i personlay don't see this in 3.x this is the reason i mention joomla 4 as there is allreday a new admin template planed.

**Comment by brianteeman** [comment]
I am closing this for the reasons stated above.
