### ISSUE TITLE
[4.0] Chosen is broken

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#15338]
### Steps to reproduce the issue
Look at dropdowns that currently use chosen in J4 (e.g. module position selection, category selection)

### Expected result
They work

### Actual result
You can't see the dropdown and selecting it renders it invisible

### Additional comments
We are investigating https://github.com/jshjohnson/Choices as an alternative to chosen (given Chosen have indicated with their latest release 1.7.0 they will not support new features and we don't want to have to core hack the extra options support in which https://github.com/jshjohnson/Choices/pull/143 will give support for) however at this time the existing chosen options should continue to work until a decision is firmly made on Choices

**Comment by Fedik** [comment]
> We are investigating https://github.com/jshjohnson/Choices as an alternative to chosen

what about [Select2](https://select2.github.io/)?
the Choices looks new, and no guarantee it will live long 😄

**Comment by wilsonge** [comment]
Honestly the decision on what to use is down to @dgt41 , @C-Lodder and @ciar4n :) I'm just writing it for completeness if someone wants to work on the issue

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/15372

**Comment by C-Lodder** [comment]
@franz-wohlkoenig - could you close this please?

**Comment by franz-wohlkoenig** [comment]
closed as having PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15338">issues.joomla.org/tracker/joomla-cms/15338</a>.</sub>
