### ISSUE TITLE
[4.0] Contact: User don't get select in Modal-Windows

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#15349]
### Steps to reproduce the issue
Create new Contact, linked User in Modal-Window don't get select.
### System information
Joomla! 4.0.0-dev (nightly Build)
macOS Sierra, 10.12.4
Firefox 52 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by joomdonation** [comment]
I guess it is the same with this one https://github.com/joomla/joomla-cms/issues/15325

**Comment by rjcf18** [comment]
Yep I've observed that same problem regarding user selection in those modal windows.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15349">issues.joomla.org/tracker/joomla-cms/15349</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
closed as knowing Issue #15325<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15349">issues.joomla.org/tracker/joomla-cms/15349</a>.</sub>
