### ISSUE TITLE
[4.0] [RFC] Single contact - Remove 'Display Options'

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#15345]
Personally I think we can remove the multiple display options for single contacts (Plain, Sliders & tabs) and just have a single plain contact form users can use. 

- One less option
- Accounting for the 3 displays means styling the contact form is quite restrictive
- If such options exist they should be towards a more functional 'plain' contact form 
- Tabs and sliders in contacts forms is somewhat unconventional. I'm sure 3PD will cater for the few users wanting them.

**Comment by brianteeman** [comment]
iirc the argument for them is particularly on a site that is using com_contacts to display full contact details and not just as a contact form.

Think of a large organisation with lots of contacts that you want to display as a staff directory. By moving the form part into a slider or tab you are emphasising the details and not the form. 

Anyway that was the logic behind it

**Comment by ciar4n** [comment]
> Think of a large organisation with lots of contacts that you want to display as a staff directory.

I guess we would have to question how common is this the case. My guess would be not very often. At least if a user is thinking about a staff directory they are more likely to go looking elsewhere (3rd party directory ext) rather than using com_contacts. It seems to be currently caught in a bit of a no mans land.

Looking at recent survey results on how often com_contacts is used...

Never: 36%
Occasionally: 41%
Frequently: 23%

Considering most sites would have a contact form, com_contacts use seems rather low.

**Comment by brianteeman** [comment]
Why would you go elsewhere when the core component does the job perfectly.

**Comment by ciar4n** [comment]
A fair point.

I just feel using the 3 displays currently shoe horns the layout. When creating a template, you have to cater for the 3 potential displays which restricts what can be done with the layout.

**Comment by ciar4n** [comment]
If removing the options is not preferred could we give each option its own layout? So each option can be considered/overridden separately?

**Comment by C-Lodder** [comment]
IMO providing 3 options for this is silly. Tabs or sliders? Cmon...

**Comment by brianteeman** [comment]
> If removing the options is not preferred could we give each option its own layout? So each option can be considered/overridden separately?

that seems a good option and serves as an example of having multiple layouts available for the same view

**Comment by mbabker** [comment]
👍 to refactoring to separate layouts versus having an excess of conditionals in one layout.

**Comment by ciar4n** [comment]
PR created.. #23829
