### ISSUE TITLE
Hidden menu

### ISSUE THREAD

**Issue by ArjanRoosemalen** [joomla/joomla-cms#15343]
On my own website, roosemalen.nl, I work with a hidden menu for the blog posts. Now I have installed the last test version of Joomla and now my hidden not link work more if you click on the blog view on the title of the "Read more".

Then behind the right place suddenly 114-blog/687-aow-betaalbaar-houden example. The entire address is roosemalen.nl/aow-betaalbaar/114-blog/687-aow-betaalbaar-houden while referring roosemalen.nl/aow-betaalbaar my set menu item.

Sorry for my bad english but I'm just a simple Dutchman

**Comment by ArjanRoosemalen** [comment]
PHP 7.1 & Mysql 5.7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15343">issues.joomla.org/tracker/joomla-cms/15343</a>.</sub>

**Comment by ssnobben** [comment]
" the last test version of Joomla" by latest version do you mean Joomla 3.7 rc2 or what version of your Joomla is the "latest" version with hidden menu option?

**Comment by ArjanRoosemalen** [comment]
Version 3.7 rc2

**Comment by franz-wohlkoenig** [comment]
@ArjanRoosemalen Can't confirm: Set an Menu `Single Contact` in Tab `Link Type` > `Display in Menus` on `No`. Menu isn't shown in Frontend, but Link (click on "Author" in Article on Frontend) works.

**Comment by ArjanRoosemalen** [comment]
![new_menu_item](https://cloud.githubusercontent.com/assets/27668547/25091125/bd941500-2387-11e7-9d19-19b79716451a.jpg)
There is no button for me not to show the item menu. See illustration.
For the update to 3.7 rc1 or two it all worked well.

**Comment by franz-wohlkoenig** [comment]
@ArjanRoosemalen set Menu-item-type you need. Click Tab `Link Type` (Screenshot shows `Linktype`).

**Comment by ArjanRoosemalen** [comment]
I have now done but the problem remains that the category and product id still get shown once in the address bar of the browser when you click on the title of the article or the "Read more" link.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15343">issues.joomla.org/tracker/joomla-cms/15343</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Test on fresh Install 3.7-rc2 + Sample Sites:

- Blog-Menu "index.php/en/park-blog"
- Article-Url: "index.php/en/park-blog/17-first-blog-post"

Same Urls if set Menu on "Display in Menu: No".

As far as i understand you got no Article-ID in this Setting?

**Comment by ArjanRoosemalen** [comment]
Maybe images make clear what I mean.
![menu-1](https://cloud.githubusercontent.com/assets/27668547/25116051/9fcb34da-240a-11e7-9fb5-f4db0e62ced6.jpg)
![menu-2](https://cloud.githubusercontent.com/assets/27668547/25116058/a4fe74e4-240a-11e7-80a6-661e68214c42.jpg)
![menu-3](https://cloud.githubusercontent.com/assets/27668547/25116062/a864ae3c-240a-11e7-9f82-ba1a8fc1e61e.jpg)
![menu-4](https://cloud.githubusercontent.com/assets/27668547/25116065/ac8ee770-240a-11e7-97db-9eb4afb9e70d.jpg)
![menu-5](https://cloud.githubusercontent.com/assets/27668547/25116068/b0533b0e-240a-11e7-8b1b-a0389ad8bfb2.jpg)
![menu-6](https://cloud.githubusercontent.com/assets/27668547/25116072/b44e4c1c-240a-11e7-8bb5-35ba597eee3c.jpg)

**Comment by Pinkeltje** [comment]
[http://yndidev.tk/37/growers](url) 
Test on fresh Install 3.7-rc2 + Sample Sites. Only changed menu-item to "hide" and inserted readmore in Happy Orange Orchard article. Link to hidden menu-item type category-blog in article seems to be ok. Link to single article (also hidden menu-item) appends article id.
![yndi 20170418 - 134006](https://cloud.githubusercontent.com/assets/8941310/25129145/120a838e-243d-11e7-81cf-462fd2ff783b.jpg)

**Comment by franz-wohlkoenig** [comment]
@Pinkeltje so you confirm the Issue?

**Comment by Pinkeltje** [comment]
Yes I do confirm the issue.

**Comment by franz-wohlkoenig** [comment]
thanks @Pinkeltje set Status at issue Tracker on "Confirmed".

**Comment by Leen29** [comment]
Hello,
Hey
I use latest Joomla version, 3.7.0-dev. 
![numinurl](https://cloud.githubusercontent.com/assets/17086048/25265469/96a3d2b2-266d-11e7-977f-7640b961363f.JPG)
And using the read more button in arikel
the same problem

**Comment by joo7** [comment]
I tried to reproduce the issue but get 404 on demo-site when setting "Use URL Rewriting" to "Yes": 

on https://demo.joomla.org/ click "Launch Test Drive"
click Content-New Article, create article (myarticle) with read-on, create category on the fly, save&close.
click menu-item, create new menu-item type category-block, select created category, select MAIN menu, save&close.
click Menues-Manage-Add New Menu, create new menu, save&close.
click menu-item, create new menu-item type single Article, select created Article (myarticle), select created menu (hidden, no module), save&close.

test frontend, clicking read-on: no item-id in url: http://j2950aac101.demojoomla.com/index.php/myarticle
=> ok, cannot confirm issue

click Configuration-Global, set Use URL Rewriting to "Yes", save&close
test frontend, clicking new menu-item in main-menu (type category-block): 404
=> different issue, cannot further investigate this issue

**Comment by ghost** [comment]
@ArjanRoosemalen have you test "Display in Menu" in Menu-Tab "Link-Type"?

**Comment by brianteeman** [comment]
Closed as a site setup issue and not a core bug
