### ISSUE TITLE
[4.0] UI- No space between the menu item name and the description

### ISSUE THREAD

**Issue by yasirunilan** [joomla/joomla-cms#15340]
### Steps to reproduce the issue
Go to the menu Menus -> Manage -> Menu items
Click on the new menu item button. A new window will open up.  There is a select field labeled as "Menu Item Type". Click on it. new modal will open up. Select one from the listed menu types.

### Expected result
![menu item space new](https://cloud.githubusercontent.com/assets/9814784/25079272/94f1b60e-2358-11e7-81a6-626bb16894d1.PNG)

### Actual result
![menu item space old](https://cloud.githubusercontent.com/assets/9814784/25079276/9cc15a9c-2358-11e7-9ff2-166ba9b461e4.PNG)

### System information (as much as possible)
Joomla! 4.0.0-dev
Windows 10
Chrome 57.0.2987.110 (64-bit)
PHP 5.6

**Comment by franz-wohlkoenig** [comment]
closed as having PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15340">issues.joomla.org/tracker/joomla-cms/15340</a>.</sub>
