### ISSUE TITLE
Tooltip is not displaying properly.

### ISSUE THREAD

**Issue by RonakParmar** [joomla/joomla-cms#15342]
### Steps to reproduce the issue
Joomla version 4
Screen Resolution: 1366*768 (16:9)
Goto->Article new/edit page->mouse hover on category dropdown.
See the category tooltip is not displaying correctly.

### Expected result
Display tooltip correctly.

### Actual result
Not able to read full tooltip text, because going out of screen.

### System information (as much as possible)
PHP Version 5.6.30
Joomla! 4.0.0-dev
Screen Resolution: 1366*768 (16:9)
![screen shot 2017-04-17 at 06 16 08](https://issues.joomla.org/uploads/1/13ea79b51c638c3c5f186c5b1b061afc.png)

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.
### System information
Joomla! 4.0.0-dev (nightly Build)
macOS Sierra, 10.12.4
Firefox 52 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/15377

**Comment by franz-wohlkoenig** [comment]
closed as havin PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15342">issues.joomla.org/tracker/joomla-cms/15342</a>.</sub>
