### ISSUE TITLE
[4.0] "Savin Tag"-Error

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#15347]
### Steps to reproduce the issue
After created an Tag in Article-View and "Save"-Article get:
![f3ffd2fc-235d-11e7-8639-b386738eed8e](https://cloud.githubusercontent.com/assets/8235763/25085659/9eb35746-2363-11e7-9305-5551a16ea2f3.JPG)
### System information
Joomla! 4.0.0-dev (nightly Build)
macOS Sierra, 10.12.4
Firefox 52 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by wilsonge** [comment]
Fixed with https://github.com/joomla/joomla-cms/commit/264b8caf04c415cff5f8dcc72a46d27abd892c23
