### ISSUE TITLE
Gallery Field not visible while creating New custom Field

### ISSUE THREAD

**Issue by webmatrix** [joomla/joomla-cms#15351]
### Steps to reproduce the issue
1) Installed Joomla_3.7.0-beta4-Beta-Full_Package on local install wampserver
2) Updated to Joomla 3.7 RC2
3) When you create New field in Content>Fields>New

### Expected result
Gallery(type) in dropdown list of Type.

### Actual result
Gallery type in dropdown list.

### System information (as much as possible)
Database Version	5.7.9
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.16
Web Server	Apache/2.4.17 (Win64) PHP/5.6.16
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.7.0-rc2 Release Candidate [ Amani ] 12-April-2017 08:18 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

### Additional comments
I don't find it in Plugins folder. Is it deprecated?
Thanks.

**Comment by Bakual** [comment]
It has been removed. I saved some of the work in my repo here: https://github.com/Bakual/CustomFieldGallery

**Comment by shoulders** [comment]
Thanks for the save Bakual. This is the biggest feature I can think of for joomla, native article galleries, perhaps with editing like simple image gallery.
