### ISSUE TITLE
[4.0] UI - Tool tip popup not fully visible

### ISSUE THREAD

**Issue by yasirunilan** [joomla/joomla-cms#15356]
### Steps to reproduce the issue
Go to the menu Menus -> Manage -> Menu items
There is a input field labeled as "Alias" hover over the label.

### Expected result
Popup tool tip should be clearly visible

### Actual result
Half of the tool tip is not visible
![18009884_1343885905668538_343841105_n](https://cloud.githubusercontent.com/assets/9814784/25092894/5ce1acd8-23ad-11e7-9859-a1ca570c2b9f.jpg)

### System information (as much as possible)

Joomla! 4.0.0-dev
Windows 10
Chrome 57.0.2987.110 (64-bit)
PHP 5.6

**Comment by franz-wohlkoenig** [comment]
isn't it same like #15342?

**Comment by yasirunilan** [comment]
Yeah didn't saw that issue. this can be closed.

**Comment by franz-wohlkoenig** [comment]
closed as known Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15356">issues.joomla.org/tracker/joomla-cms/15356</a>.</sub>
