### ISSUE TITLE
[4.0] Rename "Bottom-a"- in "Bottom-b"-Module

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#15353]
### Steps to reproduce the issue
Module of Sample Site-Installation in Position "bottom-b" are named "Bottom-a", should named "Bottom-b":
![bildschirmfoto 2017-04-17 um 14 34 39](https://cloud.githubusercontent.com/assets/8235763/25089127/a404f9bc-237b-11e7-962f-298994375b6e.JPG)
### System information
Joomla! 4.0.0-dev (nightly Build)
macOS Sierra, 10.12.4
Firefox 52 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/15366

**Comment by brianteeman** [comment]
closed as we have a PR
