### ISSUE TITLE
[com_fields] Mail custom fields disabled on frontend

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#15355]
### Steps to reproduce the issue
Create a single contact menu item
Go to  Components > Contacts > Contacts
Create a new contact
Click Fields
Click Mail from the dropdown
Create a new field
Go to the frontentd
Click the menu item
Click Contact Form

### Expected result
Custom fields to be editable.

### Actual result
![mail-custom-field](https://cloud.githubusercontent.com/assets/368084/25092229/946590aa-2341-11e7-97f3-ead3c05ff271.jpg)

### System information (as much as possible)
Latest staging version

**Comment by brianteeman** [comment]
what are the permissions for that field

**Comment by Quy** [comment]
Yes, it was a permission issue. Thanks.
