### ISSUE TITLE
[4.0] `Published`, `Trashed` isn't saved in Article-View

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#15350]
### Steps to reproduce the issue
Tests using Sample Sites.

#### Unpublished

- Open Article:
Change Status from `Published` to `Unpublished` is in Dropdown-Field saved, but:
![bildschirmfoto 2017-04-17 um 13 13 42](https://cloud.githubusercontent.com/assets/8235763/25087500/b547b64e-236f-11e7-92c6-ca2cdedab35a.JPG)
Reopen Article, Status is `Published`.
- List of Articles:
Click on green Symbol/red Symbol work.

#### Delete

- Open Article:
Change Status from `Published` to `Trashed` is in Dropdown-Field saved, but:
![bildschirmfoto 2017-04-17 um 13 13 42](https://cloud.githubusercontent.com/assets/8235763/25087500/b547b64e-236f-11e7-92c6-ca2cdedab35a.JPG)
Reopen Article, Status is `Published`.
- List of Articles:
Click on "Trash"-Symbol works, also show trashed Items by "Search Tools" and change Status back to published.
### System information
Joomla! 4.0.0-dev
macOS Sierra, 10.12.4
Firefox 52 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by joomdonation** [comment]
PR #15352 should fix this issue

**Comment by franz-wohlkoenig** [comment]
closed as having PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15350">issues.joomla.org/tracker/joomla-cms/15350</a>.</sub>
