### ISSUE TITLE
[com_fields] read only or disabled  in edit form

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#15369]
What is the use case for having a field and setting it to readonly or disabled in the edit form. Surely that means that no one can ever set a value for the field ?

<img width="401" alt="screenshotr10-01-13" src="https://cloud.githubusercontent.com/assets/1296369/25122779/05bac810-241e-11e7-93ad-2f881ced0665.png">

**Comment by Bakual** [comment]
Yep, it would meant that. Maybe as a temporary state?
@laoneo Did you just expose all possible formfield attributes or did you have a usecase in mind here?

**Comment by laoneo** [comment]
I just exposed them. But I think they are more confusing than helpful. Like now you can show a value to the user which is not editable, that's all really.

**Comment by brianteeman** [comment]
I really cant see a valid use case for them and as such they should be removed. The only use case I can think of for having a field disabled/readonly in an edit form would be if the user accessing the edit form doesnt have the correct ACL permissions but  the correct way to do that would be with the ACL.

**Comment by Bakual** [comment]
> The only use case I can think of for having a field disabled/readonly in an edit form would be if the user accessing the edit form doesnt have the correct ACL permissions but the correct way to do that would be with the ACL.

That works already independent of exposing that setting.

**Comment by brianteeman** [comment]
exactly - so we dont need these extra fields which just complicate the UI and dont really do anything

**Comment by Bakual** [comment]
Please test and review #15373

**Comment by Raere** [comment]
There is definitely a use for readonly and disabled fields. A good case example for readonly would be a membership organization who wants to assign member id, type, and expiration. An administrator can set those for recordkeeping and not allow the user to edit the fields but to only view them. A good case example for disabled is allowing members to have access to a file so the URL to the file would be there. By disabling that field, the file no longer becomes available.

**Comment by brianteeman** [comment]
that can be ahieved with the acl
