### ISSUE TITLE
[4.0] Atum template.min.css loaded when debug is on

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#15367]
As title says. It should load template.css in that case.

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/15368

**Comment by franz-wohlkoenig** [comment]
closed as having PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15367">issues.joomla.org/tracker/joomla-cms/15367</a>.</sub>
