### ISSUE TITLE
[installer] Remove installation folder not enforced

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#15360]
### Steps to reproduce the issue
Install Joomla.
On the final step of installation, you see this warning.

Per this warning message, you will not be able to proceed without removing installation folder, yet it is possible by clicking the Site or Administrator button.

![installation-remove](https://cloud.githubusercontent.com/assets/368084/25109010/aa4cb8d8-238e-11e7-956f-d0748a6883ee.jpg)

### System information (as much as possible)
Latest staging version

**Comment by zero-24** [comment]
This only works in dev versions to allow easier tests. Stable versions forces that.
