### ISSUE TITLE
TinyMCE plugin shows wrong icons

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#15370]
If you go to a content page you will see the icons for text colour and text background colour are displayed correctly as below

<img width="340" alt="screenshotr10-13-33" src="https://cloud.githubusercontent.com/assets/1296369/25123312/e0e4f48c-241f-11e7-8a66-1f8e9ea70456.png">

If you go to the plugin you will see that the icons are not displayed correctly as below

<img width="230" alt="screenshotr10-14-02" src="https://cloud.githubusercontent.com/assets/1296369/25123343/f35bcb0e-241f-11e7-86d7-80f655262cd4.png">

**Comment by dgt41** [comment]
@brianteeman those icons on the plugin configuration are dummies, thus there is no dropdown for any of those

**Comment by brianteeman** [comment]
not saying they should have dropdowns. If you look they are the wrong icons ;)

**Comment by bertmert** [comment]
Confirmed. Darker grey bg missing.

**Comment by infograf768** [comment]
Please test patch
https://github.com/joomla/joomla-cms/pull/16702
