### ISSUE TITLE
[4.0] Articles Edit -Button misalignment

### ISSUE THREAD

**Issue by yasirunilan** [joomla/joomla-cms#15375]
### Steps to reproduce the issue
Main Menu -> Content -> Articles 
select New button. A window will open. Go to the tab publishing. There is a field named "Created by". Click on that. a modal will open up

### Expected result
Buttons should not be misaligned

### Actual result
![222](https://cloud.githubusercontent.com/assets/9814784/25129700/be31b9ce-245c-11e7-9c5c-abb06a2c61d9.PNG)

### System information (as much as possible)
Joomla! 4.0.0-dev
Windows 10
Chrome 57.0.2987.110 (64-bit)
PHP 5.6

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/15384

**Comment by brianteeman** [comment]
Closed as we have a PR
