### ISSUE TITLE
Admin main menu is show in other ACL 

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#15382]
### Steps to reproduce the issue
Create a new user to work in administration.
Her group is Author
In the Permitions / Administrator Login in Allowed.
Login in the admin with this user and the buttom System is show.

### Expected result
No admin main menu show for a user with acl author with a simple acces to the administrator

### Actual result
The Menu System and the child buttom Control Panel is show

### System information (as much as possible)
Joomla 3 Rc2

**Comment by brianteeman** [comment]
I would say that is the expected behaviour as you have given access to the control panel with the admin login

**Comment by Open2logic** [comment]
The access is correct, but this is a module assigned to another group (Special), i see it strange, since if i go to this admin module and change its access from Special to Super user then it disappears, but the user still has access to the admin.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15382">issues.joomla.org/tracker/joomla-cms/15382</a>.</sub>

**Comment by brianteeman** [comment]
Sorry but you are not understanding the ACL

Special is not a group it is a viewing access level

If you look at which groups have viewing access to the special level you will see that the author group has access

**Comment by Open2logic** [comment]
I'm reviewing, the Acces Administration Interface is not allowed for this user<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15382">issues.joomla.org/tracker/joomla-cms/15382</a>.</sub>

**Comment by Open2logic** [comment]
Forget my last comment<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15382">issues.joomla.org/tracker/joomla-cms/15382</a>.</sub>

**Comment by Open2logic** [comment]
In Joomla 3.6 the same scenario is recreated and nothing is shown, as i understood, has been modified for Joomla 3.7?
Sorry I'm still learning about the new features<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15382">issues.joomla.org/tracker/joomla-cms/15382</a>.</sub>

**Comment by brianteeman** [comment]
I just tested in 3.6.5 and it is exactly the same

**Comment by Open2logic** [comment]
My error, Had the modified upper level of previous tests.
Sorry I'm with a thousand windows testing different configurations of Joomla, I'll check it out next time before creating the issue.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15382">issues.joomla.org/tracker/joomla-cms/15382</a>.</sub>

**Comment by zero-24** [comment]
So this can be closed? If yes you can just hit the close issue button on github or ping me.
