### ISSUE TITLE
[RC3] Unknown column 'a.name' in 'field list'

### ISSUE THREAD

**Issue by humblehumanbeing** [joomla/joomla-cms#15389]
### Steps to reproduce the issue
Define a field group
Define a field for this group
Go to Content/Field Groups
Go to Content/Fields

### Expected result
They should work as usual

### Actual result
Content/Field Groups is listing the records AS EXPECTED
Go to Content/Fields OUTPUTS the error "500 Unknown column 'a.name' in 'field list'"

### System information (as much as possible)
Joomla! 3.7.0-rc3

### Additional comments
It was working as expected in the previous rc's

**Comment by humblehumanbeing** [comment]
It was update from 3.6.5 -->RC1...RC3 but I saw a similar issue at https://github.com/joomla/joomla-cms/issues/15142

**Comment by zero-24** [comment]
> It was update from 3.6.5 -->RC1...RC3 Yes we have changed the database. Please try 3.6.5 -> RC3

**Comment by laoneo** [comment]
Or just change the column alias to name in the __fields table.

**Comment by rdeutz** [comment]
not supported update path, closing

**Comment by ymages** [comment]
same issue with final version (it was working before)

custom field contact or article
 error 500 Unknown column 'a.name' in 'field list'

**Comment by ymages** [comment]
ALTER TABLE `prefix_fields` CHANGE `alias` `name` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT ''
