### ISSUE TITLE
Improve speed of Drone tests

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#15380]
Not sure if this is possible, but is there a way to speed up the Drone tests at all? Currently they're quite slow as we're running `npm install` each time (https://github.com/joomla/joomla-cms/blob/staging/.drone.yml#L24)

Maybe using something like: https://www.npmjs.com/package/npm-cache

@mbabker @dgt41 ?

**Comment by rdeutz** [comment]
Just to confirm we are speaking about the same, under 1 minute is slow?

**Comment by C-Lodder** [comment]
When you've got PR's that have changes being made to them on the fly, it all adds up. If there is a way to load cached packages rather than download and install them each time, do you not deem that a better approach?

**Comment by zero-24** [comment]
@yvesh told me there is something on his todo list 👍

**Comment by rdeutz** [comment]
I made a quick check, drone can't cache (it was able to do it in the past but it seems they removed this function for whatever reason). The install takes 16 seconds so there is not so much to optimise.

**Comment by franz-wohlkoenig** [comment]
@C-Lodder close this Issue?

**Comment by yvesh** [comment]
@rdeutz before we forget it, there is a way for caching, it's just different

See https://github.com/appleboy/drone-sftp-cache
