### ISSUE TITLE
Remove IDs from URLs - option does not appear

### ISSUE THREAD

**Issue by necalex** [joomla/joomla-cms#15396]
### System information (as much as possible)

[systeminfo-2017-04-18T21-20-01+00-00.txt](https://issues.joomla.org/uploads/1/ba003561f643105c029098c6f0a6e631.txt)

### Additional comments

![screen shot 2017-04-18 at 21 21 08](https://issues.joomla.org/uploads/1/4a93d9187a5fdee1f76c6e315a496607.jpg)

**Comment by mbabker** [comment]
As noted at https://developer.joomla.org/news/674-statement-about-the-new-router-feature-for-3-7-0.html this is expected.
