### ISSUE TITLE
[3.7 RC3] PLG PHPVERSIONCHECK is shown to every backend users.

### ISSUE THREAD

**Issue by jsubri** [joomla/joomla-cms#15397]
### Steps to reproduce the issue
3.7RC3 PHP 5.4.x
"We have detected that your server is using PHP 5.4.23 which is obsolete and no longer receives official security updates by its developers..."

### Expected result
PLG_QUICKICON_PHPVERSIONCHECK_UNSUPPORTED and PLG_QUICKICON_PHPVERSIONCHECK_SECURITY_ONLY messages shall be restricted to Super Users or (core.admin) as not meaningful other user groups.

### Actual result
The messages are displayed to every users connecting to the backend.

**Comment by brianteeman** [comment]
I disagree - it is working as intended and if you dont like to see the message you should ensure that the site is upgraded to a supported version of php

**Comment by C-Lodder** [comment]
Same, I don't see what the problem is. Joomla's simply stating you're using an unsupported version of PHP:

http://php.net/supported-versions.php

At the end of the day, it's for your own benefit.

**Comment by jsubri** [comment]
I thought it would be better to have only the Super Users being notified rather than disabling the plug-in to avoid end users keeping asking questions. Thank you for this clarification. Closing

**Comment by irbian** [comment]
@jsubri In my installation I have modified the access level to a different one that only superusers have access, until a proper PHP update can be planified.
