### ISSUE TITLE
[com_fields] First, Last, and Step fields in `Fields - Integer` plugin not utilized

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#15394]
### Steps to reproduce the issue
Under Extensions > Plugins, search `Fields - Integer`.
Edit this plugin to see fields to set including First, Last, and Step fields.
Go to Content > Fields.
Create a new field.
Select `Integer` from the dropdown.

### Expected result
First, Last, and Step fields should be populated with values from the plugin.

### Actual result
First, Last, and Step fields are blank.

### System information (as much as possible)
RC3

**Comment by brianteeman** [comment]
I can confirm that they are blank BUT if you leave them blank and  look at the values in the generated field they match the values set in the plugin - so it does work but there is a UI bug

**Comment by Quy** [comment]
Updated ticket to more accurately describe the issue.

**Comment by brianteeman** [comment]
@quy now i am mmore cconfiused. After setting the values in the plugin and leaving the values blank in the field the values from the plugin are used. See screenshots
<img width="516" alt="screenshotr22-59-54" src="https://cloud.githubusercontent.com/assets/1296369/25154995/d74a8570-248a-11e7-94ed-7766b5926a3f.png">


<img width="390" alt="screenshotr22-59-35" src="https://cloud.githubusercontent.com/assets/1296369/25154994/d744fe84-248a-11e7-90e2-42b367548297.png">
<img width="343" alt="screenshotr22-59-18" src="https://cloud.githubusercontent.com/assets/1296369/25154993/d70bd118-248a-11e7-8a8d-7559829396e9.png">

**Comment by brianteeman** [comment]
from my perspective the only issue is that the First, Last and Step fields in the field defintion should say "from plugin or enter a value" and not be blank

**Comment by Quy** [comment]
It appears you have updated/saved the `Fields - Integer` plugin which makes it work. If you leave the plugin as it without updating and saving it, then it won't work until updated.

This screenshot shows the 1st integer with blank values and the 2nd integer with filled values.
![integer2](https://cloud.githubusercontent.com/assets/368084/25155115/524426f2-2448-11e7-86b5-81fe45f5a169.jpg)

**Comment by brianteeman** [comment]
Say i understand you now.i am not at my computer anymore but iirc you should to see if the plugin has default values stored in the dB. I suspect not and that is the issue. The install SQL can be updated to fix that if my guess is correct

**Comment by Quy** [comment]
The plugin has default values, but it seems you have to initialize/save it for it to be in effect.

**Comment by brianteeman** [comment]
Which means that the default values are not present in the database on install and are only in the XML. They should be in both

**Comment by Bakual** [comment]
The database actually doesn't matter that much. The default values should be in the XML and in the code where the param is requested.

**Comment by brianteeman** [comment]
@bakual maybe you are right and the default values are missing in the code from where the param is requested - I dont know where to look for that. I can say for certain that it resolved by setting the default param in the sql on install - but if you say thats the wrong way then I will wait for your reply as my PR would be wrong<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15394">issues.joomla.org/tracker/joomla-cms/15394</a>.</sub>

**Comment by Bakual** [comment]
I had a look and the way the params are merged, we can't easily add the default values to the code. So your approach with the database looks indeed better and easier.

**Comment by brianteeman** [comment]
OK - I will work on a PR now then

**Comment by brianteeman** [comment]
Closed as we have a PR see #15403
