### ISSUE TITLE
Cannot find any extensions for your version of Joomla

### ISSUE THREAD

**Issue by NomisGninnac** [joomla/joomla-cms#15393]
### Steps to reproduce the issue

Install Joomla and run "Install from web" tab

### Expected result

To see Joomla extensions

### Actual result

Error message stating "Cannot find any extensions for your version of Joomla"

### System information (as much as possible)

N/A![screen shot 2017-04-18 at 20 01 34](https://issues.joomla.org/uploads/1/f15785f5cc5feab3a5a958030de7c52d.png)

### Additional comments

This definitely needs to be fixed.  Joomla is falling behind the likes of Wix and Squarespace as it stands, all these bugs left in the stable stream will not help.

**Comment by laoneo** [comment]
The PLT is aware about this issue and we will come up with an action plan. Thanks for reporting.

**Comment by brianteeman** [comment]
I am assuming that this has been resolved elsewhere as I can not replicate it - if it is still an issue for you please report back and it can always be re-opened
