### ISSUE TITLE
[4.0] Improve styling of search tools

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#15409]
IMO the search tools styling is currently terrible and doesn't place nicely on smaller devices. I think we can drastically improve this by consolidating all the search related filters into a secondary popout and therefore decluttering the view.

The actual search input can be kept as it is.

@ciar4n @dgt41 @brianteeman @franz-wohlkoenig

Thoughts?

### Initial view.

![search1](https://cloud.githubusercontent.com/assets/2019801/25175931/71f89dd2-24f4-11e7-8a10-0f97d039b457.png)

### Popout

![screeny](https://cloud.githubusercontent.com/assets/2019801/25175957/802fc36c-24f4-11e7-9d69-034a3d3bed75.png)

**Comment by dgt41** [comment]
💯

**Comment by brianteeman** [comment]
Cant say I am a fan - never am of popups/popouts and they are very hard to make accessible.

For reference the original inspiration was similar to how google does image search

![im](https://cloud.githubusercontent.com/assets/1296369/25176148/1f5ab118-24f5-11e7-9893-08ce2d2b1d65.gif)

**Comment by brianteeman** [comment]
From a usability perspective this is also not very good imho

Before this idea
Open search tools
select a filter 
look at results
select more or different filters

With this idea
Open search tools popout
select a filter
click apply 
look at resultas
open search tools popout
select more or different filters
click apply

**Comment by C-Lodder** [comment]
@brianteeman but then on the other hand, the up side is that you can apply multiple filters, then apply them all at once, rather than having to select one, wait for the page to refresh, then apply your others.

If you also just take a look at this, it's not exactly the most appealing or friendly display:

![untitled](https://cloud.githubusercontent.com/assets/2019801/25176643/c2f2b388-24f6-11e7-9ae4-420b3bd72f56.png)

**Comment by franz-wohlkoenig** [comment]
Joomla should start with simple default Settings (like now).  Whats missing is to change default ("don't show `Language' and `Access`") or switch to @c-loddar Suggestion.

**Comment by brianteeman** [comment]
having the apply button as you state is a positive when you have 500 items displayed - but when you just have a default of 20 the refresh isnt even noticeable.

Having the search filters displayed once selected is a benefit - your method hides them after they have been selected.

IIRC filters are saved in the session as well so with your method you wouldnt even know that a filter is selected

(I dont disagree that with a lot of filters the view is not great but i just dont see this as an improvement as while the display is better the usabilty is worse)

**Comment by dgt41** [comment]
@C-Lodder @brianteeman the apply button already exists in 3.x, look at Hathor template

**Comment by ciar4n** [comment]
Just throwing this in as an alternative to the popout...

![filter](https://cloud.githubusercontent.com/assets/2803503/25178328/522938fa-24fd-11e7-8194-86c178332447.png)

**Comment by Flowman** [comment]
@brianteeman maybe we could add and info next the the Title with what filters are enabled in the session?

Article | Applied Filters (filter a, filter b, filter c)

**Comment by brianteeman** [comment]
My 2c that would defeat the objective of the proposed change

**Comment by C-Lodder** [comment]
Can always add a green outline to the select box if something has been selected, that's not an issue.

Based on the thumbs from Ciaran's screenshot, I'll submit a PR for it this week.

**Comment by Bakual** [comment]
>  the apply button already exists in 3.x, look at Hathor template

@dgt41 Hathor isn't really using search tools. They're classic filters and use a lot of different code to my knowledge.

That proposed reminded me on J2.5 (pre-Searchtools) days where the filters where in the left sidebar :smile:

**Comment by brianteeman** [comment]
I am going to close this now that we have the table options from @ciar4n merged
