### ISSUE TITLE
[3.7.0-rc3] New calendar field  not rendering right

### ISSUE THREAD

**Issue by schnuti** [joomla/joomla-cms#15402]
### Steps to reproduce the issue
- Update to J3.7.0-rc3
You may have to use a "normal" screen size or change the size of the browser with ctl/+.
This is view port dependent.
Tested with screen 1366x768,  a MS-Window text setting of 125% and FF latest with standard settings.
- Go to backend Article creation - tab Publishing.
- Click on the date fields and watch the pop up.
- Try to scroll. Not easy or impossible to see the whole pop up.

Without scrolling down.

![calendar1](https://cloud.githubusercontent.com/assets/956537/25171364/dca8f840-24ed-11e7-8443-ff334914c8d4.png)

After scrolling down

![calendar-scrolled-down](https://cloud.githubusercontent.com/assets/956537/25171421/1533f5ca-24ee-11e7-8f6f-9feaa65fa6ee.png)

 More images for this problem in  #13181.  

### Expected result
The pop up must be shown in total or be scrollable. I think it is, if it is shown below the field. Still not easy to scroll down if the pop up has extended the page hight.

### System information (as much as possible)
See above

**Comment by yasirunilan** [comment]
I can confirm this issue in 3.7 RC 4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15402">issues.joomla.org/tracker/joomla-cms/15402</a>.</sub>
