### ISSUE TITLE
[3.7] [com_fields] Warning Error loading component: com_fields, Component not found.

### ISSUE THREAD

**Issue by Maartinsh** [joomla/joomla-cms#15401]
### Steps to reproduce the issue

1) Loggin in admin panel.
2) Checking front-side part of page.

### Expected result

1) No errors
2) Seeing modules (menu items). They disappeared.

### Actual result

1) Errors/Warnings
2) No modules (menu items)

### System information (as much as possible)

Joomla! 3.6.5 is available: Update Now
Warning
Error loading component: com_fields, Component not found.

### Additional comments

I am little scared if I will not lose any data or other implementations made in past due to update. Is it safe? Will update fix this error?

**Comment by zero-24** [comment]
Can you share the errors you get?

Do you really expect modules and menu items disappear?

**Comment by pmleconte** [comment]
Same problem overhere after upgrading the "hard way" (unzip and overwrite).

To fix it, go to Extensions/Manage/Discover. 

Click on "discover" button, enter "fields" in search edit and select all extensions it shows, then click on "Install" button.

Hope it helps,

Pascal

**Comment by zero-24** [comment]
Unzip and overwrite is not a supported update method ;) please also run the database fixer button to catch some very importend missing steps if you just unzip!

**Comment by Bakual** [comment]
For the message, this should work: https://github.com/joomla/joomla-cms/pull/15465

**Comment by JujuLand** [comment]
Hi,
I have updated from 3.6.5 to 3.7 there is two days, and I have the message.
For a website on the web where I can't use the joomla system because of a download size limitation (it seems). I have unzipped in the folder, and correct the database.
For a local site where I have used the habitual method, but with the same message ...

Is there an update for this problem (I'm not a programmer) ?

Thanks
A+

**Comment by l-arnold** [comment]
I have the same issue.  Just updated from 3.6.5 to 3.7 and now this error is here.  I am looking for stated solutions (discover com_fields, or discover com_tags so far, but neither shows up).
Is there a "patch" method to repair something of this sort?

Seems this could be related to running FlexiContent which changes some of the Joomla articling and makes intensive usage of Fields, but I am not sure.

Thoughts on repair?

**Comment by tranduyhung** [comment]
Since 3.7.0 release, I updated many 3.6.5 sites to 3.7.0 and didn't see this error at all.
However I have just updated another 3.6.5 site to 3.7.1 and this error message appears.

**Comment by missnene** [comment]
Same issue. On 3.7.1:  Error loading component: com_fields, Component not found.
Contact missing from admin menu, but exists when going directly via URL.  Category for Contacts also missing, but shows in menu and on frontend.

**Comment by swiffer** [comment]
same error here updating from 3.6.5 to 3.7.1

**Comment by Bakual** [comment]
Guys, this is a closed issue. If you still have this issue after updating from 3.7.0, you need to open a new issue. Otherwise nothing will be done.

**Comment by l-arnold** [comment]
Bakual,  since you closed the issue can you reopen it?  seems redundant to stack issues with the same issue.

**Comment by Bakual** [comment]
@l-arnold I didn't close it, but yeah I could reopen it. But then it wouldn't help because it has no additional information. The issue described here initially *should* be solved in Joomla 3.7.0.
If you have the issue still in a Joomla version in the current Joomla 3.7.1 (not during updating from a previous version!), then please open a new issue so it can be tackled down.

**Comment by gregpal** [comment]
After clearing the cache (delete all) the issue just disappeared

**Comment by xnhinzkyx** [comment]
I agree with @gregpal, clearing the cache fixes the issue but should have run "Fix" for Database after upgrade.
