### ISSUE TITLE
Empty class attribute in label tag

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#15415]
### Steps to reproduce the issue
Edit an article.
View page source.
Search for `class=""`.

### Expected result
No empty class output.

### Actual result
```
<div class="control-group">
			<div class="control-label"><label id="jform_modified_by-lbl" for="jform_modified_by" class="">
	Modified By</label>
</div>
```

### Additional comments
Custom fields are affected by this too.

I attempted to fix this in `\joomla-cms-staging\layouts\joomla\form\renderfield.php`, however, I am unable to find out where $label is generated.

```
<div class="control-group<?php echo $class; ?>"<?php echo $rel; ?>>
	<?php if (empty($options['hiddenLabel'])) : ?>
		<div class="control-label"><?php echo $label; ?></div>
	<?php endif; ?>
	<div class="controls"><?php echo $input; ?></div>
</div>
```

**Comment by brianteeman** [comment]
how about renderlabel.php ?

**Comment by Quy** [comment]
Close per PR #15416
