### ISSUE TITLE
Unknown column 'a.name' in 'field list' 

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#15410]
### Steps to reproduce the issue
I saw this before as an issue, but they are closed.
Update 3.6.5 ==> RC3 (direct)
Go to Content - Fields
500 Unknown column 'a.name' in 'field list' 

### System information (as much as possible)
Update direct from 3.6.5 to 3.7.0 RC3
On localhost
php 7.0.4 apache 2.4.18 database 5.7.11
### Additional comments
I tried this with another 3.6.5 site and no problem.
Are there others having this?

**Comment by zero-24** [comment]
You can only havin this if you came from a not stable version to 3.7 as we have changed the database columname. If you come from 3.6.5 it should work.

**Comment by brianteeman** [comment]
Just tested an upgrade from 3.6.5 to rc3 and could not replicate this

**Comment by MartijnMaandag** [comment]
It is direct from 3.6.5.
Database says its up-to-date.
As I mentioned when I take another site it works fine.
Maybe we wait if somebody else has this. In the meantime I will test a little.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15410">issues.joomla.org/tracker/joomla-cms/15410</a>.</sub>

**Comment by brianteeman** [comment]
could you have used this site to test some patches?

**Comment by MartijnMaandag** [comment]
I always take e copy (Akeeba) from production to test.

But I have an idea and will try out if that is the cause.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15410">issues.joomla.org/tracker/joomla-cms/15410</a>.</sub>

**Comment by MartijnMaandag** [comment]
Yes.
If you test (more than once) go to the database and delete all the old tables (don't trust on the delete old tables in Kickstart.php).
No error anymore.
I will close this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15410">issues.joomla.org/tracker/joomla-cms/15410</a>.</sub>

**Comment by djalondon** [comment]
I hadn't tested Fields before but have a new site which was installed using Joomla 3.7 Beta 2 and have since updated to rc2 then rc4. In Articles if I go to Fields I get "Unknown column 'a.name' in 'field list'" with the following showing under Extensions: Database:

Database schema version (in #__schemas): 3.7.0-2017-04-19.
Update version (in #__extensions): 3.7.0-rc4.
Database driver: mysqli.
145 database changes were checked successfully.
173 database changes did not alter table structure and were skipped.

**Comment by zero-24** [comment]
Yes. this is expected behavior as there is no supported updatepath between dev versions.

**Comment by djalondon** [comment]
OK - so what should I do to go from an RC to 3.7.0 - I tried installing 3.7.0 from rc4 but still get the same error

**Comment by zero-24** [comment]
>  so what should I do to go from an RC to 3.7.0

There is no supported way to do that ;) But you can change the database colum name by your self in the database..

**Comment by djalondon** [comment]
OK thanks
