### ISSUE TITLE
Multilingual associations Copy Reference to Target does not keep acl permission setting

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-cms#15421]
### Steps to reproduce the issue
Using multilingual associations, select an article and then Copy Reference to Target and save the target

### Expected result
also the acl permission setting are copied

### Actual result
the acl permission setting are not copied

### System information (as much as possible)
Joomla 3.7.0RC4

### Additional comments
![multilingual-permission](https://cloud.githubusercontent.com/assets/1362388/25220146/cadec340-25a8-11e7-84b1-1215961faf35.png)

I understand it is very complicated to implement. And I confirm that also batch copy does not keep acl permission setting as we already know.

**Comment by gwsdesk** [comment]
confirmed by me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15421">issues.joomla.org/tracker/joomla-cms/15421</a>.</sub>

**Comment by infograf768** [comment]
save2copy does not indeed copy permissions, wherever the function is used (multilingual associations or not).
We also do not have among batch functions the possibility to batch keep or change permissions.

Until someone work on this, these are known aspects of J.

**Comment by ghost** [comment]
@infograf768 should this Issue stay open?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15421">issues.joomla.org/tracker/joomla-cms/15421</a>.</sub>

**Comment by infograf768** [comment]
As far as I know, nobody proposed a solution for this bug/lack of feature.
So, yes, I would keep this open.

**Comment by joomleb** [comment]
...and could be merged with [Multilanguage Associations - Copy BUGs ?](https://github.com/joomla/joomla-cms/issues/19807) ?

**Comment by jwaisner** [comment]
@AlexRed are  you still experiencing this in the latest J3?

**Comment by infograf768** [comment]
@jwaisner You can test yourself by using save2copy. not even need to use multiland assoc

**Comment by infograf768** [comment]
I think this has been solved in J4 by the way

**Comment by infograf768** [comment]
btw, I confirm this is still an "issue" in 3.x

**Comment by brianteeman** [comment]
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed. 

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
