### ISSUE TITLE
[4.0]  [com_fields] new/edit view click on cancel button having error page

### ISSUE THREAD

**Issue by RonakParmar** [joomla/joomla-cms#15420]
### Steps to reproduce the issue
Joomla! 4.0.0-dev
PHP Version : 5.6.30-10
Web Server : Apache/2.4.25 (Ubuntu) 
Goto Administrator->content->fields->new and click on cancel button.

### Expected result
Redirected to fields listing page.

### Actual result
Having error page.
![screen shot 2017-04-20 at 07 09 04](https://issues.joomla.org/uploads/1/40ecc29ab3f097a1f55ff609751f31da.png)

**Comment by franz-wohlkoenig** [comment]
Confirmed. Button "Save & Close" Works, "Close" get Error.
### System information
Joomla! 4.0.0-dev (nightly Build)
macOS Sierra, 10.12.4
Firefox 52 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by RonakParmar** [comment]
- administrator/components/com_fields/views/field/view.html.php line number: 121 and 154 
I think, we have to replace "contact" by "field" and we can fix this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15420">issues.joomla.org/tracker/joomla-cms/15420</a>.</sub>

**Comment by gunjanpatel** [comment]
Closing as we have pull request #15422 for it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15420">issues.joomla.org/tracker/joomla-cms/15420</a>.</sub>
