### ISSUE TITLE
[3.7] Text Filters Config Page Layout

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15423]
Why have a blank column with just "text filters" text in it? The space could be better used. 

<img width="1279" alt="screen shot 2017-04-20 at 10 46 03" src="https://cloud.githubusercontent.com/assets/400092/25224556/aa0dd5a8-25b6-11e7-996c-2730a3d31372.png">

**Comment by franz-wohlkoenig** [comment]
in 3.5.6 isn't this Column:
![bildschirmfoto 2017-04-20 um 12 00 06](https://cloud.githubusercontent.com/assets/8235763/25225208/f9cd1cd4-25c0-11e7-99cc-0178a7e90305.JPG)

**Comment by PhilETaylor** [comment]
> in 3.5.6 

One assumes you mean 3.6.5

> in 3.5.6 isn't this Column:

Thats why I set the subject line [3.7] :-)

**Comment by brianteeman** [comment]
It comes from the change to use a generic layout here 
https://github.com/joomla/joomla-cms/commit/9070601c2b5aa47929a4715bfdaf45322a475883

**Comment by PhilETaylor** [comment]
That link says, @Buddhima committed on 9 Oct 2013 ? strange... 

Either way, its a sad misuse of space...

**Comment by franz-wohlkoenig** [comment]
@PhilETaylor right, 3.6.5 and i wanted to show that between this Version and now something happend.

**Comment by brianteeman** [comment]
Sorry I pointed to the wrong change. Its a later one relating to showon in the layouts.

**Comment by brianteeman** [comment]
Closed as we have a PR
