### ISSUE TITLE
[4.0] Multilingual associations select target modal broken

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#15439]
### Steps to reproduce the issue
Images are worth a thousand words.

![multiassoc_modal](https://cloud.githubusercontent.com/assets/869724/25266717/6db34a18-2672-11e7-912b-c62c4ee6c1d9.gif)

js error is 
09:11:33.051 TypeError: document.getElementsByName(...)[0] is undefined 1 multiselect.min.js:1:756

code concerned is
`document.getElementsByName('checkall-toggle')[0].addEventListener('click', function(event) {
		var checkall = this;`

Normally we should not have a multiselect there therefore I guess the error is in the new admin-associations-modal.js or modal-associations.js
From https://github.com/joomla/joomla-cms/pull/14945

@dgt41

**Comment by brianteeman** [comment]
At what point are you getting the error - its not clear from your movie

**Comment by infograf768** [comment]
When posted, the movie was demonstrating that clicking in the modal did not add the article chosen to the Target and did not close the modal.

The situation has changed. It is now worse: the modal does not even display when clicking on Target or Change target.

**Comment by brianteeman** [comment]
Can you please test with #20659

**Comment by ReLater** [comment]
> Can you please test with #20659

I've tested with and without 20659 and can confirm:

> the modal does not even display when clicking on Target or Change target.

with different error
> TypeError: document.getElementById(...) is null   **bootstrap-init.min.js:1:1351**

DEBUG active:
> TypeError: document.getElementById(...) is null  bootstrap-init.js:102:10

**Comment by ReLater** [comment]
Just BTW: "Multilingual Associations: Edit Associations (Articles > Articles)" opens extremely slow. Sometimes it looks like that TinyMCE is loaded several times(?)

**Comment by infograf768** [comment]
Indeed, as @ReLater wrote, we now have an error with bootstrap-init.js

**Comment by brianteeman** [comment]
As far as I can tell this has now been resolved so I am closing - it can always be re-opened if I am mistaken.
