### ISSUE TITLE
[com_finder] Smart Search does not find tags when custom filter is deployed

### ISSUE THREAD

**Issue by peterstewart** [joomla/joomla-cms#15444]
related to Fix for tags issue #10122 
### Steps to reproduce the issue
Joomla 3.6.5
Apply the fix provided in  issue #10122
create tags and associate them with articles
create a custom filter in Smart Search component and enable it.

### Expected result
With Smart Search the tags and the articles related should be found.

### Actual result
No result with the search on tags, also not with advanced search although the tags and tag description are offered as search terms;
The same result occurs even if the custom filter is identical to the default
The default filter does find the tags
### System information (as much as possible)

PHP Built On: 	Linux lin219.gridhost.co.uk 3.2.83 #4 SMP Thu Oct 27 23:38:08 BST 2016 x86_64
Database Version: 	5.6.21
Database Collation: 	utf8_general_ci
Database Connection Collation: 	utf8mb4_general_ci
PHP Version: 	5.4.42
Web Server: 	Apache
WebServer to PHP Interface: 	cgi-fcgi
Joomla! Version: 	Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla! Platform Version: 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by franz-wohlkoenig** [comment]
@peterstewart I corrected the Issue# from 1012:2 to 10122. Is this issue also on latest staging?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15444">issues.joomla.org/tracker/joomla-cms/15444</a>.</sub>

**Comment by ghost** [comment]
closed as no Response.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15444">issues.joomla.org/tracker/joomla-cms/15444</a>.</sub>
