### ISSUE TITLE
[com_fields] Needs option to add more component specific parameters

### ISSUE THREAD

**Issue by machadoug** [joomla/joomla-cms#15443]
### Steps to reproduce the issue
I've been reading the [documentation page for the com_fields](https://docs.joomla.org/Category:Custom_Fields) and the issues here but I couldn't find an option to add component specific parameters, as it can be done with com_categories, for example:
/administrator/components/com_mycomponent/models/forms/category.xml

### Expected result
To be able to add a XML file with new parameters, for example /administrator/components/com_mycomponent/models/forms/formfields.xml

### Additional comments
This will allow third party developers to integrate better with their extensions

**Comment by Bakual** [comment]
For 3.7 it is certainly to late, but i think it is a good idea for further improving com_fields.

**Comment by laoneo** [comment]
Where do you want to add the parameters, to the field or fieldgroup?

**Comment by machadoug** [comment]
@laoneo , right now I can only think of a need to add parameters to the field.

**Comment by laoneo** [comment]
I guess this issue can be closed as we have that feature introduce with #15915.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15443">issues.joomla.org/tracker/joomla-cms/15443</a>.</sub>
