### ISSUE TITLE
[4.0] [com_cache] Proposal

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#15451]
As it stands, there are 2 views for `com_cache`, default and purge.

Personally I don't see any point in having 2 separate views for actions that are very similar.

Here are the 2 menu items under System:

![untitled](https://cloud.githubusercontent.com/assets/2019801/25283097/869b027c-26aa-11e7-97b5-3912d268b223.png)

and I propose we merge them into 1 and put the "Clear Expired Cache" button in the toolbar:

![screeny](https://cloud.githubusercontent.com/assets/2019801/25283127/991cbb70-26aa-11e7-9920-78d4241c96a2.png)

Thoughts?

**Comment by dgt41** [comment]
@C-Lodder why don't we go one step further and eliminate com_admin altogether and add all its functionality to com_config ?

**Comment by C-Lodder** [comment]
That's completely beyond my PHP skillset, so I can't answer that

**Comment by zero-24** [comment]
> @C-Lodder why don't we go one step further and eliminate com_cache/com_admin altogether and add all their functionality to com_config ?

@dgt41 com_admin is also resposible for the current user edit form as well as updates etc. i don't think we can easily remove the component.

Same for com_cache it serves a complete different functionality scope. (cache vs settings)

**Comment by dgt41** [comment]
@zero-24 depends on the way you look at this. For me com_config should be something like windows control panel or OS X's System Preferences, where the user can accomplish a lot of different tasks.

**Comment by zero-24** [comment]
hmm is'nt `windows control panel or OS X's System Preferences` just a view over different components?

**Comment by dgt41** [comment]
yup, so maybe we can just follow that root and make e.g. com_admin the control panel for joomla. That will remove a lot of unneeded menus and will improve the UX by a big margin

**Comment by zero-24** [comment]
ok so you just want to move the GUI to one unifined one and not move the seperated code. Than :+1: from me.

**Comment by dgt41** [comment]
Both ways will work, but I guess creating a simple view with icons is far easier than merging few components to one

**Comment by zero-24** [comment]
Currently i have not enough time for another bigger task sorry. I could only add this to a very long todo list, but i guess this would not help much. Sorry. I can help if someone need advice on implementing that.

But the main problem would be that currently the view is stored with the component. So if you try to have one components you need to go a route like com_categories or similiar.

But what about adding a view to com_config / com_admin where you can jump into the different components?
