### ISSUE TITLE
[com_fields]  Default Users parameter not working

### ISSUE THREAD

**Issue by stellainformatica** [joomla/joomla-cms#15453]
### Steps to reproduce the issue
- Create a new custom field type "user"
- in Default Users put some ID of users
- in an article click on the button to select the user

### Expected result
I don't know if the expected behaviour is this, but probably putting the IDs in the list of users to select there should be just the users with that ID

### Actual result
In the list there are all users

### System information (as much as possible)
Joomla 3.7.0 RC4

**Comment by zero-24** [comment]
Can you please show us a exact image of your configuration of the default setting?

**Comment by stellainformatica** [comment]
Here are my settings of the field<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15453">issues.joomla.org/tracker/joomla-cms/15453</a>.</sub>

**Comment by stellainformatica** [comment]
![screen shot 2017-04-21 at 19 09 15](https://issues.joomla.org/uploads/1/20cfc76851dd2784a84f952e9bfc487c.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15453">issues.joomla.org/tracker/joomla-cms/15453</a>.</sub>

**Comment by zero-24** [comment]
I have just checked it but i can not see where it would make sense to have more than one default user?

If you just enter one default user it works.

Can you confirm that @laoneo than we can change the language string that only one entry is allowed and not multible using a comma seperated list.

**Comment by laoneo** [comment]
The user field can select only one user anyway. So I guess it makes sense to change the default value tooltip and label.

**Comment by zero-24** [comment]
Can you do a PR @laoneo ?

**Comment by laoneo** [comment]
Not this weekend. As we have languge freeze already, we are not in a hurry.

**Comment by zero-24** [comment]
Correct. This can only be fixed in 3.7.1

**Comment by stellainformatica** [comment]
ok thanks

**Comment by laoneo** [comment]
Please test pr #15755 which changes the default user field to user. Guess this issue can be closed.

**Comment by franz-wohlkoenig** [comment]
closed as having PR #15755 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15453">issues.joomla.org/tracker/joomla-cms/15453</a>.</sub>
