### ISSUE TITLE
Menu Recovery Mode message could be clearer

### ISSUE THREAD

**Issue by stevejburge** [joomla/joomla-cms#15463]
Following on from this issue:
![recovery-mode](https://cloud.githubusercontent.com/assets/3868028/25292409/f7d31828-26a3-11e7-91e4-a1f517e95f31.png)

https://github.com/joomla/joomla-cms/issues/15462

As a Joomla user of 10+ years, I found this message to be unclear.

After some some guesswork, I figured out the Menu Manager and Module Manager options, but am stuck on what "Components Container" might be.

Could we make this message clearer?

**Comment by zero-24** [comment]
Can you suggest a better message?

> but am stuck on what "Components Container" might be.

A container that include the components that you install. If you install weblinks it got added to the `Components Container` basicly this is the components dropdown.

**Comment by stevejburge** [comment]
Thanks 

I guess I'm unclear on what the request is.

Do we need to make a menu link to every core component?

**Comment by zero-24** [comment]
> Do we need to make a menu link to every core component?

No there is a element called `Components Container`

![image](https://cloud.githubusercontent.com/assets/2596554/25292810/237f8dce-26d8-11e7-9314-7fb0a30e65aa.png)

**Comment by zero-24** [comment]
set them to the right access level :)

**Comment by stevejburge** [comment]
OK, thanks. I see that menu link now.

What permission setting controls access to it?

**Comment by zero-24** [comment]
super user? Or what ever you want to do with it. If the normal user of that menu should not see it. ;)

**Comment by stevejburge** [comment]
Thanks. OK, if that's true, it's not working.

Here's my tutorial with step-by-step instructions:
https://www.joomlashack.com/blog/tutorials/new-admin-menus/

At the end, the "Publisher" group can still see this:
![screen shot 2017-04-21 at 4 01 23 pm](https://cloud.githubusercontent.com/assets/3868028/25294146/e2e7313a-26ab-11e7-885a-074e734f38cc.png)

**Comment by zero-24** [comment]
Works as expected:
With that setting (everything to hide)

![image](https://cloud.githubusercontent.com/assets/2596554/25294426/7488989e-26df-11e7-8c7e-4e3bf602f302.png)

**Comment by stevejburge** [comment]
Thanks for the help. That works now.

OK, the truth is I never would have understood that without your help.

The original error message is vague and the workaround is only possible if someone holds your hand. 

I know you say this works as expected, but in the current state, I don't think we expect anyone to successfully do this.

It's definitely something we need to fix, IMHO.

**Comment by zero-24** [comment]
Please share your ideas i have not sayed it is perfect as it is. But also remember this is meant to be something for more advanced use cases and should IMO not be done on every site just because you can ;).

**Comment by stevejburge** [comment]
I guess my first thought is:

1) Can we clear up the message text?
2) Can we make it dismissable?

What's the thinking behind making this message un-dismissable?

**Comment by zero-24** [comment]
> Can we make it dismissable?

Yes there is a option for that `Check menu`

> Can we clear up the message text?

Sure do you have suggestions for a better text?

**Comment by stevejburge** [comment]
Ah, problem solved! The "Check menu" option solves everything :)

Still, we could make the message clearer, based on that.

I guess my question for the message is ... who are we talking to? Are we talking to a low-level user (with no permission to act on the message) or the Super Admin?

**Comment by zero-24** [comment]
We talk to the super admin testing that or setting it up. As if he is ready he is going to set the setting from above. We are also talking to the user who is testing that new feature and misconfigured it. So he can't go back to a working state. There for we have added the recovery mode that allow you to come back to a working state.

**Comment by stevejburge** [comment]
If wonder if all of that is too much for a simple message?

Maybe we need a documentation page?

"The administrator menu (Publisher menu) does not contain some expected links. Click here for details on how to add those links, or click here to automatically see the links."

**Comment by zero-24** [comment]
Than i would name it:

`The current administrator menu <b>Publisher menu</b> does not contain some importent entrys (that ther or 2 or one using sprintf). See the documentation (link that to the dokumentaion) for details on how to add those links, or turn on the recovery mode`

**Comment by zero-24** [comment]
Can you start with that documentation page? Else we cannot link it from there. Let me know if i can help you on that.

**Comment by stevejburge** [comment]
Sure, I can do that.

One question I do have ... what is the thinking behind requiring Menu Manager, Module Manager and this Component menu? Why are those the three essential links?

**Comment by zero-24** [comment]
Menu manager (you can change the admin menu here) modul manager (you can reset to preset here) components container (new components that are installed show up there) if you don't have that but you can install a component it wont show up in the menu. So this is not needed to the publisher menu but essencial to a admin (even not superadmin)

**Comment by stevejburge** [comment]
Ok, thanks @zero-24. I'll try and write up that documentation page this week.

**Comment by ymages** [comment]
same error The administrator menu menuadmin does not contain - Menu Manager, Module Manager, Components Container<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15463">issues.joomla.org/tracker/joomla-cms/15463</a>.</sub>

**Comment by ymages** [comment]
I dont get it, I dont want to turn on the recovery mode, I just want a custom admin menu with whatever I want in it , nothing more nothing less

thanks for helping<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15463">issues.joomla.org/tracker/joomla-cms/15463</a>.</sub>

**Comment by brianteeman** [comment]
@ymages thats why you can turn off the check in the admin menu module

**Comment by ymages** [comment]
ok but I dont know what to do to turn it off ? 

thanks for helping


I solved it by hiding the alert MOD_MENU_IMPORTANT_ITEMS_INACCESSIBLE_LIST_WARNING  with nothing in it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15463">issues.joomla.org/tracker/joomla-cms/15463</a>.</sub>

**Comment by ymages** [comment]
I guess nobody will understand what to do , this message should not be here or explain what to do exactly<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15463">issues.joomla.org/tracker/joomla-cms/15463</a>.</sub>

**Comment by brianteeman** [comment]
The correct way is to set the check menu option to no

<img width="344" alt="screenshotr23-39-57" src="https://cloud.githubusercontent.com/assets/1296369/25410742/8f734bac-2a10-11e7-81ef-d9106eaba21c.png">

**Comment by ymages** [comment]
ok got it ! 

thanks a lot<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15463">issues.joomla.org/tracker/joomla-cms/15463</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
closed as Issue resolved. Please feel free to reopen for further Discussion.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15463">issues.joomla.org/tracker/joomla-cms/15463</a>.</sub>

**Comment by zero-24** [comment]
Reopening as the main issue rewrite that message is not fixed yet ;)

**Comment by stevejburge** [comment]
I've been out the office this week, but should have time to work on the documentation page next week.

**Comment by zero-24** [comment]
Great. Let me know when i can help you.

**Comment by ymages** [comment]
the check menu should be off by default

**Comment by brianteeman** [comment]
@ymages absolutely not - it is there for important reasons and must be on by default

**Comment by ymages** [comment]
and 10 000 users will ask to fix it ...

**Comment by brianteeman** [comment]
That message is there to stop a site owner locking themselves out of key functionality. It is not going to change

**Comment by ymages** [comment]
I fixed it for myself ... no problem for me

thanks

**Comment by izharaazmi** [comment]
@brianteeman Should we provide a link to the setting page in the message itself (something similar to that in Post Install Messages)?

**Comment by brianteeman** [comment]
@stevejburge did you ever write that documentation?

**Comment by brianteeman** [comment]
Closed due to lack of response
