### ISSUE TITLE
Possible issue with the Menu Recovery Mode

### ISSUE THREAD

**Issue by stevejburge** [joomla/joomla-cms#15462]
### Steps to reproduce the issue
https://www.joomlashack.com/blog/tutorials/new-admin-menus/

### Expected result

Either don't show the Menu Recovery Mode message to low-level users, or make it dismissable.

### Actual result

I can't dismiss the Menu Recovery Mode message. With one click I can get rid of all normal messages, but the "Menu Recovery Mode" message always comes back.

**Comment by brianteeman** [comment]
> I can't dismiss the Menu Recovery Mode message. With one click I can get rid of all normal messages, but the "Menu Recovery Mode" message always comes back.

Its not a normal message ;)

The way to dismiss the message is to make sure you create an admin menu with the required menu items. If necessary you can set the acl level for those items so that your low level users dont see them

**Comment by stevejburge** [comment]
OK, thanks. I'll update my tutorial to explain that you need to fix the ACL levels in order to make that message disappear.

**Comment by zero-24** [comment]
Closing as expected behavoir. Thanks

**Comment by stevejburge** [comment]
OK, hopefully I'm not bugging anyone by reopening this.

If the message needs to appear - great.

But, it's not very clear. As a Joomla user for 10+ years, I'm stuck on some of what the message means. I did some testing and successfully guessed the "Menu Manager" and "Module Manager" links, but drew a blank on what "Components Container" might be
