### ISSUE TITLE
Proposal: Event triggers for usergroups to match those for users

### ISSUE THREAD

**Issue by Spudley** [joomla/joomla-cms#15460]
Joomla gives awesome ability to write plugins for user management.

With a user plugin, I can write code to intercept both before and after users are saved, when the log in or when they're deleted. I can also intercept the construction of the user profile form and modify it; I can add whole extra tabs of data to the form.

But Usergroups... not so much. There isn't a usergroup plugin type, and aren't any events I can intercept for saving groups or adding fields to the form, or anything else.

Please can we add a plugin type and set of event triggers for usergroups.

Thank you.

**Comment by zero-24** [comment]
@Spudley there are plugin events:
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_users/models/group.php#L31-L34

Did you tryerd that?

**Comment by Spudley** [comment]
@zero-24 embarrassingly, no; I'd completely missed those. Not sure how. (I don't recall seeing them documented anywhere though).

So those would be part of a user plugin, then? That's convenient.

However, I was also hoping to be able to add fields to the usergroup form, as I can for users via `onContentPrepareForm`. Is there an event like that for groups?

**Comment by zero-24** [comment]
also onContentPrepareForm is triggert.

The context is 
`$context = $form->getName();`
=>
`com_users.group`

**Comment by Spudley** [comment]
Ah great. thank you for that. I guess the ticket can be closed then.  :)

I'll try writing my plugin idea when I get a bit of spare time.

**Comment by zero-24** [comment]
👍

**Comment by Spudley** [comment]
@zero-24 - so I've been turns out that modifying the user group admin form is much harder than the user profile form. I don't want to clutter up this thread, but I've asked a question on the Joomla stackexchange site, so perhaps you could [join the discussion there](https://joomla.stackexchange.com/questions/20773/adding-fields-to-user-group-admin-form)? I feel like you might be able to give some helpful input.  :)

Thanks.
