### ISSUE TITLE
[4.0] Media UI is not proper at administrator side

### ISSUE THREAD

**Issue by bhavikDigitalWebInfosoft** [joomla/joomla-cms#15475]
### Steps to reproduce the issue
Goto administrator->media

### Expected result
UI should be in well format.

### Actual result
UI is not proper, please see attached screen dump.

### System information (as much as possible)
Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT 
PHP 5.6.28 
Ubuntu 12.04
Firefox 52.0.2 (64-bit)
Chrome Version 49.0.2623.110 (64-bit)

### Additional comments
![screen shot 2017-04-22 at 09 03 25](https://issues.joomla.org/uploads/1/139c2083db9d472582f2b19eb1a4c2cd.png)

**Comment by brianteeman** [comment]
I am going to close this as expected behaviour as the entire media manager component is being replaced in J4
