### ISSUE TITLE
[com_fields] Permissions screen in Custom Fields mentions articles

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#15486]
### Steps to reproduce the issue
Create or edit a Custom Field.
Go to the Permissons TAB.
At the bottom you will see "Changes apply to this article only".
I think this must be "Changes apply to this custom field only"
It is in the language string JLIB_RULES_SETTING_NOTES_ITEM from en-GB.com_content.ini
In Users and Contacts it is called "item" and comes from en-GB.lib_joomla.ini
![screen shot 2017-04-23 at 11 33 02](https://issues.joomla.org/uploads/1/411eed2566a0990924085836ab84534e.png)
### System information (as much as possible)
Joomla 3.7.0 rc4

**Comment by brianteeman** [comment]
probably the same issue as #11306

**Comment by MartijnMaandag** [comment]
Yes I think it is. It's growing bigger with the custom fields using this. Changing article into item will fix this fast, but won't fix the problem. It can happen everywhere.

**Comment by brianteeman** [comment]
It happens in quite a few places. I couldnt track it down and no one else seemed to care to look into it

**Comment by AlexRed** [comment]
PR here: https://issues.joomla.org/tracker/joomla-cms/13523

**Comment by franz-wohlkoenig** [comment]
closed as having PR #13523 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15486">issues.joomla.org/tracker/joomla-cms/15486</a>.</sub>
