### ISSUE TITLE
[Postgresql] Update from 3.6.5 to 3.7RC4 fails

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#15491]
### Steps to reproduce the issue
With this message:
Warning
JInstaller: :Install: Error SQL ERROR: Relation »u762r_fields_idx_checked_out« already exists.
Files Update: SQL error file DB function reports no errors.
Error loading component: com_fields, Component not found.

Under Manage > Database you will find these problems:
Database schema version (3.6.3-2016-08-16) does not match CMS version (3.7.0-2017-04-19).
    Table 'u762r_fields_values' does not exist. (From file 3.7.0-2016-08-29.sql.)
    Table 'u762r_extensions' does not have column 'package_id'. (From file 3.7.0-2016-11-24.sql.)
    Table 'u762r_ucm_content' does not have column 'core_title' with type IS NOT NULL. (From file 3.7.0-2017-01-08.sql.)
    Table 'u762r_ucm_content' does not have column 'core_body' with type IS NOT NULL. (From file 3.7.0-2017-01-08.sql.)
    Table 'u762r_ucm_content' does not have column 'core_params' with type IS NOT NULL. (From file 3.7.0-2017-01-08.sql.)
    Table 'u762r_ucm_content' does not have column 'core_metadata' with type IS NOT NULL. (From file 3.7.0-2017-01-08.sql.)
    Table 'u762r_ucm_content' does not have column 'core_images' with type IS NOT NULL. (From file 3.7.0-2017-01-08.sql.)
    Table 'u762r_ucm_content' does not have column 'core_urls' with type IS NOT NULL. (From file 3.7.0-2017-01-08.sql.)
    Table 'u762r_ucm_content' does not have column 'core_metakey' with type IS NOT NULL. (From file 3.7.0-2017-01-08.sql.)
    Table 'u762r_ucm_content' does not have column 'core_metadesc' with type IS NOT NULL. (From file 3.7.0-2017-01-08.sql.)
    Table 'u762r_categories' does not have column 'title' with type IS NOT NULL. (From file 3.7.0-2017-01-09.sql.)
    Table 'u762r_categories' does not have column 'params' with type IS NOT NULL. (From file 3.7.0-2017-01-09.sql.)
    Table 'u762r_categories' does not have column 'metadesc' with type IS NOT NULL. (From file 3.7.0-2017-01-09.sql.)
    Table 'u762r_categories' does not have column 'metakey' with type IS NOT NULL. (From file 3.7.0-2017-01-09.sql.)
    Table 'u762r_categories' does not have column 'metadata' with type IS NOT NULL. (From file 3.7.0-2017-01-09.sql.)
    Table 'u762r_redirect_links' does not have column 'comment' with type IS NOT NULL. (From file 3.7.0-2017-02-15.sql.)
    Table 'u762r_contact_details' does not have column 'sortname1' with type IS NOT NULL. (From file 3.7.0-2017-02-17.sql.)
    Table 'u762r_contact_details' does not have column 'sortname2' with type IS NOT NULL. (From file 3.7.0-2017-02-17.sql.)
    Table 'u762r_contact_details' does not have column 'sortname3' with type IS NOT NULL. (From file 3.7.0-2017-02-17.sql.)
    Table 'u762r_contact_details' does not have column 'xreference' with type IS NOT NULL. (From file 3.7.0-2017-02-17.sql.)
    Table 'u762r_newsfeeds' does not have column 'xreference' with type IS NOT NULL. (From file 3.7.0-2017-03-03.sql.)

**Comment by waader** [comment]
In administrator/components/com_admin/sql/updates/postgresql/3.7.0-2016-08-29.sql lines 69 to 74 should be changed to:
CREATE INDEX "#__fields_groups_idx_checked_out" ON "#__fields_groups" ("checked_out");
CREATE INDEX "#__fields_groups_idx_state" ON "#__fields_groups" ("state");
CREATE INDEX "#__fields_groups__created_by" ON "#__fields_groups" ("created_by");
CREATE INDEX "#__fields_groups__access" ON "#__fields_groups" ("access");
CREATE INDEX "#__fields_groups__context" ON "#__fields_groups" ("context");
CREATE INDEX "#__fields_groups__language" ON "#__fields_groups" ("language");

**Comment by zero-24** [comment]
Can you send a PR for that fix?

**Comment by zero-24** [comment]
Closing as we have a PR at #15496 Thanks!
