### ISSUE TITLE
Excessive Duplicate Queries in Debug User/Group Reports

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#15495]
### Steps to reproduce the issue

In the debug reports for users and user groups, there are an excessive number of duplicate queries in different cases.

On the downloads site I had a case where 3 queries were duplicated 11 times each.  On a "plain" install of staging, I only had one duplicated query but it still had 11 duplicates.

### Expected result

Efficient data loading and processing.

### Actual result

Duplicate queries.

**Comment by brianteeman** [comment]
Has something changed since this was reported last year as I only get the following for both users and usergroups

4 duplicate found!
2 duplicates: #3  #37
2 duplicates: #4  #38

**Comment by mbabker** [comment]
Still an issue for users that aren't super users and all groups.

<img width="1380" alt="screen shot 2018-05-29 at 6 53 40 am" src="https://user-images.githubusercontent.com/368545/40657351-21d7665a-630d-11e8-9b90-7a57e8ab05b3.png">

**Comment by alikon** [comment]
the 11 duplicated queries has gone with #20621, i hope not too much side effects :smiley:

**Comment by ghost** [comment]
closed as having Pull Request #20621
