### ISSUE TITLE
Performance issue with com_associations

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#15494]
### Steps to reproduce the issue

After test upgrading a clone of the downloads site to 3.7 RC 4, I clicked into the new `com_associations` to quickly glance at how it works.  After setting up my filters for en-GB articles, the resulting page resulted in 244 queries being executed.  The debug bar reports that 214 of the queries for the request are duplicated.  The ones that look to be coming from the component are running the same query 3 times for each item.

FWIW my clone of the site has 3 articles and 18 of our site languages set up right now (it's an older database clone that's now massively out of sync with the live site which has 27 languages running now).

### Expected result

A sane number of database queries with minimal duplicates.

### Actual result

In this scenario, the component issues 244 queries with 214 duplicated request wide (please remember not all of the duplicates will be related to `com_associations`).

**Comment by ghost** [comment]
@infograf768 can you please have a Look?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15494">issues.joomla.org/tracker/joomla-cms/15494</a>.</sub>

**Comment by infograf768** [comment]
I am not a db queries specialist. I would not know how to solve that one.
Maybe @alikon

**Comment by alikon** [comment]
i'll give it a look ....    @infograf768 can you confirm that is still an issue ?

**Comment by infograf768** [comment]
@alikon 
Looks like.
<img width="1026" alt="screen shot 2017-11-09 at 16 44 05" src="https://user-images.githubusercontent.com/869724/32614320-4c0c87b8-c56d-11e7-814e-9d867ddd6976.png">

7 languages. 25 articles in en-GB
the huge number of duplicates is
<img width="1008" alt="screen shot 2017-11-09 at 16 49 31" src="https://user-images.githubusercontent.com/869724/32614694-1820afa0-c56e-11e7-95db-f97fe7dc36b0.png">

**Comment by alikon** [comment]
@infograf768 i have cached that query with #18544 should be reduced the total number of duplicate query by 50 in your sample
please test

but i'm afraid we can do even more

**Comment by ghost** [comment]
closed as #18544 is merged.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15494">issues.joomla.org/tracker/joomla-cms/15494</a>.</sub>
