### ISSUE TITLE
[4.0] Bug in sidebar

### ISSUE THREAD

**Issue by rjcf18** [joomla/joomla-cms#15490]
### Steps to reproduce the issue

Hover over the side bar and click on Components -> Contacts, then click on Content, next click again on Components and finally click on Banners, if you scroll all the way down you'll see that some of the sidebar subitems overlap with other sidebar items, you can see what I mean in the following image:

![deepinscreenshot20170423165313](https://cloud.githubusercontent.com/assets/6710380/25315044/865fd556-2846-11e7-92c5-d8236ff9fce1.png)
 
### Expected result

No overlapping in the sidebar:
![deepinscreenshot20170423170224](https://cloud.githubusercontent.com/assets/6710380/25315058/b4f99a46-2846-11e7-88de-9d9f73e91bf0.png)

### Actual result

Overlapping in the sidebar:
![deepinscreenshot20170423165313](https://cloud.githubusercontent.com/assets/6710380/25315044/865fd556-2846-11e7-92c5-d8236ff9fce1.png)

### System information

Joomla! 4.0.0-dev
OS: Linux Deepin 15.3
Kernel: 4.4.0-3-deepin-amd64
Google Chrome: 56.0.2924.76 (64 bit)
PHP: 7.0.12-2
MySQLi 5.7.15-1

**Comment by C-Lodder** [comment]
I suppose this can be closed as we have a WIP PR in place: https://github.com/joomla/joomla-cms/pull/15430

**Comment by rjcf18** [comment]
Yep you're right this issue would only be valid should the side bar remain the same. If the new side bar changes are adopted then you can disregard this :)

**Comment by franz-wohlkoenig** [comment]
@rjcf18 can this Issue be closed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15490">issues.joomla.org/tracker/joomla-cms/15490</a>.</sub>

**Comment by rjcf18** [comment]
Sure of course :)
