### ISSUE TITLE
[com_fields] Default Users Groups parameter to be corrected

### ISSUE THREAD

**Issue by stellainformatica** [joomla/joomla-cms#15501]
### Steps to reproduce the issue
- Create a new custom field type "usergrouplist" one for contents and one for users
- in Default User Groups put some ID of users
- in an article look that custom field
- in the creation of a user in frontend look that custom field

### Actual result
- in the content the ID doesn't affect the list of user groups
- in the user creation, just the last ID is taken as default

**Comment by franz-wohlkoenig** [comment]
@stellainformatica Usergroup-ID is set as Default but you mean only Default should be shown?

### Field Type "Usergrouplist" in Content:

#### 1/2. Set one Usergroup-ID in ` Default User Groups `:

![content-b](https://cloud.githubusercontent.com/assets/8235763/25577566/48fce506-2e67-11e7-85dc-09760422bdbd.JPG)

#### 2/2 Got in Frontend:

![content-f](https://cloud.githubusercontent.com/assets/8235763/25577653/24513b20-2e68-11e7-99f6-8960ac01c548.JPG)


### Field Type "Usergrouplist" in User:

#### 1/2. Set one Usergroup-ID in ` Default User Groups `:

![bildschirmfoto 2017-05-01 um 12 06 55](https://cloud.githubusercontent.com/assets/8235763/25577492/b38f792a-2e66-11e7-85f7-190d1200499d.JPG)

#### 2/2 Got in Frontend at Registration:

![user-f](https://cloud.githubusercontent.com/assets/8235763/25577628/d98d96ec-2e67-11e7-904b-0d26ba3c15f9.JPG)

**Comment by stellainformatica** [comment]
Hi franz, try putting some IDs, not only one<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15501">issues.joomla.org/tracker/joomla-cms/15501</a>.</sub>

**Comment by brianteeman** [comment]
As far as i can tell this works perfectly correctly when it is set to MULTIPLE in the field or when it is set to from plugin and the plugin is set to multiple

## Article Screenshot
![screen shot 2017-05-23 at 11 50 56](https://issues.joomla.org/uploads/1/2d2275acef213daed1922e0c9cf5e0c2.png)

## User screenshot
![screen shot 2017-05-23 at 11 52 57](https://issues.joomla.org/uploads/1/0c7543a34b9067c68ebad0e0124eb29f.png)

## Registration screenshot
![screen shot 2017-05-23 at 11 55 27](https://issues.joomla.org/uploads/1/ebcb1f42554814016d643ba0ebad8f4e.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15501">issues.joomla.org/tracker/joomla-cms/15501</a>.</sub>

**Comment by Quy** [comment]
Cannot reproduce.

**Comment by Quy** [comment]
@stellainformatica Unable to reproduce in v3.7.3. Can you provide screenshots if still not working for you?

**Comment by brianteeman** [comment]
I am closing this due to a lack of response to the question of @quy It can always be reopened
