### ISSUE TITLE
[3.7+] Hanging nonsensible placing of text on discover page

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15507]
on page: administrator/index.php?option=com_installer&view=discover

<img width="783" alt="screen shot 2017-04-24 at 14 24 29" src="https://cloud.githubusercontent.com/assets/400092/25339224/cc233282-28f9-11e7-95c8-cc7cfa59fb17.png">

### Expected result

"Discover extensions that have not gone through the normal installation process." should be somewhere sensible

### Actual result

"Discover extensions that have not gone through the normal installation process." is actually hanging at the bottom of the page looking out of place

**Comment by franz-wohlkoenig** [comment]
Confirmed.
### System information
3.7.0-rc4
macOS Sierra, 10.12.4
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by zero-24** [comment]
> "Discover extensions that have not gone through the normal installation process." should be somewhere sensible

Something like a warning above the seache tools?

**Comment by PhilETaylor** [comment]
I would say just delete it, none of the other left tabs on this screen have explanations like this

**Comment by zero-24** [comment]
The updates have something similiar. And i guess the is not that clearly to everyone.

**Comment by PhilETaylor** [comment]
> The updates have something similiar

I dont know what you are referring to? Nothing here:

<img width="1286" alt="screen shot 2017-04-24 at 15 10 31" src="https://cloud.githubusercontent.com/assets/400092/25341266/309399fe-2900-11e7-9bd7-a0cf2d5a7955.png">

**Comment by zero-24** [comment]
the blue message above the seach tools :smile:

**Comment by brianteeman** [comment]
That short sentence used to be a really big wall of text

**Comment by PhilETaylor** [comment]
Thats more of a warning than a notice

The "discover" sentence is more neither a notice or a warning, its an explanation of what the page does - which we dont do elsewhere, thats what the help button is for! 

It looks wrong just being plonked at the bottom of the page in plain text, it looks out of place and no in fitting with the rest of Joomla

**Comment by zero-24** [comment]
Agree. Whaat about patching it out? ;)

**Comment by brianteeman** [comment]
@zero-24 see the conversation when the message was changed

**Comment by brianteeman** [comment]
Closed as we have a PR see #15528
