### ISSUE TITLE
[com_fields] A frontend Author has no ACL to set new media in com_fields

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15518]
### Steps to reproduce the issue

Install Joomla 3.7.0
Create a custom field of type media with full defaults
Login to the front end as an Author, ready to submit your new content... 

### Expected result

That a front end "Author" (A User with "Author group membership") should be able to select some media in the custom field

By default, the ACL for "Edit Custom Field Value" is inherited, which is denied.

### Actual result

When submitting content on the frontend, an Author can only see the default value (or nothing) and cannot click the missing select button to launch a modal to select some media. 

One would assume that an Author should be able to select something for this field?

<img width="459" alt="screen shot 2017-04-24 at 21 16 48" src="https://cloud.githubusercontent.com/assets/400092/25356763/5aeba5d8-2933-11e7-830b-7af1fee14a1d.png">

**Comment by PhilETaylor** [comment]
Yes I know you could mess with the ACL to achieve this, but we should be providing sound defaults for the shipped default usergroups for each type of field in com_fields

**Comment by franz-wohlkoenig** [comment]
@laoneo any Thoughts on this Issue?

**Comment by laoneo** [comment]
From a security point of view, I would go the way that an admin needs to actively activate the right permissions for non super admins. So I would leave it as it is. But I'm just a developer and not a security expert.

**Comment by Bakual** [comment]
You could set the global ACL settings for this action in the database. We can adjust that for new installations. But we can't do it for upgraded sites.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15518">issues.joomla.org/tracker/joomla-cms/15518</a>.</sub>
