### ISSUE TITLE
com_finder advanced search text hard to read without missing emphasis

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15519]
### Steps to reproduce the issue

Install Joomla 3.7.0 (defaults, protostar template)
Go to http://127.0.0.1:8000/index.php?option=com_finder
Click Advanced Search

### Expected result

Maybe some bold on the terms to actually search, they are surrounded by spans already, looks like something got lost

### Actual result

Garbled english sentences that make no sense when read to ones self, 
<img width="741" alt="screen shot 2017-04-24 at 21 26 44" src="https://cloud.githubusercontent.com/assets/400092/25357190/d19162ee-2934-11e7-93ab-e7d730ff896d.png">

**Comment by franz-wohlkoenig** [comment]
+1 for Suggestion make Sentences better readable like bold for "This", "that".

**Comment by brianteeman** [comment]
closed as we have a PR for testing #15530
