### ISSUE TITLE
Advanced Permissions Report for super admin reports not allowed

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15516]
### Steps to reproduce the issue

Install Joomla 3.7.0
Login to admin 
Go to User Manager
Click "Advanced Permissions Report" next to the Super Admin 

### Expected result

That it shows a Super Admin can do everything! 

### Actual result

The red circles say that most actions are "not allowed"

<img width="1747" alt="screen shot 2017-04-24 at 21 02 46" src="https://cloud.githubusercontent.com/assets/400092/25356251/660d1cd2-2931-11e7-9a1c-665177ad9ce0.png">

**Comment by zero-24** [comment]
Yes this is correct as you have the super amin permission (see the green) you are allowed to do every thing ;)

**Comment by PhilETaylor** [comment]
If Im allowed to do everything then there should be no red circles... it should be full of green ticks! 

If I "dont get it" then 10000s of others will not too :)

**Comment by brianteeman** [comment]
See #14959

**Comment by zero-24** [comment]
Closing as dublicate of #14959

**Comment by alikon** [comment]
@zero-24  i'm not sure this is correct
i would prefer something like this instead
![issue](https://cloud.githubusercontent.com/assets/181681/25378035/747015cc-29a9-11e7-86f0-ff703d5c3f3b.PNG)
