### ISSUE TITLE
ajax search not working

### ISSUE THREAD

**Issue by Eggeriley** [joomla/joomla-cms#15512]
1) go to gigharborchamber.net
2) try the search bar, ajax results wont show up..
i get his error in the console 
XMLHttpRequest cannot load https://www.gigharborchamber.net/index.php?type=raw&option=com_search&view=…ny&ordering=newest&limit=10&searchword=alan&tmpl=component&r=1493059609384. Response for preflight is invalid (redirect)
any help?

1) i running the latest version of joomla on the latest version of gantry 5 on rockethemes protean template, everything is up to date.

the search module i am using is rockthemes ajax search but their support is not helping me..

**Comment by zero-24** [comment]
@Eggeriley we can not support any individual site issues here. This is a issue Tracker for bugs in the Core CMS and not 3rd party extentensions. Please open a thread at https://forum.joomla.org 

I'm going to close this for now. Thanks for understanding.
