### ISSUE TITLE
Blindly calling com_ajax gives a correct error badly templated

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15514]
### Steps to reproduce the issue

/index.php?option=com_ajax

### Expected result

The error message in a correctly formatted HTML red bootstrap alert message, or some json parsable error message? 

thoughts?

### Actual result

<img width="1008" alt="screen shot 2017-04-24 at 20 43 25" src="https://cloud.githubusercontent.com/assets/400092/25355463/ac6b3bc6-292e-11e7-8f93-a09d005ae782.png">

### System information (as much as possible)

<= Joomla 3.7.0

**Comment by mbabker** [comment]
`JErrorPage` in 3.x isn't request format aware and as such uses `JDocumentError` to spit out error responses, which only supports HTML.

4.0 is format aware.  We'd have to scrutinize it a little more but in theory it'd be possible to backport https://github.com/joomla/joomla-cms/tree/4.0-dev/libraries/src/CMS/Error into 3.8 (IIRC all the work is self-contained into https://github.com/joomla/joomla-cms/commit/9a2fe89999f170cc920ff20c4e9e74d11e251088).

**Comment by mbabker** [comment]
The error handling layer is already refactored in 4.0 and the odds of this getting attention in 3.x are slim to none.  So, closing.  If someone wants to take a stab at it what I pointed out above is still an option.
