### ISSUE TITLE
Advanced Permissions Report Link makes rows even more messy

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15517]
### Steps to reproduce the issue

Install Joomla 3.7.0 
Go to User Manager

### Expected result

Something pretty, maybe move Advanced Permissions Report to the toolbar? 
Or have all three of the elements in line? 
thoughts? 

### Actual result

three lines per user! Gulp! 
<img width="240" alt="screen shot 2017-04-24 at 21 06 11" src="https://cloud.githubusercontent.com/assets/400092/25356421/0116192c-2932-11e7-8964-45ae19b7728c.png">

**Comment by khikmatullaev** [comment]
![image](https://cloud.githubusercontent.com/assets/11577281/25357924/fa4d85cc-293f-11e7-922b-ce6beb1e6966.png)
something like this?

**Comment by PhilETaylor** [comment]
I think that is better (the menu bar button, with associated JS to check if you selected just one checkbox) Although the actual user row could still be better laid out with better use of the horizontal space for the dates, using some of the wasted space in the name area...

**Comment by khikmatullaev** [comment]
Maybe will be better if we add the bottoms before the name of user? Something like in the articles

**Comment by brianteeman** [comment]
See https://github.com/joomla/joomla-cms/pull/22190

**Comment by ghost** [comment]
@PhilETaylor if #22190 is fine can you please close this issue?

**Comment by Quy** [comment]
Test #22209 for J3
