### ISSUE TITLE
typo in default dummy text 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15515]
### Steps to reproduce the issue

install joomla with dummy content
see the glaring typo of a missing spaces

### Expected result

"configuration to"
"too. Don't"
"address. You"

### Actual result
<img width="735" alt="screen shot 2017-04-24 at 20 52 48" src="https://cloud.githubusercontent.com/assets/400092/25355857/048e01fc-2930-11e7-923b-c88aa52a745b.png">

### System information (as much as possible)

These places: 
https://github.com/joomla/joomla-cms/search?utf8=%E2%9C%93&q=configurationto&type=

**Comment by brianteeman** [comment]
Closed as there is a PR
