### ISSUE TITLE
[3.7.0] Default installation dummy text lies

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15513]
### Steps to reproduce the issue

Install Joomla with default content (I forgot which one I used) 

Go to the News menu item

see:

<img width="994" alt="screen shot 2017-04-24 at 20 18 50" src="https://cloud.githubusercontent.com/assets/400092/25354636/9f74f28e-292b-11e7-95e2-556d96c34cd6.png">

### Expected result

No Lies

### Actual result

The text lies :) 

> "The module on the left shows a list of older articles."

When it doesnt :) 

### System information (as much as possible)

Joomla 3.7.0 (night before release)

**Comment by zero-24** [comment]
@PhilETaylor can you send a PR that fixes that issue? You can find the SQL's for all three database systems here:  https://github.com/joomla/joomla-cms/tree/staging/installation/sql

Thanks!

**Comment by Bakual** [comment]
The sample data in general is in a very bad shape.
Anyone remembers the template "Atomic" (https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/sample_testing.sql#L267) 😆 

I did a PR long ago (https://github.com/joomla/joomla-cms/pull/7680) which would put all those strings into language files, which then hopefully would make fixing stuff like this easier.
It still would need someone looking over all those texts or maybe better just rework the sample data (eg for J4).

**Comment by PhilETaylor** [comment]
No. Im not in PR mode, Im in rapid fire test mode.

**Comment by PhilETaylor** [comment]
> The sample data in general is in a very bad shape.

Indeed, but first impressions count :)

**Comment by rdeutz** [comment]
The text doesn't lies it is only written under different circumstances

**Comment by richard67** [comment]
No, it describes alternative facts ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15513">issues.joomla.org/tracker/joomla-cms/15513</a>.</sub>

**Comment by brianteeman** [comment]
See #15526
