### ISSUE TITLE
[3.7.0] Error on reinstalling languages

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15522]
### Steps to reproduce the issue

Install Joomla 3.7.0 with full defaults - no more languages just the defaults 

Go to Extensions -> manage -> install languages

Click **INSTALL** next to **Albanian** language
Click **REINSTALL** next to **Albanian** language

### Expected result

That  **Albanian** language is reinstalled 

### Actual result
<img width="1440" alt="screen shot 2017-04-24 at 22 23 46" src="https://cloud.githubusercontent.com/assets/400092/25359384/f088d256-293c-11e7-97a1-2dff737b0b58.png">

### Additional comments

HOWEVER note that other languages DO NOT give this error - for example, installing and reinstalling Afrikaans gives "Installation of the package was successful." and no error

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.
### System information
3.7.0-rc4
macOS Sierra, 10.12.4
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by infograf768** [comment]
As no recent news from this TT, I will correct this with  a new release.
The issue is that the package manifest does not contain `method="upgrade"`

**Comment by PhilETaylor** [comment]
If possible please check them all ;-) as this is not just Albanian :)

**Comment by infograf768** [comment]
If I had a list it would help...

**Comment by PhilETaylor** [comment]
well I was just randomly clicking the install/reinstall buttons :)

**Comment by infograf768** [comment]
Corrected packs
Albanian, Belarussian, Montenegrin, Uyghur and Vietnamese.
As soon as the script is done they will be available to install and reinstall.
