### ISSUE TITLE
Afrikaans language string issue

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15523]
### Steps to reproduce the issue

Not sure this is the the right place for this report... 

Install Joomla 3.7.0 
install Afrikaans language set as default for frontend
do a search for an invalid 1 char string

### Expected result

Afrikaans equivalent of "Search term must be a minimum of 3 characters and a maximum of 200 characters"

### Actual result

Note the html entity being displayed
Note that it says 20 and not 200 (infact other languages, (like arabic!) also say 20 chars, whereas the english says 200!!) 

<img width="578" alt="screen shot 2017-04-24 at 22 34 21" src="https://cloud.githubusercontent.com/assets/400092/25359738/2f962510-293e-11e7-84b6-eefb6db1d8a5.png">

`Soektog term moet 'n minimum van 3 karakters en 'n maksimum van 20 karakters h&ecirc;.`

**Comment by infograf768** [comment]
It is indeed not the place to post this...
One should have contacted the TT coordinator for Afrikaans
https://community.joomla.org/translations/joomla-3-translations.html#af-za

But it seems you found a bug
The lower and upper limits are defined by the TT in the xx-XX.localise.php
which gives for Afrikaans **and** en-GB
```
/**
	 * Returns the lower length limit of search words
	 *
	 * @return	integer  The lower length limit of search words.
	 * @since	1.6
	 */
	public static function getLowerLimitSearchWord() {
		return 3;
	}
	/**
	 * Returns the upper length limit of search words
	 *
	 * @return	integer  The upper length limit of search words.
	 * @since	1.6
	 */
	public static function getUpperLimitSearchWord() {
		return 20;
	}
	/**
	 * Returns the number of chars to display when searching
	 *
	 * @return	integer  The number of chars to display when searching.
	 * @since	1.6
	 */
	public static function getSearchDisplayedCharactersNumber() {
		return 200;
	}
```

`COM_SEARCH_ERROR_SEARCH_MESSAGE="Search term must be a minimum of %1$s characters and a maximum of %2$s characters."`

Therefore the error is created by this code
```
if (SearchHelper::limitSearchWord($searchWord))
		{
			$error = JText::sprintf('COM_SEARCH_ERROR_SEARCH_MESSAGE', $lower_limit, $upper_limit);
		}
```
The Afrikkans string is not following the en-GB value
`COM_SEARCH_ERROR_SEARCH_MESSAGE="Soektog term moet 'n minimum van 3 karakters en 'n maksimum van 20 karakters h&ecirc;."`

But he tried to reflect what should be (forget the h&ecirc; for now);

we should have indeed
`Search term must be a minimum of 3 characters and a maximum of 20 characters.

I guess the error is here:
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/language/language.php#L590-L598

**Comment by infograf768** [comment]
By curiosity I looked at 1.6.0 and I found that we had there the right code
```
/**
	 * getUpperLimitSearchWord function
	 *
	 * This method returns an upper limit integer for length of search words
	 *
	 * @return	integer	The upper limit integer for length of search words (20 if no value was set for a specific language)
	 * @since	1.6
	 */
	public function getUpperLimitSearchWord() {
		if ($this->upperLimitSearchWordCallback !== null) {
			return call_user_func($this->upperLimitSearchWordCallback);
		}
		else {
			return 20;
		}
	}
```

**Comment by infograf768** [comment]
hhm
https://github.com/joomla/joomla-cms/issues/5103
https://github.com/joomla/joomla-cms/pull/5121

confused...

**Comment by infograf768** [comment]
Basically this means that the upperlimit setting is always overriden if <200
 weird

**Comment by brianteeman** [comment]
@infograf768 did you forget about this?

**Comment by infograf768** [comment]
After thought: #5121 was correct. Only the Afrikkans string is incorrect.
For 4.0, we should change the default upperlimit to 200 in en-GB.localise.php and let this know to TTs
