### ISSUE TITLE
Problem while changing article's category

### ISSUE THREAD

**Issue by Saeedghb** [joomla/joomla-cms#15525]
### Steps to reproduce the issue
1- Change the administrator language to Persian.
2- Add new article (just fill in the title and text) and save.
3- Change the category.

### Expected result
Expected to save the changes (article's category)

### Actual result
After changing category field, the page reloads and renders improperly. (see attached screenshot)

### System information (as much as possible)
Joomla! 3.7.0-rc4
Joomla language: Persian (RTL)
Google chrome (latest version)
Windows 7
Run on localhost - Wamp: Apache/2.4.9 (Win64) PHP/5.5.12

### Additional comments
![screen shot 2017-04-25 at 08 38 25](https://issues.joomla.org/uploads/1/7e9f1d57dcd4c147ed807a623eb14099.png)

**Comment by dgt41** [comment]
You need the Persian language for 3.7

**Comment by Saeedghb** [comment]
Persian language is currently installed.
I first installed Joomla 3.7 RC4 then installed Persian language through installation manager.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15525">issues.joomla.org/tracker/joomla-cms/15525</a>.</sub>

**Comment by infograf768** [comment]
I can't reproduce using  persian as admin (on staging)
I think you have an issue with UTF8 and your database

@dgt41 
The big change for Persian and which needs indeed a 3.7.0.1 version concerns calendar, not this.
![screen shot 2017-04-25 at 11 32 25](https://cloud.githubusercontent.com/assets/869724/25378639/e90cd9be-29aa-11e7-94ab-d22e137c3326.png)

**Comment by Saeedghb** [comment]
@infograf768

Just realized that the problem occurs when we have defined a custom field.
Not matters UTF8 Characters are used in title, custom fields,... or not. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15525">issues.joomla.org/tracker/joomla-cms/15525</a>.</sub>

**Comment by saharmk** [comment]
I also tried to reproduce and faced an error. see attached screenshot.

The Problem occurs when the article has custom fields.

Using PHP 5.6.3
Joomla 3.7 RC4
Installed Persian language for administrator.



![screen shot 2017-04-25 at 12 23 11](https://issues.joomla.org/uploads/1/d20b534f706e1a66182eac1a36da6a09.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15525">issues.joomla.org/tracker/joomla-cms/15525</a>.</sub>

**Comment by Quy** [comment]
Please see if this PR #15294 will fix your issue.

**Comment by Saeedghb** [comment]
@Quy 

Thank you. PR #15294 does not fix this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15525">issues.joomla.org/tracker/joomla-cms/15525</a>.</sub>

**Comment by prmasadi** [comment]
I got this error
Using PHP 5.6.19
Joomla 3.7
Installation Persian language management
![screen shot 2017-04-27 at 05 49 20](https://issues.joomla.org/uploads/1/03001ded57879d940c5329667b975d30.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15525">issues.joomla.org/tracker/joomla-cms/15525</a>.</sub>

**Comment by infograf768** [comment]
which version of the Persian language are you using ? 3.6.5.3, although not fully ready for 3.7.0, provides correct date time (not speaking here of custom fields aspect)

**Comment by robynlingen** [comment]
I can confirm this on all of my Joomla 3.7 sites. If I create a custom field, I am unable to change categories on either an existing article, or a new article. I am also unable to save any custom fields. The behavior is as described above. The page reloads to the control panel without having saved the change. The article is then locked. When I remove any custom fields, everything works as normal. All of my sites (27) are in English.

**Comment by franz-wohlkoenig** [comment]
Can't confirm on clean 3.7.1-dev-Install, changing Categories in Articles using custom Fields works as expected.

@robynlingen Assuming you updated from 3.*?

**Comment by robynlingen** [comment]
Yes, that is correct. In all cases Joomla 3.6.5 updated to 3.7 either via Joomla backend, or via c-panel auto-updater for just a few of my sites. I'll test a clean install.

**Comment by dgrammatiko** [comment]
Is this still valid?

**Comment by brianteeman** [comment]
Closed due to lack of response. assuming it has been fixed elsewhere
