### ISSUE TITLE
Can not save external link

### ISSUE THREAD

**Issue by Orsey** [joomla/joomla-cms#15534]
I can not save external link
"skype:vasya"
"skype://vasya"
"viber:+38099999999"
"viber://+38099999999"
I get message "Save not permitted" when click "Save" button.

Joomla 3.6.5

**Comment by franz-wohlkoenig** [comment]
@Orsey can you give System information (like Joomla Version)?

**Comment by Orsey** [comment]
@franz-wohlkoenig System Information was added.

**Comment by brianteeman** [comment]
Thats because skype is only in the provisional list of supported uri schema in the standards and viber is not in the list at all and joomla doesnt support them

https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

**Comment by Orsey** [comment]
And what? How I can disable this verification. I don't need in this functional. Now I must use code "& # 0 5 8 ;" and Joomla save this link very well.

**Comment by bertmert** [comment]
> Thats because skype is only in the provisional list of supported uri schema ... and viber is not in the list ..

`git` is marked as provisional, too. 
`url` and `rlogin` are not in the list.

but Joomla supports them. See https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/controllers/item.php#L333-L334

**Comment by bertmert** [comment]
Please test, discuss or close PR https://github.com/joomla/joomla-cms/issues/15537

**Comment by franz-wohlkoenig** [comment]
closed as having PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15534">issues.joomla.org/tracker/joomla-cms/15534</a>.</sub>
