### ISSUE TITLE
Article Manager is now sorting by ID ascending by default when it should be ID descending

### ISSUE THREAD

**Issue by sseguin613** [joomla/joomla-cms#15549]
### Steps to reproduce the issue
1. Update to Joomla 3.7.0.
2. Go into Article Manager.
3. Default sorting of articles will display in the order of ID Ascending, yet the drop down box is set and showing ID Descending. Clicking RESET next to search gets it to display correctly.

### Expected result
Articles should be sorted by ID Descending.

### Actual result
Articles are being sorted by ID Ascending, despite the drop down at the top saying ID Descending.

### System information (as much as possible)
PHP7.1
MySQL 5.6

### Additional comments
This is occurring on all the sites I have updated to Joomla 3.7.0

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.

**Comment by brianteeman** [comment]
If i remember correctly this is the expected behaviour. It always used to be this way and it was changed in 3.6.5 but that change has been reverted. @rdeutz can you confirm

**Comment by rdeutz** [comment]
We reverted a change what is default ordering value for a new article (was in 3.6.something), this here seems to me something different.

**Comment by brianteeman** [comment]
Ok thanks - I guess I still need more caffeine

**Comment by franz-wohlkoenig** [comment]
It's better Workflow to get newest Articles on top, not 10 Years old. One Step further is let User decide whats her preferred Default.

**Comment by sseguin613** [comment]
I agree with what franz-wohlkoenig suggested above. If we can decide the default ordering.

In any case, I'd really like the default to be back to the way it was before 3.7.0, with ID descending (as the selector shows by default) rather than Ascending.

Is there an easy fix I can apply to accomplish this before it gets patched?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15549">issues.joomla.org/tracker/joomla-cms/15549</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
> Is there an easy fix I can apply to accomplish this before it gets patched?

@sseguin613 if someone take Time to write a PR.

**Comment by Bakual** [comment]
Closing as there is PR #15655

**Comment by sseguin613** [comment]
Thank you for the information. However, whether it was changed or not, the drop down at the top of the Article Manager shows by default ID Descending, when it is displaying as ID Ascending. So in the end it still is not matching up with the ordering and what the drop down is displaying by default.
