### ISSUE TITLE
No 404 if you call a unpublished page in some setups

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#15544]
### Steps to reproduce the issue

- install staging
- with testing data
- enable conservative caching
- unpublish the article with the ID 18 ('Second Blog Post')
- try to call the article with the following URL:
www.example.org/index.php/article-category-blog/18-#
try to call the article with the following URL:
- www.example.org/index.php/article-category-blog/18-asdjhasd

### Expected result

404 in both cases

### Actual result

![image](https://cloud.githubusercontent.com/assets/2596554/25405478/b8bfe662-2a03-11e7-94e7-cf6623ad4267.png)

### System information (as much as possible)

3.7.0 stable as of today

**Comment by rdeutz** [comment]
Problem confirmed

**Comment by zero-24** [comment]
Closing as there is a PR at #15558
