### ISSUE TITLE
Warning after upgrading from 3.6 to 3.7

### ISSUE THREAD

**Issue by sanio** [joomla/joomla-cms#15548]
### Steps to reproduce the issue

No Idea

### Expected result

no any Warnings

### Actual result
Warning: Cannot use a scalar value as an array in /var/www/web3/web/libraries/cms/html/html.php on line 693
Warning messages in lines 693 694 695 696 and 697 

### System information (as much as possible)
Ubuntu 6.14 php 7.0 apache2 with php-fpm 

### Additional comments
My very first report, am not sure that my compnent has no errors in my code

I think warning generated when i use this code
JHtml::script(JUri::base() . 'components/com_rentflat/assets/test.js', true);  in my default.php view

![warning](https://cloud.githubusercontent.com/assets/3997140/25407753/31cb3326-2a14-11e7-8ebe-49931c6f55aa.png)

**Comment by wilsonge** [comment]
OK I can confirm this on code review. Seems like the code we added in as a b/c layer expects that you have 3 parameters (the first always being the resource, the second the mootools inclusion, 3rd the relative to media directory). Unfortunately as we are only injecting a single parameter here the b/c compatible code https://github.com/joomla/joomla-cms/blob/3.7.0/libraries/cms/html/html.php#L673-L676 isn't triggered and therefore we think we have an options array (which isn't - it's just a boolean) and everything falls apart

**Comment by sanio** [comment]
dear wilsonge , 
could you pls tell how to suppress this warning

**Comment by zero-24** [comment]
-JHtml::script(JUri::base() . 'components/com_rentflat/assets/test.js', true);

+$options = array('framework' => true);
+JHtml::script(JUri::base() . 'components/com_rentflat/assets/test.js', $options);

This should do the trick for now.

**Comment by zero-24** [comment]
@wilsonge what about a empty check too? So we do not pass that if we have empty arrays?

**Comment by zero-24** [comment]
Maybe also

```
if (!is_array($options) || !is_array($attribs))
```

Should do the trick too as only one can also be passed.

**Comment by wilsonge** [comment]
I mean is `if (!is_array($options)` enough?

**Comment by weeblr** [comment]
@wilsonge Dropping the test on $attribs fixed the problem for me indeed, ie
`// B/C before 3.7.0
if (!is_array($options) /*&& !is_array($attribs) */)
{`

**Comment by wilsonge** [comment]
Can you do a PR @weeblr - currently not at a computer

**Comment by weeblr** [comment]
Hi George, not really, I am struggling to fix all the issue on sites being updated. There is another B/C break associated with the changes in internal representation of the scripts. You have a B/C layer when **adding a script**, but because the internal representation has changed, when using $document->getHeadData(), the data returned also changed format, and this is breaking quite some code we have on the sites for enhanced caching.

Will try.

**Comment by weeblr** [comment]
Here it is https://github.com/joomla/joomla-cms/pull/15600

**Comment by sanio** [comment]
Thanks a lot

**Comment by jeeperinaz** [comment]
#15600 was already applied and I still get these errors. Any Eta? I'm on 3.7.3.. 
socialhour.club

**Comment by ghost** [comment]
@jeeperinaz can you please open a new Issue givin exact Informations as this is a closed one?
