### ISSUE TITLE
[com_media] Unable to navigate to directories with non-latin characters

### ISSUE THREAD

**Issue by bartnikj** [joomla/joomla-cms#15543]
### Steps to reproduce the issue

1. On the backend go to Artciles -> Media
2. Try to open a directory with non-latin characters (for example: "2017/2017-01-styczeń")

### Expected result

The directory should open

### Actual result

Being redirected to images root directory

### System information (as much as possible)

Noticed since Joomla 3.5. Still happens in 3.7. Seems to be browser independent. Happened in PHP 5.2-7.0.

### Additional comments

You could also navigate to a folder directly via /administrator/index.php?option=com_media&view=mediaList&tmpl=component&folder=2017/2017-01-stycze%C5%84

### Possible solution

Seems to be a regex problem with [JInput filter "path"](https://docs.joomla.org/Retrieving_request_data_using_JInput#Getting_Values) that is used in list.php model of com_media. Regex:
`$pattern = '/^[A-Za-z0-9_-]+[A-Za-z0-9_\.-]*([\\\\\/][A-Za-z0-9_-]+[A-Za-z0-9_\.-]*)*$/';`

**Comment by khikmatullaev** [comment]
If you want to create the folder with "2017/2017-01-styczeń" name you would get the error
![image](https://cloud.githubusercontent.com/assets/11577281/25405144/a64972ec-2a02-11e7-8480-57988d58b494.png)

**Comment by khikmatullaev** [comment]
Or did you create a folder not by Joomla admin?

**Comment by bartnikj** [comment]
This one was created using JCE. But you could create it in many different ways. Still a valid path though.

**Comment by infograf768** [comment]
This is totally OK. A possible url path should not contain unicode characters. 
If we wanted to let do that, such names should be percent encoded (see unicode aliases).
It is a very different situation from folders path used in your OS itself.

Closing

**Comment by bartnikj** [comment]
How is not being able to navigate to an existing folder with valid path because of that bug "totally ok"?
