### ISSUE TITLE
htaccess.bak renamed to .htaccess on update

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15542]
### Expected result

Dont do this: https://github.com/joomla/joomla-cms/blob/4e13f90b67ab461a7e399dc7183441c68869bbc4/administrator/components/com_joomlaupdate/restore.php#L7882

### Actual result

htaccess.bak renamed to .htaccess on update overwriting valid .htaccess ?

### Additional comments
https://twitter.com/joovlaki/status/856956148133580801
@brianteeman @nikosdion

**Comment by AlexRed** [comment]
I can confirm<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15542">issues.joomla.org/tracker/joomla-cms/15542</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
closed as having PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15542">issues.joomla.org/tracker/joomla-cms/15542</a>.</sub>

**Comment by AlexRed** [comment]
Sorry, where is the PR ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15542">issues.joomla.org/tracker/joomla-cms/15542</a>.</sub>

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/pull/15576
