### ISSUE TITLE
(SOLVED) 404 - Category not found and 500 - Wrong category ID after upgrade to 3.7

### ISSUE THREAD

**Issue by ChristianGrieger** [joomla/joomla-cms#15545]
### Steps to reproduce the issue

Upgrade Joomla 3.6.5 to Joomla 7 from Joomla-Backend

### Expected result

Normal working access to categories.

### Actual result

404 - Category not found
500 - Wrong category ID

 (i checked the ids and they are right)
Call stack
#	Function	Location
1	JError::raise()	JROOT/libraries/legacy/error/error.php:277
2	JError::raiseError()	JROOT/libraries/legacy/view/category.php:127
3	JViewCategory->commonCategoryDisplay()	JROOT/components/com_content/views/category/view.html.php:72
4	ContentViewCategory->display()	JROOT/libraries/legacy/controller/legacy.php:671
5	JControllerLegacy->display()	JROOT/components/com_content/controller.php:113
6	ContentController->display()	JROOT/libraries/legacy/controller/legacy.php:709
7	JControllerLegacy->execute()	JROOT/components/com_content/content.php:39
8	require_once()	JROOT/libraries/cms/component/helper.php:394
9	JComponentHelper::executeComponent()	JROOT/libraries/cms/component/helper.php:369
10	JComponentHelper::renderComponent()	JROOT/libraries/cms/application/site.php:191
11	JApplicationSite->dispatch()	JROOT/libraries/cms/application/site.php:230
12	JApplicationSite->doExecute()	JROOT/libraries/cms/application/cms.php:265
13	JApplicationCms->execute()	JROOT/index.php:49

### System information (as much as possible)

PHP erstellt für	Linux dd38604 4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64
Datenbankversion	5.7.15-nmm5-log
Datenbankzeichensatz	utf8_general_ci
Datenbankverbindungszeichensatz	utf8mb4_general_ci
PHP-Version	7.1.1-nmm1
Webserver	Apache
PHP-Interface für den Webserver	fpm-fcgi
Joomla!-Version	Joomla! 3.7.0 Stable [ Amani ] 25-April-2017 15:36 GMT
Joomla!-Plattform-Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments

I just upgraded my joomla and tried to access the menu items to check if all is working well.
All content is working just all categorie menu items and direct access tries end in 404. I already tried to to recreate the categories and to rebuild the menu entries but get the same result. Also a new install of the core files did not help.

Can anyone provide me with a fix for the problem please? I need to finish the website :(

![error1](https://cloud.githubusercontent.com/assets/8712219/25406904/a2cbf634-2a08-11e7-841e-8e227cd72653.PNG)
![error2](https://cloud.githubusercontent.com/assets/8712219/25406903/a2cbdad2-2a08-11e7-8121-dccdf959e4c0.PNG)
![category](https://cloud.githubusercontent.com/assets/8712219/25406905/a2cd14ec-2a08-11e7-9ebc-0da6ee4b0d51.PNG)

**Comment by zero-24** [comment]
> All content is working just all categorie menu items and direct access tries end in 404.

do you mean a URL like this?
https://www.joomla.org/announcements/release-news/

**Comment by ChristianGrieger** [comment]
Yes the menu item directs to a category list and the category has 6 normal articles attached. It was working well before i updated.

**Comment by ot2sen** [comment]
Should your categories perhaps have gone unpublished? Just saw a user having that issue and they couldn´t publish them and menus not working. They fixed it by publishing categories directly in the database

**Comment by ChristianGrieger** [comment]
No categories are published. Here are the two error i get when try to open that pages.
![error1](https://cloud.githubusercontent.com/assets/8712219/25406904/a2cbf634-2a08-11e7-841e-8e227cd72653.PNG)
![error2](https://cloud.githubusercontent.com/assets/8712219/25406903/a2cbdad2-2a08-11e7-8121-dccdf959e4c0.PNG)
![category](https://cloud.githubusercontent.com/assets/8712219/25406905/a2cd14ec-2a08-11e7-9ebc-0da6ee4b0d51.PNG)

**Comment by zero-24** [comment]
Can you please try to disable the 3rdparty extension attachments?

**Comment by ChristianGrieger** [comment]
I disabled it but the same result stays.

**Comment by zero-24** [comment]
it needs to be atleaset a different error message. As this was the plugin that was mention in the error message.

![image](https://cloud.githubusercontent.com/assets/2596554/25407324/34e22de4-2a0a-11e7-9d86-da69297d682c.png)

**Comment by ChristianGrieger** [comment]
I disabled it on backend but the error stays but i have two different errors so i dont think it comes from it. See picture i added to first post and disabled plugin picture on this post.

Call stack
#	Function	Location
1	JError::raise()	JROOT/libraries/legacy/error/error.php:277
2	JError::raiseError()	JROOT/plugins/attachments/attachments_for_content/attachments_for_content.php:813
3	AttachmentsPlugin_Com_Content->attachmentsHiddenForParent()	JROOT/plugins/content/attachments/attachments.php:312
4	plgContentAttachments->onContentBeforeDisplay()	JROOT/libraries/joomla/event/event.php:70
5	JEvent->update()	JROOT/libraries/joomla/event/dispatcher.php:160
6	JEventDispatcher->trigger()	JROOT/components/com_content/views/category/tmpl/blog.php:25
7	include()	JROOT/libraries/legacy/view/legacy.php:694
8	JViewLegacy->loadTemplate()	JROOT/libraries/legacy/view/legacy.php:229
9	JViewLegacy->display()	JROOT/libraries/legacy/view/category.php:241
10	JViewCategory->display()	JROOT/components/com_content/views/category/view.html.php:260
11	ContentViewCategory->display()	JROOT/libraries/legacy/controller/legacy.php:671
12	JControllerLegacy->display()	JROOT/components/com_content/controller.php:113
13	ContentController->display()	JROOT/libraries/legacy/controller/legacy.php:709
14	JControllerLegacy->execute()	JROOT/components/com_content/content.php:39
15	require_once()	JROOT/libraries/cms/component/helper.php:394
16	JComponentHelper::executeComponent()	JROOT/libraries/cms/component/helper.php:369
17	JComponentHelper::renderComponent()	JROOT/libraries/cms/application/site.php:191
18	JApplicationSite->dispatch()	JROOT/libraries/cms/application/site.php:230
19	JApplicationSite->doExecute()	JROOT/libraries/cms/application/cms.php:265
20	JApplicationCms->execute()	JROOT/index.php:49

and


Call stack
#	Function	Location
1	JError::raise()	JROOT/libraries/legacy/error/error.php:277
2	JError::raiseError()	JROOT/libraries/legacy/view/category.php:127
3	JViewCategory->commonCategoryDisplay()	JROOT/components/com_content/views/category/view.html.php:72
4	ContentViewCategory->display()	JROOT/libraries/legacy/controller/legacy.php:671
5	JControllerLegacy->display()	JROOT/components/com_content/controller.php:113
6	ContentController->display()	JROOT/libraries/legacy/controller/legacy.php:709
7	JControllerLegacy->execute()	JROOT/components/com_content/content.php:39
8	require_once()	JROOT/libraries/cms/component/helper.php:394
9	JComponentHelper::executeComponent()	JROOT/libraries/cms/component/helper.php:369
10	JComponentHelper::renderComponent()	JROOT/libraries/cms/application/site.php:191
11	JApplicationSite->dispatch()	JROOT/libraries/cms/application/site.php:230
12	JApplicationSite->doExecute()	JROOT/libraries/cms/application/cms.php:265
13	JApplicationCms->execute()	JROOT/index.php:49

![bildschirmfoto 2017-04-25 um 23 09 13](https://cloud.githubusercontent.com/assets/8712219/25407860/45032cda-2a0c-11e7-9c83-bf4a68829f50.png)

**Comment by ot2sen** [comment]
Have a site using attachments and it did upgrade from 3.6.5 to 3.7 with no issues

**Comment by ChristianGrieger** [comment]
So looks like i have to switch back to 3.6.5 (backup) tomorrow because i need to finish the project ;(

**Comment by GFLP** [comment]
I just upgraded to 3.7 as well and am now getting a 404 Article Not Found error as well.  
![gflp 404 error](https://cloud.githubusercontent.com/assets/28025441/25409881/afb2a40a-29c8-11e7-8790-d3336130eb1b.JPG)  

I used the search field here and was able to find my site and link to all of the pages and links.  Everything seems normal except the 404 error on the home page.

**Comment by ChristianGrieger** [comment]
Normal article are working well for me just all categories are broken.

**Comment by BastianWie** [comment]
I failed also to reproduce that. I already upgraded multiple joomla installations to the latest version and none of them allowed me to reproduce the issue. Did you use some special plugins or a special template? Can you reproduce the issue with one of the default templates?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15545">issues.joomla.org/tracker/joomla-cms/15545</a>.</sub>

**Comment by csthomas** [comment]
If website on joomla 3.6.5 has category table in db corrupted (incorrect value for columns lft, rgt) then after update to 3.7 all or part of categories may be unpublished or trashed.

**Similar things may occur with menu items.**

Solution could be to delete trashed categories and move unpublished to other place before upgrade to 3.7. Then category table should be repaired.

On joomla 3.7 published column (for menus and categories) is recalculated by query:
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/sql/updates/mysql/3.7.0-2017-03-09.sql

**Comment by ChristianGrieger** [comment]
I get this error when i try to run the query on database:

`Fehler
SQL-Befehl: Dokumentation

UPDATE  `#__categories` AS  `c` INNER JOIN (

SELECT c2.id, 
CASE WHEN MIN( p.published ) >0
THEN MAX( p.published ) 
ELSE MIN( p.published ) 
END AS newPublished
FROM  `#__categories` AS  `c2` 
INNER JOIN  `#__categories` AS  `p` ON p.lft <= c2.lft
AND c2.rgt <= p.rgt
GROUP BY c2.id
)c2 ON c.id = c2.id
SET published = c2.newPublished;

MySQL meldet: Dokumentation

#1146 - Table 'd024caf4.#__categories' doesn't exist `

I checked the database and the table f6p8s_categories exist and also my categories are in the table and published.

**Comment by csthomas** [comment]
@ChristianGrieger This above query won't repair your website but only unpublish/trash subcategories in unpublished/trashed category. It is run for security reason and I'm almost sure that it was run on joomla upgrade.

Similar query was run for `#__menus`. **Please check you menu list, check trashed menu items too.**

**Comment by ChristianGrieger** [comment]
Menu checked and all selected the right way and published. It was working before the update so wrong selected categorie or not published should not be the problem:

![bildschirmfoto 2017-04-26 um 09 07 20](https://cloud.githubusercontent.com/assets/8712219/25422107/f586161e-2a5f-11e7-9bd3-9c877d289f59.png)
![bildschirmfoto 2017-04-26 um 09 07 52](https://cloud.githubusercontent.com/assets/8712219/25422108/f6b4a6ae-2a5f-11e7-8ae6-37d4c0792cae.png)

**Comment by ChristianGrieger** [comment]
@zero-24 , your idea to disable attachments plugin was a good idea but as it looks like to disable the plugin did not help to delete the problem.

I found this article here: http://www.joomlaportal.de/joomla-3-x-allgemeine-fragen/323076-error-invalid-article-parent-id-kategorieblog.html

The solution to solve my problem was to change one line in attachment files:

Datei: plugins/attachments/attachments_for_content/attachments_for_content.php (Zeile: 812)
if ($db->getErrorNum() || count($attachments) == 0)
geändert in:
if ($db->getErrorNum() || count($attachments) === false)

Thank you to all that tried to help me and i really hope it will help someone else!

**Comment by brianteeman** [comment]
Closed as not a joomla core issue

**Comment by jmcameron** [comment]
Regarding the issue with the Attachments extension:  The fix by ChristianGrieger above does seem to work.  I'm working with someone to verify that.  I noticed one other issue with Attachments on 3.7.0 that I need to fix before a release.  But in the meantime if anyone wants a version with Attachments with the fix above (and a few other fixes), please contact me at jmcameron/jmcameron/net.    
-Jonathan (author of the Attachments extension)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15545">issues.joomla.org/tracker/joomla-cms/15545</a>.</sub>
