### ISSUE TITLE
category id added after joomla 3.7 upgrade

### ISSUE THREAD

**Issue by agerinteam** [joomla/joomla-cms#15541]
hi everyone,
after i upgraded my joomla 3.6 to joomla 3.6 i'v got a big problem. after upgrade joomla to 3.7 it adds category id to url!
is there any way to remove it?!!

**Comment by zero-24** [comment]
Please share more information. I don't know what you exactly mean.

**Comment by agerinteam** [comment]
in joomla 3.6 my urls were like this: http://www.mydomain.com/category/id-article_name
but after joomla 3.7 it is becomes like this: http://www.mydomain.com/id-category/id-article_name<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15541">issues.joomla.org/tracker/joomla-cms/15541</a>.</sub>

**Comment by csthomas** [comment]
First go to back end and check if your menu item "category" is published.

**Comment by agerinteam** [comment]
i checked, it is published<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15541">issues.joomla.org/tracker/joomla-cms/15541</a>.</sub>

**Comment by mbabker** [comment]
... and any menu item associated with that category?

**Comment by agerinteam** [comment]
yes :(<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15541">issues.joomla.org/tracker/joomla-cms/15541</a>.</sub>

**Comment by csthomas** [comment]
Does old URLs work?

**Comment by agerinteam** [comment]
yes they do<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15541">issues.joomla.org/tracker/joomla-cms/15541</a>.</sub>

**Comment by agerinteam** [comment]
i installed a text joomla 3.7 site with no component or plugin. it had the same problem. i use joomla "Use URL Rewriting" in global configuration.

there are also two other problem:
1- in article latest Module it adds category id too.
2- in menu if i go in one item, and then i want to go to another, url becomes like: http://www.mydomain.com/first-item-i-clicked/id-category/id-article
it adds first item to url<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15541">issues.joomla.org/tracker/joomla-cms/15541</a>.</sub>

**Comment by agerinteam** [comment]
by text i meant test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15541">issues.joomla.org/tracker/joomla-cms/15541</a>.</sub>

**Comment by BastianWie** [comment]
I tried to reproduce that with all Joomla installations I own but failed. Are you really sure that you do not use any 3rd party components? Did you tried to re-download the joomla installer and update all files again to ensure the ZIP file is not broken somehow?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15541">issues.joomla.org/tracker/joomla-cms/15541</a>.</sub>

**Comment by agerinteam** [comment]
yes, as i told i installed even a new text joomla with no 3d-party. i use joomla "Use URL Rewriting" in global configuration, that's all i did. 
i use php 7.0.18.
Apache
linux server
urls wont be short as joomla 3.6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15541">issues.joomla.org/tracker/joomla-cms/15541</a>.</sub>

**Comment by csthomas** [comment]
It is weird.
I did a test. My steps:
1. Download zip from https://github.com/joomla/joomla-cms/releases/download/3.7.0/Joomla_3.7.0-Stable-Full_Package.zip
2. Extract.
3. Install without any testing data.
4. Go to backend and set "Use URL Rewriting" to yes
5. Rename htaccess.txt to .htaccess
6. Comment a few lines because my apache does not allow for that:
```
#Options +FollowSymlinks
#Options -Indexes
```
7. Go to backend and create article "Article Test" as featured in new created category "category".
8. Go to front page and I see my article with link: `.../8-category/1-article-test`
9. Now I create a menu item with type **"Category List"** and choose category "category" then save.
10. Go to front page again and I see link `.../category/1-article-test`

Everything works.

> there are also two other problem:
1- in article latest Module it adds category id too.
2- in menu if i go in one item, and then i want to go to another, url becomes like: http://www.mydomain.com/first-item-i-clicked/id-category/id-article
it adds first item to url

There is an issue at https://github.com/joomla/joomla-cms/issues/15336 which may also affected articles.

**Comment by agerinteam** [comment]
dear csthomas, that didn't work for me. 
but i fixed it in this way:
create new categories
move articles to new categories
remove menus 
create new menu and set menu item language to all

but it is really hard to do so. i had more than 500 articles, 20 categories and around 50 menu items.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15541">issues.joomla.org/tracker/joomla-cms/15541</a>.</sub>

**Comment by csthomas** [comment]
Thank for response.
Because you mentioned about 
> ... and set menu item language to all

I suspect this is the key.

I have created a short test on my test installation.
I went to backend, created a second article in second category and second menu item.
And everything was still working.
After I changed language from "All" to "en-GB" in "second category" menu item then I got you issue.

My conclusion
**Menu item language has to be equal to category language.**

**Comment by agerinteam** [comment]
the strangest thing was that without creating new categories and move articles into it, changing language wasn't the answer. is it a bug or i dont understand joomla multilingual feature properly?
i checked my whole site for 404 error pages. in print version, some categories or authors links are broken.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15541">issues.joomla.org/tracker/joomla-cms/15541</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@infograf768 can you please have a Look at Conclusion of @csthomas: " Menu item language has to be equal to category language."

**Comment by infograf768** [comment]
I am a bit confused here:
Is that site multilingual?
If it is not, then delete the en-GB content language (and all others) and never choose en-GB (or whatever content language) as this is totally useless (and apparently creates issues, which should be looked into as router related)

If it is multilingual, it may be an issue I can try to look into it.

**Comment by agerinteam** [comment]
@infograf768 no it was not a  multilingual site, it just was active. thank you all dudes. i have some other joomla websites, i'll do the same (menu and categories languages to be equal) if there was any issue, i'll post it here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15541">issues.joomla.org/tracker/joomla-cms/15541</a>.</sub>

**Comment by agerinteam** [comment]
i checked it was fine. thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15541">issues.joomla.org/tracker/joomla-cms/15541</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@agerinteam Issue can be closed?

**Comment by agerinteam** [comment]
@franz-wohlkoenig yes dear <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15541">issues.joomla.org/tracker/joomla-cms/15541</a>.</sub>

**Comment by Quy** [comment]
@agerinteam You can close your own issues within the issue where you can post a `Comment` or click the `Close issue` button.
![closeissue](https://cloud.githubusercontent.com/assets/368084/25539253/2db9ebc2-2bfb-11e7-9b2a-6d96fb213b18.jpg)

**Comment by rinenweb** [comment]
Had the same issue after updating to Joomla 3.7. Solved it by enabling the "System - Language Filter" plugin (though it's not a multilingual website) and setting "Item Associations" to No. Note that I had previously followed the tip regarding the setting of all menu items, categories and articles to have the same language.

**Comment by hands3dlabs** [comment]
Thanks! I had solved by this way
