### ISSUE TITLE
site scanning malware for Joomla plugins

### ISSUE THREAD

**Issue by cfwicks** [joomla/joomla-cms#15550]
### Steps to reproduce the issue
Adding various Joomla plugins may result in making the site susceptible to malware. Is there a way to verify that plugins will not fail malware scans?

### Expected result
Find verified plugins supporting malware prevention practices that will pass malware scans using an SG Site scanner application.

**Comment by PhilETaylor** [comment]
This should be closed. 

Its not Joomla's role to provide audited extensions, or validate them against a 3rd party scanning app.

**Comment by franz-wohlkoenig** [comment]
closed as mentioned.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15550">issues.joomla.org/tracker/joomla-cms/15550</a>.</sub>
