### ISSUE TITLE
Problem with the calendar

### ISSUE THREAD

**Issue by neo191987** [joomla/joomla-cms#15551]
Hi encountered problems with the calendar after update to 3.7.0.
![screen shot 2017-04-25 at 22 24 16](https://issues.joomla.org/uploads/1/f09d5b05efa396a01f9f3702c86b6ca5.png)

**Comment by wilsonge** [comment]
@dgt41

**Comment by dgt41** [comment]
@neo191987 Is this on Isis or on a front end template?
If it's front end please ask for an update from the vendor or your designer (should straight forward fix)
If it's back end probably the component has some conflicting css, again ask the vendor for an update

**Comment by neo191987** [comment]
Hi this problem is also present at the front and at the back end. 
front end -  isis
back end - Helix3

**Comment by dgt41** [comment]
@neo191987 what browser?
which views?
what happens if you disable the helix plugin ?

**Comment by brianteeman** [comment]
> front end - isis
back end - Helix3

I assume yuo meant the other way around

**Comment by neo191987** [comment]
Disable: Helix3 - Ajax and System - Helix3 Framework
Same problem. I went wrong :)

**Comment by dgt41** [comment]
@neo191987 what browser are you using?
Did you tried with another one?
Also which views produce this error?

**Comment by neo191987** [comment]
Google Chrome - Latest Version. I will now test others.

**Comment by neo191987** [comment]
Mozilla Firefox and Opera - same problem. Testing Hikashop.

**Comment by dgt41** [comment]
Editing an article the calendar displays correctly ? If so please close the issue here and open one in Hikashop

**Comment by neo191987** [comment]
Yes there works perfectly, but I tested most applications have this problem.

**Comment by Fedik** [comment]
I had this problem to, it happens when call:
```php
echo JHtml::_('calendar', $value, $name, $id, $format, $attributes);
```
and `$attributes` do not have some values, wich expected by new version of `JHtml::calendar`

I would count it as B/C problem
