### ISSUE TITLE
Close button in language associations dialog no longer working

### ISSUE THREAD

**Issue by BastianWie** [joomla/joomla-cms#15552]
### Steps to reproduce the issue

1.) Create a menu called "German" and create a link to an internal document inside that menu. Call the Link German-A
2.) Create a menu called "English" and create a link to an internal document inside that menu. Call the Link English-A
3.) Now edit the link German-A, switch to the associations tab, in the "select a Menu Item" click on "select". Click on the close or the X button. The dialog will no longer close. Now choose English-A from the items and the dialog will close.

### Expected result
The dialog box should close on the X or Close button

### Actual result
The dialog box do no longer close when using the X or the Close button

### System information (as much as possible)
- Joomla 3.7.0
- Browser: Firefox or IE ... both show the same issue

### Additional comments
I´m very sure that this function was working before the upgrade to Joomla 3.7.0 however I do no longer have a version to test that.

**Comment by infograf768** [comment]
I can't reproduce this issue.
Have you cleared all caches (Browser and Joomla) ?

**Comment by franz-wohlkoenig** [comment]
@BastianWie did Suggestion by @infograf768 solve Issue?

**Comment by BastianWie** [comment]
Hi, sorry took me some days to check that. I still can reproduce the issue on 3 PCs and installed a new fresh VMWare and failed there. Its not the cache however it is then maybe a local OS issue. Maybe something is wrong with the PC image the company is using to deploy the OS to the PCs. I think we can close this issue for the moment as it looks like if its a local issue.
