### ISSUE TITLE
[com_fields] Suggestion for Fields: Adding "Show Field" Under Menu Item Options Tab

### ISSUE THREAD

**Issue by Saurabh1** [joomla/joomla-cms#15557]
I see that there is no "Show Field" under Menu Item Options with Show Global,  Like
Show Title, Linked Titles, Show Intro Title etc. 

If there can be "Show Field" as well then user can modify if they want to show for particular page or hide or use global. 

Image Reference: http://take.ms/bBkcv

**Comment by Bakual** [comment]
The way Custom Fields works, this isn't possible to do.
Custom Fields are added using plugin events. The exact same events are also responsible for eg the "vote" plugin or similar ones. When fields are inserted into the article it's the same event as all other content plugins.

**Comment by brianteeman** [comment]
I am closing this for the reason stated above by @bakual
