### ISSUE TITLE
Directly calling JHtml::_('calendar', ...) does not work as expected

### ISSUE THREAD

**Issue by fevangelou** [joomla/joomla-cms#15569]
### Steps to reproduce the issue
Directly calling JHtml::_('calendar', ...) in components (e.g. K2) does not work as expected. Even though the JHtml calendar method sets time to be shown by default, directly calling JHtml::_('calendar', ...) either with the "showTime" attribute set to "true" or none (which would default to "true" either way), it never displays the JS calendar with the time options. Visual example here: http://jmp.sh/l3UC5L0

Other older attributes (e.g. "readonly") work as expected (probably because they don't modify the JS calendar but the HTML form field itself).

### Expected result
New Joomla 3.7.x JHtml calendar method attributes should control the display JS calandar script.

### Actual result
They don't. Visual example here: http://jmp.sh/l3UC5L0

### System information (as much as possible)
Joomla 3.7.0 on PHP 7.1.1 (via MAMP)

**Comment by fevangelou** [comment]
Here's a screenshot of the rendered data attributes: http://jmp.sh/heTySpS

You'll notice (at the bottom) that they do not conform to the default attributes set in JHtml's calendar method.

**Comment by rdeutz** [comment]
@dgt41 can you have a look

**Comment by Fedik** [comment]
it the same as #15551

step to reproduce:
```php
echo JHtml::_('calendar', '', 'blabla', 'blabla', '%Y-%m-%d', null);
```
in result you should get a working callendar, but you get a bit broken calendar 😉

**Comment by dgt41** [comment]
@fevangelou Fotis can you paste in a codepen, the exact code you are using?

**Comment by Fedik** [comment]
@dgt41 see my previous comment

**Comment by fevangelou** [comment]
This evaluates wrongly:

```
		$showTime     = !empty($showTime) ? ($showTime === 'true' ? "1" : "0") : "1";
		$todayBtn     = !empty($todayBtn) ? ($todayBtn === 'true' ? "1" : "0") : "1";
		$weekNumbers  = !empty($weekNumbers) ? ($weekNumbers === 'true' ? "1" : "0") : "0";
		$fillTable    = !empty($fillTable) ? ($fillTable === 'true' ? "1" : "0") : "1";
		$singleHeader = !empty($singleHeader) ? ($singleHeader === 'true' ? "1" : "0") : "0";
```

**Comment by janich** [comment]
Not to highjack this thread, but the start of week does not seem to be working in your screenshot?

**Comment by fevangelou** [comment]
The fix requires that this block in /libraries/cms/html/html.php is changed from:

```
		$showTime     = !empty($showTime) ? ($showTime === 'true' ? "1" : "0") : "1";
		$todayBtn     = !empty($todayBtn) ? ($todayBtn === 'true' ? "1" : "0") : "1";
		$weekNumbers  = !empty($weekNumbers) ? ($weekNumbers === 'true' ? "1" : "0") : "0";
		$fillTable    = !empty($fillTable) ? ($fillTable === 'true' ? "1" : "0") : "1";
		$singleHeader = !empty($singleHeader) ? ($singleHeader === 'true' ? "1" : "0") : "0";
```
to
```
		$showTime     = ($showTime) ? "1" : "0";
		$todayBtn     = ($todayBtn) ? "1" : "0";
		$weekNumbers  = ($weekNumbers) ? "1" : "0";
		$fillTable    = ($fillTable) ? "1" : "0";
		$singleHeader = ($singleHeader) ? "1" : "0";
```

**Comment by hikashop-nicolas** [comment]
I confirm that this fix fixes the issue for HikaShop calendar selectors too.

**Comment by fevangelou** [comment]
Added related PR with the fix.

**Comment by PhocaCz** [comment]
Hi, confirmed:
before the change:
![Before change](http://i.imgur.com/sNFHCIc.png)
after the change:
![After change](http://i.imgur.com/yuPv70m.png)

**Comment by franz-wohlkoenig** [comment]
closed as having PR #15573<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15569">issues.joomla.org/tracker/joomla-cms/15569</a>.</sub>

**Comment by domydev** [comment]
<?php echo JHTML::_('behavior.calendar');
if (!isset($this->content->id))
	$created_date = date("Y-m-d");
else
	$created_date = $this->content->date_created;
$time = date('H:i:s',strtotime($created_date));
echo JHTML::_('calendar', $created_date, "date_created", "date_created", "%Y-%m-%d $time", null); 

Bizzard not save backend for my personal component 3.7.5 > 3.8

help me save backend calendar value

**Comment by wilsonge** [comment]
@domydev this issue has been fixed - so if you are still having problems please create a new support ticket
