### ISSUE TITLE
[3.7.1] Some Default Options not shown in Menu-Options

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#15564]
### Steps to reproduce the issue
Create new Menu-Item (i.E. Type "Featured Articles"), select Tab "Options". There are some Dropdown-Fields without Default Value:

- Position of Article Info
- Article Info Title
- Show Associations
- Show Tags
### System information
3.7.1-dev
macOS Sierra, 10.12.4
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by zero-24** [comment]
Please try if resave the global config fixes your issue.

Did you a new install? If yes we need to fix the install SQL's if above workarround fixes your problem.

**Comment by brianteeman** [comment]
IIRC it is not possible to determine a default global value for these as they are featured and this is not a view that has a global option

**Comment by franz-wohlkoenig** [comment]
@zero-24 Update (nightly builds) 3.7>3.7.1. Fixed Database, `Save` and `Saved&Closed` Article Options saved issue. 
@brianteeman this was on Blog, List, also, but resolved by resaving global Options.

Thanks for helping, closing.

**Comment by zero-24** [comment]
Than we need to fix the install sql please reopen.

**Comment by brianteeman** [comment]
Closed as I created a PR to fix this as requested by @zero-24
