### ISSUE TITLE
Custom Fields Tab Not Showing When Article Options Hide

### ISSUE THREAD

**Issue by rgblogs** [joomla/joomla-cms#15572]
### Steps to reproduce the issue

Create custom fields and assign to some category.
In Articles Global Options, Editing Layout, set Show Article Options to Hide
Create or edit an article in back-end

### Expected result

Custom fields tab should be there for editing

### Actual result

Custom fields tab missing

**Comment by franz-wohlkoenig** [comment]
Thanks for reporting, but this is an duplicated report of knowing Issue #15473<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15572">issues.joomla.org/tracker/joomla-cms/15572</a>.</sub>
