### ISSUE TITLE
UI is changed for all view except permission

### ISSUE THREAD

**Issue by jaisheela** [joomla/joomla-cms#15575]
### Steps to reproduce the issue

check permission TAB 

### Expected result

drop UI should consistent 

### Actual result

UI is old

**Comment by PhilETaylor** [comment]
ok ... how about you close this issue and actually open an issue that people can follow, with details?

**Comment by jaisheela** [comment]
I think you can get it

**Comment by PhilETaylor** [comment]
No, Im not a mind reader... there are a million different permission tabs in Joomla!

**Comment by jaisheela** [comment]
![permissionsettingd](https://cloud.githubusercontent.com/assets/16459454/25434549/55aceda2-2aaa-11e7-828c-d239ff75891a.png)
 Throughout out Joomla there is the same layout for permissions, I thought you guys know Joomla better.

**Comment by PhilETaylor** [comment]
And what exactly are you saying is wrong with this screen?

**Comment by brianteeman** [comment]
Please show the differences that you are referring to. Right now I dont have a clue what you are talking about as I am not sat in front of your computer sitting in your chair

**Comment by PhilETaylor** [comment]
Oh I think what you are trying to say is that these select boxes are not being converted into chosen js dropdowns like elsewhere in Joomla. 

Chosen is a pile of crap anyway...

**Comment by jaisheela** [comment]
Yes exactly

**Comment by brianteeman** [comment]
Chosen is not used on every dropdown - it is only used where the functionality that chosen provides eg search is required

I thought you were saying that the permissions tabon that component is different to the permissions tab on other components

**Comment by PhilETaylor** [comment]
Actually chosen is used in places where its functionality is not needed, almost everywhere...

**Comment by mbabker** [comment]
Blame that on people who thought it was a good idea to load Chosen on all `<select>` elements for the sake of consistency instead of it being a functional judgement call.

**Comment by PhilETaylor** [comment]
I rather not blame, but educate :) 

Yes it looks pretty, but pretty should be one of many attributes thats evaluated before choosing a JS solution over browser defaults.. :) :) 

As for this issue, nto sure who is going to make the decision to fully implement chosen everywhere, or (based on recent feedback about the poor state of the chosen project iself) remove chosen from the core :) 

... or just leave it as it is :)

**Comment by jaisheela** [comment]
I was thinking about the consistency and if it used then it should be everywhere.

**Comment by brianteeman** [comment]
I am closing this. These selects are correct and should not be using chosen
