### ISSUE TITLE
No redirect from / to /{lang}/ when multilanguage and page cache enabled

### ISSUE THREAD

**Issue by elpescador-nl** [joomla/joomla-cms#15579]
### Steps to reproduce the issue
Enable plugins languagefilter and (page) cache and use SEF-urls.

### Expected result
I would expect when I go to example.com/ I will be redirected (302) to the default language or to the one stored in my cookie: example.com/nl/

### Actual result
I remain on example.com/ with a blank page (http 200).

### System information (as much as possible)
PHP Version: 7.0.12
Web Server: nginx/1.11.4
WebServer to PHP Interface: cgi-fcgi
Joomla! Version	Joomla! 3.7.0 Stable [ Amani ] 25-April-2017 15:36 GMT
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

Tested this behaviour in Safari and Google Chrome. Does not seem browser related.

### Additional comments
When I disable page cache plugin the redirect works however. To me it seems an issue with the page cache mechanism which prevents the redirect somehow.

**Comment by AlexRed** [comment]
I can confirm the problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15579">issues.joomla.org/tracker/joomla-cms/15579</a>.</sub>

**Comment by PhilETaylor** [comment]
is #15593 related?

**Comment by elpescador-nl** [comment]
@PhilETaylor , probably: yet another situation with the same problem: no redirection when cache plugin is enabled.

**Comment by manuel-reil** [comment]
Confirmed here as well.

**Comment by franz-wohlkoenig** [comment]
closed as related to #15674<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15579">issues.joomla.org/tracker/joomla-cms/15579</a>.</sub>
