### ISSUE TITLE
[4.0] Modals broken when trying to associate menu items

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#15570]
Create a multilang site with menu items tagged to different languages.
Associations should be enabled in the languagefilter.
Edit a menu item in one language (can be done with the Home). 
Go to Associations tag

Whether one chooses Select/Create (depending on situation), the modal does not respect the task.
Select does not select the item. Create does not let Save/Save and Close/Close.

The Clear button is broken too.

@C-Lodder

**Comment by C-Lodder** [comment]
Any errors in the console log?

**Comment by infograf768** [comment]
Also Select Target in com_associations side by side is now broken: modal displays but clicking on a content item (tested for articles and categories has no effect.

**Comment by infograf768** [comment]
some of the errors
"TypeError: window.processModalParent is not a function"

TypeError: window.processModalEdit is not a function

Error: Tooltip is transitioning

**Comment by infograf768** [comment]
for com_asssociations, I have
TypeError: o is undefined[Learn More]  admin-associations-modal.min.js:1:53
TypeError: document.getElementsByName(...)[0] is undefined[Learn More]  multiselect.min.js:1:756

**Comment by C-Lodder** [comment]
ok thanks, will take a look

**Comment by infograf768** [comment]
@C-Lodder 
Concerning com_associations side by side I can get rid of the error in admin-associations-modal.js by this code (for the uncompressed files)

```
diff --git a/media/com_associations/js/admin-associations-modal.js b/media/com_associations/js/admin-associations-modal.js
index b3cae69..48bb490 100644
--- a/media/com_associations/js/admin-associations-modal.js
+++ b/media/com_associations/js/admin-associations-modal.js
@@ -25,3 +25,3 @@
 		}
 	});
-})();
+}( Joomla, document ));
diff --git a/media/com_associations/js/modal-associations.js b/media/com_associations/js/modal-associations.js
index 01bccb3..4de5d2b 100644
--- a/media/com_associations/js/modal-associations.js
+++ b/media/com_associations/js/modal-associations.js
@@ -23,3 +23,3 @@
 	});
 
-})();
+}( Joomla, document ));
```

but not the error in multiselect

**Comment by C-Lodder** [comment]
I cannot replicate the issue entirely. The only errors I get are:

> TypeError: document.getElementsByName(...)[0] is undefined        multiselect.min.js:1:753
> TypeError: d is null                                                                        draggable.min.js:1:122

I do not  see this:

> TypeError: o is undefined[Learn More] admin-associations-modal.min.js:1:53

**Comment by brianteeman** [comment]
I cannot replicate this. Assuming it has been fixed elsewhere. I am closing it for now. It can always be re-opened

**Comment by infograf768** [comment]
That one has indeed been solved since...
but not this one: https://github.com/joomla/joomla-cms/issues/15439
