### ISSUE TITLE
Joomla 3.7 mod_menu not possible to override anymore

### ISSUE THREAD

**Issue by StefanSTS** [joomla/joomla-cms#15584]
### Steps to reproduce the issue
- Add default_disabled.php and default_enabled.php in /administrator/template/isis/html/mod_menu/.
- Change or add any menu.

### Expected result
- Changes should be visible in the admin menu.

### Actual result
- No changes visible.

### Only way to get the result
- Changing the core files .../mod_menu/preset/enabled.php and disabled.php shows the desired changes.

### System information (as much as possible)
- J 3.7, PHP 5.6.30 and PHP 7.0.18
- Isis Admin Template

### Additional comments
In mod_menu a folder preset is introduced in Joomla 3.7. There is no way to override the files enabled.php or disabled.php in the administrator template like it was before or like it would be expected for module files in general.
A fallback to either use the old files or override the new files in .../preset/ should be added.

**Comment by mbabker** [comment]
IMO this needs some thinking.  With the new admin menu management these files really should only be used to seed the default structures and any customizations should now go into the database.  I don't know if we should be making the presets overridable.

Ping @izharaazmi

**Comment by StefanSTS** [comment]
Thanks Michael for your reply on this.

I am a bit confused on how the presets work. I expected them to be read and taken into the database only on first load, but if I change the core files, the changes show up immediately, so looks like these files are read all the time before creating the admin menu. But changing the core files is anything else than wanted.

I read pull request #13036 and there is one line of @izharaazmi:
> Sounds good. Though my plan is to offer multiple presets including custom
ones. We can discuss on this.

That sounds like it is already thought of to have custom presets and going that way would be much appreciated. Using the old overrides default_enabled.php and default_disabled.php as source to override presets enabled.php and disabled.php would keep B/C. Placing custom presets in the templates override folder /html/mod_menu/enabled_mypreset.php would help adding presets without messing in the core.

Another issue I faced is that on creating a new admin menu, I could add the "Components Manager Container" and a "Components Menu Container", but trying to add a menu item to the new menu for an already existing menu item in the menu "menu", resulted into an error:
1242 - An error has occurred.
Subquery returns more than 1 row

My test installation is multilang EN and DE. But I don't think that is a multilang issue. 
Testing a bit further on that tomorrow.

**Comment by izharaazmi** [comment]
I was working on it and its almost done, nearly over 70%. However we were in RC state on J3.7, it wasn't possible to target 3.7 with it. Therefore, I slowed down a bit. Hope to see that soon.

**Comment by brianteeman** [comment]
@izharaazmi did you make any progress on this?

**Comment by izharaazmi** [comment]
Yes. I hope we have a PR next weekend.

**Comment by StefanSTS** [comment]
Hello @izharaazmi, 
may I ask if the PR will introduce the override ability again that was found before J 3.7?

**Comment by izharaazmi** [comment]
Yes, I have completed the work. Just not getting enough time to do the PR.
Hope it to be here in 2-3 days or so.

**Comment by izharaazmi** [comment]
@brianteeman @stefanSTS I have created the PR #16451. Please review/test.

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16451<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15584">issues.joomla.org/tracker/joomla-cms/15584</a>.</sub>
