### ISSUE TITLE
[4.0] layout issue in Joomla 4.0 installer

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15580]
<img width="472" alt="screen shot 2017-04-26 at 13 06 09" src="https://cloud.githubusercontent.com/assets/400092/25433690/2c194c70-2a81-11e7-8528-57aa344703bb.png">

at bceede15453147ec306edc5b2ef411c38bfb7327

**Comment by PhilETaylor** [comment]
<img width="467" alt="screen shot 2017-04-26 at 13 06 59" src="https://cloud.githubusercontent.com/assets/400092/25433707/4038107e-2a81-11e7-9844-9a6a8e96899e.png">

**Comment by brianteeman** [comment]
I'm sure I saw a PR for this recently

**Comment by C-Lodder** [comment]
What browser are you using @PhilETaylor ?

**Comment by PhilETaylor** [comment]
<img width="780" alt="screen shot 2017-04-26 at 13 33 48" src="https://cloud.githubusercontent.com/assets/400092/25434678/265f02f8-2a85-11e7-84ae-79d2a6a3b39c.png">

**Comment by C-Lodder** [comment]
New installer was merged so this can be closed?

**Comment by PhilETaylor** [comment]
yup
