### ISSUE TITLE
[com_fields] Error when accessing custom fields inside articles

### ISSUE THREAD

**Issue by fmmarmello** [joomla/joomla-cms#15589]
### Steps to reproduce the issue
Access Articles > Fields

### Expected result
List Fields

### Actual result

Unknown column 'a.name' in 'field list'

### System information (as much as possible)

I had a previous Joomla instalation, from 3.5 I think...
This is the same system where I have installed the beta.

### Additional comments
I have "corrected" that by changing the fields model, but I'm not sure if it's the best option..

Great improvements BTW

**Comment by PhilETaylor** [comment]
You have not upgraded your db correctly

Try running the FIX button in the Database page of the Extensions component

**Comment by PhilETaylor** [comment]
Also note there is no "official" upgrade path from "beta" versions :)

**Comment by fmmarmello** [comment]
Just did that :(
Still happening.
Should there be an 'alter table'?

**Comment by fmmarmello** [comment]
"Also note there is no "official" upgrade path from "beta" versions :)"

Oh Ok.. didn't know that...
That might be kind of a problem for us :(

**Comment by roland-d** [comment]
Just add that field to your database manually and you should be good to go.

**Comment by PhilETaylor** [comment]
https://developer.joomla.org/news/671-joomla-3-7-beta-3-released-for-testing.html

> Please do not upgrade any of your production sites to the beta version and do not start a new site on beta as beta is ONLY intended for testing and there is no upgrade path from Beta.

**Comment by fmmarmello** [comment]
Ok @roland-d I'll try that..

@PhilETaylor .. hmm .. I've probably ignored that last part :/ sorry about that...

**Comment by brianteeman** [comment]
Closed

**Comment by fmmarmello** [comment]
Well, it looks like it's working .. thanks guys
