### ISSUE TITLE
[4.0] During installation the progress is covered by overlay

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15581]
<img width="1120" alt="screen shot 2017-04-26 at 13 07 28" src="https://cloud.githubusercontent.com/assets/400092/25433742/609a1c54-2a81-11e7-9676-1a309d1582fe.png">

at bceede15453147ec306edc5b2ef411c38bfb7327

**Comment by C-Lodder** [comment]
New installer was merged so this can be closed?

**Comment by PhilETaylor** [comment]
probably...
