### ISSUE TITLE
[4.0] Password strength meter in INSTALLER gives false impression

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15582]
The password strength bar is not fit for use

It gives an impression that the password provided is secure

A password of "admin" gives a 100% green bar.... 

<img width="470" alt="screen shot 2017-04-26 at 13 09 27" src="https://cloud.githubusercontent.com/assets/400092/25433820/b9627854-2a81-11e7-86b3-5bf3ae888d95.png">

**Comment by dgt41** [comment]
Password accepted don't mean that the password is **strong**. You can change the settings to make it longer and requiring more special characters at the end the script is just manipulating these settings (blindly)...

**Comment by PhilETaylor** [comment]
So what is the point of this then if its not a complexity? if its just checking password length then can normal validation not do that... 

At the moment its adding visual elements for the sake of it... 

There simply is no need for a progress bar at all - unless its actually going to make user use more secure passwords

**Comment by dgt41** [comment]
@PhilETaylor the indicator is just indicating if the user is fulfilling the requirements of the site, set here:
![screen shot 2017-04-27 at 12 40 44](https://cloud.githubusercontent.com/assets/3889375/25477659/f770dcce-2b46-11e7-8523-e1d177c773ae.png)

In that context the script is not knowing if a password is strong or weak, it's just a visual help that the password is fulfilling the requirements of the site. Te initial settings are just password must be >4 characters long. Modifying these settings you can require numbers, capital letters, other symbols etc, and thus force to a more secure password

**Comment by dgt41** [comment]
@PhilETaylor I didn't realise you were referring to the installation process here, so yes then this makes sense

**Comment by PhilETaylor** [comment]
My screenshot was from the installation process :) I did forget to mention that :)

**Comment by brianteeman** [comment]
as the password strength validator is no longer present in the installer I am closing this
