### ISSUE TITLE
[4.0] Installer doesnt validate that the mysql database name is valid

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15583]
At the moment there is no validation, if you enter an invalid mysql database name (like 'joomla-4') then the installation doesnt warn, but hangs on a later step (creating the db) 

<img width="616" alt="screen shot 2017-04-26 at 13 18 49" src="https://cloud.githubusercontent.com/assets/400092/25434133/08bc70ac-2a83-11e7-8fd8-78f3ab7000cc.png">

**Comment by franz-wohlkoenig** [comment]
@mbabker Issue for 4.0-Projects?

**Comment by brianteeman** [comment]
Bizarrely I just tested this (on windows) and successfully created a database called **&*(%£""%^*(`;**

but I agree we should be validating on entry https://stackoverflow.com/questions/9537771/mysql-database-name-restrictions

**Comment by brianteeman** [comment]
closed see #21447

**Comment by continga** [comment]
Can we please reopen this issue @brianteeman ?

I think the current solution in Joomla 4 codebase
https://github.com/joomla/joomla-cms/blob/e051bb282075e86135099e73e9e0e853b5886819/installation/src/Model/SetupModel.php#L320
and
https://github.com/joomla/joomla-cms/blob/e051bb282075e86135099e73e9e0e853b5886819/installation/src/Model/DatabaseModel.php#L183
is waaaaay to strict.

E.g. in mariadb basically everything is allowed[1], so especially something like 'joomla-4', and I am using database names with dashes in them in production on all my servers for years now, without even a single problem. All applications work with this. Why should Joomla enforce something that is not needed?

So the current logic in Joomla 4 is unneeded way too strict. From my point of view, we should change that current regex to some kind of other logic. Maybe we can somehow query the DBMS and ask whether that database exists, that should be a safe way to check if it is a valid name?

Opinions?

[1] = https://mariadb.com/kb/en/library/identifier-names/

**Comment by bjxrn** [comment]
I agree that the current solution is way to strict and will prevent installation using valid database names.

The example given in the top post is wrong. joomla-4 _is_ a valid MySQL database name as long as it is quoted. And quoting is handled by Joomla's database layer.


Edit: See the [MySQL docs](https://dev.mysql.com/doc/refman/5.7/en/identifiers.html) regarding identifiers.

**Comment by PhilETaylor** [comment]
Tagging #23041 for visibility.

**Comment by Quy** [comment]
Fixed with PR #23704<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15583">issues.joomla.org/tracker/joomla-cms/15583</a>.</sub>
