### ISSUE TITLE
Blank frontend

### ISSUE THREAD

**Issue by whitedd** [joomla/joomla-cms#15597]
After upgrade from 3.6.5 to 3.7 i get blank frontend...backend working nice

### Additional comments

PHP 7.0.18

**Comment by AlexRed** [comment]
Try to clear cache<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15597">issues.joomla.org/tracker/joomla-cms/15597</a>.</sub>

**Comment by whitedd** [comment]
my cache is disabled...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15597">issues.joomla.org/tracker/joomla-cms/15597</a>.</sub>

**Comment by AlexRed** [comment]
try to set the default protostar template<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15597">issues.joomla.org/tracker/joomla-cms/15597</a>.</sub>

**Comment by whitedd** [comment]
i try...work 1-2 minutes and go blank again<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15597">issues.joomla.org/tracker/joomla-cms/15597</a>.</sub>

**Comment by AlexRed** [comment]
sure the plugin "System - Page Cache" is disabled ?

Multilanguage ?
HTTPS ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15597">issues.joomla.org/tracker/joomla-cms/15597</a>.</sub>

**Comment by whitedd** [comment]
sure the plugin "System - Page Cache" is disabled ? ....  yes

Multilanguage ? ... no
HTTPS ? ... yes<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15597">issues.joomla.org/tracker/joomla-cms/15597</a>.</sub>

**Comment by Quy** [comment]
Are you able to view your server's PHP error log to see what the issue may be?

**Comment by elpescador-nl** [comment]
Reading the symptoms I think this is related to #15579 and #15593 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15597">issues.joomla.org/tracker/joomla-cms/15597</a>.</sub>

**Comment by C-Lodder** [comment]
Blank page means there's an error being throw but PHP isn't displaying them. Please set Error Reporting in your Global Configuration to `development` and report back any errors.

**Comment by rijkdem** [comment]
Have the same problem afther upgrading to Joomla 3.7 today (with cache enabled). Disabeling the cache had no effect, cache was created every time again (even afther clearing the cache). The workaround I found for this problem: 

Manually edit the configuration.php file and clear the  

$cache_handler = 'file';
to 
public $cache_handler = '';

It looks like this resets the cache mechanism.

Unfortunately, when turning on cache again the problem occurs again. No real sollution found, looks like a bug.

I also found that the old option "Cache_lite" is missing and "File" is the only available option (forcing via configuration.php did not work).

**Comment by franz-wohlkoenig** [comment]
closed as related to #15674<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15597">issues.joomla.org/tracker/joomla-cms/15597</a>.</sub>
