### ISSUE TITLE
Fatal error on classes extending JLoader

### ISSUE THREAD

**Issue by phproberto** [joomla/joomla-cms#15596]
### Steps to reproduce the issue

JLoader `_autoload()` method was private so all the classes extending it were forced to create their own private `_autoload()` method. 

This PR changed it to public:
https://github.com/joomla/joomla-cms/pull/12478

Which causes a fatal error:

![jloader-joomla](https://cloud.githubusercontent.com/assets/1119272/25441672/2cfaf54a-2aa3-11e7-9b0f-bcc9895f017e.jpg)

This is a backward compatibility break (in case we are really following it). Such change should be delayed to `v4`

**Comment by phproberto** [comment]
Closing this as I doubt anybody will have the face the same error and we can easily fix it on our next release changing the registered autoload function. 

If someone faces the same issue and wants it to be reopened just add a comment.

**Comment by rdeutz** [comment]
closed on request
