### ISSUE TITLE
[3.7] [com_fields] Beez not showing new Checkbox custom field in an article

### ISSUE THREAD

**Issue by kat05** [joomla/joomla-cms#15595]
### Steps to reproduce the issue

I created 3 different custom fields:
1. Checkboxes
2. Text
3. URL

and made sure to have values set for them inside my article. When checking on frontend with Protostar, all 3 custom fields showed up perfectly fine. 

### Expected result

I would expect Beez to show them too.

### Actual result

When switching to Beez only the
2. Text
3. URL
custom fields are rendered.

### System information (as much as possible)

Joomla 3.7, php 7.1

### Additional comments

This seems like a minor issue but unfortunately a lot of our (RT) template overrides were done a long time ago and based on Beez, so unfortunately some of our own older templates do not show the Checkbox custom field either.

![j3_7_protostar](https://cloud.githubusercontent.com/assets/5719486/25440413/ac8b89c2-2a9f-11e7-8b14-2657ae8f448c.jpg)
![j3_7_beez](https://cloud.githubusercontent.com/assets/5719486/25440414/ac8bcd10-2a9f-11e7-9542-aeb7299fcbec.jpg)

**Comment by Bakual** [comment]
This is not related to the type checkboxes but to the "Automatic Display" position you have chosen for that field.
If you look at the override for Beez, that "afterDisplayTitle" content is only shown when the "Show Intro" parameter is set to off.
https://github.com/joomla/joomla-cms/blob/staging/templates/beez3/html/com_content/article/default.php#L76-L78

I have no clue why the code is like that. To me the whole if clause doesn't make any sense as this isn't tied to an intro text at all. I'd just remove that and always show the content of that property.

**Comment by brianteeman** [comment]
Found it

https://community.joomla.org/translations/544-joomla-project-translation-and-localization-policy.html#licenses

**Comment by Bakual** [comment]
@brianteeman Was that intended to be posted here? https://github.com/joomla/joomla-cms/commit/3d3c49374d60742ceb5075ee4ca7e0429876f8c4

**Comment by brianteeman** [comment]
Oops

**Comment by franz-wohlkoenig** [comment]
@Bakual is PR #15639 related to this Issue too?

**Comment by Bakual** [comment]
Yes, https://github.com/joomla/joomla-cms/pull/15639 should fix this.
Closing as there is a PR to test.
