### ISSUE TITLE
[com_fields] Consistency field name

### ISSUE THREAD

**Issue by onlinemindgem** [joomla/joomla-cms#15602]
### Steps to reproduce the issue

Add a new field for an article. 

Choose a title with spaces

Let the name be auto generated

### Expected result

Generated name replaces spaces with underscores just like the rest of the item (created_by_alias, modified_by_name, show_publishing_options, category_access and so on)

### Actual result

No underscores but names like 'custom-layout-show-header-image'

**Comment by Bakual** [comment]
That's because the method to generate the name is the same which generates an Alias 😄

**Comment by franz-wohlkoenig** [comment]
@onlinemindgem is Answer by @Bakual resolving Issue? If yes, please close Issue, thanks.

**Comment by brianteeman** [comment]
You are comparing the database column name with something completely different
