### ISSUE TITLE
Impossible to edit item in front

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#15615]
after update to 3.7
edit item in front
always redirect to same page no form
tested with protostar template and helix 3

**Comment by PhilETaylor** [comment]
I cannot replicate this from the information given.

**Comment by micker** [comment]
... i tested in other site yes....
argh i need to find plugin solution .... maybe jce

**Comment by PhilETaylor** [comment]
Im sorry - you are not making much sense :-)

**Comment by micker** [comment]
its realy strange that redirection doen't work ... i need to check this

**Comment by PhilETaylor** [comment]
Redirection FROM where TO where?

**Comment by micker** [comment]
on same page
url of edit button
http://site.com/mypage?task=article.edit&a_id=4&return=aHR0cDovL2NvbTNlbGxlcy5iaXovZHNpL2luZGV4LnBocC9ub3MtbWV0aWVycy9idXJlYXV0aXF1ZQ==
and i am redirect to
same url
http://site.com/mypage?task=article.edit&a_id=4&return=aHR0cDovL2NvbTNlbGxlcy5iaXovZHNpL2luZGV4LnBocC9ub3MtbWV0aWVycy9idXJlYXV0aXF1ZQ==
but it's not form editing

**Comment by PhilETaylor** [comment]
What WYSIWYG Editor are you using? 

Please send a screenshot

Is there any javascript errors in the Browser Console?

**Comment by micker** [comment]
jce and tiny same fight
no js error

**Comment by hvdmeer** [comment]
I can edit articles without problems on frontpage and J! 3.7 with JCE and Helix3.

**Comment by micker** [comment]
that strange i can edit module but item ...
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15615">issues.joomla.org/tracker/joomla-cms/15615</a>.</sub>

**Comment by brianteeman** [comment]
I am closing this item here - if you still need help please use the forum https://forum.joomla.org
