### ISSUE TITLE
[3.7] Regression in mod_menu - base item other than component not showing

### ISSUE THREAD

**Issue by Devportobello** [joomla/joomla-cms#15617]
### Steps to reproduce the issue
Create 1 menu eg: Main
Add to this menu some items like this:

Level - Item - Type
1 - Home - Article
2 - Activities - Menu heading
2.1 - Activity 1 - Article
2.2 - Activity 2 - Article
2.3 - Activity 3 - Article
3 - Contact - Article
![image](https://cloud.githubusercontent.com/assets/5180277/25479467/41a3d6cc-2b45-11e7-8765-c5fd7de3ad18.png)

Then go to modules > add a new module "Menu"
Select Menu : Main
Select base item : Activities
![image](https://cloud.githubusercontent.com/assets/5180277/25479570/95950936-2b45-11e7-826f-fedddbc0e3d8.png)

### Expected result
Could select "Activites"

### Actual result
Unable to see and select "Activities"

### Additional comments
Since j3.7

**Comment by brianteeman** [comment]
I understand why this has happened (I think) because the same modal is used in places where it would not make sense to be able to select a separator menu item - but here it clearly does make sense and i can confirm the issue

**Comment by Devportobello** [comment]
I think this PR is all about : [13036](https://github.com/joomla/joomla-cms/pull/13036) - introducing modal menu
@izharaazmi ?

**Comment by brianteeman** [comment]
yes thats the cause of the problem

**Comment by izharaazmi** [comment]
Sorry, I can't recall. What is this modal menu?

On 27-Apr-2017 6:48 PM, "Brian Teeman" <notifications@github.com> wrote:

yes thats the cause of the problem

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/joomla/joomla-cms/issues/15617#issuecomment-297710369>,
or mute the thread

**Comment by brianteeman** [comment]
go to modules > add a new module "Menu"
Select Menu : Main
Select base item : THIS OPENS THE MODAL

**Comment by izharaazmi** [comment]
Well, I guess its here
https://github.com/joomla/joomla-cms/commit/1f4826895c7c8df3f4663240f5ed0ad7115c1685#diff-d5d92c503f1c0d0d4368cceb1e31ff4fR90

**Comment by Devportobello** [comment]
Dunno what is better : rollback to another type eg: menuitem prior of : [commit](https://github.com/joomla/joomla-cms/commit/33d7bd916df6936055109504c0ac1cc5df260787) or implement a way (properties in modal_menu field) to show or not other than component "link" ?

**Comment by N6REJ** [comment]
following

**Comment by aaron-harding** [comment]
@Devportobello Looks like this field includes a disable option: https://github.com/joomla/joomla-cms/blob/008b78d61252994744950d7724615be3fad5066e/components/com_users/views/login/tmpl/logout.xml#L27

Is this a partial implementation of hiding menu items?

**Comment by Devportobello** [comment]
This is not used in the modal_menu field, but this could be a nice idea, thx for pointing this;
I'm working on a PR, in a second step i will include that

**Comment by Devportobello** [comment]
Closed, following PR.

**Comment by B3nito** [comment]
Can this be open? It is still big issue!

**Comment by Quy** [comment]
Please test PR #16061<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15617">issues.joomla.org/tracker/joomla-cms/15617</a>.</sub>
