### ISSUE TITLE
Adding Date Modified on Articles Manager (new feature)

### ISSUE THREAD

**Issue by joomlabeat** [joomla/joomla-cms#15610]
### Steps to reproduce the issue
It's possible to show/sort articles by date created, publish_up/down - but not possible to sort by date modified.

### Additional comments
I don't know if there is any specific reason why date modified is excluded (performance maybe) - but I have seen many users requiring this and it's a valid demand - There is not an alternative easy and maintainable way to add this feature as an override. 

It looks like it's a rather quick modification to com_content.

Should this be added?

**Comment by joomlabeat** [comment]
I have worked a little bit on this so I could finalize it and submit it, if it's something to be included in the core.

**Comment by brianteeman** [comment]
off the top of my head one issue would be that a large % of articles would have no date to sort by

**Comment by joomlabeat** [comment]
then it would make sense a fallback to date created? As in such case the last modified date of the article would actually be the date that it was first created...

**Comment by joomlabeat** [comment]
Basically I just checked and saw that when creating a new article last modified date defaults to current date... it looks like the field will always have a value in the database - compared to publish_down that may be 0000-00-00 00:00:00

**Comment by brianteeman** [comment]
Closed as this feature was merged with #15825
