### ISSUE TITLE
Beez template in offline mode is not loading css

### ISSUE THREAD

**Issue by gwsdesk** [joomla/joomla-cms#15614]
Beez set to offline mode is not loading the css for the frontpage
![screen shot 2017-04-27 at 09 18 17](https://issues.joomla.org/uploads/1/6fe4f67b576a08f58e5dad787e0c80ba.jpg)

**Comment by gwsdesk** [comment]
See solution as given by MIG on the forums https://forum.joomla.org/viewtopic.php?f=710&t=949676#p3471372<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15614">issues.joomla.org/tracker/joomla-cms/15614</a>.</sub>

**Comment by brianteeman** [comment]
copying the files is not a solution

**Comment by gwsdesk** [comment]
But it works seemingly?

**Comment by brianteeman** [comment]
it is masking the root problem

**Comment by imanickam** [comment]
Yes, very true...  It is not a solution.  It is just a band-aid temporary fix.

When a template is not having a custom offline.php file (just like protostar), the css files offline.css and general.css have to be loaded from the directory \templates\system\css as the file offline.php in the directory \templates\system will get executed.  But, it is not doing it.  Rather it is expecting these css files in the directory of the Default Administrator Template.

With this behavior, when Beez3 template is the default administrator template, the css files are expected from the directory \templates\beez3\css.  Once this was found, I provided a quick fix that does not alter any file.

In the process going through the code in offline.php that is located in the directory \templates\system.  Will report the finding...
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15614">issues.joomla.org/tracker/joomla-cms/15614</a>.</sub>

**Comment by gwsdesk** [comment]
@brianteeman  yep that is correct but it gives an immediate solution for those in need and that is what I referred at so people who look for an "immediate" solution have bandaid

**Comment by RickR2H** [comment]
I created a patch for this. Please test so it can be included in the next update.

**Comment by brianteeman** [comment]
Closed
