### ISSUE TITLE
Updating to 3.7.0 causes wrong links on multilingual site when switching category list language

### ISSUE THREAD

**Issue by oliver-74** [joomla/joomla-cms#15612]
### Steps to reproduce the issue

Updating my multilingual site from 3.6.5 to 3.7.0

### Expected result

Same behavior of multilingual category linking as in 3.6.5

### Actual result

I have problems with a bilingual site and I had to revert back from 3.7.0 to my 3.6.5 backup because there I have no problems:

The site is using the Joomla native multilanguage approach for an English and German version of the website. 

Under 3.7.0 when entering a category list on the German version and then clicking on the English flag to switch to the English version of that list **I end up in an article** and not in a category list. The links I see when I click on the English flag of a German category list is linking to a different article for each category and this does NOT happen if I first switch my site to English on the start page and then try to switch from the same category from English -> German. Then I end up in the correct category. So the bug only occurs on category switches from German -> English.

This also does not happen for all categories but for the majority. I have my main website running on 3.6.5 again but I have a test copy of it on 3.7.0 and I only found very few categories that can correctly switch from German to English and back. Switching always works for English -> German

When I enter the category manager and check the association links for the category which link incorrectly then the association links are set correctly in both directions BUT I am missing the "Select" button. I can only choose to edit the version on the second language but I can not select a different article to link to. The select button is still there in 3.6.5

### System information (as much as possible)

Ubuntu 16.04 with PHP 7.0.15-0ubuntu0.16.04.4
Nginx version  1.10.3

### Additional comments

I have checked for article to article language switching and for all articles which have an English and a German version, there is no problem with switching the language.

**Comment by franz-wohlkoenig** [comment]
@infograf768 can you please have a Look?

**Comment by infograf768** [comment]
This is confusing:

> When I enter the category manager and check the association links for the category which link incorrectly then the association links are set correctly in both directions BUT I am missing the "Select" button. I can only choose to edit the version on the second language but I can not select a different article to link to. The select button is still there in 3.6.5

category or article?

> BUT I am missing the "Select" button

If there is already an association, the Select button will not display. You will get only the Edit and Clear buttons.
When no associations (which would happen after using the Clear button or where none would have ever been created, then the Select and Create buttons will display.

![screen shot 2017-04-28 at 10 20 43](https://cloud.githubusercontent.com/assets/869724/25520487/61001082-2bfc-11e7-9a1c-a76e7a3a2c10.png)

Now, your issue may be related to the fact that you have not associated a category list menu item in one language to a similar menu item in the other language.

I will look into this case as I think that the associated category should be used in that case.
Have to test on 3.6.5 if this is new in 3.7.0 or not.

**Comment by infograf768** [comment]
Ok, it looks like we have a router issue as it works when SEF is off

**Comment by infograf768** [comment]
release blocker. We are not B/C in 3.7.0

**Comment by oliver-74** [comment]
@infograf768 Sorry you are right, my report should have been "I can only choose to edit the version on the second language but I can not select a different **category** to link to.". I did not mean article but category and it was indeed confusing because of the nature of the reported issue.

No problem if the "Select" button was removed in 3.7.0 and you first have to "Clear" to re-link, that is fine too. The button simply is still present in 3.6.5 so I thought I mention it in the report in case it is related to the bug.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15612">issues.joomla.org/tracker/joomla-cms/15612</a>.</sub>

**Comment by infograf768** [comment]
After a new 3.7.0 install, I am finding that it is even worse:
even when sef is off, categories associations are broken. The switcher redirects to the home page for the language chosen when changing language from a cat list menu item.

**Comment by infograf768** [comment]
I also confirm it works fine on 3.6.5

**Comment by infograf768** [comment]
Ok, found the issue.

**Comment by infograf768** [comment]
My fault here https://github.com/joomla/joomla-cms/pull/12042
Have to find a way to solve this while keeping the feature.

**Comment by infograf768** [comment]
@oliver-74 
For now, you may solve your issue by modifying the file
`/components/com_content/helpers/association.php`
line 39

Change
```
if ($view === 'article' || $view === 'category' || $view === 'featured')
```
to
```
if ($view === 'article' || $view === 'featured')
```
Please confirm.
We will lose the display of possible articles associations flags in the details for each article displayed in a category view but would get back the correct associations from cat to cat in the switcher.

**Comment by oliver-74** [comment]
@infograf768 Yes I can confirm this code change fixes the described bug.

**Comment by infograf768** [comment]
Will make PR

**Comment by infograf768** [comment]
Closing as we have a patch

https://issues.joomla.org/tracker/joomla-cms/15664



Thank you for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15612">issues.joomla.org/tracker/joomla-cms/15612</a>.</sub>
