### ISSUE TITLE
User Custom Fields not showing in Joomla Registration form, Joomla 3.7 ?

### ISSUE THREAD

**Issue by AshrafTayab** [joomla/joomla-cms#15623]
I would like to use Custom Fields in Joomla Registration form
1: I make Users: Field Groups
2: I make Users: Fields, one is a list and the other is text, with permission for Guest Allowed

Custom Fields not showing in Joomla Registration form
Did I misng some steps

Thank you

**Comment by brianteeman** [comment]
Yes you forgot to set the permission for the field to public

**Comment by AshrafTayab** [comment]
Hello,
I set both,
Field Groups and Fields in the permission for Public and Guest
Edit Custom Field Value : Allowed 
Nothing change
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15623">issues.joomla.org/tracker/joomla-cms/15623</a>.</sub>

**Comment by Bakual** [comment]
If they don't show, then you either have not set the access level to "Public" or you have a template which has an override that doesn't show the fields (try with Protostar to rule that out).

The permissions come into play when the field shows, but you can't edit anything in it.

Anyway, this is not a bug. Please use the forum (http://forum.joomla.org/) for further help.

**Comment by AshrafTayab** [comment]
Hello,

I find way Custom Fields did not showing in backend and in frontend !!!

I pot in List Values : ( eTrex® 20 )
The problem is ( ® )
I remove ( ® ) from values the Custom Fields showing in backend and in frontend

Thank you<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15623">issues.joomla.org/tracker/joomla-cms/15623</a>.</sub>

**Comment by Quy** [comment]
This will be fixed once this pr #15294 is merged.
