### ISSUE TITLE
Max execution time reached on heavy article edit

### ISSUE THREAD

**Issue by berserkerx** [joomla/joomla-cms#15628]
### Steps to reproduce the issue

Create article with contents from attached UTF-8 [ddos.txt](https://issues.joomla.org/uploads/1/0a3465f0f667f7ba7c80e81fae35174a.txt)
Try to edit and save it.
Try different PHP max_execution_time from 10 to 60.

### Expected result

Fast saving.

### Actual result

White screen with max execution time reached.

### System information (as much as possible)

Joomla 3.7.0, JCE Editor Free.

### Additional comments

1. The last executed script is always libraries/vendor/joomla/string/src/phputf8/mbstring/core.php. Lines 41 or 94.
The caller is libraries/joomla/filter/input.php.

2. Restoring the 'libraries/joomla/filter/input.php', 'libraries/joomla/filter/output.php' to version < 3.7.0 fixes the issue.

**Comment by brianteeman** [comment]
Nothing attached

**Comment by mbabker** [comment]
That file hasn't changed in 3 years, restoring that file could not "fix" anything.

**Comment by berserkerx** [comment]
Sorry, guys, fixed the description of issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15628">issues.joomla.org/tracker/joomla-cms/15628</a>.</sub>

**Comment by jsubri** [comment]
I confirm the issue, IHAC reporting the same. I was not able to reproduce yet but I believe this is tinymce specific. Initially the user reported that html formatting was not visible in tinymce (just plain text), to workaround the situation I moved the user specific usergroup to "set0" in the tinymce plug-in. The user is part of a sub-set of the Managers with less less priv (mostly restricted to Users, Articles, Categories, Modules and 1-2 core components + one  well ranked 3rd party component). 
But he is still hitting the time out in libraries/vendor/joomla/string/src/phputf8/mbstring/core.php on line 94
Was working like a charm in 3.6.5. Average articles in French are about 300 characters, so probably not "size" related.

**Comment by PhilETaylor** [comment]
Please provide your full system information provided by Joomla System Information Page

**Comment by jsubri** [comment]
PHP Built On 	SunOS scmos 5.11 11.1 i86pc
Database Version 	5.6.12
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.5.28
Web Server 	Apache/2.4.16 (Unix) PHP/5.5.28
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.7.0 Stable [ Amani ] 25-April-2017 15:36 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT PHP Built On 					SunOS scmos 5.11 11.1 i86pc
Database Version 				5.6.12
Database Collation 				utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 					5.5.28
Web Server 					Apache/2.4.16 (Unix) PHP/5.5.28
WebServer to PHP Interface 		apache2handler
Joomla! Version 				Joomla! 3.7.0 Stable [ Amani ] 25-April-2017 15:36 GMT
Joomla! Platform Version 		Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by PhilETaylor** [comment]
Please go to site.com//administrator/index.php?option=com_admin&view=sysinfo and click the Download As Text button to download the FULL system information requested, then update this issue with that.

**Comment by jsubri** [comment]
ok to privately email you the file to your github profile email address?

**Comment by brianteeman** [comment]
there is no private information in that file

**Comment by berserkerx** [comment]
[systeminfo-2017-04-28T11_56_49+00_00.txt](https://issues.joomla.org/uploads/1/e82d198031a1b4c4c94c69fae161ff79.txt)
Denial of service (HTTP 500 due to max execution time) occurs on server side.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15628">issues.joomla.org/tracker/joomla-cms/15628</a>.</sub>

**Comment by jsubri** [comment]
just replaced couple of identifiable info by xxxx..
https://gist.github.com/jsubri/6fa87546086e89725e484ba39f373ff3

**Comment by brianteeman** [comment]
(@jsubri can you create a new issue with the names of the parts you replaced as there shouldnt be any that are identififiable in that file and if there are then its a bug)

**Comment by jsubri** [comment]
Brian, my manual change was just about the template names (my bad, I should not have created the templates with such naming), otherwise the file is unmodified. I'm suspecting the user to enter a strange sequence of characters coming along with a cut&paste likely from word. If I can access to the .doc I'll try to nailed down the sequence and post again.

**Comment by kozhevn** [comment]
I can confirm this issue with following conditions:

0. It happens yesterday exactly after updation till 3.7.0
1. Restoring the 'libraries/joomla/filter/input.php', 'libraries/joomla/filter/output.php' to version < 3.7.0 really fixes the issue.
3. For me reproduction behaviour is another and it looks much tiny:<br>
I have user with  only Registered+Author+Editor+Publisher access rights. It can create/edit/publish an article over frontend.<br>
So, after 3.7.0 updation this user easily can create and edit article with very simply content ( for example we can leave  just only h3 header from example below). Article saves without problems.   <br>
But much complex content caused the issue ( content example can be taken from  'div' tag with itemprop="articleBody" on following page: http://rk6.bmstu.ru/index.php/matters/best-diploms/188-2016 )<br>
When superuser performs the same actions  under admin panel - all happens just fine and no issue there.

It seems looks like an infinity loop during article content filtration functionality  by the  'libraries/joomla/filter/output.php'. And it seems this filtration doesn't used when superuser do the same under backend.

And really, substitution libraries/joomla/filter/output.php by the old version fixed it.

**Comment by PhilETaylor** [comment]
also reported as #15673

**Comment by franz-wohlkoenig** [comment]
closed in favor of #15673<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15628">issues.joomla.org/tracker/joomla-cms/15628</a>.</sub>
