### ISSUE TITLE
[RFC] Unit Testing PHP.ini

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15624]
Hey @mbabker, is there a way to get the unit testing php.ini to be something more akin to a crappy web host one with a load of bad configs like disable_functions populated, etc...

**Comment by mbabker** [comment]
https://github.com/symfony/symfony/blob/master/.travis.yml#L70-L87 is an example of pushing stuff into php.ini on Travis.  So honestly, we just seed a file with a "subpar" config, add a build to Travis with it, and bam, done.

**Comment by PhilETaylor** [comment]
Is this something you have the keys for? ;-)

**Comment by brianteeman** [comment]
Yes the file is in the root here

**Comment by PhilETaylor** [comment]
But how would one add a build to travis with it?

**Comment by mbabker** [comment]
1) Edit https://github.com/joomla/joomla-cms/blob/staging/.travis.yml
2) Issue Pull Request
3) Profit

**Comment by brianteeman** [comment]
closed as you have started a pr
