### ISSUE TITLE
[4.0] Re-installing languages broken

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#15631]
### Steps to reproduce the issue
Install a language through Installation->Install->Upload package file.
for example pick https://github.com/infograf768/fr-FR-3.x/releases/download/3.7.0.2_stable/fr-FR_joomla_lang_full_3.7.0v2.zip

Then re-install it the same way.
One gets:
`0 - An error has occurred.`
`Call to undefined method JInstallerAdapterLanguage::set()`

Note: First install works fine as well as uninstall the pack

**Comment by mbabker** [comment]
The install adapters don't extend from `JObject` anymore so get/set aren't there.  Though I swear when I did that change I caught all of the uses...

**Comment by Bakual** [comment]
Installing a language from the language installer is indeed broken currently. It uses the "Install from URL" method. From what I debugged so far, the response from `JHttpTransportCurl->get($url)` is wrong. It does contain the header but no code and body property and thus afterwards everything fails.

It may be related to https://github.com/joomla/joomla-cms/pull/13936 (not sure).

**Comment by mbabker** [comment]
There won't be an explicit `body` or `code` property anymore, but calling `$response->body` should still give the body contents through our magic getter and B/C layer.

**Comment by Bakual** [comment]
Thanks. Have to debug bit more then 😊

**Comment by Bakual** [comment]
Btw, same issue in J3.8 for me.

**Comment by laoneo** [comment]
Can this be the cause https://github.com/joomla/joomla-cms/pull/15884?

**Comment by Bakual** [comment]
I don't think it's related to that. It seems to run through all but in the end I get "Error
Unable to find install package"
It also doesn't work in the installation step where you could add more languages.

**Comment by Bakual** [comment]
@infograf768 Can you confirm that this is the same issue as yours? And that it also doesn't work in 3.8?
If so, then this will be a release blocker for 3.8.0.

**Comment by wilsonge** [comment]
There is a pull request with #16300

**Comment by Bakual** [comment]
Apparently we have two issues as it looks. Will open a new one for the remaining.

**Comment by wilsonge** [comment]
Thankyou!

**Comment by Bakual** [comment]
Actually, I'm just stupid. The XML has `<targetplatform name="joomla" version="3.[01234567]"/>` and thus currently in 3.8 and 4.0 no matching language pack will be found.

**Comment by brianteeman** [comment]
@Bakual was just about to point that out - glad you spotted it yourself
