### ISSUE TITLE
New Feature had no database tables for use.

### ISSUE THREAD

**Issue by th3r1dd1ck** [joomla/joomla-cms#15630]
### Steps to reproduce the issue
update from 3.6.X to 3.7.0

### Expected result
custom feilds to work

### Actual result
no database entries for custom fields to operate correctly

### Additional comments
I had to use the full install to create the tables for the custom fields to be able to be used.

**Comment by franz-wohlkoenig** [comment]
Read somewhere that "Extensions > Manage > Discover" can help.

**Comment by PhilETaylor** [comment]
Your update failed to run the post upgrade tasks

Extensions > Manage > Database -> Fix button will fix your database schema.

**Comment by brianteeman** [comment]
Closed
