### ISSUE TITLE
Duplicated administrator menu

### ISSUE THREAD

**Issue by Bocatatun** [joomla/joomla-cms#15640]
### Steps to reproduce the issue
Just updating joomla 3.6.5 to 3.7

![](http://i.imgur.com/xUN5x2a.jpg "Menu")
- Try to unpublish/publish the menu administrator module

### Expected result
- See just one menu

### Actual result
- I still seeying a duplicate menu

### System information (as much as possible)
Joomla 3.7
PHP 7.0.18 
MySQL  5.1.73

**Comment by Bocatatun** [comment]
some test
The administrator menu empleados does not contain - Menu Manager, Module Manager, Components Container. Click to turn on the menu recovery mode.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15640">issues.joomla.org/tracker/joomla-cms/15640</a>.</sub>

**Comment by Bocatatun** [comment]
Solution:

- Go to menu -> administrator
- Create a new administrator menu, without items
- Go to modules -> administrator
- Delete of modificate "administration menu"
- position -> menu
- menu to show - > "Your new menu"
- check menu -> NO
- Save


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15640">issues.joomla.org/tracker/joomla-cms/15640</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
closed as Issue solved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15640">issues.joomla.org/tracker/joomla-cms/15640</a>.</sub>
