### ISSUE TITLE
Datepicker not working as it should

### ISSUE THREAD

**Issue by vegardaa** [joomla/joomla-cms#15652]
### Steps to reproduce the issue
Pick a date in the datepicker publish tab on a new or  exciting artcile. 

### Expected result

28.04.2017 11:15:59

### Actual result
When I try to set the date for an article to be published I choose the date in the datepicker. When I click on the date the format (?) is wrong: 28.042017 11:15:59. If I click again it jumps to the year 2100 in the calender view and the numbers changes from 28.042017 11:15:59 to 28.055512 15:59:00.
It's the same on all out websites after upgrading to Joomla 3.7. 

I tried choosing a date in a module (advanced module manager). It looks like it is the same datepicker, but it works fine. No problem there, only in articles. 

### System information (as much as possible)
Joomla 3.7 
Norwegian Language (nb-NO)
Centos 7.3, tried upgrading to a newer PHP version but that did not solve the issue

![1](https://cloud.githubusercontent.com/assets/4232489/25522987/564ff1f8-2c05-11e7-8a68-c06900d3c474.PNG)
![2](https://cloud.githubusercontent.com/assets/4232489/25522988/5652171c-2c05-11e7-8554-bd61664b6fd6.png)
![3](https://cloud.githubusercontent.com/assets/4232489/25522989/56551f2a-2c05-11e7-88b5-078585bf05f8.PNG)

.

**Comment by dgt41** [comment]
It's not the calendar it's the language pack that missing one vital information in the xml file. Notify the language maintainer 
@Bakual @infograf768

**Comment by Bakual** [comment]
Please notify the maintainer of your language pack of this bug. To fix it for yourself you can create a language override. The wrong string is:
`DATE_FORMAT_CALENDAR_DATETIME="%d.%m%Y %H:%M:%S"`
Correct would be:
`DATE_FORMAT_CALENDAR_DATETIME="%d.%m.%Y %H:%M:%S"`

Closing asn not an issue with core.

**Comment by vegardaa** [comment]
Thanks you. Did not know where to report this.

**Comment by syntaxerror** [comment]
@Bakual in future, feel free to point them directly to Crowdin, so they can contribute. ;)

**Comment by Bakual** [comment]
Yeah, remembered only afterwards that this language is on Crowdin :smile:
