### ISSUE TITLE
[com_fields] Save as Copy not working properly in custom fields

### ISSUE THREAD

**Issue by stellainformatica** [joomla/joomla-cms#15654]
### Steps to reproduce the issue
Create a new custom field and name it Test, for exemple in Contacts, edit it and click on the button Save as Copy

### Expected result
As per contents, the field is copied with a different name adding a number: Test (2)

### Actual result
The field is not copied, an error appears:
Save failed with the following error: Another Field has the same name (remember it may be a trashed item).

### Additional comments
The behaviour should be as in the articles: Joomla automathically adds a number to the field.

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.
### System information
3.7.1
macOS Sierra, 10.12.4
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by esedic** [comment]
Confirming issue. If you use batch operation, field is successfully copied, but it has the same name.

**Comment by Bakual** [comment]
>  If you use batch operation, field is successfully copied, but it has the same name.

That would be wrong as well, but is technically a different issue (I think).

**Comment by laoneo** [comment]
Can you please test #16664 which should fix the error.

**Comment by brianteeman** [comment]
Closed as we have a Pr for testing
