### ISSUE TITLE
Birthday field only save on required and only in English

### ISSUE THREAD

**Issue by ot2sen** [joomla/joomla-cms#15657]
### Steps to reproduce the issue
Trying to save birthday and date selected in calendar using Danish language in front, which has a different order of %d-%m-%Y than the English %Y-%m-%d set in DATE_FORMAT_CALENDAR_DATE.

### Expected result
Birthday saved

### Actual result
Getting a: Advarsel
Profilen kunne ikke gemmes: Fødselsdatoen som du angav er ugyldig. Angiv venligst en gyldig dato.
Which is the warning for profile could not be saved, birthday entered is invalid. Please enter valid date.

If I change to English front it works (but only if the field is required, else it fails with same warning in English)

### System information (as much as possible)

3.7.0

**Comment by franz-wohlkoenig** [comment]
Tried same in German Lang. (01.01.2000): Write in Field isn't saved, have to select Year by clicking "<", this Date got saved.

**Comment by infograf768** [comment]
I have no issue with French pack.
![screen shot 2017-04-28 at 16 08 34](https://cloud.githubusercontent.com/assets/869724/25532237/fb0a2444-2c2c-11e7-9254-ecb0bb6e2290.png)

![screen shot 2017-04-28 at 16 09 13](https://cloud.githubusercontent.com/assets/869724/25532251/0df904bc-2c2d-11e7-9591-097506d67844.png)

**Comment by infograf768** [comment]
My strings are:
```
DATE_FORMAT_CALENDAR_DATE="%d-%m-%Y"
DATE_FORMAT_CALENDAR_DATETIME="%d-%m-%Y %H:%M:%S"
DATE_FORMAT_FILTER_DATE="d-m-Y"
DATE_FORMAT_FILTER_DATETIME="d-m-Y H:i:s"
```

**Comment by infograf768** [comment]
german pack uses
```
DATE_FORMAT_CALENDAR_DATE="%d.%m.%Y"
DATE_FORMAT_CALENDAR_DATETIME="%d.%m.%Y %H:%M:%S"
DATE_FORMAT_FILTER_DATE="d.m.Y"
DATE_FORMAT_FILTER_DATETIME="d.m.Y H:i:s"
```

not sure we can use period instead of hyphens...

**Comment by Bakual** [comment]
The german one works fine for me. The danish one has a small typo in the `DATE_FORMAT_FILTER_DATE` filter string: `d-m-y` instead of `d-m-Y`. That's why it fails.  I've fixed it in Crowdin but it needs a new release of the language pack. Can you take care of that @ot2sen?

**Comment by Bakual** [comment]
Closing as not a core issue.

**Comment by ot2sen** [comment]
Thanks @Bakual  good catch. Didn´t see that while testing. Added as an override and now it saves as should :)
Will notify the Danish TT coordinator for him to build a new package

**Comment by rbuelund** [comment]
Have released a new package
