### ISSUE TITLE
TinyMCE strange behaviour on Frontend and Backend after update to 3.7.0 for low privileges user.

### ISSUE THREAD

**Issue by Moneetor** [joomla/joomla-cms#15651]
### Steps to reproduce the issue

Write or paste some paragraphs, add some formatting eg. Font size. and you can wait for ampty screen with no update or new article.
Even when you format only few paragraph, you see some junk chars at end. I can't see this behaviour at backend.

### Expected result

Updated or added new article with formatted paragraphs

### Actual result

Blank screen or some junk chars in the article.

### Additional comments

Downgrade to 3.6.x and wait for patch or format at back end? More suggestions?
Update: Administrator or above can edit article freely, even on frontend. Users below Administrators can't commit more complicated formatting such as font size. when there is more paragraphs than 3

**Comment by franz-wohlkoenig** [comment]
Can't confirm, test in Backend.
### System information
3.7.1
macOS Sierra, 10.12.4
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
@franz-wohlkoenig why are you testing in the backend - the report is for the frontend

**Comment by franz-wohlkoenig** [comment]
Title was to big for me.

**Comment by franz-wohlkoenig** [comment]
Test on Frontend like Title decribed and i haven't read: Can't confirm Issue.

**Comment by Moneetor** [comment]
Sorry. Maybe i put it into wrong category. I seems to problem with privileges. Editor, Manager and all below Administrator stuck commit update for article. Maybe new stronger privileges policy blocks from set bigger font when user with low privileges want commit editing. When Administrator update article there is no blank screen even on frontend.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15651">issues.joomla.org/tracker/joomla-cms/15651</a>.</sub>

**Comment by Moneetor** [comment]
What you suggest for evoid problem? Temporary revoke stronger formatting from regular users, and even from moderators?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15651">issues.joomla.org/tracker/joomla-cms/15651</a>.</sub>

**Comment by brianteeman** [comment]
There have been many changes since this issue was submitted. Can you still reproduce the problem with the latest release of Joomla?

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 22th October 2017.

**Comment by ghost** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened.
