### ISSUE TITLE
Issues with directing to default lang variation

### ISSUE THREAD

**Issue by echomedia-alan** [joomla/joomla-cms#15656]
When I click this link: http://uat.example.ie it should redirect to http://uat.example.ie/en but it only happens sometimes (more often than not, its wrong)

Im running an AWS EC2 and PHP 5.6. I was forced to roll-back the update on production to stop this problem so awaiting clarification before installing update again.

All language packs etc. are up to date

**Comment by AlexRed** [comment]
try to disable the "System - Page Cache" plugin<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15656">issues.joomla.org/tracker/joomla-cms/15656</a>.</sub>

**Comment by echomedia-alan** [comment]
That worked Alex - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15656">issues.joomla.org/tracker/joomla-cms/15656</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
closed as issue solved<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15656">issues.joomla.org/tracker/joomla-cms/15656</a>.</sub>

**Comment by AlexRed** [comment]
Solved ?
Disable disable the "System - Page Cache" plugin is not solved the issues. Solve temporarily the situation. But, for me, we need to solve it with the "System - Page Cache" plugin enabled

**Comment by franz-wohlkoenig** [comment]
right @AlexRed, related to #15674
