### ISSUE TITLE
[com_fields] Beez not allowing custom field editing on frontend

### ISSUE THREAD

**Issue by kat05** [joomla/joomla-cms#15665]
### Steps to reproduce the issue

Set Beez as the default template, log in on frontend, edit an article and hit 'Save'

### Expected result

The changes save without any issues.

### Actual result

There is a notice coming up, please see screenshot and actually it seems impossible to see/change the custom fields at all (No issue with Protostar.)

### System information (as much as possible)

Joomla 3.7, php 7.1

### Additional comments

None

![j3_7_beez_fieldrequired](https://cloud.githubusercontent.com/assets/5719486/25533746/eaedd48e-2c31-11e7-87ad-cf362c627083.jpg)

**Comment by PhilETaylor** [comment]
Confirmed... Seems someone never bothered making all core templates overrides compatible with the new features...

**Comment by mbabker** [comment]
In good news Beez3 isn't as badly broken as Hathor :rofl:

**Comment by PhilETaylor** [comment]
So is the fix the same then? Just tell users not to use core provided templates - lmao... 

> Important information: We strongly recommend all users to use the Isis template. The Hathor template has not been updated to work with the new features shipping with this release. When we released Hathor it was built with accessibility in mind, but over the years the Isis template has been improved in terms of accessibility and supporting technologies. We now believe that the Isis template is as good as or possibly better than Hathor.

**Comment by kat05** [comment]
Is this going to get fixed at some point? Been half a year now. :)

**Comment by jwaisner** [comment]
@kat05 Is this still an issue in the latest J3?

**Comment by brianteeman** [comment]
yes

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29577.
