### ISSUE TITLE
Calendar bug in Publishing tab

### ISSUE THREAD

**Issue by kairoen** [joomla/joomla-cms#15661]
It seems that after upgradering sites to Joomla 3.7.0, the calendar field in PUBLISHING tab is broken. There is missing a seperator between month and year. After clicking in calendar field again, the year is converted to year 2100 and it impossible to modify the content.

For a clean install of Joomla 3.7, this works fine.

### Steps to reproduce the issue
1. Create new article
2. Go to PUBLISHING tab
3. choose date from START PUBLISHING.
4. Click outside the calendar field and try again.

### Expected result
The new selected date should appear

### Actual result
See video/GIF here: https://www.dropbox.com/s/vbd3qea54zveu1a/Joomla3.7bug.gif?dl=0

### System information (as much as possible)
php: Linux 102a 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64
dbversion: 5.7.17-0ubuntu0.16.04.1-log
dbcollation: latin1_swedish_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 7.1.3-3+deb.sury.org~xenial+1
server: Apache/2.4.18 (Ubuntu)
sapi_name: apache2handler
version: Joomla! 3.7.0 Stable [ Amani ] 25-April-2017 15:36 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0

### Additional comments
This is critical of publishers who want to change the start and stop date in articles.

**Comment by franz-wohlkoenig** [comment]
@kairoen can you please look if #15652 is similaer?

**Comment by Bakual** [comment]
It's the same issue as https://github.com/joomla/joomla-cms/issues/15652.
Expect an update to your language pack soon. Rune already fixed it in Crowdin :+1:

**Comment by jeroenduller** [comment]
The Publishing tab completely disappeared in article backend using Isis template. Any suggestions how to bring this back?

**Comment by Bakual** [comment]
@jeroenduller Please open a new issue, commenting on a closed and unrelated issue doesn't get anything fixed :smile:

**Comment by jeroenduller** [comment]
@Bakual i did see that, so i posted a new issue under https://github.com/joomla/joomla-cms/issues/15731
