### ISSUE TITLE
[4.0] Template list view (proposal)

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#15668]
Something to spice up the view a little bit. Just a proposal. Thoughts?

![screeny](https://cloud.githubusercontent.com/assets/2019801/25536336/5c7d084a-2c32-11e7-91e8-eae96d306556.png)

@dgt41 @ciar4n @brianteeman @franz-wohlkoenig

**Comment by brianteeman** [comment]
looks nice - will probably need to document the suggested image size and have some styling to address non-standard image sizes but otherwise nice concept

**Comment by C-Lodder** [comment]
Only thing I'm a little concerned about is the fact there's no longer the ability to oder by XXX.

**Comment by brianteeman** [comment]
Why not? its still ordered but instead of vertical its in rows of three

**Comment by dgt41** [comment]
If we manage to get the footer buttons right then we can drop the second list view (this and media are the only components that have 2 list views for the same list!!!).
Like!

**Comment by PhilETaylor** [comment]
> Only thing I'm a little concerned about is the fact there's no longer the ability to order by XXX.

If you install so many templates you need to be able to order them, then you're probably doing something very very strange...

**Comment by C-Lodder** [comment]
@PhilETaylor - This is actually the styles view, not the templates view, which will probably contain more items. Purity 3 alone comes with like 8-9 styles doesn't it?

**Comment by mbabker** [comment]
Also consider multilingual sites...

![screen shot 2017-04-28 at 11 23 23 am](https://cloud.githubusercontent.com/assets/368545/25537693/2b9b6384-2c05-11e7-9cba-fb1af83a9bfa.png)

**Comment by C-Lodder** [comment]
Ah crap, forgot about multilingual. Can't see how this concept would work for that so closing.

**Comment by brianteeman** [comment]
yeah - just came back to say that it wont work if all the styles have the same image
