### ISSUE TITLE
[com_fields] Ability to display the label separatedly from the value (Content - Fields plugin)

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-cms#15669]
### Steps to reproduce the issue

It would be an useful feature to be able to display (via The Content - Fields plugin) the field label separatedly from the field value. 

### Actual result

Right now the syntax allows the following:

> {field 1} will display the field with the ID 1
> {field 1,foo} will display the selected field using the alternative layout 'foo'.
> {fieldgroup 2} will display all fields within the fieldgroup with the ID 2.

### Expected result

It would be useful feature to also allow something like:

> {field_value 1} will display only the field value of the field with the ID 1
> {field_label 1} will display only the field label of the field with the ID 1

### Additional Comments

This allows to display the label and the value in two different places with two different styles in the editor. 

### System information (as much as possible)

Joomla 3.7

**Comment by Bakual** [comment]
* Displaying only the value should be possible when you set the field to hide the label (there is an option for that in the field).
* Displaying only the label would be possible by using a custom layout which only shows the label. Same would of course also be possible for only showing the value. Eg create a layout "label.php" which just echoes the label and then you could use `{field 1, label}`

**Comment by franz-wohlkoenig** [comment]
@AndySDH if Answer by @Bakual solves your Feature Request, please close Issue, thanks.

**Comment by AndySDH** [comment]
It does, actually. Didn't think of that. It's not needed to add this as a feature.
