### ISSUE TITLE
Demo-site: Error loading component: com_content

### ISSUE THREAD

**Issue by joo7** [joomla/joomla-cms#15672]
### Steps to reproduce the issue
On demo-site https://demo.joomla.org/ click "Launch Test Drive".
Click "Content -> Articles"

### Expected result
ok

### Actual result
Error loading component: com_content, Component not found.

### System information (as much as possible)
Tested FF + Opera

**Comment by AlexRed** [comment]
I can confirm<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15672">issues.joomla.org/tracker/joomla-cms/15672</a>.</sub>

**Comment by brianteeman** [comment]
Closed as this has been reported
