### ISSUE TITLE
Scalar Array Error

### ISSUE THREAD

**Issue by silentservicemc** [joomla/joomla-cms#15677]
### Steps to reproduce the issue

Upgraded to Joomla 3.7

### Expected result

Smooth execution of existing code

### Actual result
Warning: Cannot use a scalar value as an array in /home/silentservicemc/public_html/libraries/cms/html/html.php on line 620

Warning: Cannot use a scalar value as an array in /home/silentservicemc/public_html/libraries/cms/html/html.php on line 621

Warning: Cannot use a scalar value as an array in /home/silentservicemc/public_html/libraries/cms/html/html.php on line 622

Warning: Cannot use a scalar value as an array in /home/silentservicemc/public_html/libraries/cms/html/html.php on line 623

Here is the block of code from HTML.php::
else
		{
			$options['relative']      = isset($options['relative']) ? $options['relative'] : false;
			$options['pathOnly']      = isset($options['pathOnly']) ? $options['pathOnly'] : false;
			$options['detectBrowser'] = isset($options['detectBrowser']) ? $options['detectBrowser'] : true;
			$options['detectDebug']   = isset($options['detectDebug']) ? $options['detectDebug'] : true;
		}

### System information (as much as possible)
Host:  GoDaddy.com
PHP version:  5.6
Joomla:  3.7
Template:  Beeze!

**Comment by Quy** [comment]
Please test this pr #15641 to confirm that it will fix your issue.

**Comment by silentservicemc** [comment]
Like a CHAMP!  Thank you for the rapid response...


I am a PowerScript guy by trade... PHP is kinda alien to me.  I saw the $options variable defined as an Array in the preceding If Statement, and assumed it would follow through to the Else statement.


Again, Thank you so much for the rapid turn around.


Sly


________________________________

**Comment by brianteeman** [comment]
Closed

**Comment by Quy** [comment]
@silentservicemc If you have a free moment, please consider marking pr #15641 successful here. Thanks.
https://issues.joomla.org/tracker/joomla-cms/15641
