### ISSUE TITLE
[4.0] Admin Site Title flex

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#15683]
Using flex means that the site title changes position on the screen on almost every page load because it is centred between the page title and the user action icons.

As the text hasnt changed the position on the screen shouldnt change. changing position draws your attention to it and you shouldnt be. Its a distraction!!

Probably you need to use a regular bootstrap grid and not flex

@ciar4n

**Comment by ciar4n** [comment]
Thank you @brianteeman. Had already submitted a PR for this this morn... https://github.com/joomla/joomla-cms/pull/15679

Fix since merged.

**Comment by C-Lodder** [comment]
ah balls, my bad Brian. @ciar4n check `com_associations` in the backend. The title gets pushed on to 2 lines, however the topbar has a set height, so doesn't auto expand. 

![screeny](https://cloud.githubusercontent.com/assets/2019801/25556681/88692b7a-2cf8-11e7-97b1-eca6fbe7a944.png)

**Comment by ciar4n** [comment]
Wrapping the page title here would look strange. Considering both page and site title can potentially be quite long I think we should fine an alternative layout with less restrictions in length for each.

**Comment by infograf768** [comment]
IMHO, site title should be taken away from there. We should go back to 2 top bars as we have in the the 3.x series and make sure that it works on Mobile.
As it is now, not only those are wrong, but the left navigation gets real weird and let's be frank, totally unusable.

![screen shot 2017-05-29 at 11 16 52](https://cloud.githubusercontent.com/assets/869724/26544006/74c13458-4460-11e7-8db4-0f8a2d99b118.png)
![screen shot 2017-05-29 at 11 14 34](https://cloud.githubusercontent.com/assets/869724/26544005/74be7164-4460-11e7-85bf-7af86bd46993.png)

**Comment by infograf768** [comment]
The other aspect is that the now hidden Site title link is clicked when selecting in the dropbox
![screen shot 2017-05-29 at 11 22 30](https://cloud.githubusercontent.com/assets/869724/26544224/42114d80-4461-11e7-8629-ccfc2de6be98.png)

Above I Hover the Select Language filter.

**Comment by infograf768** [comment]
@C-Lodder @ciar4n 
Hope you find a solution soonish.

**Comment by infograf768** [comment]
we may already move back the site preview to get something like
![screen shot 2017-05-31 at 15 27 07](https://cloud.githubusercontent.com/assets/869724/26637023/a25df0da-461e-11e7-8c25-6f5c1bc18960.png)

**Comment by C-Lodder** [comment]
I'm in 2 minds about this. As it stands, some of the titles are very long and the header is using flexbox to split the columns equally into 3 sections, thus not enough space.

Option 1: Have a secondary header (like J3) and put the view title there, so it has a full 12 column grid.

Option 2: Move the 3 icons to the sidebar so header is then split into 2 columns, rather than 3. This may still cause issues on smaller viewports, and I'd rather not have the header height adjusting based on content for desktop.

So I'd rather go with Option 1, but will see what others have to say.

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/16399
