### ISSUE TITLE
[4.0] missing css for mod_login

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#15697]
the login module uses a css class width-auto when you have two factor authentication enabled AND have set the module to use text instead of icons. This css class was from the bootstrap-extended.less file that we are not using in J4 and I dont see a bs4 class to replace it with

<img width="411" alt="screenshotr12-06-51" src="https://cloud.githubusercontent.com/assets/1296369/25563898/514cb818-2d9e-11e7-86a2-d9558e2bf37b.png">
<img width="369" alt="screenshotr12-07-05" src="https://cloud.githubusercontent.com/assets/1296369/25563899/514d0f70-2d9e-11e7-848c-faa5b2d41358.png">
<img width="312" alt="screenshotr12-09-26" src="https://cloud.githubusercontent.com/assets/1296369/25563900/514d7140-2d9e-11e7-913d-968a22faded6.png">

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15697">issues.joomla.org/tracker/joomla-cms/15697</a>.</sub>
