### ISSUE TITLE
Possibiltity to login with username OR email

### ISSUE THREAD

**Issue by peterpeter** [joomla/joomla-cms#15712]
On most (non Joomla!-)sites/shops were I'm registred there is the posibility to login with the username OR the registered email address (and the password). And I think this is a missing feature in Joomla!

I can do a PR, but first wanna here some other thoughts about it.

Ist it worth? Would it be a real addition, or more a security flaw? Should it be realised as an option (e.g. of com_users), as it is a bit less secure? Maybe only available in frontend? Or backend too?

What do you think?

**Comment by laoneo** [comment]
Sounds like an interesting idea. More and more online services do allow multiple login options like username, email or telephone. Can't estimate the security impact.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15712">issues.joomla.org/tracker/joomla-cms/15712</a>.</sub>

**Comment by RickR2H** [comment]
I think this would be a nice feature to have! I suggest you create a PR.

**Comment by ot2sen** [comment]
Just a note that there are more extensions doing just that.
For example this one https://extensions.joomla.org/extensions/extension/access-a-security/site-access/authentication-email/

**Comment by peterpeter** [comment]
Thanks for your thoughts. And the link.
But I think this should be a core feature and not provided by 3rd party - as it is common in many (or most) other web 'systems' as a standard.

The question is, should it be optional by configuration or fix inbuild and available to avoid to bother site-admins with one more thing to think, descide and configure. 

The downside is a little decrease of security (email guessing), and thus the question, should the site admin able to descide or not.

**Comment by mbabker** [comment]
It's fine as an extension (not every behavior must be included in the core package) and even if it were in core it must be a configurable item and not arbitrarily locked one way or the other.

**Comment by franz-wohlkoenig** [comment]
closed as having PR #15725<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15712">issues.joomla.org/tracker/joomla-cms/15712</a>.</sub>
