### ISSUE TITLE
Sub Form Fields do not save

### ISSUE THREAD

**Issue by jayblaq** [joomla/joomla-cms#15723]
### Steps to reproduce the issue

Create a parameter XML for a template add the sub form field code to the XML as described in the documentation

https://docs.joomla.org/Subform_form_field_type

I have tested with the example code and my code and neither work.  Here is my code:

style1.xml

<field name="groups" type="subform" formsource="templates/hue/parameters/basecolors_subform.xml"  layout="joomla.form.field.subform.repeatable-table" multiple="true" label="Subform Field" description="Subform Field Description" />

basecolors_subform.xml

<?xml version="1.0" encoding="UTF-8"?>
<form>
  <field name="selector" type="list" label="Base Color Selector" description="Base Color Number"> 
 				<option value="basecolor1">Base Color 1</option>
				<option value="basecolor2">Base Color 2</option>
				<option value="basecolor3">Base Color 3</option>
				<option value="basecolor4">Base Color 4</option>
				<option value="basecolor5">Base Color 5</option>
				<option value="basecolor6">Base Color 6</option>
	</field>
 <field name="basecolor1" type="colorpicker" default="#79d5e4" label="Color" description="Color: Enter Hex or CSS3 RGBA Values Only - Enter transparent for none."/>
			<field name="basecolor1groups" type="checkboxes" class="btn-group" default="body" label="Base Color Elements" description="Elements to apply color styling">
				<option value="body">Body Text</option>
				<option value="h_1">H1</option>
				<option value="h_2">H2</option>
				<option value="h_3">H3</option>
				<option value="h_4">H4</option>
				<option value="h_5">H5</option>
				<option value="h_6">H6</option>
				<option value="lin_color">Global Link</option>
				<option value="lin_hover">Link Hover</option>
				<option value="lin_active">Link Active</option>
			</field>
</form>

### Expected result

After selecting the Parameter values and saving the subform field parameters should be saved

### Actual result

None of the parameters save

### System information (as much as possible)

Joomla 3.6, Joomla 3.7

**Comment by hieblmedia** [comment]
Confirm this.

There are two ways to implement a subform.

Direct manipulation to type=subform on 'onCustomFieldsPrepareDom'. This does create the count of subform fields as duplicate field_id/item_id entries in #__fields_values table with values of one entry.

Or with an custom field type in /fields/ sub-directory. This also does not work. No values are saved.

**Comment by Bakual** [comment]
@hieblmedia Custom fields don't support subforms. So that is quite expected to fail. But I think the OP refers to using subforms in the template XML, which is a different thing.

@jayblaq Is this the same as https://github.com/joomla/joomla-cms/issues/15958 ?

**Comment by jayblaq** [comment]
The main issue that needs to be resolved is using JS in the sub forms such as color picker etc.

**Comment by Fedik** [comment]
@jayblaq  please test that #15974

**Comment by Bakual** [comment]
Closing as we have a PR
