### ISSUE TITLE
Joomla 3.7 Update Error

### ISSUE THREAD

**Issue by o0odicemano0o** [joomla/joomla-cms#15722]
Can some one explain why my search bar is coding "COM_FINDER_SEARCH_NO_RESULTS_HEADING"

ALL OF MY ADMIN PANEL IS LIKE THIS TOO
![screen shot 2017-05-01 at 16 40 21](https://issues.joomla.org/uploads/1/7e923cfc99af6c6887c83c8465fdb75b.png)

**Comment by hacki65** [comment]
Which language do you use. Try to reinstall your main language.

**Comment by wojsmol** [comment]
@o0odicemano0o see https://docs.joomla.org/J3.x:Changes_in_language_file_loading

**Comment by brianteeman** [comment]
Closed as answered

**Comment by o0odicemano0o** [comment]
@hacki65 I tried removing and reinstalling the language pack.. Still I'm seeing the issue.

**Comment by infograf768** [comment]
Try this patch: https://github.com/joomla/joomla-cms/pull/15620

**Comment by infograf768** [comment]
and tell us if you have the issue also with en-GB or only the pack you try to install, and in this case which pack?

**Comment by o0odicemano0o** [comment]
I'm only using the en-GB pack. Same issue with this pack.

**Comment by infograf768** [comment]
Then it cetainly means your server does not accept parse_ini_file.
please test the patch proposed here https://github.com/joomla/joomla-cms/pull/15620
```
diff --git a/libraries/joomla/language/language.php b/libraries/joomla/language/language.php
index 1eb40fb..9c98ad9 100644
--- a/libraries/joomla/language/language.php
+++ b/libraries/joomla/language/language.php
@@ -830,7 +830,21 @@ protected function parse($filename)
 			ini_set('track_errors', true);
 		}
 
-		$strings = @parse_ini_file($filename);
+		if (!function_exists('parse_ini_file'))
+		{
+			$contents = file_get_contents($filename);
+			$contents = str_replace('_QQ_', '"\""', $contents);
+			$strings = @parse_ini_string($contents);
+		}
+		else
+		{
+			$strings = @parse_ini_file($filename);
+		}
+
+		if (!is_array($strings))
+		{
+			$strings = array();
+		}
 
 		// Restore error tracking to what it was before.
 		if ($this->debug)
@@ -840,7 +854,7 @@ protected function parse($filename)
 			$this->debugFile($filename);
 		}
 
-		return is_array($strings) ? $strings : array();
+		return $strings;
 	}
```
- means delete the line and do not let there the - sign
+ means add the line without the + sign

**Comment by o0odicemano0o** [comment]
This is frustrating..
