### ISSUE TITLE
Quick Joomla! Test Drive (90 minutes) - misc. issues and 404 error

### ISSUE THREAD

**Issue by pepperstreet** [joomla/joomla-cms#15729]
### Steps to reproduce the issue

Please go to [official demo site](https://demo.joomla.org "Official Demo Site") and **scroll down** to the "Quick Test Drive" heading. Click "**Launch Test Drive**" button.

### Expected result

Usable backend and frontend display with all features. 
A few days ago, I have tried that with the previous J!3.6.5 and it worked like a charm.
3.7.0 does not work as expected. See below...

### Actual result

Content/Articles manager is missing. Had to use Extensions manager and "Discover" action to re-install articles manager. But Frontend still throws "404 Component not found"?!
Database not up-to-date. Had to Click "fix")
Warning: PHP temp directory not set.

### System information (as much as possible)

J! 3.7.0 demo site
powered and set up by siteground (?) 

### Additional comments 

Also tried Joomla Update - re-install. No differences. 
I tried the demo two times, from mobile and desktop devices.

---

PS: I was not sure where to report this issue. Please, delete or move it if this is the wrong place.

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.

**Comment by Bakual** [comment]
I'm closing this issue as it is not a core one but something Siteground has to fix.
I'm trying to figure out who we need to contact for that.

**Comment by brianteeman** [comment]
@bakual https://github.com/joomla/joomla-websites/issues/935

**Comment by Sandra97** [comment]
@Bakual I've reported #935 to Kiril from Siteground yesterday.

**Comment by franz-wohlkoenig** [comment]
@pepperstreet please have a Look at [Report](https://github.com/joomla/joomla-websites/issues/935#issuecomment-298609403)

**Comment by pepperstreet** [comment]
Thanks for quick replies and "forwarding"!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15729">issues.joomla.org/tracker/joomla-cms/15729</a>.</sub>
