### ISSUE TITLE
Error Occurred Installing Mobile Joomla

### ISSUE THREAD

**Issue by JamesWitvliet** [joomla/joomla-cms#15739]
### Steps to reproduce the issue

An error has occurred.
0 Class 'MjJoomlaWrapper' not found

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; plgSystemMobileBot has a deprecated constructor in /homepages/31/d569858816/htdocs/anotamain/plugins/system/mobilebot/mobilebot.php on line 28

Warning: include_once(/homepages/31/d569858816/htdocs/anotamain/administrator/components/com_mobilejoomla/legacy/joomlawrapper.php): failed to open stream: No such file or directory in /homepages/31/d569858816/htdocs/anotamain/plugins/system/mobilejoomla/mobilejoomla.php on line 711

Warning: include_once(): Failed opening '/homepages/31/d569858816/htdocs/anotamain/administrator/components/com_mobilejoomla/legacy/joomlawrapper.php' for inclusion (include_path='.:/usr/lib/php7.0') in /homepages/31/d569858816/htdocs/anotamain/plugins/system/mobilejoomla/mobilejoomla.php on line 711

**Comment by brianteeman** [comment]
Please report this to the makers of.mobile Joomla which is an extension. This tracker is just for core issues.
