### ISSUE TITLE
DeBug in J3.7

### ISSUE THREAD

**Issue by CB9TOIIIA** [joomla/joomla-cms#15732]
### Steps to reproduce the issue
Enable debug in plugins
Set on - Show session Data

![022621](https://cloud.githubusercontent.com/assets/1074710/25612240/91d5e5ae-2f32-11e7-9058-b527bb5e2e7c.png)

### Expected result
Display all messages about sql, data, memmory and etc

### Actual result
ONLY show session data

### System information (as much as possible)
Joomla 3.7

### Additional comments
If set OFF - Show session Data - result actual (without sessions).

**Comment by tonypartridge** [comment]
Can you please confirm the exact setup of the plugin, all selected options? The code is set to show the session if it's an option which is added onto the html and not replaced. 

I cannot replicate said issue.

**Comment by CB9TOIIIA** [comment]
Set ON - global config

plugin: 

![023451](https://cloud.githubusercontent.com/assets/1074710/25612568/f754bda0-2f33-11e7-9971-c7b4c98d2c1d.png)

result:

![023656](https://cloud.githubusercontent.com/assets/1074710/25612589/0a9d1ad8-2f34-11e7-9aaa-c93b11ba9fce.png)

Set off session:

![023732](https://cloud.githubusercontent.com/assets/1074710/25612616/2094ecf8-2f34-11e7-8ff2-1fd5f30a2a13.png)

result all need info:

![023811](https://cloud.githubusercontent.com/assets/1074710/25612655/377e4892-2f34-11e7-90a5-2d6d7e3da43f.png)

**Comment by CB9TOIIIA** [comment]
Maybe replace: "Show Session Data"  to "Show ONLY Session Data"

**Comment by tonypartridge** [comment]
No, that's not the usage case here, it's an option and not Show only. Can you try viewing the backend in The English and saving? the plugin. What do you see below the plugin now with debug mode on? 

It should look like:
<img width="692" alt="screenshot 2017-05-02 11 13 17" src="https://cloud.githubusercontent.com/assets/1400982/25614065/5d594cee-2f28-11e7-84d6-89772e47878d.png">

**Comment by CB9TOIIIA** [comment]
In backend ALL - OK, i report about frontpage debug.

**Comment by CB9TOIIIA** [comment]
Frontpage:

![022357](https://cloud.githubusercontent.com/assets/1074710/25614477/c68b6488-2f3a-11e7-9ad6-6656aba6c54c.png)
![022427](https://cloud.githubusercontent.com/assets/1074710/25614478/c6a49516-2f3a-11e7-88f7-2a2e1083d10c.png)

SET ON - session data

![022437](https://cloud.githubusercontent.com/assets/1074710/25614489/ce0b6b54-2f3a-11e7-929c-6bd766670c8f.png)
![022455](https://cloud.githubusercontent.com/assets/1074710/25614490/ce0e222c-2f3a-11e7-8a0b-75d0a74c9fc4.png)

**Comment by tonypartridge** [comment]
Ok so the plugin is working on the backend. It also works fine on my frontend.

Can you confirm testing with the default Joomla! protostar template? Can you try testing on a fresh Joomla! Installation.

**Comment by CB9TOIIIA** [comment]
Tested on protostar - result same.

On fresh Joomla - not tested.

![023541](https://cloud.githubusercontent.com/assets/1074710/25614798/3eefa848-2f3c-11e7-9312-4efbfde7cf65.png)

**Comment by tonypartridge** [comment]
I cannot replicate on a fresh install.

Given it is happening on the frontend of your website, I suspect it's related to a 3rd party plugin.

**Comment by CB9TOIIIA** [comment]
Fresh J 3.7 - it's OK

**Comment by franz-wohlkoenig** [comment]
closed as no Core Issue. Feel free to reopen.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15732">issues.joomla.org/tracker/joomla-cms/15732</a>.</sub>
