### ISSUE TITLE
Redirection fails on multiple status values

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#15737]
### Steps to reproduce the issue

Extensions running on FOF2 call JApplicationWeb->redirect to generate a 303 redirect AND define a Status 201. For example, saving an item.

In the past, Joomla generated a http 303 to the url and exited.

Now, J3.7 is calling the redirect AND generating the rest of headers, cancelling the 303 redirection that originated the call.

### Expected result

Successfull redirection

### Actual result

Blank page. No redirection. In the browser, headers show the Location where the browser must go and a non-300 Status header.

### System information (as much as possible)

Joomla 3.7

### Additional comments

The redirection call must use the same API to generate the headers AND replace any previously defined Status. A fix is coming.

JApplicationWeb, line 567

				// All other cases use the more efficient HTTP header for redirection.
				$this->setHeader('Status', $this->responseMap[$status], true);
				$this->setHeader('Location', $url, true);

**Comment by franz-wohlkoenig** [comment]
@anibalsanchez similar #15730?

**Comment by anibalsanchez** [comment]
Hi @franz-wohlkoenig , no, I've just tested the PR. #15730 is unrelated with this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15737">issues.joomla.org/tracker/joomla-cms/15737</a>.</sub>

**Comment by PhilETaylor** [comment]
PR here https://github.com/joomla/joomla-cms/pull/15738

**Comment by PhilETaylor** [comment]
@franz-wohlkoenig bit slow today? hahahahah close please.

**Comment by franz-wohlkoenig** [comment]
closed as having PR #15738.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15737">issues.joomla.org/tracker/joomla-cms/15737</a>.</sub>

**Comment by nayemmajhar** [comment]
There is a another fix without depending on core for FOF2 support. I have a view called item. For fix, I create a contoller name Item and rewrite FOF2 redirect method

`class MycomponentControllerItem extends FOFController
{

	public function redirect()
	{
		if ($this->redirect)
		{
			$app = JFactory::getApplication();
			$app->enqueueMessage($this->message, $this->messageType);
			$app->setHeader('Status', 'HTTP/1.1 303 See other', true);
			$app->setHeader('Location', $this->redirect, true);
			$app->redirect($this->redirect);
			return true;
		}
		return false;
	}

}`

**Comment by anibalsanchez** [comment]
Hi @nayemmajhar ,

Only the status must be corrected, because it was previously defined as 201. I've also added the Status update in my extension controllers for J 3.7.0.

Regards,
