### ISSUE TITLE
Multilingual associations is missing

### ISSUE THREAD

**Issue by apelsinskal** [joomla/joomla-cms#15734]
### Steps to reproduce the issue
Updated to Joomla 3.7 - didn't get the Multilingual associations manager

### Expected result
3.7 works fine but the Multilingual associations manager is simply missing.

**Comment by Bakual** [comment]
How did you do the update?

**Comment by apelsinskal** [comment]
Just clicked the "update now" button from backend<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15734">issues.joomla.org/tracker/joomla-cms/15734</a>.</sub>

**Comment by wilsonge** [comment]
If you go to extensions manager -> discover. And try and discover install the extension does that work?

**Comment by apelsinskal** [comment]
No. Tried after installation, and again now. Only "old" templates updates there.

**Comment by wilsonge** [comment]
Can you check if there are any files in `administrator/components/com_associations`

**Comment by apelsinskal** [comment]
![skarmavbild 2017-05-02 kl 12 35 34](https://cloud.githubusercontent.com/assets/18310962/25614820/fa52e554-2f33-11e7-848b-97a6e0e1101a.png)

**Comment by AlexRed** [comment]
try to Clear Cache (Administrator)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15734">issues.joomla.org/tracker/joomla-cms/15734</a>.</sub>

**Comment by apelsinskal** [comment]
Nothing to clear ("No Matching Results")

**Comment by wojsmol** [comment]
@apelsinskal Go to extensions manager -> database and click fix button

**Comment by apelsinskal** [comment]
No luck with that either....

**Comment by infograf768** [comment]
The new admin menu item for Multilingual associations is not created by an update sql, but directly in script.php

https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/script.php#L112-L156

**Comment by rdeutz** [comment]
Can you have a look if you have a database row with title = 'com_associations'

**Comment by apelsinskal** [comment]
I only have "j25_associations", no "com_associations"

**Comment by infograf768** [comment]
Look also in the extensions table please to check if com_associations exists there.

**Comment by apelsinskal** [comment]
@infograf768 yes it does

**Comment by infograf768** [comment]
OK, we could try something:
Delete the row in extensions table.
Then try to discover again.

**Comment by apelsinskal** [comment]
Works like a charm! Thank you so much!

**Comment by infograf768** [comment]
Closing as issue solved.
