### ISSUE TITLE
Page cache with file storage causes white pages

### ISSUE THREAD

**Issue by weeblr** [joomla/joomla-cms#15733]
In 3.7.0, under some circumstances, enabling the Cache system plugin can result in white pages for some pages

### Steps to reproduce the issue
1. Enable Cache system plugin
2. Go to its parameters and exclude one or more menu items from caching
3. Visit said menu item -> all good
4. Visit a second time -> white page

### Expected result

The page should display the same regardless of whether it's been viewed before.

### Actual result

You get  a white page.

### System information (as much as possible)

Happens if using file for storage.

### Additional comments

This is caused by a change in the lock function of the file cache storage backend: https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/cache/storage/file.php#L354

It was changed from (J! 3.6.5) 

````
$_fileopen = @fopen($path, 'r+b');
````
to (J! 3.7.0)

````
$_fileopen = @fopen($path, 'c+b');
````

This causes the cache file for a given page to be created when we check for its existence (it's created with an empty content of course) during onAfterInitialize.

Now later on, during onAfterRespond, nothing is stored in that file, because the menu item has been excluded from caching, but the empty file is still there.

Upon subsequent requests for the same page, the empty file is found during onAfterInitialize and thus loaded and displayed, resulting in a white page.

I don't know why this was changed, but I suspect this should simply be reverted. An alternative would be to only display the cached content if the cache file is not empty, but that doesn't sound right.

Change: https://github.com/joomla/joomla-cms/commit/d2dd941a4a07a4ee3d007516d9e1c7243430a49f

Note: I only tested this on windows, but PHP's fopen **c** flag is supposed to behave the same on all systems, and will create that file. I do have reports from users experiencing the same on standard hosting, which is why I looked into it.

/cc @csthomas @mbabker

**Comment by csthomas** [comment]
It is done at https://github.com/joomla/joomla-cms/pull/15592

**Comment by weeblr** [comment]
Ah crap, I did search quite a bit, including the closed issues!

**Comment by Bertram25** [comment]
I have a similar issue with firefox 55.0 (64 bits) - Debian Sid on github.com

**Comment by brianteeman** [comment]
Please create a new issue as comments on closed issues will not be seen
