### ISSUE TITLE
Explicitly mark `@covers` annotations in unit tests

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#15741]
A lot of our test coverage is coming from the fact that there are a lot of deep rooted internal couplings and static method calls which cannot be mocked.  This is massively throwing off our coverage reports and misrepresenting our actual state of the test suite.  We need to work through the test suite to explicitly mark what the test cases are actually covering so we stop having leakage of covered code through test cases that aren't designed to be covering certain methods (i.e. `JApplicationCmsTest` shouldn't be covering the `JDate` constructor).  This will help to better represent what we have explicit test cases and coverage for and therefore help us to better refine our test suite.

https://twitter.com/mbabker/status/859412612471300096

**Comment by PhilETaylor** [comment]
If only... 

But still the project accepts new features and new code without accompanying them with valid unit tests... until this is addressed, this problem will only grow and grow... :(

**Comment by mbabker** [comment]
We've gotta start somewhere.  When you have 1900 cases for the `JDate` constructor and 1896 of them are from tests that cover code that uses `JDate` (as in they shouldn't be covering that), you're basically left with not knowing what code you're actually testing.

**Comment by mbabker** [comment]
Most tests are gone in 4.0.  No point in touching 3.x tests.
