### ISSUE TITLE
Unable to select an article when making an new dummy menu item

### ISSUE THREAD

**Issue by Roodgloeiend** [joomla/joomla-cms#15744]
### Steps to reproduce the issue

Make a new menu item in the dummy menu, select menu item, article, individual article, then select an article and it get's stuck.

### Expected result
A dummy link to an article

### Actual result
No dummy link to an article

### System information (as much as possible)
Joomla version 3.7.0

**Comment by infograf768** [comment]
What exactly do you call a "dummy" menu?

**Comment by franz-wohlkoenig** [comment]
@Roodgloeiend Assuming you mean "dummy Link to an Article" means `Menu Item Type: Single Article` can't confirm Issue as select an Article works.

**Comment by Roodgloeiend** [comment]
An invisible menu link, to make the URL cleaner.

 

 

 

 

Van: infograf768 <notifications@github.com>
Beantwoorden - Aan: joomla/joomla-cms <reply@reply.github.com>
Datum: dinsdag 2 mei 2017 17:54
Aan: joomla/joomla-cms <joomla-cms@noreply.github.com>
CC: Roodgloeiend <tim@roodgloeiend.com>, Author <author@noreply.github.com>
Onderwerp: Re: [joomla/joomla-cms] Unable to select an article when making an new dummy menu item (#15744)

 

What exactly do you call a "dummy" menu?

**Comment by infograf768** [comment]
Dummy or not, indeed, selecting article does work

**Comment by Quy** [comment]
Do you want to exclude the menu item from displaying in the menu? If yes, edit the menu item and under the `Link Type` tab, select `No` for the `Display in Menu` option.

**Comment by rblezer** [comment]
There is a bigger problem underneath. When creating menus of type  "menu heading" and "text separator" in the ISIS template, the following happens:

These menus are grayed out, meaning you can't choose then as module targets.

Switching to Hathor, this works.  You can select the menus for module publishing use. 
Saving a module in the ISIS template removes the module from the menu again!
See screenshots. When you save in ISIS template module gets removed from menu.
[screen shot 2017-05-03 at 10 44 37](https://issues.joomla.org/uploads/1/4893d2a8fa6efb20348a62794a091499.jpg)![screen shot 2017-05-03 at 10 44 37](https://issues.joomla.org/uploads/1/cf9660952776a995c3e85de05e65ca81.jpg)![screen shot 2017-05-03 at 10 44 37](https://issues.joomla.org/uploads/1/0152e43ca20c9a1c3dc66555ddb28233.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15744">issues.joomla.org/tracker/joomla-cms/15744</a>.</sub>

**Comment by brianteeman** [comment]
There are two different issues here

The first one no one has been able to replicate
The second one is by design - if you have a menu type of seperator or heading then of course it is not a real page so there is no need to ever be able to set a module to display on a non existant page
