### ISSUE TITLE
Update to 3.7 moved all menu items to trash

### ISSUE THREAD

**Issue by euoceo** [joomla/joomla-cms#15749]
As the subject says. Updated to 3.7 and the site broke with 404. Upon more research all menu items were moved to trash status.

Restored the site from a backup, repeated install, same results.

cPanel hosting environment.
Database Version 	5.5.5-10.0.30-MariaDB
Database Collation 	latin1_swedish_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.6.30
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0![screen shot 2017-05-02 at 21 09 03](https://issues.joomla.org/uploads/1/b5553ec9c930d591c06b089829dd39e0.png)

**Comment by wojsmol** [comment]
@euoceo Which version of Joomla! do you upgrade?

**Comment by csthomas** [comment]
Check the published column in a table `#__menu` (replace `#_` to your prefix) for the first row with `id=1` and `alias='root'`.
This column (published) should have a value equal to 1.

**Comment by euoceo** [comment]
@wojsmol The lastest 3.6.5 branch.

**Comment by euoceo** [comment]
@csthomas Before update, the publish column value is -2! Odd.

**Comment by infograf768** [comment]
Can we close this it does not look like a joomla bug?

**Comment by franz-wohlkoenig** [comment]
closed as no Core issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15749">issues.joomla.org/tracker/joomla-cms/15749</a>.</sub>

**Comment by euoceo** [comment]
So reset that column to "1" and re-update? I'm not sure how it became -2, something off there, but as you say problem not related to the core.. Thx

**Comment by csthomas** [comment]
> So reset that column to "1" and re-update?

Yes.
I wonder If we can add to joomla update sql files below sql 
```sql
UPDATE `#__menu` SET published=1 WHERE id = 1
```
to change this value to 1.

**Comment by euoceo** [comment]
FYI, this worked. Updated table above to id = 1. Then updated to 3.7 and all worked fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15749">issues.joomla.org/tracker/joomla-cms/15749</a>.</sub>
