### ISSUE TITLE
Insert Field in Articles shows as Field Number {field } when clicked on Title in Category Blog

### ISSUE THREAD

**Issue by esskay303** [joomla/joomla-cms#15751]
### Steps to reproduce the issue

1. Insert Field in Article
2. Article Options - Set Linked Titles to Yes, Show Unauthorised Links to Yes, Show Intro Text to Hide, 
3. Set Article Access to Registered
4. Create any custom field with access right to public and insert in the article before read more (intro text)
5. Create category blog menu item
6. Check front end as non logged in user.

### Expected result

Clicking on article title should show inserted field value.

### Actual result

Clicking on article title show field name as (field --}

### System information (as much as possible)

1. PHP 7.0.18
2. Joomla 3.7
3. Database 5.6.28
4. Database Collation utf8_general_ci
5. Joomla Platform Version 13.1.0 Stable

**Comment by AlexRed** [comment]
I can confirm the problem on Joomla! 3.7.1-dev (nightly Build)

**Comment by esskay303** [comment]
Hello...Any update on this...? When this will be fixed...?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15751">issues.joomla.org/tracker/joomla-cms/15751</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@esskay303 if there is a Developer having free Time for fixing this Issue. Maybe @laoneo or @Bakual in this Case, but its their Decision on what Issue they are willing to work.

**Comment by laoneo** [comment]
I guess a event is not triggered correctly.

**Comment by Bakual** [comment]
The problem is how the "Show Unauthorized" thing is working. If that parameter is active, then the layout only displays the introtext hardocded. See https://github.com/joomla/joomla-cms/blob/staging/components/com_content/views/article/tmpl/default.php#L135

The plugin event however doesn't act on the introtext, it acts on the `$item->text` property in the view class. See https://github.com/joomla/joomla-cms/blob/staging/components/com_content/views/article/view.html.php#L166-L177

So if someone wants to take and fix that, he needs to refactor the "Show Unauthorized" feature so it uses the text property or triggers the evens on the introtext.

**Comment by esskay303** [comment]
Any update on this? When it is likely to be fixed?

**Comment by ghost** [comment]
@esskay303  if there is a Developer having free Time for fixing this Issue.

**Comment by esskay303** [comment]
If somebody can give me raw code I will test it thoroughly...

**Comment by ghost** [comment]
me too, @esskay303

**Comment by laoneo** [comment]
Please test #17175, which should fix the issue.

**Comment by zero-24** [comment]
Closing as there is a a PR for testing. Thanks.

**Comment by esskay303** [comment]
Unfortunately after updating to 3.8.1 this problem has again popped up...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15751">issues.joomla.org/tracker/joomla-cms/15751</a>.</sub>

**Comment by ghost** [comment]
@esskay303 please open a new Issue as Comments on closed Issues didn't get much Notice.
