### ISSUE TITLE
Default order of articles in back-office changed to order-id ascending. Why?

### ISSUE THREAD

**Issue by peterwouda** [joomla/joomla-cms#15750]
In the back-office the default order of articles is changed to ID ascending. I guess most users want the ordering by creation-date descending (or id descending) so the most recent article is the first. 

I can't find a way to change this default ordering in the settings. Maybe a new feature in 3.7.1?

**Comment by Quy** [comment]
Duplicate #15549 ?

**Comment by franz-wohlkoenig** [comment]
closed as duplicate Report #15549<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15750">issues.joomla.org/tracker/joomla-cms/15750</a>.</sub>
