### ISSUE TITLE
Groups for modules

### ISSUE THREAD

**Issue by mxk-ru** [joomla/joomla-cms#15752]
It has long been time to enter groups (drop-down lists) of modules. For example, I need to make 10 landing pages on the site. Each page consists of 7 modules. It turns out the real hell in the list of modules. And there are many modules for the site itself. In order to make it easier to navigate, there is a shortage of logical grouping of modules.

**Comment by franz-wohlkoenig** [comment]
@Maintainers: A Feature Request for Core or a Plugin-Solution from JED?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15752">issues.joomla.org/tracker/joomla-cms/15752</a>.</sub>

**Comment by ghost** [comment]
closing as no Response. It can always reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15752">issues.joomla.org/tracker/joomla-cms/15752</a>.</sub>
