### ISSUE TITLE
Edition in front category is already locked

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#15759]
### Steps to reproduce the issue
1 create a link on front to a submit a form with a locked categorie (blog)
2 edit an item in other categorie (event)=> categorie field is locked to event
3 when you save item is moved to loked categorie (blog)

### Joomla 3.7

**Comment by franz-wohlkoenig** [comment]
1. created a Menu Item Type `Create Article`, set in `Options` Category on `Protostar`, this Cateory is unpublished (i guess you mean this by "locked")
2. edit and saved an Article of other Category. Article stay in Category, didn't switch to unpublished Category (guess this is what you mean).

Short: Can't confirm issue (if i got your Description right)

**Comment by micker** [comment]
hello no category are published
i mean if a link to submition exist all link to edit check his params

**Comment by brianteeman** [comment]
Can you post some screenshots to explain this better.

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 26th November 2017.

**Comment by ghost** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened.
