### ISSUE TITLE
Broken Links in "Sample Site / Park Blog"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#15758]
### Steps to reproduce the issue
Install  "Sample Sites": index.php/en/park-blog
![bildschirmfoto 2017-05-03 um 11 31 43](https://cloud.githubusercontent.com/assets/8235763/25655180/4f4c8892-2ff4-11e7-8870-a21abbd74787.JPG)

- first Link "[comments](https://extensions.joomla.org/extensions/contacts-and-feedback/articles-comments)" work, 

broken are:

- "[interacting with social network sites](https://extensions.joomla.org/extensions/social-web)"
- "[tagging](https://extensions.joomla.org/extensions/content-sharing)"
- "keeping in contact with your readers" (same Target as "tagging)"
### System information
3.7.1-dev
macOS Sierra, 10.12.4
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
Closed see #16012
