### ISSUE TITLE
[4.0RFC] Time to remove the "whos online"

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15768]
### Steps to reproduce the issue

browse a joomla 4 site 
login to frontend

### Expected result

We have 0 guests and one member online

### Actual result

We have 15 guests and one member online

### Additional comments

The "whos online" has been here since Mambo days, it has NEVER been an accurate count and its about time it was simply scraped in Joomla 4

Discuss

**Comment by brianteeman** [comment]
-1 from me - I have a lot of clients who use this

**Comment by PhilETaylor** [comment]
> who use this

Who use inaccurate data that is not a count of users online but a count of sessions in the database table... doesnt even support other session handlers at all.

**Comment by mbabker** [comment]
Actually because of the longstanding behavior of always writing session metadata to the `#__session` table (independent of the session handler), it is still somewhat accurate based on the logic in the application to do basic CRUD operations there.  Even that can go away in 4.0 if https://github.com/joomla/joomla-cms/pull/13322 gets accepted.

**Comment by PhilETaylor** [comment]
>  still somewhat accurate

Im the only one in front of my mac... there are not 15 guests on my site right now :)

**Comment by elkuku** [comment]
I'd be in favor of decupling :wink: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15768">issues.joomla.org/tracker/joomla-cms/15768</a>.</sub>

**Comment by chmst** [comment]
If I understad decupling right .. like com_weblinks? Yes! :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15768">issues.joomla.org/tracker/joomla-cms/15768</a>.</sub>

**Comment by C-Lodder** [comment]
+1 to decouple.

**Comment by Spudley** [comment]
Question: Would this just be the user count on the front-end, or are you also proposing to remove the admin panel 'Logged in Users' module and the user counts in the admin panel footer?

I would definitely want to keep those items in the admin panel, but happy to lose the one on the front-end.

I assume if we do decouple anything, then sites upgrading would keep the feature? ie it would only be new sites that would have to install it separately?

If the above is true, then yes: +1 to decouple.

**Comment by chmst** [comment]
I think it is the site module whoisonline, nothing else. And I know that many users like it, no matter if it shows exactly correct states. So I would like to see it as a well maintained core extension as weblinks. But I also would like to decuple such modules and also components like com_banners from the core.  (just my2cent).

**Comment by brianteeman** [comment]
Based on the incident with the session cache recently it is clear that a lot of people are using it. No matter how inaccurate it may be.
