### ISSUE TITLE
[4.0] Editing a module on the frontend in the default template issues

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15764]
### Steps to reproduce the issue

Login to frontend 
attempt to edit a module

### Expected result

Something looking good.

### Actual result

<img width="1047" alt="screen shot 2017-05-03 at 13 03 19" src="https://cloud.githubusercontent.com/assets/400092/25659722/fb8771e2-3000-11e7-8b7c-82c7525d8ce3.png">

### Additional comments

Also note how the edit form gets "lost" in all the business of all the modules... maybe the edit page should hide much of the page ?

**Comment by C-Lodder** [comment]
Edit view should definitely hide modules. Probably wouldn't be as much of an issue on live/finished sites but with sample data, it's annoying having to scroll down.

- Option 1: Use JS to scroll the user to the form
- Option 2: Hide all modules

If option 2 is prefered, is there some fancy Joomla function for this?

**Comment by dgt41** [comment]
The frontediting.js is not **yet** compatible with J4

**Comment by PhilETaylor** [comment]
option 3 - lift the form div into a modal on top of the page?

**Comment by C-Lodder** [comment]
That could work too. Would mean the user's ettention is focused purely on the form.

Here's the styling part fixed anyway: https://github.com/joomla/joomla-cms/pull/15803

**Comment by brianteeman** [comment]
@dgrammatiko has frontediting.js been updated yet?

**Comment by dgrammatiko** [comment]
The status is:
- frontediting.js has been moved to media/legacy with an intention to have it replaced by a custom element

But this issue reported here seems that has already been solved (?):
![screen shot 2018-05-22 at 23 59 08](https://user-images.githubusercontent.com/3889375/40392675-b38b3626-5e1c-11e8-84a9-2409610abaa4.png)

The proposal for a modal or different UI is something that the @coolcat-creations needs to figure out

**Comment by ghost** [comment]
@PhilETaylor can you please check if the Issues is solved?

**Comment by PhilETaylor** [comment]
Tested on a45c321df28b6dff5b7d75979186b5ec2c17dbfb and it seems to work now.

**Comment by ghost** [comment]
thanks @PhilETaylor
