### ISSUE TITLE
[4.0] Finder Suggestions ajax call uses & in urls instead of plain &

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15763]
<img width="1275" alt="screen shot 2017-05-03 at 13 01 27" src="https://cloud.githubusercontent.com/assets/400092/25659659/ae839d26-3000-11e7-9923-91f115e8f038.png">

**Comment by franz-wohlkoenig** [comment]
@mbabker an issue for 4.0-Projects?

**Comment by ghost** [comment]
should this Issue be closed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15763">issues.joomla.org/tracker/joomla-cms/15763</a>.</sub>

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 22th October 2017.

**Comment by ghost** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened.
