### ISSUE TITLE
[4.0] User Menu module outline missing

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15765]
### Steps to reproduce the issue

Install joomla 4 
login to frontend

### Expected result

User Menu module on right has a border 

### Actual result

<img width="472" alt="screen shot 2017-05-03 at 13 06 32" src="https://cloud.githubusercontent.com/assets/400092/25659827/6f0dd0de-3001-11e7-9166-466a4f62d3bb.png">

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/15780

**Comment by franz-wohlkoenig** [comment]
closed as having PR #15780<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15765">issues.joomla.org/tracker/joomla-cms/15765</a>.</sub>
