### ISSUE TITLE
Module position

### ISSUE THREAD

**Issue by JamesWitvliet** [joomla/joomla-cms#15761]
### Steps to reproduce the issue
I have tried to insert a module into the right hand side of a page, using sidebar-b. Assigning it to this position it has created the space on the right hand side of the page but the module is below the article rather than in that space.

**Comment by Spudley** [comment]
Sounds like a template issue. What template are you using? A standard one or a third-party one? Have you modified it at all yourself.

Also, what Joomla version are you using?

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding.
