### ISSUE TITLE
[4.0] search css broken

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15762]
### Steps to reproduce the issue

install Joomla 4
search in bottom left module

### Expected result

to be able to search

### Actual result

<img width="329" alt="screen shot 2017-05-03 at 12 57 53" src="https://cloud.githubusercontent.com/assets/400092/25659566/45d88e08-3000-11e7-8e77-a912b4434820.png">

broken css styled inputbox after typing 2 chars (after the ajax returns no suggestions. 

<img width="305" alt="screen shot 2017-05-03 at 12 57 58" src="https://cloud.githubusercontent.com/assets/400092/25659567/45d8caf8-3000-11e7-8192-53dfd6230780.png">

**Comment by franz-wohlkoenig** [comment]
@PhilETaylor can you please have a Look again, looks solved:
![bildschirmfoto 2017-06-09 um 20 15 37](https://user-images.githubusercontent.com/8235763/26988627-6feced84-4d50-11e7-82a2-0bcc12988ca1.jpg)

**Comment by ghost** [comment]
@PhilETaylor is this Issue solved?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15762">issues.joomla.org/tracker/joomla-cms/15762</a>.</sub>
