### ISSUE TITLE
[4.0] Cannot edit content in the frontend - PHP Fatal Error

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15767]
### Steps to reproduce the issue

install Joomla 4 at ae3b0a44564e5b395c5fcf3f5db9723f54eb2a95
Login to frontend as super admin
edit an article

### Expected result

Being able to edit an article

### Actual result

Fatal error: Class 'ContentModelArticle' not found in /Users/phil/Sites/joomla4/components/com_content/models/form.php on line 23

**Comment by wilsonge** [comment]
I cannot replicate this anymore. I suspect it got fixed when we finished namespacing the frontend of com_content.
