### ISSUE TITLE
[4.0] Tagged Items view unstyled

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15774]
### Steps to reproduce the issue

http://joomla4/index.php/tagged-items
<img width="1182" alt="screen shot 2017-05-03 at 13 34 01" src="https://cloud.githubusercontent.com/assets/400092/25660670/3324ba84-3005-11e7-96f1-67f17f605049.png">

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/15944

**Comment by brianteeman** [comment]
Closed

**Comment by C-Lodder** [comment]
@mbabker this can be moved into the "testing/review" stage
