### ISSUE TITLE
[4.0] [RFC] Remove per second publish_up/publish_down times

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15772]
Lets try this one last time... 

In order for mysql caching to be most performant, the queries need to be exactly the same

At the moment each query with a publish_up/publish_down time in it has a second part to the time

This means that mysql cannot cache the query.

Suggestions include (over the years) 

1) Remove the seconds - meaning mysql can only cache for a minute

2) Allow this to be configurable, either use just days or hours or mins or second based timestamps in the SQL queries (always allowing the full datetime to be stored when saving the articles) 

3) answers on a postcard please... 

Joomla 4 is a great time to revisit this... making Joomla more performant and breaking with b/c

**Comment by brianteeman** [comment]
Sorry but as there has been no interest by anyone in moving forward with this feature request I am going to close it,

**Comment by PhilETaylor** [comment]
Just like the same that happened at every major series since the start... its a shame, because this one change would make Joomla content a lot more performance and cacheable.

**Comment by mbabker** [comment]
If I had time I'd take it.  But, well, prepared statements aren't going to write themselves.

**Comment by PhilETaylor** [comment]
I could not see the point in doing any code until it at least had some interest here.. which apparently it doesnt :(

**Comment by brianteeman** [comment]
@PhilETaylor if its so important to you then PR is welcome and I will personally ensure that it gets tested promptly. Unfortunately with issues like this many people wait to see code as they can not visualise the issue or they do not have the development skills to appreciate the issue
