### ISSUE TITLE
[4.0] Remove ALL vanilla JS

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#15776]
Vanilla JS is a **very** bad idea. We need to ensure Joomla is bound to jQuery 1.x so that we can support IE 8 still. This won't affect mobile users and will attract more contributors as they're be more familiar with the library

@dgt41 - Please can you also rewrite your calendar in jQuery

**Comment by mbabker** [comment]
Is this fight really bleeding over here now?

**Comment by dgt41** [comment]
Of course, I'm on it (on my way out, start running)...
