### ISSUE TITLE
[4.0] Mailto an article leads to a blank page

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15778]
### Steps to reproduce the issue

install Joomla 4
go to an article and select the Cog dropdown and then Mail 

### Expected result

a pop up allowing me to mail this article to a friend

### Actual result

blank page of death with a url of http://joomla4/index.php/component/mailto?tmpl=component&template=aurora&link=e12c9f73c44c39b9d40d092e66ad2cd042c4e298

**Comment by brianteeman** [comment]
Closed as we have a pr see #16341
