### ISSUE TITLE
[4.0] [RFC] Move away from SQL to PHP Seeding of initial database states

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15775]
Joomla 4 would be a great time to seed the initial state of Joomla with PHP instead of a SQL dump.

Advantages 

 - Set published timestamps that are recent
 - Set correct author id on items based on the random user id generated
 - Greater control over the content
 - Using the Joomla Database API to insert data will mean less relying on making non-mysql sql dumps 
 - etc... 

Discuss.

**Comment by brianteeman** [comment]
> Set correct author id on items based on the random user id generated

This is already done in 3.7 isnt it?

**Comment by PhilETaylor** [comment]
maybe, but this is about 4, and moving to a PHP seed which would have allowed that bug to be resolved in seconds instead of years

**Comment by elkuku** [comment]
BIG :+1: 
Might be a cool GSOC project :wink:
