### ISSUE TITLE
[4.0] Password Field Validation Error

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15777]
### Steps to reproduce the issue

enter one char in the password login box and blur

### Expected result

No validation error

### Actual result

<img width="607" alt="screen shot 2017-05-03 at 13 41 53" src="https://cloud.githubusercontent.com/assets/400092/25660943/5c18297a-3006-11e7-95be-bd09e24b8315.png">

### Additional comments

Yes I know a 1 char password is bad/unrealistic - but so is the validation error message.

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15777">issues.joomla.org/tracker/joomla-cms/15777</a>.</sub>

**Comment by ghost** [comment]
@C-Lodder can you please have a Look on this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15777">issues.joomla.org/tracker/joomla-cms/15777</a>.</sub>

**Comment by ghost** [comment]
Reminder to @C-Lodder as Issue is same.

**Comment by C-Lodder** [comment]
Still havent forgotten. I need to sit down and rewrite the script at some point. @dgt41 wasnt this going to be a CE?

**Comment by dgrammatiko** [comment]
yup, this needs to become a ce

**Comment by Quy** [comment]
Not reproducible

![login](https://user-images.githubusercontent.com/368084/40391300-9f34410e-5dcc-11e8-8047-5544e52a141c.jpg)
