### ISSUE TITLE
[4.0] Featured Contacts Unstyled

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15773]
http://joomla4/index.php/featured-contacts?view=featured&id=16

<img width="648" alt="screen shot 2017-05-03 at 13 32 58" src="https://cloud.githubusercontent.com/assets/400092/25660638/1314c9e6-3005-11e7-93ae-35f224748b0e.png">

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/15801
