### ISSUE TITLE
[4.0] Published: 01 January 2011

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15770]
### Steps to reproduce the issue

install Joomla 4
Look at the published dates on the frontend

### Expected result

some recent date... like the date I set up the site, or at least something this year... 

### Actual result

> Published: 01 January 2011

**Comment by mbabker** [comment]
Someone made the decision years ago that all of the default/sample content should use that date so people couldn't identify the CMS version based on the dates of the content.  Can't say I agree with it, but that's the reasoning.

It also doesn't help that in 2017 we still work with raw SQL dumps and still can't use proper PHP APIs to seed our database.

**Comment by PhilETaylor** [comment]
> It also doesn't help that in 2017 we still work with raw SQL dumps and still can't use proper PHP APIs to seed our database.

see: https://github.com/joomla/joomla-cms/issues/15775

**Comment by PhilETaylor** [comment]
>  so people couldn't identify the CMS version based on the dates of the content

All the more reason to have the installation date (which will be pseudo random then) as the timestamp.

**Comment by brianteeman** [comment]
Wasn't this fixed for J3

**Comment by ghost** [comment]
@brianteeman all Articles get installation-Date in J3, so i guess this Issue can be closed.

**Comment by brianteeman** [comment]
@franz-wohlkoenig this refers to j4

**Comment by ghost** [comment]
@brianteeman i understand your [Comment](https://github.com/joomla/joomla-cms/issues/15770#issuecomment-323323955) that if it is fixed in J3 its also fixed in J4.

**Comment by ghost** [comment]
any Update @wilsonge?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15770">issues.joomla.org/tracker/joomla-cms/15770</a>.</sub>

**Comment by brianteeman** [comment]
Sample data will be rewritten for Joomla 4 I hope so this won't be an issue. I would close it for now

**Comment by ghost** [comment]
closed as Issue solved in the Meantime.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15770">issues.joomla.org/tracker/joomla-cms/15770</a>.</sub>
