### ISSUE TITLE
[4.0] Print an article leads to a blank page

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15779]
### Steps to reproduce the issue

install Joomla 4
go to an article and select the Cog dropdown and then Print 

### Expected result

a pop up allowing me to Print this article 

### Actual result

blank page of death with a url of http://joomla4/index.php/article-categories/26-park-site/28-photo-gallery/72-animals/57-wobbegone?tmpl=component&print=1&page=

**Comment by franz-wohlkoenig** [comment]
can you please proof this ssue again? Got now this:
![bildschirmfoto 2017-06-09 um 20 07 49](https://user-images.githubusercontent.com/8235763/26988386-6d94a622-4d4f-11e7-9a48-107e42f3c6d5.jpg)

**Comment by brianteeman** [comment]
closed as this appears to have been resolved elsewhere - the print view is not correct but its not a white page of death
