### ISSUE TITLE
[4.0] You are not auth to view after logout when in edit mode

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15789]
### Steps to reproduce the issue

install Joomla 4 with default content
login to the frontend as the super admin
click one of the edit icons on a module
While in that edit mode click the Logout button in the module on the right

### Expected result

Im logged out and returned "somewhere" nice with no errors. 

### Actual result

A confusing Green AND red error message

<img width="693" alt="screen shot 2017-05-03 at 14 50 33" src="https://cloud.githubusercontent.com/assets/400092/25663547/e6976e2c-300f-11e7-91e6-9e919f4d710d.png">

**Comment by C-Lodder** [comment]
@ciar4n @dgt41 the markup seems odd. Seems as if there is markup from a floated AND static alert, but could be wrong. Would you mind looking into this?

**Comment by ciar4n** [comment]
This should resolve itself with an update of BS.

https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/aurora/css/template.css#L3493

Compared to...

https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css#L4667

**Comment by C-Lodder** [comment]
v4-dev is the same as master on BS.

It's to do with this: https://github.com/joomla/joomla-cms/blob/4.0-dev/media/system/scss/_jalert.scss

If I rightly remember, I added this as some successful messages were appearing in a blue box instead of green.

**Comment by brianteeman** [comment]
Tried to replicate this now that BS has been updated and get a worse problem with the following error
> 0 Class 'Notallowed' not found

**Comment by brianteeman** [comment]
As of the time of this comment the reported error no longer occurs and you do get the expected result
> Im logged out and returned "somewhere" nice with no errors.
