### ISSUE TITLE
[4.0] Unable to save content in admin

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15787]
### Steps to reproduce the issue

install Joomla 4
Edit a content item
Click Save 

### Expected result

Saved and return to list of articles

### Actual result

<img width="585" alt="screen shot 2017-05-03 at 14 42 04" src="https://cloud.githubusercontent.com/assets/400092/25663162/d91ee870-300e-11e7-9af5-f8fe9adae1e6.png">

**Comment by joomdonation** [comment]
It is just a small error. Look like it happens when staging is merged back to 4.0-dev. Should be fixed by PR https://github.com/joomla/joomla-cms/pull/15790

**Comment by PhilETaylor** [comment]
> It is just a small error.

One that doesnt allow any article to be saved - a big error :-)

**Comment by joomdonation** [comment]
Guess I should say small error with the code :D
