### ISSUE TITLE
[4.0] wrapping of alias in content lists

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15782]
### Steps to reproduce the issue

install joomla 4 - view list of content in admin 

### Expected result

If the alias is gonna prety much always wrap then why not start it on the new line anyway and then all rows will be of equal height instead of different heights. 

### Actual result

<img width="637" alt="screen shot 2017-05-03 at 13 59 50" src="https://cloud.githubusercontent.com/assets/400092/25661520/e41994ec-3008-11e7-8160-ddf27bda48d2.png">

**Comment by brianteeman** [comment]
as you can see in your screenshot it doesnt always wrap ;)

**Comment by PhilETaylor** [comment]
having rows that are uneven in height is a nightmare for the eyes.

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/15800
