### ISSUE TITLE
[4.0] Selecting a User in modal doesnt work

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15783]
### Steps to reproduce the issue

install Joomla 4
Edit a content item in admin 
Click the user button next to created_by or modified_by fields 
See the modal launch 
Select a user by clicking the user's name or No User button

### Expected result

The modal closes and the field is populated

### Actual result

JS Errors in console

<img width="1296" alt="screen shot 2017-05-03 at 14 04 21" src="https://cloud.githubusercontent.com/assets/400092/25661671/708fb1b8-3009-11e7-8a8d-b76bae9090ee.png">

**Comment by joomdonation** [comment]
Look like a known issue https://github.com/joomla/joomla-cms/issues/15325
