### ISSUE TITLE
[4.0] [Security] Modules list url is available to unauthenticated users

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15785]
### Steps to reproduce the issue

Set "Statistics" module to Access = Super Admins only 

Ensure you are logged out of the frontend 

using a valid token fake url: 

http://joomla4/index.php?option=com_modules&task=module.orderPosition&ce2e136a6faaa27006c5751b9cc125f2=1

### Expected result

I should not be able to see a list of modules - I can
or 
I should only be able to see a list of modules that my current user privilege allows  - I can see modules with "Super User" only 

### Actual result

```json 
{
success: true,
message: null,
messages: null,
data: [
",1,1. Archived Articles",
",2,2. Latest News",
",3,3. Articles Most Read",
",4,4. Feed Display",
",5,5. News Flash",
",6,6. Random Image",
",7,7. Articles Related Items",
",8,8. Statistics",
",9,9. Users Latest",
",10,10. Who&#039;s Online",
",11,11. Wrapper",
",12,12. Footer",
",13,13. Menu Example",
",14,14. Custom",
",15,15. Breadcrumbs",
",16,16. Banners",
",17,17. Articles Categories",
",18,18. Articles Category",
",19,19. Popular Tags",
",20,20. Similar Tags"
]
}
```

**Comment by ghost** [comment]
@mbabker should this be added to [Projects](https://github.com/joomla/joomla-cms/projects)?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15785">issues.joomla.org/tracker/joomla-cms/15785</a>.</sub>
