### ISSUE TITLE
[4.0] "Joomla! 2.5 offers two search options"

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15788]
### Steps to reproduce the issue

Install Joomla
Go to http://joomla4/index.php/search-component which is "Search Components" in the massive menu on the right on the frontend

### Expected result

That its not talking about Joomla 2.5

### Actual result
 its talking about Joomla 2.5

<img width="646" alt="screen shot 2017-05-03 at 14 47 35" src="https://cloud.githubusercontent.com/assets/400092/25663391/75e28874-300f-11e7-8112-0e3583a03bc0.png">

**Comment by brianteeman** [comment]
known issue - all sample content needs to be rewritten.

**Comment by PhilETaylor** [comment]
Is that on a list somewhere with someone assigned to it (you ;-))
