### ISSUE TITLE
[4.0] COM_MODULES_advanced_FIELDSET_LABEL

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15781]
### Steps to reproduce the issue

Edit a module in Joomla 4

### Expected result

Translated strings

### Actual result

<img width="606" alt="screen shot 2017-05-03 at 13 56 43" src="https://cloud.githubusercontent.com/assets/400092/25661397/5d69bbde-3008-11e7-823b-cad2b9af0fab.png">

**Comment by wilsonge** [comment]
Fixed with https://github.com/joomla/joomla-cms/pull/16338
