### ISSUE TITLE
[4.0] Unable to reset username/password from admin login page

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15786]
### Steps to reproduce the issue

go to /administrator/

Click Forgot your username?
Click Forgot your password?

http://joomla4/administrator/index.php?option=com_users&view=remind
http://joomla4/administrator/index.php?option=com_users&view=reset

### Expected result

These links should go to somewhere. 

### Actual result

Links reload the administrator login page

### Additional comments

**Note that SUPER ADMINS cannot change their password using online forms, on the frontend they get told to contact another super admin or use another method - so there is probably no point in these being here after all.**

**Comment by brianteeman** [comment]
More than super admins use the admin ui  ;) 

What you are seeing is a bug/rtegression

In 3.7 the links are to the frontend (ie without /administrator/ in the url

**Comment by PhilETaylor** [comment]
Cool - still a bug then 👍 )

**Comment by C-Lodder** [comment]
Possible problem with `JRoute`? Looking at the class, there doesn't appear to be a function parameter allowing you to force the client.

**Comment by zero-24** [comment]
What about removing that links?

**Comment by C-Lodder** [comment]
@zero-24 any reason why?

**Comment by C-Lodder** [comment]
balls to it...tried to fix but beyond my PHP knowledge

**Comment by joomdonation** [comment]
@C-Lodder Don't use JRoute::_ for the links. Just use the same code as in Joomla 3.7 and it should work OK https://github.com/joomla/joomla-cms/blob/staging/administrator/modules/mod_login/tmpl/default.php#L33

**Comment by C-Lodder** [comment]
Missed that.

Anyway here's the PR: https://github.com/joomla/joomla-cms/pull/15816

**Comment by zero-24** [comment]
> any reason why?

I could ask the same question ;P Why do you think we need it there?

**Comment by C-Lodder** [comment]
Cause if the user has forgotten their username/password, they then have to navigate to the frontend. Bare in mind not all sites have a login form on the homepage of their site. 

So removing it just make life harder.

**Comment by zero-24** [comment]
Hmm. I have been a few years in the forums and i never saw the request "i 'm the site admin and i don't remember my username" the pw thing also just work for non super admins so not that better i think.

**Comment by C-Lodder** [comment]
Could be a matter of one of the admins/publishers/managers etc taking time off for a while and coming back at a much later date. Could be an extremely forgetful individual. You just never know :)

**Comment by zero-24** [comment]
This is the only argument for adding it?

**Comment by C-Lodder** [comment]
I'll reverse it and ask what your arguments for removing it are :)

**Comment by zero-24** [comment]
- there was never a request nor a need for that in the past
- it does not work for superadmins (and the most users are superadmins)
- i don't see the need for 2 extra links that are just confusing for newcomers
- if we go by your argument (long away from the webseite) the account should be deactivated and the site admin should be contacted anyway.
- if we go by your argument again we should also link the docs Artikels what is joomla and how to login to joomla
- if your site really need this just override and show it.
- please remember that the most sites just have one or two superadmins so this don't work anyway.

**Comment by C-Lodder** [comment]
> the account should be deactivated and the site admin should be contacted anyway.

**should** is correct, but it's not up to us to tell users how to manage their site or users.

I know of sites that have several standard admins and publishers, not just super admins.

At the end of the day, it's a small feature making it easier to reset a password or get a forgotten username. Not hurting anyone, nor is it a security issue.

**Comment by zero-24** [comment]
>  nor is it a security issue.

i have not wrote that ;)

**Comment by C-Lodder** [comment]
Yeah I know, just pointing it out though :)

**Comment by wilsonge** [comment]
#15816 got merged so I'm going to close this
