### ISSUE TITLE
[4.0] Validation message is incorrect

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15784]
### Steps to reproduce the issue

Create a new user with a bad email, blur 

### Expected result

"Invalid email" validation message

### Actual result

<img width="594" alt="screen shot 2017-05-03 at 14 08 19" src="https://cloud.githubusercontent.com/assets/400092/25661819/0aa9f650-300a-11e7-8b1d-35bfb10c0036.png">

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15784">issues.joomla.org/tracker/joomla-cms/15784</a>.</sub>

**Comment by ghost** [comment]
@C-Lodder can yo please have a Look?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15784">issues.joomla.org/tracker/joomla-cms/15784</a>.</sub>

**Comment by C-Lodder** [comment]
Will do when I'm back from hols

**Comment by ghost** [comment]
Reminder to @C-Lodder.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15784">issues.joomla.org/tracker/joomla-cms/15784</a>.</sub>

**Comment by C-Lodder** [comment]
No worries, havent forgotten :)

**Comment by brianteeman** [comment]
Closing for now as the message has been changed
