### ISSUE TITLE
Frontend com_config issues

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15794]
### Steps to reproduce the issue

login as super admin to frontend joomla 4

http://joomla4/index.php?option=com_config&view=modules = `Call to a member function getLabel() on null`

http://joomla4/index.php?option=com_config&view=templates = `Call to a member function getFieldsets() on null`

http://joomla4/index.php?option=com_config&view=config = `Call to a member function getFieldset() on null`

E.g.

<img width="1135" alt="screen shot 2017-05-03 at 15 16 10" src="https://cloud.githubusercontent.com/assets/400092/25664741/73f6abae-3013-11e7-88d9-0add3c881f3a.png">

**Comment by joomdonation** [comment]
I don't know how com_config is used in frontend but just checked and saw that the same error happens with Joomla 3.7, so this is not really an issue with Joomla 4

**Comment by PhilETaylor** [comment]
removed 4.0 flag

**Comment by brianteeman** [comment]
its true that you get an error if you go to the reported urls but i dont see where you can generate those urls except by typing them directly<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15794">issues.joomla.org/tracker/joomla-cms/15794</a>.</sub>

**Comment by PhilETaylor** [comment]
And there lies in the bug, hackers don't care if **you** cannot generate urls, **they** will find a way to generate urls manually, and test that the result in output has some juicy information - these urls luckily generate error messages, instead of disclosing information 

NO url I can craft to your site should return a PHP fatal error, information disclosure or the like, this should be correctly handled.

**Comment by brianteeman** [comment]
as they correctly disclose error messages and do not disclose information what is the problem

**Comment by PhilETaylor** [comment]
They do not "correctly" disclose error messages - that is the whole point. They disclose PHP errors, not correctly handled errors and exceptions.

**Comment by Quy** [comment]
This is a v3 issue and not v4. Removed [4.0] from title.

@brianteeman Please change label to `J3 Issue`. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15794">issues.joomla.org/tracker/joomla-cms/15794</a>.</sub>
