### ISSUE TITLE
[4.0] JLIB_FORM_VALUE_SESSION_Redis untranslated

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15791]
### Steps to reproduce the issue

Edit global config in 4.0 
<img width="619" alt="screen shot 2017-05-03 at 14 57 38" src="https://cloud.githubusercontent.com/assets/400092/25663916/eb8f147e-3010-11e7-9087-09ffa79f272b.png">

**Comment by mbabker** [comment]
Fixed in https://github.com/joomla/joomla-cms/commit/8e64b2305e088f88d25e1cab55e34692914a2e3c
