### ISSUE TITLE
[4.0] Media Manager folder list is vertical and not in rows

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15797]
### Steps to reproduce the issue

Launch the Media Manager from the Image modal popup 

### Expected result

The folders be in rows and columns 

### Actual result

<img width="230" alt="screen shot 2017-05-03 at 15 29 15" src="https://cloud.githubusercontent.com/assets/400092/25665359/47fde4a2-3015-11e7-9c92-0e0ea4548769.png">

direct URL to this would be http://joomla4/administrator/index.php?option=com_media&view=imagesList&tmpl=component&folder=&asset=89&author=187 but its embedded in http://joomla4/administrator/index.php?option=com_media&view=images&tmpl=component&e_name=jform_articletext&asset=89&author=187

<img width="1153" alt="screen shot 2017-05-03 at 15 29 52" src="https://cloud.githubusercontent.com/assets/400092/25665408/5f5f54be-3015-11e7-98f7-3b06de23a8e8.png">

**Comment by joomdonation** [comment]
I think you should stop testing media manager as it is currently re-written in separate repo for Joomla 4 https://github.com/joomla-projects/media-manager-improvement

**Comment by PhilETaylor** [comment]
Im just going through my checklist, one extension/url/securityissue at a time :)

**Comment by joomdonation** [comment]
Just want to save you some time :)

**Comment by PhilETaylor** [comment]
5 mins in that repo and already I can see that its no where near ready for testing and no where near feature ready :(
