### ISSUE TITLE
[4.0] Enable Caching, Hit counter doesnt increment

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15792]
### Steps to reproduce the issue

Enable caching in Joomla 4.0 
Progressive and Platform specific on
Cache handler = file
reload a content item on the frontpage 

### Expected result

Hit counter increments, while still allowing the page to be cached.

### Actual result

Hit counter doesn't increment on the page - BUT IT DOES increment in the database meaning once the cache is cleared, or expires the page updates

**Comment by mbabker** [comment]
If the counters are incrementing in the database then what's the issue?  Aside from showing an outdated number based on when the cache snapshot was created.

If the counter had to update correctly on each load, that would basically invalidate caching.  Only possible ways around that are partial caching or using a plugin event to put in the right number, still requiring an extra database query.

**Comment by mbabker** [comment]
Also, how many of these issues you've reported are unique to 4.0?  Because surely this doesn't seem like something that's different from current 3.7 behaviors.

**Comment by PhilETaylor** [comment]
> Also, how many of these issues you've reported are unique to 4.0? 

Im only testing 4.0

It would be interesting to see what performance gain is being got by showing outdated information but still doing a sql update... 

If this is the way its meant to be then I guess thats ok..

**Comment by mbabker** [comment]
> It would be interesting to see what performance gain is being got by showing outdated information but still doing a sql update...

Well, for this part at least the component view isn't being triggered, a cache file is being read.  So the view isn't having to load the model, issue the database query(ies), trigger plugin events, or render the layout.  So, seems like a fair trade off to me.

**Comment by PhilETaylor** [comment]
Cool.
