### ISSUE TITLE
Can't see categories after 3.7 upgrade joomla

### ISSUE THREAD

**Issue by jpateusa** [joomla/joomla-cms#15799]
Add a new or edit an existing article. Try to select category. I would expect to see a list of published categories but nothing happens. Blank list. I checked permissions of files and all are ok. 
I am using Joomla 3.7 PHP 7 Ubuntu 16.04
I can roll back to 3.6.5 and all works ok.

**Comment by csthomas** [comment]
I may be related to https://github.com/joomla/joomla-cms/issues/15795 or https://github.com/joomla/joomla-cms/issues/15749

**Comment by csthomas** [comment]
This may help https://github.com/joomla/joomla-cms/pull/15806

**Comment by jpateusa** [comment]
csthomas I tried your posted update queries and it did not solve the issue for categories. Can you tell me which files are associated with filling that select box?

**Comment by csthomas** [comment]
At first, do you have any categories (backend) in category list?
If you do not see any, please change filter list to show all (with trashed).

If you have all categories trashed then my PR should resolve your problem, but...

1. This queries should to be run before you update to J3.7 - this queries repair published state before joomla run own queries from J3.7 update files.

2. If you run this queries on updated J3.7 then it should be ok but you have to now publish every category manually.

**Comment by jpateusa** [comment]
First, thanks for the assistance. I do see categories in the list and I have emptied the trash. I ran the queries and they executed properly. I then updated to 3.7. Same issue. No categories listed.

**Comment by jpateusa** [comment]
As a note, If I change a category's access to public it shows up in the list of categories in the article. If I change back to another access level it no longer shows up.

**Comment by eorisis** [comment]
Sounds like messed Joomla ACL. I would just try to re-save my user account just in case this fixes it if lucky, if not, create another new super user and login with that one see if things are different.

**Comment by jpateusa** [comment]
First, thanks eorisis. I tried modifying the superuser account and saving it. No change. I then added a new superuser. No change. I added the old and new superuser to all access levels / groups. Then, the articles show up. Any way to correct this where it works as it is supposed to?

**Comment by jpateusa** [comment]
So, I did a completely new Joomla 3.7 install and created various access levels and groups which super user was not checked. Then, I created some categories where access was in some of the new access levels I created. Next I tried to select one of the new categories as the parent of another category. It does not show up in 3.7 but does in 3.6.5. I then changed the access to super users and it shows up for selection. Is this a new feature of 3.7 or a bug? Looks to be a bug as it would break many installations

**Comment by ramblerswebs** [comment]
This seems to be a 3.7 issue. IT ALSO affects Contacts as well as Articles.
If I had Contacts and their Categories all as Guest it did not list them when editing the contact.
I had to change them all to Public.

**Comment by jpateusa** [comment]
Anyone have updates on this issue? Will 3.7.1 correct this?

**Comment by stevlam** [comment]
also have the issue in 3.7.0 in the category selector box.
I think is this line https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_categories/models/fields/categoryedit.php#L189 that causes the issue.
when i deleted that line it worked like it worked in 3.6.5.

maybe that line needs to be inside a if (!$user->authorise('core.admin')) to allow super users to view all.

**Comment by brianteeman** [comment]
Closing as I believe this was resolved with #16411. If that is not the case it can always be reopened
