### ISSUE TITLE
Update to 3.7.0 - Error "Call to a member function get() on a non-object in xxxxpublic_html/libraries/joomla/session/handler/joomla.php on line 71" thrown

### ISSUE THREAD

**Issue by hetclub** [joomla/joomla-cms#15798]
### Steps to reproduce the issue
A cron job runs every hour and is reporting this issue:

"Fatal error: Call to a member function get() on a non-object in <redacted>public_html/libraries/joomla/session/handler/joomla.php on line 71"

The job is being run using these commands:

"administrator/components/com_civicrm/civicrm/bin/cli.php"

### System information (as much as possible)
System Information
Setting 	Value
 
PHP Built On 	Linux het.hetclub.org 2.6.32-042stab117.16 #1 SMP Fri Sep 9 21:57:19 MSK 2016 x86_64
Database Version 	5.6.35
Database Collation 	utf8_unicode_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.6.24
Web Server 	Apache/2.4.25 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
WebServer to PHP Interface 	fpm-fcgi
Joomla! Version 	Joomla! 3.7.0 Stable [ Amani ] 25-April-2017 15:36 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0

**Comment by mbabker** [comment]
Already fixed, see https://github.com/joomla/joomla-cms/pull/15605 which will be in 3.7.1
