### ISSUE TITLE
Com_content in category blog view always shows "introtext" even if "hide" is selected

### ISSUE THREAD

**Issue by jbkhellas** [joomla/joomla-cms#15807]
### Steps to reproduce the issue
Create a category and articles with text
Create Menu Item with Category->Blog 
and select Show Introtext = hide

### Expected result
The items in category listing do not display any text

### Actual result
Text is visible

### System information (as much as possible)
Joomla v3.7

**Comment by brianteeman** [comment]
the option hide introtext refers to hiding the introtext AFTER you have clicked on the readmore.

JGLOBAL_SHOW_INTRO_DESC="If set to Show, the Intro Text of the article will show when you drill down to the article. If set to Hide, only the part of the article after the &quot;Read More&quot; break will show."

**Comment by jbkhellas** [comment]
That was fast!

Ok, I see my mistake and you are obviously right.

But is there no way to not display any text on category blog? Like only title and image?

**Comment by brianteeman** [comment]
Two options
1. Create a template override
or
2. Dont put any text before the readmore break

I am closing this as its not a core issue - for further help please use https://forum.joomla.org

**Comment by jbkhellas** [comment]
Yes sure, sorry to bother!
