### ISSUE TITLE
[com_fields] error on custom fields type list with char and accent

### ISSUE THREAD

**Issue by ymages** [joomla/joomla-cms#15815]
Joomla 3.7

impossible to write a word like Zahnärztin in the Text  field for a custom field type list, I must write Zahnaerztin that it works but it is necessary to get Zahnärztin written on front-end

Warning: SimpleXMLElement::__construct(): Entity: line 2: parser error : Entity 'auml' not defined in /libraries/joomla/form/form.php on line 728

Warning: SimpleXMLElement::__construct(): ZahnarztZahnä in /libraries/joomla/form/form.php on line 728

Warning: SimpleXMLElement::__construct(): ^ in /libraries/joomla/form/form.php on line 728

**Comment by Quy** [comment]
There is a pr #15294 to fix this. Please test with these changes:
https://github.com/joomla/joomla-cms/pull/15294/commits/99e4a645cefcfc0a50051524030d83b5c817cca0

@rdeutz @zero-24 Please merge it for 3.7.1. Thanks.

**Comment by franz-wohlkoenig** [comment]
closed as having PR #15294<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15815">issues.joomla.org/tracker/joomla-cms/15815</a>.</sub>
