### ISSUE TITLE
Administrator backend does not allow the Redis Server Port to be 0

### ISSUE THREAD

**Issue by steelAXIS** [joomla/joomla-cms#15822]
### Steps to reproduce the issue
Log into the administrator backend
go to Global Configuration / System
In Cache Settings 

set Redis Server Host to  /var/run/redis/redis.sock
set Redis Server Port to 0
set Redis xxxxx to match your redis server

### Expected result
Accept the port number 0
Save the configuration.
Print the Message 
Configuration successfully saved.

### Actual result
Error
Invalid field: Redis Server Port

The configuration System cannot be saved and joomla cannot connect to the redis server via socket.

### System information (as much as possible)
FreeBSD 11.0-RELEASE-p9
Apache/2.4.25
PHP 7.1.4 fpm-cgi
MySQL 5.7.18-log
Joomla! 3.7.0 Stable

### Additional comments
The administrator backend refuse to validate Redis Server Port to 0 or -1 but it looks like this is needed for joomla to connect to a redis server socket.
So I did hardcode the redis port to 0 in libraries/joomla/cache/storage/redis.php
```
 $server = array(
            'host' => $app->get('redis_server_host', 'localhost'),
            //'port' => $app->get('redis_server_port', 6379),
            'port' => 0,
            'auth' => $app->get('redis_server_auth', null),
            'db'   => (int) $app->get('redis_server_db', null),
        );
```
and now joomla is able to connect to redis socket and I am able to save the change made in the Global Configuration.

**Comment by PhilETaylor** [comment]
> set Redis Server Port to 0

Why would ever want to do this!??!?

The docs state:

```
# Accept connections on the specified port, default is 6379 (IANA #815344).
# If port 0 is specified Redis will not listen on a TCP socket.
```

Therefore if your set your Redis with port 0 then Joomla would not be able to connect to it anyway as it would not be listening on a TCP Socket...

**Comment by PhilETaylor** [comment]
Ah I see this now:

> set Redis Server Host to /var/run/redis/redis.sock

one moment...

**Comment by PhilETaylor** [comment]
Please test PR #15836

**Comment by brianteeman** [comment]
Closed as we have a PR for testing
