### ISSUE TITLE
Massive loading times after update to 3.7?

### ISSUE THREAD

**Issue by ChristianGrieger** [joomla/joomla-cms#15820]
Hey there,

i updated two pages now to joomla 3.7 and notices that both of them got a high loading time up to 8 seconds to get the page loaded. Does anyone else have that problem?

**Comment by laoneo** [comment]
Can you enable the debug plugin? Is there something shown which takes a lot of time?

**Comment by ChristianGrieger** [comment]
I enabled the caching option and gzip and it looks like the loading time is stable now. Debug log did not show anything importent.

**Comment by laoneo** [comment]
Good to hear.

**Comment by ChristianGrieger** [comment]
I am sorry i have to reopen this thread. I first was thinking its loading better but looks like its not gone.
So the confusing stuff is that Phil from myJoomla tested the loading of the page and for him there was no problem with the loading time. From my mobile phone its running with good loading times just from my home connection its that slow. I also tested with a friends network and there i have the same problem. I am using cloud flare for the page so loading time should be no problem at all. 

The cache plugin is disabled already and the file replaced because the known cache problem of 3.7.

@laoneo what exactly do you need from the debug log to see if there is a problem?

**Comment by ssnobben** [comment]
Have you tried to uninstall JCH Optimze other system plgs and see the results? 

Pls check with JCH Optimize to send in a support ticket to them or post in their forum about problem if you have these Joomla 3pds performance plgs and components.

**Comment by ChristianGrieger** [comment]
I installed JCH after the problem to check if it can solve the problem.

**Comment by ssnobben** [comment]
Have you tried to make a fresh Joomla install on that hosting environment and see if that have the same problem?

**Comment by ChristianGrieger** [comment]
With a fresh install it was working well.

After hours of searching the problem i disabled cloudflare for the subdomain where the problem is located and the page is loading fast again. Looks like i have to contact cloudflare so they can tell me why this problem happens.

**Comment by ssnobben** [comment]
Did you flush Cloudflare cache "everything" for your domain there also?

**Comment by ChristianGrieger** [comment]
Yes many times before on joomla and cloudflare. I now ended up with disabled cloudflare and because of the try to optimize the page for hours now its much better as before. Without the error i never had optimized it that much 😉 . So hope to get a reply from cloudflare soon because i still would like to use it.

**Comment by brianteeman** [comment]
cloudflare is very hard to get working on a subdomain

**Comment by ChristianGrieger** [comment]
@brianteeman good to know... I never noticed that but i must say that i never used cloudflare on a subdomain to develop a page. Good that i switch the page to the normal domain as soon as its done.

**Comment by ChristianGrieger** [comment]
Just to show the difference without cloudflare enabled xD:

Cloudflare: (Check loading time on bottom) 

![3d0cbd64-325b-11e7-9df8-71214166cad8](https://cloud.githubusercontent.com/assets/8712219/25773219/415d96c6-327a-11e7-8a9e-203e2ad5d404.png)

Without Cloudflare: (Check loading time on bottom) 

![bildschirmfoto 2017-05-06 um 16 36 48](https://cloud.githubusercontent.com/assets/8712219/25773224/5f5584f4-327a-11e7-908b-818e0ba0ea81.png)

**Comment by ale910109** [comment]
Try to disable Mootools.
