### ISSUE TITLE
Warning You do not have access to the Administrator section of this site.

### ISSUE THREAD

**Issue by evowebmaster** [joomla/joomla-cms#15829]
### Steps to reproduce the issue

Since upgrading to Joomla 3.7, I receive the following error when logging in as administrator;

Warning
You do not have access to the Administrator section of this site.

I have followed multiple ways to fix this issue, however none of them work.

Could this be an issue with 3.7 that differs from earlier versions?

**Comment by PhilETaylor** [comment]
This is the first report of this with literally 10000s of Joomla sites already upgraded. 

I'll say this is more a support request than an issue with Joomla. 

You might be best seeking support on the Joomla Forums.
