### ISSUE TITLE
SimplePie v1.5 + autoload

### ISSUE THREAD

**Issue by zstergios** [joomla/joomla-cms#15838]
### Steps to reproduce the issue
libraries\vendor\simplepie\simplepie\library
Version is outofdate. Newer versions all compatible with PHP7 and provide many fixes

### Expected result
Version 1.5
https://github.com/simplepie/simplepie/releases/tag/1.5

### Actual result
Version 1.3.1

### System information (as much as possible)
Joomla 3.7
PHP 7

### Additional comments
I suggest to update the package with latest simplepie version.
Also I suggest to make it package/library extension to able to auto-update each time is required or to include it only on pages that requires that

**Comment by zstergios** [comment]
Also seems simplePie library is auto loaded, should not be happened 
`if(defined('SIMPLEPIE_VERSION')) echo "SIMPLEPIE IS AUTO-LOADED";`

**Comment by brianteeman** [comment]
See the component from @wilsonge here https://github.com/joomla/joomla-cms/issues/10835#issuecomment-235913948 I dont know if he ever did check it

**Comment by zstergios** [comment]
Sorry for that! I searched before on https://issues.joomla.org.

**Comment by mbabker** [comment]
> Also seems simplePie library is auto loaded.

Everything in `libraries/vendor` is hooked up to Composer's autoloader, which depending on the package configuration will either manually load files when that's included or register mapping definitions so that classes can be loaded.  Just because something's registered into the autoloader doesn't mean the entire package is actually loaded into memory.

**Comment by zstergios** [comment]
Thanks!

**Comment by brianteeman** [comment]
i am reopening this as its still a valid question for @wilsonge if simplepie can be updated or not

**Comment by wilsonge** [comment]
I haven't had time to look into it. We have no examples in core, and I just don't have time to do a full code review inspection at the moment :/

For what little it's worth Wordpress haven't decided to go beyond 1.3.1 (their corresponding tracker has been open https://core.trac.wordpress.org/ticket/36669)

Honestly I'd just update it through composer and try it. Worst case is in a subsequent patch we may have to revert back

**Comment by zstergios** [comment]
Ι'm the developer of "Ultimate Feed Display", I have replaced the folder 
libraries\vendor\simplepie\simplepie\library with the new folder of version 1.5

I made some tests (through my mod) and I did not faced any crash or misbehavior. 
I don't know how to test it further but seems OK to me.

**Comment by brianteeman** [comment]
OK well please submit a PR to update the library

You should be aware that this library is not included in Joomla 4
