### ISSUE TITLE
[com_fields] order article list or blog by custom calendar field

### ISSUE THREAD

**Issue by dietze6** [joomla/joomla-cms#15835]
### Steps to reproduce the issue
- just not possible today

### Expected result
- if custom field is calendar field this should be used as order field for blog list

### Actual result
- custom caldendarf field not availiable to select from menu

### System information (as much as possible)
- Joomla 3.7.0

### Additional comments
- other solution could be to add "unpublish" oder "publish_down" as order-field

**Comment by Bakual** [comment]
custom fields can't be used to order or filter lists. If you need that, you have to use a full CCK.

**Comment by dietze6** [comment]
maybe it is possible to implement this to `root/components/com_content/category/blog.xml` around line 270 ?

    <field
    	name="order_date"
    	type="list"
    	description="JGLOBAL_ORDERING_DATE_DESC"
    	label="JGLOBAL_ORDERING_DATE_LABEL"
    >
    	<option value="">JGLOBAL_USE_GLOBAL</option>
    	<option value="created">JGLOBAL_CREATED</option>
    	<option value="modified">JGLOBAL_MODIFIED</option>
    	<option value="published">JPUBLISHED</option>
    	<option value="unpublished">JUNPUBLISHED</option>
    </field>
and then add in `root/components/com_content/helpers/query.php` around line 170 this

    case 'unpublished' :
    	$queryDate = ' CASE WHEN a.publish_down = ' . $db->quote($db->getNullDate()) . ' THEN a.created ELSE a.publish_down END ';
    	break;
i think in J3.5 this used to work now it doesnt anymore

Maybe i am wrong posting this here?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15835">issues.joomla.org/tracker/joomla-cms/15835</a>.</sub>

**Comment by brianteeman** [comment]
@dietze6 your code above is nothing to do with a custom calendar field.

**Comment by Bakual** [comment]
@brianteeman It's what he wrote under "Additional comments".

@dietze6 It's probably better to open a new issue for that request since you asked two different things in this issue.

**Comment by brianteeman** [comment]
I am closing this as the main issue has been answered by @Bakual and you should open a new issue for the second request
