### ISSUE TITLE
[j4.0] element-invisible

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#15832]
The class element-invisible can now be removed and replaced with sr-only

element-invisible was added to joomla3 css because bootstrap 2 didnt have a class for this but we now have sr-only which is identical but it native bs4 markup

I thought of doing a quick search replace BUT then i saw that lots of the JS will need updating as well as it manipulates the element-invisible class and I dont want to touch JS myself. 

So this Issue is a TODO item

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/15837

**Comment by brianteeman** [comment]
Cloaed
