### ISSUE TITLE
[com_fields] custom fields should be multilangual

### ISSUE THREAD

**Issue by dietze6** [joomla/joomla-cms#15834]
### Steps to reproduce the issue
- a created custom field can be shown in frontend and/or backend but has just one lable

### Expected result
- custom fields should have a language, just like articles, and should be linked to each other

### Actual result
- custom field have no language assignment

### System information (as much as possible)
- Joomla 3.7.0

### Additional comments
- please see also my issue about custom calendar fields and menu order

**Comment by Bakual** [comment]
Custom fields **have** already a language. I'm not sure what good linking (association) should do.

But then, if I understand you correctly, you just want the label translated, right? You can do that easily by creating a custom language key in the language override manager and put the key into the label field. The label is translated.

**Comment by dietze6** [comment]
Aah, my bad. I was looking for something simmilar to connecting articles with the "Associations"-Tab; as it is, it works fine for me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15834">issues.joomla.org/tracker/joomla-cms/15834</a>.</sub>

**Comment by brianteeman** [comment]
Closed
