### ISSUE TITLE
No Code Attached Yet

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15844]
EVERY Issue in Github is now being marked as "No Code Attached Yet"

Is this expected? 

@mbabker ?

**Comment by brianteeman** [comment]
Yes and it has been for a very long time - perhaps 2 years

**Comment by PhilETaylor** [comment]
What is the point of it though if its on every single issue... can it not just be turned off in the bot?

**Comment by mbabker** [comment]
The label has been there for ages.  The automation was at request in https://github.com/joomla/jissues/issues/590

**Comment by brianteeman** [comment]
Now I remember why ;)

**Comment by PhilETaylor** [comment]
So basically its a way for issues.joomla.org to distinguish between an ISSUE and a PR ? Surely there is a better way than blindly attaching a label on EVERY Issue?

**Comment by mbabker** [comment]
Probably.  Our `#__issues` table has a `has_code` column.  Feature suggestions and PRs are welcome 😉

**Comment by brianteeman** [comment]
Closing as the question has been answered

**Comment by PhilETaylor** [comment]
So its expected, but a complete waste of space for those of us that purely use GH....

**Comment by mbabker** [comment]
I've been saying for years the UX isn't exactly the greatest over there, and it affects here too; that's what happens when you have 4 PHP developers making UX/UI decisions.

**Comment by PhilETaylor** [comment]
I see Joomla is advertising for UX Team leader and Assistant Team Leader (again) 🤡
