### ISSUE TITLE
"Custom" Module - tab Advanced - cannot change Module Tag - always "div"

### ISSUE THREAD

**Issue by joo7** [joomla/joomla-cms#15859]
### Steps to reproduce the issue
Create a "Custom" module, on tab "Advanced" set "Module Tag" to "article" or else... save

### Expected result
ok (tag is "article")

### Actual result
not ok (tag is always "div", no matter what is selected)

### System information (as much as possible)
tested local and on demo-site

### Additional comments
Feature request: Sometimes it would be great to select "none" 
(to insert scribts on special sites...)

**Comment by brianteeman** [comment]
This will be dependant on the module chrome being used for the relevant position in your template. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15859">issues.joomla.org/tracker/joomla-cms/15859</a>.</sub>

**Comment by joo7** [comment]
tested on demo-site (protostar) position-1

local position in index.php: <jdoc:include type="modules" name="script" style="none" />

**Comment by brianteeman** [comment]
As is said it is dependant on the module chrome. In your test you are using "none" and if you look at the code you will see that means the tag is not being used (as you have discovered ) https://github.com/joomla/joomla-cms/blob/staging/templates/system/html/modules.php

**Comment by joo7** [comment]
in modules.php comment on line 13: none (output raw module content)
but output is with div-tags:

<div>
module content
</div>

no surrounding div-tags should be created, right? Should be raw?

**Comment by joo7** [comment]
sorry, forgot github-code-tags...
output is with div-tags:

`<div>`
module content
`</div>`

**Comment by brianteeman** [comment]
That is because the div is coming from the module itself.

This really should be discussed on the forum as its not a bug
