### ISSUE TITLE
Written by Author link error if no contact is present for this Author

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-cms#15852]
### Steps to reproduce the issue
Enable in Articles: Options -->  Link Author  -->  yes
Create the contact for the admin,
create a new user Author and not create the contact for it.
Create a new Featured menu item and some Featured article by the admin and by the Author.

### Expected result
Better no link if no contact for the Author

### Actual result
The link for the admin user is ok but the link in the Author is wrong: index.php/component/contact/contact/-?Itemid=101
Error 404

### System information (as much as possible)

Joomla 3.7.1dev

**Comment by infograf768** [comment]
I confirm

**Comment by rdeutz** [comment]
closing fix in #15874 and merged
