### ISSUE TITLE
Readmore button fails Tinymce

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#15862]
### Steps to reproduce the issue
    Create new Menu Item
    Choose "Single Article" type
    Click "Create" button for article
    Click "Read More" button

### Expected result
Readmore gets inserted

### Actual result
Readmore is not inserted

### Additional comments

https://forum.joomla.org/viewtopic.php?f=706&t=950200

**Comment by franz-wohlkoenig** [comment]
Issue confirmed, Error in Console:
![bildschirmfoto 2017-05-07 um 06 17 50](https://cloud.githubusercontent.com/assets/8235763/25777885/fc0ecf4a-32ec-11e7-8617-6cd82b06cba6.JPG)

**Comment by infograf768** [comment]
@dgt41 
Looks like it comes from https://github.com/joomla/joomla-cms/pull/15357

**Comment by infograf768** [comment]
`Options is undefined` and it is not limited to TinyMCE. Modifying title to fit.

**Comment by Webdongle** [comment]
@infograf768 

Thanks

**Comment by franz-wohlkoenig** [comment]
closed as having PR #15869<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15862">issues.joomla.org/tracker/joomla-cms/15862</a>.</sub>
