### ISSUE TITLE
Invalid security token after update from joomla 3.6.5 to joomla 3.7.0 & PHP 7.0

### ISSUE THREAD

**Issue by pintobuck** [joomla/joomla-cms#15871]
### Steps to reproduce the issue
Tried to login into Joomla backend as administrator. Got message: "The most recent request was denied because it contained an invalid security token. Please refresh the page and try again" 
Now locked out of Joomla.

### Expected result
Able to login to Joomla administrator as normal.

### Actual result
Locked out of Joomla

### System information (as much as possible)
Joomla 3.7.0., PHP 7.0
Website running on a large hosting service.
Server version: 5.5.35-MariaDB-1~squeeze
Protocol version: 10
MySQL charset:  UTF-8 Unicode (utf8)  
Web server
Apache
MySQL client version: 5.5.35-MariaDB
PHP extension: mysqli

### Additional comments 
Used phpmyadmin, tbl_extenstions, plg_system_cache and set enable = 0 to disable Joomla plg_system_cache.
Then I could login again as Joomla Administrator. No invalid security token message.
This work-around was found in https://github.com/joomla/joomla-cms/issues/9568

**Comment by pintobuck** [comment]
Joomla Forum discussion https://forum.joomla.org/viewtopic.php?f=710&t=930748

**Comment by brianteeman** [comment]
The problem is with the system cache plugin and this fix has already been merged for inclusion in 3.7.1

**Comment by Chacapamac** [comment]
I don’t think “flush cache on update” is a solution as this happen on all forms submit on Joomla 3.7.2 - PHP 7.1— Cause by Cache plugin — Turning it off stop the error (On 2 sites) — Also I got Regular Labs Cache Cleaner that do clear cache on any update in the sites.
It’s evident that you can’t have non-working Contacts Forms until an update is done on the site. Contact forms Have to work 100% of the time.

**Comment by TiQ79** [comment]
We have this issue again updating from 3.7.4 to 3.8.3. We tried a lot of times to update to earlier 3.8.x versions, but non worked. So it's still an issue.

**Comment by ghost** [comment]
@TiQ79 can you please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). There it get more Notice than here a Comment on a closed Issue.
