### ISSUE TITLE
Saving "Date of birth" in user profile produces error "date of birth" not valid date.

### ISSUE THREAD

**Issue by seagul30** [joomla/joomla-cms#15882]
### Steps to reproduce the issue
Activate plugin "User - Profile"
Open an existing user (also with new users)
Add a "Date of birth" with date picker --> value will be i.e. 2017-05-10 (English) or i.e. 10.05.2017 (German)
Save User

### Expected result
Successfully save User with Date of Birth

### Actual result
Error: "Save failed with the following error: The date of birth you entered is invalid. Please enter a valid date."

### System information (as much as possible)
Joomla 3.7.0
PHP 5.6.21 or 7.0.14 (tested on both)
DB Version 5.5.5-10.1.13-MariaDB  or 5.5.52-nmm1-log

### Additional comments
Tested with new and existing users in Frontend and Backend
Always same error.

**Comment by seagul30** [comment]
Actually, it is a language string error.
Saving throws an error, if the date is greater than today, but the error message does only tell invalid date. I will try to fix.

**Comment by zero-24** [comment]
Closing as there is a PR thanks! #15883
