### ISSUE TITLE
Tooltip BS and JQ Conflicts

### ISSUE THREAD

**Issue by Yves-K** [joomla/joomla-cms#15896]
### Steps to reproduce the issue
Use JQuery UI tooltip (for instance in article or menu admin)
**Yes, It is possible to use JQTooltip in the same DOM as a BSTooltip using the bridge functionality from JQ !**
`jQuery.widget.bridge('jqTooltip', jQuery.ui.tooltip);`

But media/media/js/mediafield.js on line 139 attempts to **destroy** all existing tooltips (BS ones).
And this happens before one can set a bridge. So we get the error :

> Uncaught Error: cannot call methods on tooltip prior to initialization; attempted to call method 'destroy'

### Expected result
This conflict should not create an error

### Actual result
This conflict creates an error and locks JavaScript !

### System information (as much as possible)
Joomla! 3.7...

### Additional comments
Before invoking  the destroy method code should ensure the object is a tooltip
or, at least use a **try and catch** the error in order to let the page scripts go on
For instance
```
try{
     this.$input.tooltip('destroy');
} catch(err){
     // do we have to do something with this error ?
}
```

**Comment by PhilETaylor** [comment]
Please test PR #15951

**Comment by Bakual** [comment]
Closing as we have a PR
