### ISSUE TITLE
[4.0][RFC] Support for module badges

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#15895]
I have a working concept for this but won't polish it and submit a PR until I know people's thought.

This is basically a proposal for a small feature that allows users to add badges to modules.

To add a badge, you would simply have to add something like the following in the Module Class Suffix input:

```
badge-success[Text Here]
```

This would result in the following:

![untitled](https://cloud.githubusercontent.com/assets/2019801/25811907/9aded780-340c-11e7-890d-56fa4f2a25d1.png)

The badges you currently see in the bottom modules are hardcoded HTML in the custom module editor, so this feature would allow you to add badges to ANY module.

Thoughts

**Comment by dgt41** [comment]
We **really** need an override creator that's tightly connected to the CSS framework. Hardcoding is not an option.
My 2c

**Comment by C-Lodder** [comment]
Well as Aurora is based on BS4, this would be couple to BS4. If other template providers wish to use the same code in their own modChrome's, they can change the `badge` class to whatever matches their framework

**Comment by brianteeman** [comment]
Not sure we need this in core.

Can it not be achieved with existing module classes

**Comment by C-Lodder** [comment]
@brianteeman - Can only be achieved if you create a custom module and hardcode the HTML in the editor

**Comment by brianteeman** [comment]
That sounds odd as I used to do something similar years ago. 

Even so I don't really see the use case myself

**Comment by C-Lodder** [comment]
yeah, I think it was on the old Yootheme templates that I used to use them.

**Comment by brianteeman** [comment]
In my case I did it myself as I have never used a template club

**Comment by Bakual** [comment]
I don't think this needs to be in core.
It's easy to do with custom CSS if someone needs it for their use case.
