### ISSUE TITLE
[com_fields] Checkboxes field type with £ (pound) sign in Values Name not working properly  

### ISSUE THREAD

**Issue by zsoltiii** [joomla/joomla-cms#15898]
### Steps to reproduce the issue
Backend: 

1. Go to Content->Fields and create a field with type: Checkboxes.
2. Assign it to a Field Group and a Category. 
3. Among Checkbox Values, add Name: '£30,000+', Value: '20000'
4. Publish field.
5. Go to Content->Articles and create an article and choose the same Category that the Field is assigned to.

### Expected result

On Article edit page the Field Group tab should come up with the Field inside that we set up above. 

### Actual result

On Article edit page the Field Group tab is not showing.

If at this stage you go and remove the £ (pound) sign from the Checkbox Values Name field then go back to the article, the Field Group tab shows correctly. 

### System information (as much as possible)

Database Version	5.7.14
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.25
Web Server	Apache/2.4.23 (Win64) PHP/5.6.25
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.7.0 Stable [ Amani ] 25-April-2017 15:36 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36

**Comment by Quy** [comment]
This will be fixed in v3.7.1. https://github.com/joomla/joomla-cms/commit/b3ca55f634526f40288b5c611175d88c27a84677

**Comment by zsoltiii** [comment]
Yes, @Quy you are absolutely right, I've used that patch you mentioned and I can confirm that the issue is solved.
