### ISSUE TITLE
Media form field type inside subform

### ISSUE THREAD

**Issue by hfittipaldi** [joomla/joomla-cms#15897]
The media form field type inside subform is not using my default media manager (JCE)

### Steps to reproduce the issue
This is just for comparison, the first field does not exist.
`<fieldset name="basic">
                <field name="myimage"
                       type="media"
                       preview="tooltip"
                       directory=""
                       label="My image"
                       description="" />
                <field name="subform"
                       type="subform"
                       formsource="path/to/file/item.xml"
                       min="1"
                       max="10"
                       multiple="true"
                       layout="joomla.form.field.subform.repeatable"
                       groupByFieldset="true"
                       label="Subform"
                       description="Subform Field Description" />
            </fieldset>`

And item.xml:
`<fieldset name="image">
                <field name="myimage"
                       type="media"
                       preview="tooltip"
                       directory=""
                       label="My image"
                       description="" />
            </fieldset>`

### Expected result
Both fields must use the same media manager, JCE in this case.

### Actual result
The field outside subform is using jce media manager and the other uses the joomla default media manager

### System information (as much as possible)
Windows 10
localhost
apache 2.4.23
php 7.0.18
mysql 5.7.14
Joomla 3.6.5

### Additional comments
This was also tested with Joomla 3.7.0, with the same results.

**Comment by brianteeman** [comment]
Sorry to say but this is an issue for JCE to resolve

**Comment by N6REJ** [comment]
@brianteeman why would it be a jce issue when "media" is the field used in both cases?

**Comment by brianteeman** [comment]
@bear because there is no such thing in joomla as a "default media manager" and joomla provides no method to have one. jce simply intercepts the calls to the joomla media manager. So in this case JCE is not intercepting this call.
