### ISSUE TITLE
[4.0] [sidebar] Use localStorage for close/open state

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#15892]
### Steps to reproduce the issue

If you close the main sidebar then refresh the page, it expands again. We should be using `localStorage` to save the state of it.

**Comment by Bakual** [comment]
+1 for using `localStorage` or maybe even better `sessionStorage` (not sure if it should be persistent across sessions).

**Comment by dgt41** [comment]
For this one I will like to have it persistent across sessions, I'm planning to reduce the menu usage to absolute minimum (hint dashboard buttons!)

**Comment by C-Lodder** [comment]
@dgt41 - want me to submit a PR for this tomorrow?

**Comment by dgt41** [comment]
Go for it!

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/16036
