### ISSUE TITLE
[J 3.7] PHP version warning should be extended to PHP 7.0 that expires earlier than 5.6 (and/or changed to Post-Install Message)

### ISSUE THREAD

**Issue by StefanSTS** [joomla/joomla-cms#15909]
### Steps to reproduce the issue
Install Joomla under PHP 5.6 and see the quickicon message in the backend that warns about the "expiration" of PHP 5.6.

First of all:
I think this entire message should be a post-install message and not a quick icon. Users should be able to click it away without the need to disable the plugin. This "disturbing" message might make sense as a quick icon three to six month before expiration.

Second:
PHP 7.0 will not receive security fixes after (I guess it was) 3rd December 2018 which is earlier than PHP 5.6.
So the message if it is really necessary to show it more than 18 month before the actual date, should reflect that is is also the case for PHP 7.0.

Removing this as a quick icon would be my favorite solution, but that might not happen, I know.

**Comment by wojsmol** [comment]
The message for php 7.0 will begin to appear after December 3, 2017 https://github.com/joomla/joomla-cms/blob/staging/plugins/quickicon/phpversioncheck/phpversioncheck.php#L124-L127.

**Comment by Quy** [comment]
Related to #14571.

**Comment by StefanSTS** [comment]
I am closing this, since the discussion is obviously in #14571 that I didn't find before.
