### ISSUE TITLE
Remove Span Class from Extra Fields

### ISSUE THREAD

**Issue by jayblaq** [joomla/joomla-cms#15921]
### Steps to reproduce the issue
Create a new field and place it in the article such as {field 1}  

### Expected result

The field outputted with no markup

### Actual result

<span class="field-value">My Field Info</span>

### System information (as much as possible)

Joomla 3.7

### Additional comments

I understand that it has class so you can add classes and styles in the field options, but how I need to render the values with no HTML to use for a social sharing call such as:

<button class="sharer button" data-sharer='twitter' data-title='{field 13}' data-hashtags='{field 14}' data-url='{field 16}'>Share on Twitter</button>

Is there anyway currently to stop it from rendering the span class?  If not can an update be made with that option?

**Comment by jayblaq** [comment]
Hello 

I figured it out - Simple override :)  It would be nice to have a button though for add render class or no render class<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15921">issues.joomla.org/tracker/joomla-cms/15921</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Categorie "Feature Request" is added.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15921">issues.joomla.org/tracker/joomla-cms/15921</a>.</sub>

**Comment by Bakual** [comment]
As you said, just override the layout or add an alternative layout. The plugin code allows to specify another layout, eg `{field 1, nospan}` would load the layout file called `nospan.php`.
I wouldn't add a parameter for that. The span that is currently wrapped around the field doesn't hurt anyone except for some very specific usecases. On the other hand it is very helpful when you want to style the field.
So imho layouts are the perfect solution for that case.

**Comment by brianteeman** [comment]
Closed as stated above
