### ISSUE TITLE
Joomla 3.7 and CACHE plugin problem

### ISSUE THREAD

**Issue by stavroszach** [joomla/joomla-cms#15926]
### Steps to reproduce the issue
In the Administrator enable the CACHE plugin and place any page in the plugin's exclusion list. Then do a System > Clear Cache.
Try to view the page you placed in the CACHE plugin's exclusion list. The first time it may appear, but do reload (CTRL+reload) the page again. The problem appears after the creation of a page cache in Joomla, therefore it appears after the second CTRL+reload.

### Expected result
Nicely displayed page.

### Actual result
Completely blank page. Nothing appears between the opening and closing body tags.

### System information (as much as possible)
cPanel Centos 6
Apache 2.4.5
PHP 7.0
Joomla 3.7

### Additional comments
The problem goes away when either the CACHE plugin is disabled or when the pages are removed from the CHACHE plugin's exclusion list.

**Comment by brianteeman** [comment]
Closed as a duplicate report
