### ISSUE TITLE
[4.0] Error "JTableMenu::_getNode(489, ) failed" after updating component

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#15929]
### Steps to reproduce the issue
While trying to adapt my component to J4 I get a nasty error message each time I install the component again. I guess this will happen with any component that is able to be installed in J4 (and has a backend menu).

### Expected result
Update a component without any error messages

### Actual result
![error](https://cloud.githubusercontent.com/assets/1018684/25889538/5b9f2962-356a-11e7-856f-c05509a81bae.PNG)

### System information (as much as possible)
Using current J4 dev branch
Menu table before the update:
![table](https://cloud.githubusercontent.com/assets/1018684/25889628/bbc3a854-356a-11e7-8fde-8dcc0aa25238.PNG)
As you see the first row seems to be without an accompagning error messages while the others (childrens) have one.

### Additional comments
I tracked it down to `\Joomla\CMS\Table\Nested::delete()` which then calls `$node = $this->_getNode($pk);` and that one then throws the Exception because the requested row doesn't exist.

I *think* this happens because during an update the menuitems are deleted and then recreated. When the first menuitem is deleted, it also deletes its children. That part works fine. Now when the second menuitem should be deleted, the row can't be found anymore since it already has been deleted (it's a children of the first menuitem).

What I don't understand is what the difference is between J3.7 and J4 here. In J3.7.0 no error is shown. Obviously the code got namespaced but from looking over it, it looks very similar to the old code.

If it helps to reproduce the issue, I've attached my component.
[com_sermonspeaker.zip](https://github.com/joomla/joomla-cms/files/989170/com_sermonspeaker.zip)

**Comment by wilsonge** [comment]
Are menu items always deleted and recreated every update? I'm assuming going to 3.7.0 to 3.7.1-dev (i.e. staging) through Joomla Update you don't get this?

**Comment by Bakual** [comment]
> Are menu items always deleted and recreated every update? I'm assuming going to 3.7.0 to 3.7.1-dev (i.e. staging) through Joomla Update you don't get this?

It's always done during component updates, yes (at least I think so). Not during CMS update (at least I hope :smile: ).

**Comment by brianteeman** [comment]
I seem to recall a pr or comment from @rdeutz on this

**Comment by rdeutz** [comment]
@brianteeman we did something for the admin menu manager but can't remember what it was exactly. I think the reason for doing it this way was laziness. The other more complicated way would be to compare the old and the now to be created menu and update/delete/create items.

**Comment by brianteeman** [comment]
I knew I remembered something

**Comment by Bakual** [comment]
But it still doesn't explain the difference in behavior between J3.7 and J4 :smile:

**Comment by Bakual** [comment]
Closing as we have a PR https://github.com/joomla/joomla-cms/pull/16428

**Comment by edthenet** [comment]
I have the same issue when i try to install Artio Bookit Free. 
But i'm still using Joomla! 3.8.2

**Comment by ghost** [comment]
@edthenet Comments on closed Issues didn't get much Notice. Please ask help on the [forums](https://forum.joomla.org/) or Developers of 3rd-Party-Component.
