### ISSUE TITLE
Article ID - module settings

### ISSUE THREAD

**Issue by mholyjr** [joomla/joomla-cms#15934]
I created a module where you have to choose an article. When you choose one you can't change it to another because it adds class _hidden_ to "Choose article" button. 

I need to be able switch articles as I want to.

Everything works fine with J3.6.

**Comment by brianteeman** [comment]
Did you click on the clear button?

**Comment by mholyjr** [comment]
I can't see any clear button.

J3.7 - Choose button with .hidden after first selection
![j3-7](https://cloud.githubusercontent.com/assets/17010236/25899450/356506b0-3590-11e7-92ca-d16a915068c4.png)

J3.6 - Choose button is ok
![j3-6](https://cloud.githubusercontent.com/assets/17010236/25899481/53a4c55c-3590-11e7-94ff-cfd8aac757c8.png)

**Comment by infograf768** [comment]
What is the `type` of your field?
It should be `modal_article` and you should get it with
`addfieldpath="/administrator/components/com_content/models/fields"`

**Comment by mholyjr** [comment]
It is `modal_article` and there's no problem with choosing an article for the first time - everything works well. 

But after you choose your article you can't change your mind, because something adds `class="hidden"` to the button. (When I delete that class using developer tools, than it's ok)

I know I could just remove `.hidden` from the CSS file but I guess there must be a better solution.

**Comment by Quy** [comment]
@mholyjr Is this still an issue? Have you upgraded to v3.8.3?

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 28th February 2018.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15934">issues.joomla.org/tracker/joomla-cms/15934</a>.</sub>
