### ISSUE TITLE
Article order (ID) wrong on initial load

### ISSUE THREAD

**Issue by gwsdesk** [joomla/joomla-cms#15931]
When you access the article manager, the default order is shown as 'ID Descending' but the list of articles is ordered ID ascending.

If you than go to page 2 of the article list, the ordering is corrected to ID descending. 

If you go back to page one again, it will show ID descending as expected. 

Leave the article manager and return and the default order is again shown as 'ID Descending' but the list of articles is ordered ID ascending again
![screen shot 2017-05-10 at 09 54 31](https://issues.joomla.org/uploads/1/aeec11d8197198fd51388bcbf718df0d.jpg)

This has been posted multiple times on the forums as well

**Comment by franz-wohlkoenig** [comment]
closed as known Issue, fixed #15655<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15931">issues.joomla.org/tracker/joomla-cms/15931</a>.</sub>

**Comment by Webdongle** [comment]
On a fresh J3.7.0 the problem exists
but
Just installed Jstaging and the default ID descending is displaying correctly on first visit to Content >>> Articles.  
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15931">issues.joomla.org/tracker/joomla-cms/15931</a>.</sub>

**Comment by brianteeman** [comment]
yes @Webdongle because it has been fixed by #15655 as stated above

**Comment by gwsdesk** [comment]
Would be nice if the title of [#15655](https://github.com/joomla/joomla-cms/pull/15655 "#15655") would have been adjusted to represent the issue saving time. How could I have found this issue with "Fix vote ordering"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15931">issues.joomla.org/tracker/joomla-cms/15931</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@gwsdesk noticed for Future.

**Comment by Webdongle** [comment]
Yes @brianteeman but that was posted as I typed my reply so did not see that post until the screen refreshed after I posted my reply 🤕
