### ISSUE TITLE
JDate showing wrong time

### ISSUE THREAD

**Issue by alagesanbe08** [joomla/joomla-cms#15930]
### Steps to reproduce the issue

    $tz = "Asia/Kolkata";
    $date = JFactory::getDate('now',$tz);
    print_r($date);

### Expected result

      JDate Object
      (
        [tz:protected] => DateTimeZone Object
        (
            [timezone_type] => 3
            [timezone] => Asia/Kolkata
        )

    [date] => 2017-05-10 14:46:15
    [timezone_type] => 3
    [timezone] => Asia/Kolkata
    )

### Actual result
    JDate Object
    (
      [tz:protected] => DateTimeZone Object
        (
            [timezone_type] => 3
            [timezone] => Asia/Kolkata
        )

     [date] => 2017-05-10 08:46:15
     [timezone_type] => 3
     [timezone] => Asia/Kolkata
    )

### Additional comments
problem in JDate constructor

line no:114 

      $date = parent::createFromFormat('U.u', number_format(microtime(true), 6, '.', ''), $tz)->format('Y-m-d H:i:s.u');

its return wrong

**Comment by Bakual** [comment]
Can you try if https://github.com/joomla/joomla-cms/pull/15853 fixes this?

**Comment by PhilETaylor** [comment]
Cannot replicate with Joomla 3.7.1rc2 at 61b9fcc
Cannot replicate with Joomla 3.7.0 at 011a6f5cc34bcc67338db2d24828fdff5940cbb6

**Comment by Bakual** [comment]
Closing as it is presumable fixed with https://github.com/joomla/joomla-cms/pull/15853
