### ISSUE TITLE
[Associations] You are not permitted to use that link...

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#15945]
### Steps to reproduce the issue
Create a basic multilingual site (2 languages are enough).
Logout.
Quit browser (tested here with FF and Safari)

Relaunch browser, log in the admin and display Multingual associations.
Choose an article and language (here default Article (en-gb)
Click on the Associations label for French.

This is what we get.
![youarenotassoc](https://cloud.githubusercontent.com/assets/869724/25909923/f1431f02-35ae-11e7-94d2-9355686503c5.gif)

After reloading the page, all is fine and the issue is never encountered again until one quits the browser and relaunches it

Any idea how to solve this?
@rdeutz @dgt41 @Fedik @alikon

**Comment by Fedik** [comment]
It looks similar to #9145 , and there already was some fix #13516

**Comment by infograf768** [comment]
looks like this fix does not work for com_associations though.
Do we have to add `JFactory::getApplication()->allowCache(false);` somewhere?

**Comment by Fedik** [comment]
I am not really understand how that fix should work 😃 
But the issue looks similar, because in the iframe we actually open the article editing form.

**Comment by PhilETaylor** [comment]
This is a classic race condition. 

"Checking out" an article is done in the session

By loading TWO iframes, loading starting at milliseconds from each other, the session of one is overwriting the other. 

You can prove this by removing the left iframe and you will see then that the right iframe loads without fail each and every time

The solution is to load each iframe - one at a time, waiting for the parent page to finish loading, then loading the left frame, and when that finishes loading load the right frame. 

On first glance there are a few other "bugs" here, like the fact I can fake urls on a non-multulingual site to view content in either pane

**Comment by PhilETaylor** [comment]
Please test #15948 (and to a much lesser degree #15947)

**Comment by infograf768** [comment]
Closing as we have a fix. https://github.com/joomla/joomla-cms/pull/15948<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15945">issues.joomla.org/tracker/joomla-cms/15945</a>.</sub>
