### ISSUE TITLE
Joomla 3.7 upgrade error message

### ISSUE THREAD

**Issue by eltigre54** [joomla/joomla-cms#15959]
### Steps to reproduce the issue
Every time I tried to upgrade to J3.7 I got error messages. I get an error message in the backend "Warning : Error loading component: com_fields, Component not found."

And on the front end an error message where the website's menu would be located, "Unknown column 'a.client_id' in 'where clause'".

Advice from Rockettheme forum suggested Under Extensions, I fixed database and under discovery resolved modules as well. After upgrade to J3.7 the front end error disappeared, but the backend error message remains.

### Expected result
Error message to disappear after upgrade

### Actual result
Error message remains

### System information (as much as possible)
Joomla 3.7, php7.0, siteground host,

**Comment by Gitjk** [comment]
Looks like this report is the same as: [15401](https://github.com/joomla/joomla-cms/issues/15401 "15401")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15959">issues.joomla.org/tracker/joomla-cms/15959</a>.</sub>

**Comment by PhilETaylor** [comment]
This is because the post upgrade tasks never ran 

Go to admin -> Extensions -> Database Tab -> Click fix button
Then go to admin -> Extension -> Discover -> Discover button -> select all -> click install 

Done.

**Comment by franz-wohlkoenig** [comment]
@eltigre54 if the hints above helped, please close this Issue, thanks.

**Comment by eltigre54** [comment]
Apologies forum if I paste in the wrong place.

I have received two emails that point me to the Extensions Database and Discovery options and instructions to resolve the issue, but it appears that with the upgrade to 3.7 these options have disappeared from the main admin menu. I am unable to access the recommendations made.

Any further clues will be gratefully appreciated.

![image](https://cloud.githubusercontent.com/assets/28617798/25976302/5733d9e8-36f7-11e7-88d3-f7c8c0640c3d.png)

**Comment by PhilETaylor** [comment]
Click the word "Manage" in your screenshot
Then look on the left of the page and you will see the Database and Discover tabs.

**Comment by tonypartridge** [comment]
Can this be closed? @zero-24

**Comment by zero-24** [comment]
This looks like a failed update please contact the forum if you need more help. Thanks https://forum.joomla.org closing here.
