### ISSUE TITLE
Menu and toolbar button disapare when using $root_user

### ISSUE THREAD

**Issue by wojsmol** [joomla/joomla-cms#15957]
### Steps to reproduce the issue
1. Delete `Super User` group from `Special`  view lewel and click `Save & Close`.
2. Add `public $root_user='SU_LOGIN';` to `configuration.php`
3. Try add `Super User` group to Special view level using backend.
### Expected result
`Super User` group successfully added to `Special` view level.
### Actual result
No admin menu and toobar buttons
### System information (as much as possible)
Joomla! 3.7.0 and staging on php 5.6.x

**Comment by wojsmol** [comment]
cc @izharaazmi as this is parly related to menu system

**Comment by zero-24** [comment]
Hmm you should be able to see it unsing the direct link correct? If yes you can add the view level back and fix the module display. Btw you dond need root user imo as you have a working superuser anyway ;) you can also do all that stuff via the database ;)

**Comment by wojsmol** [comment]
Direct links work, this is true, and you can reach the edit view of a specific view level, but there are no buttons for Save & Close. Of course, you can solve this problem through the database, which is not a problem for me, but as a moderator of the Polish Joomla forum I have found users who make queries to the database is no so easy. Then the opportunity to use `$root_user` made it easier to solve the problem.

**Comment by zero-24** [comment]
> Then the opportunity to use $root_user made it easier to solve the problem.

Sure but the problem here is $root_user are just a way to make a other user temporary super user. This is not a system recovery mode ;).

**Comment by brianteeman** [comment]
> Sure but the problem here is $root_user are just a way to make a other user temporary super user. This is not a system recovery mode ;).

Thats exactly what it is. At the absolute minimum they should have accerss to com_users

**Comment by izharaazmi** [comment]
This is happening because of the authorisedViewLevels = empty or
insufficient for that user. As of now \JAccess::getAuthorisedViewLevels
does not account to the root_user setting and hence the issue. I can do the
PR but there are few other points to worry about. Let me know.

**Comment by wojsmol** [comment]
PR will be welcome IMHO. Looking from the perspective of a person helping other inexperienced users.

**Comment by izharaazmi** [comment]
Check the PR

**Comment by brianteeman** [comment]
closed see #15988
