### ISSUE TITLE
Created date on sample data installation (#11577)

### ISSUE THREAD

**Issue by hendrikbehncke** [joomla/joomla-cms#15961]
All sample data will be updated with the current date as creation date, except for sample_testing.sql. This causes an issue with our own sample data as Joomla uses the create date as default for sorting articles in the article view. With Joomla 3.7 the sorting changes because of the reset of the creation dates.

### Steps to reproduce the issue
Install a full Joomla package with sample data.

### Expected result
Keep the original create date as provided in the sample sql.

### Actual result
All dates are set to the date when Joomla was installed

### Additional comments
I would suggest to do the replacement of the dates only for Joomla's own sample data

**Comment by brianteeman** [comment]
What do you mean by "our own sample data"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15961">issues.joomla.org/tracker/joomla-cms/15961</a>.</sub>

**Comment by wojsmol** [comment]
@brianteeman On templaes quick start package yoy mey have a option added to saple data list.

**Comment by hendrikbehncke** [comment]
Hi, as a template provider we add our own sql file with sample content to the list of sample data. Since the release of Joomla 3.7 the articles have all the same date and the sample pages don't look the same like they were created because the sorting of articles changes.
It would help if the replacement of the creation date would only happen for the Joomla sample sql files.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15961">issues.joomla.org/tracker/joomla-cms/15961</a>.</sub>

**Comment by zero-24** [comment]
@hendrikbehncke please check #16031 and provide a example to test with there thanks!

**Comment by brianteeman** [comment]
It has been several months since this issue was created without response. I am closing it at this time but it can always be reopened
