### ISSUE TITLE
Update 3.7.1-dev > 3.8: "Error: 0 Class 'JRoute' not found

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#15975]
### Steps to reproduce the issue
Update 3.7.1-dev by Joomla-Update (path: https://update.joomla.org/core/nightlies/next_minor_list.xml) got (only Menu on Top is shown, Sub-Menu "Log-out" isn't shown; below Menu is blank Page):
![bildschirmfoto 2017-05-12 um 06 17 10](https://cloud.githubusercontent.com/assets/8235763/25982203/bf8fd7ca-36da-11e7-810c-72f310fa2618.JPG)
#### in Browser-Tab Error is shown:
![bildschirmfoto 2017-05-12 um 06 17 27](https://cloud.githubusercontent.com/assets/8235763/25982209/cda17152-36da-11e7-8a2f-6424cb7fb6e6.JPG)
#### Console:
Empty string passed to getElementById().  jquery.js:2925:12
### System information
3.7.1-dev
macOS Sierra, 10.12.4
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by franz-wohlkoenig** [comment]
Test on clean 3.7.1-dev with same Result.

**Comment by mbabker** [comment]
Added one too many directories to the delete files array.  Removed it in https://github.com/joomla/joomla-cms/commit/9c23a1fe70db78e059472f2dc53b8bc34ded0542
