### ISSUE TITLE
JHTML::_('behavior.calendar') does not load calendar-setup.js and calendar-jos.css for Joomla 3.7

### ISSUE THREAD

**Issue by simbunch** [joomla/joomla-cms#15972]
Prior to Joomla 3.7, JHTML::_('behavior.calendar') will load:
/media/system/js/calendar.js
/media/system/js/calendar-setup.js
/media/system/css/calendar-jos.css 

In Joomla 3.7, only calendar.js is loaded. The 2 other files still exist.

**Comment by dgt41** [comment]
The code i there: https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/html/behavior.php#L567-L592

**Comment by rdeutz** [comment]
Already fixed

**Comment by nripendra-choudhary** [comment]
I am still finding this error with joomla3.7.4
Please help

**Comment by ghost** [comment]
@nicknripendra please open a new Issue as this one is closed.

**Comment by michaelulm** [comment]
I am still finding this error with joomla3.7.5, maybe just a kind of similiar error 
calendar doesn't work in a view in a modal, but calendar works in a list view as a part of a filter
Please help

**Comment by ghost** [comment]
@michaelulm please open a new Issue as this one is closed.
