### ISSUE TITLE
PasswordHash has a deprecated constructor

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#15985]
### Steps to reproduce the issue

Run unit tests in PHP 71. - see: https://travis-ci.org/joomla/joomla-cms/jobs/231268244

### Expected result

No warnings

### Actual result

`PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; PasswordHash has a deprecated constructor in /home/travis/build/joomla/joomla-cms/libraries/phpass/PasswordHash.php on line 27`

**Comment by photodude** [comment]
Just referencing the PR that resolves this issue, so no one needs to hunt through all the links. See #15704
