### ISSUE TITLE
3.7.1 RC1 - unknown column "a.name' in field list

### ISSUE THREAD

**Issue by Stevec4** [joomla/joomla-cms#15992]
### Steps to reproduce the issue
Joomla 3.7.0 upgraded to 3.71.RC1
Select Fields from any article menu item in back end

### Actual result
Error
Unknown column 'a.name' in 'field list'

### System information (as much as possible)
Checking the database structure
•Database schema version (in #__schemas): 3.7.0-2017-04-19.
•Update version (in #__extensions): 3.7.1-rc1.
•Database driver: mysqli.

**Comment by brianteeman** [comment]
Was it working on this install BEFORE the upgrade?

I didnt have this problem myself

**Comment by zero-24** [comment]
@Stevec4 can you please told us where your 3.7 version is comming from? Or was your 3.7 a new install?

**Comment by Stevec4** [comment]
Sorry guys looks the fields table was not updated to the stable release on my test server.
This can be closed.
Steve

**Comment by zero-24** [comment]
Thanks for the feedback.
