### ISSUE TITLE
Database transaction handling is broken...

### ISSUE THREAD

**Issue by ChristianEhlscheid** [joomla/joomla-cms#15996]
I've already submitted the bug report to the Joomla Framework repo, so i just link to it here.
The problem and the solution is the same.
https://github.com/joomla-framework/database/issues/86

**Comment by franz-wohlkoenig** [comment]
Closed as duplicate Report in Framework Repo. @mbabker will look into this Issue in Framework Repo also.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15996">issues.joomla.org/tracker/joomla-cms/15996</a>.</sub>
