### ISSUE TITLE
Registration Approval Email

### ISSUE THREAD

**Issue by jestrado** [joomla/joomla-cms#15990]
### Steps to reproduce the issue
When a user submits a registration form from this page https://www.swankykidzworld.com/index.php/login, the administrator receives an email notification (see attached capture.png).![capture.png]((https://issues.joomla.org/uploads/1/df0c4b9842bca7946a425b3d6a42dd79.png) "")

### Expected result
I would like that email to have all the populated fields of the registration form instead of only name, username and email. see attached for example (capture2.png) ![capture2.png]((https://issues.joomla.org/uploads/1/be2cc69ce27acd56231ea7e021299415.png) "")

### Actual result
(see attached capture.png).![capture.png]((https://issues.joomla.org/uploads/1/df0c4b9842bca7946a425b3d6a42dd79.png) "")

### System information (as much as possible)
Joomla 3!

### Additional comments
i am not too familiar with coding.

Thanks in advance.

**Comment by brianteeman** [comment]
> Is this possible?!


No it is not possible with the core of Joomla - it may be possible with an extension available at https://extensions.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15990">issues.joomla.org/tracker/joomla-cms/15990</a>.</sub>

**Comment by zero-24** [comment]
Closing this as not a core issue. Please ask such questions at https://forum.joomla.org thanks for understanding 👍

**Comment by jestrado** [comment]
ok. sorry for asking in the wrong place, but thank you Brian for responding

**Comment by zero-24** [comment]
no Problem 😄
