### ISSUE TITLE
After updating Joomla 3.7 the TinyMCE editor stops responding to button

### ISSUE THREAD

**Issue by tkdspb** [joomla/joomla-cms#15991]
### Steps to reproduce the issue

Sreen on https://youtu.be/ABoIR_Pd_Jo

**Comment by zero-24** [comment]
Please clear your Browser, joomla and if enabled server cache and try again

**Comment by tkdspb** [comment]
I did the reset, did run this plugin in another browser. Tried hosting and local server<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>

**Comment by tkdspb** [comment]
PHP local 7.0
PHP Hosting 6.5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>

**Comment by zero-24** [comment]
> I did the reset

What is a reset in this context?

**Comment by tkdspb** [comment]
Recently I had to change the sites template jm-service & helix
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>

**Comment by tkdspb** [comment]
Two different servers, three different browser, two different template?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>

**Comment by tkdspb** [comment]
What do you mean by RESET?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>

**Comment by tkdspb** [comment]
Sorry for the RESET. It Is the term automatic translator.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>

**Comment by tkdspb** [comment]
The problem is not in terms of a software<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>

**Comment by tkdspb** [comment]
Sreen on https://youtu.be/ABoIR_Pd_Jo<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>

**Comment by tkdspb** [comment]
I did the upgrade on the server hosting. Then the same on another website with this template. Then I checked on the local server with test pattern. What else YOU want to know?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>

**Comment by tkdspb** [comment]
browsers Yandex Google Fairefoks - the same result<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>

**Comment by wojsmol** [comment]
@tkdspb Switch to protostar as a test.

**Comment by brianteeman** [comment]
you said you are using helix 

did you upgrade it to helix 2.0 as that is needed for Joomla 3.7
https://www.joomshaper.com/joomla-templates/helix3

**Comment by tkdspb** [comment]
Why am I the administrative part of the problem is, and from the site no?
Your programmers have curves hands?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>

**Comment by tkdspb** [comment]
You can imagine updating the template in this case?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>

**Comment by brianteeman** [comment]
are you using helix template

what version is the helix template

**Comment by tkdspb** [comment]
I like this trend today I changed the engine, tomorrow you have to re-pay the programmers<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>

**Comment by wojsmol** [comment]
@tkdspb Regarding JM Services plase update EF 4 Framework plugin

**Comment by tkdspb** [comment]
The question is simple. competitive editor works. standard no. At whom curve hands?
See JCE. They never asked who made the template.
But I chose this editor and asked to make it workable.
Тем более, что он работает на сайте. Убейте своих программистов для начала. и да . я русский.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>

**Comment by tkdspb** [comment]
Especially because it works on the website. Kill your programmers to begin with. and Yes . I'm Russian.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>

**Comment by tonypartridge** [comment]
In your video you haven't cleared the browsers cache or tried clearing your CDN if you have one.

Furthermore, you are using save and close buttons in the video which are not responding.

Can you please explain clearly your problem, write in Russian and translate with google if that helps.

**Comment by tonypartridge** [comment]
Also, if you wait does it eventually produce an error? There is a bug in J3.7.0 with save in some scenarios and can you try 3.7.1.

**Comment by tkdspb** [comment]
while I have no way to update to this version in Russian in automatic mode<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>

**Comment by gwsdesk** [comment]
You were asked multiple time 

* are you using helix template

* what version is the helix template

Answer those questions please?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>

**Comment by tkdspb** [comment]
Template JM Services Template version: 1.04<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>

**Comment by tkdspb** [comment]
Based on EF4 Framework<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>

**Comment by tkdspb** [comment]
I did the updates at different sites with different templates. The problem with this Template JM Services Template version: 1.04. On Helix templates problems do not have.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>

**Comment by tonypartridge** [comment]
So contact the template provide to update it.

**Comment by tkdspb** [comment]
Thank you. The best solution JCE editor.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
closed as no Core-Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15991">issues.joomla.org/tracker/joomla-cms/15991</a>.</sub>
