### ISSUE TITLE
Redundant file?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#16005]
is this file used anywhere?
https://github.com/joomla/joomla-cms/blob/staging/components/com_contact/models/forms/form.xml

I ask because the majority of the language strings do not exist at all and yet no one has noticed this and reported untranslated strings.

**Comment by zero-24** [comment]
to me it looks like a frontend submit form for contacts. Which looks like never implemented.

**Comment by brianteeman** [comment]
That was my guess too

**Comment by bertmert** [comment]
See please
https://github.com/joomla/joomla-cms/pull/10730

https://github.com/joomla/joomla-cms/pull/10786

**Comment by brianteeman** [comment]
thanks @bertmert I will do a PR shortly to add the deprecated notice in J3 and remove this file in J4

**Comment by brianteeman** [comment]
closed see #16007
