### ISSUE TITLE
[4.0] [RFC] Move toolbar apply items to thead

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#16000]
One of a handful of solutions for the toolbar (#12789) is to move the apply items to the table head

- Logical location for such apply actions within a table
- Simplifies the view
- Resolves #12789 

![toolbar-thead](https://cloud.githubusercontent.com/assets/2803503/26024709/18684176-37cf-11e7-9dc5-cf24ccde0c71.gif)

**Comment by brianteeman** [comment]
Definitely an interesting option. Should be relatively simple to make accessible as well

**Comment by C-Lodder** [comment]
+1

**Comment by brianteeman** [comment]
Maybe replace the ...  with a cog icon would be more meaningful

**Comment by ciar4n** [comment]
![thead-icon1](https://cloud.githubusercontent.com/assets/2803503/26026068/96319d24-37ec-11e7-91d7-27a81ce895e5.png)

I guess technically the 3 dots is a menu overflow icon. This would make it correct in the tbody (overflow of the publish and feature icons) but not for the thead icon. Considering this the following would also work..

![thead-icon2](https://cloud.githubusercontent.com/assets/2803503/26026071/a2f2b516-37ec-11e7-96b4-bc7afffe8ef4.png)

**Comment by ciar4n** [comment]
Looks like google opted for 3 vertical dots for a standalone dropdown

![icon-google](https://cloud.githubusercontent.com/assets/2803503/26026080/da6eae0a-37ec-11e7-9178-98e0ddcb3c67.jpg)

**Comment by tonypartridge** [comment]
The three dots are more commonly known, whereas a config icon isn't great since it's a configuration option and publishing it more of a editing option opposed to configuration.

Love the idea though, three dots for me!

**Comment by brianteeman** [comment]
The problem with the three dots (and why I was suggesting to use something else) is that in J3 we used the three dots as the grab handles for sorting.

**Comment by ciar4n** [comment]
The grab handles in J3 appear to be vertical dots rather than horizontal. Personally I think this should be difference enough not to cause any confusion?

Might make sense to combine this column with the status column. Give a larger clickable area for head dropdown, makes logical sense as this is largely the visible column that is effected and brings the '3 dots' icon inline with the other action icons. Assuming '3 dots' represents overflow options to a menu which is largely the case (eg. https://www.facebook.com/joomla/).

![thead-icon3](https://cloud.githubusercontent.com/assets/2803503/26033006/39972996-3899-11e7-8a82-dd663281f3a2.png)

**Comment by brianteeman** [comment]
combined columns make the a11y a little harder to maintain but not impossible

**Comment by C-Lodder** [comment]
@ciar4n - think it would be much better as separate column. Like you did in the initial screenshot ;)

**Comment by brianteeman** [comment]
still not sure of the benefit of changing the icon/symbol from the current down arrow to the three dots

**Comment by mbabker** [comment]
IMO the dropdown arrow works in 3.x because it's styled as a group of buttons.  Without the button styling, to me it seems more like a misplaced character (just trying to imagine it versus the 3 dots).

**Comment by brianteeman** [comment]
Something for the UX team?

**Comment by C-Lodder** [comment]
who?

**Comment by ciar4n** [comment]
@C-Lodder  "Once upon a time in a land far far away ... ... ... "

**Comment by ciar4n** [comment]
Probably not the best example but the previous comment does show how 3 dots indicate there is more than what is shown which is why this icon is commonly used. Also why it does not work as a standalone icon (table header).

**Comment by ciar4n** [comment]
The clickable area of the head icon (initial screenshot) is very small considering it will probably be used a lot. If giving it a separate column we probably should use text instead...

![thead-icon4](https://cloud.githubusercontent.com/assets/2803503/26034224/5f9a286a-38b1-11e7-871a-383b74492788.png)

**Comment by brianteeman** [comment]
That works for me :)

**Comment by dgt41** [comment]
A side note here: the table header titles should be blue (link color) only when there is a clickable title else should be blackish (normal text). In this case e.g. Actions should be black as you shouldn't be able to sort the table depending on the available actions. The same concept should be applied to all the `th`

**Comment by tonypartridge** [comment]
Me too

**Comment by ciar4n** [comment]
First of 2 PRs created... #16015

**Comment by ciar4n** [comment]
Second of 2 PRs created.. #16076
