### ISSUE TITLE
[com_finder] Problem with suggestions

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#16011]
My problem is, that I see suggestions with no search result if I use a filter

### Steps to reproduce the issue
1. Create an article in the category donotshow and fill in the text “nina”
2. Open the component Smart Search and create the index.
3. Create a module for Smart Search and test this module with the search string “ninh”
There is nothing found, but you will see the question: Did you mean: nina? 
If you click on nina you see the search result.
4. Go back to component Smart Search and create a search filter for only showing uncategorized items.
5. Go back to the module and set the filter in the options of this module.
6. Delete the cache
7. Now go back to the frond end and test the Smart Search module again with the search string “ninh”
There is nothing found, but you will see the question: Did you mean: nina? 
If you click on nina you see no result, because you set the filter.

### Expected result

I would only see suggestions, if there are results for this suggestion. 

### Actual result

I see suggestions for results, that are filtered.

**Comment by brianteeman** [comment]
This is a long standing issue with the finder index not the filter. If I remember correctly you will also see suggestions for content that you do not have permission to see - if i remember wrongly and that has been fixed then the same fix will work here

**Comment by astridx** [comment]
I could not find an issue for this problem - if someone else find something it would great to link it here.

**Comment by brianteeman** [comment]
@astridx it would be very old - perhaps in the joomlacode archive here https://developer.joomla.org/joomlacode-archive/

The conversation was between me and chris davenport where I was stating that it was a security issue to display suggestions to content that you dont have permission to see

**Comment by brianteeman** [comment]
https://issues.joomla.org/tracker/joomla-cms/4401

**Comment by brianteeman** [comment]
and the report and discussion that resulted in that https://issues.joomla.org/tracker/joomla-cms/4301

As you will read thats not the first report (the one I remembered @astridx but its got the same answers)

**Comment by Hackwar** [comment]
The auto suggest in Smart Search does display words from unpublished content or content that you don't have access to. Unfortunately, that can not be prevented with the way Smart Searches auto suggest works. I can only give the advice to switch off auto suggest if that is a problem. We can definitely not fix that in 3.x and I'm also hesitant to change this in 4.0, which again would be really difficult.

I'm asking to close this issue as unfixable.

**Comment by ggppdk** [comment]
Issues with discussions (there are others closed as duplicates with no discussion in them)
#4301 (Smart search showing unpublished articles in auto suggest )
#8655 (Smart Search - search suggestion does not obey access permission of content)

and the PR mentioned by @brianteeman (github link)
#4401

**Comment by brianteeman** [comment]
Closed as not fixable
