### ISSUE TITLE
Joomla gavick's magazine template error after upgrading to 3.7

### ISSUE THREAD

**Issue by pdanyi** [joomla/joomla-cms#16013]
After upgrading joomla to 3.7, the template style menus disappeared in my GavickPro's Magazine template. When I go to Templaters: Edit Style, the template configurator menus from top are simply not there. In 3.6 there was no problem at all.

Question: can I roll back to lates joomla (3.6.5)? 
Or is there any other way to make the menu list available?

**Comment by franz-wohlkoenig** [comment]
Have you asked Template-Developers for this Issue? Closing as no Core-Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16013">issues.joomla.org/tracker/joomla-cms/16013</a>.</sub>

**Comment by Sandra97** [comment]
@pdanyi Update your Gavick Template (if the update is available). All tabs of the template style in the backend for all Gavick Templates have disappeared after updating to 3.7.0. Updating the template will solve your issue.
