### ISSUE TITLE
Security Patch for Version 3.6

### ISSUE THREAD

**Issue by neo191987** [joomla/joomla-cms#16021]
Hi I want to ask you to run a security patch for version 3.6. There are some problems with some of the apps, and I think I'll stick to the autumn by 3.6, because then I'll update my licenses to them. I think there will be other people willing to remain in version 3.6 for now. Thanks in advance.

**Comment by brianteeman** [comment]
That's not going to happen - the security patch for 3.6 is to upgrade

**Comment by neo191987** [comment]
Is this problem in version 3.6.5 or only in 3.7?

**Comment by brianteeman** [comment]
> Since this is a very important security fix, please be prepared to update your Joomla! installations next Wednesday.
Until the release is out, please understand that we cannot provide any further information.

**Comment by neo191987** [comment]
Okay, I'll wait. I close the ticket.
