### ISSUE TITLE
[4.0] sidebar small glitch

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#16027]
### Steps to reproduce the issue

- Click on "Components"
- Click on "News Feeds"
- Click on "News Feeds" again

### Expected result

Do nothing

### Actual result

Sidebar reverts back to it's original state. If you then want to access the 2nd level menu, you need to click one of the parent items twice.

### GIF

https://gyazo.com/1766b74b2243c568d2f2210c8f29954b

### Additional comments

Perhaps the `<a>` element should only be used if the item links your directly to the view. If the item is supposed to display a 3rd level menu, maybe use a `span` instead.

**Comment by franz-wohlkoenig** [comment]
Issue confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16027">issues.joomla.org/tracker/joomla-cms/16027</a>.</sub>

**Comment by ciar4n** [comment]
PR created.. #17070

**Comment by C-Lodder** [comment]
Closing for PR
