### ISSUE TITLE
[4.0] Cannot declare class JToolBar, because the name is already in use

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#16025]
### Steps to reproduce the issue

Go to the Article Manager and the following error is being thrown:

> Warning: Cannot declare class JToolBar, because the name is already in use in \libraries\loader.php on line 769

Something to do with this line: https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/classmap.php#L150

removing this line works but maybe not the solution

@laoneo 

### System information (as much as possible)
- Joomla 4 (latest)
- PHP 5.6 & 7.x

**Comment by laoneo** [comment]
Can you please check out the 3.8-dev branch. Do you have the same issue there as well? I haven't but it is the same code.

**Comment by laoneo** [comment]
#16037 fixes the issue
