### ISSUE TITLE
Menu Item - Tag

### ISSUE THREAD

**Issue by mseidl73** [joomla/joomla-cms#16030]
In the »Inhalt« module there are submenu items (eg in experiments) that are linked to a tag. For example, click on »Experimente - Analytik« and select an experiment from the list, the correct article will appear, but the wrong page header will appear, the slider will not be hidden and the article information will not be displayed! The differences from J 3.6.5 to J 3.7.0 I have marked in the attached pictures.
The cause is somewhere in root\components\com_content. I have on my local installation the said folder from the 3.7.0 deleted and copied from the 3.6.5. Behold, the mistakes are gone! It is also not a faulty update, because I can with a fresh (blank) 3.7.0 the error can reproduce.
I think the Problem is found on line 242 to 243 in root\components\com_content\views\article\view.html.php of 3.7.0

Link to my site: [https://www.chem-page.de](https://www.chem-page.de "Chem-Page.de")
Issue description in german: [Problembeschreibung in Deutsch](http://www.joomlaportal.de/joomla-3-x-allgemeine-fragen/328730-massive-joomla-3-7-0-probleme-caching-mod-article_latest-schlagworte-suchindex.html "Problembeschreibung in Deutsch")
![screen shot 2017-05-15 at 13 55 58](https://issues.joomla.org/uploads/1/937f689573186f1699395dc96bd91f1e.jpg)![screen shot 2017-05-15 at 13 55 58](https://issues.joomla.org/uploads/1/46a97366eeedc02e1b36bf9d4f5c20c2.jpg)

**Comment by PhilETaylor** [comment]
Is this not a duplicate of #16029

**Comment by mseidl73** [comment]
Possible. The Problem is locatet in the same file.

**Comment by SniperSister** [comment]
This is indeed a duplicate of #16029, so one of them can be closed.

Regarding your issue: do you have a menu item for the article itself or it's category? If not, please create and and test if thix fixes the issue.

**Comment by mseidl73** [comment]
The error does not occur when the item or category is linked as menu item. But now the article title is double. ![screen shot 2017-07-21 at 12 03 03](https://issues.joomla.org/uploads/1/1b8fc3557c70808abcad707abcf15db9.jpg)The error occurs when the article is called via mod_article_latest or a linked tag.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16030">issues.joomla.org/tracker/joomla-cms/16030</a>.</sub>

**Comment by mseidl73** [comment]
Another users have the same problem. See [https://forum.joomla.org/viewtopic.php?f=706&t=950605](https://forum.joomla.org/viewtopic.php?f=706&t=950605 "Latest News module does not show article title")

I have renamed the com_content folder (3.7.x) and copied the folder from 3.6.5.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16030">issues.joomla.org/tracker/joomla-cms/16030</a>.</sub>

**Comment by SniperSister** [comment]
This change in behavior is most likely related to changes to the routing code in 3.7 and I personally would consider them "expected" behavior. Explanation:

In Joomla, various things like module assignments, menu parameters (including page titles!) and even assigned templates are connected to menu items, right? 

If you now have a module that shows links to articles, that don't have an own menu item (or one to the category that those items are assigend to), Joomla needs to decide which menu item is used under the hood to look for those parameters and show the modules - and apparently with 3.7 a different menu item is chosen on your site, than the one that was chosen before.

Easy fix: create proper menu items.

**Comment by mseidl73** [comment]
So this means that you should not use mod_article_latest and tags?
Apart from each article gets its own menu point?
So I would have to create more than 1000 menu items on my website?
In 3.6.5 it all worked fine!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16030">issues.joomla.org/tracker/joomla-cms/16030</a>.</sub>

**Comment by SniperSister** [comment]
Creating items for the categories should be enough, no need to create a menu item per article.

**Comment by mseidl73** [comment]
The categories have items. For "Matriumperoxid und Schwefel" it`s "Experimente".
Also by mod_article_latest: News, Experimente, Synthesen, Neue Tutorials and Neu in der Datenbank
All articles are in categories.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16030">issues.joomla.org/tracker/joomla-cms/16030</a>.</sub>

**Comment by mseidl73** [comment]
And categories are linked as menu items (left or top).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16030">issues.joomla.org/tracker/joomla-cms/16030</a>.</sub>

**Comment by SniperSister** [comment]
That's how it's supposed to be and the routing works as expected on your site - I don't get your point here?

**Comment by mseidl73** [comment]
On my Website i have replaced the folder com_content (3.7.x) with com_content from 3.6.5. So it works.
I will change it now, so you can see the problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16030">issues.joomla.org/tracker/joomla-cms/16030</a>.</sub>

**Comment by mseidl73** [comment]
So, now it's changed.
The welcome Text title is every shown, when you click on a menuitem in Module News.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16030">issues.joomla.org/tracker/joomla-cms/16030</a>.</sub>

**Comment by SniperSister** [comment]
Please double check:

* is the category that you selected for the "News" menu item the same as the one that you assigned the actual articles too? It needs to be the exact same one, nested categories (have a general "news" category for the menu item with subcategories, where the acutal articles are assigend) won't work.
* what is the menu type of the "Anorganische Chemie" and "Synthesen" menu items? The markup is different for the items, and that lets me assume that you are having different types here.

**Comment by mseidl73** [comment]
The "News" item (top menu) is a category list item to category "News". The articles in module "News" (mod_article_latest in the bottom) are in the category "News", not nested.

The item "Synthesen" is a category list of category "Synthesen". "Anorganische Chemie" is a compact list of tagged items. The articles of "Anorganische Chemie" are in category "Synthesen"; tagged with "anorganische Chemie".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16030">issues.joomla.org/tracker/joomla-cms/16030</a>.</sub>

**Comment by SniperSister** [comment]
Ok, that makes sense and should work - at least in theory.

Apparently the 3.7 routing changes broke the code that looks for the correct category for an article.

**Comment by mseidl73** [comment]
I think so!
Ok, i change my com_content back to 3.6.5.
How to fix it?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16030">issues.joomla.org/tracker/joomla-cms/16030</a>.</sub>

**Comment by SniperSister** [comment]
This needs to be fixed within the content router which is a rather complex piece of code, so there is no "quick fix" in that case.

**Comment by mseidl73** [comment]
Qick fix: Use com_content from 3.6.5 ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16030">issues.joomla.org/tracker/joomla-cms/16030</a>.</sub>

**Comment by SniperSister** [comment]
This "fix" might cause all sorts of other problems or (worst case) overwrite security fixes that might have been applied in newer versions, so for me that isn't a solution. Your site, your choice ;)

**Comment by brianteeman** [comment]
This sounds like something unique to your own site structure as we have had no similar reports in the following year.
