### ISSUE TITLE
[com_finder] Problem with suggestions in multilanguage site

### ISSUE THREAD

**Issue by Edward0625** [joomla/joomla-cms#16033]
### Steps to reproduce the issue
1. Create a contact category "Kereskedelemi munkatársak" for hungarian language
2. Create a contact category "Sales" for english language
3. Create a contact category "Vertrieb" for germany language
4. Create a contact "Kókai Zsolt" for "Kereskedelem" category, the language is hungarian
5. Create a contact "Kókai Zsolt" for "Sales" category, the language is english
6. Create a contact "Kókai Zsolt" for "Vertrieb" category, the language is germany
7. Open the component Smart Search and create the index
8. Create a module for Smart Search and test this module with the search string “Kókai”
9. The default language is hungarian and the test is ok, the suggestions are displayed
![hungarian](https://cloud.githubusercontent.com/assets/7513278/26062072/189e8652-398a-11e7-8b40-30a442120532.jpg)

10. Change language in germany, type "Kókai" but the suggestions will not be displayed
![germany](https://cloud.githubusercontent.com/assets/7513278/26062081/208e7b6a-398a-11e7-9e4b-306928b8ea60.jpg)

11. Change language in english, type "Kókai" but the suggestions will not be displayed
![english](https://cloud.githubusercontent.com/assets/7513278/26062094/2a53ff12-398a-11e7-8de0-8b4cc58150ba.jpg)

### Expected result
I would see same suggestion in germany and english language what is displayed in hungarian language

### Actual result
Suggestion displayed just for hungarian language

### System information (as much as possible)
Joomla 3.7

### Additional comments
This is the results in finder_terms table
![finder_terms_table](https://cloud.githubusercontent.com/assets/7513278/26062347/da7db7a2-398a-11e7-93ee-d5f393be2103.jpg)

**Comment by franz-wohlkoenig** [comment]
@infograf768 any Thoughts about this Issue?

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 17th September 2017.

**Comment by ghost** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened.
