### ISSUE TITLE
[com_fields] "Alternate Layout" for Fields plugin doesn´t work

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#16032]
I just tried https://github.com/joomla/joomla-cms/pull/15027 which is already merged, but it doesn´t work for me. 

If i put in {field 1} it works
{field 1, foo} does not display the field output at all.

cc: @Bakual

**Comment by PhilETaylor** [comment]
Did your field have any value? The layout will ONLY show if $value is not empty.

**Comment by PhilETaylor** [comment]
I have tested #15027 in response to your issue, and could not find an issue

**Comment by coolcat-creations** [comment]
thank you @PhilETaylor and sorry for wasting your time. It was not an empty value but I didn´t put it in layouts but directly in com_fields :(
