### ISSUE TITLE
Fatal error with onContentPrepareForm when changing a category

### ISSUE THREAD

**Issue by ced1870** [joomla/joomla-cms#16047]
### Steps to reproduce the issue

Create a plugin with an event "onContentPrepareForm" like this

public function onContentPrepareForm($form, $data) {
	if (count($data)) {
		// get article params
		$attribs = $data->get('attribs');
	}
}

Edit an article and try to change its category. The fatal error appears that the get does not exists.

### Expected result

$data shall be the associated data for the form.

### Actual result

$data is empty

### System information (as much as possible)

Joomla! 3.7.0

### Additional comments

On article loading, $data returns a JObect

when switching the category, the $data in the article returns a simple Array

**Comment by dgt41** [comment]
Try this:
```php
public function onContentPrepareForm($form, $data) {
   if (isset($data) && count($data)) {
      // get article params
      $attribs = $data->get('attribs');
   }
}

**Comment by ced1870** [comment]
this is not correct because I'm still in the article and I need to edit the attribs

I have used this to avoid the error, but the problem is in the fact that $data shall be a JObject and not an Array

if (method_exists($data,'get')) {
				$attribs = $data->get('attribs');
			} else if (isset($data['attribs'])) {
				$attribs = $data['attribs'];
			}<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16047">issues.joomla.org/tracker/joomla-cms/16047</a>.</sub>

**Comment by dgt41** [comment]
That was my misunderstanding, yes you are right $data should remain JObject

**Comment by rdeutz** [comment]
You need to figure out what type of data you get, take a look at this: https://github.com/joomla/joomla-cms/blob/staging/plugins/system/fields/fields.php#L194

**Comment by ced1870** [comment]
I'm already checking the context, I'm in 'com_content.article' in both cases

this problem was not there before the 3.7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16047">issues.joomla.org/tracker/joomla-cms/16047</a>.</sub>

**Comment by rdeutz** [comment]
Check it with 3.6.5 it is the same you get an empty array or a jObject

**Comment by jjsjjs** [comment]
I'm having an similair issue, but without a plugin as above. 
Simply when creating an article and then change the category. 
Please see: https://forum.joomla.org/viewtopic.php?f=706&t=950583
I have no further info then the Error itself.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16047">issues.joomla.org/tracker/joomla-cms/16047</a>.</sub>

**Comment by ced1870** [comment]
@rdeutz : no matter in which version this has been introduced, it just does not work as expected :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16047">issues.joomla.org/tracker/joomla-cms/16047</a>.</sub>

**Comment by rdeutz** [comment]
oh no, it works as expected, if you check the profile plugin you will find:

 ```php

/**
	 * Adds additional fields to the user editing form
	 *
	 * @param   JForm  $form  The form to be altered.
	 * @param   mixed  $data  The associated data for the form.
	 *
	 * @return  boolean
	 *
	 * @since   1.6
	 */

```

$data has a type of mixed. No question that this is not a brillant idea to have different types for a parameter but thats's how it is.

Closing not a bug

**Comment by ced1870** [comment]
ok I agree. Then we don't investigate more to change this ?
We just close it ... it's a shame<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16047">issues.joomla.org/tracker/joomla-cms/16047</a>.</sub>

**Comment by rdeutz** [comment]
You are free to make a pull request or open a ticket with a suggestion how to change it, this ticket gives the impression we have to fix a bug.

**Comment by ced1870** [comment]
ok Robert I understand :)
Then it is not a bug, but something we could improve (my 2 cents).

I will then investigate.
Thanks !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16047">issues.joomla.org/tracker/joomla-cms/16047</a>.</sub>
