### ISSUE TITLE
"Linked Titles" option in "Tagged Items" menu item

### ISSUE THREAD

**Issue by fluctuate** [joomla/joomla-cms#16049]
### Steps to reproduce the issue

Is possible to have "Linked Titles" option in the "Tagged Items" menu item ?
I so far did override on the com_tags template.

**Comment by brianteeman** [comment]
Submit a pull request with your proposed code and then it can be considered

**Comment by fluctuate** [comment]
Here  ?
https://github.com/joomla/joomla-cms/pulls<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16049">issues.joomla.org/tracker/joomla-cms/16049</a>.</sub>

**Comment by brianteeman** [comment]
yes thats right

**Comment by fluctuate** [comment]
Can you help me, please ?
Do i have to open a Pull Request between "staging and 3.8.dev" or "master and 3.8-dev" ?

Thank you

**Comment by brianteeman** [comment]
Staging

**Comment by brianteeman** [comment]
It has been several months since this issue was created without submission of any code.I am closing it at this time but it can always be reopened
