### ISSUE TITLE
[4.0] a11y typeahead and selects

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#16041]
There are a LOT of rules and guidelines for making accessible typeahead and selects. and we all have agreed that chosen sucks for this ;)

We can satisfy them all (or the vast majority of them depending on our implementation if we use https://alphagov.github.io/accessible-autocomplete/ 

![c--a0-4waaexajz](https://cloud.githubusercontent.com/assets/1296369/26078524/b9b35770-39b7-11e7-9394-4707fb43fb05.jpg)

I believe it satisfies our requirements and is under very active development from a major organisaation ( lol )

@dgt41

**Comment by dgt41** [comment]
Right now we have this: http://leaverou.github.io/awesomplete/ (**not** covering selects), 
but if the one that you are suggesting satisfies more requirements then let's swap them

**Comment by brianteeman** [comment]
From my reading the awesomplete is still very much a work in progress regarding accessibility

**Comment by brianteeman** [comment]
@dgt41 @C-Lodder Sorry I have no idea how to swap this in but it would definitely be an improvement on awesomplete
