### ISSUE TITLE
[com_fields] Hiding label does not work

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#16044]
### Steps to reproduce the issue
Create a Field in Context Mail
Hide the lable in the settings:

![image](https://cloud.githubusercontent.com/assets/828371/26097899/63962f1a-3a26-11e7-88cd-f5a7dd1595c3.png)

### Expected result
Label should be hidden in Form

### Actual result
Label is shown
![image](https://cloud.githubusercontent.com/assets/828371/26097925/7eac7a52-3a26-11e7-95ff-f088f5299279.png)

### System information (as much as possible)
latest staging

### Additional comments
didn´t test yet the fields in other context regarding this...

**Comment by brianteeman** [comment]
That is expected behaviour on a form. The hide label refers to when the field is rendered
<img width="315" alt="screenshotr10-01-25" src="https://cloud.githubusercontent.com/assets/1296369/26098123/9fae9f26-3a1e-11e7-91e7-fe24e23466e0.png">

So for example you have a field for adding a video. The label "video" would be displayed in the form view so you know what to put in the field but it would not be displayed when you render the video. 

As every field on a form requires a label this is the correct behaviour

**Comment by coolcat-creations** [comment]
Ok, thanks Brian... Means the Label should not appear in the mail the user gets, right? Have to test this...

**Comment by brianteeman** [comment]
That i dont know - I havent looked at mail forms and fields - only content

**Comment by laoneo** [comment]
If I'm not wrong, then there is also a parameter in `JFormField` if the label should be displayed in the form or not. Don't know if it would be a good idea to expose that to the UI?

**Comment by brianteeman** [comment]
If it is exposed then the options should be display/hidden with the label visually hidden from display and not removed. otherwise its an accessibility issue

**Comment by laoneo** [comment]
Then it would require a change in the layout as well https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/form/renderfield.php#L32

**Comment by brianteeman** [comment]
I did spend some time looking at this issue last week when comparing Joomla and Drupal accessibility and I noticed that for every field in drupal there is the option display/hidden for every label to understand the use case for having a field and not displaying the label. The only use case is when you have compound fields such as the date of birth field (shown below) or something similar like multiple fields for a name or address

![bootstrap-registration-form](https://cloud.githubusercontent.com/assets/1296369/26099495/ce3a2910-3a22-11e7-85cc-5b5d6d00cc03.jpg)

**Comment by laoneo** [comment]
Or when the definition of the field is clear, like the description in the article
![image](https://cloud.githubusercontent.com/assets/251072/26099663/b771e26e-3a2b-11e7-910c-2dc3ec9bf5a1.png)

**Comment by brianteeman** [comment]
That has a label - its "content" ;)

**Comment by brianteeman** [comment]
I am closing this at this time as expected behaviour

**Comment by laoneo** [comment]
This pr #17177 adds another parameter to the field if the label should be shown in the form.
