### ISSUE TITLE
[4.0] last popover

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#16056]
Tooltip/popup/popover whatever it is called is not positioned correctly when it is on the ID column at the end of the row. You will see from the pointer that it looks like it is referring to the previous column
<img width="311" alt="screenshotr18-21-56" src="https://cloud.githubusercontent.com/assets/1296369/26119361/da9a57c4-3a64-11e7-80ed-5b27dfebd48b.png">

**Comment by C-Lodder** [comment]
Beta 1 of BS uses `popper.js` as opposed to `tether.js` for the positioning of the tooltips so will wait till it's released before looking into it.

**Comment by dgt41** [comment]
Hopefully we won't use any of Bootstrap's js...

**Comment by mbabker** [comment]
Your dislike of anything which extends or uses jQuery doesn't need to be repeated on every issue and PR.  If we haven't figured it out by now, we aren't going to 😉

**Comment by FezVrasta** [comment]
@dgt41 by the way Popper.js doesn't make use of jQuery, if it makes you feel better 😉 Bootstrap is wrapping it with a thin jQuery layer.

**Comment by brianteeman** [comment]
Closed as this is resolved with bootstrap 4 beta
