### ISSUE TITLE
[4.0] sidebar collapse icon usability

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#16053]
three times tonight i have wondered why the "back" icon in the UI didnt work and didnt appear to do anything. Each time i eventually realised its not a back button at all but the icon representing the collapsed state of the sidebar - very frustrating - not even sure if it should be rendered at all in that view - as there is nothing to open or collapse and there is no state to represent

<img width="430" alt="screenshotr17-55-48" src="https://cloud.githubusercontent.com/assets/1296369/26118255/1d58782e-3a61-11e7-9ad2-cb267af27759.png">

**Comment by ciar4n** [comment]
True. This icon should be hidden unless we do suddenly make it a back button for the edit view. It seems natural to want to hit it to return to the previous screen and cancel the edit however I am not sure randomly changing the purpose of an icon is such a great idea.

**Comment by brianteeman** [comment]
when the sidebar is not present as on this view there is no need for the icon to display at all - thats probably the easiest option

**Comment by brianteeman** [comment]
Closed as there is a PR see #16303
