### ISSUE TITLE
Set default user-agent in httpclient

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#16057]
### Steps to reproduce the issue
Any http request in joomla, (like the updates finding and fetching) is done using an empty user-agent header in the HTTP request.
It's a common practice that several servers are blocking traffic from empty or unknown user-agents, to get protected from unknown bots.

### Suggested solution
Set a default user-agent either globally in the JHttp client or specifically to some basic processes like the requests of the updater.

**Comment by brianteeman** [comment]
Please see #15385 it sounds like that resolves the issue. If so please test

**Comment by sakiss** [comment]
Seems like #15385 solves the issue

**Comment by brianteeman** [comment]
please record your test on #15385 so that is can be merged

**Comment by zero-24** [comment]
> Seems like #15385 solves the issue

I would think we should keep this open as #15385 is just for the updater. Maybe we should append the default joomla user-agent per default to all calls?
