### ISSUE TITLE
[4.0] menu changes ?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#16055]
### Steps to reproduce the issue
In 3.7 to go to the contacts component I just go to component and then contacts
In 4.0 I have to go to components, contacts, contact

![37](https://cloud.githubusercontent.com/assets/1296369/26118758/ee9351ba-3a62-11e7-9a43-2a6edccb607a.gif)

![40](https://cloud.githubusercontent.com/assets/1296369/26118759/ee9df584-3a62-11e7-94a6-64467c10b8c4.gif)

**Comment by ciar4n** [comment]
Good point. I guess there is no reason why this cant now act the same as 3.7 since we are no longer using accordions. Currently clicking the 2nd level items leaves the 3rd level open which is just a behavior that carried through from the previous accordion menu.

**Comment by dgt41** [comment]
@ciar4n you suggested 2 small icons next to contacts in another issue, can we do it like this instead of the extra level?

**Comment by brianteeman** [comment]
@dgt41 that might be ok for core but for extensions not so good. especially as some of them have a LOT of submenus

**Comment by dgt41** [comment]
@brianteeman true :(

**Comment by brianteeman** [comment]
also we have the ability already to have an icon for all menu items - you can see it in action if you switch to the hathor template - no guarantee of course that extensions use an icon or even if all of core does at this time

**Comment by ciar4n** [comment]
Maybe we can change how the sub items are displayed with the addition of a class to the parent? So by default they appear as a dropout, add a class to the parent (Eg. `sub-items-inline`) and they appear inline with the parent.

**Comment by brianteeman** [comment]
the main point i was raising is that the top level link no longer works when it did in 3.x
