### ISSUE TITLE
[4.0] Multi purpose save button

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#16054]
_This is not about the purpose only the css_

If you look at the animation on chrome for windows you will see movement when the dropdown is active - seems to be just in chrome browser

![button](https://cloud.githubusercontent.com/assets/1296369/26118487/091d06b2-3a62-11e7-8702-a40f559a3da8.gif)

**Comment by C-Lodder** [comment]
wasn't this issue raised before somewhere?

**Comment by brianteeman** [comment]
yes by me in person to you but not on the tracker

**Comment by C-Lodder** [comment]
ah ok cool. Will also look into this when BS4-beta-1.

**Comment by brianteeman** [comment]
Closed as resolved with bootstrap 4 beta
