### ISSUE TITLE
Calendar form field reverts keyed input to saved value

### ISSUE THREAD

**Issue by paul-muckypuddle** [joomla/joomla-cms#16068]
### Steps to reproduce the issue

1. Open the Article Edit screen, click the Publishing tab
2. Click the Start Publishing field and select any date
3. Click outside the field to close the calendar window
4. Click the Start Publishing field and manually change the value using the keyboard
5. Click outside the field to close the calendar window
6. Click the Start Publishing field again - the value revert to its previous (non-keyed) value

### Expected result

Calendar field retains keyed in value

### Actual result

Calendar field reverts to previous value (as stored in `data-alt-value` attribute on the text input)

### System information (as much as possible)

Joomla 3.7
PHP 5.6

### Additional comments

The values are retained if you hit 'enter' after making changes as per step 4, but not if you just click away. This differs from Joomla 3.6.X

See video of issue in action at http://support-media.muckypuddle.me/kUe5

**Comment by dgt41** [comment]
@paul-muckypuddle this has been already fixed, please update to Joomla 3.7.1 (will be available later on today)

**Comment by zero-24** [comment]
closing as this is fixed with the upcomming release.

**Comment by paul-muckypuddle** [comment]
Good to hear, thanks.
