### ISSUE TITLE
New menu items land in the paper bin

### ISSUE THREAD

**Issue by sinasafarnezhadian** [joomla/joomla-cms#16066]
### Steps to reproduce the issue
I upgraded  from 3.6 to 3.7.
Now I cannot make a new menu item. They always land in the paper bin. I cannot even switch to hidden or public. They always switch to paper bin.

### System information (as much as possible)
Jommla 3.7

### Additional comments
I have 7 menus with approx. 4000 items all together.

**Comment by sinasafarnezhadian** [comment]
No ideas?

**Comment by franz-wohlkoenig** [comment]
if you give more System Information maybe someone can help easier if its a Core issue – also you have asked in [forums](https://forum.joomla.org/)?

**Comment by tonypartridge** [comment]
Hello,

if you create a new menu item and select published on save what happens?

Can you provide a screencast of the issue?

**Comment by wojsmol** [comment]
@sinasafarnezhadian Please run this query
`SELECT  `published` FROM  `#__menu` WHERE `alias` = 'root';`
Replace #__ with table prefix
@franz-wohlkoenig This can be a good test for #15806

**Comment by sinasafarnezhadian** [comment]
@tonypartridge 

it always switched to trash/paper bin (I dont know the right term).
Here is a screencast:
https://we.tl/vesdnZetkt
I cannot upload it here :/

@wojsmol 

I will try it today.

Thank You

**Comment by wojsmol** [comment]
@sinasafarnezhadian Please post result of this query here.

**Comment by sinasafarnezhadian** [comment]
@wojsmol here the result as img
![sql](https://cloud.githubusercontent.com/assets/4929670/26297829/f4b108fa-3ed4-11e7-9a77-7335360072e0.JPG)

**Comment by wojsmol** [comment]
@sinasafarnezhadian If you have backup before update then plase  test https://github.com/joomla/joomla-cms/pull/15806. On custom update serwer content  3.7.0 width https://github.com/joomla/joomla-cms/pull/15806 appyled. So after test you must chene update server to defout and update to 3.7.1.

**Comment by sinasafarnezhadian** [comment]
what if there is no Back up ? :)
Or the back up is no more up-to-date

**Comment by tonypartridge** [comment]
Then an update shouldn't have been preformed.

**Comment by wojsmol** [comment]
@sinasafarnezhadian Then run this queries
```SQL
UPDATE `#__menu` SET `published` = 1 WHERE `alias` = 'root';
UPDATE `#__categories` SET `published` = 1 WHERE `alias` = 'root';
```
replace #__ with database prefix then publish menuotems manuali
If you woth helpwith testing https://github.com/joomla/joomla-cms/pull/15806 then restore iven old backup localy run query from https://github.com/joomla/joomla-cms/issues/16066#issuecomment-302513245 if result is rhe same as in  https://github.com/joomla/joomla-cms/issues/16066#issuecomment-303026618 the test PR on this backup.

**Comment by sinasafarnezhadian** [comment]
@wojsmol thx for helping
UPDATE `#__menu` SET `published` = 1 WHERE `alias` = 'root';
that helps me.

I will test the old back up, as soon as I restore it.

**Comment by brianteeman** [comment]
I am closing this at this time - it can be opened if required but this does sound like a support issue for the forum and not a general bug for the tracker

**Comment by wojsmol** [comment]
In addition, the issue was fixed by PR https://github.com/joomla/joomla-cms/pull/15806
