### ISSUE TITLE
[UX] Button order in modal

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#16060]
### Steps to reproduce the issue
Create a menu item "SIngle Article" and click the button to "Create" a new article within it.
Or if you have a multilingual site check the association fields in an item, they have similar buttons.

### Expected result
The save buttons in the modal are in a consistent order like in regular forms.

### Actual result
The buttons are in reversed order

#### Regular form:
![buttonorder2](https://cloud.githubusercontent.com/assets/1018684/26124374/7e358124-3a7e-11e7-8e09-9858c1cbd6ba.PNG)

#### Modal form:
![buttonorder](https://cloud.githubusercontent.com/assets/1018684/26124389/873642f4-3a7e-11e7-84ab-cdbca20aeecf.PNG)

### Additional comments
I don't know if there was a reason to have the buttons in reversed order. I just noticed today and found it a bit unexpected.

**Comment by brianteeman** [comment]
It could be easily changed to.match but I am not so sure it is needed. In one case they are a toolbar and.in the other they are submit buttons on a form. So to me they are not the same thing so do not have to be consistent but I see no reason to prevent a change either

**Comment by Bakual** [comment]
Technically, they're the same, just in different places.
I can do a PR to reverse it but I'm not an UX guy and thus assumed there was a reason :)

**Comment by Bakual** [comment]
Pinging @andrepereiradasilva since it looks like this was done with #11830 (and related ones)

**Comment by infograf768** [comment]
I guess no special reason at looking at the original pr.
I also see no reason to change that as toolbar and modals are quite different things.

**Comment by brianteeman** [comment]
@bakual you are very very unlikely to get a reply from @andrepereiradasilva

**Comment by Bakual** [comment]
Looks like

**Comment by dgt41** [comment]
For what it's worth: in the mobile era the dominant buttons tend to lay on the right hand of the screen (easily accessed using one hand), but then again people in the community *still* believe that the admin area is not for mobiles...

**Comment by brianteeman** [comment]
And that assumes everyone is right handed. It's certainly not easier if you are left handed

**Comment by Bakual** [comment]
The admin area *can* be used with mobiles, but more often it is used on desktops. That's not only a believe.
I'm not saying it's wrong that it is on the right side. I just found it a bit confusing as the order is different in that new modal compared to a regular form ("old" modals had them left like the toolbar).

**Comment by brianteeman** [comment]
I am closing this based on the lack of any overwhelming reason to change it.
