### ISSUE TITLE
In TinyMCE edit a link target blank and No Follow switch back to Alternate

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-cms#16064]
### Steps to reproduce the issue
In a new article insert a text and with TinyMCE insert a link target blank and No Follow, try to edit the link and it appears in the TinyMCE window like Rel Alternate

### Expected result
edit a link target blank and No Follow no switch back to Alternate

### Actual result
edit a link target blank and No Follow switch back to Alternate

### System information (as much as possible)
3.7.1dev

### Additional comments

![link-editor3](https://cloud.githubusercontent.com/assets/1362388/26144453/c842b374-3ae0-11e7-8d81-5e5037feece9.gif)

**Comment by brianteeman** [comment]
looks like a tinmyce bug to me and nothing that we can do anything about

**Comment by brianteeman** [comment]
if you check the generated code the code is correct

**Comment by AlexRed** [comment]
yes, link I write: "it appears in the TinyMCE window like Rel Alternate"  
but in the code it is rel="nofollow noopener noreferrer"  and you can't set it "Alternate"

**Comment by brianteeman** [comment]
Closing as not a joomla core issue - please report it upstream to tinymce
