### ISSUE TITLE
deprecated function assignRef wrong description for a replacement

### ISSUE THREAD

**Issue by oe1tkt** [joomla/joomla-cms#16065]
### The issue
/libraries/legacy/view/legacy.php
inside comments (line 342) of `function assignRef` 
      
       * <code>
       * $view = new JView;
       *
       * // Assign by name and value
       * $view->assignRef('var1', $ref);
       *
       * // Assign directly
       * $view->ref = &$var1;
       * </code>

### Should be:
      
       * <code>
	 * $view = new JView;
	 *
	 * // Assign by name and value
	 * $view->assignRef('var1', $ref);
	 *
	 * // Assign directly
	 * $view->var1 = &$ref;
	 * </code>

### Reason:
Inside the code, it is:

    public function assignRef($key, &$val)
    { //...
			$this->$key = &$val;
     // ... 
    }

### Joomla core 3.7.0

for instance, a code snipped:

     		//deprecated: $this->assignRef('lists', $this->_lists); //changed to next line:
		$this->lists = &$this->_lists;

**Comment by brianteeman** [comment]
Could you submit a pull request to fix this please

**Comment by PhilETaylor** [comment]
PR #16137

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16137<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16065">issues.joomla.org/tracker/joomla-cms/16065</a>.</sub>

**Comment by brianteeman** [comment]
@philetaylor thanks but it would have been nice if you had waited a little while to give them time to contribute

**Comment by PhilETaylor** [comment]
WTF now you are blasting me for contributing? Get a life!
