### ISSUE TITLE
[com_fields] Error message when creating a field with a name already existing

### ISSUE THREAD

**Issue by stellainformatica** [joomla/joomla-cms#16070]
### Steps to reproduce the issue
Try to create a custom field (i.e. in contacts) that has the same name of a custom field created for another extension (i.e. contents).

### Expected result
The ideal would be to let creating custom fields with the same name, if they are associated to different extensions, but, if not possible, a message should explain better why that field already exists. 

### Actual result
 appears this message:
"Save failed with the following error: Another Field has the same name (remember it may be a trashed item)."

**Comment by stellainformatica** [comment]
See PR https://github.com/joomla/joomla-cms/pull/16069<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16070">issues.joomla.org/tracker/joomla-cms/16070</a>.</sub>

**Comment by zero-24** [comment]
closing as there is a PR. ;)
