### ISSUE TITLE
[com_fields] Media fields: Directory parameter not working properly

### ISSUE THREAD

**Issue by stellainformatica** [joomla/joomla-cms#16072]
### Steps to reproduce the issue
Create a custom field type Media for Users.
Leave the parameter Directory set to - Use Default -
From frontend with a registered user add an image to the profile.
In backend now change the parameter Directory selecting a directory from the drop down list
In frontend with the same previous user try to select another image and look the media popup

### Expected result
The user can now select or upload a photo in the directory set by the administrator

### Actual result
The user see the default directory as the first time.
This behaviour seems to be just for users that already uploaded an image.
The users uploading the image for the first time, correctly see the directory set by the administrator

**Comment by AlexRed** [comment]
I can confirm the problem in Joomla 3.7.1 Dev.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16072">issues.joomla.org/tracker/joomla-cms/16072</a>.</sub>

**Comment by Bakual** [comment]
The currently selected folder imho is stored in the user session. So as long as the user doesn't close his browser, he will have the folder selected that he last opened, regardless of any setting in the field.
If he closes the browser and tries again with a fresh session, he should see the new default folder.

**Comment by AlexRed** [comment]
Not for me, in my test also if I use a different Browser I see the wrong old folder.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16072">issues.joomla.org/tracker/joomla-cms/16072</a>.</sub>

**Comment by ghost** [comment]
closed as duplicate Report #16413
