### ISSUE TITLE
[com_fields] JS Error on Subform

### ISSUE THREAD

**Issue by Sporedd** [joomla/joomla-cms#16073]
### Steps to reproduce the issue
Clean install of Joomla
Create a plugin to add extra fields with a subform
Add a new row to the subform

### Expected result
An additional row without JavaScript errors

### Actual result
The new row is added, but with a javascript error:
![image](https://cloud.githubusercontent.com/assets/3438698/26152488/6ae69d86-3b07-11e7-9b22-e90540cc7b47.png)

### System information (as much as possible)
PHP Built On	Windows NT BURO26-JESPER 6.2 build 9200 (Windows 8 Professional Edition) i586
Database Version	5.5.5-10.1.10-MariaDB
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.19
Web Server	Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.19
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.7.0 Stable [ Amani ] 25-April-2017 15:36 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) 
Chrome/58.0.3029.110 Safari/537.36
This occurs in all browsers

xml of plugin:
extravelden.xml
`   <field
                    name="imgSelector"
                    type="subform"
                    multiple="true"
                    formsource="plugins/content/extravelden/form/imgselector.xml"
                    description="Selecteer afbeeldingen en info zoals titel, subtitel en omschrijving."
                    label="Selecteer afbeeldingen en info"
                    layout="joomla.form.field.subform.repeatable-table"
            `>

imgselector.xml
`
    <field
            name="multiple_img_image"
            type="media"
            label="Afbeelding"
    />
    <field
            name="multiple_img_title"
            type="text"
            label="Afbeelding titel"
    />
`

### Additional comments
If needed i can create a  plugin with a subform, but im thinking someone has that standing ready?

The javascirpt error is a problem because i want to fill the subform row with javascirpt.

**Comment by PhilETaylor** [comment]
is `<f-orm>` a typo?

Can you provide the whole installable plugin to save time for people trying to replicate the issue?

**Comment by Sporedd** [comment]
no, thats to prevent the browser from hiding the tag :)

installer for the plugin:
[extravelden.zip](https://github.com/joomla/joomla-cms/files/1007717/extravelden.zip)

**Comment by PhilETaylor** [comment]
After installing and enabling that plugin, I get a 404 error on a missing JS file 

`http://joomla-cms/media/plg_extravelden/multipleFiles.js 404 (Not Found)`

And then when going to edit an article I get 

`Unknown column 'isproject' in 'field list'`

I cannot replicate the error you are reporting with the plugin provided in Joomla 3.7.1

**Comment by Sporedd** [comment]
The missing JS is not relevant, Could u try it with a new article.
I'll cleanup the plugin in the meanwhile

**Comment by PhilETaylor** [comment]
When I try to create a new article I get nothing but an error on the page! 

`Unknown column 'isproject' in 'field list'`

**Comment by Sporedd** [comment]
Ah oke, i tested it and it seemed to work, ill upload the new plugin in a sec

**Comment by PhilETaylor** [comment]
> Joomla! Version	Joomla! 3.7.0 Stable [ Amani ] 25-April-2017 15:36 GMT

Please download and test Joomla 3.7.1 RC 2 (or wait a few hours and test Joomla 3.7.1)

**Comment by PhilETaylor** [comment]
Maybe even test https://github.com/joomla/joomla-cms/pull/15848 which is merged already for Joomla 3.7.1

**Comment by Sporedd** [comment]
Just updated to 3.7.1 - RC2, the error doesn't seem te persist here.

I'll update the live in a few hours and get back here with the result

**Comment by zero-24** [comment]
> I'll update the live in a few hours and get back here with the result

Please install on the live site the 3.7.1 package to be release on 14:00 UTC as this is a important sec release and not the RC as the RC does not include the sec paches!

**Comment by Bakual** [comment]
The `subform` formfield type doesn't work with com_fields. That is true, That is why this field type doesn't exist in core.
So if you create a plugin to implement that field type, you need to solve this in your plugin.

**Comment by Sporedd** [comment]
I installed the just released 3.7.1 version of joomla. and i can confirm this problem is fixed.

Thanks for your time!
