### ISSUE TITLE
[com_fields]  Permissions not working in media field

### ISSUE THREAD

**Issue by stellainformatica** [joomla/joomla-cms#16075]
### Steps to reproduce the issue
Create a custom field type Media.
In Permissions select the group Registered and set to Allowed the action "Edit Custom Field Value"
With a user of the group registered try go in frontend, edit the profile and click the Select button to upload a photo. 

### Expected result
The media modal opens correctly showing the media directories

### Actual result
The modal opens, but swoes an error 403

### Additional comments
If you try with a user with higher permissions that registered (i.e. Author) the modal correctly shows the media directories

**Comment by AlexRed** [comment]
I can confirm the problem in Joomla 3.7.1 dev.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16075">issues.joomla.org/tracker/joomla-cms/16075</a>.</sub>

**Comment by brianteeman** [comment]
i would think that is the expected behaviour as the modal has a permission requirement higher than registered by default

**Comment by brianteeman** [comment]
I am closing this as the expected behaviour
