### ISSUE TITLE
Menu reset in filter after creating new menu item

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#16079]
### Steps to reproduce the issue
I have a menu with about 40 items. I go to Menus > My menu and see list of items:
![screen shot 2017-05-17 at 15 48 29](https://cloud.githubusercontent.com/assets/3432048/26154505/607cfd7a-3b18-11e7-83d3-1304be8041de.png)

After creating new menu item I returning to the list of all items and no menu is selected:
![screen shot 2017-05-17 at 15 49 57](https://cloud.githubusercontent.com/assets/3432048/26154550/9bce9956-3b18-11e7-9e56-5cf70ee5ada7.png)

That's very comfortless when you create mass menu items.

### Expected result
After creating new menu item we must be returned to the same menu.

### Actual result
I returning to All menu items.

### System information (as much as possible)
Joomla 3.7.0
PHP Version	7.0.17

**Comment by franz-wohlkoenig** [comment]
closed as duplicate Report #15447<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16079">issues.joomla.org/tracker/joomla-cms/16079</a>.</sub>
