### ISSUE TITLE
Can't upload PDF files through Media Manager or Ark Media Manager

### ISSUE THREAD

**Issue by freshlookweb** [joomla/joomla-cms#16087]
### Steps to reproduce the issue

Go to Media Manager, upload PDF, I get an error message

### Expected result

File should be uploaded successfully

### Actual result

It doesn't upload. Error - Illegal or invalid mime type detected.

### System information (as much as possible)

3.7.1, php 7

**Comment by PhilETaylor** [comment]
Duplicate of #16086
