### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by RenniePet** [joomla/joomla-cms#16095]
### Steps to reproduce the issue

Take a look at https://docs.joomla.org/Copying_a_Joomla_website

### Actual result

About half way down, it says, "It needs to be UTF8 (utf8_generic_ci)."

### Additional comments

I think that should be "utf8_**general**_ci".

**Comment by Sandra97** [comment]
It's a Wiki, meaning all users are maintainers. Feel free to udpate it yourself.

**Comment by RenniePet** [comment]
OK, done.

But you sure don't make it easy. Why not use the same authentication as the main Joomla website? And it took me three tries to beat the captcha thing, which I maintain can be misunderstood if you tend to think, um, differently.

**Comment by RenniePet** [comment]
And I can see the same error in the French, Spanish and Dutch versions, and I apparently don't have editing rights there.

**Comment by franz-wohlkoenig** [comment]
closed as no Core issue. Thanks for reporting and helping, @RenniePet.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16095">issues.joomla.org/tracker/joomla-cms/16095</a>.</sub>
