### ISSUE TITLE
3.7.1 error creating new user publisher

### ISSUE THREAD

**Issue by joo7** [joomla/joomla-cms#16093]
### Steps to reproduce the issue
create new user, set publisher, save&close

### Expected result
ok

### Actual result
0 Call to a member function addRecipient() on boolean 

### System information (as much as possible)

tested local and on demojoomla.com

### Additional comments

tested local and on demojoomla.com

**Comment by PhilETaylor** [comment]
Cannot replicate. 

My user saved fine.

Are you sure you provided a valid 

Please DON'T do testing on https://demo.joomla.org/ Its a customised version of Joomla provided by SiteGround.

**Comment by Flowman** [comment]
Get the same issue when i create a user in demojoomla.com

![image](https://cloud.githubusercontent.com/assets/212680/26185418/75b2a0dc-3bbd-11e7-94ef-bea1e0b82890.png)

**Comment by PhilETaylor** [comment]
Like I said - DONT test on the Joomla demo domains- that is a CUSTOMISED VERSION of Joomla provided by SiteGround

Please test on KNOWN entities - like your own websites on a normal webhost, or locally in a development evnvironment.

**Comment by sharphosting** [comment]
Can't replicate here either, creating a new user assigned to the "Publisher" group works fine on 3.7.1.

I tried not providing a valid email address, username or name gives a warning to say so rather than the error reported.

Are you sure you have all the steps listed accurately? It works fine for me with the ones you have listed, but they're not complete as they don't include setting the above fields as @PhilETaylor points out.

**Comment by franz-wohlkoenig** [comment]
closed as no Core Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16093">issues.joomla.org/tracker/joomla-cms/16093</a>.</sub>

**Comment by joo7** [comment]
I can reproduce the issue on webhost https://www.mittwald.de ,
valid email and other fields.

System info:

PHP Built On 	Linux s1112 2.6.32.71-kvm-32cpu-06 #1 SMP Fri Dec 2 15:35:31 CET 2016 x86_64
Database Version 	5.7.17-11
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.1.1
Web Server 	Apache
WebServer to PHP Interface 	fpm-fcgi
Joomla! Version 	Joomla! 3.7.1 Stable [ Amani ] 17-May-2017 14:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0

**Comment by franz-wohlkoenig** [comment]
reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16093">issues.joomla.org/tracker/joomla-cms/16093</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Can't confirm Issue.
### System information
3.7.1
macOS Sierra, 10.12.4
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15 and 7.1.1
- MySQLi 5.6.35

**Comment by joo7** [comment]
Can't reproduce issue on host https://www.schwarzkuenstler.com

PHP Built On 	Linux srv16.schwarzkuenstler.info 2.6.32-042stab120.19 #1 SMP Mon Feb 20 20:05:53 MSK 2017 x86_64
Database Version 	5.6.35
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.0.19
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.7.1 Stable [ Amani ] 17-May-2017 14:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0

**Comment by joo7** [comment]
I tryed "Reinstall Joomla core files" on host mittwald, issue is still there, 
anything else I can test?

**Comment by newdudeldu** [comment]
When I want to create a new user on 3.7.1, I get: 
ERR_CONTENT_DECODING_FAILED

using
PHP-Version	7.0.11
Webserver	Apache
PHP-Interface für den Webserver	fpm-fcgi
Joomla!-Version	Joomla! 3.7.1 Stable [ Amani ] 17-May-2017 14:00 GMT
Joomla!-Plattform-Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Browsererkennung	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by PhilETaylor** [comment]
> ERR_CONTENT_DECODING_FAILED

That is NOTHING to do with this at all. 

This is because you have GZIP enabled in Joomla Global Config, but your server is also encoding the output. 

Disabled GZIP in Joomla Global Configuration as you dont need it on your server which is already encoding the output.

**Comment by newdudeldu** [comment]
OK I did that and user registration works.

But why does this happen only now (didn't happen before) and only there (other editing fields worked correctly?

**Comment by joo7** [comment]
I found the reason for this issue at mittwald (https://issues.joomla.org/tracker/joomla-cms/11131):
Empty field "From Email" in global configuration - Server - Mail Settings.

**Comment by PhilETaylor** [comment]
Well that would have been obvious to me that this needs setting to send email...

**Comment by joo7** [comment]
Thank you for support and sorry for wasting your time, it is not my site, I always fill in an email on installation, a clearer error message would be nice...

**Comment by PhilETaylor** [comment]
I can now replicate this by removing the From Address in Joomla Global Config.

>  Call to a member function addRecipient() on boolean

**Comment by mbabker** [comment]
You do realize turning on debug mode will give a stack trace to the error, right?

**Comment by PhilETaylor** [comment]
> You do realize turning on debug mode will give a stack trace to the error, right?

I do yes, I doubt the others above are developers :) 

PR to test #16107

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16107<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16093">issues.joomla.org/tracker/joomla-cms/16093</a>.</sub>

**Comment by PhilETaylor** [comment]
Im starting to think @franz-wohlkoenig is a robot.. he is far too fast to be a human...
