### ISSUE TITLE
Suggested Update: Link to Release Notes in Update Email

### ISSUE THREAD

**Issue by sharphosting** [joomla/joomla-cms#16090]
It was useful to receive the "Joomla! Update available..." email from my installation just now. I wonder if it would be better to also include a link to the release notes? It's generally not a good idea to just install an update without at least reviewing them, although that is what the email implies when the only suggested action is to click the link to install the update. Perhaps before that, just under the "UPDATE INSTRUCTIONS" title, there could be something like:

```
Review the release notes at:
....
```

Perhaps with better wording saying why that is a good idea. I for one would find this useful, and it suggests a more sensible approach to site updates to all who receive them.

**Comment by brianteeman** [comment]
Sounds a good idea to me and would encourage best practice.

**Comment by brianteeman** [comment]
@zero-24 is this something you can do? You know this area of code the best I think

**Comment by zero-24** [comment]
We have no information where the release notes are. Just the info URL which can include the releasenotes. So we need to say something like: "you can find additional infos to the update here "

Can you extend the text by using the [INFOURL] placeholder where the URL should go in @brianteeman

**Comment by sharphosting** [comment]
I wondered if that might be the case (link to release notes not available with the data). Perhaps a link to release news could be useful:
https://www.joomla.org/announcements/release-news/

**Comment by zero-24** [comment]
Correct. Than I would go with the generic link.

**Comment by brianteeman** [comment]
@zero-24.if you do a pr.i will check the English if needed

**Comment by zero-24** [comment]
see #16170 Closing here.
