### ISSUE TITLE
Amp issue in fold out menu when not using SE Friendly URLs

### ISSUE THREAD

**Issue by DonPedro34** [joomla/joomla-cms#16092]
### Steps to reproduce the issue

Installed 3.7.1 on development site.
Menu with submenu will not fold out on Click. If i remove the added "amp;" from URL and reload the page, the submenu folds out correctly, any click on those entries produces a new URL with amp; and the  submenus disappears again.

When Search Engine Friendly URLs are Used - the issue is gone.

### Expected result

https://somewebsite.com/cms/index.php?option=com_content&view=category&id=467&Itemid=329

### Actual result

https://somewebsite.com/cms/index.php?option=com_content&amp;view=category&amp;id=467&amp;Itemid=329

### System information (as much as possible)

Update joomla 3.7.1
PHP version 5.6.29-nmm1

### Additional comments

I can't rollout this important Security issue update on out live system until this "amp;" issue is fixed.
Navigation on Site is impossible.

**Comment by PhilETaylor** [comment]
Duplicate of https://github.com/joomla/joomla-cms/issues/16088 and PR already for testing https://github.com/joomla/joomla-cms/pull/16089
