### ISSUE TITLE
Help screens report 3.6

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#16108]
### Steps to reproduce the issue
click on any help

### Expected result
page title is 3.7

### Actual result
page title is 3.6

### System information (as much as possible)
joomla 3.7.1

### Additional comments

![sg](https://cloud.githubusercontent.com/assets/1296369/26203525/881ad04e-3bd3-11e7-98f7-ba0e2d44c31e.gif)

**Comment by PhilETaylor** [comment]
Im pretty sure I raised this before and was told there was a reason for it, but I cant find the link now... grrrr

**Comment by mbabker** [comment]
You're probably of thinking of before 3.7 being released since at that point the Help37 namespace in the docs was just an alias to Help36.

**Comment by PhilETaylor** [comment]
> You're probably of thinking of before 3.7 being released 

Yup. That.

**Comment by brianteeman** [comment]
So who can help to fix this - some screens are at 3.7 and others at 3.6

![help](https://cloud.githubusercontent.com/assets/1296369/26258743/efac4c84-3cbd-11e7-9cd8-ce3912774b92.gif)

**Comment by Sandra97** [comment]
@Hutchy68 You're the one who can help with this.

**Comment by brianteeman** [comment]
@Sandra97 has this been fixed?

**Comment by franz-wohlkoenig** [comment]
@Sandra97 Some Screens are 3.7 (Articles) some 3.6 (Fields).

**Comment by Sandra97** [comment]
No, it's not fixed. I'll ask Tom to see that issue.

**Comment by brianteeman** [comment]
Any update on this @Sandra97

**Comment by Hutchy68** [comment]
Working on it, some have been fixed, some might have been fixed but cache is still showing until it clears, some might have been missed. 

Also looking at a permanent fix to keep it from happening in future. All tied to way translations are stored.

**Comment by brianteeman** [comment]
Can you update here when it is fixed please

**Comment by Hutchy68** [comment]
Fixed

**Comment by brianteeman** [comment]
Thank you
Closed
