### ISSUE TITLE
Feed url seems incorrect (J3.7.1) when Adds Suffix to URL is on

### ISSUE THREAD

**Issue by ramblerswebs** [joomla/joomla-cms#16101]
### Steps to reproduce the issue
If I turn on Adds Suffix to URL in Global Config then the module Syndication Feeds 
gives a url of the form
http://www.ramblers-webs.org.uk/support/support-issues.feed?type=rss
If I turn Adds Suffix to URL the feed url becomes
http://www.ramblers-webs.org.uk/support/support-issues?format=feed&type=rss

The first url does not work , the second one does

### Expected result
http://www.ramblers-webs.org.uk/support/support-issues?format=feed&type=rss

**Comment by ggppdk** [comment]
It is a known issue: https://github.com/joomla/joomla-cms/issues/7459
See an explanation for this here: https://github.com/joomla/joomla-cms/issues/7459#issuecomment-122541277

You have a 3rd system plugin that is forcing JDocument creation at an "early" stage,
 usually by calling JHTML method (e.g. to load some CSS / JS file)
and this happens before the suffix has been examined and set into the Request data

You can contact the author of the plugin (**if you find the plugin**), and ask them to move their code to a later event e.g. onBeforeCompileHead

**Comment by franz-wohlkoenig** [comment]
closed as known Issue #7459<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16101">issues.joomla.org/tracker/joomla-cms/16101</a>.</sub>
