### ISSUE TITLE
Wrong rooting after editing menu items others than main menu in backen

### ISSUE THREAD

**Issue by some1new** [joomla/joomla-cms#16106]
### Steps to reproduce the issue

Set up new menu item in other menu than main menu

### Expected result

should stay in that menu after saving

### Actual result

Menu display jumps to main menu after saving new items in other menus

### System information (as much as possible)

Joomla 3.7.1, PHP 5.6.29-nmm1

**Comment by PhilETaylor** [comment]
Already fixed - read the FAQ at https://docs.joomla.org/J3.7.1:Non_SEF_Urls_Broken

**Comment by franz-wohlkoenig** [comment]
closed as duplicate Report #15447<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16106">issues.joomla.org/tracker/joomla-cms/16106</a>.</sub>
