### ISSUE TITLE
Calendar is not showing week number in Joomla! 3.7.1

### ISSUE THREAD

**Issue by brianronnow** [joomla/joomla-cms#16102]
### Steps to reproduce the issue
Using the Calendar from modules do not show week numbers only dates

### Expected result
To show week numbers and dates.

### Actual result
Only shoing the weekdays

### System information (as much as possible)
Joomla! 3.7.1
PHP 7.0.14

**Comment by infograf768** [comment]
adding `weeknumbers="true"` in the module.xml would solve this.
Making a PR now

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/16104

**Comment by dgt41** [comment]
@brianronnow may I ask why you need the week numbers in the modules?

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16104<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16102">issues.joomla.org/tracker/joomla-cms/16102</a>.</sub>
