### ISSUE TITLE
Featured Articles stay public

### ISSUE THREAD

**Issue by some1new** [joomla/joomla-cms#16103]
I have several articels as featured. Some are displayed for guests only and some for registered.

After update from 3.6.5 to 3.7.1 all featured articles are displayed regardless of user access level-

**Comment by brianteeman** [comment]
i cant think of anything in the update that would do that

if you go to the article manager are they still set with the correct access level?
if they are then please check with one of the default templates - if it works thenit is an error in a template override

**Comment by PhilETaylor** [comment]
Cannot replicate

 - installed Joomla 3.7.1
 - Created menu link to featured articles
 - made articles featured and Registered
 - Clicked menu link to featured articles when logged out (public) 
 - No articles shown.

**Comment by some1new** [comment]
switched to protostar and beez3, still the same featured articles as guest AND registered appear on start page<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16103">issues.joomla.org/tracker/joomla-cms/16103</a>.</sub>

**Comment by sharphosting** [comment]
Have you tried from a different browser? Perhaps you have "Shared Sessions" enabled when you didn't previously, and it's just because you're logged in to the admin.

**Comment by some1new** [comment]
Please see this

http://prntscr.com/f9e8mu

settings as featured articles for both of them
http://prntscr.com/f9eagh

can be seen on www.talking-business.de/de



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16103">issues.joomla.org/tracker/joomla-cms/16103</a>.</sub>

**Comment by compojoom** [comment]
I had a look at the website. The "Show Unauthorised Links" option was set to yes. And since all the article content was in the intro text we were seeing the whole article. No idea why it was working on 3.6.5, but it actually should have been the same...

**Comment by brianteeman** [comment]
That makes perfect sense and iirc this is because of a bug fix to correct the behaviour to the one you have now. I am closing this now.
