### ISSUE TITLE
Module Style dropdown overlap with footer

### ISSUE THREAD

**Issue by Ekta-yadav** [joomla/joomla-cms#16100]
### Steps to reproduce the issue
1.Login into Joomla Administrator :
2.Extensions -> Modules -> Advanced -> Module style dropdown overlaps with footer (if there is more options)

### Expected result
Module style dropdown doesn't overlap with footer 

### Actual result
Module style dropdown doesn't overlap with footer 

### System information (as much as possible)
Joomla 3.7.1
PHP 7![screen shot 2017-05-18 at 06 59 03](https://issues.joomla.org/uploads/1/4ea44a155d77bbe17583032e462d6144.jpg)

**Comment by franz-wohlkoenig** [comment]
I didn't see this as Issue. A Dropdown is primary to show as user has set this Action.

**Comment by Ekta-yadav** [comment]
T least ther should be margin from bottom so that the dropdown be visible clearly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16100">issues.joomla.org/tracker/joomla-cms/16100</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Its visible by scroll up. Showing always Footer reduce Dropdown-Values to show, but thats what user clickes for: Show Values.

**Comment by brianteeman** [comment]
i am closing this as it is not solvable in the way that you desire. there is no way to change the size of the view based on the content of a select
