### ISSUE TITLE
LDAP Plugin no longer works

### ISSUE THREAD

**Issue by abel408** [joomla/joomla-cms#16111]
### Steps to reproduce the issue
Upgrade to > 3.7
Attempt to log in with LDAP credentials

### Expected result
LDAP plugin successfully authenticates user

### Actual result
404 error page, user does not authenticate

### System information (as much as possible)
I've had this issue with all 4 websites that I've upgraded. Problem started when I upgraded to 3.7 from 3.6.5. Server is running Ubuntu 16.04 and php7

**Comment by brianteeman** [comment]
Sounds the same as the redirect on login issue reported elsewhere and not
specifically for ldap - not at my desk to search for the exact issue number

**Comment by abel408** [comment]
I am able to log in with a Joomla user though.

**Comment by PhilETaylor** [comment]
When did you upgrade to PHP 7.x ?

**Comment by PhilETaylor** [comment]
What is the exact URL you get a 404 error page on? does it have `&amp;amp;` in it?

**Comment by PhilETaylor** [comment]
What EXACT Joomla version are you running? Please download and attach your system information using the button in Joomla System Information page in admin.

**Comment by abel408** [comment]
I performed the upgrade to PHP 7 during the same time as the upgrade to Joomla 3.7.

This is the URL that I get redirected to after I attempt to log in from an LDAP account:
https://mydomain.com/index.php?option=com_users&task=user.login&Itemid=150

When I log in as a Joomla user, I get authenticated successfully and get redirected to my profile page: https://mydomain.com/index.php?option=com_users&view=profile&Itemid=112

I'm using the login form menu type to log in, but I've also tried using the direct url (index.php?option=com_users&view=login) with the same outcome.

I am on 3.7.1 now

System Information:

 
PHP Built On	Linux media 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64
Database Version	5.7.18-0ubuntu0.16.04.1-log
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.15-0ubuntu0.16.04.4
Web Server	Apache/2.4.18 (Ubuntu)
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.7.1 Stable [ Amani ] 17-May-2017 14:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by abel408** [comment]
I'm currently having this issue with all of my sites and users are complaining. Can I get an update to this issue? Do you need any more information?

**Comment by PhilETaylor** [comment]
Quite frankly I never had the time (or energy) to set up a LDAP server and all the prerequisites in an attempt to replicate the issue. 

> I performed the upgrade to PHP 7 during the same time as the upgrade to Joomla 3.7.

Are you sure you have correctly installed PHP7 with all the required extensions for PHP 7 that are needed for LDAP to work?

>  Please download and attach your system information using the button in Joomla System Information page in admin.

I asked you to do that, and you still have not done that. Maybe I was not clear, in Joomla 3.7.1 there is a "Download as text" button on teh system information page, this is what I wanted you click, and provide the resultant file, this contains more PHP information on which I can make an educated guess of what your problem might be.

![screen shot 2017-05-22 at 18 18 11](https://cloud.githubusercontent.com/assets/400092/26320604/44915bf4-3f1b-11e7-8f46-9bf2888545f0.png)

Im "guessing" if you move back to your old PHP version (which was correctly configured) Im "guessing" that the LDAP will work. 

Im "guessing" that your PHP 7 is missing extensions, and as there is frequent error suppressor use in [ldapclient.php](https://github.com/joomla/joomla-cms/blob/f3c49e42e2a455247898fc66e26d8f202844ac08/libraries/vendor/joomla/ldap/src/LdapClient.php) (the @ sign) that the errors are being hidden.

**Comment by PhilETaylor** [comment]
Or maybe it was this merge https://github.com/joomla/joomla-cms/pull/13938 which was merged without any testing at all :( @mbabker @wilsonge

**Comment by PhilETaylor** [comment]
> @brianteeman Sounds the same as the redirect on login issue reported elsewhere and not
specifically for ldap 

Yup could be that too, both, or specifically. but the guy says logging in as a Joomla user is fine... so maybe not :(

**Comment by mbabker** [comment]
I'm not going to speak on merge policy, but the Framework package class and the CMS class were line for line the same minus the private properties being renamed to remove the underscore prefix.  So the simple act of that change should not have caused this issue.

**Comment by PhilETaylor** [comment]
> I'm not going to speak on merge policy, but the Framework package class and the CMS class were line for line the same minus the private properties being renamed to remove the underscore prefix. So the simple act of that change should not have caused this issue.

Like I said, it was a wild guess :)

**Comment by abel408** [comment]
@PhilETaylor you are correct. I was missing the php7-ldap package. I'm sorry. Odd that I couldn't find any logs indicating that.
