### ISSUE TITLE
3.7.1 error upload pdf via media

### ISSUE THREAD

**Issue by joo7** [joomla/joomla-cms#16119]
### Steps to reproduce the issue
content -> media -> upload test.pdf

### Expected result
ok

### Actual result
Error
Illegal or invalid mime type detected.

### System information (as much as possible)
tested 2 live sites 3.7.1
no issue before update from 3.6.5
no changes in options

### Additional comments
default settings in options:

Legal Extensions (File Types)
bmp,csv,doc,gif,ico,jpg,jpeg,odg,odp,ods,odt,pdf,png,ppt,swf,txt,xcf,xls,BMP,CSV,DOC,GIF,ICO,JPG,JPEG,ODG,ODP,ODS,ODT,PDF,PNG,PPT,SWF,TXT,XCF,XLS

Legal MIME Types
image/jpeg,image/gif,image/png,image/bmp,application/x-shockwave-flash,application/msword,application/excel,application/pdf,application/powerpoint,text/plain,application/x-zip

Illegal MIME Types
text/html

**Comment by brianteeman** [comment]
please see and test #16091
