### ISSUE TITLE
Repeatable is no longer rendered with Chosen layout

### ISSUE THREAD

**Issue by roland-d** [joomla/joomla-cms#16110]
### Steps to reproduce the issue
Using a subform in Joomla 3.6.5 a list is rendered using Chosen but since the update to Joomla 3.7.1 from Joomla 3.6.5 the list is no longer rendered using Chosen causing a layout problem. See the attached screenshot that shows what actually happens.

### Expected result
After updating to Joomla 3.7.1 the select list is rendered the same as in Joomla 3.6.5

### Actual result
The subform select list is rendered in a different an unusable way.

### System information (as much as possible)
Joomla 3.7.1
PHP 7.0.10 (tested with different servers)

### Additional comments
@Fedik I guess this is in your area of expertise

![subform-difference](https://cloud.githubusercontent.com/assets/359377/26204528/4b6bf8ce-3bdf-11e7-8ab7-75c8d5d7baad.png)

**Comment by Fedik** [comment]
it not "subform" but "repeatable" field 😉 
I guess it happened after this #15042 fix 😄

**Comment by roland-d** [comment]
@Fedik Correct, it is repeatable, always mix them up. Adjusted title to reflect that.

**Comment by roland-d** [comment]
@wilsonge It is correct that #15042 broke the repeatable fields. Using the repeatable.js from 3.6.5 fixed the display. Can you have a look at it?

**Comment by wilsonge** [comment]
As @Fedik wrote the patch for #15042 can I leave it in his hands?

**Comment by roland-d** [comment]
@wilsonge LOL, I thought you wrote it but you just merged it ;) @Fedik is fine by me

**Comment by Fedik** [comment]
quick fix is to set size="4" (or other number) to `<select>` with multiple="true",
it how native multi-select works 😉 

And Chosen.js in repeatable field I will check later

**Comment by Fedik** [comment]
@roland-d please test #16471

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16471<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16110">issues.joomla.org/tracker/joomla-cms/16110</a>.</sub>
