### ISSUE TITLE
Calendar shows wrong weekdays since 3.7

### ISSUE THREAD

**Issue by poca2k** [joomla/joomla-cms#16122]
### Steps to reproduce the issue
Since the 3.7 update, when i go to an article and pick a publish date, the weekdays are wrong, in the picture you can see that may 19 is shown as a saturday(sab) and it should be friday(sex), already updated it to 3.7.1 and its still the same.

**Comment by franz-wohlkoenig** [comment]
Can't confirm Issue. Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding.

**Comment by brianteeman** [comment]
what language is your site using

**Comment by ot2sen** [comment]
Does look like pt-PT and pt-BR both have this issue.
![19-05-2017_pt_br_and_pt_sab](https://cloud.githubusercontent.com/assets/790445/26244173/0231ed52-3c8f-11e7-91cd-723898714017.png)

Whether it is a week start issue with joomla or packages issue I havent looked into

**Comment by brianteeman** [comment]
looks like #16048

**Comment by infograf768** [comment]
No issue in French where we use:
```
<firstDay>1</firstDay>
		<weekEnd>0,6</weekEnd>
```
![screen shot 2017-05-19 at 12 41 31](https://cloud.githubusercontent.com/assets/869724/26244622/b3c0bf52-3c90-11e7-9d2a-f4d8783a1734.png)

Code has been corrected in pt by
https://github.com/joomla/joomla-cms/blob/staging/media/system/js/fields/calendar-locales/pt.js

**Comment by brianteeman** [comment]
I am closing as Portuguese has been fixed
