### ISSUE TITLE
Sub categories 403 error on categories list.

### ISSUE THREAD

**Issue by rajmohanvy** [joomla/joomla-cms#16120]
Hi 

The Categories listing on front have issue. In the "content" category list the HBS and Count HBS sub categories can't access by current user karthick please find categories screen shot and Frond end.
If i click on those categorys(HBS,Count HBS) is going to 403 page. My question is before 3.6 those sub category not listed in front end why 3.7 version of joomla is listing non access categories in front end. 

![front-end](https://cloud.githubusercontent.com/assets/27351166/26239824/44f137bc-3c9c-11e7-96c1-11cafc55e2f5.png)
![user](https://cloud.githubusercontent.com/assets/27351166/26239825/44f38468-3c9c-11e7-907a-66bc986956b5.png)
![categories](https://cloud.githubusercontent.com/assets/27351166/26239826/44f6c15a-3c9c-11e7-8efb-e7805cbb32a5.png)

PHP : 7.0
Joomla : 3.7.0

**Comment by brianteeman** [comment]
in the menu option check the setting of show unauthorised links

**Comment by brianteeman** [comment]
Also check the setting for show empty categories

**Comment by rajmohanvy** [comment]
@brianteeman 

The empty categories is not an issue and show Unauthorised Links is set :  No . But still not working.

**Comment by rajmohanvy** [comment]
@brianteeman

Any idea.

**Comment by tonypartridge** [comment]
@rajmohanvy did you resolve this? 

I have created a new category and set as a sub category of Blog category, restricted this to special and I don't see this as a sub category in the frontend. 

I suspect this is an issue as to how your Access Levels are setup. Please make sure only the groups allowed to see the articles / categories are selected within each access level.

**Comment by ImagesbyMurray** [comment]
I'm having the same issue - started with 3.7.1.....

I've changed child category permissions to just SuperUser, but the category still shows in Category List View.  I've toggled Menu | Options | Show Unauthorised Links to NO - no difference

![category-permission](https://user-images.githubusercontent.com/29714154/27554536-8f5b5d3e-5a63-11e7-8d45-6896a69015c4.PNG)
![category-list](https://user-images.githubusercontent.com/29714154/27554541-95b23bda-5a63-11e7-929d-7b647c1e809c.PNG)
![category-result](https://user-images.githubusercontent.com/29714154/27554552-9de8eb64-5a63-11e7-955d-c6f1f03cd789.PNG)

**Comment by brianteeman** [comment]
If you are still having problems please use the forum for support https://forum.joomla.org
