### ISSUE TITLE
Ordering custom fields

### ISSUE THREAD

**Issue by Romkev** [joomla/joomla-cms#16123]
After J 3.7.0 I have created fieldgroups and fields.
Fields Ordering as I have made in the backend: Klasse (Class)(ID 1), Wedstrijd (Match)(ID 2) - Uitslag (result) (ID 3) (I have a sports-site: www.smelnesport.nl)
After Update to J 3.7.1 the ordering is Result (ID 1) - Match (ID 2) - Class (ID 3)

By the way, its not only in the frontend display, but also on the tab in the backend of the article.

**Comment by franz-wohlkoenig** [comment]
as far as i know its expected behaviour – @SniperSister?

**Comment by Quy** [comment]
@Romkev Fixed https://github.com/joomla/joomla-cms/pull/16183

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16183<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16123">issues.joomla.org/tracker/joomla-cms/16123</a>.</sub>
