### ISSUE TITLE
Update message when on staging

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#16126]
I am on staging and my update channel is set to default but I am being offered an update to 3.7.1 - is there an xml on the update server that hasnt been updated? @zero-24 @rdeutz 
<img width="785" alt="screenshotr13-56-36" src="https://cloud.githubusercontent.com/assets/1296369/26248645/1f28557a-3c9b-11e7-9286-cfd871ddcf57.png">

**Comment by zero-24** [comment]
hmm i can not reproduce this on my site?

![image](https://cloud.githubusercontent.com/assets/2596554/26267808/4cd1bbd2-3cec-11e7-9c95-714cb067b582.png)

Can you try to refresh the cache? btw you should anyway use the next patch update server if you use staging. than we also offer reinstall ;)

**Comment by brianteeman** [comment]
Switched to the testing channel and I get this
<img width="842" alt="screenshotr22-50-35" src="https://cloud.githubusercontent.com/assets/1296369/26268132/a65028b2-3ce5-11e7-8849-eaa9e8e64a3a.png">

**Comment by brianteeman** [comment]
i have done a fresh install and its fine now - sorry must have been a local install issue
