### ISSUE TITLE
[3.7 Routing] ERR_TOO_MANY_REDIRECTS since 3.7 if the home page is not public

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#16139]
### Steps to reproduce the issue

- install 3.6.5
- setup the following.
- one article (access level super user)
- the default menu entry pointing to that article e.g. single article (also the menu has access level super user)
- update to 3.7.1
- visite the home page

### Expected result

login page

### Actual result

ERR_TOO_MANY_REDIRECTS but with the correct URL `index.php/component/users/?view=login&Itemid=101`

### Additional comments

To me it looks like something realted to the new lookup path in the new router where the home URL is choosen if anything else is not working.

Thanks for @hamby for reporting that.

**Comment by brianteeman** [comment]
@zero-24 we have lots of issues on this already

**Comment by stevlam** [comment]
i add this problem too in a registered only site in 3.7.0 

disocvered replacing in https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/component/router/rules/menu.php#L133

if (!empty($default->id))
for
if (!empty($default->id) && in_array($active->access, JFactory::getUser()->getAuthorisedViewLevels()))

stops the redirects. but not sure this is the best way to solve

**Comment by stevlam** [comment]
Just a info. This is fixed by the other one that will be on 3.7.3

**Comment by brianteeman** [comment]
Closed as we have a PR resolving this #16210 and in the meantime it can be easily resolved by ensuring you have a menu item (it can be hidden) to the login component

**Comment by gneto3** [comment]
stevlam ->   funciona! it works!

thanks.
