### ISSUE TITLE
Custom field same name error if the new field name contains characters like ... --- +++ etc..

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-cms#16132]
### Steps to reproduce the issue
Create a new content custom fied with Title "test", try to create another custom field with Title "test...---+++" 
Error
Save failed with the following error: Another Field has the same name (remember it may be a trashed item).

### Expected result
I can create custom field with different Title

### Actual result
I can't create custom field with different Title

### System information (as much as possible)

![field-name-error](https://cloud.githubusercontent.com/assets/1362388/26273847/c28b6450-3d31-11e7-82bb-27b7ce1e052b.png)

### Additional comments
Joomla 3.7.1

**Comment by brianteeman** [comment]
It's the same throughout Joomla

**Comment by AlexRed** [comment]
for the content I have:
Warning
Alias already existed so a number was added at the end. You can re-edit the article to customise the alias.
And the content was created

Where in Joomla is the same like for the custom field ?

**Comment by AlexRed** [comment]
For modules I can create modules with the same title

**Comment by mbabker** [comment]
> Where in Joomla is the same like for the custom field ?

The restriction that aliases must be unique is the same.  Replace "alias" with "name" in the case of com_fields IIRC.  What may be different is "hard" erroring like your issue report states and automagically changing the alias as com_content does as an example.

I don't think it's the Title field that's causing your error.

**Comment by AlexRed** [comment]
yes, I agree

**Comment by brianteeman** [comment]
The title of a field is NOT the same thing as the title of a module

The title of a field is a unique identifier of the field

The label of the field is the non unique text that is equivalent to the
title of a module

The reason that string and string-+++ has been explained by Michael

**Comment by Bakual** [comment]
The title doesn't matter. The "name" must be unique (sitewide) because it is also used as the "id" attribute of the element. The "name" is generated automatically from the title (exactly like the alias for an article), but you can specify one yourself.

**Comment by brianteeman** [comment]
i am closing this for the reasons stated above
