### ISSUE TITLE
Improve resource usage in Smart Search indexer

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#16131]
As of this writing, `developer.joomla.org` has an index with 14,783 items and the below settings for the index.  FWIW, the items are mostly our JoomlaCode issue archive (the plugin's at https://github.com/joomla/developer.joomla.org/blob/master/plugins/finder/tracker_issues/tracker_issues.php if it really matters).  Running the indexer via the command line, I get the "Allowed memory size..." error after about 90 batches and it takes a few runs of the CLI script to get the full index.  Our server has `memory_limit = 128M` set up.

We should do a fresh review on the resource usage in the indexer and find ways to improve things in general.

![screen shot 2017-05-19 at 10 53 08 am](https://cloud.githubusercontent.com/assets/368545/26256106/75051880-3c81-11e7-9411-7abf54fe64ab.png)

**Comment by chrisdavenport** [comment]
See https://github.com/joomla/joomla-cms/pull/12649

**Comment by tonypartridge** [comment]
@mbabker does @chrisdavenport 's pr address your issue? If so can we close this?

**Comment by mbabker** [comment]
With that PR the process completes without hitting a fatal memory error on the developer site.  Seems fine to me for now.
