### ISSUE TITLE
[com_fields] Define "imagelist" requirements

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#16136]
### Steps to reproduce the issue

create a custom field with "imagelist" 
allow multiple
select 2 images when editing content 
view content

### Expected result

An IMAGE "LIST"

### Actual result

```html
<span class="field-label">imagelist: </span>
<span class="field-value">
<img src="/images/banners/osmbanner1.png" class="myclss £%$^&amp;%*^(&amp;">
<img src="/images/banners/shop-ad-books.jpg" class="myclss £%$^&amp;%*^(&amp;">
</span>
```
(additional linebreaks my own formatting here for clarity, Joomlas output has varying linebreaks)
### System information (as much as possible)

Versions > Joomla 3.7.0 

### Additional comments

This is NOT a list (in the english sense of the word), this is just dumping out the images one after another.

Can someone define if this is what they would expect? 

**I** would expect a `<ul><li><img /></li><li><img /></li></ul>` kind of markup for an image "list"

Am I alone? (as always)

**Comment by AlexRed** [comment]
Yes, I confirm, the list images result is not so good.

Is it a good idea also add the ALT tag with the field Label text ?

**Comment by Bakual** [comment]
Selecting the same image twice is probably hard to do given how a HTML select works. The output however could be adjusted. Each field type can use an own layout, eg the imagelist uses this one: https://github.com/joomla/joomla-cms/blob/staging/plugins/fields/imagelist/tmpl/imagelist.php
This is fully overrideable.

Of course it can be changed to a list as well in core if someone wants to do a PR. However without the needed CSS you will get the bullet points before each image which probably isn't what most users want :)

**Comment by brianteeman** [comment]
I would say that the ability to add alt and title params for each image is essential

**Comment by PhilETaylor** [comment]
> I would say that the ability to add alt and title params for each image is essential

But currently impossible the way its currently written because the images are just selected using one of those horrid selectors

**Comment by Quy** [comment]
For a temporary solution, use the image filename, replace hyphens and dashes with a space, and omit extension.

**Comment by Quy** [comment]
Minimally, add `alt=""`. I vaguely recall that without `alt` attribute that the screenreader will read the filename.

**Comment by brianteeman** [comment]
> Minimally, add alt="". I vaguely recall that without alt attribute that the screenreader will read the filename.

That is correct but it is also incorrect to add a blank alt param unless the image is only used for decoration
