### ISSUE TITLE
Only for a few users : Application Instantiation Error: Could not connect to MySQL

### ISSUE THREAD

**Issue by WebAtelier47** [joomla/joomla-cms#16134]
#### Steps to reproduce the issue
Access to website, frontend or backend

#### Expected result
The website

#### Actual result
Only for a few users Application Instantiation Error: Could not connect to MySQL.

#### System information (as much as possible)
Joomla 3.7.1
Host OVH
PHP 7.0.15
MYSQL 5.5.55-0+deb7u1-log
Admin tool with htaccess
System - Page Cache enable

#### Additional comments
The Problem was resolved by clearing the user's browser cache

**Comment by franz-wohlkoenig** [comment]
at https://github.com/joomla/jissues/issues/968#issuecomment-302748017 @mbabker explained Error, so closing this issue.

**Comment by brianteeman** [comment]
this error is almost always as a result of a failure of the web server to talk to the mysql server. its highly unlikely it is anything to do with the browser cache and it was just coincedence that the connection was restored at the same time

**Comment by WebAtelier47** [comment]
Just for information, the system page cache plugin was enable.

**Comment by brianteeman** [comment]
That is completely irrelevant and unrelated to your issue
