### ISSUE TITLE
Can't access component after installation when cache is enabled

### ISSUE THREAD

**Issue by nikosdion** [joomla/joomla-cms#16147]
### Steps to reproduce the issue

* Create a new Joomla! site
* Go to Global Configuration
* Set **System Cache** to **ON - Conservative Caching**
* Install a component _through a package_, e.g. [Akeeba Backup Core](https://www.akeebabackup.com/download/akeeba-backup/5-4-0.html).
* Immediately after the installation is complete click on the Components menu and click the menu item of the component, e.g. Component, Akeeba Backup

### Expected result

The component I just installed opens.

### Actual result

404 Component Not Found

The problem persists throughout the cache time. If I go to System, Clear Cache and clear _the Administrator cache_ it works. Therefore the problem is definitely related to the global cache.

### System information (as much as possible)

Irrelevant, but here you go:

* Joomla! 3.7.1 stable
* Linux (Kubuntu 17.04) with Apache/2.4.25 (Ubuntu) and PHP 7.0.18 with the following version info.

```PHP 7.0.18-0ubuntu0.17.04.1 (cli) (built: Apr 26 2017 23:59:48) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-0ubuntu0.17.04.1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```

This information is _irrelevant_ since another site _without_ global caching worked perfectly. Also see comments above regarding deleting the cache making it work just fine...

### Additional comments

Nearly three years ago in Joomla Bug Sprint 2014 in Manchester we had fixed a series of similar bugs with modules and plugins. I remember that because @brianteeman was counting down the last 5' while I was racing against his countdown to write the patch and send the PR :stuck_out_tongue:  Joomla would cache the results of queries to the extensions table. What I did back then is add a couple of lines of code to clear that cache when we were publishing / unpublishing modules and plugins. I bet you need to do the same thing when installing extensions.

**Comment by brianteeman** [comment]
Why anything is ever cached in the administration is beyond me

**Comment by mbabker** [comment]
If https://github.com/joomla/joomla-cms/pull/15606 would ever get merged...

**Comment by nikosdion** [comment]
Am I correct in assuming that if my post-installation script clears the _system cache in both sides of the application the problem I experienced would be solved?

**Comment by mbabker** [comment]
Yes.  `JComponentHelper::load()` caches the component data in the `_system` group.  If you're doing something with plugins, `JPluginHelper::load()` uses the `com_plugins` group.

**Comment by nikosdion** [comment]
Thank you. I will modify all my post-installation scripts since I have to still support Joomla! 3.4.0 to 3.7.1.

**Comment by nikosdion** [comment]
I can confirm that the problem was reproducible on other environments with the defining parameter being the use of caching in Global Configuration. I can also confirm that cleaning the cache in my post-installation script as discussed above does solve the problem. Finally, applying gh-15606 also solves the problem without the workaround. So indeed it's a caching issue and gh-15606 solves it. I am therefore closing this issue.
