### ISSUE TITLE
db.#__utf8_conversion' doesn't exist on upate to 3.7.1

### ISSUE THREAD

**Issue by alensailnet** [joomla/joomla-cms#16145]
### Steps to reproduce the issue
update from 3.6.5 to 3.7.1

### Expected result
clean update

### Actual result

Installer: :Install: Error SQL Table 'euro2017.#__utf8_conversion' doesn't exist
Files Update: SQL error file DB function failed with error number 1146
Table 'db.#__utf8_conversion' doesn't exist
SQL =

UPDATE `#__utf8_conversion` SET `converted` = 0
 WHERE (SELECT COUNT(*) FROM `#__schemas` WHERE `extension_id`=700 AND `version_id` LIKE '3.5.0%') = 1;

### System information (as much as possible)
Database Version 	5.6.21
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.6.3
Web Server 	Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.6.3
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.7.1 Stable [ Amani ] 17-May-2017 14:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0

**Comment by wojsmol** [comment]
@alensailnet Plese go to Extensions > Manage > Database and click Fix button.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16145">issues.joomla.org/tracker/joomla-cms/16145</a>.</sub>

**Comment by alensailnet** [comment]
I have done that allready and it works - database up to date
But there is no more Joomla update on the menu  - is that expected?
Alen

**Comment by wojsmol** [comment]
No this is not expected. Go to Extensions > Manage > Database and click Discover button. If Joomla update was finf select it and click Install button.

**Comment by wojsmol** [comment]
@alensailnet Was the problem solved?

**Comment by alensailnet** [comment]
Yes after several attempts - it seems to be a cache issue but it is fine now
Now it says that the database is ok - Database table structure is up to
date.
Under Components menu Jomla update is misssing still - is that expected?
Thanks
Alen

**Comment by wojsmol** [comment]
@alensailnet See https://github.com/joomla/joomla-cms/issues/16145#issuecomment-302876899

**Comment by brianteeman** [comment]
Closed
