### ISSUE TITLE
[3.7.1] SEF Turned off, the Submenus Links don't appear

### ISSUE THREAD

**Issue by ufuk-avcu** [joomla/joomla-cms#16144]
### Steps to reproduce the issue
Create a Menu Item with a Parent and some Childs. Set the "Search Engine Friendly URLs" Option to "No". Go to the Frontend and click on the Parent Item. 

### Expected result
You should see the Child Items.

### Actual result
You don't see the Child Items and the Menu Item Class "active" is not set for the parent item.

### System information (as much as possible)
Joomla 3.7.1
PHP 5.6 / 7.0

### Additional comments
If you set "Search Engine Friendly URLs" Option to "Yes". Everything is fine.

**Comment by PhilETaylor** [comment]
Already addressed, merged and will be fixed in Joomla 3.7.2

see: https://github.com/joomla/joomla-cms/pull/16089

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16089<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16144">issues.joomla.org/tracker/joomla-cms/16144</a>.</sub>
