### ISSUE TITLE
Login via ssl in module does not work properly

### ISSUE THREAD

**Issue by webmasterab** [joomla/joomla-cms#16150]
I have created the ssl website and set the module to pass the password via ssl.
Now people can not log in with the password and need to re-create them again via the Forgotten Password.

How can I solve this

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding.

**Comment by franz-wohlkoenig** [comment]
closed as no Core Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16150">issues.joomla.org/tracker/joomla-cms/16150</a>.</sub>
