### ISSUE TITLE
Error Message with PHP7.0

### ISSUE THREAD

**Issue by rejonesjr** [joomla/joomla-cms#16162]
### Steps to reproduce the issue
            We are now getting the following errors when logging into the Admin Screen. Attached is related.
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; plgSystemJATypo has a deprecated constructor in /home/nhknight/public_html/plugins/system/jatypo/jatypo.php on line 24

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; KeyCAPTCHA_CLASS has a deprecated constructor in /home/nhknight/public_html/plugins/system/keycaptcha/keycaptcha.php on line 34

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; JAT3_AdminUtil has a deprecated constructor in /home/nhknight/public_html/plugins/system/jat3/jat3/core/admin/util.php on line 21

**Comment by mbabker** [comment]
Report the messages to the respective extension developers.  All it is is a warning that they are still using a PHP 4 feature that was deprecated in PHP 7 and presumably will be removed with PHP 8.
