### ISSUE TITLE
admin footer toolbar creates white haze thats not good/needed

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#16160]
<img width="1239" alt="screen shot 2017-05-20 at 21 46 46" src="https://cloud.githubusercontent.com/assets/400092/26279231/e9041c98-3da5-11e7-97c2-125a89eb99c1.png">
<img width="1235" alt="screen shot 2017-05-20 at 21 47 48" src="https://cloud.githubusercontent.com/assets/400092/26279232/ff104b38-3da5-11e7-854c-aa4d589571ce.png">

**Comment by franz-wohlkoenig** [comment]
@C-Lodder Comment?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16160">issues.joomla.org/tracker/joomla-cms/16160</a>.</sub>

**Comment by C-Lodder** [comment]
Meh, can be removed I suppose

**Comment by ciar4n** [comment]
PR created.. #16205

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16205<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16160">issues.joomla.org/tracker/joomla-cms/16160</a>.</sub>
