### ISSUE TITLE
[4.0] RFC Set default useragent on all JHttpFactory calls

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#16172]
### Steps to reproduce the issue

RFC Set default useragent on all JHttpFactory calls.

Here: https://github.com/joomla/joomla-cms/pull/15385 we did that for the updater but would it not make also sense to have this globaly for all calls using JHttpFactory ?

### Expected result

default useragent on all JHttpFactory calls

### Actual result

No useragent on JHttpFactory calls

**Comment by mbabker** [comment]
IMO no, `JHttp` shouldn't be forced to have a value here.  If someone wants to set it in `JHttpFactory`, I think that'd be an OK compromise but unless it becomes a mandatory value to set for a request to be valid then I wouldn't force it in the adapter.

**Comment by zero-24** [comment]
Sorry i meant `JHttpFactory` and not `JHTTP` i have just fixed the original issue.

**Comment by wojsmol** [comment]
@zero-24 Title of the issue is still wrong.

**Comment by zero-24** [comment]
fixed

**Comment by zero-24** [comment]
#16538
