### ISSUE TITLE
[com_fields] List text does not render åäö

### ISSUE THREAD

**Issue by Flowman** [joomla/joomla-cms#16175]
### Steps to reproduce the issue
Create a custom List.
In the list values text field enter any of åäö.
Check the result in front end.

### Expected result
åäö should render in front end.

### Actual result
 Warning: SimpleXMLElement::__construct(): Entity: line 2: parser error : Entity 'ouml' not defined in /usr/share/nginx/html/libraries/joomla/form/form.php on line 728

### System information (as much as possible)
Joomla 3.7.0
PHP 7.1.4
Nginx 1.12

**Comment by franz-wohlkoenig** [comment]
You mean Joomla 3.7.0 or 3.7.1?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16175">issues.joomla.org/tracker/joomla-cms/16175</a>.</sub>

**Comment by Flowman** [comment]
Sorry yes Joomla 3.7.0.

**Comment by franz-wohlkoenig** [comment]
Can't confirm:
![bildschirmfoto 2017-05-22 um 06 25 53](https://cloud.githubusercontent.com/assets/8235763/26292616/97af71cc-3eb7-11e7-8192-5a9f1f776634.JPG)

**Comment by Flowman** [comment]
Can you test it on user instead of article, and see what result you get?

**Comment by Quy** [comment]
This is fixed in 3.7.1. Please upgrade.

**Comment by franz-wohlkoenig** [comment]
Works also in "Users":
![bildschirmfoto 2017-05-22 um 07 02 03](https://cloud.githubusercontent.com/assets/8235763/26293392/a0e9802a-3ebc-11e7-9797-ad1f3fa098e1.JPG)

**Comment by franz-wohlkoenig** [comment]
clsed as fixed in Code Base. Thanks for Hint, @Quy.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16175">issues.joomla.org/tracker/joomla-cms/16175</a>.</sub>
