### ISSUE TITLE
manual time set in persian calendar not work

### ISSUE THREAD

**Issue by farhadst** [joomla/joomla-cms#16179]
### Steps to reproduce the issue
update from 3.7.0 to 3.7.1
in article publish, time set hide in calendar popup
![cal1](https://cloud.githubusercontent.com/assets/8976056/26300311/f6dad084-3ef2-11e7-95dd-d075bb808faf.jpg)

### Expected result
after set time manual and clicl any field or press save button, hour and minutes reset to curent time
![screencapture_17-05-22_14 18 26](https://cloud.githubusercontent.com/assets/8976056/26303339/a128ee96-3efc-11e7-8eb2-af80504d5418.gif)

### Additional comments
in joomla 3.7.0 by select hour and minutes in time set calendar everything is ok

**Comment by zero-24** [comment]
Can you please test this on staging too? https://github.com/joomla/joomla-cms/archive/staging.zip

**Comment by farhadst** [comment]
i have test staging and pick date is ok but after click on save button only time reset to curent

**Comment by dgrammatiko** [comment]
@farhadst this is not valid anymore, right?

**Comment by farhadst** [comment]
@dgt41 yes this problem fixed in new version

**Comment by ghost** [comment]
closed as Issue solved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16179">issues.joomla.org/tracker/joomla-cms/16179</a>.</sub>
