### ISSUE TITLE
Joomla 3.7.1 article saving problem -

### ISSUE THREAD

**Issue by anglo84** [joomla/joomla-cms#16184]
Hello, 

After and update 3.6.5 to 3.7.1 I can not save the articles. It buffers a while and then shows "page not found". 
The strange thing is that after I click "save" the URL turns into friendly URL without my domain name.

Everything takes place in the backend.

it looks like this: https://(missing domain name)/administrator/2-uncategorised/article5

Any ideas?

cc: @wojsmol

**Comment by wojsmol** [comment]
@PhilETaylor This is issue requed by you in https://github.com/joomla/joomla-cms/pull/16089#issuecomment-302704864

**Comment by PhilETaylor** [comment]
> Everything takes place in the backend.

Please be more specific!

**Comment by PhilETaylor** [comment]
What PHP version are you running?
Are you using non latin chars like amulets and other international chars æ ë tc ?
Have you tried the patches prepared for Joomla 3.7.2 here https://github.com/joomla/joomla-cms/pulls?q=is%3Apr+milestone%3A%22Joomla+3.7.2%22+is%3Aclosed

Specifically have you tried the patch https://github.com/joomla/joomla-cms/pull/16140

**Comment by wojsmol** [comment]
@anglo84 Replace /libraries/joomla/filter/input.php with libraries/joomla/filter/input.php https://raw.githubusercontent.com/csthomas/joomla-cms/db0b08a330a32256734ef673a8a35ed963ce4193/libraries/joomla/filter/input.php

**Comment by wojsmol** [comment]
@PhilETaylor I was dealing with this topic on the Polish Joomla Forum. The website is  working on php 5.5.

**Comment by anglo84** [comment]
Hello again, 

@wojsmol Wojsmol - I will try to implement the solution.

@PhilETaylor thank you for your response. What I meant was that I am editing the article in the backend, not in the frontend of my site. 

As Wojsmol said I am using PHP 5.5

**Comment by anglo84** [comment]
I have copied and changed the input.php but it didn't help...

**Comment by anglo84** [comment]
I have found the solution :) 

Content - JSitemap Pingomatic caused the problem. It is a part of jsitemap pro. I have disable it and now I can save the article :) 
Thank You for your time.

**Comment by zero-24** [comment]
Closing as 3rdparty issue. Thanks for the feedback.
