### ISSUE TITLE
Error 1146  Table 'exhaletz_miamia.#__' doesn't exist

### ISSUE THREAD

**Issue by kessyjr** [joomla/joomla-cms#16181]
### Steps to reproduce the issue
extensions > templates > template_files > css > template.css

### Expected result

Opening the edit pane of the template.css file

### Actual result

An error has occurred.
1146 Table 'exhaletz_miamia.#__' doesn't exist
Return to control panel

### System information (as much as possible)

PHP built on		:	Linux x86_64
Database version	:	5.5
Database Collation	:	utf8_unicode_ci
PHP Version		:	7.0
Server			:	Apache
Joomla version	:	3.7.1

### Additional comments
Tried fixing database - extensions > manage > Manage > database > Fix
Database table structure is up to date.
 But still experiencing same error and it happens to all files not just templates.css

**Comment by oe1tkt** [comment]
I can not reproduce this error on 2 machines (J! 3.7.1, php 5.6.30, mysql 5.5.55, Apache2 2.2.22, Debian 3.286-1 x86_64) and (J! 3.7.1, php 7.1.5, mysql 5.5.55, Apache 2.4.10, Debian 3.16.43). No error occurred.

**Comment by brianteeman** [comment]
@kessyjr you have a plugin installed on your site that is not working correctly.

**Comment by brianteeman** [comment]
For further support please use the forum https://forum.joomla.org
