### ISSUE TITLE
Add note field to article

### ISSUE THREAD

**Issue by joomlaolle** [joomla/joomla-cms#16180]
Articles lack note field. They only have version note, which does not function the same way. Any reason this has not been added (yet)?

For my specific use-case, I export articles, menus etc to XLIFF format, and would like to have a note field that I can export as instructions to the translator (XLIFF support the <note> tag). The fact that this field is present for menus and modules (mod_custom) makes no sense to me.

**Comment by laoneo** [comment]
Can this not being solved by creating a custom field?

**Comment by joomlaolle** [comment]
Perhaps, I will read up on it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16180">issues.joomla.org/tracker/joomla-cms/16180</a>.</sub>

**Comment by joomlaolle** [comment]
Old thread from user wanting the same: https://joomla.stackexchange.com/questions/14073/adding-a-note-to-an-article<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16180">issues.joomla.org/tracker/joomla-cms/16180</a>.</sub>

**Comment by brianteeman** [comment]
As no one has ever asked for it before no one has ever implemented it.

**Comment by brianteeman** [comment]
@joomlaolle did the custom field resolve your issue?

**Comment by brianteeman** [comment]
i am closing this as there has been no response for several months. It can always be reopened if required

**Comment by brianteeman** [comment]
See #19134
