### ISSUE TITLE
RFC linknames appearing in demo content

### ISSUE THREAD

**Issue by Twincarb** [joomla/joomla-cms#16196]
### Steps to reproduce the issue
linknames has just been removed from mod_users_latest #16171 and #16157 however there are a couple of references to linknames in the demo content in the following areas.

https://github.com/joomla/joomla-cms/blob/staging/tests/unit/stubs/database/jos_modules.csv
https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/sample_learn.sql
https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/sample_testing.sql
https://github.com/joomla/joomla-cms/blob/staging/installation/sql/postgresql/sample_learn.sql
https://github.com/joomla/joomla-cms/blob/staging/installation/sql/postgresql/sample_testing.sql
https://github.com/joomla/joomla-cms/blob/staging/installation/sql/sqlazure/sample_learn.sql
https://github.com/joomla/joomla-cms/blob/staging/installation/sql/sqlazure/sample_testing.sql

The following lines are shown am I correct in believing that linknames shouldn't be appearing there? and instead it should marry to the xml file? which would mean both should show filter_groups = 0? if so I am happy to make a PR to amend them.

(38, 'Users Latest', '', '', 1, '', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_users_latest', 1, 1, '{"shownumber":"5","linknames":"0","layout":"_:default","moduleclass_sfx":"","cache":"0","cache_time":"900","cachemode":"static"}', 0, '*'),
(39, 'Who''s Online', '', '', 1, '', 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 1, 'mod_whosonline', 1, 1, '{"showmode":"2","linknames":"0","layout":"_:default","moduleclass_sfx":"","cache":"0"}', 0, '*'),

**Comment by brianteeman** [comment]
feel free to submit a PR to remove it

**Comment by brianteeman** [comment]
Closed see #16331
