### ISSUE TITLE
Joomla 3.7.1 problem with admin menu after upgrade

### ISSUE THREAD

**Issue by renton-** [joomla/joomla-cms#16190]
After update joomla from 2.5 (and from 3.x too) to 3.7.1 I noticed that admin menu looks strange. All submenu is half transparent.

If I make fresh installation of Joomla 3.7 on same box then admin menu is good.

![joomla_3 7_bug](https://cloud.githubusercontent.com/assets/1737936/26320663/413ca5d8-3f2c-11e7-9b49-f3793903bb36.jpg)

**Comment by brianteeman** [comment]
This probably a browser cache issue and you have confirmed that it is not a core joomla issue as a clean install worked correctly. Please make sure you clear all cache including on your own computer. For further support please use the forum https://forum.joomla.org

**Comment by renton-** [comment]
Thank you for hint about cache. It isn't browser cache issue but it is conflict (or something like that) with JA T3 Framework. I disabled it and admin menu is working perfect now.
Thank you.

**Comment by brianteeman** [comment]
it is always the ja t3 framework - breaks joomla every time :(
