### ISSUE TITLE
Custom backend menu non-text separators currently un-intuitive

### ISSUE THREAD

**Issue by ZoFx** [joomla/joomla-cms#16198]
### Issue:
After updating to 3.7 I desperately tried to create unnamed separators in a custom backend menu. Only here on Github I found I could achieve this by naming it with a single hyphen (-). In my opinion, this is not at all intuitive. How are users supposed to know that?

What's more when named with a single hyphen, the menu item is quite hard to click in the menu item list. Of course I can select the item and use the _Edit_ button, but who the heck actually does it this way?

### Suggested solution:
I think it would be far more elegant to have a _Use Menu title as separator label_ property. And this should be switched off by default, which would be more the default behaviour of a "separator" imho. And of course the menu item type should then be named _Separator_ instead of _Text separator_
**OR:** We should have an additional _Separator_ menu item type, which doesn't even need a menu item title (no idea if this is even possible in Joomla ...) or at least works as the "classic" Joomla menu separator.

### System information
Joomla 3.7.1

### Relevant other issues
#15002 Allow menu item separators to have labels in admin menu

**Comment by franz-wohlkoenig** [comment]
i run into same Issue as i want to have a Seperator. If its not in [Docs](https://docs.joomla.org/Help37:Menus_Menu_Item_Text_Separator) please add this Information (docs is a Wiki).

**Comment by ghost** [comment]
@ZoFx have you added Information in Docs, can i close this Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16198">issues.joomla.org/tracker/joomla-cms/16198</a>.</sub>

**Comment by jonrz** [comment]
@ZoFx We will add menu separator to the ideas board for the UX team.
This is something we can take care of in the short to medium term future.
Thanks for the idea!

**Comment by ghost** [comment]
thanks for Info @jonrz so Issue stay open.

**Comment by brianteeman** [comment]
This needs resolving in J3 and not just J4 which is where the UX team are working

**Comment by ghost** [comment]
closed as having Pull Request #17970<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16198">issues.joomla.org/tracker/joomla-cms/16198</a>.</sub>
