### ISSUE TITLE
PHP Notice in blog view and Show Voting enabled

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-cms#16203]
### Steps to reproduce the issue
Create a Blog item menu, create some article for the blog. Enable Show Voting in the blog menu item.
Try to open in frontend the blog and see the php error log:
PHP Notice:  Undefined property: JCategoryNode::$rating_count in ../plugins/content/vote/tmpl/rating.php on line 45

### Expected result
No PHP Notice

### Actual result
PHP Notice:  Undefined property: JCategoryNode::$rating_count in ../plugins/content/vote/tmpl/rating.php on line 45

### System information (as much as possible)
Joomla 3.7.2 Dev

**Comment by infograf768** [comment]
Confirmed

**Comment by infograf768** [comment]
Patch coming

**Comment by infograf768** [comment]
Patch available
https://github.com/joomla/joomla-cms/pull/16204
closing
