### ISSUE TITLE
Unit Tests Failing On Staging!

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#16207]
@tonypartridge @wilsonge 

Probably from this https://github.com/joomla/joomla-cms/commit/3a7e306195ad616b88384e9c60c7b8dcff3e9f09

https://travis-ci.org/joomla/joomla-cms/builds/235154012?utm_source=github_status&utm_medium=notification

**Comment by mbabker** [comment]
Problematic PR reverted for now.
