### ISSUE TITLE
Misleading description for the "Menu heading" menu item type

### ISSUE THREAD

**Issue by ZoFx** [joomla/joomla-cms#16200]
### Steps to reproduce the issue
- Create a custom backend menu
- Add a new menu item
- Open the selection for _Menu Item Type_
- Open the _System links_ category

### Actual result
The description for the _Menu heading_ item reads "A heading for use within menus, useful when separating menus with a separator."

I honestly can't see how this makes sense. As far as I can see, Menu heading has nothing to do with the separators.

### Expected result
The description should be something like "A heading for use within menus, opens a submenu but does not link to anything itself."

### System information (as much as possible)
Joomla 3.7.1

**Comment by tonypartridge** [comment]
The message means if you use a separator within you menu this menu item is useful to be rendered after it and therefore be a heading for the next set of menu items.

**Comment by ZoFx** [comment]
I think that's what the _Text separator_ item is for right now, isn't it? In contrast to the _Text separator_, the _Menu heading_ item has the ability, to be a good (non-clickable) parent to submenu items. I think, the description should reflect that.

In general I think the entire separator thing should be looked at again. It's not completely clear yet, which one serves which purpose, let alone the currently missing (or at least rather complicated) _Separator_ item (see #16198).

**Comment by ghost** [comment]
closed as having Pull Request #18191<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16200">issues.joomla.org/tracker/joomla-cms/16200</a>.</sub>
