### ISSUE TITLE
Joomla.renderMessages - Cannot read property 'joomla.jtext' of null

### ISSUE THREAD

**Issue by Wojton** [joomla/joomla-cms#16217]
### Steps to reproduce the issue
```
  var messages = { "message": ["Message one", "Message two"],
                            "error": ["Error one", "Error two"]
                        };
 Joomla.renderMessages(messages);

```

```

   jQuery.ajax({
                    url: "index.php",
                    type: "POST",
                    data:
                    { 
                        option: "<?php echo $option ?>",
                        task: "messageform.sentMessage",
                        params: "<?php echo $this->params64 ?>",
                        "<?php echo JSession::getFormToken() ?>": '1',
                        msg:jQuery("#gs-message").val()
                    },
                    dataType: "JSON",
                    success: function(json){
                        var messages = { "message": ["Message one", "Message two"],
                            "error": ["Error one", "Error two"]
                        };
                        Joomla.renderMessages(messages);
                      //  Joomla.renderMessages(json.messages);

                        if(json.data == "message_send"){
                            jQuery("#ga-jq-submit-message-form").fadeOut('fast',function(){
                                jQuery(this).remove();
                            });
                        }
                    }
                });
```

### Expected result
Correct system message

### Actual result
```
Uncaught TypeError: Cannot read property 'joomla.jtext' of null
    at Object.e.getOptions (core.js?4d4a824…:1)
    at Object._ (core.js?4d4a824…:1)
    at Object.e.renderMessages (core.js?4d4a824…:1)
    at Object.success (messageform.html?tmpl=component&09ca28f…=1&params=YToyOntzOjM6ImFpZCI7czozO…:226)
    at i (jquery.min.js?4d4a824…:2)
    at Object.fireWith [as resolveWith] (jquery.min.js?4d4a824…:2)
    at y (jquery.min.js?4d4a824…:4)
    at XMLHttpRequest.c (jquery.min.js?4d4a824…:4)
```

### System information (as much as possible)
Joomla >3.7 (in joomla <=3.6.5 worked)

**Comment by dgt41** [comment]
I can't replicate this!
Please make sure that `core.js` is loaded in your view!

![screen shot 2017-05-23 at 21 22 50](https://cloud.githubusercontent.com/assets/3889375/26369671/088f4128-3ffe-11e7-85f6-ad907fb7112b.png)

code I used:
```js
   jQuery.ajax({
                    url: "index.php",
                    type: "POST",
                    data:
                    { 
                    },
                    dataType: "JSON",
                    success: function(json){
                    }, error: function() {
var messages = { "message": ["Message one", "Message two"],
                            "error": ["Error one", "Error two"]
                        };
                        window.Joomla.renderMessages(messages);}
                });

```

**Comment by izharaazmi** [comment]
I can confirm this issue exists. And since I had not enough time to dive in, I am using a workaround that is making a useless `JText:: script()` call in my layouts.

**Comment by Fedik** [comment]
@Wojton please enable Debug mode, and post here the javascript error again?

**Comment by tonypartridge** [comment]
Is this not caused by not having the system-messages container rendered?

**Comment by andrepereiradasilva** [comment]
could this also be related to the progressive cache issue like https://github.com/joomla/joomla-cms/issues/16375#issuecomment-305864460 ?

> 1. The JHtml::_('behavior.keepalive'); inside the mod_login template file is not being processed when cache in conservative mode.

**Comment by Fedik** [comment]
it should be fixed with #16488

**Comment by franz-wohlkoenig** [comment]
@Wojton can you please test #16488 if it fixes this Issue & in so close this Issue – thanks.

**Comment by andrepereiradasilva** [comment]
https://github.com/joomla/joomla-cms/pull/16488 should resolve the js error

But there is the issue of the `joomla.jtext` json not being loaded in certains conditions and that could be the same issue as https://github.com/joomla/joomla-cms/issues/16375#issuecomment-305864460

@Wojton is this used in a module? does this happen with Progressive cache enabled?

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 17th September 2017.

**Comment by ghost** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened.
