### ISSUE TITLE
Adding non-latin tags to joomla articles

### ISSUE THREAD

**Issue by mijalis** [joomla/joomla-cms#16225]
### Steps to reproduce the issue
Add/edit article and add a tag using a non-latin tags (eg greek)
For example: Αριανα (Greek for "Ariana")

### Expected result
When "Αριανα" is typed, the message "Looking for 'Αριανα'" should be shown and the user should be able to save tag by pressing "Enter".
For example when adding "Ariana":
![clipboard02](https://cloud.githubusercontent.com/assets/22443502/26375255/d7b43c8a-4010-11e7-81b6-871f9b3a288d.jpg)

### Actual result
Cannot save tag, the first available tag from the list is added to the article.
When the string "Αριανα" is typed, the message "Looking for 'Αριανα'" is **not** shown, therefore saving the tag is not possible.
![clipboard01](https://cloud.githubusercontent.com/assets/22443502/26375178/8d9043e2-4010-11e7-9073-adbf279da59e.jpg)

### System information (as much as possible)
PHP Built On	FreeBSD 1.1.1.1 10.3-STABLE FreeBSD 10.3-STABLE #0: Sat Dec 17 14:30:45 EET 2016 root@1.1.1.1:/usr/obj/usr/src/sys/GENERIC amd64
Database Version	5.6.36
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.30
Web Server	nginx/1.12.0
WebServer to PHP Interface	fpm-fcgi
Joomla! Version	Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by dgt41** [comment]
I can't replicate this. Can you open your browser's console and see if there are any errors logged there? If so can you copy/paste them here?

![screen shot 2017-05-23 at 23 58 48](https://cloud.githubusercontent.com/assets/3889375/26376100/04d3faa4-4014-11e7-917d-282b8994912c.png)

**Comment by mijalis** [comment]
No errors appearing..

**Comment by mijalis** [comment]
I just tried it in a different environment and it is working fine..the configuration though is different (Apache instead of Nginx.

**Comment by mijalis** [comment]
I am getting somewhere..
Plugin [Cachecontrol](https://extensions.joomla.org/extension/cachecontrol/) is causing it..
When disabled is working fine.

**Comment by brianteeman** [comment]
in that case i am closing it here as a non core issue -  I suggest that you contact the developer of that extension directly.

**Comment by mijalis** [comment]
I am re-opening this because the problem still exists.
I incorrectly reported that the plugin Cachecontrol was causing it.

I managed to correctly reproduce the problem, and it happens only if **at least one tag** exists in the database.

### Steps to reproduce the issue
Remove all tags from administrator/index.php?option=com_tags
Add/edit article and add any tag, eg: "Ariana"
Save and close Article
Edit same article and add any tag using a non-latin tags (eg greek)
For example: Αριανα (Greek for "Ariana")

### Actual result
Cannot save tag, the first available tag from the list is added to the article.
When the string "Αριανα" is typed, the message "Looking for 'Αριανα'" is **not** shown, therefore saving the tag is not possible.

**Comment by franz-wohlkoenig** [comment]
reopened as @mijalis wrote.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16225">issues.joomla.org/tracker/joomla-cms/16225</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
closed in favor of Issue #16235<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16225">issues.joomla.org/tracker/joomla-cms/16225</a>.</sub>
