### ISSUE TITLE
Virus warning in the 3.7.2 Full ZIP download

### ISSUE THREAD

**Issue by Stevec4** [joomla/joomla-cms#16220]
### Steps to reproduce the issue
I am getting a virus warning when downloading the 3.7.2 Full Zip 
https://github.com/joomla/joomla-cms/releases/download/3.7.2/Joomla_3.7.2-Stable-Full_Package.zip

It might be a false warning but this I do not get it for the 3.7.1 full download or any of the update files

Trojan Win32/Spurinst.F!cl
in administrator/templates/hathor/js/template.js

**Comment by brianteeman** [comment]
what antivirus software are you using - i just scanned it with AVG and it passed no problem

**Comment by Stevec4** [comment]
windows defender

**Comment by DavidBoggitt** [comment]
Also fine with Windows Defender.

**Comment by mbabker** [comment]
Scans fine with Sophos as well.  Seems like a false positive to me.

**Comment by Stevec4** [comment]
Thanks for double checking everyone I will close it as a false positive
