### ISSUE TITLE
[3.x] Update Codemirror to v5.27.2

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#16226]
http://codemirror.net/doc/releases.html

**Comment by wojsmol** [comment]
@C-Lodder I think you meant version 5.26.0.

**Comment by brianteeman** [comment]
i have updated the title on github ;)

**Comment by C-Lodder** [comment]
oops, thanks

**Comment by C-Lodder** [comment]
@brianteeman or @zero-24 the bot has reverted the title

**Comment by brianteeman** [comment]
thats something for @zero-24 to look at. he is the robot master

**Comment by zero-24** [comment]
Any more action required? Looks correct now to me?

**Comment by brianteeman** [comment]
@zero-24 yes the update needs to be done ;)

**Comment by brianteeman** [comment]
Closed as this has been resolved elesewhere

**Comment by C-Lodder** [comment]
@brian, it's showing 5.28 instead of 5.28.0

Doesnt that go against semver?

**Comment by mbabker** [comment]
No.  It's still major.minor.  It's just not showing a patch revision (for all intents and purposes 5.28 === 5.28.0).

**Comment by C-Lodder** [comment]
Odd but fair enough
