### ISSUE TITLE
Custom Fields in front end are not grouped.

### ISSUE THREAD

**Issue by pnkr** [joomla/joomla-cms#16231]
### Steps to reproduce the issue

Create 2 Field Groups and assign 1-2 custom fields on each.

### Expected result
On front end the custom fields are listed one by one regardless in which Field Group they belong

### Actual result
It would be nice if the fields that belong to a Field Group were grouped in a container, for example a fieldset with the title of the Group Field.
So in the above example we would have 2 fieldset.

**Comment by AlexRed** [comment]
Hello pnkr,
Do you try for User Field or Contact Field or Content Field?
In Contact Mail Field fields that belong to a Field Group are grouped.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16231">issues.joomla.org/tracker/joomla-cms/16231</a>.</sub>

**Comment by laoneo** [comment]
We tried to make them as seamless integrated as possible and in the article information, there is no grouping made. But you can do a layout override to achieve this.

**Comment by vkengo** [comment]
You mention layout override, I could not find any documentation on doing this for an alternative layout.  Is there any way that I can target a group, irrespective of its element position , i.e. my suggestion for a wrapper class. As a FED I want to make it as easy as possible for site admins to add field groups and just a class name to get the desired look and layout. Any help on this would be most welcome. I really appreciate to work to implement custom fields, thanks for all your work.

**Comment by laoneo** [comment]
I'm not sure but then this question should be asked on our forum.

**Comment by vkengo** [comment]
Thanks Allon, I will post it and see if anyone can help and update this thread.

**Comment by franz-wohlkoenig** [comment]
closed in favor of Forums. Issue can always reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16231">issues.joomla.org/tracker/joomla-cms/16231</a>.</sub>
