### ISSUE TITLE
Adding non-latin tags to joomla articles

### ISSUE THREAD

**Issue by mijalis** [joomla/joomla-cms#16235]
I am re-opening this problem (original issue #16225) because the problem still exists.
I incorrectly reported on #16225 that the plugin Cachecontrol was causing it.

I finally managed to correctly reproduce the problem, and it happens only if **at least one tag** exists in Joomla

### Steps to reproduce the issue

1. Remove all tags from Joomla from: administrator/index.php?option=com_tags
2. Add/edit article and add any latin or non-latin tag, eg: **latintag**
3. Save and close Article
4. Edit same article and add a second tag using non-latin tags (eg greek), for example: **ετικέτα**

### Expected result
While trying to add second tag and non-latin tag "ετικέτα" is typed, the message "Looking for 'ετικέτα'" should be shown and the user should be able to save tag by pressing "Enter".
For example when adding tag "latintag":
![clipboard01](https://cloud.githubusercontent.com/assets/22443502/26397751/07c73520-4080-11e7-8ade-7d4256e2a848.png)

### Actual result
When second tag "ετικέτα" is typed, the message "Looking for 'ετικέτα'" is **not** shown, therefore saving the tag is not possible.
![clipboard02](https://cloud.githubusercontent.com/assets/22443502/26397931/8d777e78-4080-11e7-84d7-b9c71a4142c7.png)

### System information (as much as possible)
PHP Built On	Linux calypso 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64
Database Version	5.5.55-0+deb8u1
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.30-0+deb8u1
Web Server	Apache/2.4.10 (Debian)
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by franz-wohlkoenig** [comment]
Can't confirm. Set Steps like wrote above, all works as expected:
![bildschirmfoto 2017-05-24 um 12 06 15](https://cloud.githubusercontent.com/assets/8235763/26398346/846441a6-4079-11e7-948f-72708e8bdc1b.JPG)
### System information
3.7.3-dev
Multilanguage Site
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by mijalis** [comment]
This definitely happens on my side.
And this on a Joomla! 3.7.2 original download package with **no** extra extensions installed.
Can you please try to save this article, add a new one and then add another tag, eg tag "δοκιμη" ?

**Comment by franz-wohlkoenig** [comment]
Done, same Result (maybe a PR is merged who solves tag-issue):
![bildschirmfoto 2017-05-24 um 12 15 45](https://cloud.githubusercontent.com/assets/8235763/26398767/d339b166-407a-11e7-8aee-384e9d8caaf8.JPG)

**Comment by franz-wohlkoenig** [comment]
I suggest to ask help on the [forums](https://forum.joomla.org/).

**Comment by mijalis** [comment]
What actually happens is that when a new tag is typed, for some milliseconds you can see the message _Looking for 'ααααα'_ but then it disappears. So if you type something and you press enter **immediately** then it is saved!
If you delay for a second, then the message _Looking for 'ααααα'_ disappears, so you can't save it.

**Comment by franz-wohlkoenig** [comment]
Can't also not confirm "delay behaviour". Please understand that i close this Issue, hopefully you get a Solution at Forums, thanks.
