### ISSUE TITLE
PHP error in Joomla Update to nightly builds

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-cms#16234]
### Steps to reproduce the issue
Use the custom XML update server in Joomla Update
https://update.joomla.org/core/nightlies/next_patch_list.xml
try to update and see php error log

### Expected result
no php error

### Actual result
PHP Warning:  simplexml_load_file(): /plugins/fields/radio/radio.xml:48: parser error : Opening and ending tag mismatch: fieldset line 23 and field in /libraries/cms/installer/installer.php on line 1997
PHP Warning:  simplexml_load_file(): 				&lt;/field&gt; in /libraries/cms/installer/installer.php on line 1997
PHP Warning:  simplexml_load_file(): 				        ^ in /libraries/cms/installer/installer.php on line 1997
PHP Warning:  simplexml_load_file(): /plugins/fields/radio/radio.xml:49: parser error : expected '&gt;' in /libraries/cms/installer/installer.php on line 1997
PHP Warning:  simplexml_load_file(): 			&lt;/fieldset&gt; in /libraries/cms/installer/installer.php on line 1997
PHP Warning:  simplexml_load_file(): 			        ^ in /libraries/cms/installer/installer.php on line 1997
PHP Warning:  simplexml_load_file(): /plugins/fields/radio/radio.xml:50: parser error : Opening and ending tag mismatch: config line 21 and fields in /libraries/cms/installer/installer.php on line 1997
PHP Warning:  simplexml_load_file(): 		&lt;/fields&gt; in /libraries/cms/installer/installer.php on line 1997
PHP Warning:  simplexml_load_file(): 		         ^ in /libraries/cms/installer/installer.php on line 1997
PHP Warning:  simplexml_load_file(): /plugins/fields/radio/radio.xml:51: parser error : Opening and ending tag mismatch: extension line 2 and config in /libraries/cms/installer/installer.php on line 1997
PHP Warning:  simplexml_load_file(): 	&lt;/config&gt; in /libraries/cms/installer/installer.php on line 1997
PHP Warning:  simplexml_load_file(): 	         ^ in /libraries/cms/installer/installer.php on line 1997
PHP Warning:  simplexml_load_file(): /plugins/fields/radio/radio.xml:52: parser error : Extra content at the end of the document in /libraries/cms/installer/installer.php on line 1997
PHP Warning:  simplexml_load_file(): &lt;/extension&gt; in /libraries/cms/installer/installer.php on line 1997
PHP Warning:  simplexml_load_file(): ^ in /libraries/cms/installer/installer.php on line 1997
PHP Warning:  simplexml_load_file(): /plugins/fields/radio/radio.xml:48: parser error : Opening and ending tag mismatch: fieldset line 23 and field in /libraries/cms/installer/installer.php on line 2215
PHP Warning:  simplexml_load_file(): 				&lt;/field&gt; in /libraries/cms/installer/installer.php on line 2215
PHP Warning:  simplexml_load_file(): 				        ^ in /libraries/cms/installer/installer.php on line 2215
PHP Warning:  simplexml_load_file(): /plugins/fields/radio/radio.xml:49: parser error : expected '&gt;' in /libraries/cms/installer/installer.php on line 2215
PHP Warning:  simplexml_load_file(): 			&lt;/fieldset&gt; in /libraries/cms/installer/installer.php on line 2215
PHP Warning:  simplexml_load_file(): 			        ^ in /libraries/cms/installer/installer.php on line 2215
PHP Warning:  simplexml_load_file(): /plugins/fields/radio/radio.xml:50: parser error : Opening and ending tag mismatch: config line 21 and fields in /libraries/cms/installer/installer.php on line 2215
PHP Warning:  simplexml_load_file(): 		&lt;/fields&gt; in /libraries/cms/installer/installer.php on line 2215
PHP Warning:  simplexml_load_file(): 		         ^ in /libraries/cms/installer/installer.php on line 2215
PHP Warning:  simplexml_load_file(): /plugins/fields/radio/radio.xml:51: parser error : Opening and ending tag mismatch: extension line 2 and config in /libraries/cms/installer/installer.php on line 2215
PHP Warning:  simplexml_load_file(): 	&lt;/config&gt; in /libraries/cms/installer/installer.php on line 2215
PHP Warning:  simplexml_load_file(): 	         ^ in /libraries/cms/installer/installer.php on line 2215
PHP Warning:  simplexml_load_file(): /plugins/fields/radio/radio.xml:52: parser error : Extra content at the end of the document in /libraries/cms/installer/installer.php on line 2215
PHP Warning:  simplexml_load_file(): &lt;/extension&gt; in /libraries/cms/installer/installer.php on line 2215
PHP Warning:  simplexml_load_file(): ^ in /libraries/cms/installer/installer.php on line 2215

### System information (as much as possible)
Joomla 3.7.2 --> 3.7.3dev

**Comment by franz-wohlkoenig** [comment]
is this similar to #16228?

**Comment by rdeutz** [comment]
already fixed in staging, duplicate report, closing
