### ISSUE TITLE
New Joomla3.7.2 installation failed when selecting 'Brochure'

### ISSUE THREAD

**Issue by jbreeding** [joomla/joomla-cms#16245]
### Steps to reproduce the issue
- Download new joomla3.7.2 package
- Select 'Brochure' as sample datas![Select Brochure](http://adminma.odns.fr/jbreeding35/images/select_brochure.jpeg "Select Brochure")

![SQL errors](http://adminma.odns.fr/jbreeding35/images/error_brochure.jpeg "SQL errors")

### Expected result
Successfull Installation.

### Actual result
Installation failed (SQL Errors)

### System information (as much as possible)
Version BdD		5.5.55-0ubuntu0.14.04.1
Version de PHP		7.0.19-1+deb.sury.org~trusty+1
Serveur web		Apache/2.4.20 (Ubuntu 14.04)
Version de Joomla	Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT

### Additional comments
Joomla package downloaded on Joomla.fr 
The joomla installation failed when inserting datasets in the database.

**Comment by brianteeman** [comment]
It would appear that this is an error in the french translation of the sample data.

@Bakual can you handle the reporting of this to the correct place. I am not sure where that is.

Closing here.

**Comment by jbreeding** [comment]
Just to know, there is a specific place for those issues ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16245">issues.joomla.org/tracker/joomla-cms/16245</a>.</sub>

**Comment by Bakual** [comment]
I'd assume it has to be told the people from https://www.joomla.fr/. But pinging @infograf768 is probably the faster way 😄

**Comment by zero-24** [comment]
Isn't the repo here: https://github.com/infograf768/fr-FR-3.x ?

**Comment by jbreeding** [comment]
Ok thanks, i will do that.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16245">issues.joomla.org/tracker/joomla-cms/16245</a>.</sub>

**Comment by infograf768** [comment]
The custom French distribution by joomla.fr includes these sample datas.
It was thought at a time that it was not necessary to modify the installation ini files for core and the custom distrib.

I will inform them that it has confused a user (first time since joomla exists ☺ ) and I will modify the 3.7.3 installation ini files to prevent this confusion in core.

**Comment by infograf768** [comment]
Corrected in core (and also updated, @Bakual .
https://github.com/joomla/joomla-cms/commit/59a9426cf17a7baf28983e3c670c6bf157b78dec

**Comment by jbreeding** [comment]
Thanks infograph, 

I made this post after seeing several users (forum.joomla.fr) who tried this installation with 'Brochure'.
( but I don't anderstand where is the '_confusion_'  ).

**Comment by infograf768** [comment]
@jbreeding 
marc, if you need to use the custom french sample data, you have to pick the distro from joomla.fr

**Comment by jbreeding** [comment]
Of course Jean Marie, and that's what i did...
Joomla 3.7.2 - Édition francophone v1 Nouveau! 05/23/2017

**Comment by infograf768** [comment]
Oh, in this case, there is an issue with that release. I will transmit.

**Comment by infograf768** [comment]
BTW I confirm, when using the French distro and brochure sample data, we do get that error.

**Comment by Opware2000** [comment]
Thank you for your report.
I will see the origin of the error and propose a new version of the French pack. Probably tomorrow or Saturday.

**Comment by infograf768** [comment]
Here is the new sql in the meanwhile:

[sample_brochure_fr.sql.zip](https://github.com/joomla/joomla-cms/files/1030987/sample_brochure_fr.sql.zip)
