### ISSUE TITLE
Can't save custom_fields values inside articles :(

### ISSUE THREAD

**Issue by fmmarmello** [joomla/joomla-cms#16247]
Hello folks, 
I had a previous Joomla installation and updated to 3.7.2.
But I simply can't save my custom fields anymore. (I mean saving the custom field value inside article)

It looks like that is some problem with fields 'filters'.
Are those filters something I set?

My field is set to show in a specific category, but when I try to save it (with valid values), I get the message : Invalid Field : myField

(I had this earlier with calendar custom fields, but the problem was related to a locale specific date_format...)

Please I really need your help!
Thanks in advance
Offtopic: Yes, I had the beta 3.7.0 :( 

3.7.2 - php 7

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding.

**Comment by fmmarmello** [comment]
Sorry
