### ISSUE TITLE
After Upgrading to 3.7.1 and 3.7.2 I am getting multiple e-mails about an update being avaliable (there isn't 3.7.2 is current)

### ISSUE THREAD

**Issue by reboot-sequence** [joomla/joomla-cms#16249]
### Steps to reproduce the issue

Upgraded to 3.7.1 then 3.7.2-- each time after updating I continue to get notifications that I am on 3.7.0 and 3.7.1 is available. Also the default 6 hour notification delay is causing about 4 e-mails a day. I would think one e-mail a day would be sufficient (I will ask my team members if 12 or 24 is okay.

### Expected result

No e-mail notifications when current version is deployed.

### System information (as much as possible)

The system manifest.xml file clearly shows 3.7.2 as current version. Is anyone else experiencing this-- I'd like to not have to disable the plugin.

**Comment by zero-24** [comment]
Can you please go to Extensions -> Manage -> Manage -> search for "Joomla" -> select all -> hit refresh cache

**Comment by zero-24** [comment]
and than show the result here

**Comment by reboot-sequence** [comment]
Here's a screenshot:

![extensionsmanagemanagejoomla](https://cloud.githubusercontent.com/assets/7933738/26451613/cd353672-412a-11e7-8815-89d8e037c973.JPG)

**Comment by reboot-sequence** [comment]
Here's a screenshot-- the first reply post I forgot to select all and refresh-- that's done now:

![extensionsmanagemanagejoomla](https://cloud.githubusercontent.com/assets/7933738/26451674/0b80f72c-412b-11e7-9682-36be0b5f23a6.JPG)

**Comment by reboot-sequence** [comment]
I had checked the manifest XML file under administrator to see what the system thought its version was since it's somewhat hidden these days (I am pretty sure that 2.5 and previous versions used to simply show Version # on the admin panel).

**Comment by Quy** [comment]
Are you referring to the Joomla version? If yes, it is displayed in the lower right corner in the Administration.

**Comment by reboot-sequence** [comment]
Yes, you're correct (I didn't notice it in the lower right), but I am also not sure where the Update Notification plugin is checking against the version number from (if at all or if some other code does that part)... 

However today when looking at various tables on the instance with the issue I did notice a <jos_hash>_update table that had about 10 entries for the same Joomla 3.7.2 update. None of my other working instances of Joomla had that going on so I've removed them (as they were a bunch of duplicate entries for 3.7.2 all for just Joomla, no extensions or anything else). I think that was probably the issue-- so it probably wasn't the notifier that was awry here, it's whatever part of the code is adding stuff to the updates table.

What's really interesting is that we have a staging area for this site, and even in the stage areas copy for this site it didn't have the 10 entries for the 3.7.2 update.

**Comment by brianteeman** [comment]
Go to the extensions menu and them update sites.there is a rebuild option

**Comment by reboot-sequence** [comment]
Ok I did that. Still getting the 6 hour reminder e-mails about 3.7.2. It
shows my current version incorrectly as 3.7.0 in the e-mail. The admin
panel and the administrator XML manifest agree on 3.7.2. Anyone know where
the update notifier reads the version number from.. what it translates
[VERSION_NUMBER] or whatever from and why it may be incorrect?

**Comment by wojsmol** [comment]
@reboot-sequence Go to  Extensions > Manage  > Database and click Fix button.

**Comment by reboot-sequence** [comment]
After doing these steps and making sure the administrator folder contents
were identical (from the staging area) I was good (no e-mails for almost a
week-- until today!). No idea what changed, but today I got an e-mail about
upgrading. It still claims 3.7.0 as the installed version and 3.7.2 as the
installed version. It makes no sense (why today?). Re-did steps provided
above I'll report back in 24 hours.

**Comment by Quy** [comment]
@reboot-sequence Is this still an issue with the latest version?

**Comment by reboot-sequence** [comment]
Not sure anymore. I ended up disabling the plug-in on one of the sites but
I've moved to a different job. Sorry I can't be of more help.
Thanks,
Tom

**Comment by ghost** [comment]
closed as unconfirmed Report. Issue can always be reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16249">issues.joomla.org/tracker/joomla-cms/16249</a>.</sub>
