### ISSUE TITLE
Debug Backtrace does not give source of error

### ISSUE THREAD

**Issue by Hackwar** [joomla/joomla-cms#16241]
### Steps to reproduce the issue
Create a PHP error in the backend, have debugging enabled.

### Expected result
error.php of isis template displays error message with file and line number of the error and backtrace.

### Actual result
file and line number are missing. The actual backtrace does not contain the file that actually created the error, but starts one file up.

### System information (as much as possible)
Joomla 3.7.1, PHP 7.0

### Additional comments
Something like this could be included in /administrator/templates/isis/error.php line 227. 
```
						<?php if ($this->debug) : ?>
							<?php echo htmlspecialchars(' on line ' . $this->error->getLine() . ' in ' . $this->error->getFile(), ENT_QUOTES, 'UTF-8');?>
						<?php endif; ?>
```
However, the code above is not really translated or anything and I'm unsure what the right solution would be in terms of translated error messages?

**Comment by mbabker** [comment]
See https://github.com/joomla/joomla-cms/pull/11675
