### ISSUE TITLE
Truncation not Working for Tag Description in Tag List

### ISSUE THREAD

**Issue by Nick126** [joomla/joomla-cms#16248]
### Steps to reproduce the issue

Create a menu item of type "List of all tags."
From the Options tab while defining this menu item set the "Maximum characters" (under description) to 200 (presumably any number).

### Expected result

The tag description should be truncated at 200 characters according to the menu options above when selecting the menu item above for display.

### Actual result

The full description is always displayed regardless of what value is used to truncate it.

### System information (as much as possible)

Database Version 	5.1.36-community-log
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8_general_ci
PHP Version 	5.3.13
Web Server 	Apache/2.2.11 (Win32) PHP/5.3.13
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.7.0 Stable [ Amani ] 25-April-2017 15:36 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 5.1; rv:52.0) Gecko/20100101 Firefox/52.0 

### Additional comments

The Tags component is misidentifying the parameter string reference used to determine truncation.  components/com_tags/views/tags/tmpl/default_items.php incorrectly uses the identifier "tag_list_item_maximum_characters" when it should be "all_tags_tag_maximum_characters."

**Comment by franz-wohlkoenig** [comment]
Duplicate Report #14667
