### ISSUE TITLE
All tabs in article editor not show

### ISSUE THREAD

**Issue by NothingKai** [joomla/joomla-cms#16252]
Please help

All tabs in article editor joomla 3.7.2 not show.
How to fix it.

Thanks you very much.
![capture](https://cloud.githubusercontent.com/assets/21333744/26424510/a264efa2-40fb-11e7-9620-233f2ef236fc.PNG)

**Comment by dgt41** [comment]
You are experience some javascript error, you need to check your browser's console.
But please use the forum for further help on your problem...

**Comment by NothingKai** [comment]
Thanks for Rep,

But when edit categories, it ok ?
Only error when edit article :(

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding.
