### ISSUE TITLE
3.2.7 - Menu Item NOT loading Articles if you change MENU ELEMENT TYPE

### ISSUE THREAD

**Issue by Moches** [joomla/joomla-cms#16255]
### Steps to reproduce the issue
I created a menu item without having any article just for test reasons, so I used the System URL option, so I could assign any url and I can test my menu item. It worked perfectly.

When I created my category and my article, I tried using the option on the menu item created before to show on a single article, it won't load any article. I did realized that when you select any article the link to the article do not change until you save the menu item. But if you go to the site and test your menu item, it will give a 403 error and I also realized that the menu item does not have the alias of the article in the url, just the alias of the name of the menu item instead. 

### Expected result

To have the appropriate article loaded on the menu item.

### Actual result

403 error and the menu item getting the menu item alias in the url.

### System information (as much as possible)

Joomla! Version	Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Running under PHP 5.6.30

### Additional comments

In the front end, the menu item tries to search for its own alias as an article instead of loading the actual article.

![screen shot 2017-05-24 at 22 48 14](https://issues.joomla.org/uploads/1/5a70cb11ca905898a4c79bb836f87082.jpg)![screen shot 2017-05-24 at 22 48 15](https://issues.joomla.org/uploads/1/f9e48c17955fad687c47e2feafb29096.jpg)![screen shot 2017-05-24 at 22 48 17](https://issues.joomla.org/uploads/1/205e1b26198be67db77a9022b284de4e.jpg)

**Comment by brianteeman** [comment]
the url of a single article menu item is correctly the alias. that is exactly how Joomla is designed to work and is the expected behaviour.

**Comment by franz-wohlkoenig** [comment]
closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16255">issues.joomla.org/tracker/joomla-cms/16255</a>.</sub>

**Comment by Moches** [comment]
Sorry to disagree with you, Yes thats the main idea, that the url of a single article should be the alias, but the alias of the article not the alias of the menu.
The menu is trying to load the alias of its own menu item and not the article it self. I thought it was self explanatory, the alias that you see on the images is the alias of the menu element and not the alias of the article itself (which should be what the menu item would be linking to).

Really sorry if at some point I bother you or thought this was something to make you waste your time. Itys not the case, if I select any other single article the same error will appear.

Not happening with other versions in joomla and the behaivor as you stated is not the same.

Again, sorry because it seems that you felt I was wasting your time.

I just wanted to help with an issue I saw it was wrong.

**Comment by brianteeman** [comment]
If you create a menu item of a type "single article" then the alias of the menu item will be the alias of the URL. this is NOT new behaviour. this is the behaviour of Joomla for at least 10 years. the alias of the article is ONLY used when you follow a link to an article from a category blog or category list page.

**Comment by Moches** [comment]
Then whay the error and why in the other sites, when I hover over the meny item that points to a single article, the alias of the article is the alias on the menu item, and not the other way arround.

**Comment by Moches** [comment]
Ok now I see the confusion here, yes your are right, I did not explain it correctly...

Its correct what you say, its the alias of the artcile not loading when clicking the menu item, which has the appropriate alias as a menu item pointing to a single article. I said that it seems that when saving the manu Item it does not save the article it self on the "Select" article option.

Ok, thanks any way, I am probably the only one having this issue.
