### ISSUE TITLE
[media] No spacing above the Browse button

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#16251]
@ciar4n Probably related to #14506

### Steps to reproduce the issue
Install staging build
Go to Contents > Media
Click `Upload` button

### Expected result
![upload-before](https://cloud.githubusercontent.com/assets/368084/26424256/6ac0b55c-4085-11e7-9e9a-381348e9db39.jpg)

### Actual result
![upload-after](https://cloud.githubusercontent.com/assets/368084/26424250/659972f8-4085-11e7-83a3-abdf2642b497.jpg)

**Comment by ciar4n** [comment]
PR created.. #16253
