### ISSUE TITLE
/libraries/fof/integration/joomla/platform.php contains calls of the deprecated method JApplicationCms->isAdmin()

### ISSUE THREAD

**Issue by nvyush** [joomla/joomla-cms#16269]
### Steps to reproduce the issue
Open the file ```/libraries/fof/integration/joomla/platform.php``` and search the string ```JFactory::getApplication()->isAdmin()```

### Expected result
The string is not found, because the method ```JApplicationCms->isAdmin()``` is deprecated and must be replaced with ```JApplicationCms->isClient('administrator')```.

### Actual result
The string is found at lines 151 and 820.

### System information (as much as possible)
Joomla! 3.7.1.

**Comment by zero-24** [comment]
As this is unmaintained 3rd party code as well it is going to be removed in joomla 4.0. I think we are save here. As the old method is also included until 4.0 :)

Closing for that reason thanks.
