### ISSUE TITLE
Joomla 3.6.5 Cache issues

### ISSUE THREAD

**Issue by ismaelhaider** [joomla/joomla-cms#16261]
### Steps to reproduce the issue
I am using Falang with joomla.When i am switching from English to Arabic or AR to EN.its switching but its not switching all template like menu is on LTR and some parts are on RTL.after refresh page it shows correctly.so i need a refresh page to see correctly.I spoke with Falang and they said its Joomla cache problem.
Note.When i am using Artio Joomsef and try to manage language switching from En to Ar its working correct.but i dont want use Artio sef.i remove it.

**Comment by brianteeman** [comment]
Before anything else please upgrade to Joomla 3.7.2 as there have been a LOT of fixes <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16261">issues.joomla.org/tracker/joomla-cms/16261</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
closed as stated above. Please reopen if Issue stay on latest Version, thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16261">issues.joomla.org/tracker/joomla-cms/16261</a>.</sub>
