### ISSUE TITLE
[3.7.2] LOTS of duplicate queries

### ISSUE THREAD

**Issue by shur** [joomla/joomla-cms#16274]
### Steps to reproduce the issue
Two modules "Articles - Latest" and "Articles - Most Read" displayed on Category blog page.
In each module display 10 or more articles.

Category menu item settings: 
Category > Show Tags: Use Global (Show)
Blog Layout > Intro Articles: 10 

Joomla Debug Console:
![j172_duplicate-queries-for-tags](https://cloud.githubusercontent.com/assets/1245155/26489671/037edb52-4211-11e7-8dc7-b40af5c23c8f.png)

Duplicate Queries Example:
![j172_duplicate-queries-example](https://cloud.githubusercontent.com/assets/1245155/26489680/10397898-4211-11e7-9687-80f9f8cb352c.png)

THIS MODULES DON'T SHOW TAGS! So why do they create so many tag request queries?

#9036 and #9038

**Comment by shur** [comment]
@joomdonation Could you take a look?

**Comment by csthomas** [comment]
There was a discussion about show tags in content model.
Because of B/C in content models the solution is a little complicated.

There was not any interest and I closed PR. 
https://github.com/joomla/joomla-cms/pull/10519

**Comment by mbabker** [comment]
See https://github.com/joomla/joomla-cms/pull/16335 for a potential solution.
