### ISSUE TITLE
3.7.2 Menu Item Alias URL not generated

### ISSUE THREAD

**Issue by grantg182** [joomla/joomla-cms#16276]
### Steps to reproduce the issue
Clean install 3.7.2. Create a second menu. Add a Menu item to the new menu, select System>Menu item alias for the Menu Type. Select a Menu Item you are 'cloning'. Then hit Save.

### Expected result
Save as expected, both menu items alias should be the same.

### Actual result
Main Menu alias is correct - http://localhost/index.php/my-link
New Menu alias is blank - http://localhost/index.php?Itemid=

Note, the itemid is missing/blank in the alias URL. After clicking Save when creating the alias menu, the Link field remains as "index.php?Itemid="

### System information (as much as possible)
Joomla 3.7.2 running on XAMPP 5.6.24 on OSX.

**Comment by franz-wohlkoenig** [comment]
Can't confirm, cause hover on Frontend the Alias-Link you get correct Link and click on it bring correct Page.

**Comment by grantg182** [comment]
Odd. I found if I clicked Clear on the Menu Item field when editing the alias, then re-selecting the menu item and saving, it worked as expected. However, in the administrator, the Link still remains incomplete after saving (i.e. "index.php?itemId=")

**Comment by csthomas** [comment]
Take a look at:
https://github.com/joomla/joomla-cms/pull/13776
https://github.com/joomla/joomla-cms/pull/14265

**Comment by brianteeman** [comment]
It does not matter what the administrator says - what matters is does the alias work

**Comment by brianteeman** [comment]
I am closing this at this time -
