### ISSUE TITLE
Bug ACL / URLS from Joomla 3.7

### ISSUE THREAD

**Issue by didierauss** [joomla/joomla-cms#16271]
# Bug ACL / URLS from Joomla 3.7

I recently upgraded from 3.6.5 to 3.7 (and 3.7.1, 3.7.2) a site that has existed for a long time. I do all the updates regularly. First tested on a version "DEV" before modifying a version in production "PRO".
(And I do well to do that!)

Since the update of joomla 3.7, I encountered a bug with ALC rights management and URLS (whatever rewritting or not, the bug has nothing to do with the .htaccess ... tests done), I m 'Explain :

## **Context:**

On the site in question, some of the articles (news) are accessible only for defined "subscribers":
- The "public" visitor does not see ACTUALITY in the main menu.
- The "public" visitor sees on the HOME page of the site of the module blocks (Last articles or Article of a category ") with the title / category / the beginning of the intro / read more ...
- If the "public" or "subscriber (unidentified)" visitor clicks on a title / "read more", it is directed to the login page (/ component / users /? View = login) See the whole article after.

## **Bug seen since 3.7:**

If the visitor "public" or "subscriber (unidentified)" clicks on a title / "read more", it is not directed to the login page (/ component / users /? View = login) And see the article in the center of the homepage without any password request. We are not directed to a new page.

After analysis, I have found that the URLS have changed since the update 3.7 ... see the explanatory screenshot, example (The site is en fr-FR only):

**3.7**
/96-adherent-actualite/derniere-actualite/personnels-transferes/252-etablissement-public-national-antoine-koenigswarter.html

**3.6.5**
/actualites/actualite-fonction-publique/96-personnels-transferes/252-etablissement-public-national-antoine-koenigswarter.html[captures-uk.pdf](https://issues.joomla.org/uploads/1/4970d9463951d5aa4126509c282b2962.pdf)

I made "public" ACTUALITE in the main menu on joomla 3.7. The bug has disappeared, it is the right URL, we are directed to the right page
actualites/actualite-fonction-publique/96-personnels-transferes/252-etablissement-public-national-antoine-koenigswarter.html

## **Conclusion:**

It seems that a change has occurred in the URLS management with the CLA since 3.7, or a change of configuration ??

I confirm that I have only made the update. I did not change anything else ... I also tested without rewriting the URLs. I reactivated the .htaccess ... The bug remains persistent.
I have no database-level errors in the Joomla Extension / Manage / Database administration

So I'm looking for an explanation, a help, a solution ... I dry a lot!
Thanks for the help

Didier A.

**Comment by PhilETaylor** [comment]
So cutting down your text we get:

> If the visitor "public" or "subscriber (unidentified)" clicks on a title / "read more", it is not directed to the login page (/ component / users /? View = login) 

> We are not directed to a new page.

Which is a known issue with many duplicate open issues.

**Comment by brianteeman** [comment]
Simple and quick fix is to create a login menu item.  It can be set to hidden.  

Closed as a duplicate

**Comment by didierauss** [comment]
Hello,

Sorry, but I keep my remarks ...

Creating a hidden menu changes absolutely nothing ... I tested your comments, and the result is identical!
  This site has worked very well since joomla 2.5 to 3.6 ...

Why since joomla 3.7, the urls have changed as described in my 1st post?

I did a test: I created a module "custom content". I have to manually re-create the entries of the articles of the category (title / intro / read more). I put the right urls, that is up to 3.6.5. I have no problems. If you click on "read more", I am redirected to the login page (without building a login menu item);

Now, if I use the module 'mod_articles_category', the automatically generated URLs are not good:
- it does not redirect to the login page
- displays the complete article on the home page

I repeat this problem has intervened since 3.7 ... Do my remarks ask for more details?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16271">issues.joomla.org/tracker/joomla-cms/16271</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Reopened for further Discussion.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16271">issues.joomla.org/tracker/joomla-cms/16271</a>.</sub>

**Comment by didierauss** [comment]
For info, I have precisely look at how the urls are created (for now rewritting)

**Since Joomla 3.7:**

/ ID (category level III) - alias: category level I / alias: category level II / alias: category level III / ID (article) - alias: article.html

**Before to 3.6.5:**

/ Menu name / alias: menu level level II / ID (category level III - alias: category level III / ID (article) - alias: article.html<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16271">issues.joomla.org/tracker/joomla-cms/16271</a>.</sub>

**Comment by brianteeman** [comment]
@franz-wohlkoenig I assume you added the wrong tag?

**Comment by brianteeman** [comment]
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed. 

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
