### ISSUE TITLE
LOG ENTERIES FOR USERS ACCESS

### ISSUE THREAD

**Issue by shrishtijain** [joomla/joomla-cms#16275]
HELLO 
I AM NEW TO JOOMLA.
I WANT TO KNOW WHERE THE LOGS ENTRIES ARE GETTING GENERATED FOR THE SITE I HAD CREATED. THAT IS WHEN USER LOGIN AT FRONT END THEN WHERE THE RECORDS GET STORED ABOUT THERE LOGIN LOGOUT .
MY  SITE IS WORKING ON LOCAL HOST
THANKS & REGARDS

**Comment by brianteeman** [comment]
Please use the forum for support. See https://forum.joomla.org
