### ISSUE TITLE
Version Note is not saved in the article

### ISSUE THREAD

**Issue by Sieger66** [joomla/joomla-cms#16285]
### Steps to reproduce the issue

Login as "Superadmin
Open a article or create a new article.
Write something in the "Version Note Field"
Save or
Save and Close 
the article.

### Expected result

Version Note is saved in the article.

### Actual result

Version Note is not saved in the article.

### System information (as much as possible)

Joomla! 3.7.2

**Comment by zero-24** [comment]
Is'nt the version note just for the version control? Can you please try the version button and see if this info is saved to the version itself?

**Comment by franz-wohlkoenig** [comment]
@Sieger66 can't confirm issue. Version Note is saved in Version itself, as @zero-24 wrote:
![bildschirmfoto 2017-05-27 um 14 27 20](https://cloud.githubusercontent.com/assets/8235763/26521435/9f366bb4-42e8-11e7-9ba6-53e1a2b07899.jpg)

**Comment by Quy** [comment]
This is the expected behavior. It is a note for a specific version when saved.

**Comment by Sieger66** [comment]
Aaaah yes. Sorry.

Sometimes it is better to read the Helpsite before.(Typical for a lay) 

So we can close this issue, because it my misunderstanding.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16285">issues.joomla.org/tracker/joomla-cms/16285</a>.</sub>

**Comment by brianteeman** [comment]
Closed as requested

**Comment by Adamzynoni** [comment]
cool
