### ISSUE TITLE
Save & New Menu

### ISSUE THREAD

**Issue by julos081** [joomla/joomla-cms#16297]
### Steps to reproduce the issue
After a menu creation, click on save & New

### Expected result
All parameters selected before have to be saved

### Actual result
The assigned menu list is reseted and we need to select again the appropriate assigned menu.

### System information (as much as possible)
joomla 3.7.2
Chrome

**Comment by franz-wohlkoenig** [comment]
Duplicate Report of #15447<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16297">issues.joomla.org/tracker/joomla-cms/16297</a>.</sub>
