### ISSUE TITLE
[4.0] session keepalive?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#16304]
@wilsonge we discussed this at the combined sprint in london

It looks like the session keepalive stuff isnt working in J4 as i am being logged out in J4 much much more often than in j3

**Comment by wilsonge** [comment]
I did do a quick test on that the next day and it seemed to be roughly working for me.

@dgt41 do you have any ideas on this?

**Comment by brianteeman** [comment]
i didnt think you got out of bed the next day

**Comment by wilsonge** [comment]
I can use a laptop from a sofa ;)

**Comment by wilsonge** [comment]
So seriously I tried setting timeout to 2 minutes and 5 minutes and hung around and it seemed to expire at the right time and not expire before that.

**Comment by brianteeman** [comment]
But is the keepalive script keeping it alive beyond the session timeout when it is supposed to?

**Comment by dgt41** [comment]
Probably https://github.com/joomla/joomla-cms/blob/4.0-dev/media/system/js/keepalive.js#L21
should be more specific like 
```js
keepaliveInterval = keepaliveOptions.interval ? parseInt(keepaliveOptions.interval) : 45 * 1000;

```

**Comment by brianteeman** [comment]
it just logged me out while i was doing a form search

**Comment by Bakual** [comment]
It's actually not the keepalive. It's the session in general which doesn't get refreshed.
To reproduce:
* Set sesssion lifetime to 1 minute
* Do stuff for one minute. Even randomly clicking things will get you logged out after that minute.

**Comment by Bakual** [comment]
Umm, I have that behavior also in staging. Is that new? I thought a page reload used to reset the session lifetime?

**Comment by wilsonge** [comment]
Update:
I've been playing with this a bit more and I agree with Thomas - I logged the responses of the javascript keepalive. Set a session time of two minutes (which mean the session refreshes every 1 minute). The first keepalive returned good. the second returned a 403 (because i no longer had permission to access the backend because my session had timed out :( )

**Comment by brianteeman** [comment]
I am wondering if it is related to the session handler. I have noticed lots of session******.php files

**Comment by wilsonge** [comment]
OK. I've literally spent days figuring this out. And it's a one line fix (of course). https://github.com/joomla/joomla-cms/pull/17623
