### ISSUE TITLE
[4.0] Control label class for title

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#16309]
The control-label class has a fixed width of 220px - in most cases this is a sensible value as seen on an option screen.

But here in the title and alias fields it creates a very big separation between the label and the field. For some users this will create a cognitive seperation between the label and the field which is defeating the purpose of the label.

<img width="628" alt="screenshotr11-28-23" src="https://cloud.githubusercontent.com/assets/1296369/26546464/fd5bb1a2-4461-11e7-8cf2-9c69d7e099f4.png">

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/16333

**Comment by brianteeman** [comment]
Closed as we have a PR

**Comment by brianteeman** [comment]
Really opened
