### ISSUE TITLE
[4.0] Menu expand collapse behaviour

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#16305]
If you compare the two movies below you will see a difference in behaviour between closing submenu by clicking on the x and closing the submenu by clicking on the icon
in the first it is a smooth action and the icon doesnt change and in the other the icon etc are reloaded from off-left 

![menu1](https://cloud.githubusercontent.com/assets/1296369/26545295/f940ff82-445c-11e7-98fd-a40dc93fb084.gif)

![menu2](https://cloud.githubusercontent.com/assets/1296369/26545296/f9469c30-445c-11e7-905d-04daa2673b73.gif)

**Comment by ciar4n** [comment]
PR created... #17070
