### ISSUE TITLE
Breadcrumbs unordered list is not semantic

### ISSUE THREAD

**Issue by yaume** [joomla/joomla-cms#16312]
> the HTML is not semantic. Coding a breadcrumb as an unordered list makes it seem like the items are on the same hierarchical level, like it's a set of items in a row. The items in a breadcrumb are not, they represent a path, with each link being a "child" of the last.
> -- <cite>[Geert van der Heide](https://css-tricks.com/triangle-breadcrumbs/#comment-84896)</cite>
According to `[Google guides](https://developers.google.com/search/docs/data-types/breadcrumbs) and [BreadcrumbList](http://schema.org/BreadcrumbList) ordered lists seem to be more semantically good

**Comment by brianteeman** [comment]
I am closing this as we have a pr. If you create a pr you don't need to create an issue at the same time

**Comment by yaume** [comment]
Sorry about that
