### ISSUE TITLE
[4.0] Unit Test Organization for new classes

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#16321]
New library classes being added are generally namespaced.  Our unit test organization right now isn't set up to support this.  We need to sort out a way to organize our test suites, and write tests for the new code.

**Comment by rdeutz** [comment]
Would be great if we find a time slot in Krakow to speak about the organisation of the test suites. 

/cc @wilsonge @yvesh

**Comment by mbabker** [comment]
> Would be great if we find a time slot in Krakow to speak about the organisation of the test suites.

We're here all week 😉

**Comment by mbabker** [comment]
Just leaving a note here (mainly so I don't forget to one day go back and write the tests once we figure out the logistics), we backported `\Joomla\CMS\Log\DelegatingPsrLogger` into 3.8 so now we do have namespaced code in 3.x without a global namespace counterpart and hence doesn't just fit in to our existing structure.
