### ISSUE TITLE
[4.0] Clear search fails

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#16344]
### Steps to reproduce the issue
Search any form and then clear the search

### Expected result
form resets

### Actual result
form and search field do not change
![searchclear](https://cloud.githubusercontent.com/assets/1296369/26558711/c3229cda-44a2-11e7-8c7d-8439f4cea17f.gif)

**Comment by tonypartridge** [comment]
Also, the html on these buttons contains a title tag with no value.

**Comment by Bakual** [comment]
It clears the search filters though 😄

**Comment by tonypartridge** [comment]
It actually added the filter for me on a fresh install, I typed some garbage and hit clear it submitted the form with the text based search.

**Comment by shubhamnba2009** [comment]
https://github.com/joomla/joomla-cms/issues/8421
I came around one of this closed issue that says it is PHP version responsible for the above issue. Is it possible that maybe it is responsible here too!!

**Comment by brianteeman** [comment]
Closing in favour of #17195
