### ISSUE TITLE
Json decoding issue (again)

### ISSUE THREAD

**Issue by davidascherG** [joomla/joomla-cms#16348]
### Steps to reproduce the issue
in all my articles that were created before May 2012 (I am not sure which Joomla! version that would have been) the Json decoding problem re-appeared when I upgraded to Joomla! v 3.7.2 from Joomla! 3.4.8 and with PHP v5.6.30.  The front end displays the usual Json error when displaying the article and the backend displays:
 An error has occurred.
0 Error decoding JSON data: Syntax error

Those old articles have metadata that looks like this:

{&amp;quot;robots&amp;quot;:&amp;quot;&amp;quot;,&amp;quot;author&amp;quot;:&amp;quot;&amp;quot;,&amp;quot;rights&amp;quot;:&amp;quot;&amp;quot;,&amp;quot;xreference&amp;quot;:&amp;quot;&amp;quot;}

I cannot imagine HOW it ended up this way.... it is obviously very wrong. NONE of the extensions I have used on the site would have touched the content metadata field, so I suspect that this bad stuff was entered by some prior version of the joomla core. And that means that this is probably not the only site that will experience this problem as they update to Joomla 3.7.2. Oddly, the problem does not occur when viewing the same articles in Joomla version 3.4.8 --- and yes, I checked and the metadata is identical bad stuff.

I was able to get around this for now by changing line line 71 in libraries/vendor/joomla/registry/src/Format/Json.php from
$decoded = json_decode($data);
to 
$decoded = json_decode( htmlspecialchars_decode (html_entity_decode($data, ENT_QUOTES ) ) ) ;

### Expected result
proper display of article

### Actual result
Json error in libraries/vendor/joomla/registry/src/Format/Json.php

### System information (as much as possible)
This what I got from my hosting provider - SiteGround
Operating system – CentOS 6.4 (Final) (64 bit)
Apache Version – Apache 2.4 – This Web Server is modified by us
PHP Versions- PHP 5.6.3 
MySQL* Version – MySQL 5.6
Zend Optimizer – 3.3.3
zlib/1.2.3
libidn/0.5.6
Kernel version – 3.12.18-clouder0 – This Kernel is our own build!
mod_rewrite is installed

### Additional comments
This is a problem that needs to be fixed once and for all in the Joomla kernel. It has nothing to do with extensions of any kind. It makes no sense to penalize people who have been using Joomla for a long time by telling them they have to fix their databases (as was recommended before). This is a Joomla core problem; not a user problem; not an extension problem.

**Comment by tonypartridge** [comment]
What editor are you using on these sites out of curiosity?

**Comment by mbabker** [comment]
The only code fix that can be made is to revert to the previous behavior of silently ignoring broken JSON data, which is bad for a lot more reasons than the current issue of the system groaning and not handling this error state.  We generally do not commit SQL updates to user data, and attempting to scan for this issue and resolve it as part of a regular update would be rather problematic and potentially lead to timeouts while running the update depending on the size of your site.

FWIW, this is the first report I've seen where quotes were HTML encoded in the database, usually it's some other syntax error (too much escaping on quotes, invalid bracket count) that is the issue.  And FWIW, core doesn't have a process that tries to HTML encode JSON fields before storing it to the database, how it got there along the way would just be playing the blame game between us and extension developers and lead to annoyed people with no productive result.

So, as annoying as it is, the only fix is for users to correct their database to ensure valid JSON strings are stored in it or demand that Joomla revert the error checking which gives the impression your site is working but whatever data was supposed to be used in that broken string won't be read and that could lead to things not working the way you expect (some data not being used in the right context for example).

**Comment by brianteeman** [comment]
It is a 2 second fix using https://github.com/renekreijveld/JoomlaJsonCheck

For the record you onlly just discovered it because you didnt keep your site upto date.

If you need further support please use the forum http://forum.joomla.org

**Comment by davidascherG** [comment]
jedit. since the site started way back with Joomla 1.x.

  _____
