### ISSUE TITLE
[4.0] New module > Error 500

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#16350]
### Steps to reproduce the issue
type in URL:
administrator/index.php?option=com_modules&view=select

got:
View not found [name, type, prefix]: select, html, administrator
![bildschirmfoto 2017-05-30 um 06 36 43](https://cloud.githubusercontent.com/assets/8235763/26568278/651f17ca-4502-11e7-8f36-664984fb2049.jpg)
### System information
4 (latest nightly build)
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
Its my fault - it should have been preview and positions not preview and select

**Comment by wilsonge** [comment]
OK I've reverted the file removal. I'm going to leave the deprecated notices there until they can be fixed :)

**Comment by brianteeman** [comment]
thanks - so I should do a new PR for 3.x to correct the deprecation and then a new pr for 4 to remove the correct files

**Comment by wilsonge** [comment]
Yup :)

**Comment by brianteeman** [comment]
ok will di it this afternoon - thanks and sorry
