### ISSUE TITLE
Invalid controller: name='file', format='html'

### ISSUE THREAD

**Issue by jamesmakau18** [joomla/joomla-cms#16351]
### Steps to reproduce the issue
when i try to upload a file e.g a picture  through joomla media

### Expected result
To upload the picture in the desired directory

### Actual result

i get an error "Invalid controller: name='file', format='html'"

### System information (as much as possible)
Also i can upload components or any other files. And the file uploader has been working for the last three months

**Comment by franz-wohlkoenig** [comment]
please have a Look if this Issue is similar: #16238

**Comment by franz-wohlkoenig** [comment]
you write in Issue Tracker "Build: 3.4.8" > please update to latest Version.

**Comment by brianteeman** [comment]
i am closing this at this time. Please update to the latest version of Joomla
