### ISSUE TITLE
Default session handler not working on nginx

### ISSUE THREAD

**Issue by jsanchezgr** [joomla/joomla-cms#16364]
After upgrading to 3.7.2 in my dev environment, it seems that session does not work on nginx + phpbrew 

### Steps to reproduce the issue
1. In the configuration.php file set `public $session_handler = 'none';`
2. Try to load any page / login

### Expected result
Normal behavior

### Actual result
`Error displaying the error page`

### System information (as much as possible)
Ubuntu 16.04 LTS
nginx 1.10.0
php 7.1.5 + fpm

### Additional comments
The error happens when Joomla! tries to start the session with no success in /libraries/joomla/session/handler/native.php
````
if (!session_start())
{
      throw new RuntimeException('Failed to start the session');
}
````

In configuration.php if I set public `$session_handler = 'database';` everything works fine.

**Comment by tonypartridge** [comment]
Why is session handler set to none? This is not possible in the Joomla! configuration page. It should always be database or file.
![screen shot 2017-06-02 at 16 01 52](https://cloud.githubusercontent.com/assets/1400982/26731718/d406c78a-47ac-11e7-9d69-e0ce5df941c4.jpg)

**Comment by andrepereiradasilva** [comment]
i have nginx and cannot confirm the issue

anyway the session handler doesn't have nothing to do with nginx. nginx does not process the sessions.

The session handler "PHP" (the config `public $session_handler = 'none';`), get the session handler and save path from the values configured in the php environment: php.ini (or in some cases in php-fpm pools config files).

Check your log files for errors.
Check your php.ini configs `session.save_handler = xxxxx` and `session.save_path = xxxxx`

See https://github.com/joomla/joomla-cms/pull/8565#issuecomment-164255663 for more info

@franz-wohlkoenig imho this can be closed

**Comment by franz-wohlkoenig** [comment]
closed as suggested.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16364">issues.joomla.org/tracker/joomla-cms/16364</a>.</sub>
