### ISSUE TITLE
Main menu and Alias menu active same time

### ISSUE THREAD

**Issue by rajmohanvy** [joomla/joomla-cms#16371]
Hi,

I have menus of articles in main menu, one of my menu is alias of main menu, where every i open menu both menus are highlighting same time. please find the screen shot. 

![expected](https://cloud.githubusercontent.com/assets/27351166/26594691/3b7079a8-4586-11e7-8c45-8ea816a05020.png)
![expected-alias](https://cloud.githubusercontent.com/assets/27351166/26594689/3b649548-4586-11e7-9c7e-ce0d11c1d1ac.png)

![about](https://cloud.githubusercontent.com/assets/27351166/26594690/3b674806-4586-11e7-931a-20dd1433fa08.png)

PHP Version : 7.0 
Joomla          : 3.0.2

**Comment by brianteeman** [comment]
And?

**Comment by rajmohanvy** [comment]
@brianteeman 

That's it.

**Comment by brianteeman** [comment]
what is the problem - seems that everything is working correctly to me

**Comment by rajmohanvy** [comment]
@brianteeman 

The output i like
![expected](https://cloud.githubusercontent.com/assets/27351166/26595048/a9e8f8fa-4587-11e7-8ede-3dbfe587973a.png)
![expected-alias](https://cloud.githubusercontent.com/assets/27351166/26595047/a9d7ca80-4587-11e7-9832-6529d148c14e.png)

But the output i got 
![about](https://cloud.githubusercontent.com/assets/27351166/26595058/b60d077a-4587-11e7-93e7-b40d5442822b.png)

**Comment by brianteeman** [comment]
That is the expected behaviour

**Comment by rajmohanvy** [comment]
@brianteeman 

Is there any option to fix this.

**Comment by brianteeman** [comment]
dont have an alias

**Comment by rajmohanvy** [comment]
@brianteeman 

Is there any other method or override to fix this.

**Comment by franz-wohlkoenig** [comment]
I think this Issue is for [forums](https://forum.joomla.org/) as this repository concerns Joomla coding, so i close this.

**Comment by rajmohanvy** [comment]
@franz-wohlkoenig 

My client won't like to some override function and we fix with menu ID, so my question how can create a joomla installer of my override code.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16371">issues.joomla.org/tracker/joomla-cms/16371</a>.</sub>
