### ISSUE TITLE
Menu Item Save and New looses Menu selection.

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#16373]
When select a menu and then new item the menu is pre-selected within the menu, this is great and speeds up development.

When you click save and new, you still expect the menu you have previously selected / are in to be used. But instead it reverts to the menu block with the default menu item in. In my case Main Menu.

**Comment by Quy** [comment]
Duplicate https://github.com/joomla/joomla-cms/issues/15447#issuecomment-302128204

**Comment by franz-wohlkoenig** [comment]
closed as duplicated Report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16373">issues.joomla.org/tracker/joomla-cms/16373</a>.</sub>
