### ISSUE TITLE
[4.0] "Reinstall Joomla core files" > Error

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#16377]
#### Joomla Update > Live Update > Reinstall Joomla core files:
`The options param must be an array or implement the ArrayAccess interface.`
![bildschirmfoto 2017-05-31 um 07 13 37](https://cloud.githubusercontent.com/assets/8235763/26616676/b1500af4-45d0-11e7-929b-1646e54766ac.jpg)
#### Settings for Update:
![bildschirmfoto 2017-05-31 um 07 14 22](https://cloud.githubusercontent.com/assets/8235763/26616684/cced2ae4-45d0-11e7-812b-196bd964b06b.jpg)
### System information
4 (latest nightly build)
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by mbabker** [comment]
Enable debug mode please and post the error with the stack trace.

**Comment by franz-wohlkoenig** [comment]
![bildschirmfoto 2017-05-31 um 09 31 05](https://cloud.githubusercontent.com/assets/8235763/26620642/e7a321dc-45e3-11e7-9a17-ffb808c1e44d.jpg)

**Comment by tonypartridge** [comment]
@mbabker wasn't @wilsonge working on J4 yesterday 😜

**Comment by mbabker** [comment]
That's usually the root of all our problems :rofl:

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/commit/53fbfadc5e0ad610e24c4226bbab0367e5569919 fixes this.  In general parameter types in the HTTP API are a bit more strict, no more passing null into places that are expecting an array type item.
