### ISSUE TITLE
[4.0] New module > Error 0

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#16379]
### Steps to reproduce the issue
Similar #16350: Modules > New > Choose an Module Type:
![bildschirmfoto 2017-05-31 um 09 38 30](https://cloud.githubusercontent.com/assets/8235763/26620927/19e7d43e-45e5-11e7-80c5-0b5c62af818e.jpg)
### System information
4 (latest nightly build)
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by mbabker** [comment]
@laoneo or @joomdonation it looks like the `$this->getTable()` call is failing here (returning boolean instead of a Table object).

**Comment by joomdonation** [comment]
I will check this. The local install I installed yesterday doesn't have this error. Will re-download and check it

**Comment by laoneo** [comment]
The MVCFactory is probably not passed down the chain.

**Comment by joomdonation** [comment]
MvcFactory is not used to create table object in this model. For some reasons, I could not re-procedure this issue myself in latest 4.0-dev. Could anyone confirms this issue?

**Comment by mbabker** [comment]
My gut feeling is if it works in the git repo or with a fresh install of the nightly build, it's an issue with trying to upgrade a nightly build (which is most assuredly broken right now, the only update logic we have in place is some of the SQL changes).

**Comment by franz-wohlkoenig** [comment]
Can install full Package if it helps.

**Comment by joomdonation** [comment]
Yes, please !

**Comment by franz-wohlkoenig** [comment]
New Module after full-Package-Install works. looks like @mbabker wrote ([Comment](https://github.com/joomla/joomla-cms/issues/16379#issuecomment-305121058)).
