### ISSUE TITLE
[4.0] RFC do not display language options unless site is multilingual

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#16370]
When a site is only in one language there really is no need to display any of the language options below (there are probably other areas too).

We have an api we can check and we should do if (Multilanguage::isEnabled()). 

It really makes no sense to display the language stuff in a monolingual site and just adds unneeded complexity to the ui
![articles joomla 4 administration 1](https://cloud.githubusercontent.com/assets/1296369/26593719/148d303e-455d-11e7-96bb-b1a929629e86.png)
![articles joomla 4 administration](https://cloud.githubusercontent.com/assets/1296369/26593720/14dd6c3e-455d-11e7-9169-b257218672c2.png)
![articles edit joomla 4 administration 1](https://cloud.githubusercontent.com/assets/1296369/26593717/1486bd76-455d-11e7-9a03-346935370233.png)
![articles edit joomla 4 administration](https://cloud.githubusercontent.com/assets/1296369/26593718/1489893e-455d-11e7-8614-ad37b77e868b.png)

**Comment by Bakual** [comment]
The associations tab is already hidden if the site isn't multilingual.
As far as I know it's only the language select that is always shown.

**Comment by brianteeman** [comment]
all the more reason to remove this useless column and field

**Comment by brianteeman** [comment]
Actually the associations tab is hidden if associations is not enabled - it uses `JLanguageAssociations::isEnabled();`
which is a different and more specific check than the one i proposed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16370">issues.joomla.org/tracker/joomla-cms/16370</a>.</sub>

**Comment by infograf768** [comment]
`JLanguageAssociations::isEnabled()` implies `JLanguageMultilang::isEnabled()`
https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/language/associations.php#L140

Now, about the RFC.
We have to take into account the fact that some 3rd party extensions may be using the language field without using our core language filter plugin. Therefore `JLanguageMultilang::isEnabled()` can't be the condition.

One solution I have been considering for a while is to create a new Global Configuration parameter. Obviously, when using our core mutilingual functionality, that parameter should be set (for example, enabling the core language filter plugin would automatically set that param if not done yet) and 3rd party multilingual extensions would also have to use it. (not B/C)

Now, practically, we have a lot of places where the field, list, filters, js, display/use Content Languages.
Which means a huge refactoring of the whole CMS in function of that new parameter afaik.

**Comment by brianteeman** [comment]
> We have to take into account the fact that some 3rd party extensions may be using the language field without using our core language filter plugin. Therefore JLanguageMultilang::isEnabled() can't be the condition.

This is for J4 so we can break backwards compatibility and make it the conditions

> Now, practically, we have a lot of places where the field, list, filters, js, display/use Content Languages.
Which means a huge refactoring of the whole CMS in function of that new parameter afaik.

so no reason not to do it then

**Comment by infograf768** [comment]
Looks like you did not read carefully what I wrote;

> We have to take into account the fact that some 3rd party extensions may be using the language field without using our core language filter plugin. Therefore `JLanguageMultilang::isEnabled()` can't be the condition.

We can't force any 3rd party to use our system plugin if they devise another way to implement a multilingual solution for Joomla. 

`JLanguageMultilang::isEnabled()` means that the **language filter system plugin is enabled**, which would break any 3rd party wanting to devise their own solution without using it.

This is why I propose to use instead a global parameter which we also would use in our core implementation, i.e.  for core `JLanguageMultilang::isEnabled()` would include that new param and 3rd party would ONLY use that new param to display all language-related fields, etc.

**Comment by infograf768** [comment]
> the exact same argument could have been used against using JLanguageAssociations::isEnabled() but it wasnt

You definitely do not (want to?) understand.
`JLanguageAssociations::isEnabled()` is totally linked to our core multingual system and `JLanguageMultilang::isEnabled()`. 

It may not be used by some existing or to be proposed 3rd party solutions which would prefer not using our core solution.

I am not making an argument. I am not against this RFC, but it should be done imho with a new API which is a Global Config parameter.

Your reply is not necessary.
