### ISSUE TITLE
[4.0] com_joomlaupdate > Error

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#16376]
### Steps to reproduce the issue
Update Joomla using downloaded Joomla_4.0.0-dev-Development-Update_Package.zip:
`Call to a member function clean() on boolean`
![bildschirmfoto 2017-05-31 um 07 08 11](https://cloud.githubusercontent.com/assets/8235763/26616575/ee72bf18-45cf-11e7-9a8a-d6a2fe44c292.jpg)

Update Channel: Custom Url https://update.joomla.org/core/nightlies/next_major_list.xml

### System information
4 (latest nightly build)
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by franz-wohlkoenig** [comment]
@mbabker:
![bildschirmfoto 2017-05-31 um 09 34 41](https://cloud.githubusercontent.com/assets/8235763/26620774/6f9913a8-45e4-11e7-91cf-1cce4e062301.jpg)

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_admin/script.php#L2349 needs to be updated to cope with the component having been namespaced.

**Comment by franz-wohlkoenig** [comment]
Fresh Install nightly build full Package got other Error:
![bildschirmfoto 2017-05-31 um 10 39 05](https://cloud.githubusercontent.com/assets/8235763/26623266/7cc7a766-45ed-11e7-9d72-24f473ef514e.jpg)

**Comment by mbabker** [comment]
Same as https://github.com/joomla/joomla-cms/issues/16377 - all the issues with the HTTP adapter are fixed there, nightly build when it runs again will have that fix.

**Comment by mbabker** [comment]
This issue should stay open.  The `com_admin` update script still needs updated for 4.0 changes.

**Comment by joomdonation** [comment]
PR is https://github.com/joomla/joomla-cms/pull/16388

**Comment by joomdonation** [comment]
@franz-wohlkoenig Please close this issue as it was sorted

**Comment by franz-wohlkoenig** [comment]
[Comment mbabker](https://github.com/joomla/joomla-cms/issues/16376#issuecomment-305138691): "This issue should stay open. The com_admin update script still needs updated for 4.0 changes."

**Comment by joomdonation** [comment]
It was updated in PR #16388 and that PR was merged
