### ISSUE TITLE
Itemid Appended to User Urls

### ISSUE THREAD

**Issue by bboilard** [joomla/joomla-cms#16383]
Issue with Itemid=435 being appended to the end of these users urls. Itemid 435 is the Home page Menu ID....
Using SEF, Joomla 3.7.2, PHP 5.6 - all working fine before 3.7.0 update. How can I get rid of this Itemid=435.

/component/users/?view=reset?Itemid=435
/component/users/?view=remind?Itemid=435
/component/users/?view=registration?Itemid=435
/component/users/?view=login?Itemid=435
/component/users/profile?Itemid=435

These are the correct URL's I want to send people to... but the new updates are appended ?Itemid=435

/component/users/?view=reset
/component/users/?view=remind
/component/users/?view=registration
/component/users/?view=login
/component/users/profile

### Expected result
Item435 is the Home page menu ID - I can't delete it... but don't want home page displaying when people go to register. This started on the update 3.7.0 and 3.7.2 - I know it's in components/users and pretty sure it's in the router.php but I have no idea what to change to prevent Item435 appending to the end.

**Comment by brianteeman** [comment]
Just create a menu to the user's component

**Comment by bboilard** [comment]
That worked as a work around, but should I need to do that when I didn't need to do that before?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16383">issues.joomla.org/tracker/joomla-cms/16383</a>.</sub>

**Comment by bboilard** [comment]
No I noticed the registration system is not working at all. Upon registration the user is not showing up in the user list at all.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16383">issues.joomla.org/tracker/joomla-cms/16383</a>.</sub>

**Comment by brianteeman** [comment]
The first part of your issue has been resolved for 3.7.3 

The second issue is unrelated and you should use the forum for support https://forum.joomla.org
