### ISSUE TITLE
[4.0] Breadcrumbs messed

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#16392]
### Steps to reproduce the issue
Breadcrumbs on Article-Page:
![bildschirmfoto 2017-05-31 um 16 26 29](https://cloud.githubusercontent.com/assets/8235763/26636870/3a04ed36-461e-11e7-89bc-45ee61adfdb4.jpg)
### System information
4 (latest nightly build)
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/16405
