### ISSUE TITLE
[4.0] Advanced Permissions Report error

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#16395]
### Steps to reproduce the issue

1. In the backend, go to User Manager
2. Click on "**Advanced Permissions Report**"

### Actual result

> Class 'Joomla\Component\Users\Administrator\Model\JFactory' not found

### System information (as much as possible)

- Joomla 4-nightly
- PHP 7.0.10

**Comment by laoneo** [comment]
https://github.com/joomla/joomla-cms/pull/16397 should fix it

**Comment by C-Lodder** [comment]
closing for PR
