### ISSUE TITLE
[com_content] /components/com_content/views/form/view.html.php contains unneeded check

### ISSUE THREAD

**Issue by nvyush** [joomla/joomla-cms#16409]
### Steps to reproduce the issue
Code review of the file [/components/com_content/views/form/view.html.php](https://github.com/joomla/joomla-cms/blob/staging/components/com_content/views/form/view.html.php), lines 49 — 77.

### Expected result
```if (!empty($this->item->id))```

### Actual result
```if (!empty($this->item) && isset($this->item->id))```

### System information (as much as possible)
Joomla 3.7.2

### Additional comments
The check ```!empty($this->item)``` is unneeded or must be above. E.g., this check is absent at the line 53.
I think, it is possible to join the statements of if conditions at the lines 72 and 77.

**Comment by Bakual** [comment]
Since you already propose some code, can you please create a Pull Request so it can be tested?
https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by nvyush** [comment]
Bakual
I have some trouble with this now.

**Comment by Bakual** [comment]
I can try to help if you tell me what the trouble is :smile:

**Comment by nvyush** [comment]
I use online github. My fork is inconsistent. I can't create second fork and I don't want to drop my fork.

**Comment by Bakual** [comment]
If you edit the file on this repo instead of your fork, then GitHub will automatically create a new branch in your fork based on this repo here.

**Comment by nvyush** [comment]
Closed as we have PR #16412.
Thanks, Bakual.
