### ISSUE TITLE
[4.0] Open com_config > Error 0

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#16407]
### Steps to reproduce the issue
Open "Global configuration": `Argument 1 passed to Joomla\CMS\Form\FormField::setForm() must be an instance of Joomla\CMS\Form\Form, instance of JForm given, called in /Applications/MAMP/htdocs/4/libraries/joomla/form/form.php on line 1915`
![bildschirmfoto 2017-06-01 um 06 01 05](https://cloud.githubusercontent.com/assets/8235763/26664192/ed69413a-468f-11e7-83d2-e05eca2d85e8.jpg)
### System information
4 (latest nightly build)
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by mbabker** [comment]
I'm pretty sure this is the type of thing https://github.com/joomla/joomla-cms/pull/16361 was addressing, George just has a miserable day of merging 3.8 up to 4.0 ahead of him before it is included in the 4.0 code.

**Comment by C-Lodder** [comment]
Can't replicate this issue. Try fetching the latest code from the repo and try again.

**Comment by franz-wohlkoenig** [comment]
Using joomla-cms-4.0-dev works. Closed.
