### ISSUE TITLE
[4.0] Open com_modules > Error 0

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#16408]
### Steps to reproduce the issue
Open
`administrator/index.php?option=com_modules` 
get: 
`Argument 1 passed to Joomla\CMS\Form\FormField::setForm() must be an instance of Joomla\CMS\Form\Form, instance of JForm given, called in /Applications/MAMP/htdocs/4/libraries/joomla/form/form.php on line 1915`
![bildschirmfoto 2017-06-01 um 06 04 33](https://cloud.githubusercontent.com/assets/8235763/26664232/40abbdc8-4690-11e7-9355-438336e24793.jpg)
Similar #16407

### System information
4 (latest nightly build)
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
Can't replicate this issue. Try fetching the latest code from the repo and try again.

**Comment by franz-wohlkoenig** [comment]
Using joomla-cms-4.0-dev works. Closed.
