### ISSUE TITLE
Orverride code of menu alias issue

### ISSUE THREAD

**Issue by rajmohanvy** [joomla/joomla-cms#16410]
Hi team,

I'm override the menu modules, please let me know is that correct or not.

  **Line     : 35
  Location : /var/www/joomla/modules/mod_menu/tmpl/
  File     : default.php**

    if (in_array($item->id, $path))
    {
        $class .= ' active';
    }

 **Replaced with**

    if (in_array($item->id, $path) && $item->type != 'alias')
    {
        $class .= ' active';
    }

  **Line     : 35
  Location : /var/www/joomla/modules/mod_menu/tmpl/
  File     : default.php**

	if (count($path) > 0 && $aliasToId == $path[count($path) - 1])
	{
		$class .= ' active';
	}
	elseif (in_array($aliasToId, $path))
	{
		$class .= ' alias-parent-active';
	}

 **Replaced with**

        if (count($path) > 0 && $item->id == $path[count($path) - 1])
	{
		$class .= ' active';
	}
	elseif (in_array($aliasToId, $path))
	{
		$class .= ' alias-parent-active';
	}

  **Line     : 53
  Location : /var/www/joomla/modules/mod_menu/tmpl/
  File     : default_url.php**

 echo JHtml::_('link', JFilterOutput::ampReplace(htmlspecialchars($item->flink, ENT_COMPAT, 'UTF-8', false)), $linktype, $attributes);

 **Replaced with**
 
  $link = JUri::base(true).'/index.php/'.$item->alias;

  echo JHtml::_('link', JFilterOutput::ampReplace(htmlspecialchars($link, ENT_COMPAT, 'UTF-8', false)), $linktype, $attributes);

**Comment by zero-24** [comment]
This here is not a support forum for custom code. Please ask such questions in the forum at forum.joomla.org or the development mailing lists: 
https://groups.google.com/forum/m/#!forum/joomla-dev-general

The other way around would be just try it out ;)
