### ISSUE TITLE
[com_fields] Field groups ordering not working properly

### ISSUE THREAD

**Issue by Hurmeli** [joomla/joomla-cms#16420]
### Steps to reproduce the issue

Create Field Groups in freshly installed Joomla 3.7.2. Use the drag and drop to re-arrange them.

### Expected result

Field Groups in _Articles: Edit_ should be in same order as in the _Articles: Field Groups_ page.

### Actual result

Field Groups seem to be in semi random order, where the ordering seems to affect some of them but sometimes one or two Field Groups are put in random position.

### System information (as much as possible)

Linux MSPQNAS01 3.12.6 #1 SMP Mon Mar 13 01:11:46 CST 2017 x86_64
5.5.51-MariaDB
PHP Version 5.5.38
Apache
Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT

### Additional comments

In case the Field Group titles have something to do with this, the Field Group names I used were:
Sisältö, Taulukot, Kuvat ja videot, Otsikko ja ingressi. 

Side note about ordering Fields themselves. When ordering them, the bottom Field in _Articles: Fields_ ends up being at top in _Articles: Edit_ view. This seems bit backwards to me.

**Comment by franz-wohlkoenig** [comment]
similar #14355 (there about Fields).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16420">issues.joomla.org/tracker/joomla-cms/16420</a>.</sub>

**Comment by Quy** [comment]
> Side note about ordering Fields themselves. When ordering them, the bottom Field in Articles: Fields ends up being at top in Articles: Edit view. This seems bit backwards to me

Fixed in #16183

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16183<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16420">issues.joomla.org/tracker/joomla-cms/16420</a>.</sub>

**Comment by Quy** [comment]
@franz-wohlkoenig I think this is a different issue about field groups and not about fields, therefore, should be reopened.

My initial reply addressed to the comment made in Additional Comments.

**Comment by franz-wohlkoenig** [comment]
reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16420">issues.joomla.org/tracker/joomla-cms/16420</a>.</sub>

**Comment by laoneo** [comment]
Please test #16663 as it should fix the issue.

**Comment by brianteeman** [comment]
Closed as we have a PR for testing
