### ISSUE TITLE
[Captcha - ReCaptcha] in frontend editor

### ISSUE THREAD

**Issue by basd82** [joomla/joomla-cms#16429]
### Steps to reproduce the issue
When i am loged in on the fronend and i edit or create an articel . i get an Captcha - ReCaptcha.
witch i must complete before i can place an artikel 

### Expected result

no Captcha - ReCaptcha

### Actual result
an Captcha - ReCaptcha

### System information (as much as possible)
Instellingen	Waarde
 
PHP gebouwd op	Linux ****-nl-lb1 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64
Database versie	5.7.18-0ubuntu0.16.04.1-log
Database collatie	latin1_swedish_ci
Collatie van de databaseverbinding	utf8mb4_general_ci
PHP versie	7.0.19-1+deb.sury.org~xenial+2
Webserver	Apache 2.4.18 (Ubuntu)
WebServer naar PHP interface	cgi-fcgi
Joomla! versie	Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Joomla! Platform versie	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Gebruikersagent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

### Additional comments
Why show a captcha at all when you are logged in ?![screen shot 2017-06-01 at 14 04 58](https://issues.joomla.org/uploads/1/ba6fff9614a0ea43d4e3ea82450fd975.png)

**Comment by brianteeman** [comment]
Go to article options in the administration and find the catchall option. Make sure it is set to no and press save on the toolbar

**Comment by brianteeman** [comment]
For further support please use the forum https://forum.joomla.org
