### ISSUE TITLE
[4.0] Install Extension direct Link

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#16423]
### Steps to reproduce the issue
Is it possible to get a Link to installed Extension in Message (and a Link to its "Options")?:
![bildschirmfoto 2017-06-01 um 12 08 40 kopie](https://cloud.githubusercontent.com/assets/8235763/26675257/8d8c65e2-46c3-11e7-94ab-34265b0f9a3c.jpg)

**Comment by brianteeman** [comment]
That would be up to the individual extension to do - so in this case you should make a request to the patchtester repo
