### ISSUE TITLE
[4.0] Install of extension packages does not work

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-cms#16430]
### Steps to reproduce the issue
When installing DPCalendar from https://joomla.digital-peak.com/download/dpcalendar/dpcalendar-6-0-4/dpcalendar-free_6_0_4-zip?format=raw I get the following error:

_Plugin Install: Field 'namespace' doesn't have a default value_

![image](https://cloud.githubusercontent.com/assets/251072/26685432/6fe44cc2-46ea-11e7-8520-75ae30ac4479.png)

### Expected result
Extension installs.

### Actual result
An error is thrown.

### System information (as much as possible)
Joomla 4 branch https://github.com/joomla/joomla-cms/tree/4.0-dev

**Comment by Bakual** [comment]
Isn't there a PR to remove the namespace column anyway? Or do we still need it?

**Comment by laoneo** [comment]
It is as our release leader decided to go a different way by silently merging #16403.

**Comment by Bakual** [comment]
Wow... merging such incomplete PRs without any discussion is a great way moving forward. 😞

**Comment by laoneo** [comment]
Closing as fixed with the pr.
