### ISSUE TITLE
3.7 migrate issue modal SqueezeBox

### ISSUE THREAD

**Issue by pablopalillo** [joomla/joomla-cms#16436]
### Steps to reproduce the issue
modal worked in 3.4 version of joomla.
In 3.7 version , the modal SqueezeBox works fine in the first try but in the second try appears black screen without content .

### Actual result 

In google chrome show this error.

```
modal.js?650a663…:7 Uncaught TypeError: Cannot read property 'removeEvent' of undefined
    at Object.toggleListeners (modal.js?650a663…:7)
    at Object.close (modal.js?650a663…:7)
    at HTMLAnchorElement.m (mootools-core.js?650a663…:119)

```

### System information (as much as possible)

joomla 3.7
php 7.1

**creation modal code**

```
	function callsqueeze(name, big) {


      	var pxX = 600;
		var pxY = 300;
		if (typeof(big) == "undefined") {
			big = false;
		}
		if (big) {
			var pxX = 800;
		}
		if (typeof(name) == "undefined") {
			name = 'posContent';
		}
		var hiddiv = jQuery('#' + name);

		hiddiv.show();
		SqueezeBox.setContent('clone', hiddiv);
		hiddiv.hide();
		SqueezeBox.resize({x: pxX, y: pxY});

	}
```

### Additional comments

tanks a lot

**Comment by tonypartridge** [comment]
Hello,

Is this in the front or backend of Joomla?!

Did you clear your browser cache?

Did you try on Joomla! 3.6?

**Comment by pablopalillo** [comment]
Hello, 
The problem is with a old library for tables sorttables  [https://github.com/stuartlangridge/sorttable](url) this present a incompatibility with mootools in the joomla version 3.7.

the problem can be solved implementing this pull request in this library. 
[https://github.com/stuartlangridge/sorttable/pull/19](url)

Thank you so much
