### ISSUE TITLE
[4.0] [com_tags] View not found

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#16438]
### Steps to reproduce the issue

Visit `administrator/index.php?option=com_tags`

### Expected result

Working list view

### Actual result

> View not found [name, type, prefix]: joomla\component\tags\administrator\controller\, html, administrator

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/16443 .

**Comment by franz-wohlkoenig** [comment]
Closed as having PR #16443 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16438">issues.joomla.org/tracker/joomla-cms/16438</a>.</sub>
