### ISSUE TITLE
[4.0] Keep the Bootstrap 4 tab scripts

### ISSUE THREAD

**Issue by Supun94** [joomla/joomla-cms#16432]
I'm trying to do migrating part from jQuery to Vanilla Javascript in tabs-state.js file. Since there're are many Bootstrap 4 tabs scripts[1] I want to know we will keep the bootstrap 4 tab scripts or not in Joomla 4 ?

[1] https://github.com/Supun94/gsoc17_js_tests/blob/master/media/system/js/tabs-state.js#L31

**Comment by Supun94** [comment]
@dgt41 @dneukirchen

**Comment by dgt41** [comment]
@Supun94 the tab_state.js will be nice to be vanilla.
The aim for the UI elements for Joomla 4 is to use custom elements (some preliminary work can be found here: https://github.com/dgt41/bs4-custom-elements

So at the moment you can convert all the parts to vanilla but the actual call to modal open will need to stay as jQuery.

**Comment by PhilETaylor** [comment]
Tab state js has been almost completely re-written and merged in staging

The version at https://github.com/Supun94/gsoc17_js_tests/blob/master/media/system/js/tabs-state.js is hugely out of date!!! 

To preserve the hours of input I made into the issues - please ensure you use the right JS file!
