### ISSUE TITLE
Tags Menu Item – Ignors global sort definition

### ISSUE THREAD

**Issue by janstieler** [joomla/joomla-cms#16441]
### Steps to reproduce the issue
Create a submenu with a tag item. Than go to the tab "Tags" and change the sort and the direction to global.
Here in the dropdown should declared the global settings in the brackets. If I change the global settings through the button option in the right top corner under menus, it will not actualise. So I have to set all tag-menuitems from hand to the right setting. 

### Expected result
THe expected result is that if I change the global Tag settings that it will also change the global menuitem settings.

### Actual result
The tag-items will not show the global Tag settings.

**Comment by janstieler** [comment]
The category com_messages are wrong and can not be deleted.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16441">issues.joomla.org/tracker/joomla-cms/16441</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Wrong Category disabled.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16441">issues.joomla.org/tracker/joomla-cms/16441</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Can't confirm Issue.
#### Test Scenario: 
1. create a Menu and Setting like above described
2. closed this Menu
3. open Tag-Options and change global Setting > Save
4. open Tag-Menu > global Settings are shown.
Can you please retest?

**Comment by tonypartridge** [comment]
Cannot confirm. I have create two test articles with two test tags. Created a  'Tagged Items' menu item and set it to be global ordering. Changed global ordering including the ascending and descending and always works as it should.

Please can you provide exact and accurate steps to recreate your problem?

Many thanks

**Comment by brianteeman** [comment]
After several months without reply and with no one able to replicate the issue I am closing this at this time. It can always be reopened if more information is provided.
