### ISSUE TITLE
Custom css class for image in menu url elements

### ISSUE THREAD

**Issue by mattiaverga** [joomla/joomla-cms#16447]
Currently, by creating a url element in a menu a custom css class can be applied to the link.
Adding the ability to apply a custom class to the image associated to the url can open the way to use css sprites for such images.

I've done the necessary changes in github (https://github.com/mattiaverga/joomla-cms/tree/menu_image_class), can I open a pull request for that? On what branch?

Thanks.

**Comment by tonypartridge** [comment]
Hello @mattiaverga,

You should do the work and pull against staging.  By all means open a pull and provide as many details as possible explaining what and how it works and how to test it.

**Comment by brianteeman** [comment]
Closed as we have a PR for testing - see #16456
