### ISSUE TITLE
Redirect after a menu is created

### ISSUE THREAD

**Issue by sam-suresh** [joomla/joomla-cms#16442]
### Steps to reproduce the issue
1. Create a new Menu Type like "Footer Menu"
2. Add new menu in this type and save and close. 

### Expected result
After saved, remain in the same menu type page. 

### Actual result
After saved redirected back to default Main Menu type page.

### System information (as much as possible)
Joomla! 3.7.2
PHP 7.0

**Comment by Quy** [comment]
Duplicate #16374. Will be fixed in v3.7.3.

**Comment by franz-wohlkoenig** [comment]
closed as Duplicate Report<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16442">issues.joomla.org/tracker/joomla-cms/16442</a>.</sub>
