### ISSUE TITLE
Tags breaks weblinks' popup window for external links

### ISSUE THREAD

**Issue by pintobuck** [joomla/joomla-cms#16450]
### Steps to reproduce the issue
Back end: Create a weblink. Set target = popup. Give it a tag. 
Front end: Test weblink - navigate to weblink via webllink menu. Click on weblink. External URL opens in a popup window.
Test tags -  Navigate to the weblink via tags (click on a tag or use the tags menu). Click on the weblink, and it opens the external page in the parent window (instead of a popup window), which effectively takes the user off of my site.

### Expected result
Expect to use tags to display the weblink (which it does), and a click on the weblink should open the external URL in a popup window (which it doesn't.)

### Actual result
Use tag to display weblink. Click on weblink, and the external URL opens in the parent window, instead of the popup window.

### System information (as much as possible)
Site hosted on a large hosting service.
PHP Built On  Linux node2 2.100.4-1-amd64-grsec #1 SMP Tue Dec 28 21:57:50 CET 2010 x86_64  
Database Version  5.5.35-MariaDB-1~squeeze  
Database Collation  latin1_swedish_ci  
Database Connection Collation  utf8mb4_general_ci  
PHP Version  7.0.98-servage1  
Web Server  Apache  
WebServer to PHP Interface  apache2handler  
Joomla! Version  Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT  
Joomla! Platform Version  Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT  
User Agent  Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; LCJB; rv:11.0) like Gecko  

### Additional comments
I would like to use tags to build a simple weblinks directory.  Tags enhances weblinks by allowing the same weblink to appear in multiple categories, without duplicating the weblink.   For example:
Category
Subcategory 1
Weblink 1A
Weblink 1B
Subcategory 2
Weblink 2A
Weblink 2B.

With Weblinks menu items I can display the weblinks in a single subcategory:
Subcategory 1
Weblink 1A
Wblink 1B

However, I would also like to be able to display all the weblinks in the parent category:
Category 
Weblink 1A
Weblink 1B
Weblink 2A
Weblink 2B.

I can do this with tags, but then the weblinks fail to use their popup window.

**Comment by zero-24** [comment]
Which exact version of weblinks do you use?

**Comment by pintobuck** [comment]
Web Links Component  3.6.0  2017-03-08  Joomla! Project  	 
Web Links Site  Module  3.6.0  2017-03-08   Joomla! Project  
Web Links Extension Package  3.6.0  2017-03-08   Joomla! Project

**Comment by pintobuck** [comment]
Tags  Component  3.1.0  December 2013  Joomla! Project

**Comment by pintobuck** [comment]
This is from one of my posts on Joomla.org forum, which may illustrate how Tags and Web Links interact on Joomla.

I found tag show/hide controls as follows:

WEB LINKS COMPONENT
Components / Weblinks / New Weblink page / Tags (on the lower right) <- here you can add or delete a tag but there is no show/hide control.

WEB LINKS MENU
Weblinks Menu item has a show/hide control tags.
Menu / Edit Item / Details / Menu Type = "Tagged Items" OR "compact list of tagged items"
Menu / Edit Item / Tag Options / Show Tag Name = Show


TAGS COMPONENT
Component Tags has no option to show or hide individual tags.
Show/hide control is only in Global Configuration / Tags.
Global Configuration / Tags / Tagged Item / Show Tagged Name = Show
Global Configuration / Tags / Tagged Item / Show Tagged Image = Show

TAGS MENU
Menu item / Details / Menu item type = "Compact List of Tagged Items" OR "Tagged Items"
Menu item / Tag Options / Show Tag Name = Show

Now here is the confusing part for me. With all the controls set to show tags, If I navigate to a web link by clicking on a tag or by using a Tags menu item, then the weblink will not display its tag. But, if I navigate to the same weblink using a Weblinks menu item, then the weblink will show its tag.

Examples:
You can see this on a test site at Thriftyfun.net. Use the Weblinks menu at the top, and click on a drop down menu item that begins with the word Weblinks. Then you can navigate to a weblink that shows its tag. For example:
http://thriftyfun.net/weblinks-list-all-subcategories/free-background-search/archived-historical-records/alabama-archived-historical-records

Again in the Weblinks menu, towards the bottom of the same dropdown, you will see menu items that begin with the word Tags. Those menu items can take you to the same tagged weblink, but the tags do not show. Or if you click on a tag, the resulting list of Weblinks will not show their tags. For example: http://thriftyfun.net/tages-tagged-items-list-of-items-with-specific-tags-adoption/Alabama

And back to the original question, navigate to a weblink via a weblink menu item, and the weblink will open a popup window. But navigate to the same weblink via a tag or a TAGS menu item, and the  weblink will open in the parent window.

**Comment by pintobuck** [comment]
I found the All_Weblinks plugin, which can display all the categories of weblinks that I list by ID number.  That seems to provide almost the same ability to sort and display weblinks as if I were using tags.  So, I have found a solution that will works for me. I'll leave it up to you to decide whether to close the weblinks and tags issue or not. Thank you.

**Comment by franz-wohlkoenig** [comment]
i will close this Issue and open one in the Weblink Repository with a Link here. So Maintainers can decide about it. Thanks for your contribute, @pintobuck
