### ISSUE TITLE
[4.0] Class 'JToolbarHelper' not found

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#16455]
### Steps to reproduce the issue
Update nightly Build Update or Full Package got after Login in Backend: `Class 'JToolbarHelper' not found`
![screen shot 2017-06-03 at 03 59 47](https://issues.joomla.org/uploads/1/def034184e19249925f89c75c5fec700.jpg)
### System information
4 (latest nightly build)
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by franz-wohlkoenig** [comment]
Same Error using joomla-cms-4.0-dev.zip

**Comment by mbabker** [comment]
Fixed in https://github.com/joomla/joomla-cms/commit/175e17a06c24b4cac81103e0e241a453f9b590bc

**Comment by caapr2018** [comment]
Same error on joomla 3.4  Backend: Class 'JToolbarHelper' not found
![capture1](https://user-images.githubusercontent.com/44617372/47737607-aa22db80-dc47-11e8-93a4-86a686d8113c.PNG)
