### ISSUE TITLE
[com_fields] default ACL field / fieldgroups not correct?

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#16457]
### Steps to reproduce the issue
in back-end:
1. Create user fieldgroup 'testgroup' (only title > save and close)

Validate default Field Group in 'testgroup' permissions for Author:
- Create: Allowed (inherited)
- Delete: Not Allowed (inherited)
- Edit: Not Allowed (inherited)
- Edit State: Not Allowed (inherited)
- Edit Own: Allowed (inherited)
- Edit Custom Field Value: Not Allowed (inherited)

2. Create user field type (eg) editor) 'testfield' in field group 'testgroup' (only title / type and field group > save and close)

On front-end:
1. login with user who has author rights (only registered and author)
2. goto the user profile and edit the user profile.

The testfield is 'read-only' and cannot be changed.

### Expected result

Because the user is member of the Author group the user should be able to create and edit assigned field values.

### Actual result
Currently the Field is read-only for everybody (no matter what ACL group you are assigned to) accept for superusers.
For every group / (when not assigned a group) field the permission needs to be changed:

- Edit Custom Field Value: **Allowed**

### System information (as much as possible)
OS Linux
PHP 7.0.19-1+deb.sury.org~zesty+2
MySQLi 5.7.18-0ubuntu0.17.04.1

### Additional comments
Not sure if having the fields default to read-only is by design (for me personal it is not logical)

The documentation: https://docs.joomla.org/J3.x:Adding_custom_fields/Parameters_for_all_Custom_Fields
states under 'In the register Options you can use the options: '
_Disabled - Should the field be disabled in the edit form.
Read only - Should the field be read-only in the edit form._ 

But these buttons are not (anymore?) in the Options tab of the field?

**Comment by franz-wohlkoenig** [comment]
changed Title for @laoneo

**Comment by Bakual** [comment]
The doc is probably outdated then. It's a wiki.

As for the default ACL values, you can set them globally in your Joomla configuration and then it will be inherited down to the fields. So you only have to set that initially in one place. By default it's indeed disabled.
We could change those default values for new installs. We can't change it during an update.
