### ISSUE TITLE
[4.0] Review Update Process

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#16458]
This is more of a general reminder task than a bug report.  Right now some parts of the regular core update process are not in place for the 4.0 branch (by explicit decision), prior to tagging beta this task must be completed.

**Comment by zero-24** [comment]
>  Right now some parts of the regular core update process are not in place for the 4.0 branch (by explicit decision)

What exactly? Do you mean the language thing or that there is no non-nightly core updateserver?

**Comment by zero-24** [comment]
Wasn't the plan to rewirte the core updater (and update.joomla.org) anyway?

**Comment by mbabker** [comment]
It's a general thing.  Like the deleted files array not having anything in it so far because we're just going to do it all in one go.

The language infrastructure is unrelated to ensuring that core updates work.  This task is a general reminder and focused specifically on the update process just to make sure we don't forget it and if we need a place to log notes/reminders related to it we have a spot.

> Wasn't the plan to rewirte the core updater (and update.joomla.org) anyway?

Not that I am aware of, there are no open items related to it as far as I'm aware.

**Comment by zero-24** [comment]
> Not that I am aware of, there are no open items related to it as far as I'm aware.

Ah ok. Thanks. /me removes another item from the todo list 😄

**Comment by mbabker** [comment]
That's not to say it absolutely will not happen at all before 4.0, just to be clear.  Just as of this moment, there is no active work on making any changes.

**Comment by wilsonge** [comment]
I'm going to close this one. We have the base process in place and have tagged beta. There's no specific issues in place for the remaining tasks before we move to stable
