### ISSUE TITLE
[4.0] No active Tab in "Extensions: Install"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#16466]
### Steps to reproduce the issue
open `?option=com_installer`> no Tab is active:
![bildschirmfoto 2017-06-03 um 12 31 36](https://cloud.githubusercontent.com/assets/8235763/26752824/fed93b9e-4858-11e7-9350-8f16edb60d46.jpg)
### System information
4.0-dev
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/16467

**Comment by brianteeman** [comment]
Closed as we have a pr
