### ISSUE TITLE
[4.0] Tab states not working

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#16468]
### Steps to reproduce the issue

1. Go to Extensions >> Install
2. Open up the browser console

### Expected result

Tab states work as expected

### Actual result

![screeny](https://cloud.githubusercontent.com/assets/2019801/26753043/a55c1c38-4855-11e7-9dcd-44e7be72c7f9.png)

**Comment by Bakual** [comment]
@PhilETaylor You want to have a look?

**Comment by PhilETaylor** [comment]
The pollyfill is not loaded probably

**Comment by C-Lodder** [comment]
Fixed with: https://github.com/joomla/joomla-cms/pull/16467
