### ISSUE TITLE
[4.0] `Cannot declare class JToolBar`

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#16462]
### Steps to reproduce the issue
Install latest staging, got Warning: ` Warning: Cannot declare class JToolBar, because the name is already in use in /Applications/MAMP/htdocs/4/libraries/loader.php on line 788`
![bildschirmfoto 2017-06-03 um 10 22 21](https://cloud.githubusercontent.com/assets/8235763/26752009/90228208-4846-11e7-87c4-a227625d61d7.jpg)
### System information
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
@laoneo didnt this get fixed a couple of weeks ago?

**Comment by laoneo** [comment]
Yes it got, @franz-wohlkoenig is that a fresh installation or did you do some  changes before the error appeared?

**Comment by esedic** [comment]
I've cloned and installed 4.0-dev branch and error is still there.

**Comment by franz-wohlkoenig** [comment]
@laoneo it was a fresh install of 4.0-dev.zip downloaded from github.

**Comment by C-Lodder** [comment]
I think @wilsonge is still in the process of merging staging into 4.0-dev, with only half of it done so far.

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/16463
