### ISSUE TITLE
[4.0] a11y drag and drop

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#16478]
Placeholder

https://www.sitepoint.com/accessible-drag-drop/
@c-lodder

**Comment by mukulevil83** [comment]
What is the point of view?  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16478">issues.joomla.org/tracker/joomla-cms/16478</a>.</sub>

**Comment by C-Lodder** [comment]
@mukulevil83 basically we're looking into re-writing the drag-n-drop functionality so it can be done using only a keyboard, for a11y purposes

**Comment by mukulevil83** [comment]
@C-Lodder thanks for telling.   [](https://www.todaypk.lol/tag/123moviesto "")  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16478">issues.joomla.org/tracker/joomla-cms/16478</a>.</sub>

**Comment by C-Lodder** [comment]
Please reopen this for reference

**Comment by brianteeman** [comment]
Closed as @dgt41 is now working on this and has the link
