### ISSUE TITLE
[mod_newsflash] Tooltip `Display Article Images` is unclear

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#16495]
### Steps to reproduce the issue
... cause User can understand "Display Intro-Image" but "param refer to images INSIDE the content - not the image fields" ([comment](https://github.com/joomla/joomla-cms/issues/5229#issuecomment-64832430)).
![bildschirmfoto 2017-06-04 um 08 07 32](https://cloud.githubusercontent.com/assets/8235763/26759435/1e36478e-48fe-11e7-8070-bce4e1fe1d30.jpg)

Two Suggestions:

1. Precise Tooltip like `Display Article Images from inside Content`
2. Prefer: allow display of Intro-Image.
### System information
3.7.2
macOS Sierra, 10.12.5
Firefox 53 (64-bit)

**Comment by brianteeman** [comment]
I have discussed this with several native english speakers and you are correct that the tooltip could be more informative for beginners BUT the suggestion actually makes it more complex and not less. Unfortunately we have not been able to come to a better suggestion than the current string. Perhaps you can ask the en-GB team to consider this.

**Comment by franz-wohlkoenig** [comment]
@brianteeman i will ask en-GB Team … if there's no Possibility to display Intro-Image – what's you're Opinion?

**Comment by brianteeman** [comment]
@franz-wohlkoenig personally i dont see the need for a change

**Comment by franz-wohlkoenig** [comment]
Thanks for your Opinion, Brian, i hope for an interested Dev.

**Comment by carlitorweb** [comment]
PR for this option #20169

**Comment by ghost** [comment]
closed as having Pull Request #20169
