### ISSUE TITLE
[4.0] Refining the layout of the top bar (layout)

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#16498]
### Current layout
![image](https://cloud.githubusercontent.com/assets/828371/26760187/82e9ff18-4912-11e7-890f-5cc0b564a515.png)

### Layout Proposal

In the Layout proposal, I used fewer colours and cleaner forms.
Subjective I think the outline icons are more accessible. The form of the icons can be easier recognized outline. 
Additionally, the elements are aligned with the buttons inside the component area.
The Joomla! Logo is also aligned in relation to the top bar.

![image](https://cloud.githubusercontent.com/assets/828371/26760156/0090621e-4912-11e7-8f7c-a0a97f4d9c07.png)

(Alignment)
![image](https://cloud.githubusercontent.com/assets/828371/26760181/615342ec-4912-11e7-8e25-21a4753b6d31.png)

**Comment by C-Lodder** [comment]
PR for the buttons: https://github.com/joomla/joomla-cms/pull/16504
