### ISSUE TITLE
[4.0] "Make the logo smaller" (layout)

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#16500]
### Steps to reproduce the issue
In marketing and layout, we tend to "Make the logo bigger".
But using the brand in smaller sizes and with more space, we appear more confident and elegant.

The current logo size creates an imbalance and takes unnecessary space from the sidebar.
![image](https://cloud.githubusercontent.com/assets/828371/26760378/b5af877a-4916-11e7-8d72-7173f104557e.png)

### Layout Proposal 1 with left-aligned logo

![image](https://cloud.githubusercontent.com/assets/828371/26760398/20456776-4917-11e7-9003-d51ee6b6d10e.png)

### Layout Proposal 2 with center-aligned logo to the navigation
![image](https://cloud.githubusercontent.com/assets/828371/26760415/5dd7770a-4917-11e7-9cba-bd5a62ace0bb.png)

**Comment by C-Lodder** [comment]
I like the fact that with the smaller logo, it would mean that when collapsing the sidebar, only the actual sidebar would need to be collapsed, thus the trigger would stay in the same place. However with the logo being that small, it looks a little too cramped.

**Comment by coolcat-creations** [comment]
We can leave the Joomla! Brandmark and place the site name next to it. 
Following example shows how a long Sitename is displayed:

![image](https://cloud.githubusercontent.com/assets/828371/26761588/dccdebe6-4932-11e7-8fac-5920e4ec2a58.png)

The Joomla! Logo and the Version move to the bottom.

![image](https://cloud.githubusercontent.com/assets/828371/26761597/f6f45fbe-4932-11e7-8db1-4ba60d4cffbf.png)

**Comment by C-Lodder** [comment]
All good with me. Can we close this issue as it's now pretty much the same as https://github.com/joomla/joomla-cms/issues/16505

**Comment by coolcat-creations** [comment]
I just add the same screenshot, but here it is about the Logo at the top... The other issue is about the status bar,...

**Comment by ciar4n** [comment]
Something like?...

![smaller-logo1](https://user-images.githubusercontent.com/2803503/27536858-e73775f6-5a68-11e7-8b4d-5e2c9555422d.png)

![smaller-logo2](https://user-images.githubusercontent.com/2803503/27536867-f3f894d2-5a68-11e7-8eb1-e9052e969d8f.png)

**Comment by C-Lodder** [comment]
@ciar4n - I'd say the sidebar toggle button is too small. Dont worry about this one, I'll need to rewrite the stats module at the sprint and this will all be part of it.

**Comment by ciar4n** [comment]
Cool. I'll park it til then.

**Comment by bassmanpaul** [comment]
Whilst on the subject of the sidebar we did a bit of user testing in our office, and quite a few people mistook the current sidebar toggle icon for a back button as the top right appearance is very similar to the browser's back button (especially when editing an item):

![sidebar-4-current](https://user-images.githubusercontent.com/6650331/27783920-0a856fc4-5fd0-11e7-8dc4-cd255029ddb5.png)

I've just spotted Freedcamp's UI redesign and they have an interesting alternative which is to place the toggle button at the bottom (it also has a custom icon which seems more intuitive):

![sidebar-4-new](https://user-images.githubusercontent.com/6650331/27784007-5fb0a126-5fd0-11e7-9ca4-2eea454c7d44.png)

They also put the logo at the bottom as well, which I don't think is a bad move either because it preserves the brand on screen whilst keeping it separate from the important actions/menus that the users will need to access, giving the menus priority.

Just some feedback & thoughts from user testing :)

**Comment by brianteeman** [comment]
@bassmanpaul I agree and I brought that up before

**Comment by ciar4n** [comment]
Moving the toggle to the bottom gets my vote to. It's size and position is a little 'in your face' for my liking.

**Comment by dgt41** [comment]
The arrow icons might be perceived as draggable, which is not the case here, so the hamburger icon is more appropriate IMHO

**Comment by C-Lodder** [comment]
Hamburger would definitely be more appropriate

**Comment by ciar4n** [comment]
Originally it was a hamburger (https://github.com/joomla/joomla-cms/pull/15430#issuecomment-297024469). It was argued that considering a hamburger icon signifies a menu, this icon was to far from the menu so a chevron was preferred. Personally I would sooner the hamburger regardless of its position.

**Comment by bassmanpaul** [comment]
In that case here are a few visualisations/variations:

## Toggle arrow
![j4-sidebar-01](https://user-images.githubusercontent.com/6650331/27817195-c732ad78-6087-11e7-9c4f-f11ad382cba5.gif)

## Hamburger menu
![j4-sidebar-02](https://user-images.githubusercontent.com/6650331/27817196-c75d0366-6087-11e7-97f9-6fe8d8d28f1b.gif)

## Hamburger with Open/close label
![j4-sidebar-03](https://user-images.githubusercontent.com/6650331/27817197-c75f4fc2-6087-11e7-9fc6-2baa37314e2a.gif)

The last one's text may be a bit small or cause multi-lingual problems.

And for reference here is how Freedcamp's behaves:

![freed-sidebar-01](https://user-images.githubusercontent.com/6650331/27817370-a06ac4fe-6088-11e7-9870-bed36a70a1ab.gif)

**Comment by coolcat-creations** [comment]
I close this, because there is a complete new layout proposal
