### ISSUE TITLE
[4.0] Move the Statusbar to the sidebar

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#16505]
### Current Situation

The Backend Content area is currently very boxed. Topbar, Sidebar, Bottom bar.

One Solution could be to move all status Information to the topbar or to the sidebar or to split the informations.

### Layout proposal

![image](https://cloud.githubusercontent.com/assets/828371/26760521/bfef6c7e-491a-11e7-9188-8c99dc98220c.png)

**Comment by C-Lodder** [comment]
Bare in mind there's is also a "Multilingual Status" option and extensions devs can add their own items here too. Regular Labs cache cleaner being an example.

**Comment by andrepereiradasilva** [comment]
is other discussion for sure, but just leaving it here
is there really the need for "Multilingual Status" to be in all backend pages? why not move it to com_languages menu (it's a com_languages view after all).

**Comment by C-Lodder** [comment]
I'd agree with that.

**Comment by coolcat-creations** [comment]
So:
1) Version and Users move to the Sidebar
2) Sidebar can be used anyway to add custom menuitems (also from other extensions)
3) Extension Developers have the possibility to add their Quickicon to the topbar
4) Extension Developers have the possibility to add things into the sidebar too 
5) Topbar has to be fixed at scrolling
6) Bottombar will be dissolved / removed completely

![image](https://cloud.githubusercontent.com/assets/828371/26761624/72c4c20a-4933-11e7-9308-93a5498f5e00.png)

**Comment by brianteeman** [comment]
(multilingual status can be moved to the dashbard where it belongs)

**Comment by C-Lodder** [comment]
@brianteeman as a quick icon perhaps?

**Comment by brianteeman** [comment]
@C-Lodder like this
<img width="893" alt="screenshotr15-53-51" src="https://cloud.githubusercontent.com/assets/1296369/26762185/0e95521c-493e-11e7-9632-50dd50938e09.png">

**Comment by ciar4n** [comment]
How would this look with one of the menu items opened? Currently the menu opens at full height of the sidebar.

**Comment by C-Lodder** [comment]
Sorry, forgot to mention, this has been done now (https://github.com/joomla/joomla-cms/pull/17056). Can be closed

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16505">issues.joomla.org/tracker/joomla-cms/16505</a>.</sub>
