### ISSUE TITLE
[4.0] Increase contrast for menu hover

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#16503]
### Steps to reproduce the issue
The Menu hover has currently not much contrast so that people with poor eyesight or with a too bright environment don't see any hover indication.

### Current Mainmenu

![image](https://cloud.githubusercontent.com/assets/828371/26760462/ba13a236-4918-11e7-93dc-ef361509a90c.png)

![image](https://cloud.githubusercontent.com/assets/828371/26760461/a667a2a0-4918-11e7-80d7-851e6342ac7f.png)

### Possible Solution 
![image](https://cloud.githubusercontent.com/assets/828371/26760468/f0c1c754-4918-11e7-9825-1587fbf6161d.png)

![image](https://cloud.githubusercontent.com/assets/828371/26760465/d66dd334-4918-11e7-8487-5b9117f947e1.png)

**Comment by brianteeman** [comment]
Thanks for submitting this - saved me doing the same thing

**Comment by ciar4n** [comment]
PR created..  #17077

**Comment by ghost** [comment]
closed as having PR #17077<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16503">issues.joomla.org/tracker/joomla-cms/16503</a>.</sub>
