### ISSUE TITLE
B/C Break: Admin Langage specific css not loaded since 3.7.0

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#16506]
### Steps to reproduce the issue
Install Persian language.
It contains, correctly, in administrator/language/fa-IR/ 
the file `fa-IR.css`.

This file is designed to override some default template css to adapt to a specific language.
In Isis and Hathor, it should be loaded by
```
// Load specific language related CSS
JHtml::_('stylesheet', 'language/' . $lang->getTag() . '/' . $lang->getTag() . '.css', array('version' => 'auto', 'relative' => true));
```

### Expected result

css loads.

### Actual result

It does not.

**Comment by infograf768** [comment]
Evidently, if I use the 2.5 code
```
$file = 'language/'. $lang->getTag() . '/' . $lang->getTag() . '.css';
if (JFile::exists($file)) {
	JFactory::getDocument()->addStyleSheet($file);
}
```
it loads OK

**Comment by C-Lodder** [comment]
Try removing `'relative' => true` from the array

**Comment by andrepereiradasilva** [comment]
```php
JHtml::_('stylesheet', ltrim(JUri::base(true), '/') . '/language/' . $lang->getTag() . '/' . $lang->getTag() . '.css', array('version' => 'auto'));
```
should work

**Comment by andrepereiradasilva** [comment]
@infograf768 @C-Lodder please test https://github.com/joomla/joomla-cms/pull/16513

**Comment by mbabker** [comment]
See PR.
