### ISSUE TITLE
weblinks broken after switch from php 5.6 to 7.1

### ISSUE THREAD

**Issue by Maderthaner** [joomla/joomla-cms#16510]
### Steps to reproduce the issue

I just switched Joomla's server PHP version from PHP 5.6.x to 7.1.5.

### Expected result

Website including links works as before after clearing cache.

### Actual result

When clicking on weblinks, it is stuck at the step, e.g., HTTX//URL/xxx?task=weblink.go&id=35 and doesn't actually go to the link destination (just blank page).
Also in den Admin Backend, I cannot edit links anymore (just goes to blank page as well).

### System information (as much as possible)

Joomla Sys Info:

PHP Built On 	Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
Database Version 	5.5.55-0+deb7u1-log
Database Collation 	latin1_german2_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.1.5
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:53.0) Gecko/20100101 Firefox/53.0 

Joomla PHP Info:
Relevant PHP Settings
Setting 	Value
 
Safe Mode 	Off
Open basedir 	None
Display Errors 	On
Short Open Tags 	On
File Uploads 	On
Magic Quotes 	Off
Register Globals 	Off
Output Buffering 	Off
Session Save Path 	/tmp
Session Auto Start 	0
XML Enabled 	Yes
Zlib Enabled 	Yes
Native ZIP Enabled 	Yes
Disabled Functions 	None
Multibyte String (mbstring) Enabled 	Yes
Iconv Available 	Yes
Mcrypt Enabled 	Yes
Maximum Input Variables 	5000 

### Additional comments

I'm using 1und1.de hosting. Website is working fine under PHP 5.6

**Comment by andrepereiradasilva** [comment]
hi, please report core supported weblinks extension issues to the weblinks extension repository (https://github.com/joomla-extensions/weblinks/issues)

@franz-wohlkoenig close?

**Comment by franz-wohlkoenig** [comment]
closed as this Issue belongs to weblinks extension repository.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16510">issues.joomla.org/tracker/joomla-cms/16510</a>.</sub>
