### ISSUE TITLE
Core.js incorrect path

### ISSUE THREAD

**Issue by grantg182** [joomla/joomla-cms#16527]
### Steps to reproduce the issue
Install Joomla 3.7.2

### Expected result
No console errors

### Actual result
GET http://localhost/media/system/core.js 

### System information (as much as possible)
3.7.2

### Additional comments

Path is incorrectly defined in libraries/cms/html/behavior.php on line 90:-

JHtml::_('script', 'system/core.js', array('version' => 'auto', 'relative' => true));

Should be system/js/core.js

**Comment by dgt41** [comment]
Relative == true means no need to use the `/js/`

**Comment by andrepereiradasilva** [comment]
```php
JHtml::_('script', 'system/core.js', array('version' => 'auto', 'relative' => true));
```
Result: 
```html
<script src="/media/system/js/core.js?b7d620c1ef135c749d6325a89e00d321"></script>
```

Also JHtml detect if file exists in the filesystem, if doesn't exist it will not create a HTML tag.

**Comment by tonypartridge** [comment]
@grantg182 can you please check the filter exist in your system:
/media/system/js/core.js

Working fine in my testbed.

**Comment by C-Lodder** [comment]
@grantg182 - have you by any chance made any core changes to Joomla?

**Comment by brianteeman** [comment]
It has been several months since the last response and from the comments above it has not been replicated - this can always be re-opened if required
