### ISSUE TITLE
Layout of Tel field type have a small error

### ISSUE THREAD

**Issue by fdesanto** [joomla/joomla-cms#16523]
### Steps to reproduce the issue
Each form that contain tel phone field

### Expected result
Output should be something like:
`<input type="tel" id="jform_name_of_field" name="jform[name_of_field]"  class="validate-phone required" value="" size="30" />`

### Actual result
`<input type="tel" id="jform_name_of_field " name="jform[name_of_field]"  class="validate-phone required" value="" size="30" />`
There is a space in ID attribute!!
Javascript function like jQuery('#jform_name_of_field') do not works

### System information (as much as possible)
Joomla 3.7.2

### Additional comments
to fix this you need to remove space char in file /layouts/joomla/form/field/tel.php at line 71

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/16524

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16524<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16523">issues.joomla.org/tracker/joomla-cms/16523</a>.</sub>
