### ISSUE TITLE
[4.0-dev] Drone is failing on a JS Error

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#16536]
### Steps to reproduce the issue

http://213.160.72.75/joomla/joomla-cms/5494

### Expected result

Drone is happy

### Actual result

Drone is not happy.

`05 06 2017 16:01:30.495:ERROR [Firefox 50.0.0 (Ubuntu 0.0.0) | Validate, validate method on #validate-numeric-nan | should add class invalid to element]:`

`05 06 2017 16:01:30.556:ERROR [Firefox 50.0.0 (Ubuntu 0.0.0) | Validate, isValid method on button click | should add class invalid to element #isvalid-numeric-nan]:`

### Additional comments

We also have the same issues on the GSOC Repos.

**Comment by wilsonge** [comment]
This is one for the GSOC Javascript testing team or @dgt41 . It's been failing on and off for a while.

**Comment by dgt41** [comment]
On my list

**Comment by zero-24** [comment]
looks like drone is running now: http://213.160.72.75/joomla/joomla-cms/5697 ? Did we fixed the error anywhere else?

**Comment by dgt41** [comment]
That image exists but was used in a moo tools modal :( I guess that test is outdated and also the highlighter.js is about to be replaced by mark.js https://github.com/joomla/joomla-cms/pull/16357

**Comment by yvesh** [comment]
It's an error in validate tests.. Sure this change was intended @dgt41?

@dgt41 Stop breaking things that's another persons job :p

**Comment by zero-24** [comment]
Last tests now run without error: http://213.160.72.75/joomla/joomla-cms/6889 closing
