### ISSUE TITLE
[4.0] Is there a special reason for the new readme?

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#16533]
### Steps to reproduce the issue

see: https://raw.githubusercontent.com/joomla/joomla-cms/4.0-dev/README.md

### Expected result

something similiar to 
![image](https://cloud.githubusercontent.com/assets/2596554/26790564/7f26f112-4a14-11e7-816d-d7972036c65a.png)

### Actual result

![image](https://cloud.githubusercontent.com/assets/2596554/26790551/741ef616-4a14-11e7-9254-86c9f5685e39.png)

**Comment by andrepereiradasilva** [comment]
yes @wilsonge https://github.com/joomla/joomla-cms/commit/593905b32adbcbf44ab57c1f3e003d1933ca1ea0  :smiling_imp:

**Comment by brianteeman** [comment]
merge in haste repent at leisure

**Comment by zero-24** [comment]
#16541

**Comment by laoneo** [comment]
Came from the media manager merge. I'm taking this onto my cap. Sorry for the trouble.
