### ISSUE TITLE
Joomla Resources Directory listing.

### ISSUE THREAD

**Issue by dcassone** [joomla/joomla-cms#16539]
### Steps to reproduce the issue
Submit a Resources Directory listing request
It was suggested that I post this here, even though it is not an actual Joomla issue.

### Expected result
Requested submitted in February 2017
Expected some sort of communications

### Actual result
I have heard nothing at all. I even submitted a couple of tickets asking the status. They have not even been assigned.

**Comment by zero-24** [comment]
The better place would be: https://github.com/joomla/joomla-websites and not the CMS issue tracker ;)

> It was suggested that I post this here, even though it is not an actual Joomla issue.

Where? Please point them to https://github.com/joomla/joomla-websites.

Thanks.
