### ISSUE TITLE
get new

### ISSUE THREAD

**Issue by SteveMuganda** [joomla/joomla-cms#16530]
### Steps to reproduce the issue
Why should we get there?

**Comment by tonypartridge** [comment]
Can you please elaborate on this? It doesn't make any sense.

**Comment by franz-wohlkoenig** [comment]
@tonypartridge in Ticker is "Build: 2", guess its a Question about Update.

**Comment by zero-24** [comment]
@SteveMuganda If your question is how to come from 2.5 to 3.x please take a look into:
https://docs.joomla.org/Special:MyLanguage/Joomla_2.5_to_3.x_Step_by_Step_Migration

If there are more questions please use the forum at https://forum.joomla.org thanks.
