### ISSUE TITLE
Multicategories for article

### ISSUE THREAD

**Issue by 1inkin** [joomla/joomla-cms#16553]

**Comment by zero-24** [comment]
@1inkin the core does not offer `Multicaregories` there fore we shipping the tags feature. Please ask any support question at https://forum.joomla.org thanks.

**Comment by 1inkin** [comment]
Can this be realized in the future in 4.0, maybe? it is important. I have many Articles that are duplicated in several categories. And I can not use tags in this situation.

**Comment by Bakual** [comment]
Most likely not.

**Comment by 1inkin** [comment]
This is bad news for me. Strange, I think this would be a useful function. I tried to use extensions, but they do not work correctly.

**Comment by Bakual** [comment]
It would need a fundamental change in the CMS, because currently categories are used for generating the URLs and calculating permissions to view and edit things.

Use Tags instead, because those are meant for that.
