### ISSUE TITLE
[4.0] Responsive admin options screen

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#16558]
See movie
![responsive](https://user-images.githubusercontent.com/1296369/26877877-4816928e-4b83-11e7-9455-7af91d6478d5.gif)

**Comment by dgt41** [comment]
@C-Lodder @ciar4n this one is for you

**Comment by ciar4n** [comment]
`flex-wrap: wrap;` on the `ul` should sort this. Will create a PR later.

**Comment by ciar4n** [comment]
PR created.. #16578

**Comment by brianteeman** [comment]
Closed as we have a PR
