### ISSUE TITLE
TinyMCE doesn't allow empty rel attribute for links and defaults to "alternate"

### ISSUE THREAD

**Issue by bjxrn** [joomla/joomla-cms#16554]
### Steps to reproduce the issue
In Joomla administration, open an article while having TinyMCE set as editor in extended mode.
Click the insert/edit link button in the MCE toolbar.

### Expected result
In most sites, when users insert a link it is rarely the case that a rel attribute is needed, and in only a fraction of those cases will the user be linking to an alternate version of the current piece of content.
There should be a "None" option for the rel field and it should be the default.

### Actual result
The Rel attribute dropdown will default to "alternate" when adding a link.
It is impossible to not set a rel attribute

### System information (as much as possible)
Joomla 3.x, TinyMCE editor, extended

### Additional comments
This can be fixed by adding `array('title' => 'None', 'value' => ''),` as the first element of the `$scriptOptions['rel_list']` array in /plugins/editors/tinymce/tinymce.php

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.
### System information
3.7.3-dev (latest nightly build)
Multilanguage Site
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
i think this is a mistake in tinymce because a link element must have a rel attribute but an a element does not have to have a link element.

I will look at creating a Pr

**Comment by brianteeman** [comment]
Closed please test #16557
