### ISSUE TITLE
Frontpage TinyMCE drag&drop upload

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#16562]
### Steps to reproduce the issue
- Create a non admin User
- Create a "submit article" menu link
- Give the user the ACL rights to Create media files (com_media => options)
- Try to upload a file via drag&drop in the frontend editor (TinyMCE)

### Expected result
The file is uploaded

### Actual result
You'll get a 403 because of: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_media/media.php#L14 (at least I think that's the reason)
The upload set asset=image, but should rather be com_content (or the check itself is wrong)

### System information (as much as possible)
Joomla! 3.7.2

**Comment by franz-wohlkoenig** [comment]
Can't confirm. 

User + -Group "Manager": drag'n'drop works in Frontend per Upload "Desktop > TinyMCE".
### System information
3.7.3-dev (staging)
Multilanguage Site
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
It has been several months since this issue was created without confirmation of the issue. I am closing it at this time but it can always be reopened
