### ISSUE TITLE
[4.0] com-media language strings

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#16560]
after the merge of the new com-media most of the language strings are missing. this is most obvious in the options screen
<img width="579" alt="screenshotr14-25-43" src="https://user-images.githubusercontent.com/1296369/26878289-eee68d20-4b84-11e7-8c43-a04fad242e07.png">

**Comment by brianteeman** [comment]
or did something go wrong with the merge as i cant get the new media manager to do anything at all?

**Comment by dgt41** [comment]
Here is a PR: https://github.com/joomla/joomla-cms/pull/16561

**Comment by mbabker** [comment]
See PR.
