### ISSUE TITLE
[3.7] "Tags"-Menu in costumized Admin-Menu

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#16564]
### Steps to reproduce the issue
Most Components of default Component-Menu can be costumized by creating a new Menu – not Tags. Would be fine to create a Tags-Menu in same Way than other Components.
### System information
3.7.3-dev (latest nightly build)
Multilanguage Site
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
Sorry I have no idea what you mean

**Comment by franz-wohlkoenig** [comment]
A Tag-Menu is only possible inside the Component-Menu. My Question is to create the Tag-Menu on same Level like iE. Module-Menu.

**Comment by brianteeman** [comment]
If I understand you correctly you are saying

It is not possible to create an admin tag component menu using the new custom admin menu creation

This is because there is no tags.xml file in the tmpl folder

**Comment by franz-wohlkoenig** [comment]
To show what i mean: The Tag-Menu is only possible in Component-Menu. I'm asking if its possible to create it in samel level like J-Update, Module, etc.
![bildschirmfoto 2017-06-07 um 16 33 04](https://user-images.githubusercontent.com/8235763/26884017-0faf3010-4b9f-11e7-8d11-edaee730e61a.jpg)

**Comment by franz-wohlkoenig** [comment]
Thanks for Info, @brianteeman.

**Comment by brianteeman** [comment]
i am looking into this

**Comment by brianteeman** [comment]
it maybe some time before i get to this so if anyone else wants to submit a pr please do

**Comment by brianteeman** [comment]
Closed see #16588
