### ISSUE TITLE
[4.0] Ajax permissions - calculated settings

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#16565]
The ajax permissions refresh is not working in J4

### Joomla 3
![ajaax3](https://user-images.githubusercontent.com/1296369/26883466-2dd30e86-4b95-11e7-8ce9-5ffffd9878bb.gif)

### Joomla 4
![ajax4](https://user-images.githubusercontent.com/1296369/26883461-2af1c8ec-4b95-11e7-9dd6-66da40603f24.gif)

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/16566 should fix it.

**Comment by brianteeman** [comment]
closed as we have a pr
