### ISSUE TITLE
[4.0] ticks on valid fields

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#16567]
@c-lodder looks like you need to do some changes to your work adding ticks on validation. See screenshot to see what happens to tinymce when you save an article
<img width="757" alt="screenshotr16-44-18" src="https://user-images.githubusercontent.com/1296369/26884733-64f1d0ca-4b98-11e7-9911-6323e4ac6bc5.png">

**Comment by franz-wohlkoenig** [comment]
Confirming Behaviour – savin an Article this green Symbols are shown for a short Time.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16567">issues.joomla.org/tracker/joomla-cms/16567</a>.</sub>

**Comment by brianteeman** [comment]
I would probably not do green ticks at all ever because it has other weird results like ticking a field that is empty.

**Comment by Bakual** [comment]
Just to add a few other cases (it's not restricted to the editor field only)
Calendar:
![calendar](https://user-images.githubusercontent.com/1018684/27023550-44962efc-4f53-11e7-9d0a-6d9abd5cf146.PNG)
Custom field in my extension:
![sermon](https://user-images.githubusercontent.com/1018684/27023559-4d3984dc-4f53-11e7-99c0-8b61c5a8502a.PNG)

**Comment by Bakual** [comment]
On the other hand, it doesn't work for category and tag fields.

**Comment by dgt41** [comment]
> On the other hand, it doesn't work for category and tag fields.

That's expected as these fields currently rely on chosen, which will be replaced in j4

**Comment by C-Lodder** [comment]
Why is this being closed?

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/17078

**Comment by brianteeman** [comment]
closed as we have a PR
