### ISSUE TITLE
[3.7] Can't assign "Custom Field" to only 1 contact category

### ISSUE THREAD

**Issue by federone** [joomla/joomla-cms#16574]
hi,

### Steps to reproduce the issue
On Joomla 3.7.2 create 2 contact categories:
- **Services**
- **General**
and create to each category the relative contacts.

then create 1 custom field (Mail), for example "test" (text input) and apply to category "**Services**":
![custom](https://user-images.githubusercontent.com/1756964/26890254-fdf12bb2-4bc1-11e7-9413-f2a42f5b7393.png)

### Expected result
that field must show-up only on "Service" category contacts, because it is assigned to "Service" category.

### Actual result
that field is visible on "**General**" category contact too ... also on "**Uncategorised**" category contacts .. and i guess on all contacts ... but it must show up only on "**_Services_**" category contacts, am i right?
every time when i create a new field and assign to specific contact category - they show up on all contacts, no matter on which "contact category" they are assigned ...

### Additional comments
am i missing something?

thank you so much,
Federico

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding.

**Comment by franz-wohlkoenig** [comment]
Closed. You can always reopen this Report if its a Bug, thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16574">issues.joomla.org/tracker/joomla-cms/16574</a>.</sub>

**Comment by federone** [comment]
i'm sure it is a bug,

assignment for "Mail" custom fields show up on all contacts, no matter in which categories they are assigned.
it is working correctly for "Contact" type custom fields, please check screenshots below:
![1](https://user-images.githubusercontent.com/1756964/26914617-5dd78c08-4c33-11e7-838a-413d2d2c1c1f.png)
![2](https://user-images.githubusercontent.com/1756964/26914618-614d8e6e-4c33-11e7-8d8b-665c6314977a.png)
![3](https://user-images.githubusercontent.com/1756964/26914621-64f6701c-4c33-11e7-8925-50dcf9030dfe.png)

can you please test it,

thank you so much,
Federico

**Comment by franz-wohlkoenig** [comment]
reopened Issue. Thanks for detailed Information. Will look into it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16574">issues.joomla.org/tracker/joomla-cms/16574</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Set issue-Status on "Confirmed". Thanks for Report, @federone 

@laoneo can you have a Look at this Issue please? There was a similar Report but i can't remember if it was about "Mail" or another one.

**Comment by federone** [comment]
any solution for this issue?

thank you so much,
Federico

**Comment by franz-wohlkoenig** [comment]
@federone No Solution as far as i know. It needs a Developer looking in it and write as next Step a Pull Request for testing.

**Comment by laoneo** [comment]
Will do next week.

**Comment by jnk22** [comment]
I am relatively new to Joomla, but ran into this bug myself a few days ago. This feature is pretty important for me, though.
How long does it usually last until something like this is fixed and being shipped within a new release?

Please don't take this comment as me being impatient or anything. I just would like to understand how much time usually passes until a reported bug like this is shipped within any release (dev, unstable, stable and so on) and when users are able to use that release then.

And of course, I am not asking for an ETA for this bugfix! Just wanna know if it could take days, weeks or months maybe, and how i can get a release with this bugfix in it, as soon as it is done :)

Thank you for all your work on this great software!

Thanks in advance,
jnk22<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16574">issues.joomla.org/tracker/joomla-cms/16574</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@jnk22 i didn't know if someone have a Statistic like you asked. But next [Milestone](https://github.com/joomla/joomla-cms/milestones) ist set, so if PR is created and sucessfully tested and merged it can be in this Milestone or Milestone come later. No Guarantee.

**Comment by laoneo** [comment]
Please test pr #16666 if it fixes the issue.

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16666 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16574">issues.joomla.org/tracker/joomla-cms/16574</a>.</sub>

**Comment by federone** [comment]
@franz-wohlkoenig @laoneo thank you very much!

Best Wishes,
Federico
