### ISSUE TITLE
not possible to create categories

### ISSUE THREAD

**Issue by umuehlbo** [joomla/joomla-cms#16581]
### Expected result
Hello.
Its not possible to create new categories.
When I click the button save or save&leave nothing happens.
Same issue for new posts.
thanks for your help
Uwe

**Comment by brianteeman** [comment]
from the information you have provided it is not possible ti help you

there was a reason you were asked questions when you created the issue

**Comment by brianteeman** [comment]
I am closing this due to lack of response - it can be reopened if meaningful information is provided
