### ISSUE TITLE
PHP 7.2 Deprecations affecting Language Package

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#16584]
As per https://wiki.php.net/rfc/deprecations_php_7_2 from PHP 7.2, using the magic variable `$php_errormsg` to track errors in INI files is deprecated to be removed in PHP 8 - we should think about conditional error handling in the language package to use the new intended behaviour documented for PHP 7 (`error_get_last`) and higher falling back to `$php_errormsg` in PHP 5.x

Given PHP 8 is already been talked about (https://www.phpclasses.org/blog/post/469-PHP-8-Performance-to-be-Boosted-with-a-JIT-engine--Lately-in-PHP-podcast-episode-76.html) maybe we need to even think about having this in the 3.x series given that 3.x is going to last till around 2020 (assuming a 3.9/4.0 release at the end of this year)

**Comment by brianteeman** [comment]
Closed as there is a PR #17856
