### ISSUE TITLE
Incorrect ordering of articles in list of tag

### ISSUE THREAD

**Issue by 1inkin** [joomla/joomla-cms#16592]
After adding Tag for articles in batch, in list of tag ordering of articles by modified date is incorrect

**Comment by brianteeman** [comment]
How is it incorrect? What are the modified dates that you have? what are you expecting to see.

Also when submitting the issue you were asked a series of questions that you chose to delete. They were important questions and without the answers no one can help.

I am closing this. Please create a new issue with more details
