### ISSUE TITLE
Jalali calendar broken

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#16590]
When using the Persian calendar and choosing another day than the present day, then hitting return, it is always the present day which is displayed/saved.

@dgt41 

Release blocker

Test made here on publishing date:

![jalali](https://user-images.githubusercontent.com/869724/26963913-79dbd3f2-4cef-11e7-80de-104032b3b5d5.gif)

**Comment by dgt41** [comment]
@infograf768 according to the code: https://github.com/joomla/joomla-cms/blob/staging/media/system/js/fields/calendar.js#L540-L544
`shift` + `enter` is the enter equal (accept value and `enter` is the same as escape. I don't remember why we did it like this

**Comment by infograf768** [comment]
@dgt41 
Enter alone works for en-GB

**Comment by infograf768** [comment]
Tried shift enter and tab => same result

**Comment by infograf768** [comment]
Also, if the Publishing field is empty for example, when i choose today, it does not save here at all. Field is saved empty

**Comment by Bakual** [comment]
"Enter" acting as "Escape" certainly is wrong and unexpected behavior. "Shift-Enter" is basically a useless combinations since there is no hint that we can use that :smile:

**Comment by infograf768** [comment]
The other issue when field is empty (Publishing field)

![jalali2](https://user-images.githubusercontent.com/869724/26964852-a9fce220-4cf3-11e7-9de4-e0841d3c37ef.gif)

**Comment by dgt41** [comment]
> The other issue when field is empty (Publishing field)

Try to close it with close button, does it work then? (then the problem is the blur code, modified recently)

**Comment by infograf768** [comment]
Nope.

**Comment by farhadst** [comment]
Hi
This problem arose in joomla 3.7
After the digit were written in Persian
I also can not manually enter a date
There was no such problem in joomla 3.6, which was the English digit.
Now for choose another day before today, i should first choosing hour and then choose the day.
but after change any digit, date reset to today

**Comment by farhadst** [comment]
I have change digit in media/system/js/fields/calendar-locales/fa-ir.js from persian to latin
![cal](https://user-images.githubusercontent.com/8976056/27033201-9211e09c-4f8d-11e7-8e7b-d290e34756ee.jpg)
but problem not fix, then replace media/system/js/fields/calendar.min.js by same file in joomla 3.7 package, and some problem fix
![cal2](https://user-images.githubusercontent.com/8976056/27033278-de51d55c-4f8d-11e7-80da-97eca6a3373c.gif)

**Comment by infograf768** [comment]
Closing as we have a patch https://github.com/joomla/joomla-cms/issues/16794

**Comment by joomla-ua** [comment]
Calendar always saves seconds like ":00"

1. If select TODAY in datepicker set date and time as 2017-06-29 04:17:47 but after save replace date and time as 2017-06-29 04:17:00
2. Always save article with seconds like ":00"

https://github.com/joomla/joomla-cms/issues/16908

**Comment by franz-wohlkoenig** [comment]
@joomla-ua thanks for reporting. As you have open a new Issue its not necessary to report same issue on another, closed issue.
