### ISSUE TITLE
custom fields html rendering not the same

### ISSUE THREAD

**Issue by ced1870** [joomla/joomla-cms#16594]
### Steps to reproduce the issue
1/ create a custom field for an article
2/ create a custom field for a contact

### Expected result
both fields have the same html output

### Actual result
both fields are rendered differently.

#### 1/ In the article
&lt;dd class="field-entry"&gt;
    &lt;span class="field-label"&gt;test: &lt;/span&gt;
    &lt;span class="field-value"&gt;here is my test&lt;/span&gt;
&lt;/dd&gt;

#### 2/ in the contact
&lt;dt class="contact-field-entry"&gt;
    &lt;span class="field-label"&gt;test: &lt;/span&gt;
&lt;/dt&gt;
&lt;dd class="contact-field-entry"&gt;
    &lt;span class="field-value"&gt;here is my test&lt;/span&gt;
&lt;/dd&gt;

### System information (as much as possible)

Joomla 3.7

### Additional comments

In my opinion, we shall keep the same structure for all custom fields and not have so much difference. Here not only that the css classes are different, also the HTMl is different

We should use something like this which is more general and flexible

#### For article
&lt;dd class="field-entry **contact-field-content**"&gt;
    &lt;span class="field-label"&gt;test: &lt;/span&gt;
    &lt;span class="field-value"&gt;here is my test&lt;/span&gt;
&lt;/dd&gt;

#### For contact
&lt;dd class="field-entry **contact-field-contact**"&gt;
    &lt;span class="field-label"&gt;test: &lt;/span&gt;
    &lt;span class="field-value"&gt;here is my test&lt;/span&gt;
&lt;/dd&gt;

**Comment by Bakual** [comment]
Contact has an override for the field JLayout. So this is expected to be different due to different JLayouts being used.

Of course trying to make them consistent would be great.

**Comment by ced1870** [comment]
thanks for your answer. In my mind by default we shall have a structure that is common to all components. Then the developpers/integrators can use the overrides to do what they want of course.

Now for example if I want to style the fields in my website, I have to use multiple css rules depending on how joomla renders them in each page. This is not correct I think
Having by default an override has no sense for me

Really, making things simpler would be great :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16594">issues.joomla.org/tracker/joomla-cms/16594</a>.</sub>

**Comment by ced1870** [comment]
My code suggestion in the contact JLayout override

in
components/com_contact/layouts/field

&lt;?php
/**
 * @package     Joomla.Site
 * @subpackage  com_contact
 *
 * @copyright   Copyright (C) 2005 - 2017 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */
defined('_JEXEC') or die;

if (!key_exists('field', $displayData))
{
	return;
}

$field = $displayData['field'];
$label = $field-&gt;label;
$value = $field-&gt;value;
$class = $field-&gt;params-&gt;get('render_class');
$showlabel = $field-&gt;params-&gt;get('showlabel');

if (!$value)
{
	return;
}

if ($field-&gt;context == 'com_contact.mail')
{
	// Prepare the value for the contact form mail
	echo $label . ': ' . $value . "\r\n";
	return;
}

?&gt;

&lt;dd class="field-entry contact-field-entry &lt;?php echo $class; ?&gt;"&gt;
&lt;?php if ($showlabel == 1) : ?&gt;
	&lt;span class="field-label"&gt;&lt;?php echo htmlentities($label, ENT_QUOTES | ENT_IGNORE, 'UTF-8'); ?&gt;: &lt;/span&gt;
&lt;?php endif; ?&gt;
&lt;span class="field-value"&gt;&lt;?php echo $value; ?&gt;&lt;/span&gt;
&lt;/dd&gt;
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16594">issues.joomla.org/tracker/joomla-cms/16594</a>.</sub>

**Comment by Bakual** [comment]
Since you already propose some code, can you try making a Pull Request?
Some documentation can be found here: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by brianteeman** [comment]
Closed as I made a PR for the above change.
