### ISSUE TITLE
Warning: Empty solution not allowed  Front-end Editing Save not working

### ISSUE THREAD

**Issue by goyat** [joomla/joomla-cms#16596]
### Steps to reproduce the issue

Step 1. Log in at the front page with Super Admin
Step 2. Open the article and edit some, Then, save the page
Step 3. Save, but the Warning made me unsaved the article

I tried JCE and TinyMCE with different templates but no sucess. The exception is smartphone. I can save it with smartphone, but with PC I can not save it.

### Expected result

The article should be saved successfully.

### Actual result

Warning: Empty solution not allowed

### System information (as much as possible)
Joomla 3.7.2
PHP 7.1

### Additional comments
Joomla captcha plugin is producing this bug. IF it is set to OFF, there is no issue. The captcha plugin is doing something wrong on article page.

**Comment by brianteeman** [comment]
Go to article options. Find the setting for captcha. Set it to none. Save. 

All done
