### ISSUE TITLE
Character counter for articles in the blog session

### ISSUE THREAD

**Issue by heroinerd** [joomla/joomla-cms#16597]
### Steps to reproduce the issue

I think it takes a look from the core of joomla!

### Expected result

That the functionality becomes standard in version 3.8 onwards

### Current result

Currently it is necessary to make some moorings in templates that are causing errors during the Joomla! And third party extensions.

### System information (as much as possible)

Initial text character counter for articles in the blog session. The option of having two screens or a "read more" button must be secondary.

### Additional comments

I've already suggested this functionality since the launch of the Joomla! 1.5, then 2.5, and I've made that suggestion because I see so much of the community with that need.

Unfortunately I do not master programming enough to create a project and write the functionality, but I am willing to participate in the test group I have always participated in.

Good job

hug

**Comment by brianteeman** [comment]
Sorry I dont understand what you are asking for and what the benefit will be

**Comment by franz-wohlkoenig** [comment]
@heroinerd You mean a Character Count like Word-Count in TinyMCE?

**Comment by heroinerd** [comment]
Sorry I dont understand what you are asking for and what the benefit will be

Initial text character counter for blog session. This feature is not available in Joomla!

There is now a character counter for the text of the button read more but for the text those who want to limit characters need to use the read more button and it should be a default setting to want to use the read more or limit for example: 200 characters for the beginning of the text.

Could you understand? My english is very bad

**Comment by mbabker** [comment]
If it helps, either type in your native language or use Google Translate.  I think I'm starting to understand what you're asking for (a character counter when creating/editing content), but it's still not coming across clearly.

**Comment by heroinerd** [comment]
@mbabker isso, um contador de caracteres padrão para ser usado na sessão blog. Facilitaria muito no desenvolvimento de sistemas.

**Comment by brianteeman** [comment]
English translation
> This is a standard character counter to be used in the blog session. It would make it much easier to develop systems.

**Comment by brianteeman** [comment]
If that is the request then there are many plugins on the JED for this

**Comment by brianteeman** [comment]
Closed
