### ISSUE TITLE
Subform field type - Default layout provokes error in Joomla! 3.7.2

### ISSUE THREAD

**Issue by Kubik-Rubik** [joomla/joomla-cms#16605]
### Steps to reproduce the issue

Add the example from the documentation (https://docs.joomla.org/Subform_form_field_type) to any XML manifest file and set the layout to "joomla.form.field.subform.default" -> _layout="joomla.form.field.subform.default"_

**Error: 0 Call to a member function getGroup() on null**

Only tested in Joomla! 3.7.2, previous versions could also be affected!

### Expected result

Form is loaded properly with the default subform layout.

### Actual result

Page is loaded only partly with the mentioned error above.

### System information (as much as possible)

Joomla! 3.7.2, PHP 7.1.5

### Additional comments

The layout "joomla.form.field.subform.repeatable-table" is also rendered "weird" (no spacing, text input type too wide etc.) due to changes in Isis (probably since 3.7). Should also be improved!

**Comment by Kubik-Rubik** [comment]
Cannot reproduce this behavior on another instance. Looks like a local problem, I will investigate further. This issue entry can be closed for now!

**Comment by boomsya** [comment]
Joomla 3.8.1 -  PHP 7.0.14
The same error when I try to collect list of items in remote Postgre DB
try to find solution

**Comment by boomsya** [comment]
My problem in `echo JLayoutHelper::render('joomla.searchtools.default', array('view' => $this));`

**Comment by Kubik-Rubik** [comment]
@boomsya Please open a new issue else your comment will get lost in this closed issue. Thanks!

**Comment by boomsya** [comment]
i dont want :) problem solved by deleting this line

**Comment by emuthomi** [comment]
Had a similar issue today, turned out to be a missing reference to the filter form. 
Solved by adding this in the View class `display()` function:

```
$this->filterForm = $this->get('FilterForm');
```
