### ISSUE TITLE
cmd+S Command does not save Article

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#16600]
### Steps to reproduce the issue
Change information in the article text
press cmd+S (apple) 

### Expected result
IIRC this is a new feature that the article is being saved.

### Actual result
Leaving the article without saving
Article is checked out

### System information (as much as possible)
macOs Sierra
Joomla! 3.7.2

**Comment by franz-wohlkoenig** [comment]
Closed as duplicate Report #16550<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16600">issues.joomla.org/tracker/joomla-cms/16600</a>.</sub>
