### ISSUE TITLE
Incorrect ordering of tagged items by modified date

### ISSUE THREAD

**Issue by 1inkin** [joomla/joomla-cms#16604]
### Steps to reproduce the issue

1. Add several Articles and remember the order of their modification
2. Add Tag
3. In Batch add Tag to several Articles
4. Add Menu
4.1 Menu Item Type = Tags/Tagged Items
4.2 Tag = to select the Tag
4.3 Tag Options/Order = Modified Date
5. Check ordering on page

### Expected result
The order of articles modification is equal to ordering on page of Tagged Items

### Actual result
Ordering on page of Tagged Items is equal to adding Tag in Batch. If again in Batch add Tag to some Article, this Article will change its position in ordering as if it was modified, but in the Article parameters the modified date does not change.

### System information (as much as possible)
Joomla 3.7.2

**Comment by franz-wohlkoenig** [comment]
Issue confirmed. 

After Step 5 Ordering of Articles in Front- and Backend is the same, but after Batch same Tag to some of the Articles ordering changed.

### System information
3.7.3-dev (latest nightly build)
Multilanguage Site
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by ghost** [comment]
@tonypartridge can you please have a Look?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16604">issues.joomla.org/tracker/joomla-cms/16604</a>.</sub>

**Comment by tonypartridge** [comment]
@1inkin so you are saying the issue is the modification date changes when you run a batch add to tags? Is that correct? 

If so that is correct, since you are modifying the article to add a tag, just doing it quickly and multiple times?

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 26th January 2018.

**Comment by ghost** [comment]
This has been closed as stated above – it can always be reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16604">issues.joomla.org/tracker/joomla-cms/16604</a>.</sub>
