### ISSUE TITLE
[4.0] Frontend: Menu "Parks" > Error

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#16601]
#### Click in Frontend on Menu "Parks", got:
![bildschirmfoto 2017-06-09 um 20 46 27](https://user-images.githubusercontent.com/8235763/26989952-498eb5b4-4d55-11e7-80ba-6adab3b40c10.jpg)
#### Console:
![bildschirmfoto 2017-06-09 um 20 48 52](https://user-images.githubusercontent.com/8235763/26989957-5375dd28-4d55-11e7-83d4-2f4d7f35f1a8.jpg)
GET 
http://localhost:8888/4/index.php/parks-home [HTTP/1.1 500 Internal Server Error 207ms]
GET 
http://localhost:8888/4/templates/aurora/css/template.css [HTTP/1.1 200 OK 0ms]
GET 
http://localhost:8888/4/templates/aurora/css/template.css [HTTP/1.1 200 OK 0ms]
### System information
4.0-dev
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
The bigger issue here is the errors with the template error page and not the missing content

**Comment by wojsmol** [comment]
This issue is related to namespacing.

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/16607 should fix it.

**Comment by franz-wohlkoenig** [comment]
Closed as having PR #16607 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16601">issues.joomla.org/tracker/joomla-cms/16601</a>.</sub>
