### ISSUE TITLE
Call to undefined method JApplicationAdministrator::isClient()

### ISSUE THREAD

**Issue by cguevaraDEPM** [joomla/joomla-cms#16603]
### Steps to reproduce the issue

I updated my Joomla´s site to 3.7.2 version

### Expected result

My web site in http://www.proyectomesoamerica.org:8082/index.php

### Actual result

I can´t acces Joomla´s administration panel after Joomla 3.7.2 update. It says Call to undefined method JApplicationAdministrator::isClient()

**Comment by brianteeman** [comment]
Please use the forum for support https://forum.joomla.org

**Comment by yveskiki** [comment]
Hello @cguevaraDEPM 
I've the same problem after trying to update my Joomla site to 3.7.2
I can't access to Joomla administration Panel, even the Front end not working
the same mesage " Call to undefined method JApplicationAdministrator::isClient() "

How did you fix that ?

Thank you in  advance

**Comment by cguevaraDEPM** [comment]
Hello,


I downloaded Joomla 3.6.5 (version I had updated before) manually in zip format, I unzipped it over my Joomla folder overwriting the files I already had and solved it. Remember to make a backup of your Joomla folder before doing the above. I hope this helps you


[1490028705902_Cecilia]


________________________________
De: yveskiki <notifications@github.com>
Enviado: lunes, 03 de julio de 2017 08:07 a.m.
Para: joomla/joomla-cms
Cc: Cecilia Guevara; Mention
Asunto: Re: [joomla/joomla-cms] Call to undefined method JApplicationAdministrator::isClient() (#16603)


Hello @cguevaraDEPM<https://github.com/cguevaradepm>
I've the same problem after trying to update my Joomla site to 3.7.2
I can't access to Joomla administration Panel, even the Front end not working
the same mesage " Call to undefined method JApplicationAdministrator::isClient() "

How did you fix that ?

Thank you in advance

**Comment by yveskiki** [comment]
Goooooooddddd my friend @cguevaraDEPM thank you so much for this advice, the best one so far.
Now my website works well : [www.ecolialabs.org](url)
Thank you !

**Comment by cguevaraDEPM** [comment]
How did you do to correctly add social sharing buttons in your site? What Joomla plugin do you use?


[cid:7a966650-96e6-4954-8a7a-5418177da23b]



[1490028705902_Cecilia]


________________________________
De: yveskiki <notifications@github.com>
Enviado: lunes, 03 de julio de 2017 01:13 p.m.
Para: joomla/joomla-cms
Cc: Cecilia Guevara; Mention
Asunto: Re: [joomla/joomla-cms] Call to undefined method JApplicationAdministrator::isClient() (#16603)


Goooooooddddd my friend @cguevaraDEPM<https://github.com/cguevaradepm> thank you so much for this advice, the best one so far.
Now my website works well : www.ecolialabs.org<url>
Thank you !

**Comment by yveskiki** [comment]
I've got social sharing buttons from this link [](https://www.addtoany.com/)

**Comment by cguevaraDEPM** [comment]
Thanks


[1490028705902_Cecilia]


________________________________
De: yveskiki <notifications@github.com>
Enviado: lunes, 03 de julio de 2017 04:21 p.m.
Para: joomla/joomla-cms
Cc: Cecilia Guevara; Mention
Asunto: Re: [joomla/joomla-cms] Call to undefined method JApplicationAdministrator::isClient() (#16603)


I've got social sharing buttons from this link <https://www.addtoany.com/>

**Comment by Kulikovpavel** [comment]
Got same error, after update from 3.4.8 to 3.8.0, with update package

"Fatal error: Call to undefined method JApplicationAdministrator::isClient() in /www/plugins/system/logout/logout.php on line 48"
Same error call in remember.php system plugin

Replaced files with full 3.8.0 release - same result, error.

**Comment by ghost** [comment]
@Kulikovpavel can you please look at reported issues? If its not reported create a new Issue. Comments on closed Issues didn't get much Notice.

**Comment by ggppdk** [comment]
@Kulikovpavel 

probably you have an extension that is replacing JApplicationAdministrator

try updating all or as many as you can of your 3rd party extensions

**Comment by CerberusMkII** [comment]
This issue seems to affect 3.4.x - 3.5 installations.

If you don't have any third party folders in /libraries/ wipe it out and upload the 3.8 libraries. 

Next you'll likely experience: **Error: 1054 Unknown column 'a.client_id' in 'where clause'**
https://github.com/joomla/joomla-cms/issues/15629

To fix this using phpMyAdmin you'll need to go to table #__menu_types, then click the 'Structure' tab, you'll see:
- id
- menutype
- title
- description

Add the following columns:
- Add after 'ID' - Name: **asset_id**, Type: **int**, Length/Values: **10**, Default: 'As Defined' **0**, Attributes: **UNSIGNED**
- Add after 'description' - Name: **client_id**, Type: **int**, Length/Values: **11**, Default: 'As Defined' **0**

The new structure should be:
- id
- asset_id
- menutype
- title
- description
- client_id

Then go to Extensions >> Manage >> Database and click 'Fix': 
/administrator/index.php?option=com_installer&view=database

**Comment by habashynn** [comment]
CerberusMkII, that fixed the problem partially. Thank you!
I followed Kulikovpavel's suggestion and deleted the "libraries" folder then copied over 3.8 libraries instead -- this fixed the frontend only...
Then i followed your instruction and modified that #_menu_types table structure then fixed database...
That brought back the backend but with some problems! one, is that all plugins are not showing under Extensions/Plugins, then i can't install any new extension getting the message "No installation plugin has been enabled. At least one must be enabled to be able to use the installer. Go to the Plugin Manager to enable the plugins."

I am guessing some other tables structure might need to be reconstructed as well? 
Thank you all for your help!

**Comment by CerberusMkII** [comment]
Sounds like you haven't fixed the database yet, I mention this at the end of the post
