### ISSUE TITLE
Combine menus Category Blog and Featured Articles

### ISSUE THREAD

**Issue by 1inkin** [joomla/joomla-cms#16606]
### Steps to reproduce the issue
1. Add Menu Category Blog and select a Category
2. Add Menu Featured Articles and select several Categories

### Expected result
Display on the page of all Articles from several unrelated Categories

### Actual result
Display on the page of Menu Category Blog of all Articles from only one Category
Display on the page of Menu Featured Articles of featured Articles from several Categories

### System information (as much as possible)
Joomla 3.7.2

### Additional comments
Need ability to select several Categories in Menu Category Blog or ability to display all Articles and to select to show, hide or only display featured Articles in Menu Featured Articles.
Maybe combine menus Category Blog and Featured Articles

**Comment by franz-wohlkoenig** [comment]
The [Answer](https://github.com/joomla/joomla-cms/issues/16591#issuecomment-307335011) by @brianteeman on your first Issue of this Topic didn't help?

**Comment by 1inkin** [comment]
No. To solve some problems I need this solution. This would make it easier to work with my site<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16606">issues.joomla.org/tracker/joomla-cms/16606</a>.</sub>

**Comment by brianteeman** [comment]
Sorry it is not possible - please use the forum for any further advice or suggestions

**Comment by 1inkin** [comment]
it's so sad
