### ISSUE TITLE
Add content in more than one category at a time

### ISSUE THREAD

**Issue by heroinerd** [joomla/joomla-cms#16602]
### Steps to reproduce the issue

Core look Joomla!

### Expected result

Implemented in version 3.8

### Actual result

Not yet thought of as an option for Joomla!

### System information (as much as possible)

I would like to add an article to more than one category, other free software already have this option and are very attractive for it.

### Additional comments

I believe that this feature of being able to add an article in more than one category would give more options in the post.

**Comment by Bakual** [comment]
The way categories and our routing works, it's not possible to have an item in more than one category. It would require a substantial rewrite of the CMS.
You can however use Tags to achieve a similar result.

Closing as expected behavior.
