### ISSUE TITLE
Hidden Tags

### ISSUE THREAD

**Issue by 1inkin** [joomla/joomla-cms#16611]
### Steps to reproduce the issue
1. Add Tag
2. Use the Tag to combine Articles for RSS or something other

### Expected result
Tag is not displayed in front-end

### Actual result
The Tag is displayed in front-end in Articles and module of popular Tags

### Additional comments
This is relevant for Tags that are used for work purposes and do not need to be shown to users. Need a parameter in the settings of the Tag to make it hidden.
The display in the Articles can be disabled using CSS, but in the tag list module it will still be displayed.

**Comment by brianteeman** [comment]
This is what template overrides are for.

**Comment by franz-wohlkoenig** [comment]
Can you solve Issue by ACL?

**Comment by brianteeman** [comment]
ACL will not help - template overrides are the answer to control what is displayed in this use case

**Comment by 1inkin** [comment]
I'm just trying to solve the problem of displaying articles from several categories. This can not decide using menus or assigning more than one category to one article, as I suggested earlier. I was advised do it with tags, but for this I need a lot of tags that do not need to be shown to users in front-end.

**Comment by tonypartridge** [comment]
So you need to create a template override as Brian points out. Tags filtering is working as expected, not you want to customise the output so you create a template override.

**Comment by franz-wohlkoenig** [comment]
closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16611">issues.joomla.org/tracker/joomla-cms/16611</a>.</sub>
