### ISSUE TITLE
[4.0] Multilingual installation broken

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#16610]
Install a new 4.0 joomla and choose multilingual.
#16609  is first merged.

1. When installing languages we get
`The most recent request was denied because it contained an invalid security token. Please refresh the page and try again.`
Clicking OK in the Alert and `Next` again does work and languages are installed.

2. Impossible to go further when choosing `Activate the multilingual feature`
Going back and trying again. Nope.
Choosing no Multilngual install gives the default site and admin set and
Warning 
```
Joomla was unable to automatically create the French (FR) menu.
Joomla was unable to automatically create the English (en-GB) menu.
```

The Main menus ARE created.
The langswitcher modules are created but NOT tagged to the languages
The menu items are NOT created.
The language filter plugin is enabled.
The Content Languages are created.
The articles and categories are NOT created
If I try to display the articles manager I get a 500
`'340.a.modified' isn't in GROUP BY '340.a.modified' isn't in GROUP BY`

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16610">issues.joomla.org/tracker/joomla-cms/16610</a>.</sub>

**Comment by andrepereiradasilva** [comment]
> If I try to display the articles manager I get a 500
> '340.a.modified' isn't in GROUP BY '340.a.modified' isn't in GROUP BY

the sql in 4.0 needs a full group by clause by forcing the `ONLY_FULL_GROUP_BY` sql mode in mysql (the other db already force it in default).

Any sql queries across the core that does not uses full group by queries will give that error.
See https://github.com/joomla/joomla-cms/pull/12494 for more info

side note: this SQL `ONLY_FULL_GROUP_BY` change (among the other sql modes forced in 4.0) should be in the 4.0 B/C breaks doc page.

**Comment by infograf768** [comment]
nice, and then what? :smiley:

**Comment by andrepereiradasilva** [comment]
a.modified is missing here https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_content/Model/Articles.php#L185

**Comment by franz-wohlkoenig** [comment]
installed latest staging with same Result as @infograf768 described.

**Comment by infograf768** [comment]
@andrepereiradasilva 
adding a.modified there solves that specific issue.
For the rest, all is still broken

**Comment by andrepereiradasilva** [comment]
Yes, there are several diferent issues. I just comment about one.

Btw probably 3.7.3 as that issue in PostgreSQL and sql server too, becauses the PR that causes that was merged for 3.7.3. see https://github.com/joomla/joomla-cms/pull/15825

**Comment by ghost** [comment]
Would be nice to test 4.0 multilangugage.

**Comment by C-Lodder** [comment]
@infograf768 is this still an issue with the new installer?

**Comment by infograf768** [comment]
The new installer does not propose the choice between installed lang for sites and admin, and neither the choice to install a multilang sample data.
Therefore this issue is not present now. Closing.
