### ISSUE TITLE
[4.0] Sample Page: "index.php/contact-us"-Error

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#16618]
### Steps to reproduce the issue
at given url link "Buyer" and "Owner" give `0 Call to a member function getItem() on boolean`
![bildschirmfoto 2017-06-11 um 06 33 24](https://user-images.githubusercontent.com/8235763/27008386-eaa78b36-4e6f-11e7-9843-12816103d789.jpg)

### System information
4.0.0-dev
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by joomdonation** [comment]
PR is https://github.com/joomla/joomla-cms/pull/16619

**Comment by franz-wohlkoenig** [comment]
closed as having PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16618">issues.joomla.org/tracker/joomla-cms/16618</a>.</sub>
