### ISSUE TITLE
Template: Difficult to see on hover

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#16614]
#### Templates > Protostar > css > click on "template.css":
![1](https://user-images.githubusercontent.com/8235763/27004195-77441386-4e05-11e7-8bd3-14c07dac7c19.jpg)
#### hover "template.css":
![2](https://user-images.githubusercontent.com/8235763/27004201-8c8d334e-4e05-11e7-832b-84bcd1082b00.jpeg)
### System information
3.7.3-dev (latest nightly build)
Multilanguage Site
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
closed see #17601 for a fix
