### ISSUE TITLE
[4.0] Backend: Users > Table-Head messed

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#16620]
### Steps to reproduce the issue
 This is also in LTR:
![27001829-13250fa4-4dd3-11e7-85f7-4b0c202faffa](https://user-images.githubusercontent.com/8235763/27009055-126f0a68-4e84-11e7-841e-6dc8991cff67.jpg)
![bildschirmfoto 2017-06-12 um 07 24 33](https://user-images.githubusercontent.com/8235763/27020315-413b4566-4f40-11e7-8c05-47a652d2e09e.jpg)

### System information
4.0-dev
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by ghost** [comment]
closed as Issue solved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16620">issues.joomla.org/tracker/joomla-cms/16620</a>.</sub>
