### ISSUE TITLE
Articles are shown one below the other, when using 'Read more' buttons.

### ISSUE THREAD

**Issue by Lichthagel** [joomla/joomla-cms#16623]
### Steps to reproduce the issue

- Create a category blog
- Set Leading Articles to 1
- Set Intro Articles to 4
- Set Columns to 3
- Set Links to 4
- Set to Across or Down (both don't work for me)
- Create some articles with read more marks (with intro texts)

### Expected result

- Having one article shown across full width (the leading article).
- Having three others side by side.

### Actual result

![bildschirmfoto vom 2017-06-11 13-59-59](https://user-images.githubusercontent.com/11707826/27010858-c8173618-4eae-11e7-9f51-8427fe4f5f09.png)

![bildschirmfoto vom 2017-06-11 14-05-12](https://user-images.githubusercontent.com/11707826/27010865-09f881fe-4eaf-11e7-9092-eb244c875b6e.png)

### System information (as much as possible)

- Using docker container, updated to Joomla 3.7.2.
- Protostar, but happens with other templates too

### Additional comments

Somehow the span4-elements are put inside the previous span4-elements.

**Comment by franz-wohlkoenig** [comment]
Can't confirm. Used Settings as given above, all works as expected.
### System information
3.7.3-dev (latest nightly build)
Multilanguage Site
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by Lichthagel** [comment]
Hmm. I will try to spin up a new docker container and try again with the same settings.

**Comment by Lichthagel** [comment]
![bildschirmfoto vom 2017-06-11 14-29-02](https://user-images.githubusercontent.com/11707826/27011022-5924d89c-4eb2-11e7-83af-d52fa8cfaee1.png)
It does work. Now it puts all span elements below each other. But why not in my other installation?

**Comment by franz-wohlkoenig** [comment]
closed as no Core-Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16623">issues.joomla.org/tracker/joomla-cms/16623</a>.</sub>
