### ISSUE TITLE
[4.0] Edit button in article modal field broken

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#16629]
### Steps to reproduce the issue
* Create or edit a menuitem of type "Single Article"
* Select an article
* Try to edit that article by using the "Edit" button

### Expected result
The selected article is loaded into the form in the modal

### Actual result
Empty form in the modal, like when creating a new article

### Additional comments
From what I saw the URL that is loaded from within the modal is `http://localhost/joomla4/administrator/index.php?option=com_content&view=article&layout=modal&tmpl=component&c7dfd92edd252bd329b97a6431da2de8=1&task=article.edit&id=%27%20+%20document.getElementById(`
So there is something wrong with the JS part that is supposed to read the ID of the article from the input.

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.

**Comment by Bakual** [comment]
@dgt41 Do you know what changed here between J3 and J4? Because the code doesn't look that different to me so I suspect a change in another place (modal?)

**Comment by dgt41** [comment]
`%27%20+%20document.getElementById(`
Well that part should be a number but it's actual javascript. Probably an error in the field modal js

**Comment by Bakual** [comment]
Yep, I figured out that myself :smile: 
The JavaScript is supposed to read the number but it looks like the URL got encoded and thus it breaks.
It's working fine with the same code in J3.

**Comment by Bakual** [comment]
@dgt41 I had a look again and the only difference I found which may be the cause is https://github.com/joomla/joomla-cms/pull/15374.
Before, the URL was used as an attribute of the iframe tag. Apparently it worked to have a JS part in that URL.
Now the URL is used in a data-url and the JS part is now broken.

I have no idea how that could be solved but it seems important to fix. From what I saw, https://github.com/joomla/joomla-cms/issues/16639 is the same or at least a similar issue.

**Comment by dgt41** [comment]
> I have no idea how that could be solved but it seems important to fix.

Of course everything that is currently broken needs to be fixed, but looking at the great picture of J4 this **will** be fixed when we transition to custom elements for modals (and tabs, accordion, dropdown). All I'm saying is you re right this is broken and needs a fix, but let's wait till we have the UI components in place (in other words let's not waste man hours on this as it will be fixed later on)

I hope my comment makes some sense :)

**Comment by Bakual** [comment]
I'd prefer to have it fixed soon as I already wasted a few hours on it only to find out that it's the same "known" issue. I guess it will be the same fix anyway that needs to be applied for BS modals as it would be for custom elements.

**Comment by brianteeman** [comment]
Confirming that the edit button is still broken

**Comment by brianteeman** [comment]
One year later and we are still waiting for the panacea of custom elements to fix everything. With only one person working on custom elements we really need to rethink if its an achievable thing to do

**Comment by Quy** [comment]
This appears to be fixed and related to PR #25001.
