### ISSUE TITLE
[com_fields] Contact Mail fields do not respect the categories

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#16622]
### Steps to reproduce the issue

- install clean staging
- create 2 contact categories (contactcategory 1 & contactcategory 2)
- create a contact in each category (contact 1 & contact 2)
- create two contact mail fields (contactfield 1 & contactfield 2)
- and assign contactfield 1 to contactcategory 1 and contactfield 2 to contactcategory 2 category
- create a contact form with "contact 1" and "contact 2"

### Expected result

Only the mail fileds assigned to category contactcategory 1 is showed to contact 1 and only the contactcategory 2 fileds are showed for contact 2.

### Actual result

All fields are showed by ignoring the contactcategory assigment

#### Contact fields
![image](https://user-images.githubusercontent.com/2596554/27010809-d314723e-4ead-11e7-881e-0d130629c234.png)

#### Contacts
![image](https://user-images.githubusercontent.com/2596554/27010810-de2f1606-4ead-11e7-90cd-bb461121f132.png)

##### contact 1 
![image](https://user-images.githubusercontent.com/2596554/27010817-f2013cf4-4ead-11e7-8150-1d6d2d230631.png)

##### contact 2
![image](https://user-images.githubusercontent.com/2596554/27010821-fe6c81a6-4ead-11e7-8960-abd830d80b9b.png)

**Comment by franz-wohlkoenig** [comment]
closed as duplicate Report of #16574<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16622">issues.joomla.org/tracker/joomla-cms/16622</a>.</sub>

**Comment by zero-24** [comment]
Thanks i have not noticed it before.

**Comment by laoneo** [comment]
Please test pr #16666 if it fixes the issue.
