### ISSUE TITLE
[4.0] "Multilingual Status" module doesn't play nice with New Media Manager

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#16637]
### Steps to reproduce the issue
* "Multilingual Status" module enabled on a multilingual site (not sure if that part is needed)
* Visit Media Manager

### Expected result
Works

### Actual result
Can't click on anything

### Additional comments
Look at the source there is a div from the multilingual module which covers the whole page:

![image](https://user-images.githubusercontent.com/1018684/27037014-f7a278d8-4f86-11e7-9f81-6ed054b0fc5a.png)

Disabling the module fixes the issue.

**Comment by dneukirchen** [comment]
Good catch! 
Seems like a conflict between flying-focus (used by module) and vue-focus used by new media manager. Will take a look at this.

**Comment by laoneo** [comment]
@Bakual can you please test https://github.com/joomla-projects/media-manager-improvement/issues/251 if it fixes your issue? Guess this one can be closed as we have a pr.

**Comment by franz-wohlkoenig** [comment]
closed as having [PR](https://github.com/joomla-projects/media-manager-improvement/issues/251 "")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16637">issues.joomla.org/tracker/joomla-cms/16637</a>.</sub>
