### ISSUE TITLE
[4.0] Multilingual Associations component can't select a target item

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#16639]
### Steps to reproduce the issue
* Go to Multilingual Associations component and select for example an english article or category
* Select a target language
* Now try the "Select Target" link (the button misses a class, thus looks ugly)

### Expected result
Modal opens where I can select an item

### Actual result
Modal opens but no items are found. "No Matching Results" is shown.

### Additional comments
Same thing happens when the item is already associated and you use the "Change Target" button.

**Comment by infograf768** [comment]
Also, similar issue when clicking on the assoc button when there are associated items in the manager. In the side by side view, the target is not displayed.

**Comment by franz-wohlkoenig** [comment]
@Bakual is this Issue solved by #16779?

**Comment by Bakual** [comment]
No, this is a different one. The other was only about the button in the toolbar.

**Comment by brianteeman** [comment]
As far as I can tell this has now been resolved so I am closing - it can always be re-opened if I am mistaken.
