### ISSUE TITLE
Mod_articles_category gets wrong module id

### ISSUE THREAD

**Issue by TheWhykiki** [joomla/joomla-cms#16640]
If you use more than one mod_articles_category Module the resulting $module->id is wrong in template-file. Shown is only the latest created module id of this module type. So this causes wrong headlines and module appearance. 
Testing $module->id in mod_articles_category.php gives the correct value if I test the ouput before the if-statement in line 64.
Outputting after the if-statement gives the value of the last created mod_articles_category.

**Comment by Bakual** [comment]
Do you have any caching enabled on your site? Maybe 3rd party solutions?

**Comment by TheWhykiki** [comment]
It's a clean joomla install 3.7.2, only Maximenu CK installed

**Comment by Quy** [comment]
@TheWhykiki Can you reproduce the issue without Maximenu CK?

**Comment by TheWhykiki** [comment]
Fixed....my fault. Was caused by false synchronizing folders with my phpStorm. Can be closed
