### ISSUE TITLE
Upgrade from 3.6.5 to 3.7.2 causing several admin menu items to disappear

### ISSUE THREAD

**Issue by montellsp** [joomla/joomla-cms#16643]
### Steps to reproduce the issue

Upgrade a site in Joomla 3.6.5 to Joomla 3.7.2

### Expected result
Everything works just fine.

### Actual result

The following administration menu items disappears after upgrade to 3.7.2

Component/Banners/Banners
Component/Banners/Categories
Component/Banners/Clients
Component/Banners/Tracks
Component/Contacts
Component/Contacts/Contacts
Component/Contacts/Categories
Component/Messaging
Component/Messaging/New Private Message
Component/Messaging/Read Private Message
Component/News Feeds
Component/News Feeds/Feeds
Component/News Feeds/Categories
Component/Redirect
Component/Search

### System information (as much as possible)

dbversion: 5.6.35
dbcollation: latin1_swedish_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 5.6.30
server: Apache/2.4.25
version: Joomla! 3.6.5

### Proposed Workaround
The only way to get back theses menuitem is to update table xx_menu (xx is your table prefix in configuration) 
with the menutype = 'main'. This is what i ended up to do.

Have anyone faced with such issue after upgrade ?

**Comment by Quy** [comment]
If you have a backup of your database before the upgrade, please test this pr #16577 and report your test.

**Comment by richard67** [comment]
This issue here can be closed because 1. it is a duplicate to #15719 , and 2. there is a PR which solves it: #16577 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16643">issues.joomla.org/tracker/joomla-cms/16643</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16643">issues.joomla.org/tracker/joomla-cms/16643</a>.</sub>

**Comment by richard67** [comment]
@montellsp Please test #16577 ([issue tracker link see here](https://issues.joomla.org/tracker/joomla-cms/16577)).
