### ISSUE TITLE
Article changing from categorie after saving

### ISSUE THREAD

**Issue by joris85** [joomla/joomla-cms#16642]
### Steps to reproduce the issue
Joomla 3.7.2
Menu-item create article with default categorie on active in frontend (after login).
Edit and saving an article in frontend changes the categorie unexpected.

### Expected result
Staying in same categorie if i do not touch the categorie

### Actual result
The article goes toe the categorie of the first menu-item with create an article that has a setting with a default article.

### System information (as much as possible)

PHP Built On	Linux njord.xolution.nu 2.6.32-642.13.1.el6.x86_64 #1 SMP Wed Jan 11 20:56:24 UTC 2017 x86_64
Database Version	5.5.53-log
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.14
Web Server	Apache/2
WebServer to PHP Interface	fpm-fcgi
Joomla! Version	Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments
If i delete the create new article menu items or i set the default categorie to not it works.
Also if the first of the create new articles is without default it is working.

Can anybody reproduce this issue?

**Comment by franz-wohlkoenig** [comment]
closed as duplicate Report of #16612<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16642">issues.joomla.org/tracker/joomla-cms/16642</a>.</sub>
