### ISSUE TITLE
Farsi (Persian) language error in article edit page - DateTime::__construct(): Failed to parse time string (۱۳۹۶-۰۳-۲۳ ۱۶:۴۸:۰۰)

### ISSUE THREAD

**Issue by ViscountVic** [joomla/joomla-cms#16667]
### Steps to reproduce the issue
Install Farsi (Persian) language for administration area.
Official Language Pack version 3.7.2.1 from  https://update.joomla.org/language/details3/fa-IR_details.xml

Then go into 1) کاربران 
2) مدیریت
3) ایجاد کاربر جدید
or in English translation will be:
Content -> Articles -> Add New Article
If you will try change category to another, page will be updated and you will receive error in page title:
0 DateTime::__construct(): Failed to parse time string (۱۳۹۶-۰۳-۲۳ ۱۶:۴۸:۰۰) at position 0 (�): Unexpected character

### Expected result
Page should be updated and ready for next editing

### Actual result
Page updated with errors, top controls bar lost, editor not loaded, big part of HTML code lost.
In page header you will see error message:
0 DateTime::__construct(): Failed to parse time string (۱۳۹۶-۰۳-۲۳ ۱۶:۴۸:۰۰) at position 0 (�): Unexpected character

### System information (as much as possible)
Setting 	Value
 
PHP Built On 	Linux s28.h.mchost.ru 2.6.32-673.26.1.lve1.4.23.el6.x86_64 #1 SMP Thu Mar 9 15:13:22 EST 2017 x86_64
Database Version 	5.6.32-78.0-log
Database Collation 	cp1251_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.6.30
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0 
Language: Persian (IR), Persian (Iran), Language: Persian (IR), Persian (Iran)
Official Language Pack version 3.7.2.1 from  https://update.joomla.org/language/details3/fa-IR_details.xml

**Comment by Quy** [comment]
Duplicate #16628
