### ISSUE TITLE
Category is Changed when Editing Article in Front end (If create article exists)

### ISSUE THREAD

**Issue by rytechsites** [joomla/joomla-cms#16669]
### Steps to reproduce the issue
1. Have a menu item on the front end to Create an Article in a specific Category (Category: Birds)
2. Edit an article in the front end (that is in Category: dogs), on the save of this article it will SWITCH to the category of Birds
3. To fix, we just changed the 'create aritcle' to no longer point to a specific category.

Others found this issue as well, here:
https://forum.joomla.org/viewtopic.php?f=706&t=950209&p=3479231#p3479231

### Expected result

The article that I'm editing should not ever have the category change without me changing it specifically.

### Actual result
Article that I'm editing category changes

### System information (as much as possible)
Joomla 3.7.2

**Comment by franz-wohlkoenig** [comment]
closed as duplicate Report #16612<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16669">issues.joomla.org/tracker/joomla-cms/16669</a>.</sub>
