### ISSUE TITLE
[4.0] file_put_contents over JFile?

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#16679]
### Steps to reproduce the issue

https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/namespacemap.php#L133

### Expected result

JFile::write

### Actual result

file_put_contents

### Additional comments

Why do we force file_put_contents here when we have JFile that can handle that?

**Comment by zero-24** [comment]
As the files was changed this line is moved here: https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/namespacemap.php#L166

**Comment by Bakual** [comment]
@yvesh I think that's your code.

**Comment by zero-24** [comment]
Closing as there is no decision of the code yet.
