### ISSUE TITLE
Subform not show tootltip and popover

### ISSUE THREAD

**Issue by mvanvu** [joomla/joomla-cms#16676]
If I create a new subform field with some description to show Bootstrap popover and then, The new "subform row add" will not listen any Bootstrap tooltip or popover event.

### I have a solution to fix it (consider to PR).
Add new update after `setUpShowon(row)` on line 222 `media/jui/js/cms-uncompressed.js`: 
```
// Fix tooltip and popover
$row.find('.hasTooltip').tooltip();
$row.find('.hasPopover').popover({
         container: 'body',
         trigger: 'hover focus'
});
```

**Comment by ghost** [comment]
~~can you please edit the Issue at [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/16676) and select the Categories – thanks.~~

**Comment by ghost** [comment]
@dgt41 can you please have a Look as @mvanvu wrote at #16695:

> The same problem #16676 but I think it depends on the template isis/js/template.js. So, I have tried to resolve it on template.js. Unluckily, it looks like has some conflict with cms.js.

**Comment by ghost** [comment]
reminder for @dgt41 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16676">issues.joomla.org/tracker/joomla-cms/16676</a>.</sub>

**Comment by dgrammatiko** [comment]
@mvanvu theoretically your code should work here. It's the same issue and the reason why this is happening is explained here: https://github.com/joomla/joomla-cms/issues/16695#issuecomment-360972228

**Comment by Quy** [comment]
Would PR #12996 fix this issue?

**Comment by Quy** [comment]
See PRs #19722 and #12996 / #20221 / #20222 / #20224 / #20225.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16676">issues.joomla.org/tracker/joomla-cms/16676</a>.</sub>
