### ISSUE TITLE
[4.0] Eclipse shows some files are not indexed

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#16682]
Each file with an interrogation mark does not show as indexed:
![screen shot 2017-06-14 at 11 05 50](https://user-images.githubusercontent.com/869724/27124518-9817bf7e-50f1-11e7-9b30-e843c6dc96af.png)
![screen shot 2017-06-14 at 11 06 08](https://user-images.githubusercontent.com/869724/27124521-9c0e28ca-50f1-11e7-88fc-0f09283150b7.png)

**Comment by yvesh** [comment]
@infograf768 we moved com_config to the (legacy) MVC (which changed folder names for example from model to Model and brought the old models folder back). What OS are you using?

**Comment by infograf768** [comment]
hmm. 
We have an issue here. It seems that on Macintosh, both `Model` and `model` are not fetched by Eclipse.
Therefore I get only `model`

**Comment by Bakual** [comment]
Currently in 4.0-dev, for whatever reason, com_config has both a `model` and `Model` folder. See https://github.com/joomla/joomla-cms/tree/4.0-dev/administrator/components/com_config

That will certainly not work for Windows machines as Windows doesn't make a difference between uppercased and lowercased folders.

**Comment by laoneo** [comment]
You can put the PHP classes into a src folder (i know some people don't like it) then it will work and you will become upgrade safe. I guess the upgrade from 3 to 4 will also not work on Windows for com_config.
Thats the challenge every component faces when it get changed to namespaces.

**Comment by Bakual** [comment]
> Thats the challenge every component faces when it get changed to namespaces.

Only when they followed the "new MVC" like com_config. The classic MVC used different folder names and there will be no issues when going to namespaces. So yes, we will need some special workaround like moving the classes to "src" for com_config (which we hopefully can revert in a later release) due to that.

**Comment by yvesh** [comment]
#16700 should fix this @infograf768 please test :-)

**Comment by laoneo** [comment]
Yes I meant new MVC.
