### ISSUE TITLE
[4.0] Plugin extension NAMESPACEMAP has no language files

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#16683]
As title says.

**Comment by yvesh** [comment]
@infograf768 true, will add them once we have a final decision (please keep the issue open)

**Comment by ghost** [comment]
@yvesh is there a final Decision?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16683">issues.joomla.org/tracker/joomla-cms/16683</a>.</sub>

**Comment by ghost** [comment]
gently Reminder @yvesh.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16683">issues.joomla.org/tracker/joomla-cms/16683</a>.</sub>

**Comment by brianteeman** [comment]
@yvesh @wilsonge What is the status with this plugin?

**Comment by wilsonge** [comment]
We need the files - I want to get https://github.com/joomla/joomla-cms/pull/18703 merged which fully transitions us over to it

**Comment by brianteeman** [comment]
Closed as resolved with #20951
