### ISSUE TITLE
[4.0] Toolbar base has no more div with id

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#16684]
As title says.
We cannot anymore target with js a toolbar button with its id as base.php just displays data.

We have
```
<?php echo $displayData['action']; ?>
```
while we have in 3.7.x
```
<div class="btn-wrapper" <?php echo $displayData['id']; ?>>
	<?php echo $displayData['action']; ?>
</div>
```

It's specially useful in com_associations when displaying the side by side page.

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/16749

**Comment by franz-wohlkoenig** [comment]
closed as having PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16684">issues.joomla.org/tracker/joomla-cms/16684</a>.</sub>
