### ISSUE TITLE
JApplication class in 3.8

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#16681]
### Steps to reproduce the issue
The current dev package of J3.8 has a B/C break due to the removal of JApplication class.
What's the plan for this? Should the legacy  JApplication still be available until 4.0 to not break B/C?

### Actual result
![japplication](https://user-images.githubusercontent.com/17835460/27123689-eff4d68a-50ee-11e7-90c1-96a9cf98e156.PNG)

**Comment by franz-wohlkoenig** [comment]
can you please edit the Issue at [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms "") and select the Categories – thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16681">issues.joomla.org/tracker/joomla-cms/16681</a>.</sub>

**Comment by mbabker** [comment]
The clas is most assuredly still there.  https://github.com/joomla/joomla-cms/blob/3.8-dev/libraries/legacy/application/application.php

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/blob/3.8-dev/administrator/components/com_admin/script.php#L2172

That line needs to be taken out of the deleted folders array because the folder isn't being deleted in 3.x.  If someone would do a PR it'd be appreciated.

**Comment by joeforjoomla** [comment]
Thanks Michael, indeed the class/folder is in the J3.8 package but it got deleted as you pointed out.
![japplication2](https://user-images.githubusercontent.com/17835460/27132333-cc2c3912-510e-11e7-8e55-1ada661e922c.PNG)

**Comment by laoneo** [comment]
PR is here #16687.

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16687<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16681">issues.joomla.org/tracker/joomla-cms/16681</a>.</sub>
