### ISSUE TITLE
[4.0] JS Compatibility with IE11

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#16688]
### Steps to reproduce the issue
Open backend with IE11

### Expected result
Works

### Actual result
I get an error in my console directly after logging in:
![image](https://user-images.githubusercontent.com/1018684/27135639-563ec228-5119-11e7-97c2-1aa5a63185f6.png)

I get another error when accessing a list view (eg article manager):
![image](https://user-images.githubusercontent.com/1018684/27135752-ae7b19b4-5119-11e7-8523-cce806542b3e.png)

### System information (as much as possible)
Used IE11 on Windows 7 for that test.

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/16693

**Comment by Bakual** [comment]
Reopening since that PR didn't help at all.

**Comment by C-Lodder** [comment]
Really? It fixed the console error for me in IE11

**Comment by Bakual** [comment]
Still exact same error message, only a few lines later due to the added lines from your PR.

![image](https://user-images.githubusercontent.com/1018684/27154599-e6fa8ebe-5155-11e7-8d77-e11dbb36a77d.png)

Tested on currrent 4.0-dev branch (commit https://github.com/joomla/joomla-cms/commit/afa4756f18c31c3c44d2635d2a9f269015a4bc31)

**Comment by dgt41** [comment]
@Bakual can you translate the error message please?

**Comment by Bakual** [comment]
> The object doesn't support the property or method "closest"

The difference to the first test is that this is now on a Windows 10 computer (at home) while the other was a Windows 7 (at work). But I guess that shouldn't matter.

**Comment by C-Lodder** [comment]
It shouldn't make a difference at all as I believe the IE version are exactly the same....just with a different version number (11 - 12)

**Comment by Bakual** [comment]
It's always IE 11. There is no IE12 😄

**Comment by C-Lodder** [comment]
That was the beer talking lol

The PR has unfortunately been merged (without tests) so could you test 1 more time and let me know if you still get an error from the `template.js`?

You also mentioned an error in the list views....just FYI, that PR wasn't supposed to fix that....only the sidebar ;)

**Comment by Bakual** [comment]
> You also mentioned an error in the list views....just FYI, that PR wasn't supposed to fix that....only the sidebar ;)

Yeah, got that. Another reason why the issue shouldn't have been closed 😄

**Comment by Bakual** [comment]
> The PR has unfortunately been merged (without tests) so could you test 1 more time and let me know if you still get an error from the template.js?

Not sure what to test. My test was done with the merged PR already and that PR didn't get any changes after the merge to my knowledge. Or did I miss something?

**Comment by wilsonge** [comment]
I'm assuming you've ensured it's not browser cache or something stupid

**Comment by C-Lodder** [comment]
Hmm odd, cause before the PR, I was getting a console log error regarding `closest()`, which prevented the sidebar from working at all. After the PR, it was all good.

@ciar4n could you test on IE11 please and see if you get any errors?

**Comment by Bakual** [comment]
> I'm assuming you've ensured it's not browser cache or something stupid

I verified in the browser dev tools that the JS files got the changes in it. As you can see from the screenshot, there is also a difference in the linenumbers where the error occurs, the difference is exactly by the lines added by the PR. So I doubt it is browser caching, would be very odd then.

**Comment by ciar4n** [comment]
Getting the same error...

> Object doesn't support property or method 'closest'

This not the reason for?.. https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/js/template.js#L17

**Comment by C-Lodder** [comment]
That's just the function for this: https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/js/template.js#L137

Supposed to be like jQuery's `closest()` function

**Comment by wilsonge** [comment]
In that case https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/js/template.js#L137 this line should be `var firstLevel = closest(allLinks[i], '.collapse-level-1');` rather than the current line?

**Comment by C-Lodder** [comment]
@Bakual - could you try the above and see if you still get the same error?

**Comment by Bakual** [comment]
The change suggested by @wilsonge seems to fix the first error indeed.

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/17029

**Comment by ghost** [comment]
closed as having PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16688">issues.joomla.org/tracker/joomla-cms/16688</a>.</sub>
