### ISSUE TITLE
[3.7] Subforms multiple not styling yes-no radio buttons properly

### ISSUE THREAD

**Issue by wigman27** [joomla/joomla-cms#16695]
### Steps to reproduce the issue
Hi,

I have found a problem with the new subforms multiple option.

Create subform field with a "yes-no" set of radio buttons.

When adding a row the radio buttons will not style.

### Expected result

A yes-no set of buttons styled as normal

### Actual result

Partialy unstyled radio buttons

### Additional comments

I have narrowed it down to a JavaScript issue. I think it is because the radio buttons don't exist in the DOM until you press the "add" button to create a new row.

The script file to create the yes-no styling only runs on document ready and doesn't run again. Hence not applying the click event or "btn" classes

**Comment by mvanvu** [comment]
The same problem #16676 but I think it depends on the template isis/js/template.js. So, I have tried to resolve it on template.js. Unluckily, it looks like has some conflict with cms.js.

**Comment by wigman27** [comment]
Yes,
I have got around it as I am using the subform field as a baseline to create my own custom field.
I am using the Isis template JavaScript in another function that fires each time I add a row.
Thanks
Lee
		

		
	





On Thu, Jun 15, 2017 at 12:49 PM +1000, "Mai Vu" <notifications@github.com> wrote:












The same problem #16676 but I think it depends on the template isis/js/template.js. So, I have tried to resolve it on template.js. Unluckily, it looks like has some conflict with cms.js.

**Comment by franz-wohlkoenig** [comment]
closed as duplicate Report of #16676, thanks for Report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16695">issues.joomla.org/tracker/joomla-cms/16695</a>.</sub>

**Comment by dgrammatiko** [comment]
> The script file to create the yes-no styling only runs on document ready and doesn't run again

True! Unfortunately J3.x doesn't have any js event system which means the subform script needs to watch for DOM changes and apply any extra needed functionality manually. This is fixed in J4 by moving all the fields to Custom Elements (meaning each field will be responsible for it's own functionality). Back to J3.x: there needs to be an observer for each new row added and then try to apply the `btn btn-group` functionality manually

**Comment by Quy** [comment]
@dgt41 Is #11299 the same issue?
