### ISSUE TITLE
com_redirect (plugin). "Warning: Error loading component: , Component not found"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#16690]
### Steps to reproduce the issue
- Current staging with testing datas. Issue reproduceable with J! 3.7.2 and earlier.

- "Activate" .htaccess.
- Joomla configuration: Set "Use URL Rewriting": YES
- Activate plugin "System - Redirect" with option "Collect URLs" = YES.
- FE: open item "Main Menu" > "Sample Sites" (example.org/sample-sites). Keep opened.
- BE: In Menu Manager open item "Sample Sites" of menu "Main Menu".
- Change "Menu Item Type": "Menu Heading".
- Reload FE page. 404 error page. Keep opened.
Have a look on the message: "Error loading component: , Component not found." and keep in mind.

- BE: Components > Redirect.
- Redirect collected 404 (example.org/sample-sites) to e.g. example.org/parks-home.
- Reload FE page.
- Redirection works "correctly" BUT message:

> Warning: Error loading component: , Component not found.
This message comes from the application messagequeue (see above) that has not been cleaned before redirect.

![14-06-_2017_16-05-57](https://user-images.githubusercontent.com/11038612/27136663-2edd90b2-511c-11e7-9e88-bf944e9218fc.jpg)

**Comment by bertmert** [comment]
See PR https://github.com/joomla/joomla-cms/pull/16728 and test please.

**Comment by bertmert** [comment]
Reopening. See discussion in https://github.com/joomla/joomla-cms/pull/16728

**Comment by ppetree** [comment]
This is still going on... Joomla! 3.7.2 Stable

**Comment by brianteeman** [comment]
The current release is 3.8.1 please update. There is no point in investigating your issue as it may have already been resolved in the multiple releases since your version

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16690">issues.joomla.org/tracker/joomla-cms/16690</a>.</sub>
