### ISSUE TITLE
getFieldset($name) does not retrieve values of parameters

### ISSUE THREAD

**Issue by individual-it** [joomla/joomla-cms#16696]
### Steps to reproduce the issue
1. download and install example component from here: https://docs.joomla.org/J3.x:Developing_an_MVC_Component/Adding_configuration
2. edit one message
3. set  "Show category" to "Hide"
4. save message
5. open same message

### Expected result
"Show category" set to "Hide"

### Actual result
"Show category" set to "Global"

### System information (as much as possible)
PHP 7.1
Joomla 3.7.2

### Additional comments
the parameter is set correctly in the database
the whole problem seems to be that `getFieldset()` does retrieve the fields correctly but not the value, the value is always empty.
It works fine in Joomla 3.5
it works fine for items defined in `<form><fieldset>` in `forms/xxxxx.xml` but not for items defined in `<form><fields name="params"><fieldset>`

I stumbled over this issue in my own extension. Workaround for me to do a `$field->setValue()` before `echo $field->input;` but that is not a real fix, is it?

**Comment by ghost** [comment]
couldn't find Component for Download at given Url.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16696">issues.joomla.org/tracker/joomla-cms/16696</a>.</sub>

**Comment by ggppdk** [comment]
This would happen if the 
- $this->item that JForm got by calling `getItem()` does not have the property
`$this->item->params` converted to be an object (or an array) of the data for the parameters

e.g. it is still a JSON string, because maybe you deleted this part out of getItem ?

```php
// Load the JSON string
$params = new JRegistry;
$params->loadString($this->item->params, 'JSON');
$this->item->params = $params;
```

about:
> it works fine in Joomla 3.5

maybe in J3.5 if $this->item->params is a JSON string then it will be silently decode into an JRegistry object ?

**Comment by jwaisner** [comment]
@individual-it is this still occurring in the latest J3?
