### ISSUE TITLE
[4.0-dev] AppVeyor errors | Could not parse the requested URI

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#16698]
### Steps to reproduce the issue

Could not parse the requested URI http://mydomain.comC:\projects\joomla-cms\libraries\vendor\bin\/../phpunit/phpunit/phpunit

https://ci.appveyor.com/project/joomla/joomla-cms/build/1.0.6525/job/le66379sbg5bhgc1

### Expected result

tests passes

### Actual result

tests fails

### System information (as much as possible)

none

### Additional comments

none

**Comment by wilsonge** [comment]
Anybody got any good ideas here. I don't understand how the hell we end up with that URL given none of JURI has changed from 3.x :/

**Comment by wilsonge** [comment]
To expand on this a bit:

Part of it stems back to this https://github.com/joomla-framework/uri/pull/6 which basically means that we throw an exception if we can't parse the URI (which we didn't before). So honestly we are probably trying to parse this same URL in 3.x but are just ignoring things when we fail to parse that URL

Quite why the URL has a filesystem path in it though to start with I have absolutely no idea :)

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16905<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16698">issues.joomla.org/tracker/joomla-cms/16698</a>.</sub>
