### ISSUE TITLE
[4.0] Multilingual. Home page wrong title and url when home is a featured menu item

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#16691]
URL is now
`http://localhost:8888/joomla_400/fr/?view=featured`
instead of `http://localhost:8888/joomla_400/fr/`
This whatever the setting for the "Modern" SEF router.
Page Title always get the en-GB home menu item.

Screenshot of the fr-FR home page where the menu item is `Accueil`
![screen shot 2017-06-14 at 16 12 54](https://user-images.githubusercontent.com/869724/27137012-0df3c79e-511d-11e7-9d2b-db1345b0e4da.png)

**Comment by wilsonge** [comment]
Can you test this on 3.8 please

**Comment by infograf768** [comment]
@wilsonge 
These 2 errors do not exist in 3.8.
Evidently, if we use the "Modern Browser", the links thereafter (when no hidden menu item for a Root category) will give
`joomla-cms-3.8-dev/fr/?view=article&id=2:article-fr-fr`
`joomla-cms-3.8-dev/fr/?view=category&id=9`
until someones codes a fall back to legacy SEF when no root menu item.

**Comment by wilsonge** [comment]
There shouldn't be a modern SEF router setting in J4. That only exists in 3.8 - and the results of 3.8 SEF with modern routing enabled should be the same as J4 :/

**Comment by infograf768** [comment]
That is not the matter here. Remains the 2 errors I stated which still exist in present 4.0 branch.

**Comment by JimJGitHub** [comment]
@wilsonge wrong url when home is a featured menu item  https://github.com/joomla/joomla-cms/issues/18771

This is big Joomla 3,8 url issue and huge problem for real sites

**Comment by infograf768** [comment]
@wilsonge 

I tested this again in present 4.0 branch
Solved: Page title is now correct depending on active language menu item.
Not solved: The Home menu items give `http://localhost:8888/joomla40/fr/?view=featured` instead of `http://localhost:8888/joomla40/fr/` when the home is a featured view.

**Comment by csthomas** [comment]
I suggest to test https://github.com/joomla/joomla-cms/pull/18429

**Comment by infograf768** [comment]
@csthomas 
This Issue is for 4.0.

But will test  #18429 on staging as we may have the same issue indeed

**Comment by infograf768** [comment]
In fact that specific issue with `?view=featured` does not exist in staging (for Home pages)

**Comment by infograf768** [comment]
Interesting:
https://github.com/joomla/joomla-cms/pull/18429 can be applied to the 4.0 branch.
It indeed solves that specific issue with featured menu items as Home pages in multilang but creates other issues
. for example when clicking on the title of an article where the langtag is added at the end of the url
`http://localhost:8888/joomla40/cattoutes/categorie-fr-fr/article-fr-fr/fr/`
=> 404

EDIT: in fact that issue already exists in 4.0

**Comment by csthomas** [comment]
@infograf768 Are you saying, #18429 fixes issue with featured and does not break above mentioned issue with language?
I yes, can you add a comment at #18429 ?

**Comment by infograf768** [comment]
well, that is in 4.0 and does not solve the article wrong placement of sef lang when clicking article.
as i said, i do not have the home page issue in 3.8 in multilingual

**Comment by brianteeman** [comment]
I cannot confirm this. Either it has been resolved elsewhere or ....

<img width="257" alt="chrome_2018-03-25_15-23-11" src="https://user-images.githubusercontent.com/1296369/37876158-8e37404a-3040-11e8-84ac-72fee37296ce.png">

**Comment by infograf768** [comment]
Title is now corrected when menu item is Home.

Any link which is not home is broken. Will create issue
