### ISSUE TITLE
[4.0] Database Fixer unexpected removes files

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#16704]
### Steps to reproduce the issue
* On a 4.0 installation, click the database fix button in Extensions -> Manage -> Database.
* Check Git for removed files

### Expected result
* administrator/manifests/packages/pkg_weblinks.xml is removed

### Actual result
Additionally removed files:
* administrator/components/com_languages/layouts/joomla/searchtools/default.php
* administrator/components/com_media/models/forms/file.xml
* media/com_banners/js/admin-banner-edit.js
* media/com_finder/js/finder.js
* media/editors/codemirror/css/codemirror.css

### Additional comments
I'm not sure why they get removed. Those are files which are present in GitHub so I would not expect them to be removed (or they should be removed from GitHub).
The Weblinks one is a known exception due to the way we decoupled it. We could probably remove it from GitHub in 4.0.

**Comment by yvesh** [comment]
> We could probably remove it from GitHub in 4.0.
We need a solution for translations etc in Web Links first. That's the reason there are still some files remaining in the core.

**Comment by Bakual** [comment]
That's true for the translation files, the package file however was another reason to my knowledge. That file wasn't present prior to the decoupling and we had to add it so weblinks is a real package. The fixer removes it when weblinks isn't installed. If we only allow to upgrade to 4.0 from versions after weblinks is decoupled, then we no longer need it.

**Comment by mbabker** [comment]
Whatever is in the com_admin upgrade script's deleted files/folders arrays is what's getting removed.  If that's not right for whatever reason then that's the place to fix it.

**Comment by Bakual** [comment]
I'll try to figure out why they ended up in there then and fix it. Probably tomorrow 😄

**Comment by Bakual** [comment]
Closing since we have a PR: #16722
