### ISSUE TITLE
There is no custom field button on Tinymce editor

### ISSUE THREAD

**Issue by ketihar** [joomla/joomla-cms#16707]
### Steps to reproduce the issue
Update from joomla 3.6.4  to joomla 3.7.2
"Content - Fields" and "Button - Field" plugins are checked and turned on
Go to article with administrator rights and try to insert a field with custom field button

### Expected result
There is a custom field button

### Actual result
There is no custom field button

### System information (as much as possible)
PHP Built On	Linux  3.13.0-79-generic #123-Ubuntu SMP  UTC 2016 x86_64
Database Version	5.5.55-0ubuntu0.14.04.1-log
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.20
Web Server	Apache/2.4.25 (Unix) OpenSSL/1.0.1f
WebServer to PHP Interface	fpm-fcgi
Joomla! Version	Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments
I have the same exactly behavior on all my sites, 12 joomla 3.7.2 sites.

**Comment by franz-wohlkoenig** [comment]
Can't confirm on 3.7.2 and 3.7.3-dev.

**Comment by franz-wohlkoenig** [comment]
Sorry for closing, unexpected select by User;-)

**Comment by ketihar** [comment]
Very weird, because on my local clean install of joomla 3.7.2 i have no issues<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16707">issues.joomla.org/tracker/joomla-cms/16707</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
as your second issue #16708 looks similar not as Core Issue have you asked help on the [forums](https://forum.joomla.org/)?

**Comment by ketihar** [comment]
Try to update  joomla 3.6.4 site to joomla 3.7.2 and you will get both those issues i post. If you try it on clean joomla 3.7.2 everything is fine.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16707">issues.joomla.org/tracker/joomla-cms/16707</a>.</sub>

**Comment by wojsmol** [comment]
@ketihar How did you update?

**Comment by ketihar** [comment]
With joomla update component<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16707">issues.joomla.org/tracker/joomla-cms/16707</a>.</sub>

**Comment by Bakual** [comment]
Do you have a custom field created? If I remeber right, the button will only show up if there is a field which could be selected. If there is none, then the button doesn't show up (because it is useless).

**Comment by ketihar** [comment]
Yes this is correct. I don't know how i miss that...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16707">issues.joomla.org/tracker/joomla-cms/16707</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
closed as no Core Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16707">issues.joomla.org/tracker/joomla-cms/16707</a>.</sub>
