### ISSUE TITLE
Custom field "list of images" doesn't show directories properly

### ISSUE THREAD

**Issue by ketihar** [joomla/joomla-cms#16708]
### Steps to reproduce the issue
Update from joomla 3.6.4  to joomla 3.7.2
Create a custom field with type "list of images"
Change the directory path of images

### Expected result
I can view all my folders on images folder

### Actual result
I don't see my folder structure,i only get 1 folder

### System information (as much as possible)
PHP Built On	Linux Charis-Hosting 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64
Database Version	5.5.55-0ubuntu0.14.04.1-log
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.20
Web Server	Apache/2.4.25 (Unix) OpenSSL/1.0.1f
WebServer to PHP Interface	fpm-fcgi
Joomla! Version	Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments
This is very weird issue because i can see only 1 folder with subfolder and no other folder inside my images folder.

**Comment by ketihar** [comment]
![screen shot 2017-06-15 at 14 18 19](https://issues.joomla.org/uploads/1/c96bdf3b7ec6d0ab554b374b32e22c37.jpeg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16708">issues.joomla.org/tracker/joomla-cms/16708</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Can't confirm:
![bildschirmfoto 2017-06-15 um 16 19 39](https://user-images.githubusercontent.com/8235763/27185723-83994716-51e6-11e7-870d-9770b4cbf350.jpg)
### System information
3.7.2, 3.7.3-dev (latest nightly build)
Multilanguage Site
macOS Sierra, 10.12.5
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by ketihar** [comment]
Have you try this on linux ubuntu server because i only get this on my linux server and not on my local system? I see that you test it on different server setup.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16708">issues.joomla.org/tracker/joomla-cms/16708</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Tested on given Setup.

As written in #16707 looks like you better ask for help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding.

**Comment by ketihar** [comment]
I know exactly what this repository concerns is, and that is why i try to help the community about a issue. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16708">issues.joomla.org/tracker/joomla-cms/16708</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Fine about this and thanks for trying to Help.

**Comment by ketihar** [comment]
Try to update on joomla 3.6.4 site to joomla 3.7.2 and you will get both those issues i post. If you try it on clean joomla 3.7.2 everything is fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16708">issues.joomla.org/tracker/joomla-cms/16708</a>.</sub>

**Comment by ketihar** [comment]
![screen shot 2017-06-16 at 09 15 17](https://issues.joomla.org/uploads/1/ed7f9f2f9775eff8ce6c9c197f1536c5.gif)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16708">issues.joomla.org/tracker/joomla-cms/16708</a>.</sub>

**Comment by ketihar** [comment]
The problem was a folder with name "images" inside my administrator folder, that was created from one plugin. You can test it easy by creating one folder with name "images" inside joomla administrator folder. You will see then that on "list of images" field if you try to change folder you will see one empty folder.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16708">issues.joomla.org/tracker/joomla-cms/16708</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
closed as no Core Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16708">issues.joomla.org/tracker/joomla-cms/16708</a>.</sub>

**Comment by brianteeman** [comment]
This should be reopened as it is a bug if the presence of a folder as described causes this issue

**Comment by franz-wohlkoenig** [comment]
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16708">issues.joomla.org/tracker/joomla-cms/16708</a>.</sub>

**Comment by Quy** [comment]
Close as having PR #17125?

**Comment by ghost** [comment]
closed as having Pull Request #17125

Thanks for Hint @Quy
