### ISSUE TITLE
[3.7.3] - Menuitem - Field for selecting article is gone

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#16719]
### Steps to reproduce the issue
I installed the nightly build / patch 3.7.2 to 3.7.3 on a site and the Homepage throws a 404.
I wanted to investigate where the error comes from and tried to switch from "featured articles" to single article. But the article selection is gone.

![image](https://user-images.githubusercontent.com/828371/27220073-24f53b9a-5284-11e7-8941-739e39463163.png)

**Comment by bertmert** [comment]
Confirmed.
Another similiar find. If you switch from "Single Article" to "Featured Articles" the field for selecting an article doesn't hide. One have to save the menu item to get rid of it.

**Comment by infograf768** [comment]
Confirmed

**Comment by infograf768** [comment]
Same issue for Contact

**Comment by Bakual** [comment]
I think #16486 is the culprit

**Comment by zero-24** [comment]
Confirmed after reverting #16486 it is working. @tonypartridge can you take a look here?

**Comment by tonypartridge** [comment]
Ok I think know why it will be happening. Will take a look on Monday and send another PR

**Comment by zero-24** [comment]
Thanks!

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16735<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16719">issues.joomla.org/tracker/joomla-cms/16719</a>.</sub>

**Comment by tonypartridge** [comment]
They fixed it by putting the other bug back in. So I'll let someone else fix it.

**Comment by zero-24** [comment]
I'm reopen here as the proposed patch is not a patch it just reverts the other PR. Lets give tony the time he need to propose a / the better patch.

**Comment by Bakual** [comment]
@tonypartridge As I wrote in that PR it is meant as a last resort in case you can't fix it. Then we have to revert and bring the original bug back in (which isn't as critical as the one introduced)

**Comment by franz-wohlkoenig** [comment]
closed in favor of #16783<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16719">issues.joomla.org/tracker/joomla-cms/16719</a>.</sub>
