### ISSUE TITLE
[4.0] Migration to FW Filesystem Package

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#16731]
With https://github.com/joomla/joomla-cms/pull/14157 the Framework's Filesystem package will be brought into the CMS as a dependency of the Archive package.  We should now work on a migration plan for the CMS filesystem classes to make use of the Framework's package.

This one is a bit more tricky than the other package conversions as the FTP layer support was removed at the Framework level and the Framework doesn't have a `JFactory` so dealing with the internal streams support is a bit harder as well.

**Comment by laoneo** [comment]
Do we still want/have to support FTP in the filesystem package? Or is it a leftover from times where hosts were messing around with file permissions problems?

**Comment by brianteeman** [comment]
There are still bad hosts (sadly) so we should keep the ftp functionality

**Comment by brianteeman** [comment]
I changed my opinion - any host still requiring ftp is probably going to be broken in lots of other ways

**Comment by mbabker** [comment]
Another architecture change I don't see getting actioned.
