### ISSUE TITLE
JFormField Calendar: when todaybutton= false, no clear button is rendered

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#16739]
see: https://github.com/joomla/joomla-cms/pull/16730
**
Reproduce the issue**
Take any calendar field, for example administrator/com_content/models/forms/article.xml
Modify the field "publish_up" like this, i.e. add the attribute todaybutton="false" 

	<field
		id="publish_up"
		name="publish_up"
		type="calendar"
		label="JGLOBAL_FIELD_PUBLISH_UP_LABEL"
		description="JGLOBAL_FIELD_PUBLISH_UP_DESC"
		class="inputbox"
		translateformat="true"
		showtime="true"
		size="22"
		filter="user_utc"
		todaybutton="false"
	/>

Open an article for editing and go to the publishing tab.
The calendar has no todaybutton, but the clear button has gone with the today button.
So the user cannot change a selection in the calendar. 

Additional Information:
This behaviour is coded in calendar.js, but seems somehow awkward.

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.

**Comment by Bakual** [comment]
@dgt41 I guess for you 😄

**Comment by richard67** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16739">issues.joomla.org/tracker/joomla-cms/16739</a>.</sub>

**Comment by richard67** [comment]
Corrected typo in title<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16739">issues.joomla.org/tracker/joomla-cms/16739</a>.</sub>

**Comment by Quy** [comment]
Fixed in #16794

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16794 

Thanks for Hint @Quy <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16739">issues.joomla.org/tracker/joomla-cms/16739</a>.</sub>
