### ISSUE TITLE
Menu: Item: I have received a message while deleting a menu (Empty Trash)

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#16734]
![screen shot 2017-06-17 at 10 46 13](https://issues.joomla.org/uploads/1/72c6b4bd48079f99faf9b4ffec50bf8d.png)Hi, I have no idea about the bug, but, there is a message with the language constant, So, You guys can find a route cause.

Condition- I had 2 menu pointing to same article, one of them were unpublished.
So, the published one, I have trashed first (It worked, no issue)
I went to trash list, I have clicked on 'Empty Trash'

And received a weird message (Refer screenshot)

**Comment by franz-wohlkoenig** [comment]
can you please give System informations (as much as possible)?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16734">issues.joomla.org/tracker/joomla-cms/16734</a>.</sub>

**Comment by aasimali** [comment]
@franz-wohlkoenig 
Joomla version: 3.7.2

The issue is, I could not reproduce it back, the scenario is difficult to create. Is it not possible to get some insight with the string that we're getting along with the error.

Thank you

**Comment by Bakual** [comment]
The string `idx_client_id_parent_id_alias_language` isn't a language key, it's the name of an index in the database table #__menu.
But I don't understand why you get such an error after **deleting** an entry. I would expect such an error when adding or editing an item (when you try to save a duplicate menuitem (same client, parent, alias and language), but not on delete.

**Comment by bertmert** [comment]
@aasimali 
Could you please post the exact aliases (about-...) of both menu items as text.

In phpMyAdmin go into table #___menu click tabulator structure. Below table you'll see a small link "Indexes" and compare with image below

![18-06-_2017_18-55-03](https://user-images.githubusercontent.com/11038612/27262475-ece139e0-5457-11e7-9f61-1944e5a62061.jpg)

**Comment by aasimali** [comment]
@bertmert The issue that I encountered was on my production server and I have no rights to edit the database table, also, I have just encountered once.

@bakual - You could be right here, because, I was also adding the new menus in parallel in the other tab,
Let me explain you further each and every step that I made.
2 tabs was opened
-In tab 1, I was first deleting the menu
-In tab 2, I was adding the same menu with some modification.

I deleted 10 menus and added 10 new menus, I encountered the issue, when I was deleting and adding menu number 5. 

Thank you for quick response.

**Comment by Bakual** [comment]
Then it may be that you inserted number 5 before it was finished deleting, or there was another item there which conflicted. I can only assume something like that.
Not sure why this error isn't catched beforem but without it being reproducable it's a bit hard to figure out what may be the cause.

**Comment by aasimali** [comment]
@Bakual - Yes, It's really hard to to reproduce, I tried twice to reproduce it at the staging server, but, was not lucky. It sounds like a glitch to me.

Thank you.

**Comment by franz-wohlkoenig** [comment]
@aasimali can you please close this Issue and reopen if there are new Infos?

**Comment by aasimali** [comment]
# closed
