### ISSUE TITLE
[com_fields] Fields are not copied when batch duplicating an article

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#16740]
### Steps to reproduce the issue
Duplicate an article with custom fields

### Expected result
Data entered in custom fields is copied too

### Actual result
All fields are empty

### System information (as much as possible)
Joomla 3.7.2

**Comment by franz-wohlkoenig** [comment]
Can't confirm. 

Copy of Article using Custom Field Txpe "Text": Data in Custom Field is saved in copied Article.
### System information
3.7.3-dev (latest nightly build)
Multilanguage Site
macOS Sierra, 10.12.5
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by coolcat-creations** [comment]
@franz-wohlkoenig how did you copy? 
I copied with batch option into another category and changed the language.

**Comment by coolcat-creations** [comment]
I just wanted to test in 3.7.3 beta but the custom field is not show if not assigned to a Field Group. Another Bug?

**Comment by coolcat-creations** [comment]
Can reproduce in 3.7.3beta:
1) Create german item with filled textfield. 
2) Save and close
3) check the checkbox in front of the item
4) Batch copy to another category and another language
5) Customfield is empty

**Comment by franz-wohlkoenig** [comment]
Issue confirmed if using "Batch"-Function.

@coolcat-creations can you please change the Title and Description that Issue is about Batch-Function?

> custom field is not show if not assigned to a Field Group

known Bug, as far i remember solved per PR.

**Comment by franz-wohlkoenig** [comment]
thanks for Update Title, @coolcat-creations Issue is also if using Batch (and not change language).

**Comment by brianteeman** [comment]
Closed as there is a pr
