### ISSUE TITLE
Please remove annoying unnecessary features in Joomla Contact form

### ISSUE THREAD

**Issue by uzielweb** [joomla/joomla-cms#16759]
> If you are submitting an issue for the Joomla! CMS, please submit it at https://github.com/joomla/joomla-cms/issues/new instead.  You may remove this line from the issue template.

#### Steps to reproduce the issue
the default_form.php have this unnecessary code in the line 25:
	
`   <?php if (isset($fieldset->label) && ($legend = trim(JText::_($fieldset->label))) !== '') : ?> 
          <legend><?php echo $legend; ?></legend>
    <?php endif; ?>`

#### Expected result
Legends title "Send a Form" is annoying and unnecessary (since Joomla 1.0)

#### Steps to reproduce the issue
in default.php have this unnecessary code in the line 113:

` <?php elseif ($presentation_style === 'plain') : ?>
    <?php echo '<h3>' . JText::_('COM_CONTACT_EMAIL_FORM') . '</h3>'; ?>`

#### Expected result
this h3 title in plain form  is annoying and unnecessary (since Joomla 1.0)

**Comment by franz-wohlkoenig** [comment]
Thanks for Request. I guess a Language Override isn't a Solution?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16759">issues.joomla.org/tracker/joomla-cms/16759</a>.</sub>

**Comment by uzielweb** [comment]
Yes. I am using this solution.
If the case is to maintain this feature  I suggest to add a option to show/hide in the xml forms.

**Comment by Bakual** [comment]
The `<legend>` is fine imho. If you don't like it, there are two possible solutions beside creating an override.
* Language string override: Create an override for COM_CONTACT_CONTACT_DEFAULT_LABEL and assign an empty value to it. The legend will no longer show.
* CSS: 
````
#contact-form legend {
    display: none;
}
````

As for the `<h3>`, we could add a CSS class to it, so it can be targetted with CSS and hidden if someones wants to. But removing it is imho wrong.

**Comment by brianteeman** [comment]
This is a matter of opinion and as it can be addressed in a template override I am closing this
