### ISSUE TITLE
showon="show_label:1" should respect the parents too

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#16750]
### Steps to reproduce the issue
Create some fields using Show on Label e.g. the attached file.
If imageHTML = Image then it provides 3 image options.  Media manager, file upload, or type in a url.
When one of them is selected it provides the relevant field.  
If imageHTML = HTML then it shows different options.  HOWEVER, the image option is still selected even though the users cannot see it.  So the field that arrives e.g. the media manager button remains even though those options are deselected.

### Actual result
If option is hidden then show on should be hidden too as it bares no relevance and is a usability issue.

### System information (as much as possible)

[systeminfo-2017-06-18T08-13-34-05-00.txt](https://issues.joomla.org/uploads/1/1e9415a1d83683104bba39b76d78a35b.txt)

### Additional comments

[exampleXML.txt](https://issues.joomla.org/uploads/1/4decdd93938861efd7e98e89729ff901.txt)

**Comment by brianteeman** [comment]
sorry I have applied your xml and read and reread your instructions and i still dont have a clue what you mean

**Comment by brianteeman** [comment]
correction I have worked it out and it is absolutely possible if you have the correct xml

you should have 
					`showon="imageHTML:1[AND]local:1"`

See 
![showon](https://user-images.githubusercontent.com/1296369/27275326-c70ac3c2-54ce-11e7-8d01-8c8455199061.gif)


I am closing this but if I have misunderstood you then it can be reopened

**Comment by uglyeoin** [comment]
Thanks, I'll update the docs :)

**Comment by uglyeoin** [comment]
Thanks a million, sorry it is in the docs at the bottom I just didn't get that far down.  Many thanks for taking the time to help.
