### ISSUE TITLE
[4.0] Dropdown for "Save" button is broken

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#16763]
### Steps to reproduce the issue
Create or edit an article

### Expected result
Working dropdown for "Save" button

### Actual result
![image](https://user-images.githubusercontent.com/1018684/27275098-4691c3f0-54d6-11e7-8b46-4c1fceaf5fbe.png)

**Comment by Bakual** [comment]
@ciar4n Any clue?

**Comment by ciar4n** [comment]
Strangely I can't replicate. Checked Chrome, FF, Edge and IE11. On what browser are you seeing this?

**Comment by brianteeman** [comment]
I have exactly the same after downloading and installing the nightly build

**Comment by ciar4n** [comment]
Yes I see it now. Appears to be caused by #16749

@C-Lodder ?

**Comment by C-Lodder** [comment]
Will fix in a bit

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/16779

**Comment by brianteeman** [comment]
closed as we have a pr
