### ISSUE TITLE
[4.0] JS error in modal-associations.js:11

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#16766]
### Steps to reproduce the issue
Edit an article in the association component

### Expected result
No errors in console

### Actual result
![image](https://user-images.githubusercontent.com/1018684/27277624-1e99350a-54df-11e7-82d0-e7717a6ce6a4.png)
Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at modal-associations.js:11
    at modal-associations.js:25

### System information (as much as possible)
Using Chrome

**Comment by dgt41** [comment]
@Bakual I guess a simple change to
```js
(function( Joomla, window) {
...
)(Joomla, window);
```

will fix that.

**Comment by Bakual** [comment]
Can you do a PR? I don't understand what you mean.

**Comment by dgt41** [comment]
Sure, although I have some more urgent things to do first.

What I meant is https://github.com/joomla/joomla-cms/blob/4.0-dev/media/com_associations/js/modal-associations.js#L25
needs to be 
```js
})(Joomla, window);
```
and the first line changed to `(function( Joomla, window) {`

**Comment by Bakual** [comment]
Ah, now it's clear to me. Thanks.
I can do the PR now :+1:

**Comment by Bakual** [comment]
PR https://github.com/joomla/joomla-cms/pull/16772
