### ISSUE TITLE
Tinymce editor not listing menus correctly

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#16778]
### Steps to reproduce the issue
In an Article create/edit screen click the 'Menu' icon in the Tinymce toolbar

### Expected result
Menu item Type 'Alias' should be in the list
Menu item Type 'External url' should be in the list

### Actual result
Menu item Type 'Alias' isn't in the list
Menu item Type 'External url' isn't in the list

### Additional comments

Surely all the menu items should be listed ?

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.

@Bakual do you know if this expected Behaviour?

**Comment by dgt41** [comment]
> Menu item Type 'External url' should be in the list

Nope, that should not be there IMHO. 
Let me elaborate here: Menu XTD Button was created as a way to expose **internal** links. The external URL, although a legit menu, is not representing an internal page and thus it shouldn't be in the list of menus (you can directly insert the link through another tinyMCE button).

**Comment by Webdongle** [comment]
> The external URL, although a legit menu, is not representing an internal page and thus it shouldn't be in the list of menus (you can directly insert the link through another tinyMCE button).

If being able to "directly insert" a link via another Tinymce button excludes that type of menu item ... then the same criterion excludes all menu items to Articles.  There is another Tinymce button for inserting direct links to Articles.

**Comment by Bakual** [comment]
Looks like it is at least intentionally not shown for the modal: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/views/items/tmpl/modal.php#L89-L90

If you want to propose a change, you likely have to adjust that list there.

**Comment by infograf768** [comment]
There was a good reason for not including alias, separator and url menu items in the possible list displayed by the modal. (container was added later).
The modal is used to select a redirection in many places and these redirections have to be internal.
Criterion for articles are quite different: one can indeed insert a link to an article via the Articles button and, if desired, through an existing menu item. Both are internal.

If one want to insert a link to an external site using TinyMCE, one has to use the Link button.
