### ISSUE TITLE
Router incorrectly tries to "fix" Itemid

### ISSUE THREAD

**Issue by weeblr** [joomla/joomla-cms#16774]
### Steps to reproduce the issue

- install stock joomla 3.7.2, with learning Joomla sample data

- Create view=featured menu item (Featured-A), showing category "Content modules" (Itemid=471)
- Create another view=featured menu item (Featured B), showing category "Display modules" (Itemid = 472 )

- In an article from category "Content modules" (ie displayed with Itemid 471), create 2 links:

index.php?option=com_content&view=featured&Itemid=471  (Featured A, Content Modules)
and
index.php?option=com_content&view=featured&Itemid=472  (Featured B, Display Modules)

- In an article from category "Display modules" (ie displayed with Itemid 472), create the same 2 links:

index.php?option=com_content&view=featured&Itemid=471
and
index.php?option=com_content&view=featured&Itemid=472

- set both articles to "Featured", so that they are displayed on their respective Featured view, and visit those 2 pages, Featured A and Featured B

### Expected result

In all cases, links go to the "Content modules" and the "Display modules" featured views, respectively.

### Actual result

On the Featured A view, the first link goes to home page, the second link is correct and goes to "Display modules"
On the Featured B view, it's the opposite, the first link is correct, the second link goes to home page.

What's happening is that when the link Itemid is the same as the current page Itemid, the router tries to "fix" the Itemid, by searching a more suitable one, but because the standard Joomla install home page is also a featured view, it uses the home page Itemid (which is first in the list of menu items) instead of leaving the it alone.

**Comment by franz-wohlkoenig** [comment]
Router > 3.8 > Lead @mbabker

**Comment by weeblr** [comment]
Hi

Just verified that the same issue still appears on Joomla 3.7.4.

Rdgs

**Comment by ghost** [comment]
@weeblr can you please test 3.8 on this Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16774">issues.joomla.org/tracker/joomla-cms/16774</a>.</sub>

**Comment by weeblr** [comment]
Hi

I tested this with j38 beta 3 and can make the following comments:

## Without the patch from #17562 

* With stable routing, the problem is still there
* Using the experimental router, the behavior is the same, but the URLs are different: they all get "?view=featured appended" as in:
/?view=featured and  content-modules?view=featured
or
/content-modules?view=featured and /?view=featured
so basically same issue as with stable routing

## With the patch from #17652 

* With stable routing, the problem is fixed and both URLs are correct on both pages
* With experimental routing the base URLs are fixed as well, but they still both get a ?view=featured query string appended

Rgds

**Comment by csthomas** [comment]
Try to test #17746.

**Comment by ghost** [comment]
closed as having Pull Request #17746 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16774">issues.joomla.org/tracker/joomla-cms/16774</a>.</sub>
