### ISSUE TITLE
Script jquery errors - Close/Save Module in backend with a lot of joomla menu

### ISSUE THREAD

**Issue by toto13009** [joomla/joomla-cms#16781]
### Steps to reproduce the issue

Inside fresh joomla install, Create some thousand joomla categories each linked to joomla menus

I added around 5.000 categories and also 5.000 linked menu 

### Expected result

In backend, I have to manage all modules as expected.

### Actual result

In frontend all works as expected.

In backend, when I am setting modules and I am clicking on "save", "save & close" or "close" all slowing down and I am getting some script error messages:

```
Warning: Unresponsive script
A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: https://mywebsite.com/media/jui/…497c6cdb76826645bd75a73960cdc8:2
```

I have to click on debug script (with firefox) and I am getting this:

```
-Empty string passed to getElementById().                            (159)  jquery.min.js:2:25285
-ReferenceError: reference to undefined property "donotValidate"[Learn More]        html5fallback.js:1:767
```

### System information (as much as possible)

PHP Built On	Linux green.o2switch.net 2.6.32-673.26.1.lve1.4.24.el6.x86_64 #1 SMP Wed Mar 29 17:09:57 EDT 2017 x86_64
Database Version	10.0.31-MariaDB
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.20
Web Server	Apache
WebServer to PHP Interface	litespeed
Joomla! Version	Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36

### Additional comments

I need help 💃

**Comment by brianteeman** [comment]
What is the value of max_input_vars in php

**Comment by toto13009** [comment]
max_execution_time	0
max_input_time	360
max_input_vars	200000
memory_limit	512M
open_basedir	no value
output_buffering	4096
post_max_size	16M
upload_max_filesize	16M

**Comment by dgt41** [comment]
@toto13009 can you add this
```php
unset($this->_scripts['media/system/js/html5fallback.js']);
```
just before https://github.com/joomla/joomla-cms/blob/staging/administrator/templates/isis/index.php#L168

Does that solve the problem?

**Comment by toto13009** [comment]
@dgt41 unfortunately not

**Comment by dgt41** [comment]
@toto13009 what is the error in this case?

**Comment by toto13009** [comment]
```
Warning: Unresponsive script
A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: https://groweek.com/media/jui/…497c6cdb76826645bd75a73960cdc8:4
```

and

-Empty string passed to getElementById().                            (22)  jquery.min.js:2:24932
-Empty string passed to getElementById().                            (154)  jquery.min.js:2:25285
-ReferenceError: reference to undefined property "donotValidate"[Learn More]        html5fallback.js:1:767

**Comment by toto13009** [comment]
For your information, in frontend I am able to edit, close, save, save & close a module without any trouble.

**Comment by dgt41** [comment]
@toto13009 ` html5fallback.js` still loaded and it shouldn't be if you used the code above...

**Comment by toto13009** [comment]
Cache browser is empty, all cache and tmp in my website are empty

I did your recommandation for testing and this is what I have got.

**Comment by toto13009** [comment]
I did it on 2 websites: My development website and my fresh install (to see if this issue was from thousands menu and categories).

Same results... unfortunately

**Comment by Quy** [comment]
@toto13009 Could this be related to #18982?

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 28th February 2018.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16781">issues.joomla.org/tracker/joomla-cms/16781</a>.</sub>
