### ISSUE TITLE
404 Category not found when article added in backend after upgrade to Joomla! 3.7.2

### ISSUE THREAD

**Issue by kortex123** [joomla/joomla-cms#16786]
### Steps to reproduce the issue
1. Login to Joomla! 3.7.2 backend. 
2. Add new article.
3. Save article or save and close article.

### Expected result
Remain on the article edit page with the link modified to: ...**edit&id=article_id** or open the article list page.

### Actual result
Front end 404 Category not found Error and the link is: **edit&id=0**
Article got saved and published if open a new window with Joomla! admin backend or website frontend.![screen shot 2017-06-20 at 07 15 03](https://issues.joomla.org/uploads/1/9099995f9ae7643886f17b32c4769fcd.jpeg)

### System information (as much as possible)

PHP Built On	Linux ____________________________ #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64
Versiune baza de date	5.5.5-10.1.24-MariaDB
Database Collation	utf8mb4_unicode_ci
Colaționare conexiune Bază de date	utf8mb4_unicode_ci
Versiune PHP	7.0.20
Server web	Apache
Interfață PHP la server-ul web	fpm-fcgi
Versiune Joomla!	Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Versiune platformă Joomla!	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Agent utilizator	Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36

Setare	Valoare
 
Safe Mode	Oprit
Deshide basedir	Nimic
Erori de afișare	Oprit
Open Tags scurte	Pornit
Urcări fișiere	Pornit
Magic Quotes	Oprit
Register Globals	Oprit
Output Buffering	Oprit
Cale de salvare sesiune	/var/cpanel/php/sessions/ea-php70
Auto Start sesiune	0
XML activat	Da
Zlib Activat	Da
ZIP nativ activat	Da
Funcții dezactivate	exec,passthru,shell_exec,system
Șir Multibyte (mbstring) Activat	Da
Iconv disponibil	Nu
Mcrypt Activat	Da
Maxim Variabile input	10000

### Additional comments
The problem is not always present but it's annoying

**Comment by franz-wohlkoenig** [comment]
Can't confirm Issue.
### System information
3.7.3-dev (latest nightly build)
Multilanguage Site
macOS Sierra, 10.12.5
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by franz-wohlkoenig** [comment]
Have you asked help on the [forums](https://forum.joomla.org/)? This repository concerns Joomla coding.

**Comment by kortex123** [comment]
I've opened a topic about this issue. Hope someone experienced the same problem and fixed it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16786">issues.joomla.org/tracker/joomla-cms/16786</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@kortex123 thanks for opening a Issue at Forums, please close this Issue.
