### ISSUE TITLE
[4.0] System information error

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#16789]
### Steps to reproduce the issue
1. Install latest 4.0-dev
2. Access to System -> System Information

### Expected result
Works well

### Actual result
0 - An error has occurred.

Call to undefined method Joomla\Database\Mysqli\MysqliDriver::getConnectionCollation()

### System information (as much as possible)

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.

**Comment by mbabker** [comment]
@wilsonge One for the database package.

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16790<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16789">issues.joomla.org/tracker/joomla-cms/16789</a>.</sub>

**Comment by wilsonge** [comment]
Reopening as the PR needs to be against the framework

**Comment by alikon** [comment]
it wasn't ported yesterday ??

**Comment by wilsonge** [comment]
Nope - but it wasn't broken yesterday :P

**Comment by joomdonation** [comment]
Yes. The issue is now fixed, thanks.
