### ISSUE TITLE
[com_fields] J3.7.x Custom Field Group Class Wrapper

### ISSUE THREAD

**Issue by vkengo** [joomla/joomla-cms#16802]
### Steps to reproduce the issue.

I have two groups of custom fields on the same page and would like wrap and style each Group.  
Formatting a group of custom fields, requires a wrapper as identifier - a class to target.

### Expected result
Need to have a 'Render Class' for a Field group

### Actual result
Nothing on fields groups on individual field

### System information (as much as possible)

Joomla 3.7.2
PHP 7+
Apache

**Comment by jayblaq** [comment]
You can use CSS to do that and :nth-child selectors.

**Comment by vkengo** [comment]
Thanks for the response, though I have to use this option for now, it may not be practical to a client if they add a new field group or move them around. I have a set pre-defined class that they use in modules and that would be idle to have the same option in fields groups.

**Comment by Quy** [comment]
Duplicate #16231

**Comment by franz-wohlkoenig** [comment]
closed as duplicate Report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16802">issues.joomla.org/tracker/joomla-cms/16802</a>.</sub>
