### ISSUE TITLE
[4.0] Installation process shows error

### ISSUE THREAD

**Issue by jjaracz** [joomla/joomla-cms#16807]
### Steps to reproduce the issue

Just fallow the installation process and when you will see the progress bar then should show error.

### Expected result

Joomla will install without errors.

### Actual result

Joomla shows an error
![screenshot_20170622_092705](https://user-images.githubusercontent.com/8504663/27426910-67e855d2-573d-11e7-9a2a-d97795f8fd9c.png)

### System information (as much as possible)

Mysql: 5.7
PHP: 7.0

**Comment by brianteeman** [comment]
This is the same issue as already reported for mysql 5,7

The fix really must be merged as a priority

**Comment by wojsmol** [comment]
Previous issue mentionet by @brianteeman is  https://github.com/joomla/joomla-cms/issues/16788

**Comment by jjaracz** [comment]
Okay, so i close this issue :)

**Comment by angre** [comment]
Unsuscribe ___________Oooo._________
 Oui aux LL  (      )     Wilfried
     .oooO        )    /       Nguessan
      (      )       (__/+22508655362
       \    ( Un pas à la Liberté
         \__)  Intégrateur S.Web

 

    Le Jeudi 22 juin 2017 9h37, Brian Teeman <notifications@github.com> a écrit :
 

 This is the same issue as already reported for mysql 5,7The fix really must be merged as a priority—
