### ISSUE TITLE
Checkboxes form field disables all options after first disabled option

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#16809]
### Steps to reproduce the issue

Create custom field extended from `JFormFieldCheckboxes` and add multiple options with disabled option in the middle of options.

Or test with XML:

```
<field name="test" type="checkboxes">
	<option value="1">1</option>
	<option value="2" disabled="true">2</option>
	<option value="3">3</option>
</field>
```
### Expected result
Only 2nd checkbox is disabled.

### Actual result
2nd and 3rd checkboxes are disabled.

### System information (as much as possible)

As usual.

### Additional comments

`/layout/joomla/form/field/checkboxes.php`:

The idea is to not use previous/field-specific 'disabled'  attribute if there are more than 1 option.

**Comment by brianteeman** [comment]
@Denitz you dont need to create an issue if you are going to immediately create a pull request

Please update #16811 with the description from your post here
