### ISSUE TITLE
Unable to display VisForm data

### ISSUE THREAD

**Issue by ranjitmane88** [joomla/joomla-cms#16819]
__### Steps to reproduce the issue
I have created VisForm and inserted data from front end.

Then I have created new menu to display this form details. But unable to view the details.

### Expected result

Form data should get displayed on form.

### Actual result

No data displayed

### System information (as much as possible)

Jooomla 3.7, PHP 7, mysql

**Comment by brianteeman** [comment]
Please use the forum for support with extensions
