### ISSUE TITLE
COM_CONTENT_BASIC_FIELDSET_LABEL

### ISSUE THREAD

**Issue by LeslieInfographie** [joomla/joomla-cms#16828]
![COM_CONTENT_BASIC_FIELDSET_LABEL](https://scontent-cdt1-1.xx.fbcdn.net/v/t1.0-9/19399693_10213571427744430_3614171466571870764_n.jpg?oh=0c29a95b51610f0de026dafbdd57c2cb&oe=59DFB7D8 "")

when editing an article in frontend, there is a tab called "COM_CONTENT_BASIC_FIELDSET_LABEL" that is not translated. This tab is also empty

**Comment by franz-wohlkoenig** [comment]
Can't confirm.
### System information
3.7.3-dev (latest nightly build)
Multilanguage Site
macOS Sierra, 10.12.5
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by infograf768** [comment]
@LeslieInfographie 
Which version of Joomla are you using and which version of the French Language pack?

**Comment by infograf768** [comment]
And which template?
Please test with Protostar default template as it could be due to your template override.

**Comment by franz-wohlkoenig** [comment]
@infograf768 haven't found Constant `COM_CONTENT_BASIC_FIELDSET_LABEL ` in Site or Admin.

**Comment by infograf768** [comment]
I know, this is why I guess it is present in a 3pd template override, maybe as a complex constant.

**Comment by LeslieInfographie** [comment]
Joomla! 3.7.2
French : 3.7.2.1

**Comment by infograf768** [comment]
@LeslieInfographie 
Please test with the Protostar default template.

**Comment by N6REJ** [comment]
While there are many other BASIC_FIELDSET_LABEL interestingly enough there are none for com_content
![image](https://user-images.githubusercontent.com/1850089/27518637-745947da-59aa-11e7-8b2d-a2dca5351303.png)

**Comment by zero-24** [comment]
@LeslieInfographie please check your html folder (in your template) Please check if there is something com_content or layout realted and show it to us.

**Comment by brianteeman** [comment]
I am closing this as it has not been replicated and there has been no updates. It can always be reopened if updated
