### ISSUE TITLE
How to create Data entry screen?

### ISSUE THREAD

**Issue by ranjitmane88** [joomla/joomla-cms#16821]
I need to create release management application using joomla 3.7

For this, we will be creating data entry screens to insert release details.

This details will be entered by admin (release manager).

Is there any feature available to map two transaction tables of data entry screens with foreign key?

Also, how can I display the records on screen which was inserted through data entry screen?

Please let me know, how can I mitigate this requirement using Joomla CMS?

**Comment by mbabker** [comment]
Hi, this issue tracker is not a user support forum for general questions; this is for tracking bugs and feature requests in Joomla.

For user support, please use the [forums](https://forum.joomla.org) and [documentation](https://docs.joomla.org).
