### ISSUE TITLE
Inquiry - Shortcuts Removal

### ISSUE THREAD

**Issue by aahmed2016** [joomla/joomla-cms#16826]
### Expected result

Main Page Maintenance;
Please remove all the shortcuts.
Please add the following shortcuts:
Youth Development (this page is currently called “youth and sports”)
Quran Courses
Afghani Language Schools
Funeral Cover
Please modify the shortcuts icon and shape it to relate to the program.
Can you please try to program the timeline photos to slide automatically?

http://www.acsansw.com/

details on logging in can be provided but need assistance with doing this task.

Also I would like to know please of any joomla paid support services that are good without a need for support using their hostin system as I am using my own host system. 

Thanks. 

### Additional comments

my email is amira.ahmed@live.com.au for login details .

**Comment by aahmed2016** [comment]
my <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16826">issues.joomla.org/tracker/joomla-cms/16826</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding.
