### ISSUE TITLE
Users registration form do not keep values

### ISSUE THREAD

**Issue by n3t** [joomla/joomla-cms#16824]
### Steps to reproduce the issue
- Fresh Joomla installation
- enable users registration
- To be more obvious, enable profile plugin
- go to frontend to registration form
- fill the form, use the same username, as is your administrator (or any other existing user)
- submit the form

### Expected result
When displayed error on duplicate username, form should keep its values.

### Actual result
Error is displayed, form is empty.

### System information (as much as possible)
Joomla 3.7.2 fresh installation.

### Additional comments
Seems there is problem in UsersModelRegistration->getData, there is getForm call, which causes recursion back to getData. As first line sets $this->data to empty stdClass, condition will not pass and lodFormData function receives empty values, so no data are loaded to the form.

**Comment by Quy** [comment]
Unable to reproduce. Tested with Joomla! 3.7.3-rc1.

**Comment by n3t** [comment]
You are right, 3.7.3-rc1 seems to solve this, closing this issue.
