### ISSUE TITLE
[4.0] JS Error: Uncaught Error: Tooltip is transitioning

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#16839]
### Steps to reproduce the issue

Sometime i get a js error in the frontend.
I have yet no way to reproduce it 100% of the times but try this:
- Use 4.0 latest with sample data
- Go to frontend
- Press F12 to open the browser dedug console
- Mouse over around the login fields and buttons for 5 seconds - you should see a js error

### Expected result

No js error.

### Actual result

> bootstrap.min.js?0b34577…:7 Uncaught Error: Tooltip is transitioning
>    at h.hide (bootstrap.min.js?0b34577…:7)
>    at h._leave (bootstrap.min.js?0b34577…:7)
>    at HTMLSpanElement.<anonymous> (bootstrap.min.js?0b34577…:7)
>    at HTMLSpanElement.handle (jquery.min.js?0b34577…:3)
>    at HTMLSpanElement.dispatch (jquery.min.js?0b34577…:3)
>    at HTMLSpanElement.q.handle (jquery.min.js?0b34577…:3)

### System information (as much as possible)

4.0 latest

### Additional comments

seems the same issue described here https://github.com/twbs/bootstrap/issues/21607 and seems to be fixed in bootstrap 4 beta 1 so i guess updating bootstrap would solve this

@dgt41 can you check?

**Comment by dgt41** [comment]
@andrepereiradasilva it's a known bug for Bootstrap alpha. They have already fixed it upstream, so the next version (beta) should take care of it

**Comment by andrepereiradasilva** [comment]
ok them will close
