### ISSUE TITLE
[4.0] Aurora: error template is not rendered correctly

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#16834]
### Steps to reproduce the issue

- Use 4.0
- set site offline.
- go to frontend url `/index.php?option=com_blabla` to generate an error

### Expected result

Nice and clean error page.

### Actual result

![image](https://user-images.githubusercontent.com/9630530/27478113-6bd30bf0-5806-11e7-9e1e-33212477f577.png)

### System information (as much as possible)

4.0 latest

### Additional comments

None.

@ciar4n @C-Lodder can you check?

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16834">issues.joomla.org/tracker/joomla-cms/16834</a>.</sub>

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/17027

**Comment by ghost** [comment]
closed as having PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16834">issues.joomla.org/tracker/joomla-cms/16834</a>.</sub>
