### ISSUE TITLE
[4.0] Aurora/IE11: Menu toogle with text mouse cursor, shouldn't be an arrow?

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#16831]
### Steps to reproduce the issue

Small issue.
In IE11 the Aurora template menu toogle mouse over cursor is a text cursor instead of an arrow.
![image](https://user-images.githubusercontent.com/9630530/27476303-22652d82-5800-11e7-9d2a-521c23838387.png)

In a clean install with no sample data: just changed the "Main Menu" module position to "menu" (which IMHO should be by default - but that's another issue).

### Expected result

An arrow
![image](https://user-images.githubusercontent.com/9630530/27476139-745030ac-57ff-11e7-85e2-2905857f6b16.png)

### Actual result

A text cursor
![image](https://user-images.githubusercontent.com/9630530/27476810-052fad1c-5802-11e7-8d65-1f545104782e.png)

### System information (as much as possible)

Latest 4.0

### Additional comments

None

@ciar4n can you check?

**Comment by C-Lodder** [comment]
BS decided to remove `cursor: pointer` from the `.btn` classes based on the following article: https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b

**Comment by andrepereiradasilva** [comment]
ok, i see the logic behind that.

anyway in IE11 it's a 
![image](https://user-images.githubusercontent.com/9630530/27476690-9a6c68da-5801-11e7-9f0f-0d4165ced146.png)
which is a wrong.

so i will change the issue title

**Comment by andrepereiradasilva** [comment]
ok changed issue to reflect only IE11 issue - even smaller issue them 😄

**Comment by C-Lodder** [comment]
See the issue now. For the icon, we're using `fa fa-bars` which is a font, as opposed to `navbar-toggler-icon` which is a background image. Will submit a PR.

**Comment by C-Lodder** [comment]
@andrepereiradasilva code added to current PR by Ciaran: https://github.com/joomla/joomla-cms/pull/16827#pullrequestreview-45957983

Can close this.
