### ISSUE TITLE
[4.0] Atum: Atum does not have a custom error page template like isis

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#16836]
### Steps to reproduce the issue

- Use 4.0
- Login in administrator
- Go to admin url `/administrator/index.php?option=com_blabla` to generate an error

### Expected result

A custom atum error page (like isis have one).

### Actual result

The administrator system template error page.
![image](https://user-images.githubusercontent.com/9630530/27478692-a149545e-5808-11e7-8c8f-c083bb381f7d.png)

### System information (as much as possible)

4.0 latest.

### Additional comments

None

@ciar4n @C-Lodder can you check?

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16836">issues.joomla.org/tracker/joomla-cms/16836</a>.</sub>

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/16861

**Comment by franz-wohlkoenig** [comment]
closed as having PR ##16861<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16836">issues.joomla.org/tracker/joomla-cms/16836</a>.</sub>
