### ISSUE TITLE
[4.0] Aurora: offline template is not rendered correctly

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#16833]
### Steps to reproduce the issue

- Use 4.0
- set site offline.
- go to frontend

### Expected result

Nice and clean offline page.

### Actual result

![image](https://user-images.githubusercontent.com/9630530/27478006-f17c97c2-5805-11e7-8d02-c226fb511f77.png)

### System information (as much as possible)

4.0 latest

### Additional comments

None.

@ciar4n @C-Lodder can you check?

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16833">issues.joomla.org/tracker/joomla-cms/16833</a>.</sub>

**Comment by ciar4n** [comment]
Thank you @andrepereiradasilva 

PR created.. #16930

**Comment by brianteeman** [comment]
Closed as we have a pr
