### ISSUE TITLE
[4.0] Aurora: Error template offers "Search", don't work

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#16849]
### Steps to reproduce the issue
show Error Page by Url `/index.php/en/eee?`, offered "Search this site" don't work:
![screen shot 2017-06-24 at 11 12 45](https://issues.joomla.org/uploads/1/8ef573cb999ecedbe46e63ebaa7ec2ce.jpg)
### System information
4.0.0-dev
macOS Sierra, 10.12.5
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/17027

**Comment by ghost** [comment]
thanks @C-Lodder
