### ISSUE TITLE
[com_fields] Uninstalling field / Deleting Field values

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#16845]
If you uninstall a field, the field values remain in the database. This is good if you have issues with the field and try to uninstall and reinstall, but shouldn´t there be any option to delete field-data that is not used anymore?

**Comment by dgt41** [comment]
@coolcat-creations I think you an use the postflight script and remove the data manually

**Comment by coolcat-creations** [comment]
So it´s the developers responsibility, right?

**Comment by Bakual** [comment]
I think the next time you save the item that data was associated with, the values would be deleted.
The values will not show up anywhere, right? It's just the orphaned data that bugs you?
Imho it's not a big issue beside that it is filling the database a bit.

**Comment by coolcat-creations** [comment]
> It's just the orphaned data that bugs you?

Yes, i think thats not "clean" - is it?

**Comment by Bakual** [comment]
I think it would be great if the field is somehow marked in the fields manager as unavailable because the plugin is either unpublished or uninstalled. But I wouldn't delete it automatically.

If the orphaned field is deleted manually, the assigned values will be deleted as well.

**Comment by laoneo** [comment]
I think it is the responsibility of com_fields to manage that situation properly. At minimum I would expect a warning message that there are still fields of that plugin which got unpublished or uninstalled.

**Comment by brianteeman** [comment]
@laoneo I disagree - we are talking about 3pd plugins here so it is the responsibility of the plugin to clean the data just as it is with all 3pd extensions

**Comment by laoneo** [comment]
When a 3pd component is uninstalled are then not also the categories uninstalled automatically of this component?

**Comment by mbabker** [comment]
The extension installer API does that, not the components involved.  And there have been a fair number of issues opened about that behavior as well.
