### ISSUE TITLE
[4.0] Aurora: Breadcrumbs messed Layout

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#16850]
### Steps to reproduce the issue
using Sample data: `/index.php/using-joomla/extensions/templates/atomic/typography-atomic/en/`, Breadcrumbs are deep so causing:
![bildschirmfoto 2017-06-24 um 13 19 54](https://user-images.githubusercontent.com/8235763/27508175-fe63b5f8-58df-11e7-9e6c-dfc36bc8de5d.jpg)
### System information
4.0.0-dev
macOS Sierra, 10.12.5
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
I cannot replicate this at all on Chrome.

It's possible that the css-grid feature that @ciar4n added has fixed this. Could you get the latest code and see if you still have the same issue?

**Comment by ghost** [comment]
Fixed:
![bildschirmfoto 2017-07-09 um 15 22 45](https://user-images.githubusercontent.com/8235763/27994270-82dcb15a-64ba-11e7-943f-2ef8d395e5f4.jpg)
