### ISSUE TITLE
Undefined variable: hiddenFieldsets in field layout

### ISSUE THREAD

**Issue by asika32764** [joomla/joomla-cms#16854]
### Steps to reproduce the issue

Create a component and add this code to `edit` layout:

```php
<?php $this->set('show_options', 0) ?>
<?php echo JLayoutHelper::render('joomla.edit.params', $this); ?>
```

### Expected result

No error and show edit page.

### Actual result

Get this error message:

![p-2017-06-25-001](https://user-images.githubusercontent.com/1639206/27510554-c415a012-5945-11e7-97d6-c18d524856da.jpg)

### System information (as much as possible)

3.7.2

### Additional comments

I'm not sure what is the usage of this variable so I didn't create PR to fix it.

**Comment by zero-24** [comment]
PR is: https://github.com/joomla/joomla-cms/pull/16856 please test
