### ISSUE TITLE
Notice message "Only variables should be assigned by reference"

### ISSUE THREAD

**Issue by yild** [joomla/joomla-cms#16857]
### Steps to reproduce the issue

Joomla 3.7.2
Set debug level to 'maximum' in global configuration

### Actual result

Notice: Only variables should be assigned by reference in /var/www/html/plugins/system/form_xml_override/form_xml_override.php on line 15
message visible on every page.

### Expected result

No message

### System information (as much as possible)

J3.7.2
PHP 7.0.20

**Comment by brianteeman** [comment]
That message is coming from an extension you have installed and not something in the core of Joomla
