### ISSUE TITLE
Joomla! Cache does not exist

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#16862]
### Steps to reproduce the issue

If the configuration.php has the incorrect location for the Joomla! cache then Joomla! will not load, the admin has an error message "Joomla! cache does not exist", the global configuration is unsaveable with the error "joomla! cache does not exist" and the global configuration loses the "file" option for caching.  ![screen shot 2017-06-25 at 14 45 43](https://issues.joomla.org/uploads/1/2cce9bebaad34402793df2dc55735c23.png)

### Expected result

The file option remains which then allows you to see the location of the Joomla! cache which helps you to identify that it is incorrect.  It also means non-technical users can change this option in global configuration rather than using FTP.

### Actual result
As the file option disappears, so does the location of the Joomla! cache meaning it is harder to understand what is going on.  It can be resolved by editing configuration.php manually. The value you need to correct is: public $cache_path = '/home/xxxxx/cache'; 

![screen shot 2017-06-25 at 14 50 32](https://issues.joomla.org/uploads/1/080e366803f6d26ba6d178942a1455f1.png)
### System information (as much as possible)
[systeminfo-2017-06-25T09-47-40-05-00.txt](https://issues.joomla.org/uploads/1/f8f4691cbf7dcf37e8e13c28a80f3bf9.txt)

**Comment by brianteeman** [comment]
I can confirm that if you set a non-existent path for the cache then after saving that field is not presented and it cannot be edited in the ui

**Comment by alor702000** [comment]
Re : Error of the file cache storage

go to configuration.php and put:
public $cache_handler = '';

**Comment by csthomas** [comment]
This PR https://github.com/joomla/joomla-cms/pull/17671 should help in half

**Comment by csthomas** [comment]
My PR does not fix the whole issue.

It only fix "the global configuration is unsaveable"

**Comment by HLeithner** [comment]
This has been fix in Joomla 3.9.6 with PR #21952
