### ISSUE TITLE
[4.0] Patch tester: Error on Fetch Data

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#16864]
### Steps to reproduce the issue
Got:
![1](https://user-images.githubusercontent.com/8235763/27517330-06cef46e-59cb-11e7-8bad-452c35dbd896.jpg)
![2](https://user-images.githubusercontent.com/8235763/27517331-08f8ada2-59cb-11e7-96b1-4cf91692a57f.jpg)
### System information
4.0.0-dev
macOS Sierra, 10.12.5
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by andrepereiradasilva** [comment]
see https://github.com/joomla/joomla-cms/pull/16865

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16865<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16864">issues.joomla.org/tracker/joomla-cms/16864</a>.</sub>
