### ISSUE TITLE
Category

### ISSUE THREAD

**Issue by mojoAdmin** [joomla/joomla-cms#16873]
Category drop down not displaying children categories when assigned custom User Group with Registered Access Level only. Tested with Contact Enhanced (CE) and Joomla com_content components.

### Steps to reproduce the issue
1. Create a new Joomla user group. Name it something (Subscribed) and assign viewing level permissions.
2. In CE create three categories, all set to public access.
3. Choose one category to be the parent category and assign the other two as children of the parent.
4. Now change the access level for one of the children categories to :Subscriber" access (or whatever you named the user group in step 1).

### Expected result
I expected the category to maintain its parent child relationship and to remain as a parent option for other categories.

### Actual result
If your experience follow mine, the category that you assigned to the Subscriber user group is no longer a child of the parent group and it is no longer available to be assigned as a parent option in the Parent dropdown. Setting the permissions back to Public allows the category to be assigned to a parent or to become a parent.

### System information (as much as possible)
Setting	Value
-----------------
PHP Built On	Linux us505.directrouter.com 2.6.32-673.26.1.lve1.4.27.el6.x86_64 #1 SMP Sun May 7 19:22:54 EDT 2017 x86_64
Database Version	10.1.24-MariaDB
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.20
Web Server	LiteSpeed
WebServer to PHP Interface	litespeed
Joomla! Version	Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

### Additional comments
Recap: Here's the essence of my experience:  When I assigned CE categories to Joomla User Groups other than Public those categories were no longer Available under the CE drop down for assigning parent Categories and if a category had already been assigned to a Parent category, that relationship was broken. IOW - CE Categories assigned to Joomla user ground s other than Public, could no longer be assigned a parent category, nor could they be assigned as a parent category.

**Comment by franz-wohlkoenig** [comment]
If you have an issue with an 3rd-Party-Product ("Contact Enhanced") please ask Developer of this Product.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16873">issues.joomla.org/tracker/joomla-cms/16873</a>.</sub>

**Comment by kpmueller** [comment]
I have also had issues with parent categories and access in 3.7.x: #16757 - don't know if it's related. I'm definitely not using any third party products in my case
