### ISSUE TITLE
Admin page wider then browser screen size in 3.7.3-rc1

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#16871]
### Steps to reproduce the issue
go to admin screen in 3.7.3-rc1

### Expected result
body stops @ browser edges

### Actual result
body is wider then browser screen width.
![image](https://user-images.githubusercontent.com/1850089/27525600-da947466-5a04-11e7-9cee-9b24993becff.png)

### System information (as much as possible)

windows 10 x64 pro 
chrome Version 58.0.3029.110 (64-bit)
& Version 59.0.3071.109 (Official Build) (64-bit)

**Comment by coolcat-creations** [comment]
Here on Chrome for Mac i have no issues.
Also not on the component page, also not with debug on. 

Version 59.0.3071.109  (Official Build)  (64-Bit)

Did you clear your cache? What does the element inspector say what causes the issue?

**Comment by zero-24** [comment]
@N6REJ can you reproduce that in a core view too? After you have applyed the suggestions by @coolcat-creations ?

**Comment by C-Lodder** [comment]
Is it just Akeeba Backup you're having this issue with or other components?

**Comment by N6REJ** [comment]
I guess I'm dumb, it's not doing it now on either sites...
