### ISSUE TITLE
No active tab in installer in 3.7.3-RC-1

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#16870]
### Steps to reproduce the issue
install 3.7.2 update to 3.7.3-rc1 via "testing" update option.

### Expected result
Going to installer would display file upload installer

### Actual result
Blank page results..
![image](https://user-images.githubusercontent.com/1850089/27524959-64fd6ef6-59ff-11e7-8a10-b64cb2cad43f.png)

[systeminfo-2017-06-26T04-39-04+00-00.txt](https://github.com/joomla/joomla-cms/files/1101055/systeminfo-2017-06-26T04-39-04.00-00.txt)

### System information (as much as possible)
Clean install, akeeba admin + waf installed.

### Additional comments
clicking on any tab.. ( none of which are clearly indicated as tabs ) then functions.
![image](https://user-images.githubusercontent.com/1850089/27525003-b1792f18-59ff-11e7-9979-b2e04cc29899.png)
![image](https://user-images.githubusercontent.com/1850089/27525024-d059fc96-59ff-11e7-9d35-7fcbe3e9af6b.png)
 active but has no effect.

JS error present & Not sure why but it appears js is cached even though cache is NOT active..
![image](https://user-images.githubusercontent.com/1850089/27525038-0a76fbc2-5a00-11e7-89c6-da8544506c0b.png)

**Comment by zero-24** [comment]
> Clean install, akeeba admin + waf installed.

Please try a clean install and try again. I can not reproduce this on 3.7.3-dev from yesterday.

**Comment by zero-24** [comment]
![image](https://user-images.githubusercontent.com/2596554/27533914-8bceeecc-5a65-11e7-8e15-e36db0149345.png)
![image](https://user-images.githubusercontent.com/2596554/27533935-9b98cfee-5a65-11e7-85b0-0eb3ebc9af9b.png)
![image](https://user-images.githubusercontent.com/2596554/27533956-a6485eaa-5a65-11e7-98bd-1078cbf801f8.png)

**Comment by N6REJ** [comment]
@zero-24 it still needs to work in update you know?  but yeah, I'll sync and see if diff

**Comment by zero-24** [comment]
> it still needs to work in update you know? 

Sure i just want to be sure that it is nothing like cache or similiar :)

**Comment by N6REJ** [comment]
@zero-24 can confirm it works from current dev on clean install..   I'm going to chock it up to some glitch as its working
