### ISSUE TITLE
Semantic versioning violation

### ISSUE THREAD

**Issue by demis-palma** [joomla/joomla-cms#16874]
The TinyMCE editor plugin jdragdrop was in the folder
`/media/editors/tinymce/plugins/jdragdrop/`
during all the 3.5 and 3.6 series, but it has been moved to
`/media/editors/tinymce/js/plugins/dragdrop/`
in 3.7 series without notice it.

Third party extensions that instantiate the editor with a plugin list
`plugins: plugin1,plugin1,jdragdrop`
results in a 404 HTTP error while retrieving the file
`/media/editors/tinymce/plugins/jdragdrop/plugin.min.js`
and of course the plugin does not work.

The compatibility should be moved in its previous directory as soon as possible.

**Comment by brianteeman** [comment]
Then it would break BC with 3.7 according to the same criteria
