### ISSUE TITLE
[UX] Feature Request: Selecting Parent Menu Item

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#16882]
In managing the menu and contents i´m stumbling often over a missing feature in the searchtools of the menuitem manager. It would be great to select a parent menu item, just like i can select a parent menu item in com_content categories. Since i don´t know how to implement, i´m asking it here as a feature request ;)

thank you!

**Comment by tonypartridge** [comment]
Not too hard to add in. But what should be shown in the list? Single level parent, all menu items?

**Comment by tonypartridge** [comment]
This can be closed now we have a PR :-)

**Comment by ghost** [comment]
closed as having PR #17060<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16882">issues.joomla.org/tracker/joomla-cms/16882</a>.</sub>
