### ISSUE TITLE
Version 3.7.2: Modules not shown - error 500: Layout "default_batch" not found

### ISSUE THREAD

**Issue by dave0688** [joomla/joomla-cms#16883]
Hello,

after upgrading to Joomla 3.7.2 I'm facing the issue that I cannot open Modules section anymore. When I click on Extensions (german: Erweiterungen - not sure what the english term is) -> Modules in the top menu, it shows: 500: Layout "default_batch" not found

### Steps to reproduce the issue
Joomla version 3.7.2: Please click on Extensions -> Modules and the error occurs (see screenshot). What I also noticed that it occurs ONLY with the isis backend template. When I activate Hathor, everything works fine.

### Expected result
To see a list of modules

### Actual result
'500: Layout "default_batch" not found' (see screenshot)

### System information (as much as possible)
PHP 7, Managed server (1und1).![screen shot 2017-06-27 at 13 17 52](https://issues.joomla.org/uploads/1/15247c9e6de1f2a19aa216581e832eb2.png)

**Comment by zero-24** [comment]
Can you try the reinstall button in com_joomlaupdate? And than try again?

Backend -> Components -> Joomla! Update -> reinstall ?

**Comment by dave0688** [comment]
Just reinstalled the template like you mentioned. Unfotunately still the same error :/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16883">issues.joomla.org/tracker/joomla-cms/16883</a>.</sub>

**Comment by zero-24** [comment]
> Just reinstalled the template like you mentioned. 

It is not about the template ;) It is about the core files ;)

**Comment by mbabker** [comment]
There is no use of a `default_batch` layout in com_modules 3.7.2.  So either the update didn't correctly update all files on your server or there is an extension trying to use that layout.

**Comment by dave0688** [comment]
Sorry, not the template. I reinstalled the **core files** like you mentioned.
Any idea how I could track that down? Can anybody help?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16883">issues.joomla.org/tracker/joomla-cms/16883</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@dave0688 have you asked help on the [forums](https://forum.joomla.org/)?

**Comment by dave0688** [comment]
Hm, noone seems to have this issue so far... The strange thing is that I have several other Joomla pages running (same version) and there's nothing wrong with them. 
Reinstalling the core files didn't help.

Does anyone have any idea? Is there any debug mode in Joomla how I could track that issue down? 

Kind regards,
David

**Comment by tonypartridge** [comment]
Hi David,

Sounds like a plugin interacting like an old version of Advanced Module Manager maybe? Also check your isis/html/ folder for any overrides.

But this can be closed as it's not a core issue.

**Comment by ghost** [comment]
closed as stated above. Thanks for Hint, @tonypartridge <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16883">issues.joomla.org/tracker/joomla-cms/16883</a>.</sub>

**Comment by dave0688** [comment]
Wow, thanks a lot for the hint with the overrides!
I checked the admin template folder (isis) and saw that there's a html/com_modules folder which is not there in other Joomla installations.

I removed the folder and it works :))
No idea where that folder came from...

Thanks for your help!

**Comment by tonypartridge** [comment]
Your welcome! Have an awesome day.
