### ISSUE TITLE
error DateTime::__construct() for new item of any component in jalali calendar (Persian language)

### ISSUE THREAD

**Issue by ghasemy50** [joomla/joomla-cms#16884]
### Steps to reproduce the issue
go to article manager in persian language and jalali calendar
click on new button
go to publishing tab and select a date on start publishing field
then set a title for article and save it.
the date is not change to gregorian calendar before save because date not save.
on my component i have this problem with DateTime::__construct(): Error.
there is problem just in new item on any form that have calendar. on edit i haven't any problem.
thanks for answere

### Expected result
not convert jalali date to gregorian date before save new item

### Actual result
convert jalali date to gregorian before save new item.

### System information (as much as possible)
On Website:
PHP Built On 	Linux linux3.centraldnserver.com 3.10.0-614.10.2.lve1.4.50.el7.x86_64 #1 SMP Mon May 22 16:28:14 EDT 2017 x86_64
Database Version 	10.1.22-MariaDB-cll-lve
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.5.38
Web Server 	Apache
WebServer to PHP Interface 	litespeed
Joomla! Version 	Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; rv:54.0) Gecko/20100101 Firefox/54.0 

On localhost:
PHP Built On 	Windows NT DESKTOP-6J51U5V 6.2 build 9200 (Windows 8 Business Edition) i586
Database Version 	5.6.17
Database Collation 	latin1_swedish_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.5.12
Web Server 	Apache/2.4.9 (Win32) PHP/5.5.12
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; rv:54.0) Gecko/20100101 Firefox/54.0

**Comment by Quy** [comment]
Duplicate #16628

**Comment by richard67** [comment]
Please check if this is a duplicate report to #16628 . If so, then there is already a PR to solve it, #16721 , and you should test it if possible, and this issue should be closed.

If it is not a duplicate report it should remain open.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16884">issues.joomla.org/tracker/joomla-cms/16884</a>.</sub>

**Comment by ghasemy50** [comment]
hi 
yes my problem was same as it.
thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16884">issues.joomla.org/tracker/joomla-cms/16884</a>.</sub>

**Comment by richard67** [comment]
Then this issue here should be closed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16884">issues.joomla.org/tracker/joomla-cms/16884</a>.</sub>

**Comment by richard67** [comment]
Was duplicate report to #16628 . PR to solve it is #16721<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16884">issues.joomla.org/tracker/joomla-cms/16884</a>.</sub>
