### ISSUE TITLE
I can not modify categories or add items help!

### ISSUE THREAD

**Issue by pukero12** [joomla/joomla-cms#16885]
Good morning.

I have the following problem:

The super user, I have granted all the permissions and I have verified more than 100 times. But when I try to create an article or update some other element inside
Of the administrator of joomla and I can save it, the page is redirected to the base bone to the one already constructed, I explain myself better. The company in which I work already has a page made in joomla then I join joomla to modify that page, when I try to create an article and I give it save joomla redirects me to the page of the company where I work, how I could solve That problem As it does not show me any error. Thank you very much
Att: Jose Manuel Cuchimba Vargas

**Comment by brianteeman** [comment]
Please use the forum for support HTTPS://Forum.joomla.org
