### ISSUE TITLE
Calendar always saves seconds like ":00"

### ISSUE THREAD

**Issue by joomla-ua** [joomla/joomla-cms#16908]
Two bugs:

1. If select TODAY in datepicker set date and time as 2017-06-29 04:17:47 but after save replace date and time as 2017-06-29 04:17:00

2. Always save article with seconds like ":00"

Joomla 3.7.2

**Comment by Quy** [comment]
Duplicate #16084

**Comment by franz-wohlkoenig** [comment]
closed as duplicate Report.

Thanks for Hint, @Quy <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16908">issues.joomla.org/tracker/joomla-cms/16908</a>.</sub>
