### ISSUE TITLE
Regression, exception handling broken in J3.7.3 RC2

### ISSUE THREAD

**Issue by ggppdk** [joomla/joomla-cms#16912]
### Steps to reproduce the issue

Changes made by that PR #13257 , do not check the exact type of the "callable" 
it just blindly assumed that it is a variable method name

It breaks exception handling in J3.7.3 RC2 (changes in redirect plugin)
and also other changes may cause failures in the future if a other callable cases are used

Throw an exception in backend,
e.g. a PHP syntax error
and see that redirect plugin fails to call the previous exception handler

### Expected result
Exceptions can be handled in backend

### Actual result
Exception handling does not work in backend

### System information (as much as possible)
J3.7.3 RC2

### Additional comments
This is a release blocker, we no longer having exception handling usable in backend

**Comment by ggppdk** [comment]
Printing the previous exception handler, used here:
https://github.com/joomla/joomla-cms/blob/staging/plugins/system/redirect/redirect.php#L112

`print_r(self::$previousExceptionHandler);`

i get
`Array ( [0] => JErrorPage [1] => render ) `

so it can not be called like:
`self::$previousExceptionHandler($error);`

**Comment by zero-24** [comment]
@rdeutz @frankmayer can you take a look here?

**Comment by frankmayer** [comment]
On it.

**Comment by franz-wohlkoenig** [comment]
closed as havin PR #16913<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16912">issues.joomla.org/tracker/joomla-cms/16912</a>.</sub>
