### ISSUE TITLE
Changing an item's status doesn't change Modified date

### ISSUE THREAD

**Issue by nicksavov** [joomla/joomla-cms#16911]
### Steps to reproduce the issue

1. Edit a published article
2. In the Publishing tab, check its Modified Date
3. In the Content tab, change its status to Unpublished or Trashed
4. Save
5. In the Publishing tab, check its Modified Date.

### Expected result

In step 5 above, I'd expect the date should have changed to the time from the Save (step 4).

### Actual result

In step 5, it's still the same date as step 2.

### System information (as much as possible)

N/A

### Additional comments

In Content Versioning, the status and modified date change is recorded and compared if another field is modified.

For example, if the Finish Publishing date is changed, a new Item Version is created. Comparing the Item Version to the previous version shows Status as changed, as well as modified date.

**Comment by brianteeman** [comment]
I'm sure this has been reported before

**Comment by nicksavov** [comment]
Looks like it:
https://github.com/joomla/joomla-cms/issues/8244

Closing

**Comment by nicksavov** [comment]
And thanks!
