### ISSUE TITLE
Notice: Trying to get property of non-object in Joomla! 3.7.2 when viewing user list at back-end

### ISSUE THREAD

**Issue by innato** [joomla/joomla-cms#16921]
### Steps to reproduce the issue
- All steps at back-end
- Set global config / server / error reporting to "maximum"
- Open users list: main menu / users / manage
- Click button NEW

### Expected result

No error, notice or warning

### Actual result

At the top of the form, you will see:

Notice: Trying to get property of non-object in /var/www/vhosts/xxxxxxx.xxx/httpdocs/administrator/components/com_users/models/user.php on line 116

### System information (as much as possible)

Joomla! Version 	Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Database Version 	5.5.52-MariaDB
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.6.30
Web Server 	Apache
WebServer to PHP Interface 	fpm-fcgi
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0

**Comment by zero-24** [comment]
Can you please double check that the plugin User-Joomla is enabled and report back here. Thanks.

**Comment by innato** [comment]
@zero-24 
You are my champion, because enabling the User-Joomla plugin solved the issue. You may ask yourself why the User-Joomla plugin was disabled, the reason is that I am using a 3rd party plugin that replaces it. Apparently this 3rd party plugin has 'forgotten' something. Maybe it's only since J3.7.2 because the issue did not occur earlier. Thanks a lot!

**Comment by franz-wohlkoenig** [comment]
closed as no Core Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16921">issues.joomla.org/tracker/joomla-cms/16921</a>.</sub>

**Comment by zero-24** [comment]
@innato please test #16935 take a look here: https://docs.joomla.org/Component_Patchtester_for_Testers for how to test using the patch tester 😄

**Comment by panter011** [comment]
Hello Everyone,
I have similar issue on my site. You can see the notices here http://infotalqual.com/v3/index.php/politica
on the right column.

Please Advice!
Thank you!

**Comment by brianteeman** [comment]
That's a completely different problem and as you can see from the complete error message the problem is in the K2 module and not the core of joomla. You should ask for support from k2 or in the joomla forum https://forum.joomla.org

**Comment by nanivc** [comment]
Notice: Trying to get property 'layout' of non-object in C:\Xampp\htdocs\Joomla\plugins\system\helix3\core\classes\menu.php on line 260

Notice: Trying to get property 'attr' of non-object in C:\Xampp\htdocs\Joomla\plugins\system\helix3\core\classes\menu.php on line 263

Notice: Trying to get property 'moduleId' of non-object in C:\Xampp\htdocs\Joomla\plugins\system\helix3\core\classes\menu.php on line 264 
help me

**Comment by brianteeman** [comment]
@nanivc those are from your template and you should speak to the makers of the template

**Comment by capitolsteel** [comment]
please help us in fixing this error.

"Notice: Trying to get property of non-object in /volume1/web/CSC/templates/theme1587/includes/includes.php on line 118 Notice: Trying to get property of non-object in /volume1/web/CSC/templates/theme1587/includes/includes.php on line 118 Notice: Trying to get property of non-object in /volume1/web/CSC/templates/theme1587/includes/includes.php on line 123 Notice: Trying to get property of non-object in /volume1/web/CSC/templates/theme1587/includes/includes.php on line 123"

**Comment by ghost** [comment]
@capitolsteel i guess its the same as @brianteeman wrote above:

> you should speak to the makers of the template.

**Comment by antonscp** [comment]
I have issue on my site. You can see the notices here https://scpcr.com
Could you help me please?

Notice: Trying to get property of non-object in /home/scpcrcom/public_html/plugins/system/helix3/core/classes/menu.php on line 261

Notice: Trying to get property of non-object in /home/scpcrcom/public_html/plugins/system/helix3/core/classes/menu.php on line 264

Notice: Trying to get property of non-object in /home/scpcrcom/public_html/plugins/system/helix3/core/classes/menu.php on line 265

Notice: Trying to get property of non-object in /home/scpcrcom/public_html/plugins/system/helix3/core/classes/menu.php on line 261

Notice: Trying to get property of non-object in /home/scpcrcom/public_html/plugins/system/helix3/core/classes/menu.php on line 264

Notice: Trying to get property of non-object in /home/scpcrcom/public_html/plugins/system/helix3/core/classes/menu.php on line 265

**Comment by brianteeman** [comment]
you should speak to the makers of the template.
