### ISSUE TITLE
New menu item created by "save&new" goes to different Menu - Joomla! 3.7.2

### ISSUE THREAD

**Issue by ysrostov** [joomla/joomla-cms#16923]
### Steps to reproduce the issue
Suppose we have clear Joomla! 3.7.2 installation with sample data which comes with single Main Menu "home, about us, news, contact us" 
1. Create second menu, let's call it "Second"
2. Select new (Second) menu and create new menu item
3. Click "save & new" and thus create the third menu item

### Expected result
New third item appears in the Second menu
### Actual result
New third item appears in the Main menu
The same goes for the all next items created by "save & new" - all appear in the Main menu instead of the Second menu.

**Comment by brianteeman** [comment]
I believe this has already been resolved for the upcoming release. Please check the 3.7.3 release candidate

**Comment by ysrostov** [comment]
Thanks, sure I'll do... is there an official link somewhere to that release candidate?

**Comment by franz-wohlkoenig** [comment]
@ysrostov https://github.com/joomla/joomla-cms/releases
@brianteeman its #16374

**Comment by franz-wohlkoenig** [comment]
closed as duplicate Report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16923">issues.joomla.org/tracker/joomla-cms/16923</a>.</sub>

**Comment by ysrostov** [comment]
The test was done and I confirm - in the new release candidate the issue is fixed, everything works as expected.
