### ISSUE TITLE
FATAL ERROR! Joomla

### ISSUE THREAD

**Issue by koohdigital** [joomla/joomla-cms#16924]
I moved the localhost folders to server then now i am getting this issue. Please help

Fatal error: Call to undefined method JFormFieldText::save() in /home/kooh/public_html/kitescoach.in/administrator/components/com_categories/views/category/tmpl/edit.php on line 32

If someone knows about it please let me know

**Comment by franz-wohlkoenig** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding.

**Comment by franz-wohlkoenig** [comment]
closed as no Core Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16924">issues.joomla.org/tracker/joomla-cms/16924</a>.</sub>
