### ISSUE TITLE
iframe Wrapper module and Menu item faill with ssl

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#16938]
### Steps to reproduce the issue
Install Joomla on a server (or test server) that has ssl
Create a Wrapper Module
Create a menu item Wrapper
Check in the front end that it works
In Global config set 'Force HTTPS' 'Entire Site' and view front end

### Expected result
Iframe should display when your site doesn't 'Force HTTPS' 'Entire Site' and when it does

### Actual result
Iframe fails to display when site 'Force HTTPS' 'Entire Site'

### Additional comments
The strange thing is that if 'Force HTTPS' 'None' but you reach the site with https then you get the error.

**Comment by zero-24** [comment]
hmm i can not reproduce this. Could it be that the website you want to show in the wraper is not HTTPS?

**Comment by Webdongle** [comment]
@zero-24 
Does the site that you tested on have an ssl cert ?
Did you set  'Force HTTPS' 'Entire Site' ?

The test site must be on a server that has an ssl cert.

e.rg
Your site has an ssl cert and you have 'Force HTTPS' 'Entire Site'  and your url is **https**://www.yoursite.com
then the wrapper does not display

With 'Force HTTPS' 'Entire Site' 'None' and your url is  **http**://www.yoursite.com
then the wrapper does display

This can easily be reproduced on xampp localhost as it has ssl.

**Comment by mbabker** [comment]
You're probably running into browser security issues with mixed content.

```html
<html>
	<body>
		<iframe src="https://michaels.website/"></iframe>
	</body>
</html>
```

Make a `iframe.html` file with these contents on a server where you access the site through HTTPS.  It should load correctly.  Change the iframed URL to a site that does not use HTTPS (http://www.0to255.com/ is one I have in my bookmarks).  When you try to load it, the browser will give you mixed content warnings in its console.

**Comment by Webdongle** [comment]
@mbabker 
So a http site will not display within an iframe in a https site because the browser security warning is not displayed in the iframe ...  which means the target site will not display ?

The only answer then is when using a https site only use https targets in an iframe ?

**Comment by mbabker** [comment]
Correct.

**Comment by franz-wohlkoenig** [comment]
closed as no Core Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16938">issues.joomla.org/tracker/joomla-cms/16938</a>.</sub>

**Comment by murugappanrm51** [comment]
I dont know if i am reopening an old issue but i am using joomla for the first time. I set up a menu item in my joomla website to access a external website using the wrapper module. I tested with various scenarios but i get the same blank screen in the iframe. I tested by loading as follows:

(1) my website in a hosting server using https - works fine
(2) my hosting site CPANEL using https - works fine
(3) my hosting site login using https - does not work
(4) company website both behind and external to the firewall using https - does not work.
(5) tested using various versions (older and latest) - results same as in 1 to 4 above.
(6) tested with a totaly basic installation of joomla - results same as in 1 to 4 above.

In all cases i tested with the latest version of xampp with PHP version 7.

Please help<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16938">issues.joomla.org/tracker/joomla-cms/16938</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@murugappanrm51 please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding.

**Comment by murugappanrm51** [comment]
I did post this in the forum. Webdongle posted the link to this location. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16938">issues.joomla.org/tracker/joomla-cms/16938</a>.</sub>

**Comment by zero-24** [comment]
> Does the site that you tested on have an ssl cert ?

Yes. Let’s Encrypt

> Did you set 'Force HTTPS' 'Entire Site' ?

Yes.

Please that the page you are loading via the iframe is https too else you get the issue that Michael described above. And this is a browser issue / behavior we have no control on the CMS level.

**Comment by toivo** [comment]
My response from the Joomla forum:  Even if both your site and the target site were to use https but the target site does not allow to be presented in a frame, Chrome displays a blank frame. Both Internet Explorer 11 and Edge show a warning with a link to access the page in a new window. 

The message "...the publisher of this content does not allow it to be displayed in a frame" does not originate from Joomla but from IE11 or Edge.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16938">issues.joomla.org/tracker/joomla-cms/16938</a>.</sub>
