### ISSUE TITLE
[Travis] PHP nightly testing errors

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#16937]
### Steps to reproduce the issue

https://travis-ci.org/joomla/joomla-cms/jobs/249121876

### Expected result

PHP nightly passes

### Actual result

count(): Parameter must be an array or an object that implements Countable

### Additional comments

```
1) JApplicationCmsTest::testRedirectLegacy
count(): Parameter must be an array or an object that implements Countable

/home/travis/build/joomla/joomla-cms/tests/unit/core/helper.php:52
/home/travis/build/joomla/joomla-cms/libraries/cms/application/cms.php:471
/home/travis/build/joomla/joomla-cms/libraries/cms/application/cms.php:244
/home/travis/build/joomla/joomla-cms/libraries/cms/application/cms.php:1057
/home/travis/build/joomla/joomla-cms/tests/unit/suites/libraries/cms/application/JApplicationCmsTest.php:505
```

In that file we have just one count: https://github.com/joomla/joomla-cms/blob/staging/tests/unit/core/helper.php#L57 but this is in line 57 and not 52? I'm not getting where we did something wrong? As `debug_backtrace` returns a `array` arcording to the doku: http://php.net/manual/en/function.debug-backtrace.php

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/pull/16840 fixes the count issue.

Most errors will always use `tests/unit/core/helper.php:52` as the line that throws the error because of the deprecation error handler in the unit test suite.  It's the second line in the stack that has the "real" location.

**Comment by zero-24** [comment]
Ah ok thanks.
