### ISSUE TITLE
[RFC] Restructure namespaced MVC classes

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-cms#16941]
As already pointed out in #16582, there is an inconsistency between the MVC classes in 
- libraries/src/Joomla/CMS/Contoller
- libraries/src/Joomla/CMS/Model
- libraries/src/Joomla/CMS/View

and the rest of the namespaced classes. For example we suffixed the fields with `Field` or the helpers with `Helper` but the MVC classes not. So I suggest we suffix them with Controller, Model and View. Then the class `\Joomla\CMS\Model\Form` will become `\Joomla\CMS\Model\FormModel`. Additionally I would move them to the Mvc folder and rename the folder to all uppercase MVC as pointed out in #15175.

As an additional change, the extension classes should also end with the corresponding suffix, so for example the [`Articles` Model](https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_content/Model/Articles.php) becomes `ArticlesModel`.

Pinging here @Bakual, @wilsonge, @mbabker and @brianteeman for opinions.

**Comment by laoneo** [comment]
Closing as we have a pr.

**Comment by ghost** [comment]
closed as having Pull Request #17614<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16941">issues.joomla.org/tracker/joomla-cms/16941</a>.</sub>
