### ISSUE TITLE
Intro Image Links And Title Tags?

### ISSUE THREAD

**Issue by nronline** [joomla/joomla-cms#16950]
### Steps to reproduce the issue

Amazed that by default article intro images do not have links attached to their corresponding articles OR a field for a title tag on the bag end for adding the link. 

It would be good for this to be available by default. It's also proven that the engagement rate for clicking images is much higher than headings/text in general. 

Is it possible this will get added and does anyone have the code to add this manually? so far i have

<a href="<?php echo JRoute::_(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid)); ?>" title="<?php echo htmlspecialchars($images->image_intro_alt); ?>">
<img

	src="<?php echo htmlspecialchars($images->image_intro); ?>"
	alt="<?php echo htmlspecialchars($images->image_intro_alt); ?>"/>
</a>

### Expected result
Article image linked to main article and title tag to be replicated from image alt tag

**Comment by brianteeman** [comment]
are you talking about the image on a blog category page?

If so then Joomla does by default add a link to the full article on the image. If you dont have that then your template is probably overriding the default layout for a blog page and not adding the code for the link

**Comment by nronline** [comment]
Hi Brian, not just the blog-item.php page but general articles, basically anything with the ability to add an article intro image. Looking for overrides now

**Comment by brianteeman** [comment]
as for your comment about the title tag - it does exist under the image its called caption

**Comment by nronline** [comment]
Hi Brian, a caption and a title are two different things. I would expect the title attribute to be displayed over a link when the user hovers over it. A caption is basically a description of an image. They are two different things. I do not want to show a caption for the image I simply want to add a title attribute to the anchor link attached to the image :)

**Comment by brianteeman** [comment]
> Hi Brian, not just the blog-item.php page but general articles, basically anything with the ability to add an article intro image. Looking for overrides now

Sorry I dont follow you - the intro image is only displayed on a blog-item page and not on any other page and the code you refer to in your first post is already present

**Comment by brianteeman** [comment]
@nronline please respond to my question as I can not understand what your issue is. If not this will be closed in a few weeks

**Comment by brianteeman** [comment]
Clozed
