### ISSUE TITLE
com_contact address is no longer displayed, after upgrade to 3.7.3

### ISSUE THREAD

**Issue by beni71** [joomla/joomla-cms#16968]
### Steps to reproduce the issue
1. Make a fresh joomla 3.7.3 installation
2. Add a new contact and fillin the fields "Address", "City or Suburb", "State or Province", "Postal/ZIP Code", "Country" and "Telephone".
3. Add a menu item to make the contact accessible from the frontend.
4. Go to the frontend and open that contact menu item.

### Expected result
Because the default settings of all listed fields above are "Show", I expect, that all those fields are shown.

### Actual result
Only the "Telephone" field value is shown.

### System information (as much as possible)
<pre>
PHP Built On 	                Windows NT XAMPP 6.1 build 7601 (Windows 7)
Database Version 	        5.5.5-10.1.24-MariaDB
Database Collation 	        utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	                7.1.6
Web Server 	                Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/7.1.6
WebServer to PHP Interface 	apache2handler
Joomla! Version 	        Joomla! 3.7.3 Stable [ Amani ] 4-July-2017 08:03 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ]
User Agent 	                Mozilla/5.0 (Windows NT 6.1; rv:54.0)
                                Gecko/20100101 Firefox/54.0 
</pre>

### Additional comments
**On the previous version of joomla (3.7.0) all worked fine. After upgrading from 3.7.0 to 3.7.3 this problem occurs.**

After short investigation of the source code, i think the problem lies in the file components/com_contact/views/contact/tmpl/default_address.php

There is a if statement to check whether the address should be displayed or not:

<pre>
if (($this->params->get('address_check') > 0) &&
</pre>

But the parameter 'address_check' is not a property of $this->params.
It is a property of $this->contact->params. The parameter 'address_check' would be set on the corresponding view.html.php file.

I have temorary fixed the problem by replacing "$this->params->get" with "$this->**contact**->params->get" on the whole file. But i am not sure, if this is a clean solution.

**Comment by franz-wohlkoenig** [comment]
Issue confirmed

**Comment by richard67** [comment]
@matrikular Can this be caused by PR #15747 ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16968">issues.joomla.org/tracker/joomla-cms/16968</a>.</sub>

**Comment by ChristineWk** [comment]
Confirm partial issue after updating from J 3.7.2 to J 3.7.3. "Address" was missing.
After replacing "$this->params->get" with "$this->contact->params->get" > adress field is visible again.
The icons in front of the fields are missing.

**Comment by matrikular** [comment]
Yes, it seems so @richard67. Please see #16971 for a possible fix.

**Comment by N6REJ** [comment]
following<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16968">issues.joomla.org/tracker/joomla-cms/16968</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16971<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16968">issues.joomla.org/tracker/joomla-cms/16968</a>.</sub>

**Comment by medator** [comment]
Selam Arkadaşlar veritabanı Kaynaklı uft ölümcül 500 hatası Bilmiyorum Güncelleme yaptıktan sonra oluştu
bu bu hata joomla güncellenen sürümüyle ilgili Böyle bir hatayla karşılaştım hatanın sebeb şu

500 Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_unicode_ci,IMPLICIT) for operation '=' Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_unicode_ci,IMPLICIT) for operation '='

Replace Hatay with Old File

/my site/administrator/modules/mod_menu/helper.php 

Saygılar  Tuncay Arıcan<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16968">issues.joomla.org/tracker/joomla-cms/16968</a>.</sub>

**Comment by medator** [comment]
Selam Arkadaşlar veritabanı Kaynaklı uft ölümcül 500 hatası Bilmiyorum Güncelleme yaptıktan sonra oluştu
bu bu hata joomla güncellenen sürümüyle ilgili Böyle bir hatayla karşılaştım hatanın sebeb şu

500 Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_unicode_ci,IMPLICIT) for operation '=' Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_unicode_ci,IMPLICIT) for operation '='

Replace Hatay with Old File

/my site/administrator/modules/mod_menu/helper.php 

Saygılar  Tuncay Arıcan<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16968">issues.joomla.org/tracker/joomla-cms/16968</a>.</sub>

**Comment by Hils** [comment]
@medator perhaps it would be easier for you to discuss this in your own language?

https://forum.joomla.org/viewforum.php?f=51

hope that helps :)

**Comment by medator** [comment]
Thank you, Mrs. Hils.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16968">issues.joomla.org/tracker/joomla-cms/16968</a>.</sub>

**Comment by federal12** [comment]
3.7.4 has fixed the icons and address but email address and vcard still do not show.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16968">issues.joomla.org/tracker/joomla-cms/16968</a>.</sub>

**Comment by ghost** [comment]
@federal12 can you please open an new Issue?

**Comment by matrikular** [comment]
@federal12 Joomla! 3.8.0-dev
![contact](https://user-images.githubusercontent.com/1304616/29188986-38b90136-7e15-11e7-8018-2232a5858323.jpg)

**Comment by federal12** [comment]
Looking good! Started a new issue as requested.
