### ISSUE TITLE
Multilanguage with PHP 5.3 causes fatal error

### ISSUE THREAD

**Issue by SniperSister** [joomla/joomla-cms#16965]
### Steps to reproduce the issue
Run a multilingual site (language filter plugin) on PHP 5.3.x

### Expected result
The site works as expected.

### Actual result
You'll get an fatal error:
> Fatal error: Function name must be a string in libraries/cms/router/router.php on line 639

### System information (as much as possible)
PHP 5.3.29

### Additional comments
This is a regression caused by this commit:
https://github.com/joomla/joomla-cms/commit/30621cf95e25f17427736ebf85d9218f5e8f84a9

**Comment by SniperSister** [comment]
Also see #16913

**Comment by SniperSister** [comment]
For a quick fix, replace libraries/cms/router/router.php with the patched version:
[router.php.zip](https://github.com/joomla/joomla-cms/files/1122371/router.php.zip)

**Comment by infograf768** [comment]
for a better fix, update your php version to 5.4.x or upper 😃

**Comment by rdeutz** [comment]
we have a PR #16966, closing
