### ISSUE TITLE
Post installation message: Wrong php detection

### ISSUE THREAD

**Issue by Klipper** [joomla/joomla-cms#16964]
### Steps to reproduce the issue
Upgrade to Joomla 3.7.3
Read post installation message.

With me it says: .... Beginning with Joomla! 3.3, **the version of PHP this site is using** will no longer be supported. ...

Actually this site is using php 7.0.20 (Siteground)
See attached screencapture:
![screen shot 2017-07-04 at 13 37 11](https://issues.joomla.org/uploads/1/16718234619940cabe7d0b8fc2da343b.png)
### Expected result

No post installation message, because I'm using correct PHP version.

**Comment by david-bettondesign** [comment]
I can confirm that I also get this on PHP 7.1.6

**Comment by brianteeman** [comment]
Please go to the system information menu and confirm that it really is php 7 etc being reported on that page

**Comment by david-bettondesign** [comment]
7.1.6-1~ubuntu16.04.1+deb.sury.org+1

**Comment by brianteeman** [comment]
sorry I see it now as well and can confirm the issue. I didnt read properly and thought you were talking about the php message on the home control panel of joomla and not the post install message

**Comment by mahagr** [comment]
I'm not seeing the message in my Joomla installation after the update. There are just 3 messages in my updated installs (test sites):

Stats Collection in Joomla
Welcome to Joomla!
Two Factor Authentication is Available

**Comment by infograf768** [comment]
Hmm, It looks like the file phpversion.php that used to be in `/administrator/components/com_admin/postinstall/phpversion.php`
is not present anymore to check the php version while the postinstall message is still present in the db

**Comment by brianteeman** [comment]
ah that is my fault then

**Comment by mahagr** [comment]
I think it's leftover message after some older update, stored into db, just like @infograf768 said.

**Comment by infograf768** [comment]
the file should not have been deleted, for people who update from a 3.2.x or earlier

**Comment by Bakual** [comment]
> the file should not have been deleted, for people who update from a 3.2.x or earlier

In 3.7, it's not relevant anymore and can be deleted. That was fine. The message has to be shown in 3.2, not in 3.7 (where it wouldn't work anymore anyway due to outdated PHP version).

**Comment by infograf768** [comment]
therefore, i guess the db has to be corrected/updated

**Comment by mahagr** [comment]
Why db should be corrected? The message came a long time ago after an update and the user hasn't marked the message to be hidden. It is just an old notification which later became obsolete after user updated PHP.

**Comment by Klipper** [comment]
"The message came a long time ago after an update and the user hasn't marked the message to be hidden."

I never have seen this message in previous updates at all... And, I always hide these blue Post Installation Messages immediately. And yes I read these messages :-) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16964">issues.joomla.org/tracker/joomla-cms/16964</a>.</sub>

**Comment by brianteeman** [comment]
> I never have seen this message in previous updates at all... And, I always hide these blue Post Installation Messages immediately. And yes I read these messages :-)

You wouldnt have seen it and therefore  been able to hide it because the code was there to hide it as you were on a higher php version.

**Comment by mbabker** [comment]
> You wouldnt have seen it and therefore been able to hide it because the code was there to hide it as you were on a higher php version.

That.  When the table was being read, the callback function defined in the file was preventing it from being displayed.  That callback function doesn't exist anymore, so the component just shows the message since there's nothing to test it against.

So yes, the record should be removed from the database as well as the file being deleted since the intent is to not have the message at all anymore.

**Comment by Klipper** [comment]
Agree, because I always try to use the latest stable php version. But probably because of missing /administrator/components/com_admin/postinstall/phpversion.php I get this message now with this latest update. I myself know I can ignore it, because I 'm sure I use correct phpversion, but may be other administrators can get confused...

If this issue will not be fixed, we will get this message now with each new update I assume...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16964">issues.joomla.org/tracker/joomla-cms/16964</a>.</sub>

**Comment by acs-ferreira** [comment]
FYI, i've updated 4 websites from 3.7.2, same webserver, got the message on all of them.

**Comment by n9iels** [comment]
Confirmed on all my installations. Also immediately a message from someone who was confused because he used PHP7 already and this message just popped up.

**Comment by brianteeman** [comment]
On the plus side at lest it shows that some people notice the messages even if they dont understand/comprehend what they say

**Comment by richard67** [comment]
I can confirm that, too, with PHP 7.1.6.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16964">issues.joomla.org/tracker/joomla-cms/16964</a>.</sub>

**Comment by ribo72** [comment]
Hello, i confirm this issue exist in joomla sites that the fresh install was in older joomla 3.x versions or migrated joomla sites from 1.5 or 2.5. I saw this issue in php 5.6.30 , 7.0.20, 7.1.6 .

**Comment by brianteeman** [comment]
Please stop posting "me too"

**Comment by N6REJ** [comment]
tracking

**Comment by infograf768** [comment]
See PR https://github.com/joomla/joomla-cms/pull/16974
