### ISSUE TITLE
`Warning: str_repeat()` after update from 3.7.2 to 3.7.3

### ISSUE THREAD

**Issue by ittoufiq** [joomla/joomla-cms#16975]
### Problem in module manager search tools

Warning: str_repeat(): Second argument has to be greater than or equal to 0 in libraries/cms/form/field/menuitem.php on line 234

http://prntscr.com/frsfor

-Thanks

**Comment by anabarcellos** [comment]
As far as I understood this is not an issue, just a simple warning. 
Did you check if the message disappears when you change the error report to "None" or "Simple"? 

Global configuration > server tab > set error reporting to 'None' or 'Simple' 

If it persists, please check the default php settings in your server. Probably they are higher than they should.   

For more information, maybe this can help: https://forum.joomla.org/viewtopic.php?t=932244 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16975">issues.joomla.org/tracker/joomla-cms/16975</a>.</sub>

**Comment by brianteeman** [comment]
there  shouldnt be any warnings

**Comment by alikon** [comment]
@ittoufiq 
can you replace  that line libraries/cms/form/field/menuitem.php on line 234
with this one `$levelPrefix = str_repeat('- ', max(0, $link->level - 1));`
and report back result

**Comment by csthomas** [comment]
IMO This is a sign of corruption of the menu.
Only one menu item "ROOT" can have `$link->level` less than 1.

**Comment by ittoufiq** [comment]
Hi, Thanks a lot guys. Should i wait for Joomla wait? Thanks

**Comment by csthomas** [comment]
Example code from @alikon should hide the warning but it probably does not fix a reason of your issue.

Do you see an unexpected menu item name like "ROOT" in select box below PHP warning?

If you have access to phpmyadmin you can show us rows from `#__menu` with column level <= 0.

**Comment by brianteeman** [comment]
I am going to close this due to a lack of reply - it can always be reopened if updated
