### ISSUE TITLE
Wrong Post-installation Message for PHP7.1.6

### ISSUE THREAD

**Issue by joo7** [joomla/joomla-cms#16976]
### Steps to reproduce the issue
set PHP Version 7.1.6 and update to J3.7.3 

### Expected result
ok

### Actual result
Your PHP Version Will Be Unsupported in Joomla! 3.3
Since version 3.2.2
Beginning with Joomla! 3.3, the version of PHP this site is using will no longer be supported. Joomla! 3.3 will require at least PHP version 5.3.10 in order to provide enhanced security features to its users.

### System information (as much as possible)
PHP Built On 	Linux xxxxxxx 3.10.0-042stab123.3 #1 SMP Fri May 5 12:29:05 MSK 2017 x86_64
Database Version 	5.5.5-10.1.24-MariaDB
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.1.6
Web Server 	Apache
WebServer to PHP Interface 	fpm-fcgi
Joomla! Version 	Joomla! 3.7.3 Stable [ Amani ] 4-July-2017 08:03 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0

**Comment by brianteeman** [comment]
Closed as a duplicate report
