### ISSUE TITLE
Contact record parts not displayed

### ISSUE THREAD

**Issue by rouhu** [joomla/joomla-cms#16980]
After 3.7.3 upgrade the address, zip-code, country are no longer displayed in Contacts component page (link to single contact). Only email and telephone is displayed.

**Comment by franz-wohlkoenig** [comment]
Thanks for report, but this is closed as duplicate Report #16968<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16980">issues.joomla.org/tracker/joomla-cms/16980</a>.</sub>
