### ISSUE TITLE
Problem with Admin Tabs in 3.7.3

### ISSUE THREAD

**Issue by alex-equities** [joomla/joomla-cms#16984]
### Steps to reproduce the issue

Go Joomla admin -> Global Config -> Pick any component (for examole Cache) then tabs are not loading

### Expected result

Load default tab

### Actual result

getting javascript error

Uncaught ReferenceError: wgxpath is not defined
in /media/system/js/tabs-state.js?605d27beb48904c56ac7b7fd39ed7dbd

### System information (as much as possible)
 upgraded from 3.7.2 to 3.7.3

**Comment by franz-wohlkoenig** [comment]
Can't confirm.

Loading "Cache"-Options got "Permissions"-Tab.

**Comment by alex-equities** [comment]
![cache options equities com administration](https://user-images.githubusercontent.com/20544918/27875178-4c71144a-6180-11e7-9fcc-0cc254bcbb65.png)

**Comment by franz-wohlkoenig** [comment]
@alex-equities i believe this Issue, but i can't confirm it as i get Tab and Permissions Settings.

**Comment by alex-equities** [comment]
Restoring `F:\work\phpStorm\Equities.com\cms\media\system\js\tabs-state.js` to original 3.7.2 version fixed the issue. But it needs to be fixed in Joomla for everybody

**Comment by alex-equities** [comment]
More Specifically - This line causing stuff to break
`    if (typeof wgxpath.install === "function") {
        wgxpath.install()
    }`

**Comment by mbabker** [comment]
This might be a browser related issue.  I can't duplicate this on any site I've upgraded in the last couple days from Chrome or Firefox on Mac.  What browser(s) are you using?

This could also be a cache issue.  From the sound of things that seems less likely since you're getting a line that's introduced in the new release but still a possibility.

**Comment by alex-equities** [comment]
I checked both Chrome and Firefox and this issue is the same on both

**Comment by brianteeman** [comment]
Have you tried on more than one joomla site? I cant replicate this either

**Comment by mbabker** [comment]
What versions?  I get the feeling we're getting into something very specific here and not just a "it works on Chrome but not IE" type error.

**Comment by brianteeman** [comment]
and on what operating system

**Comment by alex-equities** [comment]
Windows 10, Chrome Version 59.0.3071.115 (Official Build) (64-bit)

Unfortinualy I only have 1 joomla site :(

But I think the issue is pretty straight forward. I'm missing wgxpath. Does it come with Joomla core? May be it's missing from a template or something?

**Comment by brianteeman** [comment]
> Windows 10, Chrome Version 59.0.3071.115 (Official Build) (64-bit)

I am on exactly the same

**Comment by mbabker** [comment]
MacOS 10.12.5, Chrome Version 59.0.3071.115 (Official Build) (64-bit)

Can't duplicate it.

> I'm missing wgxpath. Does it come with Joomla core?

No.  Joomla doesn't ship it.  Looking at the [commit this was changed in](https://github.com/joomla/joomla-cms/commit/83ecdd82cd22db61c8a426ea48541298fb8c1e58#diff-d3f19b9eb4be961f4c9208af46af9496), it seems the PR at one point was going to add support for it and changed to another xpath polyfill perhaps?  Paging @PhilETaylor as he may remember this better.

**Comment by mbabker** [comment]
Check your network requests and see if `/media/system/js/polyfill.xpath.js` gets loaded.  That may help figure something out.  Or worst case scenario it's just a dead end.

**Comment by PhilETaylor** [comment]
> No. Joomla doesn't ship it. 

media/system/js/polyfill.xpath.js

This is 99% surely going to be a "clear your cache" issue :)

**Comment by mbabker** [comment]
When I said we don't ship it, it's because https://github.com/joomla/joomla-cms/search?utf8=%E2%9C%93&q=wgxpath&type= doesn't include it in the repo's search index.  Didn't realize that xpath polyfill was indeed wgxpath until after the fact.

**Comment by dgt41** [comment]
@mbabker media/system/js/polyfill.xpath-uncompressed.js === wgxpath

Reading that polyfill tho I see that there is a timeout of 100 ms which make me thing that this might be a race condition here, we call a function which (in a slow machine) might not be registered yet

**Comment by alex-equities** [comment]
I don't have polyfill.xpath.js loaded anywhere in source or via Chrome Network

**Comment by PhilETaylor** [comment]
@dgt41 a wild guess thats wrong. because the tabs state will call the install method when needed. 

@alex-equities if you dont have that file then you dont have a complete copy of Joomla- run the update again

**Comment by alex-equities** [comment]
I re-did the update and in the matter of fact now I do have ```polyfill.xpath.js``` file. 

Sorry for stressing everybody out :(

**Comment by zero-24** [comment]
Thanks for updating here I'm going to close than 😄

**Comment by ghost** [comment]
same error here with Joomla 3.7.3 admin
nav-tabs is empty , no li
`<ul class="nav nav-tabs" id="myTabTabs"></ul>`

 /media/system/js/polyfill.xpath.js is loaded but it does not work on any website with 3.7.3

**Comment by spurgeonbj** [comment]
Hi, We too had this issue twice.

Once after upgrade to 3.7.5 (from 3.6.5 or so) and then after upgrade to 3.8

This time around, I commented 3 lines (15-17) of tabs-states.js to get it working.

Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16984">issues.joomla.org/tracker/joomla-cms/16984</a>.</sub>

**Comment by cheesegrits** [comment]
I know this is old, but just thought I'd add a "me too", on an older customer site I'm trying to update from 3.6.5.  As soon as I enabled debug, it blew up with the same error.  However, the customer says he tried to update recently and "it broke" (hence my involvement) so I'm not sure if the site has a clean set of files.  The tabs-state.js doesn't have the "typeof wgxpath.install", but tabs-state-uncompressed.js does (plus a lot of other differences).

Anyway, just for anyone else googling around and stumbling on this ... to confirm @spurgeonbj 's fix of commenting those lines out (in the uncompressed) fixes it.
