### ISSUE TITLE
Calendar field custom is not load in Joomla3.7.2

### ISSUE THREAD

**Issue by erakashpatel** [joomla/joomla-cms#16982]
Hello,
In latest joomla3.7.2 Calendar.setup is not working.its working fine in joomla3.6.

Calendar.setup({
		inputField     :    "test-inputfield",
		ifFormat       :    "%Y-%m-%d",
		showsTime      :    false,
		button         :    "calImg",
		align		   :    "BR"
	});
Joomla 3.7.2 gives me TypeError: r is undefined in calander.min.js
Any one have load custom Joomla date like this way.
I want to load this way.

Best of luck in advance.
Thanks
akashpatel

**Comment by dgt41** [comment]
@erakashpatel as long as you already loaded the required scripts https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/form/field/calendar.php#L97-L104 this snippet should work. Are you loading the calendar (check the page assets if the scripts, css files are there) ?

**Comment by erakashpatel** [comment]
Hello @dgt41 
Thanks for the super-fast reply :)
yes. my calendar.setup script is load in popup in js.
Are you loading the calendar (check the page assets if the scripts, css files are there) ?
Answer : yes if i load calendar then its working fine.but not in popup :(

**Comment by erakashpatel** [comment]
Hello @dgt41,

I fixed it this way..
/media/system/js/fields/calendar.min.js unpack this js.
r = this.button, ->change to -> var r = this.button, in line number : 31.

NOW can you please tell me its Joomla calenndar.min.js bug ?

Thanks
akashpatel

**Comment by dgt41** [comment]
@erakashpatel if the popup opens an iframe then you need to load the scripts there as well
