### ISSUE TITLE
Fix #16756 in 3.7.3 breaks 'Create article' menu item

### ISSUE THREAD

**Issue by netamity** [joomla/joomla-cms#16983]
### Steps to reproduce the issue
Use menu item of type 'Create article' in a site updated to 3.7.3 from earlier version (3.7.2 in this case)

### Expected result
You are taken to the create article form

### Actual result
Using menu item results in redirect to current page (with non-SEF url in this case)

### System information (as much as possible)
J3.7.3
SEF URLs without modrewrite
form.php view template override (but tested without)
Menu items with issue were created before 3.7.3 but refreshed with no change

### Additional comments
Issue seems to come from a_id=0 parameter added in previous fix. Removing 
$form->setKey('a_id');
from router fixes issue -  components/com_contents/router.php:43

**Comment by infograf768** [comment]
I can't reproduce the issue in Protostar.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16983">issues.joomla.org/tracker/joomla-cms/16983</a>.</sub>

**Comment by netamity** [comment]
Excuse my ignorance. What additional info can I provide. I was hoping to use the forum post assistant, but that doesn't look right when I try to paste it into this box.
I guess it's possible that this problem is unique to my site, but I can't figure out what's different about it. I've tested on my other sites and don't have this issue.
Whatever the case, it was working before the recent update. I have got around the issue by commenting out the one line from the content router (naughty, I know).
Please advise whether you think it's worth investigating or it's best to close the issue.
Andy
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16983">issues.joomla.org/tracker/joomla-cms/16983</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@netamity please test using Protostar.

**Comment by wojsmol** [comment]
@netamity Which line you commented?
@franz-wohlkoenig  Always ask this question as a debug step in similar cases.

**Comment by netamity** [comment]
@wojsmol Commented line is components/com_content/router.php line 43
		$form->setKey('a_id');
@franz-wohlkoenig  I uncommented the above line and switched to protostar. Works without issue. Returned to my template and issue returned. So the problem resides in my custom template, a very old warp-based template that I've heavily edited.

Concluded this is a problem just for me (I'll investigate further, but I have a fix that works for me now). Happy to close if you are.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16983">issues.joomla.org/tracker/joomla-cms/16983</a>.</sub>

**Comment by ghost** [comment]
thanks for Info, @netamity. Closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16983">issues.joomla.org/tracker/joomla-cms/16983</a>.</sub>
