### ISSUE TITLE
google indexes text-snippet com_ajax&format=json

### ISSUE THREAD

**Issue by joo7** [joomla/joomla-cms#16998]
### Steps to reproduce the issue
click https://joomla.org/index.php?option=com_ajax&format=json

### Expected result
no url which can be indexed

### Actual result
found in google searchresults
https://www.google.de/search?q=%7B%22success%22%3Atrue%2C%22message%22%3Anull%2C%22messages%22%3Anull%2C%22data%22%3Anull%7D&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&ei=wxxeWdD7KOWCX564jqAC#q={%22success%22:true,%22message%22:null,%22messages%22:null,%22data%22:null}&filter=0

**Comment by franz-wohlkoenig** [comment]
closed as having PR #17012<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16998">issues.joomla.org/tracker/joomla-cms/16998</a>.</sub>
