### ISSUE TITLE
"Show Label" option on Contact Mail fields is not working

### ISSUE THREAD

**Issue by ketihar** [joomla/joomla-cms#16994]
### Steps to reproduce the issue
Create one contact
Create a mail field for the contact
Try to hide the label using "Show Label" option on the field

### Expected result
The label is hidden

### Actual result
The label is still there

### System information (as much as possible)
Setting	Value
 
PHP Built On	Windows NT DESKTOP-9URP3EH 10.0 (Windows 10)
Database Version	5.7.14
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.10
Web Server	Apache/2.4.23 (Win64) PHP/7.0.10
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)

### Additional comments
I try the updated version 3.7.3 and the problem is still there![screen shot 2017-07-06 at 10 01 53](https://issues.joomla.org/uploads/1/eb2a87bb1488c0076696b8d27e915236.gif)

**Comment by franz-wohlkoenig** [comment]
Issue confirmed. @laoneo any Suggestions?

**Comment by laoneo** [comment]
The show label setting comes only into action on the front end when the field is automatically displayed. But here we have a form where this setting is not considered.

**Comment by ghost** [comment]
so this should be explain in backend or don't show Setting for Mail-Field ot another Solution to make expected behaviour clear.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16994">issues.joomla.org/tracker/joomla-cms/16994</a>.</sub>

**Comment by laoneo** [comment]
Probably the easiest fix would be to just not show the setting on the back end for mails. Also the description itself should probably be better.

**Comment by charisketikidis** [comment]
This is a good option to have. Why we just don't fix it so we can hide the label if we want?

**Comment by laoneo** [comment]
Please test #17177, it adds a new option to hide the label also in the form.

**Comment by zero-24** [comment]
Closing as there is a PR. Thanks @laoneo
