### ISSUE TITLE
[com_fields] When non latin characters are used on contact mail custom fields, the email doesn't support those characters

### ISSUE THREAD

**Issue by ketihar** [joomla/joomla-cms#16996]
### Steps to reproduce the issue
Create one contact
Create a mail custom field for example one list custom field and put values with non latin characters (i used Greek characters like "Διαμονή")
Try to sent email from contact form on frontend

### Expected result
The email has non latin characters support and shows all greek words right

### Actual result
There is no support for non latin characters. As you can see on my picture

### System information (as much as possible)
PHP ![screen shot 2017-07-06 at 11 00 14](https://issues.joomla.org/uploads/1/a40a2df15a20eaa4d093fa43fb58fb3f.jpg)Linux Charis-Hosting 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64
5.5.55-0ubuntu0.14.04.1-log
utf8_general_ci
utf8mb4_general_ci
PHP	7.0.20
Apache/2.4.25 (Unix) OpenSSL/1.0.1f
PHP	fpm-fcgi
Joomla! 3.7.3 Stable [ Amani ] 4-July-2017 08:03 GMT
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments
When non latin characters are used on contact mail custom fields, the email that sent has no non latin characters support

**Comment by infograf768** [comment]
can you add here screen shots of the custom field itself in order to test exactly

**Comment by ketihar** [comment]
![screen shot 2017-07-06 at 15 09 35](https://issues.joomla.org/uploads/1/522c92eefb7d4cce6bb28996822dfeae.jpg)
![screen shot 2017-07-06 at 15 09 46](https://issues.joomla.org/uploads/1/680074ee7a38841751eccbe9dfd0bdcf.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16996">issues.joomla.org/tracker/joomla-cms/16996</a>.</sub>

**Comment by infograf768** [comment]
I confirm the issue. I guess List does automatically translate Values to html entities, which is wrong in this case as it is correctly saved as utf8 (uencoded) in the db.

**Comment by infograf768** [comment]
@laoneo @Bakual 
Can you look at this?

**Comment by infograf768** [comment]
By taking off the htmlentities() in 
https://github.com/joomla/joomla-cms/blob/staging/plugins/fields/list/tmpl/list.php#L31
i.e. replacing by `echo implode(', ', $texts);`
it solves the issue here.

But I guess we should rather have a specific code when list is used with mail.

**Comment by infograf768** [comment]
wow, that goes much further:
If I use text instead of list, I have the same issue.
There too it uses htmlentities()

**Comment by infograf768** [comment]
will make patch

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/17005
