### ISSUE TITLE
Joom 3.7.2 - Invalid security token. Refresh page and try again on form submit

### ISSUE THREAD

**Issue by Chacapamac** [joomla/joomla-cms#16999]
### Steps to reproduce the issue
Turn OFF “System - Page Cache”
(Try on 2 sites)

### Actual result
No More “Invalid security token. Refresh page and try again” error on Contact forms Submit

### System information (as much as possible)
Site 1 = Joomla 3.7.2 - php 7.1 - Site 2 = Joomla 3.6.5 - php 5.6.3

### Additional comments
I have Regular Labs Cache Cleaner free that clean cache on site update (not automatic) and by leaving “System - Page Cache” On will mean that all my main contacts forms will be NOT WORKING until an update is made to the site (NOT GOOD!)

**Comment by gwsdesk** [comment]
I have just tested this again on a vanilla Joomla 3.7.3 installation with Page Cache System plugin enabled with browser caching set to "yes' and I cannot replicate this. I can send an email without any problems<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16999">issues.joomla.org/tracker/joomla-cms/16999</a>.</sub>

**Comment by Chacapamac** [comment]
Thanks for your Answer

The problems was that I need to turn the cache On, on the contact modules themselves  
Good Day !

Patrick Toulze
Graf • Art Director — Marketing Counselor — Social Channels — SEO — Web Mobile

**Comment by ghost** [comment]
Closed as no Core-Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16999">issues.joomla.org/tracker/joomla-cms/16999</a>.</sub>
