### ISSUE TITLE
REGRESSION - Joomla 3.7.3: Reoccurence of profile form bug previously fixed in 3.7.0

### ISSUE THREAD

**Issue by Spudley** [joomla/joomla-cms#17001]
Please refer to https://github.com/joomla/joomla-cms/pull/13254

This pull request was made in response to a bug in J 3.6.5 whereby user profile fields would be displayed as optional on the registration form despite being set to disabled.

The fix involved changing `$this->getForm(array(), false)` to `$this->getForm(array())`.

This fix [has been reverted in J 3.7.3](https://github.com/joomla/joomla-cms/commit/b5c8b6028023abecb3ea1b31fb02bfcd8c07aeec) and the same bug is now happening again.

The reverted code also includes a comment "Don't load the data in this getForm call, or we'll call ourself", so clearly there is a reason for it to be written that way, but it is breaking the user profile plugin.

**Comment by Spudley** [comment]
Additional: I was also about to post a second ticket, stating that the J 3.7.3 update had also broken another third party user plugin, the [Multi Usergroup Registration plugin](https://www.joomapp.com/extension/joomla-frontend-usergroup-registration/). However, it turns out that this is also caused by same change. I made the same fix as before; ie removing the `false` parameter; and the issues in both plugins were resolved.

**Comment by infograf768** [comment]
@bembelimen 
Please look what you can do as it seems your PR is at stake
https://github.com/joomla/joomla-cms/pull/15724

**Comment by funbugpiz** [comment]
I have this (old) problem:

Terms of Service article is not linked to TOS label
[Your text to link here...](https://github.com/joomla/joomla-cms/issues/13973 "#13973")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17001">issues.joomla.org/tracker/joomla-cms/17001</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@funbugpiz looks like this Issue you reported isn't related to this issue so can you please open an new Issue?

**Comment by funbugpiz** [comment]
Sorry, I think there is a realation. But I can be wrong.

If I changes in components/com_users/models/registration.php line 247:
$form = $this->getForm(array(), false); to
$form = $this->getForm(array()); See above, then I fix the problem with the TOS link.

Also look at: [false param on fetching form data](https://docs.joomla.org/J3.x:Update_from_3.6.x_to_3.6.5_Profile_fields "")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17001">issues.joomla.org/tracker/joomla-cms/17001</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@infograf768 can you please have a look about Relation?

**Comment by infograf768** [comment]
Results of my tests.

**First :** 
> User profile fields would be displayed as optional on the registration form despite being set to disabled.

**I can't confirm that one when new registration in frontend :**
Plugin params:
![screen shot 2017-07-09 at 08 00 41](https://user-images.githubusercontent.com/869724/27991609-e3207864-647c-11e7-95d4-e8859b566c65.png)

Registration form:
![screen shot 2017-07-09 at 08 01 28](https://user-images.githubusercontent.com/869724/27991612-ef8a488c-647c-11e7-96f2-c48b2e790d4c.png)

Address 1 and Address 2, which are disabled, do not display in the registration form, which is correct.
But Country, which is required, is set as Optional, which is incorrect

**While creating a new User in back-end**, that user profile form in back-end just does not take into account at all of Optional/Required params, behavior similar to Registration (screenshot below).

![screen shot 2017-07-09 at 08 15 42](https://user-images.githubusercontent.com/869724/27991674-e0867c28-647e-11e7-8a05-a77312925082.png)

**Editing a profile in frontend**

Plugin params:
![screen shot 2017-07-09 at 08 11 08](https://user-images.githubusercontent.com/869724/27991634-3d753fb0-647e-11e7-86f8-efa5826c3284.png)

Frontend and back-end profile edit:
![screen shot 2017-07-09 at 08 12 09](https://user-images.githubusercontent.com/869724/27991643-5d3ee86e-647e-11e7-90c3-788a918717f4.png)

Disabled and Required fields are set OK.

**Second:**
>Terms of Service article is not linked to TOS label

I confirm the error.
(**NOTE:** For a multingual site, the TOS article has to be tagged to the correct Content Language, and its category too. Associations are to be used with other TOS articles tagged to the other Content Languages, themselves in categories tagged to the same Content Language)

**Indeed reverting**
`$form = $this->getForm(array(), false);`
to
`$form = $this->getForm(array());`

Solves both issues.

**Comment by infograf768** [comment]
PR reverting #15274
Closing.

**Comment by sandewt** [comment]
Hi infograf768,

I'm relative new here.
_
Second: Terms of Service article is not linked to TOS label_

What is the following step(s) to solve this problem?

Gr.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17001">issues.joomla.org/tracker/joomla-cms/17001</a>.</sub>

**Comment by ghost** [comment]
@funbugpiz please have a Look at PR #17043
