### ISSUE TITLE
"SELECT 1" returns null

### ISSUE THREAD

**Issue by olleharstedt** [joomla/joomla-cms#17000]
### Steps to reproduce the issue

Don't know. It's the query in asset table check(): https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/table/asset.php#L110

The result is always null for a specific page load. I'm logging the query:

    query = "\nSELECT 1\nFROM `#__assets`\nWHERE `id` = 1"

If I run it in our database, the result is 1. If I change `SELECT 1` to `SELECT COUNT(*)`, the query works.

### Expected result

1

### Actual result

null

### Additional comments

I copied this exact query into a CLI test file, but was not able to reproduce the problem.

**Comment by olleharstedt** [comment]
Changing the query to `->select('1 AS x')` makes it work.

**Comment by csthomas** [comment]
In short this is Falang issue.

See: https://github.com/joomla/joomla-cms/pull/14319#discussion_r125891241

**Comment by franz-wohlkoenig** [comment]
closed as no Core Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17000">issues.joomla.org/tracker/joomla-cms/17000</a>.</sub>
