### ISSUE TITLE
J3.7.3 ALC issue

### ISSUE THREAD

**Issue by Artwebco** [joomla/joomla-cms#17008]
### Steps to reproduce the issue

After I updated my website from J3.7.2 to J3.7.3 the menu modules which are with access level "Registered" become a visible.
Seems there is a bug in J3.7.3

**Comment by zero-24** [comment]
Why did you close this? Is this issue resolved?

**Comment by franz-wohlkoenig** [comment]
@zero-24 guess #16997 ([comment](https://github.com/joomla/joomla-cms/issues/16997#issuecomment-313499765))

**Comment by Artwebco** [comment]
This is duplicate ticket, I see here is already opened ticked for the same issue.

**Comment by zero-24** [comment]
The other ticket is about using the root user? Please double check that tis is enabled on your site else this is a different issue.

**Comment by Artwebco** [comment]
When the root user is used in configuration.php then the modules which are with "Registered" access level become visible. This issue is only under version 3.7.3.
I am sure the this is the same issue.

**Comment by brianteeman** [comment]
The root user should only ever be used as a temp measure

**Comment by Artwebco** [comment]
Yes of course, but if I forget to remove the root user it may cause confusion. :)

**Comment by brianteeman** [comment]
Somethings we can't fix
