### ISSUE TITLE
RFC Joomla non english installation

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17019]
I have meant to submit this for ages sorry for the delay but i rarely install joomla in anything other than english

When i install joomla it uses my browser language to decide what language the installer will be displayed in. So if I am using a spanish language browser then the Joomla installation will be spanish.

That's awesome and something almost unique to joomla

So why oh why oh why is the version of joomla that's installed then in English and I have to go through an extra step to install  the Spanish language and then another step to configure it as my default language (and possibly disable English as I only speak english).

Surely if I install Joomla using the spanish language then the spanish language will be installed and enabled

**Comment by ot2sen** [comment]
It would be a logic next step to do now for improving the first time user experience for all the non-English speaking users.

Why it is so goes back to when everything was manually installed, like languages packs. Also been a matter of keeping size down for the core distribution then by not adding 70 packs and related data by default.

Today you could fetch the users language on the fly and would also have to add localised core data and demo data during that process. Would require a little more work for the translation teams.

Until now this have been solved by so called unofficial distributions by some translation teams but it would be nice to have joomla speak all supported languages natively from the very first step.

**Comment by szoupi** [comment]
No matter the frontend lang, backend is always in English for me. 50% of my installations are not my native lang. I think installation process should be  simple and clever enough to suggest and allow lang customization for both front/back end

**Comment by brianteeman** [comment]
@szoupi so would you like Joomla to automatically install the language used during the installation AND english (note we need to always install english anyway as it is the fallback language if a string is not available in the alternative language)

**Comment by infograf768** [comment]
As it is now, one can choose to install in her/his language and then install other languages than en-GB (including the language chosen for the UI at installation time) and choose front and backend default languages.
Yep, would be great to be proposed to install the same language used at install time, in a new page just after choosing the sampledata or automatically at that time.
As for customized sample data, it is another matter as it is much more complex for TTs.

**Comment by brianteeman** [comment]
My thoughts would be either

a) if the installer is in greek then the greek language is automatically installed (with english) without any user input and then you can optionally install more languages as you do now

or

b) if the installer is in greek then the greek language is suggested (preselected) at the top of the page where you install additional languages

**Comment by mbabker** [comment]
The one thing we can't do right now is propose sample data in a given language without a lot of extra effort.  I don't see though why we couldn't add another step to the install process (the point where we are actually doing the install, i.e. seeding the database, writing config, etc.) where if the installer is not using en-GB we automatically download, install, and set the used language as the default for the new site (and that's something we could put into 3.8 if a PR is proposed and tested before July 28).  We might also want to put a toggle for that behavior at the last step of the installer (same screen as sample data) so someone could opt in/out of it (i.e. I don't think I'd want that behavior in my main git clone of the repo that I contribute from to always install the en-US pack).

**Comment by brianteeman** [comment]
If I knew how to wrote that code then I would ;)

Good point about en-US - a bit of an edge case issue but a valid one as thats an odd language

**Comment by infograf768** [comment]
> We might also want to put a toggle for that behavior at the last step of the installer

Indeed

**Comment by mbabker** [comment]
> Good point about en-US - a bit of an edge case issue but a valid one as thats an odd language

Same logic applies for JM and the French language or anyone else, that was just the one applicable to me personally.

**Comment by infograf768** [comment]
For any one wanting to make such a patch, do not forget that custom distros contain en-GB + their own language.

**Comment by brianteeman** [comment]
If custom distros need to be changed then they will need to be changed

**Comment by infograf768** [comment]
No need... The patch should just check which languages are included in the custom distros before re-installing those that are already present.

**Comment by mbabker** [comment]
> If I knew how to wrote that code then I would ;)

Well, for anyone interested, to sum it up:

- Add a check in https://github.com/joomla/joomla-cms/blob/staging/installation/view/install/html.php to add a task to install the language based on whatever conditional logic we choose (toggle or non en-GB language is active)
- A new controller in https://github.com/joomla/joomla-cms/tree/staging/installation/controller/install to handle the task
- With any luck, we can reuse existing code in https://github.com/joomla/joomla-cms/blob/staging/installation/model/languages.php to actually download and install the extra package, otherwise we'll need some more code in there to handle things

**Comment by dgrammatiko** [comment]
@brianteeman are you proposing this for J3 or J4?

**Comment by mbabker** [comment]
> are you proposing this for J3 or J4?

Why not both?

**Comment by brianteeman** [comment]
As J3 has over 2 years life then ideally for both

**Comment by mbabker** [comment]
We already have the code to handle installing languages, that's the most complex part of this.  The two other pieces I noted are really to trigger that code, and that's fairly simple in comparison.

**Comment by dgrammatiko** [comment]
@mbabker since the installer is not tight to any b/c why not backporting the code from the J4 (with the markup/css converts back to bs2)?
Less code is always better from a maintenance point of view, I think, also the changes are not dramatic php wise

**Comment by mbabker** [comment]
The changes I've made were tied to us bumping the PHP version and the new format aware error handler.  And I haven't seen your work yet so don't know what that entails, but I wouldn't be opposed to looking at it at least.
