### ISSUE TITLE
Php message

### ISSUE THREAD

**Issue by webmasterab** [joomla/joomla-cms#17018]
### Steps to reproduce the issue
I have not taken any steps yet.
Just want to report it

### Expected result
Get on a website with PHP 7.0.7 a post install notification that the version I use is no longer supported in joomla 3.3.
That I must have the least php 5.3.10.
While I turn php 7

What can I do about it

**Comment by franz-wohlkoenig** [comment]
closed as duplicate Report #16964, see PR #16974<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17018">issues.joomla.org/tracker/joomla-cms/17018</a>.</sub>
