### ISSUE TITLE
Duplicate tag

### ISSUE THREAD

**Issue by niaziblog** [joomla/joomla-cms#17017]
### Steps to reproduce the issue

i create menu for tag 
menu url for tag is : yoursite.com/tag/tag-name
but every tag show with 2 url
yoursite.com/tag/tag-name
yoursite.com/tag/tag-id

### Expected result
<img src="http://www.imageupload.co.uk/images/2017/07/08/Capture86c77.png" alt="Capture86c77.png" border="0" />

### System information (as much as possible)

Joomla! Version | Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments

Which file should be changed in the components\com_tags folder?

**Comment by niaziblog** [comment]
Who does not have a solution for this problem?

**Comment by ghost** [comment]
can you test on 3.8?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17017">issues.joomla.org/tracker/joomla-cms/17017</a>.</sub>

**Comment by niaziblog** [comment]
yes, i test at joomla 3.8 .0 beta 4 , same this problem
every tag show with 2 url
yoursite.com/tag/tag-name
yoursite.com/tag/id

**Comment by brianteeman** [comment]
That is the expected behaviour. The same is true for everything. But Joomla will never create a link to just the if so it's not an issue.
