### ISSUE TITLE
Need a new integrated Feature: User Profile Badges

### ISSUE THREAD

**Issue by mundogame** [joomla/joomla-cms#17020]
Its near 4.0 version of Joomla, and we need a good system for Gamification to incentivate different things in our websites. This can be with a Badge System.

This system can be used by forums, modules, news and other modules or components, and add to the profiles more atractive rewards to enjoy and more visual enrichment. -Very bad now :( -

Wordpress and other systems have plugins or addons for this feature, but joomla dont have efficient things for this.

### Examples
A system for Wordpress, http://badgeos.org/about/credly-integration/

A system for Mango, https://www.mangoapps.com/help/mangoapps-9-1-release-notes

Incentivating make more things in our websites, http://www.pcworld.com/article/2047564/gamification-using-play-to-motivate-employees-and-engage-customers.html

https://www.topcoder.com/blog/why-our-community-needed-some-stinking-badges/

https://designmodo.com/gamification/

https://wplift.com/wordpress-gamification-techniques-examples-and-free-plugins

**Comment by franz-wohlkoenig** [comment]
can you do a PR against staging-Branch like @brianteeman suggested at #16973 ([comment](https://github.com/joomla/joomla-cms/pull/16973#issuecomment-313018224))?

**Comment by mundogame** [comment]
how?

**Comment by wojsmol** [comment]
@mundogame You conding this on Github or locally?

**Comment by franz-wohlkoenig** [comment]
From a search at jooml.org i found https://docs.joomla.org/Working_with_git_and_github, which looks like a starting Point. Maybe other knows better Sources – if so, please write here, thanks.

**Comment by mundogame** [comment]
If i make a pull request, only see the compare branches text, and need to choose two to continue

**Comment by wojsmol** [comment]
@mundogame I don't see joomla-cms repo fork on https://github.com/mundogame?tab=repositories - fork this repo.

**Comment by wojsmol** [comment]
@mundogame See https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests. You cen edit many files in one PR (Pull_Request).

**Comment by C-Lodder** [comment]
Why would this be put into core rather than someone just making an extension?

**Comment by mundogame** [comment]
If someone making a extension, only that extension can benefit of this feature. If a badge system can be integrated in joomla, many modules and components around the world can make adjustments to implement the feature.

For example a forum component, can add this to the profiles of the users, or a store component can add this to incentivate purchases or virtual prices. The possibilities are endless!

**Comment by C-Lodder** [comment]
There are already extensions for this, having used some of them in the past. Alpha User Points. Not sure if it's still maintained, but if I rightly remember, someone has forked it.

**Comment by mundogame** [comment]
Alpha User Points dont use a badge system, and dont have gamification mechanics. The original developer of AUP abandoned the project.

I give you another 2 examples:

- A news module or component give badges for an user, when this user read news. The badges can be personalized for types. For example if this user read many sport news, a badge can show this in the joomla profile. The user have a visual price, the webmaster know what are the prefered news of this user.

- Another example can be an advancement. The sports user win the badge of Sports level 2. With this badge unlocked, can win a Special coupon in the store with discounts. And in the Store another badge spawn for the first purchase.

We need to add more beauty for the User Profiles in joomla, and make them more modern and efficient, and a Badge System, can help to achieve this. Another systems same Mango, Drupal or Wordpress have similar things, but joomla not.

**Comment by C-Lodder** [comment]
As much as I like the idea, this should be done as a 3PE, not part of core. This would benefit sites that are used for things such as gaming communities, etc, but other than that, I can't see this being beneficial as part of the core in the slightest.

**Comment by PhilETaylor** [comment]
> this should be done as a 3PE, not part of core

Agree. 

Not every Joomla site uses Users, or User Profiles

Community Builder and others have led the way with this in the past...

**Comment by brianteeman** [comment]
Closed as this is for an extension not the core
