### ISSUE TITLE
The login-required redirect to the login page and message does not work after updating to 3.7.3

### ISSUE THREAD

**Issue by i3health** [joomla/joomla-cms#17021]
### Steps to reproduce the issue
Go to www.i3health.com
Click on any page that's restricted to registered users. Example: From CME menu, select "Lung Cancer". Then click on "Start Activity" tab

### Expected result
User is redirected to the login page: https://www.i3health.com/cb-login

### Actual result
User is redirected to https://www.i3health.com/component/comprofiler/login?Itemid=607
This is a blank/white page (see attached)
<img width="993" alt="screen shot 2017-07-07 at 3 53 22 pm" src="https://user-images.githubusercontent.com/4172565/27990121-89b24224-641a-11e7-82b2-d1f6060d66d1.png">

Note: itemid=607 is the home menu. If we delete "?itemid=607" from the URL, the login page is displayed as expected.

Also note: We have manually added a hidden login menu to the main menu. We have also added it under the Community Builder menu, where it used to be before the upgrade to 3.7.3. (The 3.7.3 upgrade somehow deleted the Community Builder menu.)

Also note: System caching is disabled.

**Comment by franz-wohlkoenig** [comment]
Thanks for reporting, but closed as duplicate Report of #15730.

@i3health You can always reopen if its a different Isssue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17021">issues.joomla.org/tracker/joomla-cms/17021</a>.</sub>

**Comment by i3health** [comment]
This is not exactly the same as #15730. Our home menu item is public.

**Comment by ghost** [comment]
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17021">issues.joomla.org/tracker/joomla-cms/17021</a>.</sub>

**Comment by tonypartridge** [comment]
This is a Community Builder issue. Please contact them. Unless you can replicate without CB installed

**Comment by tonypartridge** [comment]
Also note, your login menu item should be public. It you don't want it on the menu then under display options set to no under show in menu.

**Comment by ghost** [comment]
closed for Reasons stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17021">issues.joomla.org/tracker/joomla-cms/17021</a>.</sub>
