### ISSUE TITLE
3.7.3 breaks address info on Contact Page

### ISSUE THREAD

**Issue by mikee91** [joomla/joomla-cms#17032]
### Steps to reproduce the issue
Open Frontend Contact page, address info no longer showing.

### Expected result
Frontend Contact page, address info should be displayed

### Actual result
Frontend Contact page, address info missing

### System information (as much as possible)
In components/com_contact/views/contact/view.html.php of 3.7.2 it was using $params, but in 3.7.3 it is now using $item->params.

components/com_contact/views/contact/tmpl/default_address.php didn't get updated in 3.7.3.

In components/com_contact/views/contact/tmpl/default_address.php I have replaced all $this->params with $this->item->params and this problem is fixed

### Additional comments
components/com_contact/views/contact/tmpl/default_address.php needs to be updated.

**Comment by ghost** [comment]
Thanks for report, but this is closed as duplicate Report #16968<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17032">issues.joomla.org/tracker/joomla-cms/17032</a>.</sub>
