### ISSUE TITLE
[4.0] [a11y] Proposal remove popovers and replace with inline text

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17044]
Tooltips are a nightmare. With the current code they are completely non accessible to non-mouse users and they also can not be used on a touch device so we shouldnt rely on them.

_Not all users will see tooltips so they must not include essential information._

It is possible to correct that (see https://www.sarasoueidan.com/blog/accessible-tooltips/ or http://accessibility.athena-ict.com/aria/examples/tooltip.shtml) but do we really need to.

A tooltip or hint should not exist if it simply **_repeats_** the content of the label. It should only exist if it provides **_additional_** explanatory content. It is not intended to be a **_manual_**!!

Because of our previous desire (incorrectly) to have a tooltip for everything a large percentage of tooltips are completely **_useless_** and do not add anything. They also require translators to **_waste a lot of time_** translating strings that are not needed.

#### 100% duplicate 
```

COM_MODULES_FIELD_CONTENT_DESC="Text"
COM_MODULES_FIELD_CONTENT_LABEL="Text"
```

#### Not required

```
COM_MODULES_FIELD_CLIENT_ID_DESC="The location of the module, Frontend or Backend. You can't change this value."
COM_MODULES_FIELD_CLIENT_ID_LABEL="Module Location"

```
### EXAMPLE
As can be seen on the screenshot below which exposes the tooltips three of the four on that page are completely redundant and can be removed
![menus edit item joomla4 administration](https://user-images.githubusercontent.com/1296369/28012543-092957ec-655e-11e7-84a5-5e464176b55a.png)

### PROPOSAL
Tooltips are removed and replaced with inline hints ONLY where needed

#### Workflow

- Step 1 - change tooltips to inline hints so we can see what is needed
- Step 2 - remove all duplicate labels and unrequired labels
- Step 3 - check all the hints that are really long help manuals and not hints
- Step 4 - decide on the best design layout for the hints

**Comment by C-Lodder** [comment]
Part 1: https://github.com/joomla/joomla-cms/pull/17050

**Comment by brianteeman** [comment]
#17050 is for tool tips and I actually meant the grey popovers

**Comment by wilsonge** [comment]
I'm largely down with this. I mean let's see how many useful tooltips are left and whether they can go in line. But massive :+1: on removing all the many redundant tips
