### ISSUE TITLE
TinyMCE drag&drop upload plugin javascript error

### ISSUE THREAD

**Issue by ztj1993** [joomla/joomla-cms#17041]
Note: the following is about software translation!

### Steps to reproduce the issue
Create a new article
Upload and upload a picture (Note: dragdrop upload)
Drag and drop again to upload the same picture (same file name)
Javascript,: Error:Uncaught, ReferenceError:, setCustomDir, is, not, defined

### Expected result
Prompt file exists or rename file

### Actual result
Javascript Error: Uncaught ReferenceError: setCustomDir is not defined

### System information (as much as possible)
Joomla 3.7 +
Actual test: Joomla 3.7.2，Joomla 3.7.3

### Additional comments
https://github.com/joomla/joomla-cms/blob/staging/media/editors/tinymce/js/plugins/dragdrop/plugin.js  line 40

**Comment by wojsmol** [comment]
cc: @dgt41 - Joomla! js master :)

**Comment by AlexRed** [comment]
I can confirm the problem
![js-error](https://user-images.githubusercontent.com/1362388/28011057-f3fb8a52-6558-11e7-8c3b-5a5997c98309.png)

**Comment by dgrammatiko** [comment]
will check it later on today

**Comment by dgrammatiko** [comment]
@ztj1993 @AlexRed @wojsmol please test #17063

**Comment by dgrammatiko** [comment]
Closing here please test the PR #17063<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17041">issues.joomla.org/tracker/joomla-cms/17041</a>.</sub>

**Comment by ghost** [comment]
closed as havin PR #17063<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17041">issues.joomla.org/tracker/joomla-cms/17041</a>.</sub>
