### ISSUE TITLE
Feature Request: Integrated User Profile Badges

### ISSUE THREAD

**Issue by mundogame** [joomla/joomla-cms#17049]
Its near 4.0 version of Joomla, and we need a good system for Gamification to incentivate different things in our websites. This can be with a Badge System.

This system can be used by forums, modules, news and other modules or components, and add to the profiles more atractive rewards to enjoy and more visual enrichment. -Very bad now :( -

Wordpress and other systems have plugins or addons for this feature, but joomla dont have efficient things for this.

### Examples
A system for Wordpress, http://badgeos.org/about/credly-integration/

A system for Mango, https://www.mangoapps.com/help/mangoapps-9-1-release-notes

Incentivating make more things in our websites, http://www.pcworld.com/article/2047564/gamification-using-play-to-motivate-employees-and-engage-customers.html

https://www.topcoder.com/blog/why-our-community-needed-some-stinking-badges/

https://designmodo.com/gamification/

https://wplift.com/wordpress-gamification-techniques-examples-and-free-plugins

**Comment by ghost** [comment]
can you please explain the Difference between this Issue and #17020?

**Comment by brianteeman** [comment]
As commented in #17020 all those examples are "addons" and not part of the core distribution

**Comment by PhilETaylor** [comment]
This is nothing more then a duplicate, exactly, of the opening text of #17020 - someone should close this.

**Comment by brianteeman** [comment]
Closed as this is for an extension not the core
