### ISSUE TITLE
Module Chrome in Admin

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17054]
The available module stylesare always being pulled from the front end template

For an admin template it should be being pulled from the /adinistrator/templates folder

This is because there is no check for SITE/ADMIN and a switch path here 
https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/form/field/chromestyle.php#L72
 
<img width="348" alt="screenshotr15-38-11" src="https://user-images.githubusercontent.com/1296369/28023956-48e066ea-6587-11e7-984e-173e673abefb.png">

**Comment by ghost** [comment]
closed as having PR #17057<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17054">issues.joomla.org/tracker/joomla-cms/17054</a>.</sub>
