### ISSUE TITLE
REGRESSION: com_tags issue with plugin System - Language Filter

### ISSUE THREAD

**Issue by mino182** [joomla/joomla-cms#17053]
### Steps to reproduce the issue

- change com_tags option "Language Filter" to "Current"
- Open single tag view to see articles with selected tag
- change frontend language
- you can change language to any, still same articles are displayed, like you didn't change language

### Expected result

- articles in single tag view should change depend on selected language.

### System information (as much as possible)

Joomla 3.7.3

### Additional comments

Problem is in file "plugins/system/languagefilter/languagefilter.php". If I replace changes from PR #12306 to code from Joomla 3.7.2 problem disappears.

Thanks.

**Comment by tonypartridge** [comment]
Confirm not working.

**Comment by infograf768** [comment]
> Problem is in file "plugins/system/languagefilter/languagefilter.php". If I replace changes from PR #12306 to code from Joomla 3.7.2 problem disappears.

Do you mean just reverting the part in the languagefilter plugin or the whole PR?

**Comment by infograf768** [comment]
@andrepereiradasilva 
This looks rather urgent as beta is to be released today.

**Comment by ghost** [comment]
set Priority in Issue Tracker on "Urgent".

**Comment by tonypartridge** [comment]
I think com_tags just needs bought up to date with JSession. Better for @redutz to review

**Comment by mino182** [comment]
@infograf768 I mean reverting just part of languagefilter.php

**Comment by infograf768** [comment]
Let's see what @rdeutz says.
If this can't be solved in com_tags, we may revert the part concerning the languagefilter.

**Comment by rdeutz** [comment]
I will let this open and make the beta release, next week we have a RC1 and we have time to fix it meanwhile.

**Comment by infograf768** [comment]
My test here show that if we set the languagefilter plugin Cookie Lifetime to Year, it works fine.
It breaks when set to Session.

**Comment by infograf768** [comment]
Will make a patch modifying that part of languagefilter (while keeping some improvement there)
When the language filter is set to session, com_tags (and possibly some other 3pd extensions) is not fetching that specific cookie setting.
It is imho the easiest way to solve the issue.

**Comment by infograf768** [comment]
In fact, the problem was in the helpers.
Please test https://github.com/joomla/joomla-cms/pull/17084

@mino182
@tonypartridge
