### ISSUE TITLE
[4.0] Batch modal close

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17068]
it is not possible to close a batch modal using either the cancel button or the x in the top right hand side

**Comment by ghost** [comment]
Can't confirm, both works. Test on "Users".
### System information
4.0.0-dev
macOS Sierra, 10.12.5
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
This is unfortunately yet another bug in BS4.

**Comment by brianteeman** [comment]
@C-Lodder are you sure its a bs4 issue. As @franz-wohlkoenig says it works fine with com_users but doesnt work with com_content
Also I just retested it with bs4 beta and no change

**Comment by C-Lodder** [comment]
My bad, probs wrong issue.

Here's a PR anyway: https://github.com/joomla/joomla-cms/pull/17564

**Comment by ghost** [comment]
closed as having Pull Request #17564<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17068">issues.joomla.org/tracker/joomla-cms/17068</a>.</sub>
