### ISSUE TITLE
[4.0] tooltip removals and html in strings

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17067]
With #17050 by @c-lodder removing the tooltips we not have just a regular title tag.

However this means that where they exist they can not have html in the language string. Its bad practice anyway so they will need to be removed.

### Example

![title](https://user-images.githubusercontent.com/1296369/28066634-a82eaedc-6635-11e7-9ee8-d4dbdbebf009.gif)

**Comment by brianteeman** [comment]
Turns out not to me html in strings but two strings being output together

JLIB_HTML_BATCH_LANGUAGE_LABEL="Set Language"
JLIB_HTML_BATCH_LANGUAGE_LABEL_DESC="Not making a selection will keep the original language when processing."

@C-Lodder can you take a look please

**Comment by ghost** [comment]
reminder @C-Lodder <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17067">issues.joomla.org/tracker/joomla-cms/17067</a>.</sub>

**Comment by C-Lodder** [comment]
So we just nees to remove the HTML markup from the strings?

**Comment by infograf768** [comment]
code in staging (or 4.0) is
```
JHtml::_('tooltipText', 'JLIB_HTML_BATCH_LANGUAGE_LABEL', 'JLIB_HTML_BATCH_LANGUAGE_LABEL_DESC')
```
strings do not contain html markup

**Comment by brianteeman** [comment]
Sorry I forgot i had opened this. There is a better issue describing the problem area here #17255
