### ISSUE TITLE
System Info Folder permissions gets the configuration file wrong?

### ISSUE THREAD

**Issue by Paladin** [joomla/joomla-cms#17076]
### Steps to reproduce the issue

1) Go to System->System Information in the administrator area
2) click Folder Permissions Tab
3) See configuration.php listed as "unwriteable"
4) Go make any system config change that changes that file.
5) Verify change has happened. (thus proving the file was in fact writeable)

### Expected result

Correct permission would be displayed ("writeable" since my configuration file is writeable)

### Actual result

"Unwriteable" is displayed

### System information (as much as possible)

Joomla 3.7.3
Centos 7.3
Apache 2.4.6
PHP 5.6.30 using apache2handler

### Additional comments

Hadn't noticed this earlier, so no idea when it happened. It has no effect on operation; its worst effect is user confusion, making someone think the configuration file isn't writeable when it is. From a quick scan of the code, it's quite possible this is an upstream bug in PHP itself, which might impact whether the permission for that file is even listed.

**Comment by richard67** [comment]
This is by design, as far as I know and experienced. The configuration.php is set to writeable with a chmod before saving the changes, and after saving it is set to readonly again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17076">issues.joomla.org/tracker/joomla-cms/17076</a>.</sub>

**Comment by Paladin** [comment]
That only happens on some systems, apparently. I see permissions of 644 with this file on a lot of systems. It's not world writeable, but it's still writeable by apache. For example, this comes from one system:

$ ls -alh configuration.php
-rw-r--r--. 1 _redacted_ _redacted_ 3.3K Jul 11 16:46 configuration.php

Yet the sysinfo permissions page says unwriteable.

**Comment by richard67** [comment]
Does it happen on shared hosts only, or also on dedicated servers?
On shared host it could be that web server user and ftp user (which is the one also used when accessing command line with SSH) are not the same. So maybe in Joomla you see the result of the check for the group permissions.

**Comment by Paladin** [comment]
The example I cited above came from a dedicated server. When I looked at the code, nothing jumped out at me that was "wrong," (if it had, I'd have appended a PR to fix it) hence my suggestion the bug may be upstream in PHP itself or in mod_php, or an artifact of the way my mpm_prefork workers are set up. From your response, I gather you've seen it as "unwriteable" before as well, so at least it's not only me seeing it.

**Comment by Schmidie64** [comment]
I could reproduced the "Bug" by changing the offline message on the Webside. The changes override the writing permissions on the Server. I tested it on my Localserver and on a other "real" Server same result. Maybe the changes on the side override the permissions on the Server. 
@Icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17076">issues.joomla.org/tracker/joomla-cms/17076</a>.</sub>

**Comment by richard67** [comment]
@Paladin @Schmidie64 Is this still an issue with Joomla! 3.9.6?

**Comment by Quy** [comment]
Closing due to no response.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17076">issues.joomla.org/tracker/joomla-cms/17076</a>.</sub>
