### ISSUE TITLE
Invalid PSR-4 loader implementation

### ISSUE THREAD

**Issue by ethernidee** [joomla/joomla-cms#17098]
### Steps to reproduce the issue
```
JLoader::registerNamespace('B', JPATH_SITE . '/libraries/app/vendor/B/src', $reset = true, $prepend = false, $type = 'psr4');
\B\B::anyMethod();
```
### Expected result

Autoloading \B\B class and calling anyMethod.

### Actual result

Class not found.

### Additional comments

File: libraries/loader.php

1. `if (strpos($class, $ns) === 0)` is not enough, there can be two namespaces AAA and AAAB, both starting with 'AAA'. Valid check is:
```
$nsLen = strlen($ns);

if (strpos($class, $ns) === 0 && isset($class[$nsLen]) && $class[$nsLen] === DIRECTORY_SEPARATOR)
```

2. `$classFilePath = $path . DIRECTORY_SEPARATOR . str_replace($nsPath, '', $classPath);`
It's totally wrong to replace namespace name in fully qualified class name. Consider \Apple\AppleBridge\AppleNice\AppleClass

Valid behavior is to strip only leading namespace part:
```
$classFilePath = $path . DIRECTORY_SEPARATOR . substr($classPath, $nsLen + 1);
```

**Comment by laoneo** [comment]
Guess this one can be closed as we have a pr.
