### ISSUE TITLE
[4.0] Updates available

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17093]
<img width="268" alt="screenshotr14-29-53" src="https://user-images.githubusercontent.com/1296369/28119993-a6cef7d4-670e-11e7-9f44-a951fd3fabcf.png">

Should there be some styling on the number of updates available as right now its kind of lost with the text @ciar4n

**Comment by AMurray2016** [comment]
Assume you mean something like the bootstrap "badge" style, something suitable to the admin template.
http://getbootstrap.com/components/#badges<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17093">issues.joomla.org/tracker/joomla-cms/17093</a>.</sub>

**Comment by ciar4n** [comment]
Good point.. something certainly needed here. Possibly a badge as suggested by @AMurray2016

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/19002

**Comment by ghost** [comment]
closed as having Pull Request #19002
