### ISSUE TITLE
[4.0] Error on com_content

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#17090]
### Steps to reproduce the issue

Go to the Article Manager and you will get the following error:

> Notice: Undefined variable: dataShowOn in C:\dev\joomla4\layouts\joomla\searchtools\default.php on line 82

Being caused by: https://github.com/joomla/joomla-cms/commit/06fe3145b44c05f3706c6bc39686d6f721afcf75#diff-7fc57bb3a5e5ed4c711d5ea9fe03a5cfR82

@ciar4n can you take a look please?

The "Table Options" button should also be a different colour (perhaps blue) when there are any active filters.

**Comment by ciar4n** [comment]
This issue is resolved with #17097

'Table Options' should now appear blue if any filters are active?

**Comment by brianteeman** [comment]
Closed
