### ISSUE TITLE
[4.0] Article-View: Mouse-over Status shows `<br>`

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#17092]
### Steps to reproduce the issue
Open Article-View, hover Status-Icon, get:
![bildschirmfoto 2017-07-12 um 15 08 19](https://user-images.githubusercontent.com/8235763/28119286-921eb03a-6714-11e7-89d9-8cb55de963b2.jpg)
### System information
4.0.0-dev
macOS Sierra, 10.12.5
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
Known issue and already reported on one of my open issuess
