### ISSUE TITLE
routing issue add article

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#17096]
### Steps to reproduce the issue
1. create a link or button on a page with the following link:
<?php echo JRoute::_('index.php?option=com_content&view=form&layout=edit&return=' . base64_encode($uri), false); ?>
2. create a menu entry for create article e.g. new-article (alias)

### Expected result
When clicking the link or button to create the new article the edit form (empty article) should be shown on the menu entry page new_article
or, if that menu is not set on the view the button was pressed on.

url in browser > [mydomain]/new-article

### Actual result
The edit form (empty article) is opened on the frontpage of the website. Thus showing all frontpage active module positions.

url in browser >[mydomain]/?view=form&layout=edit

When you have for the frontpage a main_body position active (that displays a module instead of content, then the edit form is not shown at all (it shows the main_body module)

### System information (as much as possible)
Database Version 	        5.6.36-82.0-log
Database Collation 	        utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	                7.0.21
Web Server 	                Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	        Joomla! 3.7.3 Stable [ Amani ] 4-July-2017 08:03 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	                Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0 

### Additional comments
Editing an article does work correct as this gets 'routed' to the category name.
url in browser >[mydomain]/categorymemuname?view=form&layout=edit
clicking the menu item new_article also works correct as this routes to [mydomain]/new_article where no modules are active.
I have tried to not use the return= part of the link, but that makes no difference

**Comment by Ruud68** [comment]
humm, logic got stripped >
![screen shot 2017-07-12 at 14 54 04](https://issues.joomla.org/uploads/1/fc666496ab83e465699ceed132d758c9.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17096">issues.joomla.org/tracker/joomla-cms/17096</a>.</sub>

**Comment by Ruud68** [comment]
Okay, just came back from holidays and used my renewed energy level to dive into this issue....
fixed it for my use case by using a different url:

this was the one I 'copied' from the com_content component (add article menu entry):
```
<?php echo JRoute::_('index.php?option=com_content&view=form&layout=edit&return=' . base64_encode($uri), false); ?>
```

The new one I use now (below) correctly routes to the Add new article menu (when created)). Problem solved :)
```
<?php echo JRoute::_('index.php?option=com_content&task=article.add&Itemid=' . $menuId . '&return=' . base64_encode($uri), false); ?>
```

posting here for future reference :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17096">issues.joomla.org/tracker/joomla-cms/17096</a>.</sub>

**Comment by ghost** [comment]
closed as Problem solved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17096">issues.joomla.org/tracker/joomla-cms/17096</a>.</sub>
