### ISSUE TITLE
[4.0] Merge conflicts

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17099]
there is a merge conflict that has been committed in
**installation\sql\postgresql\joomla.sql**

**Comment by brianteeman** [comment]
@wilsonge

**Comment by brianteeman** [comment]
For reference the line is https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/sql/postgresql/joomla.sql#L495

**Comment by wilsonge** [comment]
Thankyou! I'll try and figure out what's changed over the weekend!

**Comment by wilsonge** [comment]
Fixed :)

**Comment by brianteeman** [comment]
Thank you
