### ISSUE TITLE
Joomla Debug mode defaults

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#17103]
I think it would be good practice to start setting Joomla! Debug mode to registered visibility as a default, an example shows just be googling we can find lots of sites with it left enabled to the public. 

Maybe even show a notice on login dashboard, warning Debug mode is enabled.

Thoughts?

**Comment by mbabker** [comment]
Please keep in mind there are behavioral differences between when a guest user is on the site versus an authenticated user.  So this adds another layer of complexity to turning on the tool to do something that most are going to need to use in an unauthenticated context.

**Comment by tonypartridge** [comment]
I appreciate that, so why not add a notice in red it's left enabled within the dashboard? Only once on login. Even on the frontend announce a system message when it's a Joomla! Super user?

**Comment by ggppdk** [comment]
Specially for guest can an extra requirement be added?
Like a URL (variable) passphrase , that will be different per site be used to activate the console for a guest ?

The passphare will appear at the dashboard next to the enable debug parameter

Thus in order for a visitor to see the Debug console both the enable debug parameter and the passphrase
will be required

Furthermore besides the above, the enable debug parameter could be changed to:
No / Yes / Logged users

**Comment by ggppdk** [comment]
I forgot to mention that the URL (variable) passphrase , will only be needed once per session, the frontend guest user should only need to specify it once per session

**Comment by tonypartridge** [comment]
This could be added as a config option but not by default

**Comment by brianteeman** [comment]
I dont see the benefit of this - debug mode should not be enabled unless in exceptional circumstances anyway which should always be extremely short term

**Comment by tonypartridge** [comment]
The point being @brianteeman is that it's left enabled by user error. A notice in the admin area that it is enabled for instance would be good, to remind these users.

**Comment by brianteeman** [comment]
A notice in the admin showing that debug is enabled is ok although you would have to be fairly unobservant not to have noticed it anyway

**Comment by tonypartridge** [comment]
That's all relative to the user in question; they may not know it's enabled to the public for a start? Or the pages are so long they don't notice it at the bottom.

**Comment by brianteeman** [comment]
#ycfs

**Comment by brianteeman** [comment]
Seriously though a notice is fine but limiting it to certain usergroups is not going to work as that would require you to login and the majority of web sites do not have a front end login

**Comment by tonypartridge** [comment]
You can already limit to certain access. I was suggesting we did it by default.

I'll do a pull for a post login message to be output in a warning state to super users only.

**Comment by brianteeman** [comment]
Closing. No point in keeping it open any longer. All views have been expressed.
