### ISSUE TITLE
[4.0] Flying focus bug

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17100]
If you look you will see it is being duplicated five times - that line should only be present once

<img width="646" alt="screenshotr19-40-13" src="https://user-images.githubusercontent.com/1296369/28134163-08875f18-673a-11e7-8268-c803fce1b8be.png">

**Comment by dgrammatiko** [comment]
Confirmed

**Comment by dgrammatiko** [comment]
@brianteeman adding 
```js
			if (document.getElementById('flying-focus')) {
				return;
			}
```
after line 62 solves the problem. Probably @C-Lodder needs to patch this in the respected repo and publish a new version and then pull it in

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/17200
