### ISSUE TITLE
Casting to (float) result in a locale aware floating-point number.

### ISSUE THREAD

**Issue by gitlae** [joomla/joomla-cms#17114]
### Steps to reproduce the issue
Run Joomla on a host system with a non US locale, for example 'swedish'.
Create/Open an article and save it.

### Expected result
Silently save article.

### Actual result
com_finder will generate "Column count doesn't match value count at row 1" (Error Code: 1136.)

### System information (as much as possible)
Database Version 	5.5.55-cll
Database Collation 	latin1_swedish_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.6.16
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.7.3 Stable [ Amani ] 4-July-2017 08:03 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 

### Additional comments
Reason is that just casting a value to (float) will generate a locale aware floating-point number.
In Swedish ',' is used for decimal separation (3,14) and that will not work in an SQL statement.
 
[com_finder_sql_float_cast.patch.txt](https://issues.joomla.org/uploads/1/57fff111d19b19776261babe45f7488d.txt)Applied patch will at least fix the problem, might not be the perfect solution but it works for me :)

**Comment by ghost** [comment]
@Maintainers is this a Solution?

@gitlae can you make a PR (how to make a [Pull Request](https://docs.joomla.org/Filing_bugs_and_issues#Issue_a_pull_request_directly_on_Joomla.21.27s_GitHub_repository))?

**Comment by gitlae** [comment]
I have created a pull request https://github.com/joomla/joomla-cms/pull/17345.
The patch differ from the original due to recent code refactoring. 

This is my first PR so bare with me if something is not perfect :)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17114">issues.joomla.org/tracker/joomla-cms/17114</a>.</sub>

**Comment by ghost** [comment]
closed as having PR #17345.

@gitlae Thanks for contributing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17114">issues.joomla.org/tracker/joomla-cms/17114</a>.</sub>
