### ISSUE TITLE
[4.0] com users mootools

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17111]
the batch modal in com_users still has code testing for mootools

**Comment by dgrammatiko** [comment]
@brianteeman do you mean this part:
```php
 $isMoo = $input->getInt('ismoo', 1);
  
  if ($isMoo)
  {
      $onClick = "window.parent.jSelectUser(this);window.parent.jQuery('.modal.in').modal('hide');";
  }
```

**Comment by brianteeman** [comment]
No I mean this 
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_users/views/users/tmpl/modal.php#L31

and similar calls in that file

**Comment by C-Lodder** [comment]
I can submit the PR to remove the Mootools  check, but there still 1 issue. 

New Article >> Publishing Options >> Created By  (try selecting a user)

Getting 2 console log errors. 1 being from `multiselect.js` which I don't seem to understand why it's there, as it's used for the checkboxes on list views.

**Comment by C-Lodder** [comment]
This PR removes the Mootools reference right?

https://github.com/joomla/joomla-cms/pull/17763

**Comment by ghost** [comment]
@brianteeman i guess @C-Lodder ask you.

**Comment by brianteeman** [comment]
Correct it willbe fixed if that gets merged
