### ISSUE TITLE
[4.0] 'Table Options' needing 'Clear' button

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#17112]
### Steps to reproduce the issue
Since moving the 'Search Tools' to a 'Table Options' dropdown we no longer have a way to clear the filters. Originally this was done by clicking the clear option on the search field. Personally I would suggest a second clear button in the dropdown to clear the filers within the dropdown...

![tableoptions-clear](https://user-images.githubusercontent.com/2803503/28171054-2d49428a-67df-11e7-911a-2d7420ca798e.png)

**Comment by ghost** [comment]
Issue confirmed.

**Comment by brianteeman** [comment]
seems a good idea

**Comment by tonypartridge** [comment]
Does this not get a bit confusing? Should the clear on the main block auto clear them all, then the clear on the drop down clear just them?

**Comment by brianteeman** [comment]
> Originally this was done by clicking the clear option on the search field.
That works again so do we still need a second clear button?

**Comment by ciar4n** [comment]
I guess not. Closing.
