### ISSUE TITLE
3.7.4 b1 cant install language

### ISSUE THREAD

**Issue by c3ph3us** [joomla/joomla-cms#17115]
fresh install 

![przechwycenie obrazu ekranu_2017-07-13_18-14-25](https://user-images.githubusercontent.com/10565704/28176342-4ac603d0-67f7-11e7-9927-a19f7c0e5952.png)

related:
https://github.com/joomla/joomla-cms/issues/17116

**Comment by c3ph3us** [comment]
pleas add some info that this is a file permission issue! 
better add detect and a ERROR MESSAGE on main backend page 
that  JOOMLA PERMISSION ARE NOT SET CORRECTLY !!!

**Comment by zero-24** [comment]
Can you please explain what the issue was? I have no idea what you mean. Thank you.

**Comment by c3ph3us** [comment]
@zero-24  proper permission (in this case owner) on "NIX" filesystem for joomla CMS files are not set 
cms is installing and is working after install (but not proper because of missing file permissions) 

eg for www-data apache etc 

> chmod www-data:www-data -R   {path to cms here}/

**Comment by infograf768** [comment]
The error may not be due all the time to a permissions problem.
