### ISSUE TITLE
Changed layout for page break after Joomla 3.7.3 upgrade

### ISSUE THREAD

**Issue by eriknzzz** [joomla/joomla-cms#17127]
I noted a significant change to the effect of a page break after the Joomla 3.7.3 upgrade.
I am writing articles with extensive use of the page break (using JCE editor). After the upgrade the browser page header shows the current page title with the page number. In the article the page title is appended to the article title. 
Previously the browser page header only showed the article title for any page and the article title was left alone (as it should in my view).
Since the upgrade I now have two different layouts for the page break and do not seem able to do anything about that.

### Steps to reproduce the issue
Demo: this Article was created with Joomla 3.7.2 [http://ngawhetu.nz/index.php/our-resources/ebooks/93-ngawhetu/cat-ebooks/124-the-rhythmic-sky]

To show that it is a Joomla issue I have temporarily added another page break “xtra pagebreak” after the Joomla upgrade. You can see the difference in browser page title (tab text) and the article title for all pages (3.7.2) and the xtra one with 3.7.3.

Any new articles I am writing have of course this new “layout” for the page break (e.g. this article [http://ngawhetu.nz/index.php/our-resources/ebooks/93-ngawhetu/cat-ebooks/128-matariki] .

### Expected result
Article title in the browser page title and in the article header for each page (as with 3.7.2)

### Actual result
Page title and page number in the browser page title and page title appended to the article title on every page (as with 3.7.3).

### System information (as much as possible)
Joomla 3.7.2 versus Joomla 3.7.3
JCE editor PRO 2.6.16

### Additional comments
Any suggestions to fix this or do I have to wait for the Joomla team to fix this by the next upgrade?

**Comment by infograf768** [comment]
The code has been there for ages, i.e. it was not changed in 3.7.3
See https://github.com/joomla/joomla-cms/blob/staging/components/com_content/views/article/view.html.php#L322-L329

**Comment by eriknzzz** [comment]
Thanks infograf768. But can you then explain why the different behaviour in 3.7.2 and 3.7.3? Or is there a way to control this?

**Comment by eriknzzz** [comment]
Upgrade to Joomla 3.7.4 did not change anything to THIS issue. I would appreciate some suggestions. This has nothing to do with 404 errors.

**Comment by brianteeman** [comment]
Are you creating the page breaks with the Joomla!la plugin or the jce tool? Have you tried using the Tony!CE editor to see if the same!e thing happens

**Comment by eriknzzz** [comment]
I use the JCE editor toolbar item to insert the pagebreak, but I thought this used the Joomla plugin. Never had any issues with JCE and am not keen to change as I am using it for several websites. But if all fails I might try another editor. Still I have no idea why this issue suddenly came up after the previous Joomla upgrade. I also wonder why no one else seems to have this issue. Is it so rare to use page breaks?

**Comment by N6REJ** [comment]
This has nothing to do with pagebreak from what I see..  the matariki is a page header .  Your article layout has changed.  I suspect a template upgrade occurred.
![image](https://user-images.githubusercontent.com/1850089/28702156-c52002a0-7320-11e7-8ec2-f6bb04603e96.png)

**Comment by eriknzzz** [comment]
https://github.com/N6REJ thank you very much! You are probably right. I will investigate. I blamed Joomla because the new layout also occurred when editing a previous article. But of course this looks like a local issue. Thanks a lot mate! I appreciate.

**Comment by eriknzzz** [comment]
The solution turned out to be simple. In the hr tag the title attribute must not appear before the class attribute. I use the page-break command from the JCE toolbar, which causes this issue.
