### ISSUE TITLE
[4.0] menus missing selects

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17121]
At some point we lost the ability to switch between site/admin and to select the menu to list as seen below in j3

<img width="545" alt="screenshotr20-23-17" src="https://user-images.githubusercontent.com/1296369/28183919-3a2164c2-6809-11e7-901d-c911c00ab36b.png">

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17121">issues.joomla.org/tracker/joomla-cms/17121</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a PR #17630
