### ISSUE TITLE
Not showing street address with com_contact after update

### ISSUE THREAD

**Issue by davidspeijer** [joomla/joomla-cms#17131]
### Steps to reproduce the issue
Updating from Joomla 3.6.5 to 3.7.3

### Expected result
Showing the address like before

### Actual result
Not showing the address

### Additional comments
The problem is a result of a bad check at line 18/19 of /components/com_contact/views/contact/tmpl/default_address.php what isn't returning a result so the if is always negative.

<?php if ((**$this->params->get('address_check') > 0**) &&
($this->contact->address || $this->contact->suburb  || $this->contact->state || $this->contact->country || $this->contact->postcode)) : ?>

**Comment by eshiol** [comment]
Please, try to replace the line 335 in /components/com_contact/views/contact/view.html.php from
`$this->params      = &$params;`
to
`$this->params      = &$item->params;`

**Comment by davidspeijer** [comment]
This is solving the issue.

**Comment by zero-24** [comment]
As this is included in 3.7.4 (see: https://github.com/joomla/joomla-cms/pull/16971) which is planed to be released at 25.07.2017 I'm going to close here. Thanks for reporting.
