### ISSUE TITLE
[J4.0] Table options breaks large custom filters

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#17138]
### Steps to reproduce the issue
Create another filter than dropdown (input + label or an custom field) like:
![grafik](https://user-images.githubusercontent.com/1229869/28231427-bef62b1e-68eb-11e7-86f2-6c20193de3ce.png)

The filter breaks.

**Comment by brianteeman** [comment]
wouldnt that break the existing filter anyway?

Please can you be more precise about what you mean by "breaks"

**Comment by brianteeman** [comment]
I am closing this as there has been no reply and there is nothing useful in the original comment. It can always be reopened if updated
