### ISSUE TITLE
[4.0] Admin modules select position bug +

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#17132]
1. Only the frontend positions are displayed in the "Table  Options" => Positions.
![screen shot 2017-07-14 at 12 38 13](https://user-images.githubusercontent.com/869724/28209275-1a718dda-6892-11e7-82a8-10b8f355b206.png)

2. Not all modules display in the "Status" position
User, Joomla Version, etc,

3. Some displays twice (multilingual status)
![screen shot 2017-07-14 at 12 42 16](https://user-images.githubusercontent.com/869724/28209236-f09b304c-6891-11e7-8194-3fffd829ab62.png)

**Comment by C-Lodder** [comment]
3. To prevent duplicates, multilingual stats needs to be published but not assigned to a position. I did this so that the ordering didn't need to be changed

**Comment by infograf768** [comment]
@C-Lodder 
Still concerning 3.
Impossible to set back the module to "None" position.
![screen shot 2017-07-15 at 07 42 41](https://user-images.githubusercontent.com/869724/28237076-53e30e36-6937-11e7-938f-27766e475a06.png)

IN 3.7.x we can delete the position:
![screen shot 2017-07-15 at 08 29 09](https://user-images.githubusercontent.com/869724/28237106-c2417390-6937-11e7-8ff4-66ca3872207e.png)


I had to delete the modue and try to recreate.
In that case, it is also impossible to save as I get this message
```
Error
Save failed with the following error: Field 'language' doesn't have a default value
```
![screen shot 2017-07-15 at 07 46 37](https://user-images.githubusercontent.com/869724/28237074-4acc091a-6937-11e7-8de1-ccfba45132e9.png)

**Comment by infograf768** [comment]
We have other issues concerning com_modules:
Select "Options"
Result:
```
[15-Jul-2017 10:03:44 Europe/Berlin] PHP Warning:  Creating default object from empty value in /Applications/MAMP/htdocs/testnew/joomla_400/libraries/src/CMS/Helper/ModuleHelper.php on line 204
```

**Comment by brianteeman** [comment]
Closing this issue - there are multiple different issues reported here. As far as I can tell they have all been resolved but if not then please create a new issue for each one.
