### ISSUE TITLE
[4.0] com_users needs some love

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17130]
When you have notes and password reset required etc all showing the list view is a bit ugly

Not sure why we need to have both the 
Show Notes list and the Modal links

Perhaps it can be reduced to just one and restyled similar to the new edit icon? @ciar4n @C-Lodder 

<img width="494" alt="screenshotr09-58-42" src="https://user-images.githubusercontent.com/1296369/28205751-415346d0-687b-11e7-980b-abc20c147f97.png">

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/17152
