### ISSUE TITLE
[4.0] remove https force options

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17142]
In J4 there really should be no need for offering an option to force https. There is no excuse anymore for not having your entire web site on https. By keeping this option (and the code to support it) we are saying its ok to have just part of your site on https when it really isnt.

**Comment by tonypartridge** [comment]
Whilst I agree with what you are saying about all sites should be on https..... I have to disagree with this.

Building a localhost site for instance will require http in 90% of cases or you add an invalid self signed cert etc. All of which is still quite complicated for anyone to add in.

**Comment by mbabker** [comment]
We can't make Joomla HTTPS only, that's out of the question.  But any option we have which makes selected pages/sections forced HTTPS could be removed except for the one global option to force HTTPS everywhere (just to help those who can't edit .htaccess on their own).

**Comment by tonypartridge** [comment]
I agree with this @mbabker , and thus reducing clutter 😎

**Comment by brianteeman** [comment]
Closed see #17288
