### ISSUE TITLE
issues when entering dates manually in persian calendar

### ISSUE THREAD

**Issue by farhadst** [joomla/joomla-cms#17150]
### Steps to reproduce the issue
entering dates manually in persian calendar 

### Expected result
We expect the entering manually date to be saved correctly like set by calendar popup

### Actual result
but after save it, in some months, one day will be added or one day will be reduced in set time
[#16922(comment)](https://github.com/joomla/joomla-cms/pull/16922#issuecomment-312477460)

### System information (as much as possible)
joomla 3.7.3

**Comment by infograf768** [comment]
@dgt41 
Let's try again. Why would it work fine when using the popup and not when entering manually?

**Comment by brianteeman** [comment]
This is not an issue with the persian calendar - it is an issue with the entire calendar - see #17171

**Comment by infograf768** [comment]
It may be specific to Jalali as the issue concerns the correct persian date.
@farhadst 
Please test.
https://github.com/joomla/joomla-cms/pull/17183

**Comment by infograf768** [comment]
My test with https://github.com/joomla/joomla-cms/pull/17183 looks like it does not solve the jalali issue. Not using the popup but directly editing the field may add a number of days depending on the month.

**Comment by dgrammatiko** [comment]
@infograf768 ok I am doing something stupid there, I try to parse the date but the date is not an object but rather a simple array of numbers :(

This should fix the Jalali calendar (around line 1014
```js
							// We need to transform the date for the data-alt-value
							var mdate = new Date(), ndate, date = Date.parseFieldDate(calObj.inputField.value, calObj.params.dateFormat, calObj.params.dateType);
							ndate = Date.localCalToGregorian(date.getFullYear(), date.getMonth(), date.getDate());
							mdate.setFullYear(ndate[0]);
							mdate.setDate(ndate[2]);
							mdate.setMonth(ndate[1]);
							calObj.inputField.setAttribute('data-alt-value', mdate.print(calObj.params.dateFormat, 'gregorian', false));
```

Let me know if this solves the problem

**Comment by infograf768** [comment]
@dgt41 
It does!.

Therefore combining https://github.com/joomla/joomla-cms/pull/17183 and your proposal would solve the issue for me.

**Comment by farhadst** [comment]
@infograf768 @dgt41 
sorry but this change code in media/system/js/fields/calendar.js Has no effect on the problem (manually set persian date)

**Comment by dgrammatiko** [comment]
@farhadst strange, did you also applied https://github.com/joomla/joomla-cms/pull/17183?

PS. I think there is a small bug in the above snippet, there shouldn't be a new `mdate` variable, as that will reset the time to now, this should be the correct one:
```js

// We need to transform the date for the data-alt-value
							var ndate, date = Date.parseFieldDate(calObj.inputField.value, calObj.params.dateFormat, calObj.params.dateType);
							ndate = Date.localCalToGregorian(date.getFullYear(), date.getMonth(), date.getDate());
							date.setFullYear(ndate[0]);
							date.setDate(ndate[2]);
							date.setMonth(ndate[1]);
							calObj.inputField.setAttribute('data-alt-value', date.print(calObj.params.dateFormat, 'gregorian', false));
```

But again this also requires https://github.com/joomla/joomla-cms/pull/17183

**Comment by infograf768** [comment]
@farhadst 
When patching calendar.js, please do not forget to set DEBUG on.

**Comment by farhadst** [comment]
@infograf768 yes debug is on
@dgt41 in media/system/js/fields/calendar.js line 1013 to 1026 is:

```
if (calObj.params.dateType !== 'gregorian') {
							// We need to transform the date for the data-alt-value
							var ndate, date = Date.parseFieldDate(calObj.inputField.value, calObj.params.dateFormat, calObj.params.dateType);
							ndate = Date.localCalToGregorian(date.getFullYear(), date.getMonth(), date.getDate());
							date.setFullYear(ndate[0]);
							date.setDate(ndate[2]);
							date.setMonth(ndate[1]);
							calObj.inputField.setAttribute('data-alt-value', date.print(calObj.params.dateFormat, 'gregorian', false));
						} else {
									calObj.inputField.setAttribute('data-local-value', Date.parseFieldDate(calObj.inputField.value, calObj.params.dateFormat, calObj.params.dateType)
									.print(calObj.params.dateFormat, 'gregorian', false));
									calObj.inputField.setAttribute('data-alt-value', Date.parseFieldDate(calObj.inputField.value, calObj.params.dateFormat, calObj.params.dateType)
									.print(calObj.params.dateFormat, 'gregorian', false));
						}
```
but Has no effect on the problem

**Comment by dgrammatiko** [comment]
@farhadst can you please test this code:
(replace the 4th line in the above code)
```js
ndate = Date.localCalToGregorian(date.getLocalFullYear('gregorian'), date.getLocalMonth('gregorian'), date.getLocalDate('gregorian'));
```

**Comment by farhadst** [comment]
@dgt41 i replace code but no effect on the problem

**Comment by dgrammatiko** [comment]
@farhadst can you please provide some dates to test/debug this.
What I need is the
- typed date (jalali)
- saved date (jalali)
- saved date (gregorian, eg from the db)

**Comment by farhadst** [comment]
![screencapture_17-07-25_16 27 59](https://user-images.githubusercontent.com/8976056/28571137-afeac332-7156-11e7-95d0-a913b80ced51.gif)

first date is: ۱۳۹۶-۰۳-۰۸ ۰۰:۱۱:۰۰ = 1396-03-08 00:11:00 = 2017-05-29
date from 08 change to 09 and save but one day will be reduced and date is 08
no effect typ persian number or latin number

**Comment by dgrammatiko** [comment]
@farhadst excellent, thank you. That will make it way easier to debug. One more thing you mentioned that the date can also be reduced by one day, can you provide the same set of data as before for such a behaviour?

**Comment by farhadst** [comment]
@dgt41 i check again and behaviour is the like befor:

If one of the January days is chosen according to Jalali, one day will be added to set date, 
for example if set 1396-10-26 (16January) and save it, date change to 1396-10-27

any date In February, 1 day is added to the selected date

any date In March, 2 days from the chosen date will be reduced
for example if set 1396-12-24 (15March) and save it, date change to 1396-12-22

any date In April, no day can be chosen and if set any date, this change to the first of may
any date In may, 1 days from the chosen date will be reduced
There is no problem in June
any date In july, 1 days from the chosen date will be reduced
There is no problem in August and September
any date In October, 1 days from the chosen date will be reduced
any date In November, 1 day is added to the selected date
There is no problem in December

**Comment by farhadst** [comment]
An interesting point
if click on date box and then click on popup calendar, date change but if no click on date box and just click on popup calendar date no change

![screencapture_17-07-25_17 12 59](https://user-images.githubusercontent.com/8976056/28572662-2ff7bcb4-715d-11e7-9cb5-1948779a7055.gif)

**Comment by infograf768** [comment]
@farhadst

Please, look at this and post your comments there (concerns the calendar itself, not the field)

https://github.com/joomla/joomla-cms/issues/17389<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17150">issues.joomla.org/tracker/joomla-cms/17150</a>.</sub>

**Comment by farhadst** [comment]
@infograf768 I check this and Yes, this problem was to persian calendar (day name incorrect)
with file replacement problem fixed and now day name is correct

**Comment by dgrammatiko** [comment]
@farhadst this was fixed or there is something still pending here?

**Comment by farhadst** [comment]
@dgt41 No this issue not fixed and is still pending

**Comment by dgrammatiko** [comment]
@farhadst so which part is still buggy?

**Comment by farhadst** [comment]
@dgt41 yes this part is still buggy

**Comment by brianteeman** [comment]
What exactly is not working now?

**Comment by farhadst** [comment]
@brianteeman I gave a full explanation on [this post ](https://github.com/joomla/joomla-cms/issues/17150#issuecomment-317722123)

**Comment by ghost** [comment]
any Opinion @brianteeman?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17150">issues.joomla.org/tracker/joomla-cms/17150</a>.</sub>

**Comment by brianteeman** [comment]
The error described by @farhadst sounds unrelated to the calendar localisation and more to do with a difference in the timezone settings between the site and the server

**Comment by ghost** [comment]
closed as stated above. Issue can always reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17150">issues.joomla.org/tracker/joomla-cms/17150</a>.</sub>
