### ISSUE TITLE
No more sidebar or searchtools in lists on Firefox

### ISSUE THREAD

**Issue by PascalNetenvie** [joomla/joomla-cms#17154]
Since 3.7.3 Sidebar and searchtools don't work anymore in Firefox.

### Steps to reproduce the issue
Just go on Articles list

### Expected result
Have a sidebar (and Searchtools when click at top button)

### Actual result
No sidebar and nothing appear when click at searchtool top button
Error in console :
NS_ERROR_STORAGE_BUSY:   template.js:343
	window.toggleSidebar http://www.axygest.fr/administrator/templates/isis/js/template.js:343:17
	<anonyme> http://www.axygest.fr/administrator/index.php:166:4
	i http://www.axygest.fr/media/jui/js/jquery.min.js:2:27444
	fireWith http://www.axygest.fr/media/jui/js/jquery.min.js:2:28213
	ready http://www.axygest.fr/media/jui/js/jquery.min.js:2:30004
	K http://www.axygest.fr/media/jui/js/jquery.min.js:2:30366

### System information (as much as possible)
Windows 7 64
Firefox 54.0.1

**Comment by zero-24** [comment]
hmm this more sounds like a broken firefox profile please check this post: https://stackoverflow.com/questions/18877643/error-in-local-storage-ns-error-file-corrupted-firefox

```
Firefox stores its HTML5 data in a file called webappsstore.sqlite. That's sitting in your profile directory which lurks somewhere in ~/.mozilla/firefox/....default/ (depending on what your profile is called).

Move that out the way and restart Firefox and everything will come back to life.
```

**Comment by ghost** [comment]
can't confirm Issue.

closed as no Core Issue. It can always reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17154">issues.joomla.org/tracker/joomla-cms/17154</a>.</sub>

**Comment by PascalNetenvie** [comment]
It was a browser error like joomla-cms-bot said.

Thx.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17154">issues.joomla.org/tracker/joomla-cms/17154</a>.</sub>
