### ISSUE TITLE
problem in installing

### ISSUE THREAD

**Issue by Shazrina1994** [joomla/joomla-cms#17160]
### Steps to reproduce the issue

as I'm very new to Joomla-cms, when installing after all configurations of XAMPP and phpmyadmin even after creating database, the installation process after the 3rd step it takes lot more time to install. and even though I am waiting for several hours it remains the same with half installation. so anyone please help me to continue my open source project please..

**Comment by infograf768** [comment]
Please use the forum https://forum.joomla.org/viewforum.php?f=707 as Github is reserved for coding issues.
