### ISSUE TITLE
Menu items Administrator

### ISSUE THREAD

**Issue by joris85** [joomla/joomla-cms#17162]
The Administrator menu is new so maybe thats why there could be allot better :-)
I think its awesome that its there!

1. In the menu settings i can't add a style to the menu (like icon icon-music)
2. The image selecting is not working like normal menu items
3. There should be ACL for the menu items if you ask me, now it is only on the module not per item.

Is this the right spot for these kind of features?

**Comment by ghost** [comment]
@izharaazmi: can you please have a look at this Feature Request?

**Comment by izharaazmi** [comment]
For the menu item icons I'd prefer replacing the image select (media manager) button with a plain text, where we can add these icon class names.

We may have the per item ACL but it would be only useful for non-component links as component links are already using component access rules and are sufficient.

**Comment by jwaisner** [comment]
Closing as features are no longer able to be applied in J3. Please test out J4 and submit a feature request if there is something you would like to see with that template.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17162">issues.joomla.org/tracker/joomla-cms/17162</a>.</sub>
