### ISSUE TITLE
[4.0] RFC Show/Hide Strings

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17178]
If you look at our options we often have a label with the word Show in it and the options Show/Hide
When really the answer to that should be Yes/No

<img width="315" alt="screenshotr11-23-58" src="https://user-images.githubusercontent.com/1296369/28362611-ee1c8e24-6c74-11e7-881b-7fab7e1587c2.png">

Depending on the context we should be changing these options to Yes/No when the word Show or Hide is in the label OR rewording the label to remove the word Show or Hide

**Comment by C-Lodder** [comment]
If it were up to me, I'd remove the text indicator (Yes/No | Show/Hide)

The label and titles should be descriptive enough for the user

**Comment by brianteeman** [comment]
Sorry I don't follow

**Comment by C-Lodder** [comment]
Actually don't worry, my suggestion would fail a11y.

**Comment by MartijnMaandag** [comment]
Group these items together or maybe a Tab called Show/Hide with all the items with Yes/No.
