### ISSUE TITLE
Using the calendar tool disables manual date changes

### ISSUE THREAD

**Issue by drewgg** [joomla/joomla-cms#17171]
### Steps to reproduce the issue

(from the Article Manager)
1) Open an article (new or existing)
2) Change the "Start Publishing" date/time via the calendar tool (call this DATE 1)
3) Change the "Start Publishing" date/time manually (via typing in the text field) (call this DATE 2)
4) Save the article. You'll notice DATE 1 is saved; DATE 2 is lost.

Alternatively, instead of saving the article (step 4), you can simply open the calendar tool again, and you'll see the DATE 2 revert to DATE 1.

### Expected result

DATE 2 should be saved

### Actual result

DATE 1 is saved

### System information (as much as possible)

Confirmed in Chrome, Version 59.0.3071.115 (Official Build) (64-bit)
and Firefox 54.0 (32-bit)

### Additional comments

You can open and close the calendar tool without losing the ability to manually update the date. But once you make a change to the date or time via the calendar tool, manually changing the date will not stick. This happens whether or not the calendar tool is open when you manually change the date. The issue starts the moment a change to the date/time is made via the tool.

**Comment by brianteeman** [comment]
I can confirm this. Note you can make a manual change only if you havent already used the calendar picker

**Comment by drewgg** [comment]
I've created a patch here: https://github.com/joomla/joomla-cms/pull/17183

If the changes are accepted I'd need to create a pull for the minified version as well, but I'm not sure which route should be used for minification. Google Closure?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17171">issues.joomla.org/tracker/joomla-cms/17171</a>.</sub>

**Comment by ghost** [comment]
closed as having PR #17183<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17171">issues.joomla.org/tracker/joomla-cms/17171</a>.</sub>
