### ISSUE TITLE
key reference and external reference

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17173]
While trying to work out what these two fields in an article are for I have determined that "external reference" is used for the `<meta name="xreference" content="` tag and that "key reference" is just a db field that someone could use if they had a use.

Surely then (assuming I am correct above) the fields should be swapped around on the form so that all three metatags are together

### current view
<img width="408" alt="screenshotr17-51-26" src="https://user-images.githubusercontent.com/1296369/28329681-90a5daf8-6be2-11e7-8264-5ab14352a353.png">

**Comment by brianteeman** [comment]
**So many options that no one knows what they are and if they think they do then they will be surprised as they dont do what you think they will do and they are named incorrectly**

**Comment by PhilETaylor** [comment]
https://forum.joomla.org/viewtopic.php?t=844679

**Comment by brianteeman** [comment]
Thanks @PhilETaylor but they are either repeating what i wrote above OR completely irrelevant

**Comment by brianteeman** [comment]
Looking further its even more odd/wrong

Both fields have the same name

`		name="xreference" 
`

**Comment by ghost** [comment]
i had also tried figure out what these Fields are about. For my Knowledge i didn't understand this Fields Descriptions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17173">issues.joomla.org/tracker/joomla-cms/17173</a>.</sub>

**Comment by brianteeman** [comment]
I know what they are for although I don't see the need for both of them and because they have the same name it's a problem to use them

**Comment by ghost** [comment]
Off Github-Topic but if someone want more about it: https://www.robertwent.com/blog/what-is-the-xreference-meta-and-joomla-s-external-reference-field/

**Comment by DaveOzric** [comment]
> So many options that no one knows what they are and if they think they do then they will be surprised as they dont do what you think they will do and they are named incorrectly

> I know what they are for although I don't see the need for both of them and because they have the same name it's a problem to use them

So what are they for? Can't we get a rel=canonical or something that is actually useful in here instead?

**Comment by DaveOzric** [comment]
It sure would be nice to have a rel=canonical field to add a link to original content instead of mystery fields that have no explanation.
