### ISSUE TITLE
Possible bug on J3.7.3 Contacts Component

### ISSUE THREAD

**Issue by lambis7** [joomla/joomla-cms#17180]
### Steps to reproduce the issue
I recently updated my site from J3.6.5 to J3.7.3. After the upgrade i noticed the below issue:

On "_Components -> Contacts -> Contacts_" i have a user to display its info as contact person. Inside that contact and on tab "_Display_" i have the "_Display Format_" as "_Tabs_". But on site (http://thepcdoctor.gr/index.php/contactus) the contact is displayed as "_Sliders_"
This happens no matter what i have selected as "_Display Format_" value.

Previously on J3.6.5 it worked just fine, i had "_Tabs_" selected and it was ok.

### System information (as much as possible)
Joomla 3.7.3
PHP 7.0.21
MySQLi 5.5.56-MariaDB

**Comment by brianteeman** [comment]
what is the menu setting?

**Comment by lambis7** [comment]
@brianteeman what do you mean?

**Comment by brianteeman** [comment]
On the menu item is it set to sliders?

**Comment by lambis7** [comment]
No the value of "Display Format" field is set to "Tabs". But no matter what i choose as the value of that field, the contact is displayed as "Sliders"
![site](https://user-images.githubusercontent.com/24440946/28429379-1eb03b24-6d85-11e7-92f1-b35941dbdf7c.png)

**Comment by brianteeman** [comment]
In the menu item itself what is is set to

<img width="629" alt="screenshotr18-07-54" src="https://user-images.githubusercontent.com/1296369/28429918-6d8ae8e8-6d76-11e7-9b51-969f9ff4ce03.png">

**Comment by lambis7** [comment]
It was set to Use Global (Sliders). I changed it to Tabs and it works.
But on J3.6.5 i also had it Use Global (Sliders), but inside the contact i had it on Tabs and was displayed as Tabs overwritting the Menu item.

I guess that has changed on J3.7.3 and it is not a bug as i thought. Menu item has higher priority than Contact.

Thank you @brianteeman

**Comment by brianteeman** [comment]
glad you resolved it
