### ISSUE TITLE
Calendar field not able to set old date

### ISSUE THREAD

**Issue by NordiskIT** [joomla/joomla-cms#17189]
### Steps to reproduce the issue
1. Create a calendar field for an article.
2. Set the date before 1900.
3. Press enter.

### Expected result
The date is set no matter how old the date is.

### Actual result
The date field is cleared.

### System information (as much as possible)
Clean installation of Joomla 3.7.3

### Additional comments
It might have something to do with a default value for the minyear argument. Anyway, you should be able to select older dates. Why are there even a limit to this? Also, why is the minyear only relative and no option to set fixed.

**Comment by ghost** [comment]
Issue confirmed. Test com_fields in Article.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17189">issues.joomla.org/tracker/joomla-cms/17189</a>.</sub>

**Comment by infograf768** [comment]
I am not sure we can set dates older than 1900 in a gregorian calendar (because of UNix limits).

**Comment by tonypartridge** [comment]
I thought we were limited to 1970 due to unix oimitations. We are validating the dates here so it wouldn't be possible. Alternatively if you needed it in a custom field you could write a custom field to handle it without specific calendar validation. And instead Store as a string.

**Comment by brianteeman** [comment]
@tonypartridge no it will go back to 1900 - just take a look ;)

```
		JoomlaCalLocale.minYear          = JoomlaCalLocale.minYear ? JoomlaCalLocale.minYear : 1900;
		JoomlaCalLocale.maxYear          = JoomlaCalLocale.maxYear ? JoomlaCalLocale.maxYear : 2100;

```

https://github.com/joomla/joomla-cms/blob/staging/media/system/js/fields/calendar.js#L75

**Comment by ghost** [comment]
so its expected Behaviour?

**Comment by brianteeman** [comment]
It is working as designed BUT that doesn't mean it is correct. 

@dgt41 is there a reason for those min and max values?

**Comment by dgrammatiko** [comment]
@brianteeman I thought that we covered that in the layout: https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/form/field/calendar.php#L128-L129

So with an override you could have user defined values for minimum and maximum year!
PS. If it's multilingual, with mixed calendars (e.g. jalali + gregorian) the override might need to pass the right values depending on the language.

**Comment by Fedik** [comment]
limitation comes from use of [`strtotime()` functions ](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/fields/calendar.php#L247) in the calendar.
you can save any date in MySQL but it can be broken by `strtotime()` 
see notes http://php.net/strtotime

php DateTime has no such limits

**Comment by dgrammatiko** [comment]
@Fedik you are right but **only** for 32bit installations

Quoting 
> For 64-bit versions of PHP, the valid range of a timestamp is effectively infinite, as 64 bits can represent approximately 293 billion years in either direction.

**Comment by Fedik** [comment]
also true

**Comment by dgrammatiko** [comment]
Not sure if there is a bug here, as we have
- a way to pass custom minimum and maximum year
- there is a known limitation with `strtotime()` and 32bit versions of PHP

**Comment by Quy** [comment]
OK to close?

**Comment by ghost** [comment]
closing - issue can always reopened if needed.
