### ISSUE TITLE
[4.0] Warning on stdClass when Joomla! launched

### ISSUE THREAD

**Issue by kasvith** [joomla/joomla-cms#17181]
### Steps to reproduce the issue
- Do a fresh install from repo
- Go to Global Settings
- **Enable Debugging**
- Save

### Expected result
- No warnings at all

### Actual result
An error regarding this

![image](https://user-images.githubusercontent.com/13379595/28372591-c05c60d8-6cbd-11e7-8993-6f6bc14ca4b4.png)

### System information (as much as possible)
PHP 7.0 MacOSX Sierra with XAMMP

**Comment by C-Lodder** [comment]
Issue confirmed

**Comment by C-Lodder** [comment]
Only thing I can do to fix this is, replacing the `if` statement here: https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/CMS/Helper/ModuleHelper.php#L276

with this:

```
if (JDEBUG && isset($module->module) && isset($module->title))
{
	\JProfiler::getInstance('Application')->mark('afterRenderModule ' . $module->module . ' (' . $module->title . ')');
}
```

But not sure that's the best approach.

@mbabker @laoneo ?

**Comment by zero-24** [comment]
the issue comes from here: https://github.com/joomla/joomla-cms/pull/17056

**Comment by zero-24** [comment]
this line returns null https://github.com/joomla/joomla-cms/commit/3a31839471af3153f61866f481c230cbd6b6714a#diff-870be7804424d0f44d0e7e48901a743fR19

**Comment by zero-24** [comment]
https://github.com/joomla/joomla-cms/pull/17182

**Comment by C-Lodder** [comment]
thanks @zero-24

**Comment by kasvith** [comment]
@zero-24  any update?

**Comment by zero-24** [comment]
You need to test my PR at #17182 ;) thank George can merge it :)
