### ISSUE TITLE
“Linked modules” button in “Menus > Manage” ignores ACL settings

### ISSUE THREAD

**Issue by noccioletta** [joomla/joomla-cms#17188]
### Steps to reproduce the issue

**What we have**

A fresh installation of Joomla! 3.7.3

User U (Publisher group, Administrator Login allowed, Access Administration Interface allowed for both modules and menus)
Menu M, containing the main menu
Module M, displaying the main menu M

User U can edit by default all the modules

Now we set the permissions of module M denying Edit and Edit state actions to Publishers.

The Advanced Permissions Report for User U shows that’s all correct, user U is allowed to edit the menu M but can’t modify the corresponding module.

When user U logins in the administration panel he can see the list of modules, and the module M isn’t editable.

**What happens**

**Step 1.** 
User U logins in the administration panel

**Step 2.** 
User U navigates to Menus > Manage

**Step 3.** 
User U clicks on Modules button in "Linked Modules" column

**Step 4.**
User U select module M item in the dropdown list

### Expected result

The module M item in the dropdown list shouldn’t be active 
OR
The popup window shown after clicking on module M item should report that user U hasn’t the rights to modify the module

### Actual result

User U, clicking on module M item in the dropdown list, gets a popup window that allows him to edit all the values of the module, except Status, Start publishing and Finish publishing.

### System information

Joomla! Version
Joomla! 3.7.3 Stable [ Amani ] 4-July-2017 08:03 Joomla! Platform Version

### Additional comments

If we deny global edit permissions for modules to user U, the system works fine: he cannot modify M. When user U try to modify module M from ”Linked Modules", the popup window shows an "Error Edit not permitted.." red warning).

**Comment by ghost** [comment]
@sanderpotjer can you please have a Look?

**Comment by sanderpotjer** [comment]
@noccioletta good catch, that is indeed wrong!

I have created a PR request that fixes this issue, see #17838

(@franz-wohlkoenig thanks for notifying me of this issue)

**Comment by ghost** [comment]
closed as having Pull Request #17838 Thanks @sanderpotjer <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17188">issues.joomla.org/tracker/joomla-cms/17188</a>.</sub>

**Comment by noccioletta** [comment]
@franz-wohlkoenig @sanderpotjer 
Thank you !
Greetings from Università degli Studi di Perugia, Italy (http://www.unipg.it).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17188">issues.joomla.org/tracker/joomla-cms/17188</a>.</sub>
