### ISSUE TITLE
[4.0] Clear search results

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17195]
### Steps to reproduce the issue
In the list view of any component in the admin use the search box to produce a reduced list
Then press CLEAR

### Expected result
The search box is cleared and the list is reset

### Actual result
The search box is NOT cleared but the List Limit (in the table options) is reset

**Comment by C-Lodder** [comment]
Isn't this the same as: https://github.com/joomla/joomla-cms/issues/16344 ?

**Comment by brianteeman** [comment]
lol - the same as an issue I already reported although I didnt spot it clearing the list limit there so I will close that one in favour of this

**Comment by ghost** [comment]
closed as having Pull Request #18810
