### ISSUE TITLE
[4.0] Messes Layout if "Tag not found"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#17191]
### Steps to reproduce the issue
Clean Installation, in Module "All Front End Views" click on `All Tags`, get:
![bildschirmfoto 2017-07-20 um 16 00 02](https://user-images.githubusercontent.com/8235763/28421335-2e0280ac-6d65-11e7-8220-a3059455e550.jpg)

### System information
4.0.0-dev
macOS Sierra, 10.12.5
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
Hmm, seems fine for me:
![tags](https://user-images.githubusercontent.com/2019801/28461300-dff2d7d2-6e0d-11e7-86df-bed687937d09.png)

Be sure to fetch the latest code from the repo and clear your browser cache. Let me know if you're still having issues and I'll look into it further.

**Comment by ghost** [comment]
Fresh Install works. My Guess: This Time i didn't install as Multi-Lang., which not works at Installation but shows in Backend Menues, Articles, ...
