### ISSUE TITLE
[com_fields] Type "Radio" not wrapping around and scrolling off page

### ISSUE THREAD

**Issue by peetwright** [joomla/joomla-cms#17196]
### Steps to reproduce the issue
Create a field group
Add fields so you have a long list - for example every year from 2017 through 1990
Edit article to set custom field to year 1991 - you have to scroll far right on the page to get to it. 

### Expected result
Long lists of fields should wrap so they all fit on a screen without scrolling left/right

**Comment by ghost** [comment]
You mean Custom Fields of Type "List" are not shown vertical but horizontal?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17196">issues.joomla.org/tracker/joomla-cms/17196</a>.</sub>

**Comment by peetwright** [comment]
I mean they are horizontal - not vertical. Or for that matter should be horizontal, but when they reach edge of screen, break to next line. 

Now they are like this

1 | 2 | 3 | 4 | 5 | 6 | ....... until the scroll way off the screen. 

If the screen were "3" units wide, should be:

1 | 2 | 3 |
4 | 5 | 6 |
....

Because if you have a long list of items - it's not immediately apparent they are all there - as they are off-screen.

This is in the view, inside an article edit - NOT when creating the list.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17196">issues.joomla.org/tracker/joomla-cms/17196</a>.</sub>

**Comment by brianteeman** [comment]
Are you sure that's a list. Please post a screenshot of the field settings

**Comment by ghost** [comment]
Can't confirm. Set a List from 1990 to 2017, got:
![bildschirmfoto 2017-07-25 um 18 10 22](https://user-images.githubusercontent.com/8235763/28582129-9bd2f03c-7164-11e7-89cb-37ef2c41df76.jpg)

**Comment by peetwright** [comment]
Sorry - it's a type of radio. My bad on that bit. The issue remains for long lists of radio buttons though. Here is a screen shot...

![screen shot 2017-07-25 at 11 15 28 am](https://user-images.githubusercontent.com/10967063/28582387-c22d368c-712a-11e7-9afd-a63758ce644b.png)

As you can see, my browser is stretched to 3/4 of a 27" 5k display and there is more off to the right. The black vertical is my desktop showing through past the browser port. Hope this helps!

**Comment by ghost** [comment]
Issue confirmed, changed Issue-Title.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17196">issues.joomla.org/tracker/joomla-cms/17196</a>.</sub>

**Comment by brianteeman** [comment]
That's the way that the web works. You shouldn't use a radio for this

**Comment by peetwright** [comment]
@brianteeman - sorry, that's just not appropriate. Why not? I if I need to program 12 radio buttons for my clients to use in a particular situation and they only have small screens they should deal with a buggy interface to select from the 12 (and can only see 6 or 4)? What if each radio was very long and only 3 showed? This is a bug. Thank you @franz-wohlkoenig for confirming it. I appreciate it and let me know if I can assist in testing or you need more.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17196">issues.joomla.org/tracker/joomla-cms/17196</a>.</sub>

**Comment by brianteeman** [comment]
Sorry but it's nothing to do with how custom fields work but how html radio buttons work unless you can find an example elsewhere

**Comment by peetwright** [comment]
It's exactly how radio buttons work - you get a choice of one from a list of X, and only one. That's how it is used here. It's done as radio because I need to enforce that no one uses multiples. So that aside, if someone programs a list of radio buttons to be available in an article - they need to be easily seen otherwise it's a bad UX.

**Comment by brianteeman** [comment]
You can't select more than one on a list either (unless you enable multiple selects).

What you want to do can only be done with a list. This is not a Joomla problem!

**Comment by ghost** [comment]
@peetwright using different field for a Decade like "1990-1999" and so on? As @brianteeman explained its expected Behaviour, so i'm closing this Issue.
