### ISSUE TITLE
Frontend banners component points to https instead of http

### ISSUE THREAD

**Issue by orosro** [joomla/joomla-cms#17204]
### Steps to reproduce the issue
1. Add banners from the banners component and display them on a certain category or article page
2. Activate cache on administrator panel (Progressive caching)
3. Wait some time (Random minutes, or hours)

### Expected result
I expect the images not to be broken (url points to http instead of https)

### Actual result

The images url start with https instead of http, breaking the image and preventing the display.

### System information (as much as possible)

Joomla v.3.7.3
Php Version: 5.4.45 
Database: MySQL

Seo plugin: sh404Sef
Caching plugin: none
Module position: regular labs: sorcerer - can tell joomla on which page to display the modules

### Additional comments

Clearing the cache (delete all) seems to solve the problem for the moment, also disabling the cache does the trick.

**Comment by brianteeman** [comment]
Is your site running on https or http?

**Comment by orosro** [comment]
@brianteeman Hello, on http.
Also, all settings that I could find are set to http (from the configuration)

**Comment by brianteeman** [comment]
Thanks for confirming that. In that case I cant confirm it on any of my sites that have banners

**Comment by ghost** [comment]
closed this Issue as unconfirmed Report. Can always be reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17204">issues.joomla.org/tracker/joomla-cms/17204</a>.</sub>
