### ISSUE TITLE
[com_fields] Long chosen replaced multi-select drop downs do not work on iPads

### ISSUE THREAD

**Issue by GeraintEdwards** [joomla/joomla-cms#17202]
There are 2 related problems
### Steps to reproduce the issue
Using an iPad (browser doesn't matter)
**Problem 1** 
1. Create a com_content custom field of type list and mark it to allow multi-select.  
2. Add at least 12 options to select from
3. Create/edit an article and try to select one of the options beyond the first 10.  Using touch screen to select and NOT by typing in the name

**Problem 2** 
Using the same 12+ option list from problem 1 above select one option and then attempt to select another (without minimising the keyboard)

### Expected result

**Problem 1**
The drop down list should allow you to scroll/drag down within the drop down and select the options you want

**Problem 2**
You should be able to make multiple selections

### Actual result

**Problem 1**
You cannot scroll the drop down list and therefore cannot select the lower options in the list

**Problem 2**
You cannot make a second selection until you mimimise the keyboard and click in the input box a second time.

### System information (as much as possible)

You must use an iPad to test - problem is browser independent

### Additional comments

This is a known issue in the chosen library version we are using.  

See https://github.com/harvesthq/chosen/issues/2289 (long discussion) 

There would appear to be 2 solutions to the problem - 

1. disable chosen on iPad (as it is already on iPods) 
2. update the chosen library

**Comment by brianteeman** [comment]
The only way to fix this is to update chosen and apply the changes that were made to the upstream library here https://github.com/joomla/joomla-cms/pull/11779

**Comment by ghost** [comment]
any Suggestion @GeraintEdwards?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17202">issues.joomla.org/tracker/joomla-cms/17202</a>.</sub>

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 26th January 2018.

**Comment by ghost** [comment]
This has been closed as stated above – it can always be reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17202">issues.joomla.org/tracker/joomla-cms/17202</a>.</sub>

**Comment by tonypartridge** [comment]
Bump can we reopen @franz-wohlkoenig  @GeraintEdwards can you re-review?

**Comment by ghost** [comment]
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17202">issues.joomla.org/tracker/joomla-cms/17202</a>.</sub>

**Comment by pepperstreet** [comment]
As Brian mentioned above #11779 , the Chosen library had to be updated in the past. I didn't know it has been modified... Anyways, the original Chosen script version is 1.**8**.**3** and Joomla still ships with a 1.**6**.**2** (3 Aug 2016) 

Just noticed the RC of Joomla3.8.**6** … shouldn't it consider the script update? 
Joomla4 seem to use another auto-complete/multi-select, so the time is running out ;)

**Comment by brianteeman** [comment]
Anyone is welcome to take the current release and do the long work to make the changes required to not completely break backward compatibility. It's not a simple job and I am not doing it again.

**Comment by brianteeman** [comment]
I guess no one is interested in doing the hard work to update chosen without breaking b/c and as chosen will not be used in j4 (still to be finalised)  what will be used) I am going to close it

**Comment by ggppdk** [comment]
@brianteeman 

can you please link to the discussion about this, 
is there some other candidate ?
thanks

**Comment by Quy** [comment]
@ggppdk I think the discussion is here: https://github.com/joomla/joomla-cms/issues/20097#issuecomment-379293318

**Comment by jbrailas** [comment]
I have managed to solve the 1st problem but not the 2nd problem.
Here is the solution:
Download the latest chosen from here: https://github.com/harvesthq/chosen/releases
Replace chosen.min.css and chosen.css in media/jui/css
Edit chosen.jquery.min.js
find: 
t.browser_is_supported=function(){return"Microsoft Internet Explorer"===window.navigator.appName?document.documentMode>=8:!(/iP(od|hone)/i.test(window.navigator.userAgent)||/IEMobile/i.test(window.navigator.userAgent)||/Windows Phone/i.test(window.navigator.userAgent)||/BlackBerry/i.test(window.navigator.userAgent)||/BB10/i.test(window.navigator.userAgent)||/Android.*Mobile/i.test(window.navigator.userAgent))}

and replace with: 
t.browser_is_supported=function(){return"Microsoft Internet Explorer"===window.navigator.appName?document.documentMode>=8:/iP(od|hone)/i.test(window.navigator.userAgent)?!0:/Android/i.test(window.navigator.userAgent)&&/Mobile/i.test(window.navigator.userAgent)?!0:!0}

and then paste the file chosen.jquery.min.js in media/jui/js
Hard Reload the page to view the results (ctrl + shift + R)
