### ISSUE TITLE
[4.0] Dashboard missing css

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17207]
<img width="282" alt="screenshotr17-16-49" src="https://user-images.githubusercontent.com/1296369/28472438-79a662c0-6e38-11e7-9e07-3c18a4541a81.png">

As can be seen in the image the text is in black when it should be white.

The fix is either adding color:#fff to this existing class
`.quick-icons .quickicon-text-xs`

or adding this new class
```
.j-links-link {
    color: fff;
}
```

@C-Lodder @ciar4n

**Comment by ciar4n** [comment]
PR created... #17208
