### ISSUE TITLE
[tinyMCE folder image]

### ISSUE THREAD

**Issue by roby906** [joomla/joomla-cms#17201]
### Steps to reproduce the issue
From the edited admin panel, change the images folder for set 1 (cattura.PNG)

### Expected result
From the frontend when I click on images button of editor the folder should be that choice (cattura2.PNG)

### Actual result

The folder is always root (images) (cattura3.PNG)

### System information (as much as possible)

joomla 3.7.3

**Comment by AlexRed** [comment]
I can confirm the problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17201">issues.joomla.org/tracker/joomla-cms/17201</a>.</sub>

**Comment by ghost** [comment]
Closed as duplicate Report of #16413<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17201">issues.joomla.org/tracker/joomla-cms/17201</a>.</sub>
