### ISSUE TITLE
[3.7.3] Article publish date changes in Datepicker

### ISSUE THREAD

**Issue by romanzipp** [joomla/joomla-cms#17206]
### Steps to reproduce the issue

1. Create a new article
2. Enter a Title & set the publish start date

### Expected result

The date entered is in a correct syntax and should not be altered.

### Actual result

![joomla-github](https://user-images.githubusercontent.com/11266773/28466954-5594685a-6e2e-11e7-8ef4-b73b6b8e51dc.gif)

In this GIF you can see that the entered date has been changed (propably via JavaScript) before the creation has finished.
I throtteled the page speed via the Chrome Developer Tools to visualize this effect.

### System information (as much as possible)

Joomla: 3.7.3
Browsers tested: Opera 46, Firefox 54

### Additional comments

This problem only occures when creating an article, not while editing an existing object.
Only the "publish start date" seems to be changes. Other date fields do not get modified.

**Comment by ghost** [comment]
can you please test #17183?

**Comment by romanzipp** [comment]
works for me, thanks!
