### ISSUE TITLE
[4.0] Show custom fields

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17213]
### Steps to reproduce the issue

In com_contact options

<img width="531" alt="screenshotr12-21-49" src="https://user-images.githubusercontent.com/1296369/28498926-92be56fe-6fa1-11e7-8b19-db97f7b973ec.png">

As seen in the image above there is a warning message being displayed in this field
`
Warning</b>:  htmlspecialchars() expects parameter 1 to be string, array given in <b>C:\Apache24\htdocs\cms4\layouts\joomla\form\field\text.php</b> on line <b>94</b><br />`

**Comment by ghost** [comment]
How do you get this Message? I found an empty field in "Contacts: Options".

**Comment by laoneo** [comment]
Does it also happen on a fresh installation of J4?

**Comment by brianteeman** [comment]
clean install without test data and i have the error

**Comment by brianteeman** [comment]
I still get this error with alpha 2
> administrator/index.php?option=com_config&view=component&component=com_contact

<img width="617" alt="screenshotr22-12-23" src="https://user-images.githubusercontent.com/1296369/33688256-b11240c4-dad2-11e7-9fdc-7206f92e16f7.png">

**Comment by laoneo** [comment]
Please test #19008 which should fix the issue.

**Comment by ghost** [comment]
closed as having Pull Request #19008
