### ISSUE TITLE
[4.0] Select layout is empty

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17214]
Throughout J4 the select list for layouts is always empty

I believe that the issue can be resolved here
https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/cms/form/field/componentlayout.php#L111

And the cause of this issue was #16319

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/17352
