### ISSUE TITLE
$this when not in object context error when using PHP 7.1.7

### ISSUE THREAD

**Issue by visualtribe** [joomla/joomla-cms#17221]
### Steps to reproduce the issue
install php 7.1.7
load site
0-error-0 $this when not in object context

When debug system is on this is what I get:

Uncaught TypeError: Argument 1 passed to KExceptionHandlerAbstract::handleException() must be an instance of Exception, instance of Error given in /var/www/vhosts/simcomanagement.ca/httpdocs/libraries/koowa/libraries/exception/handler/abstract.php:272 Stack trace: #0 [internal function]: KExceptionHandlerAbstract->handleException(Object(Error)) #1 {main} thrown
.../libraries/koowa/libraries/exception/handler/abstract.php:272

267      * called, until all handlers have gotten a change to handle the exception.
268      *
269      * @param   Exception  $exception  The exception to be handled
270      * @return  bool  If the exception was handled return TRUE, otherwise false
271      */
272     public function handleException(Exception $exception)
273     {
274         try
275         {
276             //Try to handle the exception
277             foreach($this->getHandlers() as $handler)

If System - Redirect is turned on:

 Uncaught TypeError: Argument 1 passed to KExceptionHandlerAbstract::handleException() must be an instance of Exception, instance of Error given, called in /var/www/vhosts/simcomanagement.ca/httpdocs/plugins/system/redirect/redirect.php on line 112 and defined in /var/www/vhosts/simcomanagement.ca/httpdocs/libraries/koowa/libraries/exception/handler/abstract.php:272 Stack trace: #0 /var/www/vhosts/simcomanagement.ca/httpdocs/plugins/system/redirect/redirect.php(112): KExceptionHandlerAbstract->handleException(Object(Error)) #1 /var/www/vhosts/simcomanagement.ca/httpdocs/plugins/system/redirect/redirect.php(91): PlgSystemRedirect::doErrorHandling(Object(Error)) #2 [internal function]: PlgSystemRedirect::handleException(Object(Error)) #3 {main} thrown
.../libraries/koowa/libraries/exception/handler/abstract.php:272

267      * called, until all handlers have gotten a change to handle the exception.
268      *
269      * @param   Exception  $exception  The exception to be handled
270      * @return  bool  If the exception was handled return TRUE, otherwise false
271      */
272     public function handleException(Exception $exception)
273     {
274         try
275         {
276             //Try to handle the exception
277             foreach($this->getHandlers() as $handler)

Expected Results:
Site loads properly with no errors.

Site loads properly in 5.6.31

**Comment by brianteeman** [comment]
As seen by the error the problem is with the koowa plugin which is not part of the Joomla core.
