### ISSUE TITLE
Send mass mail includes all recipient addresses in mail in default setting

### ISSUE THREAD

**Issue by spinne1000** [joomla/joomla-cms#17223]
### Steps to reproduce the issue
Send a mass mail to all users from the backend menu Users -> Mass Mail Users.
Forgot to set "Recipients as BCC"

### Expected result
The mail to the recipient should only contain the recipient himself in the "TO" field.

### Actual result
All recipients are in the "TO" field.

### System information (as much as possible)
Joomla! Version 	Joomla! 3.7.3 Stable [ Amani ] 4-July-2017 08:03 GMT 

### Additional comments
It would be best to set the defaults to an more save value like the "Recipients as BCC" and the group selection not to "All Users Groups" by default.

**Comment by spinne1000** [comment]
Why not sending ONE mail to EACH recipient only with one his address in the TO-field?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17223">issues.joomla.org/tracker/joomla-cms/17223</a>.</sub>

**Comment by brianteeman** [comment]
Because if you have thousands of users you might hit a server restriction on the number of emails you can send

**Comment by spinne1000** [comment]
ok, I understand. 
But is there not a problem with data privacy?
I think, here in Germany that is a problem. A site owner is not allowed to publish private data without the approval of the user. And with this settings in mass mail sending, I publish all email addresses to all users in the sending mails.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17223">issues.joomla.org/tracker/joomla-cms/17223</a>.</sub>

**Comment by brianteeman** [comment]
thats why there is the option to send as BCC

There is a case for making BCC enabled by default if someone wants to do a Pull Request to make that change

**Comment by spinne1000** [comment]
If I go to "Users -> Mass Mail" Send as BCC is not enabled. I have to enable it each time.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17223">issues.joomla.org/tracker/joomla-cms/17223</a>.</sub>

**Comment by brianteeman** [comment]
That is why I said

> There is a case for making BCC enabled by default if someone wants to do a Pull Request to make that change

**Comment by spinne1000** [comment]
ok sorry. I missunderstood...
How to do that? :-) Is there a howto for new developers?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17223">issues.joomla.org/tracker/joomla-cms/17223</a>.</sub>

**Comment by brianteeman** [comment]
https://docs.joomla.org/Filing_bugs_and_issues#Issue_a_pull_request_directly_on_Joomla.21.27s_GitHub_repository

**Comment by brianteeman** [comment]
Actually it looks like it is a bug. The field is defined to be bcc by default but for some reason that isnt working

**Comment by markboos** [comment]
I would classify it as a bug, with security aspects. Recipients in the TO: field is a data leak. Think its not Low, because of the consequences.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17223">issues.joomla.org/tracker/joomla-cms/17223</a>.</sub>

**Comment by ghost** [comment]
set it on "Medium".

**Comment by zero-24** [comment]
Please see #17336
