### ISSUE TITLE
[4.0] Missing spinner

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17225]
In J3 we have a spinner.gif at joomla-cms/media/system/images/modal/spinner.gif

This is used in field permissions and language overrides but the file is not present in J4

**Comment by C-Lodder** [comment]
PR for overrides views: https://github.com/joomla/joomla-cms/pull/17334

**Comment by ghost** [comment]
closed as having PR #17334<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17225">issues.joomla.org/tracker/joomla-cms/17225</a>.</sub>

**Comment by C-Lodder** [comment]
@franz-wohlkoenig I haven't fixed the spinner on the permissions view yet. Please reopen

**Comment by ghost** [comment]
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17225">issues.joomla.org/tracker/joomla-cms/17225</a>.</sub>

**Comment by C-Lodder** [comment]
Sorry, was quicker than expected. 2nd PR: https://github.com/joomla/joomla-cms/pull/17335

**Comment by ghost** [comment]
closed as having PR #17335.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17225">issues.joomla.org/tracker/joomla-cms/17225</a>.</sub>
