### ISSUE TITLE
[4.0] Table Options in Menu Items

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17227]
Since the introduction of the combined search and filters into table options we have lost the ability to switch which menu is being displayed. This is particularly annoying after selecting all menu items from the sidebar. 

Also the menu selection is obviously a filter (even if we cant see it) so the table options is always open for com_menus

@ciar4n

**Comment by ciar4n** [comment]
Just looking at an old branch prior to moving the filters under table options and it appears this field did not exist in com_menu anytime recently in J4.

**Comment by brianteeman** [comment]
The required layouts are still present 
`administrator\components\com_menus\layouts`

**Comment by ciar4n** [comment]
I have no idea why that is not displaying. @C-Lodder ?

**Comment by C-Lodder** [comment]
I think this has been an issue before Ciarans PR to move the searchtools into a dropdown.
I've done a `git reset --hard XXXX` at increments of 50, going back 600 commits and it's still an issue way back there.

Also had a mess around with the layouts and cannot seem to figure out why it's not showing the select box to switch clients (site/admin) in `com_menus`

**Comment by brianteeman** [comment]
Closed as fixed elsewhere
