### ISSUE TITLE
[4.0] Remove edit button from toolbar issue in com_languages

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17226]
after #17091 we can see that the edit link for com_languages view=languages was constructed differently so the markup in `administrator\components\com_languages\tmpl\languages\default.php
` needs to be updated to match

@C-Lodder

**Comment by brianteeman** [comment]
and in the list of overrides

**Comment by brianteeman** [comment]
and in the list of menus (not menu items)

**Comment by brianteeman** [comment]
actually it looks like it needs to be done in a lot of places

**Comment by C-Lodder** [comment]
Not sure what you mean by this. What exactly needs updating in the list view for `com_languages`?

**Comment by brianteeman** [comment]
I assumed that in every page that you removed the edit button on then the item would have the pencil link

<img width="408" alt="screenshotr13-35-02" src="https://user-images.githubusercontent.com/1296369/28572274-31f79d28-713e-11e7-8702-9db2999e234f.png">
<img width="466" alt="screenshotr13-35-18" src="https://user-images.githubusercontent.com/1296369/28572275-32137c8c-713e-11e7-9de7-5d4a2fda5af1.png">
<img width="444" alt="screenshotr13-35-25" src="https://user-images.githubusercontent.com/1296369/28572276-3219dbae-713e-11e7-924b-5d2e6abb6dbe.png">

**Comment by C-Lodder** [comment]
Ahh gotcha. https://github.com/joomla/joomla-cms/pull/17242

**Comment by zero-24** [comment]
Closing as there is a PR.

**Comment by brianteeman** [comment]
testing that now but its not just there - do you want me to list all the components?

**Comment by C-Lodder** [comment]
yes please @brianteeman

**Comment by brianteeman** [comment]
com_users - all

com_menus&view=menus

com_fields - all

com_redirect&view=links

com_templates&view=styles
