### ISSUE TITLE
[4.0] Help button on the toolbar

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17229]
In J3 the help button was always right aligned

In J4 the help button is on the right aligned on most views but in some it is left aligned. Is that an intentional design decision

<img width="501" alt="screenshotr13-57-01" src="https://user-images.githubusercontent.com/1296369/28524357-128f19b4-7078-11e7-9db7-e2b9ad111fe6.png">

<img width="590" alt="screenshotr13-57-22" src="https://user-images.githubusercontent.com/1296369/28524358-12952fca-7078-11e7-9ba0-267ff6f5dbad.png">

@C-Lodder @ciar4n

**Comment by C-Lodder** [comment]
Not intentional. It's cause there's not `Options` button which uses the `ml-auto` class to push those 2 buttons to the right. Will try and come up with a solution.

**Comment by brianteeman** [comment]
Ok thanks for working it out. I tried and failed

**Comment by C-Lodder** [comment]
https://github.com/joomla/joomla-cms/pull/17240
