### ISSUE TITLE
Present tags not only in current language when adding them to an article in backend

### ISSUE THREAD

**Issue by Giuse69** [joomla/joomla-cms#17244]
### Steps to reproduce the issue
Tags can be associated to a language, but when the user is creating/editing an article, all tags are displayed and can be assigned to the article independently of the article language.

### Expected result
There should be a new option in tag options to present tags of current language only. If a user changes the language of the article, a popup can ask confirmation saying that tags (except those with "All" language) will be removed from the article.

**Comment by ghost** [comment]
Issue confirmed. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17244">issues.joomla.org/tracker/joomla-cms/17244</a>.</sub>

**Comment by AlexRed** [comment]
try the "Language Filter" parameter in TAG options:
![tag-language](https://user-images.githubusercontent.com/1362388/28607456-ed3585e2-71d3-11e7-9f03-2a80134a9c59.png)

**Comment by ghost** [comment]
@AlexRed "Current" don't work. I set Tag "Red" of Sample Data to Lang. "en-GB", open Article using Lang. "de-AT" and see and can save Article using Tag "Red".

Tooltip mean this is about displaying a Tag-List based on Lang:
![bildschirmfoto 2017-07-26 um 08 54 53](https://user-images.githubusercontent.com/8235763/28608340-4f032d4a-71e0-11e7-81ad-33f4090b70e4.jpg)

**Comment by AlexRed** [comment]
But you try to edit article in frontend or in administrator ?
See: https://github.com/joomla/joomla-cms/pull/14006

**Comment by ghost** [comment]
Tried in Backend. Now in Frontend, there it works.

Maybe it depends in Backend i was logged in as Superuser.

**Comment by Giuse69** [comment]
The problem is in backend, in front end no issue (also when logged as superadmin). Changed title accordingly

**Comment by Giuse69** [comment]
Hi, any update on this issue? Can it be fixed for upcoming Joomla 3.8?

**Comment by ghost** [comment]
Status is set on "Needs Review".

**Comment by inode64** [comment]
In #19047 fix same but in the frontend

**Comment by csbalazs** [comment]
The problem persists.  There are titles with two languages. I create a Category List menuitem and I set Filter Field to Tags, then all tags are displayed regardless of the language setting in the front-end.

List of Tags:
![1801161](https://user-images.githubusercontent.com/1657924/34986912-a8e31dc2-fab9-11e7-8c4c-14b8fab2d4e6.PNG)
Frontend:
![1801162](https://user-images.githubusercontent.com/1657924/34986918-acca4f3c-fab9-11e7-8cf0-2061cfc5657c.png)

**Comment by brianteeman** [comment]
Closed for the same reason as stated here https://github.com/joomla/joomla-cms/issues/15318#issuecomment-294279189
