### ISSUE TITLE
error: Speichern fehlgeschlagen! Fehler: Column count doesn't match value count at row 1 in de-DE

### ISSUE THREAD

**Issue by jojo12** [joomla/joomla-cms#17243]
### Steps to reproduce the issue
site and article language is de-DE
edit in FE or BE an article and save

### Expected result
ok
### Actual result
error notification:
Fehler
Speichern fehlgeschlagen! Fehler: Column count doesn't match value count at row 1
### System information (as much as possible)

PHP Built On | Linux server46.hostfactory.ch 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64
-- | --
Database Version | 5.5.5-10.0.30-MariaDB-0+deb8u1
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.1.3
Web Server | Apache
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 3.7.4 Stable [ Amani ] 25-July-2017 11:11 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0

### Additional comments
The article is saved correctly.
In 3.7.3 and earlier I hadn't this notification.

**Comment by ghost** [comment]
can you please change Issuetext on english? Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17243">issues.joomla.org/tracker/joomla-cms/17243</a>.</sub>

**Comment by zero-24** [comment]
I can not reproduce this on my site. Can you please double check this on a clean install placed on the same server?

**Comment by jojo12** [comment]
I've seen now, the error notification comes only when language is german (de-DE)

**Comment by zero-24** [comment]
> I've seen now, the error notification comes only when language is german (de-DE)

I have also tested german but still can not reproduce this. Did you are able to reprodue this in a clean install too?

**Comment by jojo12** [comment]
you're right. This error is not caused by joomla, but by a bad plugin, which seems to be not yet ready.
Sorry, for disturbing you.
can be closed.

**Comment by brianteeman** [comment]
Closed as requested
