### ISSUE TITLE
Unable to select category on front end after joomla 3.7.4 update

### ISSUE THREAD

**Issue by misrajitas** [joomla/joomla-cms#17245]
### Steps to reproduce the issue

Front end editor select "create a new article"
When selecting category for the new article

### Expected result

new category should be selected.

### Actual result

a category list is then open

### Additional comments
My users can not select the category

**Comment by ghost** [comment]
Can't confirm, select Category on Frontend works.

Have you asked for help on the [forums](https://forum.joomla.org/)?

**Comment by misrajitas** [comment]
I have,
this happend when updated to joomla 3.7.4 from 3.7.3 

When user selects a category, joomla logo shows as loading and then the article edit page turns into a category list page with "?view=categories" at the end of the URL.

**Comment by tonypartridge** [comment]
Did you clear the cache? Does it happen with standard Joomla! Protostar template?

**Comment by misrajitas** [comment]
Did clear cache, and it does happen with Prostar. 
I have fixed the permissions and included a Global EDIT for the users in question. 
The issue of not being able to select category is fixed, but now articles get duplicated when user changes category and then saves

**Comment by tonypartridge** [comment]
This sounds like a plugin issue. Do you have content plugins installed? 3rd party? Or a different editor?

**Comment by misrajitas** [comment]
I do have JCE Editor. 
I have Blogsten to receive Email to Articles. 
And a Sitemap Creator

**Comment by infograf768** [comment]
Please disable your 3rd party plugins, test and then add them back one by one.

**Comment by brianteeman** [comment]
I am closing this issue at this time as it has been several weeks without a response. It can always be reopened if updated

**Comment by newagesamurai** [comment]
**Steps to reproduce the issue**

User in a User group with the following 
Global permissions:
Create - allowed
Edit - denied
Edit own - allowed

Permissions for articles:
Create - allowed
Edit - denied
Edit own - allowed

Login with a user from this user group
Select "create a new article" / "edit existing article" via front end editor
Select category for the new article / change category for an existing article in the front end editor

**Expected result**

category should be selected.

**Actual result**

The category list view opens

**System information:**
Joomla 3.7.5
PHP-Version | 7.0.21


If the permisson in Global / Arcticles is set to "Edit - allowed" it works fine. So it seems that the "Edit own - allowed" permission does not seems to be recognized.

**Comment by newagesamurai** [comment]
Dear misrajitas,

you were writing "I have fixed the permissions and included a Global EDIT for the users in question.
The issue of not being able to select category is fixed..."

How exactly did you fix this? What did you mean with "a Global EDIT"?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17245">issues.joomla.org/tracker/joomla-cms/17245</a>.</sub>
