### ISSUE TITLE
Cannot install Joomla 3.7.4 on remote database

### ISSUE THREAD

**Issue by khanhlh** [joomla/joomla-cms#17246]
### Steps to reproduce the issue
Install Joomla 3.7.4 with remote database. After delete the generated random file inside installation folder, it still shows warning about remote database (no error message). Click "next" then it stuck at "Database Installing" step. 

### Actual result
**Still showing warning after verify owner**

![Still showing warning after verify owner](https://issues.joomla.org/uploads/1/d0701a5fd897ac6830c1a56e4e67dd9d.png)

**Stuck at Database installing step**

![Stuck at Database installing step](https://issues.joomla.org/uploads/1/de18c8df21830690039588d58fd10554.png)

**Continuous post generate show in Inspector**

![Continuous post generate show in Inspector](https://issues.joomla.org/uploads/1/69287a76be763269b33708fce9438ef1.png)

**Comment by AlexRed** [comment]
I can confirm the problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17246">issues.joomla.org/tracker/joomla-cms/17246</a>.</sub>

**Comment by zero-24** [comment]
Please test: https://github.com/joomla/joomla-cms/pull/17248

**Comment by e-struct** [comment]
Same problem observed.

**Comment by ghost** [comment]
@e-struct can you please test #17248 if this Pull Request solve the issue?

**Comment by Scorptech** [comment]
I can also confirm that I am having this problem with Joomla 3.7.4 with my hosting service and my ISP do not know how to fixed it. The work around is to install an older version and upgrade, but this does not solve the initial problem with 3.7.4.

**Comment by ghost** [comment]
@Scorptech the Pull Request #17248 is merged. This means if all works well it is shipped with next Release 3.8 ([Schedule](https://developer.joomla.org/roadmap.html#38))

**Comment by nemanjaradevic** [comment]
yes me too...i cannot make any new websites<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17246">issues.joomla.org/tracker/joomla-cms/17246</a>.</sub>

**Comment by zero-24** [comment]
> yes me too...i cannot make any new websites

Thank you for your report. @nemanjaradevic  Please apply this patch #17248 or wait for Joomla 3.7.5 we are going to release shortly. Thanks.
