### ISSUE TITLE
[4.0] public static function tooltipText

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17255]
This function needs reviewing now that we are not using styled tooltips/popovers in many places

For example in the permissions pages
<img width="572" alt="screenshotr10-09-02" src="https://user-images.githubusercontent.com/1296369/28613526-7c11a41a-71ea-11e7-8f2e-11e1c0886711.png">

As a title tag can't parse html we dont need to present this with the code used at https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/cms/html/html.php#L942

The title tag should only be the description in this case and not as in the code above.

(I have not done a PR as I don't know if there any knock on effects elsewhere etc and the entire function probably needs a review)

**Comment by dgrammatiko** [comment]
@brianteeman 2 things here:
- tooltips should not contain html mark up
- tooltips should be css based and activated on click, touch!

**Comment by brianteeman** [comment]
> tooltips should not contain html mark up

I know and that's why I am saying this

> tooltips should be css based and activated on click, touch!

Not part of this issue (true but beyond the scope of what I am referring to - I would love us to use https://github.com/ghosh/microtip for that)

**Comment by dgrammatiko** [comment]
AFAIK  @ciar4n already showcased something similar, based on https://kazzkiq.github.io/balloon.css/

**Comment by dgrammatiko** [comment]
For the popovers I propose: https://www.paciellogroup.com/blog/2016/01/simple-standalone-toggletip-widget-pattern/

**Comment by infograf768** [comment]
> The title tag should only be the description in this case and not as in the code above.

We may have issues in this case when the description is long (it also have to contain our existing labels) and needs LRs
How to deal with LR ?

**Comment by dgrammatiko** [comment]
what is LR?

**Comment by infograf768** [comment]
Line Return

**Comment by infograf768** [comment]
`<br>` in html markup

**Comment by brianteeman** [comment]
No there wont be a problem as a title should not have any line breaks in it and we are using this in very few places now

**Comment by dgrammatiko** [comment]
tooltips should never, ever have line returns, or be very long (few, really few words). Otherwise don't use tooltips use popover

**Comment by infograf768** [comment]
therefore it means that something like
<img width="572" alt="screenshotr10-09-02" src="https://user-images.githubusercontent.com/1296369/28613526-7c11a41a-71ea-11e7-8f2e-11e1c0886711.png">

will need popovers

**Comment by dgrammatiko** [comment]
this can be refactored so the actual title **dosn't** need expiation! It should be self explanatory. So let's fix the title and skip the tooltip all together there

**Comment by brianteeman** [comment]
There is no need for the title to be repeated in the title - therefore you dont need the html markup in there

**Comment by infograf768** [comment]
In this case, I strongly suggest you think twice about non-english languages as we have many places where descriptions/labels are twice as long as en-GB

**Comment by dgrammatiko** [comment]
@brianteeman @infograf768 from accessibility and UX perspective tooltips and popover indicate a poor design, most of the times. so in the above example instead of some meaningless `Configure ACL & Options` let's have something that describes better the action (even if it's longer, we can figure out the design later)

**Comment by brianteeman** [comment]
> In this case, I strongly suggest you think twice about non-english languages as we have many places where descriptions/labels are twice as long as en-GB

Not in J4 we dont

**Comment by brianteeman** [comment]
to be honest I am not even convinced that the string is even required in this example
