### ISSUE TITLE
[4.0] Namespace frontend modules

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#17258]
- [x] mod_articles_archive (https://github.com/joomla/joomla-cms/pull/17260)
- [x] mod_articles_categories (https://github.com/joomla/joomla-cms/pull/17269)
- [x] mod_articles_category (https://github.com/joomla/joomla-cms/pull/17321)
- [x] mod_articles_latest (https://github.com/joomla/joomla-cms/pull/17287)
- [x] mod_articles_news (https://github.com/joomla/joomla-cms/pull/17285)
- [x] mod_articles_popular (https://github.com/joomla/joomla-cms/pull/17286)
- [x] mod_breadcrumbs (https://github.com/joomla/joomla-cms/pull/17261)
- [x] mod_feed (https://github.com/joomla/joomla-cms/pull/17262)
- [x] mod_finder (https://github.com/joomla/joomla-cms/pull/17326)
- [x] mod_languages (https://github.com/joomla/joomla-cms/pull/17275)
- [x] mod_login (https://github.com/joomla/joomla-cms/pull/17319)
- [x] mod_menu (https://github.com/joomla/joomla-cms/pull/17320)
- [x] mod_random_image (https://github.com/joomla/joomla-cms/pull/17277)
- [x] mod_related_items (https://github.com/joomla/joomla-cms/pull/17283)
- [x] mod_search (https://github.com/joomla/joomla-cms/pull/17284)
- [x] mod_stats (https://github.com/joomla/joomla-cms/pull/17263)
- [x] mod_syndicate (https://github.com/joomla/joomla-cms/pull/17264)
- [x] mod_tags_popular (https://github.com/joomla/joomla-cms/pull/17281)
- [x] mod_tags_similar (https://github.com/joomla/joomla-cms/pull/17268)
- [x] mod_users_latest (https://github.com/joomla/joomla-cms/pull/17267)
- [x] mod_whosonline (https://github.com/joomla/joomla-cms/pull/17266)
- [x] mod_wrapper (https://github.com/joomla/joomla-cms/pull/17265)

**Comment by C-Lodder** [comment]
@laoneo - all modules done apart from `mod_finder`, which I'm going to need help on. 

It's to do with:

```
JLoader::register('FinderHelperRoute', JPATH_SITE . '/components/com_finder/helpers/route.php');
```

I've tried using `\FinderHelperRoute` however this still results in the class not being found. Only way I can achieve this, is if the files in the following directories are namespaced:

> components\com_finder\helpers
> administrator\components\com_finder\helpers

but that would mean the same should be done for all components.

Any ideas?

**Comment by laoneo** [comment]
If the file exists it should be fine. Did you add a \ before the JLoader code?

**Comment by C-Lodder** [comment]
yup, I added a `\` before `JLoader`. Didn't change anything

**Comment by C-Lodder** [comment]
All done. Thanks @wilsonge
