### ISSUE TITLE
0 after Search field

### ISSUE THREAD

**Issue by HK1966** [joomla/joomla-cms#17274]
Hello,

after every update i get an 0 after the Search field.
There is a solution, but i have to do this after every update.

Go to the mod_search folder and open mod_search.php

Comment out line 28 by changing: 
Code: Select all
$button         = $params->get('button', 0);

To: 
Code: Select all
// $button         = $params->get('button', 0);
It would be fine if it is getting part of the standard. 

Horst

**Comment by ghost** [comment]
@HK1966 thanks for contributing, can you make a Pull Request? How to make a [Pull Request](https://docs.joomla.org/Filing_bugs_and_issues#Issue_a_pull_request_directly_on_Joomla.21.27s_GitHub_repository).

**Comment by brianteeman** [comment]
I have seen this in the past and it was always because of an outdated mod_search override in the template

**Comment by HK1966** [comment]
Thank you!
I made an Pull Request.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17274">issues.joomla.org/tracker/joomla-cms/17274</a>.</sub>

**Comment by ghost** [comment]
thanks @HK1966, have you checked @brianteeman comment above?

**Comment by brianteeman** [comment]
Just commenting out a line of code is not a fix

**Comment by tonypartridge** [comment]
Replace the 0 with '' if the value is being output as 0. We don't want to break code but change the default value from what I understand of the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17274">issues.joomla.org/tracker/joomla-cms/17274</a>.</sub>

**Comment by tonypartridge** [comment]
I've checked the code and you must have a template override as @brianteeman states. The code you are removing is a yes/no identifier for the original module template.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17274">issues.joomla.org/tracker/joomla-cms/17274</a>.</sub>

**Comment by tonypartridge** [comment]
@franz-wohlkoenig can you close? Non-core issue
