### ISSUE TITLE
update notification ask to upgrade to older version than currently installed

### ISSUE THREAD

**Issue by joshelmich** [joomla/joomla-cms#17299]
[updatenotification.txt](https://issues.joomla.org/uploads/1/395a795d8c9cce078d35118c89c6335b.txt)### PROBLEM

I get this info in an email which is **repeatedly** :( sent to my email address

----------------------------------------------------------
this email IS NOT sent by Joomla.org. It is sent automatically by your own site,
BlahBlahBalh - http://www.blahblahblah.org/ 

================================================================================
UPDATE INFORMATION
================================================================================

Your site has discovered that there is an updated version of Joomla! available for download.

Joomla! version currently installed:        3.7.4
Joomla! version available for installation: 3.7.3

This email is sent to you by your site to remind you of this fact.
The Joomla! project will never contact you directly about available updates of Joomla! on your site.

---------------------------------------------------------------

### SOLUTION

Email is sent by updatenotification.php line 148-152 is responsible for notifying me that there is **older** version than the one **currently installed**!

// Check the available version. If it's the same as the installed version we have no updates to notify about. Please change 'eq' operator. Thanks!!

	if (version_compare($update->version, JVERSION, 'eq'))
	{
		return;
	}

**Comment by pacman10** [comment]
I'm getting exactly the same

**Your site has discovered that there is an updated version of Joomla! available for download
Joomla! version currently installed:        3.7.4
Joomla! version available for installation: 3.7.3**

several times a day but cannot work out from the steps under SOLUTION above what I have to do to stop it (who is supposed to change 'eq' operator, for example ?).

I've also spent quite some time going through the Joomla forum but cannot find any solutions I can understand. Everything seems to be in tech-speak and encrypted with obscure acronyms.

Surely there must be a simple solution with simple menu steps published somewhere.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17299">issues.joomla.org/tracker/joomla-cms/17299</a>.</sub>

**Comment by joshelmich** [comment]
file /plugins/system/updatenotification/updatenotification.php

is the culprit

where now is 'eq' should be 'gt' (see http://php.net/manual/en/function.version-compare.php)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17299">issues.joomla.org/tracker/joomla-cms/17299</a>.</sub>

**Comment by pacman10** [comment]
Thanks very much for this rapid answer. Much appreciated.

So if I understand correctly I should go to 
file /plugins/system/updatenotification/updatenotification.php
and edit that file to change 'eq' to 'gt' and that will solve my problem until Joomla! is updated again (unless the Joomla! powers-that-be in the meantime change the error themselves) ? Is that correct ? If so, where do I find the folder 
file /plugins/system/updatenotification ?
I've logged onto my site with FileZilla but cannot find it.

P.S. Aaaah, sorry. I've found a file with the same name  at /public_html/plugins/system/updatenotification. So now I edit the updatenotification.php there, right ?

**Comment by joshelmich** [comment]
All correct. Good luck!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17299">issues.joomla.org/tracker/joomla-cms/17299</a>.</sub>

**Comment by joshelmich** [comment]
It could be that the operator needs to ">=" in stead of "gt". Anyway you know what to tweak.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17299">issues.joomla.org/tracker/joomla-cms/17299</a>.</sub>

**Comment by pacman10** [comment]
Thanks very much, also for the clear instructions. I've changed it to ">=". As several of those incorrect notification mails were coming in each day I should soon see whether the change has had the desired result.

**Comment by ghost** [comment]
closed as having PR #17387<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17299">issues.joomla.org/tracker/joomla-cms/17299</a>.</sub>

**Comment by pacman10** [comment]
Since implementing the solution suggested by joshelmich in this thread I have no longer received any of the incorrect notification mails. As they were coming in every couple of hours before implementing the solution, and as the previous "gt" was clearly wrong, and as implementing the solution (change to ">=") has stopped the problem I conclude that that "gt" was the source of the error.
