### ISSUE TITLE
[3.7.4] Calendar not remember the value changed manually

### ISSUE THREAD

**Issue by fuscage** [joomla/joomla-cms#17304]
### Steps to reproduce the issue

Go to create a new article (content)
Select a date with the button in the end publication (for exemple 2017-08-31)  and close the calendar
Change manually the date value (without the calendar button) (for exemple 2017-07-01)
Click to the calendar button and the date is changed at 2017-08-31 instead of 2017-07-01

### Expected result

the calendar display the manually value

### Actual result

the calendar display the old value (choose with the calendar button)

### System information (as much as possible)

Joomla 3.7.4
Chrome Version 56.0.2924.87 (64-bit)

**Comment by ghost** [comment]
Issue confirmed. Behaviour also if "Finish Publishing"-Date is in Future.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17304">issues.joomla.org/tracker/joomla-cms/17304</a>.</sub>

**Comment by brianteeman** [comment]
is this not addressed by https://github.com/joomla/joomla-cms/pull/17183 ??

**Comment by ghost** [comment]
@brianteeman test #17183, didn't solve this Issue.

**Comment by drewgg** [comment]
@franz-wohlkoenig Hmm, #17183 does resolve this issue for me

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/713344/28685254-35894a34-72d5-11e7-9d37-cb12951c1b08.gif)

**Comment by ghost** [comment]
@drewgg you're right, this Time it wrks.

**Comment by dgrammatiko** [comment]
@drewgg please mark your test in that PR (using issues.joomla.org)

**Comment by ghost** [comment]
@dgt41 @drewgg can't cause he is creater of this PR.

**Comment by dgrammatiko** [comment]
@franz-wohlkoenig I made a mistake I meant to tag you...

**Comment by ghost** [comment]
is #17183 same Issue as this Issue?

**Comment by drewgg** [comment]
@franz-wohlkoenig yes

**Comment by ghost** [comment]
closed as duplicate Report of #17183.
@drewgg mark Test #17183 successfully done. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17304">issues.joomla.org/tracker/joomla-cms/17304</a>.</sub>
