### ISSUE TITLE
Feature Request(s) for com_redirect

### ISSUE THREAD

**Issue by pAnd0rASBG** [joomla/joomla-cms#17308]
It's great, that com_redirect comes as part of the core package, but unfortunately it is imho lacking features, which can make it complicated up to a level of not usable in production environments.

Suggestions:
* **Add Feature to ignore certain and/or all URL (GET) Parameters.**
Currently http://mysite.com/?aid=a and http://mysite.com/?aid=b will be counted as different URLs. This can be very annoying, since it will not only clutter the logged URLs, but also leave you with no way to create valid redirects, if you have visitors coming in with these.

* **Add at least basic wildcarding.**
Quite often you want to redirect a whole (virtual) subdirectory to another one, e.g. /blog/* to /newblog. In it's current form, you'd have to create a seperate redirect for every /blog/whatever URL, which is simply not feasible, let alone the cluttered list, if your old /blog/... url contains a few hundred posts.
Advanced (PREG-compatible) wildcarding would be even more awesome (e.g. redirect /blog/([a-z]*) to /newblog/$1). 

Best Regards

**Comment by tonypartridge** [comment]
The idea behind the component is to offer basic functionality for 404's out of the box. It's not a fully fledged redirects component. 

For what you want that's really what REDJ offers.

**Comment by brianteeman** [comment]
or htaccess for redirecting/renaming entire "folders"

**Comment by tonypartridge** [comment]
REDJ can do that, and not all servers support htaccess 😉.

**Comment by ghost** [comment]
i gave a thumbs-up for this Request cause i also missed some Functions on com_redirect. Another Plug in i try to avoid cause i wan't to make as much as possible by Core. Will look again on htaccess, if i can learn this.

**Comment by bembelimen** [comment]
I just saw this issue, perhaps this helps: https://github.com/joomla/joomla-cms/pull/17653 @pAnd0rASBG

**Comment by ghost** [comment]
@pAnd0rASBG if #17653 helps can you also please close this Issue?

**Comment by pAnd0rASBG** [comment]
Oh, that's really nice, thanks, closing the issue :)
