### ISSUE TITLE
A 404 error is thrown by Page Break plugin if pagination is used, without pagebreaks

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#17305]
This problem occurs when the Page Break plugin is enabled, and an article page uses a custom pagination feature for i.e. showing a list with extra items linked to an article, which if longer than 20 items, can be paginated using a JPagination object. This will result in the addition of the limitstart variable as an input var. This wasn't a problem before, but now with the modification in the Page Break plugin, this will throw a 404 error. Disabling the plugin makes the pages work normal again, and the custom list starts at page 2.

### Steps to reproduce the issue
Make sure the Page Break plugin is enabled. Open an article page which hasn't got a pagebreak tag in the content. At the end of the url add ?limitstart=20

### Expected result
The input var limitstart is at 20, so JPagination knows it's on page 2 (with limit set at 20)

### Actual result
A 404 error

### System information (as much as possible)
Joomla 3.7.3

### Additional comments
Not sure when this error occured, could be in Joomla 3.7.2, but in 3.7.1 is was working fine.

**Comment by ghost** [comment]
thanks for Report. Can you please look if #17127 is same Issue?

**Comment by brianteeman** [comment]
probably related to https://github.com/joomla/joomla-cms/pull/11217

**Comment by ghost** [comment]
#17127 is not the problem, the problem is on pages which aren't using page breaks

**Comment by eriknzzz** [comment]
But https://github.com/joomla/joomla-cms/issues/17127 is still my problem and I would appreciate some suggestions.

**Comment by ricardov03** [comment]
I present the same error in Joomla 3.7.4. I'm creating a custom module and I using the pagination.
The system return the same error when I have more then 1 page of products. Doesn't matter if you just have 1 product per page, the problem appears when I change the page with the pagination.

I see the variable that return the problem it's 'start' on the URL.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17305">issues.joomla.org/tracker/joomla-cms/17305</a>.</sub>

**Comment by julienlusson** [comment]
Same here, I've a module on an article page without page break in the text, but the module have multiple pages so, with this check only on the article text, if I click on the pagination I get a 404 error, if I disable the check from https://github.com/joomla/joomla-cms/pull/11217 it works.

**Comment by loewl** [comment]
I can also confirm this error, after the upgrade to Joomla 3.7.4 a custom module that works with pagination through GET (?start=100) throws a 404 Page Not Found error, the debug mode shows pagebreak.php on top of the callstack.
After deactivating the plugin, the pagination works correctly again.

**Comment by ReLater** [comment]
I've written a plugin that works partially similiar like plg_content_pagebreak with a toc and JPagination.

I get the described 404 error if plg_content_pagebreak is activated and the article contains no class="system-pagebreak" is present in the article.

https://github.com/joomla/joomla-cms/pull/11217 is wrong!

**Comment by ReLater** [comment]
Please test https://github.com/joomla/joomla-cms/pull/21290 and be loud if not accepted.

**Comment by ghost** [comment]
closed as having Pull Request #21290
