### ISSUE TITLE
Feature suggestion: Celebrating the contributors to Joomla.

### ISSUE THREAD

**Issue by Spudley** [joomla/joomla-cms#17306]
I have a feature suggestion for Joomla.

It would be really nice for the people who have contributed to the Joomla project to be given some recognition that would be seen by the people who use it.

It's great that I can come here to Github and see who's responsible for it, and even interact with them, but realistically speaking, most people who install Joomla will never come to the Github repo at all.

So I would like to propose a small module to be added to the control panel that shows a selection of avatars from the list of contributors as provided by the Github API. This will give some visibility to the hard work that goes into Joomla, and I hope will also encourage more people to consider contributing.

I have written a module to show what I mean - You can find it here: https://github.com/Spudley/mod_joomlacontributors

**Comment by brianteeman** [comment]
I like the idea (i did something myself a few years ago at https://spreadthejoomlalove.com/coders) but i am not sure if it is appropriate for inclusion in the core

**Comment by brianteeman** [comment]
I forgot to add that this would only include code contributors to the joomla core. Obviously people who write documentation, answer questions on the forum, write code in our other repos, translators and many many more are contributors as well

**Comment by zero-24** [comment]
There is already a new team here: https://volunteers.joomla.org/teams/volunteer-engagement-team maybe @Kubik-Rubik @yvesh want to take a look here.

**Comment by mbabker** [comment]
I think we should do better about putting this information into `joomla.org` webpages personally (I actually started redoing https://framework.joomla.org/contributors so it would [pull contributors from GitHub](https://github.com/joomla/framework.joomla.org/commit/7e5b8ceef82808f49e81004e5197ec735e54014c) versus the old static page that was a list of names from 2013).  So, it's definitely a worthwhile project, but IMO not something for the core distro.

**Comment by mbabker** [comment]
To add too, we do have various chunks of data spread all over the place:

- https://framework.joomla.org/contributors
- https://issues.joomla.org/activity/user/joomla-cms
- https://developer.joomla.org/wiki-activity.html
- https://spreadthejoomlalove.com/coders (unofficial but it has the data being talked about with this module)

Consolidating stuff into one main contributors area though would definitely be a positive step forward.  Even if the page right now just links to those resources.

**Comment by Spudley** [comment]
Thanks for all the comments here. I agree with a lot of what's been said.

I do still think there should be some space for giving credit in a way that will be seen by the average site owner, though. Whether it's in the form I suggested or not, I'm not too worried about, but I think there should be something.

I'm a strong advocate for open source software, but I always say that while it may be free to use, that doesn't mean it's not worth anything. Joomla is one of the most well-used applications on the web and is incredibly valuable. But too many of the people who download it and use it just don't get any visualisation of the effort that goes into it because they'll never visit any of the links above. The closest a lot of site owners get to seeing the wider Joomla community is searching for extensions on the JED. I'll bet that for a sizeable proportion of people, it doesn't even occur to them that they could actually contribute anything back to Joomla.

There's nothing wrong with that, but just think if we could encourage a few of them to get more involved. I feel that having some credits and a "How could you contribute?" link somewhere where they'll see it would go a long way toward doing that.

Anyway. That's all I'll say on the matter. :)  Thanks for listening.

**Comment by laoneo** [comment]
I like the idea of contributor recognition. As already said, there are a lot of other areas where people contribute. Perhaps we can collect stats from various sources and combine them in the volunteers portal. Just an idea.

**Comment by yvesh** [comment]
@laoneo the VET (Volunteers engagement team) is working with Sander and Co. on that :-) 

@Spudley Thank you for all the suggestions, we talked today in VET about it and a lot of these things are already on our todo-list. If you are interested in joining, just ping me at Glip :)

**Comment by laoneo** [comment]
Nice.

**Comment by ghost** [comment]
@Spudley as this is on the Way can you please close the Issue?

**Comment by tonypartridge** [comment]
I actually think a Core Joomla! Project component would be a good idea, showing events near by, latest news and contributors. 

We can make it uninstallable and enabled / installed by default on first install.

**Comment by Spudley** [comment]
@yvesh - I'm not familiar with Glip, so unsure how to ping you on it. I'd be interested in being able to take part though. I wouldn't be able to put in a lot of time, but if I can just lurk most of the time and contribute occasionally, I'd be happy with that.

@franz-wohlkoenig - sure, no problem. I'm happy to close the ticket if you think it should closed.

**Comment by heyjoecampbell** [comment]
I think the recognition should not be limited to code contributors, roles such as: designers, writers, editors, user group organizers, speakers, conference planners, merchandise/swag should be included as contributors. 

Why? Because it's true - Joomla is more than code, plus the initiative needs to attract & retain more skilled individuals to move things forward.

A "We Are Joomla!" page would be ideal - with a role filter of some sorts.

Creating such a page should be a campaign in itself (landing page, banners, article, dedicated team)
