### ISSUE TITLE
Comment for non-escaped $result->title

### ISSUE THREAD

**Issue by nicksavov** [joomla/joomla-cms#17324]
### Steps to reproduce the issue
1) Check out https://github.com/joomla/joomla-cms/pull/16484/files
2) Note that the security checks (i.e. the escapes) get moved to view.html.php (via the htmlspecialchars)

### Expected result

A comment to let a future coder know why it's not escaped

### Actual result

There's no comment

### System information (as much as possible)

N/A

### Additional comments

Adding the comment could be important for someone that looks at the file later down the road. They'd see that other variables are escaped, but those two aren't, and wonder why. A person might even submit code to escape it.

**Comment by ggppdk** [comment]
I would say to add a new property to the record

like
$result->title_escaped_highlighted

and leave $result->title untouched
since the way it is modified now it is inconsistent with all other template files

**Comment by tonypartridge** [comment]
@weeblr can you please add a comment on the reason from removing the escape?

**Comment by weeblr** [comment]
See https://github.com/joomla/joomla-cms/pull/17401

**Comment by ggppdk** [comment]
@weeblr 
nice , thanks for your works 

just it would have been better if a new property was added:
$result->title_escaped_search_highlighted    (or a shorter one)

this way 
-- the original issue would have been fixed
-- existing templates overrides would not need to be updated
-- consistent with all other template files where the ->title is not passed escaped, and it is also the original text unmodified

**Comment by tonypartridge** [comment]
@ggppdk whilst I see your point.. had the template developers followed the default Joomla! template all would be well.

**Comment by ggppdk** [comment]
@tonypartridge 

but since which date they should:

> had the template developers followed the default Joomla! template all would be well.

before the date that the change was introduced or after the date the change was introduced ?
anyway personally i care little of this, i think this can now be closed

**Comment by tonypartridge** [comment]
The problem is the developers have used escape around the title something which is common in Wordpress since they don't really sanitise any data naturally. 

But it's not needed in Joomla! at this level which we are rendering the template the content should already be escaped at the tmpl level.

**Comment by nicksavov** [comment]
Thanks for everyone's input! I think this issue is resolved now. But, if there's still a concern about a new property, please open a new issue report for it.
