### ISSUE TITLE
Notice: Undefined property: stdClass::$grid_id in libraries/joomla/form/fields/sql.php on line 308

### ISSUE THREAD

**Issue by justrustyspoons** [joomla/joomla-cms#17329]
### Steps to reproduce the issue
I have a custom module with a SQL form field

    <config>
        <fields name="params">
            <fieldset name="basic">
                <field
                       name="grid_id"
                       type="sql"
                       default="1"
                       label="Select an imagegrid"
                       query="SELECT grid_name AS value, grid FROM #__imagegrid" />
            </fieldset>
        </fields>
    </config>

### Expected result

No error

### Actual result

Notice: Undefined property: stdClass::$grid_id in libraries/joomla/form/fields/sql.php on line 308

### System information (as much as possible)

Joomla 3.7.4
Apache
MySQL

### Additional comments

Is this a problem with my module or something in Joomla core? Thanks

**Comment by zero-24** [comment]
This sql thing needs to have a key & value. Please take a look here: https://docs.joomla.org/SQL_form_field_type

Also the usage of the parameter `query` should be reduced please use the `sql_*` fileds in the from.

I'm going to close this as not a core bug thanks. Reopen if needed

**Comment by justrustyspoons** [comment]
Ah sorry, silly me! Thanks a lot! Fixed!
