### ISSUE TITLE
Time Zone settings in com_users

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#17333]
### Steps to reproduce the issue
- back end
- Global configuration > Server.
- Set "Server Time Zone": Zurich.
- Save configuration.

- Create a new user without any settings in tabulator "Basic Settings".

- Save the user and see "Basic Settings":
Time Zone ist "Zurich", **not "Use default" (as expected)**.

- Global configuration > Server.
- Set "Server Time Zone": El Salvador.
- Save configuration.

- Go back to user. 
- Time Zone ist still "Zurich"

Joomla 3.7.4

**Comment by ghost** [comment]
closed as having PR #17388<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17333">issues.joomla.org/tracker/joomla-cms/17333</a>.</sub>
