### ISSUE TITLE
[4.0] Popular tags PHP error

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#17330]
### Steps to reproduce the issue

- Open the frontend of the site
- Click "Popular Tags" in the "All modules" section on the left of the homepage
- Click one of the tags in the article

### Result

> Warning: Invalid argument supplied for foreach() in \components\com_tags\View\Tag\Html.php on line 320

Can be fixed by adding an `if` statement before the `foreach` loop

```
if ($this->item !== null)
```
but not sure that's the best approach

**Comment by zero-24** [comment]
hmm the exact same code is used in staging. Can you reproduce that on staging too? Maybe it is just because of missing sample data for that module?

**Comment by C-Lodder** [comment]
@zero-24 seems to work fine on staging

**Comment by zero-24** [comment]
Also without any tags in the sample data?

**Comment by C-Lodder** [comment]
Even without sample data, still works fine

**Comment by zero-24** [comment]
hmm i can no reproduce this on a clean install 4.0 ?

**Comment by C-Lodder** [comment]
Hmm, ok let me install a fresh copy of J4 as I haven't done so in a while. Will report back later on

**Comment by C-Lodder** [comment]
Reinstalling J4 worked
