### ISSUE TITLE
Joomla 3.7.4 installer enters infinite loop on delete/backup old tables

### ISSUE THREAD

**Issue by asliwinski** [joomla/joomla-cms#17342]
### Steps to reproduce the issue
Run the installer on Centos 7

### Expected result
Successful installation :)

### Actual result
Enters infinite loop on the first task (backup/delete of old tables):
```
XX.XXX.XXX.XXX - - [29/Jul/2017:04:27:17 +0200] "GET /installation/index.php?tmpl=body&view=install HTTP/1.1" 200 611 "https://example.com/installation/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
XX.XXX.XXX.XXX - - [29/Jul/2017:04:27:17 +0200] "POST /installation/index.php?task=InstallDatabase_remove HTTP/1.1" 200 361 "https://example.com/installation/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
```
The issue **does not occur** with version 3.7.3

### System information (as much as possible)
Joomla version: 3.7.4 (latest)
System: Centos 7
Server: nginx
PHP: either 5.4 or 7.1
DB: MySQL on a remote host

### Additional comments
https://stackoverflow.com/questions/45384730/joomla-installation-infinite-loop-on-delete-backup-old-tables

**Comment by zero-24** [comment]
Please test this patch: https://github.com/joomla/joomla-cms/pull/17248 thanks!
