### ISSUE TITLE
[4.0-dev] Drone fails on JS tests

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#17340]
### Steps to reproduce the issue

http://213.160.72.75/joomla/joomla-cms/7422

### Expected result

No errors

### Actual result

6 tests failed

### System information (as much as possible)

none

### Additional comments

none

**Comment by C-Lodder** [comment]
First part: https://github.com/joomla/joomla-cms/pull/17341

Think drone needs restarting though as it seems to have stopped

**Comment by zero-24** [comment]
> Think drone needs restarting though as it seems to have stopped

done

**Comment by C-Lodder** [comment]
thanks, 5/6 fixed.

**Comment by zero-24** [comment]
or should this be open until you could fix the last error?

**Comment by C-Lodder** [comment]
yeah leave it open for the time being.

**Comment by dgrammatiko** [comment]
@C-Lodder do you want me to fix this?

**Comment by C-Lodder** [comment]
If you could fix that last error, that would be great. I can't seem to figure out what the problem is.

**Comment by C-Lodder** [comment]
Only thing that may work is `.not.toContain('class');`

**Comment by dgrammatiko** [comment]
Line 42: 
```js
		it("should remove attribute class from icon", function() {
			expect($('#icon_0')).not.toHaveAttr('class', '');
		});
```
line 129:
```js
			it("should remove attribute style from icon", function() {
				expect($('#icon_0')).not.toHaveAttr('class', '');
			});

```


![screen shot 2017-07-29 at 23 04 35](https://user-images.githubusercontent.com/3889375/28747880-548d7606-74b2-11e7-8c4c-da895dce3e4c.png)


EDIT Scrap that, just remove both these tests, the GSOC student will patch this properly

**Comment by C-Lodder** [comment]
Done.

@zero-24 Drone tests passing now so you can close this issue

**Comment by zero-24** [comment]
Thanks!
