### ISSUE TITLE
[4.0] Warning: var_dump(): Couldn't fetch mysqli_result

### ISSUE THREAD

**Issue by matrikular** [joomla/joomla-cms#17350]
### Steps to reproduce the issue
Use var_dump(); or print_r(); to output the result of \JFactory::getDbo();

### Expected result
No warnings.

### Actual result
Warning: var_dump(): Couldn't fetch mysqli_result in [...]

### System information (as much as possible)
Windows NT DESKTOP-G94B9J7 10.0 build 15063 (Windows 10) i586
Database Version 5.5.5-10.1.25-MariaDB
Database Collation utf8mb4_unicode_ci
Database Connection Collation utf8_general_ci
PHP Version 7.1.7
Web Server Apache/2.4.26 (Win32) OpenSSL/1.0.2l PHP/7.1.7
WebServer to PHP Interface apache2handler
Joomla! Version Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT
User Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0

**Comment by C-Lodder** [comment]
Issue confirmed

**Comment by matrikular** [comment]
For what its worth, "first" call of [MysqliDriver::freeResult();](https://github.com/joomla/joomla-cms/blob/dfe84ffe1135198143bb58b16033faf3c076fb00/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php#L1093) seems to cause the warning.

**Comment by wilsonge** [comment]
Can no longer reproduce this so closing
