### ISSUE TITLE
wrong time (com_content) when publish new article

### ISSUE THREAD

**Issue by gocha-gochitashvili** [joomla/joomla-cms#17356]
### Steps to reproduce the issue

Add new article in article manager

### Expected result

when I add article was: 2017-07-31 12:52:00

### Actual result

it shows: 2017-07-31 12:30:00

### System information (as much as possible)

PHP Version: 7.0.21
Joomla Version: 3.7.4
Global Configuration->Server Time Zone: Tbilisi (Georgia Country)

### Additional comments

this method not working also for me. [#15853](https://github.com/joomla/joomla-cms/pull/15853)

**Comment by wojsmol** [comment]
Contact your hosting company and request a server time synchronization.

**Comment by gocha-gochitashvili** [comment]
solved width server time synchronization
