### ISSUE TITLE
[4.0] Cant log in after fail

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17366]
Try to log in to J4 with incorrect details.
You get the error but you never get a new login

See movie

![fake](https://user-images.githubusercontent.com/1296369/28786025-e253e250-760f-11e7-8e61-d8494079e454.gif)

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17366">issues.joomla.org/tracker/joomla-cms/17366</a>.</sub>

**Comment by C-Lodder** [comment]
https://github.com/joomla/joomla-cms/pull/17369

**Comment by ghost** [comment]
closed as having Pull Request #17369
