### ISSUE TITLE
Bug in AbstractUri::buildQuery - invalid HTML emitted ('[' and ']' not encoded in tagged elements list)

### ISSUE THREAD

**Issue by LivioCavallo** [joomla/joomla-cms#17365]
### Steps to reproduce the issue
Create a menu item of tagged-elements of a specific category

### Expected result
Valid HTML be generated to show required elements. In particolar we'll expect that '[' and ']' be replaced by %05B and %05D

### Actual result
Invalid HTML is emitted, '[' and ']' are used.
To locate the problem please look at the source html, or look at the page in IE or Chrome, as Firefox anyway shows embellished urlencoded links to the user!

### System information (as much as possible)
At least Joomla 3.4 to 3.7.4

### Additional comments
There was an old issue (https://github.com/joomla/joomla-platform/issues/833), closed as a no-problem. The issue remained anuway and now is a problem a real error with the introduction of tagged elements, as invalid html is not an option.

AbstractUri::buildQuery  (libraries\vendor\joomla\uri\src\  @ row 310) uses urldecode:
return urldecode(http_build_query($params, '', '&'));

I think it should be fixed by removing the urldecode part.
In fact there is no reason to urldecode here, as we are sending a response, non receveing, and http_build_query already builds a html-valid url-query-part.
And what's worst is that using urldecode we'll emit invalid html in the above mentioned case of tagged elements list!

(PS: In the above linked old issue someone mentioned compatibility with J!1.5; I do not know if that's right and anyway is compatibility with Joomla 1.5 still important?)

**Comment by zero-24** [comment]
@LivioCavallo the code you mention is placed in the upstream repo: https://github.com/joomla-framework/uri/pull/21 i have done a PR but can you please add there some test instructions so the maintainer there can take a look? Thanks!

As this is a upstream / joomla-framework issue I'm going to close this issue here please see the linked PR against the framework.
