### ISSUE TITLE
[3.7.4] [com_redirect] - Bulk imports URL wrong

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#17377]
### Steps to reproduce the issue
In com_redirect in the option Bulk import redirect a link like test to https://test.de/test
![image](https://user-images.githubusercontent.com/828371/28836753-8ab30e50-76ea-11e7-9107-6fc4c5b058d9.png)

You will see in the overview that 
/test is redirected to https://test.de/test
as you wanted

![image](https://user-images.githubusercontent.com/828371/28836813-bdf74240-76ea-11e7-9081-1849c2fac7f5.png)
but when you open this item you see that the domain was added to this adress with a slash (results in two //) so this redirect will not work.

![image](https://user-images.githubusercontent.com/828371/28836866-f5853f32-76ea-11e7-92e1-d9b8bd45ef77.png)

And adding the full URL is not correct, because if you would add the domain like that in manual mode you get an error message:

![image](https://user-images.githubusercontent.com/828371/28836973-6ef53a5c-76eb-11e7-9a09-1ecd2c15a1a4.png)

### Expected result
Bulk import should import the url like written in the textwindow

### Actual result
Bulk import adds the full domain in front ending with a slash / 

### System information (as much as possible)
Joomla 3.7.4

**Comment by ghost** [comment]
using "test" instead "/test" works.

**Comment by brianteeman** [comment]
@franz-wohlkoenig are you sure? What does it look like when you open the record

**Comment by brianteeman** [comment]
For reference the code is here
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_redirect/models/links.php#L215

**Comment by ghost** [comment]
@brianteeman there is no double //.

**Comment by coolcat-creations** [comment]
ok but when you edit it manually you have to start with / so it should work with /test proper...

**Comment by brianteeman** [comment]
![bulk](https://user-images.githubusercontent.com/1296369/28837869-3dfd05b0-76e6-11e7-822e-97feb52de36a.gif)

**Comment by coolcat-creations** [comment]
is this manually added? I have a error message there.

**Comment by brianteeman** [comment]
Closed as we have a PR for tessting see #17658

**Comment by tonypartridge** [comment]
Please test:

https://github.com/joomla/joomla-cms/issues/17661
