### ISSUE TITLE
[4.0] Issues with styling on floated alerts

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#17376]
### Steps to reproduce the issue

Open an article in the backend and click save

### Expected result

A green alert

### Actual result

- Chrome (top)
- IE11 and FF (bottom)

![screeny](https://user-images.githubusercontent.com/2019801/28833019-0c9bfe46-76d6-11e7-870f-339a972d86fb.png)

@dgt41

**Comment by dgrammatiko** [comment]
can you share a screenshot of the head of the document?

**Comment by C-Lodder** [comment]
I'm getting an error in the console too:

> too much recursion (webcomponents-cs.min.js)

###Screenshot of head:

![head](https://user-images.githubusercontent.com/2019801/28833484-5f7ab25a-76d7-11e7-9fe0-196bc45f0dbc.png)

**Comment by dgrammatiko** [comment]
So the alert stays like that? unstyled ?

**Comment by dgrammatiko** [comment]
The error is already fixed upstream

**Comment by C-Lodder** [comment]
I've just pulled the latest JS from the repo. Seems to work a little more now, but:

1. The alert colour is wrong (should be green, not blue)
2. In FF, when the alert initially appears, it has no styling for 0.5-1 second, then the styling appears

Seems fine in Chrome though

**Comment by ghost** [comment]
closed as having PR #17410<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17376">issues.joomla.org/tracker/joomla-cms/17376</a>.</sub>
