### ISSUE TITLE
Is this file unused?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17382]
While investigating another issue I discovered this file
`administrator\components\com_categories\models\fields\categoryparent.php`

It appears to be unused in the core as I can find no reference to it and it has been replaced by
`administrator\components\com_categories\models\fields\categoryedit.php`

If someone can confirm this then i will mark it as deprecated and to be removed in j4

**Comment by infograf768** [comment]
See my comment here about that file:
https://github.com/joomla/joomla-cms/pull/9749
The question remains: is it a full replacement for categoryedit and/or could it be used by 3pd?

**Comment by brianteeman** [comment]
Thanks for confirming we are not using  it in core
Yes it does appear to be a full replacement (with extras)
It could be used by 3pd that is true but I really dont like "unused" files in core as it has potential for all sorts of issues especially when changes are made.

So I propose to deprecate it here and remove it j4

?

**Comment by tonypartridge** [comment]
I agree to put is as a deprecation notice for J4 removal, devs will need to do quite a bit of work for J4 so they could always port this to their own component should they need it.

**Comment by brianteeman** [comment]
Closed
