### ISSUE TITLE
Custom profile field groups not saving!

### ISSUE THREAD

**Issue by musthafasm** [joomla/joomla-cms#17385]
### Steps to reproduce the issue

created custom user profile plugin with field groups other than "profile"

```
<?xml version="1.0" encoding="utf-8"?>
<form>
	<fields name="basic">
		<fieldset name="basic" label="">
                ........
```

While saving the registration form, it omits these field groups validation and saving
   
### Expected result

Should work same as if we use 

```
<?xml version="1.0" encoding="utf-8"?>
<form>
	<fields name="profile">
		<fieldset name="profile" label="">
                ........
```

### System information (as much as possible)

Joomla! 3.7.4

### Additional comments

**Comment by laoneo** [comment]
Would custom fields not help on that matter?

**Comment by musthafasm** [comment]
form fields loads perfect on initial screen but while submitting the form, the fields are not loading

**Comment by brianteeman** [comment]
Closing this as it can be handled by using custom fields.
