### ISSUE TITLE
Problem in persian calendar

### ISSUE THREAD

**Issue by balvard** [joomla/joomla-cms#17389]
### Steps to reproduce the issue
In persian language if choose calendar to select a date you see an error.
Date is currct but day name incorrect.
![Before change](https://www.alirezabalvardi.ir/images/before-solved-persian-calendar.png "Current version file")

### Expected result
if change this code in file date-helper.min.js the problem will be ok.
![After change](https://www.alirezabalvardi.ir/images/after-solved-persian-calendar.png "Solved problem")

### Actual result
At end of this file (media/system/js/fields/calendar-locales/date/jalali/date-helper.min.js) change this code :

from : return t=(t+1)%7};
to : return t=(t)%7};

### Additional comments
solved url
[Solved file](https://www.alirezabalvardi.ir/mynews/4-joomla-persian-calendar-java "Solved file")
Best Reg.
Alireza Balvardi

**Comment by tonypartridge** [comment]
@dgt41  can you review/make a pull?

**Comment by balvard** [comment]
I solved this problem.
I wait to update joomla and release this problem.
please see images.

**Comment by tonypartridge** [comment]
@balvard I saw that's why I asked dimitirs to review since he built the calendar into Joomla! You could create a pull request for your change @balvard

**Comment by infograf768** [comment]
@farhadst 
Please have a look

**Comment by dgrammatiko** [comment]
@balvard please make a PR with your changes so we can test it! Thanks

**Comment by balvard** [comment]
Hi to everyone
This problem just see in persian language and refer to jalali script in joomla 3.7.x
for test you can download latest joomla version (3.7.4) and install persian language.
so login with persian language and add new article , then in publishing tab choose calendar and make print screen.
then download this file : 
https://www.alirezabalvardi.ir/media/system/js/fields/calendar-locales/date/jalali/date-helper.min.js
and replace it on your joomla .
and open new article in new tab and select calendar.
Best Reg.
Alireza Balvardi

**Comment by farhadst** [comment]
@infograf768 Yes, this problem was to persian calendar
with file replacement problem fixed

**Comment by infograf768** [comment]
@dgt41  not sure @balvard will do pr, can you or shall I ?

**Comment by dgrammatiko** [comment]
@infograf768 please do so if you can!

**Comment by infograf768** [comment]
On it.

**Comment by infograf768** [comment]
@farhadst @balvard 
Please confirm https://github.com/joomla/joomla-cms/pull/17432

If OK, mark test OK in https://issues.joomla.org/tracker/joomla-cms/17432
