### ISSUE TITLE
Can't Reorder Nested Sub-Categories properly

### ISSUE THREAD

**Issue by jenniwoo** [joomla/joomla-cms#17384]
HELP ME!  Have mercy Joomla Developers and bug fixers.  Reordering bugs for Categories, I am sure, are your fault -- problems in your code -- and you must fix them soon.  I cannot finish alpha-sorting and re-nesting my over 500 categories in my Joomla 3.7 version of cagreenideas.org, the latter still my LIVE J1.5 site. Only since Joomla 3.5.1 Update came out end-of 2016 could I migrate my temporary intermediate J2.5 site (usgreenideas.org/cagi-j25) to J3.5.1 then more auto-updates onward to 3.7.4.  

Sorry for the lengthy description below, but I know of no better way for you all to get the "bigger picture" of this Category items sorting and reordering problem that in my experience has gone on, albeit it less troublesome variations since J2.5. 

Weeks ago on my J3.7.3 site I would reorder web link categories, very numerous in total as in > 200, press the "REORDER" icon at the top of the web links list.  To my horror the answer page was Article Categories.  However going back to the Web Links Categories page I would find the selected web link categories had been properly reordered. 

Most recently I had more oddly troublesome problems with categories sorting and reordering related to the setting of the "list limits" parameter: 

1. For weeks I could not get my J3.7.3 site, a cagreenideas.org subdomain site, to list more than 5 categories on a back-end Categories page. That was useless for reordering some sub-categories some of which had > 20 or even > 50 sub-category items in their parent category.  I have no idea what changed that limitation number or when or why.  

2. By trial and error I eventually reset the System->Global Configuration->Site-tab page's "list limit" parameter, which was never set at 5, resetting it from the default of 20 to 50 or 100.  Sometimes in J3.7.3 the setting had effect: List pages of Categories, Articles, Menus, web link categories and links all had those correct numbers of line items in their back-end lists.  However too often that was not the case and the list had only 5 items in it or 20, which again made reordering of longer portions of categories and subcategories impossible or extremely tedious.

BTW I have never yet had a reordering problem in a J3.4+ version of the cagreenideas.org/cagi-j3x site with reordering menu-items in menus, which I find odd if not also telling, and that knowledge would be helpful if I knew your code. This includes my J3.7.3 and most recent J3.7.4 versions of the cagi-j3x site, full URL of which is listed above. 

3. For several days before end-of-July 2017 I had set the "list limit" in Global Config->Site-tab page from 20 to 50 and somehow this time the 50-limit "stuck"; the menus, articles and categories I listed in the back-end had that-many line items.  Sorting or up-down arrow reordering of them or "change order number in an individual line-item" and click the reorder-icon at top-of-page reordered them correctly.  Also batch ordering seemed to work on groups of 2+ categories or sub-categories.  

I'm not sure when I upgraded from J3.7.3 to J3.7.4 but on 7/30/17 I changed the "list limit" from 50 to 100 and for the first time in months the 100-limit "stuck" also. For the next 24+ hours my article Categories list had 100 line-items on the list page and my reordering and re-nesting of categories in these longer lists (the latter making multi-level outlines of categories and sub-categories) proceeded rapidly.   

Then came 7/31/17 unexpected slightly different results.

4. On 7/31/17 I changed the "list limit" from 100 to 200 and got lists of Categories with only 5 items in them.  If at the bottom of the now 5-items-long Categories page I set 20 or 50 or more or ALL and pressed the adjacent Submit button, I got an answer page of Categories with 5 items.  

This was also the case today 8/01/17.  End of happy categories list sorting and reordering for me for I don't know how many more days or weeks or whatever. 

Therefore I repeat: HELP ME

And if necessary find and fix this problem I assume must be in the core code and release a well tested J3.7.5. 

I'll offer a re-positioned more private copy of the my J3.7.3 now 3.7.4 site I mentioned above for your bug testers' use, if that helps you make more exhaustive tests in the exact web site environment I have tried to describe briefly above.  The copy, however, will be at cagreenideas.org/cagi-j25nowj37. Let me know if you need an administrator account on it. 

Thank you.  JGW, 72 y.o, sf ca usa

**Comment by jenniwoo** [comment]
I forgot to make clear the following: I have tried to sort and re-nest both Web Link Categories and Article Categories for many months with problematic sorting and re-nesting results, in recent months in the Joomla 3.7.3 then 3.7.4 site with url in my original problem report. 

E.g. when I recently picked 6 items in a sub-category of article categories and numbered then 1-6 then used the Batch feature to move them to the top of their parent category, the first two items (1 & 2) ended up being items 1 and 3 under the parent category.  Item 3 became item 5 or 6 or 7.  Item 4 was maybe item 15 or more below. 

Other times I put a "0" in a category's existing order number be it sub-category or sub-sub-category, click the REORDER icon at the top of the page and that item usually ends up correctly at the very top of the list of sub-categories of their common parent item.  

Other times setting a new order number for category-item and clicking REORDER not only moves the item to the wrong place I intended within that level of categories, typically but not always the landing position is above or below the item I wanted to be near or replace, but much more problematically during that same reordering code execution, several unrelated PARENT CATEGORY ITEMS GET RESHUFFLED INTO A DIFFERENT ORDER.  

I've had 4-5 or so parent categories I had already put into alpha-sort order, go to the top or bottom of all the categories at that level. 

JGW 8/2/17 2:33 am PT <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17384">issues.joomla.org/tracker/joomla-cms/17384</a>.</sub>

**Comment by jenniwoo** [comment]
Correction: I've had 4-5 or so unrelated parent categories the parent category in which I would REORDER a sub-category item of an entiredly different parent category (all these parent categories I think at the same level, all of them in a much large set of categories, all of which I had put into alpha-sort order, result after the reordering in the unrelated 4-5 or so going, say, to the top or bottom of the former in-alpha-order set of parent categories.  Is that better?  That boggles my aging programmer's mind. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17384">issues.joomla.org/tracker/joomla-cms/17384</a>.</sub>

**Comment by ReLater** [comment]
Sounds like you're using the Hathor backend template?
Use the Isis template! Hathor is buggy and not longer (earnestly) supported.
https://github.com/joomla/joomla-cms/pull/15107

**Comment by ghost** [comment]
@jenniwoo can you please answer on above Comment?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17384">issues.joomla.org/tracker/joomla-cms/17384</a>.</sub>

**Comment by ggppdk** [comment]
You will need ISIS template together with a fix made for J3.8 (the PR is already merged for J3.8 ...):
https://github.com/joomla/joomla-cms/pull/11906

To be able to reorder them properly in J3.7.5 (since J3.8 is not yet released ...)
do 2 things
- Use ISIS template
- Set pagination limit to "all" 

for explanation read discussion in the above mentioned PR

i hope you do not have too many categories and thus you can Set pagination limit to "all" , without other issues

**Comment by ghost** [comment]
closed as Solution was given; can always reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17384">issues.joomla.org/tracker/joomla-cms/17384</a>.</sub>
