### ISSUE TITLE
[3.7.4] Small inconsistency in searchtools and category field in article

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#17380]
If you select a category in Searchtools the categories are displayed like that:
![image](https://user-images.githubusercontent.com/828371/28846953-b3499ea6-770d-11e7-9dea-c47a67187dc8.png)

If you select it in the Article, the Parent item has already a dash in front:
![image](https://user-images.githubusercontent.com/828371/28846979-cdf04e08-770d-11e7-930f-62aa902098cb.png)

So in one case its:
Category Parent
- category child

and in the other case 
- Category Parent
-- category child

It´s a very small and maybe not important issue but it confused a customer about the sublevels so i wanted to report it :)

**Comment by brianteeman** [comment]
confirmed and it is indeed wrong. If no one beats me to it I will take a stab at fixing this tomorrow

**Comment by brianteeman** [comment]
closed see #17383
