### ISSUE TITLE
[4.0] impossible to install js key

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#17397]
### Steps to reproduce the issue
using wamp64
adding db
put file of Joomla_4.0.0-dev-Development-Full_Package.zip in folder
start install
1 configuration ok
2 bdd all values are good but impossible to go in step 3
retrying to save step 2
windows browser retur this message "Last request has been refused becaus that contien an invalid marker. trying to refresh this page and re teste"
but nothing ...

### System information (as much as possible)
windows 10
wamp64 3.0.3

### additional informations
trying an j3.7.4 installation no problem

**Comment by ghost** [comment]
@micker is this still an Issue?

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 26th November 2017.

**Comment by ghost** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened.
