### ISSUE TITLE
[4.0] Incorrect datetime value: '' for column 'modified'

### ISSUE THREAD

**Issue by matrikular** [joomla/joomla-cms#17395]
### Steps to reproduce the issue
- Download and install the latest Joomla! 4.x-dev branch.
- Open Article: Field Groups and create a new field group.
- Give it a title and hit "Save".

### Expected result
The new group should have been saved.

### Actual result
The save process fails with the following error message:
> Error
Save failed with the following error: Incorrect datetime value: '' for column 'modified' at row 1

### System information (as much as possible)
Windows NT DESKTOP-G94B9J7 10.0 build 15063 (Windows 10) i586
Database Version 5.5.5-10.1.25-MariaDB
Database Collation utf8mb4_unicode_ci
Database Connection Collation utf8_general_ci
PHP Version 7.1.7
Web Server Apache/2.4.26 (Win32) OpenSSL/1.0.2l PHP/7.1.7
WebServer to PHP Interface apache2handler
Joomla! Version Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT
User Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0

**Comment by laoneo** [comment]
This should be fixed by pr #16962.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17395">issues.joomla.org/tracker/joomla-cms/17395</a>.</sub>

**Comment by brianteeman** [comment]
Closing
