### ISSUE TITLE
[4.0] Messages-Width wrong

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#17403]
### Steps to reproduce the issue
Some Messages-Width are fine (top), some to small (below):
![bildschirmfoto 2017-08-04 um 07 45 01](https://user-images.githubusercontent.com/8235763/28955801-4280a65a-78e9-11e7-8a86-da58d062eb87.jpg)
### System information
4.0.0-dev
macOS Sierra, 10.12.6
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
The smaller ones are only being that way as a temperary measure. They will be converted into a different type of display in due course

**Comment by ghost** [comment]
thanks @brianteeman for info.
