### ISSUE TITLE
Staging: Multilingual Menus with Home Page have lost their icons

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#17406]
### Steps to reproduce the issue
Create a multingual site with staging

### Expected result (test on a 3.7.4)
![screen shot 2017-08-04 at 10 52 30](https://user-images.githubusercontent.com/869724/28961730-a468b60e-7903-11e7-8398-492d224efa52.png)

### Actual result (on staging)

![screen shot 2017-08-04 at 10 58 11](https://user-images.githubusercontent.com/869724/28961817-f2b6a71c-7903-11e7-986c-49f09afc601c.png)

@izharaazmi 
Could it be a consequence of one of your PRs?

**Comment by izharaazmi** [comment]
Not sure but as I remember, I didn't add support for icons display yet.
This can be added now.

**Comment by infograf768** [comment]
This is what we had before in `enabled`:

```
if ($menuType->home == 0)
		{
			$titleicon = '';
		}
		elseif ($menuType->home == 1 && $menuType->language == '*')
		{
			$titleicon = ' <span class="icon-home" aria-hidden="true"></span>';
		}
		elseif ($menuType->home > 1)
		{
			$titleicon = ' <span>'
				. JHtml::_('image', 'mod_languages/icon-16-language.png', $menuType->home, array('title' => JText::_('MOD_MENU_HOME_MULTIPLE')), true)
				. '</span>';
		}
		elseif ($menuType->image && JHtml::_('image', 'mod_languages/' . $menuType->image . '.gif', null, null, true, true))
		{
			$titleicon = ' <span>' .
				JHtml::_('image', 'mod_languages/' . $menuType->image . '.gif', $alt, array('title' => $menuType->title_native), true) . '</span>';
		}
		else
		{
			$titleicon = ' <span class="label" title="' . $menuType->title_native . '">' . $menuType->sef . '</span>';
		}

```

**Comment by izharaazmi** [comment]
Well okay. I'll try to look into it this weekend.

**Comment by infograf768** [comment]
@izharaazmi 

We really can't release 3.8 with this bug.
Honestly I prefer reverting https://github.com/joomla/joomla-cms/pull/16451 than go without the flags.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17406">issues.joomla.org/tracker/joomla-cms/17406</a>.</sub>

**Comment by izharaazmi** [comment]
Sorry. I'll look at this today.

**Comment by izharaazmi** [comment]
@infograf768 I have done the fixes. I was trying to test with multiple menu
items but stuck. I am not able to create default menu item for different
languages.

I tried looking at the code but I don't understand it at –
libraries/src/Table/Menu.php:236

The entire if block (if ($this->home == '1')) does not look like doing what
it says. Can you please look and confirm. Also please advise if I might be
missing on something with multilingual menu homes.

**Comment by infograf768** [comment]
Closing as we have a patch
https://github.com/joomla/joomla-cms/pull/17511
