### ISSUE TITLE
[4.0] Sample Sites: Wrapper-Module to width

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#17404]
### Steps to reproduce the issue
Comparing Screenshots below shows Wrapper-Module to width:
![bildschirmfoto 2017-08-04 um 09 33 41](https://user-images.githubusercontent.com/8235763/28958881-69f03dd6-78f8-11e7-9591-2cc4ecf323b2.jpg)
![bildschirmfoto 2017-08-04 um 09 34 04](https://user-images.githubusercontent.com/8235763/28958885-6c8cfdd6-78f8-11e7-8ff1-cca8cba26059.jpg)

### System information
4.0.0-dev
macOS Sierra, 10.12.6
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
@ciar4n - how should we go about this one? There's a `width` parameter for the iframe in the wrapper module, which by default is set to `640px`. 

Do we just adjust the sample data and set it to `100%`?

**Comment by brianteeman** [comment]
The default width is 100% already
https://github.com/joomla/joomla-cms/blob/4.0-dev/modules/mod_wrapper/mod_wrapper.xml#L60

**Comment by brianteeman** [comment]
Ah I see what you mean now - its a mistake in the sample data

**Comment by C-Lodder** [comment]
Yup, but I'm referring to the sample data, which sets a value of `640`.

**Comment by brianteeman** [comment]
cross-posted ;)

**Comment by brianteeman** [comment]
I will do a PR now to fix that

**Comment by brianteeman** [comment]
Closed see #17424
