### ISSUE TITLE
No scrollbars when selecting an article on smartphone in menu item

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-cms#17400]
When selecting an article from the list in the menu item on small screens, eg. smartphones, then no vertical scrollbars are displayed. Opening the same page on a desktop pc, the scrollbars are shown.

In responsive mode:
![image](https://user-images.githubusercontent.com/251072/28925128-4096acc0-7864-11e7-897a-37949d4443fa.png)

In Desktop mode:
![image](https://user-images.githubusercontent.com/251072/28925172-621526f6-7864-11e7-977b-39b83f60bc51.png)

### Steps to reproduce the issue
- Open Chrome browser (or any other browser where you can emulate small screens)
- Set Screen width to 900px in the developer tools
- Create up to 10 articles in the back end
- Go to "Menus" -> "Main Menu"
- Click "New"
- Select "Articles" -> "Single Article"

### Expected result
The list has a vertical scrollbar as when no dev tools are activated.

### Actual result
No scrollbars are displayed.

### System information (as much as possible)
Joomla 3.7.4
Latest Chrome
Linux OS

**Comment by ciar4n** [comment]
@laoneo I believe this is expected behavior. Try opening any website in Chrome or Safari on a mobile device and you will notice there is no scroll bar until the page is 'touched'.

**Comment by laoneo** [comment]
I did open it also on my smartphone and had the same behavior.

**Comment by laoneo** [comment]
Is there some kind of official documentation around which explains the behavior. I mean if it is default behavior then we can close this issue.

**Comment by dgrammatiko** [comment]
@laoneo the modals are about to get a major refactor, moving the code from jQuery + Bootstrap to custom elements (mainly to remove the dependencies and fix the known a11y issues)

**Comment by ciar4n** [comment]
Many mobile browsers don't show scrollbars at all, while some show them only while scrolling. Been like that for a few years. I can't find anything official.. I think it is just a given at this stage.

**Comment by laoneo** [comment]
Ok, then I will close the issue.
