### ISSUE TITLE
[4.0] Single menu item edit associations broken

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#17411]
Associations tab is broken when editing a menu item

This is what we get for articles.

![screen shot 2017-08-04 at 16 18 47](https://user-images.githubusercontent.com/869724/28972664-cfb938a6-7930-11e7-86ee-37b8f014cbae.png)

This is what we get for a menu item
![screen shot 2017-08-04 at 16 15 53](https://user-images.githubusercontent.com/869724/28972693-e3db3be0-7930-11e7-9416-1da5b61a2524.png)

**Comment by ghost** [comment]
@mbabker should this be applied to a [Project](https://github.com/joomla/joomla-cms/projects)?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17411">issues.joomla.org/tracker/joomla-cms/17411</a>.</sub>

**Comment by brianteeman** [comment]
Closing as this appears to have been resolved elsewhere
<img width="599" alt="chrome_2018-03-25_13-33-57" src="https://user-images.githubusercontent.com/1296369/37875014-470f3678-3031-11e8-96a7-f4f11cc2f635.png">
