### ISSUE TITLE
Article Manager link to user

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17416]
In the article manager the name of the author is a link to the user details. I am not sure of the reason or benefit for this link BUT the problem is that there is no return value set when you follow the link. As a result when you close the user record you are at the user manager and not at the article manager.

**Comment by brianteeman** [comment]
The same is true with the linked user field in the conntact manager

**Comment by ghost** [comment]
I didn't get this Issue: Opening an Article i can select a User in a Modal Window and send back to Article.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17416">issues.joomla.org/tracker/joomla-cms/17416</a>.</sub>

**Comment by brianteeman** [comment]
It's in the article manager (the list of all articles) not the individual article view

**Comment by ghost** [comment]
Thanks Brian, got it. Both issues confirmed.
