### ISSUE TITLE
[3.8] Custom Fields - Create a "custom" position specifically for use in template overrides

### ISSUE THREAD

**Issue by jonrz** [joomla/joomla-cms#17414]
### Create a new field position called: custom (for override).

This position will not be outputted in the regular custom fields flow, and will only be displayed through a specific code within a template override. The code for individual field placement already exists, kindly provided by @gaelicwinter.

Basic instructions and code were added to the Joomla documentation.

**Comment by brianteeman** [comment]
If i understand you correctly then this can already be done

See https://docs.joomla.org/J3.x:Adding_custom_fields/Overrides<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17414">issues.joomla.org/tracker/joomla-cms/17414</a>.</sub>

**Comment by jonrz** [comment]
Let me ask this: After I load the fields helper, can I do "echo $item->jcfields->field-alias->field-value" or something like that to target the *specific field* I need? Or maybe field-id instead of field-alias, if it's decided to not implement field alias.

I'm not a PHP developer, and the code you referred me to is a "foreach", which, as far as I know, will render all fields in the same position.

What I mean, apart from the ability to use a simple one-line code to add just one specific field with the ability to choose between the label or the value, is also to remove the field from the standard flow (i.e. the field will not be rendered in any of the standard positions).

**Also:** 
The fieldshelper could be loaded by default, or maybe using a switch in the template options, to make things easier for everyone. 
We could have a field alias, to make targeting fields easier, and have reusable code across sites (especially useful for integrators).

**Comment by gaelicwinter** [comment]
In the top of the override you put this code in order to get a name-based array

foreach($item->jcfields as $jcfield)
{
    $item->jcFields[$jcfield->name] = $jcfield;
}

?>

//then down in your layout you reference the field itself 
<?php echo $item->jcFields['field-alias']-value; ?>

**Comment by gaelicwinter** [comment]
Sorry I forgot a character:

<?php echo $item->jcFields['field-alias']->value; ?>

**Comment by jonrz** [comment]
That's great!!! Thank's a million @gaelicwinter !

So, "name" is actually "alias". Good to know.
Why not using *alias*, since most Joomla users are familiar with the term, and "name" might confuse the field with something that would be displayed in the frontend?

Should I load the fields helper with the code
`<?php JLoader::register('FieldsHelper', JPATH_ADMINISTRATOR . '/components/com_fields/helpers/fields.php'); ?>` before using your *foreach* to get the name/alias?

Can I use `<?php echo $item->jcFields['field-alias']->label; ?>` to echo the label?

**Comment by jonrz** [comment]
And may I suggest having this named field addressing (plus the FieldsHelper load) implemented at the core by default, so we can just go ahead with the simple one-liner code? 
K2 did that and it is a success, with no apparent performance loss.

Also, we still need to create a custom position, to remove the field from the standard flow, so we can use the regular positions + the individually placed fields.

**Comment by gaelicwinter** [comment]
OK I just got home and looked it up.  Its actually called 'name', and my
code was not so clear, so the code should read like this.

//Top of template or layout override:
foreach($item->jcfields as $jcfield)
{
    $item->jcFields[$jcfield->name] = $jcfield;
}

?>

//In your display layout somewhere:
<?php echo $item->jcFields['name-of-field']->value; ?>

<?php echo $item->jcFields['name-of-field']->label; ?>

//The 'name-of-field' is whatever your field has entered in its 'Name'
field on the field edit form.

=============================================

**Comment by jonrz** [comment]
Thanks again @gaelicwinter 
Issue updated to include only the request for the custom position.

I've asked Sandra to add the following to the documentation: 
https://drive.google.com/open?id=1XitqQrZdFRKu7meNH_sorC_Zu64U7VeFSwFDkToJ0Ww

**Comment by brianteeman** [comment]
Sorry I still dot understand what you mean yesterday custom position 

Also the docs site is a wiki so if you think something can be improved then you should try to do it yourself and not ask for someone else to do it

**Comment by brianteeman** [comment]
Yesterday = by a

Autocorrect on my phone

**Comment by jonrz** [comment]
@brianteeman 
Thank you for the docs hint. I didn't realize it was an open wiki.

As for custom position, I mean this:
![custom_field_position](https://user-images.githubusercontent.com/25874295/29004178-cacd1442-7a99-11e7-87e2-0a6e04297b24.jpg)

I expect that if "no" is selected, fields won't be displayed at all. 
Keep in mind I'm used to K2, where if the fields are disabled, individually placed ones won't show.

**Comment by Bakual** [comment]
"No" means they are not displayed automatically. You will have to display it in an override or using the content plugin.

Imho, this issue can be closed.

**Comment by jonrz** [comment]
Many thanks @Bakual.
I'll update the docs to reflect that.

**Comment by laoneo** [comment]
Just for the record, here is the pr why the field called name and not alias https://github.com/joomla/joomla-cms/pull/14554.
