### ISSUE TITLE
Cache problem Joomla 3.7.4 Errors - The file Cache Storage is not supported on this platform...etc

### ISSUE THREAD

**Issue by roybinhood** [joomla/joomla-cms#17412]
### Steps to reproduce the issue
on a joomla 3.7.4 website i.e. www.preke.net

Note I have tried fixed related to previous versions of joomla but these do not work on 3.7.4

We have the following related cache problem/s

     a)In administrator under global configuration cache / system there is no option (example ‘file’) under Cache Handler.. It is just blank.

     b)Even before this the clear cache option under system in administrator returns a blank page.

     c) When we turn cache plugin on in backend then in front end of site everything is a white page.

     d) In Administrator / System Control panel next to word – joomla is following error in red

     “The file Cache Storage is not supported on this platform.”

### Expected result
a) File is shown as option under dropdown of Cache Handler

b) Clear Cache does not show blank page

c) Front page not blank when plugin cache turned on

d) In Administrator / System Control panel next to word – joomla is words
Joomla Version 3.7.4

### Actual result
As mentioned above

### System information (as much as possible)
Joomla 3.7.4

**Comment by tonypartridge** [comment]
Hello,

I don't think this is a Joomla! bug but an issue with your setup/configuration.

Go to: Joomla! Admin -> System -> System Information -> folder permissions

Are they all green except configuration.php which should be red?

**Comment by roybinhood** [comment]
Thank you for feedback 

I went to system info and  there are two are red 


configuration.php | Unwritable
-- | --
public_html/cache (Cache Folder) | Unwritable

But even when I change cache folder public_html/cache to 777 permission it still remains Unwritable in system info

**Comment by tonypartridge** [comment]
Hello,

This is a hosting error. Please contact your host to fix ownership / permissions of that folder.

Many thanks
Tony

**Comment by roybinhood** [comment]
I have , but I will again

**Comment by roybinhood** [comment]
They (hosts) say the ownership is fine and permissions are all writable so they say it is a Joomla thing :-)

**Comment by roybinhood** [comment]
Hosts on dedicated server said that they checked ownership and permission and all writable ... they say it is a joomla issue... maybe just my joomla issue , but I would appreciate any answers

**Comment by roybinhood** [comment]
Hosts resolved joomla issue in config file !!!

Ryan P.
Issue is resolved
I fixed it by updating the cache pathing here: ~'siteroot'/public_html/configuration.php
It was set incorrectly to public_html/cache. Should have been full pathing [/home/'siteroot'/public_html/cache/]

I changed siteroot from what it was ... to not post on here but you can see what was changed before that

**Comment by Quy** [comment]
Related to this issue #16862 ??

**Comment by tonypartridge** [comment]
Again, not an issue with the core. But an issue with the hosting /Joomla! Setup opposed to a bug. 

Can we close this?

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17412">issues.joomla.org/tracker/joomla-cms/17412</a>.</sub>

**Comment by Peeripapo** [comment]
So here's how i fixed it (in Joomla 3.9.2)

edit directly configuration.php and put:
public $cache_handler = '';

**Comment by ratanzania** [comment]
The permissions on the /cache and /administrator/cache need to be writable.

sudo chmod 777 /var/www/html/myjoomla/administrator/cache
sudo chmod 777 /var/www/html/myjoomla/cache
