### ISSUE TITLE
[4.0] Atum Green

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17420]
<img width="276" alt="screenshotr11-36-48" src="https://user-images.githubusercontent.com/1296369/29002491-9946c65a-7a9b-11e7-86f6-0839d2b2be9b.png">

There are two different greens being used. In the image above the status button is #438243 and the featured toggle is #64bd63

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/17422

**Comment by brianteeman** [comment]
Closed

**Comment by brianteeman** [comment]
Thanks @C-Lodder
