### ISSUE TITLE
Joomla 3.7.4, new user req.password field

### ISSUE THREAD

**Issue by dsimonse** [joomla/joomla-cms#17439]
### Steps to reproduce the issue
When at the backend gereration a new user the password field(s) is now requirerd. That was not required before since the password was auto-generated and sent to the user.

### Expected result
The password field(s) should not be required during backend registration and a auto-generated password should be sent to the user.

### Actual result
Typing a password is required

### System information (as much as possible)
joomla 3.7.4
YouJoomla 2.2.8
![user](https://user-images.githubusercontent.com/17233634/29034908-1cb7ed44-7b9a-11e7-9e67-f7aa4915f9a7.PNG)

**Comment by tonypartridge** [comment]
@dsimonse can you please confirm which Joomla! Version auto set the password? I've never known this to be a core feature of Joomla! Nor can I see it as a confirm option anywhere.

What you describe is a feature of Wordpress however.

**Comment by dsimonse** [comment]
Hi,
Well I'm not using Wordpress for sure. Been using Joomla for about 2 years now and I never had to register a password for a user, and the user got a password with the welcome email. So every Joomla version for the past 2 years.

**Comment by tonypartridge** [comment]
You are very right this is a mistake change. I'll look into it

**Comment by tonypartridge** [comment]
@dsimonse I've just checked J3.7.4 fresh install and these fields are not required on the backend. See:
![screenshot 2017-08-07 22 44 29](https://user-images.githubusercontent.com/1400982/29047158-65baa248-7bc2-11e7-89c3-e24c1778acde.jpg)

Can you reinstall Joomla! Core files and check you do not have a custom profile or registration plugin installed?

**Comment by dsimonse** [comment]
I reinstalled the core-files with no change. I haven't installed any new plugins and I don't know if ACYMailing could change this behaviour (installed an update recently)?

**Comment by tonypartridge** [comment]
I'm afraid you will need to test / check your 3rd party plugins and also check with english language although that shouldn't make a difference.

Many thanks
Tony

**Comment by dsimonse** [comment]
Will contact ACYMailing

**Comment by ghost** [comment]
closed as no Core Issue. Please reopen, if its a Core Issue, thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17439">issues.joomla.org/tracker/joomla-cms/17439</a>.</sub>

**Comment by dsimonse** [comment]
Hi,
Opened a case with ACYMAiling and here's their response:
*************
Hi, 

If you disable AcyMailing from your backend (http://rojteatern.nu/administrator/index.php?option=com_installer&view=manage) and then try to add user, the password is still mandatory, so I'm sorry but it seems that this doesn't come from AcyMailing..

Regards,

Alexandre - Acyba help desk team 
support@acyba.com 
*********************************
So, now I don't know what to do. Can I change a key in the DB to get the fields to not be mandatory?

//Dennis<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17439">issues.joomla.org/tracker/joomla-cms/17439</a>.</sub>

**Comment by tonypartridge** [comment]
I tested with acymailing and couldn't replicate it.

As originally suggested disable non core plugins.

**Comment by dsimonse** [comment]
Hi,

 

Please reopen, since I got response fron ACYMailing.

 

//Dennis

 

Från: Franz Wohlkönig [mailto:notifications@github.com] 
Skickat: den 8 augusti 2017 07:18
Till: joomla/joomla-cms
Kopia: dsimonse; Mention
Ämne: Re: [joomla/joomla-cms] Joomla 3.7.4, new user req.password field (#17439)

 

closed as no Core Issue. Please reopen, if its a Core Issue, thanks.

  _____  

This comment was created with the J!Tracker Application <https://github.com/joomla/jissues>  at issues.joomla.org/tracker/joomla-cms/17439.

**Comment by tonypartridge** [comment]
It's a non core issue? I cannot replicate in any J release that the fields are mandatory.

**Comment by dsimonse** [comment]
So, now I don't know what to do. Can I change a key in the DB to get the fields to not be mandatory?

**Comment by tonypartridge** [comment]
As originally suggested disable non core plugins.

**Comment by brianteeman** [comment]
It is not an issue with acymailing or with any non core plugins

As soon as you change/set a password option such as number of special characters then the password field is required. This is because the random password generator cannot create a password that satisfies those rules so the user would not be able to login. 

So if you want to have password as not required and use generated passwords then you have to reset the password options

**Comment by tonypartridge** [comment]
@brianteeman I agree, however in my tests the require asterisk was never shown when doing as you suggest. In his example the asterisk is there, the only thing that changed for me was it went to red for required in that scenario.

**Comment by brianteeman** [comment]
@tonypartridge set the  number of uppercase characters to 5 and you will see it changes to required

**Comment by tonypartridge** [comment]
Nope still shows as this.
<img width="472" alt="screenshot 2017-08-09 09 52 36" src="https://user-images.githubusercontent.com/1400982/29113277-8602ee62-7ce8-11e7-99cd-655fac1ecd7b.png">

However, I have just tried it on a clients site and noticed all fields are required by default. so will inspect it a bit more.

**Comment by dsimonse** [comment]
So what is the default settings? 
![usersettings](https://user-images.githubusercontent.com/17233634/29113601-c1eb4eb6-7cf1-11e7-8add-fd8f1d1f9eab.PNG)

**Comment by brianteeman** [comment]
<img width="393" alt="screenshotr10-51-44" src="https://user-images.githubusercontent.com/1296369/29115881-06094bb2-7cf1-11e7-805f-be595c08d43a.png">
<img width="331" alt="screenshotr10-51-59" src="https://user-images.githubusercontent.com/1296369/29115882-0619fa7a-7cf1-11e7-9df1-f186c483d9ab.png">

**Comment by dsimonse** [comment]
Hi, ok changed to "min 4" but no change. In fact the registration still opts for 6 characters.
"Use at least 6 characters, uppercase and lowercase letter, numbers and at least one special character."

**Comment by dsimonse** [comment]
The text seems to be related to RSFirewall. If I disable that the text dissapears but the password field are still mandatory.

**Comment by tonypartridge** [comment]
I've found the bug, looking into it now.

**Comment by tonypartridge** [comment]
Ok so as a fix for you, go to:

Joomla! Plugins -> User - Joomla! -> click save.

**Comment by tonypartridge** [comment]
@brianteeman  @dsimonse this was fixed 9 days ago:
https://github.com/joomla/joomla-cms/commit/dbc7a4af478a1941f43c38c52cd053ec4168343a

The issue occurs with certain upgrades of Joomla! where certain parameters are not set within the user plugin. Therefore the get request fails and falls to its default value. Which for some reason was 0 in the plugin. Next release of Joomla! will fix this.

**Comment by dsimonse** [comment]
Thanks! I disabled the "send email" and re-enabled it as per suggestion from RS and that fixed it as well.
But effectingly I clicked "save" :)

**Comment by sozzled** [comment]
Passing comment for @brianteeman @dsimonse @tonypartridge 

We've also been talking about this issue for the past week at the Joomla forum.  Has nothing to do with AcyMailing (as @brianteeman correctly points out) but see https://forum.joomla.org/viewtopic.php?f=706&t=953424

**Comment by tonypartridge** [comment]
@sozzled this has been solved. Please see my last comments.

**Comment by sozzled** [comment]
Yes, Tony, I understand the underlying cause has been addressed.  I was only making an observation in passing that additional background information (which has been around for longer than since @dsimonse opened the issue here) is available at the forum.  Aside from that, I agree there's no need to flog a dead horse.

**Comment by netmiller** [comment]
Thanks! Very much. I had same problem, and was lucky to find this conversation.
__"Joomla! Plugins -> User - Joomla! -> click save"__  helped also in my case !
