### ISSUE TITLE
How to add please select option in drop down of sql.

### ISSUE THREAD

**Issue by erakashpatel** [joomla/joomla-cms#17442]
Hello Joomla experts,

I have an issue with sql field type (custom field : https://docs.joomla.org/J3.x:Adding_custom_fields/Sql_Field)

I see all menu load in drop down. BUT i want to add select option (default) How can i add it?

Is there any way to add ?

Please suggest me.

Thanks in advance.

Thanks
akashpatel

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding.

**Comment by erakashpatel** [comment]
i am write here because its issue.
