### ISSUE TITLE
[3.8.0 beta] - error when system cache ON 

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#17448]
### Steps to reproduce the issue

1. 3.8 beta + sample data
2. global configuration -> system
3. set  System Cache ON
4. set Cache Handler file or redis etc... doesn't matter
5. visit home

### Expected result
page rendered

### Actual result
 Class 'Joomla\CMS\Document\Renderer\Html\stdClass' not found 

1 | () | JROOT/libraries/src/Document/Renderer/Html/ModuleRenderer.php:89
2 | Joomla\CMS\Document\Renderer\Html\ModuleRenderer->render() | JROOT/libraries/src/Document/Renderer/Html/ModulesRenderer.php:47
3 | Joomla\CMS\Document\Renderer\Html\ModulesRenderer->render() | JROOT/libraries/src/Document/HtmlDocument.php:491
4 | Joomla\CMS\Document\HtmlDocument->getBuffer() | JROOT/libraries/src/Document/HtmlDocument.php:782
5 | Joomla\CMS\Document\HtmlDocument->_renderTemplate() | JROOT/libraries/src/Document/HtmlDocument.php:557
6 | Joomla\CMS\Document\HtmlDocument->render() | JROOT/libraries/src/Application/CMSApplication.php:1117
7 | Joomla\CMS\Application\CMSApplication->render() | JROOT/libraries/src/Application/SiteApplication.php:780
8 | Joomla\CMS\Application\SiteApplication->render() | JROOT/libraries/src/Application/CMSApplication.php:273
9 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/index.php:49

### System information (as much as possible)

db   5.7.19-0ubuntu0.17.04.1 
php 7.0.18-0ubuntu0.17.04.1

**Comment by mbabker** [comment]
Direct committed the fix at https://github.com/joomla/joomla-cms/commit/322a477a5c0a22bcf4b3d57a293791115427bfe6

**Comment by alikon** [comment]
thanks
