### ISSUE TITLE
[4.0] Module Class Suffix echo'd twice

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#17440]
The main issue is that in most cases the 'Module Class Suffix is been echoed twice. With a couple of exceptions if you inspect a module in the frontend you will notice the class been echoed at a modChrome level and again inside the module itself.

In the following example Module Class Suffix = card-outline-danger

![suffix](https://user-images.githubusercontent.com/2803503/29049704-7c1c1532-7bcf-11e7-93ea-1e340651ce2b.png)

Personally I think the class should be moved to the outer container (eg. top-b) and removed from within the module.

**Comment by C-Lodder** [comment]
Does this online apply with Custom Modules?

Also, I believe you're targeting the modules in you CSS-grid script with the `top-b` (etc) classes aren't you?

**Comment by ciar4n** [comment]
Module suffix is been echoed in all modules except for mod_login and mod_wrapper. It is been echoed again in most module chromes with the exception I think of 'none'.

I added the position name as a class to each module with the CSS grid PR however it is currently not been used.

**Comment by ciar4n** [comment]
PR created..  #17447
