### ISSUE TITLE
Display images in mod_articles_category and show them small (resize image)

### ISSUE THREAD

**Issue by AFlorencia** [joomla/joomla-cms#17446]
Many times I found myself doing overrides to show images in this module, so I wonder why this is not part of the core, and also if there's some library included to resize the images to make them look as thumbnails.
I'm sure this will be welcome by all the Joomla comunity as this fill the gap and avoid us from installing third party extensions to have this feature. 
Also with overrides we can have as many designs as we want.
I want this with all my heart! 
Thank you!

**Comment by kavadas** [comment]
Resizing an image when the page loads is a really bad practice.

It can make your site slow or even break it ( if the image to be resized is large ).

Resizing should be done when the image is uploaded. So i don't think that this feature should be added in the module.

**Comment by ghost** [comment]
Would be fine to have different sizes generated at upload setting an Anchor for most important Part of Image.

**Comment by AFlorencia** [comment]
Kavadas, I didn't mean resize the image after upload, or on paged load I meant create thumbnails in case is necesary, what Franz said is ok for me.
This could fill the gap and give us another choice to third party modules, one module:  millions ways to display the info just aplying some fancy CSS.

**Comment by brianteeman** [comment]
As @kavadas says this is not something for the module but it would be a create thumbnails (or small image) on upload and therefore part of the media manager. 

That cannot be done in J3 but maybe the team working on the new media manager for J4 will consider it (or maybe they already have)

Please post your request here https://github.com/joomla-projects/media-manager-improvement/issues
