### ISSUE TITLE
[3.8 beta1] Help screens

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17459]
the help screens need to be set up as currently they give an error
```

RuntimeException
Error fetching page from MediaWiki API: The page you specified doesn't exist
```

**Comment by mbabker** [comment]
// @Sandra97 @Hutchy68

**Comment by Sandra97** [comment]
As 3.7 and 3.8 are the same Help Screens, we usually apply the change of namespaces and redirections when the sable is released. So it's an expected behaviour for 3.8 
But I may be wrong, it's more Tom's area than mine.

**Comment by Hutchy68** [comment]
Should be working now. We just alias Help38 to Help37 until v3.8 is released.

**Comment by brianteeman** [comment]
well you dont get an error but you do still have 3.7 in the title

**Comment by Hutchy68** [comment]
And that's the way it will be until 3.8 is released

**Comment by brianteeman** [comment]
i thought so but just wanted to confirm 

thanks for setting up the alias
