### ISSUE TITLE
feature request | send Message to Telegram Bot when update available

### ISSUE THREAD

**Issue by syswombat** [joomla/joomla-cms#17457]
### Steps to reproduce the issue
Option to add Telegram Chat_ID and bot Token 

### Expected result
whene core or Module has update a Message would be send like.
Domain
Core Update to 3.x.x
Module Update to x.y 
available 
please update asap

**Comment by C-Lodder** [comment]
Does something like this really need to go into core? Can you not just make a plugin for it instead?

**Comment by mbabker** [comment]
Yes, this would be better suited as a plugin listed on the JED than a core feature.
