### ISSUE TITLE
[3.7.4 and older] Default language code visible in Language Switcher Module

### ISSUE THREAD

**Issue by simbus82** [joomla/joomla-cms#17468]
### Steps to reproduce the issue
Enable a multilanguage Joomla (for example IT and EN)
Enable rewrite and htaccess
Publish a language switcher module (in my case inline mode)
Set the language filter plugin to remove default lang code, automatic change, etc (all option to yes!)
Create language associations for menu voices.

### Expected result
My default language is it-IT
Language switcher module should create links like **www.mysite.it/page1italian** if i'm in the page **www.mysite.it/en/page1english** . When i click the link for change language, browser open soon the right page with url **www.mysite.it/page1italian**.

### Actual result
My default language is it-IT
Language switcher module now create links like **www.mysite.it/it/page1italian** if i'm in the page **www.mysite.it/en/page1english**.
When i click the link for change language, a 301 redirect send me to www.mysite.it/page1italian.

### System information (as much as possible)
Joomla 3.7.4
All recommend system specification respected

**Comment by Bakual** [comment]
Afaik that is expected behavior. We need the /it/ so we can detect that you want to change the language. Without it you would end up on your current language (as stored in your language cookie).

**Comment by infograf768** [comment]
Expected indeed. Closing issue.

**Comment by simbus82** [comment]
Thanks for explanation @Bakual 👍
