### ISSUE TITLE
[4.0] Multilingual broken when default site language is not en-GB

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#17467]
When the default site language is not en-GB, I get a 1140 with
`1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause `

Looks related to ` ONLY_FULL_GROUP_BY` issue

In fact multilang routing is verymuch broken. When setting default site language to en-GB and switching to French, I get URLs of type
`http://localhost:8888/joomla_400/fr/categoryfrench/fr?option=com_content&view=featured&Itemid=102`
for any language which is not en-GB

**Comment by ghost** [comment]
@mbabker should this be added to [Projects](https://github.com/joomla/joomla-cms/projects)?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17467">issues.joomla.org/tracker/joomla-cms/17467</a>.</sub>

**Comment by infograf768** [comment]
We do have other issues as multilang is still fully broken (@Hackwar ), but not this one any more.
Closing.
