### ISSUE TITLE
[staging] Notices  Trying to get property of non-object

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#17462]
Install staging.
PHP logs show 2 Notices:

[10-Aug-2017 06:34:43 UTC] PHP Notice:  Trying to get property of non-object in ROOT/libraries/src/Updater/Adapter/ExtensionAdapter.php on line 127

[10-Aug-2017 06:34:43 UTC] PHP Notice:  Trying to get property of non-object in ROOT/libraries/src/Updater/Adapter/ExtensionAdapter.php on line 128

And, logically, same errors when trying to Find Updates in Extensions=>Manage=>Update
And when displaying Joomla Update component.

**Comment by AlexRed** [comment]
I can confirm the problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17462">issues.joomla.org/tracker/joomla-cms/17462</a>.</sub>

**Comment by ghost** [comment]
Status is now "Confirmed".

**Comment by infograf768** [comment]
Possible patch posted here:
https://github.com/joomla/joomla-cms/issues/17452#issuecomment-321490824

**Comment by ghost** [comment]
@infograf768 should i close Issue?

**Comment by infograf768** [comment]
I suggest we wait for @mbabker reply

**Comment by mbabker** [comment]
Closing issue, same as #17452 (which has a fix, just needs to be turned into a PR).
