### ISSUE TITLE
Feature Request: Set Module "Tags - Popular" a Parent Tag

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#17466]
### Steps to reproduce the issue
Module "Tags - Popular" can show all Tag of an Site. It would be helpful to set displayed Tags in a Cloud for a specific Tag and its Children.
### System information
3.8-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by tonypartridge** [comment]
Hello @franz-wohlkoenig so basically you want to select a parent tag in the module config and show all it's children in the frontend?

**Comment by ghost** [comment]
@tonypartridge yes, thats my Feature Request. Goal is to have multiple Instances of Module showing different Sets of Tags.

**Comment by brianteeman** [comment]
Closed - please test #17562
