### ISSUE TITLE
[3.8.0] com_users - search tools issues

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#17460]
### Steps to reproduce the issue
Users -> manage
click on searchtools

### Expected result
filter fields are correctly populated and you are able to filter user data
![screenshot from 2017-08-09 18-38-18](https://user-images.githubusercontent.com/181681/29132889-f53e9ab2-7d31-11e7-83fc-eb1eaf6a1f31.png)

### Actual result
![screenshot from 2017-08-09 18-39-11](https://user-images.githubusercontent.com/181681/29132930-1688c706-7d32-11e7-9f88-122032bf65f6.png)

with modal 
![screenshot from 2017-08-09 17-41-04](https://user-images.githubusercontent.com/181681/29132723-6aa07484-7d31-11e7-96de-2064edd23574.png)

### System information (as much as possible)
3.8.0-beta
firefox 54

**Comment by ghost** [comment]
Can't confirm. Search Tools are shown and working as expected.
### System information
3.8-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by alikon** [comment]
made a pr #17477

**Comment by laoneo** [comment]
As class names are not case sensitive in PHP and we have a convention that form files do exist in lowercase name [this](https://github.com/joomla/joomla-cms/blob/3.7.4/libraries/joomla/form/helper.php#L204) code loads the class in < 3.8. Now it is different, so we need to find a way to have the same set up. I will check it in the next few days for a proper solution. Till then I suggest to close the pr #17477 and reopen this one and mark it as release blocker.

**Comment by mbabker** [comment]
That line is only problematic if you're scanning the filesystem to find a not-yet-loaded class, it won't be hit if something hits the autoloader first.  What we have in the class mapping file won't work for these fields because their properly declared cases aren't anything that were ever autoloaded to begin with, so for form fields we might need to just uppercase the first character after `JFormField` and leave everything after lowercased.

**Comment by alikon** [comment]
reopen as requested

**Comment by laoneo** [comment]
Please test #17584, it should fix the issue.

**Comment by ghost** [comment]
closed as having Pull Request #17584<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17460">issues.joomla.org/tracker/joomla-cms/17460</a>.</sub>
