### ISSUE TITLE
'combo' form field type validation is delayed

### ISSUE THREAD

**Issue by paul-muckypuddle** [joomla/joomla-cms#17464]
### Steps to reproduce the issue
1. Create a form field of type `combo` with the `required` attribute set to `true`
2. Access a screen displaying the form field
3. Select an option

### Expected result
The field contains the selected option and no validation highlighting

### Actual result
The field is highlighted as invalid (i.e. red, bold text and a red border) until a second valid selection is made (or another pair of focus / blur events occur on the field)

### System information (as much as possible)
Joomla 3.7.4
PHP 5.6.30
Apache 2.4
Centos 7

### Additional comments
- Video of issue in action: http://support-media.muckypuddle.me/lxH0
- Field XML tested:
```
<field name="etd" type="combo" filter="text" required="true" label="COM_XXX_FORM_LBL_XXX_ETD" description="COM_XXX_FORM_DESC_XXX_ETD" hint="COM_XXX_FORM_DESC_XXX_ETD">
      <option value="1">1 Hours</option>
      <option value="2">2 Hours</option>
      <option value="3">3 Hours</option>
      <option value="4">4 Hours</option>
      <option value="5">5 Hours</option>
      <option value="6">6 Hours</option>
      <option value="7">7 Hours</option>
      <option value="8">8 Hours</option>
      <option value="9">9 Hours</option>
      <option value="10">10 Hours</option>
      <option value="11">11 Hours</option>
      <option value="12">12 Hours</option>
</field>
```

**Comment by chmst** [comment]
Very old issue and the linked Video does not exist anymore.  

But valid issue. In J4 the Formfield type="combo" does not work at all. 
Obviously nobody ever used this field type.
