### ISSUE TITLE
[3.8 Beta] Fatal Error when trying to select any menu item in administration  > Menus

### ISSUE THREAD

**Issue by Gitjk** [joomla/joomla-cms#17479]
### Steps to reproduce the issue
After update to 3.8 Beta

### Expected result
All Administration menus working

### Actual result
When I try to select any menu item in 'Administration' > 'Menus' dropdown list, I get this fatal error:
Fatal error: Call to undefined method JModuleHelper::isAdminMultilang() in ...\administrator\components\com_menus\controller.php on line 34

### Additional comments
Does anybody have the same issue or is it just me again? :-)

**Comment by ghost** [comment]
Can you please try to install 3.8 and not update.

**Comment by Gitjk** [comment]
> Can you please try to install 3.8 and not update.

I can try that later today.
Meanwhile I encounter another error in the updated site. When I enable the new router in 'Content' > 'Articles' > 'Options', I get a "404 URL invalid" when selecting an article from a category blog or category list in the frontend.

Call stack
--
# | Function | Location
1 | () | JROOT\libraries\src\Router\Router.php:237
2 | Joomla\CMS\Router\Router->parse() | JROOT\libraries\cms\router\site.php:133
3 | JRouterSite->parse() | JROOT\libraries\cms\application\cms.php:1146
4 | JApplicationCms->route() | JROOT\libraries\cms\application\site.php:795
5 | JApplicationSite->route() | JROOT\libraries\cms\application\site.php:215
6 | JApplicationSite->doExecute() | JROOT\libraries\cms\application\cms.php:265
7 | JApplicationCms->execute() | JROOT\index.php:49

**Comment by Gitjk** [comment]
Now tried a fresh installation of the full J3.8 Beta package and imported the database from the updated site afterwards in order to have content available. Result: I can't enable the new router in the options. The 'Experimental' button remains red if click it. No error message visible (Debug enabled).

**Comment by brianteeman** [comment]
You cant just import the database - that will mean you have joomla 3.8 files and a joomla 3.7 database structure

**Comment by Gitjk** [comment]
>...that will mean you have joomla 3.8 files and a joomla 3.7 database structure

I thought that clicking the 'Fix database' button updates the db tables. (The corresponding button of the shopping cart extension I use does have this kind of 'intelligence' :-)

I think this issue can be closed too, because as I wrote in (https://github.com/joomla/joomla-cms/issues/17478) my next attempt did work.

BTW - I think in the J3.8 stable release the 'Experimental' label of the router button should be changed. Doesn't make sense to me to release a 'stable' version with the new router when the release manager(s) still consider it 'experimental'.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17479">issues.joomla.org/tracker/joomla-cms/17479</a>.</sub>

**Comment by landed1** [comment]
I have this issue in one site after updating to 3.8 in the normal way. Do you want me to submit this same bug again?

**Comment by ghost** [comment]
@landed1 if the Issue isn't reported yet please open a new Issue.

**Comment by landed1** [comment]
It is this issue so has been reported but was closed. I have the error when trying to select a menu in the backend just as in this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17479">issues.joomla.org/tracker/joomla-cms/17479</a>.</sub>

**Comment by ghost** [comment]
sorry i meant if its new reported since 3.8 is out.
