### ISSUE TITLE
[Update 3.7.4 to 3.8 b1] The sample data module does not exist

### ISSUE THREAD

**Issue by RoscioZ** [joomla/joomla-cms#17471]
Hello!

### Steps to reproduce the issue
Install joomla 3.7.4, upgrade to joomla 3.8. b1

### Expected result
Possibility to create sample data module

### Actual result

The sample data module does not appear in the list of modules that can be created

### System information (as much as possible)

PHP Built On 	
**Database Version:** 5.6.33-log
**Database Collation:** utf8_general_ci
**Database Connection Collation:** utf8mb4_general_ci
**PHP Version:** 5.6.29
**Web Server:** Apache
**WebServer to PHP Interface:** cgi-fcgi
**installed on:** http://altervista.org Free hosting

**Comment by mbabker** [comment]
You did switch the module manager to show admin modules, correct?  The new module is not a frontend module.

**Comment by mbabker** [comment]
Also, for existing sites updating, the module is installed in a disabled state, so you'll need to enable it from the Extension Manager.

**Comment by RoscioZ** [comment]
Yes switch to admin modules, the problem was that it is disabled, thank you 👍

**Comment by fyre1212** [comment]
Develop your career with[ UniCCM](https://www.uniccm.com/ "UniCCM")! Our comprehensive programs in contract management, CAD design, NPORS and SMSTS accreditation and cyber security are designed to equip you with the essential skills and qualifications employers demand. Flexible online learning options allow you to study at your own pace while benefiting from the insights of experienced industry professionals. Don't miss the opportunity to invest in your future - enroll now and expand your career prospects.

https://www.uniccm.com/ 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17471">issues.joomla.org/tracker/joomla-cms/17471</a>.</sub>

**Comment by fgsw** [comment]
Above comment is spam.
