### ISSUE TITLE
Custom Fields - Type - User Groups

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#17474]
Hi guys, 
Joomla 3.7.4, creating a new Custom Field - Type - User Groups, looking to have a User field where to select "No/Yes" to add User to another User Group (in teory moving him from "Registered" 2 to "Associated" 10). So:

 - Default User Groups (A comma separated list of user groups ids): 2, 10
 - Multiple: No

**BUG ?** "Default" can be only one ?!? No ?
**BUG ?** Is shown as default always the highest Group ID
**BUG ?** Always is shown the entire User Groups list, I cannot limit the User Groups. Too dangerous, a user can be wrongly added to another user group, also as "Super User"
**BUG ?** Also setting "Multiple" to "Yes" the two user Groups are prefilled, but I can always select other User Groups from the list (too dangerous).
Please, Can you confirm ?

I suppose the two fields have to be modified and a field is missing, like:

 - Default User Group (only one): 2
 - **User Groups** (A comma separated list of user groups ids): 2, 10 (the only User Groups shown)
 - **View** (Multiple): ... Should have to be changed as "View", where to select from: Multiple No / Multiple Yes / List No/Yes, where for each listed User Group I can select No/Yes

**Comment by ghost** [comment]
@joomleb i didn't understand the Issue. Can you please explain or maybe another one understand?

**Comment by brianteeman** [comment]
I am closing this due to lack of response - it can always be reopened if updated
