### ISSUE TITLE
Custom Fields - Type - Media to upload pdf

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#17475]
Hi guys, 
as far as I understand, we'd have to use a Custom Fields - Type - Media to upload a pdf:

In **First** of all:
  1 - **How to limit the upload file type** only to .pdf files for this field ?
  2 - **How to** set the "**Maximum upload size**: ... MB" for this field ?
Seem these are two "Media" field Type option missing on the field creation.

**Second - BUG** I created a "Media" field Type, and yes, I can upload the pdf Files, but when uploaded, in the Media selector window pop-up, I cannot see the pdf file uploaded (so, I cannot select it).
I checked and I confirm the pdf file has been loaded correctly. Can you confirm ?

**Third**, cannot test the "Preview" field if there is the simple way to show the pdf file as **linked pdf icon** where clicking open it in a new window tab

**Comment by ghost** [comment]
can you please look if #10871 is related?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17475">issues.joomla.org/tracker/joomla-cms/17475</a>.</sub>

**Comment by joomleb** [comment]
Seem Yes, (sorry and thanks)...but that ticket is closed and here we have also two "festures requests";

1 - How to **limit the upload file type** only to .pdf (.xxx/.yyy/ .zzz) files for this field ? (related with the issue). In this way the "Media" Type would be usefull fo rall the uploads and the Media selector window pop-up following this setting showing only the setted extensions files intothe folder.
 
2 - How to set the "**Maximum upload size**: ... MB" for this field ?

Seem these are two "Media" field Type option "missing" on the field creation.

Please, What I have to do with this ticket ?

**Comment by ghost** [comment]
i added the "Feature Request"-Category. Now it belongs to Devs, Maintainers.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17475">issues.joomla.org/tracker/joomla-cms/17475</a>.</sub>

**Comment by Quy** [comment]
Similar to #15015?

**Comment by ghost** [comment]
closed in Favor of #15015 as suggested above. 

This Issue can always be reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17475">issues.joomla.org/tracker/joomla-cms/17475</a>.</sub>
