### ISSUE TITLE
3.7.4 contact card issue

### ISSUE THREAD

**Issue by federal12** [joomla/joomla-cms#17476]
### Steps to reproduce the issue
3.7.3  had an issue with only displaying the telephone number. 3.7.4 update replaced the address and icons but no email address. Show/Hide for Postal ZIP code has no effect, it is displayed regardless (this was just to test hiding/showing an item.

### Expected result
Contact fields to be selectable whether to display or not

### Actual result
Fields tested so far are email (does not display at all) ZIP code displays even when set to hide, vcard does not display.

**Comment by matrikular** [comment]
@federal12 I cannot confirm the issues you described.

In both Joomla! 3.7.4 and 3.8.0-dev, the contact fields show up or stay hidden as they should (global, entity, menu).
![contact](https://user-images.githubusercontent.com/1304616/29188986-38b90136-7e15-11e7-8018-2232a5858323.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17476">issues.joomla.org/tracker/joomla-cms/17476</a>.</sub>

**Comment by federal12** [comment]
Thanks for checking. Must be a template specific issue. As it used to work prior to 3.7.3 I just assumed it was a core issue. I'll do a clean install just to check for myself and compare the 2.

**Comment by brianteeman** [comment]
no need to use a clean install. it should be enough to just switch to protostar for testing

**Comment by federal12** [comment]
Hi, sorry for any confusion. The display options in edit contact don't have any effect (except show position, which does for some reason), however if I change in the menu item it all behaves as expected. I still think this is a bug as I think the individual contact display should override the menu display options.

**Comment by matrikular** [comment]
It shouldn't. If you have an active menu item for a contact entity and you are not in a / the list view of contacts, the menu item should take priority, otherwise the settings in there become useless. The same behavior is in place for articles.

**Comment by federal12** [comment]
Agreed, however for the inexperienced like me the value of having the menu item override the individual is limited and confusing. There must be benefits for this, I'm just not seeing them personally. On the plus side any other noob with the same issue now has a reference. Thanks for your help and comments, they are appreciated.

**Comment by matrikular** [comment]
One of the most beneficial things of having a menu item might be a cleaner / direct URL to the contact. It is also the only way to make one contact stand out. Like via the assignment of modules and / or custom site attributes like menu item id, class suffixes and so on.

> **Dad (Global):** _Listen kids (contacts), if someone asks you to show them where you live, you don't tell them, okay?_
> **The black sheep (Contact):** _Pah, I will do and say what **I** want!_
> **Mom (Menu):** _Dear "Hanky", you can behave like that when you're with your friends and sisters (list view), but for now be a good boy (contact) and behave as your father told you to. No, I don't say "ask your dad" this time. I have the same opinion about this as he does._

... and vice versa, of course.

**Comment by federal12** [comment]
Brilliant! Well explained, a bit more functionality than I require but useful to know. Thanks again. I've created another issue for myself now as I can now display the vCard download but it misses all but the address line of the full address! I think I'll hide it as it'll drive me nuts and it never bothered me before I could display the link!

**Comment by ghost** [comment]
@federal12 if Issue is solved please close it.
