### ISSUE TITLE
Trying to get property of non-object  ExtensionAdapter.php on line 127

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#17489]
### Steps to reproduce the issue

Go to joomla update

### Expected result

no error

### Actual result

 Notice: Trying to get property of non-object in C:\wamp\www\new2\libraries\src\Updater\Adapter\ExtensionAdapter.php on line 127
Notice: Trying to get property of non-object in C:\wamp\www\new2\libraries\src\Updater\Adapter\ExtensionAdapter.php on line 128

### Additional comments
php: 7.1.6

**Comment by mbabker** [comment]
Duplicate of https://github.com/joomla/joomla-cms/pull/17481
