### ISSUE TITLE
[3.7.x] 'showon' does not work for unchecked checkbox

### ISSUE THREAD

**Issue by dnldrws** [joomla/joomla-cms#17486]
Hi,
i want to show an input field only if an checkbox is unchecked.

### Steps to reproduce the issue
```
<form>
    <fieldset>
        <field name="rmvFoo" type="checkbox"/>
        <field name="Foo" type="text" showon="rmvFoo:0"/>
    </fieldset>
</form>
```

### Expected result
According to the documentation `showon="checkboxname:0"` or `showon="checkboxname!:1"` should work (as far as I understand it).
But it doesn't.
In 3.6.5 I used `showon="checkboxname"` to do it, but this also won't work in 3.7.x.

### Actual result
The input field never appears.

**Comment by tonypartridge** [comment]
No, I don't believe this will work since the checkbox isn't an input value. It's a selection. 

It would fall under the same issue as select lists. Which @GeraintEdwards has done a PR for:
https://github.com/joomla/joomla-cms/pull/17212

**Comment by dnldrws** [comment]
Does the change of status to "_Information Required_" mean that the information I provided is insufficient?
If so, what else do you need? Or does it mean something else? (sorry, it's my first use of the issue tracker)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17486">issues.joomla.org/tracker/joomla-cms/17486</a>.</sub>

**Comment by ghost** [comment]
@dnldrws it means to wait on Answer of @GeraintEdwards

**Comment by dnldrws** [comment]
@franz-wohlkoenig okay. thanks!

**Comment by ghost** [comment]
@dnldrws thats how i understand the Comment of @tonypartridge.

**Comment by dnldrws** [comment]
@tonypartridge I'm not sure if you are right.
Isn't the PR of @GeraintEdwards about enabling the `showon` attribute for `<option></option>`?
And my issue is that a checkbox does not work **as the target** of `showon`.

**Comment by ghost** [comment]
@tonypartridge can you please answer above Comment?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17486">issues.joomla.org/tracker/joomla-cms/17486</a>.</sub>

**Comment by ghost** [comment]
Reminder for @tonypartridge.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17486">issues.joomla.org/tracker/joomla-cms/17486</a>.</sub>

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 26th January 2018.

**Comment by tonypartridge** [comment]
I’ve asked @GeraintEdwards to try and take a look since he is doing a rewrite for the show on code

**Comment by ghost** [comment]
thanks @tonypartridge, Issue stay open.

**Comment by brianteeman** [comment]
I am going to close this. @tonypartridge is correct. If there is no input then the showon functionality won't know what to do.
