### ISSUE TITLE
Joomla with difference between firefox and google chrome.

### ISSUE THREAD

**Issue by julioalvez0502** [joomla/joomla-cms#17498]
### Steps to Reproduce Problem
Update all components and joomla

### Expected outcome
Update without problem

### Current results
Joomla with difference between firefox and google chrome.

Errors that happen in firefox:
1 - The Components menu does not display all items.

2 - Akeeba also does not display all icons without admin panel.

The site is all up to date.

They follow as pictures.

### System Information (as much as possible)
PHP running at 3.12.74-213.ELK6.x86_64 # 1 SMP Tue Jun 20 00:36:01 CDT 2017 x86_64
Version of the Database 5.6.32-78.1
Database Collation utf8_general_ci
'Collation' of database connection utf8mb4_general_ci
PHP version 7.0.18
Apache Web Server
PHP interface with Web server cgi-fcgi
Joomla! 3.7.4 Stable [Amani] July 25, 2017 11:11 GMT
Version of the Joomla Platform Joomla Platform 13.1.0 Stable [Curiosity] 24-Apr-2013 00:00 GMT
Mozilla / 5.0 User Browser (Windows NT 10.0; Win64; x64; rv: 54.0) Gecko / 20100101 Firefox / 54.0

PHP version 7.0.18![screen shot 2017-08-11 at 18 49 11](https://issues.joomla.org/uploads/1/19bc6910175a5876cccc78708b1f2ad4.jpg)![screen shot 2017-08-11 at 18 49 14](https://issues.joomla.org/uploads/1/3971fa30448436668651e35aae42edd7.jpg)

**Comment by tonypartridge** [comment]
Hello

Did you clear the cache on both browsers? What if you view it in English?

**Comment by brianteeman** [comment]
This will be closed in a few days if there is no response

**Comment by brianteeman** [comment]
Closed as stated above
