### ISSUE TITLE
Page Cache - replace Form Token doesnt work

### ISSUE THREAD

**Issue by Flocke28** [joomla/joomla-cms#17501]
### Steps to reproduce the issue

If Cache Plugin enabled then the Cache files had packed content (gzip?) but with this the Form Token replacement doesnt work in the libraries-> Cache -> Cache.php 

The Cache Plugin switched from OnAfterRender to onAfterRespond. Is this the reason?

**Comment by ghost** [comment]
Can you give more Informations like System information?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17501">issues.joomla.org/tracker/joomla-cms/17501</a>.</sub>

**Comment by Flocke28** [comment]
Hi..mi use actually joomla 3.7.4 on a Shared Server. Php 5.6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17501">issues.joomla.org/tracker/joomla-cms/17501</a>.</sub>

**Comment by Flocke28** [comment]
Here are a Screenshot of a compressed Cache File<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17501">issues.joomla.org/tracker/joomla-cms/17501</a>.</sub>

**Comment by Flocke28** [comment]
![screen shot 2017-08-12 at 07 18 26](https://issues.joomla.org/uploads/1/12eb7edb814295eb13ef211027281917.jpeg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17501">issues.joomla.org/tracker/joomla-cms/17501</a>.</sub>

**Comment by Flocke28** [comment]
The Login doesnt work with enabled Cache and packed Cache File. Possible that an other part of Joomla can't handle this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17501">issues.joomla.org/tracker/joomla-cms/17501</a>.</sub>

**Comment by Flocke28** [comment]
If i change the trigger to onAfterRender i got page Cache Files in plain  text and the Login works well.

**Comment by Flocke28** [comment]
![screen shot 2017-08-12 at 07 34 17](https://issues.joomla.org/uploads/1/dc915654e2c735fb28eaab52c9887a21.jpeg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17501">issues.joomla.org/tracker/joomla-cms/17501</a>.</sub>

**Comment by alikon** [comment]
lack of interest<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17501">issues.joomla.org/tracker/joomla-cms/17501</a>.</sub>

**Comment by mbabker** [comment]
Still a bug...

**Comment by alikon** [comment]
reopened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17501">issues.joomla.org/tracker/joomla-cms/17501</a>.</sub>

**Comment by SharkyKZ** [comment]
Test PR #25823 please.
