### ISSUE TITLE
[4.0] Frame around "Close"-Button in Message

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#17502]
### Steps to reproduce the issue
In Warning, Information, got:
![bildschirmfoto 2017-08-12 um 09 18 29](https://user-images.githubusercontent.com/8235763/29238913-9fd928fc-7f3f-11e7-82df-f30948561b50.jpg)
should be without Frame around "X" like:
![bildschirmfoto 2017-08-12 um 09 18 40](https://user-images.githubusercontent.com/8235763/29238926-fc60edf8-7f3f-11e7-95e3-29e5f4d971aa.jpg)

### System information
4.0.0-dev
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
So you got the dotted border around the X even without any interaction with the alert?

**Comment by ghost** [comment]
@C-Lodder correct: dotted Border is shown when Message is shown. Click on another Place at Screen Border is gone (like Picture 2 shows).

**Comment by dgrammatiko** [comment]
@franz-wohlkoenig that's by design! The alert gets focus automatically to satisfy accessibility rules.
Nothing that needs to be fixed here, we already fixed what needed to be fixed!

**Comment by ghost** [comment]
Thanks for Info, @dgt41
