### ISSUE TITLE
ERROR: Invalid login

### ISSUE THREAD

**Issue by MrOrkan** [joomla/joomla-cms#17514]
### Steps to reproduce the issue

https://docs.joomla.org/Joomla_2.5_to_3.x_Step_by_Step_Migration/en

After all this steps trying to update Joomla to 3.x.x. Clicking "Install the update" and see the ERROR: Invalid login 

and

Warning: file_put_contents(/var/www/domain111/public/administrator/components/com_joomlaupdate/restoration.php): failed to open stream: Permission denied in /var/www/domain111/public/libraries/joomla/filesystem/file.php on line 426

### Expected result

Updated Joomla

### Actual result

Warning: file_put_contents(/var/www/domain111/public/administrator/components/com_joomlaupdate/restoration.php): failed to open stream: Permission denied in /var/www/domain111/public/libraries/joomla/filesystem/file.php on line 426

### System information (as much as possible)

Warning: file_put_contents(/var/www/domain111/public/administrator/components/com_joomlaupdate/restoration.php): failed to open stream: Permission denied in /var/www/domain111/public/libraries/joomla/filesystem/file.php on line 426

### Additional comments

Trying to update Joomla from 2.5.28 to 3.x.x

**Comment by MrOrkan** [comment]
Solved. All packages must be 775 permission.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17514">issues.joomla.org/tracker/joomla-cms/17514</a>.</sub>

**Comment by zero-24** [comment]
Thanks for the update. I'm going to close this issue than 😄
