### ISSUE TITLE
"404 - Category not found" after update to 3.7

### ISSUE THREAD

**Issue by chetanmadaan** [joomla/joomla-cms#17513]
### Steps to reproduce the issue
Upgrade Joomla 3.4 to Joomla 3.7

### Expected result
Accessible Joomla backend user manager, global config, Category Manage (New), Plugin Manager.

### Actual result
404 - Category not found
![image](https://user-images.githubusercontent.com/3968575/29243060-6992d64c-7f64-11e7-940a-e993cf38c336.png)
```

> 
> Call stack
> #	Function	Location
> 1	()	JROOT/libraries/legacy/error/error.php:200
> 2	JError::raise()	JROOT/libraries/legacy/error/error.php:277
> 3	JError::raiseError()	JROOT/libraries/legacy/view/category.php:127
> 4	JViewCategory->commonCategoryDisplay()	JROOT/components/com_content/views/category/view.html.php:72
> 5	ContentViewCategory->display()	JROOT/libraries/legacy/controller/legacy.php:671
> 6	JControllerLegacy->display()	JROOT/components/com_content/controller.php:113
> 7	ContentController->display()	JROOT/libraries/legacy/controller/legacy.php:709
> 8	JControllerLegacy->execute()	JROOT/components/com_content/content.php:39
> 9	require_once()	JROOT/libraries/cms/component/helper.php:389
> 10	JComponentHelper::executeComponent()	JROOT/libraries/cms/component/helper.php:364
> 11	JComponentHelper::renderComponent()	JROOT/libraries/cms/application/site.php:191
> 12	JApplicationSite->dispatch()	JROOT/libraries/cms/application/site.php:230
> 13	JApplicationSite->doExecute()	JROOT/libraries/cms/application/cms.php:265
> 14	JApplicationCms->execute()	JROOT/index.php:49
> 

```
### System information (as much as possible)

Setting | Value
PHP Built On | Linux host.joomlasites  3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64
Database Version | 5.6.35
Database Collation | latin1_swedish_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 5.6.31
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.7.4 Stable [ Amani ] 25-July-2017 11:11 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

### Additional comments
The problem is that "**404 -  Category not found**" issue can be seen when trying to access the following areas on the Joomla backend.
User Manager
Category Manager (New Category)
Global Configuration
Plugin Manager --> System --> Debug plugin only (Other plugins within the system plugin and other groups are accessible).

I have a feeling this is related to: https://github.com/joomla/joomla-cms/issues/15545

1. Also, I am **not** using the Attachments plugin as mentioned in the issue #15545
2. I have cleared and removed all trashed & unpublished categories and verified via PhpMyAdmin that all categories exist are published.
3. I already ran the following SQL's and these returned **0 rows** each https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/sql/updates/mysql/3.7.0-2017-03-09.sql .

**Comment by ghost** [comment]
@chetanmadaan is this Issue still valid?

**Comment by brianteeman** [comment]
Closed if you still have a problem please use the forum for support.
