### ISSUE TITLE
[3.8 Beta] Fatal error: Undefined class constant 'MAJOR_VERSION'

### ISSUE THREAD

**Issue by Gitjk** [joomla/joomla-cms#17512]
### Steps to reproduce the issue
Open Url: .../administrator/index.php?option=com_languages&view=installed

### Expected result
The view should display installed languages.

### Actual result
 	
Fatal error: Undefined class constant 'MAJOR_VERSION' in ...\administrator\components\com_languages\views\installed\tmpl\default.php on line 103

**Comment by ghost** [comment]
Can't confirm.
### System information
3.8-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by mbabker** [comment]
Please make sure the upgrade completed successfully.  If you still have a file post-upgrade at `libraries/cms/version/version.php` then that would cause this error to occur.  Still having that file means the files that the filesystem was not properly updated to 3.8.

**Comment by ghost** [comment]
closed as no Core Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17512">issues.joomla.org/tracker/joomla-cms/17512</a>.</sub>

**Comment by Gitjk** [comment]
Sorry, I accidentally had opened the wrong test installation. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17512">issues.joomla.org/tracker/joomla-cms/17512</a>.</sub>
