### ISSUE TITLE
Calendar does not trigger jQuery events

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#17515]
### Steps to reproduce the issue
1. Open an article
2. Apply an onChange jQuery event to the publish down field
You could use the console and insert:
```jQuery('#jform_publish_down').on('change', function() { alert('test'); });```
3. Change the date of the publish down event

### Expected result
The event will be triggered (=> alert test)

### Actual result
No trigger

### Additional comments
I'm not sure, why there is a vanilla JS calendar without any jQuery hooks in a system which relays on jQuery...
To check the event use:
```jQuery('#jform_publish_down').trigger('change');```

[Delegation](https://api.jquery.com/on/#direct-and-delegated-events) should probably work, too

**Comment by dgrammatiko** [comment]
@bembelimen why not:
```js
document.getElementById('jform_publish_down').addEventListener('change', function() { alert('test'); });
```
??

This works in IE8 and all other browsers, so honestly I don't see a reason to mix jQuery when native javascript fulfils all our needs. 

Any particular reason why we need to care for jQuery's **own** events?

**Comment by bembelimen** [comment]
Hi @dgt41 ,
Thank you for your answer!

Could you also say something about event delegation?

(The reason for jQuery events is, that with vanilla JS, I have to implement a mapping for the events...)

**Comment by dgrammatiko** [comment]
@bembelimen actually looking at the code I didn't see any code for triggering the change event, or I was too hurry. I guess if the event is triggered (vanilla or jQuery) will eventually bubble up to jQuery. Give me few days and I will come back with some more solid answers here

**Comment by bembelimen** [comment]
https://github.com/joomla/joomla-cms/blob/staging/media/system/js/fields/calendar.js#L237

**Comment by bembelimen** [comment]
@dgt41 any updates here?

**Comment by C-Lodder** [comment]
@bembelimen 

You can add the `onchange` event listener to the calendar form field, like so:
```
<field
    type="calendar"
    onchange="Joomla.inputHasChanged();"
/>
```

Then in your JS:

```
var Joomla = Joomla || {};
   
(function(Joomla) {
    Joomla.inputHasChanged = function() {
        alert('changed!');
        // You can do some more jazzy stuff here.
    }

    document.addEventListener('DOMContentLoaded', function() {
        Joomla.inputHasChanged();
    });
})(Joomla);
```

**Comment by bembelimen** [comment]
Yeah, but I don't understand why there is no default implementation....

**Comment by C-Lodder** [comment]
@bembelimen The calendar was a huge change, must have been missed out.

**Comment by dgrammatiko** [comment]
@bembelimen @C-Lodder well it didn't exist in the old calendar and nobody ask for it during the testing period, but it's fairly simple to add a listener for an event, or dispatch an Event from the calendar.

**Comment by bembelimen** [comment]
@dgt41 do you have any plans to implement it? That would be great!

**Comment by coolcat-creations** [comment]
Is still still open? Any hint how to fix it?

**Comment by dgrammatiko** [comment]
@coolcat-creations supporting jQuery events in 2020 is not very bright idea. It wasn't back in 2017...

**Comment by C-Lodder** [comment]
Events are events. Doesn't matter if they're called in jQuery or vanilla JS.
I'll start looking into this now.

**Comment by C-Lodder** [comment]
The problem being is that the value is being set via Javascript, so the normal event listener don't apply. You can add a custom event:

https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/system/js/fields/calendar.es5.js#L236

Add the following to Joomla's core calendar:

```
const event = new Event('change');
this.inputField.dispatchEvent(event);
```

Then in your own code:

```
element.addEventListener('change', () => {
    console.log('has changed')
}, false)

jQuery('#element').on('change', () => {
    console.log('Look Mum....I can use jQuery too!')
})
```

**Comment by dunkmark** [comment]
Also there is a developers mode that allows coding for app developers to create components and upload them onto the marketplace for other users to use/purchase. Only one source is needed to create apps for Windows, Android, iOS, and HTML5. All that we ask is for some feedback on how we can better our software and better serve our users.

https://issues.joomla.org/uploads/1/8e309060319af1fc090e008125f0e087.pdf
https://issues.joomla.org/uploads/1/faa87f0c64351010361e2316ae839d22.pdf
https://issues.joomla.org/uploads/1/509cb8b91ff5f1f39c4d12ae3db809be.pdf
https://issues.joomla.org/uploads/1/782c59a372c0257224e575a07c2ac553.pdf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17515">issues.joomla.org/tracker/joomla-cms/17515</a>.</sub>

**Comment by ReLater** [comment]
Comment https://github.com/joomla/joomla-cms/issues/17515#issuecomment-662371104
by @dunkmark 
is SPAM. Please delete.

**Comment by JamesBrown7575** [comment]
Yes. Not Working

https://issues.joomla.org/uploads/1/2ca78667c067b26a61dcd5d06e9748c9.pdf
https://issues.joomla.org/uploads/1/b32e72b7049a67afa95052676a6dc3d3.pdf
https://issues.joomla.org/uploads/1/c17addd070040b2060020d66a97b2c31.pdf
https://issues.joomla.org/uploads/1/174d3a267441d0859aac83c4b4c588af.pdf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17515">issues.joomla.org/tracker/joomla-cms/17515</a>.</sub>

**Comment by Fedik** [comment]
please test #32756

**Comment by alikon** [comment]
closing as we have a pr #32756
