### ISSUE TITLE
Debug Language string path

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17510]
I noticed today when looking at the output with debug language the following output
```

**Loaded** : JROOT/language/en-GB/en-GB.mod_search.ini
**Loaded** : JROOT/language/en-GB/en-GB.mod_finder.ini
**Loaded** : JROOT/language/en-GB/en-GB.com_finder.ini
**Loaded** : JROOT\administrator/language/en-GB/en-GB.plg_content_finder.ini
**Loaded** : JROOT\administrator/language/en-GB/en-GB.plg_finder_categories.ini
**Loaded** : JROOT\administrator/language/en-GB/en-GB.plg_finder_contacts.ini
```

Note that the site files are in JROOT forward slash but the admin files are in JROOT backslash

This is on a windows system - it is fine on a linux system

**Comment by tonypartridge** [comment]
@brianteeman I've not got a windows dev server to test on. But can you try editing:

/libraries/cms/html/debug.php

replace:
`		$link = str_replace(JPATH_ROOT, 'JROOT', $file);
`
with: 
`		$link = str_replace(array(JPATH_ROOT, '\\'), array('JROOT', '/'), $file);
`

**Comment by mbabker** [comment]
Or you can use `JPath::clean()` to ensure the file system path is correctly formatted for the operating system.

**Comment by brianteeman** [comment]
Closed as there is a PR
