### ISSUE TITLE
[3.8] Turning on Cache results in a white screen of death on the frontend

### ISSUE THREAD

**Issue by bayareajenn** [joomla/joomla-cms#17517]
Steps to reproduce the issue:
1. Install Joomla 3.8 Beta on somewhere (occurs on Rochen, Siteground, and Mamp and Xamp (linux))
2. Install Sample Data
3. Turn error reporting to maximum
4. Go to Global Config and turn on Caching. Different servers will give different options for caching.
5. Save
6. Refresh the frontend
All the cache options on the backend result in a white screen on the frontend but on local devices they got a white screen on the backend too. They had to go to configuration.php to get to the backend again.

Turning off caching resolves the issue.

One result on Rochen with Cache Handler: File and System Cache: Conservative returned the error Fatal error: Class 'Joomla\CMS\Document\Renderer\Html\stdClass' not found in /libraries/src/Document/Renderer/Html/ModuleRenderer.php on line 89

**Comment by crleathers** [comment]
I can reproduce this issue on a fresh install of 3.8beta with any of the following cache type options:
File
Cache_Lite
Memcache

System Cache plugin is not enabled.

Fatal error: Class 'Joomla\CMS\Document\Renderer\Html\stdClass' not found in /libraries/src/Document/Renderer/Html/ModuleRenderer.php on line 89<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17517">issues.joomla.org/tracker/joomla-cms/17517</a>.</sub>

**Comment by mbabker** [comment]
Reported and fixed through https://github.com/joomla/joomla-cms/issues/17448 already.

**Comment by bayareajenn** [comment]
We installed the latest 3.8 beta TODAY and are testing stuff.

Do you suggest some other way for us to test the fix? We'd like to. Our PBF event is almost complete.

**Comment by mbabker** [comment]
Use the nightly build from https://developer.joomla.org/nightly-builds.html

That was patched after the beta release went out.

**Comment by bayareajenn** [comment]
Ok, that is a good point that we weren't aware of - going off the nightly builds for testing instead of whatever is the beta. Kinda. Not sure what I'm saying but even the bug squad didn't mention it.

We'll try it out on the nightly build. Thanks, Michael for sending on the link.
