### ISSUE TITLE
[3.8 Beta 1] JInputCLI Class not found in CLI scripts

### ISSUE THREAD

**Issue by cheiff** [joomla/joomla-cms#17522]
Hi, 
something in the moving of libraries (#17441) breaks the JInputCLI alias for CLI scripts.

### Steps to reproduce the issue
Run a CLI script, it should find JInputCLI by invoking
```php
$var = new JInputCLI();
```

### Expected result
It finds JInputCLI.

### Actual result
It does not find JInputCLI.
Application breaks.
 
----
I attach a [test cli script](https://gist.github.com/cheiff/d788600c0132dcf89e8583059f8cae3e) (based on this [script by Nicholas](https://github.com/akeeba/vagrant/blob/master/vagrant/files/joomla/install-joomla-extension.php)) that finds JInputCLI on a 3.7.4 and below but does not in 3.8.0 beta 1. 

To run the the test, put the file in the cli folder of a joomla and run
```
php cli/jinputcli-test.php
```

I have found a workaround using this
```php
      if (class_exists('JInputCLI'))
        {
          echo "JInputCLI exists\n";
          $this->input = new JInputCLI();
        }
        else
        {
          echo "JInputCLI does NOT exist\n";
          $this->input = new \Joomla\CMS\Input\Cli();
        }
```
Is this expected behaviour? Or do we have to include other class loader, on top of `JLoader::import('joomla.application.cli')` ?
If it is not expected, maybe other aliases are affected.

**Comment by mbabker** [comment]
Since 3.2.0 the correct casing of the class name has been `JInputCli` and that's what it must be called as for the class aliasing system to correctly pick it up.

**Comment by ghost** [comment]
@cheiff if Information solves Issue please close it, thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17522">issues.joomla.org/tracker/joomla-cms/17522</a>.</sub>

**Comment by cheiff** [comment]
OK. Thank you.
