### ISSUE TITLE
Schema.org: ARTICLE da rimuovere

### ISSUE THREAD

**Issue by PrincipioAttivo** [joomla/joomla-cms#17527]
### Steps to reproduce the issue

Joomla include la direttiva ARTICLE di schema.org
Questo crea vari problemi a livello SEO.
Trovo assurdo dover creare un override per rimuovere quella direttiva perchè le pagine statiche NON SONO ARTICOLI oppure, le sezioni blog, spesso sono menu di ristoranti oppure, sezioni descrittive di aziende e in tal caso, si aggiunge una sola direttiva localbusiness, non una per ogni pagina, inclusa in ARTICLE (l'azienda è una!).

Vi scongiuro: rimuovete quella direttiva se vogliamo Joomla compatibile a schema.org

**Comment by wojsmol** [comment]
@PrincipioAttivo Please describe issue in English.

**Comment by ghost** [comment]
@PrincipioAttivo if you can't please use [Google Translate](https://translate.google.com/)

**Comment by PrincipioAttivo** [comment]
Sorry  :)

Joomla includes the ARTICLE directive of schema.org
This causes SEO problems.

Articles are used for static or internal pages that are not articles but descriptive sections.
In addition, the blog section is often not used for articles but for restaurant events or menus and the respective directives can not be included within the ARTICLE DIV.

Please remove this useless and damaging directive.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17527">issues.joomla.org/tracker/joomla-cms/17527</a>.</sub>

**Comment by PrincipioAttivo** [comment]
what do you think?
Is very important!

**Comment by LivioCavallo** [comment]
I think that the blog view is intended for blogs: in J!3.7.5 it uses itemtype="https://schema.org/Blog" and itemtype="https://schema.org/BlogPosting", not Article.
If you use the the blog section for restaurant events or menus you should have an override.
Analogously if you use article vew for something that is not an article you should make an override.

Or am I missing something?
Or are you suggesting to add options in com_content views to parametrize with custom microdata?

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 26th November 2017.

**Comment by ghost** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened.
