### ISSUE TITLE
[General] Text Files Needing Updates

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#17534]
Some files in the repo need updates (issue is here more as a reminder than anything)

- `.github/CONTRIBUTING.md` - Branch data
- `libraries/src/Crypt/README.md` - Should reflect the added Sodium cipher

May be others, but those two pop off the top of my head (OK, one's a nudge from George, but still).

**Comment by zero-24** [comment]
PR is https://github.com/joomla/joomla-cms/pull/17535
