### ISSUE TITLE
Warnings when cache enabled

### ISSUE THREAD

**Issue by solracsf** [joomla/joomla-cms#17540]
When cache (redis) is activated i have these warnings at the frontend and the backend, then it disappear after a few minutes of browsing without change any setting

```
Warning: strstr() expects parameter 1 to be string, object given in
/public/libraries/joomla/cache/controller/callback.php on line 63

Warning: strstr() expects parameter 1 to be string, object given in
/public/libraries/joomla/cache/controller/callback.php on line 69

Warning: call_user_func_array() expects parameter 1 to be a valid callback,
class 'JCache' does not have a method 'contains' in
/public/libraries/joomla/cache/controller.php on line 69
```
Joomla Error Reporting is **None**.

- Joomla 3.7.5
- PHP 7.0.22
- Redis 4.0.1

**Comment by zero-24** [comment]
@mbabker can you take a look here as you was able in the past to set up a redis server. By reading the code it looks like `$callback` is a object but not callable so maybe we need to do a extra is_object check? But i also don't understand where this is not callable object comming from.

**Comment by mbabker** [comment]
> Warning: call_user_func_array() expects parameter 1 to be a valid callback,
> class 'JCache' does not have a method 'contains' in
> /public/libraries/joomla/cache/controller.php on line 69

That part is the key here.  Since 3.7.0 the cache API has had said contains method.  So it seems like when this was reported there was a bad upgrade, or even worse potentially something overloading the cache API.
