### ISSUE TITLE
4.0 Postinstall Check Update

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#17547]
Per yesterday's announcement, 4.0 will now require PHP 7.  The postinstall message check needs to be updated in 3.x for this.

**Comment by zero-24** [comment]
do you want to do that in 3.8 or do you want to wait to 3.9 for this?

**Comment by mbabker** [comment]
Should be 3.8 since the postinstall is already there.

**Comment by zero-24** [comment]
i guess the over versions for mysqli / postrgres etc don't change?

**Comment by mbabker** [comment]
Nope, just PHP.

**Comment by zero-24** [comment]
see #17549
