### ISSUE TITLE
Fatal error: Class 'XMLReader'

### ISSUE THREAD

**Issue by radik10** [joomla/joomla-cms#17556]
### Steps to reproduce the issue
after login, go to "Read messages" (post installation messages) or .../administrator/index.php?option=com_postinstall&eid=700 - this error is with clean install of joomla or after ugrade to latest version (3.7.4)

there is error:
**Fatal error: Class 'XMLReader' not found in .../libraries/joomla/feed/factory.php on line 39**

### Expected result

correctly displayed adminsitration area with messages - displayed as all other parts of jooml administration, 

### Actual result

there is only black text on white background with error messasge

### System information (as much as possible)

PHP Built On: FreeBSD web253s93.dnsserver.eu 10.2-RELEASE-p7 FreeBSD 10.2-RELEASE-p7 #0: Mon Nov 2 14:19:39 UTC 2015 root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC amd64
Database Version: 5.5.40-36.1
Database Collation: utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version: 5.6.20
Web Server: Apache
WebServer to PHP Interface: cgi-fcgi
Joomla! Version: Joomla! 3.7.4 Stable [ Amani ] 25-July-2017 11:11 GMT
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent: Mozilla/5.0 (Windows NT 5.1; rv:51.0) Gecko/20100101 Firefox/51.0 

### Additional comments
same error is also with some other componets, e.g. "FAQueue" - black text on white background instead of correctly displayed dashboard of component in joomla administration...
pls. see attached image![screen shot 2017-08-16 at 04 22 23](https://issues.joomla.org/uploads/1/b3ab73aa57433727e7f1c8986387f31e.png)

**Comment by SharkyKZ** [comment]
XMLReader is disabled on your PHP installation. It is enabled by default on all Joomla-supported versions of PHP so it's not really a Joomla issue.

**Comment by radik10** [comment]
Yes, it was disabled in "php.ini" file. Works now, thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17556">issues.joomla.org/tracker/joomla-cms/17556</a>.</sub>
