### ISSUE TITLE
html code module mod_logged (admin)

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#17559]
### Steps to reproduce the issue

* Log in at the backend.
* Go to the Control Panel -> Logged-in Users
* Log in at the frontend.
* Look at the source code in the backend.

### Expected result

See source code: 
```
....<span class="element-invisible">Log out</span></span>
```

### Actual result

See source code: 
```
....<span class="element-invisible">Log out"></span></span>
```
Look specially at

```
>Log out"></span>
```
(see **">**)

### System information (as much as possible)
File:
```
..\Joomla\administrator\modules\mod_logged\tmpl\default.php
```
Line 20:
```
<span class="icon-remove icon-white" aria-hidden="true"><span class="element-invisible"><?php echo JText::_('JLOGOUT'); ?>"></span></span>
``` 
Should (possible) be:
```
<span class="icon-remove icon-white" aria-hidden="true"><span class="element-invisible"><?php echo JText::_('JLOGOUT'); ?></span></span> 

```
Delete: **">**

### Additional comments
Joomla 3.7.4 - mod_logged (admin)

**Comment by brianteeman** [comment]
Thanks for reporting this - i have made a PR for testing #17561
