### ISSUE TITLE
MEDIA MANAGER  uploading Field for new Images

### ISSUE THREAD

**Issue by widmann-it** [joomla/joomla-cms#17551]
In Tinymce the field for uploading the pictures is unfortunately hidden because of the size of the window. It would be nice a different arrangement of the elements.

![grafik](https://user-images.githubusercontent.com/13391650/29327575-ee1e47ba-81ef-11e7-8ee1-b27ac4bd6218.png)

**Comment by brianteeman** [comment]
This is not tinymce it is part of the media manager

**Comment by ghost** [comment]
Closed as no Bug fix and already fixed with the new media manager.
