### ISSUE TITLE
[4.0] Travis error | JS file "calendar.min.js" should be loaded

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#17550]
### Steps to reproduce the issue

https://travis-ci.org/joomla/joomla-cms/jobs/264767102

### Expected result

no errors

### Actual result

```
1) JHtmlTest::testCalendar
Line:1509 JS file "calendar.min.js" should be loaded
Failed asserting that an array has the key '/media/system/js/fields/calendar.min.js'.
/home/travis/build/joomla/joomla-cms/tests/unit/suites/libraries/cms/html/JHtmlTest.php:1509
```

So should the "calendar.min.js" loaded or not?

### Additional comments

Extracted from: https://github.com/joomla/joomla-cms/pull/17548#issuecomment-322486447+

**Comment by wilsonge** [comment]
Probably but hold off. This was part 1 of fixing conflicts by merging the 3.7.4 tag. Part 2 of merging the rest of staging is coming (I'm about 75-80% done). Once that is done i'll regenerate all the media files and see what's broken with unit tests etc and fix them again :)

**Comment by wilsonge** [comment]
Update: I have fixed this as part of my WIP branch at https://github.com/wilsonge/joomla-cms/tree/4.0-dev (note I'm not pushing this into Joomla 4.0 just yet because there were massive conflicts in the admin menu module and so admin menu module is totally broken at the moment in there)

**Comment by wilsonge** [comment]
Fixed
