### ISSUE TITLE
[4.0] Switcher improvements

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#17558]
The switcher needs the following improvements:

- [ ] Accessibility
- [x] Event listeners that can be called
- [x] Move to custom elements

**Comment by brianteeman** [comment]
https://inclusive-components.design/toggle-button/

**Comment by dgrammatiko** [comment]
@C-Lodder let's move it to custom elements, then we can implement all the cases on @brianteeman 's link (e.g. `<joomla-switch>`)

**Comment by C-Lodder** [comment]
Sounds like a plan
