### ISSUE TITLE
?Itemid=101 by Contact Link in a Article

### ISSUE THREAD

**Issue by gogicomputers** [joomla/joomla-cms#17568]
### Steps to reproduce the issue
- Create a new Article
- Add a link to a single Contact
- Save it
- Call the new Article in the frontend

### Expected result
component/contact/contact/46-tsv/2.html
### Actual result
component/contact/contact/46-tsv/2.html?Itemid=101

### System information (as much as possible)
Joomla 3.7.4
PHP 7.1.8

### Additional comments
The itemid is the id of the homepage

**Comment by brianteeman** [comment]
That's is the expected behaviour if you do not have a menu link to the contact component

**Comment by ghost** [comment]
closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17568">issues.joomla.org/tracker/joomla-cms/17568</a>.</sub>

**Comment by gogicomputers** [comment]
Is it not possible to change it that it works without a menu entry?

**Comment by brianteeman** [comment]
No - the menu item is the glue that binds joomla together so if there is no menu item it will default to the home page item. 

You can always create a menu item for the contact and in the link options set it to NOT be displayed in the menu (aka hidden)
