### ISSUE TITLE
[4.0] com_redirect Fatal error

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17576]
### Steps to reproduce the issue
Enable the redirect plugin and then try to open com_redirect

### Expected result
component opens

### Actual result

**Notice: Undefined variable: previousExceptionHandler in** `C:\Apache24\htdocs\cms4\plugins\system\redirect\redirect.php on line 112`

**Fatal error: Uncaught Error: Function name must be a string in** `C:\Apache24\htdocs\cms4\plugins\system\redirect\redirect.php:112 Stack trace: #0 C:\Apache24\htdocs\cms4\plugins\system\redirect\redirect.php(91): PlgSystemRedirect::doErrorHandling(Object(Error)) #1 [internal function]: PlgSystemRedirect::handleException(Object(Error)) #2 {main} thrown in C:\Apache24\htdocs\cms4\plugins\system\redirect\redirect.php on line 112
`

### Additional comments
With the plugin disabled the component loads ok

**Comment by ghost** [comment]
Issue confirmed. Got after enabling Plugin: `Class 'Joomla\Component\Redirect\Administrator\View\Links\JText' not found`

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/17587

**Comment by ghost** [comment]
closed as having Pull Request #17587<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17576">issues.joomla.org/tracker/joomla-cms/17576</a>.</sub>
