### ISSUE TITLE
[com_fields] Editor in Subform

### ISSUE THREAD

**Issue by pixxelfactory** [joomla/joomla-cms#17578]
### Steps to reproduce the issue
Create a module / plugin for custom fields that contain a subform-field:
```
<fieldset name="basic">
	<field
		type="subform"
		name="applications_forest"
		formsource="modules/mod_applications/forms/application.xml"
		multiple="true"
		min="1"
		max="99"
		label="Application" />
```
..

Inside the subform-xml, add an editor-field:
```
<fieldset name="application" label="Application">
            <field
                name="application_title"
                type="editor"
                label="Title"
                filter="safehtml" />
```
..

Install and add a new row to the subform field.

### Expected result

By adding new rows to the subform-field, there should show a editor in each row.

### Actual result

Editor does not show up, javascript-warning about an empty string being passed to getElementById().
Editor shows only after saving the module/article

### System information (as much as possible)

Client: Firefox (54) / OSX 10.10
Server: Php 5.6 
Joomla: tried with Joomla 3.6.4 and Joomla 3.7.4
Editor: Tried with JCE (latest) and TinyMCE

### Additional comments
-

**Comment by ghost** [comment]
@laoneo this Issue was in the wrong Category.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17578">issues.joomla.org/tracker/joomla-cms/17578</a>.</sub>

**Comment by laoneo** [comment]
Guess this is an issue of editors inside of subforms in general. Perhaps @dgt41 can help here?

**Comment by Quy** [comment]
@pixxelfactory Can you reproduce this with v3.8.7?

**Comment by Quy** [comment]
Closing as not reproducible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17578">issues.joomla.org/tracker/joomla-cms/17578</a>.</sub>
