### ISSUE TITLE
Show or Hide Contact Form is ignored

### ISSUE THREAD

**Issue by twister65** [joomla/joomla-cms#17570]
### Steps to reproduce the issue
In the administration menu, select :
- Components -> Contacts -> Contacts
- Some user...
- Form
- Show or Hide in the Contact Form dropbox.

### Expected result
Show or hide the contact form.

### Actual result
This action is ignored, it has no effect, it only supports the contact form option in the global configuration.

### System information (as much as possible)
Joomla!3.7.4

**Comment by ghost** [comment]
Can't confirm. Form isn't shown if set in Contact to "Hide". 

Have you tried using a clean Install using Protostar without any 3rd-Party-Plugins -Components?

**Comment by tonypartridge** [comment]
Also check the menu item params

**Comment by twister65** [comment]
It is working in the menu item param : Menu -> Main menu -> Contact -> Mail options -> Contact form -> Hide or show.
But it is not working in the contact item param : Components -> Contacts -> Contacts -> "someuser" -> Form -> Contact form -> Hide or show.

I've just testing with joomla-cms-staging and joomla-3.7.4.

**Comment by ghost** [comment]
Have you tried using a clean Install using Protostar without any 3rd-Party-Plugins -Components?
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding.

**Comment by twister65** [comment]
Yes, it's a clean install using Protostar without any 3rd-Party-Plugins -Components.

**Comment by ghost** [comment]
Tried again, can't confirm Issue. 

Used Sample Sites, appended to Contact "Owner" a linked user > show/hide works as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17570">issues.joomla.org/tracker/joomla-cms/17570</a>.</sub>

**Comment by twister65** [comment]
Just do : 
1- Components -> Contacts -> Contacts -> New
Select a user
Fill the fields of the form
Save & Close

2- Menu -> Main menu -> New
Select Menu Item Type -> Contacts -> Single Contact
Select the contact you've just created.
Save & Close

3- Components -> Contacts -> Contacts
Click on the contact you've just created.
Click on Form
Select Hide in the "Contact Form" combobox.

4- Go to the front office (site preview)
Click on the contact item on your main menu
=> The contact form is still there !

**Comment by ghost** [comment]
Done all 4 Steps. Form isn't shown., If Contact has a linked User Form is shown/hidden depending on Settings of Contact / Menu / Contact: Options.

**Comment by twister65** [comment]
Only settings of the Contact menu item are supported, but not the settings of the Contact contact item 👎

**Comment by coolcat-creations** [comment]
I confirm the issue

**Comment by matrikular** [comment]
@twister65 please start reading here: https://github.com/joomla/joomla-cms/issues/17476#issuecomment-321750227<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17570">issues.joomla.org/tracker/joomla-cms/17570</a>.</sub>

**Comment by twister65** [comment]
@matrikular as you said in the issue #17476 , we have the same behavior with the articles.
I think this is not a good behavior.
If you like it, you can close this issue.

**Comment by matrikular** [comment]
I'm not sure what you mean with "this is not a good behavior". Would you care to elaborate?

I would recommend to see it as a usefull feature rather than in terms of "good vs bad". As mentioned before, if it wasn't for that behavior, we could just drop all options from the specific menu items, because they would be useless. The example I've given shows a good and valid usecase, I believe. Where do you see a flaw in that?

The issue can (should) only be closed by you.

**Comment by twister65** [comment]
Okay, close this issue.
It can be discussed on the forum.
Regards.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17570">issues.joomla.org/tracker/joomla-cms/17570</a>.</sub>
