### ISSUE TITLE
Unable to override alert message language string - apparently missing.

### ISSUE THREAD

**Issue by JonJamesDesign** [joomla/joomla-cms#17574]
### Steps to reproduce the issue

- In admin area, go to Extensions > Languages > Overrides
- Click, "New"
- Search for, "Empty solution not allowed." by "Value"

### Expected result
Language string should be returned and editable.

_N.B:  The language string value appears in the alert message, when attempting to send an email without completing the enabled Captcha._

### Actual result
Search result returns, "No matching texts found."

### System information (as much as possible)
**Joomla! Version**
3.7.4 Stable [Amani] 25-July-2017 11:11 GMT

**Joomla! Platform Version**
13.1.0 Stable [Curiosity] 24-Apr-2013 00:00 GMT

**Environtment**
Local Host (WAMP)

**PHP Version**
5.6.25

**Web Server**
Apache/2.4.23 (Win64)

**Web Server to PHP Interface**
apache2handler

**User Agent**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Comment by brianteeman** [comment]
Did you select admin or site in the filter BEFORE clicking new?

**Comment by ggppdk** [comment]
You need to select both client "administrator" and language "english" 
that is before clicking "new"

if you do not select correct language (in this case english)
and correct client (in this case administrator because the language string belongs to the language file of a plugin)

then you will not find it

**Comment by ggppdk** [comment]
Also i tested and the string is found

**Comment by JonJamesDesign** [comment]
Ok Admin filter it is.  Didn't think that would be the case as I saw the string on the front-end. Apologies.

**Comment by ghost** [comment]
closed as Issue solved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17574">issues.joomla.org/tracker/joomla-cms/17574</a>.</sub>
