### ISSUE TITLE
Not possible to set joomla to mode "site offline"

### ISSUE THREAD

**Issue by radik10** [joomla/joomla-cms#17577]
### Steps to reproduce the issue
 Global Configuration -> site offline = yes
(clean joomla 3.7.4 + default protostar template, in "configuration.php" is public $offline = '1';)

### Expected result
site offline (only few basic informations + login form)

### Actual result

site as normal is (no "site offline") = live page with all content

### System information (as much as possible)
Database Version: 5.5.40-36.1
Database Collation: utf8_general_ci
Database Connection Collation: utf8mb4_general_ci
PHP Version: 5.6.20
Web Server: Apache
WebServer to PHP Interface: cgi-fcgi
Joomla! Version: Joomla! 3.7.4 Stable [ Amani ] 25-July-2017 11:11 GMT 

### Additional comments
is it server (php.ini) problem? Is it joomla bug?

**Comment by ghost** [comment]
Can't confirm Issue, works as expected. 
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17577">issues.joomla.org/tracker/joomla-cms/17577</a>.</sub>

**Comment by wojsmol** [comment]
@radik10 Are you logged in when the problem occurs?

**Comment by radik10** [comment]
what extensions in php.ini are requared for joomla 3+ ? Serever Check during installation of joomla did not show any errors.... This (not working site offline)is not workink even on servers with php 7.0.5. There is no article (joomla.org) what joomla need for set website to offline (techniacl details as php setting or so). Also is missing list what to check in php.ini for correct working joomla site. Where to find those informations? Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17577">issues.joomla.org/tracker/joomla-cms/17577</a>.</sub>

**Comment by wojsmol** [comment]
@radik10 Core offline mode does not require any special settings in php.ini. Please answer my question above.

**Comment by radik10** [comment]
Yes, I am logged in (administrator part) as superuser<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17577">issues.joomla.org/tracker/joomla-cms/17577</a>.</sub>

**Comment by wojsmol** [comment]
How do you set System> Global Configuration> System tab> Session Settings> Shared Sessions? If this setting is set to Yes then this is expected behaviour.

**Comment by radik10** [comment]
Hi, 
1st - if you set page offline in global configuration, you must after that clear cache (to set page in to the offline mode), if not, page will not go offline, (this was problem aslo with protostar template)

2nd - "System> Global Configuration> System tab> Session Settings> Shared Sessions > Yes" has nothing with my problem, only it is complitaing joomla administration (red error messages). So I have it set to "No".

3th - template used (frontend) didn't have "offline.php" file. After copying it from other template (or create new), and after cleared cache (regular labs: clean cache) in joomla adminstration, it is possible to set up "site offline" in "System> Global Configuration> Site> Session Settings > Site Offline". So now it works. 

Thanks for complaisance.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17577">issues.joomla.org/tracker/joomla-cms/17577</a>.</sub>

**Comment by ghost** [comment]
@radik10 please close as this Issue is solved, thanks.
