### ISSUE TITLE
Managing extension packages

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#17579]
### Steps to reproduce the issue
In Extensions / Manage / Manage it is possible to order extensions by package ID.
However, it is not possible to search for all extensions in a particular package.
Neither is it possible to manage package extensions from there.

### Expected result
Expect to see a Extensions / Manage / Packages menu item.
Will list all installed packages.
Click on package and then able to list all extensions in that package.
Click on an extension (say a plugin) and that will take you to the extension config.
E.G. for a plugin .../administrator/index.php?option=com_plugins&view=plugin&layout=edit&extension_id=???
Similarly list all related modules and ability to create a new module from their.
Also link related templates to their styles / templates views.

### Actual result
New feature

### Additional comments
Security - ability to restrict packages user can see / edit.
Ditto extensions in the package.

**Comment by zero-24** [comment]
Closing here as there is a patch proposal at #17585 Thanks @brainforgeUK
