### ISSUE TITLE
Joomla-cms-staging installation fails

### ISSUE THREAD

**Issue by twister65** [joomla/joomla-cms#17582]
### Steps to reproduce the issue
Clean install using Protostar without any 3rd-Party-Plugins -Components, with a postgreSQL database.
Administrator login.

### Expected result
Administrator login

### Actual result
Error displaying the error page
Error: 0 ERROR: column "m.language" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: ...E(SUM(m.home),0) WHEN 0 THEN "WHEN 1 THEN CASE m.language...^

### System information (as much as possible)
PostgreSQL 9.5.6
PHP 7
Joomla-CMS-staging (17/08/2017)

### Additional comments
This query appears in this file : administrator/components/com_menus/presets/joomla.xml (line 208).
https://github.com/joomla/joomla-cms/commits/staging/administrator/components/com_menus/presets/joomla.xml
`sql_select="a.title, a.menutype, CASE COALESCE(SUM(m.home), 0) WHEN 0 THEN '' WHEN 1 THEN CASE m.language WHEN '*' THEN 'class:icon-home' ELSE CONCAT('image:mod_languages/', l.image, '.gif') END ELSE 'image:mod_languages/icon-16-language.png' END AS icon"
			sql_from="#__menu_types AS a"
			sql_where="a.client_id = 0"
			sql_leftjoin="#__menu AS m ON m.menutype = a.menutype AND m.home = 1 LEFT JOIN #__languages AS l ON l.lang_code = m.language"
			sql_group="a.id"
			sql_order="a.title ASC"`

**Comment by wojsmol** [comment]
@izharaazmi Plese check this may be related to https://github.com/joomla/joomla-cms/pull/17511

**Comment by izharaazmi** [comment]
Yeah right. I'll check it soon

**Comment by alikon** [comment]
it fail on MySQLi 5.7.19 too
did'nt understand that query well :cry:

**Comment by ghost** [comment]
closed as having Pull Request #17620<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17582">issues.joomla.org/tracker/joomla-cms/17582</a>.</sub>
