### ISSUE TITLE
[4.0] com_menus controller misses default_view

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#17581]
### Steps to reproduce the issue
Display Menu Manager
Click on Options.
Click on Cancel

Error:
`An error has occurred.

    404 View not found [name, type, prefix]: joomla\component\menus\administrator\controller\, html, `

I added
```
class Controller extends BaseController
{
	/**
	 * @var		string	The default view.
	 * @since   4.0
	 */
	protected $default_view = 'menus';
}
```
in `/administrator/components/com_menus/Controller/Controller.php`
and it solves this issue.

But I am not sure this is enough or if we need to use `items`. 
Don't we also need a `public function display()` method?

@Webdongle  Thanks you for looking into this.

**Comment by ghost** [comment]
Issue confirmed.
![bildschirmfoto 2017-08-17 um 11 47 58](https://user-images.githubusercontent.com/8235763/29406662-f1756292-8341-11e7-9913-ae9d9984729a.jpg)

**Comment by C-Lodder** [comment]
Having fetched the **latest code**, I do NOT get the error you mentioned, I simply get redirected back to the dashboard when I click `cancel`. The code change you suggested ensure I get redirected back to `com_menu`.

**Comment by infograf768** [comment]
I confirm, if it was necessary, that I still get the error on a clean install of the latest code.

**Comment by wilsonge** [comment]
Fixed with https://github.com/joomla/joomla-cms/commit/6312df8b5b57b1652d519c4c64f3a30f1cefb8ec
