### ISSUE TITLE
[4.0] Admin menu module is totally broken

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#17593]
This is as a result of the merge of the 3.8 branch

@C-Lodder is going to fix this over the next 24 hours

**Comment by C-Lodder** [comment]
Gonna have to fix this tomorrow

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/17622

**Comment by wilsonge** [comment]
Closing as we have a PR
