### ISSUE TITLE
[4.0] Install failed "Column count doesn't match value count at row 75"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#17594]
### Steps to reproduce the issue
Using 4.0-dev:
![bildschirmfoto 2017-08-18 um 06 47 36](https://user-images.githubusercontent.com/8235763/29444599-556f3e36-83e1-11e7-8aaa-f3ab938e5522.jpg)

**Comment by C-Lodder** [comment]
@wilsonge possibly related to #__assets table?

**Comment by wilsonge** [comment]
Thanks! Fixed with dabb3e9b53
