### ISSUE TITLE
Error messages when banners and contacts extensions uninstalled

### ISSUE THREAD

**Issue by jamield** [joomla/joomla-cms#17598]
### Steps to reproduce the issue

Uninstall banners and/or contact extension. Go to database fix in admin (extensions > manage > database). This error message appears:

Table 'xxxx.#__contact_details' doesn't exist
Table 'xxxx.#__banners' doesn't exist

### Expected result

No error messages. Joomla should be able to handle having uninstallable extensions removed.

**Comment by zero-24** [comment]
@jamield banner nor com_contacts should be uninstalled as they are not decoupled. Please restore them.

As they are not decoupled this is the expected behavior 😄

**Comment by jamield** [comment]
Does this not therefore expose the issue that it's possible to uninstall banners and contacts and therefore this should be made impossible?

**Comment by zero-24** [comment]
Sure. There is already code prepared to avoid that in 3.8.0 please check & test this out: https://github.com/joomla/joomla-cms/pull/17219

**Comment by jamield** [comment]
Nice! Thanks for this 👍
