### ISSUE TITLE
Message "Refresh Manifest Cache failed: Extension is not currently installed"

### ISSUE THREAD

**Issue by EliLadg** [joomla/joomla-cms#17604]
After updating Joomla! from 3.7.4 to 3.7.5 I received this message _Refresh Manifest Cache failed: Extension is not currently installed_.

In the next Joomla! updates it could be possible to add in the message the name of the extension that causes the problem?

PS: I solved (I hope!) this prblem from Extensions - Manage - Update sites - Refresh, I think it's correct, isn't it?

Thank you!

**Comment by ghost** [comment]
thanks for reporting. Closed as Issue solved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17604">issues.joomla.org/tracker/joomla-cms/17604</a>.</sub>

**Comment by brianteeman** [comment]
No it is not solved. 

The request is that the name of the extension is added to the message

**Comment by ghost** [comment]
Correct, was on wrong Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17604">issues.joomla.org/tracker/joomla-cms/17604</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #19560
