### ISSUE TITLE
[4.0] Error with JEventDispatcher::getInstance();

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#17612]
This happens when new sampledata module is displayed.
![screen shot 2017-08-19 at 08 51 32](https://user-images.githubusercontent.com/869724/29484288-ad6c5512-84bb-11e7-8c99-7bd54bc8d2a5.png)

**Comment by infograf768** [comment]
Normally should be replaced I guess by
`$data = \JFactory::getApplication()->triggerEvent('onSampledataGetOverview', array('test', 'foo'));`
This gets rid of the error but sampledata can't still be installed.
`There is an error in the sample data plugins. Response is invalid.`

Will make patch for the original issue.

**Comment by zero-24** [comment]
Closing as there is a patch at #17617
