### ISSUE TITLE
A non well formed numeric value encountered in com_installer

### ISSUE THREAD

**Issue by p3core** [joomla/joomla-cms#17616]
### Steps to reproduce the issue
http://localhost/administrator/index.php?option=com_installer&view=warnings
Extensions
----->Manage
----->Warnings

### Expected result
No warnings detected...

### Actual result
A non well formed numeric value encountered in C:\xampp\htdocs\administrator\components\com_installer\models\warnings.php on line 45

### System information (as much as possible)
Database Version | 5.5.5-10.1.25-MariaDB
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.1.7
Web Server | Apache/2.4.26 (Win32) OpenSSL/1.0.2l PHP/7.1.7
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 3.6.5 Stable

### Additional comments
-----None

**Comment by ghost** [comment]
can you please Update on latest Release an test if Issue happens?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17616">issues.joomla.org/tracker/joomla-cms/17616</a>.</sub>

**Comment by zero-24** [comment]
> Joomla! Version | Joomla! 3.6.5 Stable

This is a nearly 8 Month old Version of code. That kind of issues had been fixed in one of our 3.7er patches please update to 3.7.5. When you still have the same problem please let us know.

Thanks,

**Comment by ghost** [comment]
closed as stated above. Please reopen if Issue isn't solved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17616">issues.joomla.org/tracker/joomla-cms/17616</a>.</sub>
