### ISSUE TITLE
[4.0] Error "addStyleDeclaration" on installing Plugin

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#17611]
### Steps to reproduce the issue
Tried to install Patchtester, got:
![bildschirmfoto 2017-08-19 um 07 19 34](https://user-images.githubusercontent.com/8235763/29483749-e8b2c032-84ae-11e7-9411-1906a6610b4c.jpg)
### System information
4.0-dev
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by wilsonge** [comment]
Fixed with https://github.com/joomla/joomla-cms/commit/556ce728bba3a671f9658374542770c2083f29c1
