### ISSUE TITLE
Define a dedicated class for both field-label and field-value sections

### ISSUE THREAD

**Issue by mrhossein2017** [joomla/joomla-cms#17625]
وقت بخیر

در جوملا 3.7 مشکلی در سفارشی سازی کلاس ها فیلدها وجود دارد.
یک فیلد در جوملا 3.7 برای نمایش داراس سه قسمت است.
field-entry و field-label و field-value
زمانی که شما در تنظیمات یک فیلد به او کلاس اختصاصی می دهد این کلاس تنها به بخش field-entry اثر می گذارد. این به این معنا است که شما نمی توانید ظاهر field-label و field-value را برای فیلد خود بطور خاص سفارشی سازی نمایید. برای حل این موضوع به دو قسمت دیگر در تنظیمات فیلدها نیاز است تا بتوان در هر فیلدی که می سازیم بطور جداگانه برای  field-label و field-value کلاس تعریف کرد.

مشکل دیگر این است که پلاگین درج فیلد در مطلب جوملا 3.7 کلاس اختصاصی فیلد را نمی خواند و از تنظیمات عمومی کلاس پیروی می کند. یعنی در صورتی یکه برای یک فیلد کلاس سفارشی ساخته شده باشد ظاهر فیلدی که در ابتدا یا انتهای مطالب قرار گرفته با ظاهر فیلدی که توسط پلاگین در وسط مطالب قرار گرفته متفاوت خواهد بود.

مشکل سومی هم وجود دارد و آن اینکه نمی توان نمایش پیش فرض فیلد مطلب را بطور کامل غیرفعال کرد و تنها از پلاگین درج فیلد در مطلب برای نمایش فیلدها استفاده کرد. بهتر است نمایش پیش فرض فیلدهای جوملا 3.7 علاوه بر بالا و پایین دارای گزینه (هیچ) هم باشد. این برای مواقعی که می خواهیم بطور موقت نمایش فیلدهای یک مطلب را غیرفعال کنیم یا تنها از پلاگین برای نمایش در میان مطلب استفاده کنیم مفید خواهد بود.

متشکرم.

**Comment by ghost** [comment]
can you please write the Issue in English, thanks.

**Comment by mrhossein2017** [comment]
I do not know English well.
Please use the translate.google.com convert Persian into English.

**Comment by mrhossein2017** [comment]
Good time

In Joomla 3.7 there are some problems with class customization.
A field in Joomla 3.7 has three parts for display.
Input field and field-tag and field-value
When you assign a field to a specific class in the settings, this class only affects the field-entry field. This means that you can not customize the field-label and field-value appearance for your field. To resolve this issue, there are two other parts in the field's settings to be defined in each field we create separately defined for field-label and field-value class.

Another problem is that the Plugin does not include the field in Joomla 3.7. It does not know the class's dedicated field and the general settings class. This means that it will be different for a custom field class. The appearance of a field that differs initially or at the end of the content with the appearance of a field that is different from the content of the plugin.

There is also a third problem, and it can not completely disable the default view of the content field, and only use the plugin to insert the field in the article to display the fields. It is better to display the default view of Joomla! 3.7 fields in addition to the top and bottom options (no). This will be useful for when we want to temporarily disable the display of fields in a post or only use the plug-in to display the content.

**Comment by ghost** [comment]
is this #15667 something that may help you?

**Comment by mrhossein2017** [comment]
Although I'm not able to read English well, I suppose I have similarities with what I said.

What I definitely know is that in updating Joomla, three things have to be added to resolve this issue.
1- Provides the ability to define separate classes for three field-entry fields, field-label and field-value for each field specifically.
2- Follow the plugin to enter the field in the post from the dedicated classes of each field if specified.
3- Possibility of not displaying the fields of a content.

Of course, adding two filter plugins and comparing two or more field fields can complete and complete this collection.

**Comment by brianteeman** [comment]
> 3- Possibility of not displaying the fields of a content.

This is already possible. Set automatic display to No

**Comment by mrhossein2017** [comment]
thank you
I hope that with the addition of the rest of the cases, the power of this component will increase.

**Comment by mrhossein2017** [comment]
excuse me
Are you a Joomla project developer yourself?
Can we hope that these happen in the next updates?

**Comment by ghost** [comment]
closed in favor #18173<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17625">issues.joomla.org/tracker/joomla-cms/17625</a>.</sub>

**Comment by mrhossein** [comment]
Thank you.
But I still did not receive a clear answer from you to solve my problem.
Please give me the code you need to resolve this issue if I may add my Joomla!
Thank.
