### ISSUE TITLE
user.ico so favicon.ico gets not overwritten

### ISSUE THREAD

**Issue by jjsjjs** [joomla/joomla-cms#17629]
### Steps to reproduce the issue
Use the standard templates, update Joomla

### Expected result
your favicon is gone

### Actual result
The Joomla favicon is displayed instead of your own

### System information (as much as possible)
Every version of Joomla

### Additional comments
Is it possible to create a user.ico so the favicon is not getting overwritten every time there is an update?
This is happening when you make use of protostar or beez template. It's most annoying and easily forgotten to copy again and again and again. Thanks!

**Comment by brianteeman** [comment]
No its not possible as favicon is an internet standard

The only option is to use a copy of the default template

**Comment by jjsjjs** [comment]
You could leave it out of every update, and only put it in when a big update (read new Joomla version) is there. Updating the favicon every time is not bringing anything, but hassle for every Joomla user who uses the standard (and mostly adjusted) templates.

**Comment by brianteeman** [comment]
Re-opening

That might be possible.

**Comment by jjsjjs** [comment]
Would be great, thank you.

**Comment by C-Lodder** [comment]
Then the same would go for all the LESS files too. If you want to customize the default Protostar template, you should copy it. Same applies if you want to change the favicon

**Comment by jjsjjs** [comment]
Maybe that's true. I don't know if the LESS files are also altered as much as the template.css, which has support for user.css

**Comment by mbabker** [comment]
The right way to do things if you are going to use the core templates is to duplicate them.  We can not (and should not) pick and choose which files are "important" for an update and which files are "important" to not override because a user might have made some changes.  So it is an all or nothing agreement.

**Comment by brianteeman** [comment]
Closing

**Comment by franz-wohlkoenig** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17629">issues.joomla.org/tracker/joomla-cms/17629</a>.</sub>

**Comment by jjsjjs** [comment]
ok fair enough. Thanks.

**Comment by Bakual** [comment]
From memory, if you put a favicon into the root directory of your Joomla, the one from the template folder gets "overriden" and the one in root will be used.

**Comment by mbabker** [comment]
Well, close.  If one doesn't exist in the template and one exists at the root, that will be used.

https://github.com/joomla/joomla-cms/blob/c343565619b7e966caff5b202f6c6dced1f0cec7/libraries/src/Document/HtmlDocument.php#L663-L675

**Comment by jjsjjs** [comment]
Well that would be the same as overwriting the existing favicon, only now delete the one in in the template directory. So copying the template directory and rename would then still be the best option in this case.

**Comment by Bakual** [comment]
@mbabker Do you think we can change that order in J4? Because imho it makes more sense the other way around. Especially since we don't ship a favicon anymore in the root (I think there used to be one in earlier releases).
I doubt the default favicon we (or a template developer) ship is appropriate in most cases.

**Comment by mbabker** [comment]
Feel free to propose a PR.

**Comment by Bakual** [comment]
Done: #17677

**Comment by jjsjjs** [comment]
Thanks a lot for this constructive discussion and the PR.
