### ISSUE TITLE
[4.0] Cannot use ApplicationHelper because the name is already in use

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#17621]
### Steps to reproduce the issue

Install Joomla 4.0-dev at 4600082c5cb29573cffdcee1f7c1da8a4fbdc2a2

Login to front end

Click the edit button on the main menu

### Expected result

Ability to edit the menu

### Actual result

![screen shot 2017-08-19 at 14 21 09](https://user-images.githubusercontent.com/400092/29486949-ad304b5c-84e9-11e7-9e0f-2e942b2654a3.png)

**Comment by wilsonge** [comment]
Thankyou! Fixed with https://github.com/joomla/joomla-cms/commit/31ba44ad3ee0d0a3a39c1de23fc8cdc510b2fcc2
