### ISSUE TITLE
[4.0] CSS Class cleanup

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#17634]
- [ ] Remove the `clearfix` class if children are using `flex` instead of `float`

**Comment by ghost** [comment]
@mbabker should this be added to [Projects](https://github.com/joomla/joomla-cms/projects)?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17634">issues.joomla.org/tracker/joomla-cms/17634</a>.</sub>

**Comment by hardik-codes** [comment]
@C-Lodder in which CSS file this cleanup has to be done?

**Comment by brianteeman** [comment]
This can be closed
