### ISSUE TITLE
Editing comments in the issue tracker

### ISSUE THREAD

**Issue by CiverBlack** [joomla/joomla-cms#17649]
Hi,

i´m missing the option to edit my comments here in the issue tracker. i mean i can do it via GitHub but it feels weird to go to another site to edit a comment i wrote here.

Thanks

@iCampus

**Comment by ghost** [comment]
can you please open the issue at https://github.com/joomla/jissues, thanks.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17649">issues.joomla.org/tracker/joomla-cms/17649</a>.</sub>
