### ISSUE TITLE
Cannot add menu item after updating to Joomla 3.7.5

### ISSUE THREAD

**Issue by lutecki** [joomla/joomla-cms#17659]
### Steps to reproduce the issue
Add another menu item, then select menu type "single articles cathegory".
Then select "Pick" in the "Pick cathegory".
In the cathegory selection click on any cathegory.

![obraz](https://user-images.githubusercontent.com/31219810/29532396-36ab89b8-86ad-11e7-8d21-30f48c005fbd.png)

![obraz](https://user-images.githubusercontent.com/31219810/29532339-f2228e5e-86ac-11e7-9cab-bbe1c6774d0d.png)

### Expected result
The clicked cathegory is set as the selected one.

### Actual result
The modal dialog is not working. Clicking the cathegory is not closing it. Using "Close" button closes it but the cathegory is not selected.

The JS console shows
`TypeError: window.processModalSelect is not a function`
when clicking on the cathegory.

### System information (as much as possible)

Setting| Value
-- | --
 System operacyjny | Linux v241.home.net.pl 4.0.6 brocade-gut #36 SMP Thu May 19 16:53:59 CEST 2016 x86_64
Wersja bazy danych | 5.5.54-38.6-log
Metoda porównywania znaków w bazie danych | utf8mb4_general_ci
Metoda porównywania znaków przy połączeniu z bazą danych | utf8mb4_general_ci
Wersja PHP | 5.6.30
Serwer WWW | IdeaWebServer/0.82 (like Apache)
PHP działa na | ucgi10
Wersja Joomla! | Joomla! 3.7.5 Stable [ Amani ] 14-August-2017 12:09 GMT
Wersja Platformy Joomla! | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Klient użytkownika | Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0

### Additional comments
I also cannot edit existing menu items (created with Joomla 3.6.x) with "single articles cathegory" type. The modal is not responding and I even cannot close it.

**Comment by wojsmol** [comment]
@lutecki From which version of Joomla! you performed the update? Have you asked for help on the Polish Joomla! Forum? If so, please provide a link to the topic.

**Comment by lutecki** [comment]
Hi,
From my old version.php:

RELEASE: 3.6
CODENAME: Noether
RELDATE: 1-December-2016

I didn't ask on the Polish Joomla! Forum. I found a similar menu problem issue (#15719) here, so I thought this is a good place to report mine.

**Comment by wojsmol** [comment]
Most probably the update did not complete successfully. Check if this 2 files exists on your website:/media/system/js/modal-fields.js
/media/system/js/modal-fields-uncompressed.js
Additional info : on home.pl servers you must set domain without separation - at lest during Joomla update.

**Comment by lutecki** [comment]
I'm now comparing the FTP with a full package ZIP of 3.7.5. The update had to went wery wrong, although I got no error. I can see many, many differences in all kind of files. I think I will try to update them manually.

Can you explain what you had in mind by saying "you must set domain without separation"?

**Comment by wojsmol** [comment]
Please create topic on a Polish Joomla! Forum (http://forum.joomla.pl) where I can assist you better. This repo is generally not for individual website support. Domain separation see https://pomoc.home.pl/baza-wiedzy/jak-przekierowac-domene-na-katalog
