### ISSUE TITLE
TinyMCE Menu Linking, is slow.

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#17665]
So when you link to menu items etc, if you highlight text and link it doesn't work at all.

So you have to insert the menu item and then you need to change the text. This is a slow process. 

Can we make it so when text is highlighted and then insert menu is used the text is just linked?

**Comment by mbabker** [comment]
That requires making it a TinyMCE plugin if I'm not mistaken, not our generic "extended editor" plugin.

**Comment by brianteeman** [comment]
Are you really talking about tinymce or the xtd-editor plugin - i am confused

Maybe a screencap will help to explain

**Comment by tonypartridge** [comment]
Sorry yes, it is the Button - Menu Plugin. Its a bit confusing now given someone has merged buttons into the toolbar you assume / think it's part of the toolbar not a button.

**Comment by tonypartridge** [comment]
But fundamentally it should work like the tinymce built in link plugin. From what I can see of the code we would just need to pass in the highlighted text into the data attrib for when we click the menu item in the list. But I can't fathom out how the link/code is generated from the button yet. Anyone fancy the challenge.. a JS dev should be able to do it fairly quickly ;-)

**Comment by coolcat-creations** [comment]
+ it doesn´t work at the first time for me, i have to open it again and the second time the link is placed then.

**Comment by tonypartridge** [comment]
Its a very non user friendly system at present.

**Comment by Fedik** [comment]
@mbabker are right, it require making the plugin specifically to TinyMCE 

xtd-editor plugin are general thing

**Comment by tonypartridge** [comment]
Soo... who has the skillz to do it? is this a Dimitris area ;-). Ideally, it should work exactly like the Link linking.

**Comment by dgrammatiko** [comment]
@tonypartridge @Fedik the code for the core buttons as tinyMCE plugins already exists: https://github.com/joomla/joomla-cms/pull/7152/files

The missing part is extending the PHP API for the XTD_Buttons so they can return also the tinyMCE plugin path

**Comment by Fedik** [comment]
> The missing part is extending the PHP API for the XTD_Buttons so they can return also the tinyMCE plugin path

no need new API, just include plugin script, see [Example of loading the plugin from another URL](https://www.tinymce.com/docs/advanced/creating-a-plugin/#exampleofloadingthepluginfromanotherurl) 

only problem, that XTD_Buttons should check whether they loaded by tinyMCE editor

**Comment by tonypartridge** [comment]
@dgt41 @Fedik JS isn't my forte... could one off you kinda persons take a look? :D

**Comment by dgrammatiko** [comment]
@tonypartridge @wilsonge @Fedik I'm gonna introduce one more method to our Joomla.Editors API:
```js
getSelection() { /* return the current selection */ }
```

Then every XTD Button could call this method, get the text do any fancy stuff and then return using the method `replaceSelection`

For the editor none the API will look like:

```js
		const that = this;
		/** Register Editor */
		Joomla.editors.instances[that.childNodes[0].id] = {
			'id': that.childNodes[0].id,
			'element':  that,
			'getValue': () => { return that.childNodes[0].value; },
			'setValue': (text) => { return that.childNodes[0].value = text; },
			'getSelection' : () => {
				// obtain the index of the first selected character
				var start = that.childNodes[0].selectionStart;
				// obtain the index of the last selected character
				var finish = that.childNodes[0].selectionEnd;
				// obtain the selected text
				return that.childNodes[0].value.substring(start, finish);
			},
			'replaceSelection': (text) => { return that.insertAtCursor(text); },
			'onSave': () => {}
		};
```

Similar but easier implementation for tinyMCE and code mirror should be applied

**Comment by Fedik** [comment]
@dgrammatiko that could work :wink:

**Comment by Quy** [comment]
Please test PR #23224<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17665">issues.joomla.org/tracker/joomla-cms/17665</a>.</sub>
