### ISSUE TITLE
Superuser cannot login if not in ldap

### ISSUE THREAD

**Issue by edrobal** [joomla/joomla-cms#17663]
### Steps to reproduce the issue

You must have ldap plugin active. I have also adminexile active. Superuser is not in ldap.

### Expected result
Super user must be able to login !!!

### Actual result

Superuser cannot login if not in ldap but can login if I create it in ldap.

### System information (as much as possible)

This bug was not in version before 3.7.3.

**Comment by brianteeman** [comment]
Quick thought. Is the joomla authentication plugin ordered ABOVE the ldap plugin. In other words it will check using the joomla plugin before the LDAP plugin

**Comment by edrobal** [comment]
But I change nothing since I create this site and there is no problem before the update to 3.7.3.

**Comment by brianteeman** [comment]
Please check my comment to see. I understand you are saying that you have changed nothing but please check anyway.

**Comment by edrobal** [comment]
The order is :
1 - Joomla
2 - Cookie
3 - LDAP

**Comment by ghost** [comment]
@edrobal have you tried Suggestion of @brianteeman?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17663">issues.joomla.org/tracker/joomla-cms/17663</a>.</sub>

**Comment by edrobal** [comment]
Can I downgrade to version before 3.7.3 ?

**Comment by edrobal** [comment]
I upgrade to the last version and I have always this problem. Is there a hope this was corrected in this year or next ?

**Comment by brianteeman** [comment]
Still cannot confirm this

**Comment by edrobal** [comment]
Now it's OK
