### ISSUE TITLE
[3.8 Beta 3] New Router Label

### ISSUE THREAD

**Issue by Gitjk** [joomla/joomla-cms#17673]
How about changing the labels of the buttons which disable/enable the new router? I would suggest to use 'Legacy Router' and 'New Router'. J3.8 was announced primarily for the inclusion of the new router. Therefore it doesn't make sense to me to release J3.8 'stable' but still label the new router 'Experimental'. Either the new router works stable or it doesn't.

BTW - I've been using the new router as a plugin (made available by 'Hackwar') on several websites since more than 5 months without any issue.

**Comment by tonypartridge** [comment]
Agreed on the change

**Comment by brianteeman** [comment]
@mbabker can we do this now or is it too late for 3.8

**Comment by mbabker** [comment]
Personally I would say to do it but someone would need to coordinate with the translation teams so we don't get an angry lynch mob coming at us for changing strings after freeze.

**Comment by ghost** [comment]
closed as having Pull Request #18165<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17673">issues.joomla.org/tracker/joomla-cms/17673</a>.</sub>
