### ISSUE TITLE
Feature Request: Publishing Timer for Menu Items.

### ISSUE THREAD

**Issue by sandmanmedia** [joomla/joomla-cms#17678]
### Steps to reproduce the issue
Menu -> Main Menu ->choosing Menu Item

### Expected result
Input Start Publishing, Stop Publishing date and time, etc (the same as Articles) to set up timer.

### Actual result
There are no options for Start/stop Publishing Date and Time.

### System information (as much as possible)
Joomla 3.x

### Additional comments
I think this feature would be very convenient and necessary for managing content. Could someone please help to develop this feature? Thank you.

**Comment by alikon** [comment]
@sandmanmedia  can you test #17709

**Comment by ghost** [comment]
closed as having Pull Request #17709<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17678">issues.joomla.org/tracker/joomla-cms/17678</a>.</sub>
