### ISSUE TITLE
Sample Data Plugin text confuses me

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#17680]
### Steps to reproduce the issue
I think it may be related to this, I installed the plugin here and got the same issue.  https://github.com/joomla/joomla-cms/pull/17482

When I got to plugins and see this plugin Plugins: Sample Data - Blog
I see this text **Provides the blog sample data. Can be installed using the sample data module.**
So then I go to modules and I cannot see "Sample data module"

### Expected result
I expect to see a module but perhaps it is terminology or my lack of understanding

### Actual result
No module exists, no module is available if I press new

### System information (as much as possible)

[systeminfo-2017-08-22T18-19-57-05-00.txt](https://issues.joomla.org/uploads/1/fab1e3d44b83a472b490504e7718e4c4.txt)

**Comment by Sandra97** [comment]
The module is named "Sample Data" and is there if you look at the Administrator Modules.

**Comment by uglyeoin** [comment]
Yes, sorry I have found it now.  Please close, I don't think I can.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17680">issues.joomla.org/tracker/joomla-cms/17680</a>.</sub>
