### ISSUE TITLE
Joomla 3.7.5 and 3.8.0beta3 doesn't work with PHP 7.2.0beta3

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#17685]
### Steps to reproduce the issue

* upgrade php to 7.2.0beta3
* open front or backend page

### Expected result

default Joomla Page

### Actual result

Error Message:

```
<br />
<b>Fatal error</b>:  Uncaught Error: Class 'JClassLoader' not found in /web/x/libraries/cms.php:40
Stack trace:
#0 /web/x/includes/framework.php(18): require_once()
#1 /web/x/index.php(40): require_once('/web/x...')
#2 {main}
  thrown in <b>/web/x/libraries/cms.php</b> on line <b>40</b><br />
```

### System information (as much as possible)

* Apache 2.2
* PHP 7.2.0beta3
* Debian Linux 8.8

### Additional comments

It look like that the autoloader doesn't work.

**Comment by mbabker** [comment]
If the autoloader were completely broken our Travis CI builds wouldn't run at all (https://travis-ci.org/joomla/joomla-cms/jobs/268181310 is the last build for staging on PHP 7.2 as of this moment).  So I don't think there's a fatal error in the autoloader, meaning there could be an issue with the local environment at play here.

**Comment by HLeithner** [comment]
hmm, ok I will check this.

**Comment by mbabker** [comment]
FWIW I did try installing PHP 7.2 this morning but ran into a whole boatload of issues with my MacBook's Homebrew install so I had to give it up to come in to work.  But I think I got those issues resolved so over the weekend I can give it a fresh try and see if I can replicate the issue too.

**Comment by mbabker** [comment]
I did get PHP 7.2.0beta2 installed (latest version in Homebrew, there's still an open PR to get the latest beta published in that repo) and I couldn't duplicate the issue.  The autoloader worked as expected.

**Comment by HLeithner** [comment]
I test phpmyadmin on the same host and it seam to works fine, also phpinfo() looks ok.

I will do more tests on monday.

**Comment by mbabker** [comment]
We haven't seen an issue like this on CI builds and I've been doing some local tests without running into this.  So closing for now as non-reproducible.  If we do end up running into a scenario where it is reproduced, we can always reopen this.
