### ISSUE TITLE
Upgrade does not change version properly

### ISSUE THREAD

**Issue by gwsdesk** [joomla/joomla-cms#17696]
Upgrade to Joomla 3.8.0-beta with update package (from 3.7.5) does not changes the version to 3.8.0-Beta3. See image
![screen shot 2017-08-24 at 05 03 14](https://issues.joomla.org/uploads/1/db3e30d2cd1a10bc3ea768f1b8fe510c.gif)

**Comment by ggppdk** [comment]
That is site title,

but i can understand why this is confusing,
when you installed this testing website, you used 'Joomla 3.7.5' as site title exactly because it is a testing website ... and this resulted in this misunderstanding

**Comment by gwsdesk** [comment]
Ahh me confused indeed. Thanks for the clarification Georgios and after changing the title and refreshing cache all is fine
![version-correct](https://user-images.githubusercontent.com/8178486/29650897-f16e3c16-88c7-11e7-9fe3-7e9a8117d965.gif)
Thanks for the heads-up

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17696">issues.joomla.org/tracker/joomla-cms/17696</a>.</sub>
