### ISSUE TITLE
[4.0] Overlapping header / add margin-bottom to header

### ISSUE THREAD

**Issue by eXsiLe95** [joomla/joomla-cms#17698]
### Steps to reproduce the issue

A fresh installation of Joomla! 4.0-dev is required. Load demo content and go to any page (e.g. Parks,
 <yourinstallpath>/index.php/parks-home)

### Expected result
The menus on the sides of the site should have a little distance to the header. Should look something like this:
![This is what it should look like:](http://i.imgur.com/oMsc6jg.jpg "Correct Header Margin")

### Actual result
At the moment, the menues and content area is beeing overlapped by the header area. You can also see it with the developer tools highlighting the content area.
![This is what it actually looks like:](http://i.imgur.com/0vAR3sV.jpg "Missing Header Margin")
![This is the dev tools view](http://i.imgur.com/o2gJvjP.jpg "Dev Tools View")

### System information (as much as possible)
Running on xampp v3.2.2
Windows 10 (1703: 15063:540)
PHP 7.1.7
Joomla! 4.0-dev (joomla@4.0.0)
Chrome 60.0.3112.101 (64bit)

### Additional comments
I may will start dealing with this issue after coordinating.

Discovered @iCampus

**Comment by ghost** [comment]
Issue confirmed.

**Comment by C-Lodder** [comment]
Thanks for reporting. Will submit a PR today

**Comment by eXsiLe95** [comment]
I fixed this in the Chrome dev-tools by adding a margin-bottom: 15 fyi.

Thanks for supplying a fix! @C-Lodder <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17698">issues.joomla.org/tracker/joomla-cms/17698</a>.</sub>

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/17699

**Comment by wilsonge** [comment]
Closing as we have a PR
