### ISSUE TITLE
Wrong language string on installation

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#17706]
### Steps to reproduce the issue

Install, and press `Remove "installation" folder`

### Expected result

`"installation" folder removed.`

### Actual result

`&quot;installation&quot; folder removed.`

### System information (as much as possible)

install with en-gb language

**Comment by brianteeman** [comment]
What version of Joomla?

**Comment by 810** [comment]
staging

**Comment by brianteeman** [comment]
I didnt get that

**Comment by 810** [comment]
![ezgif-2-3d1923d8bc](https://user-images.githubusercontent.com/876623/29681932-9c67e432-8909-11e7-8029-6a9b74640aa6.gif)

**Comment by Quy** [comment]
Unable to reproduce with staging. I didn't have to click `Remove "installation" folder` button twice like you did in your screencast.

**Comment by 810** [comment]
tested again: Some result
New sub domain, downloaded staging again.

wamp 64x - chrome 60.0.3112.101

**Comment by 810** [comment]
With IE i see no quotes, its working correct.

IE = failed = &quot;installation&quot; folder removed.
Firefox = failed = &quot;installation&quot; folder removed.
Chrome = failed = &quot;installation&quot; folder removed.

**Comment by Quy** [comment]
Still unable to reproduce using Chrome v60.0.3112.113 in XAMPP on Windows 10.

**Comment by 810** [comment]
Please check that you select : English (United Kingdom)
i also made the mistake to select English us. Now all browsers are failing.

**Comment by Quy** [comment]
OK I can confirm the issue with English US.

**Comment by 810** [comment]
Uk you mean?
English US = working for me

**Comment by Quy** [comment]
Sorry, UK is not working. US is working only because it has not been updated per this PR #17436 .

**Comment by infograf768** [comment]
These strings should be modified to use escaped double quotes, or use single quotes
```
INSTL_COMPLETE_ERROR_FOLDER_DELETE="\"%s\" folder could not be deleted. Please manually delete the folder."
INSTL_COMPLETE_FOLDER_REMOVED="\"%s\" folder removed."
```
or
```
INSTL_COMPLETE_ERROR_FOLDER_DELETE="'%s' folder could not be deleted. Please manually delete the folder."
INSTL_COMPLETE_FOLDER_REMOVED="'%s' folder removed."
```

to get correctly
![screen shot 2017-08-25 at 08 52 29](https://user-images.githubusercontent.com/869724/29702827-35773ea2-8973-11e7-9ee5-f332e87c2f32.png)

**Comment by infograf768** [comment]
Another solution is to modify .../installation/controller/removefolder.php line 117-125 to use
`htmlspecialchars_decode`

```
// If an error was encountered return an error.
		if (!$return)
		{
			$app->sendJsonResponse(new Exception(htmlspecialchars_decode(JText::sprintf('INSTL_COMPLETE_ERROR_FOLDER_DELETE', 'installation')), 500));
		}

		// Create a response body.
		$r = new stdClass;
		$r->text = htmlspecialchars_decode(JText::sprintf('INSTL_COMPLETE_FOLDER_REMOVED', 'installation'));
```

@mbabker @Bakual 
What do you prefer?

**Comment by Bakual** [comment]
I would just use single quotes or escaped quotes.

**Comment by 810** [comment]
i made a pr for it, so I'm closing this issue

**Comment by infograf768** [comment]
PR is here https://github.com/joomla/joomla-cms/pull/17718
