### ISSUE TITLE
Tag filter in category list doesn't work with pagination

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#17711]
### Steps to reproduce the issue
* Create at least 11 articles so you get a 3 page list when the list size is at "5".
* Tag 6 of those articles with the same tag so you get two pages
* Create a menu item of the type "Articles » Category List" and set the "Filter Field" parameter to "Tags" (in the "List Layouts" tab).
* Now check that menuitem in frontend, filter by a tag. set the list size limit to "5" and try to go to the second page.

### Expected result
You should see the 6th article tagged to that tag.

### Actual result
The filter gets reset and you see all 3 pages of articles.

### Additional comments
This issue also exists in Joomla 3.7.4 (and maybe earlier).

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17711">issues.joomla.org/tracker/joomla-cms/17711</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #17728<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17711">issues.joomla.org/tracker/joomla-cms/17711</a>.</sub>
