### ISSUE TITLE
New URL router and options for com_users in 3.8 Beta 3

### ISSUE THREAD

**Issue by stevejburge** [joomla/joomla-cms#17715]
I'm not sure if this is intended behavior? Maybe it is

### Steps to reproduce the issue

Install Joomla 3.8 Beta 3.
Try to test the new URLs

### Expected result

New URL routing feature works identically for Articles, Contacts, News Feeds, Users

### Actual result

The Users component doesn't have the "Remove IDs from URLs" feature. 

Here is com_content:
![remove-urls](https://user-images.githubusercontent.com/3868028/29710489-7d805cfc-895e-11e7-9c6b-0133c2b338ae.png)

Here is com_users without that "Remove IDs from URLs" option:

![screen shot 2017-08-25 at 6 21 52 am](https://user-images.githubusercontent.com/3868028/29710469-6985ef3c-895e-11e7-8027-a443ddc74c76.png)

**Comment by SharkyKZ** [comment]
This is intentional. com_users doesn't have any views where IDs could be used for routing.

**Comment by stevejburge** [comment]
OK, thanks. I'll close this
