### ISSUE TITLE
[Regression] Batch Tag gives Fatal Error

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#17710]
### Steps to reproduce the issue
In the article manager, try to batch assign a tag to an article

### Expected result
Tag is assigned

### Actual result
An error has occurred. 
Call to a member function setNewTags() on null

### System information (as much as possible)
Call to a member function setNewTags() on null	
D:\xampp\htdocs\joomla38\libraries\src\MVC\Model\AdminModel.php:635

Call stack
--
|# | Function | Location
|-|--|--
1 | () | JROOT\libraries\src\MVC\Model\AdminModel.php:635
2 | Joomla\CMS\MVC\Model\AdminModel->batchTag() | JROOT\libraries\src\MVC\Model\AdminModel.php:261
3 | Joomla\CMS\MVC\Model\AdminModel->batch() | JROOT\libraries\src\MVC\Controller\FormController.php:268
4 | Joomla\CMS\MVC\Controller\FormController->batch() | JROOT\administrator\components\com_content\controllers\article.php:135
5 | ContentControllerArticle->batch() | JROOT\libraries\src\MVC\Controller\BaseController.php:710
6 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\administrator\components\com_content\content.php:21
7 | require_once() | JROOT\libraries\src\Component\ComponentHelper.php:392
8 | Joomla\CMS\Component\ComponentHelper::executeComponent() | JROOT\libraries\src\Component\ComponentHelper.php:367
9 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:101
10 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:159
11 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:267
12 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\index.php:51

### Additional comments
The same works in J3.7.5, so it looks like a regression in 3.8.0.

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17710">issues.joomla.org/tracker/joomla-cms/17710</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #17730 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17710">issues.joomla.org/tracker/joomla-cms/17710</a>.</sub>

**Comment by barraclm** [comment]
Why is this closed? The problem still exists.

**Comment by ggppdk** [comment]
@barraclm 

did you test with latest staging ?
This PR has been merged
https://github.com/joomla/joomla-cms/pull/18328
(Fix tags being deleted by any batch action and by drap and drop reordering of records)
