### ISSUE TITLE
Joomla 3.7.4 cannot save articles - Field required: Category

### ISSUE THREAD

**Issue by emceebee** [joomla/joomla-cms#17717]
Hello,

I cannot save articles anymore. 

I create a new article, add some content, choose a category to fit in and I want to save it. Even though I added a category, I will get the following message: Field required: Category.  The unwanted result; I cannot save changes in existing articles nor create new articles.. Anyone?

Joomla 3.7.4      PHP 7.1.7

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding.
