### ISSUE TITLE
BUG in Tagged page images in 3.7.x version

### ISSUE THREAD

**Issue by kotisivutohtori** [joomla/joomla-cms#17712]
### Steps to reproduce the issue
Seems there is a BUG in the Joomla core regarding TAGS Component. After update to Joomla 3.7.x (both 0 and 2) we noticed that the article intro images are missing from the TAGGED page. WE have added images for each menuitem for tagged pages. Before these were showing ok, but after 3.7.x the images are now missing. Each time after updating we have to go and command one line off from the code, to produce the images again. 

### Expected result

Tagged page menuitem images visible. 

### Actual result
Tagged page manuitem images missing. 

### System information (as much as possible)

Joomla 3.7.5 (and all new version sof 3.7.x)

### Additional comments
WE have to add a comment of row 124 in components/com_tags/views/tag/view.html.php
Without the # before the line 124, the tagged page menuitem images are missing. 

// Categories store the images differently so lets re-map it so the display is correct
        if ($items && $items[0]->type_alias === 'com_content.category')
        {
            foreach ($items as $row)
            {
                $core_params = json_decode($row->core_params);
                #$row->core_images = json_encode(array('image_intro' => $core_params->image, 'image_intro_alt' => $core_params->image_alt));
            }
        }

Hopefully this can be fixed so that we dont need to do the fix ourselves every time we update Joomla. :)

 - Anne

**Comment by ghost** [comment]
If i understand correctly i can't confirm.

Using  Menu Item Type "Tagged Items" get using 3.7.5:
![bildschirmfoto 2017-08-25 um 10 50 46](https://user-images.githubusercontent.com/8235763/29706900-aa822c56-8983-11e7-9192-94bf7adb42d0.jpg)

**Comment by n9iels** [comment]
@kotisivutohtori thanks for reporting! However I'm not able to reproduce this problem. Can you please be more specific how to reproduce this issue? Please tell us step by step what kind of menu item, tagged content and parameters you use.

The line you of code you are talking about seems to work fine as far as I can see. `$core_params->image` and `$core_params->image_alt` are correct variables.

**Comment by brianteeman** [comment]
Closing this as there has been no response and it has not been confirmed. It can always be reopened if needed.
