### ISSUE TITLE
Can'ts save article with calendar fields with no time. this happen ONLY with hungarian admin language

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#17721]
### Steps to reproduce the issue
1) Set Extensions > Language(s) > Administrator > Hungarian (Default)
1) Create Content > Fields > Calendar
2) Set Calendar Show Time: No
2) Create an article with it

### Expected result
Calendar field display with date and without time

### Actual result
You can save the article but you can't save the calendar field (it deleted and it will be empty). Error message (see attached picture). It happens only if your admin language is Hungarian! With English admin language it save perfectly.

### System information (as much as possible)
Joomla! Version: Joomla! 3.7.5 Stable [ Amani ] 14-August-2017 12:09 GMT 
Web Server: Apache 
PHP Version: 7.0.7![screen shot 2017-08-26 at 09 37 26](https://issues.joomla.org/uploads/1/17931f938f4753ae2088a4c7af50454d.jpg)

**Comment by ghost** [comment]
Issue confirmed.

Using Hungarian-Lang. in Backend cause Message on savin Calendar-com_fields.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17721">issues.joomla.org/tracker/joomla-cms/17721</a>.</sub>

**Comment by infograf768** [comment]
@dgt41 
I confirm the issue, only for the custom calendar field
I checked their ini files and calendar-locales and they look fine.

**Comment by dgrammatiko** [comment]
What is the format they re using?

**Comment by infograf768** [comment]
OK, I found the issue.
The string
DATE_FORMAT_FILTER_DATE="y-m-d"
is wrong
it should be
DATE_FORMAT_FILTER_DATE="Y-m-d"

**Comment by ghost** [comment]
@infograf768 are you making a PR?

**Comment by imanickam** [comment]
A revised version of the Hungarian language pack hu-HU_joomla_lang_full_3.7.5v2.zip has been published and is available at http://joomlacode.org/gf/project/jtranslation3_x/frs/?action=FrsReleaseBrowse&frs_package_id=6421.

**Comment by brianteeman** [comment]
Thanks for the update

**Comment by infograf768** [comment]
@franz-wohlkoenig 

> @infograf768 are you making a PR?

The error was not in core, but in the Hungarian language pack . ;)

**Comment by ghost** [comment]
Thanks for everybody!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17721">issues.joomla.org/tracker/joomla-cms/17721</a>.</sub>

**Comment by ghost** [comment]
Sorry, thanks **to** everybody. My english is bad :-(<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17721">issues.joomla.org/tracker/joomla-cms/17721</a>.</sub>
