### ISSUE TITLE
Color of the error message after attempting to delete a  Admin-menu

### ISSUE THREAD

**Issue by akritianand** [joomla/joomla-cms#17729]
### Steps to reproduce the issue
Try deleting an Admin menu which can't be deleted.
![screenshot from 2017-08-27 13-02-30](https://user-images.githubusercontent.com/23422253/29748150-c5d2e738-8b2d-11e7-8e9c-28cda298ed95.png)

### Expected result
Error message should have background red.

### Actual result
Error message has background green

### System information (as much as possible)
Joomla! 3.7.5
PHP 7.0.22-0ubuntu0.16.04.1

**Comment by ghost** [comment]
can you give an Example of Menu which can't be deleted?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17729">issues.joomla.org/tracker/joomla-cms/17729</a>.</sub>

**Comment by akritianand** [comment]
![screenshot from 2017-08-27 13-02-30](https://user-images.githubusercontent.com/23422253/29747942-1c0c6db4-8b28-11e7-8b43-f9e227f0da09.png)

**Comment by ghost** [comment]
Issue confirmed.

Create a Admin-Menu in Backend, open it with second Super-User-Account. Login as another Super-User and try to delete Admin-Menu > got Error-Message with green Background.

**Comment by ghost** [comment]
closed as having Pull Request #17734 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17729">issues.joomla.org/tracker/joomla-cms/17729</a>.</sub>

**Comment by C-Lodder** [comment]
Please reopen the issue as thr PR was closed

**Comment by ghost** [comment]
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17729">issues.joomla.org/tracker/joomla-cms/17729</a>.</sub>

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/17796

**Comment by ghost** [comment]
closed as having Pull Request #17796<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17729">issues.joomla.org/tracker/joomla-cms/17729</a>.</sub>
