### ISSUE TITLE
[4.0] Global Configuration: Tabs-Page change only after reload

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#17723]
### Steps to reproduce the issue
- open administrator/index.php?option=com_config
- change from Tab "System" to "Server": Page stay same.
- scroll down find Fields of both Tabs
- reload
- everything works until change Tab again.
### System information
4.0-dev
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
This has something to do with the switcher. Can't figure out why exactly it's happening, but if the following line is removed, then it fixes the tab issue:

https://github.com/joomla/joomla-cms/blob/4.0-dev/layouts/joomla/form/field/radio.php#L88

I'll be pulling the new web component switcher soon so hopefully that'll fix this properly

**Comment by C-Lodder** [comment]
@franz-wohlkoenig - Can you please re-test this? I have a feeling that it may have been fixed from https://github.com/joomla/joomla-cms/pull/18465

**Comment by ghost** [comment]
Can't install 4.0, Loop after "Install Joomla" (Screen 3).

### System information
macOS Sierra, 10.12.6
Firefox 56 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by ghost** [comment]
closed as Issue resolved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17723">issues.joomla.org/tracker/joomla-cms/17723</a>.</sub>
