### ISSUE TITLE
Menu Item Alias menu-selection issue

### ISSUE THREAD

**Issue by arrowthemes** [joomla/joomla-cms#17726]
### Steps to reproduce the issue
1. Install a clean Joomla installation with 3.7.5 or Joomla 3.8.0 beta 3 with no sample data
2. Create the following menu structure
<img src="https://image.ibb.co/d0051k/menu_list.png" alt="menu_list">
3. Create a new menu item of menu type 'Menu Item Alias' > Select a menu by clicking 'select' button > a modal showing all menus appears.

### Expected result
On the modal box that list the menu items, you should see any parent menus that are Text Separators or 'unselectable' menus but they should be without a link so that the user can't click on them.
<img src="https://preview.ibb.co/b6ZXgk/expected.png" alt="expected">

### Actual result
On the modal box that list the menu items, the sub items of the Parent menu 'Pages' are shown as if they are under 'Home'. This is misleading especially when you have dozens of menu. 
<img src="https://preview.ibb.co/hXbOnQ/actual.png" alt="actual">

### System information (as much as possible)
dbversion: 5.6.35
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 7.1.6
server: Apache
sapi_name: apache2handler
version: Joomla! 3.8.0-beta3 Beta [ Amani ] 22-August-2017 14:00 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

### Additional comments
Rather than hiding the parent Text Separator menu, it would be nice to show it but disable it. I remember we did the same with Module Assignment whereby the Text Separator menus are simply disabled but not hidden entirely.

**Comment by ghost** [comment]
Issue confirmed.
### System information
3.8-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by ghost** [comment]
closed as having Pull Request #18164<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17726">issues.joomla.org/tracker/joomla-cms/17726</a>.</sub>
