### ISSUE TITLE
[4.0] Site-Menu: Color of Subheads unreadable

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#17724]
### Steps to reproduce the issue
open administrator/index.php?option=com_config got:
![bildschirmfoto 2017-08-26 um 13 15 14](https://user-images.githubusercontent.com/8235763/29740847-cdd1daac-8a60-11e7-9862-2e5b71d467db.jpg)
"System" and "Component" isn't readable.
### System information
4.0-dev
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/17807

**Comment by ghost** [comment]
closed as having Pull Request #17807 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17724">issues.joomla.org/tracker/joomla-cms/17724</a>.</sub>
