### ISSUE TITLE
com_finder - invalid argument -

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#17731]
### Steps to reproduce the issue
* Go to Smart Search.
* Enter for example 'joomla' as search term.

### Expected result
* No warning message

### Actual result
* Warning message:

_Warning: Invalid argument supplied for foreach() in ..\joomla-cms-staging\joomla-cms-staging\components\com_finder\views\search\tmpl\default_results.php on line 57_

### System information (as much as possible)

* Joomla! 3.8.0-beta4-dev Development
* Xampp on Windows
* Error Reporting: System Default
* PHP 7.0.15 

### Additional comments

* None

**Comment by ghost** [comment]
Issue confirmed.
![screen shot 2017-08-27 at 08 13 39](https://issues.joomla.org/uploads/1/ee0628887a593d3eb85785ab62a55a19.jpg)
### System information
3.8-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17731">issues.joomla.org/tracker/joomla-cms/17731</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #17732 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17731">issues.joomla.org/tracker/joomla-cms/17731</a>.</sub>
