### ISSUE TITLE
JHTML::_('behavior.calendar') does not load  calendar-jos.css for Joomla 3.7.4

### ISSUE THREAD

**Issue by nchaudhary** [joomla/joomla-cms#17737]
### Steps to reproduce the issue
I am using JcalPro component for events.
When i am adding event form front end of the component and i select end date to insert there is a calendar display to add date. I see there is no CSS working of this calendar. Please chck. 

### Expected result
There should be Calendar CSS Load.

### Actual result

No calendar CSS working.

### System information (as much as possible)
Joomla 3.7.4
JCalPro 4.2.12
Php 5.6

**Comment by ghost** [comment]
Thanks for Reporting. Have you asked at JcalPro?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17737">issues.joomla.org/tracker/joomla-cms/17737</a>.</sub>

**Comment by dgrammatiko** [comment]
Core seems ok: https://github.com/joomla/joomla-cms/blob/aafbe7dc697d7bee0afc99d5b0d1144a9fad3d5e/libraries/cms/html/behavior.php#L583-L587

EDIT: there might be a bug in the JHtml::stylesheet, 
try removing `, $attribs` in the first line of the highlighted code

**Comment by brianteeman** [comment]
I tested this by inserting in `JHTML::_('behavior.calendar');` in my template and checking the source and I can see that all three of those expected files are being loaded.

**Comment by brianteeman** [comment]
I am closing this as not a core issue
