### ISSUE TITLE
[4.0] Global/Component Configuration broken

### ISSUE THREAD

**Issue by dgrammatiko** [joomla/joomla-cms#17745]
### Steps to reproduce the issue

Go to `administrator/index.php?option=com_config`
and try switching the tabs

### Expected result

tabs should switch

### Actual result

tabs not switching

**Comment by ghost** [comment]
closed as duplicate Report of #17723<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17745">issues.joomla.org/tracker/joomla-cms/17745</a>.</sub>
