### ISSUE TITLE
Pressing enter key on a calendar input field clears input of first calendar field in form on Joomla! 3.7.5

### ISSUE THREAD

**Issue by avjoomla** [joomla/joomla-cms#17741]
### Steps to reproduce the issue
Open an admin form with date field (i.e. an existing article)
Go to the Publishing options
Make sure there is a date value selected for Start Publishing and Created Date. 
If not set these date fields and save the article.
Click into the input field of the Created Date option then.
Press the enter key

### Expected result
Nothing should change with the selected dates visible in Start Publishing and in Created Date

### Actual result
Input of Start Publishing is cleared.
(It is always the input of the first date field in the form that is cleared)

### System information (as much as possible)
Joomla! 3.7.5
Php 7.1.7 on local XAMPP (as well as PHP 7.0.22 on productive webserver)
Chrome  60.0.3112.113 (Offizieller Build) (32-Bit)

### Additional comment
Tested also on Firefox 42.0 with the same result.

**Comment by ghost** [comment]
Issue confirmed.

Hit "Enter" on Keyboard while Curser is in "Created Date" empty "Start Publishing". "Save" bring current Date in "Start Publishing".

### System information
3.8-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17741">issues.joomla.org/tracker/joomla-cms/17741</a>.</sub>

**Comment by DrDreave** [comment]
I added a [pull request](https://issues.joomla.org/tracker/joomla-cms/17777 "Pull Request") treating this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17741">issues.joomla.org/tracker/joomla-cms/17741</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #17777 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17741">issues.joomla.org/tracker/joomla-cms/17741</a>.</sub>

**Comment by avjoomla** [comment]
Thanks, I tested with modified files from Pull Request https://github.com/joomla/joomla-cms/pull/17777 and this solves this issue here as well as https://github.com/joomla/joomla-cms/issues/17744<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17741">issues.joomla.org/tracker/joomla-cms/17741</a>.</sub>
