### ISSUE TITLE
Pressing clear button of calendar on required date field submits admin form in Joomla! 3.7.5

### ISSUE THREAD

**Issue by avjoomla** [joomla/joomla-cms#17744]
### Steps to reproduce the issue
Create an admin form with a required date field. I.e. open administrator\components\com_content\models\forms\article.xml and make field "publish_down" required by adding required="true" to field's xml node.
Go to Joomla! administration panel and open an article edit view.
Finish Publishing field should now be a required field.
Add Finish Publishing date, using the date picker of the calendar
Click "Clear" button on the Calendar

### Expected result
Some sort of error Message ("This field is required"). No changes to the calendar input field.

### Actual result
Article is save.
User is redirected to articles list view
Saved article is checked in

### System information (as much as possible)
Joomla! 3.7.5
Php 7.1.7 on local XAMPP (as well as PHP 7.0.22 on productive webserver)
Chrome 60.0.3112.113 (Offizieller Build) (32-Bit)

**Comment by ghost** [comment]
closed as having Pull Request #17744<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17744">issues.joomla.org/tracker/joomla-cms/17744</a>.</sub>

**Comment by avjoomla** [comment]
Thanks, I tested and can confirm, that the issue is fixed.
