### ISSUE TITLE
Referfing to "Unable to select category on front end after joomla 3.7.4 update #17245"

### ISSUE THREAD

**Issue by newagesamurai** [joomla/joomla-cms#17755]
### Steps to reproduce the issue

User in a User group with the following
Global permissions:
Create - allowed
Edit - denied
Edit own - allowed

Permissions for articles:
Create - allowed
Edit - denied
Edit own - allowed

Login with a user from this user group
Select "create a new article" / "edit existing article" via front end editor
Select category for the new article / change category for an existing article in the front end editor

### Expected result

category should be selected.

### Actual result

The category list view opens

### System information (as much as possible)
Joomla 3.7.5
PHP-Version | 7.0.21

### Additional comments
If the permisson in Global / Arcticles is set to "Edit - allowed" of course it works fine. So it seems that the "Edit own - allowed" permission does not seems to be recognized.
Was testing with some Akeeba Backups from 3.7.3 and can confirm, that after upgrading to 3.7.4. or directly to 3.7.5 the issue is appears again. So this must have something todo with 3.7.4.

**Comment by ghost** [comment]
Looking in User-Options i didn't find `Edit own`:
![bildschirmfoto 2017-09-02 um 17 42 50](https://user-images.githubusercontent.com/8235763/29996838-55b70848-9006-11e7-897d-6f5ac380fd14.jpg)

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17755">issues.joomla.org/tracker/joomla-cms/17755</a>.</sub>

**Comment by brianteeman** [comment]
@franz-wohlkoenig he is referring to the permissions set in global configuration not users.

**Comment by newagesamurai** [comment]
After some more tests I found out that the problem seems to be caused by the custom fields which are published on the fields tab in the frontend editor. As long as the custom fields are published a change of the articles category is not possible. When I try to change the category the site loads and jumps to the category list view. When I unpublish the custom fields the category change works correctly.

**Comment by ghost** [comment]
@newagesamurai looks like Issue is solved by #17872. Please have a Look and close Issue if Pull Request solve this Issue.

**Comment by brianteeman** [comment]
I am closing this as there has been no response to the comment above.
