### ISSUE TITLE
Add "whole word" search option to search's

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#17751]
### Steps to reproduce the issue
in the "testing" sample set if you search on "bug direct" you'll get partial matches.
in my experience this is rarely the case desired.
I think we should add an option for "Whole word" search instead of just 
any, all & exact.

### Expected result
Return ONLY matching whole words when set to any &/or all since exact can't be used with multiple SINGLE words.

### Actual result
![image](https://user-images.githubusercontent.com/1850089/29802049-9573a65c-8c38-11e7-9444-0c2f74fbf54b.png)
partial matches returned.

### System information (as much as possible)
[systeminfo-2017-08-29T02-34-30+00-00.txt](https://github.com/joomla/joomla-cms/files/1258941/systeminfo-2017-08-29T02-34-30.00-00.txt)

### Additional comments
Looks like the problem starts @ line 103 in content.php for "content plugin"
and near 218 in view.html.php in component.
@nibra and I spent a fair amount of time discussing / tracking this down.

**Comment by AlisonAMG** [comment]
And thank you guys so much for looking at this.

**Comment by brianteeman** [comment]
>  since exact can't be used with multiple SINGLE words.

why not?

**Comment by nibra** [comment]
Am 29.08.2017 um 10:31 schrieb Brian Teeman:

>>  since exact can't be used with multiple SINGLE words.
> 
> why not?

'exact' matches the search string as a whole. You currently can't search
for 'bug' and 'direct' without matching 'debug' and 'redirect'.

Regards,
Niels

-- 
| New Stars on the Horizon:      GreenCape  ·  nibralab  ·  laJoom |
| http://www.bsds.de   ·   BSDS Braczek Software- und DatenSysteme |
| Webdesign · Webhosting · e-Commerce · Joomla! Content Management |
 ------------------------------------------------------------------

**Comment by brianteeman** [comment]
Thanks for the explanation

**Comment by brianteeman** [comment]
For reference smart search aka com_finder searches for whole words

**Comment by N6REJ** [comment]
@brianteeman but sadly the layout is poor.  at least with Ajax live search it is.  The ultimate question is if smart search does it, why not simple search :P lol
A blog layout is sorely needed imo

**Comment by brianteeman** [comment]
Sorry but I don't understand your comment

**Comment by N6REJ** [comment]
@brianteeman its ok, lets worry about that on another issue/pr
for now lets worry about searchphrase

**Comment by tonypartridge** [comment]
@nibra can’t we do this with OR statements? If we explode on a space?

**Comment by nibra** [comment]
It is of course possible to add a search query parser. The problem IMO is to make it intuitive to use.
AND (all) and OR (any) are already implemented - they're just not searching for whole words.

**Comment by tonypartridge** [comment]
I was thinking more of a search option config for now, opposed to allowing the user control. We could allow overriding at a later date to give user control in search it desired.

**Comment by Hackwar** [comment]
Adding this feature for Joomla 3.x is nearly impossible, mainly because you are requesting a new behavior for com_search, but which at the same time requires all existing search plugins to be modified to support this feature. For Joomla 4.0 I hope to make this unnecessary, too, because we hopefully remove com_search and all related plugins for 4.0. Feel free to help making this possible and improving searching in Joomla by testing these PRs:
* #20185 [4.0] Removing artificial sharding from com_finder
* #20384 [4.0] Removing terms tuples from com_finder
* #20391 [4.0] Using language specific tokeniser and stemmer for com_finder

**Comment by brianteeman** [comment]
I did spend quite some time on this but it is virtually impossible for the reasons stated by @Hackwar 

If you really need this functionality today in J3 then you will have to use smart-search.
