### ISSUE TITLE
Implement serialized submit for forms with large number of fields

### ISSUE THREAD

**Issue by ggppdk** [joomla/joomla-cms#17757]
### Steps to reproduce the issue
I will be making a PR next week or earlier for this
but i would like to here any comments that may be helpful
please read on

Problem:
Forms with large number of fields can not be posted properly
because a usual limitation for max number of form fields via
-- PHP **max_input_vars** setting (e.g. 1000)

### Expected result

Joomla 's form JS
1. counts (a rough estimation) the number of --active-- fields in the form
2. and if they are close to 1000 (we can store current real limitation in a variable e.g. into Joomla.max_input_vars), 
3. then it serializes the form before it is posted 
4. and then it decompresses the form at server side

### Actual result

The above is not implemented and large forms can not be saved

### System information (as much as possible)

Systems with PHP max_input_vars limition (e.g. a value of 1000)

### Additional comments

How to do it
-- inside **Joomla.submitform**   we attach an extra submit event handler.

NOTE:
- we cannot do it without --**adding**-- a submit event handler because the serialization will run before any event handlers that try to manipulate the form by listening to the submit event (thus they will not be able to see the fields (fields get disabled after serialization) , plus we will be wrongly posting field values before their processing by submit events has finished)
- and then the above mentioned submit handler **cannot be attached on page load** !! because this will make it run before some of the other event handlers than are listening to the submit event, (and again the same problem that was mentioned above)

so it is needed that we both 
- do this work via a submit event handler
- and we also register our serialization submit handler last!! 

Process
1. count active fields and continue with serialization only if close to limitation
2. serialize only the active fields and store them in a single variable (**sending inactive fields is wrong**)
3. disables all active fields
4. **at this point in the future we can add an AJAX submit handler**, this must run after serialization (i am using this too already)

on Server side we need to decompress the posted data so that **they are an exact match of the original form** and are identical as if form has not been serialized
- the process must restore multi-level array fields properly, even if they have some empty values

i have already written code that does the above without using eval,
**but i am placing it at afterInitialize event**, if anyone tries to read posted input before this then it will not be possible
- so if someone has a better idea about an earlier place where to do decompression, please answer here

**Comment by dgrammatiko** [comment]
@ggppdk just a note that core.js is native javascript, so whatever you're planing to submit shouldn't depend on jQuery. Other than that your approach should be solid

**Comment by ggppdk** [comment]
@dgt41 

aahh i am using jQuery,
maybe i can submit the PR and you code replacing the jQuery code ?

**Comment by dgrammatiko** [comment]
@ggppdk George I think this might be handy: https://code.google.com/archive/p/form-serialize/downloads

But anyways, send your PR and let's take it from there

**Comment by ggppdk** [comment]
@dgt41 

ok, thanks for the link, i found another alternative,
and it worked with little modification,

also i have removed all other jQuery code from the rest of my code

i ll use it for a few days and then make a PR

**Comment by brianteeman** [comment]
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed. 

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
