### ISSUE TITLE
smart search no results error

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17753]
### Steps to reproduce the issue
Index your site with smart search and then search for a non existent word

### Expected result
No results

### Actual result
Error as below
`Warning: Invalid argument supplied for foreach() in C:\Apache24\htdocs\cms\components\com_finder\views\search\tmpl\default_results.php on line 57
`

### System information (as much as possible)
Staging as at time of post
php 7.1.1

**Comment by ghost** [comment]
Can't confirm. Searching for non-existing Word give "No Results Found".

### System information
3.8-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17753">issues.joomla.org/tracker/joomla-cms/17753</a>.</sub>

**Comment by Quy** [comment]
Duplicate #17731

**Comment by brianteeman** [comment]
Sorry I was on the wrong branch
