### ISSUE TITLE
Phpmailer does not send live and outlook

### ISSUE THREAD

**Issue by webmasterab** [joomla/joomla-cms#17761]
### Steps to reproduce the issue
See also the change log for the latest version 6.0.0
Https://github.com/PHPMailer/PHPMailer/blob/master/changelog.md

It is written

Because with the version of now in Joomla 5.2.25, it does not work

**Comment by mbabker** [comment]
Not quite sure what your issue is, but Joomla can't upgrade to PHPMailer 6 until Joomla 4 is released because of PHPMailer's raised minimum PHP version (they require 5.5.9 in the new version, 3.x requires 5.3.10).

**Comment by webmasterab** [comment]
The problem is that I do not receive info on a live address via joomla.
Have component that uses joomla phpmailer and now the formlieren do not come in via mail

**Comment by webmasterab** [comment]
Have tested on different sites
Live and hotmail addresses tested with the general settings test with phpmailer

If I use my telfort address, it will come in immediately

How can I fix it?

**Comment by brianteeman** [comment]
I doubt this is an issue with phpmailer but you can always change your site to use either sendmail or smtp in the global configuration

**Comment by webmasterab** [comment]
On another forum I received this answer.
Think that's something in here.
It seems that you tend to be Outlook's security.
Now put the stie on smtp and all mail is now sent neatly


I manage a Joomla site with a ticketing component (ticketing is managing and processing notifications). In that ticketing component, employees of organizations with their organization make email addresses through various web forms. That worked fine until early last year. For organizations that worked with Office365, the ticketing system notifications came on. This was due to additional security in Office365. This additional security means that an email address that sends mail outside of Office365's domain (in my Joomla environment) is no longer allowed automatically, but must be authorized for this purpose in the organization's DNS environment. This authorization is by placing a so-called SPF record in the DNS of the organization in question.

Read more about SPF records here: https://www.internedservices.nl/faq/spf-records-waarom-en-wat-is-het

At Office365, at least, I recognize this problem. @live is also a Microsoft component so it will also run through Office365. The phpmailer will not lie. The solution thus lies in placing a spf record in the DNS of the organization where the mail address belongs.

**Comment by brianteeman** [comment]
The spf record is nothing to do with Joomla and we can have no control over it. Upgrading phpmailer should make no difference. Closing as not a Joomla issue
