### ISSUE TITLE
Breakage of menu assignment list.

### ISSUE THREAD

**Issue by teologlomakin** [joomla/joomla-cms#17768]
Hello, friends! The problem with module menu assignments has appeared. I use the latest versionof Joomla. Please, see the photo.
![screen shot 2017-08-30 at 07 25 11](https://issues.joomla.org/uploads/1/00daf075adef44bd1add394fa56cba61.png)
Help please!

**Comment by brianteeman** [comment]
Please use the forum for support
https://forum.joomla.org
