### ISSUE TITLE
Website issues and not able to Sign in on email

### ISSUE THREAD

**Issue by ClareHF** [joomla/joomla-cms#17767]
### Steps to reproduce the issue
Music Fun for Everyone website is showing coding rather than the web information.
 
Email password forgotten clare@musicfunforeveryone.com.au

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/) as written on [Websites-Repository](https://github.com/joomla/joomla-websites). This repository concerns Joomla coding.
