### ISSUE TITLE
[4.0]Calendar Today: Items wrongly set to pending

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#17770]
See https://github.com/joomla/joomla-cms/pull/17709#issuecomment-325915853

Items are set to pending.

![user_utc](https://user-images.githubusercontent.com/869724/29863170-21a0f8b4-8d6f-11e7-92f9-35d00e652934.gif)

**Comment by brianteeman** [comment]
this is the one i was thinking of #14860

**Comment by infograf768** [comment]
https://github.com/joomla/joomla-cms/issues/14860 is unrelated to this bug. 
It deals with the tip set or not to user tz. 
It does not point to this important issue which is that the item should not be set to pending when using Today after clearing the field, even if the time is in my example changed to local PC time instead of UTC.

**Comment by brianteeman** [comment]
is this a change in behaviour? if so when did this change happen?

**Comment by infograf768** [comment]
TBH, I don't know.

**Comment by brianteeman** [comment]
thats the key. if it has always been this way then i would say its not a problem. if it has not then we need to find out what made the change instead of writing new code to patch over with a bandaid

**Comment by infograf768** [comment]
Whether it is new or not (Which would mean no one noticed it until now, rather weird...), it is a real problem and has to be solved. I will wait to see what happens with this article wrongly set to pending when the new time (2017-08-30 10:31:10) = UTC.

**Comment by brianteeman** [comment]
You are missing my point. If it is a new problem then we must look to see where and what caused this problem to appear BEFORE trying to create a fix. Who knows what other issues were created by that code. We have to stop writing code to fix things without looking to see what broke them in the first place. Thats how you end up with spaghetti code that makes no sense and creates problems in the long run.

If it has always been this way then after x years with no reports I would say it is not a problem

**Comment by alikon** [comment]
Can someone do tests on previous joomla versions please?

**Comment by infograf768** [comment]
@dgt41 
I have the feeling this is due to the new calendar. Can you check?

Will test on the last 3.6.x

**Comment by infograf768** [comment]
Same issue in 3.6.5. Can't believe this. The bug has been there for ages... The calendar always picks the local time when choosing today. It does not take into account the global config setting at all.

**Comment by brianteeman** [comment]
is it a bug then?

**Comment by infograf768** [comment]
If I set the calendar fields to use `filter="server_utc"` instead of `filter="user_utc"`
It solves the issue here.

**Comment by infograf768** [comment]
Yes, I think it is a bug.

**Comment by brianteeman** [comment]
filter=user_utc has been there since at least 2010

**Comment by dgrammatiko** [comment]
@infograf768 @brianteeman that was the reason I proposed that the calendar field should sent and receive from the front end only UTC datetime but that was a hard B/C break (?) as many people commented back then.
Anyways we should definitely do that for J4, in the mean time I don't think that this is easily patchable (by the way is server side code not js, check the data in the controller)

**Comment by infograf768** [comment]
Just tested on a 2.5.28 and it does works fine. The time displayed corresponds to the user_utc and the item is not set as pending.

**Comment by dgrammatiko** [comment]
@infograf768 i think 3.x has some extra code for the user_utc compared to 2.x. 
I think it's these lines: https://github.com/joomla/joomla-cms/blob/a444c1474ee16e2443b7d5cc19be772e4af72ada/libraries/joomla/form/fields/calendar.php#L247-L248

We always read the input as UTC and convert it to server or user but the user submitted the date with their local timezone (most of the times the browser will have the timezone to the area that the user is living). There is the inconsistency...

**Comment by dgrammatiko** [comment]
@infograf768 this should run only when the code is coming from the db, for the data that comes from a form input we need to convert it to UTC. That will fix the problem

**Comment by infograf768** [comment]
@dgt41 
patch welcome as thsi is very ennoying.
I guess that code has been tested in winter when GB is pure UTC for local users too :smiley:

**Comment by dgrammatiko** [comment]
@infograf768 unfortunately I have no clue how to distinguish if the value comes from the form or the db at that point of execution, any ideas are welcome

**Comment by infograf768** [comment]
tested a pre-PR by @dgt41  which solves the issue here.

**Comment by ghost** [comment]
closed as having Pull Request #17823 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17770">issues.joomla.org/tracker/joomla-cms/17770</a>.</sub>

**Comment by mbabker** [comment]
Re-opened.  PR had side effects and was reverted.

**Comment by brianteeman** [comment]
2 years later and I guess either this has been fixed or no one sees it as a bug worth fixing

**Comment by dgrammatiko** [comment]
@brianteeman it will worth the effort if someone could implement [edit] for J4 [/edit] my suggestion in my first comment:
**that was the reason I proposed that the calendar field should sent and receive from the front end only UTC datetime**

**Comment by brianteeman** [comment]
As we are now in rc and code freeze I am assuming that this is not going to be addressed. 

There is no point in keeping issues open if they are not accepted
