### ISSUE TITLE
[4.0] Revert #10011 (if merged)

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#17778]
This PR https://github.com/joomla/joomla-cms/pull/10011 introduces an `item-featured` class which doesn't actually get used in core.

Absolutely no point in adding a class to the DOM just **_incase_** someone applies some CSS to it. They can create a template override.

**Comment by brianteeman** [comment]
it is really silly to merge something in j3 only to remove it in j4

if you feel so strongly about this (my opinion is on that thread) then you should (continue to) express it there

**Comment by Bakual** [comment]
I'm confused, since @C-Lodder seem to have supported it in https://github.com/joomla/joomla-cms/pull/10011#issuecomment-313884113 and now wants to revert it before it even got merged. That just doesn't make sense to me.

**Comment by C-Lodder** [comment]
Bakual,  didnt even remember doing that so probably wasnt in the 'right frame of mind'.

Will close this and post on there then
