### ISSUE TITLE
Files to delete due to namespacing and tinymce file move

### ISSUE THREAD

**Issue by jsubri** [joomla/joomla-cms#17775]
### Steps to reproduce the issue
Upgrade from 3.7.5 to 3.8 Beta4 and compare the file directories versus a full install

### Expected result
no files left over in the updated site.

### Actual result
Undeleted files:
'/libraries/joomla/http/factory.php',
'/libraries/joomla/http/http.php',
'/libraries/joomla/http/response.php',
'/libraries/joomla/http/transport.php',
'/libraries/joomla/http/transport/cacert.pem',
'/libraries/joomla/http/transport/curl.php',
'/libraries/joomla/http/transport/socket.php',
'/libraries/joomla/http/transport/stream.php',
'/libraries/joomla/http/wrapper/factory.php',

Undeleted  directories:
'/libraries/joomla/http/transport',
'/libraries/joomla/http/wrapper',
'/libraries/joomla/http',
'/libraries/legacy/table/menu',
'/media/editors/tinymce/plugins/jdragdrop',

### Additional comments
3 PR with file move: PR-17441 , PR-16306, PR-15057

**Comment by mbabker** [comment]
A PR's welcome to add those to the file.  Clearly it's not easy for one person to try and maintain that list on their own.
