### ISSUE TITLE
[4.0] complete fof removal

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17781]
The docblock here needs updating/rewriting/removing not sure which as FOF is no longer being used for this and so the docblock makes no sense

https://github.com/joomla/joomla-cms/blob/c904ec358718e0a94379b791c80f43151c87bf4c/administrator/components/com_postinstall/Model/Messages.php#L298

**Comment by ghost** [comment]
@mbabker should this be added to [Projects](https://github.com/joomla/joomla-cms/projects)?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17781">issues.joomla.org/tracker/joomla-cms/17781</a>.</sub>
