### ISSUE TITLE
no more access to my website (front-end & backend)

### ISSUE THREAD

**Issue by immacolata78** [joomla/joomla-cms#17787]
### Steps to reproduce the issue
Hi,
After trying to update to Akeeba Next Generation Installer Engine v.5.5.1, my website  is not working anymore and the page is redirected to http://www.mangialarossa.com/installation/index.php where I see the following error message :

"ANGIE – Akeeba Next Generation Installer Engine v.5.5.1

Oops! The installer is already in use.

ANGIE has detected that this installer is already in use by someone else. This could be either a different person or even you using a different browser, computer or a different domain name to access the site. Please remember that http://example.com, https://example.com and http://www.example.com are three different domains as far as the restoration script can tell. This could also happen if you are trying to restore on a live site and a visitor accidentally accessed the restoration page before you."

### Expected result

Can you please help me?
Thanks

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding.
