### ISSUE TITLE
[4.0] Reverting changes on JS Diff script

### ISSUE THREAD

**Issue by CiverBlack** [joomla/joomla-cms#17786]
This issue aims to revert some of the changes made by @C-Lodder in #14613 

I am proposing to reintroduce the "show/hide-HTML"-Button and the "All/Changed Values"-Button.

I agree that many of the information displayed in the 3.x version of this view aren´t often relevant to the users. But sometimes they are needed and some of them are crucial: If i use the "Read More"-Option on my site how i´m supposed to work with this view without the content os "Full text". I basically just see half my article. Also if i have a multilingual site i would like to see whats the "Language" of the article.

I don´t think anyone questions that people need to be able to see the HTML-Tags, but if i´m just concerned with the changes in the text of the article they tend to annoy, at least if you have many inline HTML-Tags like <code>\<strong\></code>. Also we have to consider the Not-Programmer-User, they maybe don´t know HTML and are not able to understand what they are seeing.

Greetings,
Civer

@iCampus

**Comment by brianteeman** [comment]
I have to agree with you - if i compare the two then for me at least the version compare in j3 is much easier to use

**Comment by C-Lodder** [comment]
Sounds fair enough.

Would you mind submitting a PR?
This is the vendor package being used: https://github.com/kpdecker/jsdiff

**Comment by brianteeman** [comment]
if i remember correctly the reason for the change was because of the change in library?

**Comment by C-Lodder** [comment]
Can't remember. Easily fixable though

**Comment by dgrammatiko** [comment]
@CiverBlack can you take couple screenshots in j3 so we can visualise the changes you are referring here?

By the way there is no way to go back to the previous script as there are quite some maintainability problems with that (no uncompressed source code, no GitHub repo, the script is simply dead)

**Comment by C-Lodder** [comment]
@dgt41 we don't need to go back to the old script.

Don't worry, I'll add this to my to-do list and get a PR submitted at some point

**Comment by brianteeman** [comment]
@C-Lodder maybe we can work on this at the sprint next weekend

**Comment by brianteeman** [comment]
@dgt41 they are like comparing apples and carrots

**Comment by C-Lodder** [comment]
sounds good to me Brian

**Comment by CiverBlack** [comment]
@dgt41 Here are the screenshots you wanted.

There are to many information displayed to get them all on my screen. So hear is a list of the entries which are displayed when show all is selected. 

Field, Id, Title, Alias, Intro Text, Full text, Status, Category, Created Date, Created By, Created by Alias, Modified Date, Modified By, Start Publishing, Finish Publishing, Image Options, URL Options, Options, Ordering, Meta Keywords, Meta Description, Access, Hits, Metadata, _Robots_, Featured, Language, External Reference

I also just realized that it would help to be able to adjust the width of the 3 Rows.

HTML-Tags included and only the changed values:
![bildschirmfoto 2017-08-31 um 14 04 33](https://user-images.githubusercontent.com/20768436/29922321-6c20b500-8e55-11e7-9d2e-53ed066f974d.png)

HTML-Tags not included and with all values:
![bildschirmfoto 2017-08-31 um 14 04 51](https://user-images.githubusercontent.com/20768436/29922323-6c4185f0-8e55-11e7-9102-828f7f0b2b1f.png)

**Comment by dgrammatiko** [comment]
@CiverBlack what is the output if you click on the Changed Values button?

**Comment by CiverBlack** [comment]
@dgt41 you get only these columns where there is a change between the two versions.

**Comment by C-Lodder** [comment]
It's basically just adding a button to hide/show the HTML tags within the changes.

**Comment by dgrammatiko** [comment]
> I am proposing to reintroduce the "show/hide-HTML"-Button and the "All/Changed Values"-Button.

@C-Lodder so that button exists?
Also didn't we discussed this and we decided to **only** show the things that **actually** have some changes or my memory fails me? If that was the case, honestly I'm against presenting the complete data, only the affected areas is the right approach from all point of views. As is this is very close to what GitHub has (or not?)

**Comment by C-Lodder** [comment]
If it were down to me, I'd leave it as it is, cause it displays all changes, be it HTML or not.

But then again, not everybody works with a HTML editor , so may get very confused as what what the HTML tags are being displayed for, or what they even are.

**Comment by brianteeman** [comment]
As we are now in rc and code freeze I am assuming that this is not going to be addressed. And if it isnt addressed in 4.0 then it cant be until 5.0

Please either close this or mark it re-evaluate for 5

There is no point in keeping issues open if they are not accepted

**Comment by dgrammatiko** [comment]
This should be closed @richard67

**Comment by richard67** [comment]
Closing for reasons stated above.
