### ISSUE TITLE
[4.0] Bootstrap classes used with Card component needs to be updated

### ISSUE THREAD

**Issue by Saurabh1** [joomla/joomla-cms#17791]
### Steps to reproduce the issue.
Use the card code from bootstrap component and put it in any article. https://getbootstrap.com/docs/4.0/components/card/
While testing creating Card using bootstrap 4 Card component code straight from bootstrap page 
https://getbootstrap.com/docs/4.0/components/card/ (v4.0.0-beta) , I have seen that code what we have in repository is may be old or we have different code in it. Issue with the class is, it doesn't take padding for the body of card. 

For example: In Login Module, Code shows class="card-block" but in latest version of bootstrap 4 it is used as class="card-body". So far only found with card-body class.( I will upload more as I find out or test) 

Does that mean we have an old code? or we have modified code of bootstrap classes? 

It would be nice to have the same all classes from bootstrap library and use it so developers/users can use the same code and change only text as they need. It will be easy for them. 

### Expected result
![card-image-1](https://user-images.githubusercontent.com/839557/29904873-7a237dfa-8de1-11e7-936d-0c1f95a70b77.jpg)

### Actual result
![card-image-2](https://user-images.githubusercontent.com/839557/29904874-7b1806c2-8de1-11e7-930e-4d17877ee619.jpg)

**Comment by SharkyKZ** [comment]
See #17496. You should update to current 4.0-dev.

**Comment by ghost** [comment]
@Saurabh1 if the Hint of @SharkyKZ solves your Issue, please close it, thanks.

**Comment by C-Lodder** [comment]
How exactly are you applying this card to the article?

**Comment by Saurabh1** [comment]
@SharkyKZ I think we should change code to the Beta than Dev becasue it is more stable. Not to go back in old days. 

@franz-wohlkoenig My point is to update with latest version of Bootstrap 4 which will be released as stable and stable version will have same classes as I am using right now since it is in Beta version. 

@C-Lodder I am just copying and pasting the code from Bootstrap page into Article. I have also tried to override couple of things but it has same issues due to class differences.

**Comment by brianteeman** [comment]
@Saurabh1 i dont understand your coments to @SharkyKZ or @franz-wohlkoenig 

If your branch is upto date then we are using the beta of bs4

**Comment by Saurabh1** [comment]
@brianteeman I will check with latest version again, I believe I have the version from a week ago.

**Comment by Saurabh1** [comment]
It seems to be solved with updated version. Thanks @brianteeman
