### ISSUE TITLE
the problem with big numbers

### ISSUE THREAD

**Issue by lawrakina** [joomla/joomla-cms#17792]
### Steps to reproduce the issue
the problem with big numbers
good day, installed a clean Joomla 3.7.0 updated to 3.7.5
added several categories of materials, said group of fields, added the fields themselves.
If you specify the value of a field "integer" = 100000000, I get the error
/public_html/libraries/joomla/form/fields/integer.php
 73                         for ($i = $first; $i <= $last; $i += $step)
 74                         {
 75                         //      $options[] = JHtml::_('select.option', $i);
 76                         }
### System information (as much as possible)
[31-Aug-2017 09:30:20 Europe/Moscow] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 72 bytes) in /home/l/lawrfeu1/main.lawrfeu1.beget.tech/public_html/libraries/cms/html/select.php on line 515

**Comment by SharkyKZ** [comment]
Integer field creates a select containing options based on min, max and step values. It's not the right field type to use if you intend to have a large number of valid values. Text field with integer filter or number field would be more fitting.

**Comment by lawrakina** [comment]
Thank you for the help!
Please forgive a silly question from my side.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17792">issues.joomla.org/tracker/joomla-cms/17792</a>.</sub>

**Comment by ghost** [comment]
@lawrakina if this Isuue is solved please close it, thanks.

**Comment by ggppdk** [comment]
The **text field with integer filter** is for this purpose just **it is lacking browser side validation** 

At minimum
`class="validate-numeric"`
can be added by the text field when **integer filter** is selected 

----

Or better add `class="validate-integer"` , this will requiring addin 1 more case at `validate.js`
```js
setHandler('integer', function(value, element) {
	var regex = /^[0-9]*$/;
 	return regex.test(value);
});
```

Also notice that above **element** is passed to the handler,
so tag attibutes like  `data-value-min="..."`  and `data-value-max="..."` could also be used ...

**Comment by ggppdk** [comment]
Also maybe the "Integer" name for the field is bad, maybe a name "Integer drop-down select" or something shorter

**Comment by lawrakina** [comment]
Thank you very much for the answers! I will try!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17792">issues.joomla.org/tracker/joomla-cms/17792</a>.</sub>

**Comment by ghost** [comment]
closed; Issue can always reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17792">issues.joomla.org/tracker/joomla-cms/17792</a>.</sub>
