### ISSUE TITLE
[4.0] Not able to save Article with MySQL

### ISSUE THREAD

**Issue by CiverBlack** [joomla/joomla-cms#17803]
### Steps to reproduce the issue

1. Install Joomla with a MySQL Database. Not MySQLi.

2. Create a new Article.

3. Try to save it.

### Expected result

You are able to save your Article

### Actual result

It throws an error and does not let you save.

@iCampus

**Comment by brianteeman** [comment]
Joomla 4 is >= php 7

http://php.net/manual/en/mysql.php

> Depending on the version of PHP, there are either two or three PHP APIs for accessing the MySQL database. PHP 5 users can choose between the deprecated mysql extension, mysqli, or PDO_MySQL. PHP 7 removes the mysql extension, leaving only the latter two options.

**Comment by mbabker** [comment]
Just a note, because of the Framework Database package structure, the `$dbtype` in the config will be "mysql" if using the MySQL PDO driver.  Unless a merge went bad, the option should still be labeled in the UI as "MySQL (PDO)" (or something like that).

**Comment by CiverBlack** [comment]
I meant MySQL (PDO). That is what is not working

**Comment by roland-d** [comment]
In the installation process it is shown as MySQL and not as MySQL (PDO)

Edit: Ok, I found out why that is in this case. The "calculated" language is English (United States). This language file has not been updated yet to show MySQL (PDO) for the mysql value.

**Comment by alikon** [comment]
experiencing the same issue with PDO,
can someone help me to  understand `onTableBeforeReorder` event stand for ???

**Comment by brianteeman** [comment]
Unable to replicate on current 4.0 branch when using pdo

I am closing this - it can always be reopened if required
