### ISSUE TITLE
[3.9] Rework text in JoomlaUpdate when PHP Version not supported

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#17819]
### Steps to reproduce the issue
Looking at the new interface in https://github.com/joomla/joomla-cms/pull/17742 we need to tweak the the text for when a PHP Version isn't supported because it looks more like the Joomla Update system failed to find an update than it's clear a dependency is missing (see @brianteeman 's comments at the end of that issue for more information)

**Comment by brianteeman** [comment]
Lol - i was creating the issue at the same time. Going to close this one as mine has more details

**Comment by wilsonge** [comment]
Oops :) Thanks!
