### ISSUE TITLE
[4.0] xtd plugin: Image popup box issue

### ISSUE THREAD

**Issue by Saurabh1** [joomla/joomla-cms#17810]
### Steps to reproduce the issue
Create a new Article or Module. Click on Image button to add and image.

### Expected result
Should be normal popup box with all options visible to select picture and add into article or module. 

### Actual result
Currently the popup box is all too small to select images and seems to be messed up
![image popup box](https://user-images.githubusercontent.com/839557/29946882-75879b0e-8e7d-11e7-9542-04cec9960f87.jpg)
. 

### System information (as much as possible)
Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT 
PHP version : 7.0.0

**Comment by brianteeman** [comment]
This is nothing to do with tinymce it is the image editors-xtd plugin

**Comment by Saurabh1** [comment]
Thanks, We can change the Subject line.  So how can we fix the issue? It is there anyways unless I am missing something again.

**Comment by ghost** [comment]
changed Title accordingly Comment of @brianteeman<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17810">issues.joomla.org/tracker/joomla-cms/17810</a>.</sub>

**Comment by Saurabh1** [comment]
Sounds good @franz-wohlkoenig

**Comment by C-Lodder** [comment]
This can be closed as it's no longer an issue on nightly.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17810">issues.joomla.org/tracker/joomla-cms/17810</a>.</sub>
