### ISSUE TITLE
[4.0] Select box need a max-width

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17817]
### Steps to reproduce the issue
Depending on the length of the items in the select box then the select box can break the layout of the page as shown below - shouldnt there be a max-width or something to ensure a consistent width. The dropdown already expands greater than the box

<img width="373" alt="screenshotr09-51-20" src="https://user-images.githubusercontent.com/1296369/29962499-575bdae0-8efb-11e7-8642-4f5d7e1e4214.png">
<img width="386" alt="screenshotr09-52-05" src="https://user-images.githubusercontent.com/1296369/29962500-575fedf6-8efb-11e7-823d-cbada878a138.png">
<img width="412" alt="screenshotr09-52-12" src="https://user-images.githubusercontent.com/1296369/29962501-576241e6-8efb-11e7-983a-8864c5865eb2.png">

**Comment by C-Lodder** [comment]
It's overlapping because it **does** have a `max-width`.

If I remove the `max-width`, the selectbox will become as long as the longest option. Id rather just the dropdown expanded than the whole thing.

So this was intentional

**Comment by brianteeman** [comment]
If i change the max-width from 100% to 240px then it works as I expect

<img width="414" alt="screenshotr10-24-24" src="https://user-images.githubusercontent.com/1296369/29963724-cb1515f6-8eff-11e7-835b-fb87f3f5433e.png">

<img width="378" alt="screenshotr10-25-08" src="https://user-images.githubusercontent.com/1296369/29963744-dbfaeb0c-8eff-11e7-95c6-7bc3cab59a7e.png">

**Comment by brianteeman** [comment]
@C-Lodder your description of the intended behaviour seems correct

>  I'd rather just the dropdown expanded than the whole thing.

The problem is that the max-width of 100% doesnt do that without also breaking the layout as I described.

Setting 
```
custom-select {
    max-width: 240px;
}
```
resolves that.

Or am I talking rubbish?

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/19229

**Comment by ghost** [comment]
closed as having Pull Request #19229
