### ISSUE TITLE
[4.0] Module Title issue on same position

### ISSUE THREAD

**Issue by Saurabh1** [joomla/joomla-cms#17814]
### Steps to reproduce the issue
Create few custom module to position like top-a, bottom-a etc. 
Add some text to the modules, add more text in one of the module to see the issue.  Can see the longer the text you add, it adds more space in module header title.

### Expected result
It should be with the same spacing for all module header title.

### Actual result
![top a](https://user-images.githubusercontent.com/839557/29952379-61f364a2-8e9f-11e7-900c-2e7b47f7bc36.jpg)
![bottom a](https://user-images.githubusercontent.com/839557/29952451-dd570752-8e9f-11e7-9e27-05df8befe85f.jpg)

### System information (as much as possible)
Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT
PHP version : 7.0.0

**Comment by C-Lodder** [comment]
What browser?

Have you also ensured you have the most up to date code for J4?

**Comment by brianteeman** [comment]
I can confirm this on chrome and firefox for windows
I can not confirm this on edge or ie11

**Comment by ciar4n** [comment]
PR created.. #17818

**Comment by brianteeman** [comment]
Closed as we have a PR for testing

**Comment by Saurabh1** [comment]
Thanks guys!
