### ISSUE TITLE
[RFC] [4.0] Remove 'remember me' plugin

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#17826]
With modern browsers allowing you to do this client side and the fact that some modern browsers now allow you to sync all this data across different devices, do we still need a checkbox dedicated for this?

**Comment by Bakual** [comment]
You can't do the remember me client side. This does far more than just storing the user/pass in the browser. It is a safe "autologin" based on information stored in a cookie.

**Comment by mbabker** [comment]
Pretty much that.  There is a major difference in passwords being stored somewhere so login forms are autofilled and being transparently logged into a site based on a combination of data stored to the client and validated against something on the server.

**Comment by C-Lodder** [comment]
Fair enough then. Closing
