### ISSUE TITLE
[3.9] Pre-update checker messages

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17820]
### Steps to reproduce the issue
**This is for J3.9 only**
and relates to #17742 

Create the xml files as described in #17742 and force your server to fail the preinstall check. for example you could set the required php version to 7.3

The message you now get is
<img width="796" alt="screenshotr15-18-26" src="https://user-images.githubusercontent.com/1296369/29877092-8d4b7c16-8d96-11e7-81b5-939fb639a8ce.png">

To me this text suggests that I should either come back later and try again or download it manually and use the upload and update functionality

The text that i dont meet the minimum requirements is buried in the middle of text which is titled **We can't find a download URL**

**Comment by ghost** [comment]
closed as having Pull Request #17849<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17820">issues.joomla.org/tracker/joomla-cms/17820</a>.</sub>
