### ISSUE TITLE
Remember-Me functionality should be unset, when user changes password

### ISSUE THREAD

**Issue by schultz-it-solutions** [joomla/joomla-cms#17825]
### Steps to reproduce the issue
All frontend:
1) Login on one device with activated "remember-me" checkbox and close the browser again.
2) Login on another device and change your password here.
3) Go back to your first device and open the website again.

### Expected result
As the password is changed now, the "silent" login should not successfully proceed.

### Actual result
You are logged into the website on your first device (actually assuming the old password is still working), even though the password was changed since you first logged in.

### System information (as much as possible)
Joomla CMS all versions

### Additional comments
This is a security risk for the user: If someone (an ex boyfriend) can access a device where the user previously was logged in (with remember-me functionality activated), changing the users password cannot keep this person out of the users account.
(I am afraid this is not a hypthetical risk - www.alicerugglestrust.org )

I do have a patched "system-remember" plugin ready and I like to submit this to the core, but am un-knowledgeable with the "pull-request" procedure.

**Comment by schultz-it-solutions** [comment]
I could attach those changed files here if you like...

**Comment by brianteeman** [comment]
See https://docs.joomla.org/My_first_pull_request_to_Joomla!_on_Github and/or
https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by Bakual** [comment]
The remember-me doesn't use any password at all. That's why it will still work when you changed the password.

**Comment by mbabker** [comment]
The issue is if you reset your account credentials, it should invalidate that remember me cookie.  Just yesterday I reset my password on a website and my remember me authentication on all devices for that site was invalidated, I had to re-login (and authorize remember me again) for the new credentials.

**Comment by schultz-it-solutions** [comment]
I know, but if we delete the corresponding #__user_keys, these cookies remain useless.
that is what I did here:
https://github.com/joomla/joomla-cms/pull/17827/commits/9c09cc1a0aaf1129dc99983c81f93af438dd1359

**Comment by brianteeman** [comment]
closing here as we know have a pull request and should continue any discussion there.
