### ISSUE TITLE
com_fields / plugin_url for fields. Not really an issue but be nice to extend ability...

### ISSUE THREAD

**Issue by MKTGExperts** [joomla/joomla-cms#17828]
### Additional comments

So the plugin_url for fields supports CSS.  Cool, I am going to use this to make a directory of models on my eshop that are wearing my designs...  so to help them for helping me I want to give my customers all their social media links... but not every person their or here uses every single social media platform. I myself just got reddit...  so i put my css for the icon, put in the url and goto article and I see this long url beside the icon... this plugin/component needs another option "Use CSS for link" and then "use url for tool tip"  "show link"

**Comment by ghost** [comment]
can you please show Screenshots with and without your Feature Request?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17828">issues.joomla.org/tracker/joomla-cms/17828</a>.</sub>

**Comment by MKTGExperts** [comment]
This is how I have plugin_url configured
![screenshot 2017-09-09 00 44 41](https://user-images.githubusercontent.com/2774503/30238236-170fbf58-94f8-11e7-87ea-00e64f07937d.png)
This is how it currently looks by default ![screenshot 2017-09-09 00 43 43](https://user-images.githubusercontent.com/2774503/30238232-f996de34-94f7-11e7-9dc4-34d6842c84d0.png)

We need the option so that the css could become the link, and the url the could be used as a title, and the link itself. 

So you could then have this ![screenshot 2017-09-09 00 48 11](https://user-images.githubusercontent.com/2774503/30238262-9189e2c2-94f8-11e7-8854-f29690e99bed.png)

**Comment by coolcat-creations** [comment]
I created a customfield plugin for this and will publish it soon.

**Comment by brianteeman** [comment]
I dont see the real need for this in the core and it can easily be achieved with a custom field plugin. for example this one by @coolcat-creations https://github.com/coolcat-creations/plg_fields_iconlink
