### ISSUE TITLE
About performance of AdminModel saveOrder()

### ISSUE THREAD

**Issue by ggppdk** [joomla/joomla-cms#17833]
### Steps to reproduce the issue
1. Edit file: 
`libraries/src/MVC/Controller/AdminController.php`

2. Find method `saveOrderAjax()`
and comment out (so that we can use the DEBUG screen)
`\JFactory::getApplication()->close();`

3. Enable debug and visit URL:
`/administrator/index.php?option=com_categories&task=categories.saveOrderAjax`

(also same problem with menu items)
`/administrator/index.php?option=com_menus&task=items.saveOrderAjax`

### Expected result
1 SELECT query to the categories table
1 UPDATE query to the categories table

### Actual result

For N e.g. 300 categories in the table (assuming almost all of them belong to the com_conent)
300 SELECTs on the table
300 UPDATEs on the table

Code is here:
https://github.com/joomla/joomla-cms/blob/staging/libraries/src/MVC/Model/AdminModel.php#L1325-L1345

**Comment by brianteeman** [comment]
Sorry but as there has been no interest by anyone in moving forward with this feature request I am going to close it,
