### ISSUE TITLE
Plugin content pagebreak does not work for second page and next

### ISSUE THREAD

**Issue by csthomas** [joomla/joomla-cms#17830]
### Steps to reproduce the issue
Install staging Joomla and create an article with 'readmore' and several pages.
Go to the article:
* page 1 - OK
* page 2 - error 404

### Expected result
All pages should be available

### Actual result
Only first one and show all is visible. Other pages show 404

### System information (as much as possible)
Staging Joomla

### Additional comments
A reason of issue is merged PR #17175.
Plugin pagebreak is called twice.

**Comment by ghost** [comment]
looks similar to #17305

**Comment by sandewt** [comment]
I can 'only' reproduce this issue in combination with a **Read More** in an article.
One 'Page Break' is sufficient to show a 404 page. 


![issue17830](https://user-images.githubusercontent.com/9271775/29993274-91610dac-8fb2-11e7-90e7-e26a1d0d83f4.png)

**Comment by sandewt** [comment]
See file: ..\joomla-cms-staging\plugins\content\pagebreak\pagebreak.php

The code (line 76 etc.) is loading twice.
```
// Simple performance check to determine whether bot should process further.
if (StringHelper::strpos($row->text, 'class="system-pagebreak') === false)
{
	if ($page > 0)
	{
		throw new Exception(JText::_('JERROR_PAGE_NOT_FOUND'), 404);
	}
	        return true;
}
````
The first time `var_dump(StringHelper::strpos($row->text, 'class="system-pagebreak'))` let's see an int(1234) and the second time a bool(false). 
This generates the throw, an 404 error page, in line 81.

Testing without **Read More** shows the first and the second time an int(1234).  Stringhelper also loading twice. There is NOT generated an error page.

Why are loading twice?

**Comment by csthomas** [comment]
> I can 'only' reproduce this issue in combination with a Read More in an article.

Yes. I tested with 'Read More' too.
Ping to @laoneo

**Comment by niklasalbin** [comment]
tested reverting PR #17175. It resolves the issue.

**Comment by AlexRed** [comment]
I can confirm the problem in Joomla 3.8.0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17830">issues.joomla.org/tracker/joomla-cms/17830</a>.</sub>

**Comment by csthomas** [comment]
This issue should be fixed by https://github.com/joomla/joomla-cms/pull/18066, so I close it.
