### ISSUE TITLE
[4.0] Error displaying the user profile page when "Frontend User Parameters" is Hide

### ISSUE THREAD

**Issue by lufog** [joomla/joomla-cms#17843]
### Steps to reproduce the issue
In the settings of the user manager, disable the display of site settings for the user.

### Expected result
The user profile page is displayed normally.

### Actual result
If difficulties persist, please contact the System Administrator of this site and report the error below.
0 Argument 2 passed to JHtml::register() must be callable, array given, called in W:\domains\site.domain\components\com_users\tmpl\profile\default_custom.php on line 13

### System information (as much as possible)
Setting | Value
-- | --
PHP Built On | Windows NT DESKTOP-3288EOT 10.0 build 15063 (Windows 10) i586
Database Version | 5.7.19
Database Collation | utf8_general_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.1.7
Web Server | Apache
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by ghost** [comment]
Issue confirmed. 

It also happen if `Frontend User Parameters` is set on `Show`:
![bildschirmfoto 2017-09-03 um 13 03 36](https://user-images.githubusercontent.com/8235763/30002395-a55df26a-90a8-11e7-982a-663e708b6f61.jpg)
![bildschirmfoto 2017-09-03 um 13 04 32](https://user-images.githubusercontent.com/8235763/30002396-a5871622-90a8-11e7-8954-656a7e1bc4df.jpg)

**Comment by lufog** [comment]
@franz-wohlkoenig No, in your case it's a mistake in
   "plugins/system/languagefilter/languagefilter.php" in line 136
Replaсe: 
   $router->attachBuildRule(array($this, 'buildRule'), JRouter::PROCESS_DURING);
On: 
   $router->attachBuildRule(array($this, 'buildRule'), JRouter::PROCESS_BEFORE);

In your URL, the tag of the language, is in the wrong place,

**Comment by Quy** [comment]
@DebuggeR94 Cannot replicate. Please test with the latest alpha.

**Comment by brianteeman** [comment]
i can confirm this exact bug. Set Frontend User Parameters to hide in the com_user options
then on the front end login and try to edit your profile and you get the error

**Comment by Quy** [comment]
I changed the setting here `Global Configuration > Users > Frontend User Parameters`. Logged in on the front end, and edited/saved my profile successfully with show/hide of this setting.

**Comment by brianteeman** [comment]
![profile](https://user-images.githubusercontent.com/1296369/40944601-4b49970c-684d-11e8-8e45-1d8fed732a29.gif)

**Comment by Quy** [comment]
Confirmed. I had the menu item to edit user profile vs. user profile. Thanks!

**Comment by SharkyKZ** [comment]
Can't reproduce this on current nightly. The file has been modified and the failing code is no longer there.

**Comment by ghost** [comment]
closed for Reason stated above. Issue can always reopened.

**Comment by brianteeman** [comment]
i can confirm that this is no longer a valid bug and can be closed
