### ISSUE TITLE
[com_fields] possible new field group feature

### ISSUE THREAD

**Issue by stutteringp0et** [joomla/joomla-cms#17850]
I'm capable of doing this, but I wanted to get the general opinion before I issue a pull request.  

I was happily surprised that the new com_fields component field view offered the same custom param import feature as com_categories.  

For those unaware, a component using com_categories can add additional parameters to their created categories by including a correctly formatted models/forms/category.xml in their component.  As I discovered, the same can be done with com_fields.field by adding models/forms/fields/fields.xml

I was sad to discover that field groups cannot be manipulated in such a way, and I wonder why that is?  I'd very much like to add that functionality, because an extension I'm working on would greatly benefit.

Is there a reason not to do this?

**Comment by brianteeman** [comment]
Is #17769  Related to this?

**Comment by Bakual** [comment]
@brianteeman No, that one is different.

@stutteringp0et In com_fields, the field groups basically are a fieldset /tab in the form. They are not really comparable to a category. Why would you want to add parameters for a field group (fieldset / tab)?

**Comment by stutteringp0et** [comment]
I don't see how it's different from a category...

The goal is to have an admin configuration capability to display the field groups differently based on a group setting.

**Comment by Bakual** [comment]
> I don't see how it's different from a category...

Categories are different because they by design show additional information when the page is rendered. It's information may be shown above the article list (eg an image, description and the like). There are menuitems which work based on categories.
Fieldgroups are only to group the fields together. In a form the fieldgroup appears as an own tab, that's it. When displaying, you will not see a difference without an override at all. Once you have an override, you can already do anything based on the group id or the note field or whatever.

What field would you want to add to the group?

**Comment by stutteringp0et** [comment]
I'm aware of what they're for and how they're used, thank you.  I feel like you're trolling me.....  Fields grouped together is quite similar to articles in the same category.  One field can't be in more than one group just like one article can't be in more than one category.  Field groups are associated with different components just like categories can be associated with different components. Sure, field groups can't be nested - but that isn't what I'm trying to do.  It isn't a stretch to recognize that field groups are like categories.

Imagine a world where you could define a display style on a per field group basis.  Imagine a different world it the same galaxy, where you could show and hide field groups based on a group setting that defined a showon value from a field in a different group.  Imagine a world at the subatomic level, coexisting within our own world in a cave somewhere near Borneo, where an admin could define groups that were accessible only to the user that owned the item being edited....

**Comment by laoneo** [comment]
Do you want that #17317?

**Comment by stutteringp0et** [comment]
@laoneo Yup!  That's exactly what I was asking.  Looks like someone is already on it!  Thanks!  I'll close this.

**Comment by laoneo** [comment]
@stutteringp0et can you please test #17317? Thanks.
