### ISSUE TITLE
AdminMultilanguage option JSON

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#17858]
In the #__extensions table check the content of the params field for the com_modules extension

You will see that the content is something like

`{"redirect_edit":"site","adminlangfilter":1}`

Looking at the content of other fields there are missing quotes and it should look like

`{"redirect_edit":"site","adminlangfilter":"1"}`

Not sure though - please advise

**Comment by infograf768** [comment]
This is due to the `filter="integer"` in the field
```
		<field
			name="adminlangfilter"
			type="radio"
			label="COM_MODULES_ADMIN_LANG_FILTER_LABEL"
			description="COM_MODULES_ADMIN_LANG_FILTER_DESC"
			class="btn-group btn-group-yesno"
			default="0"
			filter="integer"
			>
			<option value="1">JYES</option>
			<option value="0">JNO</option>
		</field>
```

It is indeed not necessary here but no undesired consequences as the param works whether the filter is set or not.

**Comment by brianteeman** [comment]
OK - thanks for confirming - it looked odd so I thought I should check

**Comment by SharkyKZ** [comment]
Integers shouldn't be wrapped in quotes in JSON. It would be a good practice to add integer filter on all fields like this.

**Comment by infograf768** [comment]
@SharkyKZ 
Would be a good new PR as we have multiple occurences of this in core.
