### ISSUE TITLE
[4.0] 0 Failed to start session in Joomla! installer

### ISSUE THREAD

**Issue by kasvith** [joomla/joomla-cms#17865]
### Steps to reproduce the issue
- Clone from https://github.com/joomla/joomla-cms.git
- Switch to 4.0-Dev branch
- Pull to get latest updates
- Open browser
- Go to Joomla Installer

![image](https://user-images.githubusercontent.com/13379595/30028637-782e3f42-91a3-11e7-89dd-61ff2b052d00.png)

I ve used chown to change ownership of the joomla folder before installation.

### Expected result
- Working joomla installer

### Actual result
- **0 Failed to start session** error

### System information (as much as possible)
- Kubuntu 16.04
- PHP 7.1
- LAMPP was used

**Comment by laoneo** [comment]
Is a duplicate of #14956.

**Comment by kasvith** [comment]
Thanks @laoneo
