### ISSUE TITLE
Joomla Custom Fields creating error in Front-End article editing (category select) field

### ISSUE THREAD

**Issue by GCLW** [joomla/joomla-cms#17867]
### Steps to reproduce the issue
A Front End user assigned to (Registered and Author ) Creating or Editing an Article in the front-end view and under the "Publishing" tab when changing the Category in the drop-down menu (other categories are displayed) you can select a different category.

### Expected result
You can change the category of the article while in the front end editor.

### Actual result
When you click on the drop down menu and attempt to select a different category the screen flashes white briefly with the joomla logo in the center, and then displays an page that displays just categories... the URL changes "create-new-article?view=categories"

### System information (as much as possible)
Joomla 3.7.5
Database Version: 5.5.5-10.0.27-MariaDB-0ubuntu0.16.04.1
PHP: 7.0.8-0ubuntu0.16.04.3

### Additional comments
If I remove all custom fields, this error does not happen.
If I add a single custom field while keeping ALL parameter settings default the error happens.
If I change the user from Author to Publisher the error does not happen.

This only happens when I try and use custom fields while not a publisher.
I have this marked as urgent due to the fact I have users that would need to create articles in 3 categories.

**Comment by ghost** [comment]
Changed Priority according to the characteristics in [Bug Tracking Process](https://docs.joomla.org/Bug_Tracking_Process#Issue_Priorities)

**Comment by GCLW** [comment]
Ran a similar test on an older version of Joomla 3.7.0 and the error did not happen. I ran the update to 3.7.5 and now the error happens. So this bug started sometime after 3.7.0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17867">issues.joomla.org/tracker/joomla-cms/17867</a>.</sub>

**Comment by GCLW** [comment]
The error happens with 3.7.5, 3.7.4
I tested it on 3.7.0 and 3.7.3 and those are working.
The bug appears to start with 3.7.4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17867">issues.joomla.org/tracker/joomla-cms/17867</a>.</sub>

**Comment by GCLW** [comment]
Guessing this broke it... https://github.com/joomla/joomla-cms/pull/16949

**Comment by wojsmol** [comment]
@laoneo Please check this.

**Comment by dgrammatiko** [comment]
Just add a `JHtml::_('behaviour.core');` and `JHtml::_('formbehaviour.chosen');` before the inline script in https://github.com/joomla/joomla-cms/pull/16949 and that should solve the error

**Comment by laoneo** [comment]
Please test #17872 which should fix the issue. Hurry up that we can get it into 3.8 :smirk:

**Comment by ghost** [comment]
closed as having Pull Request #17872<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17867">issues.joomla.org/tracker/joomla-cms/17867</a>.</sub>

**Comment by GCLW** [comment]
I understand this is closed and I appreciate all the effort to get this fixed. But does anyone have a fix that I could apply myself, just so I can keep the category select function working on the front end.

**Comment by laoneo** [comment]
Yes, https://github.com/joomla/joomla-cms/pull/17872 should fix it, that's why we closed it, because we have a pr available. But it needs some tests to get into 3.8.

**Comment by GCLW** [comment]
Ok thanks, that fix looks like it is for 3.8 not 3.7.5

**Comment by ghost** [comment]
@GCLW you are correct, PR is for 3.8 as @laoneo wrote.

**Comment by wojsmol** [comment]
@GCLW Please test https://github.com/joomla/joomla-cms/pull/17872 on local dev environment. 3.8.0 is next stable version - https://developer.joomla.org/roadmap.html#38

**Comment by GCLW** [comment]
Installed 3.8.0-beta4 locally with sample data.
Replaced the two files that cover the fix.
Setup a user that is Registered and an Author.
Created a custom field under content; just keeping default params
logged into the front end of the website, clicked on the "Create an Article" menu item.
Clicked on the Publishing tab.
Clicked on the Category dropdown and changed it from "Uncategorised" to "News", the overlay occurs and the page is then redirected from: index.php/create-an-article to: index.php/create-an-article?view=categories

Same issue as before.

**Comment by ghost** [comment]
@GCLW can you please write your Test-Results on #17872?
