### ISSUE TITLE
Custom Fields Type Idea: "List of Articles" (correlations between articles)

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-cms#17876]
Similar to how there are Custom Field Types for "List of Images", "User" or "User Groups", a very useful addition could be the ability to choose from a "List of Articles" as another Custom Field Type. 

This would allow to create correlations between Articles in different Categories, essentially making Categories act like different "Content Types/Database Tables". Let me make a generic example:

We have two Categories:
- **Companies**, containing several Companies as individual articles
- **People**, containing people as individual articles

If I wanted to create a Custom Field to list all the People that are part of the companies in the Companies Category, right now I would have to create a List Field and I would have to type in the values all the names of the People again, despite me already having the People articles in the People Category.

With a List of Articles Custom Field, you could simply create a List field that pulls values from Artcles contained in a certain category, in this case "People". (and also allows to select multiple values, not just one)

This would pratically allow to intertwine/correlate articles between each others.

In addition, when displaying the List of Articles in the frontend, those Articles would be hyperlinked, linking to the respective Article.

So, in the frontend, when showing the "List of Articles" Custom Field named "People" in a Company page, each person name (Article Title) would be hyperlinked to the respective Article from the People Category.

I don't have the technical skills to do a PR, but I thought of this idea so I wanted to bring it up in case you would like to implement it. What do you think?

**Comment by laoneo** [comment]
We have that in DPFields 2.0 already https://github.com/Digital-Peak/DPFields. Don't know if this should be part of the core or the job of extensions.

**Comment by AndySDH** [comment]
> We have that in DPFields 2.0 already https://github.com/Digital-Peak/DPFields. Don't know if this should be part of the core or the job of extensions.

Not sure. Your documentation is outdated though, and it says "built on top of Joomla's custom fields" but then it looks like it's a completely separate extension not using Joomla custom fields?

**Comment by AndySDH** [comment]
@laoneo May you please elaborate on how you "already have that" in DPFields 2.0 as your documentation is not updated?
Otherwise, any other comment on possible implementation in the Joomla core? I think it would be an incredibly useful feature.

**Comment by laoneo** [comment]
We have an article custom fields. You can choose an article from a list of articles which will then be displayed as a second article.

**Comment by AndySDH** [comment]
Ah, I see, although it's not exactly the same thing...

**Comment by AndySDH** [comment]
Any update on this if it's considered a good idea or if it will never happen?

**Comment by ghost** [comment]
@AndySDH i have set the Status on "Information Required"

**Comment by bindi266** [comment]
hello i see **So, in the frontend, when showing the "List of Articles" Custom Field named "People" in a Company page[.](https://xmovies8.biz "") each person name (Article Title) would be hyperlinked to the respective Article from the People Category.**<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17876">issues.joomla.org/tracker/joomla-cms/17876</a>.</sub>

**Comment by AndySDH** [comment]
The advantage here is that you would be able to actually intertwine with existing articles from another category. The idea is similar to having two separate mysql tables. Think of wanting to reproduce a situation where you have for example:

A Category called "CMS" that includes these articles and has profiles for each CMS.
- Joomla
- Wordpress
- Drupal
- ...dozens of CMS.......

A Category called "Extensions Developers" that includes these articles and has profiles for each developer.
- Regular Labs
- Joomla Dev1
- Joomla Dev2
- RandomWordpressDeveloper
- DrupalDev
- ...hundreds of developers....

Now, with a Custom Field of this new type "List of Articles" (we will give it a name of "extensions-developers"), assigned to articles included in the category "CMS", I would be able to select from articles included in a certain category, in this case from category "Extensions Developers". Essentially, I would then be able to go in the "Joomla" article inside CMS category, go the Custom Field "extensions-developers", and select "Regular Labs", "Joomla Dev1", "Joomla Dev2", picking right from the articles of the "Extensions Developers" category.

In the frontend, when visiting the article "Joomla" (CMS category) and display that Custom Field "extensions-developers", you would then see something like:
![](https://i.imgur.com/BC7vTDI.jpg)

As you can see, the Article Titles are hyperlinked and they link to the respective articles from the Extensions Developers category.

**Comment by brianteeman** [comment]
Nothing wrong with the idea but it needs someone to write it

**Comment by AndySDH** [comment]
I'll patiently (but anxiously) wait for it haha. Thanks for the reply, glad you think it's a good idea.

**Comment by AndySDH** [comment]
Stop the presses, @regularlabs is writing it and working on it 😄
