### ISSUE TITLE
Users: Groups: Advanced Permissions Report

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#17874]
### Steps to reproduce the issue

Go to `Users Groups`
Select `Select: - Super Users > Advanced Permissions Report`

### Expected result

Concerning settings in columns are set as _Allowed_.

### Actual result

Only the column Super User is set as _Allowed_. NOK
See image.

![screen shot 2017-09-05 at 08 51 27](https://issues.joomla.org/uploads/1/8b7c153e1de97ce19262fcfe053362d1.png)

### System information (as much as possible)

Standard Joomla! 3.7.5 installation.

### Additional comments
For comparison:
Go to `Users Groups`
Select: `- Manager > Advanced Permissions Report`
It is clear that columns are set as _Allowed_ or _Not Allowed_. OK
See image.

![screen shot 2017-09-05 at 08 51 12](https://issues.joomla.org/uploads/1/fbe3cd6eddd5451704fe5bde50711615.png)

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17874">issues.joomla.org/tracker/joomla-cms/17874</a>.</sub>

**Comment by Sieger66** [comment]
Go to System -> Global Configuration -> Permissions -> Super Users 
and you see why.

Only the "Super User"-Action is set to Allowed
All Other Actions is set to Inherited.
Inherited means that the permissions from the parent group will be used.
The parent group of the Super User is the Public
And in Public is all action set to Not Set and is Not Allowed (Default)

If you want set all Actions by Super User-Group to Allowed and you will see it at the Advanced Permissions Report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17874">issues.joomla.org/tracker/joomla-cms/17874</a>.</sub>

**Comment by ghost** [comment]
closed as expected Behaviour.

@Sieger66 Thanks for Hint.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17874">issues.joomla.org/tracker/joomla-cms/17874</a>.</sub>

**Comment by sandewt** [comment]
Thanks @Sieger66 for your explanation.
The Advanced Permissions Report is something confusing.

_I think it is clearer for people to name the parent group in the screen.
Then there is no more or less discussion about it !!!_<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17874">issues.joomla.org/tracker/joomla-cms/17874</a>.</sub>
