### ISSUE TITLE
Group changes via JUserHelper in an onUserAfterSave event sets custom fields to their default

### ISSUE THREAD

**Issue by stutteringp0et** [joomla/joomla-cms#17878]
### Steps to reproduce the issue

1. Create some custom user fields in Users>Fields
2. Within a user plugin, call JUserHelper::addUserToGroup($uid,$gid) inside of the onUserAfterSave method
3. Edit and save the user

### Expected result
Groups change, field values remain

### Actual result
groups change, field values are defaulted

### System information (as much as possible)
J3.7.5

### Additional comments
I created a CLI to test this and it works as expected.  This only seems to happen if I add or remove groups within a user onUserAfterSave event

My temporary solution is to not use JUserHelper to add or remove groups, instead I'm querying the table directly to make my changes.  I would rather not do this, but it keeps me moving forward:

```
	$db->setQuery('DELETE FROM #__user_usergroup_map WHERE user_id = '.$id.' AND group_id IN ('.implode(',',$removegroups).')');
	$db->execute();
	
	if(!in_array($addid,$user->groups)) {
	    $o = new stdClass();
	    $o->user_id = $id;
	    $o->group_id = $addid;
	    $db->insertObject('#__user_usergroup_map',$o);
	}
```

**Comment by Denitz** [comment]
Duplicate, see https://github.com/joomla/joomla-cms/issues/17801 and https://github.com/joomla/joomla-cms/pull/17837

**Comment by ghost** [comment]
closed as duplicate Report. Thanks for Hint @Denitz<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17878">issues.joomla.org/tracker/joomla-cms/17878</a>.</sub>

**Comment by stutteringp0et** [comment]
Thanks @Denitz, I'll keep an eye on 17878
