### ISSUE TITLE
Can we have better documentation for Text Filters in Custom Fields?

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-cms#17888]
The current documentation (https://docs.joomla.org/Help37:Components_Fields_Fields_Edit) doesn't exactly explain much...
> Use from Plugin: Use from the plugin.
    No: Not.
    Raw: Raw.
    Safe html: Safe html.
    Text: Text.
    Alpha Numeric: Alpha Numeric.
    Integer: Integer.
    Float: Float.
    Telephone: Telephone.

Can we have a better documentation on how each of this selections differ from the others?

**Comment by ghost** [comment]
can yo please open this Issue at [docs](https://github.com/joomla/joomla-websites/issues/new?title=%5Bjdocs%5D%20) and closed this Issue here?

**Comment by AndySDH** [comment]
Sure, no problem.
