### ISSUE TITLE
Frontend module editing opens in default template, should be menu item template

### ISSUE THREAD

**Issue by Rakeshmvd** [joomla/joomla-cms#17884]
### Steps to reproduce the issue

1. Create a menu item with Template Style other then default, select Protostar

2. Add module to position on the new menu item

3. Give frontend access and edit access using the permissions tab to registered user of module

4. Login frontend as registered user

5. Go to module at menu item and click the edit module icon

6. Module opens to edit settings in default template. BUG 
Instead of opening with the Template Style of that menu item.

### Expected result

Frontend editing of the module should open with Template Style selected by the menu item it is linked to. 

### Actual result

Frontend Module editing always uses default template, the module is not connected to the menu item ID.

### System information (as much as possible)

The module I intend to change the settings for, is linked to a position with menu item that has Protostar as the selected Template Style.
When clicking the edit icon/button to change the settings of that module (located in the Protostar template), the module opens in the default template and not the one linked to that menu item.  :eek: 

Really do think frontend editing modules should use the itemID of the menu item it is linked to.
Or it should use the menu item (Template Style) from a menu item that uses 'Site Configuration Options'.

### Additional comments

If a module is not connected to a menu item you wish to edit, it should then use the Template Style with a menu item that is linked to 'Site Configuration Options'. As an extra option for not using the default template style.

**Comment by ghost** [comment]
on which Joomla-Version you get the Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17884">issues.joomla.org/tracker/joomla-cms/17884</a>.</sub>

**Comment by brianteeman** [comment]
i can confirm this in staging
the problem looks to be that there is no itemid

**Comment by ghost** [comment]
closed as having Pull Request #17884<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17884">issues.joomla.org/tracker/joomla-cms/17884</a>.</sub>
