### ISSUE TITLE
Undefined variable: http_response_header

### ISSUE THREAD

**Issue by BarendGoussard** [joomla/joomla-cms#17886]
Hi. I have 2 websites, 100% identical, except for configuration.php file, and of course  the physical server.
On original site, my Joomla extension module RSS Marquee (Gopiplus) works 100%, but not on my new site.
Original Site: cybersec.group - RSS works Fine
New Site: cybersec.co.nz - RSS does not get feed

### Expected result
Feed RSS normaly

### Actual result
Undefined variable: http_response_header in home/user/path/modules/mod_rss_marquee/helper.php on line 32

### System information (as much as possible)
Joomla 3.7.5
RSS Marquee 3.6
Server PHP version 4.6.6

### Additional comments
1. Ther expected RSS feed is located underneath Image Slider.
CODE FOR DOCUMENT POINTED OUT IN ERROR= PHP

`<?php
/**
 * RSS Marquee
 *
 * @package 	RSS Marquee
 * @subpackage 	RSS Marquee
 * @version   	3.6
 * @author    	Gopi Ramasamy
 * @copyright 	Copyright (C) 2010 - 2016 www.gopiplus.com, LLC
 * @license   	http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 *
 * http://www.gopiplus.com/extensions/2012/03/scrolling-rss-marquee-joomla-module/
 */

// No direct access
defined('_JEXEC') or die;

class modMarquee
{	
	public static function getMarquee($args)
	{
		$rss = $args["marquee_rss"];
		$items	= array();
		$j = 0;
		$MarqueeTitle = "";
		$MarqueeLink = "";
		
		if($rss <> "")
		{
			$xml = "";
			$content = @file_get_contents($rss);
			if (strpos($http_response_header[0], "200")) 
			{
				$f = fopen( $rss, 'r' );
				while( $data = fread( $f, 4096 ) ) { $xml .= $data; }
				fclose( $f );
				preg_match_all( "/\<item\>(.*?)\<\/item\>/s", $xml, $itemblocks );
				
				if ( ! empty($itemblocks) ) 
				{
					foreach( $itemblocks[1] as $block )
					{
						preg_match_all( "/\<title\>(.*?)\<\/title\>/",  $block, $title );
						preg_match_all( "/\<link\>(.*?)\<\/link\>/", $block, $link );
						
						$MarqueeTitle = $title[1][0];
						$MarqueeTitle = trim($MarqueeTitle);
						$MarqueeLink = $link[1][0];
						$MarqueeLink = trim($MarqueeLink);
				
						$items[$j] = new stdClass;
						$items[$j]->marque_title = $MarqueeTitle;
						$items[$j]->marque_link	= $MarqueeLink;
						$j = $j+1;
					}
				}
			}
			else
			{
				echo "Invalid or Broken rss link.";
			}
		}
		return $items;
    }	
}
?>`

**Comment by brianteeman** [comment]
As stated in the error message that you are seeing this is a bug in the module you are using. This module is not part of the core of joomla so please contact the author of the module directly or use the forum for support.

**Comment by BarendGoussard** [comment]
Good day.

I did attempt to use different readers, all resulting either in the same,
or similar issues. I will attempt to contact the manufacturers of the
component. Thanks for the response
