### ISSUE TITLE
Regroup image float and link target in global article options

### ISSUE THREAD

**Issue by forrestkirby** [joomla/joomla-cms#17892]
### Steps to reproduce the issue

- Go to [Articles: Options](/administrator/index.php?option=com_config&view=component&component=com_content "Articles: Options")
- Stay on the Articles tab
- Look for any of the options: URL Target Window, Intro Image Float or Full Text Image Float

### Expected result

The options are listed on the Articles tab

### Actual result

The options are listed on the Editing Layout tab

### System information (as much as possible)

Joomla 3.7.5
PHP 7.0.13
MySQLi 5.5.5-10.1.19-MariaDB

### Additional comments

There's a note on the Editing Layout tab explicitly stating that 'These options control the layout of the article editing page.' But image float and link target are rather layout options of articles and category pages than of the editing page. I simply think that these options would fit better in the first tab Articles.

**Comment by brianteeman** [comment]
It refers to the default settings for those options in the edit view
