### ISSUE TITLE
Article category list does not work on postgresql installed with sample testing data

### ISSUE THREAD

**Issue by csthomas** [joomla/joomla-cms#17901]
### Steps to reproduce the issue
Install Joomla staging on postgresql with sample data - testing
Go to frontpage and click on Article Category Blog or Article Category List
`/index.php/article-category-list`
`/index.php/article-category-blog`

### Expected result
Without errors

### Actual result
`500 ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list LINE 8: ORDER BY c.lft, a.title, a.created LIMIT 10 ^ `
or
`500 ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list LINE 8: ORDER BY c.lft, CASE WHEN a.publish_up = '1970-01-01 00:0... ^ `

### System information (as much as possible)
PostgreSQL 9.5.8

**Comment by ghost** [comment]
closed as having Pull Request #17902<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17901">issues.joomla.org/tracker/joomla-cms/17901</a>.</sub>
