### ISSUE TITLE
Non-Latin Alphabet Language's Sample Data Installation using mod_sampledata Fails

### ISSUE THREAD

**Issue by imanickam** [joomla/joomla-cms#17917]
**### Steps to reproduce the issue**

(a) Install Joomla 3.8.0 RC without Sample Data.

(b) Log into the site's back-end with username that has Super User privileges.

(c) Install a language pack that does not contain Latin alphabet (e.g., Tamil).

Note: For testing, the Tamil language pack for Joomla! 3.8.0 (ta-IN_joomla_lang_full_3.8.0v1.zip) is attached. 

[ta-IN_joomla_lang_full_3.8.0v1.zip](https://github.com/joomla/joomla-cms/files/1290082/ta-IN_joomla_lang_full_3.8.0v1.zip)

(d) Make Tamil (ta-IN) as the Default Backend (Administrator) language.

(e) Go to the Control Panel (தொகுதி => கட்டுப்பாட்டு பலகம்).  English equivalent: System => Control Panel.

![sample_data_failure_analysis_ta_backend](https://user-images.githubusercontent.com/4947580/30243635-dbda8b1e-95cb-11e7-95e9-a1c786c30797.jpg)

(f) Click on the link வலைப்பதிவு மாதிரித் தரவு (English equivalent: Blog Sample Data) in the module with the heading "SAMPLE DATA".

(g) Click OK on the pop-up screen to proceed with the installation of sample data.

(h) The installation of Sample Data will fail in Step 1.  A screen shot is attached.

![sample_data_failure_analysis_ta_error_install_step1](https://user-images.githubusercontent.com/4947580/30243642-1a53063c-95cc-11e7-988e-caba3579b3fe.jpg)

Translated Error message in English:
Step 1 Failed: Another category with the same parent category has the same alias (remember it may be a trashed item).

**### Expected result**

Successful installation of Sample Data that is in a language that does not contain a Latin alphabet.

![sample_data_failure_analysis_ta_install_success](https://user-images.githubusercontent.com/4947580/30243673-d0613228-95cc-11e7-95f4-2c93c5eb7e12.jpg)

Translated Informational messages in English:
Step 1: Articles done!
Step 2: Menus done!
Step 3: Modules done!

**### Actual result**

Please refer step (h) in the section ### Steps to reproduce the issue

**### System information (as much as possible)**

Joomla! 3.8.0 Release Candidate
Operating Environment: Not Applicable

**### Additional comments**

The analysis of the cause of the failure revealed the following:
- During the installation of Sample Data, first the categories are created
- In a language that contain non-Latin alphabet, when the first category (ie. வலைப்பதிவு - In English it would be Blog) is created, the alias created is having datetime stamp (e.g., 2017-09-09-20-45-57).
- When the second category (ie. உதவி - In English it would be Help) is created immediately following the first one, due to datetime stamp being used as the alias, the same alias name (e.g., 2017-09-09-20-45-57) is created.
- This is the cause of the failure.

How to rectify the situation:
Before even attempting to install the sample data, the Global Configuration option Unicode Aliases has to be set to Yes.  Once this setting is saved, the sample data installation is done successfully as shown in the section ### Expected Results.

What happens if the Global Configuration option Unicode Aliases is set to Yes, after the failure of the installation of Sample Data:
- The first category (ie. வலைப்பதிவு - In English it would be Blog) created would be created again with a different alias name
- This causes confusion in the modules "Older Posts" and "Mostly Read Posts" - The first category (ie. வலைப்பதிவு - In English it would be Blog) is being added/selected to these modules.  Whereas, as per the Sample Data in English, the category selected should be _Help_ - NOT _Blog_.

**Comment by infograf768** [comment]
I am working on this.

**Comment by infograf768** [comment]
Please test as fast as possible
https://github.com/joomla/joomla-cms/pull/17930

Closing as we have a PR
