### ISSUE TITLE
[J3.8RC1][BC] Joomla 3.8 RC1 + Yootheme Pro 1.9.5 = Resized images are not shown

### ISSUE THREAD

**Issue by ufuk-avcu** [joomla/joomla-cms#17919]
### Steps to reproduce the issue
Install Joomla 3.7.5
Install Yootheme Pro 1.9.6
Create with the Pagebuilder a Element, that contains images
Set the width and height for the images in the element

### Expected result
With Joomla 3.7.5 the images are shown

### Actual result
After an Upgrade to Joomla 3.8.0 RC1 the images not shown

### System information (as much as possible)
PHP 7.1
MySql 5.7
Before Upgrade: Joomla 3.7.5 Stable
Joomla 3.8 RC1

### Additional comments
Posted this also here: http://yootheme.com/support/question/114582

I tested Joomla 3.8 RC1 + Yootheme Pro 1.9.5 and if you set the width or height for images (not for Background images), the images are not shown anymore. If you use Joomla 3.7.5, there is no Problem.

The Problem is here:
<img src="/xxx/templates/yootheme/cache/auto-crash-18d5e554.png" srcset="//xxx/xxx/templates/yootheme/cache/auto-crash-18d5e554.png 320w, //xxx/xxx/templates/yootheme/cache/auto-crash-18d5e554.png 800w, //xxx/xxx/templates/yootheme/cache/auto-crash-18d5e554.png 400w" sizes="(min-width: 400px) 400px, 100vw" class="el-image" alt="">

This is ok: src="/xxx/templates/yootheme/cache/auto-crash-18d5e554.png"

But the srcset are broken: srcset="//xxx/xxx/templates/yootheme/cache/auto-crash-18d5e554.png

The //xxx doesn't belong there.

**Comment by C-Lodder** [comment]
They've replied:

> Yootheme will release a Joomla 3.8 compatible version after it has been released.

**Comment by ghost** [comment]
@ufuk-avcu cause Comment above can you please close Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17919">issues.joomla.org/tracker/joomla-cms/17919</a>.</sub>

**Comment by ufuk-avcu** [comment]
Hey. I just thought that this could be relevant from BC's point of view if the behavior changes in other extensions as well.

**Comment by mbabker** [comment]
If it can be isolated what specifically changed, we can look into the issue.  The report lacks any detail to be able to do anything.

Core doesn't do anything to generate `srcset` attributes by default.  https://github.com/joomla/joomla-cms/pull/15300 added support for processing `srcset` in the system SEF plugin in full, so maybe that change affected the Yootheme handling.  But that is IMO hardly a B/C break.

**Comment by oudmane** [comment]
@yootheme fixed this at pro v1.9.6

**Comment by ufuk-avcu** [comment]
@Oudmane tried now with Yootheme Pro 1.9.6 and it's not fixed.

**Comment by wronax** [comment]
I can confirm that this is a bug in the core joomla SEF plugin implementation. The same behaviour can be noticed in DJ-MediaTools gallery which also uses srcset attribute. The relative site path is added to image url no matter if image url contains it already what creates doubled relative path at the beginning of the image url.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17919">issues.joomla.org/tracker/joomla-cms/17919</a>.</sub>

**Comment by tonypartridge** [comment]
Can we close this? Pull is in: #17978

**Comment by ghost** [comment]
closed as having Pull Request #17978<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17919">issues.joomla.org/tracker/joomla-cms/17919</a>.</sub>
