### ISSUE TITLE
Template-Style parameter saved with layout parameter value that is from a other Template "template_name:layout_name" when saved to the database

### ISSUE THREAD

**Issue by Sieger66** [joomla/joomla-cms#17912]
All Joomla-Versions after Joomla! 3.8.0-rc1 

With PR #14802 in 3.8.0-rc1 come alternative layout parameter to com_content menutypes

### Steps to reproduce the issue

Protostar is Default-Template.

1. Create an alternate layout for articles in the Protostar-Template and name it menutypelayout.php - for example add into the headline of this alternate layout for articles "This is the Alternate Article Layout set in Menutype"

2. Setup a Testcategory with at least Testarticle 1 and Testarticle 2

3. Create a **Menuitem** with Testcategory Blog View, Select menutypelayout as alternate Layout in the Options tab (Choose a Layout). In the Details Tab is Template Style: protostar-Default 

4. Go to frontend and click to menuitem you have created at 3. 

5. Click in frontend on Testarticle 1 or Testarticle 2

Now the articles Testarticle 1 and 2 are shown correct in the assigned menutypelayout Layout in frontend(single-article-view).

But if you now change in the **Menuitem** to an other TemplateStyle(for example from Protostar to Beez)
Menuitem with Testcategory Blog View -> Details -> Template Style -> Beez3-Default
and save it with one click on the Save-Button.

Then works the menutypelayout furthermore with the Beez-Template
But you dont see this in the  **Menuitem** at:
Menuitem with Testcategory Blog View -> Options -> Choose a Layout

If you now save it again then is come the displayed result(view without the alternate Layout from the other Template). 
Save it twice after change to an other Template Style then you have always the correct "view".

Similar the same problem as in the PR #16755 and #8578
comes from the same bug.

### System information (as much as possible)

All Joomla-Versions after:
Joomla! 3.8.0-rc1
also for Example  3.8.3-dev

### Additional comments
shamsbd71 in PR#16755 30.Juni: 

I have tested as you asked and yes there is an issue but its not related to this xml params. its relate to
filed type componentlayout. 

mbabker in PR#16755 30.Juni: 

That layout parameter should save with a value like "template_name:layout_name" when saved to the database, and when used in the PHP API, that template name segment gets parsed by the view class to figure out that it needs to change the active template.

If that logic is broken, it will be a bug that already exists and would need to be addressed separately from adding this field.

**Comment by ghost** [comment]
@coolcat-creations can you please have a Look at this Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17912">issues.joomla.org/tracker/joomla-cms/17912</a>.</sub>

**Comment by coolcat-creations** [comment]
Yes as said by @mbabker before but that logic was broken before and is not related to the mentioned PR.

You have to change the template style, save, and then change your alternate layout. That's because the alternate layout field does not update automatically after changing the template style. 

I can't fix this update process as I don't know how. Maybe someone else knows?

**Comment by ghost** [comment]
@Sieger66 any Comment on Comment above?

**Comment by Sieger66** [comment]
Yes i know, what coolcat-creations write is correct.

But i am not a coder or programmer and i can not make a PR to correct the bug in the core-system.

Alternativly if nobody have time to fix the bug in the core : 
Make a better description or warning in the three helpsites(Help Screens):

https://help.joomla.org/proxy/index.php?option=com_help&keyref=Help38:Menus_Menu_Item_Article_Category_Blog

https://help.joomla.org/proxy/index.php?option=com_help&keyref=Help38:Menus_Menu_Item_Article_Category_List

https://help.joomla.org/proxy/index.php?option=com_help&keyref=Help38:Menus_Menu_Item_Article_Categories


For example this addition for the Details-Tab of the three helpsites(Help Screens):

If you use an alternative layout at the Options-Tab and
if you change the template style, save first the template style, and then change your alternate layout in the Options-Tab. 
That's because the alternate layout field does not update automatically allways correct after changing the template style.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17912">issues.joomla.org/tracker/joomla-cms/17912</a>.</sub>

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/27002.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17912">issues.joomla.org/tracker/joomla-cms/17912</a>.</sub>
