### ISSUE TITLE
[4.0] Custom Elements: `Element#attachShadow` was not patched.

### ISSUE THREAD

**Issue by roland-d** [joomla/joomla-cms#17914]
### Steps to reproduce the issue
1. Enable Inspector in FireFox
2. Go to the Control Panel
3. Check the Console tab
4. The notice is shown there

### Expected result
No warning

### Actual result
Warning is shown:
Custom Elements: `Element#attachShadow` was not patched.   webcomponents-ce.min.js:1:11851

### System information (as much as possible)
Joomla 4.0 Revision: ab82c24a3af3fc26120882bdba3a45d0b555c408
FireFox 55.0.3
MacOS 10.12.6 (Sierra)
PHP 7.1.6

This does not show up in Chrome

@dgt41 Something for you?

**Comment by dgrammatiko** [comment]
issue:
https://github.com/webcomponents/custom-elements/issues/106
PR:
https://github.com/webcomponents/custom-elements/pull/112

So I guess this will be handled by google at some point

**Comment by roland-d** [comment]
Clear, it is out of our control :)
