### ISSUE TITLE
[4.0] Long menu list items not displayed with left menu

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#17922]
### Steps to reproduce the issue
When you use some extension which has a lot of menu items, they are not displayed on the screen and there is no way how to access some menu items

![Menu Items](https://i.imgur.com/VGLSSAf.png)
### Expected result
All menu items should be displayed

### Actual result
All menu items are not displayed

### System information (as much as possible)
Joomla! 4, PHP 7.1

**Comment by ghost** [comment]
@mbabker should this be added to [Projects](https://github.com/joomla/joomla-cms/projects)?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17922">issues.joomla.org/tracker/joomla-cms/17922</a>.</sub>

**Comment by brianteeman** [comment]
I am going to close this for now. Lets wait until the new admin template being developed here https://github.com/joomla/40-backend-template has been merged
