### ISSUE TITLE
Inconsistent suffix while duplicating modules

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#17932]
### Steps to reproduce the issue
- In Module Manager select/check a module.
- Click button `Duplicate`.
- The title of copy has a postfix `(2)`.

- Now open a module by clicking the title link.
- Click button `Save as Copy`.
- The title of copy gets a postfix `(copy)`.

![11-09-_2017_12-17-29](https://user-images.githubusercontent.com/20780646/30270402-c29646da-96ec-11e7-8a7f-e0f67b286f5a.jpg)

### Expected result
Should be the same kind of suffix in both cases. I would prefer language independent numbering.

### System information (as much as possible)
Current staging (2017-09-11) and earlier J! versions

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17932">issues.joomla.org/tracker/joomla-cms/17932</a>.</sub>

**Comment by akritianand** [comment]
Can anybody tell me which function is executed when duplicate button is clicked? I cant find anything that is attached to it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17932">issues.joomla.org/tracker/joomla-cms/17932</a>.</sub>

**Comment by ReLater** [comment]
> which function is executed when duplicate button is clicked?

It starts here (modules controller called by button with `Joomla.submitbutton('modules.duplicate');`:

https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_modules/controllers/modules.php#L28

and then processed inside the module model

https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_modules/models/module.php#L385

**Comment by akritianand** [comment]
Thank you @ReLater <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17932">issues.joomla.org/tracker/joomla-cms/17932</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #17951<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17932">issues.joomla.org/tracker/joomla-cms/17932</a>.</sub>
