### ISSUE TITLE
Rating & Voting Labels Show without Choice Buttons when Plugin "Content - Vote" Disabled

### ISSUE THREAD

**Issue by imanickam** [joomla/joomla-cms#17937]
**### Steps to reproduce the issue**

(a) Install Joomla! 3.8.0 RC1 (or from joomla-cms staging)

(b) Log into the site's back-end

(c) Go to the screen "Articles" (Content => Articles)

(d) Click on the button Options (this should take you to the screen "Articles: Options"

(e) Go to the tab "List Layouts"

(f) Observe the labels "Show Votes in List" and "Show Ratings in List" are shown without the choice buttons Show/Hide.  Please see the screenshot below:

![articles_options_showing_votes_rating_without_buttons](https://user-images.githubusercontent.com/4947580/30287920-7ad93b60-9744-11e7-903d-10f6fa010cc3.jpg)

**### Expected result**

The labels should not be shown when the choices are not shown.  This happens when the Plugin "Content - Vote" is Disabled.

**### Actual result**

Refer Step (d) in ### Steps to reproduce the issue

**### System information (as much as possible)**

Joomla! 3.8.0 RC1
APACHE v2.4.25
PHP v7.0.20
MySQL v5.7.17

**### Additional comments**

This happens when the Plugin "Content - Vote" is Disabled.

When the Plugin "Content - Vote" is Enabled, the choice buttons Show/Hide displays properly.  Please see the screenshot below:

![articles_options_showing_votes_rating_with_buttons](https://user-images.githubusercontent.com/4947580/30288276-ceef36a4-9745-11e7-984c-e6a14d4f9715.jpg)

**Comment by ghost** [comment]
Known Issue, please look #14831
