### ISSUE TITLE
Component items missing in J3.7x

### ISSUE THREAD

**Issue by mikelawrey32** [joomla/joomla-cms#17934]
### Steps to reproduce the issue

After upgrading my site into 3.7, I have been seeing the components menu in J admin lacking items, specifically Redirect component.

### Expected result

All component items to remain.

### Actual result

Some are missing.

### System information (as much as possible)

J 3.7.4  
PHP 5.4.45
SQL 5.5.51-38.2

### Additional comments

Thinking it may be some discrepancy in database, name or ID of the components perhaps. Something to consider for future patches and upgrades

**Comment by csthomas** [comment]
I suggest you rebuild the menu and see if there are any items in the trash

**Comment by coolcat-creations** [comment]
@csthomas how to rebuild the default admin menu? Have some issues too (but not with core)

**Comment by wojsmol** [comment]
@coolcat-creations Check value of `menutype`  field in `#__menu` table if this problem start occuring after update to Joomla! 3.7.x.

**Comment by csthomas** [comment]
There is only one button in the menu list "Rebuild" which rebuild whole `#__menu` table.
If you can not find some menu items then first check trashed items. 
There may disappear some menu item from front end and go to backend. If yes then check menutype column in database (ex. by phpmyadmin). One menutype (I do not remeber now) is only reserved for backend.

**Comment by coolcat-creations** [comment]
@csthomas @wojsmol No after the Update just some Menuitems (from not core components) have missing language strings, are in uppercase and some new appeared that have nothing to do with appearing there. I speak about the core admin backend menu, nothing build by myself.

**Comment by wojsmol** [comment]
@coolcat-creations 

> and some new appeared that have nothing to do with appearing there 

Should these menu items be displayed in the frontend menu and appear in the backend in the Components menu?

**Comment by coolcat-creations** [comment]
@wojsmol 

![image](https://user-images.githubusercontent.com/828371/30522531-d5fe36bc-9bd1-11e7-8f0d-126d86f5b6f3.png)

The Screenshow shows "LANGUAGEFILESJS_MENU" 
I don't think it belongs to the frontend... And no idea where it comes from.

**Comment by infograf768** [comment]
Looks to me that screenshot does display apparently a language constant, and you can't translate a constant to English, just its value. And it is for sure NOT a joomla core lang constant.
Best way too know is to set debug lang to on and look at bottom of page which lang file is NOT loaded to figure which component is concerned

**Comment by wojsmol** [comment]
you can also execute this query in phpmyadmin
````SQL
SELECT `menutype`,`link`,`component_id`,`client_id` FROM `#__menu` WHERE `title` = 'language_constant'
````
replace `#__` with table prefix

**Comment by coolcat-creations** [comment]
Thanks that was indeed a component that appeared in the menu after update, but did not appear before the update - i uninstalled it and now it´s fixed - some more language strings in the menu are untranslated after the update, will try to reinstall the components to fix that issue.

**Comment by ghost** [comment]
As there are similar Threads this is closed but can always reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17934">issues.joomla.org/tracker/joomla-cms/17934</a>.</sub>
