### ISSUE TITLE
Language switcher module does not always use #__associations table

### ISSUE THREAD

**Issue by Giuse69** [joomla/joomla-cms#17948]
### Steps to reproduce the issue
1) A multilanguage site
2) Create a category CAT
3) Create a home menu item MENU_BLOG pointing to CAT as a Category Blog
4) Create another menu item MENU_LIST pointing to CAT as a Category List
5) Associate the menu items between the two languages: MENU_BLOG-lang1 with MENU_BLOG-lang2, MENU_LIST-lang1 to MENU_LIST-lang2.
6) Go to frontend, homepage with lang1 and look at the language switcher module for lang2

### Expected result
Language switcher module should point to MENU_BLOG_lang2 (home page in lang2) using the #__association table for that menu item

### Actual result
Language switcher module points to MENU_LIST-lang2 that is NOT associated with current menu item

### System information (as much as possible)
Joomla 3.7
any operating system

### Additional comments
Already opened one year and a half ago [Issue 9100](https://issues.joomla.org/tracker/joomla-cms/9100) and closed in may 2016 saying it could not be resolved in that version of Joomla. Reopening now to see if conditions have changed and since I think the solution might be using the association table.

**Comment by infograf768** [comment]
You mean a CAT-lang1 AND a CAT-lang2 ?

**Comment by infograf768** [comment]
It is not necessary to associate Home menu items. They are associated by default without entering anything in the _associations table.
Just associate the cat list menu items and all will be fine.

Otherwise the situation is still the same as in https://issues.joomla.org/tracker/joomla-cms/9100 i.e. the general issue with Joomla between cat list and cat blog. Nobody solved it and it is not only related to the associations table.

**Comment by Giuse69** [comment]
Hi infograf768, it's not the actual behavior I see: also not explicitly associating home menu items, the joomla lang switcher presents a wrong link to another language. 
I repeat the scenario: you are in the English homepage that is a blog category and if you click on the Italian flag in lang switcher module, you are **not** redirected to the Italian homepage but to the Italian menu item for category list.
With explicit associations between home menu items, it would be simple for the lang switcher just read from the association table present the correct link in the clickable flags (cat blog to cat blog, cat list to cat list), there is no ambiguity in the DB.

**Comment by Giuse69** [comment]
Seems to have been fixed in Joomla 3.9 and maybe also previously: can you confirm?

**Comment by brianteeman** [comment]
Nothing to do here - please close
