### ISSUE TITLE
parseController

### ISSUE THREAD

**Issue by JProof** [joomla/joomla-cms#17941]
I dont know where to ask(sry)
In J3 Series we have an method parseController
https://github.com/joomla/joomla-cms/blob/6e07ca6fadd8a5d1db3337cf0357d782646f5411/components/com_config/controller/helper.php

This feature is removed in j4? 
Has someone informations where i can find the discussion or stuff for this HelperMethod?

**Comment by roland-d** [comment]
@JProof You can ask questions on the Joomla! forum at https://forum.joomla.org 

Here is the pull request that removed this code: #16358

Looks like this has been completely removed. If you want to use this code you can include it in your own code.

**Comment by JProof** [comment]
@roland-d Thank you. Concept was good to take each controller in his own file
