### ISSUE TITLE
"category blog" menu item edit function is bad.

### ISSUE THREAD

**Issue by utopszkij** [joomla/joomla-cms#17947]
### Steps to reproduce the issue

Joomla! 3.7.5 Stable [ Amani ] 14-August-2017 12:09 GMT 
menu editor, there is no "category selection" button on the screen when editing an existing "category blog" menu item.

**Comment by utopszkij** [comment]
sceen:![screen shot 2017-09-12 at 18 15 44](https://issues.joomla.org/uploads/1/16ddc14e979f15f5dd4f4313d102e2e9.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17947">issues.joomla.org/tracker/joomla-cms/17947</a>.</sub>

**Comment by brianteeman** [comment]
That is the expected behaviour you have to press clear before you can select a different category

**Comment by ghost** [comment]
Please hit "Clear" and after select another Category.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17947">issues.joomla.org/tracker/joomla-cms/17947</a>.</sub>

**Comment by ghost** [comment]
closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17947">issues.joomla.org/tracker/joomla-cms/17947</a>.</sub>

**Comment by utopszkij** [comment]
Thanks. OK.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17947">issues.joomla.org/tracker/joomla-cms/17947</a>.</sub>
