### ISSUE TITLE
Component: Button publish not working

### ISSUE THREAD

**Issue by pdutie94** [joomla/joomla-cms#17957]
### Steps to reproduce the issue
i follow series "Developing an MVC Component" on https://docs.joomla.org/J3.x:Developing_an_MVC_Component, but when i click to publish button, i have an error "Fatal error: Call to undefined method JmsMessagesModelMessages::publish() in E:\xampp\htdocs\joomla37\libraries\legacy\controller\admin.php on line 210". Somebody help me. I using joomla 3.7.5. Thanks. 
Sorry for my bad English.

**Comment by brianteeman** [comment]
The best place to ask this question is https://groups.google.com/forum/#!forum/joomla-dev-general
