### ISSUE TITLE
Module Chrome does not work cross templates (but with the system template)

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#17953]
You can use the system chromes but not the chromes from other templates. If you select one it´s just ignored and no module container set at all.

This is a issue for me when doing a relaunch of an existing template and just roll it out on some sites. When the modules have the mod_chrome from the other chrome selected in their module parameters the view is broken.

### Steps to reproduce the issue
In the module Parameters:
- Select a module Chrome from the System - it works
- Select a module from another template then the current - no container is set around the items at all. It´s even not the "none" style.

### Expected result
The module chromes should work crosstemplate wise. 
Possible solutions:
1) Giving priority to the current template chrome and display it correctly (but thats not completely the right solution) OR
2) Displaying the chrome from the selected template

### System information (as much as possible)
Joomla 3.8 but the error exists longer - just took the time to figure out why the chrome breaks.

**Comment by brianteeman** [comment]
I dont follow you here. I wouldnt expect the module chrome (or an alternative component layout) from template 1 to work with template 2

**Comment by coolcat-creations** [comment]
Ok imagine you have a template that has a module chrome named abcdef. You duplicate the template and it has the same module chrome. Some modules have chrome abcdef assigned in their parameters. It's the same in the old and the new template. But it stops working at this point and is broken. However if you select a system chrome from the list it does not stop working.

**Comment by brianteeman** [comment]
Joomla stores the name of the template with the name of the chrome in the db eg Beez3-beezTabs That is why it stops working - i kind of expect that to be the case. If it wasnt what would happen when you have completed the work on the new template and delete the old one - all your chromes are broken ;)

System chromes are by there very nature system wide so if selected they will always work independent of the template selected

**Comment by coolcat-creations** [comment]
No, actually the assignment to the chrome would be lost then in case of a template migration i would need to select the chromes everywhere. But that's not my issue. I have to refactor the template step by step, just because... And it's just an example. Could be that two independent templates use the same Chrome names, why should it be an expected behavior that the
output is broken then?

**Comment by coolcat-creations** [comment]
Btw Alternate Layouts do work cross templates.

**Comment by ghost** [comment]
@coolcat-creations can you please see https://github.com/joomla/joomla-cms/issues/24456#issuecomment-479211889 by @mbabker?

**Comment by coolcat-creations** [comment]
There is an error if you name a module chrome same like the system template so if the same error is fired when using cross templates people will at least understand where the "bug" comes from. Thats the solution I would propose.

Second solution would be that there is only one modules.php from the system and it's overriden completely with the modules.php in the html folder. That would at least follow a part of the override logic in Joomla. But unfortunately it would break probably some templates because the override modules.php needs to carry the system functions if the template uses them. 
@franz-wohlkoenig

**Comment by Bakual** [comment]
In J3 it's probably not possible to solve.
In J4 we changed the chromes to use JLayouts and it already works the way you want it (I think). 😄

**Comment by coolcat-creations** [comment]
@Bakual exciting :) Any documentation how to migrate?

**Comment by Bakual** [comment]
Documentation? What is that?
You can look at what I did in https://github.com/joomla/joomla-cms/pull/23570
Basically you will have to copy the stuff inside the each function in modules.php to an own  JLayout.

**Comment by saraheagle** [comment]
#23570 is perfect, it'll be great to be able to use module types from other templates. Thank you :)

**Comment by Bakual** [comment]
@saraheagle That's already merged into 4.0 😄

**Comment by ghost** [comment]
@brianteeman can this Issue be closed?

**Comment by coolcat-creations** [comment]
Just one question - if 3.10 will be like 4.0 from the B/C is this system change from #23570 forseen to already work in 3.10 or not?

**Comment by brianteeman** [comment]
No new features in 3.10

As its not going to be changed in j3 and it is resolved in j4 then yes you can close it

**Comment by coolcat-creations** [comment]
Ok @franz-wohlkoenig somewhere where B/C changes are documented this will be something that will break lots of templates so it has to be written somewhere in the upgrade informations.

**Comment by ghost** [comment]
#23570 has Label "Documentation Required".

**Comment by coolcat-creations** [comment]
@franz-wohlkoenig yes but that are two things. Dokumentation Required vs. Ugrade Warnings... or not?

**Comment by ghost** [comment]
Sorry, i read "documented" and "written somewhere" and looked at Label.

**Comment by coolcat-creations** [comment]
Yes sorry - formulated it wrong... Is there any document which collects all B/C breaks?

**Comment by ghost** [comment]
https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4

I did a quick search so maybe theres another doc or more is planned.

**Comment by Bakual** [comment]
Yep, this has to be added to that BC issues doc. And best with a link to my PR or some other explanation how it works.

Templates that want to support bot J3 and J4 can already add those new JLayouts. In j3 they will just be ignored. When migrating to J4, the JLayout will then work and the modules.php will just be ignored.

**Comment by coolcat-creations** [comment]
Ok great so the other answer that this will not work in 3.10 was wrong then. Good to hear. Thank you @Bakual

**Comment by Bakual** [comment]
@coolcat-creations The JLayouts will not work in 3.10. Brian said that correctly. It will only work with 4.x.

However you can write a template which works both in 3.x and 4.x by adding both the current modules.php and the new JLayouts. That's what I meant.

**Comment by coolcat-creations** [comment]
Got it, thanks!

**Comment by jwaisner** [comment]
As this has been fixed in J4 and is confirmed to not be resolvable in J3. Closing this entry.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17953">issues.joomla.org/tracker/joomla-cms/17953</a>.</sub>

**Comment by ReLater** [comment]
> Yep, this has to be added to that BC issues doc. And best with a link to my PR...

Done: https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4#Modules
