### ISSUE TITLE
Website Authorizations

### ISSUE THREAD

**Issue by meganmill9** [joomla/joomla-cms#17965]
Using a CMS guesser, I tracked my company's website to Joomla. We are no longer in touch with the company that set up our website and need the proper authorizations to get to the new company we are working with. Can someone please help us? Email mmiller@penksevehicleservices.com or call 248-729-5446 if you are able to assist!

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding. For this Reason i close this Issue, thanks.
