### ISSUE TITLE
Duplicate extension entries when a extension is using two update servers

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#17969]
### Steps to reproduce the issue

Install a extension that uses a collection and extension update server (similiar should happen with multible update servers too)

### Expected result

Just one entry that indecate compatibility or not

### Actual result

On entry per update server that indecate compatibility or not.

### System information (as much as possible)

![image](https://user-images.githubusercontent.com/2596554/30511708-ff929fac-9ade-11e7-884a-a64d7c57ca7e.png)

### Additional comments

cc @wilsonge

**Comment by brianteeman** [comment]
Can you give an example extension that is affected by this?

**Comment by zero-24** [comment]
You can checkout any of my extensions ;) For example you can use this:

Key `56D3152A0EC8698E4D3CAD1317D484EB110`
Download: https://www.jah-tz.de/download-bereich.html

**Comment by ghost** [comment]
any Suggestion @brianteeman?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17969">issues.joomla.org/tracker/joomla-cms/17969</a>.</sub>

**Comment by brianteeman** [comment]
What is the use case for having the two update servers. It sounds weird.

**Comment by zero-24** [comment]
> What is the use case for having the two update servers. It sounds weird.

Nothing spezial but give the design of the update server this is possible and supported so we should fix that issue ;)

The idea behind that could be the priority tag or a different updateserver in case one domain is down etc.

**Comment by SDKiller** [comment]
@brianteeman

> What is the use case for having the two update servers. It sounds weird.

It isn't really (;
For example, currently in Russia many users are unable to update Joomla because some ISPs block AWS IP adresses.

http://m.cnews.ru/news/top/2017-09-26_v_rossii_zablokirovali_dostup_k_sverhpopulyarnomu

**Comment by wilsonge** [comment]
@zero-24 i can't see a PR linked to this - did this actually get fixed? if not it should be fixed :)

**Comment by zero-24** [comment]
I have been told that my setup is weird without any other voice raised in months (the fallback for blocked AWS is implemented in a different way already) I decided to close it as no issue. So correct there is no PR yet. ;)

**Comment by zero-24** [comment]
see: https://github.com/joomla/joomla-cms/pull/27318
