### ISSUE TITLE
Menu items: Associations Tab : Single quote forced escaped

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#17971]
### Steps to reproduce the issue
Set a multilngual site including French Language.
Switch backend to French
Create a new menu item, set its content language to any language available.
Save (NOT Save and close).
Display the Associations tab

You will get:
![screen shot 2017-09-16 at 16 36 27](https://user-images.githubusercontent.com/869724/30513132-4b15cfca-9afe-11e7-8243-a6ff3d5a77a5.png)

IN French the string is
`COM_MENUS_ITEM_FIELD_ASSOCIATION_NO_VALUE="- Pas d'association -"`

The single quote is escaped in the display although it should not.

The code used is
$option = $field->addChild('option', 'COM_MENUS_ITEM_FIELD_ASSOCIATION_NO_VALUE');

in
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/models/item.php#L1231-L1245

@izharaazmi 
Anyhting we can do? 
The way these field are displayed is very different from the other components.

**Comment by izharaazmi** [comment]
@infograf768 Please see if using `&apos;` helps. If not I'd look deeper.

```ini
COM_MENUS_ITEM_FIELD_ASSOCIATION_NO_VALUE="- Pas d&apos;association -"
```

**Comment by infograf768** [comment]
@izharaazmi 
I could use a real typographer quote `‘`
But it does not solve the underlying issue.

**Comment by izharaazmi** [comment]
Alright. I'd see what I can do.

**Comment by brianteeman** [comment]
It is not directly related to this one string and I suspect its either a field or JTEXT issue
As a test I made the following language overrides

  | JGLOBAL_USE_GLOBAL | Use G'lobal 
  | JGLOBAL_USE_GLOBAL_VALUE | Use G'lobal (%s)

And as can be seen in the screenshot below depending this may cause issues as well.

<img width="341" alt="screenshotr14-04-10" src="https://user-images.githubusercontent.com/1296369/31228666-2bd80286-a9d6-11e7-8313-f9cb90c3c9fd.png">

**Comment by infograf768** [comment]
the associations fields for menu items are not present in a xml. they are created on the fly as explained above. therefore it is not imho a JText issue but a result of the way Options are created.
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/models/item.php#L1231-L1245

**Comment by infograf768** [comment]
I think I found a solution, by not using the specific code
```
					$option = $field->addChild('option', 'COM_MENUS_ITEM_FIELD_ASSOCIATION_NO_VALUE');
					$option->addAttribute('value', '');
```
In that case, it is going to use the default
`COM_MENUS_SELECT_A_MENUITEM`

And then we need to change the JText from true to false in modal/menu.php
`$title_holder = JText::_('COM_MENUS_SELECT_A_MENUITEM'); // instead of true.`
in all places. It will take off the counterslash.

The patch could be more important than that though as we do have the possible same issue for modal fields elsewhere in code.

I guess it is better I do a single PR for this specific issue and then a global PR if necessary.

**Comment by infograf768** [comment]
@izharaazmi 
What do you think?

**Comment by izharaazmi** [comment]
@infograf768 In current staging I get this.
 ![image](https://user-images.githubusercontent.com/6706189/36944547-c2199d22-1fc4-11e8-9166-de4c10bb9480.png)

I installed French language. Logout and logged in with French language selected. Created a new menu item with language = french and hit save (not close). I get this in the association tab.

Am I missing something?

**Comment by izharaazmi** [comment]
Sorry, I missed that this is for 4.0. Testing again.

**Comment by infograf768** [comment]
In fact it is even more simple.
We can keep the addchild code and then just take off true in modal/menu.php
Will do PR

**Comment by izharaazmi** [comment]
@infograf768 Same result with 4.0-dev

**Comment by infograf768** [comment]
@izharaazmi 
I had changed in French the singlequote to Typographic quote, thus why you do not find the issue.

**Comment by infograf768** [comment]
Making a PR now

**Comment by infograf768** [comment]
and this is for staging :)

**Comment by infograf768** [comment]
@izharaazmi @brianteeman 
Please test
https://github.com/joomla/joomla-cms/pull/19828
