### ISSUE TITLE
Joomla statistics doesn't honor "once" choice

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#17976]
### Steps to reproduce the issue

using joomla 3.7.5 choose "once" when asked for statistics reporting.
when cookie expires it will come back again.

### Expected result
request will not show after selecting "once"

### Actual result
shows each time cookie expires

![capture](https://user-images.githubusercontent.com/1850089/30525998-eb5b87d4-9bd7-11e7-8f1e-fbe3c8a16f47.PNG)

### System information (as much as possible)

[systeminfo-2017-09-17T23-42-32+00-00.txt](https://github.com/joomla/joomla-cms/files/1309475/systeminfo-2017-09-17T23-42-32.00-00.txt)

**Comment by brianteeman** [comment]
That makes no sense because there are no cookies involved. If you check the database table #__extensions you will see the options are saved there

**Comment by C-Lodder** [comment]
@N6REG - so if you set it to 'Never' and manually clear your browser cookies, the message will reappear?

**Comment by george-wilson-iproov** [comment]
"Once" means "Yes this time then prompt me again next time Joomla would normally send stats". So this is expected behaviour

**Comment by wilsonge** [comment]
"Once" means "Yes this time then prompt me again next time Joomla would normally send stats". So this is expected behaviour

**Comment by brianteeman** [comment]
If you think about it then it can't be a cookie or the setting would only be set in the users browser which obviously wouldn't make sense when you man have many users

**Comment by N6REJ** [comment]
@brianteeman true.
@wilsonge thats silly.. once should literally mean "ok, this ONE TIME go ahead then never"  Shouldn't require 2 steps as the word 'once' is singular.
