### ISSUE TITLE
Duplicate article when change category on frontend with custom field

### ISSUE THREAD

**Issue by trananhmanh89** [joomla/joomla-cms#17977]
### Steps to reproduce the issue
1. Edit any article on frontend
2. Make sure that article has custom field
3. Change category
4. Hit save
5. Go to articles management on backend and see the result
 
### Expected result
- Article Category is changed

### Actual result
- Article is duplicated with new category

### System information (as much as possible)

-  Tested with joomla 3.7.5, 3.8 rc
- PHP 5.6
- MariaDB 10.2.3

### Additional comments
Video: https://www.youtube.com/watch?v=YM8McupJBow&feature=youtu.be

**Comment by ghost** [comment]
Can't confirm.

Change Category of Article works as expected (using a Text-Field).

### System information
3.8.0-rc2-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
i can confirm this

**Comment by alikon** [comment]
...weird...
it happens when you have a field 
without fields works as expected

**Comment by ghost** [comment]
Tried again, this Time a second com_field "List of Images": Didn't get issue. Does it depend on Mulitlang. Site also?

**Comment by alikon** [comment]
i was able to replicate the issue with a basic monolang with sample testing data and 1 article field

**Comment by ghost** [comment]
will test on fresh Install.

**Comment by ghost** [comment]
No Issue on fresh monolang. Install using one com_field type "text".

**Comment by alikon** [comment]
did you change the category from frontend ?

**Comment by ghost** [comment]
Changed Category from Frontend as Superuser.

**Comment by alikon** [comment]
i guess related to this one #17872

**Comment by brianteeman** [comment]
Yes sounds like it and would explain why it is not happening in 3.8 for @franz-wohlkoenig  not at my PC to check but will do later

**Comment by brianteeman** [comment]
I can confirm that this is resolved by #17872 so am closing it here as it will be resolved with the release of 3.8
