### ISSUE TITLE
Feature Request: Plugin Hooks for Media Upload

### ISSUE THREAD

**Issue by pAnd0rASBG** [joomla/joomla-cms#17973]
## Synopsis
Image Optimization is (still) a major part in optimizing your site's overall performance and rating. Especially when maintaining a site with multiple Editors, who are "not tech savvy", one more often than not ends up preaching "please optimize your images" only to find some of those 600dpi 150x150px 2.8 MB images in the images folder a few days later - **again**. 
Nowadays online optimizers, such as kraken.io, offer APIs for automatic image optimization, so all it would need was a Hook for Plugins in com_media (like e.g. $this->item->event->afterDisplayTitle in com_content) to run after upload.

## Request
Add a "post upload" Hook to com_media for automatic image optimization/manipulation by plugins.

Cheers

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_media/controllers/file.php#L146-L180

The `onContentBeforeSave` and `onContentAfterSave` events are already triggered.

**Comment by pAnd0rASBG** [comment]
Oh nice, my bad then. 
Cheers for pointing that out.
