### ISSUE TITLE
After update to 3.8.0 site don't work

### ISSUE THREAD

**Issue by banha-serhii** [joomla/joomla-cms#17986]
### Steps to reproduce the issue
1. After displaying message "Update Joomla to 3.8.0"  http://prntscr.com/gn2x8w use online update http://prntscr.com/gn2xl7

### Expected result
Joomla was to update

### Actual result
Displaying error:  0 - Call to undefined method JAdminCssMenu::addChild() http://prntscr.com/gn2y0b

**Comment by ghost** [comment]
maybe this helps https://www.joomshaper.com/forums/joomla-3-8

**Comment by coolcat-creations** [comment]
@banhaserhij if you have any custom admin menu module, try to disable it by renaming the folder and see if it works. Please report which module causes the issue.

**Comment by mbabker** [comment]
Added to FAQ - https://docs.joomla.org/J3.x:Call_to_undefined_method_JAdminCssMenu::addChild_in_backend

**Comment by JacquesR** [comment]
@mbabker should that page be moved under here?
https://docs.joomla.org/Category:Version_3.8.0_FAQ

**Comment by mbabker** [comment]
If Mediawiki didn't make categories so difficult it would've been there before (it is now).

**Comment by Reijo83** [comment]
Hi please update SP page Builder pro to 2.5.3<hr />More info this issu: https://www.joomshaper.com/forums/joomla-3-8

**Comment by Reijo83** [comment]
Same info: https://www.joomshaper.com/forums/joomla-3-8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17986">issues.joomla.org/tracker/joomla-cms/17986</a>.</sub>

**Comment by zero-24** [comment]
Closing as known problem thanks.
