### ISSUE TITLE
Users: Viewing Access Levels

### ISSUE THREAD

**Issue by iahmedani** [joomla/joomla-cms#17981]
### Steps to reproduce the issue
I added new user group named "special" and went to set viewing Access levels, by default it has 3 access levels, I removed(uncheck) those and it appeared that my (my profile) rights/viewing access levels were removed. 

### Expected result
Expected results was that any change in certain group should only affect that group only

**Comment by ghost** [comment]
can you please give more Details which Steps you have done, also if possible showing Screenshots in English Lang. and give System information (as much as possible).

**Comment by brianteeman** [comment]
Closed due to lack of response. It can always be re-opened if updated.
