### ISSUE TITLE
Extra Spacing in Admin Menu

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#17984]
No idea if this is intentional or not but I'm seeing extra spacing between the menu item text and the dropdown arrow on sites I've updated from 3.7.5 to 3.8.

3.7.5:
<img width="676" alt="screen shot 2017-09-19 at 7 31 14 am" src="https://user-images.githubusercontent.com/368545/30592553-da89bde6-9d0c-11e7-8b68-aae806c5ef43.png">

3.8.0:
<img width="737" alt="screen shot 2017-09-19 at 7 31 37 am" src="https://user-images.githubusercontent.com/368545/30592563-e0de35fa-9d0c-11e7-995f-bb5374945b29.png">

**Comment by brianteeman** [comment]
Doesnt look right to me

**Comment by brianteeman** [comment]
there is an extra `&nbsp;` that is causing this

**Comment by brianteeman** [comment]
it comes from (#17511) i am creating a pr to revert that bit

**Comment by brianteeman** [comment]
Closed see #17985 for a fix - good spot @mbabker
