### ISSUE TITLE
Broken Redirects Fix

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#17996]
### Steps to reproduce the issue
Have an absolute 404 generated i.e.

http://localhost/artriclessssss.html
find in redirect manager and redirect to:
http://localhost/articles.html

404 redirected to:

http://localhost/http://localhost/articles.html

### Expected result
Redirects to
http://localhost/articles.html

To fix, install patch. Test both absolutely and relative redirects work.

**Comment by wilsonge** [comment]
Closing as we have a Pull Request
