### ISSUE TITLE
Class 'JLog' not found

### ISSUE THREAD

**Issue by ctech-design** [joomla/joomla-cms#17998]
### Steps to reproduce the issue
I've updated Joomla in one of my sites to v3.8.0 and my component stopped working, it show this error.

Class 'JLog' not found in /Users/apple/Sites/test-new/libraries/legacy/error/error.php on line 371
![screen shot 2017-09-20 at 06 20 28](https://issues.joomla.org/uploads/1/f7957a626406dc81b88e57b18be9b098.png)

**Comment by ghost** [comment]
which Component you mean?

**Comment by ctech-design** [comment]
Sellecious, it's an eCommerce component. When tried to login to its backend, this error showed up.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17998">issues.joomla.org/tracker/joomla-cms/17998</a>.</sub>

**Comment by ctech-design** [comment]
Sellacious https://extensions.joomla.org/extensions/extension/e-commerce/shopping-cart/sellacious/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17998">issues.joomla.org/tracker/joomla-cms/17998</a>.</sub>

**Comment by ghost** [comment]
please contact Developers of this Component, thanks. Closing as no Core-Issue.

**Comment by Diversal** [comment]
was this ever solved?? 

Experiencing same issue, after Joomla Update. Trying to restore, however keep getting this error message!

**Comment by wojsmol** [comment]
@Diversal Please open new topic on forum https://forum.joomla.org/viewforum.php?f=710.

**Comment by Diversal** [comment]
@wojsmol  I've done so - see here: https://forum.joomla.org/viewtopic.php?f=710&t=963606
