### ISSUE TITLE
menu item alias memory error when you use double quotes on a title "some title"

### ISSUE THREAD

**Issue by geodou** [joomla/joomla-cms#18002]
### Steps to reproduce the issue
try to create a menu item with double quotes, then create a new menu and add menu item alias, use again double quotes

### Expected result
fatal error

**Comment by brianteeman** [comment]
I could not replicate this 
I created a single article menu item called - my "quotes" test
I then created a menu item alias to that menu called - my "alias" test

without problems

**Comment by geodou** [comment]
i see this problem in 3 articles witch i had to change their names, i use a clean joomla without using extensions or any other third party components etc.

the fatal error has to do with memory size and was about a file called query.php. my fault i didnt catch the line and where that file is.

now i try to recreate this and its working fine...

what can i say
