### ISSUE TITLE
No more frontend after upgrade to J3.8. Error 0 reported at /libraries/joomla/http/transport/cacert.pem

### ISSUE THREAD

**Issue by ranpre** [joomla/joomla-cms#18004]
### Steps to reproduce the issue

Upgrade Joomla 3.7.5 to 3.8 with active ssl certificate.

### Expected result
Frontpage loading

### Actual result
Frontpage fails to load. 
Error message (error 0) refers to ../libraries/joomla/http/transport/cacert.pem

### System information (as much as possible)
PHP 7
Apache

**Comment by mbabker** [comment]
The presence of a SSL certificate in and of itself is not the issue.  In fact, that file only gets read into memory by core if an extension is trying to make a remote call to another service.

With that said though, the file has moved to `libraries/src/Http/Transport/cacert.pem`, if an extension is trying to use that file on its own the reference needs to be updated.

**Comment by ghost** [comment]
@ranpre have you found which Extension is trying to use?

**Comment by ranpre** [comment]
Can't say yet, since log files are available on Monday earliest. However, when searching by FTP I found 8 different versions of cacert.pem co-existing on the server.

Another observation ist that the error indeed only happens on SSL secured site. When upgrading to J3.8 on a non-SSL test site (holding an exact copy of the SSL-site) everything went fine.

**Comment by wojsmol** [comment]
@ranpre Please give paths of `cacert.pem`.

**Comment by ranpre** [comment]
![cacert_pem](https://user-images.githubusercontent.com/16520609/30689795-4ec4c6ea-9ec2-11e7-8145-b004bdb64b69.JPG)

**Comment by wojsmol** [comment]
@ranpre `/libraries/joomla/http/transport/cacert.pem` should not exist after update to Joomla 3.8.0 if this file exist on ssl site in question then update was not completed correctly.

**Comment by ranpre** [comment]
Hmm. This contradicts somehow what @mbabker said before. If I understood him right, there's extensions that may use the file.

**Comment by wojsmol** [comment]
quote from [@mbabker reply](https://github.com/joomla/joomla-cms/issues/18004#issuecomment-330828238)

> With that said though, the file has moved to libraries/src/Http/Transport/cacert.pem, if an extension is trying to use that file on its own the reference needs to be updated.

So correct localisation of this file in 3.8.0 is `libraries/src/Http/Transport/cacert.pem`. Try using [postupdate.php](https://gist.github.com/mbabker/d7bfb4e1e2fbc6b7815a733607f89281) on dev copy of the site.

**Comment by ghost** [comment]
@ranpre any Updates as @wojsmol suggested?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18004">issues.joomla.org/tracker/joomla-cms/18004</a>.</sub>

**Comment by wojsmol** [comment]
@franz-wohlkoenig After days of faithing with those errors I can teal you that - they are not remove 1 file cases.

**Comment by ghost** [comment]
So its better to discuss on [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710) and close here?

**Comment by wojsmol** [comment]
@franz-wohlkoenig yes

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18004">issues.joomla.org/tracker/joomla-cms/18004</a>.</sub>
