### ISSUE TITLE
Do not attempt 3.8 Upgrade - Application Instantiation Error

### ISSUE THREAD

**Issue by Publiship** [joomla/joomla-cms#18005]
The database config IS correct. They only way to fix this is to restore from backup. 

Just once I'd like Joomla to issue an update that actually wo

**Comment by brianteeman** [comment]
I have updated over 50 sites  without error. From the information you have provided it is not possible to help you

**Comment by C-Lodder** [comment]
> Application Instantiation Error

Perhaps the error is coming from a 3rd party extension?

Perhaps you could give a little more information about your error?

> Just once I'd like Joomla to issue an update that actually wo

Perhaps you could help with testing Beta and RC versions before the update is released rather than posting stupid comments like that

-----------
I too have updated sites to 3.8 without any problems

**Comment by alexmixaylov** [comment]
I try update j3.7.5 to 3.8
In adminpanel i have the critical error:
Call to undefined method JAdminCssMenu::addChild()
i use a 3rd party extension -  Zoo
in front of i have problem too

**Comment by alikon** [comment]
can you test without 3rd extensions?

**Comment by alexmixaylov** [comment]
OK
I disabled the extension
and again tried to update Joomla
update is successful but  now I get this notice:

Notice: Constant JROUTER_MODE_RAW already defined in /home/alex/www/delfa.loc/libraries/cms/router/router.php on line 17
Notice: Constant JROUTER_MODE_SEF already defined in /home/alex/www/delfa.loc/libraries/cms/router/router.php on line 24

in adminpanel I can not get
I keep getting redirected

**Comment by mbabker** [comment]
If this is on 3.8 then your upgrade was not successful as the `libraries/cms/router/router.php` file should have been deleted.
