### ISSUE TITLE
PHP 7.2 Removed mcrypt

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#18007]
We have checks in core regarding the presence of the mcrypt extension.  Since that has been dropped in PHP 7.2, we need to update core to account for this.

**Comment by brianteeman** [comment]
Although we have the checks didnt we already remove any usage of mcrypt? I thought the only place it was used was in tfa and we stopped that back with 3.6.3

**Comment by mbabker** [comment]
I'm pretty sure use of it is phased out, or in optional paths (i.e. the FOF and core encryption adapters).  But, we still have some code checks in places that should probably be dropped (or if we want to check for presence at least wrap it in a PHP version conditional).

https://github.com/joomla/joomla-cms/blob/dc12100db9cb396b8210678f0f53973ef33615a1/installation/model/setup.php#L299-L304

https://github.com/joomla/joomla-cms/blob/6e07ca6fadd8a5d1db3337cf0357d782646f5411/administrator/components/com_admin/models/sysinfo.php#L255

**Comment by brianteeman** [comment]
didnt the fof update back in 2016 remove it?

**Comment by brianteeman** [comment]
sorry i was wrong on that.

**Comment by mbabker** [comment]
The hard dependency was removed.  The mcrypt adapter is still there.

All of our mcrypt code paths are still usable, even on PHP 7.2 if you install the PECL extension (why you'd want to is beyond me but hey, more power to you).  Those two links I pointed out above though are system health checks that make an implication that mcrypt should be installed.  Those are the types of things we need to deal with at this point.  It's not about functionality at this point really, it's more about what we're communicating to users in validating their server is "good" to run the software.

**Comment by brianteeman** [comment]
Ok. I will take a look at doing a pr for that then

**Comment by Quy** [comment]
See PR #18169

**Comment by ghost** [comment]
closed as having Pull Request #18169 

Thanks for Hint @Quy <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18007">issues.joomla.org/tracker/joomla-cms/18007</a>.</sub>
