### ISSUE TITLE
Ajax download error during j3.8 upgrade from 3.7.5 - install ABEND, site corrupted

### ISSUE THREAD

**Issue by fdinkler** [joomla/joomla-cms#18006]
### Steps to reproduce the issue
Using Joomla upgrade component, to download and write J3.8 files, early in the process, threw an error "Ajax downloads not permitted" and upgrade process stopped.  
Site was corrupt 500 error loading home page - no admin menus, etc...
Restored files from backup to recover.

### Expected result
Upgraded site

### Actual result
Corrupt site / partial upgrade

### System information (as much as possible)
PHP Built On	Linux box291.bluehost.com 3.10.0-614.10.2.lve1.4.50.el6h.x86_64 #1 SMP Mon May 22 17:31:11 EDT 2017 x86_64
Database Version	5.6.32-78.1-log
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.31
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.7.5 Stable [ Amani ] 14-August-2017 12:09 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments
Upgrade component has worked without problems up to this point.

**Comment by ghost** [comment]
can you please take a Look at #18003 if this Discussion help?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18006">issues.joomla.org/tracker/joomla-cms/18006</a>.</sub>

**Comment by zero-24** [comment]
> Ajax downloads not permitted

hmm please contact your hoster and double check that is not a limitation on theier side. There is no code that throw such error in the joomla core: https://github.com/joomla/joomla-cms/search?utf8=%E2%9C%93&q=Ajax+downloads+not+permitted&type= 😄 

Thanks.

**Comment by ghost** [comment]
@fdinkler have you contacted the Hoster?

**Comment by ghost** [comment]
As there are similar Threads this gets closed; it can always reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18006">issues.joomla.org/tracker/joomla-cms/18006</a>.</sub>
