### ISSUE TITLE
Update Mail - target link should show available extension updates

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#18001]
If you click on the link in the Joomla! Update mail you are redirected directly to the Joomla! update site. Which is great of course, but i think this page should check available extension updates at this point and warn the user to keep care of updating 3rd party extensions.

**Comment by brianteeman** [comment]
that is now available for 3.9

**Comment by coolcat-creations** [comment]
Ok - issue closed then ;)
