### ISSUE TITLE
Upgrade from 3.75 to 3.8 sometimes fails

### ISSUE THREAD

**Issue by rgtr** [joomla/joomla-cms#18015]
![snap_170920_152326](https://user-images.githubusercontent.com/25705418/30649464-3f40d84e-9e18-11e7-8695-b0da8bf02b9f.jpg)
### Steps to reproduce the issue
Upgrade from 3.75 to 3.8

### Expected result
Normal upgrade

### Actual result
Lost non system components like Akeeba - ouch

### System information (as much as possible)
Akeeba does appear for example in the system control panel maintenance, and in the list of plugins.

[systeminfo-2017-09-20T15-23-37+01-00.pdf](https://github.com/joomla/joomla-cms/files/1318052/systeminfo-2017-09-20T15-23-37.01-00.pdf)

### Additional comments
Everything worked well on three of my five sites, but two have this symptom
Being a volunteer running web sites i am not sql competent.
Please email richard@tdoc.net for the akeeba jpa taken after upgrade on wp.tdocplus.co.uk - front end works fine. lp.tdocplus.co.uk also  works fine.

**Comment by ghost** [comment]
can you please take a Look at #18003 if this Discussion help?

**Comment by ghost** [comment]
closing this Issue, please comment at #18020 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18015">issues.joomla.org/tracker/joomla-cms/18015</a>.</sub>
