### ISSUE TITLE
Update Joomla 3.7.5 to 3.8

### ISSUE THREAD

**Issue by classicpark** [joomla/joomla-cms#18011]
I did the update  and now on my admin part from Joomla i have a error 

GET http://www.raceworld.org/administrator/index.php?option=com_config 500 (Internal Server Error)

And in my log file on the server i have this

This is my first time that this is happend to me.

I can login to the backend but noting is working i see the top menu but its not working
And on the admin index  all info is gone

**Comment by classicpark** [comment]
Here is my error file[error.txt](https://issues.joomla.org/uploads/1/ed7708341917082231ec8fa54990c4fb.txt)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18011">issues.joomla.org/tracker/joomla-cms/18011</a>.</sub>

**Comment by ghost** [comment]
can you please take a Look at #18003 if this Discussion help?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18011">issues.joomla.org/tracker/joomla-cms/18011</a>.</sub>

**Comment by mbabker** [comment]
> Uncaught RuntimeException: Library path /libraries/src cannot be found

This means the update did not complete successfully.  3.8 adds a `libraries/src` directory.

If you have a backup try restoring it and updating again.  If that doesn't work, follow [these instructions](https://gist.github.com/mbabker/d7bfb4e1e2fbc6b7815a733607f89281) to perform a manual upgrade which should perform all of the steps required to emulate the core update process.

**Comment by mikelawrey32** [comment]
That worked for me, thanks @mbabker !  Can anyone tell me if this will be added to future updates???<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18011">issues.joomla.org/tracker/joomla-cms/18011</a>.</sub>

**Comment by ghost** [comment]
@mikelawrey32 if Issue is solved can you please close #18013?

**Comment by mbabker** [comment]
@mikelawrey32 no it won't be added to future updates.  It's really not a "core" supported update mechanism but I had seen that a lot of folks were doing updates not using the core update component for various reasons so I crafted a tool that could help make sure if folks were doing manual updates they could get all of the required changes needed for an update to go as expected.

**Comment by mikelawrey32** [comment]
Ok, Ill continue to keep my eyes open for solutions...as this is an issue that also exists when trying to update via the Joomla admin update. Thanks for your help

**Comment by classicpark** [comment]
[postupdate.txt](https://issues.joomla.org/uploads/1/3e1186a19c0ac284b4c0dc5c6d6531a3.txt)Parse error: syntax error, unexpected '<', expecting end of file in /home/sites/site43864/web/administrator/postupdate.php on line 76<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18011">issues.joomla.org/tracker/joomla-cms/18011</a>.</sub>

**Comment by classicpark** [comment]
story so far udated by ftp
Did loaded postupdate to mysite/administrator/postupdate.php

message than is Update to 3.8.0 completed successfully. 

but stil same problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18011">issues.joomla.org/tracker/joomla-cms/18011</a>.</sub>

**Comment by wilsonge** [comment]
Do you have a directory at `mysite/libraries/src`?

**Comment by classicpark** [comment]
Ps. when i go to the postupdate.php i need to login because im using admintools to secure  the backend so i need to loggin  once.
than  i do receive straith the message Update to 3.8.0 completed successfully.

So there is no action to see from postupdate.php 
Normal i need to login twice  first treu admin tools and tha with  the joomla backend login

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18011">issues.joomla.org/tracker/joomla-cms/18011</a>.</sub>

**Comment by classicpark** [comment]
I did  deleted the  admintools log file and password so i have only joola login 

uploaded again by ftp 

than straith to administrator/postupdate.php

Same message  Update to 3.8.0 completed successfully

But i did not see the script do anny thing.
i did ask my host for a bakup incl database from 3.7.5  grrr €50.- for a update

So than i need to upload the  3.8 update with ftp and than  load the coreupdate.php file with ftp and than go to mysite/administrator/postupdate.php




<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18011">issues.joomla.org/tracker/joomla-cms/18011</a>.</sub>

**Comment by classicpark** [comment]
@wilsonge  Yes i have that mysite/libraries/src<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18011">issues.joomla.org/tracker/joomla-cms/18011</a>.</sub>

**Comment by wojsmol** [comment]
@classicpark Result of the script is recorded in `mysite/logs/joomla_update.php` or `mysite/administrator/logs/joomla_update.php`

**Comment by classicpark** [comment]
@wojsmol my webhost is setting the backup back from joomla 3.7.5 now it will take some time because the database is big.
So what to do when the site is restored to Joomla 3.7.5 and than to upgrade  to Joomla 3.8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18011">issues.joomla.org/tracker/joomla-cms/18011</a>.</sub>
Old file from update 3.7.5 to 3.8 administrator/logs/joomla_update.php
[joomla_update.txt](https://github.com/joomla/joomla-cms/files/1318953/joomla_update.txt)

**Comment by classicpark** [comment]
@franz-wohlkoenig  I did check your link Admin errors after 3.7.5 to 3.8 update #18020.But there is no solution for me

**Comment by classicpark** [comment]
Sorry it whas not my meaning to close this ticket i hid the wrong button  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18011">issues.joomla.org/tracker/joomla-cms/18011</a>.</sub>

**Comment by classicpark** [comment]
@franz-wohlkoenig
My site is bag to Joomla 3.7.5 now i like to know how to upgrade to Joomla 3.8 so i dont have problems plz.
Can it be my webhost  i never had anny problems before udating Joomla and i use Joomla for a long time.
Im realy lost here @ the moment so anny advice is welkom

**Comment by ghost** [comment]
@classicpark i can give no solution. I suggest to read and write in other Threads too, also on the [forums](https://forum.joomla.org/).

**Comment by wojsmol** [comment]
@classicpark 

0.  Make sure you have a backup of your site (files and database).
1. Download [this](https://downloads.joomla.org/cms/joomla3/3-8-0/joomla_3-8-0-stable-full_package-zip?format=zip) package
2. Upload it to your site root and extract it  with file manager.
3. Remove installation folder.
4. Then use [this](https://gist.githubusercontent.com/mbabker/d7bfb4e1e2fbc6b7815a733607f89281/raw/4f8bd9cfd2c54f853ca99bae3033586a81f9f236/postupdate.php) file as described [here](https://gist.github.com/mbabker/d7bfb4e1e2fbc6b7815a733607f89281#file-readme-md).

**Comment by ghost** [comment]
@classicpark please Look at [Comment](https://github.com/joomla/joomla-cms/issues/18020#issuecomment-331279572) of @mbabker which helped others with similar Issues.

**Comment by ghost** [comment]
closing this Issue, please comment at #18020 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18011">issues.joomla.org/tracker/joomla-cms/18011</a>.</sub>
