### ISSUE TITLE
categoryedit.php error

### ISSUE THREAD

**Issue by Reijo83** [joomla/joomla-cms#18019]
### Steps to reproduce the issue
Turn on Error Reporting (Development). Go Articles, choose Search tools then choose Category now add new article. When you open up new article window you get right side error:

### Actual result
`Notice: Array to string conversion in D:\xampp\htdocs\oma2\administrator\components\com_categories\models\fields\categoryedit.php on line 281

Notice: Array to string conversion in D:\xampp\htdocs\oma2\administrator\components\com_categories\models\fields\categoryedit.php on line 281

Notice: Array to string conversion in D:\xampp\htdocs\oma2\administrator\components\com_categories\models\fields\categoryedit.php on line 281

Notice: Array to string conversion in D:\xampp\htdocs\oma2\administrator\components\com_categories\models\fields\categoryedit.php on line 281

Notice: Array to string conversion in D:\xampp\htdocs\oma2\administrator\components\com_categories\models\fields\categoryedit.php on line 281

Notice: Array to string conversion in D:\xampp\htdocs\oma2\administrator\components\com_categories\models\fields\categoryedit.php on line 281

Notice: Array to string conversion in D:\xampp\htdocs\oma2\administrator\components\com_categories\models\fields\categoryedit.php on line 281`

![example](https://user-images.githubusercontent.com/12607649/30658355-199ff6bc-9e43-11e7-8678-e3c17ebe2828.jpg)

### System information (as much as possible)
XAMP
Joomla! 3.8
PHP 7.0.13
Database Version | 5.5.5-10.1.19-MariaDB
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci

**Comment by ghost** [comment]
Issue confirmed.

You have to choose a Category to get the Notices.

**Comment by Quy** [comment]
Duplicate #17974

**Comment by ghost** [comment]
closed as duplicate Report. Thanks for Hint @Quy <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18019">issues.joomla.org/tracker/joomla-cms/18019</a>.</sub>
