### ISSUE TITLE
Updating to Joomla 3.8 crashes InnoDB

### ISSUE THREAD

**Issue by MarketingApe** [joomla/joomla-cms#18018]
### Steps to reproduce the issue
Updating from 3.7.5 to 3.8

### Expected result

crashes innodb and brings down MySQL

### Additional comments
brought down all database sites on my hosted server...tech support advised InnoDB crashed.  This happened 3 times.

**Comment by ghost** [comment]
can you please take a Look at #18003 if this Discussion help?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18018">issues.joomla.org/tracker/joomla-cms/18018</a>.</sub>

**Comment by alikon** [comment]
or tell us more details about your issue ....

**Comment by landed1** [comment]
I'm not sure how any code can bring down a Db unless it was somehow malicious but even then crashing a database...I never heard about that. I would like to guess this was first line tech support with that handy nugget of info. It may have been the crash that ruined your install?
Do you have a backup? What host are you using?

**Comment by MarketingApe** [comment]
I am using InMotionHosting.com for the host provider and use a VPS.  I will finish installing the update on the remainder of the websites on the server, but I can tell you I definitely had some issues.  The server was flawless up until I started applying the update.  Certainly coincidence is possible.  I’ll let you know how the remainder of updates goes.

**Comment by tonypartridge** [comment]
Weirdly I had a similar issue today not sure if it is related... updated to 3.8 locally and MySQL went down, had to reboot to get it backup.

**Comment by brianteeman** [comment]
What mysql version etc
What version of Joomla were you updating from
Was there anything in the mysql logs

**Comment by tonypartridge** [comment]
Personally I didn't bother looking, just assumed it was a process lockup for some reason or other. But thought it worth mentioning on here incase it has any relevance.

**Comment by MarketingApe** [comment]
Here is some info on my configuration


  *   Server: Localhost via UNIX socket
  *   Server type: MySQL
  *   Server version: 5.6.37 - MySQL Community Server (GPL)
  *   Protocol version: 10
  *   User: root@localhost
  *   Server charset: UTF-8 Unicode (utf8)
Web server

  *   cpsrvd 11.66.0.23
  *   Database client version: libmysql - 5.1.73
  *   PHP extension: mysqli[Documentation]<https://marketingape.net:2087/cpsess0938720071/3rdparty/phpMyAdmin/url.php?url=https%3A%2F%2Fsecure.php.net%2Fmanual%2Fen%2Fbook.mysqli.php> curl[Documentation]<https://marketingape.net:2087/cpsess0938720071/3rdparty/phpMyAdmin/url.php?url=https%3A%2F%2Fsecure.php.net%2Fmanual%2Fen%2Fbook.curl.php> mbstring[Documentation]<https://marketingape.net:2087/cpsess0938720071/3rdparty/phpMyAdmin/url.php?url=https%3A%2F%2Fsecure.php.net%2Fmanual%2Fen%2Fbook.mbstring.php>
  *   PHP version: 5.6.30
phpMyAdmin

  *   Version information: 4.7.3

**Comment by MarketingApe** [comment]
So first attempt to upgrade to 3.8 following crash, it has a problem while doing the ackeeba backup prior to installing 3.8.  Here is the message ackeeba produced:
<strong>AJAX Loading Error</strong><br/>HTTP Status: 500 (Internal Server Error)<br/>Internal status: error<br/>XHR ReadyState: 4<br/>Raw server response:<br/>(HTML containing script tags)
Then, InnoDB and MySql crashes.

**Comment by MarketingApe** [comment]
MySql logs indicate the table jycbs_weblinks gets corrupted.  Is this table accessed as part of the update?  I was able to do an Ackeeba backup successfully on its own (not part of the Joomla update process).  Leads me to believe the update is corrupting the table.  Here is the MySQL log:

2017-09-20 15:37:04 21532 [Warning] InnoDB: Doublewrite does not have page_no=0 of space: 9599
2017-09-20 15:37:04 7f5032e5f720 InnoDB: Operating system error number 2 in a file operation.
InnoDB: The error means the system cannot find the path specified.
InnoDB: If you are installing InnoDB, remember that you must create
InnoDB: directories yourself, InnoDB does not create them.
InnoDB: Error: could not open single-table tablespace file ./wmtlaw_jmla37/jycbs_weblinks.ibd
InnoDB: We do not continue the crash recovery, because the table may become
InnoDB: corrupt if we cannot apply the log records in the InnoDB log to it.
InnoDB: To fix the problem and start mysqld:
InnoDB: 1) If there is a permission problem in the file and mysqld cannot
InnoDB: open the file, you should modify the permissions.
InnoDB: 2) If the table is not needed, or you can restore it from a backup,
InnoDB: then you can remove the .ibd file, and InnoDB will do a normal
InnoDB: crash recovery and ignore that table.
InnoDB: 3) If the file system or the disk is broken, and you cannot remove
InnoDB: the .ibd file, you can set innodb_force_recovery > 0 in my.cnf
InnoDB: and force InnoDB to continue crash recovery here.

**Comment by brianteeman** [comment]
So from that information we can see that your issue is server related and
not to do with the upgrade as akeeba fails before the upgrade starts

**Comment by MarketingApe** [comment]
Did you get my follow-up email with respect to the table corruption that occurs?

**Comment by MarketingApe** [comment]
I'm not the only one having issues with the upgrade.  I hope this gets the attention it deserves.  Here is the error from MySQL Log:

2017-09-20 15:37:04 21532 [Warning] InnoDB: Doublewrite does not have page_no=0 of space: 9599
2017-09-20 15:37:04 7f5032e5f720 InnoDB: Operating system error number 2 in a file operation.
InnoDB: The error means the system cannot find the path specified.
InnoDB: If you are installing InnoDB, remember that you must create
InnoDB: directories yourself, InnoDB does not create them.
InnoDB: Error: could not open single-table tablespace file ./wmtlaw_jmla37/jycbs_weblinks.ibd
InnoDB: We do not continue the crash recovery, because the table may become
InnoDB: corrupt if we cannot apply the log records in the InnoDB log to it.
InnoDB: To fix the problem and start mysqld:
InnoDB: 1) If there is a permission problem in the file and mysqld cannot
InnoDB: open the file, you should modify the permissions.
InnoDB: 2) If the table is not needed, or you can restore it from a backup,
InnoDB: then you can remove the .ibd file, and InnoDB will do a normal
InnoDB: crash recovery and ignore that table.
InnoDB: 3) If the file system or the disk is broken, and you cannot remove
InnoDB: the .ibd file, you can set innodb_force_recovery > 0 in my.cnf
InnoDB: and force InnoDB to continue crash recovery here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18018">issues.joomla.org/tracker/joomla-cms/18018</a>.</sub>

**Comment by ghost** [comment]
closing this Issue, please comment at #18020 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18018">issues.joomla.org/tracker/joomla-cms/18018</a>.</sub>
