### ISSUE TITLE
Netbeans autocomplete doesn't work on joomla 3.8

### ISSUE THREAD

**Issue by trananhmanh89** [joomla/joomla-cms#18014]
Netbeans 8.2 autocomplete doesn't work on joomla 3.8. 

With joomla 3.7 or lower, it's works fine. 

Any one got the same issue 😭 ?

**Comment by mbabker** [comment]
There are two options to help with IDE resolution.  As previously announced, the core libraries were namespaced and the old class names do not exist as real classes anymore, but are still accessible through aliasing.  The below scripts can be used to generate files to help your IDE correctly resolve the old class names.

- https://github.com/nikosdion/joomlatypehints
- https://github.com/joomla/joomla-cms/blob/staging/build/stubGenerator.php

**Comment by joomdonation** [comment]
@mbabker The subGenerator comes with Joomla core is not working. I made a PR https://github.com/joomla/joomla-cms/pull/17925 to fix it but the class name is still wrong (all class name are in lower case) as explained in the PR

I had to modify some code to get correct result. So if someone needs this option, get this zip file, unzip it and save it to the root folder of your Joomla installation and it will be OK
[stubs.zip](https://github.com/joomla/joomla-cms/files/1318053/stubs.zip)

**Comment by trananhmanh89** [comment]
Awesome 👍

**Comment by trananhmanh89** [comment]
Awesome 👍

**Comment by PhocaCz** [comment]
@joomdonation 

Hi Tuan, 

works great with Eclipse.

Thank you, Jan

**Comment by joomdonation** [comment]
I'm glad it helps :)

**Comment by rbuelund** [comment]
The zip file also worked in PHPStorm - BUT - getParams is still not getting recognized ??
		
                $app = JFactory::getApplication();
		// Load the parameters.
		$params = $app->getParams();

**Comment by mbabker** [comment]
The getParams method only exists on the site application class.  Since `JFactory::getApplication()` has a docblock that returns the base CMS application class, it won't exist in the autocomplete stuff unless you put an inline docblock in your code to force it to resolve.

```php
/** @var JApplicationSite|\Joomla\CMS\Application\SiteApplication $app */
$app = JFactory::getApplication();
$params = $app->getParams();
```

**Comment by rbuelund** [comment]
Ok - thank you !

**Comment by fishtime** [comment]
Hello.
I have  used the stubs.php file and most of issues gone but not all.
When I want to go at class definition file I use Ctrl+B in PhpStorm.
`JFactory::getApplication()` - opens Factory.php file
but `extends JPlugin` - opens stubs.php at line
`abstract class JPlugin extends \Joomla\CMS\Plugin\CMSPlugin {}`

**Comment by ghost** [comment]
@fishtime please open a new Issue as Comments on closed Threads didn't get much Notice.
