### ISSUE TITLE
Strange error with J3.8 update...

### ISSUE THREAD

**Issue by mikelawrey32** [joomla/joomla-cms#18013]
### Steps to reproduce the issue

Updated to J3.8 by unzipping the upgrade package in my root

### Expected result

Normal functionality with Joomla and my site

### Actual result

The update fubars my Joomla admin and my site gives a 500 error.  Ill attach a screenshot of what my Joomla admin looks like after the update... 

### System information (as much as possible)

Current version of J3.7.4
PHP5.6
Hostgator Shared hosting

### Additional comments

![screen shot 2017-09-20 at 14 06 46](https://issues.joomla.org/uploads/1/fd304e49f0efe97350e11d692148b51f.jpg)

**Comment by ghost** [comment]
can you please take a Look at #18003 if this Discussion help?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18013">issues.joomla.org/tracker/joomla-cms/18013</a>.</sub>

**Comment by classicpark** [comment]
Same problem here

https://issues.joomla.org/tracker/joomla-cms/18011<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18013">issues.joomla.org/tracker/joomla-cms/18013</a>.</sub>

**Comment by brianteeman** [comment]
@mikelawrey32 I wouldn't expect that to work. It is not the correct method to update.

**Comment by mbabker** [comment]
If you absolutely must upgrade without using the core update component, [these instructions](https://gist.github.com/mbabker/d7bfb4e1e2fbc6b7815a733607f89281) are the only reliable method to ensure the update is completed correctly.

**Comment by mikelawrey32** [comment]
It's certainly not the "method" in which I update to 3.8.  It also doesnt work when I try and upgrade in the Joomla admin update manager.

**Comment by saopaulosao** [comment]
My Problem >>>> https://github.com/joomla/joomla-cms/issues/18114
