### ISSUE TITLE
New router not working properly on Blog Title links

### ISSUE THREAD

**Issue by gwsdesk** [joomla/joomla-cms#18029]
https://gws-desk.com/gws-desk-blog-news?view=article&id=208:the-new-router-in-joomla-3-8-0 (This is a Blog entry Title link)

Options: Set to "experimental" with "remove id's"

Expected: Id is removed
Result: See above link

**Comment by gwsdesk** [comment]
This resolves if a 'hidden' menu item is created which links to the blog entry. https://gws-desk.com/new-router however I do not think this is the way how we should resolve this since this is equal to the 'old" router method and the removal of the id's should work<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18029">issues.joomla.org/tracker/joomla-cms/18029</a>.</sub>

**Comment by AlexRed** [comment]
I can confirm the problem with the orphan article: https://github.com/joomla/joomla-cms/issues/16496#issuecomment-306130719<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18029">issues.joomla.org/tracker/joomla-cms/18029</a>.</sub>

**Comment by ghost** [comment]
closed as duplicated Report. Thanks for Hint, @AlexRed <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18029">issues.joomla.org/tracker/joomla-cms/18029</a>.</sub>
