### ISSUE TITLE
After Update to 3.8: User can create article in category via front end without having the permission for the category

### ISSUE THREAD

**Issue by newagesamurai** [joomla/joomla-cms#18027]
### Steps to reproduce the issue
Create a usergroup with the permissions of a publisher
Create a user in this group
Create a Category and disallow all actions for this category to the created usergroup on the permissions tab.
Login to fron tend with the created user, open front end editor and select the category without permission for the created user / usergroup

### Expected result
Category should not be listed / selectable

### Actual result

Category is listed and can be selected and article can be saved

### Additional comments
Works fine with 3.7.5 after Update to 3.8 issues appears

**Comment by AlexRed** [comment]
I can confirm the problem, also in backend.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18027">issues.joomla.org/tracker/joomla-cms/18027</a>.</sub>

**Comment by ghost** [comment]
Status at Issue Tracker now "Confirmed".

**Comment by gitwpia** [comment]
Anybody solved the problem?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18027">issues.joomla.org/tracker/joomla-cms/18027</a>.</sub>

**Comment by ghost** [comment]
@gaijina if theres a Pull Request for trying to solve an Issue this Issue get closed and a Link to Pull Request for testing is shown.

**Comment by gitwpia** [comment]
Sorry I'm new here. This means that you know the problem but no one knows what to do about it. I have to wait for version 8.1 and then maybe it will be fine?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18027">issues.joomla.org/tracker/joomla-cms/18027</a>.</sub>

**Comment by ghost** [comment]
It means no Developer had time or willing to create a Pull Request.

More about reporting Bugs and Pull Request read please in the [Documentation](https://docs.joomla.org/Filing_bugs_and_issues).

**Comment by ggppdk** [comment]
This issue effects the specifically the top level categories
and also only the category themselves only, their descendants are excluded
please see the PR i made for more details

**Comment by zero-24** [comment]
Thanks @ggppdk closing as there is a PR.

**Comment by AlexRed** [comment]
sorry but where is the PR by ggppdk ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18027">issues.joomla.org/tracker/joomla-cms/18027</a>.</sub>

**Comment by AlexRed** [comment]
ok, I found it: https://issues.joomla.org/tracker/joomla-cms/18131<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18027">issues.joomla.org/tracker/joomla-cms/18027</a>.</sub>
