### ISSUE TITLE
Menu Item > Category Blog : filter by Tag does not (yet) allow Multiple Selection

### ISSUE THREAD

**Issue by woluweb** [joomla/joomla-cms#18021]
### Steps to reproduce the issue

Hi,
This is a feature request.
When you create a Menu Item > Category Blog, you can filter by Tag. Great.
But you can only select *1* Tag.
See screenshot.![screen shot 2017-09-20 at 20 11 51](https://issues.joomla.org/uploads/1/48ff9f42546bbe9df4b1c25039854126.png)

### Expected result

It would be nice to allow Multiple Selection for Tags.
The page would then show all the Articles having any of these Tags.

**Comment by ghost** [comment]
+1. @hans2103 can you extend?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18021">issues.joomla.org/tracker/joomla-cms/18021</a>.</sub>

**Comment by woluweb** [comment]
BTW, I don't want to push the suggestion too far, but there is also now (since 3.8) a Tag Filter in mod_article_category (https://github.com/joomla/joomla-cms/pull/16945).
So maybe it would make sense to also allow for Multiple Tags there, especially if the code is same/similar.

**Comment by hans2103** [comment]
The only thing I did on #16945 was to copy a piece of code from the menu logic to the module logic. 
I've copied ```$articles->setState('filter.tag', $params->get('filter_tag', ''));``` from the menu into the module. 

@franz-wohlkoenig feel free to make a PR changing this single select into a multi select. It's a nice feature indeed. I will try to do the same.

**Comment by ghost** [comment]
@hans2103 i thought you have coded the PR so i called you. As you see i'm no Developer ;-)

**Comment by brianteeman** [comment]
Closed as we have a PR #18234
