### ISSUE TITLE
HTTP ERROR 500 after updating joomla 3.8

### ISSUE THREAD

**Issue by SaidBa** [joomla/joomla-cms#18026]
Since i have updated to joomla 3.8 i cannot acces my joomla administrator (backend). I get the error:

HTTP ERROR 500

How can i fix this.

Please help.

### System information (as much as possible)
I am using the last version of PHP en MYSQL

### Additional comments
How to i solve this en can i make my backend accesseble

**Comment by brianteeman** [comment]
Duplicate of #18025

**Comment by SaidBa** [comment]
Yes, that is correct, but do you have a solution
