### ISSUE TITLE
[Regression] FTPClient broken

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#18024]
### Steps to reproduce the issue
I guess any extension using the FTPClient class is broken with J3.8.0.
I have an example one, but it needs an FTP account on the german DWD server. Unfortunately they don't give them out anymore since the service is going to shut down soon 😄 

### Expected result
Works

### Actual result
White page of death due to missing wrapper for "buffer"

### System information (as much as possible)
J3.8.0

### Additional comments
The failing code line is https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Client/FtpClient.php#L858:
`$tmp = fopen('buffer://tmp', 'br+');`

Since J3.8.0 it returns false.

The responsible PR is https://github.com/joomla/joomla-cms/pull/16934 which renamed JBuffer.
Thus pinging @laoneo 

According to Michael it worked before due to the way JLoader loads the classes into memory. With the namespaced classes and its autoloader, that is no longer the case and we need to somehow register the wrapper in a better way.

Adding `stream_wrapper_register('buffer', '\\Joomla\\CMS\\Utility\\BufferStreamHandler');` to the constructor of FtpClient did get it back to work, but I got a warning "stream_wrapper_register(): Protocol buffer:// is already defined." so that's not right.

**Comment by jpreville** [comment]
I can verify that i'm also getting the same error. On a couple plugins on my site. Is there a easy solution? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18024">issues.joomla.org/tracker/joomla-cms/18024</a>.</sub>

**Comment by Bakual** [comment]
Didn't try yet. I was to tired to look further 😀

**Comment by Bakual** [comment]
@jpreville You can add the line `new JBuffer;` to your code and it will work. Looks like a hack to me though.

**Comment by jpreville** [comment]
@Bakual Thank you for the reply. Exactly where do i try placing the 

stream_wrapper_register('buffer', '\\Joomla\\CMS\\Utility\\BufferStreamHandler');

in the FtpClient.php file?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18024">issues.joomla.org/tracker/joomla-cms/18024</a>.</sub>

**Comment by Bakual** [comment]
In the constructor or before the line I referenced in the issue description.

**Comment by laoneo** [comment]
Can you guys test #18060, does it fix the issue?

**Comment by ghost** [comment]
closed as having Pull Request #18060<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18024">issues.joomla.org/tracker/joomla-cms/18024</a>.</sub>
