### ISSUE TITLE
Error: 0 Call to undefined method JadminCssMenu::addChild

### ISSUE THREAD

**Issue by visualtribe** [joomla/joomla-cms#18022]
### Steps to reproduce the issue
Installed 3.8.0 over 3.7.5
after install admin menu visible, but everything below is now a white page.

### Expected result
Everything in back end works and can see all sections

### Actual result
menu only shown. Can't navigate as every page has a white page where contents would be
Browser page title says
Error: 0 Call to undefined method JadminCssMenu::addChild

### System information (as much as possible)
Joomla 3.7.5 initially.
PHP 7.0.23
Firefox 55.0.3

### Additional comments

Cleared previous site cookies
Cleared Firefox browser cache
Didn't work![screen shot 2017-09-20 at 21 01 46](https://issues.joomla.org/uploads/1/f767ce517291b688bc37b81701cf5e02.png)

**Comment by mbabker** [comment]
See https://docs.joomla.org/J3.x:Call_to_undefined_method_JAdminCssMenu::addChild_in_backend and the many issues opened already with this same message.
