### ISSUE TITLE
After Update to 3.8:site backend cannot open

### ISSUE THREAD

**Issue by mengxiangmengyuan** [joomla/joomla-cms#18034]
### Steps to reproduce the issue

from 3.7.5 update to 3.8, backend cannot open

### System information (as much as possible)

Error: 0 Call to undefined method JAdminCssMenu::addChild()

**Comment by ghost** [comment]
You need to update pagebuilder: https://www.joomshaper.com/forums/joomla-3-8

closed as duplicated Report #18028

**Comment by mengxiangmengyuan** [comment]
Thanks
