### ISSUE TITLE
Joomla 3.7.5 update to 3.8.0 does not match target host name

### ISSUE THREAD

**Issue by samuel1201** [joomla/joomla-cms#18037]
Hello everyone!

I try to update joomla 3.7.5 to 3.8.0 and i got a wrong message.

 **SSL: certificate subject name 'joomla-org.directrouter.com' does not match target host name 'downloads.joomla.org'**

I don't know how to fix it.

**Comment by wojsmol** [comment]
cc @mbabker

**Comment by wojsmol** [comment]
@mbabker Any idea on this error? We have at least 2 more cases on the forum.

**Comment by wojsmol** [comment]
@samuel1201 Please see [this](https://forum.joomla.org/viewtopic.php?p=3494187#p3494187) forum post and contact your hosting provider.

**Comment by ghost** [comment]
As there are similar Threads this is closed but can always reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18037">issues.joomla.org/tracker/joomla-cms/18037</a>.</sub>

**Comment by wojsmol** [comment]
There is other solution also.
