### ISSUE TITLE
Missing "Use global" on article options "Layout"

### ISSUE THREAD

**Issue by drmenzelit** [joomla/joomla-cms#18039]
Since the update to Joomla 3.8 I'm missing "Use global" on the options for alternative layout on articles. 

Looking on the database I found that new articles have this: "article_layout":"_:default" inside attribs. Old articles have "article_layout":""

The new function to select an alternative layout for articles inside the menu typ blog has also no "Use global". And because of the "wrong" article layout the function is not working as expected.

**Comment by tonypartridge** [comment]
Please test the pull request. Thank you!

**Comment by ghost** [comment]
closed as having Pull Request #18054<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18039">issues.joomla.org/tracker/joomla-cms/18039</a>.</sub>

**Comment by drmenzelit** [comment]
Thank you!!
