### ISSUE TITLE
[4.0] Remove redundant options for Media Manager

### ISSUE THREAD

**Issue by kasvith** [joomla/joomla-cms#18035]
### Steps to reproduce the issue
With the New Media Manager you don't really have a specific folder for **images** so the option that is related to this can be removed safely.

![image](https://user-images.githubusercontent.com/13379595/30685816-762a5256-9eb6-11e7-9433-0bedc016398b.png)

New implementation supports multiple folders up to unlimited numbers. 
![image](https://user-images.githubusercontent.com/13379595/30685840-8d604be2-9eb6-11e7-9304-e6a48b395a7c.png)

### Additional comments
Documentation changes might required

**Comment by brianteeman** [comment]
Can it really be removed safely? That would mean that any user who did not use the default would have to go into the plugin and apply the settings there. 
Also (and i might be wrong) but isnt the value of that option used in extensions - so simply removing it would be a hard bc break

**Comment by kasvith** [comment]
then we have to mark this as to be removed in future releases. we need to deprecate it because it is not used in Joomla! 4 Media Manager at all. People will get confused by this

**Comment by ghost** [comment]
@wilsonge as Release Lead on above Comment?

**Comment by laoneo** [comment]
I guess we can remove the files setting, don't know what this setting is for at all. The question is more where an extension should place it's images? If it is in /images/com_foo then we probably need to leave the images setting. If it should be /media/com_foo/images then we can remove images setting too.

**Comment by brianteeman** [comment]
Its not about where they should store the images in the future (or past) its about is the setting used by extensions now. If it is then we need a way to deprecate the setting AND a new way for extensions to reference it. 

For example if an extension is expecting to put files in images/com_foo but images is not "mounted" is that a problem?

**Comment by dgrammatiko** [comment]
> a new way for extensions to reference it.

This should be possible through the API something like get the com_media params. In essence every **local** adapter needs to save the relative path/folder to an array named eg `localPaths` 

> For example if an extension is expecting to put files in images/com_foo but images is not "mounted" is that a problem?

I think this will not work if the folder is not mounted

@laoneo @kasvith ??

**Comment by kasvith** [comment]
you can put whatever you want in images/com_foo, Local Adapter is like an interface, you can access any folder without it. Basically if someone uses these features we have lot of time to warn them and tell to use modern way.

**Comment by laoneo** [comment]
It can become a problem when the extension uses a media form field. It always shows only folders below the image setting folder (https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Form/Field/MediaField.php#L232). So we kind of need the images setting still intact and need to make sure that images is always mounted. Probably we need to serve the folder with that setting always when the media manager is opened trough a media form field.

**Comment by ghost** [comment]
@kasvith: according to @laoneo closing this Issue, please open a new one at https://github.com/joomla-projects/media-manager-improvement.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18035">issues.joomla.org/tracker/joomla-cms/18035</a>.</sub>

**Comment by laoneo** [comment]
This one can be left open, as we tried to get feedback what to do with the settings which do become obsolete with the new MM.

**Comment by brianteeman** [comment]
@laoneo reminder

**Comment by laoneo** [comment]
Guess we will not get much more feedback. Closing it.

**Comment by brianteeman** [comment]
So I hope it will be actioned now
