### ISSUE TITLE
Update/ / Install manager keeps old versions

### ISSUE THREAD

**Issue by kukwm** [joomla/joomla-cms#18033]
### Steps to reproduce the issue
1. I updated all 3rd party extensions on dev websites with Joomla 3.7.5
2. I upgraded to Joomla 3.8

### Expected result

That things works

### Actual result

1. Additional new entries in Component menu which are nonsens (e.g. JEvents with RussiantranslationForJEvents)
2. Joomla Help: do not work anymore - get: 404 URL invalid 
3. The Joomla installer/updater do not overwrite existing extensions anymore. It makes copies and in Manager view you see a new entry for each installation process.

### System information (as much as possible)

I tested this with Apache and Windows IIS 7.5, PHP 7.0.23 and 7.1.15. Always the same result.

### Additional comments

Sorry, I can't see that version 3.8 is stable. Do you will offer an update 3.7.6 which includes the security fixes only?

**Comment by ghost** [comment]
Thanks for reporting. As you can see there are other Reports on similar Issues and Maintainers are discussing how to solve them. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18033">issues.joomla.org/tracker/joomla-cms/18033</a>.</sub>

**Comment by ghost** [comment]
This Issue can always reopened if necessary. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18033">issues.joomla.org/tracker/joomla-cms/18033</a>.</sub>
