### ISSUE TITLE
Update Joomla 3.7.4 to 3.8.0: disabled field component is back

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#18046]
### Steps to reproduce the issue
Update a Joomla 3.7.4 version with the field component disabled to Joomla 3.8.0. After that the respective menu entries are back and when yo click on one of them you get  404 Component not found.

**Comment by mbabker** [comment]
Confirmed.

Probably something to do with the menu being more database driven and being less capable of filtering out disabled items for other components.

**Comment by n3t** [comment]
See PR #18134 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18046">issues.joomla.org/tracker/joomla-cms/18046</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #18134<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18046">issues.joomla.org/tracker/joomla-cms/18046</a>.</sub>
