### ISSUE TITLE
Menu Item Alias Issue - Cannot assign item

### ISSUE THREAD

**Issue by sparkktv** [joomla/joomla-cms#18045]
Unable to assign item to a menu item alias. It just opens up a Lightbox with the Menu again and will keep doing it over and over every time you hit edit or select.
![68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f38653361333333383636333731366637623037353030343962643532653336382e706e67](https://user-images.githubusercontent.com/23144931/30697169-03b893c2-9eac-11e7-9181-815715bcb9a6.png)
![68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f63353631636433343731666563313539616662353065656461636436393663612e706e67](https://user-images.githubusercontent.com/23144931/30697243-467b988a-9eac-11e7-9f0c-c642d6c18529.png)

This issue started with Joomla 3.8 and was working fine with Joomla 3.7.5

**Comment by ghost** [comment]
Can't confirm.

Test on Production-Site using 3.8 works as expected.

**Comment by simbus82** [comment]
You have to click "clear" and then select another item.

**Comment by CEWebDesign** [comment]
Is this extra click needed or can it be handled without clearing befor selecting another item?
Maybe pass issue to the UX-Team?

**Comment by ghost** [comment]
@CEWebDesign you can write a Feature Request to https://volunteers.joomla.org/teams/user-experience-working-group

Issue closed as expected Behaviour.

**Comment by CEWebDesign** [comment]
@franz-wohlkoenig Feature Request: It would be nice, comfortable and user friendly if the JUX would have an own github issue tracker.

**Comment by mbabker** [comment]
CMS issues belong on this tracker, regardless of the team "owning" it.

**Comment by ghost** [comment]
@mbabker thanks for Info, so @CEWebDesign please open a new Issue for the Feature Request.
