### ISSUE TITLE
Page breaks and read more not working

### ISSUE THREAD

**Issue by niklasalbin** [joomla/joomla-cms#18041]
### Steps to reproduce the issue
1. fresh installation
2. new article
3. insert read more
4. insert page break
5. navigate to article
6. click link to page break page in index

### Expected result
page shows up

### Actual result
404 error

### System information (as much as possible)
Litespeed 5.2.1
php 7.0.23
5.5.5-10.1.26-MariaDB
CentOS 7.3 (with Cpanel 66.0.23)
Safe Mode	Off
Open basedir	/home/user:/usr/lib/php:/usr/php4/lib/php:/usr/local/lib/php:/usr/local/php4/lib/php:/tmp
Display Errors	On
Short Open Tags	On
File Uploads	On
Magic Quotes	Off
Register Globals	Off
Output Buffering	Off
Session Save Path	/var/cpanel/php/sessions/ea3
Session Auto Start	0
XML Enabled	Yes
Zlib Enabled	Yes
Native ZIP Enabled	Yes
Disabled Functions	None
Multibyte String (mbstring) Enabled	Yes
Iconv Available	Yes
Mcrypt Enabled	Yes
Maximum Input Variables	1000
### Additional comments
Page break links work without read more, but not with read more (hr id="system-readmore"). Tested on a new clean Joomla 3.7.5 upgraded to 3.8 and on clean 3.8 installation.
Can observe the difference here:
http://gofardesign.uk/joomlatest/index.php/2-uncategorised/2-test-article-2 (without system-readmore)
http://gofardesign.uk/joomlatest/index.php/2-uncategorised/1-test-article (with system-readmore, page link not working)

Tested with and without SEO urls

**Comment by ghost** [comment]
closed as duplicate Report #17830<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18041">issues.joomla.org/tracker/joomla-cms/18041</a>.</sub>
