### ISSUE TITLE
Joomla 3.8 Frontend Session does not expire

### ISSUE THREAD

**Issue by nirovi** [joomla/joomla-cms#18040]
### Steps to reproduce the issue
I did a test with Joomla 3.8.0,
I set the session duration in configuration to 2 minutes,
I created a "manager" user and logged in with this user in frontend,
after 4 minutes, the super user user was no longer logged into administration, while the user manager was still logged in to the frontend.
It seems then that the frontend does not expire the session.

### Expected result

Session Frontend ends after 2 minutes

### Actual result

Frontend Session does not expire

### System information (as much as possible)

Joomla 3.8.0

### Additional comments

I have tested this results also with joomla 3.6.5 and joomla 3.7.5

**Comment by AlexRed** [comment]
I can confirm the problem in Joomla 3.8.0 and Joomla 3.7.5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18040">issues.joomla.org/tracker/joomla-cms/18040</a>.</sub>

**Comment by ghost** [comment]
Status on Issue Tracker set on "Confirmed".

Thanks for confirming @AlexRed <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18040">issues.joomla.org/tracker/joomla-cms/18040</a>.</sub>

**Comment by wilsonge** [comment]
I can't reproduce. I upgraded from 3.6.5 to 3.8.0, changed my session from 15 to 2 minutes, signed out and back in again, then waited about 30 because i got distracted. But when I came back to the admin panel, and went to a different page I was signed out.

**Comment by mbabker** [comment]
If you are on a frontend page that triggers the keepalive behavior (this can be seen in the page's source, look for `keepalive.js` being loaded), then it is expected that the session won't expire.  Joomla core commonly loads this on pages with form actions to avoid the possibility of the "invalid token" error message (if the session expires before you've submitted the form the token wouldn't be valid because the value is stored to the session for comparison).

**Comment by nirovi** [comment]
In my Frontend I don't have any Form actions.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18040">issues.joomla.org/tracker/joomla-cms/18040</a>.</sub>

**Comment by mbabker** [comment]
Cannot confirm.

Logged into https://downloads.joomla.org/ backend, set session time to two minutes.  Logged into the frontend, navigated to https://downloads.joomla.org/latest and verified that the keepalive behavior was not loaded.  Went and read some other stuff, came back about three minutes later and navigated to another page.  Checked the footer (we have some conditional code in our template that changes the "Log in" text to "Log out" when authenticated), I had been correctly logged out. 
 Navigating to the login page gave me the login form, not the log out button.

**Comment by AlexRed** [comment]
nirovi remember also the "login form" module is a form. Also if you are logged the login form is here.
If you use the login module in frontend the users session won't expire

**Comment by brianteeman** [comment]
Unable to reproduce

**Comment by ghost** [comment]
@nirovi any Updates on this Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18040">issues.joomla.org/tracker/joomla-cms/18040</a>.</sub>

**Comment by nirovi** [comment]
Hi, for me the problem is still there. The front end session does not expire. This is for me a security problem in case the logged user is a publisher. I have in all page a log out botton. But I did not find the keepalive function.  How Can I solve this behavour ?

The login module I'm using is : BT Login Module Version 2.6.1 BT

Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18040">issues.joomla.org/tracker/joomla-cms/18040</a>.</sub>

**Comment by alikon** [comment]
unpublish that  "BT Login Module Version 2.6.1 BT" module maybe is not compatible with 3.8
and use the core login module  in the meantime

**Comment by AlexRed** [comment]
also with the core login module the users session won't expire like explained by mbabker. All forms load the keepalive.js

**Comment by brianteeman** [comment]
Actually the BT Login Module does not support keepalive functionality - it does not have the line `JHtml::_('behavior.keepalive');
` ie it does not force the session not to expire

Also I use this module on a few sites. I can **not** confirm that this module is forcing the session not to expire.

So in conclusion your issue is not with the BT Login Module

**Comment by nirovi** [comment]
Perfect if is not this module, how can i find the keepalive module in my websiste?  

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18040">issues.joomla.org/tracker/joomla-cms/18040</a>.</sub>

**Comment by brianteeman** [comment]
You would need to read the code. OR try disabling all the modules one at a time. Either way it is not an issue with the core which is working correctly. I am closing this here. If you need further support please use the forum https://forum.joomla.org
