### ISSUE TITLE
HTTP ERROR 500 admin page after updating to Joomla 3.8

### ISSUE THREAD

**Issue by johnsk1978** [joomla/joomla-cms#18047]
Hi, I can't access joomla back end after updating to 3.8. 
 getting error HTTP ERROR 500 in google chrome
pls help

**Comment by MarketingApe** [comment]
I had same problem - updating is corrupting a table (jycbs_weblinks) and causing MySQL to crash.  Have your host company tech support check to see if InnoDB (and MySQL) is running.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18047">issues.joomla.org/tracker/joomla-cms/18047</a>.</sub>

**Comment by johnsk1978** [comment]
hi my front page is working fine , all pages loading without error, the only problem with admin

**Comment by ghost** [comment]
closed as duplicate Report #18025<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18047">issues.joomla.org/tracker/joomla-cms/18047</a>.</sub>

**Comment by wojsmol** [comment]
@johnsk1978 

0.  Make sure do you have a backup of your site (files and database).
1. Download [this](https://downloads.joomla.org/cms/joomla3/3-8-0/joomla_3-8-0-stable-full_package-zip?format=zip) package
2. Upload it to your site root and extract it  with file manager.
3. Remove installation folder.
4. Then use [this](https://gist.githubusercontent.com/mbabker/d7bfb4e1e2fbc6b7815a733607f89281/raw/4f8bd9cfd2c54f853ca99bae3033586a81f9f236/postupdate.php) file as described [here](https://gist.github.com/mbabker/d7bfb4e1e2fbc6b7815a733607f89281#file-readme-md).

**Comment by ghost** [comment]
@wojsmol can you please write above comment also in #18025 to get Information in one Place?

**Comment by wojsmol** [comment]
@franz-wohlkoenig Comment added as planed and requested.

**Comment by johnsk1978** [comment]
@wojsmol I did the way you said , but no result
I also tried mentioned here https://www.joomshaper.com/forums/joomla-3-8
still blank admin page

**Comment by wojsmol** [comment]
Please set `$error_raporting` to `maximum` in `configuration.php`.

**Comment by johnsk1978** [comment]
I did,  but no result

error getting after login to admin 

This page isn’t working
www.mysite.com is currently unable to handle this request.
HTTP ERROR 500

**Comment by wojsmol** [comment]
Check server logs and Joomla error.php in logs folder.

**Comment by cmirnow** [comment]
My site is very old (more than 2000 pages). After the upgrade from J3.7.5  to J3.8, several pages do not open, ERROR 500. Other pages work fine. Any ideas? Guys, I'm really surprised, the work of developers leave much to be desired. I was forced to roll back to the old version, J3.7.5.

**Comment by ghost** [comment]
@cmirnow can you please read and comment at #18020

**Comment by johnsk1978** [comment]
I rolled back to j3.7.5. I tried many ways, but couldn't fix. I am using flex template, may be a problem with template after reading https://themeforest.net/item/flex-multipurpose-joomla-template/14881156/comments. now waiting for their template update.

**Comment by kalimati** [comment]
In my case the frontend is functional after the upgrade. IN the backend /administrator page I am getting this error "Error: 0 Call to undefined method JAdminCssMenu::addChild()".
I am upgrading from 3.7.4.
Tried the manual method without success.
![screenshot from 2017-09-28 13-09-54](https://user-images.githubusercontent.com/5312453/30955151-472e39a0-a450-11e7-8d88-3dc682a9897b.png)

**Comment by ghost** [comment]
Please don't write same Question like [#18025](https://github.com/joomla/joomla-cms/issues/18025#issuecomment-332756357) in different Threads, thanks.

**Comment by gNesh01** [comment]
@wojsmol Thanks, this worked for me.

**Comment by chvdr** [comment]
Hi All,
Experienced with similar situation, the problem might be in content of the configuration.php file. 
Check for some copy-paste or butt error, e.g. if "</php class"  have symbol omitted or similar. 
Cheers,
Chavdar

**Comment by ShibumiDesign** [comment]
See this forum post: https://forum.joomla.org/viewtopic.php?t=860554#p3503601 - surprised this issue still isn't fixed in 3.8.11

**Comment by ghost** [comment]
@ShibumiDesign can you please open a new Issue as Comments on closed Issues didn't get much Notice, thanks.

**Comment by wojsmol** [comment]
@Hackwar Please see link posted by @ShibumiDesign - old bug in com_finder.

**Comment by ShibumiDesign** [comment]
@franz-wohlkoenig only posted as I experienced the same issue, and found this solution while searching, thought I would link to that forum post for anyone else searching this issue...
