### ISSUE TITLE
Redirect to Full Destination URL fails

### ISSUE THREAD

**Issue by acatterson** [joomla/joomla-cms#18050]
### Steps to reproduce the issue
Create redirect in Redirect Manager
Expired URL: http://www.domain.com/some-url
New URL: http://www.domain.com/some-new-url

### Expected result
Entering http://www.domain.com/some-url in the browser address bar causes a redirect to http://www.domain.com/some-new-url

### Actual result
Entering http://www.domain.com/some-url causes a redirect to http://www.domain.com/some-url/https://www.domain.com/some-new-url and throws a 404

### System information (as much as possible)
Joomla 3.8
PHP 7.0.23
Force SSL: Entire Site
Search Engine Friendly URLs: Yes
Use URL Rewriting: Yes
*******
htaccess:
RewriteEngine On
RewriteBase /
RewriteCond %{HTTP_HOST} ^domain.com [NC]
RewriteRule ^(.*)$ http://www.domain.com/$1 [L,R=301,NC]

### Additional comments
Workaround:

When New URL is set to just /some-new-url, it works.

Expired URL: https://www.domain.com/some-url
New URL: /some-new-url
Properly redirects to http://www.domain.com/some-new-url

I thought this was related to the 3.8 upgrade but it also happens on a few 3.7.5 websites that I've tested.

Is this expected behavior? 

Joomla's documentation states:
"The Source URL you specify when you create the redirect should be the full URL as you would type it in your web browser."
"The Destination URL you specify when you create a redirect must be the full URL as well."

**Comment by ghost** [comment]
closed as duplicate Report #17996<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18050">issues.joomla.org/tracker/joomla-cms/18050</a>.</sub>
