### ISSUE TITLE
Default Category Not Set

### ISSUE THREAD

**Issue by rgblogs** [joomla/joomla-cms#18059]
### Steps to reproduce the issue

1. In List of Articles, filter by any category.

2. Create New Article

### Expected result

The category field should be set to the one filtered (like as in previous Joomla versions)

### Actual result

Category field is blank.

**Comment by ghost** [comment]
Status set in Issue Tracker "Confirmed".

Result of above Test:
![bildschirmfoto 2017-09-22 um 10 46 45](https://user-images.githubusercontent.com/8235763/30736564-873299be-9f83-11e7-8d64-ac77235637e3.jpg)

**Comment by alikon** [comment]
duplicate of #17974

**Comment by infograf768** [comment]
Closing as duplicate
