### ISSUE TITLE
SQL errors in new fresh install 3.8.0

### ISSUE THREAD

**Issue by tormes** [joomla/joomla-cms#18056]
### Steps to reproduce the issue

Fresh new install of Joomla_3.8.0-Stable-Full_Package.zip on localhost
- Database Type: PostgreSQL
- Install Sample Data: None
- Pre-Installation Check: All Yes
- Recommended settings: All Ok
Finished OK with message "Congratulations! Joomla! is now installed."

The Administration site is OK. The front-site gives error at "Home" page
(As default the page "Home" is -->  Articles » Featured Articles)

ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list LINE 9: ORDER BY c.lft, a.featured DESC, fp.ordering, CASE WHEN a.p... ^

And after creating an Article with "Feature status", the error changes to:

ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list LINE 8: ORDER BY c.lft, CASE WHEN a.publish_up = '1970-01-01 00:00:... ^

If I change the "Home" to -->  Articles » Single Article, then the front-site is OK.

If I create a new category and configure "Home" to -->  Articles » Category Blog, then the front-site gives ERROR:

500 ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list LINE 8: ORDER BY c.lft, CASE WHEN a.publish_up = '1970-01-01 00:0... ^ 

### Expected result

In a new empty fresh install of 3.8.0 version:
Home configured as Articles » Single Article   OK
Home configured as Articles » Featured Articles  OK
Home configured as Articles » Category Blog  OK

### Actual result

In a new empty fresh install of 3.8.0 version:
Home configured as Articles » Single Article   OK
Home configured as Articles » Featured Articles  ERROR
Home configured as Articles » Category Blog  ERROR

### System information (as much as possible)

Fresh new install of Joomla_3.8.0-Stable-Full_Package.zip on:
- Apache 2.4.10 (Devuan) 
- PHP Version 5.6.30-0+deb8u1
- PostgreSQL 9.6.1
- No sample data, no extensions, no other languages, no templates

### Additional comments

May be it could be related to using PostgreSQL ?

**Comment by wojsmol** [comment]
@alikon @csthomas Please check this.
@tormes Issue is related to using PostgreSQL.

**Comment by tormes** [comment]
Using Joomla_3.7.5-Stable-Full_Package.zip on the same machine with the same stack, and doing the same steps, works OK.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18056">issues.joomla.org/tracker/joomla-cms/18056</a>.</sub>

**Comment by alikon** [comment]
look at #17891 , #17902

**Comment by ghost** [comment]
closed as duplicated Report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18056">issues.joomla.org/tracker/joomla-cms/18056</a>.</sub>

**Comment by ghost** [comment]
@tormes please test #17902

**Comment by tormes** [comment]
When I overwrite the file components/com_content/models/articles.php with the same file from @alikon (last commit of Pull Request #17902), all errors reported are fixed. Note that this file has another difference in line 270 from the original in 3.8.0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18056">issues.joomla.org/tracker/joomla-cms/18056</a>.</sub>
