### ISSUE TITLE
Tags Batch Processing Error

### ISSUE THREAD

**Issue by rgblogs** [joomla/joomla-cms#18057]
### Steps to reproduce the issue

1. Select Some Articles.

2. Batch process and add any tag to the articles

### Expected result

Tag should be added to the articles.

### Actual result

Getting Error:
Fatal error: Call to a member function setNewTags() on null in 

.../public_html/libraries/src/MVC/Model/AdminModel.php on line 635

**Comment by ghost** [comment]
Issue confirmed.
### System information
3.8.1-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by AndySDH** [comment]
Might be related to #18086

**Comment by ghost** [comment]
Relation set to #18086 at Issue Tracker. Thanks @AndySDH

**Comment by Quy** [comment]
Test PR #18328

**Comment by ghost** [comment]
closed as having Pull Request #18328
