### ISSUE TITLE
UX - Assign new item to an alias menu item without extra click "clear"

### ISSUE THREAD

**Issue by CEWebDesign** [joomla/joomla-cms#18058]
### Steps to reproduce the issue
Assign another item to an alias menu item without extra click "clear" #18045

### Expected result
Click on existing item to select another item

### Actual result
Need to click "clear" before selecting another item

**Comment by simbus82** [comment]
I see this "ux problem too". The clear button is not useful, for me this button has to open the modal with the menu item selection.

**Comment by infograf768** [comment]
Lazy folks... :smiley:

**Comment by CEWebDesign** [comment]
That's why you find the UX-Team at the beach in the sun ;)

**Comment by brianteeman** [comment]
I am closing this here. To me it seems correct as it is but you can raise it with the UX team here https://github.com/joomla/joomla-ux/issues
