### ISSUE TITLE
Allow setting access levels on admin menu items?

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#18053]
I have to create 5 different menu blocks and menu modules and set access levels on these when I'm only removing 1 or two items. 

Is there any specific reason we are not loading in the access level? This can be done just to build the menu block. We don't need it for ItemID for params etc. It's merely on building the menu block...

**Comment by ghost** [comment]
theres a Thread which i don't find now where @infograf768 and @izharaazmi discuss ACL in Backend-Menu.

**Comment by infograf768** [comment]
Here I guess
https://github.com/joomla/joomla-cms/issues/18000

**Comment by brianteeman** [comment]
@tonypartridge do you need it - you can set access to the component through its own acl. Thats what I have been doing

**Comment by tonypartridge** [comment]
@brianteeman I think so, you can’t add options to the items so you have to create external URLs types. Thus there is no way to restrict this display? Whereas having the control on the menu item allows it to work quickly and easily.

**Comment by Quy** [comment]
Duplicate #17162

**Comment by ghost** [comment]
closed as duplicate Report #17162

Thanks for Hint @Quy
