### ISSUE TITLE
[com_fields] Missing markup for required attribute

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#18067]
### Steps to reproduce the issue
Create a custom field of colour that is required.
Edit an article.
View source code.
Search for `"hue"1`.

### Expected result
Either add required attribute or remove 1.

### Actual result

`<input type="text" name="jform[com_fields][colour]" id="jform_com_fields_colour" value="none"  placeholder="#rrggbb" class="minicolors required" data-position="default" data-control="hue"1 data-format="hex" data-validate="color"/>`

### System information (as much as possible)
v3.8

**Comment by ghost** [comment]
Issue confirmed.

Test as given above opened an Article in Backend and looked in Source Code.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18067">issues.joomla.org/tracker/joomla-cms/18067</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a PR #18239
