### ISSUE TITLE
User profile form is prepated twice in frontend.

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#18065]
### Steps to reproduce the issue

debug `FieldsHelper::prepareForm()` and see that it's launched twice in frontend:

Initially via `PlgSystemFields->onContentPrepareForm` event and see that it's launched twice in frontend.

Next `FieldsHelper::prepareForm()` is called again via `UsersModelProfile::getForm()`

### Expected result

`FieldsHelper::prepareForm()` should be called once on user profile form display.

### Actual result

Called twice

### Additional comments

I guess frontend `UsersModelProfile::getForm()` should not call `FieldsHelper::prepareForm()` because it's already applied via `PlgSystemFields`.

**Comment by ghost** [comment]
can you please look if #18016 is similar?

**Comment by ggppdk** [comment]
@franz-wohlkoenig 

this concerns forms , it should be a different issue

**Comment by ghost** [comment]
@ggppdk thanks for Info.

**Comment by vladimir179** [comment]
@Denitz[xmovies8](https://xmovies8.biz "") thanks for the concern, it will help me a lot.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18065">issues.joomla.org/tracker/joomla-cms/18065</a>.</sub>

**Comment by alikon** [comment]
please ban @vladimir179

**Comment by ghost** [comment]
closed as having Pull Request #18065<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18065">issues.joomla.org/tracker/joomla-cms/18065</a>.</sub>
