### ISSUE TITLE
3.7.6 to 3.8 404 error to /administrator

### ISSUE THREAD

**Issue by Wytchcat** [joomla/joomla-cms#18069]
[Affected Site](http://offgridwildernessliving.com/administrator "Affected Site")

### Steps to reproduce the issue
Upgrade site from 3.7.6 to 3.8
php 7.0
Warp 7 template framework

### Expected result
standard admin login @ /administrator

### Actual result
404 error

### System information (as much as possible)
Godaddy shared hosting
Add-on domain in sub directory
7.0 php
Warp 7 Yootheme
Akeeba Backup Core
Jce Pro latst
RSFirewall 2.11.19
Zoo 3.3.26
Widgetkit 2 2.2.11
Zoolanders 3.3.26 w/Zoomailing
AcyMailer 5.8.0
Several other 3rd party
Permissions all correct
.htaccess removed and version from 3.8 used

### Additional comments
This was probably a 3.4.x or 3.5.x original install with regular updates
Update via conventional method and completed. 
Attempts to run postupdate.php unsuccessful due to 404.
Tried to manually re update with latest full stable version (again). When postupdate.php run with installation folder present gave too many redirects error with the URL reading:
offgridwildernessliving.com/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/installation/index.php

**Comment by wojsmol** [comment]
@Wytchcat 

0.  Make sure you have a backup of your site (files and database).
1. Download [this](https://downloads.joomla.org/cms/joomla3/3-8-0/joomla_3-8-0-stable-full_package-zip?format=zip) package
2. Upload it to your site root and extract it  with file manager.
3. Remove installation folder.
4. Remove /libraries/joomla/version.php
5. Then use [this](https://gist.githubusercontent.com/mbabker/d7bfb4e1e2fbc6b7815a733607f89281/raw/4f8bd9cfd2c54f853ca99bae3033586a81f9f236/postupdate.php) file as described [here](https://gist.github.com/mbabker/d7bfb4e1e2fbc6b7815a733607f89281#file-readme-md).

**Comment by Wytchcat** [comment]
Unless that package has changed in the last 5 hours already did that before submitting.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18069">issues.joomla.org/tracker/joomla-cms/18069</a>.</sub>

**Comment by wojsmol** [comment]
See points 3 and 4

**Comment by Wytchcat** [comment]
Yes.. I know. 

no version.php and /postupdate.php won't run due to 404
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18069">issues.joomla.org/tracker/joomla-cms/18069</a>.</sub>

**Comment by mbabker** [comment]
Your administrator directory is actually present, right?  As well, the `administrator/index.php` file?  The only reasons that should (sanely) 404 is a server configuration issue (permissions, not being able to execute PHP, or something along those lines) or the file actually be missing.

**Comment by wojsmol** [comment]
@mbabker See Affected Site /administrator is displaying.

**Comment by Wytchcat** [comment]
Present and accounted for...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18069">issues.joomla.org/tracker/joomla-cms/18069</a>.</sub>

**Comment by mbabker** [comment]
I do tech support, sometimes that includes asking obvious questions just to make sure things are right.  Carry on then.

**Comment by Wytchcat** [comment]
@mbabker Understood. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18069">issues.joomla.org/tracker/joomla-cms/18069</a>.</sub>

**Comment by wojsmol** [comment]
@Wytchcat on this site you have 3.7.5 not 3.8.0 files

**Comment by Wytchcat** [comment]
Check again..now it gives me a google "Dangerous Site" warning.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18069">issues.joomla.org/tracker/joomla-cms/18069</a>.</sub>

**Comment by Wytchcat** [comment]
Same site files without the warning http://offgridwildernessliving.net/administrator
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18069">issues.joomla.org/tracker/joomla-cms/18069</a>.</sub>

**Comment by Wytchcat** [comment]
on clearing settings.. now it's a 500 error Application Instantiation Error
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18069">issues.joomla.org/tracker/joomla-cms/18069</a>.</sub>

**Comment by wojsmol** [comment]
Now /administrator is working for me.

**Comment by Wytchcat** [comment]
I'm still getting 404

**Comment by wojsmol** [comment]
both http://www.offgridwildernessliving.com/administrator/ and http://offgridwildernessliving.com/administrator/ are working from my location - tested on Mozilla Firefox.

**Comment by Wytchcat** [comment]
Try it without the www. (which gives me a phishing warning suddenly)

**Comment by wojsmol** [comment]
Check if both domain version points to the same IP and folder on the server.

**Comment by Wytchcat** [comment]
Yes they do...404 in Chrome, FF and IE

**Comment by wojsmol** [comment]
/administrator/ working for me - "Dangerous Site" warning.confirmed now.

**Comment by Wytchcat** [comment]
I am assuming the Dangerous is coming from the postupdate.php script... since removed. 

Still 404's across the board for me on this

**Comment by wojsmol** [comment]
If you wont I can attach a screenshot.

**Comment by Wytchcat** [comment]
I believe you ... just unable to replicate it on two computers and 3
browsers

**Comment by wojsmol** [comment]
Do ping from command line an compare with dns setting.

**Comment by Wytchcat** [comment]
Correct IP.  3 time outs before results

**Comment by wojsmol** [comment]
Unfortunately, my ideas are over. The problem is very strange. Try contacting the hosting support.

**Comment by Wytchcat** [comment]
They won't deal with it as it is a CMS issue not a hosting problem. 

To say nothing of advising someone to contact Godaddy support is like saying... "give up, it's over"

**Comment by Wytchcat** [comment]
@wojsmol If you are able to get to the backend logging screen. I will reinsert the postupdate.php if you will run it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18069">issues.joomla.org/tracker/joomla-cms/18069</a>.</sub>

**Comment by wojsmol** [comment]
ok

**Comment by Wytchcat** [comment]
k.. have at it
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18069">issues.joomla.org/tracker/joomla-cms/18069</a>.</sub>

**Comment by wojsmol** [comment]
> Update to 3.8.0 completed successfully. 

on http://offgridwildernessliving.com/

**Comment by Wytchcat** [comment]
thanks... sadly... still no love after a complete shut down, cache clearing and reboot.

**Comment by Wytchcat** [comment]
Issue resolved. IP blocked by host (and I didn't have to call to work it out, thank goodness.)
