### ISSUE TITLE
site inaccessible after Upgrade

### ISSUE THREAD

**Issue by kirancheema** [joomla/joomla-cms#18073]
### Steps to reproduce the issue

Hi Guys 

attempted to update a joomla site to 3.8 and have encountered the following issue. 

After Update the Front and back end of the site are inaccessible 

Message displaying :
Fatal error: Call to undefined method JProfiler::setStart() in C:\Path to site\index.php on line 43 

Last few entries from the logs\joomla_update.php 

2017-01-13T08:56:15+00:00	INFO 10.162.210.79	update	Ran query from file 3.6.0-2016-06-05. Query text: ALTER TABLE `#__languages` ADD COLUMN `asset_id` INT(11) NOT NULL AFTER `lang_id.
2017-01-13T08:56:15+00:00	INFO 10.162.210.79	update	Ran query from file 3.6.3-2016-08-15. Query text: ALTER TABLE `#__newsfeeds` MODIFY `link` VARCHAR(2048) NOT NULL;.
2017-01-13T08:56:15+00:00	INFO 10.162.210.79	update	Ran query from file 3.6.3-2016-08-16. Query text: INSERT INTO `#__postinstall_messages` (`extension_id`, `title_key`, `description.
2017-01-13T08:56:15+00:00	INFO 10.162.210.79	update	Deleting removed files and folders.
2017-01-13T08:56:22+00:00	INFO 10.162.210.79	update	Cleaning up after installation.
2017-01-13T08:56:22+00:00	INFO 10.162.210.79	update	Update to version 3.6.5 is complete.
2017-09-21T19:18:50+00:00	INFO 2.123.118.88	update	Update started by user Super User (784). Old version is 3.4.8.
2017-09-21T19:18:50+00:00	INFO 2.123.118.88	update	Downloading update file from https://downloads.joomla.org/cms/joomla3/3-8-0/Joomla_3.8.0-Stable-Update_Package.zip.
2017-09-21T19:18:56+00:00	INFO 2.123.118.88	update	File Joomla_3.8.0-Stable-Update_Package.zip successfully downloaded.
2017-09-21T19:18:56+00:00	INFO 2.123.118.88	update	Starting installation of new version.

Weirdly in the Schema table is the following 
          
extension_id:700
version_id:3.6.3-2016-08-16
       
don't know if that's related or not but was interesting 

any recovery help and advice greatfully received. 

Totally get that we should have done all the incremental updates as they came out but we didn't and now its broke.

greatful for any advice

**Comment by ghost** [comment]
have you read at https://issues.joomla.org/tracker/joomla-cms for Threads (marked red als "Critical") for different Solutions?

**Comment by wojsmol** [comment]
@kirancheema 

0.  Make sure you have a backup of your site (files and database).
1. Download [this](https://downloads.joomla.org/cms/joomla3/3-8-0/joomla_3-8-0-stable-full_package-zip?format=zip) package
2. Upload it to your site root and extract it  with file manager.
3. Remove installation folder.
4. Remove if exists 
- /libraries/cms/version/ folder
- /includes/version.php
- /libraries/version.php
- /libraries/joomla/version.php
5. Then use [this](https://gist.githubusercontent.com/mbabker/d7bfb4e1e2fbc6b7815a733607f89281/raw/4f8bd9cfd2c54f853ca99bae3033586a81f9f236/postupdate.php) file as described [here](https://gist.github.com/mbabker/d7bfb4e1e2fbc6b7815a733607f89281#file-readme-md).

**Comment by kirancheema** [comment]
@franz-wohlkoenig thanks we did check for similar issues the only one found was https://issues.joomla.org/tracker/joomla-cms/18064 - but that didn't have a resolution and seems to be a different issue . Will try the suggestion from @wojsmol :- we had started that but han't clocked the Manual update and Version files so thanks for those tips. 

Will try that and report back <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18073">issues.joomla.org/tracker/joomla-cms/18073</a>.</sub>

**Comment by ghost** [comment]
@kirancheema any News on this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18073">issues.joomla.org/tracker/joomla-cms/18073</a>.</sub>

**Comment by ed-hum** [comment]
I tried updating the site using the update button in the admin area, and also the manual method. Both of them were giving 500 error on both front-end and back-end. 

Fixed the issue by renaming the libraries folder to libraries_old, and bringing across the libraries folder from a fresh 3.8 installation. 

Hope this helps :)

**Comment by wojsmol** [comment]
@ed-hum Please open new topic in https://forum.joomla.org/viewforum.php?f=710 because Joomla! update is not just file changes.

**Comment by ghost** [comment]
closed due th lack of Response. Issue can always be reopen.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18073">issues.joomla.org/tracker/joomla-cms/18073</a>.</sub>

**Comment by kirancheema** [comment]
Hi Guys 
@franz-wohlkoenig have tried the above and it hasn't worked. 

cloned files and Database to separate server. 
Did the steps above 
No change : 

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.


C:\inetpub\....Mypath....\administrator>php postupdate.php
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\Program Files\PHP\
v7.0\ext\php_mysql.dll' - The specified module could not be found.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\Program Files\PHP\
v7.0\ext\php_pdo_sqlsrv_7_ts_x64.dll' - The specified module could not be found.

 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\Program Files\PHP\
v7.0\ext\php_sqlsrv_7_nts_x86.dll' - %1 is not a valid Win32 application.
 in Unknown on line 0
PHP Notice:  Undefined index: HTTP_HOST in C:\inetpub\Mypath\site\libraries\joomla\application\web.php on line 869

Notice: Undefined index: HTTP_HOST in C:\inetpub\Mypath\site\libraries\joomla\application\web.php on line 869
PHP Warning:  session_start(): Cannot send session cookie - headers already sent
 by (output started at C:\inetpub\Mypath\site\libraries\j
oomla\application\web.php:869) in C:\inetpub\Mypath\site\
libraries\joomla\session\session.php on line 651

Warning: session_start(): Cannot send session cookie - headers already sent by (
output started at C:\inetpub\Mypath\site\libraries\joomla
\application\web.php:869) in C:\inetpub\Mypath\site\libra
ries\joomla\session\session.php on line 651
PHP Warning:  session_start(): Cannot send session cache limiter - headers alrea
dy sent (output started at C:\inetpub\Mypath\site\librari
es\joomla\application\web.php:869) in C:\inetpub\Mypath\site\libraries\joomla\session\session.php on line 651

Warning: session_start(): Cannot send session cache limiter - headers already se
nt (output started at C:\inetpub\Mypath\site\libraries\jo
omla\application\web.php:869) in C:\inetpub\wwwroot\Mypath\site\l
ibraries\joomla\session\session.php on line 651
PHP Notice:  Undefined index: HTTP_HOST in C:\inetpub\wwwroot\Mypath\site\libraries\joomla\uri\uri.php on line 96

Notice: Undefined index: HTTP_HOST in C:\inetpub\wwwroot\Mypath\site\libraries\joomla\uri\uri.php on line 96
PHP Notice:  Constant _QQ_ already defined in C:\inetpub\wwwroot\Mypath\site\libraries\src\Language\Language.php on line 18

Notice: Constant _QQ_ already defined in C:\inetpub\wwwroot\Mypath\site\libraries\src\Language\Language.php on line 18
PHP Warning:  strstr() expects parameter 1 to be string, object given in C:\inet
pub\wwwroot\Mypath\site\libraries\joomla\cache\controller\callback.php on line 64

Warning: strstr() expects parameter 1 to be string, object given in C:\inetpub\w
wwroot\Mypath\site\libraries\joomla\cache\controller\callback.php
 on line 64
PHP Warning:  strstr() expects parameter 1 to be string, object given in C:\inet
pub\wwwroot\Mypath\site\libraries\joomla\cache\controller\callback.php on line 70

Warning: strstr() expects parameter 1 to be string, object given in C:\inetpub\w
wwroot\Mypath\site\libraries\joomla\cache\controller\callback.php
 on line 70
Update to 3.8.0 completed successfully.

C:\inetpub\wwwroot\Mypath\site\administrator>

Going to try a few other things ..<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18073">issues.joomla.org/tracker/joomla-cms/18073</a>.</sub>

**Comment by wojsmol** [comment]
@kirancheema Please open topic in https://forum.joomla.org/viewforum.php?f=710

**Comment by RustyIngles** [comment]
@wojsmol your fix worked perfectly! Thank you!
