### ISSUE TITLE
New Routing System: Remove IDs from URLs breaks links to images with names like -imagename.jpg

### ISSUE THREAD

**Issue by zluzunov** [joomla/joomla-cms#18070]
### Steps to reproduce the issue
- Enable **Experimental URL Routing** and **Remove IDs** for Articles, Contacts, News Feeds, and Users;
- Use an image with name corresponding to the pattern "_number_-imagename.jpg", e.g. "6-cats.jpg" in a custom HTML module or an article. The image can be also references in a css style of the template;

### Expected result
Images should load without problems.

### Actual result
Images do not load - browsers report them as missing.

### System information (as much as possible)
- Joomla 3.8.0
- [phpinfo().zip](https://github.com/joomla/joomla-cms/files/1324826/phpinfo.zip)

### Additional comments
Fix: rename the images and change the URLs to them;

**Comment by mbabker** [comment]
Images shouldn't be going through the routing system at all.  @Hackwar any ideas here?

**Comment by Bakual** [comment]
@mbabker The SEF plugin may play a role here? It does all kind of funny things 😄

**Comment by Gitjk** [comment]
Can't confirm that behavior with my local J3.8.0 installation. Created and inserted an image file named 6-cats.jpg. It loads in an article and also in a custom module, both with 'Remove IDs from URLs' enabled/disabled using the new router.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18070">issues.joomla.org/tracker/joomla-cms/18070</a>.</sub>

**Comment by zluzunov** [comment]
Could be an issue with the template framework. I Will try to reproduce in a new installation on the same server, without extensions and template and report here. 
Some more info:
- The template uses this framework [YJ Simple Grid](https://yjsimplegrid.com/) 
- links are relative:
- Custom HTML module uses template framework
```
<p><em>[yjsgimgs image="images/00home/10-Soil-Cut-x700.jpg" class="radiusb10" title="Field practice 1" link="" target="" effect="none"]</em></p>
<p><em>[yjsgimgs image="images/00home/6-Cut-x700.jpg" class="radiusb10" title="Field practice 1" link="" target="" effect="none"]</em></p>
```
- CSS code that did not load properly:
```
/*Baseline intro*/
.baseline-intro {
	color: #fff;
	background: url(../images/home/10-Soilx1024.jpg) no-repeat center center fixed; 
	-webkit-background-size: cover;
	-moz-background-size: cover;
	background-size: cover;
}
```

**Comment by zluzunov** [comment]
Blushing - tested, my error, I am sorry about the spam. 
Forgotten redirection rule in the htaccess. I will test twice before reporting next time.
Thank you for your time!
