### ISSUE TITLE
Array to string conversion error in admin fields helper line 330

### ISSUE THREAD

**Issue by gaelicwinter** [joomla/joomla-cms#18078]
### Steps to reproduce the issue
1. New 3.8.0 installation, no test data
2. In Global Config, turn on maximum error messages
3. Create a category, call it 'Test'
4. Create custom field and assign it to the category 'Test'
5. Go to Articles, set the list filter to filter on Category 'Test'
6. Click New Article, get error  

	Notice: Array to string conversion in C:\xampp7\htdocs\test\administrator\components\com_fields\helpers\fields.php on line 330

### Actual result
Error as stated

### System information (as much as possible)
Both live Siteground host and local xampp.
PHP7
J3.8.0

### Additional comments
The error happens because the Category Filter dropdown has changed to multiselect, so in my example, the field helper is given an array of cat id's instead of a single cat id to work with.  The New Article form tries to load custom fields for the specified category but its now an array of one or more catid's instead of just a single catid.

My suggestion would be to check the incoming catid for an array and if found, to just use the first catid.

**Comment by gaelicwinter** [comment]
$assignedCatids = isset($data->catid) ? $data->catid : (isset($data->fieldscatid) ? $data->fieldscatid : $form->getValue('catid'));

		if(is_array($assignedCatids))
		{
			$assignedCatids = $assignedCatids[0];
		}

**Comment by gaelicwinter** [comment]
reopened

**Comment by ggppdk** [comment]
Same as #17974

**Comment by ghost** [comment]
closed as duplicated Report #17974. Thanks for Hint @ggppdk <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18078">issues.joomla.org/tracker/joomla-cms/18078</a>.</sub>
