### ISSUE TITLE
3.7.6 to 3.8 update: 'img srcset' url get a second slash in the beginning of the path

### ISSUE THREAD

**Issue by springob** [joomla/joomla-cms#18077]
using the following HTML code in articles and modules
&lt;img src="/imgages/..." srcset="/imgages/...">
will output the webpage:
&lt;img src="/imgages/..." srcset="//imgages/...">
(see the second slash in the srcset attribute!)

This is new...

Workaround:
&lt;img src="/imgages/..." srcset="imgages/...">
will output:
&lt;img src="/imgages/..." srcset="/imgages/...">

**Comment by mbabker** [comment]
Fixed by https://github.com/joomla/joomla-cms/pull/17978
