### ISSUE TITLE
sef.php adding protocol // to relative url's.

### ISSUE THREAD

**Issue by phooka** [joomla/joomla-cms#18074]
### Steps to reproduce the issue
Relative URLs in srcset images have // prefixed

Images in srcset are created like so:
   srcset="//index.php?p=theme...
instead of
   srcset="/index.php?p=theme...

Fix is to modify /plugins/system/sef/sef.php line 144
  $data[] = preg_replace('#(?!/|' . $protocols . '|\#|\')([^\s]+)\s+(.*)#', $base . '$1 $2', $url);
replace with
  $data[] = preg_replace('#^(?!/|' . $protocols . '|\#|\')([^\s]+)\s+(.*)#', $base . '$1 $2', $url);

**Comment by ggppdk** [comment]
Hi @phooka 

if you search for 'srcset' you find several other issues

and also a merged PR with 3.8.1 milestone
https://github.com/joomla/joomla-cms/pull/17978
