### ISSUE TITLE
3.7.6 to 3.8 /administrator redirects to home

### ISSUE THREAD

**Issue by Wytchcat** [joomla/joomla-cms#18071]
2 sites affected.

### Steps to reproduce the issue
Upgrade 3.7.6 to 3.8 via Joomla updater

### Expected result
standard login @ /administrator

### Actual result
redirected to frontend HOME

### System information (as much as possible)
Add-on domaians godaddy shared hosting
PHP 7.0
One Yootheme Pro 1.9.7 with Yootheme's current 3.8 code correction
One Yootheme Warp 7
Multiple 3rd party extensions

### Additional comments
On upgrade .htaccess was gone. changed htaccess.txt to correct 406 errors to come to this dilemma.

Interestingly, Yootheme Pro site shows the url ending: /index.php after redirect while the Warp 7 theme still shows the /administrator while displaying the frontend homepage.

**Comment by Wytchcat** [comment]
Sites affected:

[Yootheme Pro v1.9.7](http://carmenrodriguez.com "Yootheme Pro")
[Warp 7 theme](http://bellagoestothemovies.com "Warp 7 theme")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18071">issues.joomla.org/tracker/joomla-cms/18071</a>.</sub>

**Comment by ghost** [comment]
is this Issue same like #18069?

**Comment by Wytchcat** [comment]
Possibly? the above gives a 404 error vs just redirecting to the front end.

Separate domains, installs and behavior so started a different tracker

**Comment by wojsmol** [comment]
@Wytchcat 
Yootheme Pro v1.9.7 site - wrong or expired domain.
Warp 7 theme - any security or seo extension there?

**Comment by Wytchcat** [comment]
RS Firewall on both

**Comment by Wytchcat** [comment]
All three sites are hosted on same shared hosting as add-ons.

These are in a separate directories. All DNS settings from both domain and hosting sides checked

**Comment by Wytchcat** [comment]
@wojsmol If you are able to get to the backend logging screen. I will reinsert the postupdate.php if you will run it.

**Comment by Wytchcat** [comment]
Behavior caused by IP being blocked by host due to multiple connections.
