### ISSUE TITLE
FrontEnd: Error displaying the error page after upgrading from 3.7.5 to 3.8 Backend: Error displaying the error page

### ISSUE THREAD

**Issue by ltraveler** [joomla/joomla-cms#18089]
### Steps to reproduce the issue

I am trying to open my home page after upgrade

### Expected result

Home page

### Actual result
Error displaying the error page

### System information (as much as possible)
The error in my Apache log is: 
PHP Fatal error:  Call to a member function getTag() on null in /*/*/*/libraries/src/Application/SiteApplication.php on line 463

This is the part with 463 stroke:
`
		{
			$tag = $this->getLanguage()->getTag();
		}
`
I fixed this error changing this stroke to
`
$tag = '';
`
But looks like this is not a problem. So I don't know where to look for an error. Please help me.
### Additional comments
I already used the method of downloading full package of Joomla 3.8 and using postupdate.php script during this operation I've got this message:

> PHP Notice:  Undefined index: HTTP_HOST in ***/public_html/libraries/src/Uri/Uri.php on line 101
> Update to 3.8.0 completed successfully.
> 

When I am calling index.php from the console I am getting this errors:

> php index.php
> PHP Notice:  Undefined index: REMOTE_ADDR in ***/libraries/fof30/Utils/Ip.php on line 487
> PHP Notice:  Undefined index: REMOTE_ADDR in ***/libraries/fof30/Utils/Ip.php on line 383
> PHP Notice:  Undefined index: HTTP_HOST in ***/libraries/src/Uri/Uri.php on line 101
> PHP Notice:  Undefined index: REQUEST_METHOD in ***/plugins/system/admintools/feature/wafblacklist.php on line 33
> Error displaying the error page

I switched off AdminTools using PhpMyAdmin. So after that I have just this error:

> php index.php
> PHP Notice:  Undefined index: HTTP_HOST in ***/libraries/src/Uri/Uri.php on line 101
> Error displaying the error page

For the backend the errors in console are the same.

My website doesn't work at at all. not frontend not even backend

**Comment by wojsmol** [comment]
Check page source in the browser. I have a case when additional php errors was shown at the bottom of the generated page source.

**Comment by tonypartridge** [comment]
What version oh PHP are you using? Have you disabled non core plugins?

**Comment by ltraveler** [comment]
I fixed the problem by switching on display_errors parameter in my php.info.
So after that I saw an error:

> Fatal error: Call to a member function getTag() on null in ***/libraries/src/Application/SiteApplication.php on line 463

So I disabled cache. But if I am enabling it I am getting at error on my backend:
Unable to load Cache Storage: vmfile

But I need cache. Can you please help me to find the reason of that error?..
In system configuration I can see only one option for handling cache it's "file"

**Comment by ltraveler** [comment]
@tonypa

**Comment by ltraveler** [comment]
@tonypartridge the phpvesion is 5.6.29

**Comment by ltraveler** [comment]
If the cache is enabled when I am trying to clean the cache I am getting en error:

> 500 Could not read the cache data, the configured cache handler is not supported by this environment. Could not read the cache data, the configured cache handler is not supported by this environment. Could not read the cache data, the configured cache handler is not supported by this environment.

**Comment by ltraveler** [comment]
Ok. I changed 	public $cache_handler = 'vmfile';
to
	public $cache_handler = 'file';

and that solved the problem

Looks like some kind of conflict between Virtue Mart and Joomla 3.8

**Comment by ghost** [comment]
closed as Issue solved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18089">issues.joomla.org/tracker/joomla-cms/18089</a>.</sub>
