### ISSUE TITLE
[Regression] [3.8] Articles don't use default layout set in component

### ISSUE THREAD

**Issue by makermann** [joomla/joomla-cms#18083]
### Steps to reproduce the issue
1. Install Joomla 3.7.5 (last version before update to 3.8.0)
2. Create a template with two layouts for articles (lets call them a and b) and set this up in joomla
3. Set b as the default layout in Global configuration -> articles -> choose layout
4. Create articles and menu-items, do not create a menu-item for one article A1 

Preliminary result: All articles use b as their layout, since it is the default option set in the component

5. Update to 3.8.0

Preliminary result: All articles still use b as their layout

7. Now create a menu-item for the article A1

Result: All articles use layout a as their layout, although b is set as default in the component

### Expected result
Result: All articles use b as their layout, since it is the default option set in the component

### Actual result
See above.

### System information (as much as possible)
Joomla 3.8.0 upgraded from 3.7.5
PHP 7.1 / Apache
New URL routing is set to previous behaviour.

### Additional comments
The problem was caused in my system, when the menu-item was set (which I forgot to do when the article was created long before the update). Issue is probably related to #17912.
Remedy: Set layout in every article explicitly
Please ask for further settings you need to know. Again: Thanks for your hard work!

**Comment by makermann** [comment]
Additional info: 
Resetting the layout in Global configuration -> articles -> choose layout has no effect. No matter what you set, only layout a is used. Only by explicitly setting the layout in the article a layout different than the default is used.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18083">issues.joomla.org/tracker/joomla-cms/18083</a>.</sub>

**Comment by Sieger66** [comment]
>4.  Create articles and menu-items,..

What type of menu-item do you create ?
Are all new articles in the same article-category ?

> 7. Now create a menu-item...

What type of menu-item do you create ?

**Comment by tonypartridge** [comment]
Please close, pull request already in see:
https://github.com/joomla/joomla-cms/pull/18061
