### ISSUE TITLE
Batch Article to another Category delete Article-Tags

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#18086]
### Steps to reproduce the issue
Move Articles using "Batch" from one to another Category delete existing Article-Tags.

### System information
Joomla 3.8
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.4
- MySQLi 5.5.57-0+deb7u1

**Comment by AlexRed** [comment]
I can confirm the problem <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18086">issues.joomla.org/tracker/joomla-cms/18086</a>.</sub>

**Comment by Shazrina1994** [comment]
looking forward on this issue.

**Comment by Pilotnik** [comment]
I have the same problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18086">issues.joomla.org/tracker/joomla-cms/18086</a>.</sub>

**Comment by AndySDH** [comment]
Oh weird. This is new because I used this feature before and I can 100% say this was not an issue in 3.7.5.

**Comment by cybersalt** [comment]
I have this issue as well - in 3.8.0 and still in 3.8.1

**Comment by ghost** [comment]
@cybersalt thanks for reporting. This is expected as nobody has created a Pull Request to solve the issue.

**Comment by Fuchsritter** [comment]
Hope this problem will be solved soon. Loosing all tags is horrible.

**Comment by alikon** [comment]
is under investigation

**Comment by ggppdk** [comment]
Hi i have already tested a fix for this and for the deletion of tags during reordering, i will submit a PR in the evening

**Comment by ghost** [comment]
closed as having Pull Request #18328
