### ISSUE TITLE
Broken links if article have Readmore && PageBreak

### ISSUE THREAD

**Issue by effrit** [joomla/joomla-cms#18082]
### Steps to reproduce the issue

Insert Readmore and PageBreak in article (need both of them)

### Expected result

Link in ToC to 'page_2' lead to 'page_2'

### Actual result
'page_2' produce
404 Page Not Found

demo
http://joodem.ru/1-extra-toc-float
(Press 'Page 2')

**Comment by ghost** [comment]
closed as duplicate Report ##17830<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18082">issues.joomla.org/tracker/joomla-cms/18082</a>.</sub>
