### ISSUE TITLE
Configure Site Offline to YES but in frontend has an error

### ISSUE THREAD

**Issue by juriemancia** [joomla/joomla-cms#18085]
### Steps to reproduce the issue

Hi pls help me to fix my Site Offline Configuration. After Updated to 3.8, my site has an error when I turned on the offline YES in site setting. Here's the error " This page isn’t working www.website.com is currently unable to handle this request.
HTTP ERROR 500 "

I need your help

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding. For this Reason the Issue is closed.
