### ISSUE TITLE
close to 3500 Redirect Errors after upgrade 3.7.5 to 3.8

### ISSUE THREAD

**Issue by malleBZ** [joomla/joomla-cms#18081]
Since the update all my redirects are making the same error and add the url to the front like this >>> http://www.domain.net/http://www.domain.net/news.html

Before updating to 3.8 everything was ok and the redirects were working perfectly.

Now i have to change about 3500 entries because of one silly update? that is not possible!!

**Comment by ghost** [comment]
closed as duplicate Report #17996<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18081">issues.joomla.org/tracker/joomla-cms/18081</a>.</sub>

**Comment by malleBZ** [comment]
Very poor reaction! The Problem is not solved, because the "Fix" is not working for me. After editing the redirect.php it is even more worse! The whole site reports strange errors with code "0". I tried 3 versions of this "Fix", but none worked for me!

All my SEO is effected too!! 

Please do not close a Report because you think it is solved. Keep it open until it is really solved. THANX!!!

**Comment by infograf768** [comment]
Have you tested https://github.com/joomla/joomla-cms/pull/17997 to see if it solves your issue?

**Comment by malleBZ** [comment]
Tested it just a second ago .... Error !!!

![error](https://user-images.githubusercontent.com/25465035/30780701-837cdb42-a111-11e7-8c67-db3a0e60c337.PNG)

**Comment by malleBZ** [comment]
Sorry to franz and the bot .... i was so clever to copy also the lines which are marked red and not only the green ones ...

after using the correct lines everything is working perfect!

Thanx ..!!

**Comment by brianteeman** [comment]
Maybe you wont be so quick to blame and shout in the future ;)
