### ISSUE TITLE
After Upgrading Site to 3.8.0, updating extensions and global configuration do not work.

### ISSUE THREAD

**Issue by nealrduncan** [joomla/joomla-cms#18098]
### Steps to reproduce the issue
Extensions > Manage > Update > select extensions > Update
### Expected result
Message
Updating package was successful.
### Actual result
Warning
Update path does not exist.
Message
Error updating COM_INSTALLER_TYPE_TYPE_.
### System information (as much as possible)
FTP enabled and joomla install owned by ftp user. Runing LAMP with Ubuntu server, php 5.6.30, apache 2.4.7 and maria db
### Additional comments
If I make the tmp directory owned by the ftp user, I have to make it owned by web server group in order to install extensions and I still can't update extensions. 

I also can't modify the global configuration. It says Configuration saved, but it doesn't actually write to the configuration.php file. Everything was working fine on Joomla! 3.7.5. I also tried a new 3.8 install and got the same results.

**Comment by VeghNorbert** [comment]
I have the same problem.
Joomla 3.8.0
PHP 5.3.29

Norbert Vegh

**Comment by tonypartridge** [comment]
This sounds like a server side permission issue, the install routine runs but doesn't allow the files to be overwritten. Can you check the files have been updated when installed?

**Comment by nealrduncan** [comment]
Yes, I am able to install extensions via the Joomla! interface. (I do the version updates via the patch rather than the upgrade due to the number of sites that I host.) I have tried playing with all sorts of permissions and the only one that helps is to set the tmp directory to 777 or set it to 774 with the user set to the ftp user and the group set the the web server's group, but that only allows me to install stuff fresh, the updates and altering the configuration.php file remain broken and having the tmp directory set to such loose permissions is less than ideal. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18098">issues.joomla.org/tracker/joomla-cms/18098</a>.</sub>

**Comment by tonypartridge** [comment]
Install akeeba admin tools and run a permissions fix

-- 
Tony Partridge

**Comment by nealrduncan** [comment]
I installed akeeba admin tools and ran a permissions fix. No joy.  I got the same error. "Update path does not exist." Global Configuration was not able to write to configuration.php either.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18098">issues.joomla.org/tracker/joomla-cms/18098</a>.</sub>

**Comment by samuel1201** [comment]
I have the same problem, too
Joomla 3.8.0
PHP Version 7.0.16

**Comment by wojsmol** [comment]
@tonypartridge See https://github.com/joomla/joomla-cms/issues/18024
@nealrduncan @VeghNorbert samuel1201 Whether FTP layer was configured and enabled before update? Please run [Forum Post Assistant](http://forum.joomla.org/viewtopic.php?f=621&t=582860) and post apache2php handler and folder permissions - delete with FTP client.

**Comment by samuel1201** [comment]
<img width="1242" alt="2017-09-26 4 15 01" src="https://user-images.githubusercontent.com/32161122/30849750-fc51c5ee-a2d5-11e7-9eab-11a31e26797a.png">
<img width="702" alt="2017-09-26 4 14 48" src="https://user-images.githubusercontent.com/32161122/30849754-fe288baa-a2d5-11e7-80e0-1cea9c808b73.png">

@wojsmol  My System information

**Comment by tonypartridge** [comment]
So if it is saying it can write to the configuration file but doesn't actually work... it sounds to me like the file may have an ownership issue?

**Comment by wojsmol** [comment]
@tonypartridge Also see [this forum topic](https://forum.joomla.org/viewtopic.php?f=710&t=955150&p=3494561#p3494561)

**Comment by wojsmol** [comment]
cc @Bakual

**Comment by wojsmol** [comment]
@tonypartridge My theory is simple https://github.com/joomla/joomla-cms/issues/18024 caused in same environments an ownership issue.

**Comment by Bakual** [comment]
Try if https://github.com/joomla/joomla-cms/pull/18075 fixes it.
The FtpClient class is completely broken in 3.8.0. I don't know if the FTP layer also uses that class, but changes are high indeed.

**Comment by wojsmol** [comment]
@Bakual Can you prepare a custom update server? 3.8.0 with https://github.com/joomla/joomla-cms/pull/18075

**Comment by Bakual** [comment]
No, I can't do that. Maybe @mbabker can. But then, if you need the FTP layer and it is broken, you will not be able to update anyway since it's broken. So I'm not sure what an custom updateserver would help to test?
You will have to manually replace the file using an FTP program.

**Comment by wojsmol** [comment]
@Bakual As you can see before update to 3.8.0 in this cases there was no permission issues.

**Comment by Bakual** [comment]
It sounds a lot like the whole FTP layer is broken due to the broken FtpClient class. But if that is the case, you will not be able to use the Joomla Update component to update Joomla, since that one imho uses the FTP layer as well.
So installations that use the FTP layer end up in a dead end. They will need to manually replace some files first using an FTP program.

**Comment by wojsmol** [comment]
Anather passibility is revet to backup in empty subfolder and then test https://github.com/joomla/joomla-cms/pull/18075.

**Comment by mbabker** [comment]
> Can you prepare a custom update server?

Anyone can build an update server, the only thing I "block" is being able to publish it on our domain.

**Comment by wojsmol** [comment]
@Bakual  Can you prepare it then?

**Comment by wojsmol** [comment]
@mbabker Can  wee block direct updates to 3.8.0 as you describe few days ago in other issue? On forum there are at least few cases.

**Comment by mbabker** [comment]
Nobody has answered questions I had, or really provided a clear answer of what specifically the problems are, so that we can best react to it.  Until then, I don't want to just arbitrarily put a block in place without understanding what specifically we are blocking, and that understanding will help to be able to address the underlying problem in some way (if it's an issue with trying to run the code from two simultaneous versions, we can document it somewhere and explain why the extra step is needed; if there is a fix we can make in the code we can work on that, etc.).

**Comment by wojsmol** [comment]
@mbabker Please see https://github.com/joomla/joomla-cms/issues/18020#issuecomment-331977141 plus subscribe this topic https://forum.joomla.org/viewtopic.php?t=955125&view=unread#p3494412

**Comment by Bakual** [comment]
@wojsmol You could do that yourself then I guess. Honestly I would have to figure it out first myself as well.

**Comment by nealrduncan** [comment]
The solution in 18075 worked for us, but we did have to make the tmp directory owned by the ftp user and the web server group.

**Comment by Bakual** [comment]
@nealrduncan Please comment that on the #18075 or even better mark it as a successful test in https://issues.joomla.org/tracker/joomla-cms/18075. That would help a lot.

**Comment by wojsmol** [comment]
@Bakual Can you prepare a php part then can take the updateserver part :)

**Comment by samuel1201** [comment]
I tried to change the FtpClient.php and BufferStreamHandler.php by #18075 
It's not worked..... so said.
Should i try to revert to the 3.7.5?

**Comment by samuel1201** [comment]
@nealrduncan How do you fixed it? changed the FtpClient.php and BufferStreamHandler.php?

**Comment by nealrduncan** [comment]
@samuel1201 Yes, the solution in 18075 worked for us. We use ftp and have the joomla directories owned by the ftp user, but we did have to make the tmp directory owned by the ftp user and the web server group.

**Comment by samuel1201** [comment]
@nealrduncan Thanks for your reply! 👍

**Comment by wojsmol** [comment]
@samuel1201 If PR #18075 fixes the issue in your case please mark your test results in https://issues.joomla.org/tracker/joomla-cms/18075

**Comment by samuel1201** [comment]
@wojsmol No... #18075 is not worked in my case. :(

**Comment by samuel1201** [comment]
<img width="1251" alt="2017-09-28 11 11 53" src="https://user-images.githubusercontent.com/32161122/30947723-df803a04-a43d-11e7-817e-93ac1e34ff3f.png">
The same problem!

**Comment by wojsmol** [comment]
@samuel1201 Please post WebServer to PHP Interface value System > System Information > Tabulator "System Information" and screenshot of the permission tab..

**Comment by samuel1201** [comment]
<img width="1156" alt="2017-09-28 12 40 01" src="https://user-images.githubusercontent.com/32161122/30949635-2b3b1426-a44a-11e7-875c-a4871e8d774b.png">
here

**Comment by wojsmol** [comment]
and permission tab?

**Comment by samuel1201** [comment]
<img width="623" alt="2017-09-28 2 43 35" src="https://user-images.githubusercontent.com/32161122/30952714-8ad6a218-a45b-11e7-93eb-82a7729d2065.png">

all Writable

**Comment by wojsmol** [comment]
@samuel1201 See this worming above
@nealrduncan Do you you had a warning above like in https://github.com/joomla/joomla-cms/issues/18098#issuecomment-332715608 ?

**Comment by samuel1201** [comment]
I have no idea to fix this problem.
so I'm considering reverting to the old version （3.7.5)

**Comment by wojsmol** [comment]
@Bakual Any idea for https://github.com/joomla/joomla-cms/issues/18098#issuecomment-332715608 ?
@samuel1201 you have ssh accces?

**Comment by Bakual** [comment]
> Any idea for #18098 (comment) ?

No. I also havent' looked deeper into this issue. I just know that the FtpClient class currently is broken and **if** that class is used, it will be broken as well. But I don't even know if that class is used here (when FTP layer is enabled). If you don't have the FTP layer enabled, then that shouldn't play a role at all.

**Comment by samuel1201** [comment]
@wojsmol Yes. My Nas has SSH setting

**Comment by wojsmol** [comment]
Download Full package of 3.8.0, extrackt to to separate folder and fiff this to folders. Look for mising files in site side and existing in there reference folder.
@Bakual This cen be dabe in php but noy updated when really necessary - https://checksums.kubik-rubik.de/#overview-joomla - cen we can contact Victor? - show separately missing file.

**Comment by Bakual** [comment]
Sure, contacting @Kubik-Rubik is easy :smile:

**Comment by wojsmol** [comment]
@Bakual I try this method few day ago in other issue - no response :(

**Comment by Bakual** [comment]
Few days ago he was busy with JoomlaDay Germany for sure :smile:

**Comment by wojsmol** [comment]
@Bakual ok, thx for info. I don't follow JoomlaDay's calendar around the world so closely 😄

**Comment by nealrduncan** [comment]
@wojsmol yes, we had that warning until we changed the BufferStreamHandler.php & FtpClient.php per 18075. Then we got "Unable to find install package". We had to change the tmp directory to be owned by  the web server to get it to work.

**Comment by wojsmol** [comment]
@samuel1201 See https://github.com/joomla/joomla-cms/issues/18098#issuecomment-333209430

**Comment by wojsmol** [comment]
@nealrduncan @samuel1201 Because both of you use php-fpm then try please search in the documentation how to run it as user. This is usual 1 line in appropriate config file. The please revert any ownership and permission changes  on tmp and retest PR.

**Comment by samuel1201** [comment]
@wojsmol  I build my joomla web site on my personal NAS and i am a visual & web designer so i can not to fix the problem with program grammar like PHP or SSL : ( . I install the 3.8.1 release in the morning and the problem still exists (So sad....T_T) . Finally thanks for your great great help!!

**Comment by ghost** [comment]
closed as Thread is for [Forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18098">issues.joomla.org/tracker/joomla-cms/18098</a>.</sub>

**Comment by jflash** [comment]
#18075  was worked for me, now i can update extensions with FTP layer on :)

**Comment by ghost** [comment]
@jflash please mark your Test at #18075 as successfully:

- Please open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/18075)
- Login with your github-Account
- Click on blue "Test this"-Button above Authors-Picture
- mark your Test as successfully
- hit "submit test result"

**Comment by VictorRodriguezcl** [comment]
Hello, I did a clean install of 3.8.1 on Windows 10 and Ubuntu 17.04, both on php 5.6. Ubuntu is having the blank Extensions page. Maybe tha last update of php it's generating the problem.

Thanks.

**Comment by ghost** [comment]
@VictorRodriguezcl Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.

**Comment by amzaf** [comment]
I have the same issue in a hosting environment. This is not a Joomla issue but a limitation imposed by the host which I cannot track down. I backed up my site and restored it locally. The error message disappears when run on my test server.

**Comment by PawelSzymanski89** [comment]
Try this: 
youradress.com/administrator/index.php?option=com_installer&task=database.fix
