### ISSUE TITLE
After Upgrading Site to 3.8.0 all attempts to send emails fail with http 500

### ISSUE THREAD

**Issue by cheshirealan** [joomla/joomla-cms#18096]
### Steps to reproduce the issue

All email sending from site or admin fail with http 500 except for system generated emails to notify me of changes to Global Config.

It doesn't matter whether I configure via PHP Mailer/Sendmail/SMTP - all fail.

ACYmailing has separate SMTP connection to eeMail and that works fine for newletters. 

### Expected result

Emails sent

### Actual result

http 500

### System information (as much as possible)

See Joomla Forum https://forum.joomla.org/viewtopic.php?f=710&t=954994 for full thread on the issue and attempts to fix it. Includes diagnostics

**Comment by wojsmol** [comment]
cc @dgt41 Please look at this if you have time. I try solve this on forum but no luck. IMHO issue is at lest partly related to js.

**Comment by tonypartridge** [comment]
Can you enable Joomla! Debug and max error reporting and try again? Do you see a error message?

**Comment by cheshirealan** [comment]
This was all tried and documented in the forum post. Error no longer shows on screen but firebug shows Jason parsing issue as response is empty.

**Comment by cheshirealan** [comment]
Json. Auto spell check lol

**Comment by tonypartridge** [comment]
Can you send me super user logins to tony at xws dot Im and I'll take a deeper look.

**Comment by sozzled** [comment]
@cheshirealan , please explain how the admin site sends email when someone changes the Global Settings.  Also see my reply on your forum topic.

**Comment by AMurray2016** [comment]
@sozzled, it's probably NOT joomla doing that but Akeeba Admin tools (as one example), I know that does send alerts to any config changes made.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18096">issues.joomla.org/tracker/joomla-cms/18096</a>.</sub>

**Comment by cheshirealan** [comment]
Correct, the emails are sent by Admin Tools Pro.

**Comment by tonypartridge** [comment]
So you are saying admin tools pro can send email, but Joomla! User manager cannot?

**Comment by tonypartridge** [comment]
Ok, so I found a link to your site and ran a test registration. Firstly on login you have a plugin controlling the login button given it has a count down.

Then on register you are using AcyMailing on the form. 

Can you disable all acymailing forms and the plugin controlling the count down timer for login?

And test again, also look for an error_log file in your joomla! Root.

**Comment by cheshirealan** [comment]
Correct

Its not just the user manager. The full list of emails so far that fail are:


  *   Emails sent to user when they register
  *   Forgotten password
  *   Forgotten username
  *   Contacts emails
  *   Extensions that use standard mail facility e.g. Membership Pro

ACYMailing has its own SMTP configuration and that works.

Just setting up super user for you Tony.

**Comment by cheshirealan** [comment]
Tony

I have added Super User access to the user you created however I need to email you a special url to login.

**Comment by cheshirealan** [comment]
Guys - I have found the source of the issue.

ACYMailing - it has an override feature to enable formatting of emails such as the ones regarding forgotten password.. I have disabled it and emails are now sending. I will contact ACYMailing for assistance.

**Comment by tonypartridge** [comment]
Good Detective work, and thanks handy to know for the future. This can now be closed.

**Comment by ghost** [comment]
@cheshirealan as this is not an Core-issue can you please close this issue?
