### ISSUE TITLE
Problem in the CSS code of admin panel in Joomla 4

### ISSUE THREAD

**Issue by Am707** [joomla/joomla-cms#18097]
![screen shot 2017-09-24 at 20 54 42](https://issues.joomla.org/uploads/1/4b6ed8285b36de7aebd91ac95d7d729d.jpg)
### Steps to reproduce the issue
As can be seen from the attached image, CSS code of the system Joomla 4 (admin panel) is completely executed in one line.

### Expected result
It is necessary to convert all CSS system code (administrative panel) in the form of a column, that so that user Joomla 4 if desired, will be convenient to make changes in the interface of the administrative panel.

### System information (as much as possible)
Joomla_4.0.0-dev-Development

**Comment by tonypartridge** [comment]
If you enable debug mode then the minified css files are not loaded. This is not an issue.

**Comment by brianteeman** [comment]
@tonypartridge I thnk you meant to say they are loaded when in debug mode

**Comment by tonypartridge** [comment]
Umm, I thought we load non minified css files when in Debug mode? To help well Debug...

**Comment by brianteeman** [comment]
Sorry I misread your comment. 

Anyway it is expected behaviour so I am closing
