### ISSUE TITLE
3.8: "Class not found" and Notice at Feed&type=atom

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#18095]
### Steps to reproduce the issue
Using URL `?format=feed&type=atom` for RSS-Feed got:

![bildschirmfoto 2017-09-24 um 17 22 42](https://user-images.githubusercontent.com/8235763/30783996-ffaf7c52-a14c-11e7-84c9-431522dc47a3.jpg)

Set Report on Maximum got:

`Notice: Array to string conversion in /components/com_tags/helpers/route.php on line 91`
### System information
Joomla 3.8
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
MySQLi 5.5.57-0+deb7u1
PHP 7.0.4

**Comment by AlexRed** [comment]
I can confirm the problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18095">issues.joomla.org/tracker/joomla-cms/18095</a>.</sub>

**Comment by ghost** [comment]
Status on Issue Tracker changed to "Confirmed".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18095">issues.joomla.org/tracker/joomla-cms/18095</a>.</sub>

**Comment by infograf768** [comment]
Not sure how you get that.
Can you explain in details how to reproduce?

**Comment by ghost** [comment]
Set RSS-Feed on Menu using Tags for showing Articles. Url found in Googles Search Console.

**Comment by AlexRed** [comment]
an example:
http://www.joomla.it/?format=feed&type=atom   not work
http://www.joomla.it/?format=feed&type=rss    ok

**Comment by infograf768** [comment]
I tried here on a local multilingual site
A home page menu item of type featured articles displaying an article with tags.
`http://localhost:8888/testnew/trunkgitnew/index.php/en/?format=feed&type=atom`
and I have no issues. The feed displays fine.

What do I not understand?

**Comment by ghost** [comment]
please have a Look: http://margotwohlkoenig.at/5-elemente-ernaehrung/artikel?format=feed&type=atom

**Comment by infograf768** [comment]
OK, found out how to get the error.
Site Name in Page Titles has to be set to after or before.
Patch coming

**Comment by infograf768** [comment]
Closing as we have a patch
https://github.com/joomla/joomla-cms/pull/18102

Please test
