### ISSUE TITLE
An error has occurred. 500 JForm::getInstance could not load file

### ISSUE THREAD

**Issue by fmsd91** [joomla/joomla-cms#18105]
### Steps to reproduce the issue
Enter the administrator back-end joomla and navigating anywhere I get this error. 

### Expected result
All top menus visible and destination correctly showing

### Actual result
Top menu not showing. Error message appears. When refreshing sometimes it shows correctly but most of the times the error appears again. Very annoying and difficult to work.

### System information (as much as possible)
Joomla 3.8.0 (recently updated)
php 7.0.23 (recently updated)

### Additional comments
This error occurs in Firefox, Chrome and IE and in many different computers with windows 10 and 64 bits.

**Comment by ghost** [comment]
have you read other Threads here for similar Issues?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18105">issues.joomla.org/tracker/joomla-cms/18105</a>.</sub>

**Comment by fmsd91** [comment]
Yes but nothing helped too much. I have this problem for more than 1 month. I tried to disable a lot of extensions I got my website working also badly just to solve this issue with no joy.

**Comment by alikon** [comment]
so it's unrelated to the 3.8 release

**Comment by ghost** [comment]
thanks for Clarification as i thought Issue started after Update on 3.8.

**Comment by fmsd91** [comment]
I think is more related with update of php 7.1, but when I revert both to joomla 3.6 and php 5.6 all works ok.

**Comment by wojsmol** [comment]
@fmsd91 Please open topic on the [forum](https://forum.joomla.org/).

**Comment by ghost** [comment]
closed as to be discussed in Forum.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18105">issues.joomla.org/tracker/joomla-cms/18105</a>.</sub>
