### ISSUE TITLE
Missing placeholder descriptions in article selection (menu manager)

### ISSUE THREAD

**Issue by alexpanfilov** [joomla/joomla-cms#18106]
### Steps to reproduce the issue
Menus Manager -> Select menu item type - Single Article -> Select or Change article -> Search Tools fields. 

### Expected result
Placeholder text with actual description for fields

### Actual result
Menus Manager -> Select menu item type - Single Article -> Select or Change article -> Search Tools fields.  Here are select fields with same placeholder "Type or select some options" without actual titles (Select: Category / Users / etc. )

<img src="http://alexpanfilov.com/files/select.png" />

### System information (as much as possible)
Joomla 3.8.0
English Language

**Comment by ghost** [comment]
Status in Issue Tracker changed to "Confirmed".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18106">issues.joomla.org/tracker/joomla-cms/18106</a>.</sub>

**Comment by brianteeman** [comment]
This is a direct result of the recent change to allow multiple selects on these filters. Personally the disadvantage in the UX  as shown here doesnt make that change a positive one

**Comment by infograf768** [comment]
Grr, we have a lot of other issues directly depending from that change indeed.

**Comment by alikon** [comment]
this one #17668 ?

**Comment by brianteeman** [comment]
@alikon yes thats the culprit

**Comment by alikon** [comment]
should be fixed by #18140 please test

**Comment by ghost** [comment]
closed as having Pull Request #18140<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18106">issues.joomla.org/tracker/joomla-cms/18106</a>.</sub>
