### ISSUE TITLE
Joomla forgets filtering when I publish/unpublish an item

### ISSUE THREAD

**Issue by drtothferenc19** [joomla/joomla-cms#18103]
### Steps to reproduce the issue

- Open Extension -> Plugins
- Open search tools and select 'enabled' status
- From the filtered list unpublish a plugin

### Expected result

After unpublishing the plugin I should get the filtered (published) list I used before

### Actual result

Joomla forgets the filters I used and I get the whole list with published and unpublished items

### System information (as much as possible)
PHP 7, Joomla 3.8, Firefox Private browsing

**Comment by brianteeman** [comment]
I can not replicate this. I see that you are using Firefox Private Browsing. Can you try in another browser or without private mode please

**Comment by ghost** [comment]
Can't confirm.

### System information
3.8.1-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 55 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by tonypartridge** [comment]
I can recreate this randomly.

Are you using a CDN @drtothferenc19 ?

**Comment by tonypartridge** [comment]
@drtothferenc19 please confirm?!?!

**Comment by ghost** [comment]
Status set on "Information required".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18103">issues.joomla.org/tracker/joomla-cms/18103</a>.</sub>

**Comment by tonypartridge** [comment]
No response from User, pleas close. I’ll open one if I can find a consisten way to reproduce.

**Comment by brianteeman** [comment]
Closed due to lack of response - it can always be reopened if updated
