### ISSUE TITLE
AtomRenderer

### ISSUE THREAD

**Issue by heleneross** [joomla/joomla-cms#18109]
### Steps to reproduce the issue
In global configuartion->site set Site Name in Page Titles to either before or after
Visit any page with an atom feed eg. a blog using ?format=feed&type=atom 

### Expected result
Atom feed shown

### Actual result
white page

### System information (as much as possible)
J3.8.0

### Additional comments
JText class not found in src/Document/Renderer/Feed/AtomRenderer.php on lines 68 and 72. 
Quick fix is to add \ before JText giving \JText::sprintf

**Comment by ghost** [comment]
closed as duplicated Report #18095.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18109">issues.joomla.org/tracker/joomla-cms/18109</a>.</sub>
