### ISSUE TITLE
[Regression] Calendar Formfield doesn't work anymore with custom formats

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#18112]
### Steps to reproduce the issue
Change language to german (or another language with a "translated" format) and save an article

### Expected result
Works

### Actual result
Warnings about invalid values in date fields
![image](https://user-images.githubusercontent.com/1018684/30825930-12aed490-a235-11e7-9a9f-6400f4984a07.png)

### System information (as much as possible)
Current staging

### Additional comments
This is caused by the merge of https://github.com/joomla/joomla-cms/pull/17823 which should be reverted without replacement 😄

**Comment by infograf768** [comment]
Confirm. When using French I have the same issue.

**Comment by mbabker** [comment]
#17823 reverted for now.

**Comment by Shazrina1994** [comment]
did u check the source codes as well in that related date format in the article?
