### ISSUE TITLE
[3.7.5] and [3.8.0] Category Blog items with only a few articles don't show

### ISSUE THREAD

**Issue by rpbikker** [joomla/joomla-cms#18110]
Hi all, before I start let me thank you for all the time devoted to this software!

On my website I have an issue since Joomla 3.7.5. This problem persists in Joomla 3.8.0. Looking back in my logfiles, the problem did not occur with 3.7.4 and earlier. 

### Steps to reproduce the issue
Create a menu item of type "Category Blog", filtered by one Tag, 0 "Leading Articles" and 5 "Intro Articles". When the number of articles tagged by this Tag is less than 5, the page will not show.

### Expected result
A page with tagged articles in blog layout.

### Actual result
Http error 500. Setting $error_reporting = 'development' does not produce additional php error text.

### System information (as much as possible)
Joomla 3.7.5 and 3.8.0, template Purity III v 1.2.0, T3 framework v 2.6.7, Jotcache 5.3.2, and a good number of other packages which can't imagine being involved in this problem. Host is Centos 7.4, Apache 2.4.8, PHP 7.1.9 and mariadb 5.5.56.

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding. For this Reason close this Issue, thanks.

**Comment by rpbikker** [comment]
I didn't actually ask for help, did I? I'm reporting a bug.
