### ISSUE TITLE
Après mise à jour 3.8, plus rien sauf logo.

### ISSUE THREAD

**Issue by OTBlop** [joomla/joomla-cms#18116]
### Steps to reproduce the issue
Cliqué sur le bouton mise à jour de la version 3.8.

### Expected result
Mise à jour.

### Actual result
Seul le logo en haut du site est visible, les catégories de gauche, droite et centre ne sont plus visibles.

### System information (as much as possible)
PHP 7.0

### Additional comments
Je ne connais pas trop joomla... et ai vraiment besoin d'aide :).

**Comment by ghost** [comment]
can you please write your issue in English?

**Comment by OTBlop** [comment]
Sorry,
I found a solution.
I need update template too.
Could you delete or close ? Where i could close ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18116">issues.joomla.org/tracker/joomla-cms/18116</a>.</sub>

**Comment by ghost** [comment]
closed as Issue solved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18116">issues.joomla.org/tracker/joomla-cms/18116</a>.</sub>

**Comment by OTBlop** [comment]
Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18116">issues.joomla.org/tracker/joomla-cms/18116</a>.</sub>
