### ISSUE TITLE
ERROR 503 JOOMLA 3.8  Constant _QQ_ already defined in /libraries/src/Language/Language.php on line 18

### ISSUE THREAD

**Issue by saopaulosao** [joomla/joomla-cms#18114]
ERROR BACKEND AND FRONTEND ERROR 503

Update Joomla 3.7.5 > 3.8  Constant _QQ_ already defined in /libraries/src/Language/Language.php on line 18
HP message: PHP Notice:  Undefined property: stdClass::$rating_count in plugins/content/like/like.php on line 70
PHP message: PHP Notice:  Undefined property: stdClass::$rating_count in plugins/content/like/like.php on line 70
PHP message: PHP Notice:  Undefined property: stdClass::$rating_count in plugins/content/like/like.php on line 70
PHP message: PHP Notice:  Undefined property: stdClass::$rating_count in plugins/content/like/like.php on line 70
PHP message: PHP Notice:  Undefined property: stdClass::$rating_count in plugins/content/like/like.php on line 70" while reading response header from upstream, client: 172.68.27.62, server:www.com.br, request: "GET /?nocache HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: ".com.br"

HELP ME PLEASE!

**Comment by wojsmol** [comment]
Please create topic on [forum](https://forum.joomla.org/) and add link to this topic here.

**Comment by tonypartridge** [comment]
Disable your like plugin, this is not a core issue.

**Comment by brianteeman** [comment]
And please don't spam the issue tracker.
