### ISSUE TITLE
Impossible erase cache after upgrade J 3.8.0

### ISSUE THREAD

**Issue by paoprod** [joomla/joomla-cms#18115]
### Steps to reproduce the issue
1/ Go to Global Configuration
2/ Tab "System"
3/ Cache Handler -> Cache_Lite

### Expected result
Cache folder can't be normally empty through the "System" -> "Clean cache" tool

### Actual result
Cache folder contain folders that have path in their namefolder (i.e. : Joomla/CMS/Helper/LibraryHelper::loadLibraryjoomla_lock )
Thoses folders can be erased by the "System" -> "Clean cache" tool
Neither through FTP
Neither through 3rd component (i.e. : CleanCache from regularLab) 

### System information (as much as possible)
Joomla 3.8.0
[systeminfo-2017-09-25T21-21-06-05-00.txt](https://issues.joomla.org/uploads/1/8d14911d18b905c9696cd0b9e315ec7c.txt)

### Additional comments
When the Cache Handler is set up to "File", no more folder with path in their namefolder are generated anymore.
I erased old files and folders through Cpanel and cache works great again...

**Comment by ghost** [comment]
Can't confirm for using "File"; "Cache_lite" is 3rd-Party as i can see it in clean Install?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18115">issues.joomla.org/tracker/joomla-cms/18115</a>.</sub>

**Comment by wojsmol** [comment]
@franz-wohlkoenig See this [@mbabker post]( https://forum.joomla.org/viewtopic.php?p=3379910#p3379910) as you can see Cache_Lite is in clean install but must be supported by the server.

**Comment by csthomas** [comment]
You can test https://github.com/joomla/joomla-cms/pull/17381 at check if this help you. I designed it for redis but it should be helpful for this issue. 

Please do not close this issue yet. It may not be related.

**Comment by paoprod** [comment]
@franz-wohlkoenig , I have re-installed a clean Instal of Joomla 3.8 and Cache_lite is enable without installing any 3rd-party.
@csthomas thanks for the test : 
I made a new clean install J 3.8.0 : issue is confirmed - Cache Handler -> File, OK // Cache Handler -> Cache_lite, can't erase my cache anymore.
I installed the patch suggested in #17381 
I don't get anymore folders/files with _lock termination or path in their namefolder. But All cache group stay empty, even when navigatinng on frontend to fill them. When cleaning cache, the message confirm all group cache has been emptied but actually there was nothing in there.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18115">issues.joomla.org/tracker/joomla-cms/18115</a>.</sub>

**Comment by paoprod** [comment]
For info : 
Host is Siteground (Apache/2.2.24 (Unix) mod_hive/5.5 mod_ssl/2.2.24 OpenSSL/1.0.0-fips mod_auth_passthrough/2.1 mod_fastcgi/2.4.6 mod_bwlimited/1.4 mod_fcgid/2.3.6) PHP	7.0.23 - MySQL	5.6.36-82.1-log.
The issue appear only on J 3.8.0 install, 
On J 3.7.5, no issue with cache (File or Cache_lite)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18115">issues.joomla.org/tracker/joomla-cms/18115</a>.</sub>

**Comment by paoprod** [comment]
Sorry for my comment above about cache-group empty. Cache-group work perfectly ( an issue with my FTP client, sorry for that)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18115">issues.joomla.org/tracker/joomla-cms/18115</a>.</sub>

**Comment by csthomas** [comment]
Does the suggested patch work for you?

**Comment by paoprod** [comment]
Yep, it works fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18115">issues.joomla.org/tracker/joomla-cms/18115</a>.</sub>

**Comment by csthomas** [comment]
You can mark patch as test successful at https://issues.joomla.org/tracker/joomla-cms/17381
Click on button "Test this" and mark as success.

**Comment by paoprod** [comment]
OK, Done !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18115">issues.joomla.org/tracker/joomla-cms/18115</a>.</sub>

**Comment by ghost** [comment]
closed as Issue solved by Pull Request #17381<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18115">issues.joomla.org/tracker/joomla-cms/18115</a>.</sub>
