### ISSUE TITLE
Split / paginated articles URL problem after update to 3.8

### ISSUE THREAD

**Issue by f1sz** [joomla/joomla-cms#18118]
Hello,
I found some bug on the split / paginated articles after joomla upgrade from 3.7.5 to 3.8.
"real world" example - article with split pages (intro page): http://www.razersite.eu.org/testy/65-recenzja-podkladki-razer-goliathus-speed-cosmic-large

When you click on 2nd or 3rd link (http://www.razersite.eu.org/testy/65-recenzja-podkladki-razer-goliathus-speed-cosmic-large?showall=&start=1) called "W działaniu" or "Podsumowanie" - it display a custom joomla 404 error page.

The only link from this menu that fully works is the last link (show all pages, "wszystkie strony"): http://www.razersite.eu.org/testy/65-recenzja-podkladki-razer-goliathus-speed-cosmic-large?showall=1&limitstart=

I double checked on a local webserv - it fully worked on 3.7.5 version, after I've upgraded it to 3.8 - it displays a 404 error.

### Steps to reproduce the issue
Update joomla from 3.7.5 to 3.8, create some article with split pages, click on 2nd (or next) split page, and it show a 404 error page.

### Expected result
Redirection to proper "splitted" page number, without displaying 404 not found error.

### Actual result
404 page on all splitted page (except "show all pages" link)

### System information (as much as possible)
PHP ver: 7.1.7 
MySQL ver: 5.6.36 

local webserv:
PHP: 5.6.28 
MySQL: 5.6.36

**Comment by ghost** [comment]
closed as duplicate Report #17830<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18118">issues.joomla.org/tracker/joomla-cms/18118</a>.</sub>
