### ISSUE TITLE
Authorization Issue, page will only display when logged into site.

### ISSUE THREAD

**Issue by paulmcdonald74** [joomla/joomla-cms#18111]
### Steps to reproduce the issue
This is an error with a basic custom component that worked prior to 3.8.  It is a basic page that pulls info from a custom table.  When not logged into the site, the page will not display and displays "Error  You are not authorised to view this resource."

### Expected result
It should display to public on website (not logged in) and was doing so up to 3.8.

### Actual result
Error
You are not authorised to view this resource.

### System information (as much as possible)

Database Version | 5.5.5-10.1.26-MariaDB
Database Collation | latin1_swedish_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.0.23
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.8.0 Stable [ Amani ] 19-September-2017 14:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0

### Additional comments
What is something to look for in order to fix this?   Appreciate any assistance.  Fyi, this custom component uses JViewLegacy

**Comment by tonypartridge** [comment]
Check the menu item permission and check the component access right. I don't see why it would stop working.

**Comment by paulmcdonald74** [comment]
Yes.  I definitely checked these things prior to posting.



On Sep 25, 2017, at 8:51 PM, Tony Partridge <notifications@github.com<mailto:notifications@github.com>> wrote:


Check the menu item permission and check the component access right. I don't see why it would stop working.

**Comment by tonypartridge** [comment]
Enable Joomla Debug mode. What function is calling the 503.

-- 
Tony Partridge

**Comment by ghost** [comment]
@paulmcdonald74 can you give an Update about the Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18111">issues.joomla.org/tracker/joomla-cms/18111</a>.</sub>

**Comment by brianteeman** [comment]
I am closing this at this time. It can always be reopened if updated
