### ISSUE TITLE
Error: 500 JHmlJquery::token not found

### ISSUE THREAD

**Issue by fabianskier** [joomla/joomla-cms#18124]
### Steps to reproduce the issue
After upgrade from 3.5.1 to 3.8.0.

### Expected result
Global configuration show properly.
Text Filters and Permissions tab show its options.

### Actual result
- Global configuration doesn't show Navbar, Header, Buttons (Save, Save & Close, Cancel).
- Mail setting with error. 

### System information (as much as possible)
PHP Version 5.4.16
Database MySQL 5.6.37
Joomla! 3.5.1 Stable
Joomla Platform 13.1.0 Stable
Apache/2.4.6 (CentOS)

### Additional comments
![cache settings](https://user-images.githubusercontent.com/15128101/30869050-3d717aa6-a2ae-11e7-80d4-c3a1b69878ee.PNG)
![system settings](https://user-images.githubusercontent.com/15128101/30869048-3d6ad32c-a2ae-11e7-8f4a-e6069086facb.PNG)
![site settings](https://user-images.githubusercontent.com/15128101/30869051-3d73c64e-a2ae-11e7-9121-e91d8648cc1d.PNG)
![server settings](https://user-images.githubusercontent.com/15128101/30869049-3d6d0c3c-a2ae-11e7-91d4-91c800f40c51.PNG)

**Comment by ghost** [comment]
Have you asked help on the [forums](https://forum.joomla.org/)? This repository concerns in first Place Joomla coding.

**Comment by C-Lodder** [comment]
I'd probably say the update didn't properly complete. `JHtmlJquery::token()` does exists and was added in J3.8, which you can see here:
https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/html/jquery.php#L122

Try performing the update again

**Comment by angi23** [comment]
Hi,
I have the same fabianskier's problem upgrading joomla from 3.7.5 to 3.8.1.
I followed the suggestion of C-Lodder but I have the file and the problem persists. 
Have you solved the problem? Could you help me with your suggestion?  Thanks

**Comment by ghost** [comment]
@angi23 please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710).
