### ISSUE TITLE
Bug in com_redirect

### ISSUE THREAD

**Issue by ucfnet002** [joomla/joomla-cms#18128]
### Steps to reproduce the issue
Create and publish a redirect via redirect component to an existing page. For example: https://www.domain.tld/page-old.html should be redirected to page https://www.domain.tld/page-new.html

### Expected result
The browser redirects to 
https://www.domain.tld/page-new.html

### Actual result
The browser redirects to 
https://www.domain.tld/https://www.domain.tld/page-new.html

### System information (as much as possible)
Joomla! 3.8.0

### Additional comments
The bug even exists on joomla.de.
Old URL: http://www.joomla.de/joomla-entdecken/begriffserklaerung
New URL: https://www.joomla.de/wissen

**Comment by brianteeman** [comment]
Closed as a duplicate report and already fixed for 3.8.1

**Comment by ghost** [comment]
@ucfnet002 if you are interested: Pull Request #17997
