### ISSUE TITLE
500 error on website on article single article

### ISSUE THREAD

**Issue by shawnlesky** [joomla/joomla-cms#18126]
### Steps to reproduce the issue

Joomla 3.8
### Actual result

500 error on only article/single article (rest displays as normal)

**Comment by shawnlesky** [comment]
website is steampunkpipeworks.com

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding. For this Reason closing this Issue, thanks.

**Comment by wojsmol** [comment]
@franz-wohlkoenig one  more thing - in this cases add as text forum name "Migrating and Upgrading to Joomla! 3.x". Of course if this is not a problem. :)

**Comment by shawnlesky** [comment]
So nobody can help with this?

**Comment by brianteeman** [comment]
From the information you provided it is impossible

**Comment by shawnlesky** [comment]
What would I have to do to supplement the rest of the needed information?
