### ISSUE TITLE
Editor Buttons in TinyMCE use  `<i>` instead of  `<span>` for icons

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#18120]
### Steps to reproduce the issue
Check the editor-xtd buttons in TinyMCE. The icons use a `<i>` tag instead of a (semantically correct) `<span>` tag.
In other editors where the buttons are shown below the editor, `<span>` is used.

### Expected result
Uses span

### Actual result
Uses i (italic)

### Additional comments
Now this may be something which comes from TinyMCE itself.
I noticed because it broke the icon for the ARS button (https://github.com/akeeba/release-system/issues/126) and may as well have broken it for other extensions.

**Comment by ghost** [comment]
Status "Confirmed" on Issue Tracker.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18120">issues.joomla.org/tracker/joomla-cms/18120</a>.</sub>

**Comment by esedic** [comment]
`<i>` tags are generated inside media/editors/tinymce/tinymce.min.js file

**Comment by Bakual** [comment]
Can we do anything or is that something which has to be fixed upstream in the TinyMCE repo?

**Comment by dgrammatiko** [comment]
We need to open an issue upstream. Although this is a b/c breaking change so keep low expectations

**Comment by brianteeman** [comment]
As the version of tinymce we use in j3 is no longer actively supported i would not expect an update. If the newer version of tinymce that is used in J4 has the same issue then it might be fixed there but wont help the issue reported here

**Comment by Bakual** [comment]
I opened an issue on their repo: https://github.com/tinymce/tinymce/issues/3954
Lets see how it goes.

I'm closing this one here.

**Comment by brianteeman** [comment]
we can fix it ourselves by creating our own theme for tinymce instead of using one of the vendor supplied themes (if i read the code correctly)
