### ISSUE TITLE
Serialization of 'SimpleXMLElement' is not allowed

### ISSUE THREAD

**Issue by vyurkov** [joomla/joomla-cms#18130]
### Steps to reproduce the issue
I use SJ_Contact_Ajax extension on my website.
The problem resolved in Joomla 3.7.5 by comment or delete the line
$this->cache->store(serialize($data), $id);
in /home/user/public_html/libraries/joomla/cache/controller/callback.php
but in Joomla 3.8.0 this file was removed.

### Expected result
Working FrontEnd extensions that using ajax and serialize method.

### Actual result
Error 0 Serialization of 'SimpleXMLElement' is not allowed

### System information (as much as possible)
PHP Version | 7.0.23
Web-server | Apache

**Comment by mbabker** [comment]
That fix completely disables the cache system on your site, it's not a good fix.

You need to contact the extension developer and ask them to update their extension.  They are trying to use the cache and store data with an incompatible object.

**Comment by ghost** [comment]
closed as no Core Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18130">issues.joomla.org/tracker/joomla-cms/18130</a>.</sub>

**Comment by creativeideashun** [comment]
Hy,

I located the ominous line here:
0:/public_html/libraries/src/Cache/Controller/CallbackController.php

I changed from: 
$this->cache->store(serialize($data), $id);

To:
$this->cache->store($data, $id);

And it works fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18130">issues.joomla.org/tracker/joomla-cms/18130</a>.</sub>

**Comment by ms8277** [comment]
@creativeideashun Thank you very much, that solved the issue for me. Appreciate your efforts

**Comment by mohammadky82** [comment]
@creativeideashun Removing or committing **$this->cache->store(serialize($data), $id);** without adding **$this->cache->store($data, $id);** will do it, because adding the second line will cause another issue with unserialize() function within the same file
