### ISSUE TITLE
2 instances of login-form result in duplicate ids, thus validation errors

### ISSUE THREAD

**Issue by msbt** [joomla/joomla-cms#18133]
### Steps to reproduce the issue
Add login link in the top menu which shows an overlay to log in, add second login form in the footer and check your site for validation errors

### Expected result
No validation errors

### Actual result
> Duplicate ID “login-form”.
> Duplicate ID “modlgn-username”.
> Duplicate ID “modlgn-passwd”.

### System information (as much as possible)
Latest joomla, Flex theme (http://flex.aplikko.com/)

### Additional comments
Can I somehow duplicate the login form and use different ids?

Best regards, M

**Comment by esedic** [comment]
I think this is a template issue, it uses same code for modal login and login module.

**Comment by ghost** [comment]
Please ask help at Template-Developers or on the [forums](https://forum.joomla.org/). This repository concerns Joomla coding. For this Reason closing this Issue, thanks.
