### ISSUE TITLE
[com_fields] Option to create or not Custom fields has no effect on admin menu

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#18136]
### Steps to reproduce the issue
Display Articles Options (same issue for other components using custom fields).
Set Enable Custom fields to `No`.

<img width="787" alt="screen shot 2017-09-27 at 08 10 49" src="https://user-images.githubusercontent.com/869724/30898483-d697bd0a-a35b-11e7-9092-4e56b81acb33.png">

### Result
The Fields and Field Groups do not display in the sidebar => That's OK.
They still display in the Admin menu => WRONG

<img width="475" alt="screen shot 2017-09-27 at 08 15 26" src="https://user-images.githubusercontent.com/869724/30898534-19f1b768-a35c-11e7-9c33-b56de91304a0.png">

@izharaazmi

**Comment by infograf768** [comment]
OK. I have a patch ready. Will post now.

**Comment by izharaazmi** [comment]
I have a question here. 

Its a good thing that we can detect the settings in extension too detect such things. But if we are doing this only for core and allowing no way to do the same for other developers (3DP) then we are doing it wrong.

Think of a case where a component `com_tasks` allows users to create two type of items (such as users and groups), each having a  menu item link in admin. Now there is a setting in the extension to disable either or both type of items. How do we hide that menu item? Mind it that module manager doesn't know about this `com_tasks`.

**Comment by ghost** [comment]
closed as having Pull Request #18137<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18136">issues.joomla.org/tracker/joomla-cms/18136</a>.</sub>

**Comment by ghost** [comment]
sorry @izharaazmi, reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18136">issues.joomla.org/tracker/joomla-cms/18136</a>.</sub>

**Comment by infograf768** [comment]
> Think of a case where a component com_tasks allows users to create two type of items (such as users and groups), each having a menu item link in admin. Now there is a setting in the extension to disable either or both type of items. How do we hide that menu item? Mind it that module manager doesn't know about this com_tasks.

Do you have a better solution than https://github.com/joomla/joomla-cms/pull/18137 ?

IMHO, 3pd should follow core on this: i.e. use same param and both field groups and fields enabled/disabled at the same time.

**Comment by izharaazmi** [comment]
@infograf768 If we deal with com_fields only then it would be fine. But what I am trying to solve is to support custom logic that depends on the component itself.

In our case with `com_fields` same thing can be seen as `com_fields` would decide whether to show that menu item or not. For this com_fields may require other components which uses its features to follow certain rules viz. already we have – `custom_fields_enable` attribute.

So what we need here now is that the ability to pass the control to the component which the menu item belongs and let it decide whether to show or not.

**Comment by infograf768** [comment]
> So what we need here now is that the ability to pass the control to the component which the menu item belongs and let it decide whether to show or not.

Understand. As the PR only deals with com_fields and we do not have yet that ability, Ietme close this one again.

**Comment by izharaazmi** [comment]
@infograf768 Closed, fine. Just wanted to know whether you support this approach or have some suggestions to improve?

**Comment by infograf768** [comment]
The approach looks fine (using helpers) but I am afraid we find out it implies important changes and may not be ready for 3.8.1 (or even the 3.x.x series) as 3pds using custom fields would have to modify their code.

**Comment by izharaazmi** [comment]
If I do it, I't make sure it is compatible to 3.x
