### ISSUE TITLE
Issue with read more under articles

### ISSUE THREAD

**Issue by Shazrina1994** [joomla/joomla-cms#18139]
Earlier i got the article with readmore but after upgrdings now not showing it.

### Expected result
should be a readmore when we already inserted at a specific place in articles

### Actual result
there is no readmore rather whole article being displays

**Comment by ghost** [comment]
@Shazrina1994 thanks for reporting. Please give more Details (Joomla-Version, Template, URL, ...).

**Comment by brianteeman** [comment]
Using my crystal ball and my super powers to read minds I am going to say that you are on a single article page. The READMORE button only displays on a blog category page.

**Comment by ghost** [comment]
> Earlier i got the article with readmore but after upgrdings now not showing it.

I understand this Sentence as talking about same Page: before Update with, after Update without Button as i don't own a Crystal Ball :-)

**Comment by brianteeman** [comment]
I am closing this due to lack of response. It can always be reopened.
