### ISSUE TITLE
Front end problem after updating joomla from 3.7.5 to 3.8

### ISSUE THREAD

**Issue by saydry** [joomla/joomla-cms#18148]
### Steps to reproduce the issue

Update from Joomla 3.7.5 to 3.8

### Expected result

Successful update

### Actual result

My website works well with 3.7.5, but after updating to 3.8 the website is not loading as expected.
there is no problem with the back end and the database but the front end shows just home page without any css, and it shows my menu as links so if I try to click on one of these links it stays on the same page despite the URLs are good.
I think the problem comes from the libraries files but I don't have any ideas how to fix it.
Any help will be appreciated!

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns Joomla coding. For this Reason closing this Issue, thanks.
