### ISSUE TITLE
No value on joomla update: files extracted

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#18142]
### Steps to reproduce the issue

https://github.com/joomla/joomla-cms/blob/6e07ca6fadd8a5d1db3337cf0357d782646f5411/administrator/components/com_joomlaupdate/views/update/tmpl/default.php#L59

https://github.com/joomla/joomla-cms/blob/17a45385aeb6f7bffadf68408bd2a5c91bb66684/media/com_joomlaupdate/js/update.js#L269

### Actual result

![ff](https://user-images.githubusercontent.com/876623/30944279-f913534e-a3f6-11e7-8052-f92ad42739a9.JPG)

### System information (as much as possible)

J3.x

**Comment by mbabker** [comment]
The JavaScript should be referencing `data.files` it seems.  No `lastfile` is set in the PHP generating the response data.

**Comment by 810** [comment]
confirmed, i will create a pr.
