### ISSUE TITLE
Clean Cache  3.8

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-cms#18151]
### Steps to reproduce the issue
go to administrator/index.php?option=com_installer&view=update in your backend

Select 'clear cache' and this is what happens. Clear and clean cache seem a bit muddly and the names should be more descriptive to show the difference. I don't think that the message should be cleared updates when I have pressed clear cache.

![clearcache](https://user-images.githubusercontent.com/736887/30975757-f4e0073a-a46a-11e7-8b2f-7b716a71df2c.png)

### System information (as much as possible)
upgrade to 3.8

**Comment by brianteeman** [comment]
I guess you forgot that you installed a cache cleaner plugin from nonumber :)

Closed as not a core issie

**Comment by Hils** [comment]
Many moon ago! Thank you Brian.
