### ISSUE TITLE
3.7.5 updated to 3.8 - front end looks fine, but back end non-functional

### ISSUE THREAD

**Issue by rotech1** [joomla/joomla-cms#18152]
fully updated 3.75 installation, run 3.8 update in joomla as urged by nag screen

### Expectedresult
successful update?

### Actual result
Just tried upgrading my DEV server, and immediately following the 'upgrade', (upgrade appeared to be successful - no error messages!) it went to all white screen under the Admin menu.

All the admin menus still "function", but nothing displays in the screen. Front end seems 100% functional, but back end crippled with
**"Error 0 Call to undefined method JadminCssMenu::AddChild()"**

![j38_updateglitch](https://user-images.githubusercontent.com/5864531/30981012-e1373830-a437-11e7-9131-dc6d6cbca72c.png)

Can't test backend further as nothing displays in main window regardless of what menu item is selected...

### System information (as much as possible)
before update:

PHP Built On | Linux [redacted] 2.6.32-696.10.1.el6.x86_64 #1 SMP Tue Aug 22 18:51:35 UTC 2017 x86_64
Database Version | 5.5.55
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 5.6.31
Web Server | Apache
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 3.7.5 Stable [ Amani ] 14-August-2017 12:09 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

Backend template is Isis

**Comment by Bakual** [comment]
That's caused by a incompatible 3rd party extension.

**Comment by rotech1** [comment]
Well, back to the sleuthing, then!  :( 

Back end template is Isis, so isn't that CORE? Or you are saying that the main window of backend is being over-ridden somehow by a 3rd-party extension?

All of our extensions were 100% compatible with Joomla 3.7.5 - I really don't expect a minor release to break stuff... Just thought I would pass this along since I am sure Core developers want to be fully aware of how their changes interact with the larger eco-system!

**Comment by Quy** [comment]
Are you using SP Page Builder? If yes, check out this #18034.

**Comment by rotech1** [comment]
Not using SP pagebuilder...
3rd party extensions are
Community Builder/CBsubs
Kunena Forum
K2
( all updated, and all those devs swear they are 3.8-compatible... )

**Comment by Quy** [comment]
Also see this: https://docs.joomla.org/J3.x:Call_to_undefined_method_JAdminCssMenu::addChild_in_backend

**Comment by rotech1** [comment]
Thanks! "Changes in the administrator menu module to support new features." - where can I find the exact places where said changes were made?  
Is it this change?

https://github.com/joomla/joomla-cms/commit/220802a6f6d2ab431ab938057220a5f51f3184dd

I don't see how that's relevant, but I don't see anything more recent in there...

**Comment by Quy** [comment]
Please consider posting to the [Migrating and Upgrading to Joomla! 3.x forum](https://forum.joomla.org/viewforum.php?f=710) for further assistance.

**Comment by ggppdk** [comment]
Edit configuration.php
change
`public $debug = '0';`
to
`public $debug = '1';`

change
`public $error_reporting = 'default';`
to
`public $error_reporting = 'maximum';`

Do you now get the file at where the error occurs ?

**Comment by rotech1** [comment]
Ah-ha! yes it's something that was in an extension.
`Call to undefined method JAdminCssMenu::addChild()
.../administrator/modules/mod_jomclassifiedsmenu/tmpl/default_enabled.php:15`

`$menu->addChild(new JMenuNode(JText::_('JOMCLASSIFIEDS'), '#'), true);`

JMenuNode has been deprecated? (sigh) I guess I have some digging to do...

**Comment by Quy** [comment]
@rotech1 Since this is a 3rd party extension issue, this can be closed.

**Comment by rotech1** [comment]
OK! I found THIS, so I'm on my way to hacking up a fix!

https://fossies.org/diffs/Joomla/3.7.5-Stable-Full_Package_vs_3.8.0-Stable-Full_Package/administrator/modules/mod_menu/menu.php-diff.html

**Comment by wojsmol** [comment]
@rotech1 This is simple filed update. Open a topic as suggested and will assist.

**Comment by ggppdk** [comment]
@wojsmol 

since we have already assisted @rotech1 above to find the issue
you mean open it in Joomla forums ? (not here , right ?)

People are asked to update 3rd party extensions,
but in some cases do not update non-free extensions ... (some of the issues opened here lately were because of not updating non-free extensions because the subscription has expired)

Also @rotech1 , why are you tryng to update the extension manually ?
better try to update the 3rd party (non-free) extension to its "latest" version (if an updated version is available)

**Comment by wojsmol** [comment]
Yes as requested in https://github.com/joomla/joomla-cms/issues/18152#issuecomment-332930273.  You're right that it's better to update paid extensions from official sources and not modify them.
BTW Do you remember the issue number of the about first level categories not displayed?

**Comment by rotech1** [comment]
I am using a customized version of the extension, so am obligated to maintain it manually. The maker hasn't released their 3.8-fixed version yet, but when they do ( they promise to in a couple of days!) I will look at their changes.
