### ISSUE TITLE
Article "Layout" option is not included at a Category Menu Item Level

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-cms#18150]
### Steps to reproduce the issue

I'm talking about this option:
**Articles -> New/Edit -> "Options" Tab -> "Layout" option.**
which is the one that allows you to assign a custom template override for an article.

![](https://cloud.githubusercontent.com/assets/8235763/23739209/98bd5538-049d-11e7-8169-5a5da62ac155.JPG)

### Actual result

This option is included as an option for individual Article in the Article Manager, but it's NOT included at a Menu Item Level when creating a Category Menu Item.

### Expected result

For consistency and usefulness, it would expected and useful to have this option available as part of Category Menu Items as well, similar to all the other Article Options. So it should be available as part of these Menu Items Types:
- Articles > Category Blog
- Articles > Category List
- Articles > Featured Articles

### Additional comments

This would allow to assign a custom template override for all articles displayed under that Menu Item (so for example, all articles belonging to a category) instead of having to individually assing the custom template override to each individual article one by one.

**Comment by Bakual** [comment]
Because the menu items are based on said layouts. It doesn't make sense to select a menuitem for a specific layout and then change that layout in its parameters.
Eg "category blog" and "category list" refer to the same view, but different layouts within that view.

**Comment by AndySDH** [comment]
Oh - I understand.
But if you put it like this, shouldn't that mean that when you create an alternative article layout, it should become available as a new menu item selectable under the Article Menu Types?

**Comment by AndySDH** [comment]
Oh - I understand. Thanks for the clarification, I missed that step.

But it would still make sense to have this Article layout option as part of the Category views. Currently, there is no way to make a Category Blog/List Menu Item drill down to the custom Article Layout and use that instead of the default one.

In a real world use scenario, one would want to create an alternative article layout and want to use that for all articles belonging to that certain category/menu item, instead of having to manually set it one by one.

**PS:** I edited my original post to better reflect this correction by Bakual.

**Comment by Bakual** [comment]
You should be able to select the article layout in the "category blog" and "category list" menuitems. See the first parameter in the "Options" tab.

**Comment by AndySDH** [comment]
Wait, what!? Turns out this was added in 3.8.0, I guess!? I was like, wait, I'm sure it's not there unless I'm blind. You got me curious, so I updated my dev site from 3.7.5 to 3.8.0 (I was waiting due to the bugs) and now the option is there. Wasn't there before. Well, then I guess you guys anticipated me here.

Edit: Found it -> #14802

I guess you can mark this as retro-fixed in 3.8.0 LOL

**Comment by Bakual** [comment]
Ah true, it is new in 3.8.0 😄 

I'm closing this then.
