### ISSUE TITLE
[4.0] - install Undefined class constant 'RELEASE'

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#18154]
### Steps to reproduce the issue
install 4.0 staging

### Expected result
all ok 

### Actual result
![screenshot from 2017-09-28 21-11-26](https://user-images.githubusercontent.com/181681/30985849-e8fcdf34-a491-11e7-9e24-d0596861e539.png)

**Comment by mbabker** [comment]
Side effect of https://github.com/joomla/joomla-cms/pull/18129 - looks like there's some work to do

**Comment by brianteeman** [comment]
I can confirm this error

**Comment by ghost** [comment]
closed as having Pull Request #18171<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18154">issues.joomla.org/tracker/joomla-cms/18154</a>.</sub>
