### ISSUE TITLE
ratingCount: 0 (The value provided for ratingCount must be a positive value.)

### ISSUE THREAD

**Issue by eshiol** [joomla/joomla-cms#18163]
### Steps to reproduce the issue
Create a new article.
Enable the option Show Voting.
Use the Google Structured Data Testing Tool to test the page.
### Expected result
No errors reported
### Actual result
ratingCount: 0 (The value provided for ratingCount must be a positive value.)
### Additional comments
plugins/content/vote/tmpl/rating.php shows the microdata aggregateRating even if the article has no rating.

**Comment by ghost** [comment]
Status on Issue Tracker now "Confirmed".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18163">issues.joomla.org/tracker/joomla-cms/18163</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #18166<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18163">issues.joomla.org/tracker/joomla-cms/18163</a>.</sub>

**Comment by Quy** [comment]
Another PR #18167

**Comment by Quy** [comment]
@franz-wohlkoenig You noted it to close, but it has not yet.
