### ISSUE TITLE
Uncaught Error: cannot call methods on tooltip prior to initialization; attempted to call method 'destroy'

### ISSUE THREAD

**Issue by jaimestuardo** [joomla/joomla-cms#18168]
### Steps to reproduce the issue

- Login to Administration panel
- Browse to articles editor
- Click on any article to edit it or click New button
- Watch developer tools, for example, by pressing F12. I see the error: Uncaught Error: cannot call methods on tooltip prior to initialization; attempted to call method 'destroy'

### Actual result

I think this JavaScript error is affecting modal dialog displays caused by buttons placed at the bottom of the editor area. When I press any button that should open a modal dialog, a new page with modal dialog content is opened. This kind of behaviour is typical when a JavaScript error occurs before.

### System information (as much as possible)

PHP Version 7.1.9
Joomla! 3.8.0 Stable [ Amani ] 19-September-2017 14:00 GMT
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
MySQL version 5.6.35

### Additional comments

I thought a plugin should be affecting this, so I disabled all editors-xtd plugins but the error is still happening.

**Comment by tonypartridge** [comment]
Working fine here, make sure to check for system plugins and content plugins.

**Comment by wojsmol** [comment]
@tonypartridge This but was fixed in 3.7.x, may by @jaimestuardo have a js override.

**Comment by jaimestuardo** [comment]
No override here. What js is supposed to be the cause of the issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18168">issues.joomla.org/tracker/joomla-cms/18168</a>.</sub>

**Comment by brianteeman** [comment]
Can you see if this PR fixes it for you https://github.com/joomla/joomla-cms/pull/15951

**Comment by jaimestuardo** [comment]
Yes.... it worked now... thanks.... I am wondering why that correction is not included in official Joomla release.

**Comment by brianteeman** [comment]
OK closing this. It hasnt been merged as there were not enough people testing it
