### ISSUE TITLE
Deleting Users - Reassign content

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#18160]
So this has been an issue for a while, you delete a user but other components still refer to the UID with JUser. This isn't great.

What are the thoughts on when deleting a user, when ask whom the content should be assigned too if any exists of course. Then put the deleted user ID's into another table and JUser looks in this table if the first load was unsuccessful, and we could have default username and name of: User Deleted 

So the admins can update and re-assign within their component.

**Comment by brianteeman** [comment]
Wouldnt an easier fix (and covers more scenario) being to create a batch process to allow changing the user eg select all articles for user a and batch change them to user b

**Comment by tonypartridge** [comment]
@brianteeman We can do that. But users by default won't know or think of articles that are existing. Instead they just delete users as they just want to do that and don't know/care about anything else as they are focusing on doing a single task.

A prime example, is when a site is built users tend to use an admin account and then just delete it, or at least this is what I have seen. But all content and modules etc are created under that user. Ideally we should have a reassign users items to X user and click to proceed. Maybe with a plugin hook, so other developers can have their data updated too. 

But for the developers and thousands of extensions out there that do not have it, it would be good for JUser to show name/email/username as a deleted one. So people then know they need to update it?

**Comment by ghost** [comment]
Would be a fine Enhancement in Usability as @tonypartridge wrote. Its happened often if starting using Joomla like you wrote above.

**Comment by Joomv** [comment]
Both actually would be good.
The Stack Ideas approach of nominating a user ID for "orphaned" content alongside being able to batch change the author would be a winner as far as I'm concerned.

**Comment by brianteeman** [comment]
We did have a discussion about this before - I think maybe @bakual will remember the link.

**Comment by alikon** [comment]
to me sounds like quite an easy solvable problem  if we finally proper implement foreign keys

**Comment by tonypartridge** [comment]
How will foreign keys solve it? Forgive my ignorance, but foreign keys could only work on core items and you'd have to write a cleanup script.. because you can't expect developers to adapt their working component to support them globally. 
-- 
Tony Partridge

**Comment by Bakual** [comment]
@brianteeman I think you mean #12881 (and #12908) where we show the ID for deleted users.

As for creating a different table with the deleted entries - every database table specialist will kill you for that :smile: 
If you delete something, it is gone. If you don't want to delete it, you don't delete it. You change the state to "trashed" like we do for articles (but not for users). However usually when you delete a user, you want to have it gone, not being still present with a trashed state.

As for forgeign keys, that would indeed solve it but can't be done in J3 and likely also not in J4. But we certainly should have that goal in mind.

> How will foreign keys solve it? Forgive my ignorance

In Joomla we have for example a `catid` field in #__content which is a reference to the `id` field in #__categories. But that reference is only done in PHP, not at the database level. For the database, it's just two unconnected tables.
Now database like MySQL allow to specify relations between tables, thus the name relational database :smile: . If you do define such a relation, you tell the database that this `catid` field in #__content is a "foreign key" to the `id` of the #__categories table.

Now if you delete the category, the database will check that all references of that category are deleted as well. If not, it will throw an error and prevent the delete. This means you first have to change all references before you can delete the category.
There is another mode where it would actually also delete all referenced items, but that's usually not what you want (eg if you delete a user, it would delete all articles from that user as well).

**Comment by alikon** [comment]
sorry for my brevity @tonypartridge you can find intersting reading http://www.sqlteam.com/article/using-set-null-and-set-default-with-foreign-key-constraints
in this case will be usefull `on delete set null`

**Comment by tonypartridge** [comment]
But that’s only really useful for new component adopting it and core
items?  Not solving the core problem.

Proposed solution:

We add a plugin hook to allow checking if any items exist under this user
on delete, if some are found we prompt the user whom they want to allocate
them too, allocate them and delete.

For users trying to be loaded whom cannot be found, we load in dummy data
of User Deleted. Please re-assign. For name.

Many thanks
-- 
Tony Partridge

On 29 September 2017 at 13:46:59, Nicola Galgano (notifications@github.com)
wrote:

sorry for my brevity @tonypartridge <https://github.com/tonypartridge> you
can find intersting reading
http://www.sqlteam.com/article/using-set-null-and-set-default-with-foreign-key-constraints
in this case will be usefull on delete set null

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/joomla/joomla-cms/issues/18160#issuecomment-333116729>,
or mute the thread

**Comment by brianteeman** [comment]
Imagine a site with a thousand users and ten thousand content items
Now try to delete 900 users
You will have to check all ten thousand content items to see if the user you are deleting was an author of any content.. And then you will have to repeat that 900 times
:)

**Comment by tonypartridge** [comment]
Yep you would! But it’s kinda a given, you could have multiple assignments
in a single screen.

As a temporary solution I’ll add in the batch author change.

But we need something better. I hate to mention it, but WP handles it
better although slower.

Maybe only run the check on users whom have creation rights?

-- 
Tony Partridge

**Comment by brianteeman** [comment]
the scenario i described would kill the site

**Comment by tonypartridge** [comment]
It would kill the site we unable to load user content messages too if they
had created content…

-- 
Tony Partridge

On 29 September 2017 at 14:19:25, Brian Teeman (notifications@github.com)
wrote:

the scenario i described would kill the site

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/joomla/joomla-cms/issues/18160#issuecomment-333123953>,
or mute the thread

**Comment by brianteeman** [comment]
No #12908 should have meant that if the user is not found then the id is displayed - at least that is what happens in the admin i didnt check the frontend

**Comment by tonypartridge** [comment]
It probably, does now. I’ve just being theoretical which is probably wrong
since that PR.

-- 
Tony Partridge

On 29 September 2017 at 14:31:42, Brian Teeman (notifications@github.com)
wrote:

No #12908 <https://github.com/joomla/joomla-cms/pull/12908> should have
meant that if the user is not found then the id is displayed - at least
that is what happens in the admin i didnt check the frontend

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/joomla/joomla-cms/issues/18160#issuecomment-333126925>,
or mute the thread

**Comment by tonypartridge** [comment]
Just had it on a clients site, the message was still output in the backend
atleast with the users ID in the user box.

-- 
Tony Partridge

On 29 September 2017 at 14:32:34, Tony Partridge (admin@xws.im) wrote:

It probably, does now. I’ve just being theoretical which is probably wrong
since that PR.

-- 
Tony Partridge

On 29 September 2017 at 14:31:42, Brian Teeman (notifications@github.com)
wrote:

No #12908 <https://github.com/joomla/joomla-cms/pull/12908> should have
meant that if the user is not found then the id is displayed - at least
that is what happens in the admin i didnt check the frontend

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/joomla/joomla-cms/issues/18160#issuecomment-333126925>,
or mute the thread

**Comment by Bakual** [comment]
From memory, the warning is generated by JUser itself and can't be supressed in the formfield. It kind of make sense to show the warning anyway. All I did back then was showing the ID instead of an empty field.

**Comment by coolcat-creations** [comment]
Actually a user should be able to delete himself too.
What will happen to the generated content (core and extensions?)
There must not only be a possibility to reassign an author by badge process but also a decision done by the user what will happen with private data. What if there are any orders in a shopcomponent, what if the articles should be deleted by deleting the user, what if they should stay, as well as the name from the original author even if he/she is not an user anymore... 
I think this process should be careful planned especially regarding upcoming laws.

**Comment by tonypartridge** [comment]
This issue is we don't have control over other components. We could add a Delete My Account function to the frontend easy enough.

and suspect we need to add in a hook for on deleting usings that we check all extensions for and provide an updated userid which run's the extensions function as they wish for the content to be updated to assign the content too. Maybe we add in a dummy user i.e. Deleted User which cannot be seen but can be referenced.

**Comment by coolcat-creations** [comment]
Yes, but what happens if a user deletes him self, will his articles be unpublished, assigned to someone else, assigned to "deleted user", will the articles be deleted because it's private content  or will they be still there and so on. Will there be a possibility to restore the user within a period of time (like facebook does) etc.

**Comment by brianteeman** [comment]
@coolcat-creations I have a guest blog post from a GDPR expert almost ready to be published that will address this question i hope

**Comment by infograf768** [comment]
Please translate "GDPR".

**Comment by ghost** [comment]
"General Data Protection Regulation" > https://volunteers.joomla.org/teams/gdpr-working-group

**Comment by Webdongle** [comment]
And what about quotes of users if a Joomla site has a forum ?  Posts will have quotes of the users or if deleted ... posts that make less sense because the reference was removed from the post.

@infograf768 
https://www.eugdpr.org/

@brianteeman 
> I have a guest blog post from a GDPR expert almost ready to be published

Guest blog post where ?  
Who is the expert ?  What qualifies them as an expert ?

**Comment by mandville** [comment]
> "General Data Protection Regulation" > https://volunteers.joomla.org/teams/gdpr-working-group
should that be
https://volunteers.joomla.org/teams/compliance-team

**Comment by coolcat-creations** [comment]
@Webdongle That is up to the Forum Extension Developer to implement into his "user is deleted" logic.

**Comment by Webdongle** [comment]
@coolcat-creations 
Yep agreed ...  if a webmaster has a forum (or comment system) and that extension also deletes the posts fine.  But if the extension doesn't or the user is quoted in other posts then allowing Joomla user self deletion would leave that users footprint.  Therefore that would be problematic.

That's why imho if Joomla core allows for users to self remove that it should be an optional setting (No as default).  That way the webmaster can remove all references on request rather than the user just deleting the account with the website.

On a side note ... deletion request could be clearly stated in the sites T&C.  And the T&C box/link could be an option (for the webmaster) on the Registration form instead of the user plugin.

**Comment by tonypartridge** [comment]
The delete method can be hooked into by plugins already if I remember correctly so extension devs could trigger deleting on their point.

I still think my argument stands of having a hidden single deleted user user, if you load a user that doesn’t exist it should return a false user of ‘User no longer exists’.

**Comment by alikon** [comment]
with #19023 i've tried to manage user deletion, instead of creating ghost users, with the help of the `onUserBeforeDelete` event, we can halt the delete process if the user have some "contents", in this way the webmasters can apply their wokflows to handle this situation

**Comment by tonypartridge** [comment]
@alikon,

The problem with that is you cannot account for knowing where it is used and if the developer has used it.

The solution to create a ghost user to me is better with a re-assign content for core components on deletion

**Comment by alikon** [comment]
in my view you can with `onUserBeforeDelete` any developer can implement they desired workflow

**Comment by brianteeman** [comment]
I agree with Tony on this

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/issues/18160#issuecomment-333121414

**Comment by Bakual** [comment]
Why do you need a ghost user for this? You can as well just mark it as ghost if the user is not found. Because it's exactly that.
If your concern is the message, I'm sure we could look into changing JUser or if we can catch the message.

**Comment by tonypartridge** [comment]
@thomas that’s my point if User is not found we can mark as a ghost User with username = notfound and name = User not found or a translation people approve off.

**Comment by PhoenixUK** [comment]
Would it be possible / best to choose rather than 'notfound' something that links more to the upcoming GDPR and an internationally known choice, such as 'Redacted User' whereby any of these listings, could also be linked to / have a link to an explanation of what this means in real terms, to other site visitors?

> The Merriam-Webster Online dictionary gives a third sense of redact:

**3:** to obscure or remove (text) from a document prior to publication or release

So, nothing since the turn of 2018 on any of the above, how do things stand with this whole matter please anybody?

> @tonypartridge 

 that’s my point if User is not found we can mark as a ghost User with username = notfound and name = User not found or a translation people approve off.

**Comment by mbabker** [comment]
> Would it be possible / best to choose rather than 'notfound' something that links more to the upcoming GDPR and an internationally known choice, such as 'Redacted User' whereby any of these listings

If a user record is not found in the database this does not mean that the account is redacted as it relates to removal via privacy regulated requests (i.e. GDPR), so no, the name shouldn't default that way.  The only way to do that would be to retain the user database record after sterilizing it of all PII (and I get the feeling somebody is going to argue the database PK is PII and needs to be sterilized now...).

**Comment by Joomv** [comment]
Stackideas do something that might work here.  They have a setting for "orphaned items" that allows you to select a user to assign them to on deletion of the author.  Not sure this is a good solution but thought it worth mentioning.

**Comment by Joomv** [comment]
and I repost ... time to turn off computer!

**Comment by Webdongle** [comment]
Patch created https://issues.joomla.org/tracker/joomla-cms/19023

**Comment by ghost** [comment]
closed as having Pull Request #19023
