### ISSUE TITLE
 [J3.8.0] Backend articles manager, articles in subcategories are not listed when a category is selected in category filter

### ISSUE THREAD

**Issue by hrefferh** [joomla/joomla-cms#18178]
At [https://issues.joomla.org/tracker/joomla-cms/18157](https://issues.joomla.org/tracker/joomla-cms/18157 "https://issues.joomla.org/tracker/joomla-cms/18157") I reported a bug. But as you mentioned, it is not a bug. It is a huge change with Search Tools. And I didn't find any note about.  
Different from versions < 3.8 you can't display all articles of a parent or root category by just selected it. Levels are ignored.

NO YOU HAVE TO SELECT ALL CHILD CATEGORIES ONE BY ONE. THAT'S ENOYING!

With this new behavier I have to add all this douzens of child categories one by one. I cannot imagine this is wanted!

So please bring back functionality where listing all articles of a parent or root category is done by just selecting it!!!

**Comment by ghost** [comment]
can you give please a Link on the Forum-Thread what was there discussed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18178">issues.joomla.org/tracker/joomla-cms/18178</a>.</sub>

**Comment by ggppdk** [comment]
Confirmed on testing and on code review

@hrefferh 
**Please change title** to something more appopriate,
-  this will help others understand the issue without reading all your description:

**Change title to**:
[J3.8.0] Backend articles manager, articles in subcategories are not listed when a category is selected in category filter

This is easy to fix, (restoring old behaviour) 
-- if only 1 category is selected,

but if selecting multiple categories, then listing articles in their subcategories will require some more work (and more testing e.g. max-levels filter might be needed to be ignored)

**Comment by ggppdk** [comment]
@franz-wohlkoenig 

I have made a PR
Can you change title (please see above) before closing this issue ?

**Comment by ghost** [comment]
closed as having Pull Request #18179<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18178">issues.joomla.org/tracker/joomla-cms/18178</a>.</sub>

**Comment by hrefferh** [comment]
@franz-wohlkoenig,
@ggppdk 
THANK YOU VERY MUCH!

**Comment by ghost** [comment]
@hrefferh can you please test #18179?

**Comment by hrefferh** [comment]
Yes, it works!!!

Thank you very much again! Very Kind & Great!

**Comment by ghost** [comment]
@hrefferh can you please mark your test at #18179 as successfully at Issue Tracker?

- Please open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/18179)
- Login with your github-Account
- Click on blue "Test this"-Button above Authors-Picture
- mark your Test as successfully
- hit "submit test result"
