### ISSUE TITLE
[com_fields] Lack of progress

### ISSUE THREAD

**Issue by mrhossein** [joomla/joomla-cms#18173]
Good time
I already said in another report that in a new Joomla component named fields, we can not add to the different parts of a class field, and therefore the display of fields in different formats does not look good.
With Joomla 3.8, this component did not make any difference. That's why I decided to publish it again so that in version 4 it might be worth considering the following features.

1- Ability to create a separate and custom class for the field title, field tag and box containing the two.
2- The ability to follow the plugin. Insert a field in the contents of the class. Fields of the same entry when the custom class is defined for fields in a given article.
3- Plugin to create comparison between two field fields that use the same fields.

My previous link in this thread:
https://github.com/joomla/joomla-cms/issues/17625

I apologize if this text is not written in plain text.
Thank you.

**Comment by mrhossein** [comment]
Thank you.
But I still did not receive a clear answer from you to solve my problem.
Please give me the code you need to resolve this issue if I may add my Joomla!
Thank.

**Comment by wojsmol** [comment]
cc @laoneo

**Comment by tonypartridge** [comment]
So this is more of a feature request and you are not happy with the rate of progress of the features you wish for, is that correct?

**Comment by laoneo** [comment]
Just my 2 cents here. I would not introduce more classes, if you need to alter the output, then you should use layout overrides.

**Comment by mrhossein** [comment]
Ok yes
Because the field is not like a module or something else, and really two of its important parts should be compatible with different templates to be beautiful.
And the bigger problem is that the plugin always follows the general class and you've done a lot of effort when the fields of a particular article are customized and you use the plugin to insert the fields in the article.
How do I cancel the layout?
I use Joomla, so I do not need programming complexity.

**Comment by tonypartridge** [comment]
The problem in that scenario is you still need someone to develop the classes, and who decides what should be loaded. You may want something completely different to me. The idea to custom fields is they allow Core output and flexibility with core support.

**Comment by mrhossein** [comment]
Maybe I would say it hard.
By default, every field in Joomla has no more than three parts.
I can implement these three classes in my template code and assign them the desired CSS codes. But I can not do this for each group of fields separately. Because there's no place to create a child's class.
What do you think is more complete and better than what I see in the image below?
[image](http://oi63.tinypic.com/15ria0x.jpg)
http://oi63.tinypic.com/15ria0x.jpg

**Comment by mrhossein** [comment]
Did you see the picture?
what is your opinion?

**Comment by mrhossein** [comment]
Did you see the picture?
what is your opinion?

**Comment by ghost** [comment]
Any more Opinion on this Feature Request? If not, will close it.

**Comment by alor702000** [comment]
Re : Error of the file cache storage

go to configuration.php and put:
public $cache_handler = '';

**Comment by ghost** [comment]
@alor702000 please don't post same Comment at different Issues.

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 26th November 2017.

**Comment by coolcat-creations** [comment]
Isn't that https://github.com/joomla/joomla-cms/pull/18431 ?

**Comment by ghost** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened.
