### ISSUE TITLE
menu - article category blog navigation new routing in joomla 3.8.0

### ISSUE THREAD

**Issue by inolibero** [joomla/joomla-cms#18170]
### Steps to reproduce the issue

I would point out that when creating a blog category menu, the second page produces 

### Expected result
the url: news.html?start=2

**Comment by brianteeman** [comment]
Yes that is correct - what did you expect it to be

**Comment by tonypartridge** [comment]
@brianteeman I think that is what @inolibero expects. But actually it's the item count dispalyed i.e.

?start=5

is page 2 on my system. I suspect he would want it to start on page two or it's sef'd like:

news/page-2.html

**Comment by mbabker** [comment]
Joomla core doesn't SEF pagination segments.  As for the start param, it's actually a count (using a 0-index) of the number of items to start at.  Using the developer network as an example, https://developer.joomla.org/news.html?start=5 is page 2 of the news area, each page shows 5 items, so the page is starting at item 6 (start=5 when counting from a 0-index).

**Comment by tonypartridge** [comment]
Can we close this? Expected behaviour

**Comment by ghost** [comment]
closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18170">issues.joomla.org/tracker/joomla-cms/18170</a>.</sub>
