### ISSUE TITLE
[4.0] Admin pages do not zoom in properly with "Zoom Text Only"

### ISSUE THREAD

**Issue by rgmears** [joomla/joomla-cms#18181]
### Steps to reproduce the issue

Go to any page in the Admin section. Select "Zoom Text Only" under View in the browser menu.
Either CTRL/scroll in or go to View > Zoom > Zoom In

### Expected result

![j4-media-manager-zoom-in](https://user-images.githubusercontent.com/4270063/31055216-7ae007f6-a685-11e7-89df-0f25d0690d76.gif)

### Actual result

![j4-media-manager-zoom-in-text](https://user-images.githubusercontent.com/4270063/31055222-92ffeda6-a685-11e7-824e-80ea94d03996.gif)

### System information (as much as possible)

Joomla! 4 Administration

### Additional comments

This occurs on all pages not just the Media Manager page. 
I do not know how to fix this. Am simply bringing it to people's attention.

**Comment by brianteeman** [comment]
AFAIK this is a browser specific issue and cannot be fixed

**Comment by brianteeman** [comment]
Which browser is that as i dont have that option in chrome, firefox, edge or internet explorer

correction - i see this is a firefox only option

**Comment by C-Lodder** [comment]
Are we supporting browser zoom at such a late stage in the J lifecycle?

@jonrz @armenos

**Comment by brianteeman** [comment]
@C-Lodder this is just text zoom not browser zoom and only for firefox

**Comment by C-Lodder** [comment]
@brianteeman - same question applies then

**Comment by brianteeman** [comment]
I would suggest it is impossible to resolve (and why the browsers now use or default to page zoom)

**Comment by ghost** [comment]
@rgmears your Opinion?

**Comment by rgmears** [comment]
If you want any further comment/contribution from me speak to Brian Teeman.

**Comment by C-Lodder** [comment]
@rgmears - The question was asked at you

**Comment by ghost** [comment]
@rgmears as far as i understand the Issue its not to solve in Core, so i asked what you mean as Issue-Creator.

**Comment by ciar4n** [comment]
I think this issue is related the nav icons been set to a px line-height instead of rem... https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/scss/blocks/_header.scss#L62

To replicate you must set the **Minimum font size** in FF (lang & appearance -> advanced).

We should be ok supporting the standard browser zoom.. zooming will trigger media queries in the same manner as smaller screens.

Alas with the talk of a new admin design from UX/UI.. fixing these issues in the current status quo seems pointless?

**Comment by C-Lodder** [comment]
Yeah it should probably use flexbox for this rather than the line-height

**Comment by rgmears** [comment]
The way to fix this is to change the header height from 48px to auto 
and remove the width and height from "icon-images mediamanager" which is on the SPAN inside of the H1 element. 
Also remove max-height from .main-nav li a.

**Comment by Quy** [comment]
Is this still an issue with the new backend template?

**Comment by ghost** [comment]
Closed as no Answer. It can reopened if needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18181">issues.joomla.org/tracker/joomla-cms/18181</a>.</sub>
