### ISSUE TITLE
Error: Found mime type (file format) invalid

### ISSUE THREAD

**Issue by lsavino59** [joomla/joomla-cms#18187]
### Steps to reproduce the issue
I can not load PDF files with the latest version of joomla (3.8.0) from the Media menu: Error: Found mime type (file format) invalid.
Web server: Apache/2.4.10 (Win32) - OpenSSL/1.0.1i - PHP/5.5.15 - MySQL 5.6.20 - PHP Extension: mysqli

**Comment by ghost** [comment]
closed as duplicate Report #16238<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18187">issues.joomla.org/tracker/joomla-cms/18187</a>.</sub>
