### ISSUE TITLE
Joomla update component version 3.6.2

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-cms#18184]
### Steps to reproduce the issue
In Joomla 3.8.0 fresh install I can find in the Extensions--> Manage the "Joomla! Update" component version 3.6.2, but from the XML update site: https://update.joomla.org/core/extensions/com_joomlaupdate.xml  the latest version is 3.6.1.

Also after install the com_joomlaupdate-3.6.1.zip in Joomla 3.5 I can see the "Joomla! Update" component version 3.6.2 in the Extensions--> Manage
### Expected result
"Joomla! Update" component version 3.6.1

### Actual result
"Joomla! Update" component version 3.6.2

### Additional comments
![joomla_update-362](https://user-images.githubusercontent.com/1362388/31058029-fa0357ea-a6e4-11e7-94fe-961117278f70.png)

**Comment by brianteeman** [comment]
I dont see the problem. Joomla 3.8 ships with version 3.6.2 and anyone updating to 3.8 or installing 3.8 will get that version. The standalone version is only needed when we need to update the component outside of a regular joomla update for technical reasons

**Comment by brianteeman** [comment]
For reference the version number for core xml is updated automatically whenever the bump script is run
https://github.com/joomla/joomla-cms/blob/7ab744f7b320cf4334b28a69615b292bfc8747a7/build/bump.php#L217

**Comment by infograf768** [comment]
It is not a problem but this does not means it is right. 
The last version of Joomla! Update IS 3.6.1 and not 3.6.2.

**Comment by AlexRed** [comment]
yes, it is not a big problem. But now we try to write the new documentation about how to update from Joomla 3.4 or 3.5 and we need to specify to update (manualy) before the com Joomla! Update to the last version 3.6.1, because no auto update are available for com Joomla! Update and if no at the latest version the update procedure is wrong.
But after the update to Joomla 3.8 the com Joomla! Update is at the 3.6.2 version.

**Comment by brianteeman** [comment]
>  because no auto update are available for com Joomla! Update 

Strange as I got the option to update the component

**Comment by AlexRed** [comment]
in Joomla 3.4 ?

**Comment by brianteeman** [comment]
I am double checking now. But I definitely had it the other day when doing an upgrade

**Comment by AlexRed** [comment]
I got the option to update the component only in Joomla 3.6.0
for the `<targetplatform name="joomla" version="3.6"/>`    in the XML ?
http://update.joomla.org/core/extensions/com_joomlaupdate.xml

**Comment by AlexRed** [comment]
for me is better:
`<targetplatform name="joomla" version="3.[456]" />`

**Comment by brianteeman** [comment]
Sorry I should have had more coffee.

I think you have just identified why the upgrades from old versions are failing.

We limit the upgrade to 3.5.1 and from there it goes directly to the latest version which as you have identified means that it misses 3.6.0 and the update to com_joomlaupdate

The change you mentions above should resolve that I think 
@mbabker @zero-24

**Comment by zero-24** [comment]
I'm going to review that update thing when i got back to home so we can propose a fix. (https://github.com/joomla/joomla-cms/issues/18012)

**Comment by wojsmol** [comment]
@AlexRed @zero-24 Please see this old issue https://github.com/joomla/update.joomla.org/issues/41 and a article I Referenced in the issue description.

**Comment by zero-24** [comment]
That update component is obsolet please take a look into #18192 thanks. As this update path is not longer needed i'm going to close here. Thanks.
