### ISSUE TITLE
Article default layout setting is ignored after update to Joomla 3.8

### ISSUE THREAD

**Issue by mattiaverga** [joomla/joomla-cms#18189]
Choose a custom default layout in Configuration -> articles -> articles -> choose custom layout
Create a new article

Before the upgrade to Joomla 3.8, article options -> layout was set to "Use global"
After the upgrade article options -> layout is set to "From component -> default". The "Use global" option is totally missing.

**Comment by mattiaverga** [comment]
**Pre Upgrade (Joomla 3.7)**
![Pre Upgrade (Joomla 3.7)](https://issues.joomla.org/uploads/1/0ac47248304644da1f459f6844020bef.png)


**Post Upgrade (Joomla 3.8)**
![Post Upgrade (Joomla 3.8)](https://issues.joomla.org/uploads/1/81e05b48696bf7f124192fe6eaf735a1.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18189">issues.joomla.org/tracker/joomla-cms/18189</a>.</sub>

**Comment by mattiaverga** [comment]
Sorry, images are inverted in the previous comment<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18189">issues.joomla.org/tracker/joomla-cms/18189</a>.</sub>

**Comment by tonypartridge** [comment]
Please Close, already fixed with:

https://github.com/joomla/joomla-cms/pull/18061
