### ISSUE TITLE
Menu item alias

### ISSUE THREAD

**Issue by ch2856** [joomla/joomla-cms#18180]
### Steps to reproduce the issue

No an issue, but would help for beginners. 
When you create an stsyem links - menu item alias, the users usually use the same title. If he save, it will tell the user that The alias XXX is already being used by...

I will be much smarter if there will be a default add to the alias name in this situation so if the user cick save, the alias will automatically be title-alias.

**Comment by tonypartridge** [comment]
@brianteeman you will know the history why this was changed. I am thinking of putting a pull in to add a random generated number to the end of the alias and allow the saving. Users can update if they wish, thoughts?

**Comment by brianteeman** [comment]
It was changed from a date value to a regular alias so that you can have a menu item with a system link in its path such as home/system/page whereas before it would be home/737103/page

However you should only get the error message if you are creating the alias at exactly the same level in the same menu. I cant see why anyone would ever do that

**Comment by tonypartridge** [comment]
Having re thought about it and thought about Brian’s comment, the current situation is right.

If we allow setting some random generated alias then we allow users to build a poor menu structure, we don’t want that, it has a negative effect on the CMS’s view in certain communities in relation to SEO.

**Comment by ghost** [comment]
closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18180">issues.joomla.org/tracker/joomla-cms/18180</a>.</sub>
