### ISSUE TITLE
Install Joomla 3.8.0

### ISSUE THREAD

**Issue by RvdM999** [joomla/joomla-cms#18193]
### before
release 3.8.0 available Press Install

Button Install the update

### Expected result
New version installed: 
provider https://daffy.10eurohost.nl
 
Updatepakket URL 	https://downloads.joomla.org/cms/joomla3/3-8-0/Joomla_3.8.0-Stable-Update_Package.zip 

### Actual result
Er heeft zich een fout voorgedaan.

    0 SSL: certificate subject name 'joomla-org.directrouter.com' does not match target host name 'downloads.joomla.org' 

Terug naar controlepaneel

### System information (as much as possible)
Instellingen 	Waarde
 
PHP gebouwd op 	Linux daffy.10eurohost.nl 2.6.18-419.el5 #1 SMP Fri Feb 24 22:47:42 UTC 2017 x86_64
Database versie 	5.5.52
Database collatie 	utf8_general_ci
Collatie van de databaseverbinding 	utf8mb4_general_ci
PHP versie 	5.6.19
Webserver 	Apache
WebServer naar PHP interface 	cgi-fcgi
Joomla! versie 	Joomla! 3.7.4 Stable [ Amani ] 25-July-2017 11:11 GMT
Joomla! Platform versie 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Gebruikersagent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0 

### Additional comments

provider comments on SSL:
 Joomla heeft nagelaten het SSL certificaat voor hun website ook geldig te maken voor joomla-org.directrouter.com.
Hier kunnen wij helaas weinig aan doen. 

SO: updating Joomla version to 3.8.0 directly from website SystemControl screen doesnot work (repeated tries for more than 10 times)
provider cannot or won't help for any solution
have to install from the zip-file myself: never done that; don't know where to continue after downloading the zip-file (upgrade as well as full package)

**Comment by wojsmol** [comment]
@RvdM999 Please see [this](https://forum.joomla.org/viewtopic.php?p=3494187#p3494187) forums post.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18193">issues.joomla.org/tracker/joomla-cms/18193</a>.</sub>
