### ISSUE TITLE
Error 0 Call To Undefined Method JAdminCssMenu::Addchild

### ISSUE THREAD

**Issue by williz** [joomla/joomla-cms#18198]
### Steps to reproduce the issue

After update to Joomla 3.8
Error 0 Call To Undefined Method JAdminCssMenu::Addchild 

SOLUTION:

1. It did not allow the administrator to enter.
2. Upload to the folder public_html package, Joomla_ 3.8.0-Stable-Full_Package
3. Remove the installation
4. Upload the script to folder Administrator https://github.com postupdate. php
5. Go to the Administrator folder, search modules, module, Mod_sppagebuilder_admin_menu, and rename it for, Mod_sppagebuilder_admin_menu-B

and everything will be working like normal!

**Comment by wojsmol** [comment]
@williz Please open topic on https://forum.joomla.org/viewforum.php?f=710 and close issue here. This repository is for Joomla! core issues.

**Comment by ghost** [comment]
closed as duplicate Report #18022<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18198">issues.joomla.org/tracker/joomla-cms/18198</a>.</sub>
