### ISSUE TITLE
After upgrade to Joomla 3.8 all multi-page articles are broken

### ISSUE THREAD

**Issue by mattiaverga** [joomla/joomla-cms#18201]
After upgrading my sites from Joomla 3.7 to 3.8, all multi-page articles are broken.
I can view the first page and the table of contents, but when I try to open one of the other pages I get:
Call to a member function getCode() on null

For example see http://www.techfromthenet.it/201709284957/Test-networking/avm-fritz-box-7590-l-evoluzione-del-router-xdsl.html

**Comment by ghost** [comment]
closed as duplicate Report #17830<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18201">issues.joomla.org/tracker/joomla-cms/18201</a>.</sub>
