### ISSUE TITLE
Trying to get property of non-object in libraries/src/Access/Access.php on line 608/613

### ISSUE THREAD

**Issue by lomcarlo** [joomla/joomla-cms#18209]
After upgrade to version 3.8.0 I have these messages from Apache error log:
`(omissis) PHP Notice:  Undefined offset: 1622 in /var/www/html/libraries/src/Access/Access.php on line 608, referer: http://(omissis)
(omissis) PHP Notice:  Trying to get property of non-object in /var/www/html/libraries/src/Access/Access.php on line 608, referer: http://(omissis)
(omissis) PHP Notice:  Undefined offset: 1622 in /var/www/html/libraries/src/Access/Access.php on line 613, referer: http://(omissis)
(omissis)PHP Notice:  Trying to get property of non-object in /var/www/html/libraries/src/Access/Access.php on line 613, referer: http://(omissis)`

These messages appear only when I open pages linked on menu items from a specific Content category.
I try to regenerate Content and also Menu but the error persists.
I noted that in the assets table there are some com_content.category with parent_id = 1622 but asset id 1622 does not exist.
The category that should be the parent is a root category with no parent.
I think this is the problem.

### Steps to reproduce the issue
Create a content category without parent category (Father);
Create a child category (Son) of that category (Father);
Create some contents within Son category;

### Actual result
The page is shown but the error persists

### System information (as much as possible)
PHP on | Linux spmsf 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64
database version | 5.5.57-0+deb8u1
Collation database | utf8_unicode_ci
Collation database connection | utf8mb4_general_ci
PHP ver. | 5.6.30-0+deb8u1
Web Server | Apache
WebServer PHP interface | apache2handler
Versione di Joomla! | Joomla! 3.8.0 Stable [ Amani ] 19-September-2017 14:00 GMT
Versione piattaforma Joomla! | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.

**Comment by TiMoscow** [comment]
decision:

1. Press the button "Rebuild" - in "manage menus".
2. Press the button "Rebuild" - in "manage categories".
3. To serially open each Category and to press "Save".
4. To serially open each Articles and to press "Save".

https://joomlaforum.ru/index.php/topic,342186.msg1732082.html#msg1732082
