### ISSUE TITLE
proxy function for window.listItemTask should have a return value

### ISSUE THREAD

**Issue by GeraintEdwards** [joomla/joomla-cms#18203]
See https://github.com/joomla/joomla-cms/pull/17516#pullrequestreview-66697272 - change is not  backwards comptible.  The old window.listItemTask method returned a value (false), the new one doesn't

The old and proxy function is used assuming  a return value in many places in 3rd party components and in the core e,g,
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/helpers/html/contentadministrator.php#L117

Fix is trivial - I'll so a PR

**Comment by ghost** [comment]
closed as having Pull Request #18205<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18203">issues.joomla.org/tracker/joomla-cms/18203</a>.</sub>
