### ISSUE TITLE
[4.0] 500 on frontend

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#18208]
### Steps to reproduce the issue
Do a NEW install of current 4.0 branch **without** the sample data

### Expected result
Front end works

### Actual result
500 Expression #1 of ORDER BY clause is not in SELECT list, references column 'nmmtest1.c.lft' which is not in SELECT list; this is incompatible with DISTINCT

**Comment by C-Lodder** [comment]
Can't replicate with sample data installed

**Comment by C-Lodder** [comment]
Also get the following when clicking on **Archived Articles**:

> PHP Notice:  Undefined property: Joomla\CMS\Object\CMSObject::$params in C:\XXX\components\com_content\Model\ArchiveModel.php on line 48

**Comment by brianteeman** [comment]
@C-Lodder try it without the sample data

(updated original issue

**Comment by C-Lodder** [comment]
I can also confirm the issue on a new installation **with** sample data. On the **Featured Articles** sub-page though.

@csthomas any thoughts on this?

**Comment by csthomas** [comment]
If joomla use DISTINCT or GROUP BY in query then you can order by column that is included in SELECT statement.

You can go to home menu and set new order that column exists in select statement like:
![obraz](https://user-images.githubusercontent.com/9054379/31140721-9165a48a-a875-11e7-8810-e7560b80df16.png)

or you can delete `DISTINCT` from https://github.com/joomla/joomla-cms/blob/4.0-dev/components/com_content/Model/ArticlesModel.php#L197

I do not know why someone add DISTINCT but this slow down very much this view.
The query has to be designed in a better way without using DISTINCT or GROUP BY.

IMO joomla 4.0 could try to find a better way to build query or I should say queries per model.

**Comment by ghost** [comment]
closed as having Pull Request #18215<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18208">issues.joomla.org/tracker/joomla-cms/18208</a>.</sub>

**Comment by alikon** [comment]
no please reopeon, it fix only some of the archive bugs

**Comment by ghost** [comment]
reopen as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18208">issues.joomla.org/tracker/joomla-cms/18208</a>.</sub>

**Comment by alikon** [comment]
@csthomas made the simple fix in #18215 for the `DISTINCT` clause

fully agree

> joomla 4.0 could try to find a better way to build query

**Comment by alikon** [comment]
now should fix when installing without sample data too
@franz-wohlkoenig  can be closed now

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18208">issues.joomla.org/tracker/joomla-cms/18208</a>.</sub>
