### ISSUE TITLE
noindex for tag-pages / seo

### ISSUE THREAD

**Issue by CEWebDesign** [joomla/joomla-cms#18219]
### Steps to reproduce the issue
create articles with tags

### Expected result
pages like 
component/tags/tag/my-first-tag
component/tags/tag/1
not being indexed, at least not twice, or with cannonical?

### Actual result
tag-pages get indexed twice:
component/tags/tag/my-first-tag
component/tags/tag/1

### System information (as much as possible)
J3.7.5

**Comment by brianteeman** [comment]
Please update to J3.8

**Comment by CEWebDesign** [comment]
Update to J3.8.1, no change seen, solution for now "Disallow: /component/tags/tag/" in robots.txt.

**Comment by CEWebDesign** [comment]
I created a new issue #18346 but it is same/similar issue... Please close one or the other, sorry.

**Comment by Quy** [comment]
Duplicate #18410<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18219">issues.joomla.org/tracker/joomla-cms/18219</a>.</sub>
