### ISSUE TITLE
Disallow emoji on username/password/name on user create

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#18229]
### Steps to reproduce the issue

Add a emoji on the username

### Expected result

should now be allowed

### Actual result

allowed

### System information (as much as possible)

J3.8

**Comment by tonypartridge** [comment]
Why should emoji be disallowed?

**Comment by brianteeman** [comment]
From my test - while a doublebyte emoji character was accepted for username and password when creating the account you cannot use it to login - and the screen doesnt display them correctly on save


<img width="366" alt="screenshotr10-09-03" src="https://user-images.githubusercontent.com/1296369/31219460-4bb8478a-a9b5-11e7-803e-eb99ea9e921e.png">

<img width="330" alt="screenshotr10-08-35" src="https://user-images.githubusercontent.com/1296369/31219461-4bb84a1e-a9b5-11e7-8ec4-c2d3139de6e0.png">

**Comment by tonypartridge** [comment]
So it needs to be decided whether we should allow Emoji's or disallow them in usernames and then we can take the correct action to resolve.

**Comment by brianteeman** [comment]
one of the issues if we allow them in usernames is that they currently dont display correctly in the admin as we dont support emoji there

**Comment by 810** [comment]
> Why should emoji be disallowed?

Because in many situations it will break any filter/code checks if you check the username by input.

**Comment by mbabker** [comment]
Do we have a definition somewhere of what characters our usernames are allowed to have?  If not, it can be argued anyone making a check on username with arbitrary restrictions is doing it wrong.

If the data is being stored correctly, then the display issue is related to the retrieval and handling of that data from the database.

Is this issue with emoji only present with user data, or are there issues with it elsewhere?

This one issue is going to open a can of worms...

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 26th November 2017.

**Comment by ghost** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened.
