### ISSUE TITLE
Hide `Mass Mail Users` menu item when `Disable Mass Mail` is Yes

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#18226]
### Steps to reproduce the issue
Go to Global Configuration > Server
Under Mail Settings, select Yes for Disable Mass Mail
Under Users menu, select Mass Mail Users

### Expected result
Mass Mail Users not available so it can not be selected.

### Actual result
It can be selected but goes to the Control Panel dashboard.

### Additional comments
It is fine in v3.6.5 but not in v3.8

**Comment by ghost** [comment]
Confirmed.

Menu "Mass Mail Users" should not displayed in this Case.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18226">issues.joomla.org/tracker/joomla-cms/18226</a>.</sub>

**Comment by mbabker** [comment]
This is another one of those things where the module needs special handling for this specific condition/item, especially as the backend menu becomes more database driven.  So not sure how efficiently this can be fixed, or how many special conditions for parameters or other table relations we want to be hacking in.

**Comment by ghost** [comment]
closed as having Pull Request #18233
