### ISSUE TITLE
Upgrade 3.8.0 error - Frontend broken

### ISSUE THREAD

**Issue by BatmanKuhn** [joomla/joomla-cms#18227]
### Steps to reproduce the issue
Upgrade from previous version to 3.8.0

### Expected result
Working version

### Actual result
Front-end broken - No error messages

### System information (as much as possible)
Joomla! 3.8.0 Stable [ Amani ] 19-September-2017 14:00 GMT
Darwin webserver.local 15.6.0 Darwin Kernel Version 15.6.0: Sun Jun 4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64 x86_64

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
