### ISSUE TITLE
search result display issue

### ISSUE THREAD

**Issue by hikashop-nicolas** [joomla/joomla-cms#18220]
### Steps to reproduce the issue
Create a new article with the title "SHIM/SET"
Search for it on your frontend via the Joomla search.

### Expected result
The result page should display a search result for it with a link to the article.

### Actual result
The result page has a search result but without any link.

### System information (as much as possible)
Joomla 3.8.0
PHP 7.1

### Additional comments
Someone actually reported us that issue:
https://www.hikashop.com/forum/filters-search/892216-issue-with-joomla-search-display-when-searching-by-product-code-with-slashes.html
I've proposed a code modification in Joomla there which fixes the issue for the result link coming from HikaShop, but it doesn't fix it for the result link from the Joomla article. I'm not sure what should be done for Joomla's article link but I suppose the information there should already provide a good starting point for someone familiar with Joomla's search system.

**Comment by brianteeman** [comment]
Note that you have to search for the entire string including the / or it works fine

If you search for the entire string then the title does not display (as reported) and see screenshot
<img width="336" alt="screenshotr10-32-01" src="https://user-images.githubusercontent.com/1296369/31169040-4f0d5f22-a8ef-11e7-91ae-70fb40ab2f76.png">

If you enable max error reporting you should get the following error
`Warning: preg_replace(): Unknown modifier 't' in C:\Apache24\htdocs\cms\components\com_search\views\search\view.html.php on line 268`

**Comment by hikashop-nicolas** [comment]
Yes, thanks for the additional information Brian.

**Comment by ghost** [comment]
closed as having Pull Request #18221 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18220">issues.joomla.org/tracker/joomla-cms/18220</a>.</sub>
