### ISSUE TITLE
Redirect on 3.8.1 don't work

### ISSUE THREAD

**Issue by WebMarkeThink** [joomla/joomla-cms#18235]
### Steps to reproduce the issue
Hello,
after upgrade to 3.8.1 redirect component work same 3.8.0 and don't redirect automatically old link with id article.
We have been set router to experimental.

### Expected result

***/codice-della-strada/codice-della-strada-art-63-traino-veicoli.html

### Actual result

***/codice-della-strada/345-codice-della-strada-art-63-traino-veicoli.html

**Comment by mbabker** [comment]
Duplicate of #14848
