### ISSUE TITLE
Module: Wrong Dropdown-Field at "Ordering"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#18230]
### Steps to reproduce the issue
Open a Module, you see at "Ordering" on right Column a different Dropdown-Field than "Access" or "Language":
![bildschirmfoto 2017-10-04 um 16 30 20](https://user-images.githubusercontent.com/8235763/31181452-a16d7e64-a921-11e7-9bce-d5e3502e0bcc.jpg)
### System information
3.8.2-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 56 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
I assume you mean the styling? If so then this is a duplicate report of #13904

**Comment by ghost** [comment]
closed as duplicate Report ##13904. Thanks for Hint @brianteeman <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18230">issues.joomla.org/tracker/joomla-cms/18230</a>.</sub>
