### ISSUE TITLE
Error when updating 3.8 to 3.8.1

### ISSUE THREAD

**Issue by ManfredHuebner** [joomla/joomla-cms#18232]
### Steps to reproduce the issue

Joomla 3.8 with JCE Pro and SP Page Builder. Promoted from J3.7.5

### Expected result

Upgrade to 3.8.1 without error message

### Actual result

Warning

JInstaller: :Install: Error SQL Duplicate column name 'params'
Files Update: SQL error file DB function failed with error number 1060 
Duplicate column name 'params'
SQL =
ALTER TABLE `#__fields_groups` ADD COLUMN `params` TEXT  NOT NULL  AFTER `ordering`;

### System information (as much as possible)

Setting	Value
 
PHP Built On	Linux h2653337.stratoserver.net 3.13.0-042stab124.2 #1 SMP Fri Sep 1 20:42:18 MSK 2017 x86_64
Database Version	5.5.57-0ubuntu0.14.04.1
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.24
Web Server	Apache
WebServer to PHP Interface	fpm-fcgi
Joomla! Version	Joomla! 3.8.1 Stable [ Amani ] 4-October-2017 14:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by zero-24** [comment]
how do you update? please hit the database fixer. Where / Which version you come intial from?

**Comment by ManfredHuebner** [comment]
I came from Joomla 3.8 with JCE Pro and SP Page Builder. J3.8 was promoted from J3.7.5

I used the database fixer. Said that db schema was 3.7.4, now after fix it is 3.8.0

**Comment by zero-24** [comment]
> I came from Joomla 3.8 with JCE Pro and SP Page Builder. J3.8 was promoted from J3.7.5

Sorry i don't get you.

Did you update from 3.7.5 => 3.8.1 or did you update from 3.7.5 => 3.8.0 => 3.8.1?

**Comment by brianteeman** [comment]
And did you use the updated component?

**Comment by ManfredHuebner** [comment]
I updated from 3.7.5 to J3.8 when J3.8 was released and updated to 3.8.1 from 3.8 today.

Always use the Joomla Update component ;-)

**Comment by alikon** [comment]
if i'm not wrong the `params` field already exists in the table `#__fields_groups`
in this case the `ALTER` is not needed
@ManfredHuebner  as a quick test
 remove this file `administrator/components/com_admin/sql/updates/mysql/3.8.0-2017-07-28.sql`
the update should go on

**Comment by wojsmol** [comment]
@ManfredHuebner Please post also values of this php settings:
memory_limit
max_execution_time

**Comment by ManfredHuebner** [comment]
@alikon: Update didn't fail but produced this message. I guess that during several updates over time, one update step failed without proper notice...

@wojsmol: 

memory_limit | 256M
-- | --


max_execution_time | 120
-- | --

**Comment by gheitmann** [comment]
I had the same problem upgrading from 3.7.5 to 3.8.0 and then to 3.8.1. 
`ALTER TABLE #__fields_groups ADD COLUMN params TEXT NOT NULL AFTER ordering;`

Database link warns about a not matching database shema (still 3.7.5). After hitting 'Fix' is showns the new one without any errors.

`Database schema version (in #__schemas): 3.8.0-2017-07-31.
Update version (in #__extensions): 3.8.1.
Database driver: mysqli.
147 database changes were checked.
184 database changes did not alter table structure and were skipped.`

**Comment by schnuti** [comment]
I got the warning message from the file b) 3.8.0-2017-07-31.sql when updating from 3.7.5 to 3.8.1. There is also a) 3.8.0-2017-07-28.sql.
a) adds a paramfield to #__fields_groups. Field is in the table so it probably worked.
b) wants to insert 2 sets of data into #__extensions. One id already exists with other extension. id:318 = empty, id=479: plg_editors-xtd_fields.  It looks as if the update added the code for both the module and the plug-in. Any idea how I got plg_editors-xtd_fields inserted to 479? I guess the last id for plug-ins should have bin 478. (I did not add plg_editors-xtd_fields using some "tricks")

A database-update did not show the warning but set the status to ok.
I then used some manual tricks to add the new plug-in to another (free) id. It looks ok now but I'll never use those extensions anyway. I hope no one will update the extension using a hardcoded id.  

![joomla_update_3-7-5_3-8-1](https://user-images.githubusercontent.com/956537/31573140-9f262228-b0b5-11e7-99ce-aaa7a5feebba.png)

**Comment by wojsmol** [comment]
@schnuti When it's cams to adding new core extensions then free ids are assumed AFAIK  For newer versions there is a helper for determining for example id of core extension.

**Comment by cheesegrits** [comment]
Same issue here.  Updater component.  3.7.5 to 3.8 was OK.  3.8 to 3.8.1 gets the "duplicate column name 'params'" error.  Running the database fixer seems to resolve schema.

Note that this only happened on one of dozens of sites I ran the same upgrades on.

A number of my clients have reported the issue as well.

   -- hugh

**Comment by schnuti** [comment]
@cheesegrits 
Did you check the #_extensions table? I guess the problem with the  "duplicate column name" did not break the insertion of the two new extensions but if - the database fixer may not have fixed it for you. I did not get any error message when running the fix although the items were **not** inserted and the column name was already in the db-table. The version-# was still updated.

**Comment by cheesegrits** [comment]
Same here, nothing new inserted in #__extensions.

My extension_id 479 is (same as you) plg_editors-xtd_fields.  I have no 318.

   -- hugh

**Comment by schnuti** [comment]
Shouldn't the db-fix program write a log? I understand it's hard to handle all cases as a sql error may be right or wrong depending on the case.. With a log created a professional could asses it manually later.

**Comment by schnuti** [comment]
@cheesegrits 
If you know what you are doing, you can do the following. (I guess you do know ;) )

Run the discover extension method.  Extensions -> Manage -> Discover: run Discover.
If now any extension is listed the code is there but the #__extensions entry is missing. A new plug-in and a new module from Joomla might appear. This would happen anyway, next time you run Discover.
You can do one of following 3.
1. keep them in the Discover list for ever.
2. Easy fix: Run Install from the Discover view. Disadvantage - the extensions get id numbers in the "3d-party range" and not the original ones.
3. What I did with the use of phpMyAdmin (or Co): 
- Edit the record id numbers 318 (module) / first free number below 479 (plug-in)
- Edit the field State from -1 to 0 (disabled).
- Now you can find those extensions in the Manage (extension list) as disabled. Enable if you really want to use them. 
Disadvantage: As one id is not original, remember this hack should you in future get a missing id error message.

Please let us know.

**Comment by Quy** [comment]
@ManfredHuebner This could be related to SP Page Builder. Are you using the latest version?

https://www.joomshaper.com/forums/error-after-updating-from-joomla-to-3-6-5

**Comment by Quy** [comment]
@franz-wohlkoenig Close due to extension compability??
