### ISSUE TITLE
Multilingual associations is missing

### ISSUE THREAD

**Issue by doctorwebb** [joomla/joomla-cms#18238]
### Steps to reproduce the issue
Updated Joomla from 3.6.5 to Joomla 3.8.1 - didn't get the Multilingual associations manager

### Expected result
3.8.1 works fine but the Multilingual associations manager is simply missing 
/administrator/index.php?option=com_associations   ---> "Error loading component: com_associations, Component not found"

### Additional comments
1) i have update from admin panel but this is error message
Warning
JInstaller: :Install: Error SQL Duplicate column name 'client_id'
Files Update: SQL error file DB function failed with error number 1060
Duplicate column name 'client_id'
SQL = ALTER TABLE `#__menu_types` ADD COLUMN `client_id` int(11) NOT NULL DEFAULT 0;

Error loading component: com_fields, Component not found.
Notice
Before you update Joomla, ensure that the installed extensions are available for the new Joomla version.

2) Fix database ok and update to Joomla 3.8.1 database
3) at th manager -> discover  I can not find Multilingual Associations
4) Field manager is ok

**Comment by infograf768** [comment]
Try to download to your PC the pack
https://downloads.joomla.org/cms/joomla3/3-8-1/joomla_3-8-1-stable-update_package-zip?format=zip

Then use joomlaupdate `Upload and Update`

**Comment by doctorwebb** [comment]
Dont'work unfortunately: 
/index.php?option=com_associations ---> this is the error message: "An error has occurred.404 Component not found" .


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18238">issues.joomla.org/tracker/joomla-cms/18238</a>.</sub>

**Comment by dformdotdk** [comment]
Go to extensions->manage->manage
Search for associations
Enable Multilingual Associations
Done...  :-)

**Comment by doctorwebb** [comment]
Hi dyvel,
I've already done this: "There are no extensions installed matching your query"...

 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18238">issues.joomla.org/tracker/joomla-cms/18238</a>.</sub>

**Comment by coolcat-creations** [comment]
Did you try to reinstall Joomla Core Files?

**Comment by brianteeman** [comment]
I am closing this at this time as not reproducible. It can always be reopened if further information is provided

**Comment by dsrpmedia** [comment]
I am having exactly this issue - joomla 3.8.5 - site has been upgraded several times (was originally a 1.5 site way back wnen)

**Comment by dsrpmedia** [comment]
multi lingulal associations shows up in the 'manage' area - but not the component drop down list or by direct access 

/index.php?option=com_associations ---> this is the error message: "An error has occurred.404 Component not found"

**Comment by ghost** [comment]
@dsrpmedia have you asked help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710)?
