### ISSUE TITLE
[4.0][RFC] Relax component requirement for administration section

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#18246]
https://github.com/joomla/joomla-cms/blob/f29dfba087a266881a54ccf92892a25f4bcf71d3/libraries/src/Installer/Adapter/ComponentAdapter.php#L659-L663

The component install adapter enforces a requirement that all components have an administration section, effectively mandating that all components must have an administrative backend, which is not always true.  Just look at core's com_wrapper as an example.

As this is just an arbitrary check or decision made in the past and does not have an actual practical requirement, we should relax this check and remove the requirement for an `<administration>` tag in component XML manifests.

If it is decided that there is an actual requirement for this to be in place, then we need to fix how com_wrapper is installed in the core package because using the install API there is no way to install a component in the way that particular one is.

**Comment by wilsonge** [comment]
Is there a mandate on where the components XML file get's placed (because by default it goes into the components admin area right?)

**Comment by mbabker** [comment]
It's not mandated necessarily as ultimately [`Installer::copyManifest()`](https://github.com/joomla/joomla-cms/blob/c343565619b7e966caff5b202f6c6dced1f0cec7/libraries/src/Installer/Installer.php#L1899) lets you specify which application area to store it in, but internally it all defaults to the admin app unless explicitly specified (falling back to the `extension_root` path, which for components is the admin app, if in that step an application isn't registered for the given ID).

**Comment by wilsonge** [comment]
Well as far as I can tell for components we never use this parameter. So to remove the admin check we need to make that work I guess. https://github.com/joomla/joomla-cms/blob/c343565619b7e966caff5b202f6c6dced1f0cec7/libraries/src/Installer/Adapter/ComponentAdapter.php#L303

**Comment by mbabker** [comment]
Well, it's a little more complex than that.  In [`ComponentAdapter::setupInstallPaths()`](https://github.com/joomla/joomla-cms/blob/c343565619b7e966caff5b202f6c6dced1f0cec7/libraries/src/Installer/Adapter/ComponentAdapter.php#L525) we probably need to make it not use the admin path as the extension root if we don't intend on having an administration section too.  So it probably means an internal tracking flag while processing that extension (luckily the adapters shouldn't be singleton anymore so we don't have to worry about state bleedover in the case of packages) so at least those two areas are able to act differently based on whether a component has an admin section.  We also would need to account for it on the uninstall path.

**Comment by laoneo** [comment]
The component specific service provider is now also loaded from the administrator section. If we agree to have site only components, then we need tho break out the service provider loader too. Honestly I see no use case to have a 3rd party component without any administration part.

**Comment by mbabker** [comment]
> Honestly I see no use case to have a 3rd party component without any administration part.

https://github.com/joomla-extensions/install-from-web-server is a component that is really only a frontend user interface and has a couple of config values, there's nothing to administrate in the site's backend there.  And, as demonstrated by core, there are at least two components that are entirely frontend integrations with no backend.

So while it is indeed a rather rare use case, it is a legitimate one.  I've honestly got no issue if we decide "nope, all components have to have an admin component", but then the core package and our exceptional components should be updated to reflect that requirement.

**Comment by laoneo** [comment]
Even when it has only a config.xml file, then there is already an administration part. I'm ok too with the requirement to have an admin part for a component.

**Comment by mbabker** [comment]
Per discussion this has become a hard requirement.  RFC complete.
