### ISSUE TITLE
Pagination not returning to first page

### ISSUE THREAD

**Issue by nigel-at-vividfish** [joomla/joomla-cms#18247]
### Steps to reproduce the issue
Using paginated list of items, select 2nd or subsequent page and then select first page

### Expected result
Page displayed should show as per selection

### Actual result
Return to first page has no effect.

### System information (as much as possible)
Shows up in site running the crmery component. On a 'company' page with enough contacts to cause pagination to be invoked.

### Additional comments
Problem is caused by test in /libraries/src/Router/SiteRouter.php in Joomla 3.8.1 and /libraries/cms/router/site.php previous versions. in function processParseRules the following test (line 600 in the 3.8.1 version):
	if ($start = $uri->getVar('start'))
will ignore the start value if it is zero. Replacing with:
	if (($start = $uri->getVar('start')) !== null)
Allows zero as a valid value and fixes the problem.

**Comment by wojsmol** [comment]
@nigel-at-vividfish Please try to reproduce this on core components.

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 26th November 2017.

**Comment by ghost** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened.
