### ISSUE TITLE
[4.0] com_content - thead links in lists not sorting items

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#18242]
### Steps to reproduce the issue
Navigate to content -> articlea and try sorting the table using the links in the table header.

### Expected result
Items sort by clicked table header

### Actual result
Nothing

**Comment by ghost** [comment]
@mbabker should this be added to [Projects](https://github.com/joomla/joomla-cms/projects)?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18242">issues.joomla.org/tracker/joomla-cms/18242</a>.</sub>

**Comment by Quy** [comment]
Cannot replicate as of https://github.com/joomla/joomla-cms/commit/50cdb44cd262fdfc783160b7c40a20fc1e72c943

**Comment by Quy** [comment]
@franz-wohlkoenig @brianteeman Can you replicate and close if no?

**Comment by ghost** [comment]
haven't expirienced this issue (waiting for new Testing Plattform).

**Comment by brianteeman** [comment]
Cannot replicate - must have been resolved elsewhere
