### ISSUE TITLE
Search with a "/" - inside article text, link name containing /

### ISSUE THREAD

**Issue by ThomasK0lasa** [joomla/joomla-cms#18244]
### Steps to reproduce the issue
1. Create a new article with text inside like: "This is a bug test <a href="/">IV/264/2017</a>"
2. Search for IV/264/2017 in frontend Joomla search

### Expected result
The result page should display a search result for it with a link to the article.

### Actual result
The result page has a search result but without any link.
Warning: preg_replace(): Unknown modifier '2' in \components\com_search\views\search\view.html.php on line 268

### Additional comments
This fix doesn't help with my issue: https://issues.joomla.org/tracker/joomla-cms/18221
This is my first issue here, hope I didn't mess something up ;)

**Comment by franz-wohlkoenig** [comment]
can you please test #18221?

**Comment by ThomasK0lasa** [comment]
Tested, didn't help. I wrote about it in comment section.

5 paź 2017 14:18 "Franz Wohlkönig" <notifications@github.com> napisał(a):

**Comment by ghost** [comment]
have read it to late.

Issue confirmed:
![screenshot-2017-10-5 search](https://user-images.githubusercontent.com/8235763/31226960-6f6d4b94-a9d8-11e7-9556-d5e3226dc044.png)

**Comment by infograf768** [comment]
Has'nt this be solved by https://github.com/joomla/joomla-cms/pull/18221 ?

**Comment by brianteeman** [comment]
The op explicitly says not - at a guess it is because that PR was only tested against a single / but this example has two

**Comment by infograf768** [comment]
I tested here and it works fine.

**Comment by infograf768** [comment]
<img width="417" alt="screen shot 2017-10-06 at 10 20 31" src="https://user-images.githubusercontent.com/869724/31269285-17688168-aa80-11e7-9a54-6833fc4a8dc3.png">

**Comment by brianteeman** [comment]
The original report wasnt very clear but I can repeat the problem when the string is a link

**Comment by infograf768** [comment]
I can't here. This is what I used
```
<p>some text</p>
<p> </p>
<p>This is a bug test <a href="https://github.com/">IV/264/2017</a></p>
```
As for str_replace:
"str_replace — Replace all occurrences of the search string with the replacement string"

**Comment by brianteeman** [comment]
OK I will test again soon

**Comment by infograf768** [comment]
I see the op did
```
 `This is a bug test <a href="/">IV/264/2017</a>`
```
TinyMCE changes this to
`<a href="../">IV/264/2017</a>` on save

And no problem either

**Comment by brianteeman** [comment]
My branch must have been out of date - i cant replicate it either - sorry for confusion

**Comment by Quy** [comment]
Unable to reproduce.
Line 268 is `// Make sure there are no slashes in the needle` with the merged of #18221.
@ThomasK0lasa Are you sure you applied #18221?
@franz-wohlkoenig Please test again and make sure #18221 is applied.

**Comment by ghost** [comment]
Can't confirm Issue on fresh installed 3.8.2-dev.

**Comment by infograf768** [comment]
I guess this can be closed.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18244">issues.joomla.org/tracker/joomla-cms/18244</a>.</sub>
