### ISSUE TITLE
Обновление вне зоны доступа

### ISSUE THREAD

**Issue by Lebedev30** [joomla/joomla-cms#18243]
### Steps to reproduce the issue
![screen shot 2017-10-05 at 11 04 10](https://issues.joomla.org/uploads/1/b866c1f88f54d53a7ab0e7202a8a2a83.png)!

После нажатия кнопки установить обновление получаю следующий ответ

SSL certificate problem: self signed certificate

При попытке по ссылке скачать обновление получаю следующий ответ:

![screen shot 2017-10-05 at 11 04 11](https://issues.joomla.org/uploads/1/fb0979204e6ae1cdc3525de6eaf9d2ed.png)

Просьба прописать альтернативный вариант загрузки обновлений.

P.S. Всё началось с момента выпуска вами версии 3.8

**Comment by ghost** [comment]
Please write in English; you can use Google Translator if necessary.

**Comment by Lebedev30** [comment]
After clicking the install update button, I get the following response

SSL certificate problem: self signed certificate

When I try to download the update, I get the following response:

Please register an alternative option for downloading updates.

P.S. It all started when you released version 3.8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18243">issues.joomla.org/tracker/joomla-cms/18243</a>.</sub>

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.

**Comment by Lebedev30** [comment]
Antivirus, Internet provider, operating system - Ok.

There is an error outside the Internet provider.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18243">issues.joomla.org/tracker/joomla-cms/18243</a>.</sub>

**Comment by mbabker** [comment]
Russia is blocking the Amazon Web Services region that our downloads are served through.

**Comment by Lebedev30** [comment]
Other options for obtaining updates exist? Or change the country only offers.

**Comment by mbabker** [comment]
See if you can download from https://github.com/joomla/joomla-cms/releases/tag/3.8.1 (GitHub also uses AWS for storage so there is a chance it gets blocked) or https://mirror.myjoomla.io/ (unofficial resource).

**Comment by Lebedev30** [comment]
Many thanks for the link.
