### ISSUE TITLE
TinyMCE plugin options

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#18245]
In the advanced tab we have two options that I am not sure if they even work especially after reasing the description
PLG_TINY_FIELD_HTMLWIDTH_DESC="Width of HTML editor. Should normally be left empty to let it flow. **Only applies in Advanced and Extended mode**."

There is no Advanced or Extended mode now
<img width="356" alt="screenshotr13-28-06" src="https://user-images.githubusercontent.com/1296369/31227286-34e92b8e-a9d1-11e7-88ed-c1b319b2f449.png">

**Comment by Quy** [comment]
Related PR #11489 ?

**Comment by AlexRed** [comment]
see also https://github.com/joomla/joomla-cms/issues/14835

**Comment by Quy** [comment]
@brianteeman Is this not a duplicate of #14835?

**Comment by brianteeman** [comment]
Not quite the same as I am talking about the strings and that one is talking about them not working. But I can see that I did create this issue before #14917 which was closed as we had a Pr #15069 but that one has now been closed

**Comment by coolcat-creations** [comment]
In another PR we spoke about to remove it anyway? https://github.com/joomla/joomla-cms/issues/14789
