### ISSUE TITLE
Joomla 3.8.1 still graphics bug

### ISSUE THREAD

**Issue by edalgrhe** [joomla/joomla-cms#18257]
### Steps to reproduce the issue
I did update to Joomla 3.8.1 and  my site (with favthemes), still is without graphics in chrome browser.

In firefox and IE work fine.

### Expected result

Please give me a solution (I have two site with the issue)

### System information (as much as possible)
- Joolma 3.8.1
- Template: favthems

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
