### ISSUE TITLE
JForm : Problem whith rule in subforms (multiple)

### ISSUE THREAD

**Issue by rolandalsace** [joomla/joomla-cms#18250]
Hi.

In a form whith a subform field, type multiple, the rules are only executed on the fields of the 1st subform

**Comment by Fedik** [comment]
please test that fix #14189

**Comment by ghost** [comment]
closed as there is a Pull Request for Test. It can always reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18250">issues.joomla.org/tracker/joomla-cms/18250</a>.</sub>
