### ISSUE TITLE
Joomla Cron Script not working

### ISSUE THREAD

**Issue by juliopontes** [joomla/joomla-cms#18252]
### Steps to reproduce the issue
1 - Go to terminal and run this command bellow
2 - php path/to/your/joomla/cli/finder_indexer.php

### Actual result
Error displaying the page: Application Instantiation Error

### System information (as much as possible)
php 7.X error
php 5.6 works

**Comment by csthomas** [comment]
What cache handler do you use? Turn off cache and check again.

**Comment by 810** [comment]
for me its working correct: php 7.1.7

````Smart Search INDEXER
============================
Starting Indexer
Setting up Smart Search plugins
Setup 12 items in 1.975 seconds.
 * Processed batch 1 in 5.479 seconds.
Total Processing Time: 7.456 seconds.
Peak memory usage: 14,680,064 bytes
````

**Comment by alikon** [comment]
worked for me even with cache enabled (redis,file)
php 7.0.22

**Comment by juliopontes** [comment]
Its working now 7.1.8 restarted and works.
