### ISSUE TITLE
Missing database field for Redis session cache

### ISSUE THREAD

**Issue by simbus82** [joomla/joomla-cms#18259]
### Steps to reproduce the issue
Try to enable Redis cache for session

### Expected result
A field where to write a specific Redis Database number

### Actual result
Can't select a specific Redis DB for session cache

### System information (as much as possible)
J 3.8.1
PHP 7.0.x
Apache 2.4
Cpanel/WHM latest version

### Additional comments

![image](https://user-images.githubusercontent.com/1375730/31289866-a7336b4c-aaca-11e7-9f90-c7f00331aa64.png)

**Comment by alikon** [comment]
test #18266

**Comment by brianteeman** [comment]
closed as we have a Pr

**Comment by simbus82** [comment]
Thank you!

**Comment by alikon** [comment]
please mark successful test on #18266
