### ISSUE TITLE
Front end edit button is not loading on some pages

### ISSUE THREAD

**Issue by chrisgdclarke** [joomla/joomla-cms#18262]
### Steps to reproduce the issue

1. Log in as super user on Joomla Website (frontend)
2. On some web pages the 'edit page cog' (top right position) does not appear.

### Expected result

The edit page cog should appear on every page.

### Actual result

Some pages the cog appears and on some the cog does not. There is no code between:

    
and

    

### System information (as much as possible)

Updated to Joomla 3.8.1
Siteground hosting.
example of page which it works: https://www.radiologycafe.com/interview-application/where-to-apply
example of a page where it does not work: https://www.radiologycafe.com/radiology-trainees/st1-starters-guide

### Additional comments

The issue can be reproduced if 'Position of Article info' option is set to 'Below' in menu item of that particular article. Setting 'Position of article info' to 'Use Global (Above)' fixes the issue.

I believe this is a new bug recently introduced to Joomla (maybe in 3.8)...

**Comment by chrisgdclarke** [comment]
Further info: Issue can be reproduced if 'Position of Article info' option is set to 'Below' in menu item of that particular article.  Setting 'Position of article info' to 'Use Global (Above)' fixes the issue.

I believe this is a new bug recently introduced to Joomla (maybe in 3.8)...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18262">issues.joomla.org/tracker/joomla-cms/18262</a>.</sub>

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.

**Comment by brianteeman** [comment]
Please reopen so it can be investigated.

**Comment by ghost** [comment]
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18262">issues.joomla.org/tracker/joomla-cms/18262</a>.</sub>

**Comment by brianteeman** [comment]
I have now had the opportunity to check this and cannot replicate this with either of the core joomla templates so this must be an issue with your t3 template.

I can see that your template is 2.2.3 but the latest version of that template is 2.2.8 

Please update the template as almost certainly that will fix it

**Comment by chrisgdclarke** [comment]
Thank you. Updating did not fix though. Will contact JA for help.
