### ISSUE TITLE
Invalid login when updating 3.8 to 3.8.1

### ISSUE THREAD

**Issue by Zero-Bytes** [joomla/joomla-cms#18270]
I'm getting invalid login message when trying to update from 3.8.0 to 3.8.1
It makes no difference whether I'm using the live updater or uploading the upgrade package manually.
Directory permissions are all writeable.

# System Information
**PHP erstellt für** Linux dd27830 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 
**Datenbankversion** 5.7.15-nmm5-log 
**Datenbankzeichensatz** latin1_swedish_ci 
**Datenbankverbindungszeichensatz** utf8mb4_general_ci 
**PHP-Version** 7.0.20-nmm1 
**Webserver** Apache 
**PHP-Interface für den Webserver** fpm-fcgi 
**Joomla!-Version** Joomla! 3.8.0 Stable [ Amani ] 19-September-2017 14:00 GMT 
**Joomla!-Plattform-Version** Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 
**Browsererkennung** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063

**Comment by wojsmol** [comment]
@Zero-Bytes Please post on forum https://forum.joomla.org/viewforum.php?f=710.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18270">issues.joomla.org/tracker/joomla-cms/18270</a>.</sub>
