### ISSUE TITLE
filter by category doesn't show sub-category any more

### ISSUE THREAD

**Issue by xinelope** [joomla/joomla-cms#18284]
### Steps to reproduce the issue
After update 3.8.1:
Content searchtool - filter by category - 
only one level is shown

**Comment by ghost** [comment]
can you give more Details or post a Screenshot of your Search-Settings?

**Comment by brianteeman** [comment]
This sounds the same as another issue

**Comment by wojsmol** [comment]
@brianteeman Yes, this is reported, but I don't remember issue number.

**Comment by AlexRed** [comment]
Issue https://issues.joomla.org/tracker/joomla-cms/18179  RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18284">issues.joomla.org/tracker/joomla-cms/18284</a>.</sub>

**Comment by ghost** [comment]
closed as duplicate Report. Thanks for #18179, @AlexRed <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18284">issues.joomla.org/tracker/joomla-cms/18284</a>.</sub>

**Comment by wojsmol** [comment]
As wroted by @AlexRed there is PR in RTC state https://github.com/joomla/joomla-cms/pull/18179
