### ISSUE TITLE
[com_fields] onPrepareFinderContent overwrites base table fields

### ISSUE THREAD

**Issue by hieblmedia** [joomla/joomla-cms#18296]
### Steps to reproduce the issue
Here an example for contacts.
Enable the plugin "Smart Search - Contacts"
Go into the contacts component.
Under fields, create a textfield with the name "title"
Now create an contact item and save it.

### Expected result
The is the main contact title in the finder component

### Actual result
Title is the value of the created field "title" in the finder component

**Comment by laoneo** [comment]
There is no way around this, if you define a field the same name as a core field.

**Comment by brianteeman** [comment]
Closed as expected behaviour
