### ISSUE TITLE
DateHelper.js with %d. %m.  format returns wrong data

### ISSUE THREAD

**Issue by Jeldik** [joomla/joomla-cms#18297]
### Steps to reproduce the issue
When I use date format %d.%m and save it, Joomla returns me date format in reverse result(%m.%d) in my view. When I use d.m.y, everythings is ok.

### Expected result
7.9. (%d. %m)

### Actual result
9.7. (%m. %d)

### System information (as much as possible)
I am fetching data in good format from my DB. When I debug this, I can see that problem is in Calendar.js -> checkInputs -> here DateHelper.js returns me wrong format. I am sending for example 7.9. (d.m) and I get 9.7.

**Comment by infograf768** [comment]
Are you using translateformat?

Which language is used?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18297">issues.joomla.org/tracker/joomla-cms/18297</a>.</sub>

**Comment by Jeldik** [comment]
No I don't.  But when I try it, same result.

**Comment by dgrammatiko** [comment]
@Jeldik can you provide some more info here?
What i the language?
Can you also provide the failing field (the code will be helpful), is it in core/3rd PD extension?

**Comment by Jeldik** [comment]
Failing field is whatever in format %d.%m. For example 9.6. It is looks like the method not count with format without year. What language do you mean? Some example please. Is in DateHelper.js, I don´t know if is it core or 3rd PD extension.

**Comment by dgrammatiko** [comment]
I mean what is your website backend/front end language? English, French etc
Also how did you change the format? Form field, Layout, Language string

**Comment by Jeldik** [comment]
Czech. Field i change it in xml field.

---
Tomáš Jelínek

2017-10-12 18:10 GMT+02:00 Dimitri Grammatikogianni <
notifications@github.com>:

**Comment by ghost** [comment]
any Suggestion @dgt41?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18297">issues.joomla.org/tracker/joomla-cms/18297</a>.</sub>

**Comment by ghost** [comment]
@Jeldik is this still an Issue on latest staging?

**Comment by Quy** [comment]
@franz-wohlkoenig OK to close?

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18297">issues.joomla.org/tracker/joomla-cms/18297</a>.</sub>
