### ISSUE TITLE
HTTP status code check feature > for the insatallation security check

### ISSUE THREAD

**Issue by HRIT-Florian** [joomla/joomla-cms#18294]
### Steps to reproduce the issue
The security file check at the installation could be skipped, if the HTTP status code is not 401 (HTTP authentication required) which means the installation ist http access protected. 

I think some web companys like me did work on http access protected development sites. The installation anyway take some steps, so, let's make the life easier and skipt this if it is not needed.

For this, I have opened the following attached pull request, where the http chek is now implemented.

**Comment by Quy** [comment]
@franz-wohlkoenig Close per PR #18295

**Comment by ghost** [comment]
closed as having Pull Request #18295 

Thanks for Hint @Quy
