### ISSUE TITLE
Possibly a major bug with Category Blog + Tags in 3.8.1

### ISSUE THREAD

**Issue by Hurmeli** [joomla/joomla-cms#18299]
### Steps to reproduce the issue

1) Create two categories and add an article inside each
2) Make two category blog menu items and point these to the categories you created

Test in front end, works as expected. Each category shows one article.

3) Add one tag
4) Add the tag in one of the articles
5) Make the category blog menu item pointing to category with the tagged article filter articles by that tag.

### Expected result

Both categories should still show one article.

### Actual result

Category with tag works. Category without any tags doesn't show any articles anymore.

Removing the tags will not fix this bug. Site will no longer show any articles at all.

### System information (as much as possible)

PHP Built On | Linux MSPQNAS01 3.12.6 #1 SMP Mon Mar 13 01:11:46 CST 2017 x86_64
Database Version | 5.5.51-MariaDB
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 5.5.38
Web Server | Apache
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 3.8.1 Stable [ Amani ] 4-October-2017 14:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

### Additional comments

This happens both with old and new routing. SEF URL's were not enabled while testing.

Fresh install of Joomla 3.8.1. Tested twice on two different installations. Unless this has something to do with our database / php then this is a rather major bug and will basically kill any site using blogs + tags.

Edit: Tested also with Joomla 3.8, same problem.

**Comment by csthomas** [comment]
Please test https://github.com/joomla/joomla-cms/pull/18248

**Comment by ghost** [comment]
closed as duplicate Report #18138<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18299">issues.joomla.org/tracker/joomla-cms/18299</a>.</sub>
