### ISSUE TITLE
JFormFieldCalendar using 12 hour format

### ISSUE THREAD

**Issue by billtomczak** [joomla/joomla-cms#18304]
### Steps to reproduce the issue
Edit /administrator/components/com_content/models/forms/article.xml and edit the publish_up field attributes:
* remove `translateformat`
* add `format="%Y-%m-%d %I:%M %P"`
* add `timeformat="12"`

The final result should look something like:

```xml
		<field
			name="publish_up"
			type="calendar"
			label="COM_CONTENT_FIELD_PUBLISH_UP_LABEL"
			description="COM_CONTENT_FIELD_PUBLISH_UP_DESC"
			showtime="true"
			format="%Y-%m-%d %I:%M %P"
			timeformat="12"
			size="22"
			filter="user_utc"
		/>
```

Then edit any article's `Start Publishing` field to set the time to midnight using the calendar tool and save the changes.

### Expected result
After saving, the time displaying in the text field should be 12:00 am

### Actual result
The time in the text field is set to 12:00 pm

Also, the am/pm selector text is not wide enough and the option texts are hidden (see screenshot)

### System information (as much as possible)
The time can be set manually in the text box to '12:00 am' and is saved as expected. But then you'll notice the hour drop down selection is empty. (See screenshot)

For the am/pm selector, it has a `colspan="1"` hardcoded and I believe it should be `colspan="2"`.

### Additional comments
![screen shot 2017-10-11 at 01 57 39](https://issues.joomla.org/uploads/1/37777738dc7cc8e900822cb522fcf2e2.png)

**Comment by Quy** [comment]
Please test PR #18240

**Comment by ghost** [comment]
closed as duplicate Report #18240<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18304">issues.joomla.org/tracker/joomla-cms/18304</a>.</sub>

**Comment by billtomczak** [comment]
PR #18240 doesn't seem to have fixed the problems reported here. One difference I see now in v3.8.7 is that selecting 12:00 AM using the selector controls forces to pm no matter what. Otherwise, all behaviors previously reported remain the same.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18304">issues.joomla.org/tracker/joomla-cms/18304</a>.</sub>

**Comment by ghost** [comment]
@billtomczak can you please open a new Issue as this one is closed and so Comments get low Notice.
