### ISSUE TITLE
[4.0] Frontend image is suboptimal on bigger screens

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#18309]
### Steps to reproduce the issue
View aurora on a big screen (i'm using a 2560 x 1440 monitor)

### Expected result
Full screen image or at least centered image

### Actual result
![image](https://user-images.githubusercontent.com/1986000/31442206-89e172b6-ae8d-11e7-96e5-316c5335bfe3.png)

@C-Lodder / @ciar4n

**Comment by C-Lodder** [comment]
@ciar4n - how do you wan to go about this one. We can easily make the image 100% width which will then be cut off vertically due to the `max-height` of the container. Or we can set a max-width for the image and align it to the center.

Thoughts?

Or shall we hold off till Aurora v2?

**Comment by ciar4n** [comment]
When you say a max-height on the container, are you referring to the paragraph?

Another solution is to set the image as a background to the module and throw some content in there. We can set all module backgrounds to `background-size:cover;` ..

![image](https://user-images.githubusercontent.com/2803503/31552028-36d0e852-b02e-11e7-90a9-f45f1d822cf0.png)

**Comment by C-Lodder** [comment]
cool, works for me

**Comment by ciar4n** [comment]
We can close this with #18464 merged
