### ISSUE TITLE
[Question] Can I use {loadposition ####} in custom field Textarea?

### ISSUE THREAD

**Issue by lukewoolh** [joomla/joomla-cms#18312]
I've searched far and wide and cannot find a suitable answer (or question asking the same) on the matter. I am wondering if it is possible to include {loadposition ####, style} within a custom field (text or textarea) to then be triggered on the article? I know I can use a template override etc, but for front-end content users, this would be easier...

### Steps to reproduce the issue
Create new custom field (Text area). Add in HTML markup with {loadposition ####, style} to be displayed on page.

### Expected result
See position/module content loaded within article.

### Actual result
The text "{loadposition ####, style}" is visible but not the triggered content.

### System information (as much as possible)
Joomla 3.7 (current stable)

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.

**Comment by lukewoolh** [comment]
Apologies Franz, and thank you for pointing in the right direction. Keep up the good work.

**Comment by infograf768** [comment]
@laoneo 
Any possibility of adding that feature in core?

**Comment by laoneo** [comment]
@infograf768 this should be the case already here https://github.com/joomla/joomla-cms/blob/staging/plugins/fields/textarea/tmpl/textarea.php#L18

**Comment by infograf768** [comment]
@laoneo 
I confirm `{loadposition xxx}` works in textarea custom field.

**Comment by laoneo** [comment]
But for text, it's not https://github.com/joomla/joomla-cms/blob/staging/plugins/fields/text/tmpl/text.php#L24.

**Comment by infograf768** [comment]
Should we add it?

**Comment by laoneo** [comment]
We can, not sure if it makes sense honestly.

**Comment by infograf768** [comment]
Agree.

**Comment by ggppdk** [comment]
> Should we add it?

Adding it for text ? Not without a parameter to enable it only if need
- text field is much more common

imagine calling plugin triggering like this in category view,
performance disaster
