### ISSUE TITLE
Pictures and links -tab missing from admin article editor view

### ISSUE THREAD

**Issue by VoittajaTomi** [joomla/joomla-cms#18314]
### Steps to reproduce the issue

Updated from 3.6.5 to 3.8.1

### Expected result

In the administrator article editor view I wanted to see the Images and Links -tab

Same tabs as in 3.6.5

### System information (as much as possible)

OS: Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64
Db version: 5.5.57-0+deb8u1 
PHP: 5.6.30-0+deb8u1 
Server: Apache/2.4.17 (Debian)

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
