### ISSUE TITLE
[RFC] Drop LDAP Plugin from 4.0 new installs

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#18311]
### Expected result

No LDAP Plugin in 4.0 new installs. If needed it can be installed from a joomla-extensions repo.

### Actual result

There is a unmaintained LDAP Plugin in the core that is disabled by default.

### RFC

Please leave your opinions on this topic below ;)

**Comment by mbabker** [comment]
Explain how the plugin's unmaintained?  The fact it isn't updated as frequently as other parts of the system doesn't mean it's unmaintained.  So, what are we really gaining by dropping this (and IMO if we drop the plugin we should drop the library client class too because it is even worse than the plugin as far as structure and maintainability goes) other than removing a low-maintenance burden?

**Comment by zero-24** [comment]
Sure we should drop the client lib too from the core install.

**Comment by brianteeman** [comment]
It is maintained and it is used.

**Comment by zero-24** [comment]
> It is maintained

Without any way to test it as it require a complex setup and to real test it you need a original Active Directory.

> and it is used

Would be great to know who we can ask to test changes. Weblinks was also used and i guess much more than ldap similar apply to geshi they got dropped too. ;)

**Comment by mbabker** [comment]
> Without any way to test it as it require a complex setup and to real test it you need a original Active Directory.

Actually, I just put in a lot of work [writing functional tests for the LDAP client](https://github.com/joomla-framework/ldap/pull/9) so we actually do for the first time ever have real testing of our LDAP code against a real LDAP source.  And half a clue how awkward our API actually is as a result.

**Comment by wilsonge** [comment]
We definitely need LDAP. It's almost essential for any sort of scaling company

**Comment by wilsonge** [comment]
I'm going to make an executive decision and reject this one

**Comment by zero-24** [comment]
Hmm this does not solve the issue that we can't test that thing on real sites. Nor test changes pre release. (like the last one)

> We definitely need LDAP. It's almost essential for any sort of scaling company

Sure that is the reason i suggested to move it to joomla-extensions.

:(

**Comment by mbabker** [comment]
Yes, we can test the thing.  There are instructions to set up LDAP servers for many platforms, and we have real (non-mocked) functional testing of the LDAP client code against a real LDAP server.  So the only thing that does not have proper testing is how the plugin itself behaves.  Moving it out of core and into an abandonware repo doesn't fix that particular concern.

**Comment by wilsonge** [comment]
https://github.com/joomla-framework/ldap/commit/e0c19e62f6acf16ec64159b84a139329bb55fe4f here are the tests btw. I merged them from @mbabker last week
