### ISSUE TITLE
Batch apply tags returns error

### ISSUE THREAD

**Issue by leetempest** [joomla/joomla-cms#18320]
### Steps to reproduce the issue
Use core Joomla Tags extension and create a tag.
Create a number of standard articles all in the same category.
Click checkbox and select articles.
Click on Batch button, select the Add Tag dropdown option.
Click Batch and then this error is displayed:

0 Call to a member function setNewTags() on null

### Expected result
Selected articles should have tag applied in one bacth

### Actual result
error page displaying:

0 Call to a member function setNewTags() on null

### System information (as much as possible)

Latest Joomla 3.8.1

**Comment by ghost** [comment]
closed as duplicate Report #18057.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18320">issues.joomla.org/tracker/joomla-cms/18320</a>.</sub>
