### ISSUE TITLE
[4.0-dev] Drone fails on JS tests

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#18323]
### Steps to reproduce the issue

http://ci.joomla.org/joomla/joomla-cms/280

### Expected result

drone is happy

### Actual result

drone is not happy

### Error message

![image](https://user-images.githubusercontent.com/2596554/31517307-c5d92ca0-af9b-11e7-9a78-b279cd9f7b5a.png)

**Comment by wilsonge** [comment]
@dgt41

**Comment by ghost** [comment]
Reminder @dgt41 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18323">issues.joomla.org/tracker/joomla-cms/18323</a>.</sub>

**Comment by dgrammatiko** [comment]
See #18388

**Comment by ghost** [comment]
closed as having Pull Request #18388

Thanks @dgt41
