### ISSUE TITLE
Component with multiple categories, ACL not working correctly

### ISSUE THREAD

**Issue by Flowman** [joomla/joomla-cms#18330]
### Steps to reproduce the issue

If you create a component with multiple categories for example:
```
JHtmlSidebar::addEntry(
	JText::_('COM_HELLOWORLD_CAT1'),
	'index.php?option=com_categories&extension=com_helloworld.cat1',
	$vName == 'categories'
);
JHtmlSidebar::addEntry(
	JText::_('COM_HELLOWORLD_CAT2'),
	'index.php?option=com_categories&extension=com_helloworld.cat2',
	$vName == 'categories'
);
```
When Joomla\CMS\Table\Category::_getAssetParentId tries to find the parent asset it will fail as there is no com_helloworld.cat1 asset in the assets table. It should instead try to find the component asset com_helloworld.

### Expected result

It should get the default ACL from the component asset.

### Actual result

It get is ACL from the root asset.

### System information (as much as possible)

Joomla 3.8.1
PHP 7.1.1
MySQL 5,7

### Additional comments

This could easily be fixed by exploding $this->extension and only use the first part in https://github.com/joomla/joomla-cms/blob/c343565619b7e966caff5b202f6c6dced1f0cec7/libraries/src/Table/Category.php#L109

**Comment by brianteeman** [comment]
In your asset table do the two categories have a parent id?

**Comment by Flowman** [comment]
They get the parent id of 1, so the root asset object.

**Comment by brianteeman** [comment]
So thats the problem - you need to give them the parent id of the component. See the assets for com_content for an example

**Comment by Flowman** [comment]
Every time you save it, it reset to the root asset as it cannot find the component as the parent.

You need to understand its not like the com_content as com_content does not use two categories in one component. 

Check the code in Joomla\CMS\Table\Category::_getAssetParentId and you will understand the problem.

As there is no com_helloworld.cat2 in the asset table it will always fallback to the root asset.

Even com_fields have fixed this https://github.com/joomla/joomla-cms/blob/39003a7e578c5e71ec812727b6490c03f8394649/administrator/components/com_fields/tables/group.php#L158

**Comment by jwaisner** [comment]
@Flowman Can you please confirm this still exists in J3?

**Comment by Flowman** [comment]
@jwaisner yes and I guess I will have to do a one liner pull request for it if none else has time to do it.

**Comment by Bakual** [comment]
@Flowman If you know the solution, then plwase yes. Do a PR. That's exactly how things get fixed around here 😀

**Comment by brianteeman** [comment]
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed. 

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
