### ISSUE TITLE
jml3.8.1 -  TinyMCE..... and IFRAME problem

### ISSUE THREAD

**Issue by trumpy-pl** [joomla/joomla-cms#18337]
Hello, I have problem after update to JML 3.8.1

I cannot insert IFRAME in any article .... :(
I use TinyMCE....
I have old "extended valid elements" but it don't work...

Have anyone similar problem?

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
