### ISSUE TITLE
Purge versions from database when an article is archived

### ISSUE THREAD

**Issue by mattiaverga** [joomla/joomla-cms#18332]
In order to avoid as much as possible a uncontrolled database growth, I think would be nice to have as default or as an option the ability to purge older versions of an article which is moved to the "archived" status. I think that if an article is "archived" it will not be modified anymore, so why have older version maintained in the database?

This can help to save some database space, depending on how many versions are retained for every single article.

**Comment by brianteeman** [comment]
I don't agree with your conclusion and the purpose of versions is so that you can see what and when and by who something was changed. Removing the versions data (which is very small) would defeat that aim.

**Comment by mattiaverga** [comment]
Well, version data is not so small... I have a site with nearly 5.000 articles and versioning set to 3, the whole database size is 348 MByte, 'content' table is less than 48 MByte, but 'ucm_history' is 120 MByte. That's more than 33% of the database size...

Anyway, if I choice to disable versioning (I don't really need it) is it safe to purge 'ucm_history' table? And what about 'ucm_base' and 'ucm_content'? Are they only related to versioning and can I purge them as well?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18332">issues.joomla.org/tracker/joomla-cms/18332</a>.</sub>
