### ISSUE TITLE
Joomla Profile plugin TOS bug

### ISSUE THREAD

**Issue by BjornvanSchie** [joomla/joomla-cms#18333]
### Steps to reproduce the issue
- Install Usergroup Selector (http://function90.com/products/usergroup-selector.html)
- Enable Usergroup Selector and select some groups at the "Allowed User Groups" field.
- Enable Joomla User - Profiles and require TOS and select TOS article
- Register a user from frontend with a group

### Expected result
User will be created with the selected group/groups.

### Actual result
User created, but without groups. This is because the JUser->save() is returning false. While further investigating the problem. its telling me the error using the following:
$juser->getError();
This is the result i got: Please read the Terms of Service. You will not be able to register if you do not agree with them.

(these snippets are found in the onUserAfterSave function within the plugin)

My guess is that there is a issue with the User-Profile plugin from joomla. since everything is going fine when i haven't got a TOS Article selected.

### System information (as much as possible)
Problem accours on the the following platforms:
- Windows 10 running latest version of Xampp
- MacOS running latest version of Mamp pro
- Ubuntu running webmin with apache2 server

All the instances are running a clean setup of joomla 3.8.1

### Additional comments
Teamviewer is possible if needed, also remote joomla login is do-able.

**Comment by brianteeman** [comment]
I dont have any problem using the TOS option with the core of joomla so the issue must be with the extension. Checking the extension web site i can see that they have problems when you have custom fields enabled as well. Please contact them directly for support.

Closed as not a core issue

**Comment by brianteeman** [comment]
Also check their site for the other people reporting issues with that plugin and tos 
http://function90.com/support/usergroup-selector/343-it-is-not-working-on-my-joomla-3-6-site.html

**Comment by coolcat-creations** [comment]
I confirm that there is a bug executing user plugins if a tos article is selected. If no article is selected everything works fine. Can we reopen this issue @brianteeman ?

EDIT: A quick workaround is to leave the Tos Article empty and to include the link to the TOS in the language .ini file into the label of the TOS PLG_USER_PROFILE_FIELD_TOS_LABEL. Not beautiful but it works.

**Comment by ghost** [comment]
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18333">issues.joomla.org/tracker/joomla-cms/18333</a>.</sub>

**Comment by Quy** [comment]
@coolcat-creations Please confirm that PR #19633 fixes this issue. Thanks.

**Comment by Quy** [comment]
@BjornvanSchie You marked #19633 tested successfully. If this is fixed, please close this issue. Thanks.

**Comment by Quy** [comment]
Closing as #19633 has merged. This can be reopened if still an issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18333">issues.joomla.org/tracker/joomla-cms/18333</a>.</sub>
