### ISSUE TITLE
User of group admin can view and modify backend module with access of super user

### ISSUE THREAD

**Issue by sonosergio** [joomla/joomla-cms#18331]
### Steps to reproduce the issue
Create module for backend with access only for "super user" and position cpanel

### Expected result
The user of group administrator not see the module in cpanel position and NOT see the module in module configuration page

### Actual result
The user of group administrator not see the module in cpanel position but SEE the module in module configuration page

### System information (as much as possible)
Joomla! 3.8.1 Stable

**Comment by alikon** [comment]
you should set the proper permission for the com_modules  when an user is member of administrator group accordingly 
something like
![screenshot from 2017-10-13 20-11-46](https://user-images.githubusercontent.com/181681/31559976-d2aa370a-b052-11e7-9896-62df86178086.png)

**Comment by brianteeman** [comment]
@alikon doesnt that remove all access to modules. The user is saying that he doesnt want an admin user to be able to see a module set for superusers only

**Comment by mbabker** [comment]
It's another of those viewing access levels versus the "normal" ACL things again...

**Comment by alikon** [comment]
should we need to introduce some kind of new Action property "Backend visibilty" ?

**Comment by alikon** [comment]
@brianteeman yes i've missunderstood
proposed a fix #18335 (hoping now i've understand a little bit more  :smile:)

**Comment by ghost** [comment]
closed as having Pull Request #18335
