### ISSUE TITLE
Error of the file cache storage in joomla 3.8 fixed

### ISSUE THREAD

**Issue by alor702000** [joomla/joomla-cms#18338]
### Steps to reproduce the issue
Re : Error of the file cache storage

go to configuration.php and put:
public $cache_handler = '';

**Comment by ghost** [comment]
closed as Answer is given at [Comment](https://github.com/joomla/joomla-cms/issues/16862#issuecomment-336652558)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18338">issues.joomla.org/tracker/joomla-cms/18338</a>.</sub>
