### ISSUE TITLE
menu xtd in article editor fails to report correctly in admin-items-modal.min.js after search for menu item

### ISSUE THREAD

**Issue by shawnmcginn** [joomla/joomla-cms#18340]
### Steps to reproduce the issue
Joomla version 3.7.5
Frontend or backend, in article editor select Menu to insert a menu link, search for a menu item in the modal and select any menu item.

### Expected result
Should write a link for the menu item at the cursor in the article window

### Actual result
Does nothing.  If you look at admin-items-modal.min.js this condition evaluates to true because Joomla.getOptions('xtd-menus') is undefined following a search:
if (!Joomla.getOptions('xtd-menus')) {
   // Something went wrong!
   window.parent.jModalClose();
   return false;
}
Note, if you do not search for a menu item and select from the list of available items it works as expected. Therefore you can work around the problem by searching for the desired menu item, select said item, the modal will close, re-open the modal, your search query is retained and you can now choose the desired element.

### System information (as much as possible)
Joomla version 3.7.5
running on linux shared hosting 

### Additional comments
my first defect submission, my apologies if I'm lacking any necessary info

**Comment by ghost** [comment]
Please update on latest Version and test using Core-Template without 3rd-Party-Components and Plug-Ins if this Issues is same.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18340">issues.joomla.org/tracker/joomla-cms/18340</a>.</sub>

**Comment by infograf768** [comment]
Issue confirmed on staging.
As soon as Search is used in the modal, the link to the menu item selected is NOT entered in the text field. One has to reload the modal to be able to enter the link.
+ the Clear button is broken

**Comment by infograf768** [comment]
@dgt41 Can you look into this?

**Comment by dgrammatiko** [comment]
Please test https://github.com/joomla/joomla-cms/pull/18359

**Comment by brianteeman** [comment]
Closed bas we have a pr for testing

**Comment by infograf768** [comment]
@shawnmcginn 

Please test/confirm https://github.com/joomla/joomla-cms/pull/18359
