### ISSUE TITLE
Brochure sample data needs more sample data

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#18348]
### Steps to reproduce the issue
1.Make a clean fresh install of Joomla 3.8.1
2. Select sample data 'Brochure'.
3. After completed installation, add Intro image and Full article image to article "Article 1 Title". (This is default in article sample data)
4. Open this article in frontend in Details View. It should be at this link; yourdomain.com/index.php/news/3-article-1-title

### Expected result
Breadcrumbs should be at the bottom

### Actual result

Breadcrumbs is wedged at the side

### Additional comments
Spotted by Maradona in https://forum.joomla.org/viewtopic.php?f=706&t=955721

Adding sample text wraps the breadcrumbs to the bottom as expected

**Comment by ghost** [comment]
can you please look at #18210?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18348">issues.joomla.org/tracker/joomla-cms/18348</a>.</sub>

**Comment by brianteeman** [comment]
Closed as fixed by #18210 and adding more data is never the correct fix ;)
