### ISSUE TITLE
[3.9] Check MVC Factory existance to avoid B/C Fatal Error

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#18349]
### Steps to reproduce the issue
Install an extension running on J 3.8 that extends JControllerLegacy and override the constructor __construct

### Expected result
All works fine

### Actual result
Fatal error: Call to a member function createModel() on null in E:\vhosts\joomla39\libraries\src\MVC\Controller\BaseController.php on line 559

### System information (as much as possible)
With the current MVC backported from J4.0 now a class that extends JControllerLegacy AKA Joomla\CMS\MVC\Controller\BaseController  throws a fatal error if there is an override for the constructor and the property 'factory' is so empty 

### Additional comments
Check the existance of the factory object before calling:
$this->factory->createModel
$this->factory->createView

**Comment by joeforjoomla** [comment]
Reference PR #18351

**Comment by ghost** [comment]
closed as having Pull Request #18351
