### ISSUE TITLE
j3.8.1 Creating one tag results in two url's (SEF/SEO/double content?)

### ISSUE THREAD

**Issue by CEWebDesign** [joomla/joomla-cms#18346]
### Steps to reproduce the issue
create article with tag "mytag"

### Expected result
/index.php/tags/mytag

### Actual result
Two long url's, no cannonical link:
/index.php/component/tags/tag/mytag
/index.php/component/tags/tag/1

### System information (as much as possible)
j3.8.1

### Additional comments
maybe create a new issue for the long url (SEF)?

**Comment by ghost** [comment]
closed as stated in [Comment](https://github.com/joomla/joomla-cms/issues/18219#issuecomment-336706973)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18346">issues.joomla.org/tracker/joomla-cms/18346</a>.</sub>
