### ISSUE TITLE
Fieldgroups elements should be rendered as a pair of  and  instead of a single

### ISSUE THREAD

**Issue by mattiaverga** [joomla/joomla-cms#18342]
Fieldgroups are now rendered as `<dl>` elements with a single `<dd>` element and two `<span>` elements for label and value.
They should be rendered as a pair of `<dt>` and `<dd>` elements.

**Comment by alikon** [comment]
you don't need to open an issue if you are to submit a pull request
this issue can be closed as there is #18343

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18342">issues.joomla.org/tracker/joomla-cms/18342</a>.</sub>
