### ISSUE TITLE
Add a table layout for rendering fieldgroups

### ISSUE THREAD

**Issue by mattiaverga** [joomla/joomla-cms#18344]
I would like to add a table rendering to fieldgroups. The current code already supports it (just add `{fieldgroup 1,table}` and the appropriate layout file `table.php`).

I made some progress at https://github.com/mattiaverga/joomla-cms/tree/fieldgroup_table, but I also want to apply a custom class to the table and to add the title of the fieldgroup as table caption. All the code is already in place in my branch, but I'm not sure how to recall the relevant fieldgroup options...

Is anyone willing to help developing this?

**Comment by mattiaverga** [comment]
PR #18367 partially solves this feature request. It misses the abilities to choose to display the table caption or not and to apply a custom class to the fieldgroup (e.g. to the `<table>` element).

**Comment by rdeutz** [comment]
closing this issue because we have a PR #18367
