### ISSUE TITLE
Smart Search button disabled class not removed on entering data

### ISSUE THREAD

**Issue by saraheagle** [joomla/joomla-cms#18358]
### Steps to reproduce the issue
On a clean new site >> system >> global config >> smart search >> smart search tab
Allow empty search = no

### Expected result
on /index.php?option=com_finder&view=search
<button name="Search" type="submit" class="btn btn-primary disabled">
Button has class="disabled"
When you enter a search term, I expect the disabled class to be removed

### Actual result
The disabled class is not removed until after the form has been submitted.
If you have Bootstrap this style makes the button unclickable.
.btn.disabled  {cursor:not-allowed; pointer-events:none}

**Comment by brianteeman** [comment]
That entire code needs review. 
The aim of the option "allow empty search" is for when you have filters selected
So for example if i wanted to find all the articles from a specific author then I could simply select the filter. But if allow empty search is set to no then I cant do that.
I guess that what needs to happen is for the class disabled to be removed as soon as you type in the search box when "allow empty search" is set to no

**Comment by brianteeman** [comment]
it probably needs something like ajaxchosen added to detect the inputs

**Comment by brianteeman** [comment]
@Hackwar did you see this issue

**Comment by Quy** [comment]
See #29474 for reply.

**Comment by Hackwar** [comment]
Since #29474 seems to now be working, can we close this one?
