### ISSUE TITLE
Viewport is not working

### ISSUE THREAD

**Issue by talants** [joomla/joomla-cms#18365]
### Steps to reproduce the issue

After upgrade to Joomla 3.7.3 the layout switcher uses only tablet layout. If i delete layout-tablet.css it uses only layout-mobile.css. And again i delete mobile layout it uses the standart layout.css. Alone all layouts work fine. In 3.7.2 it works as intended. After 3.7.3 to 3.8.1 can't choose proper layout. 

### System information (as much as possible)
Template is JA University. 
Linux web 3.16.0-4-686-pae #1 SMP Debian 3.16.7
Database version 5.5.49-0+deb8u1 
Php 5.6.23-0+deb8u1 
Apache

**Comment by brianteeman** [comment]
These layouts are part of your template (if I understand you correctly) and you should speak to your template provider for support.
