### ISSUE TITLE
Can't use menu aliases that begin with media

### ISSUE THREAD

**Issue by travisrisner** [joomla/joomla-cms#18366]
### Steps to reproduce the issue
* Create New Menu Item
* Select any menu type
* Set the alias to a word, such as "mediation" (you can do anything that begins with media)

### Expected result
* Loading /mediation on the front end of the website would load the correct menu item.

### Actual result
* 403 error is thrown on the front end when trying to load /mediation.

### System information (as much as possible)
* PHP 7.1.10
* Joomla 3.8.1
* Database Version 5.7.19
* Web Server nginx/1.10.3

### Additional comments
* It does seem to load properly when setting a Parent item on the menu item.
* If you put something in front of media, for example test-media, it does load properly.

**Comment by ghost** [comment]
Can't confirm.

Loading a Menu in Frontend `/index.php/en/mediation` works as expected.

**Comment by travisrisner** [comment]
Sorry, I should have specified this happens with "Search Engine Friendly" urls turned on under Site Settings.

**Comment by travisrisner** [comment]
I'm going to close this issue. After further investigation, it is something specific in our Nginx setup and not related to Joomla at all. My apologies.
