### ISSUE TITLE
default datepicker with drop-down year & months

### ISSUE THREAD

**Issue by sepehr09** [joomla/joomla-cms#18360]
hi,
is this possible to select year & month with drop-down (or typing) in default joomla datepicker? i search for date picker with all default joomla datepicker features + dropdown (or typing year)  but i found nothing!
this is very difficult selecting year with navigate bar for example if we want to select 1990 we have to navigate 27 times! but if i can type 1990 or select in drop-down ( with max - min period) this is so easier !
best regards.

**Comment by brianteeman** [comment]
Do you mean like this
![date](https://user-images.githubusercontent.com/1296369/31692629-7b419cea-b392-11e7-831f-e6f34dee28d7.gif)

**Comment by sepehr09** [comment]
thanks for your response,
i mean if click on year (2017) or if click on month(october), the drop-down list open with min-max period we set in xml. this way we can select for example 1984 so easier than navigating with tap on left arrow so many times!
for birthdate this is so helpfull.
![image](https://user-images.githubusercontent.com/11753906/31787689-6540cadc-b519-11e7-95d2-c6259c062d33.png)


best regards!

**Comment by jwaisner** [comment]
Closing as J3 is not available to add features to. Please check J4 to see if the requested feature already exists, and if not please open a feature request for J4.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18360">issues.joomla.org/tracker/joomla-cms/18360</a>.</sub>

**Comment by brianteeman** [comment]
Please stop closing valid feature requests on this criteria. You can just change the tag from J3 to J4 re-evaluate
