### ISSUE TITLE
Cannot install or update extentions after updating to 3.8.1

### ISSUE THREAD

**Issue by sasany** [joomla/joomla-cms#18374]
### Steps to reproduce the issue
Extensions > Manage > install > select extensions > install

### Expected result

Message
install package was successful.

### Actual result

Error
Unable to find install package

### System information (as much as possible)
``
     Joomla! Instance :: Joomla! 3.8.1-Stable (Amani) 4-October-2017
    Joomla! Platform :: Joomla Platform 13.1.0-Stable (Curiosity) 24-Apr-2013
    Joomla! Configured :: Yes | Read-Only (444) | Owner: --protected-- . (uid: /gid: ) | Group: --protected-- (gid: ) | Valid For: 3.8
    Configuration Options :: Offline: 0 | SEF: 1 | SEF Suffix: 1 | SEF ReWrite: 1 | .htaccess/web.config: Yes | GZip: 1 | Cache: 0 | CacheTime: 15 | CacheHandler: file | CachePlatformPrefix: 0 | FTP Layer: 0 | Proxy: 0 | LiveSite: | Session lifetime: 15 | Session handler: database | Shared sessions: 0 | SSL: 0 | FrontEdit: 1 | Error Reporting: none | Site Debug: 0 | Language Debug: 0 | Default Access: 1 | Unicode Slugs: 1 | Database Credentials Present: Yes

    Host Configuration :: OS: | OS Version: | Technology: | Web Server: LiteSpeed | Encoding: gzip, deflate | Doc Root: --protected-- | System TMP Writable: Yes

    PHP Configuration :: Version: 7.0.9 | PHP API: litespeed | Session Path Writable: Yes | Display Errors: 1 | Error Reporting: 22519 | Log Errors To: error_log | Last Known Error: 20th October 2017 08:53:37. | Register Globals: | Magic Quotes: | Safe Mode: | Open Base: /home3/xxx:/usr/lib/php:/usr/php4/lib/php:/usr/local/lib/php:/usr/local/php4/lib/php:/tmp | Uploads: 1 | Max. Upload Size: 100M | Max. POST Size: 100M | Max. Input Time: 60 | Max. Execution Time: 60 | Memory Limit: 280M

    MySQL Configuration :: Version: 5.6.37-log (Client:5.6.37) | Host: --protected-- (--protected--) | Collation: latin1_swedish_ci (Character Set: latin1) | Database Size: 158.77 MiB | #of Tables: 106

    Detailed Environment :: wrote:
    PHP Extensions :: Core (7.0.9) | date (7.0.9) | libxml (7.0.9) | openssl (7.0.9) | pcre (7.0.9) | sqlite3 (0.7-dev) | zlib (7.0.9) | bcmath (7.0.9) | calendar (7.0.9) | ctype (7.0.9) | curl (7.0.9) | dom (20031129) | hash (1.0) | fileinfo (1.0.5) | filter (7.0.9) | ftp (7.0.9) | gd (7.0.9) | gettext (7.0.9) | SPL (7.0.9) | iconv (7.0.9) | session (7.0.9) | intl (1.1.0) | json (1.4.0) | mbstring (7.0.9) | mcrypt (7.0.9) | standard (7.0.9) | mysqli (7.0.9) | mysqlnd (mysqlnd 5.0.12-dev - 20150407 - $Id: 241ae00989d1995ffcbbf63d579943635faf9972 $) | Phar (2.0.2) | posix (7.0.9) | Reflection (7.0.9) | imap (7.0.9) | SimpleXML (7.0.9) | soap (7.0.9) | sockets (7.0.9) | exif (1.4 $Id: 8bdc0c8f27c2c9dd1f7551f1f9fe3ab57a06a4b1 $) | tidy (7.0.9) | tokenizer (7.0.9) | wddx (7.0.9) | xml (7.0.9) | xmlreader (7.0.9) | xmlrpc (7.0.9) | xmlwriter (7.0.9) | xsl (7.0.9) | zip (1.13.3) | litespeed () | SourceGuardian (11.1.1) | PDO (7.0.9) | pdo_mysql (7.0.9) | pdo_sqlite (7.0.9) | ionCube Loader () | Zend Engine (3.0.0) |
    Potential Missing Extensions :: mysql | suhosin |

    Switch User Environment (Experimental) :: PHP CGI: No | Server SU: No | PHP SU: No | Custom SU (LiteSpeed/Cloud/Grid): Yes
    Potential Ownership Issues: No 

    Folder Permissions :: wrote:
    Core Folders :: images/ (755) | components/ (755) | modules/ (755) | plugins/ (755) | language/ (755) | templates/ (755) | cache/ (755) | logs/ (755) | tmp/ (755) | administrator/components/ (755) | administrator/modules/ (755) | administrator/language/ (755) | administrator/templates/ (755) | 

### Additional comments
i installed joomla update automatically from update section from 3.7.2 to 3.8.1 without error and flawlessly
The only issue is that after update I cannot install or update extentions, the website works on the frontend.
I have checked everything extensively. The folders are writable, my log and tmp paths are correct, I know that for sure,

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.

**Comment by songwa** [comment]
I have this problem before, but now is ok
check this : joomla backstage:
System ->System Information -> php setting ->Open basedir

in my case. I use Synology NAS (DSM), and php.ini setting like this

> Open_basedir = /tmp:/var/services/tmp:/var/services/web:/var/services/homes

it cannot install any package from joomla install extensions

when I modify the php.ini setting to none is OK

> :open_basedir =
