### ISSUE TITLE
Joomla updation 2.5.x to 3.x for domain jobsnprofiles.com when trying to upgrade getting error

### ISSUE THREAD

**Issue by NityaSoftwareSolutionsInc** [joomla/joomla-cms#18376]
Hi,

We have joomla old version 2.5x for domain jobsnprofiles.com but when we update joomla latest version getting some errors. Here is the errors as follows:

Fatal error: Class 'plgSystemSocialLoginTools' not found getting this in frontend.

For Administrator errors:

Fatal error: Class 'plgSystemSocialLoginTools' not found![screen shot 2017-10-21 at 04 55 10](https://issues.joomla.org/uploads/1/2eea929a49ac91df3e1851c85d224bf5.png)
![screen shot 2017-10-21 at 04 55 13](https://issues.joomla.org/uploads/1/bc581972978577e792fd8bf33c5e32f2.png)

Please help me the issue as soon as possible.

Thanks and Regards,
Raviteja

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
