### ISSUE TITLE
Debug System is really slow in 3.8.1

### ISSUE THREAD

**Issue by fillera** [joomla/joomla-cms#18378]
### Steps to reproduce the issue
Set to YES the parameter 'Debug System' in Global configurations

### Expected result
Execution of any action (site or admin) in a suitable time.

### Actual result
The execution of any action (site or admin) is too much slower than in 3.8.0

### System information (as much as possible)
**PHP Built On:** Linux linux-nf1r 4.4.27-2-default #1 SMP Thu Nov 3 14:59:54 UTC 2016 (5c21e7c) x86_64
**Database Version:** 5.5.5-10.1.26-MariaDB
**Database Collation:** utf8_general_ci
**Database Connection Collation:** utf8mb4_general_ci
**PHP Version:** 7.1.9
**Web Server:** Apache/2.4.27 (Unix) OpenSSL/1.0.2l PHP/7.1.9 mod_perl/2.0.8-dev Perl/v5.16.3
**WebServer to PHP Interface:** apache2handler
**Joomla! Version:** Joomla! 3.8.1 Stable [ Amani ] 4-October-2017 14:00 GMT
**Joomla! Platform Version:** Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
**User Agent:** Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by ggppdk** [comment]
What was always slow about it was the page rendering time by the browser
- because the JS that creates the navigation for N SQL queries is O(N\*N) , also if you have a lot of HTML it gets a little more worse than O(N\*N)

So maybe you have installed some extensions that increase the number of SQL queries
how many SQL queries do you have in the page that appears to be slow ?

**Comment by fillera** [comment]
Thank you for your quick response.

The admin panel was showing a slow execution even in com_content (e.g. showing articles)

I installed the ACL Manager extension (powered by Sander Potjer) and it showed than there were some orphan assets.

Once those orphan assets have been fixed, the Debug System has returned to work fine, I mean, with a suitable response time.

So, the problem may be related to those orphan assets...

Anyway, thank you so much for your help.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18378">issues.joomla.org/tracker/joomla-cms/18378</a>.</sub>

**Comment by ghost** [comment]
closed as Issue resolved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18378">issues.joomla.org/tracker/joomla-cms/18378</a>.</sub>
