### ISSUE TITLE
Mcrypt is deprecated but still required by Joomla

### ISSUE THREAD

**Issue by Spudley** [joomla/joomla-cms#18384]
PHP has deprecated the mcrypt extension in PHP 7.1, and will remove it entirely in 7.2. The extension is also often not available in hosted environments, regardless of PHP version.

However it is still shown as required by the Joomla installer, and used by several parts of Joomla.

Given that PHP 7.2 is due out imminently, we should probably be looking to remove this dependency.

(this issue may have been raised already; if it's a dup, please close, but I couldn't find it as searching issues for mcrypt pulls up loads of unrelated tickets where people have referenced it when describing their configuration)

**Comment by mbabker** [comment]
The required uses of mcrypt are phased out and the install checks removed.  Any remaining uses are in optional code components.

**Comment by Spudley** [comment]
Okay. Glad to know you're on top of it  :)  It still showed up in my install checks when I installed a fresh 3.8.1 just now, but did let it pass once I fixed the other issues.

Also, I note that mcrypt is still listed as required on the [Joomla technical requirements page](https://downloads.joomla.org/technical-requirements). I guess that should change too?
