### ISSUE TITLE
[4.0] Update PHPMailer to v6.0.1

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#18386]
https://github.com/PHPMailer/PHPMailer/releases/tag/v6.0.1

@mbabker

**Comment by mbabker** [comment]
I've got other pending PRs doing Composer updates that I want to see merged first.  So, it's on the list to eventually do a general Composer update for 4.0, just other priorities first.

**Comment by brianteeman** [comment]
Closed as this update has been done
