### ISSUE TITLE
Problem recaptcha joomla and k2

### ISSUE THREAD

**Issue by yimilan** [joomla/joomla-cms#18383]
my problem is that recaptcha does not work, it is outdated and it does not allow to register new users.
drive.google.com/file/d/0B2Z45zW4NmmGbGlZMk5Sd3lDd2s/view?usp=sharing

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
