### ISSUE TITLE
View site from https admininstration links to http site.

### ISSUE THREAD

**Issue by pbatink** [joomla/joomla-cms#18385]
### Steps to reproduce the issue![screen shot 2017-10-22 at 07 59 21](https://issues.joomla.org/uploads/1/7c49d7106f290b4c9905f7166f259e89.png)

Create 2 joomla instances
1. http://domain/cms/ 
2. https://domain/cms/

Login as administrator on 2. https://domain/cms/
click "view site"

### Expected result
Show 2. https://domain/cms/

### Actual result
Shows 1. http://domain/cms/ 

### System information (as much as possible)
Joomla 3.8.1
SSL: Let's Encrypt

### Additional comments
I (temporarily) use 2 instances of the same site to test for possible issues with https

**Comment by rdeutz** [comment]
Did you set in global configuration / Server / Force HTTPS to "Entire Site" ?

**Comment by pbatink** [comment]
No. Sorry. I thought I did. Thank you.
