### ISSUE TITLE
Unicode characters in database column "fieldparams" when you use Greek words on custom fields

### ISSUE THREAD

**Issue by haralake** [joomla/joomla-cms#18398]
### Steps to reproduce the issue
Create custom field with type "list" for example.
On list values use greek words on text.
On database you will see that those greek words have unicode characters instead for greek letters.

### Expected result
On database this custom field has greek letters for text values

### Actual result
On database this custom field has unicode letters like \u0398\u03b5\u03c3\u03c3\u03b1\u03bb\u03bf\u03bd\u03af\u03ba\u03b7 instead for greek letters

### System information (as much as possible)
PHP βασισμένη σε	Windows NT DESKTOP-FJQL4NC 10.0 build 15063 (Windows 10) AMD64
Έκδοση βάσης δεδομένων	5.7.14
Ευρετηρίαση βάσης δεδομένων	utf8_general_ci
Σύνθεση σύνδεσης βάσης δεδομένων	utf8mb4_general_ci
Έκδοση PHP	7.0.10
Διακομιστής ιστοσελίδων	Apache/2.4.23 (Win64) PHP/7.0.10
Διεπαφή Διακομιστή Ιστοσελίδων με την PHP	apache2handler
Έκδοση Joomla!	Joomla! 3.8.0 Stable [ Amani ] 19-September-2017 14:00 GMT
Έκδοση Joomla!	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Φυλλομετρητής χρήστη	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36![screen shot 2017-10-23 at 20 34 31](https://issues.joomla.org/uploads/1/11b52906e5d76e224a9c8fbd2f426ed2.jpg)

### Additional comments
I guess that this is a problem with all custom fields that use fieldparams and not only with the list type.
![screen shot 2017-10-23 at 20 34 32](https://issues.joomla.org/uploads/1/ef591cd40bd34fc97e767af5ee65559b.jpg)

**Comment by brianteeman** [comment]
How is it rendered? As Greek?

**Comment by esedic** [comment]
Values are rendered as Greek, probably because values are returned from #_fields_values table, where values are stored as Greek letters.

**Comment by mbabker** [comment]
I'm not seeing the bug here.  As long as the data is correctly decoded back to the right character set when being read from the database it shouldn't be an issue to store it with encoded characters.

**Comment by haralake** [comment]
Well if you need to work with db inport is a problem. If for example you want to import 200 greek cities on custom field list from a csv file or direct from phpmyadmin you will have a big problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18398">issues.joomla.org/tracker/joomla-cms/18398</a>.</sub>

**Comment by mbabker** [comment]
This can only be fixed, if desired, in Joomla 4.

As of PHP 5.4, there is an option for the `json_encode()` options bitmask, `JSON_UNESCAPED_UNICODE`, to instruct PHP to not escape multibyte unicode characters.

3v4l without bitmask - https://3v4l.org/ON13U
3v4l with bitmask - https://3v4l.org/OvHLN

As this is the native PHP behavior, I would suggest not changing it in the Joomla API.

**Comment by ghost** [comment]
closing as no Core-Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18398">issues.joomla.org/tracker/joomla-cms/18398</a>.</sub>

**Comment by esedic** [comment]
Well, as Michael said, since it's noted in Development Strategy that PHP version can only be increased for the first release of a new major version, this looks like a no go till 4.0

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18398">issues.joomla.org/tracker/joomla-cms/18398</a>.</sub>
