### ISSUE TITLE
Template installation broken in PostgreSQL on Joomla 3.8

### ISSUE THREAD

**Issue by Ria-Doshi** [joomla/joomla-cms#18390]
### Steps to reproduce the issue
Extensions - manage - install - Upload package file, after selecting the JA_Healthcare template we getting the following error message - "null value in column "system_data" violates not-null constraint DETAIL: Failing row contains (10003, 0, ja_healthcare, template, ja_healthcare, , 0, 1, 1, 0, {"name":"ja_healthcare","type":"template","creationDate":"Octobe..., {}, , null, 0, 1970-01-01 00:00:00, 0, 0)."

### Expected result
Installation complete and template available in the templates section to enable

### Actual result
"null value in column "system_data" violates not-null constraint DETAIL: Failing row contains (10003, 0, ja_healthcare, template, ja_healthcare, , 0, 1, 1, 0, {"name":"ja_healthcare","type":"template","creationDate":"Octobe..., {}, , null, 0, 1970-01-01 00:00:00, 0, 0)."

### System information (as much as possible)
Our current system setup is 
![image](https://user-images.githubusercontent.com/33010790/31867507-a7700078-b756-11e7-8225-8006736384ba.png)

postgreSQL database.

### Additional comments
The JA_healthcare template does say it's compatible with postgreSQL. We looked at this post (https://github.com/joomla/joomla-cms/issues/16074) but could not find the template.php anywhere

**Comment by brianteeman** [comment]
please contact joomlart for support

**Comment by Ria-Doshi** [comment]
This is the case with any template install not just the Joomlart template and I've also contacted them. Thanks,

**Comment by Bakual** [comment]
I've changed the title to a more helpful one and reopened the issue.

To me it sounds like some strict mode is activated but I don't know if that is default in PostgreSQL or not.

**Comment by csthomas** [comment]
Please test #18391, you can simply add text:
```php
$this->extension->system_data = '';
```
before 385 line in `libraries/src/Installer/Adapter/TemplateAdapter.php`

or replace whole file from `https://github.com/csthomas/joomla-cms/raw/c3c972ab095e4ff53e42dec758dc743e9d779396/libraries/src/Installer/Adapter/TemplateAdapter.php`

If it fixes your issue then mark test as success at https://issues.joomla.org/tracker/joomla-cms/18391

**Comment by ghost** [comment]
closed as having Pull Request #18391
