### ISSUE TITLE
Category Title Should be hidden for non-matching access level in Category Blog Layout

### ISSUE THREAD

**Issue by BartelBe** [joomla/joomla-cms#18397]
### Steps to reproduce the issue
Create a category X with public access level and 2 subcategories Y and Z with access level "registered"
Create a menu link to category X with category blog layout 

### Expected result
The category titles for subcategories Y and Z should only be shown/displayed to logged in -i.e. registered- users.

### Actual result
The Category Titles will be displayed on the page with public access level. On public access, the link correctly produces a 403 error, but the Category Title should not be displayed in the first place to public access.

### System information (as much as possible)
Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 
Database 5.5.5-10.1.26-MariaDB 
utf8mb4_general_ci   
PHP version 7.0.23 
Apache/2 fpm-fcgi 
Joomla! 3.8.1 Stable [ Amani ] 4-October-2017 14:00 GMT 
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by brianteeman** [comment]
I can confirm this

**Comment by infograf768** [comment]
On it.

**Comment by infograf768** [comment]
@brianteeman 
@BartelBe 
Please test https://github.com/joomla/joomla-cms/pull/18408

Closing as we have a patch.
