### ISSUE TITLE
Drag-sorting articles deletes tags

### ISSUE THREAD

**Issue by severdia** [joomla/joomla-cms#18399]
### Steps to reproduce the issue
I add at least one tag to an article and save it. Then drag the order/position of that article to a new position. The tag(s) I previously assigned are now deleted.

### Expected result
The tags should not be affected by article position.

### Actual result
All tags for the moved article are deleted.

### System information (as much as possible)

Joomla 3.8.1
PHP 7.0.24
DB 5.6.36-82.1-log
Apache/2.2.24 (Unix) mod_hive/5.5 mod_ssl/2.2.24 OpenSSL/1.0.0-fips mod_auth_passthrough/2.1 mod_bwlimited/1.4 mod_fastcgi/2.4.6 mod_fcgid/2.3.6

**Comment by brianteeman** [comment]
Please search before posting. This has been reported several times and has already been fixed here #18328

**Comment by severdia** [comment]
Of course I did a search, but nothing came up.
