### ISSUE TITLE
RFC Language filters in admin UI

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#18400]
Currently we can filter things (eg articles and modules) in the admin UI with the language selector search tool.

However it works on an exclusive basis which can cause issues.

## Example 
I have a multilingual site (FR/EN) with some modules assigned to just one language and some modules assigned to all

<img width="892" alt="screenshotr09-49-15" src="https://user-images.githubusercontent.com/1296369/31933302-a5eb154e-b8a0-11e7-9093-59bfb95ddf7d.png">

Now if I only want to see the modules that will appear on EN pages I select english on the filter

<img width="900" alt="screenshotr09-50-25" src="https://user-images.githubusercontent.com/1296369/31933358-cd601822-b8a0-11e7-9bbe-5f30f38353aa.png">

**_Do you see the problem?_**
Hint the modules set to ALL will also appear on the EN pages and there is no way for me to display those modules in the same list.

### Solutions
Possibility would be to 
1. Change the language select to include anything tagged ALL - eg Select FR and you see FR and ALL
2. Change the language select to be a multiselect list eg Select FR and ALL

**Comment by infograf768** [comment]
Proposal 1 does not look right to me as it could include a lot of items in the case of articles for example.
2 could be Ok if no unwanted behavior. (Introducing Multiselect has created a lot of issues).

But basically, I am OK with the filters as they are. If one wants to see which items are tagged to ALL, then filter such.

**Comment by brianteeman** [comment]
The point is that in order to see which modules appear on a French site I might have to filter by French first and then filter again by all.

**Comment by ot2sen** [comment]
Proposal 1 sounds logic. A site maintainer would like to know what is actually shown, which is chosen language and any potential All (should you have chosen to have such)

**Comment by coolcat-creations** [comment]
I think 1) is more logical, because all means also assigned to this language...

**Comment by csthomas** [comment]
I agree with 1). 
If anybody want to see only specified language modules then can sort by language field.

**Comment by woluweb** [comment]
There is one big thing that puzzles me with option 1 : 
Almost all my sites are multilingual. When do I filter for instance Articles or Menu Items on a language basis ? Typically when I want to select them all to batch-duplicate them into the second/third language.
Elements which are set to "all" are already good for "all" languages on the website and per definition don't need to be translated.
So proposition 1 would make life more complicated from that point of view.
But I would be happy with proposition 2, as there everybody gets exactly what she/he wants.

**Comment by Bakual** [comment]
I'd go with option 2 simply because with option 1 there will be no possibility to filter only those tagged to a specific language. This is limiting the filters. There isn't only one usecase for that filter 😊
Option 2 would allow anyone to filter exactly what he wants withou doing some magic behind the scenes. It is much more intuitive.

**Comment by angieradtke** [comment]
I agree with Bakual. For small pages version 1 seems to be more intuitive. However, if you have a very large page with a lot of content, version 1 is rather confusing. I think version 2 is the better alternative if the technical basis  is reliable.

**Comment by ghost** [comment]
Solution 2 is my Choice as its also similiar to other Solutions in Joomla.

**Comment by barredespace** [comment]
Solution 2 seems more intuitive to me.

**Comment by brianteeman** [comment]
I understand the batch example and that makes sense I had not considered that use case.
Thhanks for all the feedback I shall look at implementing option 2
