### ISSUE TITLE
Featured article with Super User access visible to everyone in Home

### ISSUE THREAD

**Issue by danpdanp** [joomla/joomla-cms#18413]
### Steps to reproduce the issue
IT
- nelle opzioni globali degli articoli: impostazione del parametro "Link non autrizzati" su "No"
- nelle opzioni della voce di menù predefinita "Home" (articoli in evidenza di tutte le categorie"): impostazione del parametro "Link non autorizzati" su "Usa impostazioni articolo"
- nelle opzioni dell'articolo: impostazione del parametro "Link non autorizzati"  su "No".
EN (google traslation)
- in the Global Item Options: Setting the "Unsigned Links" parameter to "No"
- in the "Home" default menu item options (articles in all categories): Setting the "Unauthorized links" parameter to "Use item settings"
- in Item Options: Setting the "Unauthorized Link" parameter to "No".

### Expected result
Un articolo in evidenza con accesso "Super user" non dovrebbe essere visibile a tutti in home page, neanche con l'indicazione "Registrati per leggere il seguito" se è stato inserito "leggi tutto". 

A featured article with "Super user" access should not be visible to everyone on the home page, even with the "Sign up to read the tutorial" if "read more" was added.

### Actual result
L'articolo è visto da tutti. Anche l'articolo "non pubblicato" è visibile. 
Tutto ritorna "normale" se l'opzione "Link non autorizzati" passa da "Usa impostazioni articolo" a "No" nelle opzioni della voce di menù predefinita "Home" (articoli in evidenza di tutte le categorie").

The article is seen by everyone. The article "Unpublished" is also visible.
Everything returns "normal" if the "Unauthorized links" option switches from "Use item settings" to "No" in the default home menu item "Home" (highlights of all categories).

### System information (as much as possible)
Linux web-lnx23.ergonet.host 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64
Versione database	5.5.5-10.1.18-MariaDB
Collation database	utf8_general_ci
Collation connessione database	utf8mb4_general_ci
Versione PHP	7.0.8
Web Server	Apache
WebServer interfaccia PHP	cgi-fcgi
Versione di Joomla!	Joomla! 3.8.1 Stable [ Amani ] 4-October-2017 14:00 GMT
Versione piattaforma Joomla!	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by AlexRed** [comment]
I can confirm this situation:
Content--> Articles --> Options --> Show Unauthorised Links =  NO  (default)
Create new article (no readmore), Access = Super User; Featured = yes
Home menu item --> Featured Article
Home menu item Options --> Show Unauthorised Links = Use Article Settings

I can see in the homepage the article for super user, without logging in.

The Article Settings is No or use global (NO), but if I set the 
Home menu item Options --> Show Unauthorised Links = No
I can't see in the homepage the article for super user without logging in.

Seems that something is not working properly<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18413">issues.joomla.org/tracker/joomla-cms/18413</a>.</sub>

**Comment by danpdanp** [comment]
I confirm the situation.
The experts at www.joomla.it have confirmed that they have been able to replicate the problem.
If you have not been able to replicate the problem, I ask: can the problem only occur for some joomla installations?
Can you help me anyway?

In the attached screenshot, the "Test" item has been set to "Super user"
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18413">issues.joomla.org/tracker/joomla-cms/18413</a>.</sub>

**Comment by ghost** [comment]
Status in Issue Tracker is set on "Confirmed".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18413">issues.joomla.org/tracker/joomla-cms/18413</a>.</sub>

**Comment by esedic** [comment]
I can't replicate this issue, although I followed steps to reproduce the issue.
Featured article with Super Users access, com_content option Show Unauthorised Links set to No, menu option Show Unauthorised Links set to Use Global (No), article is not visible for public users and visible for logged in Super Users.

Show Unauthorised Links works as expected in my case.

**Comment by brianteeman** [comment]
Try again  with the menu option as use article settings. That's the bug

**Comment by danpdanp** [comment]
I repeat and confirm:
1) com_content option Show Unauthorized Links set to No
2) menu option Show Unuthorized Links set to "use article settings"
3) featured article with Super Users access
4) article option Show Unuthorized Links set to No
Article is visible to public users.
That's the bug.
Thank you<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18413">issues.joomla.org/tracker/joomla-cms/18413</a>.</sub>

**Comment by alikon** [comment]
@danpdanp  please test #18417

**Comment by danpdanp** [comment]
I applied the change to my site (components/com_content/models/articles.php).
From an initial test, it seems that the problem is solved!
Thank you<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18413">issues.joomla.org/tracker/joomla-cms/18413</a>.</sub>

**Comment by ghost** [comment]
@danpdanp please mark your Test as successfully:

- open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/18417)
- Login with your github-Account
- Click on blue "Test this"-Button above Authors-Picture
- mark your Test as successfully
- hit "submit test result"

**Comment by ghost** [comment]
closed as having Pull Request #18417

**Comment by danpdanp** [comment]
Unfortunately, the problem reoccurs:
- in Articles -> Properties: "Link not authorized" = "No"
- in the default menu item (articles in evidence of all categories): "Link not authorized" = "Use article settings"
- in Article Options: "Link not authorized" = "No"
With these settings, an article published "Highlights", with access to "Super users" is visible on everyone's home page.

**Comment by ghost** [comment]
@danpdanp can you please open a new Issue as Comments on closed Issues didn't get much Notice. If necessary please Link on this Issue.

**Comment by danpdanp** [comment]
I'm sorry!
