### ISSUE TITLE
Add Canonical URLs For Tag Component Pages

### ISSUE THREAD

**Issue by eSilverStrike** [joomla/joomla-cms#18410]
### Steps to reproduce the issue

There are several different URLs that can be used to access either the list of tags or individual tags which list the items that have been tagged (depending if you have the SEF plugin enabled, etc..)

The tag component should add a canonical link which points to the preferred URL of one of its pages (probably based on a menu item that exists). This way Google will not get confused about which URL to use and the page will not be hit with a possible duplicate content issue.

This will also help in situations where someone decides to add/update/change the SEF plugin they are using which could result in different URLs being generated for the tags component.

For more information on Canonical URLs and how they should work see: https://support.google.com/webmasters/answer/139066?hl=en

### Expected result

Add to the head of the page the proper canonical URL. Example:

`<link rel="canonical" href="https://www.yoursite.com/tags/tag-alias" />`

### Actual result

No Canonical links are created at this time by the tags component.

### Additional comments

Articles have a similar issue which has been fixed with this pull request https://github.com/joomla/joomla-cms/issues/18318

**Comment by ghost** [comment]
@csthomas can you please have a Look on this Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18410">issues.joomla.org/tracker/joomla-cms/18410</a>.</sub>

**Comment by eSilverStrike** [comment]
Hopefully someone can look into this soon.

**Comment by ghost** [comment]
#22589 is this related?

**Comment by eSilverStrike** [comment]
#22589 is some what related along with issue #18219.  What this feature request does is add a Canonical URL within the html source that points to the correct URL for the content. This is used by search engines like Google so they know which url to display on the search engine result pages in the case of when more than one url will display the same page.  (and to avoid duplicate content issues)

I don't really understand the Joomla Dev Team sometimes. Canonical URLs is such a basic and IMPORTANT part of SEO. To not have it implemented for all the core components is crazy especially with the way the Joomla Router spits out different URLs for the same page.

Joomla does a lot right but this is one thing they need to fix (not just for the tag component).

**Comment by stalker-code** [comment]
I have the same problem.And I still could not solve it.

**Comment by ghost** [comment]
@stalker-code @eSilverStrike I see this bug not solved in Joomla! 3.9.15, it seems that joomla do not have developers to solve these issues for years now, better use wordpres for new site if this issue is important to you

**Comment by SniperSister** [comment]
@Milglius let me be crystal clear here: any positive contribution is very welcome in the Joomla community and in this tracker, so we highly appreciate if you want to help make Joomla better by i.e. testing or writing patches or moderating tickets.

As you however prefer to just open pointless tickets (see the version hash tickets), moan or leave toxic comments like this one, I hereby suspend for 30 days. Please use that time to consider how a more healthy contribution can look like. 

Thanks.

**Comment by jwaisner** [comment]
Closing as J3 is not available to add features. Please check J4 and request a feature for J4 if this request is still valid there.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18410">issues.joomla.org/tracker/joomla-cms/18410</a>.</sub>
