### ISSUE TITLE
Extension update creates multiple listing in extension table when using Joomla postgresql setup

### ISSUE THREAD

**Issue by mgilkes** [joomla/joomla-cms#18412]
This problem only applies to a Joomla setup where the database is Postgresql. I tested this on Postgresql version 9.5. There is no issue when trying this on a typical Joomla setup with MySQL. When you try to update or re-install an extension, the extension is listed multiple times for each time it is updated/re-installed, and has its own extension id.

### Steps to reproduce the issue
Take any extension with method="upgrade" in its manifest, and install it once. Then re-install it again. Just use Extension > Install > Upload Package File. You may do the re-installation as many times as you want. 2-3 times will prove the case.

### Expected result
It is expected that no matter how many times an extension is re-installed, the list in Extension > Manage would only ever have 1 entry for that extension, which was from the original, first-time installation. This is what happens when you do this on a typical Joomla-MySQL based setup.

### Actual result
If you reinstall it once, you will see 2 entires when you click on Extension > Manage. If you update/re-install it twice, you will see 3 entries. One for the first time, and 2 more for the 2 subsequent re-installations, each with different extension Ids.

### System information (as much as possible)
I tested this on a MAMP 4.1 installation on Mac OS X 10.12.6, using PHP 7.1, and MySQL 5.6.34 and Postgresql 9.5. I used 2 separate Joomla 3.8.1 installations to verify the results.

### Additional comments

**Comment by alikon** [comment]
@mgilkes please test #18416

**Comment by ghost** [comment]
closed as having Pull Request #18416
