### ISSUE TITLE
Regression: Lost many Contact Display Options

### ISSUE THREAD

**Issue by AlexRed** [joomla/joomla-cms#18423]
### Steps to reproduce the issue
Create a new menu item:  **Contacts** » **Single Contact**  
Try to disable in the **Contact Display Options**  the **Name** or **Street Address** or **Postal/ZIP Code** ecc..   
These parameters are no longer available

### Expected result
I can enable/disable in the **Contact Display Options**  the **Name** or **Street Address** or **Postal/ZIP Code**

### Actual result
I can't enable/disable in the **Contact Display Options**  the **Name** or **Street Address** or **Postal/ZIP Code**

### System information (as much as possible)
![dysokay-381](https://user-images.githubusercontent.com/1362388/32067582-aa858bf2-ba7b-11e7-9939-b3cdd6cbd95d.png)

![display-375](https://user-images.githubusercontent.com/1362388/32067595-aeb6c4c0-ba7b-11e7-865c-c0f1f3604a93.png)

### Additional comments
ok in Joomla 3.7.5
No in Joomla 3.8.0 and Joomla 3.8.1 and Joomla 3.8.2 Dev.

**Comment by brianteeman** [comment]
it looks like showon is not working for a global option. it works correctly is changed from global to a local setting

**Comment by ghost** [comment]
Issue confirmed.

### System information
3.8.2-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 56 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18423">issues.joomla.org/tracker/joomla-cms/18423</a>.</sub>

**Comment by infograf768** [comment]
Concretely, it will only work for single contact menu item or when editing a contact IF the global settings `Contact Information` is set to `Hide`.
In that case, switching to `Show` in the menu item or the contact itself will work as intended and display the fields.

**Comment by ghost** [comment]
True, @infograf768. So the Issue is that Global Setting "Contact Information: Show" isn't respected in single Contact and Single Contact-Menu.

**Comment by infograf768** [comment]
The problem is similar for articles.
Global Options display `Linked Titles` if `Show Title` is set to SHOW.

The showon is missing in article xml (should be added btw), but if I add a showon to obtain
```
			<field
				name="link_titles"
				type="list"
				label="JGLOBAL_LINKED_TITLES_LABEL"
				description="JGLOBAL_LINKED_TITLES_DESC"
				class="chzn-color"
				showon="show_title:1"
				useglobal="true"
				>
				<option	value="0">JNO</option>
				<option value="1">JYES</option>
			</field>
```
When editing an article `Show Title` would display `Use Global (Show)`
and `Linked Titles` field will not display until `Show Title` is set to `Show`.

Therefore the issue is not specific to com_contacts.

**Comment by irbian** [comment]
Regarding this I don´t know if related but

I had "sliders" as global configuration and "plain" as contact configuration. The contact form appeared as "sliders"

**Comment by ghost** [comment]
@irbian can you please open a new Issue?

**Comment by irbian** [comment]
Sure

**Comment by jwaisner** [comment]
@AlexRed Is this issue still existent in latest J3?

**Comment by brianteeman** [comment]
4 and half years later I think that can be closed
