### ISSUE TITLE
Notes for articles feature request

### ISSUE THREAD

**Issue by alandarr** [joomla/joomla-cms#18422]
I'd like to submit a feature request to have a notes field similar to the notes field in modules.

When looking at the list of modules, the note appears below the module title.

I think this would be useful to also have this feature for articles.

Thanks

**Comment by coolcat-creations** [comment]
Can you tell me the benefits or a usage example of this feature?

**Comment by saraheagle** [comment]
I agree, it would be very useful, for site builders and higher admins.

They could use this as a permanent note to say why this article has been added, why you should not do 'x' to it, why it has been setup in a specific way, how to apply specific colours or layout to it, etc. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18422">issues.joomla.org/tracker/joomla-cms/18422</a>.</sub>

**Comment by coolcat-creations** [comment]
You could create a custom Field without automatic display and write your notes in there. Is that a possible solution for you?

**Comment by ghost** [comment]
Core should be light as possible. As i understand @saraheagle i would go for a Plug-in-Solution. Module as @alandarr wrote: This Function also not in Core, also in (same?) Plug-In like Weblinks.

**Comment by saraheagle** [comment]
Thanks so much for quick replies - a custom field is a good idea, but it's on another tab and not shown in the article list, whereas the module notes are. I am thinking it would be used to give info for very nervous and/or incompetent admins.

An extra column in the content table is not a huge overhead - a plugin would be much more of an overhead?

**Comment by coolcat-creations** [comment]
Well, possibly someone could create a nice plugin to give you the ability to show whichever custom field you want in the article overview.

**Comment by alandarr** [comment]
I will certainly explore the options given here.

I understand the need for the core to be as small as possible, however, somewhere a long the way, someone suggested that this function be added to modules. It is indeed a nice feature. As far as plugins go, for me, less is better - just one more dependency to a third party.

I'm only suggesting that the same feature could be considered for articles. I would refer back to saraheagle above for examples of the benefits. This is exactly how I use it within the modules.

Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18422">issues.joomla.org/tracker/joomla-cms/18422</a>.</sub>

**Comment by Quy** [comment]
Just noting that this has been requested before #16180

**Comment by alandarr** [comment]
I would agree with @saraheagle 

> They could use this as a permanent note to say why this article has been added, why you should not do 'x' to it, why it has been setup in a specific way, how to apply specific colours or layout to it, etc.

If it was added to the modules, why not the articles? Whatever reasoning was used in the modules should also be worthy to consider for articles. J4 is boasting new admin features - I'd like this to be seriously considered.

@brianteeman closed the other thread. I'm for keeping this one alive.

**Comment by brianteeman** [comment]
its a fairly simple change to make

**Comment by alandarr** [comment]
Thanks @brianteeman for at least considering it. I normally create an admin module for every site in the control panel including links to edit pages, but the back and forth gets old. Opening a second browser tab works but not as practical as seeing notes directly in the article/module list.

Didn't see you at JWC17 this year. A good conference as usual - I always learn something new!

**Comment by brianteeman** [comment]
See #19134
