### ISSUE TITLE
index.php?option=com_users&view=login ==>> index.php/component/users/profile?Itemid=101

### ISSUE THREAD

**Issue by Frankh-de** [joomla/joomla-cms#18421]
### Steps to reproduce the issue
http://www.wassermühle-karoxbostel.de/index.php?option=com_users&view=login
use this link to login with joomla-cms and the password = login

### Expected result
Just perform the login in the frontend and show the startpage

### Actual result
Warning from Joomla
http://www.wassermühle-karoxbostel.de/index.php/component/users/profile?Itemid=101

### System information (as much as possible)
Joomla 3.8.1 freshly installed
all tables from DB removed
DB backup imported from living and updated Joomla with the same error

### Additional comments
I performed the full new install on strato.de to get rid of the login error, but the behavior is copied.
On the empty or fresh Joomla 3.8.1  the login works fine.

**Comment by ghost** [comment]
Message is `Call to a member function setState() on boolean` also `Array` on different Positions.

Test on local 3.8.2-dev: Can't confirm.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18421">issues.joomla.org/tracker/joomla-cms/18421</a>.</sub>

**Comment by Frankh-de** [comment]
The freshly installed Joomla 3.8.1 on strato.de does not show the issue.
Just after the import of all tables after removing the original tables transferred the issue to the new joomla installation.

Any idea where to search for a solution?
Where can I find the Itemid 101?
Jos_assets looks like the only table with more than 100 entries but 101 is not listed.

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
