### ISSUE TITLE
Ability to set category blog layout override from menu item

### ISSUE THREAD

**Issue by saraheagle** [joomla/joomla-cms#18424]
### Steps to reproduce the issue
Create a new "Category Blog" menu item >> Blog Layout 

### Expected result
I would like to have a "Choose a layout" dropdown _for the blog layout_ (as opposed to the article layout in the options tab), so the new menu item can use the standard 'Category Blog Layout' menu options.

### Actual result
No dropdown, a whole new menu item type with an .xml file needs to be duplicated and amended.

### System information (as much as possible)
Joomla 3.8.1

### Additional comments
The less code that needs duplicating from Joomla Core the better for keeping a Joomla site updated.

Thank you

**Comment by ghost** [comment]
@coolcat-creations looks like a Topic for you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18424">issues.joomla.org/tracker/joomla-cms/18424</a>.</sub>

**Comment by coolcat-creations** [comment]
Yes, it's the still pending PR afaik 
https://github.com/joomla/joomla-cms/pull/16755
@saraheagle please test this :)

**Comment by ghost** [comment]
Thanks for Info, @coolcat-creations, closing Issue as having PR #16755<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18424">issues.joomla.org/tracker/joomla-cms/18424</a>.</sub>

**Comment by Sieger66** [comment]
I think there is a missunderstanding between  saraheagle and  coolcat-creations.

PR 16755 and 14802 set the single-articles-details-page-layout from menu item.
This is the view that you see in the frontend after klick on a
   article in a catergory -blog (for example):

http://j38.joomla-bugs.de/using-joomla/extensions/components/content-component/article-category-blog.html

   view of single-articles-details-page-layout from menu item (for example):

http://j38.joomla-bugs.de/using-joomla/extensions/components/content-component/article-category-blog/17-first-blog-post.html


PR 16755 make this for the article-category-list-menu-item
PR 14802 make this for the article-category-blog-menu-item

but saraheagle want to "Choose a layout" dropdown for the blog layout !

**Comment by ghost** [comment]
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18424">issues.joomla.org/tracker/joomla-cms/18424</a>.</sub>

**Comment by AndySDH** [comment]
@saraheagle I see the reasoning for your idea, I also brought this up some time ago, but here is what @Bakual had to say on the matter (with a comment on #18150)

> The menu items are based on the layouts. It doesn't make sense to select a menuitem for a specific layout and then change that layout in its parameters.
Eg "category blog" and "category list" refer to the same view, but different layouts within that view.

I guess what he says is correct. By implementing this feature, you would be able to create a "Category Blog" menu and change the layout to "Category List"... it wouldn't make too much sense.

**Comment by Bakual** [comment]
> a whole new menu item type with an .xml file needs to be duplicated and amended.

That's actually the correct way because as said by Andy (and me) the menuitem itself already refers to a layout.
I agree that it isn't that sexy to duplicate the whole XML file. My approach however would be different. See https://github.com/joomla/joomla-cms/pull/10548.
My idea in that PR is to specify the bulk of the parameters at the view level, and in the layout XML files you only have the additional parameters relevant for that specific layout. That would probably solve your issue as well if I understood it correct.

**Comment by mbabker** [comment]
Unless someone is going to redesign the menu item management workflow, this should be closed as expected behavior.  Menu items are based on a specified layout of a specified view in a specified component, the menu item itself isn't designed to have a configurable layout option.

**Comment by ghost** [comment]
Closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18424">issues.joomla.org/tracker/joomla-cms/18424</a>.</sub>
