### ISSUE TITLE
fopen('buffer://tmp', 'r'); in FtpClient causing PHP warning

### ISSUE THREAD

**Issue by stAn47** [joomla/joomla-cms#18425]
### Steps to reproduce the issue
a customer of mine reports a PHP Warning: 

PHP Warning:  fopen(): Unable to find the wrapper "buffer" - did you forget to enable it when you configured PHP?

in 

/libraries/src/Client/FtpClient.php

joomla 3.8.1 + php-fpm 7.0.22 via proxy_fcgi 

it seems that: 

$buffer = fopen('buffer://tmp', 'r');

the buffer may not be always registered type for streams. (actually in most cases it probably is not)

Registered PHP Streams (defaults i believe):
php5.6 to php7.2: 
https, ftps, compress.zlib, php, file, glob, data, http, ftp, phar, zip

best regards, stan

**Comment by mbabker** [comment]
See https://github.com/joomla/joomla-cms/pull/18075 for solution.
