### ISSUE TITLE
"Fields" do not work

### ISSUE THREAD

**Issue by burgutex** [joomla/joomla-cms#18428]

**Comment by wojsmol** [comment]
Hi @burgutex
Please describe the issue in details.

**Comment by burgutex** [comment]
Joomla 3.7.3 's Newskit named template and Joomla 3.8.1 I made the new installation. It was tried offline in PHP 5.4 and 5.7. Considering the sensitivity of PHP version.

Joomla This option does not work when you add a list, picture, or other custom option in the "Field Groups / Fields" field. Only 1 list item is displayed for the list you are creating. You can not choose photos. I tried to edit the profile in the admin panel and on the front of the user. It did not. In the new Joomla versions, there are always the same problems with the things that are created as Fields.

Only it is about "Fields" and "field groups" are not working in frontend. I have tried "user" and "content" sections in backend (admin). And then I have checked it frontend and backend, they did not work. Example; I have tried chekcboxes with 3-5 checkboxes, I got only 1 checkbox. Other checboxes are gone in same field. This bug is about functionality I think. Fields are very useful.  Same problem in other Fields' options. 

Fields must check.

**Comment by ggppdk** [comment]
> Only 1 list item is displayed for the list you are creating. 

You have used the same value for all for your options (probably you left it empty)
- besides setting the "text" property (aka label) you need to also set a different "value" property for every option of the list

**Comment by ghost** [comment]
@burgutex Please look in [Documentation](https://docs.joomla.org/Main_Page) or ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.

**Comment by burgutex** [comment]
All of comments are falses. These are not solutions. We are professional for website design and Joomla! using. We tried Fileds with diiferent ways in different platforms. Fields are not working. Joomla! Forum's password protocol is so bad. Website is not accept our passwords and we are forgetting. We don't love forum.

**Comment by ggppdk** [comment]
> Joomla This option does not work when you add a list
> Only 1 list item is displayed for the list you are creating

can you post a picture of the configuration of the fileld of type 'list' ? (the General TAB that has the available options for selection)

**Comment by burgutex** [comment]
Ok. I will try your advices again. I hope I can solve this. System using must be simple. New differences musn't be in radical ways. Thank you.

**Comment by brianteeman** [comment]
Should not have been re-opened simply because lack of knowledge. If further information is provided that shows a bug in the code and not a pebkac issue it can always be reopened
