### ISSUE TITLE
Search with a / in the title. Part 2.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#18432]
### Steps to reproduce the issue
- Current Staging or apply PR https://github.com/joomla/joomla-cms/pull/18221
- Set error reporting in global Joomla configuration: Maximum.
- Go into 5 published articles and add this text somewhere in the article text:

> 1/17

- Save articles.
- Go to frontend and search for

> 1/17

- Any second hit has no title.

- Several times:

> Warning: preg_replace(): Unknown modifier '1' in \components\com_search\views\search\view.html.php on line 271

#### Reason:

See changes in https://github.com/joomla/joomla-cms/pull/18221/files

`$needle = str_replace('/', '\/', $needle);`

The problem is that this line is inside a foreach loop. So $needle becomes:
1. search hit: `1\/17` (OK).
2. search hit: `1\\/17` (PHP-Warning. Empty title.).
3. search hit: `1\\\/17` (Not really OK but no Warning).
4. search hit: `1\\\\/17` (PHP-Warning. Empty title.).
and so on.

![26-10-_2017_22-03-12](https://user-images.githubusercontent.com/20780646/32129784-f2fc9996-bb8b-11e7-94b5-b929f1fb5433.jpg)

**Comment by astridx** [comment]
I tested this and I can confirm this issue.

**Comment by ghost** [comment]
thanks @astridx Status at Issue Tracker is "Confirmed".

**Comment by ghost** [comment]
closed as having Pull Request #18433
