### ISSUE TITLE
[com_fields] Missed custom fields

### ISSUE THREAD

**Issue by OpenICTsy** [joomla/joomla-cms#18439]
### Steps to reproduce the issue
I added for example 6 custom fields and assign them to the same category and put them in the same group.

### Expected result
To find all the assigned custom fields in the article page

### Actual result
 Only 4 will appear in front end and back end in the article page.

### System information (as much as possible)
PHP Built On	Linux uk605.directrouter.com 2.6.32-673.26.1.lve1.4.27.el6.x86_64 #1 SMP Sun May 7 19:22:54 EDT 2017 x86_64
Database Version	10.1.28-MariaDB
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.24
Web Server	LiteSpeed
WebServer to PHP Interface	litespeed
Joomla! Version	Joomla! 3.8.1 Stable [ Amani ] 4-October-2017 14:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

### Additional comments
I  Attached two images to represent this issue
I can offer an admin account to the online web site where the issue appear
Note: I think this issue related to Arabic language

**Comment by ghost** [comment]
@OpenICTsy no Images are attached.

**Comment by OpenICTsy** [comment]
@franz-wohlkoenig 

![cf](https://user-images.githubusercontent.com/32321211/32159508-81aabdbe-bd56-11e7-85c6-7fed0223f9b4.jpg)
![cf-article](https://user-images.githubusercontent.com/32321211/32159509-81dce62c-bd56-11e7-88c0-165b83999d87.jpg)

**Comment by ghost** [comment]
There are 4 Text- and 2 Url-Fields. Which Type are the not show Fields?

**Comment by OpenICTsy** [comment]
Not related to type .. there are the missed fields
![cf](https://user-images.githubusercontent.com/32321211/32160199-55a339fa-bd59-11e7-89b3-78f13377cccc.jpg)

**Comment by brianteeman** [comment]
I think we will need to see screenshots of those two fields individual settings

**Comment by OpenICTsy** [comment]
@brianteeman 
![image](https://user-images.githubusercontent.com/32321211/32160368-20ff70e6-bd5a-11e7-9156-8a918d397f08.png)
![image](https://user-images.githubusercontent.com/32321211/32160392-3e207f8a-bd5a-11e7-8519-1f934ca7e87e.png)
![image](https://user-images.githubusercontent.com/32321211/32160405-4f79564e-bd5a-11e7-89e2-617380cc295f.png)

**Comment by ghost** [comment]
I guess this for [forums](https://forum.joomla.org/), becauset this repository concerns in first Place Joomla coding.

**Comment by OpenICTsy** [comment]
I think it's code related. I have changed the the name of two missed fields from Arabic to English and they appeared.

**Comment by coolcat-creations** [comment]
If you add 
`    <pre>
       <?php
       print_r($this->item->jcfields);
       ?>
       </pre>`
in your article view override, what is the output? Are all fields listed there?

**Comment by brianteeman** [comment]
It has been one month since the request for further information without reply. I am closing this at this time. It can always be reopened if further information is provided
