### ISSUE TITLE
XML config without params is not working but no warning or error.

### ISSUE THREAD

**Issue by studio42** [joomla/joomla-cms#18430]
If you forgot to add  name="params"  in an module XML config, value are not saved, but you have no warning, or errors.
### Steps to reproduce the issue
replace
```
    <config>
	<fields name="params">
```
with
```
    <config>
	<fields>
```

### Expected result
Save values or display an error "fields name is mandatory in XML file." 

### Actual result
Display fine, but not save the values

### System information (as much as possible)
Joomla 3.8.1

### Additional comments
I know it's not a real issue, but i searched 10 minutes only because this, so  i think it help other devs too if you find a trick.

**Comment by ghost** [comment]
Any Comment on this Feature Request?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18430">issues.joomla.org/tracker/joomla-cms/18430</a>.</sub>

**Comment by ReLater** [comment]
I don't think that it's a Joomla job to report any coding error THAT PERHAPS isn't a coding error (and that's the crux).

**Comment by ghost** [comment]
thanks @ReLater, closing Issue. Please reopen if i'm wrong.
