### ISSUE TITLE
Content filter doesn't allow to search for articles with "no user" set as author.

### ISSUE THREAD

**Issue by JurgenG** [joomla/joomla-cms#18434]
### Steps to reproduce the issue
1. Create an article and set the author to "no user" (button)
2. Save and close the article.
3. Open the search tools
4. Go to "- select author -"

### Expected result
5. Select "no user" at the beginning or end of the list

### Actual result
5. No easy way to find articles without assigned user

**Comment by brianteeman** [comment]
There shouldn't be any articles existing without an author

**Comment by JurgenG** [comment]
Hi Brian,

that's a pretty bold statement, considering there's even a button "no author" when you go out to select the author of an article...

Anyways, I consider it a feature to be able to set certain content as "no author" - this allows for cleaner user profiles, especially if you have a content-oriented site. (yes, I know... there are work-arounds. I could create a user called "No User" or "Brian Teeman") ;) Technically you could see the "no author" as a default present author with ID 0 (or NULL).

A different case where I use this, is where authors disappear but they allow for their content to stay. I assign "no author" but put the author name as an alias on the article.

I understand it's kind of a dogma that a piece of text should never be orphaned from its author. But what do you then do with HTML modules? Sometimes these contain more content than the articles... or articles just consisting of loadmodules... 

Love it or hate it... fact is that it's in Joomla for the moment. If we have it, we should (be able to) use it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18434">issues.joomla.org/tracker/joomla-cms/18434</a>.</sub>

**Comment by JurgenG** [comment]
Sorry, didn't press "upload" when attaching the image...!
[screen shot 2017-10-28 at 22 08 44](https://issues.joomla.org/uploads/1/605eef7f72f281598f18c668ca4e52e9.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18434">issues.joomla.org/tracker/joomla-cms/18434</a>.</sub>

**Comment by infograf768** [comment]
On it and discovered also a bug in the featured articles page. PR coming.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/18440
Closing as we have a patch
