### ISSUE TITLE
PHP 7.2 Compat Issue - Count on non-Countable object in SchemaItem

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#18437]
### Steps to reproduce the issue

Using PHP 7.2, navigate to `/administrator/index.php?option=com_installer&view=database`

### Expected result

Page renders without error

### Actual result

`Warning: count(): Parameter must be an array or an object that implements Countable in /libraries/src/Schema/ChangeItem.php on line 211`

### System information (as much as possible)

3.8.2-dev (commit 91dcb797080468fb16fa32872d36e731dbff5144), PHP 7.2 RC 5

**Comment by ghost** [comment]
@mbabker #18438 is the PR for this Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18437">issues.joomla.org/tracker/joomla-cms/18437</a>.</sub>

**Comment by wojsmol** [comment]
@franz-wohlkoenig https://github.com/joomla/joomla-cms/pull/18438 is for the same issue but does not include this part of the code.

**Comment by alikon** [comment]
https://github.com/joomla/joomla-cms/blob/c343565619b7e966caff5b202f6c6dced1f0cec7/libraries/src/Schema/ChangeItem.php#L199
`loadObject()` returns an object
we should use  instaed `loadRowList()`  wich returns an array
see #18443

**Comment by ghost** [comment]
closed as having Pull Request #18443
