### ISSUE TITLE
Bug: Frontend. When inserting article via the article xtd button, the Authors filter is broken

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#18442]
### Steps to reproduce the issue
Edit an article in frontend. Use the Article xtd button in editor to insert an article.
Search by Author in the modal.
### Expected result
Filter works.

### Actual result
We get a 500
```
500 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND a.created_by = 789 GROUP BY a.id, l.title, l.image, uc.name, ag.title, c.tit' at line 12 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND a.created_by = 789 GROUP BY a.id, l.title, l.image, uc.name, ag.title, c.tit' at line 12 
```
and PHP Warning in php logs
```
[30-Oct-2017 09:37:50 Europe/Berlin] PHP Warning:  array_keys() expects parameter 1 to be array, boolean given in /Applications/MAMP/htdocs/testnew/trunkgitnew/administrator/components/com_content/models/articles.php on line 426
[30-Oct-2017 09:37:50 Europe/Berlin] PHP Warning:  Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/testnew/trunkgitnew/administrator/components/com_content/models/articles.php on line 426
```
### Additional comments
Not nice. 😢

**Comment by brianteeman** [comment]
confirmed

**Comment by infograf768** [comment]
I think I found the solution.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/18445
Closing issue as we have a patch

**Comment by parzych24** [comment]
Witam 
Mam pytanie i jeżeli ktoś się spotkał z takim problemem proszę o info. 

Po aktualizacji (chyba bo na to wygląda) systemu joomla do wersji 3.8.2 system w panelu administratora w opcji wyszukiwania artykułów wyrzuca bład 500. Problem pojawia się podczas wpisania w wyszukiwarce art. nazwy i kliknięcia ENTER (info w załącznikach). Hosting mam na HOME.pl - administratorzy w home.pl po sprawdzeniu stwierdzili że po ich stronie jest wszystko OK (PHP 5.6). 

KOMUNIKAT BŁĘDU: po wpisaniu w wyszukiwarce "MOWE":

****You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND (a.title LIKE '%MOWE%' OR a.alias LIKE '%MOWE%') ORDER BY a.id desc LIMIT 20' at line 10 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND (a.title LIKE '%MOWE%' OR a.alias LIKE '%MOWE%')' at line 9****![screen shot 2017-11-30 at 14 01 05](https://issues.joomla.org/uploads/1/c08a14b444d1fc36d9133f89032fe5c5.png)

Proszę o info czym może być to spowodowane i jak to rozwiązać prawidłowo.![screen shot 2017-11-30 at 14 01 05](https://issues.joomla.org/uploads/1/3e4f49ae8661a04b0f6dbf0ff91db3aa.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18442">issues.joomla.org/tracker/joomla-cms/18442</a>.</sub>

**Comment by ghost** [comment]
@ parzych24 please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding.
