### ISSUE TITLE
Add an option for GROUP BY TAGS in articles category  module

### ISSUE THREAD

**Issue by rytechsites** [joomla/joomla-cms#18458]
### Steps to reproduce the issue
Modules: Articles - Category

Currently has the option to GROUP by CATEGORY

What can we do to create a module similar to this (either the same module or a new core module) to include GROUP BY TAGS.

It is understood that if an article exists with multiple tags it will display twice, which it should.

This would give the 100% functionality needed once tags were added.

Here is a sample listing...but I had to do this using multiple modules to list the items...
http://italian.rutgers.edu/academics/undergraduate/courses/course-descriptions
thanks,
Laura

**Comment by ghost** [comment]
Any Comment on this Feature Request?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18458">issues.joomla.org/tracker/joomla-cms/18458</a>.</sub>

**Comment by SharkyKZ** [comment]
How should untagged items be handled? I see 3 options:
a) Loaded but not displayed (screws with 'Count' option as the number of unique articles ends up being lower).
b) Not loaded and not displayed.
c) Loaded and displayed under 'Untagged' or 'Uncategorised' pseudo-tag. I think this is the best option but it could be misleading in case such tag is actually used on the site as the articles wouldn't be found under it.

**Comment by ghost** [comment]
closed as having Pull Request #20248.
