### ISSUE TITLE
Font in Navbar-Section (Backend) blurry.

### ISSUE THREAD

**Issue by CeleritasCognito** [joomla/joomla-cms#18454]
I use a MacBook Pro 13 (2017) and the Text on the Navbar in the Backend is not sharp, it looks blurry. Is it possible to get this Fixed? I think that this issue is caused by Font-Antialiasing.

Safari Version 11.0 (13604.1.38.1.6)
MacOS 10.13

**Comment by C-Lodder** [comment]
screenshot?

**Comment by brianteeman** [comment]
Perhaps related #5898

**Comment by C-Lodder** [comment]
`-webkit-font-smoothing: antialiased;` will always make fonts look lighter on a darker background for Mac, so try disabling it via the inspector

**Comment by CeleritasCognito** [comment]
@C-Lodder It is not lighter, it is Blurry. We use `-webkit-font-smoothing: antialiased;` on our own Website and it looks much much clearer. (Open Sans Font)
I disabled it and it looks sharper, but much uglier because it is bolder.

Here is a Screenshot:
<img width="676" alt="bildschirmfoto 2017-10-31 um 11 18 12" src="https://user-images.githubusercontent.com/18743976/32219593-f61f7724-be2e-11e7-9dd2-52c0b05c2158.png">


@brianteeman Yes, this could be related.

**Comment by coolcat-creations** [comment]
I don't see that it's blurry? Does this look more sharp to you?

<img width="627" alt="grafik" src="https://user-images.githubusercontent.com/828371/32219858-e3c64638-be2f-11e7-8155-c3c749e7f096.png">
I changed the Font Color to white here.

Original:
<img width="702" alt="grafik" src="https://user-images.githubusercontent.com/828371/32219926-1a60eeb4-be30-11e7-9d64-9599fb029338.png">


But i see also that your Navbar color is completely different. Do you use the core Template with core settings?

**Comment by CeleritasCognito** [comment]
@coolcat-creations It looks sharper :) Yes, I use the core Template, just with different Colors.
![settings](https://user-images.githubusercontent.com/18743976/32220103-bfe8898c-be30-11e7-86b9-0edb121319dd.PNG)

**Comment by coolcat-creations** [comment]
@YoKoGFX Joomla can't control your own settings ;)
There is probably an accessibility reason not to have it in pure white ... i'm not sure about that. I can change it if there are some votes for it.

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 26th January 2018.

**Comment by C-Lodder** [comment]
@dgt41 @wilsonge @philtaylor you guys use a MAC. Do you have the same issue?

**Comment by ghost** [comment]
Didn't look blurry on

- macOS Sierra, 10.12.6
- Safari 11.0.2; Firefox 57 (64-bit)

**Comment by CeleritasCognito** [comment]
I can confirm, it doesn't look blurry on my MacBook.

- macOS High Sierra 10.13.2
- Safari 11.0.2

Looks like it somehow fixed itself.

**Comment by ghost** [comment]
@YoKoGFX can you please close the issue?
