### ISSUE TITLE
menu filter php error

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#18468]
### Steps to reproduce the issue
enable full php error reporting
set the search tools filters as shown in the image below
`Warning: str_repeat(): Second argument has to be greater than or equal to 0 in C:\Apache24\htdocs\cms\administrator\components\com_menus\models\fields\menuitembytype.php on line 250
`

<img width="1090" alt="screenshotr22-24-10" src="https://user-images.githubusercontent.com/1296369/32300906-9027110e-bf53-11e7-8e0d-d190a32ba3ac.png">

**Comment by ghost** [comment]
closed as having Pull Request #18471
