### ISSUE TITLE
Calendar pop-up is hidden under menu

### ISSUE THREAD

**Issue by 80sPop** [joomla/joomla-cms#18469]
### Steps to reproduce the issue

click on calendar icon

### Expected result

full calendar pop-up display

### Actual result

calendar displays above input field, and is cut off by website's menu.

### System information (as much as possible)

Firefox 56.0, Joomla 3.8.1

**Comment by ghost** [comment]
can you please post a Screenshot?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18469">issues.joomla.org/tracker/joomla-cms/18469</a>.</sub>

**Comment by 80sPop** [comment]
![screen shot 2017-11-02 at 11 10 53](https://issues.joomla.org/uploads/1/2af43d639e0f83ce36c3c0616d527b73.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18469">issues.joomla.org/tracker/joomla-cms/18469</a>.</sub>

**Comment by ghost** [comment]
Can you please use Core-Template using Protostar if it depends on Template?

**Comment by 80sPop** [comment]
Thanks Franz, I'll try later tonight and post results.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18469">issues.joomla.org/tracker/joomla-cms/18469</a>.</sub>

**Comment by ciar4n** [comment]
This looks like a z-index issue with your template

**Comment by 80sPop** [comment]
The website was designed with the Gantry Template Framework, so changing to Protostar renders a page without any content. I'll try installing updates to the template and see what happens.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18469">issues.joomla.org/tracker/joomla-cms/18469</a>.</sub>

**Comment by tonypartridge** [comment]
@dgt41 thoughts on increasing our z-indexing for the calendar? It should trump everything on screen really ;-)

**Comment by brianteeman** [comment]
its either the template or the calendar causing this issue (which is a z-index problem)  there is nothing that can be done with the core of joomla to fix a problem like this

**Comment by tonypartridge** [comment]
The calendar is by Joomla! we will be loading in styling so if we set a high z-index for the pop-up calendar we can solve the problem from occurring in the core. Whilst I agree it can be fixed by the template, we can also improve to avoid these issues.

**Comment by brianteeman** [comment]
sorry i assumed the calendar was an addon

**Comment by tonypartridge** [comment]
😀 I suppose it could be, but it looks like our native date picker.

**Comment by ciar4n** [comment]
Unfortunately we can not simply increase the z-index of the calendar. It all depends on the z-index of its container which is within the realm of the template. To be fair it is not an easy fix for the template as a template header will often have a higher z-index than the remaining content. Otherwise the menu dropdowns in the header can appear behind said remaining content.

@dgt41 This may be a further reason to disable that flipping of the calendar from bottom to top if the calendar is located near the base of the viewport.

**Comment by 80sPop** [comment]
Is there any way to force the calendar to display below the input field?

**Comment by dgrammatiko** [comment]
Ok, so here's the problem we have and kinda egg-chicken situation:
- The calendar field should **always** display the input for manual insertion of the date
- The calendar (since the position is absolute) needs to either display on the top or bottom according to the position on the field in the document

Those 2 requirements eventually could get a page were either the top or bottom position is not an option! We've discussed with @ciar4n the option to make this a relative position and have it always display under the input, but I cannot recall why we never actually did it (probably there's a reason that I forget right now)

**Comment by ciar4n** [comment]
@videoCodec To force the calendar to display below the field try adding the following to your template CSS...

``` css
.js-calendar {
    margin-top: 0 !important;
}
```

@dgt41 Can't remember for sure but I think the reason against a relative position was the effect it would have on the remaining content of the page.

**Comment by dgrammatiko** [comment]
> the effect it would have on the remaining content of the page

True, everything will be pushed down

**Comment by 80sPop** [comment]
Thanks!

both z-index and calendar position issues were fixed with the following js override:
.js-calendar { z-index: 100000 !important; margin-top: 0 !important; }

However, since 3.8.2 upgrade, the calendar object is gone. Before upgrade, I had the following js:
if (calendar.dateClicked == true) /* do something

Does anyone know the new object containing the dateClicked element?




 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18469">issues.joomla.org/tracker/joomla-cms/18469</a>.</sub>

**Comment by Quy** [comment]
@videoCodec If you don't get an answer, you may want to post your question to Joomla! forum: https://forum.joomla.org/

**Comment by Quy** [comment]
This can be closed as the initial issue has been resolved and the followup issue is [here](https://github.com/joomla/joomla-cms/issues/18978).

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18469">issues.joomla.org/tracker/joomla-cms/18469</a>.</sub>
