### ISSUE TITLE
[improvement] - Add ACL to single Plugin

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#18462]
### Steps to reproduce the issue
Unlike Modules/Articles you aren't able to set ACL for a single plugin but you can set only for ALL plugins

**example: single module ACL**
![screenshot from 2017-11-01 09-39-43](https://user-images.githubusercontent.com/181681/32266757-e471a6fe-bee8-11e7-98a3-03d46da610ab.png)

**example: ALL plugins ACL**
![screenshot from 2017-11-01 09-44-01](https://user-images.githubusercontent.com/181681/32266855-5b25181c-bee9-11e7-8494-e9ffcce360ca.png)

### Expected result
You are able to set ACL specific to a single plugin

### Actual result
You are not able to set ACL specific to a single plugin

### Additional comments
see discussion #18435

**Comment by infograf768** [comment]
I do agree that is a missing feature

**Comment by Bakual** [comment]
Given how plugins work, wouldn't that be something that should be implemented in the plugin itself? Eg like already done in the debug plugin?

**Comment by infograf768** [comment]
@Bakual 
Not sure I understand.
We are speaking here of the simple editing/modifying of a specific plugin's params in back-end.
I.e. for example: only Super Users and not Administrators would be able to modify the authentification plugins.

**Comment by Bakual** [comment]
Ah, misunderstood then indeed.

**Comment by wilsonge** [comment]
I'm going to close this in favour of the discussion going on in #20256
