### ISSUE TITLE
Css reflecting problem

### ISSUE THREAD

**Issue by enrolmentdesk** [joomla/joomla-cms#18460]
Recently i upgrade joomla 3.5 to 3.8.1 once upgrade

i am trying to css in templates after changes not reflect the front-end

i remove cache and browser cache etc..  but not working 

please give suggestion any one asap

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
