### ISSUE TITLE
PHP Warning:  Parameter 1 to PlgSystemLogout::handleError() expected to be a reference, value given in /libraries/legacy/error/error.php on line 780

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#18476]
### Steps to reproduce the issue
Log in frontend ( I did as superadmin).
Login form module is set to display on all pages.
Edit an article.
Logout through the module

You get that Warning. Logout is done OK

Note: test done on a clean staging multilingual site

**Comment by ghost** [comment]
Can't confirm. Logout by Module (display on all Pages) give:
![bildschirmfoto 2017-11-02 um 10 47 30](https://user-images.githubusercontent.com/8235763/32319553-44a946bc-bfbb-11e7-8407-635720e37621.jpg)

**Comment by infograf768** [comment]
You get that, but the Warning shows in the PHP error logs, not on the page.

**Comment by ghost** [comment]
Had looked before Comment in php_error.log, didn't get it there too.

**Comment by infograf768** [comment]
weird

**Comment by Quy** [comment]
@infograf768 I can reproduce the warning in the error log.

**Comment by infograf768** [comment]
@Quy @franz-wohlkoenig 
I see that Franz did his test while using a test sample data while I just had used the default multilang setting when installing J.
Quy, what your were your settings?

**Comment by Quy** [comment]
Installed Test English (GB) Sample Data demo.
Edit an article in the front end.
Click the Log out button.
View error log.

**Comment by infograf768** [comment]
Thanks for info.

**Comment by ghost** [comment]
Test again on clean Install: No Warning in php_error.log.
### System information
 3.8.4-dev
Multilanguage Site (4 Lang.) & Test English (GB) Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by infograf768** [comment]
@franz-wohlkoenig 
Have you tested when the article is in the edit state, i.e. not saved yet?

**Comment by ghost** [comment]
2 Versions:

- Open Article, change something, click on Log-out-Button of Module (there comes PopUp "Do you really wanna leave Page")
- Open Article and click on Log-out-Button of Module

In both Cases no Warning.

**Comment by infograf768** [comment]
I think I found why we have that.
the method is
`public static function handleError(&$error)` in `/plugins/system/logout/logout.php`
If I change to `public static function handleError($error)`
No more Warning
It may be related to the PHP version as using the reference is there for compatibility with php 5.3
What is weird is that @franz-wohlkoenig does not get the issue although he uses a 7.x php version.
Maybe it is related to his 7.0.22 bersion?
My version of PHP is 7.1.8

**Comment by infograf768** [comment]
I confirm:  using php 7.0.22 does NOT throw the warning

**Comment by ghost** [comment]
@infograf768 confirm: got Error after changing PHP-Version to 7.1.8 in Mamp.

**Comment by infograf768** [comment]
@Quy 
What is your PHP version?

**Comment by Quy** [comment]
PHP 7.1.11  & PHP 7.2.0

**Comment by Quy** [comment]
Maybe this will give some insights: https://forum.joomla.org/viewtopic.php?t=930067

**Comment by ghost** [comment]
closed as having Pull Request #19233
