### ISSUE TITLE
Обновление 3.8.1 не устанавливается

### ISSUE THREAD

**Issue by EvgeniiKo** [joomla/joomla-cms#18479]
Ошибка
Обнаружена ошибка.
0 error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

**Comment by EvgeniiKo** [comment]
Помогите! Help!

**Comment by infograf768** [comment]
please use english

**Comment by brianteeman** [comment]
I am guessing that you are trying to update Joomla but you cannot do that because of this error. This error is caused because the server at AWS that has the download is being blocked in Russia. You can download from the unofficial mirror at mirror.myjoomla.io

**Comment by EvgeniiKo** [comment]
Correctly! The problem is solved! Updated the site manually. Thanks to all!
