### ISSUE TITLE
Joomla\CMS\Cache\Storage\FileStorage::_deleteFolder JFolder: :delete:

### ISSUE THREAD

**Issue by landed1** [joomla/joomla-cms#18477]
### Steps to reproduce the issue

Just loading any page shows a warning box, using any template

### Expected result

No warning box

### Actual result

Get a warning box with this error
Warning

Joomla\CMS\Cache\Storage\FileStorage::_deleteFolder JFolder: :delete: Could not delete folder. Path: /var/sites/b/bestantigua.com/public_html/cache/com_content

### System information (as much as possible)

php7, using memcache I believe but since there are no controls for memcache think the server must write the memcache settings itself in config?

**Comment by csthomas** [comment]
It would be good to know what version do you have.

Usual memcache is not supported by php7 and Joomla tried to use file cache. 
As you have `cache` folder without write access you get php warning.

Eventually you can check https://github.com/joomla/joomla-cms/pull/17671

**Comment by landed1** [comment]
Version 3.8.1 
How is my configuration getting written to with the memcache settings? This seems some dark area of Joomla. I really appreciate your reply by the way, I am using 3.8.1

My hosts are trying to debug the issue as I have other sites on same version without issue- so I was trying to compare the config..there appears to be no problem with the file folder ownership..hence why #17671 is not affected.

If memcache is not supported by php7 then I should be able to delete the memcache config lines? Just as a guess.

**Comment by csthomas** [comment]
I suppose you had memcache configured on php5. 
After you changed to php7 Joomla could not use memcache API because php7 does not have it.

You have a problem with access to `cache/com_content`.
You should be able delete such folder (com_content) by ftp.

You can not change it to other cache option like "File, Memcached, Redis" because Joomla has a bug  as I explained in #17671 

To describe the problem I'm using "file cache" but you start from unavailable "memcache" handler.

What I suggest?
1. Delete folder (com_content)
2. Apply my PR
3. Change cache handler.

**Comment by landed1** [comment]
Thanks again- not sure how I would do step 2. I am happy to change code. I just did step 1 which joomla has always been able to delete from the admin side anyway in clear cache...
step 3 only file is possible as far as I see no other options available. Will check my config to see if that has a legacy pointer...Thanks

**Comment by ghost** [comment]
Closed as this repository concerns in first Place Joomla coding.

**Comment by landed1** [comment]
Awesome- why people go to wordpress.

**Comment by mbabker** [comment]
The WordPress folks also point users over to their forums when items which turn out to be site specific support requests are opened on the issue tracker (which, as pointed out, is for tracking and resolving of core bugs).  Nothing out of the ordinary happening here.

**Comment by landed1** [comment]
You guys work hard on Joomla and I have used it happily for many years but this prevalent of code above all else got a few comments in the forum when sites got taken down by a code update which you defended at the time {https://forum.joomla.org/viewtopic.php?f=710&t=937036} but I pointed out that the code was not defensive. Thats the key point I think, wordpress are eager to please and their site is so much easier to manage from a webmasters viewpoint. If you want to fix the bigger picture then perhaps being a bit more human and less compiler will help it. I will be very sad to see Joomla keep loosing out and I hope the culture can return to better UX from webmasters point of view.
