### ISSUE TITLE
[4.0] Installation error page needs some work

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#18487]
### Steps to reproduce the issue
Easiest way to show this page is to run the installer and then delete your database (but not configuration.php file).

@ciar4n maybe one for you?

**Comment by ciar4n** [comment]
Sure. I'll have a look at it over the weekend.

**Comment by ciar4n** [comment]
PR created... #18493

**Comment by ghost** [comment]
closed as having Pull Request #18493.
