### ISSUE TITLE
Undefined variable: langCode in getCurrentLanguage

### ISSUE THREAD

**Issue by obuisard** [joomla/joomla-cms#18484]
### Steps to reproduce the issue

Call from an extension to JHelperContent::getCurrentLanguage()

### Expected result

Should return the language code.

### Actual result

Undefined variable: langCode in getCurrentLanguage

There is a test on langCode but that variable is not set if the site is not multi-lingual.

### System information (as much as possible)

since Joomla 3.7 apparently.

### Additional comments

The function should be able to be called without assuming the site is multi-lingual.

**Comment by infograf768** [comment]
Closing as we have a patch #18485
