### ISSUE TITLE
Joomla website does not appear in Chrome, Edge, or Firefox browsers

### ISSUE THREAD

**Issue by Norwalk1776** [joomla/joomla-cms#18488]
### System information (as much as possible)
I cannot provide specific information on Joomla since I cannot open the website. I put 3.8.1 in the Build field only to get the form submitted.  The actual build may be different.  Again, the site has worked without issue for a least year and has only started this issue in the last few weeks.

My ASUS laptop uses a WIN10 OS, 64-bit, x64-based processor. It has an Intel(R) Core(TM) i7-7500U CPU @ 2.70 GHz 2.90 GHz.  The Win10 OS is version 1703 and OS Build 15063.674. It has Trend Micro Internet Security software. It has a NVIDIA GPU with Control Panel version 8.1.1030.0

**Comment by brianteeman** [comment]
This is not the correct place to seek support. Please use the forum at https://forum.joomla.org
