### ISSUE TITLE
Forcing https gives FOF30 error

### ISSUE THREAD

**Issue by WimVDK** [joomla/joomla-cms#18498]
### Steps to reproduce the issue
1. Go to global config > Server
2. Force HTTPS > select either value
3. Click save

Below error appears
-----
An error occured

    0 Class 'FOF30\Utils\TimezoneWrangler' not found 
------

both options (administrator only or both) give the same result

### Expected result

HTTPS forced and site defaults to https instead of http so manual navigating is not needed

### Actual result

HTTPS not forced

### Host specifications

DA 2.51 with SSL by let's encrypt
Domain has SSL enabled and active valid certificate (checked online)
Manually navigating to https://<insert url>(/administrator) gives proper green lock
Joomla version: 3.8.1

Forcing https in global configuration gives error

An error occured

    0 Class 'FOF30\Utils\TimezoneWrangler' not found 

### Additional comments

SU access can be given to trustworthy tester for verification

**Comment by zero-24** [comment]
@WimVDK Generally there is no FOF30 in the core (just 2.5.5). It looks like there is some 3rd party extension using FOF30 that is broken.

Please check all 3rd Party extensions by disable them one by one (also plugins).

For more help please contact the original developer or the forum.

As this does not look like a Core Problem as there is no FOF30 in the core I'm closing this. Thanks
