### ISSUE TITLE
Plugin Redirect: Sort of excluded URLs don't work

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#18500]
### Steps to reproduce the issue

- Open "System - Redirect"
- add 3 URLs for Exclude
- try to sort by left-side Button of URL-Field

URL moves back to Place it was before.

### System information
3.8.2-rc
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 56 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by Quy** [comment]
It is working for me. Can you provide a video to see how you did it?

**Comment by ghost** [comment]
now its working. Thanks for Check.
