### ISSUE TITLE
mootools-more.js conflit with jquery range slider

### ISSUE THREAD

**Issue by alagesanbe08** [joomla/joomla-cms#18507]
### Steps to reproduce the issue
1. Just add JHTML::_('behavior.modal', 'a.modal'); 
it will load modal and mootool js in page.

2. if page contain jquery range slider, it will auto hide when slide

### System information
PHP Built On: Linux joomlatools 4.2.0-27-generic 32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 
Database Version: 5.5.47-0ubuntu0.14.04.1 
Database Collation: utf8_general_ci 
PHP Version: 7.1.2 
Web Server: Apache/2.4.18 (Ubuntu) 
Joomla! Version: Joomla! 3.8.1 Stable
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by ghost** [comment]
Please give also System informations.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18507">issues.joomla.org/tracker/joomla-cms/18507</a>.</sub>

**Comment by C-Lodder** [comment]
Ther's no such thing as a jQuery range slider...

Are you referring to jQuery UI or one from a 3rd part jQuery plugin?

Or are you getting muddled up with a HTML5 range input?

**Comment by alagesanbe08** [comment]
jQuery UI range slider https://jqueryui.com/slider/#range

**Comment by brianteeman** [comment]
Sorry but there is nothing that we can do in the core of joomla to make an external script work. There may be methods you can use that you can ask about on the forum but this is not the place
