### ISSUE TITLE
Invalid URL generated when using MenuType CategoryList

### ISSUE THREAD

**Issue by valica** [joomla/joomla-cms#18502]
### Steps to reproduce the issue
I created a menu item of type CategoryList pointing to a category which has several articles.
When going to the frontend, I saw the URL associated to the articles in the category list have the pattern:

https://<mysite>/index.php/testing-menu/12-stereo-madness

and when clicking on it, ther is a problem because the page is incorrectly rendered. After a quick look, it is clear that something went wrong and the page source showed the problem:

Some of the resources are incorrectly referenced (as URL):

<link href="/testing-menu/templates/protostar/css/template.css?7e94126c9aede281272b446c981f2bde" rel="stylesheet" />

In this example, templates is the Joomla temaplate folder which is directly at the root level of the joomla website. We see here the "testing-menu" which is put before templates

I have a "Main Menu" which contains a couple of menu items. One of them is the one having the alias "testing-menu" and it has the type Article >> CategoryList.
The articles in that category are showed as links and looking to those generated URLs I see this kind of pattern:

https://<my-site>/index.php/testing-menu/12-stereo-madness

This would have been OK but the problem is the rendering of the page. I don't know why Joomla resolves incorrectly that URL by looking for the main protostar css into a folder called "testing-menu".

<link href="/testing-menu/templates/protostar/css/template.css?7e94126c9aede281272b446c981f2bde" rel="stylesheet" />

I saw that the default menu item is OK. I tried to change the default on a different one and the previous defult became incorrectly rendered also.

I found also this topic which tells:
I am assuming your blog section doesn't have a menu item which is usually the reason for the category and article ID to appear in the url.

https://forum.joomla.org/viewtopic.php?t=941656

I tested by creating a menu item of type Single Article. Looking back to the generated URL for the article in the CategoryList, it bocame

https:/<my-site>/index.php/10-faire-un-portail-du-nether

and it was correctly sourced in css and other resources.

So at present I see the following:
1. If no SingleArticle menu item exists, then the category and the article id are part of the URL. This leads to an incorrect resrouces links generation. -> Seems to be a Joomla bug.
2. Adding a menu item of type SingleArticle, the alias created with the menu item is automatically used in the point 1. and it leads to a correct page output.

### Expected result

Clicking on the articles URLs generated by CategoryList menutype leads to article correctly displayed.

### Actual result
The layout is incorrect. The cause is the bad link genaerated for the protostar template css (see steps to reproduce).

### System information (as much as possible)

Joomle 3.8.1 (and before the very last update).

### Additional comments
There could be a workaround as described in the final part of the steps to reproduce.

**Comment by brianteeman** [comment]
sorry  i have read this three times now and i still dont understand what your rpoblem is

**Comment by valica** [comment]
The problem is related to the menutype CategoryList which creates links leading to a bad article output. My first analysis showed the problem is coming from the wrond link generated for template css.

I think it's easy to reproduce starting with an empty joomla site. Attention point: the default menu item is OK, so please test with a second menu item.

Please let me know if I can help.

Regards,
valica
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18502">issues.joomla.org/tracker/joomla-cms/18502</a>.</sub>

**Comment by ghost** [comment]
i don't get what is meant. Can you provide Screenshots or a Video showing the Issue?

**Comment by valica** [comment]
I can give you the real website link.
**EDIT BY MAINTAINER: deleted site url**
Have a look to the last menu item called "Testing menu". For the one in the middle, I'eve applied the workaround by creating a menu item SingleArticle for each of them. So only the "TEsting menu" shows the real problem.

Please let me know is I should remove the website of my son from the post once you've seen it.

Kind regards,

valica<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18502">issues.joomla.org/tracker/joomla-cms/18502</a>.</sub>

**Comment by ghost** [comment]
Got it, thanks, but can't confirm Issue. All works as expected on a clean Installation.

So this looks not like a Core-Issue - please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
