### ISSUE TITLE
Contact options ignored, only global configuration used on com_contact

### ISSUE THREAD

**Issue by irbian** [joomla/joomla-cms#18515]
### Steps to reproduce the issue
Create a contact with layout "plain". Be sure that the global configuration is set as "sliders". 

### Expected result
The contact form will appear as "plain"

### Actual result
The contact form appear as "sliders"

### System information (as much as possible)
Joomla 3.8.1

**Comment by ghost** [comment]
closed as duplicate Report (searching for # of 1st Report).

**Comment by irbian** [comment]
Would you mind to link the original issue? would like to take a look, I can´t find it

**Comment by ghost** [comment]
I'm searching as i remember this Issue a while ago. Can't find it by kow, so i reopen and search on.

**Comment by ghost** [comment]
Found it: #[18423](https://github.com/joomla/joomla-cms/issues/18423#issuecomment-340183488) - i asked you to open a new Issue *g

**Comment by ghost** [comment]
Can't confirm on Menu "List Contacts in a Category" and "single Contact".

I guess its similar to #17180? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18515">issues.joomla.org/tracker/joomla-cms/18515</a>.</sub>

**Comment by irbian** [comment]
Yeah, have checked my menu configuration and looks like the same case. Menú options override contact options, and as menu has "Use global" setted, contact options does nothing

Now that is clear how it works, I don´t know if this is the best approach. Basically if I have a global configuration that can be override at menu level or at contact level I would expected that only apply whatever I change purposely.

Anyway, I guess that the change had his motivations behind, as long as is coherent with the rest of the Joomla, it will be ok

**Comment by ghost** [comment]
closing as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18515">issues.joomla.org/tracker/joomla-cms/18515</a>.</sub>
