### ISSUE TITLE
Update Joomla 3.6.5 to 3.8.01 issues with front end styles

### ISSUE THREAD

**Issue by snuff4uk** [joomla/joomla-cms#18512]
Hello, i have a problems with styles in the front page after update joomla.
Styles do not appear on the page.
```
	<link href="/templates/jsn_metro_pro/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon" />
	<link href="/components/com_k2/css/k2.css" rel="stylesheet" type="text/css" />
	<link href="http://sitename/modules/mod_je_slicebox3d/css/slicebox.css" rel="stylesheet" type="text/css" />
	<link href="http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" rel="stylesheet
```
This are all styles i have(

I tried to see styles in class HeadRenderer function fetchHead, but in $document-_stylesheets i did not have template styles too.

Can somebody help me?

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
