### ISSUE TITLE
backend category filtering

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#18511]
Sooo I am using a scenario where we have a primary category for grouping the sub categories. When wanting to filter in the backend for all child items on the parent category I also need to select the sub categories.

To me, this doesn't make sense. Instead it would make more sense to show all items where the parent category is selected. Then should someone need sub category filtering they can select subcategories?

Thoughts?

**Comment by ggppdk** [comment]
Do you speak of J3.8.1 or did you test with staging ?

do you speak of this (max) level filter not working as expected ?

https://github.com/joomla/joomla-cms/pull/18179

**Comment by tonypartridge** [comment]
Yes 3.8.1, max levels is blank so should show all, selecting 9 still doesn't show sub categories.

**Comment by tonypartridge** [comment]
Ok checking your PR should be fixed in 3.8.2 :-)
