### ISSUE TITLE
Module Start Publishing Time

### ISSUE THREAD

**Issue by arbindbhagat** [joomla/joomla-cms#18513]
### Steps to reproduce the issue
Edit a module, and set its Start Publishing date/time to any particular time.

### Expected result
The module should start publishing at the date/time that is set up. And this should be based on the server time set under System >> Global Configuration >> Server.

### Actual result
The module is published according to the UTC time instead.

### System information (as much as possible)
Joomla 3.8.1

### Additional comments
This is making it harder to the automation of the things.

**Comment by mbabker** [comment]
Can you check the PHP configured timezone (should be in system info), your site's default timezone (set in global config), and the timezone preference for the affected user account(s)?

Joomla standardizes storage to UTC and converts to the right timezone based on the active configs.  So it's possible something is set to UTC when you intend for it to be set in a local timezone.

**Comment by arbindbhagat** [comment]
I looked at System Information >> PHP Information, and I see UTC at one place. Attached is the screenshot.

Where is this configured? At Server PHP?

If so, how do I override this per site, since there are several sites on the same server, each from different time-zones?
<img width="1161" alt="001" src="https://user-images.githubusercontent.com/19579469/32448766-1e353768-c310-11e7-82af-8569d2530d0e.png">

**Comment by mbabker** [comment]
That screenshot's your server's default timezone.  It's actually for the best it is set to UTC.

In the Joomla global config there is an option to set the default timezone for the site.  In each user's profile there is also an option to set a timezone for the user account (so this impacts logged in users, the global config is for unauthenticated users or logged in users using the global config).

**Comment by ghost** [comment]
closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18513">issues.joomla.org/tracker/joomla-cms/18513</a>.</sub>

**Comment by arbindbhagat** [comment]
I have set the New York time zone in the global config. However, the public users are still seeing the modules (if a start-publishing date is set) according to the UTC timezone.

Is that a bug? Should Joomla not follow the timezone set in global config? As of now, it is not.
