### ISSUE TITLE
Getting 503 - out of memory error after updating Joomla to 3.8.2

### ISSUE THREAD

**Issue by Gorzin** [joomla/joomla-cms#18539]
### Steps to reproduce the issue

In a module or plugin, any request that is not very small leads to a 503 error.
For example in a sql query, if I set a limit to 200 elements it works, but over I have a 503 error.
Even the "phpinfo();" request leads to the error.

I tried to change the value of the memory available both in the php file or in htaccess.ini
but it has no effect.

### Expected result

Page displayed as before

### Actual result

503: Service Unavailable error

### System information (as much as possible)

I updated Joomla from 3.8.1 to 3.8.2 and the problem appeared

**Comment by tonypartridge** [comment]
This sounds like a hosting error opposed to a system error. 

What do your error_logs say?

**Comment by Gorzin** [comment]
Hello, 

I get the following log messages:

2017-11-13 09:02:18 | Error | 31.164.244.189 | 503 | GET /en/gestion-stock HTTP/1.1
-- | -- | -- | -- | --

2017-11-13 09:02:20 | Error | 31.164.244.189 |   | (104)Connection reset by peer: AH01075: Error dispatching request to :, referer: https://www.xxx/en/admin
-- | -- | -- | -- | --

On my live website, I came back to Joomla 3.8.1 and everything is fine again.

**Comment by Quy** [comment]
There is not enough information to troubleshoot. Please ask your hosting company just in case it is a server issue and/or try upgrading to v3.8.3.

**Comment by ghost** [comment]
closed as no Core-Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18539">issues.joomla.org/tracker/joomla-cms/18539</a>.</sub>
