### ISSUE TITLE
Bad merge line 138? joomla-cms/libraries/cms/html/jquery.php

### ISSUE THREAD

**Issue by MOLEDesign** [joomla/joomla-cms#18530]
### Steps to reproduce the issue
This code has been corrupted by a bad merge maybe?

Line 138 of joomla-cms/libraries/cms/html/jquery.php

**Comment by ghost** [comment]
can you please explain what you mean?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18530">issues.joomla.org/tracker/joomla-cms/18530</a>.</sub>

**Comment by MOLEDesign** [comment]
I needed a snippet of this code as I have a token error on my 3.7 install, the code has gone all screwy at line 138. The code may still function but there is a 

<<<JS

block of badly formatted code

JS

I see things like this appear when my GIT has a conflict.

**Comment by MOLEDesign** [comment]
If this is just an inexperience issue on my part (i.e <<<JS is somehow valid, I appologise

**Comment by brianteeman** [comment]
This is valid code and used in several places

**Comment by MOLEDesign** [comment]
Apologies for wasting your time, never seen it before. I have a problem with csrf on my joomla 3.7.4 which is why I spotted it.  Slinking away now with my tail between my legs

**Comment by ghost** [comment]
@MOLEDesign if this Issue is solved please close it, thanks.

**Comment by brianteeman** [comment]
please upgrade 
lots of fixes since 3.7.4
