### ISSUE TITLE
CONCAT Function used on Unsupported platform - MSSQL 2008R2

### ISSUE THREAD

**Issue by an0ther1** [joomla/joomla-cms#18534]
### Steps to reproduce the issue

The requirements page https://downloads.joomla.org/technical-requirements identifies MSSQL Version 10.50.1600.1 (MSSQL 2008 R2)
When attempting to login to the Administration page using Joomla 3.8.2 & MS SQL 2008 R2 users will receive a message that CONCAT is not a recognised function etc
CONCAT is included in MS SQL should be 11.0 (MS SQL 2012) and later

### Expected result
CONCAT function not used

### Actual result
Message post Administrator area login: CONCAT is not a recognised function

### System information (as much as possible)
Joomla 3.8.2 - New installation
MS SQL 2008R2 (Version: 10.50.6220)
IIS 7.5

**Comment by ghost** [comment]
Related to https://github.com/joomla/joomla-websites/issues/1072

**Comment by csthomas** [comment]
I found two issues.

https://docs.microsoft.com/en-us/sql/t-sql/functions/concat-ws-transact-sql

Supported from SQLSRV 2017:
```bash
components/com_contact/models/category.php:149:          *      . ' CASE WHEN CHAR_LENGTH(a.alias) THEN CONCAT_WS(\':\', a.id, a.alias) ELSE a.id END as slug, '                                                                                                                                                          
components/com_contact/models/category.php:150:          *      . ' CASE WHEN CHAR_LENGTH(c.alias) THEN CONCAT_WS(\':\', c.id, c.alias) ELSE c.id END AS catslug ');
```

Supported from SQLSRV 2012:

```bash
administrator/components/com_menus/presets/modern.xml:209:                      sql_select="a.title, a.menutype, CASE COALESCE(SUM(m.home), 0) WHEN 0 THEN '' WHEN 1 THEN CASE m.language WHEN '*' THEN 'class:icon-home' ELSE CONCAT('image:mod_languages/', l.image, '.gif') END ELSE 'image:mod_languages/icon-16-language.png' END AS icon"
administrator/components/com_menus/presets/joomla.xml:209:                      sql_select="a.title, a.menutype, CASE COALESCE(SUM(m.home), 0) WHEN 0 THEN '' WHEN 1 THEN CASE m.language WHEN '*' THEN 'class:icon-home' ELSE CONCAT('image:mod_languages/', l.image, '.gif') END ELSE 'image:mod_languages/icon-16-language.png' END AS icon"
```

but I do not have idea how to fix queries in above xml files.

**Comment by Mohamed-Retsol** [comment]
Thanks for pinpointing those lines @csthomas

**Comment by jwaisner** [comment]
@an0ther1 Is this still an issue in the latest J3?

**Comment by brianteeman** [comment]
Yes

**Comment by brianteeman** [comment]
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed. 

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
