### ISSUE TITLE
After Update to 3.8.2 some Modules lost in backend, still present in database

### ISSUE THREAD

**Issue by Flocke28** [joomla/joomla-cms#18549]
### Steps to reproduce the issue
after update to 3.8.2 are some modules lost in the backend. but the ids are still present in the database and visible in the frontend.

the modules arent in the trash or hidden. the modules starts now with id 88.. the first id in the database is 2 (a login modul)

how can i fix that?

**Comment by alikon** [comment]
discussion is going on #18542

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18549">issues.joomla.org/tracker/joomla-cms/18549</a>.</sub>
