### ISSUE TITLE
[com_associations] Side by side associated target loading issue

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#18552]
### Steps to reproduce the issue
Create a multilingual site.
Create articles tagged to each content language (quite a few of them)
Associate articles when editing one of them.

Launch com_associations.
Filter by articles and one of the Content languages.
The items already associated show as a grey button.
Click on one of these grey buttons to load the side by side page with the already defined target (tagged to the language of the grey button)

The first time one clicks, the already associated target first appear for a while and then disappear to finally display a blank article.
Close the side by side page and then click again the same grey button.
This time all is fine, the already associated target displays fine.

![com_assoc](https://user-images.githubusercontent.com/869724/32688361-97a6bb04-c6cf-11e7-91e1-85ceb8b1ccf5.gif)

**Comment by ghost** [comment]
Can't confirm.

Set Articles on "German", click at Tab "Associations" on `EN`: Reference- and Target-Window open correct and stay so (waited 5 Minutes).
### System information
3.8.3-dev
Multilanguage Site
macOS Sierra, 10.12.6
Firefox 56 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by infograf768** [comment]
Note:
This issue does not happen on a new install but on an updated multingual site with many items.

**Comment by ghost** [comment]
Got it. Test was an on fresh Installation using Sample Data.

**Comment by ergonom2** [comment]
Have the same issue with an updated Joomla!
DE/EN, 
Language Plugin installed and active
Language Modul active or inactive.

PHP erstellt für | Linux h2141576.stratoserver.net 4.4.96-9.1.x86_64 #1 SMP PREEMPT Fri Nov 3 15:30:39 UTC 2017 x86_64
-- | --
Datenbankversion | **5.5.56-MariaDB**
Datenbankzeichensatz | utf8_general_ci
Datenbankverbindungszeichensatz | utf8mb4_general_ci
PHP-Version | **7.1.11**
Webserver | Apache
PHP-Interface für den Webserver | cgi-fcgi
Joomla!-Version | **Joomla! 3.8.2 Stable** [ Amani ] 7-November-2017 15:00 GMT
Joomla!-Plattform-Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Browsererkennung | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

Do you have any idea to fix this issue?
Thanks in advance!!

**Comment by infograf768** [comment]
I did not get the issue anymore when directly editing the reference item, deleting there the association, saving and then re-associate to the same item it was associated before.
Obviously, when we have a lot of associated items, it's a long work.

**Comment by ergonom2** [comment]
Hi,
after deleting the association and re-associating, i still have the same effect.

Not nice, because its a customers page.
Any other idea, maybe?

**Comment by onefootsimi** [comment]
Hi,
I think i have not exactly the same problem as here mentioned. In my case the site seems to reload all the time automatically. See [video](https://drive.google.com/a/blokk.ch/file/d/1H12_6DBba0LStVBOZlzObGdzLmtMV4R-/view?usp=sharing "Associations Bug")...Can somebody help me? The Joomla 3.8.3 installation is e fresh one.
 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18552">issues.joomla.org/tracker/joomla-cms/18552</a>.</sub>

**Comment by Gaukeleier** [comment]
I have the same problem with the endless reloading like seen in onefootsimi's video :(
These things did not work:
- Deactivate all external plugins (only a few)
- changed the editor
- reinstalled joomla core files

Its also 3.8.3. and a nearly fresh installation (2 weeks ago).
The endless reloading happens when i try to link articels.
With categories it works.

I hope you have ideas to solve that issue. Thanks!

**Comment by Gaukeleier** [comment]
@onefootsimi Ok I've found the solution for the infinite loading. 
- Go to your articles 
- Open the article options
- tab "editing layout"
- check if the first option is activated "show publishing parameters"

After I reactivated it everything works again.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18552">issues.joomla.org/tracker/joomla-cms/18552</a>.</sub>

**Comment by onefootsimi** [comment]
@Gaukeleier works fine! thanks a lot!!!!

**Comment by ghost** [comment]
calling @infograf768 after 25th.

**Comment by brianteeman** [comment]
@infograf768 any update on this or has it been resolved elsewhere?

**Comment by infograf768** [comment]
Not resolved.

**Comment by infograf768** [comment]
@dgt41 
Can you have a look? (Yes, I know, the js is not nice...)

**Comment by infograf768** [comment]
Closing as we have patch https://github.com/joomla/joomla-cms/pull/21176

**Comment by infograf768** [comment]
In fact I reopen as the issue here concerns 3.x and not https://github.com/joomla/joomla-cms/pull/21176

**Comment by ghost** [comment]
closed as having Pull Request #22166
