### ISSUE TITLE
[4.0] New installer does not handle DB error correctly (usability)

### ISSUE THREAD

**Issue by Fedik** [joomla/joomla-cms#18557]
### Steps to reproduce the issue
Try to install 4.0-dev with incorrect DB user/password

### Expected result
You get error message/page with possibility to go back.

### Actual result
You get useless error page (from User point of view) 
You even cannot start over.

To start over you should clear cookies and delete existing configuration.php.
That is bad.

### System information (as much as possible)
php 7.0
Joomla 4.0-dev

**Comment by ghost** [comment]
~~similar to #18557~~<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18557">issues.joomla.org/tracker/joomla-cms/18557</a>.</sub>

**Comment by Fedik** [comment]
@franz-wohlkoenig current issue about DB error handling, 
somehow it similar to #18834 but not the same

#18834 is about "back button" in general, that also should be fixed, of course

**Comment by ghost** [comment]
thanks for Info @Fedik

**Comment by zero-24** [comment]
Also the same as https://github.com/joomla/joomla-cms/issues/18736

@wilsonge wrote:
> We need to figure out how this works now that we have a single page application rather than a multi-page app.

As the message that is throw by the error also just a error message (like the database connection issues) they are failing on normal database connection errors too.

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/pull/18958 functionally fixes the issue (and I'll leave one of the interface people to do a subequent cleanup of the UI)

I'm going to leave this issue open even when my PR gets merged so we also remember to do the UX cleanup :)

**Comment by brianteeman** [comment]
closing - we have other open issues about the installer ux. no need for keeping this one which is unrelated to be open
