### ISSUE TITLE
Website and Admin Page 550 - Unable to handle request/Page isn't working

### ISSUE THREAD

**Issue by globalfairness** [joomla/joomla-cms#18569]
### Steps to reproduce the issue
We logged in to the administrator side of our website and updated extensions, and now we are unable to load both the web page itself and the administrator login. Neither globalfairness.org nor globalfairness.org/administrator work. Please help. No experience coding, etc.

### System information (as much as possible)
Hosted on Bluehost, using Joomla

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
