### ISSUE TITLE
[4.0] New Installer totally broken here

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#18560]
SEE https://github.com/joomla/joomla-cms/pull/17964
URL:
http://localhost:8888/joomla40/installation/index.php?view=setup

Result
![install40](https://user-images.githubusercontent.com/869724/32720255-42ff2542-c863-11e7-9a70-167065dfa34b.gif)

Cookies. sessions, etc. cleaned

**Comment by PhocaCz** [comment]
Hi, confirmed, I get the same results.

**Comment by dgrammatiko** [comment]
@infograf768 @PhocaCz can you try with port 80? Does that work for you?

**Comment by infograf768** [comment]
port 80 => same

**Comment by laoneo** [comment]
Does the workaround in #14956 help?

**Comment by infograf768** [comment]
Can't do vagrant

**Comment by dgrammatiko** [comment]
you don't have to, just change the path for the session folder in the provider

**Comment by laoneo** [comment]
On the line here https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/src/Service/Provider/Session.php#L56 I have to change it always to `$handler = new FilesystemHandler('/tmp');`.

**Comment by dgt41** [comment]
set it to `'/tmp'`

**Comment by wilsonge** [comment]
> On the line here https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/src/Service/Provider/Session.php#L56 I have to change it always to $handler = new FilesystemHandler('/tmp');.

Does your php user not have write access to the session directory created?

**Comment by laoneo** [comment]
It has, but for some reasons it doesn't work in PHP. Just wanted to see if @infograf768 is hit by the same bug.
Pr #16918 solves that bug as it uses the default session provider from core.

**Comment by infograf768** [comment]
Well, it would rather be `$handler = new FilesystemHandler(JPATH_ROOT . '/tmp');`
and, sorry to say, but same issue

**Comment by laoneo** [comment]
I had to choose something outside of the Joomla directory like /tmp. But if it doesn't help, then sorry for the noise.

**Comment by PhocaCz** [comment]
Changing to $handler = new FilesystemHandler('/tmp'); did the trick but then I got

![Imgur](https://i.imgur.com/PfJqbeG.png)

even the installation went successfully :idea: and I can now access both sites (frontend, backend)

Jan

**Comment by wilsonge** [comment]
@PhocaCz had you installed 4.x before the new installer succesfully then? Because we moved to the new session package a while ago - so seems very odd that part would start erroring now.

As for the database issue - I'll take a look into that - it's probably something missing between the Joomla CMS and Framework database package somewhere

**Comment by infograf768** [comment]
> I had to choose something outside of the Joomla directory like /tmp

`/tmp` is not outside the Joomla directory, just oustside the installation directory. Or have I misunderstood something?

**Comment by dgrammatiko** [comment]
@infograf768 I think you need to use the OS tmp directory

**Comment by mbabker** [comment]
Your system's `/tmp` directory, not Joomla's (`/path/to/joomla/tmp`).

**Comment by infograf768** [comment]
No sure what you mean, sorry.
I use MAMP, my test is in a subfolder of MAMP/htdocs/ i.e. htdocs/joomla40/ but it could be in a sub-sub-folder
MAMP `tmp` directory is at the same level as htdocs.

**Comment by mbabker** [comment]
No.  Your Mac has a `/tmp` directory at the same level as your `/Users` directory at the root of your hard drive.  This is the system temp directory.

**Comment by infograf768** [comment]
well, I see indeed a session there if I use '/tmp'
deleted it. Deleted cookies.
Same results

**Comment by dgrammatiko** [comment]
well MAMP's PHP might be using `/Applications/MAMP/tmp/php` instead of OS's `/tmp`

**Comment by infograf768** [comment]
what would then be the code?
I mean after `$handler = new FilesystemHandler(`
taking into account the fact that the joomla folder may be in a sub-sub-sub folder...

**Comment by mbabker** [comment]
To use the system temp directory in PHP you'd call `sys_get_temp_dir()` (may be off by a couple characters), or just hardcode `'/tmp'` for the parameter.  Or pass nothing and the filesystem handler will try to use the configured PHP session path and fall back to the system temp directory.

**Comment by infograf768** [comment]
@mbabker I already tested using the OS directory with
`$handler = new FilesystemHandler('/tmp');` and that did indeed created a session there. It did not work either. See https://github.com/joomla/joomla-cms/issues/18560#issuecomment-343930709
I also tested with no param
same issue
I give up

**Comment by infograf768** [comment]
and `var_dump(sys_get_temp_dir()); ` here gives
`string(48) "/var/folders/n7/b0gjd1nj7n5g6bpht8m798yc0000gp/T" `

**Comment by infograf768** [comment]
@dgt41 
using
`$handler = new FilesystemHandler('/Applications/MAMP/tmp/');`
does save the session there, but same result.

**Comment by dgrammatiko** [comment]
@infograf768 what version of mamp are you using?

**Comment by infograf768** [comment]
@dgt41 
4.2

**Comment by infograf768** [comment]
Updated to 4.2.1 => same issue.

**Comment by laoneo** [comment]
@infograf768 I'm not sure, if you have the same issue as @PhocaCz has.

**Comment by infograf768** [comment]
Me not know...

**Comment by infograf768** [comment]
If I use Safari instead of Firefox, I get
```
 Error
An error has occurred while processing your request.
1045 Access denied for user 'root'@'localhost' (using password: NO)

```
This when changed to 
`$handler = new FilesystemHandler('/tmp');` or still using the sessions folder

**Comment by dgrammatiko** [comment]
IIRC that error comes from multiple instances, eg you might have 2 session files (probably some method is not returning as it should be)

**Comment by dgrammatiko** [comment]
By the way are you testing on the latest 4.0 branch or on the Branch for the installer?

**Comment by infograf768** [comment]
> IIRC that error comes from multiple instances, eg you might have 2 session files (probably some method is not returning as it should be)

Only one session file here

I am testing on latest 4.0 branch

**Comment by infograf768** [comment]
hmm, got it to work at last by using Firefox "View Cookie Information" and deleting the cookie there instead of using Cookies Manager +

Folks, this process is too complex for testers. In J3, things are simple. We just modify the db name or keep the same with the same table prefix, click on delete backup and we are done.

**Comment by brianteeman** [comment]
So the problem you had was that your cookies manager was not deleting the cookie but your browser was?

**Comment by dgrammatiko** [comment]
> Folks, this process is too complex for testers.

Which process are you referring to?

**Comment by infograf768** [comment]
HMM, it DID succeed once but no more.
What I did was:

>So the problem you had was that your cookies manager was not deleting the cookie but your browser was?

Cookies Manager+ is an extension of Firefox. 
Looks like it was not deleting the cookie as it should have although it did show it was deleted OK.

In Safari, we use `Manage Web Site Data` to delete specific cookies (in this case `localhost`) and I still got the `1045 Access denied for user 'root'@'localhost' (using password: NO)`

> Which process are you referring to?

The process of reinstalling j4 when the branch has been updated.

-------------------
NOTE: Something is wrong in the Kingdom of J4 installation

**Comment by dgrammatiko** [comment]
> The process of reinstalling j4 when the branch has been updated.

What do you mean? Did you try to install it again over the old one?

**Comment by infograf768** [comment]
I did not.
What I am saying is that we will have to do it in the future for other tests modifying installation.
In 3.x, it was real easy: delete the configuration.php file and start installing again on the updated J.
Now, although we do have obviously a serious problem to be solved, one would have eventually to delete all cookies (make sure they are and all depends possibly on the browser)+ whatever necessary which I can't imagine.

**Comment by dgrammatiko** [comment]
> although we do have obviously a serious problem to be solved, one would have eventually to delete all cookies (make sure they are and all depends possibly on the browser)+ whatever necessary which I can't imagine

Ok hold on what are those **serious problems** you are talking about here?
And also the cookie thing can be solved pretty easily...

**Comment by laoneo** [comment]
I was installing Joomla many times with the new installer and had never cookie problems.

**Comment by infograf768** [comment]
The serious problem, for now is that I can't install J4 here.

**Comment by PhocaCz** [comment]
> Ok hold on what are those serious problems you are talking about here?

Maybe I can help you to understand the situation. I work with Joomla! more over 10 years. As developer I install Joomla! very often. Because the standard installer is very powerful, simple and fast, I didn't prepare any automatic function to install Joomla! in last 10 years. Just because the manual installation is fast and simple. I installed it more than a thousand times - on different environments with different limits (permissions, ownership, ftp layer, etc. etc.). One could say, I have really strong experiences with installing Joomla!. Now I just want to install Joomla! 4 and I am lost in loop. The question is what standard inexperienced user will do in such situation? Theory and practice consistently says: in such case this user is probably lost regarding using Joomla! This seems like a serious problem. 😕

**Comment by infograf768** [comment]
After the last Firefox update (57.0 Quantum, available yesterday evening), I now only get the same error as in Safari and the one @PhocaCz got i.e.
```
Error
An error has occurred while processing your request.
1045 Access denied for user 'root'@'localhost' (using password: NO)
```
This without touching at the sessions or cookies. Just deleting configuration.php
The former session in installation/sessions is replaced by the new one.

**Comment by wilsonge** [comment]
OK. right. i will chat to @rdeutz today as he can reproduce that one. I will try and get that sorted today. So does this mean we had some sort of firefox issue then? interesting if so...

**Comment by infograf768** [comment]
> interesting if so

Indeed.

**Comment by wilsonge** [comment]
So @laoneo got a 1045 the first time he used the installer and was then unable to reproduce :(

**Comment by infograf768** [comment]
I get it all the time.

**Comment by infograf768** [comment]
Hmm, I get again the issue at the origin of the Message... Grrr

**Comment by Fedik** [comment]
> 1045 the first time he used the installer and was then unable to reproduce

that is easy, just enter wrong PW or user 😉 

The installer should not continue and crash and burn, when there no DB connection, it should show some useful message to user: "Please check username or password" or something. I made issue for it some time ago #18557

Just guessing:
is there no any input filtering for PW? 
maybe @infograf768 password contain special symbols which filtered out, or somehow encoded while request


> @infograf768: Now, although we do have obviously a serious problem to be solved, one would have eventually to delete all cookies (make sure they are and all depends possibly on the browser)+ whatever necessary which I can't imagine.

I am agree. 
it even easy to reproduce: "Just enter wrong password and then try to continue or go back"   😉 
You will stuck on the error page.

**Comment by infograf768** [comment]
i used for superuser
admin/admin
and for db
root/root
which i do usually when testing on localhost

**Comment by infograf768** [comment]
`Loading failed for the <script> with source “http://localhost:8888/joomla40/media/system/js/fields/passwordview.min.js?d1fa27daf148fd07125aa694c437b914”.`

**Comment by Fedik** [comment]
@infograf768 do you have configuration.php saved after error? please check what user/password stored there, is they are correct.

**Comment by infograf768** [comment]
@Fedik 
> do you have configuration.php saved after error

Nope, as I do not get anymore the 1045 but the situation described in my original issue (Firefox Quantum).

When I did get the 1045, reloading the page did allow to go on installing and, yes, configuration.php was created.

**Comment by wilsonge** [comment]
The original firefox issue is fixed with https://github.com/joomla/joomla-cms/commit/c1eaef8339abe6f4ef04b932c2c910e36ad4a4ff

We're also committing a bodge for the 1045 issue that fixed things for @rdeutz until we fully understand the race condition (he couldn't reproduce it on chrome but could on firefox and safari 🤷‍♂️ ) with 84a79ca03e5d8254e81abf319a78cbeb1016f62b

**Comment by wilsonge** [comment]
Can you please test again @infograf768

**Comment by infograf768** [comment]
@wilsonge 
👏 
Closing as installation does not show these specific problems anymore.
We now can concentrate on the various missing aspects of it.
Thanks.
