### ISSUE TITLE
Guest modules disapear on backend

### ISSUE THREAD

**Issue by bolando** [joomla/joomla-cms#18563]
### Steps to reproduce the issue
1. Create custom Public module. Save & Close
2. Open it again and change the Group to Guest. Save & Close
3. It will disappear from the list and you will be unable to edit it.

### Expected result
1. Create custom Guest module. Save & Close
2. It should be visible on the backend list and editable.

### Actual result
Guest modules are no longer visible on the backend and no longer editable.

### System information (as much as possible)
Joomla 3.8.2, after upgrade

### Additional comments
Checked on 3 different Joomla installs
The modules are still in the database and on the frontend.

**Comment by conseilgouz** [comment]
Please check https://github.com/joomla/joomla-cms/issues/18542

Solved by https://github.com/joomla/joomla-cms/pull/18548

Pascal

**Comment by ghost** [comment]
closed as duplicate Report #18542

@pmleconte thanks for Hint.

**Comment by bolando** [comment]
Thank you!
