### ISSUE TITLE
Database error on Update Joomla 3.8.2

### ISSUE THREAD

**Issue by 99alex** [joomla/joomla-cms#18575]
### Steps to reproduce the issue
Hi

I have update to Joomla 3.8.2.

In the components menu, I am seeing entriers for deleted components https://www.screencast.com/t/Cd3ddtgThye

On clicking “COM_AKEEBASUBS” get a 404 -  https://www.screencast.com/t/m4qqrnUqggp 

I have check for DB errors and tried re-installing with no success

### System information (as much as possible)
Joomla 3.8.2

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
