### ISSUE TITLE
PostgreSQL driver don´t support port different than 5432

### ISSUE THREAD

**Issue by irbian** [joomla/joomla-cms#18578]
### Steps to reproduce the issue

Have a connection on a port different than the default and try to make a query on it

        $options = array();
        
        $options['driver']   = 'postgresql';        
        $options['host']     = '192.192.192.192:15432'; 
        $options['user']     = 'myuser';       
        $options['password'] = 'mypassword'; 
        $options['database'] = 'MYDATABASE';
        $options['prefix']   = '';             
        
        $dbo =  JDatabaseDriver::getInstance( $options );

### Expected result
I expect to work

### Actual result
"Error connecting to PGSQL database."

### Additional comments

Looking at the code (https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/database/driver/postgresql.php#L122), looks like is missing the port option, as we can see on http://php.net/manual/es/function.pg-connect.php. Modifying the code and adding port=1532, make it work

As a workaround, I can set options['host'] as  $options['host']     = '192.192.192.192 port=15432' and does the trick

**Comment by ghost** [comment]
@irbian is this still an Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18578">issues.joomla.org/tracker/joomla-cms/18578</a>.</sub>

**Comment by irbian** [comment]
looking at the code, looks like still is

**Comment by zero-24** [comment]
Here are a first basic implementation of the port support please check that out: https://github.com/joomla/joomla-cms/pull/19466 I'm open for feedback there on including also some kind of regex like we did for mysql for the port detection.

As we have a PR implementing this request I'm going to close this issue. Thanks!
