### ISSUE TITLE
[FOF] Deprecated notices on mcrypt* functions

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#18579]
### Steps to reproduce the issue

- install on PHP 7.1.6
- Enable totp
- set error level to development

### Expected result

No errors / warnings etc.

### Actual result

```
Deprecated: Function mcrypt_list_algorithms() is deprecated in JROOT/libraries/fof/utils/phpfunc/phpfunc.php on line 37

Deprecated: Function mcrypt_get_iv_size() is deprecated in JROOT/libraries/fof/encrypt/aes/mcrypt.php on line 155

Deprecated: Function mcrypt_get_iv_size() is deprecated in JROOT/libraries/fof/encrypt/aes/mcrypt.php on line 155

Deprecated: Function mcrypt_get_iv_size() is deprecated in JROOT/libraries/fof/encrypt/aes/mcrypt.php on line 155

Deprecated: Function mcrypt_decrypt() is deprecated in JROOT/libraries/fof/encrypt/aes/mcrypt.php on line 74
```

### Additional comments

What is the plan? Hacking the EOL Framework ourself or reporting & waiting for a upstream fix?

As we are told in the readme notes the following:

```
Framework on Framework 2.x is End Of Life since June 2016

If you are still using it, too bad for you. We told you to update your components to FOF 3.x back in early 2015.

Don't cry if it's broken. Don't ask us to fix it. It's DISCONTINUED, remember?
```

**Comment by mbabker** [comment]
It isn't not an issue as those method calls exist in places where there are already checks happening.  IIRC mcrypt is only used when OpenSSL is unavailable in that code.

**Comment by zero-24** [comment]
Atleast there are still explizite calls to mcrypt: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_users/models/user.php#L1014 Looks like they are only used incase we us a broken totp call as described in https://github.com/joomla/joomla-cms/issues/18559

**Comment by wilsonge** [comment]
The explicit call I see there is just to convert people currently on mcrypt over to ssl?

**Comment by zero-24** [comment]
looks like a broken envoirment than.

**Comment by wilsonge** [comment]
Not really. I mean basically this code converts from mcrypt to openssl. so to do that we need to actually call the mcrypt version first to decrypt the legacy string. then openssl to re-encrypt. so these deprecated functions are being called. But it's a one time only call per user who has a 'legacy' string
