### ISSUE TITLE
jhtml calendar doesn't change value and ignores html attribute style

### ISSUE THREAD

**Issue by jbrailas** [joomla/joomla-cms#18576]
### Steps to reproduce the issue
Execute the following and pick current date.

```
<div id="pickdate" class="disabledbutton">
<?php echo JHTML::_( 'calendar','01/01/2015','mydate','mydate','%d/%m/%Y', array('class'=>"inputbox validate-date", 'style'=>"float:left")); ?>
</div>
```

### Expected result
`<input type="text" id="mydate" name="mydate" value="15/11/2017" class="inputbox validate-date" style="float:left" data-alt-value="01/01/2017" autocomplete="off">`

### Actual result
`<input type="text" id="imerom_liksis" name="imerom_liksis" value="01/01/2015" class="inputbox validate-date" data-alt-value="15/11/2017" autocomplete="off">`

### System information (as much as possible)
Joomla 3.8.1
Apache/2.4.27 (Fedora) mod_auth_kerb/5.4 PHP/7.1.9

**Comment by rajeshstarlite** [comment]
Hello @jbrailas 
Are you using JHTML::_( 'calendar') multiple times in a page?

also style tag isn't supported https://github.com/joomla/joomla-cms/blob/staging/libraries/src/HTML/HTMLHelper.php#LC995

**Comment by jbrailas** [comment]
I am using JHTML::_( 'calendar') two times in the same page.

**Comment by rajeshstarlite** [comment]
Okay, please use unique id, name for each of the calendar and try. I think, everything should be working normally.

**Comment by jbrailas** [comment]
ok
