### ISSUE TITLE
tinymce 4.5.8

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#18572]
there is a new release with 3 small fixes but for some reason the files are not minified anymore so I am holding off creating a PR while waiting an answer from tinymce https://github.com/tinymce/tinymce/issues/4067

**Comment by dgrammatiko** [comment]
It should be here: https://github.com/tinymce/tinymce-dist/releases

**Comment by brianteeman** [comment]
Grrh I was on the wrong place https://github.com/tinymce/tinymce/releases

Closing this and will do the PR tomorrow
