### ISSUE TITLE
Joomla 3.8.2 ACL issues in MENU manager and Module Manager

### ISSUE THREAD

**Issue by pepwave1** [joomla/joomla-cms#18580]
### Steps to reproduce the issue
Go to Menu Manager
Create a menu item with ANY ACL set to ANY level other than "Guest" or "registered"
Attempt to access the item from a user account with the appropriate access level.
Menu item:  does not appear...stays in the Administrator panel, but it cannot be accessed on the user side of the website
Module item set to ANY ACL level other than "Guest" or "registered" simply disappears.

### System information (as much as possible)
Joomla 3.8.2 on Godaddy updated to PHP 7.2

### Additional comments
THIS IS A MASSIVE PAIN IN MY A**.
I will have to wait until 2 or 3am tonight...save all of the files on my website...take the whole thing down...reinstall Joomla 3.8.1 and reinstall the files and PRAY TO GOD the thing works.

I have over 200 subscribers with very specific ACL configurations on my site (it is a membership site) and I am in the middle of a campaign to get more subscribers...and THIS happens. 

Sometimes, i feel like this is what I get with going for something free instead of paying for it to be built from the ground up.

**Comment by tonypartridge** [comment]
Can you try this PR:
https://github.com/joomla/joomla-cms/pull/18548

Noting, you could just download Joomla! 3.8.1 and upload the files less the config and the installation folder overwriting the 3.8.2 files to restore it back.

**Comment by pepwave1** [comment]
That worked.
I was actually in the middle of doing this when I received this email.
I need to figure out how to close the issue report.

On Nov 15, 2017, at 03:38 PM, Tony Partridge <notifications@github.com> wrote:

Can you try this PR:
#18548
Noting, you could just download Joomla! 3.8.1 and upload the files less the config and the installation folder overwriting the 3.8.2 files to restore it back.

**Comment by pepwave1** [comment]
Solution:

Went to Godaddy.com to the CPanel...looked at my joomla install under the Applications tab.

"Upgraded Joomla" to 3.8...a backup was automatically created and the joomla install files were rewritten.

There was no degradation to the user experience...happened seamlessly<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18580">issues.joomla.org/tracker/joomla-cms/18580</a>.</sub>

**Comment by pepwave1** [comment]
How do I close this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18580">issues.joomla.org/tracker/joomla-cms/18580</a>.</sub>

**Comment by tonypartridge** [comment]
Clicking the close button at the bottom of the tracker.

**Comment by brianteeman** [comment]
closed as requested
