### ISSUE TITLE
Fatal error: Cannot use $this as parameter in C:\xampp\...\layouts\header.php on line 10

### ISSUE THREAD

**Issue by joshuaekeh** [joomla/joomla-cms#18582]
I installed a quickstart package of a Joomla theme on my pc using XAMPP. After the install completed and I had deleted the installation folder, I tried to view the site but the following error displayed.

`Fatal error: Cannot use $this as parameter in C:\xampp\htdocs\intense\templates\intensy\layouts\header.php on line 10`

The result I am supposed to get is the full demo site of the template.

I tried with another template and I also got the same result.

Could there be something wrong with the XAMPP or its Joomla

**Comment by brianteeman** [comment]
The it is a problem with the template you are using and you should ask the template creator

**Comment by ghost** [comment]
closed as no Core-Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18582">issues.joomla.org/tracker/joomla-cms/18582</a>.</sub>
