### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by chrisisswift** [joomla/joomla-cms#18585]
Our Joomla site, insidemcgraw.com is not allowing me to login to our admin panel insidemcgraw.com/administrator. Whenever I enter our credentials (username: `<removed>`, password: `<removed>`) it takes me to a screen that says:

www.insidemcgraw.com is currently unable to handle this request.
HTTP ERROR 500

Can you assist?

**Comment by brianteeman** [comment]
Please use the forum for support (https ;//forum.joomla.org) and NEVER post your admin username and password in public
