### ISSUE TITLE
Validation error for not required inputs that has pattern atribute

### ISSUE THREAD

**Issue by gptforjoomla** [joomla/joomla-cms#18591]
Hi, this pull has a problem with unrequired inputs.
### Steps to reproduce the issue
a field that is not required but has pattern to be a number or other . do not fill input and submit.
### Expected result
form must submit without error with empty value for the input

### Actual result

when user not enter value for this input and submit, validation say that field is not correct

### System information (as much as possible)

Joomla 3.8.2

**Comment by zero-24** [comment]
closing as there is a PR #18624 thanks @minijoomla
