### ISSUE TITLE
[3.8.2] Require Password Reset

### ISSUE THREAD

**Issue by MSnoeren** [joomla/joomla-cms#18590]
The require password option resets in the same request when you update the users' password as well.

### Steps to reproduce the issue
1. Open any user
2. Enter a new password in both fields
3. Enable the option "Require Password Reset"
4. Save the user

### Expected result
The expected result would be a changed password while the require password option is enabled.

### Actual result
The password changed but the "require password" option is turned off, although on was selected.

### System information (as much as possible)
Linux with PHP 7.1 and Joomla 3.8.2

### Additional comments

**Comment by brianteeman** [comment]
If I understand you I think you are not understanding the feature. 

"Setting this option to yes requires the user to reset their password the next time they log into the site."

**Comment by MSnoeren** [comment]
False, but for example; you change the password for an user into a simple one because they forgot. You check the "require password"-option and click save. The option is being reset and set to off while you requested it to be on. If you click "save and close" it'll ignored and the user will be user the easy password.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18590">issues.joomla.org/tracker/joomla-cms/18590</a>.</sub>

**Comment by zero-24** [comment]
yes. this is a known problem atm. You can not set the PW reset together with a new pw. So you first need to set the new PW and than edit the user again to set the PR reset.

**Comment by brianteeman** [comment]
ah i understand now

**Comment by zero-24** [comment]
here is the last PR tried to fix this issue: https://github.com/joomla/joomla-cms/pull/16804 maybe someone else have an good idea how to fix this and not break the other logic michael points out there.

**Comment by Quy** [comment]
How about resetting the flag only if the User ID is the owner?

**Comment by zero-24** [comment]
Can you please explain a bit more what you want us to implement?

**Comment by Quy** [comment]
Make the following an if statement where only execute it when the logged in ID is the same as the user ID of the account.

```
$array['requireReset'] = 0;
```
In other words, only the owner of the account can reset this flag. Any changes done by the Super Admin on the backend will not affect this flag.

**Comment by mbabker** [comment]
My point in https://github.com/joomla/joomla-cms/pull/16804#issuecomment-310236565 still stands.  It doesn't really matter WHO changes the password, the system only cares that the password is changed at a point after that flag is set.  And without tightly coupling JUser to request data, or moving the code to the com_users MVC (which destroys its usability if you're using some extension which acts as a replacement for com_users), there really isn't a good solution to the scenario of "as an administrator I change an account's password and mark their account as requiring a password reset".

**Comment by Quy** [comment]
Got it. Can this be closed then as expected behavior?

**Comment by mbabker** [comment]
Closing per above.
