### ISSUE TITLE
[4.0] Layout overlap on 27" screen

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18595]
### Steps to reproduce the issue

Go to Global Config 
move Google Chrome window to half of a 27" iMac screen

### Expected result

Layout doesnt overlap

### Actual result

Overlapping elements
![screen shot 2017-11-17 at 18 55 34](https://user-images.githubusercontent.com/400092/32963765-e9782c30-cbc8-11e7-8ab2-d0abf064bef2.png)

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18595">issues.joomla.org/tracker/joomla-cms/18595</a>.</sub>

**Comment by brianteeman** [comment]
This is a template issue and this will not be the admin template used. Depends on @wilsonge and @mbabker but I would recommend closing any admin template layout related issues at this time. Its a real pain and confusing for testers that the new admin template was so delayed waiting for any feedback/progress in the UX group. But thats happened.

**Comment by ciar4n** [comment]
PR created... #18658

I agree with @brianteeman, that these issues/fixes are somewhat irrelevant if the template general design is to change.

**Comment by ghost** [comment]
closed as having Pull Request #18658
