### ISSUE TITLE
[4.0] Cannot Download System Information

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18593]
### Steps to reproduce the issue

Install from joomla-cms-4.0.0-alpha1.zip with sensible defaults.
Login to admin
Go to System Information, Click 

 - Download as text
 - Download as JSON

### Expected result

Downloaded file

### Actual result

Fatal Error

### System information (as much as possible)

> Fatal error: Class 'Joomla\CMS\View\AbstractView' not found in /Users/phil/Downloads/joomla-cms-4.0.0-alpha1/administrator/components/com_admin/View/Sysinfo/JsonView.php on line 21

**Comment by brianteeman** [comment]
Confirmed

**Comment by mbabker** [comment]
Fixed via https://github.com/joomla/joomla-cms/commit/6e890f7e54bcfe0cca89347d4d561cc90933b69c
