### ISSUE TITLE
[4.0] default 404 page out of the box has JS errors/JS 404 errors

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18599]
### Steps to reproduce the issue

install [4.0Alpha] 
go to any url that generates a 404 

### Expected result

no JS errors
no assets 404

### Actual result

![screen shot 2017-11-17 at 19 21 27](https://user-images.githubusercontent.com/400092/32964869-8647a984-cbcc-11e7-9663-0a8b040c6b80.png)
![screen shot 2017-11-17 at 19 21 38](https://user-images.githubusercontent.com/400092/32964879-8cad4f04-cbcc-11e7-94f7-29b8057dd1f2.png)

**Comment by ghost** [comment]
Don't know if this is what you meant:
![bildschirmfoto 2017-11-19 um 09 04 00](https://user-images.githubusercontent.com/8235763/32988655-b6cc80ba-cd08-11e7-803a-a1078774ebca.jpg)

**Comment by PhilETaylor** [comment]
My screenshot was the frontend

![screen shot 2017-11-19 at 08 52 43](https://user-images.githubusercontent.com/400092/32988962-06adc8ac-cd07-11e7-8b01-4351f6390761.png)

**Comment by Fedik** [comment]
it is the template problem, in error.php missed `JUri::root()` for relative files. 

![screen 2017-11-19 11 08 33 661x98](https://user-images.githubusercontent.com/1568198/32989177-36bd3862-cd1a-11e7-8f66-ce4900debc6d.png)

I could fix it for backend template but there also similar problem for front end template, and there additionally missed `tether.min.js` file.
So better  to check this by someone who made/know the templates.

**Comment by PhilETaylor** [comment]
same in Alpha 2 to be clear.

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/19218

**Comment by ghost** [comment]
closed as having Pull Request ##19218
