### ISSUE TITLE
[4.0] Cannot refresh help servers

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18594]
### Steps to reproduce the issue

Steps to reproduce the issue

Install from joomla-cms-4.0.0-alpha1.zip with sensible defaults.
Login to admin
Go to Global Configuration -> System Tab
Click Refresh button next to help server

### Expected result

ajax gets json (which it is doing) and then render that as a dropdown

### Actual result

ajax gets json (which it is doing) and then the dropdown remains empty

![screen shot 2017-11-17 at 19 13 32](https://user-images.githubusercontent.com/400092/32964521-6ed688de-cbcb-11e7-91fb-afb68116199b.png)

### System information (as much as possible)

PHP Version 7.1.11

**Comment by brianteeman** [comment]
Do any other help servers exist for j4

**Comment by PhilETaylor** [comment]
Dont know, but thats not the problem. The ajax returns data, and that data should be rendered correctly - its not. 

`{"success":true,"message":null,"messages":null,"data":[{"value":"","text":"- Use Default -","disable":false},{"text":"English (GB) - Joomla help wiki","value":"https:\/\/help.joomla.org\/proxy?keyref=Help{major}{minor}:{keyref}&lang={langcode}"},{"text":"Fran\u00e7ais (FR) - Aide de Joomla!","value":"https:\/\/help.joomla.fr\/index.php?option=com_help&keyref=Help{major}{minor}:{keyref}"}]}`

**Comment by wilsonge** [comment]
Fixed with 670c07690d9b632cabde171f67a907f618b9e8aa
