### ISSUE TITLE
[4.0] Advanced Permissions Report Errors

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18592]
### Steps to reproduce the issue

Install from joomla-cms-4.0.0-alpha1.zip with sensible defaults. 
Login to admin 
Go to manage users
click Advanced Permissions Report

### Expected result

No errors

### Actual result

![screen shot 2017-11-17 at 18 50 19](https://user-images.githubusercontent.com/400092/32963528-2dbcfea8-cbc8-11e7-9639-370d49328e27.png)

### System information (as much as possible)
PHP Version 7.1.11
Mac.
Nothing crazy

**Comment by mbabker** [comment]
The model's `populateState` method is not being triggered so the request data isn't getting loaded into model state.

**Comment by wilsonge** [comment]
Should be fixed with d1fe20dab9
