### ISSUE TITLE
[4.0] Missing English

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18597]
### Steps to reproduce the issue

Install 4.0Alpha click COG icon next to popular Articles Module on control panel 

### Expected result

All english

### Actual result

Several missing text placeholders are showing 

![screen shot 2017-11-17 at 18 58 43](https://user-images.githubusercontent.com/400092/32963906-61e4c390-cbc9-11e7-8ac6-62fec6bc3b10.png)

**Comment by brianteeman** [comment]
Can not replicate this

**Comment by ot2sen** [comment]
Neither could I. Perhaps Phil used the default chosen en-US on install? Had to select en-GB

**Comment by brianteeman** [comment]
even then it wouldnt do that as there is no where in the code of j4 that those keys exist

**Comment by infograf768** [comment]
I corrected this here:
https://github.com/joomla/joomla-cms/pull/18646

that module is an admin module.

**Comment by infograf768** [comment]
Closing as we have a patch https://github.com/joomla/joomla-cms/pull/18646

**Comment by PhilETaylor** [comment]
different day - different computer - same issue. 

#18646 fixes it for me.
