### ISSUE TITLE
[4.0] New install still has extensions to discover

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18602]
### Steps to reproduce the issue

install [4.0Alpha] with sane defaults
Go to /administrator/index.php?option=com_installer&view=discover

### Expected result

See no results

### Actual result

![screen shot 2017-11-17 at 19 31 33](https://user-images.githubusercontent.com/400092/32965266-f02218d4-cbcd-11e7-99b6-c26fe8258de3.png)

### Further info

On trying to install the above extensions we get 

`PLG_EXTENSION_NAMESPACEMAP_XML_DESCRIPTION`

![screen shot 2017-11-17 at 19 32 21](https://user-images.githubusercontent.com/400092/32965325-0bfa7b64-cbce-11e7-9f92-18e1269bcc08.png)

**Comment by brianteeman** [comment]
known issue as it hasnt been decided what to do with namespacemap yet

**Comment by PhilETaylor** [comment]
and what about `footer` module?

**Comment by brianteeman** [comment]
same - its not currently used in j4

**Comment by C-Lodder** [comment]
@brianteeman I remember moving the footer to a custom module, and wanted to remove `mod_footer` from J4, however there were some objections if I recall. Don't suppose you remember what they were?

**Comment by brianteeman** [comment]
yes the question about mod_footer was if it was ok to remove it if extensions were targetting it. iirc some stuff from @regularlabs might do that

**Comment by regularlabs** [comment]
I have some admin modules that use the `status` module position. So as long as that position remains somewhere, I don't see an issue.
In J2.5 it was in the top bar. In J3 it's in the bottom bar.

I am not doing anything specifically with the `mod_footer`.

**Comment by brianteeman** [comment]
ok - thanks for confirming that @regularlabs

**Comment by dgrammatiko** [comment]
> I have some admin modules that use the status module position

I would expect that position to be on the upper right corner before the user icon and in fact it is like that

```
					<jdoc:include type="modules" name="title" />
					<jdoc:include type="modules" name="status" style="no" />
```

**Comment by schnuti** [comment]
mod_footer is a frontend module!
It was maintained 13 days ago but still in the discover list as of june 26 2018.

**Comment by brianteeman** [comment]
@schnuti thanks - silly confusion with thinking it was an admin module

**Comment by brianteeman** [comment]
with #21103 there wont be any extensions left to discover. Thanks for reporting
