### ISSUE TITLE
[4.0] Content options return error

### ISSUE THREAD

**Issue by ot2sen** [joomla/joomla-cms#18600]
### Steps to reproduce the issue
Visit Content and try edit Options.

### Expected result
Should let you edit content/category options

### Actual result
An error has occurred.
0 Class 'Joomla\Component\Content\Administrator\Field\JPluginHelper' not found

### System information (as much as possible)
Database Version 
5.6.24 
Database Collation 
utf8mb4_unicode_ci 
Database Connection Collation 
utf8_general_ci 
PHP Version 
7.1.8 
Web Server 
Apache/2.4.27 (Win32) OpenSSL/1.1.0f PHP/7.1.8 
WebServer to PHP Interface 
apache2handler 
Joomla! Version 
Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT

**Comment by PhilETaylor** [comment]
me too 

![screen shot 2017-11-17 at 19 53 26](https://user-images.githubusercontent.com/400092/32966216-ff759286-cbd0-11e7-8f44-99032ff00a46.png)

**Comment by wilsonge** [comment]
Fixed with a8b4b8ea5f31e8309050809e7566ddd733d8c102
