### ISSUE TITLE
[4.0] Forgot your username/password links are 404

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18601]
### Steps to reproduce the issue

got to /administrator/

Click - Forgot your username?
or
Click - Forgot your password?

### Expected result

Clicking takes me to a new page with 200 Ok Status (i.e. the right page) 

### Actual result

404 Not found pages.

### Additional comments
Previously reported by me back in May
https://github.com/joomla/joomla-cms/issues/15786
https://github.com/joomla/joomla-cms/pull/15816

**Comment by ghost** [comment]
Click on both Links loads Frontend-Startpage.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18601">issues.joomla.org/tracker/joomla-cms/18601</a>.</sub>

**Comment by wilsonge** [comment]
These work for me too. @PhilETaylor can you provide any more information about setup or something?

**Comment by PhilETaylor** [comment]
I just reinstalled from scratch, my "server" is 

`php -S 0.0.0.0:8010`

```
Unique ID	707d2b7806a60debd39e54bb17bfc8cf98c6de6f
PHP Version	7.1.11
DB Type	mysqli
DB Version	5.7.20
CMS Version	4.0.0
Server OS	Darwin 17.3.0
```

Now my admin side links work - but the ones on the frontend now lead to 404's 

The links are:
http://0.0.0.0:8010/index.php/remind?Itemid=101
http://0.0.0.0:8010/index.php/reset?Itemid=101

![screen shot 2017-11-18 at 19 55 58](https://user-images.githubusercontent.com/400092/32984230-82a299a0-cc9a-11e7-86b1-d4b8f48a4867.png)

**Comment by PhilETaylor** [comment]
Closing this as this is 100% caused by https://github.com/joomla/joomla-cms/issues/18683
