### ISSUE TITLE
[4.0Alpha] Joomla\Component\Templates\Administrator\Table\Style' not found

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18603]
### Steps to reproduce the issue

install [4.0Alpha] 

do this: 
![screen recording 2017-11-17 at 07 33 pm](https://user-images.githubusercontent.com/400092/32965437-5a775550-cbce-11e7-8ed5-e506dc55f530.gif)

### Expected result

No error

### Actual result

`Joomla\Component\Templates\Administrator\Table\Style' not found`

**Comment by wilsonge** [comment]
Thanks! Fixed with https://github.com/joomla/joomla-cms/commit/bc234e90fe4f0273233870d364bd255a837bc275
