### ISSUE TITLE
[4.0] Create new template file modal layout issues

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18605]
### Steps to reproduce the issue

Click create new file on the template edit page 

### Expected result

Pretty suff

### Actual result

Ugly stuff
![screen shot 2017-11-17 at 19 41 10](https://user-images.githubusercontent.com/400092/32965700-493554ee-cbcf-11e7-937d-961c866ba219.png)

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18605">issues.joomla.org/tracker/joomla-cms/18605</a>.</sub>

**Comment by ciar4n** [comment]
PR created... #18665

**Comment by ghost** [comment]
closed as having Pull Request #18665.
