### ISSUE TITLE
[4.0] Cannot add tags to content

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18608]
### Steps to reproduce the issue

Go to 
Click New 
add some tags to the article
click save 

### Expected result

Article saves

### Actual result
Class 'Joomla\Component\Tags\Administrator\Table\Tag' not found

![screen shot 2017-11-17 at 19 55 46](https://user-images.githubusercontent.com/400092/32966309-52d37c40-cbd1-11e7-9e28-4090fc039871.png)

**Comment by ghost** [comment]
Can't confirm, Tags are saved as extected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18608">issues.joomla.org/tracker/joomla-cms/18608</a>.</sub>

**Comment by wilsonge** [comment]
Could confirm

Fixed with https://github.com/joomla/joomla-cms/commit/81b42094c66cc5144c691b72e462be751912b24a
