### ISSUE TITLE
[4.0] Cannot save new field group

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18609]
### Steps to reproduce the issue

Attempt to create a new Field Group 

### Expected result

New field group saves

### Actual result
![screen shot 2017-11-17 at 19 57 59](https://user-images.githubusercontent.com/400092/32966429-ae1d9810-cbd1-11e7-9c5b-d9f3560b3f7b.png)

### additional bug

See that the help for the "Title" is just "Title" - we can do better than that :) 

![screen shot 2017-11-17 at 19 59 14](https://user-images.githubusercontent.com/400092/32966488-ce4073c4-cbd1-11e7-9975-e1bfbf267a15.png)

**Comment by ghost** [comment]
Confirmed.

Didn't get a Error but Group isn't saved (test on Articles and Users).
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18609">issues.joomla.org/tracker/joomla-cms/18609</a>.</sub>

**Comment by mbabker** [comment]
Probably a MySQL 5.7 thing.  I have the same problem.

**Comment by laoneo** [comment]
Pr #18676 should fix the issue.

**Comment by ghost** [comment]
closed as having Pull Request #18676.
