### ISSUE TITLE
[4.0Alpha] Some breakpoint means that content disappears behind left menu

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18606]
### Steps to reproduce the issue

go to admin - squeeze the page to different breakpoints - reload pages at that breakpoint - experiment.

### Expected result

good experience

### Actual result
Do we expect user to keep closing the left menu?
![screen recording 2017-11-17 at 07 46 pm](https://user-images.githubusercontent.com/400092/32965999-53bd5f78-cbd0-11e7-97a1-fbb71ef9a606.gif)

even when the left menu is closed there are overlap issues:

![screen recording 2017-11-17 at 07 49 pm](https://user-images.githubusercontent.com/400092/32966050-7cdad264-cbd0-11e7-9edb-baf802030ad9.gif)

**Comment by brianteeman** [comment]
I am going to close this one as this is not the admin template that will be used. We've been waiting a crazy long time for the UX team to feedback before implementing the real one. And as stated in the announcement it is known that this is not mobile compatible
