### ISSUE TITLE
[4.0] Unable to edit template overrides/files in admin

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18604]
### Steps to reproduce the issue

Attempt to edit template files in admin console.

### Expected result

I can see the file content

### Actual result

The file content loads in the text area for a fraction of a second, and then JS kicks in, and creates errors - might be related to the flyingfocus generic issue, might be the other codemirror JS issues. 
![screen shot 2017-11-17 at 19 39 29](https://user-images.githubusercontent.com/400092/32965655-0e835652-cbcf-11e7-9050-6e6ea77c3f18.png)

**Comment by infograf768** [comment]
Confirmed

**Comment by wilsonge** [comment]
Fixed with 8760edc02814a97a08c6b3b86a75817fa756eac1
