### ISSUE TITLE
[4.0] Media Manager reports directories as Size=0

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18616]
### Steps to reproduce the issue

Go to media manager - show by list

### Expected result

directories should not report their size, or if they do, report correctly

### Actual result

directories all report as being Size = 0 which is incorrect. 

![screen shot 2017-11-17 at 20 19 33](https://user-images.githubusercontent.com/400092/32967221-b499742c-cbd4-11e7-8616-9979552cd291.png)

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18616">issues.joomla.org/tracker/joomla-cms/18616</a>.</sub>
