### ISSUE TITLE
[4.0] Error decoding JSON data: Syntax error

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18610]
### Steps to reproduce the issue

install [4.0Alpha] 
Log many many bugs with [4.0Alpha] into github...
Go to Articles -> Fields -> New 

### Expected result

Edit form shown to create a new field

### Actual result

Error decoding JSON data: Syntax error

![screen shot 2017-11-17 at 20 00 47](https://user-images.githubusercontent.com/400092/32966559-0417515c-cbd2-11e7-9096-d08d56500738.png)

**Comment by mbabker** [comment]
Fixed via https://github.com/joomla/joomla-cms/commit/d599125a2cad74064382d31b41e0015e6495cd97
