### ISSUE TITLE
[4.0] Failed login on frontend goes to a 404 error

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18614]
### Steps to reproduce the issue

attempt to login to frontend with invalid credentials (or just click login)

### Expected result

login page with error message saying invalid credentials

### Actual result

404 error page with url http://0.0.0.0:8010/index.php/login?Itemid=101

click back and then you get the warning:

![screen shot 2017-11-17 at 20 12 50](https://user-images.githubusercontent.com/400092/32966970-b314b216-cbd3-11e7-9463-6f78bf36977c.png)

**Comment by ghost** [comment]
Can't confirm. Failing Logins (Module, Menu) redirect to `/login?view=login`.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18614">issues.joomla.org/tracker/joomla-cms/18614</a>.</sub>

**Comment by PhilETaylor** [comment]
Just tested in Alpha2 and the problem persists. 

When I fail to login it still goes to http://0.0.0.0:8010/index.php/login?Itemid=101 which is like

I DONT have any sample data installed. 

![screen shot 2017-11-19 at 17 23 43](https://user-images.githubusercontent.com/400092/32993330-6866f8a6-cd4e-11e7-9714-2f09960eebd2.png)

**Comment by ivanework** [comment]
Hope this following code will redirect to the current page:
File: \components\com_users\Controller\UserController.php inside the login failed conditional statement, Line number: [125]
```
$currentid = $app->getMenu()->getActive()->id;
$app->redirect(\JRoute::_('index.php?Itemid='.$currentid, false));
//$app->redirect(\JRoute::_('index.php?option=com_users&view=login', false));
```

And, it show the warning message, but css opacity hide the message on home page.

![534a1f444fc34a0fe379aa80c2c401f9](https://user-images.githubusercontent.com/35343631/34875225-64576b9e-f7c2-11e7-95f0-f8e895a92887.png)

**Comment by joomdonation** [comment]
This PR https://github.com/joomla/joomla-cms/pull/18924 should fixed the issue

**Comment by ivanework** [comment]
Yeah, that global fix will solve this also.

**Comment by joomdonation** [comment]
Could someone close this issue then?
