### ISSUE TITLE
[4.0] On small screens the Print/Email dropdown is truncated by screen edge

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18613]
### Steps to reproduce the issue

on small screen click the cog next to an article for the print/email dropdown

### Expected result

the dropdown is not truncated by the screen edge

### Actual result

![screen shot 2017-11-17 at 20 08 27](https://user-images.githubusercontent.com/400092/32966887-39ae9a40-cbd3-11e7-89f0-8eef706c8cb5.png)

This is a well known issue with bootstrap dropdowns too - they have a css class for dropdown-right that can be applied - Im guessing the same fix can be applied? (I know the default J4 template is not bootstrap, but still css is css :) )

**Comment by brianteeman** [comment]
it is bs4 ;) and

> Joomla 4.0 is known to **not be mobile compatible** nor upgradable from Joomla 3.9 at this point.

**Comment by PhilETaylor** [comment]
try using a small screen laptop then - same issue :) 

This one is not about being mobile. 

Any dropdown, that can be on the right of the screen, needs to unfurl to the bottom left and not bottom right of the element

**Comment by brianteeman** [comment]
small screen, mobile - same issue

**Comment by PhilETaylor** [comment]
> small screen, mobile - same issue
Disagree

you could have a MASSIVE screen, but if this dropdown is on the far left of it, it will still be truncated.

This is not about screensize, this is about proximity to the screen edge.

**Comment by ciar4n** [comment]
Appears to be a Bootstrap issue. If you open the dropdown and then scroll slightly, the dropdown position corrects itself.

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/18782

**Comment by ghost** [comment]
closed as having Pull Request #18782
