### ISSUE TITLE
[4.0] Email to friend popup fields unuseable

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18612]
### Steps to reproduce the issue

Click the email to friend link on an article 

### Expected result

a useable form 

### Actual result
tiny form fields:

![screen shot 2017-11-17 at 20 07 32](https://user-images.githubusercontent.com/400092/32966817-f692404a-cbd2-11e7-87ea-f9de9846244c.png)

### System information (as much as possible)

Google Chrome
Standard [4.0Alpha] template

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18612">issues.joomla.org/tracker/joomla-cms/18612</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #18662.
