### ISSUE TITLE
[4.0] Unstyled Button & JS error

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18615]
### Steps to reproduce the issue

Click to create new menu item -> module assignment ->click breadcrumbs ->model opens... 

### Expected result

Lipstick and paint look beautiful

### Actual result

Unstyled close button. 

![screen shot 2017-11-17 at 20 17 18](https://user-images.githubusercontent.com/400092/32967121-55f39114-cbd4-11e7-8ccc-2f52b4a64230.png)

### further bug

When clicking the unstyled close button - get new JS error

![screen shot 2017-11-17 at 20 17 54](https://user-images.githubusercontent.com/400092/32967151-75730394-cbd4-11e7-9ae3-c1b5718db786.png)

**Comment by wilsonge** [comment]
I've fixed the javascript errors with ae4add3c32f226b7d75e0cba38b5c240611d903b

As to the button - it's technically using the btn-secondary styling. So it is styled. If we want to change it we'd have to update the whole bootstrap secondary colour
