### ISSUE TITLE
[4.0] Media Manager reports files MODIFIED before the date they were CREATED!?

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18617]
### Steps to reproduce the issue

List images folder by list mode in media manager

### Expected result

Surely the modified must be after the created?

### Actual result

Modified dates are before the created dates

![screen shot 2017-11-17 at 20 19 33](https://user-images.githubusercontent.com/400092/32967285-f6ec48cc-cbd4-11e7-8ff9-85f169be8808.png)

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18617">issues.joomla.org/tracker/joomla-cms/18617</a>.</sub>

**Comment by ghost** [comment]
@PhilETaylor: according to @laoneo closing this Issue, please open a new one at https://github.com/joomla-projects/media-manager-improvement.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18617">issues.joomla.org/tracker/joomla-cms/18617</a>.</sub>

**Comment by PhilETaylor** [comment]
I dont see why it should be closed, and you dont state.

I cannot even get the media manager to load using the current code from https://github.com/joomla-projects/media-manager-improvement.

**Comment by ghost** [comment]
reopened as @laoneo suggest.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18617">issues.joomla.org/tracker/joomla-cms/18617</a>.</sub>

**Comment by brianteeman** [comment]
I can no longer replicate this. I can only assume it was resolved elsewhere so I shall close it. If I am mistaken it can always be reopened
