### ISSUE TITLE
[4.0] Link to registration form is 404

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18611]
### Steps to reproduce the issue

install [4.0Alpha] 
set "Allow User Registration" to YES

![screen shot 2017-11-17 at 20 05 19](https://user-images.githubusercontent.com/400092/32966727-af667920-cbd2-11e7-816c-4bcf86ca8c3e.png)

Go to frontend - see new "Create an account" link:

![screen shot 2017-11-17 at 20 06 02](https://user-images.githubusercontent.com/400092/32966756-c78f5eea-cbd2-11e7-8a13-dfd7171ec1fd.png)

### Expected result

Registration PAge is presented... 

### Actual result

404 Error 
![screen shot 2017-11-17 at 20 06 37](https://user-images.githubusercontent.com/400092/32966785-d534983a-cbd2-11e7-929c-678125db4e10.png)

**Comment by ghost** [comment]
Can't confirm. 

Link `Create an account` open correct "User Registration".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18611">issues.joomla.org/tracker/joomla-cms/18611</a>.</sub>

**Comment by wilsonge** [comment]
I can replicate only without sample data (i.e. no registration page menu item)

**Comment by ghost** [comment]
My Test was on an Installation using Sample Data.

**Comment by ciar4n** [comment]
PR created.. #18924

**Comment by ghost** [comment]
closed as having Pull Request #18924
