### ISSUE TITLE
[4.0] Fatal Error when using Insert Module button in WYSIWYG

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18619]
### Steps to reproduce the issue

install [4.0Alpha] 
edit an article on the frontend 
click "Module" button in the WYSIWYG editor

### Expected result

Something that is not a PHP Fatal error

### Actual result

Fatal error: Declaration of ModulesDispatcher::getController($name, $client = NULL, $config = Array) must be compatible with Joomla\CMS\Dispatcher\Dispatcher::getController(string $name, string $client = '', array $config = Array): Joomla\CMS\MVC\Controller\BaseController in /Users/phil/Downloads/joomla-cms-4.0.0-alpha1/components/com_modules/dispatcher.php on line 19

![screen shot 2017-11-17 at 20 38 34](https://user-images.githubusercontent.com/400092/32967935-4b451064-cbd7-11e7-8a71-aeba57b3d262.png)

**Comment by mbabker** [comment]
Fixed via https://github.com/joomla/joomla-cms/commit/6a024855c2122d2750b686d69cd2491ec58893e3
