### ISSUE TITLE
[4.0] Double arrows on dropdown

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18623]
### Steps to reproduce the issue
install [4.0Alpha]
Edit an article on the frontend of the site
Click Publishing Tab

### Expected result

one set of up and down arrows like this: 

![screen shot 2017-11-17 at 20 43 56](https://user-images.githubusercontent.com/400092/32968139-0abfcf56-cbd8-11e7-9392-cdda0a061a86.png)

### Actual result

Look at the Access dropdown

![screen shot 2017-11-17 at 20 44 02](https://user-images.githubusercontent.com/400092/32968144-0e7df686-cbd8-11e7-8d64-892f7f449724.png)

### System information (as much as possible)

Google Chrome

**Comment by ghost** [comment]
Issue confirmed also on `Status` and `Featured`:
![screen shot 2017-11-18 at 09 09 31](https://issues.joomla.org/uploads/1/8db3d92bf3f4e5f4988289d4a2e902a9.jpg)
### System information
4.0.0-dev
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18623">issues.joomla.org/tracker/joomla-cms/18623</a>.</sub>

**Comment by mbabker** [comment]
It's an issue with the Bootstrap `.custom-select` class.  // @C-Lodder

**Comment by ciar4n** [comment]
PR created.. #18663 

Appears to be a known bootstrap bug (twbs/bootstrap#16201).

**Comment by ghost** [comment]
closed as having Pull Request #18663
