### ISSUE TITLE
[4.0] JUser: :_load: Unable to load user with ID: 589

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18627]
### Steps to reproduce the issue

Install [4.0Alpha] 
Edit the "Uncategorised" Category

### Expected result

No error

### Actual result
JUser: :_load: Unable to load user with ID: 589
![screen shot 2017-11-17 at 20 57 32](https://user-images.githubusercontent.com/400092/32968678-00ed37c8-cbda-11e7-9a65-989ead150cfe.png)

**Comment by ghost** [comment]
Can't confirm. 
![bildschirmfoto 2017-11-18 um 10 00 53](https://user-images.githubusercontent.com/8235763/32978680-6c9a5290-cc47-11e7-9d8b-b8fce2352172.jpg)

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18627">issues.joomla.org/tracker/joomla-cms/18627</a>.</sub>

**Comment by manojLondhe** [comment]
I got similar warning for different user id

![screenshot-manoj-php7 local-2017-11-18-16-41-39-252](https://user-images.githubusercontent.com/1375006/32982113-7e2e94ac-cc7f-11e7-838e-52282729ca42.png)


**Steps:**
- Installed 4.0 alpha1
- Installed sample data during installation
- Visited articles list
- Tried opening article for editing
- Got the warning

**Comment by manojLondhe** [comment]
Something to do with sample data installation? Works fine for newly created articles and categories. @PhilETaylor

**Comment by wilsonge** [comment]
It’s sample data install from the installer which is causing this. Looks like it’s failing to pick up the default user id correctly when it installs

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/issues/13864

**Comment by PhilETaylor** [comment]
Another day, another computer, new install, edit category "Uncategorised" and same error:

![screen shot 2017-11-18 at 20 40 08](https://user-images.githubusercontent.com/400092/32984549-adffb834-cca0-11e7-8398-8234f3f12628.png)

**Comment by wilsonge** [comment]
Yah - this is still an issue. I'm not sure what's going on here - need some time on this one. The user id should be stored in the session - but it's been lost in transit somewhere between the creation of the user on install and the page we install sample data on

**Comment by wilsonge** [comment]
Scrap that. I just found the issue. Fixed with 0b29110b28a5a587b8e0597aaa758b68da27c9ee
