### ISSUE TITLE
[4.0] WYSIWYG Editor "Menu" Button leads to 404

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18620]
### Steps to reproduce the issue

edit content on frontend
using the WYSIWYG Editor "Menu" Button, press that button

### Expected result

No errors

### Actual result
404 View not found [name, type, prefix]: items, html, menusView
![screen shot 2017-11-17 at 20 39 45](https://user-images.githubusercontent.com/400092/32967974-75592e62-cbd7-11e7-9af7-2adeed2818bc.png)

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18620">issues.joomla.org/tracker/joomla-cms/18620</a>.</sub>

**Comment by infograf768** [comment]
Same error as https://github.com/joomla/joomla-cms/issues/18621

@franz-wohlkoenig 
maybe we should consolidate these (there maybe other similar) as it is the same js error

**Comment by infograf768** [comment]
The one we should keep imho is
https://github.com/joomla/joomla-cms/issues/18618

**Comment by ghost** [comment]
closed in favor of #18618<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18620">issues.joomla.org/tracker/joomla-cms/18620</a>.</sub>
