### ISSUE TITLE
[4.0] Versions modal on frontend not working

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18626]
### Steps to reproduce the issue

install [4.0Alpha]
Edit an article on the frontend of the site
Click Versions button at bottom

### Expected result

Modal with versions shown

### Actual result

grey overlay loads for a fraction of a second as if the modal is loading
It then appears to go to home page (but the url is now http://example.com/index.php?a_id=2) 
on clicking the browser back button 

-- 
I have noticed if I use CMD+click on the versions button, a new tab opens to http://0.0.0.0:8010/index.php?a_id=2 and if I close that tab down, then the original page is shown and I see the following modal float in from the top:

![screen shot 2017-11-17 at 20 48 25](https://user-images.githubusercontent.com/400092/32968300-ad2a0c52-cbd8-11e7-8d74-cdeede2140a1.png)

Lastly note the unstyled close button.

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18626">issues.joomla.org/tracker/joomla-cms/18626</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #18679
