### ISSUE TITLE
[4.0] Tags on edit article on frontend not working

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18622]
### Steps to reproduce the issue

install [4.0Alpha] 
Edit an article on the frontend of the site
Click Publishing Tab

### Expected result

Be able to set tags for this article

### Actual result

a small text input with inability to focus it or enter data
![screen shot 2017-11-17 at 20 43 07](https://user-images.githubusercontent.com/400092/32968102-f1303cd8-cbd7-11e7-9fbd-844bfa8a03b7.png)

**Comment by ghost** [comment]
Issue confirmed as Fiels is to small. Type blind a Tag and save: Tag is shown.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18622">issues.joomla.org/tracker/joomla-cms/18622</a>.</sub>

**Comment by wilsonge** [comment]
I vaguely recall some old chosen issue if chosen was hidden on page load. anyone got a better memory than me?

**Comment by dgrammatiko** [comment]
As stated in other similar issues for J4 alpha, the fields will be moved to custom elements, so let's mark this as known issue as this is WIP for the javascript team

**Comment by C-Lodder** [comment]
Temporary fix (to allow the continuation of testing) until the field has been rewritten: https://github.com/joomla/joomla-cms/pull/18784

**Comment by ghost** [comment]
closed as having Pull Request #18784
