### ISSUE TITLE
[4.0] WYSIWYG Editor "Contact" Button leads to 404

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18621]
### Steps to reproduce the issue

edit content on frontend
using the WYSIWYG Editor "Contact" Button, press that button

### Expected result

No errors

### Actual result
![screen shot 2017-11-17 at 20 40 26](https://user-images.githubusercontent.com/400092/32968047-c0fdd64c-cbd7-11e7-8676-693b45b34582.png)

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18621">issues.joomla.org/tracker/joomla-cms/18621</a>.</sub>

**Comment by infograf768** [comment]
We have a js error

![screen shot 2017-11-20 at 10 48 59](https://user-images.githubusercontent.com/869724/33012189-7d41a0fe-cde0-11e7-85ca-01ca85549670.png)

**Comment by ghost** [comment]
closed in favor of #18618<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18621">issues.joomla.org/tracker/joomla-cms/18621</a>.</sub>
