### ISSUE TITLE
[4.0Alpha] <br/> in tooltip

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18628]
### Steps to reproduce the issue

Go to the featured articles in Joomla [4.0Alpha] admin
hover over the green ticks

### Expected result

popover saying

`Published and is Current. Start: 2017-11-17 19:57`

### Actual result

`Published and is Current.<br>Start: 2017-11-17 19:57`

(Sorry I cant screenshot it as it disappears) 

you can see it in the html though 
![screen shot 2017-11-17 at 20 59 39](https://user-images.githubusercontent.com/400092/32968772-65146b18-cbda-11e7-81f8-04a772055ec3.png)

**Comment by brianteeman** [comment]
Is this not a duplicate of #17255

**Comment by PhilETaylor** [comment]
i guess so - just another example of it
