### ISSUE TITLE
[4.0] non-styled buttons on editing article on frontend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18625]
### Steps to reproduce the issue

install [4.0Alpha]
Edit an article on the frontend of the site

### Expected result

Styled correctly

### Actual result

Note the incorrectly styled cancel and versions button

![screen shot 2017-11-17 at 20 44 41](https://user-images.githubusercontent.com/400092/32968186-32ed7ece-cbd8-11e7-81d2-d8e0ea6b5e4a.png)

### System information (as much as possible)

Google Chrome

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18625">issues.joomla.org/tracker/joomla-cms/18625</a>.</sub>

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/18775
