### ISSUE TITLE
[4.0] Install extension bug setDebug and getErrorMsg

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#18639]
Using:

		$db = JFactory::getDbo();
		$db->setDebug(0);

in an installation script produces:

0 Call to undefined method Joomla\Database\Mysqli\MysqliDriver::setDebug()

Looking at:
libraries/joomla/database/driver.php

setDebug isn't deprecated so should still be supported.

Also same for getErrorMsg().

**Comment by mbabker** [comment]
Needs to be deprecated in 3.x.  The Framework removed the concept of a debug mode in the database drivers in the major version bump.

**Comment by wilsonge** [comment]
`getErrorMsg` is already deprecated https://github.com/joomla/joomla-cms/blob/3.8.2/libraries/joomla/database/database.php#L60

I've now deprecated the `setDebug` function with https://github.com/joomla/joomla-cms/commit/3e4966fe26e749a63c5112d9188c9aa10ed8e9b5 in the 3.9 branch
