### ISSUE TITLE
[4.0] Installation Footer links

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#18635]
Footer links are blue on blue, hard to see. Advise changing to white and bold as per attached.

Before:
<img width="407" alt="screen shot 2017-11-17 at 21 54 42" src="https://user-images.githubusercontent.com/1400982/32970703-f4006190-cbe1-11e7-93da-349c7bf8035d.png">

After:
<img width="418" alt="screen shot 2017-11-17 at 21 54 15" src="https://user-images.githubusercontent.com/1400982/32970669-e050a970-cbe1-11e7-8606-338d4f296528.png">

NOTE, This was on the installer.

**Comment by brianteeman** [comment]
Updated title to show its for the installation template

**Comment by mbabker** [comment]
I wouldn't use white unless the underlines are put back in otherwise there is no visual indication those are links.

**Comment by brianteeman** [comment]
agree - that would be an a11y fail

**Comment by tonypartridge** [comment]
So just live them unreadable instead 😂.

**Comment by mbabker** [comment]
Should be readable.  But just don't make it blend in to the rest of the text so you can't distinguish the links from the plain text is all I'm saying.

**Comment by C-Lodder** [comment]
@franz-wohlkoenig please re-open

**Comment by ghost** [comment]
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18635">issues.joomla.org/tracker/joomla-cms/18635</a>.</sub>

**Comment by tonypartridge** [comment]
closed as we have a pr.
