### ISSUE TITLE
[4.0] Warning: Invalid argument supplied for foreach()  QuickIconHelper.php on line 102

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18630]
### Steps to reproduce the issue

No idea. it just "appeared" during testing. 
I think it was caused by Archiving all articles - yes, that.. 

### Expected result

No errors 

### Actual result

Warning: Invalid argument supplied for foreach() in /joomla-cms-4.0.0-alpha1/administrator/modules/mod_quickicon/Helper/QuickIconHelper.php on line 102

![screen shot 2017-11-17 at 21 06 35](https://user-images.githubusercontent.com/400092/32968998-352a935e-cbdb-11e7-95f2-cb73b7c1ca39.png)

**Comment by ghost** [comment]
Can't confirm. Archived all Sample Data-Articles, didn't get Warning.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18630">issues.joomla.org/tracker/joomla-cms/18630</a>.</sub>

**Comment by mbabker** [comment]
Any extensions installed?  That data comes from plugins hooking the `onGetIcons` event so a plugin would have to be returning a non-iterable result.

**Comment by ghost** [comment]
@mbabker test on Installation out of the Box.

**Comment by C-Lodder** [comment]
@PhilETaylor you still have this error with the quickicons?

**Comment by PhilETaylor** [comment]
to replicate it I was just randomly doing things to "break it" - see the other issues raised on the same day, I just tried again today and I cannot get it to happen now.
