### ISSUE TITLE
[4.0] Left Border missing of boxes and buttons?

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#18637]
See attached, left border is missing...
<img width="406" alt="screen shot 2017-11-17 at 22 05 47" src="https://user-images.githubusercontent.com/1400982/32971086-95eff94c-cbe3-11e7-92ba-2adff8b0f38c.png">
<img width="414" alt="screen shot 2017-11-17 at 22 05 38" src="https://user-images.githubusercontent.com/1400982/32971088-98392a7a-cbe3-11e7-8d1f-f3265fe8a555.png">

**Comment by ghost** [comment]
how do you get this? Got:
![bildschirmfoto 2017-11-18 um 08 42 48](https://user-images.githubusercontent.com/8235763/32978150-8d41bc28-cc3c-11e7-8e9a-7dfb776aa7cc.jpg)
