### ISSUE TITLE
[J4.0] - Padding in boxes inconsistant

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#18636]
See attached, looks a bit whacky. Padding top, side and bottom should be equal imho.

<img width="1655" alt="screen shot 2017-11-17 at 21 55 53" src="https://user-images.githubusercontent.com/1400982/32970755-24d2b5ca-cbe2-11e7-9351-bcd596ef4465.png">

**Comment by brianteeman** [comment]
I am going to close this as this is not the template that will be used and is just temporary. Unfortunately the UX team have massively delayed its implementation

**Comment by tonypartridge** [comment]
:-( not great to release an Alpha for people to test with a template thats not even going to be used; Nevermind, will stop testing.

**Comment by brianteeman** [comment]
no argument from me on that one!!

**Comment by brianteeman** [comment]
> There is one goal for this release: to allow advance testing of custom extensions so that extension developers can report any problems well before the final release.

**Comment by tonypartridge** [comment]
I see that, but it’s been Globally announced. People are playing with it who are not developers.

The developers can just clone from git.... I’m actually concerned what the negative impact could be now 🤔

**Comment by brianteeman** [comment]
that was a quote from social media - maybe @wilsonge or @mbabker can revise the announcement to make it much much clearer the intent of this release

**Comment by infograf768** [comment]
Do you mean that atum is just a temporary template? If yes, this should be public knowledge and specially for bugsquad.
