### ISSUE TITLE
[4.0] Invalid Password field order color on Login page

### ISSUE THREAD

**Issue by Saurabh1** [joomla/joomla-cms#18634]
With the Sample Data installed, I went to login page and tried to login but even without anything entered on password field it should show with the invalid red colored border but it takes precision from Valid class. 

Also when it is not valid, I still see the green border beneath of the red one. 
![screen shot 2017-11-17 at 21 45 39](https://issues.joomla.org/uploads/1/ec855130ce23e6c6aef06a8e8c4d0d57.png)

### Expected result
It should be with the red border only.

### Actual result
Shows with the green color border without any input

### System information (as much as possible)
Joomla 4.0 Alpha
macOS High Sierra 10.13.1
Browser:Firefox Quantum 57.0

**Comment by ghost** [comment]
Depends on Browser:
### Firefox (note red+green Border at "Password")
![ff](https://user-images.githubusercontent.com/8235763/32978453-cc35491c-cc42-11e7-8eb6-e36ce8ab31ce.jpg)
### Safari, Chrome
![safari chrome](https://user-images.githubusercontent.com/8235763/32978457-d8669880-cc42-11e7-94ca-e5bbf89a0335.jpg)
### System information
4.0.0-dev
macOS Sierra, 10.12.6
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by dgrammatiko** [comment]
well the border should be either red or green, I guess we just introduce quantum states with J4!

**Comment by brianteeman** [comment]
i cannot replicate this

**Comment by ghost** [comment]
Can't confirm too:

![screen shot 2018-08-19 at 12 22 01](https://user-images.githubusercontent.com/8235763/44307864-8cfda100-a3aa-11e8-8649-7958dcffe9f0.jpg)

**Comment by ghost** [comment]
Closed due the lack of response.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18634">issues.joomla.org/tracker/joomla-cms/18634</a>.</sub>
