### ISSUE TITLE
[4.0] Type error when changing tabs when editing an article

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#18642]
Edit or create an article
Switch tabs

Result
<img width="830" alt="screen shot 2017-11-18 at 07 38 08" src="https://user-images.githubusercontent.com/869724/32977736-a10bda44-cc33-11e7-9b31-8e5c6a7c698b.png">

**Comment by PhilETaylor** [comment]
Flying focus is broken site wide in my tests I just ignored it as its a known issue apparently.

**Comment by infograf768** [comment]
See https://issues.joomla.org/tracker/joomla-cms/18649

**Comment by infograf768** [comment]
This has been solved. Closing
