### ISSUE TITLE
[4.0] Selecting articles manager throws a js error

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#18644]
Result

<img width="1179" alt="screen shot 2017-11-18 at 07 48 43" src="https://user-images.githubusercontent.com/869724/32977799-f9a15b06-cc34-11e7-84fc-a1f8fa767e21.png">

**Comment by infograf768** [comment]
Same error for Featured Manager

**Comment by wilsonge** [comment]
Fixed with d891e2be3c2da2f063d07a94f8efaf784227e322
