### ISSUE TITLE
[4.0] flying-focus.js source and minified versions are different

### ISSUE THREAD

**Issue by Fedik** [joomla/joomla-cms#18649]
flying-focus.js source and minified versions are different, 
that why we still have that flying-focus.js error on every page.

I guess it is build failure.
Can be that other scrips/styles also has difference.

**Comment by infograf768** [comment]
I confirm that when in debug mode I do not get the error in https://github.com/joomla/joomla-cms/issues/18642<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18649">issues.joomla.org/tracker/joomla-cms/18649</a>.</sub>

**Comment by C-Lodder** [comment]
Hmm, I cannot seem to replicate this console log error. Next time you see if, please load the uncompressed JS file and report the error back.

**Comment by infograf768** [comment]
That is exactly what I have done by using debug mode

**Comment by Fedik** [comment]
@C-Lodder  that what we meant, uncompressed works fine, but minified are broken 😉 

just compare the files from the 4.0-Alfa archive, they are different version of "flying-focus" js,
same in 4.0-dev branch

**Comment by C-Lodder** [comment]
@Fedik I've tried about 10-15 views in the backend with debug mode enabled and disabled. I still cannot see any error

**Comment by C-Lodder** [comment]
@Fedik @infograf768 can you try this file and let me know if it works?

[flying-focus.min.zip](https://github.com/joomla/joomla-cms/files/1485490/flying-focus.min.zip)

**Comment by infograf768** [comment]
My test was done before the release of alpha and recent PRs in the 4.0-dev branch.
I can't reproduce the issue right now. Will test with this file.

**Comment by Fedik** [comment]
I see,
it was fixed in https://github.com/joomla/joomla-cms/commit/c50e9458ea196423a5f048d1ba903addde7491c4 by @wilsonge while fixing another issue 😄 

I am closing here
