### ISSUE TITLE
[4.0] Left menu doesn't work on install error.

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#18640]
If an error occurred i.e. see attached. The left menu doesn't function, we need to click return to control panel to proceed. 

<img width="1497" alt="screen shot 2017-11-17 at 22 29 43" src="https://user-images.githubusercontent.com/1400982/32971824-039e8a64-cbe7-11e7-80bb-631de6af9d5a.png">

**Comment by ghost** [comment]
Confirmed. This happens also if you try to create a new com_field for Content.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18640">issues.joomla.org/tracker/joomla-cms/18640</a>.</sub>

**Comment by mbabker** [comment]
Can't duplicate.  Sidebar working fine on error page here.  With and without debug mode.

**Comment by C-Lodder** [comment]
@tonypartridge - do you get any errors on the browser console?

**Comment by ghost** [comment]
Can't duplicate own [Error](https://github.com/joomla/joomla-cms/issues/18640#issuecomment-345428150) anymore.

**Comment by C-Lodder** [comment]
@tonypartridge - can you confirm the issue still occurs?

**Comment by tonypartridge** [comment]
@C-Lodder can't recreate so closing.
