### ISSUE TITLE
[4.0] Select user does not display the modal

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#18643]
### Steps to reproduce the issue

EDit an article, Go to Publishing tab. Try to change the Created by user

Modal to choose user does not display

**Comment by infograf768** [comment]
NOte: Same issue to select an image
<img width="580" alt="screen shot 2017-11-18 at 07 44 28" src="https://user-images.githubusercontent.com/869724/32977776-5cdba650-cc34-11e7-983a-1b131ca83a3c.png">

+ weird text in box

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18643">issues.joomla.org/tracker/joomla-cms/18643</a>.</sub>

**Comment by wilsonge** [comment]
@dgt41 has been working on a fix for this

**Comment by dgrammatiko** [comment]
@infograf768 please mention your browsers for any css or js issues, thanks

**Comment by wilsonge** [comment]
It works in chrome but not in firefox

**Comment by infograf768** [comment]
firefox indeed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18643">issues.joomla.org/tracker/joomla-cms/18643</a>.</sub>

**Comment by ghost** [comment]
My Test was on:
### System information
4.0.0-dev
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by dgrammatiko** [comment]
This should been fixed with #18706

**Comment by ghost** [comment]
closed as fixed by #18706<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18643">issues.joomla.org/tracker/joomla-cms/18643</a>.</sub>
