### ISSUE TITLE
[4.0] mod_footer & plg_extension_namespacemap appear as discoverable

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#18647]
### Steps to reproduce the issue
Install a clean j4.0
Go to Extensions: Discover

Both extensions display as discoverable although they exist already in db (weird as they are not present in joomla.sql)

Editing db to set their state from -1 to 0 in the _extensions table solves the issue

**Comment by ghost** [comment]
duplicate Report #18602?

**Comment by brianteeman** [comment]
Closed as a duplicate
