### ISSUE TITLE
[4.0] Selecting Articles: fields manager throws a js error

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#18645]
<img width="1197" alt="screen shot 2017-11-18 at 07 51 32" src="https://user-images.githubusercontent.com/869724/32977817-56b3b7a8-cc35-11e7-8541-1ef4ab218984.png">

**Comment by wilsonge** [comment]
Fixed with d891e2be3c2da2f063d07a94f8efaf784227e322
