### ISSUE TITLE
[4.0] Registry::getInstance(); replacement?

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#18641]
What is the desired replacement for Registry::getInstance(); ?

**Comment by mbabker** [comment]
```php
use Joomla\Registry\Registry;

new Registry;
```

The registry no longer supports singleton instances and the method was removed.  See https://github.com/joomla-framework/registry/blob/2.0-dev/docs/v1-to-v2-update.md for more updates related to the Registry package.
