### ISSUE TITLE
[4.0] Error when opening TinyMCE Plugin

### ISSUE THREAD

**Issue by coolman01** [joomla/joomla-cms#18650]
### Steps to reproduce the issue

Open the plugin

### Expected result

Various setting can be chosen and set

### Actual result

Error Message - see image

### System information (as much as possible)

PHP Built On | Windows NT DJ-DESKTOP 10.0 build 15063 (Windows 10) i586
Database Version | 5.5.5-10.1.9-MariaDB
Database Collation | utf8_general_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.0.4
Web Server | Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.4
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

### Additional comments

![tinymce](https://user-images.githubusercontent.com/6746747/32979148-2c1a9cee-cc50-11e7-9556-f01ad2f88bc3.jpg)

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18650">issues.joomla.org/tracker/joomla-cms/18650</a>.</sub>

**Comment by Fedik** [comment]
I will do PR, need a minute

**Comment by Fedik** [comment]
please test #18652

**Comment by ghost** [comment]
closed as having Pull Request #18652
