### ISSUE TITLE
"News Feed Categories" Button in 4.0 leads to blank page

### ISSUE THREAD

**Issue by coolman01** [joomla/joomla-cms#18657]
### Steps to reproduce the issue

Click on "News Feed Categories" in "All Front End Views" Menu

### Expected result

Info about and/or List of categories

### Actual result

Blank page

### System information (as much as possible)

PHP Built On | Windows NT DJ-DESKTOP 10.0 build 15063 (Windows 10) i586
Database Version | 5.5.5-10.1.9-MariaDB
Database Collation | utf8_general_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.0.4
Web Server | Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.4
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by mbabker** [comment]
Fixed via https://github.com/joomla/joomla-cms/commit/43c2847062e3a6dfbdd5a5da3841c209b54af9d0
