### ISSUE TITLE
[4.0] Error when submitting a Registration on frontend

### ISSUE THREAD

**Issue by coolman01** [joomla/joomla-cms#18654]
### Steps to reproduce the issue

Frontend Login Module, select "Create an account"
Fill out form and click "Register"

### Expected result

Registration confirmed message

### Actual result

Error message (see Image)

### System information (as much as possible)

PHP Built On | Windows NT DJ-DESKTOP 10.0 build 15063 (Windows 10) i586
Database Version | 5.5.5-10.1.9-MariaDB
Database Collation | utf8_general_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.0.4
Web Server | Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.4
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

### Additional comments
There is also a message mentioning email not being available. As I'm testing on my local maschine and XAMPP - this may be the cause. I don't know.

![registration-submission](https://user-images.githubusercontent.com/6746747/32979426-5d1b7de0-cc55-11e7-9ca0-4533e9954743.jpg)

**Comment by ghost** [comment]
Issue confirmed, but new User is generated ("Enabled" and "Activated" are blocked).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18654">issues.joomla.org/tracker/joomla-cms/18654</a>.</sub>

**Comment by ghost** [comment]
@coolman01 can you please add `[4.0] ` at Beginning of Title if you report an 4.0-Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18654">issues.joomla.org/tracker/joomla-cms/18654</a>.</sub>

**Comment by coolman01** [comment]
OK - sorry. Will do.

**Comment by infograf768** [comment]
There is a js error + some files load
![screen shot 2017-11-18 at 12 00 49](https://user-images.githubusercontent.com/869724/32979588-34c883f8-cc58-11e7-93fd-6fd73c40e7fd.png)


It also concerns forgot username and password.

**Comment by mbabker** [comment]
Mail sending in core in general needs improved error handling, mail sending errors should be caught and handled and not result in a 500 page.

This should also be fixed in 3.x, not just 4.0 (basically calls to `JFactory::getMailer()->sendMail()` should be wrapped in a try/catch for a `RuntimeException`).

**Comment by infograf768** [comment]
The 404 exists for New Registration, Forgot Username and Forgot your password **when there are NO menu items for these.** Otherwise the Login Form Module uses the menu items.

Even when we do have menu items (below aliases are `registration` and `user-password-remind`, the urls are not very nice:
```
http://localhost:8888/joomla40/registration?view=registration
http://localhost:8888/joomla40/user-password-remind?view=remind
```
Looks like we have some router issues.

**Comment by brianteeman** [comment]
@Hackwar could you look at this confirmed routing issue please

**Comment by ghost** [comment]
@Hackwar do you have the Comment above on your Radar?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18654">issues.joomla.org/tracker/joomla-cms/18654</a>.</sub>

**Comment by Hackwar** [comment]
The system currently does not throw a 404. Somehow the current Itemid is added to the URL, even though it shouldn't, but that is a different issue.

**Comment by ghost** [comment]
@Hackwar thanks for Comment.

**Comment by alikon** [comment]
is this still an issue ?

**Comment by Quy** [comment]
I get alerts and not the error page as reported. 

![registration](https://user-images.githubusercontent.com/368084/59320359-eceb6e00-8c82-11e9-9c83-e0872c88660b.jpg)

**Comment by Quy** [comment]
Closing as non-reproducible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18654">issues.joomla.org/tracker/joomla-cms/18654</a>.</sub>
