### ISSUE TITLE
[4.0] "Archived Articles" leads to error page

### ISSUE THREAD

**Issue by coolman01** [joomla/joomla-cms#18655]
### Steps to reproduce the issue

Click on "Archived Articles" in "All Front End Views" leads to Error Page in Joomla 4.0

### Expected result

Shows archived articles

### Actual result

Error page including mesage "Class 'Joomla\Component\Content\Site\Model\JFactory' not found"

### System information (as much as possible)
 
PHP Built On | Windows NT DJ-DESKTOP 10.0 build 15063 (Windows 10) i586
Database Version | 5.5.5-10.1.9-MariaDB
Database Collation | utf8_general_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.0.4
Web Server | Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.4
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
![page-not-found](https://user-images.githubusercontent.com/6746747/32979489-5afa1bf6-cc56-11e7-9226-8d65c7945780.jpg)

**Comment by ghost** [comment]
Issue confirmed.

@coolman01 can you please add `[4.0] ` at Beginning of Title if you report an 4.0-Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18655">issues.joomla.org/tracker/joomla-cms/18655</a>.</sub>

**Comment by mbabker** [comment]
Fixed via https://github.com/joomla/joomla-cms/commit/8dfc4c0b1fda000bebe6a041d4c6e13fb7599e83
