### ISSUE TITLE
[4.0] Idea: UX Improvement "Post-Installation messages button"

### ISSUE THREAD

**Issue by conconnl** [joomla/joomla-cms#18659]
### Idea for a little improvement in the UX

There is a nice Post-Installation messages button, but this only displays the messages and does not have a remove button.
When you click on the message you go the component where you can hide the message, but not to the message you click on.

![ux improvement](https://user-images.githubusercontent.com/11913918/32980144-bbccb85c-cc61-11e7-9390-0a0cb08ff9cf.png)

**Comment by ghost** [comment]
changed Title to get more clear where Improvement is meant.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18659">issues.joomla.org/tracker/joomla-cms/18659</a>.</sub>

**Comment by coolcat-creations** [comment]
I would actually put post installation messages on a site after the installation and not always in the top bar...

**Comment by brianteeman** [comment]
As the message is truncated in the dropdown it would be a complete failure of the message if we allow it to be "deleted" in the dropdown

**Comment by ghost** [comment]
Please add Label "J4 Backend Template".

**Comment by brianteeman** [comment]
Please can this be closed. It defeats the objective of having the messages in the first place as we want people to read the entire message - not just the snippet shown in the dropdown
