### ISSUE TITLE
[4.0] Clicking on "Related Items" on frontend leads to error message

### ISSUE THREAD

**Issue by coolman01** [joomla/joomla-cms#18653]
### Steps to reproduce the issue

Click on the "related Items" Menu item in the All-Modules menu on the frontend

### Expected result

Display content

### Actual result

Displays content with error message (see image)

### System information (as much as possible)

PHP Built On | Windows NT DJ-DESKTOP 10.0 build 15063 (Windows 10) i586
Database Version | 5.5.5-10.1.9-MariaDB
Database Collation | utf8_general_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.0.4
Web Server | Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.4
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

![related-items](https://user-images.githubusercontent.com/6746747/32979314-2add4ae0-cc53-11e7-807c-52243f5951ef.jpg)

**Comment by ghost** [comment]
~~Can't confirm.~~
Issue confirmed (Firefox didn't show Message but block empty Space)
![bildschirmfoto 2017-11-18 um 11 42 39](https://user-images.githubusercontent.com/8235763/32979447-a5a70d04-cc55-11e7-9746-05b2c73995ca.jpg)

### System information
4.0.0-dev
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18653">issues.joomla.org/tracker/joomla-cms/18653</a>.</sub>

**Comment by wilsonge** [comment]
Fixed with 33a61f29404e7f98348dadd9fdaed1ddf8387a9b

Thanks :)
