### ISSUE TITLE
[4.0] Installer rejects emails with +

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#18668]
### Steps to reproduce the issue

I have tried to install joomla-cms-4.0.0-alpha1 with an email that includes + (anibal.sanchez+j4@ex....), but it rejected the email.

### Expected result

Acceptance of + emails in the installation process.

**Comment by mbabker** [comment]
1) Regression from 3.x, using `admin+foo@localhost.test` for install on both versions and it works on 3.x
2) For mine, it is failing in the EmailRule after the address is [converted to punycode](https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Form/Rule/EmailRule.php#L72-L79)

**Comment by infograf768** [comment]
Concerning punycode mails. 
I can't reproduce the issue when doing a clean install of 4.0-dev branch.

It also works fine in Users Manager
When creating new user through Users Manager an email of the type admin@джумла-тест.рф is or admin+foo@localhost.test is accepted OK
No success message though.

can you folks test with latest branch?

**Comment by ghost** [comment]
Works as expected:
![bildschirmfoto 2017-11-19 um 18 17 39](https://user-images.githubusercontent.com/8235763/32993279-0214616c-cd56-11e7-9507-d0611bf6ee4b.jpg)
### System information
4.0.0-dev
Multilanguage Site (4 Lang.) & Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by dgrammatiko** [comment]
What @anibalsanchez experienced (i was next to him when that happened) was a failure in the client side, so something either on the punycode or the validation needs some love

**Comment by infograf768** [comment]
I can't either reproduce when Creating an account or editing a profile in frontend

**Comment by anibalsanchez** [comment]
I've just tested on the latest J4 A2, and the issue remains.

* NOTE: The error is reported at the top of the page, after you click on "**Install Joomla**"
* So, it looks like the email is accepted, but it is validated and rejected in the final step

![screenshot from 2017-11-24 09-39-54](https://user-images.githubusercontent.com/385780/33202188-da8c6384-d0fb-11e7-9be5-e7369bab5385.png)

**Comment by anibalsanchez** [comment]
Checking the validator, the value of the field has a space instead of +, so something else is going before the validation.

**Comment by brianteeman** [comment]
I can no longer replicate this in the installer. I can only assume it was resolved elsewhere so I shall close it. If I am mistaken it can always be reopened
