### ISSUE TITLE
[4.0] Installer shows errors at the top of the page only

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#18669]
### Steps to reproduce the issue

Every step of the installation is shown below the previous steps, but the errors of the process are shown at the top of the page.

For example, when I tried to install joomla-cms-4.0.0-alpha1, and entered an invalid email, there was no indication of the error in the current step .... after looking for what was going on I found the error at the top of the page.
 

### Expected result

A clear error where the user can find it at first glance

**Comment by Quy** [comment]
I couldn't produce an error to see where it is displayed. Is this still valid issue with the nightly build?

**Comment by Quy** [comment]
Please provide screenshot.

**Comment by anibalsanchez** [comment]
It's working fine on J4 Alpha6. Closing the issue. Txs @brianteeman
