### ISSUE TITLE
[4.0] Warnings on Joomla-Update

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#18670]
### Steps to reproduce the issue
Open Joomla-Update: 

1/3: Warning: array_filter() expects parameter 2 to be a valid callback, class `JoomlaupdateModelDefault' not found in /Applications/MAMP/htdocs/4/administrator/components/com_joomlaupdate/Model/UpdateModel.php on line 1315

2/3: Warning: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/4/administrator/components/com_joomlaupdate/Model/UpdateModel.php on line 1317

![bildschirmfoto 2017-11-18 um 16 47 13](https://user-images.githubusercontent.com/8235763/32982198-c2be6452-cc80-11e7-922b-0fb79c8869e7.jpg)

3/3: Warning: Invalid argument supplied for foreach() in /Applications/MAMP/htdocs/4/administrator/components/com_joomlaupdate/tmpl/joomlaupdate/default_preupdatecheck.php on line 109

![bildschirmfoto 2017-11-18 um 16 53 46](https://user-images.githubusercontent.com/8235763/32982231-4566dce0-cc81-11e7-80f5-56a93cb54b49.jpg)

### System information
4.0.0-dev
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by mbabker** [comment]
Fixed via https://github.com/joomla/joomla-cms/commit/090fd108ae7578fdf53d0610068400d8b7323f49
