### ISSUE TITLE
[4.0] Sample Data-Tag "Red" show "Fatal Error"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#18673]
### Steps to reproduce the issue
Click on Tag "Red" (/index.php/tagged-items) got in Source Code:

```
<div class="tagspopular">
	<ul>
		<li>
		<a href="<br />
<b>Fatal error</b>:  Cannot declare class TagsHelperRoute, because the name is already in use in <b>/Applications/MAMP/htdocs/4/components/com_tags/helpers/route.php</b> on line <b>17</b><br />
```
![bildschirmfoto 2017-11-18 um 17 20 33](https://user-images.githubusercontent.com/8235763/32982447-5052faf4-cc85-11e7-960f-f6d213be11ac.jpg)
### System information
4.0.0-dev
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by wilsonge** [comment]
I can't reproduce this on the latest 4.x branch :(

**Comment by ghost** [comment]
will try Tomorrow using nightly build.

**Comment by ghost** [comment]
closed as Issue is solved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18673">issues.joomla.org/tracker/joomla-cms/18673</a>.</sub>
