### ISSUE TITLE
[4.0] [com_config] Tooltips are missing for many fields

### ISSUE THREAD

**Issue by manojLondhe** [joomla/joomla-cms#18671]
### Steps to reproduce the issue
- Login and goto [jroot]/administrator/index.php?option=com_config
- Check various fields on the form
- Tooltips are missing for many of those fields

### Expected result
- Config should have tooltips for all fields, so users don't mess up with settings unknowingly 

### Actual result
- Config form has tooltips missing for many fields

### System information (as much as possible)
--

### Additional comments
--

**Comment by wilsonge** [comment]
This is by design :) We are removing tooltips from fields that had no constructive value. Many of the tooltips just repeated what was in the label. If you think there are any missing descriptions let me know and we can write something up!
