### ISSUE TITLE
[4.0Alpha] Cannot create new newsfeed.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18680]
### Steps to reproduce the issue

install [4.0Alpha] 
go to Newsfeeds
Click New 
set title = test
set link = test
click save

### Expected result

no errors

### Actual result

Call to a member function load() on boolean

![screen shot 2017-11-18 at 19 58 49](https://user-images.githubusercontent.com/400092/32984244-e7a02944-cc9a-11e7-88f1-a97caa5764ab.png)

### System information (as much as possible)

Unique ID	707d2b7806a60debd39e54bb17bfc8cf98c6de6f
PHP Version	7.1.11
DB Type	mysqli
DB Version	5.7.20
CMS Version	4.0.0
Server OS	Darwin 17.3.0

**Comment by wilsonge** [comment]
Fixed with 337da5e1bd870b9f9df9f2fa1229ab4bc3a32d59
