### ISSUE TITLE
[4.0] Intermittent "loss" of /administrator/ in urls

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18683]
### Steps to reproduce the issue

I have had this issue on [4.0Alpha] on two separate machines on two different days

while navigating the admin console, reporting bugs, occasionally some links "lose" the /administrator/ in the url, and so then go to load a frontend url

its odd

Currently if im in admin (brand new install, only logged 2 bugs since installing) and click Content -> Articles I get to url http://0.0.0.0:8010/index.php?option=com_content which is a frontend url and not an admin url... 

very very strange

The URL is currently `http://0.0.0.0:8010/administrator#collapse7`

Note the missing last / 

the HTML of the admin menu starts with `href="index.php....`

The combination of those two means that the frontend loads.

if you manually change the url to include a trailing / like 

`http://0.0.0.0:8010/administrator/#collapse7`

Then the links all work right

Might be something to do with running with the PHP internal development server? But it is certainly a bug that needs resolving somewhere.

**Comment by PhilETaylor** [comment]
Confirmed. 

Got to http://0.0.0.0:8010/administrator (running with PHP Internal Development server) 

This url doesnt redirect to anywhere. The admin console loads fine. 

Then use any left menu item, the first click adds a fragment like #collapse7 and then the click on a menu link takes you to the frontend, and 404's

**Comment by wilsonge** [comment]
I've not ever seen this debugging 4.0 - so it's either gotta be server side or client side. I'm running chrome 62.0.3202.94 on 

```

PHP Built On | Darwin Georges-MacBook-Pro-2.local 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct 4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64
-- | --
Database Version | 5.5.5-10.2.9-MariaDB
Database Collation | utf8_general_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.0.22
Web Server | Apache/2.4.27 (Unix) PHP/7.0.22
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
```

Let's figure out the difference :)

**Comment by brianteeman** [comment]
Going to close this one at this time

**Comment by PhilETaylor** [comment]
yup - it seems whatever routing issue I had has magically disappeared
