### ISSUE TITLE
[4.0Alpha] Content categories link goes to 404

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18682]
### Steps to reproduce the issue

install [4.0Alpha]
Go to content -> categories in admin console

### Expected result

list of categories

### Actual result

404 Component not found.

on
http://0.0.0.0:8010/index.php?option=com_categories&extension=com_content

**Comment by wilsonge** [comment]
I can't reproduce this one. I have the URL http://localhost/~george/joomla-cms/administrator/index.php?option=com_categories&extension=com_content (which is the same as yours) but this works fine for me and correctly resolves

**Comment by PhilETaylor** [comment]
note the missing /administrator/ in my url - so yes, related to https://github.com/joomla/joomla-cms/issues/18683 and this one can be closed too.
