### ISSUE TITLE
[4.0Alpha] Newsfeed categories link goes to 404

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18681]
### Steps to reproduce the issue

install [4.0Alpha] 
Go to Newsfeed categories in admin console 

### Expected result

view with categories/no categories
No errors

### Actual result

404 Component not found.

### System information (as much as possible)

Unique ID	707d2b7806a60debd39e54bb17bfc8cf98c6de6f
PHP Version	7.1.11
DB Type	mysqli
DB Version	5.7.20
CMS Version	4.0.0
Server OS	Darwin 17.3.0

**Comment by wilsonge** [comment]
I can't reproduce this either. I assume this is the same kinda issue as the content categories view which works for me and not you too?

**Comment by PhilETaylor** [comment]
its now working... I think this might be related to https://github.com/joomla/joomla-cms/issues/18683 I'll keep an eye on the urls from now on.

**Comment by PhilETaylor** [comment]
closing as confirmed https://github.com/joomla/joomla-cms/issues/18683 is the reason for this

**Comment by wilsonge** [comment]
OK I'll close for now :) We can reopen if we can find a way to reproduce
