### ISSUE TITLE
[4.0] Edge browser lower left link issue

### ISSUE THREAD

**Issue by ot2sen** [joomla/joomla-cms#18687]
### Steps to reproduce the issue
At administrator page we have a link left bottom to go to site. When using Edge the hover of the link for to click it does show the description helpful link URL at same location left bottom. (You will see the same descriptive link URL when hovering the joomla logo/link middle bottom of the admin login page)
(Also a problem in J3.8.x)

### Expected result
Be able to click the link

### Actual result
Link to Site hides behind the descriptive link URL making it difficult to actually click the link.

### System information (as much as possible)
J4 Alpha1
Edge browser latest.
![18-11-2017_j4_edge_bottomleft](https://user-images.githubusercontent.com/790445/32984629-6933fb98-ccaa-11e7-9cde-70f3e99862a9.png)
![18-11-2017_j4_edge_bottomleft_onhoverlink](https://user-images.githubusercontent.com/790445/32984630-695d92be-ccaa-11e7-8095-d176a9ec9945.png)

**Comment by mbabker** [comment]
Sounds like a browser bug to me.

**Comment by C-Lodder** [comment]
Yup, this is an issue within the browser, not Joomla

**Comment by ghost** [comment]
closed as no Core-Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18687">issues.joomla.org/tracker/joomla-cms/18687</a>.</sub>
