### ISSUE TITLE
[4.0] Menu ordering

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18689]
I think this might be closed as a "admin template is not the one that will be used" however it might well be a bug too, as well as useability

However... currently the left menu is being duplicated in the content area too..

And that duplication is also in a different order of menu items 

![screen shot 2017-11-18 at 20 59 33](https://user-images.githubusercontent.com/400092/32984710-6ff6822c-cca3-11e7-8ea4-f68e2c15d0cf.png)

**Comment by mbabker** [comment]
It's the same state as the 3.x template, just more visible with the sidebar menu versus top menu.  What you're seeing is the main menu then the component's sidebar navigation.

**Comment by ghost** [comment]
similar #14539

**Comment by brianteeman** [comment]
Closing as the admin menu setup is being designed by the ux team

**Comment by PhilETaylor** [comment]
Isnt that the same excuse that has been used for years? have we actually seen any thing from the ux team actually be delivered in any release?
