### ISSUE TITLE
[4.0] Menu reordering?

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18688]
If "content" is the most important part of a Joomla site, then why are we burying the content menu item in Joomla Admin so much.

Surely its more important than System, Users, Menus and Media?

Thoughts .... 

![screen shot 2017-11-18 at 20 55 42](https://user-images.githubusercontent.com/400092/32984683-02d6523a-cca3-11e7-8a50-09c1ac6d8eef.png)

**Comment by ghost** [comment]
closed as duplicate Issue #14539. Please comment on this Issue, thanks.
