### ISSUE TITLE
[4.0] Cannot create new menu type with preset

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18684]
### Steps to reproduce the issue

install [4.0Alpha] 
attempt to create a new menu type, selecting 
 - client = administrator 
 - import a preset = joomla
click save

### Expected result

No errors

### Actual result

![screen shot 2017-11-18 at 20 11 58](https://user-images.githubusercontent.com/400092/32984339-bf008428-cc9c-11e7-8ebe-0a48aa16581c.png)

### System information (as much as possible)

Unique ID	707d2b7806a60debd39e54bb17bfc8cf98c6de6f
PHP Version	7.1.11
DB Type	mysqli
DB Version	5.7.20
CMS Version	4.0.0
Server OS	Darwin 17.3.0

**Comment by izharaazmi** [comment]
Are you able to replicate this on 3.x staging?

**Comment by ghost** [comment]
Got same Issue as @PhilETaylor on 4.0 using Presets "Joomla" or "Modern", in 3.8.3-dev works as expected.

The Menu is created: Create a new Menu with "failed" Name got Message that a Menu using this name exists (can't display Menu cause #18815).

![bildschirmfoto 2017-11-25 um 08 29 21](https://user-images.githubusercontent.com/8235763/33228404-d1d0d508-d1ba-11e7-898a-5c6f1b04013d.jpg)

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18684">issues.joomla.org/tracker/joomla-cms/18684</a>.</sub>

**Comment by astridx** [comment]
Can confirm this issue in the current 4.0-dev branch
![menus edit tes administration 1](https://user-images.githubusercontent.com/9974686/36944184-54b0cf8a-1f97-11e8-81da-cf4082d255b4.png)

**Comment by brianteeman** [comment]
@izharaazmi  can you take a look at this error please
> Menu was saved but failed to import the preset: 42000, 1064, You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') GROUP BY c2.`id`) AS c2 ON c2.newId = c.`id` SET `published` = c2.newPublish' at line 6

**Comment by izharaazmi** [comment]
Sure, I'll look at it earliest possible.

**Comment by Quy** [comment]
Please test PR #22852<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18684">issues.joomla.org/tracker/joomla-cms/18684</a>.</sub>
