### ISSUE TITLE
[4.0Alpha] Cannot install "Blog Sample Data" from control panel

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18685]
### Steps to reproduce the issue

install [4.0Alpha] with no sample data
Go to the admin console adn see the "sample data" module with a link called "Blog Sample data"
Click that link

### Expected result

Something......

### Actual result

a blue progress bar gets to 100% and a JS issue (from flying focus as ever)
Then the result of the ajax call to 
`http://0.0.0.0:8010/index.php?option=com_ajax&format=json&group=sampledata`
results in 

```json
{"error":true,"code":0,"message":"Call to a member function save() on boolean"}
```

### System information (as much as possible)

Unique ID	707d2b7806a60debd39e54bb17bfc8cf98c6de6f
PHP Version	7.1.11
DB Type	mysqli
DB Version	5.7.20
CMS Version	4.0.0
Server OS	Darwin 17.3.0

**Comment by ot2sen** [comment]
Had the same issue last night. The dots just kept dancing forever

**Comment by manojLondhe** [comment]
> Had the same issue last night. The dots just kept dancing forever

Me too. However, it worked when I created one more local instance and installed sample data during installation process.

**Comment by wilsonge** [comment]
This is related to https://github.com/joomla/joomla-cms/issues/17705 - I'm going to close this one in favour of that more generic issue

**Comment by brianteeman** [comment]
Thanks

**Comment by PhilETaylor** [comment]
Same problem in Alpha2

**Comment by wilsonge** [comment]
Expected :) I still haven’t closed the other issue yet

**Comment by PhilETaylor** [comment]
#justsaying :)

**Comment by ghost** [comment]
Pull Request for this Issue #18888
