### ISSUE TITLE
Calling JUserHelper::setUserGroups deletes user values from #__fields_values

### ISSUE THREAD

**Issue by stutteringp0et** [joomla/joomla-cms#18699]
### Steps to reproduce the issue
I'm calling JUserHelper::setUserGroups from within a plugin.

### Expected result
Users group membership changes and no other modifications are made to the user.

### Actual result
Every value stored in the #__fields_values table for that user are deleted.

### System information (as much as possible)
J3.8.2 PHP7.1

### Additional comments
I had a feeling this had something to do with the fields system plugin, so I took a quick peek and noticed that the fields aren't updated if there is an input variable "task" with a value of "activate", "block" or "unblock".  So as a test, I set "task" = "unblock" and the field values remain.  Fortunately, this doesn't actually unblock a blocked user, so I can work around this issue.

Without looking too closely, I believe this is a problem in the fields plugin, onContentAfterSave event.  I believe that 2 lines of code would fix this.

Wrapping ```$model->setFieldValue($field->id, $item->id, $value);``` with ```if(!is_null($value)) { }``` would probably do it.

**Comment by stutteringp0et** [comment]
I created PR #18701

**Comment by ghost** [comment]
closed as having Pull Request #18701
