### ISSUE TITLE
[4.0] Icon-Text shows HTML

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#18695]
### Steps to reproduce the issue
Move Curser over Icon "Status" on Module/Article:
![bildschirmfoto 2017-11-19 um 08 20 44](https://user-images.githubusercontent.com/8235763/32988347-d262f4d6-cd02-11e7-9a53-cf63fa9fa868.jpg)
### System information
4.0.0-dev
Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by infograf768** [comment]
Confirmed

**Comment by brianteeman** [comment]
This is a duplicate report.

**Comment by brianteeman** [comment]
see #17255

**Comment by ghost** [comment]
closed as duplicate Report.

Thanks for Hint, @brianteeman.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18695">issues.joomla.org/tracker/joomla-cms/18695</a>.</sub>
