### ISSUE TITLE
[4.0] User Profile errors

### ISSUE THREAD

**Issue by Reijo83** [joomla/joomla-cms#18698]
### Steps to reproduce the issue

Activate User Profile plugin. Go User Mange and choose user.
1. hit Save button you get error:
Error
Save failed with the following error: Operand should contain 1 column(s)

2. Choose User Profile and there fill up Date of Birth.
You get error: Error: 0 Class &#039;Joomla\CMS\Form\Field\DateTimeZone&#039; not foun

### System information (as much as possible)

Joomla 4 Alpha
PHP 7.0.13
Localhost

**Comment by infograf768** [comment]
I avn't reproduce in 4.0 branch

**Comment by Reijo83** [comment]
I think Save issu is related browser. I tested Chrome (62.0.3202.94), Chrome canary (64.0.3272.0), Opera (49.0.2725.39 (PGO)), Vivaldi... I get save error.
Error
Save failed with the following error: Operand should contain 1 column(s)

Firefox (57.0 (64-bit)), Edge - No save `error`
-----
But Date of Birth error is still there.

Video example:
https://youtu.be/s9YVLDpDOZU

**Comment by joomdonation** [comment]
@infograf768 Select a date for Date of Birth field and you should see the error. PR https://github.com/joomla/joomla-cms/pull/18704 should fix it. I will also open a separate PR to fix the Operand should contain 1 column(s) error

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/18705 should fix the **Operand should contain 1 column(s) error**

**Comment by ghost** [comment]
@joomdonation so this Issue can be closed?

**Comment by joomdonation** [comment]
Yes !

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18698">issues.joomla.org/tracker/joomla-cms/18698</a>.</sub>
