### ISSUE TITLE
[4.0] Using the Image button Insert js issue

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#18696]
### Steps to reproduce the issue
TinyMCE 
EDit an article
Click on the Image button
choose an image and click insert

### Actual result
Image is not inserted and js error
<img width="1218" alt="screen shot 2017-11-19 at 08 30 59" src="https://user-images.githubusercontent.com/869724/32988528-a1262efc-cd06-11e7-9aec-d2409c399509.png">

**Comment by ghost** [comment]
Issue confirmed.

**Comment by ghost** [comment]
closed as having Pull Request #18706
