### ISSUE TITLE
[4.0Alpha] Editing frontend modules

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18691]
### Steps to reproduce the issue

login to frontend with super admin rights. 
edit breadcrumbs module

### Expected result

some kind of edit form 

### Actual result
0 Call to undefined method Joomla\Component\Modules\Administrator\Model\ModulesModel::getItem()

![screen shot 2017-11-18 at 21 05 33](https://user-images.githubusercontent.com/400092/32984744-3a9faa12-cca4-11e7-9176-847d201e321a.png)

I have also seen on my other installation that the edit icon top right of a module, will launch a /administrator/ url to edit the module sometimes... that one works only if you are logged into the admin console as well as the frontend.

### System information (as much as possible)

Unique ID	707d2b7806a60debd39e54bb17bfc8cf98c6de6f
PHP Version	7.1.11
DB Type	mysqli
DB Version	5.7.20
CMS Version	4.0.0
Server OS	Darwin 17.3.0

**Comment by wilsonge** [comment]
Fixed the PHP Error with 0425083e6ee487c522c0ccb7577bdfeea9918670
