### ISSUE TITLE
[4.0] TinyMCE js errors

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#18693]
### Steps to reproduce the issue
Edit an article using TinyMce as default editor.

### Result
![screen shot 2017-11-19 at 08 10 28](https://user-images.githubusercontent.com/869724/32988279-28ec49ee-cd01-11e7-99e3-c7b292099470.png)

1. we have a js error
2. The Image button is not any more inline with other buttons as in 3.x

**Comment by infograf768** [comment]
Note: the js error is only displaying here the first time I edit an article.

**Comment by ghost** [comment]
Can't confirme. Got:
![bildschirmfoto 2017-11-19 um 08 49 15](https://user-images.githubusercontent.com/8235763/32988529-a40f7722-cd06-11e7-85a1-615d8cba0efc.jpg)



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18693">issues.joomla.org/tracker/joomla-cms/18693</a>.</sub>

**Comment by dgrammatiko** [comment]
Should be ok after #18708 and #18706

**Comment by dgrammatiko** [comment]
Is this still valid?

**Comment by infograf768** [comment]
I can't reproduce the original error. Closing.
