### ISSUE TITLE
[4.0] is disabling google chrome "Not Secure" warning message

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18692]
Might be a "wont fix" ... for discussion

Unintended consequence of the new hide/show password button on the password input box is that when toggled, the Google Chrome browser url "Not Secure" warning is being removed 

see 

![screen recording 2017-11-18 at 09 16 pm](https://user-images.githubusercontent.com/400092/32984839-d739026e-cca5-11e7-9001-b41771491374.gif)

**Comment by C-Lodder** [comment]
That's because when you click on the button, it changes the input field from `type="password"` to `type="text"`

**Comment by mbabker** [comment]
Ya, this is "won't fix" simply because we can't change browser behavior.
