### ISSUE TITLE
[4.0] JS-Error on /administrator/index.php?option=com_content

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#18697]
### Steps to reproduce the issue
Open url "/administrator/index.php?option=com_content", get Javascript-Error:
![screen shot 2017-11-19 at 08 01 09](https://issues.joomla.org/uploads/1/f0acab0d953932e18bb6f81fe8c00bef.jpg)

### System information
4.0.0-dev
Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by wilsonge** [comment]
I'm pretty sure I fixed this one last night - can you test again please on nightly?

**Comment by ghost** [comment]
closed as fixed like @wilsonge stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18697">issues.joomla.org/tracker/joomla-cms/18697</a>.</sub>
