### ISSUE TITLE
[4.0] Space missing in footer

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18690]
### Steps to reproduce the issue

install [4.0Alpha] 
go to /administrator/
check footer

### Expected result

looks good

### Actual result

![screen shot 2017-11-18 at 21 02 45](https://user-images.githubusercontent.com/400092/32984729-e2ce8556-cca3-11e7-97cb-b5f099a891a7.png)

**Comment by laoneo** [comment]
Please test #18707.

**Comment by ghost** [comment]
closed as having Pull Request #18707.
