### ISSUE TITLE
[4.0] TinyMCE css load error

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#18700]
Edit article
Important: This does not happen all the time. Got it while testing various aspects of admin.

<img width="915" alt="screen shot 2017-11-19 at 10 06 38" src="https://user-images.githubusercontent.com/869724/32989164-9576db5a-cd11-11e7-9cd9-b14ec3fbeb5f.png">

Firefox on Macintosh.

**Comment by ghost** [comment]
Can you please update to Nightly Build if you haven't to be sure?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18700">issues.joomla.org/tracker/joomla-cms/18700</a>.</sub>

**Comment by dgrammatiko** [comment]
This is a tinyMCE problem, the package itself doesn't have the map files. Can we open an issue on their repo and close it here?

**Comment by ghost** [comment]
@brianteeman can you open a Issue on tinymce-Repo while i close this?

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18700">issues.joomla.org/tracker/joomla-cms/18700</a>.</sub>

**Comment by brianteeman** [comment]
Anyone can do that

**Comment by ghost** [comment]
will do

**Comment by brianteeman** [comment]
looks like they fixed it already see
https://github.com/tinymce/tinymce/commit/114e2d6878c58d6fe452db39353cc177f842d8bd

**Comment by brianteeman** [comment]
for reference the error is in 4.7.1 and the fix is in 4.7.2

**Comment by ghost** [comment]
thanks for Info @brianteeman

**Comment by infograf768** [comment]
WE still have error. Posted on #18708

**Comment by brianteeman** [comment]
Looks like the update did not include the map :(

**Comment by C-Lodder** [comment]
Please open an issue on the TinyMCE issue tracker....where it belongs

**Comment by Quy** [comment]
@infograf768 Is this still reproducible?

**Comment by infograf768** [comment]
Nope. Tiny is now 4.7.7 in core. 

Note: 4.7.13 is available

Closing.
