### ISSUE TITLE
[4.0] Template Preview allow resize

### ISSUE THREAD

**Issue by Twincarb** [joomla/joomla-cms#18702]
### Steps to reproduce the issue
Click on Template Preview for the installed template and modal window opens up with a max width 800px which means the viewport is limited.

### Expected result
Ability to select the viewport size available, a button group or dropdown in the header to allow a quick switch between viewpoints.

### Actual result
Viewport limited to 800px

### System information (as much as possible)
J 4.0 Alpha 1
PHP 7.1.11

**Comment by dgrammatiko** [comment]
For accessibility reasons the preview needs to load in another tab, so this needs to be changed

**Comment by happy2dev** [comment]
Keep the preview in a modal doesn't make easy look. I vote for "load in another tab" according to @dgt41. I will work on this and update when it's ready.

**Comment by brianteeman** [comment]
Closed as this preview now opens in a new tab and not a modal
