### ISSUE TITLE
[4.0] Cannot save custom field

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18711]
### Steps to reproduce the issue

install [4.0Alpha2] with no sample data
Attempt to create a custom field

### Expected result

Field saved

### Actual result

![screen shot 2017-11-19 at 17 25 19](https://user-images.githubusercontent.com/400092/32993345-a12a06ce-cd4e-11e7-9b18-3bd57e9ac279.png)

### System information (as much as possible)

http://screenshot.myjoom.la/3w1F2K2y1f05

**Comment by phalouvas** [comment]
False name of table. Chaned and tested ok.

Patch for resolving is this: 

diff --git a/administrator/components/com_fields/Table/FieldTable.php b/administrator/components/com_fields/Table/FieldTable.php
index c7bc876..0efd355 100644
--- a/administrator/components/com_fields/Table/FieldTable.php
+++ b/administrator/components/com_fields/Table/FieldTable.php
@@ -112,7 +112,7 @@
 		$this->name = str_replace(',', '-', $this->name);
 
 		// Verify that the name is unique
-		$table = new Field($this->_db);
+		$table = new FieldTable($this->_db);
 
 		if ($table->load(array('name' => $this->name)) && ($table->id != $this->id || $this->id == 0))
 		{

**Comment by ghost** [comment]
closed as having Pull Request #18742
