### ISSUE TITLE
[4.0] Cannot read property 'querySelectorAll' of null

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18716]
### Steps to reproduce the issue

install [4.0Alpha2] 
Got to Fields page or field groups page in Articles in Admin 
http://0.0.0.0:8010/administrator/index.php?option=com_fields&context=com_content.article

### Expected result

No JS errors 

### Actual result

![screen shot 2017-11-19 at 17 41 24](https://user-images.githubusercontent.com/400092/32993494-e04ec4fa-cd50-11e7-92cc-ce7a5f9d5c29.png)

### System information (as much as possible)

http://screenshot.myjoom.la/3w1F2K2y1f05

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18716">issues.joomla.org/tracker/joomla-cms/18716</a>.</sub>

**Comment by dgrammatiko** [comment]
Hmm, I thought this was already patched

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/18749

**Comment by ghost** [comment]
closed as having Pull Request #18749
