### ISSUE TITLE
[4.0] Users not shown in send private messages

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18714]
### Steps to reproduce the issue

install [4.0Alpha2] 
create a Registered User
Login to admin with your super user
Attempt to send a private message to the registered user
clicking on the select user button the modal loads

### Expected result

a list of all users by default

### Actual result

- on initial page load 

"No matching results"

- attempt to search for the user by name

"No matching results"

- Promote the registered user, to super admins group and then the user will appear

### ADDITIONAL BUG

After searching for name, click "Clear" button, which I expect to clear the saved search - but the modal reloads with the same search term in the search input field. (now logged as https://github.com/joomla/joomla-cms/issues/18715)

### System information (as much as possible)

http://screenshot.myjoom.la/3w1F2K2y1f05

**Comment by brianteeman** [comment]
This is not a bug. Check any Joomla version for the last ten years. You can only send a private message to a user with admin access
https://help.joomla.org/proxy/index.php?keyref=Help38:Components_Messaging_Write

**Comment by PhilETaylor** [comment]
So rather than burying that information on another website maybe it would be good to actually state that on the send message page, or at least the documentation could be explicit 

https://help.joomla.org/proxy/index.php?keyref=Help38:Components_Messaging_Write doesnt actually say that either, it states 

`This screen lets you write and send private messages to others with the correct User Group permissions.`

but yet fails to explain what the "correct" user group permissions are!

**Comment by brianteeman** [comment]
As stated this is not a bug in j4. It has always been this way. If you think about it then it has to be that way. I guess you have never used this useless feature or you would have realised.

**Comment by PhilETaylor** [comment]
I guess this is another one we can pass to the UX team to ignore then...
