### ISSUE TITLE
[4.0] Single quoted values configuration.php

### ISSUE THREAD

**Issue by frostmakk** [joomla/joomla-cms#18710]
### System information (as much as possible)
J 4.0 Alpha 1

### Additional comments
Unlike previous versions, 4.0 does not write all the values to configuration.php as single quoted strings.
Is this by design?

![screen shot 2017-11-19 at 15 52 12](https://issues.joomla.org/uploads/1/5a52c25a40fe0e4b2043559c6821fb6f.png)

**Comment by wilsonge** [comment]
Yes. The CMS is now type aware (see https://github.com/joomla/joomla-cms/pull/17082 for an explanation in the PR as to why) :)
