### ISSUE TITLE
[4.0] Cassiopeia template shows protostar preview image

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18719]
### Steps to reproduce the issue

install J4 Alpha 2
go to http://0.0.0.0:8010/administrator/index.php?option=com_templates&view=templates

### Expected result

new thumbnail for new template

### Actual result
/templates/cassiopeia/template_thumbnail.png actually looks like this:

![screen shot 2017-11-19 at 18 19 02](https://user-images.githubusercontent.com/400092/32993836-21f536b4-cd56-11e7-83ca-bfade11e11fd.png)

![template_preview](https://user-images.githubusercontent.com/400092/32993854-678681b0-cd56-11e7-9912-2b5c59bb2150.png)

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18719">issues.joomla.org/tracker/joomla-cms/18719</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #18746

**Comment by PhilETaylor** [comment]
why was this closed?
