### ISSUE TITLE
The joomla bot changes [4.0Alpha2]  to [4.0] in issue subject lines

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18713]
The joomla bot changes [4.0Alpha2]  to [4.0] in issue subject lines which is crazy as now there is no way to tell which of the Joomla 4 issues are ancient, alpha1 or alpha2 issues

@mbabker ? is this your bot?

**Comment by ghost** [comment]
its me as you wrote alpha-Version in Comment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18713">issues.joomla.org/tracker/joomla-cms/18713</a>.</sub>

**Comment by PhilETaylor** [comment]
for each and every issue over the last 2 days ? 

It seems like a silly thing to do to me...

**Comment by ghost** [comment]
as there are always Categories to set all Issues has to be opened ;-)
