### ISSUE TITLE
unneeded user's name above tabs

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18717]
### Steps to reproduce the issue

Not so much a bug, more aesthetic.. 
Edit a user in Joomla 4 admin (or Joomla 3)

### Expected result

Something sensible.

### Actual result

There is an output of the users name (not username) above the Account details tab that is not needed. It makes no sense to have this here, as well as an editable textbox, especially as if you edit the textbox which contains this value, then the one above the tabs is not updated until the page is saved. In Joomla 4 template (currently) looks worse than in Joomla 3

![screen shot 2017-11-19 at 17 58 53](https://user-images.githubusercontent.com/400092/32993669-53b28c68-cd53-11e7-94bb-b3c6bd3478bd.png)

![screen shot 2017-11-19 at 17 56 07](https://user-images.githubusercontent.com/400092/32993643-ef482b48-cd52-11e7-970d-74a90579cdd7.png)

**Comment by ghost** [comment]
+1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18717">issues.joomla.org/tracker/joomla-cms/18717</a>.</sub>

**Comment by tonypartridge** [comment]
+1

**Comment by brianteeman** [comment]
This was added by @infograf768 https://developer.joomla.org/joomlacode-archive/issue-31060.html

The logic behind it was that if you are on a tab then there is no indicator which user you are editing

(not saying if i agree or disagree I am just reporting the history)

It is a 2 second fix if required

**Comment by ghost** [comment]
thanks for Info @brianteeman and: true, so close my "+1".

**Comment by tonypartridge** [comment]
It’s still duplicating work, why not add username: to the top on each additional fieldset which is non editable?

**Comment by brianteeman** [comment]
i dont see what the "duplicated work" is or how your proposal is any better than the current onw

**Comment by tonypartridge** [comment]
I mean duplicate data on the first screen.

Because you are adding it into a container rather than outside and it’s only shown once, you wouldn’t show it on the first tab since it’s a text edit field there.

**Comment by brianteeman** [comment]
Think about the a11y of it. The page should know the username from a title tag not a field

**Comment by PhilETaylor** [comment]
A (very very very badly mocked up) image of what I think @tonypartridge is proposing, and what is a very easy solution:

![32993643-ef482b48-cd52-11e7-970d-74a90579cdd7](https://user-images.githubusercontent.com/400092/33143662-7ba4e02a-cfb2-11e7-8310-7d51f3b23bc8.png)

**Comment by tonypartridge** [comment]
Exactly!

Or if we must have a duplicate username let’s chuck it up the top next to Edit Profile (Super User)

**Comment by PhilETaylor** [comment]
This mockup is exactly what we do for Articles, where the title is above a tab, as a form field, and not as a "title" above the tabs, with the form field buried in a tab. E.g.

<img width="1281" alt="screen shot 2017-11-22 at 18 29 25" src="https://user-images.githubusercontent.com/400092/33143887-2c2492c4-cfb3-11e7-8a72-449a9a7dba1c.png">

**Comment by brianteeman** [comment]
that seems logical - sorry if i didnt understand you tony

its an easy change

**Comment by tonypartridge** [comment]
@PhilETaylor are you going to do a pull? Or should I?

**Comment by PhilETaylor** [comment]
You can, Im neck deep in rewriting myJoomla.com for a Christmas release.

**Comment by tonypartridge** [comment]
Great, PR sent.

**Comment by ghost** [comment]
closed as having Pull Request #18824

**Comment by C-Lodder** [comment]
Please reopen

**Comment by tonypartridge** [comment]
@lodder see:
https://github.com/joomla/joomla-cms/pull/18824

**Comment by C-Lodder** [comment]
yeah sorry, wrong issue
