### ISSUE TITLE
[4.0] Warning: Database is not up to date! (fix in j4a1 broke this)

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18718]
### Steps to reproduce the issue

see: https://github.com/joomla/joomla-cms/pull/18676 https://github.com/joomla/joomla-cms/issues/18609
Regression introduced in Alpha2 by a fix in alpha1
Table 'ibhhe_fields_groups' does not have column 'params'. (From file 3.8.0-2017-07-28.sql.)

### Expected result

No database issues on clean install of Joomla 4.0 Alpha 2

### Actual result

`Warning: Database is not up to date!`
`Table 'ibhhe_fields_groups' does not have column 'params'. (From file 3.8.0-2017-07-28.sql.)`

### System information (as much as possible)

http://screenshot.myjoom.la/3w1F2K2y1f05

**Comment by wilsonge** [comment]
crud. apparently empty database columns are now features :D i've asked @laoneo on the other issue to revert #18676 and implement the other fix we discussed :)

**Comment by brianteeman** [comment]
Closed as resolved elsewhere
