### ISSUE TITLE
[4.0] Class 'Joomla\Component\Config\Administrator\Controller\Request' not found

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18726]
### Steps to reproduce the issue

ok so the set up for this one is non-sensible, but anyway, this should never error. 

Change the Home menu link to one of type "Site Configuration Options" using admin menu item editor
logout
visit homepage 

### Expected result

No error, possibly a 403 access denied? 

### Actual result

`Class 'Joomla\Component\Config\Administrator\Controller\Request' not found`

![screen shot 2017-11-19 at 19 37 21](https://user-images.githubusercontent.com/400092/32994567-1618954c-cd61-11e7-970d-7f5a696929a9.png)

### System information (as much as possible)

http://screenshot.myjoom.la/3w1F2K2y1f05

**Comment by wilsonge** [comment]
Fixed with https://github.com/joomla/joomla-cms/commit/58106343400af8d436aae0ad8fe440b87c0f7b5e
