### ISSUE TITLE
[4.0] Cannot create Contact - Call to a member function load() on boolean

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18729]
### Steps to reproduce the issue

Install Joomla 4 Alpha 2
Try to create a contact in the admin console

### Expected result

Saves - no errors

### Actual result

`Call to a member function load() on boolean`

![screen shot 2017-11-19 at 19 50 15](https://user-images.githubusercontent.com/400092/32994701-e15432ce-cd62-11e7-932a-93419440b82c.png)

### System information (as much as possible)

http://screenshot.myjoom.la/3w1F2K2y1f05

**Comment by wilsonge** [comment]
Fixed with https://github.com/joomla/joomla-cms/commit/1cea780f75d6f50d90a2f555651caad81fb44383
