### ISSUE TITLE
[4.0] JS issue on clicking search button on search form

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18728]
### Steps to reproduce the issue

(In browser preserve the JS error log) 
Create a menu item that links to the smart search
Navigate to the smart search page
search for something
Click "Search" button 

### Expected result

No JS errors

### Actual result

`Uncaught TypeError: Cannot read property 'querySelector' of undefined`

![screen recording 2017-11-19 at 07 44 pm](https://user-images.githubusercontent.com/400092/32994651-3de4446c-cd62-11e7-811c-0be5a505265e.gif)

### System information (as much as possible)

http://screenshot.myjoom.la/3w1F2K2y1f05

**Comment by wilsonge** [comment]
PR at https://github.com/joomla/joomla-cms/pull/18737
