### ISSUE TITLE
[4.0] Cannot edit my own user profile on frontend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18720]
### Steps to reproduce the issue

login to frontend of Joomla 4 alpha 2
go to http://0.0.0.0:8010/index.php?option=com_users&view=profile
click edit profile takes me to http://0.0.0.0:8010/index.php?task=profile.edit&user_id=885&Itemid=101

### Expected result

an edit profile page

### Actual result

An error page

` Invalid controller class: Joomla\Component\Content\Site\Controller\ProfileController`
![screen shot 2017-11-19 at 18 28 35](https://user-images.githubusercontent.com/400092/32993925-77650614-cd57-11e7-983c-aa901c46bc77.png)

### System information (as much as possible)

http://screenshot.myjoom.la/3w1F2K2y1f05

**Comment by wilsonge** [comment]
OK So I can't reproduce this - having said that there's definitely not class with that name in com_content :) So i think this is some sort of routing issue. What menu structure did you have?

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 26th January 2018.
