### ISSUE TITLE
[4.0] Green border of input boxes when login form fails validation

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18727]
### Steps to reproduce the issue

add menu link to login page 
load page - tab through form fields

### Expected result

RED borders on inputboxes failing validation

### Actual result

GREEN borders 

![screen recording 2017-11-19 at 07 40 pm](https://user-images.githubusercontent.com/400092/32994596-a39de8ea-cd61-11e7-8971-90f69acbee39.gif)

### System information (as much as possible)

http://screenshot.myjoom.la/3w1F2K2y1f05

**Comment by ghost** [comment]
closed as duplicate Report #18634<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18727">issues.joomla.org/tracker/joomla-cms/18727</a>.</sub>
