### ISSUE TITLE
[4.0] IFrame Wrapper URL Not validated.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18725]
### Steps to reproduce the issue

Create a menu item of type iframe wrapper - set url to be something thats certainly not a url 

### Expected result

Validation error message

### Actual result

Menu Item Saved

![screen shot 2017-11-19 at 19 34 09](https://user-images.githubusercontent.com/400092/32994527-b346c22c-cd60-11e7-93b8-5ac50024c15d.png)

### System information (as much as possible)

http://screenshot.myjoom.la/3w1F2K2y1f05

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18725">issues.joomla.org/tracker/joomla-cms/18725</a>.</sub>

**Comment by C-Lodder** [comment]
Would setting the input to `type="url"` be ok for this?

The field is rendered via `echo $this->form->renderFieldset('request');`, so I'm not sure I'd apply this.

**Comment by brianteeman** [comment]
all adding the type=url and associated validation does is to force http:// at the beginning of the garbage
