### ISSUE TITLE
[4.0] Editing module on frontend causes 500 on ordering ajax

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18721]
### Steps to reproduce the issue

Edit a module on the frontend 

### Expected result

No errors

### Actual result

Ordering dropdown missing, caused by a 500 error on the ajax call which is generating error

`Error: 0 Invalid controller class: Joomla\Component\Modules\Site\Controller\ModuleController`

![screen shot 2017-11-19 at 18 57 14](https://user-images.githubusercontent.com/400092/32994164-799401a2-cd5b-11e7-8d1f-16c6e525d92f.png)

### System information (as much as possible)

http://screenshot.myjoom.la/3w1F2K2y1f05

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18721">issues.joomla.org/tracker/joomla-cms/18721</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #20041
