### ISSUE TITLE
[4.0] frontend tooltips are displaced from their arrows.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18730]
## Steps to reproduce the issue

install Joomla 4 alpha 2
overover something with a tooltip, like module edit icon (after login)

### Expected result

The tooltip black background is joined to the black pointer arrow 

### Actual result

the tooltip loads on the left of the page, the arrow, in the right place 

Example 1:
![screen shot 2017-11-19 at 20 03 41](https://user-images.githubusercontent.com/400092/32994897-fbd26aba-cd64-11e7-90f9-7ec90210e99a.png)

Example 2:
![screen shot 2017-11-19 at 20 05 28](https://user-images.githubusercontent.com/400092/32994900-01b44372-cd65-11e7-80eb-4ca481c587cc.png)

### System information (as much as possible)

http://screenshot.myjoom.la/3w1F2K2y1f05

Google Chrome.

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18730">issues.joomla.org/tracker/joomla-cms/18730</a>.</sub>

**Comment by dgrammatiko** [comment]
Please do not spend time trying to fix this. The UI tooltip that J4 will use will be: https://github.com/joomla-projects/custom-elements/tree/master/src/js/tip

**Comment by C-Lodder** [comment]
Temporary PR until custom elements have been done and `frontediting.js` has been rewritten: https://github.com/joomla/joomla-cms/pull/18786

**Comment by ghost** [comment]
closed as having Pull Request #18786
