### ISSUE TITLE
Invalid security Token

### ISSUE THREAD

**Issue by Gensia** [joomla/joomla-cms#18738]
The most recent request was denied because it contained an invalid security token. Please refresh the page and try again.

Its easy to replicate this issue  just install Joomla and try to use it. Dont tell me this is something to do with cache and close this issue. None of the fixes on the forum work.

**Comment by ghost** [comment]
@Gensia can you please provide Links to your Forums-Discussions?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18738">issues.joomla.org/tracker/joomla-cms/18738</a>.</sub>

**Comment by boomsya** [comment]
the same error with enabled caching. Why this bug still yet in fall on 2017 ???!!
90% supporting problems with tokens when cache enabled

my solution for Joomla 3 like this (and this works few years!!):
file `/plugins/system/cache/cache.php` method `function onAfterInitialise()`

```
if($data !== false)
{
	$token	= JSession::getFormToken();
	$search = '#<input type="hidden" name="[0-9a-f]{32}" value="1" />#';
	$replacement = '<input type="hidden" name="'.$token.'" value="1" />';
	$data = preg_replace( $search, $replacement, $data );
	$search = '#<input type="hidden" value="1" name="[0-9a-f]{32}" />#';
	$replacement = '<input type="hidden" name="'.$token.'" value="1" />';
	$data = preg_replace( $search, $replacement, $data );
.....
```

**Comment by Gensia** [comment]
[quote="Forum Post Assistant (v1.3.6) : 20th November 2017"][quote="Basic Environment ::"][size=85][b]Joomla! Instance :: [/b][color=Blue]Joomla! [b]3.8.1[/b]-Stable (Amani) 4-October-2017[/color]
[b]Joomla! Platform :: [/b] [color=Blue]Joomla Platform [b]13.1.0[/b]-Stable (Curiosity) 24-Apr-2013[/color]
[b]Joomla! Configured :: [/b][color=Green]Yes[/color] | Read-Only ([color=Green]444[/color]) | [b]Owner:[/b]  [color=orange]--protected--[/color] . (uid: 1/gid: 1) | [b]Group:[/b]  [color=orange]--protected--[/color]  (gid: 1) | [b]Valid For:[/b] 3.8
[b]Configuration Options :: Offline:[/b] 0 | [b]SEF:[/b] 1 | [b]SEF Suffix:[/b] 0 | [b]SEF ReWrite:[/b] 1 | [b].htaccess/web.config:[/b] [color=Green]Yes[/color] | [b]GZip:[/b] 0 | [b]Cache:[/b] 0 | [b]CacheTime:[/b] 15 | [b]CacheHandler:[/b] file | [b]CachePlatformPrefix:[/b] 0 | [b]FTP Layer:[/b] 0 | [b]Proxy:[/b] 0 | [b]LiveSite:[/b]  | [b]Session lifetime:[/b] 15 | [b]Session handler:[/b] database | [b]Shared sessions:[/b] 0 | [b]SSL:[/b] 0 | [b]FrontEdit:[/b] 1 | [b]Error Reporting:[/b] none | [b]Site Debug:[/b] 0 | [b]Language Debug:[/b] 0 | [b]Default Access:[/b] 1 | [b]Unicode Slugs:[/b] 0 | [b]dbConnection Type:[/b] mysqli | [b]Database Credentials Present:[/b] [color=Green]Yes[/color]

[b]Host Configuration :: OS:[/b] Linux |  [b]OS Version:[/b] 2.6.32-673.26.1.lve1.4.30.el6.x86_64 | [b]Technology:[/b] x86_64 | [b]Web Server:[/b] Apache | [b]Encoding:[/b] gzip | [b]Doc Root:[/b] [color=orange]--protected--[/color] | [b]System TMP Writable:[/b] [color=Green]Yes[/color]

[b]PHP Configuration :: Version:[/b] [b]5.6.30[/b] | [b]PHP API:[/b] [b]cgi-fcgi[/b] | [b]Session Path Writable:[/b] [color=Green]Yes[/color] | [b]Display Errors:[/b]  | [b]Error Reporting:[/b] 22519 | [b]Log Errors To:[/b]  | [b]Last Known Error:[/b]  | [b]Register Globals:[/b]  | [b]Magic Quotes:[/b]  | [b]Safe Mode:[/b]  | [b]Open Base:[/b]  | [b]Uploads:[/b] 1 | [b]Max. Upload Size:[/b] 2M | [b]Max. POST Size:[/b] 8M | [b]Max. Input Time:[/b] 60 | [b]Max. Execution Time:[/b] 30 | [b]Memory Limit:[/b] 32M

[b]MySQL Configuration :: [/b] [b]Version:[/b] [b]10.0.31-MariaDB-cll-lve[/b] (Client:10.0.31-MariaDB) | [b]Host:[/b]  [color=orange]--protected--[/color] ([color=orange]--protected--[/color]) | [b]Collation:[/b] latin1_swedish_ci ([b]Character Set:[/b] latin1) | [b]Database Size:[/b] 5.32 MiB | [b]#of Tables: [/b] 121[/size][/quote][quote="Detailed Environment ::"][size=85][b]PHP Extensions :: [/b]Core (5.6.30) | date (5.6.30) | ereg () | [color=Green][b]libxml[/b][/color] () | [color=Green][b]openssl[/b][/color] () | pcre () | sqlite3 (0.7-dev) | [color=Green][b]zlib[/b][/color] (2.0) | bz2 () | calendar () | ctype () | [color=Green][b]curl[/b][/color] () | hash (1.0) | filter (0.11.0) | ftp () | gettext () | gmp () | SPL (0.2) | [color=Green][b]iconv[/b][/color] () | pcntl () | readline (5.6.30) | Reflection ($Id: 5f15287237d5f78d75b19c26915aa7bd83dee8b8 $) | session () | standard (5.6.30) | shmop () | SimpleXML (0.1) | [color=Green][b]mbstring[/b][/color] () | tokenizer (0.1) | [color=Green][b]xml[/b][/color] () | [color=Green][b]cgi-fcgi[/b][/color] () | gd () | [color=Green][b]mysql[/b][/color] (1.0) | posix () | imagick (3.4.3RC4) | [color=Green][b]mysqli[/b][/color] (0.1) | imap () | mysqlnd (mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $) | bcmath () | intl (1.1.0) | json (1.2.1) | dom (20031129) | xmlreader (0.1) | xmlrpc (0.51) | soap () | xmlwriter (0.1) | PDO (1.0.4dev) | sockets () | fileinfo (1.0.5) | exif (1.4 $Id: 1c8772f76be691b7b3f77ca31eb788a2abbcefe5 $) | [color=Green][b]mcrypt[/b][/color] () | pdo_mysql (1.0.2) | [color=Green][b]zip[/b][/color] (1.12.5) | pdo_sqlite (1.0.1) | Phar (2.0.2) | tidy (2.0) | mhash () | ionCube Loader () | Zend OPcache (7.0.4-devFE) | Zend Guard Loader () | Zend Engine (2.6.0) | 
[b]Potential Missing Extensions :: [/b][color=orange]suhosin[/color] | 

[b]Switch User Environment[/b] [i](Experimental)[/i][b] :: PHP CGI:[/b] Yes | [b]Server SU:[/b] Yes |  [b]PHP SU:[/b] Yes |   [b]Custom SU (LiteSpeed/Cloud/Grid):[/b] Yes
[b]Potential Ownership Issues:[/b] [color=Green]No[/color] [/size][/quote][quote="Folder Permissions ::"][size=85][b]Core Folders :: [/b]images/ (755) | components/ (755) | modules/ (755) | plugins/ (755) | language/ (755) | templates/ (755) | cache/ (755) | logs/ (---) | tmp/ (755) | administrator/components/ (755) | administrator/modules/ (755) | administrator/language/ (755) | administrator/templates/ (755) | administrator/logs/ (755) | 

[b]Elevated Permissions[/b] [i](First 10)[/i][b] :: [/b][/size][/quote][quote="Database Information ::"][size=85][b]Database statistics :: [/b][b]Uptime:[/b] 278305 | [b]Threads:[/b] 71 | [b]Questions:[/b] 78200548 | [b]Slow queries:[/b] 3203 | [b]Opens:[/b] 4130978 | [b]Flush tables:[/b] 1 | [b]Open tables:[/b] 400 | [b]Queries per second avg:[/b] 280.988 | [/size][/quote][quote="Extensions Discovered ::"][size=85][b]Components :: SITE :: [/b][color=Blue]com_wrapper (3.0.0) [/color]  1 | [color=Brown]WF_PREVIEW_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_FONTSIZESELECT_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_CHARMAP_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_LAYER_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_XHTMLXTRAS_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_INLINEPOPUPS_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_BROWSER_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_TEXTCASE_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_TABLE_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_FORMATSELECT_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_CLIPBOARD_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_LINK_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_ANCHOR_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_CLEANUP_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_AUTOSAVE_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_VISUALCHARS_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_FULLSCREEN_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_KITCHENSINK_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_CONTEXTMENU_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_FONTCOLOR_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_ARTICLE_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_NONBREAKING_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_IMGMANAGER_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_SEARCHREPLACE_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_EMOTIONS_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_VISUALBLOCKS_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_SPELLCHECKER_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_PRINT_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_MEDIA_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_STYLESELECT_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_HR_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_FONTSELECT_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_STYLE_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_LISTS_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_DIRECTIONALITY_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_SOURCE_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_LINKS_JOOMLALINKS_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_LINK_SEARCH_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_POPUPS_WINDOW_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_POPUPS_JCEMEDIABOX_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_FILESYSTEM_JOOMLA_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_AGGREGATOR_YOUTUBE_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_AGGREGATOR_VIMEO_TITLE (2.6.19) [/color]  1 | [color=Brown]WF_AGGREGATOR_DAILYMOTION_TITL (2.6.19) [/color]  1 | [color=Brown]WF_AGGREGATOR_VINE_TITLE (2.6.19) [/color]  1 | [color=Blue]com_mailto (3.0.0) [/color]  1 | 
[b]Components :: ADMIN :: [/b][color=Blue]com_admin (3.0.0) [/color]  1 | [color=Blue]com_config (3.0.0) [/color]  1 | [color=Blue]com_modules (3.0.0) [/color]  1 | [color=Blue]com_languages (3.0.0) [/color]  1 | [color=Blue]com_installer (3.0.0) [/color]  1 | [color=Blue]com_plugins (3.0.0) [/color]  1 | [color=Blue]com_content (3.0.0) [/color]  1 | [color=Blue]com_contenthistory (3.2.0) [/color]  1 | [color=Blue]com_templates (3.0.0) [/color]  1 | [color=Blue]com_newsfeeds (3.0.0) [/color]  1 | [color=Blue]com_joomlaupdate (3.6.2) [/color]  1 | [color=Blue]com_messages (3.0.0) [/color]  1 | [color=Blue]com_fields (3.7.0) [/color]  1 | [color=Blue]com_search (3.0.0) [/color]  1 | [color=Brown]COM_JCE (2.6.19) [/color]  1 | [color=Blue]com_checkin (3.0.0) [/color]  1 | [color=Blue]com_postinstall (3.2.0) [/color]  1 | [color=Blue]com_redirect (3.0.0) [/color]  1 | [color=Blue]com_ajax (3.2.0) [/color]  1 | [color=Blue]com_cpanel (3.0.0) [/color]  1 | [color=Blue]com_associations (3.7.0) [/color]  1 | [color=Blue]com_media (3.0.0) [/color]  1 | [color=Blue]com_categories (3.0.0) [/color]  1 | [color=Blue]com_menus (3.0.0) [/color]  1 | [color=Brown]com_jblance (2.5.7) [/color]  1 | [color=Blue]com_finder (3.0.0) [/color]  1 | [color=Blue]com_cache (3.0.0) [/color]  1 | [color=Blue]com_users (3.0.0) [/color]  1 | [color=Blue]com_login (3.0.0) [/color]  1 | [color=Blue]com_banners (3.0.0) [/color]  1 | [color=Blue]com_tags (3.1.0) [/color]  1 | 

[b]Modules :: SITE :: [/b][color=Brown]mod_jblanceusers (1.0.2) [/color]  1 | [color=Blue]mod_breadcrumbs (3.0.0) [/color]  1 | [color=Blue]mod_custom (3.0.0) [/color]  1 | [color=Brown]mod_jblancesearch (1.0.0) [/color]  1 | [color=Blue]mod_syndicate (3.0.0) [/color]  1 | [color=Brown]mod_jblancetags (1.0.0) [/color]  1 | [color=Blue]mod_tags_popular (3.1.0) [/color]  1 | [color=Blue]mod_search (3.0.0) [/color]  1 | [color=Blue]mod_tags_similar (3.1.0) [/color]  1 | [color=Blue]mod_banners (3.0.0) [/color]  1 | [color=Blue]mod_random_image (3.0.0) [/color]  1 | [color=Blue]mod_finder (3.0.0) [/color]  1 | [color=Brown]mod_jblancelatest (1.0.0) [/color]  1 | [color=Brown]mod_jblancebalance (1.0) [/color]  1 | [color=Blue]mod_stats (3.0.0) [/color]  1 | [color=Blue]mod_articles_popular (3.0.0) [/color]  1 | [color=Blue]mod_footer (3.0.0) [/color]  1 | [color=Brown]mod_jblancecategory (1.0.0) [/color]  1 | [color=Blue]mod_feed (3.0.0) [/color]  1 | [color=Brown]mod_jblancemenu (1.0.0) [/color]  1 | [color=Blue]mod_articles_latest (3.0.0) [/color]  1 | [color=Brown]mod_jblancestats (1.1) [/color]  1 | [color=Brown]mod_jblancescript (1.0) [/color]  1 | [color=Blue]mod_related_items (3.0.0) [/color]  1 | [color=Blue]mod_users_latest (3.0.0) [/color]  1 | [color=Brown]mod_jblancefeeds (1.0.0) [/color]  1 | [color=Blue]mod_whosonline (3.0.0) [/color]  1 | [color=Blue]mod_login (3.0.0) [/color]  1 | [color=Blue]mod_wrapper (3.0.0) [/color]  1 | [color=Brown]mod_jblanceservice (1.0.0) [/color]  1 | [color=Blue]mod_articles_archive (3.0.0) [/color]  1 | [color=Blue]mod_articles_news (3.0.0) [/color]  1 | [color=Blue]mod_articles_category (3.0.0) [/color]  1 | [color=Blue]mod_menu (3.0.0) [/color]  1 | [color=Blue]mod_languages (3.5.0) [/color]  1 | [color=Blue]mod_articles_categories (3.0.0) [/color]  1 | 
[b]Modules :: ADMIN :: [/b][color=Blue]mod_popular (3.0.0) [/color]  1 | [color=Blue]mod_custom (3.0.0) [/color]  1 | [color=Brown]mod_cachecleaner (6.1.0) [/color]  1 | [color=Blue]mod_status (3.0.0) [/color]  1 | [color=Blue]mod_feed (3.0.0) [/color]  1 | [color=Blue]mod_sampledata (3.8.0) [/color]  0 | [color=Blue]mod_quickicon (3.0.0) [/color]  1 | [color=Blue]mod_multilangstatus (3.0.0) [/color]  1 | [color=Blue]mod_toolbar (3.0.0) [/color]  1 | [color=Blue]mod_stats_admin (3.0.0) [/color]  1 | [color=Blue]mod_login (3.0.0) [/color]  1 | [color=Blue]mod_version (3.0.0) [/color]  1 | [color=Blue]mod_latest (3.0.0) [/color]  1 | [color=Blue]mod_logged (3.0.0) [/color]  1 | [color=Blue]mod_menu (3.0.0) [/color]  1 | [color=Blue]mod_submenu (3.0.0) [/color]  1 | [color=Blue]mod_title (3.0.0) [/color]  1 | 

[b]Plugins :: SITE :: [/b][color=Blue]plg_quickicon_phpversioncheck (3.7.0) [/color]  1 | [color=Brown]plg_quickicon_jce (2.6.0-pro-bet) [/color]  1 | [color=Blue]plg_quickicon_joomlaupdate (3.0.0) [/color]  1 | [color=Blue]plg_quickicon_extensionupdate (3.0.0) [/color]  1 | [color=Blue]plg_content_emailcloak (3.0.0) [/color]  1 | [color=Blue]plg_content_joomla (3.0.0) [/color]  1 | [color=Brown]plg_content_jce (2.6.19) [/color]  1 | [color=Blue]plg_content_pagebreak (3.0.0) [/color]  1 | [color=Blue]plg_content_fields (3.7.0) [/color]  1 | [color=Blue]plg_content_pagenavigation (3.0.0) [/color]  1 | [color=Blue]plg_content_loadmodule (3.0.0) [/color]  1 | [color=Blue]plg_content_finder (3.0.0) [/color]  0 | [color=Blue]plg_content_vote (3.0.0) [/color]  1 | [color=Blue]plg_twofactorauth_totp (3.2.0) [/color]  0 | [color=Blue]plg_twofactorauth_yubikey (3.2.0) [/color]  0 | [color=Blue]plg_authentication_joomla (3.0.0) [/color]  1 | [color=Blue]plg_authentication_ldap (3.0.0) [/color]  0 | [color=Blue]plg_authentication_cookie (3.0.0) [/color]  1 | [color=Blue]plg_authentication_gmail (3.0.0) [/color]  0 | [color=Blue]plg_search_content (3.0.0) [/color]  1 | [color=Blue]plg_search_categories (3.0.0) [/color]  1 | [color=Blue]plg_search_newsfeeds (3.0.0) [/color]  1 | [color=Brown]plg_jblance_search (1.0) [/color]  1 | [color=Blue]plg_search_contacts (3.0.0) [/color]  1 | [color=Blue]plg_search_tags (3.0.0) [/color]  1 | [color=Blue]plg_fields_textarea (3.7.0) [/color]  1 | [color=Blue]plg_fields_calendar (3.7.0) [/color]  1 | [color=Blue]plg_fields_url (3.7.0) [/color]  1 | [color=Blue]plg_fields_integer (3.7.0) [/color]  1 | [color=Blue]plg_fields_color (3.7.0) [/color]  1 | [color=Blue]plg_fields_editor (3.7.0) [/color]  1 | [color=Blue]plg_fields_list (3.7.0) [/color]  1 | [color=Blue]plg_fields_media (3.7.0) [/color]  1 | [color=Blue]plg_fields_sql (3.7.0) [/color]  1 | [color=Blue]plg_fields_radio (3.7.0) [/color]  1 | [color=Blue]plg_fields_user (3.7.0) [/color]  1 | [color=Blue]plg_fields_imagelist (3.7.0) [/color]  1 | [color=Blue]plg_fields_usergrouplist (3.7.0) [/color]  1 | [color=Blue]plg_fields_checkboxes (3.7.0) [/color]  1 | [color=Blue]plg_fields_text (3.7.0) [/color]  1 | [color=Blue]plg_extension_joomla (3.0.0) [/color]  1 | [color=Brown]plg_extension_jce (2.6.19) [/color]  1 | [color=Blue]plg_captcha_recaptcha (3.4.0) [/color]  0 | [color=Blue]plg_editors-xtd_module (3.5.0) [/color]  1 | [color=Blue]plg_editors-xtd_pagebreak (3.0.0) [/color]  1 | [color=Blue]plg_editors-xtd_article (3.0.0) [/color]  1 | [color=Blue]plg_editors-xtd_fields (3.7.0) [/color]  1 | [color=Blue]plg_editors-xtd_image (3.0.0) [/color]  1 | [color=Blue]plg_editors-xtd_readmore (3.0.0) [/color]  1 | [color=Blue]plg_editors-xtd_menu (3.7.0) [/color]  1 | [color=Blue]plg_user_joomla (3.0.0) [/color]  1 | [color=Blue]plg_user_contactcreator (3.0.0) [/color]  0 | [color=Blue]plg_user_profile (3.0.0) [/color]  0 | [color=Brown]plg_editors_codemirror (5.28) [/color]  1 | [color=Brown]plg_editors_jce (2.6.19) [/color]  1 | [color=Brown]plg_editors_tinymce (4.5.7) [/color]  1 | [color=Blue]plg_installer_packageinstaller (3.6.0) [/color]  1 | [color=Blue]plg_installer_webinstaller (1.1.1) [/color]  1 | [color=Brown]plg_installer_jce (2.6.19) [/color]  1 | [color=Blue]PLG_INSTALLER_URLINSTALLER (3.6.0) [/color]  1 | [color=Blue]PLG_INSTALLER_FOLDERINSTALLER (3.6.0) [/color]  1 | [color=Brown]plg_joombri_jblancefeeds (1.0) [/color]  1 | [color=Blue]plg_system_redirect (3.0.0) [/color]  0 | [color=Blue]plg_system_p3p (3.0.0) [/color]  0 | [color=Blue]plg_system_cache (3.0.0) [/color]  0 | [color=Brown]plg_system_jce (2.6.19) [/color]  1 | [color=Blue]plg_system_fields (3.7.0) [/color]  1 | [color=Blue]plg_system_log (3.0.0) [/color]  1 | [color=Brown]plg_jblance_regredirect (1.1) [/color]  1 | [color=Blue]plg_system_remember (3.0.0) [/color]  1 | [color=Brown]plg_system_regularlabs (17.10.14312) [/color]  1 | [color=Brown]System - Google Maps (3.3) [/color]  1 | [color=Brown]plg_system_cachecleaner (6.1.0) [/color]  1 | [color=Blue]plg_system_highlight (3.0.0) [/color]  1 | [color=Blue]plg_system_languagefilter (3.0.0) [/color]  0 | [color=Blue]plg_system_debug (3.0.0) [/color]  1 | [color=Brown]plg_system_jblanceexpiry (1.0) [/color]  1 | [color=Blue]plg_system_updatenotification (3.5.0) [/color]  1 | [color=Blue]plg_system_logout (3.0.0) [/color]  1 | [color=Blue]plg_system_languagecode (3.0.0) [/color]  0 | [color=Brown]PLG_PWEBOPENGRAPH (1.1.12) [/color]  1 | [color=Blue]plg_system_sef (3.0.0) [/color]  1 | [color=Blue]plg_system_stats (3.5.0) [/color]  1 | [color=Blue]plg_finder_content (3.0.0) [/color]  1 | [color=Blue]plg_finder_categories (3.0.0) [/color]  1 | [color=Blue]plg_finder_newsfeeds (3.0.0) [/color]  1 | [color=Blue]plg_finder_contacts (3.0.0) [/color]  1 | [color=Blue]plg_finder_tags (3.0.0) [/color]  1 | [/size][/quote][quote="Templates Discovered ::"][size=85][b]Templates :: SITE :: [/b][color=Brown][b][u]jb_charm (1.0.0)[/u][/b][/color]  1 | [color=Blue]beez3 (3.1.0)[/color]  1 | [color=Blue]protostar (1.0)[/color]  1 | 
[b]Templates :: ADMIN :: [/b][color=Blue][b][u]isis (1.0)[/u][/b][/color]  1 | [color=Blue]hathor (3.0.0)[/color]  1 | [/size][/quote][/quote]

**Comment by Gensia** [comment]
http://www.staffbook.net/register

No one can register on my site, user groups are messed up they keep on changing and usually a Invalid Token error

**Comment by Gensia** [comment]
boomsya your solution doesn't work like every other fix so far although you use barely legible English to mention cache as the culprit which I specifically mentioned so as not to close this issue with another false fix that doesnt work  I do not have cache enabled turned it off while developing and my site was never finished

**Comment by brianteeman** [comment]
@gensia your site issues are configuration and template issues - they are nothing to do with the core code of joomla

**Comment by brianteeman** [comment]
@gensia everything in your site is being passed through a file in your template called gzip.php this is causing your problems

**Comment by Gensia** [comment]
Okay my bad thank you for your help
