### ISSUE TITLE
a username can be the same as its password

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18734]
### Steps to reproduce the issue

Create a user, its username can be exactly the same as the password 

like 

username: admin
password: admin

### Expected result

That Joomla holds itself to better security/validation than this and doesn't allow this in the future. Why on earth would we allow this, I cannot see any justification. 

### Actual result

admin/admin is valid.
user/user is valid.

**Comment by brianteeman** [comment]
as always - pull requests welcome

**Comment by ghost** [comment]
closed as having Pull Request #18766
