### ISSUE TITLE
[4.0] Pagebreak messed Layout

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#18739]
### Steps to reproduce the issue
Create Pagebreak "test", got:
![bildschirmfoto 2017-11-20 um 07 48 05](https://user-images.githubusercontent.com/8235763/33005702-505901ae-cdc7-11e7-9c4f-9d560aa99936.jpg)
### System information
4.0.0-dev
Multilanguage Site (4 Lang.) & Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by wilsonge** [comment]
@ciar4n can you take a go at this one?

**Comment by C-Lodder** [comment]
@franz-wohlkoenig does https://github.com/joomla/joomla-cms/pull/18754 fix this?

**Comment by ghost** [comment]
@C-Lodder no, doesn't fix it.

**Comment by ciar4n** [comment]
PR created.. #18759

**Comment by ghost** [comment]
closed as having Pull Request #18759
