### ISSUE TITLE
[4.0] Installer security checks are broken

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#18736]
### Steps to reproduce the issue

try to Install 4.0 on a remote database

### Expected result

Sec checks about remote databases

### Actual result

No sec checks on remtote databases

### Additional comments

I have tried to figure out the problem but i run into a problem i don't understand. (all vars are variables are gone after that line for unknown reason)

As It looks like some strange things happen in this line here:
https://github.com/joomla-framework/database/blob/master/src/Mysqli/MysqliDriver.php#L220

![mysqlinit](https://user-images.githubusercontent.com/2596554/32996263-d8c62446-cd80-11e7-9628-8ca247b9a9d6.gif)

Important to know is the following step by step:
- download 4.0-alpha2
- uncomment that code here: https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/src/Model/DatabaseModel.php#L188
- and replace this line: https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/src/Model/DatabaseModel.php#L227 by `if (!\JFile::write($remoteDbPath, ''))`
- run into the first try for connection by entering `localhost2` (== runs into the checks of the new code)

**Comment by wilsonge** [comment]
There's no code for the interface for this. I did tell @SniperSister this at JAB - I should have put it in the JSST channel too. We need to figure out how this works now that we have a single page application rather than a multi-page app.

Leave this issue open - but this isn't a quick fix and we probably need to partly solve this with @coolcat-creations from a UX perspective

**Comment by PhilETaylor** [comment]
This is/should be a release blocker.

**Comment by wilsonge** [comment]
Indeed. Tagged as such :)

**Comment by zero-24** [comment]
Just ti be sure also the installation language strings have been dropped ... https://github.com/joomla/joomla-cms/blob/3.8.2/installation/language/en-GB/en-GB.ini#L34-L36

**Comment by wilsonge** [comment]
They shouldn’t have been dropped

**Comment by dgrammatiko** [comment]
FWIW the language files need a good clean up and proper English strings for some labels

**Comment by zero-24** [comment]
@wilsonge @dgt41 any updates on the installer problem with broken databases and the security checks?

**Comment by schultz-it-solutions** [comment]
I just tried to install J4-alpha11 on my system with the database residing on another server than "localhost".
This still is possible without any warning.
I would be happy to help out with testing this, if there is a solution...
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18736">issues.joomla.org/tracker/joomla-cms/18736</a>.</sub>

**Comment by wilsonge** [comment]
Nothing yet in progress that I'm aware of. This is going to end up being a pretty major piece of work given the single page app nature now I think probably a few days to code something up

**Comment by richard67** [comment]
@zero-24 The first link https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php#L230 you give in the "Additional comments" leads to nowhere ... maybe you can replace it with a link to thesame code in the database framework package?

**Comment by HLeithner** [comment]
@richard67 you can find it here https://github.com/joomla-framework/database/blob/master/src/Mysqli/MysqliDriver.php#L220 now

**Comment by richard67** [comment]
@HLeithner Thanks. Maybe @zero-24 should update the link in the description?

**Comment by zero-24** [comment]
updated.

**Comment by richard67** [comment]
I think I will work on it soon.

**Comment by richard67** [comment]
Hmm, maybe the checks have to be added to routine "validateDbConnection" in file "SetupModel.php" and not to routine "initialise" in file "DatabaseModel.php"?

**Comment by richard67** [comment]
@zero-24 I see that the commented out code is inside the `if (in_array($options->db_type, ['pgsql', 'postgresql']))` block in file "DatabaseModel.php". It should be below the next closing `}` so it comes after that "if" block. Maybe that was the reason why it did not work? And maybe it should be moved to routine "validateDbConnection" in file "SetupModel.php", like I wrote in my previous comment?

**Comment by dgrammatiko** [comment]
@richard67 there's nothing in the front end to support this so without creating some html and js this won't work.
Also from a UX point of view the checks are better to kick off before start asking the user to input anything. I do understand that the current code is checking the db but maybe you could twist the logic a bit to fit in the preinstall checks. It will make a much more better UX experience than convoluting the steps and confusing users by pausing the process and asking them to do the file upload. In sort, the concept needs some rethinking

**Comment by richard67** [comment]
@dgrammatiko I see no html to be created, can be all done with alerts. am working on it, and parts are already working. If the check make sense or not is on the sst to decide, they once have requiested it as far as I know, and I only wanna solve this issue here and maybe improve that a bit. If later someone says throw it away I have no problem with it.

**Comment by richard67** [comment]
PR is #27360 , but it is still work in progress so please don't close this issue yet.

**Comment by richard67** [comment]
PR #27360 is ready for testing. This issue can be closed. @zero-24 Please test.

**Comment by richard67** [comment]
Closed as having PR.
