### ISSUE TITLE
[4.0] window.parent.jModalClose is not a function

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18733]
### Steps to reproduce the issue

set wysiwyg editor = none, edit article, click page break

### Expected result

page break works normally

### Actual result

after setting the page break name and saving the modal doesnt close but is populated by a webpage 

![screen recording 2017-11-19 at 09 58 pm](https://user-images.githubusercontent.com/400092/32996021-161f9cb6-cd75-11e7-9b8c-9e7b3995f927.gif)

**Comment by ghost** [comment]
Can't confirm. 

Modal-Window is closing as expected.

### System information
4.0.0-dev
Multilanguage Site (4 Lang.) & Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by dgrammatiko** [comment]
@PhilETaylor this will be fixed once the complete UI library is merged, so for the time being let's mark this as a known problem

**Comment by PhilETaylor** [comment]
>once the complete UI library is merged 

When will that be?

> mark this as a known problem

The problem is not fixed. So this issue should stay open.

**Comment by C-Lodder** [comment]
PR just incase: https://github.com/joomla/joomla-cms/pull/18751

**Comment by ghost** [comment]
closed as having Pull Request #18751

**Comment by C-Lodder** [comment]
@franz-wohlkoenig - please can you re-open this?

**Comment by ghost** [comment]
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18733">issues.joomla.org/tracker/joomla-cms/18733</a>.</sub>

**Comment by Quy** [comment]
Duplicate #20478<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18733">issues.joomla.org/tracker/joomla-cms/18733</a>.</sub>
