### ISSUE TITLE
function login() in /components/com_users/controllers/user.php checks token. Why?

### ISSUE THREAD

**Issue by boomsya** [joomla/joomla-cms#18748]
from joomla 1.5 and for 3.8.1 i have problems under cache
100% situations when users goto cached login page and they have error "Invalid token"

"guest" token in 95% of sites what i was develop not needed
So when page cached - site return wrong token - token of another "guest"
and when they try to login the result is "Invalid token" :(

i dont understand what security vulnerability can makes in method "`login()`" without `checkToken`?

**Comment by tonypartridge** [comment]
Do you have a custom module or component processing the login? 

This shouldn’t be a problem with the core.

**Comment by boomsya** [comment]
no i don`t have
do you think **checkToken()** returns **true** when checks token of another guest with yours guest session?

**Comment by ghost** [comment]
@tonypartridge any Answer on above Question or is this for Forum?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18748">issues.joomla.org/tracker/joomla-cms/18748</a>.</sub>

**Comment by tonypartridge** [comment]
I think it’s more of a coding issues. checkToken only returns true for the current logged in User if the token is theirs.

**Comment by ghost** [comment]
@tonypartridge thanks for Info.
