### ISSUE TITLE
[4.0] Pagebreak: JHtml tabs not found

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#18741]
### Steps to reproduce the issue
Create Pagebreak, set in Plugin the Presentation Style to "Tabs" got:

![bildschirmfoto 2017-11-20 um 07 55 16](https://user-images.githubusercontent.com/8235763/33005880-4e7d896c-cdc8-11e7-9a3a-325677fb99d4.jpg)
### System information
4.0.0-dev
Multilanguage Site (4 Lang.) & Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/18754

**Comment by ghost** [comment]
closed as having Pull Request #18754
