### ISSUE TITLE
[4.0] Clear button doesn't work

### ISSUE THREAD

**Issue by dirksmit** [joomla/joomla-cms#18744]
### Steps to reproduce the issue
Go to Administrator - Extensions - Manage - Manage
Search for test 
Enter
Results are shown
Use clear-button

### Expected result
search results are cleared

### Actual result
Nothing happens

### System information (as much as possible)
PHP Built On 	Linux synology 3.10.102 #15217 SMP Fri Nov 3 04:40:38 CST 2017 x86_64
Database Version 	5.5.5-10.0.31-MariaDB
Database Collation 	utf8mb4_unicode_ci
Database Connection Collation 	utf8_general_ci
PHP Version 	7.0.21
Web Server 	Apache/2.4.27 (Unix)
WebServer to PHP Interface 	fpm-fcgi
Joomla! Version 	Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18744">issues.joomla.org/tracker/joomla-cms/18744</a>.</sub>

**Comment by brianteeman** [comment]
closing as a duplicate report of #17195
