### ISSUE TITLE
Module search in admin panel with spaces (before or after phrase)

### ISSUE THREAD

**Issue by boomsya** [joomla/joomla-cms#18747]
### Steps to reproduce the issue
1. goto modules list in admin panel
2. look at first module name (example "News")
3. type " News" - with space before (or after) module name in filter
4. click search

### Expected result
1. in previous versions filter truncate spaces before or after and search modules

### Actual result
1. no modules founded

### System information (as much as possible)
Joomla 3.8.1

**Comment by brianteeman** [comment]
I have tested on Joomla 3.6.5 and I cannot confirm that this worked before
If the module was called "News"
then a search for either " News" or "News " did not produce any results

**Comment by boomsya** [comment]
on Joomla 1.5 works :) fine
90% situation is when module name copy-paste from frontend and filter in admin panel. But browser adding spaces before and after of copied text and i must clear spaces manually everytime

**Comment by boomsya** [comment]
ha! but on page /administrator/index.php?option=com_installer&view=manage 
this works fine with spaces
i was typed " auth" and i have 2 lines:
"Authentication - Facebook"
"Google Authenticator"

//joomla 3.6.5

**Comment by mbabker** [comment]
The two can't be compared.  The Extension Manager does filtering at the PHP level after the query has been executed, the Module Manager is including the search term as a WHERE clause on the database query.

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 26th January 2018.

**Comment by boomsya** [comment]
can you apply trim(...) function to the searching term?

**Comment by ghost** [comment]
This has been closed as stated above – it can always be reopened.
