### ISSUE TITLE
Fatal error: Call to undefined method JApplicationSite::isClient() in /home/guide2trip/public_html/akclassycom/plugins/system/logout/logout.php on line 48

### ISSUE THREAD

**Issue by akclassy1** [joomla/joomla-cms#18750]
### Steps to reproduce the issue

Hi Guys,
I need your help in fixing the below error. I am using Joomla with a paid premium theme (JomClassifieds), when I log in my WordPress Account it showed me option to Update the Version. Once I clicked on that since then I am receiving this fatal error.

Fatal error: Call to undefined method JApplicationSite::isClient() in /home/guide2trip/public_html/akclassycom/plugins/system/logout/logout.php on line 48

Can someone help me in fixing this issue?

Thank you,
M Amer
akclassy1@gmail.com

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
