### ISSUE TITLE
[4.0] Installation folder not deleted even when checkbox says it will be

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18765]
### Steps to reproduce the issue

install joomla 4 alpha 2
see last screen has a checkbox - tick it

<img width="596" alt="screen shot 2017-11-20 at 21 33 33" src="https://user-images.githubusercontent.com/400092/33042743-ce437432-ce3a-11e7-8675-31453af91b90.png">

### Expected result

/installation/ folder is deleted

### Actual result

/installation/ folder is not deleted

**Comment by dgrammatiko** [comment]
I know you'll gonna hate me even more but this is a known issue according to: https://github.com/joomla/joomla-cms/pull/17964
<img width="550" alt="screen shot 2017-11-20 at 23 33 07" src="https://user-images.githubusercontent.com/3889375/33044955-4d70a54e-ce4b-11e7-896e-1451921905d6.png">

**Comment by brianteeman** [comment]
Set appropriate flags on this issue so it doesnt get missed or forgotten

**Comment by ghost** [comment]
@wilsonge Reopened for Project "[4.0] Installer"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18765">issues.joomla.org/tracker/joomla-cms/18765</a>.</sub>

**Comment by wilsonge** [comment]
Note to self: This is also blocking the rename of the robots.txt.dist file

**Comment by wilsonge** [comment]
See https://github.com/joomla/joomla-cms/pull/26276
