### ISSUE TITLE
[4.0] Your host needs to use PHP 7.0 or higher to run this version of Joomla!

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18764]
at the moment this is the abrupt end to someones first try with Joomla 4

`Your host needs to use PHP 7.0 or higher to run this version of Joomla!`

Maybe we could pretty that into a read error "page" that has some helpful reasons why PHP 7 is needed, some links to system requirements, documentation etc... 

Yes I know we didnt pretty it up in previous versions, but surely with Joomla 4 being able to save the world, and cure world hunger, I think we should try harder with this, that could become the first, and then last impression, someone has of Joomla...

**Comment by dgrammatiko** [comment]
Well unless we totally messed up something that page should look like: <img width="1279" alt="screen shot 2017-09-03 at 22 17 46" src="https://user-images.githubusercontent.com/3889375/30482631-8f08f55e-9a2c-11e7-8d7e-201132b9d549.png">

**Comment by PhilETaylor** [comment]
Then I would say something is messed up - cause I got a one liner.. unstyled.

**Comment by PhilETaylor** [comment]
Well that would screw it: 

https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/index.php#L20

**Comment by dgrammatiko** [comment]
Hmm, maybe we can improve that part then, we haven't really touched it since January

**Comment by PhilETaylor** [comment]
These need changing 

https://github.com/joomla/joomla-cms/blob/5e8ea37f2918abe4ba2e4c801bbdd6458cc8fdc5/index.php#L16

https://github.com/joomla/joomla-cms/blob/ab4555f397f909d1e7d6e781775c656351479d02/administrator/index.php#L20

**Comment by brianteeman** [comment]
@dgt41 Currently the static html error page is only shown if you have not installed joomla yet using the joomla installer

That is likely to be the most common way that someone would see it but they should also see the nice message when they 
1. downgrade php (perhaps by moving host)
2. use a hosting panel install script on an incompatible server (yes hosts are that stupid)

**Comment by PhilETaylor** [comment]
>  is only shown if you have not installed joomla yet using the joomla installer

A beginner doesnt get redirected from / to /installation/ because the die in /index.php

So unless a beginner manually types /installation/ in the url they will not currently see the pretty version :)

**Comment by dgrammatiko** [comment]
@PhilETaylor about the root and administrator indexes: probably yes, but if we do so then we should move the html+js to either front end or backend system template. Also your point for the installer entry.root vs ‘/installation/‘ is totally correct. Will try to submit a patch later on today, from the office

**Comment by ghost** [comment]
closed as having Pull Request #18777
