### ISSUE TITLE
[4.0] Remove dummy JSite class

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#18761]
### Steps to reproduce the issue
Given we've totally removed the JSite alias - either this class is going to fail super hard or isn't being used or there's some hella voodoo going on. https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_search/helpers/site.php

Let's figure out a way to get rid of it :)

**Comment by brianteeman** [comment]
anyone??

**Comment by wojsmol** [comment]
@wilsonge If github search is up-to-date then we only use this class once in  com_search model.

cc: @Hackwar

**Comment by wilsonge** [comment]
This has been done
