### ISSUE TITLE
[4.0] Error Save failed with the following error: Operand should contain 1 column(s)

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#18760]
I get this error when saving a user in backend.
The user is created though.

**Comment by ghost** [comment]
Similar:

![bildschirmfoto 2017-11-20 um 17 44 13](https://user-images.githubusercontent.com/8235763/33030021-74ce589c-ce1a-11e7-80f1-8bcf5f177da2.jpg)

**Comment by joomdonation** [comment]
PR for Operand should contain 1 column(s) error is https://github.com/joomla/joomla-cms/pull/18705. Please help testing so that we can have the issue sorted

**Comment by ghost** [comment]
closed as having Pull Request #18705.

Opened a new Issue for 2nd Issue #18770
