### ISSUE TITLE
Home page wrong url when home is a featured articles using 3.8 new routing system

### ISSUE THREAD

**Issue by JimJGitHub** [joomla/joomla-cms#18771]
URL get this now /?view=article&id=

### Expected result

url without id 

### Actual result

this url at the start /?view=article&id=

### System information (as much as possible)

PHP 7

 3.8 new routing system

### Additional comments
Home page wrong url when home is a featured articles menu

**Comment by JimJGitHub** [comment]
Updating Joomla 3.6.5 to Joomla 3.8.2

All urls on Home page are wrong url when home is a featured articles menu

URL is now
http://www.joomla.com/?view=article&id=2222:actual-title-then

instead of http://www.joomla.com/category/actual-title-then

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla coding.

**Comment by JimJGitHub** [comment]
franz-wohlkoenig your link sugest that joomla updating is very risky job

**Comment by infograf768** [comment]
Well, in fact, it is a real 'modern' routing **known issue** for which no solution has been provided yet when clicking on th title of an article displayed in a featured menu item.

Below links in multilang, but same on monolanguage site
Legacy: `/index.php/en/2-category-all/3-article-all`
Modern: `index.php/en/?view=article&id=3:article-all`

To solve it and get a nice readable url, one has to create a "hidden" menu item to the category or categories.
Example of result in "modern" routing:
`index.php/en/category-list/article-all`

**Comment by JimJGitHub** [comment]
how to create this "hidden" menu item to the category or categories ?

**Comment by infograf768** [comment]
<img width="934" alt="screen shot 2017-11-21 at 09 09 32" src="https://user-images.githubusercontent.com/869724/33061268-c9f8185e-ce9b-11e7-9bbd-de67d9dd21f7.png">

Then do not display in menu
<img width="792" alt="screen shot 2017-11-21 at 09 09 56" src="https://user-images.githubusercontent.com/869724/33061287-dfa6319a-ce9b-11e7-8be0-1b3a0246df7b.png">

But @franz-wohlkoenig  is right. This is a question to ask in forums as it is a known issue.

**Comment by JimJGitHub** [comment]
URL was
http://www.joomla.com/category/2222-actual-title-then
after update to Joomla 3.8.2 URL was
http://www.joomla.com/?view=article&id=2222:actual-title-then
URL is now
http://www.joomla.com/category-list/category/actual-title-then     
is this the best we can get form joomla now?
instead of http://www.joomla.com/category/actual-title-then

But @infograf768 I still think this isssue should be solved as a bug fix for 3.8.3 couse no solution has been provided yet in the forums

**Comment by csthomas** [comment]
Improvements are in PRs, Joomla needs only volunteers/testers who can test it.
After two human success test, the improvement can go as ready to commit (RTC)

If you have a little time please test https://github.com/joomla/joomla-cms/pull/18429
This is not directly related to your issue but is part of complex PR that will solve you problem.

It is a part of [Deterministic version of URL routing](https://github.com/joomla/joomla-cms/pull/17746). This one is not yet ready to be merged. I have to split it to more simpler PRs and update description.

Off course you can test it out and give a feedback.

**Comment by JimJGitHub** [comment]
@csthomas  on homepage I see this:
URL was
http://www.joomla.com/category/2222-actual-title-then
after update to Joomla 3.8.2 URL was
http://www.joomla.com/?view=article&id=2222:actual-title-then
URL is now
http://www.joomla.com/category-list/category/actual-title-then
is this the best we can get form joomla now?
instead of http://www.joomla.com/category/actual-title-then

but if I write in the browser http://www.joomla.com/category/actual-title-then it displays that article corect, but if I go to homepage it adds and displays http://www.joomla.com/category-list/category/actual-title-then

**Comment by csthomas** [comment]
This conversation should be on forum.

You do not need `category-list` menu item for categories view.
You need a published menu item for mentioned category 'category' and probably for all your categories as well.
As I see you remove IDs from URLs. 

The modern routing does not  work correctly for articles if they do not have menu item (at least one) for own or parent category. The simple solution is to add menu for root category-list as @infograf768 mentioned but that change your URL.

If you still has a problem please open a topic on forum and paste a screen-shot of you menu list/structure from backend.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18771">issues.joomla.org/tracker/joomla-cms/18771</a>.</sub>

**Comment by JimJGitHub** [comment]
@franz-wohlkoenig this issue with Joomla 3.8 URLs is not solved

The modern routing does not work correctly for articles even if they do have menu item for own or parent category

The problem is with FEATURED articles? what category you sugest to use for them if you think the issue is solved ?

on homepage I see this:
URL was
http://www.joomla.com/category/2222-actual-title-then
after update to Joomla 3.8.2 URL was
http://www.joomla.com/?view=article&id=2222:actual-title-then
URL is now
http://www.joomla.com/category-list/category/actual-title-then
is this the best we can get form joomla now?
instead of http://www.joomla.com/category/actual-title-then

but if I write in the browser http://www.joomla.com/category/actual-title-then it displays that article corect, but if I go to homepage it adds and displays http://www.joomla.com/category-list/category/actual-title-then

**Comment by JimJGitHub** [comment]
@franz-wohlkoenig  is there a documentation how to setup Joomla 3,8,2 that on home page joomla could provide correct urls for featured articles?

URL is now
http://www.joomla.com/category-list/category-one/actual-title-then
http://www.joomla.com/category-list/category-two/actual-title-then-here
is this the best we can get form joomla now?
instead of http://www.joomla.com/category-one/actual-title-then
                http://www.joomla.com/category-two/actual-title-then-here

**Comment by Hackwar** [comment]
simply make the home menu item a category blog menu item and select the root category as the category.

**Comment by infograf768** [comment]
> simply make the home menu item a category blog menu item and select the root category as the category.

There is no way to choose a Root Category in the category blog menu item. One can only choose a specific category, would it be a parent or not.

**Comment by neoacevedo** [comment]
I am understanding all. Is a similar issue to me also. I need an URL like
<http://domain>**/category/article** in a simple mode, just like WordPress does (if an article has a category, this category is shown in the URL, but else, only shows the article name in the URL). The question is why Joomla router doesn't build the URL in this mode.

An article is attached to a category. The logic router should build the URL as the previous one, but instead the URL sometimes are build as <http://domain>**/article** if the article is called from menu.

@infograf768 "root category" means any category that is at first level and has nested categories.

**Comment by ghost** [comment]
@neoacevedo Can you please open a new Issue as Comments on closed Issues didn't get much Notice, thanks.
