### ISSUE TITLE
Captcha not displayed when $class not set

### ISSUE THREAD

**Issue by dennisheiden** [joomla/joomla-cms#18773]
### Steps to reproduce the issue

```
JPluginHelper::importPlugin('captcha');
$dispatcher = JDispatcher::getInstance();
$arr = $dispatcher->trigger('onInit', 'dynamic_recaptcha_1');
echo $arr[0];
```

### Expected result

`<div id="dynamic_recaptcha_1" class="g-recaptcha " data-sitekey="SITEKEY_TOKEN" data-theme="light" data-size="compact"></div>`

### Actual result

`<div id="dynamic_recaptcha_1" data-sitekey="SITEKEY_TOKEN" data-theme="light" data-size="compact"></div>`

### System information (as much as possible)

Joomla 3.8.2
PHP 7.0.25
Apache
Linux -- 3.13.0-135-generic #184-Ubuntu SMP Wed Oct 18 11:55:51 UTC 2017 x86_64

### Additional comments

I think the bug is in plugins/captcha/recaptcha/recaptcha.php line 92

```
public function onDisplay($name = null, $id = 'dynamic_recaptcha_1', $class = '')
	{

		if ($this->params->get('version', '1.0') === '1.0')
		{
			return '<div id="' . $id . '" ' . $class . '></div>';
		}
		else
		{
			return '<div id="' . $id . '" ' . **str_replace('class="', 'class="g-recaptcha ', $class)**
					. ' data-sitekey="' . $this->params->get('public_key', '')
					. '" data-theme="' . $this->params->get('theme2', 'light')
					. '" data-size="' . $this->params->get('size', 'normal')
					. '"></div>';
		}
	}
```

The str_replace will only work if $class is containing 'class="', I don't think, that this does make any sense at all.

**Comment by Quy** [comment]
Per the docblock:
```
	 * @param   string  $class  The class of the field. This should be passed as
	 *                          e.g. 'class="required"'.
```

Changing:
```
public function onDisplay($name = null, $id = 'dynamic_recaptcha_1', $class = '')
```
to the following should fix this issue:
```
public function onDisplay($name = null, $id = 'dynamic_recaptcha_1', $class = 'class=""')
```

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 26th January 2018.

**Comment by Quy** [comment]
See PR #19190

**Comment by Quy** [comment]
@dennisheiden Please test PR #19190.
