### ISSUE TITLE
[4.0] Articles view=archive: Class 'Joomla\Component\Content\Site\View\Archive\JText' not found

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#18778]
### Steps to reproduce the issue
Open /index.php/archived-articles?view=archive, got:

![bildschirmfoto 2017-11-21 um 15 39 56](https://user-images.githubusercontent.com/8235763/33078346-afffb1be-ced2-11e7-9bab-89e9c3413458.jpg)
### System information
4.0.0-dev
Multilanguage Site (4 Lang.) & Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/18780

**Comment by ghost** [comment]
closed as having Pull Request #18780
