### ISSUE TITLE
[4.0] Save new User > Error "Could not instantiate mail function"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#18770]
### Steps to reproduce the issue
Create a new User and save, get:

![bildschirmfoto 2017-11-20 um 17 44 13](https://user-images.githubusercontent.com/8235763/33030021-74ce589c-ce1a-11e7-80f1-8bcf5f177da2.jpg)
### System information
4.0.0-dev
Multilanguage Site (4 Lang.) & Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by ghost** [comment]
related to #18596?

**Comment by ghost** [comment]
User is saved, enabled and activated.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18770">issues.joomla.org/tracker/joomla-cms/18770</a>.</sub>

**Comment by infograf768** [comment]
I can't reproduce here

**Comment by brianteeman** [comment]
@franz-wohlkoenig make sure that your test server is able to send mail - perhaps test with the contact form. If it cannot then this is the expected behaviour.

**Comment by ghost** [comment]
closed as expected Behaviour, thanks for Answers.

As far as i remeber its about MAMP.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18770">issues.joomla.org/tracker/joomla-cms/18770</a>.</sub>
