### ISSUE TITLE
[4.0] com_users routing issue

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#18774]
### Steps to reproduce the issue
Install latest Joomla 4 branch with sample data. Check urls of the following pages:

- Login /index.php/login?view=login
- Forgot username: /index.php/username-reminder?view=remind
- Forgot password; /index.php/password-reset?view=reset

### Expected result
Url should not contain view in query string, so;
- Login /index.php/login
- Forgot username: /index.php/username-reminder
- Forgot password; /index.php/password-reset

### Actual result
Urls still contain view in query string (which is not needed)

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18774">issues.joomla.org/tracker/joomla-cms/18774</a>.</sub>

**Comment by csthomas** [comment]
You should have the same on 3.8 with modern routing. 
Please test PR from 3.8 https://github.com/joomla/joomla-cms/pull/18429 on branch 4.0-dev or 3.8

```bash
curl https://patch-diff.githubusercontent.com/raw/joomla/joomla-cms/pull/18429.diff | git apply
```

**Comment by joomdonation** [comment]
@csthomas I did a quick code review at your PR and it looks OK to me. I will check it more carefully before posting my test result. Will try to get it merged to staging, so I will close this issue now
