### ISSUE TITLE
[com_fields] When creating custom form field that extends list field, is not possible to add custom attr to each option

### ISSUE THREAD

**Issue by angelovianajr** [joomla/joomla-cms#18787]
When creating a custom form field, is possible extend from another filelds, ex.: `JFormFieldList`, `JFormFieldText`. And when extend of this filelds, is usual to override the `getInput()` or `getOptions()` methods. 

Now, I'm extending `JFormFieldList`, and I want to keep the original `getInput()` but adding a custom attribute to each option of select.

I think that this to work, the ideal would be to add some property to the option, and on the HTML renderer `options()` function read this attr and add to the generated html

Below, how I want to override `getOptions()`
```
    protected function getOptions(){
        $options = parent::getOptions();
        foreach ($options as $option) {
            $option->attr="myattr='valueofmyattr'";
        }
        return $options;
    }
```

**Comment by ghost** [comment]
@laoneo any Clue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18787">issues.joomla.org/tracker/joomla-cms/18787</a>.</sub>

**Comment by laoneo** [comment]
Yes something like that can work. But I think it is better to ask in the forum.

**Comment by ghost** [comment]
@angelovianajr as @laoneo suggested please ask help on the [forums](https://forum.joomla.org/). (this repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks).

@laoneo thanks for Info.
