### ISSUE TITLE
Backend: Unable to display Modules with access permission set to "Guest"

### ISSUE THREAD

**Issue by kostalasa** [joomla/joomla-cms#18788]
### Steps to reproduce the issue

Go to J! backend
Create a new module (or modify an existing)
Set the access to "Guest"
Go to search
Filter by access = Guest

### Expected result
Joomla should display modules set with Guest permission when the appropriate filter is applied.

### Actual result
Joomla displays null (nothing)

### System information (as much as possible)
Database Version	5.6.36-82.1-log
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.25
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.8.2 Stable [ Amani ] 7-November-2017 15:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments
The only way to access a module with guest access is via PHP MyAdmin

**Comment by alikon** [comment]
solved by #18548
