### ISSUE TITLE
Problem with TinyMCE

### ISSUE THREAD

**Issue by neo191987** [joomla/joomla-cms#18790]
Hi i have a few problems with TinyMCE.  I created two skins, one for administration of other front end. The problem is the following: the skin that is set for the front end is also applied to the administration although another skin is set. Also, I can not disable read file editor.css, although I've enabled this feature.

**Comment by brianteeman** [comment]
Make sure that you have set the options correctly for EACH group

**Comment by neo191987** [comment]
Fixed. Thanks. I had not noticed that.
