### ISSUE TITLE
[4.0] How should the new php error page be translated

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#18798]
### Steps to reproduce the issue

https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/system/js/error-locales.js

### Expected result

Anyhow this can be translated maybe using the joomla ini files or the translation is commited to the core?

### Actual result

I don't see where i we can translate this

### Additional comments

Would be great to know how to translate this: cc @dgt41 @wilsonge 😄

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/pull/18777 Sorry out at the moment but it’s in the docs for this PR :)

**Comment by zero-24** [comment]
ok found it thanks 👍
