### ISSUE TITLE
[4.0] Remove jQuery UI dependency

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#18794]
If I'm not mistaken, jQuery UI was only ever used in Joomla to sort the rows in list views. Seeing as we have moved to Dragula, we can remove the jQuery UI dependency.

- [ ] Deprecate JHtml `ui` function in 3.x
- [ ] Remove JHtml `ui` function in 4.0
- [x] Convert subform fields to custom element
- [x] TinyMCE (`tinymce-builder.js`)

**Comment by dgrammatiko** [comment]
Calling @wilsonge and @mbabker here for a decision

**Comment by wilsonge** [comment]
Their repo seems pretty much abandoned. Nothing much done in the last 3-6 months.

Do we know what the migration from a code perspective form jquery ui to Dragula is like? I have no problem killing jquery ui. Just want an easy’ish transition for people doing drag + drop

**Comment by dgrammatiko** [comment]
Comparing the effort for the sortable->draggable I'll say it's a couple days work: https://github.com/joomla/joomla-cms/commit/17b8f67f54fd027ea15965ca8a492f4b3f55c971

**Comment by Fedik** [comment]
@C-Lodder add to list https://github.com/joomla/joomla-cms/blob/4.0-dev/media/editors/tinymce/js/tinymce-builder.js

**Comment by Fedik** [comment]
hm, I tried to add Dragula.js to subform.js but cannot get "sorting" to work, 
it just ignores it

**Comment by dgrammatiko** [comment]
@Fedik what is the branch you’re working?

**Comment by Fedik** [comment]
this one https://github.com/Fedik/joomla-cms/tree/subform-dragula
it start "drag", but "drop" does nothing

**Comment by Fedik** [comment]
this seems works fine https://github.com/Shopify/draggable/tree/master/src/Sortable
but it still in Beta, and do not have "pre compiled" version, or I have missed something

**Comment by dgrammatiko** [comment]
@Fedik but do we need a precompiled version? I mean if we implement subform as a custom element then we can import the parts we need from the draggable. Still we need to figure out how to pack all this in a single file and transpile it to es5 but I think it wouldn't be so hard at the end

**Comment by Fedik** [comment]
> but do we need a precompiled version?

I would like to keep it separated "here is sortable.js and there is subform.js", so sortable.js can be reused,
but we also can merge to single file, if need.

but it still in beta state 😉 
not sure for now

**Comment by dgrammatiko** [comment]
@Fedik do you have a branch with the code, can I take a look at?

**Comment by Fedik** [comment]
this time I just made a quick tests to replace "jQuery UI sortable" , and then cleaned all 😄 
I will try to make something tomorrow, and will share

btw, this is also looks cool https://lukasoppermann.github.io/html5sortable/index.html
only problem that the mobiles does not support html5 `dragable`

**Comment by Fedik** [comment]
@dgt41 there a test with use of their CDN ~~https://github.com/joomla/joomla-cms/compare/4.0-dev...Fedik:subform-sortable~~

there full example with custom element #19184

**Comment by wilsonge** [comment]
PRs
Removal: https://github.com/joomla/joomla-cms/pull/28341
Deprecation: https://github.com/joomla/joomla-cms/pull/28342
