### ISSUE TITLE
[4.0] Debug console styling makes it unuseable in default template

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#18795]
### Steps to reproduce the issue
Joomla 4 alpha 2
enable debug mode
Debug console styling makes it unuseable in default template

### Actual result
<img width="1234" alt="screen shot 2017-11-22 at 18 31 42" src="https://user-images.githubusercontent.com/400092/33143984-87a2e2fe-cfb3-11e7-98f2-3d0b4890ade5.png">

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18795">issues.joomla.org/tracker/joomla-cms/18795</a>.</sub>

**Comment by ciar4n** [comment]
PR created.. #18837

**Comment by ghost** [comment]
closed as having Pull Request #18837
