### ISSUE TITLE
[4.0] Sample data doesn't install

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#18792]
### Steps to reproduce the issue
Install 4.0.0 dev on localhost
Click customise
Skip the language
Click to install sample data 

### Expected result
Sample data is installed or a screen offering various sample data is presented

### Actual result
A faded error message flashes on the screen ... no sample data installed

### System information (as much as possible)
Installing sample data in administration No Avail ... the screen gets stuck

**Comment by brianteeman** [comment]
Updated title to show for J4

**Comment by Bakual** [comment]
I'm quite sure there is already a report for that. It isn't an issue with the sample data itself. From memory the problem is that `JModelLegacy::getInstance()` is broken.

**Comment by Bakual** [comment]
Found it.
Closed as duplicate of https://github.com/joomla/joomla-cms/issues/17705
