### ISSUE TITLE
Joomla 4 / Installation / Database Type not showing in drop down

### ISSUE THREAD

**Issue by guydumais** [joomla/joomla-cms#18805]
### Steps to reproduce the issue
[your_site_url]/installation/index.php

### Expected result
List of database types (MySql, PostgreSQL, etc.)

### Actual result
Only PostgreSQL showing:
![jommla4-bug](https://user-images.githubusercontent.com/3584604/33152259-d0ef2fa8-cfa9-11e7-8458-a80022135723.png)

My PHP Settings at GoDaddy:
![jommla4-bug-php-settings](https://user-images.githubusercontent.com/3584604/33152322-09b4bdc6-cfaa-11e7-9fd4-ce27e653386d.png)

**Comment by zero-24** [comment]
mysqli is not installed / enabled given to your screenshot ;)

**Comment by guydumais** [comment]
It is CHECKED on the screenshot. I don't understand?

**Comment by zero-24** [comment]
![image](https://user-images.githubusercontent.com/2596554/33152738-822a4b52-cfde-11e7-9f0c-2fa05a0280d4.png)

**Comment by guydumais** [comment]
![jommla4-bug-php-settings2](https://user-images.githubusercontent.com/3584604/33152769-6f4fd420-cfac-11e7-9b72-8d8653d3ed18.png)

**Comment by zero-24** [comment]
this is a complete different screenshot ;) What is about the nd_mysqli extension?

**Comment by guydumais** [comment]
BINGO! Thanks @zero-24 :)

I checked the **nd_mysqli** extension then Save. The system replied with **MYSQLI SKIPPED AS CONFLICTING**. Here are the right settings to show MYSQLI in the Dropdown:
![jommla4-bug-php-settings3](https://user-images.githubusercontent.com/3584604/33153201-b75d748c-cfae-11e7-9bf8-91a3c3f074bc.png)
