### ISSUE TITLE
[4.0] incompatible.html page title is not translatable

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#18807]
### Steps to reproduce the issue

https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/system/incompatible.html#L8

### Expected result

Be able to translate `Joomla: unsupported PHP version`

### Actual result

Unable to translate `Joomla: unsupported PHP version` == the title of the page

### Additional comments

maybe similar code like for the other strings possible?

**Comment by dgrammatiko** [comment]
Fair, this needs to be done, again, with javascript, since we don't have much (actually noting) on the backend. Will do a PR
