### ISSUE TITLE
[4.0] Extensions: Install Languages / Unable to find install package

### ISSUE THREAD

**Issue by guydumais** [joomla/joomla-cms#18809]
### Steps to reproduce the issue
1) Administration console
2) Extensions
3) Language(s)
4) Install Languages
5) Click any button called INSTALL

### Expected result
Language added

### Actual result
Error message popup:
**Unable to find install package**

### Additional comments
FRESH NEW INSTALL

**Comment by brianteeman** [comment]
If  remember correctly that is because there are no available translation uet

**Comment by infograf768** [comment]
> If remember correctly that is because there are no available translation uet

It still works for French, German and Persian for test purposes

We also get a Notice btw
PHP Notice:  Trying to get property of non-object in /administrator/components/com_installer/Model/InstallModel.php on line 388

**Comment by infograf768** [comment]
Closing as expected behaviour.
