### ISSUE TITLE
[4.0] Menus, Menu Items, Associations managers missing filters

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#18815]
### Steps to reproduce the issue
For Menus: the Client filter is missing.|
For Menu items : The Client and Menu filters are missing
For a multilingual site: The Item Type and Language filters are missing.

### Additional comments
Looks like the Searchtools Layouts are broken.

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18815">issues.joomla.org/tracker/joomla-cms/18815</a>.</sub>

**Comment by infograf768** [comment]
@C-Lodder 
@laoneo 

This issue is really bothering as we can't test Menus/Menu items/associations in order to solve other bugs.

Basically, as far as I could see: the global searchtools layout default.php  `$selectorFieldname` accepts only one field and not an array which prevents displaying 2 separate fields in the bar.

The menus and associations layout searchtools overrides are old code which anyway have to be totally modified or deleted for these 2 components.

Once deleted for com_menus, we can easily solve the Menus Manager by changing code in 
`/administrator/components/com_menus/tmpl/menus/default.php` line 43 to
`<?php echo JLayoutHelper::render('joomla.searchtools.default', array('view' => $this, 'options' => array('selectorFieldName' => 'client_id'))); ?>`

But although we can do the same for Menu Items, we will not get the menutype filter as there is no way in code to add it to the client_id

**Comment by C-Lodder** [comment]
Will take a look tonight hopefully

**Comment by infograf768** [comment]
@C-Lodder 
While you are at it and as we have now `noresults`, please modify the tpl for menus/ menus items and modal.
I.e. we should have
```
				<?php if (!empty($this->items)) : ?>
					<table class="table table-striped" id="itemList">
```

and NOT
```
			<?php if (empty($this->items)) : ?>
					<joomla-alert type="warning"><?php echo JText::_('COM_LANGUAGES_MULTILANGSTATUS_NONE'); ?></joomla-alert>
				<?php else : ?>
					<table class="table table-striped" id="itemList">
```
which anyway makes no sense at all....

**Comment by C-Lodder** [comment]
@infograf768 so remove the alert? I thought alerts were always displayed in Joomla when no results were found...

**Comment by infograf768** [comment]
the alert is obtained by

```
<field
			name="search"
			type="text"
			hint="JSEARCH_FILTER"
			noresults="JGLOBAL_NO_MATCHING_RESULTS"
		/>
```
new in 4.0

**Comment by infograf768** [comment]
/Applications/MAMP/htdocs/installmulti/joomla40/administrator/components/com_cache/forms/filter_cache.xml:19: 			noresults="JGLOBAL_NO_MATCHING_RESULTS"
/Applications/MAMP/htdocs/installmulti/joomla40/administrator/components/com_checkin/forms/filter_checkin.xml:10: 			noresults="COM_CHECKIN_NO_ITEMS"
/Applications/MAMP/htdocs/installmulti/joomla40/administrator/components/com_languages/forms/filter_installed.xml:19: 			noresults="JGLOBAL_NO_MATCHING_RESULTS"
/Applications/MAMP/htdocs/installmulti/joomla40/administrator/components/com_menus/forms/filter_items.xml:29: 			noresults="JGLOBAL_NO_MATCHING_RESULTS"
/Applications/MAMP/htdocs/installmulti/joomla40/administrator/components/com_menus/forms/filter_itemsadmin.xml:32: 			noresults="JGLOBAL_NO_MATCHING_RESULTS"
/Applications/MAMP/htdocs/installmulti/joomla40/administrator/components/com_modules/forms/filter_modules.xml:20: 			noresults="COM_MODULES_MSG_MANAGE_NO_MODULES"
/Applications/MAMP/htdocs/installmulti/joomla40/administrator/components/com_modules/forms/filter_modulesadmin.xml:23: 			noresults="COM_MODULES_MSG_MANAGE_NO_MODULES"
/Applications/MAMP/htdocs/installmulti/joomla40/administrator/components/com_templates/forms/filter_styles.xml:19: 			noresults="COM_TEMPLATES_MSG_MANAGE_NO_STYLES"
/Applications/MAMP/htdocs/installmulti/joomla40/administrator/components/com_templates/forms/filter_templates.xml:19: 			noresults="COM_TEMPLATES_MSG_MANAGE_NO_TEMPLATES"
/Applications/MAMP/htdocs/installmulti/joomla40/components/com_modules/forms/filter_modules.xml:12: 			noresults="COM_MODULES_MSG_MANAGE_NO_MODULES"

**Comment by infograf768** [comment]
Which means it is not implemented all over J, for example in com_contents where we have the old style alert.

**Comment by infograf768** [comment]
a mess... what can I say...

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/19044

@infograf768 - please could you open a new issue for the `noresults` attribute you mentioned

**Comment by ghost** [comment]
closed as having Pull Request #19044

**Comment by infograf768** [comment]
> @infograf768 - please could you open a new issue for the noresults attribute you mentioned

I will. Thanks.

**Comment by infograf768** [comment]
Looks like this new attribute only works when the model includes the method `public function getTotal()`
I can make it work for com_menus and most other components with custom code.
