### ISSUE TITLE
Parent menu item alias missing in url

### ISSUE THREAD

**Issue by alagesanbe08** [joomla/joomla-cms#18819]
### Steps to reproduce the issue
Menu A alias menu-a
    -Menu B alias menu-b
    -Menu C alias menu-c

Site frontend
 i expected url for submenu article
http://example.com/menu-a/menu-b/{article_alias}
but i got
http://example.com/menu-b/{article_alias}
### Expected result
 i expected url for submenu article
http://example.com/menu-a/menu-b/{article_alias}

### Actual result
but i got
http://example.com/menu-b/{article_alias}

### System information (as much as possible)

Database Version - 5.6.36-82.1-log
Database Collation - utf8_general_ci
PHP Version - 7.0.25
Web Server - Apache
Joomla! Version - Joomla! 3.8.2 Stable 
User Agent - Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by tonypartridge** [comment]
Is there another menu b on the first level?

**Comment by csthomas** [comment]
If `Menu A alias menu-a` is your home page then this is expected behaviour.

**Comment by brianteeman** [comment]
If this gets no response it will be closed in a few days

**Comment by alagesanbe08** [comment]
Yaa, Menu b in first level

**Comment by alagesanbe08** [comment]
its not from core, its from external system plugin. anyway Thks :)
