### ISSUE TITLE
[4.0] [com_fields] htmlspecialchars() expects parameter 1 to be string

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#18812]
### Steps to reproduce the issue
Go under Configuration > Contacts > Contact
Go to the bottom of page
See `Show User Custom Fields`

### Expected result
Display switch

### Actual result
<br /><b>Warning</b>:  htmlspecialchars() expects parameter 1 to be string, array given in <b>C:\xampp\htdocs\joomla-cms-4.0-dev\layouts\joomla\form\field\text.php</b> on line <b>94</b><br />

### System information (as much as possible)
4.0 alpha2

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18812">issues.joomla.org/tracker/joomla-cms/18812</a>.</sub>

**Comment by Quy** [comment]
Duplicate #17213
