### ISSUE TITLE
[4.0] Improve responsive design?

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#18823]
The Installer works and is a short width tall setup which is fine for mobile devices. but on my big desktop it's a bit of a mess. Can we put the boxes side by side? See attached of the issue. They could be side by side 
<img width="2400" alt="screen shot 2017-11-23 at 11 35 56" src="https://user-images.githubusercontent.com/1400982/33171052-ab014a30-d042-11e7-8107-1092d50921f8.png">

**Comment by dgrammatiko** [comment]
Let's call the experts then: @ciar4n @coolcat-creations

**Comment by coolcat-creations** [comment]
Why do you consider that as a mess? It's quite compact and clean?
We can try to make this font and container scaling thing Vitaly showed in his session at jwc, but for me it looks perfectly fine? 
Just if the Joomla Logo is really cut of, that would need fixing of course.

**Comment by brianteeman** [comment]
If you move the logo and lightbulb closer to the text then it will look fine - it will just seam that the blue is a background

**Comment by tonypartridge** [comment]
Because on a bigger screen I need to focus my eyes lower, opposed to if it is on one line my eyes are already at that level no need to move them. Which means less effort/interaction.

**Comment by mbabker** [comment]
Agree with Brian.  If you move the outside graphics in closer IMO it's fine.  I don't see the need for it to be one line personally, it's a natural flow the way it is now (at least in English the natural reading direction is left-to-right and up-to-down and the layout follows that, putting the boxes next to each other breaks that natural flow IMO plus makes the display more open for debate when you start getting into RTL languages).

**Comment by tonypartridge** [comment]
To me it looks crap on a big desktop, but I’m Manx so hey ho!

**Comment by ciar4n** [comment]
Current....

![image](https://user-images.githubusercontent.com/2803503/33184701-cd8fbbc6-d075-11e7-93fb-4415d0ef58ee.png)

Moving the outside graphics in closer.. 

![image](https://user-images.githubusercontent.com/2803503/33184454-9eecb888-d074-11e7-9019-927d9e818b8f.png)

Moving them in line with the 'steps'...

![image](https://user-images.githubusercontent.com/2803503/33184506-da0b9272-d074-11e7-99f7-beb38ce394ab.png)

Separating the header with some shading...

![image](https://user-images.githubusercontent.com/2803503/33184596-4a71f6dc-d075-11e7-8885-9ad6e4b9f08c.png)

**Comment by dgrammatiko** [comment]
> Moving them in line with the 'steps'...

+1000

**Comment by coolcat-creations** [comment]
Inline with the steps + 1

**Comment by ghost** [comment]
Moving them in line with the 'steps'...

**Comment by coolcat-creations** [comment]
How big is your desktop? I look at it at 34" and it's fine? 
> To me it looks crap on a big desktop, but I’m Manx so hey ho!

**Comment by ciar4n** [comment]
@coolcat-creations what resolution (eg. 1920×1080)?

**Comment by tonypartridge** [comment]
27” iMac at 5120 x 2880 pixel

It looks like a 2001 website where you had fixed width of 680px.

Maybe I’m just not with the Trend of single long views, but when you have the real estate I prefer to fill it

**Comment by ciar4n** [comment]
We could increase the general width on just xl screens (2560+)...

![image](https://user-images.githubusercontent.com/2803503/33186888-43390fbc-d085-11e7-884d-04ffbcf48535.png)

**Comment by coolcat-creations** [comment]
Looks not compact anymore for me, and long lines are hard to read for some. I would prefer the compact view with the empty space like it's now. "Whitespace" is something positive IMHO.

**Comment by dgrammatiko** [comment]
@tonypartridge I think you can still resize your browser's window, hopefully we didn't break that 😜

**Comment by C-Lodder** [comment]
+1 for moving them inline with the form.

I'd normally say option 4, but because there's a help icon, it should to be in the FOV

**Comment by GeraintEdwards** [comment]
+! for inline with steps

**Comment by ghost** [comment]
@wilsonge Reopened for Project "[4.0] Installer".

**Comment by coolcat-creations** [comment]
I'd recommend to contribute changes into the backend-template repo joomla/backend-template

**Comment by Quy** [comment]
@tonypartridge Do you consider this still an issue with the new backend template?

**Comment by alikon** [comment]
related to the old template, open a new issue if needed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18823">issues.joomla.org/tracker/joomla-cms/18823</a>.</sub>
