### ISSUE TITLE
[4.0 Installer] - Can't do anything when error

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#18822]
Start installer, enter wrong Database password. You are presented with:

An error has occurred while processing your request.

and the SQL error. 

You cannot edit the data and then proceed to try again. 

Also the Lightbulb top right does nothing.

**Comment by tonypartridge** [comment]
Ok, it's caused because we write the the configuration.php file before actually testing the details....

**Comment by ghost** [comment]
Similar to #18834?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18822">issues.joomla.org/tracker/joomla-cms/18822</a>.</sub>

**Comment by Fedik** [comment]
it same as #18557

**Comment by ghost** [comment]
closed as duplicate Report #18557 

Thanks for Hint @Fedik
