### ISSUE TITLE
Improve Empty Trash

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#18828]
To empty the trash we have to select the trash items first. It would make more sense if clicking empty trash and nothing is ticked we prompt with a warning, this will remove all items within your trash, click ok to proceed.

then we just delete every item within the trash?

**Comment by ghost** [comment]
+1

**Comment by gwsdesk** [comment]
+1

**Comment by dgrammatiko** [comment]
@tonypartridge I guess then the trashcan should be available either in the menu or the dashboard (similar to OSX's desktop + dock icon)

**Comment by brianteeman** [comment]
@dgt41 that would mean delete everything in the trash. And not just delete all the articles in the trash etc

**Comment by coolcat-creations** [comment]
+1 for @dgt41 Lot of Endusers don't understand Trash is a "status", it's a place like in the os where everything goes in ...

**Comment by gwsdesk** [comment]
-1 @coolcat-creations This would mean that the option for restoring accidentally "trashed" items will be almost taken away...Trash is trash so get rid pf it.... I believe we created the Status "Trashed" to keep the option open to restore. How often have I regretted "emptying my trashcan" on my desktop. The trash status has been a saver for me dozens of times

**Comment by tonypartridge** [comment]
Ok @coolcat-creations @dgt41  @brianteeman, Lets go with a two phase option. 

1. Just update what we have and allow emptying trash without an item selection.

2. Build a Trash View, kinda like Global Checkin where you can see all items in trash and empty them all or individual components

**Comment by gwsdesk** [comment]
+1 for first option but great hesitation for the second

**Comment by ghost** [comment]
d'accord with @gwsdesk

**Comment by coolcat-creations** [comment]
My customers would definetly love 2 - They beg since years for something like that, but 1) is probably just a quick PR so let's do 1. and think about 2) in another year ;-)

**Comment by alikon** [comment]
3.x is feature freeze
please open a new one on 4.x if needed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18828">issues.joomla.org/tracker/joomla-cms/18828</a>.</sub>

**Comment by brianteeman** [comment]
@alikon please re-open and tag "re-evaluate for j4"

**Comment by alikon** [comment]
reoponed as requested<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18828">issues.joomla.org/tracker/joomla-cms/18828</a>.</sub>

**Comment by alikon** [comment]
@Quy or @franz-wohlkoenig can you change the label accordingly please

**Comment by brianteeman** [comment]
Please see #27429
