### ISSUE TITLE
[4.0] Installer footer links - colour contrast

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#18825]
The colour of the links in the footer need changing so they pass AA:

![footer](https://user-images.githubusercontent.com/2019801/33172731-38add92e-d049-11e7-97b4-354e8573c8ec.png)

Also need to be done for hover too.

**Comment by ghost** [comment]
Discussion at #18635<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18825">issues.joomla.org/tracker/joomla-cms/18825</a>.</sub>

**Comment by C-Lodder** [comment]
Closing for #18635
