### ISSUE TITLE
[4.0] Password Field icon shows wrong state

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#18832]
http://recordit.co/mL2rcDBds9

The icons for displaying the password or not is wrong. I expect it to show the current state in this case and if it's hidden the eye should be closed.

**Comment by ghost** [comment]
Correct, closed Eye should be used if Password is hidden.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18832">issues.joomla.org/tracker/joomla-cms/18832</a>.</sub>

**Comment by brianteeman** [comment]
I thought what you said makes sense - but I just logged in to windows 10 and that does exactly the same as we have right now. I also checked chrome and that does the same as microsoft. So It is not showing the state but showing the action eg click here to see the password

We might think its wrong but its what others do

**Comment by dgrammatiko** [comment]
Make it more obvious, green background when visible, red when scrambled. Just an idea

**Comment by brianteeman** [comment]
the round is wheel lets not reinvent it

**Comment by coolcat-creations** [comment]
1) The Joomla Logic is different. You have an icon with the current state. Otherwise you have to put a unpublish icon next to the published articles.
2) Same is the trash icon (inside trash) that restores an article instead of trashing it completely. When I asked to change it to a restore button argument 1 was the reply ;)

**Comment by brianteeman** [comment]
This should be closed. It is a non-issue. The rest of the web and applications do this exactly the way we are doing it now. The design pattern in use has been used for decades

> If the toggle is an action - Play/Pause - then it should show the thing that will happen. So while paused it would show Play and then while playing show Pause.

**Comment by coolcat-creations** [comment]
Please show examples for "the rest of the web" here is a google example:
![grafik](https://user-images.githubusercontent.com/828371/60322330-77b8b200-997f-11e9-8131-a320a7de5db8.png)
thank you.
