### ISSUE TITLE
[4.0] DB Options - Advanced Mode?

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#18835]
In the Database Options we don't have the possibility anymore to backup old tables. 
Do we really want to remove this feature or move it in something like an advanced installer or bring it back?

**Comment by ciar4n** [comment]
I'd say remove it. There is plenty other ways of keeping a copy of the old database. 

Having said that we should problem warn users that the database will be over written.

**Comment by dgrammatiko** [comment]
@ciar4n it's not (me thinks)

**Comment by coolcat-creations** [comment]
Can we detect if tables with the same prefix exist, and if so asking if the user wants to keep them or not?

**Comment by dgrammatiko** [comment]
> Can we detect if tables with the same prefix exist, and if so asking if the user wants to keep them or not?

Yes, once we promise-fy the client side, this would be easier (and is kinda our target) to achieve

**Comment by infograf768** [comment]
I have explained here why we do need this feature back as it does not only concerns Advanced users.
https://github.com/joomla/joomla-cms/pull/18797#issuecomment-346934570

**Comment by brianteeman** [comment]
I can only assume that in the intervening time the code has been changed and is no longer relevant.

If you try to install joomla on an existing database with an existing database prefix then the existing tables are renamed to bak_prefix_tablename

@franz-wohlkoenig this can be closed

**Comment by coolcat-creations** [comment]
But if the tables belong to another installation they should not be renamed.

**Comment by brianteeman** [comment]
no different to today with joomla 3

The only way that would happen would be if
1) you manually chose the same prefix - backup created - no change to today
2) the random prefix used for site 1 is the same random prefix as used for site 2. Almost never going to happen but as a safety measure a backup is created.

So what is the problem you want to solve?

**Comment by HLeithner** [comment]
Wasn't the plan to make the installer more simple? Normally you should never install 2 or more joomla installations into one database. The only reason why we have prefixes is because mysql does not support schemas and you often only get one database from the hoster... so in the end it's a workaround for a infrastructure problem out of scope of joomla...

Anyway if we make auto backups if there is a installation it would be fine for me, hopefully the user get an information that his old database get backuped.

Can be reopened if needed.

**Comment by coolcat-creations** [comment]
Should this not be leaved open to at least make sure we inform the user what happened 

> Normally you should never install 2 or more joomla installations into one database.

That's true for experienced users, but the plan is also to increase usability, so your recommendation to inform the user is for me mandatory. 

Something like 
- "We found another Joomla database tables in this database, for security reasons we recommend to... (...) " 
- "We found another Joomla database with the same prefix (...) if you click on continue the old tables will be backed up" 
Kind of...

**Comment by brianteeman** [comment]
Again - there is no change in behaviour to joomla 3 - its just that the backup is automatic now and not left to the user

**Comment by coolcat-creations** [comment]
Yes, I got you. Anyway we can improve the User Experience and lead them and inform them what is happening there.

**Comment by HLeithner** [comment]
Notifying the user should really be done. Silently moving an old database would be a bad experience. If someone writes a PR which include a decision before it get moved it would be ok to but only if needed and not always shown.

**Comment by brianteeman** [comment]
the code to remove old database or backup old database is still there. just a ui not present so easy to add it.

**Comment by bembelimen** [comment]
Just a thought: the better solution would be to suggest a really unique prefix (checking after generating it)

**Comment by Hackwar** [comment]
Yes, we could introduce an Ajax call to check for existing tables and then display a warning message that the tables exist and will be renamed, requiring further action from the user and... Or we introduce a message below the prefix field and thus close this issue, since we have a PR with #39215. If someone feels the need to change this, they can do this in the future, but we don't have to keep an issue open for 5 years without any solution. Anyway, thanks for the report and the discussion, I hope this solves the issue sufficiently.

**Comment by coolcat-creations** [comment]
Please do not close issues because there is no solution. An issue that is 5 years old should even get higher priority when there is still no solution.

**Comment by Hackwar** [comment]
I created a solution in the PR I linked.

**Comment by coolcat-creations** [comment]
Ok, why did you write "but we don't have to keep an issue open for 5 years without any solution."

**Comment by Hackwar** [comment]
Because if no one wants to do the totally proper solution with the AJAX call and all that stuff, then I'd rather provide the simple, not perfect solution and close a 5 year old issue, than keeping it open for yet another 5 years.

**Comment by coolcat-creations** [comment]
Fair enough ok!
