### ISSUE TITLE
[4.0] [Installer] Back Button is missing

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#18834]
We don't have the possibility to get a step back in the installer.

Either we would need to show the whole form and scroll in the form like it was in the beginning or have back buttons that reveal the last step.

**Comment by ghost** [comment]
To go back last Step would help.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18834">issues.joomla.org/tracker/joomla-cms/18834</a>.</sub>

**Comment by ghost** [comment]
duplicate Report of #18557?

**Comment by ghost** [comment]
closed in favor #24556
