### ISSUE TITLE
[4.0] Only one Complete Button and automatic redirect to the backend?

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#18833]
![image](https://user-images.githubusercontent.com/828371/33187025-e26955fc-d08e-11e7-96c4-427f5a8fbe0b.png)
Can the complete button be green and just one? It could redirect to the login page where there is a frontend link anyway?

Also it's not ready if i have still to complete something. So maybe "Almost ready" ?

**Comment by dgrammatiko** [comment]
> Also it's not ready if i have still to complete something. So maybe "Almost ready"

Depends on the outcome for sample data and extra languages, there is a debate to completely remove them from the installer

**Comment by mbabker** [comment]
> Also it's not ready if i have still to complete something. So maybe "Almost ready" ?

Technically it is ready.  The site's usable, there are just some optional extras you can add with the languages and sample data.  And unless we're going to add more conditional logic to detect when we actually enforce the "remove install directory" check, I don't think we need it to say "almost ready".

**Comment by coolcat-creations** [comment]
Then we don't need a complete because it's complete?

**Comment by brianteeman** [comment]
depends on if you think of it as an adjective or a verb? ;)

eg 
To complete the site open the admin
The site is complete you can now open the admin

**Comment by brianteeman** [comment]
Personally as the title is already saying "your site is ready" then you only need "Open Site" and "Open Administrator"

Note it is Administrator not admin see style guide

**Comment by coolcat-creations** [comment]
So if the installation folder is still there it's definetly not complete for most of the users. 
Is that option just on staging versions or always?

**Comment by mbabker** [comment]
It's always there.

Removing it is not a requirement unless the version class is set to a stable release, which only happens when we are building the release packages.  When running from the git repo, it's not enforced.

**Comment by khu5h1** [comment]
@brianteeman May we go with `Open site` and `Open admin` options instead of using `Complete`.  I have understood it I may create a PR for this if it sounds good.

**Comment by richard67** [comment]
@coolcat-creations Does PR #35988 solve it for you? Or should there be done more?

**Comment by richard67** [comment]
As far as I can see the PR solves only a part of it, i.e. it still leaves 2 buttons.

**Comment by wilsonge** [comment]
I'm happy to take pull requests to improve the installer at any point. But going to close this for now as it's unlikely anything more is going to happen here given it's sat here for 3 years with no PRs and there's no clear proposals on how to improve the UX further.
