### ISSUE TITLE
[4.0] Indicate that all fields are filled with green button

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#18831]
![image](https://user-images.githubusercontent.com/828371/33186831-197c7cec-d08d-11e7-9073-9664d7e7e2a8.png)

Can the next buttons e.g. "Setup Login Data" turn green when the mandatory fields are filled ?

**Comment by ghost** [comment]
Wouldn't do that (too much Colors).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18831">issues.joomla.org/tracker/joomla-cms/18831</a>.</sub>

**Comment by dgrammatiko** [comment]
How about:
the next button is by default disabled until everything needed is filled and correct?

PS I need to check if this is even possible in a logical amount of code...

**Comment by coolcat-creations** [comment]
Yes that would work too, then the button is greyed out until all important fields are filled, right?

**Comment by brianteeman** [comment]
Interesting seeing this today after reading this tweet and the follow up conversations

![image](https://user-images.githubusercontent.com/1296369/64825950-061ff580-d5b7-11e9-8411-4da74bc8df7f.png)


https://twitter.com/adambsilver/status/1170954800374173696

**Comment by coolcat-creations** [comment]
closing as not relavant anymore
