### ISSUE TITLE
[4.0 Installer] User icon instead heart icon

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#18830]
On the Login Data page, please use the user icon instead of the heart icon. I don't associate heart with user account(s).

**Comment by coolcat-creations** [comment]
+1 

User icon and Changing the Title to "Joomla Super Administrator Login" - or something that makes clear in the heading that it's the Super Admin instead of always repeating it in the labels below.

**Comment by C-Lodder** [comment]
Already part of this PR: https://github.com/joomla/joomla-cms/pull/18797

**Comment by ghost** [comment]
closed as having Pull Request #18797
