### ISSUE TITLE
[4.0] `No Matching Results` alert background color

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#18849]
The alert background color for `No Matching Results` is blue in the control panel and different elsewhere. They should be same.

**Comment by ghost** [comment]
How you get this Alert as there is noch search in Control Panel?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18849">issues.joomla.org/tracker/joomla-cms/18849</a>.</sub>

**Comment by Quy** [comment]
This is only an issue on a clean install when there are no `Recently Added Articles` and `Popular Articles`.

**Comment by C-Lodder** [comment]
Addressed in this PR: https://github.com/joomla/joomla-cms/pull/18872

**Comment by ghost** [comment]
closed as having Pull Request #18872
