### ISSUE TITLE
[Feature Request] Improve Building a Multilanguage Site (Articles)

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#18845]
This issue was discussed with Shirat at JWC and we found a nice concept to improve working with Multilanguage Sites and it's content.

### Steps to reproduce the issue
If you have a Site with more languages you create one article in your main language, then you have to create it in the other language and create all the Associations first to be able to edit them in the Multilanguage Associations Component.

It would be nice to have an option to create automatically a "language-pack" when saving a new article that has no associations yet.

The article is copied to all languages, all associations are done and a default text in the language is added in front of the introtext that the article is not translated yet.

Means i have an Article in english that has:

**Article Title

This is my article text**

when Saving i can enable an plugin to create automatically:

German:

**Article Title

_*** Der Inhalt dieses Beitrages ist noch nicht übersetzt ***_

This is my article text**

(And the association is already done)

and so on.

Especially on Pages with a lot of languages this is a huge time saver.

**Comment by ghost** [comment]
+1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18845">issues.joomla.org/tracker/joomla-cms/18845</a>.</sub>

**Comment by infograf768** [comment]
In a tutorial I made some time ago, I explained we already can use to our advantage the batch functionality to gain a lot of time when creating a multilingual site. 
The idea is to create a first structure for the default site language with all contents according to the language.
In the following order
Main Menu, other Menus
Categories.
Articles.
Menu items.

Then create at least the default Main Menu for each language (and other Menus per language if necessary) as we can't use batch for Menus.
Then batch create categories for each language by copying the existing ones at the same level.
Then batch create articles for each language by copying the existing ones in their respective categories.
Then batch create menu items for each language by copying the existing ones.

IF we could do this in a single click that would indeed be great!

Then evidently starts the work to edit all these items and change accordingly to their language the titles, contents, etc. 

For that the Associations component is real useful and already displays items not associated which could be AND modified to fit the language.

There is no interest imho to add as introtext a specific phrase in the language used as anyway we already know in the Associations component that an item is not associated and therefore not yet modified.

**Comment by coolcat-creations** [comment]
I got this idea with the introtext from amazon documentation:
https://developer.amazon.com/de/docs/custom-skills/speechcon-reference-interjections-german.html

![grafik](https://user-images.githubusercontent.com/828371/33229818-13b681b8-d1d7-11e7-8dec-6c6ef19440b4.png)

They ensure to have every content available even if it's not translated yet.
I don't know if it's like a fallback or an article that has not been edited yet, but creating the whole language pack including all associations by creating the first article on a multilanguage site would save enormous time. Got a Website with 6 languages and it's a really boring job to do all the associations, even when using batch process. Just reminds me of the work on the Joomla 3.6 landingpage with 30+ languages ... that was really a pain.

**Comment by infograf768** [comment]
What I am saying is that, in any case, the associated item will have to be edited.
If it has been edited already and associated, this will show in com_associations, as well if it has not.

<img width="1200" alt="screen shot 2017-11-25 at 12 01 37" src="https://user-images.githubusercontent.com/869724/33229889-793510d0-d1d8-11e7-8a2b-d7894b8544b8.png">

**Comment by infograf768** [comment]
Also, we must not forget that associations is a much wider concept in Joomla than translations.

**Comment by coolcat-creations** [comment]
@infograf768 yes i know. But having that introtext at the top you'd be able just to publish it, even if it's not translated yet (if you want) So for example german users would see the page and the text in the german structure with a "Das wurde leider noch nicht übersetzt" (Sorry, this hasn't been translated yet) and the english text. It should not bother anyone as you have to translate the text anyway and you can delete this introsection when you are ready. Additional this introbox could have a flag so you can track in the database how many articles have been translated yet / have to be translated (Percent or total number of articles, or list of not translated items)

**Comment by coolcat-creations** [comment]
I put it in the Gsoc call for ideas, guess thats the best place for that :)

**Comment by marcodings** [comment]
( at the risk this has been discussed somewhere else or i missed something )

In addition. why not consider having a fall-back mechanism for multilingual
if content were not defined in a certain language it would fall back along the define list of languages.
Say from NL to DE to EN ( or whatever you specify )
@coolcat-creations we could discuss in essen

**Comment by Gitjk** [comment]
> `The article is copied to all languages, all associations are done and a default text in the language is added in front of the introtext that the article is not translated yet.`

You could copy this feature/some code from the VirtueMart extension to achieve that. (Just a hint)

**Comment by joomleb** [comment]
Would be good that you take a look to the "[JA Multilingual Component](https://www.joomlart.com/joomla/extensions/ja-multilingual-component)" free extension - [video](https://youtu.be/gSi9JqF6jb8)

I think you are speaking about those features that really should be integrated into standard Joomla Multilingual Associations by default...

**Comment by brianteeman** [comment]
Closing this as it is in progress as part of GSOC

**Comment by joomleb** [comment]
Hi Brian, 
thanks for the info, as far as I understand, it is been added as Project II 
https://docs.joomla.org/GSOC_2018_Project_Ideas#Project_II:_Automatic_Multilanguage_Associations
and Elisa Foltyn as Mentor.
Reading about GSOC 2018 presentation page, what I don't understand is:
1 - Can the idea project be discussed ? Where and how ?
2 - The timeline project would be https://developers.google.com/open-source/gsoc/timeline?hl=en 
This mean that in october this "feature" will be included into joomla ?
Can you help me about ?

PS In my opinion the issue "Multilanguage Associations - Copy BUGs #19807"
https://github.com/joomla/joomla-cms/issues/19807
should be solved before to start this new feature implementation...

**Comment by coolcat-creations** [comment]
Hello @joomleb, the Repo can be found here: https://github.com/joomla-projects/gsoc18_automatic_multilingual_association :) You are very welcome to look into it, help and test.
A GSoC Project is no guarantee that something will be merged into Joomla, first the everything must be accepted into core.

**Comment by joomleb** [comment]
Hi Elisa, 
thanks for the link. I'mnot a programmer, but sure I want install, test it, report etc.
As far as I understand the project is open as "a joomla 4.0 (alpha3 right now) fork", Am I right ?

Please, what is the Automatic Multilingual Association GSoC Project status right now? What has been done? What are the next deadlines to follow?

Please, How can I download and install it to test ?
Is there also any guidelines to follow to find and test the "new features" ?

**Comment by coolcat-creations** [comment]
Hello @joomleb The project is currently scoped to Joomla 4, indeed! But as said, thats not a guarantee it will be merged. We publish the current state in our meeting reports on the volunteers portal: https://volunteers.joomla.org/teams/gsoc-18-multi-language-association
For downloading and testing you might be interested in reading this excellent article from @brianteeman https://brian.teeman.net/joomla/873-a-dummies-guide-to-joomla-bug-testing

Greetings,

Elisa
