### ISSUE TITLE
Redirects components - Bulk Import - should error if separator not found?

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#18844]
Standard separator is |, if you do a bulk import and use , it imports with , in the url and nothing in the to address.

I suggest we issue a warning saying along the lines of:

Bulk Import failed, we did not find the | separator 

I also think we should have a toggle, enable / disable on import.

Thoughts?

**Comment by ghost** [comment]
+1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18844">issues.joomla.org/tracker/joomla-cms/18844</a>.</sub>

**Comment by brianteeman** [comment]
it was your pr so you know best

**Comment by brianteeman** [comment]
@tonypartridge something for you to do over the holidays ;)

**Comment by tonypartridge** [comment]
I’ve got a few pulls to update and add this being one 😎

**Comment by tonypartridge** [comment]
Closing as we have a PR
