### ISSUE TITLE
[4.0] Administrator-Menu: Descriptions of Menu Item Type missed

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#18858]
### Steps to reproduce the issue
Create a Administrator-Menu, in 2 Types some Descriptions are missed:

![bildschirmfoto 2017-11-25 um 11 21 20](https://user-images.githubusercontent.com/8235763/33229698-09e76baa-d1d4-11e7-99b5-801433646efd.jpg)

![bildschirmfoto 2017-11-25 um 11 21 33](https://user-images.githubusercontent.com/8235763/33229697-06c104fe-d1d4-11e7-9239-d46d451a9147.jpg)
### System information
4.0.0-dev
Multilanguage Site (4 Lang.) & Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by infograf768** [comment]
I confirm. All the strings ending with _DESC have been deleted in `en-GB.com_categories.sys.ini` although each of them is important.

**Comment by brianteeman** [comment]
That will be my mistake as although I checked to see where they were being used before removing them I completely forgot about the admin menu.

I will review them and submit a PR

**Comment by brianteeman** [comment]
Closed see #18862
