### ISSUE TITLE
[4.0] Private Messages: "Select a user" display "No Matching Results"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#18859]
### Steps to reproduce the issue
Create a new private Message and click on Icon for "Select a user", got (other User are created):

![bildschirmfoto 2017-11-25 um 13 21 34](https://user-images.githubusercontent.com/8235763/33230434-9b75a6e0-d1e3-11e7-82d5-35d7587ee572.jpg)

### System information
4.0.0-dev
Multilanguage Site (4 Lang.) & Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
You can only send private messages to users who have admin access - otherwise they wouldnt be able to read them. Therefore the list of users only includes those with admin access.

This is not a J4 thing it has always been this way and is documented

**Comment by ghost** [comment]
closed as expected Behaviour.

Thanks for Info @brianteeman <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18859">issues.joomla.org/tracker/joomla-cms/18859</a>.</sub>
