### ISSUE TITLE
[4.0] On install, for "Select the database type. *" only have 'None'

### ISSUE THREAD

**Issue by DavidBoggitt** [joomla/joomla-cms#18850]
### Steps to reproduce the issue
Upload 4.0.0 alpha 2 to host
Navigate to domain
Begin to install
Get stuck as cannot change from 'None' on Select the database type

### Expected result
Being able to select a database (None is the only option) and finish the installation

### Actual result
Error message "One of the options must be selected"

![joomla 4 0 0a2-install](https://user-images.githubusercontent.com/3079738/33221307-76251d50-d146-11e7-83fd-6a9796d3436d.png)

### System information (as much as possible)
PHP 7.0 on a Rochen host

**Comment by Quy** [comment]
Duplicate #18783

**Comment by kroonsbe** [comment]
Have exactly same issue using PHP 7.2.1 on Apache 2.4.29 server at Strato hosting provider.
User Agent Chrome/64 on Windows 10.

**Comment by hansquist** [comment]
Have exactly the same using PHP 7.0, 7.1 and 7.2 on Apache server at Versio hosting provider.

**Comment by kroonsbe** [comment]
Reloaded alle files again, same result.
No database type selection possible. 
![knipsel](https://user-images.githubusercontent.com/24250077/37331839-67374bce-26a5-11e8-95ed-7b1c2daa69c9.PNG)

**Comment by infograf768** [comment]
Please use https://github.com/joomla/joomla-cms/archive/4.0-dev.zip to test. Alpha is really too old (And choose mysqli when installing).

**Comment by hansquist** [comment]
Thank you very much for your help!

**Comment by kroonsbe** [comment]
Thanks for the download, I now only see the possibility for selecting databse MySQL(PDO). No other selctions possible.

**Comment by kroonsbe** [comment]
Trying to use MySQL (PDO) instead of MySQLi gives error.
Not possible to select MySQLi in field, only option displayed 
![error pdo](https://user-images.githubusercontent.com/24250077/37336197-f081db3c-26b0-11e8-8ae0-dc64164e0ee5.PNG)
is MySQL (PDO)

**Comment by infograf768** [comment]
Choosing MySQL (PDO) will not let you proceed (the driver itself is OK but some code has to be modified in core to use it).
It is weird though that you do not see mysqli in dropdown.

**Comment by kroonsbe** [comment]
Just for yr information I here by enclose the downloaded files of Joomla 4.0 Beta
[Downloaded files Joomla 4.0 Beta.pdf](https://github.com/joomla/joomla-cms/files/1806541/Downloaded.files.Joomla.4.0.Beta.pdf)

**Comment by mbabker** [comment]
Still a duplicate of https://github.com/joomla/joomla-cms/issues/18660 which is apparently still waiting for me to find a moment in my copious amounts of free time to fix all these months later.

**Comment by kroonsbe** [comment]
Thanks for yr reply. I will silently and relaxed wait for a solution, because I seem not be able to fix the issue.

**Comment by JimHolloman** [comment]
This issue occurred on a HostGator shared server. It did not occur on a GoDaddy shared server nor on WampServer. The WampServer was on a PC running Windows 7. I have informed HostGator of the issue and and talked to a tech rep that took an interest in the issue. Both GoDaddy and HostGator are running Apache with a cPanel interface -- but the two interfaces are quite different. JLH 180521

UPDATE: 180521
For shared hosting, I have determined that GoDaddy has MySQLnd support in its PHP Configuration and HostGator does not have MySQLnd support in its PHP Configuration. I don't know if this is the only difference between the two or not.

**Comment by AmyKrizanWang** [comment]
Same Error, mine issue was MySQL the package php-mysql is missing
sudo apt install php-mysql
sudo service apache2 restart
refreshed the browser > FIXED

**Comment by jouneytowebdev** [comment]
To fix this lower the PHP version to 7.4 then install and then change it to the latest afterwards

**Comment by brianteeman** [comment]
@jouneytowebdev that is not the fix. the correct fix is exactly what the previous poster reported. make sure that the php-mysql package is installed on the server and if not then install it.
