### ISSUE TITLE
[4.0] Select Bootstrap size for modules

### ISSUE THREAD

**Issue by Twincarb** [joomla/joomla-cms#18866]
### Steps to reproduce the issue
Create a couple of custom modules and assign to the same position (Footer is as good as any)
Under the advanced tab change the module size using the Bootstrap Size selector.

### Expected result
modules should display in a row with the correct size selected from the dropdown
html output is class="col-3" (if the size selected was 3

### Actual result
html output is class="span3" (if the size selected was 3

### System information (as much as possible)
Joomla 4Alpha
xammp

### Additional comments
I believe that https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/system/html/modules.php line 28 needs updating from
[code]$moduleClass    = $bootstrapSize !== 0 ? ' span' . $bootstrapSize : '';[/code]
to
[code]$moduleClass    = $bootstrapSize !== 0 ? ' col-' . $bootstrapSize : '';[/code]

I am not sure if this is the only change that's needed, if so I am happy to open a PR

**Comment by Bakual** [comment]
The parameter would need to be recognised by the template (Cassiopeia) module chromes as well, But to my knowledge it got stripped out. The parameter likely gets removed completely.
I haven't tried yet, but I think you should be able to write the class as a module class (suffix) and get the same result.

**Comment by ciar4n** [comment]
As mentioned by @Bakual, the Bootstrap field is been removed. The field itself still exists temporarily for the backend template. Module sizes will be set via a module class. A PR for a possible implementation of this is currently open (https://github.com/joomla/joomla-cms/pull/18516).

**Comment by Twincarb** [comment]
Thanks for the responses, I presume this can be closed when there is a PR for the removal of the Bootstrap size box.
@ciar4n I am having a look at #18516 now :smile:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18866">issues.joomla.org/tracker/joomla-cms/18866</a>.</sub>

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18866">issues.joomla.org/tracker/joomla-cms/18866</a>.</sub>

**Comment by Twincarb** [comment]
@franz-wohlkoenig we don't have a PR for the removal of the bootstrap size yet.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18866">issues.joomla.org/tracker/joomla-cms/18866</a>.</sub>

**Comment by brianteeman** [comment]
Re-opening.

**Comment by ghost** [comment]
@Twincarb misread your Comment, sorry.

**Comment by C-Lodder** [comment]
I'll do a PR now. Do we want it removed completely, or just for front-end modules? @ciar4n 

I'm thinking remove it completely and use column-count for the dashboard modules. Already removed masonry in another PR

**Comment by Bakual** [comment]
Personally, I would do it the same in front- and backend. I don't see a reason to differentiate. If the reason is the different template architecture from front- and backend, then think a second time about it 😄

**Comment by ciar4n** [comment]
Yes I'd say remove from both frontend and backend. AFAIK the only location this field is used in the backend is with the dashboard. It would be quite easy to implement #18516 in the dashboard or indeed use column-count if we wish a masonry style layout.

**Comment by C-Lodder** [comment]
Cool. Will finish off PR tomorrow

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/18957

**Comment by ghost** [comment]
closed as having Pull Request #18957
