### ISSUE TITLE
renaming alias to lower register

### ISSUE THREAD

**Issue by volandku** [joomla/joomla-cms#18867]
### Steps to reproduce the issue
Create article with alias ABC and save
You will see that saved alias is abc, not ABC

### Expected result
ABC

### Actual result
abc

### System information (as much as possible)
3.8.2 clear

**Comment by volandku** [comment]
also - there is no redirect too<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18867">issues.joomla.org/tracker/joomla-cms/18867</a>.</sub>

**Comment by brianteeman** [comment]
see #13853

**Comment by volandku** [comment]
#13853 about redirects
I see main problem in saving item

**Comment by brianteeman** [comment]
sorry i misunderstood you

it is the expected behaviour that an alias is all lowercase

**Comment by volandku** [comment]
Its wrong logic ((
Also i found i cant redirect it (with new router)

Redirect plugin see site.com/ABC as site.com/abc

**Comment by brianteeman** [comment]
Not about logic - its the internet specification
https://tools.ietf.org/html/rfc3986#section-3.1

**Comment by volandku** [comment]
OK. 
So, by spec Joomla must conver ABC to abc or show ABC with canonical tag

But i see another reaction.
Or its Apache/2.4.7 bug?
