### ISSUE TITLE
Cant find plugin by its english name

### ISSUE THREAD

**Issue by volandku** [joomla/joomla-cms#18868]
### Steps to reproduce the issue
Install russian (or may be any other language) as default and try to find plugin by its name
Also cant find in russian if upper\lower case doesnt exact

### Expected result
find ok

### Actual result
cant find

### System information (as much as possible)
3.8.2
![_039](https://user-images.githubusercontent.com/3468378/33235466-d88b878c-d249-11e7-94d2-33a6fb4e3ba8.jpg)
![_038](https://user-images.githubusercontent.com/3468378/33235467-d8a964aa-d249-11e7-84cb-72e1de9ebab9.jpg)
![_036](https://user-images.githubusercontent.com/3468378/33235468-d8c647e6-d249-11e7-8a99-7988a940a407.jpg)

**Comment by ghost** [comment]
Issue confirmed. But isn't that expected Behaviour?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18868">issues.joomla.org/tracker/joomla-cms/18868</a>.</sub>

**Comment by infograf768** [comment]
1. Search by element is not implemented in the plugin manager
2. Using or not Upper case does work fine for latin Names.

3. Upper-lower search does not indeed work for Cyrillic (or Greek). I confirm that issue.

**Comment by infograf768** [comment]
Tested that using upper/lower case in Greek/Cyrillic does work when searching articles

**Comment by coolcat-creations** [comment]
I stumbled over this to and it's expected behavior but it should be searchable by the english name for better usability...

**Comment by infograf768** [comment]
The only English wording in the extensions db is the element (`emailcloak, loadmodule, pagebreak` for example). We could do that one and treat it as we do for IDs but they are not obvious to remember.

I am not sure that the upper/lower issue in Manage as well as plugins Manager is to be expected. I rather think it is an oversight.
We are there only dealing with translated strings and not any entry in a table, but nevertheless we should be able to retrieve all names and then do a search independent from the case.

**Comment by coolcat-creations** [comment]
If i talk to a german user and i use only the english backend it's hard to remember all the translations from the plugins. So it would be just easier to say "Search for the pagebreak plugin" instead of remembering all the translations that even might change. Would be great if someone could implement this to search for the element :)

**Comment by mbabker** [comment]
To do that would require making a schema change to the extensions table (so affects all extension types and managers) and adding a hardcoded English label into the database.  The Plugin Manager doesn't do search filtering using the database query, it filters the database query results manually using the active language.

In the Extension Manager this same issue exists.  The name column in the extensions table can be used as a search filter, and this generally is the extension's "code" name (i.e. com_content or plg_search_content) as the value is pushed through `JText`.  So it would be a major B/C break to try and turn that column into a hardcoded English value, plus then you strip the ability for extensions to allow their names to be translated.

For technical reasons I don't know if this is something that should be fixed to be perfectly honest.

**Comment by coolcat-creations** [comment]
If it's too much effort definetly not, but if its possible to search by element like @infograf768 said it would be great. Thanks for the further explaination @mbabker

**Comment by infograf768** [comment]
What I can do is adding a filter by element
<img width="895" alt="screen shot 2017-11-30 at 08 53 52" src="https://user-images.githubusercontent.com/869724/33419745-1fa13cd8-d5ac-11e7-9925-fc01760db795.png">

Would that be OK for you folks?

**Comment by infograf768** [comment]
Will make PR as using the same system as id does not work here.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/18955
