### ISSUE TITLE
user.css gets overwritten in Chrome and Opera

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#18865]
### Steps to reproduce the issue
Create a user.css file in Protstar's /css folder
add
```
.input-prepend .input-small {
background-color: red;
}
```
save

View a page that has the login module is published.  Use Firefox, Chrome and Opera browsers

### Expected result
Input fields have a red background

### Actual result
Firefox works a expected
Chrome and Opera the background remains white (If you refresh the Opera browser the background flashes red).

**Comment by Quy** [comment]
Unable to reproduce. Tested successfully in Chrome Version 62.0.3202.94 and Microsoft Edge 41.16299.15.0. I don't have Opera.

**Comment by brianteeman** [comment]
Tested in chrome and unable to reproduce
