### ISSUE TITLE
Error in database query

### ISSUE THREAD

**Issue by Arkadiy-Sedelnikov** [joomla/joomla-cms#18869]
### System information (as much as possible)

libraries/joomla/database/query.php in string 1445

public function orWhere($conditions, $glue = 'AND')
	{
		return $this->extendWhere('OR', $conditions, $F);
	}
$F = undefined and wrong. Must be  $glue.
Joomla version 3.8.2

**Comment by brianteeman** [comment]
there is no problem in the core see
https://github.com/joomla/joomla-cms/blob/d81696c6f84fc6217cb2c75c38f5b4251c70c893/libraries/joomla/database/query.php#L1445-L1448

**Comment by Arkadiy-Sedelnikov** [comment]
Weird. Where do you think I came from? Looked at the distributions in them no error. Sorry to bother you.

**Comment by ghost** [comment]
@Arkadiy-Sedelnikov is this Issue to discuss on? If not, can you please close it?
