### ISSUE TITLE
Windows 10 Find Malware in joomla 4.0.0-alpha1

### ISSUE THREAD

**Issue by jamesliu668** [joomla/joomla-cms#18879]
### Steps to reproduce the issue
1. Go to download page https://github.com/joomla/joomla-cms/releases/tag/4.0.0-alpha1 in chrome
2. Click the download package zip or tar.gz 
3. Starting download
4. The browser will delete the downloaded file and popup a message, found malware in downloaded file

### System information (as much as possible)
Windows 10
Chrome 62 (64bit)

**Comment by ghost** [comment]
Have you tested latest Release Alpha2?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18879">issues.joomla.org/tracker/joomla-cms/18879</a>.</sub>

**Comment by brianteeman** [comment]
I havent been able to replicate this

what is the exact message?
are you using Windows Defender or another antivirus?

**Comment by softforge** [comment]
I cannot replicate it either and I using windows 10 and Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by C-Lodder** [comment]
Cannot replicate this at all.

- Chrome or FF
- AVG Internet Security
- Windows Defender

**Comment by ghost** [comment]
closed as Issue can not replicate. Issue can always reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18879">issues.joomla.org/tracker/joomla-cms/18879</a>.</sub>
