### ISSUE TITLE
[com_fieds] default values not searchable

### ISSUE THREAD

**Issue by effrit** [joomla/joomla-cms#18889]
### Steps to reproduce the issue
Make custom field (text type) with default value (zzzzzz, for example).
Make article with custom field with default value (don't change it!), save article.
Try search for default custom field value (zzzzzz).
### Expected result
Link to item in search result.

### Actual result
Nothing found.

### System information (as much as possible)
Search seeking in database for values of fields, but 'default' values not saved in it.
It's just link to actual value storied in custom field properties.

### Additional comments
This is important issue because not only search but filter also cant find default values (same people made filter for blog and find this issue).
So its necessary to save real value of custom fields (all of them) in DB on article saving.

**Comment by ghost** [comment]
similar to #17294?

**Comment by effrit** [comment]
No, its different. My is about empty search result in custom fields with **default** value.
'Default value' is keyword.

**Comment by Quy** [comment]
Related #18546

**Comment by Quy** [comment]
This PR #18891 would fix this too??

**Comment by Arkadiy-Sedelnikov** [comment]
>This PR #18891 would fix this too??

Yes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18889">issues.joomla.org/tracker/joomla-cms/18889</a>.</sub>

**Comment by effrit** [comment]
Yes

**Comment by Quy** [comment]
@effrit Please close this issue and test PR #18891 and submit your test result here: https://issues.joomla.org/tracker/joomla-cms/18891 Thanks.

**Comment by effrit** [comment]
PR #18891
