### ISSUE TITLE
[4.0] Inserting image in article generates js error

### ISSUE THREAD

**Issue by FB1960** [joomla/joomla-cms#18884]
### Steps to reproduce the issue

Testing the 4.0 alpha2
Trying to insert an image inside an article

### Actual result
Js error:
TypeError: Joomla.getImage is not a function   media.js:18:7
browser: Mozilla Firefox Quantum 57.0 64 bit
![firefox](https://user-images.githubusercontent.com/34027508/33264831-6ddbbb10-d36f-11e7-9606-457c64005fb1.jpg)

object doesn't support property or method getImage  media.js:(18.7)
browser: 
Microsoft Edge 40.15063.674.0
Microsoft EdgeHTML 15.15063
![edge](https://user-images.githubusercontent.com/34027508/33264818-64e9f4e0-d36f-11e7-987b-59c5acb012f4.jpg)

### System information (as much as possible)
OS: Microsoft Windows 10 Home version 10.0.15063 build 15063
Dev server   Easyphp 17
Database Version 	5.7.17 
PHP Version 	7.1.3
Web Server 	Apache/2.4.25 (Win32) PHP/7.1.3
Joomla! Version 	Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT 

### Additional comments

Google Chrome V. 62.0.3202.94 (64 bit) works fine.

The version installed is:
Joomla_4.0.0-alpha2-Alpha-Full_Package.zip

Hope this could help. Thank you.

**Comment by ghost** [comment]
@FB1960 looks like duplicate Report #18762. If yes, please close this Issue and comment on #18762, thanks.

**Comment by FB1960** [comment]
Ok, the "upload" word in the other title report confused me. Sorry.

**Comment by ghost** [comment]
reopened as stated in #18762<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18884">issues.joomla.org/tracker/joomla-cms/18884</a>.</sub>

**Comment by dgrammatiko** [comment]
Is this still an issue?

**Comment by TobsBobs** [comment]
I will check.

**Comment by TobsBobs** [comment]
I have downloaded the lastest 4.0-dev to test this problem.
In Firefox 58 there is no Js issue more. 
In Chrome 63:
If I want to insert a picture, then I get the following js error:

![fehler](https://user-images.githubusercontent.com/816779/34073316-357cf61c-e297-11e7-9e6f-da5f9e7aeff2.png)

**Comment by FB1960** [comment]
Hello, I have tested again, with the latest 4.0 alpha based on commit 8007796e5d23d92cbe6916d293de1d616d6e864c

Results:
Firefox Quantum 57.0.2 (64 bit): does not work. 
If I want to insert a picture, nothing happens and the console shows the same error: 
TypeError: Joomla.getImage is not a function media.js:18:7
Even if I use the menu "images and links" and press the button "select" nothing happens.
![mozilla](https://user-images.githubusercontent.com/34027508/34123071-ab53eec0-e42e-11e7-9ca3-ada58975c4e1.jpg)
(@TobsBobs: I have not installed yet the beta Firefox v. 58)

Google Chrome V. 63.0.3239.108 (64 bit) now works fine. (both two cases)
Microsoft Edge 41.16299.15.0 now works fine (both two cases)

**Comment by TobsBobs** [comment]
I have testet again - latest commit 8007796!

Google Chrome Version 63.0.3239.108 (Offizieller Build) (64-Bit) works fine (both two cases). 
Firefox Version 58.0b11 (64-Bit) works fine (both two cases)
Microsoft Edge 41.16299.15.0 works fine (both two cases)

@FB1960 I don´t know why!?!

**Comment by FB1960** [comment]
@TobsBobs ok, seems that we have the same good results; latest Chrome and Edge work, and the new Firefox beta on your side works.
At the moment I cannot install the beta Firefox on this pc, and so I'm not able to test, but I assume that probably also the final 58 version will work (hope so).

**Comment by brianteeman** [comment]
Closed as resolved based on tests above
