### ISSUE TITLE
Modules with access level Guest not accessible for editing from Administrator

### ISSUE THREAD

**Issue by andrewj1313** [joomla/joomla-cms#18890]
### Steps to reproduce the issue

Change a modules access level to Guest

### Expected result

Module is only visible to guests and not logged in users (this works)

### Actual result

After saving the module, when returning to the administrator backend, Extensions > Modules (Site), the module is no longer available for editing, regardless of the search criteria entered. Temporary resolution was to locate the Module within the database and change the permission/access from "5" to "1" within the database. This reestablished access to the module from the administrator backend.

### System information (as much as possible)

 
PHP Built On	Linux mXX.siteground.biz 3.12.18-clouder0 #85 SMP Mon Apr 3 10:28:14 EEST 2017 x86_64
Database Version	5.6.36-82.1-log
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.25
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.8.2 Stable [ Amani ] 7-November-2017 15:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

### Additional comments

Again, this works just fine on the frontend of the website, but it appears the module permissions setting is getting read/inforced on the administrator backend as well.

**Comment by ghost** [comment]
closed as duplicate Report #18542<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18890">issues.joomla.org/tracker/joomla-cms/18890</a>.</sub>
