### ISSUE TITLE
'Page Class' echoed as page class suffix

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#18892]
### Steps to reproduce the issue
Most of the core components echos the 'Page Class' in the containing div of the component. In every case the class is echoed as a class suffix (https://github.com/joomla/joomla-cms/blob/staging/components/com_content/views/article/tmpl/default.php#L27) rather than a standalone class which the 'Page Class' field implies .

I would question if this class should even be echoed here. Its name implies (to me at least) that it should be echoed as a class on the body tag?

**Comment by tonypartridge** [comment]
I agree, it’s a page class not a container class or suffix. 

Problem we have now is to remove it is a BC since users may be using it in their CSS. 

Would say we remove this for J4?

**Comment by ciar4n** [comment]
Yes probably best hold off any changes until J4

Adding the class to the body would make the field dependent on the template echoing the variable. Unless maybe we add the class using JS. *coughs* @dgt41?

**Comment by rgmears** [comment]
Adding the page class to the body tag is where it belongs. Doing so allows for changing the appearance of whole pages without having to use a different template. I describe how to do it here: http://www.j-tutor.studiofive.biz/elements/template

**Comment by ciar4n** [comment]
PR created.. #18967
