### ISSUE TITLE
Sample Data File Missing when installing J4.0 Alpha 2

### ISSUE THREAD

**Issue by Shedyk** [joomla/joomla-cms#18897]
### Steps to reproduce the issue
Choose customize installation during Joomla 4 installation
then skip language setup and install sample data 

### Expected result
Joomla Sample data should be installed 

### Actual result
Error: file .../..../mysql/sample_testing.sql does not exist

### System information (as much as possible)

PHP Built On | Windows NT 10.0 build 16299 (Windows 10) i586
<img width="950" alt="j4" src="https://user-images.githubusercontent.com/1322078/33312492-207df642-d439-11e7-8e46-2125614c95ab.png">

Database Version | 5.7.20-log
Database Collation | utf8mb4_unicode_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.1.11
Web Server | Apache/2.4.29 (Win32) OpenSSL/1.0.2l PHP/7.1.11
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by Bakual** [comment]
In J4, sample data will not be installed anymore during installation. That's why we have the sample data module now.
The whole step needs to be removed.

**Comment by Shedyk** [comment]
Using the Sample Data module in admin control panel doesn't work either #18904, probably for the same reason that the sql file is missing.  

> There is an error in the sample data plugins. Response is invalid.

**Comment by Bakual** [comment]
Nah, the module doesn't use SQL files at all, and there is already an issue open for that.

**Comment by Shedyk** [comment]
Ok. 
Then I guess as you suggested if sample data is not meant to be there during installation, the step should be removed from the installation wizard.

**Comment by ghost** [comment]
closed as known Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18897">issues.joomla.org/tracker/joomla-cms/18897</a>.</sub>
