### ISSUE TITLE
Joomla 4 save & close two click procedure.

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#18893]
### Steps to reproduce the issue
open module and save

### Expected result
save and close being the default / quick action

### Actual result
save is the quick action

### System information (as much as possible)
Joomla! 4.0.0-dev Development [ Amani ] 19-November-2017 16:34 GMT 

### Additional comments
It's completely counterintuitive & counter productive to have to hit a dropdown to save & close.
it's far more common that people make all their changes and then save, then it is to make incremental saves.  These button choices should be reversed!

**Comment by brianteeman** [comment]
Close as duplicate

**Comment by N6REJ** [comment]
link?

**Comment by brianteeman** [comment]
#14326
