### ISSUE TITLE
New attribute suggestion for JForm XML

### ISSUE THREAD

**Issue by Paladin** [joomla/joomla-cms#18907]
Ran into something that I think might nice to be able to use. I've no expectation of time to write the code for it myself until next year sometime, so I thought I'd toss it in here in case someone else who sees it wants to run with it before then.

New Attribute: related_global or alias_global

Discussion:
Ran into a circumstance while creating custom tabs on a custom menu item type for a template where some of the global values (show_title, link_title, etc.) could be applied differently to two values in two separate tabs. (Specific case was creating a template with a custom category view, applying such display options independently  to three classes of articles within the category.) This resulted in, for example, "lead_show_title" and "recent_show_title" parameter names to indicate the title would be shown or hidden for any of the three independently of the other two. But it would still be nice to relate those values to the "show_title" global, so the setting would only need to be changed if different from the global. So a field attribute indicating that this field's "global" setting will be the same as a recognized global field's setting would be extremely useful, giving feedback to the user for what the related global field is currently set to, as the "normal" operation of the form would have if the global value could be used.

Essentially, if this attribute is present, "use_global" will refer to the designated field, rather than the default behavior of looking for a global field of the same name as the field.

It should have zero impact on backward compatibility because only form XML that knows about this option would use it; form XML that was written before it was available should continue to work as before.

**Comment by ghost** [comment]
Any Comment by Maintainers on this Feature Request?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18907">issues.joomla.org/tracker/joomla-cms/18907</a>.</sub>

**Comment by brianteeman** [comment]
as there appears to be no interest from either the original poster or anyone else in developing this I am going to close it. it can always be reopened if there is any activity
