### ISSUE TITLE
[com_banners] back-end not responsive.

### ISSUE THREAD

**Issue by dikau** [joomla/joomla-cms#18902]
![2017-11-28_19-12-54](https://user-images.githubusercontent.com/34062088/33319280-8d090a7c-d470-11e7-948e-7d26780d5788.gif)

### System information (as much as possible)
Joomla! Version	Joomla! 3.8.2 Stable [ Amani ]
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ]
User Agent	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by brianteeman** [comment]
Closed as we have a PR for testing see #18903
