### ISSUE TITLE
ERROR BACKEND AND FRONTEND ERROR 500 Update Joomla 3.7.5 > 3.8 Constant QQ already defined in /libraries/src/Language/Language.php on line 18

### ISSUE THREAD

**Issue by tiagovtg** [joomla/joomla-cms#18906]
### Steps to reproduce the issue
http://localhost/xxxxx/administrator/index.php

### Expected result

no error

### Actual result
erro 500

### System information (as much as possible)

Notice: Constant _QQ_ already defined in \libraries\src\Language\Language.php on line 18
--
1 | 0.0004 | 241904 | {main}( ) | ..\index.php:0
2 | 0.0810 | 1681600 | JApplicationCms->execute( ) | ..\index.php:51
3 | 0.0810 | 1681968 | JApplicationAdministrator->doExecute( ) | ..\cms.php:265
4 | 0.1374 | 2664792 | JApplicationAdministrator->dispatch( ??? ) | ..\administrator.php:156
5 | 0.1467 | 2751488 | Joomla\CMS\Language\Text::_( string(15), ???, ???, ??? ) | ..\administrator.php:94
6 | 0.1470 | 2765272 | Joomla\CMS\Factory::getLanguage( ) | ..\Text.php:71
7 | 0.1470 | 2765352 | Joomla\CMS\Factory::createLanguage( ) | ..\Factory.php:214
8 | 0.1477 | 2784032 | spl_autoload_call ( string(28) ) | ..\Factory.php:750
9 | 0.1478 | 2784240 | JLoader::loadByPsr4( string(28) ) | ..\Factory.php:0
10 | 0.1480 | 2813976 | include_once( '\libraries\src\Language\Language.php' ) | ..\loader.php:548
11 | 0.1480 | 2814184 | define ( string(4), string(1) ) | ..\Language.php:18

### Additional comments
it is a some type of bug?

**Comment by wojsmol** [comment]
Hi @tiagovtg
Please create new topic on [forum](https://forum.joomla.org/viewforum.php?f=710) and run [Forum Post Assistant](https://forum.joomla.org/viewtopic.php?f=621&t=582860).

**Comment by brianteeman** [comment]
This is not a core issue - closing here - please use the forum
