### ISSUE TITLE
Wrong ordering in admin menu "Content"

### ISSUE THREAD

**Issue by hacki65** [joomla/joomla-cms#18905]
### Steps to reproduce the issue
Look at the menu "Content" and the ordering of the menuitems.

### Expected result
The menuitem "**Featured Articles**" comes after Categories (like in J3.7)

### Actual result
Menuitem is the last entry behind "Field Groups".

### Additional comments
If you are in one of the Contents the quicklinks on the left side are ordered as in the past. The new field entries are at last. In the admin menu this ordering is different. I think this is confusing.

This same confusing ordering is also in the User menu! But here have the quicklinks on the left side not the correct ordering.

![screenshot-2017-11-28 articles - joomla 3 8 - administration](https://user-images.githubusercontent.com/20481746/33323501-f5b04604-d44c-11e7-9c24-7696383222f4.png)

**Comment by hacki65** [comment]
@alikon Thanks for the PR, Nicola. What is about the User menu? Can this be fixed too?

**Comment by ghost** [comment]
closed as having Pull Request #18908 

@hacki65 can you please open a new Issue for

> What is about the User menu? Can this be fixed too?

**Comment by hacki65** [comment]
I have made a PR. Please can this be checked? I have tested it succesfully on 2 sites.
This fix also the wrong ordering in the User menu and give the same order as the sidebar has.
