### ISSUE TITLE
Blog Sample data installation not working in J4.0 Alpha 2

### ISSUE THREAD

**Issue by Shedyk** [joomla/joomla-cms#18904]
### Steps to reproduce the issue
After Joomla installation login to Administrator and click Blog Sample data link to install sample data

### Expected result
Blog Sample data is installed

### Actual result
There is an error in the sample data plugins. Response is invalid.

### System information (as much as possible)
PHP Built On | Windows NT 10.0 build 16299 (Windows 10) i586
Database Version | 5.7.20-log
Database Collation | utf8mb4_unicode_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.1.11
Web Server | Apache/2.4.29 (Win32) OpenSSL/1.0.2l PHP/7.1.11
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

### Additional comments
<img width="941" alt="sampledata" src="https://user-images.githubusercontent.com/1322078/33322119-3112e916-d459-11e7-9f62-0a90e5a3e6df.png">

**Comment by Bakual** [comment]
This is a known issue and there is even a PR for (part) of it: https://github.com/joomla/joomla-cms/pull/18888
Closing as duplicate.
