### ISSUE TITLE
[com_fields] Duplicating Article does not take over custom fields values

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#18919]
### Steps to reproduce the issue
Create an Article with Custom Fields
Fill in Custom Fields Values
Save and Copy the Article

### Expected result
The article should be copied including custom fields

### Actual result
Custom fields are blank

### System information (as much as possible)
Joomla 3.8.2

**Comment by conseilgouz** [comment]
Hi,

I just tried and did not find any problem using optional or required fields (text, buttons, list) in one article.

With what kind of custom fields did you notice your problem ?

**Comment by coolcat-creations** [comment]
I just tested again and I see that issue only appears with batch copy. So tick the checkbox in front of the Article(s) in the list, click on batch, select to copy the article, and the fields are all empty.

Thanks!

**Comment by Quy** [comment]
@coolcat-creations You reported this before #16740. Please test this PR #16958.

**Comment by coolcat-creations** [comment]
Thanks, Closing as there is a PR (tested)
