### ISSUE TITLE
[4.0] registration page returns 404

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#18923]
### Steps to reproduce the issue
Install Joomla 4
Change user options to allow registration
View the front end click the create an account link of the login module

### Expected result
Registration page should display

### Actual result
404 page is displayed

### Additional comments
Works OK if there is a menu item to the registration.

**Comment by Quy** [comment]
Duplicate #18611

**Comment by ciar4n** [comment]
PR created.. #18924

**Comment by ghost** [comment]
closed as having Pull Request #18924
