### ISSUE TITLE
[4.0] After attempting to install a template, the site is frozen

### ISSUE THREAD

**Issue by coolman01** [joomla/joomla-cms#18922]
### Steps to reproduce the issue

Installed Gantry - no problem
attempted to install template hydrogen - error message 

### Expected result

Installtion completed message

### Actual result

An error has occurred.
0 Class 'JEventDispatcher' not found
Complete site locked up

### System information (as much as possible)

PHP Built On Windows NT HP-NOTEBOOK 10.0 build 16299 (Windows 10) i586
Database Version 5.5.5-10.1.28-MariaDB
Database Collation utf8_general_ci
Database Connection Collation utf8_general_ci
PHP Version 7.1.11
Web Server Apache/2.4.29 (Win32) OpenSSL/1.0.2l PHP/7.1.11
WebServer to PHP Interface apache2handler
Joomla! Version Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT
User Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by mbabker** [comment]
The `JEventDispatcher` class is removed in 4.0.

Presumably something in Gantry is trying to use it, try disabling any plugins it installed and that may help get you back into the site.

**Comment by brianteeman** [comment]
updated title to show it is for j4

**Comment by C-Lodder** [comment]
Can we close this please. Obviously an issue with Gantry as it isn't yet J4 compat

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18922">issues.joomla.org/tracker/joomla-cms/18922</a>.</sub>
