### ISSUE TITLE
[4.0] Session timer doesn't work

### ISSUE THREAD

**Issue by coolman01** [joomla/joomla-cms#18921]
### Steps to reproduce the issue

log into admin
do nothing for period longer than entered

### Expected result

auto logout

### Actual result

still active

### System information (as much as possible)

PHP Built On	Windows NT HP-NOTEBOOK 10.0 build 16299 (Windows 10) i586
Database Version	5.5.5-10.1.28-MariaDB
Database Collation	utf8_general_ci
Database Connection Collation	utf8_general_ci
PHP Version	7.1.11
Web Server	Apache/2.4.29 (Win32) OpenSSL/1.0.2l PHP/7.1.11
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by brianteeman** [comment]
Updated title to show 4.0

**Comment by Quy** [comment]
@brianteeman title not updated 😄

**Comment by brianteeman** [comment]
@quy thanks - looks like i forgot to hit save

**Comment by infograf768** [comment]
I confirm the issue here.

**Comment by stutteringp0et** [comment]
I left one open overnight and I can confirm that there is no keepalive activity going on - it's just staying logged in.

**Comment by anuragteapot** [comment]
I also confirm that this issue is present. I make a PR to fix this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18921">issues.joomla.org/tracker/joomla-cms/18921</a>.</sub>

**Comment by anuragteapot** [comment]
@brianteeman this issue not fixed yet.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18921">issues.joomla.org/tracker/joomla-cms/18921</a>.</sub>

**Comment by mbabker** [comment]
Should be fixed after https://github.com/joomla/joomla-cms/commit/fc5a89251f581c4b0799ea80cb5823a0d96718f7

**Comment by ghost** [comment]
@coolman01 can you please test 4.0-dev?

**Comment by ghost** [comment]
Hey I have new problem now with the session time.
Now I get log out after a short period even if I'm still active in the backend.
And my session is expired.

Running on Apache 2.4 with PHP 7.2.
Session handler I tested was filesystem and database.

Can any reproduce or confirm this?

**Comment by brianteeman** [comment]
Closing as the original report that the session timer doesnt auto logout has been resolved
