### ISSUE TITLE
[com_fields] Using {field xx, layout} does not function inside editor custom field

### ISSUE THREAD

**Issue by Hurmeli** [joomla/joomla-cms#18928]
### Steps to reproduce the issue

1. Create editor custom field
2. Create any other custom field
3. In an article, try to use {field n} inside the editor field (where n is ID of the second field)

### Expected result

In frontend the second field shows up rendered inside the editor field.

### Actual result

In frontend the editor field only prints {field n} instead of actually rendering the second field.

### Additional comments

I'm really hoping I overlooked something really obvious and this actually works. If it doesn't work, I'm going to guess that this behavior is intentional. If so it's damn unfortunate and short sighted.

Other plugins already effortlessly work inside editor custom field. It really should behave exactly as the regular content field including using {field n}.

**Comment by Bakual** [comment]
Most likely it doesn't work because there is no (or wrong) "context" passed for the content.prepare event in the custom editor field. @laoneo Any thoughts?

**Comment by laoneo** [comment]
Yes and if we trigger the content prepare event for com_content.article with the full article then we land again in the same situation as with the multiple event triggering situation (#18066 and #18016).

**Comment by laoneo** [comment]
What can be done is to trigger the event with a special context where the fields content plugin is handlicg specially. But that sounds for me more than a hack.

**Comment by Bakual** [comment]
Yep indeed sounds hacky.
There is also a risk of producing recursions. Eg if someone adds the custom editor field into a custom editor field :smile: 

I guess that is just something which can't work properly and thus isn't supported.

**Comment by Hurmeli** [comment]
Guys, I know I may come off as snarky and complaining as I mostly post here when I run into bugs (from my point of view anyway). If I knew anything about programming I'd like to participate more, but all I can do now is offer opinions which may or may not be worth anything.

Joomla is falling behind times pretty fast as it is. Please don't saw off the remaining legs it's standing on. Perhaps these issues have been solved in Joomla 4 and thus it isn't worth it fixing them in Joomla 3, I can understand that. On the other hand even a hacky solution maybe worth it for an app that is basically nearing end of its life and wont see any major revisions in the future.

You're obviously restricted by past decisions on how Joomla was build. Ideally the regular content field and the build in image and link fields should be custom fields like any other, perhaps with the exception that they can only be disabled, and not entirely deleted.

Custom fields should definitely be able to be added in the content and image tabs in backend. Or in other words those tabs should just be regular Field Groups.

There are so many things just plain wrong with Joomla, but I'm not going to go there now. I've been building websites on Joomla since version 1.5 and I've done a lot of them.

Here's hoping Joomla 4 will take a turn for the better.

Sorry for the tiny rant. ;-) Over and out.

**Comment by Bakual** [comment]
J4 will not make you happy in that case.

**Comment by ghost** [comment]
@Bakual @laoneo close this Issue?

**Comment by Bakual** [comment]
I would do so. With reason "known restriction" :)

**Comment by laoneo** [comment]
Agree.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18928">issues.joomla.org/tracker/joomla-cms/18928</a>.</sub>
