### ISSUE TITLE
Sub-Categories not selected in Content-Articles view after 3.8.2 upgrade

### ISSUE THREAD

**Issue by bobr666** [joomla/joomla-cms#18931]
### Steps to reproduce the issue
I enter a category in the back end.  Select Max Levels can be set or not

### Expected result

Articles in sub-categories of main category should show

### Actual result
Articles in sub-categories of main category do not show

### System information (as much as possible)
Joomla 3.8.2
PHP Built On | Linux evm1003.sgvps.net 3.12.18-clouder0 #85 SMP Mon Apr 3 10:28:14 EEST 2017 x86_64
-- | --
Database Version | 5.6.36-82.1-log
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.0.25
Web Server | Apache/2.2.24 (Unix) mod_hive/5.5 mod_ssl/2.2.24 OpenSSL/1.0.0-fips mod_auth_passthrough/2.1 mod_bwlimited/1.4 mod_fastcgi/2.4.6 mod_fcgid/2.3.6
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.8.2 Stable [ Amani ] 7-November-2017 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
### Additional comments
Expected this to be fixed in V3.8.2.

**Comment by tonypartridge** [comment]
Please clear your browser cache, and what is the Mac level filter set too?

**Comment by ghost** [comment]
@tonypartridge i searched yesterday for a similar Report i remembered but can't find it.

**Comment by bobr666** [comment]
Browser cache cleared again and tested at all levels of filtering. Same problem. https://issues.joomla.org/tracker/joomla-cms/18179

**Comment by ghost** [comment]
@bobr666 thanks for looking for #18179.

**Comment by tonypartridge** [comment]
Working fine here with Joomla! 3.8.2. Can you please go to: Components->Joomla Update -> Check for Updates -> Reinstall Core files

**Comment by bobr666** [comment]
Solved - the problem was a plug-in from JoomlArt (JA Content).
