### ISSUE TITLE
J! 3.8.2 - Blank space character on the end of header and date

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#18930]
### Steps to reproduce the issue
Hi, I found "bug" that is doing one blank space character on header and dates in Joomla! 3.8.2. So you are not able to center headers properly, because of that blank space character on the end. Picture below

for example: com_content/views/featured/tmpl/default.php, line 23
in this code below is space character after ...page_heading')); ?>

   <h1>
   <?php echo $this->escape($this->params->get('page_heading')); ?> 
   </h1>

### Expected result
Without the end space character

### Actual result

h1,h2 and date in article have last character as space, as picture shows

### System information (as much as possible)

Joomla 3.8.2, PHP 5.6

**Comment by brianteeman** [comment]
I am assuming you meant to attach a picture?

**Comment by ghost** [comment]
![screen shot 2017-11-30 at 11 14 38](https://issues.joomla.org/uploads/1/85b45d8df999877631bb7c2e062d2ceb.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18930">issues.joomla.org/tracker/joomla-cms/18930</a>.</sub>

**Comment by brianteeman** [comment]
Whatever is causing the problem is not the code that you highlighted as that code is perfectly correct.

**Comment by ghost** [comment]
The code has "space" on the end of the line, one character. The "space" character is causing it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18930">issues.joomla.org/tracker/joomla-cms/18930</a>.</sub>

**Comment by ghost** [comment]
![screen shot 2017-11-30 at 11 20 40](https://issues.joomla.org/uploads/1/50f876c974eda042e8d07f39181f22a4.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18930">issues.joomla.org/tracker/joomla-cms/18930</a>.</sub>

**Comment by brianteeman** [comment]
If you look at the source code here there is no space
https://github.com/joomla/joomla-cms/blob/611531e95df2abe77536c11c24c922ff3c60474a/components/com_content/views/featured/tmpl/default.php#L23

**Comment by ghost** [comment]
Notepad++ show there is space, and test site is showing spaces after h1,h2 and date. So problem is where you think?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18930">issues.joomla.org/tracker/joomla-cms/18930</a>.</sub>

**Comment by C-Lodder** [comment]
Browsers will render new lines as whitespace for inline (maybe inline-block too) elements. They get ignored for block elements. So firstly ensure you're `<h1>` hasn't been given the CSS property `display: inline-block;`.

Else you can simply remove the whitespace yourself:

```
<h1><?php echo $this->escape($this->params->get('page_heading')); ?></h1>
```

or:

```
<?php echo '<h1>' . $this->escape($this->params->get('page_heading')) . '</h1>'; ?>
```

**Comment by ghost** [comment]
closed as no Core-Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18930">issues.joomla.org/tracker/joomla-cms/18930</a>.</sub>
