### ISSUE TITLE
[4.0] Com_user views broken when no menuitem for com_user

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#18952]
### Steps to reproduce the issue
Do a clean install of J4 and then try to login in frontend using the module with wrong credentials. Also try the two links for forgotten user and password.
Even with SEF turned off.

### Expected result
Works

### Actual result
Gives an 404 Invalid URL error

### Additional comments
As soon as you create a menuitem for com_users, it starts to work. So it looks like the same "issue" with com_content. You need at least one com_users menuitem, otherwise the router just refuses to work.
We at least need to create such a menuitem during installation so the base install actually works, but I seriously think the router needs some sort of fallback or many sites will face issues. Telling them they need to set up their site "correctly" isn't helpful.

**Comment by csthomas** [comment]
Try https://github.com/joomla/joomla-cms/pull/18924

**Comment by csthomas** [comment]
> Even with SEF turned off.

I can not reproduce error when SEF is off.

**Comment by joomdonation** [comment]
> I can not reproduce error when SEF is off.
Same here, can only see the issue when SEF is on

**Comment by Bakual** [comment]
Hmm true, now when I try it again it works with SEF turned off. I'm quite sure it didn't yesterday but maybe my setup was somehow messed up.

Will try the PR later.

**Comment by Bakual** [comment]
Closing as #18924 indeed solves the issue.
Great job @csthomas !
