### ISSUE TITLE
MySQL error after reinstall

### ISSUE THREAD

**Issue by neo191987** [joomla/joomla-cms#18968]
Hi when I reinstall some of the components like as a HikaShop, HikaMarket, HikaAuction and HikaSerial, I get these errors: BIGINT UNSIGNED value is out of range in '(`0k0o`.`#__menu`.`level` - 1)' or Duplicate entry '1-1-Vendors-*' for key 'idx_client_id_parent_id_alias_language'.  What could be causing this?

**Comment by ghost** [comment]
Please ask Developers of Hika-* or on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
