### ISSUE TITLE
to administrators of forum.joomla.org : registration not receiving email

### ISSUE THREAD

**Issue by danlaudk** [joomla/joomla-cms#18969]
### Steps to reproduce the issue
I register as a new user on https://forum.joomla.org/ucp.php?mode=register. It says I should find an email to activate my account. 

### Expected result
Receive an email , or an email in spam, or advised that my email address is not valid

### Actual result
No email received after some hours, and after a week

### System information (as much as possible)
chrome browser
tried 4 different email accounts: one is .org based in the US, one is .edu based in Israel/Palestine
The first email (yahoo) I tried a week ago

### Additional comments
sorry if this tracker is not the place to submit

**Comment by danlaudk** [comment]
so annoying because i simply want to post an problem as administrator of site.  i'm  well prepared haveing searched, and have forum post assistant attached , and have spent days on this problem already . how many more new forum users want to newly post but can't - this isn't being logged<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18969">issues.joomla.org/tracker/joomla-cms/18969</a>.</sub>

**Comment by stutteringp0et** [comment]
1. check your spam/junk folder
2. check with your ISP - see if they have any of the 4 joomla mx on a private blacklist

I don't use the forums as much as I used to - but I did get an email for a topic update on 11/17/2017 - so it's been sending emails as of 3 weeks ago.

**Comment by ghost** [comment]
Please ask at https://forum.joomla.org/. 

This repository you asked concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.

**Comment by stutteringp0et** [comment]
That's his problem - he can't register on forum.joomla.org - he never gets the email.

**Comment by ghost** [comment]
@stutteringp0et You're right, i copied wrong Url, wanted url was https://github.com/joomla/joomla-websites

Sorry for Mistake @danlaudk
