### ISSUE TITLE
[4.0] Username Field value cannot be empty

### ISSUE THREAD

**Issue by joshgilson** [joomla/joomla-cms#18960]
Running Joomla 4.0.0-Dev Alpha 2

In admin login area, with the correct credentials.
Error on username field is: Field value cannot be empty

I'm able to log in with no issues, but it shows the error for the auto-filled data from LastPass Chrome Extension.

![capture1](https://user-images.githubusercontent.com/4388812/33521275-4960773a-d793-11e7-8767-f42fa447a27a.JPG)

**Comment by infograf768** [comment]
Please test with last 4.0 branch
https://github.com/joomla/joomla-cms/archive/4.0-dev.zip

**Comment by C-Lodder** [comment]
I think this is because the validation script re-validates an input on `blur` rather than `keydown`

Please can the title of this issue be altered `[4.0]` at the beginning

**Comment by ghost** [comment]
Title changed to "[4.0] " at Beginning.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18960">issues.joomla.org/tracker/joomla-cms/18960</a>.</sub>

**Comment by joshgilson** [comment]
@infograf768 Updated with the link you provided, but same issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18960">issues.joomla.org/tracker/joomla-cms/18960</a>.</sub>

**Comment by anuragteapot** [comment]
I have tested this, it shows  <code> Username Field value cannot be empty. </code> If  we try to login with wrong credentials, in both Author Login and  Admin login area. But ,it have to show only warning . And with LastPass Chrome Extension it shows <code> Username Field value cannot be empty. </code> only once , at the time when user click to fill form.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18960">issues.joomla.org/tracker/joomla-cms/18960</a>.</sub>

**Comment by alikon** [comment]
can we close this one opened on 4.0.0-Dev Alpha 2, 
it can be always reopened if needed
@franz-wohlkoenig
