### ISSUE TITLE
Joomla\CMS\Document\RawDocument::addHeadLink

### ISSUE THREAD

**Issue by jmanager** [joomla/joomla-cms#18962]
### Steps to reproduce the issue
When we set in Global Configuration Use URL Rewriting & Add Suffix to URL to "Yes" (with launched .htaccess file)

### Expected result
Looking for non-html files on the server that does not exist, displays error 404

### Actual result
No error 404, after enabling error reporting we get a message:
Error displaying the error page: Call to undefined method Joomla\CMS\Document\RawDocument::addHeadLink(): View not found [name,type,prefix]: article, txt, contentView

txt - when we looking for txt file, php - when we looking for php file etc

### System information (as much as possible)
PHP 5.6, 7.0, 7.1
Apache
Tested on localhost and trusted hosting companies.

### Additional comments
No errror in Joomla 3.8.1 Previous version not tested![screen shot 2017-12-03 at 11 16 27](https://issues.joomla.org/uploads/1/383f8e423fa6ee89240962539e0bd0c1.png)
![screen shot 2017-12-03 at 11 16 39](https://issues.joomla.org/uploads/1/7f5b5012a0be75ce2d49aae0e5b02f3b.png)![screen shot 2017-12-03 at 11 16 48](https://issues.joomla.org/uploads/1/8894bba0e491409f72213fb23102a358.png)![screen shot 2017-12-03 at 11 16 53](https://issues.joomla.org/uploads/1/72c5b89bb3f191767e34401f4fc945c7.png)

**Comment by jmanager** [comment]
Impact:
When we set Display Errors to off & Error_reporting to none, bots testing our site receive a 500 error<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18962">issues.joomla.org/tracker/joomla-cms/18962</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #18966

**Comment by zyzak** [comment]
i have the same problem , any solutions?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18962">issues.joomla.org/tracker/joomla-cms/18962</a>.</sub>

**Comment by ghost** [comment]
@zyzak can you please test #18966 as there is no Test yet.

**Comment by ggppdk** [comment]
@zyzak 

Please note that to test PR #18966 
- you need to use Joomla's beez and protostar templates

to make a fix for your website if you are not using Joomla's beez and protostar templates
then you need to 
either contact the author of your Joomla template,
or someone that knows a little about Joomla templates, that will add similar checks to error.php like PR #18966 does

you can ask more in Joomla forums too

**Comment by zyzak** [comment]
I checked Protostar and Beez3 template with link domainname.pl/index.xml
I have also no debug there, and error message is Error: Call to undefined method Joomla\CMS\Document\XmlDocument::addHeadLink(): View not found [name, type, prefix]: article, xml, contentView - little different error but is giving 404

se here screen> http://zyzak.ayz.pl/beez-giving-404-but-with-error.jpg

**Comment by ggppdk** [comment]
This issue is not the same as issue #20004 

(see comment)
https://github.com/joomla/joomla-cms/issues/20004#issuecomment-377564566

Just both issues occur because no checks are being made to ensure that JDocument is a JDocumentHTML
