### ISSUE TITLE
Tag filter in blog category with pagination selects wrong page on start of new user session

### ISSUE THREAD

**Issue by kanich** [joomla/joomla-cms#18964]
The wrong page selection appears by very specific conditions for anonymous users when they have not yet assigned user session. Direct request to second or any later page for blog category opens each time first page of given blog category.

Especially annoying is this bug in case when is used page caching and external crawlers visit the site without keeping session variables. Then in some time are all pages of blog category filled by first page content.

### Steps to reproduce the issue
1.	Create category e.g. 'News'
2.	Create tag e.g. 'Science'
3.	Create 4 articles for category 'News' with tag 'Science'
4.	Create new menu item 'Science' for blog category 'News'  with assigned tag 'Science' and 2 articles in 1 column per page
5.	Disable any Joomla caching (global as well as page one).
6.	Now on frontend are available for menu item 'Science' two pages (each with 2 articles and pagination buttons), select second page (with start=2) and assign it as bookmark in the browser.  In browser assign blank page as initial page, delete all cookies for given site and close browser.
7.	Open browser, click on prepared link for the second page of 'Science'.

### Expected result
response is SECOND page of tagged blog category with pagination having more pages

### Actual result
response is FIRST page of tagged blog category with pagination having more pages

### Additional comments
Solution for issue #17711 https://github.com/joomla/joomla-cms/issues/17711 is good but it did not cover solution for described bug.

**Comment by ghost** [comment]
closed as having Pull Request #18965
