### ISSUE TITLE
[4.0] tinymce Illegal string offset

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#18973]
### Steps to reproduce the issue
enable full error reporting and try to create a new article

<img width="631" alt="screenshotr14-00-23" src="https://user-images.githubusercontent.com/1296369/33556377-9c76dcde-d8fb-11e7-9dfa-1c2e86bfc68e.png">

**Comment by C-Lodder** [comment]
Can't replicate this at all. What values do you have set for the **width** and **height** in the plugin settings?

**Comment by brianteeman** [comment]
it was just the default - let me check it wasnt my branch

**Comment by brianteeman** [comment]
checked a clean branch and same problem

**Comment by infograf768** [comment]
Confirmed here

**Comment by C-Lodder** [comment]
Can you test this please? https://github.com/joomla/joomla-cms/pull/18975

**Comment by ghost** [comment]
closed as having Pull Request #18975

**Comment by infograf768** [comment]
Hmm, in fact I cannot reproduce today.

**Comment by joomdonation** [comment]
PR #https://github.com/joomla/joomla-cms/pull/18996 should fix it. As mentioned in PR, you need to enable the plugin **Button - Field** to see the error

**Comment by brianteeman** [comment]
I can confirm your finding that it was the button - field plugin
