### ISSUE TITLE
 [4.0] The requested page can't be found.

### ISSUE THREAD

**Issue by anuragteapot** [joomla/joomla-cms#18970]
Joomla 4.0.0-Dev Alpha 2

### Steps to reproduce the issue
In author login area, with the wrong credentials in the author login.

### Expected result
It has to show Warning and login form.
![screen shot 2017-12-04 at 07 04 20](https://issues.joomla.org/uploads/1/bf82c3b2e9297504c685e995534a0721.png)
### Actual result
Error page: The requested page can't be found.

**Comment by joomdonation** [comment]
This PR https://github.com/joomla/joomla-cms/pull/18924 should fix it. Please test and confirm if it is possible

**Comment by anuragteapot** [comment]
Yes,@joomdonation it fixed, with  PR #18924. I have tested this item ✅ successfully. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18970">issues.joomla.org/tracker/joomla-cms/18970</a>.</sub>

**Comment by joomdonation** [comment]
You should close this issue, and then go to https://issues.joomla.org/tracker/joomla-cms/18924 to mark your test result as success.

**Comment by delamanche** [comment]
I am having the exact same issue on Joomla 4 alpha7. Pages that are not public show 404 instead of redirecting to login page.

**Comment by Quy** [comment]
You are testing with a very old version. Please test the nightly build. https://developer.joomla.org/nightly-builds.html
