### ISSUE TITLE
Menu Item's Module Assignment tab generates insane JS and html

### ISSUE THREAD

**Issue by okonomiyaki3000** [joomla/joomla-cms#18979]
### Steps to reproduce the issue
1. Have a lot of modules. Maybe a 200 or so. 
2. Edit a menu item. Any menu item.

### Expected result
The menu item edit page should render quickly with minimal html and js and certainly not crash because of running out of memory.

### Actual result
Actually you might run out of memory and crash because 'bootstrap.renderModal' is not the least bit scalable. 

### System information (as much as possible)
Doesn't matter. 

### Additional comments
This feature was just badly implemented in a way that doesn't scale at all. It shouldn't matter how many links  to open module editors in modal dialogs you have, you should only need one javascript function to open them all and you should only need one block of html that you can reuse for all modals. This would normally be easy to do but `JHtmlBootstrap::renderModal` makes it impossible by using an id as a selector. So the only solution is to not use that function or its accompanying layout. Will this have any implications?

**Comment by okonomiyaki3000** [comment]
On top of that, the html for the modals are all written inside of `<tr>`s which is not even valid.

**Comment by okonomiyaki3000** [comment]
OK...I found a way to deal with it. The javascript on this page could still be better. Those first four click handlers (I didn't touch) could all be done with one tiny function.

**Comment by ghost** [comment]
closed as having Pull Request #18982
