### ISSUE TITLE
Joomla 4 Alpha 2 installation error

### ISSUE THREAD

**Issue by jordan-chang** [joomla/joomla-cms#18991]
### Steps to reproduce the issue
Install Joomla 4 Alpha 2 Full Package on a sub directory. Unable to use the auto generated prefix table for the database therefore went on to use the existing one. Completed the installation however when opening the front-end and admin area i get an error page which i have attached to this ticket.

### Expected result
Able to run Joomla 4 Alpha 2 on a sub directory.![screen shot 2017-12-06 at 03 37 25](https://issues.joomla.org/uploads/1/4928233b581029f9077f6f51174bf53f.png)

### Additional comments

![screen shot 2017-12-06 at 03 37 26](https://issues.joomla.org/uploads/1/cad912d312ab807580d9bd9a6ba2a7e9.png)

**Comment by zero-24** [comment]
> Unable to use the auto generated prefix table for the database therefore went on to use the existing one.

hmm what was the reason that you can't use the generated one and what exactly did you used as fallback?

**Comment by jordan-chang** [comment]
When i try to use the generated one, a different error message came up - "#_tableprefix_extension doesn't exists"

I even tried deploying into a root folder (httpdocs) but still getting the same error. The full alpha 2 package that i use is from:

a) https://github.com/joomla/joomla-cms/releases

Additionally, can i possibly use the source code version to update my existing Joomla site? Any help would be much appreciated.

Cheers.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18991">issues.joomla.org/tracker/joomla-cms/18991</a>.</sub>

**Comment by jordan-chang** [comment]
This is the error that i'm getting when try to use generated prefix table.
![screen shot 2017-12-06 at 20 42 58](https://issues.joomla.org/uploads/1/bfa5ca7606c361d5aae4c17bb6f09320.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18991">issues.joomla.org/tracker/joomla-cms/18991</a>.</sub>

**Comment by Quy** [comment]
Please test with the latest version:
https://github.com/joomla/joomla-cms/archive/4.0-dev.zip

**Comment by jordan-chang** [comment]
Hi there,

I'm still getting the same error message with the latest joomla link given by Quy.
![screen shot 2017-12-06 at 20 46 48](https://issues.joomla.org/uploads/1/ea816b4373ecde61dd930907bc099c81.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18991">issues.joomla.org/tracker/joomla-cms/18991</a>.</sub>

**Comment by Floyd611** [comment]
Hi all,
i receive the same error without number of the error, with joomla 4 alpha 2 ![screen shot 2017-12-13 at 09 02 10](https://issues.joomla.org/uploads/1/18034589c71d3c8493f7d74d0fdd8573.png)

Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18991">issues.joomla.org/tracker/joomla-cms/18991</a>.</sub>

**Comment by stimpsonjcat** [comment]
I've downloaded the latest nightly build and can't get past the installer either. I'm trying to install Joomla 4 on my local machine. The error is: 
```
An error has occurred while processing your request.
0 Call to a member function getLabel() on null
```

The URL is: http://joomla4/installation/index.php?view=preinstall

![schermafbeelding 2017-12-21 om 17 25 05](https://user-images.githubusercontent.com/3033162/34264675-f12f5de8-e673-11e7-866b-07139ffb2e84.png)

**Comment by anuragteapot** [comment]
@stimpsonjcat can you give **System Information**<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18991">issues.joomla.org/tracker/joomla-cms/18991</a>.</sub>

**Comment by stimpsonjcat** [comment]
A local MAMP Pro server on a MacBook Pro with High Siera with PHP 7.0.22 and MySQL 5.6.35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18991">issues.joomla.org/tracker/joomla-cms/18991</a>.</sub>

**Comment by anuragteapot** [comment]
@stimpsonjcat Thanks 
Please test with the latest version: https://github.com/joomla/joomla-cms/tree/4.0-dev<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18991">issues.joomla.org/tracker/joomla-cms/18991</a>.</sub>

**Comment by stimpsonjcat** [comment]
I've figured out this had to do with folder permission. Apparently files were appointed tot www-user, instead of the local user set up in MAMP. Maybe a fault on my side in the config of MAMP. I've set the permissions to 0777, and I could go through the installer fine.
Though his 'error' should be detected by the installer, and not result in a cryptic message as above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18991">issues.joomla.org/tracker/joomla-cms/18991</a>.</sub>

**Comment by anuragteapot** [comment]
@stimpsonjcat I think your issue is solved by changing folder permission :) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18991">issues.joomla.org/tracker/joomla-cms/18991</a>.</sub>

**Comment by anuragteapot** [comment]
@jordan-chang I think you are getting this error because of not proper installation of Joomla on your system.
Please test the latest version: https://github.com/joomla/joomla-cms/tree/4.0-dev
And wait until installation automatic redirect to finishing page.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18991">issues.joomla.org/tracker/joomla-cms/18991</a>.</sub>

**Comment by shahryarjb** [comment]
Hi, I was trying to install joomla https://github.com/joomla/joomla-cms/archive/4.0-dev.zip that I saw errors like this : 

```
Warning: Uncaught PDOException: SQLSTATE[HY000] [1049] Unknown database 'joomla_dbs' in /Applications/MAMP/htdocs/joomla-cms/libraries/vendor/joomla/database/src/Pdo/PdoDriver.php:312 Stack trace: #0 /Applications/MAMP/htdocs/joomla-cms/libraries/vendor/joomla/database/src/Pdo/PdoDriver.php(312): PDO->__construct('mysql:host=loca...', 'root', 'root', Array) #1 /Applications/MAMP/htdocs/joomla-cms/libraries/vendor/joomla/database/src/Mysql/MysqlDriver.php(124): Joomla\Database\Pdo\PdoDriver->connect() #2 /Applications/MAMP/htdocs/joomla-cms/libraries/vendor/joomla/session/src/Handler/DatabaseHandler.php(222): Joomla\Database\Mysql\MysqlDriver->connect() #3 [internal function]: Joomla\Session\Handler\DatabaseHandler->open('/Applications/M...', '005e30701f4ec9d...') #4 /Applications/MAMP/htdocs/joomla-cms/libraries/vendor/joomla/session/src/Storage/NativeStorage.php(465): session_start() #5 /Applications/MAMP/htdocs/joomla-cms/libraries/src/Session/Storage/JoomlaStorage.php(303): Joomla\Session\Storage\NativeStorage->sta in /Applications/MAMP/htdocs/joomla-cms/libraries/vendor/joomla/database/src/Pdo/PdoDriver.php on line 317

Fatal error: session_start(): Failed to initialize storage module: user (path: /Applications/MAMP/tmp/php) in /Applications/MAMP/htdocs/joomla-cms/libraries/vendor/joomla/session/src/Storage/NativeStorage.php on line 465
```
It should be noted, I used to Joomla 4 Alpha 2 which didn't have any error at the installation stage , but it has error.

![screen shot 2018-04-03 at 11 14 45 am](https://user-images.githubusercontent.com/8413604/38233762-f331442c-3730-11e8-91d3-f3af7e319425.png)

my last issue : 
https://github.com/joomla/joomla-cms/issues/20050

my os : mac Os  High Sierra
my localhost is mamp 3.5
php 7.0

**Comment by brianteeman** [comment]
I am going to close this as alpha 2 is now very old and there have been a lot of changes since. If you have problems installing the nightly release or branch for github then you should create a new issue
