### ISSUE TITLE
Error in component Joomla Update

### ISSUE THREAD

**Issue by javimata** [joomla/joomla-cms#19005]
### Steps to reproduce the issue
Open Components -> Joomla Update

### Expected result
Check if are updates, but i receive a error that can see in the attach image
![screen shot 2017-12-06 at 17 26 16](https://issues.joomla.org/uploads/1/a816173f3f128c4fbef1d63845da991d.png)

Warning: array_filter() expects parameter 2 to be a valid callback, class 'JoomlaupdateModelDefault' not found in 
../administrator/components/com_joomlaupdate/Model/UpdateModel.php on line 1315

Warning: Invalid argument supplied for foreach() in
.../administrator/components/com_joomlaupdate/Model/UpdateModel.php on line 1317

**Comment by mbabker** [comment]
Already fixed via https://github.com/joomla/joomla-cms/commit/090fd108ae7578fdf53d0610068400d8b7323f49#diff-248c1ba2178aea379cef918f44919bd1
