### ISSUE TITLE
Upgrading from 3.8.1 to 3.8.2 getting a 500 error.

### ISSUE THREAD

**Issue by mike-meservy** [joomla/joomla-cms#19013]
### Steps to reproduce the issue
Select the upgrade option
Installation method is "Write files directly"
Click on the button for Install the Update.

Immediately get a 

This page isn't working
whiterivervalley.org is currently unable to handle this request
HTTP ERROR 500

I have updated several other sites with no problems.

### Expected result
Installation of the Joomla 3.8.2 upgrade.

**Comment by Quy** [comment]
Please ask help on the forums - [Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710) and close this issue. Thanks.
