### ISSUE TITLE
[4.0] [com_fields] setting a default value causes DOMElement error

### ISSUE THREAD

**Issue by stutteringp0et** [joomla/joomla-cms#19018]
### Steps to reproduce the issue

1. Create a new field (I tried text, calendar, and one of my own field extensions)
2. type a default value
3. hit save
4. scratch your head (optional)

### Expected result

Default set

### Actual result
An error has occurred.
0 Class 'Joomla\Component\Fields\Administrator\Plugin\DOMElement' not found
![screenshot from 2017-12-07 23-53-33](https://user-images.githubusercontent.com/310899/33752874-dfc41dca-dba9-11e7-8be3-7b3926dd6745.png)

### System information (as much as possible)

4.0-dev downloaded yesterday
PHP 7.1.11

### Additional comments

Everything else seems to work fine.  I can create fields, they work in profiles, data is saved and retrieved - but I just can't seem to set a default value in any of them.

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19018">issues.joomla.org/tracker/joomla-cms/19018</a>.</sub>

**Comment by stutteringp0et** [comment]
Found it - PR will be issued shortly

**Comment by ghost** [comment]
closed as having Pull Request #19019
