### ISSUE TITLE
[4.0] Rewrite form controls using flex

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#19014]
The form controls were ported over from J3 so users had the same styling. They're a mixture of floats and left margins. 

These need to be rewritten using flexbox

**Comment by himanshuc3** [comment]
# Hi C-Lodder!
I want to start contributing to Joomla! (obviously, that's why I am here).
Can you please help me get started with the development workflow that needs to be setup to start contributing so that I could get up and running ASAP.
PEACE.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19014">issues.joomla.org/tracker/joomla-cms/19014</a>.</sub>

**Comment by C-Lodder** [comment]
Join the Joomla Glip channel and ping me a message if you want. Will help you via there

**Comment by himanshuc3** [comment]
Hey man. Sorry to disturb you again. 
Actually, I've never used Glip before. So I just made an account there. 
I don't know how to join a channel/team. Is this invite based or something...

**Comment by ghost** [comment]
@himanshuc3 In "People" search for "Charlie Lodder".

**Comment by himanshuc3** [comment]
@franz-wohlkoenig My *people list* is empty right now in Glip!

**Comment by ghost** [comment]
@himanshuc3 click on "People" and search there for "Charlie Lodder".

![bildschirmfoto 2017-12-28 um 10 26 24](https://user-images.githubusercontent.com/8235763/34406487-9b1491bc-ebb9-11e7-8534-d5fe87fe7914.jpg)

**Comment by himanshuc3** [comment]
![screen shot 2017-12-28 at 3 22 58 pm](https://user-images.githubusercontent.com/19166045/34407185-0a684f30-ebe3-11e7-861e-143986d041ac.png)

I am not yet added to Joomla! I guess.

**Comment by ghost** [comment]
i try to solve this on Glip.

**Comment by ghost** [comment]
@himanshuc3 you get an invitation by Luca marco to your E-Mail-Address. Please accept, than you can search for Charlie.

**Comment by himanshuc3** [comment]
Got it.
### Thank you a ton.

**Comment by himanshuc3** [comment]
Hiya. 
@C-Lodder which team are you in?

**Comment by C-Lodder** [comment]
@himanshuc3 - Top left, just search for my name and send me a message

**Comment by himanshuc3** [comment]
![screen shot 2017-12-28 at 6 23 48 pm](https://user-images.githubusercontent.com/19166045/34411464-c709af8a-ebfc-11e7-8c73-f4440cec7ec8.png)

You don't seem to be there... 
I want to start conversation as soon as possible so that I can atleast get started exploring stuff!!!

**Comment by C-Lodder** [comment]
@himanshuc3 https://glip.com/invite/41b760f

**Comment by himanshuc3** [comment]
I am really sorry man...
But you're still not on the map! 
If you don't have time, we can talk about this later!

**Comment by C-Lodder** [comment]
@himanshuc3 - Just post a message on the "Joomla community" channel chat and I'll send you a message when I see you. That or just add me on Skype: **charlie.lodder**

**Comment by himanshuc3** [comment]
I'm really sorry, but I was not able to find you. So I'll be picking another issue and try solve that! 
PEACE.

**Comment by ghost** [comment]
@C-Lodder maybe its easier that you find @himanshuc3 on Glip?

**Comment by infograf768** [comment]
His glip name is himichhabra14

**Comment by C-Lodder** [comment]
Already tried. Dont think he is even in the Joomla Glip room

**Comment by ghost** [comment]
@C-Lodder Luca Marzo invited him yesterday.

**Comment by C-Lodder** [comment]
Maybe he's set as a guest rather than a member. Not sure. Either way he has my skype ID so can add me on there

**Comment by himanshuc3** [comment]
@C-Lodder Yes! I am indeed a guest in Joomla glip!!

**Comment by ghost** [comment]
@C-Lodder @himanshuc3 did you ever find each other?

**Comment by C-Lodder** [comment]
@franz-wohlkoenig Can't remember that far back. But don't close as the issue still stands

**Comment by rotimi-best** [comment]
I am new to Joomla and want to start contributing. I want to work on this task, @C-Lodder could you please guide on where to look to fix the form styles?

**Comment by C-Lodder** [comment]
@Rotimi-Best I'd suggest talking to the template team as I'm no longer active

**Comment by rotimi-best** [comment]
Okay, in what channel do I meet the template team?

**Comment by C-Lodder** [comment]
https://volunteers.joomla.org/teams/j4-backend-template-working-group

**Comment by C-Lodder** [comment]
Closing as template team are working on backend template
