### ISSUE TITLE
Joomla non usable in Europe lacks core Cookie Control

### ISSUE THREAD

**Issue by ozipom** [joomla/joomla-cms#19020]
Joomla 4 and Joomla 3.8.3 dont have Cookie Alert Module, compoment or plugin!

This type of module should be as a core module or official extension.

As far as I see now these Joomla extensions are outdated or aren't available.

@rdeutz  locked and limited conversation on this major Joomla issue.

**Comment by rdeutz** [comment]
If you don't stop creating issues and follow the advice you got I will block you from the repository.
