### ISSUE TITLE
Iframe Title needed for enhanced accesibility impaired users

### ISSUE THREAD

**Issue by gwsdesk** [joomla/joomla-cms#19027]
I connected on a forum post with a user who is improving accessibility for screen reader users (Screen readers are software programs that allow blind or visually impaired users to read the text that is displayed on the computer screen with a speech synthesizer or braille display)

Our wrapper does not provide a much needed Title for screen readers to recognize valuable content. The user posted a good link to the requirement https://dequeuniversity.com/tips/provide-iframe-titles

We do provide 
> "Link Title Attribute: An optional, custom description for the title attribute of the menu hyperlink"

but that does not provide a readable title for screen readers

I request to add this in the wrapper menu link so we can enhance access for this group of impaired users

**Comment by tonypartridge** [comment]
How are you adding the iframe? In which context? As far as I know core features don’t use iframes unless I’m missing it?

**Comment by gwsdesk** [comment]
@tonypartridge Yep you are missing it indeed ;-) new menu link --> type wrapper (=iframe)

**Comment by tonypartridge** [comment]
Right, always best to include detailed testing instructions! @brianteeman thoughts on the accessibility issue?

**Comment by gwsdesk** [comment]
@tonypartridge did not realize that somebody did not know that one can create a menu link type wrapper... ;-)

**Comment by tonypartridge** [comment]
I avoid iframes at all costs.

But not only that, you could have been trying it in a module, a component or text area. Maybe Even Inserting via a template override.

Without instructions everything is speculation at best.

**Comment by brianteeman** [comment]
Iirc there is a pr for this already by @dgt41 that addresses the iframe menu and module

**Comment by ghost** [comment]
#18916

**Comment by brianteeman** [comment]
Ah thats for j4. Pretty easy to replicate the title aspect of that pr for j3

**Comment by brianteeman** [comment]
See #19029
