### ISSUE TITLE
[4.0] unable to create a new viewing access level

### ISSUE THREAD

**Issue by stutteringp0et** [joomla/joomla-cms#19028]
### Steps to reproduce the issue

Go to Users > Viewing Access Levels
Try to create a new "Viewing Access Level"

### Expected result

New level form

### Actual result

An error has occurred.
0 Call to a member function getKeyName() on boolean

![screenshot from 2017-12-08 23-34-40](https://user-images.githubusercontent.com/310899/33792852-69eb2a40-dc70-11e7-96ae-b157dd2719c4.png)

### System information (as much as possible)

4.0-dev - a couple of days old (I'm on satellite, downloads take forever)
PHP 7.1.11

**Comment by stutteringp0et** [comment]
Here's the call stack:
Call stack
1	()	JROOT/libraries/src/MVC/Model/AdminModel.php:948
2	Joomla\CMS\MVC\Model\AdminModel->populateState()	JROOT/libraries/src/MVC/Model/BaseDatabaseModel.php:468
3	Joomla\CMS\MVC\Model\BaseDatabaseModel->getState()	JROOT/libraries/src/MVC/Model/AdminModel.php:894
4	Joomla\CMS\MVC\Model\AdminModel->getItem()	JROOT/administrator/components/com_users/Model/LevelModel.php:134
5	Joomla\Component\Users\Administrator\Model\LevelModel->getItem()	JROOT/administrator/components/com_users/Model/LevelModel.php:179
6	Joomla\Component\Users\Administrator\Model\LevelModel->loadFormData()	JROOT/libraries/src/MVC/Model/FormModel.php:236
7	Joomla\CMS\MVC\Model\FormModel->loadForm()	JROOT/administrator/components/com_users/Model/LevelModel.php:155
8	Joomla\Component\Users\Administrator\Model\LevelModel->getForm()	JROOT/libraries/src/MVC/View/AbstractView.php:144
9	Joomla\CMS\MVC\View\AbstractView->get()	JROOT/administrator/components/com_users/View/Level/HtmlView.php:55
10	Joomla\Component\Users\Administrator\View\Level\HtmlView->display()	JROOT/libraries/src/MVC/Controller/BaseController.php:672
11	Joomla\CMS\MVC\Controller\BaseController->display()	JROOT/administrator/components/com_users/Controller/DisplayController.php:116
12	Joomla\Component\Users\Administrator\Controller\DisplayController->display()	JROOT/libraries/src/MVC/Controller/BaseController.php:710
13	Joomla\CMS\MVC\Controller\BaseController->execute()	JROOT/libraries/src/Dispatcher/Dispatcher.php:165
14	Joomla\CMS\Dispatcher\Dispatcher->dispatch()	JROOT/libraries/src/Component/ComponentHelper.php:423
15	Joomla\CMS\Component\ComponentHelper::dispatchComponent()	JROOT/libraries/src/Component/ComponentHelper.php:364
16	Joomla\CMS\Component\ComponentHelper::renderComponent()	JROOT/libraries/src/Application/AdministratorApplication.php:106
17	Joomla\CMS\Application\AdministratorApplication->dispatch()	JROOT/libraries/src/Application/AdministratorApplication.php:149
18	Joomla\CMS\Application\AdministratorApplication->doExecute()	JROOT/libraries/src/Application/CMSApplication.php:340
19	Joomla\CMS\Application\CMSApplication->execute()	JROOT/administrator/includes/app.php:35
20	require_once()	JROOT/administrator/index.php:36

**Comment by anuragteapot** [comment]
@stutteringp0et I am able to create new "Viewing Access Level" can you check with a new installation<br>
![screen shot 2017-12-09 at 06 27 44](https://issues.joomla.org/uploads/1/67b83e678edf5be394065ca7b61a3682.png).<br>![screen shot 2017-12-09 at 06 29 35](https://issues.joomla.org/uploads/1/ab1870571333c30ec0eb4729b8b97112.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19028">issues.joomla.org/tracker/joomla-cms/19028</a>.</sub>

**Comment by ghost** [comment]
Can't confirm:
![bildschirmfoto 2017-12-09 um 08 45 55](https://user-images.githubusercontent.com/8235763/33793739-7733bd28-dcbd-11e7-8287-0410c26bd3eb.jpg)

**Comment by stutteringp0et** [comment]
will do

**Comment by stutteringp0et** [comment]
Starting another download and going to bed - maybe it'll finish overnight.  Don't ever get satellite internet.

**Comment by stutteringp0et** [comment]
OK, something was up with that installation.
