### ISSUE TITLE
Joomla 4 alpha installation issue

### ISSUE THREAD

**Issue by Artwebco** [joomla/joomla-cms#19022]
I'm trying to install Joomla 4 alpha on localhost using MAMP server (PHP 7.1)
During installation process it asking me to choose server version, but there is nothing to chose.

![screen shot 2017-12-08 at 09 51 26](https://issues.joomla.org/uploads/1/ed570c217c6a3d758a20d350e568b836.jpg)

Regards,

**Comment by ghost** [comment]
closed as duplicate Report of #18783 #18660 #18935
