### ISSUE TITLE
Multiple anchors into an article (K2 or Joomla) don't work if SEF is enabled

### ISSUE THREAD

**Issue by Repitol** [joomla/joomla-cms#19039]
### Steps to reproduce the issue
1 : create an article with several links to anchors into the same article (part1 / part 2 / part 3 / part 4)
2 : create some "back to top" links with an anchor at top of the page
3 : enable Joomla SEF

### Expected result
click on link part 2 should lead to "part 2" anchor
"back to top" link should go back to the top
then click to "part 3" should go to Part 3 and so on

### Actual result
First click on any link works : you go to the expected part of the article
click on "back to top" : works
second click on another link fails : you don't reach the part you click for
url is correctly rewritten as expected : full SEF url with "#anchor-part3" or "#anchor-part4" at the end
but you stay where you are

If SEF is disabled : everything goes well

### System information (as much as possible)
Joomla 3.8.2
problem seen with Firefox, Chrome, Safari, Explorer, Opera

### Additional comments
Everything was ok with previous Joomla versions 3.4 and maybe 3.5
I did the automatic upgrades in Joomla Backend when available
The website owner called me for a fix when it was upgraded to 3.8.2 but I'm not sure this is due to this version only. It could happen on 3.5 or 3.6 but not seen actually.

Thanks

**Comment by brianteeman** [comment]
Sounds very odd. Is there a link where it can be seen happening

**Comment by infograf768** [comment]
I can't reproduce here. testing on multilingual site.

**Comment by Repitol** [comment]
Hi brianteeman
I had to disable SEF on this page but I can make a link to a copy
One moment please, I will give the link.

merci Infograf768, Bizarre bizarre ce truc. La seule solution que j'ai eu a été de désactiver le SEF
j'ai testé avec plusieurs éditeurs.

**Comment by Repitol** [comment]
Here's the link
http://www.guillotprefa.fr/escaliers-marche-a-marche
links are just after line "Galerie photo par types de pose :"
I just tried : it works on 2 or 3 links then it doesn't work anymore

**Comment by brianteeman** [comment]
its not a joomla problem. there is a javascript error in one of the template files that is breaking the anchors. For further support please use the forum

**Comment by Repitol** [comment]
Ok fine thanks for your answer
But that's weird it goes well when SEF is disabled. Javascript error should brake the anchors too right ?

**Comment by ghost** [comment]
@Repitol Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding.
