### ISSUE TITLE
Database tables without primary key do not work with mysql group replication

### ISSUE THREAD

**Issue by michifischer** [joomla/joomla-cms#19032]
### Steps to reproduce the issue
Install Joomla 3.8.2 and use a member of a mysql group replication as database server.

### Expected result
Joomla installs.

### Actual result
The installer gives 
"Error
The table does not comply with the requirements by an external plugin."

### System information (as much as possible)
PHP 7.2
MySQLi driver
MySQL Sever version 5.7.18 with multimaster group replication

### Additional comments
The problem is missing key statements for the following tables in installation/sql/mysql/joomla.sql:
#__finder_terms_common
#__utf8_conversion

Suggested fix:
CREATE TABLE IF NOT EXISTS `#__finder_terms_common` (
  `term` varchar(75) NOT NULL,
  `language` varchar(3) NOT NULL,
  PRIMARY KEY (`term`,`language`),
  KEY `idx_word_lang` (`term`,`language`),
  KEY `idx_lang` (`language`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `#__utf8_conversion` (
  `converted` tinyint(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`converted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

**Comment by ghost** [comment]
Can a MySQL-Experienced User comment this Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19032">issues.joomla.org/tracker/joomla-cms/19032</a>.</sub>

**Comment by alikon** [comment]
as far as i know every table must have a primary key....i'll submit a pr ....

**Comment by alikon** [comment]
@michifischer can you test with #19460

**Comment by michifischer** [comment]
MySQL tables do not necessarily need a primary key per se [1]. Only if you are using group replication it's a must [2].

[1] https://dev.mysql.com/doc/refman/5.7/en/create-table.html#create-table-indexes-keys
[2] https://dev.mysql.com/doc/refman/5.7/en/group-replication-requirements.html

**Comment by ghost** [comment]
closed as having Pull Request #19460
