### ISSUE TITLE
The visualitzation of List files of Media Folder its very slowly

### ISSUE THREAD

**Issue by rbuchjoomla** [joomla/joomla-cms#19040]
### Steps to reproduce the issue

There is a malfunction at Menu Media of latest Joomla version. We have very much files and when click over this menu option, the list run very and very slow. Very slowly.

### Expected result

The list files should be very fast. At the first step only it should list the first level and not all hyerarchie levels of main folder.

### Actual result

The list of files of the folder media its very slowly

### System information (as much as possible)

Nothing... tic tac, tic tac...

**Comment by ghost** [comment]
Similar to your Comment at https://github.com/joomla/joomla-websites/issues/1099: Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
