### ISSUE TITLE
Alternate Text  for Media type custom field

### ISSUE THREAD

**Issue by michwebdev** [joomla/joomla-cms#19042]
### Steps to reproduce the issue
Add a custom field of type Media.  There is not a way to add alt text as there is in, for example JCE's Image Manager.
Run WAVE toolbar or other accessibility audit to see error.

### Expected result
When creating the custom field, after selecting type = Media,  include an option to add alt text, possibly after the Default Value option field.

### Actual result
Images are displayed without alt text and are flagged as errors in accessibility audits.

### System information (as much as possible)
Joomla 3.7.x and higher 

### Additional comments
Using alt attributes on img elements will allow people using screen readers to extract meaning from images.

**Comment by Quy** [comment]
Duplicate #16071
