### ISSUE TITLE
[Feature] - Login attempts?

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#19041]
What are people’s tboughts on adding a new login attempts feature? Which will show on each users profile and in a venerable overview with some basic filters I.e. by User and User group? 

Default limit 100 attempts per user, which include all successful, failed etc. 

This would provide a basic level of monitoring for user accounts.

**Comment by brianteeman** [comment]
my 2c its not needed in core. there are addons available that will do this

**Comment by mbabker** [comment]
IMO it is best left to the ecosystem.  That type of logging could become very problematic on a high resource site.

**Comment by tonypartridge** [comment]
Okie will close
