### ISSUE TITLE
[4.0] There is no way to put a sub menu

### ISSUE THREAD

**Issue by Miure4475** [joomla/joomla-cms#19046]
### Steps to reproduce the issue

When we try for a menu with a dependency we have no option for this

### Expected result

Have a menu to chose the dependency

**Comment by zero-24** [comment]
@Cmillept this is the place where the coding happens 😄 Please ask support questions in the support forum you can find here: https://forum.joomla.org.

**Comment by Miure4475** [comment]
@zero-24 yes I know but joomla 4 is in alpha version and I'm not sure if is that function implemented or not

**Comment by ghost** [comment]
@Cmillept thanks for Report. Please give in a future Report more Informations so Volunteers know you talk about 4.0. 

Example:

### System information
4.0.0-dev
Multilanguage Site (4 Lang.) & Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

<hr>

Reopened and Title changed.

**Comment by C-Lodder** [comment]
@Cmillept - please explain in more detail. Currently I have no idea what you mean.

**Comment by brianteeman** [comment]
I am closing this after 5 months without explanation - it can always be reopened if updated with an understandable explanation - perhaps with screenshots
