### ISSUE TITLE
[4.0] Error in changing the layout of featured articles

### ISSUE THREAD

**Issue by Miure4475** [joomla/joomla-cms#19045]
### Steps to reproduce the issue

When we have the main menu with Featured Articles and we change the number of columns nothing happens but after moving the main page to category blog and then again to Featured Articles it gets the columns requested earlier

### Expected result

It was hoped that he would alter the columns without having to do the process I said earlier

### Actual result

Does not change anything

### System information (as much as possible)

I'm using a free InfinityHost host with all minimum requirements for joomla 4

**Comment by zero-24** [comment]
> I'm using a free InfinityHost host with all minimum requirements for joomla 4

Please double check that? Do you test Joomla 4 or Joomla 3 as Joomla 4 is alpha software not ready for production usage yet 😄

**Comment by Miure4475** [comment]
@zero-24 I'm using Joomla 4 in Joomla 3.8 I know how to do that but in 4 as already been implemented??

**Comment by ghost** [comment]
Changed Title "[4.0] ..." (if i understand Comment correct).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19045">issues.joomla.org/tracker/joomla-cms/19045</a>.</sub>

**Comment by C-Lodder** [comment]
> I'm using Joomla 4 in Joomla 3.8

What do you mean by this? Either you're using Joomla 3.8, *OR* you're using Joomla 4 (alpha)

**Comment by ghost** [comment]
@C-Lodder i guess he mean "I'm using Joomla 4. In Joomla 3.8 I know ..."

**Comment by Miure4475** [comment]
@franz-wohlkoenig yes I'm using joomla 4 Alpha 2 I only open this issue to say that bug to developers know about that

**Comment by Cmillept** [comment]
you are so ugly bro damn.... try to fix that face xD

**Comment by Cmillept** [comment]
u dont understand nothing about pc's
reeally...

**Comment by brianteeman** [comment]
Closing as we have another issue on the same topic #21106
