### ISSUE TITLE
[com_fields] Media Field Default value always applied if value is empty

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#19057]
so if you choose to wipe the media field custom field so there isn't a default value anymore it is applied always. 

I would expect the default image to be loaded as a default, but not be forced to be in there. If the field value is empty when editing an article it should stay empty?

**Comment by brianteeman** [comment]
confusing default and placeholder?

**Comment by tonypartridge** [comment]
@brianteeman whilst that may be possible at times... No I am not, I want to set a default image. In this case for a slideshow for example. But say 1 or 2 pages I don't want the slideshow to show. So I delete the image value so nothing is shown.

**Comment by mbabker** [comment]
Then you can't set a default on the field.  Otherwise you are asking for a major internal (and B/C breaking) change of JForm.  When a field does not have a value, if a default is specified in the field definition that is used.

**Comment by brianteeman** [comment]
yeah you cant replace a default with an empty value - thats html specification

**Comment by tonypartridge** [comment]
S
