### ISSUE TITLE
Author option in the Compact list of tagged items

### ISSUE THREAD

**Issue by csbalazs** [joomla/joomla-cms#19056]
I would like to appear the author in the tagged items list (Tags -> Compact list of tagged items -> List Layouts) like the article  category list (Articles -> Category List -> List Layouts).
![screen shot 2017-12-13 at 09 58 01](https://issues.joomla.org/uploads/1/0778abda65f824536a7fa61d5329b2a6.png)
![screen shot 2017-12-13 at 09 58 04](https://issues.joomla.org/uploads/1/af86f3d245fb0ae98903adf470660273.png)

**Comment by csbalazs** [comment]
+ and the header:
![screen shot 2017-12-13 at 10 04 02](https://issues.joomla.org/uploads/1/5805c6aa8a50dabfee4346e8cf596bc9.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19056">issues.joomla.org/tracker/joomla-cms/19056</a>.</sub>

**Comment by mbabker** [comment]
This one's not really practical.  It would expose the creator for all content types, not just articles.  This may be OK on a site where tags are only being used with com_content, but if you have other components with tagged content (i.e. com_newsfeeds or com_contact) then it really doesn't make a lot of sense.

**Comment by brianteeman** [comment]
Closed for the reason stated above
