### ISSUE TITLE
[4.0] Installer: Install "Languages", try install "Sample Data" get Screen "Languages"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#19054]
### Steps to reproduce the issue
- Install 4.0
- click on "Customize Installation"
- install Languages for a Multilang. Site.
- after this Step you got Screen for "Costumize Installation" again
- If you try install "Sample Data" the Screen where you can choose Languages for a Multilang. Site comes up again.
- You have to scrool down, click "Skip", then you get Screen for Sample Data.
### Expected result
Screen with Languages isn't shown if Languages are installed.
### System information
4.0.0-dev
Multilanguage Site (4 Lang.) & Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by anuragteapot** [comment]
Please correct Customize spelling in Steps to reproduce the issue

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19054">issues.joomla.org/tracker/joomla-cms/19054</a>.</sub>

**Comment by ghost** [comment]
1. Install Languages for Multilang. Site
2. After that you want to install Sample data: then Languages-Screen come again, you have to scroll down and hit "Skip" to come to Screen for Sample Data-Installation.

**Comment by anuragteapot** [comment]
@franz-wohlkoenig Sorry but, there was a spelling mistake in Steps to reproduce the issue
<code> Costumize --> Customize</code><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19054">issues.joomla.org/tracker/joomla-cms/19054</a>.</sub>

**Comment by ghost** [comment]
@Anu1601CS done.

**Comment by brianteeman** [comment]
If we start to report spelling mistkeas on hitbug coments we will never stop :)

**Comment by anuragteapot** [comment]
yeah, it only for a proper system :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19054">issues.joomla.org/tracker/joomla-cms/19054</a>.</sub>

**Comment by Quy** [comment]
@franz-wohlkoenig Duplicate of #16337?

**Comment by ghost** [comment]
In Difference to #16377 here a Lang.-Package is found. But to get Sampla Data installed is difficult so its a UI-Issue in my Opinion.

**Comment by ghost** [comment]
Closing this as i cannot replicate it anymore since using http://launch.joomla.org/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19054">issues.joomla.org/tracker/joomla-cms/19054</a>.</sub>
