### ISSUE TITLE
Error while performing an Ajax request

### ISSUE THREAD

**Issue by neo191987** [joomla/joomla-cms#19055]
Hi after upgrading to 3.8.3 (PHP 7.1.12) I get this error(applies only to the site). Extensions -> Language(s) -> Overrides -> Site -> Error while performing an Ajax request.
Console error
[screen shot 2017-12-13 at 08 25 13](https://issues.joomla.org/uploads/1/c37a49f1ad58ea8d488563297fd04773.jpg)

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.

**Comment by neo191987** [comment]
Hi today and with a clean installation, give this problem: mod_fcgid: stderr: PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 1490944 bytes) in /home/andronika/public_html/libraries/joomla/database/driver.php on line 2049

**Comment by brianteeman** [comment]
Please dont comment on closed issues - no one will see them

Please create a new issue with information that would allow someone to try and replicate the issue you have
