### ISSUE TITLE
Systemlink Separator cannot be used without label

### ISSUE THREAD

**Issue by WimVDK** [joomla/joomla-cms#19059]
### Steps to reproduce the issue
Click create menu item > browse > systemlink > separator

According to the description it should be possible to create a separator WITHOUT a label

### Expected result

a horizontal line ? or separator between menu items WITHOUT a label

### Actual result

Separator can only be created WITH label. Setting the option "add menu title" to NO on the "link type" tab does not work. Saving with a blank space as menu label doesn't work either.

### Additional comments

Either the separator's description needs to be changed from "without label" to "with label only" or this is a bug, or a new feature is needed that lets users do exactly what the current description sais it can. Create a menu item separator WITHOUT a label

**Comment by brianpeat** [comment]
I agree with this. If you look at the documentation, the last tip at the bottom of the page actually suggests using a space as the title, but newer versions of Joomla! won't let you even do that.

https://docs.joomla.org/Help38:Menus_Menu_Item_Text_Separator
(Scroll to Quick Tips at the bottom)

So either the description needs to say "With image or text label" or we need to add an option to not render the title/label (which is what I'd rather see).

**Comment by tonypartridge** [comment]
What if you add:  &nsbp; Into it? Does it work then and display as expected?

**Comment by brianpeat** [comment]
Do we really want that to be our official stance though? Because unless the description tells you to do that somewhere, you'll have to either think to try it or google it. And even then, it's a hack honestly. It really should just have an on off switch to render or not render the title. Right now there IS an on off, but it only turns the title on and off if you use an image. And I'd also consider using a blank image a hack.

**Comment by tonypartridge** [comment]
That’s not an official stance, that’s asking if that works as a workaround for now.

**Comment by brianteeman** [comment]
Sent would you ever have a separator that is blank?

**Comment by brianpeat** [comment]
In the past I've wanted to put spaces in the menu and putting a space in the title HAS worked in some versions of joomla. Sometimes I've resorted to using css, but if the template doesn't stick menu id's as a class in the code for each menu item, you have to resort to a bunch of nth child stuff that feels really hacky.

Honestly in the short term, we should probably just change the description from
"A separator with or without a text label, useful to separate items within a menu."
to 
" A separator with an image or a text label, useful to separate items within a menu."

At least then it doesn't lead someone to think they can use it as a blank separator.

Long term though, there ARE times when it's nice to just be able to slap a blank space in a menu. I know it's not the fault of the core, but many templates that have mega menus auto balance the columns based on the number of top level menu items. Being able to pad it with blank spacers fixes it. Usually I have to hack the template to add menu ids and then use css to just hide those menu items.

I just think if you're going to have something called a separator, the option to have it be a blank space would be very handy.

**Comment by mbabker** [comment]
One of the separator options was intended to support Bootstrap 2.3's horizontal divider (http://getbootstrap.com/2.3.2/components.html#navs and search for "Horizontal dividers" heading).  So it should be possible to do an unlabeled and non-imaged separator.

https://github.com/joomla/joomla-cms/commit/95a518a3534f47a58a4e8027bd3bb60231e8853b#diff-46694a9cb6d3db44e100c0343f484e88
https://developer.joomla.org/joomlacode-archive/issue-29128.html

**Comment by WimVDK** [comment]
The current documentation clearly describes that it should be able to use a separator without label and it has indeed worked in the past. I've used it. What i see as a seperator is a horizontal line (<hr>) or blank space area, creating a divider. It's a very useful feature to me (or at least it was), and i'd like to be able to use it again.

**Comment by brianteeman** [comment]
It would be useful to know which joomla version this worked in

**Comment by brianteeman** [comment]
@mbabker thats for the menu heading not the text seperator

**Comment by WimVDK** [comment]
i'd love to tell you but can't remember. Can't check my current sites either because the ones it worked on no longer exist

**Comment by brianteeman** [comment]
And I also cant see where in the docs it says you can use a separator without a label (except when also using an image) unless I am looking in the wrong place

**Comment by brianpeat** [comment]
You can see it when you go to make a menu item. It doesn't infer anything about an image in the description listed next to the menu item. It's not the docs, but still obviously the first thing a user sees when choosing it. Also, if you follow the link I posted earlier, that IS the official docs and the tip no longer works (still not sure when it stopped working though.)

![screen shot 2017-12-14 at 10 20 13 am](https://user-images.githubusercontent.com/10532158/34002526-69f30f34-e0b8-11e7-8ba4-14ba79c34180.png)

**Comment by brianteeman** [comment]
Not in the current version of joomla ;)

<img width="470" alt="screenshotr16-27-52" src="https://user-images.githubusercontent.com/1296369/34002894-c6168ee8-e0eb-11e7-9c48-fd3ea037bc3f.png">

**Comment by brianpeat** [comment]
My screen shot is from Joomla 3.8.3. It's right from my company website running UK language 3.8.3.

**Comment by brianteeman** [comment]
wow thats really wierd

**Comment by brianpeat** [comment]
I just spot checked another client site, same thing, it matches mine. I'll check a few other sites too.

**Comment by WimVDK** [comment]
note: nowhere did i say in the documentation. I said item description and my sites are multi-language but main language is en-GB and also say that (or i wouldn't have created this report)

**Comment by brianpeat** [comment]
I just checked a site I inherited but did not build. Same thing as mine.

**Comment by brianteeman** [comment]
Sorry - i was checking an old site

The text was changed for 3.8.2 https://github.com/joomla/joomla-cms/pull/17970

**Comment by brianpeat** [comment]
Wait, so it works as a line in the ADMIN, but not the front end menus. Things are getting much more interesting now :)

**Comment by WimVDK** [comment]
Now it only needs to work on the front-end too :)

**Comment by brianteeman** [comment]
still dont see how it  "worked in the past"

**Comment by brianpeat** [comment]
I don't believe it ever had an option to show a line, but I do know I used to be able to put a space in as the title. I'm pretty sure that hasn't ever worked in J3 and higher though. it DOES work using the non breaking space code though so I guess at least we could modify that doc I linked to in my first comment to reflect that.

And in fact, that doc page is wrong in that it suggests using space only if you've already added an image, but there's actually an on/off option to hide the title if you're using an image. I guess I need to do some tests and rewrite that quick tip at the bottom, or we just remove it.

**Comment by brianteeman** [comment]
its a wiki so anyone can update it

**Comment by WimVDK** [comment]
If the description is going to be changed and the tooltip, i'd like to make a formal feature request then to have the ability to use a simple horizontal line as a separator on the frontend menu part as well, like what is currently possible on the backend.

**Comment by brianteeman** [comment]
i am still confused by your statement that it used to work. we would need to track down when it was changed and why. there might have been a very good reason for the change

**Comment by brianpeat** [comment]
I suspect (just guessing) that at some point someone thought it was a bad idea to have menu items with no visible title in the admin. Non breaking space still tricks it at least, but that's my guess. And it IS a good practice to not have a bunch of blank items in the list. When I get time I'll test it in 2.5 and see if it works with a regular space and not the non breaking space code.

But as far as it having had an option to HIDE the title on the front end, I don't think that's ever been in there that I can remember.

**Comment by tonypartridge** [comment]
That’s really strange, we need to narrow down the differences are you sure it was uk @brianpeat?

**Comment by Quy** [comment]
There is a work-around. Here is a markup:
```
<li class="item-480 divider"><span class="separator ">Separator</span>
</li>
```
In the custom css file, add the following css:
```
.menu .divider {
  *width: 100%;
  height: 1px;
  margin: 9px 1px;
  *margin: -5px 0 5px;
  overflow: hidden;
  background-color: #e5e5e5;
  border-bottom: 1px solid #ffffff;
}

.separator {
    display: none;
}
```

**Comment by Quy** [comment]
Anything to fix here? There is a solution as provided.

**Comment by alikon** [comment]
lack of interest<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19059">issues.joomla.org/tracker/joomla-cms/19059</a>.</sub>
