### ISSUE TITLE
Database connection

### ISSUE THREAD

**Issue by JoeryR** [joomla/joomla-cms#19063]
### Steps to reproduce the issue

Trying to install joomla 4 and put in my database info gained from my webhost.

### Expected result

a connection with the database and complete installation

### Actual result

An error has occurred while processing your request.
1046 No database selected.

### System information (as much as possible)

joomla 4.0.0 alpha 2

### Additional comments
I'm using the 3.8.3 right now and never had problems with connecting my database.
Think the problem is with tha last 2 questions in the example pic
![naamloos](https://user-images.githubusercontent.com/34521517/33959532-123c0bda-e048-11e7-8c86-70e865b732b8.jpg)

thank you

**Comment by brianteeman** [comment]
pretty sure you cant have a database called mysql

**Comment by JoeryR** [comment]
Hey,
Like I said it is a example pic.
I put in the information my webhost gave me and the database I created before installing it.
Only for the last 2 questions I don't know what to put in there.
Greets

**Comment by Quy** [comment]
Please ask support questions in [Joomla Forums](https://forum.joomla.org/).

**Comment by JoeryR** [comment]
I did, but they send me here cause there's no joomla 4 topic.

**Comment by Yiannistaos** [comment]
PHP/MySQL version?

**Comment by Quy** [comment]
It is really a setup question and not about J4. It applies to J3 too. For the 1st question, you will have to create a table in your database using your hosting control panel. For the last question, you can leave it as it.

**Comment by JoeryR** [comment]
php is 7.1
The thing is I reinstalled 3.8.3 it worked.
I try to install the 4 and I have issues.
I use for both the same database data.

**Comment by JoeryR** [comment]
Like I said, I asked the same question there and they send me here.
Will figure it out myself then.
Thanks anyway
