### ISSUE TITLE
No puedo accesar a la administración de Joomla

### ISSUE THREAD

**Issue by vicbossmx** [joomla/joomla-cms#19061]
### Steps to reproduce the issue
Al intentar normalmente al administrador de Joomla y colocar los datos necesarios, se queda en la misma pantalla, sin avanzar al panel de administrador.
¿Alguna sugerencia?

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
