### ISSUE TITLE
Updating text filters leads to JSON errors in Global configuration and when saving articles.

### ISSUE THREAD

**Issue by celius** [joomla/joomla-cms#19064]
### Steps to reproduce the issue
I updated the Text filters from Global admin, and after that I could not access Global configuration nor edit any articles anymore.

What I saw was in my database table _extensions on line 23 for com_config in the params field was:

{"filters":{"1":{"filter_type":"NH","filter_tags":"","filter_attributes":""},"9":{"filter_type":"BL","filter_tags":"","filter_attributes":""},"6":{"filter_type":"BL","filter_tags":"","filter_attributes":""},"7":{"filter_type":"NONE","filter_tags":"","filter_attributes":""},"2":{"filter_type":"NH","filter_tags":"","filter_attributes":""},"3":{"filter_type":"BL","filter_tags":"","filter_attributes":""},"4":{"filter_type":"BL","filter_tags":"","filter_attributes":""},"5":{"filter_type":"BL","filter_tags":"","filter_attributes":""},"8":{"filter_type":"NONE","filter_tags":"","filter_attributes":""}},}}}

When I changed this to:

{"filters": {"1": {"filter_type": "NH","filter_tags": "","filter_attributes": ""},"9": 
{"filter_type": "BL","filter_tags": "","filter_attributes": ""},"6": 
{"filter_type": "BL","filter_tags": "","filter_attributes": ""},"7": 
{"filter_type": "NONE","filter_tags": "","filter_attributes": ""},"2": 
{"filter_type": "NH","filter_tags": "","filter_attributes": ""},"3": 
{"filter_type": "BL","filter_tags": "","filter_attributes": ""},"4": 
{"filter_type": "BL","filter_tags": "","filter_attributes": ""},"5": 
{"filter_type": "BL","filter_tags": "","filter_attributes": ""},"8": 
{"filter_type": "NONE","filter_tags": "","filter_attributes": ""}}}

.. it works again.

The only difference between these two are the last closing brackets on the list line.

After saving (when it broke) it seems to close with this:
}},}}}

What I fixed seems to be only this:
}}}

### System information (as much as possible)
PHP 7
Joomla 3.8.2 (also checked for 3.8.3 and still an issue there.)

**Comment by brianteeman** [comment]
i can not replicate this
Both before and after changing settings in the text filter the value i have in the database ends with the correct }}}

**Comment by celius** [comment]
Very strange. Then I have no clue as to where the extra brackets came from. I did in fact change the text filters, and that's the only thing I can think of that should have affected this.

**Comment by Quy** [comment]
Please include a screenshot of the changes you did on the Text Filters page.

**Comment by brianteeman** [comment]
I am closing this at this time as not reproducible. It can always be reopened if further information is provided
