### ISSUE TITLE
[4.0] Wrong message on creating a new user.

### ISSUE THREAD

**Issue by anuragteapot** [joomla/joomla-cms#19068]
### Steps to reproduce the issue
Try to create a new user in Administrator area.

### Expected result
Message to be popup.

<b>1</b><code>Notice</code>
Could not instantiate mail function.

<b>2</b><code>Message</code>
User saved.

### Actual result
Message popup ![screen shot 2017-12-14 at 11 48 35](https://issues.joomla.org/uploads/1/0084891f3e7175bf5cce1a89852dc302.png)

<code>Error</code>
Save failed with the following error: Could not instantiate mail function.

### System information (as much as possible)

PHP version: 7.1.11
Joomla! 4.0.0-dev

### Additional comments
In both, the cases the new user is created.

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19068">issues.joomla.org/tracker/joomla-cms/19068</a>.</sub>

**Comment by brianteeman** [comment]
That is the expected behaviour if you are working on a test environment that is not configured to send mail. Please test the mail sending functionality in the global configuration.  If you can confirm that the test in global configuration works then we have a bug. If it doesnt work then its because your test environment is not configured for mail in which case Perhaps we need a better error message - something like "unable to send mail - please check your configuration"

**Comment by ghost** [comment]
Its about Error Message "Save failing …" but User is saved.

**Comment by brianteeman** [comment]
yes the message is wrong but please confirm if the test site can send emails or not

**Comment by ghost** [comment]
sorry, wasn't clear: I confirm only wrong Message, the Test-Environment is not configured to send E-Mails.

**Comment by anuragteapot** [comment]
@brianteeman ,I known but it's about error message <code>save failed</code> but the  user is created.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19068">issues.joomla.org/tracker/joomla-cms/19068</a>.</sub>

**Comment by brianteeman** [comment]
Sorry I was concentrating on the second part of the message not the first. mea culpa

I will take a look at fixing this over the next few days if no one beats me to it

**Comment by brianteeman** [comment]
Comparing it to Joomla 3 it looks like joomla 4 is outputting all messages in the queue inside the same alert output

**Comment by brianteeman** [comment]
OK its a more complex issue that this is exposing. I will create a new issue explaining it

**Comment by brianteeman** [comment]
See #19071 as you can see your small report has revealed several issues - thanks
