### ISSUE TITLE
Problem saving article in frontend

### ISSUE THREAD

**Issue by fabioassenzio** [joomla/joomla-cms#19065]
### Steps to reproduce the issue

Try to disable recaptcha plugin
go to frontend and login with an admin account
edit an article
try to save

### Expected result

saved article

### Actual result

PHP Fatal error:  Call to a member function checkAnswer() on null in /home/uaug0z2o/domains/icfontanellatoefontevivo.gov.it/public_html/libraries/src/Form/Rule/CaptchaRule.php on line 63

### System information (as much as possible)

Joomla 3.8.3
Php 5.6

### Additional comments

If recaptcha is enable there's no problem

**Comment by brianteeman** [comment]
did you disable it in the editing layout tab of the options for the article component

**Comment by fabioassenzio** [comment]
now yes and i confirm it works now, thx<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19065">issues.joomla.org/tracker/joomla-cms/19065</a>.</sub>

**Comment by ghost** [comment]
@fabioassenzio if this Issue is solved please close it, thanks.
