### ISSUE TITLE
Cannot select database type in latest night build

### ISSUE THREAD

**Issue by Basstrup** [joomla/joomla-cms#19060]
### Steps to reproduce the issue
Run the installer on host. On database setup screen drop down does not show options from setup.xml - it only shows non
![screen shot 2017-12-13 at 18 40 22](https://issues.joomla.org/uploads/1/726b817bd334898ac6bf0c20f3e3dc6f.jpg)
### Expected result
supported="mysqli,pdomysql,postgresql"

### Actual result
only shows NONE

### System information (as much as possible)
php7.1

**Comment by C-Lodder** [comment]
Please add `[4.0]` to the issue title

**Comment by ghost** [comment]
closed as duplicate Report #18660
