### ISSUE TITLE
Error while performing an Ajax request

### ISSUE THREAD

**Issue by neo191987** [joomla/joomla-cms#19067]
Hi yesterday when you update from version 3.8.2 to 3.8.3, today and clean installation displays this problem.  Extensions -> Language(s) -> Overrides -> Site -> Error while performing an Ajax request.
Error
mod_fcgid: stderr: PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 1490944 bytes) in /home/andronika/public_html/libraries/joomla/database/driver.php on line 2049

If I set an unlimited memory, the server will crash

**Comment by brianteeman** [comment]
is this on a clean install?

**Comment by neo191987** [comment]
And to clean and update

**Comment by brianteeman** [comment]
I mean do you have any extensions installed

**Comment by neo191987** [comment]
He had worked before, and I can not understand what caused him

**Comment by brianteeman** [comment]
without more information as i have asked it is impossible to guess

**Comment by ghost** [comment]
Can't confirm on a Production-Site which was updated from 3.8.2 > 3.8.3. This Site has one non-Core Plugin (Socialmeta).

**Comment by neo191987** [comment]
There was no problem in the previous version. It affects only the site and not the administration. I do not have this plugin available.

**Comment by brianteeman** [comment]
PLEASE ANSWER THE QUESTIONS

**Comment by ghost** [comment]
Question of @brianteeman was if you have 3rd-Party-Plugins installed. My Plugin was an Example.

**Comment by neo191987** [comment]
I have many plugins installed at the moment. I think a plugin is causing it there is a way to figure out.

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
