### ISSUE TITLE
Http lib tries to use cUrl instead of Stream transport, although allow_url_fopen is enabled and curl is disabled

### ISSUE THREAD

**Issue by LawrenceWence** [joomla/joomla-cms#19066]
### Steps to reproduce the issue
PHP settings with
disable_functions	exec, system, proc_open, popen, curl_exec, curl_multi_exec, show_source
allow_url_fopen	On

### Expected result
Stream transport should be used by Http library, enabling update check of Joomla and extensions

### Actual result
Updater does not work, complains that curl_exec() is not activated, but does not try to fallback to stream transport, although allow_url_fopen is set to ON.

My workaround was to remove the "CurlTransport.php" from the Transport folder of the Http library. Since that folder is scanned for available transports the curl-transport is no longer available. After that the Joomla Updater was working just fine.

### System information (as much as possible)
PHP 7.2.0
disable_functions	exec, system, proc_open, popen, curl_exec, curl_multi_exec, show_source
allow_url_fopen	On

**Comment by mbabker** [comment]
To be honest, I would be very hesitant to start changing our checks to include disabled function lists.  Otherwise in theory the check would have to include every `curl_*()` function we use.  The system passes all checks for ext/curl being installed and enabled, that is why the CurlTransport gets used.

**Comment by LawrenceWence** [comment]
If you would direct me to the php script that does the check I could at least try to understand, why it's not working for my hoster. Guess it's always good to understand why it's not working in this case.

Thanks

**Comment by mbabker** [comment]
The same CurlTransport.php file, the `__construct()` and `isSupported` methods.

**Comment by LawrenceWence** [comment]
Yeah, I understand your point. 
For the hoster the curl_exec() is the "dangerous" method, which (I guess) is only disabled for certain packages/customers. So module is loaded in general, but disabled for some users.

Since I could not find any previous error report in that direction I guess it's not done this way very often. For my peace of mind I'll ask my hoster if he could simply add curl_init() to the list of disabled functions, that should also fix it for other customers, and I don't have to do local fixes.

Thanks for your support mbabker!

**Comment by ghost** [comment]
@LawrenceWence if this Issue is solved please close it, thanks.

**Comment by LawrenceWence** [comment]
For me it can be solved by different php settings (either disable curl completely or also add curl_init() to the list of disabled functions), so I'll close it.
