### ISSUE TITLE
[4.0] Show user custom fields error in administrator.

### ISSUE THREAD

**Issue by anuragteapot** [joomla/joomla-cms#19077]
### Steps to reproduce the issue
Open :
<code>Global Configuration -> Contacts</code>
See end of page.
<code>User custom fields</code>

### Expected result
Warning not be present.

### Actual result
Warning present.
![capture10](https://user-images.githubusercontent.com/30978328/34042228-a55b62ec-e1c1-11e7-8c32-131880f371cc.PNG)

### System information (as much as possible)
PHP version: 7.1.11
Joomla! 4.0.0-dev

**Comment by ghost** [comment]
are you on latest dev? As far as i remember was this Issue solves a few Days ago:
![bildschirmfoto 2017-12-15 um 13 49 21](https://user-images.githubusercontent.com/8235763/34042837-cba9206a-e19e-11e7-957b-945bc4b32dee.jpg)

**Comment by anuragteapot** [comment]
@franz-wohlkoenig ok , let me check on latest dev.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19077">issues.joomla.org/tracker/joomla-cms/19077</a>.</sub>

**Comment by anuragteapot** [comment]
@franz-wohlkoenig I am still getting the same warning on new Dev. Can you provide me a link to latest Dev and PR which solve this issue- Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19077">issues.joomla.org/tracker/joomla-cms/19077</a>.</sub>

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/19008

**Comment by ghost** [comment]
@Anu1601CS latest dev please see screenshot below: change to "4.0-dev" and click on green Button right Side "Clone or download" > "Download zip".

![bildschirmfoto 2017-12-15 um 15 11 00](https://user-images.githubusercontent.com/8235763/34045723-7a917af4-e1aa-11e7-9d25-d163f352c32e.jpg)

**Comment by Anu1601CS** [comment]
@franz-wohlkoenig Sorry,  but I am getting same warning on new latest install.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19077">issues.joomla.org/tracker/joomla-cms/19077</a>.</sub>

**Comment by Anu1601CS** [comment]
Is any customization is needed because I installed and check that warning is present or not.
The warning still present.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19077">issues.joomla.org/tracker/joomla-cms/19077</a>.</sub>

**Comment by Anu1601CS** [comment]
@franz-wohlkoenig But, I have tested on PR #19008 manually it fixes the issue. I think PR does not merge successfully with main branch https://github.com/Anu1601CS/joomla-cms/blob/e1ab874f1b3e3dbd8ed65a735c3aeb2623e3fbb4/administrator/components/com_contact/config.xml#L345
![screen shot 2017-12-15 at 14 42 23](https://issues.joomla.org/uploads/1/4fb04d4b8d1c523f2f1787c5bb97774a.png).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19077">issues.joomla.org/tracker/joomla-cms/19077</a>.</sub>

**Comment by anuragteapot** [comment]
@franz-wohlkoenig Thanks, Issue is Fixed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19077">issues.joomla.org/tracker/joomla-cms/19077</a>.</sub>

**Comment by anuragteapot** [comment]
Issue is fixed with PR #19008
