### ISSUE TITLE
markup in title attribute does not render in tooltip

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#19074]
### Steps to reproduce the issue
Go to Global Configuration > Text Filters
Hover cursor over a field under Filter Tags2 column.

### Expected result
The number in superscript.

### Actual result
`<sup>2</sup>` markup.

![title-superscript](https://user-images.githubusercontent.com/368084/34020886-91cc6f90-e0eb-11e7-9e09-9211992e9331.gif)

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19074">issues.joomla.org/tracker/joomla-cms/19074</a>.</sub>

**Comment by dgrammatiko** [comment]
This is related to tool tips and to be more specific the lack of tooltips!

**Comment by brianteeman** [comment]
isn't this the same as #17255

**Comment by Quy** [comment]
Yes, but for v3. Close this one?

**Comment by brianteeman** [comment]
Ah - so not technically the same then ;)
This can be fixed for J3 by using a tooltip/popover which it should have been for consistency anyway in J3

**Comment by Quy** [comment]
A possible solution without using a tooltip/popover is to do a string replace `<sup>2</sup>` to `&sup2;`, however, the font size is a tad smaller. Would this be a consideration?

**Comment by brianteeman** [comment]
downside is that would mean all language files would have to be updated

**Comment by Quy** [comment]
Not necessarily. It can be changed where the title attribute is only.

`title="' . JText::_('JGLOBAL_FILTER_TAGS_LABEL') . '"'`
to
`title="' . str_replace('<sup>2</sup>', '&sup2;', JText::_('JGLOBAL_FILTER_TAGS_LABEL')) . '"'`

I know it is a brute force way of doing so don't know if this is acceptable.

**Comment by brianteeman** [comment]
Really not a fan. That's very hacky and for consistency of the ui it should be a tooltip/popover anyway

**Comment by brianteeman** [comment]
Closed see #19104
