### ISSUE TITLE
[4.0] phpmailer multiple issues

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#19071]
### Steps to reproduce the issue
Verify that phpmail will send emails on a your server with Joomla 3. You can use either the test button in global configuration or create a new user in the admin or the contact form on the front end

Once you have verified that it phpmail works on your server with joomla 3 - try the same with joomla 4 on the same server

## Issue ONE
Test button in global configuration returns the following error message
> The most recent request was denied because it contained an invalid security token. Please refresh the page and try again.

## Issue TWO
Creating a new user in the admin returns the following error message
> Save failed with the following error: Could not instantiate mail function.

This last message reveals TWO issues
1. the save was successful - it was only the sending of the mail that failed
(in J3 there would be TWO messages - one a successs on the save and one a fail on the mail)

2. the string  "Could not instantiate mail function" comes directly from phpmailer
https://github.com/joomla/joomla-cms/blob/d797b585d4cbbbd9e4c8ef219580a9f07ade0a04/libraries/vendor/phpmailer/phpmailer/src/PHPMailer.php#L1968

BUT it should be being converted to a joomla string with this code here
https://github.com/joomla/joomla-cms/blob/d797b585d4cbbbd9e4c8ef219580a9f07ade0a04/libraries/src/Mail/language/phpmailer.lang-joomla.php#L21

I suspect that fixing point 2 above will fix point 1 as well.

## Issue Three
Sending a contact on the front end

As expected from the other tests it doesnt work and we get a 500 Could not instantiate mail function.

**Comment by mbabker** [comment]
See https://github.com/joomla/joomla-cms/pull/19072 for part of this.  There's a PHPMailer bug fix (B/C break) from over a year ago that looks to have broken the code.
