### ISSUE TITLE
[4.0] uninstalling a file extension does not trigger manifest script

### ISSUE THREAD

**Issue by avjoomla** [joomla/joomla-cms#19085]
### Steps to reproduce the issue
Install a file extension that includes a script file with <scriptfile> in manifest xml. Scriptfile should have a postflight, preflight or unistall method with some custom code. Unistall the extension.
I necessary, I could create a very small test installation zip for you.

### Expected result
preflight, uninstall and postflight methods in manifest script (script.php) are executed

### Actual result
Non of the methods is executed but script file is deleted properly

### System information (as much as possible)
Joomla! 4.0.0-dev Development [ Amani ] 19-November-2017 16:34 GMT
Local XAMPP Apache/2.4.26 (Win32) OpenSSL/1.0.2l PHP/7.1.7 on Windows 7

### Additional comments
This ussue only happens on uninstall. Install works fine.
I think basically the problem is, that the getElement() function in the FileAdapter class tries to locate the script file with
```$manifestPath = \JPath::clean($this->parent->getPath('manifest'));```
but this path is not set at any time for the FileAdapter
On other adpaters (like PackageAdapter, PluginAdapter this issue does not happen, too).

**Comment by brianteeman** [comment]
Just to  confirm that this works on J3 ??

**Comment by avjoomla** [comment]
Yes, tested with Joomla! 3.8.3

**Comment by ghost** [comment]
@avjoomla can you please test if this Issue is resolved?

**Comment by avjoomla** [comment]
Hi,
no it is not.
Regards,
Aicha

**Comment by franz-wohlkoenig** [comment]
@avjoomla please mark your test as unsuccessfully (how to: https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results)

**Comment by Hackwar** [comment]
#39180 should fix this. Please test that PR. Closing this issue.
