### ISSUE TITLE
[4.0] Replace CSS class hidden-*-* with d-*-*

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#19088]
In BS4-beta, the `hidden-*-*` classes were removed in favour of `d-*-*`.

This needs to be applied over the entire CMS

**Comment by dgrammatiko** [comment]
Because `d` means hidden... in another parallel universe

**Comment by C-Lodder** [comment]
Yeah it's stupid, but `d` === `display`

**Comment by dgrammatiko** [comment]
If d stands for display then hidden === d make no freaking sense, but that’s ok because bootstrap doesn’t make any sense anymore 😂

**Comment by C-Lodder** [comment]
Well it does make sense cause before you had to use `hidden-` **or** `visible-`, and now it's just `d-`, so the approach is better. It also couples nicely with the flex utilities

The fact it's `d-` instead of `display-` is odd but meh.

**Comment by dgrammatiko** [comment]
Well for a BEM fan bootscrap will never make any sense. Anyways this needs to be done

**Comment by brianteeman** [comment]
d stands for display utilities and when you look at the totality of what the new display utility classes do then it makes sense https://getbootstrap.com/docs/4.0/utilities/display/

**Comment by infograf768** [comment]
Would not this be not B/C?
I tested some 3.8. components using radio fields and I found out that all such fields needed the class to be changed to 
```
type="radio"
class="switcher"
```
because otherwise, they just would not work at all.

I understand many aspects will not be B/C in 4.0, but have'nt we been told that an extension working fine in 3.9 will be OK for 4.0 ?

This is a genuine question, not a rant.

**Comment by C-Lodder** [comment]
@infograf768 - I'm referring to `hidden-*-*`, not `hidden-*`

The later was deprecated in BS 2.3 if I rightly remember. BS4 moved to the new display utilities in beta-1 and seeing as J4 is in alpha, it's fine.

Side note, this has nothing to do with the switcher. The `switcher` class is optional on fields, not required

**Comment by infograf768** [comment]
> Side note, this has nothing to do with the switcher. The switcher class is optional on fields, not required

I understand this has nothing to do with the switcher. But when you have though a class `class="btn-group btn-group-yesno"` in 3.9, it will not work in 4.0.

**Comment by C-Lodder** [comment]
Please open a new issue.

You may have a valid point, but I do not want to have to look through unrelated issues in the future, for the topic I need to search for

**Comment by infograf768** [comment]
Sure.

**Comment by infograf768** [comment]
https://github.com/joomla/joomla-cms/issues/19113

**Comment by ciar4n** [comment]
PR created #19332

**Comment by ghost** [comment]
closed as having Pull Request #19332
