### ISSUE TITLE
[4.0] [joomla-framework/database] Please confirm whether there is a problem !

### ISSUE THREAD

**Issue by ztj1993** [joomla/joomla-cms#19097]
Please confirm whether there is a problem !
https://github.com/joomla-framework/database/issues/105

**Comment by ghost** [comment]
closed as Issue is reported in joomla-framework/database#105<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19097">issues.joomla.org/tracker/joomla-cms/19097</a>.</sub>
