### ISSUE TITLE
[4.0] where is the github class in joomla 4?

### ISSUE THREAD

**Issue by diddipoeler** [joomla/joomla-cms#19091]

**Comment by ghost** [comment]
Can you please explain what you mean?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19091">issues.joomla.org/tracker/joomla-cms/19091</a>.</sub>

**Comment by Bakual** [comment]
In J3, we have JGithub (https://github.com/joomla/joomla-cms/tree/staging/libraries/joomla/github)
It's deprecated for 4.0 and thus removed in J4.
If you need it, it can be retrieved using composer.

Closing.
