### ISSUE TITLE
Parent Tag Item

### ISSUE THREAD

**Issue by rgblogs** [joomla/joomla-cms#19101]
### Steps to reproduce the issue

1. Go to components , then tags.
2. Add some nested tags
3. Click on search tools

Select parent Tag Item is missing (like select parent menu item)

### Expected result

There should be filter to select all tags withing the parent tag items

**Comment by ghost** [comment]
please add System Informations like below, thanks.
### System information
 3.8.4-dev
Multilanguage Site (4 Lang.) & Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19101">issues.joomla.org/tracker/joomla-cms/19101</a>.</sub>

**Comment by tonypartridge** [comment]
@franz-wohlkoenig I don’t think I added a parent filter to tags, a worthy addition can you label it feature request?

**Comment by ghost** [comment]
Label is set on Issue Tracker. I have no Permissions setting Label on Github.

**Comment by brianteeman** [comment]
If it is added for tags then it should probably be added for everything that has a parent - eg categories

**Comment by Septdir** [comment]
It would be nice to make a parent filter in `com_menu\items`

**Comment by ghost** [comment]
closed as having Pull Request #22322
