### ISSUE TITLE
Unknown column 'stability' in 'field list'

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#19107]
### Steps to reproduce the issue
on joomla 3.8
database fixed
check new update
Unknown column 'stability' in 'field list'

in backend and now in front-end ...

**Comment by ghost** [comment]
Can't confirm. 

Set "Database > fix", then "Joomla Update" > "Check for Updates": Works as expected in Front- and Backend.

**Comment by micker** [comment]
did you have an idea about this sql request ?
=> maybe an update for futur compatibility check ?
i have some site with the same problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19107">issues.joomla.org/tracker/joomla-cms/19107</a>.</sub>

**Comment by ghost** [comment]
No, i haven't as i'm no Developer. But sure other will.

**Comment by ggppdk** [comment]
To see where the error is thrown you could enable Joomla DEBUG, 
- but to get both the location of the error and also get the DB query too

Try replacing in
**administrator/templates/isis/error.php**

(similar for frontend template, but for frontend undo the change as soon as you get the error information)

```php
<?php if ($this->debug) : ?>
	<br/><?php echo htmlspecialchars($this->error->getFile(), ENT_QUOTES, 'UTF-8');?>:<?php echo $this->error->getLine(); ?>
<?php endif; ?>
```

**with**
```php
<?php if (1 || $this->debug) : ?>
	<br/><?php echo htmlspecialchars($this->error->getFile(), ENT_QUOTES, 'UTF-8');?>:<?php echo $this->error->getLine(); ?>
	<?php if ($this->error instanceof JDatabaseExceptionExecuting) : ?>
		<br/><?php echo htmlspecialchars($this->error->getQuery(), ENT_QUOTES, 'UTF-8');?>
	<?php endif; ?>
<?php endif; ?>
```

**Comment by micker** [comment]
i found sorry ... an update.xml
