### ISSUE TITLE
extensionscdn.joomla.org SSL certificate expired yesterday

### ISSUE THREAD

**Issue by Sophist-UK** [joomla/joomla-cms#19102]
### Steps to reproduce the issue

Use the Install from Web page in Joomla3 when your PC has a means of highlighting such issues (I use ESET Internet Security).

### Expected result

Certificate is valid

### Actual result

Certificate is expired.

**Comment by Sophist-UK** [comment]
Certificate expired on 18/12/2017 (midnight yesterday).

**Comment by Sophist-UK** [comment]
Also, icons for extensions no longer show up in a browser (like Chrome) configured to reject invalid certificates.

**Comment by ghost** [comment]
thanks for report, this issue belongs to https://github.com/joomla/jed-issues/issues/new > please create a new Issue there as i'm closing this Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19102">issues.joomla.org/tracker/joomla-cms/19102</a>.</sub>

**Comment by Sophist-UK** [comment]
https://github.com/joomla/jed-issues/issues/31
