### ISSUE TITLE
[4.0][3.9] css incompatibilies

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#19113]
Normally, any third party extension working fine in 3.9 should be OK in 4.0.
I found out that this was not the case for the radio field class.
Other stuff may also be at stake. Did not test all.

a 3.8 or 3.9 extension may use the class `class="btn-group btn-group-yesno"` for a radio field as this is the norm there.

Unhappily, such a class will just break the field in 4.0, i.e. we can't switch.
For it to work, we have to change the class to `class="switcher"`

@C-Lodder

**Comment by brianteeman** [comment]
Isnt that the expected behaviour - I didnt think the comment about extensions working applied to the css

**Comment by C-Lodder** [comment]
Am I right in asusming the `btn-group btn-group-yesno` class changed the button sizes and ensured one was red and the other was green?

**Comment by brianteeman** [comment]
as far as i can tell then yes

**Comment by C-Lodder** [comment]
@infograf768 The `btn-group` class it still supported. I don't know about `btn-group-yesno` though as I can't remember that far back. If it doesn't work, then I can add it back in.

**Comment by brianteeman** [comment]
I just tested an instance of 	`class="btn-group btn-group-yesno"
` that is still present in J4 - it looks ugly but it does still work

in com_modules options the adminlangfilter radio in the options

**Comment by brianteeman** [comment]
sorry - double checking it i can see that it only kind of works sometimes

**Comment by brianteeman** [comment]
closed as we have a PR for testing see #19213

**Comment by C-Lodder** [comment]
This PR only addresses the default styling. It doesn't fix the `btn-group-yes-no-maybe-definitely-supposedly` (whatever it is) class
