### ISSUE TITLE
SMTP Mailer - JSON data: HTTP 500 status code. error

### ISSUE THREAD

**Issue by adamrobinson85** [joomla/joomla-cms#19114]
### Steps to reproduce the issue

unable to use SMTP mailer - test returns JSON data: HTTP 500 status code. error

### Expected result

Test should send email as usual. 

### System information (as much as possible)

V 3.8.3

Database Version	5.5.5-10.1.29-MariaDB
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.32
Web Server	Apache
WebServer to PHP Interface	litespeed
Joomla! Version	Joomla! 3.8.3 Stable [ Amani ] 12-December-2017 15:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	

### Additional comments

This has stopped yesterday, have tried with Office 365 and Gmail and mutiple installations of Joomla

**Comment by brianteeman** [comment]
If it just stopped and you didn't change anything them I would check with your hosting provider to see if they made any changes.

**Comment by adamrobinson85** [comment]
I have checked with them and they say nothing has changed. It was working yesterday. I tested one installation on 3.8.3 and one on 3.8.2 Tomorrow Ill do a fresh install on another host just to check.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19114">issues.joomla.org/tracker/joomla-cms/19114</a>.</sub>

**Comment by brianteeman** [comment]
Well nothing in Joomla would just stop working overnight :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19114">issues.joomla.org/tracker/joomla-cms/19114</a>.</sub>

**Comment by Webdongle** [comment]
Did the fail start after an update of any kind ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19114">issues.joomla.org/tracker/joomla-cms/19114</a>.</sub>

**Comment by adamrobinson85** [comment]
Yes its strange why its stopped working, even from a Joomla test email. Ill do a fresh install on another host tonight and test out the issue just to eliminate the host from it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19114">issues.joomla.org/tracker/joomla-cms/19114</a>.</sub>

**Comment by ghost** [comment]
@adamrobinson85 have you test out the issue?

**Comment by adamrobinson85** [comment]
Yes sorry this seemed to be an issue with the webhost and being unable to contact O365. This has now been resolved. Thanks
