### ISSUE TITLE
3.8.3 blank auto popup screen on pages when cache is on

### ISSUE THREAD

**Issue by KoosOverbeeke** [joomla/joomla-cms#19111]
I tried several forums. Nobody seems to know the problem or a solution

Please help

### Steps to reproduce the issue
What happens you can see here: www.outsourcing-help.nl/demand-managers/popup%20blank.JPG

the source code you can see here: www.outsourcing-help.nl/demand-managers/bug.JPG
### Expected result
This blank popup should not be there

### Actual result
If I clear the cache the problem is gone. If I disable cache the problem is gone forever.
The source code after cleaning cache (the problem is gone now) is: https://www.outsourcing-help.nl/demand-managers/after%20closing%20popup.JPG

If I activate cache the problem is back in a couple of houres. If I activate refreshing cache on all pages (with jotcache) the problem is back within minutes. 

### System information (as much as possible)
joomla 3.8.3. 
PHP  5.6.32-1~dotdeb+7.1

I disabled other plugins such as JCE, Too Many Files, Jotcache, auto on page popup. No result. The only thing that seems to work is disable cache.

**Comment by brianteeman** [comment]
do you mean the popup should have content or do you mean there should be no popup

**Comment by KoosOverbeeke** [comment]
Thank you Brian, indeed, there should be no popup.

**Comment by ghost** [comment]
can you  write how you get this PopUp or give the Link to Thread of [forums](https://forum.joomla.org/) you mentioned above?

**Comment by brianteeman** [comment]
From the limited information I would say that the problem is nothing to do with the core of Joomla and is probably this autopop plugin you mention.

**Comment by KoosOverbeeke** [comment]
The popup I use is form Infyways. They looked at the problem and concluded id dit nit come from their popup. How they do come to that conclusion? I don't know.  My frustration is that I cannot see from which plugin the code is!

What I also don't understand is why there is no problem now en why the problem occurs when page are cached. 

If I cache the front page only. nothing happens. 
Also if I cache a page where a popup should appear that has no effect on the front page.  

After more then approximately 30 pages in cache the problem starts.  

The blank popup also appears on other pages. Also on pages where a popup should appear and that works fine  after you close the blank popup. 

If you close the blank popup and refresh the page the blank popup return tight away.

Is this enough information Brian, Franz? 

If it should help you I can enable the cache so you can see it for yourself

**Comment by brianteeman** [comment]
This really should be handled over at the forum https://forum.joomla.org now that we have established that the popup is not coming from the core of joomla

**Comment by KoosOverbeeke** [comment]
Last question! How did you establish that the popup is not coming from the core of joomla?

If I enable the core joomla cache the problem occurs! All plugin's I did disable leaved the problem in place. Only disabling cache removes the problem.

**Comment by Quy** [comment]
@KoosOverbeeke Going by your screenshots, could it be related to issue https://github.com/joomla/joomla-cms/issues/16436 with Squeezebox which is not in the core?

**Comment by KoosOverbeeke** [comment]
Thank you Quy,

Today my problem is solved thanks to Micheal Russell from Australia who really helped me out.

It looks like the problem you refer to. Our problem was caused by an old (2011) and long time not used  plugin.   It was there all the time but then in Joomla 3.8.3 it (plugin popup anywhere) suddenly and mysteriously get triggered and causes the trouble
