### ISSUE TITLE
404 error with SSL installed...

### ISSUE THREAD

**Issue by mikelawrey32** [joomla/joomla-cms#19121]
### Steps to reproduce the issue

Wildcard SSL was installed for my subdomains...however one domain, dallas-tx.puretaxhelp.com shows a 404 error page when adding https:// protocol to URL.

### Expected result

https:// prefix to work with site...and Force SSL enabled on all site pages.

### Actual result

404 error page with https:// prefix

### System information (as much as possible)

J 3.8.3. 

### Additional comments

Tried altering the .htaccess and config files...not sure what other factors are involved that would cause this?

**Comment by rdeutz** [comment]
Doesn't looks like a Joomla! thing, the 404 comes directly from your hostingprovider, seems to be a setup problem

**Comment by mikelawrey32** [comment]
Oh yea, so Ive been through it with my host and they insist it's a Joomla issue.  Because if the SSL wasnt installed correctly I would be getting a "Connection not secure" page instead.  It seems to be something perhaps with the port access?  Not accessing port 443?  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19121">issues.joomla.org/tracker/joomla-cms/19121</a>.</sub>

**Comment by rdeutz** [comment]
But it is not a Joomla 404 error page, so why should it be a Joomla issue?

**Comment by mikelawrey32** [comment]
Valid point, so let's assume it is a hosting configuration issue...any ideas what would be the culprit?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19121">issues.joomla.org/tracker/joomla-cms/19121</a>.</sub>

**Comment by rdeutz** [comment]
I would put a simple index.html (hello world) in the root and try to call this file, just to make sure it is not a php problem

**Comment by mikelawrey32** [comment]
Very good, Ill give that a shot. Thanks

**Comment by rdeutz** [comment]
Better to asked for further support in the forum, seems to me not a joomla bug
