### ISSUE TITLE
Warning: count() for Contact Categories

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#19125]
### Steps to reproduce the issue
Install `Test English (GB) Sample Data`.
On frontend, click `Contact Categories`.

### Actual result
Warning: count(): Parameter must be an array or an object that implements Countable in \components\com_contact\models\categories.php on line 96

### System information (as much as possible)
PHP 7.2.0

**Comment by brianteeman** [comment]
Closed see #19135
