### ISSUE TITLE
'Link CSS Style' label incorrect

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#19122]
### Steps to reproduce the issue
Navigate to the **Link Type** tab of a menu item. 

The **Link CSS Style** field label  should be **Link Class**. The field adds a class to the menu item link, the current label implies it is adding inline CSS.

**Comment by brianteeman** [comment]
Links CSS Class ? perhaps

**Comment by ciar4n** [comment]
IMO still not correct as a class can also be used for JS. It is also not consistent with other class fields (eg. Module Class Suffix, Header Class).

**Comment by brianteeman** [comment]
> IMO still not correct as a class can also be used for JS. 

thats exactly why i suggested adding the word CSS

**Comment by ciar4n** [comment]
Why add 'CSS' when it can also be used for JS?

**Comment by brianteeman** [comment]
ah - i thought you could only reference a css class there

**Comment by ciar4n** [comment]
In most cases I suspect it is used with CSS but it can potentially have a JS use. My 2 cents would be to change it to simply `Link Class` but happy enough with either.

**Comment by brianteeman** [comment]
For consistency then I guess Link Class is fine

**Comment by brianteeman** [comment]
closed see #19143
