### ISSUE TITLE
Warning: count() in News Feed Categories

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#19126]
### Steps to reproduce the issue
Install `Test English (GB) Sample Data`.
On frontend, click `News Feed Categories`.

### Actual result
`Warning: count(): Parameter must be an array or an object that implements Countable in \components\com_newsfeeds\models\categories.php on line 98`

### System information (as much as possible)
PHP 7.2.0

**Comment by brianteeman** [comment]
Closed see #19135
