### ISSUE TITLE
[4.0] Problem on uploading a image to media manager.

### ISSUE THREAD

**Issue by anuragteapot** [joomla/joomla-cms#19132]
### Steps to reproduce the issue

Step 1.Upload an image to the media manager.
Step 2.Then, delete it.
Step 3.Then, without refreshing page try to upload the same image. 

### Expected result

Image uploaded.

### Actual result

Image not uploaded.

### System information (as much as possible)
 
Joomla! 4.0.0-dev

**Comment by ghost** [comment]
can you please report on https://github.com/joomla-projects/media-manager-improvement and close this Issue here?

**Comment by anuragteapot** [comment]
Ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19132">issues.joomla.org/tracker/joomla-cms/19132</a>.</sub>
