### ISSUE TITLE
[4.0] Directory path is showing in media manager.

### ISSUE THREAD

**Issue by anuragteapot** [joomla/joomla-cms#19133]
### Steps to reproduce the issue
Open media manager.

### Expected result
![screen shot 2017-12-22 at 11 48 14](https://issues.joomla.org/uploads/1/f68834e6a9b200ca209ac33450ae2bc4.png)

### Actual result
![screen shot 2017-12-22 at 11 47 05](https://issues.joomla.org/uploads/1/ca431d19795801c858da5a9ab24c3973.png)

### System information (as much as possible)

Joomla! 4.0.0-dev

**Comment by ghost** [comment]
can you please report on https://github.com/joomla-projects/media-manager-improvement and close this Issue here?

**Comment by anuragteapot** [comment]
Ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19133">issues.joomla.org/tracker/joomla-cms/19133</a>.</sub>
