### ISSUE TITLE
?amp; in demos' help urls

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#19149]
### Steps to reproduce the issue
Install `Test English (GB) Sample Data`.
Go to front end.
Under `All Modules`, click `Smart Search`.
Click `Help` in the article.

### Expected result
`https://help.joomla.org/proxy/index.php?keyref=Help31:Extensions_Module_Manager_Smart_Search`

### Actual result
`https://help.joomla.org/proxy/index.php?amp;keyref=Help31:Extensions_Module_Manager_Smart_Search`

### Additional comments
nightly staging

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19149">issues.joomla.org/tracker/joomla-cms/19149</a>.</sub>

**Comment by brianteeman** [comment]
The test sample data is never distributed in an actual release. So if you want to fix it then fine but I wouldnt waste any time on it

**Comment by Quy** [comment]
See #19181
