### ISSUE TITLE
Template manager ignors Permissions

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#19144]
### Steps to reproduce the issue
Create a new user and set the user group to Administrator
With another browser login to admin with the new user
Navigate to Extensions >>> Templates >>> Templates ... click 'Protostar Details and Files'

### Expected result
'Editor' 'Create Overrides' 'Template Description' tabs should be shown.  And the template files should be available for edit.

### Actual result
The template profile is displayed

**Comment by brianteeman** [comment]
Only a super user can edit a template

**Comment by ghost** [comment]
closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19144">issues.joomla.org/tracker/joomla-cms/19144</a>.</sub>
