### ISSUE TITLE
Hamburger Menu doesn't apply Custom Color

### ISSUE THREAD

**Issue by CeleritasCognito** [joomla/joomla-cms#19172]
### Steps to reproduce the issue
1. Open Joomla Admin on Mobile
2. Set custom Colors for the ISIS Theme
3. Look at the Hamburger Menu

### Expected result
New Colors should be Applied

### Actual result
New Colors are not applied
<img width="637" alt="bildschirmfoto 2017-12-26 um 15 27 03" src="https://user-images.githubusercontent.com/18743976/34358614-88d694e6-ea51-11e7-9c78-060be648d835.png">

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19172">issues.joomla.org/tracker/joomla-cms/19172</a>.</sub>

**Comment by brianteeman** [comment]
Which setting are you changing? I dont see a setting that would suggest it would change the colour of the button or are you referring to the colour of the menu items displayed when the hamburger is expanded

**Comment by ghost** [comment]
@brianteeman i test "Nav Bar Colour" as i thought thats also for Button.

**Comment by tonypartridge** [comment]
Hamburger should probably have a transparent background

**Comment by brianteeman** [comment]
The color of the navbar is changing - it is the color of the button that is not

**Comment by Quy** [comment]
The code to update is here. When selecting a color, there is a color preview (the color and a lighter color). How to determine the lighter color that will be used when the icon is pressed?

https://github.com/joomla/joomla-cms/blob/05fd1d9f12ea62960f1ea921663fa4877994e538/administrator/templates/isis/index.php#L126

**Comment by brianteeman** [comment]
my understanding of the reported issue is different
you can change the navbar color - the user seems to be suggesting the hamburger button will change colour. I think that this is simply a user misunderstanding

**Comment by Quy** [comment]
Then what is the expected behavior of the button...to match or not match the navbar color?

**Comment by brianteeman** [comment]
I dont see any reason why it should match the navbar color

**Comment by Quy** [comment]
I agree then it is a non issue :wink:

**Comment by tonypartridge** [comment]
Easy solution, add another colour config.

**Comment by brianteeman** [comment]
after 5 years of this template with this being the first comment adding another option just isnt worth the effort. I am closing this.
