### ISSUE TITLE
[3.8.3] Request: Remove Post installation Messages from new versions

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#19185]
### Steps to reproduce the issue
Download a fresh install package from downloads.joomla.org

![grafik](https://user-images.githubusercontent.com/828371/34384727-58ff012c-eb1e-11e7-965b-23f489ec4d02.png)

### Expected result
Since it's a fresh install it means for me it's a fresh start. Post Installation messages regarding older Versions should only come when I upgrade Joomla from an older Version to a new one that is affected by that change.

### Actual result
Joomla is showing old postinstall Messages for Joomla 3.2 and 3.5 and I always have to dismiss the stuff.  It's quite annoying to dismiss that all the time.

**Comment by brianteeman** [comment]
I dont agree. These are important messages for all installs.
Security
Statistics
Welcome

There are three other messages that could be displayed and they are only displayed in certain specific upgrades

**Comment by coolcat-creations** [comment]
Then it would be a completely different page, that is not bound to changes in a specific version but like a docs page for the first steps or something like that.

**Comment by brianteeman** [comment]
If you want to submit a PR for that then go ahead - personally I dont see the need

**Comment by coolcat-creations** [comment]
Maybe this whole topic should be discussed first. What would be an important After Install Message. Is it something that makes an impact for me when i upgrade from a lower version? Then only After Installation Messages should be shown that affect me because of that changes. If it's a "Welcome Page" with the most important things, then we could extend it and change the layout and list all ressources (Volunteers Portal, Docs, Ressources Directory, and and and).

**Comment by alikon** [comment]
please folks,  help me with my bad english:
`install` is not equal to `upgrade` nor is equal to `update` 
 :stuck_out_tongue_winking_eye:
please clarify

**Comment by brianteeman** [comment]
install = new
upgrade/update = change from an older version

**Comment by alikon** [comment]
my binary mind is now happy  :smile: 
....jokes apart.....
so `postinstall` should be `postupgrade` 
or i'm still too naive ?

**Comment by coolcat-creations** [comment]
From what i understand, the messages show what significant and important changed in a certain version. So i would agree that this a post upgrade messages. They are shown always. I leave it open to a discussion if the way it's done now is good or not. In my opinion it should show up after the ugrade only and not after each install and force the user to go somewhere and click everything away.

**Comment by Quy** [comment]
This PR #19958 would be a good compromise.

**Comment by brianteeman** [comment]
Closing this
