### ISSUE TITLE
3.8.3, cant choose any category on menu type (category or list blog)

### ISSUE THREAD

**Issue by chidalgom1503** [joomla/joomla-cms#19191]
### Steps to reproduce the issue
Create a category blog (or list) menu item type.

### Expected result
Able to choose which category to display (in blog or list layout)

### Actual result
The modal which handle the category listing display a "content > categories page", which wont let to choose any category in it.
Only works on "create" category if the category field is empty.

### System information (as much as possible)
Joomla 3.8.3 (updated from 3.8.0)
PHP Version  7.0.25
Joomla! Platform Version 13.1.0 Stable

### Additional comments

![screenshot](https://user-images.githubusercontent.com/19676072/34397766-aed14f40-eb57-11e7-9062-5328b07f8ee3.png)

**Comment by Quy** [comment]
Click on a category title to select it.

**Comment by Quy** [comment]
Can you click on a category title to select it? On my end, I don't have a checkbox next to each category and the 4 columns before Access.

**Comment by chidalgom1503** [comment]
if i click on a category title it takes me to the Articles: Edit Category (inside the same modal), if click the checkbox nothing happens because there is nothing more to set after that, just "close".

Probably loads the wrong page in modal.

![screenshot](https://user-images.githubusercontent.com/19676072/34400654-507c06b8-eb72-11e7-974b-1448a330b547.png)

**Comment by Quy** [comment]
As you can see in my screenshot, your screenshot differs with the checkbox next to the category title and 4 columns before the Access column. Do you have a plugin installed that may have affected your categories modal?

![categories-modal](https://user-images.githubusercontent.com/368084/34400767-77c05ca2-eb49-11e7-8b2e-109714b2cc7b.gif)

**Comment by chidalgom1503** [comment]
This is a clean installation, 3.8.0 updated to 3.8.3.

I think is loading a wrong page inside the modal?

**Comment by Quy** [comment]
I even installed v3.8.0 and upgraded to v3.8.3. No issues with the categories modal.

**Comment by ghost** [comment]
@chidalgom1503 Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
