### ISSUE TITLE
Show category title in the browser instead of the menu title.

### ISSUE THREAD

**Issue by segundochinguel** [joomla/joomla-cms#19192]
### Steps to reproduce the issue
I have a main menu with the title "Categories" that lists all the categories, when accessing the menu, the page title in the browser shows "Categories" and if I click on any category the browser title does not change.

### Expected result
When I access a category of the list, the title of the category should be displayed in the browser.

### Actual result
When I access a category of the list it continues to show the menu title instead of the title of the category that I have selected .

### System information (as much as possible)
Joomla 3.8.3 

### Additional comments
I read of a similar problem with tags is the same case but with categories.#12158

**Comment by infograf768** [comment]
Do you mean getting the title of the category displayed as in screenshot below (here Fruit Shop Site)?
![screen shot 2017-12-28 at 10 06 35](https://user-images.githubusercontent.com/869724/34405997-e5b7c084-ebb6-11e7-8377-64a2a414d103.png)

**Comment by infograf768** [comment]
@segundochinguel
Please test https://github.com/joomla/joomla-cms/pull/19195

**Comment by ghost** [comment]
closed as having Pull Request #19195

**Comment by segundochinguel** [comment]
No, not as page heading, but as page title, which goes inside <title> </ title> in html code.

**Comment by infograf768** [comment]
hmm...

**Comment by infograf768** [comment]
Issue reopened.

**Comment by infograf768** [comment]
@segundochinguel 

Please look at https://github.com/joomla/joomla-cms/pull/19195 I added there an animated gif so you see the results

@franz-wohlkoenig 
Let's wait before closing this

**Comment by segundochinguel** [comment]
Excellent, it worked as expected. @infograf768 Thank you very very much!

**Comment by infograf768** [comment]
Closing for real now. 😄
