### ISSUE TITLE
Do we use tags in users and banners?

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#19208]
This is just a question rather than an issue. I see there are tags related code in com_users can com_banners code base. However, taking a quick look at these components, I don't see where tags is used

So the question is do we use tags in these components or not? If not, I think we should remove code related to tags in these components

**Comment by brianteeman** [comment]
I cant see any use myself

**Comment by joomdonation** [comment]
Thanks for confirming Brian. I'm going to make a PR to remove tags related code in these component
