### ISSUE TITLE
[4.0] Error in High Security Password of users Joomla

### ISSUE THREAD

**Issue by carlosjacomi** [joomla/joomla-cms#19204]
### Steps to reproduce the issue
Install Joomla using a user with a secure  password like "Admin123456+"
![image](https://user-images.githubusercontent.com/30361724/34423376-966cbf38-ebe9-11e7-8d06-8bf045844f87.png)

### Expected result
The user can enter into backend or frontend structure

### Actual result
The user can't login
![image](https://user-images.githubusercontent.com/30361724/34423417-d2e71f30-ebe9-11e7-8723-fb76c20cb96f.png)

### System information (as much as possible)
Joomla 4 Alpha 2

### Additional comments
1- If I install Joomla with a password like "123", I can login without issues
2- If I after of login with a easy password change the password for  "Admin123456+" then I can login without issues

**Comment by dgrammatiko** [comment]
`Admin123456` is a secure password? TIL!!!

**Comment by carlosjacomi** [comment]
that was a example xD for explain it!. the structure of a  password that isn't work is Mayus Letter(s)+Normal Letter(s)+ Number(s)+ Special Character(s)

**Comment by dgrammatiko** [comment]
This needs some investigation then. Can you narrow this to what chars break the password? (eg is it something from !@#$%^^&*_-+ )

**Comment by carlosjacomi** [comment]
Well i'm using a password in my website that works good with  password like the example  "Admin123456+" in the lastest version 3.8.3

**Comment by dgrammatiko** [comment]
Actually this needs do be debugged, I mean it can be js or the php filtering.
dolphin works like a charm for me : https://github.com/danielmiessler/SecLists/pull/155 :D

**Comment by anuragteapot** [comment]
Please change Build to <code>4.0-dev</code><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19204">issues.joomla.org/tracker/joomla-cms/19204</a>.</sub>

**Comment by ghost** [comment]
@Anu1601CS done.

**Comment by chetanmadaan** [comment]
I am able to re-product the same in the Joomla backend user manager as well where I use the password **admin** and it as **strong** and **accepted**.

![image](https://user-images.githubusercontent.com/3968575/34447083-b6dc9566-ecae-11e7-8a5b-3a55ddf06986.png)

**Comment by Quy** [comment]
Cannot replicate with password `Admin123456+`

**Comment by brianteeman** [comment]
Probably fixed with #20414 ?

**Comment by Quy** [comment]
Confirmed fix with #20414. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19204">issues.joomla.org/tracker/joomla-cms/19204</a>.</sub>
