### ISSUE TITLE
[4.0] double arrows (again)

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#19219]
### Steps to reproduce the issue

4.0-dev
<img width="969" alt="screen shot 2017-12-29 at 18 01 15" src="https://user-images.githubusercontent.com/400092/34443917-51c460f0-ecc2-11e7-8e89-834c6ab5e533.png">

**Comment by ghost** [comment]
Issue confirmed.

![bildschirmfoto 2017-12-29 um 19 10 07](https://user-images.githubusercontent.com/8235763/34444095-f3928c6e-eccb-11e7-885d-26aff8e082e7.jpg)

### System information
4.0.0-dev
Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19219">issues.joomla.org/tracker/joomla-cms/19219</a>.</sub>

**Comment by C-Lodder** [comment]
Reason is because the `postcss` task isn't prefixing the `appearance` attribute for Cassiopeia.

Should be:

```
.custom-select {
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
}
```

but instead it's only compiling to:

```
.custom-select {
  appearance: none;
}
```

working fine on the backend template

@ciar4n you know anything about this? Can't seem to see anything out the ordinary

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/19243
