### ISSUE TITLE
Joomla maybe Shows wrong message after update,if you disconnected from Internet in middle of it

### ISSUE THREAD

**Issue by mostafa-norouzi** [joomla/joomla-cms#19211]
Hello

I think Joomla Should check integrity of all files after any updates! because if you close "update progress page" suddenly (because of Internet connection problem for example) maybe **CMS shows wrong message**!

I made a video to explain it : https://youtu.be/0kyH27jtjZw
in this video I close browser (Firefox) manually to simulate the situation.

thank you.

**Comment by tonypartridge** [comment]
Hello,

The command was sent to the server and the server should finish executing this command I believe, we don’t handle the update with browser side verifications if I remember correctly @mbabker can you confirm?

You were upgrading from Joomla! 3.8.1 -> 3.8.3 so you would have only received a patch package and not a full CMS reinstall like you did with your Joomla! Update reinstall core files.

**Comment by mostafa-norouzi** [comment]
So you mean if I click on start update and close the browser immediately, when I come back to admin, I will face with updated site? 

**Have you tested this scenario ever?**

**Comment by ghost** [comment]
any Comment @tonypartridge?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19211">issues.joomla.org/tracker/joomla-cms/19211</a>.</sub>

**Comment by mostafa-norouzi** [comment]
I can see that issue closed with no definite result!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19211">issues.joomla.org/tracker/joomla-cms/19211</a>.</sub>

**Comment by zero-24** [comment]
Integety and other health checks are on the roadmap for 4.2 as published a few days ago: https://www.joomla.org/announcements/release-news/5819-the-day-after-joomla-4-0-planning-the-future.html

**Comment by zero-24** [comment]
On that issue here. Aborting the update proceess can lead to broken sites. When the site still works but just has sone errors you can reinstall the core files.

I'm not sure how an "update proceess aborted" issue can be handled. It is similiar with an windows update where you unplug the PC in the upgrade phase. With our acutual setup it is not easy to cover such cases.
