### ISSUE TITLE
installer Undefined property: stdClass::$class

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#19214]
### Steps to reproduce the issue

install from 8256b0f8c2141e1014d6b58d3ad048b0853f0896

### Expected result

no errors

### Actual result

<img width="1213" alt="screen shot 2017-12-29 at 16 41 32" src="https://user-images.githubusercontent.com/400092/34442004-2d0c5fde-ecb7-11e7-998a-5d5e469067ff.png">

**Comment by Quy** [comment]
Fixed #19164<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19214">issues.joomla.org/tracker/joomla-cms/19214</a>.</sub>
