### ISSUE TITLE
[4.0] icons not inline with login box fields on frontend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#19215]
### Steps to reproduce the issue

install from 8256b0f8c2141e1014d6b58d3ad048b0853f0896

### Expected result

icons inline with login box fields on frontend

### Actual result

<img width="299" alt="screen shot 2017-12-29 at 16 48 48" src="https://user-images.githubusercontent.com/400092/34442172-44c8f26c-ecb8-11e7-98e2-fa176e0641c0.png">

**Comment by ghost** [comment]
Can't confirm:
![bildschirmfoto 2017-12-29 um 17 59 44](https://user-images.githubusercontent.com/8235763/34442405-32b733a4-ecc2-11e7-96b0-aa3da83450e7.jpg)
### System information
4.0.0-dev
Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19215">issues.joomla.org/tracker/joomla-cms/19215</a>.</sub>

**Comment by C-Lodder** [comment]
Already fixed: https://github.com/joomla/joomla-cms/pull/19209

**Comment by ghost** [comment]
Can confirm on 4.0-dev Issue found by @PhilETaylor.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19215">issues.joomla.org/tracker/joomla-cms/19215</a>.</sub>

**Comment by brianteeman** [comment]
Why did you re-open it. This has been fixed by a pending PR #19209

**Comment by C-Lodder** [comment]
Reopen please

**Comment by brianteeman** [comment]
Reopened as requested

**Comment by brianteeman** [comment]
Closed as resolved with https://github.com/joomla/joomla-cms/pull/20104
