### ISSUE TITLE
[4.0] Email to friend broken

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#19221]
### Steps to reproduce the issue
4.0-dev install
install sample data
View article on frontend
attempt to send email to friend
complete form as:

<img width="659" alt="screen shot 2017-12-29 at 18 07 30" src="https://user-images.githubusercontent.com/400092/34444045-2a286734-ecc3-11e7-84c6-bf4a4a50a42c.png">

Click Send

### Expected result

Mail is sent and feedback provided

### Actual result

page reloads - no email is sent - no feedback provided

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/19393

@franz-wohlkoenig

**Comment by ghost** [comment]
no Decision was made at #19393 so i let it open.

**Comment by brianteeman** [comment]
Closed as Phil reported it again in #21737 and it was fixed in #21745
