### ISSUE TITLE
[4.0] Site Settings on frontend broken

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#19222]
### Steps to reproduce the issue

4.0-dev install
login to front end as super admin
click site settings
click save

### Expected result

saved

### Actual result

<img width="1272" alt="screen shot 2017-12-29 at 18 10 39" src="https://user-images.githubusercontent.com/400092/34444100-9775efe6-ecc3-11e7-9a01-63979bb49690.png">

**Comment by ghost** [comment]
Issue confirmed.
### System information
4.0.0-dev
Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19222">issues.joomla.org/tracker/joomla-cms/19222</a>.</sub>

**Comment by brianteeman** [comment]
The error message is 
> 0 Class 'Joomla\Component\Config\Administrator\Controller\Application' not found

**Comment by Quy** [comment]
Related to #20484. however, this specific error is no longer reproducible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19222">issues.joomla.org/tracker/joomla-cms/19222</a>.</sub>
