### ISSUE TITLE
[4.0] Template Settings broken on frontend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#19223]
### Steps to reproduce the issue

4.0-dev install
login to frontend as super admin
click Template Settings 
Click Save

### Expected result

Saved

### Actual result

<img width="1291" alt="screen shot 2017-12-29 at 18 13 19" src="https://user-images.githubusercontent.com/400092/34444148-f60b3e9e-ecc3-11e7-9044-349468c61296.png">

**Comment by brianteeman** [comment]
Requires a similar fix to #18679

**Comment by Quy** [comment]
Duplicate #20356
