### ISSUE TITLE
[4.0] Versions broken on frontend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#19220]
### Steps to reproduce the issue

4.0-dev install
install sample data
edit one on the frontend
click versions button

### Expected result

modal with versions

### Actual result

`[Fri Dec 29 18:02:14 2017] 127.0.0.1:65513 [500]: /index.php/index.php?option=com_contenthistory&view=history&layout=modal&tmpl=component&field=jform_contenthistory&item_id=1&type_id=1&type_alias=com_content.article&4b3fc97cd85b077325bbf9e3c606f92f=1`

page reloads

This is because in HTML5 the default action for a button is to SUBMIT the form, you need `type="button"` attribute to stop that happening...

Note also that the button has a `jQuery('#versionsModal').modal('show')` onclick action - I thought the frontend was getting rid of all jQuery in favor of "JS"?

However after adding that, the modal now correctly shows - but the iframe inside it incorrectly loads:

<img width="1592" alt="screen shot 2017-12-29 at 18 05 18" src="https://user-images.githubusercontent.com/400092/34444005-d7fb40da-ecc2-11e7-9053-3ec2cbb41ee1.png">

**Comment by ghost** [comment]
Issue confirmed, on following Setting Modal open an close at same Time:
### System information
4.0.0-dev
Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19220">issues.joomla.org/tracker/joomla-cms/19220</a>.</sub>

**Comment by brianteeman** [comment]
PR incoming for the button
The other error is
> 0 Invalid controller class: Joomla\Component\Contenthistory\Site\Controller\DisplayController

**Comment by mbabker** [comment]
> 0 Invalid controller class: Joomla\Component\Contenthistory\Site\Controller\DisplayController

See https://github.com/joomla/joomla-cms/pull/18679

**Comment by PhilETaylor** [comment]
#18679 would not fix the popup button - that needs @brianteeman's upcoming PR :)

**Comment by brianteeman** [comment]
I just submitted that here #19225

**Comment by mbabker** [comment]
That's why I quoted the error message 😉

**Comment by PhilETaylor** [comment]
ZZZzzzz.....
