### ISSUE TITLE
[4.0] Change sidebar-left/right to sidebar-a/b

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#19240]
Using directional naming conventions for the sidebar isn't the best approach as it may cause confusion with RTL. We should use `sidebar-a` and `sidebar-b` or the module positions instead.

**Comment by brianteeman** [comment]
Left is still left - right is still right - no matter the language. We do not mirror positions when the language direction changes so sidebar-left is perfectly ok and much more meaningful than sidebar-a

**Comment by C-Lodder** [comment]
fair point

**Comment by brianteeman** [comment]
no problem - its a common mistake of some templates that switching the language direction means to mirror the layout
