### ISSUE TITLE
Very slow website with upgrade to joomla 3.8.x and NO SUPPORT AT ALL SINCE 5 MONTH

### ISSUE THREAD

**Issue by Folamour** [joomla/joomla-cms#19258]
### Steps to reproduce the issue

publish 14k article, update from 3.7.5 to 3.8.x

### Expected result

Page load went from 4.5 sec to 9 sec.

### System information (as much as possible)

PHP exécuté sur | Linux od-2ffe84 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.39-1+deb8u1~bpo70+1 (2017-02-24) x86_64
-- | --
Version de la base de données | 5.6.33-log
Interclassement de la base de données | utf8_general_ci
Collation de la connexion à la base de données | utf8mb4_general_ci
Version de PHP | 5.6.28
Serveur web | Apache
Serveur web pour interface PHP | fpm-fcgi
Version de Joomla | Joomla! 3.7.5 Stable [ Amani ] 14-August-2017 12:09 GMT
Version de la plateforme Joomla! | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Navigateur | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

### Additional comments

Upgrading from Joomla 3.7.5 to Joomla 3.8.x make our page time load went from 4.5sec up to 9sec. our only particularity is to have 14.000 articles and 25 categories,

I have put 5 thread on Joomla.org since 5 MONTH ! and no body take care, where the support ????

On my previous resquest to Dev you closed my thread and asked me me to put another thread on Joomla.org that done and not update since 10 days....

https://forum.joomla.org/viewtopic.php?p=3507438&sid=5481121974e7f40ced529b55b1c20ec1#p3507438

Every body send the ball to another that's ridiculous, and you said joomla is a professional CMS ?

very slow website after upgrading to jooma 3.8.0
https://forum.joomla.org/viewtopic.php?f=709&t=954841

Joomla 3.8.1 site slower 10 sec instead 4 sec pageload
https://forum.joomla.org/viewtopic.php?f=709&t=955611

very slow website since release of Jooma 3.8.0
https://forum.joomla.org/viewtopic.php?p=3506909#p3506909

Very slow website when upgrading to Joomla 3.8.x
https://forum.joomla.org/viewtopic.php?p=3507438&sid=5481121974e7f40ced529b55b1c20ec1#p3507438

WE NEED SUPPORT or we will be vulnerable to Hacker, we are one of the most massive Joomla site.

Thanks in advance,

Folamour.

**Comment by brianteeman** [comment]
This still is not the correct place to post.

**Comment by Folamour** [comment]
Brian i've pust 5 post on Joomla.org and still have no answer ? we need help

**Comment by brianteeman** [comment]
What makes you feel that you are entitled to support? Any support provided on the forum is, like Joomla, provided by volunteers who are trying to help. If that is not good enough for you then you should contact someone directly from the resource directory who may be able to provide the support you require.

**Comment by Folamour** [comment]
Ok so 5 month is not enougth wait ? if no body want to take care i just have to wait until i'm hacked ? Joomla.org asked me to ask on this forum, this forum ask me to put a thread on joomla.org....

the bug we are facing indicate that joomla is NOT a professional CMS, we use it since 8 years, and he seem to have LIMIT.

**Comment by ggppdk** [comment]
@Folamour 
Enable Joomla DEBUG and compare the 2 runs (old and new website)

**Comment by ggppdk** [comment]
To get accurate results it is best to test in your duplicate / testing copy of your website (e.g. locally)

**Comment by Folamour** [comment]
Thanks hhppdk, but its a huge work because i have to wait that my host does the backup of the site, so i cannot post new article during 5 days, then i can try the upgrade, and roll back to 3.7.5. I will do the job according to your request and put the result on joomla.org on performance thread. Will also try to duplicate on my Xampp copy.

Thanks you for this bit of hope, we are really in a bad position for the future.

**Comment by mbabker** [comment]
Ignoring other comments, the Joomla project itself only provides support for the `*.joomla.org` website network, therefore we do not directly provide support to end users.

The community support forum is a volunteer network.  Users go there with issues and volunteers will assist to the best of their ability.  There is not a support staff on that platform, or for that matter any part of the Joomla project.

This GitHub repository is strictly for dealing with core bugs as it relates to the Joomla application.  A performance issue is a core bug if it can be reproduced.  An issue opened that states "I upgraded my site and now it is slow" is not going to be triaged as a core bug, sorry.

If you are in need of direct support from a service provider, you can utilize the [Resources Directory](https://resources.joomla.org/en/) to find someone to assist you.

**Comment by Folamour** [comment]
we earn no money with our website we cannot hire a service provider. this problem can be reproduced with a site with 14k article.

**Comment by ggppdk** [comment]
@Folamour 
I have answered you via an email

**Comment by Folamour** [comment]
thanks ggppdk i've replied to you too, keep you updated asap

**Comment by Folamour** [comment]
hi ggppdk sended you information no reply from your side,

**Comment by Quy** [comment]
This PR #19261 may help. To install PR with Patch Tester, please go here: https://docs.joomla.org/Testing_Joomla!_patches

**Comment by csthomas** [comment]
This PR #19284 should help:)

**Comment by Folamour** [comment]
hi all, i'm working with a long time friend Yiannis Joomla stack dev, we have implemented php7 and upgraded to 3.8.3 (the speed issue remain) we will install PR 19261 and PR 19284 on the site tonite, you can saw the speed issue on live on https://www.crashdebug.fr beware we use jot cache so you need to find a page or a category who are not in cache (use left menu), i will keep you updated

**Comment by Folamour** [comment]
Yiannis seem busy so I update the thread he have applied PR 19261 and PR 19284 pagetime load went from 4.5sec in joomla 3.7.5 to 3.5 sec in Joomla 3.8.3 (9 sec without PR), and start display page is 2.4 sec, for user Pagespeed load is 1 sec !!!!!!!!!! so its a wonderdull success !!!!!, I wand to sincerelly thanks Csthomas for is fantastic work ! and of course Georgios (ggppdk) who offer me is help, and all the Joomla devs, if I can exprim myself on the internet its because I discovered Joomla 8 year ago, I want to thank you all, you have to know that there is a lot of people using your code, and you make our life better, joomla 3.8.4 update will be awesome for user, just take a look : https://www.crashdebug,fr navigate througth the site and found a page not in cache (using left menu, and navigation bar at the bottom) they are displayed quasi instantly, you made it guys !!!!! Joomla is now as fast as wordpress with 14k article !!!!

Thanks,

Guillaume
