### ISSUE TITLE
From Joomla 3.4.0 to 3.8.3

### ISSUE THREAD

**Issue by nanilm7** [joomla/joomla-cms#19259]
### System information (as much as possible)

Database Version | 5.6.37
Database Collation | latin1_spanish_ci
PHP Version | 5.6.32
Web Server | Apache
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 3.4.0 Stable [ Ember ] 24-February-2015 23:00 GMT

### Additional comments
Hello,
I  would like to update my web Joomla from 3.4.0 to 3.8.3.
Would you please tell if I'll have problems.

Thanks

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
