### ISSUE TITLE
[4.0] Installer strips database password with ampersand

### ISSUE THREAD

**Issue by caru80** [joomla/joomla-cms#19251]
### Steps to reproduce the issue

Perform a clean install. In step 3 enter a database user password with an ampersand like: ab&cdefg

### Expected result

The password should get stored.

### Actual result

The password stored in configuration.php has been stripped from the ampersand to the end. 

### System information (as much as possible)

super@webserver ~ $ uname -a
Linux webserver 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

super@webserver ~ $ apache2 -v
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-09-18T15:09:02

super@webserver ~ $ mysql --version
mysql  Ver 15.1 Distrib 10.0.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

super@webserver ~ $ php -i | grep mysqli
/etc/php/7.1/cli/conf.d/20-mysqli.ini,
mysqli
mysqli.allow_local_infile => On => On
mysqli.allow_persistent => On => On
mysqli.default_host => no value => no value
mysqli.default_port => 3306 => 3306
mysqli.default_pw => no value => no value
mysqli.default_socket => no value => no value
mysqli.default_user => no value => no value
mysqli.max_links => Unlimited => Unlimited
mysqli.max_persistent => Unlimited => Unlimited
mysqli.reconnect => Off => Off
mysqli.rollback_on_cached_plink => Off => Off
API Extensions => mysqli,pdo_mysql

super@webserver ~ $ php --version
PHP 7.1.12-3+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Dec 14 2017 15:37:13) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.12-3+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by ghost** [comment]
can you please look at #19204 if this is a duplicated Report?

**Comment by brianteeman** [comment]
@franz-wohlkoenig its a different issue as this is the database password not the joomla password

**Comment by caru80** [comment]
Both issues seem to be connected. A Joomla user password with an ampersand also gets stripped. If I enter a "+" in the Db user or joomla user password field, the "+" is replaced with an empty space.

**Comment by anuragteapot** [comment]
@franz-wohlkoenig here also change build to <code>4.0-dev</code> Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19251">issues.joomla.org/tracker/joomla-cms/19251</a>.</sub>

**Comment by ghost** [comment]
@Anu1601CS done.

**Comment by SharkyKZ** [comment]
Fixed with #20414.

**Comment by ghost** [comment]
closed as stated above.

Thanks for Hint @SharkyKZ 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19251">issues.joomla.org/tracker/joomla-cms/19251</a>.</sub>
