### ISSUE TITLE
[4.0] [Cassiopeia] Move more code to custom modules

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#19257]
### Steps to reproduce the issue

The template's index.php should have minimal HTML markup, so we need to start moving some elements to custom modules:

- [ ] Header canvas/svg
- [ ] Footer (back to top)

**Comment by anuragteapot** [comment]
@C-Lodder  please change build to 4.0 dev<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19257">issues.joomla.org/tracker/joomla-cms/19257</a>.</sub>

**Comment by ghost** [comment]
@Anu1601CS done.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19257">issues.joomla.org/tracker/joomla-cms/19257</a>.</sub>
