### ISSUE TITLE
[4.0] Not possible to select database type !

### ISSUE THREAD

**Issue by rbuelund** [joomla/joomla-cms#19264]
### Steps to reproduce the issue
Trying to install Alpha 2 of Joomla 4 on a server mySQL not being localhost. Try to select database type.

### Expected result
Possibility to select database type

### Actual result
Not possible to select any database type. Installation NOT poissible

### System information (as much as possible)
PHP 7.1
5.5.52-MariaDB
mySQL not localhost - Serverversion: 5.7.20-18 - Percona Server (GPL), Release 18, Revision 7ce54a6deef

**Comment by ghost** [comment]
closed as duplicate Report #18660<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19264">issues.joomla.org/tracker/joomla-cms/19264</a>.</sub>
