### ISSUE TITLE
[4.0] Cannot save Articles created on the frontend. Error: Save failed with the following error: Field 'language' doesn't have a default value

### ISSUE THREAD

**Issue by bayareajenn** [joomla/joomla-cms#19260]
### Steps to reproduce the issue
1. Install J4 with Blog Sample Data
2. Add a Menu Item Type: **Create Article** to the Main Menu Blog Menu with Access of **Registered**. 
3. Select **Blog as the Category in the Options** Tab for that Menu Item.
4. Go to the frontend and login (as any UG. I did it as a Super User.)
5. Click the new Menu Item you just created and add a Title and a bit of text if desired.
6. Save it.

### Expected result
That the article would save.

### Actual result
Error: Save failed with the following error: Field 'language' doesn't have a default value and the article will not save.

Funny thing is that no where in the Create Article tabs is there a language field to select a language from.

### System information (as much as possible)
PHP 7.0.17
MySQLi 5.6.37
Caching Disabled
Gzip Disabled
Users 1
Articles 6

The site is hosted at Rochen.

### Additional comments
Can anyone else duplicate this? I saw an issue with this same error reported at https://github.com/joomla/joomla-cms/issues/17132 if that helps at all.

**Comment by ghost** [comment]
Issue confirmed.
![bildschirmfoto 2018-01-02 um 20 37 54](https://user-images.githubusercontent.com/8235763/34497201-db392932-effc-11e7-84b0-55b4ee639086.jpg)
### System information
4.0-dev
Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19260">issues.joomla.org/tracker/joomla-cms/19260</a>.</sub>

**Comment by brianteeman** [comment]
Sounds like my problem - I will take a look at this soon

**Comment by bayareajenn** [comment]
Thanks @franz-wohlkoenig and @brianteeman

**Comment by brianteeman** [comment]
The problem is that the frontend edit form doesnt use the global edit layout - grrr

**Comment by bayareajenn** [comment]
Ah, bummer. The good thing is that you knew to even look at that. I only knew there was a problem. I had no idea how to sort it. Thank you so much for looking. Let me know if there's something I'm equipped to help with and I will.

**Comment by ghost** [comment]
@bayareajenn test Pull Requests are welcome ;:

**Comment by bayareajenn** [comment]
@franz-wohlkoenig I'll totally test more of them once I'm through testing com_workflows and some TM website audits for the JUGs. I love testing!

**Comment by brianteeman** [comment]
Closed see #19302
