### ISSUE TITLE
[4.0] Rewrite sampledata.js

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#19263]
### Steps to reproduce the issue

- [x] Rewrite the script in vanilla Javascript
- [x] Replace BS alerts with CE's
- [x] Ensure the progress bar increments as per the steps

**Comment by anuragteapot** [comment]
@C-Lodder please change build to <code>4.0 dev</code><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19263">issues.joomla.org/tracker/joomla-cms/19263</a>.</sub>

**Comment by ghost** [comment]
@Anu1601CS done.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19263">issues.joomla.org/tracker/joomla-cms/19263</a>.</sub>

**Comment by anuragteapot** [comment]
@franz-wohlkoenig thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19263">issues.joomla.org/tracker/joomla-cms/19263</a>.</sub>

**Comment by C-Lodder** [comment]
change build?

**Comment by anuragteapot** [comment]
@C-Lodder I think, this is a part of Joomla-4 you have written  <code>4.0</code> in the title.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19263">issues.joomla.org/tracker/joomla-cms/19263</a>.</sub>

**Comment by C-Lodder** [comment]
I thought I already had `[4.0]` in the title

**Comment by anuragteapot** [comment]
Yes, but you mentioned build tag <code>staging</code><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19263">issues.joomla.org/tracker/joomla-cms/19263</a>.</sub>

**Comment by anuragteapot** [comment]
![screen shot 2018-01-03 at 10 46 18](https://issues.joomla.org/uploads/1/638715e6d19f5c8181c146e5bafdd524.png)
This one<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19263">issues.joomla.org/tracker/joomla-cms/19263</a>.</sub>

**Comment by C-Lodder** [comment]
Ah ok. I don't use the Issue Tracker on j.org unless I'm submitting a test, so I have no idea. Maybe something for @mbabker

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/19269
