### ISSUE TITLE
Language Uninstallation doesn't work for Japanese

### ISSUE THREAD

**Issue by Calisto1994** [joomla/joomla-cms#19265]
### Steps to reproduce the issue

I installed the japanese language pack on Joomla 3.8.3, but it didn't uninstall. It's left as installed extension and won't uninstall with error message 
![grafik](https://user-images.githubusercontent.com/35059233/34512560-9c255420-f063-11e7-97a3-afc2b5622a3d.png)

### Expected result

Removal of the language files, which did work for en-AU without any trouble.

### Actual result

When i disable the language, it's not listed as an installed language anymore and within the language manager, the button doesn't say "Reinstall", but "Install" instead

### System information (as much as possible)

[systeminfo-2018-01-03T07_57_08+00_00.txt](https://github.com/joomla/joomla-cms/files/1599697/systeminfo-2018-01-03T07_57_08.00_00.txt)

**Comment by N6REJ** [comment]
@infograf768  jm, I tested this with him via zoom and JP installed/uninstalled on my 3.8.3 site but didn't on his.  english-au did however.  His site IS Multilingual.  We checked trash, and cleared caches, checked for the language being used in some menu/content/item but nothing changed.  The behavior I saw was very strange so I had him open a ticket directly.

**Comment by ghost** [comment]
Issue confirmed.
### System information
 3.8.4-dev
Multilanguage Site (4 Lang.) & Test English (GB) Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19265">issues.joomla.org/tracker/joomla-cms/19265</a>.</sub>

**Comment by infograf768** [comment]
Looking now

**Comment by Calisto1994** [comment]
I was trying to uninstall Japanese without the language filter ("Japanese Language Pack") and it finally *worked* - i then tried to find out if there was such a package also for "english AU" and there was the main package left, just not the extensions which i already removed.

**Comment by infograf768** [comment]
Looking at the error, it looks normal if one tries to uninstall by language and not by package in recent lang packs

en-AU has not been updated (alas) to the new settings we have asked TTs to use in their manifest.
`<blockChildUninstall>true</blockChildUninstall>`

**Comment by N6REJ** [comment]
@infograf768 jm, the behavior is inconsistent.  in en-au he was able to uninstall the language sets individually but that left the pack.  with jp it refuses to allow individual removal but does remove via the pack.

**Comment by infograf768** [comment]
@N6REJ 
Look above https://github.com/joomla/joomla-cms/issues/19265#issuecomment-354956261

**Comment by infograf768** [comment]
Closing issue as not core.

**Comment by N6REJ** [comment]
@infograf768 yeah, was typing as you typed that :P  tnx
