### ISSUE TITLE
[4.0] Calendar improvements

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#19272]
- [ ] Use SVG for clock rather than pixelated PNG
- [ ] Styling for buttons

@dgt41 - you want to do this or shall I?

![calendar](https://user-images.githubusercontent.com/2019801/34520555-12a91e16-f081-11e7-9696-e0e6d190ea1f.png)

**Comment by brianteeman** [comment]
Closed due to lack of any response/interest
