### ISSUE TITLE
Also available in other language does not respect publishing status and Access Level

### ISSUE THREAD

**Issue by Giuse69** [joomla/joomla-cms#19279]
### Steps to reproduce the issue
Create article A in language L_A, create article B in language L_B and associate A to B.
Set article B as unpublished and with access = Registered.

### Expected result
1) Go to frontend as guest: you don't see any link to article in language L_B since you are not authorized to it and since it is not published.
2) Go to backend: lower the Access Level of A to Public. Go to frontend: still no flag to indicate a version in another language.

### Actual result
1) Go to frontend as guest: Joomla does show the message "Also available in L_B" but if you click on the flag, of course you get an error of unauthorized view.
2) Back to backend: lower the Access Level of A to Public. Go to frontend: the message is still there and clicking on the flag throws now a 404 error.

### System information (as much as possible)
Joomla 3.8.3

### Additional comments
Front-end should check access level and publishing state while publishing "Also available in <lang>".

**Comment by brianteeman** [comment]
confirmed

**Comment by infograf768** [comment]
Not an easy one to solve as we have no information in the infoblock about the status of the associated item itself. Just its link and the status of the Content Language.
![screen shot 2018-01-04 at 09 31 23](https://user-images.githubusercontent.com/869724/34555444-258db9a4-f132-11e7-9561-cfd100cd38df.png)

**Comment by Giuse69** [comment]
We have the id: can we add just an SQL query that checks publishing state and access level and the latter is compared with getAuthorisedViewLevels($userId)?

**Comment by infograf768** [comment]
We could do something in the associations layout indeed, but we would need to also code something for the category default_articles.php
Not sure where we should add such a code that would be used by both and is not present in the layouts as it would not be a good idea to use queries there..

**Comment by infograf768** [comment]
I guess we could do something in `ContentHelperAssociation`
Looking into this unless someone does it before.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/19314

**Comment by ghost** [comment]
closed as having Pull Request #19314
