### ISSUE TITLE
Staging [3.8.4-dev] can't login on front end with modern routing enabled

### ISSUE THREAD

**Issue by jsubri** [joomla/joomla-cms#19289]
### Steps to reproduce the issue

Staging (3.8.4-dev), I've a regression on front-end login I suspect https://github.com/joomla/joomla-cms/pull/19099 , as I'm getting a 404 with modern routing. 
I've a standard login form with "The Menu Item Login Redirect" toward a menu item. The referring page
"http://localhost/staging/index.php/fr/?option=com_users&view=login" is generating the following in the Redirects components "http://localhost/staging/index.php/fr/component/users/?task=user.login"

### Expected result
Login as usual

### Actual result

404 and "index.php/fr/component/users/?task=user.login" is logged in the Redirects components

### System information (as much as possible)
both Apache + PHP 5.4.23 and XAMPP with PHP 5.6.24

### Additional comments
Woking fine on 3.8.3

**Comment by csthomas** [comment]
~Can you explain more about "The Menu Item Login Redirect"?~ Ok I thing I found this option

**Comment by infograf768** [comment]
hmm. not sure I can reproduce here

**Comment by csthomas** [comment]
Please test #19295

**Comment by ghost** [comment]
closed as having Pull Request #19295
