### ISSUE TITLE
You are permitted to directly access this page

### ISSUE THREAD

**Issue by harpreetadi** [joomla/joomla-cms#19287]
When I am editing user in Joomla backed  dashboard  after click on close button I am not able to reopen that user again.can you please provide me solution.This is happening only in chrome

**Comment by ghost** [comment]
Thanks for reporting an issue.

Have you asked help on the [forums](https://forum.joomla.org/)? If yes, please provide a Link to the Thread. 

 This repository concerns in first Place Joomla coding.
