### ISSUE TITLE
After upgrading joomla from 3.7 to 3.8 issues

### ISSUE THREAD

**Issue by akash-simplecrm** [joomla/joomla-cms#19282]
**Getting Error in Control Panel in joomla backend**

500 JHtml image not found.	
/var/www/html/icc_2527/libraries/src/HTML/HTMLHelper.php:122
Call stack
--
# | Function | Location
1 | () | JROOT/libraries/src/HTML/HTMLHelper.php:122
2 | Joomla\CMS\HTML\HTMLHelper::_() | JROOT/administrator/modules/mod_acesearch_quickicons/mod_acesearch_quickicons.php:21
3 | getAcesearchIcon() | JROOT/administrator/modules/mod_acesearch_quickicons/mod_acesearch_quickicons.php:64
4 | include() | JROOT/libraries/src/Helper/ModuleHelper.php:201
5 | Joomla\CMS\Helper\ModuleHelper::renderModule() | JROOT/administrator/components/com_cpanel/views/cpanel/tmpl/default.php:25
6 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:695
7 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:230
8 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/administrator/components/com_cpanel/views/cpanel/view.html.php:65
9 | CpanelViewCpanel->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:672
10 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:710
11 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_cpanel/cpanel.php:15
12 | require_once() | JROOT/libraries/src/Component/ComponentHelper.php:381
13 | Joomla\CMS\Component\ComponentHelper::executeComponent() | JROOT/libraries/src/Component/ComponentHelper.php:356
14 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:101
15 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:159
16 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:267
17 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/index.php:52

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
