### ISSUE TITLE
unable to publish menu items (bug in 3.70 reported).. now in 3.8.3

### ISSUE THREAD

**Issue by johanpeters** [joomla/joomla-cms#19291]
### Steps to reproduce the issue
select publish menu item

### Expected result
item is being published 

### Actual result
item stil disabled

### System information (as much as possible)
joomla 3.8.3, php7

### Additional comments
after a lot of trying,.. delete en create new items.. problem stays the same.
delete al deleted items.. nothing works.

finaly i found a same report after joomla upgrade 3.6.5 -> 3.7.0..

i fixed it.. with phpmyadmin goto #__menu and entry Menu_Item_Root was not published.
changed the state from 0 to 1 .. and now i am able to publish existing and new menu items.

**Comment by ghost** [comment]
thanks for reporting Issue. There are similar Reports like #18020 and others which are mostly solved by [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). 

This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.

**Comment by johanpeters** [comment]
This is not upgrade or update related.. 
newly build website..

**Comment by brianteeman** [comment]
if it was a clean install of joomla from download.joomla.org then that issue should not be possible

**Comment by johanpeters** [comment]
it was a clean install from joomla.org.. i was building the website for 2 weeks.. and suddenly this happends.. i can not relate it to any installation of a component..  i was filling the website with content..

**Comment by brianteeman** [comment]
I have double checked the install files both with and without sample data and all of them correctly create the menu_item_root as published

**Comment by johanpeters** [comment]
okay.. clear... this issue was not in the beginning.. something triggered it.. i don't know what.. but if more people have this issue perhaps this whil help.. i don't know and can't find anything as root caus of this issue... but i am happy that i have fixed it.. based on the threat of this issue after upgrade 3.6.5 to 3.7.0..

**Comment by brianteeman** [comment]
if you can list all the extensions that you installed i might be able to track down the cause

**Comment by johanpeters** [comment]
rocksprocket
FE SEO
Menuary plugin
JCE Editor
multilanguage (dutch / english)
Attachment

al these extentions installed several days ago.. 
Template from energizethemes (empresa)

**Comment by brianteeman** [comment]
from that list I would strongly suspect an option menuary as it does a lot of weird stuff but i have never used it myself

**Comment by johanpeters** [comment]
And ofcorse the regular labs extentions.. and akeeba backup..

MenuAry perhaps.. verry nice extention to automaticly build menu items based on articles.. 
I will check that plugin

**Comment by PawelSzymanski89** [comment]
Try this: 
youradress.com/administrator/index.php?option=com_installer&task=database.fix
