### ISSUE TITLE
[4.0] remove radiobasic form field

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#19299]
The radiobasic form field was something I added in the early J4 days for stacked radios/checkboxes. Now that we have a PR to separate the switcher/radios and the form field was a silly move, we can remove the file and adjust the layout with a class

**Comment by brianteeman** [comment]
go for it then

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/19320
