### ISSUE TITLE
[4.0] helpTOC.php

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#19308]
this cli sccript to build the toc.json file is broken in both J3 and J4 (different errors)

**Comment by brianteeman** [comment]
Closed see #19315

**Comment by brianteeman** [comment]
Reopened for J4 - different bug

Error : class 'Joomla\Mediawiki\Http' not found

Checking composer it says it should be there but its not there in "vendor-dir": "libraries/vendor"

**Comment by mbabker** [comment]
Fixed via https://github.com/joomla/joomla-cms/commit/aed056a309c1e0cdb6c553c981153d8489610dc0

Dev dependencies (`require-dev` in Composer) aren't tracked in this repo the same as the production dependencies and their transient dependencies.  So to use the script you have to run `composer install` to get the dev dependencies (same as required for PHPUnit or Codeception).

**Comment by brianteeman** [comment]
thanks
