### ISSUE TITLE
[4.0] Session Save Path error

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#19304]
### Steps to reproduce the issue
1. Install Joomla 4

2. Access to Global Configuration area, look at System tab, In **Session Handler**, choose Filesystem, Session Save Path setting will be displayed. Two problems here:

- I am using windows and when I enter a valid path like D:\www\sessiondata, it is not being saved. Look like a problem with path filter
- I entered a wrong path like  **home/abc**. The system should validate and makes sure the path is valid before saving. However, it saves the wrong path anyway and makes the application completely broken (see the screenshot below)

![application_error](https://user-images.githubusercontent.com/977664/34614740-0c945c26-f265-11e7-9d3b-69c6887470ab.png)

**Comment by mbabker** [comment]
Addressed via https://github.com/joomla/joomla-cms/pull/19431
