### ISSUE TITLE
Can't choose module using editor plugin if you search first

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#19306]
### Steps to reproduce the issue
Open an article.  
Click on the module editor button to insert a module
Click on search tools
Select a module type
Click on the name of the module.  

### Expected result
Inserts module shortcode

### Actual result
Nothing happens.  But if you close down the window and reopen it you will be able to choose the module and the search will still be in place.
[systeminfo-2018-01-05T18_29_24+01_00.txt](https://issues.joomla.org/uploads/1/d66774115b477f2e7f779dc2dfffd4e8.txt)

**Comment by ghost** [comment]
Issue confirmed.

If using any kind of Search-Filter got:

![bildschirmfoto 2018-01-05 um 18 39 24](https://user-images.githubusercontent.com/8235763/34621069-ff22eb4c-f247-11e7-861c-01b47ef7a142.jpg)

**Comment by dgrammatiko** [comment]
Apply the same solution as in https://github.com/joomla/joomla-cms/pull/18359

This probably needs to be patched for every XTD-button.
@uglyeoin let me know if you can't provide a PR, then I'll do it

**Comment by uglyeoin** [comment]
@dgt41 I don't think I have the time at the moment.  Feel free to create a pull request if you have time, or else I will return when I have a bit of free time and give it a go.

**Comment by brianteeman** [comment]
@dgt41 tried the "same solution" and it didnt work for me :( any chance you can take a look

**Comment by dgrammatiko** [comment]
@brianteeman this is for staging, right?

**Comment by Quy** [comment]
See PR #20005<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19306">issues.joomla.org/tracker/joomla-cms/19306</a>.</sub>
