### ISSUE TITLE
4.0 Cassiopeia Customize Template: can't choose directory when creating new file

### ISSUE THREAD

**Issue by Mrs-Jaydot** [joomla/joomla-cms#19318]
### Steps to reproduce the issue
Go to Template - Customize, click "new file", choose file-type, enter name, choose directory where new file should be stored.

### Expected result
Ability to choose a directory.

### Actual result
Clicking a directory takes you back to the Template-Customize screen.
Clicking "create" will put the new file in the template's root.

### System information (as much as possible)
4.0 Alpha 2, Windows 10, Chrome browser.

### Additional comments
(First ever bug report... )

**Comment by ghost** [comment]
Both reported issues (not able to choose a Directory; "create" put the new File in Root of Template) confirmed.

No Errors shown in Browser-Console.

@Mrs-Jaydot Thanks for your first Report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19318">issues.joomla.org/tracker/joomla-cms/19318</a>.</sub>

**Comment by astridx** [comment]
Can this be closed as the PR is merged?

**Comment by Quy** [comment]
@astridx Please advise the PR #.

**Comment by astridx** [comment]
[4.0] fixErrorInTemplateJS #19356
