### ISSUE TITLE
Debug session output disrupted by session variable containing HTML

### ISSUE THREAD

**Issue by Sophist-UK** [joomla/joomla-cms#19311]
### Steps to reproduce the issue

Create a session variable containing `<strong>Some text</strong>`.

### Expected result

`"<strong>Some text</strong>"`

### Actual result

**`>Some text<\/strong>"`** with everything following in **bold** and following sections mis-displayed.

### System information (as much as possible)

J3.8.3

### Additional comments

Issue occurred when Kunena had set a session variable of the form `<strong>Some text</strong>`.

**Comment by rdeutz** [comment]
Can you give us a code example?

**Comment by Sophist-UK** [comment]
No. It happened after a Kunena upgrade, but I have submitted a PR #19312 to fix it.

**Comment by rdeutz** [comment]
closing because we have a PR #19312

**Comment by Sophist-UK** [comment]
I created the issue because the template for the PR asked for an issue #. I won't bother next time.
