### ISSUE TITLE
[4.0] Edit article via button Edit in menu item fails

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#19316]
### Steps to reproduce the issue
- Installed staging 4.
- Installed testing data.
- Open "All Menu Items".
- Open menu item "Home" (Edit view). Type is : "Single Article" 
- Click button "Edit" for editing the article "Joomla! Testing" .
- Edit form opens but empty title and empty editor.

![07-01-_2018_00-39-15](https://user-images.githubusercontent.com/20780646/34645059-ac163e74-f344-11e7-922c-31829b9ea8c0.jpg)

![07-01-_2018_00-40-04](https://user-images.githubusercontent.com/20780646/34645063-b350fc38-f344-11e7-93aa-5de7cf5ad279.jpg)

### System information (as much as possible)
xampp 7.1.8
win10 / 64

**Comment by ghost** [comment]
Issue confirmed.

Tried to reassign Article, but same Result. No Errors in Browser-Console.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19316">issues.joomla.org/tracker/joomla-cms/19316</a>.</sub>

**Comment by astridx** [comment]
I can confirm this issue, too.
**System information:** 
Ubuntu 16.04
PHP 7.0.22
Current 4.0-dev Branch

**Comment by ghost** [comment]
closed as having Pull Request #19390
