### ISSUE TITLE
Add option to hide "meta name= generator"

### ISSUE THREAD

**Issue by sshcli** [joomla/joomla-cms#19313]
### Steps to reproduce the issue
Backend->menu->new item->metadata tab

### Expected result
We need the option in the backend to hide/edit "meta name= generator"

### Actual result
There is no option to hide/edit "meta name= generator"
Anyone can see my site was made using Joomla 

### System information (as much as possible)
PHP 7.1.12
Joomla 3.8.3
MySQL 5.6.38

**Comment by Bakual** [comment]
There is no reason to hide the generator. Even if you don't show that tag, there are many other ways to detect that the site is built with Joomla. You can even detect the exact version of it without any issues.

**Comment by sshcli** [comment]
I understand.
But the other methods you mention are more advanced than this.
Right now, to see the generator is a single step "View Source Code"

For personal pages, it is ok to have it visible, but for professional pages owned by big companies this could be a problem.

**Comment by sshcli** [comment]
So, my suggestion is: 
Let the user decide if show this tag or not

**Comment by Bakual** [comment]
> But the other method you mention are more advanced than this.

Very advanced. Like for example checking the file "administrator/manifests/files/joomla.xml" (gives you exact Joomla version). Or in case administrator is blocked check if media/jui/css/bootstrap.css (or any other Joomla file) exists and you know it is Joomla. It's really not hard.
Even the regular sourcecode gives away clues for Joomla (eg template and media directories)

> For personal pages, it is ok to have it visible, but for professional pages owned by big companies this could be a problem.

I don't see the problem that companies could get when people can see they use Joomla.

**Comment by ghost** [comment]
>  Anyone can see my site was made using Joomla

You can see it without "Generator=".

**Comment by sshcli** [comment]
Ok
if no PR will be created for this issue, please feel free to close it at any time.
Regards

**Comment by ghost** [comment]
@sshcli you can always create a Pull Request but theres no Guarantee its gonna be merged.

**Comment by brianteeman** [comment]
If you want to do it you just have to add this to your template

`<?php $this->setGenerator(null); ?>
`

I am closing this as security through obscurity is no security at all
