### ISSUE TITLE
[4.0] Property $db->serverType empty

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#19317]
**Because I'm not sure if that's an expected behavior** I'm reporting it here.

with Joomla 3.8.3 it is possible to make a database serverType check like this:
```
$db = JFactory::getDbo();
if ($db->serverType != 'mysql')
{
 echo 'nag nag nag';
}
```

but not with current staging Joomla 4. `$db->serverType` is an empty property there.
(You can use `$db->getServerType() != 'mysql' ` instead.)

### System information (as much as possible)
XAMPP 7.1.8
win 10 / 64
Database Type (Joomla): MySQLi

**Comment by mbabker** [comment]
You should use the getServerType method to retrieve this as the getter will ensure the property value is set.

In 3.x the drivers may be setting this property manually but in 4.0 the code is all relying on this getter to do it.
