### ISSUE TITLE
[4.0] Rewrite markup radio form field

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#19322]
The radio form field needs to be fixed properly to support stacked/inline radios/checkboxes in addition to fixing the `btn-group` class.

**Comment by Bakual** [comment]
Can you explain more what you mean here?
What was wrong with https://github.com/joomla/joomla-cms/pull/19213?

**Comment by C-Lodder** [comment]
I need to have a chat with the a11y team and figure out if  the `btn-group` can be completely done without JS. After that, I need to ensure the standard radio button markup is always consistent, which currently it isn't.

**Comment by brianteeman** [comment]
Closed as solved elsewhere
