### ISSUE TITLE
Finder issues presenting the searched term in the results description.

### ISSUE THREAD

**Issue by Ooops-404** [joomla/joomla-cms#19339]
### Steps to reproduce the issue
Search for a term with and without quotes.

### Expected result
Searching for a term with or without quotes should be irrelevant for the feature of showing where in an article the term was found (results description field)

### Actual result
If you search for the item without quotes, ie. everyone, then the results that come back will show where in the article the term is found (first occurrence), but if you make the same search but now within quotes, ie. "everyone", then it only shows the term in the result description IF its within of the first X characters that you defined in the smart search Description Length configuration.

### System information (as much as possible) 
Database Version | 5.5.56-MariaDB
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 5.4.16
Web Server | Apache/2.4.6 (CentOS) PHP/5.4.16
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 3.8.4-dev Development [ Amani ] 12-December-2017 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299

### Additional comments
System Information was updated to the latest test on a clean Joomla install updated to the latest version (nightly build)

**Comment by ghost** [comment]
Build updated to 3.8.3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19339">issues.joomla.org/tracker/joomla-cms/19339</a>.</sub>

**Comment by tonypartridge** [comment]
Please see:
https://github.com/joomla/joomla-cms/pull/18522#issuecomment-353712318

Try using staging since my pull above is merged into this.

**Comment by Ooops-404** [comment]
> tonypartridge

How do I update to staging? I changed my Joomla update channel to testing, no luck. As in no new version found.

Thank you.

**Comment by mbabker** [comment]
Take a backup of your site, restore it in a testing environment (can be a subdirectory on your live host, just remember to delete it when finished), then update using the [nightly builds](https://developer.joomla.org/nightly-builds.html).

**Comment by Ooops-404** [comment]
@mbabker  Thank you.
Going to do it now, I'm assuming branch 3.8.. using the custom link.

**Comment by Ooops-404** [comment]
@tonypartridge 

I tried version 3.8.4-dev and 3.9.0-dev , no luck there. The problem is still there.

Were you referring to 4.0?

**Comment by Ooops-404** [comment]
Tested again, on a clean joomla install that I then updated to the latest nightly build for 3.8.x
No luck.

**Comment by brianteeman** [comment]
Closing this as its the same as #19518
