### ISSUE TITLE
Fatal error: Class 'Joomla\CMS\MVC\Model\FormModel'

### ISSUE THREAD

**Issue by ClaudiaRoldao** [joomla/joomla-cms#19333]
Hello! Someday something happened on my site and in joomla, an error message appears in joomla like this one
"Fatal error: Class 'Joomla\CMS\MVC\Model\FormModel' not found in /home/madeirai/public_html/libraries/src/MVC/Model/AdminModel.php on line 23"
and I do not know what to do.
While the site appears "index of /" and no site appears, what can I do to resolve the situation? 
A person gave me the site already built and with all the codes, just had to make basic changes, like changing images, ads and texts, this situation is not basic for me, sorry, I was grateful that someone could help, it is very important and urgent.
If someone could help me, I really appreciated it!

Thank you!

![joomla](https://user-images.githubusercontent.com/35224985/34672304-dc2d773a-f475-11e7-91d8-78371c026df4.png)
![site](https://user-images.githubusercontent.com/35224985/34672306-dc5252f8-f475-11e7-9bb1-9c87bed7a4f5.png)

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.

**Comment by brianteeman** [comment]
At least one obvious problem is that essential file "index.php" is missing from the root folder. The forum should be able to help
