### ISSUE TITLE
Missing types list for custom fields

### ISSUE THREAD

**Issue by petblower** [joomla/joomla-cms#19336]
### Steps to reproduce the issue
Hello, I have no idea what went wrong. I had some issues with recent updates and I am now using 3.8.3. Menus had disappeared, options in some plugins, and now I cannot create custom fields because I have to select a field type but none is available from the dropdown list.

### Expected result
Have a dropdown with list of available types for custom fields

### Actual result
No option is showing and I cannot save
![image](https://user-images.githubusercontent.com/35230524/34679665-ef93f27e-f496-11e7-9016-86455b7e698b.png)

### Additional comments
![image](https://user-images.githubusercontent.com/35230524/34679618-cc29ff2c-f496-11e7-9f14-d58c0a5a6995.png)

Thank you :)

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
