### ISSUE TITLE
Mail::sendMail() shouldn't use $autoReplyTo in Mail::setSender()

### ISSUE THREAD

**Issue by drTr0jan** [joomla/joomla-cms#19349]
### Steps to reproduce the issue
There's a hack in _libraries/src/Mail/Mail.php:742_:
If the _replyTo_ field doesn't exist use third param in `Mail::setSender()`.
The third param in `Mail::setSender()` (inherited from `PHPMailer::setFrom()`) had used for replyTo functional initially. But this functional has been cleaned from PHPMailer since 5.2.7 version ([#51, PHPMailer::setFrom $auto should be FALSE by default](https://github.com/PHPMailer/PHPMailer/issues/51)).

### Actual result
PHP `mail()` function doesn't send mails without the _replyTo_ field in some conditions of mail servers. Mail servers can defer the mail with custom _Sender_ field in some conditions.

### System information (as much as possible)
Joomla since 3.6.4 to latest, the Mailer is _mail_, PHP since 5.4.45 to latest

**Comment by Quy** [comment]
Please submit a PR.

**Comment by drTr0jan** [comment]
I'm a not a joomla user/programmer. I'm a web/mail server admin only on which other people install Joomla.
I don't undertsand a joomla goals and architecture. I can not submit a pull request. :(

**Comment by ghost** [comment]
@drTr0jan so we have to wait for a Developer.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19349">issues.joomla.org/tracker/joomla-cms/19349</a>.</sub>

**Comment by Quy** [comment]
Please confirm to omit the 3rd parameter from the call.

Before:
```
		// Add sender to replyTo only if no replyTo received
		$autoReplyTo = (empty($this->ReplyTo)) ? true : false;

		if ($this->setSender(array($from, $fromName, $autoReplyTo)) === false)
		{
			return false;
		}
```
After:
```
		if ($this->setSender(array($from, $fromName)) === false)
		{
			return false;
		}
```

**Comment by ghost** [comment]
Issue closed as no Information provided since 1+ Month. Issue can always reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19349">issues.joomla.org/tracker/joomla-cms/19349</a>.</sub>
