### ISSUE TITLE
Batch group delete not working properly on some case

### ISSUE THREAD

**Issue by irbian** [joomla/joomla-cms#19346]
### Steps to reproduce the issue

Create this group structure
- Group A
-- Subgroup A
- Group B
-- Subgroup B

Select all of them and delete

### Expected result

Groups deleted (or at least some error message)

### Actual result

Nothing. No action

### System information (as much as possible)

Joomla 3.8.1, PHP 5.6

### Additional comments

A workaround is selecting Group A and Group B. This delete that groups and their childrens

**Comment by brianteeman** [comment]
Before doing anything else please make sure that you have updated to the latest version of Joomla which at this moment in time is 3.8.3

**Comment by irbian** [comment]
Ok, I tested on 3.8.3. Don´t know if the difference come from the version or because I had made a simpler test, but now it was like

Group A
-- Subgroup A
Group B
-- Subgroup B

Select all, delete

Only Group A and Subgroup A, are deleted 

If I selected both a and b (but not the subgroups), all of them are properly deleted

**Comment by brianteeman** [comment]
You say groups - do you mean usergroups?

**Comment by irbian** [comment]
Yes

**Comment by brianteeman** [comment]
Thanks for confirming that

I can confirm that if you select
Group A
-- Subgroup A
Group B
-- Subgroup B

and then try to delete then ONLY
Only Group A and Subgroup A, are deleted

**Comment by jwaisner** [comment]
@irbian Can you confirm this still exists?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19346">issues.joomla.org/tracker/joomla-cms/19346</a>.</sub>

**Comment by richard67** [comment]
Closing as having a pull request. Please test #34131 . Thanks in advance.
