### ISSUE TITLE
[4.0] Severe error in Install

### ISSUE THREAD

**Issue by schnuti** [joomla/joomla-cms#19354]
### Steps to reproduce the issue
Add a wrong password for the DB user in the installation process.
Wait for the error message "Could not connect to database" 

### Expected result
Error message and try again.

### Actual result
A screen full with error messages from XDEBUG and a halt. 
Restart only possible after removing the configuration.php
After that I started new, entered a correct password and the installation ended as normal.

### System information (as much as possible)
Got this today (Jan 11) by accident when installing the version available for J4 new Media Manager

Windows 10, XAMPP, PHP 7.04

### Additional comments
I had a feeling that I entered a wrong character in the password for the DB user so I waited for the retry.

**Comment by Quy** [comment]
Duplicate #18557
