### ISSUE TITLE
[4.0] Curl php fatal error

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#19352]
`[09-Jan-2018 12:17:34 Europe/Berlin] PHP Fatal error:  Declaration of Joomla\CMS\Http\Transport\CurlTransport::request($method, Joomla\Uri\UriInterface $uri, $data = NULL, array $headers = Array, $timeout = NULL, $userAgent = NULL) must be compatible with Joomla\Http\TransportInterface::request($method, Joomla\Uri\UriInterface $uri, $data = NULL, ?array $headers = NULL, $timeout = NULL, $userAgent = NULL) in /Applications/MAMP/htdocs/installmulti/joomla40/libraries/src/Http/Transport/CurlTransport.php on line 26`

**Comment by Bakual** [comment]
> ?array $headers = NULL,

Is that question mark before `array` really there? Looks wrong to me.

**Comment by infograf768** [comment]
it is not there
I see this code there
`public function request($method, UriInterface $uri, $data = null, array $headers = [], $timeout = null, $userAgent = null);`

**Comment by Bakual** [comment]
Ah, then it marks probably the difference. Since one defaults to array and the other to NULL

**Comment by mbabker** [comment]
There has to be a PHP problem somewhere or outdated code in your clone, or something is overloading the core class.  All of the request method signatures in https://github.com/joomla/joomla-cms/tree/4.0-dev/libraries/src/Http/Transport match what is defined in https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/vendor/joomla/http/src/TransportInterface.php.

**Comment by infograf768** [comment]
Looks like I do not get the issue anymore.
