### ISSUE TITLE
not possible to add or customize contacts

### ISSUE THREAD

**Issue by umuehlbo** [joomla/joomla-cms#19355]
Hello.

It's not possible to add new or change existing contacts in field "components" --> "contacts".
After clicking "safe" oder "safe and exit" nothing more happens.

### Steps to reproduce the issue
Components --> Contacts --> add new Contact --> save and exit

### Expected result
new contact is saved or existing contact changes are saved

### Actual result
nothing happens after clicking safe or safe an exit

### System information (as much as possible)
![screen shot 2018-01-11 at 18 02 58](https://issues.joomla.org/uploads/1/0fddda28f22bb11bef4467742d75903f.jpg)

### Additional comments

![screen shot 2018-01-11 at 18 02 58](https://issues.joomla.org/uploads/1/148f7c34c79570fcee8f633afe217ab4.jpg)![screen shot 2018-01-11 at 18 02 58](https://issues.joomla.org/uploads/1/129bb52214f0b1afacd1cc1789307015.jpg)

**Comment by brianteeman** [comment]
Unable to replicate. Please use the forum for support https://forum.joomla.org
