### ISSUE TITLE
email stopped working at 3.8.3 update

### ISSUE THREAD

**Issue by spetricko** [joomla/joomla-cms#19363]
I have updated PHP, and all the addons I can think of.  I have checked the account (gmail), made sure everything is set right and I just can't get it to send an email from the site for form submitting. 
 Has anybody else run into this issue?  It is really effecting the usability of the site.

**Comment by Quy** [comment]
Please ask for assistance at [Joomla Forums](https://forum.joomla.org/viewforum.php?f=710). If a bug is found, please report it here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19363">issues.joomla.org/tracker/joomla-cms/19363</a>.</sub>
