### ISSUE TITLE
JS Issue in admin, cannot save

### ISSUE THREAD

**Issue by angelexevior** [joomla/joomla-cms#19372]
### Steps to reproduce the issue
PHP 5.6
Updated to 3.8.3

### Actual result
Administrator in menu item, cannot save, save & close, close, toolbar is gone

### System information (as much as possible)
Database Version | 5.5.58-cll
PHP Version | 5.6.32
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.8.3 Stable [ Amani ] 12-December-2017 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

Error in console (After button click):
Uncaught TypeError: Cannot read property 'task' of null
    at Object.e.submitform (core.js?3ceec799b7da3f08b7a33b49820bea4d:1)
    at Object.e.submitbutton (core.js?3ceec799b7da3f08b7a33b49820bea4d:1)
    at HTMLButtonElement.onclick (index.php?option=com_menus&view=item&client_id=0&layout=edit&id=235:1693)

### Additional comments
Browser cache wiped
Tried Chrome, Chrome incognito, Firefox, IE Edge, same result.

**Comment by angelexevior** [comment]
Tried re-applying the 3.8.x~3.8.3 manually. No result

**Comment by ghost** [comment]
From which Version you Updated first to 3.8.3?

**Comment by angelexevior** [comment]
3.8.2~3.8.3... i always upgrade as they come.
Note, issue may have existed since 3.8 in general as i haven't added anything since.

**Comment by ghost** [comment]
Thanks for Info from which Version you updated first. 

Have you asked at the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710)? If i understand your Info correct you have updated a earlier Version to 3.8, later to 3.8.3.

**Comment by ocutshaw** [comment]
I am having the same issue.  I can login to Admin but it is blank after that with now way to edit, no save, save closed, no toolbar, nothing but you can change the edit account or logout.  Cache is cleared and tried in all browsers.  I didn't change or update anything since the last login.  Anyone have any ideas.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19372">issues.joomla.org/tracker/joomla-cms/19372</a>.</sub>

**Comment by ghost** [comment]
@ocutshaw Have you asked at the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710)?

**Comment by ocutshaw** [comment]
I am there now and it seems to be a number of people with the same issue, so I am not the only person having this problem. Looks like something happened on Joomla's end with something they did over the past few days.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19372">issues.joomla.org/tracker/joomla-cms/19372</a>.</sub>

**Comment by brianteeman** [comment]
joomla can not change anything - only you can change something.

where you able to log in since you upgraded to 3.8.3

**Comment by Quy** [comment]
@angelexevior Is this happening to all menu items? If not, please advise the offending menu item type.

**Comment by Quy** [comment]
@ocutshaw Check the PHP error log to see if there are any warnings/errors.

**Comment by angelexevior** [comment]
Hope this helps someone figure it out. 
My best guess was caching either serverside or clientside. I made 2 moves which solved my issue (Don't know which one worked as i checked after both were done).

1.) Cleared and restarted memcached on server. (Running centos 6.9).
2.) Reinstalled Gantry framework (Rockettheme template).

Everything back to normality after these.
Can someone confirm if they face same issue with a rockettheme template (Gantry uses it's internal caching in both frontend and backend for rockettheme modules ~might affect rest of admin interface). If so, then this is not a joomla core issue.

Memcached? Anyone?

**Comment by Quy** [comment]
@angelexevior I installed Fluent 1.0.3 and had no issues.

Per your error `at HTMLButtonElement.onclick (index.php?option=com_menus&view=item&client_id=0&layout=edit&id=235:1693)`, `HTMLButtonElement` is found in this file `\plugins\editors\rokpad\ace\worker-javascript.js` which is from RocketTheme.

I would say it is not a Joomla core issue.

**Comment by Quy** [comment]
Closed as stated.

@ocutshaw Please open a new ticket because your issue is different.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19372">issues.joomla.org/tracker/joomla-cms/19372</a>.</sub>
