### ISSUE TITLE
Users with old password hash have custom field data erased during login

### ISSUE THREAD

**Issue by rmbutton** [joomla/joomla-cms#19379]
### Steps to reproduce the issue
1) Create user = testuser
2) Set password = testpass12
3) Create custom fields that would be entered by a new user during registration. Enter some data.
4) In phpMyAdmin, find testuser and change password hash to -
6412c972b558f324794f8f5277299990:o8LGpLw6htpjD7VyHWAWiW9cEeVyUO23
(this is the testpass12 hash created using Joomla 1.5 system)
5) Go to Front End and login using testuser and testpass12
6) Go to Backend, check testuser custom fields. They are now empty. 
7) Check phpMyAdmin, testuser new hash is something like:
$2y$10$wpRPb7uMhfFIurK9S4gneuhLcZppeIiULKpfIpIobqYRky1VJKrjq

### Expected result
Custom fields should not be set to default (mostly deleted) when a user logs in using an old hash and a new hash is created and saved.

### Actual result
Custom fields are being set to default (most are erased) during login when a new hash is saved to USERS table. Note that only the custom field data that would be entered during new user registration is affected. Other custom fields are untouched. 

### System information (as much as possible)
Joomla 3.8.3
PHP 5.6.30

### Additional comments
I moved 330 users from a Joomla 1.5 system to a 3.8.3 system. The old password hashes are accepted correctly, but they cause this loss of custom field data during login. This seems to be a similar problem to the issue of custom fields being erased when a new password is requested. See https://github.com/joomla/joomla-cms/issues/18185

**Comment by Quy** [comment]
This will be fixed in v3.8.4 with #18207.

**Comment by rmbutton** [comment]
That fixed it! Thanks!!
