### ISSUE TITLE
[4.0] Error on creating  a new viewing access level

### ISSUE THREAD

**Issue by anuragteapot** [joomla/joomla-cms#19374]
### Steps to reproduce the issue
1.Go to Users -> Viewing Access Levels
2.Try to create a new "Viewing Access Level" or edit previously Access Level.

Test this on Linux if possible.

### Expected result
No errors come.

### Actual result
An error has occurred.
<code>0 Call to a member function getKeyName() on boolean</code>

### System information (as much as possible)
Joomla: 4.0.0-dev
OS:Linux
PHP Version 7.1.12

**Comment by anuragteapot** [comment]
@franz-wohlkoenig can you test this on Linux.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19374">issues.joomla.org/tracker/joomla-cms/19374</a>.</sub>

**Comment by anuragteapot** [comment]
Related to #19028  previously, I have tested this on Windows without any issue, but in Linux, it has an issue.
I already fixed this issue just waiting for confirmation.

**Comment by ghost** [comment]
@Anu1601CS:
### System information
4.0-dev
Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by anuragteapot** [comment]
@franz-wohlkoenig its, Ok. Waiting for other to test :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19374">issues.joomla.org/tracker/joomla-cms/19374</a>.</sub>

**Comment by anuragteapot** [comment]
@Quy can you test this on Linux if possible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19374">issues.joomla.org/tracker/joomla-cms/19374</a>.</sub>

**Comment by Quy** [comment]
@Anu1601CS Confirmed the error on Linux.

**Comment by anuragteapot** [comment]
@Quy thanks for the confirmation :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19374">issues.joomla.org/tracker/joomla-cms/19374</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #19386
