### ISSUE TITLE
[4.0] Debug missing CSS in front-end Cassiopeia template

### ISSUE THREAD

**Issue by Sophist-UK** [joomla/joomla-cms#19376]
### Steps to reproduce the issue

New install of Joomla 4.
Turn on debugging for all groups.
Display home page in front end.

### Expected result

Nicely formatted Debug block looking like  that in J3 / Backend Atum template.

![atum](https://user-images.githubusercontent.com/3001893/34917320-c72efef0-f93c-11e7-8213-138a21473b67.png)

### Actual result

Horizontal inline-blocks rather than vertical blocks:

![cassiopeia](https://user-images.githubusercontent.com/3001893/34917331-dcb49a78-f93c-11e7-95b1-64d029fb9818.png)

### System information (as much as possible)

Fresh install of J4.

**Comment by ghost** [comment]
closed as no Information provided.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19376">issues.joomla.org/tracker/joomla-cms/19376</a>.</sub>

**Comment by Sophist-UK** [comment]
Finger trouble created it empty. Took me a few minutes to edit it. Please reopen.

**Comment by ghost** [comment]
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19376">issues.joomla.org/tracker/joomla-cms/19376</a>.</sub>

**Comment by Sophist-UK** [comment]
Thx.

**Comment by Sophist-UK** [comment]
No idea what the cause was - corrupted CSS download perhaps. But cleared cache and now it works.
