### ISSUE TITLE
Pagination for search module in Joomla 3.8.3 is not working

### ISSUE THREAD

**Issue by prchanda** [joomla/joomla-cms#19371]
### Steps to reproduce the issue

When I include in search module in my Joomla website, the pagination is not working as expected. Two issues :
1. If a search a word it shows that it found 10 records and when I change the display # filter to 5, it says "Total: 9 results found." which is strange. 

2. Secondly after changing the display # filter to 5 and navigate to the next page, it doesn't display the rest of the records, its empty. 

Interesting thing is that when I change the display # filter to 10, it displays all the records as expected in single page.

### Expected result

Pagination feature of search module should display rest of the records in the next page after clicking. on the "next" button

### Actual result

Changing the display # filter to 5 and navigate to the next page, it doesn't display the rest of the records, its empty. 

### System information (as much as possible)

PHP Built On  :	Windows Server 2016 AMD64
Database Version : 	5.7.9
Database Collation  :	utf8_general_ci
Database Connection Collation : 	utf8mb4_general_ci
PHP Version 	: 7.1.11
Web Server :	Microsoft-IIS/10.0
WebServer to PHP Interface :	cgi-fcgi
Joomla! Version  :	Joomla! 3.8.3 Stable [ Amani ] 12-December-2017 15:00 GMT
Joomla! Platform Version : 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent  :	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0 

### Additional comments

New installation of Joomla 3.8.3 doesn't shows this behavior. How to track why search pagination is failing ?![screen shot 2018-01-14 at 08 48 38](https://issues.joomla.org/uploads/1/9b134fbc5f2c3ee17a24b22830e8c897.png)![screen shot 2018-01-14 at 08 48 38](https://issues.joomla.org/uploads/1/0d40f357d9d36e979d06282ded41b774.png)![screen shot 2018-01-14 at 08 48 39](https://issues.joomla.org/uploads/1/eac9c2f6b50cdaff33561bd16137265e.png)

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
