### ISSUE TITLE
Archived articles only filtered by month, not year

### ISSUE THREAD

**Issue by Harmageddon** [joomla/joomla-cms#19382]
Issue originally reported by user jccemden at [Joomla-Bugs.de](http://www.joomla-bugs.de/forum/index.php?topic=744). Confirmed by me.

### Steps to reproduce the issue
1. Create an article "Archived January 2018"
   - Creation date: January 2018 (day doesn't matter)
   - Status: Archived
2. Create an article "Archived January 2017"
   - Creation date: January 2017 (day doesn't matter)
   - Status: Archived
3. Create an article "Archived February 2017"
   - Creation date: February 2017 (day doesn't matter)
   - Status: Archived
4. Create a module of the type "Archived articles" and publish it.
5. Enable SEF
6. In frontend, the module should display the months for which there are archived articles:
   - January 2018
   - February 2017
   - January 2017
7. Click on "January 2017"

### Expected result

You should only see the article from January 2017.

### Actual result

Instead, you'll see the "January" articles from all years. The month filtering works, as you don't see the "February" article, but the year filtering does not.
It works if SEF URLs are disabled. However, there is an additional issue (not sure if related or not) in both versions: The filter values are not or only partly propagated to the filter form. If you click on "January 2017", I'd expect the filter form to hold "January" as the month value and "2017" as the year. For SEF URLs, both are empty, for non-SEF, the year is entered, but the month is missing.

### System information (as much as possible)

The issue exists in Joomla! 3.8.3 and in the current staging. Tested on PHP 7.1.9.

### Additional comments

I'm not sure if this issue is related to the already known routing issues in 3.8. Due to limited time and a broken development environment, I'm not able to test the proposed PR(s) right now to see if they fix this issue, too.

**Comment by Quy** [comment]
Related #13757. I hope to have a fix/PR soon.

**Comment by ghost** [comment]
closed as having Pull Request #19397

**Comment by Quy** [comment]
@Harmageddon Please test or ask jccemden to test so that it might be included in the next release.

**Comment by jccemden** [comment]
@Quy 

if i replace the old legacyrouter.php with the new one, i get two errors: 
Warning: array_diff(): Argument #1 is not an array in site/components/com_content/models/archive.php on line 87
Warning: array_values() expects parameter 1 to be array, null given in site/components/com_content/models/archive.php on line 87<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19382">issues.joomla.org/tracker/joomla-cms/19382</a>.</sub>

**Comment by Quy** [comment]
Please apply this #19295 too.

**Comment by Quy** [comment]
Please apply this fix too: https://github.com/joomla/joomla-cms/pull/19075

**Comment by jccemden** [comment]
@Quy 
i implemented #19075 and #19295 too. 
no i can't see any posts. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19382">issues.joomla.org/tracker/joomla-cms/19382</a>.</sub>

**Comment by Quy** [comment]
I will investigate when I am at my computer in a couple of hours. Sorry #19295 is not related to this issue which I provided incorrectly.

**Comment by Quy** [comment]
Something is up with your setup. Go to this URL and it will get a `The page isn’t redirecting properly`.

http://www.escrilando.de/index.php/termine/termin-archiv/2017/12

Please undo the above changes to see if you get the same warning.

**Comment by jccemden** [comment]
I undo the changes above. The warning is consists. And now? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19382">issues.joomla.org/tracker/joomla-cms/19382</a>.</sub>
