### ISSUE TITLE
Translation error "/libraries/vendor/phpmailer/phpmailer/class.phpmailer.php"

### ISSUE THREAD

**Issue by uruk-hai-21** [joomla/joomla-cms#19388]
Is it possible to add the possibility to translate the errors for multilingual sites?

        // Define full set of translatable strings in English
        $PHPMAILER_LANG = array(
            'authenticate' => 'SMTP Error: Could not authenticate.',
            'connect_host' => 'SMTP Error: Could not connect to SMTP host.',
            'data_not_accepted' => 'SMTP Error: data not accepted.',
            'empty_message' => 'Message body empty',
            'encoding' => 'Unknown encoding: ',
            'execute' => 'Could not execute: ',
            'file_access' => 'Could not access file: ',
            'file_open' => 'File Error: Could not open file: ',
            'from_failed' => 'The following From address failed: ',
            'instantiate' => 'Could not instantiate mail function.',
            'invalid_address' => 'Invalid address: ',
            'mailer_not_supported' => ' mailer is not supported.',
            'provide_address' => 'You must provide at least one recipient email address.',
            'recipients_failed' => 'SMTP Error: The following recipients failed: ',
            'signing' => 'Signing Error: ',
            'smtp_connect_failed' => 'SMTP connect() failed.',
            'smtp_error' => 'SMTP server error: ',
            'variable_set' => 'Cannot set or reset variable: ',
            'extension_missing' => 'Extension missing: '
        );

**Comment by mbabker** [comment]
It's already possible.  Because of a change in the PHPMailer library, our last few releases haven't had the messages translated, this is fixed in 3.8.4 via https://github.com/joomla/joomla-cms/pull/19072.
