### ISSUE TITLE
[4.0] Sample Data

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#19389]
I was looking to fix a typo in the sample data when I realised that the blog sample data that you can install during the installation is different to the sample data that you can install from the new plugin y @Bakual 

Is that deliberate or an error

Before making any corrections it would be good to know which is the correct one etc

**Comment by Bakual** [comment]
Originally they were supposed to be identical. Given the time they lived in parallel by now, I wouldn't be surprised if differences arose.
Imho, with 4.0 we should drop the SQLs and only use the plugins, but afaik currently the installer still has the sample data in it even after its rewrite. don't ask me why...

**Comment by brianteeman** [comment]
Thanks

It looks like one of the differences is that when installed at install you get a complete set but when installed by the plugin you get the blog sample on top of the empty install. As a result you get the login module with the plugin but not with the SQL. 

Most of the other "errors" I saw were just content errors that I suspect have been there for years eg reference to an admin menu login that isn't present.

The question then  is if it's worth fixing or just starting from scratch with a new dataset

**Comment by Bakual** [comment]
That the plugin doesn't delete existing content is intended. That is to prevent data loss in case someone activates the install on an existing system. So yes, that difference is expected.

As for the content, I indeed just copy-pasted the existing strings for the most part.
Imho, I wouldn't  fix much for J3. For J4 we certainly should revisit the set and maybe do it even fresh.

**Comment by brianteeman** [comment]
OK I will work on a completely new set for J4 which actually has valid information
