### ISSUE TITLE
All tags are displayed regardless of the language setting

### ISSUE THREAD

**Issue by csbalazs** [joomla/joomla-cms#19387]
Hello,I have tags in two languages. I create a Category List menuitem and I set Filter Field to Tags, then all tags are displayed regardless of the language setting in the front-end. Any Ideia? Best regards, Balazs

List of Tags:
![screen shot 2018-01-16 at 10 30 08](https://issues.joomla.org/uploads/1/39cb6ebd5b67dfeb620cb61e175de959.png)
Frontend:
![screen shot 2018-01-16 at 10 30 19](https://issues.joomla.org/uploads/1/86670f989e6d6bd38bdcb6ad99da8f6d.png)

**Comment by ghost** [comment]
closed as duplicate Report #17244

**Comment by csbalazs** [comment]
I think, this is a different problem.

**Comment by ghost** [comment]
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19387">issues.joomla.org/tracker/joomla-cms/19387</a>.</sub>

**Comment by Quy** [comment]
Is your tags dropdown custom code? Please test this PR #19047.

**Comment by csbalazs** [comment]
Unfortunately, the #19047's code doesn't help.
This is a default Tag filtering in Category List:
![18011623](https://user-images.githubusercontent.com/1657924/35006503-0f8cab00-faf7-11e7-819b-f6f655b1f5cf.png)
All tags (English & Hungarian tags) appear, but the site languge is Hungarian, under the Protostar template:
![18011624](https://user-images.githubusercontent.com/1657924/35006647-6904e0d0-faf7-11e7-815b-2a08d9eb0764.png)

**Comment by alikon** [comment]
the parameter mentioned in #19047 `tag_list_language_filter`
is this Language Filter on Tags: Options
![screenshot from 2018-01-16 20-00-32](https://user-images.githubusercontent.com/181681/35006907-2e73d9de-faf8-11e7-8614-c93bc26d2b93.png)

**Comment by csbalazs** [comment]
I tried (Current + new TagField.php ), but all labels continue to appear.

**Comment by alikon** [comment]
@csbalazs  please test #19509

**Comment by ghost** [comment]
closed as having Pull Request #19509

**Comment by csbalazs** [comment]
It works now! Thx!

**Comment by ghost** [comment]
@csbalazs please mark your Test as successfully:

- open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/19509)
- Login with your github-Account
- Click on blue "Test this"-Button above Authors-Picture
- mark your Test as successfully
- hit "submit test result"
