### ISSUE TITLE
[RFC] Extract CMS coding standards to separate repo

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#19395]
Right now we have the base [coding standards](https://github.com/joomla/coding-standards) which are meant to be our coding standards used for all projects and a recommendation for extension developers to follow.  That repository, while it covers our general standards fairly well, can't have application specific rules in it like ones that apply to the CMS environment only (this is generally where you get into things like formatting of layout files or proposals such as the [deprecated code sniffs](https://github.com/Ruud68/coding-standards/tree/master/Joomla/Sniffs/Deprecated)).  Additionally, since the CMS ruleset lives in this repository, to run code style checks with the CMS specific rules in place you have to clone this repository (which complicates setting up other tooling), whereas with our base coding standards repo all you need is a `composer install` and it is fairly easy to set up checks in CI environments.

I'd like to suggest moving the [CMS coding standards](https://github.com/joomla/joomla-cms/tree/staging/build/phpcs/Joomla) to a new repository so that the extended ruleset can be used more easily outside of the CMS repository with the ruleset inheriting from the base standards repo so that we aren't duplicating maintenance efforts (for years the coding standards repo has lived separately from the ruleset inlined into this repo and they have diverged in some ways, plus some fixes have been made in one place but not the other), and this also makes the CMS ruleset available for use in other projects (right now in com_patchtester I run PHPCS against the main coding standards repo but have to have some extra rules/excludes that are already covered by the CMS ruleset for its layout files).

**Comment by brianteeman** [comment]
Seems to make logical sense to me

**Comment by nibra** [comment]
+1 - makes absolutely sense.

**Comment by tonypartridge** [comment]
+1 from me too! Great idea.

**Comment by roland-d** [comment]
+1 Sounds good.

**Comment by laoneo** [comment]
+1

**Comment by yvesh** [comment]
+1

**Comment by dgrammatiko** [comment]
+1

**Comment by mbabker** [comment]
Repo built - https://github.com/joomla/cms-coding-standards

Here's hoping it's a maintained resource and doesn't become abandonware.
