### ISSUE TITLE
[com_fields] items limited to 3 in article

### ISSUE THREAD

**Issue by shawnhy** [joomla/joomla-cms#19394]
### Steps to reproduce the issue

I add 4 items in Content->Fields but only 3 of them shown in article tab. In Components->Contacts->Field, there is no such a problem. 4 field items displays as expectation.
![Custom fields limits in article](https://image.ibb.co/jxAehR/Articles_Edit_startup_Administration_Articles_Fields_startup_Administration.jpg "")
### System information (as much as possible)

3.8.3

**Comment by brianteeman** [comment]
I cannot replicate this
Sounds like a problem with that specific field
Please post a screenshot of that field settings OR 
Create a new text field and see if that displays

**Comment by brianteeman** [comment]
<img width="597" alt="screenshotr14-34-11" src="https://user-images.githubusercontent.com/1296369/35047957-83af21ce-fb93-11e7-8ae2-3aa530e03bd1.png">

**Comment by ghost** [comment]
Updated "System Information" in first Comment to show its about "3.8.3".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19394">issues.joomla.org/tracker/joomla-cms/19394</a>.</sub>

**Comment by shawnhy** [comment]
It seems I used Chinese character in integer item's name. This results to a problem. To sum up, less than 3 items with Chinese name is okay.

**Comment by ghost** [comment]
Added Category "Multilanguage".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19394">issues.joomla.org/tracker/joomla-cms/19394</a>.</sub>

**Comment by brianteeman** [comment]
@shawnhy I think it is something else. (apologies for the language)
<img width="538" alt="screenshotr14-41-54" src="https://user-images.githubusercontent.com/1296369/35048339-a57c127a-fb94-11e7-90e8-7ced68f857a8.png">

**Comment by brianteeman** [comment]
(sorry hit close by accident)

**Comment by shawnhy** [comment]
@brianteeman can you show me a screen shot of one of the Simplified-Chinese items? Now I can only tell that you were using Titles in Chinese.

**Comment by brianteeman** [comment]
the only thing i have in chinese is the title and the autogenerated label

**Comment by shawnhy** [comment]
Thanks, it reasonable to leave the Name field blank and generate automatically from title. This time I make all types and shows only 4.
![articles__edit_-_startup_-_administration_ _articles__fields_-_startup_-_administration](https://user-images.githubusercontent.com/7928790/35049587-6d68dec6-fbdb-11e7-8e9e-17fe535fa2df.jpg)

**Comment by brianteeman** [comment]
I see a tab called "extra fields" what is that? Maybe it is conflicting. I really dont think is anything to do with the chinese

**Comment by shawnhy** [comment]
Actually I've never use Extra fields tab. It comes form T3 framework, allows us to modify looking.

**Comment by brianteeman** [comment]
I am closing this at this time. It can always be reopened if it can be replicated on a clean install
