### ISSUE TITLE
[4.0] Invalid security token when using Send Test mail

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#19392]
Set your mail account in Global Configuration, then click on `Send Test Mail` button.

Result
Error
The most recent request was denied because it contained an invalid security token. Please refresh the page and try again.

Refreshing does not help.

**Comment by anuragteapot** [comment]
Related to #19071

**Comment by ghost** [comment]
@Anu1601CS is it a duplicate Report?

**Comment by anuragteapot** [comment]
@franz-wohlkoenig yeah but, #19071 contains multiple issues which were Partially fixed and closed.
So, left this issue open.

@brianteeman any comment.

**Comment by anuragteapot** [comment]
#19426 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19392">issues.joomla.org/tracker/joomla-cms/19392</a>.</sub>

**Comment by ghost** [comment]
@Anu1601CS can you please explain why you comment above?

**Comment by anuragteapot** [comment]
@franz-wohlkoenig Not, sure but I am thinking that this issue is related to <code>Test Mail.</code>
In this issue, it shows <code>The most recent request was denied because it contained an invalid security token. Please refresh the page and try again</code> if you are trying to send mail.
Which was changed in PR.

**Comment by ghost** [comment]
Thanks, so you meant in Comment that both issues are related.

**Comment by anuragteapot** [comment]
@franz-wohlkoenig close this having PR #19426

**Comment by ghost** [comment]
closed as having Pull Request #19426
