### ISSUE TITLE
Feature request: 'Mark' archived articles

### ISSUE THREAD

**Issue by wezetel** [joomla/joomla-cms#19401]
### Steps to reproduce the issue
If searching for an article I get a list of articles matching the search criteria. There are also articles found in the archive (ok: I don't like Joomla links to these archived articles, because you first need to go the way through the archive list and manualy select the according article, but this is an issue I already have placed).
But opening an article from the archive displays the original article and there is no indication, that this article is already archived.
It would be good to have an indication, that the article is archived, e.g. a background image or some text added to the title (" - archived"). This should be handled in the settings (content settings?)
I'm currently trying a dirty stuff, by including code in components/com_content/views/article/tmpl/default.php
This is the code I currently have included after line 26:
````
<?php if ($this->item->state == 2) : ?>
<div><h3> Archived </h3></div>
<?php endif; ?>
````
Simple, but it works.
But I would prefer something included in the system and customizable from the admin area. Good would be to define a background image for archived articles.

**Comment by Quy** [comment]
Related #14923

**Comment by ghost** [comment]
@wezetel can you please comment your Feature Request on #14923 if it isn't there? Close this Issue for this Reason.

**Comment by ghost** [comment]
reopened cause its not good to have different Requests in one Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19401">issues.joomla.org/tracker/joomla-cms/19401</a>.</sub>

**Comment by wezetel** [comment]
Thanks for re-opening, because #14923 has a different scope (basically appearance of archived articles in blogs, lists,..)
My request is just for means to make it visible for end users, that they are reading an archived article. 
At the current point in time they can't distinguish, if this is really actual news or not, when they open an article.

**Comment by wezetel** [comment]
As an interim solution until this feature is included in Joomla I have included in components/com_content/views/article/tmpl/default.php after line 26 following code:
````
<?php if ($this->item->state == 2) : ?>
	<div id="archive">
<?php else: ?>
	<div>
<?php endif; ?>
````
In addition at the end of the file a  ````</div>```` needs to be added. This code is resulting in a named div only for archived articles, which can be customized in the templates css, e.g. 
#archive {background-image: url("../../../images/archived.png");}
(Remark to myself: keep in mind this is a core hack and needs to be re-applied after any Joomla Update, until this is an official feature)

**Comment by Quy** [comment]
This can be done with [Component Output Types and Layout Overrides](https://docs.joomla.org/Understanding_Output_Overrides#Component_Output_Types_and_Layout_Overrides) without hacking core files.

**Comment by wezetel** [comment]
True! Nearly forgotten that I can use overrides..
Nonetheless it would be good to have this kind of feature included in Joomla

**Comment by Quy** [comment]
Please test PR #20297<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19401">issues.joomla.org/tracker/joomla-cms/19401</a>.</sub>
