### ISSUE TITLE
[com_fields] cleared in frontend

### ISSUE THREAD

**Issue by svenboulanger** [joomla/joomla-cms#19405]
### Steps to reproduce the issue
Create a custom user field for articles. Set the custom field value for any article, then try and edit the article in the frontend as administrator or any user that can edit the user field value.

### Expected result
The user field value should not be changed since it is not visible anyway in the frontend.

### Actual result
The user field value is cleared.

### System information (as much as possible)
Joomla! Version: Joomla! 3.8.3 Stable [ Amani ] 12-December-2017 15:00 GMT
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
PHP version: 7.0.10

### Additional comments
I tracked the problem to `plugins\system\fields\fields.php` on line 91.

```php
// Determine the value if it is available from the data
$value = key_exists($field->name, $fieldsData) ? $fieldsData[$field->name] : null;

// Setting the value for the field and the item
$model->setFieldValue($field->id, $item->id, $value);
```

If the field is not found in the data, I guess it should be ignored rather than passed null?

**Comment by joomdonation** [comment]
Please check this PR https://github.com/joomla/joomla-cms/pull/18207, it might solve that issue

**Comment by svenboulanger** [comment]
I believe that pull request will solve the issue.

**Comment by ghost** [comment]
@svenboulanger can you please close this Issue if the PR solve the Issue?
