### ISSUE TITLE
You are not authorized to view this resource.

### ISSUE THREAD

**Issue by stefanpoensgen** [joomla/joomla-cms#19404]
I currently have the problem when I get a page view that is visible only after a login, I'm forwarded to the home page with the message "You are not authorized to view this resource."
After that, the page is but over his menu normal callable.
Only happens when SEF URLs are active.

Joomla 3.8.3
Multilanguage active
PHP-Version 7.1.13

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
