### ISSUE TITLE
[4.0] Joomal switcher radio field broken for Firefox

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#19403]
An image is worth a thousand words

What it should be (Safari Screenshot)
<img width="665" alt="screen shot 2018-01-19 at 07 32 37" src="https://user-images.githubusercontent.com/869724/35137745-30f36afe-fceb-11e7-87c5-c622d4835cb0.png">

What we get with Firefox
![screen shot 2018-01-19 at 07 32 27](https://user-images.githubusercontent.com/869724/35137761-3f214a74-fceb-11e7-961c-60684ba3838e.png)

**Comment by ghost** [comment]
Can't confirm:

![bildschirmfoto 2018-01-19 um 07 38 27](https://user-images.githubusercontent.com/8235763/35137856-d0b46bd8-fceb-11e7-9d5a-6e475874e550.jpg)

### System information
4.0-dev
Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by infograf768** [comment]
MY Firefox is 57.0.4
PHP 7.1.8

**Comment by ghost** [comment]
I'm also on 57.0.4.

**Comment by infograf768** [comment]
Are you using last available 4.0 dev?

**Comment by ghost** [comment]
I'm on Custom Url `https://update.joomla.org/core/nightlies/next_major_list.xml` and updated before (got "You already have the latest Joomla version, 4.0.0-dev.").

**Comment by infograf768** [comment]
Here, clean install of last real branch (not nightly) gives
<img width="1180" alt="screen shot 2018-01-19 at 08 04 53" src="https://user-images.githubusercontent.com/869724/35138586-99719f0c-fcef-11e7-883f-c1b55a1cde96.png">
Something wrong in the kingdom of Denmark

**Comment by ghost** [comment]
As far as i know nightly are updated Branch (These packages were last built: Friday, 19 January 2018 02:00:26 UTC).

**Comment by infograf768** [comment]
Console errors:

<img width="1509" alt="screen shot 2018-01-19 at 08 15 22" src="https://user-images.githubusercontent.com/869724/35138917-f924f254-fcf0-11e7-9113-2bc41477e4a1.png">

**Comment by infograf768** [comment]
Also
[19-Jan-2018 08:30:20 Europe/Berlin] PHP Notice:  Undefined offset: 0 in /Applications/MAMP/htdocs/newfolder/joomla40/layouts/joomla/form/field/radio.php on line 71
[19-Jan-2018 08:30:20 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/newfolder/joomla40/layouts/joomla/form/field/radio.php on line 71
[19-Jan-2018 08:30:20 Europe/Berlin] PHP Notice:  Undefined offset: 1 in /Applications/MAMP/htdocs/newfolder/joomla40/layouts/joomla/form/field/radio.php on line 72
[19-Jan-2018 08:30:20 Europe/Berlin] PHP Notice:  Trying to get property of non-object in /Applications/MAMP/htdocs/newfolder/joomla40/layouts/joomla/form/field/radio.php on line 72

**Comment by infograf768** [comment]
@franz-wohlkoenig 
Please do a clean install and not an update.

Use
https://developer.joomla.org/nightlies/Joomla_4.0.0-dev-Development-Full_Package.zip

**Comment by ghost** [comment]
I will, but isn't the nightly Build to not must start by Zero?

**Comment by infograf768** [comment]
Normally, yes. But there could be a problem when updating.
Specially
[4.0] Remove grunt in favour of native node build scripts (#18446)
is removing some files and the updater may not have deleted these.

**Comment by ghost** [comment]
Issue confirmed on Firefox.

**Comment by infograf768** [comment]
As you also have remarked, and that is not only on Firefox, the Statistics panel is displaying over the body and has no background.

**Comment by ghost** [comment]
Correct, the Statistic Panel-Issue is also on Safari.

**Comment by dgrammatiko** [comment]
Expected! The code in the other repo custom elements needs update

**Comment by infograf768** [comment]
@dgt41 
Understand. When will it be updated as we just can't test on Firefox?

**Comment by dgrammatiko** [comment]
I'll send a PR later on

**Comment by ghost** [comment]
closed as having Pull Request #19407
