### ISSUE TITLE
[4.0] Page got trapped in modal-backdrop.

### ISSUE THREAD

**Issue by anuragteapot** [joomla/joomla-cms#19408]
### Steps to reproduce the issue

1.Try to edit an article (Open article editor page).
2.Then scroll the page down.
3.Click on the version or preview.

### Expected result
![screen shot 2018-01-19 at 14 51 18](https://issues.joomla.org/uploads/1/e304c96933b6088152a719e6c59f822b.png)

### Actual result
![screen shot 2018-01-19 at 14 51 30](https://issues.joomla.org/uploads/1/13deb328c02d208d696d33a3d800d9ed.png)

### System information (as much as possible)
Joomla-Version:4.0.0-dev
OS:Linux

**Comment by anuragteapot** [comment]
@franz-wohlkoenig can you test this issue.

**Comment by ghost** [comment]
I'm not on Linux.

**Comment by anuragteapot** [comment]
I am not sure, is this issue present on mac or not?

**Comment by ghost** [comment]
>  OS:Linux

Means to me this happens only on Linux, so i didn't test.

Test now without Issue:

![bildschirmfoto 2018-01-20 um 12 17 53](https://user-images.githubusercontent.com/8235763/35182831-3c6a0ee6-fddc-11e7-9f68-ab9d389ff0d8.jpg)

### System information
4.0-dev
Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by anuragteapot** [comment]
Did you scroll down like this? Then check


![screenshot from 2018-01-20 16-52-36](https://user-images.githubusercontent.com/30978328/35182870-63848072-fdd4-11e7-9029-7710c496d1b2.png)

It normally working if you don't scroll

**Comment by ghost** [comment]
Works also if reduce Size of Browserwindow so i have to scroll down.

**Comment by anuragteapot** [comment]
Ok thanks,
Live demo of this issue https://www.youtube.com/watch?v=4Rj6VzlhLuU
Both in windows and Linux

**Comment by ciar4n** [comment]
Issue confirmed

Modal markup is inside the toolbar resulting in them sharing z-index when fixed. I suspect to amend this the modal markup needs outside of the toolbar. 

@dgt41

**Comment by anuragteapot** [comment]
@dgrammatiko can you please take a look here ?

**Comment by dgrammatiko** [comment]
There are 3 moving parts here:
- @ciar4n already has a PR for the sticking toolbar using only css
- @Fedik has a PR for the new toolbar
- we are working on a new accessible jquery free modal replacement

So although this is a real issue at the moment it should be fixed with either of the above mentioned PRs or the new modal

**Comment by brianteeman** [comment]
Any update on the new modal its been 3 months

**Comment by bembelimen** [comment]
If we get this issue fixed, then we can use the Patchtester in J!4, which would be a great help: https://github.com/joomla-extensions/patchtester/issues/208

**Comment by brianteeman** [comment]
@bembelimen you can still use it

**Comment by bembelimen** [comment]
True, I can, but "normal" people get irritated. Just would be nice to have it done.

**Comment by brianteeman** [comment]
yes it is irritating but it is still usable

**Comment by ghost** [comment]
closed as having Pull Request #21343
