### ISSUE TITLE
[3.8.4] Regression in the ISIS backed css

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#19411]
### Steps to reproduce the issue

- install 3.8.3
- install 3.8.4-dev
- login into 3.8.3
- find the logout dropdown
- check the same on 3.8.4-dev

### Expected result

The same as of 3.8.3

![image](https://user-images.githubusercontent.com/2596554/35175157-b24ecc10-fd72-11e7-8a75-59988d94e28f.png)

### Actual result

![image](https://user-images.githubusercontent.com/2596554/35175176-be2acfac-fd72-11e7-8ceb-afca6b1ccd73.png)

### Additional comments

Looks like this PR: https://github.com/joomla/joomla-cms/pull/19140 was the only one that changed the ISIS css files this release and by reverting the templete.css to it's original state in 3.8.3 the error is gone obviously the old issue is back so it is not a solution to just revert that back ;)

@brianteeman can you take a look into that as the original PR was yours?

**Comment by brianteeman** [comment]
This change is causing it
https://github.com/joomla/joomla-cms/pull/19140/files#diff-92bd4bc9fc868397bd2dcf5f303c0ec4L8210

**Comment by brianteeman** [comment]
i wont get a chance to look at it until monday so if someone else wants to ...

**Comment by brianteeman** [comment]
see #19417
