### ISSUE TITLE
"Category List" Menu item - hits will not hide

### ISSUE THREAD

**Issue by hsojhsoj** [joomla/joomla-cms#19410]
### Steps to reproduce the issue
Create a menu item of type "Articles" -> "Category List" 
Under "Options" tab "Show Hits" set to "Hide"

### Expected result
Hits column hidden

### Actual result
Hits are shown

### System information (as much as possible)
Joomla 3.8.3 fresh install, php 7.0.27, 

see phpinfo(); at location below
https://test02.dependentmedia.com/test/info.php

### Additional comments
Have a nice day.

**Comment by brianteeman** [comment]
Options tab sets the display of the hits for the individual article ie after clicking on an item in the list
You should be in the LISTS LAYOUT tab and setting the hits to hide there

**Comment by zero-24** [comment]
There is a explizit setting in the List Layouts tab called `Show Hits in List` that take care of the list:

![image](https://user-images.githubusercontent.com/2596554/35175607-b181c218-fd74-11e7-9cce-c7876b22ce77.png)

Result:
![image](https://user-images.githubusercontent.com/2596554/35175635-d97406aa-fd74-11e7-9a82-fb6eaa0fce19.png)
