### ISSUE TITLE
Newsfeeds broken

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#19412]
### Steps to reproduce the issue
Create a new newfeed to the joomla rss feed at` https://www.joomla.org/announcements/release-news.feed?type=rss`
Create a menu link to display the feed

### Expected result
The feed is displayed

### Actual result
Joomla default error page
` No registered feed parser for type html.
`

**Comment by brianteeman** [comment]
Update - tested with another feed also from a joomla site and it worked correctly

weird

**Comment by zero-24** [comment]
Could it be a side affect from this one: https://github.com/joomla/joomla-websites/issues/1108 aka blocked by SiteLock?

**Comment by zero-24** [comment]
As your URL is the exact one that is used by com_postinstall and errors in the Backed currently

**Comment by brianteeman** [comment]
Perhaps although I dont understand how. If you go to the url for the feed directly in a browser then it works

**Comment by zero-24** [comment]
Maybe blocked useragents or some other magic happening inside of SiteLock to secure joomla.org

**Comment by brianteeman** [comment]
but only on www as feeds from other joomla properties work

- http://feeds.joomla.org/JoomlaSecurityNews
- https://community.joomla.org/blogs/community.feed
- https://extensions.joomla.org/blog/feed/rss/jed-blog/?format=feed

**Comment by brianteeman** [comment]
ok reading the sitelock "features" it looks like it is sitelock error
