### ISSUE TITLE
[4.0] Move interactive fields to custom Elements

### ISSUE THREAD

**Issue by dgrammatiko** [joomla/joomla-cms#19427]
### Fields:

- [x] media: still jQuery dependant due to modal

- [x] user: still jQuery dependant due to modal

- [x] switcher

- [x] send test mail https://github.com/joomla/joomla-cms/pull/19426
- [x] subform https://github.com/joomla/joomla-cms/pull/19184

- [x] simple-color https://github.com/joomla/joomla-cms/pull/19281

- [ ] password (view and strength scripts are now combined) https://github.com/joomla/joomla-cms/pull/19231

- [x] Editor none: https://github.com/joomla/joomla-cms/pull/19909

- [x] Editor codemirror: https://github.com/joomla/joomla-cms/pull/19890

- [ ] Editor tinyMCE

- [x] module order: https://github.com/joomla/joomla-cms/pull/19644
- [ ] tag #19642 (or codepen: https://codepen.io/dgt41/pen/KvbbdE)
- [ ] color (advanced picker) (WIP: https://codepen.io/dgt41/pen/ypjvOL)

- [x] permissions https://github.com/joomla/joomla-cms/pull/19889 (jQuery elimination: https://github.com/joomla/joomla-cms/pull/19278)

- [ ] calendar

- [ ] modal fields

- [] radio field (group buttons): https://github.com/joomla/joomla-cms/pull/20549

~After phase one where we get the first code merged the team will cover all these fields with proper tests (and probably fix any bugs found)~

Each new script should come with at least minimum JS tests, this is vital!

**Comment by anuragteapot** [comment]
@dgt41 Can you please update permissions with my PR?

**Comment by anuragteapot** [comment]
@dgrammatiko can you add <code>joomla-alert</code> with confirm functionality in list.

**Comment by dgrammatiko** [comment]
@Anu1601CS that is not part of the fields. Also there is a huge A11Y problem if the alert contains more than the close button (basically it needs to be a modal and restrict the tab key to the elements of the modal)...

**Comment by anuragteapot** [comment]
Ok
