### ISSUE TITLE
Add more advice to helptext COM_CONFIG_FIELD_SEF_REWRITE_DESC

### ISSUE THREAD

**Issue by gorgonz** [joomla/joomla-cms#19432]
### Steps to reproduce the issue
goto the backend and navigate to system > configuration. You will see the tab "site" activated. Move your mouse over the item "Use URL Rewriting"

### Expected result
... Apache users only!</strong><br />Rename htaccess.txt to .htaccess before activating and consider to uncomment the line '# RewriteBase /". ...

### Actual result
... Apache users only!</strong><br />Rename htaccess.txt to .htaccess before activating. ...

### System information (as much as possible)
You will find the string in languages/en_GB/en-GB.com_config.ini at the tag "COM_CONFIG_FIELD_SEF_REWRITE_DESC"

### Additional comments
From my knowledge this step must be done anyway, why not help users ;-). Don't know if it would be to long to note additionally, that one has to add the subdir in the case, that the site is to be called in a  subdir. i.e "http://mysite.com/subdir/index.php"

Don't know how the info is to be spread to the other language teams ;-)

**Comment by brianteeman** [comment]
it is a "tip" not a manual

**Comment by gorgonz** [comment]
I accept, though thinking about the actual string, I suppose, it is a manual already ;-)

**Comment by brianteeman** [comment]
and that is something we are working (almost complete) to rectify in joomla 4

**Comment by gorgonz** [comment]
ic ;)

**Comment by ghost** [comment]
@gorgonz can you please close this Issue?

**Comment by gorgonz** [comment]
of course
