### ISSUE TITLE
[4.0] jQuery Migrate obsolete version

### ISSUE THREAD

**Issue by obuisard** [joomla/joomla-cms#19434]
Since the support to jQuery has been narrowed down to jQuery 3, the jQuery Migrate plugin also needs to be updated to 3 (1.4.1 is only meant to ease the path to jQuery 1.9/2.0 and is useless with jQuery 3).

Reference:    https://jquery.com/upgrade-guide/3.0/#jquery-migrate-plugin

**Comment by brianteeman** [comment]
it has been removed from j4
it was only included in j3 because a core file needed it

**Comment by brianteeman** [comment]
see #15136

**Comment by mbabker** [comment]
It's still there - https://github.com/joomla/joomla-cms/blob/4.0-dev/package.json#L27

The PR you linked was declined.  jQuery Migrate isn't enabled by default but we still have the plugin as part of our dependency tree.

**Comment by brianteeman** [comment]
Sorry my mistake. I did check the folder but i forgot it had been moved

**Comment by brianteeman** [comment]
updating to the 3.0 plugin provides very different functionality. it does not do any polyfill

**Comment by obuisard** [comment]
Whatever is decided (keep or remove migrate from Joomla 4), version 1.4.1 is useless with jQuery 3.

**Comment by dgrammatiko** [comment]
Let’s kill it 😈 with fire 🔥

**Comment by brianteeman** [comment]
I understand @wilsonge argument here https://github.com/joomla/joomla-cms/pull/15136#issuecomment-296371996 but surely the logical conclusion to that is to replace migrate 1.4.1 with the latest version

**Comment by wilsonge** [comment]
sure go for it

**Comment by brianteeman** [comment]
See https://github.com/joomla/joomla-cms/pull/22616
