### ISSUE TITLE
Send spam through user registration

### ISSUE THREAD

**Issue by yoerin** [joomla/joomla-cms#19438]
### Steps to reproduce the issue
Set user activation to 'Admin' and allow user registration.

Submit the registration form where the name of the user is spam text and enter an email to spam (use a test email for this ofcourse)

### Expected result
No email send to the user

### Actual result
The email that is used to register an account receives an email and because the name of the user contains spam text this text is placed in the email.

### Additional comments
Ad an option to turn off all emails after registration or putt a variable limitation on the username

**Comment by Fedik** [comment]
just enable Captcha for registration:
![screen 2018-01-23 15 25 47 494x270](https://user-images.githubusercontent.com/1568198/35278165-cfeb1bb6-0051-11e8-86be-9e633c49f277.png)

**Comment by brianteeman** [comment]
the username field is only 30 characters of text - not very useful for sending spam

**Comment by Quy** [comment]
While the username field has a size attribute of 30, it can be up to 150 characters long.

**Comment by brianteeman** [comment]
@quy the database table allows it to be 150 but the "spammer" can still only submit 30 characters

**Comment by Quy** [comment]
More than 150 characters can be entered but it will be truncated at 150. I created a 150 characters username.

**Comment by brianteeman** [comment]
I only tested in the admin where you can only submit 30

**Comment by Quy** [comment]
Ok then the issue is the front end registration allowing up to 150 characters.

**Comment by brianteeman** [comment]
So that's a bug and will cause issues if a long username is created on the fronted and then edited in the admin. I will take a look at fixing that

**Comment by brianteeman** [comment]
Sorry my mistake you can enter 150 characters in both admin and frontend - I must have had a different error before that was unrelated

**Comment by sandewt** [comment]
The Name is up to 400 characters long. Could also be shorter.

Moreover, it can break the layout of the site (backend + frontend) .

See the image.

![screen shot 2018-02-02 at 17 44 10](https://issues.joomla.org/uploads/1/e128c5b37a0d54e02e909ced49bbf446.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19438">issues.joomla.org/tracker/joomla-cms/19438</a>.</sub>

**Comment by Quy** [comment]
Related #14275<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19438">issues.joomla.org/tracker/joomla-cms/19438</a>.</sub>

**Comment by Quy** [comment]
Lets discuss in #14275 as it relates to more control over username/email which would address spam abuse as mentioned in this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19438">issues.joomla.org/tracker/joomla-cms/19438</a>.</sub>
