### ISSUE TITLE
3.8.4-RC regression on modern router: 404 category not found for Archived Articles

### ISSUE THREAD

**Issue by jsubri** [joomla/joomla-cms#19430]
### Steps to reproduce the issue
install  "Learn Joomla English (GB) Sample Data"
Configuration: SEF ON with Modern Router + Remove IDs from URLs = YES
Disable the menu item  "Site Map"
Select "Archived Articles" then select the "Uncategorised" link category
![new3](https://user-images.githubusercontent.com/5349333/35198395-8eb4ca8e-feee-11e7-974a-fbb47819d3d4.PNG)

404 is generated for 
http://localhost/384RC/index.php/component/content/category/uncategorised
### Expected result

no error

### Actual result

1 | () | JROOT\libraries\legacy\error\error.php:200
2 | JError::raise() | JROOT\libraries\legacy\error\error.php:277
3 | JError::raiseError() | JROOT\libraries\src\MVC\View\CategoryView.php:133
4 | Joomla\CMS\MVC\View\CategoryView->commonCategoryDisplay() | JROOT\components\com_content\views\category\view.html.php:72
5 | ContentViewCategory->display() | JROOT\libraries\src\MVC\Controller\BaseController.php:672
6 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT\components\com_content\controller.php:113
7 | ContentController->display() | JROOT\libraries\src\MVC\Controller\BaseController.php:710
8 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\components\com_content\content.php:43
9 | require_once() | JROOT\libraries\src\Component\ComponentHelper.php:382
10 | Joomla\CMS\Component\ComponentHelper::executeComponent() | JROOT\libraries\src\Component\ComponentHelper.php:357
11 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\SiteApplication.php:194
12 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT\libraries\src\Application\SiteApplication.php:233
13 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:303
14 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\index.php:49

### System information (as much as possible)
3.8.4RC with PHP 5.4.34 and 7.1

**Comment by ghost** [comment]
Can't confirm, got:

![bildschirmfoto 2018-01-22 um 07 55 16](https://user-images.githubusercontent.com/8235763/35208716-fecc5b56-ff49-11e7-8621-9a564b06d34e.jpg)

**Comment by jsubri** [comment]
@franz-wohlkoenig, I've not tested with multilingual. What you have is the expected behaviour e.g http://localhost/384RC/index.php/site-map/articles/uncategorised
After unpublishing the "Site Map" menu item, on page reload the "Archived Articles" is becoming
http://localhost/384RC/index.php/using-joomla/extensions/components/content-component/archived-articles, then the "Uncategorised" link is broken.

**Comment by infograf768** [comment]
We have 2 PRs related to archive
Please test them
https://github.com/joomla/joomla-cms/pull/19415
https://github.com/joomla/joomla-cms/pull/19397
to see if any impact

**Comment by ghost** [comment]
@jsubri i had unpublished Menu "Site Map" in [Comment](https://github.com/joomla/joomla-cms/issues/19430#issuecomment-359340210). url i got `http://localhost:8888/3/index.php/en/allcategories-en-gb/uncategorised`.
### System information
- 3.8.4-rc
- Multilanguage Site (4 Lang.) & Test English (GB) Sample Data
- Template: Protostar
- macOS Sierra, 10.12.6
- Firefox 57 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by jsubri** [comment]
@infograf768, I've tested the 2 PR referenced before posting. They do not fix this issue.
Looks like the URL is component based while there is a valid menu item. The title might be a bit misleading, shall be: " 404 category not found _**after**_ selecting archived articles
I retested once again with the 4 steps provided and still hitting the problem.

@franz-wohlkoenig, I've not tested yet this issue with Multilanguage.

**Comment by infograf768** [comment]
> I've tested the 2 PR referenced before posting.

If you have and they solve the problems they target (even if it is not yours), please mark them as successful. 😃

**Comment by joomdonation** [comment]
I can confirm this issue, the link to article is broken too. Look like https://github.com/joomla/joomla-cms/pull/19280 solved it

**Comment by csthomas** [comment]
I confirm this issue (Modern Routing + Remove IDs) and the solution is at #19280. 

@franz-wohlkoenig If you unpublish `allcategories-en-gb` menu item then you should see the problem.

Joomla before 3.8.4-dev did not build such links too often, but the problem exists from 3.8.0. 

The difference is that previously you was directed to the wrong page (in above example this is the main page), but now you get error 404. Test with `index.php/en/component/content/archive?year=2018&month=1`

@jsubri already tested it and one more test is required.

**Comment by jsubri** [comment]
#19280 is fixing it.

**Comment by ghost** [comment]
@jsubri can you please close the Issue?

**Comment by Quy** [comment]
Solved as stated in (https://github.com/joomla/joomla-cms/pull/19280#issuecomment-359430609).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19430">issues.joomla.org/tracker/joomla-cms/19430</a>.</sub>
