### ISSUE TITLE
SMTP with authentication doesn't work

### ISSUE THREAD

**Issue by rudisten1** [joomla/joomla-cms#19441]
### Steps to reproduce the issue
Configure SMTP settings under global settings to use an STMP server with authentication (port 587, STARTTLS)
Try to send a test email

### Expected result
A message indicating the mail has been sent.

### Actual result
A messase telling you that it has not been possible to connect to the SMTP server.

### System information (as much as possible)
SO: Windows NT SRVRGSQL 6.1 build 7601 (Windows Server 2008 R2 Standard Edition Service Pack 1) i586
db mysql: 5.7.13-log
db Collation : utf8_general_ci
PHP version: 5.6.24
Web Server: Microsoft-IIS/7.5
WebServer interface: cgi-fcgi
Joomla! version:! 3.8.3 Stable [ Amani ] 12-December-2017 15:00 GMT
Joomla! platform version: Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments
Possibly due to new version of PHP mailer

**Comment by Quy** [comment]
Duplicate #19440 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19441">issues.joomla.org/tracker/joomla-cms/19441</a>.</sub>
