### ISSUE TITLE
Replace Logo on Login Screen with SVG from Joomla 4 on Joomla 3

### ISSUE THREAD

**Issue by CeleritasCognito** [joomla/joomla-cms#19442]
I think we should replace the PNG on the Login with a SVG.
Joomla 4 delivers this here: /installation/template/images/logo.svg

**Comment by C-Lodder** [comment]
Joomla 3 needs to support older browsers (including FF and Chrome), which don't all play nicely with SVG's

**Comment by brianteeman** [comment]
closed for the reasons stated above
