### ISSUE TITLE
[4.0]After installing via https, base url is set to http

### ISSUE THREAD

**Issue by mueller-ma** [joomla/joomla-cms#19444]
### Steps to reproduce the issue
1. Install apache, php and mariadb
2. Download and extract joomla in the webroot
3. Visit site, http to https redirection working as intended
4. Finish installation
5. Visit installed joomla admin page

### Expected result
Force https is set to true

### Actual result
It's not

### Additional comments
I think it should be set, as the installation process was done via https

**Comment by mbabker** [comment]
👎 

The force SSL setting shouldn't be arbitrarily enabled in the installer because the request which causes the configuration to be written was performed over HTTPS.

**Comment by mueller-ma** [comment]
Even one "accidental" login over http can compromise. There should be at least a checkbox in the installer.

**Comment by mbabker** [comment]
An option is an acceptable thing.  An arbitrary behavior based on whether one specific request is issued over HTTPS IMO is not.

**Comment by jwaisner** [comment]
Features are only available to be applied to J4. Adjusting labels to J4.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19444">issues.joomla.org/tracker/joomla-cms/19444</a>.</sub>

**Comment by mueller-ma** [comment]
Unsubscribing this issue as I don't use Joomla anymore.
