### ISSUE TITLE
com_search - defaul_result displays article with html-structure  without blanks.

### ISSUE THREAD

**Issue by xinelope** [joomla/joomla-cms#19455]
### Steps to reproduce the issue
create an acrticle content structured like
```<dl><dd>abc</dd><dd>def</dd></dl>```

### Expected result
abc def
### or
abc
def

### Actual result
abcdef

### System information (as much as possible)
Joomla 3.8.3

**Comment by ghost** [comment]
Changed markup in Comment above to show HTML-Structure also Joomla-Version to 3.8.3.

**Comment by xinelope** [comment]
sorry...
### Steps to reproduce the issue

create an acrticle, content structured like
`<dl><dd>abc</dd><dd>def</dd></dl>`

**Comment by ghost** [comment]
@xinelope Comment was to show that i have changed your first Comment ;-)

**Comment by Quy** [comment]
@xinelope I can not reproduce. The output is `abc def `.

**Comment by xinelope** [comment]
Here ist an example:
http://relaunch.sandspiel.de/index.php/suche?searchword=musterfrau&searchphrase=all
(it's the same result without override)

**Comment by Quy** [comment]
There is a space between items.
![search](https://user-images.githubusercontent.com/368084/35402838-93a4cad2-01b2-11e8-8c2a-845478fabc52.jpg)

**Comment by Quy** [comment]
Not reproducible. You have an override that may have affected the markup/output.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19455">issues.joomla.org/tracker/joomla-cms/19455</a>.</sub>
