### ISSUE TITLE
no email appeaaring 

### ISSUE THREAD

**Issue by MIRIAMDART** [joomla/joomla-cms#19458]
i am trying to log in to my Joomla account i seem to have mixed up the username and password but i am not receiving ant mail to reset after several times of putting in my email address

**Comment by brianteeman** [comment]
Please use the forum for support https://forum.joomla.org
If your problem is that you cant login to the forum then please report it here https://github.com/joomla/joomla-websites

**Comment by MIRIAMDART** [comment]
please how then do i reach joomla's help desk

**Comment by brianteeman** [comment]
I repeat
Please use the forum for support https://forum.joomla.org
If your problem is that you cant login to the forum then please report it here https://github.com/joomla/joomla-websites
