### ISSUE TITLE
Newest Update Crashed Backend

### ISSUE THREAD

**Issue by mintmarketing** [joomla/joomla-cms#19459]
I was prompted to update upon login. After the update the whole backend is a blank white screen. I can pick from menu items and the pages appear to be loading, but nothing comes up on the white screen. Please help!![screen shot 2018-01-25 at 20 07 39](https://issues.joomla.org/uploads/1/7ed245da0c4a6b0e10ddd09fd6c6f5b0.png)

**Comment by brianteeman** [comment]
Please use the forum for support
https://forum.joomla.org

**Comment by mintmarketing** [comment]
Oh sorry! i thought i was in the forum!
