### ISSUE TITLE
[4.0] Image manipulation broken when inserting image in article

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#19461]
Insert Image via the image xtd in TinyMCE

![image_manip](https://user-images.githubusercontent.com/869724/35433087-74a9808e-0282-11e8-854e-cfdc38b4deb0.gif)

As the feature is designed to be used from com_media (and does not really work there), it breaks in the xtd popup

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19461">issues.joomla.org/tracker/joomla-cms/19461</a>.</sub>

**Comment by amone4** [comment]
The following change in administrator>components>com_media>tmpl>media>default.php solved the bug

before
	`'editViewUrl'             => JUri::root() . 'administrator/index.php?option=com_media&view=file' . $tmpl,`
after:
	`'editViewUrl'             => JUri::root() . 'administrator/index.php?option=com_media&view=file&tmpl=' . $tmpl,`

But for some reason, the images won't get inserted into the article.
I have been experiencing this problem in 4.0-dev before I made this change though.
This particular issue has been addressed in #19922<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19461">issues.joomla.org/tracker/joomla-cms/19461</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #19976
