### ISSUE TITLE
[4.0] Multilingual status in admin Joomla 4

### ISSUE THREAD

**Issue by mokhin-denis** [joomla/joomla-cms#19462]
### Steps to reproduce the issue

- Install Joomla 4 Alpha 2
- Create new content language
- Create new menus, categories and materials, etc
- Click on 'Multilingual status'
![2018-01-26_12-25-38](https://user-images.githubusercontent.com/11349097/35433336-26f45da2-0294-11e8-9e21-5658641c5f61.png)

### Expected result
Normal modal window with black (disabled) background
![2018-01-26_12-23-21](https://user-images.githubusercontent.com/11349097/35433358-3bbe378a-0294-11e8-9bfc-7e6698e8e737.png)

### Actual result

- Modal window is shown
- Left sidebar is over the modal window
- Black is over the whole screen
![2018-01-26_12-33-29](https://user-images.githubusercontent.com/11349097/35433612-2bb01a92-0295-11e8-806a-14cf8cf58422.png)

### System information (as much as possible)
PHP Built On | Linux server150.hosting.reg.ru 2.6.32-696.18.7.el6.x86_64 #1 SMP Thu Jan 4 17:31:22 UTC 2018 x86_64
Database Version | 5.6.35-80.0
Database Collation | utf8_general_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.1.11
Web Server | Apache/2.2.15 (CentOS)
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 4.0.0-dev Development [ Amani ] 31-March-2017 23:59 GMT
User Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

### Additional comments
A think, the DIV id="multiLingualModal" must be right after the DIV id="wrapper".

**Comment by infograf768** [comment]
Please test with staging.
Here is what I get here.
<img width="986" alt="screen shot 2018-01-26 at 10 44 56" src="https://user-images.githubusercontent.com/869724/35434132-55dd3b9c-0286-11e8-8a76-dde849519890.png">

**Comment by mokhin-denis** [comment]
Can u please help me: how to update my J4 installation with stagging version. I did not clone it from github. I installed it from zip using installer

**Comment by brianteeman** [comment]
You can't do an upgrade but you can install the nightly build from here https://developer.joomla.org/nightly-builds.html

**Comment by ghost** [comment]
duplicate Report of #19408?

**Comment by mokhin-denis** [comment]
May close issue. Thanx for @infograf768. Stagging version works fine at this point
