### ISSUE TITLE
Bulk editor?

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#19465]
What are people’s thoughts on adding a bulk menu item edit tool and a bulk content tool?

The idea would be to edit menu item title, meta title, description and keywords.

**Comment by brianteeman** [comment]
There are extensions already,

**Comment by tonypartridge** [comment]
There are 3rd party extensions to handle this yep, but to me it should be part of the core since your managing core content. Usually the 3rd party ones add their own table and store it themselves which adds additional overhead and more code. Especially when it’s all done in the core, we are just missing the ability to edit it inline.

**Comment by brianteeman** [comment]
I dont see the need for this in the core especially as the meta information is so unimportant to google etc these days

**Comment by tonypartridge** [comment]
That’s a very blindsided view on it Brian, it’s still very important, whilst not for ranking factors but for conversions. This meta snippet is what google pulls and other search engines to show on the listing which is much more relevant that what google might try to pull out of the page.

I get the core doesn’t want to improve this aspect and that’s fine, I’ll just write a component to interact directly with it for myself :-) so consider this closed.

**Comment by infograf768** [comment]
@tonypartridge 

> I get the core doesn’t want to improve this aspect and that’s fine

I was not aware that @brianteeman represented "the core"

**Comment by tonypartridge** [comment]
@infograf768, no one else has commented so there is no other interest.

**Comment by infograf768** [comment]
OK
