### ISSUE TITLE
[4.0] Bug after creating an override

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#19475]
### Steps to reproduce the issue
Extensions->Templates-> Create overrides.
Try any option Module, Component, Layout.

### Expected result
Creates an override of the extension (folder+files)

### Actual result
Getting this error :
``` 0 Argument 1 passed to Joomla\CMS\Version::getUserAgent() must be of the type string, null given, called in libraries/src/Factory.php on line 758 ```

Folder is created, no files.

### System information (as much as possible)
Joomla 4 (yesterday's Joomla_4.0.0-dev-Development-Update_Package)
PHP 7.1.7
PHP 7.2.0

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19475">issues.joomla.org/tracker/joomla-cms/19475</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #19482
