### ISSUE TITLE
Error 403 - System Information  -  Administrator

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#19478]
I added a new user to standard user group **Administrator**. When I log in with this user, menu item **System Information** in panel **System** is shown (see 1.jpg). Clicking this item, an error 403 is thrown (see 2.jpg).

### Steps to reproduce the issue
Add user to standard user group "Administrator".
Log in with this user.
Click on "System information" under "System".

### Expected result
System information is displayed.

### Actual result
Error 403 (Not authorized).

### System information (as much as possible)
Joomla 3.8.3 with only a small number of extensions (Akeeba Backup, JCE, OSMap, Phoca Maps, SIGPlus; all updated)

### Additional comments
In my understanding, an Administrator should be able to see the System Information. A Manager shouldn't.

![screen shot 2018-01-29 at 15 03 50](https://issues.joomla.org/uploads/1/8a9ab7949458c2254a0aeac434605657.jpg)
![screen shot 2018-01-29 at 15 03 50](https://issues.joomla.org/uploads/1/879eba442ee2dea2b42693ea638dc4ac.jpg)

**Comment by mbabker** [comment]
This is by design - https://github.com/joomla/joomla-cms/blob/3.8.3/administrator/components/com_admin/views/sysinfo/view.html.php#L71

The view checks for global super user permissions to see this screen as it exposes potentially sensitive information about the server setup.

**Comment by dautrich** [comment]
I got your point. But if it's designed like this, the menu item "System Information" shouldn't be displayed for an Administrator, but only for a Super User.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19478">issues.joomla.org/tracker/joomla-cms/19478</a>.</sub>

**Comment by mbabker** [comment]
This sounds vaguely like another of the issues we have where admin menu items need to be shown/hidden based on ACL (or in this case an ACL level other than the `core.manage` usually used) and not viewing levels, for which there seem to already be a bunch of workarounds in https://github.com/joomla/joomla-cms/blob/3.8.3/administrator/modules/mod_menu/menu.php#L234 for.

**Comment by Quy** [comment]
See PR #19697<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19478">issues.joomla.org/tracker/joomla-cms/19478</a>.</sub>

**Comment by ghost** [comment]
@dautrich please test #19697

**Comment by dautrich** [comment]
@franz-wohlkoenig       I have successfully tested #19697 (s. screenshot)
![result_19697](https://user-images.githubusercontent.com/7933215/36301294-9640ee70-1304-11e8-93ee-98f9f2aac413.jpg)

**Comment by ghost** [comment]
@dautrich please mark your Test as successfully:

- open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/19697)
- Login with your github-Account
- Click on blue "Test this"-Button above Authors-Picture
- mark your Test as successfully
- hit "submit test result"

**Comment by dautrich** [comment]
@franz-wohlkoenig   Done

**Comment by ghost** [comment]
Thanks @dautrich for Test. Now the Pull Request need a second successfully Test before Release Lead decide if it gets merged.
