### ISSUE TITLE
[4.0] Clear button on manual search not working

### ISSUE THREAD

**Issue by eera5607** [joomla/joomla-cms#19470]
Hello! I don't know if this has been reported before but just in case...

### Steps to reproduce the issue
Go to modules, plugins etc... do a manual search and use the clear button. 

### Expected result
Clear the text field and show all items without filters.

### Actual result
The button does not seem to do anything at all

### System information (as much as possible)
Working on localhost with XAMPP
PHP Version 7.2.0
Joomla! 4.0.0-dev Alpha 1 and Alpha 2

### Additional comments
I attached 2 GIFs to better show the issue. It is easier to understand it watching the GIFs. 
![screen shot 2018-01-27 at 21 34 52](https://issues.joomla.org/uploads/1/f5b1d59dba4b97397f2451f70f74c4e4.gif)
![screen shot 2018-01-27 at 21 34 54](https://issues.joomla.org/uploads/1/7e827bc2b997ccc59934d88dde6b116d.gif)

**Comment by Quy** [comment]
Not reproducible. Please test with the development branch. https://github.com/joomla/joomla-cms/tree/4.0-dev<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19470">issues.joomla.org/tracker/joomla-cms/19470</a>.</sub>
