### ISSUE TITLE
[4.0] CSS Grid error in Cassiopeia's template.css

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#19476]
CSS grids are tricky. 
In template.css, line 10166
``` 
.container-component {
    grid-column: auto 2fr;
}
```
Any Inspector qualifies this as an "invalid property".
After checking "grid-column" in MDN (Mozilla Developer Network
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column
It appears that length units(here, fr) are not supported by this property, grid-column being a shorthand property for grid-column-start and grid-column-end.

BTW, still exploring the fact that featured articles or category-blog are not displaying more than one column is related to CSS grid or else.

Firefox 58
Chrome 64

**Comment by C-Lodder** [comment]
Where are you seeing that `fr` isn't supported with `grid-column`?

Are you testing on J4 Alpha 2 or Nightly?

Can you provide a screenshot?

**Comment by Quy** [comment]
\templates\cassiopeia\css\template.css (starting line 10166)
```
.container-component {
  /* autoprefixer: off */
  grid-column: auto 2fr; }
```

\templates\cassiopeia\scss\blocks\_css-grid.scss
```
.container-component {
  /* autoprefixer: off */
  grid-column: auto 2fr;
}
```

**Comment by astridx** [comment]
I see the message, that there is an invalid value for property grid-column, too

I use the current 4.0-dev branch.

Attached you see  a screenshot.

![bildschirmfoto vom 2018-01-29 21-49-56](https://user-images.githubusercontent.com/9974686/35534065-a36a3c3c-053f-11e8-8c70-4f805f75f0db.png)

**Comment by ciar4n** [comment]
A valid issue. That entire rule can be removed.

I was waiting for a decision on https://github.com/joomla/joomla-cms/pull/19062 which rewrites the grid and removes that rule.

> BTW, still exploring the fact that featured articles or category-blog are not displaying more than one column is related to CSS grid or else.

Maybe you are looking for this... https://github.com/joomla/joomla-cms/pull/18319

**Comment by ghazal** [comment]
@ciar4n 
Tks for the update. 

#18319, very interesting proposition. Unfortunately, and to my dismay, "masonry" disappeared from /media/vendor/ even though mentions of it still exist in current cassiopeia's template.css.
Looks like you deleted this in #19062. CSS grid or flex don't render exactly like masonry. 
I didn't post on the issue of columns not showing in featured articles or category blog because I guessed it was a work-in-progress.

#19062 
I will test it as soon as I can.
To gridify a template is not an easy feat. Kudos.

**Comment by Quy** [comment]
Please test PR #25256.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19476">issues.joomla.org/tracker/joomla-cms/19476</a>.</sub>
