### ISSUE TITLE
[4.0] Lateral menu overlaps debug panel on backend

### ISSUE THREAD

**Issue by eera5607** [joomla/joomla-cms#19471]
### Steps to reproduce the issue
Go to Global Configuration > System tab and activate Debug System option

### Expected result
See the complete debug panel at the end of each page

### Actual result
Part of the debug panel is hidden by Joomla's lateral menu administrative pages

### System information (as much as possible)
Working on localhost with XAMPP
PHP Version 7.2.0
Joomla! 4.0.0-dev (2018-01-28)

### Additional comments
Here is the screenshot:
![screen shot 2018-01-28 at 21 27 52](https://issues.joomla.org/uploads/1/1bc22c96572463a8271fc47ec3b2ed54.png)

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19471">issues.joomla.org/tracker/joomla-cms/19471</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #20061
