### ISSUE TITLE
[4.0] Custom Elements: `Element#attachShadow` was not patched.

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#19480]
The issue  https://github.com/joomla/joomla-cms/issues/17914 described this warning first:

##Steps to reproduce the issue

1. Enable Inspector in FireFox
 2. Go to the Control Panel
 3. Check the Console tab
 4. The notice is shown there

The issue https://github.com/joomla/joomla-cms/issues/17914 is closed, because there was a PR.
The PR https://github.com/webcomponents/custom-elements/pull/112/files is merged. 

Why do we still see this warning?

The warning occurs in the file webcomponents-ce.min.js:1:7969. I cant find a file with this name in the repo https://github.com/webcomponents/custom-elements or in the repo https://github.com/webcomponents/webcomponentsjs
Can it be that the file is outdated?

**Comment by C-Lodder** [comment]
Yes, this file needs updating.

**Comment by astridx** [comment]
How can we update thar file?

**Comment by dgrammatiko** [comment]
So this is partly my fault as I didn’t realized that there were 2 console.warns in the script: https://github.com/webcomponents/custom-elements/issues/106

**Comment by dgrammatiko** [comment]
Ok, I was wrong, the latest file doesn not contain that console.log. Anyways I'll do a PR to get the latest polyfills and remove that warning

**Comment by dgrammatiko** [comment]
@astridx #19484 fixes this and a few more things

**Comment by astridx** [comment]
With this patch I neither see the warning  in the console of the browser nor in the javascript tests. So it is fine.
But I wonder where the file /media/system/js/polyfills/webcomponents/webcomponents-ce.js comes from. Is it a special file for Joomla! ?

**Comment by astridx** [comment]
Close as there is PR: https://github.com/joomla/joomla-cms/pull/19484
