### ISSUE TITLE
3.8.4  - Contacts  -  Issue with Custom Field  -  Link displayed incorrectly

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#19494]
### Steps to reproduce the issue
Under Components  - Contacts create a field group of type Mail ![screen shot 2018-01-30 at 20 44 22](https://issues.joomla.org/uploads/1/7dd16766fcbb7a40125e256b76b45117.jpg)
In tab General set Status to Published and Access to Public![screen shot 2018-01-30 at 20 45 36](https://issues.joomla.org/uploads/1/fbed3fa243b7785439f79a09727f9c2e.jpg)
In tab Permissions set Edit Own to Allowed![screen shot 2018-01-30 at 20 46 31](https://issues.joomla.org/uploads/1/bce00db86d57d6cf52459aa8e1bcc538.jpg)
Save & Close
In Contacts: Fields create a field of type Mail
In tab General: Set Type to Checkboxes, fill in a Title, set Required to Yes, set Status to Published, set the field group to the one just created, click the + sign under Checkbox Values
In field Text, add something with an a-HTML tag 
In field Value add anything![screen shot 2018-01-30 at 20 53 35](https://issues.joomla.org/uploads/1/4e6a8106f884ed0c96af2f09c6b82873.jpg)
In tab Options: Set Show Label to Show, set Show On to Site![screen shot 2018-01-30 at 20 54 51](https://issues.joomla.org/uploads/1/c9ce400ea2f1a2fc9f80e0b784a6425d.jpg)
In tab Permissions set Edit Custom Field Value to Allowed![screen shot 2018-01-30 at 20 56 00](https://issues.joomla.org/uploads/1/e140d33a68d7e276c186ff8b052b7698.jpg)
Save & Close

Go to the Contact form in the frontend
Look at the field group and the field at the bottom of the form![screen shot 2018-01-30 at 20 57 31](https://issues.joomla.org/uploads/1/97048b2b71137223ecfae1532e6e2b02.jpg)

### Expected result
The text displayed next to the checkbox should contain a link to some other page.

### Actual result
The text does not contain a link, but the respective HTML code

### System information (as much as possible)
3.8.4, some common extensions like JCE, Akeeba Backup, Phoca Maps

### Additional comments
Error can be reproduced on all my sites already on 3.8.4

**Comment by mbabker** [comment]
See https://docs.joomla.org/Special:MyLanguage/J3.x:Joomla_3.8.4_Notes_about_the_Security_Patches for information on this change.

**Comment by ghost** [comment]
Closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19494">issues.joomla.org/tracker/joomla-cms/19494</a>.</sub>

**Comment by simbus82** [comment]
Solving a security problem cutting down a features without proposing a workaround is not a good thing...

Now, how we can manage the click on a link with terms or privacy policy? This is a MUST, here in EU we must give this link near privacy or terms checkboxes.

Lot's of website use HTML in label or text/value, now they are all broken...

**Comment by nuipec** [comment]
I was facing the same issue, but then I have found the following extension: https://extensions.joomla.org/extension/bit-linked-checkboxes/

It was easy to set up, and provides a flawless solution for the problem above. Hope it helps others as well...

**Comment by dautrich** [comment]
Tom Möller has prepared an extension for that issue, too. You can find the tutorial (only in German, but shouldn't be too difficult to understand) under that link: https://forum.joomla.de/thread/4785-wie-erstelle-ich-eine-datenschutz-checkbox-inklusive-link-zum-datenschutzhinweis/.
This is what I use on my websites.
