### ISSUE TITLE
How do I build an installer from Downloading J!4 Source

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#19492]
Sorry to ask this, but there's no documentation. Not an issue but rather a question.

1. What's the command to create a package for installation from downloading or cloning J!4 branch?

2. I've installed J!4 Alpha1 like a moth ago but wanter to take advantage of the new updates to the code, how do I go about that? Hence my #1 question. 

Thanks!

**Comment by mbabker** [comment]
Use the nightly builds for "production" packages - https://developer.joomla.org/nightly-builds.html

If you've got a git clone of the repo, just checkout the `4.0-dev` branch and periodically `git pull` to retrieve updates.

**Comment by brianteeman** [comment]
Closed as answered

**Comment by frogydiak** [comment]
Thanks both!
