### ISSUE TITLE
Cannot connect to downloads.joomla.org (again)

### ISSUE THREAD

**Issue by aubreybox** [joomla/joomla-cms#19491]
https://github.com/joomla/joomla-cms/issues/19469 Problem occurs again, but issue was closed without any hint to prevent that blocking

**Comment by mbabker** [comment]
There aren't any hints to give without telling what security configuration rules in ModSec you're possibly triggering.  This could be anything from too many requests to questionable user agents on requests to some kind of IP block based on collected data from other sources.  We can ask your IP unblocked again if that's the issue but if your activity keeps triggering the firewall rules then something needs to change.

**Comment by brianteeman** [comment]
In any case this is not the place to report the issue as it is an infrastructure issue and not an issue with the ore code. The correct place would be https://github.com/joomla/joomla-websites/issues/new?title=%5Bjdown%5D%20
