### ISSUE TITLE
Joomla 3.8.4 breaks JoomShopping Login [solved]

### ISSUE THREAD

**Issue by pak7** [joomla/joomla-cms#19502]
### Steps to reproduce the issue
Use SSL redirect in .htaccess
Configure Joomla -> Configuration -> Server -> HTTPS -> Enable Site

Worked with Joomla 3.8.3

### Expected result
Successful Login to JoomShopping

### Actual result
endless Redirection LOOP

### System information (as much as possible)
Joomla 3.8.4
JoomShopping 4.16.3
JoomShopping Login Module 4.0.2
PHP 7.0.27
5.5.5-10.1.30-MariaDB
Linux 3.10.0-693.11.6.el7.x86_64

### Additional comments
Deactivate SSL in Joomla and just use .htaccess

**Comment by Quy** [comment]
I assume by the title that this is no longer an issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19502">issues.joomla.org/tracker/joomla-cms/19502</a>.</sub>
