### ISSUE TITLE
Calendar fields inside repeatable fields don't work when added using the top [+] button on an existing field

### ISSUE THREAD

**Issue by aDaneInSpain** [joomla/joomla-cms#19500]
### Steps to reproduce the issue
1. Create a component with a repeatable calendar field or install the attached component. [com_repeteable-1.0.0.zip](https://github.com/joomla/joomla-cms/files/1681538/com_repeteable-1.0.0.zip)
2. Add two or more calendar fields
3. Click save and Close
4. Edit the field again
5. Add another calendar field by clicking the top green plus button
6. Attempt to select a date in the newly added field

![image](https://user-images.githubusercontent.com/4998032/35621517-de9310d6-0684-11e8-9f77-8f55b089ada4.png)

### Expected result
The date selector shows

### Actual result
Nothing happens. The date selector does not load

### System information (as much as possible)
Joomla 3.8.3
Example component created with Component Creator

### Additional comments
Please note that clicking on the top green [+] button when _first_ adding fields works. It is only when editing the item that the problem occurs.

Please also note that clicking on the green [+] buttons next to existing fields _does_ work.

**Comment by prandini** [comment]
I'm face almost the same problem, 
when I click on top [+] button to add new row, just one row is add, and the others buttons [+] and [-] does not work anymore.

To fix i chose the layout, layout="joomla.form.field.subform.repeatable", it's no the best solution but works fine for me.

@aDaneInSpain did you find some solution for your issue?

**Comment by Quy** [comment]
Similar to #16480.

The first `+` button creates a row with `X` in the id `jform_datesselect__datesselectX__init_date`.
The other `+` buttons create rows correctly with id incremented `jform_datesselect__datesselect2__init_date`.

@Fedik Can you please take a look? Thanks.

**Comment by Fedik** [comment]
there is a fix #19774
