### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by tranchau1991** [joomla/joomla-cms#19508]
affter run install i get error
it stop install
Joomla_3.8.4-Stable-Full_Package.zip and
Joomla_3.8.2-Stable-Full_Package.zip

![Image of Yaktocat](https://i.imgur.com/bYddUKM.png)

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.

**Comment by tranchau1991** [comment]
close
https://docs.joomla.org/J3.x:Installing_Joomla#References

**Comment by florahwilliams** [comment]
Business management coursework writing service learners have an advantage of hiring the best business research writing service that is familiar with business term paper writing services for their [Business Essay Writing Services](https://topessaywriting.com/business-essay-writing-services/ "Business Essay Writing Services").  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19508">issues.joomla.org/tracker/joomla-cms/19508</a>.</sub>
