### ISSUE TITLE
URL Structure changed after updating to Joomla 3.8.4

### ISSUE THREAD

**Issue by petmug** [joomla/joomla-cms#19505]
### Steps to reproduce the issue
I recently updated to joomla 3.8.4 from 3.8.3.

This affected the urls that were linked recently from around six  months ago. The old urls same way generated are still okay..

### Expected result

http://www.researchtopichelp.net/2-topic-help/18-dba-new-research-ideas

### Actual result
http://www.researchtopichelp.net/component/content/article/2-topic-help/18-dba-new-research-ideas

### System information (as much as possible)

joomla 3.8.4 updated yesterday

### Additional comments
the addition of "/component/content/article" is the issue.

Please any help urgently before i get lots of 404 pages

Thanks

**Comment by OctavianC** [comment]
Please see #19497 (it's a long read) and could you test if #19498 solves your issue?

**Comment by petmug** [comment]
I did that and i get a url with 

"menu-alias" instead of the "/component/content/article" 

That still creates a new link that is not resolving my issue... then 

1. why is it that the old article urls not affected?/
2. If I have to have all new URls then my old URLs that are indexed will be lost and that will hurt my SEO
3. Is there a way I can retain my old urlS AS THEY WERE?
Thanks

**Comment by csthomas** [comment]
You can create (instead "menu-alias") menu item "Category Blog" or "Category List" for your category "topic help" with alias "2-topic-help".

**Comment by petmug** [comment]
Hi, thanks.. that resolves the articles in the category topic help, how about the articles in the other categories, or i repeat the same procedure and use the respective category alias as well..
Last question, will the old urls at some point start getting affected? 
Thanks for your help.

**Comment by csthomas** [comment]
Usual folks do not create a menu item for category with alias like "2-topic-help" but only "topic-help".
But for you this is probably not a solution.

If you have more top categories without any menu item then the simplest way is to repeat the procedure.

**Comment by petmug** [comment]
let me deal, if i face any issues I will contact... I just dread future updates that would mess all this.. I just want to retain my urls TO AVOID hurting SEO..

Thanks alot..

**Comment by ghost** [comment]
closed as Issue solved; it can always reopened if needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19505">issues.joomla.org/tracker/joomla-cms/19505</a>.</sub>

**Comment by petmug** [comment]
Hello, the trick is working for articles under categories but not those under subcategories.
Am stuck

**Comment by petmug** [comment]
Is there no remedy for this issue or it means we just have to get new structured urls...

**Comment by ghost** [comment]
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19505">issues.joomla.org/tracker/joomla-cms/19505</a>.</sub>

**Comment by csthomas** [comment]
You can use component redirect in joomla or you can add a redirect command in `.htaccess` file.

> Is there no remedy for this issue or it means we just have to get new structured urls...

In 3.8.4 there is a "new structured urls", which is correct, but they are different that links from 3.8.3.

In the next version 3.8.5 this changes will be (in 99%) reverted 
and IMO Joomla will have to live longer with incorrect (from the technical point of view) generated links (as before 3.8.3).

**Comment by petmug** [comment]
I kindly need your help with the kind of redirect command that I can add in .htaccess file. 
As I wait for 3.8.5 release.

 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19505">issues.joomla.org/tracker/joomla-cms/19505</a>.</sub>

**Comment by petmug** [comment]
and the redirect command that can handle all urls and remove the ""/component/content/article" part in the new redirected URLs..<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19505">issues.joomla.org/tracker/joomla-cms/19505</a>.</sub>

**Comment by joomdonation** [comment]
@csthomas Is the PR #19512 solve this issue, too? If Yes, I think @petmug can apply that PR using com_patchtester instead of waiting for 3.8.5

**Comment by csthomas** [comment]
> Is the PR #19512 solve this issue, too? 

Yes, it may be the simplest way.

**Comment by csthomas** [comment]
General advice:

   For each article in the category tree, where neither (category) has its own menu item, and the article 
   does not have its own menu item, there may always be a problem with positioning and duplicate URLs.

**Comment by petmug** [comment]
I totally agree on your advice above; Infact I started seeing the effect months ago and bought some extensions.. what is then the long term best suggestion.. for consideration. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19505">issues.joomla.org/tracker/joomla-cms/19505</a>.</sub>

**Comment by brianteeman** [comment]
Closed as the routing changes have been reverted for 3.8.5 with #19512

**Comment by petmug** [comment]
Hello, I am, back again with some observation. I created menu items for my categories (category list) under which my articles are grouped. (meaning each article has a menu item id of the category.
I used the modern routing option in articles integration option..

This is my challenge, any link I anchor or link up now is showing okay e.g
Link a) https://www.petrianeditingservice.co.uk/capstone-correction/review-assistants 

but those links that were existing never are showing a new structure UNLESS i un-link and link them again...

they look like 
Link b) https://www.petrianeditingservice.co.uk/?view=article&id=46:review-assistants

Link a and b are same article, one is showing in some pages and the other in others...

What should I do to correct this?
Any automatic way to update the urls rather that manual un-linking and re-linking?

Peter

**Comment by petmug** [comment]
with further research

**old url are** 
index.php?option=com_content&view=article&id=48:editing-helpers&catid=17**:research-proposal&Itemid=101**

**New ones are like...**
index.php?option=com_content&view=article&id=48:editing-helpers&catid=17

Is there a way I can automatically update and remove the **:research-proposal&Itemid=101** which is the homepage item it + alias on all the older links..

Peter

**Comment by ghost** [comment]
@petmug please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding, thanks.

**Comment by florahwilliams** [comment]
To seek the best [Healthcare Assignment Writing Services](https://topessaywriting.com/healthcare-assignment-writing-services/ "Healthcare Assignment Writing Services") for those studying healthcare coursework writing services, it is important to hire an award winning healthcare essay writing service company.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19505">issues.joomla.org/tracker/joomla-cms/19505</a>.</sub>
