### ISSUE TITLE
Router Issues in 3.8.4

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#19504]
Guys we are all wasting a lot of time on this in various places. Before going any further it would be good to get some clarity from the CMS Maintainers and Release Leads. If it is going to be reverted in full or if it is going to be patched

**Comment by mbabker** [comment]
I'm on company travel for the next day and a half and really won't have time to look at whatever is going on.  So someone who has more availability needs to jump in here.

**Comment by brianteeman** [comment]
so my 2c having now read the intended behaviour of the offending pull requests is that they were based on a faulty assumption about inheriting itemid. 

it has always been behaviour of joomla that if there is no itemid then the referring itemid will be used. as a result the pr have been created so that if there is no matching or explicit itemid no itemid will be used. this means that only the default template will be used, only modules set to all pages will be displayed and the url name will be based on the component name.

assuming that my summary above is correct then this has to be reverted in 3.8.5 as at the very least it is a backwards compatibility break which shouldnt happen in a patch  release if it should ever happen at all.

**Comment by csthomas** [comment]
There are all changes related to that problems https://github.com/joomla/joomla-cms/compare/staging...csthomas:routing_revert?expand=1

**Comment by rdeutz** [comment]
If it is a b/c breakt then it has to reverted, not so much to discuss here. The bigger question is, is this so urgent to create a new release very soon.

**Comment by OctavianC** [comment]
If I can weigh in on this, we've already had 15 support requests regarding this in our private ticketing system (concerning multiple extensions...) and there will be more as more people update.

**Comment by OctavianC** [comment]
Ups, those were just the already answered requests; I can spot 3 more unanswered in the queue. So yes, it's a pretty big deal at least for me.

**Comment by ghost** [comment]
+1 for soon Release. Better People moan about one more Update than about b/c-Break.

**Comment by Bakual** [comment]
> The bigger question is, is this so urgent to create a new release very soon.

I fear it is, yes.

**Comment by ghost** [comment]
Tyring to fixing this router issues I tried a downgrade manually, now I'm in panic, no matter if I re-unzip the joomla full package over my webroot, I get:

`[01-Feb-2018 10:47:12 Europe/Berlin] PHP Fatal error:  Call to undefined method JVersion::isInDevelopmentState() in .../administrator/includes/framework.php on line 30`

**Comment by rdeutz** [comment]
Do you have a backup?

**Comment by ghost** [comment]
I tried to restore a version I'd backuped with git, but no way to make it work

**Comment by csthomas** [comment]
I suggest to back to J3.8.4, install com_patchtester and apply this PR #19512.

**Comment by cavo789** [comment]
@csthomas PR #19512. installed on my server and problem solved. Thanks.

(It was impossible anymore to log in on the frontend on my multilingual website; ERR_INVALID_REDIRECT just after the submission of the log in screen. With #19512 applied, problem solved)

By the way, thanks for this quick PR and thank you @mbabker for com_patchtester; so easy to use and so powerfull (get the list, select PR, apply, it's done). 💯 🥇

**Comment by ggppdk** [comment]
So this fix is not enough ?
https://github.com/joomla/joomla-cms/pull/19498

i mean the problem is ?only? with URLs
JRoute::_('index.php?option=com_customcomponent...')
aka routing URLs without Itemid 

and the B/C break of the above are these 2 cases ??

- select current menu item if option matches (fixed by 19498) ?
- select home page menu item if its option matches and current menu item does not have a matching option (is this broken ? or this case does not exist ?)
- other ?

Sorry we do not rely on JRoute to select menu item, as almost always all URLs are handled by component router code that adds an Itemid before passed to JRoute, so we missed this breaking while testing J3.8.4-rc

**Comment by ggppdk** [comment]
Ok
i see that the B/C break is described here ?
https://github.com/joomla/joomla-cms/issues/19537

**Comment by brianteeman** [comment]
Closed as the changes have been reverted now
