### ISSUE TITLE
URL to archived articles changed after update to 3.8.4

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#19513]
### Steps to reproduce the issue
I did an update from 3.8.3 to 3.8.4. After that the links to archived articles - such as https://www.xyz.at/archiv/09-rubrik/abc/191-test-2016 dont´t get the archived article but the view 'archived articles'.

The Url to get to an archived article changed to https://www.xyz.at/component/content/article/09-rubrik/abc/191-test-2016

**Comment by joomdonation** [comment]
Could you please check to see whether the PR https://github.com/joomla/joomla-cms/pull/19512 solve your issue?

**Comment by waader** [comment]
PR #19512 doesn´t  solve the problem.

**Comment by Quy** [comment]
@waader Please test #19561.

**Comment by Quy** [comment]
Fixed/reverted in #19561.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19513">issues.joomla.org/tracker/joomla-cms/19513</a>.</sub>
