### ISSUE TITLE
Joomla 3.8x MenuRules ignores layout attribute - Bugfix included

### ISSUE THREAD

**Issue by RubbelDeCatc** [joomla/joomla-cms#19515]
### Steps to reproduce the issue
Create two menu entries listing categorise with subcategories.
One is layout print one layout default.
**index.php?option=com_content&view=categories&id=9
index.php?option=com_content&view=categories&layout=print&id=9**

### Actual result
The router picks always the print layout item because 
this entry was added last to the menu table.

This problem will afflict every component if 
entries with same attributes but different layouts
exist.

### System information (as much as possible)
Issue exist since 3.5 or whenever the router was changed.

### Solution / Fix

The issue is caused by a unnecessary simplification in
the **buildLookup** function of **MenuRules.php**
```
$this->lookup[$language][$view . $layout][$item->query[$views[$view]->key]] = $item->id;
$this->lookup[$language][$view][$item->query[$views[$view]->key]] = $item->id;
```
and
```
$this->lookup[$language][$view . $layout] = $item->id;
$this->lookup[$language][$view] = $item->id;
```

I don't understand why both keys are set. It is completely unnecessary. 
**You can safely remove these two lines because $layout is always set.**
```
$this->lookup[$language][$view][$item->query[$views[$view]->key]] = $item->id;
```
and
```
$this->lookup[$language][$view] = $item->id;
```

**Comment by ghost** [comment]
Can you please look at https://issues.joomla.org/tracker/joomla-cms on Issues labeled "Router / SEF" started by "Opened 2018-01-30" if this is a duplicate Report?

**Comment by Quy** [comment]
See PR #19516<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19515">issues.joomla.org/tracker/joomla-cms/19515</a>.</sub>
