### ISSUE TITLE
Joomla visitors module showing a growing visitors amount.

### ISSUE THREAD

**Issue by Handy84** [joomla/joomla-cms#19521]
### Steps to reproduce the issue

visit the Joomla 3.8.4 site with various browsers the amount of visitors will increase but never drops back.
Php version curently running 7.1.13

I have detected this issue on various recently updated Joomla sites...

### Expected result

The visitors amount displayed in the users online module equals the actual sessions open.

### Actual result

It seems that the amount of visitors only will increase over time I see numbers of 600+ !

### System information (as much as possible)
Php version curently running 7.1.13
installed Joomla version: 3.8.4
Joomla! 3.8.4 Stable [ Amani ] 30-January-2018 15:00 GMT
Database version: 5.5.5-10.0.29-MariaDB-cll-lve
Joomla Platform version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments
A .htaccess construction is inplace to prevent backend visit's.

The issue appears on various templates and sites, also on the Breez3 standard template.

My session tables are growing larger as well...

**Comment by alikon** [comment]
should be fixed by #19514

**Comment by csthomas** [comment]
If your session handler is database and value of `ini_get('session.gc_probability');` is equal to 0 then php won't clear your database table `#__session` at all.

**Comment by csthomas** [comment]
See http://php.net/manual/pl/session.configuration.php#115842

**Comment by Handy84** [comment]
@csthomas Thanks for your comments. Indeed php is not clearing my database table so I wrote my own cronjob to do this.
The suggested code does not seem to work.
