### ISSUE TITLE
[4.0] Cannot install sample data

### ISSUE THREAD

**Issue by josflachs** [joomla/joomla-cms#19523]
### Steps to reproduce the issue
Install Joomla 4 
Select install sample data 
Joomla installer keeps installing sample data. 
No results. (After 5 minutes I give up)

### Expected result
See sample data

**Comment by Quy** [comment]
Please make sure you are testing the latest development branch: https://github.com/joomla/joomla-cms/tree/4.0-dev

**Comment by josflachs** [comment]
I just installed the dev you recommended, same result. The progress box works, but nothing happens.

**Comment by josflachs** [comment]
That solved the problem, thanks!
