### ISSUE TITLE
[4.0] CodeMirror does not work

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-cms#19532]
### Steps to reproduce the issue
- Set code mirror as default editor
- Edit an article on the front end

### Expected result
Article is editable.

### Actual result
Javascript error.

![image](https://user-images.githubusercontent.com/251072/35718732-1f5ceada-07e6-11e8-93a3-d1124c558186.png)

### System information (as much as possible)
Joomla 4

**Comment by dgrammatiko** [comment]
I guess this is my fault, probably coming from the pr that dropped grunt, will check the code later on

**Comment by brianteeman** [comment]
Closed as we have a pr
