### ISSUE TITLE
[4.0] Editing files in com_template

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#19549]
### Steps to reproduce the issue
Open template manager 
Extensions | Templates | submenu template | choose a template 
and try to change a file. For example the file error.php

### Expected result
You see the text of the file and you can edit it.

### Actual result
You see an empty text box.

### System information (as much as possible)
current 4.0-dev branch on Ubuntu

**Comment by ghost** [comment]
Can't confirm:

![bildschirmfoto 2018-02-03 um 10 28 57](https://user-images.githubusercontent.com/8235763/35765853-1991a5b8-08cd-11e8-8ad5-9f388c8dd27d.jpg)
### System information
- 4.0-dev
- Sample Data
- Template: Cassiopeia
- macOS Sierra, 10.12.6
- Firefox 58 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by anuragteapot** [comment]
Issue confirmed. On Linux 


![screenshot from 2018-02-03 09-36-50](https://user-images.githubusercontent.com/30978328/35765901-cb5c373e-08c5-11e8-8947-b9062df79f74.png)

**Comment by brianteeman** [comment]
This sounds like a bug loading codemirror for which there is already a patch I believe

**Comment by anuragteapot** [comment]
#19534 Fix this issue @astridx Please test this PR.
