### ISSUE TITLE
Too Many Redirects - 3.8.4 COOKIE PROBLEM?

### ISSUE THREAD

**Issue by rotech1** [joomla/joomla-cms#19546]
### Steps to reproduce the issue
visit the website

### Expected result
site works perfectly, as it did right thru 3.8.3

### Actual result
This page isn't working
has redirected you too many times
Try clearing your cookies
ERR_TOO_MANY_REDIRECTS

### System information (as much as possible)
Joomla 3.8.3  PHP 7.1

### Additional comments
Is this perhaps  related to the "router issues" ?? And the reports of users never being logged out?

We recently upgraded our site to https:// 
Everything working fine the last few weeks.

But since 3.8.4 update, some users are getting "too many redirects" when they access the site from older http:// links.  First reported by a user who was clicking old archived forum post notices from months ago.  (update - can happen also directly from https:// links!) Once that is triggered the error subsequently continues with ANY url.

SO FAR I'm not able to reproduce the issue on any Mac, but some PCs with Chrome and Firefox, I can. (And then have to delete site cookies to clear it) 
It's not "reliable" though, seems to be  only once in a blue moon... Reported 4 times today!
![sessionsettings](https://user-images.githubusercontent.com/5864531/35760764-4aa387ac-0837-11e8-8062-9d92f4e59731.png)

**Comment by ReLater** [comment]
To test if it's related to the router issue:
- Install latest stable release of https://github.com/joomla-extensions/patchtester/releases
- Click button "Load data" (or similiar)
- Apply patch Pull-ID 19512 ("Revert routing changes in 3.8.4")

**Comment by ghost** [comment]
closed as known Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19546">issues.joomla.org/tracker/joomla-cms/19546</a>.</sub>
