### ISSUE TITLE
[4.0] Wrong message alert text in search.

### ISSUE THREAD

**Issue by anuragteapot** [joomla/joomla-cms#19550]
### Steps to reproduce the issue

Write a new article -> insert menu  -> search anything which was not present 
in menu search.

### Expected result
<code>No Matching Results</code>

### Actual result
<code>COM_LANGUAGES_MULTILANGSTATUS_NONE</code>
![screenshot from 2018-02-03 09-48-23](https://user-images.githubusercontent.com/30978328/35766012-6cd0162a-08c7-11e8-800d-73aad4c3936c.png)

### System information (as much as possible)
Linux

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19550">issues.joomla.org/tracker/joomla-cms/19550</a>.</sub>

**Comment by C-Lodder** [comment]
@infograf768

**Comment by infograf768** [comment]
i have already proposed a pr to solve this and more
https://github.com/joomla/joomla-cms/pull/19076

**Comment by ghost** [comment]
closed as having Pull Request #19076
