### ISSUE TITLE
[4.0] Page elements (toolbar, table,...) on small device

### ISSUE THREAD

**Issue by todordev** [joomla/joomla-cms#19553]
### Steps to reproduce the issue
Test the views of the extension Content on small device via Google Chrome Developer Tools.

### Actual result
There is a problem with the elements on small device.

![small_device](https://user-images.githubusercontent.com/1272206/35769760-8f7459ce-0918-11e8-9699-cb78d70bdbda.png)

**Comment by brianteeman** [comment]
this is not the final template or ui
please see https://magazine.joomla.org/issues/issue-nov-2017/item/3289-episode-iv-a-new-user-interface-for-the-joomla-backend

**Comment by brianteeman** [comment]
I am going to close this as stated above its not the final template
