### ISSUE TITLE
ampersand (&) in URL is displayed as HTML entity name

### ISSUE THREAD

**Issue by reburg67** [joomla/joomla-cms#19557]
### Steps to reproduce the issue
If Search Engine Friedly URL is switched off, I get URL of this kind:
```/index.php?option=com_wrapper&amp;view=wrapper&amp;Itemid=226```

### Expected result
The URL should look like this
```/index.php?option=com_wrapper&view=wrapper&Itemid=226```

Normally that does not make troubles.
But if the menu item of that URL is an I**frame Wrapper** the page is not loaded into the iframe.

### System information
Apache2, Suse 42.3, Joomla 3.8.4

**Comment by Quy** [comment]
`&` should be encoded as `&amp;` in URL. I am able to load a page with `&` and `&amp;` in an iframe wrapper. Please try to load the page without the query portion to see if you can load the page.

**Comment by Quy** [comment]
Closing as not reproducible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19557">issues.joomla.org/tracker/joomla-cms/19557</a>.</sub>
