### ISSUE TITLE
[4.0] Parent Item is not selectable

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#19556]
### Steps to reproduce the issue
Create a menu item and give this menu item a Parent Item.

### Expected result
You can choose the parent item within a drop down list.

### Actual result
You have to insert the id of the parent item in a text field

### System information (as much as possible)
ubuntu with the current 4.0-dev branch

### Additional comments

![menus edit item testjoomla4 administration](https://user-images.githubusercontent.com/9974686/35771575-7bc06514-092f-11e8-806f-9334c83bb58b.png)

**Comment by ReLater** [comment]
Confirmed.

Already reported? (but @astridx  's test instructions are clearer than in other issues):

https://github.com/joomla/joomla-cms/issues/18633
https://github.com/joomla/joomla-cms/issues/19526

**Comment by ghost** [comment]
Works as expected:

![bildschirmfoto 2018-02-04 um 07 39 47](https://user-images.githubusercontent.com/8235763/35774948-aa6cf41e-097e-11e8-94f6-75b66bf07587.jpg)
### System information
- 4.0-dev
- Sample Data
- Template: Cassiopeia
- macOS Sierra, 10.12.6
- Firefox 58 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by astridx** [comment]
Close as there is already an issue open. Sorry, I did not see that.

**Comment by ReLater** [comment]
@franz-wohlkoenig 

> Works as expected:

You have to create an new menu item. If a menu item is already saved (or from demo datas) it works as expected.

**Comment by ghost** [comment]
@ReLater new Menu Item, Type "Featured Articles" works as expected:

![bildschirmfoto 2018-02-04 um 18 08 33](https://user-images.githubusercontent.com/8235763/35780061-875d25c2-09d6-11e8-9d8a-e9326db69c6a.jpg)

**Comment by ReLater** [comment]
Hm, strange. Tested again.

![04-02-_2018_18-13-24](https://user-images.githubusercontent.com/20780646/35780134-82b8d77c-09d7-11e8-9ed9-cf104007c43f.jpg)

I will make a complete new installation of a nightly build these days. Will see.

**Comment by ghost** [comment]
Installed yesterday using Branch 4.0-dev.
