### ISSUE TITLE
JFormFieldText incorrect value for inputmode attribute

### ISSUE THREAD

**Issue by mojazz** [joomla/joomla-cms#19563]
### Steps to reproduce the issue

Define a textfield in XML that includes inputmode

    <field name="amount" type="text" default="" label="Amount" description="Amount" hint="Amount" class="form-control" inputmode="numeric" />

### Expected result

    <input type="text" name="jform[amount]" id="jform_amount"  value="" class="form-control"     placeholder="Amount"     autocomplete="off"      inputmode="numeric"  />

### Actual result

    <input type="text" name="jform[amount]" id="jform_amount"  value="" class="form-control"     placeholder="Amount"     autocomplete="off"      inputmode=" inputmode="numeric""  />

### System information (as much as possible)

Joomla! 3.8.4
PHP 7.1.13
Apache/Linux

### Additional comments

In order for this to work as expected for my component, I have overridden for now JFormFieldText to change Line 266 from:

    $inputmode    = !empty($this->inputmode) ? ' inputmode="' . $this->inputmode . '"' : '';

to:

    $inputmode    = !empty($this->inputmode) ? $this->inputmode : '';

I have not yet looked at other field types for how they handle inputmode

**Comment by mbabker** [comment]
Just at a glance, it looks like you're doing it wrong in the XML.  Your XML field element should just do `inputmode="numeric"`, it seems like you've got `inputmode=" inputmode="numeric""` in your definition.

**Comment by mojazz** [comment]
As above, this is the XML:

		<field name="amount"
			type="text"
			default=""
			label="Amount"
			description="Amount"
			hint="Amount"
			class="form-control"
			inputmode="numeric"
		/>

And if I had it incorrect in the XML, the override would make no difference.

**Comment by mojazz** [comment]
Upon digging further, inputmode attribute HTML is set in JFormFieldText::getLayoutData() (Line 266)

$inputmode    = !empty($this->inputmode) ? ' inputmode="' . $this->inputmode . '"' : '';

AND in the text field layout file "layouts\joomla\form\field\text.php" (Line 74)

    !empty($inputmode) ? 'inputmode="' . $inputmode . '"' : '',

It seems to me that it should be defined in one place or the other, not both.

**Comment by Quy** [comment]
See PR #19632<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19563">issues.joomla.org/tracker/joomla-cms/19563</a>.</sub>
