### ISSUE TITLE
how to add new theme in joomla

### ISSUE THREAD

**Issue by ganeshghule2010** [joomla/joomla-cms#19567]
### Steps to reproduce the issue

easy add template in joomla

### Expected result

not found in option in joomla

**Comment by ganeshghule2010** [comment]
plz help me for add to new theme in joomla<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19567">issues.joomla.org/tracker/joomla-cms/19567</a>.</sub>

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.

Please don't open Issues like #19566, they belong to Forums as stated above, thanks.
