### ISSUE TITLE
how to add new theme in joomla

### ISSUE THREAD

**Issue by ganeshghule2010** [joomla/joomla-cms#19566]
### Steps to reproduce the issue

how to add template in joomla

### Expected result

direct premium template add in joomla

### Actual result
not found any option

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.

**Comment by ganeshghule2010** [comment]
how to add new theme in joomla framework<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19566">issues.joomla.org/tracker/joomla-cms/19566</a>.</sub>
