### ISSUE TITLE
[4.0] Allow .SVG logo selection in Templates via Administrator Backend

### ISSUE THREAD

**Issue by iantrudell** [joomla/joomla-cms#19565]
### Steps to reproduce the issue

Extensions > Templates > Styles > Edit Style in the Joomla 4 Backend

Click the Advanced tab and then choose "Select" to change the template logo. Any .SVG file will not be listed as an available option, even if one is available.

**Comment by ghost** [comment]
Closed as duplicate Report, please look at #18373.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19565">issues.joomla.org/tracker/joomla-cms/19565</a>.</sub>
