### ISSUE TITLE
After joomla update 3.8  i face missing management tabs in modules.

### ISSUE THREAD

**Issue by mohzain** [joomla/joomla-cms#19569]
### Steps to reproduce the issue
i upgrade to joomla 3.8. after accessing any module i found no control tabs in the module, i can't assign module to pages  or access details tab.

### System information (as much as possible)
<img width="1623" alt="screen shot 2018-02-05 at 11 40 28 am" src="https://user-images.githubusercontent.com/36153831/35797976-78390a88-0a72-11e8-9d5b-89569227b647.png">

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
