### ISSUE TITLE
jdiction 2.1.0 joomla 3.8.4&3.8.5 dev error

### ISSUE THREAD

**Issue by knackko** [joomla/joomla-cms#19568]
### Steps to reproduce the issue
Joomla 3.8.5 dev
Jdiction 2.1.0 activated
One or more User fields
Users » Edit User Profile

### Expected result
Edit user profile

### Actual result
* Edit user profile (FR or EN): 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND referenceTable='' AND idLang='2'' at line 4

Edit user profile is OK when user fields are deactivated !

### System information (as much as possible)
OS Linux k
PHP 7.1.13-1+ubuntu16.04.1+deb.sury.org+1
MySQLi 5.7.21-0ubuntu0.16.04.1
Time 10:26
Caching Enabled
Gzip Enabled

Test | Result
-- | --
 
Version | Library Version: 2.1.0                               
Joomla Version 3.8.5-rc is unkown.
Plugin | Joomla Languagefilter Plugin is enabled                              
JDiction Plugin is enabled.
Database | jDiction Database Driver XML View is selected
Language | Seam to be good
Module | Module is enabled
Common mistakes | At least one content item has the language set not to ALL.

### Additional comments
It appears after 3.8.4 update, tried 3.8.5 dev, is there anybody else in that case with jdiction?

**Comment by HLeithner** [comment]
Hi,

not really the correct Bugtracker ;-) 
I will answer you in the forum. 
https://forum.jdiction.org/index.php?topic=1225.new#new

please close the issue here.

**Comment by knackko** [comment]
OK,
I hesitate on where to create the issue as joomla 3.8.4 brings some issues regarding routing and language filter, it messes my website. With 3.8.5 dev it is better, now it seems that the problem I encounter is only when editing user profile with user fields.
