### ISSUE TITLE
Show sub-menu items set to yes, does not show them

### ISSUE THREAD

**Issue by chrisgdclarke** [joomla/joomla-cms#19562]
### Steps to reproduce the issue
Make a new module type menu
Select start level 3 and end level all
Have base item as level 2 menu item
Select yes for Show sub-menu items

### Expected result
Menu should show at front end fully expanded with all sub-menus levels 3 and 4 listed with no hover sub-menus or side menus.

### Actual result
only level 3 items shows with arrows to side to click to view sub-menu.

### System information (as much as possible)
Joomla 3.8.4

### Additional comments
I discovered this when adding a menu item.
In the module-menu I did not change any settings, simply clicked save.

**Comment by ghost** [comment]
Can't confirm.

Used given "Steps to reproduce the issue" by Module "A Deep Menu" got:

![bildschirmfoto 2018-02-04 um 14 24 49](https://user-images.githubusercontent.com/8235763/35777969-346c8502-09b7-11e8-829b-9050765b8710.jpg)
### System information
- 3.8.5-dev
- Multilanguage Site (4 Lang.) & Test English (GB) Sample Data
- Template: Protostar
- macOS Sierra, 10.12.6
- Firefox 58 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by chrisgdclarke** [comment]
To give further information. I can see that the <li class="deeper" has been changed to <li class="dropdown-submenu" in the parent menu item.  And that <ul class="nav-child unstyled small" has been replaced with <ul class="dropdown-menu".

Is this a change in one of the recent updates?

**Comment by Quy** [comment]
Do you have an override of `/html/mod_menu/default.php`? Can you reproduce it with Protostar template?

**Comment by chrisgdclarke** [comment]
No I looked there first. No override to  `/html/mod_menu/default.php` I'm using T3_bs3_blank template. Do not have Protostar template as option. How can I install and test on single page?

**Comment by Quy** [comment]
This is the behavior of T3_bs3_blank template and not with Joomla. Please post to http://www.t3-framework.org/discussions.html for assistance on changing its presentation.
![t3](https://user-images.githubusercontent.com/368084/35884926-0c7a1678-0b41-11e8-8d23-017780314a7a.jpg)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19562">issues.joomla.org/tracker/joomla-cms/19562</a>.</sub>

**Comment by chrisgdclarke** [comment]
So sorry for taking your time, but thank you for pointing me in the right direction! Was getting so frustrated! Really appreciate your insight!
