### ISSUE TITLE
Front end registration failing

### ISSUE THREAD

**Issue by code-s-word** [joomla/joomla-cms#19571]
![screen shot 2018-02-05 at 13 06 14](https://issues.joomla.org/uploads/1/89d177dd2ddbb3e5f7744bf865c116e3.png)### Steps to reproduce the issue

I do not know how this is possible. Of course anyone can go to our website and try to register, and thus have this same issue (https://houseoftruth.education/en/foundation/post-list).

### Expected result

I expected to have "you have registered...."

### Actual result

Actual result is this error/warning (see image above).

### System information (as much as possible)

Tried with chrome, IE and mozilla and have the same result. 
Joomla! 3.8.4 Stable [ Amani ] 30-January-2018 15:00 GMT
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
PHP-versio	5.6.33

### Additional comments

People cannot register to our site. I noticed this problem today, when there were contacts telling me about this problem. I tried to register myself, and had the same problem. I guess this problem occurred after the latest Joomla update. From my hosting service provider was told to me that I should contact here. I have tried to erase the temporary memory, took off the ECC+ - EasyCalcCheck Plus, but nothing seems to help.

**Comment by ghost** [comment]
Can't confirm. 

Frontend-Registration works as expected.
### System information
- 3.8.5-dev
- Multilanguage Site (4 Lang.) & Test English (GB) Sample Data
- Template: Protostar
- macOS Sierra, 10.12.6
- Firefox 58 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by code-s-word** [comment]
How that can be? You didn't get that same message? Although our system doesn't recognize your registration.

Can you also register to the finnish site: (https://houseoftruth.education/fi/perusta/rekisteroidy)

I really would like to have other experiences as well.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19571">issues.joomla.org/tracker/joomla-cms/19571</a>.</sub>

**Comment by infograf768** [comment]
@code-s-word 
This may be related to the routing issue which will be corrected in 3.8.5 to be released very soon.
A RC is already available
See https://github.com/joomla/joomla-cms/pull/19512

**Comment by code-s-word** [comment]
The problem now seems to be even larger. Myself and one other user, that have permission to write and modify articles have experienced the same problem. When we modify article in front end and then save it, there is redirection to the front page and all the work is gone...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19571">issues.joomla.org/tracker/joomla-cms/19571</a>.</sub>

**Comment by infograf768** [comment]
3.8.5 has been released. Please update and then report any issue.

**Comment by code-s-word** [comment]
Works fine! Yes :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19571">issues.joomla.org/tracker/joomla-cms/19571</a>.</sub>
