### ISSUE TITLE
[4.0] Subform Custom Field Move Does not Work

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#19576]
### Steps to reproduce the issue

Create a template (I tested only) for J!4 with a field type subform with multiple true and try to create multiple instance of fields then try to move it but you cannot.

### Expected result
Instance of multiple fields should be sortable else the icon move should not be there

### Actual result
Field clone is not movable

**Comment by C-Lodder** [comment]
Please try testing with this PR applied: https://github.com/joomla/joomla-cms/pull/19184

**Comment by frogydiak** [comment]
@C-Lodder: I would assume that it has not been worked on as in the original post, **make sorting to work** is TODO. The rest of the sort talks about keyboard interaction, which I believe is not relevant. Who uses keyboard to move/sort fields?

**Comment by C-Lodder** [comment]
> Who uses keyboard to move/sort fields?

Some power users and some with certain disabilities.

> make sorting to work is TODO

It has been completed which the checked "checkbox" signifies.

**Comment by Quy** [comment]
@frogydiak As stated, please test PR #19184 and submit your test result. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19576">issues.joomla.org/tracker/joomla-cms/19576</a>.</sub>
