### ISSUE TITLE
Please test this code!

### ISSUE THREAD

**Issue by ztj1993** [joomla/joomla-cms#19570]
```
        $Options = new Joomla\Registry\Registry(['cats' => [1 => '10', 10 => '100']]);
        $Arrays = (array)$Options->get('cats');
        var_dump($Arrays["10"], $Arrays[10]);
        exit();
```
Cannot get a value through a key; What's the matter, please?

**Comment by ztj1993** [comment]
```
        $Options = new Joomla\Registry\Registry(['cats' => [1 => '10', 10 => '100']]);
        $Arrays = get_object_vars($Options->get('cats'));
        var_dump($Arrays["10"], $Arrays[10]);
```
So you can get it, please explain, thank you!

**Comment by OctavianC** [comment]
Nothing to do with Joomla! but how [PHP converts objects to arrays](http://www.php.net/manual/en/language.types.array.php#language.types.array.casting):

If an object is converted to an array, the result is an array whose elements are the object's properties. The keys are the member variable names, **with a few notable exceptions: integer properties are unaccessible;**

See also [this bug report](https://bugs.php.net/bug.php?id=45959)

**Comment by ztj1993** [comment]
@OctavianC Thank you!
