### ISSUE TITLE
Homepage pagination does not add other parameters

### ISSUE THREAD

**Issue by ztj1993** [joomla/joomla-cms#19579]
Today in the development, found that the home page can not add other parameters!

Desired results:
http://domain/?aaa=1
http://domain/?aaa=1&start=10
http://domain/?aaa=1&start=20

The result of the present:
http://domain/?aaa=1
http://domain/?start=10
http://domain/?start=20

Should it be like this?

The above content for software translation!

**Comment by zero-24** [comment]
@ztj1993 can you please try the latest rc version https://github.com/joomla/joomla-cms/releases/tag/3.8.5-rc? As this release contains patches to be released stable today.

**Comment by ztj1993** [comment]
@zero-24 OK, I'm doing more tests, as if this was just the case on the front page, and the other menu pages wouldn't have happened that way.

**Comment by ztj1993** [comment]
@zero-24 It is true that the test does not appear on the front page.

**Comment by zero-24** [comment]
@ztj1993 can you please clarify what you mean? Did the 3.8.5-rc package fixed the problem or not?

**Comment by ztj1993** [comment]
@zero-24 The effect of this problem is not very big now, only a few special cases will be used.

To implement the problem steps:
Please open this page: http://www.portablecn.com/?aa=1
Please pay attention to the URL parameter AA; then click on the next page to see that the AA parameter does not exist.

If the first page to do filtering, this problem will have an impact!

The above content for software translation!

**Comment by ggppdk** [comment]
i have seen this bug, and added a workaround in our pagination code,

When the paginated page is the home page then all URL variables that do not exist in the home page page menu item are lost, thus you can not e.g. paginate a filtered view

The bug is in SiteRouter.php

**Comment by brianteeman** [comment]
Why do you write "workarounds" instead of fixing the issue upstream and help everyone?

**Comment by ghost** [comment]
closed as having Pull Request #19582
