### ISSUE TITLE
Event - onUserBeforeDataValidation

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#19584]
### Steps to reproduce the issue

I was looking for a fields plugin event called when an article using customs fields (com_field) is saved.
I found FormModel::validate() function triggers onUserBeforeDataValidation event.

Adding function onUserBeforeDataValidation($form, &data) to my field plugin produces the functionality I require.

### Expected result

(a) Documentation for the onUserBeforeDataValidation event
(b) A more meaningful event name e.g. onFormModelBeforeDataValidation

### Actual result

(a) I could not find any documentation for this event
(b) Looks like original author for this event was too focused on the user problem they wanted to solve and not thinking of the wider applications of this event.

### System information (as much as possible)

Joomla 3.8.4

### Additional comments

Suggest changing FormModel::validate() function to something like the following:

> if (get_class($this) == 'UsersModelUser') {
>   // Obsolete, kept here for backward compatibility
>   $dispatcher->trigger('onUserBeforeDataValidation', array($form, &$data));
> }
> $dispatcher->trigger('onFormModelDataValidation', array($form, &$data));
>

**Comment by garstud** [comment]
Interesting subject! 
a) The code is located in [/libraries/src/MVC/Model/FormModel.php in line 355](https://github.com/joomla/joomla-cms/blob/staging/libraries/src/MVC/Model/FormModel.php#L355) :

`$dispatcher->trigger('onUserBeforeDataValidation', array($form, &$data));`

There is 2 parameters :
- $form : the form object to validate against
- $data : input data that will be validate after this event

b) I agree, the name of this event should be updated to onForm... or onContent... (like the others triggered events in this class)

**Comment by brianteeman** [comment]
Pull requests are welcome

**Comment by ghost** [comment]
closed as having Pull Request #20152
