### ISSUE TITLE
[4.0] What Replaces Choosen - Select Field?

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#19589]
Is choosen script deprecated in J!4? So what replaces it? Currently, it is using HTML5 default select.

Would be nice to still have the search functionalities. Maybe use this:

http://silviomoreto.github.io/bootstrap-select/

**Comment by brianteeman** [comment]
It won't be that as that would be tied to ootstrap and we want to avoid that. One possibility is awesomplete. There is a other github issue for this.sorry don't remember!bet the number but surcharge for awesomeplete

**Comment by frogydiak** [comment]
@brianteeman maybe [Choices](https://github.com/jshjohnson/Choices)?

**Comment by brianteeman** [comment]
see #22263
