### ISSUE TITLE
[4.0] Helper classes redesign

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-cms#19580]
As discussed in JAB17 we need a plan for the helper classes. At the moment they have the same setup as on J3 and are resting in the root namespace. These classes are mostly magically compiled somewhere outside of the extension itself. For example [here](https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_categories/Model/CategoriesModel.php#L383) is the Helper class of the component loaded and checked if the function exists. We need to have a look case by case how we want to solve it.

There are different ways to achieve that, we were discussing the following approaches:
- Boot functionality of an extension to load its environment
- Through Plugin events
- Service provider for the DI container
- ...

I add here a todo list of known cases where we need to find a solution for:

- [x] [Count item function](https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_categories/Model/CategoriesModel.php#L383) in com_categories 
- [x] ~[Add submenu function](https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/MVC/View/ListView.php#L178) in various places~ In the new design we are removing the submenu
- [x] [AssociationsHelper](https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_associations/Helper/AssociationsHelper.php#L344) who loads the component specific helpers
- [x] [Component specific category class](https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Categories/Categories.php#L142)
- [x] Route helper

The list is by for not complete, the plan is to constantly extend it.

**Comment by laoneo** [comment]
Adding here comments what we do discus in the meeting:

```
// Loads the services in the DI container of the component
// Category model
public function doblabla(JCategories cat = null)
{
    if (!$cat)
    {
        $cat = ComponentHelper::boot($this->option)->get('JCategories');
    }
}

// ComponentHelper
public static function boot()
{
    $container = self::getComponentContainer()->getContainer(JFactory::getContainer());
}
```

Keys:
- Associations
- JCategories
- Router
- Dispatcher

Legacy container which loads categories and associations the old way.

**Comment by mbabker** [comment]
```php

use Joomla\CMS\Association\AssociationExtensionInterface;
use Joomla\CMS\Categories\Categories;
use Joomla\CMS\Component\Router\RouterInterface;
use Joomla\CMS\Dispatcher\DispatcherInterface;

interface ComponentContainer
{
    /*
     * @return AssociationExtensionInterface|null
     * @todo Should support for this be in a separate interface?
     * @throws UnsupportedFeatureException
     */
    public function getAssociations(): ?AssociationExtensionInterface;

    /*
     * @return Categories|null
     * @todo Should support for this be in a separate interface?
     * @throws UnsupportedFeatureException
     */
    public function getCategories(): ?Categories;

    /*
     * @return DispatcherInterface
     * @todo This implies a component doesn't support 3.x structure, is this OK?  I'm not aware of there being a legacy dispatcher implementation similar to the MVC LegacyFactory.
     */
    public function getDispatcher(): DispatcherInterface;

    /*
     * @return RouterInterface|null
     * @todo Should support for this be in a separate interface? Not all components have frontend routing, i.e. com_contenthistory
     * @throws UnsupportedFeatureException
     */
    public function getRouter(): ?RouterInterface;
}

**Comment by laoneo** [comment]
You mean that's basically the return value of the boot function?

**Comment by laoneo** [comment]
Another question which arises, should not every extension be bootable, especially plugins?

**Comment by mbabker** [comment]
The object that gets created by the boot function IMO should have that interface.

For now I would focus primarily on components here.  Going back to the Symfony bundle and Laravel package comparison, our components fit that role and I'd use that extension type to sort things out first.  Then we can work out what changes are needed to do something similar for modules, plugins, templates, etc.

**Comment by laoneo** [comment]
Closing this one as the identified services are migrated to the component set up.
