### ISSUE TITLE
bug avec le carousel de sp page builder

### ISSUE THREAD

**Issue by Maireaux** [joomla/joomla-cms#19598]
### Steps to reproduce the issue
Bonjour 
J'ai les lignes suivantes sur la page d'accueil de mon site http://www.gpsc-plongee.fr/, depuis la mise à jour 3.8.5, 
Je suis en version php 7.1, j'ai plus de lignes avec la version php 7.2. 
Le site est stocké sur OVH.
Le carrousel fonctionne pourtant.
Impossible de revenir à Joomla 3.8.4 car aucune sauvegarde à été réalisée.

Notice: Undefined property: stdClass::$button_text in /home/gpscplon/www/components/com_sppagebuilder/addons/carousel/site.php on line 50

Notice: Undefined property: stdClass::$button_text in /home/gpscplon/www/components/com_sppagebuilder/addons/carousel/site.php on line 50

Notice: Undefined property: stdClass::$content in /home/gpscplon/www/components/com_sppagebuilder/addons/carousel/site.php on line 49

Notice: Undefined property: stdClass::$button_text in /home/gpscplon/www/components/com_sppagebuilder/addons/carousel/site.php on line 50

Notice: Undefined property: stdClass::$button_text in /home/gpscplon/www/components/com_sppagebuilder/addons/carousel/site.php on line 50

Notice: Undefined property: stdClass::$button_text in /home/gpscplon/www/components/com_sppagebuilder/addons/carousel/site.php on line 97

Notice: Undefined property: stdClass::$button_text in /home/gpscplon/www/components/com_sppagebuilder/addons/carousel/site.php on line 97

Notice: Undefined property: stdClass::$button_text in /home/gpscplon/www/components/com_sppagebuilder/addons/carousel/site.php on line 97

Notice: Undefined property: stdClass::$button_text in /home/gpscplon/www/components/com_sppagebuilder/addons/carousel/site.php on line 97

**Comment by ghost** [comment]
Please ask help on Forum of Sppagebuilder or the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
