### ISSUE TITLE
[4.0] Can't assign search module on Cassiopeia

### ISSUE THREAD

**Issue by eera5607** [joomla/joomla-cms#19593]
### Steps to reproduce the issue
Go to Modules > Add new module > Select Search > Fill the fields > Select position Search > click Save

### Expected result
Search module published on Cassiopeia's search position 

### Actual result
Error: Save failed with the following error: Field 'content' doesn't have a default value

### System information (as much as possible)
Working on localhost with XAMPP
PHP Version 7.2.0
Joomla! 4.0.0-dev (2018-02-06)

### Additional comments
None

**Comment by ghost** [comment]
Can't confirm. Creating new Module "Search" on Template-Position "Search" works as expected:

![screen shot 2018-02-07 at 7 57 00 am](https://user-images.githubusercontent.com/8235763/35902730-9e2b78dc-0bdc-11e8-8c9f-cd566757382a.jpg)
### System information
- 4.0-dev
- Sample Data
- Template: Cassiopeia
- macOS Sierra, 10.12.6
- Firefox 58 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.1.12
- MySQLi 5.6.38

**Comment by anuragteapot** [comment]
@franz-wohlkoenig issue confirmed on Linux.

![screenshot from 2018-02-07 22-37-39](https://user-images.githubusercontent.com/30978328/35930388-c3021ac8-0c57-11e8-9c78-0ef641117edb.png)

**Comment by mbabker** [comment]
This is probably a MySQL 5.7 issue, not a Linux versus Mac versus Windows issue.

**Comment by eera5607** [comment]
Sorry this a more complete system information:
System information
4.0-dev
Template: Cassiopeia
Windows 10
Chrome 63.0.3239.132 (Official Build)(64-bit

PHP 7.2.0
Apache/2.4.29 (Win32) OpenSSL/1.1.0g PHP/7.2.0
MySQLi 5.7
![screen shot 2018-02-07 at 17 16 02](https://issues.joomla.org/uploads/1/a21c63b4c91edf8245234fdad4f631a2.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19593">issues.joomla.org/tracker/joomla-cms/19593</a>.</sub>

**Comment by parul-123** [comment]
Although mine MySQL version is 5.7 but it is still working fine.

**Comment by anuragteapot** [comment]
@parul-123 can you give system information ?

**Comment by Bakual** [comment]
@Anu1601CS Is this a fresh installation of J4 or an updated one using GitHub? In the latter case, did you check with the database fixer if the table structure is up-to-date?

**Comment by anuragteapot** [comment]
@Bakual I have tested on latest <code>4.0-dev</code>. Using fresh installation

**Comment by anuragteapot** [comment]
And also, I checked database fixer table is up-to-date

**Comment by parul-123** [comment]
@Anu1601CS  
System Information

4.0-dev
Template: Cassiopeia
Ubuntu 16.04
Firefox 58.0.2

PHP 7.0.25
Apache/2.4.18 (Ubuntu)
MySQL  5.7

**Comment by brianteeman** [comment]
Can not confirm 

PHP Built On | Windows NT DESKTOP-VPRGVNL 10.0 build 16299 (Windows 10) AMD64
-- | --
Database Version | 5.7.21-log
Database Collation | utf8mb4_unicode_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.2.2
Web Server | Apache/2.4.29 (Win64) mod_fcgid/2.3.9 OpenSSL/1.1.0g

**Comment by happy2dev** [comment]
Can not confirm
My environment:
Joomla 4.0-dev
Mysql 5.5.59
Database Collation utf8mb4_unicode_ci
Server Cent 6.9
Apache 2.2.15
php 7.1.15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19593">issues.joomla.org/tracker/joomla-cms/19593</a>.</sub>

**Comment by Quy** [comment]
See PR #19836<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19593">issues.joomla.org/tracker/joomla-cms/19593</a>.</sub>
