### ISSUE TITLE
Number of administrators

### ISSUE THREAD

**Issue by household2012** [joomla/joomla-cms#19597]
### Steps to reproduce the issue
Hello! I update Joomla from 3.8.3 to 3.8.4 and the message in the bottom panel shows the number of administrator's authorizations, not the number of administrators. I logged in 8 times and I saw "8 Administrators" message.
Then I update Joomla from 3.8.4 to 3.8.5. Now I see 2 different messages:
1)  after restarting the computer and authorization: the message in the bottom panel shows  "2 Administrators" 
2) after authorization whithout restarting the computer the message in the bottom panel shows  "1 Administrators" 

### Expected result
I expect Joomla will show real numbers of administrators

### Actual result
Joomla show different numbers of administrators depending on restarting the computer

### System information (as much as possible)
Joomla 3.8.5
5.6.30-pl0-gentoo
Apache/2.2.29 (Gentoo) mod_dp/0.99.7 PHP/5.6.30-pl0-gentoo 

### Additional comments
I'm only one administrator

**Comment by ghost** [comment]
Thanks for Reporting. Can you please look at #19585 if the Comments solve your Issue?

**Comment by household2012** [comment]
Thank you very much! How I can delete my issue?

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19597">issues.joomla.org/tracker/joomla-cms/19597</a>.</sub>
