### ISSUE TITLE
Module News has no option for inserting intro image

### ISSUE THREAD

**Issue by bubi-luka** [joomla/joomla-cms#19599]
Hi,

the news module is missing a functionality to display intro image near the article (for example as in blog layout). The current option only display images in the article context.

The workaround is using override, but I would prefer not to do that.

There were already some proposed solutions, but no PR: https://github.com/joomla/joomla-cms/issues/5229#issuecomment-317178530. As I do not know how to make a PR, can somebody with more experience do it?

**Comment by ghost** [comment]
Thanks for Comment @bubi-luka, but closed as duplicate Report #16495.

**Comment by bubi-luka** [comment]
This is a feature request for a new, nonexistent functionality in The Article Newsflash Module and not a request for a more precise string, as is the Report [#16495](https://github.com/joomla/joomla-cms/issues/16495).

**Comment by ghost** [comment]
Reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19599">issues.joomla.org/tracker/joomla-cms/19599</a>.</sub>

**Comment by Kubik-Rubik** [comment]
@bubi-luka Please read the documentation how to do a PR: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

Here is also a good description: https://extensions.joomla.org/blog/item/how-to-contribute-to-joomla-through-github/

If you already have a solution, then please share it with us which will help us to get this feature faster into the module.

**Comment by carlitorweb** [comment]
PR for this option #20169

**Comment by ghost** [comment]
closed as having Pull Request #20169<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19599">issues.joomla.org/tracker/joomla-cms/19599</a>.</sub>
