### ISSUE TITLE
After update from Joomla 3.8.3 contacts not working properly

### ISSUE THREAD

**Issue by GDZed** [joomla/joomla-cms#19600]
### Steps to reproduce the issue
I'm use two single contact (contact component joomla) with two different forms.
Contacts selecting with two different single contact menu. After update from Joomla 3.8.3 to 3.8.4 or 3.8.5 always working only one contact. After restored from backup to 3.8.3 all works perfect.
My site link: https://www.digizit.ee/ru/contact

![contact-2](https://user-images.githubusercontent.com/25158105/35916069-d0903eb8-0c11-11e8-8d97-586f1a65c3b6.jpg)
![contact-1](https://user-images.githubusercontent.com/25158105/35916070-d0b317b2-0c11-11e8-9de1-6d62162ee5b8.jpg)

**Comment by alikon** [comment]
could be related to this https://developer.joomla.org/security-centre/720-20180102-core-xss-vulnerability).html

**Comment by zero-24** [comment]
hmm sorry @GDZed I don't understand what is wrong here? Can you fill out the form provided here on GitHub? That could help me to understand your issue and help you.

**Comment by GDZed** [comment]
I added some details.
After update always open form variant-1
Two contact has ID-1 and ID-3 and after update always open contact with ID-3

**Comment by Quy** [comment]
@GDZed Please provide steps/setup of contacts' menu items and I will try to reproduce with the Isotope theme.

**Comment by ghost** [comment]
@Quy the Issue looks like better discussed at [forums](https://forum.joomla.org/).

**Comment by Quy** [comment]
Please ask assistance @ [Joomla Forums](https://forum.joomla.org/) or [RocketTheme](http://www.rockettheme.com/forum).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19600">issues.joomla.org/tracker/joomla-cms/19600</a>.</sub>
