### ISSUE TITLE
[4.0] Error message above editor while editing files in com_template

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#19605]
### Steps to reproduce the issue
-  Open Extension  | Templates 
- Select on the left Templates and choose Cassiopeia.
- Click one file on the left - for example error.php

### Expected result
I see no error message

### Actual result
I see error message above the editor

![templates customise cassiopeia test administration](https://user-images.githubusercontent.com/9974686/35942407-d286414c-0c55-11e8-91d7-f8e50e9cc6cc.png)

**Comment by mbabker** [comment]
That's not an error message, that's the debug messages from JLayout.  So something is either enabling debug mode inside layouts (not sure how that gets turned on) or using its `debug` method to render.

**Comment by mbabker** [comment]
Expected behavior it seems.  https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/editors/codemirror/codemirror.php#L224 is explicitly enabling the layout's debug handling if you've got debug mode enabled.

**Comment by astridx** [comment]
OK, thank you. Yes I activated the debug mode.
I expected all debug message at the bottom of the page. 
But as it is expected I close this issue.
