### ISSUE TITLE
spacer form field tooltips rendered differently from other form fields

### ISSUE THREAD

**Issue by Sophist-UK** [joomla/joomla-cms#19604]
### Steps to reproduce the issue

Create a forms.xml with a spacer (no hr) and e.g. a list, both with label and description.

Render the forms.xml.

### Expected result

Both spacer and list fields should use .hasPopover class, and should have similar styled tooltips.

### Actual result

Spacer field has incorrect style because it uses .hasTooltip instead.

### System information (as much as possible)

J3.8.4,

### Additional comments

This is because /libraries/joomla/form/fields/spacer.php does not use the standard FormFields.php getLabel and renderField methods but instead has its own methods. IMO the getLabel method should limit itself to handling hr="true" and call parent.getLabel for anything else.

**Comment by brianteeman** [comment]
What is the usecase for having a tooltip/popover on a spacer?

**Comment by Sophist-UK** [comment]
The use case is that the spacer is essentially a label without a field, and my form uses lots of labels with tooltips including the spacer.

The tooltip on the spacer works, but looks very different - and this is because unlike every other form field type, the spacer form field does not use the parent getLabel method but does its own thing and does it differently.

**Comment by Sophist-UK** [comment]
There is no point (IMO) in having a tooltip on an "hr" version of spacer, so this is an exception.

**Comment by brianteeman** [comment]
@Sophist-UK will you be able to submit a pull request for this?

**Comment by Sophist-UK** [comment]
@brianteeman Sorry Brian - I looked at it and how we do tooltips on every other field type and couldn't easily spot how to do it.

However, if you can create the database shim discussed in #19367 and needed for a J4 version of that PR, then I will take another look at this issue and spend the time trying to do a PR for it.

**Comment by Quy** [comment]
PR #20584<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19604">issues.joomla.org/tracker/joomla-cms/19604</a>.</sub>
