### ISSUE TITLE
3.8.5 Session handler options no longer show php or database

### ISSUE THREAD

**Issue by Twincarb** [joomla/joomla-cms#19602]
### Steps to reproduce the issue
Upgrade to Joomla 3.8.5 & Check the session handlers that are available

### Expected result
Options to include:
File
PHP
Database
Redis etc

### Actual result
Redis & File are shown

### System information (as much as possible)
Linux server - Centos 7 
Database 5.5.5-10.1.30-MariaDB
PHP 7.0.27
Plesk Onyx 
Version 17.5.3 Update #40, last updated on Feb 6, 2018 07:15 PM

### Additional comments

I am seeing this on 2 domains that have been updated, I am about to update a 3rd which has Database as the session handler...

**Comment by mbabker** [comment]
Can't confirm.

![screen shot 2018-02-07 at 1 00 30 pm](https://user-images.githubusercontent.com/368545/35935723-f408a854-0c06-11e8-819d-a07e7156fea5.png)

Double check to make sure that you haven't made any other server related changes that could cause this to happen (removed PHP extensions, missing files in the `libraries/joomla/session` directory, etc.).

**Comment by Twincarb** [comment]
I just upgraded the other site which was using php 7.1 which went without an issue, changed the php version on that site to 7.0 which of course restarts php on the server and now all sites are working correctly.
Will put it down to an issue with php 7.0 which needed a restart.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19602">issues.joomla.org/tracker/joomla-cms/19602</a>.</sub>
