### ISSUE TITLE
[4.0] [RFC] Remove User - Profile plugin in Joomla 4.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#19619]
We have com_fields now. I think in Joomla 4 the unhandy (view Code and DB) plugin "User - Profile" should be removed from core.

Occasion:
https://github.com/joomla/joomla-cms/pull/19614#issuecomment-364075309

**Comment by C-Lodder** [comment]
I would probably say decouple rather than just remove

**Comment by mbabker** [comment]
As with anything affecting user data, there must be a migration path/tool to ensure the upgrade doesn't lose their data when moving to 4.0.

**Comment by brianteeman** [comment]
In the absence of any progress on this I m going to close it at this time. As @mbabker says there would need to be an upgrade path before this can be removed
