### ISSUE TITLE
Language Filter not changing website direction on first language switch attempt

### ISSUE THREAD

**Issue by arashemadi** [joomla/joomla-cms#19625]
### Steps to reproduce the issue
Visit: https://222publications.com/fa
Switch to English (from the menu at the top)

### Expected result

The language should be switched to English and the direction should be changed from RTL to LTR properly on the first attempt to switch the language. 

### Actual result

The language is switched to English but the direction remains RTL and the lang tag remains fa-IR instead of en-GB. You'd have to refresh an extra time to fix things. 

### System information (as much as possible)

Latest Joomla, PHP 5.6, Upgraded from Joomla 2 to Joomla 3. 

### Additional comments

I've tried so hard to fix this, but it doesn't work as it should. Please help.

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
