### ISSUE TITLE
Editing a content article fails

### ISSUE THREAD

**Issue by czimbalm** [joomla/joomla-cms#19626]
### Steps to reproduce the issue
Backend: Content, Articles and click on any article there.

### Expected result
To see the article and to edit it.

### Actual result
An error has occurred.
0 Call to undefined function modification()
 Return to Control Panel

### System information (as much as possible)

Setting | Value
-- | --
 
PHP Built On | Linux server13.iworx-host.com 2.6.32-696.18.7.el6.x86_64 #1 SMP Thu Jan 4 17:31:22 UTC 2018 x86_64
Database Version | 5.6.38-log
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.0.25
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.8.5 Stable [ Amani ] 6-February-2018 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

### Additional comments
I have updated MijoShop component to 4.0.0 and since then I get this. 
If possible would like to ask for some support to solve this problem ASAP. I am willing to pay for the assistance.

**Comment by brianteeman** [comment]
As this problem occurred after an update of a non-core component it is safe to assume that this component is the cause of the problem. Please contact mijoshop creators for support and/or if they dont help please use the forum https://forum.joomla.org
