### ISSUE TITLE
[4.0] Warning ArticlesModel.php on line 307

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#19627]
### Steps to reproduce the issue
Open Control Panel having Sample Data installed:

![screen shot 2018-02-09 at 12 06 10 pm](https://user-images.githubusercontent.com/8235763/36025077-117966bc-0d92-11e8-8a5b-03db611b7654.jpg)
### System information
- 4.0-dev
- Sample Data
- Template: Cassiopeia
- macOS Sierra, 10.12.6
- Firefox 58 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.2.1
- MySQLi 5.6.38

**Comment by anuragteapot** [comment]
@franz-wohlkoenig this issue was present in <code>PHP 7.2 </code>

**Comment by ghost** [comment]
Yes, it's present in PHP 7.2.1.

**Comment by anuragteapot** [comment]
@franz-wohlkoenig  we have a PR see #19216

**Comment by ghost** [comment]
got, thanks for Hint.
