### ISSUE TITLE
Wrong number of visitors after update 3.8.4 and 3.8.5 with session handler set to database

### ISSUE THREAD

**Issue by pera2** [joomla/joomla-cms#19639]
### Steps to reproduce the issue

After update to Joomla 3.8.4. Who's online module display wrong number of visitors (Number of visitors is abnormally high 4 #19511)

Session handler is database.

After update 3.8.4 Who's online module display wrong number of visitor with both handler (database or php).

After update 3.8.5.  Who's online module display wrong number of visitor with database handler and number of visitors with php session handler is corect.

Fix delete session meta data error #19514 - solved problem only partialy.

### Expected result

This is issue and I have not solution.

### System information (as much as possible)

PHP version | 7.0.27
www server | Apache/2.4.29 (cPanel)
www server ka PHP interfejsu | cgi-fcgi
Joomla! version | Joomla! 3.8.5 Stable [ Amani ] 6-February-2018 15:00 GMT
Joomla! version  | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by joomdonation** [comment]
If you want to have a more reliable number of visitors display in the module, consider setting up a cron job as explained here https://github.com/joomla/joomla-cms/issues/19636#issuecomment-364666497

Otherwise, increase the value of **session.gc_probability** in PHP setting would help, too

**Comment by pera2** [comment]
Thank you.

This is to complicated :). It is simplier to turn off who`s online module.  Before update 3.8.4. and 3.8.5 module working fine. I guess that something in joomla 3.8.4 update make mess. Site usually have less than 10 visitors and after update numbers is several thousands or more.

**Comment by ghost** [comment]
closed as duplicate Report #19511<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19639">issues.joomla.org/tracker/joomla-cms/19639</a>.</sub>

**Comment by ghost** [comment]
Reopened as this Issue is about 3.8.5 too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19639">issues.joomla.org/tracker/joomla-cms/19639</a>.</sub>

**Comment by joomdonation** [comment]
Yes, there was a change in 3.8.4 to improve performance and make code right related to session. In your case, change Session Handler to PHP as you mentioned should be OK

**Comment by mbabker** [comment]
See https://github.com/joomla/joomla-cms/issues/19585#issuecomment-363508044 for additional info.

Closing again, everything is working as designed for the moment (even if less than optimal for one configuration) with further efforts to improve it ongoing.
