### ISSUE TITLE
Description translation on extension installation

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#19630]
### Steps to reproduce the issue

Create a component with the following description in the manifest
&lt;description&gt;COM_MYCOMPONENT_XML_DESCRIPTION&lt;/description&gt;

### Expected result

On successfull installation translated language text displayed below successfull installation message.

### Actual result

Non-translated text COM_MYCOMPONENT_XML_DESCRIPTION displayed instead.

Rerun installation and now the translated text displayed, as expected result.
Uninstall the component and repeat the installation COM_MYCOMPONENT_XML_DESCRIPTION displayed again. 

### System information (as much as possible)

Joomla 3.8.5

**Comment by Bakual** [comment]
Did you put that language string into the com_mycomponent.sys.ini file or just into the com_mycomponent.ini?

**Comment by BrainforgeUK** [comment]
Its in both com_mycomponent.sys.ini file and com_mycomponent.ini

The one it uses when the installation is rerun is the one in com_mycomponent.sys.ini

Without uninstalling if I change the text (in the source) I have to rerun the installation twice before the new text appears.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19630">issues.joomla.org/tracker/joomla-cms/19630</a>.</sub>

**Comment by Bakual** [comment]
Can't confirm. It works fine when testing with my component.
Chances are your language file is corrupt and thus doesn't get loaded.

**Comment by BrainforgeUK** [comment]
If language file corrupt why would it work the second time?

Example component illustrating the problem can be found here:
https://github.com/brainforgeUK/com_example
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19630">issues.joomla.org/tracker/joomla-cms/19630</a>.</sub>

**Comment by infograf768** [comment]
I guess the .ini as well as the sys.ini are not in the correct language/xx-XX/ folder in the component.
If I remember well, the translation would show in that case.

Look the way it is done for the multilangstatus module:
https://github.com/joomla/joomla-cms/blob/staging/administrator/modules/mod_multilangstatus/mod_multilangstatus.xml#L13-L22

Evidently, you have to separate admin and site files.

**Comment by Bakual** [comment]
You need to move the files to /admin/language/en-GB/en-GB.com_example.sys.ini and reference them correctly again in the manifest, then it works.
However instead of using the `<language>` tag which puts the files into the global language folder, you should better just use  `<folder>language</folder>` in your manifest. This would install the language files to you component directory.

**Comment by Bakual** [comment]
I'm closing this issue as it's an error in the manifest.
