### ISSUE TITLE
[4.0][RFC] Improve and modernize Joomla Javascript

### ISSUE THREAD

**Issue by dneukirchen** [joomla/joomla-cms#19643]
## Why?

* There are many improvements in es6 which makes it a lot easier to write javascript
* The module system makes it easier to write javascript unit tests. 
* All modern js libraries and frameworks switched to es6 (angular, vue, react… and many more). We should at least try to keep up with the js world. 
* We already use es6 features in some parts of the project: i.e.: tests, media manager, custom elements.
* Browser Support for es6 is good: https://kangax.github.io/compat-table/es6/ Essentially all browsers except IE11. To support IE11 we need to compile es6 code down to es5. **This means there will be no change for the end user.**

More information about es6: https://github.com/lukehoban/es6features

## How?

- [x] Update the package.json and install dependencies needed to compile ES6 down to ES5. Add/Update scripts to compile es6 to es5: #19650
- [x] Adopt airbnb es6 javascript style guide as javascript coding standard: https://github.com/joomla/joomla-cms/pull/19638 
- [ ] Fix code style errors in build scripts #19717 
- [ ] Rename all Javascript files to *.es6.js and compile them: https://github.com/joomla-projects/joomla-es6/issues
- [ ] check all dependencies in package.json (are the versions up 2 date? Are they still required?)
- [ ] Re/Organize joomla namespace
- [ ] Refactor libraries, so that they are unit testable.
- [ ] Drop javascript test dependencies: jasmine-jquery, requirejs, jasmine-ajax… and reduce the usage of fixture testing (prefer real unit tests, probably with a mocking lib like sinon).
- [ ] Refactor the unit tests. 
- [ ] optional: implement module loading
- [ ] ~~Remove all minified scripts from repository. https://github.com/joomla/joomla-cms/pull/19637~~ 
- [ ] ~~add .eslint.es5 and lint old es5 code. Personally i think we should focus on moving things to es6 and enforce cs during refactoring instead of spending time with this.~~

**Comment by C-Lodder** [comment]
> Update the package.json and install dependencies needed to compile ES6 down to ES5

We already do this (Babel) for custom elements, so I suppose you can check that off.

**Comment by dneukirchen** [comment]
> We already do this for custom elements, so I suppose you can check that off.

yes and no... i checked the build scripts. we can at least refactor them (and probably get rid of browserify and use only babel-core instead as we said that we do not want to depend on bundlers anymore?).

**Comment by dgrammatiko** [comment]
> Rename all Javascript files to *.es6.js and compile them. (OR: rename only the files that are rewritten in es6 to *.es6.js).

Let's do it the same way we're doing it in custom elements: .js **is ES6**, `.es5.js` is dead code...

**Comment by dneukirchen** [comment]
> Let's do it the same way we're doing it in custom elements: .js is ES6, .es5.js is dead code...

we can do that,  personally i like the *.es6.js approach more, because it does not change anything for the end user (he can continue to use validation.js, which will be compiled es5).

**Comment by dgrammatiko** [comment]
Hold on, is this (i mean the ES6 coded files) only for our eyes, only for devs?
If so we can do better, use the existing `Joomla.webcomponents` loader and let the client side decide what type of js will be fetched...

**Comment by dneukirchen** [comment]
In a first step i want to improve the current js code and be able to write es6 javascript. So the new .es6.js files are mostly for devs atm. 

If we find a way to lazy load es6 modules, i would love to go a step further, but thats not a trivial task in joomla context.

**Comment by brianteeman** [comment]
is this meta list being kept upto date

**Comment by brianteeman** [comment]
Closed due to lack of response

**Comment by thednp** [comment]
asd
