### ISSUE TITLE
joomla search results showing  ...

### ISSUE THREAD

**Issue by James-Kemet** [joomla/joomla-cms#19660]
Hi, since upgrading to the lastest joomla (3.8.5) i have noticed when testing the joomla search facility that it adds code to the end of some of the article titles. I have checked these titles and there are no special characters at the end so not sure why this is happening? (see attached) or browse here http://www.kemet.com.au/component/search/?searchword=lapping%20machine&ordering=popular&searchphrase=any

I am also using the standard joomla search module not the smart search module.

Regards James

**Comment by James-Kemet** [comment]
on closer inspection i notice the code seems to appear after the keyword, see the below examples 

http://www.kemet.com.au/component/search/?searchword=lapping%20plates&ordering=popular&searchphrase=exact

http://www.kemet.com.au/component/search/?searchword=lapping%20machine&ordering=popular&searchphrase=exact<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19660">issues.joomla.org/tracker/joomla-cms/19660</a>.</sub>

**Comment by ghost** [comment]
Please provide System Informations and from which Version you Update, so People can help. 

Example:
### System information
- 3.8.6-dev
- Multilanguage Site (4 Lang.) & Test English (GB) Sample Data
- Template: Protostar
- macOS Sierra, 10.12.6
- Firefox 58 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.2.1
- MySQLi 5.6.38

**Comment by James-Kemet** [comment]
updated from 3.8.2 

PHP Built On	Linux webserver.kemet.co.uk 3.10.0-229.20.1.el7.centos.plus.x86_64 #1 SMP Wed Nov 4 01:06:14 UTC 2015 x86_64
Database Version	5.6.38
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.33
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.8.5 Stable [ Amani ] 6-February-2018 15:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19660">issues.joomla.org/tracker/joomla-cms/19660</a>.</sub>

**Comment by James-Kemet** [comment]
sorry this seems to be a template issue so can be closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19660">issues.joomla.org/tracker/joomla-cms/19660</a>.</sub>
