### ISSUE TITLE
Grouping articles by publish date in module Article Category (mod_articles_cetegory)

### ISSUE THREAD

**Issue by jjnxpct** [joomla/joomla-cms#19661]
### Steps to reproduce the issue
- Create a new articles category module showing articles from a specific category (filter - In my case 'news'.)
- Sort options: Start date publication 
- Group options: Article grouping: 'Month and year'
- Group options: Group direction: 'Descending'
- Group options: Month and Year Display Format: 'F Y'

### Expected result
I would like to see the grouping based on the publish date (publish_up)of the articles. This publish date is also shown on the site on the articles.

### Actual result
In stead of the publish date the module uses create date. So articles created in januari, but published in februari, turn up under 'januari 2018'.

### System information (as much as possible)

Joomla 3.8.5

### Additional comments

I would be nice to have an extra parameter in the module at the grouping tab to be able to chose the date for grouping: create date or publish date.

I now duplicated the module and changed these lines in the module helper.php to get what we needed:

469 - $month_year = StringHelper::substr($item->publish_up, 0, 7);
481 - $month_year = $year = StringHelper::substr($item->publish_up, 0, 4);

**Comment by brianteeman** [comment]
Can you not use the date filtering options for this?

**Comment by jjnxpct** [comment]
I believe the date filtering is meant for selecting a specific period in which the article was created (or published). So maybe between jan 2017 and dec 2018. And this period can be based on created date or published date. But this has no effect on the sorting option.

The grouping is hardcoded in the helper.php ($item->created) so there is no parameter for this in the module. So adding this parameter to the module would be a nice addition?

**Comment by SharkyKZ** [comment]
Test PR #20139 please.

**Comment by ghost** [comment]
closed as having Pull Request #20139
