### ISSUE TITLE
Showing a warning to enable Javascript.

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#19665]
### Steps to reproduce the issue

This is not a real issue, but a proposal for a new feature.

### Expected result

There is showing a warning on the Frondend site to enable JavaScript if desired. (optional)

### Actual result

There is NOT showing a warning message if necessary.

### System information (as much as possible)

Templates: Protostar and Beez3

### Additional comments

For many sites it is necessary to turn on JavaScript.
So it seems convenient to add this functionality as an extra option in the template settings.
Default = no.

Example code change in the index.php from Protostar:
```
<!-- Body -->
<div class="body" id="top">
	<noscript>
			<?php echo JText::_('TPL_PROTOSTAR_WARNJAVASCRIPT'); ?>
	</noscript>	
```

See warning message image.
![screen shot 2018-02-13 at 11 29 26](https://issues.joomla.org/uploads/1/9506a4e0cc488bbd1956152d4d9c5cd8.png)

**Comment by dgrammatiko** [comment]
Just copy paste from here:
https://github.com/joomla/joomla-cms/blob/8d7a917e8c940ab3bfdcd449acb4a12935c6a000/administrator/templates/isis/login.php#L124-L126

**Comment by sandewt** [comment]
>Just copy paste from here:

@dgt41 that was also my first thought, but the text of the Constante is related to the backend and not to the frontend.

See the \administrator\language\en-GB\en-GB.ini.

```
JGLOBAL_WARNJAVASCRIPT="Warning! JavaScript must be enabled for proper operation of the Administrator Backend."
```

I do not know if it is in Joomla! desirable to hang different text on the same Constant?
It is useful to use the same constant for Protostar and Beez3.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19665">issues.joomla.org/tracker/joomla-cms/19665</a>.</sub>

**Comment by dgrammatiko** [comment]
then replace `Administrator Backend` with `site`

**Comment by sandewt** [comment]
>then replace Administrator Backend with site

Is it allowed to use the same constante twice @dgt41 ? So yes...

I closer look let's see that this as expected works for both templates.
By adding the folowing code in the file joomla\language\en-GB\en-GB.ini.

```
JGLOBAL_WARNJAVASCRIPT="Warning! JavaScript must be enabled for proper operation of the Frontend site."
````

**Comment by Bakual** [comment]
Please use a slightly different key (eg JGLOBAL_WARNJAVASCRIPT_SITE) for the language string. That works better with translation tools and their memory.

**Comment by mbabker** [comment]
While it's easy to do for the core templates, a part of me wonders if there is actually going to be any benefit here as most sites aren't using the core templates and wouldn't have this option/feature available.  You'd almost be better off making a `mod_custom` instance with the `<noscript>` tag than hardcoding something into the template markup.

**Comment by brianteeman** [comment]
And there are even less users who browse with javascript disabled

2016 stat of 0.2% https://blockmetry.com/blog/javascript-disabled


In other words this isnt something we need to add to the core

**Comment by brianteeman** [comment]
I am going to close this as it can't really be implemented in the core as its specifically template related

**Comment by sandewt** [comment]
Thank you all for the info and the thinking.

So I have searched for an alternative and came out on a simple plugin, based on the following principle.
(For the enthusiast.)

CODE PLUGIN
```
public function onAfterRender()
{
	<!-- some code -->
	$body = $this->app->getBody();
	$body = str_replace('</body>', $message . '</body>', $body);
	$this->app->setBody($body);
	}
```
And so on.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19665">issues.joomla.org/tracker/joomla-cms/19665</a>.</sub>
