### ISSUE TITLE
Website disappered

### ISSUE THREAD

**Issue by ukturb** [joomla/joomla-cms#19666]
The joomla hosted website
http://www.turbulence.ac.uk/
 for which i am administrator but not owner, has disappeared. this is a major EPSRC funded research page that has just vanished and i would like to speak to a human about it. (the owner is overseas and very slow to respond to emails.
 Does the page need paying for? I was informed we were paid up until May this year. Is the data still available. There is a LOT of work there that has for all intents and purposes vanished.
 please get back to me at aaceu@soton.ac.uk.
 Many Thanks

Richard

**Comment by brianteeman** [comment]
Joomla is the software used to create a web site. Joomla does not host any website
