### ISSUE TITLE
No link to TOS article in registration form

### ISSUE THREAD

**Issue by PeterBenzin** [joomla/joomla-cms#19673]
### Steps to reproduce the issue

Installed Joomla 3.8.2 from scratch with demo data
Enabled user registration
In Plugin Users Profile: Set TOS to required and defined TOS article
Tested in Frontend successfully
Updated to Joomla 3.8.5 using Updater Component
Refreshed Registration Page in Front-End ... the Link to the TOS article vanished.

### Expected result

There should remain an active Link to TOS after updating

### Actual result
the Link to the TOS article vanished

### System information (as much as possible)

System Information
Setting 	Value
 
PHP Built On 	Linux vwp0099 4.4.74-1-xenu-static-he+1+ #2 SMP Mon Jun 26 12:35:59 CEST 2017 x86_64
Database Version 	5.6.36-82.0-log
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.0.27-he.0
Web Server 	Apache
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.8.5 Stable [ Amani ] 6-February-2018 15:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0 

### Additional comments
Pretty much the same like here:
https://github.com/joomla/joomla-cms/issues/13973

None of the solutions provides there have helped.

This is my first bug report here ever - I hope I have provided all neccessary information and did not overlook anything while haveing searched the issue tracker before my posting.

**Comment by brianteeman** [comment]
Thanks k you for your very first bug report. It looks like everything needed is here. I believe this has been fixed already but I can't confirm! as I am on a train so hopefully someone will respond shortly. Just wanted to give you a quick thank you.

**Comment by Quy** [comment]
Fixed #19633 to be in the next release.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19673">issues.joomla.org/tracker/joomla-cms/19673</a>.</sub>
