### ISSUE TITLE
[4.0] Error: Failed to start application

### ISSUE THREAD

**Issue by anuragteapot** [joomla/joomla-cms#19679]
### Steps to reproduce the issue

Download the latest patch <code>4.0-dev</code> and just install.

### Expected result

Installation executes normally without any issue.

### Actual result
<code>Error: Failed to start application: Call to a member function get() on array</code>

### System information (as much as possible)
Linux 
PHP 7.1
Joomla version : 4.0-dev

**Comment by anuragteapot** [comment]
Issue after #19658

**Comment by laoneo** [comment]
Does https://github.com/joomla/joomla-cms/pull/19669 help?

**Comment by anuragteapot** [comment]
Let me check

**Comment by anuragteapot** [comment]
@laoneo  #19669 not fix this issue  :(

**Comment by laoneo** [comment]
Please test #19689 which should fix the issue.

**Comment by anuragteapot** [comment]
@laoneo PR #19689 it works :)

**Comment by ghost** [comment]
@Anu1601CS can you please close this issue as PR works?
