### ISSUE TITLE
Use of & in language strings?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#19676]
I noticed that about 50% of the time the string uses & and the rest of the time the string uses `&amp;`

Is there a reason for this that I can't see or is it an inconsistency that needs to be resolved

### Examples
> JSAVE="Save `&amp;` Close"

> JACTION_ADMIN="Configure ACL & Options"

**Comment by mbabker** [comment]
Personally I'd say HTML entities shouldn't be a requirement, especially because Joomla's not supposed to be an HTML only platform.
