### ISSUE TITLE
[4.0] Error while installing

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#19696]
### Steps to reproduce the issue
Clone this repo and fetch the branch 4.0-dev and checkout this branch.

### Expected result
You can install Joomla! 4

### Actual result
You see an error: 
Error: Call to a member function get() on array in /var/www/html/JOOMLA/joomla4_test/joomla-cms/libraries/src/Service/Provider/Database.php on line 48

### System information (as much as possible)
Ubuntu 16.04
![localhost joomla joomla4_test joomla cms installation index php](https://user-images.githubusercontent.com/9974686/36280028-50c77398-1299-11e8-8a2a-4a9de68e59d2.png)

**Comment by anuragteapot** [comment]
@astridx yeah, this one is config service provider issue see #19679

**Comment by anuragteapot** [comment]
Test this PR #19689 mark result and close this issue :)

**Comment by astridx** [comment]
@Anu1601CS Thank you. So I close this.

**Comment by anuragteapot** [comment]
@astridx sure :)
