### ISSUE TITLE
Perhaps here the semicolon is forgotten

### ISSUE THREAD

**Issue by Psychosynthesis** [joomla/joomla-cms#19698]
https://github.com/joomla/joomla-cms/blob/5bf0e5d688542530587b556e35b0e1be6df3b5ae/templates/protostar/js/template.js#L13

Is it the string must not end with a semicolon?

`$ ('* [rel = tooltip]'). tooltip ();`

**Comment by C-Lodder** [comment]
Semicolon is not required

**Comment by Psychosynthesis** [comment]
Yes, I understand, but if
`.tooltip ()`
accepts arguments and in the future someone inserts some variable after this call or a function that returns a value, it will search for a long time in what reason.

**Comment by C-Lodder** [comment]
If you would prefer it to have a semicolon, then by all means, feel free to submit a PR.

**Comment by dgrammatiko** [comment]
Actually this line doesn’t belong to the template.js

**Comment by ghazal** [comment]
@dgt41 
You mean it should not be there ?

**Comment by brianteeman** [comment]
Closed as not a bug
