### ISSUE TITLE
Possible missing CSRF token tags adminForm

### ISSUE THREAD

**Issue by James-OHara** [joomla/joomla-cms#19711]
### Steps to reproduce the issue
Access [baseurl]/index.php/component/tags/?limit=20&start=0. The page source includes a form called adminform.

### Expected result
adminform would include an anti-CSRF token to prevent cross site request forgery vulnerability.

### Actual result
adminForm does not have an anti-CSRF token

### System information (as much as possible)
Joomla: 3.8.5

**Comment by mbabker** [comment]
It's bad copy/paste if anything.  The forms on the tags frontend layouts are all related to pagination and result filtering (read operations only), no need for CSRF here as these forms should be doing GET requests (why they use POST beats me but `¯\_(ツ)_/¯`).

**Comment by ghost** [comment]
Closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19711">issues.joomla.org/tracker/joomla-cms/19711</a>.</sub>
