### ISSUE TITLE
Formulario de preguntas de opción múltiple crea etiqueta  extra

### ISSUE THREAD

**Issue by gmolledaj** [joomla/joomla-cms#19716]
### Steps to reproduce the issue
Crear nueva pregunta de opción múltiple
Escribir nombre, enunciado y alguna respuesta
Ver el código html del enunciado o la respuesta

### Expected result
```<p>mi texto</p>```

### Actual result
```<p>mi texto<br></p>```
Crea una etiqueta ```<br>``` extra que sobra.

### System information (as much as possible)
versión 3.3, build 20170629, apache2, mysql 7.0 y linux

### Additional comments
Si en vez de escribir directamente la respuesta, simplemente pongo el cursor para editarla pero no escribo, ahora edito otro campo como el enunciado, y vuelvo a editar la respuesta en blanco pero esta vez escribo, el texto queda por fuera de las etiquetas de html así: ```mi texto<p><br></p>```

**Comment by Quy** [comment]
Please translate into English.

**Comment by gmolledaj** [comment]
Please learn Spanish or Esperanto, not discriminate by nationality or family income.
Mi povas tradukas al la Esperanta lingvo. Mi ne povas iras al aliaj landoj por lerni la anglan lingvon. La angla diskriminacias homojn pro sia ŝtataneco kaj enspezo.
Google:
Steps to reproduce the issue
Create new multiple-choice question
Write name, statement and some answer
See the html code of the statement or the answer

Expected result
```<p>my text</p>```

Actual result
```<p>my text<br></p>```
Create an ```<br>``` extra tag that's left over.

System information (as much as possible)
version 3.3, build 20170629, apache2, mysql 7.0 and linux

Additional comments
If instead of writing the answer directly, I simply put the cursor to edit it but I do not write, now edit another field as the statement, and return to edit the answer in white but this time I write, the text is outside the html tags so: ```my text<p><br></p>```

**Comment by brianteeman** [comment]
multiple choice question? there is nothing in the core of joomla for this. Is it a component you have installed?

version 3.3? the latest version of joomla is 3.8.5

**Comment by brianteeman** [comment]
Para cualquier duda sobre Joomla! 3.
https://forum.joomla.org/viewforum.php?f=24

**Comment by gmolledaj** [comment]
Cierto, me equivoqué, perdón.
