### ISSUE TITLE
Redirect duplicate key error with unicode and non-unicode URL

### ISSUE THREAD

**Issue by bubi-luka** [joomla/joomla-cms#19713]
### Steps to reproduce the issue

1. Set Joomla's global setting Unicode Aliases to "NO", enable Redirect plugin with option Collect URLs "Enabled". Use modern routing option.
2. Visit Joomla page using URL with character "š" in a bogus URL.
2. Visit Joomla page using same bogus URL but changing the Unicode character "š" with it's non-Unicode representation "s".
3. Visit Joomla admin area -> Menu -> Components ->Redirect. There you will find both URLs, entered separately.
4. Edit the one with Unicode character "š" and point it to a valid URL. Set it to Enabled.
5. Test this URL and it will redirect correctly.
6. Edit the one with non-Unicode character "s", set it to a valid URL and enable it.
7. On save it will give the error "Save failed with the following error: The source URL must be unique."
8. Test the URL and it will give you a 404 page. It will not use the redirect set in step No. 4.

### Expected result
I should be able to edit  both URLs, as they are different. They are treated as different by Joomla when visiting the page. The Redirect component also treat's them differently as it stores them as separate entries.

### Actual result
I can edit only one of the URLs.

### System information (as much as possible)
---
- Database Version | 5.5.5-10.2.12-MariaDB
- Database Collation | utf8mb4_general_ci
- Database Connection Collation | utf8mb4_general_ci
- PHP Version | 7.1.14
- Web Server | nginx/1.12.1
- WebServer to PHP Interface | fpm-fcgi
- Joomla! Version | Joomla! 3.8.5 Stable [ Amani ] 6-February-2018 15:00 GMT
- Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
- User Agent | Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58
---
- Search Engine Friendly URLs => YES
- Use URL Rewriting => YES
- Add Suffix to URL => YES
- Unicode Aliases => NO
- URL Routing => MODERN

### Additional comments
I can provide more details upon request.
The Trash was empty.
The attached image shows there are only two entries using this URL. The search identifies them as the same, although you can see they differ in one character.
![screenshot-2018-2-17 redirects links - bubiji - administration](https://user-images.githubusercontent.com/1206048/36341914-dde8db38-13f5-11e8-98f9-9f0911dcfe7f.png)

**Comment by infograf768** [comment]
2 questions:
1. What happens when you do not use modern routing?
2. What happens when Unicode alias is set to Yes?

**Comment by infograf768** [comment]
In fact, I tested. Same behavior.
Looking into this

**Comment by infograf768** [comment]
Please test this simple patch https://github.com/joomla/joomla-cms/pull/19734

**Comment by bubi-luka** [comment]
The patch works. Thank you!
