### ISSUE TITLE
bootstrap-rtl.css has duplicate entries

### ISSUE THREAD

**Issue by obuisard** [joomla/joomla-cms#19714]
### Steps to reproduce the issue

Force RTL mode in the Protostar template. 
Show a page that contains the icons.php content layout.

### Expected result

The button dropdown should have round corners in RTL mode 

### Actual result

The button dropdown (print/edit...) only has right corners round, the left ones are square.

### Additional comments

The problem comes from the fact that the following CSS selector is duplicated in bootstrap-rtl.css (the 2nd occurrence is wrong)

.btn-group > .btn:first-child,
.radio.btn-group > label:first-of-type

**Comment by Quy** [comment]
See PR #19715<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19714">issues.joomla.org/tracker/joomla-cms/19714</a>.</sub>
