### ISSUE TITLE
JLoader::import with same key ignores the file even if the base is different

### ISSUE THREAD

**Issue by corejoomla** [joomla/joomla-cms#19712]
### Steps to reproduce the issue
Load two different files with the different base locations but with same name.

JLoader::import('somemodel', JPATH_ROOT.'/components/com_mycomponent1/models');
JLoader::import('somemodel', JPATH_ROOT.'/components/com_mycomponent2/models');

### Expected result
Models from each component are loaded and can be used.
JModelLegacy::getInstance( 'somemodel', 'MyComponent2Model' );  should result model object.

### Actual result
JModelLegacy::getInstance( 'somemodel', 'MyComponent2Model' ); results in false value

### System information (as much as possible)
Joomla 3.8.5

**Comment by mbabker** [comment]
`JLoader::import()` works with a dot separated key to load files, it is the class method used by `jimport()`, so its proper use would be `JLoader::import('joomla.filesystem.file')` (note the method also has very explicit class name expectations, component model classes wouldn't fit the convention).

You should either use `JLoader::register()` to register class names to the autoloader, or `JModelLegacy::addIncludePath()` to register the lookup paths for your models.

**Comment by ghost** [comment]
@corejoomla can this Issue be closed?

**Comment by corejoomla** [comment]
Thanks for the clarifications. This issue can be closed.
