### ISSUE TITLE
1and1 joomla contacts form not sending to hotmail

### ISSUE THREAD

**Issue by guyawharwood** [joomla/joomla-cms#19718]
#I have two sites hosted by 1and1 running Joomla! 3.8.5. Both have contact modules. If the contact is to a hotmail.co.uk account, any emails sent fail with no error messages - the form says the send was successful. If I change the form to use a gmail account - the send is successful. This appears to be a recent problem.

I have a further site running from the same 1and1 account running Joomla! 3.8.2, which appears not to have this problem.

Is this a bug with 3.8.5 or any suggestions on how I fix this.

**Comment by brianteeman** [comment]
how do you know it failed? Did it go to the spam folder of the hotmail account.

**Comment by DavidBoggitt** [comment]
I had this with a site (different hosts).  They said the following (which fixed it):

> I've taken a look and I see the 'mailfrom' parameter in your configuration.php file is set to email-deleted@hotmail.com.  When your site tries to send a message to Hotmail with this as the from address, Hotmail detects the message as spoofed and is likely rejecting the message based on that.  If you adjust this to send mail from an address under @theactualdomainname.com then that should correct the problem. 

I've obviously redacted the sensitive information in their reply.

**Comment by guyawharwood** [comment]
I have just check my config file and it reads as follows

"	public $mailonline = '1';
	public $mailer = 'mail';
	public $mailfrom = 'g.h@hotmail.co.uk';
	public $fromname = 'Bourne Deeping Parish Church';
	public $sendmail = '/usr/sbin/sendmail';
	public $smtpauth = '0';
	public $smtpuser = '';
	public $smtppass = '';
	public $smtphost = 'localhost';
	public $smtpsecure = 'none';
	public $smtpport = '25';"

So I guess this is not the problem.

Also the problem is occurring from the contact form, which I assume isn't affected by this.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19718">issues.joomla.org/tracker/joomla-cms/19718</a>.</sub>

**Comment by Quy** [comment]
@guyawharwood `g.h@hotmail.co.uk` should be changed to a valid email address from the domain name.

**Comment by Quy** [comment]
Closing as a configuration issue and not a Joomla core issue. If you need further assistance, please ask in the [Joomla Forums](https://forum.joomla.org/).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19718">issues.joomla.org/tracker/joomla-cms/19718</a>.</sub>
