### ISSUE TITLE
[4.0] Advanced Permissions Report Fatal Error

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#19726]
### Steps to reproduce the issue

2c89b2b
Click Advanced Permissions Report on a user in user manager

### Expected result

The Advanced Permissions Report 

### Actual result

```

Notice: Trying to get property of non-object in /administrator/components/com_users/View/Debuguser/HtmlView.php on line 123

Notice: Trying to get property of non-object in /administrator/components/com_users/View/Debuguser/HtmlView.php on line 123
Call to a member function get() on null
```

### System information (as much as possible)

2c89b2b

**Comment by anuragteapot** [comment]
duplicate issue #18592 close this

**Comment by PhilETaylor** [comment]
same issue - although this time I get a different error layout
