### ISSUE TITLE
[4.0] Incorrect terminology - database name

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#19725]
### Steps to reproduce the issue

2c89b2b
Get to database page on installation

### Expected result

"Specify the database name." for the database name field

"Use table prefix to distinct Joomla sites" Should be moved somewhere else, it doesn't belong in the "table name field" 

### Actual result

"Specify the database **table** name. Use table prefix to distinct Joomla sites"

It is NOT a database table name you are specifying  - it is the database name. 

![screen shot 2018-02-18 at 19 21 55](https://user-images.githubusercontent.com/400092/36355826-3dc5efb4-14e1-11e8-8734-86e0bed5270d.png)

**Comment by Bakual** [comment]
I'm closing this as it looks like a mistake 😄

**Comment by PhilETaylor** [comment]
Please reopen - now populated

**Comment by Quy** [comment]
See PR #19728<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19725">issues.joomla.org/tracker/joomla-cms/19725</a>.</sub>

**Comment by Quy** [comment]
Pending decision on "Use table prefix to distinct Joomla sites" Should be moved somewhere else, it doesn't belong in the "table name field"

**Comment by brianteeman** [comment]
Prefix is the next field

**Comment by PhilETaylor** [comment]
> Prefix is the next field

Correct. 

The english in the sentance is not correct either:

`Use table prefix to distinct Joomla sites.`

**Comment by brianteeman** [comment]
thats not in the amended version

I dont understand why this issue was reopened

**Comment by Quy** [comment]
The request is to rephrase `Use table prefix to distinct Joomla sites.` and move it to `Specify a table prefix or use the randomly generated one.`.

**Comment by brianteeman** [comment]
With PR #19728 the installer looks like this which is correct as far as I am concerned

<img width="486" alt="chrome_2018-02-19_17-09-03" src="https://user-images.githubusercontent.com/1296369/36389647-c15351bc-1597-11e8-8b81-80991781fa5a.png">

**Comment by Quy** [comment]
You're right. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19725">issues.joomla.org/tracker/joomla-cms/19725</a>.</sub>
