### ISSUE TITLE
Articles under a category that has menu item but url still wrong

### ISSUE THREAD

**Issue by petmug** [joomla/joomla-cms#19729]
### Steps to reproduce the issue
I update my articles integration to modern from legacy.. however only the links i recently anchored/linked-up are displaying correct url.

I did create menu items for the categories in which the articles are assigned

### Expected result
If i link now, it will show this link...

https://www.petrianeditingservice.co.uk/reviewing/proofreading-aid

### Actual result
This is what it appears for links i had earlier linked up.. (IF I UNLINK MANUALLY AND LINK AGAIN, THE URL STRUCTURE CHANGES TO ONE ABOVE)
https://www.petrianeditingservice.co.uk/?view=article&id=106:proofreading-aid

### System information (as much as possible)

joomla 3.8.5

### Additional comments
Is there a way I can update all the links from the bad old version to new correct ones automatically and not manually?

Thanks.....

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla coding. For this Reason closing this Issue, thanks.
