### ISSUE TITLE
[4.0] Incorrect validation message

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#19724]
### Steps to reproduce the issue

Attempt to install Joomla4 - use "admin" as the email address, blur

### Expected result

".... is not a valid email address" error

### Actual result

"Field cannot be empty" error
![screen shot 2018-02-18 at 19 19 58](https://user-images.githubusercontent.com/400092/36355808-dcaf9446-14e0-11e8-9662-9b460bcef8b0.png)

### System information (as much as possible)

2c89b2b

**Comment by astridx** [comment]
I can confirm that issue.

**Comment by Quy** [comment]
See PR #19732<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19724">issues.joomla.org/tracker/joomla-cms/19724</a>.</sub>
