### ISSUE TITLE
[4.0] Add yubikey, dont provide secret on login, leads to error

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#19727]
### Steps to reproduce the issue

2c89b2b
Enable 2FA plugin
Enable Yubico key on super admin user using a real key
go to front end
attempt to login with username and password only.

### Expected result

Error telling me to use my secret from Yubikey 

### Actual result

404 error page 

Also note missing icons in interface 

![screen shot 2018-02-18 at 19 37 46](https://user-images.githubusercontent.com/400092/36355977-42d7a7d4-14e3-11e8-8cb2-1424c9fabebf.png)

### System information (as much as possible)

2c89b2b

**Comment by PhilETaylor** [comment]
hmmm this might be something more generic as I also had language switcher enabled... and now all my menu items are 404 with urls like

http://0.0.0.0:8080/index.php/en/blog/4-about-your-home-page/en
http://0.0.0.0:8080/index.php/en/blog/5-your-modules/en
http://0.0.0.0:8080/index.php/en/blog/6-your-template/en

**Comment by brianteeman** [comment]
I cannot replicate this on the current branch
Both site and admin logins without entering the yubikey give the correct error message.
"The two factor authentication Secret Key is invalid."

**Comment by PhilETaylor** [comment]
yup this was part of a bigger routing issue apparently.
