### ISSUE TITLE
[4.0] 404 View not found [name, type, prefix]: featured, html, helloworldView in step 2 of making basic component

### ISSUE THREAD

**Issue by parul-123** [joomla/joomla-cms#19733]
### Steps to reproduce the issue
Go to step of Adding a view to the site part
Create that component
Install that component in joomla
Then try to run the component.

### Expected result
See Hello World written in site

### Actual result
![issue](https://user-images.githubusercontent.com/15813927/36362641-82e381a8-155c-11e8-83d3-379204953aff.png)

**Comment by anuragteapot** [comment]
I think you are developing a joomla MVC  component. It's not a joomla core issue.

**Comment by parul-123** [comment]
Yeah, I am developing joomla MVC component. But I don't know the reason why it is giving me error like that and how to resolve it. Do you have any idea ??

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla Core coding. For this Reason closing this Issue, thanks.

**Comment by anuragteapot** [comment]
@franz-wohlkoenig thanks 

@parul-123 but, for help you can use https://github.com/Stevec4/Joomla-HelloWorld
