### ISSUE TITLE
removeUserFromGroup removes Custom (user) Fields data from user

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#19735]
### Steps to reproduce the issue
create custom user fields for a user
Set ACL for these fields to e.g. author ACL level
Add the user to the author group
Add values for this user to the created custom user fields

1. remove the user from the author group via the back-end user manager
 the user has no access anymore to the custom fields (= correct)
2. add the user to the author group via the back-end user manager
 the user has access to the fields again and all values that where previously filled in by the user are retained

so far so good... now for the issue

3. in your code use public static function removeUserFromGroup($userId, $groupId) (UserHelper.php) to remove the user from the author group
 **the user is removed from the author group AND all values set for the custom user fields for this user are deleted from the database!**
4. add the user (via back-end) to the author user group
 the user can re-enter (**all values are erased!**) again

### Expected result
The user should be removed from the author user group, but the values in the custom fields should be retained just like when removing the user via the back-end.

### Actual result

custom field values should be retained for the user when using public static function removeUserFromGroup($userId, $groupId)

### System information (as much as possible)

Joomla 3.8.5

**Comment by Ruud68** [comment]
when adding a user via public static function addUserToGroup($userId, $groupId) the also the custom field values for this user are erased.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19735">issues.joomla.org/tracker/joomla-cms/19735</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #19753
