### ISSUE TITLE
Search unable to find language constants when language folder located in the extension directory

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#19738]
### Steps to reproduce the issue
Install the system plugin Sourcerer from JED:
https://extensions.joomla.org/extension/sourcerer/
https://www.regularlabs.com/extensions/sourcerer/features#sourcerer_downloads_free

Enable the plugin.
Go to Languages - Create a New Override.
Search text you want to change:  copy and paste for example the following text:
SRC_TOGGLE_SOURCE_TAGS

### Expected result
The language constant is found

### Actual result
No matching texts found

### System information (as much as possible)
Environment 1: Wampserver, PHP 7.0.10, Joomla 3.8.5 and also Joomla 3.9 latest nightly build.
Environment 2: Linux, PHP 7.0.27, Joomla 3.8.5

### Additional comments
This behaviour is not limited to the extension Sourcerer. Confirmed this with a small 'Hello World' system plugin but was unable to attach it to this ticket.  

Tried Search with location set to both Site and Administrator with the same result.  If you use the language constant and add a new text as override, it works all right in both Site and Administrator when the overrides are created separately, or when 'Both' is selected.

According to @mbabker, "Since 1.6 core has supported a language folder in the extension directory and the override system should support finding those files." Ref. https://forum.joomla.org/viewtopic.php?f=706&t=959242#p3513752

**Comment by brianteeman** [comment]
Confirmed

**Comment by infograf768** [comment]
The code exists
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_languages/models/strings.php#L26

but I can't see where it is used.

**Comment by infograf768** [comment]
Should be used by the overrider.js

`Joomla.overrider.refreshCache`

@dgt41 
can you look at this please?

**Comment by infograf768** [comment]
I think I found the issue. Give me a few minutes

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/19740

**Comment by infograf768** [comment]
Note: it should not be broken for components, modules and templates as these are 3 levels deep only.
