### ISSUE TITLE
Adding new tag from mobile phone

### ISSUE THREAD

**Issue by webchun** [joomla/joomla-cms#19746]
### Steps to reproduce the issue
- Login to joomla using mobile phone
- Add new article
- Add a new tag

### Expected result
- I'm able to add new tag just like when I'm using desktop browser 
![screen shot 2018-02-21 at 02 29 59](https://issues.joomla.org/uploads/1/aa40dd83395d12831b8404a00a6b0f28.png)

### Actual result
It is impossible to add new tag. I'm able to add existing tag only
![screen shot 2018-02-21 at 02 32 11](https://issues.joomla.org/uploads/1/1af646a396291c6ae842ec48989096ab.jpg)

### System information (as much as possible)
Joomla 3.8.5

**Comment by webchun** [comment]
Hmm I'm just realized that it's because of chosen plugin limitation ![https://github.com/harvesthq/chosen/pull/1388](https://github.com/harvesthq/chosen/pull/1388)
Hopefully there will be a workaround for this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19746">issues.joomla.org/tracker/joomla-cms/19746</a>.</sub>

**Comment by ghost** [comment]
closed as no Core-Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19746">issues.joomla.org/tracker/joomla-cms/19746</a>.</sub>
