### ISSUE TITLE
[4.0] Installation database name field hint text is confusing

### ISSUE THREAD

**Issue by ThomasFinnern** [joomla/joomla-cms#19745]
New text for database name
"Specify the database table name. Use table prefix to distinct Joomla sites. "

### Steps to reproduce the issue

3rd step in J!4 installtion

### Expected result
text "database name"

### Actual result

"Specify the database table name. Use table prefix to distinct Joomla sites. "

### Additional comments

It may be intentionally but for me the text is confusing: why table and not database ?

If i am on a wrong track just close the issue

**Comment by anuragteapot** [comment]
duplicate issue #19725 please close this.

And test this PR #19728 

Thanks
