### ISSUE TITLE
Show only categories filtered in the article creation form.

### ISSUE THREAD

**Issue by segundochinguel** [joomla/joomla-cms#19747]
### Steps to reproduce the issue
Good morning, maybe it's not the right place to ask, but I'm trying to avoid displaying all my categories in the select control when I'm going to create a new article and only display the one I select after doing the search.

### Expected result
It should be displayed in the select control only the categories selected after doing a search.

### Actual result
All the existing categories are displayed, which slows the loading of the form when you have more than one thousand registered categories.

### System information (as much as possible)
Joomla 3.8.3

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.

Also please upgrade to the latest Version (3.8.5).
