### ISSUE TITLE
Call to undefined method JText::getScriptStrings()

### ISSUE THREAD

**Issue by doncheli** [joomla/joomla-cms#19759]
### Steps to reproduce the issue
Upgrade from 3.8.3 to 3.8.5 

### Expected result
Everything must be work without issues

### Actual result
Frontend issue: https://screencast.com/t/CkWBkrqm60d Backend Works fine.

### System information (as much as possible)
Apache, Php 5.4, Godaddy Hosting

### Additional comments
I made the upgrade Joomla and some components between them some languages, and now the frontend doesn't work, it shows error: 

Fatal error: Call to undefined method JText::getScriptStrings() in /home/hostelsystem/public_html/gooodbyelenin.pl/libraries/src/Document/HtmlDocument.php on line 148

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.
