### ISSUE TITLE
[4.0] - Menu Item Type - Edit single article working inciorrect

### ISSUE THREAD

**Issue by nhungredweb** [joomla/joomla-cms#19755]
### Step proceduce
1. Create new Menu Item Type is Single article and assign for one article
![image](https://user-images.githubusercontent.com/23624614/36547983-b53ed59a-1821-11e8-9d27-adef2c35c324.png)
2. Clicks on " Edit" button 
![image](https://user-images.githubusercontent.com/23624614/36548014-c28aef7c-1821-11e8-91a4-7e797e77ee95.png)
Webpage doesn't show content of the article 

### Expected result
I think . we should show the content and title of the article belong this menu item

### Actual result
Webpage doesn't show content of the article 

### System information (as much as possible)
joomla 4.0.0.alpha2
php 7.0

**Comment by ghost** [comment]
thanks for report, but its a duplicated one #19316, please test #19390, thanks.
