### ISSUE TITLE
BUG: Page Class Suffix wrong Output

### ISSUE THREAD

**Issue by hacki65** [joomla/joomla-cms#19757]
### Steps to reproduce the issue
Set a pageclass suffix in a menu for a single article (as example) and check the output on frontend.
In this cass the class is "ht-startseite"

### Expected result
Pageclass suffix is divided with a space like this: `<div class="item-page ht-startseite" itemscope itemtype="https://schema.org/Article">`

### Actual result
No space between the classes: `<div class="item-pageht-startseite" itemscope itemtype="https://schema.org/Article">`

### System information (as much as possible)
Joomla! 3.8.5

### Additional comments
This behaviour seems to be a long time, but nobody has seen it.
Example code from "/components/com_content/views/article/tmpl/default.php" line 27:
`<div class="item-page<?php echo $this->pageclass_sfx; ?>" itemscope itemtype="https://schema.org/Article">`

Possible change (see space before the echo): <div class="item-page <?php echo $this->pageclass_sfx; ?>" itemscope itemtype="https://schema.org/Article">

This bug is in many tmpl output files. At the moment only a leading space in the page class suffix field like this will help: " ht-startseite". But who knows this?

Sorry for my bad english - i hope anybody understands it.

**Comment by mbabker** [comment]
It's the way the system is designed.  The suffix field allows you to either suffix an existing class (whatever the last one is before the param's value is printed) or add additional classes, resulting in you being able to replace a class or add additional ones.

**Comment by hacki65** [comment]
But in this case the system should be redesigned? ;)

**Comment by hacki65** [comment]
BTW: i know that 2 or more classes need a space between

**Comment by mbabker** [comment]
It's a long standing debate that never dies.  You can do it both ways, neither way will appease everyone and both ways will result in bug reports that the behavior should be the opposite of what it is.  It's just one of those opinionated features.

**Comment by hacki65** [comment]
Than a better description will help?

**Comment by brianteeman** [comment]
For your information for Joomla 4 it has been redesigned
