### ISSUE TITLE
Icons missing, just text shown?

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#19765]
See:

<img width="334" alt="screenshot 2018-02-23 15 24 24" src="https://user-images.githubusercontent.com/1400982/36601742-cd42bca6-18ad-11e8-9820-4595c2ed2fda.png">

We have yes / no being shown when the user access level is above the current users. This should instead be greyed out icons should they not?

**Comment by brianteeman** [comment]
IIRC bootstrap doesnt do nice fdsabled buttons

**Comment by tonypartridge** [comment]
@brianteeman you remember incorrectly :P see the last one in the list. bottom left is the only non-faded one. Because this use cannot activate the account

**Comment by brianteeman** [comment]
The relevant code begins here https://github.com/joomla/joomla-cms/blob/c9e45bb6f5718993f4bc0a36a23cccd3162b16cd/administrator/components/com_users/views/users/tmpl/default.php#L126

**Comment by tonypartridge** [comment]
So straight away we can see why. Ok I’ll try and do a pull later.

**Comment by brianteeman** [comment]
Yes not hard to fix but I would also look at the history to see if there was a specific reason

**Comment by tonypartridge** [comment]
History doesn’t state anything obvious for that change intact I went back to 2015 and couldn’t see anything to that.

**Comment by brianteeman** [comment]
Might be this one from 2012 https://developer.joomla.org/joomlacode-archive/issue-29244.html

**Comment by tonypartridge** [comment]
Closing as we have a PR
