### ISSUE TITLE
JHtml image. Parameter $returnPath = -1 returns image path instead of image tag

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#19762]
### Steps to reproduce the issue
- Have a look at DocBlock description of HTMLHelper::image()
https://github.com/joomla/joomla-cms/blob/staging/libraries/src/HTML/HTMLHelper.php#L566-L568

`-1: Returns a <img> tag without looking for relative files`

- Add PHP code in your template's index.php and see the output in HTML source code of loaded page.
```
$img = 'images/thing.jpg';
$name = 'Thing is Thang';
$attribs = '';
$img = JHtml::_('image', $img, $name, $attribs, false, -1);
echo $img;
exit;
```
### Expected result
Method should return
```
<img src="images/thing.jpg" alt="Thing is Thang" />
```
because the last parameter (`$returnPath`) is `-1` in code above

### Actual result
Method returns only a path
```
images/thing.jpg
```
which should be only the case if `$returnPath = 1` (and file exists in a calculated relative path; otherwise empty path).

**Comment by Quy** [comment]
Confirmed. Can you please do a PR? Thanks.

**Comment by ReLater** [comment]
See PR https://github.com/joomla/joomla-cms/pull/19770
