### ISSUE TITLE
Joomla article Intro text show/hide option doesn't work

### ISSUE THREAD

**Issue by heytoufiq** [joomla/joomla-cms#19761]
### Intro text show/hide option doesn't work. 
https://prnt.sc/iiluic
https://prnt.sc/iiluol
https://prnt.sc/iilubw
Above the screenshots, settings don't work. 

### unexpected result
https://prnt.sc/iilvc8

### Expected result
https://prnt.sc/iilv7x

### System information (as much as possible)
Joomla latest version 

### Additional comments
Where should I do? Please give me instructions

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.

**Comment by heytoufiq** [comment]
Hi, So what do you think about the issue? There is no bug? Thanks <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19761">issues.joomla.org/tracker/joomla-cms/19761</a>.</sub>

**Comment by infograf768** [comment]
No bug. The tip explains it perfectly. 
<img width="376" alt="screen shot 2018-02-23 at 08 19 38" src="https://user-images.githubusercontent.com/869724/36582586-636a61b6-1872-11e8-9547-8a5b30c34f86.png">

"when you drill down" is the key here.
