### ISSUE TITLE
[4.0] Menu Accessibility

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#19763]
The code for the menu looks something like this

```
<div class="main-nav-container" **role="navigation"** aria-label="Main menu">
       <ul id="menu" class="nav navbar-nav nav-stacked main-nav clearfix ">
              <li **role="menuitem"**><a class="no-dropdown" href="index.php" target=""><span class="sidebar-item-title">Control Panel</span></a></li>
```

Role = menuitem must have a parent role=menu

However there is much more to it than that to make the entire menu accessible. Either the a11y team can take this on board or I will ask for assistance on this from an external a11y expert

Reference https://www.w3.org/WAI/tutorials/menus/

**Comment by zwiastunsw** [comment]
Thanks Brian. JAT will prepare an expert opinion in the near future.

**Comment by brianteeman** [comment]
Is it the near future yet
