### ISSUE TITLE
[4.0] IDNA-Convert script update

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#19777]
The version we have is 0.8 but there is now 1.0 (cant be used in J3.X because it requires php5.6

It is a B/C breaking release
> BC break: As of version 1.0.0 the class closely follows the PSRs PSR-1, PSR-2 and PSR-4 of the PHP-FIG. As such the classes' naming has been changed, a namespace has been introduced and the default IDN version has changed from 2003 to 2008 and minimum PHP engine version raised to 5.6.0.

**Comment by mbabker** [comment]
PR #19778
