### ISSUE TITLE
Empty page after using the filter in Contacts List

### ISSUE THREAD

**Issue by WoodyF4u** [joomla/joomla-cms#19773]
### Steps to reproduce the issue
Create some contacts in the component Contacts.
Create a new menu item of the type Contacts - List All Contact Categories
Go to the tab List Layouts and check if the Filter Filed is: Show.
Check at the frontend if you have a menu item thats shows a list of contacts and the filter field above.
Then type a name that is not a contact in the list in the filter field and press Enter.
In my case I see the text COM_CONTACT_NO_ARTICLES.
But on other sites there will be a language text displayed.
But more important... The list is gone!
Sometimes t is possible to reload the list by clicking the menu item again.
But at some other sites nothing happened aanymore when I clicked at the menu item.
For a website visitor with no knowledge of browser caching, this can be very anoying.

### Expected result
When there is a name entered in teh filter field which is not at the list of contacts, there should be a good message shown. 
And the list of contacts should still be vissible at the page.

### Actual result
See above

### System information (as much as possible)
Joomla 3.8.5
Different templates

### Additional comments
No

**Comment by brianteeman** [comment]
The fact that you can see COM_CONTACT_NO_ARTICLES indicates a problem with your installation (or perhaps template)

**Comment by Pinkeltje** [comment]
Missing text is indeed template problem. But the fact that the list disappears is not. See [this site](http://yndidev.tk/374/ "this site") for basic installation with Protostar.

![screen shot 2018-02-25 at 09 53 11](https://issues.joomla.org/uploads/1/4a8b1148e30b15c9f1b5aaca59669203.png)
![screen shot 2018-02-25 at 09 53 24](https://issues.joomla.org/uploads/1/ef07ab7c2f12ab3dfb17bd62d5ba83a5.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19773">issues.joomla.org/tracker/joomla-cms/19773</a>.</sub>

**Comment by SharkyKZ** [comment]
Test PR #20126 please.

**Comment by Pinkeltje** [comment]
Tested succesfully. Thx!

**Comment by ghost** [comment]
@Pinkeltje please mark your Test as successfully:

- open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/20126)
- Login with your github-Account
- Click on blue "Test this"-Button above Authors-Picture
- mark your Test as successfully
- hit "submit test result"

**Comment by ghost** [comment]
closed as having Pull Request #20126
