### ISSUE TITLE
PHP version check plugin

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#19783]
Spotted the following on a site running php 5.4

> We have detected that your server is using PHP 5.4.16 which is obsolete and no longer receives official security updates by its developers. The Joomla! Project recommends upgrading your site to PHP 5.6 or later which will receive security updates at least until 2018-12-31. Please ask your host to make PHP 5.6 or a later version the default version for your site. If your host is already PHP 5.6 ready please enable PHP 5.6 on your site's root and 'administrator' directories – typically you can do this yourself through a tool in your hosting control panel, but it's best to ask your host if you are unsure.

Two questions
1. Shouldnt we be recommending a version that is still actively supported

2. The code says
```
Find the oldest PHP version still supported that is newer than the current version,
 this is our recommendation for users on unsupported platforms
```
But what we are actually doing is finding the oldest version that is not end of active support.

**Comment by mbabker** [comment]
"Active support" is subjective.  I consider something receiving at least security fixes as actively supported (i.e. PHP 5.6 and 7.0 as of today), others consider full support (bug and security fixes) as active support (i.e. PHP 7.1 and 7.2 as of today).  So it depends what we want to consider as active support in the scope of the message.  If we decide it falls in the bug and security fix realm then we need to adjust the language strings and the code deciding what the oldest supported version is, otherwise the recommendation logic is fine as is.

**Comment by brianteeman** [comment]
I took the meaning of the phrase "active support" from the referenced php page https://secure.php.net/supported-versions.php

**Comment by mbabker** [comment]
Seems fair to change it to follow that definition then.

**Comment by brianteeman** [comment]
and shouldnt the code be updated so that
"support" ==> "sucurity_only"
"eos" ==> "eol"

**Comment by mbabker** [comment]
What exactly are you referring to?  In the code's date array "eos" is used to mark the date any form of support ends (same as "eol", more PC if you get into "end of life" versus "end of support" phrasing debates) and "security" refers to the date end of active support happens (basically it's in security only mode at that point).

**Comment by brianteeman** [comment]
never thought of the PC issue

**Comment by shubham59** [comment]
if the plugin is created, when and how should it appear to the user?? Should it appear everytime the user login to his account??

**Comment by shubham59** [comment]
which plugin group should be used for the development?? I am considering the group "onUserAfterLogin"?? Kindly suggest if that's correct??

**Comment by ReLater** [comment]
@shubham59 
This plugin already exists. It's called "Quick Icon - PHP Version Check" and is a core plugin.
It's displayed in Control Panel.
