### ISSUE TITLE
(4.0.0-dev) installation files not deleted

### ISSUE THREAD

**Issue by JeroenBruin77** [joomla/joomla-cms#19786]
### Steps to reproduce the issue
Upload files with FTP
Go to URL
Install Joomla 4.0
Set "remove installation files" option

### Expected result
Installation directory deleted

### Actual result
Installation directory isn't deleted

### System information (as much as possible)
Installation took place with Chrome browser

**Comment by dgrammatiko** [comment]
This functionality is not yet implemented on purpose

**Comment by JeroenBruin77** [comment]
ok thanks for replying<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19786">issues.joomla.org/tracker/joomla-cms/19786</a>.</sub>
