### ISSUE TITLE
mod_menu. Split menu. Expected behavior?

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#19793]
### Steps to reproduce the issue
- Joomla 3.8.5 or current staging.

- Create menu structure with 3 or 4 levels. In my example/images menu name is "Main Menu-EN"

```
-  Level 1
- - Level 2
- - - Level3
- - - - Level 4
```

- Create a module of type mod_menu. Settings:
![27-02-_2018_12-50-18](https://user-images.githubusercontent.com/20780646/36727338-29c3c152-1bbd-11e8-9ceb-3b6523315349.png)

- Create another module of type mod_menu. Settings:
![27-02-_2018_12-55-27](https://user-images.githubusercontent.com/20780646/36727457-96237c8e-1bbd-11e8-9e4f-0f1036f50ea6.png)

- Don't forget position and menu association "On all pages"

- Go to frontend and open menu item "**Level 1**"

### Expected result
Both modules with split menus of level 2 and level 3 are shown.

### Actual result
Only level 2 menu is displayed. For level 3 menu ModMenuHelper returns an empty list.
Because of line https://github.com/joomla/joomla-cms/blob/3.8.5/modules/mod_menu/helper.php#L69

### Additional comments
Is this really the expected behavior? If yes, I don't understand why.

**Comment by brianteeman** [comment]
Seems to work ok for me

![menu](https://user-images.githubusercontent.com/1296369/36728490-d41a1944-1bb8-11e8-8455-66cd7a89f662.gif)

<img width="286" alt="chrome_2018-02-27_12-18-45" src="https://user-images.githubusercontent.com/1296369/36728512-e546ba42-1bb8-11e8-8713-09046a6673f2.png">
<img width="364" alt="chrome_2018-02-27_12-18-56" src="https://user-images.githubusercontent.com/1296369/36728513-e5f585f4-1bb8-11e8-8d47-83514f40876b.png">
<img width="403" alt="chrome_2018-02-27_12-19-18" src="https://user-images.githubusercontent.com/1296369/36728514-e625aa86-1bb8-11e8-87f6-49e8c1bd4e58.png">
<img width="419" alt="chrome_2018-02-27_12-19-33" src="https://user-images.githubusercontent.com/1296369/36728515-e653973e-1bb8-11e8-998f-ea6c44749fbd.png">

**Comment by ReLater** [comment]
But if you click menu item "Level 1" there is no module "Level **3**". Only "Level 2".

**Comment by brianteeman** [comment]
Thats correct and expected unless you change the base item setting.

For example if your menu structure was something like this then there is no way to know when you are level 1a what level 3 to display. 
Level 1a
---Level 1a2a
-----Level 1a2a3a
-----Level 1a2aa3b
---Level a2b
-----Level 1a2b3a
-----Level 1a2aa3b
Level 1b
---Level b2a
-----Level 1b2a3a
-----Level 1b2aa3b
---Level b2b

**Comment by ReLater** [comment]
Thank you!
