### ISSUE TITLE
Modules in articles error

### ISSUE THREAD

**Issue by Bill890** [joomla/joomla-cms#19797]
### Steps to reproduce the issue
1. Create banner module / custom module (Let's for example name them "Banner One" & "Custom One"
2. Create a new article, complete writing it
3. Hit the "module" button
4. Choose your module(s) to insert
5. View your article (everything works fine now)
6. Rename your modules to any name like "Banner One X" & "Custom One Z" (names just for demonstration obviously)
7. The modules will NOT appear in article any more.
8. Some will say you have to update it. Ok. Go to article, open it. You will see the old name there.
9. Delete the old "{loadmodule..." and load the new "Banner One X" & "Custom One Z"
10. Save it. Modules will NOT appear.

So, once you change a modules name you CAN NOT use it in an article any more.

### Expected result
Should be updated and should be able to use the modules even when renamed

### Actual result
Can't use modules if renamed.

### System information (as much as possible)
Joomla 3.8.5

**Comment by infograf768** [comment]
It works fine here after modifying the title of the module in the article.
I guess you may have to clear all caches.

**Comment by Bill890** [comment]
Hi, I completely deleted and replaced the module in the article and still was not working after clearing caches. That's why I thought I must report that.

**Comment by brianteeman** [comment]
thats definitely a cache issue - closing
