### ISSUE TITLE
Weirdest ever bug in Joomla: menu voice "Sun" become "Dom"

### ISSUE THREAD

**Issue by simbus82** [joomla/joomla-cms#19800]
### Steps to reproduce the issue
Create a menu voice with title "Sun", save and close.

### Expected result
In the menu i must see (image edited to reproduce expected result)
![image](https://user-images.githubusercontent.com/1375730/36786058-4d5b4f36-1c85-11e8-885e-63e24e3996e3.png)

### Actual result
:scream: :scream: :scream:
![image](https://user-images.githubusercontent.com/1375730/36786088-61a8df6c-1c85-11e8-8120-8c37d385f552.png)

**Sun** becomes **Dom** ... WHY?

### System information (as much as possible)
Versione di Joomla! | Joomla! 3.8.5 Stable [ Amani ] 6-February-2018 15:00 GMT
-- | --
Versione piattaforma Joomla! | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

### Additional comments

I have tested this on 10 joomla websites, with php 5.6.x and 7.x, the result is the same!
Tested on Chrome, Firefox, Edge.

**Is "sun" a magic word???**

If you write "sun" or "Sun" or "SUN" the result is the same. If i write "Sun " (with a space at the end) i can see "Sun" in menu voice.

It's so weird!

**Comment by brianteeman** [comment]
I am going to guess that you either have a browser plugin that is autotranslating from English to Italian or you have a joomla plugin that is doing the same.

If you check in the database I am pretty certain you will find that it is written as Sun in the database

**Comment by simbus82** [comment]
UPDATE

I have found in /language/it-IT/it-IT.ini string translations for SUN to Dom (Domenica in italian).

No auto translate, we have tested with many people, is a clean joomla installation.

The real problem is that if i write in menu voice, in "title" field, any EN COSTANT that i have in Joomla language file for italian, i see the translation in joomla administrator!

Can you try after installing it_IT language?

**Example**
![image](https://user-images.githubusercontent.com/1375730/36786880-49aa3dae-1c88-11e8-9025-18e80ef713be.png)

**Becomes**
![image](https://user-images.githubusercontent.com/1375730/36786900-59edde46-1c88-11e8-97ce-675029708f28.png)

Is it an expected behavior that menu item fields use language overrides?

**Comment by brianteeman** [comment]
The language strings should not be able to change user created text

You have discovered a bug!!! I can confirm this with any language

**Comment by brianteeman** [comment]
By turning on language debug I can see that Joomla is trying to translate that string because it is wrapped in the **

This should not happen

<img width="483" alt="chrome_2018-02-28_12-13-47" src="https://user-images.githubusercontent.com/1296369/36787145-f3d6ad4c-1c80-11e8-98b8-6751d0ddb709.png">

**Comment by simbus82** [comment]
Oh yes, I saw. For now I will use "sun" with a space. Is there anything that can be "patched" for now?

**Comment by brianteeman** [comment]
it will need investigating to find the problem. it should not have been effecting the front end of the site

**Comment by brianteeman** [comment]
@infograf768 @wilsonge any ideas

**Comment by simbus82** [comment]
Maybe this?

https://github.com/joomla/joomla-cms/commit/4e156fa0ad46cfcbc089311a66fe8b99d21b49eb#diff-9fff16ee0e30dd09816ee172c6f5909a

"Translate menu item titles in list view. Ref #2"

**Comment by brianteeman** [comment]
Sounds like thats a possibility

**Comment by brianteeman** [comment]
The problem is in the function here https://github.com/joomla/joomla-cms/blob/1da376ed370d59f34b9399f10c67e7c573f0bf25/administrator/components/com_menus/models/items.php#L514
and specifically this line which should have a check to ensure that the client_id != 0 
`					$item->title = JText::_($item->title);`

**Comment by brianteeman** [comment]
Fix coming

**Comment by brianteeman** [comment]
Closed please test #19802

**Comment by simbus82** [comment]
Great! Thanks a lot!
