### ISSUE TITLE
[4.0] how to disable MySQL strict mode ONLY_FULL_GROUP_BY

### ISSUE THREAD

**Issue by albertusputra** [joomla/joomla-cms#19808]
by default joomla MySQL driver always set MySQL strict mode for
ONLY_FULL_GROUP_BY
how to I disable it? because the mode causing many issue if my component having complex query

**Comment by ReLater** [comment]
See discussion here
https://github.com/joomla/joomla-cms/pull/12494

[There's also a comment with a "not nice" workaround](https://github.com/joomla/joomla-cms/pull/12494#issuecomment-317554376)

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19808">issues.joomla.org/tracker/joomla-cms/19808</a>.</sub>
