### ISSUE TITLE
Joomla alias allows comma in alias

### ISSUE THREAD

**Issue by franzpeter** [joomla/joomla-cms#19803]
### Steps to reproduce the issue
Create a new article with a title containing a comma for example as title: My title, long title and click on SAVE button. Joomla will create an alias like my-title,-long-title. Question is: is comma allowed in alias?

### Expected result
comma filtered out while auto create alias

### Actual result

with comma

### System information (as much as possible)
Joomla 3.8.5

### Additional comments
I do not know if that is intended or fine to have comma in alias.

**Comment by brianteeman** [comment]
I tested the creation of an alias in both an article and a menu item
The title I used was **new, old, and brave** and in both cases the alias that was generated was **new-old-and-brave**

**Comment by Bakual** [comment]
Depends if "Unicode Alias" are enabled or not. If enabled, the alias may contain a coma.
I guess that is ok since comas aren't invalid URL characters to my knowledge.

**Comment by franzpeter** [comment]
It seems to be a server issue. I use php 7.2.2 with Plesk and php is running as FPM application served by nginx. Did test on localhost without Nginx and using php 7.2.1 cgi-fcgi, issue does not occur. Did switch the live server to use php with FastCGI served by Apache, same issue. So maybe is php 7.2.2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19803">issues.joomla.org/tracker/joomla-cms/19803</a>.</sub>

**Comment by brianteeman** [comment]
@bakual - good catch yes it does require unicode alias to be on for this to occur

**Comment by mbabker** [comment]
Personally I don't see the issue with it so long as commas are valid characters in URI slugs, but if anyone does want to change the behavior [send a PR changing this method](https://github.com/joomla-framework/filter/blob/b87e642d075dd390f264f58fdb314e0a14447b0a/src/OutputFilter.php#L124-L147).

**Comment by franzpeter** [comment]
Yes, if switching off unicode alias it does not occur. But if commas are valid characters in slugs in case of activated unicode alias I think the issue could get closed. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19803">issues.joomla.org/tracker/joomla-cms/19803</a>.</sub>

**Comment by brianteeman** [comment]
a comma is a reserved character as a sub-delimiter http://www.ietf.org/rfc/rfc3986.txt

**Comment by Bakual** [comment]
Afaik, comas are allowed (not reserved) in the path part of an URI. Which is the case here. It's up to the application if it is used as delimiter or just a generic char.

**Comment by ghost** [comment]
Issue closed as stated by @franzpeter ([Comment](https://github.com/joomla/joomla-cms/issues/19803#issuecomment-369388070))
