### ISSUE TITLE
v.3.8.5 Article Options tabs Missing

### ISSUE THREAD

**Issue by tgarzon** [joomla/joomla-cms#19813]
### Steps to reproduce the issue
Open an article to edit it or create a new article

### Expected result
The five tabs of the article management should appear (Content, Options, Publishing, Configure Edit Screen Permissions and Images and Links)

### Actual result
Only display Content tab

### System information (as much as possible)
Joomla 3.8.5
php 7.0

### Additional comments
I cann´t continue managing my website with this error

**Comment by Ruud68** [comment]
is this maybe related? issue for me was in broken editor plugin (found out by turning them off one by one)
https://issues.joomla.org/tracker/joomla-cms/14559<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19813">issues.joomla.org/tracker/joomla-cms/19813</a>.</sub>

**Comment by zero-24** [comment]
As this has been about a plugin called `ADVPoll` and not about the core I'm going to close here. Thanks.
