### ISSUE TITLE
Upgraded to Joomla 3.8.5 And Component Menu Items Disapeared

### ISSUE THREAD

**Issue by mbeckfl** [joomla/joomla-cms#19824]
### Steps to reproduce the issue
Upgraded automatically to Joomla 3.8.5
Discovered upgrades and updated database
Cleared cache and made all Joomla components active

### Expected result

Admin menu for components should not have changed. Under Menu Item Type the option "Contacts" ist not displayed anymore. 

### Actual result

When I go into my "main menu" where there was a link to a single contact - The menu type was empty and the link leads to a 404 page. 

When I choose menu type, contacts is not available anymore or seems to have disappeared.

This was the original page: http://webcache.googleusercontent.com/search?q=cache:oC2I9Uhjxe8J:www.kwg-zucht.ch/index.php/home/kontakt+&cd=2&hl=de&ct=clnk&gl=li

New: An error 404, page not found is shown. 

### System information (as much as possible)
 
PHP erstellt für | Linux hos110.unaxus.net 2.6.32-896.16.1.lve1.4.51.el6.x86_64 #1 SMP Wed Jan 17 13:19:23 EST 2018 x86_64
Datenbankversion | 5.6.38
Datenbankzeichensatz | latin1_swedish_ci
Datenbankverbindungszeichensatz | utf8mb4_general_ci
PHP-Version | 5.6.33
Webserver | Apache
PHP-Interface für den Webserver | cgi-fcgi
Joomla!-Version | Joomla! 3.8.5 Stable [ Amani ] 6-February-2018 15:00 GMT
Joomla!-Plattform-Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Browsererkennung | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

### Additional comments
Tried to follow these steps, but couldn't find a solution :-( https://github.com/joomla/joomla-cms/issues/15719  

The alias for my main menu is "mainmenu" not "main" if that makes a difference (German interface)

Can anyone help me? Thanks in advance!!!

**Comment by Quy** [comment]
Please ask help in [Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710) forum. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19824">issues.joomla.org/tracker/joomla-cms/19824</a>.</sub>
