### ISSUE TITLE
Unable to sort by Association in Categories

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#19820]
### Steps to reproduce the issue
Install a multilingual site
Go to Contents > Categories
Click on `Association` column header
or 
Click `Sort Table By` dropdown

### Expected result
Column to be sorted

### Actual result
Column not sorted

In the dropdown, missing `Association ascending` and `Association descending`.
![association](https://user-images.githubusercontent.com/368084/36935336-967e675c-1eab-11e8-9c78-026694854c85.jpg)

### System information (as much as possible)
v.3.8.5

**Comment by infograf768** [comment]
Confirmed. It works fine for articles.
I can solve the sort table By easily, but I still have to find out how to get the small sign near the column heading.
Let me see that.

**Comment by infograf768** [comment]
OK, making patch now.

**Comment by infograf768** [comment]
Patch ready https://github.com/joomla/joomla-cms/pull/19821
Thanks for your findings.
Closing
