### ISSUE TITLE
[4.0] No "Proceed"-Button

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#19827]
### Steps to reproduce the issue
1. Create an admin menu
2. Create some menu items in this admin menu
3. Select some menu items and click toolbar button batch

### Expected result
An modal is opening. You can choose your action and click <tt>proceed</tt> like for menu items of a site menu.

### Actual result
You do not see a <tt>proceed</tt> button.

![menus items test1 tes administration](https://user-images.githubusercontent.com/9974686/36944353-8a783862-1f9a-11e8-8a67-e42f6cdff606.png)

**Comment by ghost** [comment]
changed Title.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19827">issues.joomla.org/tracker/joomla-cms/19827</a>.</sub>

**Comment by tonypartridge** [comment]
If you change the move / copy does it activate the button?

**Comment by astridx** [comment]
@tonypartridge No, that does not activate the button.

**Comment by dgrammatiko** [comment]
I cannot replicate either 
![screen shot 2018-03-04 at 21 09 02](https://user-images.githubusercontent.com/3889375/36950017-653fcac8-1ff0-11e8-8762-6c6e2503e0cd.png)

**Comment by astridx** [comment]
@dgt41 Could it be that you do not use a admin menu. I think this is a screen of a site menu

**Comment by dgrammatiko** [comment]
Ooops, probably got it wrong here 😓

**Comment by Quy** [comment]
See PR #19879<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19827">issues.joomla.org/tracker/joomla-cms/19827</a>.</sub>
