### ISSUE TITLE
Feature Request: com_media missing search functionality

### ISSUE THREAD

**Issue by gunjanpatel** [joomla/joomla-cms#19853]
Imagine that user has more than 500 images and the user would like to search it by name, if we get search bar it would be easy to find the image and select it for the article instead of just looking into thumbnails.

It should also be possible to search using substring.

### Expected result
We should be able to search for images in media manager.

### Actual result
We can't search based on image name in media manager in the current version.

### Additional comments
We apologise if this feature is already proposed by someone and we had the conversation on it. We have tried to find this kind of feature requests but we haven't found it so we thought it would be great to suggest the idea.

(We have discussed this feature during our JUG Sorø bug squashing event and didn't found any proposal so far.)

**Comment by nmousedk** [comment]
yes... It would be a nice thing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19853">issues.joomla.org/tracker/joomla-cms/19853</a>.</sub>

**Comment by Quy** [comment]
For a temporary solution, you can use the browser's built-in find to search in the current directory.

**Comment by proman24** [comment]
@gunjanpatel 
Search based on the file name of the image or on the bases of features in the image like what google photos do to the images.

**Comment by zero-24** [comment]
cc @laoneo Maybe something like this can be build in then new MM for 4.0?

**Comment by tonypartridge** [comment]
@laoneo, shouldn’t be too hard to add into J4?

**Comment by laoneo** [comment]
We have already an open issue for that in the MM repo https://github.com/joomla-projects/media-manager-improvement/issues/175. Recursive search would be hard, especially with cloud adapters. But searching in the current folder can be done in the client.

**Comment by tonypartridge** [comment]
I was thinking just searching this folder for now?

**Comment by kasvith** [comment]
In NMM also recursive search was implemented in backend for local adapter i guess, 

For clouds they offer search endpoints so we can use them with nmm most of the time, depends highly on adapter implementation

**Comment by gunjanpatel** [comment]
> But searching in the current folder can be done in the client.

I think it would be great to start adding search inside the currently selected directory in the initial version. We can always improve it. It's better than nothing. Most of the time user want to search in the current level. Results can be both folders and files.

**Comment by laoneo** [comment]
@kasvith you are right. Forgot that.

Despite that I would also start with the current folder. It will be more reactive as everything can be done on the client site.

**Comment by tonypartridge** [comment]
I would probably search current folder and then when we want to add a tick box to search sub folders too?

**Comment by kasvith** [comment]
@laoneo for current folder it can be done in client, but as we planned to move for **Streams** i think we need to do a query from backend as we do not load whole folder (_imagine a folder with 1000 files_) at once.

But **for now** we can **search** in client side.

**API Endpoints are available for recursive search**

So its a matter of implementing frontend side

**Comment by zero-24** [comment]
Ok given on the feedback by @laoneo and @kasvith I'm going to close this one here as the development of the 4.0 MM is done in the issue pointed above (joomla-projects/media-manager-improvement#175) Thanks for the suggestion 👍

**Comment by dgrammatiko** [comment]
> but as we planned to move for Streams

Is this decided?

**Comment by gunjanpatel** [comment]
This feature is merged into https://github.com/joomla-projects/media-manager-improvement/pull/529

Great job. Thanks a lot, guys.
