### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by rbernard20** [joomla/joomla-cms#19859]
Hello, my site was working perfectly. I downloaded a blogging extension by Blog Factory and all of a sudden some of my Main Menu items on my website do not work. I have been updated for over a week now on all my extensions and Joomla 3.8.5. I get the error 

Fatal error: Call to undefined method Joomla\CMS\Date\Date::setOffset() in /home/preci7/public_html/10/templates/rt_quasar_j15/html/com_content/article/form.php on line 18

I would like to fix this error so I can access my pages again.

Thank you!

**Comment by Quy** [comment]
Please ask help from Blog Factory or in [Joomla Forum](https://forum.joomla.org/).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19859">issues.joomla.org/tracker/joomla-cms/19859</a>.</sub>
