### ISSUE TITLE
[4.0] Created By Alias name

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#19856]
### Steps to reproduce the issue
On the Tab 'Publishing' we do have the label 'Created by Alias' in Contacts, Banners and Articles (although in Contacts it is 'Created By Alias' with capital 'B').
In Tags this is called 'Author's Alias'. Maybe make it all the same (as not native speaking, I don't know which is the best).

**Comment by brianteeman** [comment]
Good spot

**Comment by Quy** [comment]
See PR #19857<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19856">issues.joomla.org/tracker/joomla-cms/19856</a>.</sub>

**Comment by brianteeman** [comment]
Please update the label to J4

**Comment by Civil-captain** [comment]
I think 'Created by Alias' gives the impression that 'Alias' is the username of the creator.

How about we explore 'Anonymous' or 'Anonymous Creator' to keep the verb.

**Comment by chmst** [comment]
If a name is entered here, the creator is no longer anonymous (my understanding as non-native speaker). Author's Alias sounds good for me.

**Comment by Civil-captain** [comment]
Yeah, sounds good

**Comment by crystalenka** [comment]
Is alias clear in this context, though? Thinking of plain language, is it a word that most users will understand right away? (Honest question!)

Some additional suggestions from Mattermost for consideration:

Creator's Display Name
Alternate Creators Name
Alternative Creators Name for Display

**Comment by crystalenka** [comment]
"Override Creator Name"?

**Comment by mfleeson** [comment]
Display Creator as

**Comment by brianteeman** [comment]
Fyi the issue raised was about capitalisation

**Comment by crystalenka** [comment]
That's fine, but it's also not very intuitive. It's an opportunity to both correct the capitalization per the style guide and perhaps make it more clear.

**Comment by chmst** [comment]
It was about capitalisation AND about using the same label in in all components. 
In articles the autor is displayed in "details".  Where is the author or alias of a tag displayed?

**Comment by alikon** [comment]
please test #42220
