### ISSUE TITLE
php 7,2 count

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#19852]
@quy nice easy one for you

Warning: count(): Parameter must be an array or an object that implements Countable in \libraries\src\Installer\Adapter\FileAdapter.php on line 451

I guess there might be other instances as well in that file

**Comment by brianteeman** [comment]
also 
installation\framework\application\application.php on line 250

**Comment by Quy** [comment]
@brianteeman Please advise steps to reproduce. Thanks.

**Comment by PhilETaylor** [comment]
>  Please advise steps to reproduce. Thanks.

 - Install PHP 7.2
 - Install Akeeba Backup 
 - Admin -> Extensions -> Manage -> search for akeeba 
 - Select all 
 - Click uninstall

(ignore warnings in warning box - this is expected) 

<img width="1188" alt="screen shot 2018-03-31 at 21 13 50" src="https://user-images.githubusercontent.com/400092/38167153-7ecd207e-3528-11e8-8aef-91ff007796b6.png">

**Comment by Quy** [comment]
See PR #20044
