### ISSUE TITLE
Gebruikersprofiel

### ISSUE THREAD

**Issue by Keverd** [joomla/joomla-cms#19860]
Plugin gebruiker-profiel
In het gebruikersprofiel een aantal velden als verplicht ingesteld. Bij de uitvoering krijg ik geen * te zien maar (optioneel).

### Expected result
![screen shot 2018-03-07 at 20 13 09](https://issues.joomla.org/uploads/1/0b674c2df66d902c86565d3d430c5689.png)

### Actual result
![screen shot 2018-03-07 at 20 13 03](https://issues.joomla.org/uploads/1/5a5f2ddc924ad5f602e50eb7e1cfc020.png)

### Additional comments

**Comment by Quy** [comment]
Fixed in #19633<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19860">issues.joomla.org/tracker/joomla-cms/19860</a>.</sub>
