### ISSUE TITLE
Menus > All menu Items:: Search tool filter is not working correctly, In case, if we select status as 'published', We're getting unpublished menus too

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#19874]
Go to joomla back-end
Go to Menu> All menu Items
Click on search tool option
In the status drop down, select, 'published'
check the output
**[Pre-requisites, there must be some menus created for some kind of components which does not exist anymore or you have uninstalled it)**![screen shot 2018-03-09 at 07 42 08](https://issues.joomla.org/uploads/1/1580fe4d25e5923c5b6043534fa6ed02.png)![screen shot 2018-03-09 at 07 42 10](https://issues.joomla.org/uploads/1/168266494bd599fd7a3c570627e9c043.png)

**Comment by brianteeman** [comment]
I can confirm this. 

However if you look in the database and the front end of the site you will see that the menu item is still published.

The problem is not with the filter it is with the code that is deciding what icon to display

**Comment by tonypartridge** [comment]
If you edit the item what state is returned?

**Comment by aasimali** [comment]
![saved](https://user-images.githubusercontent.com/10045599/37267292-4c8133f0-25e5-11e8-9e3f-a651b38bb548.png)
State: published (if we edit the same)
Also, It gets saved, if we click on save.

**Comment by brianteeman** [comment]
> The problem is not with the filter it is with the code that is deciding what icon to display

**Comment by infograf768** [comment]
Known issue.

**Comment by ghost** [comment]
> Known issue.

means duplicate Report and close?

**Comment by infograf768** [comment]
Not a duplicate and not close. Just meant this is a "sort of bug" we know about and I doubt we can solve in staging.
See my comment here: https://github.com/joomla/joomla-cms/pull/25197#issuecomment-502346246

**Comment by jwaisner** [comment]
@infograf768 with this being confirmed should we tag this to fix in J4 as your last comment said it may not be able to be fixed in Staging branch?

**Comment by infograf768** [comment]
In J4, we now get a specific badge with `Component not found` but filtering by published still display the menu item in the list. 
<img width="662" alt="Screen Shot 2020-03-14 at 10 44 57" src="https://user-images.githubusercontent.com/869724/76679460-f1153500-65e0-11ea-9b12-fceecede74cb.png">

So, yes, tagged this to J4 now

**Comment by brianteeman** [comment]
From my perspective there is nothing to change here and it is the intended behaviour

The menu item is published in the database but it will not be displayed on the site (as indicated by the icon) because the component can not be found.

(and in j4 this is not restricted to the "all menus" filter it is true on all menu pages)

![image](https://user-images.githubusercontent.com/1296369/186746169-f649582a-c4c7-4982-bdd1-c21b77a450af.png)

**Comment by brianteeman** [comment]
if anything it should be an error icon

**Comment by crystalenka** [comment]
Agreed, an error icon (using the error color) would be best

**Comment by brianteeman** [comment]
See #40353

**Comment by richard67** [comment]
Closing as there is a pull request which claims to solve this issue and which had been merged meanwhile. See #40353 . Feel free to reopen if you think this is wrong.
