### ISSUE TITLE
Menu Heading JPATH_COMPONENT error

### ISSUE THREAD

**Issue by AlexanderSk** [joomla/joomla-cms#19875]
### Steps to reproduce the issue
Go to a web page that has a menu heading/topic alias

like www.test.com/menu-heading/topic-alias
Now remove alias with sometihng irrelevant:

like www.test.com/menu-heading/irrelevant
The error page is visible
Html shows only: Error

Real demo page: on request - pm

### Expected result

Should show 404 error page

### Actual result

Full debugging:
Notice: Use of undefined constant JPATH_COMPONENT - assumed 'JPATH_COMPONENT' in XXX/libraries/src/MVC/Controller/BaseController.php on line 371
Error: JPath::check() - Snooping out of bounds @ JPATH_COMPONENT/views: No application is found

### System information (as much as possible)
Tested on live website - not validated on another one though.
Latest joomla version.

**Comment by brianteeman** [comment]
I can't replicate this - i got the 404 page as expected

**Comment by tonypartridge** [comment]
What Joomla! Version and any additional components?

**Comment by AlexanderSk** [comment]
Hi latest joomla it is all comp plugins lattest  too. I will have to see this on a localhost next week when i have time . I ll start disabling them one by one...

**Comment by AlexanderSk** [comment]
Issue has been located on a test environment.
The error occurs from the AcyMailing Module attached , after disabling in 404 error page shows as it should.

I will bring this issue to the respective component team. Have a nice week.![screen shot 2018-03-12 at 08 27 44](https://issues.joomla.org/uploads/1/c8fb23d44de177fcdd2d3cdef71f1539.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19875">issues.joomla.org/tracker/joomla-cms/19875</a>.</sub>

**Comment by infograf768** [comment]
Closing as not joomla core
