### ISSUE TITLE
NGINX Setting Different for J4 Alpha 2

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#19876]
I can't open certain areas in the admin area such as creating a new menu item. I get a 502.
I wonder if the settings for nginx are different now because of the new router?

Or are these settings still valid => https://docs.joomla.org/Nginx

Can't browse the frontend with enabled sef as well.

Would be happy to get a quick answer so I can start to help testing :-)

**Comment by mbabker** [comment]
There is no change required in web server configuration directives (Apache, NGINX, etc.) other than ensuring minimum requirements are met.

**Comment by PhilETaylor** [comment]
nginx error 502 means Bad Gateway... this means the the PHP had an issue - not the nginx.

**Comment by PhilETaylor** [comment]
> Can't browse the frontend with enabled sef as well.

Check you have this line correct 

`try_files $uri $uri/ /index.php?$args;`

and make sure you have restarted nginx after those changes.

 My bare working nginx config for development use is:

```
server
{
  listen 80;
  server_name remote384; #ensure your domain here is correct

  location /
  {
    root /Users/phil/Sites/remote384/;  #ensure your path here is correct
    index index.php;
    try_files $uri $uri/ /index.php?$args;
  }

   location ~ \.php
  {
    root /Users/phil/Sites/remote384/;  #ensure your path here is correct
    fastcgi_pass 127.0.0.1:9071;   #CHECK YOUR PHP PORT NUMBER 9000 by default. I have PHP 7.1 on 9071 and PHP 7.2 on 9072 etc... 
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
    fastcgi_split_path_info ^(.+\.php)(/.*)$;
    fastcgi_param DOCUMENT_ROOT $realpath_root;
    fastcgi_param   APPLICATION_ENV  local;  #just for my use
  }
}
```

**Comment by PhilETaylor** [comment]
(lastly I only just noticed that this was about J4... my comments are J3 comments :) )

**Comment by mbabker** [comment]
And again, there should be no difference in NGINX/Apache/IIS configs for J3 versus J4 (the default htaccess.txt in the 4.0 branch is a bit more defensive and adds checks for modules being enabled, but that's it).

**Comment by ghost** [comment]
I have a lot of J3 installation on that machine and they are working fine.

I'm sorry - should have done this before:

I've turned the error reporting to development (joomla config) and i get the following error messages:
https://www.awesomescreenshot.com/image/3225449/ca53a9374818df58636a18413de9b65d

Should I disable "scream" in the php.ini in order to test?

**Comment by PhilETaylor** [comment]
Everyday is a school day - developing daily in PHP for over a decade now and never heard of the scream configuration param. 

Yes. Disable that. It has no place in production, and arguably neither in developing a website - main use I could see of it would be in debugging only.

**Comment by PhilETaylor** [comment]
So did that resolve your issue?

**Comment by Quy** [comment]
Closing for now until further details.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19876">issues.joomla.org/tracker/joomla-cms/19876</a>.</sub>
