### ISSUE TITLE
Button for converting all database fields to utf8mb4

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#19881]
![image](https://user-images.githubusercontent.com/3662519/37240677-cfd3b23c-245f-11e8-8244-847e7112733a.png)

I saw in Joomla only a button for converting standard components to utf8mb4, but I did not see such a button to convert all the other components.

I suggest adding this button for converting all fields of the database to utf8mb4.

I do not know when extension developers will make such a button for their extensions. I have a database in three different encodings, a database for the site because of different extensions.

For example, I can use Emoji characters only in standart Joomla components, but I can not use these characters in some other components on the site, for example, in the JComments comment component and others.

This is really a big problem now. Please make a button for converting all the site tables into utf8mb4.

**Comment by brianteeman** [comment]
Joomla should never touch the database tables of anything else. If your component doesn't support utf8mb4 then you should speak to them.

**Comment by infograf768** [comment]
Closing as not Joomla core.
