### ISSUE TITLE
Module Articles Category - Filtering Options - Tags - multiple

### ISSUE THREAD

**Issue by pepperstreet** [joomla/joomla-cms#19885]
### Steps to reproduce the issue

Last year, the module got a useful tags parameter (PR #16945) 
See mod_articles_category -> tab Filtering Options -> Tags

### Expected result

**Multiple** tags selection.

### Actual result

**Single** tag selection.

### System information (as much as possible)

J!3.8.5

### Additional comments

According to the improved Blog MenuItem parameter in this issue #18021 and PR #18234, 
the module should allow to input multiple values, too.
Tooltip text is singular. 
Maybe it should also mention the applied filter logic: _AND/OR_

Even the **Articles - Newsflash** module has a multiple Tags parameter.

**Comment by alikon** [comment]
can you test #19983

**Comment by ghost** [comment]
closed as having Pull Request #19983
