### ISSUE TITLE
Language keys from predefined .xml files not translated

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#19898]
### Steps to reproduce the issue
Go to Menu Manager
Add a new Menu, type administrator, select one of the options predefined Joomla / predefined modern (which is embarassing, as Joomla and modern should not be alternatives)
Store the new menu.
Reopen it - you get the predefined Entries

### Expected result
The Language Keys (menu titles) from predefined xmls are translated

### Actual result
see screenshot![screen shot 2018-03-13 at 21 15 37](https://issues.joomla.org/uploads/1/9e7e124fd33b8a103c5845d9ca6c4abf.png)

**Comment by ReLater** [comment]
Confirmed. Joomla 3.8.5, 3.8.6

**Comment by infograf768** [comment]
Confirmed. 
My tests show that if we add the strings from mod_menu.ini to com_menu.ini. This is solved.
lets see if we can solve this.

**Comment by infograf768** [comment]
OK, I have a simple solution. Will make PR.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/19900
Closing as we have PR
