### ISSUE TITLE
cannot select database type during initial installetion Joomla 4.0 beta

### ISSUE THREAD

**Issue by kroonsbe** [joomla/joomla-cms#19894]
### System information (as much as possible)

Using PHP 7.2.1 on Apache server 2.4.29 at provider Strato
user agent: Chrome/64 with Windows 10-64

### Additional comments

Installetion of Beta release 2 fails due to not be able to select database type. Field remains with "None"

**Comment by ghost** [comment]
@kroonsbe can you please close this Issue as you have discussed with mbabker in another Issue (which i don't find now)?

**Comment by kroonsbe** [comment]
Closed, awaiting solution.
