### ISSUE TITLE
Joomla 3.8.6 Articles - Trash and Unpublish not working

### ISSUE THREAD

**Issue by BizSmith** [joomla/joomla-cms#19896]
### Steps to reproduce the issue
allowing Trashed and UnPublished Articles to be displayed on front end.

### Expected result
Trashed and UnPublished articles should report an error when attempted to display

**Comment by brianteeman** [comment]
Are you logged in at the time. If so then that is the expected behaviour

**Comment by BizSmith** [comment]
Yes I was logged in, tested again when logged out and producing an error
Thanks for the answer.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19896">issues.joomla.org/tracker/joomla-cms/19896</a>.</sub>

**Comment by brianteeman** [comment]
Closed as expected behaviour
