### ISSUE TITLE
Publishing article with the word "minor" leads to 403 error

### ISSUE THREAD

**Issue by brettvac** [joomla/joomla-cms#19897]
### Steps to reproduce the issue
1. Create a new article
2. Add the word "minor" to the article content\
3. Save the article

### Expected result
Article saves normally

### Actual result
Leads to 403 error.
You don't have permission to access /administrator/index.php on this server.

### System information (as much as possible)
Joomla 3.8.6 stable

**Comment by ggppdk** [comment]
Sounds like a mod_security or other security related software, matching a custom (? server-specific) security rule that blocks access to the page

**Comment by brianteeman** [comment]
I am closing this as not a core Joomla issue. @ggppdk is correct
