### ISSUE TITLE
TinyMCE plugin alert link

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#19899]
### Steps to reproduce the issue

Go to Plugins >> TinyMCE

You'll notice a warning alert with a link that doesn't do anything. If it doesn't do anything, don't make it a link.

### Expected result

A link that either links somewhere or isn't a link.

### Actual result

![screeny2](https://user-images.githubusercontent.com/2019801/37391065-02cbb176-2762-11e8-986d-36512a12ec7d.png)

The link does nothing

### System information (as much as possible)

Joomla 3.8.5

**Comment by brianteeman** [comment]
iirc the same message is displayed in content pages where the link makes sense

**Comment by brianteeman** [comment]
The only way to change this will be to create a different language string to be used when in the plugin itself in the tinymcebuilder.php file

**Comment by Quy** [comment]
Creating an extra language string is probably not necessary. The link actually goes to itself (the current page) denoted by the trailing #. I say to not worry about it. Besides, the alert goes away permanently once the plugin is saved.

**Comment by brianteeman** [comment]
I agree with you @quy I was just pointing out the only way to "fix it"

**Comment by brianteeman** [comment]
In the absence of a code proposal for this minor issue I am closing this.
