### ISSUE TITLE
Menu item type not populated with admin menu presets

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#19904]
### Steps to reproduce the issue
Some menu items are affected by this and some are not.

Create an admin menu from one of the presets.
Click `MOD_MENU_CONFIGURATION`.

### Expected result
Menu item type be prepopulated.

### Actual result
![menu-item-type](https://user-images.githubusercontent.com/368084/37415803-879868ca-2769-11e8-8029-72209f9bda59.jpg)

### System information (as much as possible)
v3.8.6

**Comment by infograf768** [comment]
Just posted about that in https://github.com/joomla/joomla-cms/pull/19900#issuecomment-373344254 😃 

@izharaazmi

**Comment by izharaazmi** [comment]
I'd look into this at the earliest

**Comment by izharaazmi** [comment]
The types are evaluate based on the entries populated here `MenusModelMenutypes::getTypeOptions`. These are usually populated using the component metadata or view/layout manifests.

Therefore, any menu item link without `view` parameter are currently losing menu item type information. I'll further investigate and try to get a solution soon.

**Comment by infograf768** [comment]
@izharaazmi 
Any progress on this?

**Comment by brianteeman** [comment]
@izharaazmi any update?
