### ISSUE TITLE
Circular reference error

### ISSUE THREAD

**Issue by magoncalves** [joomla/joomla-cms#19906]
### Steps to reproduce the issue
In frontend, try to access a heavy page, with lot of resources (galleries, modules, extensions...)

### Expected result
The page being normally displayed

### Actual result
The server triggers an error 500.
Log entry: "PHP Fatal error:  Nesting level too deep - recursive dependency? in /JOOMLA_DIRECTORY/libraries/joomla/event/dispatcher.php on line 198

### System information (as much as possible)
Debian 8.10 (Jessie)
Apache 2.4.10
PHP 5.6.33-0+deb8u1
Mysql 5.5.59
Joomla! version 3.8.6

### Additional comments
The problem is a recursive comparison on line 198 of file libraries/joomla/event/dispatcher.php: `$check['handler'] == $observer['handler']`
It's a circular reference problem, as described in: http://www.richardlord.net/blog/php/php-nesting-level-too-deep-recursive-dependency.html

**Reference:**
http://php.net/manual/en/language.oop5.object-comparison.php

**Comment by alikon** [comment]
can you test #19907?

**Comment by Magisdn** [comment]
Thanks! Its work!

**Comment by Quy** [comment]
@Magisdn Please do the following to mark your test as successful:

* Open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/19907)
* Log in with your Github account
* Click on blue `Test this` button above author's photo
* Select `Tested successfully`
* Click `Submit test result`

**Comment by zero-24** [comment]
@Quy as JBS Member you can alter tests like this:
![image](https://user-images.githubusercontent.com/2596554/37620989-09c6136c-2bbe-11e8-8d24-4eba83c15f9d.png)

;)

**Comment by ghost** [comment]
I try to avoid "Alter test" and tell People how to test to get more Volunteers. If there is no Response, i alter.

**Comment by brianteeman** [comment]
Yes it is better to teach them how to do it themselves so that hopefully they will do it correctly the next time
