### ISSUE TITLE
[QUESTION] is there a way to override the generatecss.php file?

### ISSUE THREAD

**Issue by thednp** [joomla/joomla-cms#19901]
The current code doesn't allow the user to push colors or stuff like typographic measurements into the LESS compiler process, you pretty much have to use Bootstrap 2, with its default colors, so I want the user to be able to override this file within(/or only within) my template, with 2 major changes:
* ability to push LESS variables values via PHP 
* ability to compile the LESS on template settings save

Thanks

**Comment by mbabker** [comment]
generatecss.php doesn't ship as part of a release, it's only a convenience tool used when contributing to core and making LESS changes to the core templates to quickly regenerate the CSS for the templates.  So it is not a reliable resource to use in distributed extensions/templates (and obviously not used in the template manager when LESS is compiled from there).

No, there are not hook points in the LESS compiling process to push values into the compiled CSS via PHP in any other way.

**Comment by thednp** [comment]
Thank you, but at least a hook point for template settings save?

**Comment by mbabker** [comment]
Saving template styles emits the usual `onContentBeforeSave` and `onContentAfterSave` events in the `com_templates.style` context.

**Comment by thednp** [comment]
Thank you.
