### ISSUE TITLE
J! 3.x News Feed single item view uses incorrect source to generate item URLs

### ISSUE THREAD

**Issue by sozzled** [joomla/joomla-cms#19919]
### Steps to reproduce the issue
Testing site at http://joomla37.enduring.com.au/index.php/news-feed-tests

The sources for these news feeds—the XML files—can be examined.

### Expected result

The URLs for should generate URLs based on the \<link\> element for each \<item\> in the XML feed.

### Actual result

The URLs for generate URLs based on the \<guid\> element for each \<item\> in the XML feed.

For the test site:  "News Feed 4" generates a 404 error (and I don't know why).  The URLs for "News Feed 1" and "3" and "5" generate valid URLs that will display the external content; the URLs for "News Feed 2" and "6" generate invalid URLs.

### System information (as much as possible)

See full discussion on the Joomla forum at https://forum.joomla.org/viewtopic.php?f=706&t=960129

### Additional comments

Lines 94-95 of **/components/com_newsfeeds/views/newsfeed/tmpl/default.php** probably apply

**Comment by conseilgouz** [comment]
As mentionned in above forum's discussion, component com_newfeed and module mod_feed are not consistent:
com-newfeed line (line 94)
`$uri   = !empty($this->rssDoc[$i]->guid) || $this->rssDoc[$i]->guid !== null ? trim($this->rssDoc[$i]->guid) : trim($this->rssDoc[$i]->uri);
`
mod-feed (line 93) 
`$uri   = (!empty($feed[$i]->uri) || $feed[$i]->uri !== null) ? trim($feed[$i]->uri) : trim($feed[$i]->guid);`

Please note that this is still like this in 4.0 aplha 2.

Pascal

**Comment by SharkyKZ** [comment]
@sozzled see PR #20717.

**Comment by ghost** [comment]
closed as having Pull Request #20717

**Comment by sozzled** [comment]
Thanks.
