### ISSUE TITLE
Valid email address requested while looking for next page

### ISSUE THREAD

**Issue by spiritsoleil** [joomla/joomla-cms#19915]
Hi all,
Recently we noticed an issue on our website. When browsing on our home page, you can see a list of "newsletter" we sent thanks to acymailing.
At the bottom of the page, users are supposed to be able to look to older pages but once you click on next page or type in a page number you want to reach, user is popped up to enter a valid email address.
Same issue occurs if the user wants to search for a specific term in the search field.

### Steps to reproduce the issue
Scenario 1 use the search engine on your joomla page and enter a search term, click on apply (appliquer in French) 
Scenario 2 go to the bottom of your newsletter list and click on next page and you get a popup message requesting to enter a valid email address.

### Expected result
Scenario 1 user is expecting to get the result page of their search
Scenario 2 user is expecting to reach the second page of the list

### Actual result
Scenario 1 you get a popup message requesting to enter a valid email address
Scenario 2 you get a popup message requesting to enter a valid email address

### System information (as much as possible)
Joomla! 3.8.5 Stable [ Amani ] 6-February-2018 15:00 GMT
Php 7.0.27
Acymailing Enterprise 5.9.1

### Additional comments

![image](https://user-images.githubusercontent.com/37401759/37458110-3a8e910e-2844-11e8-985f-e78995ff5009.png)

**Comment by brianteeman** [comment]
This is an issue with AcyMailing and not the core of Joomla and you should ask for support from them.
