### ISSUE TITLE
[4.0] Problem with media manager with Safari

### ISSUE THREAD

**Issue by gyvermac** [joomla/joomla-cms#19928]
### Steps to reproduce the issue

In backend go to media and clic on ... to edit one image.
![screen shot 2018-03-17 at 08 10 18](https://issues.joomla.org/uploads/1/3d713cb8073f46807165dace29f90a59.jpg)

### Expected result
![screen shot 2018-03-17 at 08 10 18](https://issues.joomla.org/uploads/1/816124602c93488968afbec01c576cb6.jpg)

### Actual result
The editing icons appear and disappear immediately. No way to clic on any of them.

### System information (as much as possible)
MacOS 10.13.3, Safari 11.0.3 (last public version) and even with Safari Technology preview

### Additional comments
If you do exactly the same but on a directory instead of an image, everything works fine !
Works on images with Firefox.

**Comment by infograf768** [comment]
Confirmed

**Comment by infograf768** [comment]
![safari_manip](https://user-images.githubusercontent.com/869724/37553327-5a3e7946-29c6-11e8-8ffd-8f912c7f8826.gif)

**Comment by anuragteapot** [comment]
@gyvermac can you please report on https://github.com/joomla-projects/media-manager-improvement and close this Issue here?
Joomla have seperate repo for media manager.
Thanks

@laoneo

**Comment by gyvermac** [comment]
@Anu1601CS I've reported on https://github.com/joomla-projects/media-manager-improvement<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19928">issues.joomla.org/tracker/joomla-cms/19928</a>.</sub>
