### ISSUE TITLE
[4.0] Image edition not working on articles

### ISSUE THREAD

**Issue by eera5607** [joomla/joomla-cms#19922]
### Steps to reproduce the issue

1. Create a new article or enter an existing one.
2. Click on Image button on CMS Content list on TinyMCE toolbar or go to Images and Links tab and select an Intro or Full Article image. 
3. Choose an image and click on the 3 dots on the corner and click the edition icon (the pencil).
![screen shot 2018-03-16 at 01 15 01](https://issues.joomla.org/uploads/1/1e28576dcde027ac6c72fa3dce8f7a83.png)

### Expected result

Edition window opens with its 3 corresponding tabs (Crop, Resize and Rotate).

### Actual result

An error has occurred.
404 View not found [name, type, prefix]: filecomponent, html, Administrator

### System information (as much as possible)

4.0-dev (2018-03-15)
Template: Cassiopeia
Windows 10
Chrome 64.0.3282.186 (Official Build)(64-bit)
PHP 7.2.0
Apache/2.4.29 (Win32) OpenSSL/1.1.0g PHP/7.2.0
MySQLi 5.7

### Additional comments

Image edition works fine on Media Manager directly.

**Comment by happy2dev** [comment]
I tested and confirm the error exists.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19922">issues.joomla.org/tracker/joomla-cms/19922</a>.</sub>

**Comment by happy2dev** [comment]
Attached my screenshot of error!
[screen shot 2018-03-30 at 06 14 29](https://issues.joomla.org/uploads/1/d011f9178d372f2ebfd41367084f3c75.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19922">issues.joomla.org/tracker/joomla-cms/19922</a>.</sub>

**Comment by laoneo** [comment]
Do you have the same provlem when you check out the latest code from the dev branch here https://github.com/joomla-projects/media-manager-improvement?

**Comment by happy2dev** [comment]
@laoneo , I have installed dev branch, and tested.
Error is still.
I attached the screenshot. Pls check.![screen shot 2018-04-01 at 11 38 50](https://issues.joomla.org/uploads/1/5f1336e3ddc7f6ae0d2e6d0af84eef87.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19922">issues.joomla.org/tracker/joomla-cms/19922</a>.</sub>

**Comment by amone4** [comment]
Isn't this issue same as the closed issue #19461 ? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19922">issues.joomla.org/tracker/joomla-cms/19922</a>.</sub>

**Comment by happy2dev** [comment]
@amone4 Hi Akhil, I will run test again and report back :) Thanks for your alert<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19922">issues.joomla.org/tracker/joomla-cms/19922</a>.</sub>

**Comment by happy2dev** [comment]
After new pull from 4.0-dev, I can confirm the bug get fixed.
Please close this issues.
![screen shot 2018-04-10 at 07 24 45](https://issues.joomla.org/uploads/1/518c4e20e70eb3c67f2d263cfd2cdc06.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19922">issues.joomla.org/tracker/joomla-cms/19922</a>.</sub>

**Comment by happy2dev** [comment]
@amone4 Thank you for your nice work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19922">issues.joomla.org/tracker/joomla-cms/19922</a>.</sub>
