### ISSUE TITLE
com_contacts editor-xtd modal bug after search

### ISSUE THREAD

**Issue by prinswebdevelopment** [joomla/joomla-cms#19920]
### Steps to reproduce the issue
Add two contacts
Go to articles and add a new article, use the editor-xtd button for add a contact in article
search one of your contacts
click to add the contact in article
the modal close, but the contact isn't add to the article

### Expected result
add the contact to the article

### Actual result
the modal close, but the contact isn't add to the article

### System information (as much as possible)
php7, joomla 3.8.6

### Additional comments
this solution can be solved in admin/contacts/modal.php:48 change the url and add "&editor=' . $editor" (same as in articles modal).

in admin-contacts-modal.js:18 the script get a false and close the modal because the script can't find the editor.

**Comment by dgrammatiko** [comment]
https://github.com/joomla/joomla-cms/issues/19306#issuecomment-355627836

**Comment by Quy** [comment]
Duplicate #19306<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19920">issues.joomla.org/tracker/joomla-cms/19920</a>.</sub>
