### ISSUE TITLE
Calendar field bug with param maxyear

### ISSUE THREAD

**Issue by thomaslanger** [joomla/joomla-cms#19926]
### Steps to reproduce the issue
Add a calendar field to a form with param maxyear="-18" to set the highest year in caleandar to year 2000
In Browser click on the calendat button to choose a day

### Expected result

If i click on a day in the calendar, the selected date should shown in the input field.

### Actual result

After selected a date, year 2000 is shown, you get a date with current year.

Try to choose a date in year 1999. Year 2000 is shown but you hav to cklick 19 times to set the year to 1999.

The Callendar JS seems to work not with the year given by "current year" and maxyear. It works calculates only with "current year".

### System information (as much as possible)

Joomla 3.8.6

**Comment by thomaslanger** [comment]
The data-attributs in the html-Code are ok. the bug must bee in the calendar.js<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19926">issues.joomla.org/tracker/joomla-cms/19926</a>.</sub>

**Comment by dgrammatiko** [comment]
is max year bigger than min year?

**Comment by thomaslanger** [comment]
minyear is not specified because i don't need a min year, only a max year older then the current. In the joomla documentation it is a optional value.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19926">issues.joomla.org/tracker/joomla-cms/19926</a>.</sub>

**Comment by thomaslanger** [comment]
<field
name="birthday"
type="calendar"
label="BIRTHDAY_LABEL"
maxyear="-16"
/><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19926">issues.joomla.org/tracker/joomla-cms/19926</a>.</sub>

**Comment by thomaslanger** [comment]
name="birthday"
type="calendar"
label="COM_FNETCM_BIRTHDAY_LABEL"
maxyear="-16"
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19926">issues.joomla.org/tracker/joomla-cms/19926</a>.</sub>

**Comment by thomaslanger** [comment]
![screen shot 2018-03-23 at 14 42 38](https://issues.joomla.org/uploads/1/bbac70b7cf1ae4dbdddf264fdc327a6f.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19926">issues.joomla.org/tracker/joomla-cms/19926</a>.</sub>

**Comment by thomaslanger** [comment]
More info required? Which? Could someone reproduce the bug?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19926">issues.joomla.org/tracker/joomla-cms/19926</a>.</sub>

**Comment by brianteeman** [comment]
I can reproduce this

**Comment by pinta83** [comment]
I have the same issue....

My maxdate is set to "-7", and when i click the date picker it only shows the currentyear -7 in the header... The actuall caledar is rendered for the current month, and I have to click the left nav arrow 7 time before i even get to the year, and then it finaly starts to change.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19926">issues.joomla.org/tracker/joomla-cms/19926</a>.</sub>

**Comment by pinta83** [comment]
And to go even further... I can click the dates (in current month) and the date will be set regardless of maxyear being set<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19926">issues.joomla.org/tracker/joomla-cms/19926</a>.</sub>

**Comment by pinta83** [comment]
Found and solved the problem....

If you take a look at /media/system/js/fields/calendar.js at lines 863-869 you can see the date.getOtherFullYear(this.params.dateType, year) call with a second parameter being a year.

Now if you take a look at the getOtherFullYear() function defined in /media/system/js/fields/calendar-locales/date/jalali/date-helper.js you will see that the function excepts only 1 paramterer...

/** Returns the year for the current date. */
Date.prototype.getOtherFullYear = function (dateType) {
	if (dateType != 'gregorian') {
		/** Modify to match the current calendar when overriding **/
		return this.getJalaliFullYear();
	} else {
		return this.getFullYear();
	}
};

----
Fix
1. Open up /media/system/js/fields/calendar.js
2. replace "date.getOtherFullYear(this.params.dateType, year);" with "date.setYear(year);" on lines 865 and 858
3. Done, everything works now :)

The bugfix covers minyear bug aswell, since both are handled on the same place..

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19926">issues.joomla.org/tracker/joomla-cms/19926</a>.</sub>

**Comment by ghost** [comment]
@dgrammatiko comment as js-guru?

**Comment by pinta83** [comment]
P.S. The bugfix covers minyear bug aswell, since both are handled on the same place...

**Comment by dgrammatiko** [comment]
Seems reasonable

**Comment by ghost** [comment]
@pinta83 can you do a Pull Request?

**Comment by pinta83** [comment]
Will do it today if I catch the time, if not - tommorow morrning ;)

**Comment by ghost** [comment]
Closed as having Pull Request #26119
