### ISSUE TITLE
CategoryEdit form field cannot be restricted to show only published categories

### ISSUE THREAD

**Issue by corejoomla** [joomla/joomla-cms#19932]
### Steps to reproduce the issue
Add a field in the form xml file with published attribute set to value 1

    <field
	name="catid"
	type="categoryedit"
	label="JCATEGORY"
	description="JFIELD_CATEGORY_DESC"
	id="catid"
	extension="com_content"
	class="inputbox"
	required="true"
	published="1"
	/>

### Expected result
The form page should show the category form field with only published categories shown

### Actual result
The field values include unpublished values shown in brackets, e.g. [category 1]

### System information (as much as possible)
Joomla 3.8.6

### Additional comments
Change the file components/com_content/models/forms/article.xml

**Comment by ghost** [comment]
closed as having Pull Request #20018.

**Comment by ghost** [comment]
@corejoomla can you please Test Pull Request #20018?
