### ISSUE TITLE
Checkbox selection in new or edit Smart Search Filter.

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#19930]
### Steps to reproduce the issue
Go to Components - Smart Search
Index the content (like examples)
Go to Search Filters and create a new one.
Click on "Search by category - xx (look at attached picture)
If You touch the checkbox it works, but if you touch a label the first checkbox is marked and not the one you check

![screen shot 2018-03-17 at 13 05 16](https://issues.joomla.org/uploads/1/82a466bb9ea3f5a018acced8db162dfb.png)

### Expected result
The checkbox of the label you click should be marked.

### Actual result
The first checkbox is marked.

### System information (as much as possible)

Latest release of Joomla (3.8.6) PHP 7.0.4 on localhost

**Comment by alikon** [comment]
confirmed

**Comment by ghost** [comment]
closed as having Pull Request #19969
