### ISSUE TITLE
Display "Locked" icon also to user who has locked the item him-/herself

### ISSUE THREAD

**Issue by kettumatti** [joomla/joomla-cms#19937]
### Steps to reproduce the issue
Login as administrator and go to article or module editing. Use browser's "back"-button to cancel editing.
Now other administrators (except super user) can't edit this item because it's locked to user who started editing it. They can see an icon in front of item title and information who and when have made the locking. 

### Expected result
The user should also see (may be with a different type of an icon) if he/she has made "stupid things" and locked  items so that other administrators can't edit them. Another solution could be some kind of warning if browser's "back"-button is clicked when in editing mode.

### Actual result
The user who has locked the item doesn't see any indication of that because locking doesn't affect him/her. 

### Additional comments
This is a problem on websites with multiple (unexperienced) administrators who tend to use browser's "back"-button unintentionally.

**Comment by Bakual** [comment]
I can't reproduce that. For me the lock also appears for my own user (Super User in that case).

**Comment by kettumatti** [comment]
Sorry, my fault! The locking icon is visible for the locker too. But could there be a warning if you are exiting the editing mode inappropriate way? Or could there be some kind of notification when you are logging out: "You have X item(s) locked for editing." and then buttons: "Release locks and logout / Keep them locked and logout." (or something like that)?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19937">issues.joomla.org/tracker/joomla-cms/19937</a>.</sub>

**Comment by Bakual** [comment]
I think that was discussed in the past already. Personally I hate those JavaScript checks. I'd rather train the users to use the cancel button.

**Comment by ggppdk** [comment]
#13120
#4773
#5815

**Comment by ggppdk** [comment]
> I think that was discussed in the past already. Personally I hate those JavaScript checks. I'd rather train the users to use the cancel button.

>Or could there be some kind of notification when you are logging out: "You have X item(s) locked for editing." and then buttons: "Release locks and logout / Keep them locked and logout." (or something like that)?

you may be logged via frontend too, or via 2 different browsers, it gets complicated, 

A button in article manager and in every backend manager "Check-in all" that will be cascaded under "Check-in"  button would be nice, and also maybe some counter next to check-in button showing how many records of current manager are currently logged

About adding warning during log-out and / or blocking logout i think it would be a little annoying ?

**Comment by simbus82** [comment]
I think the best solution is do what is doing Facebook: if i click exit button in browser, change address or click back button when i'm editing a post, FB show a warning message. A simple alert with something like "Are you sure to leave? The changes may not be saved you don't click save". THIS is a good thing to train users, not leaving dozen of locked articles.

This Pull https://github.com/joomla/joomla-cms/pull/5815 show a correct UI method that follow modern approach with UX.

**Comment by brianteeman** [comment]
Sadly the code proposed didnt work though

**Comment by jwaisner** [comment]
This discussion has ran its course. As this has not been commented on in many months, it is being closed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19937">issues.joomla.org/tracker/joomla-cms/19937</a>.</sub>
