### ISSUE TITLE
custom registration form can't be requiered anymore (3.8.5&3.8.6)

### ISSUE THREAD

**Issue by torxt** [joomla/joomla-cms#19948]
### Steps to reproduce the issue
Have a custom reg plugin made / installed like profile5
Set the custom field to requiered
Make an attempt to create user account and do not fill out the custom reg fields
Leave custom reg fields empty 
The create user account button will not light up the custom fields and you can make a registration without filling them out

### Expected result
Light up Red and Stop registration until fields are filled out

### Actual result
registration proceeds, custom reg fields are not checked for requiements

### Additional comments
It was working until the update to 3.8.5. About two years ago (???) there was the same problem, but got fixed with the next version. I don't what version was affected

**Comment by ggppdk** [comment]
There was a fix for this in J3.8.6

#19633

**Comment by torxt** [comment]
Yes the $form->loadFile('profile'); 
But my profile5 based plugin still does not work. It was working < J3.8.5
I installed J3.8.5 & J3.8.6 with no change. In the admin options I disabled one of the fields. That works. But having it optional / requiered does not change anything.  



//edit: this was the first incident I was talking about: https://docs.joomla.org/J3.x:Update_from_3.6.x_to_3.6.5_Profile_fields

My components/com_users/models/registration.php has the string: 
`$form = $this->getForm(array(), false);`

but changing to 
`$form = $this->getForm(array());`
does not do anything

**Comment by ggppdk** [comment]
You have a custom profile plugin

PR #19633 was a fix for required fields via Joomla user profile plugin
i don't know if same / similar fix applies in your case

**Comment by brianteeman** [comment]
Please use the forum for support
