### ISSUE TITLE
plg_system_redirect. Exclude URLs.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#19973]
### Steps to reproduce the issue
- Test with a "normal" online domain like example.org or subdomain like sub.example.org!
Test will not work with XAMPP, MAMP or so.

- Current staging with testing sample data.
- SEF Yes. Url Rewrite: Yes.

- Activate plugin "System - Redirect". Enable "Collect URLs".
- Go to frontend and enter not existing URL like
`example.org/database/db.sql.gz` (replace example.org with your domain). It throws a 404 error (not found)
- Check backend > Components > Redirects.
- Above URL is collected as expected. 
- Delete it.
- Go to plugin "System - Redirect" and create a new `Term` for `Exclude URLs` **without checking** "Regular Expression".
```
/database/
```
- Go to frontend and enter again not existing URL 
`example.org/database/db.sql.gz` (replace example.org with your domain).

- Check backend > Components > Redirects.

### Expected result
- Above URL is **NOT** collected by plugin.

### Actual result
- Above URL is collected by plugin.

### Additional comments
- One have to enter 
```
database/
```
in Term field instead of 
```
/database/
```
But that would also block mydatabase/ and similiar URLs.
 
Please don't comment that I should use a regular expression in this case ;-) I know that it's possible but from my point of view that's not obvious for users and not an expected behavior.

**Comment by tonypartridge** [comment]
Confirmed. Please close we have a PR.

**Comment by ghost** [comment]
closed as having Pull Request #19979
