### ISSUE TITLE
[4.0] o is undefined

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#19980]
See attached, on first load to install

@dgt41 

<img width="579" alt="screenshot 2018-03-24 23 21 26" src="https://user-images.githubusercontent.com/1400982/37869949-30a6a46a-2fba-11e8-9cf9-a48aa49a80f5.png">

**Comment by dgrammatiko** [comment]
FF?

**Comment by tonypartridge** [comment]
Yeah

**Comment by dgrammatiko** [comment]
hm, I don't get anything, do you remember which page throw that error?

**Comment by infograf768** [comment]
I also get that (Using Firefox) when loading the installation first page

**Comment by infograf768** [comment]
And in Safari too:
<img width="415" alt="screen shot 2018-03-25 at 12 14 34" src="https://user-images.githubusercontent.com/869724/37873941-23db70be-3026-11e8-886f-084f98bf752b.png">

**Comment by dgrammatiko** [comment]
Can you switch to the debug mode to get the line number?

**Comment by dgrammatiko** [comment]
Let me know if #19984 fixes this

**Comment by infograf768** [comment]
it does

**Comment by infograf768** [comment]
closing as we have PR
https://github.com/joomla/joomla-cms/pull/19984
