### ISSUE TITLE
PHP warning error for tags component with PHP 7.2.3

### ISSUE THREAD

**Issue by hakanara** [joomla/joomla-cms#19998]
From time to time this warning appears on my log file. I don't know which page or condition creates it.

PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /public_html/components/com_tags/views/tag/tmpl/default_items.php on line 26

My Joomla version is: 3.8.6, PHP version is 7.2.3

If you need the detailed system info file, I can download and post here in the format you want.

Kind regards to each Joomla team member and lover :-)

**Comment by tonypartridge** [comment]
Pease try my pr just in

**Comment by ghost** [comment]
closed as having Pull Request #20000.

**Comment by tonypartridge** [comment]
@hakanara can you please test the PR

**Comment by hakanara** [comment]
@tonypartridge I have tested and the notice is still there.

**Comment by tonypartridge** [comment]
Sorry was just an update via my phone. Will sort it for good later and confirm to re-test.
