### ISSUE TITLE
[4.0] Multilingual routing, SEF on: menu items URL broken in frontend (except home pages) + ugly urls for articles

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#19997]
### Steps to reproduce the issue
Create a multilingual site with 4.0 (2 languages are enough)
The easiest way we have now is alas still a bit complex.
Make sure you installed one of the languages we can install: French, German, Persian
Make sure both Content Languages exist and are published.
Make sure the Language Filter plugin is enabled.
Create a language switcher module and publish it in the `right` position
Then, when admin language is en-GB, go to Control Panel and Install Blog sample data (items with be tagged to en-GB).
Go to Installed languages and switch admin to the other language (French for example)
Back to Control Panel and Install again Blog Sample Data. This time it will be tagged to French.

Then set the Blog(en-GB) menu Item to Home.
Set the Blog (fr-FR) menu item to Home.
Unpublish the main menu module (the one which contains the default Home set to ALL languages).

Set SEF and URL rewriting ON in Global Config (use htaccess )

### Results
Go to Frontend and click on any menu (except the home page)

The menu `About (en-GB)` gives this url
`http://localhost:8888/installmulti/joomla40/about/en/`
instead of
`http://localhost:8888/installmulti/joomla40/en/about/`

and therefore a 404 as the `URL Language Prefix ` (en) is not at the correct place.

------------------------
Now click on one article in the  `Older Posts (en-GB)` module:
For example `Welcome to your blog (en-GB)`
You get this url, whether in modern or legacy routing

`http://localhost:8888/installmulti/joomla40/en/?view=article&id=3:welcome-to-your-blog-en-gb`

Not very nice...

Did not test other stuff.

**Comment by infograf768** [comment]
Hint: the issue is present when using SEF.

**Comment by Yddap17** [comment]
Have same issue. 
I have Search Engine Friendly URLs ON
Doesnt't matter if URL Rewrite is ON in my case

Have 5 Menus (2 Language English, 2 Language German, 1 Menu for ALL Language, which has no module position)

When I click in one of the seperated published language menus, the routing adds another language code at the end of the url.
Something like **/en/about/en**
That fires an 404 error.
When I remove the last **en** manually it works fine.

Switching the language with the switching Module (where I had difficulties installing (Get error: **Save failed with the following error: Field 'content' doesn't have a default value**), the URLs get ugly.
Like **de/?view=article&id=2**
There the _second_ language code is't added. And it works without doing anything manually. But the URL is not nice...

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19997">issues.joomla.org/tracker/joomla-cms/19997</a>.</sub>

**Comment by eltonpang** [comment]
This issue are also present in existing 3.8.7, I am about the submit a new issue but see this being reported for 4.0.  The issue are quite similar as describe by Jean-Marie Simonet.
If you need to see sample, head to http://templatesreview.cloudaccess.host
click on any of the 2 articles in the homepage, you will always see **?view=article&id=4:** follow by articele title then end with **&catid=2**
Note: the ID changes depending on the article and category of the article display

SEO Settings:
SEF URL Yes
Use URL rewriting Yes
Unicode Aliases Yes

Article Options >> Integration
URL routing Modern
Remove IDs from URL Yes<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19997">issues.joomla.org/tracker/joomla-cms/19997</a>.</sub>

**Comment by mbabker** [comment]
In your case it looks like there are no menu items configured except for the featured menu item (the home page).  The router cannot use the featured item view in com_content to create SEF URLs as featured is a content state and not part of the content hierarchy.

**Comment by eltonpang** [comment]
I had raised a ticket for 3.8.7 at https://issues.joomla.org/tracker/joomla-cms/20242 as it need to be fix or render multilanguage site not URL friendly<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19997">issues.joomla.org/tracker/joomla-cms/19997</a>.</sub>

**Comment by Hackwar** [comment]
Looks like languagefilter.php line 146 needs to be PROCESS_BEFORE instead of PROCESS_DURING. That should fix it.

**Comment by infograf768** [comment]
I'm afraid not

**Comment by infograf768** [comment]
I meant better, but not fully
I get for example
`http://localhost:8888/installmulti/joomla40/fr.html`
instead of
`http://localhost:8888/installmulti/joomla40/fr/`
for home page
also
`http://localhost:8888/installmulti/joomla40/?format=html`
when url language code is set to not show for the home page of the default site language

**Comment by infograf768** [comment]
I am closing this as the errors have changed since this issue was posted.
