### ISSUE TITLE
After update not all fields are filled out of the Session Data Purge plugin

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#20013]
### Steps to reproduce the issue

Update Joomla 3.8.5 to 3.8.6.
See the _Extensions manager: Manage_
The following fields are empty from the **Session Data Purge** plugin: **Version, Date and Author**.
See image (1).

### Expected result

All the fields have been completed.

### Actual result

Also, see the additional comments.

### System information (as much as possible)

Does not apply.

### Additional comments

After a whole new installation of Joomla 3.8.6 the concerning fields are not empty. OK
See image (2).

1) Unwanted situation = Actual result
![screen shot 2018-03-28 at 10 58 03](https://issues.joomla.org/uploads/1/bd08092f35fdc52a73166c81c6c24124.png)
2) Wanted situation
![screen shot 2018-03-28 at 10 58 06](https://issues.joomla.org/uploads/1/4e4222f8eb69f97e80c9dfdc6bce5a32.png)

**Comment by brianteeman** [comment]
~Despite what it says this plugin "Session Data Purge" is not a core plugin provided by the Joomla project and is something that you have installed~

**Comment by brianteeman** [comment]
I need more coffee

**Comment by brianteeman** [comment]
Wasn't this plugin only introduced in Joomla 3.8.6?

**Comment by mbabker** [comment]
The manifest cache data isn't placed into the update SQL statement as the caches should be refreshed as part of the update process.  Probably need to add the plugin to wherever that list is at these days.

**Comment by sandewt** [comment]
@brianteeman see issue #19687

**Comment by brianteeman** [comment]
@sandewt Yes it was introduced in 3.8.6 - your report was confusing as I assumed you meant the values were present BEFORE the upgrade to 3.8.6

**Comment by sandewt** [comment]
@brianteeman The issue occurs in case of an update/upgade to 3.8.6. I found this at several sites.
And not in the case of a new installation. Maybe another can confirm this last.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20013">issues.joomla.org/tracker/joomla-cms/20013</a>.</sub>

**Comment by brianteeman** [comment]
Yes I confirm it - I just misunderstood your original post

**Comment by sandewt** [comment]
@brianteeman That can happen.

**Comment by zero-24** [comment]
please test: https://github.com/joomla/joomla-cms/pull/20038
