### ISSUE TITLE
Question: show cached module on logined user (forcing using cache)

### ISSUE THREAD

**Issue by boomsya** [joomla/joomla-cms#20011]
J1.5-J3.8.6

i have many sites where modules updating once per day, hour. I am always try to use cache on sites because site without cache heavy load CPU on webhoster. And i have some sites with 13.000 users per day and 120.000 page views

when user is Guest (not logined) - all ok
but when user logined - cache not using. It is give some trouble with CPU load.

so, as partially solutions - enable force using modules cache. I have 50-70% of modules (like currencies, weather, top users, banners, community groups, ... etc) which not needed display actually information under logined user.

can Joomla developers add addtional option to "using cache" in module setting like "Force using"/"Using anyway and any time" :) ?

**Comment by ghost** [comment]
can someone please give a Comment on this Issue as it is since near one Month asked?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20011">issues.joomla.org/tracker/joomla-cms/20011</a>.</sub>

**Comment by mbabker** [comment]
As a general rule of thumb a response based on a privileged user's state should be considered a private a non-cacheable resource, an option like this would either call for extra overhead in the code deciding what to cache to do more caching based on ACL and view access levels or introduce a scenario where information is leaked based on which user caused the data to be cached

**Comment by ghost** [comment]
@boomsya are you interested on further Discussion on this Topic?

**Comment by boomsya** [comment]
yes. but i think nobody wants implement this feature in future versions of CMS.

**Comment by ghost** [comment]
so can you please close this Issue?

**Comment by boomsya** [comment]
close

**Comment by boomsya** [comment]
sorry for not good english :)
today i was testing my modification of core module rendering.
Problem what i have on some sites is 20 modules with ads and some other modules.
Under guest - no problem because cache enabled and SQL queries count is minimal and CPU not loading.

but under user this modules gives CPU load + DB SQL queries. It is problem. Big problem.
my sql opitization in this modules gives some acceleration but anyway - DB is heavy loaded.

so i modified file `libraries/src/Document/Renderer/Html/ModuleRenderer.php`
`if (($params->get('cache', 0) == 1 || $params->get('cache', 0) == 2) && \JFactory::getConfig()->get('caching') >= 1 && $cachemode != 'id' && $cachemode != 'safeuri')`

i was added `|| $params->get('cache', 0) == 2`

and second file is `libraries/src/Helper/ModuleHelper.php`
`if ($moduleparams->get('owncache') === 0 || $moduleparams->get('owncache') === '0' || $conf->get('caching') == 0 || $moduleparams->get('cache', 0) == 2/*|| $user->get('id')*/) `
in this file commented checks `userid `and add check `module cache param = 2`

and CMS core now using modules cache under logined user. All works fine!
but!!!! i have some modules which should not using cache under user. This module like polls or modules which draw different module body under logined user and not logined. So i was add third param in module XML like:
```
<field name="cache" type="list" default="1" label="Caching" description="Select whether to cache the content of this module">
<option value="2">No caching under logined user</option>
<option value="1">Use global</option>
<option value="0">No caching</option>
</field>
```
and that module works in three modes:
0 - not using cache
1 - cache under guest + cache under user
2 - cache under guest + no using cache under user

Web site rendering with my modification very fast
mans. What you think about adding this feature in new joomla versions? i using 3.9.2

**Comment by boomsya** [comment]
fast joomla nobody needed?

**Comment by ghost** [comment]
@Hackwar is this a Topic for j4 too?

**Comment by Hackwar** [comment]
I understand the frustration, but I agree with @mbabker here. I don't see this as part of the default Joomla core. The potential for security issues and using it wrong is to great for my taste. If you really need this, then you should look into ways to have this with proper core overrides. However I also suggest to look into optimisations of your site first. Generally, your site should respond quickly when you are the sole user and cacheing can then be used to scale that to lots of users, but it is not a solution for a generally slow site.

**Comment by ghost** [comment]
closed as stated above, thanks for taking time @Hackwar
