### ISSUE TITLE
Custom Fields (parameters) for Menu Items

### ISSUE THREAD

**Issue by Dave-LeDev** [joomla/joomla-cms#20022]
It's perhaps not a common need; I'd like to be able to add custom parameters for menu items. While this can be accomplished with a [Menu Item Layout Override](https://docs.joomla.org/Layout_Overrides_in_Joomla#Alternative_Menu_Items "Menu Item Layout Override"), depending on the parameter that needs to be added and the diversity of link types, this can require dozens of overrides.

Adding to this, if for whatever reason a template must be changed but support the same functionality, those Layout Overrides must be recreated per template.

Supporting custom fields to add parameters can potentially save much time.

**Comment by Dave-LeDev** [comment]
This is supposed to be flagged a feature request but I don't see that added. I don't see an option to change this so if an administrator could correct this for me. My apologies. First post ever on here!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20022">issues.joomla.org/tracker/joomla-cms/20022</a>.</sub>

**Comment by brianteeman** [comment]
Can you give an example please?

**Comment by Dave-LeDev** [comment]
Sure. In my very specific use case I'm modifying [EasySocial's Toolbar Module](http://easysocial.stackideas.com/ "EasySocial's Toolbar Module"). By default it's hard-coded with its own links. Instead I want to replace it with a module position and use a Menu Module in its place. Doing this not only grants me custom menu items but also ACL, which the original module isn't built with.

I've gotten thus far with minimal issue using template overrides. However, I also want to maintain the markup used in the original menu. To do so I need one extra Class tag. This will need to be added via a Menu Item Parameter. At present I will need to make at least 6 different Layout Overrides, and I'm not yet certain if overrides can be created for System Links. If instead I can add this as a Custom Field, it'd take just a couple of minutes to add and I can go about my business adding the usage of this parameter within my template. If the template is changed all I would need to do is re-add the usage of the parameter instead of that and all the Menu Item Layout overrides needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20022">issues.joomla.org/tracker/joomla-cms/20022</a>.</sub>

**Comment by Dave-LeDev** [comment]
Minor correction. I wouldn't even need to re-add the parameter as that styling is dependent upon EasySocial's markup and not the template's. So if Custom Fields are supported I would just need to copy my mod_menu and com_easysocial/toolbar overrides.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20022">issues.joomla.org/tracker/joomla-cms/20022</a>.</sub>

**Comment by brianteeman** [comment]
seems a very unique and specific requirement. you would probably best to just make your own menu module with all the data you require

**Comment by Dave-LeDev** [comment]
Even doing so, the information I need is Menu Item-specific. It wouldn't affect all links.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20022">issues.joomla.org/tracker/joomla-cms/20022</a>.</sub>

**Comment by Dave-LeDev** [comment]
I've tried finding a plugin that adds this functionality, but all I've found so far is a project from 2014 asking why their implementation wasn't working.

https://github.com/joomla/joomla-cms/issues/5289<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20022">issues.joomla.org/tracker/joomla-cms/20022</a>.</sub>

**Comment by brianteeman** [comment]
i just cant see there being a need for this in the core but maybe thats because i still dont really understand your usecase

**Comment by Dave-LeDev** [comment]
I submit that while I cannot immediately think of an alternative use case it could potentially provide a faster alternative to Menu Item Layout Overrides. Instead of having to create the override with its XML, use the Custom Fields instead. One Custom Field can be designated as a switch to render a portion of your Override. This could also potentially make custom Menu Item Layouts much simpler to develop for templators, especially if those Custom Fields can be installed along with the template.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20022">issues.joomla.org/tracker/joomla-cms/20022</a>.</sub>

**Comment by brianteeman** [comment]
and if you follow the original source you will see that they were able to fix their code

**Comment by Dave-LeDev** [comment]
My yellow flags on that are that it appears to be a personal project not really meant to be widely distributed, it hasn't been updated in at least 2 years, and I'm not proficient enough a programmer to maintain it myself. If it were part of core or as a paid 3rd party plugin I wouldn't be alone in maintaining it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20022">issues.joomla.org/tracker/joomla-cms/20022</a>.</sub>

**Comment by brianteeman** [comment]
thatz your call.
if it works then there is  no need to update it
i am just not convinced this is needed in the core.

**Comment by Dave-LeDev** [comment]
I'm new to this side of Joomla, so please have patience with me. What process is involved in deciding what goes into core? Are core components ever commissioned?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20022">issues.joomla.org/tracker/joomla-cms/20022</a>.</sub>

**Comment by brianteeman** [comment]
the biggest criteria for a new feature would be if it was useful to a significant % of web sites

**Comment by Dave-LeDev** [comment]
I'll reformulate my pitch and ask around. Thanks for your input!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20022">issues.joomla.org/tracker/joomla-cms/20022</a>.</sub>
