### ISSUE TITLE
Factory::getApplication(); highlighting in PHPStorm 

### ISSUE THREAD

**Issue by NickSdot** [joomla/joomla-cms#20030]
### Steps to reproduce the issue

Use PHPStorm.
Include Joomla! as External Library

```
use \Joomla\CMS\Factory;
$app   = Factory::getApplication();
```
### Expected result

No warning and highlighting.

### Actual result

Warning and highlighting.
<img width="783" alt="screen shot 2018-03-30 at 20 44 52" src="https://user-images.githubusercontent.com/32384907/38138089-5e7b22e4-345b-11e8-9e99-d17f3b3febae.png">

### System information (as much as possible)

Joomla 3.8.6

### Additional comments

Not sure if this really is a Joomla! issue cause there is actually a throws tag for the function
But because it's a bit annoying, I am just curious if this is to solve by the core, the PHPStorm Plugin for Joomla!, PHPStorm itself or if I myself doing something wrong.

Low prio, of course.

**Comment by trananhmanh89** [comment]
Check here, we already have solution

https://github.com/joomla/joomla-cms/issues/18014

**Comment by roland-d** [comment]
@NickSdot This is not a Joomla issue nor a PhpStorm issue. PhpStorm is correctly reporting that the function you are calling is going to throw an exception. You need to either place your code in a try/catch block as to deal with the possible exception or annotate with an `@throws` in your docblock.

**Comment by NickSdot** [comment]
Thanks for your answer @trananhmanh89, but it is not about type hinting itself.
Do I miss something or did you misunderstood my question?

Thanks @roland-d for your answer, but I think it also not is related as well to what I tried to explain.

Let's say there is not a own function in my code. 
Just place:

`use \Joomla\CMS\Factory;
$app   = Factory::getApplication();`

In a blank index.php of a template. Of course I will not have a own doc block for this.
But still I get the highlighting and warning. Got me?

@brianteeman 
Please re-open. Answer was not related in my opinion.

**Comment by roland-d** [comment]
@NickSdot There is no reason to re-open as this is not a Joomla issue. Yes, you don't have your doc block but you either add the docblock or enclose it in a try-catch. Regardless, the code is going to throw an exception if something occurs.

**Comment by NickSdot** [comment]
@roland-d 
In conclusion this means that theoretically in every of the 1178 occurrences of Factory::getApplication() in the Joomla! core itself, there must be another try-catch added?

It's not only about having this in my own code. 
It's just everywhere, where I simply can not add a try-catch because it's not my code.

Thanks for one more answer, I really want to understand this.

**Comment by mbabker** [comment]
The inspection is basically saying "you are calling this method which may throw an exception but you are not wrapping this method call in a try/catch block nor is the method from which you're making the call documented to throw an exception".

To appease PhpStorm, you'd need to do one of two things:

1) Add a `@throws` annotation to your doc block

```php
use Joomla\CMS\Factory;

class MyClass
{
    /**
     * @throws \Exception
     */
    public function processDataFromRequest()
    {
        $app = Factory::getApplication();

        // Do stuff
    }
}
```

2) Wrap the `getApplication()` call in a try/catch block


```php
use Joomla\CMS\Factory;

class MyClass
{
    /**
     * @throws \Exception
     */
    public function processDataFromRequest()
    {
        try {
            $app = Factory::getApplication();
        } catch (Exception $e) {
            // Error handling
        }

        // Do stuff
    }
}
```

You can also choose to ignore the inspection's warnings, something I commonly do on several projects myself (I have code where I purposely am not catching exceptions thrown by another class and I follow a coding style rule where I'm not adding doc blocks to my class methods unless the doc block can provide information that isn't already easily available from the method name and signature, so I don't have a doc block to annotate a `@throws` line in).

**Comment by NickSdot** [comment]
@mbabker valuable answer as always, got it, thank you!
