### ISSUE TITLE
Module Class Suffix is not working for backend module

### ISSUE THREAD

**Issue by arbindbhagat** [joomla/joomla-cms#20042]
### Steps to reproduce the issue
Put a module-class-suffix for a backend module, for example, "Popular Articles" module on backend.

### Expected result
The html output for that module on the /administrator page should contain that module-class-suffix.

### Actual result
The html output for that module on the /administrator page doesn't contain that module-class-suffix.

**Comment by ReLater** [comment]
You have to change the `Module Style` of the module to `html5` or `xhtml`!

**Comment by ghost** [comment]
Closed as Expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20042">issues.joomla.org/tracker/joomla-cms/20042</a>.</sub>
