### ISSUE TITLE
[com_users] Add trash or change confirm when delete user

### ISSUE THREAD

**Issue by Septdir** [joomla/joomla-cms#20049]
I will not write a long introduction but just give examples
*Please take a closer look at the timestamps*

**03:00** Automatic server backup  
**15:00** New user registered. Let's call it Mike
**18:00** The administrator mistakenly deletes Mike

In this situation, it is almost impossible to restore the user.

Of course this is entirely the fault of the administrator.  
You can prevent administrators from deleting users.  
You can only delete them after you create a backup  
But no one is immune from mistakes.

Therefore, I add state trash or confirm message.  
It is clear that adding to the state is quite problematic, need change database table, rewrite the user's rights, etc.  
However, just adding a `popup / modal / confirm` window with usernames to control panel template is quite simple.

Popup / Modal window will be preferable because they are better seen, unlike the standard confirm

**Comment by Quy** [comment]
I get an alert/warning before deletion:
`Are you sure you want to delete? Confirming will permanently delete the selected item(s)!`

**Comment by Septdir** [comment]
@Quy I also have this message, however, it does not specify who exactly you delete.
I change first message and title

P.S In truth, seeing such a message does not stop to think about action

**Comment by tonypartridge** [comment]
We can easily chuck in the user name with sprintf. But it’s not really soling the issue you had. 

I suppose you could add a trash system but this is quite a lot of work for users given it’s usage.

**Comment by tonypartridge** [comment]
I’d probably recommend you re-train your admins not to delete users and instead to block them and purge ones without activity that are blocked after x months.

**Comment by Quy** [comment]
Take it one step further to hide the Delete button with css and unhide when ready to delete.

**Comment by Septdir** [comment]
@Quy Well, on their sites I'll figure out how to be. But I think that this problem happens not only for me

**Comment by tonypartridge** [comment]
I see your point, I think the warning could be bigger and more prominent.

But fundamentally it’s a training issue.

With GDPR coming in, trashing users for instance will be even more frowned upon since when you want to delete a user they should be deleted.

**Comment by Septdir** [comment]
@tonypartridge You are undoubtedly right that people need to be trained and trained, but this is not stahovka from mistakes. For example, do you delete several users, how to check before deleting?

>With GDPR coming in, trashing users for instance will be even more frowned upon since when you want to delete a user they should be deleted.

In com_content, com_categories, com_menu .. have trashed in com_users permanent delete.   
Long time working with content a person gets used to the fact that he can always be restored from trashed and often does not think about the fact that in com_users permanent delete.  

Hmm .. can be allowed to delete only blocked I guess I'll do it on my site

**Comment by Septdir** [comment]
On my sites I did so
* IF `filter.state != 1`  Remove `users.delete` & `users.unblock` ELSE remove `users.block`
* IF `filter.active!= 1` Remove `users.activate`

Maybe later I'll correct model to change the query to the database

**Comment by Septdir** [comment]
If such an idea with buttons is interesting then I can do PR on next week

**Comment by Quy** [comment]
@Septdir Please submit a PR. Thanks.

**Comment by Septdir** [comment]
@Quy done

**Comment by Quy** [comment]
See PR #20348<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20049">issues.joomla.org/tracker/joomla-cms/20049</a>.</sub>
