### ISSUE TITLE
[4.0] Email cloak unittests are failing on 4.0

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#20054]
### Steps to reproduce the issue

http://ci.joomla.org/joomla/joomla-cms/4269/12

### Expected result

Drone works

### Actual result

Drone fails on 4.0-dev unittests

### System information (as much as possible)

After the merge of:
https://github.com/joomla/joomla-cms/pull/19089 ([4.0] email cloaking without inline script)
https://github.com/joomla/joomla-cms/pull/20053 (correction to the webcomponent call)

### Additional comments

cc @wilsonge @dgt41 

I have no quick idea what is wrong here :(

**Comment by dgrammatiko** [comment]
The test file should be updated here: https://github.com/joomla/test-unit/blob/master/suites/libraries/cms/html/JHtmlEmailTest.php

**Comment by zero-24** [comment]
Here is a PR: https://github.com/joomla/test-unit/pull/1

But to me that should not produce a `Exception: Failed to start application` error i would just expect a failed test.

**Comment by dgrammatiko** [comment]
@zero-24 can you restart drone?

**Comment by zero-24** [comment]
Just done http://ci.joomla.org/joomla/joomla-cms/4273/10 lets see what happens.

**Comment by dgrammatiko** [comment]
@zero-24 it needs a bit more I think: https://github.com/joomla/test-unit/pull/2

BTW: cannot marge my own PR, so @wilsonge

**Comment by zero-24** [comment]
I have no access to that repo to merge too :(

**Comment by dgrammatiko** [comment]
give me 5 secs the PR is not correct

**Comment by rdeutz** [comment]
it is merged and I tagged the repo so that it will be used

**Comment by rdeutz** [comment]
I will close it because I fixed it, with a couple of commits. For the record:

JHtmlEmail has now a dependency to HTMLHelper::webcomponet and this has a hardcoded dependency to Factory. So the falling test is no longer a Unit test and I removed the test.
