### ISSUE TITLE
[4.0] frontend default link of joomla like "Forgot your username?" has a 404 error.

### ISSUE THREAD

**Issue by shahryarjb** [joomla/joomla-cms#20050]
### Steps to reproduce the issue

after install the Joomla 4 for update and compatible my custom ex with Joomla 4 , I saw that frontend default link of joomla like "Forgot your username?" had a 404 error.

```
http://localhost:8888/joomla4/index.php/remind?Itemid=101

//and

http://localhost:8888/joomla4/index.php/reset?Itemid=101
```
It should be noted that I didn't do anything or change Joomla config

Please fix this problem if this problem exists.

![Joomla 4 broken link](http://s9.picofile.com/file/8322786768/Screen_Shot_2018_04_01_at_9_15_57_pm.png)

### System information (as much as possible)

os : mac os 
Mamp Version 3.5 (3.5)
php 7.0
Joomla Alpha 2

**Comment by Quy** [comment]
Unable to replicate. Please make sure you are testing with the [nightly builds](https://developer.joomla.org/nightly-builds.html).

**Comment by shahryarjb** [comment]
@Quy I have installed "nightly builds", but after install I have a "HTTP ERROR 500",  for this purpose, I installed Joomla Alpha 2 which it did not have any error.

![Joomla 4 broken link](http://s8.picofile.com/file/8322839468/Screen_Shot_2018_04_03_at_1_57_26_am.png)

**Comment by Quy** [comment]
Joomla Alpha 2 is very outdated, therefore, only the nightly builds should be tested. Please read issue #18991 to see if it will help. If not, please post to in it with your system information.
