### ISSUE TITLE
COM_USERS_LOGIN_REMIND="BenuZTernamen vergessen?"

### ISSUE THREAD

**Issue by britzke** [joomla/joomla-cms#20056]
### Steps to reproduce the issue
Install Event Gallery
Have a look at the German translated Joomla user login page.
### Expected result
There should be a link "Benutzername vergessen"

### Actual result
"Benuztername vergessen" (typo: "zt" should be "tz").

### System information (as much as possible)
Joomla! 3.8.6 Stable [ Amani ] 13-March-2018 14:00 GMT
PHP Version 7.1.15
Installed Event Gallery Package Version: 3.9.0 (build cf7f2ab)
Database Version Target Version: 3.8.4_2018-03-07

### Additional comments
In the file de-DE.com_eventgallery.ini there is an entry >COM_USERS_LOGIN_REMIND="Benuzternamen vergessen?"<. This is a typo: "zt"->"tz".
Why there is are translations for COM_USERS_*? Shouldn't they be done with the Joomla! user-login module?

**Comment by britzke** [comment]
Sorry! Wrong Issue tracker! Close this issue! I will post it on Event Gallery component<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20056">issues.joomla.org/tracker/joomla-cms/20056</a>.</sub>

**Comment by ReLater** [comment]
> Close this issue!

You can xlose it yourself.
