### ISSUE TITLE
Request for standard form field type for all media in library

### ISSUE THREAD

**Issue by robbiejackson** [joomla/joomla-cms#20057]
Please could we have a Standard Form Field Type which provides modal access to all the files in the media library.

This would be like the current "media" form field type, but wouldn't be restricted to just images.

The new field type should allow filtering, so that you could specify the types of files (eg audio / video) and file extensions (eg zip, gpx) which you would want presented in the modal window. 

A personal suggestion would be to extend the current media file type to include 2 other parameters which would control the filtering of what to display:
* an array of something like mime types (eg "audio/*" for presenting audio files)
* an array of file extensions

If these parameters weren't set then the functionality could revert to what is presented at the moment, which is like a mime type of image/*

**Comment by brianteeman** [comment]
That would be awesome if you could submit a PR for it

**Comment by Quy** [comment]
Please test PR #19967

**Comment by ghost** [comment]
closed as having Pull Request #19967.
