### ISSUE TITLE
User Note is still remains if the user is deleted

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#20060]
### Steps to reproduce the issue
I added a User Note to the user. Then I decided to remove this user, but if I go to User Notes, I see the entry which is not associated with the user since the user just been removed.
I suppose the user notes must be removed together with users.
 

### System information (as much as possible)
Joomla 3.8.6
PHP 7.0.29

![screen shot 2018-04-02 at 16 24 18](https://user-images.githubusercontent.com/3432048/38197724-592a31ca-3692-11e8-8e62-d495f1f5bf78.png)

**Comment by brianteeman** [comment]
if you look at the code in #20051 you will see the code to delete usernotes when a user is deleted

**Comment by Sulpher** [comment]
Thanks for the URL. 
Actually, I do not watch for recent changes and updates in Github. I founded the issue and have been reported it. If this is known bug, then this topic can be closed.
