### ISSUE TITLE
[3.8.6] [com_associations] com_fields and other tabs are not copied into the target language

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#20067]
### Steps to reproduce the issue
- Select an article in com_associations in one language
- Select a target language
- Click on "Copy Reference to target"

### Expected result
- custom fields should be copied too
- Images and Links should be copied too

### Actual result
- The custom fields are not copied to the target
- Images and Links are also not copied

**Comment by infograf768** [comment]
Here: Images and links are copied OK.
![screen shot 2018-04-04 at 07 49 47](https://user-images.githubusercontent.com/869724/38290702-d3024f5a-37dc-11e8-9ded-ee92d50095cf.png)

Concerning Custom fields:
If the custom field is tagged to All languages, it will be copied OK. 
If not and there is no Custom field tagged to the target language, the fields tab will not even display for the Target (and this is fine).
If there is a custom field tagged to the target language, it will display with its default value (if there is one)

**Comment by coolcat-creations** [comment]
I tested in staging now and it indeed works there, not in my installation. Either it was fixed somewhere or there is another bug. Thanks for testing @infograf768
