### ISSUE TITLE
[com_fields] 3.8.6 if Category is deleted, commas are shown behind the remaining one or nothing

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#20066]
### Steps to reproduce the issue
Assign a Field to severall Categories
Delete some of the Categories
Delete also from trash

### Expected result

The overview shows the Assignment to the remaining categories 

### Actual result
 Some commas appear behind the remaining categories
![grafik](https://user-images.githubusercontent.com/828371/38240357-ac9d9da4-372f-11e8-9f04-1d441a757c24.png)

or none:
![grafik](https://user-images.githubusercontent.com/828371/38240390-c4257ed8-372f-11e8-9ef7-59d11c53e32d.png)

**Comment by tonypartridge** [comment]
pr in ;-)

**Comment by Quy** [comment]
See PR #20093<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20066">issues.joomla.org/tracker/joomla-cms/20066</a>.</sub>
