### ISSUE TITLE
Backend: Search article content

### ISSUE THREAD

**Issue by smehrbrodt** [joomla/joomla-cms#20072]
The backend currently does not allow to search the article content. Only the title can be searched.

It should be possible to search the article content also.

**Comment by tonypartridge** [comment]
The issue with this is it becomes quite a heavy search with a lot of articles.  What a tick box? Keyword search content?

**Comment by smehrbrodt** [comment]
> The issue with this is it becomes quite a heavy search with a lot of articles. What a tick box? Keyword search content?

I don't think this would have any big performance implications, databases are fast at searching stuff. Also our frontend search also does this already.

Adding an option whether to search the content or not might be considered, I have no strong opinion there, as long as it's possible at all to search the content.

**Comment by smehrbrodt** [comment]
I created a pull request for this: #20083.
It allows to search the content by prefixing the search with `content:`. We have a similiar solution for searching ids and authors.

Let me know what you think about this.

**Comment by infograf768** [comment]
Closing as there is a patch
