### ISSUE TITLE
Disabling tag filtering requires new session.

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#20081]
### Steps to reproduce the issue
Create some articles and tags.
Create a menu item with 'Category Blog' type and select some tags for filtering.
View the page on frontend.
Now disable filtering by tags in the menu item and view the same page again.

### Expected result
Articles not filtered by tags.

### Actual result
Articles still filtered by tags until new session is started.

### System information (as much as possible)
J! 3.8.6
PHP 7.2.3

### Additional comments
This issue is similar to #18138 and #18299 which were solved with #18248.

**Comment by tonypartridge** [comment]
Are you disabling filtering on the menu item configuration? or within page filter?

**Comment by SharkyKZ** [comment]
In the menu item. Unless I'm missing something, Category Blog doesn't have a filter form. Only Category List does. Which is why, in my opinion, it would be OK to use value from request instead of user state for blog layout.

**Comment by tonypartridge** [comment]
Ok so this isn’t a bug. It makes no sense to add extra code for a user configuration issue. 

You have changed a setting for your menu item, when this is done it’s good practice to clear session and cache.

**Comment by ghost** [comment]
Closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20081">issues.joomla.org/tracker/joomla-cms/20081</a>.</sub>
