### ISSUE TITLE
[4.0] Mass Mail User Group Selector

### ISSUE THREAD

**Issue by lalitkumarjoomdev** [joomla/joomla-cms#20097]
Steps to reproduce the issue
Remove size="10" attribute.

Expected result
https://www.screencast.com/t/HDMDUhaWRjvs

Actual result
https://www.screencast.com/t/bgqbAPFw

Additional comments
Select field is not working properly because extra attribute (size="10") in select field.

**Comment by brianteeman** [comment]
I can't replicate this. The field should be using chosen which sets the default field with size=10 to hidden. So the only way you can have this problem is if chosen is not being loaded.

**Comment by tonypartridge** [comment]
There is more going on in that SS @brianteeman look at the tick boxes? All ajar too.

You either have a plugin/theme styling it. Or are missing some styles/js.

**Comment by SharkyKZ** [comment]
Should mention this is from 4.0. And probably an older build. 4.0-dev looks different but the issue remains. It's coming from Bootstrap. Happens when `size` attribute is added to select with `custom-select` class. It's Bootstrap's way of having a multi-select.
https://github.com/joomla/joomla-cms/blob/4.0-dev/media/vendor/bootstrap/scss/_custom-forms.scss#L198
The obvious solution is to remove the size attribute or change its value to 1.

**Comment by ghost** [comment]
Changed Title to be clear its about 4.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20097">issues.joomla.org/tracker/joomla-cms/20097</a>.</sub>

**Comment by dgrammatiko** [comment]
Just a note here: chosen is already in the legacy folder and probably will not be shipped at all in J4. There is some research going on right now on for the replacement script. 
That being said I wouldn't touch the BS library, as we shouldn't touch any files in the vendor folder. Neither chosen should be patched for this at the moment as it's candidate for total removal...
So keep this open and we will revisit the issue with the new script in place

**Comment by Quy** [comment]
No longer reproducible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20097">issues.joomla.org/tracker/joomla-cms/20097</a>.</sub>
