### ISSUE TITLE
Mass Mail User Group Selector

### ISSUE THREAD

**Issue by lalitkumarjoomdev** [joomla/joomla-cms#20096]
### Steps to reproduce the issue
Remove size="10" attribute.

### Expected result
https://www.screencast.com/t/HDMDUhaWRjvs

### Actual result
https://www.screencast.com/t/bgqbAPFw

### Additional comments
Select field is not working properly because extra attribute (size="10") in select field.

**Comment by brianteeman** [comment]
Can you please explain what does not work - perhaps with screenshots.

**Comment by Quy** [comment]
Duplicate #20097<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20096">issues.joomla.org/tracker/joomla-cms/20096</a>.</sub>
