### ISSUE TITLE
[4.0] RTL problem in atum admin template

### ISSUE THREAD

**Issue by shahryarjb** [joomla/joomla-cms#20102]
### Steps to reproduce the issue

I decided to test joomla 4 in dev-4 branch , then I saw many RTL problems in atum admin template . 
It should be noted that I oneself wanted to apply these changes, but I felt that you had a plan for that.

Please see these pic: 

### False

![screen shot 2018-04-07 at 12 04 27 am](https://user-images.githubusercontent.com/8413604/38441180-19a6c7ba-39f9-11e8-8910-0a2541c8acac.png)

### True

![screen shot 2018-04-07 at 12 18 36 am](https://user-images.githubusercontent.com/8413604/38441228-41d40ad6-39f9-11e8-9f42-3bd3a148027b.png)

---

### False
![screen shot 2018-04-07 at 12 19 53 am](https://user-images.githubusercontent.com/8413604/38441266-7132ade6-39f9-11e8-90ae-0e322a4bde89.png)

### True

![screen shot 2018-04-07 at 12 21 20 am](https://user-images.githubusercontent.com/8413604/38441336-a20a0fe0-39f9-11e8-8b1e-20d6a260361e.png)

----

### False
![screen shot 2018-04-07 at 12 22 29 am](https://user-images.githubusercontent.com/8413604/38441429-efee408c-39f9-11e8-8bcb-40dd02313817.png)

### True

![screen shot 2018-04-07 at 12 23 25 am](https://user-images.githubusercontent.com/8413604/38441438-f8802620-39f9-11e8-8e87-52b9df70db06.png)

----

### False
![screen shot 2018-04-07 at 12 26 12 am](https://user-images.githubusercontent.com/8413604/38441557-62ff88ce-39fa-11e8-958a-728c3070038f.png)

### True
![screen shot 2018-04-07 at 12 26 31 am](https://user-images.githubusercontent.com/8413604/38441563-697fd4ba-39fa-11e8-8ee6-8f5f50fc69ef.png)

----

### False

![screen shot 2018-04-07 at 12 28 10 am](https://user-images.githubusercontent.com/8413604/38441639-ad28ebd4-39fa-11e8-84ef-38616a1b8d88.png)

### True

![screen shot 2018-04-07 at 12 28 33 am](https://user-images.githubusercontent.com/8413604/38441653-b9993e5a-39fa-11e8-9b69-ff205b513f75.png)
----

### False
![screen shot 2018-04-07 at 12 29 34 am](https://user-images.githubusercontent.com/8413604/38441678-d2f21a0c-39fa-11e8-8b96-7685acfd101a.png)

### True
![screen shot 2018-04-07 at 12 30 26 am](https://user-images.githubusercontent.com/8413604/38441707-e8c4bcae-39fa-11e8-88df-d8cc4a3bd2fb.png)

and bugs ....

---
### System information (as much as possible)
os : mac
mamp 
php 7.0
joomla dev-4
safari

Thanks

**Comment by brianteeman** [comment]
Thank you very much for taking the time to make the report. 

The version of the template here is not the latest version. There is a new one under development here https://github.com/joomla/40-backend-template/

Be assured that RTL is a priority to be addressed. But they need some more time to finalise the way the template is to work before fully testing in RTL

**Comment by brianteeman** [comment]
@C-Lodder It might be good to have a dedicated RTL person on the team?

**Comment by C-Lodder** [comment]
No longer anything to do with me

**Comment by brianteeman** [comment]
I am closing this as sit has been addressed elsewhere
