### ISSUE TITLE
Invalid mime type detected: xlsx

### ISSUE THREAD

**Issue by Rollmodl** [joomla/joomla-cms#20108]
Cannot upload Excel spreadsheets

### Steps to reproduce the issue
1. Added xlsx and XLSX to Legal Extensions.
2. Checked MIME type using http://mime.ritey.com/.
3. Added application/vnd.openxmlformats-officedocument.spreadsheetml.sheet to Legal MIME Types

### Actual result
Receiving Error: Invalid mime type detected.

### Additional comments
Also tried disabling "Check MIME Types"

**Comment by tonypartridge** [comment]
Did you add it to the allowed media manager list? Within the media manager options?

**Comment by tonypartridge** [comment]
Skip that just reread your post 🙈. Will also run a test!

**Comment by Quy** [comment]
In `\libraries\src\Helper\MediaHelper.php`, above line 254 `// Get the mime type this is not an image file`, add the following:
```
var_dump($this->getMimeType($file['tmp_name']));
exit;
```

Please advise the value of the output.

**Comment by Rollmodl** [comment]
After upload I'm getting the page/message: **bool(false)**

**Comment by Quy** [comment]
Please read issue #16238. It has to do with PDF but the information should still be applicable in your case.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20108">issues.joomla.org/tracker/joomla-cms/20108</a>.</sub>

**Comment by suniljaswaniit** [comment]
You can add (application/vnd.openxmlformats-officedocument.spreadsheetml.sheet) this in Legal MIME types in the list and add xlsx in the Legal Extensions(File Types).
You can find this setting in Joomla administrator > Global > Media Settings.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20108">issues.joomla.org/tracker/joomla-cms/20108</a>.</sub>

**Comment by mimfa** [comment]
add "xlsx" and "XLSX" to your Legal File Types then add "application/vnd.openxmlformats-officedocument.presentationml.presentation" to your Legal MIME Types;

**Comment by acvmultimedia** [comment]
Thanks!! For the solution :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20108">issues.joomla.org/tracker/joomla-cms/20108</a>.</sub>
