### ISSUE TITLE
500 Layout default_batch not found

### ISSUE THREAD

**Issue by webman77** [joomla/joomla-cms#20110]
### Steps to reproduce the issue
When I click on managed users I get the following error
Can anyone help me fix this issue?

I am using Ipublisher & Joomla Social
idiotfreezone.com

500 Layout default_batch not found

**Comment by Bakual** [comment]
Please use the forums for support requests: forum.joomla.org

**Comment by ghost** [comment]
@webman77 Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding. For this Reason this Issue was closed, thanks.
