### ISSUE TITLE
PostgreSQL 10.0 Compatibility

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#20114]
After setting up an environment where tests are run against PostgreSQL 10.0, there are a couple of unit test failures which look to be related to changes in the engine.  These should be addressed both here and in the Framework repo.

Build example with failures - https://travis-ci.org/joomla-framework/database/jobs/363856099

**Comment by brianteeman** [comment]
When you say "here" do you mean in J3 and J4 or just J3

**Comment by mbabker** [comment]
Here for J3, FW repo for FW 1.x and J4 (since J4 is consuming the FW repo).

**Comment by alikon** [comment]
still not having a chance to play with a 10 instance just reading this
https://www.postgresql.org/message-id/CAE3TBxz4BkhcvYwCxtRpQyqu5NVjMAxgun5vhasM5C%2BkDcuCRA%40mail.gmail.com

**Comment by mbabker** [comment]
Anyone?  PostgreSQL 11 is already in beta too.

**Comment by alikon** [comment]
shame on me still on 9.X

**Comment by csthomas** [comment]
For FR 2.x it should be resolved by https://github.com/joomla-framework/database/pull/125

I can test on postgreSQL 10.4

**Comment by brianteeman** [comment]
@csthomas are you able to make similar changes (if needed) here for j3?

**Comment by csthomas** [comment]
Done, see https://github.com/joomla/joomla-cms/pull/21370

**Comment by ghost** [comment]
closed as having Pull Request #21370
