### ISSUE TITLE
[com_fields] RFC: Category List: Allow filtering by fields

### ISSUE THREAD

**Issue by smehrbrodt** [joomla/joomla-cms#20116]
When creating a category list, you can add a filter which filters content, author, tags.
But it's not possible to filter custom fields at the moment.

This should be supported too.

**Comment by ghost** [comment]
@laoneo can you please give a Comment on these Feature Request?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20116">issues.joomla.org/tracker/joomla-cms/20116</a>.</sub>

**Comment by laoneo** [comment]
Are you refering the front or back end? Would be a nice feature but will take some effort as the filters are currently hard coded.

**Comment by Bakual** [comment]
If I remember right, this was left out intentionally when custom fields were implemented.
It isn't an easy task to implement something like this in an architectural acceptable way.
One thing is showing the filters, another thing is actually performing the filtering function.
The latter would need some hook in the models where the query could be altered by com_fields.

**Comment by mbabker** [comment]
Implementing that requires a level of CCK capabilities that is not present in the code.  If I'm not mistaken we decided com_fields is not a CCK solution.

**Comment by Bakual** [comment]
>  If I'm not mistaken we decided com_fields is not a CCK solution.

That was my understanding as well.

**Comment by peteruoi** [comment]
Imo it would be really usefull and ofc custom fields wouldn't become cck due to this. I think the functionality of custom fields would be more completed (something like the ordering of the stars of the voting plugin).
So from a "politics" point of view i think we don't exceed the line of a wanna-be-cck but we add real nice functionality which will be very useful to people.
From the technical point of view you are the experts if it can be done easily (or at all) anf if there is someone willing to implement it:)

**Comment by mbabker** [comment]
It is technically too large of a change to make without making a full blown CCK system (the select lists generating filterable columns have to be fields aware, each component's models supporting fields has to be able to build a very highly dynamic SQL query for any of the fields the user creates; those two items on their own mandates a CCK based architecture and at that point you might as well build a full CCK solution).

**Comment by ghost** [comment]
Issue closed, Reason is Discussion above. It can always reopened if needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20116">issues.joomla.org/tracker/joomla-cms/20116</a>.</sub>
