### ISSUE TITLE
meta-robots special settings are not working for items or component/tags ? Only default setting is active

### ISSUE THREAD

**Issue by Repitol** [joomla/joomla-cms#20128]
### Steps to reproduce the issue
Hi, when you choose in Joomla settings - Robots : index,follow
the meta tag isn't displayed in source code even for articles set to no-index, no-follow.
I could see the same problem for tags set to "no-index, no-follow"
it seems the settings in Joomla configuration overrides what you set elsewhere

### Expected result
article or tags settings in publishing/robots "no-index,no-follow" should be taken into account
source code should displays <meta name="robots" content="noindex, nofollow" />

### Actual result
If general Joomla settings are set to robots : Index, follow
source code doesn't display meta name robots even when you change that on some contents
so these contents are indexed and followed

### Additional comments
tested on Joomla 3.8.6 with every default templates or commercial templates
Can you reproduce the bug ?
That is a real problem for content you don't want to be indexed.
Thanks

**Comment by brianteeman** [comment]
It is correct that if you set index,follow that it is not in the source because this is the default behaviour so it is not needed.

I set an article to no index, no follow and it was correctly set as that

**Comment by Repitol** [comment]
Hi,
right; it works for article but not for tags pages
If you create a tag then go to component/tags/ and set this tag as no-follow
can you see the meta in the source code for the tag page ?
Sometimes tags pages doesn't need to be followed.
Thanks

**Comment by Repitol** [comment]
Hi, should I open a new thread for this problem in tag pages ?
regards

**Comment by jwaisner** [comment]
@Repitol are you still experiencing this issue in the latest version of J3?

**Comment by ReLater** [comment]
Yes, it's a bug (or not ;-) ).

The main problem is that all tags view.html.php can display 0, 1 ore more tags on 1 page.

The only half-baked solution I see for this issue is to check if only 1 tag is displayed on a `tag` view page and only then let rule the robots setting of this single tag.
(I'll try a pr.)

Another solution could be to declare the setting "robots" as misleading and remove it from tag settings.

**Comment by ReLater** [comment]
Please test https://github.com/joomla/joomla-cms/pull/28334
(and discuss ;-) )
