### ISSUE TITLE
GSD - Google Structured Data - quid of "publisher"

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#20129]
### Steps to reproduce the issue
We have been working on GSD - Google Structured Data on our sites, and while trying to comply with the guidelines, we noticed that, even if itemprop="publisher" does exist in types.json (/libraries/src/Microdata/types.json), it is not implemented anywhere else.

Result : a recurring error when checking with[ Google structured data testing tool](https://search.google.com/structured-data/testing-tool "").

We found this recommendation on Google forums and it works (inserted in an article).

```
<div itemprop="publisher" itemscope itemtype="http://schema.org/Organization"> <p>© 2018 <span itemprop="name">My site name</span> All Rights Reserved.</p>
<div itemprop="logo" itemscope itemtype="https://schema.org/ImageObject"><meta itemprop="url" content="complete_url_to_the_image/logo.png"><meta itemprop="height" content="215"/><meta itemprop="width" content="730"/></div> 
</div>
```

Is there a specific reason why this "type(?)" has not been included in Joomla, in info_block.php for example.

NB : We had to exclude some native modules as well, in order to fully comply to Google structured data testing tool on a simple page.
NB 2 : A warning on mainEntityOfPage :
The mainEntityOfPage field is recommended. Please provide a value if available.
As it is only a warning, I'll leave this aside.

**Comment by jurihahn** [comment]
<img width="573" alt="gsd" src="https://user-images.githubusercontent.com/36074425/38769652-ab46de40-4006-11e8-8a0a-ce5969a28a36.png">
+1

**Comment by ghost** [comment]
@jurihahn can you please provide an english Screenshot?

**Comment by jurihahn** [comment]
sorry ;)
<img width="654" alt="gsd" src="https://user-images.githubusercontent.com/36074425/38769889-8afe822e-400a-11e8-982f-22fa7ec23490.png">

**Comment by fontanil** [comment]
Hi,

"datemodified" is an option in details for articles: add it and this error will disappear.
On single article, "headline", publisher" and "mainEntityOfPage" are missing when testing with Google testing tool.

On single article, "image" is missing if you add it in article body, not when you insert it with "images and links" tab.
On blog mode, "image" is always missing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20129">issues.joomla.org/tracker/joomla-cms/20129</a>.</sub>

**Comment by jurihahn** [comment]
I think it is important to fix "Error" with "publisher" field.
I have Joomla 3.8.6 and use default Template Protostar.

**Comment by jwaisner** [comment]
@ghazal is this still an issue in the latest J3 build?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20129">issues.joomla.org/tracker/joomla-cms/20129</a>.</sub>

**Comment by elian1994** [comment]
![Structured Data](https://www.isemc.com/images/news/20220106143048.png "Structured Data")

I saw this by accident, and J3 still exists.
My [iSEMC](https://www.isemc.com/ "iSEMC") website uses the J3 version, and I also used extended verification, but there are still errors; is there anyone who has successfully eliminated the warning?

Because I indicated on Semrush that this is a serious mistake,

Does J4 also have this problem?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20129">issues.joomla.org/tracker/joomla-cms/20129</a>.</sub>

**Comment by brianteeman** [comment]
Going to close this one now that we have a schema.org implementation
