### ISSUE TITLE
[4.0] Installation step Sample Data fails

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#20134]
### Steps to reproduce the issue
- 4.0.0-dev of today.
- Started installation.
- Selected MySQLi as database type.
- Database was created.
- configuration.php was written with
	`public $dbtype = 'mysqli';`
- Then I skipped "Install Language packages" and
- continued with "Install sample data"

There I have an endless rotating Joomla logo and a message "Warning! Please select the database type"

![10-04-_2018_22-57-14](https://user-images.githubusercontent.com/20780646/38583330-f2203bdc-3d12-11e8-938a-0ace7e97aa34.png)

I tried several times to install sample datas in the past; since the first alpha release of Joomla 4.

Never successfull.

**Comment by Bakual** [comment]
The sample data step should removed from the installation since we can now install it afterwards from the control panel.

**Comment by ReLater** [comment]
Would be nice then to have the possibility to install the testing sample data and not only the blog sample  data.

**Comment by Bakual** [comment]
See https://github.com/joomla-extensions/testing-sample-data

**Comment by ReLater** [comment]
Sorry for delayed answer. I didn't get your comment per email.
Will the plugin become a core extension or stay decoupled?
Shall I leave the issue open as a reminder because of the installation process?

**Comment by infograf768** [comment]
I would close the issue and create a new one stating that sample data is still proposed when installing J4.
Another issue is that one gets in a loop when instaliing (at Joomla installation time) one of the 3 languages we can install for testing purposes in J4, i.e. French, German or Persian. Issue not present when installing these langs in admin.

**Comment by Bakual** [comment]
> Will the plugin become a core extension or stay decoupled?

@ReLater The idea is it stays decoupled.

**Comment by ciar4n** [comment]
> The sample data step should removed from the installation since we can now install it afterwards from the control panel.

Exporting SQL is a very quick way for template developers to create 'Quick Installs' of their template demos. Would we not be asking a lot of template devs to create and maintain plugins for every one of their templates were we to remove this option?

**Comment by infograf768** [comment]
> The idea is it stays decoupled.

No real opposition for that one, but we still need a multilingual sample data plugin as, for now, it is really a pain to create a default multilingual site to test but also propose as sample for new users.
Also, that one should not be decoupled as we need TTs to translate it.

**Comment by Bakual** [comment]
> Exporting SQL is a very quick way for template developers to create 'Quick Installs' of their template demos. Would we not be asking a lot of template devs to create and maintain plugins for every one of their templates were we to remove this option?

Quick is not always best or even correct. We had a lot of issues generated by using a direct SQL approach and it was becoming also unmaintainable. That's why a different approach was needed.
Once you start into that plugin approach, you will see that it actually allows a lot more and in easier to manage ways. I'm sure template devs will find a way where they can write one plugin that fits for all their templates.

> we still need a multilingual sample data plugin

Just needs someone to write it :smile:

**Comment by ReLater** [comment]
Closing here.
- Reminder related to sample data: https://github.com/joomla/joomla-cms/issues/20262

@infograf768 

> Another issue is that one gets in a loop when instaliing (at Joomla installation time) one of the 3 languages we can install for testing purposes in J4, i.e. French, German or Persian. Issue not present when installing these langs in admin.

Because i don't understand this I haven't mentioned it in 20262
