### ISSUE TITLE
Joomla Notice:: Do not show all the notices and trim the height of the notice window by adding 'See more' option

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#20131]
1. Check the Joomla notice UI (by turning off the folder permission)
2. When the notices are more than 5 or 10, Ideally we should trim the notice height by adding **See more/See less** option

Current issue is, if there are many notices/warnings, it covers the full height of the screen which we should avoid.![screen shot 2018-04-10 at 11 45 35](https://issues.joomla.org/uploads/1/f603dc7fa6552918a38d3bfe15e47834.png)

**Comment by brianteeman** [comment]
Seems the expected behaviour to me

**Comment by aasimali** [comment]
@brianteeman I agree that it will be as expected, but, what I believe as an end user of Joomla is, If we add See more and See Less, then it will be a helpful.

And what I have experienced is, people are less interested to see all the warnings or notices or a big paragraph in one go, that's why, the see more and see less concept came into the picture.

See, if it makes sense to add that option  [It was just a suggestion from my end not a bug]

Thank you

**Comment by brianteeman** [comment]
If you want to propose some code for this then go for it. I just feel its a really edge case

**Comment by brianteeman** [comment]
Closed at this time. If someone wants to create some code for this edge case then nothing is stopping them but no point in keeping this open
