### ISSUE TITLE
[4.0] com_banners. Drag and drop ordering fails. Undefined method createTagsHelper

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#20136]
### Steps to reproduce the issue
- Joomla 4.
- Create 3 or more new banners inside same category.
- Order list by "Ordering" column.

![10-04-_2018_23-26-43](https://user-images.githubusercontent.com/20780646/38584527-e0af0c26-3d16-11e8-8acd-6700e7f5c4d2.jpg)

- Reorder banners with drag and drop feature.

![10-04-_2018_23-29-23](https://user-images.githubusercontent.com/20780646/38584601-1743d564-3d17-11e8-9c71-af3695088962.jpg)

- Click "Banners" in left menu to reload current banners list.

==> New ordering is lost:
![10-04-_2018_23-31-17](https://user-images.githubusercontent.com/20780646/38584766-a232e8cc-3d17-11e8-8d1a-bd8b94929a64.jpg)

### Additional comm.
No warnings or errors in developer tools.

**Comment by brianteeman** [comment]
closed see #19739

**Comment by ReLater** [comment]
Made some further investigations and it looks like that this one is another issue

I get the following error in tabulator "XHR" > "Preview":
`An error has occurred.`

`0 Call to undefined method Joomla\Component\Banners\Administrator\Mode\BannerModel::createTagsHelper() `

The method createTagsHelper() has been removed in Joomla 4 from all models, I think.

**Comment by ReLater** [comment]
This is the line where the non-existent method is called:
https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/MVC/Model/AdminModel.php#L1337

**Comment by ReLater** [comment]
@brianteeman 
Please reopen.

**Comment by ghost** [comment]
Reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20136">issues.joomla.org/tracker/joomla-cms/20136</a>.</sub>
