### ISSUE TITLE
PHPStorm IDE cannot find declarations

### ISSUE THREAD

**Issue by Serhioromano** [joomla/joomla-cms#20132]
I use PHPStorm as IDE to develop components for Joomla for few years already. It used to work perfectly. But one moment, not sure exactly when, it stoped intellisense on a lot of things. 

For instance very basic `JFactory`. SO when ever I use it I have to type manually by memmory. Why is that? I am sure it is some weired Joomla library structure and not PHPStorm issue. 

![2018-04-10_22-04-24](https://user-images.githubusercontent.com/650741/38568749-3dcbe3cc-3d0b-11e8-887f-cf38b7dd05f8.png)

### Steps to reproduce the issue
Just make project out of Joomla 3.8 folder.

### Expected result
I expect intellisense

### Actual result

No intellisense

### System information (as much as possible)

No

### Additional comments

One of possible reasons may be multiple declarations

**Comment by Quy** [comment]
Duplicate #20030 ?

**Comment by rdeutz** [comment]
It is because of the namespacing, we have a script build/stubGenerator.php that will created a stub.php in the root and then you are good to go and it should work as before

**Comment by Serhioromano** [comment]
> @rdeutz It is because of the namespacing, we have a script build/stubGenerator.php that will created a stub.php in the root and then you are good to go and it should work as before

And how do I do I run it? In a terminal `php ./build/stubGenerator.php`? Or how?

**Comment by roland-d** [comment]
@Serhioromano 2018.1 should recognize it out of the box otherwise use the EAP build.

**Comment by rdeutz** [comment]
> And how do I do I run it? In a terminal php ./build/stubGenerator.php 

sounds right

**Comment by Serhioromano** [comment]
> @roland-d 2018.1 should recognize it out of the box otherwise use the EAP build.

Thank you for hint. I use older version, till now I did not see the value of purchasing update.
