### ISSUE TITLE
[4.0] All images are display:block

### ISSUE THREAD

**Issue by Serhioromano** [joomla/joomla-cms#20143]
Cassiopeia template.

### Steps to reproduce the issue
Look in browser inspector
![2018-04-11_18-24-17](https://user-images.githubusercontent.com/650741/38618083-6f473410-3dba-11e8-92fe-f3ab475a820c.png)

### Expected result
![2018-04-11_19-00-57](https://user-images.githubusercontent.com/650741/38618224-cc41089e-3dba-11e8-84bf-6c98bc41a449.png)

### Actual result
![2018-04-11_19-01-26](https://user-images.githubusercontent.com/650741/38618231-cff28396-3dba-11e8-8554-913caca8246e.png)

 I add navbar to my extension. By picture in brand name break new line. 

### System information (as much as possible)

Windows 7 SP1
PHP 7.2.1-x64
Joomla 4.0.0-alfa

### Additional comments

I did not look deep inside, but I hope you will not do it like BS 2.3 was integrated before. The best way is to include pure BS 4 and then after that template CSS to override. But not extend BS 4 CSS and create your own. that proved to be wrong idea. that lead to inability to keep BS updated from release to release of Joomla.

**Comment by ciar4n** [comment]
Agree! Thank you for reporting.

PR created... #20155
