### ISSUE TITLE
[4.0] Fatal error on stub generation

### ISSUE THREAD

**Issue by Serhioromano** [joomla/joomla-cms#20141]
Produce error

### Steps to reproduce the issue
run in terminal `php ./build/stubGenerator.php`

### Expected result

stub.php generated

### Actual result

Fatal error: Class Joomla\CMS\Crypt\Cipher\CryptoCipher contains 1 abstract method and must theref
ore be declared abstract or implement the remaining methods (Joomla\Crypt\CipherInterface::isSuppo
rted) in C:\OSPanel\domains\joomla4\libraries\src\Crypt\Cipher\CryptoCipher.php on line 21

### System information (as much as possible)

php 7.2
Windows 7 SP1
Terminal in PHPStorm

### Additional comments

No

**Comment by Bakual** [comment]
Works fine for me with PHP 7.2.1.

**Comment by Serhioromano** [comment]
Do you use release or install from github branch? Also error message is clear. Do you have abstract method in `Class Joomla\CMS\Crypt\Cipher\CryptoCipher` in your version?

**Comment by Bakual** [comment]
latest github 4.0-dev branch. And no, that class doesn't have an abstract method.
See https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Crypt/Cipher/CryptoCipher.php

**Comment by mbabker** [comment]
The file clearly shows that the method that your error message says is missing is there (the error message is saying the interface's `isSupported` method is not defined).

**Comment by Bakual** [comment]
Just checked, that method was commited last november (https://github.com/bakual/joomla-cms/commit/0ae9aaa8f5097105d67e6524ae3c42f471182299).

I'm closing this issue as it looks just like your installation is outdated. It looks like the alpha which was released just between the lines got added to the interfaces and the above mentioned commit.
