### ISSUE TITLE
missing brace in default_items.php

### ISSUE THREAD

**Issue by RANDOMLY-OBFUSCATED** [joomla/joomla-cms#20149]
Hello,

### Steps to reproduce the issue
open the file plugins/system/gantry/overrides/3.0/2.5/com_content/archive/default_items.php
read at line 19 and search for the closing brace

### Expected result
need a closing brace after the line 21

### System information (as much as possible)
Joomla! 3.8.6

**Comment by laoneo** [comment]
That's an extension specific issue. Please forward it to the extension developer.

**Comment by RANDOMLY-OBFUSCATED** [comment]
Ok, I was not sure due to the header's file vs repertory.
May not possible: Don't find where to report issue about Gantry 4.
Not maintained any more ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20149">issues.joomla.org/tracker/joomla-cms/20149</a>.</sub>
