### ISSUE TITLE
2 Factor authentication - remember

### ISSUE THREAD

**Issue by jjnxpct** [joomla/joomla-cms#20150]
We want to start using (Google) two-factor authentication on the sites we manage for our clients.  But we manage about 100 sites and adding this authentication will cost us a lot of extra time to maintain the sites. 

I was wondering if it would be possible to 'remember' the authentication for a specific period of time (say 30 days) before having to enter a new code. Maybe in combination with remembering the IP is was submitted from. This wat we don;t have to authenticate every time we log in. Only every 30 days.

Or would this just defeat the purpose of the extra protection?

Kind regrads,
Jip

**Comment by brianteeman** [comment]
yes that would completely defeat the entire reason for having 2fa

**Comment by jjnxpct** [comment]
Google uses 'trusted devices':
++++++++++++++++
__If you don’t want to enter a 2-Step Verification code or use your Security Key every time you sign in to your Google Account, you can mark your computer or mobile device as trusted. With trusted computers and devices, you don’t need to enter a verification code each time you sign in._
+++++++++++++++++
https://support.google.com/accounts/answer/2544838?hl=en

So would that not be an option to use for Joomla!?

**Comment by brianteeman** [comment]
that is two step authentication and not two factor authentication iirc

**Comment by jjnxpct** [comment]
Ah right ;-) So 'trusted devices' only work with _two-step_ (like a sms with code to you phone) and not with _two-factor_ (Google app with 30 second code).

**Comment by jjnxpct** [comment]
Sorry for pushing this issue, but I also use Lastpass as a password manage. They make it possible to login to your account using two-factor authentication but also have the option to 'trust' the computer for 30 days. So this is possible... right?
![2018-04-13_09-38-37](https://user-images.githubusercontent.com/4346247/38722721-1efe6fe6-3eff-11e8-8fd9-31dd4f695553.png)

Or am I still missing something ;-)

**Comment by ggppdk** [comment]
Because of not having support for trusted devices this feature is 
a bit of a nuinance ...
thus enabled less than expected, or disabled after some time and doing other alternatives

Quoting about trusted devices :

> Devices that do not need a second step
> You can skip the second step on devices that you trust, such as your own computer.

**Comment by jjnxpct** [comment]
Two factor authentication was recently also added to myjoomla.com. Also with a trusted device option. So It is possible... Don't know if it is more or less safe. I do think this option would encourage more site managers to use 2FA.

**Comment by brianteeman** [comment]
myjoomla.com does not use joomla ;)

**Comment by jjnxpct** [comment]
Haha, no I'm sure it doesn't... I just wanted to point out that 2FA can be used with a 'trust' option. So it would be technically possible to add this to Joomla as well. Am I right?

**Comment by tonypartridge** [comment]
Of course it’s technically possible.... almost anything is! But having someone to do it is another question :-).

**Comment by eshiol** [comment]
@tonypartridge, I hope that answers your question :)

**Comment by ghost** [comment]
closed as having Pull Request #20191.
