### ISSUE TITLE
The eternal problem with the sessions in Joomla

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#20159]
![image](https://user-images.githubusercontent.com/3662519/38725823-26b009ea-3f11-11e8-8f5b-9bf010cfe32e.png)

Joomla has from the very beginning, since version 1.0 problem with the fact that if you set the time of the session for 15 minutes or 1 hour, then after the expiration of this time, you will have to reauthorize on the site.

That is, if you edited a large article in the admin panel for several hours, then after clicking on the "save article" button, you will lose all the data, all the text that you wrote. I have not seen a similar problem in other CMSs. This is a very big and important problem for Joomla.

Here's an example - if I went to Facebook and write a large text for several hours, then I do not have such a problem with the authorization. I do not need to log in again on the social network and my text will not be lost if I want to publish it.

Maybe there is some solution to this problem for Joomla?

Is it possible to do so that if a user types the text, for example in the admin panel or comments on the news on the site, that his session lasts during the period when he writes the text, that he was online when he typed text or viewed several news on the main page of the site - for example, moves through the page of the site down.

I believe that this is now the most painful problem of this CMS! We need to find a solution with authorization on the site!

**Comment by joomdonation** [comment]
I believe Joomla already has solution for this problem - at least from reading the code. It's called keepalive behavior in our code base, see https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/views/article/tmpl/edit.php#L18

With that line of code added to create article page, Joomla will keep making AJAX request after certain time (depends on session lifetime setting) to make sure you are not being logged out while still on submit article form:

- If you are not using Database Session handler, that request will be make every 5 minutes
- If you are using Database Session handler, that request will be make every (SESSION_LIFETIME - 1) minutes

**Comment by 4digitalworld** [comment]
@joomdonation Does it work in Joomla by default?

**Comment by joomdonation** [comment]
Yes, the code is in Joomla by default, so it should work.

**Comment by ggppdk** [comment]
Yes, it is inside the "default" edit.php template file

If (session) keepalive feature is not working for you
then check
- if you have a template override that does not include it
- if you have a JS error during initial form load

**Comment by brianteeman** [comment]
Closed
