### ISSUE TITLE
multilanguage lang tag and JFactory::getDocument() conflict

### ISSUE THREAD

**Issue by ced1870** [joomla/joomla-cms#20157]
### Steps to reproduce the issue
In a multilanguage website, create a system plugin with just that :

```
public function __construct(&$subject, $config = array()) {
	$doc = JFactory::getDocument();

	parent::__construct($subject, $config);
}
```

### Expected result
Nothing

### Actual result
the lang html attribute does not update to the current language, still remains on the default language

<html lang="fr-fr" dir="ltr">

instead of (for a french based website) when switching on the english language
<html lang="en-gb" dir="ltr">

### System information (as much as possible)

PHP Version 	7.1.8
Database Version 	5.7.9 
Joomla! 3.8.6

**Comment by infograf768** [comment]
question: can you reproduce this when multiple languages are installed, multilingual is not implemented, but some registered users have chosen another site UI language than the default site one?

**Comment by ced1870** [comment]
if I force the language in the user account, it works

**Comment by infograf768** [comment]
therefore, you mean  Even when the site is NOT a full multilingual site ? (In the sense of using the language filter system plugin and switcher module)

**Comment by Bakual** [comment]
You shouldn't fetch the document in the plugin constructor. That's the issue. With that, you force a document creation prior to when the CMS actually would do it.
That is because the (system) plugin classes actually get loaded very early in the request cycle.

Move that code to the plugin event where you actually use it, and then it will work fine.

**Comment by ced1870** [comment]
yes, tested both with plugin/module activated or not, the html tag is ok when user loggied in with specific language in the profile

**Comment by ghost** [comment]
@ced1870 if this issue is solved, please close, thanks.
