### ISSUE TITLE
Error in module menuwrench after update to Joomla! version 3.8.6

### ISSUE THREAD

**Issue by sancheznahu** [joomla/joomla-cms#20165]
### Steps to reproduce the issue

I'm experiencing a problem after update joomla! to version 3.8.6, the module menuwrench no load submenu items.
The option "Show Sub-menu Items" its ok.

In error.php 

PHP Notice:  Indirect modification of overloaded property Joomla\\CMS\\Menu\\MenuItem::$children has no effect in /var/www/unm/modules/mod_menuwrench/helper.php on line 84,

In line 84 and context:

`
$this->app  = joomla\CMS\factory::getApplication();
$this->db    = joomla\CMS\factory::getDbo();

$this->menu   = $this->app->getMenu();		
$items = $this->menu->getItems(null, null);

foreach ($items as $key => $item)
		{

			$items[$item->id] = $item;

			// If menu item is a category, add all articles as menu items
			if ($showCategoryItems && $this->isContent($item))
			{
				$items[$item->id]->hijo = $this->linkCategoryItems(
					$this->getCategoryItems($item->query['id']),
					$item->query['id'],
					$item->id
				);
			}

			unset($items[$key]);

			if ($item->parent_id != 1)
			{
				$items[$item->parent_id]->hijo[$item->id] = $item; <--Line 84
			}
		}
`

### Expected result

Menu and submenu listed.

### Actual result

Menu listed, the module can´t list submenus

### System information (as much as possible)
Joomla! 3.8.6
OS: Debian
Php: 5.6

**Comment by brianteeman** [comment]
mod_menuwrench is not a core module and you should contact the people who made it or ask for help on the forum https://forum.joomla.org

**Comment by ot2sen** [comment]
You would have to ask Matt @betweenbrain to update their core improvement module. Not default joomla. Look at https://extensions.joomla.org/extensions/extension/structure-a-navigation/menu-systems/menu-wrench/ and support options mentioned there
