### ISSUE TITLE
Joomla Redirects do not support tracking query strings correctly

### ISSUE THREAD

**Issue by MoTecman** [joomla/joomla-cms#20160]
### Steps to reproduce the issue

1. Create a redirect to an existing page from a non-existing page (could be an old page or a short url forwarder), e.g.

 - domain.com/it-industry (OLD or SHORT url)
 - domain.com/my-services-for-the-it-industry (new url)

Have a campaign (probably an old one), which links to the old page which is a tracked link, e.g.;

 - domain.com/it-industry?utm_source=campaign+email&utm_medium=email&utm_campaign=2018+campaign+subject&utm_term=campaign+term&utm_content=1&id=y+7niyn/aayfzheoctnc54dir0eovczldihzu5xxbmrq86r5satmoyelol1v49vsb6djvgkg2bhqryx9qfgz35/zu20r7omv7vnruwvsvawmegfajqujztkylyovuc+ardlto9numorycd/ezb51up4kppothopcnlarbe/khh+rit2xwgsvwrt9lcdvmexamkgxvpv6heom6lgnne4vs5lbhdfzfelliyr0dvimpzzind7d+f9uxzhkqj/qiwob

### Expected result

Go to 

- domain.com/my-services-for-the-it-industry?utm_source=campaign+email&utm_medium=email&utm_campaign=2018+campaign+subject&utm_term=campaign+term&utm_content=1&id=y+7niyn/aayfzheoctnc54dir0eovczldihzu5xxbmrq86r5satmoyelol1v49vsb6djvgkg2bhqryx9qfgz35/zu20r7omv7vnruwvsvawmegfajqujztkylyovuc+ardlto9numorycd/ezb51up4kppothopcnlarbe/khh+rit2xwgsvwrt9lcdvmexamkgxvpv6heom6lgnne4vs5lbhdfzfelliyr0dvimpzzind7d+f9uxzhkqj/qiwob

### Actual result

404 error:

domain.com/it-industry?utm_source=campaign+email&utm_medium=email&utm_campaign=2018+campaign+subject&utm_term=campaign+term&utm_content=1&id=y+7niyn/aayfzheoctnc54dir0eovczldihzu5xxbmrq86r5satmoyelol1v49vsb6djvgkg2bhqryx9qfgz35/zu20r7omv7vnruwvsvawmegfajqujztkylyovuc+ardlto9numorycd/ezb51up4kppothopcnlarbe/khh+rit2xwgsvwrt9lcdvmexamkgxvpv6heom6lgnne4vs5lbhdfzfelliyr0dvimpzzind7d+f9uxzhkqj/qiwob

### System information (as much as possible)

PHP Built On: Linux apache-viupc-10-zn57q 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64

Database Type: mysql
Database Version: 5.5.5-10.0.34-MariaDB-0ubuntu0.16.04.1
Database Collation: latin1_swedish_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version: 7.2.4-1+ubuntu16.04.1+deb.sury.org+1
Web Server: Apache
WebServer to PHP Interface: apache2handler
Joomla! Version: Joomla! 3.8.6 Stable [ Amani ] 13-March-2018 14:00 GMT
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0 

### Additional comments

If you have any questions or need any more information, feel free to let me know.

**Comment by tonypartridge** [comment]
Com redirects does not support wildcard redirects like you are suggesting. It’s a full url including query string.

For this you should look at htaccess rule

**Comment by franz-wohlkoenig** [comment]
closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20160">issues.joomla.org/tracker/joomla-cms/20160</a>.</sub>

**Comment by tonypartridge** [comment]
Although we could probably add a new checkbox / column for the rules parameters col, and apply to query string yes/no and we split the url into two parts match against 1.

**Comment by franz-wohlkoenig** [comment]
@tonypartridge reopen?
