### ISSUE TITLE
User cannot reset password with logout item in menu

### ISSUE THREAD

**Issue by procajlok** [joomla/joomla-cms#20171]
On Joomla **3.8.6** if I have menu item "Logout", user can't reset password. After login, system redirect user to account details (and information about password reset), but password fields is not visible.
Maybe it's the same problem like there https://issues.joomla.org/tracker/joomla-cms/12037 .
If I unpublish item "Logout", user is redirect to reset pass.

### Steps to reproduce the issue
1. Create Login module on homepage.
2. Create item in  mainmenu - Logout.
3. Login to user who must reset password.

### Expected result
After login user see fields to reset pass.

### Actual result
System redirect URL to _index.php/logout/profile?layout=edit_ but user cant reset his password. After unpublish "Logout" menu item, user see expected fields. 

### System information (as much as possible)
J! 3.8.6 and Fabrik 3.8.1.  
**Simple adress is on**

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.
