### ISSUE TITLE
[Improvement Idea] Custom Date Filtering Option for Articles/Users

### ISSUE THREAD

**Issue by adankupapa** [joomla/joomla-cms#20187]
When looking for articles published within specific dates. Like I want to to filter for Articles published between **Date1 and Date2** the current filtering system does not allow this. What it permits is to select a set of pre-defined sorts like ;

1. ID Descending
2. ID Ascending 
3. Title Descending
4. Title Ascending 
5. and a many other great similar sorts. see below
![joomla](https://user-images.githubusercontent.com/38409555/38894816-3f166786-4286-11e8-84ef-3fce506af658.png)

**PROPOSED IMPROVEMENT**
An extra sort/filter option maybe called (CUSTOM DATES) which allows user to select two dates for the system to return articles either published or created within those dates.  The screenshot below is from Google Analytics.(just added for clarity purposes. Ignore the comparison part).

![date](https://user-images.githubusercontent.com/38409555/38895724-b3f6ad5c-4288-11e8-96e1-219376b44c32.png)

**RELEVANCE:**
This will make it possible and easier to search for content published or created within specific dates instead of using the pagination system to page through lists of articles sorted in ascending or descending order only. For websites that have 1000s of articles over many years this can greatly help in when you can just remember the date an article was created. I think this will be an awesome addition to the Joomla 3.9 if not earlier. 

**EXTRA COMMENTS**
This is my first post here. Kindly pardon me if I didn't follow the rules strictly. Will do better next time.

**Comment by brianteeman** [comment]
Thanks for your contirbution. It is not a daft one but I just cant see how it will do anything more than create an even more complicate user interface. You will however probably find the new ability to search within the content (just as you can on the front end) even more useful to you.

**Comment by brianteeman** [comment]
oops pressed the wrong button (again)

**Comment by brianteeman** [comment]
I am going to close this. There doesnt seem to be any interest from someone to create the code etc
