### ISSUE TITLE
joomla update

### ISSUE THREAD

**Issue by abufatima84** [joomla/joomla-cms#20182]
### Steps to reproduce the issue
Hi dear all>
When i want to update my joomla site I have got this message
"_**Warning
JInstaller: :Install: Error SQL Can't DROP 'idx_image'; check that column/key exists
Files Update: SQL error file DB function failed with error number 1091 
Can't DROP 'idx_image'; check that column/key exists
SQL =
ALTER TABLE `#__languages` DROP INDEX `idx_image`;**_
".
and my web site has  crashed to be like this: I have uploaded screenshot from my web site

### Additional comments

![screen shot 2018-04-17 at 06 47 20](https://issues.joomla.org/uploads/1/02564009bbbe9a7b91049ff3d4528a22.png)

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.
