### ISSUE TITLE
500 Layout default_batch not found.

### ISSUE THREAD

**Issue by webman77** [joomla/joomla-cms#20181]
### Steps to reproduce the issue
Click on the user manager and I get the following error. I have tired everything to fix his issue please help.

### Expected result
User manager dosent display

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.

**Comment by brianteeman** [comment]
You havent upgraded successfully. Please use the upload and update feature of the update component
