### ISSUE TITLE
Joomla 3x :: Remove Itemid from Author Linked Contact form URL

### ISSUE THREAD

**Issue by Meavin** [joomla/joomla-cms#20184]
### Steps to reproduce the issue

Step 1: Create contact Category named "Writers" in administrator at back end. i.e., :: yoursite.com/administrator -> components ->contacts -> Categories

Step 2: Enable plugins "Content-Contact" & "User - Contact Creator" and choose category("Writers") to assign contact by default, Also enable "Automatically Publish the Contact" by clicking YES button. i.e., :: yoursite.com/administrator -> Extensions -> Plugins -> "Content-Contact" & "User - Contact Creator"

Step 3: Register your self with a new user name(John123) with different email ID(abc@xyg.com/any sample) from front end and get it activated. Or You can also Create a new joomla user as "Registered" from back-end user management.

Step 4: Go to Components->Contacts ->Contacts, there you can see the contact named "John123" which automatically created and connected to your registered email(abc@xyz.com)

Step 5: Go to administrator "Content->Article" to 'Create' or 'Edit' any one of the Articles(already created) from any desired category, and go to "Publishing" tab and "Created by" column, and link the contact(John123) as the creator of the article by clicking and selecting through user icon(blue in color). And then go to "Options" tab and make "Link Author" -> "YES" and then "SAVE"

Step 6: Go to front end to check the modified article and find the author(John123) linked contact form. 

### Expected result
Author name must be linked either without "Itemid" : 
**http://yoursite.com/component/contact/contact/John123**
OR
**http://yoursite.com/component/contact/contact/2-John123**

OR

This is much better as below If possible;
**http://yoursite.com/writers/John123**
OR
**http://yoursite.com/contacts/John123**

### Actual result

When clicked on author link, the contact from titled "John123" good enough, but the URL shows us as below: "**http://yoursite.com/component/contact/contact/2-John123?Itemid=101**"

Another Way: 
Enable the "URL Routing->to "Modern" towards remove IDs from URLs, and click on the author link(John123) then it shows us an ERROR page of 404

### System information (as much as possible)

Joomla! Version: 3.8.6 Stable
Server: Linux
Database Type: mysql
Database Version: 5.5.56-MariaDB 
PHP Version: 7.1.16
Web Server: Apache
WebServer to PHP Interface: cgi-fcgi

### Additional comments
Please help me by providing the best solution for the same ASAP If possible. 
I love JOOMLA! Thank you in advance!

Regards
Meavin
![step1](https://user-images.githubusercontent.com/17389496/38860242-60ef60bc-424d-11e8-8696-20eb7e1e2f20.jpg)
![step2](https://user-images.githubusercontent.com/17389496/38860249-64aa81f0-424d-11e8-983d-617479b76260.jpg)
![step2_1](https://user-images.githubusercontent.com/17389496/38860256-6817958a-424d-11e8-98c1-4a27f8e05428.jpg)
![step3](https://user-images.githubusercontent.com/17389496/38860259-6b4f6f7a-424d-11e8-88ed-ac6523d503e5.jpg)
![step4](https://user-images.githubusercontent.com/17389496/38860296-842143ca-424d-11e8-86b9-1dcde83d5022.jpg)
![step5_1](https://user-images.githubusercontent.com/17389496/38860303-8861a812-424d-11e8-9e9e-1eda7a840311.jpg)
![step5_2](https://user-images.githubusercontent.com/17389496/38860320-93c6a978-424d-11e8-9c24-6be2a43ba0ab.jpg)
![step6](https://user-images.githubusercontent.com/17389496/38860348-a0a19d74-424d-11e8-945d-3a5dc41faab6.jpg)
![step6_1](https://user-images.githubusercontent.com/17389496/38860362-a97adfc8-424d-11e8-846e-f11ef19d8444.jpg)
![step6_2](https://user-images.githubusercontent.com/17389496/38860377-b331b23a-424d-11e8-939a-67ae64f43778.jpg)
![step6_3](https://user-images.githubusercontent.com/17389496/38860406-c04170f0-424d-11e8-87b7-f8948e443d25.jpg)
![step6_4](https://user-images.githubusercontent.com/17389496/38860417-c6ff13f2-424d-11e8-83ef-cb51e7ed90c5.jpg)

**Comment by brianteeman** [comment]
That is the expected behaviour when there is no menu item set to display a contact form. You can resolve this by creating a menu link for the contact component. For further help please use the foum https://forum.joomla.org

**Comment by Meavin** [comment]
Hello Brian!

It's a great support really much helpful. 

Its good after created a menu named "Authors" linked "List Contacts in a Category". But the other contact in the category are not hidden - Could you please let me know on how to hide the list of contacts from in the category that has been showing in the "Authors" page page, Please help me If there is any possible method to hide the contacts from authors page. 

The ''authors'' page has still showing all the contact in the category as shown in below images;

Awaiting reply. Thanks a lot!

Regards,
Meavin
![screenshot_1](https://user-images.githubusercontent.com/17389496/38986901-87863134-43eb-11e8-9f29-a6d45314d91f.png)
![screenshot_2](https://user-images.githubusercontent.com/17389496/38986908-8bcc7e6a-43eb-11e8-8100-3b74e33363e0.png)

**Comment by ghost** [comment]
@Meavin Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding, thanks.
