### ISSUE TITLE
[4.0] Alert autodismiss not working

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#20186]
### Steps to reproduce the issue

Add the following JS snippet somewhere:

```
Joomla.renderMessages({'error': ['Test message']}, '#system-message-container', true, 3000);
```

### Expected result

This should render an error alert and auto dismiss it after 3 seconds

### Actual result

The alerts isn't dismissed

@dgrammatiko I suppose the CE vendor package needs updating cause there's no reference to  `autodismiss` in the `alert.js`

**Comment by dgrammatiko** [comment]
Autodismiss will be removed as requested from the a11y team

**Comment by C-Lodder** [comment]
Just in core, or will the whole `removeMessages` function be removed?

**Comment by dgrammatiko** [comment]
also from the core.js
