### ISSUE TITLE
[4.0] invalid markup in modal footer

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#20188]
Sorry I tried to see where this bug is coming from but couldnt find it but it is everywhere there is a modal. No idea if this is a layout, custom element or js issue

Go to com_menus and new menu item
View the source and you will see several instances like this

<img width="553" alt="chrome_2018-04-17_23-52-20" src="https://user-images.githubusercontent.com/1296369/38902924-838d3a3e-429a-11e8-8449-da7f74d84022.png">

As you can see there appear to be several extra divs especially the one at the end of the line

**Comment by Quy** [comment]
Due to the loss of formatting (tabs) in the PHP output, the closing `</div>` doesn't align with the starting `<div>` to make it appear wrong, when it is actually fine. Match the `<div>`s and you will see that this is the case.

**Comment by Quy** [comment]
The highlighted `</div>` belongs to `<div class="modal-footer">`. I pasted the page source code into Dreamweaver and no mismatched tags were found.
