### ISSUE TITLE
Joomla the DSGVO and the contact form

### ISSUE THREAD

**Issue by The-Web-Designer** [joomla/joomla-cms#20194]
I I had hoped with the new version that it would be possible to address the problem that a "data protection notice" must be included under every contact form, according to the new Europe-wide data protection basic regulation (DSGVO), which will become active as of the 26th mail.

Shortly to the explanation, with this new data security regulation must stand under each form for contact a sentence, after the slogan: I agreed to the data security explanation, with a left on this data security explanation.

Unfortunately Joomla does not offer this possibility in the standard contact form. Unless I do it via HTML override but that's not the point, it should work out of the box...

Is there already a solution or publication date for the problem?

Thank you!

Here's an extract from the law:
Contact form - not without data protection notice 

Legally, the users of the contact form require the consent of the users for the processing of personal data.  The processing of personal data such as name, address, e-mail address and telephone number is subject to permission: Only if the data subject has consciously and clearly consented to the processing of his/her personal data in accordance with § 13 paragraph 2 TMG (Telemedia Act), may they be processed.  Therefore, a corresponding data protection notice in the context of the contact form is indispensable.  The basis for this are §§ 4a, 28 paragraph 3a BDSG, §§ 13 paragraphs 2 and 3 TMG and § 94 TKG (Telecommunications Act).  The user must be informed in an understandable form about the type, purpose and scope of the collection and use of personal data.  Only in this way does he know what process he is consenting to.  Likewise, he will be informed about the right of revocation for the consent given, which he can exercise at any time. 

**In German:**

Ich hatte gehofft mit der neuen Version, nimmt man sich dem Problem an, das unter jedem Kontaktformular, laut der neuen Europaweiten Datenschutz Grundverordnung (DSGVO), welche ab dem 26. Mail aktiv wird, eine "Datenschutzhinweis" erfolgen muss.

Kurz zur Erklärung, mit dieser neuen Datenschutzverordnung muss unter jedem Kontaktformular ein Satz, nach dem Motto: "Ich stimmte der Datenschutzerklärung zu" stehen, mit einem Link auf diese Datenschutzerklärung.

Leider bietet Joomla im Standardkontaktformular dazu keine Möglichkeit. Außer ich mache es per HTML Override aber das ist ja nicht der sinn, es sollte out of the Box klappen..

Gibt es für das Problem bereits einen Lösungsansatz oder einen Veröffentlichungstermin?

Danke!

Hier der Auszug aus dem Gesetz:
Kontaktformular – nicht ohne Datenschutzhinweis

Rechtlich gesehen benötigen die Verwender des Kontaktformulars die Einwilligung der User zur Verarbeitung der personenbezogenen Daten. Denn die Verarbeitung personenbezogener Daten wie Name, Adresse, E-Mail-Adresse und Telefonnummer steht unter einem Erlaubnisvorbehalt: Nur wenn der Betroffene nach § 13 Absatz 2 TMG (Telemediengesetz) bewusst und eindeutig in die Verarbeitung seiner persönlichen Daten eingewilligt hat, dürfen diese verarbeitet werden. Deshalb ist ein entsprechender Datenschutzhinweis im Kontext des Kontaktformulars unabdingbar. Grundlage dafür sind §§ 4a, 28 Absatz 3a BDSG, §§ 13 Absatz 2 und 3 TMG sowie § 94 TKG (Telekommunikationsgesetz). Der User ist dabei in verständlicher Form über Art, Zweck und Umfang der Erhebung und Nutzung der personenbezogenen Daten zu informieren. Nur so weiß er, in welchen Vorgang er einwilligt. Gleichermaßen wird er über das Widerrufsrecht für die erteilte Einwilligung aufgeklärt, welches er jederzeit ausüben kann.

[https://www.datenschutzexperte.de/blog/datenschutz-im-internet/kontaktformular-und-datenschutz-das-sollten-sie-auf-ihrer-webseite-beachten/](url)

**Comment by brianteeman** [comment]
See https://github.com/joomla/joomla-cms/pull/20051

**Comment by jurihahn** [comment]
@brianteeman your plugin do this checkbox on contact form if user is only guest?

**Comment by brianteeman** [comment]
No it doesnt do any checkbox on the contact form. The core contact form does not store any data so it is not required to display a privacy checkbox. In addition it can reasonably be assumed that if someone wants to email you then it is legitimate for you to collect their email address so that you can reply. IANAL

**Comment by jurihahn** [comment]
I hope that I can find out from the expert of our company...
