### ISSUE TITLE
Category link with ?layout= when active Modern route

### ISSUE THREAD

**Issue by Septdir** [joomla/joomla-cms#20199]
### Steps to reproduce the issue
1. Go to Articles: Options and select  Modern as URL Routing
2. If need create Category and Article
3. Create Menu Item Category blog (not home)
4. Go to page and see category link in article blog

For example category alias will be `block`

### Expected result
`site.com/blog`

### Actual result
`site.com/blog?layout=`

### System information (as much as possible)
PHP 7.2.2 / 7.1.11
Joomla 3.8.7

### Additional comments
In truth, I do not know in which update it appeared. This was noticed by one of the clients.  
I understand that this is a Modern Route however it's still a bug  
I watched the problem on 3 websites

**Comment by brianteeman** [comment]
by one of or all of?

I cant replicate it myself on a clean install

**Comment by ghost** [comment]
Can't confirm on live 3.8.7-Site but its on php 7.0.4.

**Comment by mbabker** [comment]
If any core change caused this one it'd be https://github.com/joomla/joomla-cms/pull/19681 but even that wouldn't allow for an empty layout query string variable.

**Comment by Septdir** [comment]
@brianteeman in clean site all fine,  However, this site was created yesterday
https://dev.joomlazen.com/en/

In single language sites same problem

**Comment by Septdir** [comment]
I try to reproduce the exact path that leads to the problem or find & fix the reason

**Comment by Septdir** [comment]
@mbabker Yes #19681 is the reason when i comments these lines the link became normal

in my site where override com_content link was `/blog/web.html?layout=septdircategory`

when comment
```
//			$jinput = JFactory::getApplication()->input;
//			$layout = $jinput->get('layout');
//
//			if ($layout !== '')
//			{
//				$link .= '&layout=' . $layout;
//			}
```
link was has become `/blog/web.html`

In sites where com_content link become norlmal without ?layout

**Comment by ggppdk** [comment]
```php
$layout = $jinput->get('layout');
```

So if layout is null (not set)
you will get the layout variable appended as empty, right ?  because `null !== ''`

Maybe fix with
```php
$layout = $jinput->get('layout', '', 'CMD');
```

or
```php
if (!empty($layout))
```

**Comment by Septdir** [comment]
@ggppdk It's fixed if layout empty.
but if layout not empty for example my site where create override the problem remains  
Because with such filtering the wrong value comes. I have already made our decision now to do PR

**Comment by Septdir** [comment]
@alikon please test #20200
