### ISSUE TITLE
isInternal make JRoute unusable for login

### ISSUE THREAD

**Issue by simongareste** [joomla/joomla-cms#20193]
### Steps to reproduce the issue

Let's say that 155 is the Menu Id where I want to be redirected to after login
`JRoute::_("index.php?ItemId=155")`

### Expected result
Be redirected to the url equivalent to the Menu 155

### Actual result
I'm always redirected to 
`index.php?option=com_users&view=profile`

### System information (as much as possible)
On a Joomla 3.8.5

### Additional comments

The issue I have with this is that JRoute::_("index.php?ItemId=155") will return /index.php?option=com_whatever&anything=really, with a leading '/'. Because of this, it will not be considered as an internal URL, and the default (option=com_users&view=profile) will be used instead.

So I should not use JRoute::_($url) anymore, at least not for login, or is this somewhat of a bug?

**Comment by ghost** [comment]
can you please update to latest Release [3.8.6](https://github.com/joomla/joomla-cms/releases/tag/3.8.6) (today 3.8.7 is announced).

**Comment by SharkyKZ** [comment]
You should not wrap the link with JRoute in Login Redirect field, if that's what you're asking. In your case you should enter only `index.php?Itemid=155` (also note capitalization on Itemid).

**Comment by simongareste** [comment]
That's what I'm asking, thanks. It seems that the SocialConnect module (https://www.joomlaworks.net/extensions/commercial/socialconnect) is doing this, though I couldn't figure out if it's now obsolete, or if I'm out of date of anything.

**Comment by Quy** [comment]
@simongareste Please close if this has been answered. Thanks.
