### ISSUE TITLE
Bootstrap (JS) not included in some pages

### ISSUE THREAD

**Issue by magoncalves** [joomla/joomla-cms#20198]
### Steps to reproduce the issue
On some pages, the bootstrap.js file (specifically the "<script src="/media/jui/js/bootstrap.min.js?[UUID]" type="text/javascript"></script>" tag) is not included, resulting on no dynamic behavior on bootstrap components (Accordions, in my case).

### Expected result
The bootstrap.js being normally included.

### Actual result
The dynamic behavior from bootstrap.js components (like accordions) is not present

### System information (as much as possible)
Debian 8.10 (Jessie)
Apache 2.4.10
PHP 5.6.33-0+deb8u1
Mysql 5.5.59
Joomla! version 3.8.7

### Additional comments
I've needed to downgrade to 3.8.6 because that dynamic behavior is essential in my site, as much information is collapsed on those components.
That is why I don't put any link for you to check.

**Comment by brianteeman** [comment]
without knowing what "some pages" are or even what type of page they are it is impossible to help

**Comment by mbabker** [comment]
Joomla core does not arbitrarily load any media, if you require Bootstrap to be loaded you need to ensure it is loaded (a call to `JHtml::_('bootstrap.framework');` will take care of this for you) and that you do not rely on other parts of the system to load media for you.

Closing, not a core bug.

**Comment by mbabker** [comment]
Just to close the loop here, the only change in 3.8.7 where media stopped being loaded was https://github.com/joomla/joomla-cms/pull/19787 because the breadcrumb module doesn't use tooltips therefore there is no point in forcing the load of jQuery and Bootstrap.  This is a huge if, but if absolutely nothing else on your site's pages was actually causing Bootstrap to get loaded and that was the only spot doing it, that change would have impacted you.

**Comment by magoncalves** [comment]
That's it.
#19787 definitely impacted me.

I was using Bootstrap components and they just worked. I've never bothered about including it (it just worked and those components are all around!).
What's the best way that I can load `JHtml::_('bootstrap.framework');` so that future updates won't override it? (and in a way that it will be available in all pages)

**Comment by mbabker** [comment]
Add that line to your template.
