### ISSUE TITLE
Name attribute is deprecated, in the future fetch the pathway through the respective application

### ISSUE THREAD

**Issue by simongareste** [joomla/joomla-cms#20203]
On Joomla 3.8.7, CMSApplication function getPathway($name=null, $options = array()) logs a warning regarding $name which is deprecated.

So CMSApplication->getPathway(null,[]) will work fine, but CMSApplication->getPathway('site',[]) will not.

However, SiteApplication extends CMSApplication, and its getPathway function is
```
	public function getPathway($name = 'site', $options = array())
	{
		return parent::getPathway($name, $options);
	}
```

So this will always call CMSApplication with a $name, which will in turn print the warning.
So I'll alway get a warning when I write:

```
$app = JFactory::getApplication();
$pathway = $app->getPathway();
```

What should I do to avoid this?

Simon

**Comment by NickSdot** [comment]
@simongareste 
Please test: https://github.com/joomla/joomla-cms/pull/20206

**Comment by simongareste** [comment]
Works for me. Thanks!

Simon

**Comment by ghost** [comment]
@simongareste please mark your Test as successfully:

- open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/20206)
- Login with your github-Account
- Click on blue "Test this"-Button above Authors-Picture
- mark your Test as successfully
- hit "submit test result"
