### ISSUE TITLE
[3.8] FileLayout uses own deprecated method

### ISSUE THREAD

**Issue by NickSdot** [joomla/joomla-cms#20207]
Constructor in `Joomla\CMS\Layout\FileLayout` uses `setComponent()` and `setClient()` which both using the deprecated `$this->refreshIncludePaths()`. 

This is 'spamming' the /log/deprecated.php for no reason. 

Both methods should use the new `clearIncludePaths()` which is already used by the old `$this->refreshIncludePaths()`.

### Steps to reproduce the issue

Use `LayoutHelper::render() `to render a layout.

### Expected result
Use new `clearIncludePaths()` and get no deprecated messages in log.

### Actual result
Use old `refreshIncludePaths()` which results in deprecated messages in log.

### System information (as much as possible)
J3.8.7

### Additional comments
I'll make a Pull Request in a bit.

**Comment by ghost** [comment]
closed as having Pull Request #20208.
