### ISSUE TITLE
Order by with com_search ?

### ISSUE THREAD

**Issue by ZerooCool** [joomla/joomla-cms#20215]
### Steps to reproduce the issue
https://www.visionduweb.eu/outils/rechercher

### Expected result

Rechercher uniquement dans :

Articles
Catégories
Contacts
Évènements
Fils d'actualité
Forum
Liens web
Téléchargements
Wiki

### Actual result

Rechercher uniquement dans :

Catégories
Contacts
Articles
Fils d'actualité
Liens web
Forum
Évènements
Téléchargements
Wiki

### System information (as much as possible)

Joomla search

### Additional comments

How to order by character A B C D .....

**Comment by brianteeman** [comment]
In the plugin manager simply change the order of the search plugins

for further help please use the forum
https://forum.joomla.org
https://forum.joomla.fr

**Comment by ZerooCool** [comment]
Ok
Extensions
Plug-ins
Choice a type
Then, order as I want
