### ISSUE TITLE
[com_fields] List and check boxes "value" vs "rawvalue" confusion

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#20216]
### Steps to reproduce the issue
Create a new custom LIST field for articles. (Same pb with Checkbox, did not test all)
For example:
<img width="1066" alt="screen shot 2018-04-23 at 07 36 42" src="https://user-images.githubusercontent.com/869724/39108569-1dfd02c0-46c9-11e8-83de-6f8072823243.png">

Then edit an article and choose a value. For example "Center"
<img width="463" alt="screen shot 2018-04-23 at 07 51 19" src="https://user-images.githubusercontent.com/869724/39108983-2631190c-46cb-11e8-90db-2ac774907525.png">

Then, following the instructions in https://docs.joomla.org/J3.x:Adding_custom_fields/Overrides
edit `/components/com_content/views/article/tmpl/default.php`

Add after $info = etc.
```
foreach($this->item->jcfields as $jcfield)
{
    $this->item->jcFields[$jcfield->name] = $jcfield;
}
```
and thereafter
`var_dump($this->item->jcFields['article_class']->value);` Where `article_class` is the name of my field.

### Expected result
`center`

### Actual result
`Center`

### What has happened?
In fact, for some of the custom fields, $value = $rawvalue. It is the case for the custom Text field.
But it is not the case for List, Checkboxes, and maybe others I did not check.

For these, the real value is `$rawvalue`.
The code to use is therefore
```
$this->item->jcFields['article_class']->rawvalue
```

Obviously the docs should be updated to reflect this confusion.
I propose to also add a spacer label displaying when editing these fields.
Any other solution in code would not be B/C

What do you think?

@laoneo

**Comment by laoneo** [comment]
Docs do need to be updated for sure.

**Comment by infograf768** [comment]
Modified docs.

**Comment by infograf768** [comment]
Changed to Known Issue. Does not mean it is right, but, at this stage, it can't be modified for B/C reasons.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20216">issues.joomla.org/tracker/joomla-cms/20216</a>.</sub>

**Comment by audetcameron** [comment]
Each Article = Multiple Custom Fields and using List Type/Select fields.

We were using 
```
  echo $item->jcFields['work-project-types']->value
```
However since a recent update this is now blank.
My friend Justin found that we needed to go into the back end and enable the Show On  (BOTH)  option.  In order to get the value to display again.
![image](https://user-images.githubusercontent.com/6738453/58354838-896adf00-7e40-11e9-8ed9-3be8b767e54a.png)

**Comment by ReLater** [comment]
@audetcameron
 
Maybe your find is a new issue. It was reported on a German forum for Joomla 3.9.5 like  this:

Before update the `->value` was the `Text` of the selected list `OPTION`.
Before update the `->rawvalue` was the `Value` of the selected list `OPTION`.

After update the `->value` is empty.

I've tested it and couldn't confirm the issue but my setting for `Show on` was `Both` (= Default).
