### ISSUE TITLE
[CodeMirror] Autofocus Bug and suggestions

### ISSUE THREAD

**Issue by Septdir** [joomla/joomla-cms#20228]
## Bug
 And once again it concerns two or more editors.

If there are two or more editors on the page, then focus all at once.

### Actual result
3 editor focused together

### Expected result
Only first editor focused

You can use [this component](https://github.com/JoomlaZen/com_jzpages) for testing

## Sentence.
In my opinion, `autofocus` option should be ` No` by default

I'll explain why:
1.  It is not particularly correct that when I open the itemform immediately focus on the content
2.  If for some reason the editor does not fall into the field of view, then the page will be scrolled down to it.

**Comment by dgrammatiko** [comment]
> If there are two or more editors on the page, then focus all at once

Well I hardly see how multiple editors can get focus at the same time...

**Comment by brianteeman** [comment]
magic

**Comment by Septdir** [comment]
@dgrammatiko Like that
![default](https://user-images.githubusercontent.com/18382023/39212783-6035a9c6-4818-11e8-8ace-6fe035793b68.png)

If you need this component. I'm doing it now, but you can test it. 
https://github.com/JoomlaZen/com_jzpages  
There are 3 editors in it. 2 of which codemirror if the plugin is enabled  

Immediately say if you turn off autofocus then there is no problem

The case where two or more editors on one page is of course rare, but the bug is a bug

**Comment by dgrammatiko** [comment]
Sorry but if you get both editors focused at the same time something is utterly wrong! Focus (and blur) are more than the visual indication eg, focused element is the one that tab key will leave to go to the next one. So even if you somehow hacked the visual part you totally destroyed the keyboard navigation (and probably a few more things)

**Comment by Septdir** [comment]
@dgrammatiko 
>So even if you somehow hacked the visual part

I did not hacked anything. I just output 3 editors on one tab in my component(I need this). Output using standard code using xml and geInput function

Maybe here?
https://github.com/JoomlaZen/com_jzpages/blob/master/admin/views/page/tmpl/edit.php

or Maybe here?
https://github.com/JoomlaZen/com_jzpages/blob/master/admin/models/forms/page.xml

And if using this plugin does not work correctly, then this is a bug.

Or to output two editors in one tab Joomla breaking something? Personally, I have never read about this.

Moreover, I have never done this without the use of Joomla and there were no problems.

If the system allows you to output 2 editors on one page, then they should work correctly. Or not work at all.

**Comment by dgrammatiko** [comment]
> If the system allows you to output 2 editors on one page, then they should work correctly.

Define what is correct, because focusing simultaneously 2 elements in a page breaks the very fundamentals of the web: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus

**Comment by Septdir** [comment]
@dgrammatiko Forgive or excuse probably I incorrectly expressed.

At me now the focus is established in 3 editions at once. And this is a bug.

It is necessary that in one.

## Actual result
3 editor focused together

## Expected result
Only first editor focused

**Comment by dgrammatiko** [comment]
Ok now we're in the same page, that's a bug

**Comment by Septdir** [comment]
@dgrammatiko Thank you. Sorry, I got a little excited. Just recently, joomla is very upsetting me in terms of  bugs

**Comment by Quy** [comment]
@okonomiyaki3000 Your expertise please.

**Comment by okonomiyaki3000** [comment]
Cool. So we should decide if we want to autofocus on the first editor or not at all. I'm slightly leaning toward not at all but I don't have a strong opinion on it.

**Comment by brianteeman** [comment]
from an a11y perspective autofocus _can_ be bad

http://www.brucelawson.co.uk/2009/the-accessibility-of-html-5-autofocus/
https://dequeuniversity.com/assets/html/jquery-summit/html5/slides/form-attributes.html

**Comment by Septdir** [comment]
For the component from the example, it's best to be `not at all` So I support this position.

However, it turns out that in this case the plugin settings will be ignored.

By the way, maybe add autofocus to the xml attributes? Then the developer can adjust the focus himself and install it on the correct editor, or completely disable autofocus it in form.

This can be done in override. In my turn out to be very flexible

**Comment by grig0ry** [comment]
I agree with @Septdir. Adding autofocus to the xml attributes will be an excellent solution.

**Comment by ghost** [comment]
closed as having Pull Request #20270.
