### ISSUE TITLE
Quick Package get Script

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#20223]
Hello....

Myself and Geraint were wondering on the communities thoughts for a quick package fetch script? Which simply downloads the latest Joomla! package, extracts it and proceeds to the installation screen? 

We are seeing more and more users with slower connections and the current 13mb package does add time to the whole setup process, this way you would upload a script which takes seconds, click a button and let the server handle the traffic.

**Comment by mbabker** [comment]
Write it if you please?  Someone did something similar in the past, and core doesn't have to support every possible tool people can think of.

**Comment by tonypartridge** [comment]
We are happy to write it, we have one partially done. But there is no point in doing it completely for the core if the community is not interested.

To me it makes sense when you have slow internet connections in parts of the world where more of our newer users are coming from?

In my mind I see it being on the download page as an option of download quick start script. Or download full package.

**Comment by Bakual** [comment]
Just wondering: Is 13MB really an issue anywhere nowadays? It's not really a big file in todays terms.

**Comment by mbabker** [comment]
> In my mind I see it being on the download page as an option of download quick start script. Or download full package.

And that means it has to be core supported.  I know a lot of people use my manual update script, it's not advertised as a core tool (actually aside from my forum signature it's not advertised at all), but the people that know about it or run updates in a non-core supported way appreciate having something out there to un-break their breaks.

There's nothing wrong with having that kind of script.  The second it is published anywhere on `joomla.org` that means we have to have the project resources to maintain it.  We already have enough issues with having too many things and not enough resources to maintain them all (just look at my workload as an example, sure a lot of it is low maintenance but there's still a lot of stuff that should be spread over more people).

**Comment by tonypartridge** [comment]
Yep, as an example I am in Wales at the moment and at a peak it’s 444kbp upload. This means 13mb file takes time. Same with other places in the world and limited connections.

A script would save bandwidth in general as it would then be a singular download from Joomla! Opposed to download and then upload.

**Comment by mbabker** [comment]
And you don't have tools to work with the smaller tar files?  (ZIP is used by default because it's more generically available, at the expense of bandwidth and disk space)

**Comment by tonypartridge** [comment]
Of course, I can even do it to a server. But it just raised a valid point that actually it can take quite a bit of time to setup Joomla! No everyone is a harden developer. Or wants to start compressing and adjusting a zip file.
I'm just trying to make Joomla! Easier to use from the get go, a simple script which you click 'Start Installing Joomla' and it runs a few basic checks and then downloads, extracts and redirects seems such a logical step for Joomla! to take.

**Comment by ciar4n** [comment]
> Yep, as an example I am in Wales at the moment and at a peak it’s 444kbp upload. This means 13mb file takes time. Same with other places in the world and limited connections.

I'm on the west of Ireland and like that, 444kbp upload would be a good day. Days I'd be quicker posting it.

**Comment by mbabker** [comment]
I don't see the issue with such a script, I just don't see why it has to be released under the Joomla branding and supported by us (which sooner or later as it relates to releases or .org architecture means me, just being honest here based on historical trend).

**Comment by brianteeman** [comment]
seems a good idea to me - but i have experienced really weird issues with scripts like this on many hosts so i doubt it will be as easy as it should be

**Comment by ot2sen** [comment]
Saw one of these script just weeks ago but can´t locate it right now... 
Usually the reason for having made them is the same as in this thread.
Only had an older link to https://github.com/bestproject/getjoomla.php which seems to target github releases.

**Comment by dgrammatiko** [comment]
I would like to see us moving towards a more sensible (like this issue indicates) way of doing things. PWAs are not a trend of 2018, it's the right philosophy for websites, assume the worst speed (eg 2G) and start enhancing if the connection is better. Joomla (out of the box) is nowhere near fulfilling the actual needs of a progressive site and this is going to backfire in the very near future. Ideas like:

> It's not really a big file in todays terms

especially for css, javascript and images are really catastrophic for performance, and guess what:

> Performance is User experience!

**Comment by Bakual** [comment]
@dgrammatiko We're speaking about the CMS installation package file here. I doubt many do the installation  (including putting the installer to the server) of a completely new CMS from their phone. I don't think PWA is the right approach here :smile: 

Of course, once installed (or even the installation app steps itself), it's a completely different topic.

**Comment by laoneo** [comment]
Do not have most hosters such scripts anyway? At least mine has a button to install a Joomla right in their admin UI.

**Comment by brianteeman** [comment]
it would be better to spend th time making the installer for joomla 4 actually usable. currently its very broken

**Comment by brianteeman** [comment]
@laoneo thats only suitable for shared hosts :)

**Comment by brianteeman** [comment]
This is a very old request for a new feature in Joomla 3. As there has been no interest in providing any code to satisfy this and we are not accepting any new features in Joomla 3 I recommend that it is closed.

**Comment by alikon** [comment]
Closed as stated above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20223">issues.joomla.org/tracker/joomla-cms/20223</a>.</sub>
