### ISSUE TITLE
error

### ISSUE THREAD

**Issue by maksim10121986** [joomla/joomla-cms#20226]
A have this error in my log file of my site PHP Fatal error:  Call to undefined method Joomla\\CMS\\Document\\FeedDocument::isHtml5() in /home/aleksa/public_html/stat.uz/libraries/src/Document/Renderer/Html/HeadRenderer.php on line 77 Please help!!!

У меня в логах ошибок сайта появляется эта ошибка пожалуйста помогите разобраться вот эта ошибка в чем причина PHP Fatal error:  Call to undefined method Joomla\\CMS\\Document\\FeedDocument::isHtml5() in /home/aleksa/public_html/stat.uz/libraries/src/Document/Renderer/Html/HeadRenderer.php on line 77 Please help!!!

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.
