### ISSUE TITLE
Postgresql can't use JTable with table not in public schema

### ISSUE THREAD

**Issue by pviolette-fr** [joomla/joomla-cms#20234]
## Steps to reproduce the issue

Create a Table object on a table in a schema other than public

## Expected result

The Table is correctly constructed

## Actual result

Error : No columns found for table_name table

### Causes

On construction, the table call its getFields() method, which will retrieve the columns information from the postgresql driver by the method getTableColumns($table, $typeOnly = true). The request in this method is hardcoded to only look at the public schema ( joomla-cms/libraries/joomla/database/driver/postgresql.php - line 388).

Looking more closely it seems like there is no support for postgresql schema. Is there any plan to support this functionality in the future ?

**Comment by alikon** [comment]
well, 
if we can find some more  people that's caring about polyglot persistence,
why not
i'll write a pr for fix the

> Create a Table object on a table in a schema other than public

issue

**Comment by alikon** [comment]
please test #24999

**Comment by alikon** [comment]
closed as we have a pr to test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20234">issues.joomla.org/tracker/joomla-cms/20234</a>.</sub>
