### ISSUE TITLE
Filter field in list layout problem.

### ISSUE THREAD

**Issue by Jaironlanda** [joomla/joomla-cms#20235]
### Steps to reproduce the issue
1) Setup contacts using list layout. 
2) Register user in contact.
3) 3 users in list
    i) ABC
   ii) ABCD
   iii) ABCDE
4) enter not exist name in contact filter field. Example: ABCDEF 

### Expected result
Show notification and can go back to list contacts.  

### Actual result
Show simple notification : **No contacts to show** and can't go back to normal list.

### System information (as much as possible)
Joomla version 3.8.7
Ubuntu 16.04.4 LTS 64-bit
Ampps Server

### Additional comments
I try go homepage manually and navigate to contact list back. But contact list still not show up.

I Need wait 2 or 5 minutes to get back the contact list.

**Comment by mbabker** [comment]
Fixed by https://github.com/joomla/joomla-cms/pull/20126 to be included in next release.
