### ISSUE TITLE
[New feature][com_content] Add `Preview` button to admin toolbar

### ISSUE THREAD

**Issue by Septdir** [joomla/joomla-cms#20240]
Once I was asked to add the button `Go to item` into one of my components.

The function of the button is simple when you click a new window to open an article page on the site.

This button helps you to save time. Because to look at the article on the site you do not have to first go to the site and then look for the right page. Do not forget to log in if the article has access.

Here is a screenshot of how it might look like
![s1](https://user-images.githubusercontent.com/18382023/39299122-ae2057f6-4950-11e8-8e20-ab91bb2bfa09.png)

Here is an example of implementation.
https://github.com/JoomlaZen/com_jzpages/blob/master/admin/views/page/view.html.php#L143-L149

If you abandon `Route`, then the code will be several times shorter. Either the implementation of the button can be quite different. In truth, I did not think how to do it better.

In the parish, I can make a plugin and easily add a button to com_content, but if this function is interesting it can be added to core

**Comment by dgrammatiko** [comment]
@Septdir this is already implemented in J4, you can give it a try

**Comment by Septdir** [comment]
@dgrammatiko Thank you. Did not notice if honestly. But still there is a difference.

In the version I proposed. `preview` opens in a new tab and not in the modal window. In the modal window, it's not very convenient to use the browser Console\Developer Tools

I can rename or create a new issue

**Comment by dgrammatiko** [comment]
You can change the behaviour in J4. I don't think that anyone will be against having the preview in a new tab 😉

**Comment by Septdir** [comment]
I even know that you can still add.

Maybe add parameter for JToolbarHelper :: Link to open links in a new window


How to be this issue? Close, rename or leave. Maybe later add preview to joomla 3

**Comment by dgrammatiko** [comment]
Let's patch it first in J4 and then we can back port it in J3...

**Comment by Septdir** [comment]
@dgrammatiko Good. Then probably create a new issue.

**Comment by C-Lodder** [comment]
Code is here for you: https://github.com/joomla/joomla-cms/pull/12367

**Comment by Septdir** [comment]
@C-Lodder Thank you, one at the moment, I'm thinking of adding a setting to com_content J4 `Open preview in new tab`
#20241

**Comment by PhilETaylor** [comment]
Please see #20417 and #20418

**Comment by Septdir** [comment]
It would be better to do this in J4 #20241
