### ISSUE TITLE
3.7.x 3.8.x  Not friending URL after setting URL routing to Modern and Remove IDs from URL to Yes

### ISSUE THREAD

**Issue by eltonpang** [joomla/joomla-cms#20242]
### Steps to reproduce the issue
Fresh installation of 3.7.x or 3.8.x and install 2 additional language along with it. in this example, Simplified and Traditional Chinese.

SEO Settings:SEF URL Yes
Use URL rewriting Yes
Unicode Aliases Yes

Article Options >> Integration
URL routing Modern
Remove IDs from URL Yes

Sample of issues head to http://templatesreview.cloudaccess.host
click on any of the 2 articles in the homepage, you will always see **?view=article&id=4:** follow by article title then end with **&catid=2**
Note: the ID changes depending on the article and category of the article display

### Expected result
http://templatesreview.cloudaccess.host/english-second-page-for-testing

### Actual result
http://templatesreview.cloudaccess.host/?view=article&id=4:english-second-page-for-testing&catid=2

### System information (as much as possible)
Setting	Value
 
PHP Built On	Linux lamp115.cloudaccess.net 2.6.32-673.8.1.lve1.4.3.1.el6.x86_64 #1 SMP Thu May 5 16:06:47 EDT 2016 x86_64
Database Type	mysql
Database Version	5.5.56-cll-lve
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.1.15
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.8.7 Stable [ Amani ] 18-April-2018 14:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

### Additional comments
existing 4.0 Alpha 2 inherit issue from 3.8.x as well as report by Jean-Marie Simonet
https://issues.joomla.org/tracker/joomla-cms/19997

I am creating this since existing 3.8.x need to be fix as well or it will render the remove ID from URL useless if it remains.

**Comment by mbabker** [comment]
Exactly as I said at https://github.com/joomla/joomla-cms/issues/19997#issuecomment-384703140

You cannot ONLY have a featured content menu item and have SEF URLs be generated as you're expecting (as in you can't have a single article view be a "child" of the featured content page unless you set up a single article menu item as a child of the featured content menu item).  You need to configure your menu tree correctly to get the routes you want.

**Comment by brianteeman** [comment]
Closed as the expected behaviour - if you need more help then please use the forum

**Comment by eltonpang** [comment]
thanks for the elaboration.  unfortunately, there are lack of educational information on expected behavior of how routers should works when remove ID are set to yes.  Perhaps that why it was raised as an issued.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20242">issues.joomla.org/tracker/joomla-cms/20242</a>.</sub>
