### ISSUE TITLE
JFile::upload does not return any status message on error

### ISSUE THREAD

**Issue by olleharstedt** [joomla/joomla-cms#20246]
### Steps to reproduce the issue

Use `JFile::upload` in a way that causes an error.

### Expected result

Being able to check for errors after use.

### Actual result

Errors are only logged in log file, no exceptions or error return value.

### System information (as much as possible)

N/A

### Additional comments

I propose a static class variable called `$upload_error`, which is set to relevant error message (or object) if `upload` returns `false`.

Better would probably be throwing an exception, or returning a result array like `[boolean $result, string $errorMessage]`, but that would break compatibility.

Link to method: https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/filesystem/file.php#L521

**Comment by ghost** [comment]
Can someone please answer on this issue as its open since 10+ Days having Staus "New"?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20246">issues.joomla.org/tracker/joomla-cms/20246</a>.</sub>

**Comment by ghost** [comment]
Thanks @PhilETaylor for Answer.

So this Issue stay open as Feature Request.

**Comment by olleharstedt** [comment]
@PhilETaylor Haha, yes, I know it does that. That's the problem!! I can do a PR if you want to.

**Comment by Quy** [comment]
@olleharstedt Please submit a PR so it has a chance to be included in the core.

**Comment by olleharstedt** [comment]
Added PR here: https://github.com/joomla/joomla-cms/pull/20438

**Comment by ghost** [comment]
closed as having Pull Request #20438
