### ISSUE TITLE
[4.0][com_content] Open preview in new tab

### ISSUE THREAD

**Issue by Septdir** [joomla/joomla-cms#20241]
Continuing #20240

To open the preview in a new window, I have several suggestions
* Add to `JToolbarHelper :: Link()` param `$new` ( bool) If true open link in new window
* Add to` JToolbarHelper :: Preview()` param `$popup` (bool) If false open preview in new window (You can just use the JToolbarHelper :: Link()` with `$new=true`)

Whether to open preview in com_content in a new window or not

Both of these suggestions will be useful for developers

**Comment by PhilETaylor** [comment]
This already works for links:

`$toolbar->link('myJoomla.com ','http://myJoomla.com', true)->attributes(['target'=>"_blank"]);`

I'm implementing this for preview now, in #

Modals
`$toolbar->preview('http://myJoomla.com ','myJoomla.com', false);`
or
`$toolbar->preview('http://myJoomla.com ','myJoomla.com');`

New Tab (target="_blank"):
`$toolbar->preview('http://myJoomla.com ','myJoomla.com', true);`

**Comment by Septdir** [comment]
@PhilETaylor nice

**Comment by PhilETaylor** [comment]
see #20417

**Comment by PhilETaylor** [comment]
Please close - PR #20417

**Comment by Septdir** [comment]
@PhilETaylor thanks fo #20417 but this, but this is only a part. This issue about add preview in new window for `com_content`

**Comment by PhilETaylor** [comment]
How is that different to https://github.com/joomla/joomla-cms/issues/20418 ?

**Comment by Septdir** [comment]
@PhilETaylor  Nothing. Forgive me was not attentive to the #20418.

Сlose. See #20418
