### ISSUE TITLE
Helix framework

### ISSUE THREAD

**Issue by wilkelly** [joomla/joomla-cms#20268]
I created a site a while ago that uses the Helix framework.  I cannot change the layouts as they are grayed out and I see others had this issue.  I clicked on the links that said you could download an updated on the github site and install in Joomla.  I have not been able to find the updater on the site to download.  Any help appreciated.

**Comment by zero-24** [comment]
Hi please contact the helix framework support ;) Helix is not a part of the Joomla Core.
