### ISSUE TITLE
[4.0] Remove failing sample data installation step

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#20262]
- Sample data is still proposed when installing J4 but fails. Must be removed from installation process.
EDIT: Is not proposed any longer but a short hint occurs if you use "Customization" step.
- We can install sample data in Joomla4 from the control panel via module of type "Sample Data" and related plugins of type "sampledata".
e.g. plugin https://github.com/joomla-extensions/testing-sample-data
EDIT: This plugin does not work at the moment. See https://github.com/joomla-extensions/testing-sample-data/issues/2

![30-04-_2018_14-27-38](https://user-images.githubusercontent.com/20780646/39427288-8a77f17a-4c83-11e8-9a9a-e8dcc2184be8.jpg)

- [See also discussion here](https://github.com/joomla/joomla-cms/issues/20134).

**Comment by Quy** [comment]
Duplicate #20479 ?

**Comment by brianteeman** [comment]
No. This refers to the installer

**Comment by ReLater** [comment]
I don't think that it's a duplicate. This issue here was meant as reminder with additional information for users that wonder how to install sample data.

Sample data installation is broken completely with linked plugin above at the moment. That's why I've updated this issue here with new informations.

**Comment by Chacapamac** [comment]
I didn’t like to bring the sample data, at least for the blog in the main installation interface. I did like the ability to install a other language for administrative process or installing Joomla complete multi language at this point.

**Comment by mbabker** [comment]
Leaving sample data install only in the install app is actually a bit disadvantageous to the ecosystem:

- Sample data is only available when you first install Joomla
- Installers like Softaculous are bypassing our install app in the first place, if they offer sample data it only gets updated whenever they decide to do so
- It's harder for third parties to create quick start packages (think template clubs), as you either have to provide a fully assembled backup or hack the core SQL files to recreate your quick start package

Moving sample data to be an option in the admin app:

- Allows users to install sample data at any time
- Makes it easier to create new sample data packages as they are simply a plugin
- Makes it easier for third parties to create quick start packages, or a utility to install a template then add in all of its sample data to recreate the demo

**Comment by Bakual** [comment]
Also having the sampledata in the admin allows to create the data using the model classes instead of having to write raw SQL files (one per database type). Those sampeldata SQL files currently are notoriously in bad shape.

**Comment by brianteeman** [comment]
fixed by #25828

**Comment by ghost** [comment]
closed as stated above.
