### ISSUE TITLE
No registered feed parser for type rdf:RDF

### ISSUE THREAD

**Issue by drdehart** [joomla/joomla-cms#20264]
### Steps to reproduce the issue
Create an entry in the Newsfeed component with this feed url: http://www.mdpi.com/rss/journal/biology, then publish a News Feed menu item (single news feed) linked to that feed.

### Expected result
Listing of the items in that feed

### Actual result
Error: No registered feed parser for type rdf:RDF

### System information (as much as possible)
Joomla 3.8.7
php 7.1

### Additional comments
Other feeds,, like these work well: 
https://www.sciencedaily.com/rss/matter_energy/biochemistry.xml
http://journals.plos.org/plosbiology/feed/atom
https://www.reddit.com/r/biology/.rss

**Comment by ghost** [comment]
Can someone please answer on this issue as its open since 10+ Days having Staus "New"?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20264">issues.joomla.org/tracker/joomla-cms/20264</a>.</sub>

**Comment by mbabker** [comment]
As labeled it's a feature request.  Our feed parsing library does not have a RDF parser at this time.

**Comment by ghost** [comment]
Thanks for Info, @mbabker.

**Comment by brianteeman** [comment]
This is a very old request for a new feature in Joomla 3. As there has been no interest in providing any code to satisfy this and we are not accepting any new features in Joomla 3 I recommend that it is closed.

**Comment by alikon** [comment]
Closed as stated above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20264">issues.joomla.org/tracker/joomla-cms/20264</a>.</sub>
