### ISSUE TITLE
[4.0] JDatabaseQuery UNION gives unexpected result

### ISSUE THREAD

**Issue by simbunch** [joomla/joomla-cms#20276]
### Steps to reproduce the issue
    $q1 = $db->getQuery(true)->select('name, email')->from('customers');
    $q2 = $db->getQuery(true)->select('name, email')->from('suppliers');
    $q3 = $db->getQuery(true)->select('name, email')->from('shareholders');
    $q1->union($q2)->union($q3);
    echo $q1->__toString();

### Expected result
`SELECT name, email FROM customers UNION ( SELECT name, email FROM suppliers) UNION ( SELECT name, email FROM shareholders)`

### Actual result
`SELECT name, email FROM customers`

### System information (as much as possible)
Joomla 4
MySQL version 5.6.38

### Additional comments
Tested with Joomla 3.8.7 with expected result.

**Comment by alikon** [comment]
can you have a look at https://github.com/joomla-framework/database/pull/116 ?

**Comment by simbunch** [comment]
Worked beautifully, thank you.

**Comment by alikon** [comment]
Please mark as successful tested on the framework/database repo

**Comment by simbunch** [comment]
How do I do that?

**Comment by alikon** [comment]
Just add a comment on that pr that you have tested successfully

Il mer 2 mag 2018, 13:18 simbunch <notifications@github.com> ha scritto:
