### ISSUE TITLE
Exact search in content

### ISSUE THREAD

**Issue by degobbis** [joomla/joomla-cms#20274]
### Steps to reproduce the issue
Create articles with different content, 

Example
1. Form in content
2. form in content
3. inform in content
4. forms or Forms in content

### Expected result
Can someone tell me what the expectation is when we search for `Form` as exact search term?
My oppinion is only nr. 1, with case insansitive nr. 2 too.

### Actual result
We get all examples

**Comment by rdeutz** [comment]
1+4

**Comment by chmst** [comment]
1, 2 and 4. Because in content, where editors write texts. I cannot be sure that they use capitals correctly.

**Comment by SharkyKZ** [comment]
Duplicate #17751.

**Comment by degobbis** [comment]
@rdeutz @chmst Why nr. 4?
Number 2 I would understand, case insansitiv, but 4th could also be called formulating and is therefore not the same or exact.

**Comment by chmst** [comment]
Sorry, my fault. I did not notice the blank after your search string. Therefor: 1 and 2

**Comment by degobbis** [comment]
@chmst there is no blank in my search string. The Forms in 4. was not meant to be a plural. So if we take formulating instead, the output would be wrong for form in an exact search.

**Comment by Quy** [comment]
Duplicate of #17751<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20274">issues.joomla.org/tracker/joomla-cms/20274</a>.</sub>
