### ISSUE TITLE
Upgrading a Joomla website now on version 2.5.28 to 3.8.x  - How can this be done?

### ISSUE THREAD

**Issue by inspiremedia** [joomla/joomla-cms#20283]
### Steps to reproduce the issue
I have a dead-end CMS on HostGator and need assistance in migrating my current website http://www.undercurrentlabs.com to the new version of Joomla as in the admin logging I only get the following message:

 No updates available
You already have the latest Joomla! version, 2.5.28.

Can some one help?  professional services....anybody?

Thanks in advance!

JP

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.
