### ISSUE TITLE
Spam protection for Email Link form

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#20286]
The `Email this link to a friend` form can be used to spam. There are no length restrictions to Sender and Subject fields. As a result, block of text/links can be inserted into the email subject/body with these two fields.

Possible solutions:

* Remove subject field and use article's title instead
* Limit length of Sender field
* Remove links from these fields

**Comment by brianteeman** [comment]
Personally I would remove this functionality completely from joomla

**Comment by zero-24** [comment]
As of [3.8.9](https://github.com/joomla/joomla-cms/pull/20265) we have added captcha support so this is as save as the contact form. By that time the removal was suggested but never confirmed in the internal security tracker.

@wilsonge can you take a moment and take a decision for 4.0? We would also need to take care what happen on upgrades.

**Comment by Quy** [comment]
Pending PR #24025

**Comment by ghost** [comment]
If #24025 is merged this Issue get closed.
