### ISSUE TITLE
Extending Media Field to limit to 'users' directory.

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#20289]
We have something similar in custom fields. Idea is simple, we add an additional option to the media field which could be 'usersdir' = true would then restrict the user to upload and select files within the specificed directory plus the users id or username depending what the community thinks best. So if you defined the directory of the field as:

/images/users/

if usersdir = true and my userid is 498 it would be:

/images/users/498/

**Comment by ot2sen** [comment]
Good idea. Perhaps take groups into account too so that a publisher group for example could only upload select files within their own access group and not only their own personal files.

**Comment by tonypartridge** [comment]
That’s a bit more complicated as you can have multiple groups and access levels within the groups we can’t control what folders are shown just limited to X directory.

**Comment by laoneo** [comment]
At the beginning we had that option in the custom field, but it got removed in #13893 because of #13878.

**Comment by brianteeman** [comment]
sorry but I am going to close this for the same reasons as #13878
