### ISSUE TITLE
user registration - tos not showing correctly

### ISSUE THREAD

**Issue by thimmey** [joomla/joomla-cms#20295]
### Steps to reproduce the issue
Enable the TOS and try to register. For my site its not showing the label text and radio button text corretly

### Expected result
It should show the TOS Text an display the radio buttons correctly

### Actual result
I can see only * [] [] Label for Agree Label for no

### System information (as much as possible)
Joomla 3.8.1 (code is matching current gihub joomla-cms/plugins/user/profile/field/tos.php 
Template LightBlog

### Additional comments
I compared it with joomla-cms/plugins/user/profile/field/dob.php and this one uses other code to get the actual label text. DOB is showing fine.

![unbenannt](https://user-images.githubusercontent.com/684037/39622479-b122f470-4f92-11e8-9ec6-b813a8f6417a.PNG)

**Comment by carlitorweb** [comment]
I can not reproduce your error, in the default template of Joomla. This is an issue related to the template you use.
![registration-form---google-chrome](https://user-images.githubusercontent.com/3956472/39626862-b7233342-4f71-11e8-94d6-1b550a64aac4.png)

**Comment by Quy** [comment]
Not reproducible with v3.8.7. Please ask help at Joomla Forum: https://forum.joomla.org/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20295">issues.joomla.org/tracker/joomla-cms/20295</a>.</sub>

**Comment by Skyla-Scott** [comment]
We had the same problem and it was definitely template related. Themler places a bootstrap.css file which actually caused Protostar and Beez3 to do the same problem so it was misleading. However - could not reproduce on a vanilla install so we eventually narrowed down Themler.

bottom line for anyone reading - check your template.
