### ISSUE TITLE
Malformed subcategory links in category list and blog articles

### ISSUE THREAD

**Issue by billtomczak** [joomla/joomla-cms#20292]
### Steps to reproduce the issue

1. Create a category
2. Create a sub-category to that category
3. Create a Category Listing view and configure so sub-category link is created on the page

### Expected result

A link something like www.example.com/category-menu/2-subcategory

### Actual result

www.example.com/category-menu/2-subcategory?layout=

### System information (as much as possible)

This started happening in Joomla 3.8.7 and has been confirmed not to occur in 3.8.6

### Additional comments

This problem doesn't occur on category blog views. But the back-link to the subcategory in an article does end up with the empty layout variable.

**Comment by Quy** [comment]
Reported, fixed in #20229 and will be included in v3.8.8.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20292">issues.joomla.org/tracker/joomla-cms/20292</a>.</sub>
