### ISSUE TITLE
[4.0] Failed loading script

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#20290]
### Steps to reproduce the issue

- Fresh installation of the 4.0-dev branch
- Login to the backend

### Actual result

> Loading failed for the <script> with source “/media/vendor/webcomponentsjs/js/webcomponents-hi-sd-ce.min.js

This results in none of the CE's working

### System information (as much as possible)

- 4.0-dev branch
- PHP 7.1

@dgrammatiko `.min` files don't actually exist in this directory.

**Comment by dgrammatiko** [comment]
@C-Lodder the bootcrap update also touched webcomponents and custom elements which shouldn't because those things are not in sync right now...

**Comment by C-Lodder** [comment]
https://github.com/joomla/joomla-cms/pull/20291
