### ISSUE TITLE
[META] Update Issue Templates For New GitHub Feature

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#20298]
Per https://blog.github.com/2018-05-02-issue-template-improvements/ there are now improvements in how GitHub handles issue templates, allowing you to have multiple template styles that are presented to the user when clicking the "New Issue" button.  We should get on board with this too.

**Comment by zero-24** [comment]
What about the following proposal:

# Bug Template: (basically that what we have now)
```
### Steps to reproduce the issue



### Expected result



### Actual result



### System information (as much as possible)



### Additional comments


```

# Feature Request

```
### Is your feature request related to a problem? Please describe.



### Describe the solution you'd like



### Additional context


```

**Comment by zero-24** [comment]
@joomla/cms-maintainers @joomla/cms-maintainers-admin  Do you have suggestions / opinions on this topic?

**Comment by Bakual** [comment]
Sure, start with those two. We can always adjust if we see a need.

**Comment by rdeutz** [comment]
What about a general fix, sometimes you struggle about something that needs a fix

## Fix

### Why this should be fixed

....

### Sideeffects expected

...

**Comment by brianteeman** [comment]
Side Effects :)

**Comment by rdeutz** [comment]
I will never get this ;-)

**Comment by zero-24** [comment]
https://github.com/joomla/joomla-cms/issues/new/choose 😄 && https://github.com/joomla/joomla-cms/commit/3ca70d0dca5ac5caf643bb447eb1dab5c84703d4

@rdeutz I have extended your suggestion a bit are you ok with that?

**Comment by rdeutz** [comment]
looks good to me

**Comment by zero-24** [comment]
Ok lets see what happens and if they are used :) Closing this issue for now. Thanks!
