### ISSUE TITLE
Articles - Latest / missing order-option 'Article Order'

### ISSUE THREAD

**Issue by boschmaHH** [joomla/joomla-cms#20307]
### Steps to reproduce the issue
- menu-item showing a blog
- article order set to 'ordering'
- add a module 'articles - latest'
- reorder the articles in the blog

### Expected result
with an additional order-option like 'article order'
module shows same sorting as within the blog

### Actual result
no option like 'article order' in the module avaiable
Module can't show the articles in same order as listed in the blog

### System information (as much as possible)
Fresh installation Joomla 3.8.7

### Additional comments
With some additional fake-article-action and the module set to 'modified first' or 'touched first' you can do a workaround ;)

additional option possible?

**Comment by ReLater** [comment]
On the one hand the module is called "Articles **LATEST**". So, I think that it is the expected bahavior that it sorts articles by dates only.

But on the other hand it has already a misplaced option "Random Articles". So, ?_?

Any reason why you don't use module "Articles Category" or so?

**Comment by boschmaHH** [comment]
You are right - I never used "Articles Category" before, because of the amount of options to set
and because "Articles Latest" is doing the right job at all projects where set up.
The idea came up from a certain project, where 'Articles Latest' was already setup, but later they wanted to change the behavior …

I like the simplicity of 'Articles Latest' and if it's possible to extend the options …
But on the other hand, understanding your point right, "Random Articles" should be taken off ?_?

**Comment by infograf768** [comment]
Random articles is an historical feature of this module which may have been added before the Articles Category module was added to J.
I would just leave these modules as they are and close this issue.

**Comment by brianteeman** [comment]
Also its not actually X Random Articles. It is a Random ordering of the X latest articles

**Comment by brianteeman** [comment]
Closed for the reasons abovw
