### ISSUE TITLE
Multilingual Associations not working

### ISSUE THREAD

**Issue by widmann-it** [joomla/joomla-cms#20311]
### Steps to reproduce the issue
I go to "Components" "Multilingual Associations" and choose any article to translate into another language. Now the window opens and reloads the content again and again. The problem occurs with the two editors JCE and MCE and can be traced as required.
### Expected result
Enter the additional text in another language.
### Actual result
No input possible by reloading the page. For testing several browsers were used (Firefox, IE, Chrome) with all the error occurs. Since it is also possible in a post one cannot assume a wrong configuration of the browser.
### System information (as much as possible)
PHP Built On | Linux ovm2597 2.6.32-openvz-042stab127.2-amd64 #1 SMP Thu Jan 4 16:43:57 MSK 2018 i686
Database Type | mysql
Database Version | 5.7.20-19
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.1.9
Web Server | Apache
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 3.8.7 Stable [ Amani ] 18-April-2018 14:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0

**Comment by infograf768** [comment]
I can't reproduce the issue here with a clean core. (php 7.1.8)
I therefore think it may be related to some of your site settings, including all possible caches.

**Comment by widmann-it** [comment]
There is no cache enabled and no extension installed except JCE

**Comment by infograf768** [comment]
I have some times issue with the js when using this component, but nothing I can't solve by reloading the page.
![multi](https://user-images.githubusercontent.com/869724/39696313-a64aeeba-51ed-11e8-9601-b9f170be445c.gif)

**Comment by widmann-it** [comment]
I have just tried another (new) installation with the same result. It is probably related to the selected default language. With me it was German. I'll check again -)
