### ISSUE TITLE
Switcher parameter style works odd (Joomla 4)

### ISSUE THREAD

**Issue by htmgarcia** [joomla/joomla-cms#20314]
### Steps to reproduce the issue
If you are adding a radio parameter using the switcher class (in this case for a template through the file `templateDetails.xml`)
```
<field
    name="something"
    type="radio"
    class="switcher"
    default="0"
    label="Something">
        <option value="1">Yes</option>
	<option value="0">No</option>
</field>
```

### Expected result
The switcher should be in gray color when the default value is *0* ("No")
The switcher should be in green color when the default value is *1* ("Yes")

### Actual result
The switcher is in green color when the default value is *0* ("No")
<img width="331" alt="screen shot 2018-05-07 at 4 24 55 pm" src="https://user-images.githubusercontent.com/4999794/39725995-36a6f9b6-5213-11e8-93c9-a840611ea72f.png">

The switcher is in gray color when the default value is *1* ("Yes")
<img width="338" alt="screen shot 2018-05-07 at 4 25 28 pm" src="https://user-images.githubusercontent.com/4999794/39726030-4aae37a8-5213-11e8-9164-f8bb4facb87c.png">

### System information (as much as possible)
Chrome Version 66.0.3359.139 (Official Build) (64-bit)
MacOS High Sierra 10.13.4

### Additional comments
It seems that the order of the options would make the switcher to works fine:
```
<option value="0">No</option>
<option value="1">Yes</option>
```

In the other side, if the options are listed with "1" as first, is when doesn't work:
```
<option value="1">Yes</option>
<option value="0">No</option>
```

**Comment by dgrammatiko** [comment]
I will try to fix this in https://github.com/joomla/40-backend-template/pull/395

**Comment by htmgarcia** [comment]
Thanks @dgrammatiko !

**Comment by htmgarcia** [comment]
Closing. This issue was already reported https://github.com/joomla/40-backend-template/pull/395#issuecomment-385733128

**Comment by C-Lodder** [comment]
The normal approach for the Switcher would be (note the order of the options)
```
<option value="0">No</option>
<option value="1">Yes</option>
```

This would result in: No (grey) and Yes (green).

If you don't want "Yes" to be green, or is not the recommended setting, you can add a class to the XML field, like so:

```
<field
    type="radio"
    class="switcher switcher-danger"
```

You cannot "patch" this simply because it may not always be the case where the user uses the values **0** and **1** or the text **No** and **Yes**. They may very well go with:

```
<option value="foo">Apples</option>
<option value="bar">Pears</option>
```
