### ISSUE TITLE
[4.0] Icon styling issue

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#20315]
### Steps to reproduce the issue

In the Joomla backend, go to any list view, such as the Article or Module Manager.

### Expected result

Any icons within the list are displayed correctly

### Actual result

Small styling issue:
![screeny](https://user-images.githubusercontent.com/2019801/39753545-1e63adbe-52b7-11e8-8cfe-1230357716ad.png)

### System information (as much as possible)

Joomla 4.0-dev

**Comment by dgrammatiko** [comment]
I was about to make a PR removing the font awesome (the font) and start using the svgs (lazy loaded, cached), based on https://codepen.io/dgt41/pen/jxrwJE and as demonstrated in dgrammatiko.online (part of my JAB talk) but my phpstorm license expired...
BTW @ciar4n also agrees on the approach, as we effectively decouple joomla from font awesome but still use it!

**Comment by infograf768** [comment]
Let's be carefull with lazy-loading, if it applies here.
See https://forum.joomla.org/viewtopic.php?f=711&t=961813

**Comment by dgrammatiko** [comment]
@infograf768 that's totally irrelevant and also lazy loading **is** the best practice for **all** assets

**Comment by infograf768** [comment]
That is why I wrote

> if it applies here.

**Comment by ciar4n** [comment]
PR created...  #20514
