### ISSUE TITLE
Pagination in category list is broken

### ISSUE THREAD

**Issue by tompecina** [joomla/joomla-cms#20319]
### Steps to reproduce the issue

1. Set up a Joomla site with more than one page of results in a category.

2. Set both Search Engine Friendly URLs and Use URL Rewriting to Yes.

3. Display the respective category and check the pagination links.

### Expected result

The links are correct.

### Actual result

The links are broken, missing the "view=category" parameter.

### System information (as much as possible)

Joomla 3.8.7.

### Additional comments

I've drawn up a dirty hack, definitely not the right way to fix the issue; see the attached patch: [category_bug.patch.txt](https://issues.joomla.org/uploads/1/9d06d23298b0dd49b3185fe2efd6d164.txt).

**Comment by infograf768** [comment]
Please post a screenshot of the page and the precise urls you obtain for the pagination links (SEF off and SEF on)

**Comment by tompecina** [comment]
Attached are the two screenshots of the relevant settings. The URL for Page 2 generated by the Joomla engine is [https://paragraphos-test.pecina.cz/?id=8&start=6], while it should be [https://paragraphos-test.pecina.cz/?view=category&id=8&start=6]. Please let me know if you need any more information.

![screen shot 2018-05-09 at 15 46 01](https://issues.joomla.org/uploads/1/75c58cfe36908bf7896cd0abbab6f866.png)
![screen shot 2018-05-09 at 15 46 04](https://issues.joomla.org/uploads/1/c91c683e8129413a628df0af2f29152c.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20319">issues.joomla.org/tracker/joomla-cms/20319</a>.</sub>

**Comment by infograf768** [comment]
1. A category list menu item does display the correct pagination in a clean Joomla site.
2. Your site is weirdly done.
Links as `https://paragraphos-test.pecina.cz/?view=category&id=8` do exist in the module displayed in the left column under the header `Kategorie` => `Humor`. 
When displayed and using pagination `https://paragraphos-test.pecina.cz/?view=category&id=8&start=6` works fine
These are not links to category list but blog.

Also these links are really ugly and do not look at all as clean joomla links, SEF on or not.
Here when using the Articles Categories module as you did, I get for SEF off for example:
`root/index.php?option=com_content&view=category&id=67&Itemid=571` 
and when sef on
`root/user-modules.html`

**Comment by ghost** [comment]
Closed as stated above seems no Core-Issue.

@tompecina Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding.

**Comment by tompecina** [comment]
It seems you tested on my test site (paragraphos-test.pecina.cz) when it was already patched and thus obviously you could not reproduce the bug. If you're interested in retesting, the test site (paragraphos-test.pecina.cz) is now left unpatched and the live site (paragraphos.pecina.cz) is patched so you can see the difference.

Otherwise, I've fixed it using my patch and I'm closing the issue for myself too. Thanks for your time!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20319">issues.joomla.org/tracker/joomla-cms/20319</a>.</sub>

**Comment by ghost** [comment]
Reopened to find out if its a Core-Issue. @tompecina Thanks for Update.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20319">issues.joomla.org/tracker/joomla-cms/20319</a>.</sub>

**Comment by infograf768** [comment]
BTW, if your home page is a category list (or blog), a url like
`mydomain.com/?start=5` is perfectly OK

**Comment by tompecina** [comment]
Right, but not for any other category, which is the case here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20319">issues.joomla.org/tracker/joomla-cms/20319</a>.</sub>

**Comment by infograf768** [comment]
As I said above your links in the categories module are weird and are not the default ones we obtain with a clean Joomla.

You get
`?view=category&id=8&layout=`
I get here

`index.php?option=com_content&view=category& etc.` 

You have modified something somewhere (extension, else) which creates this apparent issue.

**Comment by tompecina** [comment]
_You have modified something somewhere (extension, else) which creates this apparent issue._

I did not modify the code in any manner (this patch is the first I applied), all I did is I toggled the URL-related controls several times before I got the URLs I liked. Which, unfortunately, I cannot reproduce because I don't remember the order of the changes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20319">issues.joomla.org/tracker/joomla-cms/20319</a>.</sub>

**Comment by infograf768** [comment]
You may not have modified joomla core code, but you may use 3rd party extensions which impact the normal Joomla Routing system.
For example, you use JComments (I do not know if that one is at stake).

**Comment by tompecina** [comment]
_You may not have modified joomla core code, but you may use 3rd party extensions which impact the normal Joomla Routing system.
For example, you use JComments (I do not know if that one is at stake)._

I removed all the third-party extensions from the test site now, but the result is the same: the category list (eg: [Humor](https://paragraphos-test.pecina.cz/?view=category&id=8&layout= "https://paragraphos-test.pecina.cz/?view=category&id=8&layout=") still produces broken pagination links.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20319">issues.joomla.org/tracker/joomla-cms/20319</a>.</sub>

**Comment by infograf768** [comment]
Give me access to your test site by sending superuser credentials at infografjms arobase gmail.com and I will have a look. I am still convinced that something is modified in your test site.

**Comment by tompecina** [comment]
I sent it to arobase at gmail.com: I hope I got the address right!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20319">issues.joomla.org/tracker/joomla-cms/20319</a>.</sub>

**Comment by infograf768** [comment]
https://fr.wikipedia.org/wiki/Arobase 😄 

Sorry, was in French...

**Comment by infograf768** [comment]
You are using Modern Routing.
In this case, one should always add at least a hidden menu item to All Categories.
I did this on the test site and now you will get urls of this type from the categories module
`https://paragraphos-test.pecina.cz/all-categories/nase-pripady/adam-b-bartos?layout=`

and pagination `https://paragraphos-test.pecina.cz/all-categories/nase-pripady/adam-b-bartos?start=10`

The `&layout=` issue has been solved in current code ( https://github.com/joomla/joomla-cms/pull/20229 ) and will be in next J release.

Please delete the special account you created for me.

**Comment by infograf768** [comment]
<img width="717" alt="screen shot 2018-05-11 at 11 28 04" src="https://user-images.githubusercontent.com/869724/39918262-3aa223a6-5510-11e8-8f35-52ccdb64ef55.png">

**Comment by tompecina** [comment]
Tested & implemented on the live site - thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20319">issues.joomla.org/tracker/joomla-cms/20319</a>.</sub>

**Comment by ghost** [comment]
@tompecina if this Issue is resolved please close it.

**Comment by infograf768** [comment]
Long time I wanted to test Olomoucké tvarůžky
do not hesitate. :)

**Comment by tompecina** [comment]
I've never tasted these (and no, I don't drink beer, for that matter) :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20319">issues.joomla.org/tracker/joomla-cms/20319</a>.</sub>

**Comment by infograf768** [comment]
hehe
