### ISSUE TITLE
[4.0] Useless lang strings in installation?

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#20312]
### Steps to reproduce the issue
I remarked these strings in installation/language/en-GB/en-GB.ini

```
; Field password messages
JFIELD_PASSWORD_INDICATE_INCOMPLETE="Password doesn't meet site's requirements"
JFIELD_PASSWORD_INDICATE_COMPLETE="Password accepted"
JFIELD_PASSWORD_NOTE_LBL="Password must contain:"
JFIELD_PASSWORD_NOTE_DESC="%1 symbol(s), %2 uppercase letter(s), %3 lowercase letter(s), %4 number(s)"
```

If anyone who added these strings intends to use them, I would be curious about the way that person intended to code as obviously the variables can't be set by the person installing Joomla.

Maybe the variable would get hardcoded default values (which could be overriden by custom distros in installation/localise.xml) ? Strings anyway would have to be modified.
 
If it is just one of these mistakes (it happens), I rather suggest to add a note asking the SuperUser to set the rules and modify her/his password once J is installed.

or just delete these strings.

**Comment by laoneo** [comment]
If they are not used, then remove them.

**Comment by infograf768** [comment]
@laoneo 
I think it's a pity not to include a password check when installing Joomla (using hardcoded values and these modified strings .`Password doesn't meet site's requirements` would not fit) OR at least inform whoever is installing joomla to modify that super user password asap after install.

As it is today, we still can install using admin/admin (convenient for testers, but not good for online sites) and forget about it.

**Comment by brianteeman** [comment]
i think its less of an unused string and more of a feature not yet implement by @dgrammatiko in the installer

**Comment by Quy** [comment]
Please test PR #27253<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20312">issues.joomla.org/tracker/joomla-cms/20312</a>.</sub>

**Comment by brianteeman** [comment]
Please re-open as I closed the PR

**Comment by Quy** [comment]
Strings can be removed per PR #30402?

**Comment by infograf768** [comment]
> Strings can be removed per PR #30402?

Yep, it looks like indeed.

**Comment by infograf768** [comment]
Others too as the password parameters are not set at installation time.

These should be kept
`JFIELD_PASSWORD_SPACES_IN_PASSWORD="Password must not have spaces at the beginning or end."`
`JFIELD_PASSWORD_TOO_LONG="Password is too long. Passwords must be less than 100 characters."`

But we can get rid of
```
JFIELD_PASSWORD_INDICATE_COMPLETE="Password accepted"
JFIELD_PASSWORD_INDICATE_INCOMPLETE="Password doesn't meet site's requirements."
JFIELD_PASSWORD_NOT_ENOUGH_INTEGERS_N="Password does not have enough digits. At least %s digits are required."
JFIELD_PASSWORD_NOT_ENOUGH_INTEGERS_N_1="Password does not have enough digits. At least 1 digit is required."
JFIELD_PASSWORD_NOT_ENOUGH_LOWERCASE_LETTERS_N="Password does not have enough lower case characters. At least %s lower case characters are required."
JFIELD_PASSWORD_NOT_ENOUGH_LOWERCASE_LETTERS_N_1="Password does not have enough lower case characters. At least 1 lower case character is required."
JFIELD_PASSWORD_NOT_ENOUGH_SYMBOLS_N="Password does not have enough symbols. At least %s symbols are required."
JFIELD_PASSWORD_NOT_ENOUGH_SYMBOLS_N_1="Password does not have enough symbols. At least 1 symbol is required."
JFIELD_PASSWORD_NOT_ENOUGH_UPPERCASE_LETTERS_N="Password does not have enough upper case characters. At least %s upper case characters are required."
JFIELD_PASSWORD_NOT_ENOUGH_UPPERCASE_LETTERS_N_1="Password does not have enough upper case characters. At least 1 upper case character is required."
JFIELD_PASSWORD_NOTE_DESC="%1 symbol(s), %2 uppercase letter(s), %3 lowercase letter(s), %4 number(s)"
JFIELD_PASSWORD_NOTE_LBL="Password must contain:"
```

**Comment by Quy** [comment]
Will you please do a PR? Thanks

**Comment by infograf768** [comment]
in fact we do need the 2 first strings as they are used under the meter.
Making PR now

**Comment by infograf768** [comment]
PR: https://github.com/joomla/joomla-cms/pull/30560
closing

**Comment by dgrammatiko** [comment]
The strings DO NOT belong to any of the apps (site, admin, install). They probably need their own file per field. 
@laoneo had implemented a hook that allows 3rd PD to override any part of Joomla, meaning someone could override the whole JForm thus such strings shouldn't belong to the JApplication 's but rather to the field or the part that they actually belong.

Not to mention that you have the same strings 3x (site, admin, install)

My 2c

**Comment by infograf768** [comment]
Sorry, @dgrammatiko  , had just done the Pr.
No idea what was done and where concerning the installation strings.
If they are linked to a specific field, I wonder how they would be included in language packs though.
Some information are welcome.

**Comment by dgrammatiko** [comment]
@infograf768 the PR is correct in the context of what the installation password field supports. What I was pointing out in my previous comment was that the language strings need a deeper evaluation, having identical strings in 2-3 different places is a maintenance nightmare.
Not asking you to come up with a solution tho, just pointing out something obvious...

**Comment by infograf768** [comment]
@dgrammatiko 
OK
While you are here, could you check what I discovered concerning the <weekend> metadata?
https://github.com/joomla/joomla-cms/pull/30554#issuecomment-686395490
