### ISSUE TITLE
Issueing a request for a deleted banner results in network errors

### ISSUE THREAD

**Issue by norman27** [joomla/joomla-cms#20325]
### Steps to reproduce the issue

- Create a banner in the component (let's say ID=123)
- (now the url /component/banners/click/123 might be indexed by google or used somewhere else)
- Delete this banner completely
- Try to request /component/banners/click/123

### Expected result
Return a HTTP status 404

### Actual result
this will result in an error message generated by the browser regarding broken contents. the return HTTP status is 303 with header Location: http://

### System information (as much as possible)
installed version 3.8.7

### Additional comments
At some point this will also be reported to you via the google search console.

**Comment by ghost** [comment]
Can please anyone answer as this issue has since one Week Status "New"?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20325">issues.joomla.org/tracker/joomla-cms/20325</a>.</sub>

**Comment by Quy** [comment]
Issue confirmed. In PHP error log:

> PHP Notice:  Trying to get property 'track_clicks' of non-object in \components\com_banners\models\banner.php on line 61
> PHP Notice:  Trying to get property 'clickurl' of non-object in \components\com_banners\models\banner.php on line 197

**Comment by Quy** [comment]
Please test PR #20664<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20325">issues.joomla.org/tracker/joomla-cms/20325</a>.</sub>
