### ISSUE TITLE
Case mismatch in core and core extensions JFactory::getDBO > JFactory::getDbo

### ISSUE THREAD

**Issue by buechner-4m** [joomla/joomla-cms#20320]
Look into the code. I found a lot case mismatches like DBO > Dbo (lowerCamelCase) 

Just for the beauty of code and less annotations in PHPStorm.

Nothing changes. 

No changes. 

Joomla 3.8.7

Just for the beauty of code.

**Comment by infograf768** [comment]
All core instances are `JFactory::getDbo()` as far as I can see.

**Comment by Quy** [comment]
Closing. This is the syntax `Dbo` and not `DBO` as the user assumes/prefers it to be.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20320">issues.joomla.org/tracker/joomla-cms/20320</a>.</sub>
