### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by widmann-it** [joomla/joomla-cms#20327]
### Steps to reproduce the issue
Install multiple languages on Joomla and disable all languages except one 
(please change default language)
### Expected result
The corresponding error message appears in the frontend "ERR_TOO_MANY_REDIRECTS"
On closer inspection, it is also noticeable that, depending on the SEO setting in the configuration, a double // after the URL is displayed in the address line after the redirection error:
### Actual result
Switch off the "Language Filter" plugin and the site is accessible again

**Comment by infograf768** [comment]
The language filter plugin should only be used when the site is set as a multilingual site (multiple languages, multiple homes, etc.)
See https://docs.joomla.org/J3.x:Setup_a_Multilingual_Site

Not a bug. Closing.
