### ISSUE TITLE
Functional testing for Joomla\CMS\Schema library

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#20332]
This library really should have some useful functional tests and not just some isolated unit tests.  Not only ensuring that the schema is computed to be in the correct state, but that the computed changeset actually gets applied against a known database state.

**Comment by alikon** [comment]
let me ping @csthomas on this.... i'm not so "able" on this :face_with_head_bandage: 
maybe in this way we can speed up  #19707 :smile:

**Comment by csthomas** [comment]
For Mysql and PostgreSQL it is possible, but for sqlsrv it will be a nightmare.

I'm not saying I'll take it, but I will put it on my TODO list.

**Comment by mbabker** [comment]
Worry less about SQL Server for now since the CMS isn't supporting it in 4.0.

**Comment by brianteeman** [comment]
As the tests have been moved shouldnt this be an issue in the other repos?

**Comment by brianteeman** [comment]
Closed
