### ISSUE TITLE
[4.0] Update the web components polyfills to v2

### ISSUE THREAD

**Issue by dgrammatiko** [joomla/joomla-cms#20331]
### Additional comments
Html imports have been removed, as of v2 (9 May 2018)

**Comment by wilsonge** [comment]
Is there supposed to be a PR for this or?

**Comment by dgrammatiko** [comment]
Will do the PR later on today

**Comment by dgrammatiko** [comment]
PR: https://github.com/joomla/joomla-cms/pull/20429
