### ISSUE TITLE
Articles Legacy Router matches ANY URL ending in a number

### ISSUE THREAD

**Issue by kavadas** [joomla/joomla-cms#20342]
### Steps to reproduce the issue
1. Set "URL Routing" to "Legacy" under Articles option.
2. Visit front-end and enter ANY URL. At the end of the URL add the ID of a published article. 

Example: 
http://site-root/any/url/here/8 (assuming that article with ID 8 is published)

Or if you have "Use URL Rewriting" to "No":
http://site-root/index.php/any/url/here/8 (assuming that article with ID 8 is published)

### Expected result
404 Page

### Actual result
The article with the ID that matches the number at the end of the URL is rendered.

### System information (as much as possible)
Joomla 3.8.7 (Fresh installation, no extensions)

### Additional comments
The issue is caused by com_content legacy router (components/com_content/helpers/legacyrouter.php) . 
Not sure if the legacy routers or the rest core extensions have the same issue.

**Comment by mbabker** [comment]
That's in part why the legacy routers were replaced...

**Comment by brianteeman** [comment]
I am going to close this as this was always an issue and is why we have a new router
