### ISSUE TITLE
Joomla tags Disqus plugin conflict

### ISSUE THREAD

**Issue by DominicVadim** [joomla/joomla-cms#20341]
### Steps to reproduce the issue

Install Disqus plugin and add some new tags in Joomla articles.

### Expected result
When reading content on website, click on any Joomla tag and list the articles containing those tags (Normal Joomla behavior,as it should be)

### Actual result

When reading articles on your website and click on any tag (previously created in articles) you get the following error: 'This page isn’t working
-Your site name here- is currently unable to handle this request.
HTTP ERROR 500' 
The error message appear in Google Chrome. In Mozilla Firefox you get a blank page instead of the error message.

### System information (as much as possible)
System Information
Setting	Value
 
PHP Built On	Linux cloud416.mxserver.ro 3.10.0 #1 SMP Fri Jan 5 21:20:16 MSK 2018 x86_64
Database Type	mysql
Database Version	5.5.5-10.2.14-MariaDB
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.36
Web Server	LiteSpeed
WebServer to PHP Interface	litespeed
Joomla! Version	Joomla! 3.8.7 Stable [ Amani ] 18-April-2018 14:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

### Additional comments
The mentioned issue is resolved by disabling System-Custom Fields plugin. Any other solution known? Thank you !

**Comment by mbabker** [comment]
There's a known conflict with the JoomlaWorks Disqus plugin.  Unfortunately it's an issue in that plugin and not the core code, so it's not something we can fix here.

**Comment by Quy** [comment]
Please test PR #19684 that should fix this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20341">issues.joomla.org/tracker/joomla-cms/20341</a>.</sub>
