### ISSUE TITLE
Support for "tabindex" HTML attribute for form fields

### ISSUE THREAD

**Issue by sagar-ttpl** [joomla/joomla-cms#20346]
For the form fields like input type text and textarea, I couldn't find any support for the "tabindex" HTML attribute.

**Comment by sagar-ttpl** [comment]
If this is a valid issue, then I can send a PR for the same.

**Comment by brianteeman** [comment]
Why would you need to set a tabindex. When not included, the code source order is the default tabbing order of a document, with links, form controls and objects getting focus as they appear in the source code.

**Comment by mbabker** [comment]
Clearly you don't work with my clients who have asked us to make the tab key skip over "non relevant" fields, even against all advice.

**Comment by brianteeman** [comment]
If that is the only use case for adding this then i would definitely not be in favour of adding the ability to break accessibility to the core of joomla

**Comment by mbabker** [comment]
There are 2 ways to argue it.

1) The `tabindex` attribute is part of the HTML spec and should be supported in core.
2) You argue that its use breaks accessibility on sites and shouldn't be supported, in which case we should explicitly not support (and remove from core) anything that can create accessibility problems.

**Comment by brianteeman** [comment]
@mbabker 
1. There are lots of things in the HTML spec that we dont expose in the UI and nor should we
2. Absolutely and if they are identified then we can work to remove them

I am closing this for the reasons stated above
