### ISSUE TITLE
[4.0] Admin template 404 error page broken styling

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20357]
### Steps to reproduce the issue

login as super admin 
go to a faked url like

https://example.com/administrator/index.php?option=com_nonsuch

### Expected result

Nice 404 error page

### Actual result

Broken styles, 

<img width="1036" alt="screen shot 2018-05-12 at 21 03 31" src="https://user-images.githubusercontent.com/400092/39961147-f6f1d05c-5627-11e8-920e-ffc4f47295b3.png">

### System information (as much as possible)

Joomla! 4.0.0-alpha3 Alpha [ Amani ] 12-May-2018 15:23 GMT

**Comment by wilsonge** [comment]
Fixed this with https://github.com/joomla/joomla-cms/commit/239f908be40a179c90a0dfdc79a50c1ae67a419c - the styling isn't perfect - but with the new admin template coming in https://github.com/joomla/40-backend-template - I'm going to close this for now with my fix until the new admin template arrives
