### ISSUE TITLE
[4.0] Too few arguments ModulesController.php on line 106 and exactly 3 expected

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20354]
### Steps to reproduce the issue

login to frontend as super admin
click edit on a module
click save to save the module

### Expected result

no error

### Actual result

0 Too few arguments to function Joomla\CMS\Dispatcher\Dispatcher::__construct(), 2 passed in /Users/phil/Downloads/Joomla_4.0.0-alpha3-Alpha-Full_Package/components/com_config/Controller/ModulesController.php on line 106 and exactly 3 expected

### System information 

Joomla! 4.0.0-alpha3 Alpha [ Amani ] 12-May-2018 15:23 GMT

**Comment by infograf768** [comment]
Using 4.0-dev, I do not get that error but another one:
TypeError: e is null[Learn More] validate.min.js:1:2467

**Comment by infograf768** [comment]
@wilsonge

**Comment by wilsonge** [comment]
Looks like it's a firefox issue that doesn't exist in Chrome. Can you open a separate issue for that please @infograf768 (and I can give it to Dimitris to work on)

I've fixed the one @PhilETaylor reported in #20382 so closing this issue as we have a PR
