### ISSUE TITLE
[4.0] Class 'Joomla\Component\Templates\Administrator\Controller\Style' not found

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20356]
### Steps to reproduce the issue

login to frontend as super admin (after installing demo data in admin)
Click template settings menu item
Click Save

### Expected result

no error - saves... 

### Actual result

Class 'Joomla\Component\Templates\Administrator\Controller\Style' not found

### System information (as much as possible)

Joomla! 4.0.0-alpha3 Alpha [ Amani ] 12-May-2018 15:23 GMT

**Comment by wilsonge** [comment]
I've fixed the class not found part but the MVCfactory injected isn't right still (just gives a different error) so leaving open for now

**Comment by laoneo** [comment]
Can you please test #20620, which should fix the issue.
