### ISSUE TITLE
[4.0] Installation text improvement

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#20351]
### Steps to reproduce the issue

During the installation process, on the "Congratulations" page, a text improvement is desirable for the first part: "Before going on to your site......"

String: INSTL_COMPLETE_DESC

**Comment by ghost** [comment]
PLEASE NOTE!
I discussed with George & Brian that once it has been decided what the text must be, they will help me to create the pull request, since it will be my first.... <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20351">issues.joomla.org/tracker/joomla-cms/20351</a>.</sub>

**Comment by brianteeman** [comment]
@joomlara as promised here is the new string - by the way, the old one was also invalid html markup 

`<p>You now have the option to customise your installation by adding another language or installing the sample data.</p>`


Good luck making your first PR with this. (everyone else please leave this for Lara)

**Comment by laoneo** [comment]
Thanks @brianteeman.

**Comment by ghost** [comment]
Thanks Brian! Let's do this...
If it doesn't work, can I blame the teacher? :) @laoneo <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20351">issues.joomla.org/tracker/joomla-cms/20351</a>.</sub>

**Comment by Quy** [comment]
See PR #20454<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20351">issues.joomla.org/tracker/joomla-cms/20351</a>.</sub>
