### ISSUE TITLE
[4.0] Default 404 page says "URL Invalid" which is not the accepted status text

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20358]
### Steps to reproduce the issue

Maybe a discussion point... or just quick fix. 

Go to any fake url to generate a 404

Although the Status text can be any human readable string, it is most common to stick to the accepted text of "Not Found"

### Expected result

"404 Not Found"
or 
"404 Page Not Found"

### Actual result

404 URL Invalid

The URL is a VALID Url, just in the context of the routing in Joomla doesnt lead to a "page".... so "URL Invalid is syntactically wrong. 

### System information (as much as possible)

Joomla! 4.0.0-alpha3 Alpha [ Amani ] 12-May-2018 15:23 GMT

**Comment by wilsonge** [comment]
This exception only is thrown in one place :) so simple from that perspective to fix https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Router/Router.php#L150

Given we are rendering this one maybe it might also be a good idea to pass this one through JText....

**Comment by PhilETaylor** [comment]
PR #20419
