### ISSUE TITLE
[4.0] Class 'Joomla\Component\Config\Administrator\Controller\Application' not found

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20355]
### Steps to reproduce the issue

login to frontend as super admin (after installing demo data in admin)
Click site settings menu item
Click Save

### Expected result

no error - saves... 

### Actual result

Class 'Joomla\Component\Config\Administrator\Controller\Application' not found

### System information (as much as possible)

Joomla! 4.0.0-alpha3 Alpha [ Amani ] 12-May-2018 15:23 GMT

**Comment by wilsonge** [comment]
I've fixed the class not found part but the MVCfactory injected isn't right still (just gives a different error) so leaving open for now

**Comment by wilsonge** [comment]
OK this no longer fatals. There's still some odd issues with this page but let's open them as we go with separate issues.
