### ISSUE TITLE
[4.0] Media Manager list mode, cannot deselect an item

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20368]
### Steps to reproduce the issue

Go to admin 
get to media manager modal
click 
<img width="74" alt="screen shot 2018-05-12 at 21 51 32" src="https://user-images.githubusercontent.com/400092/39961480-a83ff2f2-562e-11e8-82bf-8f133fe151a0.png">

Select a row - attempt to deselect a row

### Expected result

That you can select and deselect a row just by clicking

### Actual result

You cant.
Watch: 

![screen recording 2018-05-12 at 09 50 pm](https://user-images.githubusercontent.com/400092/39961482-bc74787e-562e-11e8-8609-94668036843a.gif)

### System information (as much as possible)

Joomla! 4.0.0-alpha3 Alpha [ Amani ] 12-May-2018 15:23 GMT

**Comment by laoneo** [comment]
I'm not a UX expert but I would say that this is expected behavior.

**Comment by brianteeman** [comment]
Perhaps - but then it is also the expected behaviour that shift click and control click work in an expected way - they dont. And as I have said before double click to open a folder is not expected behaviour when inside a web browser

**Comment by anuragteapot** [comment]
@PhilETaylor Can you please open this issue in media manager repo. https://github.com/joomla-projects/media-manager-improvement 
and
#20369 
#20370

**Comment by laoneo** [comment]
@brianteeman we have issues for your concerns. Please let us focus here on the issue from @PhilETaylor. Thanks.
