### ISSUE TITLE
Can delete "keep forever" versions

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20365]
### Steps to reproduce the issue

install demo data
edit an article and save it several times to make versions
click the versions button to get the versions
select all
click Keep ON/OFF 
Select all
Click delete

### Expected result

NOTHING is deleted

### Actual result

EVERYTHING is deleted... including the ones that were set to keep = on! 

Joe Blogg's Assumption is that keep = on means those version are kept and CANNOT be deleted.

**Comment by brianteeman** [comment]
I can confirm this is the same for j3 so i have updated the title and original post

**Comment by alikon** [comment]
please test #20430
