### ISSUE TITLE
[4.0] Media Manager - Create Folder, Folder, Folder

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20369]
### Steps to reproduce the issue

Click create folder in media manager

### Expected result

Textbox title should be something like "Please enter the name you want me to use when I create your new folder on the system...." (or something more userfriendly and short)

Textbox title and placeholder should not be the same... 

### Actual result

```
Folder:
[Folder]
```

<img width="255" alt="screen shot 2018-05-12 at 21 53 54" src="https://user-images.githubusercontent.com/400092/39961498-36c693be-562f-11e8-9c64-d859125f4329.png">

Just looks wrong/silly

Also modal title needs more space

Also button should be CREATE not SAVE

### System information (as much as possible)

Joomla! 4.0.0-alpha3 Alpha [ Amani ] 12-May-2018 15:23 GMT

**Comment by Quy** [comment]
Please test PR #23721<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20369">issues.joomla.org/tracker/joomla-cms/20369</a>.</sub>
