### ISSUE TITLE
[4.0] Frontend login page eye not styled

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20361]
### Steps to reproduce the issue

install Joomla! 4.0.0-alpha3 Alpha [ Amani ] 12-May-2018 15:23 GMT
install demo data in admin
go to frontend 
click login button (without entering user/pass) 
you get to the login page at 
http://example.com/index.php/author-login

### Expected result

eye is styled

### Actual result

eye is not styled

<img width="562" alt="screen shot 2018-05-12 at 21 17 02" src="https://user-images.githubusercontent.com/400092/39961229-d7a1b4ae-5629-11e8-8714-f08325d95a4c.png">

**Comment by PhilETaylor** [comment]
also on edit user page in admin 
<img width="563" alt="screen shot 2018-05-12 at 21 34 37" src="https://user-images.githubusercontent.com/400092/39961354-502a2abc-562c-11e8-91b0-316f7c78ae8d.png">

**Comment by mbabker** [comment]
It's all the same form field, custom element, or whatever it is.  Don't need an issue/comment for every occurrence of the password field with a "show password" icon 😉

**Comment by PhilETaylor** [comment]
its right in some places though :) 

<img width="303" alt="screen shot 2018-05-12 at 21 39 31" src="https://user-images.githubusercontent.com/400092/39961400-fa09fec2-562c-11e8-8b80-4155f76c2013.png">

**Comment by infograf768** [comment]
In one case (the nice one) class is `input-group-text icon-eye`
In the other it is `fa fa-eye`

Also `fa-eye` is used in the js to show/hide the password.

**Comment by Quy** [comment]
Fixed in https://github.com/joomla/joomla-cms/pull/19231#issuecomment-375866160<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20361">issues.joomla.org/tracker/joomla-cms/20361</a>.</sub>
