### ISSUE TITLE
[4.0] Unhelpful error message

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20364]
### Steps to reproduce the issue

install Joomla! 4.0.0-alpha3 Alpha [ Amani ] 12-May-2018 15:23 GMT
install demo data
save an article a few times to create versions
go to the versions page for that article
select all 
click compare

### Expected result

An error that tells you to only select TWO items to compare

### Actual result

<img width="1591" alt="screen shot 2018-05-12 at 21 27 50" src="https://user-images.githubusercontent.com/400092/39961329-7a3b41fc-562b-11e8-9a78-5cc9567a3c0f.png">

**Comment by brianteeman** [comment]
This looks like a bug in the javascript that is causing the wrong error message to be displayed as in j3 the messaage correctly says you should only chose two articles @dgrammatiko

**Comment by ghost** [comment]
closed as having Pull Request #20434
