### ISSUE TITLE
[4.0] Media Manager allows you to delete huge nested folder structure with single select & click delete!

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20367]
### Steps to reproduce the issue

In admin, find a media manager modal
Go up to the top most folder, select a folder (which could have your lifes work in it, or photos of your cat)
Click delete

### Expected result

An idiot check
Are you sure you want to delete 10231321 Cat Photos in 13412312 folders? 

### Actual result

Poof! its all deleted!!!!!! 
No backups, gone, zip, nada! 

### System information (as much as possible)

Joomla! 4.0.0-alpha3 Alpha [ Amani ] 12-May-2018 15:23 GMT

**Comment by PhilETaylor** [comment]
same with images - no warning

**Comment by laoneo** [comment]
We are on it https://github.com/joomla-projects/media-manager-improvement/pull/540.
