### ISSUE TITLE
[4.0] eye icon confusion

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20375]
### Steps to reproduce the issue
Joomla! 4.0.0-alpha3 Alpha [ Amani ] 12-May-2018 15:23 GMT

In template manager the eye icon is used, specifically on a row to show no preview available

<img width="557" alt="screen shot 2018-05-12 at 22 27 56" src="https://user-images.githubusercontent.com/400092/39961704-d2ef3f1c-5633-11e8-9115-f9faa6f87252.png">

The Issue:
**This is the same icon that in the users experience, in many other places, is used to hide/show a password. The expectation of a user is that this can be clicked.**

On this page it cannot. It should be replaced with something else to avoid confusion.

**Comment by brianteeman** [comment]
Isn't this the same in joonla3?

**Comment by ghost** [comment]
3.8.7 using disabled Preview of Module Setting:
![bildschirmfoto 2018-05-13 um 07 00 20](https://user-images.githubusercontent.com/8235763/39964033-65470d6c-567b-11e8-9f64-20df7ffb094c.jpg)

**Comment by PhilETaylor** [comment]
Yes but the difference is that J3 doesn’t also use the eye icon on password fields! That’s the point, that’s why this is a J4 issue

**Comment by brianteeman** [comment]
As the password eye is now (will be soon) styled as a button it will mean that this icon usage here will not appear to be cllickable and there is clear text explaining the icon on hover etc I dont believe there will be any confusion now that the usage here is clickable. 
If there was another icon that could be used it would of course be better but there isnt
