### ISSUE TITLE
[4.0] Media Manager, Attempt to rename file to crazy filename generates internal server error

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20370]
### Steps to reproduce the issue

in media manager try to rename a file to 

```
`"'><img src=xxx:x \x00onerror=javascript:alert(1)> </style &#32;><script &#32; :-(>/**/alert(document.location)/**/</script &#32; :-(
```

### Expected result

Error message from the ajax is captured and displayed

### Actual result

Just "Internal Server Error" is displayed in the error message when there is a more descriptive message in the JSON response

<img width="1266" alt="screen shot 2018-05-12 at 21 57 45" src="https://user-images.githubusercontent.com/400092/39961517-b03193de-562f-11e8-8426-fa8017d82a7d.png">

### System information (as much as possible)

Joomla! 4.0.0-alpha3 Alpha [ Amani ] 12-May-2018 15:23 GMT

**Comment by PhilETaylor** [comment]
@joomla/security Might need a review of this....

**Comment by laoneo** [comment]
I was playing a bit around with this issue. The problem is that `JFile`and `JFolder` do not return proper messages and error codes (see #20438 for more details). I'm also not sure if we should expose the exception message in the client (even add it in the response).

**Comment by laoneo** [comment]
Would end up then like 
![image](https://user-images.githubusercontent.com/251072/40530058-a36d4432-5ff7-11e8-9010-1d5affb7e4b8.png)
with the code https://github.com/joomla-projects/media-manager-improvement/compare/rename?expand=1. But honestly I'm not really happy with it at all as we can't detect if there is a server error or a permission exception when a file can't be moved.
