### ISSUE TITLE
[4.0] Cannot order on plugins page (JS Error)

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20374]
### Steps to reproduce the issue

install Joomla! 4.0.0-alpha3 Alpha [ Amani ] 12-May-2018 15:23 GMT
Go to plugins manager
Sort by ordering column
see that the cursor looks like a croshairs indicating sorting is possible
Attempt to sort with a drag and drop action 

### Expected result

No error

### Actual result

JS error and no sorting happening

Watch:

![screen recording 2018-05-12 at 10 21 pm](https://user-images.githubusercontent.com/400092/39961674-3e6e2952-5633-11e8-88a9-4537ae22aeae.gif)

### System information (as much as possible)

Google Chrome.

**Comment by wilsonge** [comment]
I've fixed the jQuery error by moving us from jQuery UI to draggable in 42a180a484

However I still can't actually order the plugins :( @dgrammatiko can you have a look here please to work out why

**Comment by Quy** [comment]
Please test PR #23731<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20374">issues.joomla.org/tracker/joomla-cms/20374</a>.</sub>
