### ISSUE TITLE
[4.0] Advanced Permissions Report Errors

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20378]
### Steps to reproduce the issue

Bundle with previous if you like #18686 #18592

Today:

Click Advanced Permissions Report on a user in admin:

### Expected result

Pretty.... 

### Actual result

Gulp.

<img width="1917" alt="screen shot 2018-05-12 at 22 40 49" src="https://user-images.githubusercontent.com/400092/39961786-8aa9bbd6-5635-11e8-85b3-77eddea111b9.png">
snip snip
<img width="965" alt="screen shot 2018-05-12 at 22 41 25" src="https://user-images.githubusercontent.com/400092/39961796-a2ecfa50-5635-11e8-9a15-41a848d2848d.png">

Note the styling of error pages in admin I logged [here](https://github.com/joomla/joomla-cms/issues/20357) earlier today: 

### System information (as much as possible)

PHP 7.2 !!!!

**Comment by wilsonge** [comment]
Fixed with d1fe20dab9
