### ISSUE TITLE
[4.0] Password strength meter states "Password accepted" when Joomla validation would fail password

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20371]
### Steps to reproduce the issue

I have said it before and Ill say it again, the Password strength meter should be removed - it gives a false reading - here is ANOTHER concrete example of a bug that makes it useless. 

Now lets try a password that STARTS and ENDS with SPACE char...

`SPACEabcSPACE`

where SPACE is an actual space! duh!

this gives: 
<img width="878" alt="screen shot 2018-05-12 at 22 08 28" src="https://user-images.githubusercontent.com/400092/39961575-08bf2754-5631-11e8-9b55-52341e073bf8.png">

So SPACEabcSPACE gives 100% green  - hmmm well ok then, BUT - it also states **"Password accepted"** which a user assumes means that Joomla accepts the password (not that some idiotic JS Password strength meter thinks its ok, so now he thinks it does meet the requirements! 

SAVE......

Oh... haha now you get a big warning of:

```
Warning
Password must not contain spaces at the beginning or end
```

So it was not "accepted"

A concrete example of a bug to fix, and expectation that is not managed.

**Comment by brianteeman** [comment]
You've said this before. No need to open another issue

**Comment by PhilETaylor** [comment]
Pathetic response to what it a VALID issue to be fixed! 

I bet you did not even bother reading what I wrote

**Comment by mbabker** [comment]
Other than having some more detail/opinion on the matter this is no different to https://github.com/joomla/joomla-cms/issues/15582 which you opened last year.

**Comment by PhilETaylor** [comment]
I did not realise that was still open - and ignored for a whole year :-(

**Comment by PhilETaylor** [comment]
Updated title and narrative to highlight the issue. For the record. I see this is already closed and so will never be addressed, but at least I have documented the issue for the one that comes after me.
