### ISSUE TITLE
[4.0] Fluid default template pagination issue

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20379]
### Steps to reproduce the issue

Joomla! 4.0.0-alpha3 Alpha [ Amani ] 12-May-2018 15:23 GMT
Add 10 articles
Archive all 10 articles
Edit template style - set style = fluid
Go to the frontend
navigate to the archive blog from the link in the module

gives url like http://0.0.0.0:8082/index.php/component/content/archive?year=2018&month=5

Set the limit to 5

Click page 2 pagination link

### Expected result

formatted with dropdowns above content like on page 1

page 1 = 

<img width="620" alt="screen shot 2018-05-12 at 22 45 01" src="https://user-images.githubusercontent.com/400092/39961821-27c6751c-5636-11e8-9973-c34278be1ac4.png">

### Actual result

page 2 = 

<img width="1427" alt="screen shot 2018-05-12 at 22 45 27" src="https://user-images.githubusercontent.com/400092/39961824-31e34bce-5636-11e8-86c7-ae0fad70fa0c.png">

**Comment by ghost** [comment]
Thanks Phil for your tests :-)

Do you have Rights to add Categories at Issue Tracker? Cause sometimes i don't to which Categories a Issue belongs and it would be helpful if you can do it a i guess you know it.

**Comment by PhilETaylor** [comment]
> Do you have Rights to add Categories at Issue Tracker?

I have no "rights" at all.. Im just a regular user.
