### ISSUE TITLE
[4.0] Author Login Link near footer

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20372]
### Steps to reproduce the issue

install Joomla! 4.0.0-alpha3 Alpha [ Amani ] 12-May-2018 15:23 GMT and demo data
visit frontend
note the Author Login link in bottom right corner....
looks wrong, is wrong, needs work

<img width="331" alt="screen shot 2018-05-12 at 22 13 03" src="https://user-images.githubusercontent.com/400092/39961606-c65698ce-5631-11e8-8120-f74df6e13e1d.png">

**Comment by brianteeman** [comment]
it is because the module position that this is in (footer) is unstyled in the casseiopeia template

**Comment by wilsonge** [comment]
With sample data the only thing that I have in that position is the copyright. So I'm going to close as cannot reproduce. But may potentially need reopening if i'm missing something obvious

**Comment by PhilETaylor** [comment]
I can still reproduce this today when installing the demo data

see: 

![screen shot 2018-08-19 at 22 41 11](https://user-images.githubusercontent.com/400092/44313452-01632f00-a401-11e8-8cf5-eccde44fc9b7.png)

**Comment by ghost** [comment]
Nightly Update installed one Hour ago using Multilingual Sample Data:

![screen shot 2018-08-20 at 07 04 02](https://user-images.githubusercontent.com/8235763/44321261-41e59b80-a447-11e8-8b8d-e744691b023b.jpg)

**Comment by brianteeman** [comment]
@franz-wohlkoenig the issue is with the testing data not the sample data

**Comment by ghost** [comment]
"testing data" means?

**Comment by brianteeman** [comment]
during the install (which you wont see on CA) there is an option after installing languages to install testing data

However reading it again I was **wrong** in thinking that was the data set Phil was using.

It is the sample data from the control panel (**not** the multilingual sample data) and I can confirm this issue and am re-opening

**Comment by ghost** [comment]
thanks for Info, @brianteeman. I thought all is "Sample Data".
