### ISSUE TITLE
[4.0] Cannot Toggle Menu Assignments in Template Style Edit screen

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20377]
### Steps to reproduce the issue

(Google Chrome tested only)
install Joomla! 4.0.0-alpha3 Alpha [ Amani ] 12-May-2018 15:23 GMT
edit the default template style in admin 

### Expected result

Ability to select menu assignments on that tab

### Actual result

I cant select anything except those in the top left box

WATCH:

![screen recording 2018-05-12 at 10 35 pm](https://user-images.githubusercontent.com/400092/39961750-e84d6ad6-5634-11e8-8cc6-e6f04c2c0916.gif)

**Comment by humblehumanbeing** [comment]
I think it is rather a Chrome issue than a Joomla because I had experienced the same problem in a Gantry 5 Joomla site administration. The right portion of the page in Chrome browser won't allow to make a selection.
I needed to switch to MS Edge to do so.

**Comment by PhilETaylor** [comment]
Actually tested now in firefox with DIFFERENT issues, but still lots of issues. As per video below:

![screen recording 2018-05-15 at 09 37 am](https://user-images.githubusercontent.com/400092/40045989-adc259b2-5823-11e8-83ac-3c924e40ad0c.gif)

**Comment by PhilETaylor** [comment]
Opera again has DIFFERENT issues, but still lots of issues.
![screen recording 2018-05-15 at 09 40 am](https://user-images.githubusercontent.com/400092/40046106-fd572e08-5823-11e8-9e6e-6fd5b3dd7605.gif)

**Comment by brianteeman** [comment]
see #20542
