### ISSUE TITLE
[4.0] Template Color Selector?

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20376]
### Steps to reproduce the issue

Joomla! 4.0.0-alpha3 Alpha [ Amani ] 12-May-2018 15:23 GMT

Edit template style, set RED color in the picker...

### Expected result

 Im ASSUMING this should do something

### Actual result

It appears not to do anything

<img width="1180" alt="screen shot 2018-05-12 at 22 30 05" src="https://user-images.githubusercontent.com/400092/39961711-233024e6-5634-11e8-8f07-ea467cb0940f.png">

**Comment by C-Lodder** [comment]
@dgrammatiko - Wasn't this your form field for testing purposes when you committed the CE?

**Comment by brianteeman** [comment]
Yes thats correct - https://github.com/joomla/joomla-cms/pull/19281#issuecomment-369586543

PR coming to remove it

**Comment by brianteeman** [comment]
Closed see #20652
