### ISSUE TITLE
[4.0] Firefox: module frontend edit broken

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#20389]
Ref: https://github.com/joomla/joomla-cms/issues/20354#issuecomment-388611249

### Steps to reproduce the issue
login to frontend as super admin
click edit on a module
click save to save the module

### Expected result

Saving works fine

### Actual result
js error

TypeError: e is null validate.min.js:1:2467

**Comment by infograf768** [comment]
@dgrammatiko

**Comment by Quy** [comment]
See PR #20398<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20389">issues.joomla.org/tracker/joomla-cms/20389</a>.</sub>
