### ISSUE TITLE
[4.0] password field on installer can't handle a "+" chacracter

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#20395]
### Steps to reproduce the issue
Create a database user with an password which contains a "+" and
try to install Joomla! 4.0

### Expected result
![joomla_installer](https://user-images.githubusercontent.com/37540795/39996388-963665a8-577f-11e8-8cbc-ab0fd4472e00.PNG)

### Actual result

![installer_error](https://user-images.githubusercontent.com/37540795/39997708-0f7cf842-5784-11e8-90e1-01105328857f.PNG)

### System information (as much as possible)
PHP 7.2
Apache 2.4
MySQL 5.7

### Additional comments
I tested this also with the joomla/40-backend-template repo.
The Installer there creates an configuration.php. If I look in there, I see the "+" is missing.

**Comment by PhilETaylor** [comment]
Please test #20414 which encodes the password

**Comment by PhilETaylor** [comment]
Styling of the error message forked to https://github.com/joomla/joomla-cms/issues/20415

**Comment by Quy** [comment]
See PR #20414<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20395">issues.joomla.org/tracker/joomla-cms/20395</a>.</sub>
