### ISSUE TITLE
Session handler set to PHP but sessions table still being populated

### ISSUE THREAD

**Issue by srdjanpejic** [joomla/joomla-cms#20390]
### Steps to reproduce the issue
Truncate #_sessions table, set Session handler to PHP

### Expected result
Expected to have #_sessions table empty in future

### Actual result
#_sessions table is still being populated even with handler set to PHP

### System information (as much as possible)
Joomla CMS: 3.8.5
PHP: 7.0.29
MySQL: 5.5.60

### Additional comments
I decided to take this change since my #_session table size increased to 4.2gb and both administrator panel and site were slow at times (administrator all the time)

**Comment by ghost** [comment]
can you please test on latest Release 3.8.7?

**Comment by brianteeman** [comment]
Closed as this is resolved with the current release

**Comment by srdjanpejic** [comment]
Ok, great, I'm gonna do the update soon and I'll test it again.
Tnx for the replies
