### ISSUE TITLE
Empty "layout" param in com_content Category URL generation

### ISSUE THREAD

**Issue by NickolayCh** [joomla/joomla-cms#20394]
The probjem is in file **\components\com_content\helpers\route.php**, **ContentHelperRoute::getCategoryRoute**, code:

_$layout = $jinput->get('layout');_

_if ($layout !== '')_
_{_
    _$link .= '&layout=' . $layout;_
_}_

That happens because of using not identical comparison on **$layout** variable, when the actual request param is not set and **JInput::get** method is returning **NULL** by default. Suggest using just **if ($layout)** for checking.

**Comment by mbabker** [comment]
Fixed by https://github.com/joomla/joomla-cms/pull/20229
