### ISSUE TITLE
Can't save article

### ISSUE THREAD

**Issue by Jaironlanda** [joomla/joomla-cms#20405]
### Steps to reproduce the issue
Write article and insert/edit code simple. Example PHP code:
```
public function __construct()
{
        parent::__construct();
        $this->load->database();
        $this->load->helper('url');
        $this->load->library('session');
        $this->load->library('form_validation');        
        $this->load->model('Member_model');
}
```

### Expected result
show green pop up success save article.

### Actual result
Redirect to home page and my article not save. :(

### System information (as much as possible)
Joomla! 3.8.7

**Comment by brianteeman** [comment]
It's an article editor not a code editor. Probably your attempt at injecting code in an article was correctly blocked.

**Comment by Jaironlanda** [comment]
I just want show example code in my article. How to fix it?  or any plugin to replace insert/edit code?

**Comment by brianteeman** [comment]
There are several.available.extensions for this at the extension directory.

**Comment by brianteeman** [comment]
Closed.as.not.a bug
