### ISSUE TITLE
[4.0] Status Icons not legible

### ISSUE THREAD

**Issue by OptikWebCreative** [joomla/joomla-cms#20409]
### Steps to reproduce the issue

visit any page with published status icons

### Expected result

check or cross in centre of circle

### Actual result

check or cross merging with bottom line of circle
color is correct and changes

### System information (as much as possible)

localhost J4a3 install
php 7.1.6
localhost mysql
MAMP 4.2

**Comment by brianteeman** [comment]
Closed as a duplicate of #23105
