### ISSUE TITLE
[4.0] Advanced Permission Report Error

### ISSUE THREAD

**Issue by OptikWebCreative** [joomla/joomla-cms#20407]
### Steps to reproduce the issue

Users > Manage > Advanced Permission Report

### Expected result

Information or error in template style

### Actual result

unformatted page, with error message at bottom

An error has occurred.

0 Call to a member function get() on null

### System information (as much as possible)

localhost J4a3 install 
php 7.1.6
localhost mysql
MAMP 4.2

**Comment by ghost** [comment]
@OptikWebCreative can you please write in Title whats the Issue is about?

**Comment by OptikWebCreative** [comment]
@franz-wohlkoenig apologies, meant to do it after completing the report, amended

**Comment by ghost** [comment]
@OptikWebCreative thanks for Report, no Reason for Apologies.

**Comment by PhilETaylor** [comment]
Fixed already

**Comment by brianteeman** [comment]
Thank you for taking the time to test and report this issue in alpha 3. In this case it has already been fixed.

**Comment by OptikWebCreative** [comment]
Sorry for wasting time reporting a fixed issue, i did search all the issues I’ve raised today, but nothing came up in the search :( 

I will ensure the closed tickets are included in future
