### ISSUE TITLE
[4.0] Component Install from Web Issues

### ISSUE THREAD

**Issue by OptikWebCreative** [joomla/joomla-cms#20408]
### Steps to reproduce the issue

Install From Web does nothing when click install button
Extensions > Install > Install From Web 
> Akeeba Backup
> Portfolio Gallery 

(I chose these as they are tagged on extension directory as J4 Alpha Compatible)

### Expected result

Install of Relevant Component

### Actual result

No Action / Activity

### System information (as much as possible)

localhost J4a3 install
php 7.1.6
localhost mysql
MAMP 4.2

**Comment by mbabker** [comment]
You have to scroll to the bottom of the window to see the install buttons, the JavaScript relied on jQuery for that effect and the jQuery transition has been removed.

It's a known issue tracked with https://github.com/joomla/joomla-cms/issues/19429
