### ISSUE TITLE
[4.0] [com_content] Ability to toggle the preview button to be a modal or a new tab/page

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20418]
### Steps to reproduce the issue
also see #20417 and 
#20241 - about com_content not only about opening preview in a new window
#20240 - for j3.x Although I will not oppose its closure. If this is realized in j4.

----

https://github.com/joomla/joomla-cms/pull/20417 implements the code to allow the preview button when editing an article in admin to be either a model or new window (target=_blank).

**This is the first half of this job.** 

The code to support the above feature in the Toolbar trait is now done.

The next part is to find a place to have a toggle for 

> Open the preview in a "model" or "new window" 

when clicking the preview button. 

I guess the right place is here? 

<img width="1433" alt="screen shot 2018-05-15 at 22 46 23" src="https://user-images.githubusercontent.com/400092/40085278-d242ad3c-5891-11e8-841a-e4a5a030e79c.png">

once the "right place" has been found for this toggle, the toggle can be added, and then the implementation of that selected value can be used as a bool when calling the toolbar preview link in 

https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_content/View/Article/HtmlView.php#L183

**Comment by Septdir** [comment]
Please add `[com_content]` tag to title.

@PhilETaylor
> I guess the right place is here?

Here or in Integration tab

**Comment by Septdir** [comment]
#20417 Merged

**Comment by brianteeman** [comment]
yes this screen would be the right place to add yet another option
