### ISSUE TITLE
[4.0] Top Menu disappearing on scroll

### ISSUE THREAD

**Issue by OptikWebCreative** [joomla/joomla-cms#20416]
### Steps to reproduce the issue

Any Admin Page, scroll down page, the top menu with the sidebar collapse button is scrolling off page, this is problematic when viewing for example the extension library on a smaller screen laptop (13"), when the text is interrupted and you have multiple instances of broken words

### Expected result

Top dark blue menu be static as well as the grey menu underneath it

### Actual result

Grey menu locks to top of page, blue menu scrolls off page

**Comment by brianteeman** [comment]
I believe this has already been resolved in the template repo but not merged here yet. If you can install this version of joomla then you can check it out. https://github.com/joomla/40-backend-template/archive/master.zip

**Comment by OptikWebCreative** [comment]
@brianteeman sorry, still exhibiting this same issue using the install linked above, that version also has some issues with some sub menu items being on a transparent background

**Comment by brianteeman** [comment]
As the main development of the template is being done over there can you report it on the issues there. It would really help.

Thanks for checking

**Comment by OptikWebCreative** [comment]
@brianteeman will do - great to see you active again :D

**Comment by brianteeman** [comment]
closing it here for now as it is in the template repo - thanks
