### ISSUE TITLE
[4.0] Installation validation error messages need styling

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20415]
### Steps to reproduce the issue

enter invalid creadentials in installer in 4.0-dev

### Expected result

Scrolled to top of page, and formatted error in red? 

### Actual result

left at the bottom of the scroll (on small screen) and badly templated error message like:

![39997708-0f7cf842-5784-11e8-90e1-01105328857f](https://user-images.githubusercontent.com/400092/40083538-5afa78a4-588c-11e8-91c5-abc113ed5a27.png)

### Additional comments

Forked from #20395

**Comment by Quy** [comment]
Cannot reproduce

![alert](https://user-images.githubusercontent.com/368084/40389519-8a9f10a2-5dc7-11e8-8ba1-e030e60272da.jpg)
