### ISSUE TITLE
[4.0] CODEOWNERS support

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#20420]
As discussed with @wilsonge at JAB it would be good to implement github codeowners support for J4. It does support the ability to request reviews from different people or teams for each branch within the same .git folder

See https://help.github.com/articles/about-codeowners/

**Comment by PhilETaylor** [comment]
#20137

**Comment by brianteeman** [comment]
guess you didnt read what i wrote :(

**Comment by PhilETaylor** [comment]
No I did, but for everyone else who needs to understand more about this the context is all explained much better in that thread. The discussion in that thread is important, and would just happen again in this issue - linking the two stops having to fight the same battled over and over again. 

Basically you are saying implement it for Joomla 4 - whereas the other thread has already implemented it for Joomla 3.  The concept and discussion points are mainly still valid

**Comment by mbabker** [comment]
The CODEOWNERS file was merged up, so we do have that in place now on the 4.0 branch.

It needs to be expanded upon as I was trying to argue for in the original PR so that proper teams are set up across the repo.  Especially as a fair number of resources are moving around.

**Comment by wilsonge** [comment]
I cherry-picked this in jab on Saturday as we discussed. Unless you want to have different code owners for this there’s nothing more to be done here

**Comment by brianteeman** [comment]
My reading was that you did it all in one file in the main branch and not
in each branch.

And yes there are different folders and possibly owners to monitor in the
j4 branch

**Comment by mbabker** [comment]
It works per branch.  It kicked in on the 4.0 PRs as soon as that merged up.

**Comment by brianteeman** [comment]
@wilsonge this is why I assumed it was not working on j4 https://github.com/joomla/joomla-cms/pull/20403 as it was merged without my review and it has errors

**Comment by zero-24** [comment]
Well Repo Owner / Org Owner can merge even without a review but it got appended:
![image](https://user-images.githubusercontent.com/2596554/40123607-e1157da4-5926-11e8-9477-d45bdb8e818b.png)

I'm happy to fix the errors just let me know which ;)

**Comment by brianteeman** [comment]
Just because they can doesnt mean they should ;)

I will put it on my todo list for after paris to review. Some are simple like missing . at the end of sentences but there are other parts that dont read well

**Comment by zero-24** [comment]
Thanks 👍
