### ISSUE TITLE
Smart Search - Content lock saving articles

### ISSUE THREAD

**Issue by GarryMoveOut** [joomla/joomla-cms#20423]
### Steps to reproduce the issue
Make sure that plugin Smart Search - Content is enabled.
Install official Polish Language Pack (3.8.7v2) from joomla.org
Create new article or edit existing, write something and click "Save".

### Expected result
Saved article without errors.

### Actual result
**Oryginal error message:** 
"_Error
Save failed with the following error: BŁĄD: kolumna "t" relacji "i5c7v_finder_terms" nie istnieje LINE 2: SET t.links = t.links - 1 ^_"
**translated:**
Error
Save failed with the following error: ERROR: column "t" relation"i5c7v_finder_terms" do not exist LINE 2: SET t.links = t.links - 1 ^

**Original log from pgsql:**
BŁĄD:  kolumna "t" relacji "i5c7v_finder_terms" nie istnieje przy znaku 40
WYRAŻENIE:  UPDATE "i5c7v_finder_terms" AS "t"
        SET t.links = t.links - 1
        FROM "i5c7v_finder_links_terms0" AS "m"
        WHERE "m"."link_id" = 7 AND m.term_id = t.term_id
**translated:**
ERROR:  column "t" relation "i5c7v_finder_terms"  do not exist near sign 40
STATEMENT:  UPDATE "i5c7v_finder_terms" AS "t"
        SET t.links = t.links - 1
        FROM "i5c7v_finder_links_terms0" AS "m"
        WHERE "m"."link_id" = 7 AND m.term_id = t.term_id

### System information (as much as possible)
Platform
CentOS 7 + Apache2 + PostgreSQL 9.2 + PHP 5.14.6 + Joomla 3.8.7 (3.8.6 also)

### Additional comments
When I disable Smart Search - Content plugin all works fine.  Also SQL statement is wrong.

**Comment by brianteeman** [comment]
If i recall correctly the key issue here is that it is using postgres

**Comment by csthomas** [comment]
The patch is at https://github.com/joomla/joomla-cms/pull/19964

**Comment by ghost** [comment]
closed as known issue. @csthomas thanks for searching for Pull Request.

@GarryMoveOut can you please test #19964?

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20423">issues.joomla.org/tracker/joomla-cms/20423</a>.</sub>

**Comment by GarryMoveOut** [comment]
@franz-wohlkoenig yes of course.
I tested and it works great. No errors.
