### ISSUE TITLE
[SOLVED] 4  alpha 3 mod_login wrong redirection 

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#20428]
### Steps to reproduce the issue
use normal mod_login in frontend

### Expected result
works normally

### Actual result
redirect to /component/users?task=user.login  with error 404 (The requested URL /index.php was not found on this server.)

### System information (as much as possible)
Joomla! 4.0.0-alpha3 Alpha [ Amani ] 12-May-2018 15:23 GMT
mysql 5.6.37
php 7.1.8
Apache/2.4.27 (Unix) 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
localhost using AMPPS

**Comment by carlitorweb** [comment]
I can not reproduce your issue. Here redirect normal to the home page.

![video_2018-05-16_103120](https://user-images.githubusercontent.com/3956472/40123517-68f3c362-58f4-11e8-8b0e-1a4200b747c1.gif)

----------------------------------------
Joomla! 4.0.0-alpha3 Alpha [ Amani ] 12-May-2018 15:23 GMT
php 7.2.4
Apache/2.4.33

**Comment by ghost** [comment]
Sorry my bad !
a problem with htaccess
