### ISSUE TITLE
folder & file names with spaces in the media manager

### ISSUE THREAD

**Issue by under44** [joomla/joomla-cms#20437]
### Steps to reproduce the issue
Just recently wrote a simple plugin-editors-xtd button, based on the frame com_media. But then opened a very unpleasant thing.

I cannot select a folder or a file that contains space characters in the material through editors-xtd image button.
The same in media manager. It explicitly States that the name should not contain any space characters.
Previously created folders with space characters are displayed,but there is no navigation.

### Expected result
Go to the selected folder.

### Actual result
Folder that contains space characters is not navigated.

### System information (as much as possible)
Joomla 3.8.7  17-May-2018
Apache/2.4.33(Win64) PHP/7.2.3

### Additional comments
And this is the 21st century and the development of technology? Even filtering input->get(folder,", 'path') requests does not support spaces.
It turns out that the Joomla project is now developing for themselves, not for users.
Guys, what the hell?

**Comment by brianteeman** [comment]
Comments like that are unlikely to get a positive response

**Comment by laoneo** [comment]
Thanks @brianteeman. I tried to find positive words I wanted to compile in an answer but failed.

**Comment by under44** [comment]
Dear friend, I have no purpose to offend anyone. I was shocked. How could that be? This is not a mistake, as I first thought, and a special measure. And I've always loved Joomla, but it's a very strange way.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20437">issues.joomla.org/tracker/joomla-cms/20437</a>.</sub>

**Comment by Quy** [comment]
Duplicate #18287

**Comment by infograf768** [comment]
https://superuser.com/questions/29111/what-technical-reasons-exist-for-not-using-space-characters-in-file-names

**Comment by Bakual** [comment]
I've had issues in the past myself with whitespace in filenames. Mainly when using in JS/Flash mediaplayers.
So it's not unproblematic. Of course it works for most cases and browsers itself obviously don't have issues with it, but if I have to give a recommendation, I still say try to keep filenames lowercased and without whitespace or any other special characters. Better safe than sorry :smile:

**Comment by under44** [comment]
@infograf768 ,
the first thing I wanted to do was solve the problem with URL decoding. But it gave a little, because the problem was at the level of libraries. There are, of course, reasons for the prohibition of gaps. But another question. Why not immediately build a new architecture with these albeit unpleasant features...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20437">issues.joomla.org/tracker/joomla-cms/20437</a>.</sub>

**Comment by under44** [comment]
@Bakual ,
Thin recommendation.:)) However, it is not good to drive users into some framework. Moreover, the gaps are used everywhere. I have in my project thousands of images and different documents, and all the materials links to them. My plugin certainly places them in HTML-tags without any problems. But when using standard libraries and plug-ins, you don't want to run into an impenetrable wall. Then the components as well as the engine lose their meaning if they can't be used for different tasks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20437">issues.joomla.org/tracker/joomla-cms/20437</a>.</sub>

**Comment by mbabker** [comment]
Closing as a duplicate as already pointed out in https://github.com/joomla/joomla-cms/issues/20437#issuecomment-389808986
