### ISSUE TITLE
[4.0] Why the form in "List of all tags" wraps also the list of tags?

### ISSUE THREAD

**Issue by htmgarcia** [joomla/joomla-cms#20442]
### Steps to reproduce the issue
- Create a menu item type: Tags > "List of all tags"
- Be sure you have tags to display
- Preview the page in frontend
![all_tags_](https://user-images.githubusercontent.com/4999794/40195806-33ccf16e-59d4-11e8-867e-64eb2efbbf40.jpg)

### Expected result
The form to filter tags should include only the search field and the number of items to display.

### Actual result
The form also wraps the list of tags.

### System information (as much as possible)
Chrome 66.0.3359.139 (Official Build) (64-bit)
macOS High Sierra 10.13.4

### Additional comments
Let's close the <form> tag before displaying the list of tags

**Comment by Quy** [comment]
See PR #20443<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20442">issues.joomla.org/tracker/joomla-cms/20442</a>.</sub>

**Comment by htmgarcia** [comment]
@Quy I created an issue (this one) and a PR (the one you mention).
Not sure if this is the right place to ask: what is the protocol? Open an Issue and send a PR, or is ok if I just create the PR directly with no issue associated?

**Comment by SharkyKZ** [comment]
You don't need to create an issue if you have a PR ready.
