### ISSUE TITLE
[4.0] Tool tips duplicated by callouts

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20467]
### Steps to reproduce the issue

Might be someones work in progress but looks bad at present...  

79fd94942e1758cff32da7f8f368b5f78cc75c40
google chrome
go to global config (for example) 

### Expected result

A tooltip on hover OR a callout in blue (preferably in the OTHER column and not the label column)

### Actual result

Duplication of messages

![screen recording 2018-05-19 at 07 58 pm](https://user-images.githubusercontent.com/400092/40272074-30d2635a-5b9f-11e8-8eb7-a880c4567934.gif)

### System information (as much as possible)

79fd94942e1758cff32da7f8f368b5f78cc75c40

**Comment by dgrammatiko** [comment]
Just FYI: there was a decision in JAB18 to completely drop the javascript tooltips and use css only tips (when those are required). So expect this part to drastically change when we (basically @ciar4n) gets the PR for the css part (I guess I will helping him with the php part, but feel free to take over)

**Comment by PhilETaylor** [comment]
confirmed broken in 3fc0ac2e88411a32911a8917308410c7eac1045a (Aug 2017) but actually fixed and working today in 79fd94942e1758cff32da7f8f368b5f78cc75c40 (Im an idiot and reporting issues today from the wrong checkout folder due to nginx config pointing to the wrong install doh!)
