### ISSUE TITLE
[4.0] media manager inconsistent selection of folders/files

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20469]
### Expected result

hard to explain, but either I should be able to select lots of folders AND files (and then delete?) or maybe a consistent experience when selecting different types of file or folder in multiples.... at the moment its not consistent to normal experience

### Actual result

![screen recording 2018-05-19 at 08 08 pm](https://user-images.githubusercontent.com/400092/40272133-9534ef10-5ba0-11e8-9eea-cc0b59d34885.gif)

### System information (as much as possible)

79fd94942e1758cff32da7f8f368b5f78cc75c40
google chrome

**Comment by Quy** [comment]
I think media manager related issues for v4.0 should be reported here:
https://github.com/joomla-projects/media-manager-improvement

**Comment by PhilETaylor** [comment]
hmm I thought that had already been merged? so hard for people to contribute when key components of the project are spread out and no communication is given on where what is where.

Ive filed loads of issues on media manager in the main repo - today - and before today

**Comment by Quy** [comment]
Sorry I am not 100% sure. I have not followed v4.0 issues much, however, I have seen previous reports that were instructed to report them there. For now, please ignore my comment.

 @laoneo Please advise.
