### ISSUE TITLE
[4.0] menu links wrong after 404

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20475]
### Steps to reproduce the issue

79fd94942e1758cff32da7f8f368b5f78cc75c40
Go to http://joomla-cms/administrator/index.php?option=com_nonsuch
Click Media menu item

### Expected result

first a 404, and then clicking media (or other links) still stay in /administrator/

### Actual result

/administrator/ is lost from urls

**Comment by brianteeman** [comment]
I can't replicate this in the current staging so can only assume it has been fixed elsewhere. If it has not then it can be re-opened
