### ISSUE TITLE
[4.0] Can attempt to install sample data twice

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20479]
### Steps to reproduce the issue

Click install on the sample data module - let it install the sample data - click install again, or reload the page (after a day or two maybe when you have forgotten you installed the data) and click install again 

### Expected result

Once the sample data is installed, no prompt, no install button, should ever be shown again

### Actual result

<img width="723" alt="screen shot 2018-05-19 at 21 10 08" src="https://user-images.githubusercontent.com/400092/40272674-30837b0a-5ba9-11e8-99bf-f232c0c2e17c.png">

### System information (as much as possible)

79fd94942e1758cff32da7f8f368b5f78cc75c40
Google Chrome

**Comment by brianteeman** [comment]
Confirmed. I guess we need some sort of check before the module is displayed on the control panel

**Comment by Quy** [comment]
Closing in favor of #23633 which has additional details.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20479">issues.joomla.org/tracker/joomla-cms/20479</a>.</sub>
