### ISSUE TITLE
[4.0] cannot use com_media in frontend, joomla issue, not media issue

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20476]
### Steps to reproduce the issue

@wilsonge another of your quick fixes?

79fd94942e1758cff32da7f8f368b5f78cc75c40

http://joomla-cms/index.php?option=com_media

<img width="1205" alt="screen shot 2018-05-19 at 20 55 01" src="https://user-images.githubusercontent.com/400092/40272547-ea82a6a0-5ba6-11e8-87dd-10163d934f16.png">

**Comment by laoneo** [comment]
Please test the pr in the MM repo https://github.com/joomla-projects/media-manager-improvement/pull/548. Thanks for reporting.
