### ISSUE TITLE
[4.0] Hide/Show not showing right

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20472]
### Steps to reproduce the issue

![screen recording 2018-05-19 at 08 30 pm](https://user-images.githubusercontent.com/400092/40272339-91ca28d8-5ba3-11e8-99d1-6e3da8d90a70.gif)

### Expected result

Side by side icons? ON/Off toggle switch type icons?

### Actual result

see above

### System information (as much as possible)

79fd94942e1758cff32da7f8f368b5f78cc75c40
google chrome

**Comment by Bakual** [comment]
I can't confirm this. I get a regular switcher there, not the radio buttons.
![image](https://user-images.githubusercontent.com/1018684/40272468-bdec05d0-5bad-11e8-9402-520c9939feb2.png)
Not sure why you got that.

**Comment by PhilETaylor** [comment]
cause Im bloody idiot and using the wrong folder... I am reviewing all my issues from today - sorry...

**Comment by Bakual** [comment]
Ah, that explains it 😄

**Comment by PhilETaylor** [comment]
confirmed broken in 3fc0ac2e88411a32911a8917308410c7eac1045a (Aug 2017) but actually fixed and working today in 79fd94942e1758cff32da7f8f368b5f78cc75c40
