### ISSUE TITLE
[4.0] Cannot add page break in editor of default install

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20478]
### Steps to reproduce the issue

Edit article, select CMS Content dropdown, select page break.

### Expected result

pagebreak added to WYSIWYG

### Actual result

JS Error

```
VM2623 admin-article-pagebreak.min.js:1 Uncaught TypeError: window.parent.jModalClose is not a function
```

![screen recording 2018-05-19 at 09 06 pm](https://user-images.githubusercontent.com/400092/40272661-c0dc5e52-5ba8-11e8-9180-61d990eb2cc9.gif)

### System information (as much as possible)

79fd94942e1758cff32da7f8f368b5f78cc75c40
Google chrome

**Comment by brianteeman** [comment]
Confirmed

  | window.insertPagebreak | @ | /cms4/media/com_cont…f205e60ac32f0d5dd:1
-- | -- | -- | --
  | onclick | @ | /cms4/index.php?opti…form_articletext:45

**Comment by wilsonge** [comment]
Fixed by https://github.com/joomla/joomla-cms/commit/3e1f27b01f7145771b8c49942dfd79c6353db105
