### ISSUE TITLE
[4.0] After installing sample data, get outputted notice on frontend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20480]
### Steps to reproduce the issue

install joomla 4 from 79fd94942e1758cff32da7f8f368b5f78cc75c40
install sample data from admin module
navigate to "welcome to your blog"

### Expected result

No PHP Notices, Warnings or Errors

### Actual result

Notice: Trying to get property of non-object in [/Users/phil/Sites/joomla-cms/layouts/joomla/content/full_image.php on line 14](https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/content/full_image.php#L14)

<img width="1148" alt="screen shot 2018-05-19 at 21 13 09" src="https://user-images.githubusercontent.com/400092/40272709-bf5df5c6-5ba9-11e8-81ab-1ea208fc006f.png">

### System information (as much as possible)

79fd94942e1758cff32da7f8f368b5f78cc75c40

**Comment by laoneo** [comment]
Does #20503 fix the issue?

**Comment by infograf768** [comment]
It should ;)

**Comment by Quy** [comment]
Fixed in PR #20503<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20480">issues.joomla.org/tracker/joomla-cms/20480</a>.</sub>
