### ISSUE TITLE
[4.0] Cannot save "Site Settings" in frontend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20484]
### Steps to reproduce the issue

install 4.0-dev at 79fd94942e1758cff32da7f8f368b5f78cc75c40
install sample data
login as super admin on frontend
click site settings (to edit them) 

### Expected result

Save and close buttons work

### Actual result

Save and close buttons do nothing.

![screen recording 2018-05-19 at 09 30 pm](https://user-images.githubusercontent.com/400092/40272812-e1d633a0-5bab-11e8-9ad0-1e340ca6d564.gif)

### System information (as much as possible)

79fd94942e1758cff32da7f8f368b5f78cc75c40
google chrome

**Comment by laoneo** [comment]
Please test #20620 which should fix the issue.
