### ISSUE TITLE
[4.0] WYSIWYG Editor CMS Content items not available in frontend.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20483]
### Steps to reproduce the issue

Edit an article with default editor and sample data
use the CMS Content dropdown to select Articles or Contacts

### Expected result

a model with data to select from 

### Actual result

404 in models 
(http://joomla-cms/index.php?option=com_modules&view=modules&layout=modal&tmpl=component&editor=jform_articletext&fcb67bae99528be99f3832dbc78db4cb=1)

(js for pagebreak/readmore, these forked as different issues in GH) 
![screen recording 2018-05-19 at 09 27 pm](https://user-images.githubusercontent.com/400092/40272789-78a5436c-5bab-11e8-916c-8f4018182ad7.gif)

### System information (as much as possible)

79fd94942e1758cff32da7f8f368b5f78cc75c40
Google chrome

**Comment by brianteeman** [comment]
Confirmed 404 View not found [name, type, prefix]: articles, html,

**Comment by brianteeman** [comment]
closed see #21208
