### ISSUE TITLE
[4.0] WYSIWYG errors persist on tab change

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20489]
### Steps to reproduce the issue

install 4.0-dev at 79fd94942e1758cff32da7f8f368b5f78cc75c40
install sample data 
login to frontend as super admin
edit an article 
generate an error in WYSIWYG (see my gif) 
change tab

### Expected result

Error should be dismissed, or at the least, persist on the original tab only

### Actual result

Error overlays all tabs until manually dismissed

![screen recording 2018-05-19 at 09 57 pm](https://user-images.githubusercontent.com/400092/40272979-d5c4f1a6-5baf-11e8-974d-eab1ae530f8d.gif)

### System information (as much as possible)
79fd94942e1758cff32da7f8f368b5f78cc75c40
Google Chrome

### Additional information 

does the same in admin

**Comment by dgrammatiko** [comment]
that's a tinymce bug, please report it upstream

**Comment by PhilETaylor** [comment]
maybe but might be fixable in joomla

**Comment by brianteeman** [comment]
Closed as an upstream bug
