### ISSUE TITLE
[4.0] Edit profile on frontend, cancel button reloads page,

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20485]
### Steps to reproduce the issue

install 4.0-dev at 79fd94942e1758cff32da7f8f368b5f78cc75c40
install sample data
login on frontend as super admin
click change password in top right module
Click Cancel button

### Expected result

"something" is cancelled, and redirected "somewhere'

I dont have the answer to where "somewhere" should be, but it should not be the actual result below

### Actual result

Page reloads. 

![screen recording 2018-05-19 at 09 33 pm](https://user-images.githubusercontent.com/400092/40272834-4d0c3e26-5bac-11e8-9c20-643404fd0f65.gif)

### System information (as much as possible)

79fd94942e1758cff32da7f8f368b5f78cc75c40
Google Chrome

**Comment by brianteeman** [comment]
For reference - it is the same for J3

**Comment by ghost** [comment]
closed as having Pull Request #21187
