### ISSUE TITLE
[4.0] Cannot select base item in frontend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20487]
### Steps to reproduce the issue

install from 4.0-dev at 79fd94942e1758cff32da7f8f368b5f78cc75c40
install sample data
login to frontend as super admin 
click edit button on main menu module
scroll down open accordion options and click select on BASE ITEM

### Expected result

something in a modal

### Actual result

404 in modal

clicking create gives DIFFERENT error inside a modal and then JS issue on trying to close modal

![screen recording 2018-05-19 at 09 50 pm](https://user-images.githubusercontent.com/400092/40272938-cda58766-5bae-11e8-9da3-be0ebb67c39c.gif)

### System information (as much as possible)

79fd94942e1758cff32da7f8f368b5f78cc75c40
Google Chrome

**Comment by brianteeman** [comment]
confirmed

**Comment by laoneo** [comment]
Not sure if #20620 fixes this issue too.

**Comment by infograf768** [comment]
I can't reproduce the issue here (using blog sample data on multilingual) on current 4.0-dev
(on Chrome or FIrefox)

**Comment by infograf768** [comment]
@PhilETaylor 
Do you still have the issue?

**Comment by brianteeman** [comment]
Confirmed 
404 View not found [name, type, prefix]: items, html, menusView

**Comment by laoneo** [comment]
Did you try #20620, does it not fix this issue too?

**Comment by brianteeman** [comment]
yes and no

**Comment by laoneo** [comment]
Wrong button. Will have a look on the issue next week.

**Comment by laoneo** [comment]
Can you please test #20704 which should fix the issue?
