### ISSUE TITLE
[4.0] Editing module on frontend attempts to load ajax with invalid response

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20482]
### Steps to reproduce the issue

Edit a module on the frontend

### Expected result

All ajax calls return valid responses.

### Actual result

Call to: http://joomla-cms/index.php?option=com_modules&task=module.orderPosition&fcb67bae99528be99f3832dbc78db4cb=1client_id=0&position=sidebar-right

produces error:  ` Invalid controller class: module`

![screen recording 2018-05-19 at 09 23 pm](https://user-images.githubusercontent.com/400092/40272772-02587b84-5bab-11e8-8b6a-3afef3d90588.gif)

### System information (as much as possible)
79fd94942e1758cff32da7f8f368b5f78cc75c40

**Comment by laoneo** [comment]
Please test #20622 which should fix the issue.
