### ISSUE TITLE
[4.0] Cannot save template settings on frontend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20481]
### Steps to reproduce the issue

install sample data
login to FRONTEND as admin
Edit template settings
http://joomla-cms/index.php/working-on-your-site/template-settings?view=templates

Click save

### Expected result

Saved 

### Actual result

JSON response with error:

<img width="656" alt="screen shot 2018-05-19 at 21 21 05" src="https://user-images.githubusercontent.com/400092/40272748-8edc6224-5baa-11e8-8a25-9d7b30f9e26e.png">

### System information (as much as possible)
79fd94942e1758cff32da7f8f368b5f78cc75c40

**Comment by brianteeman** [comment]
Confirmed

**Comment by laoneo** [comment]
Please test #20620 which should fix the issue.
