### ISSUE TITLE
[4.0] Cannot view/edit versions in frontend modal

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20488]
### Steps to reproduce the issue

install 4.0-dev at 79fd94942e1758cff32da7f8f368b5f78cc75c40
install sample data
login to frontend as super admin
edit an article
click versions

### Expected result

Modal with versions to select

### Actual result

Error in modal

![screen recording 2018-05-19 at 09 55 pm](https://user-images.githubusercontent.com/400092/40272965-7b64c542-5baf-11e8-8895-314a0bde0c23.gif)

### System information (as much as possible)
79fd94942e1758cff32da7f8f368b5f78cc75c40
Google Chrome

**Comment by brianteeman** [comment]
Confirmed - Invalid controller class: display

**Comment by brianteeman** [comment]
closed see #21208
