### ISSUE TITLE
[4.0] No consistancy of button color or placement when frontend editing

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20486]
### Steps to reproduce the issue

edit a module and edit site settings and edit articles on the frontend

### Expected result

Consistent save/close/button placements either at the top or bottom
Consistent colors 

### Actual result

Site settings/module edit buttons at top of the content
<img width="704" alt="screen shot 2018-05-19 at 21 34 46" src="https://user-images.githubusercontent.com/400092/40272856-972e1c2c-5bac-11e8-9358-acdef9aa46df.png">

Article save/close at bottom of the page
<img width="1141" alt="screen shot 2018-05-19 at 21 34 40" src="https://user-images.githubusercontent.com/400092/40272857-a3da7d3a-5bac-11e8-9ebe-01f6258ec549.png">

### System information (as much as possible)

79fd94942e1758cff32da7f8f368b5f78cc75c40
Google Chrome

**Comment by Quy** [comment]
Button color fixed in #20653

**Comment by ghost** [comment]
closed as having Pull Request #20653

**Comment by brianteeman** [comment]
Reopened - the PR only deals with the colour not the position
