### ISSUE TITLE
[4.0] template preview JS error

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20492]
### Steps to reproduce the issue

install 4.0-dev at 79fd94942e1758cff32da7f8f368b5f78cc75c40
login to admin
go to template manager
click templates
click the image

### Expected result

No JS error

### Actual result

JS Error

```
multiselect.min.js?132339e72563fafc2a9b345f445e4d39:1 Uncaught TypeError: Cannot read property 'checked' of null
```

![screen recording 2018-05-19 at 10 08 pm](https://user-images.githubusercontent.com/400092/40273067-2c0dfdfe-5bb1-11e8-85e0-1538fbf09366.gif)

### System information (as much as possible)

79fd94942e1758cff32da7f8f368b5f78cc75c40
Google Chrome

**Comment by brianteeman** [comment]
Confirmed

> Uncaught TypeError: Cannot read property 'checked' of null
    at HTMLTableRowElement.<anonymous> (multiselect.min.js?2ae4f040de3e2b7f3648fff8bc40ba1f:1)
(anonymous) @ multiselect.min.js?2ae4f040de3e2b7f3648fff8bc40ba1f:1

**Comment by Quy** [comment]
Please test PR #20659<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20492">issues.joomla.org/tracker/joomla-cms/20492</a>.</sub>
