### ISSUE TITLE
[4.0] Cannot create template overrides with admin

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20494]
### Steps to reproduce the issue

install 4.0-dev at 79fd949
go to template manager
click "Cassiopeia Details and Files"
go to Create overides tab
click a file to overide

### Expected result

No error - a file is created and possibly im in an edit mode of it

### Actual result

`Class 'Joomla\Filesystem\FilesystemHelper' not found`

![screen recording 2018-05-19 at 10 16 pm](https://user-images.githubusercontent.com/400092/40273118-3d944b18-5bb2-11e8-8f50-f7c30b9b942a.gif)

### System information (as much as possible)

79fd949

**Comment by laoneo** [comment]
This should be fixed when #20305 is merged into 4.0-dev.

**Comment by brianteeman** [comment]
Closed as fixed by the upstream merge of #20305
