### ISSUE TITLE
[4.0] Cannot insert contact in editor in admin - js issue

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20495]
### Steps to reproduce the issue

Attempt to insert a CONTACT using the CMS Content dropdown in the editor in admin when editing a **CUSTOM MODULE** 
Select the contact from the list in the modal

### Expected result

The modal closes

### Actual result

JS issue 

`Uncaught TypeError: window.parent.jModalClose is not a function`

![screen recording 2018-05-19 at 10 19 pm](https://user-images.githubusercontent.com/400092/40273136-ba5be2aa-5bb2-11e8-8cd6-3ddbc5538010.gif)

### System information (as much as possible)

79fd949

similar to https://github.com/joomla/joomla-cms/issues/20496 BUT DIFFERENT ENOUGH to raise different issue as different error message and probable cause

**Comment by brianteeman** [comment]
Cannot replicate

**Comment by brianteeman** [comment]
oops pressed the wrong button

**Comment by PhilETaylor** [comment]
are you attempting it in a CUSTOM MODULE ? or editing an article?

**Comment by brianteeman** [comment]
can not replicate

![contct](https://user-images.githubusercontent.com/1296369/40273612-0dd4eb86-5bbb-11e8-818b-42133724b313.gif)

**Comment by dgrammatiko** [comment]
There is  PR for this (although WIP, as we haven't decided yet the actual API): https://github.com/joomla/joomla-cms/pull/19830

**Comment by dgrammatiko** [comment]
> but this should work until the modals are redone.

So here is the actual situation: we removed the moo tools code and effectively the method jModalClose. We need a replacement for it and although it is painful to see things break, it is far more wise to get the API correctly for the entire life of J4.

**Comment by PhilETaylor** [comment]
ok - well this is still broken and still a valid issue then - albeit with a known cause. 

Strange that code is being committed (or in this case removed) and the build being left in a broken state. 

Other modals are closing ok - so there should be an easy fix to close this modal... like the others.

**Comment by dgrammatiko** [comment]
> Other modals are closing ok - so there should be an easy fix to close this modal... like the others.

Not true, switch to codemirror and observe that none of the modals actually close. Anyways alpha is not about quick fixes, as I said the API needs to be the best we can provide as it's gonna last for the entire life of J4

**Comment by PhilETaylor** [comment]
so you were happy to fix in https://github.com/joomla/joomla-cms/pull/15894 but no longer happy to do the same so that the build is stable and that people can actually use the few modals that currently dont close...? 

bedtime

**Comment by dgrammatiko** [comment]
https://github.com/joomla/joomla-cms/pull/19830 is still open once this get's merged all modals will be fixed, The PR you mentioned was the one that ended up breaking because I was solving too many issues at one pr.

**Comment by mbabker** [comment]
We can't keep applying bandaid quick fixes to keep something usable until its replacement is fully ready, we don't have the time or resources to be doing that.  We know it's broken, we know what the replacement is, help test/review said replacement so the issue gets fixed, or look for the dozen or so of us working on all these things to have less time to spend on things because we're working on bandaid quick fixes.

**Comment by brianteeman** [comment]
Closing this as it will be resolved by #19830
