### ISSUE TITLE
[4.0] PHP Error when trying to select category of user notes

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20498]
### Steps to reproduce the issue

install from 4.0-dev at 79fd949
login as super admin to admin
go to user notes and try and add a new user note
next to category click select

### Expected result

a modal with stuff to select 

### Actual result

Error: `Call to undefined method UsersHelper::countItems()`

<img width="816" alt="screen shot 2018-05-19 at 22 33 28" src="https://user-images.githubusercontent.com/400092/40273244-acde5e80-5bb4-11e8-85d9-b5bf17c5baab.png">

![screen recording 2018-05-19 at 10 31 pm](https://user-images.githubusercontent.com/400092/40273242-a0076d32-5bb4-11e8-982e-c87f015dd18b.gif)

### System information (as much as possible)

79fd949

**Comment by laoneo** [comment]
Please test #20505 which should fix the issue.
