### ISSUE TITLE
[4.0] Template preview needs center align in one place

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20493]
see

![screen recording 2018-05-19 at 10 09 pm](https://user-images.githubusercontent.com/400092/40273074-5961623c-5bb1-11e8-8c28-4d0ec5eb7fd2.gif)

79fd94942e1758cff32da7f8f368b5f78cc75c40
Google Chrome

**Comment by brianteeman** [comment]
Confirmed

**Comment by Quy** [comment]
PR #20565<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20493">issues.joomla.org/tracker/joomla-cms/20493</a>.</sub>
