### ISSUE TITLE
Permit admins to add Extra Unique Content Meta data

### ISSUE THREAD

**Issue by adankupapa** [joomla/joomla-cms#20501]
### Is your feature request related to a problem? Please describe.
Hope this is not a lame idea! I use Joomla to run a news website which is a google news publisher and I will like to add some extra meta tags aside the generic ones like OG tags, descriptions, keywords etc which Joomla and several plugins already make possible. The problem arises when one wants to add specific and content unique meta tags like **news_keywords** which was announced by Google somewhere in 2012 as a ranking factor for news sites. 
[https://www.metatags.org/google_news_keyword_metatag](https://www.metatags.org/google_news_keyword_metatag) . 
[https://searchengineland.com/google-announces-news-keywords-metatag-133759](https://searchengineland.com/google-announces-news-keywords-metatag-133759)

Since each news item must have its own set of unique**news_keywords** it will not be appropriate to use one set of keywords for all content as it is done under Global Config when setting general site metadata. Also, when the meta keywords field is populated under the article publishing tab, it gets rendered as **keywords** and not **news_keywords**.

`<meta name="keywords" content="keyword 1, keyword 2, Spain vs Netherlands, soccer, football">` which Google has said it ignores.

### Describe the solution you'd like
My suggestion is for Joomla to have a way to allow admins to add additional/specific and unique content meta tags or allow admins to convert the default **meta keywords** which is already available under **article publishing tab** to **news_keywords** for it to be rendered in the head section of each news article as below. Similar to how we can now switch between **modern url routing** and **legacy routing**

`<meta name="news_keywords" content="keyword 1, keyword 2, Spain vs Netherlands, soccer, football">`

### Additional context
- I tried using the language overrides system to find the specific string to change for this effect without luck. 
- I have searched the Extensions directory for a plugin that can do this without success. (maybe I didn't search well and will be extremely grateful if anyone can point me to one. )

**Comment by brianteeman** [comment]
did you know that this meta tag was dropped by google last year?

https://searchengineland.com/google-drops-support-meta-news-keywords-tag-292493

**Comment by brianteeman** [comment]
Closed for the reason I stated above
