### ISSUE TITLE
[Improvement Idea] Disable the right mousebutton popup in TinyMCE per default and/or per user action

### ISSUE THREAD

**Issue by BastianFie** [joomla/joomla-cms#20516]
With the latest Joomla Core Update an right mouse button popup was included (Context Menu) which allows to change links / tables inside the text:

![screen shot 2018-05-21 at 12 58 29](https://issues.joomla.org/uploads/1/13bdbec9bc2974e7469585ffba153253.png)

However that also broke the option to use the browser included spell aid. 

![screen shot 2018-05-21 at 13 00 12](https://issues.joomla.org/uploads/1/658adbb6c1edbc4b4a27c621f7588ad2.png)

So since the update the users couldn´t any longer right click on the red underlined word and choose the correct one and most of them (at least all of my user) got very upset due to that... The admin can disable the context menu (if he knows that this was added) in the TinyMCE options. But for most administrators / users this is a unexpected change I think.

So I think that this option should be disabled per default as it broke the way how user work with TinyMCE since many years. Additional I think we should put an icon in the TinyMCE menu where the user can enable that on there own without any administrator (in the case that this is a hosted Joomla installation). The reason is that I think the spell aid would be used very often and the usage from the new context menu is very limited, so disabling that new freature per default would be a better way to bring that into Joomla.

So this improvement would like to:

- Disable the Context Menu per default during new installation or any upgrade from an older Joomla where this feature wasn´t already enabled / used.

(and /) or

- Add an option in the TinyMCE menu, where the user itself can enable or disable the Context Menu (it should be disable per default and the user can enable it)

**Comment by brianteeman** [comment]
TinyMCE in Joomla3 has not been updated in a long time

**Comment by dgrammatiko** [comment]
Sorry this is not true:
![screen shot 2018-05-21 at 18 06 24](https://user-images.githubusercontent.com/3889375/40317436-c8c2ffd4-5d21-11e8-8133-b3d1c41c3e4d.png)
![screen shot 2018-05-21 at 18 06 02](https://user-images.githubusercontent.com/3889375/40317441-cb81bb20-5d21-11e8-9d84-4645c157c341.png)


can someone close this?

**Comment by infograf768** [comment]
FYI, here on Macintosh, right-click displays TinyMCE stuff while Control-click displays the usual other stuff
