### ISSUE TITLE
[postinstall] `Updated site security recommendations` link 404

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#20517]
### Steps to reproduce the issue
Go to
https://docs.joomla.org/Special:MyLanguage/J3.x:Joomla_3.8.8_notes_about_the_changed_default_settings

Will this be published on released date?

### Actual result
404 Error - Page not found

### System information (as much as possible)
v3.8.8 RC

**Comment by mbabker** [comment]
Yes it will be published by the time we release.
