### ISSUE TITLE
[4.0] Web Component polyfill gives JS Error in Chrome

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#20511]
### Steps to reproduce the issue
Use installer 

### Expected result
No console errors

### Actual result
![image](https://user-images.githubusercontent.com/1986000/40305422-6b08fe7c-5cf2-11e8-92c4-ca2b7a98aea3.png)

### System information (as much as possible)
Chrome 66

### Additional comments
@dgrammatiko

**Comment by dgrammatiko** [comment]
@wilsonge https://github.com/joomla/joomla-cms/pull/20512
My bad

**Comment by ghost** [comment]
closed as having Pull Request #20512
