### ISSUE TITLE
Incorrect links returned by search

### ISSUE THREAD

**Issue by waveywhite** [joomla/joomla-cms#20518]
### Steps to reproduce the issue

Use the old-style router
Create categories and corresponding menus (we use a combination of article lists and blogs)
Search for a keywords from an article or category

### Expected result

Returned links should be relative to the menus

### Actual result

Returned links are not related to the menus

### System information (as much as possible)

Joomla 3.8.7

### Additional comments

We were having problems with broken links from our own layout and found the issue was related to joomla-cms/components/com_content/helpers/route.php, which had new code unhelpfully including layouts when not necessary. This looks to have been resolved in the latest version, not yet release.

Could that bug in route.php also cause this problem we're finding with search results?

**Comment by brianteeman** [comment]
from the information described it is impossible to answer.

you should know that if you have more than one way (menu) to reach an article then the one with the lowest itemid will always be returned

**Comment by waveywhite** [comment]
Yes, sorry. Was a bit unclear.

We're getting search results links formatted like this:

/122-fines-and-penalties?layout=
/122-fines-and-penalties/826-fine-penalties-data-protection-policy

When the fines-and-penalties category has a legitimate menu at /legal/fines-penalties

So, there's no menu for the results. Needless to say it's a bit of a disaster. The target links pick up the home page as the default menu, unfortunately the home page has a lot of other stuff going on and the copy is buried. This wasn't happening before.

**Comment by ghost** [comment]
@waveywhite "?layout=" looks like fix by #20229 if you wanna check?

**Comment by waveywhite** [comment]
Hi @franz-wohlkoenig 
That sorted the layout= issue.

I also found that the menu structure had a problem which was contributing as well, so our mistake there.

-David.
