### ISSUE TITLE
ContentHelperRoute::getCategoryRoute -> minor bug in categories URLs

### ISSUE THREAD

**Issue by joomlabeat** [joomla/joomla-cms#20527]
### Steps to reproduce the issue
I noticed a minor issue in mod_articles_categories module, for the Categories URLs, because of the way `ContentHelperRoute::getCategoryRoute` handles the `$layout` from `$jinput`. 
Not sure if this bug appears anywhere else where `ContentHelperRoute::getCategoryRoute` is called, but for the mod_articles_categories we get URLs like below in cycles, depending from where we view the categories and when there is no menu-item for those categories to define a layout. 
```
index.php?option=com_content&view=category&id=12&layout=&Itemid=119
index.php?option=com_content&view=category&id=12=&Itemid=119
```
Notice that the **layout** param in the first occasion is just empty, which with SEF on it ends up to URLs like below:
/blog/nature/16-animals?layout=
/blog/nature/16-animals

To reproduce this, create an articles categories module for a category tree e.g. you have a blog category and subcategories. Create menu items for the parent categories and just let the children without menu items. Place the module in all pages (articles, featured items and even other component), so to make sure there isn't a `$layout` for the categories view defined. 
Start clicking on your module's categories links from your various pages and you will notice the non-constant URLs.

### Expected result
Categories URLs should be the same for the same categories.

### Actual result
Categories URLs toggles as described above, depending on the $layout param.

### System information (as much as possible)
Joomla 3.8.7

### Additional comments
The issue appears to be in the way `ContentHelperRoute::getCategoryRoute` deals with the layout param from `$jinput`  

> /components/com_content/helpers line 82 - 88:
```
$jinput = JFactory::getApplication()->input;
			$layout = $jinput->get('layout');

			if ($layout !== '')
			{
				$link .= '&layout=' . $layout;
			}

```
At line 85, it does a strict comparison for `$layout !== ''` and if it's not, then it appends it to the URL. But this is not always the case, as I don't know about other cases, in those that I tested it out, $layout came back as null. So the $layout !== '' results to true.

I think that unless we are expecting a layout to equals to "0", we could go with:

`if (!empty($layout))`

**Comment by joomlabeat** [comment]
Also - not sure about this - but what about in the case of a missing $layout for a category to default to the categories/global params?

**Comment by infograf768** [comment]
I think we already have a PR for this, can't remember which one

**Comment by ghost** [comment]
closed as fixed by #20229

**Comment by Quy** [comment]
Fixed in #20229<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20527">issues.joomla.org/tracker/joomla-cms/20527</a>.</sub>

**Comment by infograf768** [comment]
Thanks folks... my memory is not what it was... ;)

**Comment by joomlabeat** [comment]
I searched for this, but didn't find anything at first place. Now reading #20229 
Have a good day!
