### ISSUE TITLE
[4.0] Installation broken when debug lang is set

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#20524]
### Steps to reproduce the issue
Install a clean joomla 4.0-dev after setting the `installation/localise.xml` file to debug
```
<?xml version="1.0" encoding="utf-8"?>
<localise version="3.6" client="installation">
	<forceLang></forceLang>
	<helpurl></helpurl>
	<debug>1</debug>
	<sampledata></sampledata>
	<params/>
</localise>
```

### Expected result
Installation is possible

### Actual result
Installation fails on third page `Database Configuration`
We get in a loop with this error

```
SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 311 of the JSON data[Learn More]
setup.js:86:15
onSuccess
http://localhost:8888/newfolder/joomla40/installation/template/js/setup.js:86:15
e.request/n.onreadystatechange
http://localhost:8888/newfolder/joomla40/media/system/js/core.min.js:1:7724
```

@dgrammatiko I guess

**Comment by dgrammatiko** [comment]
> SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1

Well there's no json, and the js cannot cope with this. Somehow the output becomes html instead of json. Something is broken in the php side not in the js

**Comment by laoneo** [comment]
Please test #20528.
