### ISSUE TITLE
2FA Google Authenticator reveals username

### ISSUE THREAD

**Issue by jvstratum** [joomla/joomla-cms#20529]
### Steps to reproduce the issue

Activate 2FA with Google Authenticator

### Expected result

Login with 2FA

### Actual result

Everything works ok.

### System information (as much as possible)

n/a

### Additional comments
Once activated Google Authenticator app reveals username. The app displays "username at sitename.com". 

Feature request: Display sitename only or have an option wether or not to display the username.

**Comment by brianteeman** [comment]
That is how google authenticator works

**Comment by mbabker** [comment]
Even if it were practical to mask the username, you're screwed if you ever have two accounts for the same site/service in your Authenticator app (i.e. SiteGround does list their's only as "SiteGround.com", at least as of when I added 2FA, whereas every other service is either only my username or username at site URL).

So I'd personally call this expected/preferred behavior.
