### ISSUE TITLE
module random image after Joomla 3.8.8. update causes white page in front end

### ISSUE THREAD

**Issue by schildmi** [joomla/joomla-cms#20531]
### Steps to reproduce the issue

Updating joomla from 3.8.7 to 3.8.8. Using the module random image.

### Expected result

A normal view to th website...

### Actual result

The frontend is only white...

### System information (as much as possible)

OS: Debian
Webserver: Apache 
PHP: 7.1

### Additional comments

Using Joomla debug mode there comes the following error message in the frontend:

Fatal error: Using $this when not in object context in .../modules/mod_random_image/tmpl/default.php on line 16

If the random image module is disabled everything is fine.

**Comment by mbabker** [comment]
@joomla/security This is a result of the com_media hardening...

**Comment by schildmi** [comment]
And that means what...? Is there a possible to solve this case?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20531">issues.joomla.org/tracker/joomla-cms/20531</a>.</sub>

**Comment by PhilETaylor** [comment]
The issue is confirmed and the @joomla/security team are on the case.

**Comment by carlitorweb** [comment]
@schildmi mean, need wait a bit

**Comment by mbabker** [comment]
See https://github.com/joomla/joomla-cms/pull/20533

**Comment by schildmi** [comment]
Great!!! Thanks a lot!!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20531">issues.joomla.org/tracker/joomla-cms/20531</a>.</sub>

**Comment by zero-24** [comment]
FAQ Page: https://docs.joomla.org/J3.x:Module_random_image_PHP_Error_after_3.8.8

**Comment by brianteeman** [comment]
Does the jsst never test things. Always the same story on every security release :(

**Comment by SniperSister** [comment]
The patch in question was tested by 2 team members, but apparently the random image module slipped trough :(

**Comment by infograf768** [comment]
Looks like that module is not part of any default sample data. I know I never used it...
