### ISSUE TITLE
Upgrade to 3.8.8 breaks mod_random_image

### ISSUE THREAD

**Issue by prh47bridge** [joomla/joomla-cms#20535]
### Steps to reproduce the issue

1 - Set up a Joomla 3.8.7 site using mod_random_image to display random images in a location on the home page.
2 - Upgrade to Joomla 3.8.8.

### Expected result

Site still works with no changes.

### Actual result

Site crashes with error "Using $this when not in object context". Debug reveals that the problem is mod_random_image. Disabling mod_random_image results in site working again (although, obviously, the random image is now missing).

### System information (as much as possible)

Linux 16.04.4 LTS
PHP 7.0.30
Apache 2.4.18
MySQL 5.7.22

### Additional comments

I have not tested a fresh installation so I am unclear if the problem is with mod_random_image or the upgrade package. Either way, as mod_random_image is bundled with Joomla, my view is that a fixed version needs to be released ASAP.

**Comment by carlitorweb** [comment]
Duplicated. See #20533
