### ISSUE TITLE
[4.0] Http\Response doesn't include the body information

### ISSUE THREAD

**Issue by tassosm** [joomla/joomla-cms#20537]
### Steps to reproduce the issue
It seems that Http\Response no longer returns the body info in Joomla 4. 
For instance. Let's say we want to connect to Github API without providing credentials. 

```
$url = 'https://api.github.com';
$options = [];
$data = [];
	
$http = JHttpFactory::getHttp(new JRegistry($options));
$response = $http->get($url, $data);

echo $response->body;
```
### Expected result
In Joomla 3.8.7 we get the following error and therefore we know what's going wrong with the call.

`Request forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes. `

### Actual result
However, in Joomla 4 we get the following array with no information about the error.

`{"current_user_url":"https://api.github.com/user","current_user_authorizations_html_url":"https://github.com/settings/connections/applications{/client_id}","authorizations_url":"https://api.github.com/authorizations","code_search_url":....
`
### System information (as much as possible)
PHP 7.1.11-1+ubuntu14.04.1+deb.sury.org+1 
Joomla! 4.0.0-alpha4-dev Development

**Comment by PhilETaylor** [comment]
Thats because the result in Joomla 4 is the EXPECTED response to a valid GET of https://api.github.com with no query params or auth. 

The actual error is that Joomla 3 doesnt seem to send a user agent header 

(Reading your post alone, not tested the code)

**Comment by ghost** [comment]
changed Title to make clear its about 4.0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20537">issues.joomla.org/tracker/joomla-cms/20537</a>.</sub>

**Comment by PhilETaylor** [comment]
There is nothing to fix in 4.0

**Comment by ghost** [comment]
@PhilETaylor so the reported Issue is not about 4.0?

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/pull/16538 changed the HttpFactory in 4.0 to default set a User-Agent.  So if you expected an error because of that, it no longer happens in 4.0.

So, what you're seeing is as expected.

**Comment by PhilETaylor** [comment]
see: 
https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Http/Transport/CurlTransport.php#L65

As you can see the default is null for user agent

This has been changed in Joomla 4 to set a user agent by default.

**Comment by PhilETaylor** [comment]
ah you beat me to it :)

**Comment by tassosm** [comment]
OK, thanks, guys. 

I am aware of the change in J4. I was confused since in my actual code I am checking whether $response->body is set and in Joomla 4 always returns false even though it's there.

**Comment by PhilETaylor** [comment]
But that is not what you said in your issue... 

You said 

> However, in Joomla 4 we get the following array...

Now you are saying 

> Joomla 4 always returns false 

Confused much

**Comment by mbabker** [comment]
There are some other minor structural tweaks since our Response object is now a subclass of https://github.com/zendframework/zend-diactoros/blob/master/src/Response.php (and inherently PSR-7 compatible), but beyond that what's in the three main attributes (headers, body, code) should still be mostly the same when going through the magic getters (the one hard B/C break is headers is now always an array).

**Comment by PhilETaylor** [comment]
In Joomla 4.0-dev

Running this code: 

```
$url = 'https://api.github.com';
$options = [];
$data = [];
	
$http = JHttpFactory::getHttp(new JRegistry($options));
$response = $http->get($url, $data);

echo $response->body;
```

I get 

```
{"current_user_url":"https://api.github.com/user","current_user_authorizations_html_url":"https://github.com/settings/connections/applications{/client_id}","authorizations_url":"https://api.github.com/authorizations","code_search_url":"https://api.github.com/search/code?q={query}{&page,per_page,sort,order}","commit_search_url":"https://api.github.com/search/commits?q={query}{&page,per_page,sort,order}","emails_url":"https://api.github.com/user/emails","emojis_url":"https://api.github.com/emojis","events_url":"https://api.github.com/events","feeds_url":"https://api.github.com/feeds","followers_url":"https://api.github.com/user/followers","following_url":"https://api.github.com/user/following{/target}","gists_url":"https://api.github.com/gists{/gist_id}","hub_url":"https://api.github.com/hub","issue_search_url":"https://api.github.com/search/issues?q={query}{&page,per_page,sort,order}","issues_url":"https://api.github.com/issues","keys_url":"https://api.github.com/user/keys","notifications_url":"https://api.github.com/notifications","organization_repositories_url":"https://api.github.com/orgs/{org}/repos{?type,page,per_page,sort}","organization_url":"https://api.github.com/orgs/{org}","public_gists_url":"https://api.github.com/gists/public","rate_limit_url":"https://api.github.com/rate_limit","repository_url":"https://api.github.com/repos/{owner}/{repo}","repository_search_url":"https://api.github.com/search/repositories?q={query}{&page,per_page,sort,order}","current_user_repositories_url":"https://api.github.com/user/repos{?type,page,per_page,sort}","starred_url":"https://api.github.com/user/starred{/owner}{/repo}","starred_gists_url":"https://api.github.com/gists/starred","team_url":"https://api.github.com/teams","user_url":"https://api.github.com/users/{user}","user_organizations_url":"https://api.github.com/user/orgs","user_repositories_url":"https://api.github.com/users/{user}/repos{?type,page,per_page,sort}","user_search_url":"https://api.github.com/search/users?q={query}{&page,per_page,sort,order}"}



```

**Comment by PhilETaylor** [comment]
This would give `false`

```php
var_dump(isset($response->body));
```

**Comment by mbabker** [comment]
There is no longer a `$body` attribute.  As of 4.0 use of `$response->body` is deprecated (to be removed in Framework 3.0 and CMS 5.0) in favor of the PSR-7 ResponseInterface's API.

If it's decided this is worth patching, we'd need a `__isset()` method in https://github.com/joomla-framework/http/blob/2.0-dev/src/Response.php but to be honest I don't see the value here.  Generally with Response objects you should first validate the response code isn't an error (4xx or 5xx) then check if the response body is empty before continuing on; isset checks aren't efficient here.

**Comment by tassosm** [comment]
@PhilETaylor you're right. I was really confused in the first place.
@mbabker now it's more clear. Thanks.
