### ISSUE TITLE
Update Joomla 3.8.8 gives white screen on the site

### ISSUE THREAD

**Issue by DrHouse44** [joomla/joomla-cms#20538]
After the update to joomla 3.8.8 I get a white screen.
The error report once put on development.
Then I get the following error: Fatal error: Using $this when not in object context in C:\xampp\htdocs\Joomla\Joomla\mod_random_image\tmpl\default.php online 16
Luckily I had another backup and went to see what has changed in that file.

Before the update there was this:
`<?php
/**
 * @package     Joomla.Site
 * @subpackage  mod_random_image
 *
 * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;
?>
<div class="random-image<?php echo $moduleclass_sfx; ?>">
<?php if ($link) : ?>
<a href="<?php echo $link; ?>">
<?php endif; ?>
	<?php echo JHtml::_('image', $image->folder . '/' . $image->name, $image->name, array('width' => $image->width, 'height' => $image->height)); ?>
<?php if ($link) : ?>
</a>
<?php endif; ?>
</div>`

After the update, this will be displayed:
`<?php
/**
 * @package     Joomla.Site
 * @subpackage  mod_random_image
 *
 * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;
?>
<div class="random-image<?php echo $moduleclass_sfx; ?>">
<?php if ($link) : ?>
<a href="<?php echo $link; ?>">
<?php endif; ?>
	<?php echo JHtml::_('image', $image->folder . '/' . $this->escape($image->name), $this->escape($image->name), array('width' => $image->width, 'height' => $image->height)); ?>
<?php if ($link) : ?>
</a>
<?php endif; ?>
</div>`

And if I restore the file "default.php" before the update, the site will just work properly again.
The upgrade package once separately downloaded and in that file that file is also adjusted.

Is this an error in the Joomla update?

So I tried out Xampp locally first, I'm still waiting to update on the server.

**Comment by PhilETaylor** [comment]
https://docs.joomla.org/J3.x:Module_random_image_PHP_Error_after_3.8.8

**Comment by brianteeman** [comment]
This is a duplicate report and has been fixed with #20533

**Comment by DrHouse44** [comment]
okay sorry for the double post
