### ISSUE TITLE
Validate Deleted Files List

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#20530]
This is moreso a reminder for myself than anything.

Today I found a directory that shipped in 3.0 and was moved in 3.1 was never added to the deleted files array in the update script so those files were never removed from those sites.

Validate the array is in expected state and fix it if not (use the script in build directory for this).

**Comment by brianteeman** [comment]
Pretty sure that @alexred reviewed this not too long ago but only starting at about 3.4

**Comment by mbabker** [comment]
Well, clearly that wasn't enough then 😉

With https://github.com/joomla/joomla-cms/blob/staging/build/deleted_file_check.php it's actually much simpler to do now than when he did it (I only did that script fairly recently to make sure all the 3.8 stuff was right with the namespacing and moving 300 files).

**Comment by brianteeman** [comment]
so are we ok now?

**Comment by mbabker** [comment]
At least for that batch of files I added just before release today, yes.  It'd still be good to run that script in batches and make sure what it spits out (which is the result of git diff and tracking renames and deletes) matches what we have in the array for each branch (for the most part if someone other than me runs it you should be able to paste the output directly into the array and things just work, you just need to make sure deleted folders are added to the second list in the end), just to make sure we don't run into anymore potential "this doesn't work because I'm using the files from 3.0.3 while I'm on 3.8.7" problems.

**Comment by mbabker** [comment]
PR #20564
