### ISSUE TITLE
Can't create submenu in component by core function "JHtmlSidebar"

### ISSUE THREAD

**Issue by Mausino** [joomla/joomla-cms#20532]
### Steps to reproduce the issue

I got message from my developer

" we are using the joomla core function "JHtmlSidebar" and for now it don't support the submenu layout"

### Expected result

I can create submenus in by joomla function

### Actual result

Can't use joomla framework for creating of submenu

### System information (as much as possible)

Joomla 3.8.7 
Php 7.2.5
MySQL 5.6

**Comment by carlitorweb** [comment]
I do not understand very well. In your custom component not work something? Is related to Joomla?

**Comment by tonypartridge** [comment]
JHTMLsidebar doesn’t have that facility and if you want it just add your own custom menu with sub menus?

Or your developer can do a pull request to the CORE to add such features

**Comment by ghost** [comment]
Closed as above stated. 

@Mausino if needed please ask help on the [forums](https://forum.joomla.org/).
