### ISSUE TITLE
Random Image module is broken after updating to Joomla 3.8.8

### ISSUE THREAD

**Issue by htmgarcia** [joomla/joomla-cms#20540]
### Steps to reproduce the issue
- Be sure your site is updated to Joomla 3.8.8
- Create a "Random Image" module
- Preview in frontend to reach the error

### Expected result
Module should work in frontend with no problems

### Actual result
There is an error that breaks the frontend:
> Using $this when not in object context

### System information (as much as possible)
Chrome Version 66.0.3359.181
macOS High Sierra 10.13.4

**Comment by carlitorweb** [comment]
Duplicated. Fixed on #20533

**Comment by htmgarcia** [comment]
@carlitorweb thanks!
