### ISSUE TITLE
random image module breaks joomla

### ISSUE THREAD

**Issue by grotego** [joomla/joomla-cms#20545]
### Steps to reproduce the issue

when random image module is activated on joomla 3.8.8 website breaks

### Expected result

only code <div class=\"random-image\"> will be shown

### Additional comments

my solution : remove $this->slaches() from the mod_random_image/tmpl/default.php file

**Comment by brianteeman** [comment]
https://docs.joomla.org/J3.x:Module_random_image_PHP_Error_after_3.8.8
