### ISSUE TITLE
JDocument addScriptOptions in module - script won't be injected when global cache is on

### ISSUE THREAD

**Issue by joomlabeat** [joomla/joomla-cms#20546]
### Steps to reproduce the issue
Maybe I got it wrong here with "optionsStorage". I thought it's a mechanism to send logic data to the client side. So, I add my script options from inside my module to be used by the module's js. Everything works fine until I enable global cache and refresh the page.

### Expected result
Expecting the script to appear in the head of the document.

### Actual result
With the second load of the page with the cache on, the script isn't there anymore.

### System information (as much as possible)
Tested on Joomla 3.7.3 and 3.8.7

### Additional comments
Disabling the module from caching has no effect

**Comment by csthomas** [comment]
It may present the same problem as in case https://github.com/joomla/joomla-cms/issues/11203

**Comment by ghost** [comment]
closed as having Pull Request #21007
