### ISSUE TITLE
ERROR:  The archive file is corrupt, truncated, or archive parts are missing

### ISSUE THREAD

**Issue by charleyhankins** [joomla/joomla-cms#20554]
### Steps to reproduce the issue
Upgraded my PHP version to 7.0

### Expected result
Expected the Joomla version to upgrade from 3.8 to 4.0

### Actual result
ERROR:  The archive file is corrupt, truncated, or archive parts are missing

### System information (as much as possible)
Joomla 3.8.8
PHP Version 7.0.30

**Comment by zero-24** [comment]
> Expected the Joomla version to upgrade from 3.8 to 4.0

There is **no** stable release of 4.0 yet ;)

What update server did you use?
Did you updated to 3.9 dev version first (this is required).

Thanks.

**Comment by ghost** [comment]
@charleyhankins maybe a Look at https://developer.joomla.org/roadmap.html can give also Information.

**Comment by brianteeman** [comment]
not even sure if it is possible to do an "upgrade" yet

**Comment by charleyhankins** [comment]
I had not updated to 3.9.  Thanks for the info.

I was going to try out the 4.0 Alpha
[https://www.joomla.org/announcements/release-news/5718-joomla-4-0-alpha-1-release.html](https://www.joomla.org/announcements/release-news/5718-joomla-4-0-alpha-1-release.html)

Thanks!
CH

**Comment by zero-24** [comment]
https://developer.joomla.org/news/727-joomla-4-is-on-the-horizon.html

Alpha3 is the latest version and there are no update path setup done yet ;) So you can new install but not updating a new site.
