### ISSUE TITLE
[FEATURE REQUEST] Privacy tools to Joomla 3.9 Need to store user ID on delete

### ISSUE THREAD

**Issue by saraheagle** [joomla/joomla-cms#20552]
Hello, if this is not the right place to post this, just let me know.

Hopefully you will be storing the ID of the user that has deleted their data and the date that the date was deleted.

This will be needed if a site is restored from Akeeba backup. Site admins will need to find any users that have deleted their data and run the privacy tool in the admin area to make sure the data has been deleted again.

Thank you
Sarah

**Comment by Quy** [comment]
Please post here: https://github.com/joomla-projects/privacy-framework<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20552">issues.joomla.org/tracker/joomla-cms/20552</a>.</sub>
