### ISSUE TITLE
[4.0] Login module has no JS validation 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20558]
### Steps to reproduce the issue

install 4.0-dev at 7b2929924429e90a4f85e9990afe72d2db0d93b8
install demo content
visit frontend 
blur though the login forms, both the right hand module and the left hand com_users login boxes

### Expected result

Both experiences should be the same with Javascript validation on blur

### Actual result

Module doesnt have JS validation

![screen recording 2018-05-23 at 09 17 pm](https://user-images.githubusercontent.com/400092/40448952-f1c9b0ae-5ece-11e8-89e2-ffef1cbed16f.gif)

### System information (as much as possible)
7b2929924429e90a4f85e9990afe72d2db0d93b8
GC

**Comment by dgrammatiko** [comment]
PR: https://github.com/joomla/joomla-cms/pull/19231

**Comment by brianteeman** [comment]
Closed
