### ISSUE TITLE
[4.0] stats collection link JS issue

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20557]
### Steps to reproduce the issue

install from 4.0-dev at 7b2929924429e90a4f85e9990afe72d2db0d93b8
login to admin

### Expected result

No JS error

### Actual result
<img width="1063" alt="screen shot 2018-05-23 at 21 02 40" src="https://user-images.githubusercontent.com/400092/40448274-f43707c6-5ecc-11e8-85eb-8cf983bc8a63.png">
JS Error

```
Uncaught TypeError: Cannot read property 'classList' of null
    at HTMLDocument.<anonymous> (stats-message.min.js?8c0b6da4f24486887dc747f65a4ecb74:1)
```
### System information (as much as possible)

7b2929924429e90a4f85e9990afe72d2db0d93b8
GC

**Comment by PhilETaylor** [comment]
Idea binned due to ideological adherence to wrong decisions taken by a conversation of 3 in a non joomla/joomla-cms repository years ago.... 

https://github.com/joomla/joomla-cms/pull/23033#issuecomment-437717721

Another PR binned.

**Comment by PhilETaylor** [comment]
Issue reopened after culling all mention of the "Select here to view" issue and concentrating on the fact there is a Javascript issue on the page.

**Comment by Quy** [comment]
Please test PR #23727<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20557">issues.joomla.org/tracker/joomla-cms/20557</a>.</sub>
