### ISSUE TITLE
Article options not working

### ISSUE THREAD

**Issue by Jaironlanda** [joomla/joomla-cms#20566]
### Steps to reproduce the issue
1) Create new article.
2) Change article option **Show Hits** to **Hide**
3) Click save button 

### Expected result
Hit disappear in article

### Actual result
Hit still showing up. Except, Edit global options.  

### System information (as much as possible)
Joomla version : 3.8.8

### Additional comments
I think all article options have problem. Example: Show Author, Show Category, Show Publish Date, Show Title etc.

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.
