### ISSUE TITLE
website is really dead slow after upgrading from 3.8.7 to 3.8.8

### ISSUE THREAD

**Issue by mfarooqi** [joomla/joomla-cms#20560]
I don't know how to report this issue, but I'm facing real dead slow response after upgrading to 3.8.8. 

### Steps to reproduce the issue
Because we already have a lot of data in VM... 
but you can install 
Joomla-3.8.2 first 
And install VirtueMart-3.2.8.. 
and a lot of data in VM
now upgrade to 3.8.7
and upgrade to 3.8.8

### Expected result
Website should begin loading page right after pressed "Refreshed button" or clicked on any "link" ... and it should take as long as it need when downloading..  

### Actual result
When pressed "Refresh button" or hit enter after typing URL..  it takes 10s of seconds in connecting even on localhost and then starts loading.

### System information (as much as possible)
PHP Version 5.6.10
System	Darwin Muhammads-MacBook-Pro.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar 5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
Server API	Apache 2.0 Handler
Using MAMP Pro
Macbook Pro- 10GBRAM 128GBSSD 2.3GhzCi5

### Additional comments

We are using virtuemart 3.2.8. We've been already facing slowing issue for many days after upgrading from j1.5 to j3.x. For a month around I've been debugging and trying to fix the slowing issue, but was not able to get fastest response.. but still by disabling many of modules, I had achieved good enough response.

I didn't touch the last update 3.8.7 before... but after updating to 3.8.7 around 5 days back .. there was no any big change... the response time when I used to "click" on any link or starting loading page after pressing "refresh button" waiting time was around 3, 4 seconds.. while that should start responding in a second. When I hit "refresh" in Backend (Administrator view), that works fine.

Now just around 30 minutes back.. I updated to 3.8.8.... now when I press "refresh button" or "enter" on URL that is taking  more then 10 seconds.. But on the Admin view, it's working fine. 

You may be saying that this is a VirtueMart issue, but this is the same VirtueMart with 3.8.7 or before.. I don't think this should be now all in sudden a VirtueMart issue?.

**Comment by Quy** [comment]
Please report your issue to [Joomla Forum](https://forum.joomla.org/viewforum.php?f=710).

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/) as stated by @Quy. This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.

**Comment by mfarooqi** [comment]
Alright. Thank you for the comments.
