### ISSUE TITLE
Filters are hardcoded in the form

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-cms#20569]
### What needs to be fixed
As #14189 revealed, the filters are hardcoded in the Form class.

### Why this should be fixed
It is only possible to add new filters to the form by changing the Form class.

### How would you fix it
Use the same logic as for rules where the logic resists in its own class. It is possible to dynamically add new filters.

### Side Effects expected
No.

**Comment by mbabker** [comment]
Custom callbacks are already supported [in the filterField method](https://github.com/joomla/joomla-cms/blob/56b89cedb6b9df3a7f07e25b04a0d5a0b36efcdd/libraries/src/Form/Form.php#L1548-L1576) and there is no need to change anything.

**Comment by laoneo** [comment]
True.
