### ISSUE TITLE
Joomla\Filter\InputFilter removes dash from attribute names

### ISSUE THREAD

**Issue by ryandemmer** [joomla/joomla-cms#20579]
### Steps to reproduce the issue

While logged in as a Super User:

In the Global Configuration, set the **Default Editor** to _Editor - None_.

In the Text Filters tab, set the _Filter Type_ value to **Default BlackList** for the Super User group.

Save.

Go to Content -> Articles -> Add New Article.

Give the new article a Title, and add the following HTML, or a variation of it, to the Content field:

```html
<p data-value="1">Some text</p>
```
Click the Save button.

### Expected result

The article should be save with the original content added intact.

### Actual result

The hyphen is removed from the data attribute, resulting in

```html
<p datavalue="1">Some text</p>
```

### System information (as much as possible)
Joomla 3.8.8

### Additional comments

This issue was introduced in the Joomla 3.8.8 update via commit https://github.com/joomla/joomla-cms/commit/cf4c5df286815c9c343372c7210d3aedccb6e3cb with the inclusion of line 867 in libraries/vendor/joomla/filter/src/InputFilter.php

This line should be amended to allow for the - character, eg:

```php
$attrSubSet[0] = preg_replace('/[^\p{L}\p{N}\-\s]/u', '', $attrSubSet[0]);
```

**Comment by Quy** [comment]
PR #20580

It is not necessary to create an issue if you have a PR ready.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20579">issues.joomla.org/tracker/joomla-cms/20579</a>.</sub>
