### ISSUE TITLE
Name of State or Province in Contacts

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#20576]
### Steps to reproduce the issue
In Contacts we do have a field "State or Province" it is called "State or County" in the Contact Options (tab Contact and tab List Layouts), category-options and the menus.

### Expected result
Same name

### Additional comments
In con_contact (using the same variable) or Translation (using the same content)?

**Comment by brianteeman** [comment]
Good spot. Yes they should be the same - doing a pr now

**Comment by ghost** [comment]
closed as having Pull Request #20577
