### ISSUE TITLE
Link title is vertical when using icon

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#20581]
### Steps to reproduce the issue
edit menu item. add: icon icon-edit on link class

### Expected result

The title is horizontal

### Actual result

![image](https://user-images.githubusercontent.com/876623/40568855-82a5b032-607d-11e8-9541-34ccf670b833.png)

### System information (as much as possible)

Protostar

**Comment by Quy** [comment]
Do you get the same result with the following code?

`<a title=" Forums" href="/new/forums"><span class="icon icon-edit"></span> Forums</a>`

**Comment by 810** [comment]
Then it showed correctly

**Comment by Quy** [comment]
The `icon` class has a `width: 28px;` making the `a` container to be small width where the text has to be displayed vertically. You will have to change your markup as advised.

**Comment by Quy** [comment]
Try your markup with `icon-edit` only without `icon`.

**Comment by ghost** [comment]
@Quy is this a Core Issue?

**Comment by Quy** [comment]
Closing as not a core issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20581">issues.joomla.org/tracker/joomla-cms/20581</a>.</sub>

**Comment by 810** [comment]
the issue is on the menu, so also core. You can't add now a icon on the menu item

**Comment by Quy** [comment]
Was this possible in previous versions? I had to create a custom css `.auto-width {width:auto;}` as follows `icon icon-edit auto-width` to make it work.

**Comment by SharkyKZ** [comment]
This is coming from Bootstrap and is expected. See documentation http://getbootstrap.com/2.3.2/base-css.html#icons.

The markup posted by @Quy is correct. If there's demand, 'Icon Class' option could be added to create correct markup for icons. Or you can use additional class to set the width as shown above.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20581">issues.joomla.org/tracker/joomla-cms/20581</a>.</sub>
