### ISSUE TITLE
Global Config Form not reading live Configuration

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20588]
### Steps to reproduce the issue

Install Joomla 3.8.8
Go to admin -> Global Configuration -> as a test enable DEBUG = YES - then save,

LEAVE THE GLOBAL CONFIG PAGE OPEN  (http://example.com/administrator/index.php?option=com_config)

Manually edit $debug = '0'; in /configuration.php, therefore setting debug to off

return to the Joomla admin and simply refresh the page   (http://example.com/administrator/index.php?option=com_config)

### Expected result

That the change on the file system is reflected in the interface

### Actual result

Debug is still shown as on. 
The config is loaded from the session, instead of from configuration.php

### System information (as much as possible)

Joomla 3.8.8 
Google Chrome

**Comment by dgrammatiko** [comment]
Log out and log in again should update the values

**Comment by PhilETaylor** [comment]
Thats not the point. The page should read from configuration.php and not from saved session values should they differ.

**Comment by dgrammatiko** [comment]
I think it’s done this way for performance, but I guess the edit page should always fetch from the file, so I agree here

**Comment by dgrammatiko** [comment]
Flipping the arrays here https://github.com/joomla/joomla-cms/blob/66debe9e0c3a2ccd61200620b4f4e57764a946e4/administrator/components/com_config/model/application.php#L82 should do that, I do t know if there are bad effects doing it though

**Comment by ggppdk** [comment]
That merge order seems correct

administrator/components/com_config/controller/application/save.php

is different than other controllers it always adds data into session unlike all other controllers that only add them on 

validation error
save error

Also it does not seem to clear them on successful save

**Comment by ghost** [comment]
closed as having Pull Request #20590
