### ISSUE TITLE
Multilingual websites: Issue with System - Page Cache

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-cms#20594]
On multilingual websites, with the plugin System - Page Cache enable, when I navigate through a site in any language, and then click on the logo (or title of the site), I'm redirected to the homepage in the default language, instead of being redirected on the homepage in the active language.
It happens on all my multilingual websites (3.8.8), including joomla.org/3

### Expected result
When clicking on the logo/title of the site, redirection to the homepage in the active language when the Plugin is enable

### Actual result
When clicking on the logo/title of the site, redirection to the homepage in the default language instead of the active one when the Plugin is enable.
Issue solved by disabling the Plugin.

### Additional comments
FYI, it occurs whether the router is set up on legacy or modern, with different templates and different PHP versions.

**Comment by brianteeman** [comment]
Is this new behaviour. I would expect it to be always this way with the page cache plugin enabled.

**Comment by Sandra97** [comment]
It was working correctly not that long ago on all my sites including the landing page. I'm unable to tell you right know when this issue appeared (after 3.8.7 or 3.8.8). I need to dig a bit for that.

**Comment by infograf768** [comment]
Which template are you using? The link in the logo/title may depend on the way it is coded.

**Comment by Sandra97** [comment]
The official Joomla template (for the landing page), and templates from RocketTheme, YooTheme, JoomlArt.

**Comment by Sandra97** [comment]
I did some tests from 3.8.2 to 3.8.8, with different templates. Seems it was already there in 3.8.2 but I didn't notice before. So it's maybe an (annoying) expected behaviour when the cache plugin is enabled. I just disabled it everywhere and now it's fine.

**Comment by mbabker** [comment]
It's probably an issue of the order of plugins.  If something matches what the page cache plugin has stored in the cache, it immediately serves that result and kills the Joomla application cycle.  So in this case you probably need the page cache plugin ordered after the language plugins.

**Comment by infograf768** [comment]
I tested the plugin by setting browser caching off and I did not get the issue

**Comment by Sandra97** [comment]
@infograf768 On or Off for Browser caching doesn't change anything. I have the issue as soon as the plugin is enable.
@mbabker It doesn't seem to change anything, issue is still there. 
Anyway, it's not my day! 😛

**Comment by mikeveeckmans** [comment]
i have the same issue as @Sandra97 described.

**Comment by hacki65** [comment]
I have made some tests on one of my multilanguage sites and found a possible solution. The system plugin "System - Language Filter" has an option named "Cookie Lifetime". If this option is set to "Year" **all seems to be fine**.

BUT: if i switch to a language, stay at the homepage and then click on a logo i will be redirect to the default language. If i call up a subsite (like www.my-domain.de/en/contact) a cookie will be set and all is good.

Seems to be this is a Session Cookie problem. If the option is set to "Year" Joomla! generate a seperate cookie for each language. Otherwise only 1 cookie will be set.

BTW: the ordering or cache plugin settings changed nothing.

**Comment by Sandra97** [comment]
I just did some tests with 'Year' instead of 'session', I'm still redirected to the default language instead of the active one as long as Plugin - Page cache is enabled.

**Comment by ggppdk** [comment]
> I'm redirected to the homepage in the default language

It is an issue but a bit different

One is not redirected to the "default language" instead of "active"
instead **one is redirected to the language to which the language cookie was last set ...**

**If you visit a page that has already been cached** by the System - Cache plugin,
- then the code that checks if the language cookie needs to be updated does not get executed

The language filter plugin will do this during onAfterInitialise
```php
public function onAfterInitialise()
{
...
		// Attach parse rules for language SEF.
		$router->attachParseRule(array($this, 'parseRule'), JRouter::PROCESS_DURING);
	}
}
```

but if a cached page is returned via System - Cache plugin, then 
`$this->parseRule()` which will call `$this->setLanguageCookie($lang_code);`

is never executed, thus language cookie is not updated

**Comment by brianteeman** [comment]
I am assuming that this is the same as the issue with #22099 so am closing it. If my assumption is wrong please post back and it can be reopened

**Comment by Sandra97** [comment]
It's a different issue and it remains after applying the patch, so I still can't use the cache plugin on any multilingual sites.

**Comment by ghost** [comment]
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20594">issues.joomla.org/tracker/joomla-cms/20594</a>.</sub>

**Comment by franx47** [comment]
Using **Joomla 3.9.13**, the Language Switcher bug is still exist. I have the same problem on Bi-Lingual Site (English and non-english). Default language site is non-english. Everything is fine, menu item set to each of the language.

But, everytime I published the "System - Page Cache" plugin, it starts to get in problem.

Here is the Settings: 
- Use Browser Caching: No
- Exclude Menu Items: (empty)


**# ("System - Page Cache" plugin ENABLED)**

1. When the website open, it will redirect new visitor to the default language (non-english). Everything's fine.
2. When the user change the default language (non english) to English, it will redirect the user to the English page. Everything's good.
3. But when the user click the website logo or HOME menu, the site redirects back to the non-english page. Ofcourse this is incorrect. It still has to be in the English page.

I disabled the "System - Page Cache" plugin, the problem goes away.

Btw, "System - Page Cache" plugin has a good impact on Joomla page speed. Combined with JCH Optimize and System Cache (ON-Conservative).

Please, someone helps to patch this.

Thank you.

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

I have verified that this is resolved in Joomla 4 and this will now been closed.

cc @zero-24
