### ISSUE TITLE
[com_fields] for Users (Registration Form)

### ISSUE THREAD

**Issue by matiaio** [joomla/joomla-cms#20593]
### Steps to reproduce the issue

Create minimum 2 Languages (on my Website i have 3x Languages activated)
Create one Custom-User-Field per each Language (on my Website i have 3x Custom-User-Fields activated for each Language).

### Expected result

In Frontend on Page "User-Registration (German)" should apear just one User-Custom-Field corespond to each Language (German or English or Romanian)

### Actual result

In Frontend on Page "User-Registration" apears all 3x User-Custom-Fields (all 3 Languages) instead of one of them coresponding to Language activated into Frontend.

### System information (as much as possible)

I have Joomla! 3.8.8 installed

### Additional comments

How can be solved this Problem?
Best Regards

**Comment by SharkyKZ** [comment]
See PR #20596.
