### ISSUE TITLE
User profile settings allow change Editor if it restrict to Super Users

### ISSUE THREAD

**Issue by jurihahn** [joomla/joomla-cms#20605]
### Steps to reproduce the issue
Allow changing profile settings for users
got to plugins and set Codemirror Access to Super Users
Login as "Editor" user on frontend, change Editor settings to Codemirror
Edit an Article and you see TinyMCE

### Expected result
"Editor" User can not select Codemirror as editor

### Actual result
"Editor" User can select Codemirror as Editor, but this take no effect

### System information (as much as possible)
Joomla 3.8.8, PHP 7.0.27

**Comment by ghost** [comment]
Issue confirmed.
### System information
- 3.8.8
- Template: Protostar
- macOS Sierra, 10.13.4
- Firefox 60 (64-bit)
#### MAMP 4.5
- Apache-Server
- PHP 7.2.1
- MySQLi 5.6.38

**Comment by ghost** [comment]
closed as having Pull Request #20713

**Comment by ghost** [comment]
@jurihahn please test #20713
