### ISSUE TITLE
Wrong button padding on Joomla! site - Joomla! Downloads pages

### ISSUE THREAD

**Issue by AndNovAtor** [joomla/joomla-cms#20602]
### Steps to reproduce the issue

Open Joomla! Downloads pages in Chrome.

### Expected result

Download/View files buttons had padding

### Actual result

Buttons have no padding

### System information (as much as possible)

Windows 10 x64
Chrome - last version

### Additional comments

Ok, I think it's maybe not Joomla! site css's problem, but "problem" with akeeba/release-system. Anyway, this style "problem" has very low importance. or it makes no sense. )

Download/View files buttons had padding in the past.
![screenshot 2018-05-29 at GMT+3 10:36](https://issues.joomla.org/uploads/1/f866f03671f15df21656bc21a9de53b4.jpg)
![screenshot 2018-05-29 at GMT+3 10:36](https://issues.joomla.org/uploads/1/efe6bf815815dc1ddc562df97683429f.jpg)

**Comment by brianteeman** [comment]
Thank you for taking the time to report this but this isnt the right place. Please report here https://github.com/joomla/joomla-websites/issues/new?title=[jdown]%20&body=Please%20describe%20the%20problem%20or%20your%20issue
