### ISSUE TITLE
Adding notes to articles

### ISSUE THREAD

**Issue by smehrbrodt** [joomla/joomla-cms#20603]
### Is your feature request related to a problem? Please describe.

Sometimes it's helpful to have notes assigned to an article which is only visible in the administrator section.

This is already possible with modules. You can add notes to a module which will display in the module list.

### Describe the solution you'd like

Would be good to have the same for articles (a text field "Note") where you can enter additional information about the article.

**Comment by brianteeman** [comment]
Already done - see https://github.com/joomla/joomla-cms/pull/19134

**Comment by ggppdk** [comment]
> Already done - see #19134

@brianteeman 
that PR seems closed without being merged to any branch ? or i am missing something ?
staging, 3.9-dev, 3.10-dev

**Comment by brianteeman** [comment]
sorry quite right - i have reopened it
