### ISSUE TITLE
Tagged items menulink page missing images

### ISSUE THREAD

**Issue by kotisivutohtori** [joomla/joomla-cms#20600]
### Steps to reproduce the issue
Everytime I update the Joomla, I loose the the menulink images I have used for the Tagged Item menulink. Earlier those images were showing fine, but for about a year or so, the images disapper from Tagged item menu-page. 

I return the images by fixing this code:
components/com_tags/views/tag/view.html.php
Go to row 166 and add # before the code. 

// Categories store the images differently so lets re-map it so the display is correct
	    if ($items && $items[0]->type_alias === 'com_content.category')
	    {
		    foreach ($items as $row)
		    {
			    $core_params = json_decode($row->core_params);
ROW 166			    #$row->core_images = json_encode(array('image_intro' => $core_params->image, 'image_intro_alt' => $core_params->image_alt));
		    }
	    }

Is there a reasonn why the TAGGED ITEMS menulink no longer show the LINK TYPE LINK IMAGE? Why such field exists in the Tagged Items menulink settings if it no longer is used?

I hope this issue can be fixed, so I no longer need to fix this each time I update Joomla. 

Thank you!

- Anne

**Comment by SharkyKZ** [comment]
See PR #20601.

**Comment by ghost** [comment]
@kotisivutohtori can you please test #20601?
