### ISSUE TITLE
Joomla Search shows 403 Error

### ISSUE THREAD

**Issue by andyschra** [joomla/joomla-cms#20625]
### Steps to reproduce the issue
Install Joomla with Joomla Search Plugin. Enter ' (apostrophe) in search.

### Expected result
Joomla shows the Search Result Page with the Message: No entries found.

### Actual result
Joomla creates an url like /search?searchword=%27&ordering=newest&searchphrase=all&limit=100 and shows an 403 Error: You don't have permission to access /search on this server.

**Comment by brianteeman** [comment]
That error sounds like a server error message and not a joomla one. Do you have SEF urls correctly working?

If I try to search for an apostrophe I get the correct message
> Search term must be a minimum of 3 characters and a maximum of 200 characters.

Please use the forum for support https://forum.joomla.org
