### ISSUE TITLE
com_media thumbs preview don't work

### ISSUE THREAD

**Issue by lomcarlo** [joomla/joomla-cms#20638]
### Steps to reproduce the issue
open /administrator/index.php?option=com_media
click into a subfolder to open it
click on the link below the thumbnail with the hourglass on the left

### Expected result
a modal window should open
the content of the window should be an image

### Actual result
a modal window opens but image doesn't shows
the source of the image is wrong because the link on the iframe **index.php?option=com_media&view=mediaList&tmpl=component&folder=** have the slash "/" of the last folder written with **%2F** instead of **/** so the link is
```
<a href="https://example.com/images/subfolder%2Fexample.jpg" title="example.jpg" class="preview truncate">
```
instead of
```
<a href="https://example.com/images/subfolder/example.jpg" title="example.jpg" class="preview truncate">
```

### System information (as much as possible)
Joomla! 3.8.8 Stable [ Amani ] 22-May-2018 14:00 GMT
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Linux spmsf 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64
MySQL 5.5.60-0+deb8u1
PHP 5.6.33-0+deb8u1
Apache

**Comment by ghost** [comment]
Closed as duplicate Report #20635
