### ISSUE TITLE
[4.0] Admin very slow

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#20633]
### Steps to reproduce the issue
on the same machine/server that I test j3 etc on I am finding J4 very very slow

See movie and screenshot for opening a menu item- notice the 303 redirect in the screenshot and how long it is taking
It is the same for all links not just this one but without the 303 - see second screenshot for opening global config

### System information (as much as possible)

PHP Built On | Windows NT DESKTOP-VPRGVNL 10.0 build 17134 (Windows 10) AMD64
Database Version | 5.7.21-log
Database Collation | utf8mb4_unicode_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.2.2
Web Server | Apache/2.4.29 (Win64) mod_fcgid/2.3.9 OpenSSL/1.1.0g
WebServer to PHP Interface | cgi-fcgi
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

![editmenu](https://user-images.githubusercontent.com/1296369/40785697-29f69a74-64e1-11e8-9263-99397a32f602.gif)

<img width="1280" alt="chrome_2018-05-31_14-40-28" src="https://user-images.githubusercontent.com/1296369/40785707-314cf80e-64e1-11e8-8127-64b5e798b3b0.png">

<img width="1280" alt="chrome_2018-05-31_14-43-05" src="https://user-images.githubusercontent.com/1296369/40785708-3170552e-64e1-11e8-8416-f93cc10a45ce.png">

**Comment by laoneo** [comment]
Do you have debug mode enabled? Not sure if it really makes a difference but for me it is faster without debug mode.

**Comment by brianteeman** [comment]
No this was without debug

**Comment by dgrammatiko** [comment]
do you get anything in the logs?

**Comment by brianteeman** [comment]
[Thu May 31 14:18:04.172056 2018] [fcgid:warn] [pid 6176:tid 1884] [client 127.0.0.1:52340] mod_fcgid: stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in C:\\htdocs\\cms4\\libraries\\vendor\\joomla\\database\\src\\Mysqli\\MysqliStatement.php on line 120, referer: http://127.0.0.1/cms4/administrator/index.php

**Comment by dgrammatiko** [comment]
2 more questions here:
- Mysql version?
- Is this happening only with com_menus or is it irrelevant of the component?

**Comment by brianteeman** [comment]
1. as in the first post Database Version | 5.7.21-log - using mysqli
2. the component is irrelevant as shown by the two screenshots

**Comment by brianteeman** [comment]
Going to close this for now. Either resolved with latest branch or a new database
