### ISSUE TITLE
Image preview in back-office fail in 3.8.8

### ISSUE THREAD

**Issue by EmmanuelVAS** [joomla/joomla-cms#20635]
### Steps to reproduce the issue
(French version for texts and labels) : 
Go to back-office, "medias".
It seems that if images are located in a subfolder of the parent parent "images", the preview of the image fail every time.

Console shows:
GET http://www.mywebsite.com/images/Realisations_diapo%2FOrvault_cage_escalier%2FCage-escalier-Orvault8.jpg 404 (Not Found)

It seems that the "/" separator for subfloders of "images" is replaced by a "%2F".

### Expected result
Image shows in the modal

### Actual result
Image doesn't appears. Only the texte "preview" in the modal

### System information (as much as possible)
Apache2
Php 7.0

**Comment by ghost** [comment]
this sound similar to #20585. Can you please test merged #20586 if this solved Issue?

**Comment by EmmanuelVAS** [comment]
OK, I assume the problem is solved due to escaping. 
Sorry for the double issue.. Thanks !
