### ISSUE TITLE
Joomla 3.8.8 adds %2F to the image urls when the images are in a subfolder.

### ISSUE THREAD

**Issue by madesign** [joomla/joomla-cms#20641]
### Steps to reproduce the issue

Use the modal preview of an image in the media manager in a subfolder.

### Expected result

Hello,

Joomla 3.8.8 adds %2F to the image urls when the images are in a subfolder in the media manager. Seams only to effect the modal preview and when you try to copy an image. Contrary to my first suggestion it has nothing to do with SSL activating or not.

https://forum.joomla.org/viewtopic.php?f=706&t=962504&p=3527027#p3527027

Regards, Michael

### Actual result

https://youtu.be/E5UmP1jdGGQ

### System information (as much as possible)

Joomla 3.8.8

**Comment by mbabker** [comment]
Resolved by https://github.com/joomla/joomla-cms/pull/20586

**Comment by madesign** [comment]
If it’s fixed, why it’s still happen for me and others? There is no update available after 3.8.8 or do I miss something?

**Comment by mbabker** [comment]
There hasn't been a release since 3.8.8.  The issue you've noted has been fixed in the codebase and will be included in the next release.

**Comment by madesign** [comment]
Thank you! Finally.
