### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by AndyKelsall** [joomla/joomla-cms#20657]
I installed Joomla via my Synology NAS drive (3rd party app) and created an extremely basic webpage. I now wish to develop the page but cannot login. I have tried logging in with the superuser user name with what i believe was the password but that is unsuccessful. I have tried the "forgotten password" option, but I am told I cannot change the password of the supperuser.

Help please!!!

**Comment by brianteeman** [comment]
Please use thew forum for support see https://forum.joomla.org

**Comment by tonypartridge** [comment]
Also see:
https://docs.joomla.org/How_do_you_recover_or_reset_your_admin_password%3F
