### ISSUE TITLE
Images and links params

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#20651]
### Is your feature request related to a problem? Please describe.
Currently the ability to show/hide images and links fields on the edit forms are combined. In J4 we want to try and simplify the forms etc but with these fields being combined it is hard.

### Describe the solution you'd like
Separate the single option into two options - one for images and one for links
Change links to be hidden by default on new installs

### Additional context
For b/c this would only be on new installs but instead of creating two new values we could keep the existing one for "show images" and only add a new one for "show links" and in addition add extra code so that even though "show links" defaults to hide we additionally check to see if the fields have a value and then ignore the param setting of hide and show them anyway.

**Comment by brianteeman** [comment]
No one has an opinion on this?

**Comment by brianteeman** [comment]
Closed due to lack of interest

**Comment by ciar4n** [comment]
Sorry only seeing this now. I agree with the proposal. I personally don't think I have ever seen these links used. With the introduction of custom fields, I can't imagine I ever will.

**Comment by brianteeman** [comment]
Reopen to see if anyone else comments

**Comment by ggppdk** [comment]
Is it acceptable not to add new parameter,
but to do this with the existing parameter
which will be (mostly) B/C too ...

** Image and Links

0: No,  (Old text: Hide)
1: Both (Old text: Show)
2: Images
3. Links

More interested in the question of doing such things

**Comment by cyrez** [comment]
@ggppdk 👍 This way, it will add possibilities and no B/C break (and could go to j3 branch as well)
Good idea!
