### ISSUE TITLE
[4.0] SampleData Installation generates JS error if more than one plugin active

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#20662]
### Steps to reproduce the issue
* Install the testing sampledata plugin (or any other one) from https://github.com/joomla-extensions/testing-sample-data/releases/tag/v3.8.0. That one is expected to be broken in 4.0 but for this test it will do.
* Try installing the "Blog Sample Data" from the Control Panel.

### Expected result
Installs fine

### Actual result
It doesn't install. A JS error shows in the browser
![image](https://user-images.githubusercontent.com/1018684/40913195-23555992-67f4-11e8-9ea0-03fd8f2ee9c9.png)

Data response looks like this:
![image](https://user-images.githubusercontent.com/1018684/40913184-1ace649e-67f4-11e8-9d87-07567a9ea87f.png)

Please note that data is an array and the first entry is null (coming from the "testing" plugin returning empty). Our JS apparently checks the first entry and doesn't find a success property.

I'm pinging @C-Lodder here as he rewrote the JS lately. I honestly don't know if that bug existed before that rewrite or not.

**Comment by ghost** [comment]
closed as having Pull Request #20676
