### ISSUE TITLE
Plug-in for TinyMCE

### ISSUE THREAD

**Issue by motokraft** [joomla/joomla-cms#20669]
Hello!
I'm writing my plugin for the TinyMCE editor. I would like to know if I can somehow change the plugin's settings before outputting to the page?

**Comment by ghost** [comment]
Changed Title to shown only English.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20669">issues.joomla.org/tracker/joomla-cms/20669</a>.</sub>

**Comment by infograf768** [comment]
Hmm, it looks this user is asking for help. Our Github repo concerns only joomla core coding.
@motokraft 
Is this a proposal for a new Joomla core plugin? If not, please ask for help in the forums or on list joomla-dev-general@googlegroups.com

**Comment by ghost** [comment]
> I'm writing my plugin for the TinyMCE editor

So i thought ist about Coding.

**Comment by infograf768** [comment]
> So i thought ist about Coding.

It is for sure, but is it for the core or a personal plugin the user wants to add to TinyMCE. Let's wait for an answer. 😃

**Comment by dgrammatiko** [comment]
> I would like to know if I can somehow change the plugin's settings before outputting to the page

Since you are the developer of the plugin you should be able to do whatever you want. But to me it's not clear what do you mean by the `plugin's settings`. So do you want to pass some data on a specific editor instance (tinyMCE in this case), if so you need to write a plugin that alters the stored values in Joomla.storageOption (check the method here: https://github.com/joomla/joomla-cms/blob/7e938bcdf50dab813bcba8fb87ad786ada38f8fa/libraries/src/Document/Document.php#L606-L623 ).

Hope it helps

**Comment by motokraft** [comment]
there is a plugin for TinyMCE
![screenshot_1](https://user-images.githubusercontent.com/6596533/41033183-40132582-698e-11e8-9992-ed902ee58f90.png)
What it would have to do is add the init plug-in TinyMCE.
I have not yet figured out how to make tinymce.init in the plugin so that all the settings that were used for **jform[articletext]** remained

**Comment by Fedik** [comment]
It not a plugin, it just use of TinyMCE init callback.

To make your own plugin check this https://www.tinymce.com/docs/advanced/creating-a-plugin/

To add your plugin to TinyMCE use `external_plugins` option https://www.tinymce.com/docs/configure/integration-and-setup/#external_plugins
as @dgrammatiko suggested.
Or add it there manually (TinyMCE editor params):
![screen 2018-06-06 14 39 31 610x172](https://user-images.githubusercontent.com/1568198/41036095-94ea9b40-6997-11e8-88ca-5007693a072f.png)

But it is not a Joomla! core issue. 
For more help please ask on Joomla! forum.

**Comment by brianteeman** [comment]
Closed as not core
