### ISSUE TITLE
[4.0] Multililanguage: Associations do not display any more for articles categories

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#20667]
### Steps to reproduce the issue
Install last 4.0-dev
Enable the Language filter plugin and make sure Associations is set to Yes.
Display Articles Categories Manager
or edit an Article Category

### Expected result
In the manager, the Associations column should display
When editing a category, the Associations tab should display

### Actual result
Both don't display.
`$this->assoc` is always false

**Comment by infograf768** [comment]
I think I found the issue:
The code for getAssoc() method is looking for helpers the old way, i.e.
```
		else
		{
			$hname = $cname . 'HelperAssociation';
			\JLoader::register($hname, JPATH_SITE . '/components/' . $component . '/helpers/association.php');

			$assoc = class_exists($hname) && !empty($hname::$category_association);
		}

		return $assoc;
```
but not only the `helpers` folder does not exist anymore for com_content as it is now
`/Helper/AssociationsHelper.php`
but also the class has no more component name
i.e. it is `class AssociationsHelper extends \CategoryHelperAssociation`
instead of
`abstract class ContentHelperAssociation extends CategoryHelperAssociation`


This explains why it still work for com_contact but not for com_content...
Briefly said, it's all broken...

**Comment by laoneo** [comment]
Please test #20692 which should fix the issue.
