### ISSUE TITLE
[4.0] Editor Link button doesn't work in Firefox or Edge

### ISSUE THREAD

**Issue by tassosm** [joomla/joomla-cms#20665]
### Steps to reproduce the issue
Using Firefox or Edge, edit an article, select text and click on the "Insert/Edit link" editor button.

### Expected result
The Link settings popup shows up.

### Actual result
Javascript Error
`TypeError: e.split is not a function`

![link_button_doesntwork](https://user-images.githubusercontent.com/6807469/40965132-9b16785a-68b5-11e8-84c3-a6b05fe512a6.gif)

Same behavior with the following buttons as well:

- Insert/Edit media
- FInd and replace
- Source code
- Anchor

### System information (as much as possible)
Firefox 60.0.1
Edge 41.1
Joomla! 4.0.0-alpha4-dev (Fresh Install)

### Additional comments
I couldn't reproduce the issue on Chrome 67
Similar issues: #20478 and #20477

**Comment by ghost** [comment]
@dgrammatiko can you please have a Look here as this Issue isn't commented since 9 Days?

**Comment by ghost** [comment]
Issue confirmed.
### System information
- Nightly Build 4.0.0-alpha4-dev
- Multilingual Sample Data
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20665">issues.joomla.org/tracker/joomla-cms/20665</a>.</sub>

**Comment by dgrammatiko** [comment]
@tassosm can you please disable the CSP plugin and try again?

**Comment by ghost** [comment]
com_csp disabled, same Result `TypeError: e.split is not a function ... webcomponents-sd-ce.min.js:1:64022`

**Comment by dgrammatiko** [comment]
Sorry I meant the plugin System - HTTP Headers, not the csp component

Also did you clear your browser cache?

**Comment by ghost** [comment]
Same Result havin Plugin "System - HTTP Headers" disabled and Browser Cache cleared.

**Comment by tassosm** [comment]
Same result with the System - HTTP Headers disabled and cache cleared.

**Comment by roland-d** [comment]
Confirmed as well. However turning on the Joomla Debug doesn't make it load the uncompressed version of webcomponents-sd-ce.min.js. I can't find the file where this is loaded to see if there is a bug there.

**Comment by Quy** [comment]
No longer reproducible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20665">issues.joomla.org/tracker/joomla-cms/20665</a>.</sub>
