### ISSUE TITLE
Default Joomla Articles Latest module do not include a possibility to choose a specific or a list of user(s) author(s).

### ISSUE THREAD

**Issue by uzielweb** [joomla/joomla-cms#20685]
Default Joomla Articles Latest module do not include a possibility to choose a specific or a list of user(s) author(s). 

It's impossible to select users.
I have a plugin called Add XML Fields (I am the creator of this plugin) that combines some process to perform a field override.
That's ok for me. But, I am very disapointed with many default Joomla way of work.

### Steps to reproduce the issue

Create a new "Articles Latest" module in Joomla administrator

Go to "Authors" option. You will see only three options to choose, but do not appears an option to choose a specific user or a list of users.

### Expected result
Authors is expected to be an "user" form field type or another option to choose a specific user_id.

### Actual result

Show only three options, impossible to choose authors.

### System information (as much as possible)
Joomla 3.8.8, PHP7

### Additional comments

Please, include this "user" form field type in the next releases

**Comment by ghost** [comment]
> Please, include this "user" form field type in the next releases

Thanks for your Suggestion > That will be done if someone write a Pull Request, there are 2 successfully tests and Maintainer decide to merge a PR.

**Comment by SharkyKZ** [comment]
Use `Articles - Category` module.

**Comment by Quy** [comment]
Please test PR #20687<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20685">issues.joomla.org/tracker/joomla-cms/20685</a>.</sub>
