### ISSUE TITLE
Protostar does not assign for some reason

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#20696]
### Steps to reproduce the issue
Create Joomla! install.  
Use Blog dummy content
Open protostar from backend templates > Protostar
Try not to assign it to something on the main menu when on desktop

### Expected result
can assign to menu items or unassign

### Actual result
Can't click on the right hand box

Here's a nice video
https://www.dropbox.com/s/h0hbch8hi07udzf/protostar.mp4?dl=0

### System information (as much as possible)
[systeminfo-2018-06-08T16_22_34-05_00.txt](https://issues.joomla.org/uploads/1/8536fdbaa5ec00d64b86f20a2018e1d7.txt)

### Additional comments
Brand new install.  Only Akeeba Backup is installed.

**Comment by Quy** [comment]
Fixed in #20542 for v3.8.9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20696">issues.joomla.org/tracker/joomla-cms/20696</a>.</sub>

**Comment by uglyeoin** [comment]
Thanks, great job.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20696">issues.joomla.org/tracker/joomla-cms/20696</a>.</sub>
