### ISSUE TITLE
[4.0] Content Language not created when installing language

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#20691]
### Steps to reproduce the issue
Install a clean Joomla. After setting the database, install a language (German, French and Persian are available).
The language is installed, but the Content Language is not created.
![installlang_anim](https://user-images.githubusercontent.com/869724/41166548-c8c356a0-6b40-11e8-9456-c6e516a962a7.gif)

**Comment by infograf768** [comment]
Note: Let's also remember that although the code is still there in installation/src/, we can't choose admin and site default langs, multilang data (I am finishing now a specific multilang sampledata plugin to cope with that), etc.

**Comment by Quy** [comment]
It is working for me as of https://github.com/joomla/joomla-cms/commit/f180ef0aedf4bcdfc88417c9f2376ddf6b282cac

![languages](https://user-images.githubusercontent.com/368084/41167546-118bd40a-6af8-11e8-98e5-c81b4915c202.jpg)

**Comment by infograf768** [comment]
Have you installed the language as I did when installing a clean Joomla at Joomla install time, not from administrator install languages?

**Comment by Quy** [comment]
Yes, performed exact steps as in your video.

**Comment by infograf768** [comment]
Hmm... It works now... Closing

**Comment by brianteeman** [comment]
@infograf768 could it be language related - I am sure that I had something similar the other day. Content language ws only created for some of the languages

**Comment by infograf768** [comment]
can't be language pack related if it works once and not always. I guess maybe this test site had some ancient code remaining somewhere. Maybe a js conflict. We have only 3 languages that we can install and all have the correct 3.8.8.1 code.

**Comment by brianteeman** [comment]
I have no idea what languages I selected when I tried and failed :(

**Comment by Quy** [comment]
#16337 could be related?

**Comment by infograf768** [comment]
Unrelated. @mbabker managed for us to be able to install/use fr-FR, de-DE and fa-IR on 4.0.
There never is an issue when installing with `Install Languages` in back-end, only a bit unstable when installing Joomla itself. I mean the language installs but Content Language may or may not.
