### ISSUE TITLE
Calendar. Finish Publishing in modal partially hidden.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#20703]
### Steps to reproduce the issue
- 3.8.9-dev updated with nightly Joomla_3.8.9-dev-Development-Update_Package.zip of today.
Same issue in Joomla 3.8.8
- Open a menu item of type "Single Article".
- Click Edit button of field "Select Article"
- In tabulator "Publishing" open calendar of field "Finish Publishing"
- See image (calendar not usable because partially hidden)

![09-06-_2018_13-11-12](https://user-images.githubusercontent.com/20780646/41190927-92108ba8-6be7-11e8-87ac-f20003cd0ead.png)

- Tested with Vivaldi, Chrome, Firefox **ESR** 52.8.1 (32-Bit)
- In Firefox ESR all three calendar fields are partially hidden.
- In Vivaldi and Chrome only Start Publishing is correct. EDIT: But not in Joomla 3.8.8
- Did not test with current FF 60

**Comment by dgrammatiko** [comment]
@ReLater it's known issue and quite impossible to solve as long as we require the manual entry to work as well...

In this case the only solution is to rearrange the form so the field has enough space above

**Comment by ReLater** [comment]
> it's known issue

I couldn't find any older issue.

Isn't there a way to open all calendar fields here downwards? Thus, the vertical scrollbar of modal could be used (as far as I see).

**Comment by ghost** [comment]
I'm going search as i remember similar too.

**Comment by ghost** [comment]
Similar #18581, #15028, but thats not what i remember. If necessary i search again.

**Comment by Quy** [comment]
Not an issue with FF60.

**Comment by dgrammatiko** [comment]
My explanation is here: https://github.com/joomla/joomla-cms/issues/18469#issuecomment-346161292

**Comment by ReLater** [comment]
All related issues were closed without solving this one. So, I keep this issue open as a reminder and to avoid more reports.

A
```
.container-popup .js-calendar
{
 margin-top: 0 !important;
}
.container-popup
{
 padding-bottom: 200px !important;
}
```
[in custom.css](https://github.com/joomla/joomla-cms/issues/18469#issuecomment-346198931) solves it at the moment for most modals.

**Comment by Quy** [comment]
@ReLater Is this still an issue?

**Comment by ReLater** [comment]
> Is this still an issue?

Yes. Tested with 3.9.2, nightly Saturday, 29 December 2018 03:00:09 UTC
