### ISSUE TITLE
[4.0] Contacts Fatal Error

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#20709]
### Steps to reproduce the issue
Multilingual: displaying a single contact which was inserted in an article via xtd (a single contact menu item works fine)
`0 Argument 1 passed to Joomla\Registry\Registry::merge() must be an instance of Joomla\Registry\Registry, null given, called in /Applications/MAMP/htdocs/newfolder/joomla40/components/com_contact/Model/ContactModel.php on line 118 `

Displaying a contact category from a List All Contact Categories menu item page
`PHP Fatal error:  Cannot declare class Joomla\Component\Contact\Site\Helper\Route, because the name is already in use in /Applications/MAMP/htdocs/newfolder/joomla40/components/com_contact/helper/route.php on line 23`

Trying to display a Contact category from a single contact page => 404

These errors also present after merging https://github.com/joomla/joomla-cms/pull/20692

**Comment by laoneo** [comment]
This is due the fact that the Registry class doesn't allow null values anymore. More information about this topic can be found in #20675. The consequence is that every instantiate or merge needs to be surrounded by an if block. So `$registry = new Registry($value);` has to become:
```
if ($value)
{
    $registry = new Registry($value);
}
```

**Comment by roland-d** [comment]
@laoneo It may be another discussion but perhaps the Registry should return an empty Registry object?

**Comment by laoneo** [comment]
@mbabker is here the man in charge. I really don't care at all as long as we make a proper announcement when we are more strict in J4 than J3, as this class is used widely in core and 3rd party extensions.

**Comment by csthomas** [comment]
> So $registry = new Registry($value); has to become:

No, constructor still allow you to put empty string or null.
Michael only want to change `loadString()` method.

On J4, you can use:
```php
$registry = new Registry('');
$registry = new Registry(null);
```
but you can not:
```php
$registry = (new Registry())->loadString('');
$registry = (new Registry())->loadString(null);
```

Take a look at the constructor at https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/vendor/joomla/registry/src/Registry.php#L65

Currently, `Registry` has been updated for J3.x and it is not strict, J4.x has an older version with strict code.

**Comment by laoneo** [comment]
Ok then I was wrong. Not sure if Michael is pushing that change into 2.x.

**Comment by csthomas** [comment]
For me 2.x should be strict.

**Comment by laoneo** [comment]
As I said. I'm fine with both options. Np.

**Comment by mbabker** [comment]
The CMS is behind a bit on some of the Composer dependencies in 4.0.  As far as the framework repos go everything committed to master (1.x) is being merged regularly into the 2.0-dev branches, so there are few if any behavioral differences aside from intended changes.  We just need to `composer update` things here, a lot of packages haven't been updated in a while.

**Comment by infograf768** [comment]
Small reminder: we also have the fatal error concerning the class declaration here, and same for Newsfeeds. :smiley:

**Comment by brianteeman** [comment]
has this been resolved?

**Comment by laoneo** [comment]
Did #20802 fix this issue?

**Comment by infograf768** [comment]
Closing as this has indeed been solved.
