### ISSUE TITLE
css errors in protostar template

### ISSUE THREAD

**Issue by joomlahenk** [joomla/joomla-cms#20701]
### Steps to reproduce the issue
Open page using protostar template.
In browser inspect elements

### Expected result
p {
    margin: 0 0 0.75em;
}

### Actual result
p {
    margin: 0 0 0.75;
}

### System information (as much as possible)
J! 3.8.8
Using less compiler plugin with lessc version 0.3.9

### Additional comments
Discovered that the problem is in ..\media\jui\less\type.less
p {
  margin: 0 0 @baseLineHeight / 2;
}
But since @baseLineHeight is a factor and has no dimension, then margin also gets no dimension.
So change to:
p {
  margin: 0 0 @baseLineHeight / 2em;
}
This solved the problem.
I gave element p just as an example, but there are many more (like h1,h2,... blockquote, etc).

**Comment by SharkyKZ** [comment]
Can't reproduce this. `@baselineheight` in Protostar is 18px:
[https://github.com/joomla/joomla-cms/blob/staging/templates/protostar/less/variables.less#L56](https://github.com/joomla/joomla-cms/blob/staging/templates/protostar/less/variables.less#L56)
 Resulting value is 9px:
```
p {
    margin: 0 0 9px;
}
```

**Comment by joomlahenk** [comment]
Yes if set with px as a dimension, but @baselineheight is also used for css line-height property, which has no dimension. So for that I should set @baselineheight without dimension.

**Comment by SharkyKZ** [comment]
`line-height` can be defined in length units. In any case, this is coming from Bootstrap http://getbootstrap.com/2.3.2/base-css.html#body-copy.

**Comment by ghost** [comment]
@SharkyKZ close as no Core-Issue?

**Comment by joomlahenk** [comment]
OK, can be closed.
