### ISSUE TITLE
Percentage character issue with RTL languages

### ISSUE THREAD

**Issue by fouadfana** [joomla/joomla-cms#20716]
### Steps to reproduce the issue
Once you create and try to save any content ex: an article with just the character %.

### Expected result

suppose the character % appears on front end as normal post.

### Actual result

redirect to error 404 page.

**Comment by ghost** [comment]
can you give please System Information and provide for Example Screenshots so its easier to understand whats the Issue?

**Comment by fouadfana** [comment]
![percentage](https://user-images.githubusercontent.com/10183353/41229633-0242ebdc-6d7d-11e8-96c4-854e1c81af87.png)
![percentage2](https://user-images.githubusercontent.com/10183353/41229634-0263156a-6d7d-11e8-948b-9922cb5a38a4.png)

**Comment by fouadfana** [comment]
the attached screanshots above show once you try to save an article with % symbol, error 404 page appear once press save.

**Comment by infograf768** [comment]
In any case pressing Save in back-end will not trigger a 404.
I tested on frontend and, even when using RTL language, it does not trigger a 404 here.

**Comment by brianteeman** [comment]
Most likely you have a security plugin installed such as rsfirewall or simialr

**Comment by ghost** [comment]
clsed as no Core-Issue.

@fouadfana Please ask further help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding, thanks.
