### ISSUE TITLE
[4.0] Alerts -

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#20719]
### Steps to reproduce the issue
Spotted this testing a plugin. As can be seen in the screenshot the alert title is lowercase and it should be capitalised. I "suspect" that it is also not translatable

<img width="253" alt="chrome_2018-06-11_16-41-26" src="https://user-images.githubusercontent.com/1296369/41242141-a8eaead4-6d96-11e8-938e-8fdc4ad4847d.png">

**Comment by dgrammatiko** [comment]
it's not the custom element: https://github.com/joomla/joomla-cms/blob/4.0-dev/media/vendor/joomla-custom-elements/js/joomla-alert.js
it's the core.js: 
https://github.com/joomla/joomla-cms/blob/8d048ad8d4c3f760946254c5bd684e391a392dd6/media/system/js/core.js#L413-L420

(type is lowercase in J4)

But it is still translatable: https://github.com/joomla/joomla-cms/blob/4.0-dev/media/system/js/core.js#L434

**Comment by brianteeman** [comment]
That explains why my tests on changing the element didnt work ;)

It is only translatable though if we give translators strings to translate which if I read the js code correctly we are not

**Comment by dgrammatiko** [comment]
If you want to do the change the hardcoded part is here: https://github.com/joomla/joomla-cms/blob/8d048ad8d4c3f760946254c5bd684e391a392dd6/layouts/joomla/system/message.php#L17-L27

But if, lets say, type `info` is `πληροφορία` in greek, then we need to make sure the custom element is checking also against that string. If you patch the php part I'll make sure the js (ce and core) are also patched.

**Comment by ggppdk** [comment]
So the translating method is already called inside the JS code

And also the language strings exist
in frontend and backend language files
https://github.com/joomla/joomla-cms/blob/4.0-dev/language/en-GB/en-GB.ini#L12-L18
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/language/en-GB/en-GB.ini#L41-L47

`JHtmlBehavior::core()`
libraries/cms/html/behavior.php

needs to load them

**Comment by ggppdk** [comment]
I have made a PR https://github.com/joomla/joomla-cms/pull/20721

**Comment by brianteeman** [comment]
@ggppdk your code doesnt work
