### ISSUE TITLE
[3.8.8] The session table doesn't get updated

### ISSUE THREAD

**Issue by diddipoeler** [joomla/joomla-cms#20712]

**Comment by infograf768** [comment]
Please change title to English and give details on how to reproduce the issue.

**Comment by laoneo** [comment]
Changed the title.

**Comment by mbabker** [comment]
Without filling in the rest of the issue template there really isn't much to go on here...

**Comment by Quy** [comment]
Closing for now and can be reopened when additional information is provided. Please see if this issue has been reported @ [Joomla Forum](https://forum.joomla.org/)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20712">issues.joomla.org/tracker/joomla-cms/20712</a>.</sub>
