### ISSUE TITLE
Language string plurals?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#20725]
https://docs.joomla.org/J3.x:Making_a_Language_Pack_for_Joomla#Working_with_plurals

Looking at the examples can the _0 string ever be used.
COM_BANNERS_BANNERS_N_ITEMS_CHECKED_IN_0="No banner checked in"

**Comment by mbabker** [comment]
In theory yes, for most of the cases in core where we have one if it does get used it would probably indicate some kind of issue though.

**Comment by brianteeman** [comment]
From what I can see in the core IF they were used then they 
1. Should be an error message
2. We are missing a lot of them

**Comment by mbabker** [comment]
Sounds about right.

**Comment by brianteeman** [comment]
@bakual any thoughts on this?

**Comment by Bakual** [comment]
I honestly don't know if the zero form is used anywhere. Maybe if you can select multiple items for a task and the count is then depending on if something had to be done or not. Eg when you select 10 items to publish and all of them were already published it could say no items published, this kind of thing.
If that could happen it would have to be checked on a case by case basis by looking at the code and/or trying.

**Comment by brianteeman** [comment]
@bakual I tried that - if you select 10 published items and try to publish them you get a message 10 items published

**Comment by brianteeman** [comment]
See #20752
