### ISSUE TITLE
Repeatable fields are not working with a modal_article inside

### ISSUE THREAD

**Issue by muuvmuuv** [joomla/joomla-cms#20729]
Repeatable field not working with a `modal_article`-field.

### Steps to reproduce the issue
1. add a repeatable with modal_article field:
```
      <!-- Fieldset: Dock -->
      <fieldset name="dock" label="Dock">

        <field name="dock_links" type="repeatable" icon="link" label="Links">
          <fieldset hidden="true" repeat="true" addfieldpath="/administrator/components/com_content/models/fields">
            <field name="name" type="text" label="Name" description="Social Name" filter="text"/>
            <field 
              name="article"
              type="modal_article"
              label="Select an article"
              select="true"
              edit="false"
              clear="true"
            />
          </fieldset>
        </field>

      </fieldset>
      <!-- ./Fieldset: Dock -->
```

### Expected result
Show up two modals. Repeatable and Article selection.

### Actual result
Nothing happens

### System information (as much as possible)
OSX 10.13.5 (17F77)
Chrome 67.0.3396.79
Joomla 3.8.8

**Comment by Quy** [comment]
Duplicate #11805?

**Comment by dgrammatiko** [comment]
modal fields are really very poorly coded, it might be very hard to fix it without B/C break...

**Comment by f-liva** [comment]
Bad news here...

How we can help with those tests?

**Comment by okonomiyaki3000** [comment]
Not sure if it's worth it to fix this for J3. J4 is possible #20788

**Comment by brianteeman** [comment]
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed. 

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
