### ISSUE TITLE
Add layer selection fields for additional templating (or whatever it's called)

### ISSUE THREAD

**Issue by AlekVolsk** [joomla/joomla-cms#20722]
### Is your feature request related to a problem? Please describe.
for modules and plugins, there are not enough field types to select additional template layers

### Describe the solution you'd like
add field "LayoutsModule" ( /libraries/legacy/form/field/layoutsmodule.php )
add field "LayoutsPlugin" ( /libraries/legacy/form/field/layoutsplugin.php )
for "LayoutsPlugin" add language constant `JOPTION_FROM_MODULE="---From Plugin---"`

### Additional context
this allows you to create additional template layers in the 
[ **/modules/mod_mymodule/lauouts/**, 
  **/plugins/folder/my_plugin/layouts/** ] 
folder and override them in the template 
[ **/templates/myTemplate/html/layouts/mod_mymodule/**, 
  **/templates/myTemplate/html/layouts/plg_folder_myplugin** ]
, and – most importantly(!) – select the required override in the extension parameters

**Comment by AlekVolsk** [comment]
https://github.com/AlekVolsk/shits/blob/master/layoutsmodule.php

https://github.com/AlekVolsk/shits/blob/master/layoutsplugin.php

**Comment by mbabker** [comment]
There's already a module layout field - https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/form/field/modulelayout.php - what exactly are you aiming for with this suggested new field?

**Comment by AlekVolsk** [comment]
No, it is not, ModuleLayout selects the main module template, but there are modules with complex templates, when it is necessary to implement additional layers and, if necessary, to override them, to choose the necessary override in the module or plugin

**Comment by AlekVolsk** [comment]
For example, a module with a filter form, where each filter element is a separate layer, and layers of the same type sometimes need to be wrapped in a different way (for example, a list can be represented as a select, multi-select, regular list, group of checkboxes or radio, in any other way)

![screenshot_1](https://user-images.githubusercontent.com/9278339/41251185-358dd4be-6dca-11e8-86d1-23aa4a36887c.png)

**Comment by laoneo** [comment]
So you want to expand the suport of JLayouts to modules and plugins, similar to what we have already for components?

**Comment by AlekVolsk** [comment]
Yep ;)

**Comment by SharkyKZ** [comment]
JLayouts work everywhere as it is. The request is for adding a field type that looks up layouts in /layouts/ directory as opposed to /tmpl/ directory.

**Comment by Bakual** [comment]
That sounds to me like a use case very specific to your extension which you can solve yourself with a custom formfield for that "creative" use of JLayouts.
