### ISSUE TITLE
[4.0] Remove option "Mouse-over Edit Icons for" from global configuration

### ISSUE THREAD

**Issue by Hackwar** [joomla/joomla-cms#20728]
The feature "Mouse-over Edit Icons for" should be decoupled from the global configuration. This is a setting that should be part of the module or menu manager respectively and not be stored in configuration.php.

**Comment by brianteeman** [comment]
Not exactly removing it but perhaps a more meaningful title https://github.com/joomla/joomla-cms/pull/20743<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20728">issues.joomla.org/tracker/joomla-cms/20728</a>.</sub>

**Comment by brianteeman** [comment]
I think this should be closed now - with the label change it is more generic and could hopefully be extended to inline content editing etc in the future

**Comment by ghost** [comment]
Issue can always reopened if needed.
