### ISSUE TITLE
[4.0] Styling the subform repeatable field

### ISSUE THREAD

**Issue by Taatshi** [joomla/joomla-cms#20720]
Please correct the display of the subform repeatable field in the administrative part of the site. Now it does not fit even into the biggest screen resolutions. It is very uncomfortable.

Thank you
![01](https://user-images.githubusercontent.com/6442742/41244570-19512e98-6dae-11e8-82e2-6ad9b359d812.png)

Joomla 4.0 alpha

**Comment by ghost** [comment]
Changed Title cause Issue is about 4.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20720">issues.joomla.org/tracker/joomla-cms/20720</a>.</sub>

**Comment by laoneo** [comment]
Perhaps can @ciar4n help out here.

**Comment by ghost** [comment]
@Taatshi can you please look if this is an Issue on latest Nightly Build?

**Comment by AndySDH** [comment]
Repeatable field is going away in Joomla 4. It will be replaced by the better version, called Subfields
See: #24711

Please test if the problem happens with this new version too and report in that PR.

**Comment by ghost** [comment]
closed for Reason stated above.
