### ISSUE TITLE
Input class doesn't return file uploads in subform

### ISSUE THREAD

**Issue by waveywhite** [joomla/joomla-cms#20736]
### Steps to reproduce the issue

form.xml
```
<?xml version="1.0" encoding="utf-8"?>
<form>
    <field 
        name="uploads"
        type="subform"
        formsource="path/to/subform.xml"
        label="" 
        description="" 
    />
</form>
```
subform.xml
```
<?xml version="1.0" encoding="utf-8"?>
<form>
    <field 
        name="fileupload" 
        type="file" 
        required="true" 
        label="" 
        description="" 
    />
</form>
```
model.php
```
$data = JFactory::getApplication()->input->getArray();
echo json_encode($data); exit;
```
### Expected result

fileupload field data should be present

### Actual result

fileupload field data is not present

### System information (as much as possible)

Joomla 3.8.8

### Additional comments

Files are uploading from the browser using multipart form
Files are appearing in the tmp folder
The _FILES global variable has the file information
No file information on Input object.

Workaround is to examine the _FILES global variable directly. The format is a little unusual due to the HTML array syntax of the upload parameters but it's parsable.

**Comment by SharkyKZ** [comment]
I think you have to use `JFactory::getApplication()->input->files->get()` to get file data.

**Comment by SharkyKZ** [comment]
I think you have to use `JFactory::getApplication()->input->files->get()`.

**Comment by mbabker** [comment]
Correct.  `JFactory::getApplication()->input` on its own is a representation of the `$_REQUEST` superglobal.  To fetch data from a specific global, you need to explicitly add that to your call stack, we don't try to dynamically fetch from any global.

**Comment by waveywhite** [comment]
After a few hours of trawling around we've worked out how this works now.

For future reference, for when using a Joomla subform you do:

`JFactory::getApplication()->input->files->get('jform')`

This will provide a nested array of all files organised by subform name, subform row, element name, then details for each element (tmp file name, originating file name, etc).

You can't use input->files->get to get individual files for forms rendered from Joomla XML definitions
