### ISSUE TITLE
Menu SmartSearch do not show Meta Description

### ISSUE THREAD

**Issue by ioiogithub** [joomla/joomla-cms#20737]
### Steps to reproduce the issue
If I create a menu item as Search Engine in Joomla and then I fill in the field "Meta Description" for this menu item, the meta description is not inserted in the page.

### Expected result
I expect that the meta description is displayed in the output code.

### Actual result
No meta description in output code

### System information (as much as possible)
J! 3.8.8 - PHP 	7.0.30

**Comment by brianteeman** [comment]
I can not replicate this. Are you using one of the default templates? If not can you test with protostar please

**Comment by carlitorweb** [comment]
I can not replicate this on last staging. 
![screenshot_20180613115459](https://user-images.githubusercontent.com/3956472/41362860-70e67af2-6f00-11e8-8a0e-2fdad8edbe07.png)
![screenshot_20180613115541](https://user-images.githubusercontent.com/3956472/41362861-71203a44-6f00-11e8-9f54-53f225bf5b2f.png)

**Comment by ioiogithub** [comment]
I've tested also with Protostar, same issue on 2 production sites. I will
check further.


Il mer 13 giu 2018, 17:03 Brian Teeman <notifications@github.com> ha
scritto:

**Comment by ghost** [comment]
@ioiogithub closed in the Meantime. Please reopen if needed.

**Comment by ioiogithub** [comment]
Hi, I've done a new test on a fresh Joomla! 3.8.8 installation with PHP 7.0.30 and got the same issue.

Those are the steps to reproduce the issue in my case:
- fresh Joomla! 3.8.8 installation - italian language
- remove any meta description in global configuration, if present (for example created during installation by some installer)
- create a menù item as "Search Engine > Search" in the main menu
- fill in the meta description text area for this menù item
- navigate to the Search menù (do not do any search! just go to this page)

The meta description in this case is not inserted in output code. I've seen this in every site I build.

If you do perform a search in this page, then the results page has the meta description otherwise, not.

**Comment by brianteeman** [comment]
What am I doing differently - because it works for me?
![search](https://user-images.githubusercontent.com/1296369/41460737-8f09ed62-7085-11e8-92c7-387b4139cd32.gif)

**Comment by ioiogithub** [comment]
Hi Brian, I've understood the problem now. Due to the italian translation of my J! version I told you that the bug is present in the Search Engine, meanwhile for the English version I would have told you to create a menu item as "Smart Search". i've tested it with a fresh J!3.8.8 installation in english version and I've found the same issue in the Smart Search page. So please reproduce it on the Smart Search page. Thanks in advance.

**Comment by brianteeman** [comment]
Yes thats a bug - reopening issue

**Comment by brianteeman** [comment]
Closing again as I have created a pull request for testing see #20772
