### ISSUE TITLE
Image preview inside com_media no load

### ISSUE THREAD

**Issue by carlitorweb** [joomla/joomla-cms#20739]
### Steps to reproduce the issue
Go to com_media and open the preview of an image inside of a directory.

### Expected result
You can see the image preview

### Actual result
No load the image preview.
![screenshot_20180613111529](https://user-images.githubusercontent.com/3956472/41360960-e7c5b958-6efb-11e8-8300-50381948dfac.png)

### System information (as much as possible)
Joomla 3.8.8

**Comment by brianteeman** [comment]
Can you please test with staging as I believe this has already been solved

**Comment by carlitorweb** [comment]
I did, and checked again now, in the last staging. Also, I checked on a real site

**Comment by Quy** [comment]
Confirmed. Pinging @PhilETaylor Thanks.

**Comment by PhilETaylor** [comment]
@joomla/security

**Comment by PhilETaylor** [comment]
This is a strange one

Yes the / should not be %2f however 

Dev site Works:
http://127.0.0.1:1025/images/headers%2Fwalden-pond.jpg 

Live real sites dont... 
http://realsite.com/images/headers%2Fwalden-pond.jpg

**Comment by carlitorweb** [comment]
And if you load the preview in the root images folder, all work ok.

**Comment by PhilETaylor** [comment]
Additional changes made to PR https://github.com/joomla/joomla-cms/pull/20616 to encompass this case. Please test https://github.com/joomla/joomla-cms/pull/20616 and report on that PR and close this issue
