### ISSUE TITLE
joomla 3.8.8 update breaks section in site

### ISSUE THREAD

**Issue by amateurwebguy** [joomla/joomla-cms#20735]
3.8.8 breaks section in website
I have a reports section within the members area on my website.  The 3.8.8 update breaks the reports section resulting in a blank page.  Deleting and adding the menu item brings back the primary article page but all links are broken leading to a blank pages.  Only happens with this reports section.

### Steps to reproduce the issue
After re-installing multiple times a backup with 3.8.7, I narrowed it the 3.8.8 update.  I confirmed multiple times with site and sql backups going from joomla 3.8.2 to 3.8.7.  The reports section checks out fine after re-install.  The 3.8.8 update was launched. 

## Expected result
Previous updates installed flawlessly with  no issues with any section of website.  Until 3.8.8 update.

## Actual result
The update installed fine each time.  The website is functional but the specific reports section in the members area is broken resulting in a blank page showing. Happens only when 3.8.8 update is initiated. Verified and duplicated many times.  Something in 3.8.8 breaks the section.  Blank page(s) confirmed on different computers and users.  Never happened with any previous update.  Ideas?  Bugs?

### System information (as much as possible)
Rocketheme template, php 7.0.17, mysql 5.6.39, apache web server

### Additional comments
Ideas as I don't want to rebuild the entire reports section and articles.

**Comment by ghost** [comment]
@amateurwebguy Thanks for Report, have you asked help on the [forums](https://forum.joomla.org/)? If so, can you give please a Link to Discussion-Thread?

**Comment by ggppdk** [comment]
Without the actual error, 
it is not possible to say if this is a bug of Joomla 3.8.8

You can try to find the error at the server logs or try this:

In Joomla global config **both**
-- Enable Debug 
-- Set 'Error reporting' to "maximum"
Visit page that shows "blank" now the error should be visible (probably)

Copy the full text that is shown to your notepad, **and then go back to global config and disable both debug and set Error reporting back to** its previous value (?) "Default"

Paste the error here

**Comment by brianteeman** [comment]
Closing this at this time - it can always be reopened if updated
