### ISSUE TITLE
Locked Out of Joomla

### ISSUE THREAD

**Issue by Kfritz0627** [joomla/joomla-cms#20742]
### Steps to reproduce the issue
I somehow locked myself out of my website and Joomla.  When I try to login Joomla says I don't have an account.  My email is not recognized when I try to reset my password.  When I try to access my website for administration it doesn't recognize my username and password either.  Help!

**Comment by brianteeman** [comment]
Sorry to hear that. Don't panic.

If you go to the forum https://forum.joomla.org then they will be able to help
