### ISSUE TITLE
[4.0] 20650 Custom Element: Joomla! Toolbar button

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#20756]
### Steps to reproduce the issue
Since the merge of this PR last night it has revealed some broken behaviour in the script by @Fedik 
toolbar buttons that can't be used are disabled - this is great start to progressive disclosure

### Expected result
Publish button is disabled on the toolbar by default
Once an item is selected then it is enabled
Once the item is deselected then the publish button will be disabled again

### Actual result
The publish button is only disabled again on a page load not on deselecting an item- see video
![menubar](https://user-images.githubusercontent.com/1296369/41408728-8f71aa48-6fcb-11e8-9e20-cf5488c99927.gif)

**Comment by Fedik** [comment]
hm, strange, 
need to check again

**Comment by Fedik** [comment]
okay, I can confirm, 
will try to make a patch at  weekend

**Comment by Fedik** [comment]
Please test #20777

**Comment by ghost** [comment]
closed as having Pull Request #20777

**Comment by ghost** [comment]
Changed Title to show its about [4.0].<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20756">issues.joomla.org/tracker/joomla-cms/20756</a>.</sub>
