### ISSUE TITLE
session cookie / db entry and language cookie preference

### ISSUE THREAD

**Issue by pieter-groeneweg** [joomla/joomla-cms#20768]
I cannot find in all issues closed or opened. But I would like to ask a question with the developers.

Correct me if I am wrong, but I thought in the past there was a specific cookie set for the language selection when the language switcher module / plugin was published. It now seems this preference is stored in the session db tied to the session cookie.

1. Is that true?
2. Since approximately when is this?

Thanks! It would be very helpfull to know.

**Comment by mbabker** [comment]
After https://github.com/joomla/joomla-cms/pull/12306 the plugin was changed to read the preference from the session once it has been set, but ultimately it is still based on a cookie.

**Comment by pieter-groeneweg** [comment]
@mbabker, thank you very much! That is of great help.
