### ISSUE TITLE
[4.0] Installer - install languages

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#20762]
### Steps to reproduce the issue
Using J4 follow the installation process and install a second language eg french

### Expected result
Throbber is displayed over the language screen

### Actual result
Throbber is displayed over the install sample data screen

<img width="605" alt="chrome_2018-06-14_18-22-55" src="https://user-images.githubusercontent.com/1296369/41427815-01fb2876-7000-11e8-9b5f-201020731fb8.png">

**Comment by Quy** [comment]
Duplicate #16337

**Comment by brianteeman** [comment]
@quy completely unrelated
