### ISSUE TITLE
[4.0] Installer ftp etc

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#20774]
If joomla does not have the necessary permissions to create the configuration.php then you will get the following screen but there is no option to supply the ftp details 

<img width="548" alt="chrome_2018-06-15_14-32-19" src="https://user-images.githubusercontent.com/1296369/41470622-0d15d9f0-70a9-11e8-9d9a-9786edb0095d.png">

@dgrammatiko @wilsonge

**Comment by wilsonge** [comment]
I know dimitris really struggled to find a server that he could test the ftp setup on. this should be the opportunity he needs :)

**Comment by brianteeman** [comment]
I changed the code to make that screen appear

**Comment by HLeithner** [comment]
any solution to this? @brianteeman which code did you changed?

**Comment by dgrammatiko** [comment]
IIRC the idea back then was to make a check if the installation has the right permissions to write a file and if not provide a simple form (in the first screen were we do the rest of the checks against the prerequisites) and only if the supplied credentials were correct (eg file can be created/deleted) continue to the normal installation. Unfortunately, I wasn't able to reproduce such an environment locally although many people suggested quite some options. Tobias provided a server but that wasn't realistically usable for developing (and writing code upload and then check is really painstakingly slow process).

Anyways this needs to be fixed, obviously, thus I wanted to point out what was the initial idea for the implementation

**Comment by dgrammatiko** [comment]
BTW we still miss another thing that it was introduced somewhere in the 3.7 (file creation on the server before continue) and that one should also be introduced in the checks page (although it refers to the database)

**Comment by brianteeman** [comment]
@dgrammatiko we have a release blocker issue as a reminder for that as well iirc

**Comment by wilsonge** [comment]
We do https://github.com/joomla/joomla-cms/issues/18736

**Comment by PhilETaylor** [comment]
> I know dimitris really struggled to find a server that he could test the ftp setup on

Do people know how to use docker/docker-compose? if so I can build you an infrastructure-in-a-container that will provide the services you need in one place alltogether

**Comment by wilsonge** [comment]
That would be good enough for me

**Comment by PhilETaylor** [comment]
Almost there - in the meantime can I say that Joomla 3 sucks and its currently impossible to install Joomla 3 over the FTP layer due to bugs... but once installed (manually uploading the configuration.php) the FTP layer then works 

Lost time so far: 3 hours...

**Comment by brianteeman** [comment]
I am glad you could confirm that, because any reason to support FTP install for j4 is now pointless.

**Comment by PhilETaylor** [comment]
For once, we agree. Dropping the FTP layer in Joomla 4 makes perfect sense. Its 2020.

However there are still web hosts out there, and self-managed servers, that have a bad set up where the apache user is different from the ftp user and permissions nightmares.  So the FTP layer overcomes those cases. 

Its a useless feature when used on professional web hosting though.

**Comment by dgrammatiko** [comment]
> So the FTP layer overcomes those cases.

Practically **WHO** will ever install directly the software in a host?
I think the whole approach is based on assumptions.. Most people will do any work on a localhost and then upload it to the server and actually this should be the expected behaviour. For those that want to have a staging dev they're already have more than adequate knowledge to deal with installing Joomla directly on a server...

Are you trying to solve a non existing problem here (again)?

**Comment by PhilETaylor** [comment]
> upload it to the server

If the server is a professionally installed correctly configured server... perfect.

But if its a self-installed self-managed Out-of-the-box server where the FTP user and the Apache user are different... then the FTP layer is useful.

I doubt anyone is using it though. And those that are are exposing their passwords in plain text in configuration.php

Its not my decision to remove the FTP layer, and Im not promoting keeping it, I just offering to create an infrastructure in docker so things could be tested. That I have done and am uploading it now

**Comment by brianteeman** [comment]
My point was that if it doesnt work under J3 and no one has reported this then we can perhaps conclude that no one needs to install joomla this way. If that conclusion is correct then we dont need to offer it in J4 either.

Note I am talking about FTP installation and not FTP layer

**Comment by PhilETaylor** [comment]
Well **FTP Installation** means nothing more than "storing the configuration.php using the FTP Layer" 

That 100% doesnt work in Joomla 3.9.19 at all.

**Comment by dgrammatiko** [comment]
> That 100% doesnt work in Joomla 3.9.19 at all.

So that aligns perfectly with what @brianteeman wrote above. If nobody reported then probably (assumption here) nobody is using it. I'm fine with this assumption...

**Comment by PhilETaylor** [comment]
Also on this page the Verify FTP settings and the Autofind button do nothing, regardless of whatever is entered (or not entered) 

<img width="711" alt="Screenshot 2020-06-18 at 15 41 25" src="https://user-images.githubusercontent.com/400092/85034704-3ca82380-b17a-11ea-907b-8d4753d16e15.png">

**Comment by PhilETaylor** [comment]
Well as promised, here is a repo that uses docker (and docker-compose), the official Joomla Docker images (with additional FTP server installation, permissions modifications etc) to fake a "server that needs the FTP layer to install and run Joomla"

https://github.com/PhilETaylor/joomla-ftptest

Its not pretty, its not permanent, it is what it is. 

This was not a worthless task though, as two more security issues found and reported to the JSST (@SniperSister) during this process...

**Comment by PhilETaylor** [comment]
Bringing over the screenshot asked for from https://github.com/joomla/joomla-cms/issues/29618#issuecomment-644400780 so it doesn't get lost now that duplicate issue is closed. 

![84708086-bf9d6400-af57-11ea-88e9-dc4759da5aba](https://user-images.githubusercontent.com/400092/95259126-9febbd80-081e-11eb-8abd-4c9de38a82ed.png)

**Comment by Quy** [comment]
Please test PR #31857

**Comment by ghost** [comment]
@Quy close issue?

**Comment by alikon** [comment]
closing as we have a pr to test  #31857

**Comment by ghost** [comment]
@richard67 now you see what i mean https://github.com/joomla/joomla-cms/pull/32006#issuecomment-766612591).
