### ISSUE TITLE
[4.0] Can't setup Joomla 4.0 with special characters in mysql password

### ISSUE THREAD

**Issue by chrkoe** [joomla/joomla-cms#20778]
Hi,

I just wanted to test the Joomla 4.0 Alpha 3 release, which I downloaded here from github.
In the installation process, I get the following error:
Error
Check your database credentials, database type, database name or hostname

I used the same password, which I used under stable 3.8.8, where it worked fine.
The password contains some special characters like ~*;.l&=

(Yes the password is correct. I copied it and also reset it in MySQL.)

**Comment by chrkoe** [comment]
Didn't work with MySQLi AND PDO connector.
In 3.8.8 I used PDO and it worked.

**Comment by ReLater** [comment]
Did you try a nightly build installation? https://developer.joomla.org/nightly-builds.html
As far as I see this should be fixed already https://github.com/joomla/joomla-cms/pull/20414

**Comment by chrkoe** [comment]
It worked when I don't use the & character.

> Did you try a nightly build installation? 

I will try that now. Thanks for the hint.

**Comment by brianteeman** [comment]
All of these should be resolved in the nightly build. I am going to close this but it can always be reopened if you find that's not the case

**Comment by chrkoe** [comment]
I can now confirm, that it is closed in the latest nightly build. Thanks for the fast support. I just tested the 4.0.0-alpha3 tag from the repository.
