### ISSUE TITLE
3.8.8 update crashes section on site - traced to joomla random image module

### ISSUE THREAD

**Issue by amateurwebguy** [joomla/joomla-cms#20783]
Sorry my original post was deleted as I didn't provide additional info as I was focused trying to troubleshoot the  problem (reports) section to determine the problem. The issue was that the 3.8.8 update crashed a section of my site.   The reports section in the members area has as a slider (vinaora) and joomla's random image module assigned to it.
### Steps to reproduce the issue
- replicated crash with different backups 3.8.2 to 3.8.7, the 3.8.8. update crashes the eports section in the members area.
- maximum error reporting enable - **error log below**

_Notice: Array to string conversion in /home/mysite/public_html/plugins/system/modals/helpers/link.php on line 192

Notice: Array to string conversion in /home/mysitepublic_html/plugins/system/modals/helpers/link.php on line 192

Notice: Array to string conversion in /home/mysite/public_html/plugins/system/modals/helpers/link.php on line 192

Notice: Array to string conversion in /home/mysite/public_html/plugins/system/modals/helpers/link.php on line 192

Notice: Array to string conversion in /home/mysite/public_html/plugins/system/modals/helpers/link.php on line 192

Notice: Array to string conversion in /home/mysite/public_html/plugins/system/modals/helpers/link.php on line 192

Notice: Array to string conversion in /home/mysite/public_html/plugins/system/modals/helpers/link.php on line 192

Notice: Array to string conversion in /home/mysite/public_html/plugins/system/modals/helpers/link.php on line 192

Notice: Array to string conversion in /home/mysite/public_html/plugins/system/modals/helpers/link.php on line 192

Warning: require_once(/home/my_site/public_html/libraries/joomla/document/html/renderer/head.php): failed to open stream: No such file or directory in /home/my_site/public_html/templates/rt_plethora/error.php on line 138

Fatal error: require_once(): Failed opening required '/home/my_site/public_html/libraries/joomla/document/html/renderer/head.php' (include_path='.:/opt/alt/php70/usr/share/pear') in /home/my_site/public_html/templates/rt_plethora/error.php on line 138_ 

After several reinstalls, template updates and module disables/enables, I traced the problem to joomla's random image module.

I re-installed a 3.8.7 backup + mysql.  I updated with template.  All the links and modules were operating fine after template update. Then joomla updated with 3.8.8 update which then crashed the section again..  I tried to rebuild the links, page and and module arrangement but the section was broken in many places. I found that joomla's random image module seems to crash the entire section when published.  Turned off, I can see the primary page though the other pages are still broken.

I then re-installd the 3.8.7 backup BUT unpublished the joomla random image module.  Updated with 3.8.8.  All links and pages work. I then updated the template and again no problems.  However, when the joomla random image module is published, the section is broken again.  However, since I disabled the joomla image module before the update, all my pages work when is disable joomla's random image module.   The problem seems to be Joomla's random image module imho (amateur opinion).  Why it breaks, I don't know.

**When the joomla image module published after 3.8.8 update, the error report now is:**

_Notice: Array to string conversion in /home/mysite/public_html/plugins/system/modals/helpers/link.php on line 192

Notice: Array to string conversion in /home/mysite/public_html/plugins/system/modals/helpers/link.php on line 192

Notice: Array to string conversion in /home/mysite/public_html/plugins/system/modals/helpers/link.php on line 192

Notice: Array to string conversion in /home/mysite/public_html/plugins/system/modals/helpers/link.php on line 192

Notice: Array to string conversion in /home/mysite/public_html/plugins/system/modals/helpers/link.php on line 192

Notice: Array to string conversion in /home/mysite/public_html/plugins/system/modals/helpers/link.php on line 192

Notice: Array to string conversion in /home/mysite/public_html/plugins/system/modals/helpers/link.php on line 192

Notice: Array to string conversion in /home/mysite/public_html/plugins/system/modals/helpers/link.php on line 192

Notice: Array to string conversion in /home/mysite/public_html/plugins/system/modals/helpers/link.php on line 192

0
Using $this when not in object context
Oh My Gosh! You Found It!!!
Looks like the page you're trying to visit doesn't exist.
Please check the URL and try your luck again.
Take Me Home_

### System information (as much as possible)
rockettheme phlethora 1.4 and 1.8 templates, php 7.0.17, linux, mysql 5.6.39,apache server, joomla 3.8.7 previously; 3.8.8 currently

### Additional comments
It looks like something in the joomla random image module breaks the pages/links imho.  Site now stable without the built in random image module enabled.

**Comment by conseilgouz** [comment]
This problem has been reported and corrected 22 minutes after 3.8.8 version release, 26 days ago.....

Please check https://github.com/joomla/joomla-cms/pull/20533

Pascal

**Comment by brianteeman** [comment]
It is also on the release faq.
