### ISSUE TITLE
[CI] Add code linter for lowest supported PHP version

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#20782]
We should add code linting to our CI integrations to scan over changed files to ensure the syntax remains compatible with our lowest supported PHP version.  It's way too easy to introduce newer version syntax into files that have zero test coverage where the only way to detect issues is going to be thorough reading of diffs or one of the low number of users on old versions raising an issue.

There's already a lint command in `build.xml` which will scan the full repo, in theory it should be possible to get changed files in a pull request and run `php -l` on that list of files.

**Comment by mbabker** [comment]
We have enough CI related issues without adding to the wishlist.

**Comment by wojsmol** [comment]
@mbabker there even better way then `php -l` see [this project](https://github.com/PHPCompatibility/PHPCompatibility).

**Comment by mbabker** [comment]
Well aware, I oversee the Joomla compatibility ruleset for that 😉

**Comment by wojsmol** [comment]
Then what besides the general problems with CI blocks us from using this project to achieve the purpose described in this issue?

**Comment by mbabker** [comment]
It doesn't support PHPCS 1.x and aside from the work @photodude has been doing there is very little effort in moving the CMS from using the long deprecated PHPCS 1.x releases to PHPCS 2.x or 3.x.

**Comment by wojsmol** [comment]
@mbabker PHPCS fixer 2.0 config in merged to 4.0-dev via https://github.com/joomla/joomla-cms/pull/18877.

**Comment by mbabker** [comment]
PHP-CS-Fixer is a different tool from PHP_CodeSniffer (commonly acronymed as PHPCS).

**Comment by wojsmol** [comment]
But we are one step closer.
