### ISSUE TITLE
com_contacts does not show global options in menu

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#20780]
### Steps to reproduce the issue
Create a com contacts menu item.  Click on the "category" tab.  Options are set to "use global"

### Expected result
Options should say something like "use global (show)" or "use global (hide"

### Actual result
Use global is shown but to find out what the setting is you will have to go into options.  Unlike on com_contact when it will tell you the global option (a much nicer workflow when troubleshooting).  See screenshots for more clarity (hopefully)

(https://issues.joomla.org/uploads/1/15c0b2cb61d470943fcee549d8e076a0.txt)![screen shot 2018-06-16 at 19 13 07](https://issues.joomla.org/uploads/1/b1e9a6b087521ac61f4385fa3cb54edb.png)

### System information (as much as possible)
[systeminfo-2018-06-16T14_13_36-05_00.txt]

### Additional comments

![screen shot 2018-06-16 at 19 13 07](https://issues.joomla.org/uploads/1/c3b21642b2465ca443be0aaa4735c5b7.png)

**Comment by ReLater** [comment]
I cannot confirm this issue with any menu item type of group "Contacts".
**Tested with current staging nightly build 3.8.9-dev .**

Example with menu type "List Contacts in a Category"

![16-06-_2018_23-31-02](https://user-images.githubusercontent.com/20780646/41502590-d0ca5fe6-71bd-11e8-9e20-6d8417448084.png)

**Comment by ghost** [comment]
Can't confirm on 3.8.8 too, so closing this Issue as unconfirmed Report.

![bildschirmfoto 2018-06-17 um 05 46 48](https://user-images.githubusercontent.com/8235763/41504529-0cbbf652-71f2-11e8-852c-d1a8bff99ceb.jpg)

**Comment by uglyeoin** [comment]
I see the same as you today.  Yesterday I saw this:
![com_contacts--use-global--not-shown](https://user-images.githubusercontent.com/4665225/41507506-63d7dc56-722b-11e8-85c8-8062b2bba362.png)
I cannot explain how there are two different results, but if I ever understand I will let you know.
