### ISSUE TITLE
[4.0] Cassiopeia SCSS does not compile

### ISSUE THREAD

**Issue by stutteringp0et** [joomla/joomla-cms#20798]
### Steps to reproduce the issue

Attempt to compile the Cassiopeia SCSS files.  

sass scss/template.scss css/template.css
    ../../media/vendor/bootstrap/scss/_root.scss:4: Invalid CSS after "...lor}: #{$value}": expected "{", was ";" (Sass::SyntaxError)

sassc scss/template.css css/template.css
    Error: Invalid CSS after "...mplate-columns:": expected expression (e.g. 1px, bold), was "[full-start] minmax"
        on line 17 of scss/blocks/_css-grid.scss

### Expected result

compiled css

### Actual result

errors (above)

### System information (as much as possible)

Joomla 4 alpha 3
PHP 7.2.5
Sass 3.4.23
sassc: 3.4.5
libsass: 3.4.8
sass2scss: 1.1.1
sass: 3.4

**Comment by ghost** [comment]
Changed Title to show Issue is about 4.0.

**Comment by C-Lodder** [comment]
You need to run:

```
node build --compilecss
```

to compile the template SCSS.

**Comment by stutteringp0et** [comment]
So, it doesn't compile with the official compilers (Ruby/C) - ok
