### ISSUE TITLE
[3.8.8] user can't be deleted

### ISSUE THREAD

**Issue by wunschradio** [joomla/joomla-cms#20793]
### Steps to reproduce the issue
Go to users, select a user and delete

### Expected result
user should be deleted

### Actual result
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 4 

### System information (as much as possible)
Joomla 3.8.8
mySQL:  5.5.5-10.0.32-MariaDB-0+deb8u1 
PHP:  7.1.18

**Comment by carlitorweb** [comment]
I cant reproduce your issue. Tested in the last staging and a real site.

**Comment by Quy** [comment]
Unable to reproduce too. Under `Global Configuration > System`, please enable `Debug System` and post debug info.

**Comment by wunschradio** [comment]
Tested on several sites, but you are right. It's not happening on all sites. Here is the debug info:
`

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/joomla/database/driver/mysqli.php:650
2 | JDatabaseDriverMysqli->execute() | JROOT/libraries/joomla/database/driver.php:1691
3 | JDatabaseDriver->loadObjectList() | JROOT/plugins/user/jomsocialuser/jomsocialuser.php:281
4 | plgUserJomSocialUser->deleteFromCommunityMsg() | JROOT/plugins/user/jomsocialuser/jomsocialuser.php:41
5 | plgUserJomSocialUser->onBeforeDeleteUser() | JROOT/plugins/user/jomsocialuser/jomsocialuser.php:64
6 | plgUserJomSocialUser->onUserBeforeDelete() | JROOT/libraries/joomla/event/event.php:70
7 | JEvent->update() | JROOT/libraries/joomla/event/dispatcher.php:160
8 | JEventDispatcher->trigger() | JROOT/administrator/components/com_users/models/user.php:379
9 | UsersModelUser->delete() | JROOT/libraries/src/MVC/Controller/AdminController.php:132
10 | Joomla\CMS\MVC\Controller\AdminController->delete() | JROOT/libraries/src/MVC/Controller/BaseController.php:710
11 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_users/users.php:21
12 | require_once() | JROOT/libraries/src/Component/ComponentHelper.php:382
13 | Joomla\CMS\Component\ComponentHelper::executeComponent() | JROOT/libraries/src/Component/ComponentHelper.php:357
14 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:101
15 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:159
16 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:195
17 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/index.php:51

`
Seems to be a problem of JomSocial. The problem does not occur on other sites. Sorry for adding an issue while its not Joomla's fault. I just opened this because it happened in the Joomla core user section.

**Comment by brianteeman** [comment]
As shown by the stack trace this is a problem with nonsocial and not joomla. You should ask them for support.

**Comment by carlitorweb** [comment]
Seen you have a 3rd extension making problem on you site "jomsocialuser"
