### ISSUE TITLE
[4.0] Check In package-lock.json

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#20799]
Is there any reason [this bit](https://github.com/joomla/joomla-cms/blob/64a6334637382ef1eab24ad70a2c2b58f40b71f1/.gitignore#L34-L36) still needs to be in gitignore?  And if not can someone check in a `package-lock.json` file at the preferred state please?

**Comment by wilsonge** [comment]
Fixed with https://github.com/joomla/joomla-cms/commit/6e949df1e210580d0b3c9e8d9593c57d935f4c03
