### ISSUE TITLE
Article News Flash module doesn't show images

### ISSUE THREAD

**Issue by arrowthemes** [joomla/joomla-cms#20803]
### Steps to reproduce the issue
1. Create a new module of type Article News Flash > and assign a Category with images.
2. Set the setting 'Show Images' to Yes.

### Expected result
1. Images from the articles should show besides the news feed

### Actual result
No images are shown

### System information (as much as possible)
Latest Joomla 3.8.8
Database Version | 5.6.40
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 5.6.33

**Comment by SharkyKZ** [comment]
Are you talking about Articles - Newsflash module? Currently, `Show Images` option decides whether to strip images from introtext. An option to display other images is being added to 3.9. See PR #20169.

**Comment by arrowthemes** [comment]
Yes. The images don't show in the intro of the News Feed. It doesn't change anything when you set 'Show Images' to Yes or No.

**Comment by SharkyKZ** [comment]
`Show Introtext` needs to be set to `Yes`  as well.

**Comment by arrowthemes** [comment]
Show Introtext is set to Yes.

**Comment by arrowthemes** [comment]
Here's the settings I'm using
<img width="505" alt="settings" src="https://user-images.githubusercontent.com/1540099/41644998-62057fa6-7478-11e8-805c-fed2d78d6df0.png">

**Comment by brianteeman** [comment]
The current code refers to images inside the body text of your article and not any images defined in the images_links tab

**Comment by arrowthemes** [comment]
The description of the 'Show Images' parameter is vague; 'Show Article Images' could mean show the images that have been added to the 'images and links' tab. I stand to be corrected but I think it would be good to allow users to show images added in the article's 'images and links' tab not just the ones added within the article.

**Comment by SharkyKZ** [comment]
As stated in the first comment, this feature will be included in 3.9.

**Comment by brianteeman** [comment]
Closed as already resolved

**Comment by j2studio** [comment]
Im experiencing the same issue in Joomla 3.9.14. The image will only show up if I include it in the intro copy. Which is not really ideal when turning over to a client. If the client uses the Intro Image and Full Image tab I can control the size of those images and it is much easier for the client.

Moreover I am not seeing the Read More link even though it is set to show.

**Comment by brianteeman** [comment]
Then you cannot be doing it correctly or are not using the core module

![image](https://user-images.githubusercontent.com/1296369/73018300-4458db80-3e19-11ea-86fe-191ac920f179.png)

**Comment by j2studio** [comment]
Thanks, Brian, for chiming in. I am actually using the core module and all the buttons are correctly chosen to show the intro image as well as the Read More link. But they are not showing on the from end. :(

NOTE: I also tried to use the default Beez3 template over the YooTHeme template I am using. But no luck.

Please see screen shots.

<img width="1463" alt="newsflash-module" src="https://user-images.githubusercontent.com/931969/73021155-06e25700-3df5-11ea-977c-fc4b7a5c13c1.png">

**Comment by brianteeman** [comment]
Then it must be a template issue with an out of date override. you can check and confirm this by temporarily switching to protostar

**Comment by j2studio** [comment]
![Screen Shot 2020-01-23 at 3 31 10 PM](https://user-images.githubusercontent.com/931969/73021349-66d8fd80-3df5-11ea-9c2e-7ac768d6414f.png)

Prostar

**Comment by j2studio** [comment]
I take that back. When switching to Prostar I forgot to add the {loadposition}. DUH!

So it does, in fact, work. It must be a YooTheme conflict. UGH!

**Comment by brianteeman** [comment]
:)

**Comment by j2studio** [comment]
Also, for those who might be wondering, Joomla will not add a Read More link to the module on the front end unless you actually have a Read More break **in the article.** 

**Sigh** things I learn _after_ I post... lol
