### ISSUE TITLE
[3.9] plg_fields_repeatable. "__DEPLOY_VERSION__ " as version info.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#20808]
### Steps to reproduce the issue
- Joomla 3.9-dev, updated with nightly build.
- Goto extension manager.
- Search for "repeatable".
- See image.
![20-06-_2018_11-57-22](https://user-images.githubusercontent.com/20780646/41651589-2c3ae95c-7481-11e8-8a91-864e8317e7f8.png)

### Additional comments
https://github.com/joomla/joomla-cms/blob/3.9-dev/plugins/fields/repeatable/repeatable.xml#L10

**Comment by Bakual** [comment]
Afaik that will be replaced during the release process of 3.9.0 with the proper version.

**Comment by brianteeman** [comment]
Yes thats correct.
