### ISSUE TITLE
<img> Joomla 3.8.8 issue

### ISSUE THREAD

**Issue by fouadfana** [joomla/joomla-cms#20806]
### Steps to reproduce the issue
create new custom module, write just the following` <img >` then save; please note there is space after img, where if don't put space like `<img>` will works normally.

### Expected result
save the module normally as stay on administrator view  "Backend"

### Actual result
404 error page appear 

### System information (as much as possible)

Joomla 3.8.8

### Additional comments
This issue appear after upgrade to 3.8.8, where thare are many custom modules were working normally before, now once try just save them without any change, 404 error page appear.

**Comment by brianteeman** [comment]
I cannot replicate this nor can I imagine anything in core joomla that could cause a 404 in the joomla admin

**Comment by fouadfana** [comment]
so what that cause the issue after the upgrading?

**Comment by brianteeman** [comment]
I have no idea what other extensions you have on your site. It is probably one of them causing the issue.

Please use the forum for support https://forum.joomla.org

**Comment by fouadfana** [comment]
thank you, i will try to figure it out.
