### ISSUE TITLE
routing issue

### ISSUE THREAD

**Issue by kens1n** [joomla/joomla-cms#20809]
### Steps to reproduce the issue

Enter url my-site.ru/1, my-site.ru/2 or my-site.ru/3gererg

### Expected result

error 404

### Actual result

code 200, and show joomla content material where my-site.ru/number is id of material

### System information (as much as possible)

Joomla 2.5, Joomla 3.8

### Additional comments

Sorry for my english :)

**Comment by ghost** [comment]
can you give please Information which 3.8-Version?

**Comment by kens1n** [comment]
Joomla 3.8.7 with demo information https://yadi.sk/i/JhBVHfjO3YAVyw

sample pages
http://www.test-optim.j289459.myjino.ru/1
http://www.test-optim.j289459.myjino.ru/3
http://www.test-optim.j289459.myjino.ru/4
http://www.test-optim.j289459.myjino.ru/5dfgshrth

com_content list of materials
https://yadi.sk/i/d9OVzRww3YAWaK

**Comment by ghost** [comment]
Can you please test using latest Version 3.8.8?

**Comment by kens1n** [comment]
Update https://yadi.sk/i/aFIUexFb3YAX3S
And the error still exists

**Comment by ReLater** [comment]
That's the normal and often discussed behavior of Joomla.
In short: If no menu item with alias `528dfgshrth` is found the leading number 528 is interpreted as article id. Only if it doesn't exist you'll see a 404 page then.

**Comment by tonypartridge** [comment]
Exactly, it’s the way the routing is built. Nothing can change it unfortunately, except to remove ids from URLs by default to avoid a 404 occurring

**Comment by kens1n** [comment]
I work in a SEO company and this behavior of joomla makes me cry

**Comment by ggppdk** [comment]
@kens1n 

You do not have an issue when these URLs are not generated by the pages of the website itself

So can you explain how are you getting these URLs?
so that everybody can understand and follow your steps to reproduce them ?

**Comment by tonypartridge** [comment]
Also, you can redirect them with a htaccess rule if you need too. It’s not a big deal.

**Comment by ghost** [comment]
Closed as expected Behaviour.

The Issue can always be reopened for further Discussion.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20809">issues.joomla.org/tracker/joomla-cms/20809</a>.</sub>
