### ISSUE TITLE
mod_tags_similar template doesn't load if no similar items

### ISSUE THREAD

**Issue by davidbrooksio** [joomla/joomla-cms#20810]
### Steps to reproduce the issue
Create and publish an instance of mod_tags_similar (Tags - Similar).

### Expected result
If the current page has other items with similar tags then those items will show in the list. If not then an error message will show stating "No matching tags." ( MOD_TAGS_SIMILAR_NO_MATCHING_TAGS ).

### Actual result
If the current page has no items with similar tags then nothing shows (no message).

### System information (as much as possible)
Joomla 3.8.8

### Additional comments
The issue is caused by lines **24 to 27** of `modules/mod_tags_similar/mod_tags_similar.php`.
These lines can be removed because the default template accounts for an empty list and shows the error instead.

**Comment by ghost** [comment]
Issue confirmed.

But i don't know if its expected that nothing is shown if there is no matching tag.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20810">issues.joomla.org/tracker/joomla-cms/20810</a>.</sub>

**Comment by Bakual** [comment]
Imho it's expected that a module doesn't show up if it has nothing to show. Showing a message that there is nothing to show is quite useless :smile:

**Comment by ghost** [comment]
Closed as expected Behaviour. Please reopen it if needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20810">issues.joomla.org/tracker/joomla-cms/20810</a>.</sub>
