### ISSUE TITLE
Field Type Telephone Bug or Unfinished Code

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#20815]
### Steps to reproduce the issue
So I created a field in XML file with type="telephone"

### Expected result
Auto formatted telephone number based on Site Location/TimeZone maybe. 

### Actual result
The telephone number is as is and shown exactly as it is entered.

### Additional Comment
There is a JHhtmlTel class that in understanding of the code, it will supposed to format a telephone number based on the chosen format ($displayplan). But by following how the code works, on line #36, it will explode the variable $number with . delimiter. That line of code assumes that the supplied number is already formatted with dots as delimiter, why?

Anyways, there is no documentation for field type telephone. How do I use it to auto format a telephone number?

**Comment by brianteeman** [comment]
From memory, this field type is pretty useless as the Tel format it supports is the international standard. What you probably want is field type number with a filter of Tel.

**Comment by frogydiak** [comment]
@brianteeman Thanks for the info!
