### ISSUE TITLE
JDatabase (using pdo) seems to return the query instead of true or false

### ISSUE THREAD

**Issue by deathlynocturnal** [joomla/joomla-cms#20813]
### Steps to reproduce the issue
- Create a component
- In the component make a query that does the: `$db->updateObject();` method,
- View the output, for us it comes back as:

### Expected result
Boolean: true/false

### Actual result
<pre>object(PDOStatement)#340 (1) {
 ["queryString"]=>
 string(56) "UPDATE `am_lots` SET `hammer_price`='0' WHERE `id` = '0'"
}</pre>

### System information (as much as possible)
Database Type: MySQL (PDO)
Error reporting: Maximum
Debugging: false
Joomla Version: 3.8.6

### Additional comments
We have literally installed the Joomla instance and started developing, it's been about 2 months, and then we noticed this issue. This doesn't happen when using MySQLi as the driver.

**Comment by mbabker** [comment]
Can't be fixed without a B/C break.  Don't worry about the return value here, at this point if something is using the return of `JDatabaseDriver::execute()` that'll indicate a successful query and a failed query will have an exception thrown.

**Comment by deathlynocturnal** [comment]
Hi @mbabker, thanks for that but that isn't the case, if we create a query that WILL fail, then it still returns the PDOStatement.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20813">issues.joomla.org/tracker/joomla-cms/20813</a>.</sub>

**Comment by deathlynocturnal** [comment]
Therefore doing something like:

<pre>$status = $db->updateObject():
if ($status) {}</pre>

This will always succeed, even if it fails.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20813">issues.joomla.org/tracker/joomla-cms/20813</a>.</sub>

**Comment by mbabker** [comment]
Then that means `PDOStatement::execute()` is returning a true-ish value which our API does not consider a query failure (a query failure being an actual database error, not a "no results" type thing).  If there's a case where it is returning something true-ish that should be evaluated as a false or error case, [this check](https://github.com/joomla/joomla-cms/blob/c8dbb9e0fc9aa2d54f8f935fc9c6e0acfe298115/libraries/joomla/database/driver/pdo.php#L428) needs updated to account for it.

**Comment by deathlynocturnal** [comment]
@mbabker then I would suggest that check needs to be looked at, because only if there is an error within the jDatabase class will it throw an error, otherwise it will execute a update query which fails, and it does not catch it or return anything.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20813">issues.joomla.org/tracker/joomla-cms/20813</a>.</sub>

**Comment by roland-d** [comment]
@dannysmc95 This was just brought to my attention, so I figured I give it a test on Joomla 4, and I see your expected behavior now. A successful query will return a boolean true, a failed query will throw an exception.

If you are not seeing this behavior on Joomla 4 please re-open the issue so we can investigate further.
