### ISSUE TITLE
[4.0] Form field description - none or twopack

### ISSUE THREAD

**Issue by schnuti** [joomla/joomla-cms#20814]
Maybe not a real bug but a B/C problem.

To my surprise a form used in 3.x gets double descriptions in 4.0. Joomla seems to have removed the field descriptions (to avoid this?) you don't see those double descriptions. 

The first thing I had to do was adding a JLayout override to remove the description below the field.

See the image showing the title description and for the alias the alias description + the alias description PopOver. (The standard alias description is still available as you can see.)

![screenshot_3](https://user-images.githubusercontent.com/956537/41660822-6f309e20-749d-11e8-92a9-3988955f903f.jpg)

**Comment by brianteeman** [comment]
that is because we are aiming to remove most description tooltips and so that we can see which are remiaining they have been displayed as a temp measure

**Comment by schnuti** [comment]
OK! You can keep the issue as info or close it.
