### ISSUE TITLE
[3.8] The memcache Cache Storage is not supported on this platform.

### ISSUE THREAD

**Issue by thomasledoux1** [joomla/joomla-cms#20822]
### Steps to reproduce the issue
I changed my configuration.php file to include the following to use Memcached: 
public $caching = '2';
	public $cache_handler = 'memcache';
	public $memcache_server_host = 'memcached-10314.c2.eu-west-1-3.ec2.cloud.redislabs.com';
	public $memcache_server_port = '10314';
	public $memcache_server_user = 'memcached-app98811975';
	public $memcache_server_pass = '********';
I have installed the memcached extension on Heroku, and it was set up automaticly. I received the details above, so I entered the host I received and the port. There was also a username and password given to me, and I did not find how to enter this in the configuration.php so I added as seen above here. Is this maybe where I'm wrong? 

### Expected result
I expected the caching to be done by Memcached and to not receive an error.

### Actual result

Now I get a server 500 error on my heroku webserver, and the following error: 
The memcache Cache Storage is not supported on this platform.

### System information (as much as possible)
- php (7.2.6)
    - ext-gd (bundled with php)
     - nginx (1.8.1)
  - apache (2.4.33)

**Comment by brianteeman** [comment]
memcache and memcached are not the same thing

**Comment by thomasledoux1** [comment]
@brianteeman I tried with the 'memcached' as $cache_handler but got the same error..

**Comment by mbabker** [comment]
For Memcache**d**, the PHP Memcached class must be available (generally true after installing and enabling PHP's `ext/memcached`).

For Memcache, the PHP Memcache class must be available (generally true after installing and enabling PHP's `ext/memcache`, note the official extension at last check wasn't PHP 7 compatible and I'm not entirely sure the fork that's mentioned in the PHP docs comments will actually work with our adapter).

**Comment by wilsonge** [comment]
It's been two months without updates here so I'm assuming this has been solved and am closing the issue. It can always be re-opened if this is still an issue.
