### ISSUE TITLE
Argon2id Password Support

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#20826]
Per https://wiki.php.net/rfc/argon2_password_hash_enhancements Argon2id password hashes will be supported in PHP 7.3.  We should add support for this alongside our existing Argon2i logic.

**Comment by zero-24** [comment]
So just another else if like this one here: https://github.com/joomla/joomla-cms/blob/3.8.8/libraries/src/User/UserHelper.php#L342-L349 correct?

**Comment by mbabker** [comment]
Right.  And in 3.9 it should also be aware of the changes from https://github.com/joomla/joomla-cms/pull/18254.

**Comment by zero-24** [comment]
PR aginst 3.9-dev https://github.com/joomla/joomla-cms/pull/20855 :)
