### ISSUE TITLE
deleted issue

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [joomla/joomla-cms#20824]
REDACTED BY JSST

**Comment by wilsonge** [comment]
Hi,
Thanks for reporting this potential issue. I've deleted the issue contents and it will be reviewed by our security team. Please note there's a private form that's well publicised for submitting issues outside of GitHub. https://developer.joomla.org/security/contact-the-team.html Please use this in the future for submitting any potential security issues as it also allows us to contact you about the results of our investigation

**Comment by carlitorweb** [comment]
@wilsonge this issue must be delete, now Github let you see the edition a comment have. So, the text still here, and anybody can look it.
![screenshot_20180621073106](https://user-images.githubusercontent.com/3956472/41716581-e545fdda-7524-11e8-94dc-0f7e20851bfa.png)

**Comment by mbabker** [comment]
GitHub doesn't support deleting issues.

**Comment by QiAnXinCodeSafe** [comment]
I'm so sorry, I have sent a request to delete this.

**Comment by QiAnXinCodeSafe** [comment]
GitHub Reply:
Thanks for writing in to GitHub Support!

While I can't make any promises, we can definitely investigate the possibility of deleting that issue.

In order to do so, we need to receive contact from an email address associated with a GitHub account that owns or has admin privileges over the repository in question. I'm afraid the email address you're writing from is not associated with a GitHub account that has these privileges over joomla/joomla-cms.

If you can write in from an email address associated with this repository or request an owner/admin contact us we'll certainly do our best to process your request.

All the best,
Lesley

**Comment by SniperSister** [comment]
@360CodeSafe can you drop me a line at security@joomla.org - thanks!
