### ISSUE TITLE
[4.0] installing: "LoginHelper" not found

### ISSUE THREAD

**Issue by stankurd** [joomla/joomla-cms#20828]
### Steps to reproduce the issue
An error has occurred.
Class 'Joomla\Module\Login\Administrator\Helper\LoginHelper' not found

**Comment by carlitorweb** [comment]
You have to delete the file `/libraries/autoload_psr4.php`. Or clone and install again the repo.

**Comment by ghost** [comment]
Changed Title to explain whats the Issue is about.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20828">issues.joomla.org/tracker/joomla-cms/20828</a>.</sub>

**Comment by Quy** [comment]
@brianteeman I assume this is the same issue as #20902.

**Comment by roland-d** [comment]
@Quy As far as I can see, it is.

**Comment by brianteeman** [comment]
yes its the same thing.

I am closing this as there is no bug to fix
