### ISSUE TITLE
[4.0] Toolbar "Save" button border radius

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#20836]
### Steps to reproduce the issue

Since the toolbar buttons have been moved to custom elements, the border radius for the "Save" button has come back.

This is because the button has been wrapped in a custom element, therefore the following CSS doesn't apply:

```
.btn-group > .btn:not(:last-child):not(.dropdown-toggle),
.btn-group > .btn-group:not(:last-child) > .btn {
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
}
```

![screeny2](https://user-images.githubusercontent.com/2019801/41774017-e6c11a90-7615-11e8-87b1-6b26703decaf.png)

### System information (as much as possible)

- Joomla 4.0-nightly

**Comment by Quy** [comment]
I assume this is no longer applicable with the new backend template.
