### ISSUE TITLE
[4.0] Installer - incompatible.html

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#20832]
The js being called (error-locales.js) will not be loaded if joomla is being installed from a subdirectory and not the root

**Comment by dgrammatiko** [comment]
Grrrr....

**Comment by dgrammatiko** [comment]
@brianteeman can you provide some steps to reproduce it (is it on the installation or the normal joomla that throws)?

**Comment by brianteeman** [comment]
change the minimum php requirement here https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/index.php#L16

that will trigger the  loading of incompatible.html

**Comment by ghost** [comment]
closed as having Pull Request #20923
