### ISSUE TITLE
[4.0][RFC] Question concerning component development

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#20838]
I'm making my first attempts to turn a j3 component into a j4 component. 

### Steps to reproduce the issue

For this I installed my component and made basically the steps Allon explained in this video: https://www.youtube.com/watch?v=jUc5sMqb22E

In addition I had a look at the 4.0-dev weblinks branch: https://github.com/joomla-extensions/weblinks/tree/4.0-dev/src/administrator/components/com_weblinks

After that I had for the backend `J3 template-files` in the folder `administrator/component/com_mycom/views/VIEWNAME/tmpl` and `J4 template-files` in the folder `administrator/component/com_mycom/tmpl/VIEWNAME` This works well for me so far.

After that I made the same for the frontend.

### Actual result

In the frontend I noticed that in the template manager two overrides are displayed. 

![templates customise atum test administration](https://user-images.githubusercontent.com/9974686/41775966-462f73fe-7626-11e8-802b-85fd086836de.png)

Once the files are listed in the J3 template directory (`component/com_mycom/views/VIEWNAME/tmpl` ) and then the files in the J4 template directory (`/component/com_mycom/tmpl/VIEWNAME`).

### Expected result

Actually, I thought that only the files in the directory `/component/com_mycom/tmpl/VIEWNAME `are offered as override in J4.

### System information (as much as possible)
Current 4.0-dev Branch on Ubuntu 18.04

### Additional question
The question I have is whether it is allowed to create tmpl-files in the directory `/tmpl/VIEWNAME` and at the same time in the (J3-directory) `views/VIEWNAME/tmpl`. 

This works in the backend for me. But maybe I miss a problem.

**Comment by laoneo** [comment]
This is a bug. Actually there is no cleanup made after upgrade and then are both folders in the system.

**Comment by astridx** [comment]
@laoneo 
What do you mean with cleanup? Where should this be done?

**Comment by astridx** [comment]
@laoneo 
I think I found what you mean. Do you mean this method:
https://github.com/joomla/joomla-cms/blob/e6abbff595fe1bb4e6b49f24d7c3db43f0554285/administrator/components/com_admin/script.php#L271

In this method all Joomla! core views-folders are deleted.
In Joomla 4, third party extensions may not contain a folder `views` with templates anymore, too?

**Comment by wilsonge** [comment]
You can do one or the other. You shouldn't have both. The 3.x locations will continue to be supported as long as you want to support J3.x. When you choose to upgrade to the J4 way of doing things with namespaces you'll totally remove the `views` folder
