### ISSUE TITLE
[Feature] Job System, AKA Poor Man's Cron

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#20839]
We're starting to make heavy use of the `onAfterRespond` event to take care of some actions that we would prefer to delegate to a CLI/cron infrastructure, but 3.x doesn't have the greatest CLI framework and we don't want to force users to set up cron jobs so this results in adding new plugins with some kind of post-request logic (the session cleanup stuff in that plugin, update notification plugin for core updates, and the privacy system is introducing several post-request tasks).

It would be really good if we could have a basic job system that could be run either as a system plugin at `onAfterRespond` or hooked up to a cron job on CLI to be able to schedule and execute tasks like this.

**Comment by alikon** [comment]
a basic scheduler proposal https://github.com/joomla-projects/privacy-framework/pull/133

**Comment by brianteeman** [comment]
Closing here as @alikon has started
