### ISSUE TITLE
[4.0] Smart search input losing focus while typing

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#20859]
### Steps to reproduce the issue
Create a smart search module.
Open frontend
Try typing some text in to the module input

### Expected result
Input field loses focus while typing (after approx. 3 characters)

### Actual result
Input field does not lose focus while typing

### System information (as much as possible)
Finding issue in Firefox and Chrome
Windows.

**Comment by infograf768** [comment]
same on mac browsers

**Comment by mbabker** [comment]
If I were to take a guess it's something to do with the JavaScript and search suggestions feature (if that's still in place, I can't keep up with all the PRs these days).

**Comment by ciar4n** [comment]
Seems to be alright. Input loses focus with the suggestions been displayed.

**Comment by Hackwar** [comment]
@mbabker indeed, some JS issue. But not because of one of my PRs. That was happening before I started and I'm too stupid to debug this properly.

**Comment by infograf768** [comment]
I confirm. This issue is js related and was present before Hannes patches.

**Comment by infograf768** [comment]
Closing this as we a PR
https://github.com/joomla/joomla-cms/pull/20888
