### ISSUE TITLE
[4.0] FileSystem - Local : What is this plugin for?

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#20851]
Some may have remarked that we have in 4.0 a new type of plugins : Filesystem.

In this folder is a plugin called "Local"

<img width="742" alt="screen shot 2018-06-24 at 07 10 31" src="https://user-images.githubusercontent.com/869724/41816167-2ca12c12-777e-11e8-949c-e830d63f74a9.png">

Directories show in the list to choose from
<img width="302" alt="screen shot 2018-06-24 at 07 23 56" src="https://user-images.githubusercontent.com/869724/41816221-aeb967ea-777f-11e8-8ea0-ff30944439c6.png">

No idea what this does or not as the description is kind of useless...
Could someone be kind enough to give some light about both parameters and what happens when enabled or disabled?

**Comment by roland-d** [comment]
If I am not mistaken this is for the new Media Manager. This way you can allow the media manager to store images wherever you want, local, FTP server, SFTP server, Amazon, etc. For each storage location you would have a plugin. 

In the plugin you specify the base folder of where the images are going to be stored on your storage location.

**Comment by laoneo** [comment]
Exactly. Thanks @roland-d.

**Comment by infograf768** [comment]
Thanks.
May I respectfully ask for a new Description as I doubt that anyone has a reliable crystall ball to find out its use.

Also, the folder should at least give a hint of what the plugins are for. Calling it `filesystem` is real confusing. Why not something more explicit like "mediastorage" ?

**Comment by infograf768** [comment]
Also, how does it fit with the Path Folder as defined in Media Options?

**Comment by infograf768** [comment]
Found out that we can add a new images folder through this plugin. Nice feature.
But we can also hide the basic `images` folder without really knowing what we do before testing.

If plugin disabled we get:
`Warning
No filesystem providers have been found. Please enable at least one filesystem plugin.`

No link to the plugin manager and specifically this group of plugins for these in the Warning.
Really needs some care. ;)

**Comment by infograf768** [comment]
will propose some PR

**Comment by infograf768** [comment]
Closing as we have PR https://github.com/joomla/joomla-cms/pull/20854

Note: did not change the `filesystem` folder and plugin type for now. Does not look like a heavy task to do. Will do if encouraged to do so.

**Comment by laoneo** [comment]
We named it filesystem, because a long, long term goal is to abstract the filesystem of Joomla with a better cloud integration instead of just local and ftp.

**Comment by infograf768** [comment]
@laoneo 
Just curious: would there be plugins in that category which would not be media related?

**Comment by laoneo** [comment]
Not in the closer future, but I hope on one point that we can work localy with more than only FTP and the local filesystem.

**Comment by brianteeman** [comment]
But wouldn't they be more than media? I agree that at this time these plugins should be referred to as media filesystems.

**Comment by laoneo** [comment]
Hopefully yes. For example assets (mainly the media folder) can be on cloud systems too. There are definitely more use cases where I can't think of for now. Perhaps I'm too naive but I would leave them for now.
