### ISSUE TITLE
[com_fields] Media Select Field - Style issue

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#20869]
### What needs to be fixed
The media select button (Custom Fields) may be to wide in some views
![grafik](https://user-images.githubusercontent.com/828371/41896816-e94b9746-7925-11e8-980b-b7c564855e40.png)

### Why this should be fixed
User can't access the select button

### How would you fix it
Make the field adaptable to outer container somehow?

**Comment by SharkyKZ** [comment]
See PR #20209.

**Comment by ghost** [comment]
Closed as duplicate Report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20869">issues.joomla.org/tracker/joomla-cms/20869</a>.</sub>

**Comment by ghost** [comment]
@coolcat-creations can you please test #20209 as it needs on more (successfully) test?

**Comment by ciar4n** [comment]
This looks a different issue to what #20209 fixes.

**Comment by coolcat-creations** [comment]
Yes just tried and #20209 does not fix it...

**Comment by ghost** [comment]
Reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20869">issues.joomla.org/tracker/joomla-cms/20869</a>.</sub>

**Comment by coolcat-creations** [comment]
I have the solution if someone has time to change the less and to compile it, if not I will update it next week:
.field-media-input has to have an width:auto; and not 100% when showing in a subform.

.control-group, .controls, .controls input[type="text"], .controls input[type="number"], .controls input[type="email"], .controls select, .controls textarea is overriding this width so it has to be specified deeper.

**Comment by ciar4n** [comment]
If we could just get https://github.com/joomla/joomla-cms/pull/20209 tested and merged, I will continue fixing up these subforms.

**Comment by ghost** [comment]
@ciar4n #20209 is merged.

**Comment by brianteeman** [comment]
@coolcat-creations Can you create the PR to fix your problem please as promised. - thanks

**Comment by coolcat-creations** [comment]
@brianteeman I understood @ciar4n in the post below mine that he will do it. What is the status?

**Comment by brianteeman** [comment]
I don't care who does it. You were the one that said you had the fix so it seemed sensible to me that you would submit the pr. There hasnt been one yet

**Comment by coolcat-creations** [comment]
I asked what the status is to prevent several people working on the same. @ciar4n did you fixed it in the other PR or should I do it?

**Comment by brianteeman** [comment]
the other pr was something else

**Comment by ciar4n** [comment]
@coolcat-creations As stated the other pr was for a different issue. Feel free to create a pr to fix this issue if you already have the solution.

**Comment by coolcat-creations** [comment]
Ok Thanks @ciar4n

**Comment by ghost** [comment]
closed as having Pull Request #21786
