### ISSUE TITLE
[4.0] 'first' and 'last' classes in list view items

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#20862]
Quite a few list type views include logic to add a `first` class to the first item and a `last` class to the last item on the list. Do we really them?

IMO these complicate the views with little benefit. Especially considering we can now easily target these items with CSS pseudo classes like `:first-of-type` and `:last-of-type`.

Example.. https://github.com/joomla/joomla-cms/blob/4.0-dev/components/com_content/tmpl/category/default_children.php#L22-L27

Losing them is a potential b/c break with templates which happen to use them.

**Comment by mbabker** [comment]
I'd say drop them.  About the only reason I can see to keep them is if you're still supporting IE8 where the pseudo-classes aren't reliably available, and that's obviously not in J4's supported stack.

**Comment by C-Lodder** [comment]
Before removing, double check the JS to ensure they're not being referenced there

**Comment by ciar4n** [comment]
PR created #20887

@C-Lodder From what I can make out, they are not been referenced in the JS.
