### ISSUE TITLE
[4.0] Config.xml with addfieldpath property in fieldset

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#20867]
### Steps to reproduce the issue
I created a custom field that I wanted to add as a field in the config.xml file in the root folder of my com_custom. 

So, I added a property addfieldpath="/administrator/components/com_custom/Field".

Going to Options, I see the field is being rendered by using the default layout which is Text. And I knew that my custom field is not being loaded is because anything I do in the method getInput() does not do anything including die().

Is is possible to use a custom field in the config.xml by the way?

### Expected result
My custom field should be rendered.

### Actual result
No custom field is being rendered.

### Additional comments
If it should work, what should be the proper way to adding a field path to the fieldset in config.xml?

**Comment by SharkyKZ** [comment]
I'm not sure if `addfieldpath` is supposed to be broken but 4.0 uses `addfieldprefix`: `addfieldprefix="Joomla\Component\Custom\Administrator\Field"`.

**Comment by frogydiak** [comment]
@SharkyKZ I tried addfieldprefix as well and same thing, it is not loading my custom field. Shouldn't the FormField class spits an error when an xml file is trying to load an unknown field?

**Comment by frogydiak** [comment]
Nevermind, I figured it out. J4.0 is loading custom fields in config.xml just fine. It just need documentation :) and going back to my question on unknown field:

I think it should not load field type text when it cannot load the field class being called. IMO, it would be best for developers to debug if FormHelper throw an exception when field class does not exists (line 203-206 and 218-221).

**Comment by brianteeman** [comment]
Closed. Feel free to submit the documentation to the docs site - it's a wiki and/or submit a pr to add the esception
