### ISSUE TITLE
"Cannot use object of type stdClass as array" in Menu creation/editing

### ISSUE THREAD

**Issue by Shape77** [joomla/joomla-cms#20878]
### Steps to reproduce the issue
I try to create a new menu item or edit a new one

### Expected result
Creation form of a new item / Editing form of old items

### Actual result
Error: "0 Cannot use object of type stdClass as array"

### System information (as much as possible)
PHP Built On | Linux es1.siteground.eu 3.12.18-clouder0 #16 SMP Wed Feb 14 15:05:16 EET 2018 x86_64
-- | --
Database Type | mysql
Database Version | 5.6.36-82.1-log
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.2.5
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.8.10 Stable [ Amani ] 26-June-2018 15:45 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

### Additional comments
I have this issue after updating from Joomla! 3.8.8 to Joomla! 3.8.9, still having issue on Joomla! 3.8.10

**Comment by brianteeman** [comment]
Are you using PWT Sitemap? They reported and confirmed that their extension caused this issue

**Comment by Shape77** [comment]
Nope, but I use JSitemap PRO

**Comment by brianteeman** [comment]
Might be the same problem. Disable it and see and then let us know

**Comment by Shape77** [comment]
I disabled it but I have the same issue. So, JSitemap PRO is not the cause.

**Comment by SharkyKZ** [comment]
Enable debug to see where exactly this error is coming from.

**Comment by mbabker** [comment]
What type of menu item?

Enable debug mode and include a stack trace for the error.

**Comment by Shape77** [comment]
It's from CoalaWeb extension. Thank You for Your support!

**Comment by SharkyKZ** [comment]
This is caused by #20313.

**Comment by AlainRnet** [comment]
helix3 seems to be the cause of the problem. This solved my problem: https://www.joomshaper.com/forums/helix3-plugins-causing-joomal-menu-to-not-work-0-cannot-use-object-of-type-stdclass-as-array

**Comment by mbabker** [comment]
As noted in #20879 it is not a bug in any extension.

**Comment by AlainRnet** [comment]
You're right. I wanted to write that on helix 3, there was a solution... the same solution as on the thread you mention. Many thanks.

**Comment by vegasls** [comment]
I got the same error but in my case it was caused by the google structured data markup plugin by tasso marinos. But after updating to the latest version 3.1.9 it was resoved...

**Comment by Krxon** [comment]
In my case it was outdated vp onepage plugin for virtuemart
After I uninstalled itm problem was solved.

**Comment by channingb** [comment]
I too had the problem.  Thanks vegasls as I use Google Structured Data and updated it from 3.1.8 to 3.1.9.  This solved the problem.

**Comment by vishvakarmaPerfection** [comment]
Hello everyone,
i'm getting same error when i edit/create the menu..
i'm not be use PWT Sitema, CoalaWeb, helix 3, google structured data markup Extension..
we use virtuemart extension but I disabled it but I have the same issue....
please let me what the issue i have..?
thanks.

**Comment by ghost** [comment]
@vishvakarmaPerfection Please ask help on the [forums](https://forum.joomla.org/) as Comments on closed Issues didn't get much Notice.

Pleaes don't comment on different Issues same Comment, thanks.

**Comment by wdburgdorf** [comment]
> helix3 seems to be the cause of the problem. This solved my problem: https://www.joomshaper.com/forums/helix3-plugins-causing-joomal-menu-to-not-work-0-cannot-use-object-of-type-stdclass-as-array

I use Helix3 and have the same issue. The solution is only accessible for paying customers. **AlainRnet**, could you share your solution, please?

**Comment by AlainRnet** [comment]
Sorry, I don't remember and I haven't access either. I seem to remember that the bug is now closed and that it is enough to update Helix.

**Comment by AlainRnet** [comment]
Perhaps you can try :
> Edit file plugins\system\helix3\helix3.php
> 
> Add at about line 54
> (or better at the beginning of method **onContentPrepareForm**)
> `$data = is_object($data) ? (array) $data : $data;`

as described here : https://github.com/joomla/joomla-cms/issues/20879#issuecomment-400450383

**Comment by wdburgdorf** [comment]
Thank you! That helped a lot. I had to disable a few other extensions, too (SJ Mega Menu and Extra Menu Params - both by YouTech/SmartAddons). There is no update for Helix3, and the successor, Helix Ultimate seems dead, too ...

**Comment by ghost** [comment]
> 
> 
> Perhaps you can try :
> 
> > Edit file plugins\system\helix3\helix3.php
> > Add at about line 54
> > (or better at the beginning of method **onContentPrepareForm**)
> > `$data = is_object($data) ? (array) $data : $data;`
> 
> as described here : [#20879 (comment)](https://github.com/joomla/joomla-cms/issues/20879#issuecomment-400450383)

Worked for me, Thanks.

**Comment by ThakarshiSiddhiDev** [comment]
Thanks buddy its working => $data = is_object($data) ? (array) $data : $data; 
On plugins\system\helix3\helix3.php added in beginning of method onContentPrepareForm

**Comment by candidosa2** [comment]
Thank you 
Disabled and the error is gone System - Helix3 Framework
Joomla 39.24<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20878">issues.joomla.org/tracker/joomla-cms/20878</a>.</sub>
