### ISSUE TITLE
Not able to create new menu item after upgrade to J3.8.9

### ISSUE THREAD

**Issue by hans2103** [joomla/joomla-cms#20874]
### Steps to reproduce the issue
- update Joomla to 3.8.9
- login administrator
- create new menu item

### Expected result
- to be able to configure new menu item

### Actual result
- I get an error message
> Cannot use object of type stdClass as array

### System information (as much as possible)
- Joomla 3.8.9
- PHP 7.0.30

**Comment by mbabker** [comment]
Can't confirm.  Created new category blog menu item without issue.

Need more info for this issue.  Specific menu item type.  Enabling debug mode and providing a stack trace.  etc.

**Comment by hans2103** [comment]
found out it is an issue with a third party extension. My bad.

**Comment by brianteeman** [comment]
@hans2103 for anyone else who has this problem what was the extension?

**Comment by hans2103** [comment]
PWT Sitemap -> Issue confirmed by the developer and will be updated soon.

**Comment by brianteeman** [comment]
In theory a x.x.x releaase shouldnt break anything so it would be good to know what made it break

**Comment by SharkyKZ** [comment]
Break made by #20313.

**Comment by vishvakarmaPerfection** [comment]
Hello everyone,
i'm getting same error when i edit/create the menu..
i'm not be use PWT Sitema, CoalaWeb, helix 3, google structured data markup Extension..
we use virtuemart extension but I disabled it but I have the same issue....
please let me what the issue i have..?
thanks.

**Comment by ghost** [comment]
@vishvakarmaPerfection Please ask help on the [forums](https://forum.joomla.org/) as Comments on closed Issues didn't get much Notice.
