### ISSUE TITLE
[3.8.9] Class 'JClassLoader' not found on Windows Based Hosting

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#20875]
**Leaving this here to prevent duplicates, will close if not a major issue later in the day, see how many others effected. As discussed with @mbabker already.**

*MAY* be related to auto loader changes in Joomla 3.8.9 on WINDOWS machines. 

### Steps to reproduce the issue

Upgrade to Joomla 3.8.9

Update failed at
http://justatest/administrator/index.php?option=com_joomlaupdate&task=update.finalise&e63f3ad56a496e6fa0a4db3b96627288=1

### Expected result

No errors

### Actual result

> The update of a clean, out-of-the-box 3.8.8 on localhost (Wampserver 3.1.3, PHP 7.1.4) to 3.8.9 fails with the error Fatal error: Uncaught Error: Class 'JClassLoader' not found in C:\www\justatest\libraries\cms.php on line 40

**Comment by toivo** [comment]
Tested this in a newly installed 3.8.8 site on Wampserver and confirmed the error.

**Comment by PhilETaylor** [comment]
@alekvolsk @progreccor @kkaazzoo @proweb - If you have this issue please state your server configuration, a thumbs up doesnt tell us if you have this issue or just being friendly :)

**Comment by AlekVolsk** [comment]
Windows 8.1, PHP x64 7.0.21 / 7.1.7, mariadb 10.2 x64
```
Fatal error: Uncaught Error: Class 'JClassLoader' not found in C:\OS527\domains\tmp.local\libraries\cms.php:40 Stack trace: #0 C:\OS527\domains\tmp.local\includes\framework.php(18): require_once() #1 C:\OS527\domains\tmp.local\index.php(40): require_once('C:\\OS527\\domain...') #2 {main} thrown in C:\OS527\domains\tmp.local\libraries\cms.php on line 40
```

workaround: extract the **Joomla_3.8.8-Stable-Update_Package** files in the root of the site

---

@PhilETaylor a thumbs up says either to support your post or to agree with your statement or to confirm the described problem

**Comment by Matysh** [comment]
Update 3.8.8 -> 3.8.9
Windows server 2016
Apache 2.4
Php 5.6.35
mariadb 10.2 x64
Valid.

I tryed to replace all file in my installation, but still this error.

**Comment by AlekVolsk** [comment]
@PhilETaylor a thumbs up says either to support your post or to agree with your statement or to confirm the described problem

**Comment by PhilETaylor** [comment]
@AlekVolsk a thumbs up is not helpful when we are trying to gather information about environments effected, especially as your environment is different to the initial reporter. :)

**Comment by AgilityCC** [comment]
I had the same problem with Auto-Update, Partial update via FTP, and full update via FTP.  I had to revert back to 3.8.8.

3.8.9
Windows Server 2012 R2
PHP 5.6.30
IIS 8.5
cgi-fcgi

**Comment by PhilETaylor** [comment]
@agilitycc Please confirm you are on a windows based host?

**Comment by AlekVolsk** [comment]
workaround: extract the **Joomla_3.8.8-Stable-Update_Package** files in the root of the site

**Comment by kkaazzoo** [comment]
Windows 10, PHP x64, 7.1.7, MySQL 5.7 x64.

**Comment by toivo** [comment]
Windows 10, Apache 2.4.23, MySQL 5.7.14, PHP 7.1.14  - all 64-bit in Wampserver 3.1.3

**Comment by brianteeman** [comment]
It is the changes made to address  security issue

**Comment by PhilETaylor** [comment]
> This problem is being investigated/resolved by the Joomla release maintainers and a further announcement will be made by them shortly.

**Comment by AlekVolsk** [comment]
I. e. on your use of servers on the windows platform is unsafe?

**Comment by mbabker** [comment]
See https://github.com/joomla/joomla-cms/pull/20877

**Comment by PhilETaylor** [comment]
@AlekVolsk As documented [here](https://developer.joomla.org/security-centre/741-20180601-core-local-file-inclusion-with-php-5-3.html). It was always a fringe case for PHP 5.3 anyway. 

There is a patch to test... `[here](https://github.com/joomla/joomla-cms/pull/20877)`

**Comment by toivo** [comment]
The patch got my test site up and running, thanks to the team!

**Comment by mikesteele81** [comment]
@PhilETaylor The patch got my site back online. I was then able to apply update 3.8.10 without any trouble.
