### ISSUE TITLE
Where is migrating issue's forum?

### ISSUE THREAD

**Issue by BrendaNRuelas** [joomla/joomla-cms#20880]
I need help with migration of my current Joomla.com website.
But I don't see any support forums. So, forgive me for writing here.
website url: https://brendanruelas.joomla.com
Today I couldn't access my website.
Checking my email I realised that my website need to be migrated until June 29th.
So in the email I clicked the first option, because of course I want my domain and data to be migrated.
After I clicked the first option I was redirected to the launch.joomla.com home page. And... that's it.
So, I don't know if my data can be migrated or not.
I will appreciate any help from Joomla team.

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.

**Comment by jonathanCA** [comment]
Thank you for bringing this to our attention. The emails you are referring to were sent last month and the window of opportunity was set to 2 weeks and responses were collected by the previous provider. At this point it should still be possible to get a copy of your site. We are opening a ticket up in your newly migrated account at CloudAccess.net to follow up. 

Also, we are going to put a message in place for those who also may be clicking the links in those emails this far past the migration time, this should help others who may try the same thing. We greatly appreciate the feedback on this.

**Comment by BrendaNRuelas** [comment]
Yes, my bad. It's been a month since I got this email. 
Thank you very much for the answer. So, that means, my account on CloudAccess.net has been already created? Do I need to create a new one?

And, how long should I wait for my website to be restored? If it's possible, of course..

**Comment by jonathanCA** [comment]
Hi Brenda, your account has been created and your domain name was migrated (default option for those who did not make a selection). We are attempting to migrate your Joomla site now, we will open a ticket for you once this is complete. We've received a few requests for site migrations from people who did not respond to the original emails. If all goes as planned, I expect they will all be migrated by the end of the week.  

Thank you :)
