### ISSUE TITLE
advanced settings for the update server

### ISSUE THREAD

**Issue by motokraft** [joomla/joomla-cms#20883]
Hello! Can I add my own parameters when I check for updates to extensions to the update server address?

**Comment by AlekVolsk** [comment]
What do you mean by your own parameters? do you want to change the update server for a single extension?

**Comment by motokraft** [comment]
Get what will be sent a request to verify the availability of the address added to get the parameters **(?login=name&password=123)**. The password will of course be encrypted.

**Comment by AlekVolsk** [comment]
look in the direction of this [component](https://github.com/joomla-update-org/com_updsrv), it allows you to add your parameters to the url

**Comment by motokraft** [comment]
Standard means of this can not be done?

**Comment by AlekVolsk** [comment]
noup ;(

**Comment by motokraft** [comment]
How to make this update available?

**Comment by AlekVolsk** [comment]
download the release, install the component in the admin like everything should be clear, everything is done as simply and clearly

**Comment by ghost** [comment]
@motokraft if Issue is solved please close it.

**Comment by motokraft** [comment]
The problem is not solved. But the point is to start the flowering

**Comment by ghost** [comment]
ah, i read Comments by @AlekVolsk as Solution for your Issue, so of course Issue stay open.

**Comment by motokraft** [comment]
And why not put it in the core? Again there will be problems with security, or who is too lazy to do it?

**Comment by brianteeman** [comment]
Telling volunteers that they are lazy when you have never contributed is not the way to achieve anything.

**Comment by motokraft** [comment]
**Dobrovoltsy is who?**
Why not just write - thanks for this idea, we are trying to implement it in the created versions. **_(well, or something like this)_**

**Comment by cyrez** [comment]
The way exists, and is by far documented on the web.

Create an installer plugin for your extension, and use this function : 

```
	public function onInstallerBeforePackageDownload(&$url, &$headers)
	{
		// Get the component information from the #__extensions table
		JLoader::import('joomla.application.component.helper');
		$component = JComponentHelper::getComponent('com_component');
		$login = $component->params->get('login', '');
		$password = $component->params->get('password', '');

		// Bind credentials to request by appending it to the update server url
		if ( ! empty($login) && ! empty($password))
		{
			$separator = strpos($url, '?') !== false ? '&' : '?';
			$url .= $separator . 'login=' . $login . '&password=' . $password;
		}

		return true;
	}


```

> who is too lazy to do it?

I wonder who... ;-)

**Comment by cyrez** [comment]
Or this other way (integrated in Joomla core since a bit of time...) : https://github.com/joomla/joomla-cms/pull/2508

**Comment by AlekVolsk** [comment]
Unfortunately, but I see that Joomla developers are only concerned about the development and security of their own projects. Everything that can't be useful to them is ignored, so I have to write my crutches and bicycles. Issue can be closed, still there will be no solution in the kernel, obviously.

**Comment by motokraft** [comment]
The code suggested by **JoomliC** comes up half way. It is executed when the file is downloaded. And I need what would be an event when checking access to the .xml file in which there is a lot of update

**Comment by mbabker** [comment]
The features you're looking for are covered by the two comments from @JoomliC

As an extension developer, you should fill in the `extra_query` column of the update sites table as documented in https://github.com/joomla/joomla-cms/pull/2508 and this will be passed when requesting the update server XML document

Similarly, if you need to send extra information when the actual package is downloaded a plugin hooking the `onInstallerBeforePackageDownload` event is required.

What we do not support is a user editable interface for these features, it is up to the developer to create an interface in their extension to gather the extra data to use with these two features.

What cannot be done with the existing API and featureset?

**Comment by motokraft** [comment]
I can not use extra_query, because the transferred data will be dynamic

**Comment by mbabker** [comment]
Based on what factors?

**Comment by mbabker** [comment]
Also note that since 3.7.0 there is [this hook](https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_installer/models/update.php#L541-L601) which might be of use (though I don't think this one is documented anywhere near as well as the others).

**Comment by motokraft** [comment]
to the address I will add
`<?php '?login='.$user->username.'&password'.$user->password; ?>`
preparePreUpdate function is a good idea

**Comment by motokraft** [comment]
I will add to the address
`<?php '?login='.$user->username.'&password'.$user->password; ?>`
function preparePreUpdate is a good idea
