### ISSUE TITLE
Category list: Can't reset search

### ISSUE THREAD

**Issue by smehrbrodt** [joomla/joomla-cms#20884]
### Steps to reproduce the issue
1. Create a menu entry of type Articles->Category list
2. Go to the tab "List layouts" and select a value for "Filter field", e.g. author.
3. Now go to the frontend and you see the articles from the selected category and a filter field
4. Enter some author which does not exist, hit Return

### Expected result

You get no search results, but should be able to perform a new search query.

### Actual result

You only see the message "There are no articles in this category...". It is not possible to reset the filter or do another search. Even reloading the page doesn't help.

### System information (as much as possible)

Joomla 3.8.10

**Comment by SharkyKZ** [comment]
Can't reproduce this. This was fixed by #11501. Perhaps you have a really old template override?

**Comment by smehrbrodt** [comment]
Ah right, this is fixed in the default template.
Thanks for testing!
