### ISSUE TITLE
ReplyTo in com_contact form not working

### ISSUE THREAD

**Issue by feltkamptv** [joomla/joomla-cms#20886]
When a visitor fills in the contact form and the email is sent, the replyTo field is not correctly populated. So when you reply on the email, you will reply to the main site address instead of the entered email by the visitor.

### Steps to reproduce the issue
Send an email with the contact form.

### Expected result
When replying to an email send with the contact form it should send a reply to the email address which was entered in the form. 

### Actual result
The main sites email is used for replyTo instead of the entered email by the user.

### Quick solution
I solved this quickly with a small change in components/com_contact/controllers/contact.php in the _sendEmail function.

I changed:
```$email   = JStringPunycode::emailToPunycode($data['contact_email']);```

To:
```$email   = $data['contact_email'];```

This fix works because the PHPMailer library already converts the email address to Punycode, so the com_contact component does not have to convert the email address.

**Comment by brianteeman** [comment]
I can not confirm this - as seen from the email headers below on a test from my blog where the email address entered on the contact form submission was brian+testing@teeman.net

```
Received: from [127.0.0.1] (port=55864 helo=m32.siteground.biz) by m32.siteground.biz with smtp (Exim 4.89_34-9f6032f-XX) (envelope-from <blog@teeman.net>) id 1fY6cX-0006kW-7N for brian@teeman.net; Wed, 27 Jun 2018 04:20:13 -0500
To: brian@teeman.net
Subject: Brian Teeman: test
X-PHP-Originating-Script: 552:class.phpmailer.php
Date: Wed, 27 Jun 2018 04:20:13 -0500
From: "brian.teeman.net" <blog@teeman.net>
Reply-To: brian-testing <brian+testing@teeman.net>
Message-ID: <9e609fd04e456350ea727892e8ad2001@brian.teeman.net>

```

**Comment by feltkamptv** [comment]
Maybe it has already been fixed in a newer version or it is because I am using SMTP? I am still using version 3.8.8, with SMTP through Amazon SES.

**Comment by brianteeman** [comment]
No - this has always worked - or we would have had millions of bug reports. 

Please send the email headers

**Comment by feltkamptv** [comment]
I do not see anything wrong in the headers of the email:
```
Received: from a9-91.smtp-out.amazonses.com ([54.240.9.91])
Date: Wed, 27 Jun 2018 11:31:05 +0000
To: support@cryptohopper.com
From: Cryptohopper <noreply@cryptohopper.com>
Reply-To: Pim Feltkamp <info@feltkamp.tv>
Subject: Cryptohopper: Without quick solution
Message-ID: <010001644102e285-1c279bf5-6b2b-4d9e-9b7a-0156f0147dfd-000000@email.amazonses.com>
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
```

I will close this issue now and will start investigating if the issue is with Amazon SES or our email software. But it is still strange that after implementing the mentioned solution, it started working again.
