### ISSUE TITLE
Missing "Select Type" field in Extensions -> Manage (J! 3.8.10)

### ISSUE THREAD

**Issue by ucfnet002** [joomla/joomla-cms#20881]
### Steps to reproduce the issue
Backend -> Extensions -> Manage -> Manage
Search Tools -> Third search field is missing

### Expected result
A search dropdown für types

### Actual result
No search dropdown für types, just an empty field

### System information (as much as possible)
Tested on PHP 5.6 and 7.0
Joomla 3.8.10

![2018-06-26 22_39_52](https://user-images.githubusercontent.com/6213131/41937936-ebad7632-7991-11e8-9ba4-d957b47edf71.png)

**Comment by brianteeman** [comment]
Confirmed

**Comment by mbabker** [comment]
Something is inconsistent here.  It's missing on a live site.  I have it on my local git clone.

**Comment by carlitorweb** [comment]
last staging 
![screenshot_20180626164713](https://user-images.githubusercontent.com/3956472/41938159-47939224-7960-11e8-841c-2921dbebd275.png)

**Comment by brianteeman** [comment]
@mbabker yes same here.

**Comment by mbabker** [comment]
Fixed with direct commit of https://github.com/joomla/joomla-cms/commit/8383f6071aa91e28a6b53904b886c32aab757213

There used to be a differently purposed `JFormFieldType` in com_installer that was removed between 2.5 and 3.0.  The file ended up back in the deleted files list after rebuilding it.  So the file is being deleted from sites during the post-update processing.

**Comment by npsaltakis** [comment]
how to fix this issue???

**Comment by joomdonation** [comment]
Base on the commit, you can get this file https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_installer/models/fields/type.php , and upload it to administrator/components/com_installer/models/fields folder to get the issue sorted

**Comment by woluweb** [comment]
As temporary workaround, note that typing directly what you search for (Language, Component, ...) *does* work : 
![image](https://user-images.githubusercontent.com/4510979/41968651-57185388-7a05-11e8-95fd-2429444d3092.png)

**Comment by gwsdesk** [comment]
confirmed issue

**Comment by brianteeman** [comment]
Congratulations @gwsdesk you have confirmed an issue that has already been fixed

**Comment by gwsdesk** [comment]
Thank you @brianteeman for your oh so nice and kind reaction... Your precious commenting is duly noted! Keep on the good interaction..Great!

**Comment by gwsdesk** [comment]
@mbabker glad to see you agree humiliating people that way. Good management!

**Comment by sozzled** [comment]
Tested by re-creating the deleted file **/administrator/components/com_installer/models/fields/type.php** as suggested by  @joomdonation.  Tested OK.

**Comment by ManfredHuebner** [comment]
Fix works! thanks a lot to you guys :-)

**Comment by kyraslaughter-blip** [comment]
> ### Steps to reproduce the issue
> 
> Backend -> Extensions -> Manage -> Manage Search Tools -> Third search field is missing
> 
> ### Expected result
> 
> A search dropdown für types
> 
> ### Actual result
> 
> No search dropdown für types, just an empty field
> 
> ### System information (as much as possible)
> 
> Tested on PHP 5.6 and 7.0 Joomla 3.8.10
> 
> ![2018-06-26 22_39_52](https://user-images.githubusercontent.com/6213131/41937936-ebad7632-7991-11e8-9ba4-d957b47edf71.png)
