### ISSUE TITLE
Hackers have infaltrated com_contact through XSS and [POST:jform]

### ISSUE THREAD

**Issue by visualtribe** [joomla/joomla-cms#20899]
### Steps to reproduce the issue

Upgraded to 3.8.10. As soon as I did Hackers from Germany hit com_contact with XSS attacks and [POST:jform] and send multiple emails through this component. I don't even use this component on my site. 

### Expected result

No hacking and XSS attack of com_contact

### Actual result

emails are sent to me using this component 5 emails every 5 minutes

### System information (as much as possible)

PHP 7.0.30
Joomla 3.8.10

### Additional comments
At this time I have installed Security Check Pro and it is stripping the XSS attack and stopping this. Won't upgrade any more sites until this is rectified.

**Comment by PhilETaylor** [comment]
This is just spamming .

Implement captcha: 

https://docs.joomla.org/How_do_you_use_Recaptcha_in_Joomla%3F

**Comment by ghost** [comment]
Issue closed as stated above. @visualtribe please ask further help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding.
