### ISSUE TITLE
Composer libraries crash after update

### ISSUE THREAD

**Issue by austre** [joomla/joomla-cms#20896]
### Steps to reproduce the issue
I update Joomla to 3.8.10 and my compser library MPDF crashes. This situation was the same when update to 3.8.8 and to fix this i executed the command below:

[php composer.phar require mpdf/mpdf]

Now when i try frontend and backend login, message appears

[Call to a member function get() on null]

At log file

[joomla PHP Notice:  Undefined offset: 0 in libraries/vendor/joomla/input/src/Input.php]

### Expected result
I expect fix it fast (ehehe)

### Actual result
Now my app is not working.

### System information (as much as possible)
Debian8
Apache2
PHP7
Joomla 3.8.10

### Additional comments
Composer Log:

Using version ^7.1 for mpdf/mpdf
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 14 updates, 3 removals
  - Removing symfony/polyfill-php73 (v1.8.0)
  - Removing symfony/polyfill-ctype (v1.8.0)
  - Removing psr/container (1.0.0)
  - Updating symfony/polyfill-php55 (v1.8.0 => v1.6.0): Downloading (100%)
  - Updating joomla/utilities (1.5.0 => 1.4.1): Downloading (100%)
  - Updating joomla/registry (1.6.2 => 1.5.2): Downloading (100%)
  - Updating joomla/filter (1.3.5 => 1.3.3): Loading from cache
  - Updating joomla/input (1.3.0 => 1.2.0): Downloading (100%)
  - Updating joomla/application (1.9.1 => 1.8.1): Loading from cache
  - Updating joomla/di (1.5.1 => 1.4.0): Downloading (100%)
  - Updating joomla/image (1.5.0 => 1.4.0): Downloading (100%)
  - Updating joomla/ldap (1.4.0 => 1.3.0): Downloading (100%)
  - Updating paragonie/random_compat (v1.4.3 => v1.4.2): Downloading (100%)
  - Updating paragonie/sodium_compat (v1.6.2 => v1.3.1): Downloading (100%)
  - Updating symfony/polyfill-util (v1.8.0 => v1.6.0): Downloading (100%)
  - Updating symfony/polyfill-php56 (v1.8.0 => v1.6.0): Downloading (100%)
  - Updating symfony/yaml (v2.8.41 => v2.8.29): Downloading (100%)
  - Installing myclabs/deep-copy (1.7.0): Loading from cache
  - Installing setasign/fpdi (1.6.2): Loading from cache
  - Installing mpdf/mpdf (v7.1.0): Loading from cache
  - Installing tcdent/php-restclient (0.1.7): Loading from cache
setasign/fpdi suggests installing setasign/fpdf (FPDI will extend this class but as it is also possible to use "tecnickcom/tcpdf" as an alternative there's no fixed dependency configured.)
setasign/fpdi suggests installing setasign/fpdi-fpdf (Use this package to automatically evaluate dependencies to FPDF.)
setasign/fpdi suggests installing setasign/fpdi-tcpdf (Use this package to automatically evaluate dependencies to TCPDF.)
mpdf/mpdf suggests installing ext-bcmath (Needed for generation of some types of barcodes)
Generating autoload files

**Comment by mbabker** [comment]
1) According to your output, you've downgraded a lot of the core packages, that is going to cause problems
2) We do not support users running Joomla and using Composer to pull in dependencies right now so these types of changes are at your own risk

**Comment by austre** [comment]
Nice, you confirm my suspect. So, you could help about the right way to use
joomla anda composer?

Em Qua, 27 de jun de 2018 11:54, Michael Babker <notifications@github.com>
escreveu:

**Comment by Bakual** [comment]
@austre You need to run composer in an own directory. You can't use the "main" one from Joomla.
If you have a dependency in your composer library which is covered by Joomla already, you can use "replace" (I think it was that one) to trick you composer so you don't have the same library twice.

**Comment by austre** [comment]
I understand more now, so thanks all you. I'm a dummy with composer, start
learn and use about 1 month.

I was think it only works at libraries/vendor. I have my own dir for some
classes, now i'll use this one for my composer libraries.

Need learn use/configure composer in my own dir.

Now is time to watch Brazil WC game and after i'll fix those jommla
composer libs.

Em Qua, 27 de jun de 2018 12:27, Thomas Hunziker <notifications@github.com>
escreveu:

**Comment by ghost** [comment]
@austre if Issue is solved please close it.

**Comment by Bakual** [comment]
@austre You can set the vendor dir in your composer.json using
````
 "config": {
    "vendor-dir": "directory/to/vendor"
  },
````
In your code, you then require your own composer autoloader so stuff gets found.

**Comment by austre** [comment]
@Bakual I'll try this, thanks!

Now i'm trying to fix the downgrade that i made. With the command

`php composer.phar show -lo`

I got this

- joomla/application      1.8.1   1.9.1    Joomla Application Package
- joomla/di               1.4.0   1.5.1    Joomla DI Package
- joomla/filter           1.3.3   1.3.5    Joomla Filter Package
- joomla/image            1.4.0   1.5.0    Joomla Image Package
- joomla/input            1.2.0   1.3.0    Joomla Input Package
- joomla/ldap             1.3.0   1.4.0    Joomla LDAP Package
- joomla/registry         1.5.2   1.6.2    Joomla Registry Package
- joomla/utilities        1.4.1   1.5.0    Joomla Utilities Package
- paragonie/random_compat v1.4.2  v9.99.99 PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
- paragonie/sodium_compat v1.3.1  v1.6.3   Pure PHP implementation of libsodium; uses the PHP extension if it exists
- phpmailer/phpmailer     v5.2.26 v6.0.5   PHPMailer is a full-featured email creation and transfer class for PHP
- setasign/fpdi           1.6.2   v2.0.3   FPDI is a collection of PHP classes facilitating developers to read pages from existing PDF documents and use them as templ...
- simplepie/simplepie     1.3.1   1.5.1    A simple Atom/RSS parsing library for PHP
- symfony/polyfill-php55  v1.6.0  v1.8.0   Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
- symfony/polyfill-php56  v1.6.0  v1.8.0   Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
- symfony/polyfill-util   v1.6.0  v1.8.0   Symfony utilities for portability of PHP codes
- symfony/yaml            v2.8.29 v3.4.12  Symfony Yaml Component

When i try 

`php composer.phar update ./vendor/joomla/application`

I got

Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

So, **Nothing to install or update!**
What should i do?

**Comment by brianteeman** [comment]
I am closing this as while it is an issue for you it is not a core issue.

**Comment by austre** [comment]
Ahh, ok!
I understand, thanks anyway!
