### ISSUE TITLE
to change the level at a menu - starange sort. in the menu

### ISSUE THREAD

**Issue by tom2ba** [joomla/joomla-cms#20891]
### Steps to reproduce the issue
1 open a menu
2 change the level (i do from 2 to 1)

### Expected result
Error:
BIGINT UNSIGNED value is out of range in '(`maniacsql30`.`#__menu`.`level` + -(1))'

### Actual result

strange sort in the menu. different to the sort in the table xx_menu

### System information (as much as possible)

3.8.10 - linux - 

PHP erstellt für | Linux cobath-5723-1 3.16.0-4-amd64 #1 SMP Debian 3.16.51-2 (2017-12-03) x86_64
-- | --
Database Type | mysql
Datenbankversion | 5.5.60-0+deb8u1
Datenbankzeichensatz | latin1_swedish_ci
Datenbankverbindungszeichensatz | utf8mb4_general_ci
PHP-Version | 7.0.29
Webserver | Apache/2.4.10 (Debian)
PHP-Interface für den Webserver | cgi-fcgi
Joomla!-Version | Joomla! 3.8.10 Stable [ Amani ] 26-June-2018 15:45 GMT
Joomla!-Plattform-Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by ReLater** [comment]
I cannot replicate this issue with Joomla! 3.8.11-dev, testing sample data.

PHP Built On | Linux dd1620 3.13.0-149-generic #199-Ubuntu SMP Thu May 17 10:12:50 UTC 2018 x86_64
Database Type | mysql
Database Version | 5.5.58-nmm1-log
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.1.11-nmm1
Web Server | Apache
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 3.8.11-dev Development [ Amani ] 26-June-2018 15:45 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0 **ESR**

**Comment by brianteeman** [comment]
@tom2ba can you provide some screenshots of this error please

**Comment by brianteeman** [comment]
Closed. It can. Always be reopened if more information provided.
