### ISSUE TITLE
[4.0] Wrong sql update for com_csp

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#20897]
### Steps to reproduce the issue
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_admin/sql/updates/mysql/4.0.0-2018-06-03.sql#L16-L17

still contains `custom_data, system_data`

`INSERT INTO `#__extensions` (`extension_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `custom_data`, `system_data`, `checked_out`, `checked_out_time`, `ordering`, `state`, `namespace`) VALUES
(35, 'com_csp', 'component', 'com_csp', '', 0, 0, 1, 0, '', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0, 'Joomla\\Component\\Csp');`

which were removed.

same for postgresql

**Comment by ghost** [comment]
closed as having Pull Request #20898
