### ISSUE TITLE
[4.0] Field Type Rules only allow one field of the type in a fieldset?

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#20901]
### Is your feature request related to a problem? Please describe.
So I am creating a custom component with different sections (views) like dashboard, users (with sync to the com_users), categories (with sync to com_articles), media (will contain audio and video), etc. You got the idea. It is not a standard joomla core component. 

And I am working on Permissions which is using the rules field type. Looking at config.xml and access.xml, at first glance, cool! I can tell config.xml to pull from access.xml all the actions for each of my custom components sections so I can have different permissions per views or sections.

Well, I am wrong! Seems like the rules field type will only work properly if there only one instance of the field in a page. The permissions slider or tabs (I don't know what it's called) for each group does not sync with the section.

If what I am doing putting all the permission settings in one place is a bad idea, then please suggest an idea.

Thanks!

### Describe the solution you'd like
Allow rules field type to be rendered multiple times in a single page or tab pane.

### Additional context
![image](https://user-images.githubusercontent.com/1373815/41995086-5aed8398-7a05-11e8-8811-8d24647e9e41.png)

**Comment by brianteeman** [comment]
Please use the forum or Google groups for questions about custom development

**Comment by frogydiak** [comment]
@brianteeman it is at the same time a feature request and not purely custom development. How do you think would one know what are the limitations of J4 if everything should be made out of the core component? I found out that rules field type has been designed like I mentioned above. You guys allowed feature requests type of issue, didn't you?

Besides, do you think Joomla's Forum ever helped anyone? LOL! Stackoverflow does in my experience.
