### ISSUE TITLE
(UX Feature Request) Open Account Settings in Modal

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#20908]
### Is your feature request related to a problem? Please describe.
When you want to change the editor or language as an administrator quickly you always have to leave the current page and after saving the settings you have to navigate back to where you came from.

![kgb4psghgm](https://user-images.githubusercontent.com/828371/42030072-eeff4950-7ad1-11e8-8442-02bbeb90d5a4.gif)

### Describe the solution you'd like
If the Edit Account link from the upper right corner could open in a modal it would be easy to change the profile settings and at least to stay in the area where you were before.

### Additional context
This happens more often to Super Users and Users that want to switch between editors and languages - I would say "powerusers" and of course to testers of Joomla. Removing this annoying step of navigating back could be a good improvement to UX.

**Comment by brianteeman** [comment]
Maybe this can be part of the gsoc project to refactor com_users

**Comment by coolcat-creations** [comment]
I was hoping it's "just" a change of the location it opens in... but I don't know yet how to solve it.

**Comment by mbabker** [comment]
No, it's not "just" that.  Without "just" iframing the edit page into a modal there's a lot to get into here.  Rendering the form correctly, the toolbar rendering, handling form submission, etc.

**Comment by PhilETaylor** [comment]
So are we now saying that modals are a great idea for UX? 

Im sure there will be lots of people that disagree that the increased use of modals is a good thing. 

Maybe the better option here would be a dropdown selector in the top toolbar, that selected the editor or language and set it for the current page, thus reloading the page in the process, because even with a modal, after saving the change, the current page will need reloading for the change to take effect.  Almost all language switching is now like this elsewhere.

**Comment by coolcat-creations** [comment]
> So are we now saying that modals are a great idea for UX?

No we are not saying this, just trying to get a solution (without crowding the navbar).

Reloading the current page is something different then leaving completely the area you were working in...

**Comment by PhilETaylor** [comment]
But what you are proposing is 

- User clicks icon
- User moves down to select edit
- waits for a modal to load an iframe
- changes something (possibly having to scroll or invoke a tab as the edit profile page it large)
- clicks save 
- waits for iframe to save 
- waits for a loaded response from the server
- JS then checks response and then closes modal
- JS then has to reload the page before the user interacts with it
- user then has to wait for the page to reload, possibly losing work unsaved

This is a huge step back imho but then Im no expert on UX/UI...

**Comment by coolcat-creations** [comment]
The waiting times sound very long in your listing ;)
I am not an expert in UX either... But I know when I am annoyed by ending up somewhere completely else after coming from a specific place. Maybe the solution is to give the url I come from to that page and after hitting save I will be redirected to Articles Manager or Category Manager or whereever i came from.

**Comment by PhilETaylor** [comment]
> The waiting times sound very long in your listing ;)

Welcome to 90% of Joomla mass webhosting... 

The wheel - already invented: 
https://extensions.joomla.org/extension/switch-editor/
https://extensions.joomla.org/extension/backend-language-switcher/

**Comment by brianteeman** [comment]
I am closing this on the basis that multiple extensions exist that will do this.
