### ISSUE TITLE
[4.0] Error after pulling 4.0-dev branch

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#20902]
### Steps to reproduce the issue
I did a:

git pull origin 4.0-dev

I didn't get any error while pulling but when I tried to reload /administrator, I get this:

Error: Class 'Joomla\Module\Version\Administrator\Helper\VersionHelper' not found: Class 'Joomla\Module\Quickicon\Administrator\Helper\QuickIconHelper' not found

### Additional comments
I don't know what changed in the code but understandably it is still in Alpha. I was able to fix it by deleting all the files and copying over a downloaded zip file of the same branch (But using my previous database). 

Another issue with the current version of 4.0-dev branch is suddenly the Extension class is no longer auto loaded when called in the administrator\components\com_custom\services\provider.php file. My custom component would not run anymore. I am getting an error class not found:

 Class 'Joomla\Component\Mycomponent\Administrator\Extension\MyComponent' not found

I did not change anything with the provider.php file and it use to work before the git pull. Seems like the class MyComponent is not being auto loaded anymore.

I guess it is wrong to develop while the framework is still in Alpha LOL!

**Comment by roland-d** [comment]
I have the same issue and traced it back to this issue #17259 implementing this code. @laoneo Can you have a look at why this is failing? I am not sure why we are using `\Joomla\Module\Version\Administrator\Helper\` while the file is in folder `administrator\modules\mod_version\Helper`. There is no autoloader able to make that translation.

**Comment by brianteeman** [comment]
Do you still have a file called autoloader_psr4.php (or something like that) in the libraries folder?

**Comment by roland-d** [comment]
@brianteeman Yes it is there although I can see it is excluded from Git now. Removing that file fixes it. Thank you.

**Comment by brianteeman** [comment]
Going to close this ;)
