### ISSUE TITLE
[4.0] Namespacing ??

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#20928]
I am starting to complete the namespacing of the admin components in J4 but I am only a trained monkey

I can see some existing namespacing that looks like this

```
use Joomla\CMS\Help\Help as JHelp;

	$this->page = JHelp::createUrl(\JFactory::getApplication()->input->get('page', 'JHELP_START_HERE'));

```

Is that just "lazy" coding to avoid having to rename every instance in the file of JHelp

Is it not more correct to be changed to 

```
use Joomla\CMS\Help\Help;

	$this->page = Help::createUrl(\JFactory::getApplication()->input->get('page', 'JHELP_START_HERE'));

```

@laoneo @wilsonge

**Comment by Bakual** [comment]
Yes, first one is "lazy", but it's valid as well.
In the second case, you would have to change `JHelp` in the code to `Help`. So ` JHelp::createUrl` becomes ` Help::createUrl`

**Comment by brianteeman** [comment]
I know its valid but if I am going to do this I want to do it right - thats why I was checking ;)

(there was a typo in my code above that I just fixed)

Thanks

**Comment by wilsonge** [comment]
Yup as Thomas said - it was just lazy - I think I did this very early on to try and help with the merge conflicts (a slash to remove would have been easier) but when we went back and namespaced the libraries in 3.x it became totally useless.
