### ISSUE TITLE
[4.0] Description Length and Sort Field param on com_finder not working

### ISSUE THREAD

**Issue by carlitorweb** [joomla/joomla-cms#20925]
@Hackwar I found the `Description Length` and `Sort Field` options are not working as expected.

- `Description Length` no truncate the description when you change the value.
-  `Sort Field` when you put the value `Date` or `List price` throw an error:
![screenshot_20180628171359](https://user-images.githubusercontent.com/3956472/42060881-528ebbd0-7af6-11e8-91db-e0293bd21c9c.png)

**Comment by Quy** [comment]
Closing as not reproducible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20925">issues.joomla.org/tracker/joomla-cms/20925</a>.</sub>
