### ISSUE TITLE
during PR, drone CI produce error on JavaScript test

### ISSUE THREAD

**Issue by beyondykk9** [joomla/joomla-cms#20927]
### Steps to reproduce the issue

during PR, the following error is occurred on drone CI

+-- karma-firefox-launcher@0.1.7 
+-- karma-jasmine@0.3.8 
+-- karma-jasmine-ajax@0.1.13 
| `-- jasmine-ajax@3.4.0 
+-- karma-requirejs@1.1.0 
+-- karma-verbose-reporter@0.0.3 
+-- requirejs@2.3.5 
`-- text@2.0.15  (git://github.com/requirejs/text.git#d04de4ffd7bf5ba6cb80cdca2d40d4f6f52a1b1f)

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
+ cd ../..
+ tests/javascript/node_modules/karma/bin/karma start karma.conf.js --single-run
29 06 2018 04:55:38.574:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
29 06 2018 04:55:38.611:INFO [launcher]: Starting browser Firefox
29 06 2018 04:55:41.740:INFO [Firefox 59.0.0 (Ubuntu 0.0.0)]: Connected on socket EY7l9dHm9rBG3zU7AAAA with id 20438334
29 06 2018 04:55:44.284:ERROR [Firefox 59.0.0 (Ubuntu 0.0.0)]: TypeError: a.ui is undefined
at http://localhost:9876/base/media/jui/js/jquery.ui.sortable.min.js?3ebfa0c205cdb3b90e6858aea5c05607b57e93c8:17

Suites and tests results:

Browser results:

### Expected result

No errors expected

### Additional comments

I have not modified any javascript files on PR.

**Comment by zero-24** [comment]
Hi :)

I have just rebooted the build and it seams to be better now: http://ci.joomla.org/joomla/joomla-cms/6811/5

I think we can close this issue than?

**Comment by mbabker** [comment]
It really should be fixed permanently.  The constant false positives from Drone about this particular JavaScript test and the one that hangs AppVeyor on PHP 5.6 need review because a lot of times it just results in either testers passing over items because they see red X's on the CI integrations or reviewers merging without looking for "real" failures because Travis is green (which rarely gives these false positives) but the other systems aren't.

**Comment by brianteeman** [comment]
Pretty sure the failure here is not related to the PR http://ci.joomla.org/joomla/joomla-cms/6815/14

**Comment by zero-24** [comment]
JS != System Tests. This issue here was about the JS tests not the System tests. For the system tests please try to update your branch as a fix should be merged for that already.

**Comment by beyondykk9** [comment]
Okay, I will close the issue.

**Comment by mbabker** [comment]
Re-opening.  Someone needs to fix this test so it stops creating false positives on so many PRs or just flat out remove the test since it seems so critically broken.

**Comment by mbabker** [comment]
Re-closing, same reason as https://github.com/joomla/joomla-cms/issues/21050#issuecomment-406744030

Looks like failures are just going to keep being ignored.
