### ISSUE TITLE
[3.8.*] Fatal error login.php

### ISSUE THREAD

**Issue by omarguetti** [joomla/joomla-cms#20932]
I have an error on backend in Joomla website. When I insert user and password I can see this error:
Fatal error: Call to a member function get() on a non-object in /web/htdocs/www.namesite.it/home/administrator/components/com_login/models/login.php on line 33

This is the file administrator/components/com_login/models/login.php

Can this be related to a failed update?

Further info: https://stackoverflow.com/questions/51100886/joomla-3-6-white-page-in-backend-fatal-error-login-php

**Comment by mbabker** [comment]
> Can this be related to a failed update?

Yes.  It means your site was not correctly updated.  Suggest posting on the forums at https://forum.joomla.org for assistance in troubleshooting and resolving your issue.

**Comment by brianteeman** [comment]
@mbabker beat me too it
