### ISSUE TITLE
3.8.10 Extensions: Manage

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#20933]
From Joomla version 3.8.8, we have updated Joomla 3.8.10
PHP Version | 7.2.7

Is there any problem with the extension removal option?

**The problem is this way**
![3810](https://user-images.githubusercontent.com/423588/42101204-1356cc8e-7bcb-11e8-820e-51e418c90d28.png)

**Comment by mbabker** [comment]
Duplicate of #20881
