### ISSUE TITLE
Joomla local instalation using Chrome and XAMPP

### ISSUE THREAD

**Issue by dodosiz** [joomla/joomla-cms#20944]
### Steps to reproduce the issue
I am trying to install the Joomla Desktop locally. I follow the steps and in the last step the loading gif loads forever. I open my console and I see an error:

Cannot read token of null in line 189 of installation.js
The line contains this: 
`Joomla.replaceTokens(r.token);`
A few lines under this there is an assignment:
`var r = $.parseJSON(xhr.responseText);`
I run the debugger and the $.parseJSON(xhr.responseText) return undefined.

### Expected result
To finish the installations normally.

### Actual result
The loading .gif loads forever and I can not finish the installation, but my database has been created.

### System information (as much as possible)
I am on Windows 8 and I use XAMPP. I try to install Joomla version 3.8. As a server I use Apache, my databse is a mySQL 5.7 with a UTF-8 default encoding and I have PHP 7 installed. The browser I am using to install Joomla is Google Chrome.

### Additional comments
What if we replace:
`var r = $.parseJSON(xhr.responseText);`
with this:
`var r = JSON.parse(xhr.responseText);`

Configuration:
![1](https://user-images.githubusercontent.com/16365389/42134164-cb073d36-7d3e-11e8-86e8-a3f2d142e6b7.png)

**Comment by ghost** [comment]
Have you asked at https://forum.joomla.org/viewforum.php?f=707&sid=5b65be33dfa7f20419ffdb982c87e6bb as this Forum is for this Kind of Questions:

>Anyone with specific questions about installing Joomla 3.X.x on a particular stack server on their local PC (WampServer 2, XAMPP, MAMP, or LAMP). There is no guarantee that you will get an answer but we try. Alternatively go directly to the Web site of the stack(s) you are using.

**Comment by dodosiz** [comment]
I think that it's a JavaScript issue and it does not have to do with my server installation, but I'll try to install WAMP istead and see if the issue has been resolved.

**Comment by dodosiz** [comment]
I switched to WAMP and the issue is now resolved!

**Comment by m3ali** [comment]
Edit index.php file under installation folder, add this line:
set_time_limit(0);
after the line:
define('JOOMLA_MINIMUM_PHP', '5.3.10');
The problem is that installing joomla tables takes more time in some xampp versions. With this instruction set_time_limit(0); you give the installer the time it need.
