### ISSUE TITLE
Internal Server Error in media after upgrading to 3.8.10

### ISSUE THREAD

**Issue by mozaffar** [joomla/joomla-cms#20942]
After upgrading to 3.8.10 When I go to media, By clicking on any directory which contains image file it shows me Internal Server Error.

**Comment by ghost** [comment]
~~Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.~~

Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.
