### ISSUE TITLE
[4.0] Namespace updater plugin

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#20953]
### Feature request
1. add a button to manually regenerate the file

2. we are writing to a folder /libaries that we haven't written to in the past and so might not be writable. To test I made the libraries folder readonly and I didnt get any error message about not being able to build the map when i installed or deleted an extension

**Comment by laoneo** [comment]
I would even go that far that the plugin can't be disabled as it will not add a new installed extensions classpath to the list then.

**Comment by mbabker** [comment]
> I would even go that far that the plugin can't be disabled as it will not add a new installed extensions classpath to the list then.

Then a plugin is the wrong thing for this solution and it should be moved somewhere else (hint, if this needs to be an event listener our event dispatcher is not hard coupled to plugins; make it a standalone event subscriber class and in the dispatcher service when it is created add this subscriber to the dispatcher)

**Comment by laoneo** [comment]
Yes, I was [always saying](https://github.com/joomla/joomla-cms/pull/18703#issuecomment-345816494) that a plugin is the wrong thing for that use case. There is no reason to have that as plugin. And this was before we introduce the boot functionality, as we can now put the responsibility back to the extension while we have now a common path to load an extension. So we can avoid situations like #20823 and can get rid of all the balast of loading all extension namespaces into the classloader on every request even though we do not need all of them.

**Comment by brianteeman** [comment]
When I made the plugin "protected" I had hoped there was also a way to make it permanently enabled butt there isnt

**Comment by mbabker** [comment]
I've pointed it out somewhere before but the plugin manager doesn't account for the protected column's value.

**Comment by laoneo** [comment]
I would remove the plugin and move the classmap generation step somewhere into the installer as the classmap is essential part of the core (I still do not agree with the whole thing, but this is another story). For safety we can add a check in the application execute process too. But having that in a plugin is too dangerous for me.
About the issue of a none writable folder, what about a fallback to cache?

If you guys agree to remove the plugin, then I will do a pr next week.

**Comment by phalouvas** [comment]
Guys any news on this? In release 4 alpha 5 when installing a new component, it's namespace is not 'readed' from container. Must manually include it's path in file: libraries/autoload_psr4
