### ISSUE TITLE
an xtd plugin to download media files

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#20969]
### Is your feature request related to a problem? Please describe.
We do have a specific Images XTD plugin that lets browse images through a modal window in the folders defined in com_media  and insert these images very simply in an article or else.
This works fine.

But we do not have an XTD plugin to enter links to files chosen after browsing these folders in order to download them. That would be real handy to create links to download .doc, .xls, .pdf

The only core solution is entering the full path to the file through the link popup (TinyMCE). That is quite heavy.

### Feature missing in core
Joomla should not be depending on third party solutions for such a simple task.

**Comment by Quy** [comment]
Is PR #19967 related?

**Comment by infograf768** [comment]
It verywell could be. Posting there now. Please do not close for now

**Comment by brianteeman** [comment]
This is a very old request for a new feature in Joomla 3. As there has been no interest in providing any code to satisfy this and we are not accepting any new features in Joomla 3 I recommend that it is closed.

**Comment by alikon** [comment]
@infograf768 can we close this one ?

**Comment by Fedik** [comment]
It more like feature for Joomla in general ;)

And it really missing thing (or make new xtd btn or extend existing media extd btn), until someone find a time to implement it I would keep it open, and set label to j4, j5 ... jX so on :)

**Comment by micker** [comment]
Yes you have a beautifull New file manager... Need to be perfect

**Comment by Quy** [comment]
Please test PR #34634.
