### ISSUE TITLE
Extension Manager - Filter by type broken after upd to 3.8.10

### ISSUE THREAD

**Issue by sandstorm871** [joomla/joomla-cms#20961]
### Steps to reproduce the issue
Open a J3.8.10 site in Back End
Navigate to Extensions > Manage > Manage
Filter By Type is now a text field rather than a drop-down.

### Expected result

Navigating to Extensions > Manage > Manage, you should be able to select a type from "Filter by Type" - Component, Language, File, Library, Template, etc

### Actual result
Select Type dropdown is now a text field

### Additional comments
see screenshots

**Comment by mbabker** [comment]
Duplicate of #20881

**Comment by sandstorm871** [comment]
OK Sorry ;) I had searched before diving in, but didn't see this.
