### ISSUE TITLE
[4.0] Atum pagination override

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#20971]
As you can see in this code it will generate TWO class attributes. you can only have ONE

https://github.com/joomla/joomla-cms/blob/4b01c64aad89d687ecb22c8a2d01fc8c86f2814d/administrator/templates/atum/html/pagination.php#L191-L199

**Comment by Quy** [comment]
Please test PR #20978<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20971">issues.joomla.org/tracker/joomla-cms/20971</a>.</sub>
