### ISSUE TITLE
[4.0] Timezone field - duplicate class

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#20972]
If you **view** the source of com_config you will see duplicate classes. This is invalid markup

`<div class="controls"><select id="jform_offset" name="jform[offset]"  class="custom-select" class="custom-select">`
 
The first one comes from
https://github.com/joomla/joomla-cms/blob/4b01c64aad89d687ecb22c8a2d01fc8c86f2814d/libraries/src/Form/Field/GroupedlistField.php#L151

The second one comes from
https://github.com/joomla/joomla-cms/blob/4b01c64aad89d687ecb22c8a2d01fc8c86f2814d/libraries/cms/html/select.php#L222

**Comment by Quy** [comment]
Related PR #20196

**Comment by brianteeman** [comment]
You can see the same in other places such as the module style field

**Comment by brianteeman** [comment]
Closed as a duplicate
