### ISSUE TITLE
[4.0] Manage folder not working.

### ISSUE THREAD

**Issue by anuragteapot** [joomla/joomla-cms#20980]
### Steps to reproduce the issue
Open template manager. Select your template. 
And try to manage folder.

![selection_003](https://user-images.githubusercontent.com/30978328/42307440-0d7c75b4-8050-11e8-9603-3880c0094e38.png)

### Expected result
You can manage folder and able to select a folder from tree.

### Actual result
Folder tree not selectable you are not able to manager folder.

**Comment by ghost** [comment]
closed as having Pull Request #20981
