### ISSUE TITLE
[4.0] [a11y] pagination

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#20983]
in #18357 and #18326 I spent a lot of time ensuring that the pagination was fully accessible. That code needs to be ported across to J4

_I still don't understand why we have an override for this in atum_

**Comment by brianteeman** [comment]
I started working on this but have a question the code below is being used
https://github.com/joomla/joomla-cms/blob/ff44745fcfedbd896c6792de759a6645316d09b3/libraries/src/Pagination/Pagination.php#L708

and not the layout despite the comment.

I don't want to do the work multiple times so what needs to be changed.

**Comment by mbabker** [comment]
Eventually, yes, those methods should be updated to just use the layouts versus the markup that's in those methods now.

**Comment by brianteeman** [comment]
So I just replaces the code there with this
```

	protected function _item_active(PaginationObject $item)
		{
		return \JLayoutHelper::render('joomla.pagination.link', ['data' => $item, 'active' => true])
		}
```

**Comment by mbabker** [comment]
Yes.

**Comment by brianteeman** [comment]
thought so - that results in nothing being output so I guess there is another bug - will investigate

**Comment by brianteeman** [comment]
found the error - pebkac
