### ISSUE TITLE
Joomla 3.9 - Modern Routing fails in frontend - issues with mediafield inside repeatable field

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#20985]
### Steps to reproduce the issue
1) Install the current staging. 
**Backend**
2) Klick on Content » Fields and create a new Field of the type repeatable
3) Set 2 Fields there: Title and a media field. 
4) Setup a menuitem to add new articles 
5) Enable Modern Routing in the Article Options in the Integration Tab (Modern Routing, remove ID)
**Frontend**
1) Go into your frontend and login as Superuser
2) Add a new article and try to select images in the Fields Tab (Media Fields)

### Expected result
Modal should open in frontend and give you the possobility to upload or select media

### Actual result
Modal window opens with "404 - URL invalid" 

### System information (as much as possible)
Staging

**Comment by laoneo** [comment]
Can you try it with the 3.9 branch? Same behavior?

**Comment by coolcat-creations** [comment]
I could not reproduce it myself but it happens randomly to my customer. I asked for the url that is called so hopefully someone can read from the url what might go wrong in this case?

**Comment by coolcat-creations** [comment]
Achieved to figure out the problem, but no idea about how to fix it.
@laoneo @Hackwar 
The problem appears in frontend editing when modern routing is enabled 
![x0jbnshn6n](https://user-images.githubusercontent.com/828371/42442316-a0878ff2-836a-11e8-954f-ee62aada9e44.gif)

**Comment by coolcat-creations** [comment]
Seems to be fixed

**Comment by roland-d** [comment]
@bilalreffas tested this at @icampus and we cannot reproduce the issue either using the 3.9 nightly build.

**Comment by BilalReffas** [comment]
Yeah I tested this on Linux and macOS it seems like this issue was fixed already 😁
