### ISSUE TITLE
[4.0] Where is the Uncompressed template.js for Atum>

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#20988]
The admin template atum js folder only has the compressed version of the script template.min.js. 

Where's the uncompressed version?

**Comment by Quy** [comment]
\administrator\templates\atum\css\template.css<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20988">issues.joomla.org/tracker/joomla-cms/20988</a>.</sub>

**Comment by dgrammatiko** [comment]
FYI there won't be a template.js for Autum. Right now that file contains (wrongly) the logic of the:
- menu (that will be transferred in the menu module)
- the code for the grouped buttons (that code will be transferred in the relative custom element)

**Comment by ghost** [comment]
Closed as allready answered above. issue can always be reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20988">issues.joomla.org/tracker/joomla-cms/20988</a>.</sub>
