### ISSUE TITLE
[4.0] [a11y] Incorrect role=button in quickicon module

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/joomla-cms#20992]
The lines in the Quickicon module are assigned the role=button attribute. This is incorrect. These are not buttons. These are the links that open new pages   
See: 
* [2.1 First rule of ARIA use](https://www.w3.org/TR/aria-in-html/#rule1)
* [2.2 Second rule of ARIA use](https://www.w3.org/TR/aria-in-html/#secondrule)
* [Links vs. Buttons in Modern Web Applications](https://marcysutton.com/links-vs-buttons-in-modern-web-applications/)

**Comment by brianteeman** [comment]
changed title to show it is for Joomla 4

**Comment by brianteeman** [comment]
The file in question is layouts\joomla\quickicons\icon.php

**Comment by ghost** [comment]
closed as having Pull Request #20998
