### ISSUE TITLE
[4.0] Admin Modules in cpanel have wrong bootstrap size after editing

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#21001]
### Steps to reproduce the issue
You must have an istallation where the modules on cpanel are not edited yet.
The modules then have class "col-md-6" and are visible in two columns.

Klick on the edit button of a module, edit something, i.e. the number of items to be shown, save and close and go back to the cpanel.

### Expected result
The Module has col-md-6 as before.

### Actual result
The module has col-md-12, bootstrap-size is set to 0.

### Additional comments
You cannot reproduce this when a module is edited once.

**Comment by brianteeman** [comment]
This sounds like it's a result of the installation SQL default value not matched the default value in the modules. @sharkykz

**Comment by SharkyKZ** [comment]
`bootstrap_size` value is not present in SQL files but Atum's module chrome defaults to `6`.

**Comment by chmst** [comment]
Let's wait for the new template. 
If the param bootstrap_size is not set when the module is edited, bootstrap_size must remain null or '' and not be set to 0 as it is now.

**Comment by frogydiak** [comment]
Is there a branch or fork of the new backend template? Can it be tested, I want to help. Thanks!

**Comment by TobsBobs** [comment]
@frogydiak 
this is the pull request #21006 an this is the repository https://github.com/joomla/40-backend-template

**Comment by ghazal** [comment]
I have been noticing this for a while.
The setting is in administrator/templates/atum/html/modules.php,
lines 56 and 97 (well and body):
``$moduleClass    = ($bootstrapSize) ? 'col-md-' . $bootstrapSize : 'col-md-12';``
In my opinion it should be "col-md-6" but maybe we should wait for more advanced changes on Atum.

**Comment by wilsonge** [comment]
Is this still an issue?

**Comment by brianteeman** [comment]
yes

**Comment by wilsonge** [comment]
Fixed with 5defb0096e
