### ISSUE TITLE
Better translation workflow

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#21003]
It will be good to **make easier translation with com_association**
my light idea is to add a **tranlation button in editing view  in toolbar** (only if plugin language is enable) :

- article
- menu
- contact
- module

it can launch com_associations with context variable
like
`itemtype=com_content.article`
`id=12`
for a content with id 12
the workflow can be more simplier for translation !
**After maybe need to load this in same page OR in modal ...**
What do think about this ?

**Comment by brianteeman** [comment]
Please see this google summer of code project

https://github.com/joomla-projects/gsoc18_automatic_multilingual_association

https://community.joomla.org/gsoc-2018/automatic-multilingual-association-follow-up.html

**Comment by infograf768** [comment]
This proposal is quite different from the GSOC project where the matter (for which I posted some comments) is to create automatically some associations WITHOUT taking into account the translation (when a translation is necessary) of the item itself.

As far as I understand the original post here, the proposal by the user is to create a direct link to com_associations with the item already chosen through a toolbar button.

**Comment by micker** [comment]
yes that it for me 3 interesting point 

- translation workflow will be smooth
- encourage user to use association
- not realy a big coding feature (but i am a prorammer lol)

we have com_association but no link between content type and this tool no sense
for now using com_ association is
**go out content type (that no sense) >extension > com_asso > select type > select language ... (5 step)**
with this button
**content type > com_asso > select language (3 step)**

**Comment by micker** [comment]
thanks @brianteeman

**Comment by infograf768** [comment]
@micker 
This is imho what is possible in a simple way.
Let's say we have an article with id `1`.
We need to directly link to com_associations side to side page.
Therefore we need a link of the type
`administrator/index.php?option=com_associations&view=association&layout=edit&itemtype=com_content.article&task=association.edit&id=1`

This will give
<img width="1225" alt="screen shot 2018-07-06 at 12 19 48" src="https://user-images.githubusercontent.com/869724/42374136-712b195e-8117-11e8-8a04-e14f5492c71b.png">

Then, it is just a matter of Selecting the target language(s). If an association already exists, then it will load; if not, the frame will be ready to create the item in the language desired.

Until then, no big deal.
Multilang should be enabled as well as associations AND com_associations
we have to fetch the id.
One aspect has also to be checked: the item must be tagged to a specific content language and not ALL languages.
We could do that also and throw an error if not done (in the same way as in the Associations tab).

Remain the UI: should it be a toolbar button or a specific button in the Associations Tab?

**Comment by infograf768** [comment]
Obviously the same can be done for each component where associations are implemented.
I like the idea.

**Comment by infograf768** [comment]
@micker 
Do you want me to have a try at it?

**Comment by micker** [comment]
oh yes i think it will be good (i am french user we can speak about in private)
i think a button in tool bar will be more visible and understandable for end-user like "Edit translation"
after need to choose changing page or open modal ... not sure about this

**Comment by infograf768** [comment]
Forget "Edit Translation(s). 😄 
Associated items are not specifically translations, they can be anything which content is unrelated to the original.
maybe `Edit Associations`

As for a redirect, once we are in com_associations, we have direct access to all possible item types associations. Therefore it is not needed to redirect to anything imho.

**Comment by micker** [comment]
yes

**Comment by infograf768** [comment]
Ok. I will contact some maintainers and ask them if this feature would be accepted before even coding it, so I don't lose time.
Will let you know.

**Comment by micker** [comment]
yep !
thanks

**Comment by rdeutz** [comment]
I think it is a goog idea @mbabker and @wilsonge what do you think?

**Comment by Bakual** [comment]
I don't see a reason against this idea. So imho goahead.

**Comment by infograf768** [comment]
Thanks. Working on it now.

**Comment by infograf768** [comment]
I have a working patch. already done for articles and categories.
Just waiting for @Bakual code check.

**Comment by infograf768** [comment]
@micker Please test https://github.com/joomla/joomla-cms/pull/21022
