### ISSUE TITLE
Joomla 3.8.10 problem with language switcher, ampersand in link

### ISSUE THREAD

**Issue by chrkoe** [joomla/joomla-cms#21019]
In one site of my customer I have the language switcher module activated. It worked fine for a long time. Now I get a call that after updating to 3.8.10 the language switcher "destroys" the page when changing the language.
The menu items are linked corrected and after switching, the article show up in correct language.

BUT: All modules, linked to this site where not displayed. I found out that the language switcher creates some incorrect links, e.g.: `http://.../index.php?option=com_content&amp;view=article&amp;id=2:home-en&amp;catid=8&amp;lang=en&amp;Itemid=110`
When I correct the `&amp;` to an `&` everything comes up as usual.
Is this a bug in Joomla, the module or am I missing some configuration on the webserver (which I can not access very good. found no logs but I continue searching them...)

PHP 7.1.10
MySQL 5.6.19

I tried reinstalling the core via the live update function. No change.
In the attached screenshot you can see the modules, components and plugins version. Joomla itself says it is up-to-date.
![screenshot_backend](https://user-images.githubusercontent.com/33380988/42421607-9bb6b148-82d8-11e8-8165-a39214f69413.png)

**Comment by infograf768** [comment]
The switcher has been slightly modified in 3.8.10 by using `htmlspecialchars` for security reasons, which indeed changes `&` to `&amp;` .
This has no impact on the links produced.

**Comment by chrkoe** [comment]
You can look at the page and check the result: sfb138.de
The language switcher is in the top right corner under the menu.

**Comment by infograf768** [comment]
It looks like you have set this site with SEF OFF.
In that case, evidently, the urls are modified although they do work fine.
I suggest you enable sef in global configuration. This will make your URLs much more pretty.

**Comment by chrkoe** [comment]
Yes, SEF is off. I once turned them on, but then only got error messages. I guess I missed some configuration in .htaccess file but did not find the time to take care of this problem.

>In that case, evidently, the urls are modified although they do work fine.

Anyway, the url works not really good. The created urls contain `&amp;` and not `&`. The result is, that there are several moduls missing like the main menu.

**Comment by chrkoe** [comment]
Well, for a faster solution I enabled SEF.
For me, the problem is solved with this.

**Comment by infograf768** [comment]
1. the fact that some of your modules do not display is totally independent from the switcher urls.
2. using sef does not force you to use also htaccess.

in any case, it looks like your issues are unrelated to joomla code but rather t your site settings.
You should seek fo help in the forums imho.
