### ISSUE TITLE
[4.0] Table Options in com_content does not show hints in fields with multiple="true"

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#21015]
### Steps to reproduce the issue 
Go to com_content and click the Table Options. Here a modal is opened with several input fields, some of them are dropdowns with multiple="false" some of them like categories have multile="true"

### Expected result
The Fields contain hints what the user can select

### Actual result
The fields are empty.![screen shot 2018-07-07 at 21 16 42](https://issues.joomla.org/uploads/1/aea8c0d5c2a5091db79f12a6f63c6c08.png)

**Comment by Quy** [comment]
Duplicate #19882<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21015">issues.joomla.org/tracker/joomla-cms/21015</a>.</sub>
