### ISSUE TITLE
[4.0] jQuery not defined in installer.js

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#21028]
Extension manager, install view, check the console

I don't care that the plan is to decouple the jQuery dependency, while it's still there it should still be loaded as needed and it's not being loaded before a script that needs it.

**Comment by dgrammatiko** [comment]
This was due to sync mess. The J4 script was/is jQuery free. The j3 code at some point added the drag and drop functionality (base on jQ) but the code merged in j4 as it was in j3 and thus the console error. I'll do a PR right now for this

**Comment by ghost** [comment]
closed as having Pull Request #21034
