### ISSUE TITLE
[4.0] card-header hijacked in admin template

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#21029]
The Bootstrap `card-header` class is being used outside of cards in the backend, as an example in the well module chrome which isn't enforcing a card element.  I had used the `card-header` class as part of the cards for the 4.0 install from web layouts and this hijacking/reuse basically breaks the display and makes it impossible to use Bootstrap cards.

**Comment by brianteeman** [comment]
not so much hijaaking as misuse in the module chrome if i understand this correctly

**Comment by mbabker** [comment]
Seems to not be a concern, I will rework Install from Web to not use the Bootstrap card element instead once enough of the work on the proposal from last year has been completed to best determine how to refresh the interface.
