### ISSUE TITLE
[4.0] Admin Breadcrumb Contrast Unsuitable

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#21027]
Go to install from web, go to any extension, look at the breadcrumb

<img width="1140" alt="screen shot 2018-07-09 at 8 19 06 pm" src="https://user-images.githubusercontent.com/368545/42483841-80e58c26-83b5-11e8-829e-95679f220024.png">

**Comment by brianteeman** [comment]
This will be resolved when all the references to bootstrap.tab are replaced with uitab.tab
### bootstrap tab
<img width="943" alt="chrome_2018-08-21_15-35-44" src="https://user-images.githubusercontent.com/1296369/44408296-038bd180-a558-11e8-9a7e-58731057205c.png">

### ui tab
<img width="541" alt="chrome_2018-08-21_15-35-18" src="https://user-images.githubusercontent.com/1296369/44408295-038bd180-a558-11e8-81bf-6417a821be7a.png">

**Comment by mbabker** [comment]
Tabs !== Breadcrumbs?

**Comment by brianteeman** [comment]
They aren't breadcrumbs in the code (at least not in the menu  item etc)

**Comment by mbabker** [comment]
I'm talking about the actual breadcrumb (Extensions / Access & Security), not the tabs.  I know the tabs are in a state of flux pending someone going through updating all the things.

**Comment by brianteeman** [comment]
Sorry you mean you are referring to 
![image](https://user-images.githubusercontent.com/1296369/44409514-5feff080-a55a-11e8-9fc9-7302c33d5378.png)

**Comment by mbabker** [comment]
Correct.

**Comment by brianteeman** [comment]
so whats wrong with it? what would you like?

**Comment by mbabker** [comment]
The background contrast of the breadcrumb bar is indistinguishable from the page background.  Either the breadcrumb bar should have no background  (which might work OK for this template), or the background color be made darker to distinguish it.

**Comment by brianteeman** [comment]
would this be ok for you - it matches other parts

![image](https://user-images.githubusercontent.com/1296369/44410488-63847700-a55c-11e8-85ea-f8f9737ffff8.png)

**Comment by mbabker** [comment]
Yes.

**Comment by brianteeman** [comment]
closed see #21798
