### ISSUE TITLE
Module position names no longer "free" in J4

### ISSUE THREAD

**Issue by germi** [joomla/joomla-cms#21033]
Hi guys,

in J3 and before, you could type a module position, and virtually create any possible module position you may need.

in J4, looks like this option is gone and the position selector (while editing a module) is, again, just a dropdown where you can choose from pre-defined options (from the template).

Is this how it's supposed to work? this takes a way a great deal of versatility compared to J3, I think...

**Comment by dgrammatiko** [comment]
This is due to the removal of chosen from that field...

**Comment by brianteeman** [comment]
That explains why it has changed but doesnt say if that is the intended behaviour for this field

**Comment by dgrammatiko** [comment]
> but doesn't say if that is the intended behaviour for this field

I don't think that anyone actually wants to remove this feature
We have to find a replacement for chosen that fulfils at least the 3 basic side operations:
- tags
- category creation
- search/add option (eg, this one was used in the modules)

**Comment by brianteeman** [comment]
thats the problem with merging incomplete software - no ones knows if it is a bug, missing feature or intended design
