### ISSUE TITLE
Menu items should have fields too

### ISSUE THREAD

**Issue by muuvmuuv** [joomla/joomla-cms#21036]
### Is your feature request related to a problem? Please describe.

I‘m currently using the `pageclass_sfx` to get a unique name for each unit we have on our webpage. So if I give one top-level menu the class "Software" the body will have a page attribute with this string in it. Now I came up to the problem that I need to give one menu item a _class_ and this is not going to work anymore…

### Describe the solution you'd like

Copy and Paste fields from articles to menus 😁

**Comment by brianteeman** [comment]
why wont it work - you can have multiple words in that field

**Comment by muuvmuuv** [comment]
@brianteeman Yes that is correct, but I want to have them separated. Can I get a workaround for that with a plugin?

That is how it looks: `<body debug page="software" class="special">`

**Comment by brianteeman** [comment]
The best place to ask is the forum. Its not a generic use case that should go in the core
