### ISSUE TITLE
Tags on milestones

### ISSUE THREAD

**Issue by gerald-b** [joomla/joomla-cms#21041]
### Is your feature request related to a problem? Please describe.
If i read the Issues of a milestone, i can't find out, which issue is a security issue.
On Joomla.org in the Release notes i can identify there are some security issues.
but if you go to see the full list you can't see which one is the security one.
for example https://www.joomla.org/announcements/release-news/5734-joomla-3-8-9-release.html

### Describe the solution you'd like
Add one or more corresponding tags

**Comment by infograf768** [comment]
Security issues are treated separately by the JSST. They should not be public.
Corrections are specifically done just before stable is released.
If one finds a security issue, one has to mail to JSST.
security@joomla.org

**Comment by ghost** [comment]
closed as answered.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21041">issues.joomla.org/tracker/joomla-cms/21041</a>.</sub>
