### ISSUE TITLE
[4.0] page-title width doesn't work on Edge/IE11

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#21040]
### What needs to be fixed

![image](https://user-images.githubusercontent.com/876623/42525448-793d6a0c-8473-11e8-9edd-d58a8383fd21.png)

### How would you fix it

.d-flex.col {
    flex-basis: auto;
}

**Comment by brianteeman** [comment]
confirmed the issue on ie11

**Comment by SharkyKZ** [comment]
Test PR #21086 please.

**Comment by ghost** [comment]
closed as having Pull Request #21086
