### ISSUE TITLE
[4.0]Sample data menu creation

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21073]
### Steps to reproduce the issue
Install joomla and then install the sample data

### Expected result
Menus are created with unique alias that  are lowercase and do NOT include spaces eg **author-menu**

### Actual result
Menus are created without any changes eg **Author Menu**

This results in menu links in the administrator that are invalid markup because they have a space in the href

### Additional comments
Tested in J4 but probably the same problem in J3

**Comment by Bakual** [comment]
You mean the "Menu Type"? I don't see an alias for the menu itself. In J3 they seem to work fine, or I miss where it breaks.

**Comment by brianteeman** [comment]
see the video for explanation

![sample](https://user-images.githubusercontent.com/1296369/42589051-a247f808-8537-11e8-9f03-35c8724726f1.gif)

**Comment by Bakual** [comment]
Works for me in Chrome and Edge both in J3 and J4.
May that be related to the browser how the link is handled?

The line that would need to be changed is
https://github.com/joomla/joomla-cms/blob/39ab4f80f981e552c1b8ed9fd0d7beb50d0d0022/plugins/sampledata/blog/blog.php#L339
Adding `ApplicationHelper::stringURLSafe($type);` to the mix probably solves the issue.

**Comment by brianteeman** [comment]
There are two issues.

1. A link with a space in it is invalid html. It might work as a link but assistive technology may not understand it.

2. As shown in the video the value changes when you save

**Comment by Bakual** [comment]
Check #21080. That did fix it for me. I did it for J3 since the same issue is present there as well.

I'm closing this issue since we have a PR.
