### ISSUE TITLE
[4.0]Joomla-tabs custom element

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21074]
### Steps to reproduce the issue
go to the permissions page of an article and then the permissions tab and view source

### Actual result
`<joomla-tab orientation="vertical" data-ajaxuri="' . $ajaxUri . '" id="permissions-sliders">
`

### Expected result
The $ajaxUri is replaced with something

**Comment by ggppdk** [comment]
Permissions modifications seem to be working properly 

Attributes
` data-ajaxuri="' . $ajaxUri . '" id="permissions-sliders"`
do not seem to be needed here:

https://github.com/joomla/joomla-cms/commit/bb52edf5726b8357579b19e2c1302d495abf72f4#diff-fcdfc03068f0957f766ac041cc0eedbcR81

The tag attributes are only needed here ? @dgrammatiko 
https://github.com/joomla/joomla-cms/commit/bb52edf5726b8357579b19e2c1302d495abf72f4#diff-fcdfc03068f0957f766ac041cc0eedbcR80

**Comment by dgrammatiko** [comment]
@brianteeman what @ggppdk is pointing out, tabs dont have an ajax url, that belongs to the custom element permissions. I guess a sync miss

**Comment by brianteeman** [comment]
I am just reporting the error that needs to be fixed

**Comment by dgrammatiko** [comment]
actually there are more things that needs to be patched with tabs (the accordion implementation is not a11y although it passed the audit :( )

**Comment by brianteeman** [comment]
roflmao two elements tested for a11y and both failed

**Comment by dgrammatiko** [comment]
it's not funny, it means that we need to spend more time and redo them

**Comment by dgrammatiko** [comment]
Check #21078
