### ISSUE TITLE
[4.0] Toolbar with button using 2 different Html Tags as button container stuck to each other

### ISSUE THREAD

**Issue by ggppdk** [joomla/joomla-cms#21081]
### Steps to reproduce the issue

I have this issue with my extension but there are other backend screens that have same issue:

Go to backend templates manager and edit atum template
Toolbar contains

```html
<div class="btn-toolbar d-flex" role="toolbar" aria-label="Toolbar" id="toolbar">
	<button data-toggle="modal" data-target="#copyModal" ...
	<button data-toggle="modal" data-target="#folderModal" ...
	<button data-toggle="modal" data-target="#fileModal"...
	<joomla-toolbar-button id="toolbar-cancel" task="template.cancel" ...
	<button id="toolbar-help" ...
</div>
```

### Expected result

```html
	<button data-toggle="modal" data-target="#fileModal"...
	<joomla-toolbar-button id="toolbar-cancel" task="template.cancel" ...
```
have spacing between them

### Actual result
They are stuck to each other
![stuck_button](https://user-images.githubusercontent.com/5092940/42597637-15387a48-8562-11e8-8a9d-b63a79d9dd8b.png)

### System information (as much as possible)
4.0-dev with new backend template update

### Additional comments
```css
.subhead .btn-toolbar > :first-of-type {
    margin-left: 0;
}
```
should use `:first-child` instead of  `:first-of-type`

**Comment by brianteeman** [comment]
closed see #21202
