### ISSUE TITLE
[4.0] Can't install on dockerized/kubernetes envrionments

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21089]
### Steps to reproduce the issue
Create an lamp container environment an Nginx proxy i.e. with docker.
Download Joomla_4.0.0-alpha3-Alpha-Full_Package.zip and start the Installer.

### Expected result
Installation is successful and can be used. 

### Actual result
1. Installation process hangs up after enter mysql credentials getting this error:
```php
 TypeError: Uncaught exception 'TypeError' with message 'Argument 1 passed to Joomla\Utilities\ArrayHelper::toObject() must be of the type array, null given, called in /var/www/htdocs/joomla4/installation/src/Model/ConfigurationModel.php on line 39' in /var/www/htdocs/joomla4/libraries/vendor/joomla/utilities/src/ArrayHelper.php:70
in Joomla\Utilities\ArrayHelper::toObject called at /var/www/htdocs/joomla4/installation/src/Model/ConfigurationModel.php (39) in Joomla\CMS\Installation\Model\ConfigurationModel::setup called at /var/www/htdocs/joomla4/installation/src/Controller/InstallationController.php (90) in Joomla\CMS\Installation\Controller\InstallationController::config called at /var/www/htdocs/joomla4/libraries/src/MVC/Controller/BaseController.php (710) in Joomla\CMS\MVC\Controller\BaseController::execute called at /var/www/htdocs/joomla4/installation/src/Application/InstallationApplication.php (301) in Joomla\CMS\Installation\Application\InstallationApplication::executeController called at /var/www/htdocs/joomla4/installation/src/Application/InstallationApplication.php (194) in Joomla\CMS\Installation\Application\InstallationApplication::dispatch called at /var/www/htdocs/joomla4/installation/src/Application/InstallationApplication.php (223) in Joomla\CMS\Installation\Application\InstallationApplication::doExecute called at /var/www/htdocs/joomla4/installation/src/Application/InstallationApplication.php (236) in Joomla\CMS\Installation\Application\InstallationApplication::execute called at /var/www/htdocs/joomla4/installation/includes/app.php (43) in require_once called at /var/www/htdocs/joomla4/installation/index.php (36)
``` 

2. Installation succeeded but after login in to administrator, sessions are terminated instantly.
![error](https://user-images.githubusercontent.com/37540795/42643518-9e7f7f08-85f9-11e8-9978-8d4b79e339c0.PNG)

After click on one menu I get logged out. 

### System information (as much as possible)
kubernetes cluster with:
1 Apache Container (2.4.29 Ubuntu)
1 MySQL Container (5.7.19-17)
1 PHP-Container (7.1.17)
Session save handler = files
Session save path = /tmp (it's writable)

They are all linked to each other and for testing there is no scaling or something like that (so a shared session storage can't be the reaseon).

A Nginx(1.13.3) proxy is setup in front of the Apache container.

### Additional comments
Same setup with Joomla 3.8.10 works fine and there are no problems.
I guess we may have some more session bus in Joomla! 4. Cause redis is also not working:
https://github.com/joomla/joomla-cms/issues/20427

What I would prefer to use

**Comment by brianteeman** [comment]
Please retest with the nightly package as the alpha3 is very old https://developer.joomla.org/nightly-builds.html

**Comment by ghost** [comment]
I have same problem with the nightly builds.
It has to do something with session handling, cause sometime the installation process succeeded.
But then my session get terminated aft I login to the administrator. 

I add a screenshot to the actual result and some more description

**Comment by brianteeman** [comment]
to try and confirm if it is session can you try changing Session save handler = files
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21089">issues.joomla.org/tracker/joomla-cms/21089</a>.</sub>

**Comment by ghost** [comment]
@brianteeman changing to which handller. It's allready set to files.

If diesable both ini settings session.save_path and session.save_handler, php is using redis as session handler, which seems not to work currently at all.

So using files is the only way to getting the installer work to the point where we are now.

So in the few times I could finished the installtion, I tried to access the backend and got two different errors. The first one is the one in the screenshot. The second one ist default message for an invailed security token.

Whats realy strange is that Joomla 3.8.10 works fine.

**Comment by brianteeman** [comment]
I wouldnt be surprised that 3.x works and 4.x doesnt - there are a lot of fundamental changes

you can set the 	`public $session_handler = 'database';
`

that might help to track down the problem

**Comment by ghost** [comment]
So. I tested the database handler and got the same issue.
But I did some more testing.

After getting the  invalided security token error, I truncated the session table and clean the browser cache and session storage(browser).  By this I was sometimes able to login for some seconds and got kicked out with same error as sown in the screenshot.

**Comment by brianteeman** [comment]
Can you check and see if it is the same/related to #20821

**Comment by ghost** [comment]
Hey thanks for this hint. I know this issue already and check this. Sadly this not related.
I am able to start the installer and do all steps of the installation.

But sometimes installation can't be finished like described and if it's finished  I am not able to use the administrator because I get an token error or kicked out of the session.

open_basedir is fine. It's set to the documentroot and `/tmp/`writable.
Dirs are also writebale
The issue #20821  says that under same setting `/var/lib/php/session` is required for the installation in open_basedir. But I didn't get this error in the php_error logs. So this not the issue in my case.

`$path = $path ?: ini_get('session.save_path');` gives `/tmp`

**Comment by ghost** [comment]
Ok. Installation seems now to be possible quite every time.
I figured out that there is a problem in the step where database credentials are entered.
If fill all fields by copy and paste, the last input filed will get no green check until I click some where on the page. 

So if fill all fields this way and the click direct on "install joomla"  there is no green check on the prefix field and this error occur:
```php
ypeError: Uncaught exception 'TypeError' with message 'Argument 1 passed to Joomla\Utilities\ArrayHelper::toObject() must be of the type array, null given, called in /var/www/htdocs/joomla4/installation/src/Model/ConfigurationModel.php on line 39' in /var/www/htdocs/joomla4/libraries/vendor/joomla/utilities/src/ArrayHelper.php:70
in Joomla\Utilities\ArrayHelper::toObject called at /var/www/htdocs/joomla4/installation/src/Model/ConfigurationModel.php (39) in Joomla\CMS\Installation\Model\ConfigurationModel::setup called at /var/www/htdocs/joomla4/installation/src/Controller/InstallationController.php (90) in Joomla\CMS\Installation\Controller\InstallationController::config called at /var/www/htdocs/joomla4/libraries/src/MVC/Controller/BaseController.php (710) in Joomla\CMS\MVC\Controller\BaseController::execute called at /var/www/htdocs/joomla4/installation/src/Application/InstallationApplication.php (301) in Joomla\CMS\Installation\Application\InstallationApplication::executeController called at /var/www/htdocs/joomla4/installation/src/Application/InstallationApplication.php (194) in Joomla\CMS\Installation\Application\InstallationApplication::dispatch called at /var/www/htdocs/joomla4/installation/src/Application/InstallationApplication.php (223) in Joomla\CMS\Installation\Application\InstallationApplication::doExecute called at /var/www/htdocs/joomla4/installation/src/Application/InstallationApplication.php (236) in Joomla\CMS\Installation\Application\InstallationApplication::execute called at /var/www/htdocs/joomla4/installation/includes/app.php (43) in require_once called at /var/www/htdocs/joomla4/installation/index.php (36)
```
If I click somewhere on the page before clicking "install" everything goes on fine. 

But after successful installation the problem with login still happen.
Hope this information help.

**Comment by ghost** [comment]
@f-hamel can this Issue be closed?

**Comment by ghost** [comment]
Yes we can.
I guess somithin is wrong with the envrionment an session handling in php.
