### ISSUE TITLE
Taxi Booking Extension - Coupon Code not working

### ISSUE THREAD

**Issue by dreamztechsupport** [joomla/joomla-cms#21093]
I have an issue on Taxi Booking Component Extension. The Coupon Code cannot working. I already set all the setting and have a try few times but it still can't work. When I enter the Coupon Code, the subtotal for the price did not deduct the coupon code price. Can you try to look at this issue ? 

Thank you

**Comment by alikon** [comment]
please ask support at developer, this is only for joomla core

**Comment by ghost** [comment]
closed as no Core-Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21093">issues.joomla.org/tracker/joomla-cms/21093</a>.</sub>
