### ISSUE TITLE
[Modern routing] Fix wrong link to user edit profile

### ISSUE THREAD

**Issue by hfittipaldi** [joomla/joomla-cms#21099]
### Steps to reproduce the issue
Create a menu item to link to user profile menu option of com_users, set alias to user-profile. Create a menu item to link to user edit profile menu option of com_users, set alias to user-edit-profile.
Go to user profile and click on link 'Edit Profile'

### Expected result
Go to the correct page user-edit-profile

### Actual result
The link is going to user-profile?layout=edit

### System information (as much as possible)
Windows 10 - 64bits
MYSQL 5.7.14
PHP 7.1.12
Apache 2.4.23 (Win64)
Joomla! 3.8.10 Stable

**Comment by mbabker** [comment]
Duplicate of #20485 and #20958

**Comment by hfittipaldi** [comment]
Well, not quite. The issue #20485 refers to the cancel button, this is working fine. And the issue #20958 asks for a link to the profile view from the edit profile form, this is the cancel button.
Mine issue refers to the link 'edit profile' on profile page when there is a menu item pointing to edit profile page.

**Comment by mbabker** [comment]
It's the same underlying root issue.  The router doesn't account for layouts in generating URIs and the profile view has multiple layouts.

**Comment by hfittipaldi** [comment]
So, you're suggesting that I override the profile view layout pointing to the correct page? It is easy. But, to me, it seems an issue that has to be correct.

**Comment by mbabker** [comment]
And that's why the other two items are still open 😉 (it's a confirmed bug, we don't need multiple issues open for the same item and generally close duplicates to keep things in one spot)

**Comment by hfittipaldi** [comment]
My two cents, then: close the issue #20958, because there already is the cancel button. The other one refers to Joomla! 4.0 which is still in development, and my issue is the 'correct one'  😉
