### ISSUE TITLE
[4.0] Install "Blog Sample Data" fails

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21108]
### Steps to reproduce the issue
Try to install "Blog Sample Data". Message "Something failes" comes up, it ends with this:
![screen shot 2018-07-14 at 06 32 18](https://user-images.githubusercontent.com/8235763/42720878-14e54b5a-8730-11e8-9223-6cfb2d403de5.jpg)
### System information
- Joomla! 4.0.0-alpha4-dev
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve
### Additional comments
Nightly Build the Night before works as expected.

**Comment by anuragteapot** [comment]
@franz-wohlkoenig Can you please test again with fresh and latest j4?
I think this issue is solved after this #21114

**Comment by ghost** [comment]
On latest Nightly Build Multilang. Sample Data are installed, tried to install also Blog Sample Data got no "Something fails"-Message but same as Screenshot above: spinning Logo, so i closed it after a few Minutes waiting.

**Comment by infograf768** [comment]
Which sample data is installed before you try the Blog Sample Data?
If it is the Multilingual sample data, no issue here.

**Comment by ghost** [comment]
Issue reported trying to install Blog Sample Data. 

In the Meantime installed Multilang Sample Data. So if the Blog Sample Data fail is no Issue i will try on a clean Install if Blog Sample Data works as @Anu1601CS guessed.

**Comment by ghost** [comment]
@Anu1601CS is correct, Issue is solved as Blog Sample Data get installed as expected.
