### ISSUE TITLE
[4.0] "Batch"-Button isn't greyed out without marked Article

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21109]
### Steps to reproduce the issue
As Title say:

![screen shot 2018-07-14 at 06 59 58](https://user-images.githubusercontent.com/8235763/42721065-93d2340c-8733-11e8-935a-d375ca5227cc.jpg)

Also notice "Check in"- and "Batch"-Button container stuck to each other which is reported at #21081.

### System information
- Joomla! 4.0.0-alpha4-dev
- Multilingual Sample Data
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by Quy** [comment]
@Fedik

**Comment by Fedik** [comment]
yeah, that a valid issue,
this is for reference https://github.com/joomla/joomla-cms/pull/20777#issuecomment-397859740 (with explanation)

**Comment by Fedik** [comment]
@franz-wohlkoenig please test #21284

**Comment by ghost** [comment]
closed as having Pull Request #21284
