### ISSUE TITLE
MailHelper::isEmailAddres false positive

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#21107]
### Steps to reproduce the issue

````echo Joomla\CMS\Mail\MailHelper::isEmailAddress('demo@democom');````

### Expected result

false, because no dot

### Actual result

true

### System information (as much as possible)
Joomla! 3.8.11-dev

**Comment by brianteeman** [comment]
That is correct as it is a valid email address on an intranet

**Comment by ghost** [comment]
closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21107">issues.joomla.org/tracker/joomla-cms/21107</a>.</sub>
