### ISSUE TITLE
[3.9] [com_fields] Fields - Repeatable: __DEPLOY_VERSION__

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21112]
### Steps to reproduce the issue
In "Extensions: Manage" the Fields - Repeatable has Version __DEPLOY_VERSION__:
![screen shot 2018-07-14 at 14 48 29](https://user-images.githubusercontent.com/8235763/42724594-811dc6ea-8775-11e8-8fd8-754d7737d8a9.jpg)
### System information
- 3.9-dev
- Template: Protostar
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.2.3
- MySQLi 5.7.18-cll-lve

**Comment by brianteeman** [comment]
Expectrd behaviour. Automatically changed when the release is tagged.

**Comment by ghost** [comment]
thanks @brianteeman
