### ISSUE TITLE
[4.0] Nightly Build on launch.joomla.org (CloudAccess) give Error

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21119]
### Steps to reproduce the issue
Using Custom URL https://update.joomla.org/core/nightlies/next_major_list.xml on launch.joomla.org
give Error:

![screen shot 2018-07-14 at 21 18 27](https://user-images.githubusercontent.com/8235763/42727702-ae5be34a-87ab-11e8-8d17-43cd01110533.jpg)

Looks like a CloudAccess-Problem as discussed with Tobias Zulauf.
### System information
- Joomla! 4.0.0-alpha4-dev
- Multilingual Sample Data
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by wojsmol** [comment]
@franz-wohlkoenig Do you know whether this issue was reported to Cloud Acces?

**Comment by ghost** [comment]
I haven't as People of CA are here writing.

**Comment by Sandra97** [comment]
Reported to CA.

**Comment by ghost** [comment]
@Sandra97 so in Future its better to Report at CCP?

**Comment by Sandra97** [comment]
For all issues related to launch, the best is to open them in the websites repo, like for any of our properties.

**Comment by ghost** [comment]
haven't found launch.joomla.org at Website-Repo.

**Comment by Sandra97** [comment]
You can use the .com label (as it's for *.joomla.com websites) for the moment. I can add launch to the readme file and I'll see with CA if they can add the report link in the footer of launch

**Comment by ghost** [comment]
thanks @Sandra97

**Comment by ghost** [comment]
closed as reported on launch.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21119">issues.joomla.org/tracker/joomla-cms/21119</a>.</sub>
