### ISSUE TITLE
[4.0] Fatal Error on creating new Banner Category

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21111]
### Steps to reproduce the issue
As Title says: ```Fatal error: Cannot use Joomla\CMS\Factory as Factory because the name is already in use in /administrator/components/com_categories/Model/CategoryModel.php on line 32```
### System information
- Joomla! 4.0.0-alpha4-dev
- Multilingual Sample Data
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by SharkyKZ** [comment]
Test PR #21114 please.

**Comment by ghost** [comment]
closed as having Pull Request #21114
