### ISSUE TITLE
[4.0] "Showon" shown on Top instead Bottom

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21113]
### Steps to reproduce the issue
Test in Options "Articles", "Contacts", Tab "Integration":

Select "URL Routing":
![screen shot 2018-07-14 at 15 05 23](https://user-images.githubusercontent.com/8235763/42724711-b44b5a3a-8777-11e8-82cd-86894001d391.jpg)

Showon "Remove IDs from URLs" shown on Top instead Bottom:
![screen shot 2018-07-14 at 15 05 36](https://user-images.githubusercontent.com/8235763/42724713-b71d84b8-8777-11e8-994d-76387e5f0d69.jpg)
### System information
- Joomla! 4.0.0-alpha4-dev
- Multilingual Sample Data
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by SharkyKZ** [comment]
Test PR #21115 please.

**Comment by ghost** [comment]
closed as having Pull Request #21115
