### ISSUE TITLE
[4.0] Featured Articles: Search shown twice

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21120]
### Steps to reproduce the issue
As Title say:
![screen shot 2018-07-14 at 21 38 13](https://user-images.githubusercontent.com/8235763/42727871-69d5c346-87ae-11e8-9a1f-802c07f5d84f.jpg)
### System information
- Joomla! 4.0.0-alpha4-dev
- Multilingual Sample Data
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by brianteeman** [comment]
needs this same fix i put in #21087

**Comment by Quy** [comment]
See PR #21123<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21120">issues.joomla.org/tracker/joomla-cms/21120</a>.</sub>
