### ISSUE TITLE
[4.0] Click on Article-Category give Fatal Error

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21121]
### Steps to reproduce the issue
Click on a Category on Pencil or Name, got:
```Fatal error: Cannot use Joomla\CMS\Factory as Factory because the name is already in use in /administrator/components/com_categories/Model/CategoryModel.php on line 32```
### System information
- Joomla! 4.0.0-alpha4-dev
- Multilingual Sample Data
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by SharkyKZ** [comment]
Same issue as #21111. Should be fixed with PR #21114.

**Comment by ghost** [comment]
Test on Nightly Build: Issue stay. Maybe solved in Staging? If not, please reopen here as at Issue Tracker i got "Invalid response from GitHub".
