### ISSUE TITLE
[4.0] custom admin menu issue

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#21125]
### Steps to reproduce the issue
Create an admin menu.
Create, as we can do in 3.x, a Menu Heading item.
Add various menu items with the Menu Heading as parent.
(Keep the default admin menu displayed.)
### Expected result
The Menu Heading displays and its children can be found by clicking on it.

### Actual result
Another `Toggle Menu` is displayed below the existing core admin Menu. It should not.
The children do not show.

 @coolcat-creations
I know the new backend template is not stable for the moment. Is that a part which will be solved?
Looks like all parameters for these admin menu items need some work (image, etc.)

**Comment by coolcat-creations** [comment]
@infograf768 Yes, the menu is still a big issue for Joomla 4 and not final.

**Comment by ghost** [comment]
Please add Label "J4 Backend Template".

**Comment by infograf768** [comment]
Closing as this has been solved since.
