### ISSUE TITLE
JFormFieldCalendar using 12 hour format

### ISSUE THREAD

**Issue by billtomczak** [joomla/joomla-cms#21148]
This is a re-report of the issue reported in #18304. PR #18240 did not fix these issues and they remain as of v3.8.10

Creating a new issue as requested by [franz-wohlkoenig](https://github.com/franz-wohlkoenig)

### Steps to reproduce the issue
Edit /administrator/components/com_content/models/forms/article.xml and edit the publish_up field attributes:
* remove `translateformat`
* add `format="%Y-%m-%d %I:%M %P"`
* add `timeformat="12"`

The final result should look something like:

```xml
		<field
			name="publish_up"
			type="calendar"
			label="COM_CONTENT_FIELD_PUBLISH_UP_LABEL"
			description="COM_CONTENT_FIELD_PUBLISH_UP_DESC"
			showtime="true"
			format="%Y-%m-%d %I:%M %P"
			timeformat="12"
			size="22"
			filter="user_utc"
		/>
```

Then edit any article's `Start Publishing` field to set the time to midnight using the calendar tool and save the changes.

### Expected result
After saving, the time displaying in the text field should be 12:00 am (as of v3.8.7, the am/pm selector forces to pm)

### Actual result
The time in the text field is set to 12:00 pm

Also, the am/pm selector text is not wide enough and the option texts are hidden (see screenshot)

### System information (as much as possible)
The time can be set manually in the text box to '12:00 am' and is saved as expected. But then you'll notice the hour drop down selection is empty. (See screenshot)

For the am/pm selector, it has a `colspan="1"` hardcoded and I believe it should be `colspan="2"`.

### Additional comments
![screen shot 2017-10-11 at 01 57 39](https://issues.joomla.org/uploads/1/37777738dc7cc8e900822cb522fcf2e2.png)

**Comment by ghost** [comment]
@dgrammatiko a Comment by you?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21148">issues.joomla.org/tracker/joomla-cms/21148</a>.</sub>

**Comment by GCLW** [comment]
While my attempted "fix" did work for `format="%Y-%m-%d %H:%M:%S"` it did not fix other format and timeformat combinations.

While making additional changes I tested the following combinations:
`format="%Y-%m-%d %I:%M %P"` & `timeformat="12"` : passed
`format="%Y-%m-%d %I:%M %P"` & `timeformat="24"` : passed
`format="%Y-%m-%d %H:%M:%S"` & `timeformat="12"` : passed
`format="%Y-%m-%d %H:%M:%S"` & `timeformat="24"` : passed

The test was flipping noon and midnight back and forth while saving and paying attention to when the calendar updated, did the input field display the format correctly. Also the calendar reading the format and displaying in the correct timeformat the first time you click on it.

* I also noticed that manually editing the input field and then clicking on the calendar, the calendar would not display the AM/PM correctly. I made further changes to correct that. Yes, a client of mine will actually manually type in a change to the input field.

I'm attaching the updated calendar.txt[calendar.txt](https://issues.joomla.org/uploads/1/70ecff8dca0db2aef6cb99e204a0cd33.txt) file, if someone would like to minify the file and test feel free. I'm not the original author of this powerful calendar code, I just made some changes where I thought they were needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21148">issues.joomla.org/tracker/joomla-cms/21148</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #24417

**Comment by billtomczak** [comment]
Thank you https://github.com/Arpit-24! I can confirm the PR corrects the problem in English.

**Comment by ghost** [comment]
@billtomczak please mark your Test at https://issues.joomla.org/tracker/joomla-cms/24417 as successfully

**Comment by laoneo** [comment]
Pr #24417 is abandoned. So reopening the issue.

**Comment by brianteeman** [comment]
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed. 

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
