### ISSUE TITLE
[4.0] New backend template - distance between toolbar buttons issue

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#21143]
### Steps to reproduce the issue
1. Open the `Users|Manage` Menü.

![users test administration](https://user-images.githubusercontent.com/9974686/42759823-9450f43c-8908-11e8-8539-ab0c989267d6.png)

### Expected result

Between all toolbar buttons is the same distance

### Actual result

The last toolbar button has no distance to the left.

### System information (as much as possible)
Current 4.0-dev branch on Ubuntu 18.04

### Additional comments
This example is just one of many. Also in other view the last button has no distance to the left.

Where should this issue be fixed? Should it be fixed in this repo or in the backend-template repo (https://github.com/joomla/40-backend-template)?

**Comment by SharkyKZ** [comment]
Duplicate #21081 and  #21109.
