### ISSUE TITLE
[4.0] New backend template - change tab issue

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#21142]
### Steps to reproduce the issue
1. Open the `System` Menü and click on `Site Template`
2. Open the `Styles` Menü on the left side and select the template `cassiopeia`.
3. Select the Tab `Advanced` and insert a `title`.
4. Click on the toolbar button save.

### Expected result

Everything is saved and you stay in the Tab `Advanced` 

### Actual result

Everything is saved and you are redirected into the Tab `Details` 

### System information (as much as possible)
Current 4.0-dev branch on Ubuntu 18.04

### Additional comments
This example is just one of many. Also in other view one is redirected to the first tab, if one clicks on a button in the toolbar.

Where should this issue be fixed? Should it be fixed in this repo or in the backend-template repo (https://github.com/joomla/40-backend-template)?

**Comment by dgrammatiko** [comment]
This is expected. The new tabs script is including the tabs state behaviour but the old one is used here (and almost everywhere else, we just changed a couple views). Also, the tabs state script has already been moved to legacy with the aim to totally drop it

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21142">issues.joomla.org/tracker/joomla-cms/21142</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #21183

**Comment by PhilETaylor** [comment]
>  the tabs state script has already been moved to legacy with the aim to totally drop it

All my hard work gone...haha 

The hours I spent getting that right for J3 were crazy...
