### ISSUE TITLE
Media manager doesn't obey relative pathes for video files

### ISSUE THREAD

**Issue by Codereamp** [joomla/joomla-cms#21145]
### Steps to reproduce the issue
- Make sure video files can be uploaded (legal extensions, MIME times). Let's the media folder is www.mysite/media
- Create any sub-folder in main Media folder (for example 'myvideos')
- Upload a video to this new folder, so the correct location is www.mysite/media/myvideo/myvideo.mp4. 
- Hover the mouse, notice that the lacking sub-folder part (www.mysite/media/myvideo.mp4)
- Try to click the preview link, get the error about file not existing or not supported format. 

### Expected result
- The link to the video file should be resolved to the correct location like for images ( www.mysite/media/myvideo/myvideo.mp4 )

### Actual result
- The link is broken (lacks the sub-folder part) ( www.mysite/media/myvideo.mp4 )

### Additional comments

The bug is easily fixed by correcting the file
  \administrator\components\com_media\views\medialist\tmpl\thumbs_videos.php
by replacing 
   <a class="video-preview" href="<?php echo COM_MEDIA_BASEURL, '/', rawurlencode($video->name);
with 
   <a class="video-preview" href="<?php echo COM_MEDIA_BASEURL, '/', rawurlencode($video->path_relative);

path_relative is used by the image link machinery, but mistakenly missed here with videos.

**Comment by tonypartridge** [comment]
Can you do a PR please? I’ve noticed it too.

**Comment by Codereamp** [comment]
I see a new status "Information Required". Is addition information required from the issue creator?  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21145">issues.joomla.org/tracker/joomla-cms/21145</a>.</sub>

**Comment by ghost** [comment]
@Codereamp no addition Information required. 

The Status was for me that there is an Question (by @tonypartridge) unanswered.

**Comment by wojsmol** [comment]
@Codereamp @tonypartridge Please test PR https://github.com/joomla/joomla-cms/pull/21156

**Comment by ghost** [comment]
closed as having Pull Request #21156
