### ISSUE TITLE
[4.0] add new css - where?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21162]
As the list views now have a checkbox in the thead with a class of td and not th I need to create some styling for it

Its a really simple piece of css 
.table thead tr td {padding:0}

I know how to build the css from the scss

**I have no idea which scss file to put it in? Any clues?**

**Comment by ciar4n** [comment]
I guess.. https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/scss/vendor/bootstrap/_table.scss

**Comment by brianteeman** [comment]
but that's a vendor file isnt it?

**Comment by ciar4n** [comment]
I can't blame you for thinking that but no. It is just CSS targeting the vendor classes. Personally I think this folder should be removed as it is a little misleading.

Regardless it is where such CSS is been currently added.

**Comment by ciar4n** [comment]
To make a true vendor folder we would need something like this in SCSS... https://github.com/sass/sass/issues/779

Currently there is not.

**Comment by brianteeman** [comment]
ok thanks or that - it is definitely confusing nomenclature
