### ISSUE TITLE
[4.0] Custom element joomla-tab fails on ie11

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21166]
### Steps to reproduce the issue
Open any page using tabs eg article edit using internet explorer 11

### Expected result
Page loads without error

### Actual result
Page stops rendering when it hits the first occurrence of the custom element joomla-tab 

The console reports
SCRIPT438: Object doesn't support property or method 'append'
joomla-tab-es5.min.js (1,5496)

**Comment by C-Lodder** [comment]
What happens if you replace both `append()`'s with `appendChild()`?

**Comment by brianteeman** [comment]
yes that fixes it

@C-Lodder @dgrammatiko can you do a pr to fix it

**Comment by dgrammatiko** [comment]
Sure, since we are here can I have an audit for the tabs component also from you, @brianteeman ?

**Comment by brianteeman** [comment]
you mean for a11y?
If so then I really would prefer it if you asked the a11y team

**Comment by dgrammatiko** [comment]
I have already the results of their audit I just wanted to see what you will come up also

**Comment by brianteeman** [comment]
~I can tell you that it fails on a11y as there is no indicator that you are in a group of tabs or how many there are. It is keyboard accessible but not screenreader accessible~

Here is an example of an accessible tab set
https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html

There may be other ways to achieve it. If you have nvda installed then you can easily compare this example with the joomla tab element~

**Comment by brianteeman** [comment]
perhaps easier to understand what needs to be changed https://www.deque.com/blog/a11y-support-series-part-1-aria-tab-panel-accessibility/

**Comment by brianteeman** [comment]
basically the screenreader should say something like
This is a group of 6 tabs, First tab - content
then
Second tab - images
etc

**Comment by dgrammatiko** [comment]
So instead of the `<ul><li>` we should have `<button>`, fairly easy change

**Comment by brianteeman** [comment]
weird - just restarted nvda and it announced the tabs correctly. Will have to look again and see what I did before that made it not work

**Comment by brianteeman** [comment]
ok found the problem, should be an easy fix that I will look at tonight 
basically when you go to the second tab it announces
tab1title, tab2title tab 2 of 6

**Comment by brianteeman** [comment]
Not an easy fix at all. Spent some time with @fuzzbomb reviewing this verbosity last night. Not found a solution to it yet

**Comment by dgrammatiko** [comment]
@brianteeman let me know if you need some help here. I want to make another release of the custom elements before the next alpha release, so it would be great if we can tackle this issue as well

**Comment by brianteeman** [comment]
If you can fix the ie issue with appendchild I will keep looking into this verbosity issue

**Comment by dgrammatiko** [comment]
I'm gonna patch the append and some wrong id variable, later on and make another release

**Comment by fuzzbomb** [comment]
@brianteeman I confused what the actual issue is.  The summary here says there's a rendering problem, but I don't think we talked about that at all.

I'm not convinced that the verbosity aspect amounts to a bug, we didn't get much time on it.  Bear in mind that different screen readers have different philosophies about what to announce.  It should be a separate issue, rather than conflate it with a rendering script error here.

**Comment by brianteeman** [comment]
@fuzzbomb ignore the rendering problem - thats something new and is apparently an IE 11 issue with tinymce that they are looking at it. The issue with the verbosity is the code in #21204 

Would appreciate it if you were able to take a look at #21227 - dont worry if not. Or we can meetup sometime and look together

**Comment by brianteeman** [comment]
Closing this as ie11 is ok with the tabs now and the other issues can be addressed in their own issue
