### ISSUE TITLE
[4.0] Error in Joomla update. Invalid Ajax data.

### ISSUE THREAD

**Issue by anuragteapot** [joomla/joomla-cms#21160]
### Steps to reproduce the issue
try to do a Joomla update.

For test you can use: https://www.jah-tz.de/downloads/core/gsoc18_override_management/gsoc18_update_list.xml

### Expected result
Update successfully needs to be done!.

### Actual result
Error : `Invalid Ajax data.`

![screenshot from 2018-07-17 17-59-29](https://user-images.githubusercontent.com/30978328/42817380-92b8e0e2-89eb-11e8-8644-0c172bc527d3.png)

### System information (as much as possible)
Linux

### Additional comments
Maybe after this https://github.com/joomla/joomla-cms/pull/21057
issue occurred. 
@brianteeman @wilsonge @mbabker

**Comment by brianteeman** [comment]
possibly due to line 128 restore_finalisation.php

**Comment by mbabker** [comment]
We're going to have to get tricky with this file.  The intent is to overload the core classes, so as they're now namespaced, the overloading has to use the correct namespacing as well.

I think this is right (there are no IDE reported errors and no reported syntax errors linting the file), but I never write files using multiple namespaces, so I have no idea if this is going to do what we want it to.

https://gist.github.com/mbabker/5e171b1df99f71a30290125e0292b1d9

**Comment by astridx** [comment]
I can confirm this issue.

**Comment by ReLater** [comment]
@mbabker  After adding the proposed file https://gist.github.com/mbabker/5e171b1df99f71a30290125e0292b1d9 to an update or full package (Nightly Builds) I could update via Upload&Update without any issues. AJAX error is gone.

**Comment by anuragteapot** [comment]
@mbabker @brianteeman Any progress of this issue? How we have to deal with this file ?

**Comment by mbabker** [comment]
If the comment from @ReLater is any indication of success, just need a pull request updating `administrator/components/com_joomlaupdate/restore_finalisation.php` with the contents of the gist.

**Comment by ReLater** [comment]
See pr https://github.com/joomla/joomla-cms/pull/21332

**Comment by ghost** [comment]
closed as having Pull Request #21332
