### ISSUE TITLE
3.8 and 4.0: com_associations issue with contacts and newsfeeds

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#21178]
### Steps to reproduce the issue
Create a multingual site. 2 languages are enough.
Create a contact in each language and associate them in their edit page.
Load Multilingual Associations component.
Select Contact as type and one fo the languages.
Click on the greyed icon in the Associations column.
This will load the side by side page.

### Expected result
When using the Associations Tab (or button in 4.0) for the reference and the target items, the field for the other language should display the name of the associated contact.

### Actual result
It does not.
As you can see in the animated gif below, it does flash the name for a second at reload, then disapears as soon as the Target finishes loading.
![assocfieldcontact](https://user-images.githubusercontent.com/869724/42925578-f1edc4f8-8b2e-11e8-9ab1-b24b1153cea7.gif)

@rdeutz @laoneo 
### Additional comments
This works fine for articles, categories and menu items

**Comment by SharkyKZ** [comment]
https://github.com/joomla/joomla-cms/blob/7279924ddb1922bd4cb279bbf7d3c4fbf67510c8/media/com_associations/js/sidebyside-uncompressed.js#L263

https://github.com/joomla/joomla-cms/blob/7279924ddb1922bd4cb279bbf7d3c4fbf67510c8/media/com_associations/js/sidebyside-uncompressed.js#L279

Title field in Contacts and Newsfeeds is called `name`, not `title` so `#jform_title` selector doesn't work here.

**Comment by infograf768** [comment]
You are right. changing to `#jform_name` solves the issue.
Now, we do have equivalent in `ContactAssociationsHelper`
`case 'contact':
					$fields['title'] = 'a.name';`

therefore, we have to find a way to change the #jform in the side by side js depending on this parameter.

**Comment by infograf768** [comment]
we get the equivalent to title in associations helper with `$titleFieldName`

**Comment by infograf768** [comment]
OK. I have a patch.Will create PR

**Comment by infograf768** [comment]
Closing as we have a PR for 3.x
https://github.com/joomla/joomla-cms/pull/21180
