### ISSUE TITLE
[4.0] com_content Preview Overlay hide everything + can't be closed

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21170]
### Steps to reproduce the issue
Pagereload close Preview.
![screen shot 2018-07-18 at 10 14 01](https://user-images.githubusercontent.com/8235763/42868974-f9d839e8-8a73-11e8-9a52-7ef6edabd0b0.jpg)
Similar https://github.com/joomla-extensions/patchtester/issues/208
### System information
- Nightly Build 4.0.0-alpha4-dev
- Multilingual Sample Data
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by brianteeman** [comment]
duplicate of #19408 ?

**Comment by ghost** [comment]
looks like so closing.
