### ISSUE TITLE
4.0.0-dev - Article manager: change article don't have "Insert image" button

### ISSUE THREAD

**Issue by Condorious** [joomla/joomla-cms#21182]
How to add images in article if I don't have "Insert image" button in editor panel?

**Comment by ghost** [comment]
do you mean this?

![screen shot 2018-07-19 at 12 43 25](https://user-images.githubusercontent.com/8235763/42938084-64e63f5e-8b51-11e8-861b-5473d073899e.jpg)

**Comment by Condorious** [comment]
Where you get CMS Content button???
![jb](https://user-images.githubusercontent.com/5928109/42938394-8fc5be42-8b6b-11e8-8ab7-de200f15ccd5.png)

**Comment by ghost** [comment]
latest Nightly: https://update.joomla.org/core/nightlies/next_major_list.xml

or

https://developer.joomla.org/nightly-builds.html

**Comment by Condorious** [comment]
Franz, thank you!
I tried update my old version and I crash my joomla.
I maked clean install last joomla version and used previous database, all content from previous version is work in new version!
And yes, now I have image button :0))

**Comment by ghost** [comment]
+1, so can you please close the Issue?
