### ISSUE TITLE
[4.0] Modules: Position-Dropdown miss Style

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21185]
### Steps to reproduce the issue
As Title say:

![screen shot 2018-07-19 at 18 14 23](https://user-images.githubusercontent.com/8235763/42956439-3d8aed72-8b80-11e8-80e1-8eccf458ad68.jpg)

### System information
- Nightly Build 4.0.0-alpha4-dev
- Multilingual Sample Data
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by dgrammatiko** [comment]
It’s a known side effect of removing chosen

**Comment by brianteeman** [comment]
But it hasn't been removed yet

**Comment by dgrammatiko** [comment]
Are you sure? I thought this was one of the places we’ve removed it before getting a working solution (eg no way to insert custom position)

**Comment by ghost** [comment]
this worked Yesterday (or the Day before).

**Comment by SharkyKZ** [comment]
Caused by #20196.

**Comment by wilsonge** [comment]
I've added back chosen in 46a9832. The priority is a functioning backend....

**Comment by dgrammatiko** [comment]
And now you broke the ordering field 😃
