### ISSUE TITLE
[4.0] Width of a joomla-field-switcher

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#21198]
### Steps to reproduce the issue
If I change the width in a joomla-field-switcher element, the width of the span in which the text is located does not change.

![bildschirmfoto vom 2018-07-20 10-57-54](https://user-images.githubusercontent.com/9974686/42993562-f6a8773a-8c0b-11e8-8e84-5a3267b10c73.png)

Only the width of the switcher changes.

![bildschirmfoto vom 2018-07-20 11-00-32](https://user-images.githubusercontent.com/9974686/42993651-314b49da-8c0c-11e8-963b-802a1ae1871a.png)

### Expected result
When I increase the width of a switcher I see the text of the label if this text is long.

See: https://github.com/joomla-projects/gsoc18_override_management/pull/35#pullrequestreview-138712683

**Comment by C-Lodder** [comment]
Not inspected, but just looking at the screenshot I'm not sure how a block element cant have aligned to the right

**Comment by brianteeman** [comment]
Reading the PR you link to and the screenshots there it appears you resolved this as it has been merged so I am going to close this. If I am mistaken it can always be reopened
