### ISSUE TITLE
[4.0] Return value of PlgSystemHttpHeaders::setDefaultHeader() must be an instance of void, none returned

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#21193]
### Steps to reproduce the issue
Make a fork of https://github.com/joomla/joomla-cms, take the 4.0 branch - (state july 20th)
Make a fresh installation and you will get this: 

### System information (as much as possible)
Localhost in 
WIN 10
Xampp 3.2.2
![screen shot 2018-07-20 at 10 10 18](https://issues.joomla.org/uploads/1/fe90fd8cec0170d7c9e26df32047c30c.png)

![screen shot 2018-07-20 at 10 10 20](https://issues.joomla.org/uploads/1/b2c3dd8abea86f386744ac96c78e1dcc.png)

**Comment by chmst** [comment]
@franz-wohlkoenig - I think it is not the installer, or not only.

At the moment, it is not possible to work with the 4.0 dev at all. Could you add a label for system plugin? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21193">issues.joomla.org/tracker/joomla-cms/21193</a>.</sub>

**Comment by ghost** [comment]
changed to com_plugins. Mostly i'm guessing.

**Comment by zero-24** [comment]
@chmst please apply: https://github.com/joomla/joomla-cms/commit/f8934bac251796a29ddc3316152e50ac81e7baf3

**Comment by wilsonge** [comment]
Closing as confirmed fixed :)
