### ISSUE TITLE
Manage extensions > Search Tools > Select Type is textfield instead of select

### ISSUE THREAD

**Issue by kmd-muc** [joomla/joomla-cms#21192]
### Steps to reproduce the issue
In Backend Go to Menu Extensions > Manage > Manage
Click on Search Tools next to search field

### Expected result
Search Tools are displayed with "Select Type" as dropdown

### Actual result
Search Tools are displayed with "Select Type" as textfield

### System information (as much as possible)
Joomla 3.8.10
PHP Built On | Linux d396.x-mailer.de 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018 x86_64
-- | --
Database Type | mysql
Database Version | 5.5.5-10.1.34-MariaDB
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.1.19
Web Server | Apache
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 3.8.10 Stable [ Amani ] 26-June-2018 15:45 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by brianteeman** [comment]
Thank you for the report. This ha already been reported and fixed and will be in the next release
