### ISSUE TITLE
[4.0] com_content: Cannot write in Tags-Field

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21203]
### Steps to reproduce the issue
Create a new Article (or Category) you get in Tags-Field:
![screen shot 2018-07-20 at 20 13 35](https://user-images.githubusercontent.com/8235763/43018335-a26af8fc-8c59-11e8-87ad-ddc809410341.jpg)
You cannot write in Field to create new Tag.

After Click in IE. "Note" Tags-Field is available ("Select some Options"):
![screen shot 2018-07-20 at 20 13 51](https://user-images.githubusercontent.com/8235763/43018403-dae9e56c-8c59-11e8-9a14-62c713d67541.jpg)
### System information
- Nightly Build 4.0.0-alpha4-dev
- Multilingual Sample Data
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by ReLater** [comment]
Related(?): https://github.com/joomla/joomla-cms/issues/21209
Chosen has been removed at the moment without any similiar replacement(?)

**Comment by dgrammatiko** [comment]
no for the tags chosen is still there

**Comment by ghost** [comment]
closed as solved somewhere.
