### ISSUE TITLE
[4.0] frontend routing to admin views [meta]

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21208]
This is a meta issue to combine several related issues and deal with them all in the same issue.
**Fix dispatcher to use the backend** 

This can be seen when editing content on the frontend and using 
- [ ] xtd-editor plugin
- [ ] content history

The **only** xtd-editor plugin that works is the one for com_media so hopefully someone with more knowledge than me (and @wilsonge #18679) is able to fix it

It looks like it is similar to #15455 fixed by @joomdonation

**Comment by ghost** [comment]
closed as having Pull Request #21418

**Comment by laoneo** [comment]
The editor buttons are not done yet.
