### ISSUE TITLE
[4.0] Router bug:  contacts

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#21200]
This report is limited to com_contacts but it could also touch some other components in core.

### Steps to reproduce the issue
Use latest 4.0-dev
Tested on a multilingual site.
Create a contact category tagged to each language.
Create a contact in each of these categories, tagged to the same language.

I have as menu item type "List Contacts in a category" 
`/index.php/en/contact-category-en-gb`

The link on that page displaying the contact is
`/index.php/en/contact-category-en-gb/mycontact` // see below direct menu item. this url is a double with the one below (it should be `/index.php/en/my-contact`). Alias of that single contact is `mycontact`

// I do also have a direct menu item to that contact (alias of the menu item is `my_contact`)
When I use this last one (`/index.php/en/my-contact`), the category link above the contact gives
`/index.php/en/my-contact?view=category&id=14` instead of the existing `/index.php/en/contact-category-en-gb`

**Comment by wilsonge** [comment]
@hackwar can you look into this please?

**Comment by ghost** [comment]
@Hackwar is this something you will look at?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21200">issues.joomla.org/tracker/joomla-cms/21200</a>.</sub>

**Comment by Hackwar** [comment]
Add the $language parameter to the call of getCategoryRoute and this should work. That language parameter is not really optional, but since someone thought "meh, make it optional by giving it a default value", we are running into these issues everywhere.

**Comment by ghost** [comment]
thanks @Hackwar for Comment.

**Comment by infograf768** [comment]
Thanks for the hint.
See https://github.com/joomla/joomla-cms/pull/21679
(`getContactRoute` is also concerned)

Closing as we have a patch
