### ISSUE TITLE
[4.0] Custom module positions

### ISSUE THREAD

**Issue by schnuti** [joomla/joomla-cms#21209]
### Steps to reproduce the issue
Try to enter a custom module position e.g. "hidden" to create a hidden menu module.
I can't. (An empty string is possible.) 

### Expected result
It must be possible to add custom module positions as in 3.x. Not only needed for menu modules.

A "Not used/Hidden" position should be added to the frontend templates positions. I think there is one in the backend template.

**Comment by ReLater** [comment]
Yes, it's a bit confusing what's happening with Chosen like features at the moment:
Related(?)
https://github.com/joomla/joomla-cms/issues/21033
https://github.com/joomla/joomla-cms/issues/21185

**Comment by schnuti** [comment]
@ReLater Yes they are the same or related. I reverted but that is not a fix for custom positions. I can only add a "search text" not a new value. I care less about the look.

> Add back chosen for form. Fixes #21185

**Comment by schnuti** [comment]
Checked in 3.8.10 that it still works as before. It does!

**Comment by brianteeman** [comment]
As far as I can tell this has now been resolved as I had no problem creating custom positions

**Comment by ghost** [comment]
closed cause comment above. Please reopen if i'm wrong.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21209">issues.joomla.org/tracker/joomla-cms/21209</a>.</sub>
