### ISSUE TITLE
[4.0] Where did Modules go. I miss them.

### ISSUE THREAD

**Issue by schnuti** [joomla/joomla-cms#21210]
### Steps to reproduce the issue
I guess it's an "error" during development progress. Only want to say that in my latest 4.0 update the module manager only can be reached from the Control Panels oversized button.

(The first thing I'll remove/override in a stable 4.0)

###
I do think the module manager should be included in the menu. It should not be hidden in the System view. As for now it's NOT in there.

**Comment by SharkyKZ** [comment]
Modules are available in the menu under Content.

**Comment by schnuti** [comment]
OK thanks. Isn't almost everything content if all modules are? Not very user friendly
