### ISSUE TITLE
[4.0] Request: Master/details pattern in Frontend UI

### ISSUE THREAD

**Issue by SirioAstarot** [joomla/joomla-cms#21212]
It would be a good idea to implement in the user interface, the Master/details pattern through Webix UI Library, in this way you can see a website similar to a Flash application, with the most modern technologies.

A way to browse websites without reloading the page as in the example.

http://cloudsovercuba.com

Thank you.

**Comment by ghost** [comment]
Changed Title as Issue is about 4.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21212">issues.joomla.org/tracker/joomla-cms/21212</a>.</sub>

**Comment by PhilETaylor** [comment]
I don't see why this would be a good idea for Joomla core?

**Comment by ghost** [comment]
can a experienced Dev. please answer as this issue has Status "New" since more than a Week?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21212">issues.joomla.org/tracker/joomla-cms/21212</a>.</sub>

**Comment by ahotzler** [comment]
http://cloudsovercuba.com -> a blank black site without content (latest Google Chrome)

**Comment by brianteeman** [comment]
This will not be implemented in core

**Comment by dgrammatiko** [comment]
This website that you like so much is not that great:
Almost 6 seconds to deliver something to the client. This is not how you should do it!
<img width="1679" alt="screenshot 2018-07-30 at 12 00 04" src="https://user-images.githubusercontent.com/3889375/43391163-3bbcb6a6-93f0-11e8-8cc5-6b7a87f107db.png">

**Comment by ghost** [comment]
thanks Guys for comment the Issue.

**Comment by SirioAstarot** [comment]
Thank you all for the interest, but why is closed?
This in Webdev is possible through Angular, Webix UI or similar JS, but you would have to add the support to this Javascript Framework.

An explain is [Here](https://blog.webix.com/master-details-pattern-with-webix-ui).

An greatest examples is [Here](https://www.awwwards.com/websites/angularjs).

This request would be the most credible approach to a Flash Website.

**Comment by brianteeman** [comment]
This is just one reason of many
https://webix.com/licenses/

**Comment by SirioAstarot** [comment]
@brianteeman Do not come with excuses. Angular JS also as Ember.js, Meteor.js, ExtJS and React is free licence/open source, the idea is for make [SPA Frameworks](https://en.wikipedia.org/wiki/Single-page_application).

**Comment by brianteeman** [comment]
are you going to do the work?

**Comment by dgrammatiko** [comment]
@SkylarAstarot Joomla will never lock into a framework/library again. 

> Angular JS also as Ember.js, Meteor.js, ExtJS and React is free licence/open source, the idea is for make SPA Frameworks.

Joomla 4 already **ships** an SPA: it's the media manager based on Vuejs, check: https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_media/package.json

My question will be: why do you need Joomla to pull in dependencies you might require for your project?
Just use whatever you're more familiar with, we don't want to dictate react, vue, angular, ember, mojo, meteor, extjs, preact, svelte, stencil, polymer, hyperHTML, litHTML (you do realise there are way too many libs/frameworks out there to either support them all or pick one randomly).
My 2c

**Comment by SirioAstarot** [comment]
@brianteeman search Open Source in you Licence Page Webix and download, this is GPL.
https://webix.com/download/#webix-pro-vs-standard
