### ISSUE TITLE
[4.0] Undefined index: parent_id in ItemModel.php

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#21225]
In php log: Undefined index: parent_id in /administrator/components/com_menus/Model/ItemModel.php on line 1401

### Steps to reproduce the issue
Edit a menu item. Change its menu.
![menu_parentid](https://user-images.githubusercontent.com/869724/43065997-c9345aee-8e63-11e8-8163-9ee7d2f3d75d.gif)

1. The Parent Item is not automatically populated by Menu Item Root although the menu item is saved such.
2. Also: the Ordering still displays the items belonging to the former changed menu.

This does not happen in 3.x

**Comment by infograf768** [comment]
Maybe due to
<img width="1476" alt="screen shot 2018-07-23 at 10 52 10" src="https://user-images.githubusercontent.com/869724/43067055-8e31d8d8-8e66-11e8-97b8-bd1c1609fb7c.png">

**Comment by infograf768** [comment]
When debug is on
<img width="926" alt="screen shot 2018-07-23 at 10 56 38" src="https://user-images.githubusercontent.com/869724/43067257-2311adca-8e67-11e8-93af-7b98a5a242a9.png">

@dgrammatiko

**Comment by dgrammatiko** [comment]
Well, the script expects that the ajax will return a valid json but due to php error we get html and there is no conditional to handle this case. But even if such a fallback existed the page is still kinda unusable I guess without that input value (is that field mandatory?)

**Comment by infograf768** [comment]
If I set the field as required, I get the same error. In fact worse as we are in a loop and it's impossible to save the menu item.

**Comment by roland-d** [comment]
@infograf768 
> Also: the Ordering still displays the items belonging to the former changed menu.

For me this works like this in J3 as well. The ordering is never updated when I change the menu.

<img width="264" alt="image" src="https://user-images.githubusercontent.com/359377/43516732-bcffca9a-9586-11e8-8f51-a691ab7380f6.png">

<img width="251" alt="image" src="https://user-images.githubusercontent.com/359377/43516739-c496f59e-9586-11e8-92c1-4e0f05b941e5.png">

For the other issue we are going to post a PR.

**Comment by ghost** [comment]
closed as having Pull Request #21348
