### ISSUE TITLE
[4.0] Joomla Update: Trying to get property of non-object

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21223]
### Steps to reproduce the issue
On a clean Installation:
![screen shot 2018-07-23 at 07 42 42](https://user-images.githubusercontent.com/8235763/43059369-642809c8-8e4c-11e8-9771-4c9d6a9247b6.jpg)

![screen shot 2018-07-23 at 07 46 35](https://user-images.githubusercontent.com/8235763/43059429-9f018fba-8e4c-11e8-803b-a1f64576b0d7.jpg)

### System information
~~Nightly Build 4.0.0-alpha4-dev~~
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by brianteeman** [comment]
@franz-wohlkoenig can you still replicate this?

**Comment by ghost** [comment]
Yes, Message about `UpdateModel.php online 1315` is still displayed.
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by laoneo** [comment]
Can you provide some testing instructions?

**Comment by ghost** [comment]
Open `/administrator/index.php?option=com_joomlaupdate` and the Notice is shown.

**Comment by laoneo** [comment]
I did that and no error shows up.

**Comment by ghost** [comment]
Maybe a CloudAccess.issue as  get this after clean multiple clean Install too.

**Comment by ghost** [comment]
Since todays Nightly got Notice twice:

![screen shot 2018-08-11 at 14 22 27](https://user-images.githubusercontent.com/8235763/43991667-47f8b93e-9d72-11e8-9d63-a095ee7f451d.jpg)

**Comment by ghost** [comment]
clsoing as probably a Provider -Issue.
