### ISSUE TITLE
[4.0] [a11y] Custom Elements

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21226]
**_I am creating this as a new issue instead of it being on each of the open pr for custom elements as it effects  them all._**

When testing the custom elements there are several accessibility issues identified

1. Clicking on a label should give focus to the field
2. The label for the field should be announced but it is not

Looking at the following video from google and the associated examples it is clear to see that there are quite a lot of changes that need to be made to **all** the custom elements that are being used in j4 to make sure they are accessible and standards compliant. **_(This includes the custom elements already merged and all future elements)_**

Unfortunately as this is all js I can't help with writing fixes I can just point out the issue and stress the **severity** of it.

From my understanding of this it is not correct to just have the field in the custom element. The label must be in the custom element as well

### Short Video - watch first
https://www.youtube.com/watch?v=7a6bLXw2lqQ

### Documentation and examples
https://developers.google.com/web/fundamentals/web-components/examples/

**Comment by dgrammatiko** [comment]
The video is irrelevant as none of our custom elements is hiding the contents into the shadow DOM.

**Comment by brianteeman** [comment]
so it may be irrelevant but it oesn't get around the fact that we do have the problems described

**Comment by brianteeman** [comment]
Can we please just use already existing custom elements that work instead of trying and failing to write our own.

**Comment by dgrammatiko** [comment]
@brianteeman you have any suggestions?
The only requirement we have is to not have any dependencies

**Comment by brianteeman** [comment]
why not? there are plenty of dependencies already in joomla

**Comment by mbabker** [comment]
He basically means "no hard jQuery or UI framework (Bootstrap) dependencies".
