### ISSUE TITLE
[4.0] Cleanup various Node/NPM iterations

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#21221]
There are remnants of the various ways Node/NPM based tooling has been implemented into the repo (`yarn.lock` in `.gitignore`, that `/dev/assets` directory that's unused (which really should be in the `build` directory anyway), etc.).  Cleanup the legacy stuff please.

**Comment by wilsonge** [comment]
Removed yarn. @dgrammatiko can you confirm that the `dev/assets` directory is now no longer used

**Comment by dgrammatiko** [comment]
yup, kill it

**Comment by wilsonge** [comment]
Removed with https://github.com/joomla/joomla-cms/commit/43f313c99210d6087d049acd8710a3d29ba7c5ee
