### ISSUE TITLE
[4.0] Gemfile.lock committed to repo?

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#21220]
I have a `Gemfile.lock` file in my local checkout that's always in `git status` trying to be added to the repo.  We don't actively exclude it in `.gitignore` but there isn't a lock file checked in.  Can we commit the appropriate lock file to the repo?

**Comment by dgrammatiko** [comment]
I don't see a lint command for the scss files anymore, so not sure if this was removed on purpose or...

@C-Lodder any idea here?

**Comment by wilsonge** [comment]
Added the Gemlock. As this is ruby I don't think there is an npm command that can be run for this?

**Comment by C-Lodder** [comment]
I dont believe my gemfile.lock has ever been generated but yes, commit the file if you have it

**Comment by brianteeman** [comment]
Closed as @wilsonge did it but fforgot to close
