### ISSUE TITLE
RFC sort out the invalid token problem when your session expires.

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#21237]
### Steps to reproduce the issue
Wait a while until your session expires and then try to login or logout.  I think browsing is ok just logging in and logging out that causes a problem but I could be wrong.

### Expected result
Logs me out and I have to login again.  Shows a reason why in the system messages part of the page.

### Actual result
gives a white screen and tells me my session has expired.  Even if I'm logging in.  Then if I remove index.php from the URL I can continue my work as usual.  To explain this to a customer is quite a technical thing, especially on a mobile.  And it makes the software look pretty bad.

**Comment by ghost** [comment]
@uglyeoin i guess you mean Build "3.8.10" instead "3.7.10".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21237">issues.joomla.org/tracker/joomla-cms/21237</a>.</sub>

**Comment by uglyeoin** [comment]
@franz-wohlkoenig yes I do.  Although it's been a long standing problem.  Interesting the front end handles it slightly differently.  It gives you an error but logs you in anyway.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21237">issues.joomla.org/tracker/joomla-cms/21237</a>.</sub>

**Comment by ghost** [comment]
@uglyeoin thanks, changed Build at Issue Tracker.

**Comment by brianteeman** [comment]
Should be resolved by #12801

**Comment by uglyeoin** [comment]
Thanks @brianteeman please close
