### ISSUE TITLE
[4.0] Fatal error: Cannot use Joomla\CMS\Language\Multilanguage as Multilanguage

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21238]
### Steps to reproduce the issue
Open in Backend an Article, get:
` Fatal error: Cannot use Joomla\CMS\Language\Multilanguage as Multilanguage because the name is already in use in /administrator/components/com_content/Helper/PreviewHelper.php on line 18`

Edit: Same Error-Message at "Multilingual Associations: Edit Associations (Articles > Articles)"
### System information
- Nightly Build 4.0.0-alpha4-dev
- Multilingual Sample Data
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by Quy** [comment]
This is fixed in #21224. Be sure to download the latest version.

**Comment by ghost** [comment]
@Quy thanks for Info, installed Today Morning new via Cloud Access Nightly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21238">issues.joomla.org/tracker/joomla-cms/21238</a>.</sub>

**Comment by ghost** [comment]
Reopened as got same Message `/administrator/components/com_content/Helper/PreviewHelper.php on line 18` again as saving a new Article.

### System information
- Nightly Build 4.0.0-alpha4-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by laoneo** [comment]
Are you sure, that you are up to date? Because line 18 is not the starting block of the comment in the preview helper class.

**Comment by infograf768** [comment]
I think that Cloud Access Nightly is not containing the patch.

**Comment by ghost** [comment]
@laoneo i install every Day Nightly new.

**Comment by wojsmol** [comment]
@franz-wohlkoenig You're installing Nightly Builds trough ccp or manually?

**Comment by brianteeman** [comment]
It is quite possible that there was an issue at CA and they didn't update the nightly

**Comment by ghost** [comment]
@wojsmol Nightly Builds through CCP. But as Brian wrote there were Issues in the last Days till Today (Ticket is send).
