### ISSUE TITLE
[4.0] Bootstrap 4 dropped btn-xs buttons.

### ISSUE THREAD

**Issue by obsidev** [joomla/joomla-cms#21244]
### What needs to be fixed

CF : https://getbootstrap.com/docs/4.0/migration/#buttons
> Dropped the .btn-xs class entirely as .btn-sm is proportionally much smaller than v3’s.

### Why this should be fixed

The PR #15658 already migrated buttons from BS2 to BS4 ; but since then, there was some modifications in Bootstrap (it was an alpha).

### How would you fix it

Looks like the `btn-xs` should be migrated into `btn-sm`

### Side Effects expected

These btn-xs buttons are displayed as regular big buttons.
For example, there are the " grid.order " buttons.

**Comment by C-Lodder** [comment]
Already done for Casseopiea just FYI: https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/cassiopeia/scss/vendor/bootstrap/_buttons.scss#L3

**Comment by ghost** [comment]
@obsidev thanks for report Issue. If Comment by @C-Lodder solves it please close Issue.

**Comment by obsidev** [comment]
The issue can also be seen in the backend, so in "atum" template.
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/scss/vendor/bootstrap/_buttons.scss

Nevertheless, I'm not sure that it would be the best to add CSS rules in template(s) for that since it is something which has been removed in BS4. It would mean that every templates would have to add these rules and couldn't use official BS4 just like that.

**Comment by C-Lodder** [comment]
It can simply be done at CMS level rather than template level. In here for example: https://github.com/joomla/joomla-cms/tree/4.0-dev/media/system/scss

**Comment by puneeth-chanda** [comment]
can I do it for atum template??

**Comment by Bakual** [comment]
Sure, go for it.

**Comment by ghost** [comment]
@puneeth2001 is there a Pull Request coming?

**Comment by puneeth-chanda** [comment]
Not anytime soon, I am planning to work on it after a couple of days.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/24457

**Comment by ghost** [comment]
closed as having Pull Request #24457

**Comment by Quy** [comment]
Per wilconge:
> Remove the class usage<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21244">issues.joomla.org/tracker/joomla-cms/21244</a>.</sub>

**Comment by Quy** [comment]
Please test PR #24979<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21244">issues.joomla.org/tracker/joomla-cms/21244</a>.</sub>
