### ISSUE TITLE
[4.0] com_config model validation issue

### ISSUE THREAD

**Issue by obsidev** [joomla/joomla-cms#21249]
### Steps to reproduce the issue

Edit the Global configuration and provide an incorrect value for "session lifetime" : 19999
(it is possible to bypass the maximum value of the input field, which is 16383)

### Expected result

The configuration is not saved and the user get a error message with the explanation of the issue.

### Actual result

Configuration not saved but an exception is thrown "no database selected".

### System information (as much as possible)

Joomla 4 Alpha 4

### Additional comments

The "no database selected" is due to the call of $model->save while the validation returns a "false".
There is no "return;" after the $this->setRedirect
CF : https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_config/Controller/ApplicationController.php#L122

Even with the return, the error messages are not enqueued by the model and thus you don't get the validation error message.

**Comment by ghost** [comment]
Issue confirmed.

**Comment by ghost** [comment]
closed as having Pull Request #21384
