### ISSUE TITLE
[4.0] Add SCSS linter or disable hound

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#21256]
We need to either re enable the SCSS linter when compiling or disable hound. Fixing SCSS lint errors after pushing to github via hound is a recipe for insanity.

**Comment by C-Lodder** [comment]
@ciar4n You can lint the SCSS locally if you want to. Hound was added for the remainder of the contributors who may not want to have Ruby installed or even know how to lint locally.

**Comment by ciar4n** [comment]
The linter in the compile script was quite handy but you make a fair point.  Gonna close this.
