### ISSUE TITLE
Adding association to an item doe not add the association to the already associated items

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#21250]
### Steps to reproduce the issue
Create multilingual site with 3 languages.

Create for example 1 article (or anything else) in 2 of the Content Languages and associate them.

Then create another article tagged to the 3rd Content Language. Save (NOT Save and Close). 

Switch to the Associations tab and  Select Association for **only one** of the Content Languages.

Example with contacts:

![assoc_3](https://user-images.githubusercontent.com/869724/43182720-cfbf771a-8fe2-11e8-9f24-d76f3ab6b37b.gif)

### Expected result
The Article should be associated to the already associated articles.

### Actual result
It is not and the result is that the formerly associated articles are not associated anymore without any Alert.

**Comment by infograf768** [comment]
Note: the problem does not exist when using the multilingual associations component to create or associate an item to another which already has associations for other languages.

**Comment by infograf768** [comment]
This may be related to this old PR by @andrepereiradasilva https://github.com/joomla/joomla-cms/pull/12344 which implemented the associations-edit.js

@dgrammatiko 
Can you look at this?

**Comment by infograf768** [comment]
Note2: the problem is not recent. It also existed for menu items associations in 2.5

**Comment by ghost** [comment]
can't test Issue because of #21238

**Comment by infograf768** [comment]
@franz-wohlkoenig 
please use https://github.com/joomla/joomla-cms/archive/4.0-dev.zip

**Comment by ghost** [comment]
i'm on cloudaccess (nightly) so i can't.

**Comment by infograf768** [comment]
Imho we just need an Alert in case there is already associated items for the item added in the association field.

**Comment by Bakual** [comment]
Personally speaking, this is expected behavior. Since I tell in the item A to only associate it with the specified other item B and the remaining languages are left empty. I don't expect it to magically fill up with the item C and D originally associated to that other item B.

If it would not behave like this, how would you ever take off an item from an association group? It would always automatically fill up again.

**Comment by brianteeman** [comment]
I do not agree with your assessment of expected behaviour and as Thomas rightly points out it could never work either. And as you point out it has been this way since 2.5 so I guess no one else sees it as expected behaviour or they would have said something by now.

**Comment by infograf768** [comment]
I have received many surprised comments by French users about that (and some very recently) as it is damned easy to kill existing associations by forgetting an item is already associated.
The fact that it is working such since 2.5 does not mean it is good. We happily corrected a lot of stuff since 2.5 and this is NOT an argument. 

As I suggested, we may need a trick to at least inform the user he may kill existing associations before save, or a specific Ajax call through a button that would automatically fill all the fields with the existing associations if desired. The second one is out of my abilities.

**Comment by brianteeman** [comment]
A warning should only be displayed when there are existing associations that will be removed. A warning should not be displayed on the possibility that an association may be removed.

**Comment by infograf768** [comment]
Closing as we have an Ajax solution https://github.com/joomla/joomla-cms/pull/21321

**Comment by KashifzGit** [comment]
Hi,
I have a strange issue in Joomla 3.9.18, the language switch is working fine till the menu items, but articles are not being translated, the articles are perfectly associated. I am wondering what can cause this issue? any help is appreciated.
thanks

**Comment by brianteeman** [comment]
@kahisfz Please use the forum for support https://forum.joomla.org and please provide more information when you post on the forum
