### ISSUE TITLE
Joomla 4 media menager error

### ISSUE THREAD

**Issue by stankurd** [joomla/joomla-cms#21251]
### Steps to reproduce the issue
An error has occurred.
 Invalid controller class: display

**Comment by brianteeman** [comment]
There was a reason that we asked you those questions - please complete them

**Comment by stankurd** [comment]
when I try open media manager from control panel I get this error

**Comment by brianteeman** [comment]
### System information (as much as possible)

**Comment by stankurd** [comment]
Setting | Value
-- | --
 
Windows NT OLA-TOSH 6.1 build 7601 (Windows 7 Home Premium Edition Service Pack 1) AMD64
mysql
5.7.9
utf8_general_ci
utf8_general_ci
7.1.9
Apache/2.4.17 (Win64) PHP/7.1.9
apache2handler
Joomla! 4.0.0-alpha5-dev Development [ Amani ] 22-July-2018 22:58 GMT
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

**Comment by laoneo** [comment]
Try to delete the psr4 file in the libraries folder. Does it help?

**Comment by stankurd** [comment]
OK now it works
