### ISSUE TITLE
Toggle Show/Hide Module Title from within the list view

### ISSUE THREAD

**Issue by goslingcools** [joomla/joomla-cms#21252]
Can we have an toggle button in the list view of modules that toggles show/hide module title?

**Comment by brianteeman** [comment]
For what purpose - please explain more

**Comment by goslingcools** [comment]
To not always first have to go into each module to show/hide its title and save  & close it.
Maybe I'm just lazy :-)

**Comment by brianteeman** [comment]
That is something that would be very unique to a site to never want to show any module titles.

**Comment by goslingcools** [comment]
No I meant toggling each module separate, just like you can publish/unpublish each module (without having to open it)

**Comment by brianteeman** [comment]
I think you are just too lazy ;)

**Comment by brianteeman** [comment]
As you always have to go into a module to set it up then that is the best time to change the title display. It really is a rare occurrence that you would need to change this at a later date and as such I am going to close this.
