### ISSUE TITLE
To set attributes for  tag using addScript or addScriptDeclaration

### ISSUE THREAD

**Issue by KianWilliam** [joomla/joomla-cms#21253]
### Describe the solution you'd like
$document->addScript(file.js, 'text/x-template', 'modal-template')
result could  be forexample:
<script type="text/x-template" id="modal-template"></script>

**Comment by dgrammatiko** [comment]
Please **ALWAYS** use the JHtml! It's the prefered API for the static assets and already supports what you need here

**Comment by mbabker** [comment]
Use the `$attribs` param of `HTMLHelper::script()` or `Document::addScript()` to add attributes such as these.  This feature is not supported on `addScriptDeclaration` and a pull request adding it would be welcome.

**Comment by KianWilliam** [comment]
Document::addScript( ) does not have the $attribs param, it has $url, $type
, $defer and $async
Kian William

**Comment by mbabker** [comment]
Then you are on a massively outdated release as the signature was changed at 3.7.0 to have the `$attribs` param.

**Comment by KianWilliam** [comment]
Actually before sending this request I mentioned it in Joomla Forum :
https://forum.joomla.org/viewtopic.php?f=706&t=963885
to be sure. Thanks for the information
Kian William

**Comment by Quy** [comment]
@KianWilliam Please close this issue if solved. Thanks.

**Comment by KianWilliam** [comment]
Also addScriptDeclaration does not have $attribs param, does it? 
Kian William
