### ISSUE TITLE
Joomla Repeatable Field doesn't save changes from editor

### ISSUE THREAD

**Issue by TheWhykiki** [joomla/joomla-cms#21259]
### Steps to reproduce the issue

Built a module and use the Joomla Repeatable Field and use this with an editor field type.

### Expected result

Contents could be created, edited, changed and saved.

### Actual result

When using the editor field type with an Editor like Tiny or JCE the contents aren't saved. If I disable any editor and use "none" sidewide, my contents could be saved.

But here the problem now is, that I cannot use any HTML-Tags....
After saving the Repeatable-Field my HTML-Tags (like` <p></p>)` are saved....but when I tick the modules' Save-Button to save my module at all, the HTML-Tags are stripped.
Even with Raw-Filtering.

### System information (as much as possible)

Joomla 3.8.10
PHP Version 7.2.3

**Comment by ReLater** [comment]
Just as a by-the-way-recommendation: Use a field of type "subform" instead of "repeatable". Field repeatable will be removed from Joomla-4 core. Repeatable has several "problems" that makes it unhandy.

**Comment by AndySDH** [comment]
> Just as a by-the-way-recommendation: Use a field of type "subform" instead of "repeatable". Field repeatable will be removed from Joomla-4 core. Repeatable has several "problems" that makes it unhandy.

What does that mean? Are you guys seriously adding a new feature in 3.9 to then remove it in 4? If it's broken just don't add it at all, makes no sense.

**Comment by mbabker** [comment]
No, `JFormFieldRepeatable` is deprecated in favor of `JFormFieldSubform`.  Unfortunately "repeatable" seems to get used in a lot of contexts making that a rather confusing deprecation.

**Comment by AndySDH** [comment]
Oooh ok, just a name change. Cool.

**Comment by ghost** [comment]
can this Issue be closed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21259">issues.joomla.org/tracker/joomla-cms/21259</a>.</sub>

**Comment by brianteeman** [comment]
> What does that mean? Are you guys seriously adding a new feature in 3.9 to then remove it in 4? If it's broken just don't add it at all, makes no sense.

I think you got a little confused here. Repeatable was added in 3.2 and Subform was added in 3.6 and subform was marked as deprecated at the time. 

Closing as the solution is to use subform

**Comment by AndySDH** [comment]
Oh yeah, I guess I got confused with this: https://github.com/joomla/joomla-cms/pull/20243
