### ISSUE TITLE
Class 'ModulesHelper' not found In Joomla 4

### ISSUE THREAD

**Issue by erakashpatel** [joomla/joomla-cms#21265]
When i open any modules in module manager in administrator then its gives below messages.
**Class 'ModulesHelper' not found :(**

Can any one is help me regarding it. its need to fixed it i search and investigation regarding it but i cant found it

**Comment by infograf768** [comment]
Which 4.0 version are you using precisely? Have you tried https://github.com/joomla/joomla-cms/archive/4.0-dev.zip

**Comment by erakashpatel** [comment]
Thanks for the reply 
Found the solution HERE . https://github.com/joomla/joomla-cms/commit/a7a312beba24ec76d1c035f257375c764f73c5fc

Thanks @infograf768

**Comment by ghost** [comment]
Closed as fixed in Code Base.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21265">issues.joomla.org/tracker/joomla-cms/21265</a>.</sub>
