### ISSUE TITLE
Namespace questions

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21267]
I am continuing the work to namespace the librafries/src folder and I have a few questions

1. $classname = 'Joomla\\CMS\\Date\\Date';
stays as it is or changes to $classname = Date and add a use statement at the top of the file

2. \JLoader::import('joomla.filesystem.stream');
stays as it is or removed and add a use statement at the top of the file

**Comment by roland-d** [comment]
For me it works like this:

1. changes to $classname = Date and add a use statement at the top of the file
2. I am currently not aware this can be done any different.

**Comment by brianteeman** [comment]
thanks

**Comment by wilsonge** [comment]
Wrong on both :P 

1. It's the string of the class not a class instance so you need the use statement and `$classname = Date::class` (that just allows easier future refactoring in IDE's)
2. JLoader imports where special cases where we named classes in weird ways that didn't conform to Joomla's built in autoloader. So yes you can remove it and replace it with a `use` statement with the namespaced classes as it will work just fine with the composer autoloader

**Comment by brianteeman** [comment]
> JLoader imports where special cases where we named classes in weird ways that didn't conform to Joomla's built in autoloader. So yes you can remove it and replace it with a use statement as it will work just fine with the composer autoloader

Isnt that where we can do
use joomla\cms\blah\blah as ginger

??

**Comment by wilsonge** [comment]
you don't need the as even :)

**Comment by brianteeman** [comment]
thanks
