### ISSUE TITLE
Tags not displayed on Blog view when Show Publish Date is set to HIDDEN

### ISSUE THREAD

**Issue by helvecio** [joomla/joomla-cms#21273]
### Steps to reproduce the issue
1. Login to the **Administrator**, create a category;
2. Go to the **Menus Manager** and create a new menu item with the type **Category Blog**;
3. Associate this menu item to the category created in step 1; 
4. Create some articles and add tags to them;
5. Add these articles to the category created in step 1; 
6. Go to the front-end to see the page created. 
7. Now go to the **Articles** global settings; 
8. Change **Show Published Date** to **Hide**;
9. In **Articles > Show Tags** make sure it is set to **Show**
### Expected result
- **Published Date** is _hidden_, but **Tags** are _displayed_
### Actual result
- Both **Published Date** and **Tags** are _**not** displayed_
### System information (as much as possible)

- PHP Built On | Linux 
- Database Type | mysql
- Database Version | 5.6.39
- Database Collation | latin1_swedish_ci
- Database Connection Collation | utf8mb4_general_ci
- PHP Version | 5.6.36
- Web Server | Apache
- WebServer to PHP Interface | cgi-fcgi
- Joomla! Version | Joomla! 3.8.10 Stable [ Amani ] 26-June-2018 15:45 GMT
- Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
- User Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36

**Comment by ghost** [comment]
Can't confirm, works as expected. Can remember but don't find an Issue about this Behaviour.
### System information
- 3.8.11-dev
- Template: Protostar
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by mbabker** [comment]
Check for a layout override and make sure your tags display isn't nested inside a check to show the publish date.

**Comment by SharkyKZ** [comment]
Issue confirmed. Other options (modify date, create date, hits, category, parent category, author and associations) also need to be set to hidden.

**Comment by SharkyKZ** [comment]
Test PR #21275 please.

**Comment by ghost** [comment]
closed as having Pull Request #21275

**Comment by helvecio** [comment]
I fixed this issue with the following solution.

In **blog_item.php** on line 37 one finds the following code:

![01](https://user-images.githubusercontent.com/999279/43372883-145eaee4-937c-11e8-8269-08948c317dbc.png)

Moved the codes within lines 40 through 42:

![02](https://user-images.githubusercontent.com/999279/43372888-1c535622-937c-11e8-85d5-d7afcdf39734.png)

As I am not a programmer I am not sure this is the best way to do it, but it sure solved my problem.

**Comment by helvecio** [comment]
And I got the back end settings to work properly.

**Comment by mbabker** [comment]
... which is exactly what the pull request mentioned is doing, it'd be helpful to test said change so it could be merged to core ...
