### ISSUE TITLE
Issue in load module in custom temaplate

### ISSUE THREAD

**Issue by erakashpatel** [joomla/joomla-cms#21270]
### What needs to be fixed
HERE are the how i face this issue.
When i load my module new position then it will not display in browser. but when i firebug it will display like "
**<jdoc:include type="modules" name="footer" style="xhtml" />**" this.

### Why this should be fixed
Can any help here? is it issue or my template bug ?

I hope for positive reply form @infograf768 

Thanks
akash

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.
