### ISSUE TITLE
[4.0] Refactoring build script and deleted files checks for removed vendor directory

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#21277]
Following #21217 the logic to create patch packages and our existing workflows no longer works for the `libraries/vendor` and `media/vendor` directories to determine which files have been added, modified, or deleted between patch releases or to determine which files have been deleted since a git tag.  This workflow will need to be addressed before a stable release can be created.

**Comment by wilsonge** [comment]
So me and Michael discussed this offline a bit. Probably this is going to have to be a generated list of files (where we run the build tag to remove things like node_modules and build dirs after package generation) and then generate a file.

Options are the store the list of files from each release in the build directory, OR we can store them in some sort of jenkins artifact reference (https://jenkins.io/doc/pipeline/tour/tests-and-artifacts/) in the jenkins job.

Ideally we don't want to make jenkins do a "double/triple" npm build (one for the new release and one for each previous release with zipped upgrade path) as this will add significant time to the release job.

**Comment by wilsonge** [comment]
WIP PR is at https://github.com/joomla/joomla-cms/pull/25559 but fixes would be appreciated to try and prevent the double/triple build problems mentioned

**Comment by rdeutz** [comment]
Closing because we have a PR #25559
