### ISSUE TITLE
[4.0] Add build step detection

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#21278]
Following #21217 there are now "build steps" required to run the CMS straight from the git repo.  There should be some kind of detection in the application bootstrap for these steps to have been completed and give some kind of helpful message if not completed.

**Comment by HLeithner** [comment]
Maybe we need this quick?

https://github.com/joomla/joomla-cms/issues/21280

**Comment by mbabker** [comment]
See #21287
