### ISSUE TITLE
Joomla 4 crash site

### ISSUE THREAD

**Issue by stankurd** [joomla/joomla-cms#21280]
### Steps to reproduce the issue
After last update my test site was crashed can,t login  and display any page I get white blank page
I try install new test site i I have the same only white blank page can't install joomla

**Comment by ghost** [comment]
Please give more Information: "System information (as much as possible)"

**Comment by stankurd** [comment]
Windows NT OLA-TOSH 6.1 build 7601 (Windows 7 Home Premium Edition Service Pack 1) AMD64 |  
-- | --
mysql |  
5.7.9 |  
utf8_general_ci |  
utf8_general_ci |  
7.1.9 |  
Apache/2.4.17 (Win64) PHP/7.1.9 |  
apache2handler |  
Joomla! 4.0.0-alpha5-dev Development [ Amani ] 22-July-2018 22:58 GMT |  
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0 |

**Comment by HLeithner** [comment]
Do you use the latest git version? Can you tell use the commit id?

If so its possible that you have to run composer und npm


See https://github.com/joomla/joomla-cms/issues/21277

**Comment by stankurd** [comment]
folder libraries/vendor is empty maybe this is the problem

**Comment by infograf768** [comment]
It certainly is.

**Comment by TobsBobs** [comment]
What can i do? What script should i run?

**Comment by Fedik** [comment]
need to install dependacies: `composer install` if I right understood (see https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment)

but still an errors:
at admin login: `Class 'Joomla\Module\Login\Administrator\Helper\LoginHelper' not found`
at frontend: `Class 'Joomla\Module\Menu\Site\Helper\MenuHelper' not found`

**Comment by HLeithner** [comment]
Download composer and npm

Run composer install and i think npm Install.

@rdeutz could give the correct commands?

**Comment by TobsBobs** [comment]
Ok i test this.

**Comment by Fedik** [comment]
okay so if you had previously installed Joomla 4-dev repo, you have to reinstall **everything**  from the beginning:
* Update your local Joomla 4-dev repo
* Remove `/libraries/autoload_psr4.php` manually
* Remove `/configuration.php` 
* Follow https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment , basically just need:
  * `composer install`
  * `npm install`
  * `npm run build:css`
  * `npm run build:js`
* Install Joomla again

upd: the frontend error remains ` Class 'Joomla\Module\Menu\Site\Helper\MenuHelper' not found`

**Comment by Bakual** [comment]
I got best results using the commands in the build.php file:
https://github.com/joomla/joomla-cms/blob/e1bcbadc9a5d588738e95599e635db0b366d9a9b/build/build.php#L198-L199

So
- `composer install --no-dev --no-autoloader --ignore-platform-reqs`
- `npm install --unsafe-perm`

I also found it needs at least Node JS version 8. Version 6 doesn't work.
You don't need to run `npm run build` commands. Those are already run by the `npm install` command.
You also don't necessary need to delete the configuration.php file. Onyl when you want to do a fresh installation.

**Comment by mbabker** [comment]
> I also found it needs at least Node JS version 8. Version 6 doesn't work.

The required Node/NPM versions are also specified in the `package.json` file after https://github.com/joomla/joomla-cms/pull/21219 so it's not like this is buried anywhere either (basically it's NPM 5.6 and the oldest Node LTS, 8.9.4, which comes bundled with that, anything earlier has quirks with the `package-lock.json` file).

**Comment by ggppdk** [comment]
Tried with fresh git clone

`composer install`
runs fine

but with 
`npm install`

some packages fail:
jquery-minicolors
LeaVerou/awesomplete
webcomponents/webcomponentsjs/2.0.3

npm http 404 http://registry.npmjs.org/claviska/jquery-minicolors/2.2.6
npm ERR! Error: No dist in undefined package
npm ERR!     at next (C:\program files (x86)\nodejs\node_modules\npm\lib\cache.js:746:26)
npm ERR!     at C:\program files (x86)\nodejs\node_modules\npm\lib\cache.js:739:5
npm ERR!     at saved (C:\program files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:142:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\program files (x86)\\nodejs\\node.exe" "C:\\program files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\xampp\htdocs\devel\joomla-cms4
npm ERR! node -v v0.10.13
npm ERR! npm -v 1.3.2

npm http 404 http://registry.npmjs.org/webcomponents/webcomponentsjs/2.0.3

npm ERR! Failed resolving git HEAD (git://github.com/LeaVerou/awesomplete) fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
npm ERR! Failed resolving git HEAD (git://github.com/LeaVerou/awesomplete) Use '--' to separate paths from revisions, like this:
npm ERR! Failed resolving git HEAD (git://github.com/LeaVerou/awesomplete) 'git <command> [<revision>...] -- [<file>...]'
npm ERR! Failed resolving git HEAD (git://github.com/LeaVerou/awesomplete)

**Comment by Bakual** [comment]
@ggppdk Did you try with `npm install --unsafe-perm`? I had some strange errors on Linux without that parameter as well.

**Comment by ggppdk** [comment]
yes tried
`npm install --unsafe-perm`

which did not work,
and i solved it with

```
npm config set strict-ssl false
npm install 
```

or 

```
npm config set registry="http://registry.npmjs.org/"
npm install 
```

then after solving perms issues i get 2 not found errors (404)
npm http 404 http://registry.npmjs.org/claviska/jquery-minicolors/2.2.6
npm http 404 http://registry.npmjs.org/webcomponents/webcomponentsjs/2.0.3

and for 1 more error for 
git://github.com/LeaVerou/awesomplete
`fatal: ambiguous argument 'master': unknown revision or path not in the working tree.`

**Comment by ggppdk** [comment]
OK, i confused V8 JavaScript engine with the version of node JS
which options appeared when using --help

I had old Node.js version
I have updated Node.js to v8.11.3 x64 for windows

and `npm install` completed without errors

Now i can go through installation of J4 without anything missing ...

**Comment by brianteeman** [comment]
Closed
