### ISSUE TITLE
[3.8.10] extensions management (admin) - select type has disappeared

### ISSUE THREAD

**Issue by tramber91** [joomla/joomla-cms#21286]
Hi all
I just remark that in back, template Isis, when i go to
Extensions/Manage/Manage - Search tool
I have no more the dropdown filter "select type" as usual, just an empty cell
http://pix.toile-libre.org/upload/original/1532795439.jpg
Was note the case in old joomla version (Ex 3.8.3)
http://pix.toile-libre.org/upload/original/1532795730.jpg

### System information (as much as possible)
Joomla 3.8.10
ubuntu
chrome

**Comment by ghost** [comment]
Closed as duplicate Report. Duplicate of #20881<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21286">issues.joomla.org/tracker/joomla-cms/21286</a>.</sub>

**Comment by tramber91** [comment]
ok Thanks
i did not found the duplicate report open one month ago
Sorry
will be corrected in next Joomla version i presume

**Comment by ghost** [comment]
https://github.com/joomla/joomla-cms/milestone/37?closed=1

Joomla 3.8.11 is planned for July 31, 2018.

**Comment by ghost** [comment]
don't hesitate to report an Issue so thanks for your Contribute.
