### ISSUE TITLE
[4.0] com_content: Class 'CMSObject' not found

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21299]
### Steps to reproduce the issue
Open an Article or create a new one got:
![screen shot 2018-07-30 at 09 05 33](https://user-images.githubusercontent.com/8235763/43382314-c1eb05c0-93d7-11e8-8504-f20032f560e0.jpg)
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by brianteeman** [comment]
Please enable debug mode and then post the resultant stack trace

**Comment by ghost** [comment]
![screen shot 2018-07-30 at 09 17 57](https://user-images.githubusercontent.com/8235763/43382879-860ceaa8-93d9-11e8-9982-cf00b269bb22.jpg)

Call stack
1 | () | JROOT/libraries/vendor/joomla/utilities/src/ArrayHelper.php:72
2 | Joomla\Utilities\ArrayHelper::toObject() | JROOT/libraries/src/MVC/Model/AdminModel.php:930
3 | Joomla\CMS\MVC\Model\AdminModel->getItem() | JROOT/administrator/components/com_content/Model/ArticleModel.php:394
4 | Joomla\Component\Content\Administrator\Model\ArticleModel->getItem() | JROOT/administrator/components/com_content/Model/ArticleModel.php:547
5 | Joomla\Component\Content\Administrator\Model\ArticleModel->loadFormData() | JROOT/libraries/src/MVC/Model/FormModel.php:272
6 | Joomla\CMS\MVC\Model\FormModel->loadForm() | JROOT/administrator/components/com_content/Model/ArticleModel.php:455
7 | Joomla\Component\Content\Administrator\Model\ArticleModel->getForm() | JROOT/libraries/src/MVC/View/AbstractView.php:146
8 | Joomla\CMS\MVC\View\AbstractView->get() | JROOT/administrator/components/com_content/View/Article/HtmlView.php:81
9 | Joomla\Component\Content\Administrator\View\Article\HtmlView->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:679
10 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_content/Controller/DisplayController.php:59
11 | Joomla\Component\Content\Administrator\Controller\DisplayController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:717
12 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/Dispatcher.php:162
13 | Joomla\CMS\Dispatcher\Dispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:354
14 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:111
15 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:154
16 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:243
17 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:38
18 | require_once() | JROOT/administrator/index.php:36

**Comment by brianteeman** [comment]
Can you try changing this line https://github.com/joomla/joomla-cms/blob/abb2daca6d3466bcb134b5e61abe013e2c943675/libraries/src/MVC/Model/AdminModel.php#L930

to 
`		$item = ArrayHelper::toObject($properties, 'JObject');`

**Comment by ghost** [comment]
Chance Line as suggested works, Article is created/loaded as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21299">issues.joomla.org/tracker/joomla-cms/21299</a>.</sub>

**Comment by roland-d** [comment]
The `CMSObject` should be changed to `Joomla\CMS\Object\CMSObject`. @brianteeman you want to do the PR or shall I?

**Comment by brianteeman** [comment]
@roland-d can you do it please - not got time this morning

**Comment by laoneo** [comment]
You can also write CMSObject::class.

**Comment by roland-d** [comment]
@laoneo That doesn't work for me. Did you test this?

The PR I created uses the fully qualified name: #21300

I will close this as we have a PR.

**Comment by neoacevedo** [comment]
Is not CMSObject deprecated at 4.0?

**Comment by laoneo** [comment]
It is, but we have so many dependencies that it is basically impossible to do it without a hard BC break.
