### ISSUE TITLE
[4.0] Maybe i'm blind&lazy

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#21292]
### Is your feature request related to a problem? Please describe.
where i can fastly find a link to manage plugins ?

### Describe the solution you'd like

can we add near the module box a plugin box
![screenshot from 2018-07-29 10-59-00](https://user-images.githubusercontent.com/181681/43364996-5e2fad18-9325-11e8-8896-f95f092ec30b.png)

### Additional context
why i shouold click on cpanel to  find a link to manage plugins

![screenshot from 2018-07-29 11-51-04](https://user-images.githubusercontent.com/181681/43365013-c311be4c-9325-11e8-822b-ef7d2f02bf31.png)

**Comment by Fedik** [comment]
you are lazy :smile: 

for me it is fine as it is, 
personally I do not need the plugins on "each day" , maybe once a month

**Comment by alikon** [comment]
yes i'am :smile: unfortunately i'm not alone

**Comment by Fedik** [comment]
I also think it is logical to keep it in "System" section,
because for "Content creators" do not need it at all.

**Comment by ghost** [comment]
> for me it is fine as it is.

+1

**Comment by alikon** [comment]
content plugins on wich category they belongs ?

**Comment by Fedik** [comment]
> content plugins on wich category they belongs ?

to plugins :wink: 
it just a content modifiers, not a content itself, I think

**Comment by alikon** [comment]
quite border  line imho

**Comment by Bakual** [comment]
Imho, plugins should be threated similar as modules. Both are used rarely enough (you set them up once and then rarely change). I would also add a box beside the module one.
At the same time I would expect to find "manage modules" also in the system panel where the extensions, languages and plugins are found. Not under "Content" (which is basically com_content and media manager). Modules are not (only) content, they are often system things (eg a menu or breadcrumb). I would rather move the media manager out of "Content" to an own menu item than add more things unrelated to com_content to that menuitem.

**Comment by brianteeman** [comment]
If only we had the results of all that UX work

**Comment by cyrez** [comment]
IMO, there are components, modules and plugins for content. And others for system tasks.

Maybe a "task" definition could help to manage 2 parts (as it could be logical to manage com_content in the same place as other component managing main content)?
There are frontend component (articles, contacts, tags, images galleries, tickets, forum...), backend component (post-install messages, joomla update, security, backup, seo...)

@Bakual i 💯 agree that com_media could be on its own as used by many extensions of any type.

**Comment by cyrez** [comment]
> If only we had the results of all that UX work

👍 Joomla 4 is a good way to think more clearly organisation of extensions and tasks ;-)
But what is the "UX work" ? Where ?

**Comment by mbabker** [comment]
> Modules are not (only) content, they are often system things (eg a menu or breadcrumb).

But, the end result is that modules are generally producing some kind of frontend content.  Be it consuming data from a component (all the article modules), consuming data from a third party source (social networking modules), or showing some kind of page "attribute" (for lack of better terms, like a breadcrumb or menu).

**Comment by Bakual** [comment]
Yes sure, modules produce output. More often than not that output is showing some links (to related articles, navigation, menuitems, tags, social buttons, ...). If you want to call that "content", then it's appropriate. 😄 
But then, (content) plugins often do such things as well. What is the difference between a plugin which adds social buttons and a module which adds social buttons?

**Comment by brianteeman** [comment]
simple answer - is nothing in that case

but if you look at modules they can be used for so much more. Show me a plugin that is used for placing an image in the page? 

Or look at the joomla.org homepage and tell me that its not content and yet its all modules

**Comment by Fedik** [comment]
also, we have "Custom HTML" module, which often used for content,
but we do not have "Custom HTML" plugin :smile:

**Comment by mbabker** [comment]
> What is the difference between a plugin which adds social buttons and a module which adds social buttons?

In that case, nothing at all.  You have to take it a step higher and look at the extension definitions though.  By design, a module is a service which produces content for the frontend (browser facing content, not to explicitly say "frontend" as in SiteApplication).  By design, a plugin is a system wide hook to perform actions on a request based on varying conditions, whose actions may or may not include processing content (i.e. we use a content plugin which replaces a `{nightlybuilds}` shortcode with the actual packages found in the filesystem on the Developer Network for the nightly builds article).  So a module is always a content publishing item, a plugin is a general use item which may produce content.

**Comment by Bakual** [comment]
Sure, I agree with you all.
I still wouldn't put the module manager under "Content" where mostly com_content lives.
By that definition, you would have to move all frontend components to that "Content" menuitem as well, as those certainly produce more "content" than modules.
Imho the plugin manager is hidden to much now and module manager is in the wrong menuitem.

**Comment by infograf768** [comment]
Evidently, when we will be able again to create custom admin menu items correctly, this debate will look a bit "passé".
But, it is true that the new admin menu hides in a very complex page all these "System" menu items and it takes a long time to figure where is what.
Example:
Under the "Access" title, we find some Global Configuration links where the `#page-filters` or `#page-permissions` are atm useless as they redirect simply to Global Configuration page.
We also find Groups and Levels there, which apparently make sense although I have difficulties to see it separated from "Users". Maybe OK if we keep the sub menus to these in the "Users" menu.

Generally speaking, I would really like to see the "Manage" part separated in multiple parts.
At least a specific one for all concerning Languages (including a redundancy for Install Languages)

Also, I agree with @Bakual concerning Modules and Plugins

**Comment by brianteeman** [comment]
> Under the "Access" title, we find some Global Configuration links where the #page-filters or #page-permissions are atm useless as they redirect simply to Global Configuration page.

Thats because the linking to specific tabs is currently brokeen

**Comment by infograf768** [comment]
Please refrain from useless comments... Read again the word `atm`. I guess it is a usual shortcut in English for "At this moment".

**Comment by brianteeman** [comment]
It wasn't clear that you referred to that bug as there was no point mentioning the problem if you did know - so my comment was not useless at all but informative. 

Please stop the personal attacks

**Comment by ghost** [comment]
I guess the Template is for Newbies. Means Oldies have to learn.

**Comment by schnuti** [comment]
I would move the Articles to Components, where it belongs and delete the Content menu item. Articles are prominent but there are alternatives. For a site other component types might be the main content contributor. Those probably use the Joomla Media and a couple of modules too.
Modules and plug ins are extensions often creating content.
Add as many shortlink buttons to the control panel as you need. e.g. to Articles.

**Comment by wilsonge** [comment]
Right now the idea is this - modules have two primary purposes - rendering secondary component views (e.g. a contact form which goes to a forms/contact component, an event list, a featured shop product) and the obvious stuff like logos, footers etc. - the former is mainly dynamic content (and of course the latter static). Due to the former they can be often edited day to day for things like product of the day, advertising offers etc.

Plugins are largely static content - e.g. the social media icons, modifying content etc. as a result there are largely one off configurations hence they go in system

Of course this is a sweeping generalisation and there are exceptions in both cases - but this is the idea behind this. Unless someone has concrete arguments otherwise rather than just personal opinions I'm closing this as a decision made - whether popular or not with us "oldies"
