### ISSUE TITLE
[4.0] Atum status icons

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21297]
Was it the intention that they would all be grey or is that a css error??
I am repeatedly finding myself having difficulty scanning a list and determining its status with them all grey.

### Expected 
<img width="302" alt="chrome_2018-07-29_17-57-03" src="https://user-images.githubusercontent.com/1296369/43368680-fc664a72-9358-11e8-8123-e1ddd16084eb.png">

### Actual
<img width="323" alt="chrome_2018-07-29_17-57-17" src="https://user-images.githubusercontent.com/1296369/43368681-fc83423a-9358-11e8-89de-18874230fa47.png">

@ciar4n

**Comment by ciar4n** [comment]
Cascading error by the looks of it. I'll create a PR.

**Comment by brianteeman** [comment]
ok - thanks

**Comment by ciar4n** [comment]
PR.. #21312
