### ISSUE TITLE
[J4] Feature Request: Compatibility with Woocommerce

### ISSUE THREAD

**Issue by SirioAstarot** [joomla/joomla-cms#21298]
Joomla is the most versatile, easy to learn and fast CMS market, much better than the competition, but there is a dilemma when implementing my store.

I would like the new J4 Rest API to be compatible with Woocommerce Extension Shop, so many programmers could implement their store with the best option available.

**Comment by mbabker** [comment]
A REST API is platform agnostic.  It is simply HTTP requests passing data in the correct format.  Therefore, you can build anything in Joomla integrating with any WordPress site which makes use of its inbuilt REST API capabilities.  There is nothing to be built into Joomla specific for this case.

**Comment by SkylarAstarot** [comment]
NOT CLOSED FUCK! I HATE BULLSHIT BLOGPRESS, AND HAVE USED SHOP WITH FUCKING JOOMLA!!! NOT CLOSED REQUEST!

**Comment by SkylarAstarot** [comment]
Fuck you no lo cierren!
