### ISSUE TITLE
[3.x] Allow extension to specify additional query parameters in admin menu

### ISSUE THREAD

**Issue by clayfreeman** [joomla/joomla-cms#21307]
### Is your feature request related to a problem? Please describe.

Components are unable to specify additional query parameters when defining primary admin menu items in the manifest file. Submenu items, however, are able to specify additional query parameters.

### Describe the solution you'd like

Patch [this file] to allow additional query parameters as specified in the component manifest, similar to [how it is done for submenu items]. EDIT: Please see the below referenced PR (#21309).

### Additional context

It should be possible to build components without the use of a "generic" controller that defines a default view. Menu items should be able to specify the `task` and `view` query parameters so that there is no ambiguity as to which controller and view class should be used.

[this file]: https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Installer/Adapter/ComponentAdapter.php#L969
[how it is done for submenu items]: https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Installer/Adapter/ComponentAdapter.php#L1044

**Comment by ghost** [comment]
closed as having Pull Request #21309
