### ISSUE TITLE
#__template_styles.params to be LONGTEXT.

### ISSUE THREAD

**Issue by chetanmadaan** [joomla/joomla-cms#21315]
Hello,

Our layout manager for the template has quiet a good amount of JSON that it's (in some rare cases) trimming the JSON because it's too long and unable to fit in the column.

I know modifying the core table isn't an option and we may be forced to create our own table and save everything there.

I am not an expert when it comes to column types for mysql but any reason this can't be longtext? since most of the template providers are transiting to (or will be) page builders or layouts builders (Gantry/YooTheme Pro) and would be helpful to have enough space in the column to save all the JSON generated by the page.

This might also be applicable to the #__modules.params column as well.

Thanks,
Chetan

**Comment by alikon** [comment]
why not use a simply json column as  it should be available from mysql starting from 5.7.x ?

**Comment by chetanmadaan** [comment]
Again, not an expert in mysql columns but that could very well be an option.

**Comment by ghost** [comment]
closed as Issue seems solved; if not, please reopen, thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21315">issues.joomla.org/tracker/joomla-cms/21315</a>.</sub>

**Comment by alikon** [comment]
@franz-wohlkoenig can you link the solution ?

**Comment by ghost** [comment]
i meant [Comment](https://github.com/joomla/joomla-cms/issues/21315#issuecomment-409019647) by @chetanmadaan above.

**Comment by chetanmadaan** [comment]
Hi @franz-wohlkoenig,

I just confirmed that the **json** field type can be a solution, but even that requires the change in the core table level.

Thanks You,

**Comment by ghost** [comment]
thanks @chetanmadaan got it so reopened.

**Comment by chetanmadaan** [comment]
Thank You @franz-wohlkoenig 

Hopefully, someone will pay attention to this sooner or later.

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/issues/19618#issuecomment-414137648
