### ISSUE TITLE
[4.0] Cassiopeia SCSS:  Invalid CSS on Line 17 _css-grid.scss

### ISSUE THREAD

**Issue by JOYScka** [joomla/joomla-cms#21311]
### Steps to reproduce the issue

Made modification to _variables.scss
Save file
Receive Error: Invalid CSS after "...mplate-columns:": expected expression (e.g. 1px, bold), was "[full-start] minmax" on line 17 of scss/blocks/_css-grid.scss

### Expected result

Compiled css

### Actual result

Error

### System information (as much as possible)

MAMP Pro on Mac
PHP 7.1.6
Scout-App Sass compiler
Atom

### Additional comments

**Note -** Removing line 17 entirely or removing the [] around full-start, main-start, main-end, full-end eliminates the Error and the SCSS compiles correctly.
However, not a solution as it breaks the grid. 
Not familiar enough with grid-template-columns: to troubleshoot this. 
Not techy enough to get SCSS set through node and the terminal to see if running the node build --compilecss command would solve this issue. (as noted in a previous thread)

**Comment by wojsmol** [comment]
@ciar4n Please comment

**Comment by ciar4n** [comment]
This should not be reported as invalid as long as you are running a recent version of SASS?

**Comment by ghost** [comment]
@JOYScka Comment please?

**Comment by JOYScka** [comment]
It appears my issue was with the SASS version. Updated and all is well - I should have checked that. Thanks.

**Comment by brianteeman** [comment]
Glad it's resolved
