### ISSUE TITLE
Joomla 4 Class 'CMSObject' not found

### ISSUE THREAD

**Issue by stankurd** [joomla/joomla-cms#21310]
### Steps to reproduce the issue
error code

Call stack
--
# | Function | Location
1 | () | JROOT\libraries\vendor\joomla\utilities\src\ArrayHelper.php:72
2 | Joomla\Utilities\ArrayHelper::toObject() | JROOT\libraries\src\MVC\Model\AdminModel.php:930
3 | Joomla\CMS\MVC\Model\AdminModel->getItem() | JROOT\administrator\components\com_fields\Model\FieldModel.php:334
4 | Joomla\Component\Fields\Administrator\Model\FieldModel->getItem() | JROOT\administrator\components\com_fields\Model\FieldModel.php:885
5 | Joomla\Component\Fields\Administrator\Model\FieldModel->loadFormData() | JROOT\libraries\src\MVC\Model\FormModel.php:272
6 | Joomla\CMS\MVC\Model\FormModel->loadForm() | JROOT\administrator\components\com_fields\Model\FieldModel.php:531
7 | Joomla\Component\Fields\Administrator\Model\FieldModel->getForm() | JROOT\libraries\src\MVC\View\AbstractView.php:146
8 | Joomla\CMS\MVC\View\AbstractView->get() | JROOT\administrator\components\com_fields\View\Field\HtmlView.php:60
9 | Joomla\Component\Fields\Administrator\View\Field\HtmlView->display() | JROOT\libraries\src\MVC\Controller\BaseController.php:679
10 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT\administrator\components\com_fields\Controller\DisplayController.php:61
11 | Joomla\Component\Fields\Administrator\Controller\DisplayController->display() | JROOT\libraries\src\MVC\Controller\BaseController.php:717
12 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\libraries\src\Dispatcher\Dispatcher.php:162
13 | Joomla\CMS\Dispatcher\Dispatcher->dispatch() | JROOT\libraries\src\Dispatcher\LegacyDispatcher.php:72
14 | Joomla\CMS\Dispatcher\LegacyDispatcher->dispatch() | JROOT\libraries\src\Component\ComponentHelper.php:354
15 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:111
16 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:154
17 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:243
18 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\includes\app.php:46
19 | require_once() | JROOT\administrator\index.php:36

**Comment by ghost** [comment]
Closed as duplicate Report #21299<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21310">issues.joomla.org/tracker/joomla-cms/21310</a>.</sub>
