### ISSUE TITLE
[4.0.0-alpha4-dev] "Read more" did not working

### ISSUE THREAD

**Issue by Condorious** [joomla/joomla-cms#21317]
In editor menu CMS Content - Read more do not inserting tag. Nothing happens when I click Read more.

**Comment by ghost** [comment]
Issue confirmed.

Using Browser-Web-Console got:
![screen shot 2018-07-31 at 06 01 19](https://user-images.githubusercontent.com/8235763/43437018-4d9f0bca-9487-11e8-95b4-e0c995ef3167.jpg)

**Comment by wojsmol** [comment]
This is fixed in 4.0-dev - see PR https://github.com/joomla/joomla-cms/pull/21207

**Comment by ghost** [comment]
Closed as stated above.

Thanks for Reminder, @wojsmol.
