### ISSUE TITLE
[4.0] Feature menu selection regression

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21313]
In Joomla 3 you could change the feature menu item by selecting the icon. (In effect it removes the featured status from the current menu item and adds it to the new menu item)

In Joomla 4 you can not change the feature menu item in the same way. It just tries to add the featured status to the new menu item without removing the old one - therefore producing an expected error.

### Joomla 3 Example
![j3mennu](https://user-images.githubusercontent.com/1296369/43415328-37e2f9b8-942d-11e8-8a31-0eae27de4bdf.gif)

### Joomla 4 Example
![j4mennu](https://user-images.githubusercontent.com/1296369/43415338-3bba9172-942d-11e8-9651-66e22edfa662.gif)

**Comment by ghost** [comment]
Can't confirm. Created a new Menu (21313) and change "Home" by Click on Star-Button got:
![screen shot 2018-07-31 at 05 56 18](https://user-images.githubusercontent.com/8235763/43436882-9fbc4298-9486-11e8-80ac-530c99db421c.jpg)
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by brianteeman** [comment]
Closed as I cant reproduce this any more
