### ISSUE TITLE
Content Tags with the same name in multilingual sites

### ISSUE THREAD

**Issue by helvecio** [joomla/joomla-cms#21326]
On a Joomla multilingual website, when I set up categories, I can create one top-level category assigned to each language installed - EN and BR, for example. Under each of them, I can have categories with the same name for each language (e.g. Blog). 

I assumed I could do the same with Tags. 

But, when I create two top-level tags assigned to each language installed and populate them with tags which is the same word on both languages - e.g. tutorial - I noticed that is not possible, as I would do with categories.
### Steps to reproduce the issue
1. In multilingual Joomla installation, go to **Administrator > Components > Tags**
2. Create two tags assigned to each of the languages installed. E.g.: **EN** assigned to **English** and **BR** assigned to **Brazilian Portuguese**.
3. Create a tag named **Tutorial** and assign it to **English**.
4. Select **EN** as its parent tag.
5. Create a new tag also named Tutorial and assign it to **Brazilian Portuguese**.
6. Select **BR** as its parent tag.
### Expected result
Tags with the same name, when assigned to different languages and nested under different parent tags to be created.
### Actual result
The system gives you the following 
**Error - Save failed with the following error: Another Tag has the same alias (remember it may be a trashed item).**
### Additional comments
Allowing tags to work as categories do, users will be able to create tags with the same name and be able to sort articles by language when using tags as well.

**Comment by infograf768** [comment]
Issue confirmed.

**Comment by ghost** [comment]
@helvecio issue still confirmed in Joomla! 3.9.15?

**Comment by brianteeman** [comment]
This is nothing to do with multilingual and is still an issue in j4

Try to create tags as follows and you will get the incorrect message about duplicate alias
Sport
-- Children
-- Adults
Games
-- Children
-- Adults

Please change the label to J4

**Comment by richard67** [comment]
Closing as having a pull request. Please test #38576 . Thanks in advance.

**Comment by simbus82** [comment]
> Please change the label to J4

But this is a J3 issue.

**Comment by richard67** [comment]
> > Please change the label to J4
> 
> But this is a J3 issue.

J3 is in security support pase, i.e. support with bug fixes ended on August 17. Until August next year, only security issues will be fixed in J3.

**Comment by simbus82** [comment]
> > > Please change the label to J4
> > 
> > 
> > But this is a J3 issue.
> 
> J3 is in security support phase, i.e. support with bug fixes ended on August 17. Until August next year, only security issues will be fixed in J3.

"[helvecio](https://github.com/helvecio) opened this issue on 31 Jul 2018"
Bah.

**Comment by Hackwar** [comment]
As there has been several changes in this area and J3 is not supported anymore, I'm closing this one.
