### ISSUE TITLE
[4.0] com_redirect bulk import

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21338]
It is not possible to open the bulk import modal from the toolbar in com_redirect due to a javascript error

```
Uncaught TypeError: Cannot read property 'open' of null
    at HTMLButtonElement.onclick (index.php?option=com_redirect&view=links:279)

```

**Comment by ghost** [comment]
Issue confirmed, got `TypeError: document.getElementById(...) is null ... index.php:1:2`

**Comment by brianteeman** [comment]
Actually it is not a javascript error
The modal is not being generated in the php so the javascript can't find the element to open
