### ISSUE TITLE
Most recent featured articles not displayed anymore - Modules Articles-Latest and Articles-Newsflash

### ISSUE THREAD

**Issue by makermann** [joomla/joomla-cms#21333]
### Steps to reproduce the issue
1. Create a module of type newsflash or recent articles. 
2. Configure module: 
- Select category of articles. 
- Number of articles "5"
- Featured articles: "show"
- Order by "recently added first" or "Publish date".
3. Display module in any position
4. Publish 10 articles
5. Set first article featured

### Expected result
The 5 most recent articles are displayed in chronological order.

### Actual result
5 articles from the category are displayed.
Featured articles are not included in list.
The order of the articles is correct.

### System information (as much as possible)
Joomla 3.8.11, Linux + Apache, php 7.1

### Additional comments
This bug appeared after updating from 3.8.10 to 3.8.11
Please ask for additional info.

**Comment by ghost** [comment]
Can't confirm, test on "Latest Articles"-Module, please have a Look http://wohlkoenig-3.joomla.com/index.php/en/

**Comment by makermann** [comment]
Thanks for the quick response!

I found out: The problem exists only with featured articles. Featured articles are NOT displayed although in both modules the option for them is "show".

Addition: In Newsflash ordering is set to "Published date", direction "descending"
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21333">issues.joomla.org/tracker/joomla-cms/21333</a>.</sub>

**Comment by ghost** [comment]
Issue confirmed on Featured Articles aren't shown in "Latest Articles"-Module.

@makermann can you please update the issue so a Dev. doesn't have to read all of the Thread?

**Comment by makermann** [comment]
Thanks. I updated the description.

**Comment by SharkyKZ** [comment]
It's my fault 😞 . Test PR #21336 please.

**Comment by ghost** [comment]
closed as having Pull Request #21336

**Comment by ghost** [comment]
@makermann please test #21336

**Comment by makermann** [comment]
Fixed. Thanks to everyone!

**Comment by ghost** [comment]
@makermann thanks for Reporting. If you can please test current Stage so we didn't get next Release similar Report ;-)
