### ISSUE TITLE
Front-end editor created date not possible to save

### ISSUE THREAD

**Issue by nickvanballegooijen** [joomla/joomla-cms#21349]
### Steps to reproduce the issue

Add this line
<?php echo $this->form->renderField('created'); ?>
In a override of the front-end edit like
template\html\com_content\form\edit.php
### Expected result
Possible to edit and save the created date of a article in the front-end editor

### Actual result
Date is loaded but not saved

### My fix:
In site\components\com_content\models\article.xml

Add the following lines to the field created in the article.xml
filter="user_utc"
showtime="false"

I have changed the field created:
< field
	name="created"
	type="calendar"
	label="Aanmaakdatum"
	translateformat="true"
	id="created"
	filter="user_utc"
	showtime="false"
/ >

<field
	name="created"
	type="calendar"
	label="Aanmaakdatum"
	translateformat="true"
	id="created"
	filter="user_utc"
	showtime="false"
/>

### System information (as much as possible)
Joomla version 3.8.11

### Additional comments
It is possible to load the created date of a article but if you edit and save Joomla will not save it. This is caused by the filter of Joomla which will clear the value after submitting the changes.

**Comment by SharkyKZ** [comment]
This is intended. Users are not allowed to change certain data in frontend. If you want to change this, you can create a content plugin with `onContentPrepareForm` event and set desired field attributes there.

**Comment by ghost** [comment]
Closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21349">issues.joomla.org/tracker/joomla-cms/21349</a>.</sub>
