### ISSUE TITLE
[4.0 alpha 5] You can't view image repository from creating an article in IE11

### ISSUE THREAD

**Issue by padenict** [joomla/joomla-cms#21342]
### Steps to reproduce the issue
1. Using IE11, from backend administration, create a new article or edit an existing one;
2. Go to "Intro image" or "Full Article Image" and click "Select"

### Expected result
You can't view image repository content. You can upload images, but you can't see it. Under Firefox or Chrome you can view them

**Comment by ghost** [comment]
Didn't get what you mean. Can you please explain, maybe using Screenshots?

**Comment by dgrammatiko** [comment]
It's a known issue: https://github.com/joomla-projects/media-manager-improvement/pull/572

**Comment by ghost** [comment]
thanks @dgrammatiko.

Thanks @padenict for Report, but closing this Issue as its known.
