### ISSUE TITLE
Upgrade to Joomla 3.8.11 Module latest article bug, show wrong article

### ISSUE THREAD

**Issue by Folamour** [joomla/joomla-cms#21347]
### Steps to reproduce the issue

upgrade to 3.8.11

### Expected result

Module lastest article should display last article published from july

### Actual result

Module latest article display article from march 2018

can be check on rigth pane of the site on "dernier articles" https://www.crashdebug.fr

### System information (as much as possible)

PHP exécuté sur | Linux od-2ffe84 3.16.0-0.bpo.5-amd64 #1 SMP Debian 3.16.51-3+deb8u1~bpo70+1 (2018-01-09) x86_64
-- | --
Database Type | mysql
Version de la base de données | 5.6.33-log
Interclassement de la base de données | utf8_general_ci
Collation de la connexion à la base de données | utf8mb4_general_ci
Version de PHP | 7.0.13
Serveur web | Apache
Serveur web pour interface PHP | fpm-fcgi
Version de Joomla | Joomla! 3.8.11 Stable [ Amani ] 31-July-2018 14:00 GMT
Version de la plateforme Joomla! | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Navigateur | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0

### Additional comments

PR 19261 and PR 19284 seem now integrated on 3.8.11 site is blazzing fast without to install beta patch, great job folks ; )

**Comment by Folamour** [comment]
thread open on Joomla.org no fix at this time : 

https://forum.joomla.org/viewtopic.php?f=706&t=964128&p=3534201#p3534065

Thanks a lot i need a fix,

kind regards,

guillaume,

**Comment by ghost** [comment]
Thanks for Report, but closed as duplicate Report #21333 and fix PR #21336.

**Comment by ghost** [comment]
@Folamour can you please report at Forum?

**Comment by Folamour** [comment]
I frantz i understodd i should not ask here, but i have already asked on forum : 

https://forum.joomla.org/viewtopic.php?f=706&t=964128&p=3534201#p3534065

every body seem in vacation an no valuable reply, dev as been a great help to me by the past, and was the only one to can address my issue of 14 k article slow site.

sorry to disturb you,

guillaume,

**Comment by ghost** [comment]
@Folamour its fine to Report an issue. But the issue was reported and fixed earlier so i asked if you can inform in Forum-Thread that People know about the Fix and don't have to report here again.

**Comment by mbabker** [comment]
> every body seem in vacation an no valuable reply

12 hours without a reply doesn't mean that you're being ignored.  Please remember everyone's volunteering their time and nobody has to give immediate responses to every thread.

**Comment by Folamour** [comment]
yes i understood but you know we have visitor on our blog, and they are lost without latest article module, please can you tell me with PR to ask to apply to my service provider and so i can inform other on forum,

is seem to be PR #21336. can you confirm ?

thanks for your time and patience,

guillaume,

**Comment by mbabker** [comment]
Yes it is #21336 as was originally pointed out.

**Comment by Folamour** [comment]
thanks Michael i have asked my provider to apply it, keep you updated and inform on the forum

sorry to have buggy you,

kind regards,

guillaume,

**Comment by ghost** [comment]
@Folamour glad your Problem is solved. Please don't forget to inform others on Forum too.

**Comment by Folamour** [comment]
no prob franz i update the forum in a sec ; )

**Comment by Folamour** [comment]
forum updated
