### ISSUE TITLE
[4.0] Content > Articles Layout and Links Not Functioning Properly

### ISSUE THREAD

**Issue by JOYScka** [joomla/joomla-cms#21345]
### Steps to reproduce the issue
Content (sidebar) > Articles  (secondary nav) when clicked links to users view
Control panel > New Article --- layout page is non functional

### Expected result
Content (sidebar) > Articles  (secondary nav) link to articles
Control panel > New Article working layout page

### Actual result

Content (sidebar) > Articles 
<img width="1540" alt="screenshot 2018-08-01 08 47 34" src="https://user-images.githubusercontent.com/39335006/43523521-a458fff0-956a-11e8-837b-63abb57264c9.png"> 
Links here (and sidebar sticks open)
<img width="1667" alt="screenshot 2018-08-01 08 46 06" src="https://user-images.githubusercontent.com/39335006/43523536-b21ed308-956a-11e8-972e-210bfe35371f.png">
Control panel > New Article 
<img width="1699" alt="screenshot 2018-08-01 08 45 45" src="https://user-images.githubusercontent.com/39335006/43523582-d30b1fa4-956a-11e8-95dd-42b0f18e4518.png">

### System information (as much as possible)

Joomla_4.0.0-alpha5-dev-Development-Full_Package.zip
Wednesday, 01 August 2018
MAMP Mac
PHP 7.1.6
MySQL 5.6.35

**Comment by brianteeman** [comment]
The menu issue is resolved by #21316

**Comment by ghost** [comment]
@JOYScka Thanks for Report, but as Brian wrote its a known issue so closed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21345">issues.joomla.org/tracker/joomla-cms/21345</a>.</sub>

**Comment by JOYScka** [comment]
Ok. But what about the layout issue for articles? is it just me?

**Comment by ghost** [comment]
what Layout Issue you mean?

**Comment by ghost** [comment]
Issue reopened.

**Comment by JOYScka** [comment]
![screencapture-joys45-8888-administrator-index-php-2018-08-01-09_32_32](https://user-images.githubusercontent.com/39335006/43524716-f2d79fb2-956d-11e8-81c5-d45454fa201d.png)

**Comment by ghost** [comment]
Thanks @JOYScka, can't confirm this Issue. Have Today installed latest Nightly Build.

**Comment by JOYScka** [comment]
wow—ok so that screen shot is odd. because I do not see the content box at all on Google Chrome. But that is the way the page load.

**Comment by brianteeman** [comment]
Sounds like it might be a browser cache issue

**Comment by JOYScka** [comment]
Browser cache cleared - still seeing above layout.

**Comment by infograf768** [comment]
I confirm the Tabs issue when editing an article or a category.
I also confirm editor not displayed 
I confirm second levels sub menus broken. (Issue already made: https://github.com/joomla/joomla-cms/issues/21353
I do not confirm the layout of article edit issue

**Comment by ghost** [comment]
>  I also confirm editor not displayed

@infograf768 [Comment](https://github.com/joomla/joomla-cms/pull/21300#issuecomment-408822045) by @dgrammatiko: it's a known issue: [tinymce/tinymce#4502](https://github.com/tinymce/tinymce/issues/4502)

**Comment by infograf768** [comment]
Tab issue solved here by https://github.com/joomla/joomla-cms/pull/21204 (waiting for merge)

**Comment by infograf768** [comment]
TinyMCE Editor: indeed the issue is not present in Safari. Just Firefox here. (mac)

**Comment by infograf768** [comment]
Second level menus solved here
https://github.com/joomla/joomla-cms/pull/21367

Therefore, for me, except for TinyMCE, all issues are covered by PRs.

can be tested without npm

**Comment by ghost** [comment]
closed as stated above (TinyMCE is an Plugin-Issue)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21345">issues.joomla.org/tracker/joomla-cms/21345</a>.</sub>
