### ISSUE TITLE
update 3.8.11 bug in menu module

### ISSUE THREAD

**Issue by dsimonse** [joomla/joomla-cms#21351]
### Steps to reproduce the issue
Had a menu-module working with joomla 3.8.10 but after upgrade the setting for the module stays at "Default" menu type. I'm using accordion and am not able to select any other type of menu except for "Default"

### Expected result
Should be able to change menu type to accordion.

### Actual result
Stays at default and the menu is streched out.
![menu](https://user-images.githubusercontent.com/17233634/43545310-db6efd44-95d5-11e8-958b-c7fe4a933d94.PNG)
link: http://rojteatern.nu/index.php/medlemskalendern

![menu_module](https://user-images.githubusercontent.com/17233634/43545597-9ce1b160-95d6-11e8-8430-77caff0a4225.PNG)

![menu-option](https://user-images.githubusercontent.com/17233634/43546017-d5890684-95d7-11e8-9d0e-e00434cdd517.png)

### System information (as much as possible)
joomla 3.8.11
PHP 5.6.33
YouGrids 2.3.3

**Comment by ghost** [comment]
Thanks for Report. Have you checked if its a Template-Issue?

**Comment by TobsBobs** [comment]
PHP 3.6.33 ?

**Comment by ghost** [comment]
guess Typo 5.6.33

**Comment by dsimonse** [comment]
Hi, 
yes typo, 5.6.33.
I've not checked with template yet, since the issue arised after update of joomla.

**Comment by softforge** [comment]
What template is it? I have tried with the ones I have but cannot reproduce the issue

**Comment by ghost** [comment]
if you check the URL its not a Core-Template.

**Comment by dsimonse** [comment]
The template is Yougrids

**Comment by softforge** [comment]
YouGrids Template for Joomla 1.7 and UP  Aug-08-14 15:47pm  2.0.0

I will try to test tomorrow on a dev site
https://www.youjoomla.com/joomla-templates/yougrids-free-joomla-template-yjsg-powered.html?download-yougrids-template-for-joomla-1-7-and-up-341

**Comment by softforge** [comment]
http://nightly.sfdemo.co.uk/index.php
joomla 3.8.11 and your template

**Comment by dsimonse** [comment]
Hi,
Sorry the wrong picture uploaded - corrected now with appropiate link and YouGrids version.

**Comment by ghost** [comment]
@dsimonse Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.

**Comment by dsimonse** [comment]
Thanks for your help!
It's a confirmed bug in the YouGrids template.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21351">issues.joomla.org/tracker/joomla-cms/21351</a>.</sub>

**Comment by ghost** [comment]
@dsimonse thanks for Info. Don't hesitate to report an Issue.
