### ISSUE TITLE
[4.0] joomla-field-media element should trigger 'change' event when media is selected

### ISSUE THREAD

**Issue by khanhlh** [joomla/joomla-cms#21354]
After a media is selected, the value of input is updated, the joomla-field-media element should trigger 'change' event.

**Comment by ghost** [comment]
@laoneo shouldn't this kind of Issues reported at https://github.com/joomla-projects/media-manager-improvement?

**Comment by laoneo** [comment]
Its fine here

**Comment by dgrammatiko** [comment]
Please test #32379
