### ISSUE TITLE
[4.0] Collapse second level menu

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21353]
When the menu is toggled to just the icon and you select a second level menu then the second level collapses as soon as the page loads which is great. The same is not true when the menu is toggled to icon and text. Hard to explain and easier to show in these animations

![collapse](https://user-images.githubusercontent.com/1296369/43549258-1a88ef2e-95d8-11e8-84b7-7f72ef8f10b5.gif)

![open](https://user-images.githubusercontent.com/1296369/43549259-1aa55754-95d8-11e8-82cf-76963e15a245.gif)

**Comment by ghost** [comment]
Issue confirmed.

Behaviour of 2nd-Level-Menu is planned to change (maybe a horizontal 2nd Level).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21353">issues.joomla.org/tracker/joomla-cms/21353</a>.</sub>

**Comment by infograf768** [comment]
Issue confirmed

**Comment by ghost** [comment]
closed as having Pull Request #21367

**Comment by ggppdk** [comment]
@franz-wohlkoenig 


I think @brianteeman 
is describing a different issue here than issue #21360
so please reopen

@brianteeman  , right ?

I have made a PR #21367 that fixes #21360
I am a little confused why #21360 is said to be duplicate of this issue

**Comment by ghost** [comment]
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21353">issues.joomla.org/tracker/joomla-cms/21353</a>.</sub>

**Comment by infograf768** [comment]
Indeed they are not really duplicates but https://github.com/joomla/joomla-cms/pull/21367 solves both issues including this one.
Re-closing :)
