### ISSUE TITLE
Bug: New Joomla releases keep getting added for unexplicable reasons

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-cms#21355]
### Steps to reproduce the issue

- Go to the Milestones page: https://github.com/joomla/joomla-cms/milestones
- See that 3.9.0 is pretty much ready with only 2 issues left to close, and it has been like that for a long time now.
- See that a new 3.8.12 version has been scheduled, with release date 1 MONTH from now

The same thing happened last month with the 3.8.10/11 release, and two months ago with the 3.8.9 release.

### Expected result

- I would expect for 3.9 to get a scheduled date and not more in-between 3.8.x keeping getting added.

### Actual result

- Another in-between release has been added.

What makes even less sense is that they are not releases required to quickly fix urgent issues, no, every time they get scheduled ONE MONTH after the previous one, despite there not being any immediate fixes needed. Right now 3.8.12 only has one issue assigned to it.  What's the point of even having it instead of assigning it to 3.9?

### Additional comments

Come on guys. What is going on? There are issues/pull requests in 3.9 milestone that were opened over 1 year ago... Fixed, coded and merged, but still not released...  
When is it going to stop? Are we going to get to 3.8.99 before 3.9 is released? 
Oh... And Joomla 3.9 is the "GDPR release". But seeing it is not May 25th yet, you do still have some time to release it... oh wait...

Now, I personally don't have any personal urgency to have 3.9 (I already merged what I need from 3.9 in my sites anyway) or 4.0, but I just find it unexplicable that you are not moving forward already.

**Comment by jeckodevelopment** [comment]
The aim is to release version 3.9 (the so called GDPR release) once it has been tested enough in deep, to avoid publishing something that needs to be fixed and is not adequate for Production websites.

The Pull Request #20800 to merge the work done by the team on the 3.9 is open for feedbacks, tests and inputs for months, but we need urgently more and more tests before merging it.
Please take this opportunity to extensively test the 3.9 work/PRs and help us speeding up the release process for such an important version.

And, FYI, version 3.8.11 addresses 37 issues and 3.8.x release cycle has always been like this: 1 release per month approximately.

**Comment by AndySDH** [comment]
Thanks, I get it now. Just checked that PR, didn't know of its existence because it wasn't showing up in the 3.9 Milestone. I didn't know this was the status of the situation and the fact that not enough people have tested it. It's understandable, then. Sorry :)

**Comment by ghost** [comment]
@AndySDH close Issue as all clear?

**Comment by AndySDH** [comment]
Yeap.

**Comment by brianteeman** [comment]
@AndySDH for your information a milestone is normally not added to a pull request until it is merged. There are some exceptions of course.

**Comment by mbabker** [comment]
> I would expect for 3.9 to get a scheduled date and not more in-between 3.8.x keeping getting added.

As pointed out, the "blocker" for the 3.9 release is the privacy tool suite PR (#20800) being merged.  Without that either merged or abandoned, right now I'm not even going to entertain scheduling a release date for the branch, because worst case scenario we do a 3.9 release without it, then privacy tools merge, and 2-3 months after 3.9.0 there's a 3.10.0 and that's just going to create release burnout for people involved in coordinating release efforts (i.e. marketing, documentation, etc.).  Best case scenario, we put a date out, then it passes by without a release, then people groan because we didn't put out the release on that date and moved it for whatever reason; lather, rinse, repeat (it has happened before).

> What makes even less sense is that they are not releases required to quickly fix urgent issues, no, every time they get scheduled ONE MONTH after the previous one

In general, we put out regular maintenance releases.  I've tried to keep that on a predictable pattern for everyone's sanity, versus just waking up one day and being like "oh, there've been 100 merged pull requests, we can do a release now".

> There are issues/pull requests in 3.9 milestone that were opened over 1 year ago... Fixed, coded and merged, but still not released...

It happens sometimes.  We don't do a feature release simply because a new feature was accepted.  Also keep in mind 3 months ago there was no intention of releasing 3.9 until 4.0 was ready, so plans changed when the GDPR thing was put on the table for consideration.

**Comment by AndySDH** [comment]
I get it, thanks for the explanations, what you bring up makes perfect sense.

However at this point, I wonder: why not release all (or most of) the other 3.9 milestone issues/PR fixes as part of 3.8.12 instead, at this point? 
I don't think all the other stuff that's been ready to go for a long time should keep waiting months and months just because another feature is not complete... don't you think?

**Comment by mbabker** [comment]
> However at this point, I wonder: why not release all (or most of) the other 3.9 milestone issues/PR fixes as part of 3.8.12 instead, at this point?

Our releases follow Semantic Versioning, which summed up is basically this:

- Make a B/C break?  Release x+1.0.0 (major release)
- Add a feature?  Release x.y+1.0 (minor release)
- Fix stuff?  Release x.y.z+1 (patch release)

By that standard, it is inappropriate to include features in a patch release, the inclusion of features must trigger a minor release.  We've broken that in the past as required to deal with various issues and concerns (such as the download mirror feature for extension updates as a result of Russian firewall rules blocking the Amazon S3 node we use as our primary download source), but those are exceptional circumstances and aren't the normal convention.

**Comment by AndySDH** [comment]
Yeah, figured it could have been something like that. I see.

So alrighty, hopefully the privacy tool PR gets merged soon :)
Or worst case scenario I guess you could release a 3.9 without it, rename the one with the privacy tool to 3.10, and have the last 3.x release be 3.11 haha. (I know, I know, 3.11 sounds ugly as a name :D )
