### ISSUE TITLE
Module latest articles in Joomla 3.8.11 doesn't work

### ISSUE THREAD

**Issue by redzy12** [joomla/joomla-cms#21356]
### Steps to reproduce the issue

Module latest articles in Joomla after update on 3.8.11 doesn't work

**Comment by ghost** [comment]
Guess you mean ~~#21347~~ #21333 and fix PR #21336 as your Description of Issue "doesn't work" is not clear, so closing as duplicate Report.

If you mean another Issue, please reopen and describe it clear and also give "System information (as much as possible)"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21356">issues.joomla.org/tracker/joomla-cms/21356</a>.</sub>
