### ISSUE TITLE
[4.0.0-alpha4-dev] No Insert/edit image button in TinyMCE editor

### ISSUE THREAD

**Issue by Condorious** [joomla/joomla-cms#21368]
How I can add Insert/edit image button in TinyMCE editor?
I need the functionality of the text flow around the image on the left or right.

**Comment by ghost** [comment]
On a quick Look there the same Function in J3/j4, but maybe i didn't get what you mean. So can you please give more Details?

**Comment by Condorious** [comment]
Yes, I see in J3 same fuctional, but in older version I remember in Edit image I can choose text flow.
May be this question better ask TinyMCE editor team...

**Comment by ghost** [comment]
I suggest to ask at TinyMCE-Team.

Closing as no Core-Issue. It can always reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21368">issues.joomla.org/tracker/joomla-cms/21368</a>.</sub>
