### ISSUE TITLE
Private Messaging System Front-end

### ISSUE THREAD

**Issue by Settingsw** [joomla/joomla-cms#21365]
Feature Request: Private Messaging System Front-end 

there are 0 free and not abandoned reliable message systems available on JED

@brianteeman please not cloce or reopen this #21318 issue request for furteher colaboration

Is your feature request related to a problem? Please describe.

website frontend users can not communicate with each other by using a simple inbox/outbox, now ony admin can use this feature in backend

There are 0 free and not abandoned reliable message systems available on JED

Describe the solution you'd like

Private Messaging System.
Let website users communicate with each other by using a simple inbox/outbox solution in Front-end.

Additional context

Now Private Messaging screen allows you to send messages to other Back-end Joomla! users. You may read, write, send, and delete messages here. In addition, you may also manage message settings and grouping options.

Maybe there is a way to allow all registered users to send private messages in front-end, but I still couldn't figure out how to do it in Joomla!

There are 0 free and not abandoned reliable message systems available on JED

**Comment by richard67** [comment]
@Settingsw And what about [uddeIM](https://extensions.joomla.org/extensions/extension/communication/pms/uddeim/ "uddeIM") ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21365">issues.joomla.org/tracker/joomla-cms/21365</a>.</sub>

**Comment by richard67** [comment]
Ah, I just see, uddeIM is discontinued for Joomla 4. For Joomla 3 it still should work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21365">issues.joomla.org/tracker/joomla-cms/21365</a>.</sub>

**Comment by mbabker** [comment]
Considering 4.0 hasn't even reached a beta milestone I would take declared extension compatibility very lightly right now.

**Comment by richard67** [comment]
The author of uddeIM has a message on his home page that he will not continue development for Joomla 4.0.

**Comment by mbabker** [comment]
Oh, well, that's different then.  I made it as far as the JED to be honest, and nothing there had pointed that out.

**Comment by richard67** [comment]
It is really a pity because uddeIM was the most popular PMS for Jooomla. I used it in past and made very gfood experience. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21365">issues.joomla.org/tracker/joomla-cms/21365</a>.</sub>

**Comment by richard67** [comment]
Here is the corresponding message with a discussion. Maybe tghey find someone, e.g. JoomlaShack, who could continue uddeIM:
[http://www.joomlapolis.com/forum/25-uddeim-plugin-and-component/238073-support-continues-for-joomla-3-x-branch-only](http://www.joomlapolis.com/forum/25-uddeim-plugin-and-component/238073-support-continues-for-joomla-3-x-branch-only)

**Comment by richard67** [comment]
@Settingsw Did you check other extensions in [https://extensions.joomla.org/category/communication/pms/](https://extensions.joomla.org/category/communication/pms/ "https://extensions.joomla.org/category/communication/pms/"), e.g. [https://extensions.joomla.org/extensions/extension/communication/pms/codopm/](https://extensions.joomla.org/extensions/extension/communication/pms/codopm/ "https://extensions.joomla.org/extensions/extension/communication/pms/codopm/")?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21365">issues.joomla.org/tracker/joomla-cms/21365</a>.</sub>

**Comment by richard67** [comment]
codopm is free, and uddeIm is free, too, and works for J3. There is enough time to see if someone takes over uddeIM until J4 is released. So I do not really see the need for integrating a frontend PMS into Joomla Core. But that's only my opinion.

**Comment by rdeutz** [comment]
I see zero chance this going into the core, even if you have a ready to merge solution

**Comment by Settingsw** [comment]
@rdeutz please not cloce or reopen this issue request for furteher colaboration

**Comment by Settingsw** [comment]
@franz-wohlkoenig  I need uddeIM functions and price. So its bouth I need. But I fear it soon be abandonware.

@richard67 codopm not updated since 2014
uddeIM not updated since 2017

**Comment by brianteeman** [comment]
This is not a feature that will be added to the core of joomla

**Comment by Settingsw** [comment]
@brianteeman  why not? This feature is already in the core of joomla but restricted to Back-end Joomla! users.

Now Private Messaging screen allows you to send messages to other Back-end Joomla! users. You may read, write, send, and delete messages here. In addition, you may also manage message settings and grouping options.

Maybe there is a way to allow all registered users to send private messages in front-end?

**Comment by mbabker** [comment]
> please not cloce or reopen this issue request for furteher colaboration

A closed item can still be discussed.

> This feature is already in the core of joomla but restricted to Back-end Joomla! users.

com_messages in the Joomla backend is designed for administrative communication and notifications.  It is not designed as a general purpose chat/email solution.  If you are aiming for a general purpose chat/email solution, you will need an extension, because we do not feel adding this capability to core is for the benefit of the majority of our users.

> There are 0 free and not abandoned reliable message systems available on JED

Unfortunately, not every extension in any CMS' ecosystem is free, likewise just because someone starts an extension doesn't mean it will be supported forever.  That doesn't mean that core has to fill that space by adding things to our package that will have to be supported forever (because it's damn near impossible to remove something once added).

**Comment by Settingsw** [comment]
@mbabker in case you dont know - An opened item can still be discussed.

I see no reasone why not posible to enable users in fornt-end to have communication and notifications if com_messages in the Joomla backend is already designed for administrative communication and notifications.

21380

great shame on Joomla osm to have @rdeutz as the maintainers of this repository

here are the answer why no one ask features or FRC couse if you do it and rdeutz is against that feature for no reason @rdeutz and his budies just block you from further participation and closes the issue with zero answers.

@jeckodevelopment its very sad that @rdeutz wasted joomla users and devs time and closed this RFC, but it is huge disgrace for Joomla! osm if it supports such shamefull behavior of @rdeutz as the maintainers of joomla repository.

**Comment by mbabker** [comment]
The personal attacks because you do not agree with the decisions of the project leadership are not going to be tolerated.

**Comment by rdeutz** [comment]
@Settingsw you are blocked now for 7 days
