### ISSUE TITLE
[4.0.0-alpha4-dev] Articles manual ordering not saves

### ISSUE THREAD

**Issue by Condorious** [joomla/joomla-cms#21366]
### Steps to reproduce the issue
In Content - Articles Options - Shared - Article Order I choice Ordering. On  Articles list I press Ordering button for manual ordering, then move articles I need, but articles ordering is not saving.

**Comment by ghost** [comment]
Issue confirmed.

Article-Ordering is saved if Article is dargged and dropped at last Position. Its not saved if Article is dragged between other Articles or as first Article in List.

**Comment by ghost** [comment]
If you leave Article-List (ie open an Article and close) manual ordered Article is on Place before ordering. In short: Manual Ordering don't work.

**Comment by ghost** [comment]
Manual Ordering of Menu-Items works as expected.

**Comment by brianteeman** [comment]
I can not replicate this. Remember that if the articles are not in the same category then you can not sort them

### example
Article 1 - (category a)
Article 2 - (category a)
Article 3 - (category a)
Article 4 - (category b)

In this example you can **not** drag and drop or manually order _article 4_

**Comment by Quy** [comment]
I can not replicate. 

@franz-wohlkoenig Please confirm. Thanks.
