### ISSUE TITLE
[4.0] Side menu does not work anymore

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#21360]
Since the update of this night (02/08/2018) Joomla! 4.0 alpha 5, the left side menu no longer works for "content, menus, components, users". On all browsers.

**Comment by wojsmol** [comment]
Duplicate of https://github.com/joomla/joomla-cms/issues/21353?

**Comment by ghost** [comment]
Thanks for Report, but closed as duplicate Report #21353.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21360">issues.joomla.org/tracker/joomla-cms/21360</a>.</sub>

**Comment by ggppdk** [comment]
I have made PR #21367 to fix this
