### ISSUE TITLE
[4.0] TinyMCE will not initialise on Firefox

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21374]
### Steps to reproduce the issue
This is a known Issue at [TinyMCE](https://github.com/tinymce/tinymce/issues/4502) but i wan't to report it here as its not an own Issue so far.
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by ghost** [comment]
Changed Title as Safari works (Safari-Issue is reported at TinyMCE).

**Comment by ghazal** [comment]
Issue confirmed.

System information
    4.0.0-alpha5-dev - Last built: Sunday, 05 August 2018 
    macOS Sierra, 10.12.6
    Firefox 61.0.1 (64-bit)

PHP 7.2.5

**Comment by ghost** [comment]
looks fixe somewhere. Please reopen if its not true.

**Comment by brianteeman** [comment]
Well as tinymce confirmed the issue and said it will be fixed in a future version I find that surprising :)

**Comment by ghost** [comment]
me too but i read somewhere (by @dgrammatiko ?) a list of resolved ssue where this Issue is "maybe" fixed too.

**Comment by ghost** [comment]
@brianteeman #21428

**Comment by dgrammatiko** [comment]
@franz-wohlkoenig please reopen this, the patch is really a nasty workaround rather a solid solution that can be shipped in production...

**Comment by ghost** [comment]
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21374">issues.joomla.org/tracker/joomla-cms/21374</a>.</sub>

**Comment by ghost** [comment]
closed as #21588 is merged.
