### ISSUE TITLE
[4.0] com_field: Unstyled Dropdown "Category"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21375]
### Steps to reproduce the issue
As Title say:

![screen shot 2018-08-03 at 07 19 36](https://user-images.githubusercontent.com/8235763/43625535-ce24f8fa-96ed-11e8-8f45-ec096b0beabc.jpg)
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by brianteeman** [comment]
@franz-wohlkoenig there is no need to keep reporting these - the cause is the same and the fix will fix them all

**Comment by ghost** [comment]
closed as stated above.
