### ISSUE TITLE
[4.0] RTL: Login-Form "Forget Username / Password" need align right

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21376]
### Steps to reproduce the issue
As Title say:

![screen shot 2018-08-03 at 09 03 51](https://user-images.githubusercontent.com/8235763/43629120-a0f84346-96fc-11e8-8d52-b2c71d63b59e.jpg)
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by infograf768** [comment]
Closing as we have a patch
https://github.com/joomla/joomla-cms/pull/21402
