### ISSUE TITLE
RFC Private Messaging System Front-end

### ISSUE THREAD

**Issue by Settingsw** [joomla/joomla-cms#21380]
Request for Comments 

Feature Request: Private Messaging System Front-end

there are 0 free and not abandoned reliable message systems available on JED, and joomla core already have pm system but it is restricted to admin only.

Feature Request: Private Messaging System Front-end

there are 0 free and not abandoned reliable message systems available on JED, and joomla pms core system restricted to admin only.

@brianteeman please not cloce or reopen or merge this  #21377 #21318 issues request for furteher colaboration

@rdeutz please not cloce or reopen this #21365 issue request for furteher colaboration

why not? This feature is already in the core of joomla but restricted to Back-end Joomla! users.

Is your feature request related to a problem? Please describe.

website frontend users can not communicate with each other by using a simple inbox/outbox, now ony admin can use this feature in backend

There are 0 free and not abandoned reliable message systems available on JED

Describe the solution you'd like

Private Messaging System.
Let website users communicate with each other by using a simple inbox/outbox solution in Front-end.

Additional context

Now Private Messaging screen allows you to send messages to other Back-end Joomla! users. You may read, write, send, and delete messages here. In addition, you may also manage message settings and grouping options.

Maybe there is a way to allow all registered users to send private messages in front-end, but I still couldn't figure out how to do it in Joomla!

There are 0 free and not abandoned reliable message systems available on JED

@franz-wohlkoenig I need uddeIM functions and price. So its bouth I need. But I fear it soon be abandonware.

@richard67 codopm not updated since 2014
uddeIM not updated since 2017

@jeckodevelopment its very sad that @brianteeman  and @rdeutz  wasted my time and closed this RFC, but it is huge disgrace for Joomla! osm if it supports such a behavior.

still no answer why joomla pms core system is restricted to backend only? and why @brianteeman  and @rdeutz are so against it?

**Comment by jeckodevelopment** [comment]
@franz-wohlkoenig , @brianteeman please leave this RFC open to further discuss that and avoid the creation of plenty of other copies.

**Comment by alikon** [comment]
despite it cannot be considered as a "all kind of sites" feature why not ?

**Comment by franz-wohlkoenig** [comment]
fot this who missed earlier Discussions: #21377 #21365

**Comment by alikon** [comment]
sorry for miss to read the many other places where this  has been already discussed
but  you should know i'm out of chorus....

but at the end of the day what are the main objections to this proposal ?

- there are already 3dp extesnsions that already do this and they are free
- is not a so common requested feature
- we need a light core

**Comment by franz-wohlkoenig** [comment]
@alikon my Comment was not about you, it was about People who may haven't read earlier Discussions.

**Comment by alikon** [comment]
@franz-wohlkoenig even if no problem :smiley:

**Comment by rdeutz** [comment]
@Settingsw you have to respect the decision made be the maintainers of this repository, I will close this now. If you open the next issue with the same content I will block you from further participation

**Comment by Settingsw** [comment]
@rdeutz you do not respect Joomla! users RFC also you dont respect @jeckodevelopment osm secretary

still no answer why joomla pms core system is restricted to backend only? and why @brianteeman and @rdeutz are so against it?

great shame on Joomla osm to have @rdeutz as the maintainers of this repository

here are the answer why no one ask features or FRC couse if you do it and rdeutz is against that feature for no reason @rdeutz **and his budies just block you from further participation**  and closes the issue with zero answers.

@jeckodevelopment its very sad that @rdeutz wasted joomla users and devs time and closed this RFC, but it is huge disgrace for Joomla! osm if it supports such shamefull behavior of @rdeutz as the maintainers of joomla repository.
