### ISSUE TITLE
[4.0] Modules - Unable to Add Custom Module Position

### ISSUE THREAD

**Issue by JOYScka** [joomla/joomla-cms#21389]
### Steps to reproduce the issue

Modules > New > Custom 
Position - Type in custom position "main-share" 

### Expected result

Hit return on keyboard - position added

### Actual result

Hit return on keyboard - nothing

### System information (as much as possible)

Joomla_4.0.0-alpha5-dev-Development-Full_Package.zip
Friday, 03 August 2018

MAMP Mac
PHP 7.1.6
MySQL 5.6.35
Chrome
CodeMirror Editor

### Additional comments

Cache cleared

**Comment by dgrammatiko** [comment]
It's a known problem due to chosen.js which is deprecated and already removed in most places. J4 will not distribute or support chosen!

There is some work done already on the replacement: 
https://github.com/joomla/joomla-cms/pull/19671

**Comment by ghost** [comment]
@JOYScka Thanks for Report. The Issue has been reported #21209 so closed as duplicate Report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21389">issues.joomla.org/tracker/joomla-cms/21389</a>.</sub>
