### ISSUE TITLE
[Meta] Fix AppVeyor build delays for PHP 5.6

### ISSUE THREAD

**Issue by clayfreeman** [joomla/joomla-cms#21388]
### Steps to reproduce the issue

1. Cause an AppVeyor build to occur.
2. Wait 1 - 2 hrs.
3. Observe a possibly failed AppVeyor build.

### Expected result

AppVeyor should complete the PHP 5.6 build in less than five minutes, similar to PHP 7.0, 7.1.

### Actual result

AppVeyor's PHP 5.6 build takes 1 hour, minimum, in some instances and seemingly times-out.

### System information (as much as possible)

n/a

### Additional comments

The build gets stuck on [PHP Unit](https://ci.appveyor.com/project/joomla/joomla-cms/build/1.0.17571/job/ly6j9ifycfojc9n5#L1124).

**Comment by ghost** [comment]
@rdeutz is this an Issue you can Comment?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21388">issues.joomla.org/tracker/joomla-cms/21388</a>.</sub>

**Comment by rdeutz** [comment]
The reason for this is a polyfill for a crypto library there is not so much we can do

**Comment by ghost** [comment]
@rdeutz thanks for Comment.

@clayfreeman any Comment?

**Comment by clayfreeman** [comment]
Which crypto library specifically? At what file path?

I'll take a look at the tests to see if there is any room for optimization.

**Comment by rdeutz** [comment]
If you have docker (or an php5.6 env) you can see yourself, run phpunit --testdox and you will see that the JCryptCipherSodiumTest takes a very long time. IIRC then it is the $cipher->generateKey(); method what takes so long. There is not so much room for improvement without running this method the test is useless. We might need to skip these tests.

**Comment by clayfreeman** [comment]
I mean, the test suite passes currently. Nothing will change that unless the source for the polyfill changes. I'm all for skipping the Sodium test.

**Comment by rdeutz** [comment]
@clayfreeman can you make a PR?

**Comment by rdeutz** [comment]
maybe add $this->markTestSkipped('Takes too long on php5.6 and windows'); we can decide later if we need the test at all

**Comment by mbabker** [comment]
> we can decide later if we need the test at all

Oh, right, let's just remove tests validating that our cryptography API actually does what it's supposed to.  THAT makes sense.

**Comment by clayfreeman** [comment]
Its better than the entire unit test infrastructure failing due to timeouts. This can hide more serious issues under the veil of “Oh, it’s just another timeout; no need to actually investigate the failure since I already know what went wrong.”

Personally I think if we can reduce the key size for only the unit tests, it would be the best of both worlds. We can still test key generation and all related cryptography that way, and in theory the time required to generate keys can be cut down significantly.

Thoughts?

**Comment by clayfreeman** [comment]
I've just looked through the problematic library and it doesn't seem that reducing the key size is possible. I did, however, find that `\ParagonIE\Sodium\Compat::$fastMult` can be set to `true` at runtime which *might* help alleviate the issue. I could see this only reducing the time required to run by little bit though since it may not even be related to the primary issue.

**Comment by clayfreeman** [comment]
`ParagonIE_Sodium_Core_Util::declareScalarType()` is the culprit for the slow performance. This method looks like a fancy type cast proxy to facilitate strict types on PHP <= 5.6.

I personally vote that the entire test case is skipped or that pre-generated keys are used for testing instead. The likelihood of this functionality breaking in a way that doesn't result in an exception is extremely low in my opinion.

**Comment by wojsmol** [comment]
As we pin point issue to paragonie polyfill let me ping the author @paragonie-scott.

**Comment by rdeutz** [comment]
I looked at the documentation and they give some advice what you can do to make it faster, tried it but I couldn't see that it is really faster

**Comment by rdeutz** [comment]
closed as we have a PR #21633
