### ISSUE TITLE
#__content_types 'table' field too narrow

### ISSUE THREAD

**Issue by webstackdev** [joomla/joomla-cms#21395]
### Steps to reproduce the issue

Create a JSON string for the `"special"` key of the `#__content_types` table's `table` field that uses longer names for the `dbtable` or `key` than the JSON used in default installation, or includes configuration options.

### Expected result

That the database update won't error

### Actual result

Database errors, as the field is defined as `VARCHAR(255)` on MySQL

### System information (as much as possible)

MySQL database, Joomla! 3.8.10

### Additional comments

The largest current entry for the `table` field is for Newsfeeds (type_alias `com_newsfeeds.newsfeed`), at 227 characters. The field is created as `VARCHAR(255)`. I am using a prefixed surrogate key (so longer than just `id`) and my component table is namespaced (e.g. `#__vendor_tablename`), and together they exceed the 255 character limit.

Also, I notice that there are `"config":"array()"` keys in the JSON. One configuration option in com_contenthistory is `ignore_request`, set to a default of true. Any configuration options used would likely push the string length over the 255 character limit. 

I'd submit a PR, but don't have a good feel for what the field size should be.

**Comment by ghost** [comment]
can a more experienced User comment this Issue as its open since more than a Week having Status "New"?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21395">issues.joomla.org/tracker/joomla-cms/21395</a>.</sub>

**Comment by alikon** [comment]
can be doubled declaring as `VARCHAR(512)`

**Comment by ghost** [comment]
@calligraphic any Comment on Comment by @alikon?

**Comment by webstackdev** [comment]
Hi @franz-wohlkoenig franz, sorry to lose track of this issue. I've been working around the issue with this DDL statement in my install SQL:

    ALTER TABLE `#__content_types` MODIFY `table` VARCHAR(2048);

I think a wider column than what @alikon suggested might be a good idea. It's not an indexed field so there's no performance impact.

**Comment by ghost** [comment]
thanks for Comment @calligraphic. Is this Discussion #19618 similar to your Issue?

**Comment by brianteeman** [comment]
@franz-wohlkoenig no thats very different and this one is a legitimate reason for slightly increasing the size

**Comment by ghost** [comment]
closed as having Pull Request #21796

**Comment by webstackdev** [comment]
@franz-wohlkoenig Thank you. My first Joomla! PR :)

**Comment by ghost** [comment]
@calligraphic congratulations to your first PR :-)
