### ISSUE TITLE
[4.0.0-alpha4] Can't edit articles

### ISSUE THREAD

**Issue by htmgarcia** [joomla/joomla-cms#21390]
### Steps to reproduce the issue
- Using Joomla 4 Alpha 4, create an article. 
- Save and close.
- Try to edit the article you just created.

### Expected result
I should be able to reach the edit article page

### Actual result
I reach an error screen: **HTTP ERROR 500**

### System information (as much as possible)
Chrome Version 67.0.3396.99 (Official Build) (64-bit)
MacOS Sierra 10.13.6

**Comment by wojsmol** [comment]
@htmgarcia Try reproduce this issue on [nightly build](https://developer.joomla.org/nightly-builds.html)

**Comment by ghost** [comment]
Can't confirm.

![screen shot 2018-08-03 at 17 39 59](https://user-images.githubusercontent.com/8235763/43652035-4f08f696-9744-11e8-8663-bfd9031531da.jpg)


### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by htmgarcia** [comment]
@wojsmol great advice! Thanks. I updated and the issue is gone. 
btw, I'm writing a post to explain how to update a test site using https://update.joomla.org/core/nightlies/next_major_list.xml - I didn't knew about this URL.

Closing this issue since was already solved with Nightly Build 4.0.0-alpha5-dev
