### ISSUE TITLE
[4.0] com_fields: Type "Editor" give `Joomla\CMS\Object\CMSObject`

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21397]
### Steps to reproduce the issue
As Title say:

![screen shot 2018-08-04 at 06 55 15](https://user-images.githubusercontent.com/8235763/43672688-a132d58a-97b3-11e8-9715-5ca3e6ab8f31.jpg)
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by TobsBobs** [comment]
Issue confirmed 
![screenshot_2018-08-04 articles new - joomla 4 test - administration](https://user-images.githubusercontent.com/816779/43676175-1483c5c0-97ec-11e8-982f-f4040c7e15ae.png)

**Comment by brianteeman** [comment]
I can no longer replicate this issue - can only assume it has been resolved elsewhere
