### ISSUE TITLE
[4.0] com_field: Unstyled Dropdown "Hide Button"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21396]
### Steps to reproduce the issue
As Title say:
![screen shot 2018-08-04 at 06 51 15](https://user-images.githubusercontent.com/8235763/43672659-1b75c33a-97b3-11e8-93dc-b7032dc61605.jpg)
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by TobsBobs** [comment]
Issue confirmed in Firefox (62b13) and Chrome.

**Comment by wilsonge** [comment]
I think this is a 'known issue'. Right now the aim is to leave as many of the select elements in native browser select as possible. There are two exceptions 1) Tags (ajax submit etc) 2) Where we need filtering (categories, module positions etc)

**Comment by ghost** [comment]
Do i understand correct that the shown Drodown is provided by Browser? In Firefox, Safari and Chrome (all latest on Mac) all look same.

**Comment by wilsonge** [comment]
As far as I'm aware yes? There's some padding etc provided by the stylesheet. But the multiselect ultimately is browser rendered

**Comment by ghost** [comment]
thanks for Information, @wilsonge. So in Future no need for Report if a Layout look different to J3 in Cases like that.

**Comment by ggppdk** [comment]
This is as part of intention to remove / replace chosen JS ? 

If there is something known about the replacement of it ?
then please say so that we adapt to it earlier

**Comment by wilsonge** [comment]
> This is as part of intention to remove / replace chosen JS ?

Pretty much. As to a replacement/keeping the original there's still no full decision made. But definitely the aim is to remove it where it's not required. So unless there's some sort of search/ajax functionality required (tags, category filtering, module position filtering/dynamic creation etc) then we'll just use native select not chosen

**Comment by brianteeman** [comment]
and this is still my preferred option https://alphagov.github.io/accessible-autocomplete/examples/

either as an element or easier as a progressive enhancement
