### ISSUE TITLE
[4.0] Menu doesn't work

### ISSUE THREAD

**Issue by TobsBobs** [joomla/joomla-cms#21394]
### Steps to reproduce the issue
Install Joomla Nightly (These packages were built based on commit c669dac01ef191611f6a12925909bfebd5535c25)
Use the menus Content, Menus, Components and User. The menus do not work. Also chrome does not work. 

### Expected result
The Menus should work.

### Actual result
For the menu items Content, Menus, Components and User it doesn't.

### System information (as much as possible)
PHP Built On | Windows NT TOBSBOBS 10.0 build 17134 (Windows 10) i586
mysql
5.5.5-10.1.33-MariaDB
latin1_swedish_ci
utf8_general_ci
7.2.6
Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6
apache2handler
Joomla! 4.0.0-alpha5-dev Development [ Amani ] 22-July-2018 22:58 GMT
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

![screenshot_2018-08-03 control panel - joomla 4 test - administration](https://user-images.githubusercontent.com/816779/43658556-894874c0-9759-11e8-80fa-7ca23a9027e5.png)

**Comment by ghost** [comment]
what doesn't work? Can you please describe?

**Comment by ghost** [comment]
do you mean #21353?

**Comment by TobsBobs** [comment]
I mean not  #21353.
The menu doesn't open the second level of the menus.  When I click Content then it must collapse the second level submenus. But it doesn't.

**Comment by wojsmol** [comment]
@TobsBobs this is fixed by https://github.com/joomla/joomla-cms/pull/21367

**Comment by TobsBobs** [comment]
Thanks @wojsmol 
I don't see this. I close this issue
