### ISSUE TITLE
Change the 'Server Time Zone' field label to Website Time Zone

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-cms#21398]
The Joomla Global Configuration has a Field to set the 'Server Time Zone'
Saying Server time zone gives a very wrong impression. The timezone to be set here has to be the Timezone for the Primary Audience of the website. Saying Server can confuse the end users. I might have bought hosting in the US so my Server is there.. But my website's primary Audience is in India. The current nomenclature can confuse people into setting the wrong timezone

**Comment by parthlawate** [comment]
Closed as in - you dont agree ? Pls do share your thoguhts

**Comment by ghost** [comment]
Issues are closed if theres a Pull request for. If you open a PR, you don't have to create a Issue too.

**Comment by parthlawate** [comment]
Oh right :) Thanks !
