### ISSUE TITLE
[4.0]Wondering if this html tag: is regular

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#21403]
### System information (as much as possible)
Commit 3596efbb1dada6b10b654b4ae036c7329c5afe46
Saturday, 04 August 2018 02:08:02 UTC

In /layouts/joomla/toolbar/standard.php, line 54

```
<joomla-toolbar-button <?php echo $idAttr.$taskAttr.$listAttr.$formAttr.$validate.$msgAttr; ?>>

```
Just wondering if this is regular.

**Comment by Fedik** [comment]
it no ta bug it feature, it called "Custom element"

**Comment by ghost** [comment]
closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21403">issues.joomla.org/tracker/joomla-cms/21403</a>.</sub>

**Comment by ghazal** [comment]
OK, got it. Thanks.
I guess I missed this article:
 https://magazine.joomla.org/issues/issue-nov-2017/item/3286-joomla-4-custom-elements
