### ISSUE TITLE
[4.0] Menu Item Workflow: How to know that an Article has a corresponding Menu

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21411]
### Is your feature request related to a problem? Please describe.
In #21357 User can link inside an Article to a corresponding menu item. 

If User click on "New Menu Item" its not shown that the Article is linked on which Menu Item. 
### Describe the solution you'd like
It would help if User see what Menu the Article is linked.
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by brianteeman** [comment]
I do not believe this can ever be possible as there is no limit to the number of menu items that an article could be displayed on. It would only really be possible and/or useful on a system (unlike joomla) where every piece of content is displayed on its own menu item.
