### ISSUE TITLE
Accessing property without checking the object state causing Joomla installer non-responsive.

### ISSUE THREAD

**Issue by corejoomla** [joomla/joomla-cms#21412]
### Steps to reproduce the issue
Prerequisites: PHP notice messages are enabled

After installing Joomla, go to customization and select language say Hindi for installation. If the language cannot be installed, the server will not return any value, and the value is null. But the below code is accessing its properties without checking the data is null or not.

\installation\src\Model\LanguagesModel.php

    return trim($update->get('downloadurl', false)->_data);

This resulted in a notice message causing json response invalid.

    Notice: Trying to get property of non-object in D:\xampp\htdocs\joomla\installation\src\Model\LanguagesModel.php on line <i>253</i>

### Expected result

The installer shows message that it cannot install selected language.

"Joomla was unable to install Hindi language. You will be able to install it later using the Joomla Administrator"

### Actual result

Screen frozen

### System information (as much as possible)

Joomla v4.0.0.alpha4
Windows, XAMPP, PHP Notice messages enabled

### Additional comments

Installing only Hindi language

**Comment by brianteeman** [comment]
At this moment in time I understand this to be expected behaviour as only 3 languages are setup for testing with joomla 4

However I am not 100% certain so leaving this open for someone else to confirm that this is expected or not

**Comment by mbabker** [comment]
It is a real bug.

```php
return trim($update->get('downloadurl', false)->_data);
```

The update object being returned here is a subclass of the deprecated `Joomla\CMS\Object\CMSObject`.  Calling its `get()` method will try to return the value of the property name you give in the first argument, and if not set will return whatever you give as the second argument.  So in this case, when the "downloadurl" property isn't set, a boolean false is being returned.  You can't access properties of an object on a boolean value.

So, it needs to be something like this:

```php
$downloadUrl = $update->get('downloadurl', false);

if ($downloadUrl === false) {
    return '';
}

return trim($downloadUrl->_data);
```

**Comment by corejoomla** [comment]
Created PR #21413

Tested this on v4 alpha 4 and the screen is not frozen. 

Additional observation: The error message is shown behind the modal backdrop and the page is redirected to the "congratulations" screen. Although it is not related to this bug.

**Comment by brianteeman** [comment]
Closed as we have a pr
