### ISSUE TITLE
Module "Latest Articles" not showing main articles

### ISSUE THREAD

**Issue by NeckbreakerPascal** [joomla/joomla-cms#21414]
### Steps to reproduce the issue
Create a Module "Latest Articles and put it on the template that you can see it. Use a categorie and select "Show Main Articles" (I use the german version, not sure if they are called main articles).

### Expected result
See a box with all articles from the category including main and non-main. 

### Actual result
Only non-main articles are showing up.

### System information (as much as possible)
Joomla 3.8.11

### Additional comments
It looks like it is since the latests update: 3.8.11

**Comment by SharkyKZ** [comment]
Fixed with #21336. Fix will be included in 3.8.12.
