### ISSUE TITLE
[4.0] Double Click needed on Backend Main Menu for changing a view

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#21416]
### Steps to reproduce the issue

I don't know if this is a feature, but for me it looks like a bug. 

In Backend click on one of the icons, i.e. content. The content submenu appears. 
Select an item i.e. articles.
The submenu is collapsed and the articles view appears.
Now suppose you want the categories view. To get this view, you must re-open the submenu tab.
Click in the content menu in the main menu.

### Expected result
The submenu should appear.

### Actual result
Nothing happens. You must click again on the icon. 

### System information (as much as possible)
v4.0 dev
WIN10
Firefox latest version 
edge 

### Additional comments
On edge, the whole collapsing and expanding is unprdictable and bumpy

**Comment by ghost** [comment]
you didn't get this:

![screen shot 2018-08-06 at 15 07 58](https://user-images.githubusercontent.com/8235763/43718330-9dd0ef5c-998a-11e8-9973-f4ee0c3e4c54.jpg)


### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by chmst** [comment]
No, I get this, ia am on the dev branch ![screen shot 2018-08-06 at 13 13 35](https://issues.joomla.org/uploads/1/0f4b19e5d567d1d4aab19acca1034ead.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21416">issues.joomla.org/tracker/joomla-cms/21416</a>.</sub>

**Comment by brianteeman** [comment]
Can't confirm at all - looks like you are on a github clone and have not updated with npm etc

Please test with the nightly download

**Comment by chmst** [comment]
After repeating the composer / npm stuff several times I see the submenu again. Sorry for wasting your time. Please close the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21416">issues.joomla.org/tracker/joomla-cms/21416</a>.</sub>

**Comment by ghost** [comment]
@chmst Thanks for reporting Issue. Don't hesitate to report any Issue you get.

Clsong as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21416">issues.joomla.org/tracker/joomla-cms/21416</a>.</sub>
