### ISSUE TITLE
[4.0] Disabled Template Module Styles (ie chromes) still available in list

### ISSUE THREAD

**Issue by caseyzman** [joomla/joomla-cms#21429]
### Steps to reproduce the issue
Install Joomla
Install Secondary Template (any template with modules.php)
Disable template in "Manage Extensions"
Open any Module and the modules.php (ie chromes) are still available

### Expected result
I Expected the modules.php options from the disabled template to be "disabled", similar to how the modules positions and layout overrides are disabled from the now-disabled template.

### Actual result
modules.php (ie chromes) are still available in the options - modules styles dropdown

### System information (as much as possible)
tested on 3.8.11 and 4 Alpha-4

**Comment by ghost** [comment]
Changed Title to show its about 4.0 (and 3.8 too).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21429">issues.joomla.org/tracker/joomla-cms/21429</a>.</sub>

**Comment by SharkyKZ** [comment]
Test PR #21437 please.

**Comment by ghost** [comment]
closed as having Pull Request #21437
