### ISSUE TITLE
[4.0] Warning after Nightly Update

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21435]
### Steps to reproduce the issue
After successfully Update latest Nightly Build got Warning `Files Install: Custom install routine failure.`
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by brianteeman** [comment]
did you get this error again?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21435">issues.joomla.org/tracker/joomla-cms/21435</a>.</sub>

**Comment by ghost** [comment]
You're right, on todays Nightly Update no more Warning.

**Comment by alikon** [comment]
just got Files Install: Custom install routine failure. now  with 

> These packages were last built: Saturday, 11 August 2018 02:08:02 UTC

on a test site at *.joomla.com
