### ISSUE TITLE
[4.0] Move JTable property_exists to hasField method

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#21445]
We have added a new method hasField in the JTable class/interface. The intention is to replace all `property_exists` checks on JTable objects with this method. For more information read the PR that implemented this https://github.com/joomla/joomla-cms/pull/20987.

The usage of this should be used across the CMS. Should be a relatively easy issue for someone new to work on

**Comment by ghost** [comment]
closed as having Pull Request #21479

**Comment by wilsonge** [comment]
That's just covering Table classes. Reopening as we still need to do models (and I think there might be a few places in the views too)

**Comment by wilsonge** [comment]
Library models and controllers now done. There's some instances in extensions still left to be done
