### ISSUE TITLE
[4.0] Query profiling broken

### ISSUE THREAD

**Issue by elkuku** [joomla/joomla-cms#21458]
### Steps to reproduce the issue
Turn on debug

### Expected result

Database profiling information displayed in the debug console.

### Actual result

![bildschirmfoto_2018-08-07_19-51-46](https://user-images.githubusercontent.com/33978/43810080-82db23f6-9a7b-11e8-8f4e-1acd7d184735.png)

### System information (as much as possible)

https://github.com/joomla/joomla-cms/commit/0d891178fa33481e2265e2a2853555972fe64451

### Additional comments

https://docs.joomla.org/How_to_debug_your_code#Database_Queries
?

**Comment by csthomas** [comment]
On J3 the query profiling does not work on mysql PDO. See https://github.com/joomla/joomla-cms/pull/20322

**Comment by elkuku** [comment]
@csthomas thanks for pointing to your PR. From the amount of feedback it received it seems that this is not something very popular...
Now, looking at the 4.0 branch, I can not find anything about profiling in any of the database driver classes. Has this been removed, not ported to the framework and - could we do something in the debug plugin (I'm currently playing with) to restore the functionality?
Thanks for your help :wink:

**Comment by dgrammatiko** [comment]
@elkuku 
https://github.com/joomla/joomla-cms/commit/0d891178fa33481e2265e2a2853555972fe64451 points to a PR for content history scripts converted to ES6. I guess this is irrelevant here or...

**Comment by mbabker** [comment]
> Now, looking at the 4.0 branch, I can not find anything about profiling in any of the database driver classes. Has this been removed, not ported to the framework

The concept of a "debug mode" in the Framework's database drivers is gone, that would include the logic for #20322.  There's a query monitor API in its place to deal with the behaviors related to logging queries, execution times, and whatnot, but there isn't really a "great" replacement for the specific "disable cache and enable profiling" logic (this should be implemented at the application level, hooking the `DatabaseEvents::POST_CONNECT` event, but in the context of the CMS that is going to fire before plugins are loaded so you can't really use that in the debug plugin; we really need to do something about the concept of debug mode and the debug plugin being reliant on not being able to set itself up until long after the database connection is opened, the session started, etc. etc.; basically everything before the `onAfterInitialise` event is missed).

**Comment by elkuku** [comment]
@dgrammatiko I left the reference under "system information" to show at what point I did my check out. Has nothing to do with your PR :wink: 

@mbabker Yes this basically confirms my findings so it's not gonna be an easy fix.

Database experts please :stuck_out_tongue_winking_eye:

**Comment by brianteeman** [comment]
I am going to close this as it refers to the old debug code. If it is still an issue (doesn't appear to be) then it can always be reopened
