### ISSUE TITLE
CodeMirror Syntax Highlighting for LESS

### ISSUE THREAD

**Issue by forrestkirby** [joomla/joomla-cms#21451]
### Steps to reproduce the issue

- Create a new LESS file
- enter the following valid LESS

		#myelement {
			.myclass1 {
				position: absolute;
			}
			.myclass2 {
				margin: 50px; 
			}
		}

### Expected result

The syntax highlighting does not mark correct LESS markup as false and would show as in https://codemirror.net/mode/css/less.html

### Actual result

The syntax highlighting marks correct LESS markup as false and shows as in https://codemirror.net/mode/css/index.html

### System information (as much as possible)

Joomla! 3.8.11 Stable
Apache
PHP 7.2
mysql 5.6

### Additional comments

![screen shot 2018-08-07 at 16 05 44](https://issues.joomla.org/uploads/1/d0f0a047414044ff4511edc91c22fcb7.jpg)

![screen shot 2018-08-07 at 16 05 44](https://issues.joomla.org/uploads/1/e45ce97180da7785cd3d7cbc875b9b27.jpg)

![screen shot 2018-08-07 at 16 05 45](https://issues.joomla.org/uploads/1/df04e4d2f4605924225b5cc3cd158acd.jpg)

**Comment by ghost** [comment]
> Create a

thanks for Report, but what is meant by above?

**Comment by brianteeman** [comment]
@okonomiyaki3000 Could you take a look please

**Comment by forrestkirby** [comment]
> thanks for Report, but what is meant by above?

Sorry, that got truncated. I edited the first post. Thanks for the hint.

**Comment by okonomiyaki3000** [comment]
Thanks. Please test the fix. #21515

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21451">issues.joomla.org/tracker/joomla-cms/21451</a>.</sub>

**Comment by ghost** [comment]
@forrestkirby can you please test #21515?

**Comment by forrestkirby** [comment]
#21515 fixed this issue, thank you!

**Comment by ghost** [comment]
@forrestkirby please mark your Test as successfully:

- open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/21515)
- Login with your github-Account
- Click on blue "Test this"-Button above Authors-Picture
- mark your Test as successfully
- hit "submit test result"

**Comment by forrestkirby** [comment]
@franz-wohlkoenig Thanks for the instructions, test confirmed in Joomla! Issue Tracker.

**Comment by ghost** [comment]
thanks @forrestkirby, Status of #21515 is now "Ready to Commit".
