### ISSUE TITLE
[4.0] mutiselect interfeers with dropdown

### ISSUE THREAD

**Issue by dgrammatiko** [joomla/joomla-cms#21464]
### Steps to reproduce the issue

Go to /administrator/index.php?option=com_menus&view=menus

click on any of the modules dropdown (far right)
Then hover over the open dropdown

### Expected result
dropdown content visible on hover

### Actual result
dropdown content disappears on hover

![screenshot 2018-08-08 at 16 38 44](https://user-images.githubusercontent.com/3889375/43844411-ef8c3036-9b29-11e8-8faf-eae075d92fa7.png)
![screenshot 2018-08-08 at 16 38 39](https://user-images.githubusercontent.com/3889375/43844412-efada734-9b29-11e8-8e38-2b5be324863f.png)

### System information (as much as possible)
Safari, Chrome, FF (latest) on MacOS

### Additional comments

> But the fix (in the ce) will be an extremely easy event.stopPropagation();

**Comment by ghost** [comment]
closed as having Pull Request #21466

**Comment by dgrammatiko** [comment]
@franz-wohlkoenig can you please reopen this, the PR is not solving the problem

**Comment by brianteeman** [comment]
reopened as requezted

**Comment by brianteeman** [comment]
closed - please see #22615 its nothing to do with js there is a missing css class
