### ISSUE TITLE
[4.0] Control Panel: `tdp_workflow_associations' doesn't exist `

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21474]
### Steps to reproduce the issue
After Update on latest Nightly got:
![screen shot 2018-08-09 at 07 22 08](https://user-images.githubusercontent.com/8235763/43879615-2e963896-9ba5-11e8-8a68-74e1aa16ab81.jpg)
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by ghazal** [comment]
Got a similar error through Database fix.

Release : Thursday, 09 August 2018 02:08:00
commit 053f41afe1fa7c1496661aabc6336b6464a1997b

![db1-9-8-2018](https://user-images.githubusercontent.com/490245/43888462-ff8d50a8-9bc1-11e8-898f-1e500f5a2e02.png)
![db2_2018-08-09 error 1101](https://user-images.githubusercontent.com/490245/43888473-0b6f9b06-9bc2-11e8-8373-d09c1172ebab.png)

And error on front-end:
Error: Table 'xxxx.xxxx_workflow_associations' doesn't exist: 

Host : 1&1
PHP 7.2.8
Database 5.5.60

**Comment by laoneo** [comment]
You need to make a new installation as these tables are part of the new workflow feature which got merged in #20381.

**Comment by ghost** [comment]
@laoneo please read also [Comment](https://github.com/joomla/joomla-cms/issues/21475#issuecomment-411702538)
