### ISSUE TITLE
[4.0] [Workflow] Differ "Status" and "State"

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#21472]
At the moment the workflow has "states" and "status", which could be confusing, we should change this.

Description: https://github.com/joomla/joomla-cms/pull/20381#issuecomment-411319136

### Additional context
See here @brianteeman comment: https://github.com/joomla/joomla-cms/pull/20381#issuecomment-411471816

**Comment by HLeithner** [comment]
As brian suggested "Stage" would be a much better terminus.

**Comment by chmst** [comment]
Great! I'll change it asap.

**Comment by ghost** [comment]
closed as having Pull Request #21544
