### ISSUE TITLE
Table template_styles ("params" field as TEXT)

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21477]
### Steps to reproduce the issue
- Some template builders can exceed the limit of 65.000 characters for the params field in template_styles table because is set as "text".

### Expected result
Shouldn't break the JSON string.

### Actual result
Breaks the JSON string because it reaches the characters limit, and obviously the website stops working, the backoffice stops working too.

### System information (as much as possible)
- Using YooTheme Builder.

### Additional comments
Would be great to change to MEDIUMTEXT which handles up to 16mb and/or 16.000.000 characters instead of 65.000.

**Comment by brianteeman** [comment]
Then they are using the field wrong. 65,000 characters is more than enough to store a param.

**Comment by ghost** [comment]
Hi Brian, the problem is most of the template builders store their custom "less" and "javascript" code in those fields, and if for some reason you have a huge piece of code, in my case i have 200 lines of less css code, and some template customisation and that was enough to make it break.

I don't know if they expected someone to have this amount of code but i'm pretty sure this happened to someone else...

They use that field to store all the template parameters, custom module positions, etc etc that's why it easily reaches that amount.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21477">issues.joomla.org/tracker/joomla-cms/21477</a>.</sub>

**Comment by brianteeman** [comment]
as I said if that is what they are doing then they are using the field wrong. It is a field for parameters - not code or content

**Comment by rdeutz** [comment]
I agree with Brian, it is not the intended use of the field. On the other site, it doesn't hurt. If the change would be from varchar to text it would be different. But text, medium text, long text doens't make a difference. If you will see this change you have to make a PR.

**Comment by ghost** [comment]
Yes of course... i was just reporting the situation, not saying this would be the ideal solution but i've seen a lot of people having similar issues with other components like Community Builder too, so would be great to come up with a solution either for Joomla! or for 3rd party extension developers.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21477">issues.joomla.org/tracker/joomla-cms/21477</a>.</sub>

**Comment by mbabker** [comment]
> would be great to come up with a solution either for Joomla! or for 3rd party extension developers

Stop misusing the core database schema.  For the frameworks that are adding this many options, they really should be storing the extra data to their own tables and not trying to cram everything in columns not designed for your use case.

**Comment by ghost** [comment]
Yes obviously i understand... well, it's not me it's those companies that develop those extensions used by thousands and thousands in the community, i just noticed the problem and decided to share the situation. Thank you.

**Comment by ghost** [comment]
@mluispt if all discussed can you please close the Issue?
