### ISSUE TITLE
[4.0] com_categories batch Popup styling in broken.

### ISSUE THREAD

**Issue by chetanmadaan** [joomla/joomla-cms#21473]
### Steps to reproduce the issue
Go to Content >> Categories.
Make sure you have a category and then check the checkbox.
Click batch icon.
You see a popup with broken styling.

### Expected result
com_content (Article Manager Popup is fine)
![image](https://user-images.githubusercontent.com/3968575/43869564-32effd64-9b41-11e8-93dd-c315c50f2ba5.png)

### Actual result
![image](https://user-images.githubusercontent.com/3968575/43869539-140e07ba-9b41-11e8-9d52-8bb1d52ab9b6.png)

### System information (as much as possible)
Joomla! 4.0.0-alpha4

**Comment by ghost** [comment]
Issue confirmed, thanks for Report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21473">issues.joomla.org/tracker/joomla-cms/21473</a>.</sub>

**Comment by infograf768** [comment]
After patching a bit `/administrator/components/com_categories/tmpl/categories/default_batch_body.php`

I can get here:
<img width="835" alt="screen shot 2018-08-16 at 12 03 04" src="https://user-images.githubusercontent.com/869724/44202553-9be71800-a14c-11e8-9f82-b5a07fba19e3.png">


[default_batch_body.php.zip](https://github.com/joomla/joomla-cms/files/2293276/default_batch_body.php.zip)


In fact some styling is also broken elsewhere (batch menu items and also batch articles, but not as bad),
That can be solved a bit as shown above (as back-end template is WIP, I wonder if it is worht it), but remains the fact that if choosing a category or menu item (for all batches) the "Do you want to move the items or make a copy of them? " is always displayed while it should only display for example when a category has been chosen. 

See 3.8.x to see the correct behavior.
Ir goes from `style="display: none;"` to `style="display: block;"`

**Comment by infograf768** [comment]
@dgrammatiko 
Display or not of the `batch-copy-move` id depends on 
`/build/media_src/layouts/joomla/html/batch/batch-WHATEVER.es6.js`

(test here with Firefox)

Can you do something?

**Comment by infograf768** [comment]
We can also use the API and use in the default_batch_body.php this shorther code
```
		<?php if ($published >= 0) : ?>
			<div class="form-group col-md-6">
				<div class="controls">
					<?php echo JLayoutHelper::render('joomla.html.batch.item', array('extension' => $extension)); ?>
				</div>
			</div>
		<?php endif; ?>
```
But we still have the issue with js.

**Comment by dgrammatiko** [comment]
@infograf768 it's a simple fix I'll do a PR later on

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/21697

Closing as we have a patch

**Comment by chetanmadaan** [comment]
I should say, Thank you to everyone involved.
