### ISSUE TITLE
[4.0] Workflows Lacks PostgreSQL Schema

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#21487]
Yet another example of core not really being multi-database friendly or features being rushed to merge.

**Comment by alikon** [comment]
i'd argue the latter  cause  even mysql schema is faulty 🤕

**Comment by wilsonge** [comment]
Do you want to make a proposal @alikon given you are generally the db guru round here?

**Comment by alikon** [comment]
i'll do it .....

p.s
i'm not a db guru i'm just only one that love much more the data than the code 😄

**Comment by wilsonge** [comment]
Thankyou!!

p.s.
good enough for me :P

**Comment by wilsonge** [comment]
This is being managed in https://github.com/joomla/joomla-cms/pull/21520/files
