### ISSUE TITLE
[4.0] [Workflow] Workflows - remove jquery

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21497]
### Steps to reproduce the issue
As the title says. The workflows pr has introduced jquery which people have been working hard to remove :(

**Comment by dgrammatiko** [comment]
@brianteeman where are those scripts?

**Comment by brianteeman** [comment]
On my phone but at least in this file for the transitions

https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_content/tmpl/articles/default.php

**Comment by brianteeman** [comment]
Closed see #21575
