### ISSUE TITLE
[4.0] [Workflow] Fix merge conflicts

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#21518]
This core.js file here https://github.com/joomla/joomla-cms/commit/e1693bd03d64e1a87084117d54a350a179f9bbcb#diff-e774050bb49303e3648065795d20a2d0  has been added - but it's currently in the .es6 file here https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_src/system/js/core.es6.js 

As per @mbabker 's comment here I think we've also reintroduced a removed helper function here https://github.com/joomla/joomla-cms/commit/e1693bd03d64e1a87084117d54a350a179f9bbcb#diff-ef08048c8ad27a319432b478ac0a8c54R109

@bembelimen this is a high priority issue please

**Comment by ghost** [comment]
closed as having Pull Request #21523
