### ISSUE TITLE
[4.0] After Multilang. Sample Data `Error 500`

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21516]
### Steps to reproduce the issue
- Install clean Alpha5
- then 3 Languages

After Installation of Multilang. Sample Data got on 
#### com_content:
`Argument 1 passed to Joomla\Utilities\ArrayHelper::getColumn() must be of the type array, boolean given, called in /administrator/components/com_content/Model/ArticlesModel.php on line 483 `
#### /administrator/index.php
`Expression #13 of SELECT list is not in GROUP BY clause and contains nonaggregated column '.wa.state_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by infograf768** [comment]
@franz-wohlkoenig 
This has been solved by
https://github.com/joomla/joomla-cms/pull/21512

**Comment by ghost** [comment]
Thanks @infograf768 so Nightly tomorrow is fixed and testable.
