### ISSUE TITLE
[4.0] Remove the second (colourful) joomla icon from the menu

### ISSUE THREAD

**Issue by dgrammatiko** [joomla/joomla-cms#21510]
### Steps to reproduce the issue

Go to admin and start resizing the browser on the vertical axis observing the bottom joomla icon.

### Expected result
No lag

### Actual result
The animation cannot be kept in optimal frame rate (budget is 16ms) and thus is sluggish

Here is what it looks like on an i7 last gen macBook Pro:
<img width="1677" alt="screenshot 2018-08-09 at 00 33 15" src="https://user-images.githubusercontent.com/3889375/43926479-b210fff0-9c2a-11e8-9507-e2565ca7b1f6.png">

I guess this will be much worse in lower spec machines.

### Additional comments

Can we just drop the icon altogether?
What is the purpose of having 2 icons in the menu?

Form Follows Function or in other words: please do not add useless things just for prettiness

**Comment by brianteeman** [comment]
It was a very specific part of the branding that the designers and previous UX team and iirc marketing teams all felt was important

**Comment by dgrammatiko** [comment]
Sorry I disagree: marketing and branding is something totally irrelevant in this context since you are already a user of the product. There is no gain from advertising the logo multiple times.
Also take a look on windows or osx, how many times you see the logo? Just 1

**Comment by brianteeman** [comment]
Not saying I agree or disagree

**Comment by brianteeman** [comment]
As the menu is being redesigned again th8is might as well be closed until then
