### ISSUE TITLE
Able to set week-start on calendar form field type

### ISSUE THREAD

**Issue by pixxelfactory** [joomla/joomla-cms#21519]
### Is your feature request related to a problem? Please describe.

At the moment there is no option in the xml-definition of the calendar to set another day than sunday as first-day of week. It would be nice if we can set the day inside the form-xml

### Describe the solution you'd like

Able to freely set the first day of week in the xml, like so for instance:
<field type="calendar" weekstart="monday" name="....

**Comment by brianteeman** [comment]
I "think" it can be set in the language xml

**Comment by infograf768** [comment]
It is set in the language xml
`<firstDay>0</firstDay>` is Sunday for en-GB.
`<firstDay>1</firstDay>` is Monday for French fr-FR

We have no way in core to modify this by an override.

**Comment by pixxelfactory** [comment]
Hmm... ok, i guess we'll stick with the locale-version (our usage would have been to set the layout for a module/component independent of language or website ecc., since we have different administrators who speak different languages, and we want it to be consistent throughout without having to configure each language (often we have sites with 8-10 locales), but i guess the simplest solution would be to write to the locale.xml the same value for all languages).
Thanks anyways!

**Comment by infograf768** [comment]
In fact you can override...
code is in a Layout
`/layouts/joomla/form/field/calendar.php`

`data-firstday="<?php echo JFactory::getLanguage()->getFirstDay(); ?>"`

So I guess you can override that layout in your template
templates/nameoftemplate/html/layouts/joomla/form/field/calendar.php
