### ISSUE TITLE
[4.0] [Workflow] Workflows - status change

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21517]
When trying to change the status of an article clicking on the icon presents a select box BUT nothing is saved. In the console is this JS error
```

Uncaught ReferenceError: listItemTask is not defined
    at HTMLSelectElement.onchange (index.php?option=com_content:618)
onchange @ index.php?option=com_content:618
```

**Comment by wilsonge** [comment]
Ahh that's my bad. I merged a PR from Dimitris removing this the same day I merged workflows (so just an indirect conflict). I've directly fixed this with https://github.com/joomla/joomla-cms/commit/950af9754163480beb8d40dc99d87f35d752ecc9 (haven't tested the functionality is working which may need future issues - but it will fix the immediate JS error)
