### ISSUE TITLE
[4.0] Workflows - Cannot trash an article

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21527]
### Steps to reproduce the issue
Create a workflow as shown in the screenshots in #21525 

Can you see the problem?
I did not create any state with a condition of trashed

Now go to the article list and select any article using this workflow and hit trash on the toolbar

### Expected result
Article is trashed and available to me If I filter the results 

### Actual result
**UPDATE**: Despite getting the trashed success message the article is still there (see movie)
![trash](https://user-images.githubusercontent.com/1296369/43954490-9ea9268a-9c94-11e8-82a1-4731a663bef2.gif)

Can't find it by Filter State as that only shows states that are in use 
<img width="292" alt="chrome_2018-08-10_11-34-52" src="https://user-images.githubusercontent.com/1296369/43953605-778d9ebc-9c91-11e8-9f56-e01dfc03490c.png">

Can't find it by Filter Condition
<img width="358" alt="chrome_2018-08-10_11-35-43" src="https://user-images.githubusercontent.com/1296369/43953657-9531cbb4-9c91-11e8-8870-6aba58353dd8.png">

Because I never created a state that had the condition of trashed

**Comment by brianteeman** [comment]
Updated original post with more information

**Comment by ghost** [comment]
closed as having Pull Request #21532

**Comment by brianteeman** [comment]
Re-opened as the proposed solution was as useful as a chocolate teapot

**Comment by ghost** [comment]
closed as having Pull Request #21629

**Comment by brianteeman** [comment]
Reopened as #21629 was closed

**Comment by ghost** [comment]
closed as having Pull Request ##22393
