### ISSUE TITLE
Workflow - archive - featured

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21529]
The archive button has been removed because the authors of workflow state that its just a view of published (I disagree but that is a different issue) however the featured button still exists and that one definitely is just a view of published.

/me confused

**Comment by HLeithner** [comment]
The Feature button is a field in the database table, so has not much todo with the workflow directly.

**Comment by wilsonge** [comment]
Featured items have a content publishing state of published and a separate featured boolean in the db. archived is a separate publishing state from archived hence it has to use the workflow. It comes down sucky db design (archived really should be a boolean flag to - but moving to that is going to be painful from a b/c perspective). Basically this is expected for now.
