### ISSUE TITLE
Workflows - Delete state

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21521]
### Steps to reproduce the issue
1. Create a new workflow
2. Create a new state and make it the default
3. You now have two states - published and the one you created in step 2
4. Delete the published state

### Expected result
State is deleted without error

### Actual result
State is deleted and you get an error
Table 'joomla_db.array' doesn't exist
<img width="363" alt="chrome_2018-08-10_10-54-26" src="https://user-images.githubusercontent.com/1296369/43951748-d00bc3f8-9c8b-11e8-998b-16df9bee7948.png">

**Comment by ghost** [comment]
Deleting published (not default) State get:

![screen shot 2018-08-16 at 13 20 06](https://user-images.githubusercontent.com/8235763/44205620-406e5780-a157-11e8-8a67-3a60cba1d984.jpg)

State is moved to "Trashed".

**Comment by bembelimen** [comment]
This should fix the issue: https://github.com/joomla/joomla-cms/pull/21579

**Comment by ghost** [comment]
closed as having Pull Request #21579
