### ISSUE TITLE
[Joomla 4 Alpha 5] During installation, trying and install a language pack causes Apache to crash

### ISSUE THREAD

**Issue by padenict** [joomla/joomla-cms#21522]
### Steps to reproduce the issue
1. Install XAMPP
2. Extract Joomla 4 Alpha 5 package in "htdocs"
3. Launch installation
4. When required, choose to "Customize Installation" and try and install a Language pack, i.e. "Italian"

### Expected result
A Language pack should be installed

### Actual result
Apache crashes with following error in logs:
[Fri Aug 10 12:01:05.081166 2018] [php7:notice] [pid 5172:tid 1236] [client ::1:55518] PHP Notice:  Trying to get property '_data' of non-object in C:\\xampp\\htdocs\\joomla4\\installation\\src\\Model\\LanguagesModel.php on line 253, referer: http://localhost/joomla4/installation/index.php?view=remove&layout=default

**Comment by ghost** [comment]
Available Languages are at this Time French, German-DE and Persian.

**Comment by mbabker** [comment]
This one was fixed by https://github.com/joomla/joomla-cms/pull/21413
