### ISSUE TITLE
[4.0] Workflow - transitions

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21525]
I have created what I think is a typical workflow for a magazine (see screenshots) and hit a question

It is possible to have a transitions that go 
All to One
One to Two
Two to Three
Three to Four

But its not possible to have transitions that go
All to One
One to Two
Two to Three
Three to All
or
Three to one, four

The only way to do it is to create 
All to One
One to Two
Two to Three
Three to One
Three to Two
Three to Four

**_Can the "to state" be a multiselect and have an ALL option???_**

<img width="615" alt="chrome_2018-08-10_11-14-12" src="https://user-images.githubusercontent.com/1296369/43952973-6f0aef9e-9c8f-11e8-960c-4257266c998d.png">
<img width="712" alt="chrome_2018-08-10_11-14-23" src="https://user-images.githubusercontent.com/1296369/43952974-6f44ceda-9c8f-11e8-9aeb-f418a3699216.png">

**Comment by bembelimen** [comment]
In theory it could have an "to all" stage, but the problem here is, that you will have a problem with the transition, because imho you name the transition targeting the new stage. So if you change something to "trashed", you would probably name your transition something like "move to trash".

Now if we allow "to all", which is technically no problem, the naming of the transition is not distrinct.

**Comment by brianteeman** [comment]
look at my example above and you will see the problem I think we should resolve.

**Comment by brianteeman** [comment]
It's about ensuring that a workflow can be bidirectional

**Comment by bembelimen** [comment]
I see the problem, I see also the "naming" problem.

My comment was more: that's the reason for the current status, but I'm as always open for good ideas. It's a very small change in code to implement it.

At the moment the target condition is visible, perhaps we should change this to "stage", so we have something like:

Transitionname [stage 1]
Transitionname [stage 2]
Transitionname [stage 3]
