### ISSUE TITLE
[4.0] Impossible to sort any list when clicking on column heading

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#21524]
As title says
### Js error

TypeError: self.getAttribute is not a function in searchtools.js 145:29

@dgrammatiko

**Comment by infograf768** [comment]
Ok, found the culprit
code should be
```
          var newOrderCol = this.getAttribute('data-order');
          var newDirection = this.getAttribute('data-direction');
```

will make patch

**Comment by infograf768** [comment]
hmm
using npm install with a modified searchtools.es6.js where I have
const newOrderCol = this.getAttribute('data-order');
 const newDirection = this.getAttribute('data-direction');

creates a searchtools.js with
var newOrderCol = _this.getAttribute('data-order');
var newDirection = _this.getAttribute('data-direction');

I.e. an underscore is added...

although we have in the es6 file
const self = this;
self does not work either.

@dgrammatiko 
I am lost

**Comment by dgrammatiko** [comment]
This should work:
```js
item.addEventListener('click', (event) => {
  // Order to set
  const newOrderCol = event.target.getAttribute('data-order');
  const newDirection = event.target.getAttribute('data-direction');
  const newOrdering = `${newOrderCol} ${newDirection}`;
```

Obviously `this` is the class so it won't work on this case as we want to fetch the attributes of the element clicked. And obviously you have to blame me for this 😓

**Comment by infograf768** [comment]
That's it. making patch now.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/21539

**Comment by ReLater** [comment]
Could you reopen here pls. because the pr is closed without merging?

**Comment by brianteeman** [comment]
Reopened as requested

**Comment by infograf768** [comment]
Closed as we have patch
https://github.com/joomla/joomla-cms/pull/21562
