### ISSUE TITLE
[4.0] Workflows - Status, State and Transition

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21531]
Create a workflow as shown in the screenshots in #21525

Here we can see two articles - they both have a status of unpublished as can be seen by the X icon and have a state of author and graphics
<img width="212" alt="chrome_2018-08-10_12-03-38" src="https://user-images.githubusercontent.com/1296369/43954787-ae70c0ae-9c95-11e8-9055-8f16384a1191.png">

The problem/confusion comes when you try to change that.
<img width="197" alt="chrome_2018-08-10_12-06-30" src="https://user-images.githubusercontent.com/1296369/43954829-d8996778-9c95-11e8-8fe4-ab5335704e5a.png">

Here we can see the current state (author) and while I expected to see a list of states I can see a list of available transitions with their associated status
<img width="197" alt="chrome_2018-08-10_12-06-30" src="https://user-images.githubusercontent.com/1296369/43954874-071e6d6e-9c96-11e8-82e0-7a35dd260beb.png">

At no point does anything tell me that under the heading of status I am being shown a combination of status, state, transition all in the same cell.

Now when I select the available option (Stage 1) the list view changes to show me that the status of this item is now Graphics - not Stage 1 which is what I selected
<img width="234" alt="chrome_2018-08-10_12-10-13" src="https://user-images.githubusercontent.com/1296369/43955005-65bf449c-9c96-11e8-8510-ab8f3523adc8.png">

The problem/confusion is that I am selecting an apple and joomla tells me I have a fruit cocktail. As I was the person that setup the workflow I could work out what was happening but if you dont have the access to the entire workflow then you would be very confused

**Comment by bembelimen** [comment]
What do you suggest?

**Comment by ggppdk** [comment]
@brianteeman 

Does the title of this issue need to be changed to
Status, Stage, Transition ?

@bembelimen 

My personal opinion is 

At Status column there is still the icon that corresponds to the current "Condition" of the article
let's move the display of stage name into a new column called:

Workflow Stage

Thus we will have 2 columns the
- "Status" that shows 2 things **Featured flag** + "**Condition**" via an icon (published, unpublished, archived, trashed)
- "Workflow stage" that show the "Stage" by displaying its name

**Comment by brianteeman** [comment]
@ggppdk I trust your first comment was just a a bad joke - otherwise it was a complete waste of time

**Comment by brianteeman** [comment]
@bembelimen I am not sure - I need to think about options that make sense both with the default workflow naming and with any custom naming as in my screenshot.

I will look at this after the sprint

**Comment by ggppdk** [comment]
@ggppdk

Even if i wrote something stupid, even if i am wrong, or if i misunderstood something
even if i know nothing about english language,
even if i am a total idiot 

you could explain what you mean instead of being rude for no good reason
i really hope that your comment was a joke, and nothing else

**Comment by ggppdk** [comment]
@brianteeman 

Even if i wrote something stupid, even if i am wrong, or if i misunderstood something
even if i know nothing about English language,
even if i am a total idiot 

you could explain what you mean instead of being rude for no good reason
i really hope that your comment was a joke, and nothing else
