### ISSUE TITLE
[4.0] Workflow - save as copy

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21535]
Save as copy has always saved as an unpublished item

With workflows out of the box without any changes it now saves as a published item

I am guessing because that is the default state in the default workflow.

Not saying if I think this change is good or bad but it absolutely must be documented as it will change the way that people work and the expected behaviour

**Comment by ggppdk** [comment]
It is better to be make a small fix for this and save it as unpublished,

since usually the new record is unfinished content, that needs extra time and work to be finished

**Comment by bembelimen** [comment]
@ggppdk there is no guaranteed unpublished stage. The article should get the workflow assigned by the category and from there the default stage (because it has to walk through the workflow, too)

And yes, it needs very proper documentation!

**Comment by ggppdk** [comment]
i see

then what about having a default configuration of workflow that would behave like before ?

and then if someone modifies the default configuration of stages and transitions, etc
then one should be responsible to configure this too

also different but related question
what about if a category has 2 default stages ?
- a default stage for people with core.edit.state on the category
- a default stage for people without core.edit.state on the category

good idea ? possible ?
is this been worked in some PR already ?

**Comment by brianteeman** [comment]
That's what I meant in another issue that workflows is  ignoring the acl

**Comment by infograf768** [comment]
IMHO, it is extremely important that save2copy behaves as before i.e. item saved as Unpublished.
We also use this in com_associations.
If it is impossible to force this because of the category workflow, an alert/warning should be displayed.

**Comment by ggppdk** [comment]
I am thinking 

as said by @bembelimen 
there is no guaranteed 'unpublished' stage

why not add the 2 default stages instead of 1 default stage (if possible as said above)
- default for users **with** core.edit.state on category
- default for users **without** core.edit.state on category

and then 'Save as copy' will use the default stage 'of not having core.edit.state',
thus it will work for default workflow configuration
and if someone has a customized workflow configuration, then it will behave in a similar way

**Comment by Bakual** [comment]
While I understand the idea and requirement of a default workflow stage, it brings a lot of issues like this. There is also the issue that you can't choose the initial stage of an item when you create it, which brings its own issues.

Imho the only way to address this is to set a default workflow stage per state (at least for unpublished and published, ideally for all four possible states).
This way save2copy could use the default unpublished stage and when someone creates an article and has permission to publish it, he can directly publish it without going through each workflow stage first.

**Comment by brianteeman** [comment]
I don't understand why the ability to select a stage is not present all the time and I don't understand why there has to be a default. This is overcomplicating things for a reason I am yet to understand

**Comment by Bakual** [comment]
I guess one reason is that at the time you create an article, you don't even know what workflow you will use. Because that depends on the category. This would need code similar to custom fields where the form is reloaded once you change the category.
For save2copy, you will somehow have to know what stage equals to "Unpublished", as there may be multiple stages with that state 0.

**Comment by brianteeman** [comment]
Yes I wrote the same thing on another issue

**Comment by brianteeman** [comment]
It was #21547

**Comment by Bakual** [comment]
Indeed 👍

**Comment by bembelimen** [comment]
I fully agree about a com_fields solution (Ajax + show initial stage) and perhaps multiple starting points.
I think this would solve a lot of issues user have here. I think I have a good solution for it, but one step after another.

One thing I completely disagree: save2copy to unpublished in every case. I think now we have the opportunity to be flexible as hell and give the users something they can decide. So the user should decide what he/she wants. But we should always deliver a default, so he/she does not have to decide.

**Comment by brianteeman** [comment]
Sorry @bembelimen I am losing track of the workflow issues - did you write the ajax solution?
