### ISSUE TITLE
Workflow - States Ordering

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21537]
### Steps to reproduce the issue
With the default install you can change the sort order of the states. Here I changed them to be alphabetical
<img width="383" alt="chrome_2018-08-10_14-05-29" src="https://user-images.githubusercontent.com/1296369/43959404-a0c90e32-9ca6-11e8-8969-288fc097516d.png">

However that order is not used in the select lists
<img width="219" alt="chrome_2018-08-10_14-05-11" src="https://user-images.githubusercontent.com/1296369/43959445-c5dedbfc-9ca6-11e8-8095-09098ea48600.png">

**Comment by ghost** [comment]
closed as having Pull Request #21705
