### ISSUE TITLE
Workflow - archive menu filter on state

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21534]
### Steps to reproduce the issue
Create an additional workflow
Create a new menu item of type archive

### Expected result
In the list of states they would be displayed with some sort of divider between the workflows. Remember the name of a state is not unique across workflows. So if you have two workflows with the same name for all states but they actually mean something different you dont know what to select

Also as workflows are assigned to categories and you have to select the categories  then it would make sense to update the list of available states based on the workflow assigned to that category or categories
![archivemenu](https://user-images.githubusercontent.com/1296369/43957954-94d99eac-9ca1-11e8-9e36-4e211f7d0d55.gif)

**Comment by brianteeman** [comment]
Just spotted that in the batch modal for articles it is at least displayed as a grouped list

<img width="266" alt="chrome_2018-08-10_13-31-37" src="https://user-images.githubusercontent.com/1296369/43958013-cdb99006-9ca1-11e8-95ad-749692df5826.png">

**Comment by bembelimen** [comment]
ould be solved by https://github.com/joomla/joomla-cms/pull/21701

**Comment by ghost** [comment]
closed as having Pull Request #21701
