### ISSUE TITLE
Workflow - associate content to another languuage

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21536]
### Steps to reproduce the issue
On a multilingual site when you open the modal list of available articles in the other language to be associated the status column is empty

<img width="427" alt="chrome_2018-08-10_14-00-01" src="https://user-images.githubusercontent.com/1296369/43959179-db312376-9ca5-11e8-9ad0-1185d05ee2d0.png">

**Comment by infograf768** [comment]
Looks like this has been solved.
<img width="1262" alt="screen shot 2018-08-18 at 11 59 12" src="https://user-images.githubusercontent.com/869724/44298158-2ca12d80-a2de-11e8-9a9e-22e7cd2d5076.png">

closing
