### ISSUE TITLE
Custom Field Type List blank when more than 10 list values

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21530]
### Steps to reproduce the issue
In backend menu Users -> Fields, Create New Custom Field Type List and add more than 10 values to the list.

### Expected result
In frontend, login and edit user profile and select the Custom Field dropdown with created values, I would expect list of all values to be shown.

### Actual result
Only current selected value is shown - rest of list shows blank fields.

### System information (as much as possible)
Joomla 3.8.11
PHP 7.0.31

### Additional comments
Works fine when editing user profile in backend.
If only 10 fields are created in the list, it shows fine in frontend.
My first ever bug report - please accept my apologies if bugreport is incomplete or missing information.

**Comment by ReLater** [comment]
I cannot confirm this issue with `Joomla! 3.8.12-dev Development [ Amani ]`.

![10-08-_2018_16-48-34](https://user-images.githubusercontent.com/20780646/43965235-103a5272-9cbf-11e8-9732-6185de32cee6.jpg)

Could you please test with this list again?
![10-08-_2018_16-47-36](https://user-images.githubusercontent.com/20780646/43965256-1af64e5a-9cbf-11e8-8c71-5f2b59747622.jpg)

> rest of list shows blank fields

Did you check if the texts are present in HTML source code or just not displayed.^

![10-08-_2018_16-57-27](https://user-images.githubusercontent.com/20780646/43965275-224763ba-9cbf-11e8-8c06-355b842396f6.jpg)

Pls. make a screenshot of your text/value pairs.

**Comment by ghost** [comment]
Just checked - the code is in the HTML, and also just tried to switch to different template, where it works as supposed to!

I'm very sorry, that I didn't check this - was stuck in the idea that since it worked with 10 values, it had to be a bug since it was not working with 11+ values.

Appreciate all your great work - will do mine a bit better next time ;)

Thanx a lot for taking the time.

Cheers<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21530">issues.joomla.org/tracker/joomla-cms/21530</a>.</sub>
