### ISSUE TITLE
Workflow - archive

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21533]
The workflow team have stated that we don't need Archive as all it was is a way to view content with a date filter. But it is so much more than that. Hopefully this video will help to explain better how the current archive view works and if you try to replicate that with the current Joomla4 with workflows it is not currently possible

https://youtu.be/4Dy9QoCeDsE

**Comment by HLeithner** [comment]
https://github.com/joomla/joomla-cms/pull/21585 reintroduce the possibility of archive and other states for other components.

**Comment by brianteeman** [comment]
Not quite - you need to update the modules that were changed as well

**Comment by HLeithner** [comment]
Thats the second step, the Pr introduce the possibility to do this.

**Comment by brianteeman** [comment]
Closed
