### ISSUE TITLE
[4.0] Status broken when using multilingual associations

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#21540]
### Steps to reproduce the issue
Set up a multilingual site
Load the Multilingual Associations component.
Choose Articles and a language

### Result
The Status Column in the manager is unchanged versus pre-workflow.

Editing in side by side may show an empty Status field for the Reference and no Status fied at all for a new Target

**Comment by infograf768** [comment]
EDIT: No status field for a reference article means that the article is not added to the workflow_associations.

**Comment by brianteeman** [comment]
Is there any work being done on this?

**Comment by infograf768** [comment]
Since this issue was posted, we have different problems.
Some depending on workflow implementation in the Multilingual sample data and blog sample data.
Other depending on the merging of https://github.com/joomla/joomla-cms/pull/21180 which has not been ported yet to 4.0

**Comment by brianteeman** [comment]
There may be additional issues but the one you reported here is still an issue

**Comment by ghost** [comment]
Using clean Nightly Build Status in com_associations and editing in side by side show expected Status.
#### System Information

Setting | Value
-- | --
PHP Built On | Linux lamp129.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.5.el6h.x86_64 #1 SMP Thu Nov 22 10:07:47 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.23-cll-lve
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.7
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 4.0.0-alpha11-dev Development [ Amani ] 29-June-2019 11:27 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by ghost** [comment]
@infograf768 can this be closed?

**Comment by infograf768** [comment]
@franz-wohlkoenig let me have a look.

**Comment by infograf768** [comment]
Indeed can be closed.
