### ISSUE TITLE
Cron finder_indexer.php add "http://domain.com" to all links as HTTP_Host

### ISSUE THREAD

**Issue by Flocke28** [joomla/joomla-cms#21549]
### Steps to reproduce the issue

In Line 114 set HTTP_HOST = domain.com. 

Why? All Links in the Smart Search are wrong.

**Comment by brianteeman** [comment]
The reason is written on line 113

I just ran the script and dont see any problem - can you please explain more what you are seeing

<img width="813" alt="heidisql_2018-08-11_09-06-11" src="https://user-images.githubusercontent.com/1296369/43989631-d241ace0-9d45-11e8-8c76-c8a9f1f76afd.png">

**Comment by Flocke28** [comment]
I have  installed easyblog. All blog entries starts with http://domain.com in route

**Comment by brianteeman** [comment]
As it does not happen with the core joomla content I suggest that you contact the makers of easyblog for advice

**Comment by Flocke28** [comment]
Example![screen shot 2018-08-11 at 08 29 09](https://issues.joomla.org/uploads/1/c25d346a2875639f314ea97470526a6d.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21549">issues.joomla.org/tracker/joomla-cms/21549</a>.</sub>

**Comment by ghost** [comment]
closed as no Core Issue. It can alqays reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21549">issues.joomla.org/tracker/joomla-cms/21549</a>.</sub>
