### ISSUE TITLE
[4.0] Workflow - batch and multilingual associations component

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21541]
### Steps to reproduce the issue
Use the batch functionality to copy articles to another category

I thought batch wasnt working at all because even though it said success the articles were not there.
But after a new install with multilingual and trying again I noticed that the mutlingual associations component was reporting more articles.

Checking the database I can see that batch process IS WORKING but something else in workflows is preventing the articles from being found. 

Checking the database table _workflow_associations I can see that there are only 5 records so I think we can assume that there are two problems presented here.
1. Batch is not creating a record in the database table _workflow_associations so com_content doesnt think the articles exists
2. Multilingual Associations component is not querying the the database table _workflow_associations to decide what content to display

<img width="322" alt="heidisql_2018-08-10_15-42-33" src="https://user-images.githubusercontent.com/1296369/43964687-506a1558-9cb5-11e8-899d-0aab23a7685b.png">
<img width="275" alt="heidisql_2018-08-10_15-48-49" src="https://user-images.githubusercontent.com/1296369/43964688-5087d480-9cb5-11e8-8aa6-5f3b5748e8bd.png">

**Comment by ghost** [comment]
closed as having Pull Request #22104
