### ISSUE TITLE
[4.0] Status field does not display before Save

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#21547]
### Steps to reproduce the issue
Create a new Article.
As there is no Status field before Save, the default depends on the workflow settings.

Normally, for example ( https://github.com/joomla/joomla-cms/issues/21535 ), save2copy will save as Unpublished which would mean we have to set the default Workflow state to Unpublished.
(Note: save2copy is also used in Multilingual Associations componebt in the side by side window.)

The consequence is that we can't Save and Close directly a new article. One has always to re-edit the article after a Save.

**Comment by brianteeman** [comment]
I agree. I don't see the value of it not being present until saved. It should be present and show the available options for that user. 

The "difficulty" and I suspect the reason why it isn't there is that the workflow is dependent on the category selected so how do we know what to show here before it is saved. However this has already been solved by com_fields so shouldn't be a problem.

**Comment by chmst** [comment]
I agree that is is confusing if there is nothing to see. 
Maybe show the stage field disabled with a hint "Please select a category"?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21547">issues.joomla.org/tracker/joomla-cms/21547</a>.</sub>

**Comment by infograf768** [comment]
And how would you know the specific workflow of a category if no AJAX magic here?

**Comment by chmst** [comment]
Not without a list of categories and workflows/states.
But to make it simple: The hint could say "stage can be changed after save". So at least it would be less confusing.

**Comment by brianteeman** [comment]
I definitely prefer the ajax solution although we do have something similar to @chmst solution in the menus

![image](https://user-images.githubusercontent.com/1296369/45213368-40adce80-b28f-11e8-9a74-9e22098200b3.png)

**Comment by infograf768** [comment]
After save IS the issue. It means we never can use Save & Close with workflow.

**Comment by bembelimen** [comment]
See: https://github.com/joomla/joomla-cms/pull/23458

**Comment by brianteeman** [comment]
This should be closed as fixed elsewhere
