### ISSUE TITLE
[RFC] Simplify our tooling

### ISSUE THREAD

**Issue by rdeutz** [joomla/joomla-cms#21545]
## Current situation
We have a lot tools and scripts doing this and that. Most of the time only a few people know what this scripts are and if they are needed at all. Furthermore we have the new situation that a clone from the repository isn't installable.

## How to solve the tooling jungle
We already have robo.li (https://robo.li/) and using it for some tasks. I have started to move some of the Testing Task into Robo (https://github.com/joomla-projects/robo-joomla). It comes with a lot of build in tasks for making releases. It would be great if we could make tasks for package a release and steps around making a release. This will be needed for the PR testing platform and will also help the release leads.   

## Next steps

1) We need to now what tools and scripts we are using.
2) Move and document scripts

## Goal
One tool to rule them all (might not 100% possible because of node, but we can have a robo task to call npm)

**Comment by brianteeman** [comment]
Not really sure what you are expecting anyone to say here.

**Comment by mbabker** [comment]
If you want to use it for new things, go ahead.  We already have working tools and scripts for other tasks, unless refactoring them is going to be more maintainable under Robo I don't see the benefit in yet another change for the sake of change.

**Comment by HLeithner** [comment]
I rewrote my component packaging today from phing to robo and its so much simpler now ;)

If you need help just say what todo because i have no overview.

**Comment by rdeutz** [comment]
@brianteeman request for comments doesn't mean you have to comment

@mbabker the goal is to have more people able to use and to maintain our tooling, I have better things to do as change something that doesn't need a change

@HLeithner for a start https://github.com/joomla-projects/robo-joomla/projects

**Comment by brianteeman** [comment]
@rdeutz I kow understand why you posted th8is here - I had thought it would be better to have been in a productin chat

**Comment by brianteeman** [comment]
Is this still an "under discussion" item?

**Comment by HLeithner** [comment]
Yes it is and in testing hannes is already doing some work.

Edit: Wrong ticket, yes it still a topic

**Comment by brianteeman** [comment]
Sorry I obviously wasn't clear - Is this still under discussion **and needs to remain open**

**Comment by HLeithner** [comment]
Yeah I don't think so by lack of interest
