### ISSUE TITLE
Workflow - Filter state

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21542]
Before workflows it was possible to list ALL articles no matter the state
Now you can only select articles for a specific condition

<img width="262" alt="chrome_2018-08-10_15-54-11" src="https://user-images.githubusercontent.com/1296369/43964897-c238fc08-9cb5-11e8-8047-a019310a6bf4.png">
<img width="232" alt="chrome_2018-08-10_15-54-28" src="https://user-images.githubusercontent.com/1296369/43964898-c2506258-9cb5-11e8-9066-f1b088ba975d.png">

**Comment by ghost** [comment]
closed as having Pull Request #21704
