### ISSUE TITLE
[4.0] Newsflash image parameter doesn't display Intro images

### ISSUE THREAD

**Issue by htmgarcia** [joomla/joomla-cms#21546]
### Steps to reproduce the issue
- Create an "Article - Newsflash" module
- Enable **Images** (be sure one of the listed articles has indeed an intro image)
- Preview the module in frontend

### Expected result
I would expect the article's intro image would be visible, however only the images included inside article body are displayed (if any).

### Actual result
The article's intro images are not visible.

### System information (as much as possible)
Joomla 4.0 alpha 5-dev

### Additional comments
Tested with the default layout (from Advanced > Layout)

**Comment by ReLater** [comment]
It's the same behavior like in earlier Joomla versions. `Setting images: Yes/No` means: Display images or not that are embedded inside editor text.

**Comment by ReLater** [comment]
This feature will come in Joomla 3.9: https://github.com/joomla/joomla-cms/pull/20169

I (just) think that it will be ported then to Joomla 4, too.

**Comment by brianteeman** [comment]
Yes it will be merged into 4 but it will take some time until @wilsonge catches up.

**Comment by htmgarcia** [comment]
Cool! Thanks @brianteeman @ReLater
