### ISSUE TITLE
Performance of mod_logged

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#21555]
### Steps to reproduce the issue

System with large number of guest sessions very slow.
Also query does not use ORDER BY so no guarantee last X logged in users will be shown.

### System information (as much as possible)

Joomla 3.8.10
MySQL 5.5.52

### Additional comments

Suggest changing WHERE clause in getList() method in ModLoggedHelper  to
$query = $db->getQuery(true)
		->select('s.time, s.client_id, u.id, u.name, u.username')
		->from('#__session AS s')
		->join('LEFT', '#__users AS u ON s.userid = u.id')
		->where('s.userid > 0')	// Added, uses existing index
		->where('s.guest = 0')
		->order('s.time DESC');	// Added, guarantees last X rows returned

**Comment by BrainforgeUK** [comment]
This issue also affects mod_status.
Need to add userid > 0 clause to all guest = 0 conditions

Putting an index on the 'guest' column will resolve this issue in both cases.
Could this be a better method that changing the code?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21555">issues.joomla.org/tracker/joomla-cms/21555</a>.</sub>

**Comment by Quy** [comment]
Maybe PR #19708 will help too.

**Comment by SharkyKZ** [comment]
Remove `WHERE` clause and replace `LEFT JOIN` with `INNER JOIN`.

**Comment by alikon** [comment]
@franz-wohlkoenig can be closed as we have a pr #23650
