### ISSUE TITLE
[4.0] change category workflow

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#21552]
### Steps to reproduce the issue
set a new Workflow
create a new category  and set to the new Workflow
create an article  on that category
edit that category and switch back to the joomla default workflow

### Expected result
edit that article
you should see the default joomla workflow  for the article in that category or you should be able to switch to the default one 

### Actual result
the articles still belongs on the old Workflow category and there is no way to change it

![screenshot from 2018-08-12 09-10-36](https://user-images.githubusercontent.com/181681/43999593-c2bb3712-9e0f-11e8-967f-5deeb5896f95.png)

### Additional comments
çannot repeat here

**Comment by brianteeman** [comment]
Shakes head in dismay

**Comment by bembelimen** [comment]
Why should the workflow change, only because you change the category?

If you have assigned a workflow and then brought the article to published, why should you go through another workflow again, just because you change the category?

If you want to change to workflow you can do this with the appropriate function.

**Comment by brianteeman** [comment]
> Why should the workflow change, only because you change the category?

 if someone can change something then you can guarantee that they will. 

> If you have assigned a workflow and then brought the article to published, why should you go through another workflow again, just because you change the category?

Who said it was published? Even then you might have a completely different workflow

> If you want to change to workflow you can do this with the appropriate function.

Well at least one person expected that changing the category would do it. And as the states and transition names are not unique they might not even realise that what they expected to happen has not

**Comment by alikon** [comment]
> Why should the workflow change

things changes  often  (even the workflow)..... there are a lot of reason for this  and i left this to your imagination

p.s
no i haven't changed the category associated to the article

**Comment by Bakual** [comment]
> Why should the workflow change, only because you change the category?

As an example: User A isn't allowed to publish in category A, but he is allowed to do so in category B. So it's fine when he goes through the workflow in category B to get the article published and then changes the category to A?
See what he did there? Bypassed workflow ACL like a hacker.

Either changing categories isn't alllowed (booooh!) or changing the category means changing the workflow. Of course it's not nice to reset the workflow, but assuming there are different workflows for a reason (eg different people need to approve) then it's actually the right thing to do so the right people can approve the article.
I'd say if the workflow is the same for both categories, then it's fine to not reset it.

**Comment by alikon** [comment]
based on ACL (like a superadmin)  to me sounds right & legit that i can change category and/or workflow... better i shoud be able to change everything , why I should not ? if i have the (full/right) permission

**Comment by brianteeman** [comment]
This is just one example of how the entire workflow code is not written with real joomla use in mind. The only realistic way with this code is to only allow one workflow on a site.

**Comment by bembelimen** [comment]
So let's take Joomla! 3:
A user group with the following permissions:
- admin login: yes
- access com_content admin interface: yes
- create article: yes
- edit own: yes

create 2 categories with the following permissions for the user group:
category 1:
- everything on inherit

category 2:
- edit state: yes

=> Create a new article in category 1 => article is unpublished and state cannot be changed
=> Create a new article in category 2 => article is unpublished and state can be changed => set to published + change to category 1 => save => article is published in category 1

So where is the difference? As always requested...it's the same behavior as in J! 3...

**Comment by brianteeman** [comment]
You are once again confusing ACL and Workflow and forgetting that you can create much more complex (and multiple) workflows now  than you could before

**Comment by brianteeman** [comment]
In this short movie you can see that if category 1 and category 2 have different permissions when content is moved between those categories then the permissions change on the content as they are moved.
![category](https://user-images.githubusercontent.com/1296369/44936625-686fd480-ad6d-11e8-936c-2763e6d6be5f.gif)

**Comment by alikon** [comment]
obviously lack of interest<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21552">issues.joomla.org/tracker/joomla-cms/21552</a>.</sub>
