### ISSUE TITLE
[4.0][Workflow] - create new article

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#21565]
### Steps to reproduce the issue
create a new article save&close

### Expected result
article created and listed in articles manager

### Actual result
![screenshot from 2018-08-12 11-56-58](https://user-images.githubusercontent.com/181681/44000817-eba7faea-9e26-11e8-8911-450ca63393ed.png)

**Comment by wilsonge** [comment]
PR already for this https://github.com/joomla/joomla-cms/pull/21566

**Comment by brianteeman** [comment]
I am re-opening this because it is not fixed by 21566

**Comment by HLeithner** [comment]
did you recreated the autoloader?

**Comment by brianteeman** [comment]
No - why should I - its not in the test instructions anywhere

**Comment by brianteeman** [comment]
But even recreating the autoloader makes no difference

**Comment by mbabker** [comment]
Recreating the autoloader only affects namespaced code.  It will not magically fix JHtml class issues because JHtml helpers are not namespaced.

**Comment by brianteeman** [comment]
I thought it was like posting the fpa - and it magically fixed everything

**Comment by wilsonge** [comment]
Think this should be fixed again. If you could close it @brianteeman when you've had time to test

**Comment by brianteeman** [comment]
all good for me - now

@alikon when you confirm I will close this (hopefully)

**Comment by alikon** [comment]
seems ok to me too closing
