### ISSUE TITLE
Editor (tinyMCE) field type height and width are not overiding the plugin's height/width options.

### ISSUE THREAD

**Issue by jghansen** [joomla/joomla-cms#21567]
I am in the process in creating a custom component and using the field type editor. One the attributes of this field is height. The attribute does not take precedent. 
[Using this document on the field type's options](https://docs.joomla.org/Editor_form_field_type "Editor Field Type")

### Steps to reproduce the issue
1. Add editor field type to a form xml file: <field type="editor" ... height="150px" .. />
2. Display the field.

### Expected result
The tinyMce editor size should be 150px and it is not. The tinyMce editor options are set to 550px for height.

### Actual result
It defaults to the editor's advanced options (height and width) when it should not.

### Additional comments
![screen shot 2018-08-12 at 15 45 45](https://issues.joomla.org/uploads/1/fb3d01af980c570f3cbb770116e86769.png)
The screen shot shows help that define the height is only usable when the tinyMCE is in the Advanced or Extended mode. These options are no longer available in the current version of tinyMCE used by Joomla.

**Comment by Quy** [comment]
Duplicate #14835 ?

**Comment by ghost** [comment]
closed as duplicate Report #14835.

Thanks for Hint, @Quy <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21567">issues.joomla.org/tracker/joomla-cms/21567</a>.</sub>
