### ISSUE TITLE
Module -> Articles - Latest -> Featured Articles -> Show NO SHOW

### ISSUE THREAD

**Issue by hostanet** [joomla/joomla-cms#21576]
### Steps to reproduce the issue
When in Module Articles - Latest set Featured Articles to Show. There is no articles on the page which are assigned as Featured.

### Expected result
Featured Articles listed in mentioned Module

### Actual result
No show. Only articles without (star) are listed.

### System information (as much as possible)
Joomla 3.8.11.

 OS Linux p
 PHP 7.0.30-0ubuntu0.16.04.1
 MySQLi 5.7.23-0ubuntu0.16.04.1-log

### Additional comments
Result is the same as select Hide.![screen shot 2018-08-12 at 20 32 41](https://issues.joomla.org/uploads/1/aadb6361894d146d97338818c14170f7.png)
Only option to show Featured Articles is 3rd option (Only Show Featured Articles).

**Comment by Quy** [comment]
Reported/fixed in #21336 and will be available in 3.8.12.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21576">issues.joomla.org/tracker/joomla-cms/21576</a>.</sub>
