### ISSUE TITLE
Joomla "unable to handle this request" HTTP error 500 t

### ISSUE THREAD

**Issue by brandxero** [joomla/joomla-cms#21570]
### Steps to reproduce the issue
I lost my connection in the proces of updating my joomla site. Now i cant log in my adminstrator panel. it shows Joomla 3.8.0 "unable to handle this request" HTTP error 500.
Please i need help :(

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.
