### ISSUE TITLE
[4.0] Update: `Files Install: Custom install routine failure.`

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21580]
### Steps to reproduce the issue
Use Update "Nightly Build" or "Upload & Update": After Installation of "Joomla_4.0.0-alpha5-dev-Development-Update_Package.zip" got `Files Install: Custom install routine failure.`

![Screen Shot 2019-03-31 at 08 24 39](https://user-images.githubusercontent.com/8235763/55285621-ac709980-538f-11e9-85c1-f52353a52d40.png)

### Expected result
Both Ways "Nightly Build" and "Upload & Update" should Update successfully.
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by ghost** [comment]
also https://github.com/joomla/joomla-cms/issues/21435#issuecomment-412260021

**Comment by ghost** [comment]
Is it possible that the Update is done as expected and Warning can be ignored? This would be helpful instead of every Day terminate and install J4 new.

**Comment by Scrabble96** [comment]
This is still an issue in:

- Nightly build: Joomla! 4.0.0-alpha7-dev (11th/12th January 2019)
- Cassiopeia template
- Windows 10 32bit
- Firefox 64.0.2
- 

**CloudAccess.net**
PHP 7.1.25
Apache server
MySql 5.7.24-cll-lve

**Comment by ghost** [comment]
Updated Screenshot in opening Thread to show all Warnings, Notices, ...

**Comment by ghost** [comment]
Closed as no Core-Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21580">issues.joomla.org/tracker/joomla-cms/21580</a>.</sub>
