### ISSUE TITLE
Joomla 4.0 installation fails on mysql 5.5

### ISSUE THREAD

**Issue by dmitriy-cloudaccess** [joomla/joomla-cms#21582]
### Steps to reproduce the issue
Run DB installation script https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/sql/mysql/joomla.sql on mysql 5.5

### Actual result
Mysql fails with: ERROR 1067 (42000) at line 1943: Invalid default value for 'created'

### System information (as much as possible)
Mysql version 5.5.59

### Additional comments
Mysql 5.5 doesn't accept default value `NOW()` for `datetime` columns.
Like https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/sql/mysql/joomla.sql#L1951
On mysql 5.7 it works correctly.

**Comment by brianteeman** [comment]
A possible fix is to change the column type to timestamp not datetime and adding a trigger

**Comment by alikon** [comment]
or simply use the normal  default `DEFAULT '0000-00-00 00:00:00',`

**Comment by brianteeman** [comment]
@alikon I was assuming that there was a reason for the NOW()   :)

**Comment by HLeithner** [comment]
Mysql 5.5 is EOL on release of J4 but I'm note sure if the minimum version is pumped to 5.6.

**Comment by HLeithner** [comment]
@alikon can you do this in you mysql PR?

**Comment by alikon** [comment]
yes i'll do when the state/stage will end

**Comment by brianteeman** [comment]
It may be EOL but the technical requirements are
https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4

**Comment by HLeithner** [comment]
thx for the link

**Comment by wilsonge** [comment]
Mainly because over 50% of our user base still use MySQL 5.5 https://developer.joomla.org/stats/

**Comment by hvdmeer** [comment]
From what time frame are those statistics? From the start of gathering or perhaps from the last year?

**Comment by mbabker** [comment]
The API endpoint is all time.  It is still 50% for data updated in the last 90 days.

**Comment by ReLater** [comment]
See pr https://github.com/joomla/joomla-cms/pull/21600

**Comment by wilsonge** [comment]
Closing as we have the PR for testing
