### ISSUE TITLE
[4.0] com_workflow: Transitions `syntax error, unexpected ';', expecting ',' or ')' `

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21586]
### Steps to reproduce the issue
- Open `/administrator/index.php?option=com_workflow&extension=com_content`
- Click on `/administrator/index.php?option=com_workflow&view=transitions&workflow_id=1&extension=com_content`
![screen shot 2018-08-13 at 13 33 26](https://user-images.githubusercontent.com/8235763/44029483-c7864ef0-9efd-11e8-98f2-40cae42aa318.jpg)
- get
![screen shot 2018-08-13 at 13 33 07](https://user-images.githubusercontent.com/8235763/44029495-d0570c9a-9efd-11e8-8226-6025599b9d0e.jpg)

### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by HLeithner** [comment]
I mention this already in https://github.com/joomla/joomla-cms/pull/21566#issuecomment-412354145 and should be fixed with the PR.

**Comment by ghost** [comment]
thanks @HLeithner for Link but i let Issue open so its reported as own issue.

**Comment by wilsonge** [comment]
Now merged
