### ISSUE TITLE
[4.0] 500 JHtml workflowstage not found.

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21595]
### Steps to reproduce the issue
clean install with current staging at the time of this post
create an article
and bam - thats it you're screwed by the untested broken code in com_workflows

**Just revert the f-ing thing until it actually works and in the meantime the rest of us can get on with joomla 4**

<img width="1101" alt="chrome_2018-08-13_18-41-16" src="https://user-images.githubusercontent.com/1296369/44048318-e985011a-9f28-11e8-8c3d-44675c401643.png">

**Comment by alikon** [comment]
already experienced and reported

-  https://github.com/joomla/joomla-cms/pull/21553#issuecomment-412332528
- https://github.com/joomla/joomla-cms/issues/21565

i'm starting to think that if you want your pr merged,  simple add the word "workflow"  :rofl:

**Comment by mbabker** [comment]
> i'm starting to think that if you want your pr merged, simple add the word "workflow" 🤣

So you're saying if we call it the "privacy workflow system" we can get 3.9 out the door?  :trollface:

**Comment by brianteeman** [comment]
I will close this as a duplicate and take the night off

**Comment by alikon** [comment]
i'm inclined to think so :rofl: 

p.s.
sorry i'm only kidding
