### ISSUE TITLE
npm fail on autoprefixer

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21590]
Anyone else able to replicate this 
npm install failing at current head with 

```
2141 verbose stack Error: UNKNOWN: unknown error, lstat 'C:\htdocs\cms4\node_modules\.bin\autoprefixer'
2142 verbose cwd C:\htdocs\cms4
2143 verbose Windows_NT 10.0.17134
2144 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\brian\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
2145 verbose node v10.4.0
2146 verbose npm  v6.3.0
2147 error path C:\htdocs\cms4\node_modules\.bin\autoprefixer
2148 error code UNKNOWN
2149 error errno -4094
2150 error syscall lstat
2151 error UNKNOWN: unknown error, lstat 'C:\htdocs\cms4\node_modules\.bin\autoprefixer'
2152 verbose exit [ -4094, true ]
```

**Comment by richard67** [comment]
I can't replicate this on Linux. Maybe a platform-specific problem?

**Comment by rdeutz** [comment]
does this C:\htdocs\cms4\node_modules\.bin\autoprefixer file exists

**Comment by brianteeman** [comment]
no - first thing I checked
The full log can be found here https://www.dropbox.com/s/oqz98xitb5hbtyv/2018-08-13T15_34_20_191Z-debug.log?dl=0

**Comment by rdeutz** [comment]
on linix node_modules/bin is the path to the executetables so it seems the installation is not complete

**Comment by brianteeman** [comment]
thats what i know ;)

the question is why.

**Comment by brianteeman** [comment]
Looks like it was a filesystem error as a result of using both ubuntu and windows
