### ISSUE TITLE
[4.0] Users menu extra items

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21593]
### Steps to reproduce the issue
The users menu has extra links to workflows and content fields

<img width="312" alt="chrome_2018-08-13_18-09-55" src="https://user-images.githubusercontent.com/1296369/44046710-33bdd220-9f24-11e8-92c5-635098ff9afb.png">

**Comment by ghost** [comment]
Issue confirmed.

**Comment by ghost** [comment]
closed as having Pull Request #21626
