### ISSUE TITLE
Show "Array" in Post-installation Messages for Joomla CMS

### ISSUE THREAD

**Issue by dioubernardo** [joomla/joomla-cms#21594]
### Steps to reproduce the issue
Open /administrator/index.php?option=com_postinstall

### Actual result
In box "Release news from the Joomla! Project" show Array
![image](https://user-images.githubusercontent.com/3487994/44047908-42a93248-9f06-11e8-8c7c-31c49bfd0a35.png)

### System information (as much as possible)

Setting | Value
-- | --
 
PHP Built On | Linux joomla 3.13.0-153-generic #203-Ubuntu SMP Thu Jun 14 08:52:28 UTC 2018 x86_64
Database Type | mysql
Database Version | 5.5.61-0ubuntu0.14.04.1
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 5.5.9-1ubuntu4.25
Web Server | Apache
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 3.8.11 Stable [ Amani ] 31-July-2018 14:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by ghost** [comment]
can't confirm:

![screen shot 2018-08-13 at 20 25 35](https://user-images.githubusercontent.com/8235763/44050443-38c04de4-9f37-11e8-966b-3169105f03c9.jpg)

### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by dioubernardo** [comment]
I noticed that it runs this latest version on a windows server with php 7 and the error does not occur. I think it might have something to do with the PHP version.

**Comment by ReLater** [comment]
> I think it might have something to do with the PHP version.

I cannot confirm with

PHP Version | 5.5.38-nmm2
Database Version | 5.5.58-nmm1-log
Joomla! Version | Joomla! 3.8.11 Stable [ Amani ] 31-July-2018 14:00 GMT

**Comment by Quy** [comment]
@dioubernardo Is this still reproducible?

Please enable `Error Reporting` to `Development` under `Under System > Global Configuration > Server`.
Go to `Components > Post-installation Messages`.
There should be a Notice warning above `Array`.

**Comment by Quy** [comment]
Unable to reproduce. This can be reopened when more information is provided.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21594">issues.joomla.org/tracker/joomla-cms/21594</a>.</sub>
