### ISSUE TITLE
[4.0] Table Error After Update to Nightly Build since 2 days ago

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#21596]
### Steps to reproduce the issue
Today is Aug 13, 2018 and I have this issue since Saturday, Aug 11, 2018 when updating to the latest Nightly Build.

![joomla update - joomla 4 - administration 2018-08-13 11-34-51](https://user-images.githubusercontent.com/1373815/44050797-f0de2630-9eec-11e8-82fe-969379949ce6.png)

So, I went ahead to Database Fixer, select the entry and clicked on Fix. Nothing happened and I still get the Alert that "There are tables not up to date!"

![extensions database - joomla 4 - administration 2018-08-13 11-35-51](https://user-images.githubusercontent.com/1373815/44050974-6ae77472-9eed-11e8-9b33-7647aa11a80d.png)

### Expected result
Should fix the table issue.

### Actual result
Seems like the database fixer is not doing anything.

### System information (as much as possible)

Setting | Value
-- | --
 
Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64 x86_64
mysql
5.5.5-10.2.13-MariaDB
utf8_general_ci
utf8_general_ci
7.2.3
nginx/1.13.9
fpm-fcgi
Joomla! 4.0.0-alpha5-dev Development [ Amani ] 22-July-2018 22:58 GMT
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

### Additional Comments
Going to the Dashboard/Control Panel, I get 500 Error and it breaks the layout.

![error 500 2018-08-13 11-44-21](https://user-images.githubusercontent.com/1373815/44051327-68a89dd4-9eee-11e8-86c1-9898ad6eb519.png)

**Comment by richard67** [comment]
I can confirm this issue for an update. With a new installation it does not happen.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21596">issues.joomla.org/tracker/joomla-cms/21596</a>.</sub>

**Comment by HLeithner** [comment]
https://github.com/joomla/joomla-cms/pull/21566 have fixed hopefully most of the problems.

But the update script will not repair your existing installation, but it should work if you have the old database before upgrading to the nightly 2 days before.
