### ISSUE TITLE
[4.0] Workflow - layout notice

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21599]
### Steps to reproduce the issue
With current status and error reporting at maximum open any plugin

Notice: Undefined property: Joomla\CMS\Object\CMSObject::$id in C:\htdocs\cms4\layouts\joomla\edit\global.php on line 43

https://github.com/joomla/joomla-cms/blob/6c3351e5b3ba38f57452bf7834b3de80b9b90662/layouts/joomla/edit/global.php#L43

<img width="822" alt="chrome_2018-08-13_22-43-13" src="https://user-images.githubusercontent.com/1296369/44059750-48fb6942-9f4a-11e8-9981-3f84a47a8d19.png">

**Comment by ghost** [comment]
Issue confirmed.

**Comment by ghost** [comment]
closed as having Pull Request #21623
