### ISSUE TITLE
****URGENT, PLEASE RESPOND ASAP Class 'G2\L\AppLoader' not found "An Error Has Occurred"

### ISSUE THREAD

**Issue by Inbroch104** [joomla/joomla-cms#21614]
Can't access back end or front end Just get the blue screenas attached![screen shot 2018-08-14 at 14 52 53](https://issues.joomla.org/uploads/1/1ffa355fa593ef06c9b3895207aefb23.png)

Happened when I was installing Chronoforms and playing around with K2.

My whole site has completely shut down.

I'm not an IT guy but have attached what I know the specs to be.

This is going to cost me if I dont gety this up uick!![screen shot 2018-08-14 at 14 58 42](https://issues.joomla.org/uploads/1/c1f28f5d2c4be8ebf07190d9ffa83fc9.png)

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.

**Comment by Inbroch104** [comment]
Love your attitude mate....the time it took you to do all that, you could
have given me a solution.....well done mate.

Dick Head....

**Comment by jeckodevelopment** [comment]
it's so bad to see such a bad comment @Inbroch104 
I doubt people will answer if you use this behavior in an Open Source Project.
