### ISSUE TITLE
[4.0] com_modules: "Batch"-Button don't work

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21619]
### Steps to reproduce the issue
As Title say: Click on "Batch" no Modal opens. Other Buttons like Publish, Trash, ... work as expected.

![screen shot 2018-08-15 at 06 11 36](https://user-images.githubusercontent.com/8235763/44131273-246de344-a052-11e8-9967-7725aee94b35.jpg)

Test on Menue: "Batch"-Button work.
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by infograf768** [comment]
I think it is due to the problem with position as we can't for now create a new position, even when editing a module.
Although I can correct most batch, that one is special.

**Comment by brianteeman** [comment]
I got this error
```
TypeError: Cannot read property 'open' of null
/administrator/index.php?option=com_modules&client_id=0:308
```

**Comment by Quy** [comment]
No longer an issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21619">issues.joomla.org/tracker/joomla-cms/21619</a>.</sub>
