### ISSUE TITLE
[4.0] Question regarding media folder

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#21624]
The media folder is no longer in the root directory. Where in Joomla! can/should a third party extension developer put his js and css files? What is recommended?

**Comment by anuragteapot** [comment]
@astridx I think in  `root/media/` because after the setup of the environment mean after `composer install` and `npm install`  all `build/`  folder files compiled and put in `root/media/` folder.

**Comment by infograf768** [comment]
Any stable or update J release will contain the media folder.
It will let any installed extension to add (and keep) there js and css files.

**Comment by astridx** [comment]
OK. Thank you.

**Comment by rdeutz** [comment]
I see what happend, because we move the files it is no longer in git because it is empty. We should add a .gitkeep file

**Comment by brianteeman** [comment]
@rdeutz not really needed. The folder is there as soon as you run the build scripts and you cant use joomla from git until you have done that
