### ISSUE TITLE
Standard Field Type - File - Maximum upload size reads from php.ini in Joomla3.8.9

### ISSUE THREAD

**Issue by thaneshs** [joomla/joomla-cms#21636]
### Steps to reproduce the issue

You can add Joomla custom field "file" in form xml like below,
< field name="myfilevalue" type="file" label="Enter some text" description="Choose an image from your computer with maximum 5MB" size="10" accept="image/*"  />

### Expected result
![download 3](https://user-images.githubusercontent.com/41372392/44195640-482dfc00-a157-11e8-912d-16a0a317bc42.png)

### Actual result

![download](https://user-images.githubusercontent.com/41372392/44195341-5cbdc480-a156-11e8-9396-3e498d3d577b.png)

How can i remove that text Maximum upload size: 256.00 MB which reads the value from server php.ini  

### Additional comments
I have set media manager option maximum upload file size to 10MB and also added hidden field with default size as suggested in Joomla docs like below,

< field name= "MAX_FILE_SIZE" type="hidden" default="10MB"  />

I hope Joomla provides an option in field level to hide it. If anyone come across with this please advice me on this.

Thanks in Advance!!!

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.

**Comment by ghost** [comment]
Please also update to [latest Version](https://github.com/joomla/joomla-cms/releases/tag/3.8.11).

**Comment by ghost** [comment]
Sorry, misread your Issue, so reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21636">issues.joomla.org/tracker/joomla-cms/21636</a>.</sub>

**Comment by SharkyKZ** [comment]
The text can be removed in field layout (/layouts/joomla/form/field/file.php).

>I have set media manager option maximum upload file size to 10MB

File field is not related to Media manager. Media manager options are used by Media field.

**Comment by thaneshs** [comment]
Thank you for your help.

It works fine. Hope Joomla will provide an option to hide it in form field
level instead core change.

Thanks!!

**Comment by ghost** [comment]
@thaneshs If Issue is solved please close it.

> Hope Joomla will provide an option to hide it in form field level instead core change.

can you please open a Feature Request so this Wish didn't get lost?

**Comment by ReLater** [comment]
> instead core change

Maybe a misunderstanding? Normally you create an override of the mentioned JLayout file, not a core hack.
