### ISSUE TITLE
[4.0] Switcher: Color of "Yes" / "No" gone

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21639]
### Steps to reproduce the issue
Since Yesterday "Yes" or "No" is shown green, now:

![screen shot 2018-08-16 at 12 47 31](https://user-images.githubusercontent.com/8235763/44204424-cc31b500-a152-11e8-8de2-7fc8955c660e.jpg)
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by dgrammatiko** [comment]
@ciar4n did the change on the scss file break the switcher?

**Comment by ciar4n** [comment]
Shouldn't have as that PR did not change any CSS

**Comment by dgrammatiko** [comment]
oops 
<img width="845" alt="screenshot 2018-08-16 at 15 43 01" src="https://user-images.githubusercontent.com/3889375/44212230-14f56800-a16b-11e8-983d-ec680d0fb65f.png">

**Comment by ciar4n** [comment]
PR created.. #21658

**Comment by ghost** [comment]
closed as having Pull Request #21658
