### ISSUE TITLE
[4.0] com_workflow: Missing Value for "Count States"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21634]
### Steps to reproduce the issue
As Title say:

![screen shot 2018-08-16 at 07 15 04](https://user-images.githubusercontent.com/8235763/44189840-780fdc00-a124-11e8-86ea-1418a512a694.jpg)
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by infograf768** [comment]
The string is now
`COM_WORKFLOW_COUNT_STAGES`

and should therefore be modified 3 times in `/administrator/components/com_workflow/tmpl/workflows/default.php`

**Comment by wojsmol** [comment]
@franz-wohlkoenig @infograf768 Please test PR https://github.com/joomla/joomla-cms/pull/21635

**Comment by infograf768** [comment]
Closing as we have a patch https://github.com/joomla/joomla-cms/pull/21635
