### ISSUE TITLE
Permissions tab groups list

### ISSUE THREAD

**Issue by Flowman** [joomla/joomla-cms#21630]
### What needs to be fixed
I have created an education site with lots of groups (120+). When opening up any type of view that has the permission tab it is really hard to set permission. As first I need to scroll down to find the group and than scroll up again to set the permission. 

![image](https://user-images.githubusercontent.com/212680/44150233-58ab5842-a0d1-11e8-8e01-4c3ae9555ac3.png)

### Why this should be fixed
To make it easier to manage permission for sites with lots of groups.

### How would you fix it
Either make the permission fixed position and scroll with the content or have a drop down list where we can select and search for groups.

### Side Effects expected
n/a

**Comment by ciar4n** [comment]
PR created... #21637

@Flowman If you could test that would be 👍

**Comment by ghost** [comment]
closed as having Pull Request #21637
