### ISSUE TITLE
Incorrect information in Extensions: Database

### ISSUE THREAD

**Issue by dioubernardo** [joomla/joomla-cms#21642]
### Steps to reproduce the issue
1 - Uninstall News Feed extension
2 - Open /administrator/index.php?option=com_installer&view=database

### Actual result
![image](https://user-images.githubusercontent.com/3487994/44210908-1197b780-a13e-11e8-8c5b-44d7df6fa96f.png)

### System information (as much as possible)

Setting | Value
-- | --
 
PHP Built On | Linux joomla 3.13.0-153-generic #203-Ubuntu SMP Thu Jun 14 08:52:28 UTC 2018 x86_64
Database Type | mysql
Database Version | 5.5.61-0ubuntu0.14.04.1
Database Collation | latin1_swedish_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 5.5.9-1ubuntu4.25
Web Server | Apache
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 3.8.11 Stable [ Amani ] 31-July-2018 14:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by brianteeman** [comment]
TBH this is kind of expected behaviour as we dont really support 100% removal of core components

**Comment by ghost** [comment]
closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21642">issues.joomla.org/tracker/joomla-cms/21642</a>.</sub>
