### ISSUE TITLE
The security token did not match. Login Error

### ISSUE THREAD

**Issue by PhilippSPOTTERON** [joomla/joomla-cms#21644]
### Steps to reproduce the issue
After updating to 3.8.11, the frontend login on our website just displays the warning:
The security token did not match. The request was aborted to prevent any security breach. Please try again.
when trying to login.

### Expected result
normal log in.

### Actual result
Error Message: The security token did not match. The request was aborted to prevent any security breach. Please try again.

### System information (as much as possible)

PHP Built On | Linux 3.13.0-042stab127.2 #1 SMP Thu Jan 4 16:41:44 MSK 2018 x86_64
-- | --
Database Type | mysql
Database Version | 5.5.61-0ubuntu0.14.04.1
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.0.31
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.8.11 Stable [ Amani ] 31-July-2018 14:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

Safe Mode | Off
-- | --
Open basedir | /var/www/vhosts/[...]/:/tmp/
Display Errors | Off
Short Open Tags | Off
File Uploads | On
Magic Quotes | Off
Register Globals | Off
Output Buffering | On
Session Save Path | /var/lib/php5
Session Auto Start | 0
XML Enabled | Yes
Zlib Enabled | Yes
Native ZIP Enabled | Yes
Disabled Functions | None
Multibyte String (mbstring) Enabled | Yes
Iconv Available | Yes
Maximum Input Variables | 1000
PHP Version 7.0.31

System | Linux  3.13.0-042stab127.2 #1 SMP Thu Jan 4 16:41:44 MSK 2018 x86_64
Build Date | Jul 20 2018 12:58:45
Configure Command | './configure' '--prefix=/opt/plesk/php/7.0' '--bindir=/opt/plesk/php/7.0/bin' '--sbindir=/opt/plesk/php/7.0/sbin' '--libexecdir=/opt/plesk/php/7.0/lib' '--datadir=/opt/plesk/php/7.0/share' '--sysconfdir=/opt/plesk/php/7.0/etc' '--sharedstatedir=/opt/plesk/php/7.0/com' '--localstatedir=/opt/plesk/php/7.0/var' '--libdir=/opt/plesk/php/7.0/lib/x86_64-linux-gnu' '--includedir=/opt/plesk/php/7.0/include' '--infodir=/opt/plesk/php/7.0/share/info' '--mandir=/opt/plesk/php/7.0/share/man' '--build=x86_64-linux-gnu' '--host=x86_64-linux-gnu' '--with-libdir=lib' '--cache-file=../config.cache' '--with-config-file-path=/opt/plesk/php/7.0/etc' '--with-config-file-scan-dir=/opt/plesk/php/7.0/etc/php.d' '--disable-debug' '--without-pear' '--with-pic' '--disable-rpath' '--with-bz2' '--with-freetype-dir=/usr' '--with-png-dir=/usr' '--with-xpm-dir=/usr' '--enable-gd-native-ttf' '--without-gdbm' '--with-gettext' '--with-gmp' '--with-iconv' '--with-jpeg-dir=/usr' '--with-openssl' '--with-pcre-regex' '--with-zlib' '--with-layout=GNU' '--enable-exif' '--enable-ftp' '--enable-sockets' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--with-kerberos' '--enable-calendar' '--with-libxml-dir=/usr' '--enable-xml' '--enable-phpdbg' '--with-enchant=shared,/usr' '--with-system-tzdata' '--with-litespeed' '--enable-pcntl' '--with-imap=shared' '--with-imap-ssl' '--enable-mbstring=shared' '--enable-mbregex' '--with-gd=shared' '--enable-bcmath=shared' '--enable-dba=shared' '--with-db4=/usr' '--with-xmlrpc=shared' '--with-ldap=shared' '--with-ldap-sasl' '--enable-mysqlnd=shared' '--with-mysqli=shared, mysqlnd' '--with-mysql-sock=/var/run/mysqld/mysqld.sock' '--enable-dom=shared' '--with-pgsql=shared' '--with-snmp=shared,/usr' '--enable-soap=shared' '--with-xsl=shared,/usr' '--enable-xmlreader=shared' '--enable-xmlwriter=shared' '--with-curl=shared,/usr' '--enable-pdo=shared' '--with-pdo-odbc=shared, unixODBC,/usr' '--with-pdo-mysql=shared, mysqlnd' '--with-pdo-pgsql=shared,/usr' '--with-pdo-sqlite=shared,/usr' '--with-sqlite3=shared' '--enable-json=shared' '--enable-zip=shared' '--without-readline' '--with-libedit' '--with-pspell=shared' '--enable-phar=shared' '--with-mcrypt=shared,/usr' '--with-tidy=shared,/usr' '--with-unixODBC=shared,/usr' '--enable-fileinfo=shared' '--enable-intl=shared' '--with-icu-dir=/usr' '--enable-sysvmsg=shared' '--enable-sysvshm=shared' '--enable-sysvsem=shared' '--enable-posix=shared' 'build_alias=x86_64-linux-gnu' 'host_alias=x86_64-linux-gnu'
Server API | CGI/FastCGI
Virtual Directory Support | disabled
Configuration File (php.ini) Path | /opt/plesk/php/7.0/etc
Loaded Configuration File | /var/www/vhosts/system/spotteron.net/etc/php.ini
Scan this dir for additional .ini files | /opt/plesk/php/7.0/etc/php.d
Additional .ini files parsed | /opt/plesk/php/7.0/etc/php.d/00-ioncube-loader.ini, /opt/plesk/php/7.0/etc/php.d/10-opcache.ini, /opt/plesk/php/7.0/etc/php.d/20-mysqlnd.ini, /opt/plesk/php/7.0/etc/php.d/50-xdebug.ini, /opt/plesk/php/7.0/etc/php.d/bcmath.ini, /opt/plesk/php/7.0/etc/php.d/curl.ini, /opt/plesk/php/7.0/etc/php.d/dba.ini, /opt/plesk/php/7.0/etc/php.d/dom.ini, /opt/plesk/php/7.0/etc/php.d/enchant.ini, /opt/plesk/php/7.0/etc/php.d/fileinfo.ini, /opt/plesk/php/7.0/etc/php.d/gd.ini, /opt/plesk/php/7.0/etc/php.d/imagick.ini, /opt/plesk/php/7.0/etc/php.d/imap.ini, /opt/plesk/php/7.0/etc/php.d/intl.ini, /opt/plesk/php/7.0/etc/php.d/json.ini, /opt/plesk/php/7.0/etc/php.d/ldap.ini, /opt/plesk/php/7.0/etc/php.d/mbstring.ini, /opt/plesk/php/7.0/etc/php.d/mcrypt.ini, /opt/plesk/php/7.0/etc/php.d/mysqli.ini, /opt/plesk/php/7.0/etc/php.d/odbc.ini, /opt/plesk/php/7.0/etc/php.d/pdo.ini, /opt/plesk/php/7.0/etc/php.d/pdo_mysql.ini, /opt/plesk/php/7.0/etc/php.d/pdo_odbc.ini, /opt/plesk/php/7.0/etc/php.d/pdo_pgsql.ini, /opt/plesk/php/7.0/etc/php.d/pdo_sqlite.ini, /opt/plesk/php/7.0/etc/php.d/pgsql.ini, /opt/plesk/php/7.0/etc/php.d/phar.ini, /opt/plesk/php/7.0/etc/php.d/posix.ini, /opt/plesk/php/7.0/etc/php.d/pspell.ini, /opt/plesk/php/7.0/etc/php.d/redis.ini, /opt/plesk/php/7.0/etc/php.d/snmp.ini, /opt/plesk/php/7.0/etc/php.d/soap.ini, /opt/plesk/php/7.0/etc/php.d/sqlite3.ini, /opt/plesk/php/7.0/etc/php.d/sysvmsg.ini, /opt/plesk/php/7.0/etc/php.d/sysvsem.ini, /opt/plesk/php/7.0/etc/php.d/sysvshm.ini, /opt/plesk/php/7.0/etc/php.d/tidy.ini, /opt/plesk/php/7.0/etc/php.d/xmlreader.ini, /opt/plesk/php/7.0/etc/php.d/xmlrpc.ini, /opt/plesk/php/7.0/etc/php.d/xmlwriter.ini, /opt/plesk/php/7.0/etc/php.d/xsl.ini, /opt/plesk/php/7.0/etc/php.d/zip.ini
PHP API | 20151012
PHP Extension | 20151012
Zend Extension | 320151012
Zend Extension Build | API320151012, NTS
PHP Extension Build | API20151012, NTS
Debug Build | no
Thread Safety | disabled
Zend Signal Handling | disabled
Zend Memory Manager | enabled
Zend Multibyte Support | provided by mbstring
IPv6 Support | enabled
DTrace Support | disabled
Registered PHP Streams | https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip
Registered Stream Socket Transports | tcp, udp, unix, udg, ssl, sslv3, tls, tlsv1.0, tlsv1.1, tlsv1.2
Registered Stream Filters | zlib.*, bzip2.*, convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, mcrypt.*, mdecrypt.*

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.
