### ISSUE TITLE
[privacy] What to do when mail of a request failed

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-cms#21646]
### Steps to reproduce the issue
- Disable mailing
- Create a request

### Expected result
Something in the UI where I get some information about a failed request.

### Actual result
I see a pending request.

### System information (as much as possible)
Latest from https://github.com/mbabker/joomla-cms/tree/dev/privacy

**Comment by brianteeman** [comment]
Where you as the submitter gets the information or where you as the siteowner gets the information?

**Comment by mbabker** [comment]
If the site's mail sending is turned off completely then the requests can never actually work, the email to the data subject to validate the request will never go out.  At a minimum checking this setting should be incorporated into the health check module, and we might want to do some conditional handling on the forms as well.

**Comment by alikon** [comment]
in https://github.com/joomla-projects/privacy-framework/pull/230 i've just changed the order of the executed tasks

**Comment by mbabker** [comment]
That's going to be too late.  For the frontend we almost shouldn't even let the form be submitted if mail sending is turned off.  Similar for the backend.

**Comment by alikon** [comment]
did you mean a check on the request controller, should it be on time?

**Comment by mbabker** [comment]
In the model, don't even try to save it if mail sending is disabled.  It is totally inactionable and at best a waste of bytes in the database (both frontend and backend).

In the view, show some kind of message saying the form can't be submitted because mail sending is disabled, possibly don't even show the forms at all (both frontend and backend).

Those two make sure the user doesn't waste time trying to do something that won't work to begin with.

Then, add to the health check module on the privacy component dashboard a check to ensure mail sending is enabled.

**Comment by alikon** [comment]
> In the model, don't even try to save it if mail sending is disabled.

not only imo, even when we got an `phpmailerException` we are too late as we are now without joomla-projects/privacy-framework#230  we already have stored the privacy request in the db

**Comment by mbabker** [comment]
That's why there needs to be an explicit check on the configuration versus just relying on the mail API to fail out based on the config.

**Comment by laoneo** [comment]
Guess we need also be able to handle requests, when there is an Exception sending the mail.

**Comment by alikon** [comment]
should be no mail no request

**Comment by laoneo** [comment]
From my limited understanding I would agree.

**Comment by jeckodevelopment** [comment]
Well, it could result also in a new row in the Status Check:

![immagine](https://user-images.githubusercontent.com/733133/44254750-0909b480-a204-11e8-8aff-cb308e8446c6.png)

To display at a glance that the system can't work because of the disabled mailing system.

**Comment by alikon** [comment]
@jeckodevelopment  there is a  wip joomla-projects/privacy-framework#230  there i'll add that status check too, stay tuned for the next days.....

**Comment by jeckodevelopment** [comment]
Thanks @alikon !

**Comment by mbabker** [comment]
https://github.com/joomla-projects/privacy-framework/pull/231 and https://github.com/joomla-projects/privacy-framework/pull/232 should cover all aspects of this, plus the already in-place error handling when an actual email send fails.

**Comment by laoneo** [comment]
Thanks!!
