### ISSUE TITLE
[4.0] Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Debug\ExceptionHandler::handle() must be an instance of Exception

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#21645]
### Steps to reproduce the issue
Go to Plugins - edit System - Debug plugin, enable "Log Executed Queries"

### Expected result
Should be saved.

### Actual result
`Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Debug\ExceptionHandler::handle() must be an instance of Exception, instance of Error given in \J4b\libraries\vendor\symfony\debug\ExceptionHandler.php:106 Stack trace: #0 [internal function]: Symfony\Component\Debug\ExceptionHandler->handle(Object(Error)) #1 {main} thrown in \J4b\libraries\vendor\symfony\debug\ExceptionHandler.php on line 106`

### System information (as much as possible)
PHP 7.2.4, MariaDB 10.2.6, Joomla! 4.0 Nightly Builds - 16. August

**Comment by franz-wohlkoenig** [comment]
Can't find `Log Executed Queries`:

![screen shot 2018-08-16 at 16 50 02](https://user-images.githubusercontent.com/8235763/44216126-75d56e00-a174-11e8-8cd0-87bf0c8dec75.jpg)

**Comment by ghost** [comment]
Can't confirm.

Got `Notice: Undefined property: Joomla\CMS\Object\CMSObject::$id in /layouts/joomla/edit/global.php on line 43`which is solved by #21623

### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by PhocaCz** [comment]
Hi, installed the latest version per composer today (17.8.2018) (Joomla! 4.0.0-alpha5-dev - Joomla! 4.0.0-alpha5-dev Development [ Amani ] 22-July-2018 22:58 GMT). I get no more such error, so I think, it can be marked as solved.

**Comment by happy2dev** [comment]
Hi,
I redirect the page 403 You are not authorised to view this resource.
And could see This error appear " Uncaught TypeError: Argument 1 passed to Symfony\Component\Debug\ExceptionHandler::handle() must be an instance of Exception"
My env. : Joomla! 4.0.0-alpha6-dev , PHP7.2 , Apache 2.4
Please discuss. Thank you.

**Comment by ghost** [comment]
@Minh-opensource comments on closed Issue didn't get much notice. Please open a new Issue and link to this Issue if needed.

**Comment by happy2dev** [comment]
Yes, you are right. I am checking if trouble from my component. Thank you for your comment.
