### ISSUE TITLE
[4.0] Notice: Undefined property: Joomla\CMS\Object\CMSObject::$id in layouts\joomla\edit\global.php on line 43

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#21647]
### Steps to reproduce the issue
Go to administration - Plugins - edit System - Debug plugin

### Actual result
Notice: Undefined property: Joomla\CMS\Object\CMSObject::$id in layouts\joomla\edit\global.php on line 43

![Image](https://i.imgur.com/NzkeEjB.png)

### System information (as much as possible)
PHP 7.2.4, MariaDB 10.2.6, Joomla! 4 Nightly Builds - 16. August.

**Comment by alikon** [comment]
solved by #21623

**Comment by ghost** [comment]
closed as duplicate Report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21647">issues.joomla.org/tracker/joomla-cms/21647</a>.</sub>
