### ISSUE TITLE
Joomla! 4 alpha 5 error 500

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#21664]
Hello everyone, since the night update of 09/08 Joomla! 4, my test site www.joomanji.fr has a 500 error: 500 Table 'magnytu2_joomanji2.i6cx0_workflow_associations' doesn't exist Table 'magnytu2_joomanji2.i6cx0_workflow_associations' doesn't exist 
If I reinstall the patch update of 08/08/2018 everything becomes normal again.

**Comment by alikon** [comment]
Can you test with the nightly of 16/08....  a lot of things have changed in the meantime

**Comment by Magnytu2** [comment]
after reinstalling the latest version since the night update of 17/08 it's still the same mistake.

**Comment by mbabker** [comment]
Are you installing new or trying to update an existing build?  If trying to update an existing build you need to ensure that all database changes are also being applied along the way.

**Comment by Magnytu2** [comment]
Yes I tried as a test to update my test site www.joomanji.fr with the night update. But there was a change from 08/08 that created a 500 error since that day. I can not find where the change is.
But this is the game and I am aware that I will have to start all over again if this modification is not accessible.

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/pull/20381 had database changes...

**Comment by Magnytu2** [comment]
Thank you, I will redo my site with a new installation. Your job improves every day Joomla! 4 and it's cool. Even if I remain a little questioning on the admin template that is too "big" and requires more click.
A fan of Joomla!

**Comment by ghost** [comment]
@Magnytu2 if Issue is solved please close it.

**Comment by Magnytu2** [comment]
I do not see any access to close this post. Thanks for your help.
