### ISSUE TITLE
[4.0] com_workflow: Undefined Method PlgContentJoomla

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21668]
### Steps to reproduce the issue
Delete an Stage got Error (see Screenshot), but Stage is trashed:

![44267933-51d76280-a230-11e8-8bd3-cc000d11e33e](https://user-images.githubusercontent.com/8235763/44269947-4424db80-a236-11e8-8b48-60f73154e118.jpg)

First Comment on https://github.com/joomla/joomla-cms/pull/21641#issuecomment-413861717

### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by infograf768** [comment]
The method has been modified to `private function _canDeleteStages($pk)`
Trying to find out if this is included in another PR.

**Comment by wilsonge** [comment]
Should be fixed with the commit above. There are no other uses of this function in core now

**Comment by infograf768** [comment]
👍

**Comment by alikon** [comment]
not at all see https://github.com/joomla/joomla-cms/commit/e89c495d6786fb369fac467e24bf5b67cd0ed38f#commitcomment-30155758

**Comment by infograf768** [comment]
As far as I understand, that commit only concerned the method name which obviously was wrong.
Concerning the content of the method, it should be another issue/PR

**Comment by ghost** [comment]
i commented the Error is shown and that the State is trashed as expected.
