### ISSUE TITLE
[4.0] Workflows - naming inconsistency

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21666]
From Stage or Current Stage
To Stage or Target Stage

<img width="610" alt="chrome_2018-08-17_11-34-37" src="https://user-images.githubusercontent.com/1296369/44262093-aa4b3780-a211-11e8-8666-1326d98aa164.png">

**Comment by ghost** [comment]
Similar to Dropdown-Fieldname should be "Current Stage" and "Target Stage".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21666">issues.joomla.org/tracker/joomla-cms/21666</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #22059
