### ISSUE TITLE
Intro image not loading

### ISSUE THREAD

**Issue by beish** [joomla/joomla-cms#21675]
### Steps to reproduce the issue
Intro image in articles, not loading image/file manager, 404 error.

Analyzing the problem with inspect element on select button i have found that in front of url there is characters %0A (LF line feed) and directing on unexisting location - 

href="/website/%0Aindex.php?option=com_jce&view=editor&plugin=browser&standalone=1&4fedf313d9a5bcc55fd7482d1fccb5e3=1&context=22&mediatype=images&fieldid=jform_images_image_intro&folder=

When i remove %0A characters in inspect element mode images are loading with no problems. Also if i turn debugging on, these %0A characters are missing and intro images are loading.

### Expected result
When click on Select button expected is to load image/file manager to choose intro image.

### Actual result
404 error

### System information (as much as possible)
PHP Built On 	Linux 3.10.0-714.10.2.lve1.5.17.1.el7.x86_64 #1 SMP Tue May 22 10:39:25 EDT 2018 x86_64 
mysql Database Version 	5.6.39-cll-lve
PHP Version 	5.6.37
Web Server 	Apache
WebServer to PHP Interface 	litespeed
Joomla! Version 	Joomla! 3.8.11 Stable [ Amani ] 31-July-2018 14:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Editor is JCE Version 2.6.32

### Additional comments
Problem is with %0A characters loaded in front of index.php in url.

**Comment by ghost** [comment]
Thanks for Report but can't confirm: Intro Image loading by "Images and Links" works as expected.

As you use "option=com_jce" i suggest to ask in JCE-Forum, so i close this Issue as no Core-Issue. 

It can always reopened if needed.

**Comment by beish** [comment]
When i disable System SEF plugin %0A character in front of index.php disappears and everything is working, but i noticed that after the plugin was disabled, the links to the images changed and no images were loaded anymore.

**Comment by brianteeman** [comment]
That character means "new line". I would double check that you dont have anything in the configuration.php file in the $livesite variable

**Comment by beish** [comment]
I checked configuration.php and this is what is in variable: public $live_site = '';
Is this ok?

**Comment by beish** [comment]
When i uninstall all JCE components and plugins same error apears on article publishing page:

page/%0Aindex.php?option=com_media&view=images&tmpl=component&asset=com_content&author=created_by&fieldid=jform_images_image_intro&folder=

I think that System SEF plugin has somekind of problem because when i install i make default some other template the same problem exist.

**Comment by beish** [comment]
I found couse of the problems, It is not, as I originally thought, the problem in system sef plugin, rather than a rokbooster cache plugin and when disabled everything is working fine.

**Comment by ghost** [comment]
@beish glad you solved the Issue. Maybe next Time you ask at the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding.
