### ISSUE TITLE
403 Forbidden Message

### ISSUE THREAD

**Issue by alexnya** [joomla/joomla-cms#21677]
Hi,

I have a problem where when I go to my URL I'm getting the 403 Forbidden message that says the following:

You don't have permission to access / on this server.

My domain in currently pointed at /var/www/html/joomla

The permissions for var/www, var/www/html, and var/www/html/joomla are all 755. Here is my virtual host file for joomla:

<VirtualHost *:80>
ServerAdmin support@aquada.com
DocumentRoot /var/www/html/joomla/
ServerName aquadamedia.com
ServerAlias www.aquadamedia.com

<Directory /var/www/html/joomla/>
Options +FollowSymlinks
AllowOverride All
Require all granted
</Directory>

ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

I tried renaming the htaccess file and creating an index.html file within the joomla directory and I'm still getting the 403 Forbidden error message.

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.
