### ISSUE TITLE
[4.0] com_workflow: "Stages" and "Transitions" are 3rd-Level Menu

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21687]
![screen shot 2018-08-18 at 15 57 08](https://user-images.githubusercontent.com/8235763/44299975-ad245600-a2ff-11e8-99c3-a09c5de93154.jpg)

As Screenshot show "Stages" and "Transitions" are hard to see as Part of "Workflows". 
### Describe the solution you'd like
A "- " at Beginning.

**Comment by bembelimen** [comment]
It was removed in the sake of consistent requested by @brianteeman so perhaps he can say something.

**Comment by brianteeman** [comment]
Basically there should be no third level menus in j4

**Comment by ghost** [comment]
If there is no 3rd-Level-Menu a good UX then Lines between groups like:

```
Articles
Categories
Featured
----
Workflows
Stages
Transitions
----
Fields
Groups
```

**Comment by brianteeman** [comment]
Even that sidebar is supposed to be removed - its just waiting on a decision

**Comment by ghost** [comment]
thanks for Info @brianteeman

**Comment by ghost** [comment]
closing as another Solution may come.
