### ISSUE TITLE
RFC URL/Email Validation

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21680]
Why do we have this complex rule for validating urls  https://github.com/joomla/joomla-cms/blob/0cd132e059f4cfa8558acac3c84b10ef5b144f5c/libraries/src/Form/Rule/UrlRule.php#L25

Wouldn't it be much easier to use the native php validation filters
http://php.net/manual/en/filter.filters.validate.php

**Comment by brianteeman** [comment]
and in most places we dont even use that rule when we really should
https://github.com/joomla/joomla-cms/issues/13876

**Comment by ReLater** [comment]
FILTER_VALIDATE_EMAIL : dotless domain names are not supported (e.g. dings@localhost).
FILTER_VALIDATE_URL : only find ASCII URLs to be valid.

I'm not absolutely sure if it was a Joomla discussion but as far as I remember that was the reason why FILTER_VALIDATE_EMAIL was refused in the past.

**Comment by brianteeman** [comment]
yes i should have updated to say i found out the dotless domain issue - thanks

luckily we should be able to use the html5 input type email
