### ISSUE TITLE
[4.0] Factory Application method visibility

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#21699]
### Steps to reproduce the issue
As of August 18 but this issue (for me) occurs few days before right after I update (updating everyday).

Try to `Factory:getApplication()->input` and notice your IDE no longer knows what are the methods available with `input`.

This is not only happening with `input` but rather for most if not all object call.

### Expected result
Methods should be visible when an object is called for easy debugging and development.

### Actual result
Methods were no longer picked up by IDE (PhpStorm) and now I have to open the class file and look for the available methods.

**Comment by mbabker** [comment]
Not really an issue here.  `Joomla\CMS\Factory::getApplication()` is annotated to return a `Joomla\CMS\Application\CMSApplicationInterface` object in 4.0 versus a concrete class object, and interfaces do not declare class member variables on them.

Also, blindly calling `Factory::getApplication()->input` in 4.0 will not always be reliable as the CLI application in the new Console package will eventually have that removed (I just need to find the time to `composer update` that package and address the changes), which means if that code can be executed in both CLI and web contexts it will need different handling.

**Comment by ghost** [comment]
closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21699">issues.joomla.org/tracker/joomla-cms/21699</a>.</sub>
