### ISSUE TITLE
Target Attribute "open in same frame" DOES NOT WORK. Selecting link changes frame to default Menu Item Context

### ISSUE THREAD

**Issue by blevy009** [joomla/joomla-cms#21698]
### Steps to reproduce the issue
Working in Joomla 3.6.5, and lighthouse template for 3x

In article that is associated with a menu item (ie, select menu item to open Page;
Edit article and add link to that article - selecting the article via Link icon and navigating to article in +Content/to Category, select desired article.  IN Attributes, select Target drop down Open in current window /frame. SAVE

### Actual result:  The Main menu switches to the default Welcome menu item and In this Section changes to the Welcome context. The article does display, but since we have a module that ONLY displays (in center top article space) this now shows above the desired article.

I have identified a work-around:  &Itemid=567 (was getting set to Welcome menu id)  by changing the Itemid to the known and desired current menu item, it works as expected - ie, the desired article is displayed at the top of the article space, and the In this Section is Not changed.

### System information (as much as possible)

Working in Joomla 3.6.5, and lighthouse template for 3x, use about 20 modules, use 5 addons

System Information
Setting	Value
 
PHP Built On	Linux boscustweb1504.eigbox.net 4.14.22 #1 SMP Tue Feb 27 21:19:56 EST 2018 x86_64
Database Version	5.6.37-82.2-log
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.30
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

### Additional comments
I have identified a work-around:  &Itemid=567 (was getting set to Welcome menu id)  by changing the Itemid to the known and desired current menu item, it works as expected - ie, the desired article is displayed at the top of the article space, and the In this Section is Not changed.

**Comment by brianteeman** [comment]
First you must upgrade to the latest release. Yours is very old.

Second please use the forum for support. Https://forum.joomla.org
