### ISSUE TITLE
[4.0] Cleanup template declared module positions

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#21700]
### Steps to reproduce the issue
The positions defined in template.xml don't match what's in the templates

**Comment by brianteeman** [comment]
I will fix this tomorrow when I fix my accessibility bug

**Comment by brianteeman** [comment]
except it turns out there are module positions defined directly in some of the components - which is wrong to me as in order for them to be listed in available positions they need to be listed in template.xml even though they are not part of the template

**Comment by brianteeman** [comment]
Closed see #21732
