### ISSUE TITLE
[4.0] Improve sample data  workflow liaison

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#21707]
Just some thoughts about sample data (will be extended over the next weeks)

- [x]  Creating a new workflow for sample data, so they are perfect alligned and don't conflict with other workflows.

**Comment by Bakual** [comment]
Why a new workflow and not using the default one?

**Comment by bembelimen** [comment]
Because the default one is not always available.

**Comment by bembelimen** [comment]
Code: #21953 and #21968

**Comment by MauriceTerer** [comment]
Can someone guide on how to implement the joomla 4 workflow in joomla 3

**Comment by brianteeman** [comment]
You can't
 It is a joomla 4 feature

**Comment by MauriceTerer** [comment]
What should happen if i want to implement the same in joomla 3. Any ideas on how to implement this
