### ISSUE TITLE
[4.0] Don't use "bold" as font-weight type

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#21727]
### Steps to reproduce the issue

The use of font-weight:bold; can start becoming a pain, even more so they you decide to use a Google or other alternative font that utilises more than just `normal` and `bold`.

An array of font weights should be defined in the variables.scss with all the possible numeric keywords.

This will make changing the font in a template much easier

**Comment by brianteeman** [comment]
Closed see #21731
