### ISSUE TITLE
Missinng Language String

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21729]
The string COM_ASSOCIATIONS_ERROR_NO_TYPE is missing from the language files. I would write it but I can't work out what it is supposed to be or how to trigger it. Any ideas @infograf768 

https://github.com/joomla/joomla-cms/blob/f3094f29b480c4a84e1c632bd4395463a7adcf4a/administrator/components/com_associations/views/associations/view.html.php#L98

**Comment by infograf768** [comment]
Should be something like
"The item type selected does not exist for this component."

**Comment by brianteeman** [comment]
How to trigger the error?

**Comment by infograf768** [comment]
A badly coded component which proposes a wrong type. With core components, there should be no error.

**Comment by brianteeman** [comment]
OK thanks - pr incomig

**Comment by ghost** [comment]
closed as having Pull Request #21733
