### ISSUE TITLE
[4.0] Can delete "Keep forever" versions

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#21738]
### Steps to reproduce the issue

Surely if a version of an article is set to "keep forever" = yes, then I should not be able to delete it?

### Expected result

That I should have to toggle the keep forever to be no before I can delete a version of an article

### Actual result

if keep forever is enabled, I can still delete the version in the popup on the frontend.
![screen shot 2018-08-19 at 22 44 53](https://user-images.githubusercontent.com/400092/44313490-bb5a9b00-a401-11e8-8703-c0157254d249.png)

### System information (as much as possible)
5defb0096e01de56aa6a3690e4518024bdd75de5

**Comment by dgrammatiko** [comment]
Out of curiosity is J3 different here?

**Comment by PhilETaylor** [comment]
No idea. Ain't no body got time for Joomla 3 anymore. If issues are not marked with a "4" tag no one cares ;-)

**Comment by mbabker** [comment]
Maybe that's why I can't get 3.9 out the door :trollface:

**Comment by PhilETaylor** [comment]
I thought we were skipping Joomla 3.9? :trollface:

**Comment by ggppdk** [comment]
@PhilETaylor 
you had a similar issue for J3

Behavior of J3 was "corrected" or modified (depends on how you feel about fixing this) on June 18
https://github.com/joomla/joomla-cms/commit/7a33abe68bf7f7fc5d4c0c45973d6e46469c0cbe

**Comment by PhilETaylor** [comment]
did I - wow - well shows that I test repeatedly then, and that even though it appears that a PR was made - the issue is still there today....

**Comment by PhilETaylor** [comment]
Well it doesnt appear (at first glance) to have been ported to the Joomla 4 code - see https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_contenthistory/Model/HistoryModel.php and therefore this is still a valid issue

**Comment by ggppdk** [comment]
It is not easy task to move some of these changes to J4 branch, it must be a pain

**Comment by PhilETaylor** [comment]
Yes its a pain, but I thought the whole point of making PR's against 3 was that they would be eventually rolled into 4 - else all that 4 is, is a fork of an old version of 3 and missing a LOT of fixes that were applied to 3 - including security fixes :trollface:!

**Comment by brianteeman** [comment]
They are eventually being rolled into j4 - its a long and complex job - not something that can be done blindly.

**Comment by PhilETaylor** [comment]
This is still an issue in Joomla 4.0-dev @ 9d3acfd9d589989e86bda3fe35f58a47323d66f4 today
