### ISSUE TITLE
[4.0] I have 1000 extensions installed, and I cannot access them...

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#21736]
### Steps to reproduce the issue

ok I dont have a 1000 extensions installed, but I have faked having a handful installed (All called "Akeeba Backup" for this test.

The same issue we had in Mambo 4.5 onwards, users will install millions of extensions and then the extensions list causes issues in the menu structure that is nicely designed to handle a "few" but not to handle real world cases where "users" "use" the system with their Trillion Extensions all installed. 

This leads to users being able to access my extension which is called ZzzImSleeping which is off the page, and inaccessible at the bottom of a menu

### Expected result

A user experience that allows all billion installed extensions to show in the administrator menu in a pretty and useable way

In Joomla 3.5 there was a scroller, not pretty, but effective. 

### Actual result

Currently, when you scroll down on a 27" monitor you get a load of whitespace, and white on white menu text leads to "invisible" menu items. 

Grab some popcorn and watch this movie in HD  http://screenshot.myjoom.la/0K2G3l1P2K1W or the following low-res gif (cause github doesnt allow HD Movies!)

![screen-recording-2018-08-19-at-10 25-pm](https://user-images.githubusercontent.com/400092/44313364-86e5df80-a3ff-11e8-954e-a920071b7caa.gif)

### System information (as much as possible)
5defb0096e01de56aa6a3690e4518024bdd75de5

**Comment by coolcat-creations** [comment]
As the menu will be completely changed anyway, maybe this issue needs to be closed. Sorry for the time and thank you for your testing!

**Comment by PhilETaylor** [comment]
Why is the menu being completely changed again? I thought this was the new admin template already ?

**Comment by coolcat-creations** [comment]
Because of accessibility issues that can't be solved with the current design.

**Comment by brianteeman** [comment]
they can be solved - its fud that it cannot

**Comment by PhilETaylor** [comment]
Well the issue of 1000 extensions installed has been missed this time, and before, so lets hope that this issue is not ignored next time...

**Comment by coolcat-creations** [comment]
@brianteeman ok, then explain to me how to solve hover and click on the main items. Hover for submenu and click for the dashboard landingpages in an accessible way. 

However - the new designed Menu is in progress already and hopefully soon merged.

**Comment by brianteeman** [comment]
anything is possible but you chose not to ask for help

**Comment by ghost** [comment]
> hopefully soon merged

+1

**Comment by coolcat-creations** [comment]
@brianteeman We discussed that in the team you left and found a solution which will make everyone happy, including a11y.

**Comment by brianteeman** [comment]
i was never in a team - just a skype chat that after 2 months of silence I left with a note saying let me know when you reactivate

**Comment by coolcat-creations** [comment]
https://github.com/joomla/joomla-cms/issues/22005
