### ISSUE TITLE
[4.0] core.js was not properly initialised

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#21737]
### Steps to reproduce the issue

Click Email to friend feature on an article of the default content 

### Expected result

No JS errors

### Actual result

Popup window url is
/index.php/en/component/mailto?tmpl=component&template=cassiopeia&link=5bf0c621677ce2812066792bff89a77a129672cc

JS error is: 

```
core.js was not properly initialised
 /media/com_mailto/js/mailto-default.min.js?0179d59b8db39ff52e35922ed78000f5:1
```

screenshot:
![screen shot 2018-08-19 at 22 36 56](https://user-images.githubusercontent.com/400092/44313415-80a43300-a400-11e8-985e-57d6ffbf1dd0.png)

(Note big red warning generated by Google Chrome JavaScript Errors Notifier Extension)

### System information (as much as possible)
5defb0096e01de56aa6a3690e4518024bdd75de5

**Comment by dgrammatiko** [comment]
@PhilETaylor there is a PR to remove this button (email + print)

**Comment by PhilETaylor** [comment]
Removing two features Joomla has had since Mambo 1.0? wow...

**Comment by PhilETaylor** [comment]
Linking for future searchers
https://github.com/joomla/joomla-cms/pull/19393

**Comment by PhilETaylor** [comment]
The JS issue is elsewhere #21740 #21741 #21742

**Comment by dgrammatiko** [comment]
@PhilETaylor check: https://github.com/joomla/joomla-cms/pull/21745

**Comment by PhilETaylor** [comment]
fixed in https://github.com/joomla/joomla-cms/pull/21745

**Comment by ghost** [comment]
@PhilETaylor can you please mark #21745 as successfully Test?

**Comment by PhilETaylor** [comment]
Im still testing it against the 3 others listed above (trying to get Joomla 4 running on the office mac, been working from home for 4 weeks and npm is playing up)

**Comment by ghost** [comment]
should i alter the Test?

**Comment by PhilETaylor** [comment]
Well at the moment Joomla 4 build is broken so I cannot do anything...

**Comment by PhilETaylor** [comment]
I have marked #21745 as successful and it closes three other issues too

**Comment by ghost** [comment]
thanks @PhilETaylor
