### ISSUE TITLE
[4.0] Frontend-RTL: Align Menu-Item

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21747]
### What needs to be fixed
Marked Menu-Item in "Main menu fa-IR" should be right-aligned (as below in "Login Form")

![screen shot 2018-08-20 at 07 11 01](https://user-images.githubusercontent.com/8235763/44321493-a6edc100-a448-11e8-8196-40ac17a0a077.jpg)
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by infograf768** [comment]
Closing as we have patch
https://github.com/joomla/joomla-cms/pull/21749
