### ISSUE TITLE
[4.0] Weirdness with configuration/frontend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#21744]
### Steps to reproduce the issue

install Joomla 4 with demo data

Navigate to front end user registration form (while logged out)

In admin - Disable User Registration

![screen shot 2018-08-19 at 23 16 37](https://user-images.githubusercontent.com/400092/44313779-f1018300-a405-11e8-93db-313a3e9ad340.png)

reload frontend user registration form

### Expected result

404/403 error

### Actual result

form still loads fine, can be submitted, no error given and no user created.

### Additional comments

A strange one

http://0.0.0.0:8087/index.php/en/   SHOWS THE CREATE AN ACCOUNT link still after user registration is disabled

whereas http://0.0.0.0:8087/index.php/en without the trailing slash doesnt show the link in the module - strange !

No caching enabled. 

![screen shot 2018-08-19 at 23 21 39](https://user-images.githubusercontent.com/400092/44313802-a3d1e100-a406-11e8-92c3-157c772c922a.png)

**Comment by PhilETaylor** [comment]
This is a strange one. Im seeing the same behaviour with any global config change - its like the config is being cached somewhere but for one page only... 

E.g Set the site to be offline while you have a frontend page open - refresh the frontend page repeatedly and it still works (checking the PHP/Web logs you can see its NOT a browser cached version - its still going through Joomla and PHP to render it!!!) but if you navigate to any other link on the page, you then see the offline page correctly.

Its not browser - because if I open safari (as well as chrome) and then navigate around the site (which is in offline mode, and im not logged in) I can still get to the home, and several other demo pages...!!

Very strange - and if can be replicated by others, I would consider this huge issue (security too)

**Comment by PhilETaylor** [comment]
Note that the "server" is PHP command line like php -S 0.0.0.0:8085 - as that might be an important thing to test if you cannot replicate this with a webserver (nginx/apache)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21744">issues.joomla.org/tracker/joomla-cms/21744</a>.</sub>

**Comment by mbabker** [comment]
And if it really is the PHP webserver the odds of that being addressed are going to be slim to none, just being realistic here (who aside from you actually uses that for Joomla?).

**Comment by PhilETaylor** [comment]
I only mention it in passing :) just in case... 

I've yet to get a docker instance for Joomla 4 ;-) so I'm running PHP development command line server and mysql in docker :) 

Tonight I should have more time to complete the Joomla 4 development docker image for you ;-) and then I can retest... it was/is a very very very strange bug though, and I have seen this before in earlier development of Joomla 4

I'm thinking it could be an opcache thing - but not really sure why

**Comment by brianteeman** [comment]
Are you still seeing this issue on anything other than "php -s"

**Comment by PhilETaylor** [comment]
I canot replicate this today.
