### ISSUE TITLE
[4.0] Uncaught TypeError: t(...).find(...).andSelf is not a function

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#21743]
### Steps to reproduce the issue

install Joomla 4 with demo data 

login to admin as super admin

Go to Users -> Access Levels

Drag the hamburger icon to reorder levels OR click a level name

### Expected result

the level moves

### Actual result

JS error 

```
Uncaught TypeError: t(...).find(...).andSelf is not a function
```

![screen shot 2018-08-19 at 23 13 17](https://user-images.githubusercontent.com/400092/44313737-77699500-a405-11e8-91c8-36a82550b15a.png)

### System information (as much as possible)

5defb0096e01de56aa6a3690e4518024bdd75de5

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21743">issues.joomla.org/tracker/joomla-cms/21743</a>.</sub>

**Comment by C-Lodder** [comment]
Does replacing the following lines: https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_users/tmpl/levels/default.php#L28-L32

with this:

```
use Joomla\CMS\Session\Session;

if ($saveOrder)
{
	$saveOrderingUrl = 'index.php?option=com_users&task=levels.saveOrderAjax&tmpl=component' . Session::getFormToken() . '=1';
	HTMLHelper::_('draggablelist.draggable');
}
```

work?

**Comment by brianteeman** [comment]
No that gives

TypeError: Cannot read property 'querySelectorAll' of null

**Comment by brianteeman** [comment]
OK I have it working - the code from @C-Lodder was almost correct - there was just some extra code needed to be added to the table and tr

However before adding it - what is the usecase for ordering in this way - I can't see it myself and so I would propose removing it

**Comment by brianteeman** [comment]
Closed as there are several views this applies to and I have created one issue for them all #21787
