### ISSUE TITLE
[4.0] modal overlay wrong in versions

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#21746]
### Steps to reproduce the issue
install joomla4 and https://github.com/joomla/joomla-cms/pull/21745/ to fix JS issue

Then edit an article and click Versions button

### Expected result

Versions modal loads, grey is in the background not over the top so that it can be used

### Actual result

 grey blanket over the whole unusable page
![screen shot 2018-08-19 at 23 40 24](https://user-images.githubusercontent.com/400092/44313952-455a3200-a409-11e8-9d37-67c485b78a2a.png)
### System information (as much as possible)
Google Chrome
5defb0096e01de56aa6a3690e4518024bdd75de5

**Comment by PhilETaylor** [comment]
Also - note that in the console.log there is a dump of a blank array - someone might have left a console.log call in code too?

**Comment by ghost** [comment]
closed as duplicate Report #20255. Please reopen if i'm wrong.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21746">issues.joomla.org/tracker/joomla-cms/21746</a>.</sub>

**Comment by Scrabble96** [comment]
> 
> 
> closed as duplicate Report #20255. Please reopen if i'm wrong.
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/21746](https://issues.joomla.org/tracker/joomla-cms/21746).

This issue refers to incorrect overlay when in Articles: Edit. The other report (#20255 referenced above) is the incorrect overlay when viewed in Articles (i.e. the list of articles).

Anyway, it's still wrong in 4.0.0-alpha6-dev - as viewed on a subdomain of the Joomla demo via launch.joomla.com today:

![image](https://user-images.githubusercontent.com/36987494/50376433-b18db200-0604-11e9-8d89-11848728ad17.png)

(I don't think I can re-open this myself)
