### ISSUE TITLE
[4.0] RTL: Align Informations correct

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21750]
### What needs to be fixed
"Article Info" like Author-Name, Language, etc. need align right:

![screen shot 2018-08-20 at 09 36 28](https://user-images.githubusercontent.com/8235763/44326733-e3c3b300-a45c-11e8-925d-0486fd6a7f41.jpg)

url. http://wohlkoenig-4.joomla.com/index.php/fa/

### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by infograf768** [comment]
Easy to correct. Will do. Let's the other RTL PR merged first

Code to correct is
```
dd {

    margin-bottom: .5rem;
    margin-right: 0; // instead of margin-left

}
```

**Comment by brianteeman** [comment]
Best to check/correct all the ****-left etc all in one go

**Comment by ghost** [comment]
Something like that as Example:

![screen shot 2018-08-20 at 09 46 54](https://user-images.githubusercontent.com/8235763/44327115-0c987800-a45e-11e8-91ce-c90eab32dc5d.jpg)

url: http://wohlkoenig-4.joomla.com/index.php/fa/component/users/reset?Itemid=101 Please click on blue Button to get Error-Notice.
![screen shot 2018-08-20 at 09 54 53](https://user-images.githubusercontent.com/8235763/44327532-356d3d00-a45f-11e8-8856-a9a438caea74.jpg)

**Comment by infograf768** [comment]
It is right impossible to correct all in one go without knowing specific issues.
Regrouping all these issues in one would be helpful (with screenshots)
EDIT: with also specific urls to see the issue.
Then I can work on it.

**Comment by brianteeman** [comment]
So use this issue to record them all - and if there any other open issues they can be closed and copied here

**Comment by ghost** [comment]
> with also specific urls to see the issue.

@infograf768 done so far.

**Comment by ghost** [comment]
Click on Login Form-Botton without filled User- and Password-Values:

![screen shot 2018-08-20 at 09 57 49](https://user-images.githubusercontent.com/8235763/44327691-a6acf000-a45f-11e8-85ad-fa8b3f84c626.jpg)

url: http://wohlkoenig-4.joomla.com/index.php/fa/component/users/login?Itemid=101

**Comment by infograf768** [comment]
That one looks fine. What do you think it should be?
(Looks to me we have an issue with the display of Joomla.alert when the alert is too long. Will look into this specifically but may require js)

**Comment by ghost** [comment]
Blue marked Text need right aligned below "x" as same as in LTR-Languages or here (second Sentence):

![44327115-0c987800-a45e-11e8-91ce-c90eab32dc5d](https://user-images.githubusercontent.com/8235763/44328708-95191780-a462-11e8-8ad5-613da2cf9842.jpg)

**Comment by infograf768** [comment]
Afterthought:
the issue is with the Close button. It should be aligned left to solve the issue.
We have the same issue in back-end. Looking into it.

**Comment by infograf768** [comment]
Yeah, that was it. 😃 

<img width="586" alt="screen shot 2018-08-20 at 10 29 51" src="https://user-images.githubusercontent.com/869724/44329164-0907ef80-a464-11e8-96e4-1d6ab1626af3.png">

**Comment by infograf768** [comment]
Just to remember for the alert
```
joomla-alert .joomla-alert--close, joomla-alert .joomla-alert-button--close {

    float: left;  // instead of right
    color: #000;
    background: 0 0;
    border: 0;
    opacity: .5;

}
```
joomla-alert .joomla-alert--close, joomla-alert .joomla-alert-button--close {

    position: relative;
    top: -.5rem;
    left: -1.5rem; // instead of right
    padding: .2rem 1rem;
    color: inherit;

}
```

**Comment by infograf768** [comment]
ALSO:
Cassiopea logo/description
should be
```
.container-header .navbar-brand {
    position: relative;
    display: inline-block;
    padding: 0;
    margin-left: auto; // instead of margin-right
    font-size: 2rem;
    color: #fefefe;
}
```

**Comment by franz-wohlkoenig** [comment]
Load Module "Main Menu" in Position "Search" get:

![screen shot 2018-08-23 at 10 29 07](https://user-images.githubusercontent.com/8235763/44514075-6ba8f780-a6bf-11e8-8304-ac1a968869aa.jpg)

**Comment by brianteeman** [comment]
As far as I can tell this has been resolved elsewhere and can be closed. If there are other RTL issues then they should be opened in a new issue

**Comment by infograf768** [comment]
Some aspects are solved, but NOT the display of the article info in Cassiopea as well as the logo description which should align right.

<img width="351" alt="Screen Shot 2019-12-14 at 09 04 09" src="https://user-images.githubusercontent.com/869724/70845571-be786680-1e50-11ea-9403-d6b0dc889dc8.png">

Will make patch.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/27266
