### ISSUE TITLE
[4.0] Workflow - status enabled not published

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21757]
Just wondering what people think about changing the name of the status of a workflow/stage/transition to enabled/disabled/trashed instead of published/unpublished/trashed

Current
<img width="323" alt="chrome_2018-08-20_10-00-07" src="https://user-images.githubusercontent.com/1296369/44330821-e83d9b00-a45f-11e8-9f76-8ba8f72664bd.png">

Suggestion
<img width="290" alt="chrome_2018-08-20_10-00-35" src="https://user-images.githubusercontent.com/1296369/44330822-e8d63180-a45f-11e8-893a-0a9306dc714b.png">

**Comment by bembelimen** [comment]
Yes, please, good idea!

Perhaps we also get rid of the word "status"?

**Comment by brianteeman** [comment]
> Yes, please, good idea!

PR will be created

> Perhaps we also get rid of the word "status"?

I did think about that but even in plugins where we says enabled/disabled we still label it as status

**Comment by brianteeman** [comment]
ah - wait, just realised that in com_plugins we just have enabled/disabled but here you have published/unpublished/trashed :(  So to switch to just two is a bigger issue

Also while looking at the xml files I see that stage and workflow both have permissions defined in the xml but i dont see them being used anywhere??

**Comment by infograf768** [comment]
Also, we do use enable/disable for extensions manager in general.
For this and plugins it makes totally sense.
I would not change the wording elsewhere because of workgroup.

**Comment by brianteeman** [comment]
> For this and plugins it makes totally sense.

Obviously thats what I thought originally too but as there are 3 options it would require bigger changes to workflows than just changing the xml to make it just 2

> I would not change the wording elsewhere because of workgroup.

I wasn't suggesting changing anything anywhere else - not sure where you got that idea

**Comment by bembelimen** [comment]
Why should "enabled", "disabled" and "trashed" as tripple not work? Perhaps I didn't understand the context?

**Comment by brianteeman** [comment]
a triple is possible

**Comment by bembelimen** [comment]
I really like enabled/disabled and didn't get the problem here, hence the question.

**Comment by brianteeman** [comment]
The "problem" is that  elsewhere that we have enabled/disabled we do not also have trashed. So its an inconsistency to have it  as a triple here. But I can create the PR with the triple and leave it for others to decide

**Comment by brianteeman** [comment]
Closed see #21836
