### ISSUE TITLE
Module Articles - Newsflash not showing Featured Articles

### ISSUE THREAD

**Issue by crommie** [joomla/joomla-cms#21764]
### Steps to reproduce the issue
Create an Articles - Newsflash module. Set "Featured Articles" to Show. Make sure the category you're displaying contains featured articles.

### Expected result
Featured articles are shown in the module.

### Actual result
Featured articles are not shown in the module.

They do show up when you select "Only show featured articles".
### System information (as much as possible)
Joomla 3.8.11

**Comment by ghost** [comment]
thanks for Report, @crommie. his Issue has been reported and is solved by #21336, so i close it. If you have any Questions, please feel free to reopen or report another Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21764">issues.joomla.org/tracker/joomla-cms/21764</a>.</sub>
