### ISSUE TITLE
[4.0] Blog Layout have Pagination: document.adminForm is undefined

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21767]
### Steps to reproduce the issue
Create a Blog Layout using Pagination. After click on Pagination got JA-Error `TypeError: document.adminForm is undefined`, Pagination didn't load next Page.

![screen shot 2018-08-20 at 16 49 26](https://user-images.githubusercontent.com/8235763/44347787-0c699e00-a499-11e8-98e6-5c005beb090e.jpg)

### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by anibalsanchez** [comment]
I was about to report the same issue ;-)

```
index.php:357 Uncaught TypeError: Cannot read property 'limitstart' of undefined
    at HTMLAnchorElement.onclick (index.php:357)
```

It looks like the pagination on the frontend site is using the JavaScript backend navigation:

```
<a aria-label="Go to page 2" href="#" onclick="document.adminForm.limitstart.value=4; Joomla.submitform();return false;"> 
```

**Comment by brianteeman** [comment]
closing this as this has now been resolved elsewhere
