### ISSUE TITLE
Cannot edit new article after saving

### ISSUE THREAD

**Issue by ConfidantCommunications** [joomla/joomla-cms#21774]
### Steps to reproduce the issue
Start with fresh install, no sample data.
Create a new article in Uncategorized with some basic content.

### Expected result
Should save and go back to editing.

### Actual result
The article saves but the system produces a 500 error as it tries to go back to editing. My error log says "PHP Fatal error:  Cannot use Joomla\CMS\Language\Multilanguage as Multilanguage because the name is already in use in /Applications/MAMPold/htdocs_joomla4/administrator/components/com_content/Helper/PreviewHelper.php on line 18"

### System information (as much as possible)
Joomla 4 alpha 4
PHP 7.0.8
MySQLi database, version 5.0.11
Using MAMP Pro 3.5.2 on Mac OS 10.10.5

**Comment by chetanmadaan** [comment]
Already fixed in https://github.com/joomla/joomla-cms/pull/21224

**Comment by brianteeman** [comment]
Thanks for the report.
