### ISSUE TITLE
[4.0] Blog-View: `Undefined property: stdClass::$state_condition`

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21776]
### Steps to reproduce the issue
Open a Blog-View (http://wohlkoenig-4.joomla.com/index.php/fr), get:

![screen shot 2018-08-21 at 06 49 23](https://user-images.githubusercontent.com/8235763/44380981-87b96700-a50e-11e8-9adf-35d5515a76ab.jpg)
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by infograf768** [comment]
I am on it. PR coming

**Comment by infograf768** [comment]
closing as we have a patch.
https://github.com/joomla/joomla-cms/pull/21777

Can be tested with patchtester. :)
