### ISSUE TITLE
Version comparison popup is not clickable (Article manager) (J4 Issue)

### ISSUE THREAD

**Issue by chetanmadaan** [joomla/joomla-cms#21773]
### Steps to reproduce the issue
Login to Backend
Click Content >> Article.
Open article editing screen
Click Versions button

### Expected result
Actual result should have the backdrop modal behind the popup.
(Adjusted view with Firebug)
![image](https://user-images.githubusercontent.com/3968575/44364985-6e74d400-a496-11e8-9547-fd1cc4f686eb.png)

### Actual result
![image](https://user-images.githubusercontent.com/3968575/44364916-3c637200-a496-11e8-8c87-41d68afa28c1.png)

### System information (as much as possible)
Joomla 4 Alpha 4
Xampp with PHP 7 on windows.

### Additional comments
N/A

**Comment by PhilETaylor** [comment]
Already fixed with https://github.com/joomla/joomla-cms/pull/21745

**Comment by ghost** [comment]
closed as fixed in Code Base.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21773">issues.joomla.org/tracker/joomla-cms/21773</a>.</sub>
