### ISSUE TITLE
[4.0] com_workflow: "Stages" and "Transitions" are hidden if "Workflow" is used

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21778]
### Steps to reproduce the issue
Open "Article" ~~or any other Menu~~: "Stages" and "Transitions" are shown. Except click on "Workflow".

![screen shot 2018-08-21 at 07 52 58](https://user-images.githubusercontent.com/8235763/44382952-4083a400-a517-11e8-9cfe-25ed41b0d561.jpg)

### Expected result
Click on "Workflow" should also show Submenues.
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by bembelimen** [comment]
Showing the submenu on this place makes no sense, because no workflow is "active" (whose Stages/Transitions will be displayed when clicked), so the submenü only appears, if you're "in" a workflow.

**Comment by ghost** [comment]
@bembelimen thanks for Info.
