### ISSUE TITLE
[4.0] Blog View: Only 1 Column is used

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21770]
### Steps to reproduce the issue
Set Number of Columns didn't exist in Menu:
![screen shot 2018-08-20 at 18 35 37](https://user-images.githubusercontent.com/8235763/44353787-63c33a80-a4a8-11e8-8c8a-50bc735d424f.jpg)

Number of Columns exist in Article-Options:
![screen shot 2018-08-20 at 18 36 03](https://user-images.githubusercontent.com/8235763/44353817-7ccbeb80-a4a8-11e8-9bf0-c93ad31971a8.jpg)

In Frontend only 1 Column is used:
![screen shot 2018-08-20 at 18 36 28](https://user-images.githubusercontent.com/8235763/44353863-94a36f80-a4a8-11e8-8af5-8b6c31299a76.jpg)
url: http://wohlkoenig-4.joomla.com/index.php/fr/
### Expected result
View using more than 1 Column
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by brianteeman** [comment]
Same aas #21106 ?

**Comment by ghost** [comment]
true, thanks for Hint.
