### ISSUE TITLE
Update issues

### ISSUE THREAD

**Issue by feteno** [joomla/joomla-cms#21789]
### Expected result
No issue at all 

### Actual result
Alerte

Mise à jour : Impossible d'ouvrir le site de mise à jour avec l'ID 98, "Extension Update Admin Bruteforce Protection", URL : https://www.siteguarding.com/files/jadminbruteforceprotection.zip/extension.xml

Mise à jour : Impossible d'ouvrir le site de mise à jour avec l'ID 105, "Admin Tools Core", URL : https://cdn.akeebabackup.com/updates/pkgadmintoolscore.xml

Mise à jour : Impossible d'ouvrir le site de mise à jour avec l'ID 106, "Akeeba Backup Core", URL : https://cdn.akeebabackup.com/updates/pkgakeebacore.xml

### System information (as much as possible)
None ?

### Additional comments
I have no clue of what caused theses issues. 
I did not have these issues under 3.8.10 version.

**Comment by ghost** [comment]
Please ask help on the [forums - Migrating and Upgrading to Joomla! 3.x](https://forum.joomla.org/viewforum.php?f=710). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.
