### ISSUE TITLE
[4.0] File bug

### ISSUE THREAD

**Issue by TheRichik** [joomla/joomla-cms#21797]
When i used a \JFile::upload() have a little bug, u don't wrtie \JFilterInput::isSafeFile() in root\libraries\src\Filesystem\File.php on 543
Can't upload files...![screen shot 2018-08-21 at 14 36 17](https://issues.joomla.org/uploads/1/237242d029823560fae32da46ad8cdd0.png)

**Comment by SharkyKZ** [comment]
This is already fixed, see #21174.

**Comment by ghost** [comment]
closed as fixed in Code Base.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21797">issues.joomla.org/tracker/joomla-cms/21797</a>.</sub>
