### ISSUE TITLE
"New Issue": More specific on "System Information"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21793]
Submitting a new Issue a User get this:

#### System information (as much as possible)

Sometimes User ignore it, sometimes they paste all Parts of "System > System Information" which is Way to much.

Maybe its not clear what "as much as possbile" means. It would be more clear if User get Information "(Your Backend: System > System Information: Part "PHP Built On" to "User Agent").

**Comment by brianteeman** [comment]
It's when they don't post the version of Joomla and it cannot be inferred from the post that we have the main problems

**Comment by ghost** [comment]
so "Joomla Version" would be enough? Then this should be written.

**Comment by brianteeman** [comment]
It depends but it is a minimum

**Comment by ghost** [comment]
(Minimum: Your Joomla-Version)

or 

(Minimum: Your "Joomla-Version", better: "Backend: System > System Information")

**Comment by mbabker** [comment]
Instead of a generic heading, make a list or table with specific items instead of hoping someone might paste in a very specific output.

**Comment by ghost** [comment]
#### System information

Please replace Example below with Values from your Backend "System > System Information"

Setting | Value
-- | --
 
PHP Built On | Linux lamp122.cloudaccess.net 3.10.0-714.10.2.lve1.5.12.el6h.x86_64 #1 SMP Fri Feb 2 01:43:56 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.18-cll-lve
Database Collation | utf8mb4_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.1.15
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.8.12-dev Development [ Amani ] 31-July-2018 14:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0

Table is copy and paste from Backend.

**Comment by ghost** [comment]
> Please replace Example below with Values from your Backend "System > System Information"

as the Menus are different J3/j4 better use 

"Please replace Example below with Values from /index.php?option=com_admin&view=sysinfo"

**Comment by ghost** [comment]
will write if System Infomration isn't enough to copy from Backend "System > System Information".

Thanks for Discussion.
