### ISSUE TITLE
[4.0] Statistic-Module didn't show  Server- and Site Information

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21804]
### Steps to reproduce the issue
Create Statistic-Module, get:

![screen shot 2018-08-22 at 11 00 36](https://user-images.githubusercontent.com/8235763/44454282-64201a80-a5fb-11e8-9398-fbe62c66ee8f.jpg)
### Expected result
Module show  Server- and Site Information.
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by brianteeman** [comment]
Works for me

![image](https://user-images.githubusercontent.com/1296369/44454705-1ce25b80-a5f4-11e8-88d8-f1486238397d.png)

What happens if you go to `administrator/index.php?option=com_admin&view=sysinfo` do you get any errors there?

**Comment by ghost** [comment]
`administrator/index.php?option=com_admin&view=sysinfo` works. Looks like a local Issue.

**Comment by ghost** [comment]
Switches in Module was on "Hide" what i understand as "Show" ... didn't know why.

Maybe better to set Default to "Show"?

**Comment by ghazal** [comment]
The admin stats module works alright.
While testing the site stats module, I got this fatal error:
`Error: Column 'id' in field list is ambiguous: Column 'id' in field list is ambiguous`

Maybe a new post should be created ?

System information
    Nightly Build 4.0.0-alpha5-dev 8/23

**Comment by ghost** [comment]
@ghazal yes, please create a new Issue.

**Comment by ghazal** [comment]
OK.

**Comment by alikon** [comment]
> Maybe better to set Default to "Show"?

i don't think so, cause you are creating a new one, so you need to set your configuration module parameter properly (maybe  a more informative/color of the swithcer  will help to understand what is setted)

**Comment by ghost** [comment]
> maybe a more informative/color of the swithcer will help to understand what is setted

true, its more about me and Switcher-Behaviour.
