### ISSUE TITLE
Alternative category layout does not work

### ISSUE THREAD

**Issue by Gnevyshev** [joomla/joomla-cms#21800]
Joomla 3.8.11

Alternative category layout from my template does not work.

Сopy file **blog.php** from the location /components/com_content/views/category/tmpl/
to /templates/mytemplate/html/com_content/category/
So overriding works.
But:
If rename file, for example, **myblog.php** and choose this layout when edit category in back-end (options tab), overriding does not work.

**Comment by ghost** [comment]
Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding. For this Reason closing this Issue, thanks.

**Comment by Gnevyshev** [comment]
But the override is not a function of the Joomla-Core?
Overriding does not work.
Please take a closer look at this.

**Comment by ghost** [comment]
Reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21800">issues.joomla.org/tracker/joomla-cms/21800</a>.</sub>

**Comment by infograf768** [comment]
It looks like it is broken here too. 
If it is confirmed, it is a major break.

**Comment by infograf768** [comment]
To help solve the issue:
If we go into Articles Options, we do get the choice:

<img width="479" alt="screen shot 2018-08-22 at 07 34 48" src="https://user-images.githubusercontent.com/869724/44444612-e8fc3b80-a5dd-11e8-8b2a-635c4c8af3ad.png">

But in the category blog menu item we don't
<img width="512" alt="screen shot 2018-08-22 at 07 36 32" src="https://user-images.githubusercontent.com/869724/44444647-2365d880-a5de-11e8-937d-88511af360b3.png">

**Comment by SharkyKZ** [comment]
@infograf768 this is expected behavior. See #21175 comments.

**Comment by infograf768** [comment]
You are evidently right.
We have to create a custom xml in order to propose it as new menu item type.

<img width="246" alt="screen shot 2018-08-22 at 08 02 30" src="https://user-images.githubusercontent.com/869724/44445874-fcf66c00-a5e2-11e8-810d-1abc360de07a.png">

The xml can be a copy of the core one EXCEPT its layout name
```
<layout title="COM_CONTENT_CATEGORY_VIEW_MY_BLOG_TITLE" option="COM_CONTENT_CATEGORY_VIEW_MY_BLOG_OPTION">
		<help key = "JHELP_MENUS_MENU_ITEM_ARTICLE_CATEGORY_BLOG" />
		<message>
			<![CDATA[COM_CONTENT_CATEGORY_VIEW_BLOG_DESC]]>
		</message>
	</layout>
```
In order to choose it (I did not create a string here)
<img width="755" alt="screen shot 2018-08-22 at 08 15 45" src="https://user-images.githubusercontent.com/869724/44446045-a9d0e900-a5e3-11e8-81dc-5a6af400ae43.png">

**Comment by infograf768** [comment]
Closing as explanations have been given in details...

**Comment by infograf768** [comment]
Docs:
https://docs.joomla.org/Layout_Overrides_in_Joomla#Alternative_Menu_Items

**Comment by Gnevyshev** [comment]
But i don't want to override menu Item.
I want to override blog layout.
Joomla offers it in Category edit Options.
But it doesn't work.

**Comment by infograf768** [comment]
@Gnevyshev 
The possible layout override in category edit Options in the blog menu item ONLY concerns articles displayed by the blog NOT the blog itself.

If you want to always override the joomla blog layout, then just add in html the files concerned with the SAME name as in core and modify them to fit.
If you want the choice between 2 types of blog layout, create a menu item type as stated above.

**Comment by ghost** [comment]
This needs a simple User Interface.

**Comment by Gnevyshev** [comment]
@infograf768
Yes, I see that now it works that way. But it's not right. It would be better if we could set the layout for category.

**Comment by SharkyKZ** [comment]
@Gnevyshev the `Layout` option from category is used for categories that have no menu item. If your category has a menu item, it will use the layout from menu item.

**Comment by infograf768** [comment]
BTW: the interface to create overrides in a template exists through The overrides tab
<img width="1153" alt="screen shot 2018-08-22 at 09 00 11" src="https://user-images.githubusercontent.com/869724/44447867-da1b8600-a5e9-11e8-8a7b-9401ceb6d91e.png">

There one can copy/rename/edit/create the necessary files.

**Comment by ggppdk** [comment]
> But i don't want to override menu Item.
I want to override blog layout.
Joomla offers it in Category edit Options.
But it doesn't work.

I think the language string description can have some improvement 

The 'Layout' in category options

Is used when
- no active menu item
- there is an active menu item but it is not a category view menu item

----

About "Choose layout" in category menu item it is not so clear that it is about articles

**Comment by ggppdk** [comment]
I have not tested anything, i was only looking at source code, so i could be wrong

**Comment by Gnevyshev** [comment]
@SharkyKZ
> the Layout option from category is used for categories that have no menu item. If your category has a menu item, it will use the layout from menu item.

Understand.

@ggppdk, agree.

**Comment by coolcat-creations** [comment]
Agree, this issue has been raised already so many times that we should not just close it but improve it. Otherwise we will have this discussion over and over again.
