### ISSUE TITLE
[4.0] If Message is shown, only small Part of Button is clickable

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21803]
### Steps to reproduce the issue
![screen shot 2018-08-22 at 06 53 01](https://user-images.githubusercontent.com/8235763/44443571-ab48e400-a5d8-11e8-81d7-e49b6ab35a63.jpg)

In Example above only small Button-Part below "Close" is clickable. 
### Expected result
All showing Button-Part is clickable.
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by Quy** [comment]
Duplicate #25850
