### ISSUE TITLE
[4.0] Backend toolbar overlays user-dropdown

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#21815]
### Steps to reproduce the issue
In the backend klick on the user-icon for logging out. 
In the dashboard this is fine. 

If there is a toobar, the toolbar lays over the dropdown.

 ![screen shot 2018-08-22 at 21 50 35](https://issues.joomla.org/uploads/1/d7f32bcb966309d3d1774bd095a9ccb8.png)

**Comment by brianteeman** [comment]
This is my fault trying to fix the zindex issue with modals so that at least.patchtester was usable

**Comment by chmst** [comment]
The patchtester *cry*

**Comment by brianteeman** [comment]
Fixed see #22610
