### ISSUE TITLE
[4.0] Create New Workflow

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21819]
When you create a new workflow it automatically creates one new stage for published. I am not sure what the logic is behind this but its not very useful. Sure it means that you can create a new article ad this is the minimum required but it leads to confusion about why you cant delete or unpublish an article etc.

My thinking is that when you create a new workflow it automatically creates the "default" stages and transitions. This creates no extra work for the user. Instead of having to create them they just have to edit them (if required). The benefit is that you probably wont end up forgetting to create a delete stage or a transition to delete. etc

A quick test with the code in the save function in WorkflowModel seems to make it much easier to work with creating a new workflow.

Thoughts? 

@bembelimen @wilsonge @HLeithner

**Comment by ghost** [comment]
> when you create a new workflow it automatically creates the "default" stages and transitions

That would help and be "expected Behaviour".

**Comment by HLeithner** [comment]
No sure if this is better then no entry, only "published" makes not much sense that's true.

A complete workflow example should be in sampledata plugin and if you create a new workflow it should be empty but both is ok for me.

**Comment by wilsonge** [comment]
> when you create a new workflow it automatically creates the "default" stages and transitions

Depends what you mean by default :) I think that for new workflows unpublished has to be default. We also won't want the archived flow by default too I think.

**Comment by brianteeman** [comment]
By default I mean the same as currently created on install and called joomla default

Sampledata plugin is a different issue

**Comment by bembelimen** [comment]
The idea behind the published only stage was:
don't pollute the new workflow with potential unnecessary stages, because imho at the end the goal of each workflow is to publish/finish something. All other stages are optional. With a new workflow article are not automagical published without user interaction. So I'm not sure if we should add more than published to a new workflow (less is also not recommended, because then the workflow is broken)

**Comment by brianteeman** [comment]
> With a new workflow article are not automagical published without user interaction

Sorry I don't understand that statement

**Comment by brianteeman** [comment]
This also has a benefit that if a user messes up their workflow (and given the opportunity they will) they can easily create a new fully working workflow

**Comment by ghost** [comment]
closed as having Pull Request #21963
