### ISSUE TITLE
[4.0][workflow] - delete an article

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#21818]
### Steps to reproduce the issue
delete an article

### Expected result
you can delete an article

### Actual result

maybe i'm blind, but there is no way to delete an article

**Comment by infograf768** [comment]
It has become a quite complex task... GRRR

![article-delete](https://user-images.githubusercontent.com/869724/44510901-364bdc00-a6b6-11e8-8bfe-83c74c903243.gif)

**Comment by ghost** [comment]
less complex, more new Behaviour ;-)

**Comment by alikon** [comment]
quite happy  to be not so blind,  i'm only a simple mind,
btw i don't like this way .... too complex/ too many click  etc....

**Comment by simbus82** [comment]
And if you delete a Workflow, you can never delete an article, because all articles disappear...

**Comment by bembelimen** [comment]
The number of clicks did not increase? First you trash the article, then you filter for trashed items abd delete them...like in J! 3.

@simbus82 see: #21579

**Comment by brianteeman** [comment]
Count the number of clicks to trash an article
In J3 it is just two

**Comment by bembelimen** [comment]
Ok, you're right, one click more...but the principle is the same

**Comment by Bakual** [comment]
I didn't even know that clicking the green checkmark does reveal a dropdown with the states. I saw that in a screenshot already but couldn't figure out how to get that dropdown.

I'd say it's either not intuitive at all, or I'm just to stupid to figure that out.
On a related note, unpublishing multiple articles has now to be done using batch?

**Comment by brianteeman** [comment]
batch for everything seems to be the design concept here

**Comment by bembelimen** [comment]
See #21708 as wip

And clicking the button, well it's the same button as in other lists:

![grafik](https://user-images.githubusercontent.com/1229869/44552443-9b411980-a72a-11e8-8ed5-4db49d676fe1.png)

**Comment by Bakual** [comment]
> And clicking the button, well it's the same button as in other lists:

Yeah, the button is the same, but it does something different. In other places, clicking the button the state is directly toggled eg from published to unpublished. And there is a tooltip indicating what will happen when you press it.
But here we have no clue that clicking the button (which directly unpublishes in all other places) will reveal a dropdown. That's what I mean with "not intuitive".

**Comment by ghost** [comment]
closed as having Pull Request ##22393
