### ISSUE TITLE
Can someone please share the workflow code for content publishing 

### ISSUE THREAD

**Issue by MauriceTerer** [joomla/joomla-cms#21823]

**Comment by brianteeman** [comment]
Closed due to lack of any information

**Comment by MauriceTerer** [comment]
i am currently implementing a corporate site with several number of users and their requirement is that there be workflows where an author writes and article then an editor goes through the article and reviews who will then reject it and send it back or forward it to the editor who will then publish the article if satisfied. I have been going through online articles but not able to identify the proposed com_workflow
