### ISSUE TITLE
[4.0] Workflows not multilingual

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21825]
Surprised its not  been mentioned before but the workflows are not translatable. So this means that in the article list for example we have english even if the site is in french. Remember that the word "published" in this screenshot is the name of the stage not the actual status - they just happen to be the same in this example

![image](https://user-images.githubusercontent.com/1296369/44529804-dae51280-a6e4-11e8-819b-b0e3430ea122.png)

**Comment by ot2sen** [comment]
Do the French temporary language pack have these strings yet, or might it just be fall back to English when those are not available?

**Comment by brianteeman** [comment]
If only it was that simple. What is being displayed here is the value of a field. So it can be whatever you want it to be - it just can't be translated 
`<?php echo $this->escape($item->stage_title); ?>`

**Comment by infograf768** [comment]
I have already discussed that with @bembelimen 

There is a first patch here to test:
https://github.com/joomla/joomla-cms/pull/21506

Then some more will come. Basically it will work like custom admin menu items where the title is displayed through Text::_(). Some strings obviously already exist (JPUBLISHED, JTRASHED, JUNPUBLISHED, JARCHIVED) other will come from workflow ini, custom ones will need users to create strings for their custom workflows.

**Comment by infograf768** [comment]
> Do the French temporary language pack have these strings yet, or might it just be fall back to English when those are not available?

we do not have French or German or Persian temporary languages.
We are using for now the packs from 3.x

So, the strings above already exist in these packs, but not the new strings from com_workflow

And yes, new ones will be replaced for the moment (after future patches) by English when not present in these lang packs.
Below example for the action `Publish`, etc.
<img width="362" alt="screen shot 2018-08-23 at 17 47 50" src="https://user-images.githubusercontent.com/869724/44536439-c745a600-a6fc-11e8-92af-deb87d52b65c.png">

**Comment by brianteeman** [comment]
Closed as duplicate
