### ISSUE TITLE
[4.0] Site Statistic Module Fatal error

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#21820]
### Steps to reproduce the issue
Create a Site Statistics Module
Publish it.

### Actual result
`Fatal Error: Column 'id' in field list is ambiguous: Column 'id' in field list is ambiguous`

System information
Nightly Build 4.0.0-alpha5-dev 8/23

**Comment by brianteeman** [comment]
it's another problem from workflows :(

https://github.com/joomla/joomla-cms/blob/304cac87c2d27127b12ac7a061a5468eecbe753b/modules/mod_stats/Helper/StatsHelper.php#L97

**Comment by ghost** [comment]
closed as having Pull Request #21824
