### ISSUE TITLE
How to add entries to #__action_logs_extensions

### ISSUE THREAD

**Issue by Hackwar** [joomla/joomla-cms#21831]
The Privacy Suite contains a table #__action_logs_extensions, which controls some behavior for extensions. Right now each extension that wants to add data into that table needs to do that by raw SQL queries. We should add an API to add these entries. This was pushed back for 3.9, as this is a minor feature and should not delay the release of 3.9 further.

**Comment by Devportobello** [comment]
After small test, if we add new line in #__action_logs_extensions, we need also to setup #__action_log_config

Actually, PR #22389 give ability to log action but no sure if this is enough

**Comment by Quy** [comment]
https://docs.joomla.org/Make-your-own-action-log-plugin

Please close if it provides the information you need.
