### ISSUE TITLE
Module "Articles - Newsflash" is not displaying featured articles

### ISSUE THREAD

**Issue by radik10** [joomla/joomla-cms#21833]
### Steps to reproduce the issue
1 - create few articles in one category, some of them make "featured"
2 - set up module "Articles - Newsflash" and choose created category, 
3 - for "featured" choose "show" (in module settings: "Featured Articles > Show")

### Expected result
in module, on frontend, must be visible normal articles and featured too

### Actual result
not visible featured articles in module, only normal articles

### System information (as much as possible)
DB: mysql 5.5.40-36.1
PHP: 5.6.20

**Comment by SharkyKZ** [comment]
Fixed with #21336. Fix will be included in 3.8.12.

**Comment by ghost** [comment]
Closed as duplicate Report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21833">issues.joomla.org/tracker/joomla-cms/21833</a>.</sub>
