### ISSUE TITLE
[4.0] Batch - Copy Move - An error has occurred. 0 Class - JEventDispatcher not found

### ISSUE THREAD

**Issue by pepperstreet** [joomla/joomla-cms#21839]
### Steps to reproduce the issue

Select one or multiple articles in article manager. 
Click **Batch** button. 
Choose **copy or move** to another category.

### Expected result

Article(s) should be moved or copied to new location.

### Actual result

Article stays in original location. 
Category does not change.

Error message appears: 
An error has occurred.
_0 Class 'Joomla\Component\Content\Administrator\Model\JEventDispatcher' not found_

### System information (as much as possible)

alpha 4

**Comment by ghost** [comment]
@pepperstreet  Thanks for Report. The Issue has been reported #21285 so closed as duplicate Report.

**Comment by pepperstreet** [comment]
@franz-wohlkoenig 
Oops, sorry! Probably I did my search in "open" issues only. ;)

**Comment by ghost** [comment]
Next Time you know ;-)
