### ISSUE TITLE
[4.0] [workflow] Default workflow can be deleted

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#21843]
### Steps to reproduce the issue
display workflows
trash
filter by trashed
Delete

### Expected result
It should be forbidden to delete/trash/disable/modify the default workflow

### Workflow is deleted
Articles do not show anymore in manager.

**Comment by brianteeman** [comment]
Not at my pc but I am sure there is a pr for this already

**Comment by infograf768** [comment]
see https://github.com/joomla/joomla-cms/pull/21579
