### ISSUE TITLE
Stages/Transitions should not be always visible in article

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#21841]
### Steps to reproduce the issue
- Create a new workflow
- Set it as default
- Delete the default workflow
- Go to articles
- click on the left site on "Stages"

### Problem
You cannot estimate the "active workflow" from the article view. The following PR broke the behavior: https://github.com/joomla/joomla-cms/pull/21709

### Solution
It makes no sense to have an article => stage connection, it has always to be Article => Workflow => Stage

**Comment by chmst** [comment]
This is right. 
Despite of that - the sidebar will be removed completely.

**Comment by ghost** [comment]
closed as having Pull Request #21842

**Comment by brianteeman** [comment]
Problem
You cannot estimate the "active workflow" from the article view.

That is still a valid problem. 

Perhaps a read-only field displaying the active workflow could be displayed near the status select?
