### ISSUE TITLE
[4.0] Unable to find install package when click install language

### ISSUE THREAD

**Issue by pdutie94** [joomla/joomla-cms#21848]
### Steps to reproduce the issue
Click to install language

### Expected result
Install language complete

### Actual result
Alert "Unable to find install package"

### System information (as much as possible)
PHP Version : 7.0.29
Webserver : Apache/2.4.33 (Win32) OpenSSL/1.0.2n PHP/7.0.29
Joomla version : Joomla! 4.0.0-alpha4 Alpha [ Amani ] 22-July-2018 22:52 GMT

**Comment by ghost** [comment]
@pdutie94 Thanks for Report. The Issue has been reported #21806 so closed as duplicate Report.
