### ISSUE TITLE
[4.0] Wrong message when disabling the default stage

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#21846]
### Steps to reproduce the issue
You must have several stages in the stages view, one of them is marked as default.
Now disable the default stage. 

### Expected result
A message "You cannot disable the default item"

### Actual 
Message "You cannot delete the default item"

![screen shot 2018-08-25 at 23 01 26](https://issues.joomla.org/uploads/1/26ce10ff2044426993184b59a0353ce6.png)

**Comment by brianteeman** [comment]
You also get the wrong message when you try to make an unpublished workflow the default

![image](https://user-images.githubusercontent.com/1296369/44634147-7bf5f680-a98d-11e8-86c8-36c1d6683d25.png)

**Comment by Quy** [comment]
Closing per PR #22594<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21846">issues.joomla.org/tracker/joomla-cms/21846</a>.</sub>
