### ISSUE TITLE
[4.0] com_workflow: Don't allow unpublish default Workflow

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21859]
### Is your feature request related to a problem? Please describe.
Its possible to unpublish default Workflow, so User get:

![screen shot 2018-08-27 at 07 16 30](https://user-images.githubusercontent.com/8235763/44641882-a82f6880-a9c9-11e8-92d0-ecf59f7a7714.jpg)

If User create a new Article it can't be saved as getting `Error: Save failed with the following error: No default workflow available, please define one or contact an administrator.`

![screen shot 2018-08-27 at 07 21 29](https://user-images.githubusercontent.com/8235763/44641930-01979780-a9ca-11e8-95c5-2e8c61b1ae37.jpg)

### Describe the solution you'd like

Unpublish default Workflow isn't allowed. Notice on User like unpublish Home-Menu (`Error: Can't unpublish default home.`)

**Comment by brianteeman** [comment]
See #21870
