### ISSUE TITLE
[4.0] Tabs broken when editing menu items

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#21855]
As title says.

**Comment by chmst** [comment]
I had this effect too. I had installed this PR: https://github.com/joomla/joomla-cms/pull/21852/commits/321cfeb37d37f5613d66276bf3ce09ffa4fd6e1d? 

I have reverted this change and made the npm install, now it is all right again<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21855">issues.joomla.org/tracker/joomla-cms/21855</a>.</sub>

**Comment by chmst** [comment]
I am not sure if there is a coincidence. I was just a try.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21855">issues.joomla.org/tracker/joomla-cms/21855</a>.</sub>

**Comment by brianteeman** [comment]
how are they broken - there are so many different ways that something can be broken

**Comment by dgrammatiko** [comment]
It’s related to session storage and the tab state. Nothing to do with the other pr.

**Comment by chmst** [comment]
@brianteeman 
I could not change between tabs, I had several tabs marked as active at the same time, some tab contents were below the active tab. The html-validator gave lots of errors, but no errors in the console.

**Comment by brianteeman** [comment]
@chmst Thank you for describing the issue.

**Comment by infograf768** [comment]
Reverting to bootstrap instead of uitab for menu item edit could solve temporarily the issue.
I discussed yesterday this issue with @dgrammatiko who is not in favor of this solution.
One way to go —until a real solution is coded— is to click on each tab one after the other until it works again. A bit of a pain when testing other stuff but good to know.

**Comment by infograf768** [comment]
BTW, found out while looking at this yesterday that the file `/administrator/components/com_menus/tmpl/item/edit_options.php` looks like totally useless in 4.0.
Could someone confirm or not this?

**Comment by anuragteapot** [comment]
Please test this PR https://github.com/joomla-projects/custom-elements/pull/97

@brianteeman @infograf768

**Comment by anuragteapot** [comment]
https://github.com/Anu1601CS/custom-elements/blob/tab/src/js/tab/tab.js

or copy this code in `media/vendor/joomla-custom-element/js/joomla-tab.js`
And make sure you have enabled `debug` mode to load `joomla-tab.js` file.

**Comment by ghost** [comment]
@infograf768 can you please test as @Anu1601CS mentioned above?

**Comment by infograf768** [comment]
I can't reproduce this issue anymore on dev branch. Closing.
