### ISSUE TITLE
Associations - delete / delete orphans

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21869]
Is it correct that the buttons disappear as shown in the video below. Its the same in j3 - just seems odd to me.

![associations](https://user-images.githubusercontent.com/1296369/44682114-6ee31100-aa3a-11e8-9cf0-b7db3f4b7894.gif)

**Comment by infograf768** [comment]
It is correct. We designed it this way.

**Comment by brianteeman** [comment]
Could you please explain the reasoning and logic behind this. I was surprised it disappeared and assumed it was a bug because you have always insisted that we dont add or remove buttons from the toolbar

**Comment by infograf768** [comment]
These 2 buttons will always display when getting to the Associations Manager before choosing item type and language. Therefore they are NOT hidden.
They are just totally useless when one starts working on items. That was the reasoning at this time in the GSOC project and nobody complained about that since the feature was implemented in 2016.

**Comment by brianteeman** [comment]
I am very surprised because you have always and repeatedly blocked anything else from not being displayed when it is completely useless. I trust this means that you have seen the error in your ways and will now stop insisting that things must be displayed even they are "totally useless".

**Comment by infograf768** [comment]
Is it really necessary I reply further? 
You are repeatedly interpreting wrongly my position on this matter.
I have said and I repeat it: when something can be done ON THE PAGE WHERE IT IS NECESSARY TO KNOW IT CAN BE DONE, do not hide it.
In this specific case, all users getting to the Associations Manager KNOW it can be done AS THEY ARE FORCED TO PASS BY THIS PAGE before switching to what should be considered as another page after choosing an item type AND language. 
It is therefore a totally different situation.
Refusing to admit it is your problem.

Issue closed for me.

**Comment by brianteeman** [comment]
Makes no sense at all

**Comment by brianteeman** [comment]
I am re-opening this as I still don't understand the logic behind having the delete buttons only visible on a page that does not show any associations

**Comment by ghost** [comment]
@brianteeman  what software you use to create this image above ?

**Comment by brianteeman** [comment]
Licecap - it is free software available for all platforms

**Comment by lavipr** [comment]
Hi, I'm working on it for 4.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21869">issues.joomla.org/tracker/joomla-cms/21869</a>.</sub>

**Comment by infograf768** [comment]
It is totally useless to display these toolbar buttons when one has already displayed items and their possible associations. Adding them happily has no undesired consequences.

**Comment by alikon** [comment]
closed as expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21869">issues.joomla.org/tracker/joomla-cms/21869</a>.</sub>
