### ISSUE TITLE
[4.0] Custom admin menu: sql error when trying to use presets

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#21861]
### Steps to reproduce the issue
Create a custom admin menu, choosing a preset

### Expected result
All adminmenu items created

### Actual result
sql error

```
Message
Menu was saved but failed to import the preset: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') GROUP BY c2.`id`) AS c2 ON c2.newId = c.`id` SET `published` = c2.newPublished' at line 6
```

### Note:
This was working before workflow afaik

@alikon

**Comment by alikon** [comment]
i can confirm, not sure caused by workflow .... need more time for investigation...

**Comment by infograf768** [comment]
It also could be related to last night merges. Not sure either.

**Comment by brianteeman** [comment]
Pretty certain this is an old error already reported and nothing to do with workflows or other r cent changes

**Comment by brianteeman** [comment]
Closed as duplicate #18684

**Comment by infograf768** [comment]
It was working on July 15...
https://github.com/joomla/joomla-cms/issues/21125

**Comment by infograf768** [comment]
Re-closing as #21125 did not concern presets
