### ISSUE TITLE
[4.0] com_fields: Type "checkboxes", "list" and "radio" don't work

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21877]
### Steps to reproduce the issue
- create a com_field Type "Checkboxes"
- click on green "+"-Button to append Text and Value
### Expected result
new Row is opening to write Text and Values.
### Actual result
Nothing happen. No Error in Browser-Console.
Edit: Same Behaviour using "List", "Radio" in Users, Articles, Contacts.
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by brianteeman** [comment]
Closed as I assume it has been resolved elsewhere as I can not replicate it
