### ISSUE TITLE
[4.0] Shorten Explanation of "Pinned"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21879]
Create new banner, User get an Explanation for "Pinned":
##### Joomla 4
![screen shot 2018-08-28 at 11 38 48](https://user-images.githubusercontent.com/8235763/44715488-3aae3580-aab8-11e8-8586-9bd9c7d37480.jpg)
##### Joomla 3
User get this if hover:
![screen shot 2018-08-28 at 11 38 34](https://user-images.githubusercontent.com/8235763/44715505-44379d80-aab8-11e8-9883-3b0cac0a0d49.jpg)
### Describe the solution you'd like
Short Description like "Take priority over not pinned Banners." and a Link to a Help-Site.
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by brianteeman** [comment]
I agree 100% - the **only** reason I have never touched that text is because I don't understand it at all

**Comment by ggppdk** [comment]
Maybe this new description:
Ordering places 'binned' banners at the start of the list

**Comment by brianteeman** [comment]
If only that was true ;)

**Comment by ggppdk** [comment]
hhmm the only reference i found in the source code, regarding display was in ordering these first

e.g. i do not see 'sticky' property causing an ignoring

of unpublished state 
or of access level
or of publish up / down dates
etc

i only found the ordering effect
so there is more to it ?

**Comment by brianteeman** [comment]
hint - look at the module options

**Comment by ggppdk** [comment]
In the banners modules

I see only the "randomize" (of ordering) option,
which i have already see the source code
in both cases the ordering places them at the top of the list

Pinned, Ordering
Pinned, Randomize

is there some other setting, that i have missed ?

**Comment by puneeth-chanda** [comment]
I can work on this if I get the link to the so-called help site? Can you give me the link please..

**Comment by Quy** [comment]
Please test PR #23836<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21879">issues.joomla.org/tracker/joomla-cms/21879</a>.</sub>
