### ISSUE TITLE
[4.0] Post-installation Messages: "Hide all messages" don't work

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21875]
### Steps to reproduce the issue
- Open `index.php?option=com_postinstall`
- click on Button "Hide all messages"
### Expected result
All messages are gone.
### Actual result
Messages stay as before Click. No Error in Browser-Console.
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by brianteeman** [comment]
This is coming from Merge commit 'ac792d8' into 4.0-dev by @wilsonge last night

**Comment by ghost** [comment]
close Issue?

**Comment by brianteeman** [comment]
no - its a bug to fix - i was just pointing out the origin for @wilsonge

**Comment by wilsonge** [comment]
I had to try something a bit major to fix conflicts on this one cause in 4.0 this component got reworked away from FOF. If anyone wants to give it a go feel free. Else I'll try and find time tonight.

**Comment by brianteeman** [comment]
Closed see #21882
