### ISSUE TITLE
[4.0] Don't install Module "Multilanguage status"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21872]
### Steps to reproduce the issue
Install "Multilingual Sample Data".

In Backend User get Module "Multilanguage status":
![screen shot 2018-08-28 at 07 00 03](https://user-images.githubusercontent.com/8235763/44701803-be542c00-aa90-11e8-8c7c-577ea9ae2b37.jpg)

which is unnecessary as Multilanguage Status is shown right Top:
![screen shot 2018-08-28 at 07 05 46](https://user-images.githubusercontent.com/8235763/44701842-e3489f00-aa90-11e8-82d9-639f8cf33233.jpg)
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by infograf768** [comment]
The multilanguage status module is displayed as published with no position. It is THAT instance which is used automatically. It has to be present in the Modules manager. 
Expected behavior.

**Comment by ghost** [comment]
> It has to be present in the Modules manager.

Got it, from UX-Point of View would be better to hide Module, closing as expected Behaviour.
