### ISSUE TITLE
[4.0] Mass Mail Users: Align "Select" and "Text"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21876]
### Steps to reproduce the issue
Open `index.php?option=com_users&view=mail` User get:

![screen shot 2018-08-28 at 10 53 08](https://user-images.githubusercontent.com/8235763/44712404-f3707680-aab0-11e8-8320-5344236aff1f.jpg)
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by brianteeman** [comment]
Closed see #21878
