### ISSUE TITLE
[4.0] SQL error related to workflow shown in control panel after installation of current 4.0-dev with PostgreSQL DB

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#21889]
### Steps to reproduce the issue

Pull latest changes from the 4.0-dev branch so you have the latest corrections of joomla.sql for PostgreSQL from today's merged PR's and do the composer install and npm install stuff in case if there have been other changes meanwhile which require this.

Then do an installation using a PostgreSQL database.

Result: Installation finishs with success.

Login to the administrator backend.

### Expected result

The control panel does not show SQL errors.

### Actual result

The control panel shows an SQL error:
![screen shot 2018-08-28 at 14 59 23](https://issues.joomla.org/uploads/1/aba1785679a1d9d554d2bca9c8c47ecc.png)

In the log file of PostgreSQL (if logging is switched on):
`2018-08-28 16:52:53.963 CEST [108726] jdb2adm@joomladb2 ERROR:  invalid input syntax for integer: "f"
2018-08-28 16:52:53.963 CEST [108726] jdb2adm@joomladb2 STATEMENT:  INSERT INTO "j4ux0_session"
        ("session_id","guest","time","userid","username","client_id") VALUES 
        ($1, $2, $3, $4, $5, $6)
2018-08-28 16:52:54.030 CEST [108727] jdb2adm@joomladb2 ERROR:  syntax error at or near "WHERE" at character 937
2018-08-28 16:52:54.030 CEST [108727] jdb2adm@joomladb2 STATEMENT:  SELECT a.id, a.title, a.checked_out, a.checked_out_time,  a.publish_up, a.hits,l.title AS language_title, l.image AS language_image,uc.name AS editor,ag.title AS access_level,c.title AS category_title,ua.name AS author_name,"wa"."stage_id" AS "stage_id","ws"."title" AS "stage_title","ws"."condition" AS "stage_condition","ws"."workflow_id" AS "workflow_id",COALESCE(NULLIF(ROUND(v.rating_sum  / v.rating_count, 0), 0), 0) AS rating,
                                                COALESCE(NULLIF(v.rating_count, 0), 0) as rating_count
        FROM j4ux0_content AS a
        LEFT JOIN "j4ux0_languages" AS l ON l.lang_code = a.language
        LEFT JOIN j4ux0_users AS uc ON uc.id=a.checked_out
        LEFT JOIN j4ux0_viewlevels AS ag ON ag.id = a.access
        LEFT JOIN j4ux0_categories AS c ON c.id = a.catid
        LEFT JOIN j4ux0_users AS ua ON ua.id = a.created_by
        INNER JOIN "j4ux0_workflow_associations" AS "wa"
        INNER JOIN "j4ux0_workflow_stages" AS "ws"
        LEFT JOIN j4ux0_content_rating AS v ON a.id = v.content_id
        WHERE "wa"."item_id" = "a"."id" AND "ws"."id" = "wa"."stage_id" AND "ws"."condition" IN (1, 0) AND "wa"."extension"='com_content'
        ORDER BY a.hits DESC LIMIT 5`

### System information (as much as possible)

PHP 7.2
postgresql 10.5 (Ubuntu 10.5-0ubuntu0.18.04)

### Additional comments

There could be 2 errors as far as I can see in the postgresql log file: One related to insert into the session table, and the other one related to workflow stuff.

**Comment by richard67** [comment]
There could be 2 errors as far as I can see in the postgresql log file: One related to insert into the session table, and the other one related to workflow stuff.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21889">issues.joomla.org/tracker/joomla-cms/21889</a>.</sub>

**Comment by richard67** [comment]
Someone should add labels "J4 Issue" and "New Feature Workflow".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21889">issues.joomla.org/tracker/joomla-cms/21889</a>.</sub>

**Comment by alikon** [comment]
for the insert issue:
 don't know if this changes #20386 are already in the 4.0 branch

**Comment by brianteeman** [comment]
@richard67 no need to ask for labels to be added or for PR to be merged - it just adds even more messages to our inboxes. These tasks will happen when the "volunteers" that do this have the time to do it.

**Comment by richard67** [comment]
@brianteeman Ok, sorry for that.

**Comment by alikon** [comment]
@richard67
#21893  should fix the 500 error

**Comment by ghost** [comment]
closed as having Pull Request #21893
