### ISSUE TITLE
'# Columns' is missed in Blog Layout

### ISSUE THREAD

**Issue by pcc00** [joomla/joomla-cms#21890]
**Joomla 4 Alpha 5**
### Steps to reproduce the issue

Go to 'Menus' - 'Main Menu' - 'Add New Menu Item'
In 'Menu Item Type' Select 'Articles' - 'Category Blog'
Go to 'Blog Layout' tab and '# Columns' is missed.

**Comment by ghost** [comment]
@pcc00 Thanks for Report. The Issue has been reported #21106 so closed as duplicate Report.
