### ISSUE TITLE
loadmodule used more then once within an article

### ISSUE THREAD

**Issue by boschmaHH** [joomla/joomla-cms#21896]
### Steps to reproduce the issue
- fresh install Joomla 3.8.12
- create new custom module with some content
- create new article
- put in some content and loadmodule of the cretaed custome module
- repeat within the same article / content plus loadmodule several times
text
{loadposition position-4}
text
{loadposition position-4}
text
{loadposition position-4}
text
- connect menu-item with article 
- check created HTML

### Expected result
- on each position the module is loaded, there should be just one headline and one wrapping div-combination of div-class-custom and div-class-moduletable

### Actual result
- on the first position where the module is loaded it's fine
- second, doubled up headline and wrapping div
- third, three headlines and three wrapping combinations of the both div
- and so on, increasing …

### System information (as much as possible)
Joomla 3.8.12
PHP 7.2.3
Need more information?

### Additional comments
It doesn't make a difference if loadposition or loadmodule is used, or if the module is on an defined or custom position.

I used this construct of calling more than one time the same module, to import an SVG mark up several times within the same article for design reasons. As the SVG will be adjusted in future, I just wanted to place it once in the module section.
Workaround for now … multiple modules with same content/ different calls within the article …

You guys are still doing a great job!
Many thanks for all that work you do!

**Comment by mbabker** [comment]
If someone's got a few free minutes search through issues looking for something related to the template's module chrome being applied multiple times.  I swear there's a similar issue or forum thread somewhere, I just don't have the time at the moment to dig for it.

**Comment by csthomas** [comment]
Do do you have disabled " Prepare Content" in custom modules?

**Comment by ghost** [comment]
Issue confirmed also as set "Prepare Content" to "Yes", see http://wohlkoenig-38.joomla.com/

![screen shot 2018-08-29 at 07 11 38](https://user-images.githubusercontent.com/8235763/44766665-cf696f80-ab5a-11e8-94f3-aad9ef59b168.jpg)
### System information
- 3.8.12
- Template: Protostar
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by boschmaHH** [comment]
it doesn't matter which template is in use ... Protostar, Beez3, or my own … output is still the same within the div-articleBody<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21896">issues.joomla.org/tracker/joomla-cms/21896</a>.</sub>

**Comment by ghost** [comment]
@boschmaHH True, i tested with 

> Template: Protostar

**Comment by ghost** [comment]
@mbabker can also remember a similar Issue reported, haven't found yet.

**Comment by SharkyKZ** [comment]
Related #12888.

**Comment by ghost** [comment]
closed as duplicate Report #12888.
