### ISSUE TITLE
PHP Parse error on autoload_real.php

### ISSUE THREAD

**Issue by aidia** [joomla/joomla-cms#21891]
### Steps to reproduce the issue
I have two domains and one multi language website. When second domain is configured to show website from the first domain the php error occurs:

PHP Parse error:  syntax error, unexpected '[', expecting ')' in /home/xxx/domains/xxx/public_html/plugins/system/regularlabs/vendor/composer/autoload_real.php on line 24

### Expected result
Despite of the positioning issues, I should see the same website

### Actual result
PHP Parse error, as above

### System information (as much as possible)
Joomla 3.8.12
MySQL 5.5.31, PHP 7.0.27 (Apache, Linux)

**Comment by ghost** [comment]
> /plugins/system/**regularlabs**/vendor/composer/

have you asked at regularlabs?

**Comment by aidia** [comment]
not yet, but is it not a bug?

**Comment by ghost** [comment]
i don't know if its a Bug i was asking as i see "/regularlabs/" which is no Core-Part.

**Comment by mbabker** [comment]
The parse error is in a file included by an extension, so there isn't a bug that we can fix in the core package for that.  I'd suggest starting with the extension vendor to debug your issue.

**Comment by ghost** [comment]
Closed as no Core Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21891">issues.joomla.org/tracker/joomla-cms/21891</a>.</sub>
