### ISSUE TITLE
Minor problem using smtp mailer using a remote server

### ISSUE THREAD

**Issue by coolman01** [joomla/joomla-cms#21905]
### Steps to reproduce the issue
Attached is an image of the settings used.

### Expected result

Mail should be correctly sent.

### Actual result

The problem is that the self.defined certificate is not accepted and no mails are sent as a result.

### System information (as much as possible)

PHP Built On	Linux srv125.tophost.ch 3.10.0-714.10.2.lve1.4.79.el7.x86_64 #1 SMP Thu Jan 4 13:30:50 EST 2018 x86_64
Database Type	mysql
Database Version	10.1.35-MariaDB
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.1.21
Web Server	LiteSpeed
WebServer to PHP Interface	litespeed
Joomla! Version	Joomla! 3.8.12 Stable [ Amani ] 28-August-2018 14:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments

The managers of the remote email server have come up with the following solution, which unfortunately got overridden with the latest release:

/public_html/libraries/vendor/phpmailer/phpmailer/class.phpmailer.php

 

                x             Alteration on Linie 275 (which may have altered)

                              

                               public $SMTPOptions = array(

                                               'ssl' => array(

                                              'verify_peer' => false,

                                              'verify_peer_name' => false,

                                              'allow_self_signed' => true

                                               )

                               );
I pass this on as information.

**Comment by coolman01** [comment]
Here the image!
[screen shot 2018-08-29 at 08 11 10](https://issues.joomla.org/uploads/1/575413729201534adc240a3b7e3558f1.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21905">issues.joomla.org/tracker/joomla-cms/21905</a>.</sub>

**Comment by mbabker** [comment]
Not quite sure what the `allow_self_signed` option actually does, but for the other two you definitely should not turn those off.  In essence that is the same as not doing any of the security validations when loading a HTTPS page but this would be in the context of email.

**Comment by brianteeman** [comment]
As phpmailer says that the changes you made are
> not recommended as it defeats much of the point of using a secure transport at all

For a full explanation see https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#certificate-verification-failure

None of this is a joomla issue

**Comment by ghost** [comment]
closed as no Core-Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21905">issues.joomla.org/tracker/joomla-cms/21905</a>.</sub>
