### ISSUE TITLE
[4.0] Notices in com_joomlaupdate

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21909]
### Steps to reproduce the issue
with php error reporting at full go to administrator/index.php?option=com_joomlaupdate

### Expected result
no errors or notices

### Actual result
Notice: Trying to get property 'version' of non-object in C:\htdocs\cms4\administrator\components\com_joomlaupdate\Model\UpdateModel.php on line 1302

**Comment by zero-24** [comment]
Can you please update the manifest cache and check if that fixes the problem?

I'm not even sure if that works anyway. As the foreach is not done by reference and the $extension var is not used any more.

**Comment by alikon** [comment]
some extensions have "false/null" in the manifest_cache field of the `#__extensions` table like `mod_submenu`

**Comment by alikon** [comment]
so unable to get the version from a null field/registry
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_joomlaupdate/Model/UpdateModel.php#L1302

**Comment by zero-24** [comment]
Yes that should be fixed by an update of the manifest cache (which should add that data). But I'm not sure what this code does at all as it seams to not have an effect as the $extensions is by value and not by ref ;)

**Comment by alikon** [comment]
not  only that module doesn't exists at all (as a core module)
and yes i'm guessing the same,  wtf   `getNonCoreExtensions()`  means in the `com_joomlaupdate`

**Comment by alikon** [comment]
ahh it was introduced by _pre update check_  #17742

**Comment by zero-24** [comment]
If so the same issue should be patched in 3.10 too: https://github.com/joomla/joomla-cms/blob/3.10-dev/administrator/components/com_joomlaupdate/models/default.php#L1379-L1391

**Comment by alikon** [comment]
maybe even on 3.9

**Comment by zero-24** [comment]
No the pre update check was moved to 3.10

**Comment by alikon** [comment]
with #21927 no more able to replicate this issue on 4.0

**Comment by zero-24** [comment]
hmm the code still looks unused and would error again when a component don't offer a version tag or is this just me wondering what this code does at all?

**Comment by alikon** [comment]
is the version tag in a xml manifest  mandatory ?

**Comment by zero-24** [comment]
My point is this is code that is not doing anything at all but maybe it is just me. ;)
