### ISSUE TITLE
getting redirect too many times error if homepage's access level is set to "registered"

### ISSUE THREAD

**Issue by newjie** [joomla/joomla-cms#21912]
### Steps to reproduce the issue
1)Create a new Joomla installation
2)Set the default page's access level to registered

### Expected result
A login window should appear when visiting the website

### Actual result
This page isn’t working
50.116.80.232 redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

### System information (as much as possible)
I've tried this on about 10 websites of various hosting, including bluehost, godaddy and my own VPS hosted on linode, and of various PHP version, most of them have this error. However, there are two that don't have this problem, one of them is hosted with ubuntu14.04/apache2/php5.6 on linode, the other is hosted with bluehost sharing host with PHP 5.6 too. Other websites that are hosted with the same linode server and same bluehost sharing host configuration do have this problem.
I've even created 2 brand new  joomla installations on linode and bluehost(using one-click install provided by bluehost and mojo marketplace, just for test's sake, but they both have this problem, admin and url are as below
**bluehost:** http://50.116.80.232/~usbsccom/test/administrator guanliyuan/guanliyuan
**linode** http://clean.nycweb.io/administrator shenkwen/guanliyuan
For those with this issue: I've tried setting default page component to login, single article, featured article, k2, non works.

### Additional comments
I suspect it has to do with server configuration/htaccess, I've compared that of working and non-working ones but couldn't find any major difference. This is a screenshot of the comparison of httpd.conf: http://aabdc.nycweb.io/compare.png, left is of the working one.

**Comment by ggppdk** [comment]
Did you try to create a menu item for the login form ?
that is both published and of public access level

and also of language all or 1 such menu item per language

if you do not have such a menu item, then login page will use the home page menu item which is not accessible

**Comment by newjie** [comment]
That does solve the issue I think. Thanks!

**Comment by ggppdk** [comment]
Duplicate closed issues

https://github.com/joomla/joomla-cms/issues/19092
https://github.com/joomla/joomla-cms/issues/15730

without re-reading the above issues (you could read them yourself) 

the end result was
the suggested fix was involved breaking B/C 
so the answer there was better require users to create some appropriate menu item than break B/C

**Comment by ghost** [comment]
closed as duplicate Report. Thanks for Comments @ggppdk <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21912">issues.joomla.org/tracker/joomla-cms/21912</a>.</sub>
