### ISSUE TITLE
Design issue related to 'edit user profile' in frontend and backend

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21920]
### Is your feature request related to a problem? Please describe.
This issue is not related to a problem.

### Describe the solution you'd like
The fields 'password' and 'confirm password' in 'edit user profile' screen in frontend (and tab in backend) should be filled with six or eight dots rather than being empty (if a password is already set).
In addition to that these fields should be marked as 'Required field'.
This would be much more user friendly.

**Comment by brianteeman** [comment]
> In addition to that these fields should be marked as 'Required field'.

Why would you force the password to be required on editing a user profile?

**Comment by brianteeman** [comment]
> (if a password is already set).

It has to be set  otherwise the user could not have logged in to see the edit user profile page

**Comment by ghost** [comment]
In my humble opinion the password is always a required field (even if it's already present).
To a regular user an empty field looks like there is no passwort present even if it is. Most of these people are no computer nerds at all.
But - because this is only a feature request - please forget it !

**Comment by brianteeman** [comment]
It makes no sense for it to be required here. You might just be opening the profile to change an address. You shouldn't have to change your password as well every time you update your profile. Remember this is an input field not an authentication

**Comment by ghost** [comment]
> You shouldn't have to change your password as well every time you update your profile.
That's absolutely correct. Therefore the 'dots' should replace the current password if the password is already present.
There are hundreds of websites doing it that way.
But as I said before - Please forget it.
