### ISSUE TITLE
Different descriptions for password field in 'user registration' and 'edit user profile'

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21923]
### Is your feature request related to a problem? Please describe.
This issue is only related to design.

### Describe the solution you'd like
For both cases the description for password field is "Enter your desired password".
In my humble opinion it would be more user-friendly to have two different descriptions for 'password' field in 'user registration' and 'edit user profile'.
E.g. For 'user registration' = "Please enter a new password of your choice here." and for 
'edit user profile' = "If desired, you can change your current password here."
This could be done by changing the placeholder in ../components/com_users/models/forms/profile.xml  in line 37 (J3.8.12) from "COM_USERS_DESIRED_PASSWORD" to e.g. "COM_USERS_PROFILE_PASSWORD1_DESC" (This is not being used yet).
In the corresponding language file the entries would show up like:
COM_USERS_DESIRED_PASSWORD="Please enter a new password of your choice here." and
COM_USERS_PROFILE_PASSWORD1_DESC="If desired, you can change your current password here."

**Comment by ghost** [comment]
can this Issue please be answered as its open for a Week having Stauts "New"?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21923">issues.joomla.org/tracker/joomla-cms/21923</a>.</sub>

**Comment by zero-24** [comment]
Well I think it is more an en-GB point here. This is nothing technical to solve as the strings are already there. Maybe we can get the opinion by @brianteeman on the suggested strings and the intention and decide what to do than.

**Comment by brianteeman** [comment]
Easy enough to do a PR to achieve this - I probably would do it slightly differently but the idea of changing the strings in the profile is a good one. I will put it on my todo list.

**Comment by ghost** [comment]
thanks for Comments @zero-24 and thanks for putting it on your Todo-List @brianteeman

**Comment by brianteeman** [comment]
closed see #22045
