### ISSUE TITLE
Able to create a folder with period/point as part of the name, but can't delete it

### ISSUE THREAD

**Issue by htmgarcia** [joomla/joomla-cms#21926]
### Steps to reproduce the issue
Go to Content > Media
Create a folder with a period/point as part of the name (as example: `something.`)
The folder is successfully created:
![a](https://user-images.githubusercontent.com/4999794/44867827-93173b80-ac4e-11e8-8eff-86479271250c.jpg)

Now, try to delete the folder. You get an error:
![b](https://user-images.githubusercontent.com/4999794/44867832-97435900-ac4e-11e8-8a23-5e8a89c08708.jpg)

### Expected result
If a folder name includes a period, we should be able to create it and delete it, OR we shouldn't at all. Consistency.

### Actual result
You can create a folder name with period as part of the name, but can't delete it.

### System information (as much as possible)
Joomla 3.8.12
Chrome 68.0.3440.106 (Official Build) (64-bit)
macOS High Sierra 10.13.6 (17G65)

**Comment by brianteeman** [comment]
I couldnt replicate this on windows

`JFolder::create: Could not create folder.Path: C:\htdocs\cms\images\something.
`

I could replicate this on linux

`Create Complete: /something.
`

**Comment by brianteeman** [comment]
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed. 

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
