### ISSUE TITLE
During update count of extracted files increases and DEcreases

### ISSUE THREAD

**Issue by manfredvdn** [joomla/joomla-cms#21922]
### Steps to reproduce the issue
Install the previous version of Joomla and then update to the current version

### Expected result
During update 4 counters are visible (percent complete, bytes read, bytes extracted and files extracted). Expected is that the values of all counters increase during the update.  

### Actual result
The value of files extracted increases and decreases

### System information
Joomla 3.8.12

I think that the issue possibly could be fixed by adjusting the file update.js of com_joomlaupdate. In the function stepExtract the line:
jQuery('#extfiles').text(data.files);

has to be changed to:
jQuery('#extfiles').text(stat_files);

**Comment by ghost** [comment]
+1

**Comment by frostmakk** [comment]
The most annoying thing is that it keeps extracting after the progress bar has reached 100%.
A proper progress bar should never reach100. It should stop at 99, and then disappear when finished.

**Comment by SharkyKZ** [comment]
@manfredvdn Can you make a pull request?

**Comment by manfredvdn** [comment]
**@SharkyKZ**
I have never made a PR before, but I give it a try next week.

**Comment by ghost** [comment]
@manfredvdn if needed: How to make a [Pull Request](https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests).

**Comment by Quy** [comment]
Please test PR #25198.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21922">issues.joomla.org/tracker/joomla-cms/21922</a>.</sub>
