### ISSUE TITLE
Users Manage search issue

### ISSUE THREAD

**Issue by nuria-sanchez** [joomla/joomla-cms#21931]
### Steps to reproduce the issue
Users/Manager/search for a **last name** that I know is part of the DB

### Expected result
The user or users with that last name should display

### Actual result
Doesn't show any results, because it seems that the feature only searches for first names, not last names, unless the last name is part of the _username_

### System information (as much as possible)
version: Joomla 3.8.6
Operating systems: OS and Windows

### Additional comments
I have around 1500 users and I am constantly using the SEARCH feature, therefore, this bug is really annoying. Would be awesome if you can fix it. Thanks!

**Comment by brianteeman** [comment]
There is only a single name field in joomla. Not two separate fields for last name and first name.

**Comment by nuria-sanchez** [comment]
So, there is no way to search for a last name?

**Comment by brianteeman** [comment]
Screenshot showing search of a.last name.
![screenshot_20180831-012510 2](https://user-images.githubusercontent.com/1296369/44886218-02c40f80-acbd-11e8-9aa7-d769271bb494.png)

**Comment by nuria-sanchez** [comment]
Hmm… 
Look at this, I will search for Maria Banda, that you can see that her name displays if I just type Maria:





But I have 150 Marias on my DB. I would need to be able to find that specific Maria easier:


So, I necessarily have to type Maria and then go manually through the whole results list to find her. 
I am a web developer, but this is the only site that I manage now that has users, so I don’t have another one to compare to. My programmer, and the client, also complain about the same issue.

Am I missing something and doing something wrong?? Or any ideas why is not working for us?
Would really appreciate any help.

**Comment by brianteeman** [comment]
Did you intend to post a screenshot?

**Comment by nuria-sanchez** [comment]
Yes, a few, through replying to your email.
Is that not possible?




Nuria Sanchez / President
Phone 702-222-1880 
Las Vegas, NV
iworldclassdesign@gmail.com

**Comment by brianteeman** [comment]
Not via email. You will need to do it on the web site

**Comment by nuria-sanchez** [comment]
Ok, here it goes again:

Look at this, I will search for Maria Banda, that you can see that her name displays if I just type Maria:
![screen shot 2018-08-31 at 00 51 53](https://issues.joomla.org/uploads/1/eaecd74a4a37232489fb18c8f0bb50a7.jpg)

But I have 150 Marias on my DB. I would need to be able to find that specific Maria easier:
![screen shot 2018-08-31 at 00 52 43](https://issues.joomla.org/uploads/1/d246e7e8bd3848d4b1ca774e9c6fde52.png)![screen shot 2018-08-31 at 00 52 44](https://issues.joomla.org/uploads/1/80ac17ed8fda10d41568f3d18bc6f82c.png)![screen shot 2018-08-31 at 00 52 46](https://issues.joomla.org/uploads/1/0e9a7b2361270d7f0f809ec919d49986.png)![screen shot 2018-08-31 at 00 52 47](https://issues.joomla.org/uploads/1/93db07fe270d353d3a9378e294e6e70b.png)

So, I necessarily have to type Maria and then go manually through the whole results list to find her.
I am a web developer, but this is the only site that I manage now that has users, so I don’t have another one to compare to. My programmer, and the client, also complain about the same issue.

Am I missing something and doing something wrong?? Or any ideas why is not working for us?
Would really appreciate any help.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21931">issues.joomla.org/tracker/joomla-cms/21931</a>.</sub>

**Comment by brianteeman** [comment]
As can be seen by the following screenshots on a clean install of Joomla I cannot replicate the problem

<img width="376" alt="chrome_2018-08-31_08-00-30" src="https://user-images.githubusercontent.com/1296369/44897618-2fdfe480-acf4-11e8-995c-d2f622dd0276.png">
<img width="283" alt="chrome_2018-08-31_08-00-39" src="https://user-images.githubusercontent.com/1296369/44897619-2fdfe480-acf4-11e8-85b8-a587b2f27cdc.png">
<img width="443" alt="chrome_2018-08-31_08-00-46" src="https://user-images.githubusercontent.com/1296369/44897620-30787b00-acf4-11e8-9233-d789d09e4010.png">
<img width="430" alt="chrome_2018-08-31_08-01-12" src="https://user-images.githubusercontent.com/1296369/44897623-31111180-acf4-11e8-843f-5f75a9a371e1.png">

The only "debug" thing I can think of is to go to global configuration and enable debug. Go back to users and try a search. Scroll to the bottom and click on database queries to show the queries that have been performed. You should see one that looks like

```
SELECT a.*

  FROM `y7deo_users` AS a

  WHERE (a.name LIKE '%banda%' OR a.username LIKE '%banda%' OR a.email LIKE '%banda%')

  ORDER BY `a`.`name` ASC 
  LIMIT 20
```

**Comment by nuria-sanchez** [comment]
Thank yo very much for taking the time to test it, I really appreciate it.
We will do what you suggest and let you know.

Have a great day!!!

**Comment by ghost** [comment]
closing as issue seems resolved. I needed, Issue can always reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21931">issues.joomla.org/tracker/joomla-cms/21931</a>.</sub>
