### ISSUE TITLE
[4.0] Workflow breaks start and end publishing

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21930]
As the title says - it is no longer possible to use the start and end publishing feature for articles as there is no way to see the CURRENT status.

### CURRENT admin
![image](https://user-images.githubusercontent.com/1296369/44884924-ff795580-acb5-11e8-9900-ae3693fb8b8c.png)

### PREVIOUS admin

![image](https://user-images.githubusercontent.com/1296369/44884942-191a9d00-acb6-11e8-8d96-5ddcd1d364c8.png)

### Front end is correct
![image](https://user-images.githubusercontent.com/1296369/44884955-32234e00-acb6-11e8-903a-9c10cff687ec.png)

**Comment by Bakual** [comment]
It would help if the two things "status" and "workflow stage" wouldn't be mixed together. One thing (status) is if it appears or not on the site. The other thing is an administrative process stage.
The latter interacts with the former, but they are two different things.

Currently, the column in your screenshot is called "Status", but in fact it's a mixed thing between status and stage. If the stage would live in it's own column, it would make things much more intuitive and would likely prevent issues like this.

**Comment by brianteeman** [comment]
Having separate columns won't change this. We always had one icon for this. the problem is that now there is no code to change the icon.

**Comment by ghost** [comment]
closed as having Pull Request #21942
