### ISSUE TITLE
Media manager - folder with many hi-res images create big download size

### ISSUE THREAD

**Issue by joelsan** [joomla/joomla-cms#21936]
### Steps to reproduce the issue
Prepare a folder in /images with many hi-res images, I used one with 1184 images with circa 2000x1500 px. Size 438MB
Just login to administrator of a Joomla 3.8.x site with permissions to manage media
administrator/index.php?option=com_media
and navigate to the folder mentioned

### Expected result
List of image thumbs in that folder

### Actual result
The result it's OK, I've just some observations in `Additional comments` section

### System information (as much as possible)

You need a folder with many hi-res images.
I used one folder with 1184 images with circa 2000x1500 px. Size 438MB

### Additional comments
> This is not really a bug, just something to be aware.

All images in that folder are downloaded to show the thumbnails, In this case it took forever and 400MB.
I know this could be avoided by each item having his own images folder.
However, this is a real site, and the clients don't have the kind of knowledge we do and are usually difficult to predict.
It's my/our job to don't let situations like this occur. I can find a workaround in my end but this should be addressed in the com_media component.
I don't really have the answer but I'll leave some ideas:
* Pagination could help, but the problem remains(however less severe) if you have to navigate page by page to find the image.
* Pagination with search and/or ordering filter by relevant fields
* If images exceed value n force detail view only with file name, maybe fetch the image by ajax on mouse over
* A image cache with redimensioned thumbs, will need CPU power/time to resize first time.
* Could be optimized if we join some of the ideas, like cache and pagination.

This is my first time posting, Hope I'm not doing it wrong.

> Keep up the good work guys.
Joel

![screen shot 2018-08-31 at 13 11 53](https://issues.joomla.org/uploads/1/46c8f73941c5dd3129bd9b3bcb511e43.png)
![screen shot 2018-08-31 at 13 12 34](https://issues.joomla.org/uploads/1/1db1f0d73e0d95f7bd569aa01b3a8bda.png)
![screen shot 2018-08-31 at 13 11 53](https://issues.joomla.org/uploads/1/9f972d2a24396014320f91395ca03e3d.png)
![screen shot 2018-08-31 at 13 12 34](https://issues.joomla.org/uploads/1/00067901592dd47a7e1c47a0a68d2eb1.png)

**Comment by mbabker** [comment]
TBH I think the best we might be able to do in the context of 3.x is stuff a lazy loading script into the media manager and media field so the penalty of those large folders is less extreme.  With us starting to stabilize 3.x for LTS and 4.0 coming up (including a reworked media manager), I personally wouldn't suggest putting a lot of time and effort into large changes in the current system.

**Comment by joelsan** [comment]
Speedy reply. :)
Well, I hope it could be useful to have in mind when coding in the `reworked media manager`.
Thanks for your attention

**Comment by ghost** [comment]
@mbabker @joelsan can you provide code for pull request for joomla 3.9,2 to stuff a lazy loading script into the media manager and media field?

**Comment by ghost** [comment]
@joelsan can you please answer?

**Comment by joelsan** [comment]
@Milglius  & @franz-wohlkoenig , are you asking me to contribute my own code to the Joomla project?
If so , I'll think about a solution in the weekend and let you know.
___
> @mbabker @joelsan can you provide code for pull request for joomla 3.9,2 to stuff a lazy loading script into the media manager and media field?

> @joelsan can you please answer?

**Comment by ghost** [comment]
> @mbabker @joelsan can you provide code for pull request for joomla 3.9,2 to stuff a lazy loading script into the media manager and media field?

i was asking cause of this comment.

**Comment by ghost** [comment]
is there a contribution to test this code?

**Comment by ghost** [comment]
@Milglius there is no Pull Request.

**Comment by brianteeman** [comment]
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed. 

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
