### ISSUE TITLE
[4.0] Problem with router

### ISSUE THREAD

**Issue by vagabondo** [joomla/joomla-cms#21935]
1. Log in to the Admin panel. 
2. Make new Article (Category: Uncategorised, name 333, alias - 333, featured). Save and close. 
3. Open Frontend Panel. 
4. At Home page see page 333. Сhoose it. 
5. And see adress: http://filiasfox.ultimatefreehost.in/?view=article&id=8:333&catid=2

Search Engine Friendly URLs - Yes.
Use URL Rewriting - Yes
Integration: Remove IDs from URLs - Yes

**Comment by ghost** [comment]
can this Issue please be answered as its open for a Week having Stauts "New"?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21935">issues.joomla.org/tracker/joomla-cms/21935</a>.</sub>

**Comment by infograf768** [comment]
Is your Home page a Featured Articles menu item? Are you clicking on the title of the article?
If yes, then you have for now to create another  specific menu item of type "List All Categories" (it can be hidden) and the url obtained will be nice.

To test this use the latest 4.0-dev or nightly build.

**Comment by ghost** [comment]
@infograf768 thanks for Answer.

**Comment by vagabondo** [comment]
>Is your Home page a Featured Articles menu item?

Yes, Home page - Featured Articles. 

> Are you clicking on the title of the article?

Yes, Ckicking on the title of article.

> If yes... 

I make new menu items "List All Categories". If published, work correctly. If not published - incorrect url.

This decision is not fine. The user should not think how to fix the situation by adding an unnecessary menu item.

**Comment by infograf768** [comment]
This is a known issue which some people are trying to solve.

@csthomas

**Comment by vagabondo** [comment]
Now the problem is not solved. The proposed solution does not fit

**Comment by csthomas** [comment]
I will try to solve this problem, but you should reopen it.
This issue is not easy because there will be a B/C break. 

I proposed  a solution some time ago and it was released with 3.8.4 and reverted with 3.8.5.

I have to redesign it to 4.0 and we'll see.

**Comment by vagabondo** [comment]
> I will try to solve this problem, but you should reopen it.

I open new  issue. #22036

> I proposed a solution some time ago and it was released with 3.8.4 and reverted with 3.8.5.

I saw it and wrote about a similar error in the router in the branch 3.8. The solution that was proposed was extremely inconvenient (make new menu item for all categories). The user should not think about it
