### ISSUE TITLE
Editor change does not work

### ISSUE THREAD

**Issue by twister65** [joomla/joomla-cms#21943]
### Steps to reproduce the issue

1. Log in as administrator
2. System -> Global configuration
3. Change the Default Editor (Code Mirror)
4. Save & Close
5. Edit an article
 
 
### Expected result
The editor has changed. The new one is Code Mirror, for example.

### Actual result
The editor has not changed.
You have to select and save twice the editor to be taken into account.

### System information (as much as possible)
Database : **PostgreSQL v10.4**
PHP Version : 7.1.20
Joomla! Version : Joomla! 3.8.12 Stable [ Amani ] 28-August-2018 14:00 GMT
Joomla! Platform Version : Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User agent : Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by ghost** [comment]
Can't confirm. Change Default Editor in Global Configuration works as expected.

### System information
- 3.8.12
- Template: Protostar
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.0.28
- MySQLi 5.7.18-cll-lve

**Comment by twister65** [comment]
[systeminfo-2018-08-31T22_44_28-07_00.txt](https://github.com/joomla/joomla-cms/files/2342097/systeminfo-2018-08-31T22_44_28-07_00.txt)
I tried with PostgreSQL database.

**Comment by ggppdk** [comment]
Maybe you have configured an editor specifically for this user
can you edit user and check ?

**Comment by twister65** [comment]
New installation (no update) with official Joomla_3.8.12-Stable-Full_Package.zip from joomla.org.
Log in as administrator with all the default options.
The problem is still relevant.
Please, see my system configuration : 
[systeminfo-2018-08-31T22_44_28-07_00.txt](https://github.com/joomla/joomla-cms/files/2342171/systeminfo-2018-08-31T22_44_28-07_00.txt)
![superuser](https://user-images.githubusercontent.com/26852967/44944149-f41b4c80-add1-11e8-9a42-d6a4e9376338.png)

**Comment by twister65** [comment]
The configuration.php file is correctly updated.
`class JConfig {
  public $editor = 'codemirror';`
But it is not reloaded when you edit an article.
You must log out and log back in.

**Comment by alikon** [comment]
cannot replicate on staging with postgresql 9.6.8

**Comment by twister65** [comment]
Video screenshot : https://youtu.be/ygyZDMncchI

**Comment by alikon** [comment]
![articles - jstaging - administration](https://user-images.githubusercontent.com/181681/44945149-08b41080-ade3-11e8-90a2-bb71f21ba0b4.gif)

**Comment by ghost** [comment]
@twister65 have you asked at [forums](https://forum.joomla.org/)?

**Comment by twister65** [comment]
No

**Comment by ghost** [comment]
i suggest to do so as there are on one Hand your Experience on the other not confirmings and this  repository concerns in first Place Joomla-Core coding. Showing Videos didn't bring it to a Solution i guess.

**Comment by SharkyKZ** [comment]
It's caching issue. OPCache in this case. We could invalidate configuration file cache like it's done in update script:

https://github.com/joomla/joomla-cms/blob/54de7825117de7868ca10ad0553814a9dd6f400e/administrator/components/com_joomlaupdate/restore.php#L8317-L8333

**Comment by twister65** [comment]
Yes, it was a caching issue. Thank you, SharkyKZ. The editor is effectively changed with this commit : 
https://github.com/twister65/joomla-cms/commit/8f27678ee5c4aa91e773e2612c44771164772266

**Comment by ghost** [comment]
@twister65 can you please close the Issue?

**Comment by twister65** [comment]
Do you want a pull request ? Did you approve the changes ?

**Comment by ghost** [comment]
> Yes, it was a caching issue.

Thats why i asked. If you do a Pull Request i say thank you :-)

**Comment by twister65** [comment]
#https://github.com/joomla/joomla-cms/pull/21949
Some checks were not successful
1 errored, 1 failing, and 2 successful checks

**Comment by ghost** [comment]
closed as having Pull Request #21949
