### ISSUE TITLE
[4.0] Multilanguage fatal eror

### ISSUE THREAD

**Issue by MarkRS-UK** [joomla/joomla-cms#21945]
### Steps to reproduce the issue
Brand new (Alpha4) installation with blog sample data installed, nothing else changed
In the admin menu select "Articles" and click on the first article (Your Template).

### Expected result
Editor (should be TinyMCE, since I haven't changed any settings) shows up with the article in it

### Actual result
No content displayed, only the error and stack trace below

( ! ) Fatal error: Cannot use Joomla\CMS\Language\Multilanguage as Multilanguage because the name is already in use in /home/mark/public_html/Development/J4_Alpha/administrator/components/com_content/Helper/PreviewHelper.php on line 18
Call Stack
#	Time	Memory	Function	Location
1	0.0001	355792	{main}( )	.../index.php:0
2	0.0002	356272	require_once( '/home/mark/public_html/Development/J4_Alpha/administrator/includes/app.php' )	.../index.php:36
3	0.0193	1534768	Joomla\CMS\Application\AdministratorApplication->execute( )	.../app.php:38
4	0.0426	2195656	Joomla\CMS\Application\AdministratorApplication->doExecute( )	.../CMSApplication.php:238
5	0.0492	2552296	Joomla\CMS\Application\AdministratorApplication->dispatch( )	.../AdministratorApplication.php:149
6	0.0520	2645016	Joomla\CMS\Component\ComponentHelper::renderComponent( )	.../AdministratorApplication.php:106
7	0.0588	2798800	Joomla\CMS\Dispatcher\Dispatcher->dispatch( )	.../ComponentHelper.php:350
8	0.0595	2812704	Joomla\Component\Content\Administrator\Controller\DisplayController->execute( )	.../Dispatcher.php:161
9	0.0595	2812704	Joomla\Component\Content\Administrator\Controller\DisplayController->display( )	.../BaseController.php:710
10	0.0597	2812704	Joomla\Component\Content\Administrator\Controller\DisplayController->display( )	.../DisplayController.php:59
11	0.0609	2847248	Joomla\Component\Content\Administrator\View\Article\HtmlView->display( )	.../BaseController.php:672
12	0.0877	3027592	Joomla\Component\Content\Administrator\View\Article\HtmlView->addToolbar( )	.../HtmlView.php:106
13	0.1010	3229216	spl_autoload_call ( )	.../HtmlView.php:186
14	0.1010	3229312	JClassLoader->loadClass( )	.../HtmlView.php:186
15	0.1010	3229312	Composer\Autoload\ClassLoader->loadClass( )	.../loader.php:55
16	0.1010	3229472	Composer\Autoload\includeFile( )	.../ClassLoader.php:322

### System information (as much as possible)
Localhost, Linux (Fedora 27).
PHP 7.1.21
 MySQLi 5.5.5-10.2.17-MariaDB
 Caching Disabled
 Gzip Disabled
 Users 1
 Articles 6

### Additional comments

While I have looked around the admin panel and looked at a couple of the pages, and displayed the welcome page of the front end, I have changed nothing. This is a completely fresh install.

**Comment by ghost** [comment]
changed Title to show its about 4.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21945">issues.joomla.org/tracker/joomla-cms/21945</a>.</sub>

**Comment by roland-d** [comment]
@MarkRS-UK This issue seems to have been solved because line 18 is no longer a code line:

https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_content/Helper/PreviewHelper.php

**Comment by ghost** [comment]
latest Release is ~~Alpha5~~ Joomla! 4.0.0-alpha5-dev or use [Nightlybuild](https://developer.joomla.org/nightly-builds.html).

**Comment by MarkRS-UK** [comment]
On Saturday, 1 September 2018 11:45:39 BST Franz Wohlkönig wrote:
> latest Release is Alpha5 or use
> [Nightlybuild](https://developer.joomla.org/nightly-builds.html).

Thanks. My apologies

**Comment by ghost** [comment]
@MarkRS-UK can you please close the Issue?
