### ISSUE TITLE
Session handler change error

### ISSUE THREAD

**Issue by twister65** [joomla/joomla-cms#21947]
### Steps to reproduce the issue

1. Change Session Handler in PHP in the Global Configuration -> System -> Session Settings
2. Save & logout
3. Log in as Super User
4. Change Session Handler in Database in the Global Configuration -> System -> Session Settings

### Expected result
The session handler is database

### Actual result
![session error](https://user-images.githubusercontent.com/26852967/44946437-a1a35580-adfc-11e8-9168-aa4085abfb00.png)

### System information (as much as possible)
[systeminfo-2018-09-01T06_46_46-07_00.txt](https://github.com/joomla/joomla-cms/files/2342399/systeminfo-2018-09-01T06_46_46-07_00.txt)

**Comment by mbabker** [comment]
Can you test this against the 3.9 alpha?  There won't be another 3.8 release short of a security release or critical bug being found, and there were a couple changes to the session table schema in 3.9 which if I had to guess based on the "character varying" part of the error message should be fixed.

**Comment by mbabker** [comment]
(Also for future reference, either copying in the actual error message or providing a translation if it's not in English would be preferred, that way someone can easily copy/paste the message into something like Google Translate if the message isn't in their native language or core's default English)

**Comment by twister65** [comment]
I tested successfully (no error) with 3.9-dev branch.
Could you give the reference of the issue or the commit fixing this bug ?
Thanks a lot.

**Comment by mbabker** [comment]
Probably https://github.com/joomla/joomla-cms/pull/19708

**Comment by ghost** [comment]
@twister65 if the Issue is solved please close it.

**Comment by twister65** [comment]
Yes, the issue is solved (in 3.9), you can close this issue.
