### ISSUE TITLE
[4.0] pre-installation Check note is unlucky

### ISSUE THREAD

**Issue by gorgonz** [joomla/joomla-cms#21946]
### Steps to reproduce the issue
- just clone the joomla4 branch resp. unzip the package to your webserver
- assert that the installer does not have the right to create a configuration.php (is usually the default)
- start the installation with your browser and look at the first page and read the message

### Expected result
there should be a syntactically correct English message ;-)

### Actual result
You will get "You can still continue the installation only if you repair the permissions or you provide an FTP connection"

### Additional comments
well, I'm not a native English, but would suggest a sentence like:
You only may continue the installation if you repair the permissions or you provide an FTP connection

**Comment by wojsmol** [comment]
cc @brianteeman

**Comment by brianteeman** [comment]
I am aware of this. There wasn't any point in correcting it as I am still waiting for a decision about FTP.

**Comment by Quy** [comment]
Duplicate #20774?

**Comment by ghost** [comment]
closed as duplicate Report.
