### ISSUE TITLE
[4.0] Editor Field Parameter Height Does not set the editor height

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#21941]
### Steps to reproduce the issue
Try to create a field type editor:

`<field
	name="summary"
	type="editor"
	label="COM_CONTENT_FIELD_ARTICLETEXT_LABEL"
	filter="JComponentHelper::filterText"
	buttons="true"
	**height="200"**
/>`

### Expected result
The editor should be 200px in height

### Actual result
The iframe height is autoset by a javascript I assume to 550px. 

### Additional comments
If that is the expected behavior, then why is height a parameter for editor field when it does nothing? Only for modal? Eh?

**Comment by ghost** [comment]
Closed as duplicate Report #14033<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21941">issues.joomla.org/tracker/joomla-cms/21941</a>.</sub>
