### ISSUE TITLE
[4.0] Uninstalling a component can't complete

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#21958]
### Steps to reproduce the issue
Install and uninstall a 4.0 compatible component

### Actual result
 Info and warning
> Error uninstalling component.

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?_wildcard' at line 3

### System information (as much as possible)
PHP 7.2.5

Issue close to #19085

**Comment by ghost** [comment]
changed Title to show its about 4.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21958">issues.joomla.org/tracker/joomla-cms/21958</a>.</sub>

**Comment by brianteeman** [comment]
Confirmed - can be replicated with com_patchtester

**Comment by wilsonge** [comment]
This one's probably related to the conversion to prepared statements. At a very quick guess this one https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Installer/Adapter/ComponentAdapter.php#L390-L400

**Comment by brianteeman** [comment]
Closed please test #22536
