### ISSUE TITLE
[4.0] Extra information in the classes Table, Models.

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#21956]
Hello!
Inside objects inherited from Table (Joomla \ CMS \ Table \ Table), Model (Joomla \ CMS \ MVC \ Model) is a lot of unnecessary information, especially language constants (there are a lot of them).

Why are they needed there? If the developer needs them, he will refer to the static method of the class `Text`.

**Comment by ghost** [comment]
changed Title to show its about 4.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21956">issues.joomla.org/tracker/joomla-cms/21956</a>.</sub>

**Comment by ghost** [comment]
Remove all unnecessary information that does not apply to `Table`, `Model`, so that the object can be used normally for `type hint`.

I'm on an array with objects that were inherited from `Table` used the function - `count`, so I had to wait for a couple of seconds until it booted and counted .....<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21956">issues.joomla.org/tracker/joomla-cms/21956</a>.</sub>

**Comment by zero-24** [comment]
Sorry I don't get your point can you please be a bit more specific on the things you want us to remove / change in that classes?

**Comment by brianteeman** [comment]
Closed after 6 weeks without response - it can always be reopened if the requested information is provided
