### ISSUE TITLE
[3.9] Capitals in label callback

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#21957]
### Steps to reproduce the issue
I am not native English, but:
When I look at all the labels I think that callback must be written with a capital 'C' in these srings:
PLG_RECAPTCHA_EXPIRED_CALLBACK_LABEL="Expired callback"
PLG_RECAPTCHA_ERROR_CALLBACK_LABEL="Error callback"
PLG_RECAPTCHA_INVISIBLE_EXPIRED_CALLBACK_LABEL="Expired callback"
PLG_RECAPTCHA_INVISIBLE_ERROR_CALLBACK_LABEL="Error callback"

### Expected result

PLG_RECAPTCHA_EXPIRED_CALLBACK_LABEL="Expired Callback"
PLG_RECAPTCHA_ERROR_CALLBACK_LABEL="Error Callback"
PLG_RECAPTCHA_INVISIBLE_EXPIRED_CALLBACK_LABEL="Expired Callback"
PLG_RECAPTCHA_INVISIBLE_ERROR_CALLBACK_LABEL="Error Callback"

**Comment by brianteeman** [comment]
agreed

**Comment by brianteeman** [comment]
Closed - see #22048
