### ISSUE TITLE
[4.0] [UX] Disabled buttons in list views are not self explaining.

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#21964]
In List views, as for example com_content, or com_users, many buttons are without function, for example batch, trash.... They are somehow opaque which means disabled and cannot be clicked. 
A new user without knowledge of Joomla! does not know that he must "activate" these buttons by marking one or more checkboxes. There is no hint, no information. 

The behaviour in J! 3.8 is much better and self explaining: If the user clicks a button, he gets the Information that at least one item must be marked. Now the user must detect this by chance.   

![screen shot 2018-09-02 at 18 54 09](https://issues.joomla.org/uploads/1/9c6ecf6c3e24c4ad0237705d5f111daf.png)

**Comment by brianteeman** [comment]
It is a very common ux pattern.
It would be better if the buttons were not there at all until they were active but despite being an even more common ux pattern every attempt at progressive disclosure is blocked

**Comment by ggppdk** [comment]
Furthermore to what said above already,

the toolbar continuesly looks like washed up "whitened", i don't know a better word to describe it
and i find this a little tiresome / ugly, but this is just my personal opinion

**Comment by brianteeman** [comment]
Also please remember that the template design calls for all the action buttons to be grouped into one dropdown select but this is on hold because workflows broke everything

**Comment by ghost** [comment]
Issue resolved, so closed. Please reopen if i'm wrong.
