### ISSUE TITLE
[4.0] [RFC] Changing article category with different workflows

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#21973]
### Current status
At the moment the workflow for each article is defined when creating the article, depending on the assigned category. After that the article has the assigned workflow forever (except an admin changes the workflow with the batch function). So changing the category of an article does NOT change the assigned workflow.

### Idea 1
Workflows should be independent of categories. So the current implementation is quite OK.

**Advantages:**
- only the access settings of the transitions are important for the stage (status) of an article.

**Disadvantages:**
- there is a drawback in not changing the workflow: user can probably publish articles in categories they're not allowed to (see [example](https://github.com/joomla/joomla-cms/issues/21552#issuecomment-417748662)). But that's the same behaviour as in J! 3 (see [example](https://github.com/joomla/joomla-cms/issues/21552#issuecomment-417764656))

### Idea 2
When changing the category with a new workflow assigned, the article workflow should change to the initial stage of the new workflow.

**Advantages:**
- the small "gap" from Joomla! 3 will be closed, only people with the appropriate permissions can publish in a category

**Disadvantages:**
- Published articles could become unpublished in this process (or vice versa)

### Idea 3
The workflow should only change if the article is not published yet. Published article stay published. (This idea could be changed to all combinations, only unpublished don't change etc. we have some "pseudo-intelligence")

**Advantages:**
- ???

**Disadvantages:**
- Does not solve the problem with the mentioned "gap"

**Any comments or new ideas?**

**Comment by chmst** [comment]
The "gap" did not make much noise until now? So it could remain as it is. 

But I like most Idea 2. 
When I am administrator and change the category, mybe I am not aware that the workflow is concerned too. So I would like to get an information (alert?) that the workflow and the stage have changed (if the categories have different workflows).

**Comment by HRIT-Florian** [comment]
I would also prefer idea 2 as it solves the right problem and it is not too complicated!

**Comment by brianteeman** [comment]
What is this "gap" you are talking about?

**Comment by bembelimen** [comment]
In Joomla! 3.x, if you have publishing rights in category 1 but not in category 2, you still can publish in category 2.

**Comment by brianteeman** [comment]
Your own or someone elses?

**Comment by bembelimen** [comment]
Depends if you have edit.own or edit permissions: https://github.com/joomla/joomla-cms/issues/21552#issuecomment-417764656

**Comment by lavipr** [comment]
I like most Idea 2. 
While testing #21579 "Workflow prevent trashing of used stages/workflows", I was wondering why another tester couldn't test this successfully. Luckily, he wrote down his steps for testing. I tried to follow his steps and only then became aware of the fact that it is possible to assign a workflow to a category. But at the moment this assignment seems to have no impact at all (if I haven't missed a thing). The first thought when assigning a workflow to a category was that the articles assigned to this category were assigned to this workflow. 
In that case it would make sense to assign workflows to categories.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21973">issues.joomla.org/tracker/joomla-cms/21973</a>.</sub>

**Comment by brianteeman** [comment]
> But at the moment this assignment seems to have no impact at all (if I haven't missed a thing). The first thought when assigning a workflow to a category was that the articles assigned to this category were assigned to this workflow.

Currently only content created in the category after the workflow has been added to the category will get the new workflow. Thats part of the problem. If you fchange the workflow on a category or move articles from another category then the "new" workflow is not applied

**Comment by lavipr** [comment]
Thank you, @brianteeman, for your explanation.  I'm still liking idea 2.

**Comment by ghost** [comment]
closed as having Pull Request #22180
