### ISSUE TITLE
[3.9] Exception thrown 'Captcha plugin not set or not found. Please contact a site administrator.'

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#21974]
### Steps to reproduce the issue
Open user registration page

### Expected result
No error messages

### Actual result
Error messages because of an exception thrown in the file /Joomla39/libraries/src/Captcha/Captcha.php at line 237
![j39captcha](https://user-images.githubusercontent.com/17835460/44988367-ba417600-af8a-11e8-988f-52a8c3b8e1ef.PNG)

The class Joomla\CMS\Captcha\Captcha constructor receives '0' as a first parameter '$captcha'

### System information (as much as possible)

Joomla 3.9 alpha

**Comment by zero-24** [comment]
Is any Captcha plugin enabled? What is set in the Global configuration?

**Comment by joeforjoomla** [comment]
No plugins enabled:

![image](https://user-images.githubusercontent.com/17835460/44998287-91ce7180-afb4-11e8-8807-494f5f432f07.png)

**Comment by alikon** [comment]
please test #21979

**Comment by joeforjoomla** [comment]
@alikon #21979 doesn't solve this issue

**Comment by alikon** [comment]
please can you elaborate more
cause  with this config + #21979 
![screenshot from 2018-09-03 20-57-56](https://user-images.githubusercontent.com/181681/44999256-1375cd80-afbc-11e8-9081-01478611df0a.png)
i'm able to register  without issues
![screenshot from 2018-09-03 20-59-59](https://user-images.githubusercontent.com/181681/44999287-6780b200-afbc-11e8-8a5b-ac3536385cd3.png)

**Comment by ghost** [comment]
closed as having Pull Request #21979

**Comment by alikon** [comment]
@franz-wohlkoenig  before closing it let's wait for @joeforjoomla  reply

**Comment by joeforjoomla** [comment]
@franz-wohlkoenig why did you close it? I said that PR #21979 is not related to this issue.
Let me debug the code and i will let you know something more.

**Comment by ghost** [comment]
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21974">issues.joomla.org/tracker/joomla-cms/21974</a>.</sub>

**Comment by joeforjoomla** [comment]
@franz-wohlkoenig and @alikon i confirm that #21979 fixes the issue.
Sorry for my overlooking.
You can safely close this issue.

**Comment by alikon** [comment]
no problem 
just a little bit of more work for the fast @franz-wohlkoenig  :smile:

**Comment by ghost** [comment]
closed as having Pull Request #21979
