### ISSUE TITLE
ADMINISTRATOR Categories  | Sort by Number of Articles

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#21970]
On the Category list in the Administrator we can sort by ID, Title, Status, Access Leve, Language..., but not by Number of Articles (published, depublished, archived, deleted). It was fine to hav the sort functionality to. 

![screen shot 2018-09-03 at 06 21 46](https://issues.joomla.org/uploads/1/a83f5e28e083b103b69084a232b07b9c.jpg)### Expected result

**Comment by ghost** [comment]
can one please answer this Feature Request as its open for a Week having Status "New"?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21970">issues.joomla.org/tracker/joomla-cms/21970</a>.</sub>

**Comment by infograf768** [comment]
Looking at the existing code to get these values, not sure we can sort these.

**Comment by ghost** [comment]
@infograf768 thanks for answer @hytsch

**Comment by hytsch** [comment]
OK, thank You.

**Comment by ghost** [comment]
@infograf768 Issue close or do you look on the Code?

**Comment by HLeithner** [comment]
The current implementation doesn't allow us to sort for these counts, it would need a rewrite of the SQL queries to support this, this could have a bigger performance impacted.

Additionally it get more complex with J4 and the new workflow. I would suggest to close this, if someone contribute code we can reopen it.

**Comment by hytsch** [comment]
Thats's ok, thank You.

**Comment by ggppdk** [comment]
- Currently these columns are calculated only for the categories of **the current page**

if you would want to sort by them then you would have to move their calculation inside the main query
and calculate these for all website categories.

On website with a few thousands of categories this would be a considerable performance 
a slowdown not only when sort by them but also when you do no sort by them

(or to avoid performance loss, you would have to keep old way when not sorting and do an alternative a little different and slower SQL main query when sorting by one of these columns)
