### ISSUE TITLE
PHP version warning for PHP 7.0.31 shows wrong end of support date

### ISSUE THREAD

**Issue by StefanSTS** [joomla/joomla-cms#21972]
### Steps to reproduce the issue
Enter backend control panel if you have PHP 7.0.31 installed.

### Expected result
Error message saying that PHP is not receiving security fixes soon. Date for end of support should be 2018-12-03.

### Actual result
Date shown for end of support is 2018-09-03.

### System information (as much as possible)
PHP 7.0.31 
Joomla 3.8.12

### Additional comments
I guess the date to show the warning, end of support minus three month,  is taken for the end of support date.

**Comment by SharkyKZ** [comment]
Test PR #21969 please.

**Comment by ghost** [comment]
closed as having Pull Request #21972

**Comment by jamield** [comment]
Surely even with the updated date, the message is still misleading. It says "PHP 7.x is recommended"... but PHP 7.0.31 **is** PHP 7.x

**Comment by StefanSTS** [comment]
Hi jamield, sure, it could use the actual PHP version THIS_VERSION and say "a PHP version above THIS_VERSION is recommended". This would be a change in the language file.
I think the discussion should go on in #21969.

**Comment by jamield** [comment]
@StefanSTS thanks StefanSTS. Raised in #21969.
