### ISSUE TITLE
Privacy Dashboard: Status check text overlaps other text.

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#21986]
### Steps to reproduce the issue!
Making the screen smaller the text overlaps other text.
[screen shot 2018-09-04 at 11 17 15](https://issues.joomla.org/uploads/1/67f5dfe19bc29457015de78d562e581d.png)

### System information (as much as possible)
J 3.9.0-alpha Firefox and Edge

**Comment by mbabker** [comment]
Not sure there's a good fix for this one.  It's the Bootstrap grid being antiquated that's a problem here.

**Comment by Quy** [comment]
Closing per #24188.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21986">issues.joomla.org/tracker/joomla-cms/21986</a>.</sub>
