### ISSUE TITLE
[4.0] UI Tab Behavior when created via loop

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#21981]
### Steps to reproduce the issue
Create a Tab via foreach like:

<img width="1070" alt="preferences" src="https://user-images.githubusercontent.com/1373815/45007108-06071600-afb1-11e8-96da-81d63b59b015.png">

The $firstActiveTab value is **membership** which is the first array key.

### Expected result
There should only be 1 active tab.

### Actual result
<img width="981" alt="joomla4_tabui" src="https://user-images.githubusercontent.com/1373815/45006796-8a589980-afaf-11e8-8b11-08b88571461a.png">

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21981">issues.joomla.org/tracker/joomla-cms/21981</a>.</sub>

**Comment by puneeth-chanda** [comment]
can I know how to reproduce the issue
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21981">issues.joomla.org/tracker/joomla-cms/21981</a>.</sub>

**Comment by Quy** [comment]
Closing as non-reproducible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21981">issues.joomla.org/tracker/joomla-cms/21981</a>.</sub>
