### ISSUE TITLE
[4.0] Fatal error after saving an article

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#21988]
### Steps to reproduce the issue
Just create an article and save it

### Expected result
Load the the articles edit view

### Actual result
Fatal error:
Cannot use Joomla\CMS\Language\Multilanguage as Multilanguage because the name is already in use in /var/www/html/joomla40/administrator/components/com_content/Helper/PreviewHelper.php on line 18

### System information (as much as possible)
php 7.0

### Additional comments
Fresh installation of Joomla4.0.0alpha4

**Comment by sakiss** [comment]
And the xdebug's call stuck

Call Stack
--

1 | 0.0000 | 363536 | {main}(  ) | .../index.php:0
2 | 0.0001 | 364392 | require_once( '/var/www/html/joomla40/administrator/includes/app.php' ) | .../index.php:36
3 | 0.0146 | 1478176 | Joomla\CMS\Application\AdministratorApplication->execute(  ) | .../app.php:38
4 | 0.0460 | 2140960 | Joomla\CMS\Application\AdministratorApplication->doExecute(  ) | .../CMSApplication.php:238
5 | 0.0548 | 2563920 | Joomla\CMS\Application\AdministratorApplication->dispatch(  ) | .../AdministratorApplication.php:149
6 | 0.0591 | 2591256 | Joomla\CMS\Component\ComponentHelper::renderComponent(  ) | .../AdministratorApplication.php:106
7 | 0.0641 | 2745280 | Joomla\CMS\Dispatcher\Dispatcher->dispatch(  ) | .../ComponentHelper.php:350
8 | 0.0646 | 2759168 | Joomla\Component\Content\Administrator\Controller\DisplayController->execute(  ) | .../Dispatcher.php:161
9 | 0.0646 | 2759168 | Joomla\Component\Content\Administrator\Controller\DisplayController->display(  ) | .../BaseController.php:710
10 | 0.0648 | 2759168 | Joomla\Component\Content\Administrator\Controller\DisplayController->display(  ) | .../DisplayController.php:59
11 | 0.0658 | 2859232 | Joomla\Component\Content\Administrator\View\Article\HtmlView->display(  ) | .../BaseController.php:672
12 | 0.1243 | 3050240 | Joomla\Component\Content\Administrator\View\Article\HtmlView->addToolbar(  ) | .../HtmlView.php:106
13 | 0.1394 | 3186296 | spl_autoload_call (  ) | .../HtmlView.php:186
14 | 0.1394 | 3186448 | JClassLoader->loadClass(  ) | .../HtmlView.php:186
15 | 0.1394 | 3186448 | Composer\Autoload\ClassLoader->loadClass(  ) | .../loader.php:55
16 | 0.1394 | 3186560 | Composer\Autoload\includeFile(  ) | .../ClassLoader.php:322

**Comment by SharkyKZ** [comment]
This is already fixed. Test with nightly https://developer.joomla.org/nightly-builds.html.

**Comment by sakiss** [comment]
Thanks i just find it out https://github.com/joomla/joomla-cms/pull/21224

**Comment by zero-24** [comment]
Ok so this can be closed @sakiss ?

**Comment by ghost** [comment]
@sakiss can you please close the Issue?
