### ISSUE TITLE
[4.0] Edit Article Layout

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#21989]
### What needs to be fixed
Migrated issue from
https://github.com/joomla/40-backend-template/issues/418

So this is the proposal for the Article Edit View.

Just in this view the tabs are at the bottom, the focus should be at the contents and many tabs can follow with custom fields so it's good to think affront how to add more tabs then the viewport is able to show in a row. A possibility could be to add a double angle icon left and right to switch through the tabs in the moment they would break.

Also attached a mobile example.

Any ideas are welcome and i can provide the sketch file for those that want to contribute to the design.

1) Create Article

![joomla4-edit-article](https://user-images.githubusercontent.com/828371/40282536-30ed7a78-5c71-11e8-8f6c-e0d42caec8df.png)

2) Save Actions
![joomla4-edit-article-save-actions](https://user-images.githubusercontent.com/828371/40282586-e5671d06-5c71-11e8-9d99-4a612958cd0f.png)

3) Inline Editing
![joomla4-edit-article-inline-editing](https://user-images.githubusercontent.com/828371/40282579-d2002ac8-5c71-11e8-8b04-a8e7fe231424.png)
![joomla4-edit-article-inline-editing copy](https://user-images.githubusercontent.com/828371/40282580-d43cd638-5c71-11e8-8c03-ce6d890dfcbc.png)

4) Image Inline Editing and contextual change of the Editor Buttons
![joomla4-edit-article-media-support](https://user-images.githubusercontent.com/828371/40282596-0754dee4-5c72-11e8-8444-84cc00337187.png)

5) Example for the images and Links Tab
![joomla4-edit-article-image-options](https://user-images.githubusercontent.com/828371/40282552-614c3588-5c71-11e8-938f-ed9ef7b5e4c6.png)

6) Saved Dialog inside the input
![joomla4-edit-article-3](https://user-images.githubusercontent.com/828371/40282550-5dd44fc6-5c71-11e8-8315-ffbc9506dca4.png)

7) Mobile Example (Icons not correct right now)
![joomla4-edit-article-mobile](https://user-images.githubusercontent.com/828371/40282643-ce95db48-5c72-11e8-9fd6-1a7c3429afec.png)
![joomla4-edit-article-mobile copy 2](https://user-images.githubusercontent.com/828371/40282645-cedb0786-5c72-11e8-9deb-94c29ee53351.png)

**Comment by PhocaCz** [comment]
Great, it solves:
https://github.com/joomla/joomla-cms/issues/22103 (5) (reference to: https://github.com/joomla/joomla-cms/issues/14326 )

**Comment by ghost** [comment]
@PhocaCz can #22103 be closed?

**Comment by PhocaCz** [comment]
Hi, in fact, yes:
1,2,5,7 have own issue topics
3,4,8 can be discussed/newly opened when Joomla! 4 will be stable (when more users will use it)
6 it is in progress

**Comment by ghost** [comment]
thanks @PhocaCz

**Comment by brianteeman** [comment]
Can be closed now that the new template has been merged
