### ISSUE TITLE
[4.0] Dashboard - Content #426

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#21997]
Migrated issue from: https://github.com/joomla/40-backend-template/issues/426

1) Example of a Dashboard for the content
![content - initial](https://user-images.githubusercontent.com/828371/40283244-7c0948ac-5c7b-11e8-8d1e-889b8321658b.png)

2) Mobile Example (bottom icons not correct)
![mobile](https://user-images.githubusercontent.com/828371/40283247-852be3ae-5c7b-11e8-8779-c89ee775bc2c.png)

**Comment by ghost** [comment]
@coolcat-creations should this Issue stay open?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21997">issues.joomla.org/tracker/joomla-cms/21997</a>.</sub>

**Comment by coolcat-creations** [comment]
There is a PR somewhere in preparation. I can't find the reference. Consider it as WIP, thank you

**Comment by Hackwar** [comment]
This one can be closed now. The issue has been solved in the backend-template project.

**Comment by brianteeman** [comment]
No this should not be closed - they are still open issues until the work from the backend-template project is **accepted** and **merged**

**Comment by brianteeman** [comment]
Can be closed now that the new template has been merged
