### ISSUE TITLE
[4.0] Dashboard - Menus #423

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#21994]
Migrated issue from: https://github.com/joomla/40-backend-template/issues/423

1) Dashboard for Menus - Trying to be more obvious towards the User that Admin Menus can be created
![menu - initial](https://user-images.githubusercontent.com/828371/40283135-d527517e-5c79-11e8-9c89-8652eabe1409.png)

2) Mobile example (like all the others: Icons not correct at the Bottom bar)
![mobile](https://user-images.githubusercontent.com/828371/40283136-d6d5c4f6-5c79-11e8-8358-1012a888dd7a.png)

**Comment by PhilETaylor** [comment]
People can, and do, have crazy amounts of menus, and even more crazy amounts (in the 1000s) of menu items - the new menu screens need to cope with 1000s of everything

**Comment by Hackwar** [comment]
This one can be closed now. The issue has been solved in the backend-template project.

**Comment by brianteeman** [comment]
No this should not be closed - they are still open issues until the work from the backend-template project is **accepted** and **merged**

**Comment by brianteeman** [comment]
Can be closed now that the new template has been merged
