### ISSUE TITLE
[4.0] "Actionbuttons" in Toolbar #420

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#21991]
Migrated issue from:
https://github.com/joomla/40-backend-template/issues/420

1) Quickstart Actions 
![joomla4-edit-article copy 2](https://user-images.githubusercontent.com/828371/40282830-2885a37a-5c75-11e8-9bf6-75d0c7254daa.png)

2) Notifications
![joomla4-edit-article copy](https://user-images.githubusercontent.com/828371/40282829-26761178-5c75-11e8-8a66-b604d577518f.png)

3) User Options

![joomla4-edit-article](https://user-images.githubusercontent.com/828371/40282828-23ba145c-5c75-11e8-851c-c0a207c87c68.png)

**Comment by brianteeman** [comment]
Doesn't this have the same a11y issues supposedly present in the current menu

**Comment by coolcat-creations** [comment]
No, there is no different action on click / and/or hover

**Comment by Hackwar** [comment]
This feature was decided against during the development of the backend template.

**Comment by ghost** [comment]
@Hackwar should the Issue stay open to discuss about it?

**Comment by alikon** [comment]
closed thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21991">issues.joomla.org/tracker/joomla-cms/21991</a>.</sub>
