### ISSUE TITLE
[4.0] Dashboard - Users

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#21992]
Migrated issue from:
https://github.com/joomla/40-backend-template/issues/421

1) Layout Proposal for the User Dashboard:

![users - initial](https://user-images.githubusercontent.com/828371/40283013-0e7a0374-5c78-11e8-8b70-6730b72d8e94.png)

2) Mobile Example (Bottom Bar Icons not correct)

![mobile](https://user-images.githubusercontent.com/828371/40283016-137afb9e-5c78-11e8-8877-54abc62fad27.png)

**Comment by Hackwar** [comment]
This one can be closed now. The issue has been solved in the backend-template project.

**Comment by brianteeman** [comment]
No this should not be closed - they are still open issues until the work from the backend-template project is **accepted** and **merged**

**Comment by alikon** [comment]
related to the old template, open a new issue if needed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21992">issues.joomla.org/tracker/joomla-cms/21992</a>.</sub>
