### ISSUE TITLE
[4.0] Manage - (Site or Admin) Menus #424

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#21995]
Migrated issue from: https://github.com/joomla/40-backend-template/issues/424

1) Manage (Site) Menus
![menus - manage site menus](https://user-images.githubusercontent.com/828371/40283150-12d8834e-5c7a-11e8-89bd-e5ddef3bfd19.png)

- Not 100% happy with the Modules Dropdown yet
- Anything that can be improved from your point of view? 
- Should the languages have an own column / Be more obvious / have a flag ?

**Comment by Hackwar** [comment]
This proposal has been partially implemented in the new backend template and the display here is superseeded by the implementation there.

**Comment by alikon** [comment]
closed thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21995">issues.joomla.org/tracker/joomla-cms/21995</a>.</sub>
