### ISSUE TITLE
[4.0] Manage - Content - Articles #427

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#21998]
Migrated issue from: https://github.com/joomla/40-backend-template/issues/427

1) Manage Articles Overview
![content - manage articles](https://user-images.githubusercontent.com/828371/40283295-5511becc-5c7c-11e8-9dd3-f4c7ee7dc4f6.png)

2) One Article checked
![content - manage articles - item 1 ticked](https://user-images.githubusercontent.com/828371/40283298-58d21462-5c7c-11e8-83a2-44d1be741c2e.png)

3) Contextual Action Button
![content - manage articles item 1 - contextual actions](https://user-images.githubusercontent.com/828371/40283300-5bd13e9a-5c7c-11e8-8fd6-d0a66bf8ebd0.png)

4) List Options / Configurable columns
![content - manage articles - list options open lang active](https://user-images.githubusercontent.com/828371/40283302-5ec4b186-5c7c-11e8-93c6-c3d5c57eaf21.png)

5) Disabled language Column
![content - manage articles - list options open lang inactive](https://user-images.githubusercontent.com/828371/40283305-61cbe9bc-5c7c-11e8-88f7-0b9d840e4115.png)

6) Mobile example 1
![mobile](https://user-images.githubusercontent.com/828371/40283308-653b7eaa-5c7c-11e8-8881-e9c35ade7df1.png)

7) Another Mobile example
![mobile 2](https://user-images.githubusercontent.com/828371/40283311-6976d9a6-5c7c-11e8-8be3-642104c3baf4.png)

8) Swipe options on mobile 
![mobile swipe](https://user-images.githubusercontent.com/828371/40283312-6c601b96-5c7c-11e8-849d-2ac2e3c5559b.png)

**Comment by ghost** [comment]
@coolcat-creations  makes it sense to keep this Issue open?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21998">issues.joomla.org/tracker/joomla-cms/21998</a>.</sub>

**Comment by coolcat-creations** [comment]
There is a PR somewhere in preparation. I can't find the reference. Consider it as WIP, thank you

**Comment by Hackwar** [comment]
This proposal has been partially implemented in the new backend template and the display here is superseeded by the implementation there.

**Comment by alikon** [comment]
closed thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21998">issues.joomla.org/tracker/joomla-cms/21998</a>.</sub>
