### ISSUE TITLE
[4.0] Manage - Menuitems #425

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#21996]
Migrated issue from: https://github.com/joomla/40-backend-template/issues/425

1) Manage Menuitems Overview
![menu - manage menu items](https://user-images.githubusercontent.com/828371/40283214-e6924602-5c7a-11e8-8fb3-0be429ae986f.png)

2) One Item is ticked
![menu - manage menu items - tick item 1](https://user-images.githubusercontent.com/828371/40283217-eb1f8734-5c7a-11e8-8681-2d4022709901.png)

3) Contextual Action Button
![menu - manage menu items - tick item 1 - actions open](https://user-images.githubusercontent.com/828371/40283219-f344160a-5c7a-11e8-851e-a705cd5e811b.png)

Missing: 

- A column showing which menu the item belongs to when showing Items from all menus.
- Customizeable Columns

**Comment by Hackwar** [comment]
This proposal has been partially implemented in the new backend template and the display here is superseeded by the implementation there.
