### ISSUE TITLE
[4.0] Users - Manage

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#21993]
Migrated issue from: 
https://github.com/joomla/40-backend-template/issues/422

1) Manage Users Overview
![users - manage users](https://user-images.githubusercontent.com/828371/40283058-b9e26008-5c78-11e8-827c-64947f349560.png)

2) One User is checked
![users - manage users - user 1 checked](https://user-images.githubusercontent.com/828371/40283060-c46508b4-5c78-11e8-91d9-2bebf98b1eec.png)

3) Contextual Actions
![users - manage users - user 1 - actions open](https://user-images.githubusercontent.com/828371/40283062-cc2753ea-5c78-11e8-89c9-df1aa342d87a.png)

**Comment by Hackwar** [comment]
This proposal has been partially implemented in the new backend template and the display here is superseeded by the implementation there.

**Comment by ghost** [comment]
@Hackwar should the Issue stay open?

**Comment by Hackwar** [comment]
no
