### ISSUE TITLE
[4.0] Dashboard - System Settings #430

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#22001]
Migrated issue from: https://github.com/joomla/40-backend-template/issues/430

1) Interactive Dashboard for the System Settings, things to pay attention to should be obvious, things that are not needed should be marked as well (maybe lowe opacity if cache is absolutely empty, so user does not have to click inside to see it's noting there)
![settings - initial](https://user-images.githubusercontent.com/828371/40283391-acc040a2-5c7d-11e8-830b-ce4e672bd2e6.png)

2) Mobile example
![mobile](https://user-images.githubusercontent.com/828371/40283393-b113d736-5c7d-11e8-81af-8261fa72ff32.png)

**Comment by wilsonge** [comment]
I've made a start on this - doing the re-ordering of the text and changing "System" to Setup. However the Update part is being automatically moved into the templates column by the CSS (we're just using CSS `column-count` property). However whilst we could force it I would add on my macbook (13 inch) I'd loose the bottom part of the bottom of the screen - whilst how it is now allows me to see all the options

![image](https://user-images.githubusercontent.com/1986000/45393795-7f43e000-b625-11e8-8173-a9441db8691f.png)

**Comment by brianteeman** [comment]
Looks good @wilsonge . As long as we use column count etc there will always be that type of potential issue

**Comment by Hackwar** [comment]
This one can be closed now. The issue has been solved in the backend-template project.

**Comment by brianteeman** [comment]
No this should not be closed - they are still open issues until the work from the  backend-template project is accepted and merged

**Comment by brianteeman** [comment]
Can be closed now that the new template has been merged
