### ISSUE TITLE
Joomla standard field "file" not supports zip file upload

### ISSUE THREAD

**Issue by thaneshs** [joomla/joomla-cms#22007]
### Steps to reproduce the issue
Added form with Joomla standard field type => file to upload all file formats

### Expected result
Array with upload file details

### Actual result
Zip file upload is not supporting. Getting an empty array on below code,
JFactory::getApplication()->input->files->get('jform', array (), 'array');

### Additional comments
We need to allow zip file to upload if server supports zip upload.

**Comment by zero-24** [comment]
Can you please check the options you made in com_media for the allowed types? Do they include zip? What mime type does your zip have? Is that mime type whitelisted?

**Comment by thaneshs** [comment]
yes, i have updated zip file extensions in both MIME Types(application/zip) and Extensions (zip,ZIP) under media.

Its not supporting zip upload. I am getting empty array on zip upload. I hope Joomla supports

**Comment by SharkyKZ** [comment]
`File` field type doesn't use any settings from `com_media`. This is filter doing its job. Certain archives are scanned for PHP files:

https://github.com/joomla/joomla-cms/blob/56824f3b5e96ab88927fb901e6cb5f49e6e69840/libraries/src/Filter/InputFilter.php#L533-L534

You can avoid this by setting filter to `raw` and doing custom filtering in your code.
