### ISSUE TITLE
[4.0] Modal popups disable the entire screen

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#22006]
### Steps to reproduce the issue
Go to an article and press the "Versions" button

### Expected result
Versions popup

### Actual result

![articles_ edit - joomla40pre-release - administration](https://user-images.githubusercontent.com/1838041/45030675-5041d300-b055-11e8-8958-b0bd71707b03.png)

### System information (as much as possible)
Joomla4.0.0alpha5

**Comment by ghost** [comment]
@sakiss  Thanks for Report. The Issue has been reported so please close this duplicate Report.

**Comment by sakiss** [comment]
@franz-wohlkoenig Can you please mention the duplicate issue here before closing?

**Comment by ghost** [comment]
there are Comments, but no Issue, so its better stay open that it don't get lost.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22006">issues.joomla.org/tracker/joomla-cms/22006</a>.</sub>

**Comment by ghost** [comment]
@brianteeman can you please reattach "J4 Issue"?

**Comment by PhilETaylor** [comment]
Confirmed today @ 9d3acfd9d589989e86bda3fe35f58a47323d66f4

**Comment by Quy** [comment]
Duplicate #23636<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22006">issues.joomla.org/tracker/joomla-cms/22006</a>.</sub>

**Comment by PhilETaylor** [comment]
Why close the older of the two duplicates then?! This is wrong. 

https://github.com/joomla/joomla-cms/issues/23636 should be closed and this one open.

**Comment by PhilETaylor** [comment]
also possible related to https://github.com/joomla/joomla-cms/issues/20255
