### ISSUE TITLE
[4.0] System Settings - Update Extensions #432

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#22003]
Migrated issue from: https://github.com/joomla/40-backend-template/issues/432

![system settings - update](https://user-images.githubusercontent.com/828371/40283417-15e41a0e-5c7e-11e8-847e-ea96241a44c0.png)

**Comment by brianteeman** [comment]
This is very hard to make accessible as you have a second row with content spanning multiple cells

**Comment by coolcat-creations** [comment]
You can span the row with css grid and/or css does not have to span multiple cells codewise

**Comment by mbabker** [comment]
So you're saying instead of the (IMO semantically correct) `<table>` element it currently is it should be done as a set of `<div>` elements using CSS Grid?

**Comment by brianteeman** [comment]
Wrote a long answer but I see @mbabker has written it so much better and shorter

**Comment by coolcat-creations** [comment]
No, I meant there are solutions to make it semantically correct AND have a correct view. I doubt that it’s not possible at all.

**Comment by coolcat-creations** [comment]
Again I wonder why this comment is made like 11 months later...

**Comment by brianteeman** [comment]
maybe we thought it would be a lot less than 11 months before it would reach this repo

**Comment by mbabker** [comment]
Nobody's saying it's not possible, we're just pointing out potential concerns about the implementation.

But, if feedback is unwelcome I'll gladly unsubscribe from your issues.

**Comment by brianteeman** [comment]
Pretty certain that the html specification is that the data in a table cannot span two table rows

**Comment by brianteeman** [comment]
Actually I am saying it is impossible

**Comment by mbabker** [comment]
As a table, you're right.  You can still pull it off if you do the page layout with some kind of grid structure and abandon the table semantics, which most likely also has a hit on page accessibility (and I've done enough implementations of table-y things with Flexbox driven grids to know I wouldn't want to try and touch this with CSS Grid).

**Comment by brianteeman** [comment]
It is a table of tabular data so it must be a table. And if we really are serious about accessibility and not just listening when it is convenient you cannot create a table of data in any other way.

**Comment by coolcat-creations** [comment]
Could be solved for example with a nested table where the URL is the tableheader. Screenreaders can read nested tables.

**Comment by coolcat-creations** [comment]
Another solution:
![grafik](https://user-images.githubusercontent.com/828371/45054376-1096dd80-b08d-11e8-83f9-fbb38213c569.png)
https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced

**Comment by brianteeman** [comment]
Nested tables are horrendous for accessibility

We already have row headers (maybe you should read the code) but they don't resolve the issue you are presenting

**Comment by C-Lodder** [comment]
- Pushing last cell to new line: You'd have to set each cell to `inline-block` and the last cell to `block`, then fix all the alignments and borders. Way too dirty, so don't even try it.
- CSS Grid: Not even semantically correct for a data set
- Nested tables: Please don't even go there

I'd probably go as far as saying the URL's aren't even needed, else simply have a button in the last cell that directs to the authors' site or something.

**Comment by mbabker** [comment]
The URL for the update server is definitely not needed, but the URL for the announcement/changelog/whatever should definitely remain in some form.

**Comment by brianteeman** [comment]
Because it is possible for any extension to change the value of the update server of a **different** extension it is important that the url is displayed and not hidden behind a button for security purposes. At least if it is visible you might notice that you are being directed to the wrong site to grab a malicious update

**Comment by C-Lodder** [comment]
@brianteeman fair point. Just bung it below the extension name then:

![screeny](https://user-images.githubusercontent.com/2019801/45096133-bd1da180-b117-11e8-8ae1-43732770d06c.png)

**Comment by brianteeman** [comment]
Just like it is right now ;)

**Comment by alikon** [comment]
we can change the update site,  if we want, from gsoc17 #17553

**Comment by C-Lodder** [comment]
@brianteeman Shows the last time I did a git pull then

**Comment by alikon** [comment]
related to the old template, open a new issue if needed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22003">issues.joomla.org/tracker/joomla-cms/22003</a>.</sub>
