### ISSUE TITLE
[4.0] [Backend Template] Content - Manage - Articles - Actionbutton #436

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#22004]
Migrated issue from: https://github.com/joomla/40-backend-template/issues/436

### Current state
![grafik](https://user-images.githubusercontent.com/828371/40359424-ff5c0968-5dc2-11e8-948e-aa7700b4aa9b.png)

### Desired state ;)
![grafik](https://user-images.githubusercontent.com/828371/40359452-1307201a-5dc3-11e8-8b79-4b1f25052275.png)

**Comment by brianteeman** [comment]
Don't we already have a pr for this from @fedik although it's completely killed by the workflow changes

**Comment by Fedik** [comment]
It looks similar to #21247 pull request

**Comment by brianteeman** [comment]
it is - sorry I thought it was your PR @Fedik

**Comment by wilsonge** [comment]
The action button concept has largely been implemented now. I know there's some smaller subtasks to create based on this (e.g. if you want to change the text to action or integrate batch as in the design) but I'm closing this as a big ticket item
