### ISSUE TITLE
[4.0] Dashboard - Components #429

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#22000]
Migrated issue from: https://github.com/joomla/40-backend-template/issues/429

1) Yes thats NOT the most sexy solution - if anyone has an idea: help is welcome. Please look also at the other Dashboard Views to get an idea

![components - initial](https://user-images.githubusercontent.com/828371/40283365-33eac94a-5c7d-11e8-9410-9591ee10a9b2.png)

2) Mobile example
![mobile](https://user-images.githubusercontent.com/828371/40283368-3b893a24-5c7d-11e8-8375-869d0a7ff407.png)

**Comment by Hackwar** [comment]
This one can be closed now. The issue has been solved in the backend-template project.

**Comment by brianteeman** [comment]
No this should not be closed - they are still open issues until the work from the backend-template project is **accepted** and **merged**

**Comment by brianteeman** [comment]
Can be closed now that the new template has been merged
