### ISSUE TITLE
Filters not work in admin template modules

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#22009]
### Steps to reproduce the issue
Go to: Extensions/ Modules
In the first filter select: Administrator
Click in any title module and click Save and new.
NOW THE SELECT POSITION SHOW, position of site template

### Expected result
It should show positions of ADMIN TEMPLATE

### Actual result
It should show positions of SITE TEMPLATE

### System information (as much as possible)
Joomla 3.8.12

### Additional comments
Select Administrator in filter modules
Others filters also fail:
Select type: show modules for site not for admin.
Select  menu items: show items for site not for admin,
Etc.

**Comment by ghost** [comment]
Can't confirm, after Save&New Hathor- and Isis-Positions are shown as expected.
### System information
- 3.8.12
- Template: Protostar
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.0.28
- MySQLi 5.7.18-cll-lve

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22009">issues.joomla.org/tracker/joomla-cms/22009</a>.</sub>

**Comment by SharkyKZ** [comment]
@franz-wohlkoenig I think this refers to fields in filter form.

In module list, select `Administrator` client.
Check that administrator positions are shown in `- Select Position - ` field.
Mark any module and click `Publish`.
Now site positions are shown in `- Select Position - ` field.

**Comment by Open2logic** [comment]
Step by step:
1) Go to modules
2) Select in fliter: Administrator
3) CLick in any module
4) Save and new
5) In this new module, in the right lokk the positions.

Now the positions, are the site template, not for the admin template

**Comment by brianteeman** [comment]
I can't replicate this - see movie

![modules](https://user-images.githubusercontent.com/1296369/45046213-65c2f700-b06d-11e8-9ee7-1ccd6371ffad.gif)

**Comment by tonypartridge** [comment]
It sounds to me that you may have gone to create a module, then backed up and then edited and did a save and new. It’s then possible on the new module it’s re-filled your previously entered data because cancel wasn’t used the session data wasn’t cleared

**Comment by Open2logic** [comment]
Brian that video is exactly what I do. 
For me the positions are changed and it shows me the positions of the site template.
it works well for you.

I'm going to try a new installation.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22009">issues.joomla.org/tracker/joomla-cms/22009</a>.</sub>

**Comment by brianteeman** [comment]
Going to close this for now. If you are able to reproduce it on a clean site etc then it can always be reopened

**Comment by chmst** [comment]
I can confirm the issue. Could you reopen this? A have it in 3.8.12 and 3.9 nightly build.

The filters in the searchtool are for frontend when you return from the edit screen after save&new or save2copy of a module.
As soon as you select something from the status-field, the filter fields show the right content again.

![screen shot 2018-09-07 at 11 23 32](https://issues.joomla.org/uploads/1/254e3cfbb59cb50f0454b33ad05b9887.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22009">issues.joomla.org/tracker/joomla-cms/22009</a>.</sub>

**Comment by brianteeman** [comment]
@chmst what you are describing is different to the original report

**Comment by chmst** [comment]
You are right. I'll open a new issue. Thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22009">issues.joomla.org/tracker/joomla-cms/22009</a>.</sub>

**Comment by Open2logic** [comment]
That is the global problem, I indicated it in additional comments in my first text![screen shot 2018-09-07 at 14 46 36](https://issues.joomla.org/uploads/1/a91c07f4676245c980073f348afaefb7.jpg)

Selecto administrator, any module, save and close
Now the filters of the modules show options for the site not for the administrator environment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22009">issues.joomla.org/tracker/joomla-cms/22009</a>.</sub>

**Comment by Open2logic** [comment]
But we can consider two different incidents issues.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22009">issues.joomla.org/tracker/joomla-cms/22009</a>.</sub>

**Comment by SharkyKZ** [comment]
It seems to be the same issue. Test #22040 please.

**Comment by Open2logic** [comment]
I have to review because it works for Brian and I do not.
If the filters do not work in the module options is different issue.

**Comment by Open2logic** [comment]
Confirmed, does not work in a new installation.

1) In modules, select Administrator in the filter
![1](https://user-images.githubusercontent.com/9007607/45458802-a669e280-b6f5-11e8-9b8a-b77a5db46741.JPG)

Create a new custom module, now the filter of the positions shows the positions of the administration template.
![2](https://user-images.githubusercontent.com/9007607/45458832-d1543680-b6f5-11e8-9e98-c145ed8a1fa8.JPG)

Save and New, and now, the filters of the positions shows the positions of the site template
![3](https://user-images.githubusercontent.com/9007607/45458855-ef219b80-b6f5-11e8-8b16-9d40e909f2de.JPG)

Joomla 3.9.12

**Comment by ghost** [comment]
reopened for further Investigation.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22009">issues.joomla.org/tracker/joomla-cms/22009</a>.</sub>

**Comment by SharkyKZ** [comment]
Issue confirmed. When doing `Save & New` with an admin module that is available in both site and admin (e.g. `mod_custom`, `mod_login`, `mod_feed`), new module is always set to be created for site.

**Comment by SharkyKZ** [comment]
Test PR #22156 please.

**Comment by brianteeman** [comment]
> with an admin module that is available in both site and admin 

Good investigation and discovery

**Comment by ghost** [comment]
closed as having Pull Request #22156
