### ISSUE TITLE
Save and Close go to a bad path

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#22011]
### Steps to reproduce the issue
1) Go to admin menu: System/ Global configuration
2) Click in any Component. For example = Users
3) Save and Close
And the system redirect to Users view

### Expected result
After saving and closing follow in the actual view = System/ Global configuration

### Actual result
After saving and closing the system redirect to the component

### System information (as much as possible)
Joomla 3.8.12

**Comment by brianteeman** [comment]
i would say thats the intended behaviour. those links on the left are links to the  options for that component - they are not part of the global configuration

**Comment by ghost** [comment]
I go confirm to @Open2logic. Every Time a open a Module starting at Dashboard i expect to see Dashboard after closing Module ... and every Time i'm surprised to see Module View.

**Comment by Open2logic** [comment]
True Brian but after clicking on Save does not stay in this view for options for the components, goes to the component itself.

**Comment by tonypartridge** [comment]
I would have to agree that it makes sense to return to the previous page not where it assumes you may want to go, I.e. if you came from com_config to edit a component directly then great stay and reload, if not you should be returned to where you came from? I.e. the component

**Comment by Open2logic** [comment]
I repeat:
Go to System, Global configuration, in the left colukmn click in any component, SAVE and CLOSE  and NOW, magic!
You are in the component, not in System, Global configuration.

In the Global configuration, i  want to review the permissions of all the components for a new group of users, every time that i save and close, the system redirects me to the component.

**Comment by SharkyKZ** [comment]
Click `Save` instead of `Save and Close`?

**Comment by Open2logic** [comment]
Save and Close

**Comment by brianteeman** [comment]
Either do what sharkykz said and just use save or you might be able to do what you need from the advanced permissions option the user component. 

Either way the system is working as intended even if it is not what you expect.
