### ISSUE TITLE
The alias com-xxxx-name is already being used by COM_XXXX_NAME menu item ...

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#22019]
### Steps to reproduce the issue

- Install an extension that still have this legacy tag in the configuration XML:

```xml
	<!-- Administrator back-end section -->
	<administration>
		<menu view="cpanel" img="../media/com_xxxx/images/xxxx-icon.png">COM_XXXX_NAME</menu>
```

### Expected result

Installation success.

### Actual result

Error: The alias com-xxxx-name is already being used by COM_XXXX_NAME menu item ...

### System information (as much as possible)

Joomla_3.9.0-alpha-Alpha-Full_Package. PHP 7.1.21.

### Additional comments

~~The menu tag was used for icon definition on Joomla 1.5/2.5, but it is currently useless. However, there are many extensions that still have it in the XML configuration and the error is shown in the extension installation on Joomla 3.9.~~

**Comment by Bakual** [comment]
Afaik that menu tag creates the menu in the backend. It would be new to me that it is useless.
Only the "img" attribute is kind of useless since the Protostar menu doesn't show the image. It is shown in the Hathor menu however.

The error seems to come rather from a duplicate menuitem name. Eg COM_XXXX_NAME is also used in a different menu item already.

**Comment by anibalsanchez** [comment]
I'm testing on a clean J39 installation and the backend menu item is being created even without menu tag.

So, something has changed between J38 and J39, and an error is generated now.

Please, check this extension on J39 to better diagnose the case: https://www.extly.com/downloads/autotweetng-free/autotweetng-free-8-21-0.html

**Comment by brianteeman** [comment]
i just tried to install that extennsion but got the following error

![image](https://user-images.githubusercontent.com/1296369/45112971-07ffdf00-b141-11e8-9552-aa940c4625d2.png)

**Comment by anibalsanchez** [comment]
@brianteeman Really weird, it seems that it is updating without creating the tables. That line is only present in a script for an old version upgrade 7.2.0.

**Comment by anibalsanchez** [comment]
UPDATE: I've confirmed that other extensions (Weblinks, K2, etc) are installing fine. So, I'm looking for the difference that is triggering the error in J39.

**Comment by anibalsanchez** [comment]
The problem is the **view** attribute definition.

Until J38, it has been ignored by the installer (menu item link `index.php?option=com_autotweet`). 

I think that the attribute has been there since J25 and now it works again adding the view to the menu item link `index.php?option=com_autotweet&view=cpanel`. The change has been detected by a FOF validation.

I'm removing the view definition from the manifest to regain the previous behaviour and comply with the FOF validation. Since it hasn't been working in J3, the change doesn't affect the rest of the component.

The open question is if the view must be added or not and if it is added what the impact would be.

**Comment by anibalsanchez** [comment]
This is the FOF validation that expects a link without view: https://github.com/joomla/joomla-cms/blob/staging/libraries/fof/utils/installscript/installscript.php#L1776

**Comment by brianteeman** [comment]
Based in the comments above this should be closed

**Comment by alikon** [comment]
closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22019">issues.joomla.org/tracker/joomla-cms/22019</a>.</sub>
