### ISSUE TITLE
[3.9] #21695 breaks overrides usability needs revert or refactoring

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#22014]
### Steps to reproduce the issue
Unhappily,  PR #21695 was merged

Now, one has to click on search tools to define for which language site or admin to make the override.
It will always default to the alpha order of the language (and site) if not selected through searchTools when creating a new override.

We have to find a better solution imho.

I mean we may still use searchtools to filter (although we need a solution to display all overrides as the new field does not provide a possible empty Option), but we need a specific field separated from SearchTools to select to which language and client we want to create a new override for.

Instead of

<img width="781" alt="screen shot 2018-09-05 at 06 38 45" src="https://user-images.githubusercontent.com/869724/45071411-63e14e00-b0d6-11e8-97a0-fbc9f42c8d24.png">

and then click to get

<img width="821" alt="screen shot 2018-09-05 at 06 38 28" src="https://user-images.githubusercontent.com/869724/45071414-6e034c80-b0d6-11e8-9648-f8df5ff67547.png">

We need at least something like 

<img width="1187" alt="screen shot 2018-09-04 at 18 05 20" src="https://user-images.githubusercontent.com/869724/45071254-b40be080-b0d5-11e8-8e2d-a418a429f7dc.png">

and possibly modify the override edit form to choose there the language/client.

This is not so easy to do. 
To obtain the screenshot above, I moved the `language_client` field out of the `filter` fields as we do usually (plus added an option), and added a new layout where bar.php is customised.

so I did for `filter_overrides.xml`
```
<?xml version="1.0" encoding="utf-8"?>
<form>
	<field
		name="language_client"
		type="languageclient"
		filtermode="selector"
		onchange="this.form.submit();"
		>
			<option value="">COM_LANGUAGES_OVERRIDE_SELECT_LANGUAGE</option>
	</field>

	<fields name="filter">
		<field
			name="search"
			type="text"
			label="JSEARCH_FILTER"
			description="COM_LANGUAGES_SEARCH_IN_TITLE"
			hint="JSEARCH_FILTER"
		/>

	</fields>
	<fields name="list">
		<field
			name="limit"
			type="limitbox"
			label="JGLOBAL_LIMIT"
			description="JGLOBAL_LIMIT"
			class="input-mini"
			default="25"
			onchange="this.form.submit();"
		/>
	</fields>
</form>
```

and for the specific bar.php layout

```
defined('JPATH_BASE') or die;

$data = $displayData;

if ($data['view'] instanceof LanguagesViewOverrides)
{
	// We will get the language_client filter & remove it from the form filters
	$langClient = $data['view']->filterForm->getField('language_client'); ?>
	<div class="js-stools-field-filter js-stools-language_client">
		<?php echo $langClient->input; ?>
	</div>
<?php
}
// Display the main joomla layout
echo JLayoutHelper::render('joomla.searchtools.default.bar', $data, null, array('component' => 'none')); ?>
```
I also had to modify for the sake of the demo, i.e. to display the Select:
```
		// Add the languages to the internal cache.
		$this->cache = array_merge(parent::getOptions(), $languages);
```
in the new `languageclient` new field type

It does not work, i.e. the select box sticks its value to the first language in alpha order and site client. 

@wilsonge

**Comment by brianteeman** [comment]
OK I tried and hit the same problem. I can change it so that the select is displayed but I cant get that data into the edit form

**Comment by infograf768** [comment]
What have you done to get it to stick to something else than en-GB site ?
I could not do that here.

**Comment by brianteeman** [comment]
ah never tested that - it always returns to the first item :(

I am guessing it is because the values in the select are a combination of language and client eg value=en-gb1

**Comment by infograf768** [comment]
Succeeded in getting the filter to stick to the value chosen.

![screen shot 2018-09-09 at 08 40 53](https://user-images.githubusercontent.com/869724/45261941-1d5c5e00-b40c-11e8-83b6-b21e7a9d3a24.png)

But it is not yet propagated to the new override.

**Comment by wilsonge** [comment]
Closing as we have a PR with #22105

**Comment by infograf768** [comment]
Please rather test https://github.com/joomla/joomla-cms/pull/22107 which solves the usability.
