### ISSUE TITLE
[4.0] hard coded strings dropdown.php

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#22017]
The file `\layouts\joomla\toolbar\dropdown.php` has several hard coded strings that should be translatable

Note it is not just  as simple as creating a new string for the text that is there because the text is **wrong**

**Comment by HLeithner** [comment]
I can't find an usage of this layout in core. Can you point me in a direction?

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/45254945-9e6a1580-b378-11e8-98ed-ea244defb2f6.png)

**Comment by HRIT-Florian** [comment]
Oh okay, yes, it's not translated and even not displayed.
I would suggest to remove these whole unnecessary line including associaded CSS
https://github.com/joomla/joomla-cms/blob/5c2c1255b14f4ee90ebefd532436581ca0edbfa8/layouts/joomla/toolbar/dropdown.php#L37

**Comment by HLeithner** [comment]
some lines above is a aria-label:
https://github.com/joomla/joomla-cms/blob/5c2c1255b14f4ee90ebefd532436581ca0edbfa8/layouts/joomla/toolbar/dropdown.php#L31

What would you suggest to have as text brian?

**Comment by HRIT-Florian** [comment]
"Toggle Dropdown" should better be placed as title attribute for the button itself ;)

**Comment by HLeithner** [comment]
I think that "Toggle Dropdown" is pretty useless as aria label

**Comment by HRIT-Florian** [comment]
One question: Do we have a prefered language key prefix for layouts?

**Comment by HLeithner** [comment]
I think this text has to be set by the calling component.

**Comment by brianteeman** [comment]
Closed as resolved by #22429
