### ISSUE TITLE
media/system/js/fields/calendar-locales/  wrong translates and button "clear" not translated

### ISSUE THREAD

**Issue by boomsya** [joomla/joomla-cms#22025]
joomla 3.8.12
today i was modify one of component which contain Ukrainian interface
and i have found what dropdown calendar does not translate button "Clear" on calendar

so i was open media/system/js/fields/calendar-locales/uk.js   (and also files)
```
window.JoomlaCalLocale = {
	today : "Сьогодні",
	weekend : [0, 6],
	wk : "тждн.",
	time : "Час:",
	days : ["Неділя", "Понеділок", "Вівторок", "Середа", "Четвер", "П'ятниця", "Субота"],
	shortDays : ["Нд.", "Пн.", "Вт.", "Ср.", "Чт.", "Пт.", "Сб."],
	months : ["Січень", "Лютий", "Березень", "Квітень", "Травень", "Червень", "Липень", "Серпень", "Вересень", "Жовтень", "Листопад", "Грудень"],
	shortMonths : ["Січ.", "Лют.", "Бер.", "Квіт.", "Трав.", "Черв.", "Лип.", "Серп.", "Вер.", "Жовт.", "Лист.", "Груд."],
	AM : "AM",
	PM :  "PM",
	am : "am",
	pm : "pm",
	dateType : "gregorian",
	minYear : 1900,
	maxYear : 2100,
	exit: "Закрити",
	save: "Очистити"
};
```
param "save" translated as "Clear" in english translation. This is wrong translation. It must be "Зберегти",
in Russian translation it must be "Сохранить" too.

and this is translation list does not contain param 'clear'.
In Ukrainian translation it must be clear: "Очистити"
and in russian it must be clear: "Очистить"

**Comment by zero-24** [comment]
@infograf768 can you forward this to the respective TT's?

**Comment by boomsya** [comment]
uk.js right version:
```

window.JoomlaCalLocale = {
	today : "Сьогодні",
	weekend : [0, 6],
	wk : "тждн.",
	time : "Час:",
	days : ["Неділя", "Понеділок", "Вівторок", "Середа", "Четвер", "П'ятниця", "Субота"],
	shortDays : ["Нд.", "Пн.", "Вт.", "Ср.", "Чт.", "Пт.", "Сб."],
	months : ["Січень", "Лютий", "Березень", "Квітень", "Травень", "Червень", "Липень", "Серпень", "Вересень", "Жовтень", "Листопад", "Грудень"],
	shortMonths : ["Січ.", "Лют.", "Бер.", "Квіт.", "Трав.", "Черв.", "Лип.", "Серп.", "Вер.", "Жовт.", "Лист.", "Груд."],
	AM : "AM",
	PM :  "PM",
	am : "am",
	pm : "pm",
	dateType : "gregorian",
	minYear : 1900,
	maxYear : 2100,
	exit: "Закрити",
	save: "Зберегти",
	clear: "Очистити"
};
```

ru.js right version:

```
window.JoomlaCalLocale = {
	today : "Сьогодні",
	weekend : [0, 6],
	wk : "тждн.",
	time : "Час:",
	days : ["Неділя", "Понеділок", "Вівторок", "Середа", "Четвер", "П'ятниця", "Субота"],
	shortDays : ["Нд.", "Пн.", "Вт.", "Ср.", "Чт.", "Пт.", "Сб."],
	months : ["Січень", "Лютий", "Березень", "Квітень", "Травень", "Червень", "Липень", "Серпень", "Вересень", "Жовтень", "Листопад", "Грудень"],
	shortMonths : ["Січ.", "Лют.", "Бер.", "Квіт.", "Трав.", "Черв.", "Лип.", "Серп.", "Вер.", "Жовт.", "Лист.", "Груд."],
	AM : "AM",
	PM :  "PM",
	am : "am",
	pm : "pm",
	dateType : "gregorian",
	minYear : 1900,
	maxYear : 2100,
	exit: "Закрити",
	save: "Сохранить",
	clear: "Очистить"
};
```

english version wrong too. I think it is global mistake.

**Comment by infograf768** [comment]
Mistake also in en.js?

Sorry to say, but all calendar language js files are made on the model of en.js where we have
```
	exit: "Close",
	save: "Clear"
```

The param IS "save" but the value IS "Clear" and that is what it does, i.e. clearing the field.
Saving is done by hitting the "Enter" key or next to the dropdown.

**Comment by infograf768** [comment]
![clear](https://user-images.githubusercontent.com/869724/45163134-e4e03880-b1ef-11e8-8ac4-f09b4e92efcd.gif)

**Comment by boomsya** [comment]
button "Clear" works fine but it is not translating in other languages.
because option "clear" is missing and his value now into option "save" but "save" not using in calendar.
and option "save" translated wrong

**Comment by infograf768** [comment]
What the heck. You are partly right.
We must not change the value but the param indeed.
In English it is always fine, but not for other languages.
We need to change all the language locales to (for French)

`clear: "Effacer"`

instead of

`save: "Effacer"`

We do not need the option `save:"whatever"` at all...

will do patch now for all locales.

Thanks you for pointing to this issue.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/22026

**Comment by infograf768** [comment]
Closing as we have patch
