### ISSUE TITLE
[4.0] Invalid controller class: display

### ISSUE THREAD

**Issue by diddipoeler** [joomla/joomla-cms#22033]
### Steps to reproduce the issue
Update from 4.0 alpha 3 to 4.0 alpha 4

### Expected result
I got this error: **Invalid controller class: display** when i will login to admin site.

**Comment by ghost** [comment]
as far as i know its not possible to update an alpha, so you have to reinstall.

**Comment by ghost** [comment]
at https://developer.joomla.org/news/742-joomla-4-is-on-the-horizon-alpha-4.html: 

>Joomla 4.0 is known to not be mobile compatible nor upgradable at this point.

**Comment by SharkyKZ** [comment]
And use latest nightly please https://developer.joomla.org/nightly-builds.html.

**Comment by ghost** [comment]
thanks for the Hint, @SharkyKZ
