### ISSUE TITLE
Remove script type if empty string is sent.

### ISSUE THREAD

**Issue by Chaosxmk** [joomla/joomla-cms#22039]
### Is your feature request related to a problem? Please describe.
According to current specification for HTML 5 compliant browsers, the type attribute of script tags isn't required if the type is JavaScript. Modern browsers automatically identify omitted script types as JavaScript. No matter what value is sent as type attribute, type will be added, even sending an empty string.

`JFactory::getDocument()->addScript('script.js', array(), array('type' => ''));`
Becomes:
`<script src="script.js" type=""></script>`

### Describe the solution you'd like
To avoid setting off any deprecated behavior (but also not break backwards compatibility), why not have it set so that if a user provides an empty string for type, the type attribute isn't set.

`JFactory::getDocument()->addScript('script.js', array(), array('type' => ''));`
Becomes:
`<script src="script.js"></script>`

**Comment by mbabker** [comment]
You should still pass the type forward when registering scripts.

The `HtmlDocument` class has a parameter to toggle whether the document is built as HTML5 or HTML4/XHTML (it defaults to HTML4/XHTML in 3.x and in 4.0 defaults to HTML5), and the [script rendering process](https://github.com/joomla/joomla-cms/blob/eb68e01fada0ceac8695c386c9f9ac143db2f079/libraries/src/Document/Renderer/Html/HeadRenderer.php#L263-L339) already omits the type attribute in this case.

So best practice should be to always pass the type.  If you're building a template and want it to output as a HTML5 document, call `$this->setHtml5(true);` in your template's index.php file and core will take care of altering the output as appropriate.

**Comment by Chaosxmk** [comment]
Honestly, I feel like somewhere along the line, I just failed to read/understand the documentation for templates and missed that line entirely. Thank you for pointing it out.

**Comment by ghost** [comment]
closed as Issue looking solved. If i'm wrong please pardon and reopen.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22039">issues.joomla.org/tracker/joomla-cms/22039</a>.</sub>
