### ISSUE TITLE
Please make "Save and New" retain the category from the saved article for the new one.

### ISSUE THREAD

**Issue by Spudley** [joomla/joomla-cms#22031]
### Is your feature request related to a problem? Please describe.

When creating multiple articles, I finish one article, and press "Save and New". The form clears, and I can start creating the next.

This is great. However I would like a little more intelligence here with the defaults for the new blank article.

### Describe the solution you'd like

The main thing I'd like to change is that "Save and New" resets the category back to Uncategorised. When I'm creating multiple articles at once, I would almost always be adding them all to the same category, so it would be good if the category could be retained from the article I just saved.

Likewise with the Access and Language properties.

### Additional context

I'm using the latest Joomla (3.8.12).

**Comment by ReLater** [comment]
A partial workflow could be. When you're inside the articles overview:
- Set category searchtool filter to a single category.
- The same for state, language, viewlevel.
- Then click "New" and the new article will adapt all this settings. "Save and New" will inherit these settings, too.

**Comment by ghost** [comment]
@Spudley thanks for your Question, which belongs more to the [forums](https://forum.joomla.org/). As this repository concerns in first Place Joomla-Core coding and @ReLater have given Information for this Reasons closing this Issue.
