### ISSUE TITLE
[4.0] Repeat. Problem with router

### ISSUE THREAD

**Issue by vagabondo** [joomla/joomla-cms#22036]
Repeat (the problem is not solved)
    Log in to the Admin panel.
    Make new Article (Category: Uncategorised, name 333, alias - 333, featured). Save and close.
    Open Frontend Panel.
    At Home page see page 333. Сhoose it.
    And see adress: http://filiasfox.ultimatefreehost.in/?view=article&id=8:333&catid=2
Search Engine Friendly URLs - Yes.
Use URL Rewriting - Yes
Integration: Remove IDs from URLs - Yes

if exist and published other menu item "List All Categories" - nice.
if exist and not published other menu item "List All Categories" - not work.

This decision is not fine. The user should not think how to fix the situation by adding an unnecessary menu item.

**Comment by ghost** [comment]
Can a experienced User please Comment as the Issue is open since one Week and Status "New"?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22036">issues.joomla.org/tracker/joomla-cms/22036</a>.</sub>

**Comment by vagabondo** [comment]
At the moment there is no correct solution. The proposed options (entering in the menu of additional unused items, permission in the menu of category names) are not acceptable.

This problem was previously reported at 21935 (for joomla 4). Previously, it was opened for the Joomla 3.8. 
@csthomas wrote:
I will try to solve this problem, but you should reopen it. This issue is not easy because there will be a B/C break.
I proposed a solution some time ago and it was released with 3.8.4 and reverted with 3.8.5.
I have to redesign it to 4.0 and we'll see.

**Comment by stacymarkel** [comment]
These type of problem arises from user to user. Maybe your system is not working properly. Even Google can not provide the exact solution.
I recommend you to go to  [Linksys Support Number](http://www.linksysroutersupportnumber.com " Linksys Support Number"). They provide the best solution to router-related problems. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22036">issues.joomla.org/tracker/joomla-cms/22036</a>.</sub>

**Comment by vagabondo** [comment]
You wrote about the error in the router on the side of the hardware. I'm writing about a bug in the router on the site. The site's router does not work correctly with selected materials. The addresses of the site pages (for selected materials at home page) are formed incorrectly.

**Comment by infograf768** [comment]
@stacymarkel 
I see you just joined github. 
The issue described here is related to Joomla router CODE.

**Comment by ggppdk** [comment]
stacymarkel seems to be a SPAM account, posting malware links

**Comment by infograf768** [comment]
I delete the post now and inform maintainers

**Comment by csthomas** [comment]
I added a solution that breaks B/C. I invite you to test #22229

**Comment by vagabondo** [comment]
> I added a solution that breaks B/C. I invite you to test #22229

Your solutions is in the night builds? If yes, then no changes occurred. You can go to the site http://www.joomla-tested.ru. Problem exist. Even if do not use multilingual site (but site at future be multilingual).

**Comment by mbabker** [comment]
An open pull request is not going to be included in the nightly builds.

**Comment by vagabondo** [comment]
Good. I will wait

**Comment by ghost** [comment]
> Good. I will wait

@vagabondo every Pull Request needs minimal 2 successfully Tests. If you Test theres only need for one more. Then Maitainer decide if the PR will be merged for next Update. So you wait that other test, hopefully other does.

**Comment by csthomas** [comment]
To test my patch you have to extract this zip file on your joomla 4. There are 20 changed files.
[router_no_default_J4.zip](https://github.com/joomla/joomla-cms/files/2395889/router_no_default_J4.zip)

**Comment by vagabondo** [comment]
Thanks you. Don't work

The requested page can't be found. Error: 404
Adress: http://www.joomla-tested.ru/component/content/article/444?catid=2

**Comment by infograf768** [comment]
@vagabondo 
Please add your comments to the related PR, i.e. in https://github.com/joomla/joomla-cms/pull/22229

**Comment by csthomas** [comment]
This error is related to the different PR #20979. To fix it upload one more file from https://github.com/joomla/joomla-cms/blob/7ba153eadc50c129e67fb45f378b379ffe640d2b/libraries/src/Component/Router/Rules/NomenuRules.php

Click on "Raw" button and upload it in the correct place (overwriting the old file).

**Comment by ghost** [comment]
@csthomas can this Issue be closed?

**Comment by ghost** [comment]
Closing Issue. Please reopen if needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22036">issues.joomla.org/tracker/joomla-cms/22036</a>.</sub>
