### ISSUE TITLE
Searchtool filters in com_modules are set for frontend after save2copy

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#22037]
### Steps to reproduce the issue
Go to the modules overview in the backend, choose the client "administrator".
Open one of the modules and save as copy or save and new.
Go back to the list view and open searchtools. 

### Expected result
Searchtool filters show values for the backend as before

### Actual result
The filters for positions and modules show the values of the frontend.
After changing the filter status, all searchtool filters are correct.

![screen shot 2018-09-07 at 11 45 43](https://issues.joomla.org/uploads/1/cb4c6bc30c9cebf2a81ae1d6656433ea.png)

### Additional comments
Joomla 3.8.12 and 3.9 nichtly build

**Comment by brianteeman** [comment]
Confirmed

**Comment by SharkyKZ** [comment]
Test PR #22040 please.

**Comment by ghost** [comment]
closed as having Pull Request #22040
