### ISSUE TITLE
[4.0] Installer drag and drop not possible

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#22043]
### Steps to reproduce the issue
Open the Installer try to install an extension via drag and drop.

### Expected result
The installation starts like in J3.x

### Actual result
Nothing happens, there is only a Headline "tpe not found" above the panel.
Now use the Button "select a file" and get the file from the explorer. The same extension ist installed as usual. 

### System information (as much as possible)
win10, J4.0 latest version fom github,

**Comment by infograf768** [comment]
Confirmed with language pack

**Comment by ghost** [comment]
Confirmed using Patchtester and this Settings:
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.19
- MySQLi 5.7.21-cll-lve

**Comment by roland-d** [comment]
I am looking into this.

**Comment by ghost** [comment]
thanks @roland-d

**Comment by ghost** [comment]
closed as having Pull Request #22071
