### ISSUE TITLE
White page with PHP v.7.2 and Joomla 3.8.12

### ISSUE THREAD

**Issue by Mkvixj00** [joomla/joomla-cms#22046]
### Steps to reproduce the issue

On a shared hosting, if I change the PHP version from 7.0 to 7.2, I get a blank page both on frontend and backend. If I restore the previous PHP version the site reappears correctly.
By activating "display erros" in php.ini, the following message appears:

Warning: session_start (): Failed to read session data: user (path: / opt / alt / php72 / var / lib / php / session) in / home / myusername / public_html / mysubdirectory / libraries / joomla / session / handler / native .php online 260
Error: Failed to start the session

### Expected result
The correct display of site pages

### Actual result
A white page, a blank page both on frontend and backend, or this error if I enable "display errors"in php.ini : 
Warning: session_start (): Failed to read session data: user (path: / opt / alt / php72 / var / lib / php / session) in / home / myusername / public_html / mysubdirectory / libraries / joomla / session / handler / native .php online 260
Error: Failed to start the session

### System information (as much as possible)
Joomla 3.8.12
"Wedding" template, a recent theme produced by Joomlabamboo.com
RSForm! Pro 1.52.14 installed
Akeeba Backup Installed
Gantry template installed, but not used
the websiste is on a shared hosting with cPanel
Joomlart Joomla GDPR Component 1.0.4
nothing else installed

### Additional comments
I tried to disable all modules, some third-party extensions (RSForm and the Gantry), but the white page remained.
Later I tried to set Protostar as the default template, in place of what was there before, which was "Weddings" template produced by Joomlabamboo.com.
I have never disabled the extensions related to the Joomlabamboo.com template.
I have another site that uses the same template, with joomla 3.8.12, but it works well with PHP 7.2.9.

**Comment by brianteeman** [comment]
is that other site on the same server as the one that is not working?

**Comment by Mkvixj00** [comment]
Hi!
The other site is on another server, not on a shared hosting, but on a VPS Ubuntu. 
They are different sites of different owners.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22046">issues.joomla.org/tracker/joomla-cms/22046</a>.</sub>

**Comment by Mkvixj00** [comment]
Hi!
By plotting php processes, I have found that the cause of this malfunction is the "mod_roknavmenu" component. At the moment I have disabled it and the site is using version 7.2 and is correctly visible; it is possible that this component is not compatible with this version of php.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22046">issues.joomla.org/tracker/joomla-cms/22046</a>.</sub>

**Comment by brianteeman** [comment]
i asked because it sounds like a misconfigured php on the effected server - sppecificaly the session.path

**Comment by Mkvixj00** [comment]
How to resolve it?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22046">issues.joomla.org/tracker/joomla-cms/22046</a>.</sub>

**Comment by brianteeman** [comment]
As it is not a joomla issue you should speak to your host

**Comment by Mkvixj00** [comment]
Hi!
Sorry, but my technician said that having carried out the tests using the Protostar template, then disabling all the modules one at a time and then disabling some extensions, I had to report the problem to joomla.org
Are You sure that the problem is only a misconfigured "session.save_path"?
Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22046">issues.joomla.org/tracker/joomla-cms/22046</a>.</sub>

**Comment by rdeutz** [comment]
If 3.8.12 wouldn't run on 7.2 we would know. It is for sure not a problem with the core joomla, you can ask on the forum. For me it looks as your session path is not writeable or doesn't exists

**Comment by Mkvixj00** [comment]
Ok, thanks!
Regards<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22046">issues.joomla.org/tracker/joomla-cms/22046</a>.</sub>

**Comment by ggppdk** [comment]
You do not mention the session handler that you are using
(or i missed it ?)

Before you change from PHP 7.0 to PHP 7.2 

Please check that the session handler that you have configured in Joomla Global configuration
(inside "System" Tab)
has been configured properly for PHP 7.2 too

Also you may try using a different one

**Comment by Mkvixj00** [comment]
Hi, ggppdk!
If I set session handler from "database" to "PHP" I have a white page with this error: "Error: Call to a member function getActive() on null: The MySQLi extension for PHP is not installed or enabled."
Regards<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22046">issues.joomla.org/tracker/joomla-cms/22046</a>.</sub>

**Comment by ggppdk** [comment]
Ok,
i think now you have gotten a good message ... and you can solve this 

Enable mysqli for PHP 7.2 and / or try Mysql (PDO) in global configuration inside System TAB

**Comment by brianteeman** [comment]
And that confirms that your installation of php 7.2 is not correct

**Comment by Mkvixj00** [comment]
Hi ggppdk!
You say:
>Enable mysqli for PHP 7.2 and / or try Mysql (PDO) in global configuration inside System TAB

But I don't find msqli or Mysql (PDO) settings in System TAB of gloabal config. I attached a screeshot of my SyStem Tab.
![screen shot 2018-09-08 at 09 02 12](https://issues.joomla.org/uploads/1/7c95597d8342bca57fc3c0fa7a42a40a.jpg)

Thanks
Regards<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22046">issues.joomla.org/tracker/joomla-cms/22046</a>.</sub>

**Comment by ghost** [comment]
can you please discuss on the [forums](https://forum.joomla.org/) as this repository concerns in first Place Joomla-Core coding.

**Comment by Mkvixj00** [comment]
Hi franz-wohlkoenig!
Ok, I will post this discussion on forum.
Thanks
Cheers<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22046">issues.joomla.org/tracker/joomla-cms/22046</a>.</sub>

**Comment by ggppdk** [comment]
> But I don't find msqli or Mysql (PDO) settings in System TAB of gloabal config.

My mistake the setting is inside "Server" TAB, 

> Ok, I will post this discussion on forum.
Thanks
Cheers

yes, ...

**Comment by Mkvixj00** [comment]
Hi ggppdk!
There is no need to publish the problem on the forum. By setting MySQL (PDO), the site now works correctly with PHP 7.2.
Thanks so much!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22046">issues.joomla.org/tracker/joomla-cms/22046</a>.</sub>

**Comment by ghost** [comment]
@Mkvixj00 glad that this works now and thanks to all commented here.

**Comment by mtkumar82** [comment]
I think this could be due to wrong database information. please try to comment the line from 260 to 263 in libraries/joomla/session/handler/native.php and see if there are error for mysql not connected. I have this problem due to that, Hope anyone have same and this solution work for them.

**Comment by brianteeman** [comment]
NEVER change core files!!!!

**Comment by mtkumar82** [comment]
No I am not suggesting to make changes in core file. I am just suggesting it to debug the issue. If issue found revert the changes back in core file.

**Comment by Holyub** [comment]
Hi great gurus and lovers of Joomla.

Check if you db password contains special characters like ":" 
Worked for me (had issue with 3.9.11 after copying website files and db for testing & pre-prod purposes from php5.x environment to  debian 10/php7.3/mariadb 10.3.15 pre-prod environnement).

good job guys,
you're formidables !

**Comment by maryyocelotl** [comment]
disculpen tengo este error, pero solo puedo interactuar mediante FTP, que puedo hacer??
