### ISSUE TITLE
[4.0] Fix how modals are displayed

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#22044]
https://github.com/joomla/joomla-cms/pull/21847 and https://github.com/joomla/joomla-cms/pull/21852 have both been proposed as ways to solve where modals are inserted on the page. Clearly neither are optimal solutions. I've merged 21487 to allow patchtester to work for now. But we need to come up with a better solution before stable

**Comment by coolcat-creations** [comment]
Can we display the notifications as pushdown instead of modals?

**Comment by wilsonge** [comment]
If we can find someone sufficiently well versed in javascript to do it sure

**Comment by chmst** [comment]
Same problem with Versions. The contenthistory-modal is overlayed by the backdrop layer (found in contacts and articles). So some improvements concerning a11y must wait.

**Comment by infograf768** [comment]
> Same problem with Versions. The contenthistory-modal is overlayed by the backdrop layer (found in contacts and articles). 

It is not solved for Versions, even temporarily, as it does not use PopupButton

**Comment by Quy** [comment]
Please test PR #24369<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22044">issues.joomla.org/tracker/joomla-cms/22044</a>.</sub>

**Comment by infograf768** [comment]
Please see and test https://github.com/joomla/joomla-cms/pull/25147
