### ISSUE TITLE
[4.0] COM_USERS enabling and adding YubiKey runs into Fatal error Joomla\CMS\Encrypt\Randvalinterface not found

### ISSUE THREAD

**Issue by HRIT-Florian** [joomla/joomla-cms#22053]
### Steps to reproduce the issue
Enable Two Factor Authentication - YubiKey Plugin
Edit a user and set Authentication Method to YubiKey 
Add  a YubiKey and trigger save

### Expected result
Save event should run withour errors and YubiKey should be added

### Actual result
Save event did run into fatal error: Interface 'Joomla\CMS\Encrypt\Randvalinterface' not found in /html/joomladev_nightly-build2/libraries/src/Encrypt/Randval.php on line 16

### System information (as much as possible)
Joomla! 4.0.0-alpha5-dev Development [ Amani ] 22-July-2018 22:58 GMT

**Comment by ghost** [comment]
changed Title to show its about 4.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22053">issues.joomla.org/tracker/joomla-cms/22053</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #22054
