### ISSUE TITLE
Pre-Installation Check incomplete

### ISSUE THREAD

**Issue by Nzara** [joomla/joomla-cms#22057]
### Steps to reproduce the issue
1. set php.ini with
* memory_limit=16M
* upload_max_filesize=2M
* post_max_size=2M
* max_execution_time=30

2. Install Joomla as documented

### Expected result

Pre-Installation check indicates failure to meet required php.ini settings

### Actual result

* Pre-installation check show all items 'YES'
* installation freezes at 25% progress

### Additional comments

Works fine with recomended settings.
Defaults of some hosting providers may below recomended setting.
Non-expert users are very likely aware of this. We should make them aware of it and avoid frustration.

**Comment by brianteeman** [comment]
It should work with those settings why do you expect it to say it failed to meet the required settings

The fact that it fails to install is a problem that will need to be fixed

**Comment by Nzara** [comment]
Well ..., I was under the impression, it needs not to install under these poor settings. 
Let's rephrase my expectation 'Installation must succeed if the pre-installation check passes'. A solution may address either side.

**Comment by mbabker** [comment]
Without knowing why "installation freezes" there is little to do here.  Is it really freezing because of the memory?  There are no uploads in the install app so upload size is no issue here.  POST size should also not be an issue.  Time may be a problem on a lower end configuration.  But this is all blindly guessing without any real data on the underlying issue.

**Comment by brianteeman** [comment]
Can you please which version of joomla you were trying to install?

**Comment by ghost** [comment]
@brianteeman Build: 3.8.12 is given in Issue Tracker.

**Comment by Nzara** [comment]
I tried to install 3.8.12. (I noted this in a form field when creating this issue, but have no idee, where this is shown now).
Freeze means: The page with the progress bar appears. The progress bar advances somewhere near 20%, The Joomla logo is spinning. This for at least 30 minutes. Of course, I can close the browser (firefox), but nothing more meaningfull. 

This happens on Windows 10 with XAMPP. The interessting thing: changing the settings to the recomended values and the installtion succeeds in less than a minute.

**Comment by mbabker** [comment]
If it "freezes" that generally means a non-JSON response was returned from the server (you can see this on the network tab of your browser's developer console), and that breaks the JavaScript for the installation app.  And when that happens that generally means there was some kind of fatal error.  In your case, it could very well be PHP running out of memory.

> changing the settings to the recomended values and the installtion succeeds

What recommended values?

**Comment by Nzara** [comment]
Recomended values: https://docs.joomla.org/J3.x:Installing_Joomla/en
     memory_limit - Minimum: 64M Recommended: 128M or better
    upload_max_filesize - Minimum: 20M
    post_max_size - Minimum: 20M
    max_execution_time: At Least 120 Recommended: 300

**Comment by mbabker** [comment]
Here's the key phrase, just above that:

> The values for PHP.ini below are suggested values only.

The POST and upload sizes are decent to allow large file uploads (large images, our core ZIP packages are sitting at around 13 MB).  These values being decent though only impacts Joomla use when it comes to upload actions (core/extension updates, image uploads, etc.).

Max execution time is an arbitrary change, if something is failing at 30 seconds you've got bigger problems in all honesty.

As for memory limit, this one really needs to be benchmarked if we're going to do anything with it.  IIRC core PHP starts this value at 128M or 256M, there really should be no need to ever lower it and if someone is doing that then I'd say that's an issue they need to sort out (or the hosting provider doing it needs to be talked to).

**Comment by Nzara** [comment]
I benchmarked the installtion process with this configuration:
```
 Install File: Joomla_3.8.12-Stable-Full_Package
 Install Sample Data: Default English (GB) Sample Data	
 Database Type 	mysqli
 Host Name 	localhost
 Username 	joomla
 Database Name 	joomla
 Table Prefix 	jo_
 Old Database Process 	Remove 
```
It appears _max_execution_time_ is the relevant setting. A value below 40 causes the symptoms described. 
I think a pre-installation check against a value below 50 shoud be added. This will prevent user frustation and it will guide the user to proper php settings.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22057">issues.joomla.org/tracker/joomla-cms/22057</a>.</sub>

**Comment by jwaisner** [comment]
Closing as it has been noted this is not a bug with Joomla and that the host settings may need checked/adjusted.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22057">issues.joomla.org/tracker/joomla-cms/22057</a>.</sub>
