### ISSUE TITLE
[4.0] com_contact.mail adding custom field editor as required is marked as optional and required

### ISSUE THREAD

**Issue by HRIT-Florian** [joomla/joomla-cms#22056]
### Steps to reproduce the issue
Create an editor custom mail field at context com_contact.mail.
Mark it as requiered
Check the editor custom field at contact form frotend

### Expected result
Field should be required not optional

### Actual result
Field is marked as required and optional

![editorfield](https://user-images.githubusercontent.com/12803406/45253398-b3d64400-b366-11e8-9f35-85b4ed9e5b09.jpg)

### System information (as much as possible)
Joomla! 4.0.0-alpha5-dev Development [ Amani ] 22-July-2018 22:58 GMT

### Additional comments
Due to this solution https://github.com/joomla/joomla-cms/blob/staging/components/com_contact/layouts/joomla/form/renderfield.php#L31 which did now not more work till now, because editor tinymce https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/editors/tinymce/tinymce.php#L132 has no required class and required field param is also not accessacble at editors plugin onDisplay() method

**Comment by ghost** [comment]
@Didldu-Florian is this issue resolved?

**Comment by ghost** [comment]
Closed due the Lack of response. It can always reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22056">issues.joomla.org/tracker/joomla-cms/22056</a>.</sub>
