### ISSUE TITLE
[4.0] two factor authentication

### ISSUE THREAD

**Issue by joomlamarco** [joomla/joomla-cms#22052]
### Steps to reproduce the issue
enable two factor authentication (it doesn't matter if google or ypubikey or both). go to users/manage and select the user you want to set the two factor authentication and activate the two factor authentiction (as already said, it doesn't matter wich one) by putting in the mentioned code and save it.
Now log out and log in again **without** tfa code.

### Expected result
y<ou shouldn't log in 

### Actual result
you can log in

### System information (as much as possible)
PHP: PHP 7.2.9
MySQLi 5.5.5-10.2.17-MariaDB
Web Server 	Apache

**Comment by ghost** [comment]
changed Title so its easier to read its about 4.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22052">issues.joomla.org/tracker/joomla-cms/22052</a>.</sub>

**Comment by HRIT-Florian** [comment]
Did you added and enabled yubikey or google for the user?
I'm wondering because adding Yubikey runs into an error with me #22053
Check my steps at that related issue for activating Yubikey ;)

**Comment by joomlamarco** [comment]
yes, it's true. adding yubikey runs into an error. Sorry, I forgot to ad this failure ...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22052">issues.joomla.org/tracker/joomla-cms/22052</a>.</sub>

**Comment by ghost** [comment]
@joomlamarco @Didldu-Florian is this an duplicate Report or different Issues?

**Comment by joomlamarco** [comment]
it's the same issue. I repoted it as an user and @Didldu-Florian reported it as a developer

**Comment by ghost** [comment]
thanks for Information @joomlamarco Can you please close this Issue?

**Comment by HRIT-Florian** [comment]
Due to pr https://github.com/joomla/joomla-cms/pull/22054 it can be closed ;)

**Comment by ghost** [comment]
@Didldu-Florian will close it if @joomlamarco don't. I try that User close by himself so i have less work in the long run :-)
