### ISSUE TITLE
[4.0] Backend Template Template Styles

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#22058]
I think the Backend Template Style should not refer to any godness or god - even if the name is chosen so, it does not have to be explained in text.
Additionally, there are Parameters missing to change Backend Logos / Colors and to set up the Admin Login Background. How can the template scss files be parametrisized ?

<img width="1426" alt="grafik" src="https://user-images.githubusercontent.com/828371/45253509-c0f43280-b368-11e8-8527-27b4b7421321.png">

**Comment by dgrammatiko** [comment]
> How can the template scss files be parametrisized

They can't unless Joomla requires an installation of Nodejs. That's the reason I asked couple weeks ago to move to css custom properties (variables). Later on people will understand what and more importantly *why* I was talking about but it will be too late to switch...

**Comment by brianteeman** [comment]
> I think the Backend Template Style should not refer to any godness or god - even if the name is chosen so, it does not have to be explained in text.

Sorry but that is plain crazy

**Comment by coolcat-creations** [comment]
> Sorry but that is plain crazy

This information is completely useless as your comment.

**Comment by coolcat-creations** [comment]
> They can't unless Joomla requires an installation of Nodejs. That's the reason I asked couple weeks ago to move to css custom properties (variables). Later on people will understand what and more importantly why I was talking about but it will be too late to switch...

We have too... Users are using custom colors for their backends. How can this be solved?

**Comment by ghost** [comment]
> Sorry but that is plain crazy

@brianteeman can you please explain the Reasons for your Opinion?

**Comment by dgrammatiko** [comment]
> How can this be solved?

Either Joomla 4:
- will require a Nodejs and npm installation
- use css variables
- find someone to implement a WASM version of the scss compiler and patch the missing holes (eg autoprefixer)

The easiest way out is to use css variables. Also it's the platform, SCSS is not a language supported by the platform and that alone is a pretty good reason to just drop it (since in the PHP world there are no equivalent of node_scss or autoprefixer)!

**Comment by dgrammatiko** [comment]
@coolcat-creations actually there is one more option:

Keep the crappy overriding inline css that exist also in J3' ISIS:
- even more bloated code on top of the already huge css framework

But this actually reveals the true weakness of the system: it cannot provide a solid solution for properly spitting HTML and the relative CSS. HTML and CSS in Joomla are treated as unrelated products which is a great pitfall (that's the reason people like Bootstrap, it covers this weakness very well)...

**Comment by brianteeman** [comment]
> @brianteeman can you please explain the Reasons for your Opinion?

Because removing the description of the name just because you dont like to see the word god written on the page is crazy. Just as removing the word Isis from Joomla 3 would be crazy

**Comment by ghost** [comment]
Thanks for your Comment @brianteeman, now i understand.

**Comment by dgrammatiko** [comment]
FWIW I see @mbabker' proposal as a solution to this ridiculous issue: Just use the name `system` or `default` for both templates. Joomla has nothing to do with the stars or the Egyptian Gods, this idea is totally stupid. Also I can't find a description of MacOS `High Sierra` or the Android `Kit Kat`, probably if these guys don't have to explain a name also Joomla doesn't have to as well. This is another of those creepy legacy ideas that some people feel very strongly about but in reality are totally outdated and plain stupid

**Comment by coolcat-creations** [comment]
Totally Agree to @dgrammatiko

**Comment by mbabker** [comment]
Either the names and descriptions stay as is or the core templates in 4.0 are renamed "Joomla Administrator 4.0" and "Joomla Frontend 4.0" (or some even more generic names).

4.0 is terribly broken right now and we want to have yet another complaining session about a word in the name or description!?  There are more than enough bugs to be fixed than dealing with the political correctness of whether "god", "master", or a handful of other words that social justice warriors want banned from everyday use.

**Comment by alikon** [comment]
funny  :laughing:
should be a virus  in open source community,  have seen quite the same in redis for `master and slave`

**Comment by crystalenka** [comment]
Sorry, but whats the harm in keeping the reference? It’s not relevant but it’s not harmful. Personally I enjoy little useless trivia like that, I find it interesting. /shrug

**Comment by coolcat-creations** [comment]
I wanted to take care of some people that always say that "religion" or at least "religious terms" should be seperated from software (at events and so on).
Seems in THIS spefic case the "opinion" is different. 

Maybe we can start wishing a Merry Christmas again to some users in blogposts :-D

**Comment by brianteeman** [comment]
please keep your sarcastic comments to yourself
