### ISSUE TITLE
Captcha inadvertently required for sending article link with email from front end

### ISSUE THREAD

**Issue by Thomsterdam** [joomla/joomla-cms#22064]
### How to reproduce issue
Send a link of an article from front end on a clean install of Joomla! 3.9 (Click on the send email icon at the top right of an article. A pop up appears and at the top I see an error message: "Captcha plugin not set or not found. Please contact a site administrator.")

### Expected result:
I can send an email with a link to an article without a captcha

### Actual result
Joomla requires a captcha and gives this Error message:
_______________
Error
Captcha plugin not set or not found. Please contact a site administrator.
_______________

### System information (as much as possible)
Joomla! Version 
Joomla! 3.9.0-alpha Alpha [ Amani ] 31-August-2018 12:30 GMT
Joomla! Platform Version 	
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0 
PHP: 7.2

### Additional comments

![screen shot 2018-09-08 at 11 57 06](https://issues.joomla.org/uploads/1/16329ed90aa5e69bdf94bbb4d9718ec5.png)

**Comment by brianteeman** [comment]
Please test #21979

**Comment by Thomsterdam** [comment]
With latest Joomla 3.9 alpha2 (nightly builds) this works. 

Thanx for the head up, @brianteeman 

Thom<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22064">issues.joomla.org/tracker/joomla-cms/22064</a>.</sub>
