### ISSUE TITLE
[4.0] [UX] mod_random_image did not display image correctly if no width and hight is set

### ISSUE THREAD

**Issue by HRIT-Florian** [joomla/joomla-cms#22065]
### Steps to reproduce the issue
Go to modules and set a new mod_random_image module
Set path to image folder like: images/banners
Leafe width and hight emty

![randomimage](https://user-images.githubusercontent.com/12803406/45254002-3ca5ad80-b370-11e8-8247-112171984da2.jpg)

### Expected result
html width and hight attribs should be emtpy, which should effect auto scale

### Actual result
width is set to zero which effect no display!

![randomimage_2](https://user-images.githubusercontent.com/12803406/45254006-40d1cb00-b370-11e8-8b10-ec9cd6194ac7.jpg)

**Comment by ghost** [comment]
closed as having Pull Request #22068

**Comment by Quy** [comment]
Please test #32075
