### ISSUE TITLE
Privacy Note Error

### ISSUE THREAD

**Issue by Thomsterdam** [joomla/joomla-cms#22066]
This issue was mentioned in issue #20800 @sandewt 
### Steps to reproduce the issue
This issue report assumes that the Captcha issue #22064 has been resolved OR that Captcha is turned on.
- Turn on the "Content - Confirm Consent" plugin
- In Article > Options set "Show Email" to "Show"
- Send a link to an article from the the front end (Click on the link at the top right of an article and select ‘send email’).
- Fill in the form and tick the Privacy Note tick box.

### Expected result
Email is sent

### Actual result
Email is **not** sent. An error message is displayed at the top with the legend: ‘Field Required: Privacy Note’.

### System information (as much as possible)
Joomla! Version
Joomla! 3.9.0-alpha Alpha [ Amani ] 31-August-2018 12:30 GMT
Joomla! Platform Version
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
PHP: 7.2

### Additional comments

![screen shot 2018-09-08 at 12 36 23](https://issues.joomla.org/uploads/1/c74e8333a18c9bb3e2bc69a83fd5f69b.png)

**Comment by tonypartridge** [comment]
Is the tick on by default?

**Comment by SharkyKZ** [comment]
`com_mailto` was migrated to `JForm` but form data is still hardcoded. So no plugin support.

CC @zero-24.

**Comment by Thomsterdam** [comment]
@tonypartridge quote: "Is the tick on by default?"

No the tick is not there by default; the tick box obviously is. Before making the screen shot after trying to send the e-mail, I ticked it again, just for the purpose of the screenshot.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22066">issues.joomla.org/tracker/joomla-cms/22066</a>.</sub>

**Comment by zero-24** [comment]
> CC @zero-24.

Thanks for cc'ing me. I have now looked into it twice but i have not found a solution nor got any response from others i asked to take a look. I would suggest to drop my plugin added with 3.9 and replace it with an switch / option in com_contact that enables this checkbox. The hole idea of building a plugin type of system with that plugin got lost in the way the privacy suite got's build so i think it would be easier to just drop the useless not working plugin now (before the final release) and replace it with an hard coded checkbox and be done with it. Any opinions @mbabker @brianteeman ?

**Comment by mbabker** [comment]
Architecturally there should not be cross-component couplings.  Plugins are entirely misused in this project, but the plugin that is there now is doing the right thing.

**Comment by zero-24** [comment]
Well than we are going the softcode it that way: https://github.com/joomla/joomla-cms/pull/22481 here you go please test @Thomsterdam @SharkyKZ @tonypartridge
