### ISSUE TITLE
Is there a way to disable or hook in invisible recaptcha for GEO IP China?

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#22063]
### Is your feature request related to a problem? Please describe.
Running a huge multilanguage site with 6 Languages.
In China Google Recaptcha (no matter which version) is blocked and users cannot register at the website.

Is there any way to remove recaptcha only for China or is there interest to have an alternative core solution which works lokal similar to this PR ? https://github.com/joomla/joomla-cms/pull/19286

**Comment by brianteeman** [comment]
> Is there any way to remove recaptcha only for China

No not really its a limitation of google recaptcha. Your only option would be to use a self hosted captcha plugin of which there are many

**Comment by brianteeman** [comment]
Closed as answered
