### ISSUE TITLE
[4.0] custom field checkboxes: subform plus button wan't work

### ISSUE THREAD

**Issue by gorgonz** [joomla/joomla-cms#22069]
### Steps to reproduce the issue
select articles => new field
choose field type checkboxes
try to add checkbox values by pushing the "+" button

### Expected result
a new row is created to add a text/value pair

### Actual result
nothing happens

### System information (as much as possible)
using Joomla! 4.0.0-alpha5-dev during PBF

**Comment by ghost** [comment]
@gorgonz Thanks for Report. The Issue has been reported #21877 so closed as duplicate Report.
