### ISSUE TITLE
typecasting code privacy content plugin

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#22079]
### Steps to reproduce the issue

With the MySQL database, numeric fields should not be quoted, so it is important that they be typecast instead. (cf: 'Secure_coding_guidelines')

File in case: ...\plugins\system\privacyconsent\privacyconsent.php

*Line: 579*

```->where($db->quoteName('id') . ' = ' . $db->quote($user->id));```

Should be typecast

```->where($db->quoteName('id') . ' = ' . (int) $user->id);```

*Line: 649 (casting is missing)*

```->where($db->quoteName('id') . ' = ' . $user->id);```

Should be typecast

```->where($db->quoteName('id') . ' = ' . (int) $user->id);```

### System information (as much as possible)

J.3.9

### Additional comments

See https://docs.joomla.org/Secure_coding_guidelines

**Comment by alikon** [comment]
should be fixed in #22088 please test

**Comment by ghost** [comment]
closed as having Pull Request #22088
