### ISSUE TITLE
[4.0] com_content Update Form is broken

### ISSUE THREAD

**Issue by Schmidie64** [joomla/joomla-cms#22077]
### Steps to reproduce the issue
Go to Article. 
Create new Article.
Edit created Article.

### Expected result
Everything works as expected.

### Actual result
![article](https://user-images.githubusercontent.com/20770106/45254869-e17bb700-b37f-11e8-983f-dcb6a372f2ae.JPG)

### System information (as much as possible)
Windows 10 17134, XAMPP (Apache/2.4.27 (Win32) OpenSSL/1.0.2l PHP/7.1.8)
Joomla! Version: Joomla! 4.0.0-alpha5-dev Development [ Amani ] 22-July-2018 22:58 GMT
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by ghost** [comment]
closed as having Pull Request #22078
