### ISSUE TITLE
Category Manager - drag & drop ordering too difficult

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-cms#22076]
The drag & drop of categories in Category Manager does not work as expected (like in Joomla 3)

### Steps to reproduce the issue
In a Joomla 4 site with example content, create a new Category (Content > Categories > New, do not select a parent) and Save it.
Try to move it to the top of the list of Categories by drag & drop.
It's confusing that submenus will be visible and that do not see that you cannot drop it there.

See this video: https://www.dropbox.com/s/t1ix0ud7phjhxha/categories-2018-09-08_15.40.36.mkv?dl=0

### Expected result
In Joomla 3 (see the end of the video) when dragging a menu item, all sub menu items where you could not drop the item, would become invisible. Only the menu items with which you could change the order of your drag+drop category would be visible (see the end of the video)

### Actual result
It's very difficult to drag & drop an item and it works confusing. 
![screen shot 2018-09-08 at 13 58 31](https://issues.joomla.org/uploads/1/ca20ff14970e3097ce8034c04af6fcb3.png)

**Comment by brianteeman** [comment]
should be fairly easy to resolve by  updating the js

**Comment by jwaisner** [comment]
@pe7er are you still experiencing this difficulty in the latest J4 build?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22076">issues.joomla.org/tracker/joomla-cms/22076</a>.</sub>

**Comment by pe7er** [comment]
@jwaisner Thanks for reminding me about this issue

No, I cannot remember having experienced this issue in the latest J4 build.
I'm closing this issue...
