### ISSUE TITLE
preview modul position

### ISSUE THREAD

**Issue by IsarBella** [joomla/joomla-cms#22083]
### Steps to reproduce the issue
For preview modul position z-index has to be changed

### Expected result
All modul positions will be shown

### Actual result
Only a few modul positions are shown

**Comment by ghost** [comment]
Please provide System Informations like copied from your Backend "System > System Information":

Setting | Value
-- | --
PHP Built On | Linux lamp122.cloudaccess.net 3.10.0-714.10.2.lve1.5.12.el6h.x86_64 #1 SMP Fri Feb 2 01:43:56 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.18-cll-lve
Database Collation | utf8mb4_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.1.15
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.8.12-dev Development [ Amani ] 31-July-2018 14:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0

**Comment by brianteeman** [comment]
Closed due to lack of response. It can always be reopened when there is further information

**Comment by ciar4n** [comment]
I suspect this issue is related to 4.0 which does indeed appear to have a z-index issue when previewing modules with `?tp=1`

**Comment by brianteeman** [comment]
closed by #22272
