### ISSUE TITLE
[4.0] Toggle Menu Usability

### ISSUE THREAD

**Issue by IsarBella** [joomla/joomla-cms#22089]
### Steps to reproduce the issue
There are two possibilities to improve the isssue:
1. Shorten the toggle menu
2. The toggle menu will be shown with opacity

### Expected result
All items can be read completely

### Actual result
The toggle menu covers the submenu.

**Comment by brianteeman** [comment]
Could you please include some screenshots - i dont see any issue with the toggle but maybe i am looking in the wrong place

**Comment by coolcat-creations** [comment]
this is a huge issue but I am personally not satisfied with the behaviour at all. The fact you have ti actively close the submenu to have workspace is very annoying. Can you try to change the behaviour too?

**Comment by coolcat-creations** [comment]
Screenshot of the issue:
<img width="418" alt="grafik" src="https://user-images.githubusercontent.com/828371/45257213-beaeca00-b3a2-11e8-8044-e7d16e2f29b9.png">

**Comment by brianteeman** [comment]
Ah I see it now. It only occurs when you have the toggle set to full width. When it is set to collapsed it works perfectly

**Comment by brianteeman** [comment]
I am going to close this as we have a new menu being tested see #22587
