### ISSUE TITLE
[3.9] Frontend user registration "privacy consent" shows "optional" but is required

### ISSUE THREAD

**Issue by webgras** [joomla/joomla-cms#22082]
### Steps to reproduce the issue
in Administrator "Users" - "Options" set "User registration" to yes
Activate plugin "System - Privacy Consent"
in Frontend got to User registration form
field "Privacy Policy" shows "** * (optional)**"
leave field to "No"
click "register"

### Expected result
the field should not show "(optional)" because it is required and it also has the star

### Actual result
"Privacy Policy" shows "(optional)"

![optional](https://user-images.githubusercontent.com/10774704/45255273-5cdf6780-b384-11e8-91eb-05f639bff282.jpg)

**Comment by ghost** [comment]
is this a duplicate of #22056?

**Comment by webgras** [comment]
I only tested in 3.9 
your mentioned issue is 4.0
mine is from privacy plugin "System - Privacy Consent"
I did not check yet where it comes from.

**Comment by roland-d** [comment]
I am checking this but the captcha error is stupid. I don't even want a captcha.

**Comment by alikon** [comment]
the captcha error should be fixed with #21979

**Comment by roland-d** [comment]
PR is coming for this.

**Comment by roland-d** [comment]
Closing this as we have a PR #22092
