### ISSUE TITLE
[4.0] COM_USERS view edit > switching horizontal tablist effects incorrect active tabs if TwoFactor tab is available

### ISSUE THREAD

**Issue by HRIT-Florian** [joomla/joomla-cms#22081]
### Steps to reproduce the issue
Enable any TwoFactor Plugin
Got to com_users view edit a user
Try to toggle beetween horizontal tablist

### Expected result
Active Tab at tablist should be first one
Clicking on any other tab, it should be opend on first click!

### Actual result
Active Tab is wrong marked at tablist.
Multiple Tabs are active
Clicking on any inactive tab did not effect on first click, because incorrect events. 

![useredit](https://user-images.githubusercontent.com/12803406/45255178-7cc25b80-b383-11e8-893f-f567059d26a4.jpg)

### System information (as much as possible)
Joomla! 4.0.0-alpha5-dev Development [ Amani ] 22-July-2018 22:58 GMT

**Comment by brianteeman** [comment]
This isn't specific to TFA it is effecting all tabs - see #21981

**Comment by ghost** [comment]
closed as duplicate Report of #21981<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22081">issues.joomla.org/tracker/joomla-cms/22081</a>.</sub>
