### ISSUE TITLE
[3.9]Export of User Actions Log keeps popping up after export

### ISSUE THREAD

**Issue by BurtNL** [joomla/joomla-cms#22095]
### Steps to reproduce the issue
Go to Users > User Actions Log and click the button 'Export All as CSV' or make a selection of some log entries and click button 'Export Selected as CSV'. An export windows pops up to store the CSV or opens directly in Excel. Choose either one. The CSV will be exported or opens in Excel. All good.

![screen shot 2018-09-08 at 18 45 32](https://issues.joomla.org/uploads/1/9103a725bcfd85d50d06fa4f0b3ba1f7.jpg)

Now click another button on the page, such as 'Clear' or perform a search.
The export window pops up again.

### Expected result
After an export the other buttons should work as expected and not perform another export.

### Actual result
The export window pops up many times.

### System information (as much as possible)
Joomla 3.9.0-alpha2-dev on Windows 10/WAMP.

### Additional comments
None.

**Comment by alikon** [comment]
confirm 
ping @joomdonation

**Comment by joomdonation** [comment]
It's because when a button is clicked, the task associated with that button is stored in task hidden input. Then when users perform other action (without reloading the page), the form is submitted with that task and action logs keep being exported.

Does anyone knows a simple way to reset the value of task hidden input after the form is submitted? Or we will have to add some javascript to clear the value of that task hidden input for every buttons (search, clear...) before the form is submitted?

**Comment by alikon** [comment]
something like `JRequest::setVar('task', '');`  i guess

**Comment by joomdonation** [comment]
No, not something like that. We will need to find a way to reset the value of the task hidden input

- After the **Export All as CSV** button clicked
- Or somehow, before the form is submitted when users click on Search, Clear button (or even change a value in the dropdown filter in search tools)

**Comment by mbabker** [comment]
That is exactly why there are no checkboxes on the privacy request screen and the action buttons are inlined on each row.  The UI toolkit just does not work if you're performing an action that does not result in a reload/redirect.

**Comment by joomdonation** [comment]
Guess we can add a second form to the page and submit that form on export request and it would solve that issue. I will find sometime to work on it on tomorrow.

**Comment by ghost** [comment]
closed as having Pull Request #22155
