### ISSUE TITLE
SiteRouter decodes + symbols to spaces in URL paths

### ISSUE THREAD

**Issue by johnrix** [joomla/joomla-cms#22096]
### Steps to reproduce the issue
1. Create a component router that creates/handles URLs with segments containing + symbols (eg. an email with a user alias element such as in https://mysite.org/menuitemalias/user+alias@example.com/)
2. Attempt to open such a URL and log the content of the segments supplied to the component router

### Expected result
Given the above URL, the first segment supplied the the parse() method of the component router should be the email address as given. (To my understanding, + symbols only have special meaning within the query component of a URL, but should be treated literally within the URL path (ref discussion here: https://stackoverflow.com/questions/1005676/urls-and-plus-signs).

### Actual result
The + symbol in the URL is translated to a space character before being passed to the component router.

### System information (as much as possible)
Joomla 3.8.10, Ubuntu 14.04, Apache 2.4.29

### Additional comments
I've tracked this back to the use of urldecode() in libraries/src/Router/SiteRouter.php (line 89). Replacing this with rawurldecode() addresses the problem (though I have not done extensive testing to understand what other implications this change may have).

**Comment by ghost** [comment]
can you please update to latest Version (you are on 3.8.10) and retest? 

There are also some similar Issues + Pull Requests open - can you please look if they are about same Topic?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22096">issues.joomla.org/tracker/joomla-cms/22096</a>.</sub>

**Comment by johnrix** [comment]
Thanks Franz... had not actually realised there were updates - seems there was a DB schema fix waiting for me to push through before I was alerted to the updates. Have done that now and updated to 3.8.12. Problem is as before.

I spent a few minutes searching through the current PRs and issues but have not yet spotted the same issue there.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22096">issues.joomla.org/tracker/joomla-cms/22096</a>.</sub>

**Comment by ghost** [comment]
@johnrix thanks for Comment and make sure its a unique Issue.

**Comment by csthomas** [comment]
Take a look at https://github.com/joomla/joomla-cms/pull/19196 and https://github.com/joomla/joomla-cms/issues/19130

**Comment by johnrix** [comment]
Interesting... it does include reference to this problem alright. The PR there would not resolve this fully though as far as I can tell from perusing the changes.

**Comment by jwaisner** [comment]
@johnrix are you still experiencing this in 3.9.16 or the latest staging branch for 3.9?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22096">issues.joomla.org/tracker/joomla-cms/22096</a>.</sub>

**Comment by johnrix** [comment]
Hi @jwaisner, I haven't actively tested this, but the line of code in question has not changed in 3.9.16, so I think the answer would be yes.

**Comment by johnrix** [comment]
Was able to confirm with a test there now also that it is still behaving the same way.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39917 . Thanks in advance.

**Comment by brianteeman** [comment]
please test #44609
