### ISSUE TITLE
[4.0] [UX] Edit menu is a bit hidden and crazy user friendly

### ISSUE THREAD

**Issue by HRIT-Florian** [joomla/joomla-cms#22091]
### Actual result
 of com_menus&view=menus

![editmenu](https://user-images.githubusercontent.com/12803406/45255527-f9573900-b387-11e8-82b3-b219b8a7a05e.jpg)

### Expected result
No sure, but this is currently a bit confused.

Because of same behaver of menu view=items
-> goes to edit item

But at menu view=menus
-> it goes also to edit item ??

That's not logical, and the small edit function below the menu is too much hidden

I would suggest, that we handle it same as in J3, 
clicking on view=items item >> edit item
clicking on view=menus item >> edit menu

Whould that be an idea? So i can work on a PR ;)

#22086 can be referenced and closed because the issue is not properly described.

**Comment by brianteeman** [comment]
What is the difference to J3?

**Comment by HRIT-Florian** [comment]
@brianteeman oh okay, you are right, i did forget the same behaver. Anyway, in J3 we had a edit button.
Clicking on a menu item was also in J3 for me a bit confused, why i will jump to items. And now, in J4 the edit button was moved, but now we have a pencil and it did not edit, it did even jump to items view :/ ? This is really confused and i know no component in joomla where we have such a behaver. If I'm on a list view, i expect to go to edit view after onclick to any item and no to switch the list view ;)

correct me if I'm wrong thinking ;)

**Comment by brianteeman** [comment]
i absolutely agree with you and have always found it weird. i was just surprised with your comment about j3 being different and wanted to make sure we were talking about the same thing. i think there was a discussion about changing it in the pr that introduced the pencil which i think was by @chmst

**Comment by ghost** [comment]
closed as having Pull Request #22093
