### ISSUE TITLE
[3.9] Error page on frontend when multilingual site with page cache plugin enabled

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#22099]
### Steps to reproduce the issue

See below system information.

Navigate to any frontend page.

### Expected result

The page is shown.

### Actual result

The error page is shown with following PHP notice:

Notice: Undefined index: in /xyz/plugins/system/languagefilter/languagefilter.php on line 222
Notice: Trying to get property 'sef' of non-object in /xyz/plugins/system/languagefilter/languagefilter.php on line 222

### System information (as much as possible)

- Multilingual site updated from 3.8.12 to Joomla! 3.9.0-alpha2-dev nightly build of today, Sunday September 9, 2018.
- "System - Page Cache" plugin enabled.
- Standard site template Protostar.
- PHP 7.2.8
- MySQL 5.5.60

### Additional comments

The backend works normally.

When the "System - Page Cache" plugin is disabled, the frontend works well, i.e. no issue.

The value of the "Use Browser Caching" setting of the "System - Page Cache" plugin or the cache settings in global configuration (off or conservative or progressive) do not have any influence on the issue.

Having the "System - Language Code" plugin with language codes defined enabled or not also does not have any influence on the issue.

With another copy of the same Joomla 3.8.12 updated to the Joomla! 3.9 Alpha build the issue has not happened.

That means the issue came up with one of the changes in the 3.9-dev branch since Joomla! 3.9 Alpha was released.

@mbabker Maybe related to PR #21012 ?

Reverting other PRs #21011 and #21695 did not help, so I don't think the issue is caused by those.

I have not tested if that also happens with a new install of 3.9.0-alpha2-dev nightly build of today.

**Comment by richard67** [comment]
@infograf768 Can you replicate this issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22099">issues.joomla.org/tracker/joomla-cms/22099</a>.</sub>

**Comment by Sandra97** [comment]
After updating 2 multilingual sites to 3.9.0-alpha2-dev, I have an error on both `0 - Call to a member function get() on null` with the plugin enabled (I've stopped using this plugin on all my multilingual sites, see #20594)

**Comment by Sandra97** [comment]
I can also replicate this issue on a fresh install with the plugin enabled

**Comment by infograf768** [comment]
I usually never enable the system cache plugin on a multilingual site, thus why I guess I had not seen this in the last 3 days.

I confirm the issue when the system page cache plugin is enabled.
```
[09-Sep-2018 16:56:30 Europe/Berlin] PHP Notice:  Undefined variable: user in ~/plugins/system/cache/cache.php on line 118
[09-Sep-2018 16:56:30 Europe/Berlin] PHP Notice:  Undefined index:  in ~/plugins/system/languagefilter/languagefilter.php on line 222
[09-Sep-2018 16:56:30 Europe/Berlin] PHP Notice:  Trying to get property of non-object in ~/plugins/system/languagefilter/languagefilter.php on line 222
[09-Sep-2018 16:56:30 Europe/Berlin] PHP Notice:  Undefined index:  in ~/plugins/system/languagefilter/languagefilter.php on line 222
[09-Sep-2018 16:56:30 Europe/Berlin] PHP Notice:  Trying to get property of non-object in ~/plugins/system/languagefilter/languagefilter.php on line 222
```

reverting https://github.com/joomla/joomla-cms/pull/21012 solves the issue.

Setting this issue as release blocker.

@mbabker

**Comment by infograf768** [comment]
WE have 2 errors in the plugin

1. Missing `$user    = JFactory::getUser();
2. Using $app instead of $this->app

Making PR now

**Comment by infograf768** [comment]
Closing as we have patch . Please test https://github.com/joomla/joomla-cms/pull/22101
