### ISSUE TITLE
[3.9]Link to frontend opens in backend

### ISSUE THREAD

**Issue by BurtNL** [joomla/joomla-cms#22094]
### Steps to reproduce the issue
Go in backend to Users > Privacy (Dashboard).
This panel is show on the right, see the link 'Request Form Menu Item Published'.
It seems to be a link to the frontend, but opens in the backend.

![screen shot 2018-09-08 at 18 27 14](https://issues.joomla.org/uploads/1/80018c887a793f19f17a5527f0940eac.jpg)

### Expected result
Should open in frontend in new tab.

### Actual result
Opens in backend, replacing the backend interface.

### System information (as much as possible)
Joomla 3.9.0-alpha2-dev.

### Additional comments
None.

**Comment by mbabker** [comment]
There isn't a `target="_blank"` on the link and IMO there shouldn't be.

**Comment by roland-d** [comment]
There shouldn't be a `target="_blank" but is the observation correct that it should open the front-end instead of the back-end?

**Comment by mbabker** [comment]
Yes.  It is a link to the frontend request form (note here it is under the check of whether the frontend menu item is published, and the current frontend link is displayed regardless of a menu item being published so that the link can always be easily referenced).

**Comment by roland-d** [comment]
@BurtNL Do I understand you correctly that this link opens the back-end of Joomla instead of the front-end?

**Comment by BurtNL** [comment]
@roland-d To be more precise: that link opens the frontend, but in the same browser tab as the backend, thus replacing the backend. I agree with Michael that it is just a check to see if a specific form (Privacy -> Create Request) has been published, although I would expect a link to a frontend item will open in a new browser tab and doesn't replace the backend.

**Comment by roland-d** [comment]
@BurtNL Ah I see your point. In that case we can close this issue because all links in Joomla do not have a target set. It is up to the user to decide where it wants the link to open. So if you want a new tab, you can use the CTRL-click for example.

**Comment by mbabker** [comment]
I'm sure @brianteeman has the reference more handy than me but there are accessibility concerns with arbitrarily opening links in new browser tabs or windows as well, which is part of the reason we don't add the target attribute to links.

**Comment by BurtNL** [comment]
@roland-d Okay, that's fine with me.
