### ISSUE TITLE
[4.0] Jumping main menu in administration

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#22108]
Hi,
see:
https://github.com/joomla/joomla-cms/issues/22103 (1)

Menu in administration is "jumping/flickering" when hovering with mouse over it - in case some large submenu is present (tested with latest Google Chrome 69)

![1](https://i.imgur.com/og1wECY.gif)

### Steps to reproduce the issue
Work in Joomla! 4 administration

### Expected result
No jumping/flickering

### Actual result
Jumping/flickering

### System information
- Joomla! 4.0.0-alpha5-dev (latest version, installed per composer/npm)
- PHP 7
- MariaDB 10
- **Google Chrome 69**

Jan

**Comment by brianteeman** [comment]
I am going to close this as we have a new menu being tested see #22587

**Comment by PhocaCz** [comment]
Ok
