### ISSUE TITLE
[4.0] Some Joomla! 4 UI/UX issues

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#22103]
Hi,
when I work with Joomla! 4 administration, I found some specific issues (especially when compared to Joomla! 3) that make my work with Joomla! administration harder. Of course, these are very subjective feelings, but they may be of interest to someone, for example in the form of Joomla! 4 UI/UX feedback.

### Steps to reproduce the issue
Work in Joomla! 4 administration

### System information
- Joomla! 4.0.0-alpha5-dev (latest version, installed per composer/npm)
- PHP 7
- MariaDB 10
- Google Chrome 69

## 1) Jumping main administration menu, see gif:

![1](https://i.imgur.com/og1wECY.gif)

## 2) Submenu is not closed automatically:

See: https://github.com/joomla/joomla-cms/issues/22089

## 3) Quick Icons - there is quick icon to go to modules but not to go to plugins (both have the same importance)

![3](https://i.imgur.com/cuYg6T2.png)

## 5) It is not logical to have a "Save and Close" button in submenu

See: https://github.com/joomla/joomla-cms/issues/14326

## 6) Two different menus are in conflict (solution can be pretty easy - follow the Joomla! 3 and move main menu back to top and left menu to left)
![6](https://i.imgur.com/Zr0AOhw.png)

## 7) Buttons are too wide, even for widescreen monitors

See: https://github.com/joomla/joomla-cms/issues/22004

## 8) Confusing split of Install and Manage Extensions functions

![8](https://i.imgur.com/e09XY0O.png)

**Comment by wilsonge** [comment]
First of all - this is all good feedback thankyou. There are some "won't fixes" here thought

## Answer to 3/4
We've made a conscious decision to not treat modules and plugins the same way. Modules are often created multiple times (advertising sales etc etc) whereas plugins are traditionally more one off configurations. As a result we've made a conscious decision to only have a module link and the plugin link is on the system menu

## Answer to 6
It's still a WIP with the new menu - but we plan to remove the submenu - have the single menu for everything.

I'm willing to hear opinions on 8 - but they are completely separate functionality

Also can we open a specific issue for the first issue you mentioned (the menu jumping) which is clearly just an out and out bug that requires fixing. Thanks :)

**Comment by ghost** [comment]
@PhocaCz can you please open a new Issue for Issue 1?

**Comment by PhocaCz** [comment]
Hi,

(1) 
See: https://github.com/joomla/joomla-cms/issues/22108

(3),(4),(5),(8)
My workflow in Joomla! 4 is slower and more confusing in comparison to Joomla! 3. :-(

(6)

> It's still a WIP with the new menu - but we plan to remove the submenu - have the single menu for everything.

If you see the first GIF here, you will see that menu with some large list of items can make the menu UX worse, (even when ignoring the jumping/flickering problem). Mostly global configuration or component options are too long that adding them to one signle menu as a submenu will be a work for magician :-(

![6](https://i.imgur.com/f3CmDJ8.png)

(8)
> I'm willing to hear opinions on 8 - but they are completely separate functionality

If you click **Install - Extensions** or **Manage - Extensions** - you will be always redirected to one component (com_installer) with the same submenu but both groups are located in different parts (it is a matter of taste but can be confusing for users after upgrading and coming from Joomla! 3 where both are in the same menu group.

**Comment by simbus82** [comment]
Hi @PhocaCz, about point **5**

I'm working in an agency with developers and copywriters, marketers and SEOs, etc.
"Save & Close" is far less clicked than "Save".
"Save & Close" is used only when an article is ready. (Clicking "Save" often is real lifesaver)
So, IMHO, this UX/UI is good.

About point 8, you are right, it is a mess... but it's a WIP (i hope).

**Comment by PhocaCz** [comment]
Hi @simbus82 
did you read the post: #14326, it is not about what is better, if **Save** or **Save & Close**, it is about logic of the **Save & Close** button. Not about comparison of **Save** and **Save & Close** or its statistics.

**Save & Close Button is here to save you one click. With one click you do two operations: 1) Save and 2) Close**. Hiding it into the submenu means one click more (to open the submenu).

With adding the **Save & Close** button to submenu, it loses its essence. Its essence is to save you one click which is not more possible in submenu (one click to open submenu, second to click on **Save & Close** button).

And when something breaks logic, it is not UX friendly.

It is the same like you will create a shortcut on your PC desktop to some program and then you will move this shortcut out of the desktop (e.g. to some folder). Then this shortcut loses its essence.

Jan

**Comment by mbabker** [comment]
Save & Close is more than just "saving one click" and IMO it really doesn't help the argument for where it's placed on the toolbar by saying "this should be a one click action" versus "this should be a two click action".  The user is still saving a measurable amount of time using the Save & Close action versus manually saving then manually cancelling/closing (properly, which includes releasing the checkout lock), even if the action requires two clicks versus one.

To manually save and close means clicking save, waiting for two HTTP requests, clicking close, and waiting for two additional HTTP requests.  The save and close action means click the action and waiting for two HTTP requests.  Even if it is two clicks, can you say with certainty that adding the second click is going to negate the two to three seconds it would most likely take for the two HTTP requests that get skipped to be processed?

**Comment by simbus82** [comment]
For me "Save & Close" can be hidden without any fear. (In articles!)

One click on "Save" after filling the article (you must double check content, alaways!), and if you don't do any other edits... one click on "Close", it is out of any submenu and with a great visibility. This is UX.

You have to analyze the full workflow of content creation, not only the mechanical UI based on logic or programming.
This is too much "a developer vision": then we forget that the CMS must be used by copywriters, marketers, "newbies", etc. Never used HotJar inside Joomla Admin? Give it a try!

**Comment by PhocaCz** [comment]
@mbabker 

So in other words (very simplified):

- Saving one click + Saving one HTTP request = 100% of what we can save
- Skipping of saving one click + Saving one HTTP request = e.g 80% of what we can save (the ratio between both can be different, let's say it is 80% for HTTP request and 20% for one click - just an example)

So we will give up on 20% due to the UI, even in case, in edit view there are not so much buttons like in list view? (there is much more place in comparison to list view)

**Comment by PhocaCz** [comment]
@simbus82 
> You have to analyze the full workflow of content creation, not only the mechanical UI based on logic or programming.

The post #14326 is not based on my ideas but on community discussion.

**Comment by mbabker** [comment]
If your viewpoint is that every action should be one click accessible, then yes, "we will give up on 20%".  In my perspective, not every action needs to be one click accessible, and there are still gains to be had in using the shortcut action versus performing each action individually, even if it comes at the expense of "one more click".  Likewise, in my limited use of Joomla these days I find that I am primarily going for the save action, reviewing things post save, then closing the item without using the save and close action, so making the save and close action the primary action of the group would be an impediment to my workflow (and undoubtedly others who are reviewing things even after a save just to be safe).  Having two buttons, one of them being save with a dropdown to access the close action, and one being the save and close action, makes no sense here which means the only viable options are either the present single button with dropdown or keeping every action as separate buttons.

**Comment by PhocaCz** [comment]
> If your viewpoint is that every action should be one click accessible

No, it isn't, as written many times here in the discussions:
1) not based on my viewpoint
2) focused only on logic of the "Save & Close" button

> which means the only viable options are either the present single button with dropdown or keeping every action as separate buttons.

Yes, I understand and agree.

**Comment by mbabker** [comment]
If you keep the current dropdown solution, if you make "Save and Close" the primary action this assumes that for most users their workflow is to enter an item, make changes, save, and exit immediately to the management list.  If you go back to having every action as a separate button, it's (arguably) screen clutter.

If only there were some tried and true process where folks could gather data about how individuals use the software, or maybe some way to test potential changes with a target group versus proposing changes because "I like it this way better" that the project would be willing to invest in...

**Comment by PhocaCz** [comment]
> If you keep the current dropdown solution, if you make "Save and Close" the primary action

No, this is not the purpose of this topic or #14326 in any way. 

The purpose of this topic or #14326 is to say, that Joomla! 4 Save & Button lost some part of functionality in comparison to Joomla! 3.x.

I don't say that the argument: "Ok, we can live with it because of new dropdown function which is much more important" is wrong but maybe someone can have better idea how to solve it. It is still only feedback (maybe too much discussed but most of the discussion is about explaining what exactly is meant)

**Comment by alikon** [comment]
>  bunch of different people who have a bunch of different **workflows**.

then the new workflows to the rescue :rofl:

**Comment by PhocaCz** [comment]
> What makes "Save and Close" so special in relation to other tasks, such as "Save as Copy" or "Save and New", that mean it should be given precedence over other tasks?

Save & Close is completely different button. It is a final button, confirming the end of your edit. Even you didn't do any change, you mostly click Save & Close button to be 100% sure, nothing will be lost. Mostly the last and very important button.

> Does it really make sense to have multiple save buttons on the toolbar, to allow "special" tasks to have one less click to reach them, or is it appropriate to group all save actions as is the case now?

Hard to explain, something like ten finger writer can never explain to not ten finger writing users why is ten finger writing so important. Workflow is 10x faster and the speed is not about fast cooperation of fingers but about your eyes too, which can read the source text without losing time by looking at the keyboard. So yes it makes sense.

> Basically, aside from having to retrain your muscle memory, are you really losing time/effort/focus/etc. on clicking twice to reach Save and Close in 4.0 in comparison to only one click in 3.x and earlier

Yes, otherwise #14326 and the base discussion would never occur.

**Comment by mbabker** [comment]
That response still IMO focuses very heavily on the single task without additional context and the number of clicks to execute it without additional context.

TBH without proper UX related data backing things up, this "what items should be separate toolbar buttons and inherently how many clicks does it take to complete an action" discussion is going to go nowhere because it is going to be entirely opinion driven, and opinion driven development is not a strong development model to be basing long term decisions off of.

**Comment by PhocaCz** [comment]
Ok

**Comment by coolcat-creations** [comment]
I agree to @PhocaCz and it was the design concept to have a Save Button and Save & Close with dropdown actions. It was dicussed with @wilsonge and and many others at JAB and should be done like that. See https://github.com/joomla/joomla-cms/issues/21989

**Comment by PhocaCz** [comment]
Hi @coolcat-creations
#21989 looks really great, is there anything I can do to support this proposal (e.g. testing, etc.)?

**Comment by coolcat-creations** [comment]
@PhocaCz As far as I understood there is no one to to the template development so if you can grab the issue and make a PR?

**Comment by mbabker** [comment]
I still strongly object to just randomly making workflow decisions based on what people think looks good or a click count.  Either we need to do some real UX related testing and gather some real data or we need to just flat out stop making UI/UX changes on a whim because somebody thinks something looks good.

Oh who the hell am I kidding.  Joomla's never been able to sustain a UX team anyway.  On a whim design seems to be how things are going to be done around here, and it's actually really frustrating.

**Comment by mbabker** [comment]
Deleted my comments from this thread (apologies for now having broken it).  I feel like my opinions on UI/UX related matters are going too far against the grain from what people want, so there's no point in continuing to debate it and therefore my feedback is unnecessary.

**Comment by PhocaCz** [comment]
@mbabker 
I don't have any problems with your comments, unfortunately I don't know the background so I cannot understand your comments fully.

Unfortunately no ideas about UI/UX team in Joomla! so you need to know that some comments are based on not sufficient information (for example, there is an assumption that there is some UI/UX team which will make the final decision about UI/UX changes based on Github proposals and comments) :bulb:

**Comment by mbabker** [comment]
There is no UX team, hence my repeated backhanded comments about a lack of UX related testing or data or that Joomla's UX is based on someone deciding "this looks good".

**Comment by PhocaCz** [comment]
Ok, but "this looks good" doesn't mean, it will be 100% agreed and merged. It is just one of many possible comments. When I say, this completely solves what I have asked, still doesn't mean it is the right way. And unfortunately when there is no UI/UX team, we cannot freeze all possible UI/UX changes, there must be found another way how to decide about UI/UX proposals. :bulb:

**Comment by PhocaCz** [comment]
Closing for now:
1,2,5,7 have own issue topics
3,4,8 can be discussed/newly opened when Joomla! 4 will be stable (when more users will use it)
6 it is in progress

**Comment by jwaisner** [comment]
This discussion has ran its course. the J4 administration UI/UX has been overhauled. Please check the latest build and provide feedback.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22103">issues.joomla.org/tracker/joomla-cms/22103</a>.</sub>
