### ISSUE TITLE
[4.0] An error has occurred. 0 Class 'DebugBar\DebugBar' not found

### ISSUE THREAD

**Issue by stankurd** [joomla/joomla-cms#22116]
### Steps to reproduce the issue
Just update Joomla 4
An error has occurred.
0 Class 'DebugBar\DebugBar' not found

**Comment by mbabker** [comment]
If you're running from the git repo then you should generally be running `composer install` and `npm install` after each `git pull`.

The PR merging the debug bar package is not yet in a nightly build.

**Comment by stankurd** [comment]
OK Fixed

**Comment by ghost** [comment]
reclosed as Issue was marked "open".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22116">issues.joomla.org/tracker/joomla-cms/22116</a>.</sub>

**Comment by infograf768** [comment]
I have the same error after using npm install
Log in Terminal is
Error: ENOENT: no such file or directory, lstat '/Applications/MAMP/htdocs/installmulti/joomla40/libraries/vendor/maximebf/debugbar/src/DebugBar/Resources'

**Comment by ghost** [comment]
Issue reopened.

**Comment by infograf768** [comment]
hmm closing again. Looks like it is necessary to also run `composer install` before `npm install` here.
My eclipse repo does not contain that file after update. 

@mbabker why is that file not present in our github 4.0-dev branch?
