### ISSUE TITLE
Article Manual order is lost when modified by Batch

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#22110]
Hello

Manually sorting posts in a category and editing them through batch processing (for example, changing access levels) will result in losing the manual order.

best regards
Hitsch

### Steps to reproduce the issue
Order some articles manually.
Change the Access Level (or Language...).

### Expected result
Same order as before.

### Actual result
The order has changed.

**Comment by ghost** [comment]
Issue confirmed (test by changing access level).
### System information
- 3.9.0-beta2-dev
- Template: Protostar
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by Quy** [comment]
@franz-wohlkoenig Can you reproduce with the latest version?

**Comment by ghost** [comment]
@Quy no testing anymore.

**Comment by Quy** [comment]
Closing as not reproducible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22110">issues.joomla.org/tracker/joomla-cms/22110</a>.</sub>
