### ISSUE TITLE
[4.0] Notifications drop UNDER menu bar

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#22118]
### Steps to reproduce the issue
Open plugins manager
click on "notifications"
If there are any the notifications will drop UNDER the menu bar.

### Expected result

pop over content

### Actual result

pops under

### System information (as much as possible)

[systeminfo-2018-09-10T18_02_41+00_00.json.txt](https://github.com/joomla/joomla-cms/files/2367877/systeminfo-2018-09-10T18_02_41%2B00_00.json.txt)

### Additional comments
![image](https://user-images.githubusercontent.com/1850089/45315317-b1582380-b4f9-11e8-9910-cd3d49701703.png)

**Comment by N6REJ** [comment]
pr in a few minutes...

**Comment by mbabker** [comment]
There's a long standing z-index issue between that, modals, and something else.  So if you manage to work that out then a lot of people will appreciate it.

**Comment by N6REJ** [comment]
@mbabker 
`.header .dropdown-notifications {
    min-width: 280px;
    padding: 0;
    border: 0;
    z-index: 1041;
}`
look ok?

**Comment by ghost** [comment]
~~Issue isn't shown in issue Tracker.~~

**Comment by brianteeman** [comment]
Submit the pr and then it can be tested

**Comment by N6REJ** [comment]
I will, I've been having problems on my end.. sorry for a delay on such a tiny thing.  My LAMP STACK(s) are not liking npm install

**Comment by ghost** [comment]
closed as having Pull Request #22186
