### ISSUE TITLE
[4.0] Wrong bootstrap size in mod_statistics_admin

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#22124]
### Steps to reproduce the issue
Add a new statistc admin module in cpanel. 

### Expected result
Width col-md-6 as other modules

### Actual result
Width col-md-12 

### System information (as much as possible)
v4.0 dev

### Additional comments
With sample data the with is correct.

**Comment by SharkyKZ** [comment]
That is correct behavior, IMO. `col-md-12` is the default. Sample data just comes with `col-md-6` explicitly set.

**Comment by chmst** [comment]
I see that other modules have the same behaviour, so you are right. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22124">issues.joomla.org/tracker/joomla-cms/22124</a>.</sub>

**Comment by ghost** [comment]
@chmst Thanks for Report. As the Issue is expected Behaviour closed it.
