### ISSUE TITLE
[4.0] Edit Menu - select single article with js error

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#22129]
### Steps to reproduce the issue
Open an Menu Item which goes to a single article. Click the Edit Button. 

### Expected result
A Modal with Articles.

### Actual result
Nothing happens. 

![screen shot 2018-09-11 at 12 14 43](https://issues.joomla.org/uploads/1/d362d4bd2dd79ec4e21e0649c6bdd2f5.png)

### System information (as much as possible)
latest dev 4.0, composer and npm performed just before the test.

**Comment by brianteeman** [comment]
Fairly certain this has already been reported
