### ISSUE TITLE
[4.0] plg_system_debug Fatal error: Uncaught TypeError: Argument 1 passed to Symfony

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#22122]
### Steps to reproduce the issue
- Install nightly build Joomla_4.0.0-alpha5-dev-Development-Full_Package.zip 10 September 2018 02:
- Error reporting: Development  (Global configuration)
- Go into Plugins > "System - Debug"
- Check first that plugin is enabled

- **De**activate everything but:
"Refresh Assets" : YES (See issue https://github.com/joomla/joomla-cms/issues/22121 why important).
"Log Priorities" : ALL
"Profiling" : SHOW
"Log Executed Queries" : YES

- In another tab - Activate debug (Global configuration)

- Save plugin.

### Expected result
- All fine and debug tabs below page

### Actual result
White page with error:
```
Fatal error: 

Uncaught TypeError:
Argument 1 passed to Symfony\Component\Debug\ExceptionHandler::handle() must be an instance of Exception, instance of Error given in /libraries/vendor/symfony/debug/ExceptionHandler.php:106

Stack trace:
#0 [internal function]: Symfony\Component\Debug\ExceptionHandler->handle(Object(Error))
#1 {main}
  thrown in /libraries/vendor/symfony/debug/ExceptionHandler.php on line <b>106</b>
```

### Additional comments
Only if both settings "Log Priorities" AND "Log Executed Queries" are enabled the error is thrown.

### System information (as much as possible)
See System information in https://github.com/joomla/joomla-cms/issues/22121#issue-358851386

**Comment by ReLater** [comment]
Related ? https://github.com/joomla/joomla-cms/issues/21645

**Comment by ghost** [comment]
Comment above by @ReLater isn't shown in issue Tracker.

**Comment by chmst** [comment]
I can confirm this issue. Had it when I added accidetially a wrong database (from 3.8) in the configuration.php.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22122">issues.joomla.org/tracker/joomla-cms/22122</a>.</sub>

**Comment by ReLater** [comment]
Solved atm by https://github.com/joomla/joomla-cms/pull/20380
