### ISSUE TITLE
[RFC] Help Server options in the backend: Removal of help.joomla.fr

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-cms#22127]
When using the backend in French, a user has the option to display the help screens from an unofficial property, help.joomla.fr, instead of help.joomla.org.

It used to make totally sense as, at that time, the official documentation was available in English only.

Since then, a multilingual system has been implemented on docs.joomla.org.
Furthermore, it seems that help.joomla.fr is not updated anymore, displaying help screens for versions between 3.1.1 and 3.2.0, and so many help screens don’t even exist. 

Without mentioning that docs.joomla.org is an open property where anyone can contribute, which is not the case of help.joomla.fr

Of course, all JDocs help screens are not yet translated into French, and there’s still lot of work to do, but having JDocs as the only source for help screens could allow the community to translate one and only source. 

A last thing, as JDocs help screens are automatically displayed in the language set up for your backend, this option becomes even more obsolete.

**Comment by brianteeman** [comment]
If it is not up to date then it should be removed. 

If french is the only language that ever provided a help server then the entire option should be removed

**Comment by alikon** [comment]
![screenshot from 2018-09-11 20-16-30](https://user-images.githubusercontent.com/181681/45379171-a2f42f80-b5ff-11e8-889b-ecb084ae33c9.png)


it's temporary or it has been decided already to switch on docs.joomla.org ?

**Comment by mbabker** [comment]
The public facing `help.joomla.org` domain has been that way for quite some time (because the public facing version of the site was in essence 1.0 and early 1.5 documentation, the site was abandoned).

The help screen proxy (served via `help.joomla.org/proxy` is not going anywhere anytime soon (and is really just a wrapper around `docs.joomla.org` to read items out of the Mediawiki API and do some formatting to display those in the iframed context the screens are rendered in).

**Comment by mbabker** [comment]
(Long and short `help.joomla.org` these days is an internal domain, not something we're directing the public to (directly), if someone wants to create content for that subdomain though to replace the notice https://github.com/joomla/help.joomla.org is where to send pull requests)

**Comment by alikon** [comment]
thanks for the explanation
so the silly #22133  simply remove the `.fr`

**Comment by ghost** [comment]
closed as having Pull Request #22133

**Comment by infograf768** [comment]
See my comment here
https://github.com/joomla/joomla-cms/pull/22133#issuecomment-420514970
