### ISSUE TITLE
[4.0] Nightly build. New installation. JS/Ajax error SyntaxError: JSON.parse: unexpected character

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#22135]
### Steps to reproduce the issue
- Install Joomla_4.0.0-alpha5-dev-Development-Full_Package.zip, 11 September 2018 02:00:22 UTC
- Installation hangs after entering credentials for database and starting installation afterwards.

### Expected result
- Successful installation

### Actual result
- Endless running spinner and errors in console:

## Firefox 62.0 (64-Bit)/Win 10
```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data: template.js:189:16
onSuccess
/installation/template/js/template.js:189:16
e.request/o.onreadystatechange
/media/system/js/core.min.js:1:8183
```
## Vivaldi 1.15.1147.64 (Stable channel) (32-Bit)//Win10 
```
index.php:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at onSuccess (template.js?1f470a31858053af25563fb8b1b5b13e:189)
    at XMLHttpRequest.o.onreadystatechange (core.min.js?1f470a31858053af25563fb8b1b5b13e:1)
```
### System information (as much as possible)
See "System information" at https://github.com/joomla/joomla-cms/issues/22121#issue-358851386 (System information)

**Comment by mbabker** [comment]
Inspect the network tab and find the bad HTTP response please?  If you're getting that error that's suggesting an HTML response is being returned when JSON is expected.

**Comment by ReLater** [comment]
It's a HTML warning:

![11-09-_2018_22-51-28](https://user-images.githubusercontent.com/20780646/45387253-cf1aab00-b615-11e8-809c-2cbc316d5a2b.jpg)

by AJAX request `/installation/index.php?task=installation.config&format=json`

Task `config` in https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/template/js/template.js#L185

**Comment by ReLater** [comment]
Reason: https://github.com/joomla/joomla-cms/pull/21790/
@laoneo

**Comment by ReLater** [comment]
Fixed with https://github.com/joomla/joomla-cms/commit/024d943c104f6a489403d42fcdf12590960a6673
