### ISSUE TITLE
(4.0) update not working

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#22134]
### Steps to reproduce the issue
Install Joomla 3.8.12
Set channel to Custom https://update.joomla.org/core/nightlies/next_major_list.xml
Save&Close
Update

### Expected result
3.8.12 updates to 4.0

### Actual result
Fail

### System information (as much as possible)
Wamp localhost
PHP Built On 	Windows NT MY-COMPUTER 10.0 build 17134 (Windows 10) AMD64
Database Type 	mysql
Database Version 	5.7.19
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.1.9
Web Server 	Apache/2.4.27 (Win64) PHP/7.1.9
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.8.8 Stable [ Amani ] 22-May-2018 14:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.

### Additional comments
According to https://developer.joomla.org/nightly-builds.html

To always use the latest version **and test the update component** you can use this custom update server: https://update.joomla.org/core/nightlies/next_major_list.xml

**Comment by mbabker** [comment]
Not surprising given current development state.

https://github.com/joomla/joomla-cms/issues/16458 is the meta task related to ensuring upgrades to 4.0 actually work.  Closing in favor of.
