### ISSUE TITLE
[3.9] Action Log Plugin – Deactivate automated notifications via email

### ISSUE THREAD

**Issue by blueforce** [joomla/joomla-cms#22130]
### Is your feature request related to a problem? Please describe.
If the actionlog Plugin is activated, the Backend Userlogs store all user actions in the DB and send me an email. 
So I have 2 Notifications. First in the DB visible in the Dashboard-Module «Last Actions» and second in my mailbox. If an admin is in the backend and do something I receive dozens of emails per hour.

### Describe the solution you'd like
I like to set up in the settings of the plugin two options:
- Logs only in DB, visible in the dashboard
- Logs in DB and Email

### Additional context
Tested in J! 3.9 Beta, from actual release today

**Comment by SharkyKZ** [comment]
Email notification option can be disabled in user profile.

**Comment by blueforce** [comment]
That's not logical, but it's okay.
Thank you

**Comment by mbabker** [comment]
If you're the only admin on a site it might not make much sense, but it allows per-user customization of the notifications they receive (so it benefits multi-admin sites more).  IMO it wouldn't make much sense to have the plugin disable the ability for any user to receive email notifications.
