### ISSUE TITLE
[3.9] email domain options logic fail?

### ISSUE THREAD

**Issue by onderzoekspraktijk** [joomla/joomla-cms#22148]
### Steps to reproduce the issue
In 3.9.0 beta, set two email domains rules:
- first disallow all domains: by setting Domain Name: * and Rule: Disallow;
- next set new rule below the first, and allow one domain: by setting Doain Name to *domain.ext and Rule: Allow.

### Expected result
This should not allow new registration using any email address other then name@domain.ext; but should accept any registrations using name@domain.ext.

### Actual result

Every email address is blocked and triggers the error message als emailaddresses using domain.ext: "The email domain domain.ext is not allowed. Please enter another email address."

### System information (as much as possible)
joomla 3.9.0-beta Beta [Amani] 11-September-2018 12.15 GMT
PHP: 7.1.21;
Webserver: Litespeed;
mysql, 10.2.17-MariaDB

### Additional comments

Would be lovely if this works; using it for organisation websites where only persons registering with the company-domain email can register.

**Comment by alikon** [comment]
maybe is not necessary to declare

> first disallow all domains: by setting Domain Name: * and Rule: Disallow;

but only

![screenshot from 2018-09-12 21-21-44](https://user-images.githubusercontent.com/181681/45448142-ea4af080-b6d1-11e8-9082-baa237b8e523.png)


from a quick test

**Comment by Quy** [comment]
See https://github.com/joomla/joomla-cms/pull/20383#issuecomment-402469828
Remove `*` from `*domain.ext`

**Comment by Quy** [comment]
Closing per my previous comment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22148">issues.joomla.org/tracker/joomla-cms/22148</a>.</sub>
