### ISSUE TITLE
[4.0] component sql

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#22142]
While preparing #22141 I see that some components have an sql folder for install and uninstall

I have no idea if these are 
1. needed
2. up to date

But more importantly some of them only have mysql scripts and no postgres

**Comment by alikon** [comment]
for "protected" components they shouldn't be necessary  (cause you cannot uninstall them)
for "unistallable"  maybe they are needed .....

**Comment by mbabker** [comment]
> for "unistallable" maybe they are needed .....

Nothing in core is safely uninstallable.

**Comment by mbabker** [comment]
> I have no idea if these are
> 
> 1. needed
> 2. up to date

If we actually treated the core extensions as extensions, then yes they would be needed.  But as we don't treat the core extensions as extensions, there are a lot of liberties we can take with them, especially in the manifests and whether extension level SQL is maintained.

Personally, I would suggest if it is an extension it is treated as an extension (accurate manifest, local SQL files, etc.) but as we don't manage core extensions as extensions and we definitely don't have the resources to maintain things I'd almost say just strip the core manifests to the minimum needed to not break the extension manager's display and be done with it.

**Comment by brianteeman** [comment]
i have already updated the manifests to match the current file status and it has been merged now
