### ISSUE TITLE
Menu Edit: Values of right column are reset after dismiss of the typeselect modal

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#22150]
### Steps to reproduce the issue
In backend menus, click "new" and get the edit screen for a menu item.

Enter a name, set different values in the right column, 
i.e. set state to trashed, enter a note, select an eccess-level.

Then activate the "select menu type" button, choose a Menutype and close the modal.

### Expected result
The input made in the right panel is as before.

### Actual result
Most inputfields in the right panel are reset to the default values of the respective FormFields

### Additional comments
3.8.12, but maybe this exists since a longer time. 
I got it first some weeks ago, with 3.8.11.

**Comment by ReLater** [comment]
Confirmed. Made settings on right side are reset after page reload when I close the modal. And inherit the searchtool filters of menus list view or the default values.

**Comment by webmasterab** [comment]
I also reported this isseu and it was closed because it was there.
I now also see that it has been in for more than a year.
Is there no solution?

I can therefore confirm
https://github.com/joomla/joomla-cms/issues/27034

**Comment by laoneo** [comment]
Please test #37478 which should fix the behavior.
