### ISSUE TITLE
Batch process the selected menu items: Without  Process button

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#22154]
### Steps to reproduce the issue
1) Create new administrator menu.
2) Create new item for this new menu
![a](https://user-images.githubusercontent.com/9007607/45460039-97862e80-b6fb-11e8-8184-b8f58cb39ab2.JPG)

3) Select this item and click in Batch button.

_To Move or Copy your selection please select a Menu or parent item._

4) Select Move or Copy
¿Where is the process button?
![b](https://user-images.githubusercontent.com/9007607/45460057-b97fb100-b6fb-11e8-9505-cb42b14f1978.JPG)

![c](https://user-images.githubusercontent.com/9007607/45460108-dfa55100-b6fb-11e8-8cdc-89d770af54ba.JPG)

### Expected result
That the button to process is visible 

### Actual result
There is no button to process

### System information (as much as possible)
Joomla 3.9.12

**Comment by ghost** [comment]
Issue confirmed.

@Open2logic can you please test if this happens in 3.8 too?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22154">issues.joomla.org/tracker/joomla-cms/22154</a>.</sub>

**Comment by richard67** [comment]
@franz-wohlkoenig I think he meant 3.8.12 because there is no 3.9.12 (yet).

**Comment by Open2logic** [comment]
Sorry.

3.8.12<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22154">issues.joomla.org/tracker/joomla-cms/22154</a>.</sub>

**Comment by ghost** [comment]
ah, i thought 3.9 is meant.

**Comment by infograf768** [comment]
@izharaazmi 
can you have a look?

**Comment by izharaazmi** [comment]
I'll have a look soon.

**Comment by infograf768** [comment]
the code is
```
<?php if ((strlen($menuType) && $menuType != '*' && $clientId == 0) || ($published > 0 && $clientId == 1)): ?>
	<button class="btn btn-success" type="submit" onclick="Joomla.submitbutton('item.batch');">
		<?php echo JText::_('JGLOBAL_BATCH_PROCESS'); ?>
	</button>
<?php endif; ?>
```

As one can see, when `clientId == 1` (admin menu) then we need the state to be `Published > 0`.

The issue is solved when Search Tools Status is set to Published.

<img width="845" alt="screen shot 2018-09-13 at 18 15 35" src="https://user-images.githubusercontent.com/869724/45501361-3d2fb100-b781-11e8-8d79-fed5ee579814.png">
<img width="1002" alt="screen shot 2018-09-13 at 18 16 25" src="https://user-images.githubusercontent.com/869724/45501369-428cfb80-b781-11e8-8767-dfa4c89971ad.png">

No idea why this was implemented this way.

~EDIT: No idea either why we have `strlen($menuType)`~

**Comment by infograf768** [comment]
The issue comes from https://github.com/joomla/joomla-cms/pull/18195

**Comment by infograf768** [comment]
see also
https://github.com/joomla/joomla-cms/pull/19879 (for 4.0)

**Comment by izharaazmi** [comment]
I just checked it and I see #19879 does fix this right. However I am not sure why we can't process trashed items, any idea?

**Comment by infograf768** [comment]
We could, but is it a good idea? I think not. Most of the time (99%), if some stuff is in Trash and remained in trash, it was because someone forgot to delete it.

As https://github.com/joomla/joomla-cms/pull/19879 is towards 4.0, I suggest to make a similar PR towards staging. Will you do?

**Comment by izharaazmi** [comment]
@infograf768 Please see whether https://github.com/joomla/joomla-cms/pull/22178 is acceptable. If not I'll do it the old way.

**Comment by infograf768** [comment]
Closing as we have patch https://github.com/joomla/joomla-cms/pull/22178
