### ISSUE TITLE
[3.9] com_actionlogs and com_privacy do not have visible "permissions"

### ISSUE THREAD

**Issue by jsubri** [joomla/joomla-cms#22153]
### Steps to reproduce the issue

enable actionlogs and privacy
Global Configuration, under component select either Privacy or User Actions Log
For none of them you can enable "permissions"

Back-end : login as Super User, both Privacy and User Actions Log menus are visible.
Back-end : login as Administrator, both Privacy and User Actions Log menus are not visible. If this is the expected behavior how we can make them available to Administrator ? 
With Administrator "User Actions Log" is reachable using administrator/index.php?option=com_actionlogs even the menu is not visible. 
With Administrator "Privacy" is not reachable using administrator/index.php?option=com_privacy "403 You are not authorised to view this resource"

### Actual result
Inconsistent permissions / menu visibility for Administrator

### System information (as much as possible)
3.9 Beta
PHP 7.1.12

**Comment by mbabker** [comment]
> If this is the expected behavior how we can make them available to Administrator ?

You don't.  The components are both hardcoded to only be authorized for use by super users.

**Comment by ghost** [comment]
@jsubri can you please close the Issue if the Answer of @mbabker resolve it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22153">issues.joomla.org/tracker/joomla-cms/22153</a>.</sub>

**Comment by B3nito** [comment]
I can see too - logged in as Administrator level.
![grafik](https://user-images.githubusercontent.com/43232309/45484173-95e85500-b753-11e8-840a-0b1b50aff7a9.png)

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/22163 will make com_actionslog accessible to super admins account only and should address this issue
