### ISSUE TITLE
[4.0] Choose how we want to add browser specific Polyfills

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#22164]
### Steps to reproduce the issue
From the conversation in #22100 there are several ways to attach a polyfill

1. Server side browser detection to insert the js file
2. Client side browser detection to insert the js file (I believe the way that @dgrammatiko preferred)
3. Always include the JS but bail early we don't need to patch

Disadvantages of each:
1. If there are proxies in front then server detection can fail. Practically given most the polyfills are IE and most IE usage is in corporates with proxies this could be significant
2. Including other JS files with javascript isn't very clean (but guarantees support added where required)
3. Means the JS file is always loaded increasing page load time of first page load.

**Comment by brianteeman** [comment]
@wilsonge is this still relevant now ie11 support is dropped?

**Comment by dgrammatiko** [comment]
Polyfills are still very relevant in the ESxxxx land so this still needs to be addressed

**Comment by brianteeman** [comment]
@wilsonge is this still relevant. If it is then shouldnt it be addressed right now. Otherwise please close

**Comment by dgrammatiko** [comment]
This is still relevant. The missing polyfill is one tiny file: https://www.npmjs.com/package/dom4 but also we NEED to review the ES5 files (or just remove them as right now they are not functional AFAIK)

About the loading: is far easier, just load the js with a `nomodule` attribute and without any defer/async. Make sure that is in the dependencies in the WAM. That's it, no sniffing no extra processing...

**Comment by brianteeman** [comment]
so this should be marked as a release blocker

**Comment by dgrammatiko** [comment]
> so this should be marked as a release blocker

Depends on the severity of IE11 support

**Comment by dgrammatiko** [comment]
The ie poly fills are irrelevant so this can be closed @richard67

**Comment by richard67** [comment]
Closing for reason stated in the previous comment.
