### ISSUE TITLE
[4.0] ACL: Inherit permission

### ISSUE THREAD

**Issue by rolandalsace** [joomla/joomla-cms#22169]
### Steps to reproduce the issue
In a workflow permissions, when you change execute transition to allowed or denied, after save the state return to inherit, but the calculated setting have the value seted (allowed ou denied).

In fact it's not a inherit value.

It's not possible to return ton a real inherit value, even if we force to inherit, it's always the old value allowed or denied event if it's display "inherited".

The problème is the same in Transition ACL "Execute Transition".

After save allowed or denied, the calculated value seems good, but the field display "inherited". 

(update 16:50 with integration of my comment)

### Additional comments
J4 alpha5 bluid 12/09/2018

**Comment by rolandalsace** [comment]
I complete my tests.

In fact it's not possible to return ton inherit, even if we force to inherit, it's always the old value allowed or denied.

The problème is the same in Transition ACL "Execute Transition", after save allowed or denied, the calculated value seems good, but the field display "inherited". <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22169">issues.joomla.org/tracker/joomla-cms/22169</a>.</sub>

**Comment by alikon** [comment]
i suggest you to test with the current 4.0 staging, a lot of things have changed in the meantime

**Comment by rolandalsace** [comment]
I have test with the last nightly build ...
These packages were last built: Thursday, 13 September 2018 02:00:17 UTC

**Comment by rolandalsace** [comment]
...and in com_content, the select list "state" dont display the list of Stages in transitions authorised for the current user.
Only the actual stage of current item is on the state list.
The problème is perhaps in ACL management, and not in com_workflows ?

**Comment by alikon** [comment]
iirc before workflows.......
i've not experienced issues with ACL even in 4.0 branch

**Comment by bembelimen** [comment]
> iirc before workflows.......
> i've not experienced issues with ACL even in 4.0 branch

Sorry to disappoint you, but this issue is also in com_menu, com_categories, ....

**Comment by brianteeman** [comment]
Can you post some screenshots please - or even better a short recording with something like https://www.cockos.com/licecap/

**Comment by rolandalsace** [comment]
Hi 

Here is the vidéo of the 2 problems (2 files low quality because 10mb and zip because upload of mp4 not allowed !)
[joomla workflow and acl problem.part1of2.zip](https://github.com/joomla/joomla-cms/files/2391811/joomla.workflow.and.acl.problem.part1of2.zip)
[joomla workflow and acl problem.part2of2.zip](https://github.com/joomla/joomla-cms/files/2391819/joomla.workflow.and.acl.problem.part2of2.zip)

PS : I confirm the post of bembelimen (see my 2nd video file)

**Comment by brianteeman** [comment]
Thank you for the videos. I can confirm what you are seeing AND that this issue is not present in Joomla 3

**Comment by brianteeman** [comment]
I have updated the title to show that this is not specifically related to workflows

**Comment by rolandalsace** [comment]
> 
> 
> Thank you for the videos. I can confirm what you are seeing AND that this issue is not present in Joomla 3

Of course (and fortunately), it's only on J4 alpha x (see my 1st post).

**Comment by brianteeman** [comment]
pretty certain this is coming from a bug in media\system\webcomponents\js\joomla-field-permissions.js

**Comment by rolandalsace** [comment]
Hi.

Today the problème is always here with the last nigthly build of J4 alpha7 (2019-02-20)

The problème is only on categories.

In the store action the json "rules" field of the #__assets table is cleared, instead of be completed with the new user's group rule.

So the others user's group rule are lost.

It's only in asset stored by com_categories (but for all extensions)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22169">issues.joomla.org/tracker/joomla-cms/22169</a>.</sub>

**Comment by Quy** [comment]
@bembelimen OK to close with PR #29263?

edit: updated PR ID

**Comment by bembelimen** [comment]
Yes, should be fixed with the PR.

**Comment by Quy** [comment]
Please test PR #29263?
