### ISSUE TITLE
Privacy Policy Status Wording is misleading

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#22167]
![grafik](https://user-images.githubusercontent.com/43232309/45493647-8c6ce600-b76f-11e8-89da-5c9ae0016c21.png)
The label say publish and unpublish - but plugins are disabled or enabled.

![grafik](https://user-images.githubusercontent.com/43232309/45493688-a3133d00-b76f-11e8-970b-3c5370db1116.png)

![grafik](https://user-images.githubusercontent.com/43232309/45493743-bcb48480-b76f-11e8-9017-e900bcf6074d.png)

And you can only edit privacy for one language here.
Maybe headline can say Plugin Status check so user knows where to search.

**Comment by mbabker** [comment]
The check is not based on whether you have that specific plugin enabled.  The check is on whether a plugin which supports defining a privacy policy has one set.

So in the case with the core plugin, it checks whether you have set an article as your privacy policy in that plugin.

**Comment by B3nito** [comment]
Then maybe you say **set** or **not set** but published the policy it is.

**Comment by brianteeman** [comment]
Published is the correct English here

**Comment by B3nito** [comment]
I know that it is a correct english word, but the policy is published always it is only not set in the plugin.

**Comment by brianteeman** [comment]
Closed. This is not referring to the plugin. IT is referring to if there is a privacy policy published
