### ISSUE TITLE
string truncate error after update to Joomla 3.9

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#22171]
I have this code in my theme:
`	
$intro = '';
$intro = $item->introtext;
JHTML::_('string.truncate');
echo JHtmlString::truncate($intro,110, true, false);`

when update to 3.9 I have this error:
![grafik](https://user-images.githubusercontent.com/43232309/45495748-2afb4600-b774-11e8-9ba8-9d6172ee2ba1.png)
In 3.8.12 no have a problem.

**Comment by SharkyKZ** [comment]
Remove `JHTML::_('string.truncate')` or change `JHtmlString::truncate($intro,110, true, false)` to `JHtml::_('string.truncate', $intro,110, true, false)`.

**Comment by B3nito** [comment]
Thank you, issue solved, but why it working in 3.8.12 ?

**Comment by SharkyKZ** [comment]
No idea. Doesn't work for me on 3.8.12.

**Comment by laoneo** [comment]
For me `JHTML::_('string.truncate');` does also not work on 3.8.12. Do you have the same error reporting setting in your Joomla config?

**Comment by B3nito** [comment]
can be not. thank you everyone!
