### ISSUE TITLE
Privacy agree consent later is error 403 after submit

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#22173]
### Steps to reproduce the issue
- you update to joomla 3.9 beta and you enable plugin for privacy
- you setup privacy policy
- you login as user and you get profile page
- you click on agree

### Expected result
- Profile save

### Actual result
- Error 403

### System information (as much as possible)
Joomla nighlty build 3.9

**Comment by alikon** [comment]
can someone else confirm, cuase i'm unable to replicate

**Comment by B3nito** [comment]
Its a site that I update from 3.8.12 with many users. User was created in 3.8.x

**Comment by alikon** [comment]
did you check if in Extensions-> Database  are reported some fix?

**Comment by B3nito** [comment]
There is no fix report

![grafik](https://user-images.githubusercontent.com/43232309/45546358-5a19c200-b81d-11e8-9f75-f9cc18250f19.png)

**Comment by joomdonation** [comment]
Last night, I tried but could not re-procedure the issue (my installation is a fresh installation of Joomla 3.9 beta)

Could you please make a screenshot of the error page? Maybe it will help us seeing the issue easier

**Comment by B3nito** [comment]
![grafik](https://user-images.githubusercontent.com/43232309/45585980-1db69680-b8ef-11e8-99f8-08739eecea09.png)
It is 403 error on http://localhost/joomlatest/es/editar-perfil?task=profile.save

it is not fresh installation it is update from 3.8.12 site for test

**Comment by joomdonation** [comment]
This issue should be addressed by https://github.com/joomla/joomla-cms/pull/22196 already. You can confirm that by look at #__privacy_consents table on your site database, change data type of subject field to varchar(255) and it will solve this issue (before, it was varchar(25) and could not store data properly)

**Comment by joomdonation** [comment]
Sorry, please ignore my above comment, I was about commenting on a different issue https://github.com/joomla/joomla-cms/issues/22212 (but maybe you can try this suggestion anyway)

**Comment by B3nito** [comment]
I reinstalled Joomla nightly build today and I have still 403 Error also with #22196 - no change

**Comment by joomdonation** [comment]
Not sure why 403 errors happen. If it's a test site and you can share, make a backup using akeeba backup and attach it here. I will try to check to see where the 403 comes from and get it sorted

**Comment by B3nito** [comment]
It is a website with 4000 users and internal data I cannot share it. But maybe help this?
![grafik](https://user-images.githubusercontent.com/43232309/45750434-5d42f280-bc0f-11e8-8a12-b4c1b7f9a65f.png)

**Comment by joomdonation** [comment]
If you look at the callstack, you will see that it's something from AdminTools, not from Joomla core

**Comment by B3nito** [comment]
Got it. Is it possible to exclude super admin from privacy tool consent in joomla? otherwise you have to disable admintools. Because settings saving is not possible for super admins.

**Comment by mbabker** [comment]
We should not be introducing code to bypass privacy policy acceptance on the frontend based on permissions.

**Comment by brianteeman** [comment]
> . Because settings saving is not possible for super admins.

It is possible, there is an option in admintols specifically for that. I am closing this as the "problem" is not related to joomla core

**Comment by B3nito** [comment]
My company have written contract with every administrator that is more extended than the policy for website. because they have another work doing as a visitor of website. I can imagine other companies work same and need to disable or have another contract for super user and admin...
