### ISSUE TITLE
Privacy add custom consent in user registration

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#22170]
Is it possible to add more consent documents to the registration? terms and conditions or conditions of contradiction?

**Comment by mbabker** [comment]
Use custom fields or write plugins extending the forms.  All the consent plugin is doing is using the existing core API to extend the registration form to add the consent field, it's not doing anything special that wasn't available before 3.9.

**Comment by B3nito** [comment]
is there documentation how to collect and manage additional consent in the privacy component?

**Comment by ghost** [comment]
@mbabker cen you please comment?

**Comment by ghost** [comment]
@mbabker reminder.

**Comment by jwaisner** [comment]
Closing this as it was not validated as a bug or feature request.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22170">issues.joomla.org/tracker/joomla-cms/22170</a>.</sub>
