### ISSUE TITLE
[com_installer] JTEXT::sprintf not translating in install script

### ISSUE THREAD

**Issue by mixahlos** [joomla/joomla-cms#22179]
### Steps to reproduce the issue
create an install script for extension.
In the preflight function (or any other function, I have also tried in more cases)
```
  public function __construct() {
    $manifest = $this->getItemArray(JFactory::getDbo()->quote($this->extension));
    $this->oldRelease = $manifest['version'];
  }
  public function preflight($type, $parent) {
    $this->release = $parent->get('manifest')->version;
    if (strtolower($type) == 'update') {
      if (version_compare($this->release, $this->oldRelease, '<')) {
        JFactory::getApplication()->enqueueMessage(JText::sprintf('COM_EXAMPLE_UPDATE_LOWER_VERSION', $this->oldRelease, $this->release), 'error');
        return false;
      } 
      return true;
    }
```

The language file in : admin/language/en-GB.com_example.sys.ini

`COM_EXAMPLE_UPDATE_LOWER_VERSION="Your version is %s. You cannot downgrade to version %s !"`

### Expected result
Error
Your version is 0.1.5. You cannot downgrade to version 0.1.1 !
Error installing component

### Actual result
Error
COM_EXAMPLE_UPDATE_LOWER_VERSION
Error installing component

### System information (as much as possible)
Joomla Version : 3.8.12

**Comment by tonypartridge** [comment]
You haven’t included the language file on the preflight since it’s not installed. 

iirc for it to be loaded on the installer it needs to be in:

/language/en-GB.com_example.ini

**Comment by infograf768** [comment]
> /language/en-GB.com_example.ini

or `/language/en-GB/en-GB.com_example.ini` ?
can't find a doc on preflight

**Comment by mixahlos** [comment]
The Language  ini file is not the problem. The following Is translated fine.
 `JText::_('COM_EXAMPLE_UPDATE_LOWER_VERSION')`

If you check the [docs](https://docs.joomla.org/Special:MyLanguage/J3.2:Developing_an_MVC_Component/Adding_an_install-uninstall-update_script_file) you will notice this : 

> note: If you want that these languages KEYs to be used at the first install of the component, the sys.ini language file must be stored in the component folder (admin/language/en-GB/en-GB.com_helloworld.sys.ini), and the xml manifest file must contains a folder tag for copying language in the component folder. Modify your Manifest file accordingly:

**Comment by ghost** [comment]
@infograf768 can you please comment?

**Comment by infograf768** [comment]
can't help without getting such an extension.

**Comment by ghost** [comment]
so @mixahlos have to provide an Extension?

**Comment by infograf768** [comment]
that would help, yes, as I see no reason for JText to work and JText::sprintf not

**Comment by infograf768** [comment]
My guess is that the string should be in components/extension/language/xx-XX/xx-XX.extension.sys.ini

**Comment by ghost** [comment]
@mixahlos can you provide a Extension?

**Comment by ghost** [comment]
Closed as no Answer, please reopen if needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22179">issues.joomla.org/tracker/joomla-cms/22179</a>.</sub>
