### ISSUE TITLE
Privacy user side menu not with full items

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#22172]
![grafik](https://user-images.githubusercontent.com/43232309/45496169-1f5c4f00-b775-11e8-9f03-354cf0764d7e.png)

Privacy consent is not show in the menu

**Comment by mbabker** [comment]
This is an intentional design decision, see https://github.com/joomla-projects/privacy-framework/issues/228 and https://github.com/joomla-projects/privacy-framework/pull/229

**Comment by B3nito** [comment]
Did you design it? Not clear for me.

**Comment by mbabker** [comment]
It opens too big a can of worms because if we're going to add the privacy and action log component items to the com_users sidebar then all three of those components should have the same sidebar.  They are individual components, they should not be cross-linked as you suggest.
