### ISSUE TITLE
[4.0] Nested subforms buttons not clickable

### ISSUE THREAD

**Issue by continga** [joomla/joomla-cms#22183]
When adding nested subforms in Joomla 4.0.0-alpha3 and adding multiple rows of the most-inner subform, the add/remove buttons of the more outer subforms are not clickable anymore.

### Steps to reproduce the issue
1) Install Joomla 4.0.0-alpha3
2) Edit the file `plugins/fields/checkboxes/params/checkboxes.xml` and add the following after line 26:
```
<field
        name="subformlevel2"
        type="subform"
        label="PLG_FIELDS_CHECKBOXES_PARAMS_OPTIONS_LABEL"
        layout="joomla.form.field.subform.repeatable-table"
        icon="list"
        multiple="true"
>
        <form hidden="true" name="list_templates_modal" repeat="true">
                <field
                        name="name_lvl2"
                        type="text"
                        label="PLG_FIELDS_CHECKBOXES_PARAMS_OPTIONS_NAME_LABEL"
                        size="30"
                />
                <field
                        name="subformlevel3"
                        type="subform"
                        label="PLG_FIELDS_CHECKBOXES_PARAMS_OPTIONS_LABEL"
                        layout="joomla.form.field.subform.repeatable-table"
                        icon="list"
                        multiple="true"
                >
                        <form hidden="true" name="list_templates_modal" repeat="true">
                                <field
                                        name="name_lvl3"
                                        type="text"
                                        label="PLG_FIELDS_CHECKBOXES_PARAMS_OPTIONS_NAME_LABEL"
                                        size="30"
                                />
                        </form>
                </field>
        </form>
</field>
```
3) In the Joomla installation, go to the Backend, Content -> Fields -> New, change the `Type` to `Checkboxes`
4) Add a new row of the `Checkbox values`, and a new row of the then appearing inner subform, and a new row of the then appearing inner subform, so you have 3 rows of the 3 nested subforms - like in this screenshot:
![image](https://user-images.githubusercontent.com/2082625/45556901-ae806a00-b83c-11e8-9c05-0b9cb5b4b577.png)
5) Try to click on the add or remove buttons of the outer subforms (not the innermost) - they are not working, there isn't even an onclick-event assigned to them.

### Expected result
The outermost add/remove buttons should work, they should add a new row of their respective subform.

### Actual result
The buttons do nothing, there isn't even an onlick event assigned to them.

### System information (as much as possible)
Tested on Joomla 4.0.0-alpha3 using Firefox 62.0 on Linux.

### Additional comments
I noticed this problem when testing this functionality in Joomla 4 regarding PR #17552 (re @Fedik )

**Comment by ghost** [comment]
can you please test on [Nightly Build](https://developer.joomla.org/nightly-builds.html)?

**Comment by continga** [comment]
Well, with the latest Nightly Build, the system seems completely broken tbh.

When clicking Content -> Fields -> New, only the name of the field can be set, not the Type etc:
![image](https://user-images.githubusercontent.com/2082625/45560364-2bafdd00-b845-11e8-972f-593d84396fa2.png)

After saving it, I get access to the other options, so I testwise added the 3 nested subforms for the Textfield type:
![image](https://user-images.githubusercontent.com/2082625/45560451-61ed5c80-b845-11e8-9bd6-55fe08a9f75c.png)

But now nothing happens at all when clicking on the "Add" button, so the whole Subform system is broken in the latest nightly build.

**Comment by Fedik** [comment]
I just checked and can confirm, the `subform` field is broken
I will check more, when will have some time

something with build scrip

**Comment by Fedik** [comment]
please test #22185

**Comment by ghost** [comment]
closed as having Pull Request #22185

**Comment by continga** [comment]
@franz-wohlkoenig Can we please reopen this issue?

The problem with the nightly build (subforms not working at all) is fixed with #22185 but the main problem from the opening post is still present.

I just tested the main problem (described in the opening post) on 4.0-dev at version https://github.com/joomla/joomla-cms/commit/e051bb282075e86135099e73e9e0e853b5886819 with the patch applied from #22185 but still the add / remove buttons are not clickable:
![image](https://user-images.githubusercontent.com/2082625/45563648-4aff3800-b84e-11e8-90d5-5e8a9a77ccae.png)

**Comment by ghost** [comment]
Reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22183">issues.joomla.org/tracker/joomla-cms/22183</a>.</sub>

**Comment by Fedik** [comment]
> but still the add / remove buttons are not clickable

this is a styling issue, 
so no issue here :wink: 

![screen 2018-09-14 21 23 34 585x518](https://user-images.githubusercontent.com/1568198/45568189-a2100780-b864-11e8-82db-2de8859a64ce.png)


 btw, I would not recommend to use very deeeeeep nested `subform`

**Comment by continga** [comment]
well, you are right @Fedik ... I removed that element from the page for taking the above screenshot, but did then not check whether that element was causing the error xD sorry...

Should be then close this issue, or should we keep it open to fix the problem with the overlaying element?

**Comment by Fedik** [comment]
I guess can close it, because the issue was caused not by real use case but by the testing instruction.

**Comment by ghost** [comment]
Closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22183">issues.joomla.org/tracker/joomla-cms/22183</a>.</sub>
