### ISSUE TITLE
[3.9] User Actions Log: Privacy Consent not displayed in the dashboard

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-cms#22184]
When a user is registering on a site, their consent to the Terms and Conditions is displayed on the Action Logs screen, but not their consent to the Privacy Policy (which is stored in the Privacy Consents screen). 
Wouldn't it make sense to have also this Privacy Consent displayed in the Action Logs?

**Comment by alikon** [comment]
yes for me
see #22192

**Comment by ghost** [comment]
closed as having Pull Request #22192
