### ISSUE TITLE
[3.9] 404 for Privacy/Terms articles if articles are "uncategorised"

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-cms#22195]
If the Privacy or Terms & Conditions articles are under the "Uncategorised" category, when clicking on the Privacy or Terms link in the registration form (or contact form),  you have a nice 404.
If the articles are in a created category, the articles are displayed as expected.

**Comment by alikon** [comment]
cannot replicate

**Comment by Sandra97** [comment]
I told you I was a terrible tester 😉

**Comment by alikon** [comment]
not sure if i've already told you.... but....human tester are supposed to be "**terrible**"  :smiley:

**Comment by Sandra97** [comment]
I can grant you an access to my dev server if you want to check

**Comment by brianteeman** [comment]
@Sandra97 is this still an issue for you or can this be closed?

**Comment by Sandra97** [comment]
I'm finishing moving today so I'll check tonight and will let you know.

**Comment by Sandra97** [comment]
I can't replicate anymore. I presume we can close this issue.
