### ISSUE TITLE
No action log 

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#22199]
Activate Actionlog in plugin
![grafik](https://user-images.githubusercontent.com/43232309/45586206-f82b8c00-b8f2-11e8-8875-067acc37f7a5.png)

Create new article
Edit article
create user
delete user

No action logged
![grafik](https://user-images.githubusercontent.com/43232309/45586210-109ba680-b8f3-11e8-8852-3a2b8dea59a7.png)

**Comment by SharkyKZ** [comment]
What about `System - User Actions Log` plugin (not shown in your screenshot)?

**Comment by B3nito** [comment]
That was problem! Thank you! Why not found with seach for "privacy"? Everything have privacy in name and not this.

**Comment by brianteeman** [comment]
Because it is more generic than just privacy.
