### ISSUE TITLE
Privacy Content wording I agree and No

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#22198]
![grafik](https://user-images.githubusercontent.com/43232309/45586067-7fc3cb80-b8f0-11e8-9abd-0e8c43a0fd9e.png)

The consent text say "I agree" and "No" - It is better to say I don't agree or something that is opposite of "I agree". Because No is no answer. A question is missing too. Or you say I agree to privacy policy and I not agree to privacy policy. It is more legal say then.

**Comment by SharkyKZ** [comment]
IMO, all fields like this should be a checkbox.

**Comment by B3nito** [comment]
You can say it is radiobox because it is only one option you chose but here is no question or full sentence. You say here "I agree" and "No" it is not good - My teacher asked me to say full sentence in school jajaja

**Comment by alikon** [comment]
lack of interest<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22198">issues.joomla.org/tracker/joomla-cms/22198</a>.</sub>

**Comment by SharkyKZ** [comment]
Hey, this is in my backlog. Keep this open for now, in case someone else wants to do it before I get around to it.

**Comment by alikon** [comment]
reopened as requested<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22198">issues.joomla.org/tracker/joomla-cms/22198</a>.</sub>

**Comment by alikon** [comment]
@SharkyKZ  can we close this one or it is still in your backlog ?

**Comment by therahilshaikh** [comment]
can i contribute?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22198">issues.joomla.org/tracker/joomla-cms/22198</a>.</sub>

**Comment by ghost** [comment]
> can i contribute?

@therahilshaikh please read https://github.com/joomla/joomla-cms/issues/31540#issuecomment-811070565

**Comment by shagungarg0** [comment]
is this issue still on?

**Comment by Quy** [comment]
Please test PR #37181. Thanks.
