### ISSUE TITLE
[4.0] build/stubGenerator.php does not work: Dispatcher not set in Joomla\CMS\Application\CliApplication

### ISSUE THREAD

**Issue by Fedik** [joomla/joomla-cms#22191]
### Steps to reproduce the issue
run in console `php build/stubGenerator.php`,

### Expected result
the script runs

### Actual result
error, HTML output with `<h1>Whoops, looks like something went wrong.</h1>`

With try/catch I found a real error:
```
Dispatcher not set in Joomla\CMS\Application\CliApplication
line: /libraries/vendor/joomla/event/src/DispatcherAwareTrait.php:41
```

### System information (as much as possible)
php 7.2
joomla 4.0-dev branch

**Comment by wilsonge** [comment]
> With try/catch I found a real error:
> Dispatcher not set in Joomla\CMS\Application\CliApplication
line: /libraries/vendor/joomla/event/src/DispatcherAwareTrait.php:41

Just as an FYI for next time you can also set the param here https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/bootstrap.php#L51 to `true` to get that trace too :)

**Comment by wilsonge** [comment]
Fixed with https://github.com/joomla/joomla-cms/commit/373e53101b04b01de7715dea0761dc77ce1884f7

**Comment by Fedik** [comment]
@wilsonge thanks for info and for fixing
