### ISSUE TITLE
[4.0] messages pop up sometimes cropped

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#22202]
### Steps to reproduce the issue
- Joomla 4 Nightly, new installation
- Go to articles list (BE)
- Click the bell
![15-09-_2018_17-46-46](https://user-images.githubusercontent.com/20780646/45588126-e3112600-b90f-11e8-9ca1-c8b090b27661.jpg)

**Comment by TobsBobs** [comment]
PR #22186
