### ISSUE TITLE
Could not start mail function.

### ISSUE THREAD

**Issue by ZerooCool** [joomla/joomla-cms#22205]
### Steps to reproduce the issue
When i install apache mariadb by default with joomla, i can't send mail with PHP Mail.
Syslog notify this line : /var/www/html/libraries/vendor/phpmailer/phpmailer/class.phpmailer.php:702 

### Expected result
Send a mail with php mail.

### Actual result
From administrator when i test the mail :
`Could not start mail function.` (Translated to English by JM)

### System information (as much as possible)
The serveur Debian 9.5 stable
https://github.com/ZerooCool/Linux-Search-Engine-Optimisation/blob/master/installation/3-installer-le-serveur-dans-le-conteneur.sh

https://github.com/ZerooCool/Linux-Search-Engine-Optimisation/blob/master/installation/4-installer-joomla.sh

### Additional comments
When i change a option in admin panel, for change mail value, and Save that, i need F5 after that to see the new value. Refresh not work good, with joomla, or, firefox ?

**Comment by SharkyKZ** [comment]
> When i change a option in admin panel, for change mail value, and Save that, i need F5 after that to see the new value. Refresh not work good, with joomla, or, firefox ?

Test PR https://github.com/joomla/joomla-cms/pull/21949 for this issue.

**Comment by ghost** [comment]
closed as having Pull Request #21949

**Comment by ZerooCool** [comment]
I confirm Brian's answer.
STARTTLS + the good SSL server at OVH works. The email is sent.

I confirm that the problem of sending mail is solved, using another SMTP server, directly in SSL: ssl0.ovh.net for OVH.

Thank you Franz and Brian.

**Comment by ZerooCool** [comment]
I confirm Brian's answer.
STARTTLS + the good SSL server at OVH works. The email is sent.

I confirm that the problem of sending mail is solved, using another SMTP server, directly in SSL: ssl0.ovh.net for OVH.

Thank you Franz and Brian.
