### ISSUE TITLE
[3.9] Actions log. Users of group "Registered" receive action logs messages by email.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#22203]
### Steps to reproduce the issue
- New installation: Nightly build Joomla_3.9.0-beta2-dev-Development-Full_Package.zip, Saturday, 15 September 2018 02:00:02 UTC
- Activate Plugin "System - User Actions Log"
- Add a new  user (in my case named "Example4") with group **Registered(!)** and before you save it go to tab "User Actions Log"
- And even if it's stupid set `Sent notifactions... : Yes`

![15-09-_2018_23-28-58](https://user-images.githubusercontent.com/20780646/45590878-7b74ce00-b943-11e8-9f10-f01d8871c0ee.jpg)

- Save user
- Deactivate/Activate an extension or do some other actions relevant for plugin "System - User Actions Log"
- Check the new emails that the new user received:

![15-09-_2018_23-51-20](https://user-images.githubusercontent.com/20780646/45590859-36509c00-b943-11e8-8c64-48538d45cab7.jpg)

- Go into the user profile of this user. Try to disable `Sent notifactions... : Yes`. No tabulator anymore to do that.

![16-09-_2018_00-01-41](https://user-images.githubusercontent.com/20780646/45590884-c393f080-b943-11e8-948d-f3c9720ba9a1.jpg)

### Expected result
- Users of group Registered never get action log emails.

**Comment by SharkyKZ** [comment]
This fix is included in #21983.

**Comment by ghost** [comment]
closed as having Pull Request #21983
