### ISSUE TITLE
Creating categories on the fly with numbers

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#22216]
### Steps to reproduce the issue

1. Create a category and remember the ID (or use an existing category) e.g. "2"
2. Create a new article or edit one and try to create a new category with the name: "2nd workshop" (important: the ID of the category from 1. has to be the leading character) by typing in the name in the category select on the right side + confirm with [ENTER]
3. Save article

### Expected result
A new category is created and assigned to the article

### Actual result
The old category from 1 is assigned

**Comment by brianteeman** [comment]
confirmed

**Comment by SharkyKZ** [comment]
Test PR #25024 please.

**Comment by alikon** [comment]
closed as we have a pr #25024<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22216">issues.joomla.org/tracker/joomla-cms/22216</a>.</sub>
