### ISSUE TITLE
Core files distributed are deleted by update script (not in sync)

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22219]
myJoomla.com users report that several files are "missing" from their webspace.

On investigation, for example, 

administrator/templates/hathor/html/com_languages/installed/default_ftp.php

This file exists in staging here: 

https://github.com/joomla/joomla-cms/blob/staging/administrator/templates/hathor/html/com_languages/installed/default_ftp.php

But is deleted here: 

https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/script.php#L533

It looks like something is out of sync here... maybe there are more files that can be removed from staging... The myJoomla.com file lists are compiled by the Stable Zip of the release. 

**The point is, why distribute the file, and then delete it?**

Files effected:
```
/media/mod_languages/images/si_lk.gif
/media/jui/img/ajax-loader.gif
/libraries/fof/LICENSE.txt
/administrator/templates/hathor/html/com_languages/installed/default_ftp.php
```

ALSO Joomla is INCORRECTLY deleting `/media/mod_languages/images/si_lk.gif` This is because in the past someone added `si_LK.gif` and `si_lk.gif` (case sensitive) to the distribution, and now Joomla is deleting that in script.php - this is incorrect, because its deleting the lowercase (correct one) that Joomla needs even though in script.php its the `si_LK.gif` one - this is because someone who added that did not test PHP on all platforms... and did not understand that unlink is not case sensitive ;-)

**Comment by Scrabble96** [comment]
It seems that the language/index.html file has been changed, too, from  `<!DOCTYPE html><title></title>` to  `<html><head><title></title></head><body></body></html>` .

**Comment by onderzoekspraktijk** [comment]
For sometime now this issue persists.
Today updated to joomla 3.8.13, checked afterwards using Watchfulli audit, wich reports as missing:
/libraries/fof/LICENSE.txt
/media/jui/img/ajax-loader.gif
/media/mod_languages/images/si_lk.gif.
The first one will be Akeeba, the last two are Joomla core files.

So I used the re-install Joomla core filed button inside the Joomla Update component. Cjecked again with Watchfulli audit and got the exact same error message again.

I suppose this is no show stopper, but it feels not right.

**Comment by Scrabble96** [comment]
> I suppose this is no show stopper, but it feels not right.

I use Watchful.li, too, which is how I first came across the issue. Would you be able to post your comment above on the Joomla 3.8.13 discussion forum? I made a comment about it but I think I'm either being ignored or they think I'm not a Super User, which I am. If you comment about the same missing files, they might take more notice.

**Comment by infograf768** [comment]
I have proposed maintainers to delete these lines in script.php

**Comment by PhilETaylor** [comment]
ok I have opened #22580, #22581, #22582, #22583 to address some of these.

I don't have time to unpick the CaseSensitive si_lk.gif deletion at the moment, I'll come back to that.

**Comment by onderzoekspraktijk** [comment]
Okay!

**Comment by Scrabble96** [comment]
> 
> 
> ok I have opened #22580, #22581, #22582, #22583 to address some of these.
> 
> I don't have time to unpick the CaseSensitive si_lk.gif deletion at the moment, I'll come back to that as it needs to be tested on multiple file systems and platforms as we only need to delete the si_LK.gif and not the si_lk.gif

Thank you.

**Comment by PhilETaylor** [comment]
after https://github.com/joomla/joomla-cms/pull/22648 and https://github.com/joomla/joomla-cms/pull/22646 the only thing left is the si_lk.gif and I dont know how best to handle that as PHP appears to not respect case sensitivity.

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/9902#issuecomment-213947521
