### ISSUE TITLE
Login + remember me + Redirect after login

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#22215]
### Steps to reproduce the issue

1. Create a page (e.g. article), set the menu entry as "home" and set it to registered
2. Create another article, also for registered user only
3. Create a link to the login (public)
4. Log into your page and check the "remember me" checkbox
5. Go to the article from point 2.
6. Copy the link and then close your browser
7. Open browser again and put in the link from article 2

### Expected result
after the plugin relog in you it should redirect you to article 2

### Actual result
The "home"-page appears

### System information (as much as possible)
Latest Joomla 3.8

TLTR: you send a user a link, he/she is automatical logged in and instead of seeing the content of the link he/she is redirected to the home page

**Comment by jwaisner** [comment]
@bembelimen is this still occurring in the latest J3 build?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22215">issues.joomla.org/tracker/joomla-cms/22215</a>.</sub>

**Comment by bembelimen** [comment]
Yes

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

I have verified that this is resolved in Joomla 4 (assuming that you do have a login menu item as in the instruction) and this will now been closed.

@zero-24
