### ISSUE TITLE
Language string with wrong HTML format

### ISSUE THREAD

**Issue by Valc** [joomla/joomla-cms#22214]
### Steps to reproduce the issue
Edit the administrator language file **en-GB.plg_content_contact.ini** at staging branch
Search the key **PLG_CONTENT_CONTACT_PARAM_URL_DESCRIPTION**
The actual string is:
```
You can link the author name to:<ul><li>Associated contact page.<li>Webpage specified in the associated contact profile.<li>Email specified in the associated contact profile.</ul>
```

### Expected result
Good HTML format

### Actual result
Bad HTML format due now is not closing the "li" tags

### Additional comments
Here is solved:
```
You can link the author name to:<ul><li>Associated contact page.</li><li>Webpage specified in the associated contact profile.</li><li>Email specified in the associated contact profile.</li></ul>
```
Regards, Valc.

**Comment by infograf768** [comment]
This is imho current practice. 
See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li

`Tag omission | The end tag can be omitted if the list item is immediately followed by another <li> element, or if there is no more content in its parent element.`

**Comment by Valc** [comment]
Thanks you. No idea about that rule.
If other non mozilla browser also are allowing that one, ok.
Regards.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22214">issues.joomla.org/tracker/joomla-cms/22214</a>.</sub>

**Comment by infograf768** [comment]
I think so as the list is correctly displayed and we never had any comment on this. :smiley:
