### ISSUE TITLE
existing user saving agreement with privacy policy keeps getting privacy notice in neverending loop

### ISSUE THREAD

**Issue by onderzoekspraktijk** [joomla/joomla-cms#22212]
### Steps to reproduce the issue
I used a backup of a live website installed 3.9.0 alpa, and after that beta.
When I log into the frontend I get the edit profile page. This gives me notice to tick the box I agree in the field Privacy Policy, and save that by clicking the submit button.

### Expected result
The result should be that in the backend my agreemeny is registered, and in the frontend I get the message Profile saved...

### Actual result
All this happens, but also I get a notice telling me:
"Please confirm that you consent to this web site stronig your information etc....."
And also the field Privacy Polici is there (in red) with the two responses I agree and No, with No tickt.

When I tick I agree, I get in an neverending loop where the system registers my agreement, and still keeps presenting the notive and the field and keeps asking ...etc.

### System information (as much as possible)
This is a real-life site. So I had Easy profile on, and Trombinoscope. Both deliver extra's in userregistration and contact presentation. I deleted both but cannot see any change in the issue after deleting them. However: perhaps they have triggered something when they were active. Perhaps noy. Both were there in the alpha and worke okay. So.

### Additional comments
The profile has also the field Send notification for User Actions Log, this also presents two radio bittons, and this field works okay: when Yes is ticket the change takes hold aftre submitting the form. So the field type as such functions okay.

**Comment by Twincarb** [comment]
Is this only with an Administrator account? Or does it happen to a Registered user as well? If it's only Admin accounts that have the issue are you running a component that prevents editing of Administrator accounts from the front end?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22212">issues.joomla.org/tracker/joomla-cms/22212</a>.</sub>

**Comment by onderzoekspraktijk** [comment]
It does happen to a registered user as well. (I made a new user set to rgeistred from the backen end. The new user after first login has to tocjt the privacy consent, and this triggers the same neverending loop in the same way.)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22212">issues.joomla.org/tracker/joomla-cms/22212</a>.</sub>

**Comment by Sandra97** [comment]
I can reproduce the issue on 2 live sites upgraded to Beta2. A registered user keeps being asked to confirm their consent. I switched the template to use Protostar to see if it could have been due to some template overrides but still not working as expected.

**Comment by B3nito** [comment]
I have this https://github.com/joomla/joomla-cms/issues/22173 maybe it is connected.

**Comment by joomdonation** [comment]
This issue should be addressed by #22196 already. You can confirm that by look at #__privacy_consents table on your site database, change data type of subject field to varchar(255) and it will solve this issue (before, it was varchar(25) and data was not stored properly)

**Comment by ghost** [comment]
closed as having Pull Request #22196

**Comment by Healyhatman** [comment]
Still happening for me, two different sites.

**Comment by ghost** [comment]
@Healyhatman can you please open a new Issue as Comments on closed ones got low Notice. https://docs.joomla.org/Filing_bugs_and_issues#Reporting_bugs
