### ISSUE TITLE
[com_actionlogs] Localize export header

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#22225]
### Steps to reproduce the issue
Should the export headers be localized?

`$rows[] = array('Id', 'Message', 'Date', 'Extension', 'User', 'Ip');`

**Comment by mbabker** [comment]
I'm going to suggest no.  It helps keep the data machine parsable if there is a consistent format for the headings (otherwise you're left assuming based on column count that column 3 is the date).
