### ISSUE TITLE
Remove period under Date column

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#22226]
### Steps to reproduce the issue

`10 minutes ago.`
I don't consider the value a sentence so remove the period. Also, this is the only column that appends a period.

**Comment by mbabker** [comment]
It's coming from the [language strings](https://github.com/joomla/joomla-cms/blob/358f568255deb3d14ed16af573f951268e913dc7/administrator/language/en-GB/en-GB.lib_joomla.ini#L407-L419).

**Comment by brianteeman** [comment]
It would need its own string if its a column heading instead of reusing a generic string

**Comment by mbabker** [comment]
It's not a heading, it's the content in the row.

<img width="380" alt="screen shot 2018-09-18 at 7 16 44 am" src="https://user-images.githubusercontent.com/368545/45686879-ddcff900-bb12-11e8-89f1-63ebb371c239.png">

**Comment by brianteeman** [comment]
ok - deosn't need a period then BUT these strings already existed and are in a generic file so it is reasonable to assume they could have been used to produce something like
`File named john was created 23 hours ago.
`
So if you want to use it here without the period then it will need to be new strings

**Comment by mbabker** [comment]
Same strings are also used on the privacy component's requests list.  Just something to keep in mind for whomever works on a pull request.

**Comment by SharkyKZ** [comment]
And any 3rd party extensions that use `JHtmlDate::relative()`.

**Comment by alikon** [comment]
@Quy can we close this one ? 
it seems lack of interest
