### ISSUE TITLE
Uninstall library extension type throws error

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#22221]
### Steps to reproduce the issue
1. Install Joomla 3.9 beta
2. Install the attached library
3. Then uninstall it

### Expected result
The library is uninstalled

### Actual result

> Call to a member function attributes() on null	
> D:\www\beta\plugins\actionlog\joomla\joomla.php:428
> 

Call stack
--
# | Function | Location
1 | () | JROOT\plugins\actionlog\joomla\joomla.php:428
2 | PlgActionlogJoomla->onExtensionAfterUninstall() | JROOT\libraries\joomla\event\event.php:70
3 | JEvent->update() | JROOT\libraries\joomla\event\dispatcher.php:160
4 | JEventDispatcher->trigger() | JROOT\libraries\src\Installer\Installer.php:773
5 | Joomla\CMS\Installer\Installer->uninstall() | JROOT\administrator\components\com_installer\models\manage.php:246
6 | InstallerModelManage->remove() | JROOT\administrator\components\com_installer\controllers\manage.php:105
7 | InstallerControllerManage->remove() | JROOT\libraries\src\MVC\Controller\BaseController.php:710
8 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\administrator\components\com_installer\installer.php:19
9 | require_once() | JROOT\libraries\src\Component\ComponentHelper.php:382
10 | Joomla\CMS\Component\ComponentHelper::executeComponent() | JROOT\libraries\src\Component\ComponentHelper.php:357
11 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:101
12 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:159
13 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:195
14 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\index.php:51

[lib_osphpexcel.zip](https://github.com/joomla/joomla-cms/files/2388847/lib_osphpexcel.zip)

### System information (as much as possible)
Joomla 3.9 beta

### Additional comments
For some reasons, this command https://github.com/joomla/joomla-cms/blob/staging/plugins/actionlog/joomla/joomla.php#L425, $manifest is null and it causes the issue

Sometime, I also see that install library gets similar issue, too. Mean $manifest after this command is also null https://github.com/joomla/joomla-cms/blob/staging/plugins/actionlog/joomla/joomla.php#L368

The main question here is when install/uninstall extension, do we have a case which this command return null?
[lib_osphpexcel.zip](https://github.com/joomla/joomla-cms/files/2388869/lib_osphpexcel.zip)

```php
$manifest      = $installer->get('manifest');
```

**Comment by ReLater** [comment]
Confirmed for several libraries (with 3.9 nightly of yesterday). I thought that my libraries/packages are buggy somewhere ;-) Main problem was that packages that contain libraries can't be uninstalled completely.

**Comment by alikon** [comment]
should happen not only with libraries.... i've experienced something similar with pkg_weblinks maybe a too old one,  
surely https://github.com/joomla/joomla-cms/blob/staging/plugins/actionlog/joomla/joomla.php#L408
needs more care

**Comment by Quy** [comment]
See PR #22237<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22221">issues.joomla.org/tracker/joomla-cms/22221</a>.</sub>
