### ISSUE TITLE
[3.9] User Action Log [Clear] button issue

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#22234]
### Steps to reproduce the issue
in back-end > Users > User Action Log
click [Export All to CVS]
... you are prompted to open or download the export csv file
open or press cancel

click [Clear] button

### Expected result

The (search) form should be reset

### Actual result

The CVS is experted again and you are promted to download or open the CVS

### System information (as much as possible)

Joomla! 3.9.0-beta Beta [ Amani ] 11-September-2018 12:15 GMT

**Comment by Ruud68** [comment]
same applies for changing sort order and limit<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22234">issues.joomla.org/tracker/joomla-cms/22234</a>.</sub>

**Comment by SharkyKZ** [comment]
This should be fixed with #22155.

**Comment by Quy** [comment]
Please test with [nightly builds](https://developer.joomla.org/nightly-builds.html).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22234">issues.joomla.org/tracker/joomla-cms/22234</a>.</sub>
