### ISSUE TITLE
[3.9] User Action Log export all subject to selected rows

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#22233]
### Steps to reproduce the issue
in Back-end > Users > User Action Log
select subset of logged items
press button [Export **ALL** as CVS]

### Expected result

All entries should be exported

### Actual result

Only selected entries are exported (same as button [Export Selected as CVS])

### System information (as much as possible)
Joomla! 3.9.0-beta Beta [ Amani ] 11-September-2018 12:15 GMT

**Comment by joomdonation** [comment]
This should also be fixed with https://github.com/joomla/joomla-cms/pull/22155

**Comment by Quy** [comment]
Confirmed fix.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22233">issues.joomla.org/tracker/joomla-cms/22233</a>.</sub>

**Comment by Ruud68** [comment]
top, confirmed fixed by: #22155
