### ISSUE TITLE
No values under User Actions Log Options in Profile

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#22238]
### Steps to reproduce the issue
Log in the front end
Click `Your Profile`
See `User Actions Log Options`

### Expected result
Display 1 as Yes
Display selected event(s)

### Actual result
![useractionslogoptions](https://user-images.githubusercontent.com/368084/45704482-d832dd00-bb2b-11e8-8baa-ac56c0fae069.jpg)

### System information (as much as possible)
v3.9

**Comment by SharkyKZ** [comment]
Same is true for fields under `Basic Settings`.

**Comment by alikon** [comment]
please test  #27749

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/27771.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22238">issues.joomla.org/tracker/joomla-cms/22238</a>.</sub>
