### ISSUE TITLE
[3.9] Module Action Logs - Latest exposing info to non superusers

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#22236]
### Steps to reproduce the issue
login to the back-end with a user with manager (or administrator) rights

### Expected result
module Action Logs - Latest should NOT display log entries

### Actual result
module Action Logs - Latest displays log entries
and manager / administrator can even see more log entries by changing the value in the module

### System information (as much as possible)
Joomla! 3.9.0-beta Beta [ Amani ] 11-September-2018 12:15 GMT 

### Additional comments
displaying the User Action logs is limited to super users only, the module Action Logsshould respect that permission rule.![screen shot 2018-09-18 at 12 54 00](https://issues.joomla.org/uploads/1/c4a49614ca45713ab3fae99fec7a708a.jpg)

**Comment by infograf768** [comment]
I guess you have to define yourself the Permissions for that module when creating it.

**Comment by ReLater** [comment]
I cannot confirm this issue with J3.9.0 Nightly https://developer.joomla.org/nightly-builds.html
There is no Latest Actions module to see for Manager(s) or Administrator(s). And they can't change module settings.

I also applied patch https://github.com/joomla/joomla-cms/pull/21983 with PatchTester and used database fix button but I don't know if that pr is needed concerning this issue!

**Comment by mbabker** [comment]
One can still create a new instance of the action logs and privacy requests modules separate from what is in the new install packages (and actually you have to when upgrading from 3.8 or earlier because we aren't arbitrarily adding new dashboard modules to an existing site).  So the modules should probably perform some form of ACL check.

**Comment by Quy** [comment]
Please test PR #22239<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22236">issues.joomla.org/tracker/joomla-cms/22236</a>.</sub>
