### ISSUE TITLE
Finally Replace Platform Version Strings in Libraries

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#22243]
The Platform is a long dead concept, yet its version strings continue to exist in the libraries in `@since` and `@deprecated` tags.  Now that we are talking about CMS 3.x, CMS 4.0, Framework 1.x, and Framework 2.0, having yet another random range of version strings just makes things even more confusing (especially when you get into classes where something has a `@since 11.1` tag with a `@deprecated 4.0` tag).

Lets get these tags back near the "right" values and get rid of some of the confusion.  General rule of thumb that can be used for some bulk updates:

- Platform 11.1: Shipped with CMS 1.7, but encompasses things added to the API all the way back to 1.5 (I think the only still standing 1.0 class is `Joomla\CMS\Version` so there shouldn't be anything you'd need to check on that version branch)
- Platform 11.3: For the most part shipped with CMS 1.7.3, in a couple of cases I found things weren't included until 2.5.0.  I'd just call it all 1.7.3 and be done with it myself, but YMMV.
- Platform 12.x or 13.1: CMS 3.x releases (3.0 would be mostly 12.3 or earlier, IIRC 13.1 was stuff added in 3.1 or 3.2)

**Comment by laoneo** [comment]
Agree

**Comment by csthomas** [comment]
Good idea

**Comment by brianteeman** [comment]
do you want this done for J3 and J4 or just J4?

**Comment by mbabker** [comment]
Both would be nice.  Unless you really think the since versions on https://api.joomla.org/cms-3/classes/Joomla.CMS.Language.LanguageHelper.html make sense.

**Comment by brianteeman** [comment]
Ok - if no one beats me to it I will put it on my todo list for the sprint on saturday

**Comment by brianteeman** [comment]
@mbabker what about 
since 11.1.1 etc
should they just go to 1.7

**Comment by brianteeman** [comment]
I have identified the following platform versions in use with J3. Because they are sol old I am struggling to locate exactly which joomla cms versions they should be changed to. Any help appreciated

- 11.1
- 11.2
- 11.3
- 11.4
- 12.1
- 12.2
- 12.3
- 12.4
- 13.1
- 13.3

**Comment by mbabker** [comment]
11.1/2 - Can be anything 1.7.0 or older
11.3 was merged into 1.7.3
11.4 was merged into 2.5.0
12.1 was merged into 3.0.0
12.2 was merged into 3.0.1
12.3 I don't believe was ever actually merged to the CMS, or if it was at that point we were cherry-picking things
13.1 was merged into 3.2.0

There was never a 13.3 so to do it "right" you'd have to follow the git blame back to the right issue or release.

**Comment by brianteeman** [comment]
there are 1667 instances of 12.3 ;)

**Comment by mbabker** [comment]
I just looked at the version history for the JPlatform class.  It is entirely possible things were cherry-picked and that class never updated, or all the 12.3 things landed with 13.1 in 3.2.0.  Or, people just fudged stuff because who cares.

**Comment by brianteeman** [comment]
This is what I will be changing to

- 11.1 ==> 1.7.0
- 11.2 ==> 1.7.0
- 11.3 ==> 1.7.3
- 11.4 ==> 2.5.0
- 12.1 ==> 3.0.0
- 12.2 ==> 3.0.1
- 12.3 ==> 3.1.4
- 12.4 ==> 3.3.0
- 13.1 ==> 3.2.0
- 13.3 ==> Only ever an @deprecated so 4.0.0

**Comment by brianteeman** [comment]
see #22605 for J3 version

**Comment by brianteeman** [comment]
see #22607 for J4 version
