### ISSUE TITLE
Pagenavigation override not listed in template manager

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#22245]
### Steps to reproduce the issue
Navigate to Extensions -> Templates -> Templates -> [YourTemplate] -> Create Overrides. PageNavigation (https://github.com/joomla/joomla-cms/tree/staging/plugins/content/pagenavigation) does not appear to be listed. At least not where I would have expected it (under plugins/content)

### Expected result
PageNavigation override listed under plugins/content

### Actual result
PageNavigation not listed

**Comment by B3nito** [comment]
Issue confirmed. No plugins are listed in theme overrides. Fields and another plugins missing too.

**Comment by SharkyKZ** [comment]
Test PR #22248 please.

**Comment by ghost** [comment]
closed as having Pull Request #22248
