### ISSUE TITLE
Action log settings wording

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#22247]
In profile page you can select component for notify. 
Headline is saying I can select event. 
But event is "create, edit, delete"

Can I select event?
Then event is missing 

or 

Can I select component?
Then headline is wrong.

![grafik](https://user-images.githubusercontent.com/43232309/45747832-4a2c2480-bc07-11e8-8d89-dd9244304537.png)

**Comment by B3nito** [comment]
And list should only appear when setting is set to yes

**Comment by ReLater** [comment]
> And list should only appear when setting is set to yes

See https://github.com/joomla/joomla-cms/pull/22250

**Comment by ghost** [comment]
closed as having Pull Request #22250

**Comment by ghost** [comment]
@B3nito can you please test #22250?

**Comment by ReLater** [comment]
@franz-wohlkoenig 
Please reopen because the pr solves only comment
> And list should only appear when setting is set to yes

The rest would be a language change.

**Comment by ghost** [comment]
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22247">issues.joomla.org/tracker/joomla-cms/22247</a>.</sub>

**Comment by ReLater** [comment]
I closed  https://github.com/joomla/joomla-cms/pull/22250
See my comments there why. A big mystery...

**Comment by Quy** [comment]
I consider the wording to be fine since events are different actions that can occur for the selected components.
