### ISSUE TITLE
Assign article to two languages

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#22257]
### Is your feature request related to a problem? Please describe.
yes, I have a site with 3 languages, but one language is not translated complete

### Describe the solution you'd like
I want to assign the english articles to two languages until finish with translation or forever

**Comment by infograf768** [comment]
Use the batch copy. Please ask this type of question in the forums.

**Comment by B3nito** [comment]
Sorry but I don't want to copy so much everything and copy of the same content. when I change I have to change all. I think it can be good to assign to more languages to one article. We have all or one but we don't have two languages for one. that is why I have posted for feature request. Maybe it can be improved in Joomla.

**Comment by brianteeman** [comment]
I believe this was part of one of this years gsoc projects but I dont know the status of it 
https://github.com/joomla-projects/gsoc18_automatic_multilingual_association

**Comment by Sandra97** [comment]
A fallback language feature was part of this project but AFAIK this feature has been abandoned.

**Comment by brianteeman** [comment]
the specific feature or the project?

**Comment by Sandra97** [comment]
This specific feature. Lavinia and Wang intend to continue working on the multilingual project

**Comment by infograf768** [comment]
> Sorry but I don't want to copy so much everything and copy of the same content. when I change I have to change all.

Batch copying first categories, including changing language, and then, after filtering by category, batch copying the English articles to the other language(s) and categories, lets you edit/translate the non-translated-yet existing copied articles tagged to the other languages at your rythm, using or not the multilingual associations component.
It goes pretty fast. Just need to structure correctly your categories on the exact model of the English tagged ones.

**Comment by ghost** [comment]
Maybe https://docs.joomla.org/J3.x:Setup_a_Multilingual_Site is a starting Point.

**Comment by B3nito** [comment]
Then I have to maintain two articles all the time when I don't want to translate. not good solution. I know how to set up multilanguage, I work with Joomla since 5 years. I think it can be improved when you dont seeing language as language but as origin or language of visitor. this not mean you have to have all content in the language of visitor.

**Comment by infograf768** [comment]
It may depend on the way you display these articles. Some exxamples.

A. If you use a blog menu item for each content language:
An example of a structure is to create a unique category set to ALL languages.
Then add in this category articles tagged to various languages INCLUDING article tagged to ALL.
When the blog is displayed it will show the articles tagged to the content language in use + the ones tagged to ALL.

B. If you use a featured menu item for each content language:
Also create a category tagged to ALL languages, among these tagged to a specific language.
Add in that category all articles which should display for every language, themseleves tagged to ALL.

C. Another way is to tag all your categories to ALL languages and add articles tagged to any language + some tagged to ALL in each category.
This last one lets you keep any number of specific categories.

Just make sure the menu items for each content language are set to display the same category.

The problem with that is that you can't associate items set to ALL, whether they are categories or articles. You would have to only associate items tagged to a specific language, including menu items.

If none of these satisfies your need, then you will have to wait someone creates the code to allow what you want, or propose it yourself.

**Comment by B3nito** [comment]
I am not good in coding :( I am more a Template Developer...

**Comment by brianteeman** [comment]
This is a very old request for a new feature in Joomla 3. As there has been no interest in providing any code to satisfy this and we are not accepting any new features in Joomla 3 I recommend that it is closed.

**Comment by alikon** [comment]
Closed as stated above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22257">issues.joomla.org/tracker/joomla-cms/22257</a>.</sub>
