### ISSUE TITLE
The tooltip of the page navigation is displayed as html.

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#22256]
### Steps to reproduce the issue

Open a page with a **page navigation** (see buttons Prev - Next).
See also issue #20177.

### Expected result

The **tooltip** of the page navigation is loaded with the bootstrap tooltip code.
See the image below. 

### Actual result

The tooltip of the page navigation is displayed as html.
Because the following script file is not loaded:
```<script src=".../Joomla/media/jui/js/bootstrap.min.js?xxxxx"></script>```

*See image: bootstrap is not loaded*
![screen shot 2018-09-19 at 16 13 32](https://issues.joomla.org/uploads/1/c0f03e85ea5cbc0565e3b64507878a2c.png)

### System information (as much as possible)

* Joomla! 3.9.0-alpha2-dev Development
* PHP 7.1.20

### Additional comments

Possible solution:
Add ```JHtml::_('bootstrap.tooltip');``` into the file ```...\plugins\content\pagenavigation\tmpl\default.php```

*Image: bootstrap is loaded*
![screen shot 2018-09-19 at 16 13 34](https://issues.joomla.org/uploads/1/b85d9adb3c29a6c925bcda4b2ca007e4.png)

**Comment by SharkyKZ** [comment]
The fix is correct. Can you submit a pull request?

**Comment by ghost** [comment]
@sandewt can you please provide a Pull Request?

**Comment by ghost** [comment]
@SharkyKZ can you do the Pull Request?

**Comment by SharkyKZ** [comment]
Test PR #24203 please.

**Comment by ghost** [comment]
closed as having Pull Request #24203 

Thanks @SharkyKZ
