### ISSUE TITLE
Language Override bug in parser handling values with quotes

### ISSUE THREAD

**Issue by biltongandpotroast** [joomla/joomla-cms#22251]
### Steps to reproduce the issue

Add any or all of the folowing overrides to file /language/overrides/en-GB.override.ini by editing it over ftp using an application like FileZilla or cPanel File Manager.

COM_VIRTUEMART_CART_NO_SHIPPING_METHOD_PUBLIC="We are sorry, no delivery options are available for your country and type of products selected. View <a href=\"index.php?option=com_content&view=article&id=53&Itemid=1161&tmpl=component#delivery-restrictions\" class=\"jcepopup\" data-mediabox-height=\"600\" data-mediabox-width=\"800\">Delivery Restrictions</a>."

COM_VIRTUEMART_REG_COMPLETE="<div class=\"componentheading\">Registration complete, these details will be used at checkout. Please continue shopping.</div>"

PLG_SYSTEM_VPFRAMEWORK_COOKIE_CONSENT_MESSAGE="This website uses cookies to ensure you get the best experience on our website. Please read our <a href=\"https://www.trendco.co.uk/terms-and-conditions-of-use\" target=\"_blank\">website Terms & Conditions of Use</a> and <a href=\"https://www.trendco.co.uk/privacy-policy-security#cookies\" target=\"_blank\">Privacy Policy</a> for more information."

### Expected result

These new values should be appended to the language file.

### Actual result

All values of the language file are removed except for the following:

MOD_LOGIN_VALUE_USERNAME 	Username/Email
JLIB_LOGIN_AUTHENTICATE 	Username/email and password do not match or you do not have an account yet.
JGLOBAL_AUTH_NO_USER 	Username/email and password do not match or you do not have an account yet.
JGLOBAL_AUTH_INVALID_PASS 	Username/email and password do not match or you do not have an account yet.
COM_VIRTUEMART_USERNAME 	Username/Email

### System information (as much as possible)

Joomla 3.8.12
PHP 7.0.31

### Additional comments

These entries can be added individually using the Joomla Admin->Languages: Overrides->New function but I'm not convinced this always works (probably when "" are not escaped).

When the values are lost, it is a big task restoring the previous values one by one in this way. The quicker alternative is to edit the file using ftp and pasting all values in from a backup file but then this fails when you include values with "" so they have to be done seperately as explained above.

**Comment by infograf768** [comment]
> These entries can be added individually using the Joomla Admin->Languages: Overrides->New function but I'm not convinced this always works (probably when "" are not escaped).

Joomla automatically escapes doublequotes in the values when overrides are created this way.
It works perfectly, The doublequotes should never be entered as escaped in the value.

<img width="282" alt="screen shot 2018-09-19 at 15 55 56" src="https://user-images.githubusercontent.com/869724/45757818-8de15700-bc24-11e8-9986-f9322e971fda.png">

will give
`COM_VIRTUEMART_REG_COMPLETE="<div class=\"componentheading\" />Registration complete, these details will be used at checkout. Please continue shopping."`

When you edit directly the file xx-XX.override.ini, the escape should be present
Your example IS wrong

`PLG_SYSTEM_VPFRAMEWORK_COOKIE_CONSENT_MESSAGE="This website uses cookies to ensure you get the best experience on our website. Please read our <a href="https://www.trendco.co.uk/terms-and-conditions-of-use\" target="_blank">website Terms & Conditions of Use and <a href="https://www.trendco.co.uk/privacy-policy-security#cookies\" target="_blank">Privacy Policy for more information."`

the escape sign is only entered for 2 closing doublequotes.

It should be
`PLG_SYSTEM_VPFRAMEWORK_COOKIE_CONSENT_MESSAGE="This website uses cookies to ensure you get the best experience on our website. Please read our <a href=\"https://www.trendco.co.uk/terms-and-conditions-of-use\" target=\"_blank\">website Terms & Conditions of Use and <a href=\"https://www.trendco.co.uk/privacy-policy-security#cookies\" target=\"_blank\">Privacy Policy for more information."`

Then, it is easy to check that override displays correctly in the override manager (without the escape signs) and no problem at all...

No bug here at all.

**Comment by biltongandpotroast** [comment]
I have just edited the override value MOD_LOGIN_VALUE_USERNAME="Email/Email" in Joomla Admin->Language Overrides, changing it to MOD_LOGIN_VALUE_USERNAME="Username / Email" and this resulted in the overrides becoming corrupted same as Actual Result reported above.

I have attached a backup of en-GB.override taken before this occurred.[en-GB.override - 20180919 - backup after problem resolved.txt](https://issues.joomla.org/uploads/1/716f47816b71965fd641b22e89e16baa.txt)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22251">issues.joomla.org/tracker/joomla-cms/22251</a>.</sub>

**Comment by infograf768** [comment]
I have absolutely no issue using your file and then modifying that value.

<img width="1225" alt="screen shot 2018-09-19 at 17 47 56" src="https://user-images.githubusercontent.com/869724/45765037-57133d00-bc34-11e8-96c0-6e2f1bbc7468.png">

Can you attach here the "corrupted" file?

**Comment by biltongandpotroast** [comment]
I have just repeated this with same result.

Steps:

1. Edit the file /language/overrides/en-GB.override.ini and delete contents, replace with contents in attached file1.txt. This file excludes the 3 values containing escaped quotes.
2. Check Overrides in Joomla Admin - they look good.
3. In Joomla Admin, add the 3 overrides from file2.txt, removing the escaped quotes by changing the `\"` with `"`.
4. 2. Check Overrides in Joomla Admin - they look good.
5. Edit any other override in Joomla Admin.
6. Check Overrides in Joomla Admin - all gone except for those in file3.txt. Where do these come from?

[file2.txt](https://issues.joomla.org/uploads/1/0f3e308ee7ca7d1831b5b8e8d328047d.txt)[file3.txt](https://issues.joomla.org/uploads/1/b22833699b5cb29675013bf6ca3df426.txt)[file1.txt](https://issues.joomla.org/uploads/1/b70d11cf54b50ee451e1e5e4a2e43eb7.txt)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22251">issues.joomla.org/tracker/joomla-cms/22251</a>.</sub>

**Comment by ReLater** [comment]
I can't replicate this issue wit nightly 3.9 of today. I followed all steps.
Did you clear the cache in overrides view? Maybe a db issue?
Did you check the filter setting?

**Comment by infograf768** [comment]
Absolutely no problem here. No idea what happens in your case.
You may have to totally replace the file on your host by a new one.

In any case, this is not a Joomla bug. Closing Issue.

**Comment by biltongandpotroast** [comment]
fyi

I have been using Clear Cache throughout in trying to resolve this problem and checking the contents of table _overrider accordingly. It is currently empty with all overrides restored as per above steps.

I am familiar with the filter setting, Site / Administrator. I am only havving a problem with Site overrides.

File permissions have been checked and are correct.

I have checked the Joomla core files in /administrator/components/com_languages against the same in a new Joomla 3.8.12 package and they are all identical. There are no admin template overrides.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22251">issues.joomla.org/tracker/joomla-cms/22251</a>.</sub>
