### ISSUE TITLE
[3.9] action logs notifications. showon attribute for field logs_notification_extensions ignored in profile edit

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#22262]
### Steps to reproduce the issue
- Newly installed nightly 3.9 of today.
- Apply this change https://github.com/joomla/joomla-cms/pull/22250/files in file `plugins/system/actionlogs/forms/actionlogs.xml`
- Login as a Super User in BE.
- Go into your account via Users > Manage > click your account to edit it
(com_users&view=user)

- Go into tabulator `User Actions Log Options`
Check that `showon` attribute works as expected like shown in images of first comment https://github.com/joomla/joomla-cms/pull/22250#issue-216625164

- Then go into "Edit Account" (upper right corner in Isis) and check that showon **doesn't** work like shown in images of first comment.
(com_admin&view=profile)

Both views use the same xml file above. But when used in "Edit Account" the field doesn't load `showon` scripts, doesn't set `data-showon` attribute.

**Comment by SharkyKZ** [comment]
Test PR #22277 please.

**Comment by ghost** [comment]
closed as having Pull Request #22277
