### ISSUE TITLE
[3.9] No filter options in Language Overrides

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#22261]
### Steps to reproduce the issue
Go to `Extensions > Language(s) > Overrides`
Click `New` button

Get the following error due to no filter box.

```
Warning
To create a new override, please first select a language and client.
```

### Expected result
![overrides-filter](https://user-images.githubusercontent.com/368084/45769886-c1f15380-bbf5-11e8-8ae9-d2b420cfdec8.jpg)

### Actual result
![overrides-nofilter](https://user-images.githubusercontent.com/368084/45769899-cae22500-bbf5-11e8-9b2d-fca445362fc3.jpg)

### System information (as much as possible)
v3.9

**Comment by mbabker** [comment]
The layout was changed to use search tools.

![screen shot 2018-09-19 at 12 25 03 pm](https://user-images.githubusercontent.com/368545/45770106-194bef80-bc07-11e8-834a-07608857242e.png)

**Comment by Quy** [comment]
I don't have a `Search Tools` button. This is the nightly build 3.9,

![overrides-searchtools](https://user-images.githubusercontent.com/368084/45770472-514b3680-bbf7-11e8-849a-508ae06ccde8.jpg)

**Comment by ghost** [comment]
Issue confirmed, no Search Tools are shown.
### System information
- 3.9.0-beta2-dev
- Template: Protostar
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by mbabker** [comment]
Then something's being stripped at packaging or deleted on update because it's there when running from git.

**Comment by ReLater** [comment]
See pr https://github.com/joomla/joomla-cms/pull/22264

**Comment by AlexanderSk** [comment]
Hello, i just noticed this issue on 3.9 Stable can you please check?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22261">issues.joomla.org/tracker/joomla-cms/22261</a>.</sub>

**Comment by AlexanderSk** [comment]
![screen shot 2018-10-31 at 10 14 01](https://issues.joomla.org/uploads/1/49d8d7572d095b4c06ff9268bf28fbfd.png) Here is the Print Screen also. Thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22261">issues.joomla.org/tracker/joomla-cms/22261</a>.</sub>

**Comment by ghost** [comment]
@AlexanderSk can you please open a new Issue as Comments on closed ones didn't get much Notice.

https://docs.joomla.org/Filing_bugs_and_issues#Reporting_bugs

Can't confirm the reported Issue.
### System information
- 3.9
- Template: Protostar
- macOS Sierra, 10.13.6
- Firefox 63 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by infograf768** [comment]
@AlexanderSk 
See https://github.com/joomla/joomla-cms/pull/22264

This means that your update did not go well as the `com_languages/joomla/searchtools/default/bar.php` file was deleted although script.php was modified to not delete it.
Try to re-update 3.9.0 with the joomlaupdate component

**Comment by AlexanderSk** [comment]
Done -> https://issues.joomla.org/tracker/joomla-cms/22885 Thank you!

**Comment by AlexanderSk** [comment]
Did that just now did not work :S but please lets go to the new topic :)
