### ISSUE TITLE
[3.9] Latest Actions Module - Constant instead of Value for T&C

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-cms#22267]
When a use is registerating to a site and accept the Terms & Conditions, the latest actions module displays the constant instead of the value.
![1](https://user-images.githubusercontent.com/4682328/45797182-97aa9f00-bca4-11e8-9793-82289585b30b.png)

Note that the value is displayed on the User Actions Log Screen
![2](https://user-images.githubusercontent.com/4682328/45797184-9bd6bc80-bca4-11e8-808b-a3c633f6f273.png)

**Comment by ReLater** [comment]
I don't know if this pr will be accepted but translates the language string https://github.com/joomla/joomla-cms/pull/22282

**Comment by Sandra97** [comment]
And  the result is better for sure ;)
![index](https://user-images.githubusercontent.com/4682328/45831350-67dcb500-bcff-11e8-91e4-f34f65289e60.png)

**Comment by ghost** [comment]
closed as having Pull Request #22282
