### ISSUE TITLE
Joomla 3.9 display module information

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#22269]
Hello, is it possible to armonize the format of information such as the number of users and article in the information module of the site
![screen shot 2018-09-20 at 08 41 23](https://issues.joomla.org/uploads/1/743cea28109d1b141d942ea3216f2b4e.jpg)

**Comment by brianteeman** [comment]
Sorry I don't see from your image what the problem is

Site information says there are 7 articles on the site
The module is showing the 5 most popular articles on the site

**Comment by Magnytu2** [comment]
Sorry, but it's just for the size of the button, way too square.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22269">issues.joomla.org/tracker/joomla-cms/22269</a>.</sub>

**Comment by Fedik** [comment]
@brianteeman I think that @Magnytu2 talking about a styling issue, 
the numbers style looks different, not "harmonized"

**Comment by brianteeman** [comment]
They look different because they are different. 
The number style on the article count in the popular articles module is just a style
The number on the article count in the system info module is now a button

**Comment by brianteeman** [comment]
For reference the code in the stats module was changed to make these buttons here https://github.com/joomla/joomla-cms/pull/13396

**Comment by ghost** [comment]
closed as having Pull Request #22276.
@Magnytu2 can you please test PR?
