### ISSUE TITLE
Empty fields after update - missing code in ExtensionHelper.php

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#22279]
### Steps to reproduce the issue

Update Joomla 3.8.12 to 3.9.0.
See the **Extensions manager: Manage**
*The following fields are empty from the Privacy - Action Logs plugin: Version, Date and Author.*
See the image below.

### Expected result

*The concerning fields are NOT empty.*

Solution:
See file `...\Joomla\libraries\src\Extension\ExtensionHelper.php`
Add some code, line: 208 - ...
```
// Core plugin extensions - privacy
array('plugin', 'actionlogs', 'privacy', 0), // missing rule
array('plugin', 'contact', 'privacy', 0),
And so on
```

### Actual result

*The concerning fields are empty.*

The manifest cache data isn't placed into the update SQL statement.
See file `...\Joomla\libraries\src\Extension\ExtensionHelper.php`
Missing code, line: 208 - ...
```
// Core plugin extensions - privacy
array('plugin', 'contact', 'privacy', 0),
array('plugin', 'content', 'privacy', 0),
array('plugin', 'message', 'privacy', 0),
array('plugin', 'user', 'privacy', 0),
```
### System information (as much as possible)

See comparable issues #20013 and #20038

### Additional comments

Joomla! 3.9.0-beta2 Beta 
Php 7.1.20

![screen shot 2018-09-20 at 13 45 40](https://issues.joomla.org/uploads/1/f7e89ae01ef982f31146df5ba3ac18ae.png)

**Comment by ghost** [comment]
Can one please Comment as the Issue is openend for a Week having Status "New"? Thanks in advance.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22279">issues.joomla.org/tracker/joomla-cms/22279</a>.</sub>

**Comment by infograf768** [comment]
Looks like this has been solved in present staging.
The code is present in the ExtensionHelper.
Just did a Refresh cache

**Comment by ghost** [comment]
thanks for Comment @infograf768.

@sandewt if Issue is solved can you please close it?

**Comment by sandewt** [comment]
>The code is present in the ExtensionHelper.

@infograf768, it is somewhat confusing, there are two actionlogs plugins (a privacy and a system).

I have updated to Joomla! 3.9.0-beta3 Beta. The concerning fields are know not empty. So it seems to be OK. See the image below.

But I cannot find the code ``array('plugin', 'actionlogs', 'privacy', 0)`` in the ExtensionHelper.

What code do you mean?

(Note. The code ``array('plugin', 'actionlogs', 'system', 0)`` is present in line 231.)

![fields-1a](https://user-images.githubusercontent.com/9271775/46154339-3de24000-c275-11e8-80eb-6e7d5f3b5c9e.png)

**Comment by infograf768** [comment]
Sorry, did not understand your post.
We do have
https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Extension/ExtensionHelper.php#L208-L212

But it looks like indeed we miss
('plugin', 'actionlogs', 'privacy', 0) in the ExtensionHelper.

Will make PR now.

**Comment by infograf768** [comment]
see https://github.com/joomla/joomla-cms/pull/22409
