### ISSUE TITLE
No Batch Process possible when in all menu items

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#22284]
### Steps to reproduce the issue
Select all menu items to show
click checkbox of items
click on badgeprocess

<img width="1017" alt="grafik" src="https://user-images.githubusercontent.com/43232309/45833770-cad14a80-bd05-11e8-8162-1859eeb2e048.png">

Badge process not possible for items of different menus
<img width="890" alt="grafik" src="https://user-images.githubusercontent.com/43232309/45833815-ea687300-bd05-11e8-818c-bd7b58fdb138.png">

### Expected result
Badge process should working independant of menu

### Actual result
Not possible
and when you edit item and close from this view then you are not in the all menu item view, you have menu selected.

### System information (as much as possible)
Current Joomla 3.8.12

**Comment by brianteeman** [comment]
There are some very sensible reasons why this is not possible and why you get the message.

**Comment by ghost** [comment]
@brianteeman i struggled Yesterday also about this Behaviour translating a doc so i'm interested whats the sensible Reasons for?

**Comment by brianteeman** [comment]
iirc it is because we can't keep the tree or check the alias are unique - best to look ata the pr that introduced the feature

**Comment by ghost** [comment]
Changed Title Badge > Batch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22284">issues.joomla.org/tracker/joomla-cms/22284</a>.</sub>

**Comment by ghost** [comment]
thanks @brianteeman for your Help. Its true, i can search for the PR by myself.

Closing Issue by Explanation above.
