### ISSUE TITLE
Preview module positions needing language strings

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#22304]
### Steps to reproduce the issue
Module position preview using static text for **Position** and **Style**. I suspect these should be language strings?

### Expected result
Language strings for **Position** and **Style**

### Actual result
https://github.com/joomla/joomla-cms/blob/staging/templates/system/html/modules.php#L147

**Comment by brianteeman** [comment]
If those strings are translatable in the UI (which I believe they are) then yes they should be language strings

**Comment by infograf768** [comment]
@ciar4n 
Will do patch if you have not yet.
I will use
JGLOBAL_PREVIEW_POSITION="Position: "
JGLOBAL_PREVIEW_STYLE="Style: "

in en-GB.ini frontend

**Comment by ciar4n** [comment]
Please go for it. I meant to do it after #22272 got merged but duly forgot about it!

Thank you.

**Comment by infograf768** [comment]
please test https://github.com/joomla/joomla-cms/pull/22365
