### ISSUE TITLE
One User Session

### ISSUE THREAD

**Issue by MauriceTerer** [joomla/joomla-cms#22306]
### Is your feature request related to a problem? Please describe.
Currently in Joomla users can login concurrently using the same username 

### Describe the solution you'd like
i would like to limit one user per session so that a user cant login using another computer or browser when already logged in. I want to achieve this without a plugin

**Comment by ReLater** [comment]
> I want to achieve this without a plugin

Why? I would say that's the job of a plugin.

And, by the way, I don't see a reliable way to check if a user just forgot to log out correctly. Then the log in from another computer/browser will be blocked at least until the next session timeout. Maybe longer.

And please describe a common use case for this issue. I can't imagine one.

**Comment by Fedik** [comment]
> And please describe a common use case for this issue. I can't imagine one.

such thing often used on paid/per subscription services

>  I don't see a reliable way to check if a user just forgot to log out correctly

that easy, when user logged in then all existing session for same user "logout"

I think it a job for a plugin developer.

**Comment by ReLater** [comment]
> that easy, when user logged in then all existing session for same user "logout"

Yes, that's easy. Kicking all logged in users out if somebody tries to login with same credentials/userId.
But @MauriceTerer said:

> so that a user cant login using another computer or browser when already logged in.

**Comment by Fedik** [comment]
then I misunderstood

**Comment by brianteeman** [comment]
It has been more than one month since the request for more information from the original poster without reply. I am closing this. It can always be reopened if required.
