### ISSUE TITLE
Class 'Joomla\Language\Language' not found in Joomla\Filter\OutputFilter::stringUrlSafe

### ISSUE THREAD

**Issue by jlainezs** [joomla/joomla-cms#22316]
### Steps to reproduce the issue

- In a component code do call \Joomla\Filter\OutputFilter::stringUrlSafe($someText)

### Expected result

- Get the url safe version of text passed to the function.

### Actual result

- The response to the call is a **Class 'Joomla\Language\Language' not found** error

### System information (as much as possible)

- Joomla! 3.8.12 Stable [ Amani ] 28-August-2018 14:00 GMT
- English, Catalan and Spanish languages installed
- Multilanguage content disabled (not working on multilanguage yet)
- PHP 7.1.20
- Ubuntu Trusty 64 in a Vagrant box over Virtual Box. BTW, the folder where the site live is shared with a Windows 10 system.

### Additional comments

The **Language** class is defined in the namespace \Joomla\CMS\Language instead of \Joomla\Language\Language as it is written in the **OutputFilter** class. However, changing the **use** of line 11 in this class into **Joola\CMS\Language\Language** raises the runtime error **Too few arguments to function Joomla\CMS\Language\Language::getInstance(), 0 passed in /var/www/html/libraries/vendor/joomla/filter/src/OutputFilter.php on line 100 and at least 1 expected**

**Comment by mbabker** [comment]
You should be using the `Joomla\CMS\Filter\OutputFilter` class, not the `Joomla\Filter\OutputFilter` class.

**Comment by ghost** [comment]
@jlainezs if the Comment above solve the Issue please close it, thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22316">issues.joomla.org/tracker/joomla-cms/22316</a>.</sub>

**Comment by jlainezs** [comment]
Change to used class to the one suggested solved the issue.
Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22316">issues.joomla.org/tracker/joomla-cms/22316</a>.</sub>
