### ISSUE TITLE
[3.9] Reminder. Actions log. Remove com_cache from loggable_extensions

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#22312]
### Steps to reproduce the issue
If component `Cache` is activated in com_actionlogs settings (`Events To Log`) nothing happens. No logging of com_cache actions like `delete`, `purge` and so on.

**Comment by mbabker** [comment]
1) Is there really anything pertinent to log here?  Do we really need a "Michael cleared the site cache" message, especially when that is more often than not going to cycle itself out through automated means and not user action?

2) Does com_cache actually trigger relevant plugin events to do anything useful with these actions?

**Comment by ReLater** [comment]
1.) I myself say "No".
2.) No. One would have to add the logging to the controller or model at the moment or would need to establish triggers/events.

I opened this issue because component "Cache" is shown in the actions log settings. And questions will occur after 3.9 stable is released.

**Comment by mbabker** [comment]
Then to me the answer is to just drop com_cache out of that setting.

**Comment by ReLater** [comment]
I'm not able to do that because of sql update scripts that have to be written, too.
I changed the title of this issue. Maybe someone finds the time to do that. If not, who cares, and I will close it in some weeks.

**Comment by Quy** [comment]
This is a new feature. It is not necessary to write an update sql. Right?

**Comment by ReLater** [comment]
I'm not sure. We have already 3.9 sql update scripts that write loggable_extensions entries and things. I don't know if they are used in stable release or combined or just can be changed before the stable ...

**Comment by richard67** [comment]
@ReLater As far as I know the sql schema updates will not be combined. They will be used in stable release. Before release candidate it should be sufficient just to change the existing update sql scripts, after that it might be necessary to add new ones.
@mbabker can you confirm that?
@ReLater If you need help with the update scripts, maybe me or @alikon can help.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22312">issues.joomla.org/tracker/joomla-cms/22312</a>.</sub>
