### ISSUE TITLE
[4.0] Table Options Button Dropdown Label

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#22311]
### What needs to be fixed
In any lists view of core components where the layout `joomla.searchtools.default` is visible, there is a tool dropdown to filter the content. The button label is set to **Table Options** I know the lists is a table but the button label should not be technically in accordance to what element is used, should it be?

### Why this should be fixed
It would make more sense to document or point people to go to **Filter Options** and set the filter, rather than go to Table Options.

![joomla4_tableoptions](https://user-images.githubusercontent.com/1373815/45906886-a54a4c80-bdaa-11e8-9571-2626b116bd2f.png)

**Comment by brianteeman** [comment]
It is not just filtering it is also sorting

**Comment by frogydiak** [comment]
:D Well, IMO regardless, that option is more of a filter than ordering.

**Comment by chmst** [comment]
Table Options sounds strange for me too. From a user's point of view I would say that it manipulates the content of the screen. 
Maybe "Content Options"? We should aks here users who are not developers :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22311">issues.joomla.org/tracker/joomla-cms/22311</a>.</sub>

**Comment by ggppdk** [comment]
Personally , i like the organization in the following link

https://github.com/joomla/joomla-cms/issues/22314#issuecomment-423725569

it is understandable and clean looking

**Comment by frogydiak** [comment]
@ggppdk I agree, splitting the function into two like in [https://github.com/joomla/joomla-cms/issues/22314#issuecomment-423725569](url) makes more sense.

**Comment by hardik-codes** [comment]
@brianteeman does this issue needs to be addressed?

**Comment by ghost** [comment]
Please add Label "J4 Backend Template".

**Comment by brianteeman** [comment]
This was resolved in #24022 and can be closed

**Comment by roland-d** [comment]
Closed as requested.
