### ISSUE TITLE
[4.0] Search Toolbar Aligned Right

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#22314]
### What needs to be fixed
Is there any reason why the search box in layout `joomla.searchtools.default` is aligned right? Is this something that is standard in UK or Europe? 

![joomla4_search_alignedright](https://user-images.githubusercontent.com/1373815/45907761-0cb5cb80-bdae-11e8-828a-b059ca01e89b.png)

### Why this should be fixed
Since we read from Left to right, having an empty space in the left looks awkward compared to this:

![joomla4_searchtool_left_aligned](https://user-images.githubusercontent.com/1373815/45907801-45ee3b80-bdae-11e8-8362-1f9b40b86cae.png)

### Side Effects expected
In com_menu, the way `joomla.searchtools.default` was coded, it will break the layout when showing custom filter field but I think it can easily be fixed with the  Filter dropdown Button on its own line of code and not in the same layout with the search box.

Here's a mock up of filters in one place:
![joomla4_with_customfilter](https://user-images.githubusercontent.com/1373815/45907981-1e4ba300-bdaf-11e8-9c84-a7aff5158865.png)

**Comment by brianteeman** [comment]
Nothing to do with uk or europe

Read https://uxmag.com/articles/usability-tip-dont-make-me-search-for-search

Or the book don't make me think

**Comment by frogydiak** [comment]
@brianteeman In a site header, I agree that search is usually found on the right side but searchtools search box is a toolbar (not a page header). Based on the URL you provided above: 

![usability-tips-dont-make-me-search-meetup](https://user-images.githubusercontent.com/1373815/45911104-0599b800-bdc4-11e8-8cb1-c2c07539fb3c.png)

Notice the toolbar in the middle with a gray background, the placement of search box is on the left side and buttons on the right. It creates a balance in UI. Take a look at the current layout of searchtools where the searchbox is in the right.

![joomla4_search_alignedright](https://user-images.githubusercontent.com/1373815/45911175-03842900-bdc5-11e8-9aff-ffed478fc563.png)

I don't know, it just feels like something is missing in the UI.

**Comment by brianteeman** [comment]
I am not a designer. I just took the time to reply to you.

**Comment by ciar4n** [comment]
Having used J4 for some time, I did find myself missing the filters/search at the top left of the table. I think it was a mistake moving them to the top right and hiding them behind a dropdown (my own doing).

**Comment by brianteeman** [comment]
I've been using it for a long time now as well. The filters were always behind a dropdown so I dont mind it here and I never use the sort dropdowns I just click on the column headers (which will be more obvious when my pr is merged)

As for the position of the search box - I really dont mind it - I think its just a case of muscle memory and I am far more used to looking for a search box on the right hand side as thats a far more common design

**Comment by brianteeman** [comment]
I do note however that the design proposed by @coolcat-creations calls for the dropdown to be split into two again and for the action buttons to be on the same row

![screeshot of proposed screen](https://user-images.githubusercontent.com/828371/40283295-5511becc-5c7c-11e8-9dd3-f4c7ee7dc4f6.png)

**Comment by ciar4n** [comment]
> hiding them behind a dropdown

What I meant really is away from the J3 searchtools, which I believe was fashioned on Google (search for something -> click 'Tools') and changing them to the more traditional dropdown. But as you say, this is maybe just muscle memory on my part (I use searchtools a lot).

**Comment by brianteeman** [comment]
yes it was modelled on google

**Comment by frogydiak** [comment]
If the toolbar should be moved into one bar (like in the screenshot [above](https://github.com/joomla/joomla-cms/issues/22314#issuecomment-423725569)) then I guess it would make more sense for the search box to be aligned right. @ciar4n is right, I guess I use searchtools a lot also in J3 and it is a muscle memory for me to look for searchbox on the left side but J4 placement is on the right and blank space on the left of the bar... in most views.

**Comment by ggppdk** [comment]
Also in smaller screens can the text of buttons

'Filtering options' 
'List options' 

be auto-hidden ? leaving only the icons ?

**Comment by coolcat-creations** [comment]
> I do note however that the design proposed by @coolcat-creations calls for the dropdown to be split into two again and for the action buttons to be on the same row
> 
> ![screeshot of proposed screen](https://user-images.githubusercontent.com/828371/40283295-5511becc-5c7c-11e8-9dd3-f4c7ee7dc4f6.png)

It's not intended to be split, I described it in the JCM Article that it's intended to have options to display certain columns or not. It does not have to have such a big button but every user has different data which is important for them, so the backend gets more overview if the user is able to customize the table columns. For example rating is maybe not important to some editors but rather the language. For some others the autor and the title is very important but the creation date does not matter at all. It's about decluttering the backend for everyones own needs. See screen: https://coolcat-creations.com/joomla/#/screens/266934595 The most reasonable position for this settings would be probably a cog icon next to the table colums instead of the seperate button I proposed, since the settings are not changed regulary and don't need that much attention.

**Comment by ghost** [comment]
Please add Label "J4 Backend Template".

**Comment by alikon** [comment]
related to the old template, open a new issue if needed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22314">issues.joomla.org/tracker/joomla-cms/22314</a>.</sub>
