### ISSUE TITLE
No fallback for language content override ini strings

### ISSUE THREAD

**Issue by julienV** [joomla/joomla-cms#22329]
### Steps to reproduce the issue
Use in a view/module/plugin/etc... a language string that is only defined in language content override.
For example, in a template override com_content/article/default.php
Only create the language string in the default language of the site.
then, try to switch language in frontend.

### Expected result
As we didn't define the language string in the other language content override, we expect it to fallback to the default language override

### Actual result
It displays the string key instead

### System information (as much as possible)
joomla 3.8.12

**Comment by ghost** [comment]
closed as having Pull Request #22330
