### ISSUE TITLE
[4.0] [RFC] Installation customise

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#22321]
### Steps to reproduce the issue
Install a new Joomla 4.0 until you come to the last step where you get the button "customise". 
The whole process is hard to describe and hard to explain and has several bugs. 

### Expected result
In the customise box I expect two (or more) buttons: 
Install Languages / Install Sample Data / Install Multilingual Site 
As soon as multilingual or sapledate is done, these buttons are disabled.

And I expect that sample data use the user_id of an existing user.

Alternative: No sampledata at all. They are on the cpanel.

### Actual result
This button "customise" opens a selection of languages to install.
If you scroll down the whole list you get two buttons "next" and "skip". 

Do NOT select a language and press "next": You come back to "customise" which somehow is not "next".

Select one or more languages and press "next": Languages are installed and during installation the "Do you want sample data?" is visible behind the background, then it all goes back to "customise".

Here you can again click customise and come to the languages .. scroll down to end of screen and click "skip"  now installation of sample data is possible and it all goes back to customise. 
The user_id in sample data is set to a random value, which means that every action I made now in articles is accompagnied by the alert "user does not exist".

It is possible to repeat this and start sample data again - which throws errors "duplicate ID". 

### Additional comments

**Comment by brianteeman** [comment]
Can you look through this filtered list of installer bugs - pretty sure this is all in there but parts may not be

https://github.com/joomla/joomla-cms/projects/15

**Comment by chmst** [comment]
Indeed, this issue also requqires to remove the installation of sample data installation. https://issues.joomla.org/tracker/joomla-cms/20262

**Comment by Quy** [comment]
Duplicate #22907?

**Comment by Quy** [comment]
@chmst Sample installation to be removed in #25828. 

Please close if this issue is no longer valid.
