### ISSUE TITLE
template modals don't resize if content is higher then 400px;

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#22331]
### What needs to be fixed
.modal-body has a hard set max-height: 400px; which causes content to be hidden if that content is higher then 400px;

### Why this should be fixed
This would allow more fluid sizing of modals.

### How would you fix it
all content of .modal-body to set the height.

### Side Effects expected
js for ios layout may no longer be necessary.

### to test.
go to template manager and click on beez 3 template preview image.  
Using inspector change height of the image to 500px;
Contents will overflow...
![show-overflow](https://user-images.githubusercontent.com/1850089/45922277-f03c9080-be8c-11e8-84ea-6f519161c2ca.PNG)

apply patch.
now modal resizes to keep contents visible.
![image](https://user-images.githubusercontent.com/1850089/45922289-24b04c80-be8d-11e8-8690-5f1d85fba242.png)

**Comment by ghost** [comment]
closed as having Pull Request #22332
