### ISSUE TITLE
[Privacy] Possible issue when accepting policy in frontend

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#22334]
Titled this issue as "possible" because I may have forgotten a setting somewhere.

### Steps to reproduce the issue
Login frontend. I did that as superuser
Fill profile and **Agree to policy**

Submit.

we get

<img width="765" alt="screen shot 2018-09-23 at 10 00 04" src="https://user-images.githubusercontent.com/869724/45925540-c8ded580-bf17-11e8-918d-f76c6f2f5676.png">

and I agree is back to `No`

<img width="740" alt="screen shot 2018-09-23 at 10 00 24" src="https://user-images.githubusercontent.com/869724/45925542-d7c58800-bf17-11e8-91c9-bcc2e5ed9ea2.png">

Note: I did receive the mail stating the last action
![screen shot 2018-09-23 at 10 07 26](https://user-images.githubusercontent.com/869724/45925576-82d64180-bf18-11e8-90e3-2da4e449676b.png)

As this did not work, I can't submit a request for informations from the frontend menu item

**Comment by SharkyKZ** [comment]
Maybe duplicate of #22212?

**Comment by Sandra97** [comment]
I can't reproduce, it works as expected for me.
If it's not a fresh install, did you apply [this change](https://github.com/joomla/joomla-cms/pull/22196) in your #__privacy_consent table?

**Comment by infograf768** [comment]
OK, closing as indeed using varchar 255 solves that precise issue.
Thanks for hint.
