### ISSUE TITLE
[4.0] Nightly build. New installation. "It looks like you are trying to run Joomla! from our git repository."

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#22338]
### Steps to reproduce the issue
- Several reports and I tried it, too:
Try to install  Nightly Build Sunday, 23 September 2018 02:00:36 UTC
Joomla_4.0.0-alpha5-dev-Development-Full_Package.zip

### Expected result
- Installation GUI

### Actual result
![23-09-_2018_13-05-54](https://user-images.githubusercontent.com/20780646/45927316-d43efa80-bf31-11e8-8bd9-532447223871.jpg)

**Comment by ReLater** [comment]
The whole /media/ folder is missing.

**Comment by richard67** [comment]
Yes, and compiled css of the templates are missing, too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22338">issues.joomla.org/tracker/joomla-cms/22338</a>.</sub>

**Comment by ReLater** [comment]
Also missing in 4.0 branch of repository

**Comment by richard67** [comment]
Nightly build package from yesterday was ok.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22338">issues.joomla.org/tracker/joomla-cms/22338</a>.</sub>

**Comment by richard67** [comment]
@wilsonge Any idea what could have happened?

**Comment by richard67** [comment]
@ReLater Media folder is not in 4.0-dev branch of the repo anymore since PR #21328 , I think. But it should have been created by `nmp install` before the package was packed. It seems this failed somehow. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22338">issues.joomla.org/tracker/joomla-cms/22338</a>.</sub>

**Comment by ReLater** [comment]
Related: https://github.com/joomla/joomla-cms/issues/22325
One should test own commits before committing them blindly into an "official" branch for merging.

Again frustrated "normal" testers/users out there.

**Comment by wilsonge** [comment]
ping @mbabker as I'm not sure where the new jenkins lives. Given git is compiling just fine and the comments on @22325 wondering if the jenkins workspace isn't being cleared down properly

**Comment by mbabker** [comment]
Nightly build regenerated.  It had nothing to do with "blindly committing to an official branch", there was a GitHub API hiccup when the build for the 4.0 branch was put together last night and it caused the package to not build correctly.  Nothing more, nothing less.

**Comment by mbabker** [comment]
FWIW https://github.com/joomla/joomla-cms/commit/4e8b30462b11e6b0e2e1bbb1da8edf7a86b6ee0a adds checks to the build script to fail it if `composer install` or `npm install` fail (the latter being what actually failed), this should cause the nightly build job to fail over as well and not push a broken package.

**Comment by ReLater** [comment]
> "blindly committing to an official branch"

Sorry, but there is also https://github.com/joomla/joomla-cms/issues/22325 that makes it impossible to recompile scss after build. That is something that I packed also in my angry phrase.

**Comment by brianteeman** [comment]
That is completely unrelated
