### ISSUE TITLE
Add manual selection of tags to module Tags Popular

### ISSUE THREAD

**Issue by oorzaak** [joomla/joomla-cms#22340]
### Steps to reproduce the issue

I needed a module that shows a manual selection of tags; as far as I know this is not possible at present using Joomla core modules. However I found a way to add this option with just one line of code to the module Tags Popular.

I contacted Roland Dalmulder about his and he advised me to submit as a Pull Request to add this line to the core. I'm not sure how to create a pull request so if I'm doing this wrong I hope that someone will be so kind to help me :smiley: 

### Additional comments

In mod_tags_popular.xml I added an extra option to the parameter field order_value. See attached txt file for the code of this option.

If selected, the module shows the tags in the order as set manually in the Tags component. This can be combined with setting the maximum number of tags in order to create your custom selection (up to the overall maximum of 20).

Please note that in this case the module does not take into account the "popularity" of the tag. This is exactly as I needed but it may conflict with the idea of the module: showing popular tags. However, the Random option of the module doesn't take that into account either (as a matter of fact, when selecting my cusom option the execution of the module script follows the same 'logical path' through the code as when selecting the Random option).

It might be a good idea to add some instruction about this. Apart from that, I think this offers some nice extra fuctionality and I was surprised at how easy it was to add this.

Kind regards, 

Frits Jongbloets

**Comment by oorzaak** [comment]
Hmm, attachment seems not te be present. I'll try again:

[mod_tags_popular-extra-option.txt](https://issues.joomla.org/uploads/1/5d46f76abae680014964e309a13514b3.txt)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22340">issues.joomla.org/tracker/joomla-cms/22340</a>.</sub>

**Comment by ReLater** [comment]
Here you find a documentation how you can provide a pr using your browser:
https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

Have a look on the Branch select box before you start with step "Find the file you want to modify on Github". "Staging" is the right one at the moment for Joomla 3 and your issue.

Don't be shy ;-) You'll break nothing with these steps and other users and/or magic tools will leave their comments if something more has to be done.

A clear and step-by-step testing instruction for dump testers like me is always a must. Screenshots are always welcome if helpful. One can easily drag and drop them into the pr description.

**Comment by oorzaak** [comment]
I added a pull request #22384 for my proposal. Maybe this issue #22340 should be closed / deleted?

Frits

**Comment by ReLater** [comment]
If you provide a pr and the issue is yours you can close the issue. If it's not your own issue somebody else will close it because you don't have the rights then.

**Comment by oorzaak** [comment]
Thanks for your help. Closing ths issue now.

**Comment by Holleyjolley** [comment]
Hej,
thank you for this proposal. Exactly what I am looking for. I managed to add this additional option and selected the order-option in the module but if I choose a tag (without existing sub-tags) the module outputs "no tags found". Do I have to undertake any other changement e.g. in tags options?
Thank you.
