### ISSUE TITLE
[4.0] After installation of an extensions, inactive tabs are visible, active tab is hidden

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#22352]
### Steps to reproduce the issue
Install a component as package file, i.e. the patchtester.

### Expected result
The tabs remain unchanged (with success or failure alert)

### Actual result
After the installation, the active tab is hidden, the inactive tabs are visible and marked as active. 

![screen shot 2018-09-24 at 14 00 15](https://issues.joomla.org/uploads/1/e45121c6c1708e678fa8637c6eea80ec.png)

**Comment by ghost** [comment]
closed as duplicate Report of #21981 

Please reopen if i failed and its a different Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22352">issues.joomla.org/tracker/joomla-cms/22352</a>.</sub>
