### ISSUE TITLE
User policy is not accepted

### ISSUE THREAD

**Issue by deroderuiter** [joomla/joomla-cms#22388]
### Steps to reproduce the issue
Log in on the font end as a registered user and except the user policy

### Expected result
The result should be that the screen disappears and that the user policy is accepted

### Actual result
The screen doesn't disappear and the user-policy is not accepted. The next message appears again: 

_Please confirm that you consent to this web site storing your information by agreeing to the privacy policy._

### System information (as much as possible)
I installed Joomla version, 3.9.0-beta4-dev.  

PHP Built On | Linux vserver261.axc.nl 3.10.0-714.10.2.lve1.5.12.el7.x86_64 #1 SMP Fri Feb 2 00:27:48 EST 2018 x86_64
-- | --
Database Type | mysql
Database Version | 10.2.13-MariaDB
Database Collation | latin1_swedish_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.1.15
Web Server | Apache/2
WebServer to PHP Interface | litespeed
Joomla! Version | Joomla! 3.9.0-beta4-dev Development [ Amani ] 26-September-2018 12:30 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

### Additional comments
I tried this on two different sites. One of them is a completely new installation, but the result is the same for both sites.

**Comment by joomdonation** [comment]
This error was fixed before, so it should not happen anymore. If it is possible, could you please look at your site database, find the table **#__privacy_consents**, check data type of **subject** field. If it's not **varchar (255)**, change it to **varchar (255)** and check it again to see whether it's working fine?

**Comment by deroderuiter** [comment]
That was the problem. The old data type was varchar (25). I changed it to
varchar (255) and now it's working fine indeed!


Op wo 26 sep. 2018 om 17:12 schreef Tuan Pham Ngoc <notifications@github.com

**Comment by ghost** [comment]
@deroderuiter can you please close the Issue as its resolved?
