### ISSUE TITLE
Joomla site does not open in safari for windows

### ISSUE THREAD

**Issue by Shivani-Parihar** [joomla/joomla-cms#22391]
### Steps to reproduce the issue
Safari 5.1.7 was last version for Windows and I am unable to open my joomla site on safari for windows.

![2018-09-26-2](https://user-images.githubusercontent.com/22653372/46100560-49f3d200-c18f-11e8-8665-6b0f4bd6fd2e.png)

![2018-09-26](https://user-images.githubusercontent.com/22653372/46100579-537d3a00-c18f-11e8-95be-f2483b509eca.png)

Can anyone help me with this issue.

**Comment by brianteeman** [comment]
Because it is so old and extremely outdated I am not surprised. It is not a supported browser anymore with joomla and you should download and install a modern browser.
