### ISSUE TITLE
Menu item "Archived Articles" misses options for readmore link and complete intro

### ISSUE THREAD

**Issue by HerKle** [joomla/joomla-cms#22394]
In the options of that menu item the intro text cannot be presented up tot the "readmore". There is only the possibility to cut the text after x characters. Then an ellipse (…) is added *below* the paragraph, instead of directly after the cut text. This is completely different to the "normal" display of articles in Joomla! showing the complete intro text separated by the readmore link. This different behaviour is irritating for the visitors.

I would like to have a consistent presentation of the content, also when it's archived. Please give archived articles the readmore link back,

Thx!

**Comment by ghost** [comment]
@HLeithner  can you please comment?

**Comment by HLeithner** [comment]
This depends on the template, if you have a custom template it should be fixed there, if its the core template we should fix it.

**Comment by brianteeman** [comment]
it is a core issue

**Comment by HLeithner** [comment]
@brianteeman could you make a PR?

**Comment by brianteeman** [comment]
its a big change that would be a b/c break

**Comment by HLeithner** [comment]
Ok then we can close this here. J4 should be ok with a new template?

@HerKle you should be able to fix this with a template override please ask in the forum if you need help with this.

**Comment by brianteeman** [comment]
it is not a template issue!!!!!! Have you never built a web site with Joomla

**Comment by HLeithner** [comment]
never used archive no sorry

**Comment by brianteeman** [comment]
Clearly

**Comment by HLeithner** [comment]
It took me 20 minutes to figure out how to fix it with a template override.

make a copy of this template file: components/com_content/views/archive/tmpl/default_items.php

Modify line 132 from:
```php
<div class="intro" itemprop="articleBody"> <?php echo JHtml::_('string.truncateComplex', $item->introtext, $params->get('introtext_limit')); ?> </div>
```
to
```php
<?php echo $item->introtext; ?>
<?php echo JLayoutHelper::render('joomla.content.readmore', array('item' => $item, 'params' => $params, 'link' => $link)); ?>
```

that would be enough to achieve the layout the opener wants, maybe some settings have to be set in the parameter so the readmore buttons looks the same.

So yes I already build a joomla website.

**Comment by Joomv** [comment]
Just a friendly reminder to be kind on Github.  There is no need to be rude.
Thanks.
