### ISSUE TITLE
Wrong use of @deprecate in libraries\src\Document\Document.php

### ISSUE THREAD

**Issue by basd82** [joomla/joomla-cms#22390]
### Steps to reproduce the issue
On line 656 it states:
* @deprecated 4.0  The (url, mime, media, attribs) method signature is deprecated, use (url, options, attributes) instead.

That's an incorrect usage of the tag: http://docs.phpdoc.org/references/phpdoc/tags/deprecated.html
You can't deprecate a certain signature, only the whole structural element (the method in this case).

### Expected result

Not markt as deprecated

### Actual result

The whole structural element (the method in this case) is marked as deprecate
https://stackoverflow.com/questions/27005219/is-it-possible-to-deprecate-method-parameters-in-php

### System information (as much as possible)
Joomla 3.8.12

### Additional comments
Solution remove invalid deprecate tag

**Comment by zero-24** [comment]
> Solution remove invalid deprecate tag

hmm i would suggest to change it to a @note so the information is still there. Can you do a PR against the staging repo for that change?

**Comment by laoneo** [comment]
We have more places like that. The correct solution would be to introduce a new function with a new name and deprecate this one. The problem is that this doc block exists since a long time and changing to a different function would be overhead. Honestly I would leave it like it is and better look that it will never happen again.

**Comment by ghost** [comment]
@HLeithner can Release Lead please decide?

**Comment by laoneo** [comment]
In J4 this code gets removed anyway. So I would close this issue and leave J3 as it is.

**Comment by ghost** [comment]
Closed as stated above, thanks @laoneo <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22390">issues.joomla.org/tracker/joomla-cms/22390</a>.</sub>
