### ISSUE TITLE
Option for Disable Hits counter increment

### ISSUE THREAD

**Issue by effrit** [joomla/joomla-cms#22406]
### Is your feature request related to a problem? Please describe.
Current Hits counter (article DB field) mostly useless because  it counts even your own (administrator) and any bots multiply visits.
But still it used for sorting content by popularity and you can show this hits to users and be proud of huge numbers of views of your articles. 

### Describe the solution you'd like
I suggest to make Option (in Articles: Options) to disable this counter increment so u can use this BD field to make more useful plugin for hits.
ps
I know what there is plugin(s) which make additional decrement (DB request) for hits to disable increment based on certain condition, but this is just not right.

**Comment by brianteeman** [comment]
Wouldn't it be better if you can write a more accurate counter that it is submitted to core as a replacement

**Comment by effrit** [comment]
We don't needed more accurate counter in core because it will decrease performance.
So my suggestion is make it possible to make third-part plugins for peoples who need more accurate hits.

**Comment by Quy** [comment]
Related #15771

**Comment by effrit** [comment]
cool, disabling increment solve problem for peoples who dont need it but want mysql caching. doubleshot.

**Comment by Septdir** [comment]
I agree that @brianteeman is worth fixing the counter.  
However, I also like the idea of @effrit, it's just not the most important application of disabling the htis parameter.

Disabling hits in the first place need those people who do not use them.  
Why do I need an extra query in the database, if I do not use this function?

#15771 In my opinion too radical

**Comment by brianteeman** [comment]
> Why do I need an extra query in the database, if I do not use this function?
You can say that about every query

**Comment by Septdir** [comment]
@brianteeman 
> You can say that about every query

Exactly. And if has parameters to turn off these query, it's very cool.

**Comment by brianteeman** [comment]
good luck writing the code

**Comment by ghost** [comment]
closed as having Pull Request #22413
