### ISSUE TITLE
[3.9] Repeatable field - parameters - min max repetitions

### ISSUE THREAD

**Issue by pepperstreet** [joomla/joomla-cms#22411]
### Is your feature request related to a problem? Please describe.

The (awesome) repeatable field lacks 2 important subform parameters.
Important to restrict user inputs to a reasonable or fixed amount. 
Important to protect against massive form value submissions. 
The core XML subform field has options to set the minimum and maximum repetitions: 

> min (optional) count of minimum repeating in multiple mode. Default: 0.
> max (optional) count of maximum repeating in multiple mode. Default: 1000.

### Describe the solution you'd like

Offer repetition parameters for MIN and MAX values. Defaults like in core subform field.

### Additional context

Thanks in advance!

**Comment by ghost** [comment]
can you please test if this is still an Issue in latest Version?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22411">issues.joomla.org/tracker/joomla-cms/22411</a>.</sub>

**Comment by ghost** [comment]
Closed as no Answer; please reopen if needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22411">issues.joomla.org/tracker/joomla-cms/22411</a>.</sub>
