### ISSUE TITLE
[3.9] Repeatable field - parameters - choose form input layout

### ISSUE THREAD

**Issue by pepperstreet** [joomla/joomla-cms#22412]
### Is your feature request related to a problem? Please describe.

The current repeatable field uses the **table layout** for form input display. 
Nice to display a "typical" data table with headings. It works quite well for a smaller amount of fields and fields that do not require too much space itself. There is also some sort of "responsive" table display through CSS and media-queries...: Columns begin to stack vertically. 

But with larger fields like editor or media, it can easily break the layout. Not to mention a greater amount of fields.

The core XML subform field seem to supply different layouts. Excerpt from documentation...

> _joomla.form.field.subform.**default**_ 
> render the subform in a div container, without support of repeating. Default for single mode.
> _joomla.form.field.subform.**repeatable**_ 
> render the subform in a div container, used for multiple mode. Support groupByFieldset.
> _joomla.form.field.subform.**repeatable-table**_ 
> render the subform as a table, used for multiple mode. Supports groupByFieldset. By default each field is rendered as a table column, but if groupByFieldset=true then each fieldset is rendered as a table column.

The 2nd "**repeatable**" layout is based on **DIV**'s. It always stacks the sub-fields vertically. It has also a different button layout and positions. The DIV layout is always top-to-bottom. It works well on any screen-size. 

Currently you can't switch to this or any other layout, because the table based one is a hard-coded default.  
  
### Describe the solution you'd like

A parameter to choose the form input layout. 

Maybe a toggle between the 2 multiple mode layouts is enough in this particular case? 
Although a dynamic layout select box is probably more versatile and future proof. 

### Additional context

Thanks in advance!

Subform field type documentation:
https://docs.joomla.org/Subform_form_field_type

**Comment by ghost** [comment]
does the Issue stay in latest Version 3.9.3?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22412">issues.joomla.org/tracker/joomla-cms/22412</a>.</sub>

**Comment by Fedik** [comment]
@franz-wohlkoenig I do not think that it is actual.
The repeatable field are depreciated, and the subform field have an attribute `layout` to choose the layout

**Comment by ghost** [comment]
Thanks for Comment, @Fedik 

closed based on Comment above. If closing is wrong please reopen and sorry.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22412">issues.joomla.org/tracker/joomla-cms/22412</a>.</sub>
