### ISSUE TITLE
[4.0] Icons missing on all managers except articles

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#22420]
### Steps to reproduce the issue
j4 clean install.
Display any manager.

Example:
Installed language Default icon missing

<img width="1015" alt="screen shot 2018-09-28 at 09 21 23" src="https://user-images.githubusercontent.com/869724/46198735-79304d80-c30d-11e8-8f57-13251868e1f4.png">

categories status icon missing

<img width="598" alt="screen shot 2018-09-28 at 10 59 31" src="https://user-images.githubusercontent.com/869724/46198801-9c5afd00-c30d-11e8-8751-f4828f42709c.png">

**Comment by chmst** [comment]
@infograf768 Please test this: https://github.com/joomla/joomla-cms/pull/22424/commits/14bfb01821e4b60811f4a306c28f8e00940a6e1e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22420">issues.joomla.org/tracker/joomla-cms/22420</a>.</sub>

**Comment by wilsonge** [comment]
Closing as I've merged #22424

**Comment by infograf768** [comment]
Thanks!
