### ISSUE TITLE
Possible redundant CSS relating to media 'Upload Widget'?

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#22430]
### Steps to reproduce the issue
https://github.com/joomla/joomla-cms/blob/staging/media/media/css/mediamanager.css#L45-L180
https://github.com/joomla/joomla-cms/blob/staging/media/media/css/popup-imagemanager.css#L70-L192

Is there still a use for this CSS? Failing to find any related markup.

**Comment by brianteeman** [comment]
Even if there isn't we cant remove it in j3 in case someone else is using it - can we ?

**Comment by ciar4n** [comment]
I don't know what the official stance on this is (if any). I know I have certainly removed CSS in the past deemed unused.

This is a sizeable chunk of CSS that is both unused and undocumented. Not even sure how usable it is. (eg. links there to images that don't appear to exist). If I was to hazard a guess, it looks like a progress indicator for image uploads. Did such a thing ever exist? Possibly something reverted before a release?

**Comment by brianteeman** [comment]
Best to look at the git history

**Comment by ciar4n** [comment]
Appears to be from before moving to github.

**Comment by Quy** [comment]
CSS for Flash-based file uploader that was removed due to XSS vulnerability. 

Removed in 2.5.10
https://developer.joomla.org/security-centre/83-20130404-core-xss-vulnerability.html

Removed in 3.1.0
https://github.com/joomla/joomla-cms/commit/4de5b0c4f23a3ab3ba9731deb5a28b80e06119fb

**Comment by ciar4n** [comment]
Thank you @Quy.

**Comment by ciar4n** [comment]
PR to remove... #22453
