### ISSUE TITLE
[4.0] Can't open articles for edit

### ISSUE THREAD

**Issue by emilushi** [joomla/joomla-cms#22436]
### Steps to reproduce the issue
1. Install Joomla 4
2. Install simple data or create a new article
3. Navigate on Articles list page
4. Click an article to open for edit

### Expected result
Load article edit view

### Actual result
Browser message:
`This page isn’t working
joomla.test is currently unable to handle this request.
HTTP ERROR 500`

Apache error log:
` AH01071: Got error 'PHP message: PHP Fatal error:  Cannot use Joomla\\CMS\\Language\\Multilanguage as Multilanguage because the name is already in use in /var/www/html/joomla/administrator/components/com_content/Helper/PreviewHelper.php on line 18', referer: http://joomla.test/administrator/index.php?option=com_content`

### System information (as much as possible)
OS: Ubuntu 16.04.4 LTS
HTTP Server: Apache/2.4.34 (Ubuntu)
SQL Server: mysql  Ver 14.14 Distrib 5.6.30, for Linux (x86_64)
PHP: PHP Version 7.3.0beta2

**Comment by Quy** [comment]
Make sure you are testing with the nightly builds.

https://developer.joomla.org/nightly-builds.html

**Comment by emilushi** [comment]
> Make sure you are testing with the nightly builds.
> 
> https://developer.joomla.org/nightly-builds.html

I'm using this release: https://github.com/joomla/joomla-cms/releases/tag/4.0.0-alpha4

**Comment by Quy** [comment]
That release is outdated. Please use the nightly builds.

**Comment by emilushi** [comment]
> That release is outdated. Please use the nightly builds.

Thanks! The nightly build worked perfect.
