### ISSUE TITLE
[3.8] Issue SEF Routing System in Archived Articles

### ISSUE THREAD

**Issue by walturbo** [joomla/joomla-cms#22450]
### Steps to reproduce the issue

-Enable Routing System
-Archive a series of articles in a category
-In menu item select voice Archived Articles and select the category
-Enable module menu.

### Expected result

Links are user friendly

### Actual result

All links aren't SEF, for example test.tv/articoli-archiviati?view=article&id=4:test-quattro&catid=8

### System information (as much as possible)

Joomla! 3.8.12 / PHP 7.2.8 / MySQLi 5.5.61

**Comment by infograf768** [comment]
Are you using "Modern" or "Legacy" router?
If you are using "Modern":
Have you created a specific menu item to display that category as a blog or list?
Or a List all categories menu item?
If not please create one, even if it is hidden. Then check again the links.

**Comment by csthomas** [comment]
When the article was published you probably does not know that the category does not have any menu item. For current version of joomla this is very important.

The problem is that joomla does not enforce prefix `/component/content/article` for every article without its own menu item (directly, by category or by all categories).

When you are on page like `/category-with-menu/1-article` then you can see a link to the article "test-quattro" as  `/category-with-menu/4-test-quattro` (1).

When you go to `/category-2-with-menu/category-3-menu` then the link to "test-quattro" will look like `/category-2-with-menu/category-3-menu/4-test-quattro` (2)

When your home page is the login page (com_users/login), then link to your article from that page will be `/component/content/article/4-test-quattro?...` (3)

After you archive your article and you can see it in archive view, now you have  `articoli-archiviati?view=article&id=4:test-quattro&catid=8` (4)

I mentioned one article with 4 different links generated by joomla! 
For this example, bots will visit your article 4 times.

I'm trying to convince more people that article without own menu item should have only one canonical link like `/component/content/article/8-category-alias/4-test-quattro`. 
See issue #19537 and PR for J4 #22229

I know, this is not a beautiful link, but at least it's easy to find.
It easy to search for prefix `/component/content` in GA. 
And then add missing menu items in your joomla.

**Comment by walturbo** [comment]
> Are you using "Modern" or "Legacy" router?

I have only Modern Router with "Remove IDs from URLs" enabled

> Have you created a specific menu item to display that category as a blog or list?

The menu is "Menu Item Type -> Archived Articles" and I have only one category with archived articles.

Menu is hidden, but not work though aren't hidden.

**Comment by csthomas** [comment]
One of the options is to create menu item "Articles - > Category Blog" for your category with id 8.

**Comment by walturbo** [comment]
> When the article was published you probably does not know that the category does not have any menu item. For current version of joomla this is very important.

All categories are linked to a menu on my site

> When your home page is the login page (com_users/login), then link to your article from that page will be `/component/content/article/4-test-quattro?...` (3)

Even if I log in, the link remains the same

> After you archive your article and you can see it in archive view, now you have `articoli-archiviati?view=article&id=4:test-quattro&catid=8` (4)

Yes, when the link is stored, it is similar to this one
 
> I mentioned one article with 4 different links generated by joomla!
> For this example, bots will visit your article 4 times.

I hope one of these 4 is a canonical link!

> One of the options is to create menu item "Articles - > Category Blog" for your category with id 8.

In [this link](https://www.ricettelastminute.com/test-3.8-lindo) there is a temporary site to perform tests, at the top you can find all the menus:

-Home (with 2 not archived articles)
-List of Archived Articles (with 2 archived articles but the link isn't SEF)
-Archived Articles with Layout Blog (with 2 articles but are hidden because are archived!)

**Comment by csthomas** [comment]
I have checked your test website.
your Home page is "Category 1", and you have there 2 published articles.

I assume that your archived articles does not belong directly to "Category 1".
They belong to different category/subcategory, I will call it "Category A".

Probably to fix your problem you have to publish "Category A". 
Archived categories does not work correctly.
I would say that Joomla should remove "Archive" state from categories.
 
If I'm wrong please show a screenshot of your menu items from the backend.

>> When your home page is the login page (com_users/login), then link to your article from that page will be /component/content/article/4-test-quattro?... (3)

> Even if I log in, the link remains the same

This is misunderstanding. 
Now you have Home Page as Articles -> Category List
I said that if you change your Home Page to Users -> Login Form and then check URL

**Comment by walturbo** [comment]
> your Home page is "Category 1", and you have there 2 published articles.

Yes!

> I assume that your archived articles does not belong directly to "Category 1".
> They belong to different category/subcategory, I will call it "Category A".
> Probably to fix your problem you have to publish "Category A".

I have "Category 1", "Category 2" and "Category 3" not archived but published.

> I would say that Joomla should remove "Archive" state from categories.
> 
> If I'm wrong please show a screenshot of your menu items from the backend.
> 
> > > When your home page is the login page (com_users/login), then link to your article from that page will be /component/content/article/4-test-quattro?... (3)

I have modified home page with login page, check now.

<h2>Categories:</h2>

![Category](https://www.ricettelastminute.com/test-3.8-lindo/varie/category.jpg)

<h2>Articles:</h2>

![Category](https://www.ricettelastminute.com/test-3.8-lindo/varie/articles.jpg)

<h2>Menus:</h2>

![Category](https://www.ricettelastminute.com/test-3.8-lindo/varie/menus.jpg)

<h2>Menu HOME PAGE (old, now is users login):</h2>

![Category](https://www.ricettelastminute.com/test-3.8-lindo/varie/menu-home.jpg)

<h2>Menu LIST OF ARCHIVED ARTICLES:</h2>

![Category](https://www.ricettelastminute.com/test-3.8-lindo/varie/menu-list-of-archived-articles.jpg)

<h2>Menu ARCHIVED ARTICLES WITH LAYOUT BLOG:</h2>

![Category](https://www.ricettelastminute.com/test-3.8-lindo/varie/menu-archived-articles-with-layout-blog.jpg)

**Comment by csthomas** [comment]
I can say that Category 2 does not have own menu item. Articles from Category 2 are visible in the Archive menu item(/list-of-archived-articles).

Go to https://www.ricettelastminute.com/test-3.8-lindo/component/content/archive
and you should see that articles from category 3 has correct links.

**Comment by walturbo** [comment]
You are right!
Is this normal or will this problem be solved with the next versions?

**Comment by csthomas** [comment]
AFAIK a lot of people treat it as a normal.
I have a different opinion. But my modifications may still not satisfy you.

I would like that website should generate correct canonical link without creating menu item for all categories in one or per every category.

If there is no menu item then a link like:
`/articoli-archiviati?view=article&id=4:test-quattro&catid=8`
should look like:
`/component/content/article/category-2/test-quattro`

and should not depend on which page you will generate such a link.

If you do not want to create a lot of menu items for categories then you should move Category 2 and Category 3 into Category 1. Then everything should work without additional menu items.

Category 1 (top category)
- Category 2 (subcategory)
- Category 3 (subcategory)

**Comment by walturbo** [comment]
Great!
Thanks for the time you dedicated to me ... hoping the Joomla team will simplify this procedure!

See you soon,
Walter

**Comment by ghost** [comment]
closed as Issue seems resolved; if not please reopen and apologize.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22450">issues.joomla.org/tracker/joomla-cms/22450</a>.</sub>
