### ISSUE TITLE
[3.8] Error while copying menu item

### ISSUE THREAD

**Issue by solracsf** [joomla/joomla-cms#22459]
### Steps to reproduce the issue
Try to copy a menu item to the same parent as the copied item

### Expected result
Item is copied

### Actual result
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ````') GROUP BY c2.`id`) AS c2 ON c2.newId = c.`id` SET `published` = c2.newPublished'```` at line 6 

### System information (as much as possible)
Joomla! 3.8.12
MariaDB 10.3.9
PHP 7.0.32

**Comment by solracsf** [comment]
Similar to https://github.com/joomla/joomla-cms/issues/18684 but for J3.8

**Comment by csthomas** [comment]
I suspect that your menu table is corrupted. Click on `Rebuild` button and try again.
