### ISSUE TITLE
[4.0] No extensions can be installed

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/joomla-cms#22463]
### Steps to reproduce the issue
I am trying to install the com_patchtester component from the file or from URL

### Expected result
Starting the installation

### Actual result
Nothing happens. I receive the message in console: 
TypeError: Joomla.submitbuttonurl is not a function[More info] 
onclick http://localhost/j46/administrator/index.php:1:1

### System information (as much as possible)
Windows 10
Agent: Chrome v. 69.0.3497.100 (64-bit) and Firefox v. 61.0.2 (64-bit)
Joomla on: https://github.com/joomla/joomla-cms/commit/3472e8b6ce8e4a60246b7a6364caf1deafb1fc82https://github.com/joomla/joomla-cms/commit/3472e8b6ce8e4a60246b7a6364caf1deafb1fc82
### Additional comments
@dgrammatiko ?

**Comment by dgrammatiko** [comment]
@zwiastunsw do you have a media folder? Do you have a media/com_installer/... file? Is it loaded in that view?

**Comment by zwiastunsw** [comment]
folder media and media/com_installer exist, but files in the js folder are not loaded

**Comment by wojsmol** [comment]
@dgrammatiko I confirm issue reported by @zwiastunsw.Bellow I post st answers as a table

|    question	|  answer	|
|---	|---	|
|    media folder 	|   exist 	|
|   media/com_installer/	|   exist	|
|   loaded in view	|   no	|

\media\com_installer\js contains following files
```
installer.es6.js
installer.es6.min.js
installer.js
installer.min.js
```

**Comment by dgrammatiko** [comment]
@wojsmol change lines 24,25 to the new version:
```
HTMLHelper::_('stylesheet', 'com_installer/installer.css', ['version' => 'auto', 'relative' => true]);
HTMLHelper::_('script', 'com_installer/installer.js', ['version' => 'auto', 'relative' => true]);
```

**Comment by wojsmol** [comment]
@dgrammatiko Ok, give me path to file to edit.
edit
I find it in administrator\components\com_installer\tmpl\install\default.php.
After applying suggested changes installer is working. Install from Web tab is always active and displayed on top of other tabs.

**Comment by wojsmol** [comment]
Please test https://github.com/joomla/joomla-cms/pull/22467
