### ISSUE TITLE
[3.8] Smart Search Indexer - MariaDB, SQL Syntax Error

### ISSUE THREAD

**Issue by n00bster** [joomla/joomla-cms#22471]
I noticed that the Smart Search Indexer are failing and does stop always around 90%.
The error came up on both sides when i run the indexer: on CLI or at joomla Backend

i looked in this documentations and tested some things out but could not fix the problem on my own:
https://docs.joomla.org/Smart_Search_configuration_options
https://docs.joomla.org/Smart_Search_on_large_sites

there for it would be fine when some one could have a look in my problem.
when i missed a info what it would good to know, please give me a hint.
I'm not a developer or programmer, i hope it is not a problem to get help here.

### Steps to reproduce the issue
- run smart indexer from backend results in the issue.
- also when i run the smart indexer in the CLI
i used this command to test the smart search indexer from CLI:
```
/RunCloud/Packages/php72rc/bin/php -d memory_limit=256M webapps/mywebapp/cli/finder_indexer.php --purge
```
in the documentations i found a info to change the temporary memory size. i did so from 32M to:
```
tmp_table_size = 64M
max_heap_table_size = 64M 
```
without positiv result - after i have restarted the MYSQL service the problem still exists.

I changed also for testing purposes the "batch size" to "5", but that does also not help - same error came up.

i also consulted with my server administration host (runcloud.io). they are saying that this error is not in there scope - answer from support:
> It looks like an application level issue, we do not provide any application level support, you would have to upgrade it to the latest one or get in touch with the Joomla support team, they can help you with this.

### Expected result
the smart indexer should run without error and finish the process.

### Actual result
the process is stopping always in the last third of the process with this error message in the CLI
```
* Processed batch 92 in 5.166 seconds.
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 12' at line 1
```
or the error message from the backend:
![2018-09-30_21-27-17](https://user-images.githubusercontent.com/1003469/46393990-d9e1d080-c6e7-11e8-8b8a-0f8e16277591.jpg)

### System information (as much as possible)
SERVER: cloudserver - Linux ubuntu 18 x64
SERVER Administration: [runcloud.io](https://runcloud.io/)
Database: 5.5.5-10.2.15-MariaDB-1:10.2.15+maria~bionic-log
PHP: 7.2.8
Webserver: Apache/2.4.34
Joomla: 3.8.12

#### Smart Search Indexer OPTIONS are set all on default
Indexer Batch Size: 50
Memory Table Limit: 30000

**Comment by Quy** [comment]
Please test this PR #13502

**Comment by n00bster** [comment]
> Please test this PR #13502

thx to jump in here, how can i download this patch files there? 
sorry to ask this but i'm not very familiar with github.

**Comment by Quy** [comment]
Go to the following 2 links and right click to save them to your computer. Backup the old files and replace with new files in their respective directories.

https://raw.githubusercontent.com/joomla/joomla-cms/d6a4e1aa50f9896af455aa2bdcca4e9619e110a4/cli/finder_indexer.php

https://raw.githubusercontent.com/joomla/joomla-cms/d6a4e1aa50f9896af455aa2bdcca4e9619e110a4/language/en-GB/en-GB.finder_cli.ini

**Comment by n00bster** [comment]
thx. 
i did run this patch and the error came up again:
```
/RunCloud/Packages/php72rc/bin/php -d memory_limit=512M webapps/mywebapp/cli/finder_indexer.php --purge
```

```
 * Continuing processing of batch ...
 * Processed batch 91 in 3.449 seconds.
 * Pausing processing for 1 seconds ...
 * Continuing processing of batch ...
 * Processed batch 92 in 4.964 seconds.
 * Pausing processing for 1 seconds ...
 * Continuing processing of batch ...
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 19' at line 1
```
it looks like it is always the batch with the number 93 where the error comes up with the default batchsize of 50.

**Comment by Quy** [comment]
Please enable `Debug System` under `System > Global Configuration` to see the failed SQL query.

**Comment by n00bster** [comment]
in the joomla debug console i don't see any signs of a problem that matches this error message. are the debug output also saved in a log file? how can i copy this in a way that i can post it here.

**Comment by Quy** [comment]
Enable it, then run the indexer.

**Comment by n00bster** [comment]
![2018-10-03_19-44-45](https://user-images.githubusercontent.com/1003469/46428679-ec3e2780-c744-11e8-85a0-5daf8d2b1fc6.jpg)
that is what i get, sorry but most of this messages are hidden in the iframe console window.

**Comment by Quy** [comment]
Sorry also please select `Maximum` in `Global Configuration > Server > Error Reporting` and try again.

**Comment by mbabker** [comment]
I don't think you're getting these queries without some core hacking.

The debug plugin only spits out output on HTML responses, so what you're getting in the indexer modal is the first AJAX request that seeds it.  The plugin also won't even do anything useful if the `onAfterRespond` hook fires and you aren't in a HTML format (which you wouldn't be for the indexer, it's all JSON; that sucks because there are other useful bits like writing the SQL log file for the request).

Lastly, the indexer (like most things in core handling non-HTML responses) short circuits the request cycle and explicitly calls `$app->close()` at the end of the controller instead of letting the request actually go through the full cycle.  So `onAfterDispatch` and `onAfterRespond` never fire (two of the main hooks in the debug plugin).

**Comment by n00bster** [comment]
after further testing by deactivating one plugin after the other and rerun the indexer on CLI i was able to narrow down the problem.

conclusion is that the "finder_plugin" from eorisis metadata tool ([https://eorisis.com/web-design/joomla-extensions/metadata](https://eorisis.com/web-design/joomla-extensions/metadata)) cause the problem. 

George from eorisis did patch the tool and to problem is gone.

**Comment by infograf768** [comment]
Closing as not Joomla related.
