### ISSUE TITLE
[RFC] Language strings for vote plugin

### ISSUE THREAD

**Issue by Harmageddon** [joomla/joomla-cms#22478]
I just tested a PR with the vote plugin and was irritated by the English language strings for the messages. To me, the capitalization in these two messages looks a bit arbitrary:
https://github.com/joomla/joomla-cms/blob/staging/language/en-GB/en-GB.com_content.ini#L12-L13

Because these messages are complete sentences and don't contain any names, I would suggest writing everything except the first word in lowercase. But I'd like to hear the opinion of a native speaker (e.g. @brianteeman?) on this.

Also, both messages talk about an article being rated, though the vote plugin can be used for categories, too. Maybe a more "neutral" term like "item" or "page" should be used here?

**Comment by brianteeman** [comment]
1. you are correct about the capitalisation
2. if it really can be used on a category then yes it should be changed to item BUT i didnt see a way for it to be used on a category

**Comment by Harmageddon** [comment]
@brianteeman Thank you for your quick reply! You're right, rating categories is not possible. This was a misinterpretation on my side. Sorry!
I'll open a PR for the capitalisation then.
