### ISSUE TITLE
Users not being logged in on *.site.com but are on www.site.com

### ISSUE THREAD

**Issue by fusedNL** [joomla/joomla-cms#22487]
### Expected result
Expected when a user receives a direct URL to see himself as logged in. Both applying to https://www.site.com/article/1 and https://site.com/article/1 

### Actual result
On https://www.site.com/article/1  user is logged in and can see private article. However on http://site.com/article/1 user is redirected to the logged out section.

### System information (as much as possible)

=============
System Information
=============
php: Linux com-linweb306 4.14.18-combell #1 SMP Fri Feb 9 09:33:00 CET 2018 x86_64
dbserver: mysql
dbversion: 5.7.22-22
dbcollation: latin1_swedish_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 7.2.7
server: Apache
sapi_name: fpm-fcgi
version: Joomla! 3.8.12 Stable [ Amani ] 28-August-2018 14:00 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

=============
PHP Settings
=============
safe_mode: false
display_errors: false
short_open_tag: true
file_uploads: true
magic_quotes_gpc: false
register_globals: false
output_buffering: false
open_basedir: xxxxxx
session.save_path: xxxxxx
session.auto_start: 0
disable_functions: symlink
xml: true
zlib: true
zip: true
mbstring: true
iconv: true
max_input_vars: 20000

=============
Configuration File
=============
MetaAuthor: 1
MetaDesc: 
MetaKeys: 
MetaRights: 
MetaTitle: 1
MetaVersion: 0
access: 1
cache_handler: file
cachetime: 15
caching: 0
captcha: recaptcha
cookie_domain: 
cookie_path: 
db: xxxxxx
dbprefix: xxxxxx
dbtype: mysqli
debug: 0
debug_lang: 0
display_offline_message: 1
editor: jce
error_reporting: none
feed_email: author
feed_limit: 10
force_ssl: 2
fromname: xxxxxx
ftp_enable: 0
ftp_host: 127.0.0.1
ftp_pass: xxxxxx
ftp_port: 21
ftp_root: 
ftp_user: xxxxxx
gzip: 1
helpurl: https://help.joomla.org/proxy?keyref=Help{major}{minor}:{keyref}&lang={langcode}
host: xxxxxx
lifetime: 600
list_limit: 20
live_site: 
log_path: xxxxxx
mailer: smtp
mailfrom: xxxxxx
memcache_compress: 1
memcache_persist: 1
memcache_server_host: xxxxxx
memcache_server_port: 11211
offline: 0
offline_image: 
offline_message: We are offline till 12:35 due to maintenance. 
offset: Europe/Amsterdam
offset_user: UTC
password: xxxxxx
robots: 
secret: xxxxxx
sef: 1
sef_rewrite: 1
sef_suffix: 0
sendmail: xxxxxx
session_handler: none
sitename: xxxxxx
sitename_pagetitles: 1
smtpauth: 1
smtphost: xxxxxx
smtppass: xxxxxx
smtpport: 465
smtpsecure: ssl
smtpuser: xxxxxx
tmp_path: xxxxxx
unicodeslugs: 0
user: xxxxxx
memcached_persist: 1
memcached_compress: 0
memcached_server_host: xxxxxx
memcached_server_port: 11211
proxy_enable: 0
proxy_host: 
proxy_port: 
proxy_user: 
proxy_pass: 
mailonline: 1
session_memcache_server_host: xxxxxx
session_memcache_server_port: 11211
session_memcached_server_host: xxxxxx
session_memcached_server_port: 11211
frontediting: 1
asset_id: 1
redis_persist: 1
redis_server_host: xxxxxx
redis_server_port: 6379
redis_server_auth: 
redis_server_db: 0
massmailoff: 0
cache_platformprefix: 0
shared_session: 0

### Additional comments

Plugin forever sessions is running, tried not using it but still same issue after removing all cache.

**Comment by tonypartridge** [comment]
Are you sure it’s not http/https related?

**Comment by mbabker** [comment]
`example.com` and `www.example.com` are two different domains (well, www is a subdomain, even though in practice the two are generally interchangeable).  Generally, you should redirect your traffic so that either the use of the www subdomain is enforced or removed (`.htaccess` can help with this).  Otherwise, you will need to adjust your cookie settings to allow cookies to be used on both the root domain and the www subdomain.

**Comment by Quy** [comment]
Closing as this is a setup issue. If you need further assistance, please ask in Joomla Forum https://forum.joomla.org/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22487">issues.joomla.org/tracker/joomla-cms/22487</a>.</sub>
