### ISSUE TITLE
create new article J4

### ISSUE THREAD

**Issue by stankurd** [joomla/joomla-cms#22488]
### Steps to reproduce the issue

Try create new article and try use cakendar to start publishing can't open popup 
 window with calendar  
![screenshot_2018-10-03 articles new - jl4 - administration](https://user-images.githubusercontent.com/939374/46431178-6671aa80-c74b-11e8-93b1-729901e6f327.png)
### Actual result

no 

### System information (as much as possible)

  | Value
-- | --
 
Windows NT MACIEK-KOMPUTER 6.1 build 7601 (Windows 7 Home Premium Edition Service Pack 1) AMD64
mysql
5.7.23
utf8_unicode_ci
utf8_general_ci
7.2.10
Apache/2.4.27 (Win64) PHP/7.2.10
apache2handler
Joomla! 4.0.0-alpha5-dev Development [ Amani ] 22-July-2018 22:58 GMT
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0

**Comment by TobsBobs** [comment]
I can confirm this issue!

**Comment by stankurd** [comment]
After last update all is OK
