### ISSUE TITLE
Media mamager don't works J4

### ISSUE THREAD

**Issue by stankurd** [joomla/joomla-cms#22484]
### Steps to reproduce the issue
Try open media manager

### Actual result

Call stack
--
# | Function | Location
1 | () | JROOT\plugins\filesystem\local\local.php:98
2 | PlgFileSystemLocal->getAdapters() | JROOT\administrator\components\com_media\src\Model\MediaModel.php:52
3 | Joomla\Component\Media\Administrator\Model\MediaModel->getProviders() | JROOT\libraries\src\MVC\View\AbstractView.php:146
4 | Joomla\CMS\MVC\View\AbstractView->get() | JROOT\administrator\components\com_media\src\View\Media\HtmlView.php:64
5 | Joomla\Component\Media\Administrator\View\Media\HtmlView->display() | JROOT\libraries\src\MVC\Controller\BaseController.php:686
6 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT\libraries\src\MVC\Controller\BaseController.php:724
7 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\libraries\src\Dispatcher\ComponentDispatcher.php:162
8 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT\libraries\src\Component\ComponentHelper.php:354
9 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:111
10 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:154
11 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:233
12 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\includes\app.php:63
13 | require_once() | JROOT\administrator\index.php:36

### System information (as much as possible)
Setting	Value
 
PHP Built On	Windows NT MACIEK-KOMPUTER 6.1 build 7601 (Windows 7 Home Premium Edition Service Pack 1) AMD64
Database Type	mysql
Database Version	5.7.23
Database Collation	utf8_unicode_ci
Database Connection Collation	utf8_general_ci
PHP Version	7.2.10
Web Server	Apache/2.4.27 (Win64) PHP/7.2.10
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 4.0.0-alpha5-dev Development [ Amani ] 22-July-2018 22:58 GMT
User Agent	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by TobsBobs** [comment]
I have the last nightly build Joomla 4 and the media manger works. Which version do you have.

**Comment by stankurd** [comment]
Just update via git with last changes

**Comment by stankurd** [comment]
An error has occurred.

    0 Class 'Joomla\Plugin\Filesystem\Local\Adapter\LocalAdapter' not found

**Comment by laoneo** [comment]
Delete the psr4 file in the libraries folder.

**Comment by stankurd** [comment]
ok now it's works
