### ISSUE TITLE
Modal not opening in Firefox

### ISSUE THREAD

**Issue by AndiLeni** [joomla/joomla-cms#22489]
### Steps to reproduce the issue
Goto 'menu'
Click the 'Ein Modul für dieses Menü hinzufügen' (select a module for this menu)

### Expected result
Modal opens

### Actual result
Modal not visible to user but visible to inspector 

### System information (as much as possible)
Firefox newest
Php 7.2.9

### Additional comments
Bug does not appear in Chrome

**Comment by Quy** [comment]
Joomla version?

**Comment by AndiLeni** [comment]
The newest. Should be 3.8.12 if I remember correctly.

**Comment by infograf768** [comment]
Can't reproduce on staging, Macintosh, Firefox 62.0.2, PHP 7.1.13

**Comment by AndiLeni** [comment]
Mhmm. That's pretty strange. 
It works fine on my windows tablet. I'm gonna have a look on my other laptop later to determine if the problem still persists.

**Comment by Quy** [comment]
Can't reproduce it either on Windows 10 Home, Firefox 62.0.3

**Comment by AndiLeni** [comment]
It works fine now. Obviously it was some browser cache issue.
Closing this now.
