### ISSUE TITLE
Jcfields property is null for a child category item in blog view

### ISSUE THREAD

**Issue by SemaphoreOxalis** [joomla/joomla-cms#22483]
### Steps to reproduce the issue
Create a category with sub-categories inside
Create a custom field for sub-categories
Set a value to one or multiple sub-categories
Create a menu item "blog view" and configure it for showing sub-categories
Create an override for blog_children.php 
Populate the $child variable with the "classic procedure" :smile: 
```php
JLoader::register('FieldsHelper', JPATH_ADMINISTRATOR . '/components/com_fields/helpers/fields.php');

foreach($child->jcfields as $jcfield)
     {
          $child->jcFields[$jcfield->name] = $jcfield;
     }
 var_dump ($child->jcfields);
```

### Expected result

Array with the custom field properties

### Actual result

NULL

### System information (as much as possible)

J!3.8.12

### Additional comments
It seems it's the same issue for all categories view like if these view don't be able to load jcfields

**Comment by ghost** [comment]
can you please test if this is an Issue using latest Version?

According to the https://docs.joomla.org/Bug_and_Issue_Tracker_Priority i changed from "Urgent" to "Medium".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22483">issues.joomla.org/tracker/joomla-cms/22483</a>.</sub>

**Comment by ghost** [comment]
closed as no Answer. Please reopen if needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22483">issues.joomla.org/tracker/joomla-cms/22483</a>.</sub>
