### ISSUE TITLE
Error 500 opening article in backend

### ISSUE THREAD

**Issue by faffone** [joomla/joomla-cms#22496]
### Steps to reproduce the issue
Create new article
Save the article
Try to re-open the article

### Expected result
The article is opened

### Actual result
HTTP ERROR 500

### System information (as much as possible)
WEB Server   Apache/2.4.34 (Unix) OpenSSL/1.0.2p SVN/1.11.0-dev PHP/7.2.10
Joomla! Version	   Joomla! 4.0.0-alpha4 Alpha [ Amani ] 22-July-2018 22:52 GMT
Local NAS QNAP TS251+
QTS 4.3.5.0713 (2018/09/28)

### Additional comments
The article was regularly created
The article is regularly showed in frontend
No problem browsing the website pages in frontend
No problem working with other backend options
If i create a new module custom, no problem to reopen and modify it (there's no editor problem)

Excuse me for my bad english ;-)
Bye
Alfio

**Comment by Quy** [comment]
Please test with nightly builds here: https://developer.joomla.org/nightly-builds.html<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22496">issues.joomla.org/tracker/joomla-cms/22496</a>.</sub>

**Comment by faffone** [comment]
The last nightly-builds works. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22496">issues.joomla.org/tracker/joomla-cms/22496</a>.</sub>
