### ISSUE TITLE
[4.0] [RFC] libraries/cms/html/jgrid.php needs a review

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#22501]
libraries/cms/html/jgrid.php seems to be dammaged. A review should be made to be sure that parameters are correct and consistent.
Some PRS made missing buttons visible again, but the parameters still are not consitent - especially the parameter text.

**Comment by laoneo** [comment]
Since when it is damaged?

**Comment by chmst** [comment]
I noticed missing icons the day before this issue https://issues.joomla.org/tracker/joomla-cms/22420

**Comment by SharkyKZ** [comment]
#22294. But some calls were missing arguments even before.

**Comment by chmst** [comment]
At the moment,the ordering column is not working. If I remove the parameter "text"  here https://github.com/joomla/joomla-cms/blame/14bfb01821e4b60811f4a306c28f8e00940a6e1e/libraries/cms/html/jgrid.php#L423 and here https://github.com/joomla/joomla-cms/blame/14bfb01821e4b60811f4a306c28f8e00940a6e1e/libraries/cms/html/jgrid.php#L423  it works, but then the parameter text is not used at all.

**Comment by SharkyKZ** [comment]
Need to restore second `$text` parameter in `orderUp()` and `orderDown()` that was removed with #22424. The unneeded param was already removed with #22349.

**Comment by chmst** [comment]
Thank you very much. I have commited these changes. https://github.com/joomla/joomla-cms/pull/22437.  So this should do it. Just seems strange to have the same param two times.

**Comment by laoneo** [comment]
In #22349 it was reduced from three times to only two times.

**Comment by chmst** [comment]
Please close this, thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22501">issues.joomla.org/tracker/joomla-cms/22501</a>.</sub>

**Comment by Quy** [comment]
@chmst You can close your own issues. Please see the `Close issue` button next to the `Comment` button in the screenshot. 

![close](https://user-images.githubusercontent.com/368084/48725967-bb299180-ebe2-11e8-80ae-df469a5a8294.jpg)
