### ISSUE TITLE
Ugly Joomla core provided Protostar template Bug

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#22504]
### Steps to reproduce the issue

Menus

Articles » Category Blog

Blog Layout

Intro Articles 200
Columns 3

### Expected result

Columns 3 display intro articles 

### Actual result

First couple rows it seems to display intro articles ok, but after that these rows intro articles somehow srinks and I get ugly display such as only 1 intro article in the row and then all other articles are squeezed and are ugly to view.

### System information (as much as possible)

Joomla 3.8.12 Protostar template Blog Layout ugly bug

### Additional comments

How to help fix this ugly core provided Joomla protostar template bug?

**Comment by brianteeman** [comment]
Almost impossible to help without see it but this is almost certainly due to bad markup **inside** one of your articles and nothing to do with the template.

Please use the forum for further support https://forum.joomla.org

**Comment by ghost** [comment]
What is a bad markup inside one of articles in joomla that couse this ugly bug in joomla core provided Protostar template?

I see zero such thing in articles, maybe you know what markup can couse such ugly joomla display? 

This is almost certainly due to ugly bug in joomla core provided Protostar template.

**Comment by ciar4n** [comment]
Usually caused by an unclosed div in the article.

**Comment by ghost** [comment]
@ciar4n  thanks :) div was the case
