### ISSUE TITLE
[4.0] plugin statistics popup not an alert

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#22507]
![image](https://user-images.githubusercontent.com/1296369/46529904-033d6080-c890-11e8-8cd8-863c6aca4641.png)

This should not have a role=alert as this role does not allow for a response by the user, instead it should have a role=alertdialog

Not sure if it is best to create a new custom element for alertdialog of if it should be an option passed to the existing alert custom element.

In addition it should receive focus https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alertdialog_role

**Comment by hardik-codes** [comment]
@brianteeman Working on it

**Comment by hardik-codes** [comment]
@brianteeman where is ```role=alert``` defined ?
As I'm not able to find it in ```message.php```

**Comment by ghost** [comment]
@brianteeman can you please help?

**Comment by brianteeman** [comment]
If i could have fixed it myself i would already have done so

**Comment by Quy** [comment]
I assume this is upstream:
`\media\vendor\joomla-custom-elements\js\joomla-alert.js`

`role` is set here:
```
    /* Lifecycle, element appended to the DOM */
    connectedCallback() {
      this.setAttribute('role', 'alert');
      this.classList.add('joomla-alert--show');
```

**Comment by brianteeman** [comment]
Upstream is https://github.com/joomla-projects/custom-elements/issues/118

**Comment by Quy** [comment]
Please test https://github.com/joomla-projects/custom-elements/pull/119

**Comment by alikon** [comment]
closed as we have a pr joomla-projects/custom-elements#119<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22507">issues.joomla.org/tracker/joomla-cms/22507</a>.</sub>
