### ISSUE TITLE
Edit Article Error when not allowed to edit custom field

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#22519]
### Steps to reproduce the issue
Create custom field with default value as Super Administrator of any kind and assign to be displayed in Article edit
Login as Editor and try to edit and save the article

### Expected result
- Editor is not allowed to edit custom field, that is ok
- Article can be save because editor does not touch custom field

### Actual result
- Article cannot be save and error message invalid field
- every field must be enabled for Editor in ACL setting

### System information (as much as possible)
Joomla 3.8.12

### Additional comments
The Editor does not need the field it is for super user but editor cant save article when field is not changed in settings.

**Comment by brianteeman** [comment]
is it a required field?

**Comment by B3nito** [comment]
No its not required

**Comment by webstractions** [comment]
I had the same problem. Had to go into the Permissions tab for each custom field and allow for _Edit Custom Field Value_ for each added field.

**Comment by B3nito** [comment]
yes and that is a lot of work and you have always to think about it

**Comment by B3nito** [comment]
Will it be solve in next version?

**Comment by zero-24** [comment]
Please test: https://github.com/joomla/joomla-cms/pull/22923 @B3nito @webstractions

**Comment by simbus82** [comment]
I think problem is another: usergroups like Editor and Administrator for default they can't edit "custom field content". It's wrong for me.
For example, when i create a "Custom Field Group", for default Administrator can not edit the "content" of Field, aka they can't create and save articles with custom fields.
![image](https://user-images.githubusercontent.com/1375730/51401109-49ba8080-1b4a-11e9-972f-e0b8fdc76a75.png)

It's not a code bug, but i think a wrong "default" value for this permission.
It's happen in 3.9.2.

PS: without changing the permission of all custom fields, you can change permission of "Custom fields Group". Permission of single custom field are inherited from here.

**Comment by HLeithner** [comment]
This should be fixed now with PR https://github.com/joomla/joomla-cms/pull/22923
