### ISSUE TITLE
Menu Item alias is not set correct when used in another language

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#22515]
### Steps to reproduce the issue
On a mulilanguage site create a menuitem in language A.
In language B setup a menu item alias to the item of the language A

### Expected result
When you Click on menu item alias in Language B you are redirected to Menuitem in Language A
languagedomain.com/B/ -> languagedomain.com/A/mydesireditem

### Actual result
You are redirected to a new Menuitem of language B with content of A, and everything surrounding is wrong.
languagedomain.com/B/ -> languagedomain.com/B/mydesireditem, wrong modules

### System information (as much as possible)
Joomla 3.8.12

**Comment by infograf768** [comment]
In a multilingual site, one should never use an alias menu item to a menu item tagged to another language. As the language is not set correctly, one will get into various issues, the one concerning modules being an obvious one.
If you need to create a menu item in language A which will display a menu item in language B, use the URL menu item.

First copy the link of the menu item in language B:
<img width="806" alt="screen shot 2018-10-06 at 11 08 56" src="https://user-images.githubusercontent.com/869724/46569654-46630680-c958-11e8-9926-1a297506d332.png">

here it is `index.php?option=com_content&view=category&layout=blog&id=9`

Then create a URL menu item in language A, enter the link you just copied and add the lang
Example for French (French is language B)
`index.php?option=com_content&view=category&layout=blog&id=9&lang=fr`

It will look like
<img width="1009" alt="screen shot 2018-10-06 at 10 54 27" src="https://user-images.githubusercontent.com/869724/46569684-b40f3280-c958-11e8-8847-76ed34c3ad91.png">

and it will work fine.

**Comment by B3nito** [comment]
But this is like "hardcoded" It should be possible to link to another site in another language in my opinion.

**Comment by infograf768** [comment]
I may have a solution to make alias menu item multilingual aware.
Obviously this will not link to another site but the same site when the menu item targeted is tagged to another language.

**Comment by infograf768** [comment]
hmm. That would only be for Protostar as my modifications are only for now in the menu module.
have to find a more general way. Not obvious...

**Comment by csthomas** [comment]
I suggest to add a `lang` parameter to `$item->flink = 'index.php?Itemid=' . $item->params->get('aliasoptions');` in mod_menu helper.php.

**Comment by infograf768** [comment]
I have done that and PR is ready, but it would work ONLY when using the core menu module.
```
diff --git a/modules/mod_menu/helper.php b/modules/mod_menu/helper.php
index dbc9254..0d69d4e 100644
--- a/modules/mod_menu/helper.php
+++ b/modules/mod_menu/helper.php
@@ -115,5 +115,28 @@
 
 						case 'alias':
-							$item->flink = 'index.php?Itemid=' . $item->params->get('aliasoptions');
+							// Query the language of the target menu item
+							if (JLanguageMultilang::isEnabled())
+							{
+								$db = \JFactory::getDbo();
+								$query = $db->getQuery(true)
+									->select($db->quoteName('language'))
+									->from($db->quoteName('#__menu'))
+									->where($db->quoteName('id') . ' = ' . (int) $item->params->get('aliasoptions'));
+
+								$db->setQuery($query);
+								$language = $db->loadResult();
+							}
+
+							// Use language code if not set to ALL
+							if ($language && JLanguageMultilang::isEnabled() && $language !== '*')
+							{
+								$lang = '&lang=' . $language;
+							}
+							else
+							{
+								$lang = '';
+							}
+
+							$item->flink = 'index.php?Itemid=' . $item->params->get('aliasoptions') . $lang;
 							break;
```

**Comment by HLeithner** [comment]
I would suggest streamlined variant
```php
$item->flink = 'index.php?Itemid=' . $item->params->get('aliasoptions');

// Query the language of the target menu item
if (JLanguage::MultilangisEnabled())
{
  $db    = \JFactory::getDbo();
  $query = $db->getQuery(true)
              ->select($db->quoteName('language'))
              ->from($db->quoteName('#__menu'))
              ->where($db->quoteName('id') . ' = ' . (int) $item->params->get('aliasoptions'));

  $db->setQuery($query);
  $language = $db->loadResult();
  // Use language code if not set to ALL
  if ($language !== '*')
  {
    $item->flink .= '&lang=' . $language;
  }
}
```

**Comment by csthomas** [comment]
Why not use something like ...getMenu()->getItem((int) $item->params->get('aliasoptions'));

**Comment by infograf768** [comment]
`aliasoptions` only contains the itemid

**Comment by infograf768** [comment]
but the issue is, as I see it, that it would only work for the core menu module.
Is it worth doing it in that case?

**Comment by csthomas** [comment]
I do not see a problem with
```php
$newItem = JFactory::getApplication()->getMenu()->getItem((int) $item->params->get('aliasoptions'));
$language = $newItem->language;
```

> Is it worth doing it in that case?

IMO yes, but I have not have any multilingual website yet:)

**Comment by infograf768** [comment]
your code saves a query.
Will do PR, knowing that it will not work when the site does not use the core module.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/22579

closing as we have a patch.
