### ISSUE TITLE
[4.0] Direct commits

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#22511]
In the last few days there have been a large number of direct commits to the 4.0 branch. 

For obvious reasons that really should not ever be done.

So far I have identified two errors which I believe are as a result of these direct commits

1. Calendar field will not open
2. Permissions table is empty (not the db table)

**Comment by infograf768** [comment]
I confirm these 2 issues.

**Comment by infograf768** [comment]
Concerning permissions, it comes from
https://github.com/joomla/joomla-cms/pull/22378
