### ISSUE TITLE
Menu Heading, Menu Alias cannot be set as base entry in menu module

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#22516]
### Steps to reproduce the issue
Setup a menu heading or alias contact
setup menu children of this menu item
setup menu module to always display children of contact on site (base entry)

### Expected result
You can set any base entry you want

### Actual result
Menu heading and menu alias are not clickable and not active

### System information (as much as possible)
Joomla 3.8.12

**Comment by ghost** [comment]
can you please test the issue in latest Version?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22516">issues.joomla.org/tracker/joomla-cms/22516</a>.</sub>

**Comment by brianteeman** [comment]
No need to test - nothing has changed

**Comment by ghost** [comment]
thanks @brianteeman <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22516">issues.joomla.org/tracker/joomla-cms/22516</a>.</sub>

**Comment by SharkyKZ** [comment]
Alias is clickable for me.

Menu heading is not but that's intended. It's a heading, not a link.

**Comment by alikon** [comment]
expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22516">issues.joomla.org/tracker/joomla-cms/22516</a>.</sub>

**Comment by SharkyKZ** [comment]
I misunderstood the issue. This is duplicate of #20556.
