### ISSUE TITLE
Very long article name, text do not wrap in com_associations

### ISSUE THREAD

**Issue by jsubri** [joomla/joomla-cms#22522]
### Steps to reproduce the issue
- create an article with a long name such as "A very very very very long loooooooooooooooooooooooooooooong long title and long alias will not wrap in com_associations"
- leave Alias blank and assign to a language
- save and search for it in com_associations

### Expected result
Text wrap the same as com_content

### Actual result
![very long com_associations](https://user-images.githubusercontent.com/5349333/46572400-5c3af080-c985-11e8-8e57-b349b257d874.PNG)

### System information (as much as possible)
current staging 3.9

**Comment by brianteeman** [comment]
Please test #22523
