### ISSUE TITLE
Bug with generate base href meta-tag.

### ISSUE THREAD

**Issue by sdi68** [joomla/joomla-cms#22527]
### Steps to reproduce the issue
I have Joomla settings:
public $sef = '1';
public $sef_rewrite = '1';
public $sef_suffix = '0';
public $unicodeslugs = '1';
In this case meta-tag "base" included href="http://www.mysite.ru/..." - the current page address. For example:
![screen shot 2018-10-07 at 09 06 00](https://issues.joomla.org/uploads/1/0694296814484073b1118819432276e3.png) 
But not only http://www.mysite.ru/
To correct this bug must in file  /libraries/src/Application/SiteApplication.php make the follow change in line 164:
![screen shot 2018-10-07 at 09 13 12](https://issues.joomla.org/uploads/1/14b7d10d98bc98129d59acc69bd191e3.png) 

### Expected result
The meta-tag "base" included href="http://www.mysite.ru/"

### Actual result
The meta-tag "base" included current page address href="http://www.mysite.ru/..."

### System information (as much as possible)
Joomla 3.8x
Joomla settings:
public $sef = '1';
public $sef_rewrite = '1';
public $sef_suffix = '0';
public $unicodeslugs = '1';

**Comment by Quy** [comment]
Please test PR #22565<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22527">issues.joomla.org/tracker/joomla-cms/22527</a>.</sub>
