### ISSUE TITLE
[com_actionlogs] Sort events in alpha order

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#22533]
### Steps to reproduce the issue
Go to `System > Global Configuration > User Actions Log`

`Articles` and `Check-in` are not in alpha order.

### Actual result
```
Banners
Cache
Categories
Configuration Manager
Contacts
Articles
Installer
Media
Menus
Messaging
Modules Manager
News Feeds
Plugins
Redirects
Tags
Templates
Users
Check-in
```

**Comment by SharkyKZ** [comment]
Test PR #22542 please.
