### ISSUE TITLE
[4.0] Bugs in uninstall extension

### ISSUE THREAD

**Issue by schnuti** [joomla/joomla-cms#22531]
### Steps to reproduce the issue
Try to uninstall a plugin ( without a db schema! any with? ).
Try to uninstall a component without a db schema.
Try to unistall a component without J categories.

Related: #21958 
 
### Actual result
Breaks uninstall.

see
https://github.com/joomla/joomla-cms/blob/b863f50f8b3f4872d6e1504b8a05f68ce99f9413/libraries/src/Installer/Adapter/PluginAdapter.php#L204-212

https://github.com/joomla/joomla-cms/blob/b863f50f8b3f4872d6e1504b8a05f68ce99f9413/libraries/src/Installer/Adapter/ComponentAdapter.php#L373-379

https://github.com/joomla/joomla-cms/blob/b863f50f8b3f4872d6e1504b8a05f68ce99f9413/libraries/src/Installer/Adapter/ComponentAdapter.php#L392-400

**Comment by mbabker** [comment]
Actual error messages would be helpful here instead of linking to three random queries.

**Comment by schnuti** [comment]
The lines are not random.

Plugin Error: Class 'Joomla\CMS\Installer\Adapter\ParameterType' not found 
From Debug stack: JROOT\libraries\src\Installer\Adapter\PluginAdapter.php:210 

Component error 1 
Warning
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?_wildcard' at line 3

After "removing" the lines equal to the plugin at ComponentAdapter.php Line 373 I got this
Component Error: Call to a member function clear() on null 
From Debug stack:  JROOT\libraries\src\Installer\Adapter\ComponentAdapter.php:393

No schema and no categories involved in those two extensions.

**Comment by mbabker** [comment]
Wasn't trying to imply they're random, but without error messages or some other context like that comment provides the links on their own really don't say anything helpful.

**Comment by brianteeman** [comment]
This is the exact same error as #21958 - it doesnt need a separate issue so I am closing this here so we only have one issue to track

**Comment by schnuti** [comment]
@brianteeman They are not the same as this is about plugins and components as specified. But never mind.
