### ISSUE TITLE
[4.0] XAMPP 7.2.7/9 Windows. Template Manager. Saving of files fails.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#22535]
### Steps to reproduce the issue
- Use XAMPP(!) with nightly build of today Joomla 4 Sunday, 07 October 2018 02:00:37 UTC
- Go to template manager:
`administrator/index.php?option=com_templates&view=templates&client_id=0`
- Open Casseiopaia template and try to edit a css file.
- After Save or Save&Close: empty grey component area.
- Edits not saved.

**Comment by brianteeman** [comment]
what php version?

**Comment by ReLater** [comment]
The error occurs here: https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_templates/Controller/TemplateController.php#L315

e.g. a file /css/user.css is saved:
`$data['filename']` is `\css\user.css` on WINDOWS
but 
`end($explodeArray)` is `/css/user.css`

So `$data['filename'] != end($explodeArray)` is always `true `and the save method returns `false`.

**BUT: I wonder why we don't see the error message then.**

> what php version?

Tested with XAMPP 7.2.7/win10 64 and another user tested with XAMPP 7.2.9/win?

**Comment by ReLater** [comment]
Please test pr https://github.com/joomla/joomla-cms/pull/22539
