### ISSUE TITLE
[com_actionlogs] Call to undefined method stdClass::execute() 

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#22532]
### Steps to reproduce the issue
Log in the front end as super user.
Edit and save a module.
In the back end, in the `Latest Actions` box, click on the `All Modules` link.
> User admin updated the module All Modules

### Actual result
> Error: 0 Call to undefined method stdClass::execute()

In PHP error log:
> PHP Warning:  Creating default object from empty value in \administrator\components\com_config\config.php on line 28

### System information (as much as possible)
staging

**Comment by infograf768** [comment]
I confirm

**Comment by infograf768** [comment]
the link includes `com_config`
`/administrator/index.php?option=com_config&task=module.edit&id=125`

instead of `com_modules` etc.

**Comment by infograf768** [comment]
I have a possible patch for that one. Will make PR.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/22545
Thank you for testing.
Closing as we have a patch
