### ISSUE TITLE
Frontend editing of categories descriptions

### ISSUE THREAD

**Issue by johanpeters** [joomla/joomla-cms#22548]
i am looking for a way to edit descriptions of categories from frontend, as the same way of articles.

now the only way i know is from the backend.. normal end users you dont give access to the backend.. but the need to edit the text.. so now a admin needs to do that.. its not logical.

**Comment by richard67** [comment]
@johanpeters What do you mean with "article groups"? Categories?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22548">issues.joomla.org/tracker/joomla-cms/22548</a>.</sub>

**Comment by johanpeters** [comment]
Yes.. that is correct.. article categories.



Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: Richard Fath <notifications@github.com> Datum: 09-10-18  19:44  (GMT+01:00) Aan: joomla/joomla-cms <joomla-cms@noreply.github.com> Cc: johanpeters <j.peters@itics.nl>, Mention <mention@noreply.github.com> Onderwerp: Re: [joomla/joomla-cms] frontend editor of Article groups (#22548) 
@johanpeters What do you mean with "article groups"? Categories?This comment was created with the J!Tracker Application at issues.joomla.org/tracker/joomla-cms/22548.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/joomla/joomla-cms","title":"joomla/joomla-cms","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/joomla/joomla-cms"}},"updates":{"snippets":[{"icon":"PERSON","message":"@richard67 in #22548: @johanpeters What do you mean with \"article groups\"? Categories?\u003chr /\u003e\u003csub\u003eThis comment was created with the \u003ca href=\"https://github.com/joomla/jissues\"\u003eJ!Tracker Application\u003c/a\u003e at \u003ca href=\"https://issues.joomla.org/tracker/joomla-cms/22548\"\u003eissues.joomla.org/tracker/joomla-cms/22548\u003c/a\u003e.\u003c/sub\u003e"}],"action":{"name":"View Issue","url":"https://github.com/joomla/joomla-cms/issues/22548#issuecomment-428284879"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/joomla/joomla-cms/issues/22548#issuecomment-428284879",
"url": "https://github.com/joomla/joomla-cms/issues/22548#issuecomment-428284879",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [joomla/joomla-cms] frontend editor of Article groups (#22548)",
"sections": [
{
"text": "",
"activityTitle": "**Richard Fath**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@richard67",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"joomla/joomla-cms\",\n\"issueId\": 22548,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"joomla/joomla-cms\",\n\"issueId\": 22548\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/joomla/joomla-cms/issues/22548#issuecomment-428284879"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 389146816\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by richard67** [comment]
@johanpeters And "editing the subscribtion" means "editing the description", so it finally should be "mainly is about editing descriptions of categories from frontend", right? If so, could you change the description of your issue in this way? Otherwise people might not understand what you want.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22548">issues.joomla.org/tracker/joomla-cms/22548</a>.</sub>

**Comment by johanpeters** [comment]
I have changed the text

**Comment by brianteeman** [comment]
It has never been intended that you can do everything from the front end Tay you can do in the admin

**Comment by micker** [comment]
manage category in front can be a good adding (with ACL for sure)
- add category
- add description / image
- rename / move /edit
with ACL we can check if parent is allowed etc
it a specific feature but interesting for a lighter management

**Comment by johanpeters** [comment]
i know that not everything has to be at the frontend.. but category description would be one of the things you would like to modify in the front by normal users.. and not configure them with backend interface.. to complex for them.. 
daily operations on a website schould be frond.. 
backend is for administrators .. not for editors, etc... 

this is one of the things i miss in Joomla... never the less a greate and powerfull platform..

**Comment by micker** [comment]
One if trick is to use articleanywhere plugin
Create article and insert it un each description

**Comment by johanpeters** [comment]
@micker that could work.. but i realy think Joomla schould make this function by default.
it's not logical to give access to regulair users / editors for editing categorie descriptions.. 
as work around the greate plugins from regularlabs (i use default) is okay..

**Comment by brianteeman** [comment]
Not logical to you but perfectly logical to me.

Creating and updating categories is an administrative task

**Comment by alikon** [comment]
backend task,closing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22548">issues.joomla.org/tracker/joomla-cms/22548</a>.</sub>
