### ISSUE TITLE
Language switcher - current language link

### ISSUE THREAD

**Issue by Giuse69** [joomla/joomla-cms#22555]
### Steps to reproduce the issue
A two languages site EN and IT an article created in the two languages and associated each other, a menu item pointing to article category created in the two languages and associated each other.
Going to the article in English, language switcher module published, SEF enabled with URL rewrite.

### Expected result
The IT flag link points to the Italian article. 
The EN flag (current language) points to current URL. 

### Actual result
Current language flag points to the menu URL, without the last part of the article.

### System information (as much as possible)
Joomla 3.8.12, no additional component nor plugin.

**Comment by infograf768** [comment]
Can't reproduce here. Code implies that an associated item (here an article) has priority over a menu item.

**Comment by Giuse69** [comment]
See for example [here](https://www.lightpoint.info/OTHER/j4/home-en/articles/2-my-first-article): article in English, the Italian flag points to the Italian associated article, the English flag points to menu URL and not to current article. Same for Italian article: English flag link is ok, Italian flag not ok.
Probably because there is no associated English article to current article but... since it is the article itself?

**Comment by infograf768** [comment]
what are the settings of this site? They look pretty weird.
I see homes do not display anything and there are no menu modules with links.

domain.info/OTHER/j4/
domain.info/OTHER/j4/it/

This does not look like a joomla issue. You should use the forums to try to solve your problem.

**Comment by Giuse69** [comment]
I put up this very simple scenario/site just for showing this issue (it is an almost empty site in a subfolder of an exiting site) but you can see the same issue in the main site, for example [here](https://www.lightpoint.info/it/foto/foto-notizie/1384-photokina-2018-notizie)

**Comment by infograf768** [comment]
I confirm.
Is it a real issue? Not really as it is useless to click on the flag for the same language.
This is why we may set the Active Language parameter to No in the module when not using dropdown.
Nevertheless we should try to solve that.

**Comment by brianteeman** [comment]
Make the flag for the active language inactive?

**Comment by infograf768** [comment]
We could do that, but I am looking at another possibility right now.

**Comment by brianteeman** [comment]
Semantically it probably should be disabled/inactive

**Comment by infograf768** [comment]
Displaying the flag or language name without a link would look pretty weird.
Users may think something is wrong when they click on it.
I prepared a PR which will correct the issue and display the current url.

**Comment by brianteeman** [comment]
Just as a "home" link shouldnt be enabled on the home page

**Comment by infograf768** [comment]
Not related at all.
The home link IS enabled. The only difference is that it does not need associations to be associated.
The link in that case is simply
`$language->link = JRoute::_('index.php?lang=' . $language->sef . '&Itemid=' . $itemid);`

**Comment by infograf768** [comment]
Closing as we have a patch
https://github.com/joomla/joomla-cms/pull/22558

@Giuse69 
I can add the full modified file there if you can't apply patches.
