### ISSUE TITLE
[com_actionlogs] Invalid controller: name='form', format=''

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#22551]
### Steps to reproduce the issue
Log in the front end as super user.
Edit an article.
In the back end, in the `Latest Actions` box, click on the article link.

### Actual result
> Invalid controller: name='form', format='' 

### System information (as much as possible)
3.9RC

**Comment by infograf768** [comment]
You mean edit and save I guess?

**Comment by Quy** [comment]
Yes so that the action is logged.

**Comment by infograf768** [comment]
will look tomorrow. On ipad right now.

**Comment by alikon** [comment]
can confirm , similar to #22545

**Comment by infograf768** [comment]
what is the exact link you get?

**Comment by Quy** [comment]
> /administrator/index.php?option=com_content&task=form.edit&id=22

**Comment by alikon** [comment]
please see #22554 as a quick&dirty fix
