### ISSUE TITLE
Admin Login loop when redis selected for session cache.

### ISSUE THREAD

**Issue by chizuoka** [joomla/joomla-cms#22556]
### Steps to reproduce the issue
Set redis for session cache
Login to backend admin

### Expected result
Login successfully

### Actual result
Get stuck on login loop, login goes back to login over and over

### System information (as much as possible)
Joomla! 3.8.12
Ubuntu 18.04

**Comment by HLeithner** [comment]
Are you sure redis is working? it sound like that joomla is unable to create a session.

**Comment by Mat-o** [comment]
Hi,
I use Redis as session manager and cache in many joomla instances with default parameters.
Eight of them are on the same Redis database, and I have no issue of any kind. In that regard, it is better than memcached.
You should look at your Redis server or the Redis connector, or ask your provider if he can provide details.

**Comment by chizuoka** [comment]
Actually i suspect it could not create the session. Which leads to a second possible bug, i keep getting an error "Redis ping failed" however when i run redis-cli from the client machine to the target redis machine, there is no issues at all. I even see joomla sending "Select 0" pings consistently to the redis server. Anyway i can debug what went wrong?

Additionally, it actually worked for a long while, and just suddenly stopped working 2 days ago.

**Comment by PhilETaylor** [comment]
Have you recently added a password for Redis Database 0 ? 

Is Redis Database 0 shared between multiple Joomla sites ?

What happens if you use Redis Database 6 for example?

**Comment by Quy** [comment]
This can be reopened when the requested information is provided.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22556">issues.joomla.org/tracker/joomla-cms/22556</a>.</sub>
