### ISSUE TITLE
Joomla 3.8.13 Warning

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#22564]
### Steps to reproduce the issue

update from Joomla 3.8.12 to Joomla 3.8.13 

### Expected result

no Warning

### Actual result

Warning
JInstaller: :Install: Error SQL Can't DROP 'series_2'; check that column/key exists
Files Update: SQL error file DB function failed with error number 1091 
Can't DROP 'series_2'; check that column/key exists
SQL =
ALTER TABLE `#__user_keys` DROP INDEX `series_2`;

### System information (as much as possible)

Joomla 3.8.13 
PHP 7.1.22

### Additional comments

How to fix this?

**Comment by Quy** [comment]
Related PR #21944

**Comment by Quy** [comment]
Are you using PostgreSQL database?

**Comment by ghost** [comment]
no its MySQL 5.7

**Comment by ghost** [comment]
Disapeared in joomla 3.9.2
