### ISSUE TITLE
Wrapper Iframe not compatible in RESPONSIVE Mode

### ISSUE THREAD

**Issue by rishabhchd19** [joomla/joomla-cms#22569]
Create a Menu and Select Wrapper Iframe. In url put WEBRTC services that uses Microphone and Camera say https://appear.in/yd-xxxxxxxxxx and save it with no scroll bars and Autowidth. Give Public Access and Save. Open the Menu by clicking the link will throw a request to enable MICROPHONE & CAMERA on Desktop CHROME Browser but do not on Android Mobile phones in Responsive Mode because INSPECT ELEMENT>>Console throws an error that iframe in the wrapper is not calling the functions due to change in Chrome Policy recently updated to deprecate support audio and video in iframes. If manually/programatically build an HTML page with iframe and tags <iframe src="https://example.com" allow="geolocation; microphone; camera sandbox=allow-same-scripts"></iframe>, the page loaded successfully on Mobile Responsive Mode. That means Iframe Wrapper is unable to call the iframe tags properly according to new policies of CHROME Browser for deprecate support audio and video in iframes and page URL in Responsive doesn't load and throw Microphone and Video Option on Mobile CHROME Browsers.

 <iframe src="https://example.com" allow="geolocation; microphone; camera"></iframe> must be called and allow the microphone and camera to be used on Mobile phones with Recent CHROME update.

joomla has still not updated Geolocation issue caused by permissions on cross-origin iframes when url is called in wrapper. Chrome recently updated to deprecate support audio and video in iframes. Hence a small code change always required. I.e.<iframe src="https://example.com" allow="geolocation; microphone; camera"></iframe> to work on recent CHROME browser on Android Mobiles.

**Comment by ghost** [comment]
@HLeithner  can you please comment?

**Comment by HLeithner** [comment]
The Allow attribute is only supported on chrome, as long as it's not a standard it makes less sense for us to support it.

But you can create a template overwrite and add the allow attribute to the iframe-tag.

I'm closing this, if you have questions how to create a override please ask in the forums for help.

**Comment by ghost** [comment]
thanks @HLeithner

**Comment by brianteeman** [comment]
Not sure what is going on here. This was closed in 2019 but the bot reopened it in 2023. From what I can understand it is not relevant and should be closed again
