### ISSUE TITLE
[4.0] - Admin User Menu hidden behind Help Button

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#22561]
Alpha 5 dev nightly, see:

<img width="214" alt="screenshot 2018-10-09 13 49 05" src="https://user-images.githubusercontent.com/1400982/46670491-42d6b600-cbca-11e8-99f8-3e6ecb2fa76b.png">

button is in front of the dropdown admin user menu.

**Comment by brianteeman** [comment]
Closed see #22610
