### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by johanpeters** [joomla/joomla-cms#22568]
### Is your feature request related to a problem? Please describe.
default 404 error page is not user and search engine friendly

### Describe the solution you'd like
build in 404 error page handling so that the 404 page is build based on the template.. with module positions for example smart search etc..

**Comment by mbabker** [comment]
The error handling is rewritten in 4.0 to allow a template's `error.php` layout to behave the same way as the `index.php` layout.  This cannot be done in 3.x due to B/C concerns.

**Comment by brianteeman** [comment]
Closed for the reasons stated above
