### ISSUE TITLE
force 2FA use for users

### ISSUE THREAD

**Issue by johanpeters** [joomla/joomla-cms#22566]
### Is your feature request related to a problem? Please describe.
Joomla supports 2FA for users.. but currently there is no option to force the use of it before a user can fully logged in to the website.. currently i use a 3rd party exention to arrange this.. but it would be greate to have this build in the core.. 

### Describe the solution you'd like
1. user logged in
2. if 2FA is configured.. 2FA authentication 
3. if 2FA is not yet configured the user must first configer 2FA complete before he can do anything else on the website.

**Comment by PhilETaylor** [comment]
I have repeatedly approached this and repeatedly got shot down. 

Even when I suggested the 2FA plugins were enabled by default so that their features were at least seen and not hidden (The tabs in edit user screen don't show until the plugins are enabled), and that idea got shot down. :-(

**Comment by johanpeters** [comment]
@PhilETaylor .. i don't understand it why.. Besides functionality.. Security schould be default.. (GDPR demands.. Security by default and Security by design).. 
I can understand why its not enabled by default.. but a message (after installation) or Security check schould notify the admin of the existance and use.. 
And if you enable you should be able to manage (force 2FA or option).. in the core there is now option to force 2Fa..

luckly for us.. there is a 3rd party solution for this.. 
Akeeba LoginGuard... offers al the options you whant.. incl. force the use of 2FA at login.. 
i

**Comment by PhilETaylor** [comment]
Like you said, there are third party solutions that are already available to fix this in Joomla, while that is the case, Joomla will probably never change its mind on running a "security first" project, instead of a "lets not upset users" project... 

Thats the "joy" of a mass distributed project that has to cater for the "worse" and the "best" users. People still view "security" as a pain in the arse, instead of something to be celebrated and educated 

(My 11 year old has her own Laptop with  FileVault enabled, Her own GPG key, SMIME email encryption enabled on all her iDevices, and her own Yubikey! Educating people about security is not as difficult as people make out!) 

So if you search this tracker you will see that your request has been made many times, and many times it has come to a dead end.

**Comment by brianteeman** [comment]
As @mbabker already said to you  

> Come up with a way to do it that does not lead to user confusion (UX fail) and submit a pull request. I will bend over backwards to personally see your PR is reviewed at the expense of one of the other 97 things I probably should be doing at the time. Ball's in your court because I for one don't have the time to be doing pretty much anything else right now.

**Comment by johanpeters** [comment]
indead... that is the main issue i think.. 
But security does not have to be hard, user unfrendly etc.. furthermore.. when hacks of joomla websites go public.. its killing for the project.. 
and when the integrate security by default and design.. other extentions can rely on that and not create al there own security settings.. One Security place for the complete site.. 

perhaps a sepperate distribution.
1. Joomla basic (current settings)
2. Joomla Secured (firewall, 2FA, Backend Security, database Security, CRC checks, unable to install (non approved) extentions outsite extentions.joomla.org). etc..

**Comment by johanpeters** [comment]
@brianteeman 
> As @mbabker already said to you
> 
> > Come up with a way to do it that does not lead to user confusion (UX fail) and submit a pull request. I will bend over backwards to personally see your PR is reviewed at the expense of one of the other 97 things I probably should be doing at the time. Ball's in your court because I for one don't have the time to be doing pretty much anything else right now.

take a look at Akeeba LoginGuard.. the already made it.. and user friendly.. 
just adept it in the joomla core.. thats all fokes..

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/issues/20373#issuecomment-389292769

**Comment by Quy** [comment]
Please test PR #26253<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22566">issues.joomla.org/tracker/joomla-cms/22566</a>.</sub>
