### ISSUE TITLE
Checkbox field type does not automatically check when default value is 1

### ISSUE THREAD

**Issue by JamilaCisse** [joomla/joomla-cms#22575]
### Steps to reproduce the issue

1. Add a checkbox field to a component
2. Set the default value to 1
![screenshot from 2018-10-10 13-29-58](https://user-images.githubusercontent.com/28758211/46740114-52c1c900-cca2-11e8-953f-1c442bf94060.png)

### Expected result
When opening the form, the checkbox is checked

### Actual result
When opening the form, the checkbox is unchecked
![screenshot from 2018-10-10 13-27-19](https://user-images.githubusercontent.com/28758211/46740151-6a994d00-cca2-11e8-94f6-1d92b07c27fb.png)

### System information (as much as possible)
Joomla! 3.8.13

**Comment by SharkyKZ** [comment]
`default` attribute here defines the value of generated input element. Use `checked="true"` to indicate that the checkbox should be checked by default.

**Comment by aDaneInSpain** [comment]
@SharkyKZ thanks for replying. Unfortunately the [Joomla documentation](https://docs.joomla.org/Checkbox_form_field_type) is not reflecting this feature but I have submitted an issue to them.

Would you mind explaining to me what the `default` value is used for. I don't really understand it.

**Comment by SharkyKZ** [comment]
It sets the value of the field. A checkbox can have any value, not just `1`. For example,  checkbox field with `default="myValue"` will generate `<input type="checkbox" value="myValue">`.

**Comment by aDaneInSpain** [comment]
But then why not just set `value="myValue"`?

**Comment by brianteeman** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#Checking_boxes_by_default

**Comment by aDaneInSpain** [comment]
@brianteeman That just shows how to (in HTML) set a checkbox to be checked, I don't really see how that is relevant here as we are discussing how to get Joomla to write that code, not how to write that code ourselves.

My main question now is what is the difference between setting `value="1"` and `default="1"` in the *XML* definition of a field.

**Comment by aDaneInSpain** [comment]
In fact from the documentation:

What would be the difference between

`<field name="show_title" type="checkbox" label="Show title" description="Show the title of the item" value="1" default="0" />`

and 

`<field name="show_title" type="checkbox" label="Show title" description="Show the title of the item" value="1" default="1" />`

**Comment by brianteeman** [comment]
It is relevant because the way to have a checkbox default to being checked is to give it an attribute of checked

You can see this in the core of joomla here https://github.com/joomla/joomla-cms/blob/673466ad3f9186829a8604d80ba881f997d59c0d/administrator/components/com_users/models/forms/mail.xml#L47

The attribute checked is **not** the same thing as a value. It is all in the link I posted.

**Comment by aDaneInSpain** [comment]
I am fully aware of how a checkbox is checked in the browser but that is not what I am now asking. 

Now I know that I should use `checked="true"` or I guess like your example `checked="1"` to check the checkbox inside Joomla's XML file to get Joomla to write `checked` inside the HTML input tag (even though this was omitted from the documentation).

What I do not understand is what is difference between `default` and `value`? To me it makes no sense for a checkbox to have a `default` attribute, In fact the specifications does not have a `default` attribute so why do we in Joomla and what does it do?

**Comment by mbabker** [comment]
The Joomla form XML schema is not a one-for-one match with the HTML spec on the HTML input types, remember that the XML schema is a definition of the form and that it is parsed to create the HTML representation (in many cases the attributes you specify in the XML and what actually renders in HTML do align but there are several attributes that only apply in the context of our XML schema, including `translate_label`, `translate_description`, `labelclass`, and `showon`).

`default` is an attribute available to all form fields (as it is defined as part of the base `Joomla\CMS\Form\FormField` class) which specifies a default value for a field if when the form is submitted the field is empty; this is applied while the form data is passed through `Joomla\CMS\Form\Form::filter()`.

You're right that in the context of a checkbox field it doesn't really make sense.  Ignore it if you choose, but it'd be pretty painful to refactor the form field classes to remove that particular attribute from the checkbox field type.

**Comment by aDaneInSpain** [comment]
I figured this was most likely the answer. So in my opinion it should just be ignored, which is what I will ask the documentation team to do as it will otherwise be confusing as people may think that setting the `default` to the same value as `value` will check the checkbox.
