### ISSUE TITLE
[3.9 Upgrade] Missing administrator modules

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#22577]
### Steps to reproduce the issue
Install 3.8.13
Upgrade to 3.9RC
Create a new module for Administrator
The following modules are missing:

> Action Logs - Latest
> Privacy Dashboard

### System information (as much as possible)
Performed Database Fix and Discover

**Comment by infograf768** [comment]
afaik the modules and plugins related to privacy and actionlogs may have to be enabled in `Manage`
