### ISSUE TITLE
Only the first page is printed

### ISSUE THREAD

**Issue by alve89** [joomla/joomla-cms#22574]
### Steps to reproduce the issue
Opening a page (designed in Gantry) that contains a navigation, breadcrumbs and a very long table in a module (implemented as module instance). 
Press Ctrl + P to print the page.

### Expected result
Printing the whole page (as I didn't add any @media print attributes) but the default Gantry printing CSS.

### Actual result
Only the first page is printed.

### System information (as much as possible)
Joomla 3.8.13
Gantry 5.4.26

### Additional comments
Other pages (of the same site, so also designed with Gantry) are printed completely, so I think the problem is the module.

**Comment by HLeithner** [comment]
That sounds like a template problem and not a Joomla problem, please use the forum.joomla.org or contact you template vendor.
