### ISSUE TITLE
Joomla 3.8.13 installation issue - 502 Bad Gateway

### ISSUE THREAD

**Issue by thaneshs** [joomla/joomla-cms#22573]
### Steps to reproduce the issue
We have received php upgrade warning on administrator as below,

![upgrade_warning](https://user-images.githubusercontent.com/41372392/46733477-1005ee00-ccae-11e8-997d-485883f6c0d3.png)

We have upgraded our server to latest php version. Once server upgraded, we are facing - 502 Bad Gateway error. We tried to install latest version of Joomla3.8.13 directly to server. But we are not able to install Joomla in server.  

Our current server PHP version is - PHP 7.3

PHP 7.3.0RC2 (cli) (built: Sep 25 2018 09:07:55) ( NTS )
Copyright (c) 1997-2018 The PHP Group

### Actual result
Console response on Joomla installation:

[HTTP/2.0 502 Bad Gateway 1867ms]

### System information (as much as possible)

PHP 7.3.0

### Additional comments

We are able to access Joomla installation page, but not able to continue next step to install Joomla. 

![installation_error](https://user-images.githubusercontent.com/41372392/46733576-565b4d00-ccae-11e8-910e-d30eba3cff6c.png)

Is there any issue with PHP version support on Joomla3.8.13 ? Can you please help me out on this?

**Comment by HLeithner** [comment]
Can you please check the server error.log?

**Comment by thaneshs** [comment]
Yes, we are getting the following error when try to continue installation,

[core:notice] [pid xxxxx]: child pid xxxxx exit signal Segmentation fault (11)

**Comment by HLeithner** [comment]
so php crashes... then I think you should report this problem to php.net because this shouldn't happen

**Comment by HLeithner** [comment]
btw. I using php 7.3.0rc2 too on my development server and it works for me, so it shouldn't be joomla.
Did a update to 3.8.13 without problems.
Maybe you can make a strace or gdb for the php guys.

**Comment by HLeithner** [comment]
@brianteeman can be closed and reopened if needed.
