### ISSUE TITLE
Tagged Items ugly Joomla Bug

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#22589]
### Steps to reproduce the issue

Menu Title > Drop number

Details
Menu Item Type > Tagged Items
Tag > Drop number
Content Type > Article

Menu > Main menu
Parent Item > SMALL
Ordering > Drop number

### Expected result

/small/drop-number/brin-te

### Actual result

/?view=article&id=54:brin-te&catid=12

### System information (as much as possible)

Joomla 3.8.13
PHP 7.1
MySQL 5.7

### Additional comments

How to fix this?

**Comment by infograf768** [comment]
Have you created a menu item for the category of the article, or a List All categories menu item?
If not, test that.

**Comment by csthomas** [comment]
Take a look at the nice list:
https://github.com/joomla/joomla-cms/issues/22450
https://github.com/joomla/joomla-cms/issues/22036
https://github.com/joomla/joomla-cms/issues/21935
https://github.com/joomla/joomla-cms/issues/20892
https://github.com/joomla/joomla-cms/issues/20242
https://github.com/joomla/joomla-cms/issues/19997
https://github.com/joomla/joomla-cms/issues/19729
https://github.com/joomla/joomla-cms/issues/19537
https://github.com/joomla/joomla-cms/issues/19497
https://github.com/joomla/joomla-cms/issues/18818
https://github.com/joomla/joomla-cms/issues/18771
https://github.com/joomla/joomla-cms/issues/17719
https://github.com/joomla/joomla-cms/issues/17096
https://github.com/joomla/joomla-cms/issues/16496
https://github.com/joomla/joomla-cms/issues/14175

I prepared PR to solve that on J4 but the is no testers for https://github.com/joomla/joomla-cms/pull/22229

I can prepare similar PR for J3 but it requires more people to be involved. Testers are needed. Last time when I did it, I made a few mistakes and PRs were reverted in J3.8.5.

**Comment by ghost** [comment]
Yes menu item for the category of the article Menu Item Type > Tagged Items

but Actual result still is 

/?view=article&id=54:brin-te&catid=12

@infograf768 can you be more specific how to test this or is there a documentation ?

**Comment by ghost** [comment]
@csthomas  the list of bugs is big please please prepare similar PR for J3 if it solves this joomla bug

**Comment by SharkyKZ** [comment]
Do you have `URL Routing` set to `Modern`?

**Comment by ghost** [comment]
Yes URL Routing set to Modern

**Comment by csthomas** [comment]
My PR would only replace `/?view=article&id=54:brin-te&catid=12` by something like `/component/content/article/54:brin-te?catid=12` or `/component/content/article/12-your-category-alias/54:brin-te`.

If there are more people interested, I will try to find more time to do it.

If you want to have a nicer URL, you need to set the menu item for each top category or for categories view. You should find more information in mentioned issues above.

**Comment by ghost** [comment]
@csthomas @infograf768 so it is imposible to make 

Expected result
/small/drop-number/brin-te
Actual result
/?view=article&id=54:brin-te&catid=12

after pr the best joomla can make is /component/content/article/12-your-category-alias/54:brin-te. ? not /small/drop-number/brin-te ?

**Comment by SharkyKZ** [comment]
You can't use one component (in this case `com_tags`) to automatically build an URL for another component (`com_content`). You can only do this manually by making the article a child menu item of Tagged Items menu item. You'd have to do this for every article tagged with your tag. To avoid that, you should use Categories, not Tags, to structure your site.

**Comment by csthomas** [comment]
Without the appropriate menu items it is impossible. Please read mentioned issues to see what options do you have. @SharkyKZ's comment is correct.

I suggest to take a look at https://github.com/joomla/joomla-cms/issues/22450#issuecomment-426670719 . As the home page, you can set the category view for "Top Category". Other categories move into "Top Category".

**Comment by ghost** [comment]
@SharkyKZ  could you please explain what is the correct way to get this using tags?

Expected result
/small/drop-number/brin-te
Actual result
/?view=article&id=54:brin-te&catid=12

**Comment by ghost** [comment]
@infograf768  is there documentation on how these Tagged Items should work using modern routing?

**Comment by infograf768** [comment]
This imho is not related to tagged items, it is a general issue with Modern routing.

Until @csthomas patch is tested and does work without B/C issues, the best solution [again] is to create a `List All Categories` menu item, even hidden, as a root menu item in your menu.
Let's say this menu item alias is `listallcat`

You will never get anyway
`/small/drop-number/brin-te`

but
`/listallcat/brin-te`

**Comment by infograf768** [comment]
I mean if you do not have a direct menu item to the article.

**Comment by ghost** [comment]
@infograf768 After you create a menuitem for the tag you still get /component/tags/tag/tag-name when you click on article and scrool down to the tag.

What are your steps to reproduce /tags/tagname ?

**Comment by radioagent** [comment]
I have menu item with category blog. Category contain 45 articles. When i press to this menu item i see 10 articles. And all these articles have same tag. It looks like that tag filter is applied. 
If i will manually go to links with ?filter_tag[0]="something" i can change set of articles in the blog without filters. It looks like filtering is applied and stored somewhere when i try to look on list of all articles.

Is it same error? Or i should create new bug report?

**Comment by csthomas** [comment]
@radioagent Your issue is different. The filters are applied in menu item - go to backend, edit the menu item and select/deselect tags.

**Comment by ghost** [comment]
@Hackwar can you please comment about the Router-Aspects?

**Comment by Hackwar** [comment]
This is expected behavior and your website is not correctly configured. Even if @infograf768 thinks it's wrong, you still have to create menu items for your content, otherwise you get crap URLs. That the tagging system is also crap, is a different story. I wouldn't know what else to say about this.

**Comment by brianteeman** [comment]
@Hackwar please be careful with your words

**Comment by ghost** [comment]
@Hackwar thanks for Comment, closing Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22589">issues.joomla.org/tracker/joomla-cms/22589</a>.</sub>
