### ISSUE TITLE
Actions logged for guest users are not displayed on "User Actions Log" view in backend

### ISSUE THREAD

**Issue by ankushmaherwal** [joomla/joomla-cms#22586]
### Steps to reproduce the issue
While implimenting the plugin of type ActionLog its possible to log actions of guest users. In many extensions guest users are allowed to place orders and do other actions.  

### Expected result
Using Joomla methods the implimentor can log actions for guest users but the actions are not shown in the "User Actions Log" view in backend.

### Actual result
If Joomla method ActionlogsModelActionlog::addLog($messages, $messageLanguageKey, $context, $userId = null); allowes to add action logs for guest users then the logs should be shown in the "User Actions Log" view in backend.

### System information (as much as possible)
Joomla version "Joomla! 3.9.0-rc"

**Comment by alikon** [comment]
please test #22588

**Comment by brianteeman** [comment]
Closed as we have a pr for testing
