### ISSUE TITLE
J3.8.13 backend edit password issue

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#22598]
### Steps to reproduce the issue

Create new admin account, check reset password on next login.

Login backend with the new account. You get the edit user account, to change the password. But when you save then you get the error.

Looks like the security fix broke the edit password check feature on the backend.

### Expected result
Password saved.

### Actual result

Error

An error has occurred.
403 Access Denied 

### System information (as much as possible)

J3.8.13

**Comment by infograf768** [comment]
Looks like same issue in staging/3.9.0RC

**Comment by infograf768** [comment]
Setting as release blocker

**Comment by infograf768** [comment]
Testing again and I can't reproduce on staging.

**Comment by zero-24** [comment]
I can not reproduce this with the given instructions too. Can you please a bit more precise which user with what access data you have created and is it possible to reproduce this on a 3.8.13 clean install?

> Looks like the security fix broke the edit password check feature on the backend.

Well it should not as nothing in this direction has been touched. Please check: https://github.com/joomla/joomla-cms/commit/27ca70a097a3d64f958bfee77a21f33002c33bfc

**Comment by brianteeman** [comment]
I can not reproduce this with the given instructions too.

**Comment by PhilETaylor** [comment]
I can not reproduce this with Joomla 3.8.13 on a live site.

**Comment by 810** [comment]
I can't reproduce the issue on new installs.
I got the issue on a clients website. 

Mhh got it now, looks like admin tools was blocking it.

**Comment by PhilETaylor** [comment]
> looks like admin tools was blocking it.

Disabling the editing of Joomla Users in the backend is a standard feature of @nikosdion Admin Tools, that gets applied (IIRC) when you run the "Quick start wizard" in Admin Tools.

This is not a Joomla core issue then.
