### ISSUE TITLE
Tags bug

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#22595]
### Steps to reproduce the issue

modern sef on click on tagged article tag

if you click on rticle title you get /small/drop-number/brin-te

but if you click on tag yu get /?view=article&id=54:brin-te&catid=12

### Expected result

/small/drop-number/brin-te

### Actual result

/?view=article&id=54:brin-te&catid=12

### System information (as much as possible)

Joomla 3.8.13
PHP 7.1
MySQL 5.7

### Additional comments

How to fix this?

**Comment by ReLater** [comment]
Already reported here: https://github.com/joomla/joomla-cms/issues/22589

**Comment by ghost** [comment]
@ReLater This is similar but diferent joomla tag bug
