### ISSUE TITLE
[com_fields] 'Menu' field type is needed

### ISSUE THREAD

**Issue by sridhar-a** [joomla/joomla-cms#22590]
### Steps to reproduce the issue
- Login to Joomla
- Go to 'Content > Fields'
- Click 'New' (i.e. Create New Field)
- In the 'Type' drop-down list, there is no 'Menu' type found (attached screenshot).

### Expected result
A New Field with type 'Menu' will be created.

### Actual result
Since, there is no New Field with Type 'Menu', it can not be created and used in the Articles.

### System information (as much as possible)
Joomla 3.8.12
Windows 10

### Additional comments
It will be great and will be much helpful, if this New Field 'Menu' will be added in the Joomla CMS in com_fields.
![screen shot 2018-10-12 at 07 17 50](https://issues.joomla.org/uploads/1/739fb31c58708d0b89322a66b90acdf5.png)

**Comment by tonypartridge** [comment]
Hmm, you could use an editor field and then click menu in the editor. And insert the menu item?

**Comment by pepperstreet** [comment]
I like the idea, because it does exist as a core XML field.
Easy and secure method to allow quick links to the site's menu structure.

**Comment by brianteeman** [comment]
This was created but sadly has not been accepted

**Comment by N6REJ** [comment]
@brianteeman maybe link it so it can be rejuvenated

**Comment by joomdonation** [comment]
There is PR https://github.com/joomla/joomla-cms/pull/39192 which implements this request. Please help testing so that we can have this feature available in core. Thanks !
