### ISSUE TITLE
[4.0] Using CDN

### ISSUE THREAD

**Issue by BaleshSrle** [joomla/joomla-cms#22609]
### Is your feature request related to a problem? Please describe.

Because Joomla 4 is becoming ever so elaborate and heavy for servers, my idea is to make Joomla 4 as lite as possible. I think that there are some files that take space (like JQuery, HTML5Shiv)

### Describe the solution you'd like

My solution is to use CDN on Joomla 4, because it will be fewer files to upload to server via FTP.

### Additional context
On this links you can find files which can be used in Joomla 4. Yo can even select which version of this files can you insert in Joomla.
https://cdnjs.com/libraries/mootools
https://cdnjs.com/libraries/mootools-more
https://cdnjs.com/libraries/jquery
https://cdnjs.com/libraries/jquery-migrate
https://cdnjs.com/libraries/html5shiv

**Comment by SharkyKZ** [comment]
Joomla! must ship with all required files. Otherwise it would be unusable where internet connection is not available (e.g. intranets).

**Comment by brianteeman** [comment]
Closed for the reason stated above.

**Comment by BaleshSrle** [comment]
What does Intranet has with CDN servers? If you want to know more about CDN's you can wisit https://en.wikipedia.org/wiki/Content_delivery_network . 

BTW, does anyone know about Cloudflare? The files of those links (from my previous post) are hosted on Cloudflare CDN servers. If you want to have more info about Cloudflare you can visit https://www.cloudflare.com/network/ & https://www.cloudflarestatus.com/ .

**Comment by brianteeman** [comment]
If you are using an intranet then you cannot use a cdn

**Comment by BaleshSrle** [comment]
Changed HTML5Shiv from Joomla's original link to new https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js in https://baleshevich.dobojcaffe.com/v2/ and it works.

**Comment by brianteeman** [comment]
We are not saying that if you use a cdn it will not work.

We are saying if you are on an intranet and do not have access to the entire internet then a cdn will not work as you cannot access the files.

This is why the core of joomla must ship with all the files

**Comment by BaleshSrle** [comment]
> 
> 
> We are not saying that if you use a cdn it will not work.
> 
> We are saying if you are on an intranet and do not have access to the entire internet then a cdn will not work as you cannot access the files.
> 
> This is why the core of joomla must ship with all the files

I must have read "Intranet" because @SharkyKZ might wrote that.
BTW, how does Joomla! uses CDN for Banners @ Joomla! Volunteers Portal ?

**Comment by ghost** [comment]
>  BTW, how does Joomla! uses CDN for Banners @ Joomla! Volunteers Portal ?

Please ask on [Forum](https://forum.joomla.org/)

**Comment by BaleshSrle** [comment]
@franz-wohlkoenig I mean, if Joomla! can use CDN for Joomla! Volunteers Banners, why can't it use CDN for JQuery, HTML5Shiv, Bootstrap & Mootools . Right?

**Comment by brianteeman** [comment]
> We are not saying that if you use a cdn it will not work.
> 
> We are saying if you are on an intranet and do not have access to the entire internet then a cdn will not work as you cannot access the files.
> 
> This is why the core of joomla must ship with all the files

**Comment by mbabker** [comment]
Out-of-the-box, Joomla cannot require files be loaded from a third party CDN.  Someone using Joomla can opt to use a CDN if they choose.

If you are in a closed network environment (AKA intranet), where there is limited or no access to the public internet, then loading files from a CDN is not going to be possible.  This is basically the same as if you're working on a copy of a website on your local computer that has its internet access turned off.

Please remember that not every PHP application is deployed somewhere that can just load anything from anywhere in the world.  If Joomla, or any CMS, defaulted to requiring a CDN to load resources, then those platforms would immediately be unusable to anyone who is intending on deploying said CMS into a closed network.

**Comment by BaleshSrle** [comment]
Guys, are you sitfing on your ears?! Can you read the only compent of @SharkyKZ.

I DON'T USE INTRANET, AND I WANT FROM JOOMLA TO USE CDN, BECAUSE SOME BRAINIACS WANT TO ADD MORE FILES TO UPLOAD TO SERVER, AND SOME OF US DON'T HAVE UNLIMITED SPACE ON SERVERS.
I WANT FROM JOOMLA! TO TAKE SOME OF HEAVY FILES LIKE BOOTSTRAP, JQUERY, HTML5SHIV AND UPLOAD THEM TO THEIR CDN SERVER(S) , OR TO **USE ONLY MINIFIED VERSION** OF THIS FILES, BECAUSE JOOMLA! IS GETTING TOO HEAVY AND DEMANDING TO UPLOAD VIA FTP.

**Comment by mbabker** [comment]
You can configure Joomla to use a CDN, nothing stops you from doing that.

Joomla cannot be set up to by default require a CDN or to not ship the media files that it requires.  That makes Joomla unusable in a closed network environment, period.  And no, this is not a hypothetical issue.  My first experience with Joomla was on one of those closed networks where no CDNs are available at all.

As this has been repeatedly answered as to why it is not feasible to strip the default distribution of Joomla of media files or to require public internet access to a CDN, I suggest locking this issue as resolved.
