### ISSUE TITLE
[4.0] Colour layout swatch positioning

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#22604]
### What needs to be fixed

The positioning of the colour fields/layout

### Why this should be fixed

Due to the increased height of inputs with the new template and jQuery Minicolours not adapting, the swatch is misaligned

### How would you fix it

Add some styling overrides for the current picker as shown below:

```
.minicolors-theme-bootstrap .minicolors-swatch {
    top: 50%;
    left: 8px;
    border-radius: 0;
    transform: translateY(-50%);
}
```

### Screenshots

![screeny](https://user-images.githubusercontent.com/2019801/46915710-1c889000-cfa7-11e8-92e2-98e225697238.png)

**Comment by brianteeman** [comment]
@C-Lodder can you submit a PR please

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/22628

**Comment by brianteeman** [comment]
thanks @C-Lodder
