### ISSUE TITLE
Redirect to the same page after login

### ISSUE THREAD

**Issue by ZerooCool** [joomla/joomla-cms#22600]
### Is your feature request related to a problem? Please describe.

Joomla still does not integrate natively the connection and redirection on the same page?
Could this be improved for Joomla 4?
Come on, we're counting on you for a Joomla 4 version full of practical news!

### Describe the solution you'd like

In 2015 I used the BT Login module. In 2015 again I tested mod_je_login.

The mod of connection that I use since September 2016: SCLogin
www.sourcecoast.com/index.php?option=com_ars&view=release&Itemid=248

### Additional context

https://docs.joomla.org/How_do_you_redirect_users_after_a_successful_login%3F
https://www.joomla-tips.org/developer-tools/redirect-users-after-a-successful-login.html
https://stackoverflow.com/questions/5475839/joomla-login-redirection-back-to-page-to-the-previous-page

**Comment by brianteeman** [comment]
Can you give an example of the type of page you are on when you need to login - I cannot replicate your problem

![more](https://user-images.githubusercontent.com/1296369/46914453-cc550200-cf95-11e8-8e22-7fc6647f6d8a.gif)

**Comment by ZerooCool** [comment]
Hello Brian,

The links I added are not really a problem.
I did not try to patch the code, as proposed in the Joomla documentation.

I use the SCLogin module today, on my main site, which allows me to redirect pages, to stay on the same page, when I connect.

By default, it seems to me that Joomla does not offer this option.
Joomla offers to redirect to a page of your choice, for example, to the home page.

However, if we visit an article, or a forum (Kunena) when we connect, we want to stay on the same content, so be redirected to the page we were consulting.

For this reason, I ask if for Joomla4, this option could be integrated by default, which would be a great better, at the level of the connection management.

**Comment by brianteeman** [comment]
and as i showed above I do not have the problem you describe

**Comment by ZerooCool** [comment]
By using Joomla by default, are you redirected automatically to the page?

If you go on the forum page Kunena 127 ... You connect on this page, and, you stay on this same page?

Strange because in all my tests with Joomla, the redirection is always made to the home page.

**Comment by brianteeman** [comment]
i dont use kunena so i dont know how that works. i can only comment on how the core of joomla works. if the issue is with kunena you should ask on their forum

**Comment by ZerooCool** [comment]
This is a joomla issue and I confirm that the redirection when connecting does not work.
We do not stay on the current page.

So it's really very painful to use joomla, when you connect, and, we do not stay on the same page.

**Comment by ggppdk** [comment]
@ZerooCool 

Joomla has 2 different login forms
1. the login form of the com_users component 
2. the login form of the login module

---- 

1. The login form of the com_users component , makes use the 'return' variable, a base64 encoded URL that is normally set by the extension that redirected you to 'login form' of the com_users component 

(this is the example that brianteeman showed above that shows returning you to the original component that redirected you to the login form)

2. The (**Joomla**) login module does not need the 'return' variable, because it is displayed next to the current component,
and its default behavior is to stay to current page,
(so the form contains a hidden 'return' FORM field that point to current page)

This is mentioned in the description of the parameter "**Login Redirection Page**" but you must click to clear the parameter "**Login Redirection Page**" , and save the login module
- if "**Login Redirection Page**" is not empty, then its value will be used instead of current page

If you have multiple login modules then make sure that you are editing and saving the correct one

**Comment by ZerooCool** [comment]
In fact, I do not think I use a module directly because I go through a menu link.
index.php? option = & view = login com_users

So that's all there is more native to Joomla.

The Joomla that I use is brand new and beautiful, and I realize that it's really annoying to have this type of behavior at the connection.

**Comment by brianteeman** [comment]
What you are saying makes no sense. Please record a short "movie" to show us exactly how you have this configured.  You can use licecap for this https://www.cockos.com/licecap/

**Comment by ZerooCool** [comment]
Hi, https://www.dropbox.com/s/r54edq0wwnpsb5x/ok.gif?dl=0

The picture.
Thank you for licecap.

**Comment by brianteeman** [comment]
Please change to use the login module - NOT the component menu item. That should work how you are expecting it to work.

**Comment by brianteeman** [comment]
Unless you only want to have access to those pages if you are logged in, If that is the case then you can simply set the access level for those menu items to registered.

**Comment by ZerooCool** [comment]
This is totally the purpose of my question.
I could and I will test with a module, but, aesthetically, I would have preferred to use a menu link, more discreet.

It may not be possible?
I do not really know what would prevent it from happening.

Could not the menu link be "enhanced" to allow this?

**Comment by brianteeman** [comment]
The menu link can not know where you want to go as it is is generic

**Comment by ZerooCool** [comment]
hello, precisely, and, I'll stay on this question, which is really the subject of my message and my questions!

Is it technically possible to allow to change this, natively, in Joomla!

Is it possible to recover the value of the current url, at the moment we click on the menu link! ?

If we can retrieve the value of the current URL, at the time of the click, we can tell him to return to this address, once the connection is established?

It would be "simply" an option to modify, natively! ?

If the connection module allows it, I think the connection link should allow it too?

It may not be a priority to do so.
Or maybe I do not understand technically what could stop it?
I still find that this menu link should be able to behave like the module, and, allow the redirection to the page where it has been activated.
It would therefore be good to be on the same page, without returning to the main menu.

Admittedly, in a site with many content, it is really tedious to return to the main menu, when connecting, because then we must find the content that we were consulting.

These are unnecessary navigation actions.

Now, if technically it's not possible, sorry for making you waste time answering me.

One last time, I would like to raise awareness of the interest, at the level of the interaction Man / Machine, if the link of menu could be as effective as the module, I think that this squeezed a plus, for Joomla, it would be surely more coherent.

One could consider in the menu link settings options, the choice to return to the home page, or, to stay on the same page, which means, retrieve the current url at the time of the action, for to go back there.

Is it so complicated to integrate?

**Comment by brianteeman** [comment]
it is not possible because it is not needed . the module already does exactly what you want and it is designed for that specific purpose

**Comment by ghost** [comment]
closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22600">issues.joomla.org/tracker/joomla-cms/22600</a>.</sub>
