### ISSUE TITLE
[custom field] "Read More" in content field disappear after saving

### ISSUE THREAD

**Issue by walturbo** [joomla/joomla-cms#22622]
### What needs to be fixed
I use the custom fields.

- I have compiled content field and custom fields in article.
- I have added command "read more" in content field. "Read more" is in last row, after theren't nothing.
- In options of article, select "hidden" in introductive text.

When save article the code of "read more" disappear, will be remove to the system.
In the frontend of the article the introductive text will appear and following the custom fields.

### Why this should be fixed
Because "read more" disregards existing custom fields

**Comment by ghost** [comment]
does the Issue exist on latest Version?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22622">issues.joomla.org/tracker/joomla-cms/22622</a>.</sub>

**Comment by ghost** [comment]
closed as no Answer, Issue can always reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22622">issues.joomla.org/tracker/joomla-cms/22622</a>.</sub>
