### ISSUE TITLE
Database import lib only imports first table

### ISSUE THREAD

**Issue by gslitt91** [joomla/joomla-cms#22620]
I tried to file bug in joomla core lib "JDatabaseImporterMysqli" .  But not able to.

 Here are bug details in function mergeStructure

it only merges first table structure .
  This code "if ($queries = $this->getAlterTableSql($xml->database->table_structure))"  has problem .

Solutuion:  Change it  to this "if ($queries = $this->getAlterTableSql($table)) {" .

  

If you feel there's a bug in Joomla, please report it using the following process:
http://docs.joomla.org/Filing_bugs_and_issues

Let us know if you have any questions.

Thanks!

Kind regards,
Nick

_Originally posted by @nicksavov in https://github.com/joomla/joomla-cms/issues/694#issuecomment-12730296_

**Comment by brianteeman** [comment]
No idea what this relates to - closed

**Comment by ggppdk** [comment]
SPAM by bot

**Comment by gslitt91** [comment]
> No idea what this relates to - closed

https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/database/importer.php  this file has issue at line 190 .

**Comment by gslitt91** [comment]
steps to reproduce
1. Export here is code for export
  require_once JPATH_COMPONENT . '/lib/importer.php';
        $database = JFactory::getDBO();
        $tables = $database->getTableList();
        $prefix = $database->getPrefix();
        $dt_tables = [];
        foreach ($tables as $table) {
            if (strpos($table, "_dtsms_") !== false) {
                $dt_tables[] = $table;
            }
        }
        $schema = [];
        $cnt = 1;
        
          $exporter = new JDatabaseExporterMysqli();
          $exporter->setDbo($database);
          $exporter->from($dt_tables);
          echo $exporter->__toString();

**Comment by gslitt91** [comment]
While importing from same xml only imports first table

**Comment by ggppdk** [comment]
What about the title of this issue "Hi Bruno"

**Comment by gslitt91** [comment]
Sorry posting first time . So just replied from other issue . let me edit title
