### ISSUE TITLE
[com_actionlogs] After deselecting all events to disable logging, checkboxes remain ticked

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22627]
### Steps to reproduce the issue

Joomla 3.9 RC1 
Click Options in Action Logs screen
deselect all events to be logged (thus disabling logging) 
Click save

### Expected result

Page reloads with green configuration saved notice
Checkboxes are all NOT checked

### Actual result

Page reloads with green configuration saved notice
Checkboxes are all CHECKED again 

### System information (as much as possible)

Google Chrome, no JS errors in console

![screen recording 2018-10-15 at 10 11 am](https://user-images.githubusercontent.com/400092/46941298-ba8d6080-d062-11e8-98d2-14b3380df388.gif)

**Comment by mbabker** [comment]
Expected behavior based on the current form definition.  Having no items checked means the field is empty which means the form API applies the default value to the field, which is all extensions.

**Comment by PhilETaylor** [comment]
yup - but still totally wrong user experience :)

**Comment by cyrez** [comment]
> Expected behavior based on the current form definition. Having no items checked means the field is empty which means the form API applies the default value to the field, which is all extensions.

If you uncheck all extensions, and save, no extension will be logged (as default is not stored in params, and no value is then stored for `loggable_extensions` param) but opening again the config shows core extensions checked...

I think action logs could be an **opt-in system**, and maybe with improvement to be able to check all or none on one click : 
![capture d ecran 2018-10-15 a 19 20 16](https://user-images.githubusercontent.com/2385058/46967130-eedb3e00-d0af-11e8-9e68-e3a0abf6ad9a.png)
The screen capture is an attempt i've tried using `treeselectmenu.jquery.min.js` to integrate a select all / none (a simplified version of module pages assignment system).

**Comment by Quy** [comment]
Please test PR #22627<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22627">issues.joomla.org/tracker/joomla-cms/22627</a>.</sub>

**Comment by cyrez** [comment]
@Quy, PR to test is #22674 ;-)
