### ISSUE TITLE
[com_actionlogs] Confusing Timezone in CSV export

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22629]
### Steps to reproduce the issue

Joomla 3.9 RC1 
Export your action log when your Joomla Global Config Timezone is NOT GMT

### Expected result

Something that is not confusing - **but maybe its only idiots like me that would be confused?**

### Actual result

The dates in the db, are translated to the configured time zone, but the file name of the export has a GMT date/time in the file name, leading to "me" believing that the dates in the CSV are also GMT. 

When opened in Pages on Mac, the GMT from the filename is above the date column making "me" think that all the dates are in GMT

<img width="864" alt="screenshot 2018-10-15 at 10 20 34" src="https://user-images.githubusercontent.com/400092/46941874-fecd3080-d063-11e8-84f2-e93ce535162f.png">

options:
  - Maybe have the export filename translated to configured time zone too
  - Maybe always use GMT/UTC in all dates/times

**Comment by mbabker** [comment]
CSV exports should be standardized to UTC.

**Comment by mbabker** [comment]
See https://github.com/joomla/joomla-cms/pull/22751
