### ISSUE TITLE
[com_actionlogs] After exporting to CSV, changing a filter forces new download

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22626]
### Steps to reproduce the issue

Joomla 3.9 RC1 
View the action log screen in admin
Click Export button (either) 
Note it downloads a CSV
Change any dropdown (Extension, Date, User, Sort)
Note it downloads ANOTHER CSV instead of reloading the HTML list of actions with correct filtering

### Expected result

Page reloads with  HTML list of actions with correct filtering after clicking an export button

### Actual result

Note it downloads ANOTHER CSV instead of reloading the HTML list of actions with correct filtering

### System information (as much as possible)

Google Chrome - No JS errors in console.

**Comment by Quy** [comment]
This was fixed with #22155. Not reproducible in Chrome with 3.9rc2 (nightly).

**Comment by mbabker** [comment]
> Cool so it was fixed after rc1 was released.

"mbabker merged commit b55c735 into joomla:staging on Sep 15"

Didn't realize we had RC in September 😉

**Comment by PhilETaylor** [comment]
grrr ok in that case its probably still an issue

**Comment by PhilETaylor** [comment]
ok I cannot replicate it again now - strange - very very strange

**Comment by mbabker** [comment]
Mildly serious and mildly sarcastic but maybe you need to clean your environment up?  This is the second or third item from today that should have been fixed already yet you had an issue with.

**Comment by PhilETaylor** [comment]
Correct.

I have two Joomla 3.9 sites - one is an upgrade from the beta's and one is a clean install. 

I dont think that this is the 2nd or 3rd though, the others that have been closed have been because they have been fixed after the RC was released, and I was asked to test the RC not the bleeding edge git versions

**Comment by PhilETaylor** [comment]
> I have two Joomla 3.9 sites - one is an upgrade from the beta's and one is a clean install.

and just realised that the upgraded from beta version, which is a docker image, duh, has reverted to 3.9beta after a docker restart this morning ... grrrrrrrrrrrrrrrr

**Comment by mbabker** [comment]
The other one that came to mind was the Crowdin config file thing you did the PR for, which was excluded from packaging at beta 2 (and wouldn't have been deleted from the existing site).  So, that's why I was thinking you might have had some local quirk, which looks like is the case (gotta love VMs).
