### ISSUE TITLE
[com_actionlogs] Cannot search for terms likely to be searched for

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22635]
### Steps to reproduce the issue

Joomla 3.9rc1

Think like a regular everyday Joomla super admin (and not like a developer/contributor)

in Action logs admin, a normal Joomla super admin will assume the search box allows them to - erm - actually search for something... 

ok, so I wanted to search for "logged in" to see what users have logged in today

### Expected result

List of actions with "logged in" in their Action text. 
### Actual result

No results

The actual sql run is only searching on usernames

```sql
SELECT a.*, u.name
  FROM ltm4b_action_logs AS a
  INNER JOIN ltm4b_users AS u 
  ON a.user_id = u.id
  WHERE (`u`.`username` LIKE '%logged%')
  ORDER BY a.id DESC
```

in which case, the search is doing exactly the same as the user dropdown and is therefore useless for searching anything other than usernames (and even that fact is not communicated)

**Comment by mbabker** [comment]
Doing this level of filtering in SQL won't work as the translation keys for messages are stored in the database.  So, things here would have to be done similar to other components where you basically pull the full table into memory then apply filtering/pagination in PHP versus using SQL.

**Comment by PhilETaylor** [comment]
Yup I get that. which basically makes this searchbox useless, as you can only search for username, and you already have a searchable dropdown for that selection anyway
