### ISSUE TITLE
[com_privacy] Requests can be made for email addresses that are not registered users

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22638]
### Steps to reproduce the issue

Is this meant to be this way?

"Submitting information requests through the frontend is restricted to authenticated users at this time" and then Privacy Requests can be made for email addresses that are not registered users, even made up users...

Seems strange.

If "Submitting information requests through the frontend is restricted to authenticated users at this time" then surely the email address field should be prefilled with the logged in user, or even removed completely and the logged in users email used?

 > Security issue forked to private repo https://github.com/joomla/cms-security/issues/281 @joomla/security .

**Comment by brianteeman** [comment]
See https://github.com/joomla-projects/privacy-framework/pull/225

and such a shame that in the entire alpha, beta and multiple RC releases the @joomla/security team did not test this at all

**Comment by PhilETaylor** [comment]
> and such a shame that in the entire alpha, beta and multiple RC releases the @joomla/security team did not test this at all

Factually incorrect.
