### ISSUE TITLE
[com_actionlogs & reCaptcha] Doesn't use correct IP address when behind proxy

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22636]
### Steps to reproduce the issue

install Joomla 3.9 RC1 behind a load balancer or reverse proxy (like many people do, like many web hosts do) 

Joomla historically doesn't use IP address in many places, but one place this is very evident is in the new features for Joomla 3.9

### Expected result

Action Log & reCaptcha use IP Address, expect to use the correct IP address of the USER (and not the proxy server, host, or any other IP address)

### Actual result

Action Log & reCaptcha IP Address is read from `$_SERVER['REMOTE_ADDR']` with code

```php
$ip = JFactory::getApplication()->input->server->get('REMOTE_ADDR', null, 'raw');
// or 
$input->server->get('REMOTE_ADDR', '', 'string');
```

This will NOT give you the correct IP address for the user when behind proxies.

### Additional comments

See the great work already distributed with Joomla in [FOFUtilsIp](https://github.com/joomla/joomla-cms/blob/d3fb98cb9ba20a6e03b78ba7ee269b336c04862f/libraries/fof/utils/ip/ip.php#L422) that could be implemented. 

### ALSO see

Very bad use in [storing votes](https://github.com/joomla/joomla-cms/blob/f6c6bf5b232f841e18f46de438f969e4fc434832/components/com_content/models/article.php#L272) too 

```php
$userIP = $_SERVER['REMOTE_ADDR'];
```

**Comment by alikon** [comment]
can you test #22670 is for `com_actionlogs` only

**Comment by zero-24** [comment]
Closing as there is a PR.

**Comment by PhilETaylor** [comment]
The pr covers one of three areas covered by this issue so why would you close the issue? 

——
Sent from my iPhone - sorry - if needed I’ll send longer email from my desk later.
——

**Comment by alikon** [comment]
you are 2 fast for me  :smiley: 
see #22671 #22672 #22673

**Comment by zero-24** [comment]
> The pr covers one of three areas covered by this issue so why would you close the issue?

I can read from the mind of @alikon and by that know that he was preparing the other PRs too :P

**Comment by PhilETaylor** [comment]
I’m in bed unwell actually- but hey.




——
Sent from my iPhone - sorry - if needed I’ll send longer email from my desk later.
——
