### ISSUE TITLE
Sample Data installation should not be repatable

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#22634]
### Steps to reproduce the issue
Make an installation. The Cpanel shows the Sample data installation module.
Install Sample Data.

### Expected result
The Sample Data Module should show the Information "Sample data are installed" and have no link to repeat the sample-data-installation.

### Actual result
The Sample data link is cklickable. If the user clicks again, as consequence an error occurs.
It is correct from developers point of view but confusing for novice users.

![screen shot 2018-10-15 at 09 55 01](https://issues.joomla.org/uploads/1/de1d07e21dc7d1b9b942d72bbe5b2546.png)

**Comment by brianteeman** [comment]
There already is an open issue for this

**Comment by brianteeman** [comment]
closed see #20479
