### ISSUE TITLE
Add new index for performance of large session tables

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22632]
### Steps to reproduce the issue

have a MASSIVE session table 

Joomla will run non optimised, non indexed queries like 

```sql
SELECT COUNT(session_id)
  FROM ltm4b_session
  WHERE guest = 0 
  AND client_id = 0
```

### Expected result

Optimised performance

### Actual result

Bad performance

### Additional comments

Recommend the following index:

```sql
ALTER TABLE `#__session` ADD INDEX (`client_id`, `guest`);
```

**Comment by alikon** [comment]
can you quantify  Massive ?

**Comment by PhilETaylor** [comment]
> can you quantify Massive ?

No.

**Comment by PhilETaylor** [comment]
On dev mac

13000 rows = query time for above query without index = 9.31 ms
13000 rows = query time for above query with index = 0.55 ms

**Comment by SharkyKZ** [comment]
Related/duplicate #21555. Use `userid` instead of `guest`.

**Comment by PhilETaylor** [comment]
Not a duplicate. Just something else to address.

**Comment by brianteeman** [comment]
Instead of posting the code that you want to be changed in an issue report - please submit a pull request. You shouldn't expect people to do your work for you. It's not s if you don't know how to write the code!!!

**Comment by PhilETaylor** [comment]
Brian

It's because of people like you - no, you specifically, that I do not contribute to this project as much as I used to. You really are stuck up yourself eh? 

Its not code "I want changed" 

Its not "my work" Im expecting people to do. 

It's called contributing ... if you do not count issues as contributing then thats not my problem.

This is the reason you have spent the last 3 years blocked. And the reason I will again block you right now. 

I'm disappointed that once again you chose personal attacks of those actually contributing. And yes, raising issues REGARDLESS OF ABILITY is contributing. Not everyone has no job and can just drop everything to code. It's not always appropriate to be fixing issues at the same time as reporting them. Different hats for different times. 

Ironically, someone literally just told me you would start with these personal attacks, and within an hour you started again. 

Pathetic.

**Comment by brianteeman** [comment]
~Glad I am blocked so I dont have to read your egotistical rants. Unlike you I don't pretend to my clients that I am a core contributor to Joomla. I contribute because that is what community is all about.  What you do is leach, moan and use Joomla only when it suits you for commercial gain.~

**Comment by PhilETaylor** [comment]
Personal attacks will not be tolerated.

**Comment by brianteeman** [comment]
truth hurts

**Comment by laoneo** [comment]
I locked this issue as the focus get lost. If somebody feels like to open a pr with the index change, this is very welcome.

**Comment by Bakual** [comment]
Closing since there is a PR: https://github.com/joomla/joomla-cms/pull/22668
