### ISSUE TITLE
[4.0] Template manager - new file modal overflow

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#22644]
### Steps to reproduce the issue
Create a new file in the template

### Expected result
Able to navigate the tree within the modal

### Actual result
if it is a large tree (you may need to create some overrides) then the tree expands out of the modal

### Solution
I believe the issue is because in order for the overflow-y to be set (eg overflow-y: scroll) the container div must have a specified height. @C-Lodder @ciar4n can you help?

### Current behaviour
![real-actual](https://user-images.githubusercontent.com/1296369/46959874-05c06700-d095-11e8-870c-664b2d79461f.gif)

### Expected behaviour
![actual](https://user-images.githubusercontent.com/1296369/46959883-09ec8480-d095-11e8-9697-e9bec8eb09d9.gif)

**Comment by C-Lodder** [comment]
@brianteeman The issue derives from this line: https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media/legacy/js/bootstrap-init.js#L129

which overrides the overflow property, normally allowing you to scroll

**Comment by brianteeman** [comment]
looks like a bug at my end as I cant replicate it now. Will close for now. Thanks @C-Lodder

**Comment by C-Lodder** [comment]
@brianteeman Nah definitely not a bug your end. I know what you mean though...sometimes it occurs and sometimes it doesn't. Either way, that line needs to be removed to fix the issue

**Comment by brianteeman** [comment]
ok re-opening for now. I thought I was going mad
