### ISSUE TITLE
[com_actionlogs] When plugin unpublished, there is no warning

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22641]
### Steps to reproduce the issue

install Joomla 3.9rc1 
unpublish "Action Log - Joomla"
go to administrator/index.php?option=com_actionlogs

### Expected result

A warning that action log collection is disabled.

**This would bring it in line with the other extensions** that rely on a plugin being enabled,  Redirect System Plugin example

<img width="769" alt="screenshot 2018-10-15 at 12 12 18" src="https://user-images.githubusercontent.com/400092/46947719-a3a33a00-d073-11e8-9b15-7e576b7a3cfa.png">

and the search component example

<img width="728" alt="screenshot 2018-10-15 at 12 12 56" src="https://user-images.githubusercontent.com/400092/46947734-af8efc00-d073-11e8-8396-7dbde3696622.png">

and the smart search example

<img width="1128" alt="screenshot 2018-10-15 at 12 14 20" src="https://user-images.githubusercontent.com/400092/46947774-e06f3100-d073-11e8-80d8-4aba70a83a11.png">

### Actual result

No warning

### hahahaha opposite to 

https://github.com/joomla/joomla-cms/issues/20474

**Comment by alikon** [comment]
there is something at #21898

**Comment by PhilETaylor** [comment]
Cool
