### ISSUE TITLE
[com_privacy] No action checkbox and unable to move from pending status

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22640]
### Steps to reproduce the issue

ok what am I missing?

I have no action checkbox and unable to move from pending status

<img width="832" alt="screenshot 2018-10-15 at 12 09 33" src="https://user-images.githubusercontent.com/400092/46947614-45765700-d073-11e8-942b-51b665c6a81d.png">

**Comment by mbabker** [comment]
Follow https://docs.joomla.org/J3.x:Information_Request_Workflow_in_Privacy_Component

Nobody can move a pending request out of pending through the UI.  The subject user MUST confirm the request.

**Comment by PhilETaylor** [comment]
excellent - thats what I missed, I also have mail disabled in this docker instance so I never saw the emails. I never had time to check the actual exporting of the info this morning before my work day kicked in.
