### ISSUE TITLE
Privacy Policy Consent not asked to new user in backend

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#22659]
### Steps to reproduce the issue
Log as super user in back-end.
Create a user as administrator in back-end.
Logout
Log in back-end with this new user

### Expected result
The new user should be asked to consent to the Privacy policy

### Actual result
It does not

**Comment by infograf768** [comment]
Note: It does work OK in front-end

**Comment by mbabker** [comment]
This was the system design.  If someone wants to propose an option to require it for the backend I personally wouldn't be opposed to it, but I don't think it needs to be a hard requirement for the backend the same way it is frontend.

**Comment by infograf768** [comment]
Closing as this is intended behavior.

**Comment by mc-cm** [comment]
Seems I'm the only one who actually hase a requirement for the privacy consent features in backend. I have  many users whom I give backend access (actually all publishers) to the sites. We do a backend only strategy, and therefor I'd like to see the consent privacy features of J3.9 applied also to the backend. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22659">issues.joomla.org/tracker/joomla-cms/22659</a>.</sub>
