### ISSUE TITLE
Godaddy blocks registration verification email due to "SPAM" content

### ISSUE THREAD

**Issue by devmrs** [joomla/joomla-cms#22657]
### Steps to reproduce the issue
Attempt to register @ sunlifearc.org

### Expected result
Receive verification email

### Actual result
No email received because Godaddy Spam Filter blocks the email

### System information (as much as possible)
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  auggiepimentel91@gmail.com
    host a2nlsmtpcp-v01.shr.prod.iad2.secureserver.net [198.71.232.0]
    SMTP error from remote mail server after end of data:
    552 5.2.0 CBgYgTq4ZM0DP :: CPANEL :: Message rejected for spam or virus content ::
    Please include this entire message when contacting support ::
    v=2.3 cv=a9ThCnaF c=1 sm=1 tr=0 p=L4DFVq6t_HQ3kkP71zcA:9
a=cbnzLByw5Eopqc1jhu0XRg==:117 a=9+rZDBEiDlHhcck0kWbJtElFXBc=:19
a=IkcTkHD0fZMA:10 a=TnL_TAEZBzAA:10 a=5mMnsbq4KeQA:10 a=smKx5t2vBNcA:10
a=mqDg_6gO95AA:10 a=zPEzg-GQAAAA:8 a=QEXdDO2ut3YA:10 a=GjgB7cfr_M4A:10
a=2c8qgOxouhqCjNl9YZ4Y:22 ::
    100.00

### Additional comments
A Customer Support person at Godaddy told me that the email requires a "Un-Subscribe" link. This makes no sense because the user is not subscribing to anything.

**Comment by brianteeman** [comment]
You are correct - the godaddy support doesnt know what they are talking about or godaddy have a very silly spam filter - but this isnt the right place to ask for joomla community support - please use https://forum.joomla.org
