### ISSUE TITLE
Ugly Joomla Tags 

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#22661]
### Steps to reproduce the issue

Tags > New

### Expected result
URLs 
/tag-name

### Actual result
URLs 
/component/tags/tag/tag-name

### System information (as much as possible)

Joomla 3.8.13
PHP 7.1
MySQL 5.7

### Additional comments
I can't find documentation on tags URLs ?

**Comment by Bakual** [comment]
If you want an URL like "/tag-name", you need to create a menu item for it.

> I can't find documentation on tags URLs

They behave the same as other URLs as well. If you need assistance, please use the forums for help.

Closing this issue since it is expected behavior.

**Comment by ghost** [comment]
@Bakual so if users create 1000 tags manager also need in addition to create 1000 menu items in joomla ?
Or everyone using joomla get ugly Joomla Tags /component/tags/tag/tag-name

is expected joomla behavior?

documentation on tags URLs

**Comment by Bakual** [comment]
>  if users create 1000 tags manager also need in addition to create 1000 menu items in joomla ?

If your user wants the tag accessible as a the first segment of the URL (eg domain.com/tagname), then yes.

> Or everyone using joomla get ugly Joomla Tags /component/tags/tag/tag-name

Of course not. If you care about URLs of the tags, you can create a (hidden) menuitem (eg "tags") for the tag category and thus get eg "domain.com/tags/tagname".

> documentation on tags URLs

As said, same as every other component. There is no difference and thus no specific documentation is needed. Articles aren't accessible by domain.com/articlename either.

as said before, please use the forum if you need further assistance.  This is the issue tracker for issues with the code itself. Not for issues with the implentation.

**Comment by ghost** [comment]
After you create a menuitem for the tag you still get /component/tags/tag/tag-name when you click on article and scrool down to the tag.

@Bakual  What are your steps to reproduce "domain.com/tags/tagname".

**Comment by Bakual** [comment]
https://forum.joomla.org/
