### ISSUE TITLE
[4.0] Login module - password view

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#22664]
The module is supposed to support the ability to view the password by clicking on the eye but when you do you get the following error for the site module

```
Uncaught TypeError: Cannot read property 'nextElementSibling' of null
    at HTMLSpanElement.<anonymous> (passwordview.min.js?a41cbebf78ce21eda724838de8f977ba:1)
(anonymous) @ passwordview.min.js?a41cbebf78ce21eda724838de8f977ba:1
```
and this error for the admin module

```
Uncaught TypeError: Cannot set property 'type' of null
    at HTMLSpanElement.<anonymous> (passwordview.min.js?a41cbebf78ce21eda724838de8f977ba:1)
(anonymous) @ passwordview.min.js?a41cbebf78ce21eda724838de8f977ba:1
```

Spotted this while trying to fix some a11y errors with it but I cant do that while there is this js error and I dont have the js skill to debug/fix

**Comment by brianteeman** [comment]
The only place it does work correctly is `administrator/index.php?option=com_users&view=user&layout=edit`

**Comment by C-Lodder** [comment]
I see the issue. Will submit a PR later

**Comment by laoneo** [comment]
I'm on it already

**Comment by C-Lodder** [comment]
@laoneo Can I suggest the login module actually utilises the password/text layouts first and then the JS is fixed accordingly?

**Comment by brianteeman** [comment]
To be honest the way this JS works appears to be a hard coding to a specific markup. I thought the entire point of layouts etc was to free a designer from specific hard requirements like this. We're just swapping one well supported and cohesive framework for a hotch porch of hacked together scripts that still place restrictions.

**Comment by laoneo** [comment]
Please comment on #22666. I tried to decouple it as much as possible from the structure
