### ISSUE TITLE
Action Logs mail issue for non superuser!!!

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#22662]
### Steps to reproduce the issue
Create a new administrator user in backend.
As the user has by default no access to Action logs, it can't be set to NOT receive actionlogs emails as a Super User can do. 

### RESULT
The mail box of this administrator user is filled with action logs messages.

**Comment by ReLater** [comment]
Did you test with pr https://github.com/joomla/joomla-cms/pull/21983 ?

**Comment by infograf768** [comment]
nope. will do later

**Comment by infograf768** [comment]
Looks like https://github.com/joomla/joomla-cms/pull/21983 solves the issue.
Thanks for the hint.
Closing
