### ISSUE TITLE
BUG MENU Language settings - NOT engine friendly URLs

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#22686]
### Expected result
set to ALL languages, then the URLs will be search engine friendly

### Actual result
If all menu items are set to ALL languages, then the URLs will be search engine friendly

### System information (as much as possible)
Joomla version 3.8.13 New installation
**Resellers Account**

**PHP built on** Linux
**Database type** mysql
**Database version** 10.1.31-MariaDB-cll-lve
**Database collation** utf8_general_ci
**Collation of the database connection** utf8mb4_general_ci
### PHP version 7.1.21
**Web server** Apache / 2
**Web server to** PHP interface litespeed
**Joomla! version Joomla!** 3.8.13 Stable [Amani] 9-October-2018 14:00 GMT
**Joomla! Platform version** Joomla Platform 13.1.0 Stable [Curiosity] 24-Apr-2013 00:00 GMT
User Agent Mozilla / 

### Additional comments
BUG found

It is difficult to describe what exactly happened, I will describe this as well as possible.

Installation Joomla new Version 1.8.13

After installation you can switch on at System> General settings

Search engine-friendly URLs and Use URL rewrite, both are set to YES.

_______________________________________________________

Then the Options> Articles option can be used.

At Items> Options> Integration tab the option "Route URL" is set to "Renewal".

The other option that appears then can be turned on the following option: "Remove IDs from URLs"

_______________________________________________________

categories

Once everything is set correctly, you can start creating categories.
They set the necessary important options there, as well as the language.

______________________________________________________

**BUG MENU Language settings**

After installing a new Joomla, the HOME does not work.

The front page then immediately gives an error message error 400.

Afterwards you are obliged to delete "Home" and to create a new "home". The front page is then visible again without the error message 400.

Now it's time to create Menu Items, as is customary, set the new Menu Item to the language of the country you are from.

After having created all the menus, the result is that as soon as articles are pointed to the category that corresponds to the created Menu Item NO search engine-friendly URLs

Once all menu items that you have added are set to ALL LANGUAGES, all search engine friendly URLs are.
_______________________________________________________

In brief

If you set the language in the created menu Items, the URLs will NOT become Search engine friendly

If all menu items are set to ALL languages, then the URLs will be search engine friendly

**Comment by ghost** [comment]
Okay, well here is a example what I mean [https://nieuwsberichten.eu/muis/](url)

**Comment by ghost** [comment]
#
On the new website, i have code some in the PhpMyAdmin

Open phpMyAdmin and select the database powering your Joomla website.
Click on the #__extensions table.
Open the row where the name field is set com_content.
Add the following to the params field **{** just before the curly bracket **}**
`,"sef_advanced":"1","sef_advanced_link":"1"`

I don't know yet, what will happens , when I make some Menu-Items with language set on them.

**Comment by infograf768** [comment]
I am sorry but I do not understand your issue at all.
For example
 > the HOME does not work

What is your Home menu item? What should it display?

> Now it's time to create Menu Items, as is customary, set the new Menu Item to the language of the country you are from.

Is your site a multilingual site? If not, why setting these to "the language of the country you are from." It is no use.

IN any case, what is your site structure? What kind of urls do you get which are "not user friendly"?

**Comment by ghost** [comment]
HOME, is not working after a new install, you get a 404 or a blank screen
After remove the HOME, I have to make a new one, the problem is solved than.

Than a new menu Item "**News**" set language on Dutch.
The following Menu Item sub "**inland news**" and set also to the language Dutch
The following Menu Item sub "**Foreign news**" and set also to the language Dutch

Before you start with creating menus, articles and categories. You must first have all settings of joomla correct.

System> Global configuration> on the first tab the following must be switched on

1 - Rename htaccess file.
2 - Search Engine Friendly URLs "YES"
2 - Use URL Rewriting "YES"

Contents > Articles> Options> integrate

1 - URL Routing "Modern"
2 - Remove IDs from URLs "YES"

Plugins

Extensions> plugin> System - Language Code set to "en-US"

Extensions> plugin> System - Language Filter
1 - Language Selection for new Visitors "Site language"
2 - Automatic Language Change "YES"
3 - Associations "YES"
4 - Add Alternate Meta Tags "YES"
5 - Add x-default Meta Tag "YES"
6 - x-default Language "Dutch (nl-NL)"
7 - Remove URL Language Code "YES"
8 - Cookie Lifetime "Session"

Extensions> Language (s)

1 - Languages: Installed (Administrator) set to "Dutch (nl-NL)"
2 - Languages: Installed (Site) "Dutch (nl-NL)"

Now it comes
As soon as you go to the front page and want to visit an article, you will not see Search Engine Friendly URLs

If I put the newly created "menu items," "** News **"> "** inland news **" and "** Foreign news **" on language selection in menus, all URLs are Search Engine Friendly URLs

This is NOT a Search Engine Friendly URLs, but this I get when I set the Menu-Items to the language "Dutch (nl-NL)"

nieuwsberichten.eu/?view=article&id=212:explosie-treft-damascus-vliegbasis-munitiedepot&catid=16

Well this is a clean URL  nieuwsberichten.eu/opzet/nieuwsberichten/buitenland-nieuwsberichten/explosie-treft-damascus-vliegbasis-munitiedepot

multilingual site "NO"

Now tell me, what do I wrong here????

**Comment by brianteeman** [comment]
if you are not building a multilingual site then you dont need the language filter plugin enabled 
> This plugin is to be enabled only when the Language Switcher module is published.

your site in dutch so is there no need to enable the language code plugin either

**Comment by ghost** [comment]
> your site in dutch so is there no need to enable the language code plugin either

Completely correct, but when they say from JoomlaComunity you must set it to "language code" I do so. But the result stays the same

**Comment by brianteeman** [comment]
well whoever said that was wrong

**Comment by hvdmeer** [comment]
Just read the Dutch thread on the forum. 
I think the Dutch people were thinking in the wrong direction because in his first post over there he mentioned changing the language setting. So that's why I think people thought it is a multilingual site.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22686">issues.joomla.org/tracker/joomla-cms/22686</a>.</sub>

**Comment by brianteeman** [comment]
i am closing it here. the forum is the best place for support.

**Comment by ghost** [comment]
@hvdmeer @brianteeman 
Correct, in the first topic I did indicated that, but they mist it all. And I did not mention that at all, that I have a multilingual site

That was the reason, to provide at much information about the issue. So the most people know than, where to look, what I did not see.
