### ISSUE TITLE
User Actions Log: not installing Module, after upgrade from 3.8.14

### ISSUE THREAD

**Issue by rotech1** [joomla/joomla-cms#22689]
### Steps to reproduce the issue
upgrade to 3.9 RC

### Expected result
User Actions log working

### Actual result
Log page is accessible. But (after some actions by users both front and back end) I find no data in the log... Checked the Modules ( as per https://docs.joomla.org/Help38:Extensions_Module_Manager_Admin_Latestactions ) and no such module can be found in the modules list! 

???  Bad docs, or bad upgrade??

Docs (https://docs.joomla.org/Special:MyLanguage/J3.x:User_Action_Logs )strongly imply that only the ONE "Action Log" plugin needs to be enabled to record system logs - and there is nothing in the docs requiring either of the others be enabled as prerequisite for it to function...

plugin "Action Log" is enabled, and the other two new 'action plugins' are not.
Disabled Action Log plugin, then re-enabled, and tested again. Still nothing...

### System information (as much as possible)
Setting	Value
 
PHP Built On	Linux [redacted] 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64
Database Type	mysql
Database Version	8.0.12
Database Collation	utf8mb4_0900_ai_ci
Database Connection Collation	utf8mb4_0900_ai_ci
PHP Version	7.2.10
Web Server	Apache/2.4.6 (CentOS) PHP/7.2.10
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.9.0-rc Release Candidate [ Amani ] 10-October-2018 12:30 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36

### Additional comments

I'm going to disable the plugin now... 
I don't think this would ever be enabled on our high-volume site, anyway (too much overhead wasted on a feature that we do not need...)

**Comment by Quy** [comment]
See #22577

> the modules and plugins related to privacy and actionlogs may have to be enabled in Manage

**Comment by rotech1** [comment]
OK, so somebody will update the documentation accordingly then?

**Comment by mbabker** [comment]
The `3.9.0-2018-05-20.sql` and `3.9.0-2018-06-12.sql` change deltas add the modules but don't enable them, counter to `joomla.sql` which does have them enabled.

I don't remember if there was a reason or if it's an oversight, but I'd suggest the extensions should be enabled in those deltas so that the modules are easily found when adding them to existing sites and the extra steps of finding them in the extension manager and enabling them aren't necessary.

**Comment by infograf768** [comment]
We are quite a few who learned that the hard way...
Patch here https://github.com/joomla/joomla-cms/pull/22691
