### ISSUE TITLE
[com_actionlogs][RFC] When purging the action log no record of this is kept

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22695]
### Steps to reproduce the issue

Joomla 3.9
Purge the action logs

### Expected result

A single row is inserted after the purge, saying that {{username}} purged the action log, with his IP and date

### Actual result

No Matching Results

### Additional comments

This would be very useful for covering your back and knowing who what when purged the action log database.

**Comment by alikon** [comment]
Make sense to me

**Comment by AMurray2016** [comment]
Just a comment related to this, I have a similar problem with the action log is not listing other important system tasks such as joomla core updates. I tested 3.9.0RC with updating to 3.9.0RC2; I changed the update the Update Channel to "Custom URL" (using the nightly build URL for 3.9.0RC/RC2).  It updated the system OK but never logged the fact that I had just done the core version update.  This can be moved to a separate issue if need be, but I had trouble with GITHUB in trying to log this separately.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22695">issues.joomla.org/tracker/joomla-cms/22695</a>.</sub>

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/issues/22703 for the missing actions.

FWIW, we really didn't go through and add either new plugin events or explicit calls to the com_actionlogs component to log every action.  It essentially picked up on everything existing in the current system.  So it's not like someone sat down and decided "log this, log that, don't log that though".

**Comment by mbabker** [comment]
PR https://github.com/joomla/joomla-cms/pull/22740
