### ISSUE TITLE
Images class and media manager on Insert menu for TinyMCE

### ISSUE THREAD

**Issue by Dade88** [joomla/joomla-cms#22694]
### Problem
1. It's impossible to insert image **classes** from either the image utility or media manager.
2. Users coming from "other CMS" complains because Media Manager is not on Insert dropdown menu.
3. TinyMCE's image utility is misleading without a proper interface to link images from Media Manager.

### Possible solution
1. This is absolutely a must, and while maybe modifying it for TinyMCE is not on the plan, this should be absolutely included on Joomla's Media Manager.
2. We need to adapt to others standards and place Media Manager on Insert dropdown menu.
3. Disable or improve default TinyMCE's image utility.

**Comment by brianteeman** [comment]
![editor](https://user-images.githubusercontent.com/1296369/47151904-08a89b00-d2d3-11e8-843c-adf7efdc00b1.gif)

**Comment by Dade88** [comment]
I am sorry but I do not understand how your comment has anything to do with the issue/feature I posted @brianteeman . Maybe I didn't explain well enough, I will try to make a practical example.

Most clients like to have shadows on their images with shadows, while this is not a problem if I am developing the site (I edit directly from the source code), you can't expect 99.99% of clients to dig into an article code and add class="whatever" to the exact <img> tag they wish to edit.

There is a "Caption Class" option but there isn't an "Image Class", as you can see from your own gif.

On the other hand, having TinyMCE's image button and Joomla's Media Manager button is misleading for many new users starting using Joomla, and at least Media Manager should appear on "Insert" dropdown menu so both options are shown in the same context.

**Comment by ghost** [comment]
@laoneo is the new Media Manager for this Request?

**Comment by Quy** [comment]
In J4, you don't have these options anymore. All you can do it select the image.
In J3, there is a workaround by editing the HTML source.

**Comment by ghost** [comment]
Closed as stated above. Issue can always reopened.
