### ISSUE TITLE
[com_actionlogs][RFC] Deleting users leaves their actions in action logs table, with broken links

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22696]
### Steps to reproduce the issue

Have users with actions in the action logs

delete those users in User Manager

### Expected result

I would assume their rows would have been removed from the action logs table

### Actual result

The rows remain, links to the user become broken as the user no longer exists.

### Additional comments

Discuss

![screenshot 2018-10-18 at 14 32 58](https://user-images.githubusercontent.com/400092/47158084-c25b3800-d2e2-11e8-9205-faf4fdf5eaf7.png)

**Comment by alikon** [comment]
for me you should'nt delete from log the action performed by an "ex-user" by default 
but after some site admin "work/think"
