### ISSUE TITLE
[4.0] [mod_article_news] No output for image

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#22698]
### Steps to reproduce the issue
Mod_article_news contains an option to display an article image, however, there is no image in the output... https://github.com/joomla/joomla-cms/blob/4.0-dev/modules/mod_articles_news/tmpl/_item.php

Looks like https://github.com/joomla/joomla-cms/pull/20169 is not applied to the 4.0-dev branch

**Comment by brianteeman** [comment]
I think "wiklsonge has only got as far as mergin 3.7 upstream

**Comment by mbabker** [comment]
The last update I saw was that 3.8.7 was where things were at in merging.

**Comment by ciar4n** [comment]
Ah ok. I guess I can close this.
