### ISSUE TITLE
language switcher generated URI show "&amp;" instead of "&"

### ISSUE THREAD

**Issue by pieter-groeneweg** [joomla/joomla-cms#22693]
### Steps to reproduce the issue
create a multilingual site.
do NOT enable SEF URL's

### Expected result
URI under the flags to show URI with `&` as separator of the querystring

### Actual result
URI under the flags do show URI querystring separator as `&amp;`

### System information (as much as possible)
My system is J!3.8.13 on PHP7.2.11, MySQL5.5.33, Apache2.2.15

### Additional comments
See also https://forum.joomla.org/viewtopic.php?p=3544309

### Possible solution that works for me:
replace all 
`htmlspecialchars(JUri::current(), ENT_COMPAT, 'UTF-8')`
with 
`JUri::current()`

**Comment by infograf768** [comment]
Closing. This is not a bug. It was changed for security reason:
https://developer.joomla.org/security-centre/740-20180602-core-xss-vulnerability-in-language-switcher-module

**Comment by pieter-groeneweg** [comment]
Maybe reopen..

Change 
`htmlspecialchars($language->link, ENT_QUOTES, 'UTF-8')`
into
`JFilterOutput::ampReplace(htmlspecialchars($language->link, ENT_QUOTES, 'UTF-8', FALSE))`

Works too.. same format as used in menu module. That should do it I assume. At least with me.

**Comment by infograf768** [comment]
Forwarded to JSST to check if that does not re-introduce the vulnerability.

**Comment by infograf768** [comment]
I am told it's OK to patch this way.
Reopened.
Can you propose the PR?

**Comment by infograf768** [comment]
in fact, do not worry about that. I will include that patch in a pending PR i made for this module.

**Comment by pieter-groeneweg** [comment]
Sorry I am out for the weekend.. did not read this any earlier to respond.. thanks! Keep up the good work!

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/22558
Closing as we have a patch.

**Comment by infograf768** [comment]
Hmm
In fact I have tested this here and there is no change in the link produced...
I should have tested before.

**Comment by infograf768** [comment]
Reverting JFilterOutput::ampReplace as this will not do the job.
reopening.

**Comment by infograf768** [comment]
I may have another solution.
Will keep you posted.

**Comment by infograf768** [comment]
OK, now https://github.com/joomla/joomla-cms/pull/22558 can be tested.
closing again.
