### ISSUE TITLE
[com_privacy] When exporting data, consents are not exported

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22708]
### Steps to reproduce the issue

Install Joomla 3.9
Enable all new 3.9 features like consents plugin
Give consent
Request export of all personal data
Confirm that request
export the data in admin, resulting in an XML

### Expected result

The XML contains personal information that is stored as part of the consents

E.g:

> admin | 348 | Privacy Policy | The user consented to storing their user information using the IP address 127.0.0.1The user agent string of the user's browser was:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36 This information was automatically recorded when the user submitted their details on the web site and checked the confirm box

### Actual result

The XML doesn't export this personal data as part of its dataset.

**Comment by mbabker** [comment]
See https://github.com/joomla/joomla-cms/pull/22749
