### ISSUE TITLE
[com_actionlogs] Installing official language is recorded twice

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22702]
### Steps to reproduce the issue

Install a language pack
View action log

### Expected result

One row

### Actual result

Two identical rows

(Probably as its installing from the package, 2 items, but still confusing to an end user looking at the logs)

also not hyperlinked like they could be like other items get in the logs

![screenshot 2018-10-18 at 16 08 08](https://user-images.githubusercontent.com/400092/47164583-36500d00-d2f0-11e8-9e9e-a14188270b51.png)

**Comment by brianteeman** [comment]
I am going to guess that one is the site language and one is the admin
language

**Comment by mbabker** [comment]
Without getting translators to rename their extensions, this one's a "can't fix".  Unless we're going to arbitrarily add exclude rules to what types of extensions are logged.
