### ISSUE TITLE
[com_actionlogs] Email Subjects All The Same

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22709]
### Steps to reproduce the issue

Enable the sending of Action Log entries to a Super Admin by Mail in Joomla 3.9
Generate a load of emails

### Expected result

Each subject line to be descriptive of the alerted action

### Actual result

Generic "Latest User Actions" subject line

![screenshot 2018-10-19 at 00 47 26](https://user-images.githubusercontent.com/400092/47190407-1abd2480-d339-11e8-873e-f56ffa99f4db.png)

### Additional comments

Trust me, myJoomla.com has been sending these kind of User Action Emails for years now and in the early days the **number one complaint** was that the subject lines were the same. 

Also "Latest User Actions" is not actually what the email is about, its about a SINGLE user action generated - not plural. 

Highly recommend putting the site name or url in the subject too

Remember, Super admins will want to filter these into other mailboxes - trust me... 

If the emails are not useful, then no one will ever use this feature.

Recommend something like

 - `[MySite Name] User admin saved the global configuration`
 - `[MySite Name] User mike logged into the administrator`

**Comment by mbabker** [comment]
Not every email will be a single action (this was iterated over in the project repo), so any changes need to keep that in mind.

At a minimum we do need site name.
