### ISSUE TITLE
[com_actionlogs] Some important actions not logged

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22703]
### Steps to reproduce the issue

In Joomla 3.9 
 - clear the cache in admin as a super admin (Important action because it can literally change a site's output to the world)
 - check in the checked out items (Important action because allows someone access to something they never had access to before)
 - Export a CSV from action logs (important action as personal information is contained) 

 - possibly a million other actions ... 

Where do we draw the line on what should be logged in the action log? Who is going to decide what actions are being logged... where is the line? Are we only goign to restrict the actions log to actions that trigger existing events or are additional events going to be created and triggered so we can capture those important events... 

An example where Joomla is doing this right, is that exports of data in com_privacy is now logged. 

### Expected result

Both should be recorded as an action in the log

### Actual result

Nothing is recorded.

**Comment by mbabker** [comment]
The TL;DR on it is without either a hookable event the plugin can catch or adding an explicit log call like the com_privacy models all do (which probably should be done for the CSV export), then there's no way to catch an action to be logged.

For com_cache if I'm not mistaken there's a PR adding logs for that.

**Comment by PhilETaylor** [comment]
So like I ask, would it not be great to add more hookable events for identified "important actions"?

**Comment by mbabker** [comment]
Events are cheap to add, not everything has to be forced into `onContent(Before|After)(Save|Delete)`

**Comment by PhilETaylor** [comment]
> Events are cheap to add, not everything has to be forced into onContent(Before|After)(Save|Delete)

Translation: Go ahead and add events for these important actions and any more that we can identify..

**Comment by B3nito** [comment]
Sorry is there a documentation how to add action log in own component or module or to other 3rd party?

**Comment by PhilETaylor** [comment]
> Sorry is there a documentation how to add action log in own component or module or to other 3rd party?

Not that I have seen, all I have seen is the title for that section here: https://docs.joomla.org/J3.x:User_Action_Logs#How_to_hook_an_extension_to_the_system

# How_to_hook_an_extension_to_the_system

**Comment by alikon** [comment]
for 

> check in the checked out items (Important action because allows someone access to something they never had access to before)

see #22530

**Comment by alikon** [comment]
for 

> clear the cache in admin as a super admin (Important action because it can literally change a site's output to the world)

see #22739

**Comment by B3nito** [comment]
> Not that I have seen, all I have seen is the title for that section here: https://docs.joomla.org/J3.x:User_Action_Logs#How_to_hook_an_extension_to_the_system
How to hook an extension to the system

Thank you @PhilETaylor , but I am dissapointed... How should someone 3rd party prepare for this version if its not documented? How can you expect others to be ready for next version if not written how to get ready? it is always the same for new versions in joomla. you have to know code very well and study it and most time only the persons who implement feature can take advantage.
