### ISSUE TITLE
[com_privacy] User gets no notification that their data has been deleted/their remove request honoured

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22719]
### Steps to reproduce the issue

Joomla 3.9 with all new features enabled

User "me@phil-taylor.com" requests a REMOVE request
He Confirms it with a token from the email 
The admin sees this, and clicks the X to delete all his data
The admin sets the status to COMPLETED

### Expected result

That the user some how is informed that his request has been successful/honoured

### Actual result

No notification is sent to me@phil-taylor.com that his data is deleted

**Comment by mbabker** [comment]
There's a part of me that wants to chuck this into the "won't fix" pile, for similar reasoning that we don't automatically advance requests to "completed" when you hit the action buttons.  The admin actioning the request should most definitely notify the user they've completed it, but I'm not sure it's something we can efficiently code into the code processing the actions.

**Comment by PhilETaylor** [comment]
Do it :-) 

Wont fix :)
