### ISSUE TITLE
[com_privacy] Cannot request a remove request without agreeing to your policies

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22717]
### Steps to reproduce the issue

Joomla 3.9 with all new privacy features enabled

"I hate you, I hate your site, I want you to delete all my data... oh I have to login to do that? ffs... ok I'm logged in, whoah now you have redirected me to my profile and demand me to agree to your Privacy policy - I cannot click the Create Remove Request link as it redirects me back to the edit profile page... dammit... I now have to Agree to something which I don't agree in order to make a request for you to delete all my data....."

### Expected result

Maybe an exception to the create request page that doesnt require me to agree to the policies? 

### Actual result

unable to create a privacy request to remove my data without first agreeing the policy I dont agree with

### or is it just me?

possibly. ZZzzzz...

**Comment by brianteeman** [comment]
Its just you.
