### ISSUE TITLE
Joomla sef issue  /component/tags/tag/tag-name

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#22723]
### Steps to reproduce the issue

Create a menuitem for the tag you still get /component/tags/tag/tag-name when you click on article and scrool down to the tag.

### Expected result

/tags/tagname 

### Actual result

/component/tags/tag/tag-name

### System information (as much as possible)

Joomla 3.8.13
PHP 7.1
MySQL 5.7

### Additional comments

What are your steps to reproduce /tags/tagname ?

**Comment by SharkyKZ** [comment]
Create a menu item with type `List of all tags`.

**Comment by ghost** [comment]
menu item with type List of all tags is created but actual result is still /component/tags/tag/tag-name

**Comment by mbabker** [comment]
How is this any different from the other 5 tags related issues you have opened?

**Comment by SharkyKZ** [comment]
Same as #22661 but that one was closed and locked.

**Comment by ghost** [comment]
What are your steps to reproduce /tags/tagname ? This is Joomla sef issue.

**Comment by SharkyKZ** [comment]
I can reproduce this issue. It only affects multilingual sites.

Set up a multilingual site.
Create a tag and set its language.
Create a `Tagged Items` menu item and select the tag or create `List of all tags` menu item.
Set the language of the menu item to be the same as the tag's.

**Comment by infograf768** [comment]
See forum
https://forum.joomla.org/viewtopic.php?f=706&t=966291&e=1&view=unread#p3544100

**Comment by ghost** [comment]
@infograf768 can this Issue be closed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22723">issues.joomla.org/tracker/joomla-cms/22723</a>.</sub>

**Comment by ghost** [comment]
closed as Issue seems for Forums, please reopen if i'm wrong.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22723">issues.joomla.org/tracker/joomla-cms/22723</a>.</sub>
