### ISSUE TITLE
[com_privacy] Doesnt implement checked_out/checked_out_time correctly

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22722]
### Steps to reproduce the issue

Joomla 3.9 with all privacy features enabled.

User me@phil-taylor.com requests deletion
User me@phil-taylor.com confirms request
Admin edits that request

### Expected result

The request is "checked_out" and checked_out_time is set in the db
Fro this to be listed in Maintenance: Global Check-in at http://0.0.0.0/administrator/index.php?option=com_checkin

### Actual result

Although there is a checked_out and checked_out_time columns in the database in #__privacy_requests table - the functionality is not implemented in the component.

Either it could be implemented, OR these columns in the db could be removed. Easy one. I think its the latter.

**Comment by mbabker** [comment]
See https://github.com/joomla/joomla-cms/pull/22748
