### ISSUE TITLE
Parent Menu Item filtered like itemlist is filtered

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#22734]
### Steps to reproduce the issue
You have menu with at least one item

Search for a menu item named dlfkbldfbldfjblfg
-> You have no results in menu

Create a new menu items and try to set one of the existing items as parent

### Expected result
parent item list shows all available items

### Actual result
parent item list is filtered like the search you make in the menu item list

**Comment by tonypartridge** [comment]
Can you confirm which version of Joomla? There have been some updates to the parent menu filtering

**Comment by B3nito** [comment]
It is not J4 issue it is 3.8.13 issue.

**Comment by ghost** [comment]
@B3nito does this Issue exist on latest Version?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22734">issues.joomla.org/tracker/joomla-cms/22734</a>.</sub>

**Comment by ghost** [comment]
closed as no Response, please reopen if needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22734">issues.joomla.org/tracker/joomla-cms/22734</a>.</sub>
