### ISSUE TITLE
Not able to login admin panel

### ISSUE THREAD

**Issue by DonaldTrump88** [joomla/joomla-cms#22738]
### Steps to reproduce the issue

Today I have installed latest J4 build. After installation I was able to login. During the session I had enabled double authentication and disabled them. But in database the dual authentication was active. So I deactivated them in database.
Then I tried to login in admin panel, unfortunately it did not work. So modified the password in database using MD5 encrypt md5online.org. I was not able to login and the MD5 value in database was reset to random value. This happed couple to times before also with double authetication scenario. The same thing J3 works fine.

### Expected result

login to admin panel

### Actual result

Error

**Comment by ElephantInTheRoomFirst** [comment]
Related issue
https://github.com/joomla/joomla-cms/issues/21334

**Comment by ElephantInTheRoomFirst** [comment]
It will be great if anyone explains how to reset password in database in J4. The J3 MD5 method does not work anymore.

**Comment by ReLater** [comment]
> The J3 MD5 method does not work anymore.

Did you also try the SQL steps below headline "Add a New Super Administrator User" with a **new** user.
https://docs.joomla.org/How_do_you_recover_or_reset_your_admin_password%3F

Please provide some more system informations. I know that it works but also know that it doesn't work sometimes ;-)

Any error messages?

> was reset to random value

It's not a random value as far as I remember but Joomla accepts the first login but then tries to use a less weak encryption method than MD5 and hardens/salts the weak MD5 password.

**Comment by ElephantInTheRoomFirst** [comment]
Thanks for the reply. I tried to direct edit password in database. It did not either. There is not error message, just I get the login screen again.

**Comment by ElephantInTheRoomFirst** [comment]
I have just reinstalled latest version of J4. It seems working again. :)
Previously, I had disabled some extensions to make it light weight. Do you know any non-core (which can be disabled) extension which will prevent me from logging in?

**Comment by brianteeman** [comment]
You should not disable the plugins **Authentication - Joomla** or **User - Joomla!**

**Comment by brianteeman** [comment]
You should not disable the plugins **Authentication - Joomla** or **User - Joomla!**

**Comment by ghost** [comment]
closed as Issue solved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22738">issues.joomla.org/tracker/joomla-cms/22738</a>.</sub>
