### ISSUE TITLE
An error has occurred while processing installation

### ISSUE THREAD

**Issue by mehdiMj-ir** [joomla/joomla-cms#22742]
### Steps to reproduce the issue
I wanted to try Joomla 4, so I download joomla 4 alpha 3 full package.I create a database in my local host and extract joomla zip file in to a folder.
when try to write an address and install joomla4, this happened.  

### System information (as much as possible)

An error has occurred while processing your request.
0 Call to a member function getLabel() on null

### Additional comments
![screenshot from 2018-10-20 16-20-48](https://user-images.githubusercontent.com/20270329/47255917-6af4cd80-d484-11e8-8e1b-2f0b0fd862d8.png)

**Comment by ReLater** [comment]
Please use installation and update packages from this source:
https://developer.joomla.org/nightly-builds.html

**Comment by mehdiMj-ir** [comment]
> Please use installation and update packages from this source:
> https://developer.joomla.org/nightly-builds.html

tank you very much, I download Joomla 4 Alpha 5 and works perfectly :+1:
