### ISSUE TITLE
[4.0] Forum links in menu

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#22759]
Unless I am mistaken the following code is not longer required  in the menu as the links have been moved to `administrator\components\com_admin\tmpl\help`

@infograf768 or others - if you can confirm that I can remove the code

https://github.com/joomla/joomla-cms/blob/97ba92fe2e969efdcd0e5e22d6be5b9b1c645edf/administrator/modules/mod_menu/Menu/CssMenu.php#L271-L282

**Comment by infograf768** [comment]
If you grep for
`index.php?option=com_admin&amp;view=help&amp;layout=langforum` 
you will find it 3 times in J4.
in CssMenu.php
in Menushelper.php
in the HtmlView.php

Until custom admin menus issue is solved I would leave all this alone.

**Comment by brianteeman** [comment]
its nothing to with custom admin menus

these forum links are now in the help page
