### ISSUE TITLE
Multilingual associations link is missing in Components

### ISSUE THREAD

**Issue by RedStar87** [joomla/joomla-cms#22756]
### Steps to reproduce the issue

Updated to Joomla 3.8.13 - the link to the Multilingual Associations (Manager) is no more available from the Components tab in Joomla.

### Expected result

The Multilingual Associations component is already installed and seems to be activated. Plugins "Language Filter" and "Language Code" are activated and correctly set.

### Actual result

However the link to the Multilingual Associations is not displayed when going to the "Components" tab.

### System information (as much as possible)

Joomla! 3.8.13 Stable [ Amani ] 9-October-2018 14:00 GMT
PHP 7.2.11
MySQL version: 5.6.41-cll-lve

### Additional comments

I checked in my database through PHP MyAdmin and "com_associations" can not be found anywhere in my database...

Thanks in advance,

Max.

<img width="578" alt="greenshot 2018-10-21 21 08 50" src="https://user-images.githubusercontent.com/44346451/47271154-15005280-d576-11e8-89f1-9181cff054e2.png">
<img width="1272" alt="greenshot 2018-10-21 21 09 40" src="https://user-images.githubusercontent.com/44346451/47271155-1c276080-d576-11e8-8a23-992a016cff3a.png">
<img width="1269" alt="greenshot 2018-10-21 21 10 25" src="https://user-images.githubusercontent.com/44346451/47271158-1fbae780-d576-11e8-9225-02a308865507.png">

**Comment by infograf768** [comment]
Looks like your update did not go well. 
You may have to update again. What was the version you updated from?

**Comment by infograf768** [comment]
Your extension manager is showing com_associations. Therefore that means the component exists in the _extensions table. Refresh cache there to be sure.
Have you checked your _menu table in the db? Maybe the menu item is unpublished
<img width="1369" alt="screen shot 2018-10-22 at 06 52 51" src="https://user-images.githubusercontent.com/869724/47278226-80bedb80-d5c7-11e8-9e23-a534f391de41.png">

**Comment by RedStar87** [comment]
I checked in the _extensions table but there’s nothing related to « com_association »…

![greenshot 2018-10-22 08 52 24](https://user-images.githubusercontent.com/44346451/47281212-2b3ffa00-d5da-11e8-86dc-ab2c964ae053.png)


There’s no entry also in _menu table:

![greenshot 2018-10-22 09 03 15](https://user-images.githubusercontent.com/44346451/47281216-33983500-d5da-11e8-8cc3-a2f5a383206f.png)


I refreshed the DB already.

**Comment by infograf768** [comment]
1. refresh cache in Extensions=>Manage

Does the component still shows?

2. Verify that the component is present in administrator/components/

**Comment by RedStar87** [comment]
Hi I checked in the _extensions table but there’s nothing related to « com_association »…




There’s no entry also in _menu table:



I refreshed the DB already.


Regards,

Max.

**Comment by RedStar87** [comment]
>     1. refresh cache in Extensions=>Manage
> 
> 
> Does the component still shows?
> 
>     1. Verify that the component is present in administrator/components/

Hi!

Affirmative, after a Refresh in "Extensions-Manage" the component is still there, but always missing in Administrator-Components

![greenshot 2018-10-24 21 04 52](https://user-images.githubusercontent.com/44346451/47454965-da462680-d7d0-11e8-8c50-6cf8e13f4027.png)

<img width="574" alt="greenshot 2018-10-24 21 08 50" src="https://user-images.githubusercontent.com/44346451/47455024-095c9800-d7d1-11e8-98a8-c07bad08974d.png">

**Comment by infograf768** [comment]
Something is wrong here.
You normally can't have the component showing in Extensions: Manage after refreshing cache if com_associations is NOT present in the _extensions table in the database.
This is not a joomla bug. Please ask for help in the forums as this needs access to your site as super user to try to solve the issue.
