### ISSUE TITLE
Not able to create admin menu in J4 from preset.

### ISSUE THREAD

**Issue by DonaldTrump88** [joomla/joomla-cms#22758]
### Steps to reproduce the issue
Install J4 22.10..1018
Go to menu manager
Create admin menu and set Joomla or Mordern as preset
Click save then you get the following error. 

### Expected result
Creation of menu without error. 

### Actual result
This is the error
Menu was saved but failed to import the preset: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') GROUP BY c2.`id`) AS c2 ON c2.newId = c.`id` SET `published` = c2.newPublished' at line 6

### System information (as much as possible)
PHP Built On	removed
Database Type	mysql
Database Version	5.5.61-MariaDB-cll-lve
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8_general_ci
PHP Version	7.1.23
Web Server	Apache
WebServer to PHP Interface	litespeed
Joomla! Version	Joomla! 4.0.0-alpha5-dev Development [ Amani ] 22-July-2018 22:58 GMT

Relevant PHP Settings
Setting	Value
 
Open basedir	None
Display Errors	Off
Short Open Tags	On
File Uploads	On
Output Buffering	On
Session Save Path	/opt/alt/php71/var/lib/php/session
Session Auto Start	0
XML Enabled	Yes
Zlib Enabled	Yes
Native ZIP Enabled	Yes
Disabled Functions	None
Multibyte String (mbstring) Enabled	Yes
Iconv Available	Yes
Maximum Input Variables	1000

Setting	Value
offline	
offline_message	This site is down for maintenance.<br>Please check back again soon.
display_offline_message	1
offline_image	
sitename	Joomla 4 Alpha 5 - 22.10..2018
editor	tinymce
captcha	0
list_limit	20
access	1
debug	
debug_lang	
dbtype	mysqli
host	xxxxxx
user	xxxxxx
password	xxxxxx
db	gteinc_
dbprefix	ap9b9_
live_site	
secret	removed
gzip	
error_reporting	default
helpurl	https://help.joomla.org/proxy?keyref=Help{major}{minor}:{keyref}&lang={langcode}
ftp_host	
ftp_port	
ftp_user	xxxxxx
ftp_pass	xxxxxx
ftp_root	
ftp_enable	0
offset	UTC
mailonline	1
mailer	mail
mailfrom	info@igsmart.tech
fromname	Joomla 4 Alpha 5 - 22.10..2018
sendmail	/usr/sbin/sendmail
smtpauth	
smtpuser	xxxxxx
smtppass	xxxxxx
smtphost	localhost
smtpsecure	none
smtpport	25
caching	0
cache_handler	file
cachetime	15
cache_platformprefix	
MetaDesc	
MetaKeys	
MetaTitle	1
MetaAuthor	1
MetaVersion	
robots	
sef	1
sef_rewrite	
sef_suffix	
unicodeslugs	
feed_limit	10
feed_email	none
log_path	removed
tmp_path	removed
lifetime	15
session_handler	database
shared_session	
session_metadata	1

**Comment by Quy** [comment]
Please test PR #22852<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22758">issues.joomla.org/tracker/joomla-cms/22758</a>.</sub>
