### ISSUE TITLE
Update releases should NOT change old sql update files

### ISSUE THREAD

**Issue by janmyszkier** [joomla/joomla-cms#22754]
### Steps to reproduce the issue
1. Install Joomla from any year (i.e: 2017)
2. Wait till a new year (2018)
3. Download first release from 2018, check any update file that has copyright in it. I.e:
/administrator/components/com_admin/sql/updates/mysql/3.0.0.sql

### Expected result
New installer files should be provided when changing data. old installers should NOT be changed.

### Actual result
Copyright years is updated within OLD installer file.

### System information (as much as possible)
any system, this is about installer file contents.

### Additional comments
I understand doing `sed` replace inline or simple "Find and replace in the project" is easy and fast. But this is not how data consistency is enforced. 
This also makes very hard to realize what has changed in the update and if it is important or not because of a lot of copyrights changes within the files.

**Comment by brianteeman** [comment]
Not sure how a change would help you now.

**Comment by Bakual** [comment]
> This also makes very hard to realize what has changed in the update and if it is important or not because of a lot of copyrights changes within the files.

Just to give you some heads up. In the release note, you see if the update is important or not. If it's called a security update, it is important - no excuses. If it is a regular update, you can delay the update a bit, but it still absolutely should be installed.
As long as you don't do any core hacks (which you must not do anyway), it shouldn't matter to you what changes were done in the update in detail. You're going to apply the update sooner or later anyway.

So imho, I see no reason to change our past behavior of changing the copyright in all files (SQL files included). If there are other reasons to not change the copyright date, we can evaluate it for sure, but this reason doesn't sound like a good enough argument to me.

**Comment by janmyszkier** [comment]
@brianteeman :
If the process is bad (and here, it is), and there's a way to improve it in the future, it SHOULD be improved. Especially when it saves time. 

@Bakual 
Once the update is not about security BUT it changes the way our core business functionality works (i.e - just stupid example - form handling), then for the business/client it is also important to look into how that thing was changed without browsing through thousands of files that just changed copyright notice along with the rest of the update. Security updates are another type of the required code updates.

**Comment by brianteeman** [comment]
1. I dont believe the process is bad
2. Even if it was changed now it wont help you
3. You should be updating joomla through the joomlaupdate component

**Comment by mbabker** [comment]
If you're talking about copyright statements in the extension manifest caches, honestly those caches shouldn't be in the SQL files anyway as they're automatically (re-)generated at initial install or update.  So that's a non-issue.

If you're talking real structure or "critical" core data changes, agree in full.

**Comment by janmyszkier** [comment]
@brianteeman 
> Even if it was changed now it wont help you

Can you elaborate on this? Because right now what you're saying doesn't make sense (at least not without context)

> You should be updating joomla through the joomlaupdate component

Are you sure update component doesn't update the old files copyright? (making Joomla package files and server files inconsistent, so doesn't sound like a good thing)

**Comment by ghost** [comment]
@HLeithner can you please comment for J3?

**Comment by janmyszkier** [comment]
Just another reason to change this - save time:
example:
- install update using downloaded package (because developer use git and they put files in git, so the company deployment tool can move it to the server)
- you want to see what was the changed logic between update on december and update on january and see if there's something you need to alter in your code
- good luck analyzing thousands of files, because copyrights changed in them too

**Comment by HLeithner** [comment]
That's a legal decision. Maybe @ronnikc can say something about this.

**Comment by brianteeman** [comment]
I would like to correct my comments above. I was under the impression that OLD update sql files would not be looked at again after they had been used. Seems that there is a bug that instead of being fixed people have change those old update files and they are being looked at

**Comment by jwaisner** [comment]
@HLeithner do we have any update to provide here or is the determination that it is a legal decision for this issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22754">issues.joomla.org/tracker/joomla-cms/22754</a>.</sub>

**Comment by HLeithner** [comment]
Since it's a legal thing I will contact Hugh Douglas-Smith about this.

**Comment by brianteeman** [comment]
@HLeithner I guess nothing is going to happen here now and this should be closed. Not my call though

**Comment by HLeithner** [comment]
Since we no longer update old files and set all copyright dates to the (hopefully) original date this issue can be closed because it's solved. @brianteeman thanks for pointing me to this pr again.

**Comment by brianteeman** [comment]
Well we dont update old files for copyright but the sql update files are not immutable as I constantly debate with @richard67
