### ISSUE TITLE
[4.0] Modules language files no more loaded correctly

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#22768]
### Steps to reproduce the issue
Install J4 Alpha5, install a module having language files included in the module path such as:

Joomla40/modules/mod_mymodule/language/en-GB/en-GB.mod_mymodule.ini

### Expected result
Language files are correctly loaded from Joomla40/modules/mod_mymodule/language/en-GB/en-GB.mod_mymodule.ini

### Actual result
Language files are loaded from Joomla40/modules/mod_mymodule/language/en-GB/en-GB.mod_mymodule.ini but seems lost or overwritten at some point, and the result is having modules strings untranslated.

**Comment by infograf768** [comment]
Can you post such a module?
I wanted to test for plugins but I can't install a 3.x plugin on j4 because I get a `Call to a member function clean() on null` from
`Undefined variable: pathObject in /Applications/MAMP/htdocs/installmulti/joomla40/libraries/src/Filesystem/File.php on line 472`

**Comment by infograf768** [comment]
Also tested after modifying that plugin to use J4 methods. Same result.

**Comment by infograf768** [comment]
Ok, therefore I added the plugin manually and I discovered it Ok.
Language file is loaded fine.
Will try to find a module where the language files are only in its language folder to test your issue (on last j4.0-dev)

**Comment by infograf768** [comment]
Strings are loaded OK in backend for a module.
Do you have the issue in backend as well as frontend?

**Comment by laoneo** [comment]
@joeforjoomla where do you see untranslated strings?

**Comment by laoneo** [comment]
@infograf768 please test https://github.com/joomla/joomla-cms/pull/22771 if the upload works now.

**Comment by joeforjoomla** [comment]
@infograf768 @laoneo refer to this PR #22786 where i narrowed down the problem, probably due to the recently merged modules dispatcher

**Comment by infograf768** [comment]
@joeforjoomla 
You have not replied to my question.
Is the issue present in frontend too?
IN backend I could not reproduce your issue.

Please add here the zip of a module for which you have the issue as I could not reproduce it.

**Comment by infograf768** [comment]
I again did a test:
I took off from the core language folder in admin the 2 files
en-GB.mod_multilangstatus.ini
en-GB.mod_multilangstatus.sys.ini

These 2 files are also present in the language folder of the module.
They ARE loaded OK, as can be seen in the debug below:

<img width="976" alt="screen shot 2018-10-24 at 07 24 03" src="https://user-images.githubusercontent.com/869724/47408062-1e4c1380-d75e-11e8-9931-081b54e7c142.png">

**Comment by infograf768** [comment]
To test debug lang for site modules, one has first to apply this patch:
https://github.com/joomla/joomla-cms/pull/22775

**Comment by infograf768** [comment]
HMm, tested in frontend and the issue IS in frontend.
will test now https://github.com/joomla/joomla-cms/pull/22786

**Comment by infograf768** [comment]
See my comment https://github.com/joomla/joomla-cms/pull/22786#issuecomment-432528628
