### ISSUE TITLE
Sending message to user from update server when update not available.

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#22767]
### Steps to reproduce the issue

Currently if the update server wants to stop updates for any item the only way I can see to do this is for the update server admin to invalidate the downloadurl.  The messages produced are not user friendly.

Looking at https://docs.joomla.org/Deploying_an_Update_Server a possible method would be to add another element to the XML with a message such as...

```xml
<noupdatemessage>This a helpfull message.</noupdatemessage>
```

When a user attempts to update an extension and encounters an XML containing such an element the update is gracefully abandoned and the supplied message displayed.

This feature could also be used to provide information to a user when a purchase / subscription is required. Which is actually my reason for raising this issue.

### Expected result

As explained above.

### Actual result

No user friendly information

**Comment by brianteeman** [comment]
Have a look at JEvents
They change the extension name in the update manager to

JEvents - Calendar Plus . ** Your JEvents Club subscription has expired **
--

![image](https://user-images.githubusercontent.com/1296369/47340144-428fed80-d695-11e8-8128-71efa4b32f41.png)

**Comment by BrainforgeUK** [comment]
Thanks, almost but not quite.
The user is still able to select the extension and try an update.
In this example I want to replace the error message with the warning.

Warning generated by a fiddle in the extension XML manifest, which ideally would like to avoid.
![update-1](https://user-images.githubusercontent.com/3941269/47348548-a02e3500-d6a9-11e8-8594-a85f11d90403.jpg)

**Comment by brianteeman** [comment]
This is a very old request for a new feature in Joomla 3. As there has been no interest in providing any code to satisfy this and we are not accepting any new features in Joomla 3 I recommend that it is closed.

**Comment by alikon** [comment]
Closed as stated above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22767">issues.joomla.org/tracker/joomla-cms/22767</a>.</sub>
