### ISSUE TITLE
[4.0] Resizing template editor causes multiple editor instances

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22778]
### Steps to reproduce the issue

This doesn't happen on 3.8.13
Install Joomla 4.0-dev @ 9d3acfd9d589989e86bda3fe35f58a47323d66f4
Login to Admin -> System -> Site Templates -> Cassiopeia Details and Files -> index.php 

### Expected result

Be able to see enough of the file to meaningfully edit it.
Only see one editor instance

### Actual result

1) only 19 rows of the editor are visible (on my laptop) 

2) On resizing the browser from big to small and back to big - I now get THREE editor instances!

<img width="1460" alt="screenshot 2018-10-23 at 20 39 28" src="https://user-images.githubusercontent.com/400092/47386117-c41e6480-d703-11e8-87d6-b3c715056429.png">
 
### System information (as much as possible)

Google chrome 70 on mac

**Comment by brianteeman** [comment]
Cannot replicate on Chrome 70 - windows

**Comment by PhilETaylor** [comment]
I can still replicate this today on all browsers on mac (Google Chrome, Safari, Firefox tested) which rules out this being a browser issue and rules out extensions in google chrome and rules out it being specific to my work mac (as its 0549am and Im at home now on a different mac)

Exact URL I'm on http://0.0.0.0/administrator/index.php?option=com_templates&view=template&id=510&file=L2NvbXBvbmVudC5waHA%3D

To replicate this, drag the right hand side of the browser to the left to crate a tall browser window (all the way, and back again) 

Each time you do that you will get THREE textareas. Each time

![screen recording 2018-11-08 at 05 48 am](https://user-images.githubusercontent.com/400092/48180108-0fe32780-e31a-11e8-9d25-7bb5662801f6.gif)

**Comment by infograf768** [comment]
I am afraid I do not even get codemirror here (last branch version):

<img width="978" alt="screen shot 2018-11-09 at 08 52 20" src="https://user-images.githubusercontent.com/869724/48249936-dfc08500-e3fc-11e8-92be-a9a33f0a429c.png">

**Comment by infograf768** [comment]
Only this:
SyntaxError: expected expression, got '<'[Learn More] localhost:8888:2

**Comment by infograf768** [comment]
It is on a multilingual site btw.

**Comment by Scrabble96** [comment]
I am also getting this on joomla.com CloudAccess.net website, using Firefox. Currently five screens.
This is on J4.0 Alpha 7 dev.
![image](https://user-images.githubusercontent.com/36987494/50702031-9892f100-1047-11e9-8783-8cde00f8406b.png)

**Comment by Scrabble96** [comment]
Why was this issue closed? Or is there a PR for it now? I'm still getting multiple instances of codemirror when resizing my desktop screen to a smaller width. I've just checked on the Joomla_4.0.0-alpha11-dev-Development-Full_Package build Sat 03 Aug 2019.

**Comment by Scrabble96** [comment]
Could this be linked to overrides in some way? When working on an override it is possible to have the three views, headed "Overridden file (editable)", "Original file (readonly)" and "Diff between original and overridden file" respectively. On re-sizing the wide desktop to a narrow view, each of the first two views is duplicated, but interestingly, not the 'differences' view. Resize back and forth again, and the first two views have four copies but the last one is still single.

**Comment by PhilETaylor** [comment]
Just to confirm this still happens today, and in beta 1

**Comment by shim-sao** [comment]
Still here in beta 3
- Open browser tools (ctrl+shift+i) => _ok_
- Close the tools => _duplication of the editor_
- Re-open the tools => _duplication of the editor again_
`404 Failed to load resource: /media/vendor/codemirror/mode/text/html/text/html.min.js`
- ... duplication again & again<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22778">issues.joomla.org/tracker/joomla-cms/22778</a>.</sub>

**Comment by shim-sao** [comment]
I found a javascript error here : `/media/plg_editors_codemirror/js/joomla-editor-codemirror.js`
```
this.checkElement('CodeMirror', 'findModeByName').then(() => {
  // For mode autoloading.
  window.CodeMirror.modeURL = this.getAttribute('mod-path'); // Fire this function any time an editor is created.
```
On a second call a new instance of the editor is created with the bad url.
`console.log(' modeURL = ' + this.getAttribute('mod-path'))`

Adding a counter of instance seems to resolve the problem : 

```
super()
this.n = 0
```
```
this.n += 1
if (this.n > 1) {
  return;
}
window.CodeMirror.modeURL = this.getAttribute('mod-path');
```
works also with multiple editors like in associations for example

**Comment by brianteeman** [comment]
Thats great - could you submit a pull request please

**Comment by shim-sao** [comment]
After several tests this created new bugs but I think I found where the error really came from.
```
if (this.instance !== '') {
  Joomla.editors.instances[this.element.id] = this.instance;
  return;
}
```
if you don't add the instance to the list, buttons like readmore don't work anymore

**Comment by richard67** [comment]
Closing as having a PR. Please test #30240 . Thanks @shim-sao for the fix, it looks good to me at code review.

**Comment by richard67** [comment]
Feel free to re-open this issue if the PR doesn't fix it completely.

**Comment by richard67** [comment]
Hmm, PR was closed, don't know why. New PR is #30241 . Please test.

**Comment by shim-sao** [comment]
I have create a new pull request because I don't have updated my fork before.
I discover a little github, very sorry :(

**Comment by richard67** [comment]
Ok, no problem.
