### ISSUE TITLE
Error: Failed to start application: Failed to start the session

### ISSUE THREAD

**Issue by manelizaorcadia** [joomla/joomla-cms#22770]
I updated the joomla to the recent version 3.8.13 because I always got an error when accessing the front page as it says:

session_start(): Cannot find save handler 'memcached'... So I updated the configuration file and deleted the new variables like memcache_ , etc.. 

I was able to access the front page, but now, I can't access the administrator's area as it always say:

Error: Failed to start application: Failed to start the session

Hope you can help. Thanks

**Comment by brianteeman** [comment]
Do you have
```

	public $session_handler = 'database';
	public $shared_session = '0';
```

**Comment by manelizaorcadia** [comment]
Hello, thank you for the reply, and yes, I have them. 

`public $lifetime = '1440';
public $session_handler = 'database';
public $shared_session = '0';`

I don't have issue before until recently.

**Comment by brianteeman** [comment]
This really should be asked on the forum https://forum.joomla.org

**Comment by manelizaorcadia** [comment]
Oops, okay, thanks. I posted in their facebook and said to post it here to address the issue.
