### ISSUE TITLE
Serialization of 'Closure' is not allowed 

### ISSUE THREAD

**Issue by stankurd** [joomla/joomla-cms#22777]
### Steps to reproduce the issue
After last git udate i heve this bug in frontend view
Serialization of 'Closure' is not allowed 

Call stack
--
# | Function | Location
1 | () | JROOT\libraries\src\Document\HtmlDocument.php:472
2 | serialize() | JROOT\libraries\src\Document\HtmlDocument.php:472
3 | Joomla\CMS\Document\HtmlDocument->getBuffer() | JROOT\libraries\src\Document\HtmlDocument.php:797
4 | Joomla\CMS\Document\HtmlDocument->_renderTemplate() | JROOT\libraries\src\Document\HtmlDocument.php:569
5 | Joomla\CMS\Document\HtmlDocument->render() | JROOT\libraries\src\Application\CMSApplication.php:986
6 | Joomla\CMS\Application\CMSApplication->render() | JROOT\libraries\src\Application\SiteApplication.php:764
7 | Joomla\CMS\Application\SiteApplication->render() | JROOT\libraries\src\Application\CMSApplication.php:239
8 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\includes\app.php:63
9 | require_once() | JROOT\index.php:36

in backend no problem
### System information (as much as possible)

Setting | Value
-- | --
 
Windows NT OLA-TOSH 6.1 build 7601 (Windows 7 Home Premium Edition Service Pack 1) AMD64
mysql
5.7.23
utf8_general_ci
utf8_general_ci
7.2.10
Apache/2.4.17 (Win64) PHP/7.2.10
apache2handler
Joomla! 4.0.0-alpha5-dev Development [ Amani ] 22-July-2018 22:58 GMT
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/issues/22685

**Comment by brianteeman** [comment]
Closing as we dont need multiple reports of the same thing
