### ISSUE TITLE
[4.0] No flag on message icon on arrival of new private message

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22785]
### Steps to reproduce the issue

set up 2 super admins
send a private message from A to B
login as B

### Expected result

Expect to see a red dot/number on the envelope in the top right 

### Actual result

<img width="711" alt="screenshot 2018-10-23 at 21 32 48" src="https://user-images.githubusercontent.com/400092/47388924-55dda000-d70b-11e8-9004-1975809198c4.png">

Example when there is post installation messages
<img width="441" alt="screenshot 2018-10-23 at 21 34 11" src="https://user-images.githubusercontent.com/400092/47388946-65f57f80-d70b-11e8-93ec-26ad6181a390.png">

**Comment by C-Lodder** [comment]
Number no longer appears to be part of the session for some reason. Will probably require a custom query in the module helper
