### ISSUE TITLE
[4.0] js error on resizing screen

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22788]
### Steps to reproduce the issue

Login to Joomla 4.0-dev @9d3acfd9d589989e86bda3fe35f58a47323d66f4
resize your browser a little

### Expected result

NO Js error

### Actual result

JS error 

```
admin-menu.min.js?714bd7c681dcb1da83e738c93edacebc:1 Uncaught ReferenceError: setMenuHeight is not defined
    at admin-menu.min.js?714bd7c681dcb1da83e738c93edacebc:1
```
<img width="1012" alt="screenshot 2018-10-23 at 21 49 57" src="https://user-images.githubusercontent.com/400092/47389792-9a6a3b00-d70d-11e8-85ac-a6555e8635b8.png">

### System information (as much as possible)
Chrome 70 on mac

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/22809
