### ISSUE TITLE
[RFC] Move system features out of components

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22787]
Thinking out the box. Joomla 4 is the right time for major changes.

The word "components" is very Joomla specific, not user friendly and can be badly misunderstood in other contexts. 

So, these menu items are currently under components in admin: 

Joomla Update 
Messaging
Multilingual Associations
Post Installation Messages
Redirects
and more maybe 

are more system administrator tasks than user tasks. I know they are "really" components as defined by their code structure and com_something but their TASKS are more suited to the Super Admin / Maintenance of the site

Could Joomla take the bold step and move these into System area of Joomla 4? Maybe creating a "system" type of component somehow.

So after 1 year the site has 

Akeeba Backup - a system component, users maybe use occasionally, Super Admins use a lot
JCE Editor - a system component, users maybe use occasionally, 

JEvents - in components, users use this
Event Booking - in components, users use this daily 
Ozio Gallery  - in components, users use this daily 
Hikashop -  - in components, users use this daily 

Or even, more thinking out side the box, these 4 should come under **Site Content** (currently called content) BECAUSE THAT IS WHAT THEY ARE, the sites content! 

There are other menu moves, for example, "Administrator Modules" doesnt need to be under Content!!! , same for many fields and field groups and workflows - these are all system things 

maybe on installation a component can declare what they do, and be added to the right menus dynamically? Its either generating content for a site, or it is a system tool. (any other types of component you can think of, nope?)

thoughts?

**Comment by uglyeoin** [comment]
I like this idea but we have a Joomla! admin menu creator.  Does that solve your requirement?  Not that this is a bad idea, I think the default installation could easily include these and it WOULD be an improvement.

**Comment by PhilETaylor** [comment]
> Does that solve your requirement? 

I have no requirements! 

Im just trying to simplify the default installation of Joomla.

**Comment by uglyeoin** [comment]
Sounds like a sensible suggestion to me.

**Comment by PhilETaylor** [comment]
> Its clear I'm not welcome to contribute to this project. So I will refrain from doing so in the future.
