### ISSUE TITLE
[RFC] Deprecate use of a locked lock to indicate checked-out

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22782]
When an item is checked out, we show a locked lock.

A locked lock icon also symbolises "secure" to the average internet user

We are trying to say the item is "being edited by someone else" (or "locked") but in 2018 I think the secure locked lock is indicating to the average user something else. Back in 2001 this would have been acceptable, but with the push to a more secure web, the locked padlock has come to symbolise something different. 

Feel free to disagree - I know many will, but it seems the time is right in 4.0 to find another way to show that an item is being edited by someone else, than using the lock symbol that browsers use to indicate "Secure" 

<img src="https://static.joomlart.com/images/tutorials/CheckIn/can-not-access.png">

Image stolen from https://www.joomlart.com/tutorials/joomla-tutorials/joomla-site-maintenance-global-check-in-explained

**Comment by rotech1** [comment]
what's a symbol that indicates "blocked" ( or 'ye shall not pass...' ) ??

**Comment by PhilETaylor** [comment]
> what's a symbol that indicates "blocked" ( or 'ye shall not pass...' ) ??

I don't have all the answers. That's why this is an RFC. 

The hyperlinked title could have its hyperlink removed, and maybe a label with the word [checked out]

Or the non hyperlinked title could actually provide helpful feedback like

`A Title - (Currently being edited by Mike Simms)`

**Comment by chmst** [comment]
What co you think about the icon "ban"? https://fontawesome.com/v4.7.0/icon/ban<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22782">issues.joomla.org/tracker/joomla-cms/22782</a>.</sub>

**Comment by ggppdk** [comment]
So what other applications are using to indicate a checked out record ?

A locked icon
A door with an exiting arrow icon
other ?

I think choice to consider would be (an available icon resembling the following ?)
a door with a both way arrow
a document with a lock

**Comment by infograf768** [comment]
what about this
https://fontawesome.com/v4.7.0/icon/hand-paper-o

**Comment by chmst** [comment]
What do we want to show? That the item is protected (so the lock is correct).
Or that the access is forbidden? Then we can use the ban icon or minus-circle
Or we say "keep out" then the hand-paper-o could do, but for me it is not self-explaining. 

My2cent: no matter what we choose, some people will disagree - so why not keep the lock icon?

**Comment by PhilETaylor** [comment]
> so why not keep the lock icon?

Because things have now changed. Its 2018. The lock icon is promoted and used by all browsers, all services to indicate a "Secure" page. 

We are **not** trying to indicate that an item is secure. We are trying to indicate that you have no access to edit it, because it is currently being edited by another user. 

The item is not protected - its being edited by someone else at this time. Big difference.
Access is not forbidden -its being edited by someone else at this time. Big difference.
We are not saying"keep out" - we are saying its being edited by someone else at this time. Big difference.

Well as its clear no one agrees with this I'll just shut up 

Ask any "normal web user" what a locked padlock is, and they will all tell you it means the page is secure. 


examples - not one with a locked padlock

<img width="906" alt="edit-log-plugin-confluence-4" src="https://user-images.githubusercontent.com/400092/47687623-59a37380-db9e-11e8-9b50-ee1d251642c3.png">
<img src="https://user-images.githubusercontent.com/400092/47687629-5f995480-db9e-11e8-82eb-0454749727c6.jpeg">
<img src="https://user-images.githubusercontent.com/400092/47687639-7344bb00-db9e-11e8-8b51-c77d51e7e3bc.png">
<img width="601" alt="image" src="https://user-images.githubusercontent.com/400092/47687652-7c358c80-db9e-11e8-9e6b-6a1ab6402a1b.png">
<img src="https://user-images.githubusercontent.com/400092/47687653-7c358c80-db9e-11e8-954f-1d09f4d58fb0.png">
<img src="https://user-images.githubusercontent.com/400092/47687654-7c358c80-db9e-11e8-9a3a-9912213d5c3c.png">
<img src="https://user-images.githubusercontent.com/400092/47687655-7cce2300-db9e-11e8-8a26-79028f6eec86.png">
<img src="https://user-images.githubusercontent.com/400092/47687656-7cce2300-db9e-11e8-8ff6-3223e3bbd380.png">
<img src="https://user-images.githubusercontent.com/400092/47687657-7cce2300-db9e-11e8-9d60-7039dd193991.png">
<img src="https://user-images.githubusercontent.com/400092/47687658-7cce2300-db9e-11e8-8071-c822d34289f2.png">
<img src="https://user-images.githubusercontent.com/400092/47687659-7cce2300-db9e-11e8-8280-895368e0585f.jpg)
![savedocument](https://user-images.githubusercontent.com/400092/47687660-7d66b980-db9e-11e8-87a0-346a3d5887fe.png">

**Comment by mbabker** [comment]
That set of comparisons is really unfair to the context that we're using the icon in.  The icon is representing a status flag on the record and is shown in a list of other items, each of those screenshots is in essence either a warning message or a confirmation prompt that looks to be shown after trying to open a locked or checked out item.

**Comment by PhilETaylor** [comment]
My daughter says why not an animated three dots - like the “I’m typing” indicator in literally every chat app when you are waiting for someone else to type.... add a hover message on that, or on attempting to edit it a modal warning saying it’s being edited by who and if acl allows, allow to checkin direct from there and continue to edit....

We can do better than just a lock icon I’m sure!

——
Sent from my iPhone - sorry - if needed I’ll send longer email from my desk later.
——

**Comment by PhilETaylor** [comment]
#close

——
Sent from my iPhone - sorry - if needed I’ll send longer email from my desk later.
——

**Comment by mbabker** [comment]
I'm not heavily invested in what icon is used, just pointing out that your comparisons weren't entirely fair for the contexts they're used in.

**Comment by chmst** [comment]
When I teach admins, I have to explain many things .. for example: no user underrstands why trashed items are found via the status filter. But everyone understands intuitively that an item is protected or locked because another user is working on it. 
For me, the lock used by browsers to indicate the secure page is wrong. I would expect a "success" icon to indicate: this site is all right, it is secure. :D

**Comment by AMurray2016** [comment]
> what's a symbol that indicates "blocked" ( or 'ye shall not pass...' ) ??

Something like the "prohibited" or "no-entry" symbol? I'm sure they are used world-wide, and their meaning would be relatively clear in the context of a checked-out article.

**Comment by chmst** [comment]
I am not interested in the icon too, but like this Idea 
>The hyperlinked title could have its hyperlink removed, and maybe a label with the word [checked out]
Or the non hyperlinked title could actually provide helpful feedback like 

Something like this is informative. 

![checked-out](https://user-images.githubusercontent.com/1035262/47962468-62240000-e01d-11e8-977b-60d433c1fb46.PNG)

**Comment by hardik-codes** [comment]
Does this issue needs to be taken ahead?

**Comment by chmst** [comment]
I don't know - if you make a PR, let' see what happens. This information is used in nearly every list view. Make one, for example in com_contacts, so we can see it.

**Comment by coolcat-creations** [comment]
I like the ideas of the 3 animated dots. But for this leaving the article unsaved should check the article in. Like described in this issue: https://github.com/joomla/joomla-cms/issues/22060

It does not make sense to keep it checked in, when the user is not working on it anymore.

I bet there is a way to solve this issue by having something like a pair between session cookie and article edition. If the pair gets "disconnected" the article has to be checked in again.
