### ISSUE TITLE
[4.0] Batch modal button unstyled

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22781]
### Steps to reproduce the issue

Joomla 4.0-dev @ 9d3acfd9d589989e86bda3fe35f58a47323d66f4
in Articles list select all and then click batch

### Expected result

Styled buttons

### Actual result

<img width="1468" alt="screenshot 2018-10-23 at 21 12 16" src="https://user-images.githubusercontent.com/400092/47387855-76582b00-d708-11e8-893b-8050ee2e2b5c.png">

### System information (as much as possible)

Chrome 70.

**Comment by wilsonge** [comment]
Closed as we have a PR #23137
