### ISSUE TITLE
[4.0] Cannot order access levels with drag and drop 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22789]
### Steps to reproduce the issue

Tombola 4.0-dev @ 9d3acfd9d589989e86bda3fe35f58a47323d66f4
Login to admin
Users -> Access Levels
drag with the drag handle a row to another place in the list
drop

### Expected result

Something to happen, (I dont actually understand why you can drag/drop these as the ACL tree is more complicated than just the ordering ) 

### Actual result

On drop, an ajax request is made which returns with a 500 Server Error response.

```
Call to a member function saveorder() on boolean
```

<img width="942" alt="screenshot 2018-10-23 at 21 59 25" src="https://user-images.githubusercontent.com/400092/47390306-ee295400-d70e-11e8-8a1f-77a862143f44.png">

**Comment by chmst** [comment]
In my application (newest 4.0 dev, oct. 27) I can order the viewlevels by drag and drop. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22789">issues.joomla.org/tracker/joomla-cms/22789</a>.</sub>
