### ISSUE TITLE
[4.0] JS Error when "no matching results"

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22784]
### Steps to reproduce the issue

Joomla 4.0-dev @ 9d3acfd9d589989e86bda3fe35f58a47323d66f4
Components -> Messaging -> New Private Message
Click button to select a user

### Expected result

No JS error
Close button styled

### Actual result

JS Error in console

```
Uncaught TypeError: Cannot read property 'hasAttribute' of null
    at HTMLDocument.e (searchtools.min.js?714bd7c681dcb1da83e738c93edacebc:1)
```

<img width="964" alt="screenshot 2018-10-23 at 21 28 11" src="https://user-images.githubusercontent.com/400092/47388630-9852ad00-d70a-11e8-8e52-7a7b70029618.png">
### System information (as much as possible)

Google Chrome 70

**Comment by PhilETaylor** [comment]
ok this is a GENERIC issue 

Go to any list page and search for adlhalksdfhj to generate no matching results - and you can replicate this js error - e.g in the list of articles in com_content

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/22810
