### ISSUE TITLE
[4.0] COM_WORKFLOW_DEFAULT_WORKFLOW not translated on edit page

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22794]
### Steps to reproduce the issue

Joomla 4.0-dev @ 9d3acfd9d589989e86bda3fe35f58a47323d66f4
Login to admin -> content -> workflows
Click Joomla default

### Expected result

not to see untranslated COM_WORKFLOW_DEFAULT_WORKFLOW

### Actual result

`COM_WORKFLOW_DEFAULT_WORKFLOW` in the name field

<img width="712" alt="screenshot 2018-10-23 at 22 13 02" src="https://user-images.githubusercontent.com/400092/47391095-d3f07580-d710-11e8-9eea-02feb7f1e9aa.png">

**Comment by mbabker** [comment]
This is intended and used in a few places to allow you to set a language string as the name (if we showed the translated language string you'd end up saving the translated text).

**Comment by PhilETaylor** [comment]
Then you should not translate it as "Joomla default" on the other page :)

**Comment by PhilETaylor** [comment]
ccccccjffvvgurujekchbhdvrlvrnvcglhrdvvvkvhtu
ccccccjffvvgbigtgnlettkv

**Comment by PhilETaylor** [comment]
ccccccjffvvgurujekchbhdvrlvrnvcglhrdvvvkvhtu
ccccccjffvvgbigtgnlettkv

**Comment by mbabker** [comment]
So for menus and workflows and wherever else we're supporting this behavior we should just show the translation key then?  Because that makes a lot of sense.

**Comment by bembelimen** [comment]
Apply https://github.com/joomla/joomla-cms/pull/22827 and problem is solved :P
