### ISSUE TITLE
[4.0] Inconsistant use of plurals

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22791]
### Steps to reproduce the issue

System menu 

<img width="430" alt="screenshot 2018-10-23 at 22 03 35" src="https://user-images.githubusercontent.com/400092/47390527-8aebf180-d70f-11e8-8023-0d33887c96fd.png">

`Language overrides` -> leads to NO matching results page

whereas the two items with (s) lead to a single entry on a default install

Then you have plural redirects and plugins... when you could have zero of these on a site

It would make more sense to have all plural without any brackets because if you "want to edit a plugin " you would go to a menu item entitled "Plugins" etc... if you "want to edit a language " you would go to a menu item entitled "languages" etc...

Im sure b@rianeeman will disagree but this makes more sense than having four without brackets and two with brackets...

**Comment by rotech1** [comment]
makes sense to me too

**Comment by infograf768** [comment]
Agree. (It is already wrong imho in 3.x for Language(s))

**Comment by chmst** [comment]
Agree, it is only for English as other languages have their own usage of singular/plural. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22791">issues.joomla.org/tracker/joomla-cms/22791</a>.</sub>

**Comment by Quy** [comment]
Please test PR #23515<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22791">issues.joomla.org/tracker/joomla-cms/22791</a>.</sub>
