### ISSUE TITLE
[4.0] Calendar Field Ability to Turn Off Date and Show Time Only

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#22792]
### Is your feature request related to a problem? Please describe.
Not a problem with the current calendar function per se but rather a problem with the application. I am creating a form that needs to input Time only.

### Describe the solution you'd like
If possible, an option to disable the date portion in the calendar and only time is enabled. Something like vanilla javascript like [flatflickr](https://github.com/flatpickr/flatpickr) can do.

**Comment by PhilETaylor** [comment]
and yet others have asked for just the date and no time :) cant win unless we make it configurable :)

**Comment by frogydiak** [comment]
@PhilETaylor isn't it by default, the current calendar field is date only unless you enable the time? :) you get +1 here for configurable calendar field.

**Comment by Quy** [comment]
Duplicate #22140?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22792">issues.joomla.org/tracker/joomla-cms/22792</a>.</sub>

**Comment by ghost** [comment]
closed as duplicate report. Please reopen if its not.
