### ISSUE TITLE
[4.0] Left menu when selecting menus, collapses 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22796]
### Steps to reproduce the issue

Joomla 4.0-dev @ 9d3acfd9d589989e86bda3fe35f58a47323d66f4
Login to admin 

Click Menus

Click Manage - notice left menu stays open with manage selected
Click All menu items - notice left menu stays open with All menu items selected
Click Author menu 

### Expected result

Expect left menu to stay open and Author menu to stay selected

### Actual result

Left menu collapsed

This is a Different ISSUE to #22795 it is NOT a duplicate.

**Comment by hardik-codes** [comment]
@PhilETaylor could you please upload the screenshot of above as in my system Author menu is not showing up

**Comment by PhilETaylor** [comment]
whats the point if the whole admin template is being changed in secret without the ability for us to comment on it...

**Comment by brianteeman** [comment]
You might as well close it @PhilETaylor as you are quite correct there is no point due to the secret cabal

**Comment by infograf768** [comment]
"cabal" or not, the left menu does not collapse for any item anymore until the toggle is used.
