### ISSUE TITLE
[4.0][com_finder] Finder default state screen wrong 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22799]
Joomla 4 com_finder in admin doesnt show "No matching results" like all the other screens defaults do. 

com_finder shows the table headers instead

Compare:

<img width="1416" alt="screenshot 2018-10-23 at 22 31 29" src="https://user-images.githubusercontent.com/400092/47392129-98a37600-d713-11e8-8bdd-ebe521e2f52b.png">
<img width="1412" alt="screenshot 2018-10-23 at 22 31 39" src="https://user-images.githubusercontent.com/400092/47392131-993c0c80-d713-11e8-8d8e-e2a4b23c5d91.png">

**Comment by hardik-codes** [comment]
@PhilETaylor the code works fine in the com_search but somehow it is not working in com_finder. How can I debug the same ?
 ```<?php if (empty($this->items)) : ?>
	<div class="alert alert-warning">
	  <?php echo Text::_('JGLOBAL_NO_MATCHING_RESULTS'); ?>
	</div>```
