### ISSUE TITLE
[4.0] Attempting to delete viewing access level gives double feedback

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22790]
### Steps to reproduce the issue

Login to admin of Joomla 4.0-dev @ 9d3acfd9d589989e86bda3fe35f58a47323d66f4
Users -> Access Levels
Select box next to special 
click delete
click ok 

### Expected result

One error message

### Actual result

Two identical messages

<img width="1229" alt="screenshot 2018-10-23 at 22 01 39" src="https://user-images.githubusercontent.com/400092/47390428-43656580-d70f-11e8-8e65-cdea96950dbd.png">

**Comment by puneeth-chanda** [comment]
can I assign it to myself

**Comment by puneeth2001** [comment]
Can I claim this issue
@

**Comment by PhilETaylor** [comment]
You dont need to assign issues to yourself, just propose a Pull Request and then mention that pull request that you have submitted in the issue, and someone will close the issue in favour of a Pull Request that can be tested.

The Joomla Project doesnt use the Assign feature of Issues.

**Comment by puneeth-chanda** [comment]
ok thanks
:)

**Comment by Quy** [comment]
Please test PR #23724<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22790">issues.joomla.org/tracker/joomla-cms/22790</a>.</sub>
