### ISSUE TITLE
[4.0] Links to tabs in configuration pages dont work

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22793]
### Steps to reproduce the issue

Joommla 4.0-dev @ 9d3acfd9d589989e86bda3fe35f58a47323d66f4
Login to admin -> Settings 

see

<img width="438" alt="screenshot 2018-10-23 at 22 08 24" src="https://user-images.githubusercontent.com/400092/47390865-4876e480-d710-11e8-8366-6abc903bbe6e.png">

### Expected result

Click Settings or text filters - expect to be taken to the right tab in config page

### Actual result

Taken to config page but the tab is not selected

Disappointed as I spent a LOT of time working with tabs in Joomla 3.

**Comment by dgrammatiko** [comment]
This probably comes from this https://github.com/joomla-projects/custom-elements/pull/106

That repo although it has tests the tests don't run as travis is not passing the environment variables for sauce labs anymore...
In sort people need to run the tests locally before committing any code.

**Comment by PhilETaylor** [comment]
@mbabker fix travis ;-) ;-)

**Comment by dgrammatiko** [comment]
Actually @rdeutz needs to provide a drone instance for that repo due to the sauce labs credentials (need to be passed as env variables). Similar to https://github.com/joomla/test-javascript/pull/10

**Comment by dgrammatiko** [comment]
@PhilETaylor actually this is ok as the system settings page uses still the old jQuery Bootcrap code. Once converted to the new joomla-ui the functionality will be restored

**Comment by PhilETaylor** [comment]
>  this is ok

Meaning that its broken, and people should ignore that its broken, not that it "is ok"

**Comment by mbabker** [comment]
> @mbabker fix travis ;-) ;-)

Thank you for your call, your concern is important to me, however I am presently overbooked doing too many jobs, your issue will have to wait for the next free moment for processing 😉

**Comment by dgrammatiko** [comment]
@PhilETaylor here is the default.php with the new tabs: 
```
		<div class="col-md-10">
			<joomla-tab view="tabs" oriendation="horizontal" id="config-document">
				<section id="page-site" name="<?php echo Text::_('JSITE'); ?>">
					<div class="row">
						<div class="col-lg-12 col-xl-6">
							<?php echo $this->loadTemplate('site'); ?>
							<?php echo $this->loadTemplate('metadata'); ?>
						</div>
						<div class="col-lg-12 col-xl-6">
							<?php echo $this->loadTemplate('seo'); ?>
							<?php echo $this->loadTemplate('cookie'); ?>
						</div>
					</div>
				</section>
                <section id="page-system" name="<?php echo Text::_('COM_CONFIG_SYSTEM'); ?>">
					<div class="row">
						<div class="col-md-12">
							<?php echo $this->loadTemplate('system'); ?>
							<?php echo $this->loadTemplate('debug'); ?>
							<?php echo $this->loadTemplate('cache'); ?>
							<?php echo $this->loadTemplate('session'); ?>
						</div>
					</div>
                </section>
				<section id="page-server" name="<?php echo Text::_('COM_CONFIG_SERVER'); ?>">
					<div class="row">
						<div class="col-lg-12 col-xl-6">
							<?php echo $this->loadTemplate('server'); ?>
							<?php echo $this->loadTemplate('locale'); ?>
							<?php echo $this->loadTemplate('ftp'); ?>
							<?php echo $this->loadTemplate('proxy'); ?>
						</div>
						<div class="col-lg-12 col-xl-6">
							<?php echo $this->loadTemplate('database'); ?>
							<?php echo $this->loadTemplate('mail'); ?>
						</div>
					</div>
				</section>
				<section id="page-filters" name="<?php echo Text::_('COM_CONFIG_TEXT_FILTERS'); ?>">
					<div class="row">
						<div class="col-md-12">
							<?php echo $this->loadTemplate('filters'); ?>
						</div>
					</div>
				</section>
				<?php if ($this->ftp) : ?>
					<section id="page-ftp" name="<?php echo Text::_('COM_CONFIG_FTP_SETTINGS'); ?>">
						<div class="col-md-12">
							<?php echo $this->loadTemplate('ftplogin'); ?>
						</div>
					</section>
				<?php endif; ?>
				<section id="page-permissions" name="<?php echo Text::_('COM_CONFIG_PERMISSIONS'); ?>">
					<div class="row">
						<?php echo $this->loadTemplate('permissions'); ?>
					</div>
				</section>
				<input type="hidden" name="task" value="">
				<?php echo HTMLHelper::_('form.token'); ?>
			</joomla-tab>
		</div>
```

Enjoy

**Comment by dgrammatiko** [comment]
> Meaning that its broken, and people should ignore that its broken?, not that it "is ok"

Meaning that someone needs to drop the old script and markup and move that page to the new one. The code is right above.
OK means that is expected that the old tab state script doesn't work anymore, it's deprecated and once all the tabs converted it will be deleted

**Comment by hardik-codes** [comment]
@dgrammatiko could you please specify the path to the above default.php file?

**Comment by dgrammatiko** [comment]
@hardik-codes probably this one: https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_config/tmpl/application/default.php

**Comment by hardik-codes** [comment]
Thanks @dgrammatiko

**Comment by hardik-codes** [comment]
@dgrammatiko when I used the above code in  https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_config/tmpl/application/default.php  on clicking on ```Setting``` or ```Text Filters``` the ```Text Filters``` tab is the one that remains activated regardless of what is clicked.

**Comment by dgrammatiko** [comment]
Clan your browser cache

**Comment by hardik-codes** [comment]
@dgrammatiko I've cleaned browser cache, but what I have noticed is that after clicking on any tab in config page when I go back to admin->System and on clicking ```Settings``` or ```Text Filters```  the tab which I had previously clicked is the one that remains activated, regardless of what is being clicked on.

**Comment by dgrammatiko** [comment]
@hardik-codes are you actually loading the tabs custom element? Did you remove the old scripts from the page?
The code above is just the html changes, there are also the scripts that need to be loaded there

**Comment by hardik-codes** [comment]
@dgrammatiko could you please help me remove those.

**Comment by dgrammatiko** [comment]
@hardik-codes there you go: https://github.com/joomla/joomla-cms/pull/23780
