### ISSUE TITLE
[4.0][com_media] Can delete whole images folder by mistake with no confirmation

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22805]
### Steps to reproduce the issue

I KNOW that I reported this before and that it was fixed by adding a warning before, but right now in joomla 4 media manager you can select all, and click delete, and you have now deleted everything - no warning at all. 

### Expected result

an "are you sure" ?

### Actual result

Gone! all of it! all the images in the folder 

and a js error

```
Notifications.js:26 Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes
    at t.value (http://127.0.0.1/media/com_media/js/mediamanager.min.js:6:44919)
    at t.value (http://127.0.0.1/media/com_media/js/mediamanager.min.js:6:44664)
    at onSuccess (http://127.0.0.1/media/com_media/js/mediamanager.min.js:6:38704)
    at XMLHttpRequest.o.onreadystatechange (http://127.0.0.1/media/system/js/core.min.js?714bd7c681dcb1da83e738c93edacebc:1:8195)
```

**Comment by puneeth-chanda** [comment]
@PhilETaylor can I know why is this issue closed

**Comment by HLeithner** [comment]
All issues and PRs from Phil are still valid but he stepped from Joomla 11 days ago.

Hopefully he comes back one day.

**Comment by puneeth-chanda** [comment]
Can I work on this right now?

**Comment by HLeithner** [comment]
sure

**Comment by infograf768** [comment]
we have already a pr for that<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22805">issues.joomla.org/tracker/joomla-cms/22805</a>.</sub>

**Comment by infograf768** [comment]
see #23756

**Comment by PhilETaylor** [comment]
> Hopefully he comes back one day.

Doubt it. The abuse continues.
