### ISSUE TITLE
New menu item, modal window class not being removed

### ISSUE THREAD

**Issue by RustyIngles** [joomla/joomla-cms#22814]
### Steps to reproduce the issue

In Joomla 3.8.13, go and create a New Menu Item. (The menu type doesn't matter, but we will be using a Category List to reproduce this issue). From the menu item type, select Articles -> Category List. From the 'Choose a Category' option, click 'Select' - if you now inspect the HTML, you will notice that there are two divs created:

```
<div class="modal-backdrop fade in"></div>
<div class="modal-backdrop fade in"></div>

```
When selecting the required 'Category' for the Category List, the CMS closed one of the above divs but the other is left open.

I have tested this in Chrome 69, Chrome 70, Firefox 62 and the above bug is always present.

If you don't select a Category, but click the X, this removes both of the divs.

### Expected result

There shouldn't be two divs created when clicking on the Select Category

### Actual result

Two divs created:

```
<div class="modal-backdrop fade in"></div>
<div class="modal-backdrop fade in"></div>

```

**Comment by brianteeman** [comment]
edited post so the code could be seen

**Comment by Webdongle** [comment]
Unable to reproduce.
Are you using a fresh Joomla with Protostar as default frontend Template?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22814">issues.joomla.org/tracker/joomla-cms/22814</a>.</sub>

**Comment by RustyIngles** [comment]
Yes, this is using standard Protostar. Even on fresh installs it's the same. Using Chrome 69/70 and Firefox it's the same.

**Comment by Quy** [comment]
Unable to reproduce as seen with the HTML inspector on Firefox 63.0 Windows and Chrome Version 70.0.3538.77 (Official Build) (64-bit).

![modal-backdrop](https://user-images.githubusercontent.com/368084/47625265-4ed6d900-dae1-11e8-86c5-71f8ab417bca.jpg)

**Comment by Quy** [comment]
Not reproducible in v3.9. Closing for now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22814">issues.joomla.org/tracker/joomla-cms/22814</a>.</sub>
