### ISSUE TITLE
[4.0] Fix Image API use

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#22817]
In 3.x we made the `Joomla\CMS\Image` classes extend  the `Joomla\Image` classes from the Framework and deprecated the CMS classes.  After this happened, we decided to deprecate the Framework package.  So, the CMS needs to break this class inheritance (which is technically a B/C break) and basically inline all the code back into the CMS namespace.

**Comment by mbabker** [comment]
Hmm, not the template or the test architecture.  Odds are nobody's touching it.

**Comment by SharkyKZ** [comment]
This needs to be done one way or another. I could give it a try but I have no idea how to map Framework versions to CMS versions.

**Comment by mbabker** [comment]
Framework 1.x is used in CMS 3.x

Framework 2.x is used in CMS 4.x

For all intents and purposes, you just need to copy the code from the `Joomla\Image` classes back into `Joomla\CMS\Image` classes and undo the deprecations of the CMS' classes and not have them extend the Framework classes.  Then `joomla/image` can be removed from the Composer manifest.

**Comment by SharkyKZ** [comment]
What about doc blocks? For example, `Joomla\Image\Image::$generateBestQuality` has `@since  1.4.0` while `Joomla\CMS\Image\Image::$generateBestQuality` has `@since  3.7.0`. I suppose we should use CMS versions. But what about versions for methods and properties not documented in CMS, e.g. `Joomla\Image\Image::watermark()` with 1.3.0 version?

**Comment by mbabker** [comment]
The version it was introduced into the CMS API is what the doc block should be.

**Comment by SharkyKZ** [comment]
See PR #25763 please.

**Comment by ghost** [comment]
Closed as having Pull Request #25763
