### ISSUE TITLE
[3.9.0-rc2] Database not up to date

### ISSUE THREAD

**Issue by ssnobben** [joomla/joomla-cms#22821]
### Steps to reproduce the issue

Create a new site on launch.joomla.com get problem here https://forum.joomla.org/viewtopic.php?f=805&t=966623. 

Cloudaccess fix it after some support. Dont know if there is something just personally for me on this hosting bcs I had a test site there before if so close this one.

After login going to database see this error     

3 Database Problems Found.

    Other Information

    - Database schema version (None) does not match CMS version (3.9.0-2018-10-21).
    - Database update version (None) does not match CMS version (3.9.0-rc2-dev).
    - The Joomla! Core database tables have not been converted yet to UTF-8 Multibyte (utf8mb4).

    Database schema version (in #__schemas): 3.9.0-2018-10-21.
    Update version (in #__extensions): 3.9.0-rc2-dev.
    Database driver: mysqli.
    166 database changes were checked.
    206 database changes did not alter table structure and were skipped.

Warning

Warning: Database is not up to date!

Table 'xwi_ucm_content' has the wrong type or attributes for column 'core_title' with type varchar(400). (From file 3.7.0-2017-01-08.sql.)

### System information (as much as possible)
3.9.0-rc2-dev

### Additional comments
Clicking on the Fix db things works out..

**Comment by ReLater** [comment]
Always use installation and update packages of this site for testing:
https://developer.joomla.org/nightly-builds.html

**Comment by Quy** [comment]
Please test with the nightly build and if still an issue, this can be reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22821">issues.joomla.org/tracker/joomla-cms/22821</a>.</sub>
