### ISSUE TITLE
[4.0] Media manager broken

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#22829]
### Steps to reproduce the issue
Install a clean 4.0 dev. ( npm install done)

Go to media manager
index.php?option=com_media

### Expected result
Manager should display.
Same when using the Image xtd.

### Actual result
<img width="1226" alt="screen shot 2018-10-27 at 07 23 49" src="https://user-images.githubusercontent.com/869724/47599950-4aaf9c00-d9b9-11e8-876f-d26b3972c97b.png">

`ReferenceError: MediaManager is not defined`

### System information (as much as possible)
```
// Add javascripts
HTMLHelper::_('script', 'media/com_media/js/mediamanager.js');

// Add stylesheets
HTMLHelper::_('stylesheet', 'media/com_media/css/mediamanager.css');
```
should load these files. But they do not exist, even after a npm install.

**Comment by Fedik** [comment]
hm, I just tried with latest version of 4.0-dev, and all works fine for me 
same for #22830

**Comment by infograf768** [comment]
Have you tried with nightly build or a 4.0 checkout?

**Comment by brianteeman** [comment]
Make sure there were no errors with the npm install. Sounds like the same problem described with the nightly yesterday.

**Comment by Fedik** [comment]
I have tried with latest 4.0-dev branch

**Comment by infograf768** [comment]
Here I have errors for com_media
```
> node-sass@4.9.3 install /Applications/MAMP/htdocs/testnew/joomla40/administrator/components/com_media/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/mac/.npm/node-sass/4.9.3/darwin-x64-57_binding.node

> node-sass@4.9.3 postinstall /Applications/MAMP/htdocs/testnew/joomla40/administrator/components/com_media/node_modules/node-sass
> node scripts/build.js

Binary found at /Applications/MAMP/htdocs/testnew/joomla40/administrator/components/com_media/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Testing binary
Binary is fine
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@5.0.1 requires a peer of webpack@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN com_media@4.0.0 No repository field.

removed 23 packages, updated 18 packages and audited 8538 packages in 4.884s
found 0 vulnerabilities


> com_media@4.0.0 build /Applications/MAMP/htdocs/testnew/joomla40/administrator/components/com_media
> cross-env NODE_ENV=production webpack --progress --hide-modules

sh: /Applications/MAMP/htdocs/testnew/joomla40/administrator/components/com_media/node_modules/.bin/cross-env: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! com_media@4.0.0 build: `cross-env NODE_ENV=production webpack --progress --hide-modules`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the com_media@4.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

CSS for cassiopea is definitely broken: see nightly build where they are not present either.

**Comment by Fedik** [comment]
hm, maybe try remove (or rename) manually:
/administrator/components/com_media/node_modules
and
/node_modules

and run "npm install" again , they will be recreated

**Comment by infograf768** [comment]
removing node_modules for com_media solved it for com_media. It is frustrating as it was a clean install. I should not have to delete the node_modules folder.

It does not solve cassiopea absent css
See https://github.com/joomla/joomla-cms/issues/22824

Closing this PR and leaving the one for Cassiopea.
