### ISSUE TITLE
[4.0] Basic Cassiopeia CSS files disappeared from css folder in Nightly Builds

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#22824]
Can someone care to explain why template.css, template.min.css, etc.. (except offline and offline.min.css) are not included in latest versions of Nightly Builds (Friday, 26 October 2018) in the /css/ folder of Cassiopeia ?

Are not Nightly Builds packages supposed to work out of the box, and without the need of SASS/scss compiling ?

Or else ?

**Comment by manojLondhe** [comment]
I noticed the same today.

**Comment by mbabker** [comment]
Probably something to do with this bit of output from running the build commands:

```sh
something exploded 19
something exploded Undefined variable: "$atum-box-shadow".
something exploded 81
something exploded 19
something exploded Undefined variable: "$atum-box-shadow".
something exploded 81
```

Meaning there's an error in compiling some file (probably the Cassiopeia CSS).  Relax, it's a SCSS bug, not someone trying to ship incomplete packages.

**Comment by ghazal** [comment]
OK. Thank you.
Un-stressed now ~_^.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/22831
