### ISSUE TITLE
Words in  titles are not indexed by Smart Search

### ISSUE THREAD

**Issue by saraheagle** [joomla/joomla-cms#22828]
### Steps to reproduce the issue
In an article, create a page break like this
```html
<hr class="system-pagebreak" title="Nutrition as you grow older" />
```

Add some other text, do not include the word "nutrition" anywhere else.

### Expected result
After the content has been indexed, and "nutrition" searched for the page should show in the search results

### Actual result
This page does not show in the search results unless the word "nutrition" is included somewhere in "ordinary" text.

### System information (as much as possible) 
PHP Built On	Linux uk15.siteground.eu 3.12.18-clouder0 #20 SMP Mon Feb 26 12:15:53 EET 2018 x86_64
Database Type	mysql
Database Version	5.6.40-84.0-log
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.38
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.8.13 Stable [ Amani ] 9-October-2018 14:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

### Additional comments
I'm not sure if this is possible to achieve, my clients are very surprised it does not work as from a users point of view, when you look at your site on the front-end, it's clearly there in the text! (They are not overly happy about the thought of going through their content and checking that such "keywords" are in ordinary text, but they'll just have to do that for now) Thanks

**Comment by mbabker** [comment]
Text that is contained within HTML attributes (such as this title) isn't included in the indexed content.  The pagebreak plugin would need to be updated to basically render out these `<hr>` tags in the way they would for a regular page request in order for the titles to become visible content for the indexer.

**Comment by Quy** [comment]
Is this an expected behavior and won't fix? Even the `title` attribute of an `img` tag in contents is not indexed.

**Comment by SharkyKZ** [comment]
Attributes could be indexed. But what should and shouldn't be indexed is a matter of discussion.

**Comment by alikon** [comment]
imo matter for 4.x.....closing
