### ISSUE TITLE
Joomla 3.9 Version history link broken

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22820]
### Steps to reproduce the issue

in https://github.com/joomla/joomla-cms/blob/staging/README.md the link to 

`Joomla! 3.9 version history.`

leads to a 404 error page

Not sure if the solution is to fix the link or to create the wiki page...

**Comment by Sandra97** [comment]
I'll create the page on the release day, so it's expected and the link is correct
