### ISSUE TITLE
Labels not found - [#20243] - [FEATURE] J 3.9 - A Repeatable Custom Field

### ISSUE THREAD

**Issue by fabricioventura** [joomla/joomla-cms#22826]
J3.9 - [FEATURE] A Repeatable Custom Field

Hello @roland-d  , congratulations on the addition and the idea.

I noticed that it does not have a label in the repeatable items, which makes the view very complicated, would not it be interesting to add the possibility of inserting a label in the record of the repeating fields ones in the article?

More issues:
-The link field type should be present,  it's so important :(
-The extra fields type media, did not appear the picture on the frontend!

See image:
https://drive.google.com/file/d/1ZC6gQyeS2Vb8sBOktwx50-6uPYqmxNsz/view?usp=sharing 

Thank you!

**Comment by AndySDH** [comment]
This can be closed as it's going to be fixed on new Subform field implementation:
#22446
