### ISSUE TITLE
[4.0] Installing the sample data

### ISSUE THREAD

**Issue by Chacapamac** [joomla/joomla-cms#22837]
### Steps to reproduce the issue
Normal installation process
— After you select a language and press “Next” you can see, in the background, the “Install Sample Data” Step with the Joomla logo working animation. All that disappear and you are going back to the “Congratulation” Step.

### Expected result

I guess, you should have access to the “Install Sample Data” Step 

### Actual result

Bypass

### System information (as much as possible)

Local Mamp - PHP 7.2.1 — Firefox Dev & Safari — El Capita

### Additional comments
https://ibb.co/bCNeTA

**Comment by Chacapamac** [comment]
Screenshot 
![screen shot 2018-10-27 at 14 42 47](https://issues.joomla.org/uploads/1/cdacbcb1c0ffd1c2f3ae376ea025886d.jpg)
Sorry, first time posting an image here — What is the best way<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22837">issues.joomla.org/tracker/joomla-cms/22837</a>.</sub>

**Comment by chmst** [comment]
For adding an image, store the screenshot as .png or .jpg file and drag it on the edit form. 


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22837">issues.joomla.org/tracker/joomla-cms/22837</a>.</sub>

**Comment by Quy** [comment]
Click `Customize Installation` again, click `Skip` to get to the `Install Sample Data` screen.

**Comment by Chacapamac** [comment]
Do not close this I will come back on it.

**Comment by ReLater** [comment]
As far as I know sample data installation will be removed from Joomla installation steps:
https://github.com/joomla/joomla-cms/issues/20262
I haven't heard anything to the contrary since I've posted 20262...
(... but would be happy to hear ... ;-) )

**Comment by Chacapamac** [comment]
That part of the installation was not straightforward and even confusing, I will have ask for change.

I didn’t like to bring the sample data, at least for the blog in the main installation interface. I did like the ability to install a other language for administrative process or installing Joomla complete multi language at this point.

You can close this
