### ISSUE TITLE
[4.0] Cassiopeia css missing after npm install

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#22830]
### Steps to reproduce the issue
Install a clean 4.0-dev.
Add some content.
Display frontend.

### Actual result
Cassiopeia should have css, but none has been created.
The page is not formatted.
Its css folder only contains the offline.css

**Comment by ReLater** [comment]
Related: https://github.com/joomla/joomla-cms/issues/22824

**Comment by Fedik** [comment]
what happens if you run?
`node build.js --compile-css templates/cassiopeia/scss/template.scss`

**Comment by Fedik** [comment]
okay, I can reproduce it also :smile: 

to reproduce:
remove /css from template then run:
node build.js --compile-css

in result only offline.css file created

**Comment by infograf768** [comment]
The problem comes from
https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/cassiopeia/scss/vendor/_chosen.scss#L81

**Comment by Fedik** [comment]
yeap, just wanted to post the same :smile:

**Comment by infograf768** [comment]
@wilsonge 
I guess you committed that one.

**Comment by infograf768** [comment]
I can solve it by modifying to
`box-shadow: $cassiopeia-box-shadow;`

**Comment by infograf768** [comment]
will make PR

**Comment by wilsonge** [comment]
Sorry! Your fix sounds good

**Comment by infograf768** [comment]
closing for https://github.com/joomla/joomla-cms/pull/22831
