### ISSUE TITLE
Frontend CSS not working

### ISSUE THREAD

**Issue by Chacapamac** [joomla/joomla-cms#22838]
### Steps to reproduce the issue
Finish normal installation

### Expected result
Cassiopeia front end

### Actual result
Missing CSS

### System information (as much as possible)
Mamp, PHP 7.2.1, Firefox Dev, El Capitan

### Additional comments
![screen shot 2018-10-27 at 14 54 06](https://issues.joomla.org/uploads/1/b580089f4f6fb1ef83ba4aa54ede712d.jpg)

**Comment by Quy** [comment]
Reported and fixed #22831<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22838">issues.joomla.org/tracker/joomla-cms/22838</a>.</sub>
