### ISSUE TITLE
[4.0] Unable to navigate through pagination

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#22841]
### Steps to reproduce the issue
Create a category blog with enough articles to display pagination. Try navigating to the second page of results.

### Expected result
Navigates to second page

### Actual result
Nothing

```
TypeError: document.adminForm is undefined[Learn More] 2 category-blog:1:1
	onclick http://localhost/joomla-4-dev/index.php/category-blog#:1:1

```

**Comment by Quy** [comment]
Duplicate #21767?
