### ISSUE TITLE
Launch J! v.4.0.0-alpha becomes J! 3.9.0-rc3-dev

### ISSUE THREAD

**Issue by AlainRnet** [joomla/joomla-cms#22855]
### Steps to reproduce the issue
I wanted to test J!4 with Launch, so I select "Joomla! 4.0.0-alpha5-dev" in "Advanced settings" but as you can see on http://artisanduweb.joomla.com/ it's J!3 :-(

![screen shot 2018-10-29 at 16 39 33](https://issues.joomla.org/uploads/1/36f48aa7c78f3dafc4eeba39b2cc98a6.png)

**Comment by Quy** [comment]
@Sandra97 @franz-wohlkoenig Where do you report this to CloudAccess?

**Comment by Sandra97** [comment]
It would be better to close this issue and open one in the right repository: https://github.com/joomla/joomla-websites/issues
Then I can assign it to Jonathan

**Comment by ghost** [comment]
https://github.com/joomla/joomla-websites/issues/new?title=%5Bjlaunch%5D%20

**Comment by Quy** [comment]
@AlainRnet Please report if still an issue @ https://github.com/joomla/joomla-websites/issues<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22855">issues.joomla.org/tracker/joomla-cms/22855</a>.</sub>

**Comment by AlainRnet** [comment]
I did it (https://github.com/joomla/joomla-websites/issues/1244), many thanks.
Solution : there is an inversion in dropdown between J!3.9.0 and J!4.0.0.
