### ISSUE TITLE
Infinite loop with RSS feed

### ISSUE THREAD

**Issue by fredo-m** [joomla/joomla-cms#22854]
Hi,

This is a small bug that deserves protection against awkwardness.

In the module "Feed Display", if in the field "Feed URL" you put the address of the site, you generate a loop that consumes all possible access to the web server. On a web server you use all processes up to the maximum limit, a small DOS.

Tested with Joomla 3.8.1.

Regards.

**Comment by brianteeman** [comment]
Do you mean you put your own url in the module?

If so its hardly a DOS as you did it yourself

**Comment by fredo-m** [comment]
Hi,

Yes, we have a client on a shared server that wanted to test the module. Not knowing what to put as URL, she put that of her website. She made inaccessible all the websites of this shared server .

Regards.

**Comment by brianteeman** [comment]
So this shared server doesn't run each site in isolation?

**Comment by fredo-m** [comment]
With the Apache prefork MPM module, the "MaxRequestWorkers" directive is global, it can not be configured vhost by vhost.

Regards.

**Comment by Quy** [comment]
Isn't this a hosting/user issue than a core issue?

**Comment by alikon** [comment]
hosting issue for me

**Comment by brianteeman** [comment]
The only thing we could do is to prevent someone putting in a link to their own site.

**Comment by Quy** [comment]
You should be able to post your own site. I tested locally without issues.

**Comment by alikon** [comment]
not a core issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22854">issues.joomla.org/tracker/joomla-cms/22854</a>.</sub>
