### ISSUE TITLE
[4.0] Broken menu presets

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#22853]
### Steps to reproduce the issue
Apply #22852
Create a modern menu preset (administrator => new menu)
Create a second menu preset (with a stating letter larger than the first one)

### Expected result
both presets are created

### Actual result
Error for double alias clash

### Additional comments
I think the error is here: https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_menus/presets/modern.xml#L145-L193

The SQL, creating the title do not use the current (new) menu

**Comment by Quy** [comment]
See PR #22852<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22853">issues.joomla.org/tracker/joomla-cms/22853</a>.</sub>

**Comment by bembelimen** [comment]
@Quy
Please reopen, this is another issue, which is a follow up of the PR you mentioned.

The presets are on more than one level broken, we have to fix step by step

**Comment by bembelimen** [comment]
Fixed here #22852
