### ISSUE TITLE
Joomla cache prevent ratings votes from being seen

### ISSUE THREAD

**Issue by Spudley** [joomla/joomla-cms#22858]
### Steps to reproduce the issue

* Turn on caching on a Joomla site.
* Turn on the content ratings feature.
* Now go try to give vote ratings for some of your content. Especially ones that have not previously been rated.

### Expected result

When I give a rating for a piece of content, I expect the page to reload and to show me a star rating for that article which takes into account the score I gave it.

### Actual result

What actually happens is that the cached version of the page is served, and so I just see the same score as before. If it wasn't rated before, this means that I still see "No ratings yet" even though I also have a message on the page saying thank you for rating this article.

### System information (as much as possible)

Tested with an up-to-date Joomla version (3.8.13).

### Additional comments

The fix would seem to be to add some code to the ratings feature to make it flush the cache for the current article when a rating is saved.

**Comment by ghost** [comment]
does this Issue exist on latest Version?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22858">issues.joomla.org/tracker/joomla-cms/22858</a>.</sub>

**Comment by Spudley** [comment]
Hi Franz. I've just re-tested it on the latest version (3.9.3) and yes, the problem remains the same.

**Comment by ghost** [comment]
@Spudley thanks for test again > @HLeithner can you please comment?

**Comment by HLeithner** [comment]
I don't see a clear function in our cache layer... maybe @mbabker can help?

**Comment by mbabker** [comment]
There is a partially implemented `Joomla\CMS\Cache\CacheStorage::flush()` method, that should probably be exposed through `Joomla\CMS\Cache\Cache` too.

But that's overkill for this.  A vote operation needs to clean the `com_content` cache group and the cache for relevant modules.  Essentially, the frontend article model needs to have the `storeVote` method call `$this->cleanCache()` and the extended `cleanCache()` method from the admin article model copied to the frontend class to ensure all appropriate groups are cleaned.

**Comment by brianteeman** [comment]
There might be some help looking in the hits code. as I remember @rdeutz did some work on it that sounds like it was tackling the same root issue

**Comment by SharkyKZ** [comment]
Test PR #25201 please.

**Comment by ghost** [comment]
Closed as having Pull Request #25201
