### ISSUE TITLE
Inconsitent creation of items: admin menu

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#22866]
### What needs to be fixed
If you select the contect administrator for creating a new menu, administrator is not preselect
<img width="670" alt="grafik" src="https://user-images.githubusercontent.com/43232309/47722780-75b51c80-dc53-11e8-96f8-05a8c4dd5c10.png">
<img width="567" alt="grafik" src="https://user-images.githubusercontent.com/43232309/47722802-7d74c100-dc53-11e8-8a30-fa404d08c526.png">

### Why this should be fixed
Because in other areas in joomla you select context and then this context is defined.
(fields, items, articles, modules)

### How would you fix it
have administrator selected when context administrator is selected

### Side Effects expected
better UX

**Comment by brianteeman** [comment]
Closed see #22903
