### ISSUE TITLE
Update 3.8.13> 3.9 does not work

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#22875]
Hello, I just made the update, but there are no changes. I used different browsers, and emptied the caches. The site is good Joomla! 3.9 but no new functions?

**Comment by Quy** [comment]
Please post your issue to the Joomla Forum https://forum.joomla.org/viewforum.php?f=710<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22875">issues.joomla.org/tracker/joomla-cms/22875</a>.</sub>
