### ISSUE TITLE
com_installer - Feature to separate core files from third-party files

### ISSUE THREAD

**Issue by motwguy** [joomla/joomla-cms#22871]
### Steps to reproduce the issue
In working on older sites, I often find a large number of plugins that are old and no longer supported. These are potential security risks that should be removed. It would be beneficial if there were an easy way to isolate core files from third-party files (hide Joomla core?) in the admin management display. 

### Expected result
See only non-essential files.

### Actual result
All files are displayed together.

**Comment by PhilETaylor** [comment]
Joomla doesn't list site files in the admin console at all (apart from media/templates)? 

Is this really just a duplicate of #22872

**Comment by brianteeman** [comment]
Extensions > Manage > Manage

filter by ID descending

if it has an ID > 1000 it is an addon

(In Joomla 4 there is a filter for this)

**Comment by richard67** [comment]
@brianteeman ID > 1000 is not reliable on installations which have gone through a long history of updates since new core extensions had been added without fixed ID in the update SQL so for those the auto-increment value > 1000 had been used.

**Comment by brianteeman** [comment]
This should be closed. Its possible in J4 and at this time no new features are being accepted for J3
