### ISSUE TITLE
[3.9.0] Parse error in PHP versions

### ISSUE THREAD

**Issue by Chaosxmk** [joomla/joomla-cms#22876]
### Steps to reproduce the issue
Update Joomla to 3.9 or install 3.9
Go to /administrator/index.php, pass login if not logged in

### Expected result
Page displays correctly without errors

### Actual result
Page crashes with:
`Parse error: syntax error, unexpected T_OBJECT_OPERATOR in /libraries/cms/html/content.php on line 74`

### System information (as much as possible)
Bug was fixed as soon as PHP version was set to 5.6, so this is likely affecting older PHP versions.

### Additional comments
Not sure bug is worth fixing if future versions of Joomla won't work outside of at least 5.6.

**Comment by mbabker** [comment]
It's a PHP 5.3 compat issue.  That line will work fine on 5.4.

**Comment by Chaosxmk** [comment]
I figured I'd raise a bug anyways because Joomla.org still states that minimum version is 5.3.10, and that version doesn't work with Joomla 3.9

**Comment by mbabker** [comment]
It's a bug.  Just saying it's not affecting 5.4 or 5.5.

**Comment by Chaosxmk** [comment]
Right, changed title to reflect that.

**Comment by SharkyKZ** [comment]
Test PR #22877 please.
