### ISSUE TITLE
Update 3.10 > 3.2.7

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#22881]
### Steps to reproduce the issue
Installed a new 3.10-dev.-Site. In Backend got Information that should Update on new Version "3.2.7".
![bildschirmfoto 2018-10-31 um 07 08 27](https://user-images.githubusercontent.com/8235763/47769339-ddaf4580-dcdb-11e8-9b84-9979716ddaa4.png)

### Expected result
No Information about an old Version.
### System information
- 3.10
- Template: Protostar
- macOS Sierra, 10.13.6
- Firefox 63 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve
### Additional comments
Looks like 3.2 ist higher than 3.10.

**Comment by infograf768** [comment]
I can't reproduce here.
![screen shot 2018-10-31 at 12 30 12](https://user-images.githubusercontent.com/869724/47785348-c044a080-dd08-11e8-9c52-bbb2918b9557.png)

**Comment by ghost** [comment]
Maybe a CloudAccess-Issue, closed here, reported at https://github.com/joomla/joomla-websites/issues/1246
