### ISSUE TITLE
Remove required field option on config_domain.xml

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#22880]
### Steps to reproduce the issue

3.8.x Set the recaptcha option to v2.

Update to 3.9.0.
Set new invisible plugin settings
go to backend - users - option - try to switch captcha option

### Expected result

option saved

### Actual result

Error.

When you go to the domain tab, you will see a red input field.

![image](https://user-images.githubusercontent.com/876623/47761516-f22e1680-dcb8-11e8-8c0c-11d79701ebff.png)
### Additional comments
https://github.com/joomla/joomla-cms/pull/20383#issuecomment-434539038

**Comment by SharkyKZ** [comment]
Probably to do with #17552. IE doesn't support `<template>` element.

**Comment by Quy** [comment]
@continga

**Comment by Fedik** [comment]
-IE doesn't support <template> element

Support, if you add `display: none` :smile:

**Comment by Quy** [comment]
Please test PR #24832

**Comment by ghost** [comment]
Closed as having Pull Request #24832
