### ISSUE TITLE
Language overrides Filter Field is Missing

### ISSUE THREAD

**Issue by AlexanderSk** [joomla/joomla-cms#22885]
### Steps to reproduce the issue
Go to Admin backend -> Extentions -> Languages -> Overides (administrator/index.php?option=com_languages&view=overrides) on 3.9.0

### Expected result
![screen shot 2018-10-31 at 10 36 46](https://issues.joomla.org/uploads/1/996290ff582c02c9e277b9a718c48fcf.png)

### Actual result
![screen shot 2018-10-31 at 10 37 13](https://issues.joomla.org/uploads/1/9600cf0673aa78a01567800b59be1321.png)

### System information (as much as possible)
Updated from 3.8.13
PHP Version	7.2.9
Database Version	5.5.60-MariaDB
Web Server	Apache__server
WebServer to PHP Interface	fpm-fcgi
Joomla! Version	Joomla! 3.9.0 Stable [ Amani ] 30-October-2018 14:00 GMT

**Comment by infograf768** [comment]
@AlexanderSk 
See https://github.com/joomla/joomla-cms/pull/22264

This means that your update did not go well as the `com_languages/joomla/searchtools/default/bar.php` file was deleted although script.php was modified to not delete it.
Try to re-update 3.9.0 with the joomlaupdate component

**Comment by brianteeman** [comment]
Have you resolved this?

**Comment by AlexanderSk** [comment]
Hi, as you mention it i never faced this issue another day... perhaps it was the browser cache... Language selection is now not on bottom left but on same row of course... Please close this :)

![2018_11_06_13_48_32_languages_overrides_ink_toner gr_administration](https://user-images.githubusercontent.com/2542688/48062429-b28c9080-e1ca-11e8-994a-1ed2c8fdf707.png)

**Comment by brianteeman** [comment]
Closed as requested

**Comment by dDraxb** [comment]
If there is a default.php file (due to a faulty update or something) left in the searchtools folder the language dropdown will also not show up. 

![Schermafbeelding 2019-11-01 om 12 14 45](https://user-images.githubusercontent.com/57256108/68021303-5ce5a980-fca1-11e9-8d53-9bcc171e4c0f.png)
