### ISSUE TITLE
Guest Status Categories Filter in Article Manager not displaying.

### ISSUE THREAD

**Issue by jed-keenan** [joomla/joomla-cms#22884]
### Steps to reproduce the issue
Set the status of an article category to Guest, add a Guest status article to the category, use the Search Tool in Article Manager to filter for the category in Select Category.
### Expected result
The Guest status article category to show in the results.
### Actual result
The Guest status article does not show.
### System information (as much as possible)
CMS is up to date.
### Additional comments
Changing status to Public etc. works correctly.

**Comment by infograf768** [comment]
I confirm the issue.
A Super User has to add `Guest` to its Assigned user groups to be able to filter by such a category.

<img width="407" alt="screen shot 2018-10-31 at 12 35 08" src="https://user-images.githubusercontent.com/869724/47785644-9dff5280-dd09-11e8-9879-656d63561627.png">

**Comment by ghost** [comment]
Closed as having Pull Request.
