### ISSUE TITLE
Repeatable fields media shows only path, no image

### ISSUE THREAD

**Issue by Romkev** [joomla/joomla-cms#22899]
### Steps to reproduce the issue
New field, type repeatble, sort media
In article, fields, browse to a image and select it

### Expected result
In frontend you should see the selected image/picture
testpage to be seen: https://dewerelddichterbij.nl/test

### Actual result
You see only path to the image for exemple: images/landen/picture1.jpg
(

### System information (as much as possible)
PHP 7.1.17
J 3.9

### Additional comments
At media (output) is missing [ <src=" ] and the closing ["/>]

**Comment by AndySDH** [comment]
This can be closed as it's going to be fixed on new Subform field implementation:
https://github.com/joomla/joomla-cms/pull/22446
