### ISSUE TITLE
Error messages and block with Invisible Recaptcha

### ISSUE THREAD

**Issue by sseguin613** [joomla/joomla-cms#22892]
### Steps to reproduce the issue
1. Register Google Invisible Recaptcha to obtain site and secret keys.
2. Enter keys in the Invisible Recaptcha plugin and enable.
3. Set Global Configuration recaptcha to Invisible Recaptcha.
4. Set User manager recaptcha to Invisible Recaptcha.
5. Visit front end login screen and use either Forgot password or Forgot username.
6. Enter email address.  (note that the Recaptcha logo appears at the bottom right corner of the browser window).
7. Click Submit.

### Expected result
No error messages and the password or username recovery is successful.

### Actual result
The password or username recovery on front end is not successful, and the following error messages display.
×
Error
invalid-input-secret

×
Notice
Reset password failed: Invalid field: Captcha

### System information (as much as possible)
Joomla 3.9

Database Version | 5.6.41-84.1
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.2.9-1+0~20180910100423.5+jessie~1.gbpdaac35
Web Server | Apache/2.4.10 (Debian)
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 3.9.0 Stable [ Amani ] 30-October-2018 14:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0

### Additional comments
Regular Recaptcha works fine but Invisible Recaptcha does not work in the new Joomla 3.9
I enabled System Debug but there was no errors or anything there to report that was related to this issue.

**Comment by Ruud68** [comment]
Hi, just tried this but cannot reproduce: works for me :(<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22892">issues.joomla.org/tracker/joomla-cms/22892</a>.</sub>

**Comment by zero-24** [comment]
> invalid-input-secret

Can you please double check the secret and site key?

**Comment by sseguin613** [comment]
I have. I even tried creating a second key on the google site and no change. The invisible keys work on other web applications I have but not on the Joomla site. The domains are also set correctly for the recaptcha key's settings.

**Comment by zero-24** [comment]
hmm something seams to be wrong with the secret key anyway. As per ReCaptcha API Doku the error code `invalid-input-secret` comes with the reason `The secret parameter is invalid or malformed.` https://developers.google.com/recaptcha/docs/verify

**Comment by Ruud68** [comment]
just asking the obvious: are you sure the whole key is copied (sometimes when you have eg a - in the key the double click doesn't select the whole key.
Does the copied key not have space / tab in front or back? happened to me when selecting the key via dragging the mouse over it.

**Comment by sseguin613** [comment]
I was able to get it working. 

There was an issue with the keys being generated with the Google Recaptcha site. It's working properly now and thus, the Invisible Recaptcha is as well.

Thank you. This can be closed now.

**Comment by alexdwalker** [comment]
I too get this issue with the invisible captcha. I also tried Captcha 2 and got the error: Reset password failed: Invalid field: Captcha <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22892">issues.joomla.org/tracker/joomla-cms/22892</a>.</sub>
