### ISSUE TITLE
[3.9] Content - Contact plugin update causes empty contact_link

### ISSUE THREAD

**Issue by danielmorell** [joomla/joomla-cms#22896]
### Steps to reproduce the issue

- Install Joomla 3.9
- Create Contact and assign Linked User
- Create Article created by user linked to contact
- Set content component Show Author and Link Author to Yes, and set menu/article settings to use global

### Expected result

Author displayed in the article info with a link to contact that was created.

### Actual result

The author is displayed but there is no link to the contact.

`$displayData['item']->contact_link` in layouts\joomla\content\info_block\author.php returns an empty result.

### System information (as much as possible)

Joomla 3.9.0
PHP 7.2

### Additional comments

#18258

The **Content - Contact** plugin needs to be opened and saved for the default plugin settings to take effect. Once this is done the expected result is achieved.

This behavior is consistent on new installations as well as updates to existing sites.

**Comment by ReLater** [comment]
Please test https://github.com/joomla/joomla-cms/pull/22904

**Comment by danielmorell** [comment]
@ReLater I tested #22904. It corrected the issue.

Nice work.

**Comment by Quy** [comment]
@danmorell please submit your test:

Login to issue tracker: https://issues.joomla.org/tracker/joomla-cms/22904.
Click `Test this`.
Mark `Tested successfully`.
Click `Submit test result`.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22896">issues.joomla.org/tracker/joomla-cms/22896</a>.</sub>
