### ISSUE TITLE
Extension Pagination and Uninstalling

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#22906]
### Steps to reproduce the issue
Find an extension with logs of plugins for example: EasyBlog, navigate to page two, uninstall all of page two extensions/plugins/modules. The page refreshes as if all has been uninstalled from the entire site. But actually only all of page two was uninstalled which is right, you should however now be redirected to page 1 not page 2 since there is no page 2. 

Suspect we need to check if total extensions = limit if so set limitstart = 0.

**Comment by SharkyKZ** [comment]
Test PR #25195 please.

**Comment by ghost** [comment]
Closed as having Pull Request #25195
