### ISSUE TITLE
Custom field type calendar wont's save when only date (no time) is used

### ISSUE THREAD

**Issue by jjnxpct** [joomla/joomla-cms#22900]
### Steps to reproduce the issue
Create a custom field of the type 'calendar' (datepicker). Set the option 'Show time' to No. Create an article and fill in the date and save the article.

### Expected result
The date is saved.

### Actual result
An error appears saying the date field is not valid. Article is not saved. This does not happen when the option 'Show time' is set to 'Yes'

### System information (as much as possible)
Joomla 3.9, PHP 7.2.10, MySQL 5.5.61

**Comment by Quy** [comment]
Unable to reproduce. What is the date entered and the exact error message?

**Comment by jjnxpct** [comment]
I narrowed it down a bit more. It seems this error only appeared when my backend language is set to Dutch. When I set it to the default English the problem does not exist. I have some screenshots to illustrate:

https://inxpactdrive.nl/s/npXCWKOU5hvHBzl

Not sure how or why a backend language would cause this.

**Comment by jjnxpct** [comment]
I tried to disable all admin language overrides. That did not help.

**Comment by jjnxpct** [comment]
Well, the problem is solved for me by adding this to the language overide for the backend Dutch language:

DATE_FORMAT_CALENDAR_DATE="%d-%m-%Y"
DATE_FORMAT_CALENDAR_DATETIME="%d-%m-%Y %H:%M:%S"
DATE_FORMAT_FILTER_DATE="d-m-Y"
DATE_FORMAT_FILTER_DATETIME="d-m-Y H:i:s"

Not the date is displayed in the Dutch format (better for us...) and the article gets saved OK, And as far as I can see this has no further impact on the site. So this solves this issue for me. 

But maybe this problem should not occur at all? I will leave this assessment to others for now.
Thanks for listening so far ;-)

**Comment by ghost** [comment]
@jjnxpct can you please get in touch with one Dutch-Translator at https://docs.joomla.org/JDOC:Documentation_Translators#nl_-_Nederlands_-_Dutch?

**Comment by brianteeman** [comment]
NOTE: not the first time there has been an issue with the dutch date format iirc - maybe @bakual can confirm

**Comment by wojsmol** [comment]
@jjnxpct There is small typo in Dutch language package for Joomla! 3.9.0 both site and admin in nl-NL.ini there is ```DATE_FORMAT_FILTER_DATE="y-m-d"``` instead of ```DATE_FORMAT_FILTER_DATE="Y-m-d"```.

**Comment by infograf768** [comment]
Dutch TT can be reached at
https://forum.joomla.org/memberlist.php?mode=viewprofile&u=129749

**Comment by jjnxpct** [comment]
@wojsmol Excelent find. Thanks!

**Comment by jjnxpct** [comment]
I noticed the same error in these language strings:
DATE_FORMAT_LC4="y-m-d" (admin nl-NL.ini)
DATE_FORMAT_JS1="y-m-d" (site nl-NL.ini)

**Comment by wojsmol** [comment]
cc @MartijnMaandag (this is Dutch TT github nick) Please check Dutch language pack regarding date formats.

**Comment by Bakual** [comment]
I'm going to close this issue then as it is indeed a bug in the language.

I think @brianteeman was referring to the PR https://github.com/joomla/joomla-cms/pull/22373 which tries to solve an issue that is already solved if the language pack would be corrected (from how I understand that PR) 😄

**Comment by MartijnMaandag** [comment]
The date format in the Dutch language files is like this for years. I changed it and am testing this with @jjnxpct 
When it works I will release a new Dutch package.

**Comment by jjnxpct** [comment]
@MartijnMaandag I tested the new language files you send me. I cleared all the overrides and there are no issues as far as I can tell. The problem I had described in this thread is solved. Thanks!

**Comment by Bakual** [comment]
I'm closing this issue then.
