### ISSUE TITLE
Several attributes have no effect on the editor field type

### ISSUE THREAD

**Issue by aDaneInSpain** [joomla/joomla-cms#22901]
### Steps to reproduce the issue
Create a component using the [editor field type](https://docs.joomla.org/Editor_form_field_type). Set a value in the following 4 field types:

- width
- height
- cols
- rows

### Expected result
The wysiwyg editor follows the entered attribute data

### Actual result
The wysiwyg editor remains unchanged

### System information (as much as possible)
Joomla 3.9.0

### Additional comments
I have updated the documentation for now and tagged those 4 fields. Once I know if this is a bug or intended behaviour I will update the documentation to reflect reality.

**Comment by brianteeman** [comment]
If I remember correctly the issue is that the actual editor used will/can/may override these.

If you disable the joomla editor plugins the options "should" work.

**Comment by aDaneInSpain** [comment]
Yeah I figure it is something like this, but if it does not work with the default editor I think the documentation should read something like "Only works on some editors" or similar.

**Comment by Quy** [comment]
Related PR #14033?

**Comment by aDaneInSpain** [comment]
I think it is related but not sure if it the whole story or if it was fixed. Why is the issue closed?

**Comment by brianteeman** [comment]
it is not closed

**Comment by aDaneInSpain** [comment]
My bad. Not sure why I saw that as closed.

**Comment by ghost** [comment]
@Quy #14033 seems not to work.

**Comment by Quy** [comment]
Please test PR #26755 for the width/height settings.

**Comment by jwaisner** [comment]
@aDaneInSpain Is this still an issue after the PR that Quy posted?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22901">issues.joomla.org/tracker/joomla-cms/22901</a>.</sub>

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed.

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc [@zero-24](https://github.com/zero-24)
