### ISSUE TITLE
[4.0] Sample data & Multilingual installation

### ISSUE THREAD

**Issue by Chacapamac** [joomla/joomla-cms#22907]
### Steps to reproduce the issue

In Joomla installation process

### System information (as much as possible)
alpha5-dev

Mamp, PHP 7.2.1, Firefox Dev, El Capitan

If I understand well, the “Sample data” will be pull out of the installation process.
https://github.com/joomla/joomla-cms/issues/20262

My first remark will be that it will really cool and logical to be able, at least (in the installation process), to install another language for the administration and/or installing the base multilingual system. That will be great for non-english speaking webmaster, site owner to right away edit their brand new Joomla site in their native language.

• This is how I see that in the Joomla Web Installer:
**Step 1:** when the user choose another language Than English (United State) at the first Installation window
 ￼![screen shot 2018-11-01 at 15 29 12](https://issues.joomla.org/uploads/1/4e44634c5018fb0a35f61c6bb4038eb4.jpg)

(Maybe this is the intent already but the select language don’t seem to work???)

— The language selected is automatically install

**Step 2:** one of the following installation window should show this and do exactly what it says
![screen shot 2018-11-01 at 15 30 32](https://issues.joomla.org/uploads/1/ad02db73e591b8369969d282487f534b.jpg)
￼ 

• **This panel should appear alone**, as an option
(You should have a bypass button here if the user do not want to install anything at that point to go to the next screen

I really don’t care about the “Blog” Sample data and worst, the fact that you can’t install the Multilingual setup if you install it first is confusing and many people will have to redo their installation.

Adding other languages and/or creating a fully functional multilingual site are a great power feature compare to other CMS, when installing. Installing Blog sample data are not important.

Keep the Multilingual option at the Installation level and leave Blog Sample data as a choice in the Control panel level — No more confusion and on top of that Joomla show one of it’s major force. Installation of a fully multilingual site in few click.

**Comment by Bakual** [comment]
I'm not aware that anyone wanted to remove the language installation step from the installer. Only the sample data step should be removed but that's independant from the language installation.

**Comment by Chacapamac** [comment]
This is my new view...

**• Step 1**
![1-choose-language---site-name](https://user-images.githubusercontent.com/1907276/48561650-67efd000-e8be-11e8-9801-646120536ee1.jpg)

**• Step 2**
![2-user-admin-back-button](https://user-images.githubusercontent.com/1907276/48561668-763dec00-e8be-11e8-9b72-e68e6ea0471f.jpg)

**• Step 3**
No change to Database infos (Only the back button)

**• Step 4**
![4-multilanguage-system---finish](https://user-images.githubusercontent.com/1907276/48561733-9d94b900-e8be-11e8-930f-ae7bbcf7e491.jpg)

**Comment by Chacapamac** [comment]
Kind of sad, after trying to reach to revive the Joomla archived team “User Experience Team (JUX)” or join and participate to any team in charge of the ergonomic development, design and UX for Joomla 4. No response ?????

Joomla 4 steaming along with an interface that is really far from optimal and people wanting to help have no place to donate their time.

This is a complete revision of the interface, not porting attention here can be catastrophic. So far I’m far from impress in what I see...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22907">issues.joomla.org/tracker/joomla-cms/22907</a>.</sub>

**Comment by mbabker** [comment]
As far as I'm aware there is no "formal" UI/UX team right now, there does seem to be a small group of people working in a private space on revisions to the backend template to get things closer to the actual design specification so maybe you can catch one of their ears and be invited to that space?

**Comment by ghost** [comment]
@Chacapamac as @mbabker wrote: https://volunteers.joomla.org/teams/j4-backend-template-working-group - source: https://volunteers.joomla.org/board-of-directors/reports/921-osm-inc-full-board-meeting-november-29-2018

**Comment by Chacapamac** [comment]
Thanks franz, from that link

I will try to be part of that group...

Production Department

A new Template Working Group has been created to work on the backend template https://volunteers.joomla.org/teams/j4-backend-template-working-group

Production Department Leadership voted to allow upgrades from Beta’s of Major/Minor releases to simplify testing pre-releases.

Joomla 3.9.1 has been released. George would like to thank Michael Babker for his hard work as Release Lead.

Other than the Backend Template, the priority for Joomla 4 is to stabilise the features merged so far in order to start working towards a Beta release.

**Comment by Chacapamac** [comment]
Invitation demand sent.

**Comment by Chacapamac** [comment]
Nobody came back to me?
Joomla 4 will be release in the first half of 2019 and the interface is the first thing that people will see and experience. 
That first impression and the first minutes of use will determine it’s future success.

So far, what I see is an interface that I consider relatively poor at the visual level & ergonomically. 

Really Sad!

**Comment by Bakual** [comment]
> Joomla 4 will be release in the first half of 2019.

I would be very suprprised if J4 is released in the first half of 2019. More likely end of this year.

> So far, what I see is an interface that I consider relatively poor at the visual level & ergonomically.

The software is an alpha version...

**Comment by Chacapamac** [comment]
Still ready to help?

**Comment by wilsonge** [comment]
Can we put the screenshots in https://github.com/joomla/joomla-cms/issues/24481 please as they look good (but there's been some discussions there on various technical aspects). This is definitely something I'd like to implement though!

If anyone's interested in working on this please do!!

**Comment by Chacapamac** [comment]
Anything I can do, ask, I’m not a programmer but really good at CSS, design and ergonomic. 
Don’t forget to see my discussion on Joomla forum with 40612 views and my vision on the sad design of the administration here —> https://forum.joomla.org/viewtopic.php?f=803&t=970614
