### ISSUE TITLE
[3.9.0] System - Privacy Consent - Modal with Privacy Article requires MooTools

### ISSUE THREAD

**Issue by jwiesel** [joomla/joomla-cms#22908]
### Steps to reproduce the issue
* Disable MooTools on your site (e.g. using plugin "MooTools Enabler/Disabler"
* Activate plugin "System - Privacy Consent"
* In the plugin options set a "Privacy Article"
* With a user without a valid consent try to login
* Below "Data Privacy", hover over or click on the star icon with the privacy policy 

### Expected result
* A modal dialog should open showing the data privacy article

### Actual result
* No modal window appears. Actually nothing happens except showing the popover
* Developer console of the web-browser shows two errors

> ReferenceError: Hash is not defined
> TypeError: SqueezeBox is undefined

### System information (as much as possible)
* Joomla 3.9.0
* PHP 7.2

### Additional comments
* Can we use Bootstrap modals instead of MooTools for the plugin??

**Comment by zero-24** [comment]
Please check & test this one: https://github.com/joomla/joomla-cms/pull/22926 as this is the first partial fix of this issue touching the `Content ConfirmConsent` Plugin. When approved similar code can be applied to the other places you mention.

**Comment by ghost** [comment]
closed as having Pull Request #22926
