### ISSUE TITLE
SQL error during discovery of privacy suite

### ISSUE THREAD

**Issue by Stevec4** [joomla/joomla-cms#22905]
### Steps to reproduce the issue

Installed J3.9
Use discover to install the new privacy suite

### Expected result
Suite should be installed

### Actual result
Message is displayed that the suite is installed but nothing appears in the menus.
Select discover once again action logs is the only item displayed. when selecting install the SQL error is displayed.

1062 Duplicate entry "507" (it increments each time I try to install)
/libraries/joomla/database/driver/mysqli.php:661

### System information (as much as possible)
Database Type  mysql 
Database Version  5.5.5-10.2.12-MariaDB-log 
Database Collation  utf8_general_ci 
Database Connection Collation  utf8mb4_general_ci 
PHP Version  7.1.22 
Web Server  Apache 
WebServer to PHP Interface  cgi-fcgi 
Joomla! Version  Joomla! 3.9.0 Stable [ Amani ] 30-October-2018 14:00 GMT 
Joomla! Platform Version  Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 
User Agent  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763 

### Additional comments
![discover](https://user-images.githubusercontent.com/6751354/47850652-5e3d7700-ddac-11e8-8e11-a66a226b0c34.png)
![error](https://user-images.githubusercontent.com/6751354/47850653-5e3d7700-ddac-11e8-89e4-b87f24024a22.png)

**Comment by alikon** [comment]
please clarify
are you updating/upgrading from wich  version ?

**Comment by ReLater** [comment]
> Installed J3.9

Last stable release?
A new installation?

> Use discover to install the new privacy suite

Normally this step should not be necessary after a new installetion.

**Comment by Stevec4** [comment]
upgraded from 3.8.13

**Comment by ghost** [comment]
After upgrade from 3.8.13 haven't to discover Privacy Suite, it was installed.

**Comment by mbabker** [comment]
If you're running into duplicate key issues it basically means the auto increment on your extensions table got reset (because usually it should be over 10,000).  Since core still tries to force all of its extensions to have known identifiers, your issue boils down to autoincrement being a mess on your system.  Unfortunately there isn't much that can be done about this one and the last time I raised the issue it was shrugged off.

**Comment by jflash** [comment]
I was having analog problem: https://forum.joomla.org/viewtopic.php?f=710&t=966861

**Comment by Stevec4** [comment]
Thanks for the explanation Michael.

**Comment by uglyeoin** [comment]
Here is a solution.  https://www.joomla-monster.com/blog/joomla-templates/solution-for-1602-duplicate-sql-entry-error-while-updating-to-joomla-3-6 (runs and hides)

**Comment by Stevec4** [comment]
@uglyeoin Thanks for posting that link.
