### ISSUE TITLE
Sidebar Users: entering menu items

### ISSUE THREAD

**Issue by atodaro** [joomla/joomla-cms#22910]
### It requires the insertion of the menu items "privacy" and "user actions log" as image
![screen menu utenti](https://user-images.githubusercontent.com/12257435/47905327-21927e00-de87-11e8-9256-7f30356025e3.png)

### Additional context
Joomla 3.9.0
Admin template: Isis

**Comment by brianteeman** [comment]
Please read https://github.com/joomla/joomla-cms/issues/22867#issuecomment-434343296

**Comment by atodaro** [comment]
Thanks @brianteeman
