### ISSUE TITLE
[4.0] Multilingual Sample Data install stay stuck at 3 of 8

### ISSUE THREAD

**Issue by Chacapamac** [joomla/joomla-cms#22919]
### Steps to reproduce the issue

Install Multilingual Sample Data in administration Control Panel/Sample Data

### Expected result
Installation

### Actual result

Stuck on step 3

### System information (as much as possible)

alpha5-dev

Mama, PHP 7.2.1, Firefox Dev, El Capitan

### Additional comments
• No Blog Sample data installed
• Second language installed and Content language published

![screen shot 2018-11-02 at 14 28 29](https://issues.joomla.org/uploads/1/62c75db4aa22df2d2861b78b44a548da.jpg)

**Comment by Bakual** [comment]
The third step would publish the content languages.
My guess is that something crashes now because of some namespacing in 4.0 or some other architecture change. If you can look at the raw AJAX respone, it will likely have a PHP error message within the JSON data somewhere. That would help.

**Comment by Chacapamac** [comment]
I have no error in the logs but on Firefox dev console I get that
![errors](https://user-images.githubusercontent.com/1907276/47944624-15341280-ded3-11e8-909f-1f1837417365.jpg)

3 errors are identical
![error2](https://user-images.githubusercontent.com/1907276/47944739-db174080-ded3-11e8-972c-4b3c66726494.jpg)

Last error
![error3](https://user-images.githubusercontent.com/1907276/47944742-e4081200-ded3-11e8-8b51-653dbc0fc8c3.jpg)

**Comment by Bakual** [comment]
I see

The issue is actually two.
First one is that the blog sampledata plugin doesn't check in step4 if it's meant to act on that event. It should not but it returns a success message neverthless.
The second issue is that the JavaScript apparently can't handle multiple messages and thus breaks on step 4.

Adding a check to the blog sampledata plugin in step4 would fix the main issue here.

**Comment by Chacapamac** [comment]
I’m not using the blog sample data as you have to install Multilingual first.
Something I can do ?
Not really a big Java coder...

**Comment by Bakual** [comment]
Check https://github.com/joomla/joomla-cms/pull/22937
