### ISSUE TITLE
[4.0] Warnings in npm install

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#22915]
### Steps to reproduce the issue

1. Fetch the current git repo
2. run `npm install`

### Expected result
No warnings

### Actual result

npm WARN lifecycle joomla@4.0.0~install: cannot run in wd joomla@4.0.0 node build.js --copy-assets && node build.js --build-check (wd=/var/www/html/joomla-cms)
npm WARN lifecycle joomla@4.0.0~postinstall: cannot run in wd joomla@4.0.0 node build.js --compile-js && node build.js --compile-css && node build.js --compile-ce &&cd administrator/components/com_media && npm install && npm run build (wd=/var/www/html/joomla-cms)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 8149 packages in 7.427s
found 10 vulnerabilities (9 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

### System information (as much as possible)

Current 4.0-dev Branch on Ubuntu 18.04

### Additional comments
I have just rebuilt my system. Joomla is now working. But: I'm worried about the warnings. Did I do something wrong?

```
$ node --version
v10.13.0
$ npm --version
6.4.1
```

**Comment by wojsmol** [comment]
@astridx Please post node --version and npm --version results.

**Comment by brianteeman** [comment]
fsevents is only for osx - thats why you get an unsupported message on windows and why it is optional (google for more info on what it is used for if you want) so as you are on windows it is normal

**Comment by astridx** [comment]
@wojsmol 
```
$ node --version
v10.13.0
$ npm --version
6.4.1

```

**Comment by astridx** [comment]
@brianteeman Thanks for explaining the fsevents warning.

**Comment by dgrammatiko** [comment]
@astridx the warning has to do with permission:
Do 
```
sudo chown -R my_name /usr/local
```

This will fix that but also is something common for linux installation


PS replace my_name with your actual user name

**Comment by brianteeman** [comment]
Can this be closed now?

**Comment by astridx** [comment]
@dgrammatiko Thank you for your reply. But, my user is the owner of /urs/local. 

@brianteeman I just updated my branches and started a new `npm install` but I see still see the warnings and vulnerabilities. Are I am the only one?

**Comment by mbabker** [comment]
The vulnerabilities are not a concern.  The NPM environment for the CMS is an ecosystem of something like 5000 packages and dependencies of dependencies are locked to older versions of packages with fixed issues.  Those issues are in the build/compiler dependencies, if they're even triggered at all.

**Comment by sakiss** [comment]
For anyone facing that, seems like a permission related issue.
This is how i solved it:
`npm install --unsafe-perm`
