### ISSUE TITLE
Admin component menu: plugin & template visible

### ISSUE THREAD

**Issue by peterhulst** [joomla/joomla-cms#22911]
### Steps to reproduce the issue
Select Component menu in version 3.9.0

### Expected result
List of components only

### Actual result
Some Plugins and Templates are also displayed

### System information (as much as possible)

version 3.9.0

**Comment by infograf768** [comment]
can't reproduce the issue here.

**Comment by peterhulst** [comment]
See display in figure attached from local test installation (e.g. contentnotifier, Helix3, PurityIII, pkg*)

![joomla390_bug_component_menu](https://user-images.githubusercontent.com/8728563/47907096-dda17800-de8a-11e8-8c7c-16cd094f7a76.jpg)

**Comment by ReLater** [comment]
Because I see "SP Upgrade" in the list. This error occurs relatively often in sites that were upgraded in the past from Joomla 1.5 or 2.5 with migration tools. Sometimes these errors are "sleeping" for a long time before they become obvious.

I don't know if the "Rebuild" button in "Menus" area can help here.

But that's not a Joomla core issue and you should ask in a forum for help.

**Comment by infograf768** [comment]
FYI:
we have experienced such errors for language packs for example, when updating multiple items at the same time and Akeeba Backup was part of these multiple items.

**Comment by peterhulst** [comment]
Thank you for the quick reply. The 'Rebuild' does not help.
Indeed the site was rebuild with SP Upgrade. 
But the display of plugin and templates in Component Menu was not visible in 3.8.13. 
It started in 3.9.0 directly after the upgrade.

Regards.

**Comment by ghost** [comment]
> Sometimes these errors are "sleeping" for a long time before they become obvious. (ReLater)

**Comment by brianteeman** [comment]
Probably an invalid assets table. See https://docs.joomla.org/Fixing_the_assets_table

**Comment by Quy** [comment]
Please ask help in [Joomla forums](https://forum.joomla.org/viewforum.php?f=710).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22911">issues.joomla.org/tracker/joomla-cms/22911</a>.</sub>
