### ISSUE TITLE
[4.0] Saving new site menu type fails with error "Incorrect integer value: 'client_id' ..."

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#22928]
### Steps to reproduce the issue

New installation of 4.0-alpha5-dev nightly build from 2018-11-03.

Create a new menu type for the site and try to save it.

### Expected result

Saved without error.

### Actual result

![screen shot 2018-11-03 at 12 23 27](https://issues.joomla.org/uploads/1/a62d6b5700423666ad99f3a12e20ef7b.png)

### System information (as much as possible)

New installation of 4.0-alpha5-dev nightly build from 2018-11-03.
PHP 7.2.10
MySQL 5.5.60
DB driver MySQLi

**Comment by richard67** [comment]
Could that be caused by PR #22903 ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22928">issues.joomla.org/tracker/joomla-cms/22928</a>.</sub>

**Comment by SharkyKZ** [comment]
Test PR #22929 please.

**Comment by richard67** [comment]
Closing as there is a PR #22929 .
