### ISSUE TITLE
Latest Actions 

### ISSUE THREAD

**Issue by joomlatester** [joomla/joomla-cms#22921]
### Steps to reproduce the issue
Go to Extensions > Modules > Administrator > Latest Actions > Advanced > Automatic Title (ON).
Next go to System > Control panel.

![error](https://user-images.githubusercontent.com/44710991/47935762-db1b3e80-dedb-11e8-80d6-01b85b094824.jpg)

### Expected result
No error

### Actual result
An error has occurred.
Class 'ModLatestHelper' not found

### System information (as much as possible)
Joomla 3.9.0

**Comment by zero-24** [comment]
Confirmed. Please check & test this patch: https://github.com/joomla/joomla-cms/pull/22925
