### ISSUE TITLE
Latest Actions module

### ISSUE THREAD

**Issue by joomlatester** [joomla/joomla-cms#22922]
### Is your feature request related to a problem? Please describe.
Display module to all Administrator not only Super User and add feature to show action only a logged in user.
Example: Popular Articles > Authors (Anyone, Added or modified by me)
Example: Latest Actions > Actions (All, Only my actions)

**Comment by zero-24** [comment]
Hi,

> Display module to all Administrator not only Super User 

RE: (by @mbabker )
> It was purposefully decided to restrict these components to super users only. In the case of a privacy request, when exporting data the person processing the request inherently must have (or gains through an information leak) read access to all of the data that plugins are responding with. When removing data, the person processing the request must inherently have (or gains by bypassing ACL) what is in essence a combination of core.edit and core.delete permissions. And for action logs, someone could see a user performing actions in a component they may not even be aware is installed because ACL restricts them from even seeing it.
>If we made it so non super users were able to access these components, inherently we are either dealing with some form of ACL violation in other parts of the system or the processed data must be ACL restricted to that user's role, resulting in an incomplete action log or data export.

Where this would result into an information leak to the Administrator Users.

More context can be found here: https://github.com/joomla/joomla-cms/issues/20281#issuecomment-422772956 

> add feature to show action only a logged in user.
> Example: Popular Articles > Authors (Anyone, Added or modified by me)
> Example: Latest Actions > Actions (All, Only my actions)

I fully understand the request. I would like to hear @brianteeman 's and @mbabker 's opinion on this first as this module is not directly intended to do something like this and it would add yet another option :)

**Comment by brianteeman** [comment]
I agree with @mbabker comment

**Comment by ghost** [comment]
@brianteeman does your Comment mean to close this Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22922">issues.joomla.org/tracker/joomla-cms/22922</a>.</sub>

**Comment by brianteeman** [comment]
That is my personal opinion

**Comment by ghost** [comment]
thanks @brianteeman 

closing this Issue as there is no Response; it can always reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22922">issues.joomla.org/tracker/joomla-cms/22922</a>.</sub>
