### ISSUE TITLE
Privacy component ACL

### ISSUE THREAD

**Issue by joomlatester** [joomla/joomla-cms#22924]
### Is your feature request related to a problem? Please describe.
We have a few user groups on website:
- Registered (Front-end)
- Author (Backend)
- Editor (Backend)
- Administrator (Backend)
Group manages users and privacy but not joomla updates, extensions install.
- Super administrator (Backend)
Group manages the site from a technical point of view. Performs updates etc.

### Describe the solution you'd like
Add options to Privacy component which group has access to the component.
Now it has to be a Super user and in addition to the Privacy Component must have access to, for example to Joomla! update.

**I have a suggestions.
When admin group has access to User Component (Access Administration Interface, Delete) then Component Privacy appears to.**

**Comment by ggppdk** [comment]
It was only allowed to super admin,
because some aspects related to com_privacy are only possible / should be only possible for super admin

i found these topics / comments

https://github.com/joomla/joomla-cms/pull/22239
https://github.com/joomla/joomla-cms/issues/20281#issuecomment-422772956

**Comment by brianteeman** [comment]
Closed as intended behaviour
