### ISSUE TITLE
com_newsfeeds/newsfeed alternative layouts don't work

### ISSUE THREAD

**Issue by stutteringp0et** [joomla/joomla-cms#22920]
### Steps to reproduce the issue

Copy /components/com_newsfeeds/views/newsfeed/tmpl/default.php to /templates/protostar/html/com_newsfeeds/newsfeed/default.php and to
/templates/protostar/html/com_newsfeeds/newsfeed/alt.php

Edit /templates/protostar/html/com_newsfeeds/newsfeed/default.php add "default" just after the first closing PHP tag.
Edit /templates/protostar/html/com_newsfeeds/newsfeed/alt.php add "alt" just after the first closing PHP tag.

Create a newsfeed, and change its layout to "alt"

Create a menu item to a single news feed to display this test.

### Expected result

Overridden alternative layout displayed

### Actual result

Overridden default layout displayed

### System information (as much as possible)

J3.9, PHP 7.2 FPM, NGINX

### Additional comments

It appears that the layout override does work, it just doesn't load anything other than a file named default.php

**Comment by tonypartridge** [comment]
If you remove the default.php file does alt then load?

**Comment by stutteringp0et** [comment]
No sir. Nothing I've tried loads alt. The reason I added the default test is to show that the override works and which is loaded

**Comment by uglyeoin** [comment]
I believe overrides only work if the original template exists in the main component directory.  Thus is it is not an override but a unique template which will not be overridden by an update so it can go in the normal folder.  At least that was what I thought happened.

**Comment by mbabker** [comment]
Menu items are goofy beasts when it comes to alternate layouts in that they define the layout to be used.  So you need the appropriate XML file to go along with it if you're trying to do something as a new layout.

**Comment by stutteringp0et** [comment]
OK, I'll look into that.  I remember something about XML files in the override document

**Comment by stutteringp0et** [comment]
I've tested this against com_content and I can create any override layout name I desire.  It doesn't need to exist in components/com_content/view/article/tmpl in order to be selected and the override to operate as expected.

I have also tested this behavior against com_contact, and it behaves like com_newsfeeds, only default.php is activated as an alternative layout although alternate files are displayed and can be selected.

**Comment by SharkyKZ** [comment]
If Article behavior is considered correct, it can be changed in other places. Related commit https://github.com/joomla/joomla-cms/commit/80fffd920410c8a47b3a2e232d11be00b9803a6b.

**Comment by jwaisner** [comment]
@stutteringp0et Is this still being experienced in the latest J3 build?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22920">issues.joomla.org/tracker/joomla-cms/22920</a>.</sub>

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

As explained above https://github.com/joomla/joomla-cms/pull/30676 this is not an issue to be resolve. It just didnt work the way that you expected it to.

Please close
