### ISSUE TITLE
Cannot delete module position for module in Module manager

### ISSUE THREAD

**Issue by ManfredHuebner** [joomla/joomla-cms#22935]
### Steps to reproduce the issue
Editing a module and try to delete the module position to none

### Expected result
Should be possible to assign a module to position "none" as in previous versions

### Actual result
Module position cannot be set to none.

### System information (as much as possible)
Joomla 3.9.0, PHP 7.1

**Comment by brianteeman** [comment]
Which version of Joomla are you referring to?

**Comment by ManfredHuebner** [comment]
Sorry, Joomla 3.9. In 3.8.13 it worked. The choosen element doesn't have the attribute -deselect but in 3.8.13 it has. Unfortunately, I wasn't able to determine in which part of the code the attribute is set (maybe in JS of the choosen library)

**Comment by infograf768** [comment]
I confirm the issue.
This is what we got before 3.9.x
<img width="390" alt="screen shot 2018-11-06 at 15 41 36" src="https://user-images.githubusercontent.com/869724/48071412-8c6eec80-e1da-11e8-8e86-2463068e8c42.png">

When clicking on the cross it deleted the position, thus setting it to None.
The cross is absent in 3.9.0 and staging.

**Comment by infograf768** [comment]
@dgrammatiko

**Comment by Quy** [comment]
In chosen.query.js:
under 3.8.13, `this.options.allow_single_deselect` is `true`.
under 3.9.0, `this.options.allow_single_deselect` is `undefined`.

I don't know where this value is set.

**Comment by ManfredHuebner** [comment]
I also try to figure that out and cannot find. So I guess, the chosen version has changed and that's the reason.

**Comment by infograf768** [comment]
No change as we can see here:
https://github.com/joomla/joomla-cms/tree/staging/media/jui/js

**Comment by ManfredHuebner** [comment]
Mysterious.
I can remember that we have had a similar issue back in a previous version. Unfortunately, I cannot remember which one ;-)

**Comment by infograf768** [comment]
I found a way to solve this. can you test?
Modify
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_modules/views/module/tmpl/edit_positions.php#L26

by using
`'id'          => 'jform_position_chzn',` // i.e. adding `_chzn` to the id

The drawback is that we get in source a double `_chzn` for the <div id:
<img width="728" alt="screen shot 2018-11-09 at 11 29 38" src="https://user-images.githubusercontent.com/869724/48257471-e3f79d00-e412-11e8-9ee3-2d065f0e3163.png">

I can get rid of it in `chosen.query.js` by taking off `+ "_chzn"` in
```
      if (this.form_field.id.length) {
        container_props.id = this.form_field.id.replace(/[^\w]/g, '_') + "_chzn";
```
But this may have undesired results.

**Comment by infograf768** [comment]
BTW: I guess same issue when editing modules in frontend.

**Comment by dgrammatiko** [comment]
@infograf768 sorry but the error is not in the chosen file!!!
`unset($this->_scripts["/media/system/js/moduleorder.js"]);` and you'll see that the x button reappears. SO whatever was committed in the moduleorder script is wrong

**Comment by infograf768** [comment]
Looking

**Comment by infograf768** [comment]
I confirm.
reverting https://github.com/joomla/joomla-cms/pull/21692 corrects this behavior.

**Comment by infograf768** [comment]
@Fedik 
Can you have a look at this please? I can't find how to modify the js except by reverting.

**Comment by Fedik** [comment]
I will try

**Comment by infograf768** [comment]
tks

**Comment by dgrammatiko** [comment]
Reverting is the best choice, that field doesn't need to be governed by chosen and if the styling (that was the issue solved there, right?) doesn't fit the rest of the chosen fields just update the CSS. DO NOT add javascript to fix CSS problems...

**Comment by Fedik** [comment]
please test #23052
