### ISSUE TITLE
'Call to a member function get() on string' while browsing articles by TAG

### ISSUE THREAD

**Issue by cloggg** [joomla/joomla-cms#22934]
Some of my articles are tagged.
I also have a menu, which contains of items: 'Tags » Compact list of tagged items', where each item shows articles tagged with different tag
In majority, all items display correct results, however I cannot browse at least one specific tag list.
I got 'Call to a member function get() on string' error
I saw that there were some fixes of such problem done in version 3.9, but they did not work in my case (I had the same issues in 3.8.x, but decided to wait for 3.9)

I am able to provide more details, however I need to know what to look for.

Please let me know if you need additional information
Bests, 
Cloggg

Env:
Joomla! Version 	Joomla! 3.9.0 Stable [ Amani ] 30-October-2018 14:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0 
PHP Version 7.1.20

**Comment by Quy** [comment]
Please test this PR #19684

**Comment by cloggg** [comment]
This solved the issue - thank you!
I will start using tags and report if I find any problem.
For the moment the solution looks OK ;)

Kind Regards
Cloggg

**Comment by Quy** [comment]
Thank you for testing. Please submit your test result:

Login to issue tracker: https://issues.joomla.org/tracker/joomla-cms/19684
Click `Test this`.
Mark `Tested successfully`.
Click `Submit test result`.

**Comment by Bakual** [comment]
Closing this issue since we have a PR
