### ISSUE TITLE
[3.9.0] On login with Privacy Consent plugin enabled and Logout menu item published:  user unable to consent to privacy policy

### ISSUE THREAD

**Issue by sozzled** [joomla/joomla-cms#22938]
### Steps to reproduce the issue

See full details at https://forum.joomla.org/viewtopic.php?f=706&t=966887 (they're fairly detailed)
Start with pre-J! 3.9.0 website with **Logout** **_menu item_** published.
Update site to J! 3.9.0
Enable _System - Privacy Consent_ plugin and select a published article containing the site's "privacy policy"
Login to frontend.

### Expected result

On first login at frontend, user should be redirected to a page where the user profile is displayed and the user is able to consent to the privacy policy (or edit the logged-in user profile). 

### Actual result

On first login at frontend, user is redirected to a page where the user profile is displayed but the user is unable to consent to the privacy policy (or edit the logged-in user profile). 

### System information (as much as possible)

Full details contained in FPA report at https://forum.joomla.org/viewtopic.php?f=706&t=966887#p3546552

### Additional comments

No-one else has confirmed that they're able to reproduce this problem on their own websites.  One other user has confirmed that the situation (as I've described it) happens when they've also used the test site.

The problem is reproducible on any site where the **Logout** menu item is published and the _System - Privacy Consent_ plugin is configured and enabled.

Not related to https://github.com/joomla/joomla-cms/pull/22927 although the file components/com_privacy/controller.php has been replaced with the updated replacements

**Comment by SharkyKZ** [comment]
I can reproduce this. It's a legacy router issue that affects older versions too (tested on 3.8.13). So not related to Privacy Consent plugin.

To reproduce:
Create `Users -> Logout` menu item.
Do not create any other `Users` menu item.
Attempt to edit user profile.

Related PR #21274 but it's broken at the moment. @Hackwar suggests switching to modern routing which does solve the issue.

**Comment by sozzled** [comment]
@SharkyKZ:  sorry but the test website http://vanilla390.enduring.com.au has modern routing enabled.  I made the change after I read the follow-up suggestions.  Using modern routing does **_not_** solve the issue.

Please remember the important qualification to reproduce the issue:  you need to have a **Logout** _**menu item**_ published.   It's definitely related to the Privacy Consent plugin.

**Comment by SharkyKZ** [comment]
>modern routing enabled

Just to make sure, is it enabled for `com_users` too?

>It's definitely related to the Privacy Consent plugin.

I don't think so. The issue can be reproduced on your 3.8.13 site too.

Login to http://vanilla3813.enduring.com.au.
Open user profile (directly through `index.php?option=com_users&view=profile` or enable `Show Profile Link` option in login module for quick access).
Click `Edit Profile`.

**Comment by Webdongle** [comment]
I can confirm the issue happens when 3.8.13 is installed and updated to 3.9.0.
When a user is registered when the System - Privacy Consent plugin is disabled ... then the first login after it is enabled renders the site unusable.  There is no way to confirm consent.
It makes no difference if the user is created from the frontend or in the backend.

The confusing thing is that on my live site (which has been updated from I forget when) there is no issue.  I have compared my site with @sozzled test site (and my own test site) with my live site ... and can not see any reason why it works on my live site but not freshly installed/updated live sites.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22938">issues.joomla.org/tracker/joomla-cms/22938</a>.</sub>

**Comment by sozzled** [comment]
> 
> > modern routing enabled
> 
> Just to make sure, is it enabled for `com_users` too?

Ah-ha!  Enabling "modern routing" on `com_users` resolves the problem.  Very interesting.  This is a "gotcha"!  Thanks for the workaround.

**Comment by Webdongle** [comment]
I have legacy routing on my site but the problem does not exist there ?
It was one of the first settings I compared when testing on the test site.

**Comment by SharkyKZ** [comment]
@Webdongle maybe you have a menu item for User Profile or Edit User Profile?

**Comment by Webdongle** [comment]
@SharkyKZ  none enabled ... but I must have done something different.  In any event the issue is confirmed and some will surely create a fix.

**Comment by webhelpus** [comment]
I'm getting the same issue logging into a live site (was live before 3.9) on the frontend with my Super User Account.  I get automatically redirected to the user edit to consent to the Privacy Policy, but when I do, I get a 403 Access Denied error.

**Comment by Hackwar** [comment]
Is your registration menu item set to guest?

**Comment by SharkyKZ** [comment]
@sozzled @Webdongle #19485 might fix your issue.

**Comment by SharkyKZ** [comment]
@webhelpus I can't reproduce your issue. You should open a separate issue with more details about your menu item setup.

**Comment by ghost** [comment]
closed as Issue by Thread-Opener is solved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22938">issues.joomla.org/tracker/joomla-cms/22938</a>.</sub>
