### ISSUE TITLE
Repetable Field is works poorly with InternetExplorer

### ISSUE THREAD

**Issue by retikanya** [joomla/joomla-cms#22933]
### Steps to reproduce the issue
Global Configuration -> Users -> Email Domains

### Expected result
A line does not appear in an empty list.

### Actual result
An additional line is displayed, disturbed by the operation. The error is **only** for IE + J! 3.9.0.
<img width="1046" alt="repetablefielderror" src="https://user-images.githubusercontent.com/5268327/47956624-7f1dec00-dfa7-11e8-9619-e89204ad9a89.png">

### System information (as much as possible)
Joomla 3.9.0
IE 11.1.47

### Additional comments
None

**Comment by SharkyKZ** [comment]
Duplicate #22880.
