### ISSUE TITLE
Updating an extension does not replace the previous version

### ISSUE THREAD

**Issue by twister65** [joomla/joomla-cms#22949]
### Steps to reproduce the issue
Update any extension with a postgreSQL database installed.

For example : 
- Install Sigplus 1.4.3.2 : https://bitbucket.org/hunyadi/sigplus/downloads/pkg_sigplus-1.4.3.2.zip
- Go to Extensions -> Manage -> Update
- Click on "Find Updates" button
- Select and Update Sigplus 1.4.3.3.

### Expected result
The previous version of the extension is replaced by the new one.

### Actual result
The previous version and the new version of the extension are still there.
![issue-22949](https://user-images.githubusercontent.com/26852967/48119805-8e838a80-e270-11e8-9ab0-3269bb218b26.png)

### System information (as much as possible)
Joomla v3.9 (or staging) with postgreSQL.

### Additional comments
It works fine with a mySQL database.

**Comment by brianteeman** [comment]
Do you get any error messages?

**Comment by twister65** [comment]
> Do you get any error messages?

no error message during the update.

**Comment by twister65** [comment]
It does not find existing extension.
https://github.com/joomla/joomla-cms/blob/d67e585595d41b3705aa0673fd4d3afdaa68d7b5/libraries/src/Installer/Adapter/PluginAdapter.php#L52
https://github.com/joomla/joomla-cms/blob/d67e585595d41b3705aa0673fd4d3afdaa68d7b5/libraries/src/Installer/Adapter/ModuleAdapter.php#L52
I don't know why ?

**Comment by SharkyKZ** [comment]
Test PR #22993 please.
