### ISSUE TITLE
[4.0] Sample Data doesn't show responses

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#22943]
### Steps to reproduce the issue
Try to install any sample data from the module

### Expected result
Status messages are displayed per step so the user sees what happens.

### Actual result
Progress bar works and sample data installs, but the messages aren't visible

### System information (as much as possible)
Tested with Chrome and current Joomla 4 branch.

### Additional comments
The messages are actually there in the DOM, but invisible:

![image](https://user-images.githubusercontent.com/1018684/48001756-cfad5a80-e109-11e8-944d-d7ec4346b613.png)

The console shows errors regarding the Custom Element "<joomla-alert>":

![image](https://user-images.githubusercontent.com/1018684/48001834-04211680-e10a-11e8-93f7-dbfba3d08ecd.png)

**Comment by wilsonge** [comment]
Fixed in custom elements repo. I'll get a released tagged in there and port it over tonight
