### ISSUE TITLE
[4.0] $moduleclass_sfx no more shown in module-views with style="none"

### ISSUE THREAD

**Issue by BPBlueprint** [joomla/joomla-cms#22944]
### Steps to reproduce the issue
e.g. custom module, when used with style="none"

### Expected result
`<div class="mod-custom custom my-own-class">`

### Actual result
`<div class="mod-custom custom">`

### System information (as much as possible)
Joomla 4.0 Alpha5

**Comment by laoneo** [comment]
Can you provide us a bit more detailed steps how we can reproduce the issue?

**Comment by HusiBT** [comment]
Quite easy:
e.g. modules/mod_custom/tmpl/default.php

instead of
`<div class="custom<?php echo $moduleclass_sfx; ?>">`
the possibility for additional class _echo $moduleclass_sfx_ now is missing, so that we only have
`<div class="mod-custom custom">`

This happens when I use in _templaes/my-template/index.php_ the style _style="none"_
`<jdoc:include type="modules" name="position-0" style="none" />`

**Comment by brianteeman** [comment]
style = none has never supported a module chrome with a $moduleclass_sfx

This is not a change in Joomla 4

Perhaps the template you used in Joomla 3 had an override for style=none in modules.php

**Comment by SharkyKZ** [comment]
Suffix was removed from module layout files in J4.

**Comment by HusiBT** [comment]
> 
> 
> Suffix was removed from module layout files in J4.

Sad to hear this...

**Comment by brianteeman** [comment]
@SharkyKZ sorry you are mistaken - the change was to remove the need for the space at the beginning
https://github.com/joomla/joomla-cms/blob/c092ab6c9ad2d9ad6100837407ef78d33709c2b2/templates/system/html/modules.php#L35

**Comment by HusiBT** [comment]
@brianteeman that means, that $moduleclass_sfx will be placed again in layout files?

**Comment by SharkyKZ** [comment]
Layouts, not chromes. See #17447.

**Comment by ghost** [comment]
@BPBlueprint cn this Issue be closed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22944">issues.joomla.org/tracker/joomla-cms/22944</a>.</sub>

**Comment by ghost** [comment]
Closed as no Response; please reopen if needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22944">issues.joomla.org/tracker/joomla-cms/22944</a>.</sub>
