### ISSUE TITLE
Question. Why is $category->title prepared by content plugins?

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#22941]
Small performance issue.

Does anybody know the reason why category titles are prepared by content plugins here:
https://github.com/joomla/joomla-cms/blob/3.9.0/layouts/joomla/content/category_default.php#L55-L59
?

**Comment by ReLater** [comment]
Would it be a B\C break to just escape them like other titles?

**Comment by Bakual** [comment]
The question is not if it is a B/C break if you remove an existing plugin event. It is.
The right question would what the use case is for this event. It's likely to alter the title in some ways (eg attaching an icon to it?) or do some other complex stuff based on category title.

**Comment by ReLater** [comment]
I didn't find a use case in core.

But if it's a B\C break it's not worth to talk about.
