### ISSUE TITLE
[4.0] Cannot install Joomla 4 Alpha 5

### ISSUE THREAD

**Issue by bjxrn** [joomla/joomla-cms#22945]
### Steps to reproduce the issue
I've uploaded & unpacked [the alpha 5 release](https://github.com/joomla/joomla-cms/releases/tag/4.0.0-alpha5) to a server and started the installation process. After entering data in the Setup Site Name, Login Data, and Database Configuration boxes I clicked on Install Joomla. 

### Expected result
I would expect the Joomla installation to proceed

### Actual result
The Database Configuration box stays visible, but above it the two previous step boxes (Setup Site Name, Login Data) become visible again. 
The following error (in core.min.js) is logged to the console in Chrome
```
Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes
    at http://sitename.ext/media/system/js/core.min.js?2eccf88367d4a8b7fe89cd12f66938cb:1:3360
    at Array.forEach (<anonymous>)
    at Object.e.renderMessages (http://sitename.ext/media/system/js/core.min.js?2eccf88367d4a8b7fe89cd12f66938cb:1:3222)
    at onSuccess (http://sitename.ext/installation/template/js/setup.js?2eccf88367d4a8b7fe89cd12f66938cb:88:12)
    at XMLHttpRequest.o.onreadystatechange (http://sitename.ext/media/system/js/core.min.js?2eccf88367d4a8b7fe89cd12f66938cb:1:8195)
```

Trying it in Firefox the console error I get is
```
NotSupportedError: Operation is not supported core.min.js:1
e.renderMessages/<
http://sitename.ext/media/system/js/core.min.js:1:3358
forEach self-hosted:262:13 e.renderMessages
http://sitename.ext/media/system/js/core.min.js:1:3222
onSuccess
http://sitename.ext/installation/template/js/setup.js:88:5
e.request/o.onreadystatechange
http://sitename.ext/media/system/js/core.min.js:1:8183
```

### System information (as much as possible)
Chrome 70.0.3538.77
Firefox 63.0b10 (developer edition)

**Comment by ReLater** [comment]
Please use always nightly builds from source
https://developer.joomla.org/nightly-builds.html
for installation and updates.

**Comment by bjxrn** [comment]
That did resolve this issue.

Please note: There was a post made today over at https://developer.joomla.org/news/758-joomla-4-is-on-the-horizon-alpha-5.html specifically linking to the alpha 5 release page.

**Comment by Sandra97** [comment]
It's also mentioned in this post

> Regular testers will have noticed that there has been a recent change in the development process for Joomla 4. You can no longer simply clone the Joomla 4 branch on GitHub and install Joomla. You will need to set up a full local environment - detailed here.
If you want to quickly try Joomla 4 you can still download and install a nightly build locally or install a hosted instance at launch.joomla.org.

**Comment by bjxrn** [comment]
@Sandra97 I'm not quite sure what you are expecting me to do here. If I see a post saying that there's a new version _for testing_ with a big button saying "Download", then I will take it that I should use that download button.

**Comment by Sandra97** [comment]
It was just to say that everything is mentioned in the blog post: How to test J4 if you're using the GitHub pack or the 'easiest' ways using the nightly build or launch. 
I just wished people were reading the whole blog post and don't stop at the download button ;)

**Comment by ghost** [comment]
@Sandra97 Locate "Download"-Button at bottom ;-)

**Comment by ReLater** [comment]
And/Or place a more prominent comment concerning advantages of nightly builds because regular alphas are outdated after some hours at the moment.

**Comment by bjxrn** [comment]
Speaking just for myself, even after reading the whole post it is not obvious to me that I should have downloaded the nightly. Especially with several links to the alpha with text saying that the release is for testing.

The section about Joomla 4 Testing starts off with a paragraph about setting up a development environment (which isn't what I'm looking for). And yes, then there is a sentence mentioning the nightly after that, but nothing that indicates that this is somehow the version that takes precedence over the alpha linked at the top of the post.

Would it perhaps be better to just mention the alpha in general terms, but have the download button say something like "latest version" and link to the nightly instead?

**Comment by Sandra97** [comment]
We'll see to do it in a different way for the Alpha 6 post. Thanks for your feedback.

**Comment by bjxrn** [comment]
Thank _you_. I'm very grateful for all the hard work being done both on the code as well as everything around it (including the release announcements).
