### ISSUE TITLE
Users in back-end are logged out before end of session intermittently

### ISSUE THREAD

**Issue by Chaosxmk** [joomla/joomla-cms#22959]
### Steps to reproduce the issue
- Log into back-end
- Navigate around

### Expected result
User stays logged in so long as they continue performing actions before session expires

### Actual result
Occasionally, user is logged out even when session has yet to expire. No error/warning message is given (ie. `Warning! Your session has expired. Please log in again.`)

### System information (as much as possible)
```
Setting | Value
PHP Built On | Linux site.ca 3.10.0-714.10.2.lve1.5.19.3.el7.x86_64 #1 SMP Tue Aug 7 21:33:29 EDT 2018 x86_64
Database Type | mysql
Database Version | 5.5.5-10.1.26-MariaDB
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 5.6.31
Web Server | LiteSpeed
WebServer to PHP Interface | litespeed
Joomla! Version | Joomla! 3.9.0 Stable [ Amani ] 30-October-2018 14:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3602.2 Safari/537.36
```
```Configuration File
Setting | Value
offline | 0
offline_message | Ce site est en maintenance.<br /> Merci de revenir ultérieurement.
display_offline_message | 1
offline_image | 
sitename | Site name
editor | tinymce
captcha | recaptcha
list_limit | 20
access | 1
debug | 0
debug_lang | 0
dbtype | mysqli
host | xxxxxx
user | xxxxxx
password | xxxxxx
db | xxxxxx
dbprefix | xxxxxx
live_site | 
secret | xxxxxx
gzip | 1
error_reporting | default
helpurl | https://help.joomla.fr/index.php?option=com_help&keyref=Help{major}{minor}:{keyref}
ftp_host | 
ftp_port | 
ftp_user | xxxxxx
ftp_pass | xxxxxx
ftp_root | 
ftp_enable | 0
offset | America/New_York
mailonline | 1
mailer | mail
mailfrom | xxxxxx
fromname | xxxxxx
sendmail | /usr/sbin/sendmail
smtpauth | 0
smtpuser | xxxxxx
smtppass | xxxxxx
smtphost | localhost
smtpsecure | none
smtpport | 25
caching | 0
cache_handler | file
cachetime | 15
cache_platformprefix | 0
MetaDesc | 
MetaKeys | 
MetaTitle | 1
MetaAuthor | 1
MetaVersion | 0
robots | 
sef | 1
sef_rewrite | 1
sef_suffix | 0
unicodeslugs | 0
feed_limit | 10
feed_email | none
log_path | /home/site/domains/site.com/public_html/administrator/logs
tmp_path | /home/site/domains/site.com/public_html/tmp
lifetime | 70
session_handler | database
shared_session | 0
memcache_persist | 1
memcache_compress | 0
memcache_server_host | localhost
memcache_server_port | 11211
memcached_persist | 1
memcached_compress | 0
memcached_server_host | localhost
memcached_server_port | 11211
redis_persist | 1
redis_server_host | localhost
redis_server_port | 6379
redis_server_auth | 
redis_server_db | 0
proxy_enable | 0
proxy_host | 
proxy_port | 
proxy_user | 
proxy_pass | 
massmailoff | 0
replyto | 
replytoname | 
MetaRights | 
sitename_pagetitles | 1
force_ssl | 0
session_memcache_server_host | localhost
session_memcache_server_port | 11211
session_memcached_server_host | localhost
session_memcached_server_port | 11211
session_redis_persist | 1
session_redis_server_host | localhost
session_redis_server_port | 6379
session_redis_server_auth | 
session_redis_server_db | 0
frontediting | 0
cookie_domain | 
cookie_path | 
asset_id | 1
debug_lang_const | 1
```

### Additional comments
This bug has been really bothersome. I can;t pinpoint an exact action that causes it, it just seems to be random. Although, I've noticed I get logged out far more frequently when trying to check for updates/perform updates. Not sure if it's coincidental or related.

**Comment by chmst** [comment]
There are several user in the german joomla forum with the same problem. 

Here a automatic tranlated post- maybe it conains useful information:

Already since Joomla 3.6 I have the problem that I am logged out again and again, as if a session timeout would take place. This problem occurs meanwhile with three separate Joomla installations, which are separated by quota on the server. All pages are on Joomla 3.9

Example for the error: I write e.g. as admin in the backend texts in a post and click on save. Buff, already I see only the login mask for the backend. And of course the entered text is gone and the post is marked with the black small lock symbol as not closed correctly.

This "logout" can take place during any action, e.g. when I switch from the HTML editor window to the code window or when I click on different functions in the backend, such as a category or a menu, etc. It should therefore not be JCE editor related.

So far this didn't happen so often and I thought that it might be gone with the next Joomla update. But now with Joomla 3.9 it has become so common that I can't work properly anymore!

Translated with www.DeepL.com/Translator<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22959">issues.joomla.org/tracker/joomla-cms/22959</a>.</sub>

**Comment by csthomas** [comment]
You probably have a session race as you are logged as Super User. 

You could temporary disable a plugin (you will not be informed about new updates):
- Quick Icon - Joomla! Update Notification

and check again.

There are more ajax calls that can reset session data, but this is more important.
Another way is to login as a non Super User, then the updates are not checked.

**Comment by brianteeman** [comment]
sounds like there might be an issue with jce not triggering the keepalive. can these users replicate the issue with tinymce

**Comment by Chaosxmk** [comment]
Assuming you're referring to editors, I can confirm this occurs (intermittently mind you) with TinyMCE active and no editor.

Even without the plugin `Quick Icon - Joomla! Update Notification` active, I've still encountered this issue.

**Comment by Chaosxmk** [comment]
I've deactivated both plugins that perform update checks, `Quick Icon - Joomla! Update Notification` and `Quick Icon - Joomla! Extensions Updates Notification` at the start of the week to see if maybe they were related. Thus far, I haven't experienced any instances of being logged out from valid sessions. Is it possible one of the two (or possibly both) break the session if their respective ajax calls aren't finished?

**Comment by duckpmsf** [comment]
I have the same problema.
I'm using PHP 7.1 and the joomla version is 3.9.4.

Can someone help me regarding this situation?

Regards
Paulo

**Comment by duckpmsf** [comment]
Hi all,

Can you please help me regarding this subject?

Best Regards
Paulo

**Comment by ghost** [comment]
@duckpmsf it needs a Dev. having Time and Interest to investigate an Issue.

**Comment by Chaosxmk** [comment]
The problem is also that the bug is intermittent. Despite opening this issue months ago, since January I have yet to experience it again.

**Comment by brianteeman** [comment]
I would file it down to the magic fairies and move on.

**Comment by ghost** [comment]
closed as stated above; Issue can always be reopened.
