### ISSUE TITLE
com actionlog, unpublish missing language string

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#22951]
### What needs to be fixed
If you unpublish action log plugin this appears in control center.
<img width="423" alt="grafik" src="https://user-images.githubusercontent.com/43232309/48088095-5abd4c00-e201-11e8-85af-0d439a903443.png">

It would be also good if it would dissapear from control center. Otherwise you have to hide so much modules in versions 3.9+ if you dont need this privacy tool

**Comment by ReLater** [comment]
There's a pr for the untranslated strings that needs tests. It solves your issue.
https://github.com/joomla/joomla-cms/pull/22282
