### ISSUE TITLE
Modules in Content menu, instead of System menu

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#22950]
### Steps to reproduce the issue

Checking the latest J 4.0.0-alpha5, I'm finding that Site and Admin Modules are shown prominently in the Content menu (after the Fields/Field Groups).

### Expected result

The new System menu must include the Site and Admin Modules items. The modules are indeed part of the internal system and must not be shown to the users who enter new content.

BTW: Fields/Field Groups should also be in the System panel along the rest of the internal/advanced system configuration.

### Actual result

Site and Admin Modules are shown prominently in the Content menu

### System information (as much as possible)

J 4.0.0-alpha5

**Comment by brianteeman** [comment]
this is by design and the intended behaviour

**Comment by anibalsanchez** [comment]
Yes, I understand that it has been defined in this way. However, it is odd finding the modules inside the Content menu. We already had to explain the Fields/Field Groups... now we are getting the Modules (Front and Back) in the Content menu. If we keep going in this direction, Plugins are also going to appear in the Content menu.

Backend Modules are mostly hidden and unknown to most users today. So, showing Admin Modules in the Content menu is going to be at least surprising.

Better, if we review the definition now, and we move back all the system stuff inside the new System panel.

**Comment by brianteeman** [comment]
It was not a random decision by an individual who just did it. This was a very specific request from the UX team (when it existed)

**Comment by anibalsanchez** [comment]
It would be great if the UX responsible explains the reasoning behind the decision. I'm sure that I'm not going to be the only one noticing the change.

**Comment by brianteeman** [comment]
Its here on github - search and ye shall find

**Comment by infograf768** [comment]
There is no reason imho not to also add the Modules manager in the System Panel dashboard under the Manage group —whatever one thinks about the presence of the modules as a sub of Content.
We already do that for the Joomlaupdate component, Users Groups and Levels and com_redirect.

**Comment by infograf768** [comment]
Will do patch.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/22957
closing as we have a patch
