### ISSUE TITLE
Joomla 4 Update nightly problem with url

### ISSUE THREAD

**Issue by JKouvakis** [joomla/joomla-cms#22958]
### Steps to reproduce the issue
With Custom URL Update Channel
https://update.joomla.org/core/nightlies/next_major_list.xml
i get "https://developer.joomla.org/nightlies/Joomla_4.0.0-alpha5-dev-Development-Update_Package.zip" which is 404 and the correct url from https://developer.joomla.org/nightly-builds.html is "https://developer.joomla.org/nightlies/Joomla_4.0.0-alpha5-Alpha-Update_Package.zip" without "-dev"

**Comment by mbabker** [comment]
@wilsonge bump the version string and update the update server XML.

**Comment by mbabker** [comment]
Fixed

**Comment by wilsonge** [comment]
Thankyou! sorry just got to this
