### ISSUE TITLE
[3.9.1] Plugin manager. Can't activate/deactivate plugins with click on icons.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#22952]
### Steps to reproduce the issue
- Install nightly 3.9.1 Tuesday, 06 November 2018 03:00:19 UTC
- Go to `Extensions` > `Plugins`
- Try to activate or deactivate plugins by clicking on icons.
- Page reloads but Status of plugin doesn't change.

### Additional comments
Open plugin and change `Status` and `Save` works as expected.

**Comment by Quy** [comment]
@dneukirchen Side-effect of PR #22851

**Comment by dneukirchen** [comment]
Jap. The used Table `Joomla\CMS\Table\Extension` has no column alias for the published column, but it should have one.

**Comment by Quy** [comment]
Please test PR #22953<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22952">issues.joomla.org/tracker/joomla-cms/22952</a>.</sub>
