### ISSUE TITLE
[4.0] Select the database type duplicated

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22964]
### Steps to reproduce the issue

Database configuration page of the Joomla 4 installer

>commit 2a76a1d930d617773c80b2c9eee5d5605918e8e2 (HEAD -> 4.0-dev, origin/4.0-dev)

### Expected result

For either no help text, or help text that is helpful and not just a duplicate of the form field label.

### Actual result

> Select the database type

![screenshot 2018-11-08 at 05 28 28](https://user-images.githubusercontent.com/400092/48179528-921e1c80-e317-11e8-9042-2186a38b12ba.png)

**Comment by puneeth-chanda** [comment]
What do you actually want to change?, I am sorry that I could not get you here "not just a duplicate of the form field label.", Can you please say it clearly.

**Comment by PhilETaylor** [comment]
Help text should HELP.  Simply repeating the same as the form field label is not helping. Either the help text should be improved or removed.

I’m no expert. But saying the same thing above and below a form field is not needed and can and should be improved 

——
Sent from my iPhone - sorry - if needed I’ll send longer email from my desk later.
——

**Comment by puneeth-chanda** [comment]
ok i got it
can you suggest me what should I put there instead of this??

**Comment by Bakual** [comment]
The help text can be deleted without replacement. Or if you want to have one it should be a helpful text eg "If you're unsure what to choose, try with MySQL as it is the most common type or ask your hosting company."

**Comment by Quy** [comment]
Please test PR #23705<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22964">issues.joomla.org/tracker/joomla-cms/22964</a>.</sub>

**Comment by puneeth-chanda** [comment]
is my PR merged??

**Comment by Bakual** [comment]
> is my PR merged??

No, but we regulary close the issue if there is a PR open for it.

**Comment by puneeth-chanda** [comment]
ok fine thanks
