### ISSUE TITLE
Mail Disabled notification type wrong

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#22960]
When you disable mailing from the Joomla! config you are shown this message when logging in:
<img width="645" alt="screenshot 2018-11-07 22 46 38" src="https://user-images.githubusercontent.com/1400982/48166008-3b94ec00-e2df-11e8-9b80-1dfb249dc800.png">

Shouldn't we be present with a warning message rather than a success message given we haven't successfully done anything? It's more  a notice/warning?

Many thanks
Tony

**Comment by brianteeman** [comment]
You should only get that if joomla is trying to send an email

**Comment by tonypartridge** [comment]
But still, it shows a success colour. It wasn’t a success trying to send anything?

Many thanks
Tony

**Comment by Quy** [comment]
Please test PR #24256<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22960">issues.joomla.org/tracker/joomla-cms/22960</a>.</sub>
