### ISSUE TITLE
[4.0] Wrong error on connecting to mysql

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22961]
### Steps to reproduce the issue

Attempt to install Joomla 4 from 4.0-dev branch
make a typo in the db password

### Expected result

A sensible error message

### Actual result

A message that tells me the connector returned a number, and then a string instead of a number
![screenshot 2018-11-08 at 05 16 23](https://user-images.githubusercontent.com/400092/48179127-79ad0280-e315-11e8-808f-14b91044e016.png)

> Could not connect to the database. Connector returned number: Could not connect to database.

**Comment by hardik-codes** [comment]
What should be the correct error message then @PhilETaylor

**Comment by PhilETaylor** [comment]
I thought that would be obvious.

As I said: "A message that tells me the connector returned a number, and then a string instead of a number"

So either you should tell me the "returned number" from mysql or you should tell me a sentence and remove the string that says you are telling me the "connector returned number"

**Comment by hardik-codes** [comment]
In my humble opinion the number is irrelevant for the user. So we can change the error message directly. Is that Ok with you @PhilETaylor

**Comment by PhilETaylor** [comment]
Not up to me which way it goes. But whatever it changes to it should make sense. 

However the error number can be important as its more specific than "cannot connect"

**Comment by hardik-codes** [comment]
Could you possibly tell me why this is not working ```Could not connect to the database. Connector returned number: %s"```  in ```/installation/language/en-GB/en-GB.ini``` and in similar files.
Why does ```%s ``` not works here??

**Comment by Quy** [comment]
Please test PR #23759<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22961">issues.joomla.org/tracker/joomla-cms/22961</a>.</sub>
