### ISSUE TITLE
[4.0] panel not centered in admin console

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22965]
### Steps to reproduce the issue

Install Joomla 4 from 

> commit 2a76a1d930d617773c80b2c9eee5d5605918e8e2 (HEAD -> 4.0-dev, origin/4.0-dev)

Login to admin

### Expected result

The Joomla stats blue dialog to be centered.

### Actual result

![screenshot 2018-11-08 at 05 38 23](https://user-images.githubusercontent.com/400092/48179745-867f2580-e318-11e8-814b-0a0a74ed8f47.png)

### System information (as much as possible)

Google Chrome

**Comment by PhilETaylor** [comment]
looks like a generic issue with these info/warning/alerts 

![screenshot 2018-11-08 at 05 50 55](https://user-images.githubusercontent.com/400092/48180159-5afd3a80-e31a-11e8-9d17-9d232bf9c717.png)

**Comment by C-Lodder** [comment]
It was decided to have the alerts displayed in the center of the main container, due to the sidebar being collapsible.

**Comment by brianteeman** [comment]
Closed as intended behaviour

**Comment by PhilETaylor** [comment]
This makes literally no sense!

The left menu is not collapsed by default

The alerts should be central regardless of the menu collapse state. 

Wide screen monitors are the norm nowadays- hardly anyone needs or wants a collapsible left menu

**Comment by mbabker** [comment]
> Wide screen monitors are the norm nowadays- hardly anyone needs or wants a collapsible left menu

You don't use a 13" laptop frequently then, where screen real estate is still valuable.  You don't work with clients who are frequently on the go and working with smaller laptops or tablets.  Assuming the vast majority is running primarily on 1080p+ displays is really short sighted.

**Comment by PhilETaylor** [comment]
It still makes no sense that we cannot center the dialog regardless of the state of the left menu.  It’s simple maths right? 

OCD lovers will hate this offsetting the right all the time!

**Comment by C-Lodder** [comment]
@PhilETaylor If I rightly remember, it was decided so that the alerts were always in the center of the main content (excluding the sidebar) as opposed to the entire viewport.

I don't know which is best but definitely keep this issue open to discussion.

**Comment by PhilETaylor** [comment]
That decision is literally insane.

If you are on a small screen, small enough to warrant collapsing the left menu, then the last thing you want is the dialogs to be EVEN MORE offset to the right on your small screen.

**Comment by PhilETaylor** [comment]
> Closed as intended behaviour

Please reopen this issue.
