### ISSUE TITLE
[4.0] Crazy Admin Action buttons Width

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22969]
Im sure this is probably a WIP or one of those where people disagree again, and I know I have raised this repeatedly over the 4.0 cycle, and multiple people have addressed it over time, but we are now in Alpha and this is still an issue today. 

In order to get the following screenshot, I need a browser width of 1660px. Anything smaller and the buttons wrap making the page look horrible. 

![screenshot 2018-11-08 at 05 59 07](https://user-images.githubusercontent.com/400092/48180444-6c931200-e31b-11e8-9f12-7375353a7719.png)

I have a 27" iMac (the one Im using is an older one with 2560x1440 resolution, using half the screen for the browser I get 1280px browser width - this looks like this:

![screenshot 2018-11-08 at 05 59 25](https://user-images.githubusercontent.com/400092/48180486-964c3900-e31b-11e8-9e6f-873bf4616a1b.png)

As you can see the buttons are wrapping and overlapping.

We can do better than this :)

**Comment by infograf768** [comment]
We should also take in consideration the fact that in some languages, the texts may be much longer...

**Comment by ciar4n** [comment]
#22393 should resolve this for com-content. It just requires a test.

**Comment by brianteeman** [comment]
Closed as there is a pr that needs testing
