### ISSUE TITLE
[4.0] Actual text color not clear

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22962]
### Steps to reproduce the issue

Last page of Joomla 4 installation

> commit 2a76a1d930d617773c80b2c9eee5d5605918e8e2 (HEAD -> 4.0-dev, origin/4.0-dev)

### Expected result

Orange warnings to be very clear and readable 

### Actual result

What looks like black on a rust colour, almost brown background
![screenshot 2018-11-08 at 05 21 59](https://user-images.githubusercontent.com/400092/48179293-677f9400-e316-11e8-863b-ba62e2550f03.png)

**Comment by C-Lodder** [comment]
This is part of Bootstrap's colour mixing. It sets the text colour for certain components depending on their background colour. Will have to be overriden or just have somne custom badges.

**Comment by hardik-codes** [comment]
How do we check our changes since the installation is a one time process. Do we have to install again and again to check for our changes done?

**Comment by hardik-codes** [comment]
I think the above concerned is related to the file ```administrator/components/com_admin/tmpl/sysinfo/default_phpsettings.php```. If I'm wrong please let me know.

**Comment by C-Lodder** [comment]
@hardik-codes Just delete the `configuration.php` file and this will allow you to install Joomla again
