### ISSUE TITLE
[4.0] table options dropdowns placeholder weirdness

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22966]
### Steps to reproduce the issue

Install Joomla 4.0 at 

> commit 2a76a1d930d617773c80b2c9eee5d5605918e8e2 (HEAD -> 4.0-dev, origin/4.0-dev)

Login to admin
Select Articles from left menu
Select Table Options dropdown 

### Expected result

Placeholders in all dropdowns

### Actual result

Something weird, the dropdowns are blank on first load, then appear after messing around with it.

![screen recording 2018-11-08 at 05 43 am](https://user-images.githubusercontent.com/400092/48179899-35236600-e319-11e8-9b6c-802c84264f68.gif)

### System information (as much as possible)

Google Chrome Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by brianteeman** [comment]
Closed as a known issue. Will be solved when the choices pr is merged
