### ISSUE TITLE
[4.0][JS] Cannot read property 'addEventListener' of undefined

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22967]
### Steps to reproduce the issue

Install Joomla 4.0 at 

> commit 2a76a1d930d617773c80b2c9eee5d5605918e8e2 (HEAD -> 4.0-dev, origin/4.0-dev)

Navigate to http://example.com/administrator/index.php?option=com_menus&view=menus

### Expected result

No JS error

### Actual result

> admin-menus-default.min.js?9e052d5056f44c7819c84ab6e5d16a50:1 Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at HTMLDocument.<anonymous> (admin-menus-default.min.js?9e052d5056f44c7819c84ab6e5d16a50:1)

**Comment by infograf768** [comment]
Confirmed.

**Comment by laoneo** [comment]
Please test #23062 which should fix the issue.
