### ISSUE TITLE
Notice: Undefined index: option in components/com_content/views/article/view.html.php on line 253 and 245

### ISSUE THREAD

**Issue by markovanderpuil** [joomla/joomla-cms#22973]
Here's an example of the issue: [Joomla Project](http://cg.noacsc.org/parents-students/calendars/lunchmenu/19-sample-data-articles/joomla/48-the-joomla-project)

Apparently a lot of users have this issue: [If you google: joomla Notice: Undefined index: option in view.html.php line 245 253](https://www.google.com/search?hl=nl&ei=IzrkW6DrMMbGwQKH7pDwCA&q=joomla+Notice%3A+Undefined+index%3A+option+in+view.html.php+line+245+253&oq=joomla+Notice%3A+Undefined+index%3A+option+in+view.html.php+line+245+253&gs_l=psy-ab.3...0.0.0.1535.0.0.0.0.0.0.0.0..0.0....0...1c..64.psy-ab..0.0.0....0.1dKF-GiozJQ)

This is probably related to using "fixed" urls where there is no query option in the menu item. I'm using a very popular plugin 'sh404sef' to get search engine friendly urls. Apparently this causes the option key to be dropped from menu->query.

### Expected result

It should not show the notices.

### Actual result

The following Notices show on the page:
`Notice: Undefined index: option in D:\xampp\htdocs\joomla\components\com_content\views\article\view.html.php on line 245

Notice: Undefined index: option in D:\xampp\htdocs\joomla\components\com_content\views\article\view.html.php on line 253

Notice: Undefined index: option in D:\xampp\htdocs\joomla\components\com_content\views\article\view.html.php on line 253

Notice: Undefined index: option in D:\xampp\htdocs\joomla\components\com_content\views\article\view.html.php on line 253`

### System information (as much as possible)

Windows & Linux. PHP 7.2 possibly others.

### Additional comments

I would suggest checking with:
`isset($menu->query['option'])`
on lines 245 and 253

I haven't contributed yet, but I could try and make a pull request for this.

**Comment by SharkyKZ** [comment]
sh404sef is known for generating invalid URLs. In this case it's adding System Link type menu item ID to internal URLs. Does this issue need fixing in core if it can only be reproduced by manually altering the URL?

**Comment by markovanderpuil** [comment]
I was thinking the same thing, is it okay if Joomla generates notices if the url is changed? (manually or by a plugin/module)

**Comment by mbabker** [comment]
Honestly, if an extension is manipulating the core data structure and removing what can be considered mandatory bits of data, then I would call it a bug in those extensions and not something that core needs to defensively code around.

**Comment by PhilETaylor** [comment]
I would say that the core has to handle this - regardless of its cause. Because not handling it can output error messages to the screen - Joomla has proudly developed to standards that dont output warnings like this and can run with error_reporting on maximum 

The [example given](http://cg.noacsc.org/parents-students/calendars/lunchmenu/19-sample-data-articles/joomla/48-the-joomla-project) shows that Joomla is outputting a warning with the full path to the site - a minor information disclosure 

For the sake of a simple isset or array_key_exists check...

**Comment by PhilETaylor** [comment]
PR https://github.com/joomla/joomla-cms/pull/23045
