### ISSUE TITLE
[4.0] Alpha 5 installer works fine, no errors, but site is "Empty"!

### ISSUE THREAD

**Issue by rotech1** [joomla/joomla-cms#22974]
### Steps to reproduce the issue
install as per usual instructions
choose the add sample data option

### Expected result
working site for testing

### Actual result
Empty frontend!
Empty backend! ( no menus, no modules)

### System information (as much as possible)
Apache/2.4.6 (CentOS) PHP/7.1.23
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407
PHP extension: mysqli curl mbstring 
PHP version: 7.1.23
MySQL Server version: 8.0.13 - MySQL Community Server - GPL
(this same apache server / SQL server currently runs a J3.9 installation just fine)

### Additional comments
screen shot of front end / back end at https://forum.joomla.org/viewtopic.php?f=803&t=967064

**Comment by rotech1** [comment]
UPDATED with FPA output ( see forum thread https://forum.joomla.org/viewtopic.php?f=803&t=967064&p=3547996#p3547996 )<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22974">issues.joomla.org/tracker/joomla-cms/22974</a>.</sub>

**Comment by csthomas** [comment]
I assume that you have mysql 5.7 or newer.

There is a problem with zero dates. 
If you replace (in phpmyadmin) the zero dates `0000-00-00 00: 00: 00` by` 1000-00-00 00: 00: 00` in the `#__ modules` table, then the modules should appear.

This PR may help too https://github.com/joomla/joomla-cms/pull/21901

**Comment by rotech1** [comment]
Thanks!
running SQL 8…

but setting all the zero dates starting with 1000 doesn't improve the situation here... still no modules or menus in either front or backend.

**Comment by rotech1** [comment]
**Here is a clue, perhaps... (??)

pasted URL for check database, it sent back this:**

-----------------------------------------------


`Table 'j40a5_modules' has the wrong type or attributes for column 'content' with type TEXT. (From file 4.0.0-2018-03-05.sql.)

Table 'j40a5_finder_terms' has the wrong type or attributes for column 'language' with type CHAR(7). (From file 4.0.0-2018-04-14.sql.)

Table 'j40a5_finder_terms_common' has the wrong type or attributes for column 'language' with type CHAR(7). (From file 4.0.0-2018-04-14.sql.)

Table 'j40a5_finder_tokens' has the wrong type or attributes for column 'language' with type CHAR(7). (From file 4.0.0-2018-04-14.sql.)

Table 'j40a5_finder_tokens_aggregate' has the wrong type or attributes for column 'language' with type CHAR(7). (From file 4.0.0-2018-04-14.sql.)

Table 'j40a5_finder_links' has the wrong type or attributes for column 'language' with type CHAR(7). (From file 4.0.0-2018-04-14.sql.)

18 database changes were checked.

41 database changes did not alter table structure and were skipped.`

**Incidentally, my (perfectly running) 3.8.13 install (on the same server,using MySQL8)  also reports some db problems (but in 3.8.13 the functionality of the front and back end are both 100% perfect)... here are the 3.8.13 errors:**

`Table 'j38_languages' has the wrong type or attributes for column 'sitename' with type VARCHAR(1024). (From file 2.5.0-2012-01-14.sql.)

Table 'j38_associations' has the wrong type or attributes for column 'id' with type INT(11). (From file 3.0.3.sql.)
Table 'j38_user_profiles' has the wrong type or attributes for column 'profile_value' with type TEXT. (From file 3.3.4-2014-08-03.sql.)

Table 'j38_redirect_links' has the wrong type or attributes for column 'old_url' with type VARCHAR(2048). (From file 3.5.0-2016-03-01.sql.)

Table 'j38_redirect_links' has the wrong type or attributes for column 'new_url' with type VARCHAR(2048). (From file 3.5.0-2016-03-01.sql.)

Table 'j38_redirect_links' has the wrong type or attributes for column 'referer' with type VARCHAR(2048). (From file 3.5.0-2016-03-01.sql.)

Table 'j38_redirect_links' has the wrong type or attributes for column 'new_url' with type VARCHAR(2048). (From file 3.6.0-2016-04-06.sql.)

Table 'j38_newsfeeds' has the wrong type or attributes for column 'link' with type VARCHAR(2048). (From file 3.6.3-2016-08-15.sql.)

Table 'j38_extensions' has the wrong type or attributes for column 'enabled' with type TINYINT(3). (From file 3.7.0-2016-11-04.sql.)

Table 'j38_modules' has the wrong type or attributes for column 'content' with type text. (From file 3.7.0-2016-11-27.sql.)

Table 'j38_ucm_content' has the wrong type or attributes for column 'core_body' with type mediumtext. (From file 3.7.0-2017-01-08.sql.)

Table 'j38_ucm_content' has the wrong type or attributes for column 'core_params' with type text. (From file 3.7.0-2017-01-08.sql.)

Table 'j38_ucm_content' has the wrong type or attributes for column 'core_images' with type text. (From file 3.7.0-2017-01-08.sql.)

Table 'j38_ucm_content' has the wrong type or attributes for column 'core_urls' with type text. (From file 3.7.0-2017-01-08.sql.)

Table 'j38_ucm_content' has the wrong type or attributes for column 'core_metakey' with type text. (From file 3.7.0-2017-01-08.sql.)

Table 'j38_ucm_content' has the wrong type or attributes for column 'core_metadesc' with type text. (From file 3.7.0-2017-01-08.sql.)

Table 'j38_categories' has the wrong type or attributes for column 'description' with type mediumtext. (From file 3.7.0-2017-01-09.sql.)

Table 'j38_categories' has the wrong type or attributes for column 'params' with type text. (From file 3.7.0-2017-01-09.sql.)

Table 'j38_finder_links' has the wrong type or attributes for column 'description' with type text. (From file 3.7.0-2017-03-19.sql.)`

-------

PS: the Fix button in J3.8.13 has no effect on the above errors...

**Comment by rotech1** [comment]
UPDATED: I once again tried the update 

UPDATE `#__modules` SET `checked_out_time` = '1000-01-01 00:00:00', `publish_up` = '1000-01-01 00:00:00', `publish_down` = '1000-01-01 00:00:00';

**And the back end IS WORKING  this time ( very odd, as I had run that before to no avail..) As is the front end. Maybe just because I had applied the Alpha 6 update??**

Incidentally, the same db errors are noted as above ( for J4) and  "Fix" button doesn't fix them...

**Comment by ghost** [comment]
closed in favor of #24151<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22974">issues.joomla.org/tracker/joomla-cms/22974</a>.</sub>
