### ISSUE TITLE
[4.0] Updates are available! 1

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22978]
### Steps to reproduce the issue

Install old extension for Joomla 4 
Sample file http://screenshot.myjoom.la/568113a08854
Go to Joomla 4 admin

### Expected result

text of "1 Updates are available" 
or
Updates are available (1) where the 1 is a bubble in red with text white floated top right maybe

I dont have the eye for how it should be, only that it currently is not the best it can be. 

### Actual result

![screenshot 2018-11-09 at 15 10 54](https://user-images.githubusercontent.com/400092/48270408-e61d2400-e431-11e8-9aed-017954c3f327.png)

Note that the grey badge (1) gets lost and looks strange.

-----

Also the popover alert has text 

![screenshot 2018-11-09 at 15 08 02](https://user-images.githubusercontent.com/400092/48270556-3f855300-e432-11e8-932f-429df94fe8c4.png)

> (1) Extension Update(s) are available:

I suggest that this could be a dynamic string to incorprate the number into the actual sentance to remove the (s) plurarlizer and remove the :

so eg

> 1 Extension update is available

> 100 Extension updates are available

**Comment by PhilETaylor** [comment]
@infograf768 Is this one covered by your excellent work this week?

**Comment by infograf768** [comment]
I did not change that order in https://github.com/joomla/joomla-cms/pull/23095 
Waiting for tests to get it merged asap... Please do.
We can change the order after that merge if desired quite easily, but not the plural forms.

I had though a discussion about implementing plural forms in JS and it looks like it is impossible.
To see the discussion look at https://github.com/joomla/joomla-cms/pull/23061
