### ISSUE TITLE
For more information on warnings, see the Joomla! Documentation Site.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22987]
### Steps to reproduce the issue

On this page /administrator/index.php?option=com_joomlaupdate there is the text 

> For more information on warnings, see the Joomla! Documentation Site.

### Expected result

That the link goes to the documentation site which is full of help to do with the warnings

### Actual result

That the link goes to the documentation site which has **zero help about the warnings**

Recommend removing this part of the accordion as its factually incorrect and misleading. Thoughts?

Or will someone offer to write the documentation after all these years (doubt it, no one has after all these years)

**Comment by mbabker** [comment]
"This is undocumented, we should remove references to the documentation instead of writing the documentation".

Because that makes sense.

Wait, that's the easy way out.  For some people, that does seem to be the preferred solution to Joomla issues 🤔

**Comment by PhilETaylor** [comment]
Its been this way for years :) a link that says "go here for help" only for the user to end up on a site that has zero help :)
