### ISSUE TITLE
[3.9] navigating to first page in pagination not possible with SEF urls disabled

### ISSUE THREAD

**Issue by hendrikbehncke** [joomla/joomla-cms#22983]
### Steps to reproduce the issue
Disable SEF URLs in the global configuration.
Navigate through the blog articles with the pagination. 
It is not possible to get back to first page, the url will always contain the current `limitstart=` value

### Expected result
Navigating back to first page

### Actual result
It's not possible to navigate to the first page

### System information (as much as possible)
Joomla 3.9.0 stable
Protostar template
Blog demo content

### Additional comments
Not sure but maybe caused by this PR https://github.com/joomla/joomla-cms/pull/19467

The Router will add the current URL parameters to the created pagination link.

**Comment by csthomas** [comment]
Try this patch.

```diff
diff --git a/libraries/src/Pagination/Pagination.php b/libraries/src/Pagination/Pagination.php
index df4c0600e7..bdf53e0247 100644
--- a/libraries/src/Pagination/Pagination.php
+++ b/libraries/src/Pagination/Pagination.php
@@ -771,6 +771,12 @@ class Pagination
                // Build the additional URL parameters string.
                $params = '';
 
+               if ($this->app->input->get('limitstart') !== null)
+               {
+                       // Reset limitstart parameter if exists
+                       $params = '&' . $this->prefix . 'limitstart=';
+               }
+
                if (!empty($this->additionalUrlParams))
                {
                        foreach ($this->additionalUrlParams as $key => $value)
```

**Comment by csthomas** [comment]
Please test #23042
