### ISSUE TITLE
[4.0] Update Warnings Not Clear

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22986]
### Steps to reproduce the issue

Install Joomla 4.0-dev
Login to admin and navigate to the Joomla update component

### Expected result

Normally you will see at least one warning in my experience, they are in an accordion. 

I expect that the display will look good, making clear what I see are the headers of an accordion that can be clicked, and clear when they are clicked. The first item in the accordion is closed in 4.0 and open in 3.x

### Actual result

Everything is flat on a white background and doesn't give any indication they can be clicked.

![screen recording 2018-11-09 at 07 56 pm](https://user-images.githubusercontent.com/400092/48285168-9e11f780-e459-11e8-9004-03a0a701fdb0.gif)

(compared to Joomla 3.9.0 below)

![screenshot 2018-11-09 at 19 57 28](https://user-images.githubusercontent.com/400092/48285195-bb46c600-e459-11e8-85e9-826a6181f106.png)

**Comment by infograf768** [comment]
My experience here (as I had to cope with this in com_localise), is that we miss a css:
when we use `HTMLHelper::_('bootstrap.addSlide'` we get the class `class="card-header` for the slide and `class="accordion"` for the `<div>`.
therefore we do need for example:
```
.accordion .card-header {
    background-color: #cfe6e9;
    something
    something else
}
```

**Comment by mbabker** [comment]
No, the use of Bootstrap elements needs to be corrected.  I don't know who decided to misuse the Card component's header class in incompatible contexts but that needs to be corrected, not furthered upon (if it's not wrapped in `<div class="card">` then none of Bootstrap's `card-*` classes should be used, I'm looking at you module chromes...).

**Comment by C-Lodder** [comment]
@mbabker I dont see any misuse of the card component here. It's purely a styling related component and has no JS associated with it, nor do the classes affect a11y.

It's simply due to the fact the background has been set to transparent:

https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/scss/_variables.scss#L139

**Comment by mbabker** [comment]
Well then things have changed because there was a point where `.card-header` was being used with modules with no sort of wrapping `.card` anywhere.  And to me that is misuse, even if it is "purely a styling related component".

**Comment by C-Lodder** [comment]
Ahh in that aspect
