### ISSUE TITLE
 Select here to see the information that will be sent.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#22980]
### Steps to reproduce the issue

Edit Joomla stats plugin

### Expected result

Sensible English

A "click" is not a "select", you select an option from a dropdown, you click a link

There is no reason to hide the data to start with? Just show it and remove the link?

### Actual result

> 
Select here to see the information that will be sent. 

![screenshot 2018-11-09 at 15 32 35](https://user-images.githubusercontent.com/400092/48271708-d2bf8800-e434-11e8-8767-20ca9b4706b2.png)

### Additional comments

related to https://github.com/joomla/joomla-cms/issues/20557 but not a duplicate

**Comment by mbabker** [comment]
You can't "click" anything when you're using a touch screen device.

**Comment by mbabker** [comment]
Refs:

- https://github.com/joomla/joomla-cms/pull/19310
- https://github.com/joomla/joomla-cms/pull/7430

**Comment by PhilETaylor** [comment]
"select" also has a totally different meaning on a mobile device :) 

"click" is the more commonly accepted internet term for pressing a link

You "select" from a list of things.

You "click/press/touch" a link

You do not "select" a link to trigger a hide show

**Comment by PhilETaylor** [comment]
Also "Click here... to do something" is so 1990s... 

https://www.smashingmagazine.com/2012/06/links-should-never-say-click-here/

**Comment by mbabker** [comment]
Without device detection and unique language strings, you are not going to create verbiage that is correct for all devices.  You cannot "click" a link on a touch screen device, and you do not "press" a link when using a mouse.

> where "view the information that will be sent" is hyperlinked.

Isn't that nothing more than a "click here to do something" link in alternative text?
