### ISSUE TITLE
issue in relation to incorrect display of breadcrumbs, sitemap and url's

### ISSUE THREAD

**Issue by quichot** [joomla/joomla-cms#22982]
### Steps to reproduce the issue
tested wite joomla 3.9.0
template protostar

Situation:
3 articles assigned to category
2 articles contain also a tag	
1 menuitem A type category blog filtered on one category and 1 tag
1 menuitem B  type category blog filtered on one category 

### Expected result
Display of a detailpage via blogpage A and B is correct
Breadcrumb: Start >  category  > article
url ans sitemap: domainname.tld/category/article

### Actual result
Breadcrumb: Start >  tag > article
url and sitemap: domainname.tld/tag/article

### System information (as much as possible)
tested wite joomla 3.9.0
template protostar

### Additional comments
Situation:
3 articles assigned to category
2 articles contain also a tag	
1 menuitem A type category blog filtered on one category and 1 tag
1 menuitem B  type category blog filtered on one category 

Display of breadcrumb and url are both incorrect in case of detailpage of an article through blogpage B
e.g. "Start >  tag > article" and url:domainname.tld/tag/article instead of "Start >  category  > article" and url:domainname.tld/category/article

when i depublish menu item A display breadcrumb of detailpage af an article through blogpage B is correct (Start >  category  > article)
when i put menu item A beneath menu item B display breadcrumb on  blogpage A is  incorrect (Start >  category  > article instead of "Start >  tag  > article)
Same behaviour is als with urls. (url:domainname.tld/category/article)

**Comment by quichot** [comment]
@infograf768 someone told me you might be interested in this issue.

**Comment by infograf768** [comment]
Really wonder who is that "someone"... 😸  specially concerning tags.

**Comment by quichot** [comment]
well that was exactly the reason for my hesitation to tag you. I want to reveal my source, but only in private ;-).
Anyway, i wondered why nothing happenend until now with the  issue i created. So i asked in the dutch community how to bring it under attention of the joomla devs. Your name was mentioned there.

The issue above is really annoying though, filtering on tags has absolutely no use if it frustrates correct routing in Joomla.

**Comment by Shankowsky** [comment]
The breadcrumb module also creates an error in Google Structured Data testing tools:

https://search.google.com/structured-data/testing-tool <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22982">issues.joomla.org/tracker/joomla-cms/22982</a>.</sub>

**Comment by brianteeman** [comment]
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed. 

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
