### ISSUE TITLE
[4.0][com_workflow] Docblocks Incorrect return types documented.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#23021]
Incorrect return types documented.

https://github.com/joomla/joomla-cms/blob/b7673120c5b26544756c5bb50e1695c5dfaa820f/administrator/components/com_workflow/Model/WorkflowModel.php#L278

https://github.com/joomla/joomla-cms/blob/b7673120c5b26544756c5bb50e1695c5dfaa820f/administrator/components/com_workflow/Controller/WorkflowController.php#L229

**Comment by SharkyKZ** [comment]
For first point test PR #23026.

Second point is correct, I think. It calls parent's `save()` method which should return a boolean. See https://github.com/joomla/joomla-cms/blob/b7673120c5b26544756c5bb50e1695c5dfaa820f/libraries/src/MVC/Controller/FormController.php

**Comment by SharkyKZ** [comment]
Yes, you're right. There are several instances of this.

**Comment by SharkyKZ** [comment]
Test PR #23048 please.

**Comment by SharkyKZ** [comment]
This can be closed now.
