### ISSUE TITLE
[4.0] CLI command - update,  throwing an error

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#23024]
While testing the [CLI Update Documentation](https://docs.joomla.org/J4.x:CLI_Update "cli"), 
for example, this command:
```
php cli/joomla.php check-updates
```
I keep having this error:
```
parse error, expecting `';'' or `'{'' in /libraries/src/Exception/ExceptionHandler.php on line 37

```
Possibly related:
[4.0] Load the document properly in the exception handler by laoneo · Pull Request #22913 · joomla/joomla-cms
https://github.com/joomla/joomla-cms/pull/22913
Tested with and without this PR though, no change.

MacOS
PHP 7.2.5
Composer v 1.7.2
Node v 10.12.0
NPM v 5.10.0

**Comment by PhilETaylor** [comment]
/libraries/src/Exception/ExceptionHandler.php on line 37 looks good to me

https://github.com/joomla/joomla-cms/blob/d67e585595d41b3705aa0673fd4d3afdaa68d7b5/libraries/src/Exception/ExceptionHandler.php#L37

**Comment by mbabker** [comment]
That's the 3.9 line @PhilETaylor.  In 4.0 line 37 is a method declaration which uses PHP 7 scalar and return typehints.

@ghazal Make sure your CLI PHP binary is running the expected version (as web and CLI can be running two different PHP versions).

**Comment by PhilETaylor** [comment]
In that case maybe the CLI code needs to be doing a PHP Version sanity check before running commands?

**Comment by mbabker** [comment]
ffc8f3be808c0a84e489c3e436b06112a24f965d adds the PHP version check and minimum PHP constant to the `cli/joomla.php` script.

**Comment by PhilETaylor** [comment]
:-)

**Comment by ghazal** [comment]
> ... Make sure your CLI PHP binary is running the expected version (as web and CLI can be running two different PHP versions).
That's what I suspected.
My computer runs on PHP 5.6.30
My bitnami stack on PHP 7.2.5 
The joomla package reads PHP 5.6.30
If I update composer.json to PHP 7.2.5 (having removed composer.lock before) and run 
`composer install` again, the joomla package reads PHP 7.2.5 allright.
But the `php whatever` command still throws that error.
I guess I'll have to follow your advice (check CLI PHP binary) or maybe update the php version on this computer.

Thanks for your replies.

**Comment by Quy** [comment]
@ghazal Please close issue if resolved.

**Comment by ghazal** [comment]
Not really resolved, but OK. I'll reopen  it if necessary.

**Comment by ghazal** [comment]
Finally,  I used this binary package to update my global PHP version :
https://php-osx.liip.ch/

Symfony is grumbling now.

"I'll get it one day, I'll get it."

**Comment by PhilETaylor** [comment]
If you are on a mac, checkout the Homebrew implementation of PHP which allows easy installation of multiple versions of PHP and the ability to switch between them. 

see the PHP section of https://getgrav.org/blog/macos-mojave-apache-multiple-php-versions which explains how.

**Comment by ghazal** [comment]
@PhilETaylor 
Thanks.
I use Homebrew but have been stumped by their recent deprecation of php tap.
Gonna test this tut.

**Comment by PhilETaylor** [comment]
yeah that was a pain in the arse... but it all seems to be stable again now.

**Comment by ghost** [comment]
@ghazal can this Issue be closed?

**Comment by ghazal** [comment]
Yes.

**Comment by ghost** [comment]
thanks @ghazal
