### ISSUE TITLE
[4.0[ Multilingual Sample Data Install by Joomla administration - No close or hide button & second position in Sample Data

### ISSUE THREAD

**Issue by Chacapamac** [joomla/joomla-cms#23028]
### Steps to reproduce the issue

Install Multilingual Sample Data by Joomla administration

### System information (as much as possible)
alpha5-Alpha-Full
Mamp, PHP 7.2.1, Firefox Dev, El Capitan

### Additional comments

1— I personally think that the possibility to Install the Joomla multilingual system should be available when installing.
See my issue here —> https://issues.joomla.org/tracker/joomla-cms/22907

2— In Joomla administration, The Multilingual Sample Data is under the Blog Sample Data, many people will install the blog data first and realize after that they cannot install the Multilingual system after. They will have to reinstall or learn how to setup manually a multilingual web site — Not Cool. Also, the Multilingual box stay in the administration even when installed (Blog sample data is the same)— This is confusing as if they are used you will never need them again...

Suggestion to fix it; (sadly I cannot myself, not good enough coding experience...)
**1** — At least, having the multilanguage box on top of Blog data

**2** — Rename Sample Data Section (With 2 box Blog & multilanguage) by “ Customized Joomla!” 
• Box 1 title — Install Multilingual system & Sample Data
• Box 2 title — Install a Blog section & sample data 

**3** — Add a more visible warning that you cannot install the blog data first

**4**— Add a close/hide button to take out manually theses 2 boxes from the administration if they used or will be never used to clear up the control panel

**Comment by Bakual** [comment]
While sample data installation will be removed from the installer, language installation (and with that setting up a multilingual site) afaik will stay. I'm not aware of anyone saying that part should be removed.

Installing blog sampledata and multilingual "sampledata" should both be possible.
If not, that is a bug that should be fixed. Did you get an error message while trying to do that?

As for the order, that would be an easy change. How they appear is based on how the plugins are ordered in the manager. So changing the ordering column values in the installation SQL files would be enough.

I wouldn't add a close/hide button to the module. Simply because other modules don't have that as well. The module is a regular module and can be disabled in the module manager if someone wants to hide it. You cna also hide single entries because those are regular plugins (from the "sampeldata" group).
Keep in mind that 3rd party extensions could offer their own sampledata options in that module.

**Comment by Chacapamac** [comment]
Thanks Bakuai
> language installation (and with that setting up a multilingual site) afaik will stay.

From the first steps installation ?

**Comment by Bakual** [comment]
As an optional step in the installer, like it is today in J3.

**Comment by Chacapamac** [comment]
That is great news **Bakuai**. 

The ability to install in a few click a fully functional multilingual site is one of the great force that, to my knowledge other CMS cannot do.

More, at the marketing level, this make Joomla a more “international” solution, compare to it’s competitor.

I even propose a design and functionality at #22907 
![multi-install](https://user-images.githubusercontent.com/1907276/48513455-cc148480-e829-11e8-9a6d-b38bcf5863da.jpeg)

**Comment by infograf768** [comment]
If I understand well, that is not what @Bakual wrote.
He said that installing languages is (or will be, if broken atm) still possible in 4.0 but that it is not considered to add at Installation time the sample data for basic multilingual site as we do in J3.
One still has to do this in CPanel through the module and plugin.

I personally agree with you that it SHOULD still be possible at install time.

**Comment by Chacapamac** [comment]
@infograf768 
> I personally agree with you that it SHOULD still be possible at install time.
Of course!
I understand that installing the Blog Sample Data become a choice in the administration, but not including the possibility to install another language and/or Joomla complete multi language system in the installation is an error for 2 main reasons;

**1.** International administrators will surely appreciate their brand new site administration in their language without any other steps _(that maybe be complex for them _(think about Newbie to Joomla)__ 

**2.**This is a MAJOR plus for the Joomla platform ( for it’s world domination...  :) )
To my knowledge, no other CMS can do that.

Go to #22907 
I propose my view of the Joomla installation process (and multilingual installation)

**Comment by Chacapamac** [comment]
Kind of sad, after trying to reach to revive the Joomla archived team “User Experience Team (JUX)” or join and participate to any team in charge of the ergonomic development, design and UX for Joomla 4. No response ?????

Joomla 4 steaming along with an interface that is really far from optimal and people wanting to help have no place to donate their time.

This is a complete revision of the interface, not porting attention here can be catastrophic. So far I’m far from impress in what I see...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23028">issues.joomla.org/tracker/joomla-cms/23028</a>.</sub>

**Comment by ghost** [comment]
@Chacapamac as wrote on 2 other, same comments: https://volunteers.joomla.org/teams/j4-backend-template-working-group

**Comment by infograf768** [comment]
Re-implementing the possibility of installing a basic multilingual site at Joomla installation time does not depend imho on the back-end template working group.
That decision has to be (or not) taken by the Production Department Team.
Until now, this has been refused and I had to create a specific multilang sampledata plugin in 4.0 to cope with this.

@Webdongle @rdeutz 
Can this be reconsidered?

**Comment by Webdongle** [comment]
@infograf768 I do not use multilanguage nor do I have any say in the development of Joomla.  But if you are asking me then I say your word on multilanguage should be the final word on the subject.  And all others should do as you request.

**Comment by infograf768** [comment]
oops, wanted to ping @wilsonge but w got you. 😈

**Comment by Chacapamac** [comment]
> Re-implementing the possibility of installing a basic multilingual site at Joomla installation time does not depend imho on the back-end template working group.
That decision has to be (or not) taken by the Production Department Team.
Until now, this has been refused and I had to create a specific multilane sampledata plugin in 4.0 to cope with this.

Hopefully the light is at the end of the tunnel and the **Production Department Team** will implement it in the install process. It will be a big plus for Joomla.

**Comment by mbabker** [comment]
> Re-implementing the possibility of installing a basic multilingual site at Joomla installation time does not depend imho on the back-end template working group.
> That decision has to be (or not) taken by the Production Department Team.
> Until now, this has been refused and I had to create a specific multilang sampledata plugin in 4.0 to cope with this.

To be fair here, I don't think it was ever suggested that the multilanguage section be removed in full from the install app (and if it was I agree that's a bad idea, BUT, it must always be in the back of everyone's minds that a lot of Joomla installs happen without seeing Joomla's installer through platforms like Softaculous so some features may never be seen by users unless those vendors are exposing them).  Having a multilanguage sample data plugin that follows the plugin driven approach that all sample data is moving to is a good idea and should be implemented regardless of where the "do you want to set up a multilanguage website" steps live.

**Comment by Chacapamac** [comment]
> BUT, it must always be in the back of everyone's minds that a lot of Joomla installs happen without seeing Joomla's installer through platforms like Softaculous

Didn’t think at this... 
– Keep Multilingual as an install OPTION
- Keep Multilingual as a backend administration OPTION

The only actual caveat in the administration is the fact that no sample data should be installed before Installing the Multilingual system. 
The way it is now, be sure you will have lot of people actually make the mistake to install the Blog sample data before the Multilingual option

**Suggestion, something like;** 
**• Original**
**Sample data which will set up a multilingual site.**
Before launching, make sure you have at least 2 languages installed with their Content Languages and that no sample data has been installed.

**• it should say, to be clear**
**Set up a multilingual site (with Multilingual Sample data)**
**_IMPORTANT - If needed, install BEFORE the Blog sample data_**
Before launching, make sure you have at least 2 languages installed with their Content Languages and that no **Blog** sample data has been installed.

**• Also** the multi language option **should be first** (on top of the Blog sample data)

**Comment by mbabker** [comment]
That conflict only exists between the blog and multilingual sample data sets, and even then there's no confirmation that it is actually an issue (at worst you've got both sets installed and the blog data isn't set up as multilingual content, which is not a bug because even if you have set up a site to be multilanguage that does not mean every piece of content on it must be internationalized).  Any text strings should not imply that you can only install one sample data set, because it is entirely possible multiple sets could be installed without any issue at all.  Also consider that as a plugin based system, the core supported blog and multilingual sample data sets are not the only options available (https://github.com/joomla-extensions/testing-sample-data has the testing data set and extension vendors can create their own plugins).

**Comment by Bakual** [comment]
@Chacapamac If there is indeed a conflict between those two sample data sets, please open a new issue for it with the details. I'm sure it can be solved.

> Before launching, make sure you have at least 2 languages installed with their Content Languages and that no sample data has been installed.

The multilingual sample data can't be installed if there aren't two languages set up already. It will show you an error message.
I wrote a PR which actually hides the option if the languages aren't present: https://github.com/joomla/joomla-cms/pull/20749
I'm not convinced this is needed but the code is there if it's deemed necessary 😄

**Comment by Webdongle** [comment]
> If there is indeed a conflict between those two sample data sets, please open a new issue for it with the details. I'm sure it can be solved.

Does the install sample data screen not say that installing without sample data is to be chosen for multi language sites ?

**Comment by mbabker** [comment]
> Does the install sample data screen not say that installing without sample data is to be chosen for multi language sites ?

For 3.x and sample data driven by SQL files, yes you should avoid installing sample data.  With either 3.x or 4.x and sample data plugins, this suggestion (restriction?) should not exist.

**Comment by infograf768** [comment]
> I wrote a PR which actually hides the option if the languages aren't present: #20749
I'm not convinced this is needed but the code is there if it's deemed necessary 😄

Hiding the option also hides the feature. Not good imho.

> With either 3.x or 4.x and sample data plugins, this suggestion (restriction?) should not exist.

It may not be a big issue with blog sample data plugin but, with the present code for 4.x it may be for the multilang sample data, depending on what was already created.
If you have already installed testing sample data then the sampledata module is NOT displayed in CP. Let's enable it, install a language and run it. (BTW, we have a bug for the Position field for admin modules).
Result: Yes, home pages are set as should, but the site is a mess as what was installed with testing sample data is set to ALL languages (except Parks which should be modified I guess). 
Very confusing for the user.

**Comment by Bakual** [comment]
As said, open a new issue for conflicts. For the testing sample data there is even an own repo for it.

**Comment by mbabker** [comment]
> Very confusing for the user.

Yeah, the UX of it all isn't very good my any means.  But from a technical perspective, my point is there shouldn't be a thinking that only one sample data set can ever be installed on a site and after that you're on your own.

**Comment by Webdongle** [comment]
'off the wall' thought
Could various people write sample data for various languages.  Yes that would take time but if a collection of sample data (for various languages) was to be built up ... could they then be incorporated (during install) in a drop down menu ?

Sample data for different languages doesn't need all the pages translated ... just a few pages with menus/menu items as an example of how a mulit language site can be set up.

**Comment by infograf768** [comment]
@Webdongle 
We have a way to install a basic multilang site without it being a tutorial (code is still present in installation and just need to be adapted to j4).
Going further than that is asking a bit too much imho.

**Comment by Bakual** [comment]
@Webdongle The blog sample data by itself is multilingual aware. It will install the items with the currently active language. If you afterwards switch language, you can install it again for that language. All strings used by the plugin are regular language files which are translated the same way the rest of core is.

**Comment by jwaisner** [comment]
Please see #24481 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23028">issues.joomla.org/tracker/joomla-cms/23028</a>.</sub>

**Comment by brianteeman** [comment]
this is nothing to do with #24481
