### ISSUE TITLE
[4.0] PSR-18 Support in HTTP package

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#23029]
After https://github.com/joomla-framework/http/pull/37 the Framework's HTTP package now supports [PSR-18](https://www.php-fig.org/psr/psr-18/) for sending HTTP requests.  As the CMS classes are an extension of the Framework, that support will inherently be available after the next `composer update` for that package.  However, part of the support requires that all exceptions implement `Psr\Http\Client\ClientExceptionInterface`, meaning we need to update our exceptions to do so.

x-ref https://github.com/joomla-framework/http/issues/38

**Comment by PhilETaylor** [comment]
> all exceptions implement

You mean those exceptions used when making http requests and not "all" exceptions everywhere right?

**Comment by mbabker** [comment]
Right.  If in the `Joomla\(CMS\)Http` namespace the Exception should implement that `ClientExceptionInterface` somehow.
