### ISSUE TITLE
Granular customization of article editor

### ISSUE THREAD

**Issue by awdhaan** [joomla/joomla-cms#23031]
### Steps to reproduce the issue
Create a new article or edit an existing one

### Expected result
Simplified article editor showing the fields and functions for the type of website. This can differ per scenario.
For some content managers, the article editor can be overwhelming while other ones need all capabilities.

It would be really useful to have more granular control over which tabs, fields and functions are shown to a content manager. It is already possible to show/hide the “Options” etc., but it would be optimal to mix and match article editor tabs and tab contents for a specific site scenario.

**Comment by brianteeman** [comment]
You can do this with overrides. There is an article in the joomla magazine by Sander Potjer about this

**Comment by ghost** [comment]
@brianteeman do you mean https://magazine.joomla.org/issues/issue-sept-2014/item/2293-creating-an-article-in-joomla-has-never-been-this-easy?

**Comment by awdhaan** [comment]
I understand the overrides, but if it can be configured, that would be more flexible then maintaining a custom admin template imho

**Comment by mbabker** [comment]
Joomla core is not built as a CCK platform or as a drag-and-drop builder where through the UI you can build and maintain interfaces for everything.  If you want to customize layouts, template overrides (or custom templates) is the way to go.

**Comment by rdeutz** [comment]
We already have more switches and option as an air plane like airbus 380 or Boeing 780. 
Sorry but I am closing this because we will not implement or merge a PR for this functionality,
