### ISSUE TITLE
ConsoleApplication, Application, AbstractApplication constructor mistmatch causes lost of config

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#23038]
### Steps to reproduce the issue

ConsoleApplication (extending Application) calls parent::__construct($input, $config);

But, Application constructor is __construct(Registry $config = null);

Then, Application (extending AbstractApplication) calls parent::__construct(null, $config);

### Expected result

Configuration properly managed in ConsoleApplication.

### Actual result

The config is being lost.

### System information (as much as possible)

J4 A5

**Comment by PhilETaylor** [comment]
is this related to https://github.com/joomla/joomla-cms/issues/22931 https://github.com/joomla-framework/application/issues/84 @mbabker

**Comment by mbabker** [comment]
Sooner or later yes, after a `composer update` is done updating the `joomla/console` package.
