### ISSUE TITLE
[4.0] Rearrange System Panel / Add (n) badges to items with issues

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#23032]
### Steps to reproduce the issue

Just a thought
Joomla 4.0-dev
administrator/index.php?option=com_cpanel&view=system

### Expected result

That the most common features of Joomla are uppermost left in the visual area and those lesser used features lower down/right

If an update is available then, (6) could be added next to Extensions 
If there are installation messages, (3) could be added next to installation messages
If there are warnings,  (1) could be added next to warnings
If there are extensions discovered,  (1) could be added next to discover

![screenshot 2018-11-11 at 01](https://user-images.githubusercontent.com/400092/48308054-cfbab980-e552-11e8-8956-3dd5f69dace1.png)

### another thought

Another idea is that these should actually be CONFIGURABLE admin menus with menu items that can then be extended/modified/manipulated by 3pd and "Super Admins" to remove/add/change menu items at will.

There is no reason to hard code all these "menus" when they could be created with the menu manager and managed as real menus.

### Actual result

![screenshot 2018-11-11 at 01 33 28](https://user-images.githubusercontent.com/400092/48308056-d3e6d700-e552-11e8-9d41-6effe7b1e714.png)

**Comment by infograf768** [comment]
Looking into that as I think it is a good idea.

**Comment by C-Lodder** [comment]
The whole masonry grid needs to be rethought too. At best they're ok for photo galleries, assuming there is no particular content hierarchy but for a list, it makes scanning horrible.

**Comment by PhilETaylor** [comment]
> The whole masonry grid needs to be rethought too. 

Yes thats what I meant when I wrote (badly worded and explained, sorry)

>That the most common features of Joomla are uppermost left in the visual area and those lesser used features lower down/right

**Comment by mbabker** [comment]
> There is no reason to hard code all these "menus" when they could be created with the menu manager and managed as real menus.

As nice as customizable administrative menus are, just keep in mind that making the admin area too flexible makes writing coherent documentation that much more complex because you can't "simply" say "Go to Extensions > Modules to manage your site's modules" if things are too customized.  So, there needs to be a sane balance here.

**Comment by PhilETaylor** [comment]
lol - so lets dumb down Joomla features for the sake of documentation hahahahhaha

**Comment by mbabker** [comment]
That is not what I said at all.

**Comment by PhilETaylor** [comment]
We already "dumb down" the interface if a user doesnt have ACL to do something ... its no different.

**Comment by PhilETaylor** [comment]
We already "dumb down" the interface if a user doesnt have ACL to do something ... its no different.

1) Create an "dumbadmin" user in the Administrators group
2) Remove the ACL for the redirects component for the administrators groupd
3) login as "dumbadmin"
4) Note that redirects is no longer in the menu system on this page! 

That is no more "complex" to document than what I proposed. 

![screenshot 2018-11-12 at 00 44 31](https://user-images.githubusercontent.com/400092/48320658-276d2980-e614-11e8-9cd3-784e537dcffa.png)

**Comment by mbabker** [comment]
Documenting a feature is only available with a given ACL level still usually results in that feature consistently being discoverable in some spot.

Again, I'm not saying that making things flexible is bad.  My only caution is if you make things too flexible you make it too easy for users to potentially mess things up catastrophically and too hard for documentation writers (for core, third party service providers, or those building sites and handing them off to clients) to consistently document things.  So make sure whatever is done has a balanced approach, I don't think that's asking for too much (stop thinking that only "smart" developers will use the system and don't let the system be so flexible "average user" can shoot themselves in the foot).

**Comment by ghost** [comment]
~~Documentation~~ Helpscreens should reflect the default Values of Joomla-Core in Text and Pictures. And Possibilities shipped by Core (Mulitlang. as example). 

Had meant "Helpscreens" instead "Documentation" so this comment isn't on topic, please ignore.

**Comment by infograf768** [comment]
I have made a PR to implement the original proposal of this issue, i.e. adding pills when necessary
See https://github.com/joomla/joomla-cms/pull/23047

As the discussion went further than the original proposal, I'm not closing this for now.

**Comment by PhilETaylor** [comment]
>  I'm not closing this for now.

Easier than addressing my "opinions" apparently :) 

Outstanding conversations: 

1) @C-Lodder The whole masonry grid needs to be rethought too. 
2)  customizable administrative menus 

I'll stick to code and not offer opinions on Joomla directions/features in the future. Apparently I always ask for too much.

**Comment by infograf768** [comment]
> Easier than addressing my "opinions" apparently :)

For sure. Easy to guess what I think of the whole UI in j4... ;)

**Comment by PhilETaylor** [comment]
Yeah! but make sure you "[select](https://github.com/joomla/joomla-cms/issues/22980)" instead of "click" the ui, would not want to upset anyone :-P

**Comment by infograf768** [comment]
hehe
