### ISSUE TITLE
Custom Elements integration with Custom Fields needs work

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#23036]
As part of the custom fields integration we've had to make a reasonably nasty hack to hide errors https://github.com/joomla/joomla-cms/pull/22263/files#diff-1012a2e43c80bf48fceac68dbb3552c7R315

I want to spend some time before final release working out if there is a better way of working around custom elements/reworking the internals of custom fields or if this is the best we can do

**Comment by dgrammatiko** [comment]
@wilsonge don't waste your time on this, the solutions is already here: https://github.com/joomla/joomla-cms/pull/22491

**Comment by wilsonge** [comment]
That looks like a good start but you’re not changing the DomDocument code there which is the issue in the choices PR

**Comment by dgrammatiko** [comment]
I don't think you need that with my approach, check what the custom fields plugin is returning and also how that is used by the category field. (the idea is that custom fields should do their part on the form prepare, therefore, no DOMDocument need)

**Comment by dgrammatiko** [comment]
@wilsonge if you have to use DOMDocument I'll suggest adding https://github.com/ivopetkov/html5-dom-document-php. The native DOMDocument doesn't even understand HTML5 tags like header, main, footer (hot garbage...)

**Comment by Fedik** [comment]
please test this #30268

**Comment by alikon** [comment]
closing as we have a PR
