### ISSUE TITLE
[4.0] System Panel Page, drop shaddow missing

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#23043]
Under the "Administrator Modules" there is no final dropshadow

![screenshot 2018-11-12 at 00 33 52](https://user-images.githubusercontent.com/400092/48320490-b0836100-e612-11e8-9159-c7a3a9fac1b9.png)

Google Chrome Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by puneeth-chanda** [comment]
@PhilETaylor while zooming it is not showing any error
![screenshot from 2019-01-26 19-23-24](https://user-images.githubusercontent.com/43813460/51788094-232ac400-21a0-11e9-9728-7d54d937d90f.png)

**Comment by puneeth-chanda** [comment]
Should I remove shadows for all??

**Comment by PhilETaylor** [comment]
Don't waste your time - the admin template is currently being developed in a private repository and so any changes like this are just a waste of time because no one knows if the private changes are going to duplicate or even make this useless. 

I cant find the link for you at the moment that explains

**Comment by puneeth-chanda** [comment]
ok fine

**Comment by PhilETaylor** [comment]
Finally found the link buried in a team page

https://volunteers.joomla.org/teams/j4-backend-template-working-group/reports/926-team-setup
