### ISSUE TITLE
Rename User Admin #__action_logs_users' doesn't exist

### ISSUE THREAD

**Issue by ZerooCool** [joomla/joomla-cms#23040]
### Steps to reproduce the issue
Hello
I tested Joomla 3.9 in beta a few weeks ago on https://launch.joomla.org.

From the admin interface, I renamed my admin user "xotudovi" to "ADMIN_FOR_EXEMPLE".

I now have the following message:

Erreur
Table 'xotudovi.#__action_logs_users' doesn't exist

But, this user does not exist anymore.

### Expected result
Do not see this error.

### Actual result
Erreur
Table 'xotudovi.#__action_logs_users' doesn't exist

### System information (as much as possible)
Joomla 3.9 in beta a few weeks ago on https://launch.joomla.org.

### Additional comments

In the meantime, I updated for Joomla 3.9.
But the error message is still there.

I do not know if this was due to the Beta version, nor, if this bug is still active.

**Comment by SharkyKZ** [comment]
If you can navigate the backend, go to Extensions -> Database and click Fix.

**Comment by PhilETaylor** [comment]
I cannot replicate this in a clean install or an upgraded site. 

It is 99% likely to be a failed upgrade by the cloudaccess system, or your doing, and following the instructions from @SharkyKZ will fix it.

**Comment by ZerooCool** [comment]
Good answer from @SharkyKZ 
Warning: the database is out of date!
[Resolved]

**Comment by franz-wohlkoenig** [comment]
Reopen because: Open Admin-Module "Recently Added Articles" and save got ```1146 Table '#_action_logs_users' doesn't exist```

Database-Fix don't change Behaviour, after of an Component (Article, Menu, ...) the Error is shown.
