### ISSUE TITLE
super administrator can't log to administrator site

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#23051]
### Steps to reproduce the issue

1 actived privacy component
2 try to login on administrator

### Expected result

need to redirect to profil page or display a message

### Actual result

nothing => user can't connect him

... user can be frustrate by this experience .....

**Comment by tonypartridge** [comment]
Did the user accept the privacy policy?

**Comment by micker** [comment]
no that the problem an admin can't redirect he only block on login admin page ....
whitout explication

**Comment by Quy** [comment]
I cannot reproduce.

**Comment by ghost** [comment]
closed as stated above, Issue can always reopened.
