### ISSUE TITLE
since 3.8.11 I get a error caused by the changes made in file: libraries/src/Router/SiteRouter.php - probably line 602 if ($start !== null)

### ISSUE THREAD

**Issue by hostingby** [joomla/joomla-cms#23050]
since 3.8.11 I get a error caused by the changes made in file: libraries/src/Router/SiteRouter.php - probably line 602 if ($start !== null)
On my forum, when a topic consists of many reactions, they are divided into several pages;
[1] [2] [3] when you want to change from 3 to 1, the first message is not displayed.
By using the old file of version 3.8.10 problem is solved
I am using template beez3, forum kunena.
I hope you can undo the changes made in 3.8.11. version 3.8.10 worked perfectly.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/19452

**Comment by SharkyKZ** [comment]
Also see if #23042 helps.

**Comment by Quy** [comment]
@toerrijders I am not able to reproduce this with v3.8.13 and Kunena v5.1.6.1. Can you provide steps to reproduce it? Have you reported this issue in Kunena forum or Joomla forum to see if others have experienced it too?

**Comment by csthomas** [comment]
There is a router bug in old version of kunena  <= 5.0.12 as mentioned at https://github.com/joomla/joomla-cms/pull/19452#issuecomment-360907874

**Comment by hostingby** [comment]
I 'm still using Kunena 4, I tried version 5 and probably that was version 5.0.12 with the bug so it make no difference at the time. 
This morning after installing Kunena 5.16 the problem is gone.
A lot of people still using kunena 4 because of the missing template blue eagle in the past,  it took 2 years and now you can buy the blue eagle template.
For those who want to keep using the old kunena 4 version, the routing bug is gone when using old file libraries/src/Router/SiteRouter.php from version 3.8.10

Thanks you all for your answers...

**Comment by infograf768** [comment]
Closing as it is not a Joomla bug.
