### ISSUE TITLE
After updating to 3.9.0 h1 page headings disappeared

### ISSUE THREAD

**Issue by ribo72** [joomla/joomla-cms#23068]
### Steps to reproduce the issue

The Show Page Heading as Yes in menu item in single article is not appear adter update to joomla 3.9.0 . Please check our discussion in joomla forum  https://forum.joomla.org/viewtopic.php?f=706&t=967175
Thank you

**Comment by Quy** [comment]
This appears to be solved. Please close if it is no longer an issue.
