### ISSUE TITLE
Travis PHP 7.3 broken.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#23060]
Paging @mbabker to fix the travis PHP 7.3 build please :):)

```
...........................SS.../home/travis/.travis/job_stages: line 104:  2551 Illegal instruction     (core dumped) libraries/vendor/bin/phpunit --configuration travisci-phpunit.xml
The command "if [[ $RUN_UNIT_TESTS == "yes" ]]; then libraries/vendor/bin/phpunit --configuration travisci-phpunit.xml; fi" exited with 132.
```

https://travis-ci.org/joomla/joomla-cms/jobs/454185931

**Comment by zero-24** [comment]
it seams like to be and problem at travis itself? As the file that throws the error is `/home/travis/.travis/job_stages: line 104:` ?

**Comment by mbabker** [comment]
It's either an issue with the Travis platform or with the PHP 7.3 RC itself.  Laravel too has the same problem.

**Comment by PhilETaylor** [comment]
Well apparently the solution is to ignore it... e5157f2db1e4c9b0160e60b14eb536b725a8d17f

**Comment by zero-24** [comment]
Solution is not the right term but as this is something out of the control of our code and seams to be a problem on other repos too we should give travis time to take a look but not blocking all PRs to be merged when Travis fails.

**Comment by PhilETaylor** [comment]
![screenshot 2018-11-13 at 22 32 46](https://user-images.githubusercontent.com/400092/48447531-0fbcaf00-e794-11e8-8b25-4c759259c126.png)

The test suite runs perfectly, and completes, on my mac with PHP 7.3beta3.

**Comment by zero-24** [comment]
Yes it seams that travis now uses RC5 and as said before the error message looks like a travis platform issue not a PHP issue itself lets check what happens at the time RC6 comes out.

**Comment by PhilETaylor** [comment]
With PHP 7.3RC5 in a docker container I get: 

![screenshot 2018-11-13 at 22 36 48](https://user-images.githubusercontent.com/400092/48447720-a38e7b00-e794-11e8-8699-ae191ccccf2f.png)

**Comment by zero-24** [comment]
undefined index SCRIPT_NAME ? Can you identify the failing test? Can you confirm that docker container runs the tests successful on an other PHP Version? (just to make sure anything required is running there)

**Comment by PhilETaylor** [comment]
failing test was 

> Starting test 'JComponentRouterRulesNomenuTest::testConstruct'.

I removed that, next failure with the same error is 

> Starting test 'JHelpTest::testCreateUrl'.
EUndefined index: SCRIPT_NAME

**Comment by mbabker** [comment]
Congrats, Phil.  You've just run into the same issues what tests we have left have always had.  There's global state bleedover between tests and they aren't portable across environments.

====

> Yes it seams that travis now uses RC5 and as said before the error message looks like a travis platform issue not a PHP issue itself lets check what happens at the time RC6 comes out.

There's no assurance that it is not a PHP issue.  Just because the file path has what is presumably the file that the YAML config is parsed into does not automatically mean it is a Travis-CI issue.  FWIW I did get a project to run its test suite on Travis-CI with PHP 7.3 RC 5 so that does give some credit to it not being a platform (whatever the system the Travis-CI run is being made on) problem and some credit toward a potential PHP bug (and considering both Joomla's and Laravel's test suites are having the same issue, that does seem to strengthen that argument).

**Comment by PhilETaylor** [comment]
> Congrats, Phil. You've just run into the same issues what tests we have left have always had. There's global state bleedover between tests and they aren't portable across environments.

This project never ceases to amaze me. The one whole point of tests is that they are runable and  portable... /facepalm

After faking SCRIPT_NAME in TestCase.php setUp function (and directly in a load of tests) **I was able to run the complete test suite on PHP 7.3RC5.** in a docker container (Alpine based, PHP Earth packages - same build that ALL the LIVE myJoomla.com service containers are running production)

**Comment by PhilETaylor** [comment]
As a core file is generated, is there any interest in looking at something like http://jsteemann.github.io/blog/2014/10/30/getting-core-dumps-of-failed-travisci-builds/ ?

**Comment by mbabker** [comment]
It's a Travis-CI issue.

Framework Repos:
- https://travis-ci.org/joomla-framework/application/builds/454758565 passed on 7.3
- https://travis-ci.org/joomla-framework/archive/builds/454758629 passed on 7.3
- https://travis-ci.org/joomla-framework/authentication/builds/454758677 failed on 7.3
- https://travis-ci.org/joomla-framework/controller/builds/454760241 passed on 7.3
- https://travis-ci.org/joomla-framework/crypt/builds/454760386 passed on 7.3
- https://travis-ci.org/joomla-framework/data/builds/454760437 passed on 7.3
- https://travis-ci.org/joomla-framework/database/builds/454762736 is still going but all 7.3 builds have passed as of this writing

CMS Repo:
- https://travis-ci.org/joomla/joomla-cms/builds/454764451 passed building [this commit](https://github.com/joomla/joomla-cms/commit/c0b39bd9cedd5697a557bdea905514f39f7035bc)
- https://travis-ci.org/joomla/joomla-cms/builds/454764377 passed building [this commit](https://github.com/joomla/joomla-cms/commit/3d138f87058e864e7424b527eccca54caf2fcc3b) (this is the one that tried to get the core dump)
