### ISSUE TITLE
[4.0] Alpha5 Installation with PDO Database Type loop

### ISSUE THREAD

**Issue by austre** [joomla/joomla-cms#23076]
### Steps to reproduce the issue
1- Download J4 Alpha5 from [here](https://github.com/joomla/joomla-cms/releases/tag/4.0.0-alpha5)
1- Install J4 Alpha5 with PDO Database Type

### Expected result
![j4a5_img02](https://user-images.githubusercontent.com/4764413/48482636-f8131400-e7ef-11e8-880a-8cb26c2be3fb.JPG)

### Actual result
![j4a5_img01](https://user-images.githubusercontent.com/4764413/48482656-0a8d4d80-e7f0-11e8-987f-0ed3f6d1f7d0.JPG)

### System information (as much as possible)
[Debian 9.5][PHP 7.3][MySQL 8][Joomla 4 Alpha 5]

### Additional comments
More details at [this request](https://github.com/joomla/joomla-cms/pull/19989)

**Comment by dzdeveloper** [comment]
i have the same issue  neither MYSQLI or PDO works for me 
os : windows 10 x64
server : xampp (latest version)

**Comment by dzdeveloper** [comment]
i have the same issue , neither MYSQLI or PDO works for me
os : windows 10 x64
server : xampp (latest version)

**Comment by Quy** [comment]
Please test with the [nightly builds](https://developer.joomla.org/nightly-builds.html) to see if it is still an issue.

**Comment by austre** [comment]
At first step, we can't go next cause Name of Joomla Site field not exists.
![j4a6_img01](https://user-images.githubusercontent.com/4764413/49221663-8a064980-f3b8-11e8-90b9-3d54ba395ec8.JPG)

**Comment by ghost** [comment]
can you please test with https://developer.joomla.org/nightly-builds.html<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23076">issues.joomla.org/tracker/joomla-cms/23076</a>.</sub>

**Comment by ghost** [comment]
Closed as no Answer, please reopen if needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23076">issues.joomla.org/tracker/joomla-cms/23076</a>.</sub>
