### ISSUE TITLE
[4.0] New banner fails to save

### ISSUE THREAD

**Issue by phalouvas** [joomla/joomla-cms#23072]
### Steps to reproduce the issue
1. Create new banner
2. Put a title
3. Choose a client. 
4. Save.

Be aware that the problem only occurs on new banner, and if you choose a client.

### Expected result
To save a new banner on the selected client.

### Actual result
An error has occurred.
0 Call to a member function load() on boolean 

### System information (as much as possible)
Joomla v4alpha5

### Additional comments
The problem is on file /administrator/components/com_banners/Table/BannerTable 
line 204. Change from:

$client = Table::getInstance('Client', __NAMESPACE__ . '\\', array('dbo' => $db));
to
$client = new ClientTable($db);
I will also try to submit PR that fixes this issue.

**Comment by richard67** [comment]
This issue can be closed because it’s solved with commit https://github.com/joomla/joomla-cms/commit/329fd3b2db7b4da4a36c7c1b214b1bb9e6b638ac
