### ISSUE TITLE
Cannot login in Joomla 3.9

### ISSUE THREAD

**Issue by akfaisel** [joomla/joomla-cms#23079]
### Steps to reproduce the issue
1. Go to http://demo.joombri.in/component/users/?view=login 
2. Type username freelancer and password password. 
3. Click on Log in button.

### Expected result
Expected to login successfully.

### Actual result
Fatal error: Cannot redeclare class Composer\Autoload\ClassLoader in /home/joombrii/public_html/demo3/libraries/vendor/composer/ClassLoader.php on line 43

### System information (as much as possible)
Joomla 3.9
PHP 7.0

### Additional comments
This error is coming on another domain www.joombri.in as well.

**Comment by SharkyKZ** [comment]
Have you solved this? I can login to your site just fine.

**Comment by akfaisel** [comment]
Hi

Yes, suddenly the login is working and I'm confused <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23079">issues.joomla.org/tracker/joomla-cms/23079</a>.</sub>

**Comment by infograf768** [comment]
Please close the issue if it's solved.

**Comment by zero-24** [comment]
Closing as it seams to be solved now.
