### ISSUE TITLE
JApplicationCli object instantiation fails

### ISSUE THREAD

**Issue by wanderlusted18** [joomla/joomla-cms#23075]
### Steps to reproduce the issue
Run the below code from a terminal

### Expected result
JApplication object instatiated, traces are printed to the terminal

### Actual result
Instatiation seems to fail when the parent constructor is called. T2 is never printed to the terminal

### System information (as much as possible)
Joomla 3.8

### Additional comments
Hi There, 

I was trying to use the code from the below link to simply instantiate a JApplicationCli object, but it seems that my code just dies when the parent constructor is called. No error message. T1 is printed out on the terminal, but T2 is not. What am I doing wrong?  Thanks!

https://github.com/joomla/joomla-cms/issues/7028

```
<?php


// We are a valid entry point.
const _JEXEC = 1;
error_reporting(E_ALL | E_NOTICE);
ini_set('display_errors', 1);
// Load system defines
if (file_exists(dirname(__DIR__) . '/defines.php'))
{
	require_once dirname(__DIR__) . '/defines.php';
}
if (!defined('_JDEFINES'))
{
	define('JPATH_BASE', dirname(__DIR__));
	require_once JPATH_BASE . '/includes/defines.php';
}
require_once JPATH_LIBRARIES . '/import.legacy.php';
require_once JPATH_LIBRARIES . '/cms.php';
// Load the configuration
require_once JPATH_CONFIGURATION . '/configuration.php';
// ----------------------


class TestCli extends JApplicationCli {
    public function __construct() {
    	echo "T1\n";
	parent::__construct();
	echo "T2\n";
        $this->config = new JConfig();
        // important for storing several rows
        JFactory::$application = $this;
    }
    public function doExecute() {
    	echo "T3\n";
        
    }
    
}

echo "started...\n";
try {
    JApplicationCli::getInstance('TestCli')->execute();
} 
catch (Exception $e) {
    // An exception has been caught, just echo the message.
    fwrite(STDOUT, $e->getMessage() . "\n");
    exit($e->getCode());
}

echo "finished...\n";
?>
```

**Comment by mbabker** [comment]
If it's dying in the constructors, odds are you are hitting [this bit of code](https://github.com/joomla/joomla-cms/blob/9dfa9ea75791d0ced27436c257424e7c0eb50e0b/libraries/src/Application/CliApplication.php#L57-L61).  This seems to imply your command line PHP environment is not set up as core expects.

**Comment by wanderlusted18** [comment]
Thanks this is really helpful. Any chance you can send me an example of  / link to the typical settings of these environmental variables? Many thanks!

**Comment by mbabker** [comment]
PHP's CLI SAPI by default should define both constants that check looks for.  Likewise, executing a PHP script from command line should result in `$_SERVER['argv']` being populated.  If this is not happening, there is a good chance that the PHP binary that you're executing is not one that is using the CLI SAPI and this would be a host/server issue that needs to be addressed

**Comment by wanderlusted18** [comment]
Thanks again! It turned out that i was using the wrong php executable and this caused the above problems.
