### ISSUE TITLE
[UPDATE-BUG-STILL OPEN] Joomla! 3.9.15 - Combo field in repeatable form

### ISSUE THREAD

**Issue by Polm90** [joomla/joomla-cms#23077]
I have a multiple subform; in it there is a "Combo" field.

When I try to open the field list, it works only for the first instance; the other ones doesn't have the related event handler attached.

I use Joomla 3.9.0 (latest release)

**Comment by ghost** [comment]
can you please test on latest Release [3.9.3](https://github.com/joomla/joomla-cms/releases/tag/3.9.3 "")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23077">issues.joomla.org/tracker/joomla-cms/23077</a>.</sub>

**Comment by ghost** [comment]
Closed as no Answer, please reopen if needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23077">issues.joomla.org/tracker/joomla-cms/23077</a>.</sub>

**Comment by andykirk** [comment]
I'm experiencing this same problem on 3.9.11

Any fix for this?

Thanks

**Comment by Polm90** [comment]
The bug is still present in Joomla! 3.9.15 using the protostar default layout.

Form xml example:
```
<field name="test"
			   type="repeatable"
			   icon="list"
			   description="test_desc"
			   label="test_label"
			  >
			<fieldset hidden="true" name="repeatable_test" repeat="true">

				<field name="description"
					   label="description_label"
					   size="30"
					   type="combo">
					<option value="1">test 1</option>
					<option value="2">test 2</option>
				</field>
			</fieldset>
		</field>
```
This is the result:
![image](https://user-images.githubusercontent.com/4883463/73447837-de5fdd00-435f-11ea-8988-21654860b29d.png)
Clicking on the "arrow icon" doesn't do anything (neither the first time).

Moreover, neither the combo field type with the multiple attribute actually works: it ignores the attribute.

XML example:

```
<field name="test_combo"
			   label="test_combo_label"
			   multiple="true"
			   size="30"
			   type="combo">
			<option value="1">test 1</option>
			<option value="2">test 2</option>
		</field>
```

Finally, using a combo field type inside a subform with multiple attribute, doesn't work: the first instance works properly, but the following ones don't (clicking the arrow doesn't open the option list).

XML example:

```
<field
				name="test_combo"
				multiple="true"
				type="subform"
				formsource="components/com_test/models/forms/subform.xml"
				label="test_combo_lbl"
				description="test_combo_desc"
				min="1"
				buttons="add,remove"
				required="true"
		/>
```
and in the subform.xml file:

```
<form>
	<fields>
		<field name="test_combo"
			   label="test_combo_label"
			   multiple="true"
			   size="30"
			   type="combo">
			<option value="1">test 1</option>
			<option value="2">test 2</option>
		</field>
	</fields>
</form>
```

**Comment by Polm90** [comment]
@joomla-cms-bot can you re-open?

**Comment by tgv604** [comment]
No fix, apparently no one cares, but in the meantime you can put this js in your template

```
jQuery(document).ready(function($) {		
	$(document).on("subform-row-add", function(e, row) {
		$(row).find("div.combobox").ComboTransform();
        });		
});
```

**Comment by HLeithner** [comment]
It would really be great if @tgv604 can make a proper PR we could test, merge and finally fix this bug.

thx

**Comment by Polm90** [comment]
> No fix, apparently no one cares, but in the meantime you can put this js in your template
> 
> ```
> jQuery(document).ready(function($) {		
> 	$(document).on("subform-row-add", function(e, row) {
> 		$(row).find("div.combobox").ComboTransform();
>         });		
> });
> ```

Thank you, it works with this fix!

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed.

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
