### ISSUE TITLE
[4.0] Menu item set to guest access level not visible to anonymous users

### ISSUE THREAD

**Issue by tuum** [joomla/joomla-cms#23083]
### Steps to reproduce the issue
Create new menu item
Set access=guest
Look at front end site. Can't see menu item.

### Expected result
In Joomla 3, menu item set to guest is visible to anonymous users (not logged in), and is hidden when user logs in (registered user). I would expect Joomla 4 to do the same, or to have a new anonymous access level for this purpose.

### Actual result
Menu item set to guest access level is not shown to non-logged in users.

### System information (as much as possible)
Joomla 4.0.0 Alpha5

### Additional comments
I'm trying to create a "log in" menu item that is only visible to non-logged in users. When no user is logged in, menu item should be visible. When they log in, it should not be visible. Could do this in Joomla 3 using guest access level.

**Comment by SharkyKZ** [comment]
Test PR #23085 please.
