### ISSUE TITLE
[j4] Reset button on media manager

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#23088]
### Steps to reproduce the issue

Edit an image
Click on reset

### Expected result

we need to display original image

### Actual result

no image

**Comment by brianteeman** [comment]
Unable to replicate with current branch

**Comment by Quy** [comment]
Not reproducible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23088">issues.joomla.org/tracker/joomla-cms/23088</a>.</sub>
