### ISSUE TITLE
[4.0] media manager return and correction

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#23087]
### Is your feature request related to a problem? Please describe.
For now the media manager design isn't effective
1 full with option is realy a problem for usability (a slider or in input in 800px isn't good for eyes lol)
2 order option problem
3 No button to save a new image version

### Describe the solution you'd like
i think use right column is good for large screen
ex
![media](https://user-images.githubusercontent.com/2539440/48542377-522eda80-e8bf-11e8-897e-a27431627ccb.png)

About order (for commun user and most used option) will be
For crop
Aspect ratio
Width
Height
Quality
X-axis (it a googd option but not commun)
Y-axis (it a googd option but not commun)

For rezize
Width
Height
Quality
=> maybe add a size report ?

For rotate
Angle
Quality

I think its realy important to add a button "Save as a new image" to avoid confusion and better workflow

**Comment by dautrich** [comment]
I don't really get your point. Can you explain more clearly what you would like to achieve!?

**Comment by micker** [comment]
hello for now all options are after images
1 input fields ar in full width, that not good for design, not good to use (accessibility, ususability)
2 order need to be more logical, ex for rezize it not logical to propose quality at first and width after axis ...
we need to be more precise to achieve this impressive features ...

After we need to add a "save as new" its not a good workflow too duplicate at first and edit and save

At end maybe have a size report can be a good help for user to understand quality and size change on image size

**Comment by ghost** [comment]
@laoneo any Comment please?

**Comment by ghost** [comment]
Addes Categorie "Feature Request" at Issue Tracker.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23087">issues.joomla.org/tracker/joomla-cms/23087</a>.</sub>

**Comment by brianteeman** [comment]
@micker there have been quite a few changes since you made this report and the UI has changed for the pages you are referring to. I am going to close this now because of that BUT if you feel there are still issues then it can either be reopened or you can create a new issue
