### ISSUE TITLE
user profil link not wirking after update from joomla 3.8 to 3.9

### ISSUE THREAD

**Issue by technoparck** [joomla/joomla-cms#23081]
### Steps to reproduce the issue
hello 

i have upadted joomla 3.8 to 3.9 and then the user Written by author link is not working any more it don't show any link to click on it , also the issue is on the plugins/content/contact/contact.php when i replace it with the one of the 3.8 verion it show the Written by author link ..

how can i fix this please ?
and how can i ovveride this file to the template ?

### Expected result
same issue with Protostar ,when i replace the plugins/content/contact/contact.php file with the one of joomla 3.8 it works as you look here https://www.screencast.com/t/QBRiB4ICjgtd but when i use the file of 3.9 i don't work https://www.screencast.com/t/hr165Usrmr13

### Actual result
also to test i have installed a new joomla3.9 from joomla.org i have not installed any plugin or component or template and i have create a contact and asigned it to the user on Protostar template , but is give the same issue , that see that the error is on the new update because when i replace plugins/content/contact/contact.php file with the one from the 3.8 version it work correctly 

is there any fix for this ?

### System information (as much as possible)
Joomla! Instance :: Joomla! 3.9.0-Stable (Amani) 30-October-2018
Joomla! Platform :: Joomla Platform 13.1.0-Stable (Curiosity) 24-Apr-2013
Joomla! Configured :: Yes | Read-Only (444) | Owner: --protected-- . (uid: 1/gid: 1) | Group: --protected-- (gid: 1) | Valid For: 3.9
Configuration Options :: Offline: false | SEF: true | SEF Suffix: false | SEF ReWrite: true | .htaccess/web.config: Yes | GZip: false | Cache: false | CacheTime: 15 | CacheHandler: file | CachePlatformPrefix: false | FTP Layer: false | Proxy: false | LiveSite: | Session lifetime: 15 | Session handler: database | Shared sessions: false | SSL: 0 | Error Reporting: maximum | Site Debug: false | Language Debug: false | Default Access: 1 | Unicode Slugs: false | dbConnection Type: mysqli | PHP Supports J! 3.9.0: Yes | Database Credentials Present: Yes | 

Host Configuration :: OS: Linux | OS Version: 4.4.0-112-generic | Technology: x86_64 | Web Server: Apache | Encoding: gzip, deflate | Doc Root: --protected-- | System TMP Writable: Yes | Free Disk Space : 2.31 GiB |

PHP Configuration :: Version: 7.1.24 | PHP API: fpm-fcgi | Session Path Writable: Yes | Display Errors: | Error Reporting: 22519 | Log Errors To: | Last Known Error: | Register Globals: | Magic Quotes: | Safe Mode: | Open Base: | Uploads: 1 | Max. Upload Size: 16M | Max. POST Size: 16M | Max. Input Time: 120 | Max. Execution Time: 120 | Memory Limit: 128M

Database Configuration :: Version: 5.7.24-0ubuntu0.16.04.1 (Client:mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $) | Host: --protected-- (--protected--) | Localhost: Yes | Collation: utf8_general_ci (Character Set: utf8) | Database Size: 14.40 MiB | #of Tables:  250

**Comment by SharkyKZ** [comment]
See if this helps #22904.

**Comment by technoparck** [comment]
ok , thank you very much , i have fixed it the issue was only because link was disable on the plugin i have enabled it and it fixed https://www.screencast.com/t/zxs6XsPimKlm<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23081">issues.joomla.org/tracker/joomla-cms/23081</a>.</sub>
