### ISSUE TITLE
[4.0] New Menu item workflow

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#23086]
### Steps to reproduce the issue
edit or create an item
click on New Menu item

### Expected result

A link to current item with title

### Actual result

Nothing was select, user need to select type of link

I think we need to check context and add value inside
In category => link to category with name
In item => link to item with name
etc ...

**Comment by dautrich** [comment]
I don't really get your point. Can you explain more clearly what you would like to achieve!?

**Comment by micker** [comment]
lol sorry did you test it (its joke)?
no sense to click on "add item link menu" in an item form and need to select type, name etc ...
when you you clic on buy did you need to reselect article in cart ??
it will be automatic

**Comment by chmst** [comment]
I  do not understand either.
If you edit or create an item - which item? A Menu Item for a Menu? While editing a Item, it is not possible to click on "new item" this button exists only on lists. 
 Could you give a screenshot?

**Comment by brianteeman** [comment]
![newmenu](https://user-images.githubusercontent.com/1296369/48639679-36652a80-e9cc-11e8-8a76-c1993d58508f.gif)

**Comment by chmst** [comment]
Thank you ... got it. The item is an article ..

**Comment by micker** [comment]
Yes sorry that the same workflow for category thanks @brianteeman for gif

**Comment by brianteeman** [comment]
Its a bug not a missing feature

**Comment by infograf768** [comment]
The code does not create at all a single article menu item.
It just loads the menu item modal. Only the language would already be filled in case of multilingual site and the item has a language set.
```
				// Setup variables for display
				$linkSuffix = '&amp;layout=modal&amp;client_id=0&amp;tmpl=component&amp;' . Session::getFormToken() . '=1';
				$linkItem   = 'index.php?option=com_menus&amp;view=item' . $linkSuffix;

				// Force the language of the menu item when multilang is implemented
				if (Multilanguage::isEnabled() && $this->form->getValue('language') !== '*')
				{
					$linkItem .= '&amp;forcedLanguage=' . $this->form->getValue('language');
				}

				$urlNew  = $linkItem . '&amp;task=item.add';
```

**Comment by micker** [comment]
Thanks for checking code @infograf768

**Comment by micker** [comment]
i think we need to finish this feature ... or remove add link to menu button because no sense to add information x2

**Comment by brianteeman** [comment]
Closing as this has been resolved elsewhere and is no longer reproducable<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23086">issues.joomla.org/tracker/joomla-cms/23086</a>.</sub>
