### ISSUE TITLE
[4.0][RELEASE_BLOCKER] Reimplement the security check in installer

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#23089]
For development (I assume) the security [check in the Joomla 4.0 installer to prevent use of remote databases has been commented out. ](https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/src/Model/DatabaseModel.php#L200)

This is a security issue if we "forget" to reimplement before release.

This issue, if someone can flag as a release blocker, will serve to ensure this is not forgotten before release.

@joomla/security

**Comment by brianteeman** [comment]
Closed - already here as a release blocker - please search before posting

**Comment by PhilETaylor** [comment]
hmmm I did search, and it never came up in the new GH Beta thing either... strange. At least its there, rather have it double than not at all.

**Comment by zero-24** [comment]
Just for reference here is the issue mention above: https://github.com/joomla/joomla-cms/issues/18736

**Comment by PhilETaylor** [comment]
Yup - ironically I commented the same about this being a release blocker in that issue too ;-)
