### ISSUE TITLE
It is missing an eye icon on Joomla! Web Installer

### ISSUE THREAD

**Issue by todordev** [joomla/joomla-cms#23109]
### Steps to reproduce the issue
Start new  Installation via Joomla! Web Installer and go forward to step 2.

### Expected result
I expect to see an eye icon on the button that I can use to unmask the password.

### Actual result
There is no icon.

### System information (as much as possible)
Firefox 63

![joomla_installer](https://user-images.githubusercontent.com/1272206/48670878-2d896b80-eb28-11e8-92d7-c4b2140be6ff.png)

**Comment by SharkyKZ** [comment]
Test PR #23097 please.

**Comment by SharkyKZ** [comment]
Test PR #23097 please.
