### ISSUE TITLE
[4.0] SUGGEST: Control panel icons design

### ISSUE THREAD

**Issue by acvmultimedia** [joomla/joomla-cms#23103]
### Steps to reproduce the issue

Administrator first page "control panel".

### Expected result

The panel control menu should have a change in 2 icons and I suggest putting a slight green background color.

### Actual result

![screen shot 2018-11-17 at 11 51 00](https://issues.joomla.org/uploads/1/6b15ed3e0055f76b2b4a1de4ab2f1de2.jpg)

**Comment by infograf768** [comment]
This rather easy to do.
But first please lets test and merge https://github.com/joomla/joomla-cms/pull/23095

**Comment by hardik-codes** [comment]
@infograf768 may I go ahead with this issue ?

**Comment by Quy** [comment]
@hardik-codes Joomla! is is community developed software. You do not need to get permission to submit pull requests. Go for it!

**Comment by hardik-codes** [comment]
OK
@Quy could you help me with the files to get started ?

**Comment by hardik-codes** [comment]
@infograf and @Quy which 2 icons need to be changed ?

**Comment by Quy** [comment]
Sorry I don't know. @acvmultimedia please advise.

**Comment by infograf768** [comment]
The background can be modified by changing
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/scss/blocks/_quickicons.scss#L60-L62

to
```
    &.success {
      color: var(--success);
      background: #d9e6d9;
      box-shadow: $quickicon-box-shadow-success;
    }
```
to get, after running npm ci

<img width="659" alt="screen shot 2019-02-01 at 10 16 35" src="https://user-images.githubusercontent.com/869724/52113748-82f2f600-260a-11e9-954a-dfd6036322f4.png">

If we want to change the icons, they will be changed globally, i.e. whatever the status.
Example `'image' => 'fa fa-file-o',` in:
https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/quickicon/overridecheck/overridecheck.php#L87-L96

can be modifed to
`'image' => 'fa fa-file,`
similar for Extensions update to obtain
<img width="614" alt="screen shot 2019-02-01 at 10 25 06" src="https://user-images.githubusercontent.com/869724/52114291-f812fb00-260b-11e9-8664-b12623cf19b5.png">

**Comment by acvmultimedia** [comment]
Thanks @infograf768 that is the idea, I am a designer and no programer can you change it for me in Joomla! 4 core?

**Comment by infograf768** [comment]
Evidently, if we have the use for this background color elsewhere, I guess we could define it as a new `$colors` variable.

**Comment by acvmultimedia** [comment]
OK, for green background #e9ffe5 and icons better with interior filled with color (star and document).

**Comment by infograf768** [comment]
background should correspond to the color we use for Success Messages, that's why I used
`background: #d9e6d9;` which is the same as used in alert.
No usee to introduce new colors imho

**Comment by acvmultimedia** [comment]
Sorry, it´s OK #d9e6d9 thanks @infograf768

**Comment by infograf768** [comment]
Will make PR with a new $colors variable

**Comment by hardik-codes** [comment]
@infograf768 please may I go ahead with this issue

**Comment by infograf768** [comment]
Sorry, already done
https://github.com/joomla/joomla-cms/pull/23733

Please test. Closing as we have a patch.

**Comment by infograf768** [comment]
@hardik-codes 
There is a quite simple way to find out where a code has to be modified:
Use web developper tools ( I use Firefox ) and inspect code.
In 4.0, a specific css may come from different types of scss. 
To test I often put debug system on to test stuff on non-minified files.
Then search how this code is produced. I use often BBEdit multifiles search.

**Comment by acvmultimedia** [comment]
OK I will close Issue?

**Comment by infograf768** [comment]
done
