### ISSUE TITLE
[4.0] Fatal error All Menu Items

### ISSUE THREAD

**Issue by todordev** [joomla/joomla-cms#23108]
### Steps to reproduce the issue
Open All Menu Items.

### Actual result
Fatal error 
You have an error in your SQL syntax;....  `published`,`a`.`component_id`,....

### System information (as much as possible)
Apache/2.4.37 
PHP/7.2.12 
MariaDB/10.1.37

### Additional comments
It will be fixed if you replace 'a.published' with **_null_** in the method **_getListQuery_** in _administrator/components/com_menus/Model/ItemsModel.php_

![sql](https://user-images.githubusercontent.com/1272206/48670830-578e5e00-eb27-11e8-88b5-5281c8062949.png)
![line_267](https://user-images.githubusercontent.com/1272206/48670832-59582180-eb27-11e8-8b64-828912546b2b.png)

**Comment by infograf768** [comment]
On mysqli, I do not get the error, whether I keep present code or modify as suggested.
Don't have MariadB to test.
@alikon

**Comment by tonypartridge** [comment]
I’m a bit puzzled why we are trying to load in the column as it’s self? Suggest replacing it as null like the rest?  Can you do a PR @ITPrism ?

**Comment by csthomas** [comment]
The last change was at https://github.com/joomla/joomla-cms/pull/10281/files

The null array is probably useless. Simply removing the whole array should help.

**Comment by tonypartridge** [comment]
Agreed

Many thanks

**Comment by Quy** [comment]
Please test PR #23293<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23108">issues.joomla.org/tracker/joomla-cms/23108</a>.</sub>
