### ISSUE TITLE
3.9.0: Archived articles included in Category List Layout

### ISSUE THREAD

**Issue by pyberg** [joomla/joomla-cms#23106]
### Steps to reproduce the issue

Create a menu item of type Category List

### Expected result
See a list of published articles in the category

### Actual result
Both published and archived articles are shown

### System information (as much as possible)
Joomla 3.9.0

**Comment by SharkyKZ** [comment]
Are you logged in with admin account?

**Comment by pyberg** [comment]
They are showing for Registered users too.

**Comment by SharkyKZ** [comment]
If Registered users have permission to edit articles, this is expected.

**Comment by GCLW** [comment]
IMO
It should only show up for a registered user that has the ability to change the "state" of the article, not edit alone. Default Registered, Author, or Editor, permissions do not have that ability, so they should not be able to see it. A Publisher should.



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23106">issues.joomla.org/tracker/joomla-cms/23106</a>.</sub>

**Comment by SharkyKZ** [comment]
How are you going to edit the article if you can't see it?

**Comment by GCLW** [comment]
It is an Archived article. Sort of goes against logic of "Archiving" something if you are going to be editing it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23106">issues.joomla.org/tracker/joomla-cms/23106</a>.</sub>

**Comment by rdeutz** [comment]
This is expected behaviour, if you like to edit an article you have to get this article out of the archive. All this can be done from the admin interface.

**Comment by pyberg** [comment]
It turned out Public was mistakenly given Edit Permissions to the category.
