### ISSUE TITLE
Joomla Site / Google Authenticator needs Site Name

### ISSUE THREAD

**Issue by OzzieBob** [joomla/joomla-cms#23101]
### Steps to reproduce the issue
Enable 2FA for a Joomla user account
Either Scan the QR Code or manually type the code into Google Authenticator

### Expected result
Item created in Authenticator with a site name / identifier  

### Actual result
Item created in Authenticator with no site name / identifier 

### System information (as much as possible)
Google Authenticator (ios)
Joomla Website(s) 3.9.0 / PHP 7.1.24

### Additional comments
There needs to be a way of having the Site name display in Google Authenticator, as it does with other non-Joomla sites. If you manage/administer multiple Joomla websites, this is essential to be able to use 2FA, but even for one off sites it would be a useful feature.

**Comment by brianteeman** [comment]
I cannot confirm this on android. google authenticator displays username@domainname below each OTP

**Comment by OzzieBob** [comment]
Just to clarify, I am talking about the Site Name (above the code) not the email address below.  The Email address used for the user account may not necessarily tied to the website domain.

If you look at other codes in Google Authenticator they generally present as:

**Site Name

**1 2 3 4 5 6**
Account Name**

However in Joomla Sites, it presents as:

**1 2 3 4 5 6**
Account Name**

**Comment by brianteeman** [comment]
in the examples above none of them are my email address or the email address of the user
they are all
USERNAME@DOMAIN

**Comment by brianteeman** [comment]
ah - sorry I understand now what you are requesting. Its the issuer param that is displayed above the number

**Comment by brianteeman** [comment]
https://github.com/google/google-authenticator/wiki/Key-Uri-Format#issuer

**Comment by brianteeman** [comment]
Unfortunately I tried to make the required change but even when using the samples directly on the doc site the authenticator app did not recognise the "issuer" - this was before I tried to add it to Joomla

**Comment by kjetil-kilhavn** [comment]
I have the same issue. I had to disable two-factor authentication when switching to a Google Android-phone from my previous Sailfish OS-phone, and have not been able to activate it again. In the mean time I have updated the site to Joomla 3.9.8 and the problem persists.

**Comment by brianteeman** [comment]
You absolutely do not have the same problem. The "problem" referred to here is purely a cosmetic issue.

Your problem is because there is no way provided by google for you to "move" from one phone to another and it is expected that you have to create a new authentication when you change device. This is beyond joomla's control

**Comment by kjetil-kilhavn** [comment]
Ahh.. Sorry, I thought the authenticator wasn't working. Obviously didn't read the description thoroughly enough. Then I agree it's absolutely not the same issue as in my case I am not able to enable 2 factor authentication with Google again. I don't know if it is beyond Joomla's control or not, but I don't have the same problem with Github. Anyway, leaving this thread now :-)

**Comment by Quy** [comment]
Please test PR #27368
