### ISSUE TITLE
Is there a way to list specific tags?

### ISSUE THREAD

**Issue by lasanthaa** [joomla/joomla-cms#23102]
I am using joomla  3.8.1 for bookstore cms. I want to list some specific tags as a list (to list all authors). But there is a option to list all tags a list. Is there a way to do this?

**Comment by Quy** [comment]
Maybe use the `Parent Tag` option.

**Comment by Quy** [comment]
Use `Parent Tag` option. For further help, please ask in [Joomla Forum](https://forum.joomla.org/).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23102">issues.joomla.org/tracker/joomla-cms/23102</a>.</sub>
