### ISSUE TITLE
Create custom field sub groups

### ISSUE THREAD

**Issue by johanpeters** [joomla/joomla-cms#23117]
I would like to see sub groups for custom fields..
currently only 1 level of groups are possible.. it would be nice to have subgroups..
for example .. for user custom fields..
create a tab (fieldgroup)
inside that tab (depending on template).. in colums the sub fieldgroups.

Example.
fields
- function
- employeenumber
- Employment status
- speciality
- teammember
- projectmember

fieldgroup Company
sub fieldgroup Employee
sub fieldgroup Department

On the user profile 
Tab Company
Employee .                                 Department
- function                                   - teammember
- employeenumber                   - projectmember
- employment status
- speciality

etc.etc.etc..

**Comment by Bakual** [comment]
Imho that goes beyond what custom fields are intended for. It would mean that each template has to also support "nested" forms (eg tabs within a tab or columns like you suggested) which is used nowhere else in core.

But then, nothing should stop you from displaying your custom fields the way you want them to appear. You just need to create an override for that form.

**Comment by AndySDH** [comment]
Yeah I don't think this is needed and as @Bakual  mentioned it would make things really complicated in forms and in frontend also.

Field Groups are a way to display similar fields together in forms and frontend, not field categories.

**Comment by laoneo** [comment]
Funny thing is we had that in the initial draft as groups had been categories. Then it got changed to a new entity groups :-)

**Comment by AndySDH** [comment]
> Funny thing is we had that in the initial draft as groups had been categories. Then it got changed to a new entity groups :-)

Yeah, I remember that. I think it makes more sense as it is now :)

**Comment by ghost** [comment]
@laoneo closing the Issue?

**Comment by ghost** [comment]
Closed due the lack of Response.
