### ISSUE TITLE
[SOLVED] [4.0 Alpha 6-dev] Fatal error in the left submenu in administration

### ISSUE THREAD

**Issue by acvmultimedia** [joomla/joomla-cms#23110]
### Steps to reproduce the issue

Lunch Joomla! alpha6-dev

### Expected result

Display submenu

### Actual result

It´s not possible to display submenu and this issue it´s only in alpha 6 because in alpha 5 it was fine.

### System information (as much as possible)

Alpha6-dev in launch Joomla!

**Comment by acvmultimedia** [comment]
Hello,

I tried to create an article and it´s impossible, I think the problem it´s related.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23110">issues.joomla.org/tracker/joomla-cms/23110</a>.</sub>

**Comment by infograf768** [comment]
Modified Priority as can't be reproduced.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23110">issues.joomla.org/tracker/joomla-cms/23110</a>.</sub>

**Comment by acvmultimedia** [comment]
Right, I just saw that they have removed the alpha 6 and have put back the alpha 5 y Joomla! Launch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23110">issues.joomla.org/tracker/joomla-cms/23110</a>.</sub>

**Comment by infograf768** [comment]
Closing. Please use nightly builds to test alpha6-dev.
