### ISSUE TITLE
[4.0] Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#23115]
### Steps to reproduce the issue
Go to `Global Configuration`.
Click `Save` button.
View PHP error log file.

### Actual result
`Invalid argument supplied for foreach() in \libraries\src\Form\Rule\RulesRule.php on line 104`

### System information (as much as possible)
v4alpha6

**Comment by infograf768** [comment]
I confirm this.

**Comment by infograf768** [comment]
`$elActions` is boolean in 4.0 while it is an array in 3.x, thus why we get this Invalid argument

**Comment by infograf768** [comment]
Maybe we need to do
```
		// Iterate over the asset actions and add to the actions.
		if ($elActions)
		{
			foreach ($elActions as $item)
			{
				$actions[] = $item->name;
			}
		}
```
@laoneo ?

**Comment by Quy** [comment]
Since`$elActions` is a boolean, then there is no purpose in looping through it as if it is an array.

**Comment by laoneo** [comment]
You are right, please test #23125.

**Comment by infograf768** [comment]
Closing as we have https://issues.joomla.org/tracker/joomla-cms/23125
