### ISSUE TITLE
Question concerning Image class

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#23118]
[3.9]

In file `libraries/src/Image/Image.php` I see a deprecated comment. `@deprecated  5.0 Use the class \Joomla\Image\Image instead`

In `libraries/vendor/joomla/image/src/Image.php` is a deprecated comment, too. `@deprecated  The joomla/image package is deprecated`.

What's the future of the Image class? Will it be removed completely and one should start to write a custom helper class for custom extensions?

**Comment by SharkyKZ** [comment]
See #22817.

**Comment by ReLater** [comment]
Thank you
