### ISSUE TITLE
Reset checked_out value to DEFAULT instead of 0 in global checkin

### ISSUE THREAD

**Issue by julienV** [joomla/joomla-cms#23121]
### Steps to reproduce the issue
In our component, we use a foreign key with constraint on checked_out column to the #_users table, to that we can use ON UPDATE/DELETE feature. To make this work, the default value must be null, and not 0, as there is no user with id 0.
It works fine while doing checkins internally to our component, but we get an error when use Joomla! global checkin feature on our tables, as it tries to set the value back to 0 instead of null.
The solution for this is to use DEFAULT keyword instead of 0 in the query. 

### Expected result
Checkin should reset checked_out value to the table column default

### Actual result
it tries to reset the value to 0

### System information (as much as possible)
joomla 3.9.0

**Comment by Quy** [comment]
See PR #23122<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23121">issues.joomla.org/tracker/joomla-cms/23121</a>.</sub>
