### ISSUE TITLE
DSGVO - Privacy information export does not work

### ISSUE THREAD

**Issue by TheFallenWolf** [joomla/joomla-cms#23128]
### Steps to reproduce the issue
Exporting a DSGVO-sheet after getting a user-request via the ACP, either by direct download or by mail.

### Expected result
Complete user-informations-sheet is created and downloaded/sent by mail.

### Actual result
Exported file with that only says this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<data-export>
  <domain name="user_contact" description="joomla_user_contact_data"/>
  <domain name="contact_contact_custom_fields" description="joomla_contact_contact_custom_fields_data"/>
</data-export>
```

### System information (as much as possible)
See attached file[systeminfo-2018-11-20T17_14_52+01_00.txt](https://issues.joomla.org/uploads/1/e14ed9b8f4bee8dbd11beace7170872e.txt)

### Additional comments
This would be a rather important thing to find a solution for, as I have to provide the information to our users in some way. Thanks!

**Comment by TheFallenWolf** [comment]
Oh, seems like i mistyped the code, sorry for that.
The current output is:

```php
<?xml version="1.0" encoding="utf-8"?>
<data-export>
  <domain name="user_contact" description="joomla_user_contact_data"/>
  <domain name="contact_contact_custom_fields" description="joomla_contact_contact_custom_fields_data"/>
</data-export>
```

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23128">issues.joomla.org/tracker/joomla-cms/23128</a>.</sub>

**Comment by mbabker** [comment]
You will need to enable error reporting and provide an actual error message for us to diagnose this.  An empty export is valid if for whatever reason no data is found at all in supported plugins/contexts.

**Comment by Quy** [comment]
Closing for now until additional information is provided.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23128">issues.joomla.org/tracker/joomla-cms/23128</a>.</sub>
