### ISSUE TITLE
Privacy features also for backend

### ISSUE THREAD

**Issue by mc-cm** [joomla/joomla-cms#23134]
### Steps to reproduce the issue

see issue #22659

Seems I'm the only one who actually has the requirement for the privacy consent features in backend of Joomla.
I have many users whom I give backend access (actually all publishers) to the sites. We do a backend only strategy, and therefor I'd like to see the consent privacy features of J3.9 applied also to the backend. Thanks!

see issue #22659

### Expected result
Users need to give their consent to the privacy policy when they login to the backend of Joomla. In their profile they also should be able to request the export or deletion of their data. Same as in frontend.

### Actual result
Not possible at the moment, see #22659

### Additional comments

**Comment by mbabker** [comment]
If someone wants to add an option to do so, it will be evaluated.  But, it should not be a hard requirement the same way it is for the frontend (so basically, you should still be able to require the consents but only on the frontend, or both apps, if configured).

Part of the thinking here is that your public facing privacy policies are going to be dealing with how anyone interacts with the public facing aspect of your site (anything that's not in the `/administrator` area, including when logged into the front end).  Whereas if you're agreeing to policies for the backend, in many cases you would actually need to consent to some form of privileged access agreement or some other addendum on top of the public facing documents (privacy policy, terms of service, etc.).  Adding a consent option for this backend access agreement is a great opportunity for a plugin, but I don't feel like this bit has to be part of core.

**Comment by alikon** [comment]
closing as it is a new feature and that if wanted can be made by extension developers, not something from core<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23134">issues.joomla.org/tracker/joomla-cms/23134</a>.</sub>
