### ISSUE TITLE
[com_actionlogs] no logs recorded, database may be inconsistent

### ISSUE THREAD

**Issue by mtomzig** [joomla/joomla-cms#23133]
I've got an Joomla instance running on Windows Server 2012 R2 with IIS, PHP and Microsoft SQL database server.

With the last Joomla update to version 3.9.0 a new component com_actionlogs was provided. Unfortunately i could not get the log running. After a look into the database (and an comparison to an Joomla installation on an MySQL server) i recognized that the table structure is different. After a look into the sql installation files of the new version i recognized the following:

`file: administrator/components/com_admin/sql/updates/sqlazure/3.9.0-2018-05-05.sql`

This is the syntax for creating the new table:
`CREATE TABLE [#__action_log_config](`
`	[id] [int] IDENTITY(1,1) NOT NULL,`
`	[type_title] [nvarchar](255) NOT NULL DEFAULT '',`
`	[type_alias] [nvarchar](255) NOT NULL DEFAULT '',`
`	[title_holder] [nvarchar](255) NULL,`
`	[table_values] [nvarchar](255) NULL`
`	CONSTRAINT [PK_#__action_log_config_id] PRIMARY KEY CLUSTERED`
` (`
` 	[id] ASC`
` )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]`
` ) ON [PRIMARY];`

This ist the insert statement for this table (just one insert for example):
`INSERT INTO [#__action_log_config] ([id], [type_title], [type_alias], [id_holder], [title_holder], [table_name], [text_prefix])`
`SELECT 1, 'article', 'com_content.article', 'id' ,'title' , '#__content', 'PLG_ACTIONLOG_JOOMLA'`

The columns for create and index aren't matching.

What can I do to get things working.

**Comment by alikon** [comment]
#23136 should fix inconsistecy
