### ISSUE TITLE
[com_fields] Ability to create and assign alternate layout to custom fields values

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-cms#23138]
I was told by @Bakual to open a new issue for this so here it is.

PR #18571 added the ability to assign different layouts at a FIELD level (override for: "components/com_fields/layouts/fields/render.php" - so before knowing which field type it's going to render), which is great.
But in addition to this, we also need the ability to assign different layouts for individual values of specific field types that include multiple values, such as list, checkboxes, and repeatable/subform (for example, override for values of a list field would be: "plugins/fields/list/tmpl/list.php")

This can come useful in preparation for the repeatable/subform field finalization (#22446), as it would allow to create for example a table layout for the repeatable/subform field type as mentioned in #20243.

Or for example, as suggested by @laoneo in #20243, a UL layout for a list field type:
> I would rather see a new function in core to define a default layout for the > field and provide different layouts for the same field type. For the list it would mean to add a new file > here like /plugins/fields/list/tmpl/list_ul.php and then provide these layouts as option in the field.
> What do you guys think?

In the Field Editing it could look something like:

![image](https://user-images.githubusercontent.com/25923699/48864481-f7b8e100-edcc-11e8-9804-034eb43c1ad9.png)
(Possibly for clarity we could rename the "Layout" option to "Field Layout")

And of course, the dropdown there would list the **layout files ONLY for that field type**. So a field of type "list" would only display files included in "/plugins/fields/list/tmpl/"

What do you think? Can you @laoneo or @Bakual or someone else create a PR for this?

**Comment by Bakual** [comment]
It probably doesn't make sense for plugins other than the custom fields ones. Since the other plugins (eg vote, pagebreak) only have one instance and already can be overridden. You don't need the possibility for more than one layout there.

For the custom field type plugins I can see a slim usecase to have multiple different layouts for the values since you can have multiple "instances" of the same plugin active.
So if someone wants to have a take at it, go ahead. Best probably to create a new field similar to `JFormFieldComponentlayout` and `JFormFieldModulelayout` and then add the proper logic to the custom field classes somewhere.

**Comment by AndySDH** [comment]
> It probably doesn't make sense for plugins other than the custom fields ones. Since the other plugins (eg vote, pagebreak) only have one instance and already can be overridden. You don't need the possibility for more than one layout there.
> 
> For the custom field type plugins I can see a slim usecase to have multiple different layouts for the values since you can have multiple "instances" of the same plugin active.

Yeah, of course, this is just for custom fields, not meant for other plugins.

**Comment by AndySDH** [comment]
Was hoping you could take a crack at it :P

**Comment by Bakual** [comment]
I probably don't have the time :-)

**Comment by laoneo** [comment]
Me neither

**Comment by AndySDH** [comment]
Well, that's too bad :(
I'd do it myself if I had the knowledge to do it but unfortunately I don't.
It would be a pretty essential feature for the repeatable field as different ways to display it are very necessary for that (to the point where I would even consider packing some preset basic layouts, like a table, by default in the core)

**Comment by jwaisner** [comment]
Features are not available to be added to J3. Please review J4 and if this feature is still requested then please open a request.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23138">issues.joomla.org/tracker/joomla-cms/23138</a>.</sub>

**Comment by brianteeman** [comment]
Reopening and tagging "re-evaluate for j4"

I really dont understand why you are closing all these issues without even the courtesy of checking it yourself

**Comment by AndySDH** [comment]
As per the tag "J4 Re-evaluate", can this be re-evaluated by someone? :P

Maybe for J4.1 if it's too big of an addition to make it for J4.
