### ISSUE TITLE
SMTP not working in Joomla 4 Alpha 5

### ISSUE THREAD

**Issue by robs12345** [joomla/joomla-cms#23130]
### Steps to reproduce the issue
Enter SMTP settings into the Global Config page, Server tab.
Click 'Send Test Mail'

### Expected result
Receive a test email.

### Actual result
Nothing. The screen did not respond to the Test Email button.
Debugging ON, no info there either.

### System information (as much as possible)

PHP Built On	Linux sh34-554.ich-5.com 2.6.32-042stab116.2 #1 SMP Fri Jun 24 15:33:57 MSK 2016 x86_64
Database Type	mysql
Database Version	5.6.41
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8_general_ci
PHP Version	7.2.12
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 4.0.0-alpha5 Alpha [ Amani ] 4-November-2018 23:23 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

### Additional comments
SMTP Settings exactly the same as in Joomla 3.9 on same server.

**Comment by joeforjoomla** [comment]
Confirmed, SMTP with the new version of PHPMailer does not work anymore.

**Comment by roland-d** [comment]
Hello, closing this issue as there is a pull request #23591
