### ISSUE TITLE
[4.0] SUGGEST: Weblink Categories and expired weblinks

### ISSUE THREAD

**Issue by kgeary007** [joomla/joomla-cms#23131]
### Is your feature request related to a problem? Please describe.
If a weblink category has no published links it does not display in the front end.
If a weblink category has been published and then it's weblinks are unpublished, the category still displays.

If a Finish Publishing date is set for a weblink, in the admin section it will show a status icon yellow when the expiration date arrives but the weblink does not automatically unpublish.

### Describe the solution you'd like
When the Finish Publishing date arrives the weblink automatically unpublishes.
When a weblink category has no published links, the category does not display.

**Comment by Bakual** [comment]
Please open this issue at https://github.com/joomla-extensions/weblinks/issues as Weblinks is a decoupled extension.
