### ISSUE TITLE
Site-Module "Login": Field "Caching" show only "No caching"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#23147]
### Steps to reproduce the issue
Open Module "Login", Advanced-Tab: Field "Caching" show in dropdown only "No caching". Tooltip say "Use the global cache setting to cache the content of this module or disable caching for this module".

Edit: Same in Module "Random Image" #23162 and "Syndication Feeds" #23163. 

![bildschirmfoto 2018-11-23 um 09 12 10](https://user-images.githubusercontent.com/8235763/48933398-6c406c80-ef00-11e8-9987-1363c9700a52.png)
### System information
- 3.9
- Template: Protostar
- macOS Sierra, 10.13.6
- Firefox 63 (64-bit)
#### CloudAccess.net
- PHP 7.1.24
- MySQLi 5.7.18-cll-lve
### Additional comments
Similar Modules show "Use Global/No caching" and the Field "Cache Time".

**Comment by brianteeman** [comment]
The tooltip is incorrect as correctly these should not be cachable. It is using the generic tooltip.

**Comment by alikon** [comment]
then we don't need  that field at all #23152

**Comment by Quy** [comment]
Reopening as there are two other modules affected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23147">issues.joomla.org/tracker/joomla-cms/23147</a>.</sub>

**Comment by ghost** [comment]
thanks for comments and PR. If the unneeded Cachefield is removed from Modules maintenance of Helpscreens get a little easier :-)

**Comment by ghost** [comment]
@Quy should i open issues for each module?

**Comment by ghost** [comment]
closing as all 3 Modules have its own Pull Request now. Thanks all for Comments and work.
