### ISSUE TITLE
Media options update

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#23142]
### Is your feature request related to a problem? Please describe.

Update Legal Extensions (File Types), Legal Image Extensions (File Types), Legal MIME Types

### Describe the solution you'd like

My snippets based on default JCE File Browser:
https://gitlab.com/snippets/1782418

**Comment by zero-24** [comment]
Hi, we should at least keep off the `,swf,SWF,` & `,application/x-shockwave-flash` as this has been removed for many reasons including security. For the others I'm not sure if we should whiteliste all that file types. By knowing that most of the sites would never use it nor would the hosting (core upload filter) detect them as valid at all.

**Comment by ghost** [comment]
Hi,
You're right about the files `swf,SWF` & `application/x-shockwave-flash`. 
I forgot about it, but I have already excluded this type of files.
If you think that the rest is useless, you can at least add support for Office 365 files, including docx, pptx, xlsx.

**Comment by Quy** [comment]
Lets decide if to include Office 365 files, including docx, pptx, xlsx only.

**Comment by brianteeman** [comment]
I would not be in favour of that @quy as other non microsoft applications create the old style doc, xls and ppt files. I am also personally using office 2016 which is not end of life until the end of 2020. I dont see any advantage in this change or am i missing something

**Comment by Quy** [comment]
This is to keep existing ones and decide which new ones to add.

**Comment by dgrammatiko** [comment]
Partially updated with: #34634
