### ISSUE TITLE
Modules: Remove Tab "Description" on 2 Types

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#23141]
### Is your feature request related to a problem?
Make maintaning of helpscreens easier as more chunks can be used. Belongs to Site-Module
#### "Articles - Related" 
![screenshot_2018-11-22 modules articles - related - 3 9 - administration](https://user-images.githubusercontent.com/8235763/48908340-46688880-ee6a-11e8-9b47-9423193e20d9.png)
#### "Language Switcher".
![screenshot_2018-11-22 modules language switcher - 3 9 - administration](https://user-images.githubusercontent.com/8235763/48908348-4bc5d300-ee6a-11e8-9121-a44e0c6a87ea.png)
### Describe the solution you'd like
Short Description on first Tab "Module" and/or write to click on help-button.

**Comment by brianteeman** [comment]
iirc the description tab is automatically displayed if the module description is longer than a set number of characters

**Comment by ghost** [comment]
thanks for sharing your knowledge, Brian.

**Comment by brianteeman** [comment]
This should be closed. The code is working as intended
