### ISSUE TITLE
News Feeds not working in 3.9

### ISSUE THREAD

**Issue by shz99** [joomla/joomla-cms#23150]
### Steps to reproduce the issue
created a couple of news feeds under Components -- News Feeds and set up a Category. Then I created a menu item to to List News Feeds in a Category and selected the category for the news feeds. 

### Expected result
The menu item opens a page listing the news feeds under the category. When clicking each title of News Feeds, it should open a page for the feed details

### Actual result
Although the menu item opens a page listing the news feeds under the category,  when clicking the feed' title, I got a page showing error and NO content of the news feed at all. 

### System information (as much as possible)
The error message: 

"0 No registered feed parser for type html."

**Comment by SharkyKZ** [comment]
It means the link you entered as feed source is a HTML page. But it has to be a valid Atom or RSS feed.

**Comment by shz99** [comment]
Got it. Thanks a lot!

**Comment by infograf768** [comment]
closing as not joomla issue
