### ISSUE TITLE
All popup seems not rendered properly. they don't load bootstrap.

### ISSUE THREAD

**Issue by ranggasito** [joomla/joomla-cms#23156]
### Steps to reproduce the issue
I'm currently developing Joomla's component for my client. I need media form field and editor form field in a form page to input the data I need.

### Expected result
it should be work just like in administrator system.

### Actual result
all plugins button in the editor form field (article, image, contact, menu, module) are not worked as expected in administrator site. in the pop up frame seems they don't load bootstrap(see the images in attachment. I tried to insert codes to load bootstrap in the com_media layout and it worked. so I assume this is a bug. And I also tried in all default templates in Joomla and still it has the same result.

### System information (as much as possible)
Joomla 3.9.0
PHP 7.2.0

### Additional comments
below are the results : 

![image](https://user-images.githubusercontent.com/8582431/48968105-8c654e00-f01c-11e8-8e74-8fb16bb86d5f.png)

![image](https://user-images.githubusercontent.com/8582431/48968114-bae32900-f01c-11e8-95a5-91e06c16e97d.png)

![image](https://user-images.githubusercontent.com/8582431/48968118-cd5d6280-f01c-11e8-8f43-370e6a59d5e1.png)

![image](https://user-images.githubusercontent.com/8582431/48968121-e239f600-f01c-11e8-9062-a0729cb85eb3.png)

![image](https://user-images.githubusercontent.com/8582431/48968127-f5e55c80-f01c-11e8-9990-3a01c173c0b4.png)

**Comment by mbabker** [comment]
The modals use your active template's `component.php` file.  Joomla core does not arbitrarily load the Bootstrap assets anywhere, but the core templates do as they are built on Bootstrap.

You will need to ensure your template is loading Bootstrap (adding `JHtml::_('bootstrap.loadCss');` to the `component.php` file will do the trick), or create layout overrides and adapt those to your template's theming.

Closing as this is not a core bug.
