### ISSUE TITLE
PHP 7.2 Use of undefined constant MCRYPT_RIJNDAEL_128

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#23151]
### Steps to reproduce the issue

Use the Joomla encrypt classes from fof
PHP 7.2 compatibility 

### Actual result

```
[Fri Nov 23 11:59:07 2018] PHP Warning:  Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128' (this will throw an Error in a future version of PHP) in /Users/phil/example.com/libraries/fof/encrypt/aes.php on line 170
[Fri Nov 23 11:59:07 2018] PHP Warning:  Use of undefined constant MCRYPT_MODE_CBC - assumed 'MCRYPT_MODE_CBC' (this will throw an Error in a future version of PHP) in /Users/phil/example.com/libraries/fof/encrypt/aes.php on line 170
```

https://github.com/joomla/joomla-cms/blob/ddfa622365c1c7be975e744a2a5ba4de674f07fb/libraries/fof/encrypt/aes.php#L170

### Expected result

No errors

### System information (as much as possible)

PHP 7.2 command line

### Additional comments

@nikosdion states:

> The latter two notices come from FOF 2 which is part of Joomla!. I terminated support for FOF 2 in mid-2016. FWIW the latest FOF 2 version I supplied to Joomla! does not have this problem. We are detecting mcrypt or OpenSSL presence and we prefer to use the latter.

**Comment by PhilETaylor** [comment]
MCRYPT_RIJNDAEL_128 is also used in restore.php

https://github.com/joomla/joomla-cms/blob/ddfa622365c1c7be975e744a2a5ba4de674f07fb/administrator/components/com_joomlaupdate/restore.php#L6916

and MCRYPT_MODE_CBC

https://github.com/joomla/joomla-cms/blob/ddfa622365c1c7be975e744a2a5ba4de674f07fb/administrator/components/com_joomlaupdate/restore.php#L6918

**Comment by mbabker** [comment]
If you're doing blind searches for anything mcrypt related you're going to find a lot of references.  The fact they exist is not a problem.  If they are actually being used on PHP 7.2, it is a problem.  If you look at the restore.php code you will find that class is conditionally instantiated therefore those lines you highlighted are only executed if that condition is true.

**Comment by mbabker** [comment]
Also take into consideration that the extension is installable via PECL.  Therefore, a straight up "mcrypt should not be executed on PHP 7.2" policy cannot apply to any code, you must continue to use `extension_loaded()` checks.

**Comment by zero-24** [comment]
> Use the Joomla encrypt classes from fof

Simple solution don't use `$adapter = new FOFEncryptAesMcrypt();`  but  `$adapter = new FOFEncryptAesOpenssl();` :P 

But this here: https://github.com/joomla/joomla-cms/blob/ddfa622365c1c7be975e744a2a5ba4de674f07fb/libraries/fof/encrypt/aes.php#L34-L69 should make sure there is no problem at all unless you decide to override the adapter `priority`?

So how can you reproduce the problem, without directly using `$adapter = new FOFEncryptAesMcrypt();`?

**Comment by PhilETaylor** [comment]
>So how can you reproduce the problem

This problem came to light when moving a Joomla site to localhost which is PHP 7.2, and on restoring the site using Akeeba ANGIE wizard 6.3.0.

**Comment by zero-24** [comment]
> This problem came to light when moving a Joomla site to localhost which is PHP 7.2, and on restoring the site using Akeeba ANGIE wizard 6.3.0.

Can you reproduce the problem on a clean install without 3rd Party Software on the same localhost running PHP 7.2?
