### ISSUE TITLE
Make administrator module titles multilingual

### ISSUE THREAD

**Issue by Pinkeltje** [joomla/joomla-cms#23157]
### Is your feature request related to a problem? Please describe.
No real problem. Just suggestion.

### Describe the solution you'd like
Titles are now all in English. When administrator language is set to different language, module titles stay English.
![20181124-1419-008](https://user-images.githubusercontent.com/8941310/48969140-9413fb00-effa-11e8-9385-57fc53de84c7.png)

**Comment by Bakual** [comment]
That's because the module title is something the administrator enters when he creates or edits the module. Similar to article or menu titles.
If you really need them in different languages, you can create multiple module instances and assign them to each language with each having the proper title.

**Comment by Pinkeltje** [comment]
I understand and I can change module titles, but when installing a clean Joomla, a certain number of modules is automatically published on the dashboard. Resulting in a partial English backend.

**Comment by brianteeman** [comment]
Or just use the automatic title option which is designed exactly for this

**Comment by Bakual** [comment]
> when installing a clean Joomla, a certain number of modules is automatically published on the dashboard. Resulting in a partial English backend.

Yep, that's because they are hardcoded in the SQL files.

> Or just use the automatic title option which is designed exactly for this

Those only work for certain modules and the feature is disabled by default 😄

**Comment by coolcat-creations** [comment]
Idea for a PR: Just wrap a JText around it to make them translateable... No?

**Comment by brianteeman** [comment]
We already have two ways to display the module titles in the admin in multiple languages - do we really need a third

**Comment by mbabker** [comment]
> We already have two ways to display the module titles in the admin in multiple languages - do we really need a third

No.

**Comment by brianteeman** [comment]
This should be closed as it is already possible
