### ISSUE TITLE
[4.0] contact form not responsive

### ISSUE THREAD

**Issue by AlainRnet** [joomla/joomla-cms#23177]
### What needs to be fixed
I tried J4 on Joomla.com and I see that fields aren't responsive : http://artisanduweb.joomla.com/index.php/contact.html?view=contact&id=1

![photo_2018-11-27_09-51-12](https://user-images.githubusercontent.com/6475120/49069639-07e81a80-f22a-11e8-98ae-e0d8e977b208.jpg)

### Why this should be fixed
CSS ? Somtehing like :
@media(max-width: 768px){
form:not(.form-no-margin) .control-group .controls {margin-left: 80px;}
}
@media(max-width: 480px){
form:not(.form-no-margin) .control-group .control-label {float: none;}
form:not(.form-no-margin) .control-group .controls {margin: 0;}
}

**Comment by C-Lodder** [comment]
Ideally the form layouts need to be rewritten using flexbox rather than a set width for the label, floats and left margins.

**Comment by jwaisner** [comment]
@AlainRnet are you still experiencing this in the latest J4 build?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23177">issues.joomla.org/tracker/joomla-cms/23177</a>.</sub>

**Comment by AlainRnet** [comment]
No, everything is OK now.
Thank you for the follow-up.
Regards.
