### ISSUE TITLE
Weblinks categories: Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#23172]
### Steps to reproduce the issue
1. Install Weblinks 3.6.0 Package from https://extensions.joomla.org/extensions/extension/official-extensions/weblinks/ on Joomla 3.9.0 using PHP 7.2 and set to report PHP warnings.
2. Go to Components - Web Links and add any URL as New Web Link to the existing category Uncategorised with default options, Save & Close.
3. Create a new menu item and select Web Links - List All Web Link Categories with default options, Save & Close.
4. Go to the front end and select the new link.

### Expected result
The list shows the category Uncategorised.

### Actual result
Warning: count(): Parameter must be an array or an object that implements Countable in C:\www\joomla380\components\com_weblinks\models\categories.php on line 95

The list shows the category Uncategorised.

### System information (as much as possible)
Joomla 3.9.0
PHP 7.2.11

### Additional comments
Fixed by inserting the following lines before line 95 in 
components/com_weblinks/models/categories.php

		if (!is_array($this->_items))
		{
			$this->_items	= array();
		}

Ref. topic "Weblinks Categories page - Warning: count() at https://forum.joomla.org/viewtopic.php?f=715&t=967481

**Comment by SharkyKZ** [comment]
Please open this issue at https://github.com/joomla-extensions/weblinks/issues as Weblinks is a decoupled extension.

**Comment by infograf768** [comment]
Also, I can't reproduce your issue here on 3.9.1-rc
I always get 2 arrays, even if the first one if NULL

**Comment by toivo** [comment]
I do not know about 3.9.1-rc but I have now reproduced the warning in an out-of-the-box Joomla 3.9.0 updated with Joomla_3.9.1-dev-Development-Update_Package.zip.

Also in the code available from https://github.com/joomla-extensions/weblinks the file models/categories.php is identical to version 3.6.0.

 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23172">issues.joomla.org/tracker/joomla-cms/23172</a>.</sub>

**Comment by toivo** [comment]
In any case, submitted https://github.com/joomla-extensions/weblinks/issues/393<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23172">issues.joomla.org/tracker/joomla-cms/23172</a>.</sub>
