### ISSUE TITLE
Notice Undefined index: HTTP_HOST

### ISSUE THREAD

**Issue by ZerooCool** [joomla/joomla-cms#23170]
### Steps to reproduce the issue
Joomla last stable version.
Apache2.4
Php7.2
Debian

I see this notice in /var/log/apache2/error.log :

[php7:notice] PHP Notice: Undefined index: HTTP_HOST in /var/www/html/libraries/src/Application/WebApplication.php on line 992
[php7:notice] PHP Notice: Undefined index: HTTP_HOST in /var/www/html/libraries/src/Uri/Uri.php on line 90

**Comment by Quy** [comment]
See PR #17655<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23170">issues.joomla.org/tracker/joomla-cms/23170</a>.</sub>
