### ISSUE TITLE
[3.9.1] user action log - is logging things twice

### ISSUE THREAD

**Issue by n00bster** [joomla/joomla-cms#23179]
### Steps to reproduce the issue
1) i have updated from 3.8.13 to 3.9.1
2) i have setup the module for the user action log in the admin area
3) i have enabled the system plugin user action log

### Expected result
i think it should only log one entry per login activity from a users login in the frontend.

### Actual result
a user login activity get`s logged twice. see picture!
![2018-11-27_18-42-23](https://user-images.githubusercontent.com/1003469/49100957-625a9880-f275-11e8-89c3-40bbe1125129.png)

### System information (as much as possible)
Database Version | 5.5.5-10.2.15-MariaDB
Database Collation | utf8mb4_general_ci
PHP Version | 7.2.11

**Comment by peterpeter** [comment]
Can not confirm this issue - on three sites with action-log enabled every login/-out action is logged only once.

**Comment by n00bster** [comment]
> Can not confirm this issue - on three sites with action-log enabled every login/-out action is logged only once.

ok, thx for feedback.
the problem is not continuous, as you can see it does not affect all logins. 
![2018-11-28_11-14-59](https://user-images.githubusercontent.com/1003469/49145131-659a6680-f2ff-11e8-9c7a-26e6dcd6f9ec.png)
maybe it has something to do with the joomla sessions. sometimes i notice that on the login i got the message that the token is outdated and i have to login again...

**Comment by peterpeter** [comment]
Or maybe it is related to the/a redirect after login and/or other used 3rd URL/Routing extensions if any.
You could try another redirect after login or non SEF-Urls, or both.

**Comment by tonypartridge** [comment]
Is it possible they are double clicking extremely fast that the token has not had chance to expire at the time of login?

**Comment by Quy** [comment]
This can be reopened when additional information is provided.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23179">issues.joomla.org/tracker/joomla-cms/23179</a>.</sub>
