### ISSUE TITLE
System hangs when loggin in with an existing user (which not yet have seen the private policy accepting form

### ISSUE THREAD

**Issue by jojo12** [joomla/joomla-cms#23184]
### Steps to reproduce the issue
Joomla! 3.9.1 and latest Community Builder
Login as an existing user, accepting the privacy policy in the form, and trying to save (or to cancel). System hangs, I can only logout via backend and throwing out.
The error notification:
Warning
The email address you entered is already in use. Please enter another email address.

What can I do, I need CB and Joomla!

### Expected result
should redirect to an other page e.g. cb user profile. (like before)

### System information (as much as possible)
System hangs, I can only logout via backend and throwing out.
The error notification:
Warning
The email address you entered is already in use. Please enter another email address.

What can I do, I need CB and Joomla!

**Comment by mbabker** [comment]
Please test if you can reproduce this issue with core only.  If you can only reproduce it with Community Builder installed and enabled, you will need to file a bug report with them as it would appear that package is causing your issue.

**Comment by Quy** [comment]
This can be reopened if required.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23184">issues.joomla.org/tracker/joomla-cms/23184</a>.</sub>
