### ISSUE TITLE
Table templates_styles home wrong fieldtype

### ISSUE THREAD

**Issue by GarryMoveOut** [joomla/joomla-cms#23188]
### Steps to reproduce the issue
Install Joomla on apache with MySQL or PostgresSQL database.

### Expected result
Table template_styles with column home with type tinyint.

### Actual result
Table template_styles has a column home with type varchar(7)
```
-- Table: ****_template_styles

CREATE TABLE ****_template_styles
(
  id serial NOT NULL,
  template character varying(50) NOT NULL DEFAULT ''::character varying,
  client_id smallint NOT NULL DEFAULT 0,
  home character varying(7) NOT NULL DEFAULT '0'::character varying,
  title character varying(255) NOT NULL DEFAULT ''::character varying,
  params text NOT NULL,
  CONSTRAINT aa360_template_styles_pkey PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE *****_template_styles
  OWNER TO ****;
```
Some plug-ins won't work with varchar.

### System information (as much as possible)
CentOS 7, Apache + PHP5.6 + PostgresSQL 9.6

### Additional comments
Doc about table:
https://docs.joomla.org/Tables/template_styles

**Comment by infograf768** [comment]
Never understood indeed why we have char(7) instead of tinyint(1) as the value is 0 or 1

**Comment by alikon** [comment]
please test #24595

**Comment by ghost** [comment]
Closed as having Pull Request.
