### ISSUE TITLE
Can't create new field groups in Joomla 4.0 latest nightly

### ISSUE THREAD

**Issue by lllopo** [joomla/joomla-cms#23183]
### Steps to reproduce the issue
Go to 'Users > Field Groups', Click 'New'

### Expected result
Create new field group page opens

### Actual result
Class 'Joomla\Component\Fields\Administrator\Model\JTable' not found 

### System information (as much as possible)
Lates Joomla 4.0 nightly build, Apache 2.4 64bit, PHP 7.2 64bit, Windows 10 1809

**Comment by infograf768** [comment]
Confirmed. Preparing a patch.

**Comment by infograf768** [comment]
See PR https://github.com/joomla/joomla-cms/pull/23187
closing as we have a patch
