### ISSUE TITLE
ERROR: Invalid login - Joomla 3.9.1 Update

### ISSUE THREAD

**Issue by alebak** [joomla/joomla-cms#23201]
I'm trying to update to Joomla 3.9.1 and I get this javascript alert: 

ERROR: 
Invalid login

In the developer tools, the console doesn't display any error messages.

What could be happening?

It spend both in localhost and on the production server.

![step1](https://user-images.githubusercontent.com/6515879/49258110-518b5d80-f402-11e8-9c28-94899c6d230d.png)
![step2](https://user-images.githubusercontent.com/6515879/49258112-551ee480-f402-11e8-8dcc-92a76e57f097.png)
![step3](https://user-images.githubusercontent.com/6515879/49258119-5819d500-f402-11e8-9bef-572dbd4eb9bf.png)
![step4](https://user-images.githubusercontent.com/6515879/49258126-5d771f80-f402-11e8-8ba0-f551f08540f2.png)

**Comment by PhilETaylor** [comment]
The fact that it has got part of the way through the extraction process means that the blind login was working, and then not... 

You might be best upgrading this time manually to ensure that you are overwriting all Joomla core files with clean ones.

**Comment by tonypartridge** [comment]
Do you have a cookie plugin in place? I have seen this when the frontend clears the cookies for the site as part of a partially implemented cookies plugin.

**Comment by PhilETaylor** [comment]
This is nothing to do with cookies. 

The restore.php is looking for a hard coded password in restoration.php (which is an ini file) that is transient. The password is passed in the json each request and cookies are not used at all.

The most likey cause of this issue is that your webhosts virus scanner or other file monitoring software is deleting restoration.php during the process. 

https://github.com/joomla/joomla-cms/blob/51a6c75cfdb8b2b7d9a8d4162e2c2fd1553d3966/administrator/components/com_joomlaupdate/restore.php#L7991

https://github.com/joomla/joomla-cms/blob/51a6c75cfdb8b2b7d9a8d4162e2c2fd1553d3966/administrator/components/com_joomlaupdate/restore.php#L8074

**Comment by Quy** [comment]
Closing assuming it is not a Joomla core issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23201">issues.joomla.org/tracker/joomla-cms/23201</a>.</sub>

**Comment by mostafa-norouzi** [comment]
I had the same problem and the reason was because of **no space on host**. you can check it too.

**Comment by l-arnold** [comment]
Thank you @greenreptile .  That was my problem unbeknownst to me.  Fixed now and easy upgrade complete.

**Comment by rulatir** [comment]
The underlying problem that trips the installer may not be a Joomla core issue, but the ridiculously uninformative error message definitely is. Requesting reopening.

**Comment by jikometrix** [comment]
I had same issue trying update from 3.9.13 to 3.9.14 on Windows server 2016, PHP 7.3 and MySQL 5.7. Invalid login. I was using chrome on Mac Mahaje. I switched my browser to FireFox and was able update without error.  Maybe something is up with my chrome install.

**Comment by RobbenR** [comment]
> I had same issue trying update from 3.9.13 to 3.9.14 on Windows server 2016, PHP 7.3 and MySQL 5.7. Invalid login. I was using chrome on Mac Mahaje. I switched my browser to FireFox and was able update without error. Maybe something is up with my chrome install.

Thanks, this is still relevant, used chrome and received the error.. switched to Firefox and system is updating.. That little piece of information was very much appreciated.

**Comment by andreidumbrava** [comment]
If you run on linux and you serve files from a location under your container's user (apache/nginx), just change the file permission to 7xx (x may be 7,5,4 or 1).
It doesn't matter if you have restoration.php or not (I don't have it).

But annoying issue as it leaves no breadcrumbs.

**Comment by brianteeman** [comment]
No idea how or why but I just had this happen to me and I can confirm that as soon as I switched from chrome to firefox it worked perfectly

**Comment by PhilETaylor** [comment]
just a thought: Is your .htaccess optimised to add long expires headers to urls?? Im wondering if the url called that creates the restoration password file is not being "hit" because chrome has it "cached" do to expires headers... we have had this before (and I spent a month fixing) on editing articles.

**Comment by brianteeman** [comment]
No .htaccess

One thing I just tried was to use chrome in incognito mode ie no browser extensions. Guess what it worked perfectly

**Comment by PhilETaylor** [comment]
Which also uses a clean cache. I’m convinced this is Google loading a url redirect from cache and bypassing a url that creates the restoration file

I’ll add it on my todo list for 2023 to investigate that theory

**Comment by PhilETaylor** [comment]
2021 obviously. Fat fingers.

**Comment by Fredooweb** [comment]
Hi,

I had the same problem on my local server, just because I didn't change the log Directory : it stays on my production server directory. 
So, I've just change this directory and it works well.

Hope it helps :-)
