### ISSUE TITLE
[J3.9.1] Publish, unpublish, trash, archive, trash not working for tables having column as state instead of published

### ISSUE THREAD

**Issue by manojLondhe** [joomla/joomla-cms#23204]
### Steps to reproduce the issue

Publish, unpublish, trash, archive, trash not working for tables having `state` as column, and if no alias is set as below in respective table.php,

```
public function __construct(&$db) 
{
	parent::__construct('#__my_table', 'id', $db);

	// Set the alias since the column is called state
	$this->setColumnAlias('published', 'state');
}
```

This used to work till Joomla 3.9, [this PR](https://github.com/joomla/joomla-cms/pull/22851/files) seem to have caused this to break.

### Expected result

Publish, unpublish, trash, archive, trash should work as it was on 3.8.x

### Actual result

Publish, unpublish, trash, archive, trash not working as it was on 3.8.x

### System information (as much as possible)

PHP Version  7.2.12-1+ubuntu16.04.1+deb.sury.org+1
Joomla! Version | Joomla! 3.9.1 Stable

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/23200
Closing as known issue.

**Comment by manojLondhe** [comment]
Thanks @infograf768 
Sorry for duplicate!
