### ISSUE TITLE
Warning Update: :Extension: Could not open https://appscdn.joomla.org/webapps/jedapps/webinstaller.xml Error connecting to the server: Failed to connect to appscdn.joomla.org port 443: Connection refused Error Invalid URL Unable to find install package

### ISSUE THREAD

**Issue by dzacky** [joomla/joomla-cms#23218]
### Steps to reproduce the issue

Update: :Extension: Could not open https://appscdn.joomla.org/webapps/jedapps/webinstaller.xml
Error connecting to the server: Failed to connect to appscdn.joomla.org port 443: Connection refused

**Comment by dzacky** [comment]
this is a fresh install, had same problem with first install could not update any extensions modules<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23218">issues.joomla.org/tracker/joomla-cms/23218</a>.</sub>

**Comment by dzacky** [comment]
i manually went to the link in a brouser and saw the xml file went to the link in the file and downloaded the zip file and installed it via the uload and it worked but the problem is still i cant update any modules or extenshions i get the same erro for each.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23218">issues.joomla.org/tracker/joomla-cms/23218</a>.</sub>

**Comment by mbabker** [comment]
You will need to troubleshoot this issue with your hosting provider.  If your site cannot connect to any external sources that is a pretty good sign that either something in PHP is not configured right (i.e. the curl extension not installed and enabled) or there is a firewall in place preventing your site from communicating with these resources.

Closing as there is not a core bug in this issue.

**Comment by dzacky** [comment]
Still getting these messages when i try to update

Warning
Update: Could not open update site #4 "WebInstaller Update Site", URL: http://appscdn.joomla.org/webapps/jedapps/webinstaller.xml
Update: Could not open update site #6 "Akeeba FEF", URL: http://cdn.akeebabackup.com/updates/fef.xml
Update: Could not open update site #7 "Akeeba Backup Professional", URL: https://cdn.akeebabackup.com/updates/pkgakeebapro.xml
Update: Could not open update site #8 "WebInstaller Update Site", URL: https://appscdn.joomla.org/webapps/jedapps/webinstaller.xml
Update: Could not open update site #9 "FOF 3.x", URL: http://cdn.akeebabackup.com/updates/fof3.xml<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23218">issues.joomla.org/tracker/joomla-cms/23218</a>.</sub>
