### ISSUE TITLE
Joomla 4.0 update check fails

### ISSUE THREAD

**Issue by lllopo** [joomla/joomla-cms#23223]
### Steps to reproduce the issue
Go to the control panel home. Wait for Joomla to check for updates.

### Expected result
Update check to finish with result - either updates available or not.

### Actual result
Update check hangs on "Checking Joomla ..."

### System information (as much as possible)
Joomla 4.0 latest nightlie. PHP 7.2, Firefox 63.0.3, Windows 10 1809.

### Additional comments
Console message :
TypeError: r is undefined[Learn More] jupdatecheck.min.js:1:361
	onSuccess http://host/media/plg_quickicon_joomlaupdate/js/jupdatecheck.min.js:1:361
	e.request/o.onreadystatechange http://host/media/system/js/core.min.js:1:8265

**Comment by lllopo** [comment]
Same in Chrome. Error message :
Uncaught TypeError: Cannot read property 'version' of undefined
    at onSuccess (jupdatecheck.min.js?ccf033bf68a0a993bc16589a0df7cf8b:1)
    at XMLHttpRequest.o.onreadystatechange (core.min.js?ccf033bf68a0a993bc16589a0df7cf8b:1)

**Comment by infograf768** [comment]
please test 
https://github.com/joomla/joomla-cms/pull/23214

**Comment by infograf768** [comment]
it needs running npm ci

**Comment by richard67** [comment]
Should be solved with PR #23214 . Please close.

**Comment by wilsonge** [comment]
Thanks guys!
