### ISSUE TITLE
Add a Backup hint to the Update Message

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#23225]
### Steps to reproduce the issue
As soon as a new Version is available, the user gets message:
COM_INSTALLER_MSG_WARNINGS_UPDATE_NOTICE="Before updating ensure that the update is compatible with your Joomla! installation."

The Problem is: Many users do not know how to check the compatibility with extensions and perform the update. 

I suggest to expand this message:
"If you are not sure -  make a BACKUP of your installation BEFORE you start updating!".
(Native speaker required)

**Comment by brianteeman** [comment]
good idea

**Comment by chmst** [comment]
Would you make a PR? In correct British english?

**Comment by DavidBoggitt** [comment]
Not sure about PRs, but I'd suggest:

COM_INSTALLER_MSG_WARNINGS_UPDATE_NOTICE="Before updating, please ensure that the update is compatible with your Joomla! installation.  If you are not sure, you are STRONGLY advised to make a BACKUP of your installation before you start updating."

**Comment by mbabker** [comment]
Please don't randomly CAPS LOCK words in the MIDDLE of sentences.  If you really need emphasis on text, there are semantic HTML elements that should be used instead.

**Comment by Quy** [comment]
See PR #23229<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23225">issues.joomla.org/tracker/joomla-cms/23225</a>.</sub>
