### ISSUE TITLE
Joomla! update dont have results.

### ISSUE THREAD

**Issue by felemental** [joomla/joomla-cms#23226]
### Steps to reproduce the issue
After login to Joomla Desktop - > an update is available. **Update Now**

Actual version of Joomla | 3.6.5
Newest version of Joomla | 3.9.1

![image](https://user-images.githubusercontent.com/45593042/49436928-a3453680-f7ba-11e8-9634-b527c1fd3a55.png)

then click  **Install Update**

after installation, still i have **3.6.5**

![image](https://user-images.githubusercontent.com/45593042/49437013-dab3e300-f7ba-11e8-852c-3553bf09f25f.png)

After clicking **Check updates** i have the same things to do.

### Expected result

Install version 3.9.1 of Joomla!

### Actual result

Joomla! 3.6.5 installed

### System information (as much as possible)

PHP Interpreter  v 7
![image](https://user-images.githubusercontent.com/45593042/49437328-937a2200-f7bb-11e8-955e-43553b38f221.png)

**Comment by Quy** [comment]
Please post your issue to the `Migrating and Upgrading` in [Joomla Forums](https://forum.joomla.org/viewforum.php?f=710) for assistance and report back if bug is found.
