### ISSUE TITLE
[4.0] Joomla installation: language always switches to en-GB when getting to the remove view and thereafter

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#23222]
### Steps to reproduce the issue
Install a clean 4.0 branch or nightly
Select en-US as language at installation time. (I also tested with fa-IR after adding that lang to installation languages)
Pass steps one after the other. en-US is kept as language and direction until getting to the `index.php?view=remove&layout=default` page where you can choose to `Customise Installation` or `Complete and Open Site`, or `Complete & Open Admin`

### Expected result
The en-US is still the language set for the page and subsequent pages until opening site or admin.

### Actual result
It switches to en-GB and subsequent specific installation pages after clicking `Customise Installation` also.

Also, but this has already been stated quite some time ago, Languages still can't be installed if choosing such.

@dgrammatiko 

I guess this is due to the setup.js or remove.js files not keeping the chosen installation language.
Concerning installing languages, no idea at all.

**Comment by infograf768** [comment]
@Fedik 
Can you have a look?

**Comment by Fedik** [comment]
> Concerning installing languages, no idea at all.

me to :)
I will try to check, but not faster than next week

**Comment by Fedik** [comment]
> I guess this is due to the setup.js or remove.js files not keeping the chosen installation language.

These files doing nothing tricky, just "show"/"hide" specific HTML section, and sometimes send AJAX request.
The language handled by server side.

tbh, I have no idea, maybe something with session, but I cannot prove

> It switches to en-GB and subsequent specific installation pages after clicking Customise Installation also.

When you click `Customise` then remove.js  just display a hidden `<fieldset>` of languages, that already rendered on server. Maybe something with translation in View.

**Comment by dgrammatiko** [comment]
> maybe something with session

Exactly, it's the PHP side that looses the state, not the client side

**Comment by infograf768** [comment]
Closing in favour of https://github.com/joomla/joomla-cms/issues/25130 as it is more detailed.
