### ISSUE TITLE
Joomla 3.9.1 Banner Click URL not even showing on the page, so there is nothing to click on

### ISSUE THREAD

**Issue by luby1** [joomla/joomla-cms#23237]
### Steps to reproduce the issue
Create a simple custom banner with css and html. This is my example:
<style>
.div_text_shadow{
color: rgb(255, 255, 255);
font-size: 25px;
background-color: rgb(51, 51, 51);
text-shadow: rgb(255, 255, 255) 0px -1px 4px, rgb(255, 255, 0) 0px -2px 10px, rgb(255, 128, 0) 0px -10px 20px, rgb(255, 0, 0) 0px -18px 40px;
text-align:center;
}
</style>
<div class="div_text_shadow">Click Here for Christmas Giveaway</div>

Enter the click url (any proper url should work, i.e. https://kravfighter.co.nz/)
Create Banner Module and assign it to a banner module position.
Clear cache
Refresh the page
### Expected result
Banner is showing in the right position, and when you click on it, you're taken to a website specified in the click url.
### Actual result
There is no click url on the page, so clicking on the banner does nothing.
This is the excerpt from the code of the page:

<div class="bannergroup">
<div class="banneritem">
<style>
.div_text_shadow{
color: rgb(255, 255, 255);
font-size: 25px;
background-color: rgb(51, 51, 51);
text-shadow: rgb(255, 255, 255) 0px -1px 4px, rgb(255, 255, 0) 0px -2px 10px, rgb(255, 128, 0) 0px -10px 20px, rgb(255, 0, 0) 0px -18px 40px;
text-align:center;
}
</style>
<div class="div_text_shadow">Click Here for Christmas Giveaway</div>
<div class="clr"></div>
</div>
</div>

### System information (as much as possible)
Joomla 3.9.1 - tested on Protostar Template and on JF-Simone Gantry 5 template.  SEF urls enabled.

### Additional comments
Div tags were removed from all the above code examples and I don't know how to show them here.

**Comment by Quy** [comment]
From the [help documentation](https://help.joomla.org/proxy?keyref=Help39:Components_Banners_Banners_Edit&lang=en):

`Custom Code. Use {CLICKURL} and {NAME} to merge 'Click URL' and 'Name' values respectively into your custom code. For example: <a href="{CLICKURL}"><img src="enter url to image" alt="{NAME}" title="{NAME}"></a>.`

`Another option is to enter an HTML custom code. For example: <div class="yourclass"><a href="https://yourdomain.com"><img src="pathofyourimage"></a></div>`
