### ISSUE TITLE
Privacy consent dont translate language constant strings

### ISSUE THREAD

**Issue by ideaalab** [joomla/joomla-cms#23241]
### Steps to reproduce the issue
If you have a multilanguage site, on the Privacy consent plugin, if you use a language replacement string, it does not get translated.
For example use:
COM_USER_PRIVACY_CONSENT_SHORT_TOS: "Text in Spanish"
COM_USER_PRIVACY_CONSENT_SHORT_TOS: "Text in English"

### Expected result
On the registration form, the replacement string should show.

### Actual result
The constant string is shown instead.

### Additional comments
This can be solved changing file /plugins/system/privacyconsent/field/privacy.php line 41:

FROM THIS:
$privacynote = !empty($this->element['note']) ? $this->element['note'] : Text::_('PLG_SYSTEM_PRIVACYCONSENT_NOTE_FIELD_DEFAULT');

TO THIS:
$privacynote = !empty($this->element['note']) ? Text::_($this->element['note']) : Text::_('PLG_SYSTEM_PRIVACYCONSENT_NOTE_FIELD_DEFAULT');

I didnt check if the redirection text can use translation strings, but maybe it has the same problem.

**Comment by mbabker** [comment]
As explained in https://docs.joomla.org/J3.x:Privacy#Short_Privacy_Policy the text of that input area is not designed to be translated.  If you want to have a translated string you should create a language override for the `PLG_SYSTEM_PRIVACYCONSENT_NOTE_FIELD_DEFAULT` key.

Closing as this is the intended system behavior.

**Comment by ideaalab** [comment]
Ok, thanks for your attention.
In my opinion a regular user is not aware of this, and its not easy to find the correct translation string for this. Whenever a textfield is available, i think its easier to create your own string than finding which one is the one to override. Not to say that most possibly the user dont even think that his own string will not work. Thats what happened to me.
But its fine, im sure the team already thought about this, and the used method is the best...
Regards!
