### ISSUE TITLE
GDPR > Automatic Deletion of user actions

### ISSUE THREAD

**Issue by RalfRoemling** [joomla/joomla-cms#23245]
GDPR is claiming to tell people, when their save data is goin' to be deleted, e.g. in case of most hosters you can set a range of days after which log-files are deleted.

Would be great to have such an adjustible automatic cleanup in User Actions too.

**Comment by SharkyKZ** [comment]
See `Days to delete logs after` option in `System - User Actions Log` plugin.

**Comment by RalfRoemling** [comment]
Thx :-)

Havn't noticed that (obviously) and would have assumed to find it under `User > User Actions:Options`
