### ISSUE TITLE
com_fields parameter show_on not work

### ISSUE THREAD

**Issue by boomsya** [joomla/joomla-cms#23246]
joomla 3.9.1

create new field and set "Show on" only in administrator
Go to news category - field showed :(

Phrase "show_on" gives only XML + 1 PHP file. 
In `administrator/components/com_fields/helpers/fields.php` file we have function `displayFieldOnForm()`
but this function not called when page rendering
and parent function `onCustomFieldsPrepareDom()` in file `administrator/components/com_fields/libraries/fieldsplugin.php` not called too

//sorry. My English is not very good

**Comment by boomsya** [comment]
![fields](https://user-images.githubusercontent.com/8008462/49686657-6356ba00-fb00-11e8-8e1d-a6d6e8308a2e.jpg)

**Comment by boomsya** [comment]
**solution:**
add to function `public function onCustomFieldsPrepareField($context, $item, $field)` in file `administrator/components/com_fields/libraries/fieldsplugin.php` code:
```
// Detect if the field is configured to be displayed on the form
if (!FieldsHelper::displayFieldOnForm($field))
{
	return null;
}
```
after that all works fine

**Comment by ghost** [comment]
@HLeithner  can you please comment?

**Comment by HLeithner** [comment]
@boomsya could you create a PR?

**Comment by ghost** [comment]
@boomsya gently Reminder.

**Comment by boomsya** [comment]
no

**Comment by alikon** [comment]
please test  #24397
