### ISSUE TITLE
[4.0] TinyMCE 5.0

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#23251]
TinyMCE 5.0 is now in beta and is scheduled for release in Q1 2019 - well before any possible Joomla 4 release.

As this has lots of changes including how it is integrated it would make sense to switch to it now - otherwise people will be developing plugins and updating plugins for the wrong version and will have to do it all over again. 

There are significant accessibility improvements with v5

https://go.tiny.cloud/blog/tinymce-5-moves-from-preview-to-beta/

**Comment by brianteeman** [comment]
Release will be on Feb 4

**Comment by brianteeman** [comment]
And now released

**Comment by bembelimen** [comment]
I got my feet wet with the first tests ([https://github.com/bembelimen/joomla-cms/tree/tinymce-5.0](https://github.com/bembelimen/joomla-cms/tree/tinymce-5.0)) and it does not look that hard to run it in default mode.

Adding the parameter needs some clean up (some JS errors), but most stuff from 4.x works in the 5.x version.

**Comment by brianteeman** [comment]
Great that someone has started to work on this

**Comment by brianteeman** [comment]
Closed - see #24110
