### ISSUE TITLE
[4.0] out of date lock file

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#23257]
### Steps to reproduce the issue
on a clean system clone joomla 4 branch (Current at time of testing was https://github.com/joomla/joomla-cms/commit/a913426abef6a6791b6826da2ddc0c73d8ef89b6
perform "composer install" as per the docs

### Expected result
lock file in sync with composer.json - no warning messages

### Actual result
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

There were approx 47 updates

**Comment by brianteeman** [comment]
Unfortunately despite the console saying I should update the docs says dont

> It should be enough to run composer install as this will install PHP dependencies saved in the composer.lock file. You can do this as many times as you like, it will only install new packages when the composer.lock file is changed. Don't run composer update as this will update all packages to newer versions and update the composer.lock file.

**Comment by Quy** [comment]
Please test PR #23271<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23257">issues.joomla.org/tracker/joomla-cms/23257</a>.</sub>
