### ISSUE TITLE
[4.0] The requested page can't be found with Progressive Caching

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#23250]
### Steps to reproduce the issue
Activate Progessive Caching in Global Configuration
![global configuration test administration](https://user-images.githubusercontent.com/9974686/49695851-58a03180-fba1-11e8-9400-a56c2f7f3e31.png)

### Expected result
The frontend appears without failure
![home 3](https://user-images.githubusercontent.com/9974686/49695856-65bd2080-fba1-11e8-9635-8b6e1907e082.png)

### Actual result
I see a failure.
![error 0](https://user-images.githubusercontent.com/9974686/49695860-78375a00-fba1-11e8-9c63-a69f6f53d6ef.png)

### System information (as much as possible)
Current Joomla Repo on Ubuntu 18.04

**Comment by ghost** [comment]
@infograf768 can you please comment?

**Comment by ghost** [comment]
Issue confirmed.
### System information
Setting | Value
-- | --
PHP Built On | Linux lamp122.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.7.el6h.x86_64 nr.1 SMP Mon Dec 17 12:02:35 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.24-cll-lve
Database Collation | utf8_general_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.1.26
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Latest Nightly Build Update from Joomla! 4.0.0-alpha8-dev Development [ Amani ] 9-March-2019 13:41 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by SharkyKZ** [comment]
Test PR #26262 please.

**Comment by ghost** [comment]
Closed as having Pull Request #26262
