### ISSUE TITLE
[4.0] Enabling Debug System kills media manager

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#23255]
### Steps to reproduce the issue
As title says.
URL is
`/administrator/index.php?option=com_media&path=local-0:/`

### Expected result
Same as when debug is disabled:

<img width="933" alt="screen shot 2018-12-10 at 09 28 58" src="https://user-images.githubusercontent.com/869724/49719653-138e0500-fc5e-11e8-9d1d-0009f3a852b6.png">

### Actual result
<img width="861" alt="screen shot 2018-12-10 at 09 29 49" src="https://user-images.githubusercontent.com/869724/49719692-2d2f4c80-fc5e-11e8-8861-9a8d2a8d7697.png">

### Additional comments
Some errors in Console:
`SyntaxError: import declarations may only appear at top level of a module mediamanager.js:1 `
on Firefox.
or similar
`SyntaxError: Unexpected identifier 'Vue'. import call expects exactly one argument.`
on Safari.
```
Source map error: request failed with status 404
Resource URL: http://localhost:8888/installmulti/joomla40/media/vendor/metismenujs/js/metismenujs.js?c71e83b4299e53b9e9f2cbc41461860a
Source Map URL: metismenujs.js.map[Learn More]
Source map error: request failed with status 404
Resource URL: http://localhost:8888/installmulti/joomla40/media/vendor/css-vars-ponyfill/js/css-vars-ponyfill.js?1.15.1
Source Map URL: css-vars-ponyfill.js.map[Learn More]
Source map error: request failed with status 404
Resource URL: http://localhost:8888/installmulti/joomla40/media/vendor/bootstrap/js/bootstrap.bundle.js?4.1.3
Source Map URL: bootstrap.bundle.js.map[Learn More]
```

These .map files are present on my test site.

**Comment by Quy** [comment]
I am not able to reproduce with the nightly build of `Tuesday, 11 December 2018 03:00:37 UTC`.

**Comment by infograf768** [comment]
OK. I found the issue. We may still have a bug. I explain.

I had a `mediamanager.js` file in `.../media/com_media/js/mediamanager.js` dated october 2018.
After using npm ci on that existing site, that file was kept there. 
That file was an exact copy of `/administrator/components/com_media/resources/scripts/mediamanager.js`

In a new clean install, this file IS NOT created in the media folder and all works well because, when debug is on, only the `mediamanager.min.js` is created and used as we have no `mediamanager.js` to use.

Should that file be created as other js are is the question.
Before closing, need explanations.

@dgrammatiko ?

**Comment by dgrammatiko** [comment]
The debugging for a vue application, media manager, is way deferent than the plain old imperative scripts. There shouldn’t be an unminified file imho

**Comment by laoneo** [comment]
@dgrammatiko is right, we don't have a none minified file, because it is a vue application which compiles the JS file out of the .vue files.

**Comment by dgrammatiko** [comment]
FYI Joomla should drop the non minified files as also the rest of the files (I mean the es6 DOM related scripts) need some sort of transpiling. Also for anyone that wants to contribute there is a watch option in the npm command that recompiles on every file change. The uncompressed files are useless...

**Comment by mbabker** [comment]
> The uncompressed files are useless...

When working against the core repository, sure.  Remember, debug mode is available on production sites and away from the Git repository and having non minified files can help in tracing/debugging an issue in a website (which may lead back to a core issue).  So the use and support for non minified files needs to keep being a consideration (especially as given the current structure the source ES6 files are not shipped with production builds).

**Comment by infograf768** [comment]
Closing but not convinced as, indeed, no way for testers to debug. Looks like it will be more and more a matter of specialists.
