### ISSUE TITLE
.modal class conflict in terms.php with Bootstrap

### ISSUE THREAD

**Issue by sachieldvangel** [joomla/joomla-cms#23267]
> If you are submitting an issue for the Joomla! CMS, please submit it at https://github.com/joomla/joomla-cms/issues/new instead.  You may remove this line from the issue template.

#### Steps to reproduce the issue

Use any template or otherwise incorporate Bootstrap into Joomla.
Enable the User - Terms and Conditions plugin.
Link an article to the Terms and Conditions plugin.
Attempt to register a new User via the frontend.
"Terms and Conditions" link will not be visible, only the "*" for required fields.

, and when a new user is registering, the link for the Terms & Conditions will not be visible because of the "display:none" and other issues with the .modal class.

#### Expected result

This line in the source uses a "modal" class on the link.

`<a href="/index.php/component/content/article/12-club-docs/2-constitution-and-bylaws?tmpl=component&amp;Itemid=101" class="modal" rel="{handler: 'iframe', size: {x:800, y:500}}">Terms &amp; Conditions</a>`

Bootstrap contains its own definition for .modal:
`.modal {
 position:fixed;
 top:0;
 right:0;
 bottom:0;
 left:0;
 z-index:1050;
 display:none;
 overflow:hidden;
 outline:0
}`

#### Actual result

The line only renders a "*" with no link to the complete terms and conditions.

#### System information (as much as possible)
Joomla 3.9.1
Helix Ultimate Template v 1.0.5
Bootstrap v4.1.3

#### Additional comments

Source of class definition is in /plugins/user/terms/field/terms.php:
line 106:
`$attribs['class'] = 'modal';`

**Comment by ghost** [comment]
can you please update on latest Version and use Default-Settings like Protostar?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23267">issues.joomla.org/tracker/joomla-cms/23267</a>.</sub>

**Comment by ghost** [comment]
Closed as no Answer; please reopen if needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23267">issues.joomla.org/tracker/joomla-cms/23267</a>.</sub>
