### ISSUE TITLE
PHP 7.3, PHP Warning from restore.php

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#23266]
### Steps to reproduce the issue

Run Joomla Update using com_joomlaupdate

### Expected result

No PHP Warnings

### Actual result

> [Tue Dec 11 14:41:24 2018] PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /Users/phil/Downloads/restore/administrator/components/com_joomlaupdate/restore.php on line 1225

<img width="1059" alt="screenshot 2018-12-11 at 15 02 45" src="https://user-images.githubusercontent.com/400092/49809038-d4db7600-fd55-11e8-8017-d8d83920562d.png">

https://github.com/joomla/joomla-cms/blob/51a6c75cfdb8b2b7d9a8d4162e2c2fd1553d3966/administrator/components/com_joomlaupdate/restore.php#L1225

### System information (as much as possible)

```
PHP 7.3.0 (cli) (built: Dec  7 2018 11:00:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by conseilgouz** [comment]
Hi,

This is a new PHP 7.3 warning: see https://secure.php.net/manual/en/migration73.incompatible.php

Pascal

**Comment by PhilETaylor** [comment]
Yes I know. But it still needs fixing.

**Comment by alikon** [comment]
i'm afraid there will be a lot more :smiley:
