### ISSUE TITLE
Banners -> Clients Published\UnPublished don`t work

### ISSUE THREAD

**Issue by alexgru** [joomla/joomla-cms#23269]
### Steps to reproduce the issue
Go to admin area -> Components -> Banners -> Clients
administrator/index.php?option=com_banners&view=clients
Add new Client and try Published\Unpublished him.
This problem have any components why in file administrator\components\com_mycomponent\tables\mytable.php
have **function publish** .

### Expected result
Published\Unpublished

### Actual result
None
Don`t change status

### System information (as much as possible)
Joomla 3.9.1

### Additional comments
Problem in libraries\src\MVC\Model\AdminModel.php
Line 1066 - 1071
```php
if ($table->get($table->getColumnAlias('published'), $value) == $value)
				{
					unset($pks[$i]);
 
					continue;
				}
```

**Comment by Quy** [comment]
Fixed in upcoming v3.9.2. See PR #23193.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23269">issues.joomla.org/tracker/joomla-cms/23269</a>.</sub>
