### ISSUE TITLE
[4.0] Saving in modal window don't work

### ISSUE THREAD

**Issue by wojsmol** [joomla/joomla-cms#23260]
### Steps to reproduce the issue
- Install current 4.0-dev with testing sample data.
- Go to any menuitem of type Category List, Single, Contact, Single Article, Single News Feed
- Edit item in modal window
- Try save using Save or Save & Close buttons

### Expected result
Item saved
### Actual result
```
TypeError: iframeDocument is null[More informations] modal-fields.js:154:4
window.processModalEdit http://localhost/j4010122018/media/system/js/fields/modal-fields.js:154:4
onclick http://localhost/j4010122018/administrator/index.php:1:1
```
Above error message is recorded with System Debug set to Yes, but the issue exist also when System Debug is set to No.

### System information (as much as possible)

Setting | Value
-- | --
PHP Built On | Windows NT WIN8 6.3 build 9600 (Windows 8.1 Home Premium Edition) i586
Database Type | mysql
Database Version | 5.5.28
Database Collation | utf8mb4_unicode_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.1.11
Web Server | Apache/2.4.16 (Win32) mod_fcgid/2.3.9
WebServer to PHP Interface  | cgi-fcgi
Joomla! Version  | Joomla! 4.0.0-alpha6-dev Development [ Amani ] 4-November-2018 23:23 GMT
User Agent | Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0

### Additional comments
cc @dgrammatiko

**Comment by infograf768** [comment]
Confirmed.

**Comment by infograf768** [comment]
@dgrammatiko

**Comment by fvdn** [comment]
Confirmed

**Comment by dgrammatiko** [comment]
Test: https://github.com/joomla/joomla-cms/pull/20788

**Comment by gnanakeethan** [comment]
@dgrammatiko 

Is there a need to apply the PR and test?

**Comment by gnanakeethan** [comment]
@infograf768 @dgrammatiko 

I ran through this. Now I see an almost empty Modal box on a clean state install.  **TABBED SECTION MISSING** . 

```Uncaught TypeError: Cannot read property 'nodeName' of null``` in joomla-tab.js

**Comment by Quy** [comment]
Please tees PR #24350<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23260">issues.joomla.org/tracker/joomla-cms/23260</a>.</sub>
