### ISSUE TITLE
Workflow - Manager/Publisher ACL unable to change status of custom workflow

### ISSUE THREAD

**Issue by dmurphy779** [joomla/joomla-cms#23262]
### Steps to reproduce the issue
1) Create category "Academics"
2) Create custom workflow "Dan's Workflow"
3) Assign Dan's Workflow to Academics
4) Create stages in Dan's Workflow
5) Create transitions in Dan's Workflow
6) Create user "testuser1" with manager or publisher permissions
7) Sign out / sign in in an testuser1 (as manager acl) and access administrator backend
7) Create new article & assign category to Academics
8) Add new article to main menu (not necessary but just in case)
7) Ensure manager and publishers both have ability to change status in article
8) As testuser1, edit the new article and try to change status from "New" to "Dept. Review"

### Expected result

A dropdown should appear showing "Dept. Review" as a status change option. 

### Actual result

Only the "New" status is shown (unable to select the Dept. Review status

### System information (as much as possible)
Joomla! 4.0.0-alpha6-dev

locally hosted on xampp (Windows 10) apache 7.1, MySqli

### Additional comments

As superuser, I am able to change the status of the custom workflow but not for users with Manager or Publisher ACL permissions.

Also, it does not appear that there is functionality in place to set ACL privileges to change a specific status. For example if I created a user group as "Dept Minion" under the Editor ACL, they should only be able to change the status to "Ready for Dept. Review". While a user in usergroup "Dept. Supervisor" under the Editor ACL should only be able to change status to "Ready for Web Admin Review". Additionally, an optional user selection field should be defined for each transition so that the proper individuals are notified by email when a status change takes place. Just a thought. Workflows is a great addition to Joomla! Keep it up. 
![screen shot 2018-12-11 at 07 02 11](https://issues.joomla.org/uploads/1/7aebfce431a35600bfca31baf70e08c6.png)![screen shot 2018-12-11 at 07 02 13](https://issues.joomla.org/uploads/1/b2b73d24cbe417cecde81ef03ee7ff77.png)

**Comment by Quy** [comment]
@bembelimen

**Comment by bembelimen** [comment]
Did you set the execute permissions in the transition edit view?

**Comment by dmurphy779** [comment]
Yes - I confirmed that the correct user groups were assigned in each of the transitions and showing they are allowed to edit state. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23262">issues.joomla.org/tracker/joomla-cms/23262</a>.</sub>

**Comment by bembelimen** [comment]
> Did you set the **execute permissions** in the transition edit view?

Not the "edit state" permission

**Comment by ghost** [comment]
any Comment @dmurphy779 or should this be closed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23262">issues.joomla.org/tracker/joomla-cms/23262</a>.</sub>

**Comment by dmurphy779** [comment]
I'm sorry but I don't have time to test further right now. Feel free to close this if you are unable to duplicate the issue on your end. I love what you folks are doing with the workflow component. I just hope it's intuitive / flexible enough to use. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23262">issues.joomla.org/tracker/joomla-cms/23262</a>.</sub>

**Comment by ghost** [comment]
closed as stated above, Issue can always reopened if needed. Thanks for your Time @dmurphy779.
