### ISSUE TITLE
[4.0] Replace Uglify-es with Terser

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23265]
The [Uglify-ES](https://www.npmjs.com/package/uglify-es) package is no longer maintained.

You should update to [Terser](https://github.com/terser-js/terser) which is a fork that retains API and CLI compatibility.

**Comment by dgrammatiko** [comment]
FWIW uglify-es is **only** used for ES5 since the last or for the build tools. The reason is that either uglify-we or any other minifying script is useless now that we use the Babel minifier, which btw is the only one that can be trusted, check the react repo for the bugs from uglify-es

**Comment by C-Lodder** [comment]
But with Fedik's PR, ES6 files will be shipped and thus need to be minified. Uglify doesnt support ES6

**Comment by dgrammatiko** [comment]
That approach is also wrong. In order to ship esXXXX code you need to use module/nomodule in the script tags. That's what everybody else is doing. The approach to keep thinking on es5 terms for ESXXX is plain wrong...

**Comment by dgrammatiko** [comment]
> Uglify doesnt support ES6 

For Esxxxx you can use babel without transpiling, just minifying. Check the code in the build tools this is already supported:

```js
const settings = [
    {
        presets: [
            ['@babel/preset-env', {
                targets: {
                    browsers: ["ie 11"]
                },
                modules: false
            }],
        ],
        plugins: [
            ['add-header-comment', { header: [headerText] }],
            ['@babel/plugin-transform-classes']
        ],
        comments: true
    },
    {
    presets: [
        ['@babel/preset-env', {
            targets: {
                browsers: ["ie 11"]
            },
            modules: false
        }],
        "minify"
    ],
    plugins: [
        ['@babel/plugin-transform-classes']
    ],
    comments: false
}
];
```

Those settings are used to transpile to es5, but you can have a copy of them with `browsers: ["last 2 versions"]` and voila ES6 minified (and also transpiled any newer feature to the minimum browser that Joomla wants to support)...

**Comment by C-Lodder** [comment]
Yes browser detection is wrong. Should be feature detection, but then all assets will need to be lazy loaded.

**Comment by dgrammatiko** [comment]
Actually Joomla can use feature detection without lazy loading the scripts:
<img width="735" alt="screenshot 2018-12-16 at 11 21 51" src="https://user-images.githubusercontent.com/3889375/50052477-ec837780-0124-11e9-9785-c6f915fc4214.png">

https://philipwalton.com/articles/deploying-es2015-code-in-production-today/

As always there are some caveats: scripts need to be ALWAYS deferred (otherwise the order of execution might be messed up), but this is the recommended best practice so at some point ppl should accept it and move forward...
