### ISSUE TITLE
Joomla 3.91 update

### ISSUE THREAD

**Issue by A8014766** [joomla/joomla-cms#23263]
After doing a 3.91 update I get error 500 when trying to write or edit any of my articles
It says  an error has occured 500 Unknown column 'a.note' in 'field list'. I have gone to my last back up and all is well?
Can you tell me what I have done wrong?

**Comment by SharkyKZ** [comment]
Try Extensions -> Database -> Fix.

**Comment by A8014766** [comment]
Wow many thanks that sorted my problem just like that, a million thanks!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23263">issues.joomla.org/tracker/joomla-cms/23263</a>.</sub>

**Comment by infograf768** [comment]
closing

**Comment by scaserta11** [comment]
Worked perfectly. Thank you.
