### ISSUE TITLE
[4.0]Create menu item error

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#23276]
### Steps to reproduce the issue
1. Install Joomla 4 nightly build
2. Try to create a menu item

### Expected result
Menu item created

### Actual result
An error has occurred.
0 Too few arguments to function PlgContentJoomla::onContentBeforeSave(), 3 passed in D:\www\joomla4\libraries\src\Plugin\CMSPlugin.php on line 287 and exactly 4 expected

### System information (as much as possible)
Joomla 4 nightly build

### Additional comments
This can be easily fixed by modifying code on this line https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/models/item.php#L1430 and add $data variable to the event trigger. However, there would be many other places which we need to check and also, it would cause same errors with third party extension. So maybe we can make $data parameter optional in this method onContentBeforeSave https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/content/joomla/joomla.php#L55

**Comment by infograf768** [comment]
I confirm the issue, not only create but also saving an existing menu item.

**Comment by infograf768** [comment]
I like better your second solution, something like
`public function onContentBeforeSave($context, $table, $isNew, $data = '')`

**Comment by ElephantInTheRoomFirst** [comment]
I have encountered issue on 21st Dec nightly build. As of now, I am using the workaround suggested above  public function onContentBeforeSave($context, $table, $isNew, $data = '').

**Comment by ReLater** [comment]
Please test pr https://github.com/joomla/joomla-cms/pull/23395

**Comment by joomdonation** [comment]
The bug was fixed on https://github.com/joomla/joomla-cms/pull/23355 (and the decision was keep $data as required parameter in the method). So your PR should be closed, too

**Comment by ReLater** [comment]
@joomdonation 
I use a J!4 where 23355 is already merged. So, I see no reason to close my PR at the moment.

**Comment by joomdonation** [comment]
OK. Just for information, you can see @wilsonge comment about it at https://github.com/joomla/joomla-cms/pull/23293#issuecomment-450033939 ($data is required, not optional as proposed in your PR)
