### ISSUE TITLE
[4.0] Translation missing

### ISSUE THREAD

**Issue by gwsdesk** [joomla/joomla-cms#23272]
under Articles-->Workflow-->Edit Workflow Title missing

WORKFLOW_DEFAULT_WORKFLOW instead of 'Title'

**Comment by infograf768** [comment]
in fact the string constant is
`COM_WORKFLOW_DEFAULT_WORKFLOW `
and it is present afaik
```
COM_WORKFLOW_DEFAULT_WORKFLOW="Joomla! Default"
```
therefore it look like it is not translated in `administrator/index.php?option=com_workflow&extension=com_content`

**Comment by infograf768** [comment]
OK, found where the error is. Making patch

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/23275
closing as we have a patch
