### ISSUE TITLE
sql query using group by requires me to add all the fields in my select as fields in the groupby clause

### ISSUE THREAD

**Issue by rgjoyce** [joomla/joomla-cms#23282]
### Steps to reproduce the issue
I am updating my J3 component to J4 and have come across a major problem
and example of my query.
$query->select($db->quoteName(array('r.rid' ,  'e.id', 'r.firstname', 'r.lastname', 'r.email', 'e.titel', 'l.club', 'l.url', 'l.city',
				 'l.plz', 'l.street', 'l.country', 'l.locdescription','e.status', 'e.email_reminder', 'e.dates', 'e.times',
				 'e.enddates', 'e.endtimes', 'e.shortdescription', 'e.datdescription'),array('uid','eid',null,null,
				null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null)))
	->from($db->quoteName('#__registrationmanagerking_events','e'))
	->from($db->quoteName('#__registrationmanagerking_locate','l'))
	->from($db->quoteName('#__registrationmanagerking_register','r'))

	->where($db->quoteName('r.notified') . ' =0 ','and')
	->where($db->quoteName('r.status') . ' =1 ','and')
	->where($db->quoteName('e.id') . ' = '.$db->quoteName('r.rdid'),'and')
	->where($db->quoteName('l.id') . ' = '.$db->quoteName('e.locid'),'and')
	->where($db->quoteName('e.published') . ' =1 ','and')
	->where($db->quote($current_date) .'>= DATE_SUB(e.dates ,INTERVAL e.notifydate DAY)','and')
	->where($db->quoteName('e.notifydate') . ' !=0 ','and')
	->where($db->quoteName('e.status') . ' !=2 ')
        ->group($db->quoteName('r.rid'));

I ONLY want to group by r.rid and nothing else.
Joomla! 4 requires me to add ALL the fields in my field select list, in the group clause.
I can see this in the core components, but I think this is VERY wrong.
Not only is it wrong, but it will stop almost EVERY Joomla! commercial and free component from working.
It seems very Unnecessary to have made this change.

**Comment by alikon** [comment]
that's SQL and it is not wrong

**Comment by ReLater** [comment]
@rgjoyce See https://github.com/joomla/joomla-cms/issues/19808 please and the linked discussions/prs.

**Comment by rgjoyce** [comment]
yeah but why FORCE strict mode?
It is only my opinion but I think this is s horrible decision.
you are forcing more and more core changes to extensions and pushing away more and more developers.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23282">issues.joomla.org/tracker/joomla-cms/23282</a>.</sub>

**Comment by mbabker** [comment]
The forced strict mode was already removed due to backlash.

**Comment by roland-d** [comment]
What a pity.

**Comment by joeforjoomla** [comment]
@rgjoyce honestly i don't know why you stumbled into this issue. The decision has already been to remove the strict mode for group by so it can't depend on Joomla 4 because it doesn't force MySQL only full group by. Maybe you are using an old nightly build.
Joomla 4 currently uses the following SQL modes:

'STRICT_TRANS_TABLES',
'ERROR_FOR_DIVISION_BY_ZERO',
'NO_AUTO_CREATE_USER',
'NO_ENGINE_SUBSTITUTION'

**Comment by mbabker** [comment]
Closing issue.  Already addressed.

**Comment by rgjoyce** [comment]
I use the version downloadable from the Joomla.org site yesterday
