### ISSUE TITLE
Erroneous spanish ldap plugin help translation

### ISSUE THREAD

**Issue by mperaya** [joomla/joomla-cms#23286]
In the popup param label help for "Search String" and "User's DN" of the ldap plugin on latest joomla, the english version says that:
"several strings can be used separated by semicolons."

The official spanish language pack has translated this as:
"Se pueden usar varias cadenas separadas por una coma"

but "coma" is the spanish translation of "comma". The english term "semicolon" is "punto y coma" in spanish.

This error makes the plugin unusable if you define more than one string on any of this two fields.

**Comment by infograf768** [comment]
We will inform the Spanish Translation Team of this error.
Closing as this not Joomla core.

**Comment by infograf768** [comment]
@Valc

**Comment by Valc** [comment]
Thanks for reporting. In the next release will be solved.
