### ISSUE TITLE
New feature request: Module Articles Newsflash Make Show Intro Text Clickable Option

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#23283]
Module Articles Newsflash

Make Show Intro Text Clickable Option

**Comment by SharkyKZ** [comment]
Make a template override.

**Comment by ghost** [comment]
What code you suggest to put in a default joomla protostar template override to get this New feature for Module Articles Newsflash ?

**Comment by Quy** [comment]
@Milglius Please ask help in [Joomla Forums](https://forum.joomla.org/).

**Comment by ghost** [comment]
This is New feature request: Module Articles Newsflash Make Show Intro Text Clicable Option

If you have code to enable this new feature please provide your suggested code here it must work with default joomla protostar template

**Comment by ghost** [comment]
It seems joomla protostar template override doesn't work to enable this feature.

**Comment by ghost** [comment]
I cant find answer nor in forums nor in git Maybe someone with better knowledge of code knows how to 

make this article title go on article picture and be clicable? 

I know how to make override but dont know what code to write in joomla overrride to make this feature

Hope you understand what feature I want to make

**Comment by ghost** [comment]
is ther anyone or should this Issue be closed as its for Forum?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23283">issues.joomla.org/tracker/joomla-cms/23283</a>.</sub>

**Comment by ghost** [comment]
A Solution is stated above, so closing this Issue. Maybe a Dev find time for doing against J4.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23283">issues.joomla.org/tracker/joomla-cms/23283</a>.</sub>

**Comment by ghost** [comment]
franz-wohlkoenig please provide the actual working code if you claim A Solution is stated above.

Forum is dead zero Solution there 

Request to reopen this New feature request untill the actual working code would be provided

**Comment by Milglius** [comment]
Yes I prefer Wordpress, joomla was ok decade ago, now joomla is outdted and buggy cms and its getting even worse

current joomla devs as @brianteeman @franz-wohlkoenig and @Bakual show no respect for joomla user

there is no bug there is no documentation and joomla issue is closed

In that case I prefer Wordpress

can you recommend me tool to migrate from buggy outdated joomla 3,9,5 to modern Wordpress 5,1,1?

**Comment by Bakual** [comment]
Deleted last comment as it was not related to this issue.
