### ISSUE TITLE
PHP scripts throw error 500 after updating to 3.9.1

### ISSUE THREAD

**Issue by PercyP** [joomla/joomla-cms#23291]
### Steps to reproduce the issue
Hi,

I have updated from Joomla 3.8.5 to 3.9.1 and my cron jobs no longer work. I am using SPPagebuilder 3.8 (latest release just in case this matters). 

My cron jobs throw an error 500 when I try to run script in url - this used to work perfectly. I have tried changing permissions on the files to 755 and eve 777 but still produces the error. I could revert bact to joomla 3.8.5 but really hope I don't have to do this. 

Are there changes to something in new releases of Joomla that would cause this, if yes how can I fix it?

### Expected result
Script runs

### Actual result
Error 500

**Comment by Quy** [comment]
Please ask help in [Joomla Forum](https://forum.joomla.org/viewforum.php?f=710).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23291">issues.joomla.org/tracker/joomla-cms/23291</a>.</sub>
