### ISSUE TITLE
[3.9.1] Removing User Note

### ISSUE THREAD

**Issue by Tom582** [joomla/joomla-cms#23295]
Dear All,

the following issue may be related to #23191. 

I am running a website upgraded from Joomla 1.5 to Joomla 3.9.1 in several steps over the past years. After removing a registered user I noticed that a user note associated with that user was still available under Users -> User Notes. So, I tried to trash it by means of its attached Status menu from the "User Notes" view. It did not work. In the next step, I marked the corresponding user note with a checkmark and clicked on the Trash button in the top bar of the "User Notes" view in order to remove it. This did not work either. I repeated the same exercise trying to archive or even unpublish that user note. Without any success.

I only succeeded, when I opened the obsolete user note and trashed it from "inside" per Status -> Trashed.

### Steps to reproduce the issue

- Create a user note
- Navigate to "Users -> User Notes"
- Try to unpublish, archive or trash the new note

### Expected result

The new user note is
- unpublished
- archived
- trashed

### Actual result

Unpublishing, archiving and trashing has no effect at all.
0 user note was unpublished/archived/trashed.

### System information (as much as possible)

Joomla 3.9.1
PHP 7.2.12

### Additional comments

I only succeeded, when I opened the obsolete user note and trashed it from "inside" per Status -> Trashed.

Regards
Tom

**Comment by SharkyKZ** [comment]
The PR you mention (#23191) fixes this issue. The fix will be included in the next release.

**Comment by Quy** [comment]
Fixed in upcoming v3.9.2. See PR #23191<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23295">issues.joomla.org/tracker/joomla-cms/23295</a>.</sub>

**Comment by Tom582** [comment]
Great. I was already a little bit afraid that this issue may have been caused by the evolution of my website.

Thanks
Tom
