### ISSUE TITLE
Repeatable custom field loose content after batch processing

### ISSUE THREAD

**Issue by BPBlueprint** [joomla/joomla-cms#23307]
### Steps to reproduce the issue
Create a custom field type "Repeatable"
Create different categories
Create an article and enter some content into repeatable custom fields > save article
Use bash-processing and move article to antoher category

### Expected result
content of repeatable custom field is still visible

### Actual result
there is no more content in repeatable custom field

### System information (as much as possible)
Joomla 3.9.1
PHP 7.2

### Additional comments
a) Other custom fields do not lose there content. Only for type repeatable
b) putting article to another category by opening article > chose category works! But problems by batch-processing

**Comment by tonypartridge** [comment]
Thanks for the report! PR now in please test :-)

**Comment by Quy** [comment]
Please test PR #23310.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23307">issues.joomla.org/tracker/joomla-cms/23307</a>.</sub>
