### ISSUE TITLE
[4.0] Language debug mode not showing line numbers.

### ISSUE THREAD

**Issue by rgjoyce** [joomla/joomla-cms#23305]
### Steps to reproduce the issue
turn on debug mode for language.

### Expected result
For the system to list the language file and the line number where the problem is.

### Actual result

listing the file with absolute path.
/administrator/components/com_registrationmanagerking/language/en-GB/en-GB.com_registrationmanagerking.ini
13 times for 13 errors.

### System information (as much as possible)
Joomla 4 nightly build 6

I would have expected the line numbers to have been provided too. To find the problem lines, I had to load the language file in a Joomla 3.9.1 site.

**Comment by infograf768** [comment]
Issue confirmed.

**Comment by infograf768** [comment]
@elkuku 
Not only we do not have any more the lines in error, but the Tabs are not translated.

**Comment by elkuku** [comment]
Confirmed.
This is only true for plain text. You can set the `xdebug.file_link_format` in your `php.ini` to open the file in your favorite text editor / IDE :wink:

**Comment by rgjoyce** [comment]
This may very well be. But most users of Joomla aren’t developers and won’t know that.

It is more user friendly if the info is presented in a user friendly presentable fashion so that there is no confusion and no additional user work other than opening the specified file and investigating the reported line.

**Comment by elkuku** [comment]
Totally agree with you :wink: 
So there's #23308 which should fix this issue.
Not sure if you can test it, otherwise you have to wait until it gets merged and included in the next nightly.

**Comment by Quy** [comment]
Please test PR #23308.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23305">issues.joomla.org/tracker/joomla-cms/23305</a>.</sub>

**Comment by infograf768** [comment]
@elkuku 
will test tomorrow. what about the tabs? (Queries, Untranslated, Errors)

**Comment by elkuku** [comment]
> what about the tabs?

There has never been an effort, nor a request, to translate anything in the new debug thing (apart from the config settings).

**Comment by infograf768** [comment]
> There has never been an effort, nor a request, to translate anything in the new debug thing (apart from the config settings).

I understand there were no efforts. Time to implement it I guess...
We have in 3.x
<img width="341" alt="screen shot 2018-12-21 at 07 19 12" src="https://user-images.githubusercontent.com/869724/50327798-c8db7b00-04f0-11e9-85d3-4f4c48211609.png">

In J4, the Tabs names are defined in the DataCollector/various files in the `getWidgets()` methods

Therefore I guess that we could for example use in `/plugins/system/debug/DataCollector/LanguageStringsCollector.php`:

```
[...]
use Joomla\CMS\Language\Text;
[...]
	public function getWidgets(): array
	{
		return [
			Text::_('PLG_DEBUG_UNTRANSLATED_STRINGS')       => [
				'icon'    => 'question-circle',
				'widget'  => 'PhpDebugBar.Widgets.languageStringsWidget',
				'map'     => $this->name . '.data',
				'default' => ''
			],
			Text::_('PLG_DEBUG_UNTRANSLATED_STRINGS') . ':badge' => [
				'map'     => $this->name . '.count',
				'default' => 'null'
			]
		];
	}
```
As the string already exists, this would give for French:

<img width="903" alt="screen shot 2018-12-21 at 08 31 46" src="https://user-images.githubusercontent.com/869724/50330303-fd543480-04fa-11e9-9b82-9bda99510470.png">

What do you think?

**Comment by infograf768** [comment]
Closing this as we have #23308 

Translations would be for another PR.

**Comment by infograf768** [comment]
Note: some translations have to be done in the widjet.js files.
