### ISSUE TITLE
[4.0] Tags - Batch Edit TAGS add PARENT Tag

### ISSUE THREAD

**Issue by rytechsites** [joomla/joomla-cms#23304]
### Describe the solution you'd like
On the Manage TAGS page
Select some tags, then click BATCH Button
From here you should be able to 'via batch' CHANGE the PARENT to something else

this is for Tag 'Organization'

Also it would be helpful, if there was a way to add MULTIPLE TAGS at one time, 'add in batch', so if you want to add 100 tags, you can just give a list, with commas, and it will add them all as individual tags.

**Comment by Quy** [comment]
Related #23185

**Comment by rytechsites** [comment]
I'm not sure if it really is realated.  The related id: #23185 is about the ARTICLES.  Where this request is in the TAG management, and on the TAG screen what you are able to do in 'BATCH MODE'.

Does that make sense?

thanks,
LAura

**Comment by Quy** [comment]
Yes, I understand now. Thanks.

**Comment by brianteeman** [comment]
Please remove the j3 label

**Comment by brianteeman** [comment]
#38583 allows you to batch copy and batch move tags

**Comment by richard67** [comment]
@brianteeman Does your PR solve this issue?

**Comment by brianteeman** [comment]
I am tempted to say that the last part of this feature request is resolved as you can use the api to bulk create tags

**Comment by brianteeman** [comment]
Going to close this as the batch function and api resolve the reported issue
