### ISSUE TITLE
JHTML::email::cloak fires HTML5 warning

### ISSUE THREAD

**Issue by thuebschmann** [joomla/joomla-cms#23300]
### Steps to reproduce the issue
enable emailcloack plugin
set document->isHTML5(true)
have an emial in Content
Check the gernerated page with https://validator.w3.org/nu/

### Expected result
Generate Html without the type attribute in inline-script tag
<span id="cloake7fa3ec772fcb512429aabca45b631b7">Diese E-Mail-Adresse ist vor Spambots geschützt! Zur Anzeige muss JavaScript eingeschaltet sein!</span><script>
				document.getElementById('cloake7fa3ec772fcb512429aabca45b631b7').innerHTML = '';
				var prefix = '&#109;a' + 'i&#108;' + '&#116;o';
				var path = 'hr' + 'ef' + '=';
				var addye7fa3ec772fcb512429aabca45b631b7 = '&#105;nf&#111;' + '&#64;';
				addye7fa3ec772fcb512429aabca45b631b7 = addye7fa3ec772fcb512429aabca45b631b7 + 'w&#101;k&#111;24' + '&#46;' + 'd&#101;';
				var addy_texte7fa3ec772fcb512429aabca45b631b7 = '&#105;nf&#111;@w&#101;k&#111;24.d&#101; ';document.getElementById('cloake7fa3ec772fcb512429aabca45b631b7').innerHTML += '<a ' + path + '\'' + prefix + ':' + addye7fa3ec772fcb512429aabca45b631b7 + '\'>'+addy_texte7fa3ec772fcb512429aabca45b631b7+'<\/a>';
		</script>

### Actual result
<span id="cloake7fa3ec772fcb512429aabca45b631b7">Diese E-Mail-Adresse ist vor Spambots geschützt! Zur Anzeige muss JavaScript eingeschaltet sein!</span><script **type='text/javascript'**>
				document.getElementById('cloake7fa3ec772fcb512429aabca45b631b7').innerHTML = '';
				var prefix = '&#109;a' + 'i&#108;' + '&#116;o';
				var path = 'hr' + 'ef' + '=';
				var addye7fa3ec772fcb512429aabca45b631b7 = '&#105;nf&#111;' + '&#64;';
				addye7fa3ec772fcb512429aabca45b631b7 = addye7fa3ec772fcb512429aabca45b631b7 + 'w&#101;k&#111;24' + '&#46;' + 'd&#101;';
				var addy_texte7fa3ec772fcb512429aabca45b631b7 = '&#105;nf&#111;@w&#101;k&#111;24.d&#101; ';document.getElementById('cloake7fa3ec772fcb512429aabca45b631b7').innerHTML += '<a ' + path + '\'' + prefix + ':' + addye7fa3ec772fcb512429aabca45b631b7 + '\'>'+addy_texte7fa3ec772fcb512429aabca45b631b7+'<\/a>';
		</script>

### System information (as much as possible)
Database Type 	mysql
Datenbankversion 	5.6.19-67.0-log
Datenbankzeichensatz 	utf8_general_ci
Datenbankverbindungszeichensatz 	utf8mb4_general_ci
PHP-Version 	7.2.11
Webserver 	Apache/2.4.35
PHP-Interface für den Webserver 	cgi-fcgi
Joomla!-Version 	Joomla! 3.9.1 Stable [ Amani ] 27-November-2018 15:00 GMT
Joomla!-Plattform-Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Browsererkennung 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0 

### Additional comments
I think you must changee the /libraries/cms/html/email.php file on line 102 and remove the hard code

**Comment by mbabker** [comment]
HTML5 says the type CAN be omitted and the default `text/javascript` MIME is assumed, it does not say that the type MUST be omitted when the type is the default `text/javascript` MIME, see https://www.w3.org/TR/html5/semantics-scripting.html#element-attrdef-script-type for reference.  So it's fine as is for now.

**Comment by richard67** [comment]
This issue should be closed for reason stated above by mbabker.
