### ISSUE TITLE
wrong og:description for categories

### ISSUE THREAD

**Issue by Vitaliy214** [joomla/joomla-cms#23306]
### Steps to reproduce the issue
Create a category with materials

### Expected result
og: description category is incorrect, displays og: description from the first listed material in the category

### System information (as much as possible)
PHP Linux cook-house 2.6.32-042stab127.2 # 1 SMP Mon Aug 27 21:07:08 MSK 2018 x86_64
Database type mysql
Database Version 5.5.5-10.1.26-MariaDB-0 + deb9u1
Coding database utf8_general_ci
Database connection encoding utf8mb4_general_ci
PHP Version 7.2.13
Apache / 2.4.25 Web Server (Debian)
Interface between web server and PHP cgi-fcgi
Joomla version! Joomla! 3.9.1 Stable [Amani] 27-November-2018 15:00 GMT
Joomla version! Platform Joomla Platform 13.1.0 Stable [Curiosity] 24-Apr-2013 00:00 GMT
Mozilla / 5.0 user browser (Windows NT 6.1; Win64; x64) AppleWebKit / 537.36 (KHTML, like Gecko) Chrome / 71.0.3578.98 Safari / 537.36

**Comment by SharkyKZ** [comment]
Joomla! does not have OpenGraph tags out of the box. You must be using a 3rd party extension. In which case you should report this issue to its developer.
