### ISSUE TITLE
Joomla\CMS\Table\Menu::_getNode(1, ) failed.

### ISSUE THREAD

**Issue by louisjansen** [joomla/joomla-cms#23302]
### Steps to reproduce the issue
I dont' know when this first happened but for some of my components I am missing the menu items in the administrator menu. Reinstalling the component generates

1) Error: Joomla\CMS\Table\Menu::_getNode(1, ) failed.
2) Warning: Eror building Administrator Menus.

Some components where this is happening are:
* Google Structured Data by Tassos Marinos
* Extension Manager by Regular Labs

The components work fine and can be requested by typing the exact payload in the browser address bar.![screen shot 2018-12-19 at 15 05 09](https://issues.joomla.org/uploads/1/0dc534b5785f55b4aff9e40a2ce05302.png)

### Expected result
Not getting warnings and errors when installing components
Visible administrator menu items for all installed components

### Actual result
No administrator menu items for some components
Getting error and warning every time install or update the component

### System information (as much as possible)
Joomla 3.9.1
SP Page Builder + template
MySQL 5.7.20-18
PHP 7.1.22

**Comment by louisjansen** [comment]
Also happens with updating SP Page Builder to latest version<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23302">issues.joomla.org/tracker/joomla-cms/23302</a>.</sub>

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/20436
