### ISSUE TITLE
3rd Party Extensions Pre-Update Check compatability column showing "Unkown error"

### ISSUE THREAD

**Issue by rgjoyce** [joomla/joomla-cms#23311]
In the process of porting to Joomla 4.
In the Joomla updater component, I see "Unkown error"
1) should be "Unknown error" not "unkown error"
but the main problem
3) WHY Unkown error?
What is the system checking for in this column?

**Comment by ReLater** [comment]
Typo `unkown` instead of `unknown` corrected in language file with https://github.com/joomla/joomla-cms/pull/23313

**Comment by rgjoyce** [comment]
can someone tell me how I can get access to the code to check the bugs that I report?

**Comment by rgjoyce** [comment]
Also, is there any response about point 2?

**Comment by ReLater** [comment]
> how I can get access to the code

[GitHub](https://github.com/joomla/joomla-cms/)

Click tabulator `Code`, select the `Branch`, e.g. `4.0-dev` OR a `Tag` for already released versions. Browse through folders/files. Be aware that lots of vendor libraries aren't present in the 4.0 repository on GitHub.

[Using the Github UI to Make Pull Requests](https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests)

**Comment by ghost** [comment]
closed as Question is answered.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23311">issues.joomla.org/tracker/joomla-cms/23311</a>.</sub>
