### ISSUE TITLE
reCaptcha plugin is not working when editor plugin is loaded

### ISSUE THREAD

**Issue by corejoomla** [joomla/joomla-cms#23322]
### Steps to reproduce the issue
In any component form page, load the editor using below code
`<?php echo $form->getInput('description'); ?>`

and load recaptcha plugin with below code

```
JPluginHelper::importPlugin('captcha');
$app->triggerEvent('onInit', array(null, 'ca_captcha'));
$recaptcha = $app->triggerEvent('onDisplay', array(null, 'ca_captcha', 'class=""'));
echo (isset($recaptcha[0])) ? $recaptcha[0] : '';
```

### Expected result

Both editor and recaptcha loaded

### Actual result
throws error and it shows below error in stacktrace
`Too few arguments to function PlgEditorTinymce::onDisplay(), 3 passed in D:\xampp\htdocs\j4\libraries\src\Plugin\CMSPlugin.php on line 287 and at least 6 expected`

### System information (as much as possible)

Joomla 4, XAMPP, PHP 7.2

### Additional comments
Both captcha and editor plugins are using same `onInit` and `onDisplay` functions which may be the reason for the issue.

**Comment by Quy** [comment]
See PR #23331<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23322">issues.joomla.org/tracker/joomla-cms/23322</a>.</sub>
