### ISSUE TITLE
Error updating Joomla! 2.5 to 3.5.1

### ISSUE THREAD

**Issue by pedro-maschio** [joomla/joomla-cms#23328]
### Steps to reproduce the issue
I tried to update Joomla! 2.5 to other version using the Components > Joomla! Update button, which returned an error.

### Expected result
A Joomla! update.

### Actual result
Update: :Extension: Could not open http://www.mapkcode.com/updates/mk-countdown.xml
Update: :Collection: Could not open http://update.joomlapt.com/translationlist.xml
Update: :Extension: Could not open https://www.joomlacontenteditor.net/index.php?option=com_updates&view=update&format=xml&file=jcemediabox.xml
Update: :Extension: Could not open https://deploy.ostraining.com/client/update/free/stable/lib_allediaframework/extension.xml
Update: :Extension: Could not open http://www.joomshaper.com/updates/mod_sp_tweet.xml

Error loading module MySQL server has gone away SQL=SELECT m.id, m.title, m.module, m.position, m.content, m.showtitle, m.params, mm.menuid FROM fonkx_modules AS m LEFT JOIN fonkx_modules_menu AS mm ON mm.moduleid = m.id LEFT JOIN fonkx_extensions AS e ON e.element = m.module AND e.client_id = m.client_id WHERE m.published = 1 AND e.enabled = 1 AND (m.publish_up = '0000-00-00 00:00:00' OR m.publish_up <= '2018-12-23 21:58:28') AND (m.publish_down = '0000-00-00 00:00:00' OR m.publish_down >= '2018-12-23 21:58:28') AND m.access IN (1,1,2,3) AND m.client_id = 1 AND (mm.menuid = 0 OR mm.menuid <= 0) ORDER BY m.position, m.ordering

I really need to update this website.

**Comment by Quy** [comment]
Please use [Joomla Forums](https://forum.joomla.org/viewforum.php?f=710) for assistance.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23328">issues.joomla.org/tracker/joomla-cms/23328</a>.</sub>
