### ISSUE TITLE
Warning with "continue" in dispatcher.php

### ISSUE THREAD

**Issue by fredo-m** [joomla/joomla-cms#23338]
Hi,

I accessed the post-install messages display page, and I have:

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/.../libraries/fof/dispatcher/dispatcher.php on line 524

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/.../libraries/fof/dispatcher/dispatcher.php on line 529

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/.../libraries/fof/dispatcher/dispatcher.php on line 534

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/.../libraries/fof/dispatcher/dispatcher.php on line 539

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/.../libraries/fof/dispatcher/dispatcher.php on line 552

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/.../libraries/fof/dispatcher/dispatcher.php on line 561

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/.../libraries/fof/dispatcher/dispatcher.php on line 566

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/.../libraries/fof/dispatcher/dispatcher.php on line 580

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/.../libraries/fof/dispatcher/dispatcher.php on line 609

With PHP 7, continue with a switch can be considered a break.
We must add an argument: 

http://php.net/manual/en/control-structures.continue.php
Note: In PHP the switch statement is considered a looping structure for the purposes of continue. continue behaves like break (when no arguments are passed). If a switch is inside a loop, continue 2 will continue with the next iteration of the outer loop. 

### System information (as much as possible)
Joomla! 3.9.1 Stable [ Amani ] 27-November-2018 15:00 GMT 
PHP 7.3.0-2 (Debian)

Regards.

**Comment by PhilETaylor** [comment]
@nikosdion :)

**Comment by nikosdion** [comment]
As we have made clear to the Joomla! project we discontinued the extended support for FOF 2 in June 2016. This is 2 years longer than what we had originally been asked to provide.

Since Joomla! decided back in 2013 to remove FOF from future versions you should have rewritten the post-installation messages component to use core MVC. That component was never meant to be a final version. It was a quick and dirty solution to a pressing problem shortly before release. I guess institutional memory was lost when the people involved left (or where made to leave) the project.

Seriously, FOF 2's code is long gone from working memory and has mostly faded from my long term memory as well. I haven't touched it in nearly 4 years. Feel free to replace `continue` with `continue 2` and add a note after the copyright header that this file is a modified version of the original. That's the GPL-compatible way to go about it.

**Comment by Ndatenda** [comment]
How can it be that with PHP 7.3 the problem occurs but not with 7.2? 

Joomla! 3.9.3-rc Release Candidate [ Amani ] 9-February-2019 19:20 GMT 
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 
PHP Version 7.3.1
System | Windows NT DESKTOP-5Q3Q8BN 10.0 build 17134 (Windows 10) i586
Build Date | Jan  9 2019 22:19:38
Compiler | MSVC15 (Visual C++ 2017)
Loaded Configuration File | C:\xampp\php\php.ini

**Comment by brianteeman** [comment]
Because php changed

**Comment by Ndatenda** [comment]
but if the support ended already in June 2016, 
and the Joomla!-installation is working with PHP 7.2.14 (Released: 07 Feb 2019), 
then why doesn't it work with PHP 7.3?
Doesn't that mean that the change must have happened from PHP 7.2 to PHP 7.3?!

Sorry if I'm asking stupid questions. Just wanted to point it out for others who might come across similar problem, or for Joomla! to update (?) dispatcher.php

**Comment by nikosdion** [comment]
The change in behaviour was indeed introduced in PHP 7.3.0. 

The use of `continue` inside a `switch` statement did NOT throw a warning in PHP 5 and PHP 7.0 to 7.2 inclusive. In PHP 7.3 it started throwing a PHP Warning. In PHP 7.4 or 8.0 (it's not yet set in stone) it will be not allowed and throw a PHP Error.

**Comment by PhilETaylor** [comment]
PR https://github.com/joomla/joomla-cms/pull/23858

**Comment by Quy** [comment]
Please test PR #23866<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23338">issues.joomla.org/tracker/joomla-cms/23338</a>.</sub>

**Comment by ReLater** [comment]
@Quy PR #23866 is closed without merge.

**Comment by Quy** [comment]
Please test PR #23873<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23338">issues.joomla.org/tracker/joomla-cms/23338</a>.</sub>

**Comment by peterhulst** [comment]
Hello,

On a local XAMPP installation with PHP 7.3.4 and Joomla 3.9.4 I still have this issue.
Is this normal or should it have been solved?

Regards,
Peter<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23338">issues.joomla.org/tracker/joomla-cms/23338</a>.</sub>

**Comment by peterhulst** [comment]
But now it is in:
libraries\f0f\dispatcher\dispatcher.php on line 524

so f0f instead fof.

Replacing the displatcher.php in f0f with that of fof (and editing fof-->f0f) solved the problem (file added with changed filetype)[dispatcher.txt](https://issues.joomla.org/uploads/1/9ce29c8b68b05f4530b62e02cb2e65c7.txt)

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23338">issues.joomla.org/tracker/joomla-cms/23338</a>.</sub>

**Comment by ReLater** [comment]
@peterhulst 

> so f0f instead fof.

`f0f` is not part of the Joomla core. Normally all current Akeeba extensions use a newer FOF (e.g. `fof30`) and not `f0f` any more.

This said I think that you use another extension that uses an outdated version of `f0f` or your extensions aren't up to date.

Your issue is not a core issue and you should ask in a forum.

**Comment by peterhulst** [comment]
Thank you! I think it is 'Autotweet'. 
The map: f0f is there because of remains of an older installation I guess

**Comment by alexsnitol** [comment]
@peterhulst

Thank you! Your decision helped me!

I use J2Store.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23338">issues.joomla.org/tracker/joomla-cms/23338</a>.</sub>
