### ISSUE TITLE
J4 Alpha 6 update fails

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#23346]
### Steps to reproduce the issue
Install Joomla 3.9.1
Update by custom url  https://update.joomla.org/core/nightlies/next_major_list.xml or by downloading the update package and using Joomla upload and install

### Expected result
Update should work

### Actual result
ERROR:
Invalid AJAX data:
<br />
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught Error: Class 'Joomla\CMS\Filesystem\AKFactory' not found in C:\wamp64-3-1-4\www\j391\administrator\components\com_joomlaupdate\restore_finalisation.php on line <i>124</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Error: Class 'Joomla\CMS\Filesystem\AKFactory' not found in C:\wamp64-3-1-4\www\j391\administrator\components\com_joomlaupdate\restore_finalisation.php on line <i>124</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0007</td><td bgcolor='#eeeeec' align='right'>463536</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp64-3-1-4\www\j391\administrator\components\com_joomlaupdate\restore.php' bgcolor='#eeeeec'>...\restore.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0373</td><td bgcolor='#eeeeec' align='right'>535184</td><td bgcolor='#eeeeec'>finalizeRestore(  )</td><td title='C:\wamp64-3-1-4\www\j391\administrator\components\com_joomlaupdate\restore.php' bgcolor='#eeeeec'>...\restore.php<b>:</b>8335</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0650</td><td bgcolor='#eeeeec' align='right'>536952</td><td bgcolor='#eeeeec'>JoomlaInstallerScript->deleteUnexistingFiles(  )</td><td title='C:\wamp64-3-1-4\www\j391\administrator\components\com_joomlaupdate\restore_finalisation.php' bgcolor='#eeeeec'>...\restore_finalisation.php<b>:</b>75</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0662</td><td bgcolor='#eeeeec' align='right'>537048</td><td bgcolor='#eeeeec'>Joomla\CMS\Filesystem\File::delete(  )</td><td title='C:\wamp64-3-1-4\www\j391\administrator\components\com_admin\script.php' bgcolor='#eeeeec'>...\script.php<b>:</b>3952</td></tr>
</table></font>

**Comment by Quy** [comment]
Duplicate #23315 ?

**Comment by richard67** [comment]
Expected result is wrong. There is no valid update path from 3.9 to 4.0. See discussion in #23315 .
