### ISSUE TITLE
J4 Alpha 6 sample data fails

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#23347]
### Steps to reproduce the issue
Install Joomla_4.0.0-alpha6-dev-Development-Full_Package.zip
Try and install sample data

### Expected result
Sample data installs

### Actual result
Fails stating a error in the sample data plugin.

**Comment by wojsmol** [comment]
@Webdongle Which saple data plugin you tested?

**Comment by Webdongle** [comment]
@wojsmol  Not the multilanguage.  Cant remember what it was called ... the top one of the two choices ... might have been 'blog' ?

Tested on wamp localhost php 7.2.10

**Comment by wojsmol** [comment]
@Webdongle Issue confirmed and already fixed with #23344 and #23293 only administrator/components/com_menus/Model/ItemModel.php change.
