### ISSUE TITLE
[4.0] Proposal: Remove the confirm password from user

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#23345]
### Steps to reproduce the issue
In former Joomla Versions, a password confirm field was added to the user edit, to reduce errors in entering a password. 
In J4.0 we have a button which shows the password in plain text, if desired. 
This is a more comfortable solution for avoiding errors.
I suggest to remove the confirm-password field from the user edit view. 

![screen shot 2018-12-26 at 22 39 21](https://issues.joomla.org/uploads/1/ac46cbc609d02547921caca8be1af554.png)

**Comment by C-Lodder** [comment]
Thought I already removed this

**Comment by wojsmol** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/23357
