### ISSUE TITLE
clean cache function cannot really clean the custom component's settings in redis db. Joomla 3.9.x with Redis 3.2.10

### ISSUE THREAD

**Issue by kingyond** [joomla/joomla-cms#23352]
### Steps to reproduce the issue
installed Redis 3.2.10 as cache server.
create new custom component with settings in config.xml
installed the custom component.
try to use params,
$params = JComponentHelper::getParams("com_custom_xxx",true);//replace com_custom_xxx as the correct name.
        var_dump($params);
change the settings from the custom component default settings page.
again try to use the params, but this time.
the result the $params has no value. (It may has correct values after minutes later, maybe wait for the cache expired)
try to clear all cache from com_cache component page.
try to user the params again.
the params still empty (or the old's values)

### Expected result
after try to clean all cache from com_cache component page.
try to use params again, the params should refresh and replace with new changed settings.

### Actual result
the clean cache function cannot delete the correct redis cache.

### System information (as much as possible)
Joomla 3.9.x
Redis 3.2.10
Php 7.10.x
Centos 7.4
nginx 1.14.2

### Additional comments
try to use redis-cli to clean the cache db. the cache refresh immediately.

**Comment by richard67** [comment]
@kingyond Where did you get PHP 7.10.x? Right now, latest version is 7.3.x!

**Comment by ghost** [comment]
closed as no Response but Issue can always be reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23352">issues.joomla.org/tracker/joomla-cms/23352</a>.</sub>
