### ISSUE TITLE
[4.0] com_csp in sample data missing

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#23359]
### Steps to reproduce the issue
- Install a new Joomla! instance
- Install the sample data in the installation process
- Finish installation

### Expected result
com_csp is in the backendmenu

### Actual result
com_csp is missing

### Additional comments
https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/sql/mysql/joomla.sql#L1222

**Comment by infograf768** [comment]
It is also missing when not installing sample data.

1. Class is wrong in the xml or in the sql..
`associations` vs `csp`
2. It is accessible via System=>Manage

BTW, that component is a mystery to me... What are its parameters? What kind of reports shall we get?

**Comment by infograf768** [comment]
OK, found the issue here: the component_id for com_csp was the id of com_workflow in extensions.
Once this id is modified the menu displays:
![screen shot 2018-12-28 at 16 13 07](https://user-images.githubusercontent.com/869724/50519494-83541a80-0abb-11e9-9669-75a53ae98e7e.png)

**Comment by infograf768** [comment]
It should be 36
`(23, 'main', 'com_csp', 'Content-Security-Policy', '', 'Content-Security-Policy', 'index.php?option=com_csp', 'component', 1, 1, 1, 36, 0, '0000-00-00 00:00:00', 0, 0, 'class:associations', 0, '', 41, 42, 0, '*', 1),` 
instead of 35

**Comment by Quy** [comment]
Please test PR #23586<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23359">issues.joomla.org/tracker/joomla-cms/23359</a>.</sub>
