### ISSUE TITLE
Marking unread messages as read must work

### ISSUE THREAD

**Issue by ZerooCool** [joomla/joomla-cms#23354]
### Steps to reproduce the issue
/administrator/index.php?option=com_messages&view=messages

### Expected result
marking unread messages as read must work.

### Actual result
I have this on a new Joomla, the read message feature does not seem to work.

### System information (as much as possible)
Apache 2.4
Debian SID
PHP 7.2
Actual stable Joomla Version ( And it's a new installation. )

**Comment by Quy** [comment]
Duplicate #23221<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23354">issues.joomla.org/tracker/joomla-cms/23354</a>.</sub>

**Comment by ZerooCool** [comment]
This should have been solved with #23192
Will be available in 3.9.2

Closing as duplicate.

Ok, thank you.
