### ISSUE TITLE
Character counter for meta description?

### ISSUE THREAD

**Issue by AK-CCM** [joomla/joomla-cms#23358]
This is a feature request for Joomla! 4.

It would be great if anyone could implement a character counter beneath the field of the meta description.

**Comment by b2z** [comment]
For Joomla 3 [there is a plugin](https://github.com/wedal/plg_wedal_meta_counter "") that displays the counter for title and meta description. I think it should work for Joomla 4 also.
![screen shot 2018-12-28 at 07 17 04](https://issues.joomla.org/uploads/1/50017458822f8c84d3b8ddbb54e1502d.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23358">issues.joomla.org/tracker/joomla-cms/23358</a>.</sub>

**Comment by b2z** [comment]
For Joomla 3 [there is a plugin](https://github.com/wedal/plg_wedal_meta_counter "") that displays the counter for title and meta description. I think it should work for Joomla 4 also.
![screen shot 2018-12-28 at 07 17 04](https://issues.joomla.org/uploads/1/50017458822f8c84d3b8ddbb54e1502d.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23358">issues.joomla.org/tracker/joomla-cms/23358</a>.</sub>

**Comment by AK-CCM** [comment]
Yes, the plugin is working in Joomla 4 - I've tried it with the Alpha 5:

![screen shot 2018-12-28 at 09 30 18](https://issues.joomla.org/uploads/1/b4fa6d93150620d305589855d5072237.png)

But this is a reverse character counter with fixed values. I think a simple character counter is more useful, because Google and perhaps another search engines too change the max length of titles and meta descriptions from time to time.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23358">issues.joomla.org/tracker/joomla-cms/23358</a>.</sub>

**Comment by b2z** [comment]
Well you can set up max values in plugin settings easily.

**Comment by tonypartridge** [comment]
Should be fairly simple to add, possible adjust the JForm fields to have a display count when limit is in force

**Comment by ghost** [comment]
@AK-CCM can this Issue be closed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23358">issues.joomla.org/tracker/joomla-cms/23358</a>.</sub>

**Comment by ghost** [comment]
Closed as no Answer; please reopen if needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23358">issues.joomla.org/tracker/joomla-cms/23358</a>.</sub>
