### ISSUE TITLE
Redirection on Wordpress Website

### ISSUE THREAD

**Issue by pk2234** [joomla/joomla-cms#23361]
### Steps to reproduce the issue
I'm trying to redirect HTTP to HTTPS but it's not working.

Actually recently I updated my website with SSL certificate in that everything is done. I have added redirect code in my .htaccess file.

RewriteEngine On RewriteCond %{HTTPS} off RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301] But the only Homepage working perfectly. It’s automatically redirecting http://www.lyricsfed.com to https://www.lyricsfed.com
But all others page/post did not get redirecting. I am using your plugin, please give me a solution for all page redirecting.

I want to redirect my all post automatically.

Example: http://www.example.com/post/ to https://www.example.com/post/

Pleases short out my problem.

**Comment by tonypartridge** [comment]
This is Joomla! GitHub for coding related issues to Joomla! Please use google for your Wordpress issues.
