### ISSUE TITLE
[4.0] Languages: Installed. Switch Language button.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#23365]
### Steps to reproduce the issue
- Install Joomla_4.0.0-alpha7-dev-Development-Full_Package, nightly build, Friday, 28 December 2018 03:00:39 UTC.
- Install an additional language: `administrator/index.php?option=com_installer&view=languages`
- Go to "Languages: Installed" view: `administrator/index.php?option=com_languages&view=installed`
- Change "client" filter: Site/Administrator. 

### Expected result
- I don't know.

#### Client = Administrator (button displayed)

![28-12-_2018_15-29-38](https://user-images.githubusercontent.com/20780646/50518393-a976bc00-0ab5-11e9-8ce4-3dae15d44e3d.jpg)

#### Client = Site  (button not displayed)

![28-12-_2018_15-30-24](https://user-images.githubusercontent.com/20780646/50518399-b72c4180-0ab5-11e9-9c65-18ea9bf6c692.jpg)

**Comment by infograf768** [comment]
The Switch Language button has exactly the same role in 4.x as for 3.x.
It lets change the admin language without setting the new chosen admin language as default.
This is not a bug but a feature.

Closing.
