### ISSUE TITLE
Version 4 Alpha 6 Release Not Installable

### ISSUE THREAD

**Issue by mavrosxristoforos** [joomla/joomla-cms#23372]
### Steps to reproduce the issue

1. Go to [Joomla Releases](https://github.com/joomla/joomla-cms/releases) and download the package for Joomla 4 Alpha 6.
2. Extract the archive contents in your web server desired directory
3. Open in web browser

### Expected result

Joomla Installation process

### Actual result

An admittedly beautiful error screen that mentions: "It looks like you are trying to run Joomla! from our git repository. To do so requires you complete a couple of extra steps first." and a link to [Setting Up Your Local Environment](https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment).

I did not clone the git repository. But then, of course, I tried to follow the instructions found in the help link. It mentions to run `composer install` in the root directory of the git repo. One assumes, that this means to run the command in the downloaded and extracted directory. I did try that, but there is no composer.lock file.
So, do we have to clone the repository to test the latest Joomla alpha release? If yes, shouldn't that be specifically described in the release notes? Again, if yes, why include a non working Joomla_4.0.0-alpha6-Alpha-Full_Package.* file?
I am assuming (and hoping) that this is just an issue with the release, rather than a change of the release process.

### System information (as much as possible)

Windows 10, WAMP 64, PHP 7.0.4, Composer 1.7.3, Node.js 8.9.4, NPM 5.6.0

### Additional comments

This issue is similar to [issue 22945](https://github.com/joomla/joomla-cms/issues/22945). However, in that issue it is mentioned that the Alpha 6 process would be different.

**Comment by ghazal** [comment]
Unfortunately, I think you are right.
[This release](https://github.com/joomla/joomla-cms/releases) is missing the necessary composer.lock and composer.json to install composer. 

actually there are 2 distributions of J4,
[the one in Nightly Builds](https://developer.joomla.org/nightly-builds.html)
now alpha 7, and installable normally

[and the github one](https://github.com/joomla/joomla-cms/tree/4.0-dev)
with all the necessary files to install composer (and node and npm for that matter). 
All required/mandatory in this distribution.

What I understand is that maybe there has been a mixup between these two.

But I might be wrong.

**Comment by richard67** [comment]
Issue #22945 is misleading. It tells to use nightly build, but as well as the nightly builds also the alpha 6 release build should contain the generated files and dependencies, so `composer install` and `npm install` should not be necessary with any build, and cloning the repository should also not be necessary.

I assume that in the same way as is was with alpha 5, the alpha 6 does not contain generated files and dependencies because either `composer install` or `npm install` has crashed or not been executed during the build phase.

**Comment by richard67** [comment]
@zero-24 @wilsonge Could you check if I am right with my previous comment and if necessary rebuild alpha 6 so we have new containers (zip, tgz, ...)?

**Comment by richard67** [comment]
@zero-24 @wilsonge I've just compared the alpha 6 container (zip) with the one of the nightly build of today.

In alpha 6 the file `libraries/vendor/autoload.php` is missing, which should have been generated by composer and is present in the nightly build.

Can this be the reason why installing alpha 6 fails with the famous "It looks like you are trying to run Joomla! from our git repository.  ..." message?

**Comment by zero-24** [comment]
> Can this be the reason why installing alpha 6 fails with the famous "It looks like you are trying to run Joomla! from our git repository. ..." message?

Yes :)

**Comment by richard67** [comment]
So who will rebuild the alpha 6 containers (zip, tgz)?

**Comment by wilsonge** [comment]
I will get on it. Apologies

**Comment by richard67** [comment]
@wilsonge You owe us all a beer 👅

**Comment by wilsonge** [comment]
Packages are updated. i think they have the right composer files this time. apologies.

**Comment by richard67** [comment]
@wilsonge I can confirm that compared to the old alpha 6 zip, the new one in addition contains file `libraries/vendor/autoload.php` and folder `libraries/vendor/composer` (with files in it).

@mavrosxristoforos Can you download the package for Joomla 4 Alpha 6 again and test if your issue is solved? If not, post back here.
