### ISSUE TITLE
"Warning: count(): Parameter must be an array or an object that implements Countable" in J3 with PHP 7.3

### ISSUE THREAD

**Issue by VisiGod** [joomla/joomla-cms#23377]
### Steps to reproduce the issue
Use php version 7.3. In any view that has the code:
if (count($errors = $this->get('Errors'))) {
a warning appears that says "Warning: count(): Parameter must be an array or an object that implements Countable in [put view file here]"

After some testing, I was able to replace the code to:
if ($this->get('Errors') && count($errors = $this->get('Errors'))) {

and no longer have the warning

### Expected result
No warning on code

**Comment by ReLater** [comment]
> After some testing, I was able to replace the code

Could you please inform us where you got the error and in which file you've added your fix.

**Comment by ReLater** [comment]
Ah, sorry. I didn't see

> Use php version 7.3. In any view that has the code:

**Comment by VisiGod** [comment]
I can do a list of files that produce that error if needed.

**Comment by ReLater** [comment]
I would make a single Pull Request first (before I waste my time with lots of files) and wait for comments of the experts here. If they say "Solution is OK" then one could fix all other codes.

Start your Pull Request title with a `[RFC]` (request for comments).

HowTo:  [Using the Github UI to Make Pull Requests](https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests/en)

**Comment by trailsnail** [comment]
@VisiGod 
`if ($this->get('Errors') && count($errors = $this->get('Errors'))) {`
is not the best solution.

I would use `if (!empty($this->get('Errors'))) {`

or if `$errors` is used later in code:

`$errors = $this->get('Errors');`
`if (!empty($errors)) {`

I do not know the code, but I'm always in favor of calling a method only once and using its result.
It may be that in your example the double calling of `$this->get('Errors')` will execute function code twice which would not be the best for performance reasons


2nd solution would be, if `$this->get('Errors')` will always `return array()` if no errors exist. So errors on all callsites will be fixed. but as I said - I don't know the code ;)

**Comment by PhilETaylor** [comment]
Apart from just doing a code review itself, have you actually received this error message output on a live Joomla site ?

Are you able to provide a replicateable test case?

I understand the PHP 7 compatibility issue well - but Im struggling to understand why we are not receiving more reports about the error... maybe Joomla is never running those areas of code?

**Comment by VisiGod** [comment]
This was found when testing against PHP 7.3 which is not widely used on production. Since I was testing the component on 7.3, this core error appeared.

**Comment by SharkyKZ** [comment]
I can't reproduce this on core. But `count()` calls can be removed anyways if their result is not used elsewhere.

**Comment by ghost** [comment]
closed for Reason stated above.
