### ISSUE TITLE
Joomla version 3.9.1

### ISSUE THREAD

**Issue by Sybergypsy** [joomla/joomla-cms#23382]
I am trying to update to Joomla version 3.9.1 on www.ladismith.org.za/administrator but it progresses to 74% each time and then gives an error saying "Invalid login". I have spoken to the web hosts but they can not assist me - they have updated the PHP version but are now stuck and unable to resolve this issue. Please assist urgently? See screenshots![screen shot 2018-12-29 at 07 14 54](https://issues.joomla.org/uploads/1/33fb9666bbd03f0d918679a2688683db.png) attached. Thanks!![screen shot 2018-12-29 at 07 14 54](https://issues.joomla.org/uploads/1/1c56b8d0aaa6830d04e614e3d186bf87.png)

**Comment by DavidBoggitt** [comment]
Do you definitely have enough web space for the download?

**Comment by Bakual** [comment]
Please use the Joomla forums (http://forum.joomla.org) for support questions. This tracker here is about code issues.

**Comment by Sybergypsy** [comment]
Hello!

I am not sure. How much do I need and how do I check?

**Comment by Bakual** [comment]
As written, please take it to the forums.
