### ISSUE TITLE
[4.0] Administrator modules. No positions selectbox

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#23398]
### Steps to reproduce the issue
- 4.0 Nightly of yesterday.
- Go to "Modules (Administrator)": `administrator/index.php?option=com_modules&client_id=1`
- Click "New" and select whatever module type.
- Try to select a Position. No dropdown. No positions provided. Text field.

**Comment by Quy** [comment]
See PR #23289

**Comment by ReLater** [comment]
Thank you! PR solves the issue
