### ISSUE TITLE
launch.joomla.org sites using out of date PHP and Joomla 3.9.1

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#23399]
### Steps to reproduce the issue
Register a subdomain at joomla.com for testing purposes (hosted by CloudAccess.net) following instructions on launch.joomla.org which can be reached by clicking the blue button at the top right of the Joomla! Issue Tracker page.

### Expected result
Joomla! 4 Alpha 6
Up-to-date PHP 7.1 min

### Actual result
Joomla 3.9.1
PHP 7.0.33 plus this message, which was also on the Joomla! 4 Alpha 5 site last week (see Additional notes):

Error
We have detected that your server is using PHP 7.0.33 which is obsolete and no longer receives official security updates by its developers. The Joomla! Project recommends upgrading your site to PHP 7.1 or later which will receive security updates at least until 2019-12-01. Please ask your host to make PHP 7.1 or a later version the default version for your site. If your host is already PHP 7.1 ready please enable PHP 7.1 on your site's root and 'administrator' directories – typically you can do this yourself through a tool in your hosting control panel, but it's best to ask your host if you are unsure

### System information (as much as possible)
N/A

### Additional comments
This is the second site I have tried to use. The first one - set up on 22nd December, which was on Joomla! 4 Alpha 5 - has disappeared.

### UPDATE
I can now not access the new subdomain. CloudAccess.net says it does not exist. (Message: Oops, something went wrong... please check back in a bit.

If you are the owner of this website, you may want to check the common causes for this Apache error:

    The requested URL does not exist on this site
    The site encountered internal error
    This site is not properly configured within the CloudAccess.net network

If you continue to see this error message please submit a support ticket in your Cloud Control Panel and the CloudAccess.net Team would be happy to help.

Thank you, CloudAccess.net"

That's only 15 minutes after I created it!
I have attempted to submit a support ticket, but their bug reporting tool just loops back to the main submit ticket page, and there's no option to actually submit one.

**Comment by Quy** [comment]
Please report issue here: https://github.com/joomla/joomla-websites/issues<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23399">issues.joomla.org/tracker/joomla-cms/23399</a>.</sub>
