### ISSUE TITLE
[4.0] Custom administrator menu. Second "Toggle menu" not working and senseless(?)

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#23397]
### Steps to reproduce the issue
- Apply patch https://github.com/joomla/joomla-cms/pull/23395 or other solution if provided meanwhile.
- Create an additional administrator menu.
- Create a menu item in the new menu
- Create a module "Administrator Menu":
Position: menu
Check Menu: No

### Expected result
- No additional "Toggle menu" or working one

### Actual result
- See image:

![30-12-_2018_17-16-39](https://user-images.githubusercontent.com/20780646/50549095-33aa5600-0c57-11e9-870b-c2dcf3812d58.jpg)

**Comment by ReLater** [comment]
Addition:

Put your custom administrator menu in position "title". All collapse features of the main menu (left sidebar) fail. One cannot expand submenus and so on.

![30-12-_2018_18-22-12](https://user-images.githubusercontent.com/20780646/50549601-f0081a00-0c5f-11e9-8f62-2b4177424d56.jpg)

**Comment by ReLater** [comment]
Reasons are too many hard coded selector `id`s in layout and JavaScript.

**Comment by chmst** [comment]
https://issues.joomla.org/tracker/joomla-cms/23070<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23397">issues.joomla.org/tracker/joomla-cms/23397</a>.</sub>
