### ISSUE TITLE
[4.0] Error while storing a tag

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#23401]
### Steps to reproduce the issue
Try to store a new tag in com_tags.

### Expected result
The tag is stored

### Actual result
An error has occurred.

0 Too few arguments to function PlgContentJoomla::onContentBeforeSave(), 3 passed in D:\xampp\htdocs\joomla-fork\libraries\src\Plugin\CMSPlugin.php on line 287 and exactly 4 expected 

### System information (as much as possible)
PHP Built On 	Windows NT DESKTOP-STILS1K 10.0 build 17134 (Windows 10) i586
Database Type 	mysql
Database Version 	5.5.5-10.1.35-MariaDB
Database Collation 	utf8mb4_unicode_ci
Database Connection Collation 	utf8_general_ci
PHP Version 	7.2.9
Web Server 	Apache/2.4.34 (Win32) OpenSSL/1.1.0i PHP/7.2.9
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 4.0.0-alpha7-dev Development [ Amani ] 27-December-2018 17:58 GMT

**Comment by Quy** [comment]
Please test PR #23395

**Comment by chmst** [comment]
Closed - the PR #23395 fixes the issue
