### ISSUE TITLE
[4.0] Administrator menu. Menu type "Module Manager". No option to select client.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#23400]
### Steps to reproduce the issue
- In a custom administrator menu.
- Ceate a new menu item of type "Module Manager".
- Because **view** "Module Manager" has no filter for "Site/Administrator" and because the **menu item type** "Module Manager" doesn't provide an option to select a `client_id=0` or `client_id=1` it depends on your last visit which modules you see. No chance to switch it.

I propose to bring back the filter "Site/Administrator" in view "Module Manager".

**Comment by chmst** [comment]
I would suggest to have only one Module Overview in the system, every Module could have a badge or an icon for its client. Then there could be a Filter for Frontend (default) and backend, and no need for separate links. 
![screen shot 2018-12-30 at 18 38 43](https://issues.joomla.org/uploads/1/9c6d152a7ad2ce266fcae51231d11b2a.png)




<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23400">issues.joomla.org/tracker/joomla-cms/23400</a>.</sub>

**Comment by mbabker** [comment]
You would have to change modules to not be client specific for that to be viable.  Otherwise, at the absolute minimum, the "new module" button becomes confusing having mixed modules from both applications.

**Comment by chmst** [comment]
You are right. The screen was only "thinking loud" because testers have problems with the two different links to modules. And as @Re:Later writes, it is not userfriendly. Maybe we can go back to the 3.x solution.

**Comment by brianteeman** [comment]
pretty sure @infograf768 has already raised this as an issue

**Comment by infograf768** [comment]
Indeed.
See https://github.com/joomla/joomla-cms/pull/23289
Note and General Comment

**Comment by infograf768** [comment]
Making patch for this now.

**Comment by infograf768** [comment]
Closing as we have a patch
https://github.com/joomla/joomla-cms/pull/23406
Thanks you for testing.
