### ISSUE TITLE
Can not create a contact from menu!

### ISSUE THREAD

**Issue by fvdn** [joomla/joomla-cms#23405]
### Steps to reproduce the issue
Menus -> Main menu -> New -> Select (Menu type item) -> Contacts -> Single contact -> Create

### Expected result
To save of save &close  the contact item

### Actual result
It is not possible to save or save&close the contact item

### System information (as much as possible)
Joomla_4.0.0-alpha7-dev-Development-Update_Package.zip
These packages were built based on commit 0d68d9e23fcb7ba17048cc20b2a2b1c56afc1c46
These packages were last built: Monday, 31 December 2018 03:00:41 UTC
PHP Built On 	Darwin iFred-iMac.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
Database Type 	mysql
Database Version 	5.6.35
Database Collation 	utf8_bin
Database Connection Collation 	utf8_general_ci
PHP Version 	7.1.8
Web Server 	Apache/2.2.32 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.1.8 mod_ssl/2.2.32 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0
WebServer to PHP Interface 	apache2handler
User Agent 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0

**Comment by infograf768** [comment]
Duplicate... https://github.com/joomla/joomla-cms/issues/23260

**Comment by fvdn** [comment]
Yes, i see this issue is already posted.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23405">issues.joomla.org/tracker/joomla-cms/23405</a>.</sub>
