### ISSUE TITLE
New configs to display featured contacts at the top & number of contacts to display on a contact list page.

### ISSUE THREAD

**Issue by vaibhavsTekdi** [joomla/joomla-cms#23408]
### Is your feature request related to a problem? Please describe.

Yes, the user cannot able to see the featured contacts at the top in the contact list & also not able to set the number of contacts to display on a single page.

### Describe the solution you'd like

Add new configs are as follows :

- Contacts to List: Should have a numbers to show contacts on list page with 'All' option.
- Sort By: Featured Contacts Ordering (It will display the featured contacts at the top in the contact list)

Add above configs about showing the number of contacts(default numbers) to display on contact list page & also add a new sort option as 'Featured Contacts Ordering' in sort by config under 'Contacts: Options >> List Layouts' tab as global at the component level.

Also, these configs should available at Joomla contact menu having 'List Contacts in a Category' menu type. Both the configs should have global values as default values. 

Contacts list should display according to contact menu level configs.

### Additional context

With the existing config(s) at Contacts component level options & Contacts menu level, user cannot able to see the featured contacts at the top in the contact list & also not able to set the number of contacts to display on a single page. 
It is showing the contacts sort by name or ordering or sort name etc.

**Comment by Quy** [comment]
See PR #23409<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23408">issues.joomla.org/tracker/joomla-cms/23408</a>.</sub>
