### ISSUE TITLE
[4.0] Cannot empty trash in newsfeeds

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#23403]
### Steps to reproduce the issue
Perform the "empty trash" function to one or more trashed entries in newsfeeds overview.

### Expected result
Items are deleted

### Actual result
Argument 1 passed to Joomla\Component\Newsfeeds\Administrator\Controller\NewsfeedsController::postDeleteHook() must be an instance of Joomla\Component\Newsfeeds\Administrator\Controller\Model, instance of Joomla\Component\Newsfeeds\Administrator\Model\NewsfeedModel given, called in D:\xampp\htdocs\joomla-fork\libraries\src\MVC\Controller\AdminController.php on line 161

**Comment by Quy** [comment]
Please test PR #23445<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23403">issues.joomla.org/tracker/joomla-cms/23403</a>.</sub>
