### ISSUE TITLE
[4.0] notify-alerts/joomla-alert blocks buttons/elements beneath when all messages closed

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#23425]
### Steps to reproduce the issue
- Go in a plugin wit a smaller device/screen size.
- Save it.
- Scroll down until "Plugin saved" message hides the Close button.

![01-01-_2019_23-36-27](https://user-images.githubusercontent.com/20780646/50577013-a6196280-0e1e-11e9-956d-42f68d2ec5d1.jpg)

- Close the green message and try to click on the Close button. Nothing happens.

- Inspector shows empty container:

![01-01-_2019_23-35-46](https://user-images.githubusercontent.com/20780646/50577059-74ed6200-0e1f-11e9-874d-529e618a3329.jpg)

**Comment by ghost** [comment]
Closed as works as expected now. @ReLater please reopen if Issue isn't solved on your Side.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23425">issues.joomla.org/tracker/joomla-cms/23425</a>.</sub>

**Comment by ReLater** [comment]
This isssue isn't solved with current nightly. But I don't know if it should be reopened because of "Wait for final and new backend template atum 4!" whenever things like this issue are reported.
??????

**Comment by Quy** [comment]
Duplicate #21803
