### ISSUE TITLE
[4.0] PR #21558 moved system-message outside if (!empty) in layouts/joomla/system/message.php file

### ISSUE THREAD

**Issue by conseilgouz** [joomla/joomla-cms#23420]
### Steps to reproduce the issue
In https://github.com/joomla/joomla-cms/pull/21558, file layouts/joomla/system/message.php has been updated and <div id="system-message> has been moved outside of its "if !empty($msgList) test (lines 27/28 and 41/42.

If no system has to be displayed  an empty <div id="system-message"></div> is displayed.

If your template has some CSS codes to customize #system-message behaviour, it will be displayed, even if it is unnecessary (empty).

### Expected result
Do not display empty #system-message div

### Actual result
Display an empty #system-message div

### System information (as much as possible)
Joomla 4.0
PHP 7.2.7

**Comment by mbabker** [comment]
The container should always be rendered on the page to allow it to be targeted by the JavaScript API.

**Comment by Quy** [comment]
See PR #23421<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23420">issues.joomla.org/tracker/joomla-cms/23420</a>.</sub>

**Comment by conseilgouz** [comment]
> The container should always be rendered on the page to allow it to be targeted by the JavaScript API.

Hi Michael,

The container is `<div id="system-message-container">` and not `<div id="system-message">`. If no message has to be displayed, there no need to display this extra div. That was working like this prior https://github.com/joomla/joomla-cms/pull/21558.

Happy new year,

Pascal
