### ISSUE TITLE
Smart Search Menu item -> Advanced - Use Global does not always show default state

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#23427]
### Steps to reproduce the issue
Create a menu item for Smart Search
Click on Advanced.
All items are set to "Use Global" but only 1 item has "Use Global (no)".  

### Expected result
Other items should have "Use Global (show)" or "Use Global (hide)" or other relevant feedback.

### Actual result
![smart-search-menu-item](https://user-images.githubusercontent.com/4665225/50603163-7d8e7880-0eb1-11e9-8814-48d584f9da76.png)

### System information (as much as possible)
[systeminfo-2019-01-02T11_12_00-06_00.txt](https://github.com/joomla/joomla-cms/files/2721375/systeminfo-2019-01-02T11_12_00-06_00.txt)

### Additional comments
If someone can point me to the relevant information I could try to fix this if it's within my capeabilities.

**Comment by ReLater** [comment]
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/fields/list.php#L225

If there's no global option you can't display it: See
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/fields/list.php#L211

**Comment by ghost** [comment]
@ReLater does your Comment mean this Issue can be closed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23427">issues.joomla.org/tracker/joomla-cms/23427</a>.</sub>

**Comment by ReLater** [comment]
@franz-wohlkoenig 
From my point of view yes, close it, because
> If there's no global option you can't display it

**Comment by ghost** [comment]
closed as stated above, thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23427">issues.joomla.org/tracker/joomla-cms/23427</a>.</sub>
