### ISSUE TITLE
[4.0] Incorrect instructions in error message

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#23423]
### Steps to reproduce the issue
System-> Templates-> Site template styles-> select template and then click [ Delete ] button.

### Expected result
To be able to delete the template (one I had installed)

### Actual result
Error message with instructions carried over, I think, from Joomla! 3x:
   Error
   Can't delete the last style of a template. To uninstall/delete a 
   template go to: Extensions-> Manage-> Manage-> Select template to be 
   deleted-> Select 'Uninstall'."

1. Why is there a delete button if it can't be used?
2. The message should read as:
   Error
   Can't delete a template here. To uninstall/delete a 
   template go to: System-> Manage-> Extensions-> Select template to be 
   deleted-> Select 'Uninstall'.

### System information (as much as possible)
J4 Alpha 7 nightly build 31/12/18-01/01/19

**Comment by ReLater** [comment]
> Why is there a delete button if it can't be used?

- Your in the **styles** view.
- The button is for deleting STYLES of templates, not for uninstalling templates. Any template can have several styles. But needs at least 1 style.
- And you can install several templates with several styles.
- So, the message is correct if you try to delete the last style of a template.

Should Joomla first check if all installed templates have just one style and then hide the Delete button? I think that would be a bit too much.

**Comment by Scrabble96** [comment]
Ok. Thanks, @ReLater regarding STYLES. 

The message breadcrumb, however, is still wrong as to delete a template you no longer go through 
Extensions-> Manage-> Manage-> Select template but via 
System-> Manage-> Extensions-> Select template, 
so that does need changing.

**Comment by Scrabble96** [comment]
I have searched and searched the administrator language files in the code here on github but I cannot find where this text is stored so that I can fork it and suggest a correction as these instructions are for Joomla! 3x not 4x:

![image](https://user-images.githubusercontent.com/36987494/50989070-4ac62f00-1506-11e9-85a7-2aa7bfa5c9c1.png)

**Comment by ReLater** [comment]
First select the right branch. Then navigate to administrator/language/en-GB/en-GB.com_templates.ini
![11-01-_2019_02-48-06](https://user-images.githubusercontent.com/20780646/51008334-a8309f00-154b-11e9-8f37-19be8dac56e7.jpg)

**Comment by Scrabble96** [comment]
Thank you, @ReLater 
That's what I did yesterday, but for some reason (I was probably too tired and should have left it until today), I couldn't see the administrator/language/en-GB/en-GB.com_templates.ini file. Today I can.
