### ISSUE TITLE
Isis has no section content/row-fluid closing div

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#23428]
### Steps to reproduce the issue

The issue is not detected by browsers. It is an Html error with no visible effects, but the resulting Html is invalid.

### Additional comments

Just in case, I'm submitting the fix to have a valid Html

**Comment by Quy** [comment]
It is not necessary to create an issue if you have a pull request for it. Just provide the details in the PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23428">issues.joomla.org/tracker/joomla-cms/23428</a>.</sub>
