### ISSUE TITLE
500 error SQL syntax when clicking Menu and Menu items in administration?

### ISSUE THREAD

**Issue by Chacapamac** [joomla/joomla-cms#23437]
### Steps to reproduce the issue

Clicking “All Menu items” or “Main Menu (fr-FR)” or Main Menu (en-GB)” or Main Menu

### Expected result
Showing item in Joomla administration

### Actual result

Error 500
<<
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`published`,`a`.`component_id`,`a`.`checked_out`,`a`.`checked_out_time`,`a`.`br' at line 1 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`published`,`a`.`component_id`,`a`.`checked_out`,`a`.`checked_out_time`,`a`.`br' at line 1 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`published`,`a`.`component_id`,`a`.`checked_out`,`a`.`checked_out_time`,`a`.`br' at line 1
>>

### System information (as much as possible)

Joomla! 4.0.0-alpha6-dev on Mamp - PHP 7.2.1

### Additional comments

I will try reinstall, this is the nighty build from 2 or 3 weeks already.
Maybe the fact that I use a multilingual example have something to do with it.

**Comment by Quy** [comment]
Already fixed in nightly build from a week ago. Please reinstall with a recent nightly build.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23437">issues.joomla.org/tracker/joomla-cms/23437</a>.</sub>

**Comment by Chacapamac** [comment]
Yep Fixed, I just try, work perfectly<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23437">issues.joomla.org/tracker/joomla-cms/23437</a>.</sub>
