### ISSUE TITLE
[4.0] [RFC] Should we add json extension to setting Valid Source Formats of template manager

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#23439]
### Steps to reproduce the issue
- 4.0 nightly build.
- Go to `administrator/index.php?option=com_templates&view=templates`
- Click on "Cassiopeia Details and Files"
- See file list on the left:
File `joomla.asset.json` is missing.

- Shall we add json to https://github.com/joomla/joomla-cms/blob/4.0.0-alpha6/administrator/components/com_templates/config.xml#L45 ?

- Users can configure allowed souce formats via administrator/index.php?option=com_config&view=component&component=com_templates , too, but maybe a little bit more user friendly if...

**Comment by astridx** [comment]
My comment. I think we should change the `config.xml` as @ReLater ReLater has suggested. I think that's just been forgotten here: https://github.com/joomla/joomla-cms/pull/22435

**Comment by ReLater** [comment]
See pr https://github.com/joomla/joomla-cms/pull/23469
