### ISSUE TITLE
Showon not working on subform until after article is saved

### ISSUE THREAD

**Issue by design-innovations** [joomla/joomla-cms#23430]
### Steps to reproduce the issue
1.) Create subform
2.) My code in subform:
```
<field name="multiple_media" type="radio" default="no" label="Is there more than 1 image or video in this group?" description="Toggle for additional figure content." class="btn-group">
		<option value="yes">Yes</option>
		<option value="no">No</option>
	</field>
```
3.) Add field(s) with showon. My code is:
`<field name="media-image" type="media" showon="media_type:image" label="Image" directory="" preview="true" preview_height="150" />`

### Expected result
Fields with showon should show up immediately when option is chosen. It only shows if I save the article after the subform has been created and can be toggled on and off once it is saved.

### Actual result
Fields with showon do not display until after the article is saved.

### System information (as much as possible)
- Mac with MAMP Pro
- Joomla 3.9.1
- PHP 5.6.37

**Comment by design-innovations** [comment]
It seems the issue is coming from an issue in the custom fields I'm loading. This can be closed.

**Comment by richard67** [comment]
@learncss You can close it yourself, there should be a button for doing that.
