### ISSUE TITLE
[4.0] Cannot add module class to language switcher module?

### ISSUE THREAD

**Issue by Chacapamac** [joomla/joomla-cms#23447]
### Steps to reproduce the issue

Add class name to language switcher in Joomla administration

### Expected result

Class name added to container element

### Actual result

No class name added

### System information (as much as possible)

Joomla_4.0.0-alpha7 (3 days ago)

### Additional comments

Curiously seem to work with other modules ???

**Comment by infograf768** [comment]
<img width="542" alt="screen shot 2019-01-04 at 17 07 32" src="https://user-images.githubusercontent.com/869724/50697714-5071cf80-1043-11e9-960e-f87bc36c38c2.png">


It is added to the container <div>
<img width="481" alt="screen shot 2019-01-04 at 17 04 55" src="https://user-images.githubusercontent.com/869724/50697605-fa049100-1042-11e9-94cc-4c90d8481832.png">

**Comment by Chacapamac** [comment]
Thanks Infograf768

With your help, I find the problem

I put my switcher in a new added position

`<?php if ($this->countModules('top-tools')) : ?>
			<div class="grid-child container-top-tools">
				<jdoc:include type="modules" name="top-tools" style="none" />
			</div>
			<?php endif; ?>`

If I change the module “style” for “default” or “xhtml”, my module class is added
`<?php if ($this->countModules('top-tools')) : ?>
			<div class="grid-child container-top-tools">
				<jdoc:include type="modules" name="top-tools" style="xhtml" />
			</div>
			<?php endif; ?>`

`style="none" />`
• No custom added class work in the module administration if “none”

• Also, if “none”, no div moduletable is added

Is this normal ?

**Comment by brianteeman** [comment]
> Is this normal ?

yes and it is the same in joomla3

**Comment by infograf768** [comment]
In 3.x for me it is a bug.
`$params->get('moduleclass_sfx')` is never fetched.
Therefore
`<div class="mod-languages<?php echo $moduleclass_sfx; ?>">`
gives nothing.
Trying now to find why.

**Comment by brianteeman** [comment]
See https://github.com/joomla/joomla-cms/blob/25564d884892bd52f2f9a67d57b911e8ee501e5e/templates/system/html/modules.php#L15

It is by design and has been that way forever

**Comment by infograf768** [comment]
The fact that it has been like that forever does not mean it is ok.
Let's rather find how to solve this as it happens also when choosing html5 as style.

**Comment by infograf768** [comment]
I mean in 3.x

**Comment by infograf768** [comment]
In fact, the problem comes from a confusion for $params in `ModLanguagesHelper::getList($params);`

There, `$params` is not added to the module params but replaced by the plugin params.

**Comment by infograf768** [comment]
If I modify the helper (still in 3.x), I get (after adding `switcherclass` in the module as `moduleclass_sfx`):

<img width="453" alt="screen shot 2019-01-05 at 11 29 57" src="https://user-images.githubusercontent.com/869724/50723389-55835d00-10dd-11e9-85c2-505736a6bb5a.png">

**Comment by infograf768** [comment]
Will make patch for 3.x as the change is simple.
Would it be B/C is to be decided.
EDIT: The helper has been modified in last staging and the issue is no more present there.
:)

**Comment by infograf768** [comment]
Therefore I apologize:

> Also, if “none”, no div moduletable is added
> Is this normal ?

Yes it is. Closing as expected behavior.

**Comment by Chacapamac** [comment]
Cool!
