### ISSUE TITLE
Why is a suffix added to css and js files in J4?

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#23442]
### Is your feature request related to a problem? Please describe.
Using both Firefox and Chrome inspectors, both the css and js files have suffixes added to them, e.g:
joomla.com/templates/cassiopeia/css/template.min.css?5f557ff33c0d15ac212520025cf14ad5 and
joomla.com/templates/cassiopeia/css/user.css?5f557ff33c0d15ac212520025cf14ad5
/media/legacy/js/jquery-noconflict.min.js?5f557ff33c0d15ac212520025cf14ad5
### Describe the solution you'd like
No suffixes:
joomla.com/templates/cassiopeia/css/template.min.css
joomla.com/templates/cassiopeia/css/user.css
/media/legacy/js/jquery-noconflict.min.js

### Additional context
Viewing site on CloudAccess.net hosted site

**Comment by richard67** [comment]
The suffixes are added for versioning: when a css or ja file has changed, browsers will still use the old version from cache if no such suffix. With the changed suffix after the file has been changed, the browser will not use the old cached file.

**Comment by Bakual** [comment]
That's not new to J4 either. The feature exists already in J3 and is widely used.
I'm closing this as expected behavior.
