### ISSUE TITLE
J4.0 - module positions partially hidden by publishing calendars

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#23449]
### Steps to reproduce the issue
Open existing or create a new module
Click the drop-down arrow to display module positions

### Expected result
This should hide the Start Publishing and Finish Publishing calendars

### Actual result
The calendars sit on top of the module positions list. See screenshot below.
![image](https://user-images.githubusercontent.com/36987494/50702293-6b930e00-1048-11e9-8c24-e13d97ce40a9.png)

### System information (as much as possible)
J4.0 Alpha 7 dev

**Comment by infograf768** [comment]
Known issue.
See https://github.com/joomla/joomla-cms/pull/23415
and https://github.com/joomla/joomla-cms/pull/22263#issuecomment-448137042

**Comment by Scrabble96** [comment]
Ok, thanks, @infograf768 
I did try to look for already open/closed issues, but as I couldn't find anything with 'calendar' or 'module positions' in the subject it wasn't possible (for me, anyway).

**Comment by ghost** [comment]
@Scrabble96 please close this Issue as its a known one, thanks.
