### ISSUE TITLE
J4.0 - resizing screen makes module positions menu disappear

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#23448]
### Steps to reproduce the issue
Start a new module - in this case a Custom module.
Resize browser screen from full size (on desktop) to about half screen width
Click the Position drop-down arrow

### Expected result
To see a list of template positions

### Actual result
Drop-down menu shows only two items: 
"Type or select some...
No results match"

See screenshot:
![image](https://user-images.githubusercontent.com/36987494/50701686-72208600-1046-11e9-83eb-c2d968b17f3d.png)

### System information (as much as possible)
Happens on both Firefox and Chrome
On CloudAccess.net joomla.com website

**Comment by infograf768** [comment]
Confirmed, independent of the https://github.com/joomla/joomla-cms/pull/23289 merge.

This is due to https://github.com/joomla/joomla-cms/pull/22263
When resizing, only way to get the dropdown correctly is to reload the page and therefore these js.

@Fedik

**Comment by Fedik** [comment]
Yeah, that a :bug:  with CE for the dropdown made in #22263.
Happened because `tabs.js` moving things around in DOM tree, on resize.

**Comment by Fedik** [comment]
please test #23455

**Comment by infograf768** [comment]
Test https://github.com/joomla/joomla-cms/pull/25676
