### ISSUE TITLE
J4 Welcome message displayed for guest on front end

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#23441]
### Steps to reproduce the issue
Added code to cassiopeia index.php to display welcome message if anyone other than guest is logged in:

```
	<?php if ($user->guest !=1) : ?>       
	   <div class="container-fluid">
		  <p class="floatleft">
                    <?php echo 'Welcome, ' . $user->name; ?>
	          </p>
		</div>
	<?php endif; ?>

```

### Expected result
No message when viewing website as casual viewer

### Actual result
Welcome,

### System information (as much as possible)
J4.0 Alpha 7 nightly build from a few days ago on CloudAccess.net Joomla site.

### Additional comments
Original code which works correctly on Joomla! 3.9.1 site which has the same error in J.4.0 as the code above:

```
	<?php if ($user->guest !=1) { ?>       
	   <div class="container-fluid">
		  <p class="floatleft">
                    <?php echo 'Welcome, ' . $user->name; ?>
                  </p>
		</div>
    <?php } ?>

```

**Comment by Bakual** [comment]
Where exactly do you want that code change? In the login module?
Imho, that one already has an option to enable such a greeting which only applies when someone is logged in.

**Comment by infograf768** [comment]
The code posted above, btw, does not exist in 3.9.x core.

**Comment by Scrabble96** [comment]
Thanks, @Bakual 
I couldn't find it in the index.php (which is where it is in my current J3x template, created by me). I'll set up a front-end user later then log in to see what happens and where the welcome message is displayed.

**Comment by infograf768** [comment]
The code we use in core is in the module and will display only when a user has logged in:
```
<?php if ($params->get('greeting', 1)) : ?>
	<div class="login-greeting">
	<?php if (!$params->get('name', 0)) : ?>
		<?php echo JText::sprintf('MOD_LOGIN_HINAME', htmlspecialchars($user->get('name'), ENT_COMPAT, 'UTF-8')); ?>
	<?php else : ?>
		<?php echo JText::sprintf('MOD_LOGIN_HINAME', htmlspecialchars($user->get('username'), ENT_COMPAT, 'UTF-8')); ?>
	<?php endif; ?>
	</div>
<?php endif; ?>
```

**Comment by Bakual** [comment]
For reference where the code from JMS is:
https://github.com/joomla/joomla-cms/blob/56affaf39af8a8811b96f789c40b4c9cfd024dad/modules/mod_login/tmpl/default_logout.php#L19-L27

I'm closing this issue as it's not about core. If you need assistance to adjust your own template, feel free to ask in the forums.

**Comment by Scrabble96** [comment]
Thank you both @infograf768 and @Bakual
