### ISSUE TITLE
Korean translation for mod_whosonline

### ISSUE THREAD

**Issue by thalueng** [joomla/joomla-cms#23440]
MOD_WHOSONLINE_WE_HAVE is missing the 's' for '%2$s'
Language string version 3.8.9.1 on Joomla 3.9.1

**Comment by infograf768** [comment]
Forwarding to Korean Translation Team.
Closing as not a Joomla bug.

**Comment by infograf768** [comment]
In the mean while I suggest you create an override for that string.

**Comment by Bakual** [comment]
As that file is part of the korean language pack, you need to contact the korean translation team (see https://community.joomla.org/translations/joomla-3-translations.html#ko-kr).

**Comment by Bakual** [comment]
Ah, JM was faster 👍
