### ISSUE TITLE
Add a space caracter

### ISSUE THREAD

**Issue by ZerooCool** [joomla/joomla-cms#23453]
### Steps to reproduce the issue
Edit a article.

### Expected result
ICON Sauvegarder ICON Version ICON Annuler

### Actual result
ICON Sauvegarder **ICONVersion** ICON Annuler

### System information (as much as possible)
Joomla stable.

**Comment by PhilETaylor** [comment]
Save someone else googling: 
`Sauvegarder` = Save 
`Annuler` = Cancel

So I'm GUESSING that `Version` = Versions button on the edit content page...

**Comment by infograf768** [comment]
@ZerooCool 
I guess this is in frontend.
Which template are you using?
Please post a screenshot of the page.

Here with Protostar, all is fine (and not in the same order)
<img width="444" alt="screen shot 2019-01-05 at 07 50 10" src="https://user-images.githubusercontent.com/869724/50721365-9a4bcb80-10be-11e9-933b-b05d8b6c8fd3.png">
:

**Comment by ZerooCool** [comment]
Hello, thank you for the answer.
I was not sure, but since it's front-end, it certainly comes from the template, out, I do not use the default template Joomla.

I thought to do well by going back here this detail, but, apparently, it is to the developer of the template that I had to address myself.

https://www.astemplates.com/joomla-template-details/873-et-conference
( Free version )

**Comment by Quy** [comment]
Not a Joomla core issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23453">issues.joomla.org/tracker/joomla-cms/23453</a>.</sub>
