### ISSUE TITLE
“loadmodule“ editor button not showing in custom html module?

### ISSUE THREAD

**Issue by Chacapamac** [joomla/joomla-cms#23456]
### Steps to reproduce the issue

Go to editor in a custom html module

### Expected result

Have the CMS Content > Module button 

### Actual result

Nothing

### Additional comments

**Suggestion:**
**1—** Wy the Naming “CMS Content” — Should be Joomla content
You should keep the branding.

**2—** In module, the insert module button should turn on the “Prepare Content” options or warning??

**Comment by SharkyKZ** [comment]
This is intentional.

**Comment by Chacapamac** [comment]
Sometime you need to insert modules inside Custom html modules.

**Comment by ghost** [comment]
any Comment by Maintainers?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23456">issues.joomla.org/tracker/joomla-cms/23456</a>.</sub>

**Comment by ghost** [comment]
@HLeithner can you please comment?

**Comment by HLeithner** [comment]
that could cause an endless loop so, I think it is not so easy to solve. Also I'm not sure if this is really the way to go.

If you really need this you need to write a layout override and load the modules there.
