### ISSUE TITLE
[4.0] 100px padding is causing module position names list to wrap on medium-width screens

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#23451]
### Steps to reproduce the issue
Open existing or create new module.
Resize (desktop) screen to about half width but so that position list is still to the right of the editor, not below.
Click the Position drop-down menu to view list of module positions

### Expected result
Readable module positions

### Actual result
Difficult-to-read module positions due to 100px right padding after module position name with a min-width set at 640px, which is too narrow and possibly not necessary.

![image](https://user-images.githubusercontent.com/36987494/50703131-14426d00-104b-11e9-8343-5acaa3e7afbf.png)

### System information (as much as possible)
Viewing on J4.0 Alpha 7-dev
The browser inspector says it's in a file called /media/vendor/choicesjs/css/choices.min.css.
I have found choices.css in the site folders and the code in question is on line 260:
```
@media (min-width: 640px) {
  .choices__list--dropdown .choices__item--selectable {
    padding-right: 100px;
  }

```
Changing the padding to 10px makes the module names readable again but the "Press to select" text (data-select-text) now overlaps the module name:

![image](https://user-images.githubusercontent.com/36987494/50704366-042c8c80-104f-11e9-81a3-ce861691e8db.png)

### Additional comments
I'm afraid that suggesting a code change to make the data-select-text wrap below the module name is beyond me, but is this text really necessary? What else would you do to select a position? You don't say "Press to select" on other menus (as far as I've noticed).

**Comment by hardik-codes** [comment]
I think the same in this regard that we don't say "Press to select" on menus. @Scrabble96 I think I should go about solving the above thing and also excluding the "Press on select".

**Comment by ghost** [comment]
closed as having Pull Request #23706

**Comment by Scrabble96** [comment]
There is a similar function in articles when choosing categories, but this displays correctly. I would suggest that the CSS code used for displaying the category options is copied over to the module position display.

However, my success rate with raising PRs is practically nil, so I would appreciate someone with experience doing this, please. Thank you.

**Comment by brianteeman** [comment]
This is just waiting on an update from the choices js script. The fix has been merged and hopefully it will be merged soon

**Comment by ciar4n** [comment]
PR created.. #28658
