### ISSUE TITLE
Filter by Categories Levels not working on Featured Articles View

### ISSUE THREAD

**Issue by carlitorweb** [joomla/joomla-cms#23450]
### Steps to reproduce the issue

- Go to Content -> Categories
- Create a subcategory. For example:
**Parent Category
____ Children Category**
----------------------------------------------
- Go to Content -> Articles 
- Create an article as Featured and assign it to the category "Children Category"
----------------------------------------------
- Go to Content -> Featured Articles
- Filter by Category "Parent Category" and Filter by Max Levels "2" (Can be at any level)
----------------------------------------------

### Expected result
The article assigned to the category "Children Category" is listed.

### Actual result
The article assigned to the category "Children Category" is not listed.

### System information (as much as possible)
Joomla 3.9.1

**Comment by Quy** [comment]
Please test PR #23454<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23450">issues.joomla.org/tracker/joomla-cms/23450</a>.</sub>
