### ISSUE TITLE
[4.0] Admin template atum does not have pagination footer

### ISSUE THREAD

**Issue by DonaldTrump88** [joomla/joomla-cms#23466]
### What needs to be fixed
Pagination::getListFooter looks for footer at following location 
administrator/templates/atum/html/pagination.php

It has been not added. 

### Why this should be fixed
Pagination footer does not get displayed.

### How would you fix it
Add pagination

### Side Effects expected
Not sure

Build: 06 Jan 2019 nightly build

**Comment by ElephantInTheRoomFirst** [comment]
It looks like deprecated. Should it be added or the deprecation code should be removed?

**Comment by chmst** [comment]
The panination footer is displayed in my application. 
Which list-limit do you have in your configuration? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23466">issues.joomla.org/tracker/joomla-cms/23466</a>.</sub>

**Comment by ghost** [comment]
@Ninja-007 can you please Comment?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23466">issues.joomla.org/tracker/joomla-cms/23466</a>.</sub>

**Comment by ElephantInTheRoomFirst** [comment]
I am not using the code now. If you want you may close it now,

**Comment by ghost** [comment]
closed as stated above, thanks @Ninja-007 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23466">issues.joomla.org/tracker/joomla-cms/23466</a>.</sub>
