### ISSUE TITLE
[4.0] Default menu failed to load when allowed for under to registered ACL

### ISSUE THREAD

**Issue by DonaldTrump88** [joomla/joomla-cms#23462]
### Steps to reproduce the issue
1. Create a site menu for registered group
2. Add one menu item for registered group and set it default.
3. Now load the website from frontend.
4. The website does not load. Browser shows error, too many redirections.
5. Sometimes, it does load login page. 

### Expected result
The browser error message is not friendly. Although I understand that Joomla needs to redirect to login page. 
Eiither website should show a friendly error message while redirecting to avoid the browser error or show login promptly without error.

### Actual result
Error message

### System information (as much as possible)
Joomla! 4 alpha , nightly build 06 Jan 2019

**Comment by ElephantInTheRoomFirst** [comment]
Note that this annoyance type of problem and has low priority. Close it if not found useful.

**Comment by infograf768** [comment]
Confirmed.
We get an url of the type
`index.php/component/users/login?Itemid=101`

A simple solution is to create a new menu containing a Login menu item set to Public. One does not even need a module.

**Comment by ElephantInTheRoomFirst** [comment]
Thanks. I fixed the issue by creating public login page. It was mere nuisance for some time.
