### ISSUE TITLE
[4.0] Workflow change default

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#23465]
### Steps to reproduce the issue
Create a new workflow and save
From the list of workflows click on the featured icon to set the new workflow as the default
Now try to make the original workflow the default by clicking on the featured icon

### Expected result
All workflows can be set as default by clicking on the featured icon

### Actual result
The original workflow can not be set as default (again) by clicking on the featured icon - only by using the default button in the toolbar

**Comment by Quy** [comment]
Please test PR #23607<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23465">issues.joomla.org/tracker/joomla-cms/23465</a>.</sub>
