### ISSUE TITLE
[4.0] Workflow default

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#23464]
### Steps to reproduce the issue
Clean install
Create a new workflow called "new"
Set the new workflow to be the default
Create a new article (in the only existing category "uncategorised")

### Expected result
Article will use the default workflow

### Actual result
Article is still using the original workflow "Joomla Default"

### Additional comments
This is because the "uncategorised" category is created with during installation with a workflow set to "Joomla Default"
It should be set as "Use Default"

**Comment by hardik-codes** [comment]
@brianteeman in which file are the proposed changes to be made ?

**Comment by brianteeman** [comment]
See #23701
