### ISSUE TITLE
The button module 'mod_search' don't appears

### ISSUE THREAD

**Issue by ZerooCool** [joomla/joomla-cms#23468]
### Steps to reproduce the issue
You can see my Beta Website : https://www.visionduweb.fr/forum
Template "ET conference"

Module mod_search is off cannvas ( Clic the right menu mobile icône )
I can see only the input.

With Extensions/module from administrator, i have configure 'mod_search' and i say yes, to use button for search.
Button to the right or to the left position, it's the same, i can't see this button.

### Expected result
A button for 'mod_search' 

### Actual result
Don't have the button for 'mod_search' 

### System information (as much as possible)
Joomla stable
PHP 7.2
Apache 2.4

### Additional comments
Template "ET conference"
It's a problem with the template, or, a Joomla core problem ?

**Comment by chmst** [comment]
I think it is the template. It is the mod_finder? If yes, go to the template manager, click on your template. 
Open the directory html and see if there is a file mod_finder.  
It seems that the button is not displayed a t all.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23468">issues.joomla.org/tracker/joomla-cms/23468</a>.</sub>

**Comment by ZerooCool** [comment]
I would have thought of mod_search that I see present in the template, when I click on extensions / template / template to create a substitution (which I do not do.)

I do not see mod_finder actually.

Can you give me your opinion, on the following address of my site? The hidden menu is called with the small icon at the top right and allows you to start a search.

https://www.visionduweb.fr

**Comment by Quy** [comment]
This is not producible with the core Protostar template, therefore, it must be with your template. Please consult with this template provider for assistance.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23468">issues.joomla.org/tracker/joomla-cms/23468</a>.</sub>
