### ISSUE TITLE
Autochange link: adding "administrator" segment

### ISSUE THREAD

**Issue by xakepok** [joomla/joomla-cms#23476]
### Steps to reproduce the issue
* Add new module "Html code" in Admin panel (cpanel position)
* Add any link on front-end site: http://example.com/show-content
* Save and close, go to cpanel position

### Expected result
Link http://example.com/show-content

### Actual result
Link is http://example.com/administrator/show-content

### System information (as much as possible)
Version 3.9.1

**Comment by infograf768** [comment]
This will happen when using TinyMCE as the link is changed to be relative.
If you use CodeMirror or no editor, it will work fine.
Example:
<img width="874" alt="screen shot 2019-01-09 at 10 20 49" src="https://user-images.githubusercontent.com/869724/50889442-46abeb80-13f8-11e9-88c8-555c315d439e.png">

**Comment by infograf768** [comment]
Looks like we do have a bug though as, when setting tinyMCE to use absolute URLs, it still keeps it relative. Looking into this.

**Comment by infograf768** [comment]
Also, try setting TnyMCE to use Absolute URLs
<img width="426" alt="screen shot 2019-01-09 at 10 25 43" src="https://user-images.githubusercontent.com/869724/50892391-ac02db00-13fe-11e9-8b8b-b5821085d89b.png">

**Comment by infograf768** [comment]
The most important problem is that the xtd-editors plugin are still displayed when `relative_urls` is set to true (except for `Image` which works fine.

**Comment by xakepok** [comment]
> Also, try setting TnyMCE to use Absolute URLs
> <img alt="screen shot 2019-01-09 at 10 25 43" width="426" src="https://user-images.githubusercontent.com/869724/50892391-ac02db00-13fe-11e9-8b8b-b5821085d89b.png">

Thanks! it's worked! But i think, relative URLs must take into account the location of the module.

**Comment by infograf768** [comment]
Also don't forget that once you set URLs to `Absolute`, it will also behave this way for all urls entered in the textarea everywhere TinyMCE is used. Not a good idea if your site is moved.

> But i think, relative URLs must take into account the location of the module.

There is no way to know beforehand if the URL targets admin or site.

**Comment by ghost** [comment]
closed as Issue seems to be resolved; if not sorry and reopen it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23476">issues.joomla.org/tracker/joomla-cms/23476</a>.</sub>
