### ISSUE TITLE
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

### ISSUE THREAD

**Issue by AugPin** [joomla/joomla-cms#23474]
### Steps to reproduce the issue

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/clients/7cc97be8e3439b5c67521867a6d4f5ed/web/040-ALPHA/plugins/system/debug/debug.php on line 590

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/clients/7cc97be8e3439b5c67521867a6d4f5ed/web/040-ALPHA/plugins/system/debug/debug.php on line 611

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/clients/7cc97be8e3439b5c67521867a6d4f5ed/web/040-ALPHA/plugins/system/debug/debug.php on line 617

### System information (as much as possible)

Setting | Value
-- | --
 
Linux h2web15 4.9.0-0.bpo.5-amd64 #1 SMP Debian 4.9.65-3+deb9u2~bpo8+1 (2017-01-05) x86_64
mysql
5.7.19-log
utf8_general_ci
utf8_general_ci
7.3.0
Apache
fpm-fcgi
Joomla! 4.0.0-alpha5 Alpha [ Amani ] 4-November-2018 23:23 GMT
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by ReLater** [comment]
> Joomla! 4.0.0-alpha5 Alpha [ Amani ] 4-November-2018 23:23 GMT

This is fixed already. You're using an outdated Joomla release. For testing purposes use current nightly builds https://developer.joomla.org/nightly-builds.html or at least the last official J4 release https://github.com/joomla/joomla-cms/releases
