### ISSUE TITLE
Joomla 4 Template copy

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#23483]
### Steps to reproduce the issue
In Administration Make a copy of the Casseiopeia Template

### Expected result
All the files of the Template are copied

### Actual result
joomla.asset.json and offline.php are not copied

**Comment by SharkyKZ** [comment]
Test PR #23484 please.

**Comment by infograf768** [comment]
Closing as we have https://github.com/joomla/joomla-cms/pull/23484
