### ISSUE TITLE
WCAG: Autum alert colors are too similar for Color-Blind Users

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#23480]
### Steps to reproduce the issue

I've been processing new extensions with [JED Checker](https://extensions.joomla.org/extension/jedchecker/ "JED Checker") for Joomla 4, and I have noticed that the Alert colors are difficult to differentiate for Color-Blind Users.

These are the Autum colors vs the original Bootstrap 4 colors:

Alert Class | Autum  | Bootstrap 4
------------- |------------- | -------------
Font Success    |`#18411a` | `#155724`
Font Info       |`#08434c` | `#004085`
Font Warning    |`#5d2e00` | `#856404`
Font Danger     |`#661514` | `#721c24`
Background Success  |`#d5e5d6` | `#d4edda`
Background Info     |`#cfe6e9` | `#cce5ff`
Background Warning  |`#f0decc` | `#fff3cd`
Background Danger   |`#f3d4d4` | `#f8d7da`

This is the sample page: https://blog.anibalhsanchez.com/media/Color-Blind/JED-checker-Test-J4-Administration.html

You can check the colors here: https://www.color-blindness.com/coblis-color-blindness-simulator/

#### References

_By some estimates, up to 10% of the male population of the world suffers from some form of color blindness. The most common being Protanopia, or Red-Green color blindness, the inability to distinguish between red and green hues._

* *Accessibility Basics: Testing Your Page For Color Blindness*
https://css-tricks.com/accessibility-basics-testing-your-page-for-color-blindness/
* *Improving The Color Accessibility For Color-Blind Users*  https://www.smashingmagazine.com/2016/06/improving-color-accessibility-for-color-blind-users/
* **Web Accessibility Guidelines v1.0 - Contrast & Color** Find colors that provide maximum contrast, including enough contrast between content and the background, so that text and non-decorative images are legible for anyone with low vision or color deficiencies. http://web-accessibility.carnegiemuseums.org/design/color/

### Expected result

Autum Colors aligned with WCAG guidelines for Color-Blind Users.

### Actual result

Current colors can't be easily differentiated.

Please, check the screenshots.

**Comment by anibalsanchez** [comment]
## Current Colors

![Current Color Palette](https://blog.anibalhsanchez.com/media/Color-Blind/alert-colors.png)

## Greyscale Comparison

![Greyscale Comparison](https://blog.anibalhsanchez.com/media/Color-Blind/alert-colors-bw.png)

## Dichromatic view: Red-Blind/Protanopia

![Dichromatic view: Red-Blind/Protanopia](https://blog.anibalhsanchez.com/media/Color-Blind/Red-Blind_Protanopia.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23480">issues.joomla.org/tracker/joomla-cms/23480</a>.</sub>

**Comment by anibalsanchez** [comment]
Just for fun, you can test if you are Color-Blind here: https://enchroma.com/pages/test

**Comment by brianteeman** [comment]
A quick check of the WCAG color contrast checker doesn't show a problem with the one I checked (success)

![image](https://user-images.githubusercontent.com/1296369/50839992-6e984200-1359-11e9-9384-6e3e982d4d81.png)

**Comment by brianteeman** [comment]
and this is the "danger"

https://webaim.org/resources/contrastchecker/?fcolor=661514&bcolor=F3D4D4

![image](https://user-images.githubusercontent.com/1296369/50840058-94254b80-1359-11e9-983c-bdef4c3d41a3.png)

**Comment by anibalsanchez** [comment]
The overall contrast is not the problem. It is how similar the colors are for a color-blind user.

**Comment by mbabker** [comment]
Color should not be used as the sole indicator for message severity, and personally I wouldn't try to find a color palette that creates enough shades of gray to be visually different.

**Comment by brianteeman** [comment]
> The overall contrast is not the problem. It is how similar the colors are for a color-blind user.

Your post says that it is about the contrast - that is the only thing that WCAG is concerned with

> Color should not be used as the sole indicator for message severity,

Exactly although my pr that addressed that was closed

**Comment by anibalsanchez** [comment]
The contrast works in different ways for each viewer. So, yes, the first check is about the contrast between foreground and background. The content is legible. In a second analysis, I'm trying to express that these colors don't communicate for color-blind users the original intention.

Yes, icons can help to communicate the same intention.

In any case, the template is still in the works and it has not been a11y checked. So, you can close the issue if it can't be addressed now.

**Comment by brianteeman** [comment]
yes sadly a huge amount of time and effort to make the template accessible has been thrown away

**Comment by rdeutz** [comment]
We will look into it when it is time to do so

**Comment by Thomsterdam** [comment]
I second Anibal's issue. For a colourblind man (officially: a man with "color vision deficiency" = CVD) like me, the colours of the buttons are not distinctive enough: they seem to blend to similar colours. 
I tested this on a site, together with my (female) neighbour, who is not colourblind. We used this page: https://www.color-blindness.com/coblis-color-blindness-simulator/ which enables the rest of the Joomla users to see the colours a colourblind person sees. 

The top picture is what I took from Joomla 4 alpha 7 back end.
![joomla4buttons](https://user-images.githubusercontent.com/8308385/51629825-da2d0280-1f48-11e9-94e6-fac88756707b.png)
The second and third show what a colourblind person sees, depending on the type of colourblindness s/he is affected by: 
First "Green-Weak/Deuteranomaly" CVD
![green-weak-deuteranomaly](https://user-images.githubusercontent.com/8308385/51629927-1b251700-1f49-11e9-9990-5354a5356244.png)
Secondly "Red-Blind/Protanopia" CVD 
![red-blind-protanopia](https://user-images.githubusercontent.com/8308385/51629942-2415e880-1f49-11e9-887f-32bd32622b80.png)
You will understand the buttons are not workable for a man with CVD (I say man, because this is the type of colourblindness that affects only men: **8 percent of the male population**)
A solution could be either a change of the colour scheme, or a setting under "options" that would make Joomla 4 acceptable for colourblind people.

**Comment by anibalsanchez** [comment]
@Thomsterdam The conclusion of this ticket was that the current template is going to be replaced with a new version. This new template is still in the works and not even checked for accessibility. 

FYI: https://volunteers.joomla.org/teams/j4-backend-template-working-group/reports/926-team-setup

**Comment by brianteeman** [comment]
I doubt that will make any difference as the current template IS compliant with the WCAG guidelines. 

You can read them here https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-without-color.html

**Comment by brianteeman** [comment]
There are three visual indicators - colour, icon and text 
Two of those are independent of colour so it satisfies WCAG

I agree that in your Protanopia simulation the colours are very similar and we could play around t adjust the colours to make the simulator show it as more different. BUT and an important BUT. Every individual is different and we can never have a set of colours that would satisfy everyone
