### ISSUE TITLE
.body .container - moves 15px to the left if article.height > inner.screen.height

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#23482]
### Steps to reproduce the issue
0. occurs in all delivered standard templates - beez3, vmbeez3, protostar
1. a. content->articles->new article - options don't matter
      type a few lines and/or insert an image not higher than inner.screen.hight
   b. content->articles->new article - options don't matter
      type 100 lines and/or insert an image !higher! than inner.screen.hight
   c. add corresponding menus

### Expected result
if you click through the menu items the -> .body .container ->  leaves unchainged

### Actual result
if you click through the menu items the -> .body .container ->  changes position to the left 15px depending on article height > inner.screen.height

### System information (as much as possible)
Windows7 x64 -- IIS7.5 -- Php7.2 -- MySQL8.0.13x64 command-line --

### Additional comments
it depends on 
.row-fluid .span9 {
		width: 74.468085099%;
		*width: 74.414893609638%;
		/* height:3000px; added Bangert*/

**Comment by ciar4n** [comment]
Shift in viewport due to scrollbar? If so then this would be expected behaviour.

**Comment by ghost** [comment]
Yes you are right - I set - html { overflow-y:scroll; } to avoid that shift.

**Comment by ciar4n** [comment]
@AxelBangert Thank you for the update.

This issue can be closed.
