### ISSUE TITLE
[4.0] Nightly alpha7. AJAX error during update with nightly build of today

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#23490]
### Steps to reproduce the issue
- I have installed a nightly build Joomla_4.0.0-alpha7-dev-Development-Full_Package.zip some days ago.
- I made an update today with nightlies "Wednesday, 09 January 2019 03:00:34 UTC".
- Via Upload & Update.
- Progress bar stops after a while with error:
```
ERROR:
Invalid AJAX data:
Fatal error:  Uncaught Error: Class 'Joomla\CMS\Filesystem\AKFactory' not found in administrator/components/com_joomlaupdate/restore_finalisation.php:124
Stack trace:
#0 administrator/components/com_admin/script.php(3953): Joomla\CMS\Filesystem\File::delete('/www/htdocs/w00...')
#1 administrator/components/com_joomlaupdate/restore_finalisation.php(75): JoomlaInstallerScript->deleteUnexistingFiles()
#2 administrator/components/com_joomlaupdate/restore.php(8335): finalizeRestore('/www/htdocs/w00...', '/www/htdocs/w00...')
#3 {main}
  thrown in administrator/components/com_joomlaupdate/restore_finalisation.php on line 124
```

**Comment by ChristineWk** [comment]
I had similar the same:
I made an update with nightlies on Monday, 07 January 2019.
Via Upload & Update.
But: Progress bar showed 100% extracted files with the same error as @ReLater mentioned above. "Klick" on OK didn't help.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23490">issues.joomla.org/tracker/joomla-cms/23490</a>.</sub>

**Comment by ghazal** [comment]
Issue confirmed as of today's nightly, ie -> Thursday, 10 January 2019<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23490">issues.joomla.org/tracker/joomla-cms/23490</a>.</sub>

**Comment by ElephantInTheRoomFirst** [comment]
+1

**Comment by ReLater** [comment]
I haven't tested https://github.com/joomla/joomla-cms/pull/23506 yet. But it should solve this issue as far as I see. Closing.

**Comment by ghazal** [comment]
Confirmed.
 Issue solved.
