### ISSUE TITLE
[4.0] Custom administrator menu. No linking to menu items in left sidebar.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#23491]
I'm not talking about menu modules here

### Steps to reproduce the issue
- 4.0 nightly alpha7 with blog sample data
- Create a custom administrator menu, e.g called "meins".
- Add 1, 2 menu items.
- Have a look in the left sidebar

- First click on a menu title of a Site menu: All fine. You'll be redirected to the items view of this menu.
- Then click on the menu title "meins" of your new administrator menu.
==> No redirection to the menu items of this menu. Only a submenu "Add New Menu Item"

![09-01-_2019_21-23-50](https://user-images.githubusercontent.com/20780646/50926429-45f57280-1455-11e9-8049-32d8c36edc31.jpg)

#### Addition
- If I disable "Add New Shortcuts" in module "Admin Menu" (type "Administrator Menu"). the custom menu "meins" is linked to the menu items. Fine so far.
- But what is this setting good for if no other item of the Admin menu gets a "Add New Menu Item" if it's activated?
- At least inconsistent behavior...

**Comment by bahl24** [comment]
@ReLater I think the issue has been fixed, I was unable to reproduce it. Kindly recheck.

**Comment by ReLater** [comment]
I rely in your statement.

**Comment by infograf768** [comment]
Sorry to say but admin menus are totally broken at this stage of the branch.
Creating an admin menu with menu items does not create a tree at all.

**Comment by ReLater** [comment]
Also related: https://github.com/joomla/joomla-cms/issues/23070
