### ISSUE TITLE
launch.joomla.org breaks at installation

### ISSUE THREAD

**Issue by schnuti** [joomla/joomla-cms#23500]
Sorry, don't know if this is the place to report this bug. Please forward if not.

Breaking the installation process on launch.joomla.org is not the best marketing.
I tried to install the latest Beta (today - jan. 10., Location Europe)

Installation stops with:
{"error":"data is invalid","message":"Please click on the reCAPTCHA box."}

I  can't see any reCaptcha on the installation page.

**Comment by Quy** [comment]
Please report issue here: https://github.com/joomla/joomla-websites/issues<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23500">issues.joomla.org/tracker/joomla-cms/23500</a>.</sub>
