### ISSUE TITLE
Problem with template in Joomla4 alfa 5/6

### ISSUE THREAD

**Issue by fgonc124** [joomla/joomla-cms#23505]
I have a template that works fine in Joomla 3.9.1. and in Joomla 4 Alfa 1 to Alfa 3.

But stoped work in latest Joomla4 Alfa versions, Alfa 5 and Alfa 6

The template should show an horizontal menu like this ![screen shot 2019-01-10 at 21 48 50](https://issues.joomla.org/uploads/1/1631ca971b5345c8e1e456451db6f1cd.jpg)
Instead  it shows a menu like this ![screen shot 2019-01-10 at 21 49 06](https://issues.joomla.org/uploads/1/5bf6285a308976728b5023d29403add5.jpg)
You can see the html generated by version J4 Alfa3 
![screen shot 2019-01-10 at 21 49 06](https://issues.joomla.org/uploads/1/136e2a2f2e66323195b9d543f4a5942f.jpg)
and by Alfa 6
![screen shot 2019-01-10 at 21 49 06](https://issues.joomla.org/uploads/1/0d4cb8a6b9c095c44258016e20db4814.jpg). 
The problem is on last line. Alfa6 generates \<ul class="menu"> instead of \<ul class="lcp-hmenu"> .
After debuging the file lcp_template\html\mod_menu\default.php I found that the array $attribs['name'] is not set. Because of that the line 
if (isset($attribs['name']) && $attribs['name'] == 'user3')
  is never excuted. 

### Steps to reproduce the issue
install the attached template, lcp_template Make it the default template and assign position user3

### Expected result
![screen shot 2019-01-10 at 21 48 50](https://issues.joomla.org/uploads/1/1631ca971b5345c8e1e456451db6f1cd.jpg)

### Actual result
![screen shot 2019-01-10 at 21 49 06](https://issues.joomla.org/uploads/1/5bf6285a308976728b5023d29403add5.jpg)

### System information (as much as possible)
Windows 10 with Apache 2.4 + PHP 7.1.2 + Mysql 5.7.17 + Mysqli driver ( the same happens with PDO driver)
### Additional comments
I can't send the template so that you test it. How can I overcome the problem

**Comment by ElephantInTheRoomFirst** [comment]
You may do a pull request. https://help.github.com/articles/fork-a-repo/

**Comment by fgonc124** [comment]
Where can I find documentation of Flow execution of templates.?
Its strange the same template works in J4 Alpha3 and not in Alpha 5/6.
Thanks in advance
