### ISSUE TITLE
Provision for showing only filter container and hiding the "search tool" button on list view.

### ISSUE THREAD

**Issue by amit4106udale** [joomla/joomla-cms#23507]
### Is your feature request related to a problem? Please describe.
Yes, Currently there is no such provision to show filters container by hiding the "search tools" button. Most of the times in frontend, user don't want an extra click to open the filters. So, we need a facility to show only the filters container of the search tool.

![users - joomlafilters - administration](https://user-images.githubusercontent.com/26816967/51024137-b237b980-15ae-11e9-87a1-6d426cc800f9.png)

### Describe the solution you'd like
Need to add a config in custum options for showing the filter container and hide the "search tools button". 

### Additional context
It will reduce the number of clicks for better user experience. 
Sometimes there are only one or to filter fileds in filter container so its is not needed show the  "search tools" button. Instead of that, we can show the filter container directly.

**For example :-**
We need to pass one extra param at the time of rendering respective search toolbar, on the basis of this it will hide the  "search tools" button and directly show the filter container.

  **JLayoutHelper::render('joomla.searchtools.default', array('view' => $this, options=> array('showOnlyFilters' => 1)));**

**Comment by ghost** [comment]
@amit4106udale please close this Issue as you have created the Pull Request #23508.
