### ISSUE TITLE
J 4.0 new menu items not found - get 404 error instead

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#23503]
### Steps to reproduce the issue
Create new menu items. In this case I created three different types:
1. Single article (alias 'test')
2. Category blog (alias 'category-blog')
3. Login (alias 'login-form')
All on the main menu with standard Public access and all published.
### Expected result
To reach any of these pages when clicking the link in the main menu

### Actual result
1. The menu items are displayed on the main menu
2. The URL is displayed at the bottom left of the browser (Firefox) as normal, when hovering over the main menu item link
3. Clicking on the link results in a 404 error:

![image](https://user-images.githubusercontent.com/36987494/50982509-434a5a00-14f5-11e9-90d0-e0b97aee5925.png)

### System information (as much as possible)
Using Joomla! 4.0.0-alpha7-dev (from a few days ago) on CloudAccess.net website
Different browsers have the same result

### Additional comments
Is this related to #23086 or something else?

**Comment by GHSVS-de** [comment]
It looks like you've activated "Use URL Rewriting" in global settings but didn't activate your `.htaccess` by renaming `htaccess.txt` to `.htaccess`

**Comment by Scrabble96** [comment]
Thank you, @GHSVS-de, that was indeed the problem. It's so long since I'd started a Joomla website from scratch, rather than using an Akeeba backup installation with .htaccess already renamed, that I'd forgotten. Apologies.
