### ISSUE TITLE
[4.0] [RFC] Shall we increase the default values for "Password Options" a bit?

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#23511]
### Steps to reproduce the issue
- Go to Users > Options (`administrator/index.php?option=com_config&view=component&component=com_users`)
- Check the default settings for "Password Options".

These values are faaaar away from being secure. J4 gives us the possibility to define a little bit more secure default settings for newly created accounts.

Suggestions please if accepted.

**Comment by brianteeman** [comment]
IIRC (and I could be wrong) the reason for the current default values was because of how to handle existing users who created passwords before any restrictions were created

**Comment by ReLater** [comment]
Only new users or users with a flag "Require Password Reset" will be forced to respect theses settings. Existing passwords are not affected. I haven't tested that with J4 but in J3 it's like that.

BTW: If an administrator creates a new user account (back-end) without entering a password these settings are also ignored (hard coded length of new random password). Maybe that should be also lengthened a bit(?)

**Comment by brianteeman** [comment]
If the settings are ignored then that is a bug

**Comment by ReLater** [comment]
>  If an administrator creates a new user account (back-end) without entering a password these settings are also ignored

Just to confirm this behavior in J4:
- The password length in this case is always 8.
- Characters: [a-zA-Z0-9] (random combinations)
- Generated here: https://github.com/joomla/joomla-cms/blob/4.0.0-alpha6/libraries/src/User/UserHelper.php#L495-L497
- Called by: https://github.com/joomla/joomla-cms/blob/4.0.0-alpha6/libraries/src/User/User.php#L584
