### ISSUE TITLE
[4.0] Atum template title parameter shows the wrong color

### ISSUE THREAD

**Issue by nadjak77** [joomla/joomla-cms#23519]
### Steps to reproduce the issue
Go to the backend template style and edit the atum style. Toggle the "Site name"-parameter.

### Expected result
Show => green
Hide => gray

### Actual result
Show => gray
Hide => green

![grafik](https://user-images.githubusercontent.com/37655645/51074620-94875480-1681-11e9-83d7-4294fa5bcb4d.png)

![grafik](https://user-images.githubusercontent.com/37655645/51074626-9ea95300-1681-11e9-8f60-09aa376fd1e0.png)

**Comment by Quy** [comment]
Please test PR #23521<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23519">issues.joomla.org/tracker/joomla-cms/23519</a>.</sub>
