### ISSUE TITLE
[4.0] Avoid use of of @import for Google font

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#23516]
### What needs to be fixed
Cassiopeia template.css line 8:
`@import url("https://fonts.googleapis.com/css?family=Fira+Sans:400");`

### Why this should be fixed
Highlighted in GTMetrix analysis and, to quote Yellow Lab Tools: "It’s bad for performance to use `@import` because CSS files don't get downloaded in parallel.
You should use `<link rel='stylesheet' href='a.css'>` instead."

### How would you fix it
Either:
Move the request to the head of the index.php file with 
`<link href="https://fonts.googleapis.com/css?family=Fira+Sans:400" rel="stylesheet">`
or include the font in the files and use `@fontface` 

### Side Effects expected
Better browser support

**Comment by astridx** [comment]
We load the fonts from Google's Server. There are many advantages preventing loading the Google fonts from Google’s servers but save locally. The reasons vary from privacy concerns over caching advantages to reducing file requests from third party servers. 

Is there something against not only changing the way you integrate, but also storing the font locally?

**Comment by hardik-codes** [comment]
@Scrabble96 May I work on this issue?

**Comment by Scrabble96** [comment]
> 
> 
> @Scrabble96 May I work on this issue?

@hardik-codes 
Please, be my guest. My expertise in Joomla core code is very limited. How my suggested solution, or any other solution, is implemented is not my area of expertise.

**Comment by hardik-codes** [comment]
Then I'll try to implement your solution and create a pull request for the same @Scrabble96

**Comment by hardik-codes** [comment]
@C-Lodder and @dgrammatiko to which index.php file the above changes are to be made?

**Comment by C-Lodder** [comment]
@hardik-codes The font is being imported here:

https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/cassiopeia/scss/blocks/_global.scss#L3

The `index.php` file you'll need to add it to is:

https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/cassiopeia/index.php

**Comment by hardik-codes** [comment]
Thanks @C-Lodder

**Comment by C-Lodder** [comment]
@hardik-codes Should just be able to get away with this in the `index.php` file:

```
HTMLHelper::_('stylesheet', 'https://fonts.googleapis.com/css?family=Fira+Sans:400');
```

**Comment by puneeth-chanda** [comment]
@hardik-codes are you still working on the issue, if not I will work on it

**Comment by hardik-codes** [comment]
@puneeth2001 already a PR is generated for this issue.

**Comment by roland-d** [comment]
Closing this as we have a PR #23682

**Comment by dgrammatiko** [comment]
@puneeth2001 read my comments and see if you can come up with the right changes

**Comment by dgrammatiko** [comment]
@roland-d that PR is not working as is...

**Comment by roland-d** [comment]
@dgrammatiko Let's discuss the issues in the PR itself. Thanks for pointing it out.

**Comment by hardik-codes** [comment]
@puneeth2001 I'm still working on it
