### ISSUE TITLE
[4.0] Legacy View not working - no data from model

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#23517]
### Steps to reproduce the issue
When you open some view in administration which is based on JViewLegacy (external component views), it does not load data from model

### Expected result
Data from model are loaded.

### Actual result
Joomla! 4.0.0-alpha6 - everything works as expected.
Joomla! 4.0.0-alpha7-dev - data are not loaded.

You can test it with some external component view or build your own:
```php
jimport( 'joomla.application.component.view' );

class SomeView extends JViewLegacy
{
	protected $state;

	function display($tpl = null) {

		$this->state		= $this->get('State');
		dump($this->state);
	}
}
```

produces in Alpha6
![OK](https://i.imgur.com/ynVIPNF.png)

but in Alpha7 (latest build created by composer/npm):
![OK](https://i.imgur.com/bk9PpHD.png)

Data from model are not loaded at all
### System information (as much as possible)
Joomla! 4.0.0-alpha6 - works OK :heavy_check_mark: 
Joomla! 4.0.0-alpha7-dev (latest build created by composer/npm) - data are not loaded. :red_circle: 

Joomla! Version | 4.0.0-alpha7-dev
-- | --
PHP Version | 7.2.4
Identity | user
Response | 200
Template | atum
Database | ServermysqlVersion5.5.5-10.2.6-MariaDBCollationutf8mb4_unicode_ciConn Collationutf8_general_ci

**Comment by stankurd** [comment]
maybe this is the same i have this bug
An error has occurred.
 Call to a member function getName() on boolean 
# | Function | Location
1 | () | JROOT\libraries\src\MVC\View\AbstractView.php:189

**Comment by wilsonge** [comment]
I have no clue why. But https://github.com/joomla/joomla-cms/pull/23525 seems to fix the extension I tested with

**Comment by PhocaCz** [comment]
Thank you @wilsonge , this did the trick.
