### ISSUE TITLE
Is it correct that we have references to Wordpress in our code?

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#23527]
Is it correct that we have references to Wordpress in our code?
https://github.com/joomla/joomla-cms/blob/c17bfc4bfc75847c334176c519a87ba871c401de/administrator/components/com_joomlaupdate/restore.php#L6625

**Comment by dgrammatiko** [comment]
@astridx this is **not** a Joomla file. Check the doc blocks...

**Comment by astridx** [comment]
@dgrammatiko Thank you.
But now I am confused. Why is the file in the joomla-cms repo? Is this correct?

**Comment by mbabker** [comment]
The file comes from a third party vendor (Akeeba) and is based on code they have written to support Joomla core updates specifically as well as logic for their products for both Joomla and WordPress.  There is no issue here.
