### ISSUE TITLE
[4.0] Include woff2 as default Valid Font Format in Global configuration for templates

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#23520]
### Is your feature request related to a problem? Please describe.
Not a problem; just looking ahead. To quote creativemarket.com found on Google search for woff vs woff2: "WOFF2 is the next generation of WOFF. The WOFF2 format offers a 30% average compression gain over the original WOFF."

### Describe the solution you'd like
Add 'WOFF2" or "woff2" as default Valid Font Format in Global configuration for templates 
I know it can be added manually, but if it is going to be increasingly frequently in the future, it might as well be there.

**Comment by ReLater** [comment]
See https://github.com/joomla/joomla-cms/pull/23522

**Comment by Scrabble96** [comment]
Sorry, I must remember to check PRs as well as Issues.
