### ISSUE TITLE
[4.0] com_tags various errors

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#23529]
### Steps to reproduce the issue
Admin
Creating or modifying a tag via com_tags and Save
Error:
Too few arguments to function PlgContentJoomla::onContentBeforeSave(), 3 passed in /joomla-cms/libraries/src/Plugin/CMSPlugin.php on line 287 and exactly 4 expected 

Front
These Menu Types created:
Compact list of tagged items
Tagged Items
List of all tags

Error:
Class 'Joomla\Component\Tags\Site\Model\TagsHelperRoute' not found 
PS : I guess this should be
Joomla\Component\Tags\Site\Helper\TagsHelperRoute

### System information (as much as possible)
PHP 7.2.5
Nightly Build: Sunday, 13 January 2019 (update package)

**Comment by ReLater** [comment]
Concerning: "Creating or modifying a tag via com_tags and Save. Error:...."

Test https://github.com/joomla/joomla-cms/pull/23531 please.

**Comment by ghazal** [comment]
@ReLater 
Thanks for correcting error 1.
Already merged.
Do you think I should make a new post for error 2 ?

**Comment by infograf768** [comment]
No use. This has not been closed in order to also correct this error. :)

**Comment by ghazal** [comment]
OK.

**Comment by infograf768** [comment]
The file to correct is
.../components/com_tags/tmpl/tags/default_items.php
Adding
`use Joomla\Component\Tags\Site\Helper\TagsHelperRoute;` should solve it.

**Comment by ghazal** [comment]
@infograf768 
I tried this, it doesn't work, otherwise I would have made a pull request.

**Comment by infograf768** [comment]
It works here for a "List of all tags" menu item.
The other specific menu items for tags are broken at the moment because of the new choice.js which prevents from selecting the options for the field:

![screen shot 2019-01-14 at 12 17 20](https://user-images.githubusercontent.com/869724/51109759-7c851180-17f6-11e9-9d86-c7cd9c22d37a.png)

**Comment by infograf768** [comment]
BTW: I would not test anything on an "Updated" 4.0. I always test on the branch after running npm ci

**Comment by ghazal** [comment]
True that my test site with composer and npm was several updates behind. 
Corrected.
This solution doesn't work on front-end.
But maybe we should hold this off until the menu system is fully functional and com_tags itself is corrected because there are still some bugs.

**Comment by ghost** [comment]
@ghazal closing this Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23529">issues.joomla.org/tracker/joomla-cms/23529</a>.</sub>

**Comment by ghazal** [comment]
Yes. Sorry.

**Comment by ghost** [comment]
thanks @ghazal
