### ISSUE TITLE
[4.0] [com_fields] Inconsistent positions across article views

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#23536]
### Steps to reproduce the issue
Create three custom fields and set the values for automatic display to "after title", "before content" and "after content"

### Expected result
1. Single article, Blog item, featured item will all display the same
2. "After content" will be at the end of the content and therefore not displayed on a blog item or featured item

### Actual result
1. "after title" does not display on blog item
2. "after content" is displayed after the readmore link

### Article View
![image](https://user-images.githubusercontent.com/1296369/51104097-045e2200-17dd-11e9-8e4f-114b06ceaba5.png)

### Blog View
![image](https://user-images.githubusercontent.com/1296369/51104134-2192f080-17dd-11e9-8727-859c76f6e23a.png)

### Featured View
![image](https://user-images.githubusercontent.com/1296369/51104165-3c656500-17dd-11e9-92db-abed4f01dfa4.png)

**Comment by rytechsites** [comment]
Will this be worked on in a future release?  This is important, as we have many category blog views, and want to be able to 'control' the custom fields to 'not display' in the blog view, but in the article view, and previously the only way was to use the 'display after content'.

**Comment by brianteeman** [comment]
Closed due to lack of interest
