### ISSUE TITLE
blog of featured articles

### ISSUE THREAD

**Issue by ZerooCool** [joomla/joomla-cms#23532]
By default, the menu link that calls my homepage was: blog of featured articles

The article posted had at the top of the page, the author, the date, and what interests me here, the category.

When I clicked category, only 4 items were displayed (table view) and pagination enabled, which offered me 4 pages.

I could not figure out how to set up a "Featured Articles Blog" menu link so that the "Category Name" link displayed at the top of an article could show all items in a table, on a single page.

I changed the menu link that displayed the home page, I put, "post an article" (only the article home page.)

Now, if I click on the name of the category, I have the full table of articles that appears.

I do not know if this is due to my Joomla setting, I have not found the option to set the number of items to display in a table with a link like "Featured articles blog".

Now that I have chosen the option to display a single article, the category link correctly displays my table, with items from my category, and, child categories, in one table of all articles.

**Comment by ZerooCool** [comment]
Another problem that I encountered to display items from a table category. I found the option in a tab that seems to me inconsistent. I could be wrong.

Objective: Display in a table, the list of articles of a category and its children.

Resolution:

Create a menu link: List of items in a category
In the category tab, change the Subcategories value to "None".

In the article settings, Blog / Featured tab, I pass the first four values ​​to 1 1 1 0 (which does not seem essential.)
The Include subcategories value is changed to "All".

Now, if I click on my menu link, I have a table that will display the list of items in a category (and its children) as a table, in the same table.

What seems to me poorly conceived:
When creating the Article menu link, you have the option to create two types of Blog menu links, or, to list the articles of a category, since I chose the option "List articles of a category" it seems confusing, having to set the display through: article settings, "Blog / Featured Tab", with the value Include subcategories to be changed to "All".

**Comment by ZerooCool** [comment]
Always with this incomprehension between list and blog, the expected result corresponds almost to my expectations, but, not totally!

Now that I have created a menu link for a single article, see : https://www.visionduweb.fr

I also agreed in the link of the article, that the titles are clickable. So, the category that appears above my article is clickable.

So I can click on "Site Structure".

There, the list of all my articles will be displayed. It's interesting, I was not necessarily trying to do that, but, I think it's good, it can be used to make all the content accessible.

No way to find out how to limit the number of articles displayed here, to take advantage of the pagination.

So I have my homepage, which displays a unique article, I click on the category of this article that I allowed to be clickable, and, this will show me in tabular form, all the articles of my site, from the category "site structure" and the categories children as well.

Can you help me set a default size, for the number of lines allowed to be displayed, and have pagination?

If I turn on the "Display Selector" from the article settings, I can add the drop-down list that allows to display fewer items, if and only if, the user changes the display itself.

I would like to limit myself, the number of articles displayed, for example, to 20 or 25. I do not find this possibility.

--------------------------------

With a menu link: List of items in a category, this menu link to a List tab, which allows you to set a limit.

With my menu link, I display an article.
This type of menu link does not have to list finally ... The option is not integrated.

Still, a link "category name is clickable" and will display a list of items in the category. So I do not have the ability to control the limit of displayed items.

**Comment by brianteeman** [comment]
If you create a menu item (it doesnt have to be visible) of type category list then do you get what you are trying to achieve?

**Comment by ZerooCool** [comment]
Watch the rendering here then click on the category structure of the site
http://visionduweb.joomla.com/

You notice that the display of the links is without pagination, therefore, if 1000 articles, a page of 1000 lines ....
http://visionduweb.joomla.com/index.php/8-structure-du-site

If as you propose it to me I chose to create a menu link in list view, for my home page, the home page will surely be displayed in a table, as a list, out, nobody would want to display a page Welcome in the form of a list, to have a nice page.

I think it's a very nasty side effect:
1- If we click on the category (clickable title) from a page that displays a single article ....
2- If we have configured by default the item settings to display them as a list, as well as the child categories ....

3: So! ... The edge effect would occur?
So if the category of my unique home page article is called "Site Structure" and would display all articles of "Site Structure" without any pagination by default.

**Comment by brianteeman** [comment]
> http://visionduweb.joomla.com/index.php/8-structure-du-site

That shows me that you did not create a menu link of type Category List as I suggested

If you do that then you can control the number of items displayed in the list. I logged in to your site and did that for you

**Comment by ZerooCool** [comment]
Thank you I will look at your example and I come back to validate the subject in the day.

**Comment by ZerooCool** [comment]
I do not know for lines of code, this is the insert video icon, in the default text editor.

I guess iframes are removed by default.

Therefore, by default, the insert video icon does not work.

Even if adding a component or a plugin can correct this, I think an improvement is to be made, for the default behavior.

**Comment by ZerooCool** [comment]
Very well, actually, I knew this type of manipulation, which actually works very well.

I thought I could have this type of behavior, without having to add a menu link.

Thanks to your example, it works very well now.

I may still be in the query with the type of link I get: 
domain / link-from-menu

I would have expected a link of the type:
domain / category / link-the-menu
 
I find the correct result in what I could expect, but, I do not understand why I do not get a link like: 
domain / category / link-of-the-menu

Thank you for your answer and the time you took for the example.

https://www.visionduweb.fr
https://www.visionduweb.fr/structure-du-site

**Comment by ghost** [comment]
closed as Issue solved. Please reopen if its not.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23532">issues.joomla.org/tracker/joomla-cms/23532</a>.</sub>
