### ISSUE TITLE
subform doesn't allow multiple default values

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#23534]
### Steps to reproduce the issue
create a subform field.
[form.txt](https://github.com/joomla/joomla-cms/files/2753922/form.txt)
( wouldn't allow direct pasting of form field )
examine backend.  You'll see 4 rows of fields instead of 2 rows with defaults

![image](https://user-images.githubusercontent.com/1850089/51094671-97af3d00-1774-11e9-9ed6-a8036008d50c.png)

change form type to repeatable
examine backend...
you get single row ( NOT SURPRISING )
![image](https://user-images.githubusercontent.com/1850089/51094694-cc22f900-1774-11e9-8a1d-0d860c2dd7da.png)
put type back to subform, remove default values.
![image](https://user-images.githubusercontent.com/1850089/51094712-f7a5e380-1774-11e9-9c22-b2fcf808783d.png)
add default to individual fields
`                        <field
                                name="socialiconname"
                                type="text"
                                label="name"
                                default="mary"
                        />
                        <field
                                name="socialiconimage"
                                type="media"
                                label="image"
                                default=""
                        />
                        <field
                                name="socialiconclass"
                                type="text"
                                label="class"
                                default="fa fa-facebook"
                        />
                        <field
                                name="socialiconurl"
                                type="url"
                                label="url"
                                default="http://no.net"
                        />`
![image](https://user-images.githubusercontent.com/1850089/51094746-2e7bf980-1775-11e9-88f5-ca17e9dd24d2.png)

### Expected result
multiple rows with defaults set per subform field.

### Actual result
see above.

### System information (as much as possible)

[systeminfo-2019-01-14T02_54_24+00_00.txt](https://github.com/joomla/joomla-cms/files/2753914/systeminfo-2019-01-14T02_54_24%2B00_00.txt)

### Additional comments
I've tried dozens of possibilities and nothing seems to work properly.

**Comment by dgrammatiko** [comment]
@N6REJ this is expected. The repeated fields, in the current implementation, are just a hard copy of the initial provided field. So whatever the default value there will be repeated on the subsequent fields. It's designed that way, it's not a fault or limitation.

PS if you need deferent default values then spawn different fields...

**Comment by N6REJ** [comment]
@dgrammatiko  oh wow... Why the downgrade from repeatable?  That was an important feature imo.
So what is the purpose/use of the "default" parameter?  https://docs.joomla.org/Special:MyLanguage/subform_form_field_type  Says to use a json string which afaik I'm doing correctly.

**Comment by SharkyKZ** [comment]
This should work:
```
{"socialArray0":{"socialiconname":"facebook","socialimage":"","socialclass":"fa fa-facebook","socialiconurl":"http://no.net"}, "socialArray1":{"socialiconname":"Youtube","socialimage":"","socialclass":"","socialiconurl":""}}
```
It's how the values are stored in the database.

**Comment by N6REJ** [comment]
very interesting, ty!  I assume this would go in the "default" parameter

**Comment by SharkyKZ** [comment]
Yes, it would go to `default` attribute. There was an error in the above code. Fixed now.

**Comment by dgrammatiko** [comment]
@N6REJ sorry I was wrong, probably because I don't use extensively this form field

**Comment by Fedik** [comment]
I think it can be closed, as it not an issue, but incorrect usage

**Comment by N6REJ** [comment]
@Fedik not incorrect usage necessarily, more like undocumented usage!

@dgrammatiko it's fine :D  your right way more then your wrong lol

**Comment by brianteeman** [comment]
This should be closed base don @fedik comment above
