### ISSUE TITLE
PHP Warning: Invalid argument supplied for foreach()... tag/view.feed.php on line 35

### ISSUE THREAD

**Issue by meichenblatt** [joomla/joomla-cms#23542]
Hi,

We are getting this error thrown to error log file:

[14-Jan-2019 05:26:34 UTC] PHP Warning: Invalid argument supplied for foreach() in /home/vargopt/public_html/components/com_tags/views/tag/view.feed.php on line 35 

php version 7.2
Joomla version: 3.9.1

Any ideas?

Thanks!

**Comment by tonypartridge** [comment]
I’ve made a PR. Can you try the proposed changes, I’m not at a computer st the moment.

**Comment by Quy** [comment]
Please test PR #23543<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23542">issues.joomla.org/tracker/joomla-cms/23542</a>.</sub>
