### ISSUE TITLE
[4.0] Non-clickable module in a menu item

### ISSUE THREAD

**Issue by hardik-codes** [joomla/joomla-cms#23540]
### Steps to reproduce the issue
Navigate to following page from the admin page
**Menus** >> **Main** **Menu** >> **Home**
![joomla6](https://user-images.githubusercontent.com/34353697/51133061-eda9e080-1859-11e9-8d31-a59d58df0b5d.png)

### Expected result
Under the **Module Assignment** tab, menu items such as **Breadcrumbs**, **Main Menu** should be clickable and should take the user to another page

### Actual result
On clicking the menu items such as **Breadcrumbs**, **Main Menu** nothing happens.

**Comment by infograf768** [comment]
Confirmed. 
`moduleEditModal` is broken atm.
same for edit article modal

**Comment by Quy** [comment]
Please test PR #23609<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23540">issues.joomla.org/tracker/joomla-cms/23540</a>.</sub>
