### ISSUE TITLE
[3.9] Badword(s) in contact form does not work

### ISSUE THREAD

**Issue by ChristineWk** [joomla/joomla-cms#23546]
Issue reported: https://forum.joomla.de/thread/7135-badwords-in-kontaktformular-funktionieren-nicht/
### Steps to reproduce the issue
Go to: components > contacts > contacts
Contact Form > show (activated)

Fill in the contact form with banned words. 

Form:
Banned Subject: badword1;badword2;
Banned Text: badword1;badword2;

### Expected result
Contact form should not be sent.

### Actual result
Contact form sent.
There is no message either.

**Comment by infograf768** [comment]
Confirmed.
It is only working if set in com_contacts Global Options.
In that case, one gets an invalid field error for Message

**Comment by infograf768** [comment]
The test for these are done in
/components/com_contact/models/rules/contactemailsubject.php
and
/components/com_contact/models/rules/contactemailmessage.php

Where $params are only fetched from the component.

**Comment by ChristineWk** [comment]
@infograf768 Thank you for your info: "to set in Global Options. Will check it.

Concerning 2nd reply: how should it be tested? Do we have to check also the php files?

 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23546">issues.joomla.org/tracker/joomla-cms/23546</a>.</sub>

**Comment by infograf768** [comment]
The /components/com_contact/models/forms/contact.xml contains:
```
		<field
			name="contact_subject"
			type="text"
			label="COM_CONTACT_CONTACT_MESSAGE_SUBJECT_LABEL"
			description="COM_CONTACT_CONTACT_MESSAGE_SUBJECT_DESC"
			id="contact-emailmsg"
			size="60"
			filter="string"
			validate="contactemailsubject"
			required="true"
		/>

		<field
			name="contact_message"
			type="textarea"
			label="COM_CONTACT_CONTACT_ENTER_MESSAGE_LABEL"
			description="COM_CONTACT_CONTACT_ENTER_MESSAGE_DESC"
			cols="50"
			rows="10"
			id="contact-message"
			filter="safehtml"
			validate="contactemailmessage"
			required="true"
		/>
```
As one can see, the validation comes from the files I noted in
https://github.com/joomla/joomla-cms/issues/23546#issuecomment-454349261

To solve this, we would need to merge the params from the contact itself, then the params from the menu item displaying the contact to the Component params in these files where we only have:
`$params = JComponentHelper::getParams('com_contact');`

Looking into it here. Not sure I can solve. Will try.

**Comment by ChristineWk** [comment]
> 
> 
> Confirmed.
> It is only working if set in com_contacts Global Options.
> In that case, one gets an invalid field error for Message

Just tested. Confirm above. Options > Form > Banned Subject / Banned Text
Message:
Fehler
Ungültiges Feld: Betreff
Ungültiges Feld: Nachricht

**Comment by infograf768** [comment]
same for `banned_email`
Grr

**Comment by infograf768** [comment]
Making a PR now.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/23569
closing as we have a PR

**Comment by infograf768** [comment]
@ChristineWk 
Please inform also https://forum.joomla.de/thread/7135-badwords-in-kontaktformular-funktionieren-nicht/ about the PR to test.

**Comment by ChristineWk** [comment]
@infograf768 Thank you! Tested PR#23569 and will inform forum accordingly
