### ISSUE TITLE
Users > Search Tools:: Select Group drop down should be multi select not the single select

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#23544]
Go to Joomla Back end
Go to Users
Click on search tools
Open the Select Group drop down
If you see, this drop down only allow to select the single value
But, ideally, it should let us select multiple options as one user can belong to many groups

_Thank you._![screen shot 2019-01-15 at 07 23 37](https://issues.joomla.org/uploads/1/610c47614fddcec5e8999977053bd82c.png)

**Comment by ElephantInTheRoomFirst** [comment]
Interesting observation. 
This can be applicable to other dropdowns also. Example github issue filtering.

**Comment by ghost** [comment]
@HLeithner as new Feature didn't go in J3 should that get a J4-Label.

**Comment by HLeithner** [comment]
Yes

**Comment by brianteeman** [comment]
Not sure it is a correct observation anyway

**Comment by aasimali** [comment]
@brianteeman 
Can you please explain to me the correct one?

**Comment by ghost** [comment]
@HLeithner can you set a j4-Label as i have no Permissions.

**Comment by HLeithner** [comment]
It's a valid feature request so select multiple access levels similar to multiple categories

**Comment by brianteeman** [comment]
If a user is in many groups eg members and specialmembers then setting the filter to members will find the user AND setting the filter to specialmemembers will find the user. So I am not sure what it is you are trying to achieve

**Comment by brianteeman** [comment]
@HLeithner it is nothing like categories. An item can only be in one category. A user can be in multiple groups

**Comment by HLeithner** [comment]
Isn't the target to show all articles visible to access group "A", "B" and "C"?

**Comment by brianteeman** [comment]
The settings within a filter are OR not AND
And the request is not for com_articles but com_users

**Comment by aasimali** [comment]
@brianteeman 
Let me explain to you why I raised this?
- I have 1k users on my website
- Out of which 5 users belong to admin + registered
- 10 belongs to admin level only

So to know the name of the users who actually belongs to admin + registered, how I will use the filters?

**Comment by brianteeman** [comment]
@aasimali the problem is that no other filter works as an AND filter. If the code3 was changed to make this one filter work as an AND instead of OR then that would create confusion

**Comment by aasimali** [comment]
@brianteeman 
I got your point, but don't you think this case is also confusing and filters are not serving their purpose?

**Comment by HLeithner** [comment]
Oh yeah its com users, mixing filter types could be really confusing so I'm not sure if this makes the interface easier one the other site the category filter is a OR filter and would have the same behavior

**Comment by alikon** [comment]
closing as it imo is a new feature and not an issue
new features should go in the 4.x
@aasimali please submit  a pr on that branch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23544">issues.joomla.org/tracker/joomla-cms/23544</a>.</sub>

**Comment by aasimali** [comment]
@alikon 
Can you please submit a PR for this feature? as I am not from the development background.
