### ISSUE TITLE
[4.0] PHP error when using the "usergroup" form field

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23545]
### Steps to reproduce the issue

Add the following field to `modules/mod_login/mod_login.xml`:

    <field name="test" type="usergroup" multiple="true" label="Usergroup" />

### Expected result

Ability to select multiple usergroups which then become appended to the input (similar to selecting tags for an article)

### Actual result

> Warning: htmlspecialchars() expects parameter 1 to be string, array given in C:\dev\joomla4\layouts\joomla\form\field\text.php on line 96

![screenshot_2019-01-15 modules login - joomla 4 - administration](https://user-images.githubusercontent.com/2019801/51171611-4359a980-18a9-11e9-9eaa-2645989d8013.png)

### System information (as much as possible)

- 4.0-dev build
- PHP 7.2.10

### Additional comments

I assume it's most likely calling the **wrong** layout

**Comment by infograf768** [comment]
Can you explain what you are trying to do with such a field in the login module?
Limiting login to specific groups?
BTW: Unhappily, selecting a tag or multiple tags is badly broken in 4.0

**Comment by infograf768** [comment]
BTW, such a field exists for debug
```
				<field
					name="filter_groups"
					type="usergrouplist"
					label="PLG_DEBUG_FIELD_ALLOWED_GROUPS_LABEL"
					multiple="true"
					filter="int_array"
					size="10"
				/>
```
and it works there for what it does.

**Comment by C-Lodder** [comment]
@infograf768 Adding it to the Login module was purely an example. I'm trying to use it in my own extension.

`usergrouplist` seems to work...thanks.

That said, if `usergroup` is deprecated and is planned to be removed in J4, I still shouldn't be geetting an error, seeing

**Comment by infograf768** [comment]
The logic would be that for "usergroups" as for "tag" we get a new field type similar to CategoryeditField.php or ModulesPositioneditField.php using choice.js.
No idea if anyone working on that
