### ISSUE TITLE
CSS Class for tag link

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#23547]
### Steps to reproduce the issue
![image](https://user-images.githubusercontent.com/1296369/51172546-5cfbf080-18ab-11e9-8c32-0435c806fc9d.png)

The instructions says that "If empty 'label label-info' will be added by the default tag layout." But that isn't quite true as the field has a default value of 'label label-info' so even if left blank the default value will be saved.  This default value is not needed because the layout will add it anyway 
`				<?php $link_class = $tagParams->get('tag_link_class', 'label label-info'); ?>
` as correctly described in the tooltip.

**Comment by ciar4n** [comment]
Does it make more sense to change the description to simply "If empty, 'label label-info' will be used" and keep the default value? At least that way it is more apparent to the user what is happening.

**Comment by brianteeman** [comment]
You're right - after submitting this issue I saw other fields with similar behaviour and a better text

See #23561
