### ISSUE TITLE
[3.9.2][com_menus] templatestyle select not shown

### ISSUE THREAD

**Issue by apophis1982** [joomla/joomla-cms#23551]
### Steps to reproduce the issue
Go to Menus -> New or existing menu item -> every menu type except menu item alias

### Expected result
template style selectbox is displayed

### Actual result
template style selectbox is hidden

### System information (as much as possible)
new install joomla 3.9.2 and update from 3.9.1 to 3.9.2 on linux ubuntu server, php 7.2

### Additional comments
In the xml file item.xml in administrator/components/com_menus/models/forms the field template_style_id changend. showon="params.alias_redirect:0" was added. Without this entry everything works fine

**Comment by HLeithner** [comment]
I can confirm this problem, after update Template style is not visible any longer.

**Comment by jeckodevelopment** [comment]
Issue confirmed.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23551">issues.joomla.org/tracker/joomla-cms/23551</a>.</sub>

**Comment by mbabker** [comment]
Paging @csthomas

Side effect of https://github.com/joomla/joomla-cms/pull/23278 ?

**Comment by infograf768** [comment]
> Side effect of #23278 ?

Indeed here. Reverting it gets back the template style field.

**Comment by csthomas** [comment]
Below patch should fix the problem:
```diff
diff --git a/administrator/components/com_menus/models/forms/item.xml b/administrator/components/com_menus/models/forms/item.xml
index 66dd1bc4a5..fd9a057cbb 100644
--- a/administrator/components/com_menus/models/forms/item.xml
+++ b/administrator/components/com_menus/models/forms/item.xml
@@ -146,7 +146,7 @@
                        description="COM_MENUS_ITEM_FIELD_TEMPLATE_DESC"
                        client="site"
                        filter="int"
-                       showon="params.alias_redirect:0"
+                       showon="type!:alias[OR]params.alias_redirect:0"
                        >
                        <option value="0">JOPTION_USE_DEFAULT</option>
                </field>
```

**Comment by Sandra97** [comment]
Thanks @csthomas 
Your fix works for me

**Comment by wojsmol** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/23556

**Comment by infograf768** [comment]
Closing as we have https://github.com/joomla/joomla-cms/pull/23556

**Comment by Leen29** [comment]
Thanks @csthomas
Your fix works for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23551">issues.joomla.org/tracker/joomla-cms/23551</a>.</sub>

**Comment by infograf768** [comment]
Inform your communities:
https://docs.joomla.org/J3.x:Template_Style_field_not_shown_in_Menu_Items

**Comment by WebDud** [comment]
@csthomas Thank you, works for me !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23551">issues.joomla.org/tracker/joomla-cms/23551</a>.</sub>

**Comment by AlbrechtFrick** [comment]
@csthomas  works fine for me . thanx!
