### ISSUE TITLE
New article results in "DB Access denied" but new article is created + DB Domain wrong in error message

### ISSUE THREAD

**Issue by chainsawbeaver** [joomla/joomla-cms#23557]
### Solution
FYI: User for database was missing CREATE TEMPORARY TABLES and LOCK TABLES rights -> with these enabled it worked fine.

### Steps to reproduce the issue
Adding a new article or changing any article and clicking save (or save & close, or save & new), I get the error:
**1044 Access denied for user 'USERNAME'@'%.DOMAIN.TLD' to database 'DATABASENAME'**

but afterwards there is a new article in the articles list. This has the right title and content but category is always "Uncategorised".

**The database domain is: 22.ABC.DOMAIN.TLD and not %.DOMAIN.TLD as given by the error message.**

Same error when I try to add a new category.

### Expected result
*1 New article with category and content
*2 New category

### Actual result
*1 New article with category Uncategorised and error message "1044 Access denied for user 'USERNAME'@'%.DOMAIN' to database 'DATABASENAME'"
*2 error message "1044 Access denied for user 'USERNAME'@'%.DOMAIN' to database 'DATABASENAME'"

### System information (as much as possible)
Fresh install of Joomla 3.9.1  -> with Error
+ Update to 3.9.2 -> Also with Error

PHP Built On | Linux SERVER 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64
Database Type | mysql
Database Version | 5.7.24-log
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.0.33
Web Server | Apache
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 3.9.2 Stable [ Amani ] 15-January-2019 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0

Relevant PHP Settings
Safe Mode | Off
Open basedir | None
Display Errors | Off
Short Open Tags | Off
File Uploads | On
Magic Quotes | Off
Register Globals | Off
Output Buffering | On
Session Save Path | /var/lib/php/session
Session Auto Start | 0
XML Enabled | Yes
Zlib Enabled | Yes
Native ZIP Enabled | Yes
Disabled Functions | None
Multibyte String (mbstring) Enabled | Yes
Iconv Available | Yes
Maximum Input Variables | 1000

**Comment by ElephantInTheRoomFirst** [comment]
Interesting!!
Are you sure that the error is due to Joomla! and not due to your database server? 
Did your update happen correctly?

**Comment by brianteeman** [comment]
> The database domain is: 22.ABC.DOMAIN.TLD and not %.DOMAIN.TLD as given by the error message.

What are the settings in global config
![image](https://user-images.githubusercontent.com/1296369/51256535-8432ea80-199d-11e9-9a2d-7483606d2451.png)

**Comment by ElephantInTheRoomFirst** [comment]
I have updated my fresh installation 3.9.1 to 3.9.2 and carry out above mentioned scenario. There is no error.

**Comment by chainsawbeaver** [comment]
Thank you for your answers!

> I have updated my fresh installation 3.9.1 to 3.9.2 and carry out above mentioned scenario. There is no error.

I had the error with 3.9.1 and 3.9.2 (did the update today, to see if that fixed it, clarified this above)



> > The database domain is: 22.ABC.DOMAIN.TLD and not %.DOMAIN.TLD as given by the error essage.
> 
> What are the settings in global config

The settings in Global config are all correct e.g. host is 22.ABC.DOMAIN.TLD


> Are you sure that the error is due to Joomla! and not due to your database server?

I am not sure. But isn't at least the error message output wrong/bugged even if the problem is the db server?

> Did your update happen correctly?

Yes that seemed to work. But the error was already there (3.9.1) (clarified this above)

**Comment by chainsawbeaver** [comment]
Thank you for your answers!

> I have updated my fresh installation 3.9.1 to 3.9.2 and carry out above mentioned scenario. There is no error.

I had the error with 3.9.1 and 3.9.2 (did the update today, to see if that fixed it, clarified this above)



> > The database domain is: 22.ABC.DOMAIN.TLD and not %.DOMAIN.TLD as given by the error essage.
> 
> What are the settings in global config

The settings in Global config are all correct e.g. host is 22.ABC.DOMAIN.TLD


> Are you sure that the error is due to Joomla! and not due to your database server?

I am not sure. But isn't at least the error message output wrong/bugged even if the problem is the db server?

> Did your update happen correctly?

Yes that seemed to work. But the error was already there (3.9.1) (clarified this above)

**Comment by HLeithner** [comment]
The error message comes from the mySQL server,

> 1044 Access denied for user 'USERNAME'@'%.DOMAIN.TLD' to database 'DATABASENAME'

USERNAME is your username and after the @ is the host validation, in your case any server which ends with .DOMAIN.TLD is valid for this username. So the error message is correct.

It's possible that article saving executes a database query that is not allowed for your user. The question is which one and what is not allowed?

**Comment by chainsawbeaver** [comment]
> The error message comes from the mySQL server,
> 
> > 1044 Access denied for user 'USERNAME'@'%.DOMAIN.TLD' to database 'DATABASENAME'
> 
> USERNAME is your username and after the @ is the host validation, in your case any server which ends with .DOMAIN.TLD is valid for this username. So the error message is correct.
> 
> It's possible that article saving executes a database query that is not allowed for your user. The question is which one and what is not allowed?

Thank you for your answer! I will close this issue because the problem is with our database settings.

**Comment by chainsawbeaver** [comment]
FYI: User for database was missing CREATE TEMPORARY TABLES and LOCK TABLES rights -> with these enabled it worked fine.
