### ISSUE TITLE
Weblink component does not wrap line including title and alias, table width is increased instead

### ISSUE THREAD

**Issue by kofaysi** [joomla/joomla-cms#23559]
### Steps to reproduce the issue

Create weblink with a title of 200+ characters

### Expected result

The Title (Alias) line to be wrapped in /administrator/index.php?option=com_weblinks view

### Actual result

The Title (alias) line is not wrapped and the table width of the weblink list is increased. Columns Access, Hits, Language and ID are behind the right screen (scrolling is required).

### System information (as much as possible)

Joomla! 3.9.2

**Comment by Quy** [comment]
Please open this issue at https://github.com/joomla-extensions/weblinks/issues as Weblinks is a decoupled extension.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23559">issues.joomla.org/tracker/joomla-cms/23559</a>.</sub>
