### ISSUE TITLE
Remove IDs from CONTACTS URLs

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#23565]
### Is your feature request related to a problem? Please describe.
If I set in Articles: Options - Integration:
URL Routing = Modern
Remove IDs from URLs = Yes
now my articles url is without the ID, but not the Contact URLs

### Describe the solution you'd like
Remove the ID in the contact URLs

**Comment by mbabker** [comment]
You need to change this setting in the contact component settings.  The remove IDs setting is on a per-component basis, changing it in com_content for articles does not change the entire site.
