### ISSUE TITLE
How to add a slash at url article Joomla 3.9?

### ISSUE THREAD

**Issue by Serp7676** [joomla/joomla-cms#23567]
It used to be easy - in file  libraries\joomla\filter\filteroutput.php,  change [^A-Za-z0-9\-]/ in line 91 (add new symbol)

But now this file is gone.  It was possible to create any alias!  
How can I add new symbol in alias??

**Comment by ReLater** [comment]
@Serp7676 
Could you please close your issue and ask in a [forum](https://forum.joomla.org/). Here's the wrong place to ask for dirty and maybe dangerous core hacks.
