### ISSUE TITLE
[4.0] [RFC] Table Options - Active Filters are not visible

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#23572]
### Table Options contain filters - active filters are not visible 
Make several articles or workflows, trash one or more, disable one or more.
Then filter for something. And the list is reloaded.
It is not recognizable that a filter is active, or which filter it is. 
In Version3.x, the searchtool remains open and active filters are visible. Very useful.

Possible solutions:
-  Let the filter panel open - no good solution, the filter panle it is too big.
-  Make an alert above the table: Your active filte is ....
-  Change the colour of the filter button which at lest indicates that a filter is active
-  Other ?

**Comment by brianteeman** [comment]
Another solution is to use the existing table caption
I already added the functionality for the table caption to state what the field is sorted by (#22404) and I had intended to further enhance that to include information on any filters. This is essential for a11y. All that would need to be done is to expose the table caption visually. I didnt do that originally as I was waiting for the template.

**Comment by alikon** [comment]
i vote for 

> In Version3.x, the searchtool remains open and active filters are visible. Very useful.

**Comment by Quy** [comment]
Please confirm that this is no longer an issue.

**Comment by chmst** [comment]
Resolved with the new Backend Template
