### ISSUE TITLE
Google Fonts accent are placed after the letter

### ISSUE THREAD

**Issue by dkaneloglou** [joomla/joomla-cms#23574]
Hi, 

I have  a problem with google fonts when I use letters with accents (Spanish). 
The accent is placed after the letter. ex. 
![image](https://user-images.githubusercontent.com/6862345/51314244-07b11200-1a58-11e9-8d02-42c1fe481c8a.png)

I use this code
`<link href="https://fonts.googleapis.com/css?family=Montserrat&subset=latin,latin-ext,cyrillic" rel="stylesheet">`

and 

`<style type="text/css">*{font-family:Montserrat !important;}</style>`

If I copy the word and paste it in editor the accent is shown correctly. I tried various fonts, Roboto, Ubuntu and have the same problem. 
I use Joomla 3.9.1 
I don´t think is a template issue, because I have this problem also using the protostar template.
I am not sure is it is a joomla issue or google font issue.

**Comment by Bakual** [comment]
Please use the forums (http://forum.joomla.org) for such requests, thanks.
This is the issue tracker for the Joomla core code.
