### ISSUE TITLE
[4.0] Creating articles from menu doesn't work

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#23587]
### Steps to reproduce the issue
* Create a Menuitem of time single article
* Press the plus button create article (opens modal)
* Try to save the modal

### Expected result
* Modal closes and article is saved

### Actual result
* Save button doesn't do anything

### System information (as much as possible)
* J4 git commit 7601d4f0a52e68f7

**Comment by ElephantInTheRoomFirst** [comment]
Confirmed on 14 Jan nightly build.

**Comment by wojsmol** [comment]
This is duplicate of https://github.com/joomla/joomla-cms/issues/23260
