### ISSUE TITLE
count with tags ignores view level and count of every published item is displayed

### ISSUE THREAD

**Issue by kofaysi** [joomla/joomla-cms#23582]
### Steps to reproduce the issue

Log in to the backend. 

For articles and contacts: In a category of Content or Contacts, create an item with a restricted view level (Administrator, editor, not user). Or change an existing one.

For tags: Change the view level for an Article with a particular chosen tag. Create and publish Tags - Popular module, if not published yet.

Log in to the frontend as a user. 

For articles and contacts: List the categories of the articles or contacts and observe the number of items. 

For tags: Observe the similar in the module for Tags - Popular.

### Expected result

For articles and contacts: In that particular Category or for that particular tag, the number of the items shall be restricted only to the items, which the user can see -- the access level of the user allows that.

### Actual result

For articles and contacts: When opening the Category, the number is at least one item less -- the item for which the view rights has been previously changed.

For tags: The count of items displayed next to the tag differs from the number of items under that tags -- after opening the tag.

### System information (as much as possible)

Joomla 3.9.2

### Additional comments

https://forum.joomla.org/viewtopic.php?f=708&t=922805

**Comment by kofaysi** [comment]
I have analyzed the helper file and find out that tags are filtered according the view access level:
https://github.com/joomla/joomla-cms/blob/1b01db5b0f638ca89a0da12f9681c32af0c76a2c/modules/mod_tags_popular/helper.php#L51
but the articles with these tags are not filtered:
https://github.com/joomla/joomla-cms/blob/1b01db5b0f638ca89a0da12f9681c32af0c76a2c/modules/mod_tags_popular/helper.php#L118
adding
`->where('a.access IN (' . $groups . ')');`
to line 120 does not make any change.

Solving the `else` case is up to my knowledge.

**Comment by ghost** [comment]
@HLeithner  can you please comment?

**Comment by HLeithner** [comment]
iirc @Hackwar looked at this for j4

**Comment by ghost** [comment]
this is for J3.

**Comment by Hackwar** [comment]
I've not looked into this yet. I'm in the process of rewriting tagging in 4.0, but did not get to that part yet. But in general the bug description looks correct.

**Comment by SharkyKZ** [comment]
Test PR #25473 please.

**Comment by ghost** [comment]
Closed as having Pull Request #25473
