### ISSUE TITLE
Front end edit problem in custom module with content

### ISSUE THREAD

**Issue by mino182** [joomla/joomla-cms#23584]
### Steps to reproduce the issue
Make custom module with content (copy of mod_custom)

### Expected result
visible content editor.

### Actual result
No content editor

### System information (as much as possible)
In file:
components/com_config/view/modules/tmpl/default.php

on line 18 is variable $hasContent which is dependent on module name. Module which has other name than custom, mod_custom doesn't get content form because of condition on line 182 of same file.
      

### Additional comments
Is it possible to make other decision algorithm for show content form? Thanks

**Comment by ElephantInTheRoomFirst** [comment]
Joomla version?

**Comment by mino182** [comment]
3.9.2

**Comment by ElephantInTheRoomFirst** [comment]
I am not able to reproduce the issue on the build, although module name is different as you have described.
 
![custom-module-on-new](https://user-images.githubusercontent.com/28602840/51424003-11f21e00-1bc8-11e9-9e0f-f4e7b8f441f4.PNG)
![custom-module-on-save-reopen](https://user-images.githubusercontent.com/28602840/51424004-128ab480-1bc8-11e9-8d70-9ed70eeefa91.PNG)

**Comment by mino182** [comment]
Thanks for trying to help, yes in backend it works, my issue is in front end (as in name of issue). And  for clarification I mean create new module like "mod_something", no another instance of mod_custom via module manager.

**Comment by infograf768** [comment]
Could you add here a zip of your new module? I may have an idea but first need to check your code.

**Comment by mino182** [comment]
[mod_customadv.zip](https://github.com/joomla/joomla-cms/files/2775465/mod_customadv.zip)

Thanks.

**Comment by infograf768** [comment]
Would you use this module only for your needs or do you want to distribute it?

**Comment by mino182** [comment]
Only for my needs...

**Comment by infograf768** [comment]
In that case, it is very easy.
For now, create an override in the html folder of your template.
![screen shot 2019-01-20 at 10 40 21](https://user-images.githubusercontent.com/869724/51437529-d6c31e00-1c9f-11e9-86f1-deab5d6e858c.png)
`default.php` is a copy of `/components/com_config/view/modules/tmpl/default.php`

In that file, modify line 18
from
`$hasContent = empty($this->item['module']) || $this->item['module'] === 'custom' || $this->item['module'] === 'mod_custom';`
to
`$hasContent = empty($this->item['module']) || $this->item['module'] === 'custom' || $this->item['module'] === 'mod_custom' || $this->item['module'] === 'mod_customadv';`

And that will work.
It does not solve the issue globally for any module of that type without this override, but I am still looking into this.

**Comment by mino182** [comment]
Thanks, I actually use this sollution, but if there will be some upgrade in com_config, I will not get it, or I will need to check changes on every update... So this is reason why I open issue, that maybe someone come with better sollution for module type check...

**Comment by infograf768** [comment]
Can you try to replace `/components/com_config/view/modules/tmpl/default.php`
by this file
[default.php.zip](https://github.com/joomla/joomla-cms/files/2776512/default.php.zip)

**Comment by mino182** [comment]
It works. Thanks. Will it be in next release?

**Comment by infograf768** [comment]
I will propose a PR for it and, after being tested, maintainers will decide if/when it is included.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/23604
Closing Issue as we have a patch.

**Comment by infograf768** [comment]
@mino182 
Please mark your test OK in https://issues.joomla.org/tracker/joomla-cms/23604
