### ISSUE TITLE
The publisher's options for the video should be improved.

### ISSUE THREAD

**Issue by ZerooCool** [joomla/joomla-cms#23581]
Is it normal that, by default, the text editor and its add video button do not work?

If I put the link of a youtube video, from the add video button, in the default editor, the wizard will propose 3 tabs. The first tab is used to put the link of the target, the second tab offers a copy code to paste into the HTML.

Still, the HTML will be cleaned, by default, which will prevent the addition of the video.

**Comment by infograf768** [comment]
I guess this is when you use TinyMCe.
Could you post here the exact code you are using and what you get after saving the item (article?) (Link can be a fake one. It does not matter.)

**Comment by ZerooCool** [comment]
You can see this video : http://visionduweb.eu/video.mp4.zip

**Comment by infograf768** [comment]
1. The file is corrupted and can't be read on Macintosh
2. I just need the lines of code used and have no time anyway to read a video and try to pick up what code was used.

**Comment by ZerooCool** [comment]
I do not know for lines of code, this is the insert video icon, in the default text editor.

I guess iframes are removed by default.

Therefore, by default, the insert video icon does not work.

Even if adding a component or a plugin can correct this, I think an improvement is to be made, for the default behavior.

**Comment by infograf768** [comment]
It is very easy to see in the textarea what you have done when inserting the video by just Toggling editor.
Also, TinyMCE parameters can be modified when editing the plugin:
<img width="444" alt="screen shot 2019-01-18 at 17 45 59" src="https://user-images.githubusercontent.com/869724/51400562-0875a100-1b49-11e9-8133-7350cb106c1f.png">
<img width="376" alt="screen shot 2019-01-18 at 17 45 53" src="https://user-images.githubusercontent.com/869724/51400563-090e3780-1b49-11e9-8af2-762544375250.png">

If iframe is the culprit, then just allow it for superusers

**Comment by ZerooCool** [comment]
This HTML code of the icon?

<div id="mceu_32" class="mce-widget mce-btn mce-btn-small" tabindex="-1" aria-labelledby="mceu_32" role="button" aria-label="Insert/edit media"><button role="presentation" type="button" tabindex="-1"><i class="mce-ico mce-i-media"></i></button></div>

Ok yes the plugin can manage but, my point is to improve the use of Joomla, by default.

Off, if we propose a video icon in Joomla, the icon must be functional, without requiring settings in the plugins.

That's why you have to pre-set this, if possible, for the user, allowing iframes directly.

Otherwise, delete this video element.

I do not know if it's feasible simply, and easy to maintain, but it would be better for the end user.

**Comment by Bakual** [comment]
Please use the forum (forum.joomla.org) for support requests. This is the issue tracker for bus in core code. Thanks.

**Comment by ZerooCool** [comment]
I voluntarily posted here, because, I think that just to propose an icon in the core Joomla, via its editor, which does not work by default, is not a relevant choice.

**Comment by Bakual** [comment]
Just because it by default doesn't work with Youtube (because they use iframes) doesn't mean the media button is broken by default. It works for all kind of inserts that don't use iframes.
Allowing iframes by default would be a very bad idea.
So if you want to allow that for your authors/users, it has to be an informed choice of you as administrator.
