### ISSUE TITLE
[4.0] Tags broken in articles, menues

### ISSUE THREAD

**Issue by Duddy67** [joomla/joomla-cms#23589]
### Steps to reproduce the issue
- Create one or more tags in the Tags component.
- Go to the Content component 
- Edit an article. 
- Select tags 

### Expected result
Get a tag list when clicking into the article Tags field.

### Actual result
Get a "No results match" message.

### System information (as much as possible)
Joomla 4 alpha 7 (nightly build 19/01/2019)
DB mysql 5.7.24
PHP 7.2.10
Apache 2.4.29
![tag_list_issue](https://user-images.githubusercontent.com/19156036/51424231-5fbc5580-1bcb-11e9-8641-230342936175.png)

**Comment by ElephantInTheRoomFirst** [comment]
Thanks 
I have tested in 19 Jan nightly build.

1. Tags do not appear below when no text is typed. 
2. The added added tags (in com_tag directly) does appear when some text from tage title typed in tags box. That is little bit tricky and can be improved.
3. After typing tag search string, the created tags does show up but cannot be added even after clicking on that.

**Comment by ghazal** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23589">issues.joomla.org/tracker/joomla-cms/23589</a>.</sub>

**Comment by puneeth-chanda** [comment]
@Ninja-007 Issue confirmed but one more thing when some part of the title is typed in the tag box it is suggesting but on clicking it is not getting selected.

**Comment by Hackwar** [comment]
The problem is "your setup" (not really). You seem to be using MariaDB and that returns integers as, surprise, integers. The JS script however expects strings and thus fails when you click on the item. I've fixed that in my attempts of rewriting the tagging system to something sane. I will need some more time to get it done.

**Comment by Duddy67** [comment]
Thanks for your work.
> You seem to be using MariaDB 

Not at all. As mentioned in my post above I use MySQL 5.7.24.
But may be in this version MySQL returns integers as integers too.

**Comment by SharkyKZ** [comment]
Duplicate #25759. You now have to enter a search term for tags to appear. I think it would make sense to have an option to disable this requirement.

**Comment by SharkyKZ** [comment]
Actually that's already possible. In Tag component options set `Tag Entry Mode` to Nested.

**Comment by SharkyKZ** [comment]
Closing as expected behavior.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23589">issues.joomla.org/tracker/joomla-cms/23589</a>.</sub>
