### ISSUE TITLE
A js file is fully written in one single line and it is difficult to understand.

### ISSUE THREAD

**Issue by puneeth-chanda** [joomla/joomla-cms#23596]
### difficult to understand the code

###Beauitify

**Comment by ElephantInTheRoomFirst** [comment]
Sorry, I did not understand the issue. Please add version of Joomla. 
Minimised JS is beneficial. You may read the benefits here. 
https://stackoverflow.com/questions/31690045/what-are-the-advantages-of-minified-javascript-code

**Comment by puneeth-chanda** [comment]
Ohh sorry I don't know about it, anyway thanks for letting me know, I am closing this issue

**Comment by roland-d** [comment]
@puneeth2001 Just FYI, if you enable debug mode in Joomla, you will get the readable versions of the files.
