### ISSUE TITLE
[4.0] Administrator login page is rendered from error page

### ISSUE THREAD

**Issue by roland-d** [joomla/joomla-cms#23598]
### Steps to reproduce the issue
1. Enable the Debug System in Global configuration
2. Logout
3. Check the browser console window and notice JavaScript errors because jQuery is not loaded

Debugging this issue I found out that:
1. Script tags are placed in the body instead of the head
2. The admin page is rendered from the error page handler

This is caused because this line of code in the `libraries/src/Application/CMSApplication.php` file:
`$uri = clone Uri::getInstance();`

gets a value of:
`http://joomlacms.test/media/vendor/css-vars-ponyfill/js/css-vars-ponyfill.js.map`

The router can't find a route for this and throws an exception.

### Expected result
Debug bar is displayed when enabled and page is rendered using the regular page renderer.

### Actual result
No debug bar is displayed and the page is rendered using the error page renderer.

### System information (as much as possible)
Joomla 4.0-dev branch
PHP 7.2 / PHP 7.3
MySQL 5.7

**Comment by dgrammatiko** [comment]
> Check the browser console window and notice JavaScript errors because jQuery is not loaded

If DebugBar is depending on jQuery then it should make sure it's loaded. The templates **should not force** jQuery.

> Script tags are placed in the body instead of the head

This is intended. Actually if devs were more aware of the benefits of having the scripts before the body closing tags the product will be so much more performant...


In sort add: `HTMLHelper::_('jquery.framework')` in the debugBar layouts...

**Comment by roland-d** [comment]
@dgrammatiko 
> In sort add: HTMLHelper::_('jquery.framework') in the debugBar layouts...

Too good to be true, it isn't that easy otherwise I would have done so already.

This line removes jQuery again:
https://github.com/joomla/joomla-cms/blob/9c229a28001b5dd98082e464175a3abdaeda5546/plugins/system/debug/debug.php#L291

If you remove that line, jQuery is added twice. Regardless of that, this code is placed in the head and Joomla is placing JS files at the end, so jQuery is loaded too late.

All I can see for now is that we do remove that line and then remove the debugbar jQuery from the output.

@elkuku Any ideas here?

**Comment by mbabker** [comment]
The line you linked disables the jQuery library shipped with the DebugBar package, that has no affect on jQuery loaded through the HTML or Document APIs.

**Comment by dgrammatiko** [comment]
> This line removes jQuery again:

So after the line add the Joomla's HTMLHelper for loading the jQuery. That should do the trick!

Edit: I just saw that this is using the assets manager and quite honestly I have no clue, still HTMLHelper **should** work but it's not the right way to mix different methods

**Comment by dgrammatiko** [comment]
@roland-d so I figure out why this is breaking. In all the files in the dir: `plugins/system/debug/DataCollector/InfoCollector.php` the assets are handled by the DebugBar. That's wrong, we need to use Joomla's API to ensure consistency. So 
https://github.com/joomla/joomla-cms/blob/d0c00c50822d69730d2b1c4ee6e4315bf8adc0b5/plugins/system/debug/DataCollector/InfoCollector.php#L90-L106
this needs to return an empty array but the function needs to use HTMLHelper to load the js and css. Also since we're here we need to place the actual files in a js/ and css/ folder so we can use the `('relative' => true)` and also set the media version to auto.

That should do it

**Comment by dgrammatiko** [comment]
@roland-d check #23637

**Comment by Fedik** [comment]
that because someone put `<jdoc:include type="scripts"/>` at bottom of the login layout, with a hope that everything will be fine, but it is not :smirk: 

please test #23639

**Comment by Fedik** [comment]
ah, cache hahaha
@dgrammatiko was faster, I close mine

**Comment by roland-d** [comment]
@dgrammatiko Thank you 🙇  This works.

@Fedik Can you test #23639  as well?

Closing this as we have a PR.
