### ISSUE TITLE
J4 Missing language strings in admin menu

### ISSUE THREAD

**Issue by DonaldTrump88** [joomla/joomla-cms#23602]
### Steps to reproduce the issue
Install and see left hand menus in extensions.
Start Joomla in debug mode. It will show untranslated strings.

Following strings are not translated. 
MOD_MENU_INSTALLER_SUBMENU_INSTALL	
MOD_MENU_INSTALLER_SUBMENU_DISCOVER
MOD_MENU_INSTALLER_SUBMENU_LANGUAGES
MOD_MENU_EXTENSIONS_MODULE_MANAGER
MOD_MENU_COM_TEMPLATES_SUBMENU_STYLES
MOD_MENU_COM_TEMPLATES_SUBMENU_TEMPLATES
MOD_MENU_EXTENSIONS_TEMPLATE_MANAGER

The strings come from administrator\language\en-GB\en-GB.mod_menu.ini

The 3.9.2 has the strings. J4 does not have. 

### Expected result
The translated string values should be in language file.

### Actual result
The strings are not translated.

### System information (as much as possible)
20 Jan 2019 nightly build.

**Comment by infograf768** [comment]
These strings are normally used when creating a custom administrator Menu and using modern.xml to populate the Menu.
At this stage the whole functionality is totally broken in 4.0.
It is likely that modern.xml will anyway be modified to fit the new admin menu system.

BTW: I have no idea how you managed to show these as untranslated by using debug lang as the functionality is dead fish.
`Install and see left hand menus in extensions.`
Which precise page is that? post url please.

**Comment by ElephantInTheRoomFirst** [comment]
@infograf768 
I had installed the alpha build somewhere in Dec. Till yesterday, I was doing nightly build update. Even after update the menus where present and untranslated.
Yesterday I installed from fresh build the menu has disappeared. 

But untranslated strings are still present. When I go in different menus, the untranslated strings appear. 
I feel that, I should test this little later when J4 becomes stable enough.

**Comment by infograf768** [comment]
> But untranslated strings are still present. When I go in different menus, the untranslated strings appear.

We may have still untranslated strings in general, but do you still get these in debug lang is the question.

**Comment by ElephantInTheRoomFirst** [comment]
Yes, I see the untranslated strings but not in the left hand menu.

**Comment by infograf768** [comment]
I am asking you on which page? URL ?

**Comment by infograf768** [comment]
I mean for the strings you quote originally.

**Comment by ElephantInTheRoomFirst** [comment]
No, they are not.

**Comment by infograf768** [comment]
Let's close this then and see what happens when custom admin menus creation is corrected.
