### ISSUE TITLE
[4.0] admin Template language file does not get loaded/missing

### ISSUE THREAD

**Issue by DonaldTrump88** [joomla/joomla-cms#23601]
### What needs to be fixed
Template language file does not get loaded.

The file is present in administrator\templates\atum\language\en-GB\en-GB.tpl_atum.ini
J4 searches in /administrator/language/en-GB/en-GB.tpl_atum.ini

Build: 20 Jan nightly build
### How would you fix it
Add the language file copy code.

**Comment by ReLater** [comment]
Maybe related? https://github.com/joomla/joomla-cms/issues/23489

**Comment by ElephantInTheRoomFirst** [comment]
Thanks @ReLater The issue is about frontend.
My raised issue is about admin template.

**Comment by ReLater** [comment]
Maybe I misunderstand your description.

The priority of language files is the same in backend. First search in administrator/language/. Only if file not found then search in template folder.

Did you delete the files in administrator/language/ ? If yes and the language files from template folder are not loaded then that's a bug.

**Comment by ElephantInTheRoomFirst** [comment]
I did not delete any language file.

**Comment by infograf768** [comment]
it works fine on dev branch. please set debug language on in global config. Post here a screenshot of the loaded language files from debug

**Comment by ElephantInTheRoomFirst** [comment]
![unable-to-load-template-lang-file](https://user-images.githubusercontent.com/28602840/51489945-0eb68800-1daa-11e9-9ce9-9190b54627a1.PNG)

**Comment by brianteeman** [comment]
There is something wrong with your install. There is nothing that should be loading fof30. Probably explains your other issues as well

**Comment by ElephantInTheRoomFirst** [comment]
fof30 comes from akeeba backup, I believe.

**Comment by infograf768** [comment]
In any case, the atum language file IS loaded from atum language folder and everything looks translated at looking at your screenshot.
Can you close the issue?

**Comment by ElephantInTheRoomFirst** [comment]
Let me reinstall J4 from fresh build and verifiy the issue. Hopefully, it will be resolved.

**Comment by ElephantInTheRoomFirst** [comment]
This is fresh install of today nightly build. 
* Just installed
* Enabled debug 
* Took screenshot

Am I only facing the problem? 

![unable-to-load-template-lang-file-21-jan-build](https://user-images.githubusercontent.com/28602840/51492865-8b9a2f80-1db3-11e9-8c9f-22b7bfc7b171.PNG)

**Comment by mbabker** [comment]
What is the issue you are aiming to address?

The core lookup pattern is to search in `/administrator/language` for a language file, then the extension if a file is not found in the `administrator/language` directory (so in this case, `/administrator/templates/atum/language`).  So you will always have a missing file in that list for any extension which does not place their files in the `/administrator/language` or `/language` directories.  Callers to `$language->load()` aren't checking if a file exists first, the Language API is doing that check.

If you're attempting to report that the Atum language files do not exist in the `administrator/language` directory, then you are correct that is an inconsistency in the current code base.

**Comment by ElephantInTheRoomFirst** [comment]
Well if the template language file is only supposed to be in /administrator/template/atum/language folder then it is not an issue. 
My understanding is /administrator/template/atum/language fallback path and /administrator/language primary path. As J4 has one admin template, may it will be better if we place the language file in /administrator/language path or stop searching there.

**Comment by ElephantInTheRoomFirst** [comment]
If the inconsistency is acceptable and by design then you may close the issue.

**Comment by mbabker** [comment]
> As J4 has one admin template, may it will be better if we place the language file in /administrator/language path or stop searching there.

The core behavior for all extensions is to first search the application's global language directory `/administrator/language` for the admin app, `/language` for the site app, `/installation/language` for the install app if it were to ever support the notion of extensions) then to search in the extension for a language directory (so `/templates/<foo>/language` for a frontend template, `/administrator/components/<foo>/language` for a backend component).  The first search is ALWAYS performed and the second search is ONLY performed if the first search does not find a file to be processed.

So, for any extension (not just those in the core package) which does NOT place their language files in the global language directory, there will always be a line like the one you are highlighting.  That is the system design.

**Comment by infograf768** [comment]
The lang files, for core templates, should be in both places.
In core folders as they have to be translated and present in the TTs lang packs. And also in the templates language folder as the templates can be copied and the code needs the lang files there.

**Comment by ReLater** [comment]
So we're landing here: https://github.com/joomla/joomla-cms/pull/23493#issuecomment-453001068

and this issue is one because the files are missing.

As long as it will not become a must to use the core language folder in custom templates and copying them will still function as usual I can live with any solution ;-)

**Comment by infograf768** [comment]
@ReLater 

@Bakual and myself looked at the way template copy works. We found that it is the the template folder as a whole which is copied, and then some modifications for some files ($newName).

Nowhere during that copy are language files copied separately, which means we can't have a conditional which would look first in a place (the template folder) and then in the corresponding core folder.

Code is here:
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_templates/Model/TemplateModel.php#L732

This means we need to patch the model code in order to also look in the core folder IF no language files are found in the template/language/ folder and if it is the case, copy the files found to the copied template/language/ temp folder before returning `fixTemplateName`

**Comment by brianteeman** [comment]
This should be closed as the reported issue is not a bug but by design.  All the off topic comments should be continued in #23493
