### ISSUE TITLE
Batch not possible for chosen menu items

### ISSUE THREAD

**Issue by kofaysi** [joomla/joomla-cms#23615]
### Steps to reproduce the issue

Choose some menu items and try batch process them.

### Expected result

A modal windows opens where batch commands are available.

### Actual result

Error appears:
**Batch process the selected menu items**
To use batch processing, please first select a Menu in the manager.
https://screenshots.firefox.com/vt35JKsQ2nteaAdA/svjsvetova523-1.cz

### System information (as much as possible)

J3.9.2

**Comment by ReLater** [comment]
That's the expected message/behavior. You have to select a **menu** via filter settings first. If you're in the view "All menu items (of all menus)" you can't start batch processes.

**Comment by simbus82** [comment]
For me it is not a bug. You can't do a batch if you don't pre-select a "menu", otherwise you could not copy or move hierarchies of menu items respecting "parent-child" tree

**Comment by kofaysi** [comment]
I totally didn't expect that behaviour. I wanted to change access levels. I understand your argument (moving branches).

**Comment by kofaysi** [comment]
Additionally, I think it is a confusing term "the manager". I have selected two, four, all menu items, and the behaviour was the same.

**Comment by infograf768** [comment]
As told above, make sure you first filter by a menu, then use batch with the displayed menu items.
Closing as not a bug.

**Comment by kofaysi** [comment]
From the previous messages, I learned that I should select a menu. And I don't want to argue about the sense of it. But I want to point out that it is hard to decrypt the warning, because something else lead me that wrong way:

In case when no menu is selected and no menu item is selected, the Batch command issues a warning "Please first make a selection from the list". Both Site and Administrator. That is clearly a message to select items by checkmarking them. But checkmarking them wont't help, because: The warning differs from the one, when no menu is selected, but some menu item(s) is/are selected:  "To use batch processing, please first select a Menu in the manager". The warning "Please first make a selection from the list" is confusing and should be changed to the same as "To use batch processing, please first select a Menu in the manager".

**Comment by kofaysi** [comment]
And now I wish to give an argument against the timing of the warning. Does batch processing Language and Access level for menu items of different menus make sense? If it does (and it makes sense to me), then it would be much clearer to issue a warning next to the move/copy batch command, or after it was not possible to execute. In the Batch commands selection list, it could be a red warning "No menu selected. Please select menu." and disabling that particular batch move/copy command.
