### ISSUE TITLE
[4.0] Workflows no working

### ISSUE THREAD

**Issue by lllopo** [joomla/joomla-cms#23612]
### Steps to reproduce the issue
Click on 'Content > Workflows' in main menu

### Expected result
Workflows page loads

### Actual result
Error : Unknown column 'w.core' in 'field list'

### System information (as much as possible)
Latest alpha 7 nightly (updated through update package), php 7.2x64, MariaDB 10.3x64, Win 10 Pro

**Comment by infograf768** [comment]
Most likely due to the use of update.
I can't reproduce this on clean 4.0-dev branch.

**Comment by lllopo** [comment]
> Most likely due to the use of update.
> I can't reproduce this on clean 4.0-dev branch.

Yup, possible. That's why I explicitly mentioned it. Will try with a clean install then and come back to you.

**Comment by lllopo** [comment]
Confirmed. Works fine with a fresh install. Closing.
