### ISSUE TITLE
Properties set by BaseDatabaseModel->setState() gets overwritten after a call to getState()

### ISSUE THREAD

**Issue by horvathcsabazoltan** [joomla/joomla-cms#23611]
### Steps to reproduce the issue
```
// I used a ListModel in the display() of a HtmlView. 
$model = $this->getModel('mymodelname'); 

$model->setState('list.limit', '0');

// returns the default setting instead of the value I set on previous line
$listLimit = $model->getState('list.limit'); 
```

### Expected result
`$listLimit` should be 0

### Actual result
`$listLimit` is the default setting

### System information (as much as possible)
Joomla 3.8.12 on XAMPP (Windows 10)
The same behavior is suspected in newer versions on any platform

### Additional comments
I guess the `setState()` method shouold call `populateState()` if internal state is not set - just like in `getState()`. 

I don't want to overwrite the default setting by overwriting the model's `populateState()`, because I needed all the items from the model in this view only.

**Comment by SharkyKZ** [comment]
You have a syntax error (missing quote):
```
$model->setState('list.limit, '0');
```
And you have to pass the property name (`list.limit`) to `getState()`:
```
$listLimit = $model->getState('list.limit'); 
```

**Comment by horvathcsabazoltan** [comment]
I've edited my comment, so these errors are gone. Thanks @SharkyKZ for pointing it out.

**Comment by SharkyKZ** [comment]
Does your issue still remain?

**Comment by horvathcsabazoltan** [comment]
Yes. I did not copy the code, I typed it in here. My original code did not contain these typos. Sorry for that.

**Comment by ReLater** [comment]
> Joomla 3.8.12 on XAMPP 

The current Joomla version is 3.9.2. You should update you're Joomla and test again.

**Comment by horvathcsabazoltan** [comment]
I've updated to Joomla 3.9.2 but the problem is still there.

Sorry for the delay.

**Comment by ghost** [comment]
@HLeithner  can you please comment?

**Comment by HLeithner** [comment]
If the Model is new you have to first get the State and then you can change the state, don't ask me why thats Joomla behavior.

simple make ```$model->getState();``` before you make the setState call

**Comment by ghost** [comment]
Closed as Solution provided above. Please reopen if i misunderstood.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23611">issues.joomla.org/tracker/joomla-cms/23611</a>.</sub>
