### ISSUE TITLE
Template Style Chooser gone after upgrade to 3.9.2

### ISSUE THREAD

**Issue by pAnd0rASBG** [joomla/joomla-cms#23614]
### Steps to reproduce the issue
Open any Menu item, try to assign Template Style from Dropdown as used to be.

### Expected result
To have the Template Style Dropdown
![screen shot 2019-01-21 at 10 31 13](https://issues.joomla.org/uploads/1/002cd236cf042c7dca9edc16ab07f741.png)

### Actual result
Template Style Dropdown is gone
![screen shot 2019-01-21 at 10 31 23](https://issues.joomla.org/uploads/1/3d3cc6a216601a6b2be978bfca8a043f.png)

### System information (as much as possible)
Not System specific - happened on all our sites with the 3.9.2 Update.

### Additional comments
Please fix, all our content editors are trained to use it, so it breaks their workflow :smile:

**Comment by jeckodevelopment** [comment]
Hello,
it has been fixed by https://github.com/joomla/joomla-cms/pull/23556
The fix will be included in Joomla 3.9.3 (released in February).

There is also a page of Documentation that suggests how to apply a workaround: https://docs.joomla.org/J3.x:Template_Style_field_not_shown_in_Menu_Items
