### ISSUE TITLE
Protostar - please add Google font for body setting to template style manager

### ISSUE THREAD

**Issue by janwychowaniak** [joomla/joomla-cms#23618]
The style manager for the Protostar template allows for setting "_Google font for headings_", which I find very convenient. But I also need to be able to set Google font for body of articles in a corresponding fashion, a feature that in my opinion is a logical compliment to the former. In other words,
"_Google font for headings_" allows setting font for **h1, h2, h3, h4, h5, h6 and .site-title**, afaik.
I would need something analogous for setting font for **body**.
Can you please add it as well?
Thank you.
![screen shot 2019-01-21 at 23 47 22](https://issues.joomla.org/uploads/1/ad58ef2e2b97eba042a6af058d17ad47.jpg)

**Comment by ghost** [comment]
@zero-24 can you please comment?

**Comment by zero-24** [comment]
What kind of comment? @franz-wohlkoenig ? :D

**Comment by ghost** [comment]
If this is something to discuss or close.

**Comment by janwychowaniak** [comment]
In the meantime, I have found an interesting article that might provide a suggestion on how to implement this in imho a relatively elegant and flexible way. I hope this proves helpful in resolving the issue. [> link <](https://www.byman.it/site/index.php?option=com_content&view=article&id=251:protostar-google-font-body&catid=39&Itemid=154)

**Comment by ghost** [comment]
it's about having the correct Solution and also a Volunteer having Time and Interest to do a Pull Request, having two successfully Tests, ...

**Comment by infograf768** [comment]
Although it is pretty easy to implement (patch would take a few minutes only, and not exactly as described in that link which dates back from 2014), it depends on the decision of @HLeithner as this can be done as a simple change in a copy of protostar.

**Comment by ghost** [comment]
Theres also the Opinion to do new Features only against J4.

**Comment by infograf768** [comment]
I would not consider this as a real new feature as it concerns only Protostar which is not used in 4.0 ;)

**Comment by Bakual** [comment]
Technically it's still a new feature 😄

**Comment by infograf768** [comment]
Not wrong. 😺

**Comment by ghost** [comment]
@HLeithner Release Lead decide :-)

**Comment by HLeithner** [comment]
Is this really useful? Doesn't a custom.css does the same in 3 lines?
But I will merge it if its only a small addition because it doesn't effect merging into 4.0 (because it doesn't exists in j4)

You have to find someone that could write a PR

**Comment by alikon** [comment]
closing as it is a new feature on protostar and new feature must go on 4.x and 4.x don't have protostar<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23618">issues.joomla.org/tracker/joomla-cms/23618</a>.</sub>
