### ISSUE TITLE
[4.0]  [com_menus] An error has occurred

### ISSUE THREAD

**Issue by amitranjan2** [joomla/joomla-cms#23610]
## Steps to reproduce the issue
Navigate to the following page from the admin page
Menus >> Main Menu >> Home

## Expected result
After clicking on Close, it should goes on Home 

## Actual result
After clicking on Close it throws error 
Call to undefined method Joomla\Component\Menus\Administrator\Model\ItemModel::getColumnAlias()

**Comment by ElephantInTheRoomFirst** [comment]
Sorry, I could not reproduce the issue in 20 Jan nightly  build.
Which build are you using?
