### ISSUE TITLE
[4.0] Error when trying to save new article

### ISSUE THREAD

**Issue by amitranjan2** [joomla/joomla-cms#23617]
### Steps to reproduce the issue

Navigate to the following page from the admin page
content >> Articles >> New
add some contents and try to save 

### Expected result
A new article should be saved

### Actual result
it throws an error
Save failed with the following error: Incorrect integer value: '' for column 'hits' at row 1

**Comment by ghazal** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23617">issues.joomla.org/tracker/joomla-cms/23617</a>.</sub>

**Comment by infograf768** [comment]
Also confirmed here.

**Comment by infograf768** [comment]
@alikon ?

**Comment by infograf768** [comment]
I solved this here by adding
`			$data['hits'] = 0;`
line 922 of `/administrator/components/com_content/Model/ArticleModel.php`
but I think this is just a hack as default hits is set as 0 is db.

**Comment by alikon** [comment]
hmmm... see #23638...

**Comment by jeremysmartin399** [comment]
I get the same issue when saving articles on Joomla 4, alpha 7 with the trial account with cloud access. Receive "Error
Save failed with the following error: Incorrect integer value: '' for column 'hits' at row 1".

I get the same message when adding to the contacts component as well.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23617">issues.joomla.org/tracker/joomla-cms/23617</a>.</sub>

**Comment by infograf768** [comment]
Joomla4, alpha7 does not contain https://github.com/joomla/joomla-cms/pull/23638

Confirmed for Contact. Will make patch for that one.

**Comment by infograf768** [comment]
For contact, please test https://github.com/joomla/joomla-cms/pull/23688

**Comment by Leen29** [comment]
I get the same issue when saving articles on Joomla 4, alpha 7 with the wamp server <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23617">issues.joomla.org/tracker/joomla-cms/23617</a>.</sub>
