### ISSUE TITLE
Should we consider adding a URL in Help menu of administration section to the license file?

### ISSUE THREAD

**Issue by artur-stepien** [joomla/joomla-cms#23621]
### Expected result
Added a link to the Help menu in administration section pointing to License file or a native language license page (eg. the one from http://gnu.org.pl)

### Actual result
No information about license in any visible part of admin section

### System information (as much as possible)
3.9

### Additional comments
It would be nice to have a clear conscience. As I remember license orders you to deliver copy of the license to the end user. The license file is in the files but which client does know how to get there? Not to mention to even be aware of the fact that the license is out there. If there would be a license link in administration panel that would take at least one worry from the developer. Help menu is easily accessible and single URL doesn't waste much space.

**Comment by ghost** [comment]
@HLeithner  can you please comment?

**Comment by HLeithner** [comment]
@yvesh is Legal DC, may he can answer this better.

**Comment by brianteeman** [comment]
The link is already present in both joomla 3 and joomla 4

![image](https://user-images.githubusercontent.com/1296369/53730946-3c92f000-3e71-11e9-8e3f-5e3ecc89498b.png)

![image](https://user-images.githubusercontent.com/1296369/53730981-4fa5c000-3e71-11e9-8c48-799f68a1078f.png)

**Comment by ghost** [comment]
closed following above Comment, thanks @brianteeman <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23621">issues.joomla.org/tracker/joomla-cms/23621</a>.</sub>

**Comment by artur-stepien** [comment]
It was about adding it to the Help menu not keeping in a hidden section where 99% of users doesn't even look. In Polish for example the Help articles are non-existing therefore no one looks there at all. So the non-working help section has the direct link but the license doesn't.
