### ISSUE TITLE
[4.0] Title field for new article is same length as Allias

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23626]
### Steps to reproduce the issue

Go to create a new article, menu item, etc..
You'll notice that the "Title" input is the same length as the "Alias" input below.

### Expected result

The "Title" input should be longer which it used to be in an earlier state of J4

### Actual result

Same length

**Comment by dgrammatiko** [comment]
Fields should always have a 100% width setting width in 240px or whatever is not very responsive and also is a huge anti pattern. Mobile first...
Also the div soup around the label and the input is totally crap and needs to go...

**Comment by infograf768** [comment]
+1

**Comment by hardik-codes** [comment]
Does this issue needs to be addressed @dgrammatiko and @infograf768

**Comment by dgrammatiko** [comment]
> The "Title" input should be longer which it used to be in an earlier state of J4

Why the distinction? For what is worth **all** inputs should have a width 100% and the container div will act as the upper hard limit...

**Comment by C-Lodder** [comment]
@dgrammatiko I believe it was requested by some users as it was a more meaningful field.

**Comment by hardik-codes** [comment]
@C-Lodder does this issue needs to be taken forward ?

**Comment by C-Lodder** [comment]
Not sure really. Im just basing this on J3 and an earlier state of J4.

@coolcat-creations will be able to give her feedback

**Comment by hardik-codes** [comment]
@C-Lodder how do I contact @coolcat-creations regarding this?

**Comment by C-Lodder** [comment]
She'll get a notification with the above tags

**Comment by coolcat-creations** [comment]
I agree to @dgrammatiko - about the length. Thanks for following up. Can anyone take care of this issue?

**Comment by hardik-codes** [comment]
Yes I'm in @coolcat-creations . Please specify what exactly are the changes to be made

**Comment by infograf768** [comment]
There are 2 places to look at:
For the extra div
`/layouts/joomla/edit/title_alias.php`

I just modified it here to
```
<?php
/**
 * @package     Joomla.Site
 * @subpackage  Layout
 *
 * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('JPATH_BASE') or die;

$form  = $displayData->getForm();

$title = $form->getField('title') ? 'title' : ($form->getField('name') ? 'name' : '');

echo $title ? $form->renderField($title) : '';
echo $form->renderField('alias');
```
for the css:
changes to be done in `/administrator/templates/atum/scss/blocks/_form.scss`
```
.form-control {
  max-width: $input-max-width;
  background-color: var(--white-offset);
}
```
This css override default bootstrap 100% for this class.
Not sure if we should delete the max-width or set it to 100% or none.
All depends on what we do finally about bootstrap...

**Comment by infograf768** [comment]
@coolcat-creations 
What do you think?

**Comment by hardik-codes** [comment]
On changing the ```max-width: $input-max-width;``` the width of both title filed and alias field change simultaneously.

**Comment by ghost** [comment]
Reminder at @coolcat-creations for above Comment by @infograf768 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23626">issues.joomla.org/tracker/joomla-cms/23626</a>.</sub>

**Comment by coolcat-creations** [comment]
Please see this screen: https://coolcat-creations.com/joomla/#/screens/267320995
But take Dimitris suggestion into account that both fields have 50% in Desktop and 100% width in Mobile.
