### ISSUE TITLE
[4.0] JS error when closing a list view

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23629]
### Steps to reproduce
Go to:

1. System
2. Site Modules
3. Open any module
4. Click the "Close" button in the toolbar

### Result

> TypeError: window.parent.Joomla.Modal.getCurrent(...) is undefined in admin-module-edit.min.js

**Comment by infograf768** [comment]
Confirmed. We still get redirected to the Modules Manager though.

**Comment by dgrammatiko** [comment]
https://github.com/joomla/joomla-cms/issues/23629

**Comment by infograf768** [comment]
You mean https://github.com/joomla/joomla-cms/pull/23642
closing as we have a patch
