### ISSUE TITLE
[4.0] Global Config Permissions inconsistent widths

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23627]
### Steps to reproduce the issue

Go to the "Permissions" tab in Global Configuration

You'll notice:

1. The container doesn't use 100% width
2. Too many `row` classes are being used, meaning there's a negative margin of `7.5px` and the containers aren't aligned

**Comment by hardik-codes** [comment]
@C-Lodder could you help me with the file for the changes?

**Comment by infograf768** [comment]
Closing as we have a patch
https://github.com/joomla/joomla-cms/pull/23687

**Comment by hardik-codes** [comment]
@amitranjan2 at least you should first ensure if someone is working on that issue or not, before submitting PR for the same

**Comment by amitranjan2** [comment]
@hardik-codes I have been working on this issue since the opening of this issue if someone is not asking about the file for the changes, it does not mean that nobody is working on this issue.
I hope, you got my point

**Comment by hardik-codes** [comment]
@amitranjan2 But at least you should have initiated any kind of activity on that issue, letting others in the community to know that you are working on it

**Comment by C-Lodder** [comment]
@infograf768 please reopen as the PR only fixes 1 of 2 issues. The width still needs to be 100%

**Comment by C-Lodder** [comment]
Closing #23687
