### ISSUE TITLE
Wrong display module in preview article (blog view)

### ISSUE THREAD

**Issue by uruk-hai-21** [joomla/joomla-cms#23622]
Hi,
if I load a module in preview article content, it is shown correctly in category blog view but looking at souce code there is an error (view example of source code).

**Example**:

**Content of article**:
```
{loadmoduleid 110}
<hr id="system-readmore" />
{loadmoduleid 102}
```

**Category blog view page**:
![](https://i.ibb.co/bBfKYZR/Schermata-2019-01-22-alle-11-51-25.png "")

**Page source**:
![](https://i.ibb.co/RYfKtTb/Schermata-2019-01-22-alle-11-52-06.png "")

Why?

**Comment by ghost** [comment]
closed, Please ask on [Forum](https://forum.joomla.org/). You can always reopen if needed.
