### ISSUE TITLE
[4.0] Two different design styles for tabs

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23625]
### Steps to reproduce the issue

Visit:

- (New Menu Item) -- `/administrator/index.php?option=com_menus&view=item&client_id=0&menutype=mainmenu&layout=edit`
- (Global Config) -- `/administrator/index.php?option=com_config`

### Expected result

A consistent design

### Actual result

An inconsistent design

**Comment by ciar4n** [comment]
I believe one uses custom element tabs while the other is using bootstrap tabs. At the time there was no answer on if we maintain two sets of code for similar elements or remove bootstrap tabs. That was about where my involvement ended.

I have no idea what the plans are in the new private template repo.

**Comment by Bakual** [comment]
To my knowledge, there is no private template repo with code in it. Just a private issue tracker.
The code is in form of PRs to this repo.

**Comment by ciar4n** [comment]
> To my knowledge, there is no private template repo with code in it. Just a private issue tracker.
The code is in form of PRs to this repo.

Maybe I am misreading this but it certainly hints towards work been carried out elsewhere... https://volunteers.joomla.org/teams/j4-backend-template-working-group/reports/926-team-setup

If what you say is true then it still seems pointless contributing towards the template in this repo if you are not part of that private tracker. Both myself and Charlie have rewritten this CSS a couple of times already to match whatever design was flavour of the month at the time. Not much need contributing further if it's going to be overruled again by decisions made in private. At least that has been my stance for the last while., wrong as it may be.

**Comment by Bakual** [comment]
My information is from @wilsonge, so I'd say it's accurate. They don't rewrite the template, they do collaborative PRs to improve the existing work.
Further questions would have to be answered by George and @rdeutz.

I just stated this because I think it's perfectly fine to solve issues here as well, outside of that group. So tackling this issue by doing a PR would be appreciated.

**Comment by ciar4n** [comment]
As before there still needs to be a decision on whither 2 sets of CSS are to be maintained for each UI element that is moved to a custom element?

**Comment by C-Lodder** [comment]
PR: #23780
