### ISSUE TITLE
[4.0] User permissions table requires horizontal scroll

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23628]
### Steps to reproduce the issue

Go to `/administrator/index.php?option=com_users&view=debuguser&user_id=704` (change `user_id` to your own)

or:

1. Go to Manage Users
2. Click on the "permissions" icon to view the permissions for that user

You'll see that the table is far too wide, creating a horizontal scroll for the entire page.

**Comment by hardik-codes** [comment]
@C-Lodder what could be the probable solution for this issue. Since the page is having horizontal scroll can it be fixed by fixing the CSS??

**Comment by C-Lodder** [comment]
You'll have to ask the design/template team

**Comment by hardik-codes** [comment]
So the design needs to be changed to accommodate the whole table?

**Comment by hardik-codes** [comment]
@C-Lodder To whom should I reach out to ?

**Comment by C-Lodder** [comment]
@coolcat-creations and @rdeutz

**Comment by hardik-codes** [comment]
@coolcat-creations and @rdeutz please help me out in fixing this issue?

**Comment by coolcat-creations** [comment]
Will have a look into this and give feedback, thanks!

**Comment by hardik-codes** [comment]
ok

**Comment by puneeth-chanda** [comment]
it is ok for me here:![screen shot 2019-02-26 at 12 36 59](https://issues.joomla.org/uploads/1/10500d6dbfddbf6a1c51793d03038846.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23628">issues.joomla.org/tracker/joomla-cms/23628</a>.</sub>

**Comment by ghost** [comment]
closed as this should be reported if the new Design have this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23628">issues.joomla.org/tracker/joomla-cms/23628</a>.</sub>

**Comment by brianteeman** [comment]
Please reopen until the new design solves it

**Comment by ghost** [comment]
reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23628">issues.joomla.org/tracker/joomla-cms/23628</a>.</sub>

**Comment by C-Lodder** [comment]
Closing as template team are working on backend template

**Comment by MartijnMaandag** [comment]
This is still a problem.![screen shot 2020-08-03 at 12 13 36](https://issues.joomla.org/uploads/1/65c002386359d7d4906ecb6cad7e9661.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23628">issues.joomla.org/tracker/joomla-cms/23628</a>.</sub>

**Comment by Quy** [comment]
@MartijnMaandag Please scroll to the bottom of the page.

![23628](https://user-images.githubusercontent.com/368084/89194807-b6df0c80-d55c-11ea-865d-1e1fcc4847f0.png)

**Comment by MartijnMaandag** [comment]
Thanks
I don't think this is clear for somebody on this page.
(Not for me ;-) )

I don't know how to make it more clear.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23628">issues.joomla.org/tracker/joomla-cms/23628</a>.</sub>

**Comment by brianteeman** [comment]
Agree with @MartijnMaandag Please re-open

**Comment by brianteeman** [comment]
Togethetr with 37807 and the new table coumn selector I doubt there is anything further that can be done here

**Comment by rdeutz** [comment]
Agree
