### ISSUE TITLE
[4.0] Wrong alert colours after installing sample data

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23632]
### Steps to reproduce the issue

Install some sample data via the Control Panel

### Expected result

Green alerts

### Actual result

Blue alerts

![screenshot_2019-01-22 control panel - joomla 4 - administration](https://user-images.githubusercontent.com/2019801/51540526-8d650100-1e4e-11e9-9a43-f6709a3a21c8.png)

**Comment by Bakual** [comment]
I think the class is defined here: https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_src/mod_sampledata/js/sampledata-process.es6.js#L62
The rest is CSS.

Is it the wrong class or is the CSS wrong?

**Comment by C-Lodder** [comment]
It's not the CSS that's wrong, it's the `type` attribute:

```
<joomla-alert type="info"></joomla-alert>
```

The `type` should be `success`, not `info`

**Comment by Bakual** [comment]
Ah, then I'm out as I don't know where that comes from. Must be somewhere in the JS stuff.

**Comment by infograf768** [comment]
Also 'success' or 'error' should be translated in the message.

**Comment by hardik-codes** [comment]
@C-Lodder changing the ```type``` attribute from ```info``` to ```success``` in https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/system/stats/layouts/message.php does not work out in my local machine. Are there any more changes to be done apart from the one above ??

**Comment by C-Lodder** [comment]
You'll most likely need to change the JS

**Comment by hardik-codes** [comment]
JS in which file?

**Comment by Bakual** [comment]
The JS file involved is https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_src/mod_sampledata/js/sampledata-process.es6.js
After any modification you need to run the npm commands to compile that thing. Don't ask me details 😄

**Comment by hardik-codes** [comment]
How do I check whether my changes are implemented or not because the Sample data installation process is a single time process and cannot be reverted back??

**Comment by Bakual** [comment]
You can install it as many times as you want. But you need to delete the created categories and items so you don't get an error (because the item already exists).
It also works if you have a backup of the original database that you can restore.

**Comment by hardik-codes** [comment]
@Bakual I deleted all the created categories but it is still giving me the error on install. What's the other way round

**Comment by Bakual** [comment]
Either manually delete all created items (categories, articles, menuitems, ...), use a database backup of a previous state or drop the database tables and do a fresh installation. That's about the variants.

**Comment by infograf768** [comment]
Delete in this order:
First: Menus (that will also delete the menu items). Do not delete the default mainmenu.
Second: Articles
Third: Categories

**Comment by infograf768** [comment]
`https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_src/mod_sampledata/js/sampledata-process.es6.js#L62` imho concerns the progress bar and not the body of the message.

**Comment by infograf768** [comment]
Ok, I have a patch for that. Creating PR now.

**Comment by hardik-codes** [comment]
Patch for which issue? @infograf768

**Comment by infograf768** [comment]
the colour for the background of the messages should be greenish instead of blue. The issue stated by the OP. 
I.e. to obtain
<img width="714" alt="screen shot 2019-01-31 at 11 20 06" src="https://user-images.githubusercontent.com/869724/52047848-35af4f80-254a-11e9-8541-fb19c79d951f.png">

PR ready in a few minutes.

**Comment by hardik-codes** [comment]
May I help with that ?
Please suggest me the changes I'll more than willing to generate the PR asap.

**Comment by infograf768** [comment]
Already done. Please test https://github.com/joomla/joomla-cms/pull/23726
Closing as we have a patch
