### ISSUE TITLE
[4.0] "My Settings" not saving in com_messages

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23635]
### Steps to reproduce the issue

1. Go to `/administrator/index.php?option=com_messages`
2. Click on the "My Settings" button in the toolbar
3. Toggle one of the switchers
4. Click "Save & Close"
5. Click on the "My Settings" button in the toolbar (again)

### Expected result

Settings are saved

### Actual result

Nothing is saved and you'll noticed the switcher is in the same state as it was when you first opened the modal

**Comment by amitranjan2** [comment]
issue confirmed

**Comment by dgrammatiko** [comment]
https://github.com/joomla/joomla-cms/pull/23600

**Comment by C-Lodder** [comment]
Closing for PR
