### ISSUE TITLE
Removing type="text/javascript" from script tags

### ISSUE THREAD

**Issue by artur-stepien** [joomla/joomla-cms#23631]
### Steps to reproduce the issue
Every `<script>` tag in the system has the `type="text/javascript"` attribute, just look in the source

### Expected result
For a Java Script remove the `type` attribute

### System information (as much as possible)
Every system version

### Additional comments
As the `type="text/javascript"` attribute is considered unnecessary in W3C validator maybe we should just remove it for those type of scripts? Why send to the browser something that isn't necessary.

**Comment by C-Lodder** [comment]
It should be removed unless otherwise specified or `$this->setHtml5(true)` has been defined.

Same goes for `type="text/css`

**Comment by mbabker** [comment]
In 3.x, Joomla core defaults to XHTML/HTML4 compliant syntax which uses the `type` attributes.

In 4.0, Joomla core defaults to HTML5 which omits `type` attributes for default types.

This behavior can be toggled with `$this->setHtml5()` as indicated by @C-Lodder.

Closing as this is expected API behavior.
