### ISSUE TITLE
[4.0] Attempting to install sample data twice

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23633]
### Steps to reproduce the issue

1. Install sample data via the backend
2. refresh the page
3. Attempt to install it again

### Expected result

Either:

1. Disable the "Install" button and change the text of it to "Installed"
2. Completely hide the box
3. Display a more appropriate message such as stating they've already installed it

### Actual result

A red alert:

> Step 1 Failed: Another category with the same parent category has the same alias (remember it may be a trashed item).

**Comment by Bakual** [comment]
Doesn't work because we have no way of tracking which sample data is installed. Even if we would track it (in a database), we wouldn't know if the installed sample data still is the original one or if it got deleted or whatever.

The only error we can get is that the category already exists, for whatever reason (sample data already installed or category manually created with same name). And that we do.

**Comment by C-Lodder** [comment]
@Bakual The sample data derives from a plugin, so is it not possible to add custom field to each XML file, for example:

```
<field type="foo" name="blog_sample_data_installed" value="0">
```

and upon installing the sample data, that parameter value be updated to `1`

**Comment by Bakual** [comment]
And what happens if the user removes the sample data manually and wants to install it again?
Or wants to install it twice in different languages (which is perfectly fine and works).

**Comment by Bakual** [comment]
Don't get me wrong. I don't want to shoot this down. But it was discussed already when we introduced this module and we didn't find a solution that would work.

**Comment by C-Lodder** [comment]
@Bakual ah, I was not aware that is could be installed for different languages

**Comment by ghost** [comment]
closed on Base of Comment above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23633">issues.joomla.org/tracker/joomla-cms/23633</a>.</sub>

**Comment by chmst** [comment]
In J4 users get only blog sample data. If the user tries to install again, an appropriate message appears as requested.

> Display a more appropriate message such as stating they've already installed it.

Hopefully we find a better solution for J5

**Comment by brianteeman** [comment]
Actually it is pretty easy to resolve
in the sample data add a step that unpublished the sample data plugin
or
Update the plugin code so that it can be disabled and still published then
in the sample data add a step that disables the install button of the sample data plugin

**Comment by Hackwar** [comment]
I did the modification Brian proposed in #39216. Since you can install blog and multilang sampledata multiple times, I only added this to the testing sampledata. Closing this issue since we have a PR.
