### ISSUE TITLE
[4.0] Help page issues

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23630]
### Steps to reproduce the issue

In the Joomla backend click on "Help", then "Joomla! Help"

### Actual result

1. Untranslated strings
2. Overlapping line just under "Alphabetical Index"

![screenshot_2019-01-22 joomla help - joomla 4 - administration](https://user-images.githubusercontent.com/2019801/51540355-1def1180-1e4e-11e9-903d-927823d0ce1e.png)

**Comment by vijay9908** [comment]
I didn't understand what untranslated strings mean! , and moreover the redirect links are expired!

**Comment by vijay9908** [comment]
<img width="874" alt="screenshot 2019-01-23 at 6 30 06 pm" src="https://user-images.githubusercontent.com/43515280/51608342-2eca8080-1f3d-11e9-8fd9-5e5928eb6fdf.png">
The links referring are expired and showing error! , Do I need to remove the 3 untranslated strings?

**Comment by C-Lodder** [comment]
@vijay9908 Weblinks has been decoupled from Joomla, so I assume these would need to be removed. @brianteeman ?

**Comment by vijay9908** [comment]
The code base for weblink not being a part of core,The issue can't be carried further so!

**Comment by prahladkumarpopuri** [comment]
![screenshot from 2019-01-27 22-07-11](https://user-images.githubusercontent.com/37904158/51803886-006fdc80-2280-11e9-90bc-7f6e2cd551fc.png)
Is this enough or do I need to add a scroll bar to visible the full word

**Comment by vijay9908** [comment]
As the strings that are untranslated are decoupled from Joomla , I suggest to remove it and make the page appear clean.

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/23837
