### ISSUE TITLE
[4.0] Modal backdrop overlapping entire page

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23636]
### Steps to reproduce the issue

1. Go to `/administrator/index.php?option=com_categories&view=categories&extension=com_users`
2. Click on the "Versions" buton in the toolbar

### Expected result

A workable UI

### Actual result

The modal backdrop is overlapping the entire page so nothing is clickable.

![screeny2](https://user-images.githubusercontent.com/2019801/51541826-b1761180-1e51-11e9-97b9-a9c209ae4df2.png)

**Comment by ciar4n** [comment]
This occurs anywhere the modal is triggered from the toolbar. The problem occurs on a number of pages.

I believe to amend the modal markup needs to move to before the closing body tag instead of where the modal is been triggered from (eg. toolbar).

**Comment by C-Lodder** [comment]
Funnily enough it works in IE11 🥇

**Comment by ciar4n** [comment]
The would be expected as IE11 does not support position:sticky. Therefore the modal is positioned relative to the `body` and not the `subhead`.

**Comment by puneeth-chanda** [comment]
@C-Lodder Can I know what to change here, this file is in I am not exactly knowing where the mistake is
  layouts/joomla/toolbar/versions.php 
![screenshot from 2019-02-13 20-13-20](https://user-images.githubusercontent.com/43813460/52719600-f19d5f80-2fcb-11e9-899b-ae0d6e5d9b39.png)

**Comment by C-Lodder** [comment]
@puneeth2001 - I don't know off the top of my head. You'll have to debug it

**Comment by puneeth-chanda** [comment]
ok, I'll try doing it.

**Comment by puneeth-chanda** [comment]
By the way, can I work on it??

**Comment by Bakual** [comment]
@puneeth2001 You certainly don't need a permission to do it. We're thankful you're helping! 👍

**Comment by puneeth-chanda** [comment]
@C-Lodder Is it necessary that the backdrop should be there?
![screenshot from 2019-02-14 21-19-03](https://user-images.githubusercontent.com/43813460/52798608-4ad5c380-309e-11e9-9fb1-102647cff2f2.png)
I have deleted the backdrop and it is working fine.

**Comment by C-Lodder** [comment]
@puneeth2001 - Yes the backdrop should be there for UX purposes, so it allows people to focus easily on the contents of the modal

**Comment by ghost** [comment]
closed as having Pull Request #23906

**Comment by ciar4n** [comment]
@franz-wohlkoenig #23906 is not a solution to this issue

**Comment by ghost** [comment]
sorry @ciar4n , reopened

**Comment by ciar4n** [comment]
Thank you @franz-wohlkoenig

**Comment by amelcher** [comment]
In the meantime, maybe somebody can just add this line to the ISIS template css file?
body:not(.modal-open) .modal-backdrop.fade {display:none;}<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23636">issues.joomla.org/tracker/joomla-cms/23636</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #24369

**Comment by infograf768** [comment]
Please see https://github.com/joomla/joomla-cms/pull/25147
