### ISSUE TITLE
[4.0] Installing Multilingual sample data

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23634]
### Steps to reproduce the issue

Attempt to install multilingual sample data without having installed any additional languages

### Expected result

Grey out the "Install" button if the criteria hasn't been met

### Actual result

Required to click "Install", then confirm an alert message, then a danger alert is displayed

![screenshot_2019-01-22 control panel - joomla 4 - administration](https://user-images.githubusercontent.com/2019801/51541280-57c11780-1e50-11e9-8274-cd36d8851808.png)

**Comment by Bakual** [comment]
See https://github.com/joomla/joomla-cms/pull/20749 for a change in that behavior, which would completely hide the option if the criteria is not met.
You suggestions would be an alternative, but would require an API change in how the module works.

**Comment by C-Lodder** [comment]
@Bakual Hiding the option probably isn't a good idea as users could be wondering how to install sample data. Greying out the button would be much more appropriate.

**Comment by Bakual** [comment]
I'm no fan of either actually.

The text already states what the requirements are, and when you press the button it clearly says what you're missing. That's fine for me.
If we grey out the button, you would also have to dynamically tell the user somehow what exactly he is missing. Maybe by clicking the button you'd get a help text or whatever. In the end, you just complicate the code but don't gain anything. But that's a personal opinion.

**Comment by infograf768** [comment]
I think this alert is fine. Obsfuscating the possibility would make it a hidden feature, as well as multilang in general by the way.

**Comment by Quy** [comment]
Duplicate #23028?

**Comment by ghost** [comment]
Duplicate of #23028
