### ISSUE TITLE
[4.0alpha6] Formfield type note duplicate display

### ISSUE THREAD

**Issue by UWiX-nl** [joomla/joomla-cms#23645]
### Steps to reproduce the issue
Create a config.xml file or use the component.xml file to add a note:

        <field 
            name="note_exceptions" 
            type="note" 
            class="alert alert-info" 
            close="true" 
            label="PLG_SYSTEM_MYPLUGIN_FIELD_OVERRIDE_LBL" 
            description="PLG_SYSTEM_MYPLUGIN_FIELD_OVERRIDE_DESC" 
        />

Open up the options of the component/plugin and check the note. It produces a blue alert window which can be closed with a title and description. But the description is repeated once more below the alert-window in text-muted style (without the title).

### Expected result
Show the alert-window with the title and description without a repetition of the description below the alert-window.

### Actual result
It produces a blue alert-window which can be closed with a title and description. The description is repeated once more below the alert-window in text-muted style (without the title).

### System information (as much as possible)
Joomla! 4-alph6 running Xampp with PHP 7.2.5 and MySQLi 5.0.12-dev-20150407

### Additional comments
The file "/layouts/joomla/form/renderfield.php" contains exta lines after the <div class="controls"...>:

    <?php if (!empty($description)) : ?>
        <div id="<?php echo $id; ?>">
            <small class="form-text text-muted"><?php echo $description; ?></small>
        </div>
    <?php endif; ?>

Removing these will solve the issue but I guess they are there for a reason because it's used as a description below the input fields. A check fot field type so it will not show the line duplicated when it's a "note" field?

**Comment by ghost** [comment]
@infograf768 can you please comment?

**Comment by ghost** [comment]
@infograf768 reminder.

**Comment by infograf768** [comment]
??

**Comment by ghost** [comment]
@infograf768 meant [Comment](https://github.com/joomla/joomla-cms/issues/23645#issuecomment-469166153)

**Comment by infograf768** [comment]
Honestly, at this time, no idea about that.
Here I get if I add this field in com_content config.xml
<img width="1167" alt="Screen Shot 2019-03-16 at 19 12 51" src="https://user-images.githubusercontent.com/869724/54479683-9e633a80-481f-11e9-8c67-62d65abe1cb4.png">

**Comment by ghost** [comment]
thanks for Comment @infograf768

**Comment by alikon** [comment]
this issue was reported on Joomla! 4-alpha-6...
hopefully has been resolved  :smile:   and could always be reopened if needed
@franz-wohlkoenig  please close
