### ISSUE TITLE
Invisible recaptcha plugin 

### ISSUE THREAD

**Issue by DaveOzric** [joomla/joomla-cms#23648]
### Steps to reproduce the issue
Create invisible recaptcha keys on Google and add to plugin and publish

### Expected result
No warning on Google's dashboard

### Actual result
We detected that your site is not verifying reCAPTCHA solutions. This is required for the proper use of reCAPTCHA on your site. Please see our developer site for more information.

### System information (as much as possible)
PHP Built On 	Linux vps21291.inmotionhosting.com 2.6.32-042stab127.2 #1 SMP Thu Jan 4 16:41:44 MSK 2018 x86_64
Database Type 	mysql
Database Version 	5.6.41
Database Collation 	latin1_swedish_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.1.26
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.9.2 Stable [ Amani ] 15-January-2019 15:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0 

### Additional comments
Both sites I have the new invisible version have this issue. I have used the invisible keys with 3rd party options without issue.![screen shot 2019-01-23 at 14 01 56](https://issues.joomla.org/uploads/1/b85aac54c983d1f83640ee2c34a58b46.png)
![screen shot 2019-01-23 at 14 01 57](https://issues.joomla.org/uploads/1/d80efcb1155b5b05b84b75de01e13c8a.png)

**Comment by DaveOzric** [comment]
Some sites say this: We detected that your site is verifying reCAPTCHA passed solutions less than 50% of the time. This could indicate a problem with your integration with reCAPTCHA. Please see our developer site for more information.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23648">issues.joomla.org/tracker/joomla-cms/23648</a>.</sub>

**Comment by DaveOzric** [comment]
t appears to be only an issue when using 3rd party extensions that can utilize the core plugin. I switched a site that only has the Joomla Component Contact form and the error message does not show up on Google.

RSForm Pro
JoomDonation
DJ Catalog

These use the core plugin but the error is there. I wonder what changed? They were using the recapthca v2 without issue via the core plugin.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23648">issues.joomla.org/tracker/joomla-cms/23648</a>.</sub>

**Comment by PhilETaylor** [comment]
> it appears to be only an issue when using 3rd party extensions that can utilize the core plugin.

So not a core Joomla issue but an issue with their implementation of it ?

**Comment by DaveOzric** [comment]
That is what I think too. Getting developers to fix it is another story.

**Comment by PhilETaylor** [comment]
You can close this issue in the joomla/joomla-cms github if its not a core issue :)
