### ISSUE TITLE
TinyMCE is unediteable in Google Chrome

### ISSUE THREAD

**Issue by Chaosxmk** [joomla/joomla-cms#23641]
### Steps to reproduce the issue
1. Open Google Chrome 73.0.3673.0
2. Set TinyMCE as the default editor
3. Create a new article
4. Try to type

### Expected result
The editor should allow typing.

### Actual result
No text appears at all.

### System information (as much as possible)
PHP Version | 7.2.14
Joomla! Version | Joomla! 3.9.2 Stable [ Amani ] 15-January-2019 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments
I've tested with both Firefox 65.0b12 and Google Chrome 73.0.3673.0, and only Chrome has been having this problem. Firefox is able to use the editor as intended. I don't have access to previous versions of Chrome to test if it failed to open in them as well.

The developer console doesn't display any error/warning messages whatsoever, but using tools to edit the text does (bold, italic, insert image, etc).

Furthermore, toggling the editor and reactivating the editor (or loading an article with text already set) simply displays the editor as though it were 100% empty.

**Comment by brianteeman** [comment]
I cannot replicate this.

Is this back end or frontend?

**Comment by Chaosxmk** [comment]
Backend. I tested on another computer, and was able to replicate the bug. I've since tried deactivating all of the custom plugins I've made that might affect the editor, no change.

**Comment by brianteeman** [comment]
1. Test with chrome in incognito mode. That  will disable any browser plugins.

2. If above doesn't work then look in the chrome console for any error reports.

**Comment by mbabker** [comment]
It's also going to be a little newer than what ships in 3.x at this point but also see if you can recreate the issue with TinyMCE's demo, https://www.tiny.cloud/docs/demo/full-featured/

**Comment by Chaosxmk** [comment]
Problem persists in incognito mode with all browser plugins disabled, developper console doesn't display any errors, but by filtering console log to allow verbose logs, it does display these warnings:
```[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952 | tinymce.min.js?a2ca9841e7c4ba91664a1d46f55d0b43:2
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952 | tinymce.min.js?a2ca9841e7c4ba91664a1d46f55d0b43:2
[Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write | tinymce.min.js?a2ca9841e7c4ba91664a1d46f55d0b43:11
[Violation] 'load' handler took 194ms | tinymce.min.js?a2ca9841e7c4ba91664a1d46f55d0b43:4
```

The TinyMCE demo provided does not have this error, editor is displaying content and allowing the editing of content as expected.

**Comment by brianteeman** [comment]
@Chaosxmk I use chrome all day everyday as I suspect a million more do. So I really think it must be something to do with your site. If you want to provide me with access I am happy to take a look. brian at teeman dot net

**Comment by Chaosxmk** [comment]
Just did a completely fresh install, no custom modules/components/plugins installed, problem persists. Going to create a login for you to test it out yourself. Expect an email soon.

**Comment by brianteeman** [comment]
As expected I just logged in with the details you provided and it worked perfectly

**Comment by Chaosxmk** [comment]
Well, this is quickly becoming quite perplexing and annoying. What version of Chrome did you test in? I've been doing all of my tests in the dev channel version of Chrome (73.0.3679.0). I'm not sure what else there is to try out.

**Comment by Bakual** [comment]
So you're running a development (alpha) version of Chrome? I'd say you should open an issue at their issue tracker first then. It may well be possible that it is a bug in Chrome itself.

**Comment by Chaosxmk** [comment]
I've submitted a bug report to Chrome devs, but since it's hard to determine if this is caused by an upcoming update to the Chrome engine or a particular bug in the current dev version that will never go public, should this issue be closed or left open for the time being?

**Comment by brianteeman** [comment]
My apologies - I didnt realise you were using the dev release. 

I can confirm the problem with the dev release of chrome

**Comment by Bakual** [comment]
I'd say if it's only happening in an alpha version of a product that is marketed as "expected to be highly unstable", then it's clear to me.

**Comment by Bakual** [comment]
Just for reference from https://developers.google.com/web/updates/2019/01/devtools

> Note: Canary is released as soon as its built, without testing. This means that Canary breaks about once-a-month. It's usually fixed within a day. You can go back to using Chrome Stable while Canary is broken.

So I'd first verify with Google that it's intended behavior and not a bug in Chrome 73 that gets fixed soon.

**Comment by ghost** [comment]
closed as no Core-Issue. Please reopen if needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23641">issues.joomla.org/tracker/joomla-cms/23641</a>.</sub>

**Comment by brianteeman** [comment]
Just commenting that Chrome Version 73.0.3683.86 (Official Build) (64-bit) has been released now and there is no problem
