### ISSUE TITLE
[4.0] Copy icon in debug bar doesn't show

### ISSUE THREAD

**Issue by roland-d** [joomla/joomla-cms#23644]
### Steps to reproduce the issue
1. Go to Global Configuration
2. Enable the Debug System
3. Go to System 
4. Click on Plugins
5. Search on `debug`
6. Make sure the `System - Debug` plugin is enabled

When you see the debug bar click on the Queries word and the debug bar will open and show the queries. There is a Copy function with an icon but the icons doesn't show. Same goes for other icons in that list:
<img width="856" alt="image" src="https://user-images.githubusercontent.com/359377/51588079-4c6afc00-1ee3-11e9-880d-20348006a14f.png">

### Expected result
The correct icons are shown

### Actual result
The incorrect icon is shown

### System information (as much as possible)
Joomla 4.0-dev #d0c00c50822d69730d2b1c4ee6e4315bf8adc0b5
Firefox/Safari
PHP 7.2.14

**Comment by infograf768** [comment]
Confirmed, since the implementation of new debug.

**Comment by hardik-codes** [comment]
@infograf768 which file should I approach to solve this issue?

**Comment by Quy** [comment]
@elkuku

**Comment by infograf768** [comment]
The error looks related to the use of
font-family: PhpDebugbarFontAwesome;
instead of FontAwesome

There is a specific definition for PhpDebugbarFontAwesome in
/media/vendor/debugbar/vendor/font-awesome/css/font-awesome.min.css
(after using npm ci)
It looks like the file is not loaded.

**Comment by hardik-codes** [comment]
@infograf768 I've changed the font-family from PhpDebugbarFontAwesome to FontAwesome in ```build/media/plg_system_debug/widgets/languageStrings/widget.css``` and ```build/media/plg_system_debug/widgets/sqlqueries/widget.css``` but it doesn't work for me.

**Comment by Fedik** [comment]
is that fix an issue #23637?

**Comment by infograf768** [comment]
@hardik-codes 
I am afraid that would not work as we need to load 
`/media/vendor/debugbar/vendor/font-awesome/css/font-awesome.min.css`
which has specific css for the debug, not only for sqlqueries.

@elkuku please look into this.

**Comment by infograf768** [comment]
@Fedik 
#23637 does not solve this icon issue.

**Comment by hardik-codes** [comment]
@elkuku please help me with this

**Comment by infograf768** [comment]
@hardik-codes 
Indeed changing the font name in the widget.css in the build folder solves the issue BUT one has to run npm ci to get the right code in the minified widget.min.css in the media folder as it is always the minified file which is loaded, even when debug is on.

Contrary to what I thought first, `/media/vendor/debugbar/vendor/font-awesome/css/font-awesome.min.css` is useless...

Which means that `/libraries/vendor/maximebf/debugbar/src/DebugBar/JavascriptRenderer.php` is not used.

making patch now.

**Comment by infograf768** [comment]
Closing as we have patch.
Please test https://github.com/joomla/joomla-cms/pull/23732
