### ISSUE TITLE
underscore with double point before echoes in module and another parts

### ISSUE THREAD

**Issue by uzielweb** [joomla/joomla-cms#23640]
### Steps to reproduce the issue
byuserposts.php is my custom layout in php for my module
in my custom built module I need to retrieve the layout name, but when I uses echo
echo $params->get('layout');

 I retrieve some like this
_:byuserposts 

### Expected result

When echo  layout we need to retrieve only the layout name.
"byuserposts" for example

### Actual result

_:byuserposts

**Comment by SharkyKZ** [comment]
This is expected. Layout value consists of template name (or underscore if global layout is used) and layout name, separated by colon. E.g. if you created `custom.php` layout for Protostar and selected it, the value would be `protostar:custom`.

**Comment by Bakual** [comment]
I'm closing this issue as it is expected behavior.
If you need assistance with adjusting your code, feel free to ask on the forum (forum.joomla.org).
