### ISSUE TITLE
[4.0] Remove plg_fields_repeatable

### ISSUE THREAD

**Issue by continga** [joomla/joomla-cms#23659]
As discussed in #22446 we need to remove the plg_fields_repeatable plugin as soon as #22446 is merged into 3.10-dev

Background: Pull request #22446 implements a new custom field type plg_fields_subfields which is capable of using predefined custom fields for use as sub fields of a subform containing those. This functionality is basically an expansion of the functionality of the plg_fields_repeatable type. Hence, to keep the Joomla! core clean, we need to remove the plg_fields_repeatable plugin.

What needs to be done is that the plg_fields_repeatable plugin needs to be removed for all new installations of Joomla!, and for all existing installations that do not use that plugin (so have no repeatable custom fields). For installations that use it, we need to either provide a transitioning-script, or we need to explain the user how to switch from the repeatable type to the subfields type. To accomplish this, we maybe first need to declare the plg_fields_subfields type as deprecated in a first step.

A first idea of how to remove the repeatable type from core and how to build a transitioning script can be found in this diff https://github.com/continga/joomla-cms/commit/71f831d2a78fdc5340ef5d60352cdb7fa23e04ec
That diff was previously part of the beforementioned PR, but we decided to do the plg_fields_repeatable stuff in a separate issue and keep it outside of the scope of the plg_fields_subfields PR. That is the reason this issue got created.

So in a first place, we need to decide on the actions that need to be taken in regards to the plg_fields_repeatable plugin when #22446 got merged, and when we have decided and when #22446 is merged, we need to create an additional PR for this.

**Comment by ghost** [comment]
@infograf768 can you please comment?

**Comment by ghost** [comment]
@infograf768 reminder

**Comment by infograf768** [comment]
As it looks that #22446 is not going to go into 3.x and is not changed to be targeted at 4.0, this Issue looks out of scope for now.
The proposed code should imho be added to #22446 if necessary in order to merge both together when proposed and accepted.

**Comment by ghost** [comment]
@infograf768 thanks for Comment. So its for @HLeithner or @wilsonge

**Comment by HLeithner** [comment]
We can't remove anything in a minor version. At least not following the semver definition.
Beside this, how should this work what happens to layout overrides?

**Comment by micker** [comment]
I think repetable field is already use in many extension ... Try to start migration now Can be interesting now for less work on j4 migration

**Comment by HLeithner** [comment]
Migration seams not to be the problem (script is ready) but layout overrides may have to be changed.

**Comment by wilsonge** [comment]
It would make sense in this case to merge #22446 so people have a version where they can migrate their fields out of repeatable and into the subform field. But yes the repeatable field cannot be removed until 4.0 - but we can of course mark it as deprecated as soon as that is merged

**Comment by wilsonge** [comment]
AMENDMENT TO ABOVE: Apologies. I missed there was a migration script. If there's a migration script then the correct place to do that migration is in 4.0 and not have this in 3.10! Sorry!

**Comment by ghost** [comment]
changed Title cause of above Comment by @wilsonge

**Comment by wilsonge** [comment]
Adding release blocker label as this needs to be solved for 4.0 stable

**Comment by jwaisner** [comment]
Increasing priority as per guidelines for beta-blockers.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23659">issues.joomla.org/tracker/joomla-cms/23659</a>.</sub>

**Comment by Quy** [comment]
See PR #28319 Draft.
