### ISSUE TITLE
Call to undefined method Joomla\CMS\Application\AdministratorApplication::edirect() 

### ISSUE THREAD

**Issue by Flocke28** [joomla/joomla-cms#23656]
### Steps to reproduce the issue
After update to Joomla! 3.9.2  i got this error if i try to copie an entry from AlphaUserPoints Rules

Call to undefined method Joomla\CMS\Application\AdministratorApplication::edirect() 

It looks that are missing a "r" for redirect.

--------------------------------------------------------

Also i got a error 0 - invalid controller: name='user', format='' on my mobile page if i try to login.

**Comment by Bakual** [comment]
Since AlphaUserPoints isn't part of core, please use the issue tracker for that extension.
The second one sounds like an error in your login module. Chances are high you're using a 3rd party there as well.

I'm closing this as it is not a core issue.
