### ISSUE TITLE
Images in an RSS feed from a Category View are unuseable by Mailchimp

### ISSUE THREAD

**Issue by Bodge-IT** [joomla/joomla-cms#23657]
### Steps to reproduce the issue
When Joomla's RSS feature is used to auto generate MailChimp newsletters from a Category View URL, no intro-image is pulled through the feed.  MailChimp generates an html email without images.
Looking at the feed url in a browser, shows the images as present and checking the code it appears that images are thrown into `<description>` element.  It also seems to add fixed width & height to images.
Rightly or wrongly, MailChimp strips or hides these images from description and does not parse through to its mail output.  Joomla! is not using the expected RSS media enclosures for its media.

### Expected result
Images are pulled through the feed, within an `<enclosure>` element, outside of the `<description>` element.  Images should not necessarily be contained by height or width, as this can be handled by the feed interpretter.
RSS Spec(used as source): https://cyber.harvard.edu/rss/rss.html#hrelementsOfLtitemgt

### Actual result
Images are passed through the feed within the `<description>` element and wrapped in a `<p>` tag.  This change was implemented in #11402.  While this showed up for me in MailChimp, it could apply to any RSS interpretter.

### System information (as much as possible)
Files affected:
components/com_content/views/category/view.feed.php
libraries/src/Document/Renderer/FeedRssRenderer.php
libraries/src/MVC/ViewCategoryFeedView.php

Having created a fix for this, the above files required changing but I suspect, because of the circumvention of availability of the appropriate functionality, a good reason exists for not handling images appropriately.

### Additional comments
All the elements for this to work already seem to be present in the library, it seems Joomla! is just circumventing these and passing the images within the `<description>` element.

**Comment by ghost** [comment]
This is about which Joomla-3-Version?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23657">issues.joomla.org/tracker/joomla-cms/23657</a>.</sub>

**Comment by ghost** [comment]
closed as no Answer; please reopen if needed.
