### ISSUE TITLE
Special characters in username

### ISSUE THREAD

**Issue by anka56** [joomla/joomla-cms#23658]
### Steps to reproduce the issue

1. Install a fresh Joomla version 3.9.x and call the super user
 admin%
(username with a special character, e.g. **%** )

2. After Joomla has been successfully installed, try to log in to the backend using the new username "admin%"

### Actual result
Access denied with this error message:
"Username and password do not match or you do not have an account yet."

### Additional comments
When trying to add a new user with special character in the username in the backend, you get an error saying:
"Save failed with the following error: Please enter a valid username. No space at beginning or end, at least 2 characters and must not have the following characters: < > \ " ' % ; ( ) &."

To me it looks like joomla is using different filters for username.

**Comment by brianteeman** [comment]
Pretty sure we have had this reported before?

**Comment by anka56** [comment]
The only report I could find is related to Joomla 4.0 ([#19301](https://issues.joomla.org/tracker/joomla-cms/19301 "")), so I thought it was a different one.   <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23658">issues.joomla.org/tracker/joomla-cms/23658</a>.</sub>

**Comment by brianteeman** [comment]
Ah that was it. Different code but probably the same underlying reason. The validation code in the installation app is out of sync with the cms

**Comment by alikon** [comment]
test #23918

**Comment by HLeithner** [comment]
Closed because we have a PR thx @alikon
