### ISSUE TITLE
[4.0] SQL int default value should be numeric

### ISSUE THREAD

**Issue by amitranjan2** [joomla/joomla-cms#23668]
### Steps to reproduce the issue

https://github.com/joomla/joomla-cms/blob/d0c00c50822d69730d2b1c4ee6e4315bf8adc0b5/administrator/components/com_finder/sql/install.mysql.sql#L77

I think, 
DEFAULT value should be Numeric 1, not char '1'
am I right?

if yes should I do PR?

### Expected result
same as before

### Actual result

same as before

**Comment by alikon** [comment]
yes, please...

**Comment by Quy** [comment]
See PR #23669<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23668">issues.joomla.org/tracker/joomla-cms/23668</a>.</sub>
