### ISSUE TITLE
Re-populate components menu without extension reinstall

### ISSUE THREAD

**Issue by alex7r** [joomla/joomla-cms#23666]
### Is your feature request related to a problem? Please describe.
I we discover the component that by some reason have no (or have not all) menu/submenu items in the XML. There is no way to fix this but building the package manually and reinstalling it with installation manager.

### Describe the solution you'd like
Have some button in "discover" for example to repopulate menu based on current XML files.
Right now we can rebuild cache of those XML files, but it will have no effect on menu items.

**Comment by ghost** [comment]
this is for [4.0]?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23666">issues.joomla.org/tracker/joomla-cms/23666</a>.</sub>

**Comment by ghost** [comment]
closed as no Answer; please reopen if needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23666">issues.joomla.org/tracker/joomla-cms/23666</a>.</sub>

**Comment by alex7r** [comment]
That's for both. I mean I would like it to be fixed at least in 4.0, but this is a non issue for 3.x also.

**Comment by HLeithner** [comment]
Makes sense to have this button especially when 4.0 doesn't have any sidetoolbar
