### ISSUE TITLE
Update availability notification - high latency

### ISSUE THREAD

**Issue by creative-resort** [joomla/joomla-cms#23663]
### Steps to reproduce the issue

visit the main Joomla! "Control Panel" page and in the left hand sidebar, look at the Joomla! update status under "maintainence".

### Expected result

The update status (at least for Joomla!, optimally also for plugins) should be available immediately or after 3-5 seconds.

### Actual result

It takes 16 seconds and more, even on a performant server.

### System information (as much as possible)

PHP Built On | Linux dd21204 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64
Database Type | mysql
Database Version | 5.7.21-nmm1-log
Database Collation | latin1_swedish_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.1.23-nmm1
Web Server | Apache
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 3.9.2 Stable [ Amani ] 15-January-2019 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Chrome/71.0.3578.98

### Additional comments

The status could be pre-cached, especially on a website with high traffic this would make sense.

**Comment by ghost** [comment]
can you please test on latest Version?

**Comment by creative-resort** [comment]
done,
same story with Joomla! 3.9.3

**Comment by ReLater** [comment]
Did you read this thread already? https://github.com/joomla/joomla-cms/issues/24066

**Comment by ReLater** [comment]
BTW: I can't confirm "16 seconds and more" on a medium performant server.

**Comment by ghost** [comment]
@creative-resort can this Issue be closed?

**Comment by creative-resort** [comment]
Thank you @ReLater.
I've read it and while I understand how the mechanics behind the scenes work,
it doesn't solve the issue.

What is the best way to debug / measure execution times on functions for those ajax calls?

**Comment by ghost** [comment]
@ReLater can you please comment?

**Comment by HLeithner** [comment]
So I checked our update system and found out that the update cache get purged before we do a update check. I create a PR #24217 to fix this. please test.

Closing this.

**Comment by creative-resort** [comment]
Amazing! Thank you!
This is how it's supposed to work. Very quick, now.

**Comment by HLeithner** [comment]
@creative-resort thx for your feedback.
