### ISSUE TITLE
Joomla 3.9.2 Login Component CSS Styling ugly

### ISSUE THREAD

**Issue by BRoehling** [joomla/joomla-cms#23678]
### What needs to be fixed
Joomla 3.9.2 (German). Login component -> CSS Styling.
Image 1: checkbox should be in front of "angemeldet bleiben" or behind it but not below.

![login-1](https://user-images.githubusercontent.com/46946646/51788675-0c28a980-2181-11e9-9f91-f279b4114165.jpg)

Image 2: 1 and 2 have a positive margin. Why? 3. needs more space between "Datum des letzten Besuchs" and date.

![login-2](https://user-images.githubusercontent.com/46946646/51788694-4003cf00-2181-11e9-978a-586c78dd5dfb.jpg)

### Why this should be fixed
it looks like a mess. Should be clean and visually working professionally.

### How would you fix it
Modify the CSS

### Side Effects expected
none

**Comment by brianteeman** [comment]
That sounds like a template issue to me as it looks like this in the default protostar

![image](https://user-images.githubusercontent.com/1296369/51788751-adabfd00-2179-11e9-9272-dc530c6e0cdd.png)

**Comment by BRoehling** [comment]
I fixed the template :)
