### ISSUE TITLE
[4.0] An error has occurred on Search Filter

### ISSUE THREAD

**Issue by amitranjan2** [joomla/joomla-cms#23677]
### Steps to reproduce the issue

Navigate to the following page from the admin page

Components >> smart search >> Search Filters >>New 
then write title name and click   >> save and close 

### Expected result
It should be saved and title name should be displaced 

### Actual result
0 Class 'Text' not found

**Comment by anuragteapot** [comment]
Issue Confirmed.

**Comment by anuragteapot** [comment]
@amitranjan2 Can you please do PR for this?

**Comment by amitranjan2** [comment]
@Anu1601CS ok, I will

**Comment by Quy** [comment]
See PR #23679<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23677">issues.joomla.org/tracker/joomla-cms/23677</a>.</sub>
