### ISSUE TITLE
Tags in alphabetical order when creating a new article

### ISSUE THREAD

**Issue by PixedBo** [joomla/joomla-cms#23674]
### Is your feature request related to a problem? Please describe.

This is a feature request: now when i create a new article in backend and want to assign tags they come in ID ordered list.

### Describe the solution you'd like

If you have a lot of tags and don't remember all of them a list in alphabetical order is much easier to use than a "random" list (ordered by ID all tags seems randomized).
Of course you can start type the tag and Chosen finds it for you, but i think that alphabetical order is better for user experience.

### Additional context

Example: 

ID 1 - Example Tag
ID 2 - Another Example Tag
ID 3 - Beautiful Tag

While I would like them displayed as:

ID 2 - Another Example Tag
ID 3 - Beautiful Tag
ID 1 - Example Tag

Thank you

![tags](https://user-images.githubusercontent.com/12549961/51786925-5c950c80-216b-11e9-8d55-c0bb8bd80d6b.jpg)

**Comment by ReLater** [comment]
> a "random" list (ordered by ID

As  far as I understand they aren't ordered by id but are ordered in the chosen field like I order them in com_tags. I think that's the best solution and shouldn't be changed.

![26-01-_2019_21-01-36](https://user-images.githubusercontent.com/20780646/51792149-ccc48200-21ad-11e9-8727-391f13bfcaed.jpg)
![26-01-_2019_21-02-17](https://user-images.githubusercontent.com/20780646/51792151-cfbf7280-21ad-11e9-8727-6be8b26a22e0.jpg)

**Comment by PixedBo** [comment]
You are right, I can manually order them. But if you have lots of tags it would be a nightmare to order them manually. Maybe the option to choose which order use would be a great plus. Thank you anyway.

**Comment by tonypartridge** [comment]
The best option here isn’t to add more config options but actually add a sort feature into the list view and then save order I believe would be the best solution.

**Comment by Bakual** [comment]
It has to be by "order" because of the possibility of nested tags. If you alphaorder it, that could get tricky.

The field has a good filter. Once you start typing the list is reduced to matching results. So it's not hard to find a tag even if it's not alphaordered.

**Comment by ghost** [comment]
Closed as there is a Way to handle. Please reopen if needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23674">issues.joomla.org/tracker/joomla-cms/23674</a>.</sub>
