### ISSUE TITLE
[4.0] Disable install button after installing sample data

### ISSUE THREAD

**Issue by hardik-codes** [joomla/joomla-cms#23670]
### Steps to reproduce the issue
In the Control Panel, clicking on the install button for the blog sample data for the first time results in 
![sample_data](https://user-images.githubusercontent.com/34353697/51766180-f626d480-20ff-11e9-8d50-f8978d454654.png)

If the user visits the control panel after a time gap, the user might unknowingly click the install button again which would result in the following error

![screenshot_2019-01-26 control panel - joomla - administration](https://user-images.githubusercontent.com/34353697/51766384-6c2b3b80-2100-11e9-9367-ea1f8d0a423a.png)

This would unnecessarily confuse the user.

### Expected result
The install button should be disabled after the sample data is installed

### Actual result
The install button is not disabled

**Comment by Quy** [comment]
Duplicate #23633<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23670">issues.joomla.org/tracker/joomla-cms/23670</a>.</sub>
