### ISSUE TITLE
[4.0] System Panel excessive queries

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#23675]
### Steps to reproduce the issue
Enable debug

478 statements were executed, 124 of which were duplicates, 354 unique

That's just a little bit excessive ;)

**Comment by bembelimen** [comment]
Biggest issues is the checked_out check (https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_cpanel/Model/SystemModel.php#L69 ~ 90 queries) and the findUpdate() call (https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_cpanel/Model/SystemModel.php#L215 ~ 250 queries).
Perhaps we could remove the findUpdate call and fall back to the Ajax solution used by the plugin?

**Comment by bembelimen** [comment]
Hello @brianteeman I tinkered around with the system board and have first codes:
https://github.com/bembelimen/joomla-cms/tree/system-dashboard
If you have time to check (it's not PR ready yet), I would really appreciate it.

**Comment by brianteeman** [comment]
Thats a lot better - only 26 queries.

**Comment by brianteeman** [comment]
closed see #23936
