### ISSUE TITLE
J4 User custom field creation error modified_time column

### ISSUE THREAD

**Issue by DonaldTrump88** [joomla/joomla-cms#23680]
### Steps to reproduce the issue
* Go to /administrator/index.php?option=com_fields&view=field&layout=edit&context=com_users.user
User > fields
* Create text field. 
* Add title and label.

### Expected result
Field gets created
Same use case works in J3

### Actual result
Error, see screenshot
![j4-user-field-creation-problem](https://user-images.githubusercontent.com/28602840/51789244-13eb4c80-2187-11e9-8316-a410c41e426c.PNG)

### System information (as much as possible)
J4 25 Jan 2019 nightly build

**Comment by amitranjan2** [comment]
test this PR #23669.  After that it might work for you
![image](https://user-images.githubusercontent.com/41797766/51790435-621a4300-21bb-11e9-8ac4-3c8cfc0700ad.png)

**Comment by ElephantInTheRoomFirst** [comment]
@amitranjan2  Thanks

I did not find test instructions in the PR. The PR has changes in sql and css files.

**Comment by Quy** [comment]
See PR #23689<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23680">issues.joomla.org/tracker/joomla-cms/23680</a>.</sub>
