### ISSUE TITLE
Use of undefined constant JDEBUG

### ISSUE THREAD

**Issue by dioubernardo** [joomla/joomla-cms#23699]
### Steps to reproduce the issue

-- crop.php

```<?php
const _JEXEC = 1;

if (!defined('_JDEFINES')){
    define('JPATH_BASE', dirname(__DIR__));
    require_once JPATH_BASE . '/includes/defines.php';
}

require_once JPATH_LIBRARIES . '/import.legacy.php';
require_once JPATH_LIBRARIES . '/cms.php';
require_once JPATH_CONFIGURATION . '/configuration.php';
require_once JPATH_BASE . '/includes/framework.php';

class CronFURG extends JApplicationCli{

	public function doExecute(){
		...
	}
}

JApplicationCli::getInstance('CronFURG')->execute();
```
```
php cron.php
```

### Expected result

No result

### Actual result

PHP Warning:  Use of undefined constant JDEBUG - assumed 'JDEBUG' (this will throw an Error in a future version of PHP) in /storage/htdocs/joomla/ppgbaac/libraries/src/Version.php on line 327

**Comment by PhilETaylor** [comment]
try 

```php
<?php
define('_JEXEC', 1);
define('JPATH_BASE', realpath('../'));
ini_set('display_errors', '1');
error_reporting(E_ALL);
define('JDEBUG', 1);
include_once JPATH_BASE . '/includes/defines.php';
include_once JPATH_BASE . '/includes/framework.php';
include_once JPATH_BASE . '/libraries/joomla/factory.php';

class CronFURG extends JApplicationCli{
  public function doExecute(){
   //	...
  }
}

JApplicationCli::getInstance('CronFURG')->execute();


```

**Comment by N6REJ** [comment]
@franz-wohlkoenig REOPEN THIS PLEASE
as of 3.9.11 this is still occurring
![image](https://user-images.githubusercontent.com/1850089/64367457-a1c0cd00-cfdd-11e9-81c1-d2c1b63ae2fc.png)
the "hi" is the jdebug working but it's throwing the warning.

**Comment by N6REJ** [comment]
changing if(JDEBUG) to if (defined('JDEBUG') && JDEBUG) solves the issue. 
	
	<?php if (defined('JDEBUG') && JDEBUG)
	{
		echo "hi";
	}
	?>
![image](https://user-images.githubusercontent.com/1850089/64368264-86ef5800-cfdf-11e9-931a-32f93b96d234.png)

**Comment by N6REJ** [comment]
This solves the issue which is strange since it thinks there is no jdebug constant.


	<jdoc:include type="modules" name="debug" style="none"/>
	
	<?php if (defined('JDEBUG') && JDEBUG)
	{
		HTMLHelper::_( 'stylesheet', '/framework/debug.css', $HTMLHelperDebug );
	}
	?>

**Comment by mbabker** [comment]
Constants are case sensitive so your warning is correct because Joomla does not create mixed case constants.

I’m also not quite sure how this qualifies to re-open an issue when both the source path of the error and the way of triggering it have nothing to do with the original report.  A similar error message does not equate to the same “bug”.
