### ISSUE TITLE
Add native authentication with Apereo CAS

### ISSUE THREAD

**Issue by shteevy** [joomla/joomla-cms#23690]
Hello, i'm using Apereo CAS (https://www.apereo.org/projects/cas) to authenticate our users

Do you think this type of authentication will be implemeted into joomla with a native plugin in the futur ?

Many thanks,

Shteevy

**Comment by HLeithner** [comment]
There is a plugin for this: 
https://extensions.joomla.org/extension/external-login-cas-plugin/

I don't think this will be part of the core in the near future.

**Comment by shteevy** [comment]
Hello, thank you for this answer. But i think it will be very usefull if this kind of authentication would be native in Joomla. The Project External Login on gitHub indicates : "This project needs a maintainer" and is no longuer updated.
Other opensource community projects like Moodle integrate a CAS plugin.
Steve

**Comment by eddiekonczal** [comment]
shteevy, we are looking for the same solution in our organization.  We have been using External Login but as you say, it's no longer supported and it won't work in Joomla! 4.  When you say you're using Apereo CAS to authenticate our users, are you using the External Login extension, your own extension, or some other method?

**Comment by shteevy** [comment]
Hello Eddie,
For practical reasons due to the overload related to COVID, we have decided to switch to AzureAD authentication. CAS should be integrated into Joomla. Unfortunately, we didn't have time to offer this development to the community. Good luck in your research. Steve

**Comment by eddiekonczal** [comment]
Steve,
Thanks for the reply!  Is there an AzureAD extension available, or did you need to build one yourself?
-Eddie

**Comment by eddiekonczal** [comment]
Additional: do extensions exist for non-Azure implementations of AD authentication?

**Comment by shteevy** [comment]
Hello, there is "Mini-Orange OAuth plugin for Joomla" for Azure AD
AD direct Authentication is native into Joomla (LDAP Plugin : https://docs.joomla.org/LDAP) 
Steve
