### ISSUE TITLE
[4.0] Status-change Dropdown is activated with action button

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#23717]
### Steps to reproduce the issue
Go to Articles overview. 
Klick on one action button "featured".

### Expected result
The featured state is changed and the rest of the screen remains unchanged

### Actual result
This activates the corresponding checkbox and this activates the Status Change Dropdown for a moment.
This is correct from the developers point of view but looks like a bug for the user.

**Comment by hardik-codes** [comment]
@chmst I was not able to understand "activates the Status Change Dropdown for a moment.". What does it actually mean?

**Comment by chmst** [comment]
I see it in this PR #23718.
Here I click on the featured button. For a moment you see that the checkbox is activated and the State-change Button changes the colour.

**Comment by brianteeman** [comment]
@chmst Is this what you mean?

![feat](https://user-images.githubusercontent.com/1296369/52170215-1547e680-273e-11e9-81f2-89185428a218.gif)

**Comment by Quy** [comment]
Unrelated, is it intentional to display `Published` under the Status column? If yes, what is its purpose?

**Comment by chmst** [comment]
@brianteeman yes! 
@Quy this status button shows if the item is published - the dropdown allows changing this condition. This is still work in progess.

**Comment by hardik-codes** [comment]
@chmst coold you possibly explain why such behavior is shown by ```Status change``` dropdown button for a moment.

**Comment by Arpit-24** [comment]
@chmst Not really sure but do you mean to get rid of the outline that appears on click?

Like as shown

![upload](https://user-images.githubusercontent.com/26358271/54883392-83ca3a80-4e8b-11e9-85ae-7bee43d36eda.gif)

**Comment by ghost** [comment]
Closed as Issue resolved somewhere. @chmst please reopen if Issue isn't resolved.
