### ISSUE TITLE
[4.0] Login form module does not reflect shared session state

### ISSUE THREAD

**Issue by lllopo** [joomla/joomla-cms#23734]
### Steps to reproduce the issue
1. Enable shared sessions in global configuration
2. Login in the backend
3. Go to the frontend with Login Form module added somewhere on the page

### Expected result
Login Form module should display Log Out button

### Actual result
Login Form module still displays login form even though the user is logged in through the backend in a shared session

### System information (as much as possible)
Joomla 4.0 alpha 7 latest nightly, PHP 7.2x64, Apachae 2.4, MariaDB 10.3x64, Win 10 1809

**Comment by ghost** [comment]
@infograf768 can you please comment?

**Comment by ghost** [comment]
@wilsonge  can you please comment as Release Lead 4?

**Comment by ghost** [comment]
Closed as Issue resolved somewhere. @lllopo please reopen if Issue isn't resolved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23734">issues.joomla.org/tracker/joomla-cms/23734</a>.</sub>
