### ISSUE TITLE
PHPMyAdmin - Table does not support optimize ?

### ISSUE THREAD

**Issue by Chacapamac** [joomla/joomla-cms#23738]
### Steps to reproduce the issue

Try to optimize database in PHPMyAdmin

### Expected result

Just Optimize

### Actual result
Message: Table 

### System information (as much as possible)

PHP 7.2.1 - MYSQL 5.6.38

### Additional comments

Collation UTF8B4 Type: InnoDB

Is this normal?

**Comment by HLeithner** [comment]
The complete message would be nice but anyway thats normal and the table get recreated.

Also this has not much todo with Joomla.

**Comment by Chacapamac** [comment]
I just remark this and wonder if it was the same for older version of Joomla, I just test and yes, same with older version of Joomla.

**YOU CAN CLOSE THIS!**

MORE EXPLANATION HERE...
Likely, you're doing OPTIMIZE on an InnoDB table (table using the InnoDB storage engine, rather than the MyISAM storage engine).

InnoDB doesn't support the OPTIMIZE the way MyISAM does. It does something different. It creates an empty table, and copies all of the rows from the existing table into it, and essentially deletes the old table and renames the new table, and then runs an ANALYZE to gather statistics. That's the closest that InnoDB can get to doing an OPTIMIZE.

The message you are getting is basically MySQL server repeating what the InnoDB storage engine told MySQL server:

Table does not support optimize is the InnoDB storage engine saying...

"I (the InnoDB storage engine) don't do an OPTIMIZE operation like my friend (the MyISAM storage engine) does."

"doing recreate + analyze instead" is the InnoDB storage engine saying...

"I have decided to perform a different set of operations which will achieve an equivalent result."
