### ISSUE TITLE
[4.0] [WIP] Links to buttons

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/joomla-cms#23737]
In alpha6 version I found 15 files in which instead of the tag `button` was used the `a` tag with the attribute `role=button`. We have already explained that this is an accessibility error that needs to be fixed.
Could anyone improve these files? 
It has already happened that @SharkyKZ corrected a number of errors of this type in one PR (https://github.com/joomla/joomla-cms/pull/22494)
Below is a list of them.
- [x] administrator/components/com_asotiations/Field/Modal/AsotiationsField.php
- [x] administrator/components/com_categoies/Field/Modal/CategoryField.php
- [x] administrator/components/com_contact/Field/Modal/ContactField.php
- [x] administrator/components/com_content/Field/Modal/ArticleField.php
- [x] administrator/components/com_content/View/Article/HtmlView.php
- [ ] administrator/components/com_fields/Field/Modal/FieldField.php
- [x] administrator/components/com_media/resources/scripts/components/modals/share-modal.vue
- [x] administrator/components/com_menus/tmpl/item/edit_modules.php
- [ ] administrator/components/com_menus/tmpl/menus/default.php
- [x] administrator/components/com_newsfeeds/Field/Modal/NewsfeedField.php
- [x] administrator/components/com_templates/Service/HTML/Templates.php
- [x] administrator/modules/mod_logged/tmpl/default.php
- [ ] administrator/modules/mod_multilangstatus/tmpl/default.php
- [x] installation/tmpl/remove/default.php
- [x] layouts/joomla/toolbar/versions.php
I did not check, but I suppose similar changes are needed in Joomla3.

**Comment by brianteeman** [comment]
i strongly suspect that these have all been fixed in 3.9 by @SharkyKZ  and are just waiting for @wilsonge to merge them into j4. j4 is currently over 1000 commits behind/

**Comment by brianteeman** [comment]
i can see that these are still present BUT most are for modal close buttons which is scheduled to be rewritten. I will do a pr for the rest

**Comment by Quy** [comment]
Please confirm that this can be closed.

**Comment by wilsonge** [comment]
Looks like 3 files left to me

**Comment by Quy** [comment]
Related PR #23740

**Comment by Quy** [comment]
Deleted in PR #25139.
`administrator/components/com_fields/Field/Modal/FieldField.php`

Fixed in PR #25126
`administrator/components/com_menus/tmpl/menus/default.php`
`administrator/modules/mod_multilangstatus/tmpl/default.php`
