### ISSUE TITLE
[4.0] Unclear sidebar navigation

### ISSUE THREAD

**Issue by bahl24** [joomla/joomla-cms#23746]
### Steps to reproduce the issue
system->global configuration. See nav menu under components

![screenshot from 2019-02-03 00-46-57](https://user-images.githubusercontent.com/36095178/52168231-85aa3400-274d-11e9-80c2-6a663d307c43.png)

### Actual result
When toggle menu is open, sidebar nav is not clear as evident in screenshot.

### System information (as much as possible)
OS-Ubuntu 18.04

**Comment by Quy** [comment]
See PR #23747<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23746">issues.joomla.org/tracker/joomla-cms/23746</a>.</sub>
