### ISSUE TITLE
[4.0] Typed tags get added in autocomplete list

### ISSUE THREAD

**Issue by Harshil99** [joomla/joomla-cms#23748]
### Steps to reproduce the issue

- Create one or more tags in the Tags component.
- Go and create a new article.
- Type a tag from Tags component.
- Clear the tag you wrote.
- Type that same tag again.

### Expected result
Autocomplete list (without duplicate) of tags as per typed letters.

### Actual result
Typed tags (one from Tags component) get added to autocomplete list.
![screenshot from 2019-02-03 01-12-09](https://user-images.githubusercontent.com/31547079/52168771-33204600-2754-11e9-8417-2eb224fdc634.png)

### System information (as much as possible)
Joomla 4 alpha 7

**Comment by amitranjan2** [comment]
issue confirmed

**Comment by amitranjan2** [comment]
@dgrammatiko Is this `choice.js` issue or joomla?

**Comment by ghost** [comment]
@dgrammatiko can you please comment?

**Comment by ghost** [comment]
@wilsonge  can you please comment as Release Lead 4?

**Comment by Quy** [comment]
No longer reproducible in the latest nightly build.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23748">issues.joomla.org/tracker/joomla-cms/23748</a>.</sub>
