### ISSUE TITLE
[4.0] User Notes edit category Save &Close  and Save Button  link broken

### ISSUE THREAD

**Issue by amitranjan2** [joomla/joomla-cms#23751]
### Steps to reproduce the issue
Navigate to the following page from the admin page

Users >> User Note  >> New >>  Category
select the Category and choose  and then click on edit button on the Category itself

and then click on Save or Save& Close button

### Expected result

Save and Save &Close Button should work

### Actual result
It's not working, link broken

**Comment by infograf768** [comment]
Known error for modals.
`TypeError: iframeDocument is null` in modal-fields.js

This has not yet been taken care of by @dgrammatiko

**Comment by ghost** [comment]
Closed as known Issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23751">issues.joomla.org/tracker/joomla-cms/23751</a>.</sub>
