### ISSUE TITLE
Search menu by component

### ISSUE THREAD

**Issue by activha** [joomla/joomla-cms#23765]
Sometimes you have websites with lots of menu and a few components. Then it's pretty hard to know whether you have menu linked to only one component or one task.

Duplicates may render things difficult with SEO

A simple thing would be to have the ability to search menu by component in order to get a list of all menu items linked to a unique component.

I hope others may find it useful also and feel it should be part of the core

**Comment by brianteeman** [comment]
Do you mean like this https://github.com/joomla/joomla-cms/pull/23566

**Comment by brianteeman** [comment]
This should be closed as a duplicate
