### ISSUE TITLE
Message requiring to log in should be of type Notice (blue) or Warning (yellow) instead of Message (green)

### ISSUE THREAD

**Issue by kofaysi** [joomla/joomla-cms#23763]
### Steps to reproduce the issue

* Register a new arbitrary user.
* Log out of all the Joomla frontend.
* Wait for the activation e-mail and activate the account by clicking on the link.

### Expected result

A non-green (an unaccomplished event) message or notice should appear. It can be blue Notice or yellow Warning as in https://docs.joomla.org/Display_error_messages_and_notices

### Actual result

A green (successful event) message appears. The text is great and valid, but it is misleading about successful event.

### System information (as much as possible)

Joomla 3.9.2

### Additional comments

This behavior changed in the last months. Previously it was possible to activate accounts unless the respective administrator was logged out. Now, it is required that the administrator (or similar user) logs in. That is a valid requirement and a good change in the code, IMO. But visually nothing changed, only the message and the process changed. The message is still green as in "successful valid action completed". That is misleading. Action is required to finish the validation process.

All it is a corrected optical aid. Of course, it is no excuse that the message was interpreted falsely by the user... Or is it? ]:->

**Comment by kofaysi** [comment]
The screenshot of the current message is included.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23763">issues.joomla.org/tracker/joomla-cms/23763</a>.</sub>

**Comment by kofaysi** [comment]
The screenshot of the current message is included.
![screen shot 2019-02-04 at 09 12 52](https://issues.joomla.org/uploads/1/becd5e2252eeac7473dacccde5f86d5e.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23763">issues.joomla.org/tracker/joomla-cms/23763</a>.</sub>

**Comment by brianteeman** [comment]
That string is not coming from Joomla.

**Comment by kofaysi** [comment]
I have search in language override and this came up:
![screen shot 2019-02-04 at 15 39 51](https://issues.joomla.org/uploads/1/f441e8a9e3034886d6f24f113d680e29.png)
That is why I identified Joomla and com_users. The capitalization is a result of the gTranslate plugin. (gTranslate has been switched on, while already on English default site language.)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23763">issues.joomla.org/tracker/joomla-cms/23763</a>.</sub>

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/blob/staging/language/en-GB/en-GB.com_users.ini#L120

Indeed, there no message type set in
`ROOT/components/com_users/controllers/registration.php`
line 92
`$this->setMessage($message);`

By default, it therefore uses the `Message` type.

It should be a warning
`$this->setMessage($message, 'warning');`

@kofaysi Can you propose a PR?

**Comment by kofaysi** [comment]
My first PR has been created https://github.com/kofaysi/joomla-cms/pull/1

I used this manual https://extensions.joomla.org/blog/item/how-to-contribute-to-joomla-through-github/ (screenshots are outdated).

Did I miss anything crucial, please?

**Comment by kofaysi** [comment]
I think that that PR is going to affect the line 84, too
`$message = JText::_('COM_USERS_REGISTRATION_ACL_ADMIN_ACTIVATION_PERMISSIONS');`
and it is a correct behavior also.

**Comment by infograf768** [comment]
yes. both messages are concerned.
now you have to propose your PR from your branch to staging

**Comment by kofaysi** [comment]
Hm, I think I did sth wrong, I missed something or should I await an action by somebody else, please? I merged the branch to staging few days ago
![image](https://user-images.githubusercontent.com/17022173/52504215-09e63680-2be8-11e9-9c81-14ce8c9d247f.png)
But there is no code attached to this issue yet and the PR did not appear in Joomla! Patch Tester yet either.

**Comment by ghost** [comment]
@kofaysi can this Issue be closed?

**Comment by kofaysi** [comment]
I made a stupid mistake and merged the PR into staging only now. I guess, a code will be attached soon. So, the issue should stay open until the PR is accepted or dismissed, right?

**Comment by ghost** [comment]
if there is a PR the issue can be closed.
