### ISSUE TITLE
Unexpectedly closes its session in Google Chrome

### ISSUE THREAD

**Issue by BRoehling** [joomla/joomla-cms#23772]
### Steps to reproduce the issue

Open and fiddle with Joomla 3.9.2 in Google Chrome Version 71.0.3578.98 (Offizieller Build) (32-Bit)

### Expected result

session is active for defined session time (from global configuration)

### Actual result

Super user is logged out after 1-3 minutes (session time set to: 999 minutes)

### System information (as much as possible)

Joomla 3.9.2 German

Einstellung | Wert
 
PHP erstellt für | Linux v1361.ncsrv.de 4.4.0-042stab132.1 #1 SMP Wed Jul 11 13:51:30 MSK 2018 x86_64
Datenbanktyp | mysql
Datenbankversion | 5.7.25-0ubuntu0.16.04.2
Datenbankzeichensatz | utf8_general_ci
Datenbankverbindungszeichensatz | utf8mb4_general_ci
PHP-Version | 7.2.14
Webserver | Apache
PHP-Interface für den Webserver | fpm-fcgi
Joomla!-Version | Joomla! 3.9.2 Stable [ Amani ] 15-January-2019 15:00 GMT
Joomla!-Plattform-Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Browsererkennung | Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 OPR/58.0.3135.47

### Additional comments

It doesn't happen in Opera Version: 58.0.3135.47
About the other web-browsers I haven't tried.

**Comment by brianteeman** [comment]
I have been using 
Version 71.0.3578.98 (Official Build) (64-bit)
and havent experienced any problems

**Comment by brianteeman** [comment]
Maybe it was a bug in that 32 bit version of chrome or even a browser plugin.

As of today the latest release (I just updated) is 
v. 72.0.3626.81

**Comment by PhilETaylor** [comment]
Sessions are not expired or "closed" by a browser. 

Sessions are handled purely server side only.

All the browser contains is a session cookie. 

The cookie is sent with every request, that is the only responsibility of a browser with regard to sessions.

If you are telling me the Google Chrome is failing to send cookies with requests, then I would say that you are mistaken, else 100% of the web where you have to login would be broken in Google Chrome right now.

**Comment by brndt** [comment]
I have the same problem with Chrome (72.0.3626.96, 64 bit)/Opera(58.0.3135.53)
Joomla 3.9.3.

If you reopen your browser or restart your PC, you need to re-login.
I suppose "Remember Me" doesn't places a cookie on the user's computer.

Meanwhile Firefox works perfectly.

**Comment by ghost** [comment]
@Quy isn't this a Duplicate of #22959?

**Comment by Quy** [comment]
I assume so. Maybe close one of them or both if they are no longer an issue.

**Comment by ghost** [comment]
closed as stated above; Issue can always be reopened.

**Comment by brndt** [comment]
I can confirm this problem still occurs.
But if you disable this option in Google Chrome

Preload pages for faster browsing and searching: Browsers use an IP address to load a webpage. When you visit a webpage, Chrome can look up the IP addresses of all the page's links and load the ones you might navigate to next. If you turn this setting on, websites and any embedded content that are preloaded can set and read their own cookies as if you had visited them, even if you don't. 

Everything is ok - cookie isn't deleted.
The problem is that this option is used by default by Google Chrome.

**Comment by brndt** [comment]
Duplicate of #26386
