### ISSUE TITLE
[J4.0] Make the comparable read-only original file copyable as well

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#23775]
### Is your feature request related to a problem? Please describe.
I am using a joomla.com free website with Joomla! 4.0.0-alpha7-dev installed. I have the main Cassiopeia template, a modified version of that template and another template which I had written from scratch for J3.9 and Bootstrap 4x. I am switching between all three templates to compare them.

Using Joomla! 4.0.0-alpha7-dev I had a notification of changes to template overrides in my own template. 

In the template files editor it is possible to switch on both 'Show original' - which appears to the right of the override - and 'Show differences' which shows below the two files (see first screenshot below).

As my override was based on a J3.9 file, I would like to have a three-way comparison, which I intend to do using an editor such as Notepad++, with my override, the J3.9 file it was based on and the new J4.0 version. 

However, the 'read-only' option is literally just that. It is not possible to highlight the text and copy it. The only way to get it is to create yet another override, which in many instances, such as this html/com_content/category/blog_item.php creates all the other override files for 'category' as well, which I don't need and then have to delete after copying the code from the file I do need.

Additionally, the colours in the 'Show diff' section are confusing. The code highlighted in green would imply that it is the 'correct' or 'new' code and the red code the opposite. In fact, the obsolete code in the override is the green code and the new code in the original, read-only, file is highlighted in red.

![image](https://user-images.githubusercontent.com/36987494/52296006-334b5c00-2975-11e9-957c-21e8d8c403fc.png)

### Describe the solution you'd like
1. Allow the code from the read-only file to be copyable
2. Switch the 'show diff' highlight colours around

### Additional context
Regarding the notifications: 
The first notification is in the control panel as you log in: 
![image](https://user-images.githubusercontent.com/36987494/52295300-62f96480-2973-11e9-99e6-3b90c08556a7.png)

Clicking this takes you straight to the template files section and indicates which template has files to check:
![image](https://user-images.githubusercontent.com/36987494/52295575-15312c00-2974-11e9-8604-7d73f824dd1a.png)

It is necessary to click on the template name to view which files to check. The 'change found' text is not clickable; it would be good if it was and took you straight to the 'updated files' tab in the editor where the changes can be viewed:
![image](https://user-images.githubusercontent.com/36987494/52295698-604b3f00-2974-11e9-8249-1990a52c68ae.png)
[I'm not sure that 'update action' is the correct column heading as it suggest that a Joomla update is required. Perhaps 'update source' would be more appropriate?]

Having got here the first time, I discovered that the updates are not actually updates to the overrides as suggested, but the original files on which they were based.

**Comment by astridx** [comment]
> @Scrabble96 Additionally, the colors in the 'Show diff' section are confusing. The code highlighted in green would imply that it is the 'correct' or 'new' code and the red code the opposite. In fact, the obsolete code in the override is the green code and the new code in the original, read-only, file is highlighted in red.

Here I do not share your opinion. The `diff view` is made to check after an update, whether the own Overrides should be adjusted. So whether an update in the core files improvements have been added or even security holes were closed. So the green Code is not obsolete. The green Code is the one you should orient yourself on.
More information you can find in the documentation: https://docs.joomla.org/J4.x:Improved_Override_Management

**Comment by Scrabble96** [comment]
> 
> Here I do not share your opinion... 

Fair enough. I'll just have to get used to it.
Thank you for initiating the two PRs, though, @astridx
