### ISSUE TITLE
[RFC] Migration from J3 to J4

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23778]
To help assist users migrate from J3 to J4, I think it might be wise to automate things a little from the template side of things.

For example, in the Protostar template, we use position-7 for the right hand side, and `sidebar-right` for Cassiopeia.

So it would be nice to have a script in place that automatically changes the positions of modules to their relatively position in J4, assuming Isis it the default template being used.

**Comment by brianteeman** [comment]
Isis is admin and Cassiopeia is front end

**Comment by Fedik** [comment]
the idea not bad,

I see only one potential issue, when Cassiopeia is default template, but user also have a custom template with the same position name as in Cassiopeia, and this custom template are assigned to specific menu.

**Comment by C-Lodder** [comment]
@brianteeman I meant Protostar

**Comment by brianteeman** [comment]
@C-Lodder ahah

Its a nice idea to have a "mapping table" that will map the protostar positions to the cassiopeia positions

I would only run it if the user is actively using the protostar template though. Most 3pd templates use their own position names but there may be one or two positions that are named the same. We wouldnt want to do a partial "migration"

**Comment by Bakual** [comment]
You could have a button in the Cassiopeia Template to trigger that migration, but I'm not sure if it's really that useful or if it is more confusing for all those who didn't use Protostar.

**Comment by C-Lodder** [comment]
Of course. It would have to be a full migration, based on people havving Protostar set as their only template.

Not fussed about how the migrations takes place, be it on the actual update itself or a button in the template settings, but either way, it will save the need to assign all modules again

**Comment by jwaisner** [comment]
This RFC has not been updated in almost a year. Closing this out. If there is a feature that is requested for J4 please open a feature request.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23778">issues.joomla.org/tracker/joomla-cms/23778</a>.</sub>

**Comment by brianteeman** [comment]
This should not be closed. Just think a little PLEASE before closing something

**Comment by jwaisner** [comment]
I stand by my closing of this issue. If it is a feature request, then an item needs opened as such.

**Comment by C-Lodder** [comment]
@jwaisner I opened this as an `[RFC]`, meaning Request For Comment. It can be considered a feature request or something that **should** simply be done in core.

I don't need to use a premade template for feature requests, so please stop closing this.

**Comment by wilsonge** [comment]
The problem with this is - it's very hard to detect that protostar is the only used template. Because you can set template overrides in menu items etc. I think practically the use case is rare and maybe we could just say that this use case is a higher priority....

**Comment by brianteeman** [comment]
I guess this can be closed now that j4 is released?
