### ISSUE TITLE
Article Category with access set to specific group doesn't come up in the Article search tool category list

### ISSUE THREAD

**Issue by sveinaberg** [joomla/joomla-cms#23773]
### Steps to reproduce the issue
Create an article category with access set to a custom ![screen shot 2019-02-05 at 17 20 37](https://issues.joomla.org/uploads/1/25d33d6b213306f70344b3642ea081eb.jpg)access group. 

### Expected result
In the Article search tool, this category should show up in the category search field

### Actual result
In the Article search tool, this category will not show up in the category search field

### System information (as much as possible)
Joomla 3.9.2

### Additional comments

![screen shot 2019-02-05 at 17 20 38](https://issues.joomla.org/uploads/1/1d42870a12b2793cf685394ac0a9ae13.jpg)

**Comment by brianteeman** [comment]
Is the person doing the search in the group. If not then it would be the expected behaviour (i think)

**Comment by tonypartridge** [comment]
As Brian points out it’s likely the user doing the search is not in the group. You might be a super user but that doesn’t override custom ACL

**Comment by sveinaberg** [comment]
This is to me a weird behavior. In the back-end, as a super user, one should be able to find any article by searching for the category, whether the super user is a member of said group or not?

**Comment by tonypartridge** [comment]
Not at all, that’s not how ACL works. Backend isn’t only for a single group. 

In your scenario you are assuming everyone should see everything in the backend.

**Comment by sveinaberg** [comment]
But shouldn't the super user be able to access all groups in the back-end? Do I need to add the super user to all groups in order to manage all content?

**Comment by tonypartridge** [comment]
Only if you add the super user to that group. ACL doesn't assume Super users are the highest possible level. It just sets defaults. If you create an isolated usergroup then it is isolated from everyone but that group.

**Comment by mbabker** [comment]
Access groups does not use ACL.  So yes, your super user group needs to be added to every access group.

**Comment by sveinaberg** [comment]
OK, that is doable. Thanks for your help!

**Comment by Quy** [comment]
Closing as expected behavior.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23773">issues.joomla.org/tracker/joomla-cms/23773</a>.</sub>
