### ISSUE TITLE
Missing verification code warning fail

### ISSUE THREAD

**Issue by ava-sig** [joomla/joomla-cms#23770]
### Steps to reproduce the issue
Reset a password for a simple user. Input user and verification code received in the mail. Input new password and confirmation password.

### Expected result
Password changed successfully

### Actual result
Password changed successfully but two warnings appear.
Error warning is not a real warning because password was changed successfully.

### System information (as much as possible)
MacOs,  Chrome - both latest.
Joomla 3.8.13 - not sure if this is fixed in newer Joomla versions.

### Additional comments
![image](https://user-images.githubusercontent.com/3773948/52255318-c0ad9280-291a-11e9-8dea-aa9a9ae751d7.png)

**Comment by PhilETaylor** [comment]
> Joomla 3.8.13 - not sure if this is fixed in newer Joomla versions.

Please dont report issues in old versions. Upgrade your site and see if that fixes the problem

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23770">issues.joomla.org/tracker/joomla-cms/23770</a>.</sub>
