### ISSUE TITLE
[4.0] System page it too hard to scan

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23777]
### What needs to be fixed

Backend "System" page

### Why this should be fixed

I understand the reasoning behind this page and it has potential to be a great way to quickly access different pages within the backend, however it's taking far too long to scan.

Currently, I believe there are 31 items on the System page which are separated into list groups.
Due to the fact that there are so many items that are purely text without any visual indicators, such as icons, it has an impact on muscle memory.

We've even had a user over on JSE asking where to find the Plugin Manager in J4 alpha.

### How would you fix it

@coolcat-creations  @rdeutz

**Comment by brianteeman** [comment]
Also see #23675

**Comment by lllopo** [comment]
I second this. The page is really hard to read and find stuff. Because of too many items it either needs reorganization or adding some quick search of sorts ... or both.

**Comment by infograf768** [comment]
There is a way to add icons to every item listed.
Would that be better/sufficient?
For example:
<img width="382" alt="screen shot 2019-02-08 at 11 43 32" src="https://user-images.githubusercontent.com/869724/52473742-d29b6980-2b96-11e9-9d8f-b77e3605c5a1.png">

**Comment by C-Lodder** [comment]
@infograf768 already tried and it barely helps

**Comment by infograf768** [comment]
Then the only other solution I see would be to use accordeon sliders. One slider per section.
We may lose the badges though when sliders are closed, which means a kind of warning icon should be added to the title of the slider when necessary i.e. when items in that section are displaying a badge.

**Comment by Bakual** [comment]
The warnings (eg available updates) have to be done differently anyway, because they should not be checked on each pageload. So I wouldn't factor that into a redesign.

Accordeons may be a solution. But honestly, the elephant in the room is that there are way to many items on that page. You can paint it with another colour or try to hide part of it, but the elephant is still there 😆

**Comment by infograf768** [comment]
> The warnings (eg available updates) have to be done differently anyway, because they should not be checked on each pageload. So I wouldn't factor that into a redesign.

Correct for Extensions and Joomla Update, but not for Discover, Checkin or Post Install messages as these are very convenient to be informed about straight away.

If we do not care about any badge, then we can make a kind of menu tree in that page with the sections as headers and the items as sub as we have in 3.x, the difference being that it would be in a specific page instead of the main admin menu.

Good luck in any case for the custom admin menu feature.

**Comment by Bakual** [comment]
> Correct for Extensions and Joomla Update, but not for Discover, Checkin or Post Install messages as these are very convenient to be informed about straight away.

You can use regular messages or a dedicated message hub or whatever. That can be decided independant of any design. It doesn't have to be a label strapped to the item. That's what I meant :)

**Comment by infograf768** [comment]
Indeed

**Comment by lllopo** [comment]
I think with a little some re-organisation, it could become a bit more readable. Maybe like this :
![joom](https://user-images.githubusercontent.com/5485902/52480380-35e7c480-2bb4-11e9-8d67-b974a47a8d5b.jpg)

- bigger titles
- contextually grouped columns
- separate languages section to reduce the clutter in 'manage'
- gouped site and admin modules page (this can be an in-page filter)

**Comment by lllopo** [comment]
I'm also not sure where 'redirects' and 'content security policy' should fall. Maybe they should move to the 'setup' and 'access' groups respectively.

**Comment by brianteeman** [comment]
Sounds much better to me

**Comment by coolcat-creations** [comment]
This page has another big issue, For example (one of many) If you are in Install Languages there is no way to click directly on Content Languages. Suggestions how to fix this bit messed up structure are welcome :-)

**Comment by brianteeman** [comment]
Already discussed extensively - guess you missed it

**Comment by C-Lodder** [comment]
Closing as template team are working on backend template
