### ISSUE TITLE
Can you give the breadcrumbs module an id ?

### ISSUE THREAD

**Issue by BRoehling** [joomla/joomla-cms#23776]
### Is your feature request related to a problem? Please describe.

I'm trying to use a smooth scroll function which scrolls to an anchor by using a div id.
Unfortunately I can't give the breadcrumbs module no id, it only accepts a class.

### Describe the solution you'd like

Have an option to assign an id to the breadcrumbs module.
Do you guys know a workaround?

**Comment by Bakual** [comment]
You could use an override or alternative layout and put the ID into that. That's why that feature exists.
