### ISSUE TITLE
[4.0] Wrong color of form in edit article

### ISSUE THREAD

**Issue by bahl24** [joomla/joomla-cms#23781]
### Steps to reproduce the issue
Content->Article->click on an existing article to get Articles:Edit page
Notice the color of options under 'Status' on right side.

### Expected result
The options should be colored like published->green etc. like other components.eg-
![screenshot from 2019-02-05 21-19-32](https://user-images.githubusercontent.com/36095178/52355981-6535ee80-2a59-11e9-9695-3d203d92298f.png)

### Actual result
![screenshot from 2019-02-05 21-19-57](https://user-images.githubusercontent.com/36095178/52356095-a0d0b880-2a59-11e9-9645-ab9c7f4d2698.png)

**Comment by Quy** [comment]
See PR #23782.

FYI: It is not necessary to open an issue if you already have a pull request for it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23781">issues.joomla.org/tracker/joomla-cms/23781</a>.</sub>

**Comment by chmst** [comment]
@bahl24 meanwhile the design of the backend is new. I think we dan close this now?
