### ISSUE TITLE
[4.0] Missing language string on permissions page

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23794]
### Steps to reproduce the issue

1. Go to the User Manager
2. Click on any user
3. Click the "permissions" icon

You'll notice the missing lang string for `COM_WORKFLOW_DEFAULT_WORKFLOW `

### Actual result

![screeny](https://user-images.githubusercontent.com/2019801/52468896-ebe5eb00-2b81-11e9-93b1-c03a589ee9a1.png)

**Comment by SharkyKZ** [comment]
Asset titles are not translatable.

**Comment by infograf768** [comment]
Set Debug lang on.
The string exists
COM_WORKFLOW_DEFAULT_WORKFLOW="Joomla! Default"
Not only the language file is not loaded but the Asset Title Column values are NOT translatable at all.
Published, etc are also not translated at all

**Comment by C-Lodder** [comment]
Whether is translatable or not, something should be done as it's creating a lot of unecessary whitespace

And that just looks like a plain bug on a fresh installation

**Comment by infograf768** [comment]
> something should be done

Agree.

@bembelimen

**Comment by infograf768** [comment]
Evidently we need to modify to
`<?php echo $this->escape(Text::_($item->title)); ?>`
but it is not sufficient as the correct ini files are not loaded in most cases.

**Comment by brianteeman** [comment]
It is nothing to do with translations or language strings. 

This column gets its value from the assets table
```
SELECT a.id, a.name, a.title, a.level, a.lft, a.rgt
FROM `__assets` AS `a`
ORDER BY a.lft asc LIMIT 20
```

The value in the assets table is COM_WORKFLOW_DEFAULT_WORKFLOW

So the problem is not here but with the code that creates the record in the assets table which is actually an error in the installation sql.

Pull request incoming

**Comment by brianteeman** [comment]
Please test #23976

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/23992
