### ISSUE TITLE
[4.0] Calendar tweaks

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23795]
### Steps to reproduce the issue

1. Open an article in the Joomla backend
2. Open the calendar found under "Start Publishing"

### Actual result

- `Clear`, `Today` and `Close` don't look like clickable buttons at all.
- The border above `Sat` and `wk` seems to be double the size
- An SVG clock icons as opposed to PNG

![screeny2](https://user-images.githubusercontent.com/2019801/52469116-7a5a6c80-2b82-11e9-8fbd-761a716348ab.png)

**Comment by hardik-codes** [comment]
@C-Lodder should the ```Clear```,```Today```and ```Close```have spacing between them so that they look like clickable buttons

**Comment by C-Lodder** [comment]
@hardik-codes yes

**Comment by hardik-codes** [comment]
@C-Lodder How do I get svg clock icon?

**Comment by C-Lodder** [comment]
@hardik-codes https://raw.githubusercontent.com/encharm/Font-Awesome-SVG-PNG/master/black/svg/clock-o.svg

**Comment by hardik-codes** [comment]
@C-Lodder could you please help with the svg?
I'm already done with the other two things in the issue

**Comment by hardik-codes** [comment]
@C-Lodder I'm still stuck with the implementation of the svg clock icon ?

**Comment by C-Lodder** [comment]
@hardik-codes : https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/system/css/fields/calendar.css#L152

You will need to encode the SVG for CSS usage, using a tool like this: https://yoksel.github.io/url-encoder/

**Comment by hardik-codes** [comment]
@C-Lodder Which css file contains  the code for the ```Clear```, ```Today``` and ```Close``` buttons.

**Comment by C-Lodder** [comment]
You dont need to modify the CSS file. The buttons will most likely be injected from the JS file but dont worry about those, cause I'll be rewriting the calendar as a custom element soon

**Comment by hardik-codes** [comment]
Ok then. 
But will I not be needing the CSS file to reduce the border above```Sat``` and ```wk```?

**Comment by C-Lodder** [comment]
I'm not sure about that. I haven't debugged it properly, but I would have thought it's something in the CSS file that needs fixing

**Comment by hardik-codes** [comment]
Ok then I'll try it on my part. Let me know the css file please.

**Comment by C-Lodder** [comment]
calendar.css

**Comment by hardik-codes** [comment]
@C-Lodder please review PR#23903

**Comment by C-Lodder** [comment]
Closing as we have a PR: #23903
