### ISSUE TITLE
[4.0] Status dropdown arrows needs changing colour

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23793]
### Steps to reproduce the issue

1. Go yo your Plugin Manager
2. Open any plugin
3. Switch the Status between "enabled" and "disabled"

You'll notice the dropdown arrow is grey and should be white, so it can be properly seen

### Actual result

![screenshot_2019-02-08 plugins authentication - joomla - joomla 4 - administration](https://user-images.githubusercontent.com/2019801/52468674-4e8ab700-2b81-11e9-8e69-bbde3793d53a.png)

**Comment by puneeth-chanda** [comment]
![image](https://user-images.githubusercontent.com/43813460/52493704-24251200-2bf2-11e9-9de6-08c5af9fd46c.png)
is it ok!

**Comment by C-Lodder** [comment]
@puneeth2001 Look at the red dropdown (Disabled). It's red with a grey arrow. The arrow should be white for colour contrast purposes

**Comment by coolcat-creations** [comment]
Can we please just style it according to the other Dropdowns and use same classes (for example save button)

**Comment by C-Lodder** [comment]
@coolcat-creations So you want to remove the background (red/green) from the dropdown, depending on which item is selected?

**Comment by ghost** [comment]
closed as having Pull Request #24099
