### ISSUE TITLE
[4.0] Language Overrides - search box

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23798]
### Steps to reproduce the issue

1. Go to `administrator/index.php?option=com_languages&view=overrides`

You'll notice the search box has grey buttons as is on the left hand side, whereas on other pages, it's on the right hand side with blue buttons

### Actual result

![screeny3](https://user-images.githubusercontent.com/2019801/52472545-7848db80-2b8b-11e9-9912-a1f3e721856b.png)

**Comment by hardik-codes** [comment]
@C-Lodder the searchbox is also a little bit different than on other pages as other searchboxes do not have a clear button and the dropdown menu from number of results on the page, unlike this one. I'll be aligning it to the right ad changing the color to blue. Is that okay?

**Comment by C-Lodder** [comment]
yup that's fine

**Comment by infograf768** [comment]
The searchbox and, generally speaking, the overrides manager have been modified in 3.9.
Let's wait 3.9 is merged into 4.0 to take care of this.

**Comment by hardik-codes** [comment]
So should I leave this issue untouched ?

**Comment by brianteeman** [comment]
If only j4 wasnt over 1000 commits behind staging life would be so much easier </rant>

**Comment by puneeth-chanda** [comment]
can I work on this issue now?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23798">issues.joomla.org/tracker/joomla-cms/23798</a>.</sub>

**Comment by hardik-codes** [comment]
@puneeth2001 I'm already working on it and waiting for the commits to be merged

**Comment by infograf768** [comment]
Folks, I remind you that there were important changes in 3.8-9 for this feature and that it has not yet been ported to 4.0.
Look at a 3.9.3 site to see what we have there.
I suggest to wait until more stuff is ported to 4.0.

**Comment by hardik-codes** [comment]
@infograf768 I have got a patch ready should I submit it now ?

**Comment by infograf768** [comment]
Be patient please...
https://github.com/joomla/joomla-cms/pull/22107 has not been yet merged in 4.0
Once done, patch welcome, but please read the comments in that PR.

**Comment by C-Lodder** [comment]
Closing as template team are working on backend template

**Comment by infograf768** [comment]
It concerns more than template.
Please test https://github.com/joomla/joomla-cms/pull/24553

and read my note at the bottom of the description of the issue.
