### ISSUE TITLE
[4.0] Template Styles - Close button not working

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23799]
### Steps to reproduce the issue

1. Go to `/administrator/index.php?option=com_templates&view=styles`
2. Open the Cassiopeia template
3. Click the "Close" button

### Expected result

Directed back to the list view

### Actual result

Nothing happens

**Comment by brianteeman** [comment]
Can you check other close buttons - I think I saw the same in other places earlier today

**Comment by C-Lodder** [comment]
@brianteeman I think the other ones are working fine, however there may be some that I've missed

**Comment by hardik-codes** [comment]
The close button is  working fine for me @C-Lodder 
My joomla version: Joomla! 4.0.0-alpha7-dev

**Comment by puneeth-chanda** [comment]
![screenshot from 2019-02-11 17-12-48](https://user-images.githubusercontent.com/43813460/52561477-831c9e00-2e21-11e9-949d-59b233d16769.png)
I am getting this error

**Comment by C-Lodder** [comment]
@puneeth2001 I've updated the test link in my OP. It should have been `view=styles`, not `view=style`

**Comment by puneeth-chanda** [comment]
@C-Lodder it is working for me.

**Comment by C-Lodder** [comment]
@hardik-codes @puneeth2001 I never work with downloadable alpha's, but instead the latest (cutting edge) code from the repo. I'll refetch the code again tonight and test, as the issue may have been resolved.

**Comment by C-Lodder** [comment]
Seems to be working now
