### ISSUE TITLE
[4.0] Media Manager file info overlapping text

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23796]
### Steps to reproduce the issue

1. Go to the Media Manager
2. Click the "info" icon in the top right to reveal info mation about selected images
3. Reduce your browser window until the next starts overlapping.

### Actual result

![screenshot_2019-02-08 media - joomla 4 - administration](https://user-images.githubusercontent.com/2019801/52469580-b6da9800-2b83-11e9-8165-8a345ababc2b.png)

**Comment by infograf768** [comment]
I have patch ready for that. I prepared it including rtl in general for com_media and I am waiting for the big com_media PR to be merged ( https://github.com/joomla/joomla-cms/pull/23756 )

I modified the code to use `<ul><li>`

For example in RTL, my PR gives:
<img width="1352" alt="media_manager_rtl_persian" src="https://user-images.githubusercontent.com/869724/52469689-74698900-2b8c-11e9-9374-86ad768bf481.png">

**Comment by infograf768** [comment]
@C-Lodder 
Please look at
https://github.com/joomla/joomla-cms/pull/23756#issuecomment-460207089

**Comment by C-Lodder** [comment]
@infograf768 seems fine. Only thing I'd changed based on your screenshot is add a small bottom margin for each `<li>`...maybe `margin-bottom: .3rem`

**Comment by infograf768** [comment]
Noted.

**Comment by hardik-codes** [comment]
@infograf768 how by the use of ```<ul><li>``` were you able to achieve the desired effect ? Please help with the code

**Comment by hardik-codes** [comment]
@infograf768 how do I install any RTL language. Because the install button on this page ```administrator/index.php?option=com_installer&view=languages``` doesn't seem to be working

**Comment by infograf768** [comment]
this has been solved already and rtl patch too which i will post asap

**Comment by infograf768** [comment]
see 
https://github.com/joomla/joomla-cms/pull/23902 for ltr

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/24043 for RTL + some other stuff.
