### ISSUE TITLE
[4.0] Console error on Article edit page

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23792]
### Steps to reproduce the issue

1. Open the browser console
2. Go to create a new article in the Joomla backend
2. Reduce the browser window width until you see an error in the console

### Actual result

> TypeError: this.buttonSelect is null     joomla-field-user.min.js:1:1585

**Comment by amitranjan2** [comment]
issue confirmed
![image](https://user-images.githubusercontent.com/41797766/52479584-23c74f80-2bcf-11e9-93bb-5ba715eaed84.png)
this error in Google chrome


 this.buttonSelect is null    ----this error in Firefox

**Comment by Quy** [comment]
Please test PR #23881<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23792">issues.joomla.org/tracker/joomla-cms/23792</a>.</sub>
