### ISSUE TITLE
[4.0] User dropdown menu need some sort of box-shadow

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23791]
### What needs to be fixed

This will only apply to some pages in the backend, but if you look at the screenshot below, you'll notice the User menu dropdown pretty much blends in with the content and thus hard to see:

![screenshot_2019-02-08 mass mail users - joomla 4 - administration](https://user-images.githubusercontent.com/2019801/52468489-c2788f80-2b80-11e9-83fa-3fca320df270.png)

**Comment by hardik-codes** [comment]
Does the shadow needs to be on all 3 sides?

**Comment by C-Lodder** [comment]
Ideally yes as the site may be in RTL

**Comment by hardik-codes** [comment]
Any specific number of pixels in width or can I use anything appropriate?

**Comment by C-Lodder** [comment]
Not my choice. Submit a PR with what you feel works

**Comment by hardik-codes** [comment]
In which css selector the box-shadow attribute has to go because it is being over-ridden in many. Also changes are to be done in all these 3 file ```administrator/templates/atum/scss/template-rtl.scss``` ,  ```administrator/templates/atum/scss/blocks/_header.scss``` and ```templates/cassiopeia/scss/vendor/bootstrap/_dropdown.scss``` ?

**Comment by C-Lodder** [comment]
`administrator/templates/atum/scss/blocks/_header.scss`

**Comment by hardik-codes** [comment]
I've added box-shadow to the selector ```.dropdown-menu``` but it doesn't work for me. I think so, I have to run the command ```npm run build:css``` to see the desired changes, Am I right?

**Comment by C-Lodder** [comment]
correct ;)

**Comment by Quy** [comment]
Please test PR #23833<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23791">issues.joomla.org/tracker/joomla-cms/23791</a>.</sub>
