### ISSUE TITLE
[4.0] [IE11] Client dropdown mis-alignment

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23807]
### Steps to reproduce the issue

Go to `administrator/index.php?option=com_modules&view=modules`

### Actual result

![screeny22](https://user-images.githubusercontent.com/2019801/52477403-ae8d5780-2b99-11e9-83a2-d7c25150b016.png)

**Comment by ghost** [comment]
closed as having Pull Request #24421
