### ISSUE TITLE
[4.0] Menu Assignment - toggle checkboxes

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23801]
### Steps to reproduce the issue

1. Go to `administrator/index.php?option=com_templates&view=style`
2. Open the Cassiopeia template
3. Go to the "Menu Assignment" tab
4. Use the buttons to toggle the selection of all checkboxes

### Expected result

Toggle selection checks/unchecks the checkboxes

### Actual result

Not working as expected

![screeny4](https://user-images.githubusercontent.com/2019801/52472999-a2e76400-2b8c-11e9-8caf-f72b55111e3b.png)

**Comment by amitranjan2** [comment]
issue confirmed

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/23844
