### ISSUE TITLE
[4.0] [IE11] - Login page

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23805]
### Steps to reproduce the issue

Visit the backend login page in IE11

You'll notice the background placement is a little weird (see screenshot)

### Actual result

![ie11](https://user-images.githubusercontent.com/2019801/52475664-19d42b00-2b94-11e9-847c-006468565c17.png)

**Comment by puneeth-chanda** [comment]
What do you want to change here?

**Comment by C-Lodder** [comment]
@puneeth2001 well as you can see, the background is shifted to the bottom right of the page and it should fill the entire page.

Simple solution:

```
.view-login .login-bg-grad {
    position: fixed;
    top: 0;        << add this
    left: 0;       << add this
    z-index: -1;
    width: 100vw;
    height: 100vh;
    background-image: linear-gradient(45deg,rgba(43,92,145,.9) 30%,rgba(59,151,249,.2));
}
```

**Comment by puneeth-chanda** [comment]
![image](https://user-images.githubusercontent.com/43813460/52480323-5a9e6500-2bd1-11e9-9af2-40f6aa29007d.png)
I am not getting anything like that

**Comment by C-Lodder** [comment]
@puneeth2001 The issue is in IE11, not Chrome

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/23945
