### ISSUE TITLE
[4.0] [IE11] Notifications dropdown is very wide

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23808]
### Steps to reproduce the issue

See screenshot below

![screeny3](https://user-images.githubusercontent.com/2019801/52477540-252a5500-2b9a-11e9-8b92-be18000b09a3.png)

**Comment by vijay9908** [comment]
What are the resize parameters?

**Comment by C-Lodder** [comment]
Compare the dropdown on any evergreen browser, and that's what the width should be

**Comment by ghost** [comment]
@vijay9908 are you working on it?

**Comment by vijay9908** [comment]
No sir

Regards,
Vijay

**Comment by ghost** [comment]
@vijay9908 sorry, i missunderstood https://github.com/joomla/joomla-cms/issues/23808#issuecomment-462655173

**Comment by C-Lodder** [comment]
Closing as template team are working on backend template
