### ISSUE TITLE
[4.0] Edit Style - Select Logo

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23803]
### Steps to reproduce the issue

1. Go to `administrator/index.php?option=com_templates&view=styles`
2. Open the Cassiopeia template
3. Go to the "Advanced" tab
4. Try and select a logo

### Expected result

Opens a a modal with the Media Manager

### Actual result

Nothing happens

**Comment by hardik-codes** [comment]
![23803](https://user-images.githubusercontent.com/34353697/52521585-390baf00-2c9f-11e9-8c60-67bb7da266e4.png)

This is what I am getting on visiting the above page

**Comment by amitranjan2** [comment]
@C-Lodder  

@hardik-codes correct link should be  administrator/index.php?option=com_templates&view=styles
![image](https://user-images.githubusercontent.com/41797766/52522350-3793b400-2caa-11e9-8674-d7a3b89b997c.png)

**Comment by C-Lodder** [comment]
Oops thanks. I've updated my original post with the correct link

**Comment by bahl24** [comment]
@C-Lodder Modal is visible when you click on select button
![screenshot from 2019-02-18 00-19-21](https://user-images.githubusercontent.com/36095178/52917555-ec654b00-3312-11e9-8781-194302706c25.png)

**Comment by C-Lodder** [comment]
Seems to be working now
