### ISSUE TITLE
[4.0] [IE11] Tabs are stacked

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23809]
### Steps to reproduce the issue

In IE11, go to `/administrator/index.php?option=com_config`

### Expected result

Tabs should be next to eachother

### Actual result

Tabs are stacked

![screeny4](https://user-images.githubusercontent.com/2019801/52477599-6a4e8700-2b9a-11e9-83ad-645e5ca267d0.png)

**Comment by ghost** [comment]
closed as having Pull Request #24420

**Comment by C-Lodder** [comment]
Franz, could you reopen please as the PR was closed. Thanks

**Comment by ghost** [comment]
Reopened as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23809">issues.joomla.org/tracker/joomla-cms/23809</a>.</sub>

**Comment by Quy** [comment]
Is PR #23780 not a fix?

**Comment by ghost** [comment]
@Quy i thought also as @dgrammatiko wrote in #24420 but it seems not, so @C-Lodder wanted it reopened.

**Comment by dgrammatiko** [comment]
#23780 fixes the tabs and the tab state as well, so this can be closed

**Comment by ghost** [comment]
Closed as stated above, thanks @dgrammatiko <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23809">issues.joomla.org/tracker/joomla-cms/23809</a>.</sub>

**Comment by C-Lodder** [comment]
@franz-wohlkoenig https://github.com/joomla/joomla-cms/pull/23780 was closed so this can be reopened
