### ISSUE TITLE
[4.0] [Mobile] Small screen toolbar toggle unstyled & void

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#23815]
### Steps to reproduce the issue
Markup exists for a toolar toggle on smaller screens (https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/index.php#L99).

This toggle does not do anything

### Expected result
Toolbar displayed/hidden when toggle button is clicked

### Actual result
Nothing. Just an un-styled toggle button..

![image](https://user-images.githubusercontent.com/2803503/52482950-878b5180-2baa-11e9-8ccd-f2c0d4cd1aa4.png)

**Comment by hardik-codes** [comment]
I don't see the toolbar toggle button in my machine . Anything specific needs to be done to view this

**Comment by ciar4n** [comment]
Reduce the browser viewport size.

**Comment by hardik-codes** [comment]
I did so but I'm not seeing the toggle button

**Comment by ciar4n** [comment]
List view (articles). Visible in both Chrome and FF.

**Comment by hardik-codes** [comment]
Got it and working on it

**Comment by puneeth2001** [comment]
@hardik-codes are you still working on it if not I'll do it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23815">issues.joomla.org/tracker/joomla-cms/23815</a>.</sub>

**Comment by hardik-codes** [comment]
Yeah working on it

**Comment by ghost** [comment]
closed as having Pull Request #24083
