### ISSUE TITLE
[4.0] [Mobile] Title column in list views needing min-width

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#23816]
### Steps to reproduce the issue
Considering it is usually the most relevant column in the list views, the title column needs a minimum width for smaller screens. 

### Expected result
![image](https://user-images.githubusercontent.com/2803503/52483252-4b0c2580-2bab-11e9-92b9-3a432401ff21.png)

### Actual result
![image](https://user-images.githubusercontent.com/2803503/52483282-5f502280-2bab-11e9-9e81-8df354f94765.png)

**Comment by hardik-codes** [comment]
@ciar4n how can I reproduce this issue ?

**Comment by ciar4n** [comment]
Reduce browser width in article list view

**Comment by hardik-codes** [comment]
@ciar4n what should be the minimum width according to you ?

**Comment by ciar4n** [comment]
14rem should do it.

**Comment by hardik-codes** [comment]
Ok
Working on it

**Comment by ghost** [comment]
closed as having Pull Request #23886

**Comment by brianteeman** [comment]
I can no longer replicate this 
![image](https://user-images.githubusercontent.com/1296369/70813691-cfc66200-1dc1-11ea-85bc-e808c1c6ae87.png)

**Comment by Quy** [comment]
Reproducible.

![23816](https://user-images.githubusercontent.com/368084/70824043-2b7af600-1d96-11ea-8e03-809360ec194a.jpg)

**Comment by brianteeman** [comment]
Is that mobile as stated in the issue ?

**Comment by Quy** [comment]
In the description, it states for smaller screens so I assume tablets too.

**Comment by vijay9908** [comment]
Breaking words instead of all letters with inline flex in css , O
r setting a minimum size would fix the issue I guess

**Comment by Quy** [comment]
Due to too many columns to fit in mobile view (tablet), which columns can be hidden? `*` denotes to display.

Stage *
Featured *
Status *
Title *
Access
Author
Association
Language
Date Created
Hits
ID

**Comment by Quy** [comment]
Closing in favor of #32912 that is a global issue including this issue.
