### ISSUE TITLE
[4.0] Unable to scroll when previewing an article

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23812]
### Steps to reproduce the issue

1. Open any article in your Article Manager
2. Click the "Preview" button which will open up a modal

You'll notice that scrolling is not possible within the modal

**Comment by amitranjan2** [comment]
@C-Lodder  can you give me the system information?
its working fine in ubuntu 18.04

**Comment by infograf768** [comment]
I also can't reproduce the issue. Scrolling works here OK.

**Comment by C-Lodder** [comment]
It's an issue in Firefox for me. There seems to be something wrgonw tih the frontend. Possible some JS script causing everything to run extremely slow and cause the browser to crash.

**Comment by ghost** [comment]
Closed as works now as expected: Test using Firefox 66.0.2 on MacOS 10.13.6 @C-Lodder please reopen if Issue isn't solved on your Side.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23812">issues.joomla.org/tracker/joomla-cms/23812</a>.</sub>
