### ISSUE TITLE
[4.0] [IE11] Misaligned Joomla logo in sidebar

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23813]
### Steps to reproduce the issue

1. Open the backend in IE11
2. Toggle the sidebar so it's collapsed

### Expected result

The Joomla logo is slightly reduced in size and is horizontally aligned to the middle

### Actual result

The logo stays the same size  and isn't correctly aligned

![screeny5](https://user-images.githubusercontent.com/2019801/52482008-ffa44800-2ba7-11e9-922e-be1554f5d674.png)

**Comment by ghost** [comment]
closed as having Pull Request #24385
