### ISSUE TITLE
[4.0] [Mobile] Label/Field should collapse to columns on smaller screens

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#23817]
### Steps to reproduce the issue
It's not really possible to maintain label / field in a single row on smaller screens. best they collapse to a single column.

### Expected result
![image](https://user-images.githubusercontent.com/2803503/52483494-fae19300-2bab-11e9-8647-9fa1cce68dec.png)

### Actual result
![image](https://user-images.githubusercontent.com/2803503/52483469-e9988680-2bab-11e9-91dd-76d35862277e.png)

**Comment by puneeth-chanda** [comment]
I could not reproduce the issue can you say me how?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23817">issues.joomla.org/tracker/joomla-cms/23817</a>.</sub>

**Comment by ciar4n** [comment]
Open publishing tab of an article. Reduce the viewport size.

**Comment by puneeth-chanda** [comment]
I reduced the viewport as much as possible but I am getting like this even then:
![screenshot from 2019-02-26 20-14-56](https://user-images.githubusercontent.com/43813460/53421303-72fce500-3a03-11e9-99b7-2084221e4c76.png)

**Comment by ciar4n** [comment]
Considering some mobiles are as low as 320px, you will need to reduce your viewport further.

**Comment by brianteeman** [comment]
### 320px
![image](https://user-images.githubusercontent.com/1296369/53423898-1f29d600-39da-11e9-9b1d-5be91cb97408.png)

### 360px
![image](https://user-images.githubusercontent.com/1296369/53423926-29e46b00-39da-11e9-81d9-5a4628dc02ce.png)

**Comment by ghost** [comment]
closed as having Pull Request #24386
