### ISSUE TITLE
[4.0] Horizontal scroll on screens

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#23814]
### Steps to reproduce the issue
View the backend template on any screen less than 600px. 

### Expected result
No horizontal scrollbar

### Actual result
Horizontal scrollbar

![image](https://user-images.githubusercontent.com/2803503/52482631-b1904400-2ba9-11e9-937c-2fe3d9633f1a.png)

**Comment by bahl24** [comment]
![screenshot from 2019-02-18 00-04-00](https://user-images.githubusercontent.com/36095178/52917378-b2934500-3310-11e9-8b9c-30646a180232.png)
@ciar4n I am getting the horz scroll bar, can you specify which browser you are using or pull recent updates and try again

**Comment by ciar4n** [comment]
That is the issue. There should not be a horizontal scrollbar.

**Comment by bahl24** [comment]
@ciar4n Then are you expecting all buttons on single page without scroll bar, so how to navigate?

**Comment by ciar4n** [comment]
> @ciar4n Then are you expecting all buttons on single page without scroll bar, so how to navigate?

Sorry but I do not understand what you are saying. Please note I am talking about the horizontal scroll, not the vertical scroll.

**Comment by bahl24** [comment]
> > @ciar4n Then are you expecting all buttons on single page without scroll bar, so how to navigate?
> 
> Sorry but I do not understand what you are saying. Please note I am talking about the horizontal scroll, not the vertical scroll.

I want to know that without scrollbar how can we navigate?
One solution can be to close the toggle menu <600px so that all content is on the screen eliminating need of horz scroll bar.

**Comment by bahl24** [comment]
> > > @ciar4n Then are you expecting all buttons on single page without scroll bar, so how to navigate?
> > 
> > 
> > Sorry but I do not understand what you are saying. Please note I am talking about the horizontal scroll, not the vertical scroll.
> 
> I want to know that without scrollbar how can we navigate?
> One solution can be to close the toggle menu <600px so that all content is on the screen eliminating need of horz scroll bar. @ciar4n

**Comment by ciar4n** [comment]
> One solution can be to close the toggle menu <600px so that all content is on the screen eliminating need of horz scroll bar.

That would certainly be a start. Moving the menu to an absolute position on smaller screens. Not floating the quickicons. Also need some consideration of what columns are expected on smaller screens within tables.

**Comment by bahl24** [comment]
But I still can't understand what is the problem in having the scroll bar,
as it makes navigation far easier.

**Comment by ciar4n** [comment]
A difference of opinion I guess. As a rule I believe horizontal scroll is to be avoided.

**Comment by alikon** [comment]
can we close this for reason 

> Closing as template team are working on backend template

**Comment by ciar4n** [comment]
The issue should be closed against a PR. When backend repo opens a PR to this repo to submit their code, then the issue can be closed (presuming it resolves the issue).

**Comment by alikon** [comment]
sorry for the unsafe close request ...
please @franz-wohlkoenig  reopen

**Comment by ciar4n** [comment]
Issue appears to be now resolved. Closing.
