### ISSUE TITLE
[4.0] [Mobile] Non CE tabs not responsive on mid size screens

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#23819]
### Steps to reproduce the issue
Non CE tab navigation is only partially responsive. On mid screen sizes items get compressed and push outside of their wrapper.

Possibly need a min-width and allowed to wrap on smaller screens.

### Expected result
![image](https://user-images.githubusercontent.com/2803503/52484776-0edac400-2baf-11e9-8575-b3836ceffa09.png)

### Actual result
![image](https://user-images.githubusercontent.com/2803503/52484697-e81c8d80-2bae-11e9-870d-d5bdd2784736.png)

**Comment by hardik-codes** [comment]
@ciar4n in which component should I fix this for testing purposes??

**Comment by hardik-codes** [comment]
![admin](https://user-images.githubusercontent.com/34353697/52522371-86d9e480-2caa-11e9-9ce2-b0001368b05e.png)
  
I was able to fix the min-width issue but I'm not able to wrap it, what should I do

**Comment by ciar4n** [comment]
This stops the tabs from wrapping... https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/scss/vendor/bootstrap/_nav.scss#L4

Set `flex-wrap: wrap;` on screens you wish the tabs to wrap.

**Comment by hardik-codes** [comment]
I already had  tried setting ```flex-wrap: wrap;``` but on doing that the screen looks like this
![screen1](https://user-images.githubusercontent.com/34353697/52522995-5ac26180-2cb2-11e9-8b57-40a7137b55ca.png)

**Comment by ciar4n** [comment]
Expected as the flex items are set to `width:100%` .. https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/scss/vendor/bootstrap/_nav.scss#L17

Remove/override the 100% width. Probably need to also unset the justify-content property of the flex container.

**Comment by ghost** [comment]
closed as having Pull Request #23843

**Comment by Quy** [comment]
Fixed #26890<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23819">issues.joomla.org/tracker/joomla-cms/23819</a>.</sub>
