### ISSUE TITLE
[4.0] [IE11] Template file editor throwing an JS error

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23821]
### Steps to reproduce the issue

1. In IE11, go to `/administrator/index.php?option=com_templates&view=templates`
2. Click on "Cassiopeia Details and Files"
3. On the left, click on any of the files to open it

### Expected result

Working editor

### Actual result

> 'regeneratorRuntime' is undefined .... joomla-editor-codemirror-es5.min.js (1,5776)

**Comment by alikon** [comment]
can we close this for reason 

> Closing as template team are working on backend template
