### ISSUE TITLE
[4.0] [Mobile] Choices dropdown not responsive

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#23820]
### Steps to reproduce the issue
Open 'choices' dropdown on smaller screens (<1200px) (Category edit -> Parent field).

Dropdown appears compressed on smaller screens.

### Expected result
![image](https://user-images.githubusercontent.com/2803503/52485386-a856a580-2bb0-11e9-83b8-05d6380e01c3.png)

### Actual result
![image](https://user-images.githubusercontent.com/2803503/52485320-80674200-2bb0-11e9-97da-d992337991fc.png)

**Comment by hardik-codes** [comment]
I have already worked on an issue of such a kind 
See #23451 
I think it is quite similar to that and I'll be working on it

**Comment by ciar4n** [comment]
I'll close this as it is the same issue as #23451
