### ISSUE TITLE
[4.0] Sub-form fields not working in IE11

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23822]
### Steps to reproduce the issue

1. In IE11, go to `/administrator/index.php?option=com_plugins&view=plugin`
2. Search for and open the "Redirect" plugin
3. Click the "+" (plus) icon next to "Exclude URLs"

### Expected result

The subform fields start to populate the area

### Actual result

Nothing happens and a JS error is thrown:

> Invalid calling object  .....  webcomponents-sd-ce-pf.min.js (1,56047)

**Comment by brianteeman** [comment]
This issue can be closed as the production department have decided to adopt a browser support policy of PROD2019/005 - Change minimum version requirements for all browsers to n-2 and drop support for Internet Explorer. https://volunteers.joomla.org/departments/production/reports/1031-production-dept-meeting-may-28-2019
