### ISSUE TITLE
[4.0] [IE11] Language Override - JS error

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23823]
### Steps to reproduce the issue

1. In IE11, go to `/administrator/index.php?option=com_languages&view=override&layout=edit`
2. Click inside the Search input directly below the blue alert

### Actual result

Javascript error:

> Unable to get property 'remove' of undefined or null reference   ....  admin-override-edit-refresh-searchstring.min.js (1,347)

**Comment by ghost** [comment]
closed as having Pull Request #24508
