### ISSUE TITLE
[4.0] Menu Module Assignment not working

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23826]
### Steps to reproduce the issue

1. Go to `/administrator/index.php?option=com_menus&view=items&menutype=mainmenu`
2. Go to edit menu
3. Click the "Module Assignment" tab
4. Click any of the module links

### Expected result

Open a modal with the module settings

### Actual result

Nothing happens

![screenshot_2019-02-08 menus edit item - joomla 4 - administration](https://user-images.githubusercontent.com/2019801/52488532-f327eb80-2bb7-11e9-8cbb-8cd51c7e2937.png)

**Comment by amitranjan2** [comment]
@C-Lodder  see this PR #23609  for your issue
After merge it will work


Issue duplicate #23540

**Comment by C-Lodder** [comment]
@amitranjan2 thanks
