### ISSUE TITLE
[4.0] Media Manager not working

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#23825]
### Steps to reproduce the issue

Visit the Media Manager in IE11

### Expected result

A working page

### Actual result

Nothing is working and JS errors are being thrown:

![screeny6](https://user-images.githubusercontent.com/2019801/52488160-24ec8280-2bb7-11e9-863f-b42316f77010.png)

**Comment by ghost** [comment]
@laoneo can you please comment?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23825">issues.joomla.org/tracker/joomla-cms/23825</a>.</sub>

**Comment by C-Lodder** [comment]
Haven't tested, but  perhaps https://github.com/joomla/joomla-cms/pull/24288 solves this

**Comment by ghost** [comment]
Thanks @C-Lodder, Issue stay open till #24288 is tested.

**Comment by brianteeman** [comment]
Confirming that this error is still present

**Comment by brianteeman** [comment]
This issue can be closed as the production department have decided to adopt a browser support policy of PROD2019/005 - Change minimum version requirements for all browsers to n-2 and drop support for Internet Explorer. https://volunteers.joomla.org/departments/production/reports/1031-production-dept-meeting-may-28-2019
