### ISSUE TITLE
[4.0] [Mobile] Header icon dropdowns not visible on smaller screeens

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#23827]
### Steps to reproduce the issue
On smaller screens the header icon dropdowns are not displayed.

Z-index issue with dropdown displaying behind following elements.

### Expected result
![image](https://user-images.githubusercontent.com/2803503/52488562-02a73480-2bb8-11e9-961c-3d6e7c1a10b4.png)

### Actual result
![image](https://user-images.githubusercontent.com/2803503/52488521-ec997400-2bb7-11e9-8064-8c63d4639be3.png)

**Comment by C-Lodder** [comment]
Already an issue for it (https://github.com/joomla/joomla-cms/issues/23818) but will close mine

**Comment by hardik-codes** [comment]
@ciar4n I tried solving it by adding a media query followed by a high z-index. But this does not work out for me any suggestions?

**Comment by ciar4n** [comment]
Where are you setting the z-index?

**Comment by hardik-codes** [comment]
In the ```.dropdown-menu``` selector in ```administrator/templates/atum/scss/blocks/_header.scss``` inside the ```@include media-breakpoint-down(sm) { ```  media query.

**Comment by ciar4n** [comment]
You will need to apply it to the outer container... https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/index.php#L66

**Comment by puneeth-chanda** [comment]
can I work on it??
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23827">issues.joomla.org/tracker/joomla-cms/23827</a>.</sub>

**Comment by hardik-codes** [comment]
@puneeth2001 there is already a PR for this issue and this issue might be closed once the PR is reviewed

**Comment by ghost** [comment]
closing this issue as having Pull Request #23865
