### ISSUE TITLE
[4.0] Debug plugin uses method `getClientId` which is not part of the application interface

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#23845]
### Steps to reproduce the issue

At [this line](https://github.com/joomla/joomla-cms/blob/ad2c673ac27c2fd19bbdf6003aee0451d068de16/plugins/system/debug/debug.php#L177) is a call to `Joomla\CMS\Application\CMSApplication::getClientId()`.  This method is not part of `Joomla\CMS\Application\CMSApplicationInterface` and inherently not defined in `Joomla\CMS\Application\ConsoleApplication`, therefore the console application will not run when the debug plugin is active.

### Expected result

The console application should run without error.

### Actual result

The console application fails with the debug plugin active due to use of a method not declared as part of the application interface.

**Comment by Fedik** [comment]
~that can be changed to just:~
~`$storagePath = JPATH_CACHE . '/plg_system_debug';`~
~I try to make PR tomorrow~

ah no, it cannot,
then debug history will show mixed debug log, hm

Need to get the name of active App somehow, or something that can separate the log per App

**Comment by Fedik** [comment]
please check #23859

**Comment by infograf768** [comment]
Closing as we have a PR #23859
