### ISSUE TITLE
Action Log module links

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#23841]
### Steps to reproduce the issue
Unpublish/publish a plugin
Return to control panel and see the message in the Action Log module
Follow the link

### Expected result
com_plugins opens with the specified plugin open for editing

### Actual result
com_plugin opens at the list

### Additional comments
This is because the links are all &id=xx
But for plugins they need to be &extension_id=xx

/cc @alikon

**Comment by alikon** [comment]
see #23853
