### ISSUE TITLE
[4.0] Debug bar - Information missing

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#23849]
### Steps to reproduce the issue
Activate debug and the debug plugin

### Expected result
The debug bar displays at least the same information as in Joomla! 3 or an improvement.

### Actual result
A selection of missing information:
- call stack (most time the correct line where the query is executed is shown, but that information is useless when the query is build somewhere else (e.g. `\libraries\src\Table\Table.php`)
- Explain information (One could copy&paste the query to phpmyadmin etc. but that slows down working with the debug)
- Profiling of the execution (still could be copy&pasted to phpmyadmin, but there are probably the information different)

### Additional comments
I also think, the debug bar could be improved with some colors, to identify slow queries, or sum ups faster.

**Comment by Quy** [comment]
@elkuku

**Comment by bembelimen** [comment]
Nevermind, the debug bar overlapped the options
