### ISSUE TITLE
class="red" ignored in alerts

### ISSUE THREAD

**Issue by kofaysi** [joomla/joomla-cms#23850]
### Steps to reproduce the issue

Make actions to display any message containing `"_QQ_"red"_QQ_"`, e.g., change site language.
https://github.com/joomla/joomla-cms/blob/6f4ccc25f9a03988fd3631bfdb410c71a608723f/administrator/language/en-GB/en-GB.com_languages.ini#L88

### Expected result

The "Warning!" word is displayed in red color as stated in the source code using class="red".

### Actual result

The "Warning!" word is displayed in green color (no color contrast to the text around).
![image](https://user-images.githubusercontent.com/17022173/52527407-691b7800-2cc8-11e9-82b9-ec170728f997.png)

### System information (as much as possible)

Joomla 3.9.2

### Additional comments

I think no class `red` is defined in template.css.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/23851#issuecomment-462146893

**Comment by kofaysi** [comment]
obsolete
