### ISSUE TITLE
[4.0] Export button on Tracks not working

### ISSUE THREAD

**Issue by amitranjan2** [joomla/joomla-cms#23856]
### Steps to reproduce the issue

1. Go to `administrator/index.php?option=com_banners&view=tracks`
    Click on Export

### Expected result

Should be  able to Export 

### Actual result
Backdrop

Not able to Export
![image](https://user-images.githubusercontent.com/41797766/52532879-8c3e3a00-2d51-11e9-9de0-a7e42fea8c5b.png)

**Comment by puneeth-chanda** [comment]
#23636 
similar problem is here.

**Comment by ghost** [comment]
closed as duplicate Report #23636<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23856">issues.joomla.org/tracker/joomla-cms/23856</a>.</sub>
