### ISSUE TITLE
[4.0][a11y]Password field in Login form module has no label

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/joomla-cms#23860]
### Steps to reproduce the issue
1. Set the Display icons option to Icons
2. Check the source code

### Expected result
It should be the label element "Password" for `modlgn-passwd`. Just as there is a label for `modlgn-username`.

### Actual result
Currently, the label does not exist.  Of course, when the Display icons option is set to Text, the label exist.
Chrome and Firefox browsers show in the Accessibility tree that the item has an accessible name, NVDA screen reader announces this name, but testing tools (Audits in Chrome, tota11y, ANDI) report no label.

**Comment by infograf768** [comment]
On it.

**Comment by zwiastunsw** [comment]
@infograf768 : Placeholder is not label :)

**Comment by infograf768** [comment]
Yes, I am making the patch. This is what I meant with "On it"

**Comment by infograf768** [comment]
Closing as we have a patch
https://github.com/joomla/joomla-cms/pull/23862
