### ISSUE TITLE
GPL Violation's in FOF Changes.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#23867]
It has[ come to light](https://github.com/joomla/joomla-cms/pull/23858#issuecomment-462139164) that the following code changes were not made correctly honouring the GPL Licence Section 2(a) and @nikosdion has requested that the project abide by the licence granted to the Joomla project. 

The following PRs have changed /libraries/fof files without abiding by Section 2(a) of the GPL. Namely the requirement to 

>   2. You may modify your copy or copies of the Program or any portion
of it, thus forming a work based on the Program, and copy and
distribute such modifications or work under the terms of Section 1
above, provided that you also meet all of these conditions:

Specifically:

>    a) You must cause the modified files to carry prominent notices
    stating that you changed the files and the date of any change.

All of the following PRs make changes the source code and do not `carry prominent notices` 

 - @Spudley https://github.com/joomla/joomla-cms/pull/14269
 - @julienV https://github.com/joomla/joomla-cms/pull/15007
 - @okonomiyaki3000 https://github.com/joomla/joomla-cms/pull/12546
 - @izharaazmi https://github.com/joomla/joomla-cms/pull/13857
 - @laoneo https://github.com/joomla/joomla-cms/pull/13319
 - @laoneo https://github.com/joomla/joomla-cms/pull/11833
 - @rdeutz https://github.com/joomla/joomla-cms/pull/12497
 - @piotrmocko https://github.com/joomla/joomla-cms/pull/10742
 - @amouhzi https://github.com/anezi/joomla-cms/pull/61
 - @mbabker https://github.com/joomla/joomla-cms/pull/3436
- @wilsonge https://github.com/joomla/joomla-cms/pull/3730

Some of these changes are very old, and might have then further been changed by upgrades of fof. Individual applicability has not been tested. 

If you consider that comments are also changes to the source code that need to be GPL Compliantly changed too then these commits also need addressing:

 @zero-24  - https://github.com/joomla/joomla-cms/pull/15302 
 @brianteeman  - https://github.com/joomla/joomla-cms/pull/15565
 @brianteeman - https://github.com/joomla/joomla-cms/pull/10378

Also, these were mainly merged by @rdeutz @wilsonge @Kubik-Rubik, so maybe some licensing checks could be made in future? maybe an improvement to the PR Github Template to include a section on licensing to focus the mind of the submitter? 

Also note that I have only checked joomla-cms/staging, however its clear that this violating action of the GPL licence continues into the Joomla 4 branch https://github.com/joomla/joomla-cms/commit/4c0da178dcde554ceeb14478431010e9427f9d01

So what needs to be done to resolve this?

The [requested action](https://github.com/joomla/joomla-cms/pull/23858#issuecomment-462139164) of the copyright holder is:

> If the Joomla! project has made changes without putting prominent notices it is in violation of the License of the Software. Please add the notices as stipulated by the License to restore compliance with the License.

Good luck.

**Comment by Bakual** [comment]
> Also note that I have only checked joomla-cms/staging, however its clear that this violating action of the GPL licence continues into the Joomla 4 branch

Since to my knowledge FOF will be removed in 4.0, we can focus solely on `staging`. There can't be any violation anymore in 4.0 when the code got removed.

**Comment by PhilETaylor** [comment]
From @mbabker buried [elsewhere](https://github.com/joomla/joomla-cms/pull/23869#discussion_r255355361)

> Personally, I take offense to the fact that you are trying to assign blame to specific individuals in #23867 as though every action by one of those individuals is one of willful malintent. You are trying to spin things around in a way that suggests every one of those individuals should have had their pull requests closed and banned from contributing until they can pass your expectations on familiarity with the GPL license. I don't know the license that in depth, I rely on others to help cover down on places where I don't know things. In the time it has taken this conversation to unfold, someone could have addressed your finger pointing by adding the requisite annotations to each file and been done with things, instead you aim to change the contribution workflow to one that says "I have passed an exam that certifies I understand the GNU General Public License, version 2, and that my contributions are of legal compliance with the text of the license".

I'm not blaming anyone for anything.

I'm simply aggregating the changes that were made in a non GPL compliant way.

I'm not spinning anything at all. Nothing I have said it spin. 

I am not the copyright holder, @nikosdion is, and he has expressed his [own thoughts](https://github.com/joomla/joomla-cms/pull/23858#issuecomment-462139164) on it 

Im sorry for wanting the project to resolve this issue and to look for ways to improve the process in the future.

Once again it comes back to personal attacks. 

Its clear I'm not welcome to contribute to this project. So I will refrain from doing so in the future.

**Comment by mbabker** [comment]
> I'm simply aggregating the changes that were made in a non GPL compliant way.

Which you could have done without the name and shame, especially the bit about "merged by X".  That is the part that I felt crossed the line between reporting potential licensing issues and blaming people for screwing up.

**Comment by PhilETaylor** [comment]
If the shoe fits. Wear it. Call yourself a maintainer, then maintain - higher standards are expected of those who should know better.

**Comment by mbabker** [comment]
Unlike some others listed in this issue, I've actually put my money where my mouth is for the better part of the last decade.  And if I've screwed up once or twice along the way, that means I'm human.  So sorry for not being a damn robot and not being able to live up to your FUBAR expectations, and actually giving a damn about my time and the work I've put in to make other people's lives better without shitting on their efforts every chance I get.

**Comment by PhilETaylor** [comment]
Once again with the personal attacks. Amazing but come to expect nothing less from those involved in Joomla.

#blocked

**Comment by brianteeman** [comment]
These comments are nothing but trying to assign blame

**Comment by PhilETaylor** [comment]
Well teeman you got what you wanted... time to publish the truth about your abuse too...

> Its clear I'm not welcome to contribute to this project. So I will refrain from doing so in the future.

**Comment by PhilETaylor** [comment]
> Its clear I'm not welcome to contribute to this project.
![screenshot 2019-02-10 at 21 51 49](https://user-images.githubusercontent.com/400092/52540141-24eaaf00-2d7e-11e9-8564-6aa7407a3b65.png)

**Comment by amouhzi** [comment]
Hello,

I removed my very old fork.

Best regards.

**Comment by nikosdion** [comment]
Guys. Copyright law requires the copyright holder to assert his rights. Otherwise the copyright won't hold in court. That's the only reason I asked for the addition of **a single comment line** on the offending files. I hereby grant permissions to OSM to publish my contact form email verbatim to demonstrate that this is exactly what I said to them, as the legal custodians of the project.

Also, I don't understand grown ups throwing tantrums in public. You're not toddlers. When I ask, politely, that a comment line be added because that's what the legal license of the code says you can do something simple. Read the license. Understand I'm right. Add the comment line. Start to finish: 3'. Throwing a tantrum has only wasted hours for dozens of people FOR NO GOOD REASON. This is a stupidly easy thing to fix. It's not like we're discussing the refactoring of the entire backend template with repercussions on all extensions for years to come. We're discussing adding something like 6 comment lines. They could even be identical, to the tune of "This file has been modified by the Joomla! project / OpenSourceMatters Inc. in accordance with the GPLv2 license. This is not the author's original work and should not be confused with it". Bam! That's it! **GROW THE HELL UP**.

**Comment by Spudley** [comment]
I'm a little confused here; I've been mentioned in this thread... so is there actually anything that I need to do, or can I ignore all of this? It looks like the required changes have been made, right?

**Comment by okonomiyaki3000** [comment]
@Spudley I'm mentioned here too but I have no intention of taking any action whatsoever.

**Comment by HLeithner** [comment]
The violation has already been fixed by Luca, so you don't have to do anything.
