### ISSUE TITLE
Rotating an image in Joomla

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#23875]
### Is your feature request related to a problem? Please describe.

Imposible to rotate an image in Joomla core

### Describe the solution you'd like

Rotating an image in Joomla

**Comment by algomaster99** [comment]
Can you help me setup the project? It failed at `npm ci`.

**Comment by C-Lodder** [comment]
No, it's not impossible to rotate an image in Joomla.

Please do some CSS research: https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate

Unless your template has something like this, which is highly unlikely:
```
* {
  transform: rotate(0) !important;
}
```

**Comment by mbabker** [comment]
And if you're looking for a PHP API see https://api.joomla.org/cms-3/classes/Joomla.CMS.Image.Image.html (don't mind the deprecation notices, those actually need to go away and some refactoring needs to happen, I have another issue on the topic somewhere).

If you're looking for a UI integration for this, the media manager in 4.0 supports it.

Is there anything you missing after this knowledge?

**Comment by ghost** [comment]
Yes thank you for trying to help, maybe its very simple and obviuos but I cant find there I need to insert this code to make it work in Joomla 3.9?

For example If I need to Watermark all the images in articles?

watermark(\Joomla\Image\Image $watermark, integer $transparency = 50, integer $bottomMargin, integer $rightMargin) : \Joomla\Image\Image

Do I need to insert this code in protostar template, in what file of this template or somethere else?

**Comment by dgrammatiko** [comment]
@Milglius get this https://github.com/dgrammatiko/imageUploaderHelper

Make all the alterations you need and then all your files will be watermarked or whatever you choose to do there after the upload process.

**Comment by tapiochre101** [comment]
@Milglius try the JCE Editor Component. It comes with a very handy image editor that allows you to rotate, resize and crop your images. 

Hope this helps.
C<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23875">issues.joomla.org/tracker/joomla-cms/23875</a>.</sub>

**Comment by ghost** [comment]
@mbabker mentioned that one just can use api , but the problem no one knows where to insert this api in joomla

**Comment by mbabker** [comment]
The plugin @dgrammatiko linked to demonstrates use of the Image API.

**Comment by ghost** [comment]
so api works only in plugin you cant just paste `watermark(\Joomla\Image\Image $watermark, integer $transparency = 50, integer $bottomMargin, integer $rightMargin) : \Joomla\Image\Image` in the template ?

**Comment by mbabker** [comment]
You can't paste that line as is anywhere, the API documentation doesn't give code examples but some basic documentation of what the method does and its signature which contains what the method expects to receive and what will be returned at the end of it.  If you need a practical example, this is one:

```php
use Joomla\CMS\Image\Image;

$imagePath = '/path/to/image.jpg';
$watermarkedImagePath = '/path/to/image-watermark.jpg';

// Get the image type from file properties so we save things correctly
$imageType = Image::getImageFileProperties($imagePath)->type;

// Load image to be watermarked
$image = new Image;
$image->loadFile($imagePath);

// Load image to use as watermark
$watermarkImage = new Image;
$watermarkImage->loadFile('/path/to/watermark.jpg');

// Customize to suit your needs
$transparency = 50;
$bottomMargin = 10;
$rightMargin = 10;

// Apply watermark to image
$image->watermark($watermarkImage, $transparency, $bottomMargin, $rightMargin);

// Save to filesystem
$image->toFile($watermarkedImagePath, $imageType);
```

This should be done in a plugin listening to a save event, not in your template.  The Image API is meant to edit images then save them back into the filesystem, it will be painfully inefficient if you try to watermark an image in your template each time the page is displayed.

**Comment by mbabker** [comment]
At this point this issue is turning into a user support request, which isn't what this platform is used for.  If you need further assistance, please use the forums at https://forum.joomla.org.

Given there is an API in Joomla for plugins to process images, the media manager in 4.0 will have more image editing capabilities, and there are extensions for 3.x to do this type of thing, there isn't any feature request here that isn't already fulfilled either.

**Comment by ghost** [comment]
Thank you for information
