### ISSUE TITLE
Lot of space is given sideways description.

### ISSUE THREAD

**Issue by puneeth-chanda** [joomla/joomla-cms#23874]
### Decrease the white space in the 
![screenshot from 2019-02-11 17-58-25](https://user-images.githubusercontent.com/43813460/52563291-f70d7500-2e26-11e9-950d-9da73d528104.png)
new tags component

**Comment by C-Lodder** [comment]
This is due to the form field labels being wrapped in a container with a width of 200px (or something similar). This is a generic thing across all labels in Joomla.

**Comment by vijay9908** [comment]
Things like these don't create any problem and moreover such generic things can be avoided.

**Comment by Quy** [comment]
Please test PR #23946<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23874">issues.joomla.org/tracker/joomla-cms/23874</a>.</sub>
