### ISSUE TITLE
Allow displaying access level in the info_block (Details)

### ISSUE THREAD

**Issue by kofaysi** [joomla/joomla-cms#23871]
### Is your feature request related to a problem? Please describe.

I wish to display the "Access Level" information next to the articles' header/footer. Currently, it is possible to display data such as Created date, Modified date, Author, Voting and similar.

In the default installation of the Joomla the aim would be the following: Indicate to a certain user group (let's say Editors) that the article they are viewing has some restricted view and it is not yet visible let's say to the Public group.

### Describe the solution you'd like

A possibility to display the Access Level in the info_block, a.k.a. Details, to the Articles in the similar manner a it is possible with publish_date, created_date, voting, views, ... in Global configuration > Articles > Articles

### Additional context

Original at https://forum.joomla.org/viewtopic.php?f=708&t=935519

**Comment by ghost** [comment]
@HLeithner can you please comment?

**Comment by HLeithner** [comment]
You have the access level of the article in $item in the template but not the access level title, so this could be get by a query or have to be joined in article query. But this query is already really big and till now nobody needs it... If you find someone that write the PR we will consider to include it.

**Comment by ghost** [comment]
> If you find someone that write the PR we will consider to include it.

@kofaysi have you found?

**Comment by alikon** [comment]
lack of interest and not a bug<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23871">issues.joomla.org/tracker/joomla-cms/23871</a>.</sub>
