### ISSUE TITLE
[4.0][a11y] Labels Module Assignment are not associated with forms

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/joomla-cms#23889]
### Steps to reproduce the issue
1. Go to Modules new/edit
2. Use screen reader (I use NVDA),  move focus to Module Assignment field
or 
3. Click on the Module Assignment label
or
4. Check Accessibility tree (in Chrome) 

### Expected result
* The screen reader should announce the role combobox and the label Module Assignment
* When you click on a label, the field should receive a focus
* The field should have an accessible name in the Accessibility tree 

### Actual result
1. Screen reader (NVDA) announces only a role, does not announce a label
2. When you click on a label, the field does not receive a focus
3. The field does not have an accessible name in the Accessibility tree

### System information (as much as possible)
* Windows 10,
* Chrome 72.0.3626.81, Firefox/65.0
* Apache 2.0 server (online)
### Additional comments
The label should probably be assigned to the 'select' field. 
![image](https://user-images.githubusercontent.com/29527200/52678288-640d3180-2f31-11e9-8e78-a13b2727fd5f.png)

**Comment by brianteeman** [comment]
Please test #23922
