### ISSUE TITLE
[4.0] Incorrect scope in elements with ARIA role

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/joomla-cms#23887]
### Steps to reproduce the issue
1. Go to Modules Article Category Edit page
2. Run ChromeLens Accessibility test 
### Actual result
You will receive more than 20 messages: **Elements with ARIA roles must be in the correct scope**

All tree nodes should be contained in or owned by an element with role `tree`. Currently tree nodes with the role of `treeitem` are not correct in element with role `group`. 

![tree_treeitem](https://user-images.githubusercontent.com/29527200/52650208-14efde00-2eea-11e9-9b97-b73123c5768a.png)

See: [WAI-ARIA Authoring Practices 1.1 TreeView](https://www.w3.org/TR/wai-aria-practices-1.1/#TreeView)
**Note**: This is webcomponent: joomla-field-fancy-select   
@dgrammatiko

**Comment by dgrammatiko** [comment]
@zwiastunsw you need to open an issue to choices, unfortunately, people thought that this script was a good fit for Joomla, welcome to chosen no2...

**Comment by zwiastunsw** [comment]
@dgrammatiko : I'm sory. I don't understand your comment

**Comment by dgrammatiko** [comment]
@zwiastunsw we **don't** have control over that code!!!
It means you need to open an issue to their repo: https://github.com/jshjohnson/Choices

And if you're lucky it may get resolved

**Comment by zwiastunsw** [comment]
Hmmm. It's too difficult for me.

**Comment by brianteeman** [comment]
not sure why you have highlited the div with the role=group as that is not a containing div for the items with a role=treeitem

**Comment by brianteeman** [comment]
@zwiastunsw you are correct however that the role attribute is not being used correctly pretty much everywhere

**Comment by brianteeman** [comment]
I have reported this upstream

**Comment by jwaisner** [comment]
Closing as this has been confirmed as reported upstream to Choices.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23887">issues.joomla.org/tracker/joomla-cms/23887</a>.</sub>
