### ISSUE TITLE
Captcha is not shown on Internet Explorer

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#23883]
### Steps to reproduce the issue
Captcha does not work with Internet Explorer

### Expected result
Invisible (core) captcha should be shown

### Actual result
Invisible (core) captcha is not available in IE
Error Message when trying to register "Captcha cannot be empty"

### System information (as much as possible)
Joomla 3.9.2.

**Comment by brianteeman** [comment]
Is internet explorer in compatibility mode? If so then that is a known issue from google

https://support.google.com/recaptcha/answer/6223838?hl=en

**Comment by B3nito** [comment]
It is not added to the compatibility view settings, and it is the Internet Explorer 11. When I view website in Internet Explorer Captcha is not loading and not visible but still required field. It gives an error when trying to register.

**Comment by B3nito** [comment]
I have errors on the page like squeezebox not defined and hash not defined modal.js and the ToS is not working. It seems it requires mootools but I cannot use mootools on the page. Is it not show on IE because off mootools?

**Comment by brianteeman** [comment]
OK so this sounds much more like an issue with your site template as you have multiple things not working.

**Comment by B3nito** [comment]
I tested. When I enable Mootools it works in IE. But Mootools should not be mandatory.

**Comment by jeckodevelopment** [comment]
which template are you using?

**Comment by B3nito** [comment]
I am using a Bootstrap 4 Template. I made unset mootools because I don't need it. But it breaks captcha on Internet Explorer. When I enable Mootools it works.

**Comment by ghost** [comment]
@B3nito Isn't Bootstrap2 supported by J3 and not BS4 as your Template use?

**Comment by Quy** [comment]
Unable to reproduce error.
