### ISSUE TITLE
Feature request for privacy - User Registration without consent

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#23898]
### Is your feature request related to a problem? Please describe.
I want to give the User the possibility to say NO and still use website.
Currently User is forced to give consent.

### Describe the solution you'd like
Possibility for user to say "NO" and his activities are not tracked.

**Comment by jeckodevelopment** [comment]
Technically, you shouldn't handle personal data without consent.
If a user is registered, means that you are handling/processing personal data.
It's not only about tracking activities, data processing includes also the fact that you might have access to personal data, and user registration gives you the opportunity to view (then process) users data.

**Comment by brianteeman** [comment]
This should not be in the core

**Comment by ghost** [comment]
close as comment above. Please reopen if needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23898">issues.joomla.org/tracker/joomla-cms/23898</a>.</sub>
