### ISSUE TITLE
[3.9] review time of user notes is saved wrong

### ISSUE THREAD

**Issue by mojoooo** [joomla/joomla-cms#23890]
### Steps to reproduce the issue
Login as administrator and go to user -> notes. Try to change the review time of a user note.

### Expected result
The entered date will be saved and shown as the new review date.

### Actual result
After entering and saving the new date, it gets converted like:

The day will ever be converted to the 20th.

The month stays the same as entered.

The year changes irregularly depending on the entry. (e.g. 2013, 2020,...)

Example: I enter 13.02.2019 and get the result 20.02.2013.

### System information (as much as possible)

Joomla 3.9.2

Mysql 5.7.24

PHP 7.2.15

Apache localhost

### Additional comments

In administrator/components/com_users/tables/note.php

before storing to database "return parent::store($updateNulls);"

The value of $this->review_time has the proper value.

In database the review time in table _user_notes has the inproper value. 

Changing it manually changes the displayed review time in user notes.

**Comment by ghost** [comment]
@HLeithner can you please comment?

**Comment by infograf768** [comment]
The date format entered should be correctly entered if done manually. It depends on the format used by the language.
The first time it is saved as it has no date yet, it will pick the language defined format.
When editing thereafter and whatever the language, the format should be similar to the one displayed in the field.
In French, it would be 03-03-2011 while in en-GB it will be 2011-03-03

Not a bug.

**Comment by ghost** [comment]
thanks @infograf768

**Comment by mojoooo** [comment]
Hello,

firstly i want to thank you for answering. But the problem still exists.

I have tried to enter it manually but still the same happens. 
Even in a fresh Joomla installation without custom code there is the same behaviour.
I've also tried different formats, but every time i get the same result like described above.

Do you have any ideas?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23890">issues.joomla.org/tracker/joomla-cms/23890</a>.</sub>
