### ISSUE TITLE
[4.0] Language change for toggle editor button

### ISSUE THREAD

**Issue by hardik-codes** [joomla/joomla-cms#23891]
### Steps to reproduce the issue
Open any article from the article list view. 
If there are no articles create one 

### Expected result
In my humble opinion, the toggle editor button should be like this 
![toggle3](https://user-images.githubusercontent.com/34353697/52712745-821f7400-2fbb-11e9-9117-d1a7355df7cc.png)

 

### Actual result
![toggle 2](https://user-images.githubusercontent.com/34353697/52712545-ee4da800-2fba-11e9-902e-8223d56f4067.png)

### Additional comments
Other tabs such as Configure Edit Screen, which comprises of more than one word has its first letter of each word capital, by the same logic the above change goes.

**Comment by hardik-codes** [comment]
@brianteeman please comment on the validity of the issue

**Comment by brianteeman** [comment]
If you are creating a pull request there is no need to create an issue as well.

This can be closed
