### ISSUE TITLE
Weblinks not inheriting Global Settings for Target

### ISSUE THREAD

**Issue by tapiochre101** [joomla/joomla-cms#23894]
Unsure if this gets pulled over from githib or not. Sorry if I mess up!

### Steps to reproduce the issue

    1. In Components >> Web Links Manager >> Options, set Target to "Open in New Window"

    2. Create a new Weblink Category (or use an existing category)

    3. Create a new Weblink, assign to the category

    4. Set the Weblink's target is to "Use Global"

    5. Create a Weblink Module and assign the above category to the module. Assign module to a suitable menu and position.

    6. Visit front end and test the weblink.

### Expected result

Weblink should open in a new tab or window.
### Actual result

Weblink opens in Parent window
### System information (as much as possible)

PHP Version | 7.2.14
Joomla! 3.9.3 Stable [ Amani ] 12-February-2019 15:00 GMT
Web Links Extension Package version 3.6.0 (from **Install from Web** option of Installer)
### Additional comments

    1. Setting weblink to use "Use Global" and inspecting the source of the link, there is no target="_blank" seen. In fact there is no 'target="....." at all.

    2. This missing 'target="..." us true no matter how the Global Setting for target us set.

    3. Setting the weblink's target to 'Open in new window' works.

Semi conclusion, is that the module is disregarding how the Global Target setting is set for weblinks.

Problem also seen in previous releases of J! 3.X

**Comment by Quy** [comment]
Please post to the Weblinks repo: https://github.com/joomla-extensions/weblinks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23894">issues.joomla.org/tracker/joomla-cms/23894</a>.</sub>

**Comment by tapiochre101** [comment]
Thanks

 

https://github.com/joomla-extensions/weblinks/issues/397

 

Regards

Chris Elliott
Tapiochre Ltd 

M: 07958 726700 

Follow me on Twitter: @tapiochre 

2017 – Tapiochre’s 15th Year in Business

**Comment by skuzmina** [comment]
Hi, 

Can you tell when it will get fixed in Joomla?

Thanks, 
Sandra

**Comment by ghost** [comment]
@skuzmina Please post to the Weblinks repo: https://github.com/joomla-extensions/weblinks/issues/397
