### ISSUE TITLE
[4.0] Text Not Found in Finder > Filters

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#23899]
### Steps to reproduce the issue
Under the _com_finder_ click _filters_
Url: administrator/index.php?option=com_finder&view=filters

### Expected result
Show the list of the filters

### Actual result
_Fatal error: Text Not Found_

### System information (as much as possible)
Joomla 4.0 alpha6

### Additional comments
Add the Text class in the file:
administrator/components/com_finder/tmpl/filters/default.php

`use Joomla\CMS\Language\Text;`

**Comment by amitranjan2** [comment]
For your concern Duplicate #23677

**Comment by sakiss** [comment]
Ok I am closing as duplicate
