### ISSUE TITLE
Blank summary window after upload media image

### ISSUE THREAD

**Issue by danjde** [joomla/joomla-cms#23895]
### Steps to reproduce the issue
Uploading any media into contents

### Expected result
shows the upload confirmation window with all relevant information

### Actual result
only an empty page shown 

### System information (as much as possible)
Debian 8
Apache2 2.4.10
php 5.6.38
mysql 5.5.59
Joomla 3.9.2
verified file permission, all ok

### Additional comments
I've try with others Joomla sites hosted by the same (identical environment) server and all is working fine. Only for this one web site Joomla 3.9.2 appear the blank page (picture 1 below)

Uploading for the second time the same image, obtain the error (duplicate) media window, as expected (picture 2 below)

![1](https://user-images.githubusercontent.com/4129294/52732789-530c0100-2fc1-11e9-875d-5958700ad1c7.png)
![2](https://user-images.githubusercontent.com/4129294/52732790-530c0100-2fc1-11e9-98ea-0b58a3d3f73b.png)

**Comment by HLeithner** [comment]
Could you please check the php and apache  error log.

**Comment by danjde** [comment]
Hi @HLeithner,
I've try to look into php and Apache log but I can not find any useful information.
I've enabled for php (/etc/php5/apache2/php.ini):
 
`error_reporting = E_ALL`

Then I've verified if it is hooked log path by executing www.mysite.com/phpinfo.php:

> Directive-----------------Local Value-----------------------------------------Master Value
> 
> error_log----------------/var/log/apache2/php_errors.log----------------/var/log/apache2/php_errors.log

but uselessly.
I don't know how give you more informations, if you can give me some useful suggestions, I will apply them :-)

**Comment by zero-24** [comment]
Can you show us the content of the file /var/log/apache2/php_errors.log for that given time period that could help analyse the problem.

**Comment by danjde** [comment]
..I', sorry but /var/log/apache2/php_errors.log stay empty as empty stay /var/log/apache2/error.log

**Comment by danjde** [comment]
I've set to Joomla log to "developer" and now I can see:

> Fatal error: Class 'imagerecycleComponentHelper' not found in /var/www/mysite.it/public_html/administrator/components/com_imagerecycle/helpers/imagerecycle.php on line 254

**Comment by danjde** [comment]
Disabling all imagerecycle components solve this issue.
Removing imagerecycle does it better!

Many thanks!
