### ISSUE TITLE
Customization of the contact limit displayed in the category menu

### ISSUE THREAD

**Issue by lisandroTSilva** [joomla/joomla-cms#23904]
### Steps to reproduce the issue

- Create some contacts (10 for example) in a specific category.
- Create a type menu "Contacts » List Contacts in a Category"
- System > Global Configuration > tab _Site_ > option:  _Default List Limit_, This setting that determines the Contact Limit displayed.

### Expected result
This item sets the number of rows in the administrative area and in the site, I would like to be able to set the maximum number, or unlimited, a presentation of an item to contact list.

My expectation is that this value would be customized to the contact submission feature, just as are the article categories.

### System information (as much as possible)

Setting | Value
-- | --
PHP Version | 7.2.6
Web Server | Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 3.9.2 Stable [ Amani ] 15-January-2019 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by ghost** [comment]
@infograf768 can you please comment?

**Comment by lisandroTSilva** [comment]
**Note:** There is no code to attach, it's a conceptual question, I have no code to expose.

**Comment by lisandroTSilva** [comment]
My expectation is that it is possible to define, individually, even globally, a limit of listing items for **site** and one for **admin**

**Comment by ghost** [comment]
@HLeithner can you please comment as Release Lead 3.9?

**Comment by HLeithner** [comment]
com_contact doesn't expose a limit parameter but it uses the global configuration default list limit, there is only one limit for frontend and backend.

You can change the limit with a layout override, f. ex. copy the default.php and and .xml and add the limit parameter to the request fields.

something like this:
```xml
	<!-- Add fields to the request variables for the layout. -->
	<fields name="request"
		addfieldpath="/administrator/components/com_categories/models/fields"
	>
		<fieldset name="request"
			addfieldpath="/administrator/components/com_contact/models/fields"
		>
			<field
				name="id"
				type="modal_category"
				label="COM_CONTACT_FIELD_CATEGORY_LABEL"
				description="COM_CONTACT_FIELD_CATEGORY_DESC"
				extension="com_contact"
				required="true"
				select="true"
				new="true"
				edit="true"
				clear="true"
			/>
			<field
				name="limit"
				type="text"
				label="limit"
				description="This is the limit parameter set for this category view"
			/>
		</fieldset>
	</fields>
```

Adding a separated global front-/backend limit would be possible but there could be some b/c issues.
It would be easier to add contact scope limiting.

If someone create a PR for 4.0 I we would consider to accept it. If you need more information about overrides plz. ask in the forum.

**Comment by ghost** [comment]
@HLeithner thanks for taking Time to comment.
