### ISSUE TITLE
Bug with 3.9.3: content plugin with leaflet doesn't works anymore

### ISSUE THREAD

**Issue by jojo12** [joomla/joomla-cms#23909]
### Steps to reproduce the issue
contentplugin osm_akuechler is installed and activated
textfilter is no filter

### Expected result
like that in Joomla! 3.9.2 it worked and showed a osmmap in article.

### Actual result
no map in article

### System information (as much as possible)
PHP erstellt für 	Linux server46.hostfactory.ch 3.16.0-6-amd64 #1 SMP Debian 3.16.56-1+deb8u1 (2018-05-08) x86_64
Datenbanktyp 	mysql
Datenbankversion 	5.5.5-10.0.35-MariaDB-0+deb8u1
Datenbankzeichensatz 	utf8mb4_general_ci
Datenbankverbindungszeichensatz 	utf8mb4_general_ci
PHP-Version 	7.2.9
Webserver 	Apache
PHP-Interface für den Webserver 	fpm-fcgi
Joomla!-Version 	Joomla! 3.9.3 Stable [ Amani ] 12-February-2019 15:00 GMT
Joomla!-Plattform-Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Browsererkennung 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by HLeithner** [comment]
I tested the plugin with 3.9.3 and it works fine for me, at least the example works fine.

You have to be more specific.

Reference to the plugin issue https://github.com/admiralsmaster/osm_akuechler/issues/8

**Comment by Bakual** [comment]
Since this is not a core issue, I'm closing it.
Please ask the developer of the plugin for further assistance.
