### ISSUE TITLE
[4.0] Auto-ordering on item saving Not working

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#23905]
### Steps to reproduce the issue
Use the \Joomla\CMS\Table\Table::save inside your Model

This function is meant abstract all the functions for saving an item (bind, check, store).
In case it gets as 2nd parameter the ordering field name ($orderingFilter), it is supposed to re-order the item, based on the existing rows in the table.

### Expected result
Give a proper/incremental ordering number

### Actual result
No number.
![localhost_filters](https://user-images.githubusercontent.com/1838041/52793842-5235a680-3077-11e9-8091-75c4c2567ddd.png)

### System information (as much as possible)
Joomla 4.0 alpha6

### Additional comments
Actual function that does the re-ordering
\Joomla\CMS\Table\Table::reorder

**Comment by ghost** [comment]
@infograf768 can you please comment?

**Comment by ghost** [comment]
@wilsonge  can you please comment as Release Lead 4?

**Comment by wilsonge** [comment]
No clue about this one off the top of my head. Sounds bad tho. Added it onto my list

**Comment by brianteeman** [comment]
can someone put the release blocker tag back please

**Comment by dgrammatiko** [comment]
FWIW also the drag and drop functionality on any list view is based on this so also that won't work correctly

**Comment by sakiss** [comment]
Maybe related with: https://github.com/joomla-framework/database/issues/213

**Comment by SharkyKZ** [comment]
Is this a MySQL 8 issue? I can't reproduce this on 5.7.31.

**Comment by SharkyKZ** [comment]
One thing that doesn't make sense is that ordering condition is required for ordering to work at all. This should not be required.

**Comment by HLeithner** [comment]
Hi @sakiss 

@bembelimen and I tried to reproduce this issue and can't find a problem not by adding directly an entry to the table not by using the backend for com_content

```php
	$componet = JFactory::getApplication()->bootComponent('com_content');

	/** @var JTable $table */
	$table = $componet->getMVCFactory()->createTable('Article');

	$array = [
		'title' => 'Test1',
		'alias' => 'test1',
		'introtext' => 'text',
		'catid' => 2,
		'language' => '*',
		'state' => 1,
	];

	$table->save($array, 'catid');

	$array = [
		'title' => 'Test2',
		'alias' => 'test2',
		'introtext' => 'text',
		'catid' => 2,
		'language' => '*',
		'state' => 1,
	];

	$table->save($array, 'catid');
```


this code results in a proper ordering.

I'm removing the release blocker label and would close this issue until you can provide a code to reproduce this issue.
