### ISSUE TITLE
Remove trailing white spaces in robots.txt

### ISSUE THREAD

**Issue by mmustermann628483** [joomla/joomla-cms#23915]
Remove the trailing white spaces in line 1, 2, 3, 6, 7, 8 and the double blank line at the end in the file robots.txt.

**Comment by hardik-codes** [comment]
@mmustermann628483 in which version of Joomla this has to be done. I'll be working on it

**Comment by Bakual** [comment]
We only ship the https://github.com/joomla/joomla-cms/blob/staging/robots.txt.dist file. The robots.txt in your web directory is done either by you manually or by your webhost.

**Comment by mmustermann628483** [comment]
Yes I am talking about the file that is shipped by the installation. It is not important, just my editor asked me to fix the white spaces. I just wanted to mention this since Joomla! has such a strict code styling. Just 10 seconds to "fix" that.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23915">issues.joomla.org/tracker/joomla-cms/23915</a>.</sub>

**Comment by hardik-codes** [comment]
@mmustermann628483 working on it

**Comment by Bakual** [comment]
Closing since we have a PR #23916
