### ISSUE TITLE
Remove trailing white spaces in htaccess

### ISSUE THREAD

**Issue by mmustermann628483** [joomla/joomla-cms#23914]
Remove the trailing white spaces in line 11, 13, 14, 15 and 38 in the file htaccess.

**Comment by HLeithner** [comment]
If you like to change the source code of the project you have to learn how to do it. Github makes it really simple for small changes.

In your case, you only have to open the file to change in github, click on the edit button and make the changes you want to do. After this you get a pull request page, there you can create a pull request against the joomla repository and we can the the change easily and merge it if its good and useful.

More information could be found here https://help.github.com/articles/editing-files-in-another-user-s-repository/

**Comment by hardik-codes** [comment]
@mmustermann628483 in which version of Joomla this has to be done. I'll be working on it

**Comment by Bakual** [comment]
We don't create any .htaccess file. This would have been done by you or your webhost.
What we ship is the file https://github.com/joomla/joomla-cms/blob/staging/htaccess.txt.

If I look at your mentioned lines, those are all comments. A trailing whiespace doesn't matter at all there.
Is there a reason you want to remove those?

**Comment by mmustermann628483** [comment]
Yes I am talking about the file that is shipped by the installation. It is not important, just my editor asked me to fix the white spaces. I just wanted to mention this since Joomla! has such a strict code styling.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23914">issues.joomla.org/tracker/joomla-cms/23914</a>.</sub>

**Comment by hardik-codes** [comment]
@mmustermann628483  working on it

**Comment by Bakual** [comment]
Closing since we have a PR #23917
