### ISSUE TITLE
[4.0] - Menu Item Type - Button single article Edit not working

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/joomla-cms#23910]
### Steps to reproduce the issue

* Create a menu item of the Single article type 
* Click button "Edit" for editing selected article.
![edit_article](https://user-images.githubusercontent.com/29527200/52851733-1fdb8600-3117-11e9-875d-d15b62606bfc.png)

### Expected result
The modal window should open.

### Actual result
Modal window does not open. Errors are reported in the console
```JavaScript
Unchecked runtime.lastError: The message port closed before a response was received.

VM789:1 Uncaught SyntaxError: Unexpected token &
    at HTMLDivElement.<anonymous> (bootstrap-init.min.js?b6432954b58a2d1215a2ab1cfd487988:1)
    at HTMLDivElement.dispatch (jquery.min.js?3.3.1:2)
    at HTMLDivElement.y.handle (jquery.min.js?3.3.1:2)
    at Object.trigger (jquery.min.js?3.3.1:2)
    at HTMLDivElement.<anonymous> (jquery.min.js?3.3.1:2)
    at Function.each (jquery.min.js?3.3.1:2)
    at w.fn.init.each (jquery.min.js?3.3.1:2)
    at w.fn.init.trigger (jquery.min.js?3.3.1:2)
    at r.e.show (modal.js:117)
    at HTMLDivElement.<anonymous> (modal.js:517)
```
### System information (as much as possible)
Setting | Value
-- | --
PHP Built On | Linux m36s20-6-25db.ispgateway.de 3.18.117-pvops-xen-x64 #1 SMP Tue Aug 7 13:41:39 CEST 2018 x86_64
Database Type | mysql
Database Version | 5.6.19-67.0-log
Database Collation | utf8_general_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.2.3
Web Server | Apache/2.4.35
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 4.0.0-alpha7-dev Development [ Amani ] 27-December-2018 17:58 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

**Comment by amitranjan2** [comment]
issue confirmed

**Comment by amitranjan2** [comment]
And also,
Save & Close   and Save button not working
Only Close button is working

**Comment by zwiastunsw** [comment]
@amitranjan2 
Save @ Close button not working in modal window when you can open a modal window (See: https://github.com/joomla/joomla-cms/issues/23260) . In this case the modal window cannot be opened at all.

**Comment by puneeth-chanda** [comment]
![screenshot from 2019-02-15 17-28-59](https://user-images.githubusercontent.com/43813460/52855533-af992880-3147-11e9-9dc4-8e651692d545.png)
I am getting nothing like that

**Comment by zwiastunsw** [comment]
1. click Select button
2. Select menu type Articles > Single Article
3. Select article

**Comment by amitranjan2** [comment]
Follow this

click >> Select >> Articles>>Single Article

**Comment by puneeth-chanda** [comment]
can I work on this issue?

**Comment by zwiastunsw** [comment]
I think so.  And also on that: https://github.com/joomla/joomla-cms/issues/23260
You don't need a permission to do it. We are happy to help you.

**Comment by Quy** [comment]
Please test PR #24349<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23910">issues.joomla.org/tracker/joomla-cms/23910</a>.</sub>
