### ISSUE TITLE
[4.0] custom field fancy select

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#23920]
### Steps to reproduce the issue
Where this field type is displayed we have extra space as seen below

![image](https://user-images.githubusercontent.com/1296369/52905528-632b1700-3233-11e9-9e5b-6fa72bfab6bb.png)

@dgrammatiko can you take a look

**Comment by dgrammatiko** [comment]
tags?

**Comment by brianteeman** [comment]
yes - sorry didnt want the screen shot too big

![image](https://user-images.githubusercontent.com/1296369/52905552-b4d3a180-3233-11e9-93c3-423a87f7c5f8.png)

**Comment by dgrammatiko** [comment]
Hm, I don't get that, which browser?

**Comment by brianteeman** [comment]
Not on all pages it would seem

Check  User Notes: Edit Category

**Comment by dgrammatiko** [comment]
This is coming from the choices.js:
![screenshot 2019-02-16 at 23 04 07](https://user-images.githubusercontent.com/3889375/52905767-3b41b080-323f-11e9-8a08-3011cf0e4efc.png)

**Comment by brianteeman** [comment]
but why only on that page?

**Comment by dgrammatiko** [comment]
It's your beloved Bootstrap, just remove the class `col-sm-12`

**Comment by brianteeman** [comment]
so its not choices then ;)

**Comment by dgrammatiko** [comment]
I tend to blame always Javascript but when Bootstrap is also involved my chances are running low on the first one 😛

**Comment by brianteeman** [comment]
Closed see #23921
