### ISSUE TITLE
Add language param to Custom HTML module in backend

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#23926]
We can use a custom HTML module for back-end to display something on dashboard.
Since this module means custom text, in the case of multilingual website it might be useful to allow admin to prepare different HTML modules for each language section.

Yes, it is possible  to make a new module like 'hello world' and insert one language string there which might be overriden via Joomla override, but my idea is to add a new param to Custom HTML moduel [backend] to select the language below "ordering" param.

![screen shot 2019-02-17 at 23 43 27](https://user-images.githubusercontent.com/3432048/52918936-ed47ae00-330d-11e9-9ed9-40b76eace1a2.png)

![screen shot 2019-02-17 at 23 41 49](https://user-images.githubusercontent.com/3432048/52918977-6f37d700-330e-11e9-8a93-00e7c8339c3b.png)

**Comment by brianteeman** [comment]
Admin modules already do this

**Comment by Sulpher** [comment]
I do not see an option to select the language for admin modules (see the screenshot above). There is no such problem for front modules.

**Comment by Sulpher** [comment]
![jadmin](https://user-images.githubusercontent.com/3432048/52919170-98596700-3310-11e9-9f74-0865bdc10d57.gif)
Joomla 3.9.3

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/52919235-00e81a00-32f8-11e9-9eea-ac5c8f4a4ac0.png)

**Comment by Sulpher** [comment]
Wow, I did not about this feature. Thank you, Brian :-)
