### ISSUE TITLE
Update to Joomla 3.9.3 fails (PostgreSQL)

### ISSUE THREAD

**Issue by twister65** [joomla/joomla-cms#23925]
PR #23526 ([com_actionlogs] - log checkin actions) fails.
### Steps to reproduce the issue
Update to Joomla 3.9.3 with a PostgreSQL database.

### Expected result
No alert message.

### Actual result
![update3-9-3](https://user-images.githubusercontent.com/26852967/52916124-15b6b480-32dc-11e9-8b4d-1fed367144d0.png)

**Comment by twister65** [comment]
To fix this issue, apply this SQL script to your postgreSQL database before the update to Joomla 3.9.3 : 
[3.9.4-2019-02-17.txt](https://github.com/joomla/joomla-cms/files/2873171/3.9.4-2019-02-17.txt)
Don't forget to change the prefix (#_).

**Comment by wilsonge** [comment]
@alikon Are you able to take a look into this?

**Comment by alikon** [comment]
sure i'll look at this

**Comment by alikon** [comment]
unable to reproduce upgrading from 3.9.2 to 3.9.3 with postgresql 11.1 (Ubuntu 11.1-3.pgdg18.04+1) 
@twister65 from what version of joomla are you upgrading ? and on what postgresql version ?

**Comment by twister65** [comment]
I upgraded from Joomla 3.9.0 to 3.9.3 with postgresql 10.6.

**Comment by twister65** [comment]
The update of Joomla 3.8 to Joomla 3.9 revealed anomalies with Log action and privacy tool suite. The tables have been created but not the sequences. I do not know why, I can not explain it.
