### ISSUE TITLE
Uploading File Exists Error

### ISSUE THREAD

**Issue by rgtr** [joomla/joomla-cms#23924]
### Steps to reproduce the issue
If you have a media item with spaces [uploaded in 2013 when spaces in media file names was acceptable], rename the item with "-"'s replacing the spaces
Upload.

### Expected result
File will upload. e.g. 
Old file: "SN Mill 20.jpg" with spaces remains
New File "SN-Mill-20.jpg" with dashes uploads ok,

### Actual result
Error File Exits

### System information (as much as possible)
Joomla 3.9.3 on PHP 7.2.14
Database mysql - 5.5.5-10.1.27-MariaDB
Apache/2.4.37 (Unix)
Database Collation - utf8_general_ci
Database Connection Collation - utf8mb4_general_ci

### Additional comments
Seems like the comparison needs to be corrected.
However, renaming to "sn-Mill-20.jpg" uploads ok !

**Comment by rgtr** [comment]
No visible code to a Joomla User ...

**Comment by ghost** [comment]
@infograf768 can you please comment?

**Comment by infograf768** [comment]
I can't reproduce the issue here.

**Comment by ghost** [comment]
closed as unconfirmed Report. Please reopen if closing was wrong.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23924">issues.joomla.org/tracker/joomla-cms/23924</a>.</sub>
