### ISSUE TITLE
mail protect

### ISSUE THREAD

**Issue by stankurd** [joomla/joomla-cms#23935]
### Steps to reproduce the issue
Joomla 4.0
script joomla-hidden-mail.min.js crash site i get this error in konsole 
Error: Script terminated by timeout at:n
connectedCallback@/media/system/js/joomla-hidden-mail.min.js?793a1d91502d7a55abeb1654c7aa6828:1:498
@http:///media/system/js/joomla-hidden-mail.min.js?793a1d91502d7a55abeb1654c7aa6828:1:14

**Comment by dgrammatiko** [comment]
@stankurd browser? steps to reproduce?

**Comment by stankurd** [comment]
=============
System Information
=============
php: Linux s36.linuxpl.com 4.4.41-grsec #1 SMP Tue Jan 10 11:31:31 CET 2017 x86_64
dbserver: mysql
dbversion: 5.6.36
dbcollation: latin2_general_ci
dbconnectioncollation: utf8_general_ci
phpversion: 7.3.0
server: Apache
sapi_name: cgi-fcgi
version: Joomla! 4.0.0-alpha7-dev Development [ Amani ] 27-December-2018 17:58 GMT
useragent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by zero-24** [comment]
@stankurd can you reproduce the issue when you have cleared the Firefox browser cache? And can you confirm this on the latest nightly build too?
https://developer.joomla.org/nightly-builds.html

When yes please let us know what you do to get the mention error message.

**Comment by ghost** [comment]
closed as no reply. It can always reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23935">issues.joomla.org/tracker/joomla-cms/23935</a>.</sub>
