### ISSUE TITLE
looping in users goups

### ISSUE THREAD

**Issue by rolandalsace** [joomla/joomla-cms#23933]
Possible to make looping in users groups
See pictures (copy of DB)

### Steps to reproduce the issue
Always

### Expected result
Fatal error: Maximum function nesting level of '256' reached, aborting! in ...\libraries\src\Helper\UserGroupsHelper.php on line 169

**Comment by rolandalsace** [comment]
![screen shot 2019-02-18 at 11 25 11](https://issues.joomla.org/uploads/1/76147d108e3281d0ca2753ae1257abea.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23933">issues.joomla.org/tracker/joomla-cms/23933</a>.</sub>

**Comment by zero-24** [comment]
how did you configured such group loop?

**Comment by rolandalsace** [comment]
Hi.
Simply, in admin com_users&view=group&layout=edit , in changing parent user group and selecting a son by error

**Comment by rolandalsace** [comment]
Strange that sons are displayed in select field.

**Comment by zero-24** [comment]
Hi please check this PR: https://github.com/joomla/joomla-cms/pull/24021.

As we have an PR I'm going to close this issue here. Please let us know your test results there.
