### ISSUE TITLE
[4.0] Media Manager missing strings

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#23943]
There are two language files for the media manager. 

language\en-GB\en-GB.com_media.ini
administrator\language\en-GB\en-GB.com_media.ini

I would expect them to have the same number of strings as there is no difference between the front end and the admin views (at least that I could see)

I would also expect that the values of the strings was the same in both but it is not
eg
COM_MEDIA_NAME="Image Name"
COM_MEDIA_NAME="Name"

**Comment by puneeth-chanda** [comment]
@brianteeman  just clarifying that it is been called from administrator\language\en-GB\en-GB.com_media.ini  i.e. 'COM_MEDIA_NAME="Name" ' this is the correct one I think

**Comment by mbabker** [comment]
If the admin language file is the only one used then the frontend file should be removed.  It's an excess and unused resource and it puts extra work on translators to maintain an unused resource (and they already have enough excess work in their workflows).

**Comment by brianteeman** [comment]
@puneeth2001 then please remove the incorrect file if it is not being used AND check that all the required strings are present. For example COM_MEDIA_INCREASE_GRID is not present in the admin version but it is needed

**Comment by puneeth-chanda** [comment]
@brianteeman surprisingly only 'COM_MEDIA_NAME' string is the only thing which is present in common in both the files(but with different string values) and remaining all strings are different i.e if one is present in a file it is not present in the other one.  I'll put the screenshot of the code if necessary.

**Comment by brianteeman** [comment]
This string is still missing COM_MEDIA_INCREASE_GRID Check the code!!!

**Comment by puneeth-chanda** [comment]
ok I'll check it

**Comment by puneeth-chanda** [comment]
sorry!! yes, there are some strings along with this which must be added.

**Comment by puneeth-chanda** [comment]
@brianteeman there are a lot of strings which need to be added and I am not sure that they might be used from the other file somewhere I think it's better to leave it that way or any suggestions??

**Comment by brianteeman** [comment]
No it is not better to leave it broken

**Comment by puneeth-chanda** [comment]
ok I'll do it.

**Comment by brianteeman** [comment]
Closed see #23957
