### ISSUE TITLE
[4.0] CLI ConsoleApplication must be declered abstract

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#23941]
### Steps to reproduce the issue

Just execute /cli/joomla.php on command line

### Expected result
Output of the working cli

### Actual result
Following php error:
```php
contains 1 abstract method and must therefore be declared abstract or implement the remaining methods
```

### System information (as much as possible)
PHP 7.1

### Additional comments
Maybe this caused by following abstract functions in `libraries/src/Application/EventAware.php`:
```php
/**
         * Get the event dispatcher.
         *
         * @return  DispatcherInterface
         *
         * @since   4.0.0
         * @throws  \UnexpectedValueException May be thrown if the dispatcher has not been set.
         */
        abstract public function getDispatcher();

        /**
         * Get the logger.
         *
         * @return  LoggerInterface
         *
         * @since   4.0.0
         */
        abstract public function getLogger();
```
I saw we are user this in `/libraries/src/Application/ConsoleApplication.php`:
```php
use DispatcherAwareTrait, EventAware, IdentityAware, ContainerAwareTrait, ExtensionManagerTrait;
```
on line 35.

**Comment by mbabker** [comment]
This would be fixed by https://github.com/joomla/joomla-cms/pull/23847 but apparently either I'm on a pull request blacklist or changes that aren't related to the template or web applications causing errors to be thrown in everyone's faces aren't getting any attention.

**Comment by ghost** [comment]
Still got the same error.

**Comment by mbabker** [comment]
You need to be using the current git branch.  Nightly builds are built nightly, not on every commit.

**Comment by ghost** [comment]
I merged the current 4.0-dev branche in to my 4.0 and update my command classes to use the new structure.

**Comment by mbabker** [comment]
You did a fresh `composer install` as well to bring in the current dependency tree?

**Comment by ghost** [comment]
thanks @mbabker. Miss the `composer install`
