### ISSUE TITLE
Invalid comments in modules?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#23954]
Am I being daft and missing something but when I read 

https://github.com/joomla/joomla-cms/blob/a66130ac6cf28ab6d23cd64a5b7b28e581f9d907/modules/mod_articles_latest/helper.php#L47-L50

The comment implies to me that each of these is set by a param in the module. But only one of those is actually set by a param in the module

**Comment by HLeithner** [comment]
I think you only need the count parameter, because you want the latest X articles that are visible.

But yes I think you can remove the comment if you want.

**Comment by brianteeman** [comment]
Annoyingly I actually wanted to be able to display unpublished items which is how I came to this code

**Comment by brianteeman** [comment]
Closed see #23964 for solution
