### ISSUE TITLE
[3.9.3] New User Activation: joomla fail to send mail to user after manual activation frpm backend

### ISSUE THREAD

**Issue by robertwline** [joomla/joomla-cms#23952]
### Steps to reproduce the issue
When new user registers at the site I provide to enable/activate him from backand area.

### Expected result
Clicking on the activate/enabling button user link, in the backand area, should sent email to user to inform him about approved activation.

### Actual result
The user is enabled and activated but the user doesn't reveive any activation mail.

### System information (as much as possible)
Joomla 3.9.3
PHP 7.2.12 on Linux Apache
MySQL 5.6.4

**Comment by brianteeman** [comment]
This is a known issue. There is no code in Joomla to perform this action. 

You can read about some plugins etc to fix this for you in this article and its comments https://brian.teeman.net/joomla/870-authorising-and-approving-joomla-users

**Comment by robertwline** [comment]
Thanks

**Comment by alikon** [comment]
there is already a pr for this  #20282

**Comment by robertwline** [comment]
Thanks
