### ISSUE TITLE
Logo não aparece no Google Chrome do Joomla 1.6.3

### ISSUE THREAD

**Issue by lborges1310** [joomla/joomla-cms#23955]
O logo do meu site Joomla 1.6.3 não aparece no Google Chrome.

Ele aparece normalmente no Internet Explorer

**Comment by C-Lodder** [comment]
1. Please write your issues in English
2. Joomla 1.6.3 is no longer supported. Please refer to the migration documentation and get your site updated

**Comment by mbabker** [comment]
According to Google Translate, this is an issue with the logo on your site.  As this is a template issue, you should seek support in the forums at https://forum.joomla.org (there is an international section as well to post in your native language if English isn't a strong language for you).  Likewise, Joomla 1.6 is not supported at all.  So closing as not a core issue.
