### ISSUE TITLE
What is the point of $glue in union

### ISSUE THREAD

**Issue by spignataro** [joomla/joomla-cms#23958]
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/database/query.php#L1519

When looking at doing unions we are very limited considering it looks like for many years that union() function in the primary query is still lacking the $glue capability. Is there a reason why we can not set our own glue for our unions?

**Comment by HLeithner** [comment]
you are right seams useless at least for the shipped JDatabaseQuery classes

**Comment by puneeth-chanda** [comment]
does this belong to J4

**Comment by ghost** [comment]
@HLeithner can you please comment?

**Comment by HLeithner** [comment]
I think this is not an issue and can be closed, because it keeps the API consistent and maybe needed by new database drivers.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23958">issues.joomla.org/tracker/joomla-cms/23958</a>.</sub>
