### ISSUE TITLE
com_content workflow transition field problem

### ISSUE THREAD

**Issue by rolandalsace** [joomla/joomla-cms#23960]
In com_content edit form, the select transition list have no option (only the actual state of the current item.

The problem is here : 

In /components/com_content/froms/articles.xml the field "transition" have this description :

		<field
			name="transition"
			type="transition"
			component="com_content"
			addfieldprefix="Joomla\Component\Workflow\Administrator\Field"
			label="COM_CONTENT_STATE"
		>

But the "transition" field (in /librairies/src/Form/Field/TransitionField.php) use $element['extension'] in line 73.

So it would have to change component="com_content" to extension="com_content" in com_content articles.xml transition field.

	<field
			name="transition"
			type="transition"
			extension="com_content"
			addfieldprefix="Joomla\Component\Workflow\Administrator\Field"
			label="COM_CONTENT_STATE"
		>
So the select transition options list is well generated.

Regards.

### Steps to reproduce the issue
Always

**Comment by bembelimen** [comment]
Thx for this find, please test the PR...

**Comment by Quy** [comment]
Please test PR #23996<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23960">issues.joomla.org/tracker/joomla-cms/23960</a>.</sub>
