### ISSUE TITLE
[4.0] Note field

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#23966]
### Steps to reproduce the issue
The note field is used to display the information about the skins in the tinymce editor plugin

The code has always been wrong but in j4 it now results in visually broken code as well

![image](https://user-images.githubusercontent.com/1296369/53165328-54918680-35ca-11e9-9cef-6deecabdae89.png)

**Comment by infograf768** [comment]
The correct path is
`/media/vendor/tinymce/skins/`
but placing a new skin there is killed when using npm ci.
As, normally, final users do not have to use npm ci when updating J, it may be possible to add the skin there and it would not be deleted. Not sure.

Also, tinymcebuilder is not designed to load the css from such a new skin. As well for init.es6.js. Maybe more in other files (theme.js, etc.).

@dgrammatiko 
Shall we just get rid of the Note itself and only use lightgray or is it possible to correct all this?

**Comment by brianteeman** [comment]
the actual text is off topic - please open a separate issue for that - this issue is about the Note field itself. I just used the skins as an example of its use. It is used in many places

**Comment by dgrammatiko** [comment]
@infograf768 I’m pretty sure I had a pr that cleaned up this mess by moving the override template to the actual template of the site

**Comment by dgrammatiko** [comment]
@infograf768 feel free to resurrect: 
https://github.com/joomla/joomla-cms/pull/14510 and https://github.com/joomla/joomla-cms/pull/14456
Both totally valid and imo needed changes. These PRs align tinyMCE to the rest of the overriding methods on Joomla

**Comment by infograf768** [comment]
@dgrammatiko 
Alas I would not know what to do with these.

@brianteeman 
The issue looks related to renderfield.php which does not accept specific elements in the xml, allowing therefore to create new css classes or conditions to cope with this bad display.

**Comment by infograf768** [comment]
Checked further:
1. I see no reason (for TinyMCE) to use the Note type for that field. Using a spacer would be easier. (as we do for com_media Options). Don't know if any pb with spacer and a11y. If there is then the spacer field may have to be modified.
2. The renderfield.php file has been heavily modified in 4.0 vs 3.x. This explain the double display of the description in a supplementary `<div>`.
See https://github.com/joomla/joomla-cms/pull/18465 by @C-Lodder  and https://github.com/joomla/joomla-cms/pull/22165 by @brianteeman 
It is not obvious to find out the reasons **as these were merged without ever being tested OK**, this already in 2017...
3. As stated above there are ways to define specific classes in the xml and then check if they exist in renderfield.php $displayData and depending on this, create new css to correct the display.

I know there other fields in core using the Note field type but could not find a way to display them.
To implement this, it would be useful to test these too.

There may be simpler solutions but could not find them.
@C-Lodder

**Comment by brianteeman** [comment]
The problem is that this field (and others) is not using a layout - instead all the markup is being generated (badly) in the library` libraries\src\Form\Field\NoteField.php`

@wilsonge has already pointed out that all fields need to use a layout and that will resolve everything for this note field as well.

~I will try to work on this next week but if anyone else wants to do it then just go for it~

**Comment by brianteeman** [comment]
@SharkyKZ as you did the checkbox field it would be great if you could also do the note field

**Comment by brianteeman** [comment]
Closing this as the issue with tinmyce has been fixed with #29259

**Comment by brianteeman** [comment]
Re-opened - #29259 just masked the problem by not using the note field. the problem still exists if the field is used.

**Comment by brianteeman** [comment]
closed see #29710
