### ISSUE TITLE
[4.0]Out of image buttons unusable in media-manager

### ISSUE THREAD

**Issue by bahl24** [joomla/joomla-cms#23968]
Go to media manager, decrease icon size, click image actions
![screenshot from 2019-02-21 17-21-36](https://user-images.githubusercontent.com/36095178/53167263-7821f480-35fd-11e9-9521-2435e2806bd4.png)
Buttons outside image are unusable as action tab closes as we leave image

### Expected result
All buttons work

### Actual result
action tab closes as we leave image

**Comment by puneeth2001** [comment]
Can I work on this?

**Comment by ghost** [comment]
@infograf768 can you please comment?

**Comment by anuragteapot** [comment]
@bahl24 We have lots of issue for media-manager. Try to fix this like this. 
https://github.com/joomla-projects/media-manager-improvement/issues/567

**Comment by ghost** [comment]
@bahl24 have you tried to fix like @Anu1601CS suggested?

**Comment by bahl24** [comment]
On it.

**Comment by ghost** [comment]
@bahl24 any News?

**Comment by ghost** [comment]
closed as having Pull Request #24423
