### ISSUE TITLE
Problems removing news feed extension

### ISSUE THREAD

**Issue by dioubernardo** [joomla/joomla-cms#23974]
### Steps to reproduce the issue
Uninstall newsfeed extensions

### Expected result
Remove all itens from menu

### Actual result
A menu item named com_newsfeeds_categories is visible

### System information (as much as possible)
Joomla 3.9.3 default instalation

### Additional comments
In index.php?option=com_installer&view=database

Table 'joomla.#__newsfeeds' doesn't exist

Tabela 'ce6py_newsfeeds' não deve conter a coluna 'filename'. (Do arquivo 3.0.0.sql.)
Tabela 'ce6py_newsfeeds' não possui a coluna 'description'. (Do arquivo 3.0.0.sql.)
Tabela 'ce6py_newsfeeds' não possui a coluna 'version'. (Do arquivo 3.0.0.sql.)
Tabela 'ce6py_newsfeeds' não possui a coluna 'hits'. (Do arquivo 3.0.0.sql.)
Tabela 'ce6py_newsfeeds' não possui a coluna 'images'. (Do arquivo 3.0.0.sql.)
A tabela 'ce6py_newsfeeds' tem um tipo ou atributos errados para a coluna 'link' com o tipo VARCHAR(2048). (Do arquivo 3.6.3-2016-08-15.sql.)
A tabela 'ce6py_newsfeeds' tem um tipo ou atributos errados para a coluna 'xreference' com o tipo varchar(50). (Do arquivo 3.7.0-2017-03-03.sql.)

**Comment by mbabker** [comment]
Core extensions cannot be uninstalled, this will cause problems.

**Comment by brianteeman** [comment]
This should be closed

**Comment by dioubernardo** [comment]
All other core extensions are protected at /administrator/index.php?option=com_installer&view=manage. It is not. It would be interesting then to block it so that it can not be uninstalled in the administrative interface.

I'm a user, if it's allowed to do it! ;) As you know I should not do it I think it should be blocked.

**Comment by mbabker** [comment]
Protected has a very bad definition and is heavily misused.  If you mark something protected, you can't disable it either, and most core extensions can be safely disabled.  I tried fixing this definition, sadly like most purely technical pull requests it ended up abandoned because I couldn't continue keeping a patch updated that clearly was not getting any attention.
