### ISSUE TITLE
[4.0] Save button icon

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#23971]
As reported here https://github.com/joomla/joomla-cms/pull/23942#issuecomment-465076511

The newly separated save button uses a different icon to the save group.

The design proposal was to use the same icon for both. 

Plus it seems odd to me to use the icon for edit to signify save https://fontawesome.com/v4.7.0/icon/pencil-square-o

**Comment by bahl24** [comment]
@brianteeman Can I work on this?
Replacing edit icon with the save one would be the best option

**Comment by brianteeman** [comment]
@bahl24 you do not need to keep asking

**Comment by bahl24** [comment]
@brianteeman Which icon should I replace the pencil symbol with?

**Comment by bahl24** [comment]
Plus or Check or files symbol

**Comment by infograf768** [comment]
Using the present icon is fine imho and consistent with 3.x

<img width="433" alt="screen shot 2019-02-22 at 08 29 39" src="https://user-images.githubusercontent.com/869724/53226690-31bfaa80-367c-11e9-9f94-4b80c9098621.png">

**Comment by infograf768** [comment]
If it has absolutely to be changed, we may want to use
https://fontawesome.com/v4.7.0/icon/floppy-o
which does mean save in fontawesome

**Comment by HLeithner** [comment]
you are really funny jean-marie ;-) we have 2019

**Comment by chmst** [comment]
icon-bookmark ?

**Comment by HLeithner** [comment]
to be a bit constructive, my opinion is something like this:
![image](https://user-images.githubusercontent.com/1497730/53233173-05605a00-368d-11e9-9617-a542dc0a008b.png)

**Comment by brianteeman** [comment]
Whats wrong with using the same icon for both. They are both "save". The design proposal uses the same icon for both

**Comment by HLeithner** [comment]
also possible but I think one is "save and continue working" and the other ist "save and be finished"

But the save icon at the moment is the "edit" icon so that would be "wrong" anyway

**Comment by bahl24** [comment]
@infograf768 's icon seems most appropriate

**Comment by drmenzelit** [comment]
I think, the edit icon is maybe "wrong", but for me it implies that I saved my work but I can still edit something. So in my opinion we should keep the current icon.

**Comment by brianteeman** [comment]
When you are using an external and common icon set and the icon is called "edit" then it is reasonable to assume that users will see this icon being used elsewhere to indicate "edit" and not "save" which is what we want.

Anyway I brought this up simply because the design document shows one icon being used for both

**Comment by ghost** [comment]
@bahl24 are you working on it?

**Comment by bahl24** [comment]
@franz-wohlkoenig I think from the above discussion, that icon change is not needed. Correct me if I am wrong.
I was going to work, but there was no conclusion.

**Comment by brianteeman** [comment]
Closing this as the icon used is now the same for both buttons in the new template. Although @HLeithner will be happy that the icon that's been chose is the floppy disk 🤦‍♂ 

![image](https://user-images.githubusercontent.com/1296369/59152651-85de7700-8a40-11e9-9cc9-01c16d0580ab.png)
