### ISSUE TITLE
[4.0] com_media frontend edit image with xtd broken

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#23979]
### Steps to reproduce the issue
Log in frontend as super User.
Edit an article and select the Image xtd (Used TinyMce as editor)
Try to edit an image.

### Actual result
Frontend page loaded in modal

![mediafrontend](https://user-images.githubusercontent.com/869724/53228352-39ce1900-3681-11e9-87bd-02db550f5a3c.gif)

Looks like the issue is different from https://github.com/joomla/joomla-cms/issues/23510

**Comment by puneeth-chanda** [comment]
@infograf768 What do you want the expected result to be?

**Comment by infograf768** [comment]
Same as in backend: being able to use these edit functionalities, when authorized to do so.

**Comment by puneeth-chanda** [comment]
issue confirmed!

**Comment by vijay9908** [comment]
I am not getting any images to select one and even after downloading and uploading an image, I am getting no image shown up from uploads
I am currently running macOS and tried replicating issue using safari

**Comment by ghost** [comment]
@infograf768  how you create this image to show actual result?

**Comment by infograf768** [comment]
I use Licecap on Macintosh

**Comment by ghost** [comment]
Issue seems to be resolved. @infograf768 can you please have a look?
#### System Information

Setting | Value
-- | --
PHP Built On | Linux lamp129.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.5.el6h.x86_64 #1 SMP Thu Nov 22 10:07:47 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.23-cll-lve
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.7
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 4.0.0-alpha11-dev Development [ Amani ] 29-June-2019 11:27 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by Quy** [comment]
It is no longer an issue to edit an image, however, there is an issue to insert an image.

> TypeError: Joomla.getImage is not a function

**Comment by Quy** [comment]
Please test PR #27634<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23979">issues.joomla.org/tracker/joomla-cms/23979</a>.</sub>
