### ISSUE TITLE
[4.0] Media Manager paths

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#23972]
Media Manager has an option to set the path to the images folder. But the new media manager doesnt use that path - instead it uses the paths defined in the filesystem plugin.

However we cant just delete the path set in the options as 
1. what happens on upgrades from J3 that have a path set that isnt "images"
2. we still use the image_path that is set in the component options in multiple places

**Comment by vijay9908** [comment]
Can I know about this issue in detail! , so  that I can work on this.

**Comment by brianteeman** [comment]
@vijay9908 all the detail is in the original post

**Comment by ghost** [comment]
@vijay9908 are you working on this Issue?

**Comment by vijay9908** [comment]
No Sir

**Comment by ghost** [comment]
@vijay9908 thanks for your Answer. I asked because of https://github.com/joomla/joomla-cms/issues/23972#issuecomment-469660355

**Comment by dgrammatiko** [comment]
@brianteeman I think my comment https://github.com/joomla/joomla-cms/pull/34634#issuecomment-869147325 is a proper solution (the foundation exists in J4, as we can have as many local adapters as we want).
Also maybe defaulting to a folder `user_uploads` or something more appropriate as the media manager can now deal with more media types than just images (assuming that #34634 will be merged)

**Comment by brianteeman** [comment]
doesnt resolve the issue raised here

**Comment by dgrammatiko** [comment]
> doesnt resolve the issue raised here

I've linked to a comment/proposal about a possible solution and yes the other PR is unrelated to this issue

**Comment by brianteeman** [comment]
Closing as we have a similar issue #31568 that includes this
