### ISSUE TITLE
Fatal error on PHP 5.4.19 on repeatable-table.php

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#23982]
### Steps to reproduce the issue
Use Joomla subform on PHP older than 5.5

### Expected result
Works as expected

### Actual result
Fatal error: Can't use function return value in write context in /home/content/76/10380776/html/imbarcoimmediato/layouts/joomla/form/field/subform/repeatable-table.php on line 59

### System information (as much as possible)
Joomla 3.9.3, PHP 5.4.19 (it's a client website)

### Additional comments
The line of code causing the error is here https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/form/field/subform/repeatable-table.php#L59 . According to php manual http://php.net/manual/en/function.empty.php:

> Prior to PHP 5.5, empty() only supports variables; anything else will result in a parse error

Maybe we can change if (!empty(JText::_($field->description))) to if (JText::_($field->description) !== '') or add a new variable to store JText::_($field->description) before passing it to empty call

**Comment by Quy** [comment]
Please test PR #23984<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23982">issues.joomla.org/tracker/joomla-cms/23982</a>.</sub>
