### ISSUE TITLE
[3.9.3] Language overrides Filter Field is Missing - after update to 3.9.3

### ISSUE THREAD

**Issue by chrisvphogan** [joomla/joomla-cms#23988]
### Steps to reproduce the issue

After update to Joomla 3.9.3 I seem to have lost the ability to add overrides.

I have English GB as default language. When I try to create a new override I am asked to select a language and client, but the box to enable me to do this is not there. 

### Expected result

A dropdown box with a list of 'installed languages' should be there!? 

### Actual result

The box to enable me to do this is not there. 

### System information (as much as possible)

Joomla v3.9.3
PHP v7.1.26
T3 Framework 2.7.4

### Additional comments

This was a previous issue on this thread: https://github.com/joomla/joomla-cms/issues/22885

**Comment by infograf768** [comment]
The possible issues and way to solve it are listed in https://github.com/joomla/joomla-cms/issues/22885

**Comment by chrisvphogan** [comment]
Tried to clear cache etc and I've also tried to reinstall the 3.9.3 update again via the Joomla Backend and 'Components' > 'Joomla! Update' 

Problem is, Akeeba kicks in, and begins to back up (but fails)...I also tried FTP upload of the update, but I get the same Akeeba problem, and even when I try to install/upload the package, the same problem of the backup just going to a blank page occurs!

Its so weird as Akeeba does work, but I did try to re-install it, to no aval...

I also tried to manually ftp/upload the bar.php to this location:

administrator/components/com_languages/layouts/joomla/searchtools/default

...from the latest Joomla v3.9.3 and 3.9.2 and that did not work either?!

**Comment by brianteeman** [comment]
Disable akeeba backup on update option

**Comment by chrisvphogan** [comment]
Ok great didn’t know that was available as it wasn’t named as Akeeba in plug-ins:

‘System - Backup on update’

I’ll give this a go once at computer...and hope the missing bar appears on the overrides!

**Comment by chrisvphogan** [comment]
After trying to install without System - Backup on update turned on I get the following message now?

![screenshot 2019-03-02 at 14 44 05](https://user-images.githubusercontent.com/22639013/53683645-30852200-3cfb-11e9-9320-4ae4dff8f8ee.png)

**Comment by ghost** [comment]
@chrisvphogan have you asked in Forum?

**Comment by infograf768** [comment]
Try "Fix" database and then indeed ask in forums as someone may want to help you by accessing yor site.

**Comment by chrisvphogan** [comment]
Yes I've asked the Joomla forum...the above error has been fixed via ‘extentions database manager’ but i now get another error: 0 Joomla\Filesystem\File::delete: Failed deleting data.php

I also tried to install quite a few plugin etc in the Extensions » Discover

**Comment by ghost** [comment]
closed as issue for Forum.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23988">issues.joomla.org/tracker/joomla-cms/23988</a>.</sub>
