### ISSUE TITLE
User permissions reseted after update to 3.9.3

### ISSUE THREAD

**Issue by team187** [joomla/joomla-cms#23987]
### Additional comments

Hello,

I had a problem on several sites after upgrading to the latest version of joomla from 3.9.1. I have modified the default Manager permissions before the upgrad, to display only few menus and components and everything was reseted now. And I had to set them up again.

Thanks,
Bojan

**Comment by zero-24** [comment]
´Dear Bojan, please let us know what was changed and what got lost. Could you reproduce this issue with an core install without any 3rd Party extensions?

And what 3prd Party extensions are installed on that site? I personally can not remember any change that would cause such an problem between 3.9.1 and 3.9.3.

> I have modified the default Manager permissions before the upgrad

Just a sidenote it is not recommended to do this and changing the core shipped roles. The recommended way is to copy that group and than apply changes. But anyway something like that should not happen so please let us know how we can debug this.

**Comment by mbabker** [comment]
> > I have modified the default Manager permissions before the upgrad
> 
> Just a sidenote it is not recommended to do this and changing the core shipped roles.

Since when?  The ACL tree is nothing like other parts of the system in that it can fully be customized (you really only need 3 ACL groups for a fully functional site; Public (the root node of it all), Guest (this is in part thanks to that goofy parameter that exists), and Super User (because someone has to manage things)), there is no requirement that the groups and settings that ship with the CMS be kept as is and if there were then those groups should be hardcoded everywhere.

**Comment by zero-24** [comment]
Yes and as noted I don't see a technical reason that enforce this suggestion and I don't think that this issue has something to do with that permission change. But I would not recommend changing this roles even when it should be technical possible.

**Comment by ReLater** [comment]
I made a test yesterday but with a 3.9.2 and not 3.9.1  where lots of ACL settings for Administrator and Manager and parent groups are changed. Nearly all core extensions and rights forbidden in back-end.

I can't reproduce the issue. All settings are the same afterwards.

But that Joomla installation is very minimalistic. Just Akeeba Backup, EasyJoomlaBackup, JCE.

**Comment by team187** [comment]
It must be then some previous update from 3.8.

I will try to get back with more details.

On all sites Akeeba backup, K2, rsfirewall, rsform, and unite nivo slider. I'm almost sure they couldn't affect the ACL configuration.

Thanks for the current advices and help.

**Comment by ghost** [comment]
closed as comment above. It can always reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23987">issues.joomla.org/tracker/joomla-cms/23987</a>.</sub>
