### ISSUE TITLE
[3.9] When using Joomla toolbar in frontend list view, clicking on edit, publish, unpublish, trash buttons reloads the page, when we click on OK from "Please first make a selection from the list." alert

### ISSUE THREAD

**Issue by vaivk369** [joomla/joomla-cms#23980]
### Steps to reproduce the issue
I have used following code, to display Joomla toolbar on my list view in frontend.

JLoader::register('JToolBarHelper', JPATH_ADMINISTRATOR . '/includes/toolbar.php');

JToolBarHelper::editList();
JToolBarHelper::publishList();
JToolBarHelper::unpublishList();
JToolBarHelper::trash();

### Expected result

When I do not make any selection and hit any of the button, I get alert with message "Please first make a selection from the list." . Clicking OK from this alert, should just close the alert window without reloading the page

### Actual result
Clicking OK from this alert, reloading the page

### System information (as much as possible)
I have set protostar - Default as my default template and tested this on mozilla.

**Comment by ghost** [comment]
@infograf768 can you please comment?

**Comment by ghost** [comment]
@HLeithner can you please comment as Release Lead 3.9?

**Comment by HLeithner** [comment]
seams to be a problem with the frontend template and javascript joomla uses for frontend editing.
which template do you use?

**Comment by ghost** [comment]
Closed due the lack of response. Please reopen if needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23980">issues.joomla.org/tracker/joomla-cms/23980</a>.</sub>
