### ISSUE TITLE
[4.0] Save and close button not working

### ISSUE THREAD

**Issue by puneeth-chanda** [joomla/joomla-cms#23998]
### Steps to reproduce the issue
go to http://localhost/joomla-cms/administrator/index.php?option=com_menus&view=item&client_id=0&layout=edit&id=102
and click edit.

### Expected result
a popup appears where save and close button works

### Actual result
Save and close button not working
![screenshot from 2019-02-24 12-50-11](https://user-images.githubusercontent.com/43813460/53296323-31b5db00-3833-11e9-9ad3-f7bc1467f91a.png)

### System information (as much as possible)
chrome
mint 19

**Comment by infograf768** [comment]
Known issue with all modals. This needs to be solved globally.

**Comment by puneeth-chanda** [comment]
Are anyone working on it??

**Comment by infograf768** [comment]
@dgrammatiko , normally.

**Comment by dgrammatiko** [comment]
@infograf768 somebody else volunteered to resurrect this PR: https://github.com/joomla/joomla-cms/pull/20788

**Comment by Quy** [comment]
Duplicate #23260 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23998">issues.joomla.org/tracker/joomla-cms/23998</a>.</sub>
