### ISSUE TITLE
Error in router.php and view.feed.php

### ISSUE THREAD

**Issue by wlh1950** [joomla/joomla-cms#23999]
### Steps to reproduce the issue

The error.log file on my hosts server shows these errors:

Undefined index: id in /joomla/components/com_tags/router.php on line 84

Invalid argument supplied for foreach() in /joomla/components/com_tags/views/tag/view.feed.php on line 35

### System information (as much as possible)

Joomla 3.9.3

**Comment by Quy** [comment]
Please test PR #23543<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23999">issues.joomla.org/tracker/joomla-cms/23999</a>.</sub>
