### ISSUE TITLE
[4.0] Missing tabs

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/joomla-cms#23994]
### Steps to reproduce the issue
1. Log in to the Backend
2. Select in admin menu: Menus > All Menu  Items > a menu item of the Single Article or Blog Category type.
3. Activate the Edit (or New) button.
4. In the modal window, change the current Content (or Category) tab to Option (or other) tab.
5. Leave the modal window by clicking Close 
6. Repeat the Edit (or New) button.
### Expected result
In the modal window there should be a tab interface 
![tabs1](https://user-images.githubusercontent.com/29527200/53288442-51dc9000-3788-11e9-8254-d2f5c244255b.png)

### Actual result
Missing tabs
![tabs2](https://user-images.githubusercontent.com/29527200/53288444-5739da80-3788-11e9-8314-582c93b859aa.png)

### System information (as much as possible)
* Windows 10,
* Chrome 72.0.3626.81, Firefox/65.0
* Apache 2.0 server (online)
### Additional comments
Error in Chrome console:
![error](https://user-images.githubusercontent.com/29527200/53288509-2ad28e00-3789-11e9-98f7-f1e47786ba3b.png)
Error in Firefox console:
![errors2](https://user-images.githubusercontent.com/29527200/53288512-3756e680-3789-11e9-89d3-78d1ac373b2f.png)

@dgrammatiko

**Comment by dgrammatiko** [comment]
@zwiastunsw it's a known problem not related to tabs but the modal-fields which is totally broken

**Comment by zwiastunsw** [comment]
I understand. Is there anyone working on that?

**Comment by ghost** [comment]
> Is there anyone working on that?

@wilsonge do you know as Release Lead 4?

**Comment by wilsonge** [comment]
Nope. As far as I can tell it's a bug in the tabs custom element. At least for me this patch worked. https://github.com/joomla-projects/custom-elements/pull/115 . As far as I can tell the tabs custom element breaks if it's inside a parents tabs element. But it can't travel outside the iframe to actually find it.

**Comment by brianteeman** [comment]
I can not replicate this. Probably fixed elsewhere. If someone else can confirm then it can be closed

**Comment by wilsonge** [comment]
I merged my own patch above I linked to in the tabs custom element. I can’t vouch for the code quality. But seems to have fixed the issue

**Comment by ghost** [comment]
Closed as commented above. It can always reopened if needed.
