### ISSUE TITLE
Template Morph do not set as default

### ISSUE THREAD

**Issue by nblancodl** [joomla/joomla-cms#24005]
### Steps to reproduce the issue

Hello, I have install the Morph template in my Joomla administrator but when I set it as default it doesn't update to this template, it remains with the past that I had installed. I need to set as default the Morph template for my web page.

My name is Natalia Blanco, my email is [nblancodl@gmail.com](mailto:nblancodl@gmail.com) and my domain is compgenioss.com

Thank you, I will pending to your answer.

**Comment by Quy** [comment]
Please ask support questions in [Joomla Forum](https://forum.joomla.org/).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24005">issues.joomla.org/tracker/joomla-cms/24005</a>.</sub>
