### ISSUE TITLE
Required Custom User Fields Does not Scroll to "Error" on submit

### ISSUE THREAD

**Issue by j2studio** [joomla/joomla-cms#24004]
### Steps to reproduce the issue
Create Additional User Fields
Make Field Required
On front end, skip required field and try to submit

### Expected result
Page to scroll to error indicating that required field is missed

### Actual result
Page does not move and user dones't know why

### System information (as much as possible)
Joomla 3.9.3
YooTHeme Pro 1.18.10
Safari or Chrome on Mac

### Additional comments
I also tried this on a generic installation of Joomla using the givcen template with same result

**Comment by brianteeman** [comment]
Joomla does not currently support inline error messages

**Comment by j2studio** [comment]
Ok thanks, Brian.
