### ISSUE TITLE
[4.0] Modules drag and drop ordering broken

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#24008]
### Steps to reproduce the issue
Make sure you have a number of modules set to the display in the same position.
Filter by this position in the Module Manager.
If a multilingual site, also filter by Language
Drag and drop is totally unreliable although the modules are moved OK in the manager.

The only way to get for example a specific module to display on top on the position is to not NOT FILTER the manager at all and then use drag and drop, or use the Ordering field of the module itself.

**Comment by bahl24** [comment]
@infograf768 Drag and drop is not working in other places also such as article manager

**Comment by dgrammatiko** [comment]
@infograf768 that might be a bug and probably the cause is that the script is reading some attribute to get information if the list has nested elements or not (that's from the top of my head). So in reality the patch should be quite easy: in the filters script we should take care of the form or the table (wherever the nested attribute is set and make sure that the value reflects the filtered list.

Plain English: by default most lists can be nested. If you filter on a category or whatever then probably you loose the nested part but the script still behaves as if the list was still nested...

Should be easy to patch if anyone follows the logic explained above

**Comment by infograf768** [comment]
> Should be easy to patch if anyone follows the logic explained above

Just remain to find the "anyone"...

**Comment by puneeth-chanda** [comment]
on it.

**Comment by puneeth-chanda** [comment]
it is working when we sort it by order, should I make it independent of this thing.

**Comment by infograf768** [comment]
It is not working when filtering.

**Comment by puneeth-chanda** [comment]
@infograf768  is it for sure that it is necessary to make drag and drop available for all I mean even without filtering. IMHO it might be done for some reason I think.

**Comment by infograf768** [comment]
it is working for all and also when filtering in 3.x.
People may use few positions and few modules. therefore it is useful for them

**Comment by Bakual** [comment]
For frontend modules, ordering works fine for me.
For backend modules, ordering is broken both with drag and drop and when trying to set the ordering in the module settings. I only have the option "None" there.
![image](https://user-images.githubusercontent.com/1018684/54926100-efee8200-4f0f-11e9-9960-b0579d47fad5.png)

**Comment by ghost** [comment]
closed as having Pull Request #24358

**Comment by Bakual** [comment]
My PR solves another issue. While also ordering the drag and drop afaik uses a different JavaScript script (draggable.js).

**Comment by infograf768** [comment]
I am reopening this.
For site modules:
As I said, when filtered, for example by position, the ordering is not respected when it has been done via drag and drop.

Manager
<img width="1256" alt="Screen Shot 2019-03-28 at 07 54 40" src="https://user-images.githubusercontent.com/869724/55136500-da0ad800-512e-11e9-9f97-9d681ed4ed78.png">


Frontend
<img width="434" alt="Screen Shot 2019-03-28 at 07 51 39" src="https://user-images.githubusercontent.com/869724/55136299-58b34580-512e-11e9-9a2f-42d87a28464d.png">

It should be:
Switcher
Main Menu
Login form

Editing one of these modules and looking at the Ordering field, we can see it is wrong:
<img width="318" alt="Screen Shot 2019-03-28 at 07 57 13" src="https://user-images.githubusercontent.com/869724/55136585-1fc7a080-512f-11e9-8012-d37125483366.png">

**Comment by ghost** [comment]
@infograf768 @Bakual Sorry for closing.

**Comment by regularlabs** [comment]
Still not fixed!

**Comment by gostn** [comment]
Request to remove the question mark in the title as drag ´n´ drop-ordering ist broken if a position is filtered.

**Comment by HLeithner** [comment]
Fixed in #31480
