### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by magskate** [joomla/joomla-cms#24015]
Hi,
our website is not working
westfieldvillage.co.uk

Error message:
Fatal error: Cannot use Joomla\String\String as String because 'String' is a special class name in /home/westfie3/public_html/libraries/vendor/joomla/registry/src/Format/Json.php on line 12

**Comment by HLeithner** [comment]
Sounds like you have an old Joomla Version and upgraded you PHP version.

**Comment by Quy** [comment]
Duplicate #8817<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24015">issues.joomla.org/tracker/joomla-cms/24015</a>.</sub>
