### ISSUE TITLE
Media Manager Video Uploads

### ISSUE THREAD

**Issue by Karl-Goddard** [joomla/joomla-cms#24027]
### Steps to reproduce the issue
Add mp4 to legal extensions and MIME types and try uploading a video using Media Manager. The video I am trying to upload is smaller than my PHP upload size limit and the joomla max size limit in global config. Note that this issue doesn't occur if I set restrict uploads to "NO".

### Expected result
Successful upload.

### Actual result
Error: Not a valid image

### System information (as much as possible)
Joomla v3.9.2
PHP upload size is 25Mb
PHP v5.6.36
Zend engine v2.6.0
CentOS Linux 7 (core)

This is the video I am trying to upload:
[big_buck_bunny.mp4.tar.gz](https://github.com/joomla/joomla-cms/files/2907584/big_buck_bunny.mp4.tar.gz)

### Additional comments
I am Super User
Joomla's System Information -> File Permission are all set to writable
Both the Image path and the File path are set to images.
Other media types such as images and documents upload with out errors.

**Comment by ghost** [comment]
@infograf768 can you please comment?

**Comment by SharkyKZ** [comment]
I can't reproduce this issue. The file was uploaded successfully. But see if #20968 helps.

**Comment by ghost** [comment]
closed based on Comment above. 

@SharkyKZ thanks for taking Time to take a Look.

**Comment by SharkyKZ** [comment]
@franz-wohlkoenig don't close this yet. The linked PR is closed so the issue still needs to be solved, if someone else can reproduce it.

**Comment by ghost** [comment]
@SharkyKZ looks like not so.

**Comment by Quy** [comment]
Please test PR #25351<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24027">issues.joomla.org/tracker/joomla-cms/24027</a>.</sub>
