### ISSUE TITLE
[3.9.3] Banner Module cached; Over-ride edits to fail to update IRL

### ISSUE THREAD

**Issue by isdaft** [joomla/joomla-cms#24029]
### Steps to reproduce the issue
create an override for a banner 
create associated module and link to an area dictated in .xml
make edits to over-ride php

### Expected result
any and all subsequent edits to the over-ride will be seen after the edit is made.

### Actual result
html produced from php over-ride SOMETIMES, will stay the same even though the over-ride php is supposed to show something different on the dom.

### System information (as much as possible)

PHP Built On | Linux *link* 3.12.18-clouder0 #28 SMP Thu Mar 8 11:53:03 EET 2018 x86_64
-- | --
Database Type | mysql
Database Version | 5.6.36-82.1-log
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.0.33
Web Server | Apache/2.4.29 (Unix) mod_hive/6.6 OpenSSL/1.0.1e-fips mod_fastcgi/2.4.6
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.9.3 Stable [ Amani ] 12-February-2019 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0

### Additional comments
In order to fix, i have had to delete the module and re-recreate a new one so that the over-ride gets printed correctly. 
Feels like a caching issue, or that sql is not properly updating? The issue does not occur often, and occurs less on newly created modules / with over-rides that are updated frequently.

I use firefox dev edition with zero caching

**Comment by ghost** [comment]
@infograf768 can you please comment?

**Comment by ghost** [comment]
@HLeithner can you please comment as Release Lead 3.9?

**Comment by HLeithner** [comment]
Sounds like a caching problem in an php opcache module, do you use opcache or apc or any other opcaching module for php?
If yes, try to disable it.

**Comment by isdaft** [comment]
Thank you. Will comment back if the issue re-emerges.
