### ISSUE TITLE
PHP Notice:  Undefined index: id in components/com_tags/router.php

### ISSUE THREAD

**Issue by dioubernardo** [joomla/joomla-cms#24039]
PHP Notice:  Undefined index: id in /storage/htdocs/joomla/furg/components/com_tags/router.php on line 79

PHP Notice:  Undefined index: id in /storage/htdocs/joomla/furg/components/com_tags/router.php on line 84

### System information (as much as possible)
PHP Version 7.3.2-3
Ubuntu 14.04.1
Joomla! 3.9.3 Stable

**Comment by ReLater** [comment]
Related? https://github.com/joomla/joomla-cms/issues/23999

**Comment by Quy** [comment]
@dioubernardo Can you provide steps on how to reproduce it?

**Comment by dioubernardo** [comment]
Install default Joomla and read apache error log after many access ;)

**Comment by Quy** [comment]
Which link(s)? The log should show the referring links/pages.

**Comment by dioubernardo** [comment]
In many links

[Thu Feb 28 06:29:35.041084 2019] [php7:notice] [pid 25715] [client 200.19.255.54:43925] PHP Notice:  Undefined index: id in /storage/htdocs/joomla/furg/components/com_tags/router.php on line 84, referer: https://furg.br/en/component/tags/tag/nucleo-de-traducao

[Thu Feb 28 06:30:51.871571 2019] [php7:notice] [pid 25721] [client 200.19.255.54:43231] PHP Notice:  Undefined index: id in /storage/htdocs/joomla/furg/components/com_tags/router.php on line 79, referer: https://furg.br/en/component/tags/tag/nucli-isf

[Thu Feb 28 06:25:54.161090 2019] [php7:notice] [pid 25478] [client 200.19.255.54:52599] PHP Notice:  Undefined index: id in /storage/htdocs/joomla/furg/components/com_tags/router.php on line 79, referer: https://furg.br/en/component/tags/tag/nucleo-de-extensao?format=feed&type=rss

[Thu Feb 28 06:25:54.161480 2019] [php7:notice] [pid 25478] [client 200.19.255.54:52599] PHP Notice:  Undefined index: id in /storage/htdocs/joomla/furg/components/com_tags/router.php on line 84, referer: https://furg.br/en/component/tags/tag/nucleo-de-extensao?format=feed&type=rss

[Thu Feb 28 06:24:57.160699 2019] [php7:notice] [pid 25334] [client 200.19.255.54:59081] PHP Notice:  Undefined index: id in /storage/htdocs/joomla/furg/components/com_tags/router.php on line 79, referer: https://furg.br/en/component/tags/tag/novos-servidores?format=feed&type=atom

[Thu Feb 28 06:24:57.160773 2019] [php7:notice] [pid 25334] [client 200.19.255.54:59081] PHP Notice:  Undefined index: id in /storage/htdocs/joomla/furg/components/com_tags/router.php on line 84, referer: https://furg.br/en/component/tags/tag/novos-servidores?format=feed&type=atom

**Comment by Quy** [comment]
Please test PR #24051<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24039">issues.joomla.org/tracker/joomla-cms/24039</a>.</sub>
