### ISSUE TITLE
[4.0] Components menu

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#24032]
As Redirects and Post Installation Messages are now correctly in the system control panel they should be removed from the actual components menu.

**Comment by brianteeman** [comment]
and joomla update

**Comment by bahl24** [comment]
On it.

**Comment by bembelimen** [comment]
see https://github.com/joomla/joomla-cms/pull/23760 for first try, I'll update it over the weekend

**Comment by brianteeman** [comment]
Sorry @bembelimen I completely missed that. Great minds think alike
