### ISSUE TITLE
Untracked strings in help page

### ISSUE THREAD

**Issue by puneeth-chanda** [joomla/joomla-cms#24055]
### What needs to be fixed
some untracked strings must be removed
![screenshot from 2019-03-01 21-10-34](https://user-images.githubusercontent.com/43813460/53648674-8065d980-3c66-11e9-847d-22085cd5cd32.png)

### Why this should be fixed
Seems awkard

**Comment by brianteeman** [comment]
Duplicate report

**Comment by puneeth-chanda** [comment]
is the issue already present

**Comment by Quy** [comment]
Duplicate #23630. Please test PR #23839.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24055">issues.joomla.org/tracker/joomla-cms/24055</a>.</sub>

**Comment by vijay9908** [comment]
> is the issue already present

yup!!
