### ISSUE TITLE
Debug plugin errors on php 7.3

### ISSUE THREAD

**Issue by billtomczak** [joomla/joomla-cms#24050]
### Steps to reproduce the issue
* Install Joomla 4
* set error reporting to at least 'Simple'

### Expected result
no errors

### Actual result
The following errors are reported on admin pages
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/plugins/system/debug/debug.php on line 590

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/plugins/system/debug/debug.php on line 611

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/html/plugins/system/debug/debug.php on line 617

### System information (as much as possible)
Linux df9945feec8c 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64
MySQL 5.7.25
php 7.3.2 apache2handler
Apache/2.4.25 (Debian)
Joomla! 4.0.0-alpha5 Alpha [ Amani ] 4-November-2018 23:23 GMT
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36

**Comment by SharkyKZ** [comment]
Already fixed, see #23253.

**Comment by billtomczak** [comment]
My Apologies - I did a search and didn't find anything.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24050">issues.joomla.org/tracker/joomla-cms/24050</a>.</sub>
