### ISSUE TITLE
[4.0] Table Options opens when clicking in main area

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#24067]
### Steps to reproduce the issue
In the Articles List View, ant the Table Options is used to selected Articles in a Category, which produces the expected results.

However, when you click in the main area of the Article List, the Table Options open again, this time in wide screen format, on top of the list, making the screen unusable thereafter.

### Expected result

The Table Options should not re-open in wide format over the top of the Article List when you click in the main window area.  Might be helpful to have a Close "X" in the corner to close the Table Options block.

**Comment by brianteeman** [comment]
The options are open to show that you have a filter set.

**Comment by brianteeman** [comment]
Can you post a screenshot of what you mean by "unusable"

**Comment by ReLater** [comment]
I'm not absolutely sure but I think that this is fixed already in current Joomla 4 (nightly builds).
https://developer.joomla.org/nightly-builds.html

**Comment by brianteeman** [comment]
Grrh Thats why it asks for the System information. How is anyone supposed to know it was Joomla 4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24067">issues.joomla.org/tracker/joomla-cms/24067</a>.</sub>

**Comment by ghost** [comment]
@200MPHMEDIA please append "[4.0]" in front of the Title.

**Comment by 200MPHMEDIA** [comment]
Joomla! 4alpha7 is where it is showing up.  Isn't this a "4.0" post?  If so, should not be necessary to identify it as a "4.0" problem.  If selecting a filter, and it functions, then going to the main content area and clicking on the screen, and the filter opens screen-width on top of the content area, hiding the resulting list, is a normal process - someone needs to re-think it.  And, why no "X" option to close the Table Options when selected.  This is very ratty functioning on this section of admin.

**Comment by 200MPHMEDIA** [comment]
Installed the nightly build and the issue has been fixed. So someone saw the problem and fixed it, instead of defending why it functioned like that.  Thanks for the fix.

**Comment by ghost** [comment]
> Joomla! 4alpha7 is where it is showing up. Isn't this a "4.0" post?

Its about see in Title that a 4.0-Issue is reported.
