### ISSUE TITLE
[4.0] Enable Debug mode is not working

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#24070]
### Steps to reproduce the issue

Enable 
![global configuration rsfd administration](https://user-images.githubusercontent.com/9974686/53694370-3556de00-3dae-11e9-99ae-aafafb3e6aa9.png)

### Expected result

I see debug information on the end of the page.

### Actual result

I do not see debug information.

![home](https://user-images.githubusercontent.com/9974686/53694372-3556de00-3dae-11e9-9706-733ded022fd8.png)

**Comment by ghost** [comment]
@infograf768 can you please comment?

**Comment by infograf768** [comment]
One has to click on the bottom left icon to see debug (lang or system or both).
<img width="229" alt="screen shot 2019-03-03 at 12 23 11" src="https://user-images.githubusercontent.com/869724/53694436-2b81aa80-3daf-11e9-9d48-36d090da61d7.png">

<img width="384" alt="screen shot 2019-03-03 at 12 21 40" src="https://user-images.githubusercontent.com/869724/53694424-f2e1d100-3dae-11e9-9192-232ab5ed76a0.png">

**Comment by infograf768** [comment]
Closing as not a bug.

**Comment by ghost** [comment]
thanks @infograf768
