### ISSUE TITLE
Option setting for User Action Logs isn't working

### ISSUE THREAD

**Issue by fr56** [joomla/joomla-cms#24071]
### Steps to reproduce the issue

Joomla 3.9.3. Users, User Action Log, Options, Events to log. Uncheck the (new) box Check-in.

### Expected result
No events for check-in will be shown in the User Actions Log.

### Actual result
The events for check-in are shown.
"User x performed a check in to table #__content " every time an article, menu item or module is opened, saved or closed.

### System information (as much as possible)
Joomla 3.9.3, PHP 7.3.2

### Additional comments
Upgraded from J 3.9.2 to J 3.9.3. 

Another thing is that I really don't understand the purpose of this event. Because it never says which article / menu item / module it concerns.

**Comment by ghost** [comment]
@HLeithner can you please comment?

**Comment by HLeithner** [comment]
@zero-24 could you look at this?

**Comment by Quy** [comment]
@alikon

**Comment by alikon** [comment]
i'll look at it

**Comment by alikon** [comment]
please test #24086

for 

> Another thing is that I really don't understand the purpose of this event. Because it never says which article / menu item / module it concerns.

i'll dig it later cause is not a bug imho more an improvement

**Comment by ghost** [comment]
closed as having Pull Request #24086
