### ISSUE TITLE
[4.0] Toggle editor place change

### ISSUE THREAD

**Issue by puneeth-chanda** [joomla/joomla-cms#24076]
### What needs to be fixed
Toggle editor is presently below the text box If this is aside alias it would be nice 
![screenshot from 2019-03-03 22-41-22](https://user-images.githubusercontent.com/43813460/53698658-d624b800-3e05-11e9-9ebb-4dddd4bed520.png)

**Comment by C-Lodder** [comment]
Tagging @coolcat-creations and @rdeutz

**Comment by coolcat-creations** [comment]
Can anyone take care of this screen maybe? The Toggle (bottom right) could be ordered to top OFC
https://coolcat-creations.com/joomla/#/screens/267320995

**Comment by bahl24** [comment]
I can work on it. @coolcat-creations @C-Lodder 
What would be an acceptable position to put it, both on site as well as adminstrator side?

**Comment by infograf768** [comment]
@coolcat-creations 
I find it difficult to work on anything for the admin template when your proposed admin design is changing so drastically (at what I saw in https://coolcat-creations.com/joomla/#/screens/267320995 for various managers) vs what we have now.

**Comment by bahl24** [comment]
![screenshot from 2019-03-07 17-38-42](https://user-images.githubusercontent.com/36095178/53955792-e5567f00-40ff-11e9-81e6-0ddcd7223aed.png)
How about this?

**Comment by coolcat-creations** [comment]
Just like in my Screen but at the top?

**Comment by bahl24** [comment]
> Just like in my Screen but at the top?

Yes, that too looks fine

**Comment by alikon** [comment]
related to the old template, open a new issue if needed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24076">issues.joomla.org/tracker/joomla-cms/24076</a>.</sub>

**Comment by infograf768** [comment]
Please test
https://github.com/joomla/joomla-cms/pull/26102
