### ISSUE TITLE
[4.0] SmartSearch Indexing debug js errors

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#24084]
### Steps to reproduce the issue
Click on Index in a multilingual site with 4 languages

EDIT: modified issue after doing clean install
### Actual result

**When system debug is on**
```
ReferenceError: jQuery is not defined[Learn More] debugbar.js:4:5
TypeError: PhpDebugBar.utils is undefined[Learn More] widgets.js:14:9
TypeError: PhpDebugBar.Widget is undefined[Learn More] openhandler.js:13:5
TypeError: PhpDebugBar.utils is undefined[Learn More] widget.min.js:1:18
TypeError: PhpDebugBar.utils is undefined[Learn More] widget.min.js:1:18
TypeError: PhpDebugBar.DebugBar is not a constructor[Learn More] index.php:70:19 
```
@Hackwar

**Comment by Hackwar** [comment]
I can't replicate the issue. We lately merged a PR that contains database changes which would result in this error. Please make sure that your #__finder_taxonomy table contains lft, rgt and language columns.

**Comment by infograf768** [comment]
It is a clean install.
I modified the issue (maybe while you were responding) and the table is OK.
The issue in fact concerns the errors for debug js files when Indexing.

**Comment by infograf768** [comment]
Modified issue to
"SmartSearch Indexing debug js errors"

**Comment by Hackwar** [comment]
In that case I will ask @elkuku to have a look here.

**Comment by Fedik** [comment]
@infograf768 I have a suspicion that this #23637 should fix the bug,  but not sure

**Comment by infograf768** [comment]
@Fedik 
Correct! Closing as #23637 solves the issue indeed.
