### ISSUE TITLE
JOOMLA installed on POSTGRES => problem with users email (can be duplicated)

### ISSUE THREAD

**Issue by mdaoudi123** [joomla/joomla-cms#24095]
I installed an instance of JOOMLA on a POSTGRES database and I noticed that the email address of the users is case sensitive.
The problem is that you can create two users with the same address.
Example:
user 1: test@test.fr
User 2: Test@test.fr

Normally the verification of the email address must be insensitive box.
Indeed I noticed that in the methods of checking the email addresses in the core of joomla, do not handle this case.

To solve the problem, waiting for a patch, I had to change the type of the mail fields in the table #__users from VARCHAR to CITEXT.

Could you make this fix in the next version / patch of Joomla.

Informations:
----------------
Joomla version: 3.9.2 (installed on Postgres) and not on Mysql
Postgres version: 10
PHP version: 7.2

thank you in advance

**Comment by ghost** [comment]
Please give "System information (as much as possible)"

**Comment by mdaoudi123** [comment]
Hi,
First thanks for responding.
Joomla version 3.9.2 (installed on Postgres) and not on Mysql
Postgres version 10
PHP version 7.2

that's all

Need more informations?

**Comment by ghost** [comment]
as 3.9: @HLeithner can you please comment?

**Comment by ghost** [comment]
@mdaoudi123 can you please append the Information in first Comment so they don't have to be searched by Volunteers?

**Comment by HLeithner** [comment]
@alikon can you look at this?

**Comment by mdaoudi123** [comment]
Thanks

**Comment by alikon** [comment]
i don't think we can use **CITEXT** on the 3.x branch cause of [Unsupported versions: 9.3 / 9.2 / 9.1 / 9.0 / 8.4](https://www.postgresql.org/docs/current/citext.html)
and joomla 3.x still [support 8.3.18](https://downloads.joomla.org/technical-requirements) as minimum requirement we should use something like
```sql 
SELECT id FROM #__users WHERE lower(email) = LOWER(email);
```
and for performance  maybe change the index too
```sql 
ALTER TABLE #__users DROP INDEX email;
CREATE INDEX email ON #__users (LOWER(email));
```

**Comment by mdaoudi123** [comment]
**Hello**,
Thanks for responding.

In the begining i tried to use the "**LOWER**" function to compare the email, but i found a lot of function that use this comparaison. So i was obliged to change all the function into many files and I was afraid to forget others. so i choose this simpliest solution: "**CITEXT**".

I think that we have to create a new patch where we the function "**LOWER**" will be used for every email comparaison. do you agree with me @alikon ?

**regards**

**Comment by alikon** [comment]
@mdaoudi123 yes, are you going to submit a pr ?

**Comment by mdaoudi123** [comment]
Hello,

I dont know how to do it. 
Could you please tell me how? or do it in my place?

Thanks
@alikon

**Comment by alikon** [comment]
ok then please test this draft pr #24117

**Comment by ghost** [comment]
closed as having Pull Request #24117

**Comment by mdaoudi123** [comment]
Thanks a lot for your help.

But There is also another file where exists a email comparaison:
- components/com_users/models/reset.php => function **processResetConfirm**
- components/com_users/models/remind.php => function **processRemindRequest**
- ...
and into other files..... (search for "**$db->quoteName('email')**")

Could you please add the correction to thoses files @alikon

**Comment by alikon** [comment]
yes for sure, i was in hurry yesterday and made a draft pr only
please @mdaoudi123 comment on #24117

**Comment by mdaoudi123** [comment]
already done. thanks for responding
