### ISSUE TITLE
[4.0] Blog sample data plugin workflow state issue

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#24093]
### Steps to reproduce the issue
Clean Joomla install.
In CPanel install Blog Sample Data

### Expected result
All articles created are published

### Actual result
All articles are unpublished.

@bembelimen 
I guess that as Unpublished is default Joomla workflow, it is to be expected. BUT when I add `$article['state'] = 1;` it does not work either.

Note: it works fine for the multilingual sample data as we directly save in db without using the model.

**Comment by puneeth-chanda** [comment]
Issue confirmed.
working on it.

**Comment by Quy** [comment]
Please test PR #24101<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24093">issues.joomla.org/tracker/joomla-cms/24093</a>.</sub>
