### ISSUE TITLE
[4.0] Redirect after edit to origin

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#24109]
### What needs to be fixed
When something is edited from a shortcut link, for example like here: https://github.com/joomla/joomla-cms/pull/23934 the user should be redirected to the origin he came from

If you edit the module and close it, you end up in the module manager. It would be good to implement a refererlink on such icons so when you close something you get back to where you came from. 

@infograf768 tagging you because of your + vote ;)

**Comment by infograf768** [comment]
This change works fine here for https://github.com/joomla/joomla-cms/pull/23934

```
diff --git a/administrator/components/com_modules/tmpl/module/edit.php b/administrator/components/com_modules/tmpl/module/edit.php
index 6ed075f..8a076bb 100644
--- a/administrator/components/com_modules/tmpl/module/edit.php
+++ b/administrator/components/com_modules/tmpl/module/edit.php
@@ -15,4 +15,5 @@
 use Joomla\CMS\Layout\LayoutHelper;
 use Joomla\CMS\Router\Route;
+use Joomla\CMS\Uri\Uri;
 
 HTMLHelper::_('behavior.formvalidator');
@@ -198,4 +199,10 @@
 		<?php echo $this->form->getInput('module'); ?>
 		<?php echo $this->form->getInput('client_id'); ?>
+
+		<?php // Redirect to CPanel when the module has been edited from there. ?>
+		<?php $url = htmlspecialchars($_SERVER['HTTP_REFERER']); ?>
+		<?php if ($this->item->client_id == 1 && ($url == Uri::root() . 'administrator/index.php' || $url == Uri::root() . 'administrator/index.php?option=com_cpanel')) : ?>
+			<input type="hidden" name="return" value="<?php echo base64_encode('index.php?option=com_cpanel') ?>">
+		<?php endif; ?>
 	</div>
 </form>
```

I guess we also could use a code using session.
Not sure what is the best solution

**Comment by coolcat-creations** [comment]
Ok I guess after the edit is merged I or @C-Lodder can add this "fix" to the module or should this fix be done to all possible places? Then the places should be maybe listed.
I can think of - edit userprofile ... but which else?

**Comment by infograf768** [comment]
we must first decide if we should use that kind of code or not.

**Comment by infograf768** [comment]
after some discussion, that code is not the right way.
will test another and, if it works fine, will make pr

**Comment by infograf768** [comment]
I wait for @C-Lodder pr to be merged to propose the patch as the main change is in fact in the url in modules.php

**Comment by coolcat-creations** [comment]
Thank you :)

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/issues/24109 for the CPanel modules

**Comment by ghost** [comment]
@infograf768 #23934 to test.

**Comment by ghost** [comment]
closed as having Pull Request #23934

**Comment by infograf768** [comment]
@franz-wohlkoenig 
#23934 was merged and that is why I could make the new PR :)

I reopen this as it did not only concern the cpanel modules but eventually other places in core where the redirect would be nice to implement.

Please, all, state which precise places.

**Comment by infograf768** [comment]
@chmst 
Also proposed for Edit Account
https://github.com/joomla/joomla-cms/pull/24281

**Comment by brianteeman** [comment]
This should be closed. The original issue has been resolved as have lots of other similar "return to origin" issues. If there are any new links that need to "return to origin" then they should be in their own new issue/pr

**Comment by ghost** [comment]
closed as stated above.
