### ISSUE TITLE
[4.0] File system plugin Fatal Error

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#24102]
### Steps to reproduce the issue
Edit the File system plugin
`administrator/index.php?option=com_plugins&view=plugin&layout=edit&extension_id=483`

### Actual result
fatal error: Object of class stdClass could not be converted to string in ROOT/libraries/cms/html/select.php on line 647

**Comment by SharkyKZ** [comment]
Test PR #24103 please.

**Comment by infograf768** [comment]
Closing as https://github.com/joomla/joomla-cms/pull/24103 solves the issue.
Thanks.
