### ISSUE TITLE
[4.0] [WIP] Use namespaced classes

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#24108]
- [ ] JRegistry
- [x] JRegistryFormatIni
- [x] JRegistryFormatJson
- [x] JRegistryFormatPhp
- [x] JRegistryFormatXml
- [x] JStringInflector
- [x] JStringNormalise
- [x] JData
- [x] JDataSet
- [x] JDataDumpable
- [ ] JApplicationAdministrator
- [x] JApplicationHelper
- [ ] JApplicationBase
- [ ] JApplicationCli
- [ ] JApplicationCms
- [x] JApplicationDaemon
- [ ] JApplicationSite
- [ ] JApplicationWeb
- [x] JApplicationWebClient
- [x] JDaemon
- [ ] JCli
- [x] JWeb
- [x] JWebClient
- [ ] JModelAdmin
- [ ] JModelForm
- [ ] JModelItem
- [ ] JModelList
- [ ] JModelLegacy
- [x] JViewCategories
- [x] JViewCategory
- [x] JViewCategoryfeed
- [ ] JViewLegacy
- [x] JControllerAdmin
- [ ] JControllerLegacy
- [x] JControllerForm
- [ ] JTableInterface
- [ ] JTable
- [x] JTableNested
- [ ] JTableAsset
- [x] JTableExtension
- [ ] JTableLanguage
- [ ] JTableUpdate
- [x] JTableUpdatesite
- [x] JTableUser
- [x] JTableUsergroup
- [x] JTableViewlevel
- [x] JTableContenthistory
- [x] JTableContenttype
- [x] JTableCorecontent
- [x] JTableUcm
- [ ] JTableCategory
- [ ] JTableContent
- [ ] JTableMenu
- [ ] JTableMenuType
- [ ] JTableModule
- [ ] JAccess
- [x] JAccessRule
- [x] JAccessRules
- [x] JAccessExceptionNotallowed
- [x] JRule
- [x] JRules
- [ ] JHelp
- [x] JCaptcha
- [x] JLanguageAssociations
- [ ] JLanguage
- [x] JLanguageHelper
- [x] JLanguageStemmer
- [x] JLanguageMultilang
- [ ] JText
- [x] JLanguageTransliterate
- [x] JLanguageStemmerPorteren
- [ ] JComponentHelper
- [ ] JComponentRecord
- [x] JComponentExceptionMissing
- [x] JComponentRouterBase
- [x] JComponentRouterInterface
- [x] JComponentRouterLegacy
- [x] JComponentRouterView
- [x] JComponentRouterViewconfiguration
- [x] JComponentRouterRulesMenu
- [x] JComponentRouterRulesNomenu
- [x] JComponentRouterRulesInterface
- [x] JComponentRouterRulesStandard
- [ ] JEditor
- [ ] JErrorPage
- [ ] JAuthenticationHelper
- [ ] JHelper
- [ ] JHelperContent
- [x] JHelperContenthistory
- [x] JLibraryHelper
- [x] JHelperMedia
- [ ] JModuleHelper
- [ ] JHelperRoute
- [x] JSearchHelper
- [ ] JHelperTags
- [ ] JHelperUsergroups
- [ ] JLayoutBase
- [ ] JLayoutFile
- [ ] JLayoutHelper
- [ ] JLayout
- [x] JResponseJson
- [ ] JPlugin
- [ ] JPluginHelper
- [ ] JMenu
- [x] JMenuAdministrator
- [x] JMenuItem
- [x] JMenuSite
- [ ] JPagination
- [x] JPaginationObject
- [ ] JPathway
- [ ] JPathwaySite
- [x] JSchemaChangeitem
- [x] JSchemaChangeset
- [x] JSchemaChangeitemMysql
- [x] JSchemaChangeitemPostgresql
- [x] JSchemaChangeitemSqlsrv
- [x] JUcm
- [x] JUcmBase
- [ ] JUcmContent
- [ ] JUcmType
- [ ] JToolbar
- [ ] JToolbarButton
- [x] JToolbarButtonConfirm
- [x] JToolbarButtonCustom
- [x] JToolbarButtonHelp
- [x] JToolbarButtonLink
- [x] JToolbarButtonPopup
- [x] JToolbarButtonSeparator
- [x] JToolbarButtonStandard
- [ ] JToolbarHelper
- [x] JButton
- [ ] JVersion
- [ ] JAuthentication
- [ ] JAuthenticationResponse
- [x] JBrowser
- [x] JAssociationExtensionInterface
- [x] JAssociationExtensionHelper
- [ ] JDocument
- [ ] JDocumentError
- [x] JDocumentFeed
- [ ] JDocumentHtml
- [x] JDocumentImage
- [x] JDocumentJson
- [x] JDocumentOpensearch
- [x] JDocumentRaw
- [ ] JDocumentRenderer
- [x] JDocumentXml
- [x] JDocumentRendererFeedAtom
- [x] JDocumentRendererFeedRss
- [x] JDocumentRendererHtmlComponent
- [x] JDocumentRendererHtmlHead
- [x] JDocumentRendererHtmlMessage
- [x] JDocumentRendererHtmlModule
- [x] JDocumentRendererHtmlModules
- [x] JDocumentRendererAtom
- [x] JDocumentRendererRSS
- [x] JDocumentRendererComponent
- [x] JDocumentRendererHead
- [x] JDocumentRendererMessage
- [x] JDocumentRendererModule
- [x] JDocumentRendererModules
- [x] JFeedEnclosure
- [x] JFeedImage
- [ ] JFeedItem
- [x] JOpenSearchImage
- [x] JOpenSearchUrl
- [ ] JFilterInput
- [ ] JFilterOutput
- [ ] JHttp
- [ ] JHttpFactory
- [ ] JHttpResponse
- [ ] JHttpTransport
- [x] JHttpTransportCurl
- [x] JHttpTransportSocket
- [x] JHttpTransportStream
- [ ] JInstaller
- [ ] JInstallerAdapter
- [ ] JInstallerExtension
- [ ] JExtension
- [ ] JInstallerHelper
- [ ] JInstallerScript
- [ ] JInstallerManifest
- [ ] JInstallerAdapterComponent
- [ ] JInstallerComponent
- [ ] JInstallerAdapterFile
- [ ] JInstallerFile
- [ ] JInstallerAdapterLanguage
- [ ] JInstallerLanguage
- [ ] JInstallerAdapterLibrary
- [ ] JInstallerLibrary
- [ ] JInstallerAdapterModule
- [ ] JInstallerModule
- [ ] JInstallerAdapterPackage
- [ ] JInstallerPackage
- [ ] JInstallerAdapterPlugin
- [ ] JInstallerPlugin
- [ ] JInstallerAdapterTemplate
- [ ] JInstallerTemplate
- [ ] JInstallerManifestLibrary
- [ ] JInstallerManifestPackage
- [ ] JRouterAdministrator
- [ ] JRoute
- [ ] JRouter
- [ ] JRouterSite
- [ ] JCategories
- [ ] JCategoryNode
- [ ] JDate
- [ ] JLog
- [ ] JLogEntry
- [x] JLogLogger
- [ ] JLogger
- [ ] JLogLoggerCallback
- [x] JLogLoggerDatabase
- [x] JLogLoggerEcho
- [x] JLogLoggerFormattedtext
- [x] JLogLoggerMessagequeue
- [x] JLogLoggerSyslog
- [x] JLogLoggerW3c
- [ ] JProfiler
- [ ] JUri
- [x] JCache
- [ ] JCacheController
- [ ] JCacheStorage
- [ ] JCacheControllerCallback
- [x] JCacheControllerOutput
- [x] JCacheControllerPage
- [ ] JCacheControllerView
- [x] JCacheStorageApcu
- [x] JCacheStorageHelper
- [x] JCacheStorageFile
- [x] JCacheStorageMemcached
- [x] JCacheStorageRedis
- [x] JCacheStorageWincache
- [ ] JCacheException
- [ ] JCacheExceptionConnecting
- [x] JCacheExceptionUnsupported
- [ ] JSession
- [ ] JUser
- [ ] JUserHelper
- [ ] JForm
- [ ] JFormField
- [ ] JFormHelper
- [ ] JFormRule
- [ ] JFormFieldAccessLevel
- [x] JFormFieldAliastag
- [x] JFormFieldAuthor
- [x] JFormFieldCacheHandler
- [x] JFormFieldCalendar
- [x] JFormFieldCaptcha
- [x] JFormFieldCategory
- [x] JFormFieldCheckbox
- [x] JFormFieldCheckboxes
- [x] JFormFieldChromeStyle
- [x] JFormFieldColor
- [x] JFormFieldCombo
- [x] JFormFieldComponentlayout
- [x] JFormFieldComponents
- [x] JFormFieldContenthistory
- [ ] JFormFieldContentlanguage
- [x] JFormFieldContenttype
- [ ] JFormFieldDatabaseConnection
- [x] JFormFieldEditor
- [x] JFormFieldEMail
- [x] JFormFieldFile
- [x] JFormFieldFileList
- [x] JFormFieldFolderList
- [x] JFormFieldFrontend_Language
- [x] JFormFieldGroupedList
- [x] JFormFieldHeadertag
- [x] JFormFieldHelpsite
- [x] JFormFieldHidden
- [x] JFormFieldImageList
- [x] JFormFieldInteger
- [ ] JFormFieldLanguage
- [x] JFormFieldLastvisitDateRange
- [x] JFormFieldLimitbox
- [ ] JFormFieldList
- [ ] JFormFieldMedia
- [x] JFormFieldMenu
- [x] JFormFieldMenuitem
- [x] JFormFieldMeter
- [x] JFormFieldModulelayout
- [x] JFormFieldModuleOrder
- [x] JFormFieldModulePosition
- [x] JFormFieldModuletag
- [x] JFormFieldNote
- [ ] JFormFieldNumber
- [ ] JFormFieldOrdering
- [x] JFormFieldPassword
- [x] JFormFieldPlugins
- [x] JFormFieldPlugin_Status
- [ ] JFormFieldPredefinedList
- [ ] JFormFieldRadio
- [x] JFormFieldRange
- [x] JFormFieldRedirect_Status
- [x] JFormFieldRegistrationDateRange
- [x] JFormFieldRules
- [x] JFormFieldSessionHandler
- [x] JFormFieldSpacer
- [x] JFormFieldSQL
- [x] JFormFieldStatus
- [x] JFormFieldSubform
- [x] JFormFieldTag
- [x] JFormFieldTel
- [x] JFormFieldTemplatestyle
- [ ] JFormFieldText
- [ ] JFormFieldTextarea
- [x] JFormFieldTimezone
- [ ] JFormFieldUrl
- [x] JFormFieldUserActive
- [x] JFormFieldUserGroupList
- [x] JFormFieldUserState
- [ ] JFormFieldUser
- [x] JFormRuleBoolean
- [x] JFormRuleCalendar
- [x] JFormRuleCaptcha
- [x] JFormRuleColor
- [ ] JFormRuleEmail
- [ ] JFormRuleEquals
- [x] JFormRuleNotequals
- [x] JFormRuleNumber
- [x] JFormRuleOptions
- [x] JFormRulePassword
- [x] JFormRuleRules
- [ ] JFormRuleTel
- [ ] JFormRuleUrl
- [x] JFormRuleUsername
- [x] JMicrodata
- [ ] JDatabaseDriver
- [x] JDatabaseExporter
- [ ] JDatabaseFactory
- [x] JDatabaseImporter
- [ ] JDatabaseInterface
- [ ] JDatabaseIterator
- [ ] JDatabaseQuery
- [ ] JDatabaseDriverMysqli
- [ ] JDatabaseDriverPdo
- [ ] JDatabaseDriverPdomysql
- [ ] JDatabaseDriverPgsql
- [ ] JDatabaseDriverSqlazure
- [ ] JDatabaseDriverSqlite
- [ ] JDatabaseDriverSqlsrv
- [ ] JDatabaseExceptionConnecting
- [ ] JDatabaseExceptionExecuting
- [ ] JDatabaseExceptionUnsupported
- [x] JDatabaseExporterMysqli
- [x] JDatabaseExporterPdomysql
- [x] JDatabaseExporterPgsql
- [x] JDatabaseImporterMysqli
- [x] JDatabaseImporterPdomysql
- [x] JDatabaseImporterPgsql
- [x] JDatabaseQueryElement
- [x] JDatabaseQueryLimitable
- [x] JDatabaseQueryPreparable
- [x] JDatabaseQueryMysqli
- [x] JDatabaseQueryPdo
- [x] JDatabaseQueryPdomysql
- [x] JDatabaseQueryPgsql
- [x] JDatabaseQuerySqlazure
- [x] JDatabaseQuerySqlite
- [x] JDatabaseQuerySqlsrv
- [x] JFactory (#24106)
- [ ] JMail
- [x] JMailHelper (#24119)
- [ ] JClientHelper
- [ ] JClientFtp
- [ ] JFTP
- [x] JClientLdap
- [x] JLDAP
- [x] JUpdate
- [x] JUpdateAdapter
- [x] JUpdater
- [x] JUpdaterCollection
- [x] JUpdaterExtension
- [ ] JCrypt
- [x] JCryptCipher
- [x] JCryptKey
- [ ] \\Joomla\\CMS\\Crypt\\CipherInterface
- [ ] \\Joomla\\CMS\\Crypt\\Key
- [x] JCryptCipherCrypto
- [ ] JStringPunycode
- [x] JBuffer
- [ ] JUtility
- [ ] JInputCli
- [x] JInputCookie
- [ ] JInputFiles
- [ ] JInput
- [x] JInputJSON
- [ ] JFeed
- [ ] JFeedEntry
- [x] JFeedFactory
- [x] JFeedLink
- [ ] JFeedParser
- [ ] JFeedPerson
- [x] JFeedParserAtom
- [x] JFeedParserNamespace
- [x] JFeedParserRss
- [x] JFeedParserRssItunes
- [x] JFeedParserRssMedia
- [ ] JImage
- [ ] JImageFilter
- [x] JImageFilterBackgroundfill
- [x] JImageFilterBrightness
- [x] JImageFilterContrast
- [x] JImageFilterEdgedetect
- [x] JImageFilterEmboss
- [x] JImageFilterNegate
- [x] JImageFilterSmooth
- [ ] JObject
- [x] JExtensionHelper
- [ ] JHtml
- [ ] \\Joomla\\Application\\Cli\\CliInput
- [ ] \\Joomla\\Application\\Cli\\CliOutput
- [ ] \\Joomla\\Application\\Cli\\ColorStyle
- [ ] \\Joomla\\Application\\Cli\\Output\\Stdout
- [ ] \\Joomla\\Application\\Cli\\Output\\Xml
- [ ] \\Joomla\\Application\\Cli\\Output\\Processor\\ColorProcessor
- [ ] \\Joomla\\Application\\Cli\\Output\\Processor\\ProcessorInterface
- [ ] JFile
- [ ] JFolder
- [ ] JFilesystemHelper
- [x] JFilesystemPatcher
- [ ] JPath
- [ ] JStream
- [x] JStreamString
- [x] JStringController

**Comment by brianteeman** [comment]
Checked a few and all of these are already done.
 JRegistryFormatIni
  JRegistryFormatJson
  JRegistryFormatPhp
  JRegistryFormatXml
  JStringInflector
  JStringNormalise
  JData
  JDataSet
  JDataDumpable
   JUpdate
  JUpdateAdapter
  JUpdater
  JUpdaterCollection
  JUpdaterExtension

**Comment by C-Lodder** [comment]
thanks @brianteeman

**Comment by brianteeman** [comment]
These are all done as well
  JImageFilterBackgroundfill
  JImageFilterBrightness
  JImageFilterContrast
  JImageFilterEdgedetect
  JImageFilterEmboss
  JImageFilterNegate
  JImageFilterSmooth

**Comment by brianteeman** [comment]
JInputCookie
JBuffer
JButton
JBrowser
JOpenSearchImage
JOpenSearchUrl
 JCache
   JCacheControllerOutput
  JCacheControllerPage
  JCacheStorageApcu
  JCacheStorageHelper
  JCacheStorageFile
  JCacheStorageMemcached
  JCacheStorageRedis
  JCacheStorageWincache
   JCacheExceptionUnsupported
  JFeedParserAtom
  JFeedParserNamespace
  JFeedParserRss
  JFeedParserRssItunes
  JFeedParserRssMedia
JFeedFactory
JFeedlink

**Comment by C-Lodder** [comment]
`JCache` is still referenced in some comment blocks, so will leave that for now

**Comment by brianteeman** [comment]
When I did the original pass through updating these I ignored the docblocks and comments

**Comment by brianteeman** [comment]
JLanguageAssociations
  JLanguageHelper
  JLanguageStemmer
  JLanguageMultilang
  JLanguageTransliterate
  JLanguageStemmerPorteren

**Comment by brianteeman** [comment]
JDatabaseExporter
  JDatabaseExporterMysqli
  JDatabaseExporterPdomysql
  JDatabaseExporterPgsql
 JDatabaseImporterMysqli
  JDatabaseImporterPdomysql
  JDatabaseImporterPgsql
  JDatabaseImporter

**Comment by brianteeman** [comment]
JDatabaseQueryElement
  JDatabaseQueryLimitable
  JDatabaseQueryPreparable
  JDatabaseQueryMysqli
  JDatabaseQueryPdo
  JDatabaseQueryPdomysql
  JDatabaseQueryPgsql
  JDatabaseQuerySqlazure
  JDatabaseQuerySqlite
  JDatabaseQuerySqlsrv

**Comment by brianteeman** [comment]
JFormRuleBoolean
  JFormRuleCalendar
  JFormRuleCaptcha
  JFormRuleColor
  JFormRuleNotequals
  JFormRuleNumber
  JFormRuleOptions
  JFormRulePassword
  JFormRuleRules
  JFormRuleUsername

**Comment by brianteeman** [comment]
JFormFieldAliastag
  JFormFieldAuthor
 JFormFieldCacheHandler
  JFormFieldCalendar
  JFormFieldCaptcha
  JFormFieldCategory
  JFormFieldCheckbox
  JFormFieldCheckboxes
  JFormFieldChromeStyle
  JFormFieldColor
  JFormFieldCombo
  JFormFieldComponentlayout
  JFormFieldComponents
  JFormFieldContenthistory
  JFormFieldContenttype
 JFormFieldEditor
  JFormFieldEMail
JFormFieldFile
  JFormFieldFileList
  JFormFieldFolderList
  JFormFieldFrontend_Language
 JFormFieldHeadertag
  JFormFieldHelpsite
  JFormFieldHidden
JFormFieldGroupedList
  JFormFieldHeadertag
  JFormFieldHelpsite
  JFormFieldHidden
  JFormFieldImageList
  JFormFieldInteger
  JFormFieldLastvisitDateRange
  JFormFieldLimitbox
JFormFieldMenu
  JFormFieldMenuitem
  JFormFieldMeter
  JFormFieldModulelayout
  JFormFieldModuleOrder
  JFormFieldModulePosition
  JFormFieldModuletag
JFormFieldNote
JFormFieldPassword
  JFormFieldPlugins
  JFormFieldPlugin_Status
JFormFieldRange
  JFormFieldRedirect_Status
  JFormFieldRegistrationDateRange
  JFormFieldRules
 JFormFieldSessionHandler
  JFormFieldSpacer
  JFormFieldSQL
  JFormFieldStatus
  JFormFieldSubform
 JFormFieldTag
  JFormFieldTel
  JFormFieldTemplatestyle
  JFormFieldTimezone
 JFormFieldUserActive
  JFormFieldUserGroupList
  JFormFieldUserState

**Comment by brianteeman** [comment]
JMailHelper #24119

**Comment by brianteeman** [comment]
JLogLogger
  JLogLoggerDatabase
  JLogLoggerEcho
  JLogLoggerFormattedtext
  JLogLoggerMessagequeue
  JLogLoggerSyslog
  JLogLoggerW3c

**Comment by brianteeman** [comment]
JHttpTransportCurl
  JHttpTransportSocket
  JHttpTransportStream

**Comment by C-Lodder** [comment]
List up to date

**Comment by brianteeman** [comment]
I don't know how we should address the following scenarios

a code comment - example
`	 * This function is passed log entries by JLogLoggerCallback.
`

a docblock - example
`	 * @param   \JInput              $input    Input
`
another example
```
	/**
	 * The event input.
	 *
	 * @var \JInput
	 * @since  4.0.0
	 */
	private $input = null;
```

**Comment by C-Lodder** [comment]
I'm in the process of improving the regex. I'll ping you when I'm done and also give you my node script which will assist in automatically making the changes for you.

**Comment by brianteeman** [comment]
Can this be closed now @C-Lodder

**Comment by ghost** [comment]
@C-Lodder can this be closed, which Categorie belongs it on Issue Tracker?

**Comment by C-Lodder** [comment]
Why close this? There are still lots of classes that require converting

**Comment by ghost** [comment]
@C-Lodder i asked as Brian asked before. Can you please give me a Hint for Categorie (is it "Code Style")?

**Comment by C-Lodder** [comment]
@franz-wohlkoenig Yeah I suppose Code Style would be fine

**Comment by brianteeman** [comment]
i didnt realise you had closed your pr

**Comment by brianteeman** [comment]
Pretty sure that this can be closed now
