### ISSUE TITLE
Custom Field - Integer: start from 0

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#24111]
### Is your feature request related to a problem? Please describe.

I create a Custom Field with Integer number. When I choose the value, I can not select 0

### Describe the solution you'd like

Add 0 option

### Additional context

![custom-field-integer](https://user-images.githubusercontent.com/906604/53945485-0304f380-40c2-11e9-8900-7e9ad8433b76.PNG)

**Comment by SharkyKZ** [comment]
Set `First`, `Last` and `Step` values in your custom field.

![untitled](https://user-images.githubusercontent.com/7325021/53946564-c094e400-40cc-11e9-95b1-54f093fea573.png)

**Comment by ghost** [comment]
@Razzo1987 Please ask on [Forum](https://forum.joomla.org/)
