### ISSUE TITLE
Internal Server Error instead of Joomla error page on PHP-FPM

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#24125]
### Steps to reproduce the issue

Run Joomla on PHP-FPM setup.
Cause an error, e.g. put a call to non-existing function in `templates/protostar/index.php`.

### Expected result

Joomla error page. With stack trace if debug is enabled.

### Actual result

Internal Server Error.

### System information (as much as possible)

Setting | Value
-- | --
 
PHP Built On | Linux 2.6.32-042stab134.8 #1 SMP Fri Dec 7 17:16:09 MSK 2018 x86_64
Database Type | mysql
Database Version | 5.5.5-10.3.12-MariaDB
Database Collation | latin1_swedish_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.2
Web Server | Apache/2
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 3.9.3 Stable [ Amani ] 12-February-2019 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments

Not a solution, but replacing `$app->toString()` with `$app->getBody()` here displays the error page normally. So maybe this is something to do with sending headers:

https://github.com/joomla/joomla-cms/blob/2d2a75618602422dc9a03bf53fd7b124c7deb3a2/libraries/src/Exception/ExceptionHandler.php#L126

**Comment by ghost** [comment]
@SharkyKZ can you please give the Issue a Categorie on Issue Tracker? I have no clue where to assign.

**Comment by SharkyKZ** [comment]
Closing this as per https://github.com/joomla/joomla-cms/issues/24183#issuecomment-473887905 it's a server configuration issue.
