### ISSUE TITLE
[4.0] extract the search position from the menu position .

### ISSUE THREAD

**Issue by hitaly** [joomla/joomla-cms#24129]
### Steps to reproduce the issue
add the main menu module to position MENU .
add the search module to position SEARCH .
test it on mobile : 
the search show just after click on the colaps menu button .![screen shot 2019-03-08 at 14 38 03](https://issues.joomla.org/uploads/1/154451470dd3ed89bda75f3cd114decd.jpeg)

### Expected result
extract the search position from the navbar div 

### System information (as much as possible)
joomla 4 alpha 6

**Comment by ghost** [comment]
Please add "[4.0]" at Start of Title.

**Comment by ghost** [comment]
According to https://docs.joomla.org/Bug_and_Issue_Tracker_Priority changed Priority from "Crticial" to "Medium".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24129">issues.joomla.org/tracker/joomla-cms/24129</a>.</sub>

**Comment by brianteeman** [comment]
Reading the code that is the intended behaviour. I assume @ciar4n can explain the reasoning

**Comment by ciar4n** [comment]
I can't remember off hand if this was in @C-Lodder original template PR or something I changed after. I assume the reasoning was for a less cluttered small screen display. I'm easy about it so feel free to change if you deem this an issue. 

Is this even going to be the J4 template? I'm hearing mixed reports.

![image](https://user-images.githubusercontent.com/2803503/54072991-a51b0c00-4279-11e9-9951-7a8af5a97c55.png)

**Comment by hitaly** [comment]
i see the issue on alpha 7 too .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24129">issues.joomla.org/tracker/joomla-cms/24129</a>.</sub>

**Comment by ghost** [comment]
@hitaly thats expected if none is working on it.

**Comment by Scrabble96** [comment]
Why is this expected behaviour? Why hide the search bar in small-screen view, anyway?

I cannot believe that tapping what everyone would believe to be a tappable menu - i.e. the three lines that countless websites use to indicate the presence of a mobile-friendly menu - should display an otherwise hidden search bar. 

If I viewed a website with this template I would be very surprised not to find a menu under the three lines.

The main menu in Cassiopeia's default position of sidebar-right disappears completely on a mobile phone if there's any content on the page:

![Screenshot_20190906-175610_Chrome-small](https://user-images.githubusercontent.com/36987494/64446923-ffcedc80-d0d1-11e9-9468-ff6d993ef260.jpg)

The main menu is down below here somewhere in the sidebar that has dropped below the component area.

**Comment by ciar4n** [comment]
> Why is this expected behaviour? Why hide the search bar in small-screen view, anyway?

This wasn't done with any serious consideration or reasoning. I don't think anyone would argue against changing it.

**Comment by Scrabble96** [comment]
I propose the following change to Cassiopeia index.php and some extra CSS for the search div:

Index.php - remove lines 103 to 115 inclusive:

`				<?php if ($this->countModules('menu') || $this->countModules('search')) : ?>`
`					<button class="navbar-toggler navbar-toggler-right" type="button" aria-hidden="true" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="<?php echo Text::_('TPL_CASSIOPEIA_TOGGLE'); ?>">`
`						<span class="fa fa-bars"></span>`
`					</button>`
`					<div class="collapse navbar-collapse" id="navbar">`
`						<jdoc:include type="modules" name="menu" style="none" />`
`						<?php if ($this->countModules('search')) : ?>`
`							<div class="form-inline">`
`								<jdoc:include type="modules" name="search" style="none" />`
`							</div>`
`						<?php endif; ?>`
`					</div>`
`				<?php endif; ?>`

Replace with:

`				<?php if ($this->countModules('search')) : ?>`
`					<div id="search" class="form-inline">`
`        					<jdoc:include type="modules" name="search" style="none"/>`
`        				</div>`
`				<?php endif; ?>`

Add the following css (somewhere):

`#search {
  margin-top: 10px;
}`
`@media (min-width: 992px) {
  #search {
    margin-top: 0;
  }
}`

I'm also not sure what would happen if someone wanted to put an actual menu behind the burger bar.

**Comment by mbabker** [comment]
In all fairness here, my company has done a few websites where clicking a "hamburger icon" on mobile or tablet devices shows both the main menu and a search bar (usually this also involves an off screen menu coming into view from the side instead of the Bootstrap navbar behavior).  So while it might not be the normal thing for many people, it is a practice that is used and can work well.  All that to say I don't see an issue with the current behavior myself but we all know what they say about opinions.

**Comment by Scrabble96** [comment]
> 
> 
> In all fairness here, my company has done a few websites where clicking a "hamburger icon" on mobile or tablet devices shows both the main menu and a search bar.

At the moment, it _only_ shows the search bar.

**Comment by mbabker** [comment]
Then I’d say there’s a bit of a logic bug.  Either the main menu should be in the header area (as most would expect) which doesn’t make things look “broken” with the hamburger menu only toggling search or there shouldn’t be a menu spot in the header and therefore no need for a hamburger.

At a minimum it sounds like the template needs conditional logic as to whether the hamburger should even render based on whether some module uses the menu position.

**Comment by Scrabble96** [comment]
> 
> 
> Then I’d say there’s a bit of a logic bug. Either the main menu should be in the header area (as most would expect) which doesn’t make things look “broken” with the hamburger menu only toggling search or there shouldn’t be a menu spot in the header and therefore no need for a hamburger.

I have to agree with you.

**Comment by jwaisner** [comment]
@hitaly Is this still an issue in the latest J4 build?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24129">issues.joomla.org/tracker/joomla-cms/24129</a>.</sub>

**Comment by brianteeman** [comment]
@jwaisner nothing has been changed which is why this is still open

**Comment by hitaly** [comment]
> 
> 
> @hitaly Is this still an issue in the latest J4 build?
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/24129](https://issues.joomla.org/tracker/joomla-cms/24129).

@jwaisner  YES YES ...
i tryed it now on j4 beta1 and the issue  still there .

**Comment by hitaly** [comment]
@jwaisner 
i dont know why you turned the Priority to low ?! 
and why this bug still there in alpha 4 ?! 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24129">issues.joomla.org/tracker/joomla-cms/24129</a>.</sub>

**Comment by hitaly** [comment]
i mean  why this bug still there in beta 4 ?!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24129">issues.joomla.org/tracker/joomla-cms/24129</a>.</sub>

**Comment by drmenzelit** [comment]
That has been solved in Cassiopeia repository:
https://github.com/joomla/cassiopeia/pull/89

**Comment by Scrabble96** [comment]
> 
> 
> That has been solved in Cassiopeia repository:
> [joomla/cassiopeia#89](https://github.com/joomla/cassiopeia/pull/89)

Well, I never knew that repository was there. How is it different from the joomla-cms repository, which has Cassiopeia files in its code?

**Comment by C-Lodder** [comment]
@Scrabble96 That repo is dedicated to Cassiopeia fixes and improvements. It will eventually be merged back into this repo.

**Comment by drmenzelit** [comment]
There is a working group for Cassiopeia improvement. I thought @chmst told that already.
We are preparing a PR for the cms repo.

**Comment by Scrabble96** [comment]
> 
> 
> There is a working group for Cassiopeia improvement. I thought @chmst told that already.
> We are preparing a PR for the cms repo.

@chmst mentioned the working group to me but as I've never been involved with one I had no idea what it entails. I know a bit more, now.

**Comment by drmenzelit** [comment]
If you are in glip, you can join the Cassiopeia public channel

**Comment by hitaly** [comment]
just now i download beta 4 and test it ... the bug still there and not fixed .
steps : 
1- add the menu module to menu position .
2- add the search module to search position .
3- on pc click ctrl with + to zoom in the screen until see the colaps menu icon and the search will hide .
4- click the colaps menu icon , you will see the search under the menu .

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24129">issues.joomla.org/tracker/joomla-cms/24129</a>.</sub>

**Comment by drmenzelit** [comment]
@hitaly this has been solved in a special Cassiopeia repository. We are preparing a PR for the core.

**Comment by hitaly** [comment]
@drmenzelit fantastic 
very good news .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24129">issues.joomla.org/tracker/joomla-cms/24129</a>.</sub>

**Comment by brianteeman** [comment]
This should be closed now
