### ISSUE TITLE
save & save new & save close & save copy not be a list on big screens

### ISSUE THREAD

**Issue by hitaly** [joomla/joomla-cms#24128]
### Steps to reproduce the issue
it is not nice to group the save new & save close & save copy with the save button on big screens .
it is ok for mobile .
it is a hard work when create a lot of articles or modules .... etc .
![screen shot 2019-03-08 at 14 04 46](https://issues.joomla.org/uploads/1/939a245d986d2e33611d05e7846ff2c8.jpg)

### Additional comments

![screen shot 2019-03-08 at 14 04 46](https://issues.joomla.org/uploads/1/9c3972abaf738bef4d3d9b60b50049d6.jpg)

**Comment by ghost** [comment]
Please add "[4.0]" at Start of Title.

**Comment by Quy** [comment]
Duplicate #14326

**Comment by ghost** [comment]
closed as duplicate Report, thanks @Quy <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24128">issues.joomla.org/tracker/joomla-cms/24128</a>.</sub>
