### ISSUE TITLE
JEventDispatcher trigger args

### ISSUE THREAD

**Issue by MacTrophy** [joomla/joomla-cms#24130]
### Steps to reproduce the issue
I think calling anything with the `JEventDispatcher->trigger` with an event name and no args OR an empty args array will result in a error.

In my plugin I am calling 
```
$dispatcher = JEventDispatcher::getInstance();
$dispatcher->trigger('onUserAfterLogout'); // trigger('onUserAfterLogout', array()); is also problematic
```
to get the `PlgAuthenticationCookie` to do it's job. If the 2nd parameter to trigger is not specified or I pass `array()`, I will get
```
Too few arguments to function PlgAuthenticationCookie::onUserAfterLogout(), 0 passed in libraries/joomla/event/event.php on line 70 and exactly 1 expected
```

if I call `$dispatcher->trigger('onUserAfterLogout', array('whatever' => 'whatever'));` it will work!

The problem seems to come from the call in `JEvent->update(&$args)` where the method `call_user_func_array` is called, PHP seems to NOT assign anything to the arguments of the triggered method if the array is empty.

### Expected result
Shouldn't raise an error!

IMO the JEvent should handle this and properly setup the $args array to avoid this situation

### Actual result
```
Too few arguments to function PlgAuthenticationCookie::onUserAfterLogout(), 0 passed in libraries/joomla/event/event.php on line 70 and exactly 1 expected
```

### System information (as much as possible)
Joomla 3.9.3
PHP 7.2 (AFAIK was not problematic under 5.6)
Debian 9 fully updated

**Comment by mbabker** [comment]
`PlgAuthenticationCookie::onUserAfterLogout()` requires at least one parameter, so `JEventDispatcher::getInstance()->trigger('onUserAfterLogout')` or `JEventDispatcher::getInstance()->trigger('onUserAfterLogout', [])` won't work.  You must provide at least one value in the arguments array.  So, this would be an expected behavior, not because of an issue in the event dispatcher but rather the listeners for an event.

**Comment by ghost** [comment]
closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24130">issues.joomla.org/tracker/joomla-cms/24130</a>.</sub>
