### ISSUE TITLE
[4.0] Header Overflow in administrator/articles/options

### ISSUE THREAD

**Issue by Puneet-Jain-18** [joomla/joomla-cms#24145]
### Steps to reproduce the issue
Go to backend =>articles=>options

### Expected result
header inside limited width

### Actual result

![Screenshot (13)](https://user-images.githubusercontent.com/34083630/54081919-2f737680-4333-11e9-9f9e-4e1999b7d911.png)

**Comment by ghost** [comment]
please provide Informations like "Nightly Build" or which "Alpha-Version".

**Comment by Puneet-Jain-18** [comment]
the version is : Joomla! 4.0.0-alpha7-dev

**Comment by Arpit-24** [comment]
Resetting the zoom on the page fixes the issue.

**Comment by ghost** [comment]
closed as having Pull Request #24382
