### ISSUE TITLE
Login for users without backend access

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#24141]
### Steps to reproduce the issue
Create a user in a group without backend access. 
Try to login with this account.

### Expected result
An Error message as for example "do not have access to the Administrator section of this site"
or nothing. 

### Actual result
The error message is displayed but a sliding effect initiated

**Comment by ghost** [comment]
@chmst please provide System Informations.

**Comment by chmst** [comment]
So sorry, can you close this @franz-wohlkoenig?

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24141">issues.joomla.org/tracker/joomla-cms/24141</a>.</sub>
