### ISSUE TITLE
[3.9] Adding a parameter in password management

### ISSUE THREAD

**Issue by eric-lamy-agerix** [joomla/joomla-cms#24156]
Hello,

Currently the password management settings allow to set for X digits lenght: at least X Upper Case, at least X Integer and at least X Symbol. However, it is not possible to ask for at least X Lower Case.

For some large accounts, it is described in the specifications that the password must have a lenght of X characters with at least X upper case, X lowercase, X integer and X symbol.
With the current system I am stuck for the Lower Case.

So I would like to have a box "at least X Lower Case" as it's done for Upper Case.
Thx for reading my request

**Comment by ghost** [comment]
@Quy can you please have a Look?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24156">issues.joomla.org/tracker/joomla-cms/24156</a>.</sub>

**Comment by HLeithner** [comment]
@agerix you are right this is missing. it should be trivial to add it.

**Comment by HLeithner** [comment]
I added a PR. Closing this. @agerix please test the PR.
