### ISSUE TITLE
[4.0] can't install languages in joomla 4 alpha 7

### ISSUE THREAD

**Issue by hitaly** [joomla/joomla-cms#24153]
### Steps to reproduce the issue
- system panel > Manage > languages > Install Languages .
click to install any Language , not work and get error message that say : 
Error
Unable to find install package

![screen shot 2019-03-11 at 03 50 20](https://issues.joomla.org/uploads/1/6755e20b6ebd91420275fb1cc74ffb18.jpeg)

**Comment by ghost** [comment]
there are only a few Languages available at the Moment: de-de, fr-fr and persian. So this Behaviour is expected, please close the Issue.
