### ISSUE TITLE
[4.0] Blank Pages at Frontend and Backend after Fresh installation of Joomla on MySQL 8

### ISSUE THREAD

**Issue by bosunski** [joomla/joomla-cms#24151]
### Steps to reproduce the issue
- Cloned fresh `4.0-dev` branch
- Ran `composer install` and then `npm install`
- Ran Joomla Web installation as usual
- Tried to open either the Administrator or the Site

### Expected result
I expect to see content both on the Frontend and backend like this:
![Screenshot 2019-03-10 at 4 09 17 PM](https://user-images.githubusercontent.com/15146515/54086989-0eb91a00-434f-11e9-991a-1ec75c0a9975.png)
![Screenshot 2019-03-10 at 4 09 45 PM](https://user-images.githubusercontent.com/15146515/54086990-0eb91a00-434f-11e9-87db-b41746b51d9b.png)

### Actual result
I saw a blank Page both on the Frontend and the Backend(Administrator) sides.

<img width="1436" alt="Screenshot 2019-03-10 at 12 07 03 PM" src="https://user-images.githubusercontent.com/15146515/54086928-66a35100-434e-11e9-944b-ed3c049be86b.png">

<img width="1680" alt="Screenshot 2019-03-10 at 10 35 45 AM" src="https://user-images.githubusercontent.com/15146515/54086948-9eaa9400-434e-11e9-9d92-3c2ecb6ded5f.png">

### System information (as much as possible)

- MAC OSX Mojave 10.14.3
- PHP 7.2.15 and 7.3
- MySQL 8
- Node v10.15.2
- NPM v6.4.1

### Additional comments
I noticed this when I turned on debugging for the one I installed on my Ubuntu Server and the One I have locally on my Mac OSX, here is the result:
<img width="1680" alt="Screenshot 2019-03-10 at 2 21 21 PM" src="https://user-images.githubusercontent.com/15146515/54086970-d285b980-434e-11e9-8894-9b6609c7b1cf.png">

**Comment by ghazal** [comment]
Everything worked fine for me today.
Using a mac too.
Try this:
`git clone --depth=1 -b 4.0-dev https://github.com/joomla/joomla-cms/`
`composer install`
`npm ci`
instead of
`npm install`

**Comment by ghost** [comment]
closed as unconfirmed Report. Please reopen if Issue persist.

@ghazal thanks for Investigation.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24151">issues.joomla.org/tracker/joomla-cms/24151</a>.</sub>

**Comment by bosunski** [comment]
@ghazal Thanks.

The issues still persist after trying out @ghazal 's suggestion. Tried on 2 Macbooks, still same issue.

@ghazal What is your environment details?

**Comment by bosunski** [comment]
Do you have a similar environment like mine?
System information
- MAC OSX Mojave 10.14.3
- PHP 7.2.15 and 7.3
- MySQL 8
- Node v10.15.2
- NPM v6.4.1

**Comment by ghost** [comment]
reopened as Issue persist.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24151">issues.joomla.org/tracker/joomla-cms/24151</a>.</sub>

**Comment by ghazal** [comment]
My environment:
mac 10.12

node 11.10.0
npm  6.8.0
Composer  version 1.8.4
All packagers installed and updated via [Homebrew](https://brew.sh/)

iTerm instead of Mac Terminal

php 7.2.5
MySQL 5.7.22 
Actually, I am using [Bitnami MAMP stack](https://bitnami.com/stack/mamp/installer), so I don't have to care about these versions.

**Comment by bosunski** [comment]
Based on what you just posted above, the only notable difference in our configuration is the MySQL versions, mine is `v8` while yours is `v5.7`. Noticing that, I downgraded to `v5.7` and everything works fine now.

It appears Joomla `v4.0` might be having compatibility issues with MySQL `v8`.

Thanks, @ghazal and @franz-wohlkoenig 😅 for the time, I'm finally done with this battle after days!

**Comment by brianteeman** [comment]
Can this be re-opened please and change the title from (mac osx) to (mysql 8) as it definitely needs investigating

**Comment by bosunski** [comment]
Alright ... I'll do that.

**Comment by alikon** [comment]
@bosunski can you report back what it is present in your  mysql 8 error.log please

**Comment by bosunski** [comment]
I didn't think of the error logs earlier as I already removed MySQL 8 and installed 5.7. I will install `v8` again and get the error logs across.

**Comment by Quy** [comment]
Duplicate #22974?

**Comment by roland-d** [comment]
Does this need updating? https://docs.joomla.org/Joomla_and_MySQL_8

**Comment by Quy** [comment]
Close this as a known issue as there is a doc page for it?

**Comment by ghost** [comment]
closed as stated above; Issue can always be reopened.

**Comment by mbabker** [comment]
Actually, there should be one issue open somewhere tracking the progress of MySQL 8 compatibility in the CMS.  Without that, items will be continually closed pointing to that docs page which gives the impression that Joomla is not making efforts to support MySQL 8 (hell it still doesn't fully support 5.7).

Closing items and pointing to a doc page generally comes across as "this is how Joomla works, here is the documentation reference explaining it".

**Comment by ghost** [comment]
Reopen Issue as comment by @mbabker stated above.

**Comment by Quy** [comment]
Closing in favor of #25452 as it has additional details.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24151">issues.joomla.org/tracker/joomla-cms/24151</a>.</sub>
