### ISSUE TITLE
[4.0] 4.0.0-alpha7-dev to 4.0.0-alpha8-dev: XMLs not updated with the new version

### ISSUE THREAD

**Issue by dmitriy-cloudaccess** [joomla/joomla-cms#24154]
### Steps to reproduce the issue
Joomla 4.0 NightlyBuilds download link (found on https://developer.joomla.org/nightly-builds.html)
is  `https://developer.joomla.org/nightlies/Joomla_4.0.0-alpha8-dev-Development-Full_Package.zip`
its version is `4.0.0-alpha8-dev`.
However next major list XML contains old version - `4.0.0-alpha7-dev`. https://update.joomla.org/core/nightlies/next_major_list.xml

### Expected result
https://update.joomla.org/core/nightlies/next_major_list.xml
4.0.0-alpha8-dev

### Actual result
https://update.joomla.org/core/nightlies/next_major_list.xml
4.0.0-alpha7-dev

**Comment by infograf768** [comment]
Confirmed.

**Comment by infograf768** [comment]
Corrected.
