### ISSUE TITLE
[4.0] Media Manager add more format to preview and edit. WebP

### ISSUE THREAD

**Issue by mrownicki** [joomla/joomla-cms#24157]
Summary of Changes
Media manger support preview graphic image like webp, jxr etc (next-gen)
Crop, rotate, save native format and quality.

Required configuration change in allowed file extensions and mime types added.
WEBP support all modern web browser except safari https://caniuse.com/#feat=webp

Testing Instructions
Upload image, manipulate and save in native format.

Expected result
After upload I can see preview file webp.
Webp manipulate size, crop, save to webp etc.

Actual result
don't preview, no size,
(https://issues.joomla.org/uploads/1/427069caa59f9c6dee833d5c68755c38.png)
(https://issues.joomla.org/uploads/1/189f6ef075bd140618b176626e843aa0.png)

Documentation Changes Required
NONE!

**Comment by ghost** [comment]
@Quy can you please have a Look?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24157">issues.joomla.org/tracker/joomla-cms/24157</a>.</sub>

**Comment by ghost** [comment]
webp is not supported in joomla 3,9,4 also

**Comment by ghost** [comment]
@laoneo can you please comment?

**Comment by laoneo** [comment]
I don't see any issues to support webp.

**Comment by brianteeman** [comment]
Not being supported on i0S is a major roadblock for me

**Comment by uglyeoin** [comment]
Is it a difficult thing to support?  iOS support would be nice, but failing that, if everyone else could have quicker loading images that would still be beneficial in terms of end user experience and also in terms of SEO.  I guess the way I see it, if Apple wants iOS users to suffer with slower loading websites so be it, but everyone else is supporting it, so in the long term, you can expect them to have to join suit.

**Comment by ghost** [comment]
webp is not supported in joomla 3,9,15 also so joomla users suffer with slower loading websites

brian its ios problem not joomla

**Comment by uglyeoin** [comment]
That's not strictly correct.  You can use the external link and manually type it and it will work.  So it's not supported or unsupported.  But yes, the media manager doesn't support them.  I'm not sure if it is a difficult change or not.  I manage to get by but it's not really end user friendly.

**Comment by korenevskiy** [comment]
Bug DragInDrop.
The standard `<input type="file"/>` field supports drag and drop. You can take an image file and drag it to the file field in any form of any Chromium-based browser site.
However, this function does not work when dragging a file to the image field in the material editor.
The modified file field should inherit from the `<input type="file"/>` field, we can use the tag `<label>` and add more functions. But you should always use the standard field `<input type= "file"/>`.
However, the material editor uses the `<input type="TEXT"/>` field without using the `<LABEL>`tag.
.
It is important to note that the field supposedly serves for the name of the file selected from the server. However, you can't change the name manually, which means it doesn't matter to the user what type of field this field actually is. If this is the case, we can use the hidden field `<input type="hidden" name="filename"/>`, but use the open field `<input type="file"/>` to upload and drag the file to the content editor.

**Comment by brianteeman** [comment]
In 2 years a lot has changed. webp is now supported across all supported browsers.

**Comment by joomleb** [comment]
> In 2 years a lot has changed. webp is now supported across all supported browsers.

Yes, [added support on iOS Safari 14 version](https://developer.apple.com/documentation/safari-release-notes/safari-14-release-notes)

**Comment by infograf768** [comment]
Test this to know if your browser supports webp
http://toste.dk/rh.php

My Safari OSX v 12 does not.

**Comment by brianteeman** [comment]
Time to update your computer ;)

**Comment by infograf768** [comment]
I accept donations.

**Comment by brianteeman** [comment]
see #33090
