### ISSUE TITLE
[4.0] Untranslated strings???

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#24168]
### Steps to reproduce the issue
Enable debug language
All strings should be wrapped in **
Observe how many of the button are wrapped in ?? indicating untranslated but they are
I don't know if its a bug in the debug code or what

### Examples
![image](https://user-images.githubusercontent.com/1296369/54155864-e7407b00-443c-11e9-95a5-1c570b45afbb.png)

![image](https://user-images.githubusercontent.com/1296369/54155914-fe7f6880-443c-11e9-8a65-e2be29cd6f33.png)

![image](https://user-images.githubusercontent.com/1296369/54155930-08a16700-443d-11e9-840e-c8a68e72055c.png)

**Comment by SharkyKZ** [comment]
It means the string is translated multiple times.

**Comment by infograf768** [comment]
For `Preview`, it is quite simple

It is first translated in
https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Toolbar/ToolbarButton.php#L121
as every toolbar button by default

Then it is translated again in
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_content/View/Article/HtmlView.php#L197-L200

This one can be solved here by modifying this last one to
```
				$url = PreviewHelper::url($this->item);
				$toolbar->preview($url, 'JGLOBAL_PREVIEW')
					->bodyHeight(80)
					->modalWidth(90);
```
to get
![Screen Shot 2019-03-12 at 07 04 19](https://user-images.githubusercontent.com/869724/54178169-24385c00-4495-11e9-9ba3-a3cbf694d72c.png)

I could not find a way for `Change Status`

**Comment by hardik-codes** [comment]
Started working on this.

**Comment by puneeth-chanda** [comment]
@SharkyKZ are you sure that this is being caused by repetition of strings, I can find the repetetion
 in the 'preview' thing as @infograf768 said but couldn't find the repetetion in case of Change Status.

**Comment by puneeth-chanda** [comment]
![image](https://user-images.githubusercontent.com/43813460/54216196-31922c80-450f-11e9-8ccb-596dfa38c0b9.png)
I found these being called only once,  i.e. in plugins/sampledata/blog/blog.php

**Comment by SharkyKZ** [comment]
Site menus are not translatable.

>are you sure that this is being caused by repetition of strings

Yes, it's because `Joomla\CMS\Toolbar\Button\DropdownButton::prepareOptions()` calls `parent::prepareOptions()` which translates the string and then uses the options to create a new button. But new button expects an untranslated string.

https://github.com/joomla/joomla-cms/blob/96b325ccd38e48570e93447a113246833c3d91b8/libraries/src/Toolbar/Button/DropdownButton.php#L70

**Comment by infograf768** [comment]
Indeed
`$this->getText()` also uses `Text::_`

**Comment by puneeth-chanda** [comment]
ok I get it thanks.

**Comment by infograf768** [comment]
Preview double translation now solved:
https://github.com/joomla/joomla-cms/pull/24178

Remains Change Status if it can be done.

**Comment by ghost** [comment]
@infograf768 Issue stay open?

**Comment by infograf768** [comment]
remains the Change Status issue to solve, if possible.

**Comment by brianteeman** [comment]
@infograf768 

> Preview double translation now solved:
> #24178
> 

That's not the right PR?

**Comment by infograf768** [comment]
The right PR was https://github.com/joomla/joomla-cms/pull/24173

Reopening as `Change Status` issue is not solved yet.

**Comment by brianteeman** [comment]
Closing - not worth keeping it open for this edge case.
