### ISSUE TITLE
problem when using php.ini in combination with php 7.3

### ISSUE THREAD

**Issue by jvstratum** [joomla/joomla-cms#24170]
### Steps to reproduce the issue

Place php.ini wioth some variables in public_html or /administrator

### Expected result

php variables are set and there are no errors when accessing frontend or backend

### Actual result

Frontend/backend will not load:

Warning: array_key_exists() expects parameter 2 to be array, null given in /home/.../public_html/libraries/cms.php on line 74

Warning: session_name(): Cannot change session name when headers already sent in /home/.../public_html/libraries/joomla/session/handler/native.php on line 128

Warning: session_cache_limiter(): Cannot change cache limiter when headers already sent in /home/.../public_html/libraries/joomla/session/handler/native.php on line 235
Error: Failed to start application: Failed to start the session because headers have already been sent by "/home/.../public_html/libraries/cms.php" at line 74.

### System information (as much as possible)

PHP version 7.3
Joomla version 3.9.3

### Additional comments

When using php 7.1 everything works ok. I contacted SiteGround about this. Their answer:

_"You will need to contact a professional developer who will be able to review your application version/settings /modules/ extensions and ensure that the aforementioned are all compatible with PHP 7.3.

If you encounter any issues when applying a newer PHP Version, this means that your website is not properly configured to function with that PHP version."_ 

Can someone clarify if this a Joomla issue or a hosting issue?

**Comment by brianteeman** [comment]
As you only said "some variables" and not which variables it is impossible to give anything more than a vague answer of "Joomla works with php 7.3 although it is possible that some of your extensions or template may need updating"

This should be closed here and asked on the forum

**Comment by jvstratum** [comment]
Thank you for your reply Brian,

I were these variables:

max_input_vars 
max_file_uploads 

Sorry for posting the question in the wrong place. Please close the ticket, I will post it to the forum.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24170">issues.joomla.org/tracker/joomla-cms/24170</a>.</sub>

**Comment by ghost** [comment]
closed as an Issue for Forum.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24170">issues.joomla.org/tracker/joomla-cms/24170</a>.</sub>
