### ISSUE TITLE
geoip2.phar doesn't work after update to 3.9.4

### ISSUE THREAD

**Issue by Karl-Goddard** [joomla/joomla-cms#24176]
### Steps to reproduce the issue
Update any Joomla site that uses geoip2 to v3.9.4

### Expected result
The site to be fully functional.

### Actual result
Unexpected file extension in "phar://geoip2.phar/src/Database/Reader.php"

### System information (as much as possible)

- The owner is set to apache

- The server is running on PHP 5.6.36

- CentOS Linux version 7
![screenshot-dev sungroupinc com-8088-2019 03 12-16-45-06](https://user-images.githubusercontent.com/47645546/54235819-80789b80-44e8-11e9-971c-15dc65d17756.png)

**Comment by ReLater** [comment]
Maybe related:
https://github.com/joomla/joomla-cms/issues/23907
https://github.com/joomla/joomla-cms/pull/23956
@HLeithner

**Comment by HLeithner** [comment]
@Karl-Goddard hmm strange @jurihahn tested it with the new version successfully

**Comment by HLeithner** [comment]
@Karl-Goddard can test this on another host? With a lower or higher PHP version?

**Comment by Karl-Goddard** [comment]
@HLeithner I have another test server running PHP7. I'll give it a try and let you know the result.

**Comment by Karl-Goddard** [comment]
@HLeithner 

PHP version:

PHP 7.2.13 (cli) (built: Dec  5 2018 07:37:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies with Zend OPcache v7.2.13, Copyright (c) 1999-2018, by Zend Technologies


Attached is a screenshot of the site on the php7 server after it was updated to 3.9.4

![screenshot-php7 sungroupinc com-2019 03 13-08-25-39]

(https://user-images.githubusercontent.com/47645546/54278815-db060c00-4569-11e9-82ea-08fe618bef6d.png)

**Comment by Karl-Goddard** [comment]
@ReLater I did the patch from #23907, which now gives me a new error: 

![screenshot-php7 sungroupinc com-2019 03 13-08-48-52](https://user-images.githubusercontent.com/47645546/54280020-dd1d9a00-456c-11e9-8b6c-2da46b564fe9.png)

**Comment by ohader** [comment]
@Karl-Goddard In the mentioned `PharStreamWrapper.php` file around line 445 (in method `collectInvocation($path)`), could you please `var_dump($path)` and post it here?

**Comment by Karl-Goddard** [comment]
@ohader var_dump($path) doesn't give any output. I tries placing it at the start of the function as well as before this line ```$manager->getCollection()->collect($this->invocation);```

**Comment by ReLater** [comment]
> I did the patch from #23907, which now gives me a new error

As far as I know the final patch is already integrated in Joomla 3.9.4 with pr 23956.  Code in 23907 was just a quick pre-test for old Joomla 3.9.3 code

**Comment by jurihahn** [comment]
I tested it again with Joomla 3.9.4, and it works as verified earlier.
PHP 7.3.2 (apache2handler)

**Comment by ohader** [comment]
* https://github.com/TYPO3/phar-stream-wrapper/issues/21
* https://github.com/TYPO3/phar-stream-wrapper/pull/22

Just for internal research and verification: Which version of the `geoip2.phar` has been used?

**Comment by jurihahn** [comment]
> Which version of the `geoip2.phar` has been used?

latest 2.9.0

**Comment by jurihahn** [comment]
I think my test was wrong ... I made my correction, then I applied the patch, but it looks like patch tool dont override my hotfix...
My last test with pure Joomla was not successful, I cannot use "geoip.phar".

**Comment by jurihahn** [comment]
does not work even after update to Joomla 3.9.5

**Comment by ghost** [comment]
@jurihahn that is expected as no Dev. made a Pull Request which solve the Issue.

**Comment by jurihahn** [comment]
i have workaround for "GeoIP2.phar"
`require_once ( 'phar://' . __DIR__ . '/geoip2.phar/vendor/autoload.php' );`

**Comment by ghost** [comment]
@jurihahn is it a Core-Issue?

**Comment by jurihahn** [comment]
Joomla include this library https://github.com/TYPO3/phar-stream-wrapper since version 3.9.3
It's a bug in this library.

**Comment by HLeithner** [comment]
do you have example code how you use this phar file? something I can copy-paste or install?

**Comment by jurihahn** [comment]
In this issue https://github.com/joomla/joomla-cms/issues/23907 i have description how to get this error.

**Comment by HLeithner** [comment]
Ok, I think we can close this, this is a phar-stream-wrapper problem and has it own issue at https://github.com/TYPO3/phar-stream-wrapper/issues/21

Workaround: ```require_once ( 'phar://' . __DIR__ . '/geoip2.phar/vendor/autoload.php' );```
