### ISSUE TITLE
Message reporting to log in (after cache is expired) should be warning type

### ISSUE THREAD

**Issue by kofaysi** [joomla/joomla-cms#24177]
### Steps to reproduce the issue

Request a content of any link on the page or on the site after the cache has been expired.

### Expected result

The message "Please login first" will be a different color than green.

### Actual result

The message is green, a positive and successful action.

### System information (as much as possible)

J3.9.4
code to be changed
https://github.com/joomla/joomla-cms/blob/fe597ef10fe6d6f0841bebc8aeebaad72d7080f3/libraries/src/Application/SiteApplication.php#L94

**Comment by hardik-codes** [comment]
Working on it
@kofaysi what should be the color according to you.

**Comment by kofaysi** [comment]
Yellow is my choice :) And it fits to the warning definition, too.

**Comment by hardik-codes** [comment]
@kofaysi how can I reduce the cachetimeout for testing purposes?

**Comment by kofaysi** [comment]
I believe it is in Global configuration > System > Cache settings > Cache time

**Comment by hardik-codes** [comment]
@kofaysi I not able to reproduce the issue correctly could you please elaborate

**Comment by kofaysi** [comment]
Activate "Logged-in Users" module for the Administrator interface and logout the user there.

I don't think that the reconstruction of the effect is so important. The message is of type message (green) by default, because no type is defined https://docs.joomla.org/Display_error_messages_and_notices. So, I argue that "a message requiring a user to log in first" should by of type notice or warning (preferred), wherever it occurs.

**Comment by hardik-codes** [comment]
Could you do screenshot please.

**Comment by kofaysi** [comment]
![image](https://user-images.githubusercontent.com/17022173/54436029-15baa080-4732-11e9-9214-1e4cf6c8d597.png)

**Comment by hardik-codes** [comment]
Screenshot for How do I 
> Activate "Logged-in Users" module for the Administrator interface and logout the user there.

**Comment by kofaysi** [comment]
publishing the module to the cpanel
![image](https://user-images.githubusercontent.com/17022173/54436701-4c44eb00-4733-11e9-90a4-91e6b2141ba2.png)
logging out a user in the cpanel (home of the administrator)
![image](https://user-images.githubusercontent.com/17022173/54436709-51099f00-4733-11e9-8ff3-efcc29da13f3.png)

**Comment by ghost** [comment]
closed as having Pull Request #24200
