### ISSUE TITLE
[4.0] Media field fails in subform

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#24179]
### Steps to reproduce the issue

Use `media` field in subform.

### Expected result

Works correctly on existing and new rows.

### Actual result

Javascript error.
```
TypeError: this.querySelector(...).open is not a function
joomla-field-media.js:244:45
```

### System information (as much as possible)

Joomla 4 alpha8

**Comment by puneeth-chanda** [comment]
@Denitz I could not reproduce the issue can you help me how.

**Comment by Denitz** [comment]
@puneeth2001 

[article.xml.txt](https://github.com/joomla/joomla-cms/files/2962346/article.xml.txt)

Replace `/administrator/components/com_content/forms/article.xml` with attached file (rename to .xml), it adds the code:

```
			

<field
					name="media_gallery"
					type="subform"
					multiple="true"
					layout="joomla.form.field.subform.repeatable-table"
					label="Gallery"
			>
				<form>
					<field name="path" type="media" required="true"
						   label="Image" />
				</form>
			</field>
```

Edit article and see Gallery field in Options, try to add items and select images.

**Comment by puneeth-chanda** [comment]
ok I will try it.

**Comment by ghost** [comment]
@puneeth2001 any Update?

**Comment by puneeth-chanda** [comment]
not yet, working on it.

**Comment by Quy** [comment]
Please test PR #24362<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24179">issues.joomla.org/tracker/joomla-cms/24179</a>.</sub>

**Comment by RomanaBW** [comment]
Should this issue be reopened? It works with single field (multiple="false"), but multiple="true" throws the same error on alpha11
