### ISSUE TITLE
Privacy Suite not logging consents from Contact Forms

### ISSUE THREAD

**Issue by JAVesey** [joomla/joomla-cms#24184]
### Steps to reproduce the issue
1. Enable the privacy suite plugins and have the Privacy Notice checkbox showing on Contact component email forms
2. User checks the "Privacy Note" check box.
3. User clicks the "Send Email" button.

### Expected result
The text alongside the Privacy Note checkbox says:
"By submitting this form you agree to the Privacy Policy of this website and the storing of the submitted information."  This reads as though the acceptance of the Privacy Note will be recorded/logged in /administrator.

### Actual result
There is no logging of the acceptance of the Privacy Note.

### System information (as much as possible)
Joomla 3.9.4
PHP7.2.15
Protostar template

### Additional comments
None

**Comment by frankota** [comment]
I had the same problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24184">issues.joomla.org/tracker/joomla-cms/24184</a>.</sub>

**Comment by brianteeman** [comment]
Is it this for guests (not logged in)?

If it is then it doesn't log as there is nothing to log

**Comment by ReLater** [comment]
Why should a contact form log the privacy consent? If you don't confirm you can't send the message.

I you're a registered user you have already confirmed. It's not necessary that you log that again just because you use the contact form. Just overhead.

**Comment by mbabker** [comment]
https://github.com/joomla-projects/privacy-framework/issues/213 for additional context.

**Comment by ghost** [comment]
Is this expected Behaviour?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24184">issues.joomla.org/tracker/joomla-cms/24184</a>.</sub>

**Comment by ReLater** [comment]
> Is this expected Behaviour?

Yes, it is.

**Comment by ghost** [comment]
Thanks for Info @ReLater 

Closed as expected Behaviour.
