### ISSUE TITLE
Problem with menu link to single article from administrator

### ISSUE THREAD

**Issue by pavanipotturi** [joomla/joomla-cms#24180]
### Steps to reproduce the issue
1. Create Menu and add MenuItem with single article . The path of the menu item is appended with Tracks or Categories .
for example if we created www.example.com/test then it is going to www.example.com/Tracks/test

### Expected result
example: www.example.com/test

### Actual result

example: www.example.com/Tracks/test

### System information (as much as possible)

Menu Rebuild is resolving the issue.

**Comment by puneeth-chanda** [comment]
@pavanipotturi can you provide the version of Joomla you are using.

**Comment by ghost** [comment]
@puneeth2001 in https://issues.joomla.org/tracker/joomla-cms/24180 its 3.9.4.

**Comment by ReLater** [comment]
Is that a Joomla that was migrated from Joomla 1.5 in the past or from Joomla 2.5 with a migrator tool?

Then this is a known issue because of a "confused menu table" but not a Jooma core issue. Sometimes this phenomen occurs years after the migration.

**Comment by pavanipotturi** [comment]
@ReLater is there any way to fix this issue?

**Comment by ReLater** [comment]
Repairing the menu table if error occurs again and again. Sometimes not that easy. You should ask in a forum I think.

**Comment by ghost** [comment]
Closed as an issue for [Forum](https://forum.joomla.org/)
