### ISSUE TITLE
[3.9] Changing module position adds instead of replacing the ordering dropdown

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#24182]
### Steps to reproduce the issue

Change a module position, a new ordering dropdown is added.

![module ordering](https://user-images.githubusercontent.com/1497730/54290929-145f6b80-45ac-11e9-8947-c3ed276eb852.gif)

### Expected result

Replace the old ordering dropdown.

### Actual result

Adds a new dropdown

### System information (as much as possible)

Joomla: 3.9.3+

**Comment by infograf768** [comment]
Confirmed

**Comment by infograf768** [comment]
Console error
`window.writeDynaList() is deprecated without a replacement!` in core.js 1:4520

**Comment by ghost** [comment]
closed as having Pull Request #24260
