### ISSUE TITLE
JFactory::getDate doesn´t set the timezone properly

### ISSUE THREAD

**Issue by irbian** [joomla/joomla-cms#24196]
### Steps to reproduce the issue

```php
         $config = JFactory::getConfig();
         $offset = $config->get('offset');
         $tz = new DateTimeZone($offset);
         $date = JFactory::getDate($timestamp, $tz); 
         //            $date->setTimezone($tz);
         print_r($date);
         $date->toSql(true);
```
Both php config and Joomla config, with timezone set to Atlantic/Canary

### Expected result

```php
Joomla\CMS\Date\Date Object
(
    [tz:protected] => DateTimeZone Object
        (
            [timezone_type] => 3
            [timezone] => Atlantic/Canary
        )

    [date] => 2018-10-22 23:59:00.000000
    [timezone_type] => 3
    [timezone] => Atlantic/Canary
)
```

### Actual result
```php
Joomla\CMS\Date\Date Object
(
    [tz:protected] => DateTimeZone Object
        (
            [timezone_type] => 3
            [timezone] => Atlantic/Canary
        )

    [date] => 2018-10-22 22:59:00.000000
    [timezone_type] => 1
    [timezone] => +00:00
)
```

### System information (as much as possible)

In this line we are setting the $tz property, but not the internal $tz. ¿Wouldn´t be that necessary? https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Date/Date.php#L118

¿Or maybe is something to control on the format method, here? https://github.com/joomla/joomla-cms/blame/staging/libraries/src/Date/Date.php#L293

### Additional comments
Actually, if I recall correctly, the problem is not with the timezone, but with the DST, because you need the timezone_type properly set so the date format takes it into account

If I uncomment the commented line in my code, it works.

**Comment by ghost** [comment]
@Quy can you please have a Look?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24196">issues.joomla.org/tracker/joomla-cms/24196</a>.</sub>

**Comment by HLeithner** [comment]
@bembelimen any comments on this?

**Comment by mbabker** [comment]
When the Date class is instantiated, it standardizes dates to UTC and the user's selected timezone stored in the `Joomla\CMS\Date\Date::$tz` property with UTC being pushed up into `DateTime::$timezone`.  See [the constructor](https://github.com/joomla/joomla-cms/blob/3.9.4/libraries/src/Date/Date.php#L85-L119) for details.

What practical issues are you experiencing with the standardized UTC timezone?

**Comment by irbian** [comment]
It's simple, if I use the format method (https://github.com/joomla/joomla-cms/blame/staging/libraries/src/Date/Date.php#L281) with local a true, it doesn´t show the local time taking into account the DST, because it never execute a setTimezone

Actually, is even more fun, because of https://github.com/joomla/joomla-cms/blame/staging/libraries/src/Date/Date.php#L327, if I do:

format(false) // works
format(true) // works

But if I don´t do it

// format(false) //
format(true) // don´t work

Again, because the inner object doesn´t have its timezone properly set

**Comment by ghost** [comment]
@irbian can you create a Pull Request (https://extensions.joomla.org/blog/item/how-to-contribute-to-joomla-through-github/)?

**Comment by irbian** [comment]
I could try, but I´m not sure yet the most correct way to solve it. Using setTimezone on the constructor?

**Comment by ghost** [comment]
@HLeithner can you please answer?

**Comment by HLeithner** [comment]
I think @mbabker has much more knowledge about this as me, I also experienced problems with jdate and timezones... but didn't debugged it... changing something in jdate could lead to unexpected behavior for existing installations...

**Comment by jwaisner** [comment]
@irbian are you still seeing this as an issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24196">issues.joomla.org/tracker/joomla-cms/24196</a>.</sub>

**Comment by irbian** [comment]
Interesting enough, I haven´t found this issue in a lot of places. One would be https://github.com/joomla/joomla-cms/blame/staging/administrator/components/com_categories/models/category.php where the setTimezone is already called and also on https://github.com/joomla/joomla-cms/blame/staging/administrator/components/com_tags/models/tag.php

I see at least three problems. How big of a problem they are is beyond me

- One. JFactory::getDate($timestamp, $tz), won´t set the internal date object timezone that some methods as Date::format use
- Two. format is not a function, but a procedure, because it modifies the internal date object timezone
- Three $date->toSql(true) won´t work unless you have called explicitly before, the method setTimezone

**Comment by joomdonation** [comment]
Look like the issue was solved elsewhere. I just tried on latest Joomla 4 and could not re-procedure the issue anymore. The date object has timezone set to the passed timezone (I remember there was a PR dealing with this issue sometime ago). 

With that said, I'm closing this issue. Feel free to re-open if the issue is still valid.
