### ISSUE TITLE
[4.0] install error: JInstallerHelper' not found

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#24198]
### Steps to reproduce the issue

Install Kunena 6.0 nightly build.

### Expected result

No error

### Actual result

Class 'Joomla\Component\Installer\Administrator\Model\JInstallerHelper' not found 

### Additional comments

Issue is on administrator\components\com_installer\Model\InstallModel.php line 191

**Comment by ReLater** [comment]
Please test pr https://github.com/joomla/joomla-cms/pull/24199
