### ISSUE TITLE
[4.0] Field Group (Category) error during a new category creation

### ISSUE THREAD

**Issue by nitesh-solanki** [joomla/joomla-cms#24202]
### Steps to reproduce the issue
Error
Save failed with the following error: Incorrect datetime value: '' for column 'modified' at row 1

I am getting these error when I am create a new category in Field Groups in the Joomla! 4.0.0-alpha7 while the same process is working fine at Joomla! 3.9.4

### Expected result
![screen shot 2019-03-16 at 12 12 02](https://issues.joomla.org/uploads/1/d0d6eed76dc2bab0e800794e8dea890f.png)

### Actual result

If I remove the readonly attribute of Modified Date and select a date from Created Date and then copy-paste it to the Modified Date.
Then it works.!

### System information (as much as possible)
Joomla! 4.0.0-alpha7
Database Version 	5.7.25-0ubuntu0.16.04.2
PHP Version 	7.2.16-1+ubuntu16.04.1+deb.sury.org+1
Web Server 	Apache/2.4.18 (Ubuntu)

### Additional comments

![screen shot 2019-03-16 at 12 12 12](https://issues.joomla.org/uploads/1/2f99a303b538fe3598eb20fcc96f7a63.png)

**Comment by bahl24** [comment]
Issue confirmed, let me try to solve this. In the table fields_groups the value being passed is '' which is not the expected datetime value.

**Comment by ghost** [comment]
closed as having Pull Request #24215

**Comment by infograf768** [comment]
Please rather test https://github.com/joomla/joomla-cms/pull/24234
I am closing now #24215
