### ISSUE TITLE
Registration.Activation Problem Strange Message And No Redirection 3.X

### ISSUE THREAD

**Issue by diolegend** [joomla/joomla-cms#24201]
### Steps to reproduce the issue

Hello Everyone, 

I need help with these 2 kinds of problem: 

1. I have two languages which are Italian and English and I created two menus for each (register & login) to get the alias in URL.
https://www.ingrossoborseonline.com/it/registrati
https://www.ingrossoborseonline.com/en/register
...

When I registered on the website in the Italian version of the webpage which is [](https://www.ingrossoborseonline.com/it/), I will get the confirmation email and receive something like "https://www.ingrossoborseonline.com/it/component/users/?task=registration.activate&token=f5d455188e4d75c6c21f98f783e35ce8&Itemid=122", the URL will redirect to https://www.ingrossoborseonline.com/it/registratilayout?=complete, so okay, everything going right (a problem will discuss to the part 2), But if I registered with the English version, giving the confirmation URL is "https://www.ingrossoborseonline.com/en/component/users/?task=registration.activate&token=a01453557b8f775895e5cb19576bd781&Itemid=123" with /en which is great, but it will redirect to "https://www.ingrossoborseonline.com/en/registrati" (no sense... Italian and English), so it will get a 404 error, for now, I did a manual redirection to https://www.ingrossoborseonline.com/en/register for resolving this problem and surprisingly get a no English message...

![](https://www.ingrossoborseonline.com/images/problem-register.png)

2. The normal redirection is to https://www.ingrossoborseonline.com/it/ ... t=complete[/b] which I get a JSON message I think it is... same as https://www.ingrossoborseonline.com/en/ ... t-complete

![](https://www.ingrossoborseonline.com/images/layout-complete-problem.png)

Menu structure:
![](https://www.ingrossoborseonline.com/images/menu.png)

Thank you to everyone, if it can resolve this big problem...
### Expected result

Normal Redirection and normal message with the actual language message.
No white screen.

### System information (as much as possible)

 
PHP  | Linux webd014.cluster023.gra.hosting.ovh.net 4.14.66-ovh-vps-grsec-zfs-classid #1 SMP Thu Aug 23 15:15:40 CEST 2018 x86_64
Database Type | mysql
Versione database | 5.6.39-log
Collation database | latin1_swedish_ci
Collation connessione database | utf8mb4_general_ci
Versione PHP | 7.2.14
Web Server | Apache
WebServer interfaccia PHP | fpm-fcgi
Versione di Joomla! | Joomla! 3.9.4 Stable [ Amani ] 12-March-2019 15:00 GMT
Versione piattaforma Joomla! | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36

PHP:

Safe Mode | No
Open basedir | Nessuno
Display Errors | No
Short Open Tags | Sì
Caricamento file | Sì
Magic Quotes | No
Register Globals | No
Output Buffering | Sì
Percorso salvataggio sessione | /tmp
Auto start sessione | 0
XML abilitato | Sì
Zlib abilitato | Sì
ZIP nativo abilitato | Sì
Funzioni disabilitate | _dyuweyrj4,_dyuweyrj4r,dl
Mbstring abilitato | Sì
Iconv disponibile | Sì
Maximum Input Variables | 16000

=============
FOLDER PERMISSSIONS
=============
administrator/components:  writable
administrator/language:  writable
administrator/language/it-IT:  writable
administrator/language/ru-RU:  writable
administrator/language/en-GB:  writable
administrator/language/de-DE:  writable
administrator/language/overrides:  writable
administrator/manifests/files:  writable
administrator/manifests/libraries:  writable
administrator/manifests/packages:  writable
administrator/modules:  writable
administrator/templates:  writable
components:  writable
images:  writable
images/swmenufree:  writable
images/sampledata:  writable
images/slider:  writable
images/phocadownload:  writable
images/slidereng:  writable
images/ArtFeatureCarousel2:  writable
images/ArtFeatureCarousel:  writable
images/jch_optimize_backup_images:  writable
images/headers:  writable
images/jch-optimize:  writable
images/icethumbs:  writable
images/aricloudcarousel:  writable
images/banners:  writable
language:  writable
language/it-IT:  writable
language/overrides:  writable
language/en-GB:  writable
libraries:  writable
media:  writable
modules:  writable
plugins:  writable
plugins/search:  writable
plugins/sampledata:  writable
plugins/community:  writable
plugins/acymailing:  writable
plugins/fields:  writable
plugins/xmap:  writable
plugins/twofactorauth:  writable
plugins/everything_in_everyway:  writable
plugins/editors:  writable
plugins/system:  writable
plugins/jshoppingcheckout:  writable
plugins/privacy:  writable
plugins/actionlog:  writable
plugins/solidres:  writable
plugins/finder:  writable
plugins/editors-xtd:  writable
plugins/extension:  writable
plugins/jshoppingmenu:  writable
plugins/jshoppingadmin:  writable
plugins/jshoppingrouter:  writable
plugins/jshopping:  writable
plugins/installer:  writable
plugins/user:  writable
plugins/quickicons:  writable
plugins/jshoppingproducts:  writable
plugins/ajax:  writable
plugins/mijopolls:  writable
plugins/jmonitoring:  writable
plugins/authentication:  writable
plugins/quickicon:  writable
plugins/captcha:  writable
plugins/content:  writable
templates:  writable
configuration.php:  NOT writable
xxxxxx/cache:  writable
log:  writable
tmp:  writable

**Comment by ghost** [comment]
comment by @infograf768?

**Comment by infograf768** [comment]
Are you using the core multilingual feature?
What are the exact settings for the com_users "New User Account Activation"?
Are you using SEF? htaccess?

The links you posted make no sense to me.
We only get an `Itemid` in the url when SEF is set to No
Here I have set "New User Account Activation" to "self"

I get when SEF is set to No (here for en-GB)
`SITEBASEURL/index.php?option=com_users&task=registration.activate&token=55891c5aea376d296d2d4218295aad19&Itemid=373&lang=en`

otherwise we only get a token and the url contains the alias of the registration form menu item.

and when SEF is set to yes with an .htaccess using another language (here fr-FR, default language)
`SITEBASEURL/enregistrement-french?task=registration.activate&token=387975b4941d3a6412c97c99727e34ae`

in both cases the redirection is correct and message too.

My guess is that your settings are wrong somehow or a third party extension is messing multilingual on your site.
You should get help on the forums.

**Comment by ghost** [comment]
Thanks @infograf768 for Comment. 

As written above please ask on [Forum](https://forum.joomla.org/), Issue closed.
