### ISSUE TITLE
[4.0] Language files not loaded by plugin constructors

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#24205]
### Steps to reproduce the issue

Enable language debug. Enable some plugins that autoload language files. Check loaded language files.

### Expected result

Plugin language files loaded.

### Actual result

Plugin language files not loaded.

### System information (as much as possible)

4.0-dev nightly.

### Additional comments

Seems to be stemming from #21768. CC @laoneo.

**Comment by SharkyKZ** [comment]
https://github.com/joomla/joomla-cms/blob/204944255cf6cbc08358625e541e0acccf64aa10/libraries/src/Factory.php#L745
This returns `NULL` but it should be language code?

**Comment by laoneo** [comment]
Is it a specific plugin or all of them?

**Comment by ReLater** [comment]
Related? https://github.com/joomla/joomla-cms/issues/17444

**Comment by SharkyKZ** [comment]
@laoneo this happens with plugins that load language in the constructor. Loading language manually later on during any plugin event works fine.

@ReLater Yes, it's the same. Guess I should close this.

**Comment by brianteeman** [comment]
This is what @wilsonge struggled and failed to work out last week
