### ISSUE TITLE
[4.0] Undefined variable Notice when displaying Contacts Manager

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#24208]
### Steps to reproduce the issue
Displays the contacts manager

### Notice
`[16-Mar-2019 17:38:22 Europe/Berlin] PHP Notice:  Undefined variable: noUser in /Applications/MAMP/htdocs/installmulti/joomla40/layouts/joomla/html/batch/user.php on line 26`

The choice for "No user" is not proposed in the batch modal

**Comment by chmst** [comment]
Confirmed.
But: The Batch function should be checked in all views, it does not make sense to get the batch modal when nothing is to do.  

Batch should be always be disabled until at least one item in the list is selected.
When at least one item is selected the button is enabled. 


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24208">issues.joomla.org/tracker/joomla-cms/24208</a>.</sub>

**Comment by chmst** [comment]
@infograf768 can you post a screen, please? The batch button must be disabled when you are on the view contacts, until you mark at least one contact.

**Comment by infograf768** [comment]
I have an issue here in present branch after a clean install

The `Change status` and `Batch` button are not greyed)when first displaying any manager... (that is a new behavior as it was working fine until recently). This for all managers, not only contacts.
If one selects an item in the list and then unselect it, then the buttons rightfully get greyed.
Looks like this is an issue with our js.

For the user notice, I found where is the problem and now making a patch.

**Comment by chmst** [comment]
see also this issue: https://github.com/joomla/joomla-cms/issues/24226

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/24228
