### ISSUE TITLE
Message reporting an error on update fail should be of error type

### ISSUE THREAD

**Issue by kofaysi** [joomla/joomla-cms#24209]
### Steps to reproduce the issue

Install a package which contains an error and evoke:
https://github.com/joomla/joomla-cms/blob/fe597ef10fe6d6f0841bebc8aeebaad72d7080f3/administrator/components/com_installer/models/update.php#L466

Example of package, error and Joomla combination:
https://screenshots.firefox.com/UojAszn3JtInhoFu/ctenarsky-klub.cz

### Expected result

Message "Error updating package" of Error type appears.

### Actual result

Message "Error updating package" of Message type appears.

### System information (as much as possible)

J3.9.1
https://github.com/joomla/joomla-cms/blob/2177bef45a2ac4d792be0c4a274e7207249987c9/administrator/language/en-GB/en-GB.com_installer.ini#L141

**Comment by ReLater** [comment]
Please test pr https://github.com/joomla/joomla-cms/pull/24210
