### ISSUE TITLE
[4.0][a11y] New menu item Buttons inaccessible for keyboard users

### ISSUE THREAD

**Issue by Puneet-Jain-18** [joomla/joomla-cms#24218]
### Steps to reproduce the issue

go to backend
component/articles/**open already created already article**/New Menu Item/

try navigating to  Close or Save buttons in the footer using keyboard

### Expected result
Close or save button could be accessed

### Actual result
Not able to navigate to Close or Save buttons in the footer

**Comment by chmst** [comment]
Work in progress: https://issues.joomla.org/tracker/joomla-cms/23254<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24218">issues.joomla.org/tracker/joomla-cms/24218</a>.</sub>

**Comment by ghost** [comment]
closed as stated above, thanks @chmst
