### ISSUE TITLE
[4.0] Content Security Policy main menu item missing language string on login

### ISSUE THREAD

**Issue by lllopo** [joomla/joomla-cms#24214]
### Steps to reproduce the issue
1. Login to Joomla backend
2. Open main menu

### Expected result
The content security policy menu item should be "Content Security Policy"

### Actual result
The content security policy menu item has "com_csp" as text

### System information (as much as possible)
Joomla! 4.0.0-alpha8-dev Development [ Amani ] 9-March-2019 13:41

### Additional comments
After clicking on the content security policy menu item the menu item text is changed to "Content Security Policy" as it should be.

**Comment by ghost** [comment]
Is this related to #24202?

**Comment by lllopo** [comment]
I don’t think so.

**Comment by ghost** [comment]
sorry @lllopo was a Question for Maintainer.

**Comment by wilsonge** [comment]
It's possible it's related to https://github.com/joomla/joomla-cms/issues/17444 - but i think unlikely given all the other menu strings are loading. Certainly don't see how it's related to #24202

**Comment by brianteeman** [comment]
I thought this was not going to be in the menu anyway but only in the dashboard

**Comment by wilsonge** [comment]
I won't be - there's a PR somewhere to do that. But it's just a weird bug

**Comment by bahl24** [comment]
I think the problem is in line 17 https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_csp/csp.xml, The menu tag should enclose `Content Security Policy` instead of `com_csp`. The component might need a fresh install after changing.

**Comment by zero-24** [comment]
> The menu tag should enclose Content Security Policy instead of com_csp.

No it should not as this is the place where the language string com_csp should be used.

Banners and most of the other components is using the same: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_banners/banners.xml#L32 ;)

**Comment by wilsonge** [comment]
Closed as we have a PR https://github.com/joomla/joomla-cms/pull/24431
