### ISSUE TITLE
[4.0 alpha 7] fresh installation - database table warning

### ISSUE THREAD

**Issue by schnuti** [joomla/joomla-cms#24229]
### Steps to reproduce the issue
Download the installation package and install J! alpha 7
Have a look at Database "check" and you'll see this

![db-problem](https://user-images.githubusercontent.com/956537/54531182-f1a2cd80-4984-11e9-96f5-dd9e9bb0c249.jpg)

There was a title/tool-tip saying something like "index language is missing" I believe. The code from:  4.0.0-2018-07-10.sql is probably missing for the installation.
It's easy to fix, just click the button.

### Expected result
Fresh installation should not have any db-problem.

### Actual result
See above

### System information (as much as possible)
XAMPP on Windows

**Comment by chmst** [comment]
Please test #24204<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24229">issues.joomla.org/tracker/joomla-cms/24229</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #24204
