### ISSUE TITLE
[4.0] Toolbar Buttons enable and disable

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#24226]
### Steps to reproduce the issue
Open a list view, for example articles. The Buttons for actions and batch are enabled. 

![screen shot 2019-03-17 at 22 09 08](https://issues.joomla.org/uploads/1/c73ea0bfb7cd6edf8be211f3ac33c21a.png)

### Expected result
Buttons are disabled as long as no item ist selected

### Actual result
Buttons are enabled. 
But select an item, then "deselect" it and the buttons are comme il faut. 

### Additional comments
Related to https://issues.joomla.org/tracker/joomla-cms/24208

**Comment by puneeth-chanda** [comment]
@chmst Its working fine for me:
![screenshot-localhost-2019 03 18-11-54-02](https://user-images.githubusercontent.com/43813460/54510742-98cb3900-4974-11e9-83a7-dec035be068f.png)

**Comment by infograf768** [comment]
@puneeth2001 
This happens in present branch after npm ci

**Comment by puneeth-chanda** [comment]
issue confirmed

**Comment by maliouris** [comment]
Can you check this request ? https://github.com/joomla/joomla-cms/pull/24243

**Comment by ghost** [comment]
closed as having Pull Request #24243
