### ISSUE TITLE
User account registration used for sending spam

### ISSUE THREAD

**Issue by the-djmaze** [joomla/joomla-cms#24231]
### Steps to reproduce the issue
1. Create a user account on a Joomla website.
2. Use a user name as "Cristal wants to see you in 9 hours http://www .connecticut-weddings.com/redirect.asp?URL=http://project1200995 .tilda.ws,"

### Expected result
Error about user name

### Actual result
Activation e-mail is send to new user as:

"Hello Cristal wants to see you in 9 hours http://www. connecticut-weddings.com/redirect.asp?URL=http://project1200995. tilda.ws,

Thank you for your registration..."

### System information (as much as possible)
Joomla 3.9.4

### Additional comments

User name should be checked against URI content and fail

**Comment by Quy** [comment]
Please test PR #20142<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24231">issues.joomla.org/tracker/joomla-cms/24231</a>.</sub>
