### ISSUE TITLE
[4.0]Full Screen Design

### ISSUE THREAD

**Issue by meet2410shah** [joomla/joomla-cms#24237]
### What needs to be fixed
![Issue](https://user-images.githubusercontent.com/44209311/54588564-617a8c00-4a49-11e9-88cf-58f14204815c.png)

### Why this should be fixed
The other written content is below this buttons and due to this it is not be visible .

### How would you fix it
I can just place the navigation bar at the top of the screen and rest of the content will remain below that navigation bar.

### Side Effects expected
Effect the user Experience.

**Comment by meet2410shah** [comment]
There is also no way to close from the full screen.

**Comment by ghost** [comment]
please append "[4.0]" at beginning of Title.

**Comment by ghost** [comment]
please provide System Informations like Nightly Build or Alpha, Browserversion, ... in first Comment.

**Comment by ghost** [comment]
> There is also no way to close from the full screen.

![Screen Shot 2019-03-19 at 09 42 30](https://user-images.githubusercontent.com/8235763/54591858-69c3ce80-4a2b-11e9-8262-eb44b24d5715.png)

**Comment by ghost** [comment]
Issue confirmed on:

Setting | Value
-- | --
PHP Built On | Linux lamp122.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.7.el6h.x86_64 nr.1 SMP Mon Dec 17 12:02:35 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.24-cll-lve
Database Collation | utf8_general_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.1.26
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 4.0.0-alpha8-dev Development [ Amani ] 9-March-2019 13:41 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:65.0) Gecko/20100101 Firefox/65.0

**Comment by Quy** [comment]
Please test PR #24334<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24237">issues.joomla.org/tracker/joomla-cms/24237</a>.</sub>
