### ISSUE TITLE
Category blog menu item shows no results after unused tag added and removed

### ISSUE THREAD

**Issue by mdmstw** [joomla/joomla-cms#24246]
### Steps to reproduce the issue
1. Create a category blog menu item which has articles assigned to the selected category.
2. Verify the category blog shows a list of articles.
3. Create a new tag (Components->Tags), but don't reference it on any article.
4. Edit the category blog menu item and assign the new tag, then save the menu item.
5. Verify that the category blog shows no articles (this is correct because the new tag is not assigned to the articles)
6. Edit the category blog menu item and remove the tag, then save the menu item.
7. Notice the category blog continues to show no articles (incorrect/unexpected). 

### Expected result
At step 7, because the tag was removed from the category blog menu item, it should return to showing the articles assigned to the category as it correctly did in step 2.

### System information (as much as possible)
Joomla 3.9.4
PHP 5.6.39
MySQL 5.7.25

**Comment by ghost** [comment]
@HLeithner can you please comment?

**Comment by HLeithner** [comment]
I tested this with joomla 3.9.4. it seams that the tag filter is cached in the user session. if the user closes the browser and reopens it, all articles are correctly shown.

**Comment by brianteeman** [comment]
This has been reported before
