### ISSUE TITLE
Articles permission issue

### ISSUE THREAD

**Issue by Flowman** [joomla/joomla-cms#24245]
### Steps to reproduce the issue
Create a group with permission to logon to admin
Create a category and assign the group the create
Login as the user and filter by the category
Try to create an article

### Expected result
User should be able to create article

### Actual result
User cannot create article

### System information (as much as possible)
Joomla 3.9.4

### Additional comments
https://github.com/joomla/joomla-cms/blob/b9097d9d4bbdaaa8f1831f84a502f0c632e34cfd/administrator/components/com_content/views/articles/view.html.php#L149

The $this->state->get('filter.category_id') is an array and get converted into a int.

https://github.com/joomla/joomla-cms/blob/b9097d9d4bbdaaa8f1831f84a502f0c632e34cfd/libraries/src/Helper/ContentHelper.php#L214

So the asset name will always be "com_content.category.1"

**Comment by ghost** [comment]
@HLeithner can you please comment?

**Comment by HLeithner** [comment]
Maybe a problem of the multi category filter feature? Can't validate it at the moment. @Quy can you check this?

**Comment by Flowman** [comment]
I guess the getActions method should check if the ID is array than process the whole array, if it a single value do what it does today.

**Comment by Flowman** [comment]
I just realized that create work as there is "count($user->getAuthorisedCategories('com_content', 'core.create'))" that fixes the issue for create, but I was testing core.edit and core.edit.state that does not work.

https://github.com/joomla/joomla-cms/blob/b9097d9d4bbdaaa8f1831f84a502f0c632e34cfd/administrator/components/com_content/views/articles/view.html.php#L157

**Comment by jwaisner** [comment]
@Flowman is this still an issue?

**Comment by brianteeman** [comment]
This is the expected behaviour - you have a user who can create a category nut you have not given them permissio to create an article.

this should be closed
