### ISSUE TITLE
[4.0] SMTP connection fails without SSL/TLS

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#24241]
Related PR #23591 

### Steps to reproduce the issue
Try to connect to an SMTP server without any SSL/TLS security option turned on

![image](https://user-images.githubusercontent.com/17835460/54603391-7bfe3680-4a44-11e9-9db9-10027700ed81.png)

### Expected result
Connection is successful as in Joomla 3.9

### Actual result
Connection fails and doesn't fallback anymore to a new one without a secutiry layer
It's not possible to connect to SMTP server without any SSL/TLS because $SMTPAutoTLS in the PHPMailer class is always true and not managed in any way by the mail class or Joomla options.

Additionally, even SSL/TLS options fail to connect to the SMTP server if enabled.

### System information (as much as possible)
Joomla 4.0 Alpha 8

### Additional comments
This is the result to have removed the following code in the Mail class within the Send function:

```
try
{
// Try sending with default settings
$result = parent::send();
}
catch (\phpmailerException $e)
{
$result = false;

if ($this->SMTPAutoTLS)
{
	/**
	 * PHPMailer has an issue with servers with invalid certificates
	 *
	 * See: https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#opportunistic-tls
	 */
	$this->SMTPAutoTLS = false;

	try
	{
		// Try it again with TLS turned off
		$result = parent::send();
	}
	catch (\phpmailerException $e)
	{
		// Keep false for B/C compatibility
		$result = false;
	}
}
}
```

**Comment by ghost** [comment]
~~Can you please provide more Details. I can't reproduce this Issue.~~

Mailer use always PHP-Mail, but SMTP is saved in Configuration.

**Comment by joeforjoomla** [comment]
I'm using an SMTP account on my localhost as usual. Let me know if you need additional informations about the SMTP configuration.

**Comment by joeforjoomla** [comment]
The only way to have it working as in Joomla 3 is settings 
public $SMTPAutoTLS = false;
in the PHPMailer.php

**Comment by joeforjoomla** [comment]
![image](https://user-images.githubusercontent.com/17835460/55312390-b6fd6280-5465-11e9-8656-eab420805b8c.png)

**Comment by ghost** [comment]
I searched for SMTP at CloudAccess, can't find.

**Comment by joeforjoomla** [comment]
I don't know which SMTP you are searching. I'm just talking about a standard SMTP account.

**Comment by ghost** [comment]
> standard SMTP account

Don't know what this mean.

**Comment by joeforjoomla** [comment]
Don't you know what is an SMTP account?

**Comment by ghost** [comment]
I don't know what you mean by "standard" SMTP-Account, so i searched at CloudAccess.

**Comment by joeforjoomla** [comment]
I mean an SMTP account configured as in the screenshot.

**Comment by wilsonge** [comment]
Please test https://github.com/joomla/joomla-cms/issues/24886
