### ISSUE TITLE
[4.0] Update "Alpha8" to "Nightly Build": ... a "NULL" was provided

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#24240]
### Steps to reproduce the issue
Update "Alpha8" to "Nightly Build, got:
![modified](https://user-images.githubusercontent.com/8235763/54597615-266f5d00-4a37-11e9-892b-a6fc110d7e81.png)
### System information
Setting | Value
-- | --
PHP Built On | Linux lamp122.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.7.el6h.x86_64 nr.1 SMP Mon Dec 17 12:02:35 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.24-cll-lve
Database Collation | utf8_general_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.1.26
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 4.0.0-alpha8-dev Development [ Amani ] 9-March-2019 13:41 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:65.0) Gecko/20100101 Firefox/65.0

**Comment by wilsonge** [comment]
Do you have a stack trace for this error?

**Comment by ghost** [comment]
how to get a stack trace?

**Comment by wilsonge** [comment]
turn on debug in system configuration and go back to the page (if you can't access system configuration edit configuration.php directly)

**Comment by ghost** [comment]
Thanks @wilsonge , but after new Installation got: "Secure Connection Failed An error occurred during a connection to fw4.joomla.com. Peer's Certificate has been revoked. Error code: SEC_ERROR_REVOKED_CERTIFICATE" - Issue is reported to CloudAccess.

**Comment by wilsonge** [comment]
No rush! Just whenever you have time :)

**Comment by ghost** [comment]
i tried again installing but its always solved only on CloudAccess-Side, so i gave up.

**Comment by ghost** [comment]
@wilsonge After enabling "Debug" get "Whoops, looks like something went wrong." at Back- and Frontend.

**Comment by ghost** [comment]
Closing as Issue resolved elsewhere.
