### ISSUE TITLE
Unexpected rename of uploaded file

### ISSUE THREAD

**Issue by fractaleater** [joomla/joomla-cms#24247]
### Steps to reproduce the issue
upload a file that starts with same name as domain.. ex: www.johndoe.com, and attempt upload of a file called "johndoe.com.test.pdf" (no quotes)

### Expected result
A file called "johndoe.com.test.pdf" (no quotes) in the media folder.

### Actual result
A file called "johndoecom.test.pdf" (no quotes) in the media folder.

### System information (as much as possible)
PHP 7.2.14
Apache cgi-fcgi

### Additional comments
Not commenting on the best practices of uploading a file that will have a url like http://www.johndoe.com/johndoe.com.test.pdf, but still should not be forbidden.

**Comment by ghost** [comment]
@HLeithner can you please comment?

**Comment by HLeithner** [comment]
We only allow 2 "." in a filename, I don't know way maybe @mbabker can answer this?
https://github.com/joomla/joomla-cms/blob/staging/libraries/vendor/joomla/filesystem/src/File.php#L46

**Comment by ghost** [comment]
Closed due th lack of Response. Issue can always reopened if needed.
