### ISSUE TITLE
Revert an upgrade

### ISSUE THREAD

**Issue by asmego** [joomla/joomla-cms#24250]
### Steps to reproduce the issue
Someone on our team selected the option to upgrade the Joomla Software. I didn't see what the exact upgrade was. Now, no one can login to Joonmla. This is the error message when we try to login. 
Parse error: syntax error, unexpected '$this' (T_VARIABLE) in /home3/njcouns/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/DAO.php on line 1123

I'm assuming we need to revert back to the previous version of Joomla, if possible. How do I do that?

**Comment by ghost** [comment]
Please ask on [Forum](https://forum.joomla.org/)
