### ISSUE TITLE
Error after upgrading. I think it needs to be reverted.

### ISSUE THREAD

**Issue by asmego** [joomla/joomla-cms#24251]
### Steps to reproduce the issue
One of our users upgraded the Joomla Software. I'm not sure of the exact upgrade that they did. Now, no one can login to Joomla to make changes. Once I try to login, I get this error: 
Parse error: syntax error, unexpected '$this' (T_VARIABLE) in /home3/njcouns/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/DAO.php on line 1123

I'm assuming that I need to revert back to a version before any changes were made. How do I fix this issue?

**Comment by ghost** [comment]
Please ask on [Forum](https://forum.joomla.org/)
