### ISSUE TITLE
[3.9] QR code generator - Google Authenticator

### ISSUE THREAD

**Issue by uruk-hai-21** [joomla/joomla-cms#24252]
### Steps to reproduce the issue
Enable plugin "Two Factor Authentication - Google Authenticator"

### Expected result
When Google Authenticator is enabled in user profile the QR Code is generated

### Actual result
QR code is not generated

### System information (as much as possible)
Joomla 3.9.4

### Additional comments
Qr code is generated in /libraries/fof/encrypt/totp.php in line 157
"$encoder = "https://chart.googleapis.com/chart?chs=200x200&chld=Q|2&cht=qr&chl=";"

But the QR code generation service of Google is deprecated in March 14, 2019:
https://developers.google.com/chart/infographics/

**Comment by PhilETaylor** [comment]
Google no longer provides a chart API for QR Codes. It was actually deprecated in 2012 and **turned off Completely on March 18, 2019**

**Comment by HLeithner** [comment]
So 2 possibilities, remove it or replace it with f. ex. qrcode http://phpqrcode.sourceforge.net (lib seams old enough to required php 5.3, untested)

**Comment by brianteeman** [comment]
Removing it is not an option

For j3 we could use https://github.com/kazuhikoarase/qrcode-generator/blob/master/php/qrcode.php

For j4 presumably we are using something else already as fof isnt included

**Comment by HLeithner** [comment]
why is removing not an option? for convenient reasons you mean?

**Comment by HLeithner** [comment]
The JS versions fits better vor this use case in my opinion.

**Comment by brianteeman** [comment]
yes. 

and I just checked that j4 has the same problem

**Comment by Quy** [comment]
Please test PR #24255<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24252">issues.joomla.org/tracker/joomla-cms/24252</a>.</sub>
