### ISSUE TITLE
User activation bug in Joomla

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#24259]
### Steps to reproduce the issue

New User Account Activation

Then new user clicks on activation email link and is redirected to site frontend and reads message that his account is activated , 

### Expected result

the admin in backend should see activated in green colour not in red

### Actual result

admin in backend sees activated in red colour

### System information (as much as possible)

joomla 3.9.4
moder sef on

**Comment by hardik-codes** [comment]
@Milglius could you please post screenshots for reproducing the issue?
I'll be working on it

**Comment by infograf768** [comment]
and post the settings you use for `User Account Activation`

**Comment by hardik-codes** [comment]
working on it

**Comment by ghost** [comment]
@hardik-codes A Solution is stated above. Could you please post screenshots and post the settings you use for User Account Activation for not reproducing the issue in joomla 3.9.4?

**Comment by hardik-codes** [comment]
@Milglius actually I need help with the procedure to reproduce the issue correctly

**Comment by ghost** [comment]
@hardik-codes with what procedure you need help?

**Comment by hardik-codes** [comment]
@Milglius could you just post the screenshot where the user activated appears in red?

**Comment by ReLater** [comment]
Sorry @Milglius but this is not the first issue that you post without detailed step-by-step instructions. It's not fair that helpers have to test all possible settings and have to write testing instructions for you. That's a waste of time.

Register a new user in Joomla fornt-end.

#### I can't reproduce the issue with these settings.

![27-03-_2019_14-57-33](https://user-images.githubusercontent.com/20780646/55082239-9ae27580-50a1-11e9-91d7-04d057bed298.jpg)

After clkicking the activation link in email to new user all fine:

![27-03-_2019_14-58-38](https://user-images.githubusercontent.com/20780646/55082297-b77ead80-50a1-11e9-9a6b-fb6ef221849e.jpg)

#### I can reproduce the issue with these settings.

![27-03-_2019_15-11-13](https://user-images.githubusercontent.com/20780646/55082888-c6199480-50a2-11e9-93aa-0a3582b63896.jpg)

After clkicking the activation link in email to new user: Activated is not green:

![27-03-_2019_15-12-08](https://user-images.githubusercontent.com/20780646/55082968-ea757100-50a2-11e9-8350-c7f3217a7e17.jpg)

### But the administrator gets an activation email where they have to click the activation link, too.

From my point of view: Expected bahavior.

**Comment by ghost** [comment]
@ReLater I try my best to help 

Yes its happens not with self but with administrator 

I hope @hardik-codes now understands procedure for reproducing the joomla issue

**Comment by ghost** [comment]
@ReLater How should we know if its expected bahavior?

**Comment by ghost** [comment]
@Milglius like https://github.com/joomla/joomla-cms/issues/24387#issuecomment-477456211 please describe your Issue so Volunteers can understand.

**Comment by ghost** [comment]
a Step-by-Step-Description, Screenshots is stated above
@franz-wohlkoenig please describe your Issue so I can understand how to help you

**Comment by ghost** [comment]
closed for same Reason as wrote in #24387<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24259">issues.joomla.org/tracker/joomla-cms/24259</a>.</sub>
