### ISSUE TITLE
Parent tags area is not populated

### ISSUE THREAD

**Issue by softforge** [joomla/joomla-cms#24268]
### Steps to reproduce the issue
In J4 go to Tags and add a tag. Save, Close

Now start a new tag and on the right under parent hit the drop down to select the first tag as the parent to the one you are creating

### Expected result
See the tag that was first created and be able to select it as a parent of the new tag being made

### Actual result
No tags appear in the drop-down. You can never select a parent tag

### System information (as much as possible)

Joomla 4 Alpha 8

**Comment by Bodge-IT** [comment]
I also checked  for this issue and could repeat.

**Comment by Quy** [comment]
Duplicate #23748?

**Comment by ghost** [comment]
Issue is closed at Tracker but here shown als "Open".

**Comment by Quy** [comment]
@infograf768 Please close on Github side. Thanks.

**Comment by infograf768** [comment]
done

**Comment by softforge** [comment]
I don't think they are duplicates. One is about the behaviour of adding tags in an article the other about trying to add a hierarchy of tags in the tag component. It would be worth seeing if the fix of the issue in the articles touches the issue in the tag component but I will watch the other issue and if the fix for that does not have an effect on the issue I found then I will ask to reopen this issue
