### ISSUE TITLE
[4.0] Batch not disabled

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#24262]
The batch button should be disabled until the user has selected at least one item. It was in J3 but currently it is not in j4

**Comment by ghost** [comment]
Duplicate #24226

**Comment by Fedik** [comment]
it was fixed once #21284 
seems a regression or not fully fixed

**Comment by infograf768** [comment]
https://github.com/joomla/joomla-cms/pull/24243 has solved that.

**Comment by infograf768** [comment]
closing as solved in codebase.
