### ISSUE TITLE
Forgot password erases account activation

### ISSUE THREAD

**Issue by innato** [joomla/joomla-cms#24269]
### Steps to reproduce the issue
Checked with Joomla! 3.9.4.
1. An existing registered user visits the front-end and clicks the "forgot your password" link.
2. Fill in the user's email address on the next screen and submit.
3. Next screen will inform you that email has been sent and is asking for Username and Verification Code.
4. Immediately after this, user remembers his password.
5. User goes to the home page and logs into the front-end in the usual way (i.e. without reading email and without using the verfification code).

### Expected result
6. User is allowed to log in as per normal procedure and without using the sent email or the verification code.
7. The user account (at back-end and in db) is restored to its previous state.

### Actual result
8. User is allowed to log in as per normal procedure (so this is OK).
9. The user account "Activated" status (back-end) remains disabled (not OK).
10. For the related user, the "activation" field in db contains a code string (should be empty) and the "lastResetTime" db field contains a timestamp instead of "0000-00-00 00:00:00" and the db field "resetCount" is 1 instead of 0 (not OK).

### System information (as much as possible)
Joomla! 3.9.4. standard install on local WAMP32 server (localhost). PHP 7.2.14. MySQL 5.7.21.

### Additional comments
Front-end user will probably not notice anything of this, but the described behaviour is inconsistent (designwise).
Maybe this is an omission rather than a bug.

**Comment by ghost** [comment]
@innato can you please look if this is reported (and maybe closed)? I remember a similaer Report.

**Comment by innato** [comment]
@franz-wohlkoenig I am sorry but don't know what you mean. Have I not reported it by my above submission? Or do you mean that it as been reported already and may have been closed meanwhile? I could not find an earlier report, but may not have searched long or good enough.

**Comment by ghost** [comment]
I thought a similaer Issue was reported (but maybe closed) earlier.

**Comment by Quy** [comment]
Please test PR #24327<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24269">issues.joomla.org/tracker/joomla-cms/24269</a>.</sub>
