### ISSUE TITLE
Word searched with Advanced search found in plural but not in singular

### ISSUE THREAD

**Issue by agilare** [joomla/joomla-cms#24286]
### Steps to reproduce the issue

1. make a research on Advanced Search module, for ex. "ascenseur" (french) in https://www.energie-environnement.ch/
2. articles containing the word ("ascenseur") exists https://www.energie-environnement.ch/le-saviez-vous/420-les-ascenseurs-utilisent-davantage-d-electricite-pour-attendre-que-pour-fonctionner ("Si l’ascenseur soutire...") but are not listed in results 

### Expected result

List of articles containing the searched word

### Actual result

Article containing the word not listed in results

### System information (as much as possible)

- PHP 7.2, MySQL 5.6, Joomla 3.9.4
- all articles are indexed, including the one containing the searched word
- [Indexing parameters of the example (energie-environnement.ch, french)](https://www.energie-environnement.ch/images/ee-joomla-search.png)

**Comment by ghost** [comment]
@Hackwar can you please give a Comment?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24286">issues.joomla.org/tracker/joomla-cms/24286</a>.</sub>

**Comment by Hackwar** [comment]
Smart Search in 3.x is broken. Don't expect this to work with anything else than English. In 4.0 all of this is fixed, in 3.x it's not possible in a b/c way. Sorry.

**Comment by Hackwar** [comment]
But I've written a plugin that backports the changes from 4.0 to 3.9. the version on my website is a bit outdated, but I'll update that soon.

**Comment by ghost** [comment]
After Update can you please provide a Link for similaer Issues?

**Comment by agilare** [comment]
Will the plugin porting the fix to 3.9 be publicly available ?

**Comment by alikon** [comment]
fixed in 4.x<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24286">issues.joomla.org/tracker/joomla-cms/24286</a>.</sub>
