### ISSUE TITLE
Random Image module

### ISSUE THREAD

**Issue by EmmaPuls** [joomla/joomla-cms#24298]
### What needs to be fixed
In the [Random Image Module](https://github.com/joomla/joomla-cms/blob/9217057c486b0050fdbde816b26d3fb83e1f806a/modules/mod_random_image/helper.php#L39-L42), there is a line that sets the default width to 100 if the user enters no width.
```
if ($width == '')
{
    $width = 100;
}
```
I'm assuming the intended functionality is to set the default width to 100%, however this code is ambiguous and get's interpreted as 100px in Chrome. 

### Why this should be fixed
Errors like this build up and ambiguous code is bad in general.

### How would you fix it
```
if ($width == '')
{
    $width = "100%";
}
```

### Side Effects expected
Images that users are used to being small will become responsive.

**Comment by ghost** [comment]
Thanks for your Suggest, can you make a [Pull Request](https://extensions.joomla.org/blog/item/how-to-contribute-to-joomla-through-github/) against J4?

**Comment by JamesNGarrett** [comment]
The field in the random image module config is a number type input and it defaults to 100.  It is clearly labled 'px'.

This is not an error just very limited in its functionality.  The module was written in a time prior to responsiveness.

**Comment by hardik-codes** [comment]
Members is this issue already resolved  as suggested by @JamesNGarrett  ?

**Comment by EmmaPuls** [comment]
I'd be more than happy to update the plugin with responsiveness if it's cool for me to contribute that kind of change? I'm pretty sure I could make it backwards compatible pretty easily.

**Comment by ghost** [comment]
if this is for j3 calling @HLeithner

**Comment by Bakual** [comment]
"Adding functionality" has to go to J4.
"Fixing bug" (without changing functionality) can go into J3.

**Comment by EmmaPuls** [comment]
> "Adding functionality" has to go to J4.
> "Fixing bug" (without changing functionality) can go into J3.

Truth but devo for my employer. I've already patched up their J3 implementation with a workaround so it's not a problem anyway. 

I'll add this to J4 then and do a pull request, cheers.

**Comment by Quy** [comment]
Related PR #22068 for J4.

**Comment by ghost** [comment]
> Related PR #22068 for J4.

@Quy does this mean something for this Issue?

**Comment by alikon** [comment]
managed in #22068<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24298">issues.joomla.org/tracker/joomla-cms/24298</a>.</sub>
