### ISSUE TITLE
Duplicating a template breaks if name of joomla install (physical folder) matches the template name.

### ISSUE THREAD

**Issue by chetanmadaan** [joomla/joomla-cms#24295]
### Steps to reproduce the issue
1. Install Joomla at localhost/beez3/
2. Go to extensions >> Templates >> Templates
3. Open beez3 template.
4. Click copy template on top left.
5. Put in any name in the popup.

### Expected result
![image](https://user-images.githubusercontent.com/3968575/54784283-d2f93c80-4bf9-11e9-8be9-5a1711a5673f.png)
Template should be copied.

### Actual result
![image](https://user-images.githubusercontent.com/3968575/54784262-c379f380-4bf9-11e9-9792-48b70d554c0a.png)
Copy template fails.

### System information (as much as possible)
Joomla 3.9.4
Windows 7 64 bit
Xampp
PHP 7.0
MySQL 5.6

### Additional comments

The problem is specifically here:
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_templates/models/template.php#L333

The **str_replace** function replaces the name of template wherever it exists in the path:

```
$file: D:\home\htdocs\beez3\tmp\template_copy_5c93fab14b898/language/en-GB/en-GB.tpl_beez3.ini
$newFile: D:\home\htdocs\testtemplate\tmp\template_copy_5c93fab14b898/language/en-GB/en-GB.tpl_testtemplate.ini
```

**Comment by ghost** [comment]
@HLeithner can you please comment?

**Comment by HLeithner** [comment]
it's a bug and we should fix it. Maybe someone could write a PR for this.

**Comment by Quy** [comment]
Please test PR #24316<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24295">issues.joomla.org/tracker/joomla-cms/24295</a>.</sub>
