### ISSUE TITLE
Install Joomla 4 alpha 6 - Failed

### ISSUE THREAD

**Issue by deathlynocturnal** [joomla/joomla-cms#24307]
### Steps to reproduce the issue

For me it was just running the installation process.

### Expected result

Site should install as normal.

### Actual result

Site fails me on the following:
Could not connect to the database. Connector returned number: SQLSTATE[42000]: Syntax error or access violation: 1231 Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER' - is Joomla 4 compatible with MySQL Server 8?

### System information (as much as possible)

- PHP 7.1.25
- MySQL 8.0.15
- Httpd server (Brew installed Apache)
- MacOS Mojave (Version: 10.14.1)

### Additional comments

Works for other versions of Joomla but just not the first one. Attached output and full PHP info.

**Comment by brianteeman** [comment]
Please see https://docs.joomla.org/Joomla_and_MySQL_8

**Comment by ghost** [comment]
closed for Reason stated above.
