### ISSUE TITLE
[4.0] Warning and Notice when Installing language pack

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#24302]
### Steps to reproduce the issue

Go to `administrator/index.php?option=com_installer&view=languages`
Install French (fr-FR) or German (de-DE) languages

1. We get a Notice 
`There were no checksums provided in the package.`
2. We get a PHP warning
`[22-Mar-2019 09:02:29 Europe/Berlin] PHP Warning:  Creating default object from empty value in ~/libraries/src/Updater/Update.php on line 299`

**Comment by alikon** [comment]
the 1) should be OK  see #17619 & #17555 (gsoc 2017) in 4.x every install pkg should have at least a checksum

for 2)  i'll investigate later

**Comment by infograf768** [comment]
Concerning 1) I did understand this has been implemented, but how shall we do to add a checksum for language packs?

**Comment by alikon** [comment]
a perfect example can be like com_patchtester do it
https://github.com/joomla-extensions/patchtester/blob/master/build/patchtester/build.sh#L19
even core do it https://github.com/joomla/update.joomla.org/blob/master/www/core/sts/extension_sts.xml#L184

- calculate the hash of the pkg/zip 
- add the hash to the pkg manifest

we need to find a "good " way to do it in an "easy way" for the language release cycle too

**Comment by brianteeman** [comment]
I can not replicate this

**Comment by infograf768** [comment]
Indeed, we do not have this anymore.
Closing.
