### ISSUE TITLE
[4.0] [a11y] Show Password

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#24312]
### Steps to reproduce the issue
Frontend login module
Admin login page
Admin user form

observe the password field and that if you can see and use a mouse then you are able to click on the eye icon and the password is revealed

### Expected result
- Users must be able to navigate to all interactive interface components using a keyboard.
- Visible focus. incomplete. Components must provide a visible indication when they have the input focus. (it's a span not an input element)
- After clicking on the eye there is no change in the sr-only text to indicate that the password is revealed

### Additional comments
As it stands right now the password view code is completely inaccessible and should be removed

**Comment by maliouris** [comment]
https://github.com/joomla/joomla-cms/pull/24287. Sorry for this but my changes were applied to my last pull request. Can you check it ?

**Comment by maliouris** [comment]
https://github.com/joomla/joomla-cms/pull/24287 I didn't make a new brach and this pull request ended up like this. Should I remove it and make 2 clear new pull requests ?

**Comment by Quy** [comment]
Please test PR #24326<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24312">issues.joomla.org/tracker/joomla-cms/24312</a>.</sub>

**Comment by Quy** [comment]
See PRs #27412 #27425

**Comment by SharkyKZ** [comment]
With https://github.com/joomla/joomla-cms/pull/27733 there should be no more issues remaining. Closing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24312">issues.joomla.org/tracker/joomla-cms/24312</a>.</sub>
