### ISSUE TITLE
[4.0] Error when Closing/Saving

### ISSUE THREAD

**Issue by simbus82** [joomla/joomla-cms#24314]
### Steps to reproduce the issue
Install Joomla 4.0 Nightly (22/03/2019)
Solve the stats.php bug https://github.com/joomla/joomla-cms/pull/24303

1. Open a Module, click on Save, or Save&Close or Close.
2. Open an article, delete date & time from publishing fields, then click on Save or Save&Close.

### Expected result

1. Module closed or saved or saved&closed without error.
2. Article saved or saved&closed without error

### Actual result

1. After Close "_An error has occurred. 1048 Column 'checked_out_time' cannot be null_" OR
After Save "_Save failed with the following error: Column 'publish_up' cannot be null_"
2. After Save "_Error: Save failed with the following error: Incorrect datetime value: '' for column 'created' at row 1_"

### System information (as much as possible)
dbserver: mysql
dbversion: 5.5.5-10.1.38-MariaDB
dbcollation: utf8_general_ci
dbconnectioncollation: utf8_general_ci
phpversion: 7.2.14
server: Apache
sapi_name: litespeed
version: Joomla! 4.0.0-alpha8-dev Development [ Amani ] 9-March-2019 13:41 GMT
useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36

### Additional comments
Some warnings in console:
```
DevTools failed to parse SourceMap: https://mywebsite.com/media/vendor/awesomplete/js/awesomplete.min.js.map
DevTools failed to parse SourceMap: https://mywebsite.com/media/vendor/css-vars-ponyfill/js/css-vars-ponyfill.min.js.map
DevTools failed to parse SourceMap: https://mywebsite.com/media/vendor/bootstrap/js/bootstrap.bundle.min.js.map
```
But i have these warnings in every page of Admin.
In frontend i have only this warning:
```
DevTools failed to parse SourceMap: https://mywebsite.com/media/vendor/bootstrap/js/bootstrap.bundle.min.js.map
```

**Comment by SharkyKZ** [comment]
If you have updated from another nightly, use System -> Database -> Fix to update database tables.

**Comment by simbus82** [comment]
Thanks! It worked!
Sorry, my fail!

PS: I think we need a notification about "Database problems" in Control Panel too. Or a new notification in the "notification bell"

**Comment by ghost** [comment]
Closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24314">issues.joomla.org/tracker/joomla-cms/24314</a>.</sub>
