### ISSUE TITLE
[4.0] 'Edit' text not visible on hover

### ISSUE THREAD

**Issue by Harshil99** [joomla/joomla-cms#24324]
### Steps to reproduce the issue
Go to Control Panel.
Click on the setting (gear) icon of any one of these (Sample Data, Logged-in Users, Popular Articles, Recently Added Articles, Site Information).
Hover over Edit.

### Expected result
Text ('Edit') color remains same i.e. Black or even according to specific contrast ratio like that in 'Unpublish' text below it.

### Actual result
Text ('Edit') color changes to white on hover.
![12](https://user-images.githubusercontent.com/31547079/54867981-6f177500-4dad-11e9-8828-0fbd8bec9c61.png)

### System information (as much as possible)
Joomla! 4.0.0-alpha8-dev
Google Chrome Version 72.0.3626.121 (Official Build) (64-bit)
Ubuntu 18.04.2 LTS

**Comment by bahl24** [comment]
I am unable to reproduce the issue, kindly recheck.
![Screenshot from 2019-03-25 15-47-21](https://user-images.githubusercontent.com/36095178/54911847-56c26a00-4f15-11e9-820a-7238a4a2fe4a.png)

**Comment by Puneet-Jain-18** [comment]
issue reproduces for me
version Joomla 4.0.0 alpha 8 -dev

**Comment by gkrn** [comment]
i am unable to reproduce the issue too , kindly recheck.
version Joomla 4.0.0 alpha 8-dev
Google Chrome Version- 73.0.3683.86

**Comment by Harshil99** [comment]
The issue produces some commits ago but now on hover it works good.
