### ISSUE TITLE
[4.0] joomla-toolbar-button-min.js disconnectedCallback has error

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#24333]
### Steps to reproduce the issue
Execute the disconnectedCallback of the toolbar button custom element

### Expected result
No js errors in the console

### Actual result
Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present

The disconnectedCallback function has the following and incomplete call to removeEventListener, it should be either removed or attached to a proper event handler passed in as the second argument:

`this.removeEventListener('click');`

### System information (as much as possible)

Joomla 4 Alpha 8

**Comment by Quy** [comment]
Please test PR #24338<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24333">issues.joomla.org/tracker/joomla-cms/24333</a>.</sub>

**Comment by joeforjoomla** [comment]
https://github.com/joomla/joomla-cms/pull/24338 works perfectly, no more errors
