### ISSUE TITLE
[4.0] Multilanguage Status module can't be unpublished

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#24339]
### Steps to reproduce the issue
Set up a multilingual site (eg using the sample data)
Try to disable the now unneeded multilanguage status module in the module manager
Refresh page.

### Expected result
Module is disabled and doesn't appear anymore.

### Actual result
Module always appears and gets republished without any notice on page refresh.

### Additional comments
PR #19463 added code which unpublishes/publishes the module on each pagerefresh according to the state of the language filter plugin. #21906 does a similar thing in the mod_status module so the module is always shown in the status bar, regardless of state and position settings.
Both PRs imho were wrong. We should not alter the published state of another extension, except maybe when needed for proper function. And even then there should be a notice and of course not done on each page request.

The multilang status module is a nice helpful module when trying to set up a multilingual site manually. But it is of no use once the site is set up. so it should be able to be disabled.
With 4,0 and the multilingual sample data, it's even less of use since you can set up a multilingual site with the press of a button.

I think the basic issue is that the mod_status module has the loading of the multilang status module hardcoded in its layout (introduced with #17056). Which is architecturally wrong (modules shouldn't load modules). The other PRs just are bandaid for the problems that come with that.

**Comment by infograf768** [comment]
https://github.com/joomla/joomla-cms/pull/19463 was made to deal with the automatic loading of the module which had been present in the 4.0 existing code at the time as you remarked.
The issue was that it did not display the module as published in the module manager and someone could by error display 2 modules... Also the status position would display the second module in a weird way.
I kind of like personnaly this automatic display by @C-Lodder as it is a clear sign that the site is set as multilingual and it does not take much page real estate.

**Comment by infograf768** [comment]
> With 4,0 and the multilingual sample data, it's even less of use since you can set up a multilingual site with the press of a button.

It does for a sample indeed, but once that sample is created, the user will test and modify the site and the module is very helpful to check at any time if anything is wrong.
I have even proposed a new PR 
https://github.com/joomla/joomla-cms/pull/24062
to check for more possible errors and get new messages to improve the module.

**Comment by Bakual** [comment]
> I kind of like personnaly this automatic display by @C-Lodder as it is a clear sign that the site is set as multilingual and it does not take much page real estate.

It's still wrong. The need for your two PRs are a direct result of that.

> Also the status position would display the second module in a weird way.

Which can and should be solved. Shouldn't be that hard.

Imho, the code for the module should be taken out of the mod_status one and the multilang module threated like a regular module. Put it as an own module into the status position (like in J3) and fix the display issues and everything is fine.

**Comment by Bakual** [comment]
See https://github.com/joomla/joomla-cms/pull/24341

Closing as we have a PR.
