### ISSUE TITLE
[4.0] item remain highlighted even after hover is removed

### ISSUE THREAD

**Issue by Puneet-Jain-18** [joomla/joomla-cms#24346]
### Steps to reproduce the issue
go to template styles=>advanced=> (select a parameter in which you have to select a file)
continuously hover over two items 

### Expected result
the black hover background from the previous item is removed on hovering over the new item

### Actual result
2 item remains with black hovering background
![Screenshot (37)](https://user-images.githubusercontent.com/34083630/54934449-89378b80-4f44-11e9-9ccf-dacb3bcffcc5.png)

### System information (as much as possible)
Joomla 4.0.0 alpha 8-dev

**Comment by schnuti** [comment]
I can confirm the issue.
It should be tagged as Media Manager and JavaScript. To test go directly to NMM.
I think I found the problem. An active attribute is added when hovering but is probably not correct removed. However when I use browser debugging (Chrome and FF)the active attribute (and the grey background) is removed as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24346">issues.joomla.org/tracker/joomla-cms/24346</a>.</sub>

**Comment by Quy** [comment]
Please test PR #24351<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24346">issues.joomla.org/tracker/joomla-cms/24346</a>.</sub>
