### ISSUE TITLE
[FireFox] Template menu assignment - page-break-inside property ignored

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#24344]
Break inside been ignore in FireFox if column-count is set.

### Steps to reproduce the issue
Have less than 4 menus. Navigate to template style menu assignment tab. Note if using sample data, it is probably easier to just delete the extra li nodes to display less than 4 menus (browser tools).

### Expected result
![image](https://user-images.githubusercontent.com/2803503/54932264-68564280-4f12-11e9-927d-4a035a07021d.png)

### Actual result
![image](https://user-images.githubusercontent.com/2803503/54932285-74420480-4f12-11e9-975a-635202564f59.png)

### System information (as much as possible)
FireFox

**Comment by Quy** [comment]
See PR #24345<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24344">issues.joomla.org/tracker/joomla-cms/24344</a>.</sub>
