### ISSUE TITLE
List of tagged items - 1054 - Unknown column 'Array' in 'where clause'

### ISSUE THREAD

**Issue by oschibsted** [joomla/joomla-cms#24342]
### Steps to reproduce the issue
Create a menu item using a "Compact list of tagged items" or "Tagged Items", set a tag and then navigate to the page.

### Expected result
See the list of articles that are tagged with the selected tag.

### Actual result
A SQL error, "1054 Unknown column 'Array' in 'where clause'".

### System information

Database Type | mysql
Database Version | 5.6.43
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.1.26
Web Server | Apache
WebServer to PHP Interface | litespeed
Joomla! Version | Joomla! 3.9.4 Stable [ Amani ] 12-March-2019 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments
I have the exact same issue as #19079 which is marked as closed without a fix.

This generated link does not work and gives an error:
 index.php?option=com_tags&view=tag&id[0]=2&Itemid=123

This link works(id[0]-->id): 
index.php?option=com_tags&view=tag&id=2&Itemid=123

**Comment by oschibsted** [comment]
Full error:

Unknown column 'Array' in 'where clause'	
/CENSORED/libraries/joomla/database/driver/mysqli.php:665

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/joomla/database/driver/mysqli.php:665
2 | JDatabaseDriverMysqli->execute() | JROOT/libraries/joomla/database/driver.php:1459
3 | JDatabaseDriver->loadAssoc() | JROOT/libraries/src/Table/Table.php:731
4 | Joomla\CMS\Table\Table->load() | JROOT/templates/support_template/index.php:37
5 | require() | JROOT/libraries/src/Document/HtmlDocument.php:658
6 | Joomla\CMS\Document\HtmlDocument->_loadTemplate() | JROOT/libraries/src/Document/HtmlDocument.php:720
7 | Joomla\CMS\Document\HtmlDocument->_fetchTemplate() | JROOT/libraries/src/Document/HtmlDocument.php:535
8 | Joomla\CMS\Document\HtmlDocument->parse() | JROOT/libraries/src/Application/CMSApplication.php:1030
9 | Joomla\CMS\Application\CMSApplication->render() | JROOT/libraries/src/Application/SiteApplication.php:778
10 | Joomla\CMS\Application\SiteApplication->render() | JROOT/libraries/src/Application/CMSApplication.php:202
11 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/index.php:49

**Comment by oschibsted** [comment]
I see a PHP Warning in the error-log as this happends:

[25-Mar-2019 14:00:45 UTC] PHP Warning:  Invalid argument supplied for foreach() in /CENSORED/libraries/joomla/database/driver.php on line 1904

This error does not appear when i change "id[0]" to "id" in the URL

**Comment by SharkyKZ** [comment]
Call stack indicates the issue is with your template:

```
4 | Joomla\CMS\Table\Table->load() | JROOT/templates/support_template/index.php:37
```

**Comment by oschibsted** [comment]
> Call stack indicates the issue is with your template:
> 
> ```
> 4 | Joomla\CMS\Table\Table->load() | JROOT/templates/support_template/index.php:37
> ```

Thanks alot. That was the problem!
