### ISSUE TITLE
URLs with utf8mb4 characters allowed

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#24354]
### Steps to reproduce the issue
Try to copy/paste an utf8mb4 character such as 😍 into a whatever alias menu, articles, etc when the 'Unicode aliases' option is enabled

### Expected result
The utf8mb4 character is stripped out and the link is working

### Actual result
The utf8mb4 is still there and the link is broken causing a MySQL error:

1267 Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='

### System information (as much as possible)
ALL Joomla versions

![image](https://user-images.githubusercontent.com/17835460/54990110-38627a00-4fba-11e9-90fb-ed3d60bfd18d.png)

**Comment by gkrn** [comment]
I think you need to go to your PhpMyadmin and change the collation of the the tables from 'utf8_general_ci' to 'utf8mb4_unicode_ci'.
Here's an article I found that might help -https://www.joomlathat.com/support/music-collection/1267-illegal-mix-of-collations-utf8-general-ci-implicit-and-utf8mb4-general-ci-coercible-for-operation-like

**Comment by joeforjoomla** [comment]
@gkrn we are talking about Joomla core tables, not something to go and change through phpMyAdmin
Additionally, the 'alias' field for each table of Joomla is set to utf8mb4_bin

**Comment by SharkyKZ** [comment]
@joeforjoomla please enable system debug in Global Configuration and post stack trace. Is this on a clean installation or updated? Do you have any extensions installed? Can you post a list of all your tables and their collations?

I can create the alias but I do not get the error. On a clean installation all tables should be `utf8mb4`.

**Comment by SharkyKZ** [comment]
I can reproduce this in backend.

**Comment by joeforjoomla** [comment]
@SharkyKZ closed as not a core issue.
Sorry for the delay.
