### ISSUE TITLE
[3.9.4] In Administration > Système > Configuration, if change the value in any field after Saving have to reload the page to see saved value

### ISSUE THREAD

**Issue by sergueikp** [joomla/joomla-cms#24357]
### Steps to reproduce the issue
1. Go to administration side
2. Go to Système > Configuration > Tab Serveur > Paramètres du serveur
3. Change value in the field Rapport d'erreurs: from old value "Aucun" to new value : "Maximum"
4. Click Save button, page is saved and reloaded
5. but you see the old value "Aucun" in the field Rapport d'erreurs
6. Refresh (reload) the page in the browser by clicking Reload the current page button in the browser's menu
7. Now you will see the new value: "Maximum" in the field

### Expected result
After clicking Save button new saved value must be displayed without any additional action 

### Actual result
You have to reload the page in the browser in order to see new saved value (or click two times on the Save button)

### System information (as much as possible)
PHP exécuté sur	Linux 2018 x86_64
Type de la base de données	mysql
Version de la base de données	5.5.30
Interclassement de la base de données	utf8_general_ci
Collation de la connexion à la base de données	utf8mb4_general_ci
Version de PHP	5.6.39
Serveur web	Apache
Serveur web pour interface PHP	fpm-fcgi
Version de Joomla	Joomla! 3.9.4 Stable [ Amani ] 12-March-2019 15:00 GMT
Version de la plateforme Joomla!	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments
I've tested the issue on my Windows 7 64-bits
my browser: Chrome Version 73.0.3683.86 (Build officiel) (64 bits)

Cordialement.

**Comment by Quy** [comment]
Unable to reproduce. Please ask for assistance in [Joomla Forum](https://forum.joomla.org/).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24357">issues.joomla.org/tracker/joomla-cms/24357</a>.</sub>

**Comment by SharkyKZ** [comment]
Previously such issue was caused by OPCache and fixed with #21949. Are you using any sort of caching on your system?

**Comment by sergueikp** [comment]
Hi, I'm using native Joomla caching and JCH Optimize Pro plugin which minimize the javascript and html files. I will deactivate it and see if there will be some changes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24357">issues.joomla.org/tracker/joomla-cms/24357</a>.</sub>

**Comment by sergueikp** [comment]
I've deactivated JCH Optimize Pro, but it gives no effect.
It's strange because the problem exists only In Administration > Système > Configuration page.
I've tested on some other pages like users and menu, there is no such problem. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24357">issues.joomla.org/tracker/joomla-cms/24357</a>.</sub>

**Comment by sergueikp** [comment]
Even in Administration > Système > Configuration > Options any page there is no such problem !
Only on Système > Configuration page. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24357">issues.joomla.org/tracker/joomla-cms/24357</a>.</sub>
