### ISSUE TITLE
Won't load after update: error JlanguageHelper

### ISSUE THREAD

**Issue by dougbevan** [joomla/joomla-cms#24355]
### Steps to reproduce the issue
Try to load site after update

### Expected result
Site load

### Actual result
PHP Fatal error:  Call to undefined method JLanguageHelper::parseIniFile() in D:\Sites\hivppi\libraries\src\Language\Language.php on line 803

### Additional comments
Tried update through web gui, process hung at 100%.  Tried manual method, but getting the above error.

**Comment by Quy** [comment]
Please ask for help at [Joomla Forum](https://forum.joomla.org/viewforum.php?f=710).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24355">issues.joomla.org/tracker/joomla-cms/24355</a>.</sub>

**Comment by ghost** [comment]
After Update a Joomla Site from 3.7.5 to 3.9.8, site won't load and display the following error message : 

_**Warning: Creating default object from empty value in /public_html/libraries/cms/application/site.php on line 540

Warning: Creating default object from empty value in /public_html/libraries/cms/application/site.php on line 540
Error displaying the error page: Call to undefined method JLanguageHelper::parseIniFile(): Call to undefined method JLanguageHelper::parseIniFile()**_

## Solution : 
Rename libraries folder to libraries.old
Copy libraries folder from 3.9.8 full package zip to your site.

## Note : 
if you have any custom libraries sub-folders in libraries.old, copy them again into the new libraries folder.


## Result : 
Site loads successfully
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24355">issues.joomla.org/tracker/joomla-cms/24355</a>.</sub>

**Comment by yahyamohsen** [comment]
Thanks alot for your help
