### ISSUE TITLE
[4.0] Undefined index: namespace

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#24360]
### Steps to reproduce the issue
Download the nightly build.
Install.
Check PHP error log.

### Actual result
PHP Notice:  Undefined index: namespace in \libraries\src\Installer\Adapter\ComponentAdapter.php on line 1423

### System information (as much as possible)
Joomla_4.0.0-alpha8-dev-Development-Full_Package

**Comment by wilsonge** [comment]
Confirmed. This currently blocks the installer from completing for me too.

**Comment by zero-24** [comment]
cc @roland-d and @NunoLopes96 it might should be checked before that there is a value in the namespace parameter as IIRC this is optional.

**Comment by alikon** [comment]
see #24367

**Comment by ghost** [comment]
closed as having Pull Request #24367
