### ISSUE TITLE
Duplicated custom fields in content component

### ISSUE THREAD

**Issue by artur-stepien** [joomla/joomla-cms#24361]
### Steps to reproduce the issue
- Go to administration of Content component
- Create a category called `A`
- Create a category called `B` and select parent category to `A` so the category tree looks like this: `A -> B`
- Create custom article field called `Test` and as a category select both `A` and `B`. Then in `Options` tab select `Automatic Display` to `Before Content`
- Create article called `Test Article` in `B` category and fill `Test` field with with: `This is the test field`
- Create a new articles blog view menu item displaying articles from `B` category
- Go to front end and open the new menu item you created
- Find the article called `Test Article` and open it.

### Expected result
This article `Test` field should only be visible once

### Actual result
Field is duplicated

### System information (as much as possible)
3.9.4 but I'm pretty sure it goes back to the introduction of custom fields

### Additional comments
I investigated the matter and it is caused by incomplete query in `FieldsModelFields` model (method `getListQuery`) from `/administrator/components/com_fields`. There is no group by in the query so field will be duplicated as many times as the number of parent categories on which your custom field exists. So if your tree is like A -> B -> C -> D and you place the article in D with setting the custom field to be available in all 4 categories you will have this field displayed 4 times. Simple group by should do the trick. It exists in content component but I'm pretty sure it affects all components using custom form fields and categories.

**Comment by alikon** [comment]
i'm unable to replicate if i understand this issue correctly
![Screenshot from 2019-04-05 18-40-46](https://user-images.githubusercontent.com/181681/55643017-5f972380-57d2-11e9-8091-ee524768f1ea.png)

**Comment by ggppdk** [comment]
Confirmed, e.g. you have field assigned to category D
- and you have category tree
A
 -> B
-> -> C
-> -> -> D

If you also assign field to the (ancestor) categories A,B,C (see picture)

![bug_field_mul_view](https://user-images.githubusercontent.com/5092940/55648133-279adb00-57e8-11e9-9480-5791861c4d1a.png)

Then you will get field values to appear 4 times when viewing the article in category D because,
there is no group-by (or other solution) in the getListQuery() as the description says

https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_fields/models/fields.php#L219-L224

```php
// Join over the assigned categories
$query->join('LEFT', $db->quoteName('#__fields_categories') . ' AS fc ON fc.field_id = a.id')
```
results in joining with the __fields_categories table 4 times, and getting same field 4 times

**Comment by alikon** [comment]
yes  i can confirm the issue now 
thanks @ggppdk for info :+1:

**Comment by Bakual** [comment]
I would look for another solution than using group-by. Groups are meant to use aggregate functions on the grouped rows. We don't need that.
A better approach is using DISTINCT.

**Comment by artur-stepien** [comment]
Well in this situation  GROUP BY or DISTINCT makes no difference.  Its just internal way of finding fields. So Just use the faster one?

**Comment by Bakual** [comment]
GROUP BY also means you need to add each selected column (that doesn't contain different values) to the GROUP BY command.
DISTINCT is much simpler as you can just specify one column.

So at least the code gets simpler with DISTINCT 😄

**Comment by alikon** [comment]
for me the issue is here https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_fields/models/fields.php#L209
why 
`// Traverse the tree up to get all the fields which are attached to a parent` ?

**Comment by ghost** [comment]
closed as having a Pull Request.

**Comment by artur-stepien** [comment]
@alikon The inheritance is ok. With 150+ children for lets say a products catalogue you don't have to add every category. If you have 10 fields that should be in 150 categories you're basically f*** :D So the inheritance is ok.

**Comment by alikon** [comment]
@artur-stepien please test #24516
