### ISSUE TITLE
[4.0] COM_ACTIONLOGS_POSTINSTALL_BODY missing closing  tag

### ISSUE THREAD

**Issue by horus68** [joomla/joomla-cms#24376]
### Steps to reproduce the issue
 </a> missing in version 4 language string COM_ACTIONLOGS_POSTINSTALL_BODY
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/language/en-GB/en-GB.com_actionlogs.ini#L52

`COM_ACTIONLOGS_POSTINSTALL_BODY="<p>With the release of Joomla 3.9.0 you can now log all administrative actions performed by your users in supported extensions. It is now easy to see who did what and when they did it.</p><p>The logs can be reviewed in Joomla or exported for external use.</p><p>For further information on this new feature read the <a href='https://docs.joomla.org/J3.x:User_Action_Logs' target='_new'>User Action Logs documentation.</p>`"

### Expected result
Closing hyperlink tag
`</a></p>`

Version 3 has closing tag:
https://github.com/joomla/joomla-cms/blob/3.10-dev/administrator/language/en-GB/en-GB.com_actionlogs.ini

**Comment by ghost** [comment]
please add "4.0 " at Start of Title.

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/pull/22027 has not been merged to 4.0 yet.

This should be closed per https://github.com/joomla/joomla-cms/issues/24188

**Comment by zero-24** [comment]
Closing for the reason above and #24188

**Comment by zero-24** [comment]
This is going to be fixed when the PR mention get merged up to 4.0
