### ISSUE TITLE
Optimize the flags images in /media/mod_languages/images

### ISSUE THREAD

**Issue by blueboar2** [joomla/joomla-cms#24374]
In the images in /media/mod_languages/images folder there are 161 gif images with flags. Some are ok (for example at.gif, 83 bytes), but others are quite big (tk_tm.gif is 1608 bytes, 20 times larger). I suggest to optimize images (for example, remove XMP metadata and change color number from 256 to smaller - for 18x12 flags there is no need to 256 colors).

I removed the metadata from files, and the size dropped by 20% (10K). But i don't know, how to change color number, so that quality is not lowered (for images, where less than 128/64/32/16 colours are used). Optimized images are attached.

Yes, i know, that it is a tiny improvement, but there is millions of users, so in the end it will be big change.!

**Comment by zero-24** [comment]
Hi it seams the images are not attached. Can you please send them as pull request?

**Comment by ghost** [comment]
~~@Bakual do i remember correctly similaer Discussions about Flags?~~

found: #12014

**Comment by blueboar2** [comment]
![screen shot 2019-03-27 at 12 05 25](https://issues.joomla.org/uploads/1/26feb2bd028abdcfd5464eb34cffa2ae.gif)![screen shot 2019-03-27 at 12 05 25](https://issues.joomla.org/uploads/1/d738acb887d1a258b8d3149ee39d070e.gif)![screen shot 2019-03-27 at 12 05 25](https://issues.joomla.org/uploads/1/e815125af67b19c3880c5b13a145f28f.gif)![screen shot 2019-03-27 at 12 05 25](https://issues.joomla.org/uploads/1/1a99a8078c6d7edfed167154ff7f9911.gif)![screen shot 2019-03-27 at 12 05 25](https://issues.joomla.org/uploads/1/72ee466ddddad7d344ae5a8989eac164.gif)![screen shot 2019-03-27 at 12 05 25](https://issues.joomla.org/uploads/1/fbe74a85af67d178abcde15568d10e11.gif)![screen shot 2019-03-27 at 12 05 25](https://issues.joomla.org/uploads/1/b19f98787859b610871efc6d7cbfb10b.gif)![screen shot 2019-03-27 at 12 05 ![screen shot 2019-03-27 at 12 06 11](https://issues.joomla.org/uploads/1/6b14588a3d69856b27ce0eda1965a64f.gif)25](https://issues.joomla.org/uploads/1/f2f545ac461fe3b78c2528b470b2d0cf.gif)![screen shot 2019-03-27 at 12 05 25](https://issues.joomla.org/uploads/1/5792bd3c758a34d013a77d5585035b5b.gif)![screen shot 2019-03-27 at 12 05 25](https://issues.joomla.org/uploads/1/afa325afd3463b2d31ad4abe7d8d1298.gif)![screen shot 2019-03-27 at 12 05 25](https://issues.joomla.org/uploads/1/70793e9cc7f00594f538d8098d5496b8.gif)![screen shot 2019-03-27 at 12 05 25](https://issues.joomla.org/uploads/1/8eda05a9807b732726eb0f66f0249c09.gif)![screen shot 2019-03-27 at 12 05 25](https://issues.joomla.org/uploads/1/06821acb43d57cef1f644f43ebd772de.gif)![screen shot 2019-03-27 at 12 05 25](https://issues.joomla.org/uploads/1/7e0a0c57b32671b2a4c95d363fe37f15.gif)![screen shot 2019-03-27 at 12 05 25](https://issues.joomla.org/uploads/1/38f440dc9dedc892c75a88da171d7a67.gif)![screen shot 2019-03-27 at 12 05 26](https://issues.joomla.org/uploads/1/5e385fa202c7e7414b19b6a98751004d.gif)![screen shot 2019-03-27 at 12 05 26](https://issues.joomla.org/uploads/1/faaf275a659f14f06fab4765af0506bc.gif)![screen shot 2019-03-27 at 12 05 26](https://issues.joomla.org/uploads/1/c4447a3239e048783f66ab4cf6538c35.gif)![screen shot 2019-03-27 at 12 05 26](https://issues.joomla.org/uploads/1/4df555db1a6a83ab7d53f1a1b10069de.gif)![screen shot 2019-03-27 at 12 05 26](https://issues.joomla.org/uploads/1/bb9fe8583aaea316a242a5d86a473726.gif)![screen shot 2019-03-27 at 12 05 26](https://issues.joomla.org/uploads/1/53eda958c67a42a2cfb69a5a12647460.gif)![screen shot 2019-03-27 at 12 05 26](https://issues.joomla.org/uploads/1/b2a9dfe1f833ea02cb34665edb81ce53.gif)![screen shot 2019-03-27 at 12 05 26](https://issues.joomla.org/uploads/1/113c648306badf3a61e6940c5df6c172.gif)![screen shot 2019-03-27 at 12 05 26](https://issues.joomla.org/uploads/1/3cca144292706b6c9affc12744ecb28b.gif)![screen shot 2019-03-27 at 12 05 26](https://issues.joomla.org/uploads/1/1fa95643e305e7b4c4caa8ea8dab447c.gif)![screen shot 2019-03-27 at 12 05 26](https://issues.joomla.org/uploads/1/1b1538a911d4e75ecaf69d17402fd8ea.gif)![screen shot 2019-03-27 at 12 05 26](https://issues.joomla.org/uploads/1/f21ce8426d2d1f1b0a184268f2c9606b.gif)![screen shot 2019-03-27 at 12 05 26](https://issues.joomla.org/uploads/1/98936df25ecee1b0e98860b4ce5bf967.gif)![screen shot 2019-03-27 at 12 05 26](https://issues.joomla.org/uploads/1/74fdfae7058ba7af52cd0b5e470b799a.gif)![screen shot 2019-03-27 at 12 05 26](https://issues.joomla.org/uploads/1/b7e30645d89a640939943655576c1be3.gif)![screen shot 2019-03-27 at 12 05 26](https://issues.joomla.org/uploads/1/d7c1cbe29ef18c1a2f8b15bebf06abaf.gif)![screen shot 2019-03-27 at 12 05 26](https://issues.joomla.org/uploads/1/cf8fcb72df9dfba4fbec931941d94aed.gif)![screen shot 2019-03-27 at 12 05 26](https://issues.joomla.org/uploads/1/780011543610b5c1888bf10c73ef3044.gif)![screen shot 2019-03-27 at 12 05 27](https://issues.joomla.org/uploads/1/44fe97666752902a2dcd5e9a7297f9c9.gif)![screen shot 2019-03-27 at 12 05 27](https://issues.joomla.org/uploads/1/fb54a1637ce81dc2fcc56c8cc14299cd.gif)![screen shot 2019-03-27 at 12 05 27](https://issues.joomla.org/uploads/1/1300a3e729e6d3562cee3b3251aaee51.gif)![screen shot 2019-03-27 at 12 05 27](https://issues.joomla.org/uploads/1/dcf665a5b061dcf21d7683f577e659de.gif)![screen shot 2019-03-27 at 12 05 27](https://issues.joomla.org/uploads/1/6add9b532324f1ee69727421bd63d619.gif)![screen shot 2019-03-27 at 12 05 27](https://issues.joomla.org/uploads/1/5f6cb48a00bee3d80dc81bd7ad6072a3.gif)![screen shot 2019-03-27 at 12 05 27](https://issues.joomla.org/uploads/1/b3634a1841c01f977e913d38e9ed48f6.gif)![screen shot 2019-03-27 at 12 05 27](https://issues.joomla.org/uploads/1/76e7773e4ab746e905dff65676355d30.gif)![screen shot 2019-03-27 at 12 05 27](https://issues.joomla.org/uploads/1/cfe6ab67f8779668f26804e5d3d6da04.gif)![screen shot 2019-03-27 at 12 05 27](https://issues.joomla.org/uploads/1/30331858d2693c171174aaaad1ebaaa6.gif)![screen shot 2019-03-27 at 12 05 27](https://issues.joomla.org/uploads/1/dee96b96526110b23594e3bb2313b209.gif)![screen shot 2019-03-27 at 12 05 27](https://issues.joomla.org/uploads/1/1e626be36d6aa5cba0da4e8a4054ca3c.gif)![screen shot 2019-03-27 at 12 05 27](https://issues.joomla.org/uploads/1/85d1e7b578608fbefbeb6d8b28afb446.gif)![screen shot 2019-03-27 at 12 05 27](https://issues.joomla.org/uploads/1/361aa9104600976724da6993d93a27fd.gif)![screen shot 2019-03-27 at 12 05 27](https://issues.joomla.org/uploads/1/a56bd440f96d66fe1aa206a9c79c9d68.gif)![screen shot 2019-03-27 at 12 05 27](https://issues.joomla.org/uploads/1/9303e3be3de621581a8d32a95778ff10.gif)![screen shot 2019-03-27 at 12 05 28](https://issues.joomla.org/uploads/1/3ac9118b686efe11d0a2626ee8d2df05.gif)![screen shot 2019-03-27 at 12 05 28](https://issues.joomla.org/uploads/1/a34c70528ad4273a66ad7c476a73acb5.gif)![screen shot 2019-03-27 at 12 05 28](https://issues.joomla.org/uploads/1/b6f9361c6169d3d00e7ff735f363da95.gif)![screen shot 2019-03-27 at 12 05 28](https://issues.joomla.org/uploads/1/6967bf8479f05b8e83ce325c0441f85a.gif)![screen shot 2019-03-27 at 12 05 28](https://issues.joomla.org/uploads/1/96f011c372e452217436f625a94c161a.gif)![screen shot 2019-03-27 at 12 05 28](https://issues.joomla.org/uploads/1/630864542f452ac57586bc18bc2482b0.gif)![screen shot 2019-03-27 at 12 05 28](https://issues.joomla.org/uploads/1/b8e16c4cb37a114b3a40c287d8eb5eb8.gif)![screen shot 2019-03-27 at 12 05 28](https://issues.joomla.org/uploads/1/0f57f027819a53f62ccd3204ec2892ef.gif)![screen shot 2019-03-27 at 12 05 28](https://issues.joomla.org/uploads/1/107cb01a39680cd81a99669aaefcf886.gif)![screen shot 2019-03-27 at 12 05 28](https://issues.joomla.org/uploads/1/e323ea775d8d7360e4a79d6b778f25a1.gif)![screen shot 2019-03-27 at 12 05 28](https://issues.joomla.org/uploads/1/585f10742708d6f12836ec9b95b4999c.gif)![screen shot 2019-03-27 at 12 05 28](https://issues.joomla.org/uploads/1/a53cf5893ebe8a5adf0a0ee33cb29975.gif)![screen shot 2019-03-27 at 12 05 28](https://issues.joomla.org/uploads/1/6e02634f9688b2f679069d2275e6df53.gif)![screen shot 2019-03-27 at 12 05 28](https://issues.joomla.org/uploads/1/7f18bf0c98c5f9f831ed5813ea9c2c6b.gif)![screen shot 2019-03-27 at 12 05 29](https://issues.joomla.org/uploads/1/3b7152d567c1d41d185fee7f24acbbf1.gif)![screen shot 2019-03-27 at 12 05 29](https://issues.joomla.org/uploads/1/d0a95877e4b8dc30ed78167d7c93f4a6.gif)![screen shot 2019-03-27 at 12 05 29](https://issues.joomla.org/uploads/1/3823a9e533415ee5831238bddba8d8ae.gif)![screen shot 2019-03-27 at 12 05 29](https://issues.joomla.org/uploads/1/6da7f60cf2b12598a21fa2d0712e2887.gif)![screen shot 2019-03-27 at 12 05 29](https://issues.joomla.org/uploads/1/55bd76943efbdc94b231256367916d22.gif)![screen shot 2019-03-27 at 12 05 29](https://issues.joomla.org/uploads/1/f583c463fa518b562480ce510681bbd6.gif)![screen shot 2019-03-27 at 12 05 29](https://issues.joomla.org/uploads/1/64a4887113eb5f34deb8b60835cb03b1.gif)![screen shot 2019-03-27 at 12 05 29](https://issues.joomla.org/uploads/1/d1ebb96544eefd47fa0bc8e14cfdd170.gif)![screen shot 2019-03-27 at 12 05 29](https://issues.joomla.org/uploads/1/f7b771764b5f6d143ec7e7e2411627c3.gif)![screen shot 2019-03-27 at 12 05 29](https://issues.joomla.org/uploads/1/dc2c5899c00071f63baa9d07b17f24c7.gif)![screen shot 2019-03-27 at 12 05 29](https://issues.joomla.org/uploads/1/6b922fe362767bbb4303034816a494b2.gif)![screen shot 2019-03-27 at 12 05 29](https://issues.joomla.org/uploads/1/ee680349f2d87c80a89879bdf95bcd0c.gif)![screen shot 2019-03-27 at 12 06 11](https://issues.joomla.org/uploads/1/d0655888fb6fac087bfff2bade8282b7.gif)![screen shot 2019-03-27 at 12 06 12](https://issues.joomla.org/uploads/1/d538d1e247b89348efb5c5634dcf7da5.gif)![screen shot 2019-03-27 at 12 06 12](https://issues.joomla.org/uploads/1/e67d98f5b5ee6f2c055dc3fd46e9f176.gif)![screen shot 2019-03-27 at 12 06 12](https://issues.joomla.org/uploads/1/590ae212a945e707d0d435dd2f893dd2.gif)![screen shot 2019-03-27 at 12 06 12](https://issues.joomla.org/uploads/1/644a3cef75aae38983999c1756b73cd7.gif)![screen shot 2019-03-27 at 12 06 12](https://issues.joomla.org/uploads/1/190186d13367c58390fc1dc836e87669.gif)![screen shot 2019-03-27 at 12 06 12](https://issues.joomla.org/uploads/1/59331b36c486204ce0f81092148db341.gif)![screen shot 2019-03-27 at 12 06 12](https://issues.joomla.org/uploads/1/2795d2a25c95d85ef5a3acd50fb7b6e3.gif)![screen shot 2019-03-27 at 12 06 12](https://issues.joomla.org/uploads/1/39a17c4da0138414bd0a549679d08dcb.gif)![screen shot 2019-03-27 at 12 06 12](https://issues.joomla.org/uploads/1/4ea611e0fd716e9fc465a6625140cb1b.gif)![screen shot 2019-03-27 at 12 06 12](https://issues.joomla.org/uploads/1/0dd8be5a52f8e4bd36c623243b50dd8e.gif)![screen shot 2019-03-27 at 12 06 12](https://issues.joomla.org/uploads/1/befad3b0b36a6f03eda0b23fc2ed5629.gif)![screen shot 2019-03-27 at 12 06 12](https://issues.joomla.org/uploads/1/37b650042edc234a09bb146004f835ea.gif)![screen shot 2019-03-27 at 12 06 12](https://issues.joomla.org/uploads/1/64331e3c312715bb9c79676675d1759f.gif)![screen shot 2019-03-27 at 12 06 12](https://issues.joomla.org/uploads/1/5ab0b4da732dde525456adfe59b28520.gif)![screen shot 2019-03-27 at 12 06 12](https://issues.joomla.org/uploads/1/03bc0e9e3a7ef1044fd2feece8acf8f5.gif)![screen shot 2019-03-27 at 12 06 12](https://issues.joomla.org/uploads/1/62f6eee460a48621b7d9e9b03015fdf1.gif)![screen shot 2019-03-27 at 12 06 12](https://issues.joomla.org/uploads/1/6b17983bbca441584917dd57dccaeb32.gif)![screen shot 2019-03-27 at 12 06 12](https://issues.joomla.org/uploads/1/3bc886b1c46f51ca9b6e3068eeb993bf.gif)![screen shot 2019-03-27 at 12 06 13](https://issues.joomla.org/uploads/1/0aa5222b8f9dc82b1743afbabd9efa91.gif)![screen shot 2019-03-27 at 12 06 13](https://issues.joomla.org/uploads/1/d9ee77d3994f959b343f0f21fe08ea6e.gif)![screen shot 2019-03-27 at 12 06 13](https://issues.joomla.org/uploads/1/76d7d9c640120a21d60ff5ade9fd7250.gif)![screen shot 2019-03-27 at 12 06 13](https://issues.joomla.org/uploads/1/981be02b5eefe1c054a38cd653f5f06f.gif)![screen shot 2019-03-27 at 12 06 13](https://issues.joomla.org/uploads/1/96a80fade5d97d82d1a8854f5ff991e2.gif)![screen shot 2019-03-27 at 12 06 12](https://issues.joomla.org/uploads/1/50c3dd1031a6ac2ac721ead6736f53ed.gif)![screen shot 2019-03-27 at 12 06 13](https://issues.joomla.org/uploads/1/99f46ac4e6255160f28a5a84c1f6f375.gif)![screen shot 2019-03-27 at 12 06 13](https://issues.joomla.org/uploads/1/e664bf8379da2082b0fab0f9540e1523.gif)![screen shot 2019-03-27 at 12 06 13](https://issues.joomla.org/uploads/1/da2c084d227401c71465683f40495097.gif)![screen shot 2019-03-27 at 12 06 13](https://issues.joomla.org/uploads/1/894ac12a0b9c49828af2db02e68091c4.gif)![screen shot 2019-03-27 at 12 06 13](https://issues.joomla.org/uploads/1/7063ba5a1c56b4980fedbe8a0348afbb.gif)![screen shot 2019-03-27 at 12 06 13](https://issues.joomla.org/uploads/1/8c27b58a667e6ff2ab0729450b8c3a93.gif)![screen shot 2019-03-27 at 12 06 13](https://issues.joomla.org/uploads/1/cfc4bc3df9d4852ea533eda6946d0524.gif)![screen shot 2019-03-27 at 12 06 13](https://issues.joomla.org/uploads/1/471ef0fb13b5a1c7afe5d389768b4413.gif)![screen shot 2019-03-27 at 12 06 13](https://issues.joomla.org/uploads/1/eeeda653347cbcda97fe0e961224c584.gif)![screen shot 2019-03-27 at 12 06 13](https://issues.joomla.org/uploads/1/7fc39729aaf413b197cac7f8a7ae2ecd.gif)![screen shot 2019-03-27 at 12 06 13](https://issues.joomla.org/uploads/1/eff785a1b26275f075ca6fef68fcda3d.gif)![screen shot 2019-03-27 at 12 06 13](https://issues.joomla.org/uploads/1/427249480fda86aa1d19d2522bad8612.gif)![screen shot 2019-03-27 at 12 06 14](https://issues.joomla.org/uploads/1/ab265540b8a1f6204ed23752504c9dbd.gif)![screen shot 2019-03-27 at 12 06 14](https://issues.joomla.org/uploads/1/1f62316269f24834e3c08e4db401aa78.gif)![screen shot 2019-03-27 at 12 06 14](https://issues.joomla.org/uploads/1/81e9542f9262284b5a07b5d30e7131d7.gif)![screen shot 2019-03-27 at 12 06 14](https://issues.joomla.org/uploads/1/da6acc6857b547005e7c2c6ab325058f.gif)![screen shot 2019-03-27 at 12 06 12](https://issues.joomla.org/uploads/1/f95b8f2ea3d15c26659fe60367424ec1.gif)![screen shot 2019-03-27 at 12 06 14](https://issues.joomla.org/uploads/1/89367745c127044ad950ee5f1755d3b3.gif)![screen shot 2019-03-27 at 12 06 14](https://issues.joomla.org/uploads/1/c74fa2f9dee916b9ee6990c27f1954ae.gif)![screen shot 2019-03-27 at 12 06 14](https://issues.joomla.org/uploads/1/89c7d3cdc3289895aa93084393aae532.gif)![screen shot 2019-03-27 at 12 06 14](https://issues.joomla.org/uploads/1/b7c1068ad4fa7c61dbbcbaa90b51c15d.gif)![screen shot 2019-03-27 at 12 06 14](https://issues.joomla.org/uploads/1/8db6e158433afb0647cb43feeea964da.gif)![screen shot 2019-03-27 at 12 06 14](https://issues.joomla.org/uploads/1/60be52d2294281df1858c94604123229.gif)![screen shot 2019-03-27 at 12 06 14](https://issues.joomla.org/uploads/1/0558fb2373643d20bae5410544bb701f.gif)![screen shot 2019-03-27 at 12 06 14](https://issues.joomla.org/uploads/1/0044b088134822743191dac818790f5d.gif)![screen shot 2019-03-27 at 12 06 14](https://issues.joomla.org/uploads/1/626b92e5a170404ae82c859860492c6a.gif)![screen shot 2019-03-27 at 12 06 14](https://issues.joomla.org/uploads/1/3d2851d9bda7be9f76d689ef6d93e7ac.gif)![screen shot 2019-03-27 at 12 06 14](https://issues.joomla.org/uploads/1/1c821f1286b13e7625cee22ba178e92e.gif)![screen shot 2019-03-27 at 12 06 14](https://issues.joomla.org/uploads/1/aa3fb301bd1056c3c1e5e64e903a672d.gif)![screen shot 2019-03-27 at 12 06 14](https://issues.joomla.org/uploads/1/a31c0e013b788f8aad94d004f822444f.gif)![screen shot 2019-03-27 at 12 06 14](https://issues.joomla.org/uploads/1/2e728b2a746d12da780359198c032e5a.gif)![screen shot 2019-03-27 at 12 06 15](https://issues.joomla.org/uploads/1/2eda5ff93b771379f963a7643ac237ba.gif)![screen shot 2019-03-27 at 12 06 15](https://issues.joomla.org/uploads/1/9ec3b2edb81775f121c478d3fa189e40.gif)![screen shot 2019-03-27 at 12 06 15](https://issues.joomla.org/uploads/1/7f7362b48f6b11e975a9878b3d56de19.gif)![screen shot 2019-03-27 at 12 06 15](https://issues.joomla.org/uploads/1/0c0ce791f5473415a8535bff201023ef.gif)![screen shot 2019-03-27 at 12 06 15](https://issues.joomla.org/uploads/1/2013a50189ca78546d75e9711299126d.gif)![screen shot 2019-03-27 at 12 06 15](https://issues.joomla.org/uploads/1/51dcaf66881b1f6b45611d3dca7b1d17.gif)![screen shot 2019-03-27 at 12 06 15](https://issues.joomla.org/uploads/1/9231df1dda04932ae41982ad5df1110d.gif)![screen shot 2019-03-27 at 12 06 15](https://issues.joomla.org/uploads/1/8979856614c41904f3632993a791f2f1.gif)![screen shot 2019-03-27 at 12 06 15](https://issues.joomla.org/uploads/1/a04ebbe1e48409955b3d02a0fd701e2d.gif)![screen shot 2019-03-27 at 12 06 15](https://issues.joomla.org/uploads/1/5ce3f5857b146ff78e69ec26f5cf83cb.gif)![screen shot 2019-03-27 at 12 06 15](https://issues.joomla.org/uploads/1/9dd3cd1ad2cba8112cc83bcc55eb6c64.gif)![screen shot 2019-03-27 at 12 06 15](https://issues.joomla.org/uploads/1/2d037f803f055be8d43e8eabd6ecad07.gif)![screen shot 2019-03-27 at 12 06 15](https://issues.joomla.org/uploads/1/eb742db3167afb86a76b8cd53ca9bd32.gif)![screen shot 2019-03-27 at 12 06 15](https://issues.joomla.org/uploads/1/8e3a3635a3404d11b1ec95ab3f129c3b.gif)![screen shot 2019-03-27 at 12 06 15](https://issues.joomla.org/uploads/1/cf167c0ca59b9bb607cab8f7906ec983.gif)![screen shot 2019-03-27 at 12 06 15](https://issues.joomla.org/uploads/1/532d5374bf30653587ecbd01b920cd69.gif)![screen shot 2019-03-27 at 12 06 15](https://issues.joomla.org/uploads/1/4deeadf9ce278af628c9feeb144e260c.gif)![screen shot 2019-03-27 at 12 06 16](https://issues.joomla.org/uploads/1/f95468b2088b21bf2b039d8c6abe3b89.gif)![screen shot 2019-03-27 at 12 06 16](https://issues.joomla.org/uploads/1/73bc27ec35219cce37db7d600ed144f9.gif)![screen shot 2019-03-27 at 12 06 16](https://issues.joomla.org/uploads/1/81eaf4e794df93f6c1737c565d2329bd.gif)![screen shot 2019-03-27 at 12 06 16](https://issues.joomla.org/uploads/1/721c6a131b8fd9d9a82c14ab48183ed4.gif)![screen shot 2019-03-27 at 12 06 16](https://issues.joomla.org/uploads/1/5ab3b306bdcee9d0f7f1343155b9869e.gif)![screen shot 2019-03-27 at 12 06 16](https://issues.joomla.org/uploads/1/7d4f5557201c1873bb0663f343488684.gif)![screen shot 2019-03-27 at 12 06 16](https://issues.joomla.org/uploads/1/accb4bb006840ef19c2301fee04a997f.gif)![screen shot 2019-03-27 at 12 06 16](https://issues.joomla.org/uploads/1/aaf45c7efd2072502dd18167738ac684.gif)![screen shot 2019-03-27 at 12 06 16](https://issues.joomla.org/uploads/1/206011d79b2712e294715060f670052b.gif)![screen shot 2019-03-27 at 12 06 16](https://issues.joomla.org/uploads/1/685096032c49775e124f706f8b84e561.gif)![screen shot 2019-03-27 at 12 06 16](https://issues.joomla.org/uploads/1/59da9c8582d957d28affc300ff997e54.gif)![screen shot 2019-03-27 at 12 06 16](https://issues.joomla.org/uploads/1/b51ab11a1d20c3936f3f0b2442606304.gif)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24374">issues.joomla.org/tracker/joomla-cms/24374</a>.</sub>

**Comment by blueboar2** [comment]
Send them as pull request on github?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24374">issues.joomla.org/tracker/joomla-cms/24374</a>.</sub>

**Comment by blueboar2** [comment]
I've uploaded it to http://gtrk-kurgan.ru/images.zip. Are these ok?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24374">issues.joomla.org/tracker/joomla-cms/24374</a>.</sub>

**Comment by zero-24** [comment]
> Send them as pull request on github?

Yes: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

at the path where the images are you should be able to upload them using github UI too.

**Comment by blueboar2** [comment]
Done. https://github.com/joomla/joomla-cms/pull/24378<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24374">issues.joomla.org/tracker/joomla-cms/24374</a>.</sub>

**Comment by ghost** [comment]
closed as having Pull Request #24378
