### ISSUE TITLE
Multi category - blog layout view

### ISSUE THREAD

**Issue by yozmag** [joomla/joomla-cms#24383]
### Is your feature request related to a problem? Please describe.
We have the need to have a page with category blog layout but select several categories that are not nested. This also allow to have a rss feed for several categories 

### Describe the solution you'd like
I have made a copy of the feature view (This allow several categories) and the featured model( comment line ('filter.frontpage', true);)  register the new router and it's working.

### Additional context
Could this go to the joomla core, I think this is useful for others.

**Comment by ghost** [comment]
this is useful

**Comment by Bakual** [comment]
Just use tags to achieve what you want. That should do the trick.
A real multicategory (not nested categories) view isn't possible with Joomla. You get issues with ACL and routing.

**Comment by brianteeman** [comment]
I share @Bakual concerns BUT without seeing the code it is  stab in the dark. Please submit a Pull Request with your changes so they can be evaluated

**Comment by yozmag** [comment]
I will make a pull request for review, but @Bakual concerns are unfunded because this is just other view of articles, there is no change in the article, just like feature blog view but for items that are not feature, acl and routing just the same.

**Comment by yozmag** [comment]
Add a PR #24412 for this

**Comment by ghost** [comment]
closed as having Pull Request #24412
