### ISSUE TITLE
[4.0] Custom HTML Module don’t add a module class added in the module admin - Only show mod-custom custom?

### ISSUE THREAD

**Issue by Chacapamac** [joomla/joomla-cms#24388]
### Steps to reproduce the issue

Add a custom module class in the module admin — e.g. myclass

### Expected result
See the class added to the normal “<div class="mod-custom custom">“

Like “`<div class="mod-custom custom myclass">“`

### Actual result
Custom class is no show
“<div class="mod-custom custom">“

### System information (as much as possible)
Mamp Local Installation - php 7.2.1

**Comment by brianteeman** [comment]
What is the module chrome for the position

**Comment by Chacapamac** [comment]
Probably my bad as it is a custom position, it is xhtml<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24388">issues.joomla.org/tracker/joomla-cms/24388</a>.</sub>

**Comment by Chacapamac** [comment]
custom position<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24388">issues.joomla.org/tracker/joomla-cms/24388</a>.</sub>

**Comment by Chacapamac** [comment]
If I look at my working backup the style/chrome was xhtml before?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24388">issues.joomla.org/tracker/joomla-cms/24388</a>.</sub>

**Comment by ghost** [comment]
Please add "[4.0] " at Start of Title.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24388">issues.joomla.org/tracker/joomla-cms/24388</a>.</sub>

**Comment by brianteeman** [comment]
I cannot replicate this

**Comment by ghost** [comment]
closed as solved elsewhere. @Chacapamac please reopen if i failed.

**Comment by Chacapamac** [comment]
Franz, you said
> Please add "[4.0] " at Start of Title.
and
> closed as solved elsewhere.

I’m not sure... what is the solution ?

**Comment by ghost** [comment]
> I cannot replicate this

@Chacapamac this was between my 2 comments :-)
