### ISSUE TITLE
Activate user without login

### ISSUE THREAD

**Issue by tntmartin** [joomla/joomla-cms#24381]
### Steps to reproduce the issue
I hope this is the right place to request changes.

After Joomla 3.8.12 it's no longer possible to activate new user by link in e-mail.
Now an additional requirement to login before clicking on the link. Is it resonable to make this security design optinal in future versions so you can turn it off? I mean you have the option for users to get activated directly on registration, then I don't see it as a big flaw to make it optional for admins to directly activate users by link in e-mail, without login.

https://developer.joomla.org/security-centre/754-20181004-core-acl-violation-in-com-users-for-the-admin-verification.html

**Comment by mbabker** [comment]
This cannot be turned off without re-introducing the referenced security issue, even if it is an option turned on by the user's choice it has security repercussions.  Issue should be closed as a won't fix.
