### ISSUE TITLE
tag list field show

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#24387]
### Steps to reproduce the issue

create items tag and field

click on tag and you get list of tagged items with all fields shown

### Expected result

get only tagged items list without fields shown

### Actual result

list of tagged items with all fields display

### System information (as much as possible)

joomla 3.9.4
protostar template

**Comment by brianteeman** [comment]
Please post some screenshots

**Comment by ghost** [comment]
@brianteeman A Solution is stated above. Could you please post screenshots for not reproducing the issue in joomla 3.9.4 protostar template?

**Comment by brianteeman** [comment]
I still don't understand the original post. That's why I asked for some screenshots

**Comment by ghost** [comment]
@brianteeman you have article with tag and field?

**Comment by ghost** [comment]
@Milglius can you please provide more Information, so willing Volunteers may understand the Issue? Maybe a Step-by-Step-Description, Screenshots or Screencast.

**Comment by ghost** [comment]
a Step-by-Step-Description is stated above.

@franz-wohlkoenig you have article with tag and field?

**Comment by brianteeman** [comment]
Please close this. It's a simple request for screenshot so we can see the issue more clearly. As the op refuses to do that then we can't help

**Comment by ghost** [comment]
It's a simple request @brianteeman do you have article with tag and field?

**Comment by ghost** [comment]
@Milglius sorry, you let me no choice than closing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24387">issues.joomla.org/tracker/joomla-cms/24387</a>.</sub>

**Comment by ghost** [comment]
big sorry to @brianteeman and @franz-wohlkoenig just reinstalled joomla and now it is fixed :)
