### ISSUE TITLE
[4.0] Joomla 4 Backend Design Reloaded

### ISSUE THREAD

**Issue by Chacapamac** [joomla/joomla-cms#24380]
### Steps to reproduce the issue

Open Joomla 4

### Expected result

Being in a pro, ergonomically correct interface

### Actual result

Far from it

### Additional comments
I wrote the same things in Joomla forum to try have the community talk about one, if not the most important aspect of the release of Joomla 4. —> https://forum.joomla.org/viewtopic.php?f=803&t=970614
 
You and I, we know Joomla is simply the best CMS out there. Sadly, even if you get the best system ever it mean nothing if the administration interface is poor it will push away first time user & developers alike & negate all the great efforts made to put it together.

## ABOUT THE NEW DESIGN
![screen shot 2019-03-27 at 13 45 00](https://issues.joomla.org/uploads/1/98a081bddb81ac3a2b45b17d9ff5f924.jpg)

Sorry for the designer(s) behind it but it is important to see the weakness of this interface. I learn design with 2 high end designers in my life (and my father) and I thank them everyday to show me my mistakes and help me understand the logic behind the design.

• Here no logic, no unification of the design of the top and left menu that have now 2 completely different scheme where the top menu now ressemble more the style of the infos page.

• The left menu, lost in is corner, is now the main (Strong) focus point leaving the top menu, the quick icons and the infos page in a washout meli-melo of disparate blocks that have no real homogeneity. 

• The top white background is simply boring and the cute, lively Joomla logo is a simple dot in the corner.

• All that in a uncertain palish light blue background that, I hope, will be replace by a neutral gray to permit the infos to stand out.

• The color scheme is cold and uninviting. 

This is simply bad, between me and my 2 boss designers we cumulate close to 150 years of design, typography and branding and I hope, a good sens of what work and what don’t. 

This, sadly, is simply not acceptable.

I LOVE Joomla and I Care to much to let that go

## PROPOSE DESIGN
_This is base on an older version of the admin interface_

![screen shot 2019-03-27 at 13 49 59](https://issues.joomla.org/uploads/1/f874168ad98cbf3d3c791b61f1e75146.jpeg)
**What I change:**

• I replace the cool blue used for the top/left menu by the more warmer friendly blue use in the old presentation - Make the Backend Atmosphere less glacial ....

• Also I replace pale blue background by a neutral gray background to put the content stand out. By going neutral you got a better background that will not distort perception of images and attire attention — This is why Photoshop pros always use a neutral gray as background

• Remark that I add to the first level menu few items that NEED to be there and not hidden to wherever...
1- Global configuration
Note: This menu need to be front & frontmost, nobody will argue with me, I think :)

2- Extensions (Modules & plugins)
Note:Front & frontmost, and permit to reassemble the pieces (Modules, Plugins) that you can add to a Joomla site to customize it

• I also change the order to rebalance the importance of the left menu

• In the left menu I add a left triangle at the “System” item as I have no ideas for what reason, suddenly, we should have another menu system or different way to view content on this small menu to end up in the messier, unorganize System Page. It look like the designer when out of ideas and trow everything in that punch bol that make me sick already. The Golden Rules of successful interface design, homogeneity and predictability is just trow by the windows, common people????? 

• I add a direct Top buttons to Plugins (Inside Extensions), This is as much important as Modules or even Component. Need to be first level.

• I also put the Multilingual Sample Data where it should be in a normal left to right order of reading, before the Blog Sample as in a multilingual site the Blog data SHOULD NOT be installed before the Multilingual.

• I also, in the Multilingual data I Add hypothetical Direct links to the Languages Install and The Content Languages — We need to think to first time users, they are the one that will stick or not to Joomla

• Also I take out all drop-shadow as this is a big no-no in flat design, not needed here anyway

Hopefully this will start the discussion.

**Comment by ghost** [comment]
There is a Backend-Design in Work > @coolcat-creations

**Comment by Chacapamac** [comment]
**Where can we see that ?**
— So far, Joomla Alpha-8 still drag that Sad “NEW DESIGN” Hopefully it is not what you are talking about?

**Comment by ghost** [comment]
its beeing developed in a private Repository, as far a s i know - please search for @coolcat-creations Issues, where she wrote about it.

**Comment by ghost** [comment]
https://volunteers.joomla.org/teams/j4-backend-template-working-group

**Comment by Chacapamac** [comment]
After checking, Yes Elisa is the author of that SAD “NEW DESIGN” an the Joomla DEV are going for it. Sad Day for Joomla. 

I see that the effort I put to change the course of that mistake is useless.

Go ahead and make My Joomla 4 be rejected at the plate. Sad Day for Joomla.

**Comment by micker** [comment]
i understand but htink about this => you can create your own admin template ! sometime we think to have the best solution but community doesn't want this .... not a sad day just a desagre ...
check wordpress community and guthemberg .... that realy a sad day because no real solution wihtout a fork
just a note about your design, no realy effective for accessibility ... too much color in many place => if we check contrast point by point it's good but in global its bad

**Comment by bembelimen** [comment]
Sorry @Chacapamac but 7 of your 10 bullet points have nothing to do with the template, it's content (yes, displayed menu items and module orders are not task of the template). So we have the following opinions left:

> • I replace the cool blue used for the top/left menu by the more warmer friendly blue use in the old presentation - Make the Backend Atmosphere less glacial ....

With the new template it's possible to configurate your colorset by parameters.

> • Also I replace pale blue background by a neutral gray background to put the content stand out. By going neutral you got a better background that will not distort perception of images and attire attention — This is why Photoshop pros always use a neutral gray as background

Same here, no problem to configurate your own colorset in the params

> • Also I take out all drop-shadow as this is a big no-no in flat design, not needed here anyway

If you think, no drop-shadow should be used, create a PR against the new backend template repo.

Thanks for your feedback, but please try to separate Joomla! content functionallity (=> if it should change, make a PR against the 4.0-dev) with template functionallity.

**Comment by Chacapamac** [comment]
Fantastic that you can modify the color, great, but painting over a broken UI/UX will not change the fact that overall ergonomic and ease of use is a mess. 

A big point responsible of the success or failure of any CMS will always be these few first seconds or minutes a new user, a web site developer will discover the interface. 
If it’s easy, comfortable and professionally made, they will stick to Joomla.

If it’s confusing and amateurish, as it is now they will drop Joomla for another CMS that care about their end users. They will not even care that you make your menu pink.

I have 45 years of Design, Architecture and lately (20 Years) in software and web site ergonomics optimization. 

The problems I seeI are not suggestive, they are basic design and interface mistakes.

**I decide to go to war with this mistake just because I Love Joomla.**

**Look at the growing negative comments of People using Joomla for ages and newer aficionados alike around that terrible design on my post** —> https://forum.joomla.org/viewtopic.php?f=803&t=970614

**Comment by bembelimen** [comment]
Did you take any actions suggested in the post above or are you just here to express your opinion?

Linking the same bullet points again and again does not make them any more relevant for the backend template...

**Comment by HLeithner** [comment]
@Chacapamac didn't you see the design before? it has been published end of 2017 https://magazine.joomla.org/issues/issue-nov-2017/item/3289-episode-iv-a-new-user-interface-for-the-joomla-backend

Now its a bit late to say everything is bad because the template team has create a new modern template.

Changes are hard and even I will miss the horizontal main menu but for people not doing joomla since 10 years it's easier as it is similar to many other applications.

But nobody holding you to make suggestions on how to make it better.

**Comment by C-Lodder** [comment]
> Also I take out all drop-shadow as this is a big no-no in flat design, not needed here anyway

Perhaps you may want to consider the user experience and a11y on this matter. When you have a light dropdown on a light background, (e.g white on white), using a dropdown shadow makes it easier for the user to see the dropdown menu.

A prime example:

![screeny](https://user-images.githubusercontent.com/2019801/55099318-67aae100-50b7-11e9-8acc-06db28e2a830.png)

This is also done by (not just with dropdowns) Facebook, Youtube, Twitter, Airbnb, Github, LinkedIn, Huawei and many more.

> The color scheme is cold and uninviting

Why so?

> Go ahead and make My Joomla 4 be rejected at the plate. Sad Day for Joomla.

You've mentioned multiple times how much you love Joomla and the experience you posses as a designer, so why not put it to use and join the template team?

And from a user experience perspective and a11y, I assume you have evidence to back up all your points.

Don't get me wrong, I feel there are certain aspects of the site that provide me (as a power user), a poor user experience, such as the new System page and long labels on the installation.

**Comment by ot2sen** [comment]
Look @Chacapamac it is clear that change isn´t a strenght of yours.
Nevertheless, change is what brings joomla forward.
You said your piece here, and sent us to forum thread to validate your
concern. It didn´t. All it did was make us click the signature link of
yours and visit your site.
This didn´t bring extra validity to your UX/UI/Design concerns, at all. You
sent me back to another design era. Last decade was fine, but joomla is
looking into the next decade.
I would suggest you to take a step back, look at it from a distance and try
see waht the designers see. Change is a fun beast to get familiar with over
time. I believe you will get it too :)
The accessibility and UI improments here, for all users, matters a lot more
that colours good for your individual eye ;)

**Comment by ghost** [comment]
Closed as main Points seems said - if i'm failed, please reopen.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24380">issues.joomla.org/tracker/joomla-cms/24380</a>.</sub>

**Comment by Chacapamac** [comment]
>  it is clear that change isn´t a strength of yours. 
Nothing to do with change, but the square wheel will never work. 

NOTE:
Design are subjective but people go to university to learn the do and don’t and basics rules that are recognize to make good or bad design — UX is always the same, the user experience is king and everything should start there. Before any design the UX should be on paper. The UI (Design) should now clothes and help the UX.

- If the UX is wrongly established, nothing else matter even with the better design


>  All it did was make us click the signature link of yours and visit your site. This didn´t bring extra validity to your UX/UI/Design concerns, at all. You sent me back to another design era. Last decade was fine,

Yep you right that Joomla 1.5 site is in the same state and slowly loose working part when I finished it I don’t know how many many year ago (I think more like 2 decades) from there I never have the time or the needs to make another one. From there, I have my fill of good customers. But finally I should  have a brand new site this year or 2020.

You got the people that listen and think & you have the people that seem to listen.

**Comment by coolcat-creations** [comment]
Hello @Chacapamac - I received your mail through the volunteers portal but there was no reply adress, please provide a communication canal to lead you to the tasks that are currently important in Joomla 4 Backend and to see if you are able to help with those.

**Comment by ghost** [comment]
I am with Chacapamac  , this backend design is absurd, Ill do my own template... no customer on earth will accept this design

**Comment by Chacapamac** [comment]
My email; is p.toulze@grafcomm.ca
Ready to help...
Everything happen on that Joomla forum post
https://forum.joomla.org/viewtopic.php?f=803&t=970614
