### ISSUE TITLE
Expected bahavior Register a new user in Joomla fornt-end

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#24406]
### Steps to reproduce the issue

Register a new user in Joomla fornt-end.

### Expected result

no documentation?

From my point of view: not Expected bahavior.

### Actual result

After clkicking the activation link in email to new user: Activated is not green:

screenshot by @ReLater in #24259

### System information (as much as possible)

joomla 3.9.4
moder sef on

### Additional comments

where to find joomla expected bahavior on Both the "Enabled" and "Activated" columns?

what diferencies have "Enabled" and "Activated" ?

**Comment by brianteeman** [comment]
Please close - question has been asked and answered

**Comment by ghost** [comment]
question has been **never** answered

**Comment by ghost** [comment]
its very strange why @brianteeman  trys to hide joomla bugs

if the joomla policy is to hide bugs I ll use wordprees instead

**Comment by Bakual** [comment]
Closing as expected behavior.
This also answers the question "why Brian tries to hide Joomla bugs". He doesn't because there is no bug.

If you prefer Wordpress over Joomla, feel free to use it. Always use the tool which fits your needs best.

**Comment by ghost** [comment]
So bug in joomla is expected behavior, no documentation in joomla is expected behavior. If you find bug in joomla just write there is no bug and close the joomla issue.

In that case I prefer Wordpress

can you recommend me tool to migrate from buggy outdated joomla 3,9,5 to modern Wordpress 5,1,1?


@Bakual what is expected behavior?

where to find joomla expected bahavior on Both the "Enabled" and "Activated" columns?

what diferencies have "Enabled" and "Activated" ?

**Comment by Bakual** [comment]
Documentation can be found on https://docs.joomla.org. There are quite a few pages relating to user account activation. Support can be found on https://forum.joomla.org.
This isn't the place for both of those. An issue can be openend here if there is a bug or you're missing a feature. But you just have a different understanding of what is expected, that's not a bug.

**Comment by ghost** [comment]
@Bakual in links you provided there are 0 information on :  joomla docs is outdated and joomla forum is dead

joomla expected bahavior on Both the "Enabled" and "Activated" columns?

what diferencies have "Enabled" and "Activated" ?

So bug in joomla is expected behavior, no documentation in joomla is expected behavior. If you find bug in joomla just write there is no bug and close the joomla issue.

In that case I prefer Wordpress,

can you recommend me tool to migrate from buggy outdated joomla 3,9,5 to modern Wordpress 5,1,1?

**Comment by Bakual** [comment]
> can you recommend me tool to migrate from buggy outdated joomla 3,9,5 to modern Wordpress 5,1,1?

Of course not.

I'm locking this issue as it's written more than once already where you can find your answers.
