### ISSUE TITLE
tagged items articles titles list without fields display bug

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#24405]
### Steps to reproduce the issue

in frontend create article with tag and fields

click on published article tag "brian sit"

you get example url  /component/tags/tag/brian-sit

you get list of articles that have "brian sit" tag

### Expected result

the list of articles titles are displayd

### Actual result

the list of articles titles including fields are displayed

### System information (as much as possible)

joomla 3.9.4
protostar template

### Additional comments

It's a simple request @brianteeman and @franz-wohlkoenig do you have article with tag and field?

I do not have permission to post screenshot, sorry

**Comment by brianteeman** [comment]
please close for reasons already explained several times

**Comment by ghost** [comment]
question has been never answered

its very strange why @brianteeman trys to hide joomla bugs

if the joomla policy is to hide bugs I ll use wordprees instead

**Comment by ghost** [comment]
Closed in favor Discussion #24387

**Comment by ghost** [comment]
So bug in joomla is expected behavior, no documentation in joomla is expected behavior. If you find bug in joomla just write there is no bug and close the joomla issue.

In that case I prefer Wordpress

can you recommend me tool to migrate from buggy outdated joomla 3,9,5 to modern Wordpress 5,1,1?

**Comment by ghost** [comment]
big sorry to @brianteeman and @franz-wohlkoenig just reinstalled joomla and now this issue is fixed :)
