### ISSUE TITLE
Install the Hound GitHub App

### ISSUE THREAD

**Issue by gylaz** [joomla/joomla-cms#24401]
### Is your feature request related to a problem? Please describe.

Hound currently cannot review this repo because it can't set the Pull Request status.

### Describe the solution you'd like

Install the [Hound GitHub app](https://github.com/apps/hound) which would address the issue.
An admin of this repo would have to simply follow the link, click "Configure" and install Hound app on just this one repository. GitHub apps is what GitHub is trying to move everyone to.

### Additional context

I noticed errors on this repository on the Hound's side, and figured I'd reach out.

**Comment by jeckodevelopment** [comment]
@HLeithner @wilsonge @mbabker

**Comment by zero-24** [comment]
Should be active now again.

**Comment by wilsonge** [comment]
Looks good to me now too. Thanks for reaching out!
