### ISSUE TITLE
Registration Email Activation Problem, Only JSON Message

### ISSUE THREAD

**Issue by diolegend** [joomla/joomla-cms#24419]
### Steps to reproduce the issue
We have to go: [https://www.ingrossoborseonline.com/en/](https://www.ingrossoborseonline.com/en/) and click the register button, insert all the details of account and finally click the register button.

We will get an email message from info@ingrossoborseonline.com which tell me to click the link for email verification.

And will show this message and nothing else...

![JSON_Account_Activation_Problem](https://user-images.githubusercontent.com/18214809/55276022-54ce2180-52ee-11e9-9345-70da0508fecf.png)

### Expected result

The normal message

### Actual result

![JSON_Account_Activation_Problem](https://user-images.githubusercontent.com/18214809/55276026-5f88b680-52ee-11e9-86e3-40f778eb5f07.png)

### System information (as much as possible)

Impostazione | Valore
-- | --
 
PHP attivo su | Linux webd014.cluster023.gra.hosting.ovh.net 4.14.66-ovh-vps-grsec-zfs-classid #1 SMP Thu Aug 23 15:15:40 CEST 2018 x86_64
Database Type | mysql
Versione database | 5.6.39-log
Collation database | latin1_swedish_ci
Collation connessione database | utf8mb4_general_ci
Versione PHP | 7.2.14
Web Server | Apache
WebServer interfaccia PHP | fpm-fcgi
Versione di Joomla! | Joomla! 3.9.4 Stable [ Amani ] 12-March-2019 15:00 GMT
Versione piattaforma Joomla! | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36

**Comment by ReLater** [comment]
Please ask in a forum for help and close your issue here on GitHub. The issue that you describe isn't a Joomla core issue. You're using JoomShopping and an AJAX-driven registration form that is not part of Joomla core.

I can't reproduce your issue with a "normal" Joomla.

**Comment by ghost** [comment]
Closed for Reasons stated above ([Forum](https://forum.joomla.org/)).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24419">issues.joomla.org/tracker/joomla-cms/24419</a>.</sub>
