### ISSUE TITLE
Web Links in Search results open in parent window instead of new window (global)

### ISSUE THREAD

**Issue by kofaysi** [joomla/joomla-cms#24415]
### Steps to reproduce the issue

Set Global configuration > Web Links > Target > Open in new window
Search (finder / smart search) for a weblink name which has Target set to Global
Open the link of the weblink in the search results.

### Expected result

Opens in new window.
Link structure should be:
`index.php?option=com_weblinks&task=weblink.go&id=119&Itemid=591`

### Actual result

Opens in parent window.
Links structure is
`index.php?option=com_weblinks&view=weblink&id=119:weblink-name&catid=90&Itemid=591`

### System information (as much as possible)

Joomla 3.9.4

### Additional comments

Not sure where to report: Joomla Smart Search or Web Links

**Comment by ghost** [comment]
Please report in https://github.com/joomla-extensions/weblinks/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24415">issues.joomla.org/tracker/joomla-cms/24415</a>.</sub>
