### ISSUE TITLE
Error page not being invoked for certain urls containing numbers

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#24438]
### Steps to reproduce the issue
Download and install Joomla 3.9.4. with "sample data english blog".
rename htaccess.txt to .htaccess in joomla root directory
Enable SEF urls in joomla global configuration (no need to enable url rewriting)
Type "yourdomain.com/rubbish" - you get the "error" page and "not found" shows correctly.

Now type "yourdomain.com/1" or "yourdomain.com/1rubbish" or any url that starts with number and you get the "home" page and no error is shown at all

### Expected result

error page should be shown

### Actual result

Home page shows

### System information (as much as possible)

Any system spec

### Additional comments

I believe that this change was introduced in on eof the last few versions of Joomla as this used to work.

**Comment by ghost** [comment]
Can't confirm on a quick Test on a 3.9.4-Livesite, got always 404 as expected.

**Comment by brianteeman** [comment]
Pretty certain that this is a known issue when you use a number that matches an article id

**Comment by ReLater** [comment]
> I believe that this change was introduced in on eof the last few versions of Joomla as this used to work.

No. It's like @brianteeman says. And it's the known and "correct" behavior at least since Joomla 2.5. BTW: you can use it for short urls (nice side effect).

Use "Modern URL Routing" plus "Remove IDs from URLs" to get rid of it.

**Comment by ghost** [comment]
Closed as expected Behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24438">issues.joomla.org/tracker/joomla-cms/24438</a>.</sub>
