### ISSUE TITLE
Accessibility errors with Tagged Items menu item

### ISSUE THREAD

**Issue by eddiekonczal** [joomla/joomla-cms#24446]
### Steps to reproduce the issue

- Create a "Tagged Items" menu item
- Enable "Filter Field" on the "Item Options" tab
- Enable "Display Select" on the "Pagination Options" tab
- Save the menu item
- Analyze the page with the "WorldSpace Attest DevTools" plugin for Google Chrome

### Expected result

The page should not return any accessibility errors

### Actual result

The page returns these accessibility errors:

1. Filter field: "Form elements must have labels"

> Issue description
> Ensures every form element has a label
> 
> Impact: critical
>  Learn more
> Element location
> input[autocomplete="off"]
> Element source
> <input type="text" autocomplete="off" readonly="">
> 
> To solve this violation, you need to:
> Fix at least one (1) of these issues:
> aria-label attribute does not exist or is empty
> 
> aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
> 
> Form element does not have an implicit (wrapped) <label>
> 
> Form element does not have an explicit <label>
> 
> Element has no title attribute or the title attribute is empty

2. Display select: "Buttons must have discernible text"

This violation appears twice: once for the search icon and once for the "X" icon.

> Issue description
> Ensures buttons have discernible text
> 
> Impact: serious
>  Learn more
> Element location
> button[type="button"]
> Element source
> <button type="button" name="filter-search-button" title="Search" onclick="document.adminForm.submit();" class="btn"> <span class="icon-search"></span> </button>
> To solve this violation, you need to:
> Fix the following:
> Element is in tab order and does not have accessible text

### System information (as much as possible)

PHP Built On | Linux www3 4.4.162-94.72-default #1 SMP Mon Nov 12 18:57:45 UTC 2018 (9de753f) x86_64
Database Type | mysql
Database Version | 5.5.39
Database Collation | utf8mb4_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.0.7
Web Server | Apache
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 3.9.4 Stable [ Amani ] 12-March-2019 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0 SeaMonkey/2.49.4

**Comment by ghost** [comment]
@zwiastunsw can you please comment?

**Comment by zwiastunsw** [comment]
I confirm. The error is caused by the lack of label for the input field generated by javascript:
```<div class="chzn-search"><input type="text" autocomplete="off" readonly=""></div>```
This code is generated by media/jui/js/ajax-chosen.js script.

In addition: the screen reader does not read values selected from the list by the user.

**Note 1**: The same error occurs on the search results list page. 
**Note 2**: In Joomla 4 there is no such error.
**Note 3**:  The item number selector is also used, for example, on the pages of the item list in a category, but in this case there is no error. However, In this case this code js is not called.

**Comment by brianteeman** [comment]
This is a problem from the chzn script that can't be fixed in joomla 3

**Comment by zwiastunsw** [comment]
> This is a problem from the chzn script...

Exactly... :)

**Comment by brianteeman** [comment]
Unfortunately it cannot be fixed in j3 so should be closed

**Comment by ghost** [comment]
Closed for the Reason stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24446">issues.joomla.org/tracker/joomla-cms/24446</a>.</sub>
