### ISSUE TITLE
Module styles from specific template only work when that template is used on that page

### ISSUE THREAD

**Issue by saraheagle** [joomla/joomla-cms#24456]
### Steps to reproduce the issue
- Make sure you have the Beez & Protostar templates installed and enabled
- Have the Beez template as the default template
- Create a new "Custom" module and put it into a position where it can be seen on the front end of the website.
- In the advanced tab choose the "well" Protostar module style

### Expected result
- The "well" Protostar module style is being used

### Actual result
- It is not being used

### System information (as much as possible)
PHP Built On	Windows NT TERROR 10.0 build 17763 (Windows 10) i586
Database Type	mysql
Database Version	5.5.5-10.1.31-MariaDB
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.2.4
Web Server	Apache/2.4.33 (Win32) OpenSSL/1.1.0g PHP/7.2.4
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.9.4 Stable [ Amani ] 12-March-2019 15:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

### Additional comments
This is not really a bug, I presume that the system is meant to work this way.
However it would be MUCH more useful if you could use module styles from ALL templates that are installed and enabled, not just the template that is currently being used on that page.
The fact that they are all listed in the drop-down for you to choose from, misleads an admin into believing that they are available to use.

Thank you :)

**Comment by Chaosxmk** [comment]
Alternatively, if it proves too difficult to allow a user to use a module style from any template, then the list of available styles should be limited to only the active template.

**Comment by brianteeman** [comment]
Same as #17953 ??

**Comment by mbabker** [comment]
> Alternatively, if it proves too difficult to allow a user to use a module style from any template, then the list of available styles should be limited to only the active template.

It's too complex to limit the options in that field to whatever is contextually relevant to the module.  Which includes limiting the template position selector to "active template" or the module chrome selector in the same way (you'd need a lot of heavy engineering to be able to properly filter this down, and a lot of AJAX driven field reloading to reset other fields if you change something, i.e. if you change the module's position to one in another template then the chrome selection should reset).  I wish luck to anyone who tries to tackle this, but the amount of complexity involved here makes me doubt improving things is feasible.

**Comment by ghost** [comment]
Closed as duplicate Report #17953. Thanks for Hint @brianteeman <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24456">issues.joomla.org/tracker/joomla-cms/24456</a>.</sub>
