### ISSUE TITLE
[4.0] Error when there is no category in articles

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#24452]
### Steps to reproduce the issue
Install a fresh version. 
Then go to com_content, categories, trash and delete the category.

### Expected result
A warning, something like "Delete not possible. You must have at least one category"

### Actual result
The category is deleted. 
The view artices now throws the error:
Argument 1 passed to Joomla\Utilities\ArrayHelper::getColumn() must be of the type array, boolean given, called in administrator\components\com_content\Model\ArticlesModel.php on line 516 

### Additional comments
All versions and probably all extensions which use categories

**Comment by mbabker** [comment]
Nothing says that there must be at least one category.

Actually, that specific error at that specific line means that nobody is doing error checking in the `getTransitions` method, a common missing thing in Joomla's code.  The `getItems` doc block clearly indicates a boolean false is returned on failure.

**Comment by brianteeman** [comment]
As you can create a category on the fly within the article edit form there shouldnt be a reason that you cannot delete all empty categories

**Comment by chmst** [comment]
@brianteeman you are right.
@mbabker After a new installation this error has diappeared. Sorry for wrong alert.

**Comment by mbabker** [comment]
There's still a bug to be addressed and something should be open (either this with the title corrected or a new item) to address it.  [This line](https://github.com/joomla/joomla-cms/blob/2bdb02a464362efc3e26f442a91d141a2521bf11/administrator/components/com_content/Model/ArticlesModel.php#L514) does not check for a boolean false return, meaning there is no error handling and that should be fixed to prevent the fatal error you posted in your original post.

**Comment by ghost** [comment]
@chmst can you please open an Issue as @mbabker suggested above?

**Comment by alikon** [comment]
unable to replicate with

- Install a fresh latest staging without data
- go to com_content, categories
- trash and delete the category

both
`..index.php?option=com_content`

and 
`...index.php?option=com_categories&extension=com_content`

gives expected result 
`No Matching Results `

what i'm missing ?

**Comment by mbabker** [comment]
The title is not relevant at this point.  As I noted in https://github.com/joomla/joomla-cms/issues/24452#issuecomment-479058646 the bug is the lack of error checking when calling `$this->getItems()`, if for some reason that returns a boolean false that scenario is not accounted for which results in the "Argument 1 passed to Joomla\Utilities\ArrayHelper::getColumn() must be of the type array, boolean given, called in administrator\components\com_content\Model\ArticlesModel.php on line 516" fatal error from the original issue post.  You're not going to replicate this issue without breaking something else.

**Comment by chmst** [comment]
As I said, the error has diappeard after a new installation. Probably it was a database update between the last pulls which caused the error.

**Comment by alikon** [comment]
did you mean after https://github.com/joomla/joomla-cms/blob/2bdb02a464362efc3e26f442a91d141a2521bf11/administrator/components/com_content/Model/ArticlesModel.php#L514

something like

```php
if (!$items)
{
	return false;
}
```
?

**Comment by mbabker** [comment]
Right.

**Comment by ghost** [comment]
closed as having Pull Request #24458
