### ISSUE TITLE
[4.0] Blog Sample Data doesn't show completed.

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#24459]
### Steps to reproduce the issue

install clean dev_4.0
after installation run blog sample data installer

### Expected result
sample data is installed and informs me its completed.
install button changes to "installed" or "completed"
progress bar goes away or CLEARLY indicates completed ( change color? )

### Actual result
![image](https://user-images.githubusercontent.com/1850089/55435531-ad582580-555f-11e9-8c97-8e3d5a6a9e7a.png)

### System information (as much as possible)

[systeminfo-2019-04-02T20_55_44+00_00.txt](https://github.com/joomla/joomla-cms/files/3035894/systeminfo-2019-04-02T20_55_44%2B00_00.txt)

**Comment by Bakual** [comment]
The last message states it has been installed and the progress bar is at 100%. Imho it's quite clear.

Of course the bar could be changing colors (should be simple with CSS) - but I wouldn't make that specific for the sample data. Progress bars ideally look the same in the whole CMS.
I also wouldn't hide it. That would be strange and unexpected.

I wouldn't touch the "install" buttons. After a page refresh they would be back at initial state anyway.

Maybe the last message could be a different color or another text to indicate better it's the last one.

**Comment by ghost** [comment]
> Maybe the last message could be a different color (...) to indicate better it's the last one.

+1 for this.

**Comment by hardik-codes** [comment]
> Maybe the last message could be a different color or another text to indicate better it's the last one.

@Bakual should I do these changes

**Comment by Bakual** [comment]
@hardik-codes You don't have to ask for permission. Just do if you're interested 😄

**Comment by hardik-codes** [comment]
@Bakual What should be the exact change so that it is consistent with the joomla design?

**Comment by Bakual** [comment]
I have no clue - I'm not a designer 😄
Maybe @coolcat-creations has an idea.

**Comment by coolcat-creations** [comment]
If all the steps are bound to each other its enough to have 1 Progressbar, telling the current progress and in the end the result (installation of sample data completed) no need so much messages IMHO.

**Comment by infograf768** [comment]
it is not really. Some steps can succeed while others will not.

**Comment by brianteeman** [comment]
Is it ever possible for a scenario like this?
Step 1 - pass
Step 2 - fail
Step 3 - pass
Step 4 - pass

**Comment by infograf768** [comment]
Yes, I remarked that when the plugin was modified in 3.9 for security reasons. 
It will be merged  in 4.0 with this new code.

https://github.com/joomla/joomla-cms/commit/bbdf775fbee26d275ce60ea466b778e4694210a1#diff-8ca6ae5a8651d5eb87f3bad712894457

<img width="932" alt="capture" src="https://user-images.githubusercontent.com/869724/55492966-6ab64c00-5638-11e9-8df9-90baa7dd7fbd.png">

In my test I had there refused core.create for menus to an admin.

For that case we could also add the the authorisation (core.create) for all components used in the first `public function onSampledataGetOverview()` therefore refusing to run the plugin when the user has no create rights for ALL the components involved.

**Note :** a failure for one iteration may also happen if the component concerned is NOT enabled.
**Note 2 :** It will be necessary anyway to make a patch for the multilingual sample data after the 3.9 commit is merged into 4.0

**Comment by Bakual** [comment]
It can skip a step if some requirements are not met (eg if an extensions isn't installed), but that's still technically a success. If one step actually fails, the whole thing will stop and it will never go further.

**Comment by pe7er** [comment]
I was also a bit confused about installing sample content: 
the progress bar is animated, and keeps "moving" even after the installation has been completed.
```
<div class="progress">
	<div class="progress-bar progress-bar-striped progress-bar-animated bg-success" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="100" style="width: 100%;">4/4</div>
</div>
```

Can't we remove the "progress-bar-animated" part with JavaScript after the installation has been finished?

**Comment by brianteeman** [comment]
better yet - remove the animated part completely as it fails a11y reduced-motion tests
