### ISSUE TITLE
Filter Ordering not working

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/joomla-cms#24465]
### Steps to reproduce the issue
1. Use Search to search for a popular word (e.g. joomla on a test site)
2. When you go to the search results page, try sorting the results.
![ordering_39](https://user-images.githubusercontent.com/29527200/55523763-da552700-568a-11e9-89c7-50853037d3ca.png)

### Expected result
The page is reloaded and the position order is changed according to the selected criterion. 
### Actual result
Nothing happens

**Comment by ghost** [comment]
Issue confirmed. Change Results for Example to "Oldes first" and click again on "Search"-Button didn't show oldest Article first (similaer Alphabetical Order).

No Errors on Console.

### System information
- 3.9, latest nightly build
- Template: Protostar
- macOS Sierra, 10.13.6
- Firefox 66 (64-bit)
#### CloudAccess.net
- PHP 7.1.27
- MySQLi 5.7.24-cll-lve

**Comment by brianteeman** [comment]
Same answer as #24466

**Comment by infograf768** [comment]
Looks like this is due to the `$relevance` variable in the search content plugin.
It is defined in the query as
`$relevance[] = ' CASE WHEN ' . $wheres2[0] . ' THEN 5 ELSE 0 END ';`

a `var_dump($relevance);` gives when searching for "joomla"
`array(1) { [0]=> string(67) " CASE WHEN LOWER(a.title) LIKE LOWER('%joomla%') THEN 5 ELSE 0 END " } `

Then further, we have.

```
			if (!empty($relevance))
			{
				$query->select(implode(' + ', $relevance) . ' AS relevance');
				$order = ' relevance DESC, ' . $order;
			}
```

If I comment `$order = ' relevance DESC, ' . $order;` then ordering works fine.

Any way it does not change order on the fly. One has to click on Search again.

The `$relevance` variable was added in https://github.com/joomla/joomla-cms/pull/20197
and I (as others) tested it OK at the time...

@alikon ?

**Comment by infograf768** [comment]
### NOTE
If I search for something else than "Joomla", then it works OK

**Comment by alikon** [comment]
apart the "_The page is reloaded_" for me this is not  (strictly) an error but much more a UX problem
for the ordering, for me this is an expected and wanted behaviour as per #20197
we want to give "privilege" when the word is present in the title in the result

**Comment by zwiastunsw** [comment]
@alikon : <strike>This is an error. When using the keyboard, the page reloads accidentally when you move the cursor to the next number in the list. I cannot decide how many items I want to display</strike>.

**Comment by alikon** [comment]
@zwiastunsw i've analyzed the issue posted 
this is a 3rd one ? or I'm wrong ?

**Comment by zwiastunsw** [comment]
> this is a 3rd one ? or I'm wrong ?

I understand

**Comment by zwiastunsw** [comment]
Wait a minute. Sorry. Sorry.
There's only a UX problem here. The filter works for a new search. Earlier @Brian Teeman explained.
Therefore, it should be on the site before the search form. Or there should be information that you can change the way you organize the results of the new search.

**Comment by alikon** [comment]
are you suggesting that some better explanation should be done in the docs.joomla.org ?

**Comment by zwiastunsw** [comment]
Just a minute. I'll test it again. Because I have strange behavior.

**Comment by zwiastunsw** [comment]
1. I have reported that after the filter change the page is not overloaded and the results are not arranged according to the selected filter. @brianteeman explained that the filter works only for the new search.
This is a different behaviour than in the Joomla Backend. If we think that this is the correct behavior, then - in my opinion - the user should be warned about it, e.g. by an appropriate order of forms - first filters, then a search form. Or you need to add a short instruction, e.g. "Set up a new search".  
2. After I reported ,  @franz-wohlkoenig  and @infograf768 noticed that the filter was not working properly. And this is a different, but important issue.
I tested it. Two filters are not working properly: Alphabetically and Oldest first:

see: Alphabetically
![alpha](https://user-images.githubusercontent.com/29527200/56079440-c204ab00-5df4-11e9-8bbd-a82f0be70f7c.png)
see Oldest first
![olest](https://user-images.githubusercontent.com/29527200/56079454-dea0e300-5df4-11e9-9577-db221677141a.png)

**Comment by brianteeman** [comment]
It is not a filter/sort of the results.

It is for new searches. That's why it is positioned next to the search box and not next to the results.

It has always been this way.

**Comment by zwiastunsw** [comment]
I accept your opinion. 
I think this issue should be closed and a new one should be opened to define the issue of incorrect filter working.

**Comment by alikon** [comment]
Again the result order give priority when the searched word is present on the title

**Comment by brianteeman** [comment]
AS stated above by the original reporter this should be closed
