### ISSUE TITLE
[4.0] Filter ordering not working

### ISSUE THREAD

**Issue by zwiastunsw** [joomla/joomla-cms#24466]
### Steps to reproduce the issue
1. Use Search to search for a popular word (e.g. joomla on a test site)
2. When you go to the search results page, try sorting the results.
![orderingJ4](https://user-images.githubusercontent.com/29527200/55523802-0670a800-568b-11e9-8b34-6a14fe894294.png)

### Expected result
The page is reloaded and the position order is changed according to the selected criterion. 
### Actual result
Nothing happens

**Comment by ghost** [comment]
@HLeithner should Issues of J3 and J4 be reported only in J3 like #24465 so this Issue get closed?

Similaer Questions for #24467 / #24468, #24469 / #24470

**Comment by brianteeman** [comment]
If I remember correctly that is to chose the sort order on a new search and not the existing one

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/issues/24465#issuecomment-479789450

**Comment by HLeithner** [comment]
Joomla 4 should not include com_search.

**Comment by infograf768** [comment]
Was it formally decided? imho there was a debate on this.

**Comment by simbus82** [comment]
It seems that a lot of Joomla users (professionals, not developers, but real "admin" users) see the presence of two search systems as really confusing. Even for me, com_search is no longer useful. Smart Search works pretty well in most cases.

**Comment by HLeithner** [comment]
I'm not 100% sure about this decision ask @wilsonge and @Hackwar on this topic

**Comment by zwiastunsw** [comment]
@brianteeman write: 
>If I remember correctly that is to chose the sort order on a new search and not the existing one

I confirm that this is the case. 
OK. This is not a error. But this is a UX problem. The user has to guess when to use a sorting filter. The page layout suggests that you first need to perform a search.

2. I know that the Search component is not to be in Joomla 4. But it is. If it is not to be, it should simply be removed.

**Comment by HLeithner** [comment]
com_search has been removed from J4 https://github.com/joomla/joomla-cms/pull/20637

I'm closing this. thx
