### ISSUE TITLE
[4.0] installing template throws isAdmin error

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#24460]
### Steps to reproduce the issue
install j4 staging.
attempt to install "helix ultimate"

### Expected result

installed correctly

### Actual result

![image](https://user-images.githubusercontent.com/1850089/55439050-fa8cc500-5568-11e9-9139-13534140f3b4.png)

### System information (as much as possible)

[systeminfo-2019-04-02T20_55_44+00_00.txt](https://github.com/joomla/joomla-cms/files/3036056/systeminfo-2019-04-02T20_55_44%2B00_00.txt)

**Comment by Quy** [comment]
Turn on debug. The error could be coming from the template.

**Comment by mbabker** [comment]
https://api.joomla.org/cms-3/classes/Joomla.CMS.Application.CMSApplication.html#method_isAdmin

**Comment by infograf768** [comment]
The template needs a lot of care to use in j4.
isAdmin but also isSite in the plugin, (I could install by using isClient(), but also much more.

Closing
