### ISSUE TITLE
Reopen: review time of user notes is saved wrong

### ISSUE THREAD

**Issue by mojoooo** [joomla/joomla-cms#24462]
Hello again,

i've already reported this error in https://issues.joomla.org/tracker/joomla-cms/23890 and need to reopen it again, because the problem isn't solved yet.
I've tested your suggestions without success.

I can provide you with some more information:
When I create a new user hint the review time is set automatically to the current date. After saving it gets converted to a different date like described in the above-mentioned issue.

I can exclude that it's up to the date format.

Do you have further suggestions?

Thank you.

**Comment by ghost** [comment]
Please ask on [Forum](https://forum.joomla.org/)

**Comment by ReLater** [comment]
@franz-wohlkoenig 

Could you plese reopen. I can confirm this issue with current 3.9.5-dev. It was also reported in a German forum some minutes ago.

## Testing instructions
- Set back-end language to german (de-DE).
- Create a new User Note.
- In field "Review Date" select a date with the date picker (see first image below).
- Save user note and check the date (see second imege).

![08-04-_2019_17-18-54](https://user-images.githubusercontent.com/20780646/55735950-a8ddb200-5a22-11e9-9f4a-c5fd2fb08bfb.jpg)

![08-04-_2019_17-19-16](https://user-images.githubusercontent.com/20780646/55735965-b2671a00-5a22-11e9-8dc9-9eb8d3935344.jpg)

**Comment by ReLater** [comment]
## Addition to Testing instructions:
- When you see second image in my last post above then save again.
- The date field is empty afterwards.
![08-04-_2019_17-49-23](https://user-images.githubusercontent.com/20780646/55738111-bb59ea80-5a26-11e9-85a9-016989d2b017.jpg)

**Comment by ChristineWk** [comment]
Confirm Testing instructions & result with change of the date to: 20.04.2008

Addition to Testing instructions after saving again: The field is not empty, but I got date: 20.04.**2020**

**Comment by Quy** [comment]
Please test PR #24529<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24462">issues.joomla.org/tracker/joomla-cms/24462</a>.</sub>

**Comment by mojoooo** [comment]
Tested successfully. Thank you very much :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24462">issues.joomla.org/tracker/joomla-cms/24462</a>.</sub>
