### ISSUE TITLE
Info_block render helper not hiding all html

### ISSUE THREAD

**Issue by Stalib** [joomla/joomla-cms#2447]
Description:

The info block render helper does not hide the entire html generated when selecting above or below from the article options when using components like Category Blog. The default article view component is fine as it does not use the render helper.

This produces errors when trying to style the .article-info class. If this is intentional, please note this breaks behavior across different components IE Category Blog and the default article view.

Version:

Joomla 3.2 (Windows 7 64bit, Chrome)

Details:

File: .. / layouts / joomla / content / info_block / block.php 

```
<dl class="article-info  muted">
		<?php if ($displayData['position'] == 'above' && ($blockPosition == 0 || $blockPosition == 2)
                        [Other Code]
		<?php endif; ?>
	</dl>
```

Should be:

```
<?php if ($displayData['position'] == 'above' && ($blockPosition == 0 || $blockPosition == 2)
           <dl class="article-info  muted">
                        [Other Code]
          </dl>
<?php endif; ?>
```

Repro Steps:

1. Select Category Blog as menu item type
2. Change position of article info in the article options section to either above or below
3. Add any css to .article-info IE .article-info {padding: 5px; border: thin solid red; background-color: green;)

Results:

Both article-info are still visible. One with text and one without depending on option selected.

Expected:

Only one article-info box should be visible depending on your option (IE either below or above)

**Comment by brianteeman** [comment]
After considerable time without update I am closing this. If you feel this is still an issue please provide further information and it can always be reopened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/2447">issues.joomla.org/joomla-cms/2447</a>.</sub>
