### ISSUE TITLE
[4.0] Batch copy fails

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#24478]
### Steps to reproduce the issue
Install sample data
Select all articles
Select batch
Select a category and copy

### Expected result
Articles are copied to the selected category

### Actual result
Message says Success but no articles have been copied

**Comment by ghost** [comment]
Issue confirmed.

**Comment by brianteeman** [comment]
Checking the database the content is created but joomla cannot see it. Probably related to workflows?

**Comment by Quy** [comment]
Please test PR #24519<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24478">issues.joomla.org/tracker/joomla-cms/24478</a>.</sub>

**Comment by richard67** [comment]
Please test PR #26835 . Is solves the same problem as PR #24519 , but in a more elegant way.
