### ISSUE TITLE
When login via android mobile (chrome browser) - Login not working

### ISSUE THREAD

**Issue by alagesanbe08** [joomla/joomla-cms#24474]
### Steps to reproduce the issue

1. Open Chrome browser in android
2. Try to login in Joomla site

### Expected result

Login into site

### Actual result

It does not allow to login

Chrome version: 72.0.3626.105

I just tried more than 3 sites in 3 different device

**Comment by ghost** [comment]
Have you asked on [Forum](https://forum.joomla.org/)?

**Comment by Bakual** [comment]
It certainly works for my sites on my android.
Tested with Chrome 73.0.3683.90 and Android 7.0

**Comment by brianteeman** [comment]
And my sites with Android 8 and 9

**Comment by ghost** [comment]
@Bakual @brianteeman Thanks for testing. Closing as no Core-Issue. Issue can always be reopened.
