### ISSUE TITLE
[4.0] com_search no results

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#24479]
### Steps to reproduce the issue
Install sample data
On the front end use the search module to search for any term

### Expected result
Search page with results

### Actual result
Search always returns 0 results

The query generated is```

SELECT  CASE WHEN LOWER(a.title) LIKE LOWER('%welcome%') THEN 5 ELSE 0 END  AS relevance,a.title AS title, a.metadesc, a.metakey, a.created AS created,CONCAT(a.introtext,a.fulltext) AS text, CASE WHEN CHAR_LENGTH(a.alias) != 0 THEN CONCAT_WS(':', a.id, a.alias) ELSE a.id END AS slug, CASE WHEN CHAR_LENGTH(c.alias) != 0 THEN CONCAT_WS(':', c.id, c.alias) ELSE c.id END AS catslug,c.title AS section,'2' AS browsernav
FROM `phnlb_content` AS `a`
INNER JOIN `phnlb_categories` AS `c` ON c.id = a.catid AND c.access IN (1,1,5)
WHERE ((LOWER(a.title) LIKE LOWER('%welcome%') OR LOWER(a.introtext) LIKE LOWER('%welcome%') OR LOWER(a.fulltext) LIKE LOWER('%welcome%') OR LOWER(a.metakey) LIKE LOWER('%welcome%') OR LOWER(a.metadesc) LIKE LOWER('%welcome%'))) AND a.state = 2 AND c.published = 1 AND a.access IN (1,1,5) AND c.access IN (1,1,5) AND (a.publish_up = '0000-00-00 00:00:00' OR a.publish_up <= '2019-04-04 11:41:43') AND (a.publish_down = '0000-00-00 00:00:00' OR a.publish_down >= '2019-04-04 11:41:43')
ORDER BY  relevance DESC,  relevance DESC, a.created DESC LIMIT 50
```

A simple search of the database shows that I should have 4 results
```
SELECT * FROM phnlb_content
WHERE title LIKE "%welcome%"
```

### System information (as much as possible)



### Additional comments

**Comment by ghost** [comment]
closed as having Pull Request #24494
