### ISSUE TITLE
[4.0] Separate tags from CategoryServiceInterface

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#24486]
Reminder for @wilsonge.

**Comment by wilsonge** [comment]
To expand here tags shouldn't be coupled to categories (e.g. https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Categories/CategoryServiceInterface.php#L48-L59) and these interfaces should be separated

**Comment by wilsonge** [comment]
Closing for #24587 which contains more of these interface issues
