### ISSUE TITLE
[4.0] Edit state on multiple articles fails

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#24480]
### Steps to reproduce the issue
Create two identical articles in the same category
One published and one unpublished
Select both articles
From the change status dropdown select publish

### Expected result
One item published resulting in two published articles

### Actual result
No change to published state and incorrect messages

![image](https://user-images.githubusercontent.com/1296369/55553739-ef58a700-56d8-11e9-8e0a-3acffcaa8c85.png)

**Comment by ghost** [comment]
Issue confirmed.

**Comment by bahl24** [comment]
> One published and one published

@brianteeman Do you mean 1 published & 1 unpublished?
Also if 1 article is published, the published button is disabled.

**Comment by brianteeman** [comment]
yes i did and i have updated the original report

**Comment by bahl24** [comment]
@brianteeman I have solved the issue that the unpublished article was not being published, before opening a PR I wanted to ask if I should remove the warning message-"Edit state is not published"?
Warning is displayed when we try to publish an already published article, so IMO warning is needed.
So, should the expected outcome involve the warning?

**Comment by brianteeman** [comment]
Is the message useful? No

**Comment by brianteeman** [comment]
Look at the behaviour in joomla 3

**Comment by ghost** [comment]
closed as having Pull Request.
