### ISSUE TITLE
[4.0] Hide columns

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#24495]
Reminder for @wilsonge.

**Comment by bembelimen** [comment]
I'm working on it!

**Comment by brianteeman** [comment]
Is this still being worked on?

**Comment by brianteeman** [comment]
Is this still being worked on?

**Comment by brianteeman** [comment]
@bembelimen is this still being worked on? If you started and don't have time to finish can you share what you have done so far and then others can take it on. Please

**Comment by wilsonge** [comment]
I'm not aware of @bembelimen working on this - so let's assume it's not being worked on

**Comment by Quy** [comment]
Is this about being able to configure/hide columns in list view as in #27876?

**Comment by brianteeman** [comment]
ok so I am closing this here and redirecting you to #27876
