### ISSUE TITLE
[4.0] Remove language prefix from language files to ease crowdin process

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#24493]
Reminder for @wilsonge.

**Comment by brianteeman** [comment]
Is anything happening with this. If it is then it really should be merged before we can be api complete and release a beta

**Comment by Bakual** [comment]
Basically, @wilsonge has to merge up the 3.10-dev branch into 4.0-dev so PR https://github.com/joomla/joomla-cms/pull/19353 is available in 4.0.
Then I can do a simple PR of removing the prefix from the language files.

But you're right, that has to be done before first beta.

**Comment by brianteeman** [comment]
ok - thanks for the update

**Comment by brianteeman** [comment]
I assume that this can be closed now?

**Comment by Bakual** [comment]
Indeed. Thanks for the reminder.
