### ISSUE TITLE
[4.0] Sidebar in com_config styling/layout

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#24499]
Placeholder for @wilsonge

**Comment by nadjak77** [comment]
Can you please descripe more details what is wrong.
Thank you.

**Comment by ghost** [comment]
> Placeholder for @wilsonge

As Release Lead he is working through different Aspects. To not forget an issue this Reminder was created.

**Comment by nadjak77** [comment]
Thank you

**Comment by wilsonge** [comment]
Basically the double sidebar in com_config (the main menu and the option to choose component/global config) gives a poor user experience. We need to find some sort of way of an alternative design format. This is just a placeholder issue to contain that

**Comment by brianteeman** [comment]
I am not 100% convinced that there is a problem to resolve here. The only non sidebar alternative that comes to mind is to have a select at the top like in module manager where you select between site and admin but here it would be between global and a big list of components

**Comment by wilsonge** [comment]
The problem is with the left hand menu this layout starts to become very cramped. Your almost enforced on a laptop to minimise the main menu to have enough space

**Comment by brianteeman** [comment]
I dont see the issue on a desktop resolution but there is definitely an issue on mobile

**Comment by brianteeman** [comment]
> I dont see the issue on a desktop resolution but there is definitely an issue on mobile

Just checked the proposal in the new template and it addresses the mobile issue

**Comment by brianteeman** [comment]
@wilsonge I really think this is not an issue any more

**Comment by wilsonge** [comment]
I have a feeling there still might be issues in 3rd party components who will have a left hand menu (rather than use the main menu for 3.10 compat). But we can take that as we go. Happy to close for now and re-evaluate later if required
