### ISSUE TITLE
[4.0] Sidebar menu in system dashboard (languages etc)

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#24497]
Reminder for @wilsonge.

**Comment by bembelimen** [comment]
@wilsonge let's talk here in the sprint, probably it's solved in the backend template already?

**Comment by brianteeman** [comment]
There are quite a few open pr that will resolve most of this (if not all)

**Comment by wilsonge** [comment]
i think i've merged all the open pr's on this now. where are we sitting at?

**Comment by brianteeman** [comment]
I "think" its just the config options sidebar thats left

**Comment by brianteeman** [comment]
checked and the outstanding ones are 
com_finder #24020
com_contact #23366

**Comment by infograf768** [comment]
com_contact has been solved.
remains com_finder

**Comment by Quy** [comment]
#27032 com_finder
#24499 com_config

**Comment by Quy** [comment]
Closing as one is RTC and the other has its own issue #.
