### ISSUE TITLE
[4.0] Editor XTD and Versioning in the frontend is broken

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#24491]
Reminder for @wilsonge. Similar: #23510, #23979

**Comment by jwaisner** [comment]
@wilsonge IS this needed anymore?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24491">issues.joomla.org/tracker/joomla-cms/24491</a>.</sub>

**Comment by wilsonge** [comment]
No clue. I know JM's been working on some of the styling - so I assume someone's got it working - but haven't tested anything.

**Comment by infograf768** [comment]
Will test today

**Comment by infograf768** [comment]
We do have an issue with versionning indeed.
Some small display but more important using the restore button is not loading the version chosen in the editor.
As it is apparently the same issue in back-end, I am closing this and create a new issue.
Will look separately at the versionning modal display.

**Comment by infograf768** [comment]
After further checks, looks like Restore works OK. Will try to normalise the modal display vs the XTDs modal

**Comment by wilsonge** [comment]
Thanks JM!

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/28405
