### ISSUE TITLE
[4.0] Breadcrumbs/Help & Options icon "row" in template

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#24500]
Placeholder for @wilsonge

**Comment by bembelimen** [comment]
![breadcrumb](https://user-images.githubusercontent.com/1229869/56474228-2ec41900-6477-11e9-8634-7ae590d77133.png)

**Comment by brianteeman** [comment]
Breadcrumbs is not part of the new template

**Comment by Hackwar** [comment]
I coded this part and had a PR for this, however this a) has pretty little use in the backend and b) is not really implementable reliably since the backend has no idea of menu items or a hierarchy between those. So this one can be closed.

**Comment by ghost** [comment]
closed as stated above.

**Comment by alikon** [comment]
closed thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24500">issues.joomla.org/tracker/joomla-cms/24500</a>.</sub>

**Comment by brianteeman** [comment]
Would the concept of "breadcrumbs" not be useful on an item page?

eg on an article it would show
Category\Category\title
