### ISSUE TITLE
[4.0] articles not displayed in com_content

### ISSUE THREAD

**Issue by Puneet-Jain-18** [joomla/joomla-cms#24514]
### Steps to reproduce the issue
Go To administrator/content/articles in the backend of the website

### Expected result

![Screenshot (43)](https://user-images.githubusercontent.com/34083630/55665717-ee9f4c80-5861-11e9-8e72-c6a39e197098.png)

### Actual result
![Screenshot (42)](https://user-images.githubusercontent.com/34083630/55665719-f19a3d00-5861-11e9-8c0f-51dc3c2e4e4f.png)

### System information (as much as possible)
Joomla 4.0.0 alpha-8-dev

### Additional comments
Was working fine about 10 days ago

**Comment by Bakual** [comment]
I'm closing this as no detail is given.

**Comment by Puneet-Jain-18** [comment]
@Bakual sorry posted by mistake without adding information
Please reopen

**Comment by infograf768** [comment]
Has this test been done with a clean install of 4.0-dev branch?
If not please do as I do not have this error here.

**Comment by Puneet-Jain-18** [comment]
Yes, I have tested it on a clean install the error Reproduce.

**Comment by ghost** [comment]
Can't confirm too.
### System information
Setting | Value
-- | --
PHP Built On | Linux lamp122.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.7.el6h.x86_64 nr.1 SMP Mon Dec 17 12:02:35 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.24-cll-lve
Database Collation | utf8_general_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.1.26
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Latest Nightly Build Update from Joomla! 4.0.0-alpha8-dev Development [ Amani ] 9-March-2019 13:41 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by Puneet-Jain-18** [comment]
I will check it once more.

**Comment by Bakual** [comment]
Please delete configuration.php and reinstall J4 fresh. That error comes from changes in SQL schema and only happens when you update from a previous J4 installation (not supported yet).

Closing as expected behavior.

**Comment by Puneet-Jain-18** [comment]
Ok !! Sorry and thanks :)

**Comment by infograf768** [comment]
If there is no category at all, see https://github.com/joomla/joomla-cms/pull/24458
