### ISSUE TITLE
[4.0] Page Reload on Clicking Publish button for Published Article

### ISSUE THREAD

**Issue by Puneet-Jain-18** [joomla/joomla-cms#24518]
### Steps to reproduce the issue
go to already created articles in the backend administrator 
Select a check-box of a published article
open change status toolbar list and click on publish

### Expected result
Nothing Happens as the button is read-only

### Actual result
The page is reloaded.
Request Probably goes to the backend(to be confirmed)

### System information (as much as possible)

joomla 4.0.0 -Alpha -8 -dev

### Additional comments
Similar Issue if the article is unpublished and unpublish button is clicked.

**Comment by brianteeman** [comment]
The problem is that the button is not "read-only". It has a class of disabled but that's not the same thing as a disabled button

Current code
```
<button class="button-unpublish dropdown-item disabled" type="button">
	<span class="icon-unpublish" aria-hidden="true"></span>
	Unpublish</button>
```
As far as I remember it should be
```
<button class="button-unpublish dropdown-item disabled" type="button" disabled="true">
	<span class="icon-unpublish" aria-hidden="true"></span>
	Unpublish</button>
```

**Comment by hardik-codes** [comment]
@Puneet-Jain-18 could you please recheck as I am getting this error message: One or more of the selected articles can't set be to  published.

**Comment by Puneet-Jain-18** [comment]
@brianteeman I will try to  do the changes suggested by you
@hardik-codes No, I don't get that kind of error

**Comment by Puneet-Jain-18** [comment]
This Kind Of behavior is handled at the backend by this code already.

` unpublishBtn.addEventListener('click', (e) => {
      if (e.target.classList.contains('disabled')) {
        e.stopPropagation();`

So I wanted to ask should we do changes to stop page from reloading also,??

**Comment by bahl24** [comment]
Kindly see #24517 which solves #24480 ,in that I have modified the condition for disabling of workflow buttons. Now Publish button will only be disabled only when all the selected items are published & active even if 1 of the selected is unpublished/archived/trashed (which is the expected behavior).
Similarly for other workflow buttons. 
But yes the disabled buttons are clickable which shouldn't be the case.
**The PR doesn't solve this issue**

**Comment by Puneet-Jain-18** [comment]
I will have a look Thanks !!

**Comment by ghost** [comment]
Closed as having Pull Request.
