### ISSUE TITLE
[4.0] Error in ArticlesModal.php

### ISSUE THREAD

**Issue by meet2410shah** [joomla/joomla-cms#24523]
### Error : 

Load the another page from articles, the function `getTransitions()`
line No. 511 : `ArrayHelper::getColumn($items, 'stage_id');`

![Issue1](https://user-images.githubusercontent.com/44209311/55723169-ee4fae80-5a25-11e9-83b7-acc6ab41e87f.png)

**Comment by Quy** [comment]
Duplicate #24452. Please test PR #24458.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24523">issues.joomla.org/tracker/joomla-cms/24523</a>.</sub>
