### ISSUE TITLE
Cannot login to Joomla

### ISSUE THREAD

**Issue by asmego** [joomla/joomla-cms#24527]
### Steps to reproduce the issue
Go to https://njcounseling.org/administrator and login. 
Then I get this error message: This page isn’t working njcounseling.org is currently unable to handle this request.
HTTP ERROR 500

Also, our Civicrm module is not working. When we click on a registration link, we also get this same error message as above. I'm not sure if the 2 issues are related or not. 

### Expected result
When logging in, it should go to our dashboard for Joomla and enable us to edit the site. 

### Actual result
I get an error page. 

### System information (as much as possible)
We recently migrated to a new host. All of the files seem to be there and intact.

### Additional comments
I have contacted our new host, but they couldn't figure out the issue. I have posted on the forum, but have gotten no response. I've also tried to search within the forum and have tried to troubleshoot the issue. I cannot figure this out!! Please help!

The error is showing on views/default/helpers/defaultloadedfromtemplate.php on line 1612.

SO the issue is on defaultloadedfromtemplate.php file.

**Comment by Quy** [comment]
Please ask help at [Joomla Forums](https://forum.joomla.org/).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24527">issues.joomla.org/tracker/joomla-cms/24527</a>.</sub>

**Comment by asmego** [comment]
I have tried contacting the Joomla Forums. I have not been able to resolve this issue. 
-Andrea
    On Monday, April 8, 2019, 12:18:17 PM EDT, Joomla! CMS Bot <notifications@github.com> wrote:  
 
 
Set to "closed" on behalf of @Quy by The JTracker Application at issues.joomla.org/joomla-cms/24527
