### ISSUE TITLE
[4.0] Checked_out_time error

### ISSUE THREAD

**Issue by meet2410shah** [joomla/joomla-cms#24525]
When we "close" an administration module. It shows the error in the column "checked_out_time" that can not be null.
(Joomla 3.9 has also similar kind of issue regarding checked_out_time. #22722).

![Issue3](https://user-images.githubusercontent.com/44209311/55725039-5d2f0680-5a2a-11e9-9152-a5e164ec0a4f.png)

**Comment by Quy** [comment]
Unable to reproduce. Are you testing with the [nightly builds](https://developer.joomla.org/nightly-builds.html)?

**Comment by simbus82** [comment]
Try to Fix Database in System -> Database

**Comment by Puneet-Jain-18** [comment]
I am also unable to reproduce the error

my version :Joomla! 4.0.0-alpha8-dev

**Comment by infograf768** [comment]
This PR has not yet been merged into 4.0
https://github.com/joomla/joomla-cms/pull/22748/files

@wilsonge Is that part of your next PR?

**Comment by ghost** [comment]
Closed as unconfirmed Report. Thanks anyway for Report and all other Commentators.
