### ISSUE TITLE
[4.0] Versions.php file error

### ISSUE THREAD

**Issue by meet2410shah** [joomla/joomla-cms#24526]
### Steps to reproduce the issue
STEP: 1 Open an article.
STEP: 2 Click on versions

### Output
![Issue4](https://user-images.githubusercontent.com/44209311/55726758-2c50d080-5a2e-11e9-9490-4c422d936f5b.png)

### Additional comments
Modal has z-index less than the layer on it. Due to this Close button is not functioning.

**Comment by Quy** [comment]
Duplicate #22044

**Comment by ghost** [comment]
Closed as duplicate Report. Thanks @Quy
