### ISSUE TITLE
[4.0] Full Screen Mode: Joomla Editor

### ISSUE THREAD

**Issue by rotimi-best** [joomla/joomla-cms#24530]
### Is your feature request related to a problem? Please describe.
While I was trying to edit and write some code in the Joomla Editor, cause I was on my PC (which has a screen resolution of 1366 x 768 Pixel) the coding area seemed really small that just to see what is up I needed to scroll up and then scroll back down to continue typing. 

![image](https://user-images.githubusercontent.com/31730715/55754411-42be5280-5a55-11e9-8358-8c36696d4056.png)

Version 4.0

### Describe the solution you'd like
I suggest a fullscreen mode. Meaning there can be a button or an icon that once clicked the text area becomes larger and the file structure collapse. Then the user can toggle back to make it return it back to default. A designer and a UX master is required to determine how it would look but in a nutshell what is required is for my coding area to become larger.

Another option could be to just make the web page go fullscreen, like is shown in the [codepen](https://codepen.io/matt-west/pen/hmqsF). The disadvantage I just see with this approach is that the user would need to always have to exit the fullscreen whenever he/she needs to use another tab in the browser.

**Comment by ghost** [comment]
Thanks for your feature Request. Please add "[4.0] " at start of Title.

**Comment by ghost** [comment]
In J3 is a F-Key, which is missing in J4
![Screen Shot 2019-04-09 at 06 40 23](https://user-images.githubusercontent.com/8235763/55773758-7075bc80-5a92-11e9-8455-ed3ac29ec04b.png)

**Comment by ghost** [comment]
Added "J4 Backend Template", maybe it depends on the new coming one.

**Comment by rotimi-best** [comment]
Oh interesting. I also saw another issue that had to do with using Ctrl + Q together but that really didn't solve the problem because those buttons above were inconvenient IMHO cause they obstructed still my working area.
![image](https://user-images.githubusercontent.com/31730715/55774461-e16ea180-5a9d-11e9-8aef-ae5eb3d0a9a5.png)

**Comment by brianteeman** [comment]
It is simply a bug in the codemirror editor

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/25333

**Comment by ghost** [comment]
Closed as having Pull Request #25333
