### ISSUE TITLE
Updated to 3.9.5 - When finished it reads that I have updated to 3.9.4

### ISSUE THREAD

**Issue by dgrimey** [joomla/joomla-cms#24537]
### Steps to reproduce the issue
Ran the upgrade. 
![joomla-3-9-5](https://www.scdit.com/joomla-3-9-5-update.JPG "Joomla 3--9-5 update text")

### Expected result
To read "Your site has been updated. Your Joomla version is now 3.9.5"

**Comment by ghost** [comment]
Thanks for your Report. Can't confirm on a livesite it shows 3.9.5 as expected. Lets wait if more similar Comments come in.

![Screen Shot 2019-04-09 at 17 24 13](https://user-images.githubusercontent.com/8235763/55813053-68e30180-5aec-11e9-87df-7a540229bdc4.png)

**Comment by dgrimey** [comment]
I updated a couple more sites and I did not have it say 3.9.4. Not sure why I got it on the first site. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24537">issues.joomla.org/tracker/joomla-cms/24537</a>.</sub>

**Comment by infograf768** [comment]
As I can't either reproduce the issue, closing.
