### ISSUE TITLE
[4.0] Workflow Buttons not working when page navigated using browser back/forward keys

### ISSUE THREAD

**Issue by Puneet-Jain-18** [joomla/joomla-cms#24545]
### Steps to reproduce the issue
Go to backend
Administrator/content/articles
**Select checkbox of any article**
Go to any other website(eg www.google.com) by entering URL in the same tab
navigate back to Joomla using browser back button

### Expected result

Work Flow buttons are still accessible when the checkbox is clicked

### Actual result
![Screenshot (49)](https://user-images.githubusercontent.com/34083630/55892187-76bf8200-5bd3-11e9-8989-53768b1c61e8.png)

### System information (as much as possible)

Joomla! 4.0.0-alpha8-dev

### Additional comments
a) works fine if no articles are selected before navigating to another website
b) Starts working if additional articles are selected with articles that were selected before navigating to another website

**Comment by hardik-codes** [comment]
Issue confirmed

**Comment by maliouris** [comment]
I have made a pr for this a long time ago https://github.com/joomla/joomla-cms/pull/24328

**Comment by Puneet-Jain-18** [comment]
I would check out your PR in some time thanks!!

**Comment by ghost** [comment]
Closed as having Pull Request #24328
