### ISSUE TITLE
[4.0] Resolve B/C break in BaseDatabaseModel

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#24559]
The `LeagcyModelLoaderTrait` is having unexpected behaviour in J4. The static variable used to load the classes is unfortunately initialised per class. This means changing `BaseDatabaseModel::getInstance()`/`JModelLegacy::getInstance()` to `BaseModel::getInstance()` - this is not an intended b/c break. Options are:

- Move the trait to `BaseDatabaseModel` from `BaseModel`
- Rework the static variable to one in the trait. However this will allow 3rd parties to override it which isn't intended.

This has been an issue I've had to manually patch in the action logs and privacy components (e.g. https://github.com/joomla/joomla-cms/pull/24555/commits/494a5672df21d7d63afce72f8f4a59f33744f939), so is definitely a real thing for components migrating from J3 to J4

**Comment by jwaisner** [comment]
Increasing priority as per guidelines for beta-blockers.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24559">issues.joomla.org/tracker/joomla-cms/24559</a>.</sub>

**Comment by wilsonge** [comment]
Agreed in meeting to remove methods + properties from the trait

**Comment by rdeutz** [comment]
Closing because we have a PR #27998
