### ISSUE TITLE
Syntax error when using Quotation mark EN

### ISSUE THREAD

**Issue by ch2856** [joomla/joomla-cms#24552]
### Steps to reproduce the issue
create a new article and at the title write " (Quotation mark HEX CODE:&#x22;) and save. try to load this article on the frontend.

### Expected result
Page should load

### Actual result

Error decoding JSON data: Syntax error

### System information (as much as possible)

j 3.9.5 
Mac OS

### Additional comments
1. It happens only with MacOS quote in English (")
2. Issue started after updating top J3.9.5
3. trying to use &#x22; in the title didn't solve it.

**Comment by ch2856** [comment]
HEX Code & #x22;<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24552">issues.joomla.org/tracker/joomla-cms/24552</a>.</sub>

**Comment by ghost** [comment]
Can't confirm (see "Getting Started at https://fw3.joomla.com/)

![Screen Shot 2019-04-11 at 06 52 39](https://user-images.githubusercontent.com/8235763/55931623-95029d80-5c26-11e9-9dc3-fc9643b47128.png)
### System information
- 3.9, latest nightly build
- Template: Protostar
- macOS High Sierra, 10.13.6
- Firefox 66 (64-bit)
#### CloudAccess.net
- PHP 7.1.27
- MySQLi 5.7.24-cll-lve

**Comment by infograf768** [comment]
Can't confirm either
using
`&#x22;Myarticle&#x22;` as title
when saved is transformed to
`&quot;Myarticle&quot;` as title
and `myarticle` as alias

**Comment by ch2856** [comment]
Thanks guys. I have tested it on different test site now and no issues, I guess it's some issue I need to check on the local server (XAMPP 7.1.24).

**Comment by ghost** [comment]
@ch2856 Thanks for Report anyway :-)
