### ISSUE TITLE
Not able to edit TinyMCE Editor Plugin - Loading forever

### ISSUE THREAD

**Issue by sajalaspl** [joomla/joomla-cms#24554]
### Steps to reproduce the issue
I've Joomla 3.9.1 version. And I'm facing an interesting issue. I am not able to edit the "Editor - TinyMCE" plugin from the back-end. I've checked that it's not locked. Following is the URL which takes forever to load.

/administrator/index.php?option=com_plugins&task=plugin.edit&extension_id=412

I have tried to debug code and found out the issue in the following code in "administrator/components/com_plugins/views/plugin/tmpl/edit.php" file.

```
<?php
				$this->fieldset = 'basic';
				$html = JLayoutHelper::render('joomla.edit.fieldset', $this);
				echo $html ? '<hr />' . $html : '';
?>
```

If I comment the "$html = JLayoutHelper::render('joomla.edit.fieldset', $this);" line, it loads the edit plugin interface, but blank page with generic options. If I change $this->fieldset from "basic' to 'advanced' it also works.

So, there's something with 'basic' option.

Can anyone help on this?

**Comment by ghost** [comment]
Please update on latest Release: https://github.com/joomla/joomla-cms/releases/tag/3.9.5, so closing the Issue.
