### ISSUE TITLE
categoryedit JFormField set attribute allowAdd to false problem

### ISSUE THREAD

**Issue by rolandalsace** [joomla/joomla-cms#24566]
Hi.

Joomla 3.9.5

It's not possible to change the allowAdd attribute of the JFormField categoryedit to false.

In /administrator/component/com_categories/models/fields/categoryedit.php

line : 59 we set $this->allowAdd to blank or to a simplexmlelement

line : 344 		if ($this->allowAdd)
		{

Here we tests $this->allowAdd as booleen, so when it's an SimpleXMLElement (wich is generaly the case),
this test return always true.

So if we make a 
$form->setFieldAttribute('catid','allowAdd','false'); 

This have no effect, and worse it is interpreted as true.

Regards

### Steps to reproduce the issue

Always

**Comment by ghost** [comment]
@HLeithner can you please comment?

**Comment by rolandalsace** [comment]
Hi Franz.

What do you want to know else ?

With x-debug i see that (see in my description above)  that in line 344 of /administrator/component/com_categories/models/fields/categoryedit.php 
$this->allowAdd is tested as booleen and as this variable is of type SimpleXMLElement, the condition is always true.

So a $form->setFieldAttribute('catid','allowAdd','false'); has no effect.

I do not see what I can explain in more detail.

Regards.

**Comment by ghost** [comment]
> What do you want to know else ?

i'm calling Harald as Release Lead, i'm user no Dev.

**Comment by rolandalsace** [comment]
I suggest to change in line 57 of /administrator/component/com_categories/models/fields/categoryedit.php

$this->allowAdd = isset($this->element['allowAdd']) ? $this->element['allowAdd'] : '';

by

$this->allowAdd = isset($this->element['allowAdd']) ? (bool)filter_var((((array)$this->element->attributes())['@attributes']['allowAdd']), FILTER_VALIDATE_BOOLEAN) : '';

This solve the problème.

Regards.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24566">issues.joomla.org/tracker/joomla-cms/24566</a>.</sub>

**Comment by rolandalsace** [comment]
or

$this->allowAdd = isset($this->element['allowAdd']) ? (bool)filter_var((((array)$this->element->attributes())['@attributes']['allowAdd']), FILTER_VALIDATE_BOOLEAN) : false;
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24566">issues.joomla.org/tracker/joomla-cms/24566</a>.</sub>

**Comment by alikon** [comment]
please do pr

**Comment by hardik-codes** [comment]
please test #24574

**Comment by ghost** [comment]
Closed as having Pull Request.
