### ISSUE TITLE
Install from Web - Ordering First/Last

### ISSUE THREAD

**Issue by RolandSM** [joomla/joomla-cms#24564]
Hi,

I´m missing the ordering option of the Web Installer? Why it was removed?
This was very useful to set it for example as last Tab, so when I click to Install no connection to the catalogue is done.

**Comment by brianteeman** [comment]
Just order the install plugins in the order you want in the plugin manager

**Comment by ghost** [comment]
Closed as expected Behaviour.

**Comment by RolandSM** [comment]
Oh no, I'm ashamed...
