### ISSUE TITLE
[4.0] class "Multilanguage" or "JLanguageMultilang" ?

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#24568]
Today's install via CLI : 12/4/2019

Fatal error after install: 
Class 'Joomla\Module\Menu\Site\Helper\JLanguageMultilang' not found 
in
/modules/mod_menu/Helper/MenuHelper.php line 129
The only class I found is:
Multilanguage in
/libraries/src/Language/Multilanguage.php
This one works.

I guess it's a mix-up in the naming of class. Didn't make a pull request, not sure about the right class name.

**Comment by alikon** [comment]
please test #24569

**Comment by infograf768** [comment]
closing as we have apatch
