### ISSUE TITLE
[3.9.5 Update Error] Invalid Ajax Data Update from 3.9.4

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#24570]
Is there any report on Error: Invalid Ajax Data when upgrading from 3.9.4 to 3.9.5?

### System information (as much as possible)
 
PHP Built On | Linux centos-01.localdomain 3.10.0-862.6.3.el7.x86_64 #1 SMP Tue Jun 26 16:32:21 UTC 2018 x86_64
Database Type | mysql
Database Version | 5.5.60-MariaDB
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.1.22
Web Server | nginx/1.12.2
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 3.9.4 Stable [ Amani ] 12-March-2019 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

### Additional comments

I am having this issue in 1 server with multiple domains (3).

**Comment by HLeithner** [comment]
No, not till now. Please add some information so we can help.

**Comment by ghost** [comment]
@frogydiak have you asked on [Forum](https://forum.joomla.org/)?

**Comment by Quy** [comment]
Here is a [related issue](https://forum.joomla.org/viewtopic.php?t=954808) from Joomla Forum. Please post to Joomla Forum for assistance. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24570">issues.joomla.org/tracker/joomla-cms/24570</a>.</sub>
