### ISSUE TITLE
[4.0] Module Edit: Position is empty coming form cPanel

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#24575]
### Steps to reproduce the issue
Go to cPanel in the backend. 
Edit one of the modules.

### Expected result
The Module is opened and the position of the module is "cpanel", other positions of the backend template are visible in the position dropdown. 

### Actual result
Sometimes (not always) the position of module then is  "none" and there are only positions of the frontend template visible, not from the backend template.
It seems that in some situations the client is not set properly.

**Comment by ghost** [comment]
Issue confirmed.

**Comment by infograf768** [comment]
It looks like this happens when the admin modules manager has not been displayed yet during the session. Therefore the default is site positions.

**Comment by infograf768** [comment]
We just have to change the userstate. Making PR now

**Comment by infograf768** [comment]
Closing as we have a patch https://github.com/joomla/joomla-cms/pull/24583

Please test

**Comment by SharkyKZ** [comment]
Test PR #24698 please.
