### ISSUE TITLE
[4.0] "User Actions Log" repeats in Components Menu

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#24578]
### Steps to reproduce the issue
Open the Control Panel > Components.
At the bottom of the list, the "User Actions Log" links are duplicated.
This the April 13 Nightly Build, but it appeared in several builds earlier.

### Expected result
Only one link should display; not duplicates.

**Comment by ghost** [comment]
@chmst can you please have a look?

**Comment by alikon** [comment]
can't confirm with current staging

**Comment by chmst** [comment]
I cannot confirm. @200MPHMEDIA please check the list ofyour admin modules, if there are two items for action logs.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24578">issues.joomla.org/tracker/joomla-cms/24578</a>.</sub>

**Comment by 200MPHMEDIA** [comment]
Still appeared with double entrees.  Performed a fresh install and now the list shows properly with only a single link.  Might be that when uploading nightly builds and fixing the database tables, this was overlooked or missed.  In any case, now sorted.  Thanks for the response.

**Comment by ghost** [comment]
@200MPHMEDIA please close an issue if its solved. Thanks for your Report.
