### ISSUE TITLE
[4.0] Table '#_action_logs_users' doesn't exist

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#24571]
### Steps to reproduce the issue

Open Admin-Module "Recently Added Articles" and save got ```1146 Table '#_action_logs_users' doesn't exist```

Database-Fix don't change Behaviour, after save of an Component (Article, Menu, ...) or Click on Logout-Button the Error is shown.
### System information
Setting | Value
-- | --
PHP Built On | Linux lamp122.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.7.el6h.x86_64 nr.1 SMP Mon Dec 17 12:02:35 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.24-cll-lve
Database Collation | utf8_general_ci
Database Connection Collation | utf8_general_ci
PHP Version | 7.1.26
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Latest Nightly Build Update from Joomla! 4.0.0-alpha8-dev Development [ Amani ] 9-March-2019 13:41 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by alikon** [comment]
probably due to nightly build unable to replicate on staging

**Comment by chmst** [comment]
confirmed. After pulling the latest changes. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24571">issues.joomla.org/tracker/joomla-cms/24571</a>.</sub>

**Comment by chmst** [comment]
I could store the table via sql by removing all " in the sql update file (MariaDB)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24571">issues.joomla.org/tracker/joomla-cms/24571</a>.</sub>

**Comment by alikon** [comment]
so are you both updating from a previous 4.0 version  and not starting from scratch ?

**Comment by ghost** [comment]
yes, Update to nightly build.

**Comment by chmst** [comment]
yes, pulling yesterday's updates from v4.0 dev. It is normal that the table is not stored, but in general I cn do a database fix. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24571">issues.joomla.org/tracker/joomla-cms/24571</a>.</sub>

**Comment by alikon** [comment]
in that case then i personally  don't care too much on these issues .... there are a lot of work in progress to port 3.9 to 4.0.... and iirc there is no update path from a nightly build to another

**Comment by ghost** [comment]
thanks @alikon, closing for that reason

**Comment by ghost** [comment]
Additional Info: Until beta there can't be guarantee an upgrade path.
