### ISSUE TITLE
[4.0] overflow dropdown of latest action settings icon

### ISSUE THREAD

**Issue by Puneet-Jain-18** [joomla/joomla-cms#24582]
### Steps to reproduce the issue

Go to control panel at the backend, click on settings icon of **latest action** 

### Expected result
The dropdown opens towards the left to prevent overflow

### Actual result
![rec3](https://user-images.githubusercontent.com/34083630/56089081-cdb2a900-5eaa-11e9-8848-3485ad6c89fd.gif)

### System information (as much as possible)

Joomla! 4.0.0-alpha8-dev

**Comment by Puneet-Jain-18** [comment]
@brianteeman should I work on this, Or this is a same type of issue as we discussed here: (https://github.com/joomla/joomla-cms/pull/24579#issuecomment-482835968)

**Comment by brianteeman** [comment]
This has been resolved elsewhere and can be closed
![image](https://user-images.githubusercontent.com/1296369/64987047-438ac880-d8c0-11e9-9c05-a752c5cbef28.png)

**Comment by Quy** [comment]
Fixed with PR #25815<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24582">issues.joomla.org/tracker/joomla-cms/24582</a>.</sub>
