### ISSUE TITLE
[4.0] Text in title of cheched_out shows HTML-Tags

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#24584]
### Steps to reproduce the issue

Move Curser over Icon "Checked_out" in any View. You see a hint using the title-attribut that show HTML-tags.

![Bildschirmfoto von 2019 04 14 12 28 05](https://user-images.githubusercontent.com/9974686/56091643-b6c38500-5eb1-11e9-8eec-63155de955bd.png)

### Expected Result
You see a nice formatted hint. I think we do not want to use the title attribute for this.

**Comment by brianteeman** [comment]
Duplicate report #21373

**Comment by astridx** [comment]
Sorry, I did not see the duplicated issue
