### ISSUE TITLE
Administrator can't change article's author

### ISSUE THREAD

**Issue by panta7** [joomla/joomla-cms#24597]
### Steps to reproduce the issue
Backend login with administrator user. Than create or edit and article and can't change article's author. Only super user can do this.

### Expected result
Not only super user but alsa administrator could change article's author.

### Actual result
Only super user can change article's author.

### System information (as much as possible)
Joomla 3.9.5
Default administration privileges.

**Comment by ReLater** [comment]
I can't confirm your find. I can change the author (Created By) of all articles after I've logged in with Administrator rights.

**Comment by ghost** [comment]
@panta7 have you asked on [Forum](https://forum.joomla.org/) as Github is for coding.

**Comment by panta7** [comment]
Yes, i'm waiting form someone answer. Thanks
[https://forum.joomla.org/viewtopic.php?f=719&t=953203](url)

**Comment by ghost** [comment]
Closing Issue for Reason stated above. Please don't post double Issues on different Sites as all are Volunteers and they should not waste their Time.

**Comment by panta7** [comment]
Ok, sorry.
