### ISSUE TITLE
Categories are not showing via global settings

### ISSUE THREAD

**Issue by cypisekcypisek** [joomla/joomla-cms#24593]
### Steps to reproduce the issue

After recent update to 3.9.4 version all categories but one stopped showing up as a meta tag under a title. **The category that shows (pic attached) is 'News' the one that is not included as a main menu item, any other category that is a menu item disappeared**  (pic attached - should show 'Posted in Business' after the date same as in News example).
Global settings are set to show, but articles are ignoring them. It's working if I change from 'show global' to 'show' in individual articles.
The system is pulling author and date created but not category. 

### Expected result
Category is responding to global settings

### System information (as much as possible)

![screen shot 2019-04-15 at 16 40 56](https://issues.joomla.org/uploads/1/db605bb84661309412079a22d7f3b995.png)

### Additional comments

![screen shot 2019-04-15 at 16 41 07](https://issues.joomla.org/uploads/1/9389c73ca7583b8e5de27f015c7720f6.png)

**Comment by ghost** [comment]
Please ask on [Forum](https://forum.joomla.org/)
