### ISSUE TITLE
[4.0] Dashboard cog goes off screen

### ISSUE THREAD

**Issue by roland-d** [joomla/joomla-cms#24609]
### Steps to reproduce the issue
1. Login to Joomla 4 dashboard
2. Click on the cog to open the menu for that module
<img width="414" alt="image" src="https://user-images.githubusercontent.com/359377/56233173-d1992380-6082-11e9-8106-71861be2337d.png">
3. The menu collapse outside the screen
<img width="408" alt="image" src="https://user-images.githubusercontent.com/359377/56233225-e70e4d80-6082-11e9-865d-143530879899.png">

### Expected result
The menu opens on screen.

### Actual result
The menu opens off screen

### System information (as much as possible)
Joomla! 4.0.0-alpha8-dev
Firefox 66.0 (64-bit)
MacOS 10.14.4

### Additional comments
None

Pinging @coolcat-creations

**Comment by Quy** [comment]
Duplicate #24582<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24609">issues.joomla.org/tracker/joomla-cms/24609</a>.</sub>

**Comment by roland-d** [comment]
Thank you @Quy I searched but did not find that one ;)
