### ISSUE TITLE
PHP Warning:  Use of undefined constant JPATH_COMPONENT

### ISSUE THREAD

**Issue by jjnxpct** [joomla/joomla-cms#24607]
### Steps to reproduce the issue
Cronjob triggers Smart Search plugin to index the content:
/usr/local/bin/php /home/[USER]/domains/[DOMAIN]/public_html/cli/finder_indexer.php --purge

### Expected result
All batches processed without any errors

### Actual result
We see these warnings (in the cron e-mail we receive): 

Warning: Use of undefined constant JPATH_COMPONENT - assumed 'JPATH_COMPONENT' (this will throw an Error in a future version of PHP) in /home/[USER]/domains/[DOMAIN]/public_html/administrator/components/com_fields/models/group.php on line 74

### System information (as much as possible)
Joomla! 3.9.5	
MariaDB 5.5.63
PHP 7.2.16
Apache/2

**Comment by ghost** [comment]
@HLeithner can you please comment?

**Comment by HLeithner** [comment]
@Hackwar  can you look at this?

**Comment by Hackwar** [comment]
This is unrelated to smart search and rather an issue in the fields group model.

**Comment by HLeithner** [comment]
I think that the CLI doesn't provide a component context so JPATH_COMPONENT isn't set while indexing.

But yes the problem seams to be in com_fields that tries to find out which component is active using this constant.

@laoneo Can we remove this check because we only add a table search path here.

**Comment by ReLater** [comment]
Why not adding an additional
`define('JPATH_COMPONENT', JPATH_COMPONENT_ADMINISTRATOR);`
inside cli script.

> I think that the CLI doesn't provide a component context

But `finder_indexer.php` does:
`define('JPATH_COMPONENT_ADMINISTRATOR', JPATH_ADMINISTRATOR . '/components/com_finder');`

**Comment by Quy** [comment]
Please test PR #24630.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24607">issues.joomla.org/tracker/joomla-cms/24607</a>.</sub>

**Comment by alikon** [comment]
please test #24630
