### ISSUE TITLE
New created content (articles,modules) have id=0

### ISSUE THREAD

**Issue by solracsf** [joomla/joomla-cms#24608]
### Steps to reproduce the issue
Create a new module, it is saved with `id=0` and `asset_id=0`

### Expected result
Module has in incremented `id`

### Actual result
Actually `id=0`

Which results in module can't be edited or deleted (it can be Trashed with an error: `Null primary key not allowed` but when try to delete i have `Delete not permitted`.)

IF this module isn't deleted manually from the DB, no other module can't be created as it will trow a duplicated PRIMARY KEY.

The only similar thing found is https://github.com/joomla/joomla-cms/pull/11468

I've reinstalled Joomla core files (trough `com_joomlaupdate`) and Fixed the DB (trough `com_installer`)

### System information (as much as possible)

Setting | Value
-- | --
Database Version | MariaDB-10.3.14
Database Collation | utf8mb4_general_ci
Database Connection Collation | utf8mb4_general_ci
Database driver | pdomysql
PHP Version | 7.2.17
Web Server | Apache/2.4.39 (Unix) OpenSSL/1.1.0g
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 3.9.5 Stable [ Amani ] 9-April-2019 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments

![image](https://user-images.githubusercontent.com/12234510/56206288-4dc44480-604c-11e9-9b19-b58f4255a212.png)

![image](https://user-images.githubusercontent.com/12234510/56206313-5d438d80-604c-11e9-8b2e-80d7b6a291f9.png)

**Comment by ReLater** [comment]
I can't reproduce the issue with Database Type "MySql (PDO)", Joomla 3.9.5, 5.5.5-10.1.34-MariaDB, PHP 7.2.

Normally errors like this occur if your database tables are broken.

Check if the field `id` of table `#__modules` is marked as `AUTO_INCREMENT`.

If not please ask in a forum to get help.

![16-04-_2019_14-21-14](https://user-images.githubusercontent.com/20780646/56209195-35a3f380-6053-11e9-901d-c7e265cccb75.jpg)

**Comment by ghost** [comment]
Closed Issue as stated above.
Please ask on [Forum](https://forum.joomla.org/)

**Comment by solracsf** [comment]
Ok thanks anyway, **forum is completely useless**, my last three questions had no answers at all since weeks. Cheers!

**Comment by ghost** [comment]
Sorry to hear that @acs-ferreira but here are also Forummember so if you Link to the Questions i'm sure they will answer (@wojsmol)

**Comment by solracsf** [comment]
No problem, thanks.
I've managed to solve it myself, it was indeed an `AUTO_INCREMENT` problem.

**Comment by ghost** [comment]
thanks @ReLater for help.
