### ISSUE TITLE
Style - Menuitem Assignement: Checkboxes disappear when the menu alias is named "hidden"

### ISSUE THREAD

**Issue by jbjhjm** [joomla/joomla-cms#24605]
### Steps to reproduce the issue

Create a new Menu named Hidden and set the menutype to "hidden".
Add a menu item to that menu.
Open a template style and check the menu associations tab.

### Expected result
A visible checkbox to associate the template style with the created menu item.

### Actual result
No checkbox visible. Reason for that is the menu alias will be added to the Input tag as a class - without any prefix. So it becomes input[type=checkbox].hidden which is a class used by bootstrap to hide stuff.

Issue is present in 3.9.5.

**Comment by infograf768** [comment]
Modified "Associations" to "Assignment" as these are different functions. ;)

I confirm the behavior.
<img width="428" alt="Screen Shot 2019-04-16 at 11 05 28" src="https://user-images.githubusercontent.com/869724/56196682-97eefb00-6037-11e9-8ef0-7edbc1392334.png">

Not much we can do imho. We "could" prevent using "hidden" as menu type, but are we sure it is the only Menu Type that we should not accept?

**Comment by infograf768** [comment]
If we add around https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/models/menu.php#L216
```
		if ($data['menutype'] == 'hidden')
		{
			$this->setError(JText::sprintf('COM_MENU_MENU_TYPE_FORBIDDEN', $data['menutype']));

			return false;
		}
```
and the lang string, 
`COM_MENU_MENU_TYPE_FORBIDDEN="The Menu Type \"%s\" is forbidden. Please use another Menu Type."`

we can get:

<img width="730" alt="Screen Shot 2019-04-16 at 11 35 26" src="https://user-images.githubusercontent.com/869724/56199521-5b260280-603d-11e9-9a26-625a266ec68b.png">

I just wonder if there are other terms that should be forbidden.

**Comment by infograf768** [comment]
@HLeithner 
What do you think?

**Comment by HLeithner** [comment]
sounds wrong, why I'm not allowed to create a menu type "hidden" I think I created many of them.

The checkbox gets the menu name as class attribute and hidden has a special meaning. I'm not sure why the menu alias is in the class of the checkbox... maybe prefixing it or removing it...

**Comment by infograf768** [comment]
Indeed. The code is
`class="chk-menulink <?php echo $type->menutype; ?>"`

But would not changing that break B/C?

**Comment by ReLater** [comment]
I would prefix it with something like
`class="chk-menulink <?php echo 'menutype-' . $type->menutype; ?>"`

We need 3 prefixes then in code of `edit_assignment.php`

And because it's a bug that must be fixed I wouldn't care about B/C in this case.

**Comment by ReLater** [comment]
Or creating an override for the ISIS template for `edit_assignment.php` with these changes.

**Comment by brianteeman** [comment]
is there even a need to have the menutype in the class name? 

The menutype exists for the javascript to identify the checkbox and not for any styling. So that can easily and correctly be changed to a data- attribute instead.

As for b/c this is only in the admin ui AND rendered markup is not part of the B/C policy

**Comment by brianteeman** [comment]
OR the code could be written exactly the same as the selector in the module assignment

**Comment by HLeithner** [comment]
@brianteeman can you create a pr for this? I would suggest do the same as in module assignment

**Comment by brianteeman** [comment]
sorry i dont have time to do anything on j3

**Comment by Quy** [comment]
Please test PR #25454.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24605">issues.joomla.org/tracker/joomla-cms/24605</a>.</sub>
