### ISSUE TITLE
htaccess not updated in new version

### ISSUE THREAD

**Issue by eric-lamy-agerix** [joomla/joomla-cms#24617]
Since 3.9 version we have an admin messages displayed and since 3.9.3 one of these messages is :
The security team recommends to manually apply the necessary changes to existing .htaccess or web.config files, as those files can not be updated automatically.

Changes for .htaccess
(***)
Changes for web.config
Add the following lines right after "</rewrite>":
(...)

I think it could be a good idea to change the htaccess wich is on new version. For example if you dowmload the last version 3.5.9 you get the old htaccess.

Thx for reading me and have a nice day ;)

**Comment by HLeithner** [comment]
htaccess.txt has been changed with the same release: https://github.com/joomla/joomla-cms/commit/8fdbcb163040ff7b8fd12fb27bbfae76816bdad3#diff-05d39072fa81e84ead7860131f02ea3f
