### ISSUE TITLE
Joomla (extension) updates fail with misleading message after incorrect file test

### ISSUE THREAD

**Issue by brettdelmage** [joomla/joomla-cms#24616]
### Observed error

Various package updates fail with the misleading message "Failed deleting inaccessible file".
The message / error appears to be generated in
public static function delete
in libraries/vendor/joomla/filesystem/src/File.php

The error is thrown when a file cannot be chmod'd.

This error will occur when the file is OWNed by other than the webserver or php process.  e.g. php-fpm.

HOWEVER the file and the directory it is in may still be writeable by the webserver or php process or other (e.g. on Linux) and therefore actually deletable.

Checking file ownership may not be an appropriate test for file deletability. In very secure installations Joomla and web file ownerships may be deliberately set during normal operation to an owner other than the webserver or php process. File and directory write permissions could be enabled temporarily by the admin before doing an update (as I do).

### Steps to reproduce the issue

1. Set Joomla file ownership to an ID other than that of the webserver or php process  e.g. php-fpm
2. Set Joomla file permissions to 666 and directory permissions to 777
3. Attempt a Joomla core or extension update
4. Observe failure message.

### Expected result

The Joomla core or extension update should complete without error

### Actual result

The Joomla core or extension update fails with the misleading message "Failed deleting inaccessible file".

### System information (as much as possible)

Any Linux or Unix system

**Comment by Quy** [comment]
Related #23504 ?

**Comment by ghost** [comment]
@brettdelmage I guess you Report about J3 so i set J3 Issue-Label. Please give System Information reporting an Issue.

**Comment by alikon** [comment]
yes @Quy same issue like #23504

**Comment by ghost** [comment]
Closed as duplicate Report. @brettdelmage thanks for Report, don't hesitate to report further.

@Quy @alikon thanks for finding Duplicate.

**Comment by brettdelmage** [comment]
> @brettdelmage I guess you Report about J3 so i set J3 Issue-Label.
Thanks, I am new to this so overlooked that.
> Please give System Information reporting an Issue.
As I reported, the System version is _irrelevant_, otherwise I would have included it. Thanks.
