### ISSUE TITLE
Articles of subcateogries are not displayed on Menu blog page

### ISSUE THREAD

**Issue by FormationGrowthHacking** [joomla/joomla-cms#24614]
### Steps to reproduce the issue
Create 1 main category "Blog"
Then create subcategories in this main categorie:
 - Blog
   -- Cat1
   -- Cat2

Then create articles in category blog and subcategories Cat1 & Cat2

Then create a Menu "XLayout Blog" for main category "Blog". I name this menu "Blog".

I configured options of articles Subcategory Levels= All in both tabs "Category" & "Categories".
I configured In menu, Include Subcategories=All

### Expected result

When clicking on this menu "BLog". I suppose to see list of articles of main cateogry and subcategories. 

### Actual result

It shows only articles of main category blog. It doesn't show articles of subcategories.

### System information (as much as possible)
PHP Version | 7.1.24
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.8.11 Stable [ Amani ] 31-July-2018 14:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
mysql Database Version | 5.6.41-84.1

### Additional comments

This issue seems to be very old. I saw it everywhere on forums.
![joomla_issue4](https://user-images.githubusercontent.com/49636922/56242799-5c851880-6099-11e9-8825-9084650c1524.jpg)
![joomla_issue3](https://user-images.githubusercontent.com/49636922/56242800-5c851880-6099-11e9-9348-960bc922320d.jpg)
![joomla_issue2](https://user-images.githubusercontent.com/49636922/56242801-5d1daf00-6099-11e9-9229-c016c1c53c1c.jpg)
![joomla_issue1](https://user-images.githubusercontent.com/49636922/56242802-5d1daf00-6099-11e9-9ebc-7fa1cc959d68.jpg)

**Comment by ReLater** [comment]
Please close your issue here on GitHub and ask in a forum because you are using an outdated, old version of Joomla (Joomla! 3.8.11 Stable) and this platform is only for issues with current and future versions .

(In secret: You forgot this setting:
![16-04-_2019_22-52-31](https://user-images.githubusercontent.com/20780646/56243561-32345a80-609b-11e9-8734-961ccbb4b287.jpg)
)

**Comment by FormationGrowthHacking** [comment]
I am sorry. I didnt know.
  

  
I will try tgis asap. Thank you so much.
  
  
  

  
  
  

  
  
>

**Comment by FormationGrowthHacking** [comment]
Ok. Just for info, I did activate this.
  

  
I will post issue on forum.
       

     
  

  
  
>
