### ISSUE TITLE
[4.0] TinyMCE Toggle Button Location

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#24622]
### Steps to reproduce the issue
At present, the "Toggle" Button on the TinyMCE Editor is at the bottom right of the editor window area.  It is the only link/button in that location.

It is very inconvenient to scroll down to toggle to html view.  

Previoulsy, the button was located at the top left window area, making it very convenient to toggle the views back and forth.

Can the "Toggle" Link be moved from bottom right to top left.

**Comment by ghost** [comment]
Duplicate of #24076 > @200MPHMEDIA please check.
