### ISSUE TITLE
[4.0] I see literal language strings in the actions module in the administrator on the cpanel

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#24629]
### Steps to reproduce the issue
Install J4 go to cPanel.
Actions module has these strings

`PLG_SYSTEM_ACTIONLOGS_CONTENT_UPDATED`

### Expected result
Translated text

### Actual result
Literal language string

### System information (as much as possible)
[systeminfo-2019-04-17T11_09_01-04_00.txt](https://github.com/joomla/joomla-cms/files/3090336/systeminfo-2019-04-17T11_09_01-04_00.txt)

**Comment by ReLater** [comment]
Related: https://github.com/joomla/joomla-cms/issues/22816
