### ISSUE TITLE
Frontend editing Permission issue

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#24626]
### Steps to reproduce the issue
Install staging with **ANY** sample data.
Login frontend as Super User
Click gear icon and select edit
Select 'Publishing' tab

### Expected result
You should be able to change category

### Actual result
Category dropdown llist is greyed out

### Additional comments
Have set 'Critical because if there is an error in ACL there could be others

**Comment by brianteeman** [comment]
This is not critical See https://docs.joomla.org/Bug_and_Issue_Tracker_Priority

**Comment by X-Bumble** [comment]
I can confirm this issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24626">issues.joomla.org/tracker/joomla-cms/24626</a>.</sub>

**Comment by X-Bumble** [comment]
I can confirm this issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24626">issues.joomla.org/tracker/joomla-cms/24626</a>.</sub>

**Comment by brianteeman** [comment]
Which sample data - there are several in j3

**Comment by infograf768** [comment]
This was done on purpose.
See https://github.com/joomla/joomla-cms/pull/24216

**Comment by brianteeman** [comment]
that was a hard breaking backwards compatibility issue that should not have been done in a patch release at all. @HLeithner

**Comment by infograf768** [comment]
It was MUCH more dangerous before
Read https://github.com/joomla/joomla-cms/issues/23991

**Comment by brianteeman** [comment]
So you solved the create category bug by completing disabling the ability to change category 🤦‍♂️ 

@HLeithner correctly said
> If it's this way we can't change it in 3.9 but we should fix the "create" category bug.

**Comment by Webdongle** [comment]
Surely changing category should be linked with 'Edit state'.  i.e. if A user is trusted to publish/unpublish an Article then they should be trusted to change Category?  After all users could only select a category that they had edit Permissions for.

**Comment by infograf768** [comment]
@Webdongle 
the problem was larger than that in the sense that even with edit state, one may not know the full backend category structure when in frontend.
The readonly is only when editing an already saved article.

**Comment by brianteeman** [comment]
All that should have been changed was the ability to create a new category.

Everything else is a hard b/c break that should never me done in a patch release

**Comment by dfrassi** [comment]
I'm sorry but my users are in panic because they don't find the way to push an article in another category by frontend.
Let me know if i have to downgrade the joomla version.
Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24626">issues.joomla.org/tracker/joomla-cms/24626</a>.</sub>

**Comment by Webdongle** [comment]
Using an older version of Joomla is a security risk ... and you would loose everything new after installing an old backup.  Work around would be
Create a new user group with Registered as Parent
Allow backend access
Article Permissions allow 'Access Administration Interface '
Put you required users in that new group
They can log in /administrator and only see the Articles/Categories

**Comment by dfrassi** [comment]
I have got 5.000 users in my site, it's a big drama to teaching them a new editing mode of their contents. Are you really want to mantain this feature? Are there any other possibility to solve this problem?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24626">issues.joomla.org/tracker/joomla-cms/24626</a>.</sub>

**Comment by HLeithner** [comment]
@dfrassi at the moment you can revert the changes from the related PR: https://github.com/joomla/joomla-cms/pull/24216/files

**Comment by peteruoi** [comment]
Plz don't do the following advice before backing up and someone else much more experienced than me confirms that this will work.
I think that reverting the changes in this file https://github.com/joomla/joomla-cms/pull/24216/files
will return the previous behaviour. I think that these changes where not part of the security holes patched so you don't have that concern. This if of course a temporary sollution as the next update in joomla will overwrite them but maybe PLT decides to revert it too.
Again i have not tested it but if @infograf768 says that this patch caused maybe reverting it will solve it.

**Comment by infograf768** [comment]
@Webdongle 

> Surely changing category should be linked with 'Edit state'. i.e. if A user is trusted to publish/unpublish an Article then they should be trusted to change Category?

See proposal here
https://github.com/joomla/joomla-cms/pull/24640

**Comment by ghost** [comment]
Closed as having Pull Request.

**Comment by Webdongle** [comment]
@infograf768 That patch was merged before I checked it.  great stuff thanks

**Comment by infograf768** [comment]
it is not merged yet. needs one more tester and a decision by @HLeithner

**Comment by infograf768** [comment]
@dfrassi
Have you tested the patch?

**Comment by dfrassi** [comment]
not yet, please can you send me the patched article.php file?

**Comment by ghost** [comment]
@dfrassi how to test > https://docs.joomla.org/Testing_Joomla!_patches

**Comment by dfrassi** [comment]
Ok, i have installed the jtester component, what patch i have to apply?

![jtester](https://user-images.githubusercontent.com/897854/56791323-16515700-6807-11e9-9078-f35bde03f0c2.png)

**Comment by ghost** [comment]
@dfrassi apologies, now i see #24640 is merged. @infograf768 can you please comment?

**Comment by infograf768** [comment]
A merged PR can't be tested by patchtester.
In any case the PR is clear: now the category can be modified (after the article is saved) by users of type Publishers or UP, NOT by their own authors  if they do not have edit.state permissions.

here is the modified article.php to replace
˜/administrator/components/com_content/models/article.php
[article.php.zip](https://github.com/joomla/joomla-cms/files/3120805/article.php.zip)

**Comment by dfrassi** [comment]
ok, now it's right
thanks

**Comment by nzyeehaa** [comment]
On the current joomla release, zero users can edit any existing article from the front end, (even super users). _Joomla is broken and needs an urgent update._

luckily one of my customers contacted me for an urgent resolution. There are others that will just be swearing a lot...
It has wasted four hours of experimenting with permissions/templates and searching for answers to finally find this thread. The majority of Joomla users wont get off that light.
I appreciate the countless work that goes into joomla, however - it doesnt need this bad rap, this has been an oversight - not many end users will use github, and still - nothing shows on any joomla updates

@brianteeman - thanks for your comments.
