### ISSUE TITLE
[com_fields] Field type media. Wrong default value/path in article edit.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#24644]
### Steps to reproduce the issue
- Create a custom field for articles of type `Media`
- Select a directory and enter an existing image name inside that directory as Default Value
![19-04-_2019_15-17-13](https://user-images.githubusercontent.com/20780646/56425884-646dd400-62b6-11e9-94e8-cbbafa257b3b.jpg)
- Save the field
- Open an article and see:

![19-04-_2019_15-19-32](https://user-images.githubusercontent.com/20780646/56425972-b3b40480-62b6-11e9-8773-3f88b9235de2.jpg)
- **The path is wrong. It should be `images/banners/shop-ad.jpg`**

- Don't change the media field and save the article.
- See the article in frontend.
 
![19-04-_2019_15-24-47](https://user-images.githubusercontent.com/20780646/56426134-61bfae80-62b7-11e9-939c-bebbbecd1b6b.jpg)

### Expected result
- Field resolves the directory path correctly.

### Actual result
- Directory path ignored and one have to select the media again (in any article).

**Comment by infograf768** [comment]
I can't reproduce the issue
![Screen Shot 2019-04-29 at 07 53 39](https://user-images.githubusercontent.com/869724/56878352-f5317600-6a53-11e9-8426-0b829e16110c.png)

![Screen Shot 2019-04-29 at 07 53 03](https://user-images.githubusercontent.com/869724/56878361-024e6500-6a54-11e9-8314-ec4b081b5c92.png)

![Screen Shot 2019-04-29 at 07 54 44](https://user-images.githubusercontent.com/869724/56878377-14c89e80-6a54-11e9-9659-81be8e5e08b4.png)

**Comment by infograf768** [comment]
Hmm
You are right.
If we do not select again the image when editing the article, the path is not added.

This means we have to enter the full path to the image in the Default Value

![Screen Shot 2019-04-29 at 08 03 19](https://user-images.githubusercontent.com/869724/56878625-4beb7f80-6a55-11e9-8c73-96bd568d74d1.png)

**Comment by infograf768** [comment]
I have been playing a bit further with this.
The `default_value` field is a textarea and is common to all custom fields.
Could not find an easy way to override the field type in this case.

The following patch could partly (see Note below) solve the issue, but only for the frontend display as it will not allow the preview of the default image when editing the article.
 
```
diff --git a/plugins/fields/media/tmpl/media.php b/plugins/fields/media/tmpl/media.php
index 1707e09..981093e 100644
--- a/plugins/fields/media/tmpl/media.php
+++ b/plugins/fields/media/tmpl/media.php
@@ -9,4 +9,6 @@
 defined('_JEXEC') or die;
 
+use Joomla\CMS\Component\ComponentHelper;
+
 if ($field->value == '')
 {
@@ -22,4 +24,8 @@
 
 $value  = (array) $field->value;
+
+$directory = $fieldParams->get('directory') ? $fieldParams->get('directory') . '/' : '';
+$imagePath = ComponentHelper::getParams('com_media')->get('image_path', 'images') . '/';
+
 $buffer = '';
 
@@ -31,4 +37,9 @@
 	}
 
+	if (!strpos($path, '/'))
+	{
+		$path = $imagePath . $directory . $path;
+	}
+
 	$buffer .= sprintf('<img src="%s"%s>',
 		htmlentities($path, ENT_COMPAT, 'UTF-8', true),
```

**Note:** I am using above the variable `$imagePath`. 
For this plugin, it will always be `images/` as the directory is defined in the xml. 
This is an important limitation.
The plugin should be improved to let use the default "Path to Images Folder" defined in com_media configuration.

**Comment by ReLater** [comment]
> This means we have to enter the full path to the image in the Default Value

And in field type `Imagelist` we only have to enter the image name. That's at least inconsistent or zero UIX.

##### Back to field of type `media`:

Try this (two different directories). Now the setting `Directory` is completely useless:

![29-04-_2019_10-05-53](https://user-images.githubusercontent.com/20780646/56883291-8873a700-6a66-11e9-9f24-a07d0af8a508.jpg)

Go into article. In field click `Select` or `Clear and then Select`. The media manager opens `images/banners/` but not `images/sampledata/fruitshop`.

**Comment by infograf768** [comment]
> And in field type Imagelist we only have to enter the image name

Is that working really?
I always get `The default value is invalid.`

**Comment by ReLater** [comment]
> I always get The default value is invalid.

I forgot to mention pr https://github.com/joomla/joomla-cms/pull/24643

Maybe also of interest in this context: https://github.com/joomla/joomla-cms/issues/23568
