### ISSUE TITLE
Banner tracks raise a 500 error [postgresql]

### ISSUE THREAD

**Issue by twister65** [joomla/joomla-cms#24649]
### Steps to reproduce the issue
Install Joomla with examples. The database must be postgreSQL.
Go to Components->Banners->Banners.
Click Support Joomla! banner.
Click the Banner Details tab.
Select Yes for "Track Impressions" and "Track Clicks".
Go to the example site:
index.php/using-joomla/extensions/modules/display-modules/banner

### Actual result
![banner_tracks](https://user-images.githubusercontent.com/26852967/56466911-6bacf300-6418-11e9-991a-522b9662e0cc.png)

### System information (as much as possible)

php: Linux pc-salon 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64
dbserver: postgresql
dbversion: 9.5.6
dbcollation: C
dbconnectioncollation: UTF8
phpversion: 7.2.15-0ubuntu0.18.04.2
server: Apache/2.4.29 (Ubuntu)
sapi_name: apache2handler
version: Joomla! 3.9.5 Stable [ Amani ] 9-April-2019 15:00 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/73.0.3683.86 Chrome/73.0.3683.86 Safari/537.36

**Comment by ghost** [comment]
Please post System Information in Comment, thanks.

**Comment by alikon** [comment]
@twister65 
we have made 2 fix for the same issue present on postgresql 
we are the only 2 working on postgresql :+1:

**Comment by ghost** [comment]
Closed as having Pull Request #24651, #24652

**Comment by alikon** [comment]
@franz-wohlkoenig better we have 2 pr #24651, #24652

**Comment by ghost** [comment]
@alikon comment updated by second Pull Request-#
