### ISSUE TITLE
[4.0] Lost responsiveness of menubar of new article

### ISSUE THREAD

**Issue by Puneet-Jain-18** [joomla/joomla-cms#24645]
### Steps to reproduce the issue
go to administrator=>content=>articles=>new=>publish tab
Resize tab to a small width,
The menubar changes according to responsive design

![Screenshot (65)](https://user-images.githubusercontent.com/34083630/56434168-19bd7d80-62f1-11e9-8950-b583a64f49e7.png)

**Reload the screen at the same width**

### Expected result

The page is displayed with similar responsive menubar

### Actual result
Responsiveness is lost and a horizontal scrollbar is added

![menubar2](https://user-images.githubusercontent.com/34083630/56434080-c6e3c600-62f0-11e9-88c0-a1ca18ad8b2c.gif)

### System information (as much as possible)

Joomla! 4.0.0-alpha8-dev

**Comment by ReLater** [comment]
Confirmed with current nightly build Joomla_4.0.0-alpha9-dev, 20 April 2019 02:00:48 UTC

@franz-wohlkoenig 
I think this issue should get a "J4 Backend Template" label (?)

**Comment by ghost** [comment]
thanks @ReLater

**Comment by Quy** [comment]
Unable to reproduce. Please check again.

**Comment by alikon** [comment]
no more replicable, fixed elsewhere<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24645">issues.joomla.org/tracker/joomla-cms/24645</a>.</sub>
