### ISSUE TITLE
In Contacts, line including title and alias is not wrapped, table width is increased instead

### ISSUE THREAD

**Issue by kofaysi** [joomla/joomla-cms#24650]
### Steps to reproduce the issue

Create contact with a title of 200+ characters

### Expected result

The Title (Alias) line to be wrapped in /administrator/index.php?option=com_contact view

### Actual result

The Title (alias) line is not wrapped and the table width of the contact list is increased. Columns of Access, Hits, Language and ID are behind the right edge of the screen (scrolling is required).

### System information (as much as possible)

Joomla! 3.9.5

The `nowrap` class is the culprit.
https://github.com/joomla/joomla-cms/blob/fe597ef10fe6d6f0841bebc8aeebaad72d7080f3/administrator/components/com_contact/views/contacts/tmpl/default.php#L138

### Additional comments

The CSS definition for `nowrap` and `has-context` does not have effect:
https://github.com/joomla/joomla-cms/blob/d3fb98cb9ba20a6e03b78ba7ee269b336c04862f/administrator/templates/isis/less/blocks/_tables.less#L72

**Comment by ghost** [comment]
Closed as having Pull Request.
