### ISSUE TITLE
Media manager plugin does not work in content plugins

### ISSUE THREAD

**Issue by pixxelfactory** [joomla/joomla-cms#24653]
### Steps to reproduce the issue
- Install another media-manager (in our case just install JCE, it comes with a cool media manager)
- Create a content-plugin to add fields to the standard joomla articles (we use repeatable subforms, so we have to use a custom content-plugin)
- Insert a media-field as field inside the subform
- It shows the standard (not so powerful) Joomla-Media manager, where as in other areas (modules...) the media-fields media-manager is replaced with the JCE manager

### Expected result
Media fields inside content plugins show the 3rd-party media-manager

### Actual result
The standard joomla media-manager shows up

### System information (as much as possible)
- Joomla 3.9.5 clean install
- JCE as primary editor

### Additional comments
I wrote it as a bug-report, since i think that it is a Joomla-related issue, since in modules ecc. the 3rd-party media-manager shows up, only in content-plugin fields we get the not-so-cool joomla media manager.

**Comment by brianteeman** [comment]
This is an issue for JCE to resolve and should be closed here and reported to them directly

**Comment by ghost** [comment]
Thanks for reporting Issue @pixxelfactory, closed as stated above.
