### ISSUE TITLE
Hyphen not allowed anymore in MySQL database name?

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-cms#24657]
It seems not possible anymore to use a hyphen in a MySQL database name (like "joomla-cms").

### Steps to reproduce the issue
Install Joomla and use a database name with a hyphen in the name, for example joomla-cms

### Expected result
In Joomla 3.x you could use a hyphen in the database name. 
I would expect to do the same in Joomla 4.

### Actual result
Trying to use a MySQL database called "joomla-cms" resulted in the following warning:
_The database name is invalid. It must start with a letter, followed by alphanumeric characters._

A workaround is to use an underscore instead, like joomla-cms

### System information (as much as possible)
Joomla 4.0-dev
PHP 7.2.17-1
MySQL 5.5.5-10.1.37-MariaDB-0+deb9u1

**Comment by brianteeman** [comment]
This is the relevant line in the code
https://github.com/joomla/joomla-cms/blob/6a360e96a8eab76239c8c0a2a3d8cb364e1b80e0/installation/src/Model/DatabaseModel.php#L183

**Comment by pe7er** [comment]
PR: https://github.com/joomla/joomla-cms/pull/24658

**Comment by ghost** [comment]
Closed as having Pull Request.
