### ISSUE TITLE
[4.0] Fontawesome icons broken on installation pages

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#24659]
### Steps to reproduce the issue

Checkout latest 4.0-dev (after merge of PR #24648 ), do a `composer install` and an `npm install`, and then run a new installation.

### Expected result

Installation pages show Fontawesome icons.

### Actual result

Installation pages don't show Fontawesome icons, see red marks in following screenshots:

![screen shot 2019-04-21 at 12 10 48](https://issues.joomla.org/uploads/1/d434e0c0857e1211a6fea9c69a3f55d9.png)

![screen shot 2019-04-21 at 12 10 55](https://issues.joomla.org/uploads/1/9772482325ab9d9e55d4fc0bcac41ed5.png)

![screen shot 2019-04-21 at 12 11 00](https://issues.joomla.org/uploads/1/d1fdafea6b44075ca29abb792f519880.png)

![screen shot 2019-04-21 at 12 11 06](https://issues.joomla.org/uploads/1/3316a269e38fdaf0b189b16d82533123.png)

### System information (as much as possible)

Current 4.0-dev after merge of PR #24648 .

### Additional comments

After installation has been finished and I logged in at backend, the icons there were ok, so it just affects the installation pages.

**Comment by richard67** [comment]
@brianteeman Can you check this? Can you reproduce?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24659">issues.joomla.org/tracker/joomla-cms/24659</a>.</sub>

**Comment by richard67** [comment]
I think I found the reason. Am preparing a PR for it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24659">issues.joomla.org/tracker/joomla-cms/24659</a>.</sub>

**Comment by ghost** [comment]
Closed as having Pull Request.
