### ISSUE TITLE
[4.0] Media Manager image edits background

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#24662]
When editing an image with the media manager only one of the tools has a background which is essential when working with transparent or white images.

![image](https://user-images.githubusercontent.com/1296369/56471547-bf84ff80-644b-11e9-8724-59792a3979c4.png)

![image](https://user-images.githubusercontent.com/1296369/56471552-cb70c180-644b-11e9-8a6c-105792144f70.png)

![image](https://user-images.githubusercontent.com/1296369/56471558-db88a100-644b-11e9-9ca3-cc508aabe329.png)

**Comment by chetanmadaan** [comment]
I was able to reproduce this as well.

**Comment by brianteeman** [comment]
Closed see #27785
