### ISSUE TITLE
Click Version Tab from Article page Screen Freezes

### ISSUE THREAD

**Issue by neiljames** [joomla/joomla-cms#24667]
### Steps to reproduce the issue
From article page click the version button

### Expected result
Pop up page for me to access the recent versions

### Actual result

Pop up page appears shaded grey and freezes, The versions/close button/top right cross do not respond to a mouse click. The only way to exit this is to use the browser back button

### System information (as much as possible)

Localhost 3.1.7 64bit services, PHP 7.2.14, Apapache 2.4.37, MySql 5.7.24

**Comment by brianteeman** [comment]
known issue with modals

**Comment by ghost** [comment]
closed as known Issue.
