### ISSUE TITLE
[4.0] TinyMCE add link

### ISSUE THREAD

**Issue by neiljames** [joomla/joomla-cms#24666]
### Steps to reproduce the issue
Highlight text inside the article to add a menu link to point towards an exisiting internal menu link, click the link button and there is no selection choice. However if I highlight text and click the cms button I get the option to choose.

### Expected result

When I click the tinyMce link button I expected to be given a  choice of internal Menu/Article items to link to

### Actual result

No choice for the url, I can only insert/paste an external link

### System information (as much as possible)

Localhost 3.1.7 64bit services, PHP 7.2.14, Apapache 2.4.37, MySql 5.7.24

### Additional comments
Sorry guys if this is not what you want but I have decided to replicate my current website using Joomla 4, This is one issue, dont know if this is the type of help you need

**Comment by ghost** [comment]
@bembelimen is this resolved by #24110?

**Comment by brianteeman** [comment]
@franz-wohlkoenig No it is a different issue. Add link is a tinymmce feature that is not aware of joomla. The cmsactions link is a joomla plugin that is aware of joomla

**Comment by ghost** [comment]
thanks @brianteeman, so clsoing as no core-issue?

**Comment by AndyGaskell** [comment]
If I understand this right, it sounds like perhaps a UX issue.  In the sense that it is a separate flow to create a link to an external URL, or an internal URL.  This being, perhaps sub optimal that the user needs to understand this difference at the start of the "Add a link to an article" work flow.

@neiljames does that sound like what you were thinking?

Click on TinyMCE link button...
![TinyMCE_link](https://user-images.githubusercontent.com/91541/56493318-99f90400-64e6-11e9-914a-a357c3798a0d.png)

Link to another article on the site, click the "CMS Content" button, then "Article"...
![Joomla_article_link](https://user-images.githubusercontent.com/91541/56493320-9c5b5e00-64e6-11e9-937e-971ade56c4e5.png)

All screen-grabs of Joomla 4 current nightly.

**Comment by neiljames** [comment]
There seems to be a definite split between the add link or use the cms for internal linking, the tinyMce link allows you to add the following - Text to Display - Title - Rel - Open Link in, which is more advanced. When I use the cms button I have to add the items listed by coding them directly.
To me using the cms button causes a far more complex way of adding the full contents of the anchor tag, what if the user does not know of these important instructions. The tinyMce way of choosing from a short menu inside the modal is far better.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24666">issues.joomla.org/tracker/joomla-cms/24666</a>.</sub>

**Comment by infograf768** [comment]
This is not a core issue. Joomla uses TinyMCE as default editor and therefore its functionalities as they are provided by this 3rd party extension. 
The main reason to touch as less as possible to 3rd party libraries in Joomla is a matter of maintenance.
Our plugins hooks into Tiny as they hook into other editors like CodeMirror, NoEditor or others.

One is free to use the third party JCE extension for example where TinyMCE is part of a component where TinyMCE is modified to provide more options.

Closing.
