### ISSUE TITLE
Delete Banners Tracks raises an error [PostgreSQL]

### ISSUE THREAD

**Issue by twister65** [joomla/joomla-cms#24679]
### Steps to reproduce the issue
Generate banner tracks with impression and click.
Go to Components -> Banners -> Tracks.
Click the Delete Tracks button.

### Expected result
All tracks are deleted.

### Actual result
![delete_tracks](https://user-images.githubusercontent.com/26852967/56498388-b9e9f100-6501-11e9-873f-2139591156c4.png)

### System information (as much as possible)
php: Linux pc-salon 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64
dbserver: postgresql
dbversion: 9.5.6
dbcollation: C
dbconnectioncollation: UTF8
phpversion: 7.2.15-0ubuntu0.18.04.2
server: Apache/2.4.29 (Ubuntu)
sapi_name: apache2handler
version: Joomla! 3.9.5 Stable [ Amani ] 9-April-2019 15:00 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/73.0.3683.86 Chrome/73.0.3683.86 Safari/537.36

### Additional comments
PostgreSQL does not accept integers for the where clause.
I suggest to replace:
https://github.com/joomla/joomla-cms/blob/314c3bcc0b21bd5fdd88113286435b06b19bab3f/administrator/components/com_banners/models/tracks.php#L231
by:
`$where = 'true';`

**Comment by richard67** [comment]
Or maybe better by `$where = '1 = 1';`
"1 = 1" resolves to "TRUE" in every kind of SQL database.

**Comment by richard67** [comment]
It's a good question if we have the same mistake elswhere in code.

**Comment by twister65** [comment]
> It's a good question if we have the same mistake elswhere in code.

https://github.com/joomla/joomla-cms/blob/314c3bcc0b21bd5fdd88113286435b06b19bab3f/administrator/components/com_finder/models/maps.php#L402

**Comment by richard67** [comment]
It seems those 2 are the only ones I can find, too. Question is how could we test the 2nd one?

**Comment by richard67** [comment]
And who will make the PR? If you want I can do it.

**Comment by twister65** [comment]
Good question: How to to purge all maps from the taxonomy ?
Yes, you can make the PR if you want.
Thanks.

**Comment by richard67** [comment]
@twister65 Please test PR #24682 .

For the other place I make other PR to be tested by code review, since where clause is not necessary there at all.

**Comment by ghost** [comment]
Closed as having Pull Request.

**Comment by richard67** [comment]
@twister65 Other PR is #24683 , please test, too, if possible.
