### ISSUE TITLE
[4.0] Notices on libraries/src/Component/Router/Rules/StandardRules.php

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#24676]
Notices keep showing up on front-end, sample data installed
Undefined index: login in libraries/src/Component/Router/Rules/StandardRules.php on line 209
Trying to get property 'key' of non-object in libraries/src/Component/Router/Rules/StandardRules.php on line 211

### System information (as much as possible)
PHP 7.2.5
Last build (Monday, 22 April)
Installed via CLI, Composer and NPM included -> full sample data

**Comment by ghazal** [comment]
A

**Comment by kkelsey0886** [comment]
I see this spamming my php logs. What is this and why is there so many router rules issues?
