### ISSUE TITLE
Media Folder

### ISSUE THREAD

**Issue by neiljames** [joomla/joomla-cms#24689]
### Steps to reproduce the issue

Click the folder containing images inside the media manager

### Expected result

The folder to open and show/upload images inside the folder

### Actual result

Nothing happens, you have to go to the image tree to access the images inside the folder or upload images

### System information (as much as possible)

localhost wammp 3.1.7 64 bit

**Comment by Quy** [comment]
Be sure to double click the folder.

**Comment by neiljames** [comment]
Double click works, sorry<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24689">issues.joomla.org/tracker/joomla-cms/24689</a>.</sub>
