### ISSUE TITLE
Submit an article raises an error [PosgreSQL (PDO)]

### ISSUE THREAD

**Issue by twister65** [joomla/joomla-cms#24688]
### Steps to reproduce the issue
Log on to the site.
Click the "Submit an article" link.
Fill the title field.
Click the Save button.

### Expected result
The new article has been submitted without error.
![sub_art_ok](https://user-images.githubusercontent.com/26852967/56502408-7d72c100-6512-11e9-87f2-59797e0c310c.png)

### Actual result
The new article has been submitted with an error.
![submit_article](https://user-images.githubusercontent.com/26852967/56502047-55cf2900-6511-11e9-91e1-d6083fa57c29.png)

### System information (as much as possible)
php: Linux pc-salon 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64
dbserver: postgresql
dbversion: 9.5.6
dbcollation: C
dbconnectioncollation: UTF8
phpversion: 7.2.15-0ubuntu0.18.04.2
server: Apache/2.4.29 (Ubuntu)
sapi_name: apache2handler
version: Joomla! 3.9.5 Stable [ Amani ] 9-April-2019 15:00 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/73.0.3683.86 Chrome/73.0.3683.86 Safari/537.36

### Additional comments
The native PosgreSQL driver works. This issue only occurs with the PDO PostgreSQL driver.

**Comment by richard67** [comment]
I could not reproduce this with current staging and PosgreSQL (PDO).

**Comment by twister65** [comment]
>  could not reproduce this with current staging and PosgreSQL (PDO).
