### ISSUE TITLE
[4.0] Unable to save Article with Emoji in it

### ISSUE THREAD

**Issue by chetanmadaan** [joomla/joomla-cms#24697]
### Steps to reproduce the issue
Create an article, add Emoji from Toolbar, try to save it.

### Expected result
Should save the emoji and display on frontend.

### Actual result
`Save failed with the following error: Incorrect string value: '\xF0\x9F\x94\xA2`
![image](https://user-images.githubusercontent.com/3968575/56537318-3bf00f00-652e-11e9-8d90-2004ffa6ade7.png)

### System information (as much as possible)
Joomla 4.0 Alpha 8.
PHP 7.2.15
MySQLi 5.5.5-10.1.38-MariaDB

### Additional comments
I made sure the #__conent table and columns are utf8mb4 collate (_which I think is default in J4_).

**Comment by ghost** [comment]
related #7803?

**Comment by brianteeman** [comment]
@franz-wohlkoenig no

**Comment by brianteeman** [comment]
It works in Joomla 3 :(

**Comment by infograf768** [comment]
Maybe this would help:
https://stackoverflow.com/questions/10957238/incorrect-string-value-when-trying-to-insert-utf-8-into-mysql-via-jdbc

**Comment by brianteeman** [comment]
No its nothing to do with anything there. Inserting an emoji in the article title works perfectly when done directly in the database. It is an issue somewhere with the joomla validation code

**Comment by infograf768** [comment]
I modified here` introtext` and `fulltext` types from `Medium Type` to `blob` and I don't get the error.
@alikon ?

**Comment by brianteeman** [comment]
I repeat - it is nothing to do with the mysql field type as you can successfully insert the multibyte character directly in the database AND it worked in joomla 3 with the same mysql settings

**Comment by Bakual** [comment]
@brianteeman Just to understand: When you say "directly in the database" you use the CLI or a PHP based tool like phpMyAdmin? The latter would be closer to what Joomla does (using PHP).
It may be that both of you are right, after all 😄

**Comment by brianteeman** [comment]
I mean directly in the database not via php with heidisql or sequel pro

**Comment by wilsonge** [comment]
The only thing I'm aware that changed related to that was https://github.com/joomla/joomla-cms/pull/22035

**Comment by chetanmadaan** [comment]
Please let me know if any of you would like any additional information or would like me to test anything?

I also went ahead and changed the driver from Mysqli to Mysql (PDO) and now the system info reads the following info as well.

Database Collation | Database Connection Collation
-- | --
utf8mb4_unicode_ci | utf8_general_ci

**Comment by wilsonge** [comment]
Aha that was the hint i needed. Try https://github.com/joomla/joomla-cms/pull/24704

**Comment by ghost** [comment]
Closed as having Pull Request.

**Comment by infograf768** [comment]
@wilsonge
Your patch does not work here (mysqli);

**Comment by chetanmadaan** [comment]
didn't work for me either.

**Comment by ghost** [comment]
@chetanmadaan can you please comment on #24704

**Comment by chetanmadaan** [comment]
> @chetanmadaan can you please comment on #24704

Just did.
