### ISSUE TITLE
[4.0] WordPress like URL editor

### ISSUE THREAD

**Issue by chetanmadaan** [joomla/joomla-cms#24692]
### Is your feature request related to a problem? Please describe.
N/A.
### Describe the solution you'd like
Just thinking out loud here, I think it would be very useful to give the user a URL editor (like wordpress), where while editing the article, they can see what the URL would be on the frontend and even edit it (if menu alias is being changed, user can be given a popup for confirmation).

I understand that WordPress only has posts and Joomla has articles, categories and other types which further links to menu items (which can result in different URL's on how you have something linked on the frontend).

But, we can predict what the URL will be on the frontend, based on whether the SEF is enabled or not or whether the current Item is linked to a menu items or not.

### Additional context
I understand that when SEF extensions and other 3rd party extensions get involved, thing can be cumbersome, but I am only thinking for a solution for Joomla articles (core joomla out of the box).

Thank you for reading.

**Comment by brianteeman** [comment]
Joomla is not Wordpress

**Comment by HLeithner** [comment]
Would be possible with the new route helper.

**Comment by Bakual** [comment]
Displaying the expected URL should actually be quite simple in J4. As Harald wrote with the new Router we have a single "correct" URL for a given item.

However editing anything beside the current item alias could become quite tricky as each part of the URL would have to be identified somehow as to where it comes from (menuitem path, category path).
Any change in that path would have impacts on other URLs. So I wouldn't do that.
Also keep in mind that you can always create a menuitem for a given item and create a custom URL this way.

**Comment by brianteeman** [comment]
Displaying the URL is very different to editing the URL. Unlike WordPress a url does not have to be to a single item.

**Comment by HLeithner** [comment]
In wordpress you can change the "alias" of the blog entry, so its more or less the same as our alias iirc.

So displaying the baseurl + the alias would be possible but would not work with a direct linked menu item als Thomas described

**Comment by chetanmadaan** [comment]
> Joomla is not Wordpress

I agree Brain and I am not trying to make Joomla work like WordPress. I just have a hard time explaining my clients the links for items that are either not linked to a menu item or linked to a hidden menu item.

**Comment by chetanmadaan** [comment]
> Displaying the expected URL should actually be quite simple in J4. As Harald wrote with the new Router we have a single "correct" URL for a given item.
> 
> However editing anything beside the current item alias could become quite tricky as each part of the URL would have to be identified somehow as to where it comes from (menuitem path, category path).
> Any change in that path would have impacts on other URLs. So I wouldn't do that.
> Also keep in mind that you can always create a menu item for a given item and create a custom URL this way.

even if we can only display the URL to the and not have the editing ability just the job and for editing we can point the users to menu items and stuff. May be? May be not?

**Comment by brianteeman** [comment]
You are forgetting that you don't always know what the full url will be when you create an article because you haven't created a suitable menu item yet.

**Comment by brianteeman** [comment]
> In wordpress you can change the "alias" of the blog entry, so its more or less the same as our alias iirc.

No it is very different

**Comment by Bakual** [comment]
> You are forgetting that you don't always know what the full url will be when you create an article because you haven't created a suitable menu item yet.

We can only ever show the currently expected URL. If the user creates a new menuitem afterwards for that article (or its category), then of course the displayed URL would be different next time that article form is loaded.
I think just displaying the URL is an interesting idea. Editing it not so much.

**Comment by HLeithner** [comment]
> > In wordpress you can change the "alias" of the blog entry, so its more or less the same as our alias iirc.
> 
> No it is very different

Would you like to explain this? My test on a wordpress sites gives me the feeling thats something similar.

**Comment by brianteeman** [comment]
They are what wp calls permalinks https://codex.wordpress.org/Using_Permalinks

**Comment by chetanmadaan** [comment]
> expected URL. If the user creates a new menuitem afterwards for that article (or its category), then of course the displayed URL would be different next time that article form is loaded.
> I think just displaying the URL is an interesting idea. Editing it not so much.

I agree, even if we can can just show the URL (Like I said in the original post), that'd be more than enough for the end user, 
Right now, the user (the client) (who naive enough), doesn't even know what the URL looks like or is going to be on the frontend, unless it's linked on a menu item (which is actively showing up on the frontend).

Thanks,
Chetan

**Comment by fevangelou** [comment]
@chetanmadaan That's because WP is a post-based CMS, whereas Joomla is an application-based CMS (application = component in Joomla lingo).

WordPress can easily determine that post ID X referenced on the URL will always map to the posts table (and the record with ID X).

Calling an article ID in Joomla through the URL though would yield nothing as you need to define WHICH component to redirect the DB call, which view, task and so on, in order to fetch the required content.

That why WP overrides are hackish and contain hardcoded references to IDs and whatnot. The only thing that kinda saves the situation is the pre-existence of "view" specific sub-templates in WP, e.g. category.php, page.php, single.php etc. And that's why Joomla is 10 times easier in theming compared to WP.

**Comment by Fedik** [comment]
it is already possible, no? with editors-xtd/menu button

**Comment by SharkyKZ** [comment]
@Fedik the question is about displaying links to frontend items in backend.

It's already possible but only for published items. Article preview button already uses this.

**Comment by chetanmadaan** [comment]
> @chetanmadaan That's because WP is a post-based CMS, whereas Joomla is an application-based CMS (application = component in Joomla lingo).
> 
> WordPress can easily determine that post ID X referenced on the URL will always map to the posts table (and the record with ID X).
> 
> Calling an article ID in Joomla through the URL though would yield nothing as you need to define WHICH component to redirect the DB call, which view, task and so on, in order to fetch the required content.
> 
> That why WP overrides are hackish and contain hardcoded references to IDs and whatnot. The only thing that kinda saves the situation is the pre-existence of "view" specific sub-templates in WP, e.g. category.php, page.php, single.php etc. And that's why Joomla is 10 times easier in theming compared to WP.

Thanks for the explanation. All am I really looking for is a link for the _dumb end user_ to access the URL of the current article. I do understand the different between WP & Joomla

**Comment by chetanmadaan** [comment]
> @Fedik the question is about displaying links to frontend items in backend.
> 
> It's already possible but only for published items. Article preview button already uses this.

I just tried the preview and it opens the article in the iframe but doesn't really shows the user what the URL is, which is what the original request was.

**Comment by chetanmadaan** [comment]
> it is already possible, no? with editors-xtd/menu button

Yes but again that inserts the link inside the content. What we are looking for is a direct link for the current article starting user in the face.

**Comment by brianteeman** [comment]
Why? What use it it to you? How are you using it? That will help us understand

**Comment by chetanmadaan** [comment]
> Why? What use it it to you? How are you using it? That will help us understand

I am trying to get a link to the current article without linking it to a menu and without telling the user to manually type in site.com/index.php?option=... and all that stuff.

**Comment by brianteeman** [comment]
Again I ask you why? Why do you need it? 
Without a menu it is going to be impossible

**Comment by Bakual** [comment]
I think it can be useful to see the URL that an article is going to get.
Easier to share (otherwise you need to navigate to it in frontend).
Easier to spot suboptimal structures (eg missing menuitem)

**Comment by chetanmadaan** [comment]
> Again I ask you why? Why do you need it?
> Without a menu it is going to be impossible

The user doesn't want to link it to a menu item. It is possible without a menu item. the link is
**index.php?option=com_content&view=article&id=xxx**

**Comment by chetanmadaan** [comment]
> I think it can be useful to see the URL that an article is going to get.
> Easier to share (otherwise you need to navigate to it in frontend).
> Easier to spot suboptimal structures (eg missing menuitem)
Thank You @Bakual

**Comment by brianteeman** [comment]
> The user doesn't want to link it to a menu item. It is possible without a menu item. the link is
index.php?option=com_content&view=article&id=xxx

But the SEF url will be dependant on whatever is the closest best fit for the menu.

**Comment by chetanmadaan** [comment]
> > The user doesn't want to link it to a menu item. It is possible without a menu item. the link is
> > index.php?option=com_content&view=article&id=xxx
> 
> But the SEF url will be dependant on whatever is the closest best fit for the menu.

Then we build something that's allow use to generate the same URL on the backend. Either way, we want give the user URL's for item in the frontend. Like Virtuemart does for products and Wordpress does for posts that its.

May be we can follow the buttons inside the Editor that allows us to insert links to menu items, articles & contact items. Just a non SEF link directly to the item?

**Comment by micker** [comment]
have a consistent item url without creating a menu link will be smother for workflow .... i like this idea for end-user
but how to check duplicate content if we have menu link AND direct item link ..

**Comment by chetanmadaan** [comment]
> have a consistent item url without creating a menu link will be smother for workflow .... i like this idea for end-user
> but how to check duplicate content if we have menu link AND direct item link ..

I wouldn't know the coding aspect of it. Again, duplicates is something Joomla 4 shouldn't have or atleast try to fix the duplicate url problem.

**Comment by Bakual** [comment]
> have a consistent item url without creating a menu link will be smother for workflow .... i like this idea for end-user

That's not possible: Menulinks are essential in Joomla.
The only URL you could get without a menuitem would be the non-SEF one (eg index.php?option=com_content&view=article&catid=123&id=456).

As I said in an earlier comment, the only thing whjich would be possible to do in J4 is having the frontend URL displayed in the form. It wouldn't be editable at all. If you want to change it, you would have to change the alias in the respective menuitem/category/article.
Everything else is just out of scope in Joomla due to the way URLs are generated and routing is done.

**Comment by brianteeman** [comment]
> As I said in an earlier comment, the only thing whjich would be possible to do in J4 is having the frontend URL displayed in the form

And that would not be a permanent url (like in wordpress) but subject to change as menu items change

**Comment by Bakual** [comment]
> And that would not be a permanent url (like in wordpress) but subject to change as menu items change

Exactly. It would only be a convenient way to quickly share an URL.

**Comment by micker** [comment]
yes it will a be untresting solution to create a dynamic link between menu link and url in content
now that doesn't work if we change menu link urlused in content isn't update
=> can we herite link params with itemid ?

**Comment by chetanmadaan** [comment]
Thank you all for the contributions so far. The URL won't be permanent or editable. Just display.

**Comment by brianteeman** [comment]
In my opinion this should be closed. The complete architecture of joomla is of a menu based system and not a page based system so this idea is never going to produce something that is really usable
