### ISSUE TITLE
No error message when showing already existing e-mail

### ISSUE THREAD

**Issue by random332** [joomla/joomla-cms#24693]
### Steps to reproduce the issue
Register a user with the same adress than an existing user

### Expected result
Error message to show.

### Actual result
The page is reloaded and field emptied without error message in default template.
The error message is only shown when the user registers successfuly :
![error joomla](https://user-images.githubusercontent.com/49867929/56519251-e6256200-6541-11e9-95dd-fd7c7974318c.PNG)

### System information (as much as possible)
Beez template on Joomla 3.9.3

**Comment by infograf768** [comment]
Can't reproduce in 3.9.5.

<img width="1035" alt="Screen Shot 2019-04-23 at 06 58 14" src="https://user-images.githubusercontent.com/869724/56555436-3843a300-6595-11e9-89f1-06e178ac4361.png">

The correct string in fr-FR is
`JLIB_DATABASE_ERROR_EMAIL_INUSE="Cette adresse e-mail est déjà utilisée. Merci d'utiliser une autre adresse e-mail."`
Therefore the message you get is not provided by the French language pack.

**Comment by ghost** [comment]
@random332 please update on latest Version, closing as unconfirmed Report. You can always reopen if needed.
