### ISSUE TITLE
Action log module not visible for non-superusers

### ISSUE THREAD

**Issue by random332** [joomla/joomla-cms#24694]
### Steps to reproduce the issue
Publish Administrator module "latest action logs" in cpanel position
Have the module to have special permission.

### Expected result
Visibility of the module in cpannel for non-superusers

### Actual result
The module is not present in cpannel except if you are a superuser.

### System information (as much as possible)
Joomla 3.9.5

### Additional comments
Logged-in Users is visible in cpannel with the same "special" access set.
![Capture](https://user-images.githubusercontent.com/49867929/56527533-1541d080-654e-11e9-96d2-64208b288f10.PNG)

**Comment by brianteeman** [comment]
This is by design - see https://github.com/joomla/joomla-cms/issues/22922#issuecomment-435500828

**Comment by ghost** [comment]
Closed as expected behaviour. Thanks for reporting @random332.
