### ISSUE TITLE
PHP Mail not Work at Joomla

### ISSUE THREAD

**Issue by widmann-it** [joomla/joomla-cms#24707]
### Steps to reproduce the issue
After the change from PHP 7.2.x to PHP 7.3.1x the mail dispatch does not work anymore.

### Expected result
Sending the email should be done

### Actual result
Email will not be sent, error message from Joomla that the mail was not sent

### System information (as much as possible)
The error can be simulated on various different systems. 

### Additional comments
The error can be simulated on various different systems.

**Comment by ReLater** [comment]
> The error can be simulated on various different systems.

Because I can't reproduce this issue (J3.9.5, PHP7.3) with `PHP-Mail` or `SMTP` (SSL/TLS; Authentication) settings and feature `Send Test Mail` on 3 test sites: Could you please provide more system informations and testing instructions?

**Comment by widmann-it** [comment]
The problem can be limited to one PHP problem, because several installations are affected. As soon as PHP 7.3 is used, the mail dispatch does not work anymore. If you switch back to 7.1 or 7.2, sending the mail works without problems. It occurs with all variants of the mail dispatch! (Sendmail, SMTP)

It has been tested with Joomla 3.9.4 and 3.9.5

**Comment by Quy** [comment]
Please search Joomla Forums. Here are some threads regarding this issue:

https://forum.joomla.org/viewtopic.php?f=706&t=970270
https://forum.joomla.org/viewtopic.php?f=706&t=968659

**Comment by widmann-it** [comment]
I am familiar with the two issues, but they do not solve the problem. Since the error occurs with different systems it is to be assumed that this is an error within PHP. In the parallel discussion in the Glip Channel D_A_CH to this problem different approaches were already mentioned. 

Global sending of emails disabled - no
Switching the sending methods - sendmail to SMTP etc. without success.
Several providers were tested, at 1&1 (1x OK 1x failed), Goneo (1x OK 1x failed), Mittwald (30 x failed).

The support of Mittwald said that the PHPMailer 5.2 does not work with PHP 7.3. The same message came from another community portal which does not work with Joomla.

**Comment by ghost** [comment]
Closed as having Pull Request.
