### ISSUE TITLE
[4.0] no way to remove warning messages in system/warning

### ISSUE THREAD

**Issue by Puneet-Jain-18** [joomla/joomla-cms#24710]
### Steps to reproduce the issue
Go to administrator/system/warnings

### Expected result
Warnings are displayed with an icon at top of each warning to close it.

### Actual result

No possible way to close a warning

![Screenshot (66)](https://user-images.githubusercontent.com/34083630/56605455-d5e4b400-6621-11e9-92fc-6cd92e0dcaee.png)

### System information (as much as possible)

Joomla! 4.0.0-alpha8-dev

**Comment by Quy** [comment]
What would be the point of closing the warning? 

The same happens with no results.
![no-results](https://user-images.githubusercontent.com/368084/56616651-ba9e8800-65d2-11e9-9de4-3d3fa3ab4ccb.jpg)

**Comment by brianteeman** [comment]
please close as expected behaviour

**Comment by Puneet-Jain-18** [comment]
@Quy  @brianteeman    Actually what I thought was, even after visiting the page the warnings are displayed as the notification here
![Screenshot (67)](https://user-images.githubusercontent.com/34083630/56628483-9b9e0580-6667-11e9-907b-872c8f00e66d.png)

So if a new warning is generated at a later point of time, it might not attract the user's attention.

Also, User could decide which warnings are necessary and need to be kept and close the ones which he finds not useful.
If you think it's not a problem then it's ok :)

**Comment by brianteeman** [comment]
The only correct way to remove the warning is to resolve the issue you are being warned about.
