### ISSUE TITLE
Semver j3

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#24728]
What is the point in saying joomla follows semantic versioning when it is only selectively applied.

### Expected result
No new features in a patch release

### Actual result

Depends on the whim of the committer

3.9.5 and now 3.9.6 have new features.

**Comment by brianteeman** [comment]
more new features merged into 3.9.6 :( :(

and yet great new features are being rejected and forced into J4 next year

**Comment by HLeithner** [comment]
@brianteeman which new feature did I merged?

**Comment by brianteeman** [comment]
#23514

**Comment by HLeithner** [comment]
Sorry that is no feature, it is a bug, because the xml was missing, that php code that uses the parameter already exists but didn't worked because you can't set it.

**Comment by Bakual** [comment]
https://github.com/joomla/joomla-cms/pull/24115 is a new feature as well (new options).

**Comment by Bakual** [comment]
> Sorry that is no feature, it is a bug,

Sorry, but you could argue this was for everything. Even if code is aprtially missing.
Eg frontend editing for com_contact: Most of the code is already there. It would still be a new feature and thus goes rightfully into J4.

**Comment by alikon** [comment]
#23514 is quite a bit bordeline, imo, so it depeneds on how you feel/read it

**Comment by brianteeman** [comment]
> > Sorry that is no feature, it is a bug,

> Sorry, but you could argue this was for everything. Even if code is partially missing.
Eg frontend editing for com_contact: Most of the code is already there. It would still be a new feature and thus goes rightfully into J4.

#23499 is exactly the same and was **_correctly_** not accepted for a patch release

**Comment by richard67** [comment]
Would PR's #24730 , #24736 and #24737 be new features, or are these bug fixes?
