### ISSUE TITLE
admin user account details throws error

### ISSUE THREAD

**Issue by iwjoomla** [joomla/joomla-cms#24729]
### Steps to reproduce the issue
1. In Joomla 3.9.5 backend, click Users->Manage  to display list of user accounts.  
2. Click on account name (superuser account), and the error occurs without displaying account info.

### Expected result
The account details for the User should have been displayed

### Actual result
    An error has occurred.
    0 Call to undefined function Joomla\CMS\Form\dom_import_simplexml()

javascript:
### System information (as much as possible)
Joomla 3.9.5
PHP 7.1.28
Mysqli 5.6.43

### Additional comments
This error seems to only occur with the account currently logged in at the time. 
When tested with a 2nd Superuser account, the same error occurred as described above, but with that user account name.
However, the 1st account that the error originally occurred on, could now be displayed using User->Manage  (when logged in with 2nd user account)

So it appears this error ONLY occurs on the account the user is currently logged in with.

**Comment by DavidBoggitt** [comment]
Not seeing this at all.  Try reinstalling the core and seeing if the same error occurs.  Is this on a fresh install of 3.9.5?

**Comment by alikon** [comment]
i'm unable to reproduce too

**Comment by ghost** [comment]
@iwjoomla Please ask on [Forum](https://forum.joomla.org/)

**Comment by SharkyKZ** [comment]
Enable Debug System in Global Configuration to see where this is coming from.

**Comment by HLeithner** [comment]
The reason is that your php installation doesn't support libxml.

**Comment by iwjoomla** [comment]
I checked PHP information and  libxml 2.9.4  is installed

**Comment by HLeithner** [comment]
Please activate debugmode as @SharkyKZ explained

**Comment by iwjoomla** [comment]
Here is what my home page looks like with Development Error Reporting enabled
![joomla_screen_using_development_debug](https://user-images.githubusercontent.com/50024063/56851300-b6bc7f80-68ca-11e9-80a6-2c52079f7444.jpg)

**Comment by iwjoomla** [comment]
With Debug enabled:
An error has occurred.
0 Call to undefined function Joomla\CMS\Form\dom_import_simplexml()	
/home/tmmuseum/public_html/libraries/src/Form/Form.php:887

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/src/Form/Form.php:887
2 | Joomla\CMS\Form\Form->removeField() | JROOT/administrator/components/com_users/models/user.php:148
3 | UsersModelUser->getForm() | JROOT/libraries/src/MVC/View/HtmlView.php:425
4 | Joomla\CMS\MVC\View\HtmlView->get() | JROOT/administrator/components/com_users/views/user/view.html.php:40
5 | UsersViewUser->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:672
6 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_users/controller.php:107
7 | UsersController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:710
8 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_users/users.php:21
9 | require_once() | JROOT/libraries/src/Component/ComponentHelper.php:402
10 | Joomla\CMS\Component\ComponentHelper::executeComponent() | JROOT/libraries/src/Component/ComponentHelper.php:377
11 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:101
12 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:159
13 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:196
14 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/index.php:51

**Comment by HLeithner** [comment]
You installation doesn't support https://www.php.net/manual/de/function.dom-import-simplexml.php

**Comment by iwjoomla** [comment]
Just to follow up, the problem is now fixed.  The PHP 7.1 extensions "xmlreader" and "xmlwriter" were enabled on the server...  and now Users->Manage->Admin (in this case) displays correctly. 
Thanks for everyone's help and suggestions.
