### ISSUE TITLE
[4.0] Notice: Trying to get property 'stage_id' of non-object

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#24727]
### Steps to reproduce the issue
Open new article on backend.

### Expected result

no notice

### Actual result

Notice: Trying to get property 'stage_id' of non-object in C:\wamp\www\j4\administrator\components\com_content\Model\ArticleModel.php on line 602

**Comment by chmst** [comment]
Can you give more information? Did you fix the datebase?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24727">issues.joomla.org/tracker/joomla-cms/24727</a>.</sub>

**Comment by Bakual** [comment]
Was this a fresh installation or an updated one from previous J4 version?
If the latter, please try with a fresh installation.

**Comment by 810** [comment]
updated by github, also did a database fix, but it looks like this missing this column on the fix.

**Comment by Bakual** [comment]
Updated by github is not supported. So please use a fresh installation. If it works then, we can close this.

**Comment by ghost** [comment]
> Updated by github is not supported.

We need to inform People what kind of Update on Alpha, Beta, ... is supported. For Example "Nightly on Nightly isn't supported in Alpha, but supported with Beta", ...

**Comment by Bakual** [comment]
I think it's actually already written somewhere. But basically it's still only support for official stable releases. Everything else may or may not work.
For 4.0, the current plan is still to support updates from betas upwards, certainly not alphas.

**Comment by ghost** [comment]
This Info should be in "J4 on horizon" and/or Nightly-Download.

**Comment by Bakual** [comment]
Currently it's no different from staging.
See https://developer.joomla.org/development-strategy.html point 4.4:
> All Alpha, Beta and Release Candidate releases (defined in SemVer as "pre-releases") must always be regarded as unsupported. It is entirely possible that these releases may contain serious bugs, security issues, forwards and backwards incompatibilities, entire features that are subsequently withdrawn, and so on. There will be no supported update or migration paths from a development release to any other release.

**Comment by ghost** [comment]
@Bakual thanks, i have missed that Document.

**Comment by Sandra97** [comment]
In Alpha 6, 7 and 8 blog posts, we have this mention: 

> To make the life of testers easier, we will be more strict in updating the deleted files and modifying the SQL changes. This will allow updates between Beta / RC and Stable.
