### ISSUE TITLE
[4.0] Installer Database should not use popovers

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#24748]
### Is your feature request related to a problem? Please describe.
The screen for Database fix is not accessible. It looks like this: 

![database-fix](https://user-images.githubusercontent.com/1035262/56862246-27d26480-69a9-11e9-976f-540868fe9540.PNG)

### Describe the solution you'd like
There is no need to show a warning or info alert when opening the screen. 

There is plenty of place on this screen, even if there are three or four items in the table. The whole text which is now in the popover should be visible at once if the screen is opened. 
The same for all other content which is now  in popvers.

Additionally the language strings could be more positive. Instead of speaking about problems or "no problem", let's speak about "the state of your database" .. here native speakers are required.

**Comment by brianteeman** [comment]
From the screenshot it looks like there are more than two problems.

For me I question what value there is in displaying the details of the problems.

**Comment by chmst** [comment]
Indeed there are several issues. 
What I wanted to be resolved here are the popovers and the alert. 

If the infomation provided in the popovers is correct is not in scope of tis issue.

**Comment by brianteeman** [comment]
If the information is of no value then it's an easy fix

**Comment by brianteeman** [comment]
If https://github.com/joomla/joomla-cms/pull/24441 ever gets tested and merged then it will be easy to apply the same technique to solve the problem here

**Comment by richard67** [comment]
@brianteeman As you closed PR #24441 in favour of PR #24892 which got merged, can this also be applied for the issue here? As far as I see it is something else. Anyway, the information in the tool tips of the installer database view are relevant in my opinion. So if there is a way to make them accessible or replace the popovers by some div like you did in other places, it should be done. If you have an idea on what to do but are too busy to make a PR, give me some input and I will try my best to do it.

**Comment by brianteeman** [comment]
@richard67 use the technique in #24899 as an example.

**Comment by richard67** [comment]
@brianteeman Not sure if I understand #24899 . How can I test that?

**Comment by brianteeman** [comment]
apply the pr. open an article for editing. use the browser back button to go back to the list view and checkout the change on the padlock icon

**Comment by ghost** [comment]
Closed as having Pull Request #25207
