### ISSUE TITLE
[4.0] Backend manage extensions wrong changelogModal item

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#24744]
### Steps to reproduce the issue

Install a package component like kunena.
Go to backend - system - extensions - manage
Show all items. (filter)
kunena item like Kunena - Joomla Integration click on the version number

### Expected result

The right changelog menu item is opened.

### Actual result

He opens the modal from Kunena - AltaUserPoints Integration 

### System information (as much as possible)

Joomla! 4.0.0-alpha8
Kunena 6.0.0-ALPHA2-DEV

### Additional comments
Joomla modal opens the first filtered component name item. For kunena its Kunena - AltaUserPoints Integration plugin.

**Comment by ghost** [comment]
can you test on latest [nightly](https://developer.joomla.org/nightly-builds.html)?

**Comment by 810** [comment]
![image](https://user-images.githubusercontent.com/876623/56863086-67517e80-69b2-11e9-8a44-48c7af384103.png)

**Comment by alikon** [comment]
@roland-d  can you give a look please

**Comment by roland-d** [comment]
@alikon Yes I will take a look.

**Comment by roland-d** [comment]
Closing this as we have a PR #24777
