### ISSUE TITLE
[4.0] Error saving a new article (pgsql)

### ISSUE THREAD

**Issue by twister65** [joomla/joomla-cms#24749]
### Steps to reproduce the issue
Articles: New -> Save

### Expected result
Article saved

### Actual result
Throws :
Error
Save failed with the following error: 42601, 7, ERROR: syntax error at or near "ON" LINE 6: ...tid = 2 AND state >= 0 AND "ordering" >= 0) AS sq ON "id" = ... ^

### System information (as much as possible)
Joomla! Version: Joomla! 4.0.0-alpha8 Alpha [ Amani ] 18-April-2019 14:19 GMT
with PR #24747
Database Type:  postgresql
Database Version: 9.5.6
PHP Version: 7.2.17-0ubuntu0.18.04.1

**Comment by alikon** [comment]
can you test with #24148 and with #24319 ....

**Comment by richard67** [comment]
@twister65 I've just tested PR #24148 with success. It seems to solve this issue. PR #24319 is also good. Could you test, too?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24749">issues.joomla.org/tracker/joomla-cms/24749</a>.</sub>

**Comment by twister65** [comment]
We have PR #24148 .
