### ISSUE TITLE
[4.0] Unable to complete the installation with PostgreSQL

### ISSUE THREAD

**Issue by twister65** [joomla/joomla-cms#24740]
### Steps to reproduce the issue
Select the PostgreSQL (PDO) driver during installation.

### Expected result
J4 is installed with a PostgreSQL database

### Actual result
Go back to the first step.

### System information (as much as possible)
Joomla 4 alpha 8
PostgreSQL 9.5.6.

**Comment by alikon** [comment]
please test #24747<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24740">issues.joomla.org/tracker/joomla-cms/24740</a>.</sub>
