### ISSUE TITLE
[4.0] Create overrides screen layout inconsistent and close button doesn't work

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#24752]
### Steps to reproduce the issue
![j4--screenshot-patchtesterj4 cloudaccess host-2019 04 28-19-13-17](https://user-images.githubusercontent.com/4665225/56868489-eb275d00-69ea-11e9-99c9-efd38bb33f72.png)
Go to System > Templates > choose a template > Create Overrides

### Expected result
1. All lists have items on a new line
2. Clicking a list item expands it
3. Close button works

### Actual result
1. Plugins appear on the same line and are cramped.
2. Clicking them does nothing.
3. Clicking close does nothing (I created an override first so perhaps that causes this particular problem)

### System information (as much as possible)
[systeminfo-2019-04-28T14_21_07-04_00.txt](https://github.com/joomla/joomla-cms/files/3125331/systeminfo-2019-04-28T14_21_07-04_00.txt)

**Comment by brianteeman** [comment]
can not replicate - check your browser console for any errors

**Comment by SharkyKZ** [comment]
>version: Joomla! 4.0.0-alpha8-dev Development [ Amani ] 9-March-2019 13:41 GMT

This was fixed some days ago, see #24639. Use the latest nightly please.

**Comment by uglyeoin** [comment]
Apologies I've got it setup on the launch.joomla.org cheers for the heads up

**Comment by ghost** [comment]
@uglyeoin you have to setup every day new as upgrades from nightly to nightly will work only from J4-Beta on.
