### ISSUE TITLE
[com_fields] - UNDO fix show on side/admin/both

### ISSUE THREAD

**Issue by joomlahenk** [joomla/joomla-cms#24754]
### Steps to reproduce the issue
Change custom field option show-on from site to administrator

### Expected result
Custom field tab is not displayed in front-end edit, but is displayed in backend edit
The custom field IS displayed on the actual site 

### Actual result
Custom field tab not displayed in front-end edit, but is displayed in backend edit
The custom field is NOT displayed on the actual site 

### System information (as much as possible)
J! 3.9.5

### Additional comments
Refers to issue #24397 
As already commented by duvi:
The "Show on" setting should only affect where the field should be visible in the EDIT view - in admin, in front end or both.

If you don't want the CF to display on site, you just unpublish

Please UNDO this.

**Comment by ghost** [comment]
@alikon can you please comment as #24397 is created by you?

**Comment by alikon** [comment]
imo #24397 is correct/expected behaviuor

**Comment by joomlahenk** [comment]
The issue I have after this change is that all custom fieds on my site disappear after update to 3.9.5.
This was because I had set show-on to administrator as I don't want a user to see a tab for the CF in the editor when he wants to edit an article in the front end.

Now I need to set show-on to site to have it show on the site and then the user has a tab for the CF in the editor in the front end, although he is not allowed to change the CF.

Maybe there needs to be a better description of what this setting is ment to do.
Do we use it for the EDIT view or for the SITE view or a mix of both?
I think it is realy needed to be able to show/not-show the CF tab in the front-end edit

**Comment by alikon** [comment]
from https://docs.joomla.org/J3.x:Adding_custom_fields/Parameters_for_all_Custom_Fields

> Show on
On which part of the site should the field be shown. In the backend, in the frontend or both?

**Comment by joomlahenk** [comment]
Show on
On which part of the site should the field be shown. In the backend editor, in the frontend editor or both?
The backend is used for editing.
The frontend is the site as anyone can see it.
The frontend editor is used by a user that logs-in on the frontend and does not use the backend.
So it this case we have 3 viewing modes not just 2.

Changing this setting should not have any inpact on the site as anyone can see it.

**Comment by kat0d** [comment]
@alikon alikon and where is the 

- Disabled: Should the field be disabled in the edit form.
- Read only: Should the field be read-only in the edit form.
parameters ???
![image](https://user-images.githubusercontent.com/11921942/57588915-9b857d00-7524-11e9-9c78-7bf4aa8d18d2.png)

**Comment by AndySDH** [comment]
> The "Show on" setting should only affect where the field should be visible in the EDIT view - in admin, in front end or both.
> 
> If you don't want the CF to display on site, you just unpublish

Agreed.

That setting has always been for controlling where the field can be edited.

It just has a bad description.

So the correct thing to do is that the "Show on" setting should be renamed to "Can be edited in..."
with options: Backend/Frontend/Both

And #24397 should indeed be un-done.

**Comment by AndySDH** [comment]
Just a reminder for this. Please @alikon can you check this?

**Comment by alikon** [comment]
feel free to submit a pr, i've already said my pov on this matter https://github.com/joomla/joomla-cms/issues/24754#issuecomment-487850964

**Comment by AndySDH** [comment]
@alikon Sorry but did you read my post here? That description is badly worded to begin with.
> "On which part of the site should the field be shown. In the backend, in the frontend or both?"

This is just bad wording and not the intended functionallity. Custom Fields already have a setting that controls whether the custom field should be displayed or not on the frontend. This:

![image](https://user-images.githubusercontent.com/25923699/58480241-3a7fbb00-815a-11e9-8042-2caa2169a9d8.png)

So there already is a setting that controls the display on the frontend or not.

The current setting called "Show on" is and was always meant to be an option for where the custom field could be **edited**, not where it could be displayed. It was just bad wording of the description.

Please don't be "stubborn" just because this would undo something you did, please try to understand the situation as it's something that was misinterpreted.

**Comment by AndySDH** [comment]
Also another proof that the option was only meant to be for the editing form, and not the frontend display, is that the method is called "displayFieldOnForm"

See, key word: OnForm.

![image](https://user-images.githubusercontent.com/25923699/58480720-31431e00-815b-11e9-9421-a2b35f3ffd18.png)

So right now you added a check for the frontend display based on an option that was meant for the edit form display.

Please try to work with us man!

**Comment by ghost** [comment]
Closed as having Pull Request #25062
