### ISSUE TITLE
[4.0] php 7.3 support switch is equivalent to "break"

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#24762]
### Actual result

PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in 
\administrator\components\com_joomlaupdate\restore.php on line 1220

**Comment by brianteeman** [comment]
I thought this got fixed ages ago. But if not then please submit a pull request

**Comment by SharkyKZ** [comment]
This is fixed in 3.x, see https://github.com/joomla/joomla-cms/pull/23481.

**Comment by ghost** [comment]
Closed as having Pull Request.
