### ISSUE TITLE
[4.0] [PostgreSQL] Database problem with com_finder tables after new installation

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#24769]
### Steps to reproduce the issue

1. Pull current (May 1, 2019) 4.0-dev branch and do `composer install` and `npm ci`, or use nightly build from tonight. Both include PR #24747, which is needed to install on PostgreSQL. Alpha 8 does not include that yet, so please don't use Alpha 8.
2. Install Joomla 4 using a PostgreSQL database.
3. After installation has finished with success, login to backend, confirm the statistics dialog, then goto the system panel and check section "Information - Database". Result: You see that there is 1 database problem.
4. Click "Database" to get to the Database view.

### Expected result

No database problems.

### Actual result

![screen shot 2019-05-01 at 09 59 15](https://issues.joomla.org/uploads/1/cf9d34b84d4bb5b3a7834023f1e289dd.png)

### System information (as much as possible)

Current 4.0-dev branch (today is May 1, 2019) fresh installation using PostgreSQL database.

### Additional comments

The problem came up after PR #20561 was merged.

**Comment by richard67** [comment]
@alikon Because you test with PostgreSQL, too: Can you reproduce this issue?

@Hackwar It seems that in your PR #20561 , the changes in joomla.sql and 4.0.0-2018-07-29.sql for postgresql database are not consistent, because the database checker checks the schema updates. Maybe you can check and fix?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24769">issues.joomla.org/tracker/joomla-cms/24769</a>.</sub>

**Comment by alikon** [comment]
i'll look at it sure , btw can you test #24768 always postgresql related ?

**Comment by richard67** [comment]
@alikon @Hackwar No need to investigate. I am already doing and working on a fix.

**Comment by richard67** [comment]
I found the problem and made the neccessary corrections.

Closing as having PR #24771 .
