### ISSUE TITLE
[4.0] Disable pointer event on .header-shadow

### ISSUE THREAD

**Issue by ced1870** [joomla/joomla-cms#24761]
### Steps to reproduce the issue

Load a module with user actions (buttons or what you want) in the position "banner"

### Expected result

Able to click the buttons

### Actual result

Unable to click the buttons

### System information (as much as possible)

PHP 7.3 + J4alpha9

### Additional comments

The problem is that the .header-shadow DIV in the template Cassiopeia take place over the content and then create a layer where the user can not click the buttons 

SOLUTION :
 In the CSS, add 
pointer-events: none;
to the css class .header-shadow

**Comment by brianteeman** [comment]
As you have a solution please submit a pull request

**Comment by Quy** [comment]
Please test PR #25010<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24761">issues.joomla.org/tracker/joomla-cms/24761</a>.</sub>
