### ISSUE TITLE
[4.0][com_postinstall] Move Post-installation Messages from Components menu to System?

### ISSUE THREAD

**Issue by sanderpotjer** [joomla/joomla-cms#24783]
With the new "System" dashboard containing all features relevant to the site administrators, I'm wondering if it would not be more logical to display the "Post-installation Messages" as an option under `administrator/index.php?option=com_cpanel&view=system`instead of the "Components" menu in the sidebar.

Any specific reason to leave it under "Components"?

**Comment by sanderpotjer** [comment]
Just noticed it is already visible on the system page :-) 

<img width="380" alt="Screenshot 2019-05-04 at 14 38 06" src="https://user-images.githubusercontent.com/522834/57179111-4a1d2400-6e7a-11e9-8785-332fd188e010.png">

I would suggest to remove it from the Components menu. Objections?

**Comment by Quy** [comment]
See PR #23760

**Comment by sanderpotjer** [comment]
@quy thanks for pointing to the PR!
