### ISSUE TITLE
[4.0] Users: Edit - date fields not editable but changable via HTML

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-cms#24780]
### Steps to reproduce the issue
Users > Manage > select a user

As Super Admin you cannot edit the Registration date because it's readonly.
![users-edit1](https://user-images.githubusercontent.com/1217850/57177599-c48f7900-6e65-11e9-85e0-393edc201406.png)

You can edit the HTML source (via Google Chrome > Inspect)
![users-edit2](https://user-images.githubusercontent.com/1217850/57177598-c48f7900-6e65-11e9-878b-9643a74dc02c.png)

and save the new date:
![users-edit3](https://user-images.githubusercontent.com/1217850/57177597-c3f6e280-6e65-11e9-8aa1-dce909ed77a1.png)

### Expected result
If a form field is readonly, you should not be able to save the field via a HTML change.

**Comment by PeterTHM** [comment]
This issue may occure because the calendar.js allways replaces the field value with the given data-alt-value (if set) when the field is not set to disabled.

Because this fields are not intended to be changed manually, I would suggest to set them to disabled in the user.xml

**Comment by brianteeman** [comment]
setting the field to disabled will make it invisible to assistive technology

**Comment by Chaosxmk** [comment]
Does assistive technology need the input to have a name attribute? A readonly input without a name will have its value tossed away when the form is sent. Still bypass-able by manually putting the field name back in, but that comes down to the same effect as setting the field as disabled.

**Comment by pau1a** [comment]
Does this even need to be a form field? Surely its only ever set once (at registration) and subsequent display could be in an element that isn't a form field but is made to look like one.

I can't remember any situations where this is editable on J3. Im still working through J4 so may be way off.

**Comment by Quy** [comment]
Please test PR #27328
