### ISSUE TITLE
[4.0][com_fields] Category select is missing/broken for fields

### ISSUE THREAD

**Issue by sanderpotjer** [joomla/joomla-cms#24782]
From #24711
> Also, it seems like choosing a category for a custom field currently seems broken in 4.0-dev generally, not only in this branch? Seems to be caused by an exception being thrown at
https://github.com/joomla/joomla-cms/blob/e2abc0993baa4e5abb5a3166c56f3888c278c40c/administrator/components/com_fields/Model/FieldModel.php#L989
This needs to be investigated, but it ain't part of this PR. Just dropping this note here, because I think testers will stumble accross not being able to set a category for a custom field.

Creating a separate issue for this to make sure we fix this :-)

**Comment by brianteeman** [comment]
I can confirm this - good spot

**Comment by AndySDH** [comment]
Pretty big deal that needs to be fixed

**Comment by Quy** [comment]
Please test PR #26157<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24782">issues.joomla.org/tracker/joomla-cms/24782</a>.</sub>
