### ISSUE TITLE
[4.0] Full Sample Data Errors on Menus Links

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#24797]
### Steps to reproduce the issue
Choose Install Sample Data during Install Process.

### Actual result
On Menu Manager for All modules, we can see these errors :

![image](https://user-images.githubusercontent.com/490245/57192694-8fe9f300-6f33-11e9-8752-3e182080ec3f.png)

The actual link on Front-end is:

`index.php?option=com_config&view=article&id=29&Itemid=303`

On Menu Manager for All Front-end Views, we get this on Tags links:

![image](https://user-images.githubusercontent.com/490245/57192795-9462db80-6f34-11e9-8524-6c7e9acb03bd.png)

The actual link on Front-end is:

index.php?option=com_ajax&view=tag&layout=list&id[0]=3&Itemid=474

* I corrected "All tags" Menu Link 

### System information (as much as possible)
Last Build - as of May 5th
commit 99235f2070b0a529d6edbdafe75d29c8dd711d47

macOS 10.12
PHP 7.2.5
Bitnami stack

**Comment by ReLater** [comment]
> Choose Install Sample Data during Install Process.

You shouldn't do that. The sample data during installation are completely outdated and as far as I know this ist still a valid issue: https://github.com/joomla/joomla-cms/issues/20262 = This step will be removed.

Install sample date AFTER installation in ControlPanel! There's a module to do that.

In other words: Your find is not an unexpected issue.

**Comment by ghazal** [comment]
OK.
Well. Then it should be removed.
