### ISSUE TITLE
[4.0] Workflow doesnt set filters

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#24814]
As part of the accessibility requirements of a list view it is essential that the table has a caption that describes the table, the sort order and any filters.

The first two of those are already done.

While investigating a method to do the filter part I saw that the two filters related to workflows (stage and condition) do not set the activeFilter

To test add this code to the top of the article list view
```
<?php $this->activeFilters = $this->get('ActiveFilters'); ?>
<?php print_r($this->activeFilters); ?>
```

Now when you select a filter it should be displayed by the code above.

It works perfectly for all the filters except for  two filters related to workflows

**Comment by Quy** [comment]
Please test PR #24864<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24814">issues.joomla.org/tracker/joomla-cms/24814</a>.</sub>

**Comment by brianteeman** [comment]
Please re-open as #24864 is nothing to do with this

**Comment by SharkyKZ** [comment]
Test PR #25183 please.

**Comment by alikon** [comment]
closed as we have a pr to test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24814">issues.joomla.org/tracker/joomla-cms/24814</a>.</sub>
