### ISSUE TITLE
Custom Content

### ISSUE THREAD

**Issue by webconsolinc** [joomla/joomla-cms#24822]
### Is your feature request related to a problem? Please describe.

Hi, I love Joomla! Custom Fields. It's working very well and serve the purpose for all businesses.

In addition to that, I am looking to have a way of creating custom content type that extends from "Articles". For example, I need a content type called "Products" (because Articles, as a term, is more for Blog) while I know that I can use Articles to manage "Products" type of content, but for user is really not intuitive. Also, when a website that has both commerce (products) and blog (articles), then it's getting confusing for content author (it's just not elegant).

### Describe the solution you'd like

Would be nice if there's away for me to add "View" called "Products" to the "com_content" and that view is pretty much extending the functionality of "Articles" (without touching a line of code of the out-of-the-box component).

### Additional context

I find this use case is useful for website or application that has multiple content types.

**Comment by ghost** [comment]
Thanks for your comment. Theres a Discussion at #19150, please comment there. Closed for this Reason.
