### ISSUE TITLE
[4.0] Broken id in com_cpanel&view=system headers

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#24827]
### Steps to reproduce the issue
System Panel: option=com_cpanel&view=system.

The card headers have strange ids:![screen shot 2019-05-07 at 14 07 48](https://issues.joomla.org/uploads/1/c24a19b241bcd4e6483e85ede5ec4a20.png)

Unfortunately I cannot find where the id is generated or modified.

**Comment by chmst** [comment]
Note: Strange IDs are not really the problem. But this destroys the aria-hidden Attribute for the leading icon.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24827">issues.joomla.org/tracker/joomla-cms/24827</a>.</sub>

**Comment by ReLater** [comment]
> Unfortunately I cannot find where the id is generated or modified.

I think it's /media/vendor/skipto/skipTo.js

**Comment by brianteeman** [comment]
The id is coming from skipto plugin

I dont see how it is breaking any aria attribute though

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/57310709-278d4400-70e2-11e9-9edf-677d613b90f8.png)

**Comment by chmst** [comment]
Thank you @brianteeman and @ReLater. This issue can be closed.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24827">issues.joomla.org/tracker/joomla-cms/24827</a>.</sub>
