### ISSUE TITLE
Website not getting redirect from http to https

### ISSUE THREAD

**Issue by zobeco** [joomla/joomla-cms#24824]
### Steps to reproduce the issue

Mine website is not getting redirect from http://www.zobeco.com to https://www.zobeco.com. I have purchased an SSL certificate from hosting provider. i have installed the redirect plugin but not getting SSL secure.

**Comment by ghost** [comment]
@zobeco as answered in #24823 please ask on [Forum](https://forum.joomla.org/) as this Reporitory is for Coding. Thanks for your Understanding.
