### ISSUE TITLE
[4.0] console command can't be called in debug mode

### ISSUE THREAD

**Issue by SniperSister** [joomla/joomla-cms#24839]
### Steps to reproduce the issue
Enable debug mode, call `php cli/joomla.php list`

### Expected result
List returned

### Actual result
`Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Debug\ExceptionHandler::handle() must be an instance of Exception, instance of Error given in [..]/libraries/vendor/symfony/debug/ExceptionHandler.php:106`

**Comment by SharkyKZ** [comment]
Test PR #23859 please.

**Comment by ghost** [comment]
Closed as having Pull Request #23859

Thanks for hint, @SharkyKZ
