### ISSUE TITLE
[4.0] skipto not adapted to many languages, specially to RTL

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#24836]
### Steps to reproduce the issue
Install Persian language
Add this file to the Persian admin language where I have translated just a few strings for the demonstration. (Change .txt to .ini) and switch admin language.

[fa-IR.plg_system_skipto.txt](https://github.com/joomla/joomla-cms/files/3156006/fa-IR.plg_system_skipto.txt)

### Results
In English

<img width="515" alt="Screen Shot 2019-05-08 at 09 27 28" src="https://user-images.githubusercontent.com/869724/57357615-9f577f00-7173-11e9-83bd-3c023a5a9739.png">

In Persian

<img width="657" alt="Screen Shot 2019-05-08 at 09 07 24" src="https://user-images.githubusercontent.com/869724/57357280-e002c880-7172-11e9-920e-e0cfd95a1b48.png">

![Screen Shot 2019-05-08 at 09 35 38](https://user-images.githubusercontent.com/869724/57358018-b9459180-7174-11e9-9f03-2e40b2669d99.png)

The words "Main:", "Nav:" and "Search" are not translated, **whatever the language**.

**In RTL**, the dropdown is displayed to the left of the screen and the text-align is set to left, although both should be to the right.

We should get something like this (h1, h2, are correctly displayed when the item concerned is rtl language):

<img width="717" alt="Screen Shot 2019-05-08 at 10 29 16" src="https://user-images.githubusercontent.com/869724/57361218-39bbc080-717c-11e9-9b5a-5a850ecd994d.png">

The`SkipTo.css` file is loaded first from the vendor folder. It should be possible therefore to add a `build/plg_system_skipto/css/SkipTo-rtl.min.css` which would be loaded by `skipto.php` when language is RTL. 
Remains to decide if it should be a complete file or just contain the necessary overrides.

**Comment by brianteeman** [comment]
> The words "Main:", "Nav:" and "Search" are not translated, whatever the language.

They are aria terms so should not be translated

**Comment by infograf768** [comment]
I understand these ARIA role terms are normally markup terms i.e. `<main>` or `<nav> ... </nav>` or `<search>`
I still don't understand why they should be displayed as such in the dropdown.
Is it simply an overseen in the js?

Modified Note: Do I mistake or `Search` does not display the Search field? 
It does focus after tabbing but the page has already scrolled down, thus hiding the field.

**Comment by brianteeman** [comment]
Hopefully most of this will be resolved by #31854

**Comment by Quy** [comment]
@infograf768 Please confirm fix with PR #32043.

**Comment by infograf768** [comment]
Will try to test asap

**Comment by infograf768** [comment]
remains some stuff todo. Creating issue now.
Closing this one.
