### ISSUE TITLE
[4.0] Alpha8 %00 Internal Server Error

### ISSUE THREAD

**Issue by GoolaGong** [joomla/joomla-cms#24830]
### Steps to reproduce the issue
I'm a novice at testing new versions of Joomla, but wanted to test Joomla 4 before it was issued formally and I had to try and upgrade from 3.9.
I installed it first on my PC under XAMPP, copied a few articles and categories from the live site and everything worked without problem.
I then set up a new sub-domain of my live site on my host, created a database and installed Joomla 4.0.0 alpha8 and basically repeated what I'd set up on my PC.

### Expected result
When the test site was loaded, the Home page appeared with no problem and I expected the two other menu items to display as they had on my PC under XAMPP.

### Actual result
The actual result of clicking on a menu item was to get a 500 Server error. 
I tried changing the Menu Items "Default Page" and each page loaded correctly as expected but again clicking on another menu item would cause the 500 server error.  I repeated this test for each of the three menu items.

### System information (as much as possible)
[systeminfo-2019-05-07T15_41_56+01_00.txt](https://github.com/joomla/joomla-cms/files/3153170/systeminfo-2019-05-07T15_41_56%2B01_00.txt)

**Comment by ReLater** [comment]
Maybe it's better to give a nightly build a chance?
https://developer.joomla.org/nightly-builds.html

**Comment by GoolaGong** [comment]
Just tried that - Your site has been updated. Your Joomla version is now 4.0.0-alpha9-dev.

Site won't load at all now: Error: Unknown column 'm.publish_up' in 'where clause': Unknown column 'm.publish_up' in 'where clause'

**Comment by ReLater** [comment]
I'm not sure if I understood you correctly.
It's not possible to update from Joomla 3.9 to Joomla 4. Joomla 3.10 will be the first version that will be prepared for updates to Joomla 4. You have to wait.

**Comment by GoolaGong** [comment]
No, indeed. I have the main site (Joomla 3.9) installed under www...., a dev... test site (Joomla 3.9), in a sub-domain, where I test changes and carry out updates before implementing on the main site. I then set up a further sub-domian, dev4... where I installed Joomla 4.0 Alpha 8. All "three" sites have their own database and are complete separate Joomla installations.
So, I tried to update Alpha 8 to Alpha 9 and got this error. I intend now downloading the full Alpha 9, delete everything off the "dev4" sub-domain, delete the associated database, create a new one and then install Alpha 9 and see what happens.

**Comment by ReLater** [comment]
> I tried to update Alpha 8 to Alpha 9

Yes, it's not guaranteed that updates from J4-whatever to J4-whenever work. All I know is that I can/could update my `Joomla 4 nightly` to `Joomla 4 nightly of the following day` for a longer time via `Joomla! Update` > `Upload & Update` (FULL or UPGRADE package) with a database fix afterwards `administrator/index.php?option=com_installer&view=database`.

But "not guaranteed".

Thus your find is "known behavior" and you should close this issue.

**Comment by ghost** [comment]
Updates from alpha to alpha are not supported. Best to use nightly as suggested. Joomla4 iin Beta will then support updates from Nightly to Nightly. For this Reason Issue closed.

**Comment by GoolaGong** [comment]
Thanks for suggestions, etc. I've just rebuilt my test Joomla 4.0 Alpha 9, added two articles, no changes to settings (other than a couple in Configuration) and I'm getting exactly the same problem "500 Internal Server Error".

**Comment by ReLater** [comment]
- Set Error Reporting to Maximum and enable Debug (System) inside Global Configuration.
- Did you rename `htaccess.txt` to `.htaccess` ?
`sef_rewrite: true` (your system informations say that).

**Comment by GoolaGong** [comment]
Cracked my problem! 
How did I forget to rename htaccess.txt?
My apologies for wasting everybody's time and very many thanks for your help.
