### ISSUE TITLE
Sorry if this is the wrong place code is showing up on the front end

### ISSUE THREAD

**Issue by ehatcher** [joomla/joomla-cms#24842]
I don't know how or when it started because the code only shows up on Chrome and Edge and not Firefox. I do most things in firefox. I have attached a photo. Is it a setting? or a bug?

![website chrome and edge 3](https://user-images.githubusercontent.com/17323554/57416920-4964f480-71d0-11e9-9c90-52412a9c2dc2.png)

### Steps to reproduce the issue
I have no idea. I think it may be a setting for accessibility?

### Expected result
a website with no code showing

### Actual result
Some sections have code showing starting with
Go to table of contents (Keyboard shortcut: ALT + SHIFT + 0)

### System information (as much as possible)
Joomla 3.96
template gantry 4. 1..39

**Comment by Quy** [comment]
Please ask help in Joomla Forum https://forum.joomla.org/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24842">issues.joomla.org/tracker/joomla-cms/24842</a>.</sub>
