### ISSUE TITLE
[4.0] Extended Search Tools for Categories - select parent category

### ISSUE THREAD

**Issue by reillplast** [joomla/joomla-cms#24844]
In order to sort many subcategories more easily, an additional filter similar to the menu items (see screenshot = select parent menu item) would be helpful. This would allow to select a parent category to filter.

<img width="1158" alt="Select-Parent-Category" src="https://user-images.githubusercontent.com/19149137/57447717-f9ca0b80-7257-11e9-9c0f-d997d0419831.png">

**Comment by ReLater** [comment]
As far as I know there won't go new features into Joomla 3. Only bug fixes.

Maybe you have a chance in Joomla 4 and maybe @franz-wohlkoenig changes the label accordingly. You should mention Joomla 4 then in your opening https://github.com/joomla/joomla-cms/issues/24844#issue-442174750 .

**Comment by Quy** [comment]
Related PR #17211?

**Comment by brianteeman** [comment]
see #27486
