### ISSUE TITLE
ERROR: Invalid login - Joomla 3.9.6

### ISSUE THREAD

**Issue by Fassendek** [joomla/joomla-cms#24845]
Hello! I'm trying to update to Joomla 3.9.6 and I get this javascript alert:
**ERROR: Invalid login.**
I'm not the only one with this problem. I read a lot of material on this topic, but did not find the cause and method of solving this problem. And on earlier versions of Joomla! was the same problem since 3.9.0 Prompt how to update and get rid of this problem? Changing the browser and manual installation did not give anything, again the same: ERROR: Invalid login.. What to do?
![ошибка_обновления](https://user-images.githubusercontent.com/19346208/57457122-93ed7c00-7277-11e9-8b7c-d8551ed6290d.png)

**Comment by ReLater** [comment]
I saw this error in the past because of a "strange" line in my .htaccess file. In that case it was a line that should block some bot requests. Thus: Try again after deactivating your htaccess.

**Comment by Fassendek** [comment]
Deactivating file .htaccess doesn't help!

**Comment by ghost** [comment]
@Fassendek Please ask on [Forum](https://forum.joomla.org/)
