### ISSUE TITLE
[4.0] Action Logs show constant rather than value

### ISSUE THREAD

**Issue by twister65** [joomla/joomla-cms#24846]
### Steps to reproduce the issue
- Enable or disable a plugin.
- Watch the Latest Actions module in the Control Panel

### Expected result
User xxx published the plugin plg_captcha_recaptcha_invisible

### Actual result
PLG_SYSTEM_ACTIONLOGS_CONTENT_PUBLISHED

### System information (as much as possible)
- Joomla! Version: Joomla! 4.0.0-alpha9-dev Development [ Amani ] 19-April-2019 09:23 GMT
- Database Type: mysql
- Database Version: 5.7.26-0ubuntu0.18.04.1

### Additional comments
It works fine with Joomla 3.9.6.

**Comment by ghost** [comment]
is this also an issue using Nightly Build?

**Comment by twister65** [comment]
This is the Nightly Build from this day.

**Comment by twister65** [comment]
This is another issue : System information is not correct.

**Comment by brianteeman** [comment]
please open a new issue report for each issue

**Comment by twister65** [comment]
We have PR #24847
