### ISSUE TITLE
[4.0] Changelog js error

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#24849]
The new code to display the changelog of an available update in the extension manager produces a javascript error when you click on the button

/cc @roland-d 

```
core.min.js?384e8209bc67fc38429624bf76893747:1 Uncaught TypeError: Cannot set property 'innerHTML' of undefined
    at onSuccess (core.min.js?384e8209bc67fc38429624bf76893747:1)
    at XMLHttpRequest.c.onreadystatechange (core.min.js?384e8209bc67fc38429624bf76893747:1)
onSuccess @ core.min.js?384e8209bc67fc38429624bf76893747:1
c.onreadystatechange @ core.min.js?384e8209bc67fc38429624bf76893747:1
XMLHttpRequest.send (async)
a.request @ core.min.js?384e8209bc67fc38429624bf76893747:1
a.loadChangelog @ core.min.js?384e8209bc67fc38429624bf76893747:1
onclick @ index.php?option=com_installer&view=update:546
```

**Comment by C-Lodder** [comment]
@brianteeman https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/system/js/core.es6.js#L938

Try replacing:
```
document.querySelectorAll(`#changelogModal${extensionId} .modal-body`)[0].innerHTML = result.data;
```

with this:

```
document.querySelector(`#changelogModal .modal-body`).innerHTML = result.data;
```

Although this Javascript really needs to be moved out of `core.js` and into a separate file associated with `com_installer`: https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/com_installer/js/installer.es6.js

Perhaps someone can move the inline JS too: https://github.com/joomla/joomla-cms/pull/24026/files#diff-8bbf22d9af9d1d1e6f15a80c694446e2R109

**Comment by brianteeman** [comment]
Thanks @C-Lodder I will leave it for someone else to make the pr

**Comment by roland-d** [comment]
Closing as we have a PR #24890
