### ISSUE TITLE
[4.0] icon width

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#24853]
Fontawesome icons are **not** all the same width. In some circumstances this results in undesired behaviour as seen below

![eye](https://user-images.githubusercontent.com/1296369/57555395-148da480-736c-11e9-8c6f-e212f5f9aaaf.gif)

Ref:
https://fontawesome.com/how-to-use/on-the-web/styling/fixed-width-icons

**Comment by B3nito** [comment]
you can use fw class

**Comment by brianteeman** [comment]
Yes thats exactly what is in the link

**Comment by B3nito** [comment]
Yes, you only need to change the icon, its not a big problem.
