### ISSUE TITLE
[4.0] Language and auto update plugins

### ISSUE THREAD

**Issue by Rakeshmvd** [joomla/joomla-cms#24856]
Feature request.

Please add these two plugins as standard plugins.

They are so simple and yet very important for the further progress of Joomla. They really need to be implemented as standard plugins since they add really necesary functions.

EasyLanguage http://www.isapp.it/en/easy-language/83-easy-language-en.html
Auto update through cron: https://www.joomlashowroom.com/products/auto-update-for-joomla

Please add them!

EasyLanguage: To use simply insert the following code in the template, editor or any editable field of any component or module:
{lang en}Text english{/lang}
{lang it}Testo italiano{/lang}
{lang de}Deutsch Text{/lang}

**Comment by mbabker** [comment]
Randomly adding a plugin that supports automatic updates is a bad idea.  Search through this tracker, there are several discussions over the years dealing with automatic update support.  The TL;DR here is it is much more than slapping some code in the CMS and shipping it.

**Comment by infograf768** [comment]
As for easylanguage, I just had a look at it.
The plugin implies an obsolete replacement of the language switcher module helper (it does not consider component items associations).
It also needs an override of the search content plugin.
Its code would need a full refactoring and can't be integrated as is in Joomla.

In any case, one is free to get it from JED and use if desired (and conscious of the consequences).

Closing as not joomla core

**Comment by Rakeshmvd** [comment]
As a Joomla user since version 1.0, I have never liked the joomla muli-language system. Creating three menu's for two languages is illogical and very cubersome as websites change often. With the rise of various Page-Builders and their new structure, I see that Joomla is getting momentum again. These PageBuilders have trouble with Joomla's language system, so a second option is really necessary. With EasyLanguage, you do not need the three menu ways anymore. This is in my opinion the right way foreward, by using this as a standard second option, you make many people happy I believe.

As for the auto update, one of the major reasons so many left Joomla and went to Wordpress. Time to address this too with J4 and tackle this finally.

I understand it is not a copy-paste plugin situation, but there is still time from this Alpha stage. It can still be implemented in time before the final release.
