### ISSUE TITLE
[4.0] Menu collapsed when returning

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#24855]
Select a component from the menu

### Expected result
Menu remains open when you return to the list view from the edit view

### Actual result
Menu collapsed 
![menu](https://user-images.githubusercontent.com/1296369/57559519-1b231880-737a-11e9-9f27-ae1b8b98de5b.gif)

**Comment by SharkyKZ** [comment]
Test PR https://github.com/joomla/joomla-cms/pull/24801 please.

**Comment by brianteeman** [comment]
From the title of that PR I couldnt see how it was related. I can now - thanks
