### ISSUE TITLE
[4.0] User action log - name or user

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#24862]
In the user action log we use name and user inconsistently

![image](https://user-images.githubusercontent.com/1296369/57581693-e2d32580-74b2-11e9-95e0-1cf1042edb87.png)

Here it says user "brian-login" where "brian-login" is the field username and
Name = "brian" where "brian" is the field name

But here in the filter
![image](https://user-images.githubusercontent.com/1296369/57581712-30e82900-74b3-11e9-8a7d-c1768637d6a1.png)

It says user is "brian" where "brian" is the field name

**Comment by alikon** [comment]
@roland-d can you consider this on in #24936

**Comment by roland-d** [comment]
@alikon I checked but this is a big change, it is worth to have it's own PR as it needs changing quite a few functions and language files.

**Comment by zero-24** [comment]
As this has been merged into 3.9: https://github.com/joomla/joomla-cms/pull/24992 i think we can close here? Or do you want to keep this here open until it is merged up to 4.0? @brianteeman @roland-d @alikon ?

**Comment by infograf768** [comment]
@zero-24 
please see my comment
https://github.com/joomla/joomla-cms/pull/24992#issuecomment-504639720

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/25291

**Comment by zero-24** [comment]
Merged thanks.
