### ISSUE TITLE
[4.0] UCM state and history not updated when changing item state in list view.

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#24878]
### Steps to reproduce the issue

Create an article or contact. Add some tags.
Go to item list. Change item state (publish/unpublish) using inline or toolbar button.
View item's `core_state` value in `#__ucm_content` table.
Edit the item, view its versions history.

### Expected result

`core_state` value is `1`.
Versions entry created.

### Actual result

`core_state` value is `0`.
Versions entry not created.

### System information (as much as possible)

Current 4.0-dev nightly
PHP 7.2.4

**Comment by richard67** [comment]
It seems saving the UCM stuff when publishing an article is not the only thing which works well in the article edit view but doesn't work in the list view, see issue #24972 .

**Comment by SharkyKZ** [comment]
#24972 seems workflow-related.

My issue appears to be caused by Behavior plugins not running on state change. Issue also affects other content types.

**Comment by brianteeman** [comment]
Yes #24972 is a related issue in that it is all because of the workflow code

**Comment by SharkyKZ** [comment]
Turns out you were right. The state issue is workflow related. See PR https://github.com/joomla/joomla-cms/pull/29197.

And history issue exists in J3 too, related to #8244.
