### ISSUE TITLE
TinyMCE drag & drop - "Unable to upload file" error

### ISSUE THREAD

**Issue by wnkkm** [joomla/joomla-cms#24877]
### Steps to reproduce the issue
1. Create an image folder like "/media/photo/2019" outside joomla's "images" folder;
2. Create a symbolic link of a subfolder "media" in "images" folder for the "/media" folder;
  (so that images/media/... symbolic folder name can access to the physical folder "/media/...")
3. Configure TinyMCE's plugin setting "Images Directory" to have "media/photo/2019";
4. Edit an article with TinyMCE editor, and try drag-and-drop an image file into the edit window.

### Expected result
The drag-and-dropped image should be shown in the article's edit window after the image file was uploaded to the subfolder "/media/photo/2019/".

### Actual result
The image file was not uploaded, and "Unable to upload file.: /jmlundefined" error message was popped up.

### System information (as much as possible)
Joomla 3.9.6.  PHP 7.2.18

### Additional comments
This problem happened since Joomla 3.9.5, and was not fixed in 3.9.6.
Only a symbolic linked path for Images Directory of TinyMCE seems to show the problem, but no problem with a physical path setting for Images Directory setting  of TinyMCE plugin.
A symbolic directory link had worked fine with image drag-and-drop in TinyMCE editor before upgrading to 3.9.5.

**Comment by ghost** [comment]
@wnkkm thanks for your Report. Can you please look if #24539 is about same Issue? If yes please comment there and close this Issue.

**Comment by wnkkm** [comment]
Yes, I think the issue https://github.com/joomla/joomla-cms/issues/24539 looks the same issue.
So I close this issue.
