### ISSUE TITLE
Custom fields J3.x

### ISSUE THREAD

**Issue by kat0d** [joomla/joomla-cms#24876]
### Steps to reproduce the issue
- Add user custom field
- try to hide this field from user edit form, and just to show in user profile
or
- assign read-only attribute
or
- disable in the edit form

### Expected result
disable field in the user edit form

### Actual result
#nothing works!!!
where is this futures ?!!!
![image](https://user-images.githubusercontent.com/11921942/57588973-98d75780-7525-11e9-89f0-4e2e1c19058b.png)
only that i see is
![image](https://user-images.githubusercontent.com/11921942/57588984-bd333400-7525-11e9-83ec-9b8ac2bb2d56.png)
and if set this option to "NO" it's disabled field not only in the profile edit form, but in profile page too!!

### System information (as much as possible)
Joomla 3.9.6
php 7.2

### Additional comments

- add to repeatable field more field types by default, e.g. calendar, radio, checkboxes, **SELECT LIST**
- how do i know, what default values i need to fill with repeatable field ?? add explanation here https://docs.joomla.org/Special:MyLanguage/J3.x:Adding_custom_fields/Repeatable_Field

**Comment by ghost** [comment]
@kat0d thanks for your Report. Is it the same you asked at https://github.com/joomla/joomla-cms/issues/24754#issuecomment-491637331?

**Comment by kat0d** [comment]
@franz-wohlkoenig basically yes. i just can't find out, is it i'm missing something, or it's just really bugs. because custom fields exists quite long time in Joomla. and this is not full list of their bugs.

**Comment by Quy** [comment]
So this is the same issue as #24754?

**Comment by kat0d** [comment]
@Quy no, we are pursuing the same goal, as I understand it. But these are different bugs. we use different options.
and there is one more
if you not allow edit custom field values in field permissions
![image](https://user-images.githubusercontent.com/11921942/57632531-82271400-75aa-11e9-89e1-f20ded8da2ae.png)
if this field is present in user profile edit form(which i can't disable with Joomla options), so you get an error, when you save the form
![j3bug](https://user-images.githubusercontent.com/11921942/57632911-4e002300-75ab-11e9-938b-de86f48de783.gif)

**Comment by kat0d** [comment]
my goal:
- add repeatable field, so admin can add fields, and user can see this fields in user profile page, but can't see it in user edit form, or at least can't edit it. and this simple task is currently impossible with standard joomla options.

**Comment by kat0d** [comment]
ok, so here is a quick, if someone need this future now
- disable "Edit Custom Field Value" in field "Permissions" tab
create template rewrite:
JOOMLA-SITE\components\com_users\views\profile\tmpl\edit.php
now it's in your template
JOOMLA-SITE\templates\JOOMLA-TEMPLATE\html\com_users\profile\edit.php

find:
```php
<?php if ($field->hidden) : ?>
```
in my case it's line 68
add before this line:
```php
<?php if ($field->disabled){ continue; } ?>
```
you're done, BUT, if you have only one field in fieldset group, you will have an empty fieldset in edit form, so hide it with css, or assign field to other fieldset group with more than one field.

i can't believe this. custom fields starts from J3.7, and no one don't use it like this. or am i an idiot:)


and what it for ??
![image](https://user-images.githubusercontent.com/11921942/57640647-bfe06880-75bb-11e9-94c2-22ac296f6db8.png)
if field is hidden, for what reason to show field input ??

**Comment by ghost** [comment]
@laoneo ?

**Comment by alikon** [comment]
Closing this due to not receiving required information to determine if this is a bug or not. If you feel this still needs review, please open a new tracker entry with as much information as possible to ensure it can be reviewed properly
