### ISSUE TITLE
[4.0] Regression in JMail

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#24885]
We've got a regression in the mailer. As part of this pull request moving us to exception handling, we're failing to resend the email https://github.com/joomla/joomla-cms/pull/21320/files#diff-5aaa46eebca8b0cbd13c16868c45123aR130 if the auto tls feature is enabled (or attempting to disable it for that matter). I strongly suspect this is the reason that @brianteeman had issues in the privacy component here https://github.com/joomla/joomla-cms/pull/24874#issuecomment-491799741

**Comment by brianteeman** [comment]
further testing shows I get thT 500 ERROR whenever I try to send a mail

**Comment by wilsonge** [comment]
Try this https://github.com/joomla/joomla-cms/pull/24886 - it's required either way. I'll leave this one open for now however as there might be more required for your issue

**Comment by joeforjoomla** [comment]
@wilsonge i had already opened this one that i reference: https://github.com/joomla/joomla-cms/issues/24241

**Comment by wilsonge** [comment]
Ahh nice. I'd missed that :)

**Comment by wilsonge** [comment]
Looks like this is solved by #24886
