### ISSUE TITLE
JFile::upload should return result code instead of boolean

### ISSUE THREAD

**Issue by olleharstedt** [joomla/joomla-cms#24887]
### Is your feature request related to a problem? Please describe.

If upload file fails, you want to know why so that you can show an error message to the user and also react accordingly in the code. Right now, the type of the error is just recorded in the log.

### Describe the solution you'd like

Return integer instead of boolean. OR throw an exception.

To increase backward compatibility, 1 can be success, failure can be 0, -1, -2, etc.

### Additional context

https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Filesystem/File.php#L531

I will create a PR when an accepted solution is agreed upon (result code vs exception).

**Comment by HLeithner** [comment]
changing this would be a b/c break even if it shouldn't be too bad, did you checked if this is still a valid issue in j4?

**Comment by olleharstedt** [comment]
Yes, this is still an issue in 4: https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Filesystem/File.php#L449

**Comment by olleharstedt** [comment]
Also see discussion here: https://github.com/joomla/joomla-cms/pull/20438

**Comment by HLeithner** [comment]
So you already got your answer from Michael https://github.com/joomla/joomla-cms/pull/20438#issuecomment-389866320 

please create a pull request against the framework and throw a exception if it doesn't succeed.

**Comment by olleharstedt** [comment]
Eh, no. Because it doesn't answer whether or not you prefer a result code or throwing an exception. Please read the whole thread. This issue is not about promoting my old PR.

**Comment by HLeithner** [comment]
My fault it's not in the framework its in the CMS.

**Comment by olleharstedt** [comment]
Done: https://github.com/joomla/joomla-cms/pull/24894
