### ISSUE TITLE
[4.0] Plugin as services ERROR

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#24907]
### Steps to reproduce the issue
after Plugin as services (#20547) the home page displays

 An error has occurred.
0 Class 'Joomla\Plugin\Quickicon\Joomlaupdate\Extension\Joomlaupdate' not found

/cc @laoneo

**Comment by SharkyKZ** [comment]
If you updated from a previous nightly, delete `libraries/autoload_psr4.php` so it can be regenerated.

**Comment by infograf768** [comment]
Closing as @SharkyKZ reply is correct.

**Comment by laoneo** [comment]
Thanks @SharkyKZ for the fast response.

**Comment by brianteeman** [comment]
Thank you!!

**Comment by pe7er** [comment]
Thanks!
