### ISSUE TITLE
[4.0] Introduce a concept of multi select field before it's too late

### ISSUE THREAD

**Issue by lambdaheart** [joomla/joomla-cms#24918]
### Is your feature request related to a problem? Please describe.
Currently if I want to use custom fields for implementing article gallery or attachments I could use something like `repeatable` field and then construct a subform with `media` field for attaching the image and `text` field for adding caption to that image.

However, this is pain in the a** because user has to add images one by one.

### Describe the solution you'd like
Perfect solution would be to introduce concept of multi select field type from which other fields could inherit.

Inheriting from `multi_select` shouldn't mean that this field should necessarily always return multiple items, just that it can return multiple items if required to do so.

For example, here's how already existing fields could behave when they implement `multi_select`:

+ media : user could select multiple files at once returning array of files
+ calendar : user could select a range of dates at once returning array of dates
+ user : user could select multiple users at once returning array of users

And some potential new fields that I'd also like to see:

+ article : user can select multiple articles at once returning array of articles

---

So the idea here is that fields that implement `multi_select` would behave like normal single select fields as they usually do (e.g. media, user, calendar ...), but when they are within `repeatable` field a select box would appear above the `repeatable` field table allowing us to choose by which `multi_select` field in `repeatable` field we want to add new rows.

At first I thought that if there are multiple `multi_select` fields within the `repeatable` field that we should somehow select which one is "primary" but then again, why should we not be able to add new rows by any `multi_select` field?

### Additional context

Here's the ascii layout sketch of what I'm imagining:

```
--------------------------------------------
| Media          ▼ | [Add New Rows Button] |
--------------------------------------------

-------------------------------------------------------------
| Image 01 [Edit] | User 01 [Edit] | Some text field 01 | [x]
-------------------------------------------------------------
| Image 02 [Edit] | User 02 [Edit] | Some text field 02 | [x]
-------------------------------------------------------------
| Image 03 [Edit] | User 03 [Edit] | Some text field 03 | [x]
-------------------------------------------------------------
| Image 04 [Edit] | User 04 [Edit] | Some text field 04 | [x]
-------------------------------------------------------------
| Image 05 [Edit] | User 05 [Edit] | Some text field 05 | [x]
-------------------------------------------------------------
| Image 06 [Edit] | User 06 [Edit] | Some text field 06 | [x]
-------------------------------------------------------------
```

So basically, here are two `multi_select` fields (`media` and `user`) within the `repeatable` field and a normal `text` field. 

Before the `repeatable` items there is a drop down list where we can select either `media` or `user` field, and once we do we can click `Add New Rows Button` which will open modal where we can either select multiple files form media manager, or multiple users from user list.

When we select `n` users from the user list modal window we get `n` new rows with those selected users but all other fields empty, leaving it to the user to fill them in.

We can also change from `user` to `media` and after clicking `Add New Rows Button` we could add additional `x` rows after selecting `x` images.

If we try to change e.g. `Image 04` from the example we get modal window again, but this time we can only select one image for that particular row in `repeatable`.

---

I think this is a good idea which would make custom fields extremely useful, but it could go to waste if we are late with adoption.

So far media manager is the main blocker for this feature because it is very bad and can't select multiple images (and files not at all) from the modal window, and he is the main feature required for creating galleries, attachments and such.

**Comment by ghost** [comment]
Please add "[4.0]" at Start of Title as new Features go in J4.

**Comment by ghost** [comment]
@alikon something to comment as Feature Request?

**Comment by alikon** [comment]
@franz-wohlkoenig  imo a feature request that can be covered  already with extensions

**Comment by ghost** [comment]
closed for Reason stated above.

Thanks @alikon

**Comment by lambdaheart** [comment]
@alikon @franz-wohlkoenig I don't see how this can be covered with extensions. Whole idea of `repeatable` field is that it integrates with other fields (which can be created by other users).

If a standard for this undoubtedly very useful behaviour is not set in core Joomla then I don't see how two different fields from two different authors can work well with one another in this situation.

**Comment by ghost** [comment]
reopen for further discussion @alikon

**Comment by AndySDH** [comment]
> And some potential new fields that I'd also like to see:
> article : user can select multiple articles at once returning array of articles

For that there already is a fantastic extension for it: https://www.regularlabs.com/extensions/articlesfield/

**Comment by alikon** [comment]
so we have an alternative with a 3dp extension can we close this ?

**Comment by AndySDH** [comment]
This has been merged with Subfields, can be closed
