### ISSUE TITLE
B/C fix - Modules (including core) using the "cache" XML parameter always cached, regardless of that parameter's value

### ISSUE THREAD

**Issue by fevangelou** [joomla/joomla-cms#24917]
### Steps to reproduce the issue
Many Joomla core modules (e.g. mod_menu, mod_custom etc.) as well as lots of third-party modules still use "cache" as the de-facto XML parameter to allow for a module to be cached along with the rest of Joomla's rendered content (when Joomla caching is set to "on") or excluded from Joomla's cache overall.

The current check in JModuleHelper::moduleCache() is currently invalid (checks for the newer "owncache" XML parameter twice).

See pull request https://github.com/joomla/joomla-cms/pull/24916 for the simple fix.

### Expected result
When Joomla's cache is enabled, most core modules with caching set to "no" (usually under the Advanced tab in their parameters) and probably the vast majority of third-party modules are always cached. This should not happen.

**Comment by Quy** [comment]
FYI: It is not necessary to open an issue if you have a PR for it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24917">issues.joomla.org/tracker/joomla-cms/24917</a>.</sub>

**Comment by fevangelou** [comment]
The pull request template mentions a reference to the issue ID at the very top. Perhaps you should explicitly mention there that it's not need to also open an issue. ;)
