### ISSUE TITLE
[4.0] Smart Search Filter Inverse Search

### ISSUE THREAD

**Issue by saraheagle** [joomla/joomla-cms#24923]
### Steps to reproduce the issue
Go to Smart Search >> New Filter >> Edit Filter tab
Currently we can search by type, categories etc and tick on what we want included in the search. 

### Expected result
It would be very useful if we could invert the search so we could tick on what was *not* to be included instead. 

So we could have a category for all articles called "Not Searchable". And tick that so all article categories are searched apart from that one. Otherwise you need to remember to add a new categories to the search filter and this just is not realistic for some admins on some sites.

Thank you :)

**Comment by franz-wohlkoenig** [comment]
changed Title as new Features goes in J4.

**Comment by alikon** [comment]
@Hackwar is this something that you are considering in your smart search re-work?

**Comment by Hackwar** [comment]
This can indeed be done, but it wont be possible for 4.0 anymore, I'm afraid. For 4.1 this can however be considered.

**Comment by Formatio-hippocampi** [comment]
label "new feature".
