### ISSUE TITLE
RSS shows wrong category

### ISSUE THREAD

**Issue by empty88** [joomla/joomla-cms#24926]
### Steps to reproduce the issue
add "?format=feed&type=rss" to an url of a page that contains a category blog that shows all articles in the selected category and its subcategories

### Expected result
tha value of the category tag is the category/subcategory of each article

### Actual result
the value of the category tag is always the selected category of the category blog not of the single feed item (article)

### System information (as much as possible)
Joomla 3.9.6 (just updated)
PHP 7.1.23

### Additional comments
I don't know if it's as intended or a bug, but I would appreciate my expected result

**Comment by ghost** [comment]
Please update on latest Version 3.9.6.

**Comment by empty88** [comment]
I updated now on 3.9.6 but nothing changed

**Comment by ghost** [comment]
have you asked on [Forum](https://forum.joomla.org/) (this Repository is for coding)?

**Comment by SharkyKZ** [comment]
I can confirm this issue.

**Comment by ghost** [comment]
@SharkyKZ so its a Bug and not intended?

**Comment by empty88** [comment]
@franz-wohlkoenig if this is the wrong place for reporting bugs, I will post to the forum, sorry

**Comment by SharkyKZ** [comment]
@franz-wohlkoenig Yes, I think so.

@empty88 this is the right place.

**Comment by ghost** [comment]
@empty88 as its now clear its a bug its the right place :-)

**Comment by empty88** [comment]
Well, now I am very proud of finding a bug and contributing to this excellent project ;-)

**Comment by SharkyKZ** [comment]
Test PR #24932 please.

**Comment by ghost** [comment]
Closed as having Pull Request #24932
