### ISSUE TITLE
[4.0] Reminder due to pr #24921. Remove "HTMLHelper::_('bootstrap.framework');" from modules

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#24922]
### ToDo
- After pr https://github.com/joomla/joomla-cms/pull/24921 is merged check whick modules need line `HTMLHelper::_('bootstrap.framework');`
- See https://github.com/joomla/joomla-cms/pull/24921#issuecomment-493000484

**Comment by richard67** [comment]
```
$ find ./administrator/modules/ -type f -exec grep -l "HTMLHelper::_('bootstrap.framework');" {} \;
./administrator/modules/mod_popular/tmpl/default.php
./administrator/modules/mod_sampledata/tmpl/default.php
./administrator/modules/mod_feed/tmpl/default.php
./administrator/modules/mod_status/tmpl/default.php
./administrator/modules/mod_logged/tmpl/default.php
./administrator/modules/mod_multilangstatus/tmpl/default.php
./administrator/modules/mod_latestactions/tmpl/default.php
./administrator/modules/mod_latest/tmpl/default.php
$
```

```
$ find ./administrator/modules/ -type f -exec grep -l "dropdown" {} \;
./administrator/modules/mod_menu/tmpl/default_submenu.php
./administrator/modules/mod_status/tmpl/default.php
$
```

Don't know if that helps.

**Comment by ReLater** [comment]
Finding is not the ""problem"" but to decide if Bootstrap is loaded also for functionalities of the HTML **output** of the modules.
I don't have the time at the moment to investigate that.

**Comment by richard67** [comment]
So it would need to compare the HTML output produced by the modules listed in my first listing with the content of the same modules when the `HTMLHelper::_('bootstrap.framework');` has been removed, and if output is the same, then the line is obsolete, right? Or does it need more to be investigated?

**Comment by ReLater** [comment]
>  and if output is the same, then the line is obsolete, right?

Yes, if everything functions as before.

Even if I've learned Joomla 4 core doesn't need JQuery/Bootstrap-JS and everything in core will be replaced somehow by Vanilla scripts it looks like that this isn't the fact yet. Thus I'm in doubt if we can remove these lines.

**Comment by richard67** [comment]
I will see if I can find time. But if you find time before me or others, let us known here so we don't do double work.

**Comment by richard67** [comment]
@ReLater Meanwhile I am also in doubt if it is as easy as I assumed it to be. Do you know who could help us with that?

**Comment by ReLater** [comment]
Yes, not easy to test. Time-consuming.

I use a plugin that removes bootstrap-*.js in backend. Then compare the output plus functionalities of the backend modules with and without active plugin. I also deactivate other backend modules as far as possible. 

First result: mod_popular doesn't need bootstrap.

BUT then I've found that `/templates/atum/layouts/chromes/body.php` DOESN'T load bootstrap-*.js but uses it for the edit cog dropdowns of modules. Thus it should load BS if we follow the common practice.

![25-05-_2019_15-42-10](https://user-images.githubusercontent.com/20780646/58370176-c77d0700-7f03-11e9-8093-07af18db62ed.jpg)

Now I think it's better to place a pr first for that find in `body.php` and ask for comments there if it's correct to add `HTMLHelper::_('bootstrap.framework');` where it's missing AND (more important) if it's worth the time to investigate further for other files; instead of waiting.

See my related comment: "Even if **I've learned Joomla 4 core doesn't need JQuery/Bootstrap-JS and everything in core will be replaced somehow by Vanilla scripts** it looks like that this isn't the fact yet."

**Comment by ReLater** [comment]
Maybe @franz-wohlkoenig knows whom to ping?
I try @dgrammatiko , @wilsonge , @Bakual https://github.com/joomla/joomla-cms/issues/24922#issuecomment-495919259

**Comment by ghost** [comment]
@ReLater sorry, have no idea.

**Comment by brianteeman** [comment]
There is NO point looking at this until the new template is completed

**Comment by ReLater** [comment]
From my point of view modules should load their dependencies also with other templates but only if needed.

The main question is: Will be backend core extensions BS and Jquery free or not?

> There is NO point looking at this until the new template is completed

Yes for chrome `body.php`. That's an atum layout. But not mod_popular.

**Comment by wilsonge** [comment]
The backend extensions will be jQuery (direct usages) free. However they won't be Bootstrap free from a CSS perspective. The aim is to make the backend not automatically load the javascript on all pages unless required.
