### ISSUE TITLE
[range] form field sets to min when default value is 0 (zero)

### ISSUE THREAD

**Issue by thednp** [joomla/joomla-cms#24938]
### Steps to reproduce the issue
Anywhere in your template/module options make a new field

```xml
<field 
	name="testrange" 
	type="range" 
	label="Test Range" 
	description="Test range desc" 
	min="-10" 
	max="10"
	step="0.1" 
	class="" 
	default="0"
/>
```
![range-field-issue-code](https://user-images.githubusercontent.com/6761246/57935552-bd875280-78ca-11e9-81eb-515abaa7b6fe.png)

Check module/template admin form

### Expected result
Expecting the form play nice with 0 (zero) values and default values.

### Actual result
![range-issue-front-end](https://user-images.githubusercontent.com/6761246/57935559-c1b37000-78ca-11e9-9808-27d77731709e.png)

### System information (as much as possible)
Joomla 3.9.6
php 7.3.4
mysqlnd 5.0.12-dev

### Additional comments
Possibly related to #8928, I tested the `number` field with same settings, all good. Going to settle there for now.

**Comment by SharkyKZ** [comment]
Test PR #24939 please.
