### ISSUE TITLE
[4.0] Error in Alpha9

### ISSUE THREAD

**Issue by rbuelund** [joomla/joomla-cms#24937]
### Steps to reproduce the issue
Live upgrade to Alpha 10 and repair databse.

### Expected result
A functioning dashboard

### Actual result

Error: Class 'Joomla\Plugin\Quickicon\Joomlaupdate\Extension\Joomlaupdate' not found 

### System information (as much as possible)
PHP 7.3

**Comment by rbuelund** [comment]
Sorry - Alpha 9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24937">issues.joomla.org/tracker/joomla-cms/24937</a>.</sub>

**Comment by SharkyKZ** [comment]
Duplicate #24907. Delete `libraries/autoload_psr4.php` file.
