### ISSUE TITLE
Remove IDs from URLs break manual number urls

### ISSUE THREAD

**Issue by yfxwardy** [joomla/joomla-cms#24930]
### What needs to be fixed
Article - Integration -Remove IDs from URLs - YES

### Why this should be fixed
If we have articles with manual name alias like this - "025-part-of-the-some-book" we get error 404 on this articles. I have many many such pages.
And I dont want to turn this setting off because I need another new blog without automatic articles id.

### How would you fix it
I think the system have to check if there is no manual name alias with number. And dont touch manual alias with numbers.

**Comment by ghost** [comment]
@Hackwar calling but this is for J4

**Comment by brianteeman** [comment]
I have tested this but I cannot replicate the problem am I missing something?

1. My options
![image](https://user-images.githubusercontent.com/1296369/58021545-193c2080-7b03-11e9-811a-a3a83e52fbf0.png)

2. My url
![image](https://user-images.githubusercontent.com/1296369/58021567-26590f80-7b03-11e9-85f3-9f4ed75071bc.png)

3. Front end 
![image](https://user-images.githubusercontent.com/1296369/58021600-3ec92a00-7b03-11e9-9206-12143f63e566.png)

**Comment by yfxwardy** [comment]
> I have tested this but I cannot replicate the problem am I missing something?

@brianteeman, 
I don't know why exactly you cant replicate this problem.
Maybe it is  Global Configuration - Use URL Rewriting (But I tested - it isn't)
Maybe some old article or category layout override? Don't know.

My joomla version: 3.9.6
PHP Version | 7.2.15
Web Server | Apache/2.4.7
I have several nesting levels in menu and in categories
![2019-05-20 20_14_34-Menus_ Items](https://user-images.githubusercontent.com/4341610/58039820-861fdc80-7b3c-11e9-95dd-ecf614ae26ec.png)
![2019-05-20 20_15_37-Articles_ Categories](https://user-images.githubusercontent.com/4341610/58039832-8a4bfa00-7b3c-11e9-80f7-0846f0c07ed7.png)
![2019-05-20 20_16_08-Articles](https://user-images.githubusercontent.com/4341610/58039835-8c15bd80-7b3c-11e9-8f92-c4b74bb0ca06.png)
I don't have menu items on child articles

With your screens I see you have another admin template or another joomla version
How can I help you another way?

I have written you email with a link to my site

**Comment by brianteeman** [comment]
The first post said joomla 4 - that's what I used

**Comment by yfxwardy** [comment]
@brianteeman 
This was transffered not by me.
Will you help me or We should wait Joomla 4 to work with?

**Comment by ghost** [comment]
@Robespeler there was no Information about which Version you wrote so i guessed J4.

**Comment by yfxwardy** [comment]
@franz-wohlkoenig 
Sorry If it was my mistake
I thought that you transffered it to explain this problem will be solved in joomla 4

**Comment by ghost** [comment]
if its a new Feature it goes in J4, Bugs needs to be solved in J3.

**Comment by brianteeman** [comment]
@franz-wohlkoenig it is a bug report

@Robespeler I have also tested it on one of my sites and an article with an alias of `27-september-2017` loaded as expected

**Comment by yfxwardy** [comment]
I tested with more attention and ...
It is some another problem. 
If Remove IDs from URLs - Yes
I have error 404 with any normal alias too. Number in alias doesn't matter.
Now I just don't know why I have 404 error with this setting on.

**Comment by brianteeman** [comment]
I suggest that you ask for support on the forum
