### ISSUE TITLE
[4.0] Duplicate field labels

### ISSUE THREAD

**Issue by roland-d** [joomla/joomla-cms#24940]
### Steps to reproduce the issue
1. Go to Users list
2. Edit a user
3. Notice that the options at the bottom have a duplicate field label
<img width="605" alt="image" src="https://user-images.githubusercontent.com/359377/57966570-1f3fcf00-7954-11e9-9bc5-6fc1b1438eba.png">

### Expected result
The field will have only 1 label

### Actual result
The field has a duplicate label

### System information (as much as possible)
Joomla 4.0-dev branch

This happens due to the `switcher` class

/cc @brianteeman

**Comment by roland-d** [comment]
Perhaps related #24802

**Comment by richard67** [comment]
Same with the switcher in the "User Actions Log Options" tab.

All controls have a control label div. Switcher fieldset in addition has legend:
![Unbenannt](https://user-images.githubusercontent.com/7413183/57968135-e6f5bc00-7966-11e9-9f32-c0890534b971.png)

Not sure what the right solution is: To make the legend invisible (display: none) or not to output the control label div for a switcher field.

Let's wait for Brian's feedback.

**Comment by brianteeman** [comment]
No display: none is not the solution. It was working perfectly - not sure what has been changed but i will take a look

**Comment by brianteeman** [comment]
Fixed - see #24942

**Comment by ghost** [comment]
Closed as having Pull Request #24942
