### ISSUE TITLE
Ajax doesn't work for child menus if you change the menu

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#24948]
### Steps to reproduce the issue
Create a menu item, it doesn't matter which one.
Go to menus, look at the option for "parent item".
If you have parents within the menu they are available or else it says "menu item root".

Change the "menu".
now to go "parent item".  It only offers you "menu item root".  

Click on save.  Now click on "parent item", you see all of the parent items are available.

### Expected result
I thought this used to work when you changed menu item.  Perhaps I am wrong, or perhaps something has changed.
It is not intuitive that you have to save, this should occur automatically unless there is a reason not to.

### Actual result
New users need to know that saving will bring up the other menu items or else become confused or think the system does not work properly.

### System information (as much as possible)
=============
System Information
=============
php: Linux squareballoon.gds.guru.net.uk 3.10.0-714.10.2.lve1.5.19.3.el7.x86_64 #1 SMP Tue Aug 7 21:33:29 EDT 2018 x86_64
dbserver: mysql
dbversion: 5.7.26
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 7.2.18
server: LiteSpeed
sapi_name: litespeed
version: Joomla! 3.9.6 Stable [ Amani ] 7-May-2019 15:00 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by brianteeman** [comment]
Can't replicate this
![newmenu](https://user-images.githubusercontent.com/1296369/58045452-72737680-7b3a-11e9-9d0b-1ed9c6557db1.gif)

**Comment by uglyeoin** [comment]
Me either, I've tried on a few sites in different browsers.  Not sure what occurred there, must have been a dodgy loading problem.  If I encounter it a little more consistently I'll try to work out why.
