### ISSUE TITLE
Batch moving menu items to a new menu only works if you click a menu item

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#24945]
### Steps to reproduce the issue
Create two menus both with items and child items.
Try to move a menu from the secondary menu to the primary menu "menu item root"

### Expected result
Menus move

### Actual result
Menus get added to the current menu or sometimes just disappear.

If you try to move them to an **item** in the primary menu they move successfully. 

At that point you can click on the individual item and manually change it from the "parent item" dropdown to "menu item root" and it works.  But they have to start in the right menu in the first place.

### System information (as much as possible)
=============
System Information
=============
php: Linux squareballoon.gds.guru.net.uk 3.10.0-714.10.2.lve1.5.19.3.el7.x86_64 #1 SMP Tue Aug 7 21:33:29 EDT 2018 x86_64
dbserver: mysql
dbversion: 5.7.26
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 7.2.18
server: LiteSpeed
sapi_name: litespeed
version: Joomla! 3.9.6 Stable [ Amani ] 7-May-2019 15:00 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0

### Additional comments
I seem to be encountering a lot of weird issues today.  Could this be localised to my setup?

**Comment by ghost** [comment]
@uglyeoin can you please write System Informations in Comment soe People haven't to download them?

**Comment by uglyeoin** [comment]
Thanks @franz-wohlkoenig done and will continue to do so moving forwards.  Good tip thanks.

**Comment by brianteeman** [comment]
~You are mistaken - "menu item root" is not a different menu it is the top level of the current menu. So if you do what you did then you get the expected result~ Sorry misread

**Comment by infograf768** [comment]
Not sure I understand.
let's say you want to batch move "menu-item-1"
No where we see "menu item root" but instead "Add to this menu" in the dropdown and also the menu items for that menu.
If "Add to this menu" is selected in batch and Move, the "menu-item-1" item is rightfully moved to the root of the selected menu.
If one selects a menu item instead in the dropdown, the "menu-item-1" is added as child of this menu item.

![Screen Shot 2019-05-24 at 17 11 35](https://user-images.githubusercontent.com/869724/58337882-0bf69d00-7e47-11e9-8c0b-13ce820bcc7a.png)

For me there is no bug.

**Comment by alikon** [comment]
normal for me too (or i don't understand the issue)

**Comment by infograf768** [comment]
Closing. Can be reopened if necessary with screenshots explaining the issue in details
