### ISSUE TITLE
403 Forbidden Error Getting Worse and Spreading

### ISSUE THREAD

**Issue by simcoblog** [joomla/joomla-cms#24950]
I started getting the 403 Forbidden Error about two years ago when I tried to close a few of the content pages/files I created for the two sites I built using Joomla back in 2012.  I've Googled and seen people talk about a possible conflict between Joomla and ModSecurity.

My Web hosting company does not allow individual customers to tinker with ModSecurity settings, but they will do it for you if you go through live chat with them so they can watch exactly which file triggers the error.  I've not gone down that path, hoping when Joomla 4.0 comes out later this year, the 403 error will disappear.  BTW, they wouldn't even tell me which version of ModSecurity they're running (odd).

But this problem seems to be getting worse.  I'm currently running Joomla 3.9.5 and all of a sudden I started getting this error when I close the CSS file for the Prostar template that comes with Joomla.  (I have to edit that file to display side-by-side banners.)  I also started getting the same error when I close the banner files that I set up several years ago.  I never had trouble editing/closing the Prostar file and my banner files before (I usually edit my banner files once a month).  Upgrading to Joomla 3.9.6 didn't help.  In fact, I thought 3.9.6 was the culprit and actually did a Softaculous restore to go back to 3.9.5.

I've looked at the ModSecurity site, but I figure I'd try the Joomla issue tracker first.  Ok, I'm seeing a real-time message about the Joomla Security Strike Team.  I'll ignore that for now as my problem is not a "security" issue.

**Comment by Quy** [comment]
Please ask help in Joomla Forum. https://forum.joomla.org/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24950">issues.joomla.org/tracker/joomla-cms/24950</a>.</sub>
