### ISSUE TITLE
Smart Search not finding content with "21"

### ISSUE THREAD

**Issue by lairdf** [joomla/joomla-cms#24955]
### Steps to reproduce the issue
- Create an article with a title of "Century 21"
- Create a menu item for smart search
- Search for "century 21" 

### Expected result
- Expect to find the content matching "century 21"

### Actual result
- Article is not found.

### System information (as much as possible)
Joomla! 3.9.4 (and tested also on Joomla! 3.9.5 and Joomla! 3.9.6)

### Additional comments
Changing the content to "century 211", it works.  Other combinations work ("century 40" works fine) 
"Century 1" fails
"Century 2" fails
"Century 21" fails
"Century 12" fails
"Century 10" Works
"Century 11" Works

**Comment by conseilgouz** [comment]
Hi,

Could not reproduce this issue.

Did you try to clear index then index again ?

If you check in smart search component, do you see your article with its title ?

**Comment by lairdf** [comment]
I have re-indexed a few times.  For me, it's not only reproducible, but it happens every time.  In my example, the article IS found if I search for "century", so I'm sure the article is indexed in the search index.  But searching for "century 21" fails.  I can even create a new article with a 21 ("foo 21") at the end of the title, and CAN find it with "foo", but not when searching for "foo 21".

**Comment by lairdf** [comment]
So, please put a hold on this.  I think the issue may in fact be on my side.   The same search behaviour (not finding a 21) does NOT occur on my Dev or Testing environments, only my live/production site.  

I'm going to close this issue, to not waste your time.
