### ISSUE TITLE
[4.0] Cache call() method supposed to be deprecated?

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#24951]
### Steps to reproduce the issue

The `call()` method inside the Cache Callback Contrroller is marked as deprecated:
https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Cache/Controller/CallbackController.php#L37

However appear to have been removed in Joomla 4

Therefore using `Factory::getCache()->call([xxx, xxx]);`

will throw an error

**Comment by SharkyKZ** [comment]
Yes, it's marked to be removed in 4.0 and was removed in 4.0.

See https://github.com/joomla/joomla-cms/issues/24703.

**Comment by C-Lodder** [comment]
Does the deprecated notice not mean it _will_ be deprecated in 4.0?

**Comment by mbabker** [comment]
The generally accepted practice for a `@deprecated` annotation is the version will be the first version the element may be removed in.  So something `@deprecated 4.0` means it may be removed in 4.0.  It doesn't mean "as of 4.0 this element is deprecated and will be removed at the next major version".

**Comment by C-Lodder** [comment]
Ah fair enough. Thanks for clarifying
