### ISSUE TITLE
Readmore redirect incorrect

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#24962]
### Steps to reproduce the issue
Create an Article with readmore
Set Access registered

Create Category blog for category the Article is in
Set the blog to Show Unauthorised
Visit the front end not logged in
Click the readmore link

### Expected result
You are redirected to the login page

### Actual result
You reach a page that tells you that you are unauthorised

### Additional comments
This issue was fixed in J2.5.x https://developer.joomla.org/joomlacode-archive/issue-30284.html but has reintroduced since

**Comment by ghost** [comment]
please "System information (as much as possible)"

**Comment by Webdongle** [comment]
On all systems afaik.  But we will know that if others test on their systems.
Here is the sys info where I tested it

PHP Built On | Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
-- | --
Database Type | mysql
Database Version | 5.5.60-0+deb7u1-log
Database Collation | latin1_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.5
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.9.6 Stable [ Amani ] 7-May-2019 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by mbabker** [comment]
> This issue was fixed in J2.5.x https://developer.joomla.org/joomlacode-archive/issue-30284.html but has reintroduced since

For reference, that issue was closed without a commit.  https://github.com/joomla/joomla-cms/pull/1215 and https://github.com/joomla/joomla-cms/pull/1216 were the pull requests with relevant updates for that issue.  It was also noted that particular fix was only needed for 2.5 and that 3.1 at the time wasn't impacted by that issue.  And for completeness, neither of those changes would actually apply on the current 3.9 code because the layouts don't `urlencode()` the return links so there's nothing to remove a `urlencode()` call from.

**Comment by Webdongle** [comment]
OK so the bug wasnt fixed in 2.5 but was not present in 3.1.  But is now present in 3.6.9. although the code is different.
Who else has tested to confirm it ?
Will it be fixed ?

That behaviour was considered a bug then (so by the same) surely it is a bug now?

**Comment by mbabker** [comment]
No idea what the state of that code/feature is.  Just wanted to clarify the status of the issue you linked so nobody spent time trying to do a `git blame` to figure out what changed after that issue.

I don't think whatever issue you're seeing is actually related to that old JoomlaCode issue at all.  The fix for that issue applied only to the 2.5 code base and the same suggested fix is not applicable to 3.9 at all.  So while the issue descriptions might be similar, that's about where the similarities end.  Not saying there isn't a bug, I'm only saying that you shouldn't put too much value in that old issue or anything related to it.

**Comment by Webdongle** [comment]
Woods ... Trees
My point of adding that link was not for the code it contained but to ratify that the issue was (at one time) considered a bug.  Thus the fact that clicking the readmore link (when the user is not permitted to see the Article) needs to redirect to login/register.

Can someone please follow the test instructions and con firm (or deny) the bug exists.  Then perhaps someone might fix it.

**Comment by brianteeman** [comment]
I use the readmore feature on a very popular site exactly in the way that you describe and it works perfectly. Just to be 100% certain I also tested with protostar as well as the custom site template

**Comment by mbabker** [comment]
`*sigh*`

It was not my intent to say it's working as expected or confirm a bug or tell someone to close the issue or anything like that.  When I see someone file an issue with a reference to another past issue, generally that signals to me that either there is a regression from the past issue or an incomplete fix.  And after spending 10 minutes reading that issue and the references I could find, it became clear to me that whatever problem you're having that caused you to file this bug report is not related to the issue you linked.  And that's all I wanted to say on the topic, to keep others from trying to do the same.

For a lot of people, cross-linking issues generally means they're related in some form, and in this case they aren't beyond at one point in the past someone saying a similar behavior was considered a bug and having a similar set of symptoms.

**Comment by Webdongle** [comment]
@mbabker  thanks for that

@brianteeman thanks for the feedback am checking now to see why I get different results.

**Comment by Webdongle** [comment]
With Articles >>> options >>> Show Unauthorised Links no and blog menu item Show Unauthorised Links yes.  I get the unauthorised when clicking the readmore

With Articles >>> options >>> Show Unauthorised Links yes and blog menu item Show Unauthorised Links use global.  I get the page with the intro text and readmore.  Clicking that readmore link just refreshes the page showing the intro text.

Same result with legacy and modern routing.

**Comment by brianteeman** [comment]
The settings on my site that works perfectly and I believe are the same as your failing test are

### Article Options
![image](https://user-images.githubusercontent.com/1296369/58044028-ab115100-7b36-11e9-9975-504ab2d57959.png)

### Menu 
![image](https://user-images.githubusercontent.com/1296369/58043977-8e751900-7b36-11e9-84ee-718805cb0c5e.png)

**Comment by Webdongle** [comment]
Yes that works. At least the readmore leads to the page showing the intro text.  But that page has a readmore not 'login to readmore' link.  But the following doesn't
Article options
![unauthorised 01](https://user-images.githubusercontent.com/1115202/58049438-c5522b80-7b44-11e9-8cac-ed67fad1c23d.JPG)
Article Registered
![unauthorised 03](https://user-images.githubusercontent.com/1115202/58049730-75279900-7b45-11e9-97d4-311efc0f2894.JPG)
Blog menu item
![unauthorised 02](https://user-images.githubusercontent.com/1115202/58049472-dbf88280-7b44-11e9-9d9e-cc399c341f48.JPG)
Them read more leads to a page showing
![unauthorised 04](https://user-images.githubusercontent.com/1115202/58049939-f5e69500-7b45-11e9-948a-cdc7a568a06a.JPG)

With Global No and blog menu item Yes ... then **the Article setting is overriding the menu item setting.  It should not (only meta data in the Article settings should override the menu item).**

Also the article used to show 'login to readmore' not 'read more'.  The visitor would click it and the login page would be displayed (or their profile page if they were logged in with a user that did not have access to the level set in the Article.

**Comment by brianteeman** [comment]
Don't know what to say. It works perfectly for me

**Comment by Webdongle** [comment]
Because you have global Yes.  When Global is No ... then Article setting 'Use global (No)' overrides the menu setting.  Set Articles >>> Options (not Articles >>> your Articles name ... options) to No for show authorised.  Then the blog menu item setting 'Yes' is not honoured ... it is overwritten by the Article  'Use global (No)'.  The article setting should not override the blog menu item setting.

**Comment by brianteeman** [comment]
I can not confirm that either

### Menu
![image](https://user-images.githubusercontent.com/1296369/58054819-b757d700-7b53-11e9-899a-d94c52852ac9.png)

### Article
![image](https://user-images.githubusercontent.com/1296369/58054837-c8a0e380-7b53-11e9-8adf-218e61002ed0.png)

### Login to read more
![image](https://user-images.githubusercontent.com/1296369/58054865-e2422b00-7b53-11e9-866b-4564fb4ceaa9.png)

### Login
![image](https://user-images.githubusercontent.com/1296369/58054876-eb32fc80-7b53-11e9-889b-2517cccd91c8.png)

**Comment by ghost** [comment]
@Webdongle can you please ask further on [Forum](https://forum.joomla.org/), clsoing for this Reason.
