### ISSUE TITLE
Repeatable Subforms IE Bug

### ISSUE THREAD

**Issue by okonomiyaki3000** [joomla/joomla-cms#24969]
### Steps to reproduce the issue
Open any form containing a repeatable subform with IE. 

### Expected result
Repeatable subform can add or remove rows on demand. Doesn't do so automatically.

### Actual result
A row will always be added automatically because IE does not support the `<template>` tag and those contents will be treated like regular html.

### System information (as much as possible)
IE. This happens with IE because no version of it supports `<template>`

**Comment by ghost** [comment]
J3?

**Comment by okonomiyaki3000** [comment]
Yes. 3.9

**Comment by okonomiyaki3000** [comment]
It seems it happened here: f2a9874944c9776b2c6a9ccf4df2ae7b7ccb4875

**Comment by SharkyKZ** [comment]
There's this PR #24947 but it has conflicts since #24919 was merged.

**Comment by alikon** [comment]
as we have a pr #24947 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24969">issues.joomla.org/tracker/joomla-cms/24969</a>.</sub>
