### ISSUE TITLE
Turning on debug then trying to upload an image to an article says JSON error

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#24964]
### Steps to reproduce the issue
Turn on Debug in Global Configuration.
Click on an article.
Try to upload an image.

### Expected result
See files and folders of images you can use in your article.

### Actual result
"The server returned an invalid JSON response."

### System information (as much as possible)
=============
System Information
=============
php: Linux squareballoon.gds.guru.net.uk 3.10.0-714.10.2.lve1.5.19.3.el7.x86_64 #1 SMP Tue Aug 7 21:33:29 EDT 2018 x86_64
dbserver: mysql
dbversion: 5.7.26
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 7.2.18
server: LiteSpeed
sapi_name: litespeed
version: Joomla! 3.9.6 Stable [ Amani ] 7-May-2019 15:00 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0

### Additional comments
Turning off debug works as usual
Browsing the media manager works as usual even with debug on

**Comment by Quy** [comment]
Unable to replicate the error. Tested on cloudaccess.host with j3.9.6.

**Comment by brianteeman** [comment]
I assume from your other post that this is also using JCE and is nothing to do with core Joomla

**Comment by alikon** [comment]
not from core<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24964">issues.joomla.org/tracker/joomla-cms/24964</a>.</sub>
