### ISSUE TITLE
[4.0] Workflows affecting publish date

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#24972]
While testing #24968 I saw that a publish_up date doesn't always get created.

The behaviour now in Joomla 4 is that if you create a new article it has a default status of unpublished and it is created with a null date for publish_up

If you go back to edit the article and change the status to publish and then save and you get a publish_up of now()

BUT If you change the status from the list view then you do not get a publish_up date at all

**Comment by richard67** [comment]
It seems setting the publish date to now() when publishing an article is not the only thing which works well in the article edit view but doesn't work in the list view, see issue #24878 .

**Comment by brianteeman** [comment]
Closing this as it appears to no longer be an issue with wfv3 #29235
