### ISSUE TITLE
Rips has died

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#24988]
@zero-24 @SniperSister It would be great if you could take a look at rips as it is currently failing on all pr as it is unable to connect to the api

**Comment by zero-24** [comment]
We are working on it will let you know when we are ready. thanks for reporting. cc @SniperSister

**Comment by brianteeman** [comment]
Thanks - if possible could you restart it on all the failing pr from today

**Comment by zero-24** [comment]
Will try that when possible. Thanks.

**Comment by SniperSister** [comment]
RIPS is back again!

**Comment by SniperSister** [comment]
Fixed!

**Comment by zero-24** [comment]
Latest jobs has been rebooted please feel free to ping me on any missing one.

**Comment by zero-24** [comment]
It might took some time to process them for sure.

**Comment by brianteeman** [comment]
i think it is every pr #24974 on that needs restarting

**Comment by zero-24** [comment]
restartet: https://ci.joomla.org/joomla/joomla-cms/18602 but it will take some time atm we have 23 builds in the queue ;)

**Comment by brianteeman** [comment]
Thank you

**Comment by brianteeman** [comment]
Sorry something is still not right

**Comment by zero-24** [comment]
any details? Please let us know what is not right ;) It it difficult to debug "something" or do you mean there are reports like this: https://ci.joomla.org/joomla/joomla-cms/18629/1/19 ? Are all branches up-to-date?

**Comment by zero-24** [comment]
I have just resolved some false positives but this is the only issue i can see right now?

**Comment by brianteeman** [comment]
I think so - i will recheck again soon.  Do we need to ping you when rips fails or not?

**Comment by brianteeman** [comment]
It looks like all the ones of mine that are failing now are due to 4(?) false positives

**Comment by zero-24** [comment]
> Do we need to ping you when rips fails or not?

Yes please tag me on all issues. Please only first check that the branch is up-to-date when rips errors than tag me.

> It looks like all the ones of mine that are failing now are due to 4(?) false positives

Yes they are all the same false positives that I have fixed / reviewed now on a new check they should work.

As the actual issue is solved I'm going to close here again. :)
