### ISSUE TITLE
Getting fields for a table in another schema

### ISSUE THREAD

**Issue by softarius** [joomla/joomla-cms#24998]
[0004-getTableColumns-for-another-schema.txt](https://issues.joomla.org/uploads/1/7281e7ba37eb3836a10c1d0c665b7246.txt)

### Steps to reproduce the issue

- install Joomla with PostgreSQl driver.
- create a new schema (for example 'test')
- create a new table in this schema

```
CREATE TABLE test.customer (
  id SERIAL,
  name VARCHAR(100),
  PRIMARY KEY(id)
) 
WITH (oids = false);
```
- in code call getTableColumns for this table

```
$db = JFactory::getDBO();
$custfields=$db->getTableColumns('test.customer'); 
```
### Expected result
Array with fields of table

### Actual result
Empty array

### System information (as much as possible)

PostgreSQL Joomla driver using (important!)
Any operation system (Windows or Linux for me)
Joomla 3.9.6 (or staging)
PostgreSQL 10 (or other)

### Additional comments
A fixed this bag (see attached patch)

**Comment by ghost** [comment]
Please "System information (as much as possible)"

**Comment by softarius** [comment]
## System information (as much as possible)

- PostgreSQL Joomla driver using (important!)
- Any operation system (Windows or Linux for me)
- Joomla 3.9.6 (or staging)
- PostgreSQL 10 (or other)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24998">issues.joomla.org/tracker/joomla-cms/24998</a>.</sub>

**Comment by alikon** [comment]
you have already the solution so then
please submit a pr is  easy: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by softarius** [comment]
Yes. Done. 
PR #24999<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24998">issues.joomla.org/tracker/joomla-cms/24998</a>.</sub>

**Comment by richard67** [comment]
Then you can close this issue because there is a PR.

**Comment by alikon** [comment]
closing as we have a pr for testing #24999<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24998">issues.joomla.org/tracker/joomla-cms/24998</a>.</sub>
