### ISSUE TITLE
[4.0] Important Plugin/Event missing

### ISSUE THREAD

**Issue by arbindbhagat** [joomla/joomla-cms#25009]
When a not-logged-in user tries to access a content that is only for logged-in-users, that user is redirected to the login page.

We want to develop a plugin that does some important thing when this happens. However, on https://docs.joomla.org/Special:MyLanguage/Plugin/Events page, I don't see any event that would get triggered in this case of redirection-to-login-page.

Joomla must have an event that does this. Please consider to add this very basic-and-important feature.

**Comment by ghost** [comment]
can you please give "System information (as much as possible)"

**Comment by arbindbhagat** [comment]
It is a feature that Joomla is missing. So, basically, it is a feature request. So, the system information won't help in this case.

**Comment by ReLater** [comment]
> When a not-logged-in user tries to access a content that is only for logged-in-users, that user is redirected to the login page.

When I try as a not-logged-in user to access  a content that is only for logged-in-users I'm not redirected but see a message:

```
Error
You are not authorised to view this resource.
```

Please provide some more detailed testing instructions how to build your scenario.

If $app->redirect participates (i don't know) events onBeforeRespond and onAfterRespond are triggered.
https://github.com/joomla/joomla-cms/pull/20677

**Comment by alikon** [comment]
Closing this due to not receiving required information to determine if this is a bug or not. If you feel this still needs review, please open a new tracker entry with as much information as possible to ensure it can be reviewed properly
