### ISSUE TITLE
[4.0] Impossible to access control panel

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25008]
If you are a manager and try to access the admin then you land on the "control panel" but as soon as you click on any link there is no way to get back to the "control panel"

**Comment by ghost** [comment]
J4?

**Comment by brianteeman** [comment]
Yes. Sorry the screenshot is missing

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/58384774-f2d42480-7fdd-11e9-851a-dbcc5dc13d81.png)

**Comment by infograf768** [comment]
PR https://github.com/joomla/joomla-cms/pull/25012
closing as we have a patch

**Comment by brianteeman** [comment]
Thanks
