### ISSUE TITLE
[4.0] Bug after update alpha9-dev to alpha10-dev

### ISSUE THREAD

**Issue by diddipoeler** [joomla/joomla-cms#25000]
### Steps to reproduce the issue
update from 9 to 10

### Expected result

An error has occurred.
0 Class 'Joomla\Plugin\Quickicon\Joomlaupdate\Extension\Joomlaupdate' not found

**Comment by simbus82** [comment]
I have the same problem, after a DB Fix too.

**Comment by brianteeman** [comment]
Delete the autoloader file in the libraries folder and then refresh

**Comment by Quy** [comment]
Duplicate #24907<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25000">issues.joomla.org/tracker/joomla-cms/25000</a>.</sub>
