### ISSUE TITLE
JHtml::_('calendar'... doesn't Support attribute Pattern

### ISSUE THREAD

**Issue by thuebschmann** [joomla/joomla-cms#25016]
### Steps to reproduce the issue
platce the folling cate in Templace

&lt;?php
$attrib = array ("class"=>"cal");

$attrib['placeholder']='tt.mm.jjjj';
$attrib['pattern']='\d{2}\.\d{2}\.\d{4}';
echo JHtml::_('calendar', time(), 'test', 'test','%d.%m.%Y', $attrib);
?>

### Expected result
<pre>
&lt;input type="text" id="test" name="test" value="" class="cal" pattern="\d{2}\.\d{2}\.\d{4}\" placeholder="tt.mm.jjjj" data-alt-value="" autocomplete="off">
</pre>
### Actual result

<pre>
&lt;input type="text" id="test" name="test" value="" class="cal" placeholder="tt.mm.jjjj" data-alt-value="" autocomplete="off">
</pre>

### System information (as much as possible)

[systeminfo-2019-05-27T11_52_29+02_00.txt](https://issues.joomla.org/uploads/1/9996beaee541d7f70339f653125bdbe5.txt)

**Comment by ghost** [comment]
please add System Information in comment.

**Comment by Bakual** [comment]
Does that even make much sense in a localised enviroment?
Imho it would only work in your own extension which you run on a site where only one language is installed. As soon as you have a distributed extension, you don't know in which language it will be used and the pattern may be different.

**Comment by thuebschmann** [comment]
here are the system information
[systeminfo-2019-05-27T11_52_29+02_00.txt](https://github.com/joomla/joomla-cms/files/3223690/systeminfo-2019-05-27T11_52_29%2B02_00.txt)

**Comment by ghost** [comment]
@thuebschmann its about copy the System Information in the opening Comment so Volunteers don't have to download them.

**Comment by ghost** [comment]
Guess its for J3 so adding the Label.

**Comment by brianteeman** [comment]
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed. 

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
