### ISSUE TITLE
[4.0] Class 'JRequest' not found 

### ISSUE THREAD

**Issue by thatgrrl** [joomla/joomla-cms#25019]
I installed the new Joomla alpha, fresh from the source just now. I thought I would have a look at what's new. My site runs on the protostar template and not many extensions added. But, I can not get past the login screen due to an error. 

Class 'JRequest' not found

With a note in red about the template - 

Error
The template for this display is not available.

I'm going back to Joomla3, my backup files. I won't be available to try this or that to fix the error. I'm just new to Joomla and still working on the CSS files to try make the text editor screen readable for low vision. That's enough tinkering for me. ![screen shot 2019-05-27 at 15 16 52](https://issues.joomla.org/uploads/1/290f52ea8939da3f5dc5d7da4aa144f0.png)

**Comment by SharkyKZ** [comment]
>not many extensions added

One or more of your extensions is using `JRequest` class which doesn't exist in 4.0. Enable debug by setting `$debug` to `true` in `configuration.php` file. You'll see where this is coming from.

**Comment by ghost** [comment]
closed as no Core Issue.

**Comment by HLeithner** [comment]
@thatgrrl please contact the author of the extension if you could find the extension as mention by SharkyKZ. The API used is deprecated since Joomla 1.7
