### ISSUE TITLE
Custom.css not loading in chrome

### ISSUE THREAD

**Issue by Ribberholt** [joomla/joomla-cms#25026]
### Steps to reproduce the issue
Open the page in chrome

### Expected result
every custom.css edit to function

### Actual result
no custom css function

### System information (as much as possible)
Template: Purity III from Joomlart
Joomla version: Latest

### Additional comments
I found this thread: https://github.com/joomla/joomla-cms/issues/14220
Which adress my issue to a toe. How ever it was closed so I'm opening a new one. My issue is the same. Purity III and other joomlart templates run with a Custom.css option which should work to override any Css on the site. In Firefox it works fine, but in chrome and Edge the stylesheet is not loading properly. What do I do?

**Comment by brianteeman** [comment]
If part of a a joomlart template doesnt work then you should contact Joomlart for support

**Comment by ghost** [comment]
closed as no core issue.
