### ISSUE TITLE
[4.0] Feature Idea: Showon for filling Custom Fields

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-cms#25027]
This is an idea I had for a while.
The ability to show the input form of a custom field based on the value of another custom field in the same input form.

For example, say you have a category of "Sports".

You have a custom field of type "List" called "Sport Type" that can be: football, basket, tennis, swimming, water-polo, etc...

You have a custom field of type "Text" called "Pool size". You want this custom field only show up for being filled in only if the sport type is an aquatic sport.

So when creating the custom field "Pool size", in the field options you could have something like:

![image](https://user-images.githubusercontent.com/25923699/58470224-7f4b2800-8141-11e9-805b-dcf6420bebe3.png)

You could add up to 3 showon conditions.

Then when editing an article inside the "Sports" category, the ability to enter a value for the "Pool size" field would only show up if you previously set the "Sport Type" to either "swimming" or "water-polo" as the other custom field value.

![image](https://user-images.githubusercontent.com/25923699/58472369-68f39b00-8146-11e9-9daa-23a8e9c30116.png)

If the sport is set to "Football" for example, the "Pool size" field input would be collapsed.

![image](https://user-images.githubusercontent.com/25923699/58472407-790b7a80-8146-11e9-9090-8763f0119c64.png)

This is just an example. But I'm sure you get the purpose of the showon thingy.

**Comment by frogydiak** [comment]
I second this feature also. I wish it will be added to the next J4 version.

**Comment by brianteeman** [comment]
This hasd been implemented https://github.com/joomla/joomla-cms/pull/39051

**Comment by AndySDH** [comment]
Awesome! 4 years in the making, glad it made it in!
