### ISSUE TITLE
[4.0] Workflow status change

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25020]
If you click on the status icon in order to change the status it changes to a select box and if you select a new status then the page is saved etc

However if you decide that you dont want to change the status after all there is no way to "close" the select box. I would have expected that clicking anywhere other than in the select box would close the select and return to the icon

**Comment by wilsonge** [comment]
If you click elsewhere presumably that would make this not accessible - we'd need some sort of escape action and maybe trapped focus?

**Comment by brianteeman** [comment]
Not really sure. It should work the same as a drop-down select. I think

**Comment by brianteeman** [comment]
The specification for a list is here https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html

From what I can tell there are two issues that perhaps have the same fix

A select list should change the value immediately (it does) and then you press enter to confirm (it does) and that technically you can not undo a change so there is no escape to close.

However the issue is that you can not "select" the existing value. If you could then the issue would probably be resolved. However there might be consequences to someones workflow as it might trigger an event?

**Comment by brianteeman** [comment]
@wilsonge I think it might be able to be fixed in a much easier way. Currently the select is built using ContentHelper::filterTransitions

If that is changed so that the list is not filtered then it should work. (I don't know how but I am sure you do)

**Comment by brianteeman** [comment]
Still an issue with the new workflows

There is no way to click away from the opened list to close it. I am guessing there needs to be some js for this
```

// eventListener to select item
on click inside the list
select item and close the list
```

```
// eventListener to close the div
on click outside the list
close the list
```

**Comment by HLeithner** [comment]
@bembelimen can you have a look at this?

**Comment by bembelimen** [comment]
Any reason why a close button would not work?

```[select][x]```

**Comment by brianteeman** [comment]
no - that would be fine although might be a bit ugly
