### ISSUE TITLE
[4.0] Backend - Extensions: Update - remove urls -> text-links, to make the view clearer

### ISSUE THREAD

**Issue by hgh-esn** [joomla/joomla-cms#25021]
### Steps to reproduce the issue

Going into the backends "System>Update>Extensions"

### Expected result
To make the page and the listing clearer, it would be much more effective, the url's were not displayed as plain text. For the first one it is better to set a text-link who shows a modal-popup with the link-data. The second url should be displayed as an external text-link .

<img width="957" alt="2019-05-28_13h50_21" src="https://user-images.githubusercontent.com/5299726/58476811-35b70900-8152-11e9-8182-d231303931c7.png">

### Actual result

The listview with one or more lines is displayed, if updates are available. At the right of each line, there are two big url-strings displayed.
<img width="949" alt="2019-05-27_18h21_03" src="https://user-images.githubusercontent.com/5299726/58431263-45304680-80ad-11e9-849a-a1f11e6195eb.png">
These url-strings increase the space requirement on the page enormously and make the view very confusing. 

### System information (as much as possible)

J4-alpha-dev-9/10

### Additional comments

The text-links can be freely defined.
My suggestions:
==========
**UpdateServer - InfoURL**  
**Documentation**

I can make the necessary changes if desired.

**Comment by hgh-esn** [comment]
Need help !!!!

I'm totally confused.
How can I push this changes from the forked repo ????

**Comment by brianteeman** [comment]
It was a deliberate decision to display the url and not "hide" it behind a "text link" so that the user can see what the url is before clicking it

Instead of using a modal just have a div that is displayed on "hover", "active" like the search box and see #24899 for an example

**Comment by brianteeman** [comment]
> How can I push this changes from the forked repo ????

In your forked repo make sure that you create a new branch and make your changes there. 
Then if you come to this repo you will see a message similar to this

![image](https://user-images.githubusercontent.com/1296369/58517396-24e2b380-81a3-11e9-9f6b-4036ae8bfbfc.png)

Click on the button "compare and pull request"

On the next page change the base from staging to 4.0-dev and complete the details 

![image](https://user-images.githubusercontent.com/1296369/58517448-59ef0600-81a3-11e9-941c-4ccfa0434208.png)

**Comment by brianteeman** [comment]
PS you need to remove those changes from your 4.0dev branch because they just appeared in your other PR.

Golden rule to remember - 1 branch = 1 pr

**Comment by hgh-esn** [comment]
@brianteeman 
> It was a deliberate decision to display the url and not "hide" it behind a "text link" so that the user can see what the url is before clicking it
> 
> Instead of using a modal just have a div that is displayed on "hover", "active" like the search box and see #24899 for an example

In the case of the update-view, a hoovered div is - I think- suboptimal - why?  
1. In a hoovered div, the user can't scratch the url into the clipboard for further operations.
In the modal it continues to be possible as in the original view.

2. The hoovered div may be cut on top, because of other languages than en-GB. See this "de-DE" screenshot - here the upper informations are being "cut off".
<img width="959" alt="2019-05-30_07h12_57" src="https://user-images.githubusercontent.com/5299726/58615791-41264380-82bc-11e9-946e-3142e16d99a6.png">

This is the "en-GB" screenshot: 
<img width="957" alt="2019-05-30_07h13_58" src="https://user-images.githubusercontent.com/5299726/58615856-631fc600-82bc-11e9-832a-9d416b42d6e3.png">

So for me the modal is the better solution at that place.

**Comment by hgh-esn** [comment]
@roland-d  @infograf768  @richard67 @ReLater  

Should I go into code-changing to get this solution?
What's your opinion about that?

**Comment by ReLater** [comment]
Just because you pinged me: Here's my personal opinion:
1) I hate "hovers" and would prefer the popup in this case. The only practicable way to copy a link.
but also
2) I hate unnecessary clicks and would leave it as it is now in current Joomla backend. Both URLs always visible.
but also
3) I don't have to decide that

**Comment by richard67** [comment]
@hgh-esn 

> Should I go into code-changing to get this solution?
> What's your opinion about that?

I would say: No, leave it as it is. But that's just my personal opinion, I don't have to decide that.

**Comment by infograf768** [comment]
agree with leaving it as is.

**Comment by roland-d** [comment]
Leave it as it is. The URLs are also long because you have a long URL :grin: Your URL has three subfolders.
