### ISSUE TITLE
Quickicons error after update to Joomla! 4.0.0-alpha10-dev

### ISSUE THREAD

**Issue by crimle** [joomla/joomla-cms#25036]
### Steps to reproduce the issue
Goto Components > Joomla! Update > Options
Set Update Channel = Custom URL
Set Custom URL = https://update.joomla.org/core/nightlies/next_major_list.xml
Start and confirm the update process
After the update is accomplished click the [ControlPanel] button

### Expected result
The ControlPanel is displayed without error message

### Actual result
The ControlPanel is displayed with the following error message

An error has occurred.
0 Class 'Joomla\Plugin\Quickicon\Joomlaupdate\Extension\Joomlaupdate' not found 
Return to ControlPanel

Click [Return to ControlPanel] but the error message persits. You will not get to the ControlPanel any more.

### System information (as much as possible)
Update was performed from Joomla! 4.0.0-alpha8-dev to Joomla! 4.0.0-alpha10-dev
PHP Version 7.3.4

**Comment by brianteeman** [comment]
Updates when in alpha are not really supported. This is a known issue and can be fixed by deleting this file \libraries\autoload_psr4.php
It will then be automagically regenerated and your site will work

**Comment by ghost** [comment]
closed for Reason stated above.
