### ISSUE TITLE
[4.0] Class 'Joomla\Component\Finder\Administrator\Indexer\FinderHelperRoute' not found

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#25031]
### Steps to reproduce the issue
Add `Smart Search` module.
Perform search on front end.

### Actual result
> Class 'Joomla\Component\Finder\Administrator\Indexer\FinderHelperRoute' not found

### System information (as much as possible)
> JROOT\administrator\components\com_finder\Indexer\Query.php:364

**Comment by alikon** [comment]
please test  #25040<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25031">issues.joomla.org/tracker/joomla-cms/25031</a>.</sub>
