### ISSUE TITLE
[4.0] Form cannot be submitted for Article save

### ISSUE THREAD

**Issue by neiljames** [joomla/joomla-cms#25039]
### Steps to reproduce the issue
Click save to save changes made to an article

### Expected result
Article saved

### Actual result
When save button clicked  a popup tells me "Error, form cannot be submitted as its missing required data. Please correct marked field and try again".
Category* one of the options must be selected.
However the category selection box has no categories available to choose from (there are categories set up), the only way to move on is to reload the page which takes me back to the previous successful save.

### System information (as much as possible)
Localhost
Joomla! 4.0.0-alpha9
PHP 7.2.14

Using JCE editor
### Additional comments
Just started to happen today for no apparent reason, I was editing an article by setting up bootstrap responsive grid column sizes for breakpoints

**Comment by Quy** [comment]
Cannot reproduce. Please test the nightly build: https://developer.joomla.org/nightly-builds.html

**Comment by ghost** [comment]
closed for REason stated above and due the lack of response.
