### ISSUE TITLE
Administration or Super User, User Activation on Frontend Broken

### ISSUE THREAD

**Issue by visualtribe** [joomla/joomla-cms#25033]
### Steps to reproduce the issue
Receive user activation email
Click on link
link takes me to a login on the public side
login
taken to home page and told "You are not authorised to view this resource." yet I am a super user which can see everything. It also doesn't work for Administrator level.
Yet it logs me in and secured pages can be seen. If I click the link again takes me to the home page and gives me the same error.

### Expected result
Like it was before click on link, user activated

or

login on front end and told that user is now activated

### Actual result
sent to home page and told the above

### System information (as much as possible)

Joomla 3.9.6
PHP 7.2
FireFox for Mac

### Additional comments
Ever since you changed the ACL where you can't be logged in as Super User and also logged in on the front end, this ACL hasn't worked.

**Comment by visualtribe** [comment]
It might be just this site for some reason. My other sites seem to work. I build my Joomla sites all the same and with the same components. For some reason it won't pass to the complete page. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25033">issues.joomla.org/tracker/joomla-cms/25033</a>.</sub>

**Comment by ghost** [comment]
> It might be just this site for some reason. My other sites seem to work.

Please ask on [Forum](https://forum.joomla.org/)

**Comment by visualtribe** [comment]
Question

When you tested your setup was your login link set to Public or Guest? I fixed my issue by setting the login link from Guest to Public and everything worked. I found that solution from a Stackoverflow post. However, the login link should work with Guest.

**Comment by ReLater** [comment]
The most common workaround is to assign the user `Guest` group in `Super User` profiles, too. Then you don't have to change the settings of the login link.
Not a perfect solution but normally acceptable.

**Comment by visualtribe** [comment]
I was using superuser and it still gave me the error and wouldn't let me activate anyone until I made it Public.

**Comment by ReLater** [comment]
Just to clarify that you didn't misunderstand my comment:

![grafik](https://user-images.githubusercontent.com/20780646/58876334-0f531980-86ce-11e9-9cd8-63d97440cd53.png)

As additional group beside group "Super Users".

**Comment by visualtribe** [comment]
Understood, but should superuser not already be tied to Guest by default rather than adding them to guest? If I have to do this then that precludes there is something wrong with the coding that is interfering with superuser belonging to guest or really any group. Any group should be able to see guest by default. Yes?

**Comment by ReLater** [comment]
Any logged in user normally doesn't see what is set to Guest. Guest is similiar to Public (no registration, no rights) but gives you the possibility to hide modules, menu items etc. that are only for NOT logged in users. Logged in users don't see them.

> but should superuser not already be tied to Guest

That's somehow open to interpretation. Following the above logic, no. But yes, your issue came up a little bit unexpected with Joomla 3.9.iDontKnow
