### ISSUE TITLE
Modern URL Routing 

### ISSUE THREAD

**Issue by Ferriero** [joomla/joomla-cms#25063]
### Steps to reproduce the issue

Hi everyone

I activated the modern URL Routing and set Remove ID from the URLs to yes.

Since I made the links obtained with "Link article" no longer work if the article is not part of the same category.

In addition to manually changing the links (which I would like to avoid) what can I do?

Here's where to find the links:
Links that do not work: open "Da visitare" on this page https://www.nelbelsalento.it/paesi/lecce
Link that works: https://www.nelbelsalento.it/scopri-il-salento/da-visitare/piazza-duomo-lecce

Thanks!

**Comment by ghost** [comment]
Please ask on [Forum](https://forum.joomla.org/)
