### ISSUE TITLE
[4.0] Custom fields warning

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25066]
### Steps to reproduce the issue
Create a new custom field for content

### Expected result
Form with no errors

### Actual result
The following warning at the top of the page

`Warning: Declaration of PlgFieldsRepeatable::onCustomFieldsPrepareDom($field, DOMElement $parent, JForm $form) should be compatible with Joomla\Component\Fields\Administrator\Plugin\FieldsPlugin::onCustomFieldsPrepareDom($field, DOMElement $parent, Joomla\CMS\Form\Form $form) in C:\htdocs\joomla-cms\plugins\fields\repeatable\repeatable.php on line 76`

**Comment by SharkyKZ** [comment]
Test PR #25067 please.
