### ISSUE TITLE
[4.0]  Backend: Extensions-Update-View: Warning-message is quite annoying

### ISSUE THREAD

**Issue by hgh-esn** [joomla/joomla-cms#25061]
### Steps to reproduce the issue

Go into system>update>extensions. See what's coming up.

### Actual result 

When calling / reloading, etc.  the extensions-update view,  the constantly popping up warning message is quite annoying, especially since it must first be closed to get to all the buttons.
<img width="954" alt="2019-05-30_08h46_25" src="https://user-images.githubusercontent.com/5299726/58614784-b2b0c280-82b9-11e9-86ba-424a74fbf07c.png">

### Expected result

In this case, the insertion of the warning text in the upper view area (as it was solved in J3) would be the much better solution.
<img width="937" alt="2019-05-30_09h05_30" src="https://user-images.githubusercontent.com/5299726/58614963-20f58500-82ba-11e9-89de-d3a4fd588918.png">

in J4 it might also be a solution, to put this Information into the unused area left to the search-field as a hardcoded test..

### System information (as much as possible)

J4-alpha-9/10-dev

**Comment by ReLater** [comment]
That's a known issue and as far as I know that's already under consideration.

And yes, I hope too, that these messages will go away as popups in J4. Back to ISIS style....

**Comment by ghost** [comment]
closed as known issue.

**Comment by hgh-esn** [comment]
And what is the known issue?

**Comment by SharkyKZ** [comment]
Related issues #21803,  #16497, #13907.

**Comment by ReLater** [comment]
And just partially related: https://github.com/joomla/joomla-cms/issues/23425
