### ISSUE TITLE
Published, but is Pending

### ISSUE THREAD

**Issue by Barbara0000** [joomla/joomla-cms#25073]
### Steps to reproduce the issue
I want to add an article in one of my pages, on the english language. Every time when I am adding new articles, at 1/3 pages I get a problem where my article is not published.
I do exactly the SAME things in all 3 languages, but from some reason, I always get this mistake (not always in the same site, so each time differently).
Then, sometimes I do again, the SAME thing, and the article is published. 

Right now, I again have an article on my Italian site, which is in status: Published, but it is pending. I tried to do 2,3 times from beginning, but still, it is the same.

Can you please provide me with the answer and a solution of this problem, cause right now, this is just frustrating since there is NO difference in the actions I am doing in order to publish the article!

### Expected result
Article that is published.

### Actual result
Article in status: Published, but is Pending

### System information (as much as possible)
I am using Joomla! 2.5.28

**Comment by alikon** [comment]
please ask support on forum https://forum.joomla.org/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25073">issues.joomla.org/tracker/joomla-cms/25073</a>.</sub>

**Comment by HLeithner** [comment]
And you should really upgrade your joomla installation.
