### ISSUE TITLE
PLG_LOADMODULE_XML_DESCRIPTION should mention loadmoduleid

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#25074]
### Steps to reproduce the issue
- Joomla 3
- Go to settings of plugin "Content - Load Modules".
- Read the description.
- `loadmoduleid` alternative is not mentioned.

### Additional comments
https://github.com/joomla/joomla-cms/blob/staging/administrator/language/en-GB/en-GB.plg_content_loadmodule.ini#L14
https://github.com/joomla/joomla-cms/blob/staging/administrator/language/en-GB/en-GB.plg_content_loadmodule.sys.ini#L7

**Comment by Quy** [comment]
Please test PR #25076<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25074">issues.joomla.org/tracker/joomla-cms/25074</a>.</sub>
