### ISSUE TITLE
[4.0] Regression creating fields

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25080]
If a field does not have a params/fieldname.xml with a fieldparams fieldset then you can not save the field

### Steps to reproduce the issue
Try to create a new color field

### Expected result
Field successfully saved

### Actual result
![image](https://user-images.githubusercontent.com/1296369/58748823-b38e5380-8475-11e9-8415-64dddfcfbb38.png)

Save failed with the following error: Field 'fieldparams' doesn't have a default value

### Additional comments
In joomla 3 there was no requirement for fieldparams and you can create a color field without any problem

**Comment by SharkyKZ** [comment]
Test PR #25119 please.
