### ISSUE TITLE
[4.0] Duplicate ID from associations ?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25088]
It is very important that there are no duplicate ID on a page. If you go to a page like administrator/index.php?option=com_tags&view=tag&layout=edit and search the source you will find TWO identical ID of jform_id.

As far as I can tell one is coming from layouts/joomla/edit/global.php and was introduced in #22166 
The other is coming from joomla-cms/layouts/joomla/edit/publishingdata.php

**Comment by brianteeman** [comment]
Basically the ID is included in the publishingdata tab and in the basic settings

**Comment by infograf768** [comment]
I may have a solution. Will create PR to test.

**Comment by infograf768** [comment]
Closing as we have a patch
https://github.com/joomla/joomla-cms/pull/25096

Please test.
