### ISSUE TITLE
Improve UX for error "verification code not found"

### ISSUE THREAD

**Issue by webgras** [joomla/joomla-cms#25099]
### What needs to be fixed
Improve the language string COM_USERS_ACTIVATION_TOKEN_NOT_FOUND
old: Verification code not found. 
new: Verification code not found. Check if your account is already activated and try to log in.

### Why this should be fixed
If a user registers at the website and gets the confirmation email to activate the account, and clicks the confirmation link with the authentication token more then one time, then the error message shows only "verification code not found".
But maybe the account is already activated
- by the user (unintended double click, trying to activate for the second time after a few days, ...)
- by an administrator
- by a virus scanner, that followed the link in the email.

However, the user could already login, but does not know.

### How would you fix it
Add information in the language string

### Side Effects expected
Probably none, or maybe spammers who will get more information than necessary.

**Comment by ghost** [comment]
Guess its for J3.

**Comment by webgras** [comment]
yes, sorry, forgot to mention.

**Comment by Quy** [comment]
Please submit your PR to Joomla repo.

**Comment by webgras** [comment]
> Please submit your PR to Joomla repo.

yes, I will do that.

However, somebody suggested in a glip channel, that in case the activation token is - for example - not copied correctly or with a line break within the email, then the token will not be found. Then the error message is correct. So probably, we should also give information about that.

Shall we add some more information like that?
`"Verification code not found. <br>Check if your account is already activated and try to log in. Check also if the token is copied correctly to the browser address bar."`

**Comment by Quy** [comment]
Go for it. Others can comment once there is a PR to test.

**Comment by ghost** [comment]
Closed as having Pull Request #25107
