### ISSUE TITLE
Tags class empty until edit/save

### ISSUE THREAD

**Issue by recreatinganew** [joomla/joomla-cms#25110]
Create and save a tag during backend article creation.
Tag class is empty.
Open/edit/save/close tag in backend.
Tag class is changed to "label label-info".

I have confirmed this also happened in prior recent versions of Joomla.
Joomla 3.9.6

![image](https://user-images.githubusercontent.com/12423349/58849119-21de3c00-8657-11e9-98c7-43700ad28385.png)

**Comment by SharkyKZ** [comment]
This is an issue with your template. Although class is indeed not saved for tags created on the fly, the default tags layout uses `label label-info` class as fallback:

https://github.com/joomla/joomla-cms/blob/71266bdfb3b3b9f14c23ee32018c4cbaf9596129/layouts/joomla/content/tags.php#L24

Your template has a tags layout override (templates/shaper_helix3/html/layouts/joomla/content/tags.php) which does not use a fallback:

     <?php $link_class = $tagParams->get('tag_link_class'); ?>

**Comment by ghost** [comment]
closed as no core Issue. 
Please ask on [Forum](https://forum.joomla.org/) if further Informationsa are needed.
