### ISSUE TITLE
[4.0] Unused modal in com_fields

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25125]
While working on #23737 I can't see how or where `administrator\components\com_fields\Field\Modal\FieldField.php` is used. Can anyone enlighten me?

**Comment by Quy** [comment]
I assume it is for the Field button in the editor.

![editor-field](https://user-images.githubusercontent.com/368084/59078905-175db580-8896-11e9-8d42-7f4fb8f46ca1.jpg)

**Comment by brianteeman** [comment]
@quy thanks for the answer but I don't think that's it. Deleting the file has no impact on that button or the resulting modal

**Comment by Quy** [comment]
You're right. I think it is safe to delete. In it there are untranslated language strings.

**Comment by infograf768** [comment]
That kind of modal is used when there are associations that can be set when editing an item.
For example `modal_article` for com_content:
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_content/Model/ArticleModel.php#L1107-L1137

1. There is no code to associate fields in the preprocess form of FieldModel
2. I don't even know if it makes sense to associate fields.

ATM, the field type is not used.

**Comment by infograf768** [comment]
As for the Field displaying in the TinyMCE CMS Content dropdown, it depends on the Button - Field editor-xtd and I wonder what it is used for as we can't select a field in the modal produced but only displays the existing fields. Normally though, looking at the $link, it should use that modal.
`$link = 'index.php?option=com_fields&amp;view=fields&amp;layout=modal&amp;tmpl=component&amp;context='
			. $context . '&amp;editor=' . $name . '&amp;' . Session::getFormToken() . '=1';`

**Comment by Quy** [comment]
It works in J3, but not in J4.

From the `Content - Fields` plugin:
```
This plugin allows you to display a custom field which has been inserted with the 'Button - Fields' plugin or using Syntax: {field #} directly into the editor area.
Possible Syntax:

    {field 1} will display the field with the ID 1
    {field 1,foo} will display the selected field using the alternative layout 'foo'.
    {fieldgroup 2} will display all fields within the fieldgroup with the ID 2.
```

**Comment by Quy** [comment]
Please test PR #25139.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25125">issues.joomla.org/tracker/joomla-cms/25125</a>.</sub>
