### ISSUE TITLE
Update Alpha 8 to 10 error - A string or Joomla\Uri\UriInterface object must be provided, a "NULL" was provided.

### ISSUE THREAD

**Issue by Chacapamac** [joomla/joomla-cms#25122]
**Steps to reproduce the issue**
Update local Mamp Alpha 8 to 10

**Additional comments**

I get this error on updating from Alpha8 to Alpha 10.

> a string or joomla\uri\uriinterface object must be provided, a "null" was provided

**_Not sure if anything is installed but it stay at Alpha 8 ?_**

**Comment by brianteeman** [comment]
it is expected that updates with alpha releases will not work

**Comment by Quy** [comment]
Please test using the nightly builds. https://developer.joomla.org/nightly-builds.html<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25122">issues.joomla.org/tracker/joomla-cms/25122</a>.</sub>

**Comment by Chacapamac** [comment]
> Please test using the nightly builds
This is what I did and add as custom URL —> https://update.joomla.org/core/nightlies/next_major_list.xml

I guess that doesn't work as Brian explain, now how can I update a test site I’m working on without reinstalling completely?

**Comment by brianteeman** [comment]
You always have to do a new install - you can not just update

Both @quy and myself gave the correct information

**Comment by Chacapamac** [comment]
Thanks Understood.
