### ISSUE TITLE
Wrong download links in XMLs

### ISSUE THREAD

**Issue by dmitriy-cloudaccess** [joomla/joomla-cms#25133]
This issue is similar to https://github.com/joomla/joomla-cms/issues/24638

https://update.joomla.org/core/nightlies/next_patch_list.xml has wrong download links.
version pointed in the XML is `3.9.7-dev`.
I guess actual version is 3.9.7-rc-Release_Candidate
Update server doesn't work because of that.

**Comment by HLeithner** [comment]
My fault, should work again.

**Comment by dmitriy-cloudaccess** [comment]
Works now. Thanks.
