### ISSUE TITLE
[4.0] Backend: Version-modal is unable to close

### ISSUE THREAD

**Issue by hgh-esn** [joomla/joomla-cms#25141]
After installing the act. Nightly build 4.0-dev I found out this:
 
### Steps to reproduce the issue
Login into the backend.
Select an element in (categories, articles, etc.) and go into edit-mode.

When clicking to the Version-button a modal opens.  

### Expected result

The modal should have reaching [x] or a reaching close button. 

### Actual result

Both button are there, but the could not be clicked.
The only way to close the modal is to reload the page by the brower.

### System information (as much as possible)

Nightly build 4.0-dev-alpha10 [190608]

**Comment by ghost** [comment]
@Quy shouldn't #25001 fix this?

**Comment by infograf768** [comment]
#25001 does not fix it.
duplicate https://github.com/joomla/joomla-cms/issues/22044
closing
