### ISSUE TITLE
[4.0] Backend: Extensions Update - Listed updates only for "enabled" extensions ?

### ISSUE THREAD

**Issue by hgh-esn** [joomla/joomla-cms#25154]
### Steps to reproduce the issue

Setup an update server.
Install an extension, i.e. a plugin.
Create an update for an installed extension and configure it in the update server.
  
### Expected result

The existing update listview should only list the plugin, if it is installed **and** enabled.
If it is enabled later on, then it should go into the update listview. 

As an alternative, the current status of the update elements should be displayed- perhaps in the form of an icon -  in the listing. 

### Actual result

All updates for enabled and disabled elements (plugin, modul,etc.) are being listed.

### System information (as much as possible)

J4-dev_alpha-10

### Additional comments

Sometimes installed elements (extensions, plugins, modules, etc.) are only deactivated and not uninstalled. 
In this case the updater should not show existing updates for such elements. 
So you avoid updating elements witch are not really active.

**Comment by brianteeman** [comment]
That would be incredibly silly. You would be potentially leaving software on your site that has known security issues

**Comment by alikon** [comment]
expected behaviuor<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25154">issues.joomla.org/tracker/joomla-cms/25154</a>.</sub>

**Comment by SniperSister** [comment]
I agree with @brianteeman, the suggestion is a very bad idea, especially from a security perspective.
