### ISSUE TITLE
[4.0] Filters broken in com_menus

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25160]
### Steps to reproduce the issue
Create a new menu item and then trash it
Using the filters set the status to trashed

### Expected result
You can see one trashed item

### Actual result
The status doesnt get set

### Steps to reproduce the issue
Go to the Menus->Manage
You can see that there are trashed menu items. Click on the number and you will go to the list of trashed menu items.
Try to change the filter to anything other than trashed

### Expected result
The page refreshes with the selected filter

### Actual result
The page refreshes with the original selected filter

**Comment by infograf768** [comment]
Confirmed. Column ordering also broken.

**Comment by infograf768** [comment]
Hint:
If a Menutype is not selected but all menu items (`- Select Menu -`) in the filter, then all filtering works fine.

**Comment by SharkyKZ** [comment]
Test PR #25181 please.

**Comment by alikon** [comment]
please test #25181<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25160">issues.joomla.org/tracker/joomla-cms/25160</a>.</sub>
