### ISSUE TITLE
Website not getting redirect..

### ISSUE THREAD

**Issue by Bean2223** [joomla/joomla-cms#25165]
Hello everyone,

It’s been awhile since I checked on my website and work on it, and I just noticed that my website is not getting redirect from http://www.windowsmoviemaker.xyz/ to https://www.windowsmoviemaker.xyz/ it automatically opens to http version. It’s really annoying. I don’t have a backup on my computer, and I really need some help and hope someone can tell me how to get rid of that http and convert into https version, i have activated the SSl through hosting and wordpress plugin too.

I’m not very good at wordpress to begin with, and it has taken me awhile to make my website. I really hope to get some help with details on how to resolve this problem.

**Comment by ghost** [comment]
Please ask on Wordpress, this is Joomla.
