### ISSUE TITLE
Backend User Management Issue when autofill tools are used

### ISSUE THREAD

**Issue by sandstorm871** [joomla/joomla-cms#25173]
More & more of us are using Password Managers & browser extensions to help us use these in daily life.

I have had several reports from some of my website administrators, that when they are editing users information in the Back End > Manage Users the user's information is prepopulated with there own name, username, emails, etc.  Causing problems when the admin is trying to change a user group or other user related information.

I see the problem as the name, username, email and password fields in the BackEnd User Profile page are encoded either the same way as a login page, or they meet the criteria that some password managers and browser autofill tools look for in trying to identify a login form. 
Can these be modified so that when the page is rendered, Password Management & other autofill tools do not think they are login forms?

### Steps to reproduce the issue
With Auto Fill enabled within the browser or Password Manager goto a Joomla! sites Back End > Users > Manage
Select a User other than yourself
You will see the users details are changed (AutoFilled) with your own.

### Expected result
Access a user's details via Back End > Users > ManageS >  User without having the information overwritten.

### Actual result
You will see the users details are changed (AutoFilled) with your own.

### System information (as much as possible)
Joomla 3.9.6
PHP7.2.x
Tested with Chrome, FF, Safari using LastPass, 1Password

**Comment by ghost** [comment]
New Features go in J4.

**Comment by brianteeman** [comment]
@franz-wohlkoenig to me it is a bug to be fixed in J3 as I am sure we have tried to do this before so it should not autofill

**Comment by alikon** [comment]
LastPass (i suppose  1password etc too) does provide settings on a per domain basis on whether to autofill fields or not   so not an issue imo

**Comment by brianteeman** [comment]
@sandstorm871 what are they using ?

**Comment by brianteeman** [comment]
Now that I think about it the problem is most likely not something we can do anything about. There is an autocomplete=off setting we could add BUT chrome disables that.

**Comment by sandstorm871** [comment]
> @sandstorm871 what are they using?

I tested this myself with LastPass & 1Password, disabling autofill does stop this happening but also stops me from using my password manager to log into the site.
Admins I have spoken with are using similar password managers, however, one was not using a password manager, so they assumed it must have been a browser setting.

Personally, I think the backend view for editing a users information shouldn't allow any sort of autofill.

**Comment by alikon** [comment]
iirc  at least Lastpass should allow you to use an url so you can still use on login url and not on user management url

**Comment by brianteeman** [comment]
> Personally, I think the backend view for editing a users information shouldn't allow any sort of autofill.

tell that to the browsers https://caniuse.com/#search=autofill

**Comment by mbabker** [comment]
The problem is if you disable autofill it's going to break the legitimate use cases, unless either the browser or the browser extension ignores that.

On a user profile edit page, it's really difficult to impossible to have the forms distinguish themselves as "I am editing my own account" versus "I am editing another person's account".  Even if you start using more detailed `autocomplete` attribute values, it doesn't really fix the problem 100%.  The autofill systems were designed for frontend use cases where a single user is doing stuff for themselves, they aren't suited for administrative interfaces.

**Comment by virusyscorp** [comment]
Old thread but this is still an issue as we approach v4.

How about a checkbox on the backend form to indicate edit of another user? Perhaps autofill could be turned off when check=true?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25173">issues.joomla.org/tracker/joomla-cms/25173</a>.</sub>
