### ISSUE TITLE
[3.9.7] Upgrade issue

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25174]
I guess the release team didnt test an update or they would have noticed that you get a "checksum failed" message

![updaate](https://user-images.githubusercontent.com/1296369/59284694-97a06400-8c64-11e9-8616-40b5099fa065.gif)

**Comment by HLeithner** [comment]
I added the wrong hashes to the update server, this couldn't be tested by the release team.
Should work now.

**Comment by brianteeman** [comment]
I can confirm it works now with the correct hashes
