### ISSUE TITLE
[4.0] sql/mysql/sample_testing.sql does not exist

### ISSUE THREAD

**Issue by antonbag** [joomla/joomla-cms#25182]
### Steps to reproduce the issue
Fresh installation of J4 alpha10. Customize installation and install sample data.

### Expected result
The sample data is installed

### Actual result
Error "sample_testing.sql does not exist"

### System information (as much as possible)

Linux system
Php 7.3

**Comment by ghazal** [comment]
Install sample data via the module "sample data" once you've logged in admin.
Triggering sample data while installing has been discontinued.
Nevertheless, you are right, it's a bug. This should be removed from the installation process.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25182">issues.joomla.org/tracker/joomla-cms/25182</a>.</sub>

**Comment by Quy** [comment]
Duplicate #20262<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25182">issues.joomla.org/tracker/joomla-cms/25182</a>.</sub>
