### ISSUE TITLE
Repeatable custom field: Editor and Textarea fields always filter HTML since Joomla! 3.9.8

### ISSUE THREAD

**Issue by BPBlueprint** [joomla/joomla-cms#25187]
No problems with Joomla! 3.9.6
Problems since Joomla! 3.9.8

### Steps to reproduce the issue
1. Create Custom Field Type "Repeatable Field".
2. Use "Editor" and/or "Text-Area"-Fields as part of Repeatable-Field.
3. Type in HTML-Tags like < br > or < p >< /p > ...

### Expected result
HTML-Tags are not filtered / deleted after saving.

### Actual result
HTML-Tags are filtered / deleted after saving.

### System information (as much as possible)
No problems with Joomla! 3.9.6
Problems since Joomla! 3.9.8

### Additional comments
In plugin-settings I can set "Custom Field: Editor" and "Custom Field: Textera" to "unfiltered" or "safe HTML". 

Those setting still work correctly with the CustomField "Editor" and CustomField "Texterea", but not with Custom Field "Repeatable->Editor" and/or "Repeatable->TextArea"

**Comment by ghost** [comment]
Closed as having Pull Request #25189
