### ISSUE TITLE
ldap authentification error with duplicate mail

### ISSUE THREAD

**Issue by edrobal** [joomla/joomla-cms#25190]
### Steps to reproduce the issue
2 ldap entries have different cn and password but same mail

### Expected result
The second user must be able to connect with its username/password

### Actual result
when connecting (first time), second cannot connect

### System information (as much as possible)
PHP exécuté sur Linux h2web38 4.9.0-0.bpo.9-amd64 #1 SMP Debian 4.9.168-1+deb9u2~deb8u1 (2019-05-14) x86_64
Type de la base de données mysql
Version de la base de données 5.6.33-log
Interclassement de la base de données 	utf8_general_ci
Collation de la connexion à la base de données 	utf8mb4_general_ci
Version de PHP 	7.3.5
Serveur web 	Apache
Serveur web pour interface PHP 	fpm-fcgi
Version de Joomla 	Joomla! 3.9.8 Stable [ Amani ] 11-June-2019 20:00 GMT
Version de la plateforme Joomla! 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by ghost** [comment]
@HLeithner can you please comment?

**Comment by alikon** [comment]
maybe related to #25191

**Comment by ghost** [comment]
but this Issue is for J3.

**Comment by richard67** [comment]
Not related.

**Comment by HLeithner** [comment]
iirc joomla writes an entry to the user table on ldap login and joomla needs an unique e-mail address per user. So I think we can't do much against this.

**Comment by edrobal** [comment]
It's crazy but no choice. And this mail address is usefulness for joomla. User not registered in ldap cannot connect in private area.
