### ISSUE TITLE
Repeatable subForm weird display on IE

### ISSUE THREAD

**Issue by ventsonge** [joomla/joomla-cms#25194]
### Steps to reproduce the issue
Install a new joomla site
Add a subform on any config file
open this config screen on IE
Check the bottom of the page :

### Expected result
the subform template should not be displayed

### Actual result
 the subform template is displayed

### System information (as much as possible)
Joomla 3.9.9
Windows 7
IE 11.0

### Additional comments
I know their was a solution to a previous IE bug relative to subform, but this bug seems to be a side effect of the solution.

**Comment by ReLater** [comment]
Could you post a screenshot. I have no idea what you are talking about. When you "Add a subform on any config file" isn't it normal that "the subform template is displayed" when you "open this config screen"??

**Comment by ventsonge** [comment]
Sure, sorry sometime i have trouble explaining bugs in english, I hope the screen will clear this up.

it's displayed like that

![joomla weird display](https://user-images.githubusercontent.com/6533878/59476104-12969400-8e8a-11e9-8be2-d062c3697d1a.png)

You can see the template is indeed displayed where it should be, but also at the end of the page.
It's even weirder if you try to input a repeatable-table subform, cause IE rewrite the HTML, so since it's a tr/td outside of a table he just remove tr/td and then when you try to add the column the display is broken

**Comment by Quy** [comment]
Closing per PR #25200.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25194">issues.joomla.org/tracker/joomla-cms/25194</a>.</sub>
