### ISSUE TITLE
[4.0] Batch copy articles

### ISSUE THREAD

**Issue by yanzhaoINT** [joomla/joomla-cms#25199]
### Steps to reproduce the issue
  - Select articles by checking the checkbox in articles list.
  - Click batch button.
  - Choose a category and choose copy. 
  - Click 'Process'.

### Expected result
Copied articles appear in the article list with new category.

### Actual result
No new articles appear in the article list.

### System information (as much as possible)
Joomla 4 alpha 9
nginx
Ubuntu 16.04.6 LTS

**Comment by Quy** [comment]
Already reported. Please test PR #24519.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25199">issues.joomla.org/tracker/joomla-cms/25199</a>.</sub>
