### ISSUE TITLE
JRoute failing to generate https urls when SSL argument set to true

### ISSUE THREAD

**Issue by kirblam** [joomla/joomla-cms#25204]
### Steps to reproduce the issue
<form action="<?php echo JRoute::_('index.php?option=com_blah', true, true); ?>"

### Expected result
<form action="https://www.ptotoday.com/component/blah/"

### Actual result
<form action="http://www.ptotoday.com/component/plus/"

### System information (as much as possible)
Appears to be specific to 3.9.8 - I believe it was working in 3.9.6
bug evident on centos 6.x production + Mac (MAMP) development environment. 
production php: 7.1.30, dev php: 7.0.12

### Additional comments
I'm adding in an extra check for http:// output as some forms appear to be failing for unsecure submission.

**Comment by brianteeman** [comment]
From the information provided it is impossible to replicate or diagnose. Obviously it is not a generic issue or there would be millions of broken sites

**Comment by SharkyKZ** [comment]
The argument is documented as an integer, not a boolean. Before #24089 it was cast as integer so passing `true` worked the same as `1`.

**Comment by ghost** [comment]
@SharkyKZ what does it mean, bug, expected behaviour, ...?

**Comment by HLeithner** [comment]
I not a bug because the documentation say the parameter should be an integer but it's an unexpected behavior change so it's more a less a b/c.

I will add a cast to the Jroute::_ function for compat reasons.

**Comment by ghost** [comment]
Closed as having Pull Request #25225
