### ISSUE TITLE
[4.0] Uninstalling extensions which have an update site fails with call to undefined method

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#25229]
### Steps to reproduce the issue

Happens since PR #25055 has been merged.

1. Install clean 4.0-dev.
2. In backend, install some extension which has an update site, e.g. one of the supported languages for 4.0, e.g. German DE.
3. Try to uninstall the extension.

### Expected result

Extension is uninstalled.

### Actual result

![screen shot 2019-06-16 at 10 43 42](https://issues.joomla.org/uploads/1/de1c14d1509a3edc48ee9469fba24cda.png)

### System information (as much as possible)

4.0-dev

### Additional comments

The problem comes from PR #25055 having been merged recently, which includes the call to a DB driver function "whereNotIn" which has not been merged yet with any PR into 4.0-dev:

```
richard@vmkubu01:~/lamp/public_html/joomla-cms-4.0-dev$ find ./ -type f -name "*\.php" -exec grep -il "wherenotin" {} \;
./plugins/extension/joomla/joomla.php
richard@vmkubu01:~/lamp/public_html/joomla-cms-4.0-dev$
```

Another PR which contains a call to that function is PR #25090 , which has not been merged yet.

The missing function has been added to the database framework with [https://github.com/joomla-framework/database/pull/156](https://github.com/joomla-framework/database/pull/156 "https://github.com/joomla-framework/database/pull/156"), but it seems these changes have not been fetched yet.

Running `composer update joomla/database` locally on my 4.0-dev branch solves the problem.

@alikon Please check and comment.

**Comment by alikon** [comment]
confimed, but https://github.com/joomla-framework/database/pull/156 is merged on the framework database repo, maybe a simple update to the composer can solve it, let's ping @HLeithner

**Comment by richard67** [comment]
@alikon ~~Not sure if update via composer will help because there has not been made a new release of the framework database package since that time.~~ Edit: I just see composer should fetch current 2.0-dev branch from the framework database package. But I always do a complete reset of my branch before testing, so a "composer install" seems not to do that. Waiting for what @HLeithner sais.

**Comment by richard67** [comment]
@alikon @HLeithner Running `composer update joomla/database` locally on my 4.0-dev branch solves the problem.

**Comment by richard67** [comment]
@alikon @HLeithner It seems I just have to change file `composer.lock` as follows, right?

![Unbenannt](https://user-images.githubusercontent.com/7413183/59563569-12d69100-903c-11e9-92ea-806f1ef61c51.png)

![Unbenannt-2](https://user-images.githubusercontent.com/7413183/59563570-166a1800-903c-11e9-9c16-75f918de01df.png)

If that is all: Shall I make the PR for that?

**Comment by richard67** [comment]
Closing as having PR #25232 .
