### ISSUE TITLE
[4.0] All modals broken in frontend when editing article

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#25220]
### Steps to reproduce the issue
Edit an article in frontend.
Try to insert any editor-xtd => a Modal displays with error.
Same when using the Versions button 
`The requested page can't be found.`

**Comment by brianteeman** [comment]
We have multiple issues for this already (including from you)

**Comment by brianteeman** [comment]
Duplicate of #24491 #23510 #23979

**Comment by ghost** [comment]
Closed as duplicate Report.
