### ISSUE TITLE
[4.0] "back-to-top": Structural flaw in the footer tag of Cassiopeia

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#25239]
There is a structural flaw in the footer tag of the site template:

```
<footer class="grid-child container-footer footer">
	<hr>
	<p class="float-right">
		<a href="#top" id="back-top" class="back-top">
			<span class="icon-arrow-up-4" aria-hidden="true"></span>
			<span class="sr-only"><?php echo Text::_('TPL_CASSIOPEIA_BACKTOTOP'); ?></span>
			</a>
		</p>
<jdoc:include type="modules" name="footer" style="none" />
	</footer>
```

### Actual result
The "back-to-top" feature is in the same tag as a call to a module in a footer position. So, when one assigns a module to the footer position, the module content is kind of "glued" to the "back-to-top".
I guess the call to the module should be at least in another tag, maybe another footer.

**Comment by Quy** [comment]
Duplicate of Issue #23457 and its PR #23606?

**Comment by C-Lodder** [comment]
@Quy, the PR isn't a good approach at all. The "back to top" should be a custom module so that users can disable it if required

**Comment by Quy** [comment]
Closed PR #23606 for a proper fix.

**Comment by SharkyKZ** [comment]
"Back to top" It's fine as a template feature, IMO. But a template option could be added for disabling it.

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/25250

**Comment by alikon** [comment]
closed for pr  #25250<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25239">issues.joomla.org/tracker/joomla-cms/25239</a>.</sub>

**Comment by C-Lodder** [comment]
@alikon PR closed. This can be reopened.

**Comment by alikon** [comment]
reopened as requested<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25239">issues.joomla.org/tracker/joomla-cms/25239</a>.</sub>

**Comment by Scrabble96** [comment]
Can this issue be renamed to include "back-to-top" or "back-top" as that is what this is really about?

**Comment by richard67** [comment]
Closing as having a pull request (PR) which shall solve this issue. Please test PR #30441 .
