### ISSUE TITLE
Duplicate module chrome when loading multiple instances of the same module

### ISSUE THREAD

**Issue by ralain** [joomla/joomla-cms#25253]
### Steps to reproduce the issue

Create a simple Custom HTML module. Set Show Title to Show. Set Module Style to html5.
Insert the module multiple times in the same article using loadmodule, loadposition or loadmoduleid methods. Example:
{loadmoduleid 96}{loadmoduleid 96}{loadmoduleid 96}

### Expected result

Module repeats unchanged when viewing the article in frontend.

### Actual result

Module repeats with title showing multiple times on subsequent instances of the module.

![screen shot 2019-06-17 at 10 13 42](https://issues.joomla.org/uploads/1/731f473ae1423c7ad957c7a86cedbcb8.png)

**Comment by SharkyKZ** [comment]
Duplicate of https://github.com/joomla/joomla-cms/issues/12888.

**Comment by ghost** [comment]
Thanks for Report @ralain and for finding the Duplicate @SharkyKZ 

Closed as duplicate Report.
