### ISSUE TITLE
[com_contact] Undefined property: ContactTableContact::$title

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#25255]
### Steps to reproduce the issue
Go to Components > Contacts
Select a contact.
Click Batch.
Perform Copy to a category.

### Actual result
> PHP Notice:  Undefined property: ContactTableContact::$title in \libraries\src\MVC\Model\AdminModel.php on line 1556

### System information (as much as possible)
Latest staging

**Comment by richard67** [comment]
Confirmed.

**Comment by SharkyKZ** [comment]
Test PR #25259 please.

**Comment by ghost** [comment]
Closed as having Pull Request #25259
