### ISSUE TITLE
Help selector field in global config removed...!

### ISSUE THREAD

**Issue by tarnian1390** [joomla/joomla-cms#25267]
### Actual result
Help selector field in global config removed...! 
I can't point to my help server...

And please remove xml file from update package joomlaCMS...

**Comment by ghost** [comment]
Please ask on [Forum](https://forum.joomla.org/)

**Comment by HLeithner** [comment]
The Helpserver support has been removed in the last minor update.

**Comment by infograf768** [comment]
@tarnian1390
The only other help server available was for French.
As it was totally obsolete and French help is now available through the joomla server, it was useless, thus that change.
