### ISSUE TITLE
0 Joomla\Filesystem\File::delete: Failed deleting inaccessible file xyz.php

### ISSUE THREAD

**Issue by sajalaspl** [joomla/joomla-cms#25268]
Joomla 3.9.4

This seems to be general issue, and it can happen with any extension you're installing.

For me, I'm installing EasyBlog extension, and during installation it gives me following error:

0 Joomla\Filesystem\File::delete: Failed deleting inaccessible file autoposting.php 

Now, if I find "autoposting.php" in easyblog dirs, I delete it manually, it moves on. Then, it gives same error but for another file.

I tried 777 whole project, but no difference.

Can anyone help on this?

**Comment by ghost** [comment]
Please ask on [Forum](https://forum.joomla.org/)

**Comment by HLeithner** [comment]
@sajalaspl we need more information about the versions you are using.

**Comment by Quy** [comment]
Possible duplicate #23504

**Comment by ghost** [comment]
@sajalaspl can you please confirm the report is a duplicate of #23504?

**Comment by Quy** [comment]
Duplicate of #23504<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25268">issues.joomla.org/tracker/joomla-cms/25268</a>.</sub>

**Comment by sajalaspl** [comment]
System Information:

PHP Built On | Linux aum224.aum.com 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64
-- | --
Database Type | mysql
Database Version | 5.5.5-10.2.7-MariaDB
Database Collation | utf32_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.1.23
Web Server | nginx/1.12.1
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 3.9.4 Stable [ Amani ] 12-March-2019 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0

**Comment by HLeithner** [comment]
Seams not to be a duplicate because it's on linux and the other bugreport is windows specific...

**Comment by Quy** [comment]
Linux is discussed in the other issue. Why not keep it under one issue?

**Comment by brianteeman** [comment]
The site probably needs to use ftp mode (and it needs updating)

**Comment by HLeithner** [comment]
Because I'm not sure thats it is the same problem.

@sajalaspl can you edit the file libraries\vendor\joomla\filesystem\src\Path.php as commented in this comment: https://github.com/joomla/joomla-cms/issues/23504#issuecomment-480508661

The Line shoud be 124.

And as brian said please update to the lastest version before you test.

**Comment by mbabker** [comment]
Or, you know, someone can actually dig in and try fixing the API and re-validating all of the assumptions within it like I suggested 2 months ago.

**Comment by sajalaspl** [comment]
@HLeithner OK, I'll upgrade Joomla version, then I'll do the changes as you've mentioned in the libraries\vendor\joomla\filesystem\src\Path.php file. And then I'll get back to you.

As a temporary "fix", I deleted all the existing files of the EasyBlog extension "manually", and that did the trick.

**Comment by alikon** [comment]
Closing this due to not receiving required information to determine if this is a bug or not. If you feel this still needs review, please open a new tracker entry with as much information as possible to ensure it can be reviewed properly
