### ISSUE TITLE
Update of user settings requires knowledge of user password

### ISSUE THREAD

**Issue by Guttormson** [joomla/joomla-cms#25273]
### Steps to reproduce the issue
As administrator, change a setting for another user - ie. editor, language or user group

### Expected result
As administrator I would expect to make such a change without affecting, or knowledge of, user's password

### Actual result
Requires confirmation of password with message : 'The passwords you entered do not match. Please enter your desired password in the password field and confirm your entry by entering it in the confirm password field.'
Will not allow a change without either changing the ps or knowing it.

**Comment by ReLater** [comment]
> The passwords you entered do not match

I haven't seen that message for a long time in Joomla. Normally it's a browser addon or an app as far as I remember that fills the password field.

> Will not allow a change without either changing the ps or knowing it.

That's wrong. Simply clear **both** password fields! Then you can save.

**Comment by Guttormson** [comment]
How simple.  Thanks

**Comment by hgh-esn** [comment]
... and then the user has a cleared password?

**Comment by Guttormson** [comment]
No, the password is re-entered by the system at the conclusion of the
save.  Tried it and that was what happened in my Chrome browser.

**Comment by ghost** [comment]
@Guttormson please close the Issue if its solved.
