### ISSUE TITLE
HTML code removed from Editor field in repeatable custom field

### ISSUE THREAD

**Issue by artur-stepien** [joomla/joomla-cms#25271]
### Steps to reproduce the issue
* Go to: `Content -> Fields -> New`
* Fill `Title` and `Name`
* From `Type` select `Repeatable`
* In `Form Fields` add new field of type `Editor` and fill its name
* Click on `Save & Close`
* Go to: `Content -> Articles -> Add New Article`
* Find your new created custom field and fill it with for example bold text.
* Fill article `Title` and mark `Featured` to `Yes`
* Click on `Save & Close`
* Go to front-end of your website and find the article you just created then enter it.

### Expected result
The custom field we just created should contain HTML (for example bold text)

### Actual result
Pure text, no new lines, no bold text.

### System information (as much as possible)
Joomla 3.9.8 but that can be for a longer period of time.

### Additional comments
The content of `rawvalue` in stored field is HTML free. So it is cleared on article save. The `Fields - Repeatable`  plugin doesn't have the filter parameter. I tried to go into `Fields - Editor` plugin parameters and setting default filter there. But as it seems it isn't even used. The best option would probably be to use the filtering option from `Fields - Editor` plugin in rendering of Editor in `Fields - Repeatable` or what would be most flexible, use `Text Filters` settings from `Global Configuration`. That way we can secure the input depending on user group.

**Comment by Quy** [comment]
Fixed per #25189 to be in 3.9.9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25271">issues.joomla.org/tracker/joomla-cms/25271</a>.</sub>

**Comment by artur-stepien** [comment]
@Quy Just quick question. When is the planned 3.9.9 release date?

**Comment by ghost** [comment]
Once a Month, last Release was last Week (https://github.com/joomla/joomla-cms/milestones?state=closed)

**Comment by HLeithner** [comment]
I updated the planed release date for 9.7.2019

**Comment by ReLater** [comment]
> The best option would probably be to use the filtering option from Fields - Editor plugin in rendering of Editor in Fields - Repeatable

If you find a working way to re-add the Global option for https://github.com/joomla/joomla-cms/pull/25189 ; a pr would be very welcome.

**Comment by artur-stepien** [comment]
@ReLater Youre talking about extending this `Filter` parameter in provided PR to have something like `Use global configuration`?

**Comment by ReLater** [comment]
@artur-stepien 
> Youre talking about extending this Filter parameter in provided PR to have something like Use global configuration?

Yes. We removed the `Global` parameter there because it didn't work and I didn't want to hard code the sub field types in repeatable.php or rather start several requests for the active filter value of any single plugin there. If you find an elegant way ... would be great.
