### ISSUE TITLE
[4.0] xreference

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25272]
every **article** has two input fields in the publishing tab
![image](https://user-images.githubusercontent.com/1296369/59771204-32222800-92a1-11e9-80f6-c2623c3b193b.png)
![image](https://user-images.githubusercontent.com/1296369/59771236-39493600-92a1-11e9-8e7d-05c3c86d5786.png)

Guess what both have the same field name="xreference"
The first is saved in the json field 'metadata'
The second is saved in its own dedicated field

I can't see anywhere that they are used in com_contact
the code for this was added in 1.6 by @infograf768 

=====
**contacts** does not have an input field but there is one in the database. 
This time there is some code that references it in the store function but I don't see how you could ever store anything if there is no input. This code was added with #29088 by @mbabker
https://github.com/joomla/joomla-cms/blob/12d28754c4cee2b3f2e9fa43934c86e2a9f0b2a3/administrator/components/com_contact/Table/ContactTable.php#L102-L106

======
**newsfeeds** does have an input field and a database field
![image](https://user-images.githubusercontent.com/1296369/59772183-394a3580-92a3-11e9-9993-c0dc2b73c7e8.png)

but i cant find any reference at all in the code to see if it is used

=====
There are various other places that get the field in a query for example but then dont do anything with it. To me this is all some legacy code that has lost the connection to whatever it used to do and should be removed. No point keeping and updating code that doesnt do anything

**Comment by Quy** [comment]
You reported this before #17173. Sorry I don't have an answer.

**Comment by brianteeman** [comment]
Yes I know I am trying again.

**Comment by brianteeman** [comment]
Surely someone must care that we have legacy code that no one knows what its for polluting the cms

**Comment by Quy** [comment]
Found this in Joomla Forum: https://forum.joomla.org/viewtopic.php?t=34676

**Comment by brianteeman** [comment]
Well that says to me that this field is completely useless now

**Comment by ghost** [comment]
Closed as having Pull Request #25524
