### ISSUE TITLE
Update typo3 phar-steam-wrapper

### ISSUE THREAD

**Issue by LoRexxar** [joomla/joomla-cms#25277]
### Is your feature request related to a problem? Please describe.

typo3 phar-steam-wrapper 2.1.1 and 2.1.2 update and fix some bugs. and some bugs  affect my use, I hope to update this plugin。

### Describe the solution you'd like

update typo3 phar-steam-wrapper to 2.1.2

### Additional context

https://github.com/TYPO3/phar-stream-wrapper/releases

**Comment by LoRexxar** [comment]
there are a secrutiy issue update in 2.1.1

https://typo3.org/security/advisory/typo3-psa-2019-008/

i think it will make my joomla cms be unsafe , Although I don't know how the problem will occur, I want to protect my server.

**Comment by HLeithner** [comment]
The security problem you mention has been fixed in Joomla! 3.9.6 as 
[20190502] - Core - By-passing protection of Phar Stream Wrapper Interceptor
https://developer.joomla.org/security-centre.html

I will do a composer update and create a PR for it, you can test this later today.

**Comment by ghost** [comment]
Closed as having Pull Request #25279
