### ISSUE TITLE
Update the AppVeyor Badge to point to Release-Joomla

### ISSUE THREAD

**Issue by blastoise186** [joomla/joomla-cms#25274]
### Is your feature request related to a problem? Please describe.
I've noticed that for some time now, the AppVeyor Badge on Joomla's readme file here on GitHub still directs to /joomla/joomla-cms which is no longer valid, leaving it in a constant state of "Build Failing" indefinitely.

### Describe the solution you'd like

Because the project is now under /release-joomla/joomla-cms on AppVeyor, would it be possible to change the AppVeyor Badge to the new location?

### Additional context

I tried to look at how to do this myself, but it appears that I'd need a link from their API which I don't think I can get.

**Comment by richard67** [comment]
@blastoise186 Do you want to make the pull requests (1 for staging and 1 for 4.0-dev) to correct this? Or shall I do that?

**Comment by blastoise186** [comment]
Hi @richard67 ,

I would be happy to give it a go, it's just that there seems to be an API specific link for AppVeyor, and I don't know if the link changed when the project got moved.

But I guess it's worth me giving it a go

**Comment by richard67** [comment]
@wilsonge George, do you know if these keys like "bpcx ..." in the link URLs of the Appveyor badges have changed when it was changed from `project/joomla/joomla-cms` to `project/release-joomla/joomla-cms`? I guess it needs an Appveyor login to check that.

**Comment by blastoise186** [comment]
I might have a problem there actually.

According to https://www.appveyor.com/docs/status-badges/ the Status Badges normally include a security token, but it might be possible to workaround it since the repository is public

**Comment by richard67** [comment]
Let's wait for reply from George, and if he is not available I will ask some other maintainer who should know that. I'll report back here in that case.

**Comment by Quy** [comment]
Fixed in J4 with PR #25241.

**Comment by richard67** [comment]
@Quy No. In that PR URL is still `https://ci.appveyor.com/project/joomla/joomla-cms` and not `https://ci.appveyor.com/project/release-joomla/joomla-cms`. If you look on the page of the first link, you see old stuff from 9 months ago. If you look on the page of the 2nd link, you see recent commits for both 4.0-dev and staging. Unfortunately both @Hackwar when he coded the PR and me when I tested it did not notice that the badge status does not fit to recent commits.

**Comment by blastoise186** [comment]
Thanks. In theory, I could manually force the badge to use links that don't involve a security token, but I don't feel comfortable making such a change without agreement.

**Comment by richard67** [comment]
@blastoise186 No, we should use the security token. The one (or more) maintainers who have the credentials for the Appveyor login will know if those tokens have changed or not, or will be able to look that up. No need to hurry. It seems it did not work in the last 9 months, so one or 2 days more or less will not be a big issue.

**Comment by blastoise186** [comment]
That's good with me then. Thanks for handling it!

**Comment by richard67** [comment]
Thanks for reporting it.

**Comment by blastoise186** [comment]
No problem. Also, while I'm here I noticed that 3.10-dev still shows the old links for the Drone badge. Would you like me to PR that badge, since I can do that without any trouble?

**Comment by richard67** [comment]
No, the 3.10-dev branch gets the changes from the staging branch merged in after every new 3.9.x release. And in staging it recently has been corrected. So for 3.10-dev nothing has to be done.

**Comment by richard67** [comment]
@blastoise186 But if you would like to contribute to Joomla and have a bit spare time from time to time, just check some new issues, and if you know how to solve it, a pull request is always welcome. Same if you discover a new issue, feel free to make a PR. We have a few code style rules which are checked by our ci tools (Drone), and we have the rule that every PR should be tested by the author before proposing it, but I think that's quite normal. As we are an open community, everybody can propose PRs, it does not need to become a member of anything.

**Comment by blastoise186** [comment]
Sure thing, thanks! I'm unfortunately unable to contribute code as it's not in my skill set, but I've been watching the repository for a few years and use Joomla a lot. So I'll definitely try to contribute a few things.

Thanks for the welcome too, I appreciate it

**Comment by richard67** [comment]
Well, watching and using Joomla and reporting issues is also a good thing and helpful for us. So thanks for that, and keep going on.

**Comment by ghost** [comment]
Closed as having Pull Request #25275

**Comment by richard67** [comment]
Is for staging. PR for 4.0-dev follows in a minute.

**Comment by richard67** [comment]
PR for 4.0-dev is #25276 .

**Comment by blastoise186** [comment]
Ah ha, perfect. tysm
