### ISSUE TITLE
[4.0]  Extensions-Update: generate an info, when extension is unpublished

### ISSUE THREAD

**Issue by hgh-esn** [joomla/joomla-cms#25280]
### Describe the solution you'd like
Make the update listview a bit more informative to the admin.  Show a hint for unpublished extensions when an update exist.

**Background:**
The extension update view lists all the extensions for which an update exists.

**But only the installation of the extension and not its actual state (enabled/disabled) is recognised.**

I think, it would be a good idea to at least give a hint, if an update for a currently not activated extension is pending.
The administrator can then even form an opinion on whether the update should be carried out, or whether he makes a more detailed check before and eventually even uninstalled the extension, if it isn't necessary anymore.

### Actual result

Currently, if there's one or more updates, a list will be displayed, containing in tabular form the essential information such as: name of extension, currently installed version, new version, changelog, etc.

![2019-06-20_11h27_02](https://user-images.githubusercontent.com/5299726/59838016-8505e900-934e-11e9-8e19-6152df900327.png)

### Expected result

If the are no unpublished extensions to update, the first seen view is displayed.

But if there is an **update for a currently inactive extension**, an **Info column** will be generated on the left and an **info icon** with **short text** will be displayed there. 
In addition, a message is displayed above the table in an additional info line, indicating that one and several updates are available for deactivated extensions. 
This hint line is important, because the list may be long because of multiple entries and the inactive extension may not be immediately visible. If you scroll through the list, you can find it via the info icon.

![2019-06-20_10h23_07](https://user-images.githubusercontent.com/5299726/59838171-ca2a1b00-934e-11e9-92c3-668a66f21d84.png)
![2019-06-20_10h23_38](https://user-images.githubusercontent.com/5299726/59838183-ceeecf00-934e-11e9-834b-ba6925c08219.png)

### Additional comments

Creating the appropriate hints is not difficult and can be realized with some smaller changes in this existing files as:

/administrator/components/com_installer/View/Update/HtmlView.php    
... check if an unpublished update-item exists
/administrator/components/com_installer/tmpl/update/default.php     
... make changes to the view
/administrator/components/com_installer/Model/UpdateModel.php      
 ... get the necessary data
/administrator/language/en-GB/en-GB.com_installer.ini               
... some new language keys

If it is wished, I can do the codings.

**Comment by mbabker** [comment]
Distinguishing an extension as enabled or disabled on the update screen is a bad idea (and FWIW WordPress does not do this either).  Regardless of whether it is enabled or disabled, it should still be updated as the vendor releases updates.  Even as a disabled extension, it is still code on your site and is a possible path toward a hack if not maintained.

**Comment by ghost** [comment]
isn't his Issue the same than #25154?

**Comment by mbabker** [comment]
No, that one wanted to flat out remove disabled extensions from the update list.

**Comment by brianteeman** [comment]
Both should be closed as they encourage bad security practices

**Comment by ghost** [comment]
closed as stated above. Thanks for Info @mbabker @brianteeman

**Comment by hgh-esn** [comment]
@mbabker @brianteeman @franz-wohlkoenig 
I can not really share the concerns. 
If it is important to update non-activated elements as well, the possibility to exclude an update via the select tick should **not** be possible. In short, a forced update should be implemented for all installed elements, whether activated or not.

**Comment by mbabker** [comment]
Blindly applying extension updates is a pretty bad idea too.  Users ignoring updates is one thing, and it's not something anyone should try to tackle in core.  Changing the interface to give the perception that it's OK to ignore updates for disabled extensions is a pretty bad idea in the long run.  If it is installed on your site, whether active or not it needs to be maintained.  The only safe way to ignore extension updates is to uninstall the extension.

Also, there is this thing about taking a backup and testing updates before applying them in production.  Imagine if Joomla just blindly applied extension updates when they were found and a major, backward compatibility breaking, update were applied with no notice.
