### ISSUE TITLE
[4.0] Tooltip cutoff

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#25282]
### Steps to reproduce the issue
Go to Contents > Site Modules
Hover mouse over icon under Status column.

### Actual result
![tooltip](https://user-images.githubusercontent.com/368084/59858319-a1465d80-932f-11e9-8797-3733a0605a70.jpg)

**Comment by brianteeman** [comment]
Confirmed - I am sure a css wizard can fix this ;) aka not me

**Comment by Quy** [comment]
See PR #25355<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25282">issues.joomla.org/tracker/joomla-cms/25282</a>.</sub>
