### ISSUE TITLE
Errors occur when changing category in the batch window

### ISSUE THREAD

**Issue by Duddy67** [joomla/joomla-cms#25284]
### Steps to reproduce the issue
Select some articles in the backend article list. 
Click on the Batch button then change the category of these articles.

### Expected result
The selected articles are now in the category selected in the batch window.

### Actual result
Error messages occur but in a very random way.

It can be this one:

`Batch process failed with following error: Joomla\CMS\Table\Asset::moveByReference() is trying to make record ID 68 a child of itself.`

or this one:

`1062 Duplicate entry '1-3-3' for key 'uc_ItemnameTagid'`

### System information (as much as possible)
Ubuntu 18.04 
Apache 2.4.29
MySQL 5.7.26
Joomla 3.9.8

### Additional comments
Again, the errors occur in a very random way. You sometimes have to repeat the steps several times before one of these error appears.
N.B: In order to get the second error (Duplicate entry) the selected articles must have tags.

**Comment by ghost** [comment]
@Bug Squad Team: Have one an Idea about the 2 given Error Messages?

**Comment by alikon** [comment]
i suspect  a buggy `#__asset` table

**Comment by ghost** [comment]
Thanks @alikon. @Duddy67 Please ask on [Forum](https://forum.joomla.org/)

**Comment by richard67** [comment]
@franz-wohlkoenig , I hope nobody here uses thie nick name "bug", otherwise he/she got an email ;-)

I've never seen those error messages before, but as Nicola said, it smells like asset table not ok.

**Comment by Duddy67** [comment]
So this problem is not considered as a bug ?
I ran these tests with a Joomla out of the box (no extra components, plugins...) so I guess the asset table is perfectly clean. 
Moreover, regarding the Duplicate entry error, it seems to be related to the tag table and not necessarily to the asset table.

**Comment by ghost** [comment]
> I ran these tests with a Joomla out of the box

thats a new Information > reopening.

**Comment by richard67** [comment]
@Duddy67 "Joomla out of the box ...." did you install any kind of sample data with the last step of the installation?

**Comment by richard67** [comment]
@Duddy67 And what is your PHP version? That's missing in the system info in the description.

**Comment by HLeithner** [comment]
@alikon can be related to your PR https://github.com/joomla/joomla-cms/pull/24730 ?

**Comment by alikon** [comment]
it could be, but  

> the errors occur in a very random way

so untill we have a how to reproduce way.... it's quite hard

**Comment by ghost** [comment]
@Duddy67 can you please describe exactly what happens if error occur next time so we can reproduce?

**Comment by Duddy67** [comment]
@richard67  
`did you install any kind of sample data with the last step of the installation?`
Nope, I created the articles by hand one by one.

`And what is your PHP version?`
My PHP version: 7.2.1

@franz-wohlkoenig 
As I said it's a tricky one and you have to repeat the steps several times before one of these errors occurs. Sometimes by alternating the batch selection (ie: several articles then just one) it might trigger the error. But again it's very random. I attach 2 screenshots of these errors just in case.

![2019-06-21-100839_1280x1024_scrot](https://user-images.githubusercontent.com/19156036/59908840-9dd5d380-940e-11e9-966f-fb2e308b5092.png)
![2019-06-21-101143_1280x1024_scrot](https://user-images.githubusercontent.com/19156036/59908853-a3cbb480-940e-11e9-9136-023d94299146.png)

**Comment by SharkyKZ** [comment]
@Duddy67 Please enable debug in System Configuration and try to reproduce the error in first screenshot. You should see a stack trace. Post it here.

**Comment by Duddy67** [comment]
@SharkyKZ 
Here: (it's in 2 parts, sorry for that)

![2019-06-21-104327_1280x1024_scrot](https://user-images.githubusercontent.com/19156036/59910277-e5119380-9411-11e9-9b5b-dd262a7e78a6.png)
![2019-06-21-104331_1280x1024_scrot](https://user-images.githubusercontent.com/19156036/59910292-e9d64780-9411-11e9-9fe6-73f3207406bd.png)

**Comment by alikon** [comment]
i've tryied to replicate but ..... unable to get this error
i've copyied moved artciles between categories with tag without ..... but...unable to replicate

**Comment by Quy** [comment]
@Duddy67 Is this reproducible with the latest version of Joomla? If yes, please test PR #20943.

**Comment by Quy** [comment]
Closing due to lack of response. Please test with the latest Joomla. If still an issue, please comment here.

**Comment by ausaec** [comment]
I have this issue right now. I was moving categories around. Not sure how to fix but I’m about to hire a freelancer on Upwork because it’s crashed my whole site Alecomm.com
 Any thoughts would be great. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25284">issues.joomla.org/tracker/joomla-cms/25284</a>.</sub>
