### ISSUE TITLE
Table of Content Generator for Joomla 4.0

### ISSUE THREAD

**Issue by Gitjk** [joomla/joomla-cms#25294]
Discussion / Feature Request:

Joomla is a CMS, but imho it still lacks an easy to use 'Table of Content' generator, which can for example automatically generate a ToC for all articles within a category from the article headings. The article index feature only allows to add anchor links within a single article. And the category list menu item displays only an 'ugly' table without the possibility to add a structure to the list of articles.

I'm currently trying to make navigating within a long manual more user friendly and found only one extension (Extra ToC) in the JED, which can eventually produce for example an easy to use structured ToC from articles within a category in a sidebar.

Imho it would be nice to have something like this in Joomla 4.0.

**Comment by brianteeman** [comment]
What is wrong with using  Modules: Articles - Category

**Comment by Gitjk** [comment]
Somehow I missed that module all these years. I'll have to play with it for a few days to see if I can come up with visually appealing and easy to follow ToC structure. Primarily I want to replace the ugly category list table with something better and have a ToC generated from article headings automatically - without the need to frequently have to adjust fixed menus manually.

At a first glance the ToC extension mentioned above provides more options.

Anyway, thanks for your hint. Will test it...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25294">issues.joomla.org/tracker/joomla-cms/25294</a>.</sub>

**Comment by ghost** [comment]
@Gitjk please close the Issue if its solved already.

**Comment by Gitjk** [comment]
Don't know yet if Brian's recommendation does what I want to have. Will close this feature request and eventually reopen it later if I find significant shortcomings with the existing 'Articles - Category' module when trying to use it for user-friendly ToCs.
