### ISSUE TITLE
Entity Encoding don't work with Titles

### ISSUE THREAD

**Issue by forofo** [joomla/joomla-cms#25300]
### Steps to reproduce the issue
(redirected from JCE developers: https://github.com/widgetfactory/jce/issues/42 )

Enable Editor Global Configuration -> Entity Encoding: "Named" , and this option only works for the article text although no for the titles of articles.

Special characters of some languages are not fixed in the title of articles when are published. Presently, we are forced to insert HTML entities in the title field (ie: &eacute;-> é) to replace these special characters (accents, etc) and avoid the ascii wrong.

### Expected result

é á ó

### Actual result
ascii chars

### System information (as much as possible)
Joomla last stable version

**Comment by brianteeman** [comment]
> Enable Editor Global Configuration -> Entity Encoding: "Named" , and this option only works for the article text although no for the titles of articles.

I don't have an option like that - could you post a screenshot

**Comment by brianteeman** [comment]
I think you might have meant the configuration in the tinymce editor plugin and not a global configuration?

If that is correct then no setting there would have anything to do with the text in a title field

I have created many articles using french characters with accents without any problem with an incorrect value

![image](https://user-images.githubusercontent.com/1296369/59980239-d3371880-95ea-11e9-9ed8-6ab06d07165e.png)

**Comment by esedic** [comment]
> I think you might have meant the configuration in the tinymce editor plugin and not a global configuration?
> 
> If that is correct then no setting there would have anything to do with the text in a title field
> 
> I have created many articles using french characters with accents without any problem with an incorrect value
> 
> ![image](https://user-images.githubusercontent.com/1296369/59980239-d3371880-95ea-11e9-9ed8-6ab06d07165e.png)

Based on his JCE Github issue, @forofo is probably talking about JCE config parameter, not TinyMCE.

**Comment by brianteeman** [comment]
> Based on his JCE Github issue, @forofo is probably talking about JCE config parameter, not TinyMCE.

Tinymce has a similar one ;) But the comment in the JCE issue is correct. NO editor plugin option has any impact on a text field

**Comment by forofo** [comment]
> I don't have an option like that - could you post a screenshot

JCE developers told me it was  a Joomla problem:  https://github.com/widgetfactory/jce/issues/42

The only option to hide the bug is using "Named" instead "UTF-8".  In this way at least we can write HTML entities to hide the problem: 
![jce](https://user-images.githubusercontent.com/11773511/59985020-07ccc380-962f-11e9-9cdf-01f93fc67fdf.jpg)


Only after writing the HTML entity and saving, the title will show the right character:

![edit1](https://user-images.githubusercontent.com/11773511/59985071-66923d00-962f-11e9-94eb-91f152071c85.jpg)


![edit2](https://user-images.githubusercontent.com/11773511/59985073-6bef8780-962f-11e9-825f-afc0665d67d0.jpg)

If now I save this again, then again it will show wrong ascii characters. This is uncomfortable and primitive. Is there some easy fix?

thanks!

**Comment by ReLater** [comment]
Are you talking about problems in the frontend?

I can't reproduce your find:

![24-06-_2019_04-09-20](https://user-images.githubusercontent.com/20780646/59986240-30a48700-9636-11e9-9d5c-ec1e78d8ccc1.jpg)

![24-06-_2019_04-09-50](https://user-images.githubusercontent.com/20780646/59986246-3601d180-9636-11e9-9803-116a0c9a82a3.jpg)

![24-06-_2019_04-07-29](https://user-images.githubusercontent.com/20780646/59986249-39955880-9636-11e9-8cee-fbbcb74c9750.jpg)

**Comment by infograf768** [comment]
Why would one enter an item title as html entities? Most are resolved to utf8 when saved in db.
Some are not (Non Latin glyphs as Chinese for example);

Your screenshots show the use of K2 which is anyway not Joomla core.
I think this can be closed.

**Comment by ghost** [comment]
closed as stated above
