### ISSUE TITLE
[subform] Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#25308]
### Steps to reproduce the issue
Go System >Global Configuration > Users
Click Save button
View PHP error log

### Actual result
> PHP Warning:  Invalid argument supplied for foreach() in \libraries\src\Form\Form.php on line 1558

### System information (as much as possible)
Occurs only in v3.9.8

**Comment by ReLater** [comment]
Reason is the change for the subform security fix in Form.php. When the "Email Domain Options" subform object in user options is empty (no rows) we have this warning.

Please test pr https://github.com/joomla/joomla-cms/pull/25310
