### ISSUE TITLE
[4.0] Diff View in Template Manager is broken

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#25323]
### Steps to reproduce the issue

1. Open Template Manager 
2. Click on an override-file. Perhaps you have to create an override first.
3. Activate diff-view

### Expected result

You see the diff-view

### Actual result

No diff-view is opened. 

### Additional comments
See https://github.com/joomla/joomla-cms/pull/21851 for more information about diff-view

![Templates  Customise  Cassiopeia    test   Administration(1)](https://user-images.githubusercontent.com/9974686/60084665-3a161800-9738-11e9-9394-68606aea3eca.png)

**Comment by richard67** [comment]
When opening the edit view, a javascript error is reported for the editor (codemirror), and then the loading of the js file is aborted, see following screen shot:
![Unbenannt](https://user-images.githubusercontent.com/7413183/60116709-db24c300-9778-11e9-8fbd-6bc1609fccd2.png)

In English: 1. script media/vendor/codemirror/mode/text/x-php/text/x-php.min.js has been loaded even if its MIME type is not valid for javascript, and 2. Loading failed for the same script.

Maybe that's related to this issue?

**Comment by ghazal** [comment]
Issue and JS error confirmed.
Today's build.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25323">issues.joomla.org/tracker/joomla-cms/25323</a>.</sub>

**Comment by richard67** [comment]
The js error happens only when editing a file from an override. When editing any other file not belonging to any override, the js errro doesn't happen. So it seems really to be related to the override management.

**Comment by richard67** [comment]
No idea what that could be. I think it needs a js expert. Maybe @dgrammatiko can help?

**Comment by richard67** [comment]
@SharkyKZ Could that be related to PR #24639 ?

**Comment by SharkyKZ** [comment]
@richard67 No, that's not related.

**Comment by SharkyKZ** [comment]
My guess it's to do with #24463.

**Comment by richard67** [comment]
That could be. I will check details later after work.

**Comment by richard67** [comment]
@brianteeman Could you have a look on this issue? I think it really can have something to do with the new switchers from PR #24463 , like Sharky supposes, because that diff view for override files in the template manager contains switchers, too, and those seem still be the old ones.

**Comment by brianteeman** [comment]
Not able to test right now. the template_overrides table never gets updated

I doubt very much it is anything to do with the switcher code as that is pure css. But you can test it yourself by deleting the class=switcher for two fields in administrator\components\com_templates\forms\source.xml

**Comment by richard67** [comment]
@brianteeman Thanks, I've tried that, removing class from the 2 switchers, and as you supposed that did not help. It seems the js of that diff view is either broken or not loaded at all. Maybe something to do with the codemirror editors in that view? Do you know who can help here further? I first thought some selector in js may fail because of changed classes, that's why I thought it could be related to your changes.

**Comment by dgrammatiko** [comment]
FWIW the js of that diff view was depending on 2 events emitted by the old switcher. Those events do NOT exist any more, therefore, the script doesn't do anything anymore...

**Comment by richard67** [comment]
@dgrammatiko This explains a lot. Thanks for helping.

**Comment by dgrammatiko** [comment]
@richard67 I can also describe a possible solution:
- Add an on click attribute on the form of that view, eg onclick="Joomla.switchDifState()"
- add a simple iife on the top of the js file on that view something like: 
```js
((Joomla) => {
  Joomla.switchDifState = (event) {
    if (event.target.checked) {
      event.target.dispatchEvent(new CustomEvent('theNameOfTheExistingEventForOn'));
    } else {
      event.target.dispatchEvent(new CustomEvent('theNameOfTheExistingEventForOff'));
    }
})(Joomla);
``` 

- The code might need some tweaks...
- This approach expects that the new switch element **has** a functional code for the onclick event

**Comment by richard67** [comment]
@dgrammatiko Thanks. I'll try to find some time on weekend. But if someone who is more familiar with js and events finds time before, I would not be unhappy.

**Comment by Harmageddon** [comment]
I'd propose #26359 as a fix. Please have a look there!

**Comment by alikon** [comment]
please test #26359<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25323">issues.joomla.org/tracker/joomla-cms/25323</a>.</sub>
