### ISSUE TITLE
[4.0] Editor Plugin - Menu.  Menus do not appear, styling is also off

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#25336]
### Steps to reproduce the issue
Open an article
Click on the CMS Content Editor button
Click on Menus
Choose a menu from the dropdown e.g. "main menu"

### Expected result
Menus items appear
Fonts are styled normally

### Actual result
I believe labels are showing which are only meant for screen readers
No menu items show
Fonts are in Times or something similar

### System information (as much as possible)
=============
System Information
=============
php: Linux lamp134.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.7.el6h.x86_64 #1 SMP Mon Dec 17 12:02:35 EST 2018 x86_64
dbserver: mysql
dbversion: 5.7.24-cll-lve
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 7.2.19
server: Apache
sapi_name: cgi-fcgi
version: Joomla! 4.0.0-alpha10-dev Development [ Amani ] 16-May-2019 19:22 GMT
useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0

**Comment by brianteeman** [comment]
Is this front end or back end

Some screenshots would be useful

**Comment by SharkyKZ** [comment]
Caused by #25197. PR on the way.

**Comment by uglyeoin** [comment]
I had only tested on the back end, but unfortunately the front-end looks a bit odd

![initial](https://user-images.githubusercontent.com/4665225/60177098-ed9e0b80-980f-11e9-8ca5-7da015fcf6a4.jpg)
![on-click](https://user-images.githubusercontent.com/4665225/60177099-ed9e0b80-980f-11e9-8fe8-639805b81ad5.jpg)
![front-end](https://user-images.githubusercontent.com/4665225/60177097-ed9e0b80-980f-11e9-97e4-a3de50d59f05.jpg)

**Comment by uglyeoin** [comment]
@SharkyKZ great thanks, do I still need to raise one for the front end issue do you know?  I can't see any articles and I can't edit them

**Comment by brianteeman** [comment]
re the front end - make sure you are 100% upto date and that you have run `npm i`

**Comment by SharkyKZ** [comment]
Test PR #25338 please.

**Comment by ghost** [comment]
Closed as having Pull Request #25338

**Comment by uglyeoin** [comment]
@brianteeman thanks, will try that now

**Comment by uglyeoin** [comment]
@brianteeman I don't suppose there's an easy way to make sure I'm on the latest version?  I added the custom URL from the nightly builds page to my Joomla! update and it found no updates, I assume that alpha 10 dev doesn't change every day.

**Comment by brianteeman** [comment]
Only by using git.

**Comment by ReLater** [comment]
>  I assume that alpha 10 dev doesn't change every day.

That's wrong. Once a day:

That's what I've learned some weeks ago after understanding it wrong for years ;-)

- Enter custom update server: https://update.joomla.org/core/nightlies/next_major_list.xml in joomla-update options.
- Go to administrator/index.php?option=com_joomlaupdate
- Click "Check for Updates"
- Go to tab "Live Update"
- Click button "Reinstall" even if Joomla tells you "You already have the latest Joomla version"
- Now you have updated to the current nightly.

**Comment by ReLater** [comment]
Have deleted my comment because nonsense if pr not merged yet.
