### ISSUE TITLE
Joomla Menu Start Levels Bug

### ISSUE THREAD

**Issue by lipatovroman** [joomla/joomla-cms#25337]
For example we have 2 menus on site.
First menu have several levels.
Second menu just have 1 item menu.
No any problem. Both menus displays correct.

But we configured menu module to display 1-st menu items only from 2-nd level,
this menu does not displays - if now active menu item from 2-nd menu.

It only displays if own items is active.
Watch this short video:

https://www.youtube.com/watch?v=9cOWwPhYpHI&feature=youtu.be

I used Joomla! 3.9.8 Stable [ Amani ] 11-June-2019 20:00 GMT

**Comment by brianteeman** [comment]
Please use the forum for support https://forum.joomla.org

**Comment by lipatovroman** [comment]
This is message from forum
![Screenshot](https://biblsoft.ru/images/monopics/2019-06-26_14-48-19.jpg "Screenshot")
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25337">issues.joomla.org/tracker/joomla-cms/25337</a>.</sub>

**Comment by ghost** [comment]
> This is message from forum

~~@lipatovroman this is a new Info, reopen. Please give a Link to the Thread so Dev. can read it.~~

This is a Forum rule and if i read @brianteeman correct its not a Bug.

**Comment by lipatovroman** [comment]
Have you seen video?
It's normal behaviour?

**Comment by ghost** [comment]
Please ask on [Forum](https://forum.joomla.org/)

**Comment by HLeithner** [comment]
@lipatovroman yes that's expected behavior.

**Comment by lipatovroman** [comment]
Not clear... 
Menu with all levels displays, menu from 2-nd level not displays.
In same time menu displays in 2 cases if now active from this menu.
It should not be.
How in this case I will get working menu?

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/60190897-53e45780-982b-11e9-8c41-a2a6b30d115e.png)
