### ISSUE TITLE
[4.0] Multilingual: When selecting another menu type in the Select menu item modal the modal reloads the full menu items Manager

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#25342]
### Steps to reproduce the issue
Multilingual site. https://github.com/joomla/joomla-cms/pull/25338 corrected in the test site.
Also patch with https://github.com/joomla/joomla-cms/pull/25341 although it is not necessary if the Select concerns the correct language.

Switching the Menu in the modal should show `No Matching results` if the selected menu does not contain any menu item tagged to the desired language.

### Actual result
It loads the full Manager in the modal

<img width="1383" alt="Screen Shot 2019-06-27 at 09 01 04" src="https://user-images.githubusercontent.com/869724/60244180-24c8f700-98ba-11e9-8c35-d90ea2f6bdc8.png">

@SharkyKZ  @richard67

**Comment by SharkyKZ** [comment]
Bandage fix on the way. But I think there might be more similar issues coming from #24801 in other components. Do we really need those redirects?

**Comment by SharkyKZ** [comment]
Test PR #25345 please.

**Comment by ghost** [comment]
Closed as having Pull Request #25345

**Comment by infograf768** [comment]
#25345 does not fully solve the issue but it is possible that what is does not solve is entirely unrelated.
