### ISSUE TITLE
Article - Global Options: Different Tooltips on 3 Datetypes

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25343]
### Steps to reproduce the issue
As Title say there are this Tooltips:
![publish](https://user-images.githubusercontent.com/8235763/60244552-eaac2500-98ba-11e9-88a7-53e3cefd6991.png)
![modified](https://user-images.githubusercontent.com/8235763/60244554-eb44bb80-98ba-11e9-8be5-cf985d0682bd.png)
![create](https://user-images.githubusercontent.com/8235763/60244556-eb44bb80-98ba-11e9-89b7-c1d84b182816.png)
### Expected result
"Create Date" has correct Tooltip which should be shown in other 2 Dates too.
### System information (as much as possible)
Setting | Value
-- | --
PHP Built On | Linux lamp126.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.5.el6h.x86_64 #1 SMP Thu Nov 22 10:07:47 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.23-cll-lve
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.6
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.9.8 Stable [ Amani ] 11-June-2019 20:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:67.0) Gecko/20100101 Firefox/67.0

**Comment by SharkyKZ** [comment]
These strings are also used when editing articles and article/category menu items. To be completely accurate we probably need separate strings for each occasion. Either that or remove the part about this being a global setting. @infograf768?

**Comment by pau1a** [comment]
> These strings are also used when editing articles and article/category menu items. To be completely accurate we probably need separate strings for each occasion. Either that or remove the part about this being a global setting. @infograf768?

+1 on this. The strings are declared separately and the shorter one is JGLOBAL_SHOW_MODIFY_DATE_DESC

/administrator/language/en-GB/en-GB.ini line 588

Id say separate strings for each is the way

**Comment by ghost** [comment]
Closed as having Pull Request #25554

**Comment by infograf768** [comment]
> These strings are also used when editing articles and article/category menu items. To be completely accurate we probably need separate strings for each occasion. Either that or remove the part about this being a global setting. @infograf768?

I agree.
See my comment here.
https://github.com/joomla/joomla-cms/pull/25556#issuecomment-511309183
