### ISSUE TITLE
[4.0] behavior.tabstate

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25359]
Unless I am completely misreading this then the code for saving the tabstate has been removed as the new tab code doesn't need extra code. If that is correct then we dont need to have `HTMLHelper::_('behavior.tabstate');` in 20+files

**Comment by dgrammatiko** [comment]
True

The tab state is controlled either by  a hash in the url or an attribute in the tabs element

**Comment by SharkyKZ** [comment]
`JHtmlBehavior::tabstate()` is empty in 4.0. Should it be deprecated/removed?

**Comment by brianteeman** [comment]
The "problem" is that while the opened state works ie when you return to a page you are on the same tab what doesnt work is the ability to open a tab directly with a link eg `administrator/index.php?option=com_config#page-permissions`

**Comment by Quy** [comment]
> TypeError: tabLink is null

```
    showTab(tab) {
      const tabLink = document.querySelector(`#tab-${tab.id}`);
      tabLink.click();
    }
```
