### ISSUE TITLE
[4.0] Multilingual Propagate method broken

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#25364]
### Steps to reproduce the issue
Create a multingual site with 4 languages
French, German (de-DE) can be installed at J clean install time or through `index.php?option=com_installer&view=languages`
As Persian is hard to read for most, install Italian through `index.php?option=com_installer&view=install` package tab
[it-IT_joomla_lang_full_3.9.8v1.zip](https://github.com/joomla/joomla-cms/files/3341468/it-IT_joomla_lang_full_3.9.8v1.zip)
English en-GB is present by default.

Then run the Multilingual sample data module in Control Panel.
Then, run the Blog Sample data module after switching to each language in backend.

The test here concerns Menu items but we get the same results for each component.

We have menu items of type `Create Article` in the Author Menu for each language.
Edit the en-GB one and through the Associations tab, create associations to the French and German ones. Save and Close.

Then edit the Italian one. In its Associations tab Select the en-GB `Create a Post (en-GB)`.
Then use the now available `Propagate` button.

### Expected result
The French and German associations should be added.

### Actual result
Only The French one is added.

_In the screenshot below I did not do anything concerning Persian which was already present in my test site. Just ignore it_

![Screen Shot 2019-06-29 at 09 01 43](https://user-images.githubusercontent.com/869724/60380866-8d47dd80-9a4c-11e9-93f7-be16768c41d1.png)

Hint: the process is interrupted and no Message is displayed.

In Console we get this type of error

![Screen Shot 2019-06-29 at 08 59 42](https://user-images.githubusercontent.com/869724/60380845-4c4fc900-9a4c-11e9-810a-842469a94219.png)

**Comment by infograf768** [comment]
I found where is the culprit.
In modal-fields.js the line 196
`Joomla.Modal.getCurrent().close();`
has replaced line 194 in modal-fields-uncompressed.js in J3
`jQuery('#ModalSelect' + itemType + '_' + fieldPrefix).modal('hide');`

If I use the J3 code there, the issue is solved.

No idea how to correct that when not using JQuery

**Comment by infograf768** [comment]
@Fedik @dgrammatiko ?

**Comment by Fedik** [comment]
the problem that I even do not know what `Propagate` button for :smile: 
something new :)

**Comment by dgrammatiko** [comment]
@infograf768 try to open the modal from that Propagate (wtf is this?) and then open the browser's terminal and type `Joomla.Modal.getCurrent()` what's the output?
Also try: `window.parent.Joomla.Modal.getCurrent()`, what's the output?

**Comment by Fedik** [comment]
something with processModalSelect() in media-field, in some reason it tries to close non existing modal

**Comment by Fedik** [comment]
@infograf768 please try to test next:
in `media-field.js` find `window.processModalSelect  = ..`
there change line `Joomla.Modal.getCurrent().close()` to:
```javascript
if (Joomla.Modal.getCurrent()) {
  Joomla.Modal.getCurrent().close();
}
```

**Comment by ghost** [comment]
> the problem that I even do not know what Propagate button for 😄 something new :)
 
Multilingual: Propagating existing associations if desired #21321

**Comment by infograf768** [comment]
@Fedik will try tomorrow

**Comment by infograf768** [comment]
@Fedik
Right on spot!
Making PR now. Thanks.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/25371

Closing as we have a patch
