### ISSUE TITLE
[4.0] Associations: Change Target-Category too if Category is associated

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25375]
### Problem
Copy a Reference Article to a Target change automated the Language, not the associated Category.
### Solution 
Example: Copy Reference Article from de-AT to Target en-GB should also change automated the corresponding Reference-Category "Artikel (de-AT)" to Target-Category "Articles (en-GB)"
as both Categories are associated.

**Comment by infograf768** [comment]
I do understand that this would be a nice improvement indeed.
Not sure how to accomplish it as the code is using save2copy for all types.

**Comment by ghost** [comment]
Got it, just wanted to ask. Maybe another Time.
