### ISSUE TITLE
[4.0] media manager failure message

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25379]
### Steps to reproduce the issue
Change the maximum image size that can be uploaded to 1mb
Try to upload an image that is bigger than 1mb

### Expected result
Error message `This file is too large to upload`

### Actual result
Error message `You are not authorized`

**Comment by pau1a** [comment]
Could somebody advise where the unminified version of mediamanager.min.js is located please

**Comment by alikon** [comment]
should be this one https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_media/resources/scripts/mediamanager.js

**Comment by brianteeman** [comment]
The problem is that the `private function checkContent() `  in `administrator\components\com_media\src\Controller\ApiController.php` is not generating the message and instead it is coming from ` _handleError(error)` in `administrator\components\com_media\resources\scripts\app\Api.js`

**Comment by chmst** [comment]
Just tested on a fresh intallation, with maximun set to 1mb. 

1. Uploading a bigger image results in the error as described by @brianteeman 

2. Repating the Upload with another big image. I got "Item uploaded." but nothing was uploaded.

3. Repeating with a very small image. I got "Item uploaded." but nothing was uploaded.

Win10, local installation in xampp

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25379">issues.joomla.org/tracker/joomla-cms/25379</a>.</sub>

**Comment by Quy** [comment]
Please test PR #30573
