### ISSUE TITLE
Repeatable custom field with parentheses in field name prevents you from saving article

### ISSUE THREAD

**Issue by crystalenka** [joomla/joomla-cms#25384]
### Steps to reproduce the issue

1. Create a repeatable custom field linked to an article. 
2. Add a form field with parentheses as part of the name. For example, `Caption (optional)`
3. Save, and create a new article.
4. Add content to the custom field.
5. Press save.

### Expected result
I expect the save button to work.

### Actual result
Nothing happens, I can only close.

### System information (as much as possible)
MacOS Mojave 10.14.5
Joomla 3.9.8
local dev server on PHP 7.2.14

### Additional comments
It's definitely the parentheses, as changing the field name to `Caption - optional` makes it work

Console spits out this error:
`Error: Syntax error, unrecognized expression: #jform_com_fields__insights-images__insights-images0__Caption (optional)-lbl jquery.min.js:2:12666`

**Comment by ghost** [comment]
@Quy @richard67 comment?

**Comment by Quy** [comment]
@roland-d

**Comment by SharkyKZ** [comment]
PR #25398 should fix this once it's ready for testing.

**Comment by ghost** [comment]
@SharkyKZ please comment when Pull Request is ready for test so this Issue can be closed.

**Comment by richard67** [comment]
@SharkyKZ I think PR #25398 is ready for testing. Do you agree?

**Comment by SharkyKZ** [comment]
I don't know if it's OK to manually edit minified files, or do we always need to use a minifier. It looks OK on review though.

**Comment by richard67** [comment]
@crystalenka Please test PR #25398 .
