### ISSUE TITLE
[4.0] Smart Search Indexer don´t work

### ISSUE THREAD

**Issue by TobsBobs** [joomla/joomla-cms#25380]
### Steps to reproduce the issue
Install Joomla 4 nightly build, install sample data an run the Smart Search indexer.
Nothing happens but an error message appears in the console. I do not know if the error in the console has anything to do with the indexer.

### Expected result
Content is indexed and Smart Search can be used.

### Actual result
Smart Search Indexer don`t work.

### System information (as much as possible)
php: Windows NT TOBSBOBS 10.0 build 18362 (Windows 10) AMD64
dbserver: mysql
dbversion: 10.3.15-MariaDB
dbcollation: latin1_swedish_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 7.3.6
server: Apache/2.4.39 (Win64) OpenSSL/1.1.1c PHP/7.3.6
sapi_name: apache2handler
version: Joomla! 4.0.0-alpha11-dev Development [ Amani ] 29-June-2019 11:27 GMT
useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0

### Additional comments
![indexer](https://user-images.githubusercontent.com/816779/60401461-1b71b000-9b82-11e9-8e2b-b7bb709c68a4.png)

**Comment by Quy** [comment]
In PHP error log:

> PHP Fatal error:  Class PlgFinderCategories contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Joomla\Component\Finder\Administrator\Indexer\Adapter::setup) in \plugins\finder\categories\categories.php on line 458

**Comment by SharkyKZ** [comment]
Test PR #25381 please.
