### ISSUE TITLE
[4.0] Call to a member function getRootId() on boolean

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#25388]
### Steps to reproduce the issue
I am getting this fatal error on the admin login page. Seems like it came around once a new version is released.
*I set my admin to find J4 updates from the update stream

### Expected result
Admin login form

### Actual result
Error page

### System information (as much as possible)
Joomla 4.0 alpha 8

### Additional comments

Call stack
--
# | Function | Location
1 | () | JROOT/plugins/system/updatenotification/updatenotification.php:331
2 | PlgSystemUpdatenotification->getSuperUsers() | JROOT/plugins/system/updatenotification/updatenotification.php:210
3 | PlgSystemUpdatenotification->onAfterRender() | JROOT/libraries/src/Plugin/CMSPlugin.php:285
4 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() | JROOT/libraries/vendor/joomla/event/src/Dispatcher.php:412
5 | Joomla\Event\Dispatcher->dispatch() | JROOT/libraries/src/Application/EventAware.php:111
6 | Joomla\CMS\Application\WebApplication->triggerEvent() | JROOT/libraries/src/Application/CMSApplication.php:976
7 | Joomla\CMS\Application\CMSApplication->render() | JROOT/libraries/src/Application/AdministratorApplication.php:450
8 | Joomla\CMS\Application\AdministratorApplication->render() | JROOT/libraries/src/Application/CMSApplication.php:247
9 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:63
10 | require_once() | JROOT/administrator/index.php:36

**Comment by ghost** [comment]
Nightly Builds cannot be updated in Alpha. Please install a fresh Build.

**Comment by sakiss** [comment]
1. > Nightly Builds cannot be updated in Alpha. Please install a fresh Build.

Then the Nightly Builds page should be updated as it suggests an update stream for the J4 alphas.
https://developer.joomla.org/nightly-builds.html
Btw. This stream was working perfectly updating all the previous J4 alphas

2. Still this does not solve the error in the first place. 
There is an error in the plugins/system/updatenotification plugin which should be fixed or at least handled.

**Comment by sakiss** [comment]
The error comes from this code:
`Table::getInstance('Asset', 'Table')->getRootId();`

Table::getInstance() returns a Table object or false (when it fails).
Trying to call getRootId() from a boolean causes a fatal error.

Possibly some type check should be preceded.
```
$table=Table::getInstance('Asset', 'Table');
if($table===false) {
return $ret;
}
$rootId=$table->getRootId();
```

**Comment by SharkyKZ** [comment]
Test PR #25390 please.

**Comment by sakiss** [comment]
PR #25390 fixes it

**Comment by ghost** [comment]
@sakiss  please mark your test as successfully (how to: https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results)
