### ISSUE TITLE
Subform - Wrong ID generated for the elements of subform when we click on Plus (+) button to add repeated subform

### ISSUE THREAD

**Issue by ankush-maherwal** [joomla/joomla-cms#25387]
### Steps to reproduce the issue
1) Add a subform field (repeatable) in any form and set the value of "min" attribute of subform field as 1
2) Name one of the input field in the subform as (repetable_subform-test). i.e use hyphen in the name of the input field.
3) For the first i.e the default block of repeatable subform the id of the input field with a hyphen in the name will be generated as **"jform_com_tjucm_sample_subform__com_tjucm_sample_subform0__repetable_subform_test"** as Joomla replaces all the non-word characters with (_) underscore for the attribute Id of all the fields (as per getId function in FormField class)
4) After clicking on the plus (+) button to add the repeatable block the id of the field with a hyphen in the name the id is generated as **"jform_com_tjucm_sample_subform__com_tjucm_sample_subform1__repetable_subform-test"** i.e the id contains hyphen as the hyphen is not replaced with an underscore in the code of subform-repetable.js file

### Expected result
The id of the field in subform was expected to be without any hyphen in it **"jform_com_tjucm_sample_subform__com_tjucm_sample_subform1__repetable_subform_test"**

### Actual result
The id of the input element contains hyphen if the field name contains a hyphen 
**"jform_com_tjucm_sample_subform__com_tjucm_sample_subform1__repetable_subform-test"**

### System information (as much as possible)
Latest Joomla

### Additional comments
getId() function in class FormField has the code which replaces all the non-word characters in the id of an element to underscore.

Such code is missing in the "subform-repeatable.js" which generated the clone of the fields in the subform

**Comment by ReLater** [comment]
Just a question: Does this behavior lead to any issues/errors/malfunctions?

**Comment by ankushmaherwal** [comment]
No, this behavior does not leads to any issue or error in Joomla core but the behavior is not gerneric in both the cases i.e Standard form and the sub-form which leads to difficulties for the extension developer to predict the behavior and impliment the solutions of thair problems.

**Comment by alikon** [comment]
please test #25398<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25387">issues.joomla.org/tracker/joomla-cms/25387</a>.</sub>
