### ISSUE TITLE
Frontend Site Configuration error on save

### ISSUE THREAD

**Issue by conseilgouz** [joomla/joomla-cms#25385]
### Steps to reproduce the issue

Create a menu type "Configuration manager", "Site Configuration options", access "Super User". Go to FrontEnd and log as superuser. Site Configutration is displayed and may be updated. Click on Save button

### Expected result

Config. updated

### Actual result

When clicking on "Save", Error 0 - Call to a member function filter() on boolean

1 | () | JROOT\components\com_config\model\form.php:296
-- | -- | --
2 | ConfigModelForm->validate() | JROOT\administrator\components\com_config\controller\application\save.php:66
3 | ConfigControllerApplicationSave->execute() | JROOT\components\com_config\controller\config\save.php:88
4 | ConfigControllerConfigSave->execute() | JROOT\components\com_config\config.php:27
5 | require_once() | JROOT\libraries\src\Component\ComponentHelper.php:402
6 | Joomla\CMS\Component\ComponentHelper::executeComponent() | JROOT\libraries\src\Component\ComponentHelper.php:377
7 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\SiteApplication.php:194
8 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT\libraries\src\Application\SiteApplication.php:233
9 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:196
10 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\index.php:49

### System information (as much as possible)

Joomla 3.9.8

### Additional comments

New lines in administrator/com_config/controller/application/save.php in Joomla 3.9.4 : https://github.com/joomla/joomla-cms/commit/bbdf775fbee26d275ce60ea466b778e4694210a1#diff-895e4b6b20845e2bd3a76e72ecc20fed

**Comment by pmleconte** [comment]
Wrong stack : 

Call stack
--
# | Function | Location
1 | () | JROOT\components\com_config\model\form.php:296
2 | ConfigModelForm->validate() | JROOT\administrator\components\com_config\controller\application\save.php:66
3 | ConfigControllerApplicationSave->execute() | JROOT\components\com_config\controller\config\save.php:88
4 | ConfigControllerConfigSave->execute() | JROOT\components\com_config\config.php:27
5 | require_once() | JROOT\libraries\src\Component\ComponentHelper.php:402
6 | Joomla\CMS\Component\ComponentHelper::executeComponent() | JROOT\libraries\src\Component\ComponentHelper.php:377
7 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\SiteApplication.php:194
8 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT\libraries\src\Application\SiteApplication.php:233
9 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:196
10 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\index.php:49

Pascal

**Comment by ghost** [comment]
Issue confirmed.

**Comment by infograf768** [comment]
Informed the powers that be.

**Comment by ghost** [comment]
> Informed the powers that be.

Means?

**Comment by infograf768** [comment]
JSST

**Comment by franz-wohlkoenig** [comment]
Should be informed or is informed?

**Comment by HLeithner** [comment]
We have a PR https://github.com/joomla/joomla-cms/pull/25404 closing...
