### ISSUE TITLE
[4.0] Choicesjs empty list on mobile

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25396]
I thought this was a problem with the choices/js code that it is not showing the select list on a mobile device but it must be something about the Joomla implementation as the authors demo.

Compare the select input demo on a mobile device https://joshuajohnson.co.uk/Choices/
With the module position select in joomla on a mobile device

**Comment by brianteeman** [comment]
I might have stumbled onto a known chromium bug that was fixed today.

**Comment by Fedik** [comment]
I not sure, but can you please check if  #25676 helps
