### ISSUE TITLE
JForm showon attribute does not work in foreach ($this->form->getFieldset() as $field) rendering

### ISSUE THREAD

**Issue by ayazbaloch** [joomla/joomla-cms#25408]
shown attribute does not work if fields render through foreach loop such as
<?php foreach ($this->form->getFieldset() as $field): ?>
          <div class="control-group">
                         <div class="control-label"><?php **echo $field->label;** ?></div>
                        <div class="controls"><?php **echo $field->input;** ?></div>
                        </div>
<?php endforeach; ?>

while it works when fields render such as **<?php echo $this->form->renderField('fieldname'); ?>**

**Comment by ghost** [comment]
Which Version?

**Comment by SharkyKZ** [comment]
I think this is expected behavior at the moment. If you're rendering input and label manually, you also have to handle showon. See this for example:

https://github.com/joomla/joomla-cms/blob/fea05e25c831166b7a17af3976abaf3307e8bb8d/layouts/joomla/searchtools/default/filters.php#L20-L26

**Comment by richard67** [comment]
SharkyKZ is correct. I think this issue can be closed as expected behavior. No need for more info about version.

**Comment by ayazbaloch** [comment]
Thanks dear @SharkyKZ  for elaborating it.

**Comment by ayazbaloch** [comment]
Dear @SharkyKZ , I think this should be mentioned in Joomla Document.

**Comment by ghost** [comment]
@ayazbaloch JDoc is a wiki, so please append the wanted Information, thanks.

**Comment by ayazbaloch** [comment]
Thanks @franz-wohlkoenig for guiding.
