### ISSUE TITLE
Multilanguage Status: Misleading Warning on Contact

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25415]
### Steps to reproduce the issue
- Have a multilanguage Page using 2 Languages (en-gb, de-at) setup properly including Contacts for each Language for 2 Users 
- Install de-ch as Content language + activate it

After Activation joomla show this (blue) Warning:
![Screen Shot 2019-07-03 at 13 50 34](https://user-images.githubusercontent.com/8235763/60589727-7da4fd80-9d9a-11e9-94ae-48ff4ca9ba93.png)
### Expected result
No (blue) Warning cause no Contact is assigned to "All".
### System information (as much as possible)
Setting | Value
-- | --
PHP Built On | Linux lamp126.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.5.el6h.x86_64 #1 SMP Thu Nov 22 10:07:47 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.23-cll-lve
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.6
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.9.8 Stable [ Amani ] 11-June-2019 20:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:67.0) Gecko/20100101 Firefox/67.0

**Comment by SharkyKZ** [comment]
Have you created a contact for de-CH language?

**Comment by ghost** [comment]
No, only the 3rd Language is activated.

**Comment by SharkyKZ** [comment]
If I understand correctly, this is expected. Need to create a contact for any newly installed languages to fulfill the condition:
>Warning! A user/author should have only one contact to which is assigned language 'All' **OR one contact for each published Content Language**.

**Comment by ghost** [comment]
This Warning is only on Contact, not on Menu, Categories, ...

**Comment by infograf768** [comment]
Not a bug. Warning is fine. The issue will never occur for another component than contacts.
The reason is that we have here a specific parameter which is the user name. In a multilingual site when one clicks on Written by, it should work whatever the Content Language used.

**Comment by ghost** [comment]
Got it, thanks @infograf768 and @SharkyKZ for Discussion.

**Comment by brianteeman** [comment]
Should it not be class="warning" not info - espec as the text begins with "Warning" ??

**Comment by richard67** [comment]
I followed the testing instructions but I don't get that warning. It seems it really needs some special starting conditions beside those mentioned in the description.

**Comment by ghost** [comment]
@richard67 the Warning is expected Behaviour. Its now about "Should it not be class="warning" not info - espec as the text begins with "Warning" ??" as @brianteeman wrote.

**Comment by richard67** [comment]
yes i know and wanted to correct it, but cant's test because can't get the warning, and we shall not make untested PR's :tongue:

**Comment by ghost** [comment]
got it :-)

**Comment by richard67** [comment]
@brianteeman To be honest, I am not sure what is better: Change class and icon so the message has warning icon and color, or leave class and icon as it is but remove text "Warning! " at beginning of the language string, or even both together for maximum consistency, because the other messages in that view, e.g. the top one in the screenshot, have warning icon and class, but their language strings don't start with text "Warning! ".

What do you recommend?

**Comment by richard67** [comment]
@franz-wohlkoenig Please test PR #25426 .
