### ISSUE TITLE
Link Class. An optional class to apply to the menu hyperlink.

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25425]
### Steps to reproduce the issue

Try to find An optional class to apply to the menu hyperlink.

### Expected result

Get all Link Class.

### Actual result

Zero real example of what Link Class

### System information (as much as possible)

protostar joomla latest

### Additional comments
please dont suggest your forum couse your forum is dead, no one answers questions there

**Comment by SniperSister** [comment]
Duplicate of #25423

**Comment by Milglius** [comment]
David Jardin thank you for suggestion to use wordpres cms couse your answers are useless and Joomla cms is still abandonware and outdated cms

**Comment by brianteeman** [comment]
Actually the problem is that you are not understanding the css 

the option in the menu adds a class to the `li`
what you are trying to target the `a` inside the `li`

so what you need to do is add the class to the menu link as you presumably have already done
then in your css you will create something like

`.newmenuclass a:hover, .newmenuclass a:focus`

**Comment by Milglius** [comment]
@brianteeman yes I am still trying to be friends with css thats why this is feature request couse now its very dificult :(

Where I need to put this .newmenuclass a:hover, .newmenuclass a:focus  ?

Here are the questions
So what I need to write in Link Class field ?

What css file I need to create and where to put it ?

I created user.css put it in css directory of protostar template

#sub-navigation-home li.sub-navigation-home-news a 
{
 color: #C1C1C1;
 font-family: arial;
 text-align: center;
 text-transform:uppercase; 
}

but it doesnt work in joomla menu item id nothing changes in it :(

@brianteeman thanks in adwance for your real help, it seems like to you its very simple :)

**Comment by brianteeman** [comment]
Sorry but this is a topic for the forum I wont be replying further here

**Comment by Milglius** [comment]
Sorry but Brian Teeman thank you for suggestion to use wordpres cms couse your answers are useless and Joomla cms is still abandonware and outdated cms

Sorry but it seems like even to you brian teeman joomla cms is very dificult to use  :( Very sad what abandonware and outdated cms joomla become. Good that we still can use good modern Wordpress cms.

Bye sorry for my questions about joomla , **it seems like its almoust imposible to change colour of menu item id in joomla cms** or it is well guarded secret by joomla developers and cofaunders, very strange ant not encouraging to use Joomla cms as abandonware and outdated cms

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/issues/25423#issuecomment-508720963

**Comment by ghost** [comment]
@Milglius please stay in joomla-repositories focussed on issue, thank you.
