### ISSUE TITLE
Feature request Menus: Items ID colour change Protostar template

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25423]
Menus: Items Protostar template

### Steps to reproduce the issue

Try to make this menu item - text colour white and surounding pink colour
Link Class no reaction

### Expected result

We want to change ony this id - Registratia2, but all other menus and ID must stay as they where before .

Try to make this menus item only 1 ID - text colour white and surounding pink colour, and then you drag mouse pointer it goes dark pink colour text white

### System information (as much as possible)

Joomla 3,9,8, PHP 7.2

### Additional comments

If you know documentation or something like this can be dome withour fr please provide info

**Comment by alikon** [comment]
please ask on [forum](https://forum.joomla.org/ "forum")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25423">issues.joomla.org/tracker/joomla-cms/25423</a>.</sub>

**Comment by Milglius** [comment]
@alikon please dont suggest this couse your forum is dead, no one answers questions there

Please reopen this is Feature request

**Comment by Milglius** [comment]
David Jardin thank you for suggestion to use wordpres cms couse your answers are useless and Joomla cms is still abandonware and outdated cms

is Nicola Galgano also sugestion to use Wordpres cms, if yes ok and bye We ll use Wordpress cms for our project

**Comment by alikon** [comment]
@Milglius this is an issue tracker and not an helpdesk 
an usefull starting learnig point  https://docs.joomla.org/Special:MyLanguage/J3.2:How_to_use_the_Template_Manager#Creating_Overrides

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/issues/25425#issuecomment-508569616

**Comment by Milglius** [comment]
@alikon thanks for trying to help me but information in your link is outdated and doesnt work

it seems like its almoust imposible to change colour of 1 menu item id in joomla cms

**Comment by Milglius** [comment]
Nicola Galgano sorry but this is real issue and joomla cms dosn't have helpdesk :(

it seems like its almoust imposible to change colour of 1 menu item id in joomla cms even for joomla developers and joomla developers think its good to close real issues rather then solve them, very sad and sorry for joomla but Joomla cms is now abandonware and outdated cms with hundreds and maybe thousands closed but unsolved issues. :(

We ll use modern Wordpress cms for our project :)

**Comment by brianteeman** [comment]
30 seconds work
add a link class to the menu item of pink
add the css required 
```
a.pink {
    background-color: pink;
    color: white;
}

a.pink:hover {
    background-color: deeppink!important;
}

```

![mm2](https://user-images.githubusercontent.com/1296369/60718186-e8317700-9f1b-11e9-8733-fed2e1e2f2bd.gif)

**Comment by Milglius** [comment]
Brian you are genius. This is what I wanted to have. Maybe I am dumb as a nut but I think its something very very simple I still dont understand, I spent on this issue 5 weeks and still no results :((( and you did it in 30 seconds.

Can you please also share your secret and show gif image how you do these 2 steps?
1. add a link class to the menu item of pink (What and exaactly and where you write it)
2. add the css required (What exactly and where you write it)

Cause what I did is something wrong but I still dont understand what I did wrong in
Templates: Customise (Protostar)
I created file "/css/user.css" in template "protostar". 
added your code 
a.pink {
    background-color: pink;
    color: white;
}

a.pink:hover {
    background-color: deeppink!important;
}

and  in Menus: Edit Item Link Type Link Class field write this file name user.css

But nothing happen :((

**Comment by brianteeman** [comment]
it says class name - it does not say file name

**Comment by ghost** [comment]
@Milglius please ask on [Forum](https://forum.joomla.org/) as this Repository is for coding.

**Comment by ghost** [comment]
Brian thanks I was very wrong my deepest apologation to all developers.
