### ISSUE TITLE
[4.0] Modify Module on Frontend: "Call to a member function getType() on null"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25435]
### Steps to reproduce the issue

1. Unpublish Module on Frontend
2. Save and Close
3. got ```{"error":true,"code":0,"message":"Call to a member function getType() on null"}```

![Screen Shot 2019-07-05 at 06 05 04](https://user-images.githubusercontent.com/8235763/60697644-93760800-9eeb-11e9-8881-d696b00870bc.png)

- Same if Module get trashed or "Save" is clicked
- Same if Module get a new Position
### System information (as much as possible)

Setting | Value
-- | --
php | Linux lamp128.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.5.el6h.x86_64 #1 SMP Thu Nov 22 10:07:47 EST 2018 x86_64
dbserver | mysql
dbversion | 5.7.23-cll-lve
dbcollation | utf8_general_ci
dbconnectioncollation | utf8mb4_general_ci
phpversion | 7.3.6
server | Apache
sapi_name | cgi-fcgi
version | Joomla! 4.0.0-alpha11-dev Development [ Amani ] 29-June-2019 11:27 GMT
useragent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:67.0) Gecko/20100101 Firefox/67.0

**Comment by SharkyKZ** [comment]
Coming from #25148. Specifically this change https://github.com/joomla/joomla-cms/pull/25148/commits/2ee908bfaedf135a6f405e1e296a73f843696d83#diff-25f87817fcc874d876290c1acc9440f5R95

@wilsonge

**Comment by Quy** [comment]
Duplicate #27283
