### ISSUE TITLE
[4.0] media manager create folder

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25430]
When you click on the create folder button a popup appears.
You then enter the folder name you want to create and click on create
The new folder is now created and you get a success message
### BUT
The popup stays open. I would expect it to close

![mm](https://user-images.githubusercontent.com/1296369/60687214-14f67780-9ea5-11e9-9360-9bc258e7d4ef.gif)

**Comment by Quy** [comment]
Unable to replicate with the latest nightly build using Firefox 67.0.4 and Chrome Version 75.0.3770.100 on Windows 10.

**Comment by brianteeman** [comment]
still happens for me with Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by pau1a** [comment]
Unable to replicate using Safari Version 12.1 (12607.1.40.1.5) on MacOS Sierra 10.12.6

**Comment by brianteeman** [comment]
Really confused now. Obviously it was happening as I made the video. But no one else can replicate it and now I cant either. So I am going to close it for now
