### ISSUE TITLE
[4.0] CMS Content in frontend - The requested page can't be found

### ISSUE THREAD

**Issue by twister65** [joomla/joomla-cms#25444]
### Steps to reproduce the issue
Edit an article in frontend.
Click on CMS Content in the editor and click on:
- Article
- Contact
- Menu
- Module

### Expected result
- List of articles for Article
- "No Matching Results" information message or list fo contacts for Contact
- List of menus for Menu
- List of modules for Module

### Actual result
![article_error](https://user-images.githubusercontent.com/26852967/60752541-36e81b00-9fc7-11e9-89cf-556cf77c425e.png)
![contact_error](https://user-images.githubusercontent.com/26852967/60752544-3ea7bf80-9fc7-11e9-92ea-7200f3e778d1.png)
...

### System information (as much as possible)
Joomla_4.0.0-alpha11-dev-Development-Full_Package.zip | Saturday, 06 July 2019 02:00:58 UTC

Database Version | 10.3.16-MariaDB-1:10.3.16

PHP Version | 7.2.19-0ubuntu0.18.04.1

### Additional comments
No error in backend (edit an article in the admin interface).

**Comment by ghost** [comment]
Please have a Look if this already reported at #23510, #23979

**Comment by twister65** [comment]
Thx @franz-wohlkoenig, issue #23510 has already reported this bug.
Closed as having Pull Request #25367.
