### ISSUE TITLE
Not possible to move the "edit profile" on the front-end to certain category

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25441]
### Steps to reproduce the issue
Not possible to move the "edit profile" on the front-end to a specific section on site

index.php?option=com_users&view=profile&layout=edit&Itemid=101

Once the user login after registration ! They automatically redirected to the edit profile page on main page but we need to to redirect them to sertain category.

### Expected result

we need to redirect them to sertain specific category not the main page.

### Actual result

Once the user login after first registration! They automatically redirected to the edit profile page on main page

### System information (as much as possible)

j3.9.8 , php7.2

### Additional comments
Redirect Message
Edit Your Profile
This is the message that is displayed to existing users when they login for the first time since the Privacy Consent plugin was enabled on the site.

**Comment by brianteeman** [comment]
1. Thats expected behaviour so that they can complete the details on the privacy plugin
2. Once thats done it wont happen again and you can redirect them how you want see https://docs.joomla.org/How_do_you_redirect_users_after_a_successful_login%3F

**Comment by ghost** [comment]
is there a way to change the position of that module ?

couse now this module is on the bottom of the site and users cant see it couse they need to scroold down a lot

**Comment by brianteeman** [comment]
sorry but I can't guess what you are referring to as I cant see your site. But once again this is a forum issue. So please ask the question there. I will not be answering here again. Sorry

**Comment by brianteeman** [comment]
@franz-wohlkoenig @quy please close this

**Comment by SharkyKZ** [comment]
If you have modules appearing above profile form and want to remove them, create a menu item for Edit User Profile view and unassign the modules for this menu item.

**Comment by ghost** [comment]
Yes I have modules appearing above profile form and want the profile form appearing above modules

**Comment by ghost** [comment]
How to unassign the modules for this menu item Edit User Profile

**Comment by brianteeman** [comment]
@Milglius use the forum please !!!

**Comment by ot2sen** [comment]
@Milglius There is a tab 'Module Assignment' in the edit mode of the menu item, where you can see which modules are assigned to this specific menu item. Even has a 'Hide unassigned' to make it even more clear. You can click each of the listed modules and then edit them to not show on this item. As Brian said, please  use the forum for any further questions on this topic, thanks :)

**Comment by ghost** [comment]
is it expected behaviour when so that they can complete the details on the privacy plugin but if they dont agree with the terms and want to cancel nothing happens the stay on the same page

cancel button doesnt work

**Comment by SharkyKZ** [comment]
Yes, registered users MUST agree to privacy policy to continue using the site.

**Comment by ghost** [comment]
Yes they must agree, but why we need **cancel buton** there which does nothing?

But if they dont agree, how should they ask to remove thir account from the site?

**Comment by ReLater** [comment]
> Yes they must agree, but why we need cancel buton there which does nothing?

It does something. It redirects again to the confirmation page with a clear message.

> But if they dont agree, how should they ask to remove thir account from the site?

Provide a logout module on the same page. Thus the user can log out and contact you per email or whatever.

All these issues were discussed already in the past and the possibility to log out without redirect to confirmation page was added then.

**Comment by ghost** [comment]
thanks
