### ISSUE TITLE
[4.0] Improve SEO -> Minimize Redirects on Multi-Language Websites

### ISSUE THREAD

**Issue by kartzke** [joomla/joomla-cms#25449]
### Steps to reproduce the issue
Applies to multi-lingual Joomla websites with mod_rewrite and SEF URLs turned on.  

In the Joomla plugin "System - Language Filter", there is an option to "Remove URL Language Code".  See attached screenshot.  

This feature removes the language code from the URL for the websites default language.  So for example, with English set as the default site language, this option would remove /en/ from the URL. 

This feature works as expected.  But the Language Switcher Module is not aware of this option when a user is viewing a non-EN page.

For example, if I am on a page in Thai, the URL might be something like:
- https://www.example.com/th/category/article

If I use the language switcher to change to English, the alternate URL will be constructed with the /en/ language code:
- https://www.example.com/en/category/article

Which then 301 redirects to:
- https://www.example.com/category/article

### Expected result
When the "Remove URL Language Code" feature is enabled, the language switcher module should not include the language code for the default site language.  Using the example above, it should link to this URL

- https://www.example.com/category/article

### Actual result
The language switcher module does include the language code, triggering an unnecessary 301 redirect.  This causes an extra server request, delays the user experience and wastes SEO crawl budget.

### System information (as much as possible)

Setting | Value
Database Type | mysql
Database Version | 5.7.25-log
Database Collation | latin1_swedish_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.6
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.9.8 Stable [ Amani ] 11-June-2019 20:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments
On large websites, this can be an impactful optimisation that helps improve the user experience, optimise server resources and improve SEO by conserving crawl budget and potentially consolidating pagerank.

<img width="1273" alt="Screen Shot 2019-07-06 at 19 28 39" src="https://user-images.githubusercontent.com/713503/60756337-8578d200-a026-11e9-8aac-e25c58292f00.png">

**Comment by ghost** [comment]
Please can a Bug Squad Team-Member answer as this Issue is opened more than 12 hours ago?

**Comment by infograf768** [comment]
afaik we do absolutely need to include the 'sef' prefix when using Remove Language Code, even if the final result is to not display it for Search Engines for the site default language.
The redirects are done on purpose and the switcher is not at stake.
See:
https://github.com/joomla/joomla-cms/blob/staging/plugins/system/languagefilter/languagefilter.php#L461-L478

**Comment by kartzke** [comment]
@infograf768 Thanks for the feedback!  But why is this absolutely needed?  Couldn't the front-end logic be set up to exclude the default language code when that option is enabled?  Joomla seems to operate this way when viewing the site in the default language.

Meaning, if I am viewing a site in English (the default) and I navigate to the language switcher, the URL does not include /en/.  But if I'm on a non-EN page, then the /en/ prefix is included.  So this scenario creates an extra redirect, which is much better than not having it, but still not ideal.

**Comment by infograf768** [comment]
Basically, a new user has no cookie set or the cookie has expired. 
Let's say the default site language is set to en-GB (sef prefix is "en". But the user browser preferred language is set to it-IT (sef is "it")

When this user tries to load `mysite.com/` from somewhere on the web, Joomla checks the browser default language and IF it finds it, redirects to `mysite.com/it/` and NOT to the en-GB version.

same for en-GB if preferred browser language is en-GB, it will redirect to `mysite.com/en/`
Joomla understands that and will modify the url to not display the sef prefix.

Note: It is important to set your site map with the prefix for each language.

**Comment by Slava287** [comment]
As a result, as I understand it, for large sites it is better to leave the display of the prefix for the default language in order to save the crawling budget?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25449">issues.joomla.org/tracker/joomla-cms/25449</a>.</sub>

**Comment by Hackwar** [comment]
This issue should be fixed with #43858. Please have a look and test it.

**Comment by Slava287** [comment]
Big thanks!

**Comment by Slava287** [comment]
Hello. Joomla! 5.2.3 Stable. This doesn't work.
