### ISSUE TITLE
[4.0] Edit account

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25440]
In Joomla 3 the edit account link from the user menu (top right) went to a view of com_admin and not com_users. This caused loads of problems with things like tFA and custom fields not showing up when accessing the user account details via the com_admin link.  

No one came up with a reason/explanation why it was done that way so we killed the com_admin link and changed it to a com_users link.

Today I found the reason it used to be done with com_admin. If a user is a manager then by default they do not have access to com_users so if they try to change their account details from that link they will get a 403

**Comment by SharkyKZ** [comment]
What do we do here? Restore the profile view and try to workaround mentioned issues? Or change permission checks in com_users to allow all users edit their own profiles?

**Comment by brianteeman** [comment]
I tried the edit own response but the menus got a bit funky if you dont have access to the component. Don't remember how exactly

**Comment by SharkyKZ** [comment]
Going to try to restore it. See PR #29251.
