### ISSUE TITLE
[4.0] Feature request: possibility to remove name Registration Confusing

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25479]
### Steps to reproduce the issue

Agreement to the site's Privacy Policy is required.

On registration after you get redirected to to privacy agreement is there posiblity to not display or remove name field in options?

Registration Confusing

Why do we need on registration page to have these 2 fields?

Name

User name

Can we just have user name ?

Couse name is confusing to our users they don't know what name to use then they try login to our site 

### Expected result

See just Username

### Actual result

See Name and Username

### System information (as much as possible)

j3.9.8

### Additional comments

Now its very confusing having Name and Username

**Comment by brianteeman** [comment]
name is their real legal name (obviously not unique)
username can be anything that they want (must be unique)

As this is an agreement it must include the real legal name

**Comment by schnuti** [comment]
You could use a language string override to change the label Name to Real Name or what you like.
No guarantee though, the label Name might be used in another context.

**Comment by brianteeman** [comment]
This should be closed. The current string is the intended behaviour and if a site wants to change it then they can easily create an override

**Comment by ghost** [comment]
closed as stated above.
