### ISSUE TITLE
[3.9] Wrong download links in XMLs

### ISSUE THREAD

**Issue by dmitriy-cloudaccess** [joomla/joomla-cms#25487]
This issue is similar to https://github.com/joomla/joomla-cms/issues/25133 (Can't reopen)
Latest NightlyBuild version is `3.9.10-dev`
https://update.joomla.org/core/nightlies/next_patch_list.xml contains reference to old version `3.9.9-dev`
Update server doesn't work.

**Comment by ghost** [comment]
thanks for Report @dmitriy-cloudaccess, calling @HLeithner

**Comment by HLeithner** [comment]
@zero24 could you check this, we have another release today this get changed too.

**Comment by zero-24** [comment]
This is going to be fixed by: https://github.com/joomla/update.joomla.org/pull/136 as at this time we would have 3.9.11-dev. For that reason I'm closing here. Thanks for the report :)
