### ISSUE TITLE
Install folder removal banner stays

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#25486]
### Steps to reproduce the issue

install latest staging.
after completion click on "remove installation folder"

### Expected result
status will be completed and banner will be gone.
![expected](https://user-images.githubusercontent.com/1850089/61159527-ed656780-a4c1-11e9-91d5-0f463c445342.jpg)

### Actual result
![image](https://user-images.githubusercontent.com/1850089/60939529-a0a14700-a29d-11e9-83af-9941e98e395d.png)

**Comment by richard67** [comment]
I can't reproduce this. After having clicked the button to remove the installation folder, I see:
![Unbenannt](https://user-images.githubusercontent.com/7413183/60996926-ed485900-a355-11e9-9796-e6c99dcd7f61.png)

That means in my case the button has the right text, while the button in your screenshot still has text from before removal.

Ok, that text in the yellow box "PLEASE REMEMBER ..." is silly, but that is an old thing I think, as far as I remember it was always like this.

Could you test again with current staging?

**Comment by Quy** [comment]
I think he wants the yellow box to disappear upon successful installation.

**Comment by richard67** [comment]
Successful installation folder removal you mean, I hope.

**Comment by Quy** [comment]
On second thought, maybe remove the text only in the yellow box after successful removal.

**Comment by richard67** [comment]
Yes, that could be easier and sufficient.

**Comment by N6REJ** [comment]
Just to make sure I wasn't smoking something I repeated the install, using latest clone.
pre-click...
![image](https://user-images.githubusercontent.com/1850089/61011534-8c625600-a340-11e9-90b2-95fc5521a806.png)
post-click
![image](https://user-images.githubusercontent.com/1850089/61011542-93896400-a340-11e9-94dc-3f3b0b346a95.png)
additional clicks not available.

**Comment by pau1a** [comment]
+1 on removing the "PLEASE REMEMBER..." post click as its no longer necessary if the button click has successfully removed the folder

**Comment by pau1a** [comment]
I also can't reproduce this:After clicking the button I see:
![image](https://user-images.githubusercontent.com/291554/61186126-aad69300-a659-11e9-93a7-19638bddf4f8.png)

**Comment by N6REJ** [comment]
@pau1a what LAMP stack are you using?  Recently I had an issue with WSL Ubuntu not updating extensions properly but "Neard" ( wamp clone ) behaving perfectly.

**Comment by pau1a** [comment]
@N6REJ The test I did earlier was on an Ubuntu 16.04.6 LTS box running PHP 7.2.18-1 , Apache/2.4.18 and MYSQL 5.7.26.
I used the Joomla! 3.9.11-dev Development staging build

**Comment by N6REJ** [comment]
the only "major" diff between our builds ( besides platform ) is I did it on ubuntu 18.10(?) and mariadb10.xxx
makes me wonder.....
in Neard I'm getting session error if I switch from mysql 5.7 to maria10

**Comment by N6REJ** [comment]
let me try another install using neard and see if same error pops

**Comment by pau1a** [comment]
any php errors?

**Comment by N6REJ** [comment]
not that I saw... just tested and working fine with latest pull & mysql 5.7  Going to try maria next.

**Comment by N6REJ** [comment]
nope, won't install in mariadb 10.xxxx 
Error
Could not connect to the database. Connector returned number: Could not connect to MySQL server.

**Comment by N6REJ** [comment]
@pau1a just tried with mariadb 5.5.60 and had same failure.

**Comment by N6REJ** [comment]
@pau1a ok, more info.. mariadb was on port 3307 and mysql was on 3306, there is no option for changing ports nor selecting mariadb in J!.  Changing maria to 3306 solved the issue in all forms & versions.
so, it seems this is a wsl specific issue.

**Comment by pau1a** [comment]
Interesting.. I didn't know you were running an external DB.

**Comment by N6REJ** [comment]
http://neard.io it's a variant of wamp
wsl = Windows Subsystem for Linux 
I was trying both as wsl is MUCH faster and lighter then wamp or any vm(ish) method

**Comment by Quy** [comment]
@N6REJ OK to close?

**Comment by N6REJ** [comment]
@Quy yeah,  who knows what kind of flakiness wsl is doing to the kernel.
