### ISSUE TITLE
Feature request: frontend Submit an Article publishing tab not display certain fields

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25491]
### Steps to reproduce the issue
Submit an Article
Try in frontend create article to not display in Publishing tab these fields :
Note
Author's Alias
Access 

### Expected result

You don't see in frontend create article in Publishing tab these fields :

Note
Author's Alias
Access 

### Actual result

You see in frontend create article in Publishing tab these fields :

Note
Author's Alias
Access 

### System information (as much as possible)

j3.9.9

### Additional comments

**Comment by ghost** [comment]
New Features will go in J4, so this is assigned.

**Comment by ghost** [comment]
Joomla 3.9.9 don't have this feature to not display these: ?

Note
Author's Alias
Access

?

**Comment by ghost** [comment]
You wrote in Title "Feature Request", so i comment.

**Comment by ghost** [comment]
Yes its feature request, but as you already know joomla documentation is very bad or I dont know how to use it, So I ask here if somebody knows how to do this in j 3.9.9 if yes it ll be easy to do it in j 4

Franz do you know if such feature is in j 3.9.9 already?

**Comment by brianteeman** [comment]
The feature is there and has been for a very long time
![image](https://user-images.githubusercontent.com/1296369/60963392-90728180-a308-11e9-9ebb-53f3e822a9b3.png)

You have disabled some features in the content options - thats why you dont see the fields.

If you cant find the options to change back to the defaults then please ask on the forum.

There is no bug and no missing feature. Please close.

**Comment by ghost** [comment]
@Milglius thanks for Report, please ask on [Forum](https://forum.joomla.org/)

**Comment by ghost** [comment]
@brianteeman the problem is I see these 3 fields:
Note
Author's Alias
Access

And I want feature not to see these fields.

I see lots of same questions on the forum but still no answer for years. Thats why I think we need this feature.

If you know how to not display just these 3 fields (Note, Author's Alias,Access) please share this information here or on forum.

**Comment by infograf768** [comment]
Hmm. It rather looks like what the original poster want is to NOT display these specific fields in frontend.
The com_content layout let's set `Show Publishing Options` to Hide, this does not work in frontend  for all fields because the forms displayed by the Publishing Tab in frontend are different.

@Milglius
You can create an override for tmpl/edit/form.php in your frontend template where we have (in core for Protostar) the following code
```
<?php echo JHtml::_('bootstrap.addTab', $this->tab_name, 'publishing', JText::_('COM_CONTENT_PUBLISHING')); ?>
				<?php echo $this->form->renderField('catid'); ?>
				<?php echo $this->form->renderField('tags'); ?>
				<?php echo $this->form->renderField('note'); ?>
				<?php if ($params->get('save_history', 0)) : ?>
					<?php echo $this->form->renderField('version_note'); ?>
				<?php endif; ?>
				<?php if ($params->get('show_publishing_options', 1) == 1) : ?>
					<?php echo $this->form->renderField('created_by_alias'); ?>
				<?php endif; ?>
				<?php if ($this->item->params->get('access-change')) : ?>
					<?php echo $this->form->renderField('state'); ?>
					<?php echo $this->form->renderField('featured'); ?>
					<?php if ($params->get('show_publishing_options', 1) == 1) : ?>
						<?php echo $this->form->renderField('publish_up'); ?>
						<?php echo $this->form->renderField('publish_down'); ?>
					<?php endif; ?>
				<?php endif; ?>
				<?php echo $this->form->renderField('access'); ?>
				<?php if (is_null($this->item->id)) : ?>
					<div class="control-group">
						<div class="control-label">
						</div>
						<div class="controls">
							<?php echo JText::_('COM_CONTENT_ORDERING'); ?>
						</div>
					</div>
				<?php endif; ?>
			<?php echo JHtml::_('bootstrap.endTab'); ?>
```
As you see you can modify there what does not fit for you.

**Comment by brianteeman** [comment]
https://brian.teeman.net/joomla/867-simplifying-joomla-content-editing-part-1
https://brian.teeman.net/joomla/868-simplifying-joomla-content-editing-part-2
https://magazine.joomla.org/issues/issue-sept-2014/item/2293-creating-an-article-in-joomla-has-never-been-this-easy

**Comment by ghost** [comment]
@infograf768 You are right I want to NOT display these specific fields in frontend Submit an Article.

Where I can find this file
**tmpl/edit/form.php** in frontend template (in core for Protostar)

**Comment by infograf768** [comment]
It does depend on your template. For Protostar you can do it this way:
Copy the file `ROOT/components/com_content/views/form/tmpl/edit.php`
Then create or make sure you have in your template in the html folder the following structure where you have copied the edit.php file (if there is already one, edit it to fit your needs). Protostar has none, so I created it.
<img width="170" alt="Screen Shot 2019-07-10 at 17 13 29" src="https://user-images.githubusercontent.com/869724/60981201-2b358500-a336-11e9-8bd9-0e668682f696.png">

To reflect your needs here is a modified edit.php file (uncompress) for Protostar.
[edit.php.zip](https://github.com/joomla/joomla-cms/files/3378223/edit.php.zip)

Which gives
<img width="660" alt="Screen Shot 2019-07-10 at 17 22 35" src="https://user-images.githubusercontent.com/869724/60981927-887e0600-a337-11e9-9fa6-f24f0febbad4.png">

Please next time ask on forum.
