### ISSUE TITLE
Joomla Upgrade - 3.9.9 - Template style replicated

### ISSUE THREAD

**Issue by joeblack41** [joomla/joomla-cms#25492]
### Steps to reproduce the issue
After upgrade Joomla, all my websites have template style replicated several times with the same ID. 

On DB is all normal.
The only style that is not replicated is the default style.
If i delete one, all get's deleted.![screen shot 2019-07-10 at 10 45 43](https://issues.joomla.org/uploads/1/b60ece6a02b55d255e3442edee8ecf36.jpg)

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/issues/25482

**Comment by ghost** [comment]
closed as allready reported.
