### ISSUE TITLE
[4.0] Behavior.multiselect [js] [regression]

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25500]
Can someone more intelligent than me confirm/deny that these doc blocks are correct

My assumption from the doc block is that multiselect would allow me to click on row1 and the shift click on row8 and that would select all rows 1 though 8.

**updated:**  _Checked in joomla 3 and my assumption was correct - its just not working in j4_

https://github.com/joomla/joomla-cms/blob/42067d565666ac51d01b8b96d422e294cc494da4/libraries/cms/html/behavior.php#L143

https://github.com/joomla/joomla-cms/blob/42067d565666ac51d01b8b96d422e294cc494da4/build/media_source/system/js/multiselect.es6.js#L24

I can see that there is a event for the shift key in the js but it doesnt do what I expected
https://github.com/joomla/joomla-cms/blob/42067d565666ac51d01b8b96d422e294cc494da4/build/media_source/system/js/multiselect.es6.js#L92-L97

**Comment by dgrammatiko** [comment]
Probably a binding is missing in the constructor, eg:
`this.onRowClick = this.onRowClick.bind(this);`

**Comment by brianteeman** [comment]
js is all greek to me - i am just reporting

**Comment by brianteeman** [comment]
Sorry I tried to understand the js to fix this but it's still all greek to me

**Comment by infograf768** [comment]
`this.onRowClick = this.onRowClick.bind(this);` is present in multiselect.js

**Comment by Fedik** [comment]
It seems that while migration from jquery, this part of code was lost:
https://github.com/joomla/joomla-cms/blob/22f096ed68914245f1867e64f07d51f1cf4dedbf/media/system/js/multiselect-uncompressed.js#L25-L36

**Comment by richard67** [comment]
Hmm to me it seems multiselect is broken at least in 4.2, it not also on 4.1 (not tested yet). See my comment here: https://github.com/joomla/joomla-cms/pull/37379#issuecomment-1079666593

On 3.10.6 it works.

Update: Just read the issue completely and so I can just confirm it.

**Comment by Fedik** [comment]
Please test https://github.com/joomla/joomla-cms/pull/42330
