### ISSUE TITLE
[4.0] Mass Mail js errors

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25509]
Go to Mass Mail Users `administrator/index.php?option=com_users&view=mail`

Complete the form and try to send

### Expected
Email is sent and some sort of success message (or even a fail message)

### Actual 
Nothing happens at all. No visible error message
Checking the JS console

admin-users-mail.min.js?70a249800046311618a4b736a004dcad:1 Uncaught TypeError: 

```
Joomla.getSelectedValue is not a function
    at Object.Joomla.submitbutton (admin-users-mail.min.js?70a249800046311618a4b736a004dcad:1)
    at HTMLElement.executeTask (joomla-toolbar-button.min.js?70a249800046311618a4b736a004dcad:1)
    at HTMLElement.<anonymous> (joomla-toolbar-button.min.js?70a249800046311618a4b736a004dcad:1)
```

**Comment by infograf768** [comment]
That function has been deprecated in 4.0 from core.js
```
window.getSelectedValue = function ( frmName, srcListName ) {
		console.warn('window.getSelectedValue() is deprecated without a replacement!');

		var srcList = document[ frmName ][ srcListName ],
		    i = srcList.selectedIndex;

		if ( i !== null && i > -1 ) {
			return srcList.options[ i ].value;
		} else {
			return null;
		}
	};
```

**Comment by brianteeman** [comment]
guess thats the bug then

**Comment by infograf768** [comment]
I may have a solution. Testing now.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/25517

Closing as we have a patch
