### ISSUE TITLE
[4.0] mail options

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25508]
### Steps to reproduce the issue
In global configuration the defaults are for send mail yes and disable mass mail no
![image](https://user-images.githubusercontent.com/1296369/61006441-3f8f7700-a362-11e9-87ad-49a730cfc3c1.png)

### Test 1
Send mail no
![image](https://user-images.githubusercontent.com/1296369/61006571-91d09800-a362-11e9-900c-a1d18a0d549e.png)
Note that you cant now change the mass mail setting as its hidden so its just the defaault

### Test 2
Send mail yes - disable mass mail yes
![image](https://user-images.githubusercontent.com/1296369/61006504-62ba2680-a362-11e9-8702-f8fc44bf2bf5.png)

### Expected result
Mass Mail not displayed in the main menu

#### Test 1
Mass mail still on the menu AND the component opens

#### Test 2
Mass Mail removed from users menu

**Comment by Quy** [comment]
Please test PR #25510.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25508">issues.joomla.org/tracker/joomla-cms/25508</a>.</sub>
