### ISSUE TITLE
Incorrect? configuration in logging regarding remote users ip.

### ISSUE THREAD

**Issue by twrhills** [joomla/joomla-cms#25518]
### Steps to reproduce the issue
Install Joomla behind a reverse proxy which provides both remote_addr and http_x_forwarded_for headers.
Perform a login failure on /administrator
Check the /logs/error.php log

### Expected result
To see the ip address from http_x_forwarded_for reported as the offending IP address.

### Actual result
To see the ip address from remote_addr reported as the offending IP address.

### System information (as much as possible)

N/A

### Additional comments

Not 100% sure if this is a problem or not, I believe that if HTTP_X_FORWARDED_FOR is set this should be treated as overriding REMOTE_IP, this is not the case in the following file:

./libraries/src/Log/Logger/FormattedtextLogger.php

Here we see:

        protected function formatLine(LogEntry $entry)
        {
                // Set some default field values if not already set.
                if (!isset($entry->clientIP))
                {
                        // Check for proxies as well.
                        if (isset($_SERVER['REMOTE_ADDR']))
                        {
                                $entry->clientIP = $_SERVER['REMOTE_ADDR'];
                        }
                        elseif (isset($_SERVER['HTTP_X_FORWARDED_FOR']))
                        {
                                $entry->clientIP = $_SERVER['HTTP_X_FORWARDED_FOR'];
                        }
                        elseif (isset($_SERVER['HTTP_CLIENT_IP']))
                        {
                                $entry->clientIP = $_SERVER['HTTP_CLIENT_IP'];
                        }
                }

**Comment by ghost** [comment]
Guess J3

**Comment by SharkyKZ** [comment]
Test PR #25520 please.

**Comment by ghost** [comment]
Closed as having Pull Request #25520
