### ISSUE TITLE
Login error and incorrect admin interface/content

### ISSUE THREAD

**Issue by ljd2484** [joomla/joomla-cms#25526]
### Steps to reproduce the issue
Log into Joomla with regular login credentials: email and password (accesses by typing administrator at the end of website url)

### Expected result
Successfully logged in, showing normal admin interface with current, up to date content (articles, media, items, etc)

### Actual result
Login error
Use of undefined constant JAUTHENTICATE_STATUS_FAILURE - assumed 'JAUTHENTICATE_STATUS_FAILURE' (this will throw an Error in a future version of PHP) in /home/forge/www.cg-la.com/plugins/authentication/facebook/facebook.php on line 98
Says user and password do not match or you don’t have an account yet.
Had to get access again by creating an admin account again, only to see when logged into admin interface that everything past January 2019 has been deleted (modules, items, articles, media, etc.)

### Additional comments
Hosted by Cloudflare and Amazon Web Services, tried to reboot server through Media Temple but still shows the old website. Trying to figure out how I can restore it back to where it was and whether or not this is fixable through Joomla/caused by Joomla?

**Comment by ghost** [comment]
Please ask on [Forum](https://forum.joomla.org/) as this Repository is for coding.
