### ISSUE TITLE
[4.0] Some files missing on Windows when updating

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#25531]
### Steps to reproduce the issue

Install nightly.
Update or reinstall.
Visit com_config.

### Expected result

Works.

### Actual result

> Invalid controller class: display

### System Information

4.0 nightly
Windows

### Additional comments

Coming from https://github.com/joomla/joomla-cms/commit/0f83986d1b95eb7e37881f1240b3e79b1a125558

@wilsonge I think this will require some case sensitive handling like discussed in #23725.

The following folders are deleted but they're supposed to exist in 4.0 with different casing:
```
/administrator/components/com_config/controller
/administrator/components/com_config/helper
/administrator/components/com_config/model
/administrator/components/com_config/view
/components/com_config/controller
/components/com_config/model
/components/com_config/view
```

**Comment by wilsonge** [comment]
Yah that would make sense. Not sure how to handle those cases :/ Will also be an issue for those upgrading from j3 to j4

**Comment by mbabker** [comment]
The top level `src` directory in a component would actually help here.

**Comment by SharkyKZ** [comment]
`plugins/system/stats/Field` is also missing.

**Comment by wilsonge** [comment]
> plugins/system/stats/Field is also missing.

Any namespaced plugins with fields are going to fail 🤦‍♂

**Comment by wilsonge** [comment]
Patch moving to the subdirectory for com_config https://github.com/joomla/joomla-cms/pull/27481. Plugin fields still to be solved

**Comment by SharkyKZ** [comment]
Closing as Stats plugin solved with https://github.com/joomla/joomla-cms/pull/27630.

**Comment by wilsonge** [comment]
Yay! thankyou!
