### ISSUE TITLE
[4.0] Frontend Profile display and Profile edit problem with plg_system_actionlogs

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#25534]
### Steps to reproduce the issue
Log in frontend to get the Profile display.
Then click on Edit.

### Result

PLG_SYSTEM_ACTIONLOGS_OPTIONS
PLG_SYSTEM_ACTIONLOGS_NOTIFICATIONS
PLG_SYSTEM_ACTIONLOGS_EXTENSIONS_NOTIFICATIONS 
 are not translated in Profile display

![Screen Shot 2019-07-12 at 16 43 47](https://user-images.githubusercontent.com/869724/61136814-8dbc8b80-a4c4-11e9-9b99-579eceae5389.png)

It's even worse in Profile edit as the showon is also broken

![plugin_system_actionlogs](https://user-images.githubusercontent.com/869724/61136854-a0cf5b80-a4c4-11e9-8fcc-de3e46f27392.png)

**Comment by infograf768** [comment]
Compare with backend
<img width="963" alt="Screen Shot 2019-07-12 at 16 50 55" src="https://user-images.githubusercontent.com/869724/61137148-4682ca80-a4c5-11e9-82af-1c20a345f586.png">

**Comment by SharkyKZ** [comment]
Bandage PR #25535. Ultimately, though, #17444 needs to be addressed somehow.

**Comment by brianteeman** [comment]
Lets do it properly and not with a bandage. that will only create more work in the long run. Not like it has to be fixed right this minute

**Comment by mbabker** [comment]
The language part could've been fixed 15 months ago if https://github.com/joomla/joomla-cms/issues/17444#issuecomment-385214046 were taken seriously.

**Comment by infograf768** [comment]
#25535 does not fully solve the problem:
<img width="916" alt="Screen Shot 2019-07-13 at 07 39 50" src="https://user-images.githubusercontent.com/869724/61167592-bcc51280-a541-11e9-8eb3-f5dd56b21b62.png">

**Comment by Quy** [comment]
Please confirm that this is no longer an issue.

![25534](https://user-images.githubusercontent.com/368084/77856600-142d1080-71ad-11ea-92af-92b0ce731c35.jpg)

**Comment by Quy** [comment]
Closing as non reproducible.
