### ISSUE TITLE
[4.0] Password stength on installation

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#25547]
Thoughts on adding the password strength meter to the admin account on creation? Whilst it is assumed it should be a secure password newer users may think they have a secure password when they don't and with the controlling the main super user account password I think it would be a logical addition

**Comment by brianteeman** [comment]
its a good idea - go for it

**Comment by dgrammatiko** [comment]
@tonypartridge just resurrect https://github.com/joomla/joomla-cms/pull/23215

**Comment by C-Lodder** [comment]
Good luck getting it merged

**Comment by brianteeman** [comment]
Is this something you are going to work on @tonypartridge

**Comment by tonypartridge** [comment]
Yep will do! Just got a bit rammed with stuff the last week.

**Comment by Quy** [comment]
Related #25914

**Comment by ghost** [comment]
closed in favor of #25914
