### ISSUE TITLE
[4.0] SEO, users like it

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#25555]
This is a simple but highly demanded idea that users like a lot.
Go to NEW article in tab PUBLISHING, it looks like this.

![metas-joomla4](https://user-images.githubusercontent.com/9007607/61187784-38c07700-a676-11e9-8a2f-3f62ee8cdb80.JPG)

If we take the title, the link and the meta description we can show it like this

![google-preview](https://user-images.githubusercontent.com/9007607/61187871-796cc000-a677-11e9-8576-61197935fe5e.jpg)

It is a functionality that is being valued a lot among users and that other cms have no need to install etensions

Thanks.

**Comment by mbabker** [comment]
SERP previews can only be put in core if they can be done in a generic way (so no putting something in that favors Google, there are other search engines in use worldwide).  Better off leaving this to extensions.

**Comment by joeforjoomla** [comment]
Agree with @mbabker 
The Joomla core can't take responsibility to show or simulate a Google preview, this is not something reliable. Indeed a SERP preview can't never be the real one shown by Google so this would be an always wrong thing

**Comment by ghost** [comment]
Thanks for sharing the Idea, @Open2logic. As others comment its not for Core, but Extensions. So closing Issue, it can always reopened if further Discussiosn is needed.
