### ISSUE TITLE
Joomla Articles Category Blog Protostar template Bug

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25552]
### Steps to reproduce the issue

Create article in blog view using frontend

Image is not clicable only title and read more is clicable

### Expected result

Image is clicable (everything in article above read more must be clicable)

### Actual result
![ntitled](https://user-images.githubusercontent.com/43875462/61181168-04739900-a62b-11e9-91f7-8800adf8b519.png)

Image is not clicable only title and read more is clicable

### System information (as much as possible)

Joomla 3.9.9 Protostar

**Comment by richard67** [comment]
Not everything which does not work as you expect it is a bug.

Has that ever worked in past? If so, it is a regression and so of course a bug.

But if it never has worked in past you can't just say it is a bug.

Maybe you should look up in Wikipedia the definition of a bug.

And then, putting always word bug in titles of your issues which in most cases are not bugs looks as if you wanted to lower Joomla's reputation by increasing Google search resuls for Joomla + bug. Maybe it is that what you want?

**Comment by brianteeman** [comment]
@Milglius If you continue to use this issue tracker for support when you should be using the forum we will have no option but to restrict your access

**Comment by richard67** [comment]
@Milglius Do I read right, Joomla version 3.9.9? If so, please update to 3.9.10 and test again.
And do I understand right, when you create the article in backend, it works like you expect it, and when you create the article in frontend, it doesn't work like you expect?

**Comment by ghost** [comment]
@Milglius Please ask on [Forum](https://forum.joomla.org/) as this Repository is for coding.

**Comment by ghost** [comment]
@richard67 if you think not clicable image in joomla is ok and not a bug or not clicable image is not a sign of outdated cms , then yes we have diferent opinions what is a bug in todays cms.  

Regarding bad joomla bug reputation. You lower Joomla's reputation by increasing restrict user access to voice opinion about bugs in joomla. My humble advise to devs instead of copy pasting: go to dead joomla forum ask question and get 0 usefull answer there, better solve real joomla bugs here in github couse its coding bugs

Bug number 1
**Image is not clicable only title and read more is clicable**

![ntitled](https://user-images.githubusercontent.com/43875462/61185378-69e27c80-a661-11e9-90eb-8cb094730005.png)

If you stll think its not a bug or not a sign of outdated cms, thats ok I ll use wordpress, couse there you can get this Clicable image in article out of the box. No big deal, I have done my part informed joomla devs about bug if they choose to ingore joomla bugs thats their way. Wordpres thout its a bug years ago and solved this issue. Now no one could think that getting unclicable image default template could be normal. But I see in joomla protostar its normal, strange to me and seems quite old and dated solution.

**Comment by infograf768** [comment]
Insert image. Select image. Add hyperlink (to where you want the click to direct to) and done. 
Where is the problem or ‘bug’ ?

**Comment by ghost** [comment]
Expected result : then you click on image you should get the same result as if you click on read more or article title.

The problem is you now need adition manual work every time user writes article, thats in my opinion  big joomla bug.

**Comment by brianteeman** [comment]
@Milglius what you want to do is very easy with a template override. WordPress is not Joomla. Joomla is not WordPress. You can not build the same web site

**Comment by ghost** [comment]
@brianteeman I searched joomla forum, documentation and here and couldnt find what need to be changed in protostar template. If it is so easy why no one can provide real solution here or post a link to solution in forum or documentation?

so what template override in protostar need to be done to get this image clicable as title and readmore is ?
![ntitled](https://user-images.githubusercontent.com/43875462/61188142-97d8b880-a683-11e9-8c58-2949c8bc28df.png)

**Comment by brianteeman** [comment]
Sorry but I am not answering support questions here

**Comment by ghost** [comment]
@brianteeman thats ok , you dont need to answer here if you dont want. You can answer in joomla forum, documentation or any place you want. 

If to solve this joomla problem is so easy as brian claims , it should be very easy for any joomla dev to write protostar template override for this. So I hope we ll have at leaste 1 joomla dev who can share protostar template override code here rather then ridiculate joomla user. Thanks for all good will.

**Comment by mbabker** [comment]
@Milglius this GitHub repository is not for end user support requests, please respect the requests of others who have directed you to the forums or other platforms geared toward end user support requests.

**Comment by ghost** [comment]
@mbabker please respect joomla end users. Joomla is very buggy software in my opinion Joomla forums are dead, no real support for joomla end users there. Even on GitHub joomla developers choose to write useless comments instead of charing open source code of protostar template override . Brian said its very easy to do. 

But I see that to ridiculate joomla user brings more joy to joomla devs then to fix jooma bug in github or in forum or other platform.

So I hope we ll have at leaste 1 joomla dev who can share open source protostar template override code here rather then choose the path to ridiculate joomla user. Thanks for all good will.

**Comment by alikon** [comment]
@Milglius  this is the last advice please do not post  support question here, the right place to post support questions is on the forum.

Thanks for your attention

**Comment by infograf768** [comment]
Topic locked. Thanks for your patience.
