### ISSUE TITLE
[4.0] Remove IE fallbacks from calendar

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25565]
As stated in https://volunteers.joomla.org/departments/production/reports/1031-production-dept-meeting-may-28-2019, J4 will no longer support IE11

So the following code can be removed:
https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/system/js/fields/calendar.es5.js#L259-L274

**Comment by ghost** [comment]
Closed as having Pull Request #25569
