### ISSUE TITLE
[4.0] Draggable.js to ES6

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25567]
Convert the draggable script to ES6.

Already done here if anyone wants to open a new PR: https://github.com/joomla/joomla-cms/pull/25227/files#diff-5de13dc8b49ef8469c0f1c2f25cbbbba

**Comment by alikon** [comment]
please test #25573 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25567">issues.joomla.org/tracker/joomla-cms/25567</a>.</sub>
