### ISSUE TITLE
[4.0] Remove [].slice.call() from JS

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25566]
As stated in https://volunteers.joomla.org/departments/production/reports/1031-production-dept-meeting-may-28-2019, J4 will no longer support IE11, therefore we do not require `[].slice.call(...)`

PR submitted to MDN to update the browser support table: https://github.com/mdn/browser-compat-data/pull/4288

**Comment by dgrammatiko** [comment]
@C-Lodder by the book I have to agree with this **but** the CMS **shouldn't** restrict people that want to build sites with support for IE8, 9, 10. Check the stats of your own country's gov.uk: https://twitter.com/TheRealNooshu/status/1145777955571941376

Let me explain a bit myself here: For the backend, it's fine to raise the requirements to evergreen, no arguments there **but** all the front end facing scripts should be available for at least IE11. Things like core.js, validate.js and the fields should be available in ES5.

**Comment by C-Lodder** [comment]
But then you're maintaining code for a browser you don't support. MS will most likely drop support for IE before J5 is released.

**Comment by dgrammatiko** [comment]
J5 is on the horizon?

> But then you're maintaining code for a browser you don't support

Just by making sure that nodelist is iterable doesn't mean that you actually have to do something more for maintainability. Anyways, the project missed the train to align with the current practices, ES6 as plain scripts is wrong, they should be modules, so I don't have strong feelings for anything anymore...
There are way deeper and more significant decisions that will shape the future of J4 than the ES5 compatibility scripts

**Comment by C-Lodder** [comment]
> Just by making sure that nodelist is iterable doesn't mean that you actually have to do something more for maintainability.

True, and I'm not saying iterating over an nodelist using `forEach` is an ES6 feature (cause it isn't), but it's inconsistencies like this that means all JS related PR's will need to be tested in IE11, because there are others out there.

**Comment by C-Lodder** [comment]
Also, this doesn't restrict people at all. It's simply a matter of what's shipped in core. People are of course quite within their right to create an override

**Comment by wilsonge** [comment]
I agree with @dgrammatiko to an extent here. I don't want to make it too hard to build frontend templates on IE. Basically in core we can use the ES6 files natively now. So actually I think we can use this https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#web-standards for the es5 files which will hopefully still be ie11 compat (but not used by core but provided as a service for templates who require it). And that will polyfill nodeList.foreach
