### ISSUE TITLE
Feature request: automaticaly resize article image in Joomla core 

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25564]
### Steps to reproduce the issue

Try to add 5 pictures to joomla article and you easily can get published fronted 1 article with 25 MB size. Joomla claims to be cms but cant even resize image, even GitHub can resize image. Or is 30MB article normal thing thing for joomla? then same article in wordpress is 300KB. Is realy now Wordprees is 100x better then joomla? 

### Expected result

KB

### Actual result

25MB or more MB

### System information (as much as possible)

Joomla 3,9,9

**Comment by micker** [comment]
hello its not a bug ... joomla doesn't rezize on upload (j4 will can) you need add plugin AND adding 25 mg for 5 image you need to teach to your user that not the solution (host can limit this)

**Comment by ghost** [comment]
what plugin you need to resize joomla article image on upload? j4 will be release in 2022 or even maybe later, so j4 is just a wish.

Its realy big huge joomla bug as I said even GitHub resize image, so for joomla cms to be unable to resize image in article is real nonsense.

@micker you need to teach not users but core joomla devs that joomla doesn't rezize on image upload in article and this is big sign of crappy joomla software. Thats why users abandon buggy joomla and just use wordpress with rezize on upload.

**Comment by brianteeman** [comment]
@HLeithner please take some action here - its wasting lots of peoples time

**Comment by ghost** [comment]
@brianteeman its your personal opinion

**Comment by C-Lodder** [comment]
Why can't you simply use an extension or far superior 3rd party service for compression?
If you're using software such as Photoshop or Gimp for your images, then you should be "saving for web" anyway.

> Thats why users abandon buggy joomla and just use wordpress with rezize on upload.

Funny, cause WP vulnerabilities are about as consistent as pigeon sh*t on Trafalgar Square

**Comment by ghost** [comment]
What not abandoned and working plugin you need to use to resize joomla article image on upload?

 I said even GitHub resize image. So Photoshop or Gimp is not an option, then Wordpress can do it on upload.

**Comment by HLeithner** [comment]
@Milglius I really would like to have this feature too but it's not on the timeline atm and I'm sure there are 3rs party addons that can do this for you. I'm personally use my own extension for this. I'm closing this because will not be fixed anytime soon and would be a job for a plugin of the new mediamanger (for example) thx for you understanding.

**Comment by ghost** [comment]
Thats why users abandon buggy joomla and just use Wordpress with image rezize on upload.

Now there are 0 not abandoned and working plugins (please correct me if I am wrong) extensions for joomla article with image rezize on upload.

So Every joomla user should code his extension himself if he dont want to use buggy and outdated core joomla. HLeithner already use his own extension couse he dont like buggy outdated core joomla.

You just need image libraries (like image magik or gd) for php on your server, most have them. So if joomla lacks this simple feature (even GitHub can resize image) it just means joomla is abandoned software. 

Do any Joomla dev know if there are not abandoned release of free open source extension to enable joomla article image rezize on upload?

**Comment by micker** [comment]
@Milglius please learn a little ...
- to be more sympatic
- to help your customer to use internet website ...
if you realy know WP you now that you need plugin to check different number of item for each category view ... that the idea of best CMS in world lol
every cms have his ability if you need more install plugin that the game

**Comment by ghost** [comment]
@micker what you mean be more sympatic? How this is related to the issue?

The question still is what not abandoned release of free open source joomla extension can article image rezize on upload?

**Comment by C-Lodder** [comment]
@Milglius Just because the core doesn't support a feature, does not been it's a bug or outdated. As I stated before, Github do this as it's a 3rd party service. Other 3rd party services do the same, such as Facebook or instead have size limitations.
Joomla is not a service.

If you want to compress images before uploading them to your server, then:

1. Create a plugin, or
2. Download a pre-existing extension, or
3. Use a 3rd party service such as [TinyPNG](https://tinypng.com/), or
4. Use Wordpress if you love it so much

**Comment by ghost** [comment]
@C-Lodder then on joomla main page it should be writen that joomla can't resize article image on upload.

That if joomla user try to add 5 pictures to joomla article and he easily can get published fronted 1 article with 25 MB size or more MB. If joomla user want joomla to resize image on upload joomla user must be software developer and must have programers skills to Create a plugin, or buy a plugin which may not work. Couse there 0 pre existing plugins that are free and open source and not abandoned.

I am searching for 5 months for such extension for joomla with 0 succes rate. And now we dont have money to hire developers or to buy paid extension.

Your suggested TinyPNG have Wordpress extension to use its services but dont have Joomla extension.

As you suggested Wordpress is good solution 
When you upload an image to your website, WordPress will create different sized versions of it (see Settings > Compress JPEG & PNG images). The plugin will compress each of these sizes

**Comment by HLeithner** [comment]
Ok I'm sorry I completly forgot that the j4 mediamanger can resize, crop and rotate out of the box so I'm disable commenting on this.
