### ISSUE TITLE
[4.0] Codestyle(?) fixes in 25451 breaks com_contact

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25574]
### Steps to reproduce the issue
Try to go to contacts in the admin. 

### Expected result
Contact list loads

### Actual result
If no contacts then you get the usual no records 
If there are contacts then you get the error `$i is not allowed to be 0`

### Additional comments
This is because of the changes made in #25451 by @hackwar here
https://github.com/joomla/joomla-cms/blob/566252b47d75c44bfefc6921b8deddd30ef6d91f/administrator/components/com_contact/Service/HTML/AdministratorService.php#L107-L113

As I dont understand the code there I have not done a simple revert - although I note that contacts works as intended if reverted

**Comment by SharkyKZ** [comment]
Reverting is fine.

**Comment by SharkyKZ** [comment]
Test PR #25576 please.
