### ISSUE TITLE
Joomla statistics plugin remains enabled

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#25578]
### Steps to reproduce the issue
Install Joomla
Select never to send stats
Check the Joomla statistics

### Expected result
The Joomla statistics plugin should be disabled

### Actual result
The Joomla statistics plugin is enabled

### System information (as much as possible)
Tested on wamp localhost php 7.2.15

### Additional comments
Also existing sites updated to 3.9.10 (which previously had Never selected) have the plugin enabled

**Comment by mbabker** [comment]
It's intended to remain enabled.  Selecting to never send stats option doesn't arbitrarily disable the plugin, the plugin just knows it will not send any stats up.

**Comment by ghost** [comment]
Closed as expected Behaviour.

**Comment by Webdongle** [comment]
But post install message says
"If you do not wish to provide the Joomla Project with this information you can disable the plugin called System - Joomla Statistics."
That implies that when the plugin is enabled that it collects and sends the statistics.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25578">issues.joomla.org/tracker/joomla-cms/25578</a>.</sub>

**Comment by Webdongle** [comment]
Yes I found the setting in the plugin but the wording in the Post installation message is misleading.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25578">issues.joomla.org/tracker/joomla-cms/25578</a>.</sub>

**Comment by ghost** [comment]
@brianteeman can you please have a look at the "misleading Post installation message"?

**Comment by Webdongle** [comment]
Suggest the word says something like
"If you do not wish to provide the Joomla Project with this information you can edit the settings of the plugin called System - Joomla Statistics"

**Comment by brianteeman** [comment]
> Suggest the word says something like
> "If you do not wish to provide the Joomla Project with this information you can edit the settings of the plugin called System - Joomla Statistics"

That would be incorrect

![image](https://user-images.githubusercontent.com/1296369/61277381-fe57f680-a7a9-11e9-8d46-22320079cd7d.png)

The three buttons correctly describe the options for sending the statistics.

I am happy with the current text

**Comment by Webdongle** [comment]
I am not speaking of the initial installation message.  The information in the Post installation messages
"_If you do not wish to provide the Joomla Project with this information you can disable the plugin called System - Joomla Statistics_."
Implies that when the plugin is enable that it sends the statistics.  But it does not do that because there is a setting in the plugin.

**Comment by Webdongle** [comment]
But fine.  Have it your way ... you always do.

**Comment by brianteeman** [comment]
The original report made no mention of the post installation message
Having said that there is nothing incorrect about the post installation message

**Comment by Webdongle** [comment]
No it didn't but I since realised that the plugin had settings and did not need to be disabled like the Post installation message instructed.  Thus the Post installation message saying the disabling the plugin  ... is misleading.

**Comment by ghost** [comment]
@Webdongle i didn't understand your Issue, but if you have an Issue which isn't discussed enough please open a new one and describe your Issue.
