### ISSUE TITLE
[4.0] composer.lock file out-of-sync

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#25571]
Running `composer install` on current `4.0-dev` branch gives a "Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them." message in the console.  This should not happen.

Someone should introduce a CI step that prohibits this from even being possible.

**Comment by Hackwar** [comment]
Scrap that, I misunderstood everything. D'oh.

**Comment by Hackwar** [comment]
Yes, indeed, we should add such a step to drone. Going to bring that up in the ATT.

**Comment by Quy** [comment]
Please test PR #25577<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25571">issues.joomla.org/tracker/joomla-cms/25571</a>.</sub>
