### ISSUE TITLE
[4.0] Multilang status module

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25580]
![image](https://user-images.githubusercontent.com/1296369/61281040-d8822000-a7b0-11e9-8c66-c9d95b41827e.png)

Is this correct? How do you publish a site language? Does it mean "Installed site language"

@Bakual @infograf768

**Comment by Bakual** [comment]
You can deactivate a language pack in the extension manager. That's what this refers to. It coulöd be installed but not activated.
So a more correct term would maybe be "Activated Site Languages"?

**Comment by brianteeman** [comment]
Thanks for explaining. As the extension manager enables and disables I will submit a pr to change it to "Enabled....

**Comment by ghost** [comment]
Closed as having Pull Request #25584

**Comment by infograf768** [comment]
> You can deactivate a language pack in the extension manager. That's what this refers to. It could be installed but not activated.

I think we have a bug here. In fact when you disable a language in Extensions Manager, the language does not display at all.
Code is `$status->element` for both the Language tag and the "Published Site Languages "
That is a bug...

**Comment by infograf768** [comment]
code is
```
	/**
	 * Method to return combined language status.
	 *
	 * @return  array of language objects.
	 */
	public static function getStatus()
	{
		// Check for combined status.
		$db = Factory::getDbo();
		$query = $db->getQuery(true);

		// Select all fields from the languages table.
		$query->select('a.*', 'l.home')
			->select('a.published AS published')
			->select('a.lang_code AS lang_code')
			->from('#__languages AS a');

		// Select the language home pages.
		$query->select('l.home AS home')
			->select('l.language AS home_language')
			->join('LEFT', '#__menu AS l ON l.language = a.lang_code AND l.home=1 AND l.published=1 AND l.language <> \'*\'')
			->select('e.enabled AS enabled')
			->select('e.element AS element')
			->join('LEFT', '#__extensions  AS e ON e.element = a.lang_code')
			->where('e.client_id = 0')
			->where('e.enabled = 1')
			->where('e.state = 0');

		$db->setQuery($query);

		return $db->loadObjectList();
	}
```

**Comment by brianteeman** [comment]
When I tested disabling a site language in the extension manager the module displayed the language with the expected icons and messages

**Comment by infograf768** [comment]
If you disable French site for example, you get (with your PR but would also be the same before your PR):
<img width="1108" alt="Screen Shot 2019-07-16 at 13 00 50" src="https://user-images.githubusercontent.com/869724/61289509-cb255f80-a7c9-11e9-9182-fe55cfd04192.png">

This is wrong:
We should get fr-FR and then a X

We have a bug here. Looking at it now.

**Comment by infograf768** [comment]
We should get this
<img width="968" alt="Screen Shot 2019-07-16 at 13 09 50" src="https://user-images.githubusercontent.com/869724/61289999-0e340280-a7cb-11e9-9f78-f7dab4b0e82a.png">

**Comment by brianteeman** [comment]
No problem for me

![image](https://user-images.githubusercontent.com/1296369/61290769-9367e900-a7c4-11e9-872c-3c09d1a2715a.png)

![image](https://user-images.githubusercontent.com/1296369/61290782-9a8ef700-a7c4-11e9-8cf1-315e2b7f12f7.png)

**Comment by infograf768** [comment]
GRRR... forget it. I had some cache on... Sorry

**Comment by brianteeman** [comment]
lol
