### ISSUE TITLE
[4.0] for the NOT YET merged new admin template: color setting problem

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#25583]
### Steps to reproduce the issue
Edit atum primary color like 105
Save and reload
![2019-07-16_12h02_40](https://user-images.githubusercontent.com/2539440/61285658-a0cfa400-a7c1-11e9-8d50-960efda05ecd.png)

### Expected result
color seating need be 105

### Actual result
color setting is always 207

**Comment by pau1a** [comment]
Forgive my ignorance but I don't see a way to set this colour. How are you setting this?

**Comment by brianteeman** [comment]
In the template styles setting of the new admin template that is not merged yet

**Comment by pau1a** [comment]
> In the template styles setting of the new admin template that is not merged yet

Ah right, thank god for your edit. I thought I was going mad. Will grab the latest dev build. Im looking at alpha 10

**Comment by brianteeman** [comment]
The new template is not merged yet so is not in a dev build

**Comment by brianteeman** [comment]
@micker @franz-wohlkoenig please edit the original post to indicate that this is for the NOT YET merged new admin template. There may be other issues created that should be updated as well

**Comment by micker** [comment]
ok no problem i test joomla aplha 11
