### ISSUE TITLE
[4.0] backend : filter and search zone

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#25582]
### What needs to be fixed
hello i like new administration template it realy good first step !!!
i like the idea that joomla will be more simple and usefull  (group button, group action)

### Why this should be fixed
i think we can do more with filter and search ... many time user doesn't use it realy i think. It a big block for nothing at first
![2019-07-16_11h44_03](https://user-images.githubusercontent.com/2539440/61284331-05d5ca80-a7bf-11e9-88dd-2915e4f2ed85.png)

### How would you fix it
Maybe we can move this bar in  action zone hide search input
![2019-07-16_11h46_58](https://user-images.githubusercontent.com/2539440/61284528-6e24ac00-a7bf-11e9-8485-07cbd7a0234b.png)

or maybe more 
put all in a search and filter button
![image](https://user-images.githubusercontent.com/2539440/61284760-f3a85c00-a7bf-11e9-8dee-04cef1b1297c.png)

**Comment by alikon** [comment]
@micker
as this refers to #25570 wich is not merged yet please comment on the pr's and not open new issues for not merged code

thanks for your attention

**Comment by micker** [comment]
done thanks @alikon

**Comment by alikon** [comment]
closing as reported to the pr #25570 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25582">issues.joomla.org/tracker/joomla-cms/25582</a>.</sub>
