### ISSUE TITLE
[4.0] com_csp collecting ?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25594]
### Steps to reproduce the issue

1. enable detect mode. 
2. browse a few pages in the site and the admin
3. return to com_csp
4. see you have a list of entries
5. select them all and trash them
6. repeat step 2 and 3
**7. you have no entries**

The reason is that you already trashed the entry. So it probably was detected again but as a database record existed a new record wasnt created.

Took me ages to determine this and I had to check the database to discover this.

### Expected behaviour
Any combination of
1. detected in trash ==> unpublished
2. if trash not empty always display a "check the trash" message
3. change trash to delete

**Comment by zero-24** [comment]
> detected in trash ==> unpublished

This is happening right now :) When something is in the trash it is not added to the auto generated http header rule and for the reasons you described above there are also no now entrys generated. Excalty how com_redirect is working.

> if trash not empty always display a "check the trash" message

Agree on my list makes sense. thanks.

> change trash to delete

Well please share some more details what you are proposing here. As this is a default Joomla CRUD you mean to skip the trash at all? Or do I get it wrong? Currently this is working exactly like com_redirects collect mode where when something is in the trash the hit counter of the trashed item gets increased and not a new item is generated.

**Comment by brianteeman** [comment]
yes i meant skip the trash

**Comment by zero-24** [comment]
ok thanks.

**Comment by zero-24** [comment]
PR is in: https://github.com/joomla/joomla-cms/pull/25712/files closing here. Thanks.
