### ISSUE TITLE
Broken image icon get displayed in contact if admin deletes the image from media

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#25607]
### Steps to reproduce the issue
1. Login to joomla admin 
2. Go to component -> contacts.
3. Create new contact
4. Assign the contact image and fill all the mandatory field
5. Save the contact.
6. Login as admin to frontend.
7. Open the menu contact and select the user.
8. Now remove the image from media manager in backend (joomla admin)
9. Refresh the contacts in frontend.
10. See the contact image

### Expected result
If the admin removes image then the blank area should be displayed. 

### Actual result
Broken image area getting displayed

![screen shot 2019-07-17 at 10 28 15](https://issues.joomla.org/uploads/1/be8da273ad3d75c814a6fe50c2618da8.png)

**Comment by richard67** [comment]
1. Which Joomla version?
2. Screenshot looks like 3rd party template. Can you check with the standard Protostar template?

**Comment by brianteeman** [comment]
Doesnt matter what joomla version or template

If you delete an image file but dont remove the code to load the image then it will of course display an image not found message. That's nothing to do with Joomla - its how the web works

**Comment by infograf768** [comment]
We could check if the image is present or not as we know its relative path (`$this->contact->image`) and if not preventing display the `<div>`. Evidently that would only work for core template and for 3pd templates not overriding the tmpl.

**Comment by uthorat** [comment]
Hello richard,

Joomla version - Joomla! 3.9.10
Checked on protostar. PFA,


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25607">issues.joomla.org/tracker/joomla-cms/25607</a>.</sub>

**Comment by uthorat** [comment]
![screen shot 2019-07-17 at 11 03 31](https://issues.joomla.org/uploads/1/3417e8ccb3db041f9eedd729ae213234.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25607">issues.joomla.org/tracker/joomla-cms/25607</a>.</sub>

**Comment by ghost** [comment]
@uthorat please add the System Information in your opening Comment.

If i understand your Issue correct its about displaying a breaking-Image Info if Browser didn't find the given Image-url. Which is as @brianteeman wrote expected Behaviour.

**Comment by brianteeman** [comment]
> We could check if the image is present or not as we know its relative path ($this->contact->image) and if not preventing display the <div>. Evidently that would only work for core template and for 3pd templates not overriding the tmpl.

It would also only work for images defined in a field and not images in content.

**Comment by uthorat** [comment]
@franz-wohlkoenig Okay! Can we remove the broken image icon? 

When you create contacts without adding an image then at that time blank space is displayed which is correct. 
Please refer the screenshot, in which I have created one contact without adding image
![screen shot 2019-07-17 at 11 26 03](https://issues.joomla.org/uploads/1/06571628e480c469b51c3a777c12a4be.png)


So same when you delete the image can we add blank space?

### System information
Os: Windows 10
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25607">issues.joomla.org/tracker/joomla-cms/25607</a>.</sub>

**Comment by ghost** [comment]
> @uthorat please add the System Informations in your opening Comment.

**Comment by brianteeman** [comment]
The broken image icon is coming from your browser not from joomla

**Comment by uthorat** [comment]
@brianteeman If its a my browser issue, then how it gets display on another machine browser - https://bugcheck.cloudaccess.host/index.php/conacts  Pls check here. 
I have created two contacts.
User 1 - Firstly I have added image, then remove from the media manager.
Umesh - Didn't add the contact image.

So my suggestion is, if I am deleting the image from media manager then I should get the same view of user 2(Umesh) as he hasn't added the image.


@franz-wohlkoenig 
![screen shot 2019-07-17 at 12 52 31](https://issues.joomla.org/uploads/1/4b11a6bb921740bd0bc5feb80a1d11a1.png)






<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25607">issues.joomla.org/tracker/joomla-cms/25607</a>.</sub>

**Comment by ReLater** [comment]
> We could check if the image is present or not 

Please don't do that. Some more code and then at many places where similiar effects theoretically could occur.

If an image doesn't exist that a user has selected one should see that in the browser and not hide the failure by more and more "friendly" codes.

**Comment by ghost** [comment]
#### Firefox
![Screen Shot 2019-07-17 at 15 20 25](https://user-images.githubusercontent.com/8235763/61378786-7c99c300-a8a6-11e9-873f-8adc2c45c8cf.png)
#### Safari
![Screen Shot 2019-07-17 at 15 20 10](https://user-images.githubusercontent.com/8235763/61378815-8ae7df00-a8a6-11e9-92b4-bb77f410e1f9.png)
Browser show if a Image is missed.

I suggest to ask on [Forum](https://forum.joomla.org/) as this Repository is for coding; closing Issue.

**Comment by ReLater** [comment]
> We could check if the image is present or not as we know its relative path

Not always. You can also enter an image url like `https://example.org/thing.jpg` for the image.
