### ISSUE TITLE
[4.0] Install languages - old version info

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25612]
The current situation is that if you hover on the version number you will see information if the version is out of date but it is very easy to miss
<img width="706" alt="chrome_2019-07-17_13-59-25" src="https://user-images.githubusercontent.com/1296369/61377470-312de780-a89b-11e9-8bc6-b1d29e66f1b7.png">

### Option 1
If the version is out of date then when you click on install you get a warning before installing

### Option 2
Display the message permanently on screen
![image](https://user-images.githubusercontent.com/1296369/61377580-65a1a380-a89b-11e9-8ec7-0e0d8dc72458.png)

### Option 3
I'm sure their must be more options

/cc @Bakual @infograf768

**Comment by richard67** [comment]
Just my 5 cent: I don't like option2. It will show some 120 times the same message. Hard to find the one or 2 language packs which are up to date between the 120 (or so) others.

Maybe we can just have an icon for that in a column, and if nessesary one time this "Language pack does not match" text in a kind of legend above or below the list?

**Comment by richard67** [comment]
Maybe just a sad emoji in a column beside the version if not up to date, or a red exclamation mark, and beside the column header (should be short, so "Up to date" might be too long) show a referrer to a footnote, and this then has the text what the column means?

Or have that sad emoji or red exclamation mark right (or left if RTL) beside the version but in same column, and add referrer to footnote to the version column header?

**Comment by brianteeman** [comment]
1. I have faith that we will only have a few out of date languages
2. Whatever is done it has to be accessible

**Comment by richard67** [comment]
1. In my 3.9.10 it is some 50/50 good/outdated
2. I agree.

I could live with your option 2, I just would not like it very much ;-)

**Comment by infograf768** [comment]
> I have faith that we will only have a few out of date languages

As we will certainly get much less languages than available in 3.x, this looks right at first sight, but my experience shows we still would have a good proportion of outdated. 
One simple reason is the time it may take to update a pack when a new version is released as it depends on the availability of TTs.
The other is that we may now be able to update J to non-stable versions.

Concerning the solution, I am still hoping that someone codes the use of an interrogation mark to display available readable tooltips. In that case we would see the interrogation mark in red near the version number and some sr only stuff in that case.

![Screen Shot 2019-07-18 at 09 04 04](https://user-images.githubusercontent.com/869724/61436434-13b05a80-a93b-11e9-83af-14b5c1bf017d.png)


Concerning the alert, it would work in Install Languages (only one lang pack can be installed at a time) but not during Joomla installation as one can select multiple languages to install at the same time. I guess we should normalize that behavior.

Note: the background brown reddish color and pink text color for the `badge-warning` class in the new backend template are not only ugly but the figure is hardly readable..

**Comment by ghost** [comment]
> I guess we should normalize that behavior.

+1 if it mean to install multiple Languages at one Time in an installed Joomla.

**Comment by brianteeman** [comment]
@infograf768 
Do you want the ? on all languages or do you mean just on those that are out of date?
If the latter then I would suggest to use the warning icon ⚠️ 
If that's what you want its very easy for me to do that

**Comment by Bakual** [comment]
I think JM meant that icon as a general solution in case tooltips are available. Then this would solve itself.

But here in that case, I'd use a warning icon as well.

**Comment by infograf768** [comment]
I meant using the interrogation mark as a way to display the tooltip (not only there but everywhere in Joomla)
It would not show in this case if the language is up to date.

For people with no sight disabilities, the colour of the version (badge-warning) is enough imho compared to the updated language that should be green (badge-success).

Not sure about usng a warning icon as a replacement to the interrogation mark as it would not be obvious hovering it would be understood as going to display the tooltip. 
But added to the interrogation mark could be OK although getting heavy.

Note: I wonder if we could not also add a Filtering by Version.

**Comment by brianteeman** [comment]
1. Adding tooltips back in to Joomla is off topic here
2. I will do it with an ℹ️ (information) icon if out of date and we can see how it works
3. Filtering by version is off topic here but I wouldnt recommend it. I want my language not just my language if its up to date.

**Comment by infograf768** [comment]
> I will do it with an ℹ️ (information) icon if out of date and we can see how it works

Looks like a good idea.

**Comment by ghost** [comment]
Closed as having Pull Request #25630
