### ISSUE TITLE
Captcha not in contact and registration forms, only - but also in login form

### ISSUE THREAD

**Issue by gersteba** [joomla/joomla-cms#25613]
Hello!
Joomla 3.9.10 is still not providing websites with a captcha protected login form.
Please complete the captcha protection of Joomla websites including it also in the login form - thank you!
Kind regards,
Gerald

**Comment by brianteeman** [comment]
I have implemented this on the registration on one of my sites at the clients insistence. It has not stopped spam registrations at all.but it has prevented people from signing up and I have to do that manually for those I hear about

**Comment by SharkyKZ** [comment]
Duplicate #14791.

**Comment by richard67** [comment]
Edit: Wrong issue commmented.

**Comment by ghost** [comment]
@SharkyKZ #14791 is about 4.0

**Comment by alikon** [comment]
3.x is feature freeze so better continue on #14791

**Comment by ghost** [comment]
Closed as duplicate Report.

**Comment by alikon** [comment]
closed in favour of #14791<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25613">issues.joomla.org/tracker/joomla-cms/25613</a>.</sub>
