### ISSUE TITLE
Media: Required space between the field when user clicks on create new folder

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#25611]
### Steps to reproduce the issue
1. Login to joomla admin panel
2. Go to content -> media
3. Click on create new folder

### Expected result
fields should have some space

### Actual result
Fields are touched to eachother.

### System information (as much as possible)

PHP Version	7.1.30
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.9.10 Stable [ Amani ] 10-July-2019 15:57 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

### Additional comments
![screen shot 2019-07-17 at 13 54 14](https://issues.joomla.org/uploads/1/74339aee431884102a94a2ecbf773a6b.png)

**Comment by ghost** [comment]
@Quy can you please have a look?

**Comment by pau1a** [comment]
I always assumed this was done as a conscious decision however I tend to agree that a little margin separation would look better

**Comment by ghost** [comment]
@pau1a i guess its not soo important for Developers. If you can make a Pull Request and risk that it didn't get merged cause of an conscious decision i didn't know would be helpfull.

**Comment by ghost** [comment]
Closed as having Pull Request #25629
