### ISSUE TITLE
[4.0] Installed and updated date?

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#25627]
I personally think it would be a good addition to have the date an extension/plugin/module/library was installed and the date the extension/plugin/module/library was updated. 

What are other peoples thoughts on this?

**Comment by alikon** [comment]
make sense to me

**Comment by brianteeman** [comment]
Instead of writing the code to do that (needs new db columns etc) why not take advantage of user action logs?

**Comment by tonypartridge** [comment]
We absolutely can. I was just thinking it would make more sense in the
extensions view as an over view and part of the extension ? Since you are
usually there anyway.

I suppose technically it should be in the user actions logs if they are
setup correctly.

**Comment by alikon** [comment]
not sure we can avoid to add new columns to the db (the actions log can be disabled)

**Comment by mbabker** [comment]
Sounds like an action log thing to me, not something that belongs as part of the `#__extensions` table schema.

**Comment by apple-fan-pl** [comment]
@mbabker Disable action log? Do you have any idea what consequences it might have on whole site? I bet you dont! Otherwise you wouldnt write something as absurdish as this.

**Comment by tonypartridge** [comment]
> 
> 
> @mbabker Disable action log? Do you have any idea what consequences it might have on whole site? I bet you dont! Otherwise you wouldnt write something as absurdish as this.

Given Michael knows the insides out of Joomla! of the top of his head and was the main release lead for way too long I'd say he knows what he's talking about ;-).

But he hasn't day disable action logs? but just to use it instead of being part of the core extensions table...

**Comment by mbabker** [comment]
Trolling and sarcasm aside, I actually would know a little bit about how the action log component works.  Logging the time an extension was installed or last updated is not so critical that it needs to be handled in the `#__extensions` table and related PHP APIs (and yes I get that to some people it's more urgent than others, but IMO the action logging system fits this use case perfectly for those who desire it).

**Comment by alikon** [comment]
i'm really sorry  if my previous comment https://github.com/joomla/joomla-cms/issues/25627#issuecomment-512708878 about the option to disable action log have raised this missunderstanding, i'll explore a way to deal this with user action logs

**Comment by apple-fan-pl** [comment]
> main release lead for way too long I'd say he knows what he's talking about ;-).
Being release lead in some nimor project is not relevant..... he wasnt accepted into larger and serious project as they dont accept clowns.......

**Comment by infograf768** [comment]
Folks, please do not reply to trolls. Just ignore them.

**Comment by alikon** [comment]
after some dirty hack to the com_patchtester manifest to let it point on localhost with a fake new version  & the corresponding  hack to the table `#__update_site`
![Screenshot from 2019-07-28 11-54-21](https://user-images.githubusercontent.com/181681/62005105-82a56480-b12e-11e9-8224-71e367223b9a.png)

so after my silly test i think we already have this feature .....

**Comment by alikon** [comment]
@tonypartridge can you consider this issue as closed ?
