### ISSUE TITLE
[4.0] Group user in form

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#25620]
For websites like schools, gyms, classified ads, communities,

Now the registrarion form add in global user group.
![default](https://user-images.githubusercontent.com/9007607/61421484-8e5f8280-a907-11e9-8e62-86564047515d.JPG)

This is better, choose the default user group in the menu buttom.
![default-user](https://user-images.githubusercontent.com/9007607/61421683-67ee1700-a908-11e9-8d20-141717c174e8.jpg)

**Comment by HLeithner** [comment]
I'm not sure if the menu item is the right place to do this, because this features would have security implications. So it should be thought thru carefully.

**Comment by micker** [comment]
i think something already exist
https://extensions.joomla.org/extension/usergroup-selector/

**Comment by Open2logic** [comment]
It seems that the menu item is the most logical, because the registration component is associated.

**Comment by mbabker** [comment]
IMO this suggestion should not be implemented.  What group a user is registered into by default should not change because of the menu item associated with the page.

**Comment by brianteeman** [comment]
I can see the logic for having something like a usergroup selector in the reg form but not for basing it on a menu item. As @micker pointed out something like this already exists as free plugin. I dont see the need for this in the core therefore.

**Comment by Open2logic** [comment]
The extension that is cited has not been updated since 2015 and is only for Joomla 3, I do not believe that this functionality exists as an extension for Joomla 4.
There are two functionalities where Joomla is the perfect option for a website, the Joomla multi-language management is incredible and the Joomla ACL is spectacular, any improvement in these two fields, however small they may be, should be implemented, so as not to make past mistakes and lose Joomla's position as the best cms for multi-language websites and websites with user roles.
This functionality does not exist as an extension for Joomla 4, nor will it exist, it should be implemented.

**Comment by brianteeman** [comment]
As joomla 4 is not even at a beta its very premature to say that an extension will not be updated to support it.

**Comment by Open2logic** [comment]
I have spoken with the developer of the extension indicated (selector user group), he will not develop it for Joomla 4

**Comment by brianteeman** [comment]
Having just had to do something like this for a university I can tell you that the menu approach does have some serious security implications as suggested by @HLeithner The only way I was able to achieve this was to use completely different forms for registration

**Comment by Open2logic** [comment]
Noooo, ohhh
I was finishing a plugin for this functionality and I was going to add it here and see your opinions

Now my work in the trash.

But it would be a great improvement for Joomla 4 and for the type of teaching websites, gym websites, etc. and I am not a security expert to provide a solution according to your comment, if you could tell me what I should consider.

I will also add my plugin here next week.

Could it be restricted and that there was no access to the special groups?
It would be a solution

**Comment by Quy** [comment]
OK to close?

**Comment by Open2logic** [comment]
Wait Quy, not in such a hurry to close improvements for Joomla 4, Brian has also experienced this problem in Joomla when working on a university website.
Obviously it is a necessity for many websites and it would be a great improvement for Joomla. Let me upload my plugin and you think

**Comment by brianteeman** [comment]
@Open2logic still waiting

**Comment by Open2logic** [comment]
When you want a registration form in Joomla you can only call the component.
I was not sure whether to finish the plugin or make a module to show the registry component but with the option of group assignment. In this way, we not only gained the functionality of the group assignment but we could not have the Joomla registration form in a module and we can show next to an article. After testing I think the plugin solution was more elegant, but I am entertained with the module.
I finish the plugin on Saturday and I share it. Thanks for the patience and trust.

**Comment by Open2logic** [comment]
I wanted to comment on a problem that I see in the future.
There are fewer and fewer programmers creating extensions for Joomla.
I remember when I gave Joomla courses that I talked to the students about the number of extensions they could get.
But over time we knew that the important thing was not the quantity but the quality.
Although there were many extensions to create a forum, we all recommended the same, although there were many extensions for forms we all recommended the same, etc.
But one of the things that makes Joomla great is that there are advanced features that come with the kernel and you don't need external extensions. This gives peace of mind and confidence of continuity in the support. 
Now is the time to consider whether Joomla includes new functionalities because extensions that cover that functionality are not going to come out.

I've been looking at Wordpress ACL extensions and they are a disaster and a cheap copy of the Joomla user component. They copy badly but add other functions that are interesting for the developer.

This extension is quite interesting
https://wordpress.org/plugins/private-content/

And I have thought about this idea based on the quality of extensions and the lack of extensions in the future.
Joomla should copy the Apple model, Apps Store and recommend official Joomla extensions.
They would not be extensions included as core functionalities, but neither extensions made without supervision or quality review.
It would be an intermediate point where programmers would feel Joomla's support in their extensions and could rely more on creating extensions as a business.
I do not believe that I have enough security to create a functionality included in the core, but to offer it as a basic extension for Joomla.
Finally I created a registration module and a plugin, this version is for Joomla 3, in another comment I add instructions and captures.

[usergroupselector.zip](https://github.com/joomla/joomla-cms/files/4245647/usergroupselector.zip)

[mod_wsregister.zip](https://github.com/joomla/joomla-cms/files/4245642/mod_wsregister.zip)

**Comment by Open2logic** [comment]
The problem with the current User Group extension Register extension, is that it shows a selector where the user sees all the groups created in a drop-down.

I have created a modification that allows you to assign a user group to the registration module without the user knowing what group it is.

Now a gym website could create registration for classes in groups of Yoga, Karate, etc. a website of a university could create records of Classroom A, Classroom B.

Simply a module is shown on the information page of each course, class, classroom, etc. The module already defines in which group they are registering

**Comment by brianteeman** [comment]
I just took a look at the files you submitted. I think you really need to take another look at them. There are a lot of files completely unrelated included and there are some very clear and obvious form errors

**Comment by Open2logic** [comment]
I hope and wish that this plugin is better programmed and meets this requirement, if it doesn't work, I don't think it knows how to do it better.


[plg_user_open2logicregisteruser.zip](https://github.com/joomla/joomla-cms/files/6572705/plg_user_open2logicregisteruser.zip)

Is for Joomla 3

A menu item associated with the registry component is created and it is indicated in the menu button options in which user group the registry will be generated.
In this way we can have several menu buttons with registration for teachers, students, etc ...

**Comment by brianteeman** [comment]
I understand what you are looking to do here. Have a registration form for teachers and a registration form for students. The problem however is that there is no way to stop a student registering as a teacher etc. The only way you can prevent that (which is what I did for a university) is to automatically set the correct group (teacher/student) based on other information. In my case it was by validating a staff id field. 

This is not something that the core can or should do in my opinion and I will leave it to others to decide if this should be closed or not.

**Comment by joomdonation** [comment]
Base on feedbacks on this issue, this is something we won't implement in core. So I'm closing this issue.
