### ISSUE TITLE
Resize image on upload jce core editor

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25637]
### Steps to reproduce the issue

Resize on upload bug using jce core editor

### Expected result

Free resize image on upload using jce core editor

### Actual result

No free resize image on upload using jce core editor

### Additional comments
here is solution on how to solve this bug, please test and bug fix :) and help us provide for joomla users free image resize on upload plugin for jce core editor.

**Comment by brianteeman** [comment]
JCE is not part of the core

**Comment by SniperSister** [comment]
Closed for reason stated above

**Comment by SharkyKZ** [comment]
You can try submitting this to JCE https://github.com/widgetfactory/jce.

**Comment by ghost** [comment]
I tried but it seems still no interest in making Free resize image on upload using jce core editor.

I would be very happy if it be accepted , but untill this happens joomla users needs Free resize image on upload using jce core editor

**Comment by N6REJ** [comment]
@Milglius that feature has been in free for a decade.  Perhaps you don't have the media manager installed.  Anyway, Ryan is a great guy so you just need to use his support system.

**Comment by ghost** [comment]
@N6REJ Ryan do not provide that feature for free. It is not free now you need to buy it.  His support forum is also paid one not free. Ryan is a great guy and we hope he reconsiders his desision to not provide free image resize on upload in jce.

Free resize image on upload using jce core editor do not exist in Ryans extension . 

So as I understand our only option is to create our own free open source plugin to have this feature for free to all joomla users - resize joomla article image on upload.

**Comment by mbabker** [comment]
Someone please edit out all of the backlinks to this plugin, this is borderline spam.

**Comment by ghost** [comment]
mbabker you a funny you have lots of time to remove links to free open source plugin of others but yourself share links of paid plugins. Unless you are happy that joomla cms is so outdated that no one can resize image for free using outdated joomla cms. Then please help us to create this plugin, or just create this plugin yourself for free. And put you link to that free plugin. I personaly have big doubts you coud create such plugin, couse its seems in my opinion you just like that joomla 3.9.10 is abandoned outdated cms.

Free resize on upload open source plugin for Joomla JCE core extension now is the only way to go and have resize on upload for free for joomla users.

**Comment by infograf768** [comment]
Topic locked.
Once more: this is the Joomla core Issues and Pull Requests project, not any 3rd party github project.
