### ISSUE TITLE
[4.0] Improve ES5 Generation with polyfills for IE

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#25639]
Despite core is dropping formal support for IE in our template neither do we want to make it too hard to build frontend templates on IE. Basically in core we can use the ES6 files natively now and we also don't want to have to add IE code in this.

I believe we can use this https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#web-standards for the es5 files which will hopefully still be ie11 compat (but not used by core but provided as a service for templates who require it). And that will polyfill nodeList.foreach removing our requirement for example to use `[].slice.call()` from JS as an example

This came out of this closed issue https://github.com/joomla/joomla-cms/issues/25566

**Comment by brianteeman** [comment]
@Fedik @dgrammatiko @wilsonge Is this still an issue?

**Comment by dgrammatiko** [comment]
Partially. The core-js that @wilsonge mentioned here is already in our dependencies https://github.com/joomla/joomla-cms/blob/f4ac18829fad6eadd7260ac2f951aca0c7da459b/package.json#L77 **BUT** the ES5 rollup config needs some attention. I mean we can inflate every script by injecting the polyfills from core-js (easy fix I already have the code muted in place) or serve the polyfills as separate scripts (with a `nomodule` attribute) so we don't repeat the polyfills per script. Reference: https://github.com/joomla/joomla-cms/pull/32315#issuecomment-787427272

**Comment by dgrammatiko** [comment]
@brianteeman this can be closed as there's a PR: https://github.com/joomla/joomla-cms/pull/33084

**Comment by dgrammatiko** [comment]
This can be closed but there is still https://github.com/joomla/joomla-cms/issues/22164 which needs to be addressed (eg polyfills not provided by babel)

@Quy @alikon

**Comment by joomdonation** [comment]
Closing as requested. Thanks @dgrammatiko
