### ISSUE TITLE
Admin - Can save user detail with invalid / past Registration date using burpsuit.

### ISSUE THREAD

**Issue by AdityaTaware** [joomla/joomla-cms#25632]
### Steps to reproduce the issue
1. Start burpsuit and open Joomla admin panel
2. Go to the Users list view
3. Open any existing registered user for edit.
4. Now start burpsuit intercept.
5. Now click on the Save button from the user edit page.
6. Now check Params in burpsuit and update the date as required.
7. Click on Froward button to submit a request.
8. Do the forward action 2-3 times and off the Intercept.
9. Check the updated record in Joomla admin list

### Expected result
The registration date should not accept an invalid/past date and date greater than the last visit date

### Actual result
System accept invalid or past Registration date 

### System information (as much as possible)
PHP Built On	Linux lamp134.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.7.el6h.x86_64 #1 SMP Mon Dec 17 12:02:35 EST 2018 x86_64
Database Type	mysql
Database Version	5.7.24-cll-lve
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.1.30
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.9.10 Stable [ Amani ] 10-July-2019 15:57 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36![screen shot 2019-07-18 at 13 22 46](https://issues.joomla.org/uploads/1/b58024e926233143d9a31b19e13fba24.png)

### Additional comments

![screen shot 2019-07-18 at 13 25 32](https://issues.joomla.org/uploads/1/5e2bc5bb9633899c9a7258c2fba03c08.png)

**Comment by brianteeman** [comment]
That's because there is no validation in the xml (client side) and there is no validation on that form (server side)

**Comment by Quy** [comment]
Related #24780?

**Comment by Quy** [comment]
Duplicate #24780, but just a different way of producing the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25632">issues.joomla.org/tracker/joomla-cms/25632</a>.</sub>

**Comment by Quy** [comment]
@AdityaTaware Please test PR #27328
