### ISSUE TITLE
Logo Not Centered in Login Box of Isis template

### ISSUE THREAD

**Issue by picht** [joomla/joomla-cms#25636]
Hi

When using a Login Logo with the isis template, the logo is not centered with the login boxes.
Shouldn't it be?

regards
Picht

**Comment by ghost** [comment]
Please ask on [Forum](https://forum.joomla.org/) as this Repository is for coding.

**Comment by picht** [comment]
I know how to center it using css, but as it looks rather stupid with the logo not centered I thought it was an error in the template.
If it is an error in the template it should be fixed. For this I was pointed here from the forum :)

**Comment by picht** [comment]
@franz-wohlkoenig 
I know how to center it using css, but as it looks rather stupid with the logo not centered I thought it was an error in the template.
If it is an error in the template it should be fixed. For this I was pointed here from the forum :)

**Comment by ghost** [comment]
> For this I was pointed here from the forum :)

New Information, reopened.

**Comment by ghost** [comment]
Can you please provide the Link to the Forumthread?

**Comment by picht** [comment]
https://forum.joomla.org/viewtopic.php?f=713&t=973171

**Comment by ghost** [comment]
@HLeithner if this is something we should look at i would ask @pau1a if you're interested?

**Comment by HLeithner** [comment]
I have no opinion if this should be centered or not. Iit can be changed by css so I don't see a reason to change this.

**Comment by ghost** [comment]
Thanks @HLeithner. 

@picht thanks for report, but closing for the Reason stated above by Release Lead.

**Comment by picht** [comment]
OK :)
