### ISSUE TITLE
Error on submit if custom fields are displayed but disabled

### ISSUE THREAD

**Issue by degobbis** [joomla/joomla-cms#25652]
### Steps to reproduce the issue
1. Create a custom field from the type media and disable the permission to edit custom field value for the group Manager.
2. Edit in backend the article with this custom field as a super user and as an example select an image.
3. Login in frontend with the user in the group Manager and edit the article with this custom field and safe it without any changes.

### Expected result
The article will be submitted and saved.

### Actual result
This will show a warning with invalid field.

### System information (as much as possible)
Tested on Joomla 3.9.10
with PHP 7.3.x, 7.2.x and 7.1.x
on Linux and Windows

### Additional comments
Also the warning shown prints the field name to define the error field, which may be named differently from the label and therefore may not be findable.
I fixed this here #25626

**Comment by ghost** [comment]
Closed as having Pull Request #25626

**Comment by degobbis** [comment]
@franz-wohlkoenig please reopne the issue, my PR #25626 fixes the error of the warning message but not the problem described here itself.

**Comment by alikon** [comment]
please test #25682<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25652">issues.joomla.org/tracker/joomla-cms/25652</a>.</sub>
