### ISSUE TITLE
Tinymce version is 5.0.12

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25653]
Feature request: Tinymce version is 5.0.12

Does Joomla 3.9.10 use tinymce version 5.0.12 ?

Does Joomla 4 use tinymce version 5.0.12 ?

**Comment by HLeithner** [comment]
For 3.9 it's unlikely to get tinymce 5 into the core because of the api changes in tinymce.

Joomla 4.0 already includes tinymce 5.0

**Comment by brianteeman** [comment]
It is not unlikely - it is impossible
It is nothing to do with the api changes (which are minimal)
The reason is that the current version of TinyMCE used in Joomla 3 is the last version that supports all the web browsers that Joomla 3.x supports.

**Comment by ghost** [comment]
so joomla 3.9.10 supports unsupported web browsers thats why joomla 3.x dont use new TinyMCE 5.0.12 ?

what browsers Joomla 3.x supports that are supported by web browsers developers but not by TinyMCE 5.0.12 ?

**Comment by HLeithner** [comment]
J3 supports ie8+
