### ISSUE TITLE
[4.0] ACL for media

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25654]
### Is your feature request related to a problem? Please describe.

Feature request : ACL for media

### Describe the solution you'd like

ACL for media

**Comment by brianteeman** [comment]
Please provide more information.
Do you mean ACL on who can access com_media
or do you mean something more fine controlled

**Comment by ghost** [comment]
more fine controlled

for example 

at least users who upload media should only see their folder and only their media using frontend

**Comment by brianteeman** [comment]
You already brought this up before and it was answered then!

**Comment by ghost** [comment]
Discussion #23261. 

@Milglius please don't ask allready answered Questions as it means double Work for other Volunteers to answer, search for Questions …

**Comment by ghost** [comment]
it was closed and locked by your request but not answered, brian I hope you understand english language

brian please provide your answer regarding joomla ACL for media

ACL for media will be denied as feature in joomla 4 ? yes ?
