### ISSUE TITLE
[4.0] Field Groups - 403

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25651]
### Steps to reproduce the issue
Create a content field
Create a content field group
Re-open the content field group

### Expected result
Group opens

### Actual result
403 You are not authorised to view this resource.

### Additional comments
```

Call stack
--
# | Function | Location
1 | () | JROOT\administrator\components\com_fields\Dispatcher\Dispatcher.php:45
2 | Joomla\Component\Fields\Administrator\Dispatcher\Dispatcher->checkAccess() | JROOT\libraries\src\Dispatcher\ComponentDispatcher.php:115
3 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT\libraries\src\Component\ComponentHelper.php:383
4 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:116
5 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:159
6 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:241
7 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\includes\app.php:63
8 | require_once() | JROOT\administrator\index.php:36

```

**Comment by Quy** [comment]
Context value is missing in the URL , thus, the error.

`http://localhost/joomla-cms-4.0-dev/administrator/index.php?option=com_fields&view=group&layout=edit&id=1&context=`

**Comment by brianteeman** [comment]
I have finally tracked down the problem to the changes made in #24801

If I revert the changes to the files `administrator\components\com_fields\tmpl\groups\default.php` and `administrator\components\com_fields\Controller\GroupController.php` then the problem is resolved.

Probably simply reverting that change is not the solution.

@roland-d as this was your code could you please take a look

**Comment by Quy** [comment]
Please test PR #26424<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25651">issues.joomla.org/tracker/joomla-cms/25651</a>.</sub>
