### ISSUE TITLE
[4.0] Logging in Debug plugin is broken

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#25675]
### Steps to reproduce the issue

Enable `Debug System` in Global Configuration.
Enable `System - Debug` plugin.
In plugin, enable `Log Deprecated API`.
Inspect the Debug bar.

### Expected result

100s of deprecation messages.

### Actual result

Only 1 message.

### Additional comments

Caused by #20547 (CC @laoneo). At first glimpse this call could be moved from constructor to an event but I'm not sure if this is the correct solution, plus it might miss some messages this way:

https://github.com/joomla/joomla-cms/blob/effa28d607008fb9eac7fb55149ca30229f142d0/plugins/system/debug/debug.php#L186

**Comment by laoneo** [comment]
I will have a look on the debug plugin as there are some other things which need to be changed.

**Comment by infograf768** [comment]
> there are some other things which need to be changed.

I could not login this morning after updating  a dev test site (which was set to debug) to latest -dev via eclipse and running npm ci.
`Joomla\Plugin\System\Debug\Storage\FileStorage;  not found.`

After adding `/use Joomla\Plugin\System\Debug\Storage\FileStorage;` in 
`/plugins/system/debug/Storage/FileStorage.php`

I could log in. Thereafter I commented that line and it worked fine again.
Hope it helps.

**Comment by SharkyKZ** [comment]
@laoneo Thanks.

@infograf768 You needed to delete the `libraries/autoload_psr4.php` file. Maybe we should have it regenerated automatically after updating Joomla!

**Comment by laoneo** [comment]
Please test #26264.

**Comment by ghost** [comment]
Closed as having Pull Request #26264

**Comment by infograf768** [comment]
reopened as #26264 did not solve it.

**Comment by jwaisner** [comment]
Increasing priority as per guidelines for beta-blockers.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25675">issues.joomla.org/tracker/joomla-cms/25675</a>.</sub>

**Comment by alikon** [comment]
i would not add another issue, but also query explain is broken in the debug plugin as we are now quite converted all SQL to prepared statements
![Screenshot from 2020-03-28 09-26-38](https://user-images.githubusercontent.com/181681/77818849-52a3cc00-70d6-11ea-8457-64cee5671cf0.png)

**Comment by Fedik** [comment]
Please test #30317

@alikon about db "explain", I think it may be better to open a new issue, it more related to DB layer.

**Comment by alikon** [comment]
it can be better,
or wait ....
before to switch on this new thing maybe someone would had been to think a little bit more , we are losing a too much feature from j3 compared to j4 for what ?   .... a more fancy display
your friendly complainer...

**Comment by Fedik** [comment]
> we are losing a too much feature from j3 compared to j4 for what ? .... a more fancy display

No, it not because fancy display, it because DB layer limitation.
Later I will open new issue with some explanation.

**Comment by richard67** [comment]
So what about this issue here? Can it be closed because PR #30317 will solve it?

**Comment by Fedik** [comment]
Wait, I will open new issue about database, then we can close this :wink:

**Comment by richard67** [comment]
Ok, thanks. No need to hurry, just ping me when done.

**Comment by Fedik** [comment]
there it is #30318

**Comment by richard67** [comment]
Closing as having 1 pull request covering the main issue here, and one issue to keep track of the remaining one:
- PR #30317 
- Issue #30318

Thanks @Fedik .

**Comment by alikon** [comment]
please don't get me wrong
i really appreciate your efforts
but we still miss something "Call Stack" for example
j3
![Screenshot from 2020-08-09 11-28-39](https://user-images.githubusercontent.com/181681/89729191-8521e600-da33-11ea-9ffd-87c68c9a939d.png)

j4

![Screenshot from 2020-08-09 11-27-57](https://user-images.githubusercontent.com/181681/89729181-70455280-da33-11ea-892a-565ab0163382.png)

**Comment by HLeithner** [comment]
> but we still miss something "Call Stack" for example

You have to activate Call Stack, Explain and Profile in the plugin first
