### ISSUE TITLE
[4.0]: 1064 you have an error in your sql syntax

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#25678]
### Steps to reproduce the issue
Twice uploaded and installed Joomla 4 Alpha 10 package. 
First done on the joomla.com via launch.joomla.org free test website service. The previous install was J4 Alpha 7.  The second installation was on my own server which overwrote a clean install of Joomla 3.9.10 via Softaculous on cPanel. 
The screenshots below are from my server.

### Expected result
Access to Administration panel and to see basic Cassiopeia template on front-end

### Actual result
Before logging in, the Admin login had an error message (see pic)

![screen shot 2019-07-21 at 17 54 09](https://issues.joomla.org/uploads/1/8c2fc94db8cfc7f42fb16e6cdb7f86e5.jpg)

In the Admin panel this message: 

"An error has occurred.
1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `' at line 1" 

PLUS: message in a salmon pink box at the top of the admin panel: 
"Error
The template for this display is not available." 
(same text as the Admin login screen)![screen shot 2019-07-21 at 17 53 14](https://issues.joomla.org/uploads/1/46a8ead5749325f07329d9e85e61fc11.jpg)

On the front end, in an otherwise white screen: Error

### System information (as much as possible)
1: PHP 7.2
   Otherwise as provided by launch.joomla.org 
2: Pretty much the same on my server

### Additional comments
I can't install Joomla locally on my PC because however hard I try I cannot get the hang of the emulator.

**Comment by brianteeman** [comment]
at a guess its because you overwrote an existing install of j3

**Comment by ghost** [comment]
closed as expected behaviour.

**Comment by brianteeman** [comment]
@franz-wohlkoenig please dont be in such a rush to close things. I made a guess. It would at least be polite to give the reporter time to see if my guess was correct before you close it

**Comment by richard67** [comment]
It seems there was not just an old installation overwritten like I understood the description first, it was really made an update. For alpha 7 to alpha 10 this is not expected to work, and for updating 3.9.10 it should be fixed in current nightly build of 4.0 and in next alpha or beta.

**Comment by ghost** [comment]
Nightly updates are for Beta announced.

**Comment by Scrabble96** [comment]
To clarify: first I tried to update an existing J4 Alpha 7 to Alpha 10 which did not work. This was on a website created on [subdomain].joomla.com using the free launch.joomla.org. When I tried to view the site I just got 'Error' on an otherwise blank page. In the Admin panel, there was an error message. I can't remember the wording searching for a solution I found it was fixed by deleting /libraries/autoload_psr4.php. This gave me access to the Alpha 10 Admin panel but I still had an error for the front end. Rather than jumping from Alpha 7 to Alpha 10, should I re-install Alpha 7 and then install first Alpha 8 and then Alpha 9 and then Alpha 10?

Then (not mentioned in my original post above) I tried a brand new installation on launch.joomla.org with a new subdomain. The default Joomla 4 installation here is still Alpha 7, so I had no option but to install that. Unfortunately, the ccp.cloudaccess.net login is asking me to complete the Captcha before logging in... but there is NO Captcha to complete, so I am stuck and cannot access the Admin panel. In the meantime, the front end again just displays a white page with 'Error'.

Next, I created a new subdomain on my own testing domain. Installed a standard Joomla 3.9.10 installation and then installed Joomla 4 Alpha 10. This is obviously wrong, too, and I got the messages as shown in the screenshots above.

Today, I have deleted all the content from that subdomain, uploaded the J4 Alpha 10 zip file to the subdomain and unzipped it there. I am attempting to go through the Joomla installation process but I keep getting a message that it cannot connect to the database, despite the fact that I had created a new database in cPanel, linked to a new user with ALL privileges. I have tried both the database name and user name with and without the subdomain_ prefix.

**** Without being able to install J4A10 I cannot test possible solutions to issues and PRs that I have initiated in Joomla 4 github. ****

**Comment by Scrabble96** [comment]
Update: having set up yet another new database and new user on cPanel I have now completed the J4A10 installation and have access to both the Admin panel and can see Cassiopeia on the front-end. I will take up the logging in issue on ccp.cloudaccess.net directly with them.

**Comment by brianteeman** [comment]
Great
