### ISSUE TITLE
Feature request: What cookies creates Joomla ?

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25670]
What cookies creates Joomla ?

Where we can find all cookies Joomla 3.9.10 creates?

**Comment by infograf768** [comment]
This is NOT a feature request!
All cookies, whether created by Joomla or any other site, are stored by the browser.
Again, please use forum or search with Google before posting here as THIS IS FOR CODING!!!

Closing.

**Comment by ghost** [comment]
This is feature request

We want to know What cookies creates Joomla ?

Joomla 3.9.10 cookies should be documented.

Joomla developers need to document and share What cookies creates Joomla.

I just spent some days finding out by trial and error what cookies are dropped by a few joomla sites; which cookies are essential and which are not.

**Comment by SharkyKZ** [comment]
You can view cookie and other privacy-related information in Privacy component's Capabilities page https://docs.joomla.org/Help39:Components_Privacy_Capabilities.
