### ISSUE TITLE
User Disable/ Enable Actions Log

### ISSUE THREAD

**Issue by vijaykhollam** [joomla/joomla-cms#25688]
### Steps to reproduce the issue
Login to Joomla Admin using one of the superuser accounts
1. Go to Users => Manage
2. Disable any user 
3. Go to Users => Users Action Log
4. See the latest activity. "User admin updated the user Vijay"

### Expected result
Login to Joomla Admin using one of the superuser accounts
1. Go to users => Manage
2. Disable user
3. Go to Users => Users Action Log
4. See the latest activity. "User admin has disabled the user Vijay."

### Actual result
When any admin user disables/enable to any user from Joomla admin its adds following activity 
"User admin updated the user Vijay" in the User Actions Log.
This information is not correct and not helpful, Ideally, It should add an activity like "User admin has disabled/enabled the user Vijay."

### System information (as much as possible)
Joomla version : Joomla! 3.9.10
![screen shot 2019-07-22 at 14 51 58](https://issues.joomla.org/uploads/1/c59e33c0b7f8fba3d0fdfb2a7107e9f8.png)
![screen shot 2019-07-22 at 14 52 00](https://issues.joomla.org/uploads/1/cc38d6c760212d0f5d472cf27bb9b8e5.png)

**Comment by infograf768** [comment]
I doubt it is possible with what we have now as we have common simplified strings for actionlogs.

For example changing default language is not taken care of.
Same for Feature/Unfeature an article or contact
Same for Checkin or setting/unsetting a menu item as Home, etc.

Basically, it would be extremely complex to deal precisely with every possibility.

@mbabker

**Comment by mbabker** [comment]
Just close as won't fix, for exactly the reasons just given.  Even if you can wire something together (with all the complexity that's going to come with it) to explicitly log actions by the buttons (checkin, feature, enable/disable user, etc.) you're still stuck writing even more complex code if someone changes these attributes from the edit screen when they might be updating multiple fields at once.  While it'd be a nice to have, it just borders on being too complex to sanely deal with.
