### ISSUE TITLE
[4..0] Media Manager - Send a mail onAfterSave

### ISSUE THREAD

**Issue by schnuti** [joomla/joomla-cms#25683]
### Is your feature request related to a problem? Please describe.
As mentioned in another issue the uploads could be logged for privacy reasons. I don't think this is needed as by default the images folder and its content is public. i.e. it makes no sin to store private or copyrighted content in those folders.
But the coin has another side. If uploads are allowed, the site owner is responsible for the content. See new EU-legislation about copyright. The so called social media try to fix this with AI (Artificial Intelligence), Joomla users have to use Manuel Intelligence. 

I think this is for Core and not 3.d Party.

### Describe the solution you'd like
Add a core plugin (onAfterSave) that sends an email (user group dependent) to the Administrator with info about user and the uploaded item. That makes it possible to check if the content of the uploaded item is conform with the sites Terms of Use. e.g. free to use without any credits.

(A media table should be introduced in the near future.)

**Comment by alikon** [comment]
Sounds like a good addition to me

**Comment by alikon** [comment]
after some more look at it we already have something 
ie when you upload an image we log an entry in the user action log 
![Screenshot from 2019-08-11 09-31-33](https://user-images.githubusercontent.com/181681/62831151-e2196f00-bc1a-11e9-9590-d5e9a8c02aad.png)

**Comment by brianteeman** [comment]
As stated by @alikon this is already done by the user actions log and should be closed
