### ISSUE TITLE
[required feature] Add or modify fields in user registration

### ISSUE THREAD

**Issue by Pablo234** [joomla/joomla-cms#25707]
### Steps to reproduce the issue

When you use standard user registration you cant add new fields. Just disable current fields.

### Expected result

Add some basic types: image (for use as logo or avatar for example), text field, text box, etc.

### Actual result

You cant add or modify.

### Additional comments

Create an extender user registration plugin that allows to extend the basic user info.

**Comment by brianteeman** [comment]
This is already possible - see https://docs.joomla.org/J3.x:Adding_custom_fields/User_Field

**Comment by ghost** [comment]
Closed as comment above.

**Comment by Pablo234** [comment]
Your answer is for select an user from a selector.

What I mean is to modify default user profile fields (adding, modifying or removing).

**Comment by brianteeman** [comment]
Sorry but I still dont see what it is that you want that cannot be done already

**Comment by alikon** [comment]
https://github.com/joomla/joomla-cms/issues/25707#issuecomment-515197224 or create your own profile plugin https://docs.joomla.org/Creating_a_profile_plugin

**Comment by alikon** [comment]
not an issue there are already some way<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25707">issues.joomla.org/tracker/joomla-cms/25707</a>.</sub>

**Comment by Pablo234** [comment]
which components are supported?


documentation says contact component and articles (this must be updated)
but i think users component is also supported
