### ISSUE TITLE
Articles: Inserted modules referenced by ID not working

### ISSUE THREAD

**Issue by aci78** [joomla/joomla-cms#25701]
### Steps to reproduce the issue
Add a module in an article using Add module button from the editor.
After choosing the module, we get in the editor's window:

{loadmoduleid 109}

### Expected result

Module with ID 109 should be displayed in the content of the article on the preview page after saving the article.

### Actual result

Error page with: Call to undefined method JModuleHelper::getModuleById()

### System information (as much as possible)

Joomla 3.9.10

PHP 7.2 (ea-php72) 

Web server | LiteSpeed
-- | --
HTTP response code | 200

alt-svc | quic=":443"; ma=2592000; v="35,39,43"
cache-control | no-store, no-cache, must-revalidate, post-check=0, pre-check=0
connection | close
content-encoding | gzip
content-type | text/html; charset=utf-8
date | Wed, 24 Jul 2019 16:57:05 GMT
expires | Wed, 17 Aug 2005 00:00:00 GMT
last-modified | Wed, 24 Jul 2019 16:57:05 GMT
pragma | no-cache
server | LiteSpeed
transfer-encoding | chunked
vary | Accept-Encoding
Time to contact web server | 2.879497 seconds

### Additional comments

If I manually edit the syntax to {loadmodule mod_login,module title} the result is as expected. Please modify back the plugin file loadmodule to use the old syntax by module type and name, not by ID, and also add a warning not to change the module name, otherwise the already inserted module name in old articles will not be updated to the new module name.
 
Thank you

**Comment by alikon** [comment]
unable to reproduce

**Comment by ghost** [comment]
can't confirm too. 

@aci78 have you asked in [Forum](https://forum.joomla.org/)?

**Comment by joeforjoomla** [comment]
By sure not a core issue, a third-party extension is overriding the JModuleHelper class not updated to the latest version including the getModuleById function.

**Comment by ghost** [comment]
closed as no Core-Issue. Can always reopened if needed.

**Comment by aci78** [comment]
![Screenshot_2019-07-25_18-49-16](https://user-images.githubusercontent.com/53271784/61889047-6676ad00-af0d-11e9-8c39-6117b381a7af.png)
![Screenshot_2019-07-25_18-48-55](https://user-images.githubusercontent.com/53271784/61889074-72626f00-af0d-11e9-963c-df32e5938b36.png)

I have to tell that I am using the old router method and the error is real.

**Comment by ghost** [comment]
Test again using legacy routing – works as expected.

Setting | Value
-- | --
PHP Built On | Linux lamp122.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.7.el6h.x86_64 #1 SMP Mon Dec 17 12:02:35 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.24-cll-lve
Database Collation | utf8mb4_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.1.30
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.9.11-dev Development [ Amani ] 10-July-2019 16:04 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by ghost** [comment]
> @aci78 have you asked in [Forum](https://forum.joomla.org/)?

**Comment by ot2sen** [comment]
@aci78 Try to change to the standard Joomla frontend template. When you then see it works to load the module by id, then visit your template provider joomlashine and ask in their support forum.
