### ISSUE TITLE
[Protostar] Possibly redundant code

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#25705]
Pretty sure this statement is redundant.... https://github.com/joomla/joomla-cms/blob/staging/templates/protostar/index.php#L31-L38

1. I can't find $fullWidth been used anywhere
2. I cant get $task === 'edit'

Also... https://github.com/joomla/joomla-cms/blob/staging/templates/protostar/offline.php#L20
And... https://github.com/joomla/joomla-cms/blob/staging/templates/protostar/error.php#L29-L36

**Comment by brianteeman** [comment]
if i remember correctly this was used to make the edit pages full width and not cramped by left and right modules. it was set with mootools iirc

**Comment by Quy** [comment]
The code added [here](https://github.com/joomla/joomla-cms/commit/cd663c07837e050ed2c183956ead8089487412a9#diff-cf538a09535bff6ecf56b6c2404e431d), however, no context provided to determine its purpose. OK to remove?

**Comment by SharkyKZ** [comment]
Yes, it's unused.

**Comment by Quy** [comment]
Please test PR #26361.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25705">issues.joomla.org/tracker/joomla-cms/25705</a>.</sub>
