### ISSUE TITLE
Terms and Conditions

### ISSUE THREAD

**Issue by Pablo234** [joomla/joomla-cms#25706]
### Steps to reproduce the issue

1- Disable Terms and Conds Plugin if you have it enabled

2- Register a new user from the front -> you see the terms and conds radio button from standard form (as a field).

2- Enable Terms and Conds Plugin

3- Go to front and register a new user. You see 2 radio buttons for the same: terms and conds (standard form field) and terms and conds (PLUGIN)

### Expected result

The user should only have one option for accept terms and conds.

When you enable Terms and Conds PLUGIN the field must be overrided or extended, not duplicated.

**Comment by brianteeman** [comment]
The field in the registration form is one that you have created. Only the one from the plugin is one that is part of core joomla

**Comment by ghost** [comment]
closed by comment above.
