### ISSUE TITLE
Please fill out this field Not translatable

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25736]
### Steps to reproduce the issue

Please fill out this field Not translatable 

### Expected result

Please fill out this field translatable 

### Actual result

Please fill out this field Not translatable 

### System information (as much as possible)

Joomla 3.9.10

**Comment by ghost** [comment]
Thanks for Report. Can you please give Information which field you mean, maybe use a Screenshot?

**Comment by brianteeman** [comment]
I am guessing you are referring to a message like this
![image](https://user-images.githubusercontent.com/1296369/62041634-07a68180-b1f4-11e9-98d5-f1b32a062c8f.png)

This message is coming directly from your web browser and is displayed in the language of your web browser

**Comment by ghost** [comment]
![Untitledf](https://user-images.githubusercontent.com/43875462/62042694-5d385980-b207-11e9-8cea-c92c15861dae.png)

use protostar template in contacts

You cant translate thi : Please fill out this field

**Comment by ghost** [comment]
Yes Brian you are right, so its not tranlstable ?

**Comment by infograf768** [comment]
See https://stackoverflow.com/questions/42092145/html5-constraint-validation-translation-with-django

**Comment by brianteeman** [comment]
@Milglius no its not translatable by you. The message is from the browser and will be displayed according to the users own language so that you dont have to translate it

**Comment by ghost** [comment]
closed as no core-issue. 

@Milglius Please ask this kind of questions on [Forum](https://forum.joomla.org/) as this Repository is for coding.

**Comment by brianteeman** [comment]
@franz-wohlkoenig it was a perfectly valid question
