### ISSUE TITLE
[4.0] SEO Settings > Use URL rewriting text display error and possibly elsewhere

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#25731]
### What needs to be fixed
Joomla 4 Alpha 10 Dev text display error in Global Configuration 'Use URL rewriting'
Text taken from joomla-cms/administrator/language/en-GB/en-GB.com_config.ini

### Why this should be fixed
To view the error, in the Admin panel, go to System > Global Configuration > Site > SEO Settings and you will see the text under 'Use URL rewriting' displayed like this, including the new line and bold codes:

`Available for IIS 7 and Apache. <br><strong>Apache users only!</strong><br>Rename htaccess.txt to .htaccess before activating.<br><strong>IIS 7 users only!</strong><br>Rename web.config.txt to web.config and install IIS URL Rewrite Module before activating.<br>`

![Global configuration SEO settings](https://user-images.githubusercontent.com/36987494/62009583-e04ea680-b158-11e9-8f8e-c047f61ce3a3.jpg)

Changing `<strong>[text]</strong> to <b>[text]</b>` makes no difference and changing `<br> to <br />` or using the escape character \n doesn't do anything either.

### How would you fix it
Not sure. I've tried. It would appear that there is an instruction somewhere to strip html tags from this .ini file and possibly all other .ini files, too. This is not the only line that has html in this file. Joomla! documentation says that adding html tags to ini files is fine, so it should work.

### Side Effects expected
Display as author intended

**Comment by brianteeman** [comment]
I thought I submitted a pr for this.

**Comment by brianteeman** [comment]
Yes - it was fixed with #25537

**Comment by ghost** [comment]
closed as fixed by #25537

**Comment by Scrabble96** [comment]
Sorry. I searched 'URL rewriting', 'SEO Settings' and the name of the file, but not 'html in description' before submitting my issue.
