### ISSUE TITLE
[4.0] Polyfill for Details/Summary Elements

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#25749]
Per @C-Lodder in https://github.com/joomla/joomla-cms/pull/25740

> Note that MS Edge does not support the Details/Summary elements (with the accordion effect). The content will always be visible.
> Edge Chromium should be released in late 2019 (which will support it).

Per @brianteeman there is a polyfill available at https://github.com/javan/details-element-polyfill

This tracks that so closer to our release date of J4 we can make a decision based on global browser usage about whether we want to use the polyfill or not

**Comment by dgrammatiko** [comment]
@wilsonge the website we're currently on uses the details element is some interesting ways (as a custom element):
- as a modal https://github.com/github/details-dialog-element
- as a dropdown https://github.com/github/details-menu-element

The dropdown is a no brainer, just import it as is. The modal needs some patching for the iframes...

**Comment by brianteeman** [comment]
As we are already at browser -1version supporting details it should be pretty safe now to close this

**Comment by wilsonge** [comment]
Sounds good to me
