### ISSUE TITLE
[4.0] Errors when opening article edit view and saving article with PostgreSQL database

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#25748]
### Steps to reproduce the issue

When opening the edit view for an article or other things like e.g. tags, a red alert popup with title "Error" and text "An error has occurred." is shown.

When saving a newly created article for the first time, another a red alert popup with title "Error" is shown with following text:

> Save failed with the following error: 23502, 7, ERROR: null value in column "introtext" violates not-null
> constraint DETAIL: Failing row contains (71, 0, test, test, null, , 0, 2, 2019-07-30 17:49:31, 31, ,
> 1970-01-01 00:00:00, 0, 0, 1970-01-01 00:00:00, 1970-01-01 00:00:00, 1970-01-01 00:00:00,
> {"image_intro":"","float_intro":"","image_intro_alt":"","image_i...,
> {"urla":"","urlatext":"","targeta":"","urlb":"","urlbtext":"","t...,
> {"article_layout":"","show_title":"","link_titles":"","show_tags..., 1, 0, , , 1, 0,
> {"robots":"","author":"","rights":""}, 0, *, ).
> An error has occurred.

With an already existing article, the 2nd error does not happen.

On a MySQL database, none of these errors happens, it happens only on PostgreSQL.

### Expected result

No errors.

### Actual result

See above.

### System information (as much as possible)

PHP 7.2
PostgreSQL 10.9

### Additional comments

Maybe the cause of both is the same 1 error, or maybe it is 2 different errors.

**Comment by alikon** [comment]
for the 1st one  see #25752...
i'll investigate further but later for the 2nd one

**Comment by alikon** [comment]
for the 2nd i'm unable to replicate with (#25752 and #25724) both applyied 
just got some warning on the postgresql log
`postgres@joomla WARNING:  nonstandard use of \\ in a string literal at character 242
2019-07-31 19:34:32.412 CEST [5493] postgres@joomla HINT:  Use the escape string syntax for backslashes, e.g., E'\\'.`

p.s
forgot to mention i'm on PostgreSQL (PDO) 11.4 (Ubuntu 11.4-1.1~build1)

**Comment by richard67** [comment]
@alikon the 2nd item is also solved if only #25752 is applied but not #25724 .

**Comment by richard67** [comment]
Closing because both errors solved with PR #25752 .

**Comment by alikon** [comment]
@richard67  you know  i usually made mistake "when on train" :smile:

**Comment by richard67** [comment]
@alikon question is if we will find the unquoted backslash somewhere, and another thing is issue #25747 , which seems to me to be related to errros with database function calls.

**Comment by alikon** [comment]
yet not looked at #25747 sorry...and for sure will need to catch the unquoted backslash....
