### ISSUE TITLE
Translated strings are missing in Joomla! Update

### ISSUE THREAD

**Issue by twister65** [joomla/joomla-cms#25745]
### Steps to reproduce the issue
Install a language pack.
Go to administrator/index.php?option=com_joomlaupdate
Click on the second tab "Upload & Update" translated.
Scroll down to Joomla package file.
The label and description of the button are not translated.

### Expected result
Label and description of "Joomla package file" button are translated.

### Actual result
![Update_file_button](https://user-images.githubusercontent.com/26852967/62113285-98449680-b2b4-11e9-9b02-c67bea2561c7.png)

### System information (as much as possible)
Joomla! 3.9.11-dev (Tuesday, 30 July 2019 02:00:36 UTC)
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0

### Additional comments
COM_INSTALLER_MSG_INSTALL_NO_FILE_SELECTED is present in my localized language file (fr-FR.com_installer.ini).

**Comment by twister65** [comment]
@infograf768 , I don't understand I have:
`COM_INSTALLER_MSG_INSTALL_NO_FILE_SELECTED="Aucun fichier sélectionné"`
in administrator/language/fr-FR/fr-FR.com_installer.ini

**Comment by SharkyKZ** [comment]
These strings are coming from your browser.

**Comment by twister65** [comment]
> These strings are coming from your browser.

With Chrome these strings are translated but not with Mozilla Firefox.

**Comment by SharkyKZ** [comment]
This should depend on browser's language. Maybe your Chrome is in French but Firefox in English? We use a basic file input here.

**Comment by twister65** [comment]
> This should depend on browser's language. Maybe your Chrome is in French but Firefox in English? We use a basic file input here.

![french_firefox](https://user-images.githubusercontent.com/26852967/62116057-d2fcfd80-b2b9-11e9-9eec-770ef177e365.png)

**Comment by twister65** [comment]
It is a Mozilla Firefox issue with Ubuntu.

**Comment by infograf768** [comment]
Same issue on Macintosh/Firefox: translation depends on the browser settings.
The string COM_INSTALLER_MSG_INSTALL_NO_FILE_SELECTED is only used in case of error...
