### ISSUE TITLE
[4.0] edit Authors article so that author can correct some stuff in his submitted but unpublished article

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25757]
### Is your feature request related to a problem? Please describe.

Joomla 4 edit Authors article so that author can correct some stuff in his submitted but unpublished article, now after submitting the article author is in the dar cous it seems as if article disapeared, authos haz 0 access to the submitted article.

### Describe the solution you'd like

Joomla 4 edit Authors article so that author can correct some stuff in his submitted but unpublished article

**Comment by infograf768** [comment]
@Milglius You are saying the present situation is not B/C.
Please state the exact version of Joomla where you consider it was working fine and I will have a look.

**Comment by ghost** [comment]
@infograf768 its in #17812 in the year 2017 it was reported by joomla user as joomla backward compatibility issue, please ask joomla users in #17812 they stated there since which version joomla has  backward compatibility issue

**Comment by infograf768** [comment]
So, if you read somewhere that the Earth is flat, you will quote this as true without checking if it is related to the problem you describe ? 🤣 

https://github.com/joomla/joomla-cms/issues/17812 title is
"frontend created articles are not published but only submitted"

This has nothing to do with the Issue here.

As I said in another post, user with only `core.edit.own` will not be able to re-edit the article after save (**and this as far as J 2.5 at least**) as the code filters the display for Unpublished articles.

The only solution I see, _possibly for J4 if someone codes it_, is to get a `Save & Preview` button which would display the article in a modal without quitting the edit form until the `Save` button is used.

**Comment by ghost** [comment]
Why joomla user Author with core.edit.own will not be able to edit their article after save?

it is bug in joomla core.edit.own then, couse Author should be able to edit his articles

**Comment by infograf768** [comment]
Author is able to edit his article after it is published. This was always the case and therefore you are asking for a new feature which has never been implemented in Joomla and therefore **there is no B/C issue here**.
You are requesting a new feature and that is fine. 
I have posted what I think would be the best solution for J4 as we do not accept new features for J3.

**Comment by ghost** [comment]
So buggy joomla logic was always the case of joomla.

#17812 states its big joomla backward compatibility issue infograf you should read not only titles. As I understand it started since joomla 3.8 I ll try to check it soon.

Why joomla use such a buggy thing as Author is able to see and edit his article after it is published only by other user?

**Comment by ghost** [comment]
@alikon stateted it seems before Joomla 3.5.7

**Comment by alikon** [comment]
@Milglius  please don't cross-post 
thanks

**Comment by ghost** [comment]
ok alikon

**Comment by brianteeman** [comment]
So what you need to do is to find where this changed and the pull request that it was changed in. That will then let you see if it was "by accident" or if it was for a specific reason. Only then will you be in a position to move forward with a solution

**Comment by ghost** [comment]
Brian I was unable to find where this changed. 

@infograf768 so the only solution you see is for J4 to get a Save & Preview button which would display the article in a modal without quitting the edit form until the Save button is used?

Do most of you think this would be the best solution for J4 ?

**Comment by Quy** [comment]
Duplicate #22232

**Comment by ghost** [comment]
it seems it was in joomla 1.0 #27698

**Comment by brianteeman** [comment]
Thats not the same thing.

In that one it is about being able to save the article while you are working on it. Here you are talking about being able to come back at a later date.

**Comment by ghost** [comment]
#27698 brian in that one he is talking "Actually save changes, close editor and shows articles list. Fo continue editing is necessary find the rticle, reopen and find where we are before.".
