### ISSUE TITLE
[4.0]  Same colors for same options

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#25758]
### Steps to reproduce the issue
Go to Categories and creaste new, Publised is in baclground Green amd UInpublished is in background Red.
Go top modules and creaste new, Publised is in baclground Green amd UInpublished is in background Red.
Go top menus and creaste new item, Publised is in baclground Green amd UInpublished is in background ed.
But in articles, creatte new and Publised or Unpublished are transparent background.

### Expected result
That the background in Articles Status  Red for Unpublished, Green for Publih.

### Actual result
But in articles, creatte new and Publised or Unpublished are transparent background.

**Comment by Quy** [comment]
Duplicate #23781?
