### ISSUE TITLE
big joomla 3.x backward compatibility issue frontend created articles are not editable by their authors in frontend

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25755]
### Steps to reproduce the issue
Choose in Menu Create Article Category frontend-edit

In frontend after submitting article Authors do not see their article so they can't edit their article, 
also article is not published. Its big joomla 3.x backward compatibility issue.

frontend created articles are not editable by their authors after they submit article and not published but only submitted.

### Expected result

In frontend after submitting article Authors see their article so they can edit their article, 

### Actual result

In frontend after submitting article Authors do not see their article and they can't edit their article

### System information (as much as possible)

Joomla 3.9.10

**Comment by infograf768** [comment]
Once Submitted, an article created by an author is not displayed until it is Published by at least a Publisher. Therefore it can't be edited by the author. This has always been the case.
 I do not see the B/C issue here...

It is true that it would be nice to have a Preview so that the author can correct some stuff, but this would be a new feature.

**Comment by SharkyKZ** [comment]
Is this a duplicate of #17812?

**Comment by brianteeman** [comment]
How is this a backwards compatibility issue?

**Comment by brianteeman** [comment]
@SharkyKZ yes you are correct and this should be closed here. We only need one issue

**Comment by ghost** [comment]
@Milglius please don't open Issues if they are [reported](https://github.com/joomla/joomla-cms/issues/17812#issuecomment-515884137). This takes time from other Volunteers  they could use better.

**Comment by ghost** [comment]
Its very similar joomla bug but not the same

#17812 is about frontend created articles are not published

but #25755 is about Authors do not see their article after its submitted so they can't edit their article, the article can remain unpublished, but authors should have posibility to edit their unpublished article.

Please reopen this issue couse its similar joomla bug but not the same joomla bug

**Comment by ghost** [comment]
@infograf768 
> 
> Once Submitted, an article created by an author is not displayed until it is Published by at least a Publisher. Therefore it can't be edited by the author. This has always been the case.
> I do not see the B/C issue here...
> 

@infograf768 in #17812 it is reported that this is joomla 3 B/C issue  

Posibility silently disapeared since Joomla 3.8  This is known Joomla 3 backwards compatibility issue since 2017

Issue #25755 reported here is diferent 
So you think that to edit Authors article so that author can correct some stuff in his submitted but unpublished article , would be a new joomla 3.9.10 feature?

**Comment by infograf768** [comment]
I replied about this issue.

**Comment by ghost** [comment]
@infograf768 why you think it is new feature ?

I think its joomla bug

If managers can have this feauture in Joomla 3 why authors cant have this feature in joomla 3 ?
