### ISSUE TITLE
system plugin remember me, not working on IE browser

### ISSUE THREAD

**Issue by visuvelu** [joomla/joomla-cms#25768]
### Steps to reproduce the issue
1. Open IE browser, login to front-end. Check remember option.
2. After logged in, go to your profile and copy the current URL.
3. close IE browser and re-open again.
4. paste and go to the profile URL

### Expected result
Since I chosen remember me it suppose to stay on profile page.

other browsers handled this session cookie, and stay on profile page including edge browser.

### Actual result
On IE, can't able to see the cookie 'remember_me'; it simply redirect to login page.

### System information (as much as possible)
latest joomla version. 3.9.1.
Plugin system - Remember me, enabled.
SSL enabled.

### Additional comments
Works fine on other browsers.

**Comment by ghost** [comment]
> latest joomla version. 3.9.1.

Please update on latest Version and test if Issue is the same.

**Comment by visuvelu** [comment]
> > latest joomla version. 3.9.1.
> 
> Please update on latest Version and test if Issue is the same.
@franz-wohlkoenig 
okay, i have updated the joomla and the latest version is 3.9.10. But still same issue.

**Comment by visuvelu** [comment]
@franz-wohlkoenig any working sample with the latest version? or any cross checks on configuration settings? actually the issue was happened only on IE (version 3.9.8) but after upgraded to latest version (3.9.10) now the same error (missing joomla_remember_me_xxxxx cookie and reopen registered access page it leads to login page only ). 
any other suggestions?

**Comment by visuvelu** [comment]
@brianteeman any suggestions on the above?

**Comment by Quy** [comment]
Which version of IE?

**Comment by visuvelu** [comment]
@Quy IE version 11 and same happens on IE lower versions too. But looks fine on edge

**Comment by HLeithner** [comment]
@visuvelu does this only happens if you go directly to the profile page?

I tested it with IE 11 and it works without issues... so can you send my the url and a test user at harald.leithner@community.joomla.org ?

**Comment by Bakual** [comment]
Check also the Cookie settings in the Joomla configuration.
And try to delete all cookies from that site in your browser, maybe a wrong one confuses the system.
You can also try to manually log out of the page, this should delete the remember-me cookie as well.

**Comment by HLeithner** [comment]
@visuvelu I got your email and tested it with my ie11 and you site without any issues... do you have any virus software or internetsecurity software installed?

I also think it's not a joomla problem and should be asked in the forum. ymmv

**Comment by ghost** [comment]
closed as stated above.

**Comment by visuvelu** [comment]
yes it was my fault.. one of my system plugin override the above action. Thank you @franz-wohlkoenig @HLeithner @Bakual
