### ISSUE TITLE
Can't download nightly builds

### ISSUE THREAD

**Issue by Pawel-Panek** [joomla/joomla-cms#25764]
### Steps to reproduce the issue
```
# curl -v https://developer.joomla.org/nightly-builds.html
* About to connect() to developer.joomla.org port 443 (#0)
*   Trying 72.29.124.158... Connection timed out
* couldn't connect to host
* Closing connection #0
curl: (7) couldn't connect to host
```

### Expected result

Connect to https://developer.joomla.org/ and download updates list.

### Actual result

Connection time out.

### System information (as much as possible)

Centos 6, curl 7.19.7

### Additional comments

Tried from various networks in US and EU.

**Comment by ghost** [comment]
closed as allready reported https://github.com/joomla/joomla-websites/issues/1340
