### ISSUE TITLE
[4.0] Authors upload and insert image in article as simple as is in github

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25762]
### Is your feature request related to a problem? Please describe.

#25755
#17812
#25564 

### Describe the solution you'd like

upload and insert image in article as simple as is in github

**Comment by brianteeman** [comment]
Do you mean like this
![drsag](https://user-images.githubusercontent.com/1296369/62368576-ea8bee80-b524-11e9-8484-f275bd28545e.gif)

**Comment by alikon** [comment]
after the good explanation i'm closing this as not an issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25762">issues.joomla.org/tracker/joomla-cms/25762</a>.</sub>

**Comment by ghost** [comment]
Brian you are genius, but I cant do this in mobile phone android with small screen, or I am missing something ? and we already have such feature ?

**Comment by ghost** [comment]
@alikon please reopen the issue couse @brianteeman solution is not posible with mobile phones.
