### ISSUE TITLE
[4.0] Tidy up the com_templates button layout

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#25772]
### Is your feature request related to a problem? Please describe.
Looking at an installation of 03 Aug 2019 nightly build Joomla_4.0.0-alpha11-dev-Development-Full_Package

In the admin editor (Codemirror) when editing index.php, for example, there are several editor buttons that run onto a second row. It looks rather messy, with the two rows touching each each other and a gap at the beginning of the second row:

![buttons-jammed-together](https://user-images.githubusercontent.com/36987494/62412574-be43a100-b5fc-11e9-950b-1a2b1b5554b7.jpg)

### Describe the solution you'd like
Tidy up the CSS. I have no idea where this code comes from, but using the Firefox inspector I can recommend the following changes end up in template.min.css and/or the html code:

Where the html is 
`<div id="subhead" class="subhead">`
change the associated CSS from
`.subhead {
       padding: 13px 0;
}`
to
`.subhead {
	padding: 13px 0 5px 0;
}`

Then, where applicable to html code like this:
`<button class="btn btn-primary" data-toggle="modal" data-target="[various options]">`
change CSS from
`.subhead .btn-toolbar > * {
      margin-left: .75rem;
}
`
to:
`.subhead .btn-toolbar > * {
      margin-right: .75rem;
      margin-bottom: .5rem; /* new code added */
}`

After this, there is no longer any need for the first-child left margin CSS:
`.subhead .btn-toolbar > :first-child {
    margin-left: 0;
}`

and,
EITHER add a new class to right-align the help button:
`
#toolbar-help {
 margin-right: 0;
}
`
OR, change the html:
`<joomla-toolbar-button id="toolbar-help" class="ml-auto">` to
`<joomla-toolbar-button id="toolbar-help" class="ml-auto mr-0">`

It will now all look like this:

![buttons-tidied](https://user-images.githubusercontent.com/36987494/62412840-a4f02400-b5ff-11e9-9769-d0fa08a72cb5.jpg)

### Additional context
This could possibly apply to other areas of the Admin panel.

**Comment by brianteeman** [comment]
Its nothing to do with codemirror.

**Comment by Quy** [comment]
Please test the new backend template PR #25570. There is a link to the nightly build in the PR.

**Comment by Quy** [comment]
Duplicate PR #24579. Here is the new backend template.

![25772](https://user-images.githubusercontent.com/368084/62416178-a8c57b80-b5ea-11e9-9878-fb46159911f9.jpg)

**Comment by ghost** [comment]
closed as stated above.

**Comment by Scrabble96** [comment]
I have just installed the 'new' backend template as per PR #25570 

The button layout is fine when you first click into the template files system:

![files](https://user-images.githubusercontent.com/36987494/62422099-f999aa80-b6a4-11e9-8212-fcd90bd95ebe.jpg)

BUT, as soon as you select a file to edit, there is almost the same layout I mentioned earlier, except that the Help button is correctly right-aligned:

![new-dev-layout](https://user-images.githubusercontent.com/36987494/62422071-7d9f6280-b6a4-11e9-9a0f-ceed097f4f77.jpg)

**Comment by brianteeman** [comment]
We could group all the file/folder actions into a single dropdown button

**Comment by brianteeman** [comment]
Can the title of this be changed to com_templates from codemirror pplease

**Comment by Quy** [comment]
Please test PR #29446
