### ISSUE TITLE
[4.0] Display user name and not user type on frontend and both name and type in admin panel

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#25771]
### Is your feature request related to a problem? Please describe.
This is similar to, but not the same as, #24862. Sorry if it's been raised elsewhere; I couldn't find anything.

This is on an installation of Joomla_4.0.0-alpha11-dev-Development-Full_Package.zip building Sat 3rd August.

On the front end after logging in, it says "Hi Super User"
![frontend-display](https://user-images.githubusercontent.com/36987494/62412357-0a8ce200-b5f9-11e9-97fd-40c6a697acef.jpg)

In the admin panel, under 'Logged-in users', it displays the user type, rather than the name. 

![admin-panel](https://user-images.githubusercontent.com/36987494/62412401-8dae3800-b5f9-11e9-8c1a-5a3cf55f2357.jpg)

### Describe the solution you'd like
Front end: display user name, not user type
Admin: perhaps it could display both name and user type? As it is, it's not very helpful.

### Additional context
None

**Comment by SharkyKZ** [comment]
`Super User` is the name of the default user. Name can be changed in user profile.

**Comment by Scrabble96** [comment]
Ah, yes. But perhaps it would still be useful to display user type along with name in the Admin panel? Not necessary if there only a few users, but perhaps if there are many.

**Comment by infograf768** [comment]
Imho, the issue is mostly to normalize `Logged-in Users` and `Latest Actions` as one uses the Name and the other the Username.

<img width="675" alt="Screen Shot 2019-08-03 at 17 12 37" src="https://user-images.githubusercontent.com/869724/62413710-4c765200-b612-11e9-9c64-0026084acebb.png">

afaik, Username is unique while Name is not.

**Comment by brianteeman** [comment]
Unfortunately whilst I agree it would be a good idea to display the usergroup that the user belongs to it gets a bit tricky when you have users who are members of multiple usergroups

**Comment by infograf768** [comment]
usergroups have nothing to do with OP

@Scrabble96
Imho frontend is fine as the user will recognize her/his Name.

**Comment by brianteeman** [comment]
> usergroups have nothing to do with OP

I understood the question where it says "user type" to mean "usergroup"

**Comment by alikon** [comment]
just making a reference to #25774

**Comment by Scrabble96** [comment]
Thank you, @alikon, @brianteeman 's PR #25774 is a good suggestion. And yes, I did mean usergroup and I understand your comment re users belonging to multiple groups. 

I will close this issue.
