### ISSUE TITLE
error handling in LanguageHelper::parseIniFile

### ISSUE THREAD

**Issue by thalueng** [joomla/joomla-cms#25789]
### Steps to reproduce the issue
$php_errormsg is deprecated in PHP 7.2

### Expected result
replace with error_get_last()

**Comment by ghost** [comment]
~Please give System information (as much as possible)~
From Issue Tracker its about 3.9.10.

**Comment by infograf768** [comment]
See https://www.php.net/manual/en/reserved.variables.phperrormsg.php

https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Language/LanguageHelper.php#L445

**Comment by Quy** [comment]
For reference PR #17856

**Comment by brianteeman** [comment]
Could someone please change the label to J4 Issue

**Comment by richard67** [comment]
Closing as having a pull request. Please test #41908 . Thanks in advance.
