### ISSUE TITLE
[4.0] Security Headers plugin breaks Com_fields

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25787]
### Steps to reproduce the issue
1. Enable the Security Headers plugin with default options

2. Try to create a new field of any of the following types

- checkboxes
- radio
- list
Which I believe are the only fields with the layout `"joomla.form.field.subform.repeatable-table"`

### Expected result
page refreshes and you can create a field

### Actual result
the template doesn't load and checking the source you can see the code in the head is broken
![image](https://user-images.githubusercontent.com/1296369/62498666-de7b8780-b7d7-11e9-95e3-f9d8bfdb37fb.png)

### Additional comments
Disable the plugin (which means that no nonce is created etc) and com_fields works as expected

//cc @zero-24

**Comment by zero-24** [comment]
Confirmed seams to be an regression from this commit https://github.com/joomla/joomla-cms/commit/86a0d88e415112553ede15e989cfa1b81a32e15c

Here is a fix please test: https://github.com/joomla/joomla-cms/pull/25788
