### ISSUE TITLE
"Partage de Session" rend le JFactory::GetUser() null

### ISSUE THREAD

**Issue by EmmanuelVAS** [joomla/joomla-cms#25799]
### Steps to reproduce the issue

Configuration globale de Joomla :
Activer les "**Sessions Partagées**" (onglet "système")
Puis depuis le back-office, édition d'un article ou autre, utiliser un plugin de type "filemanager" ou "jfilemanager" (ex: parcourir les images du serveur) > Le  JFactory::getUser() vaut null... On est donc considéré comme guest. On ne peut donc pas parcourir.
Message obtenu : _500:"Le navigateur de fichier est désactivée pour des raisons de sécurité. S'il vous plaît contactez votre administrateur système et de vérifier vos autorisations des utilisateurs et des niveaux d'accès."_

### Expected result

Avoir un $user valide
Pouvoir parcourir les images du serveur

### Actual result

$user vaut null
On ne peut pas parcourir le dossier images

### System information (as much as possible)
Joomla 3.9.10
PHP 5.7

**Comment by infograf768** [comment]
Please use English in this repo.

**Comment by infograf768** [comment]
BTW, this message (in French) is not present in core french pack and its equivalent also absent in en-GB..

**Comment by ghost** [comment]
closed as no Core-Issue. 
@EmmanuelVAS Please ask on [Forum](https://forum.joomla.org/) as this Repository is for coding.

**Comment by EmmanuelVAS** [comment]
Hi,

Thanks for your (extreme) quick answer.
I have been clumsy in the writing of the issue...

Sorry for bothering, all i was first saying is :

it seems that *JFactory::getUser()*; doesn't work from everywhere with 
the "*shared sessions*" global option activated.

The error i got was dumped from 
/plugins/editors/jckeditor/plugins/jfilebrowser/lang/fr.js

and because 
/plugins/editors/jckeditor/jckeditor/includes/ckeditor/plugins/authenticate.php 
is unable to get the Joomla User anymore.

Best regards,


-- 
Emmanuel LOISELET

Développement Sites Internet
VA Solutions
3 rue du Tisserand
44800 St Herblain
Tel : 02 40 71 71 22
mail : support@va-solutions.fr

Le 09/08/2019 à 11:45, infograf768 a écrit :

**Comment by infograf768** [comment]
we do understand that your issue comes from a 3rd party plugin, not joomla core. This is why we suggest to post on forums and/or ask the developer of the extension.

**Comment by infograf768** [comment]
FYI: JCK editor has not been updated since 2015. It is totally obsolete. Suggest to change editor.
