### ISSUE TITLE
[4.0] New articles unpublished by default; new modules published by default

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#25794]
### Is your feature request related to a problem? Please describe.
I have installed the latest Alpha 11 dev update (6th August 2019) on one domain and the new backend template ref PR #25570 on another. This issue applies to both.

There is an inconsistency between new articles' and new modules' published status:

If you create a new article, the default status is 'Unpublished' with the Status button 'Unpublished' having a neutral grey background. (In J3.9.10 the default status is 'Published', displayed with a green background and the unpublished status has a red background).

If you create a new module, the default status is 'Published' with the Status button for 'Published' having a bright green background. This is the same as J3.9.10.
If you save the module and then save a copy, the default status is set, as expected, to 'Unpublished' and this has a bright red background.

### Describe the solution you'd like
1. The 'Unpublished' status for articles should have a red background
2. New Articles and Modules (but not new copies) should both be 'Published' by default and the status should have a green background.

**Comment by SharkyKZ** [comment]
First point is a duplicate of https://github.com/joomla/joomla-cms/issues/23781.

Second point is expected behavior. It's the new Workflows feature in 4.0. Default status for new articles is Unpublished. This can be changed by modifying the Workflow.

**Comment by ghost** [comment]
closed as stated above.
