### ISSUE TITLE
Be able to set user permissions for frontend site config options

### ISSUE THREAD

**Issue by saraheagle** [joomla/joomla-cms#25791]
### Steps to reproduce the issue
- Login to the front-end as an Administrator (not super user)
- Go to the frontend site config options /index.php?option=com_config&view=config&controller=config.display.config

### Expected result
- Be able to see the options to edit them

### Actual result
- Blank page

### System information (as much as possible)
PHP Built On	Windows NT TERROR 10.0 build 17763 (Windows 10) i586
Database Type	mysql
Database Version	5.5.5-10.1.31-MariaDB
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.2.4
Web Server	Apache/2.4.33 (Win32) OpenSSL/1.1.0g PHP/7.2.4
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.9.10 Stable [ Amani ] 10-July-2019 15:57 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

### Additional comments
It would be great if there was a way in the admin area to set permissions so that I could allow my site admins to access this from the front end. Is this something that could be done?

The main issue is them being unable to access default meta keywords & description.

Thank you

**Comment by brianteeman** [comment]
Users at the level can not access global configuration in the admin either - which is by design so making this change to let them access global configuration in the frontend would not be a good idea. The content of that config is deliberately restricted.

**Comment by ghost** [comment]
@saraheagle if the Issue don't need further Discussion please close it.

**Comment by saraheagle** [comment]
Thanks for the reply, is there a security concern with changing the config file from the front end in general? I am just wondering about creating a small extension so my customers can edit just the meta keywords & description.

**Comment by brianteeman** [comment]
It is not about the frontend per se. The issue is that to update then you are giving access to the main configuration.php which contains sensitive data.

If it is just for the meta fields then I would go for a different approach. I am sure there must be extensions that exist which will let you set a meta description in the db and then use that instead of the data in the configuration.php.

Not tried it but take a look at https://kubik-rubik.de/efseo-easy-frontend-seo

**Comment by saraheagle** [comment]
I see, thanks very much for your help :)
