### ISSUE TITLE
Tags are not tracked in the COMPARE feature in versions

### ISSUE THREAD

**Issue by vdrover** [joomla/joomla-cms#2579]
#### Steps to reproduce the issue
1. Install fresh j3.2.0 on localhost with php5.4.3 and MySQL 5.5.20. I used the new multilingual install feature and the following languages: English (GB), FR, HU and Afrikaans.
2. Open an article, add a tag and a version note.
3. SAVE.
4. Click the version button and compare the 2 versions.

#### Expected result
When comparing, the tag added as described above in Step 2 should be indicated as a change.

#### Actual result
There is no field showing tags at all in the comparison.

#### System information (as much as possible)
Database Version	 5.5.20
Database Collation	 utf8_general_ci
PHP Version	 5.4.3
Web Server	 Apache
WebServer to PHP Interface	 apache2handler
Joomla! Version	 Joomla! 3.2.0 Stable [ Ember ] 6-November-2013 14:00 GMT
Joomla! Platform Version	 Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.57 Safari/537.36

**Comment by wilsonge** [comment]
Version history acts on the 'base content' fields. As tags are an 'extension' to the UCM base content fields they aren't tracked by user history. Whilst this is inconvenient given the current code structure this won't be changed in the foreseeable future.
