### ISSUE TITLE
Make restore.php PHP 7.4 compatible

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#25800]
Upgrading to @nikosdion current version of restore.php makes more trouble then fixing our version to support php 7.4.

See https://github.com/joomla/joomla-cms/pull/25793

We need a PR to change indexed string accesses from {} to [] syntax

**Comment by richard67** [comment]
There is PR #25782 . As far as I can see, @SharkyKZ had included restore.php and later reverted that due to upgrading. So if he again reverts the last commit, which is the revert commit, it should come back and all is fine. Or am I wrong?

**Comment by HLeithner** [comment]
Yes but should an own PR for better testing, because breaking the upgrade system could be a real pain. So if @SharkyKZ can create a new pr (and change the copyright information requested by nik) it would be great.

**Comment by ghost** [comment]
Closed as having Pull Request #25801
