### ISSUE TITLE
Undefined property: Joomla\CMS\Updater\Update::$downloadurl

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#25827]
### Steps to reproduce the issue
Install 3.9.10
Upgrade to 3.9.11-rc
Go to `Global Configuration > Joomla! Update`
Change to `Testing`
Go to `Components > Joomla! Update`
Under `Reinstall package URL` section, see warning.

### Actual result
```
PHP Notice:  Undefined property: Joomla\CMS\Updater\Update::$downloadurl in \administrator\components\com_joomlaupdate\views\default\tmpl\default_reinstall.php on line 34
PHP Notice:  Trying to get property '_data' of non-object in \administrator\components\com_joomlaupdate\views\default\tmpl\default_reinstall.php on line 34
PHP Notice:  Undefined property: Joomla\CMS\Updater\Update::$downloadurl in \administrator\components\com_joomlaupdate\views\default\tmpl\default_reinstall.php on line 35
PHP Notice:  Trying to get property '_data' of non-object in \administrator\components\com_joomlaupdate\views\default\tmpl\default_reinstall.php on line 35
```

@zero-24

**Comment by richard67** [comment]
Release blocker?

**Comment by zero-24** [comment]
As mention here: https://github.com/joomla/joomla-cms/issues/25766#issuecomment-520575725 the current collection.xml update server does not support minimum stability. The first steps for that are included here: https://github.com/joomla/joomla-cms/pull/25809 but for the full support we need to do some more steps as mention in the issue above.

For a workaround here is the update server PR: https://github.com/joomla/update.joomla.org/pull/141 cc @HLeithner 

For showing the correct `no download` message here we also need to fix this check here: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_joomlaupdate/views/default/tmpl/default.php#L48

So some steps todo but nothing that should held back the current update as there we only use stable stability ;)

**Comment by HLeithner** [comment]
@Quy can you test again with clean cache, it should be ok now.

**Comment by Quy** [comment]
@HLeithner OK now.

**Comment by zero-24** [comment]
Please check this PR: https://github.com/joomla/joomla-cms/pull/25924 this fixes the root cause of the problem in com_joomlaupdate. Thanks!
