### ISSUE TITLE
[4.0] RFC - enable smart search by default

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25826]
Now that there is just one search in joomla 4 shouldn't smart search be enabled by default on all new installs?

![image](https://user-images.githubusercontent.com/1296369/62888854-16368200-bd38-11e9-95e5-6ddc8fc625ee.png)

cc/ @wilsonge @hackwar

**Comment by wilsonge** [comment]
Yes please

**Comment by wilsonge** [comment]
Although we have to be careful because any sample data installed in sql (especially thinking `localise.sql` packs and the `custom.sql` file) will not be indexed into smart search as it stands. But by enabling the plugin all other content will be indexed

**Comment by brianteeman** [comment]
dont think there is anything we can do about that

**Comment by wilsonge** [comment]
We could try forcing an index as part of install after the sql has run. but not sure how easy or not that's going to be. it should be fairly quick as there's never going to be *that* much data on install

**Comment by brianteeman** [comment]
Closed - see #25839
