### ISSUE TITLE
[4.0] template editor directory tree icons not linked

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#25835]
### Steps to reproduce the issue
Select System > Templates > Site Templates > open Cassiopeia
Click on a folder icon 

### Expected result
The folder/directory tree should open, as it does in J3.

### Actual result
The tree does not open. Only if you click on the adjacent word, e.g. 'css' or 'html'.
Instead, in Firefox, it highlights the whole link with a blue box:

![directory-tree](https://user-images.githubusercontent.com/36987494/62961470-bc47c200-bdf4-11e9-8fc1-27b40d0aaa7b.jpg)

It doesn't work in Chrome, either, although there is no blue box. In both cases, the blue becomes darker on hover.

### System information (as much as possible)
Tested on last night's backend Dev nightly installation and also the main Alpha 11 Nightly from 9th August.

### Additional comments
On a side note, it would be even better if the file icons were white rather than blue, to differentiate them more obviously from the folder icons, as they are in J3:

![J3-white-icons](https://user-images.githubusercontent.com/36987494/62961829-6889a880-bdf5-11e9-8b62-1e01183577bd.jpg)

**Comment by brianteeman** [comment]
The reason they are not clickable I believe is because the icon has an aria-hidden attribute

**Comment by Scrabble96** [comment]
Can it be removed?

**Comment by brianteeman** [comment]
No - it is there for accessibility. Maybe there is some other option - I will investigate it. Thanks for reporting.

**Comment by SharkyKZ** [comment]
Test PR #25836 please.

**Comment by brianteeman** [comment]
cool - i was completely wrong
