### ISSUE TITLE
Email address validation is missing while registration

### ISSUE THREAD

**Issue by jaisheela** [joomla/joomla-cms#25838]
### Steps to reproduce the issue
-Go to Joomla Registeration page  YourSite/index.php?option=com_users&view=registration
-Fill the registration form with username,password
-Enter Email Address  , such as tove@gmailcom
-Confirm Email Address ,  such as tove@gmailcom
-Click on Register
-Give a successful message

### Expected result

Should not accept any email address which does not have format as this **xyz@xyz.com**

### Actual result

Takes a incorrect input , accept the incorrect email id  such **xyz@xyzcom**
Also accepts **q1@com** which is incorrect
### System information (as much as possible)

Joomla version is 3.9.11.
Database Version | 5.7.27-0ubuntu0.16.04.1
PHP Version | 7.0.33-8+ubuntu16.04.1+deb.sury.org+1
Web Server | Apache/2.4.18 (Ubuntu)

**Comment by brianteeman** [comment]
This is working as intended. The examples you gave are valid

**Comment by simbus82** [comment]
> This is working as intended. The examples you gave are valid

Really???
tove@gmailcom
xyz@xyzcom
q1@com

They are not valid email address...

**Comment by HLeithner** [comment]
For easier read I link to wikipedia and not to rfc822 that explains which is a valid e-mail address https://en.wikipedia.org/wiki/Email_address

Examples from wikipedia:

> simple@example.com
very.common@example.com
disposable.style.email.with+symbol@example.com
other.email-with-hyphen@example.com
fully-qualified-domain@example.com
user.name+tag+sorting@example.com (may go to user.name@example.com inbox depending on mail server)
x@example.com (one-letter local-part)
example-indeed@strange-example.com
admin@mailserver1 (local domain name with no TLD, although ICANN highly discourages dotless email addresses)
example@s.example (see the List of Internet top-level domains)
" "@example.org (space between the quotes)
"john..doe"@example.org (quoted double dot)

Here is your example:

> admin@mailserver1 (local domain name with no TLD, although ICANN highly discourages dotless email addresses)

**Comment by simbus82** [comment]
@HLeithner i know the good old RFC822 **from 1982**. 

> "_ICANN highly discourages dotless email addresses_"

We need to check if we are in a local environment, because this "validation" is going against the basic user experience, producing registration errors, duplicated accounts, failure to receive validation emails, user management errors, etc.

In 2019, we need to stop thinking like "blind" developers but we need to think like "customers" of Joomla CMS.
I do not think people are happy to know that to CMS let me subscribe to an email like myname.lasname@gmailcom, losing all communications between cms and user's email address, only because I give a typo in a account registration field.
How many Joomla CMSes are installed like an "intranet / local app" that need dotless address, versus the biggest part of Joomla CMSes developed for standard websites?

**Comment by HLeithner** [comment]
iirc a@com is a used email address at least it had been used.

Also it would be possible that google starts to use search@google as email account or sales@amazon.

But anyway patches are welcome against j4, add a possibility to extend the email filter for user registration or email validation. I'm not sure if our current filter can easy filter addresses without a point but I'm sure it can be extended to do this.

**Comment by manojLondhe** [comment]
I agree with this

@simbus82 

> We need to check if we are in a local environment, because this "validation" is going against the basic user experience, producing registration errors, duplicated accounts, failure to receive validation emails, user management errors, etc.

> I do not think people are happy to know that to CMS let me subscribe to an email like myname.lasname@gmailcom, losing all communications between cms and user's email address, only because I give a typo in a account registration field.
How many Joomla CMSes are installed like an "intranet / local app" that need dotless address, versus the biggest part of Joomla CMSes developed for standard websites?
