### ISSUE TITLE
[4.0] Dashboards

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25851]
Since the merge of the new template the dashboards fail to load

merge error?

```
An error has occurred.
0 Class 'Joomla\Module\Submenu\Administrator\Menu\Menu' not found
```

![image](https://user-images.githubusercontent.com/1296369/63086596-1c02b200-bf48-11e9-9c66-f798727ea25f.png)

**Comment by brianteeman** [comment]
Resolved simply by deleting the file `\libraries\autoload_psr4.php` and let it be automatically regenerated.

(Don't close this for now so others don't report it)

**Comment by ghost** [comment]
Can't confirm.
#### System Information

Setting | Value
-- | --
PHP Built On | Linux lamp129.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.5.el6h.x86_64 #1 SMP Thu Nov 22 10:07:47 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.23-cll-lve
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.7
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 4.0.0-alpha11-dev Development [ Amani ] 29-June-2019 11:27 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by ot2sen** [comment]
Can´t confirm either. Fresh install of nightly and dashboards works well, no issues seen.
![16-08-2019 22-26-54sysdash-ok](https://user-images.githubusercontent.com/790445/63196264-279fc700-c075-11e9-87b4-63decb7c9084.png)

**Comment by brianteeman** [comment]
@ot2sen https://github.com/joomla/joomla-cms/issues/25851#issuecomment-521581904

**Comment by ot2sen** [comment]
kk, for info I guess to have it regenerate. Thats fine. And clean works, which is fine too :)
