### ISSUE TITLE
[4.0]  [backend-template] Admin menu UI display issue when menu title is more than x characters

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#25852]
An image is worth a thousands words:

<img width="243" alt="Screen Shot 2019-08-15 at 11 30 06" src="https://user-images.githubusercontent.com/869724/63086611-87508200-bf50-11e9-93e6-f51d56cbb204.png">

**Comment by ghost** [comment]
Issue confirmed.
#### System Information

Setting | Value
-- | --
PHP Built On | Linux lamp129.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.5.el6h.x86_64 #1 SMP Thu Nov 22 10:07:47 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.23-cll-lve
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.7
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 4.0.0-alpha11-dev Development [ Amani ] 29-June-2019 11:27 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by infograf768** [comment]
We just do not have enough space for this vertical menu.
Modifying the default from 15.625rem (Where does this figure comes from???) to 19 or 20rem (and for other places from 11rem to 14rem) solves the issue:

<img width="349" alt="Screen Shot 2019-08-16 at 19 10 20" src="https://user-images.githubusercontent.com/869724/63185313-ff569f00-c059-11e9-9307-2daa061acb94.png">

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/25922
Closing as we have a patch
