### ISSUE TITLE
[4.0] Buttons

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25854]
Originally reported at https://github.com/joomla/backend-template/issues/410 on 31 July

Notice the space at the bottom of the blue box in the help button ![image](https://user-images.githubusercontent.com/1296369/62202085-89c3b100-b380-11e9-83f2-f82cb5a37ff9.png)

Notice the space at the bottom of the grey box and possibly not enough space on the green box
![image](https://user-images.githubusercontent.com/1296369/62202254-e1fab300-b380-11e9-8194-e0730a75c62c.png)

Perhaps more obvious when active
![image](https://user-images.githubusercontent.com/1296369/62202320-ff2f8180-b380-11e9-9390-89feeffbd69f.png)

Notice the spacing on the dropdown box on all sides
![image](https://user-images.githubusercontent.com/1296369/62202395-225a3100-b381-11e9-9986-cf2374da50d6.png)

Notice that the dropdown is shifted to the right
![image](https://user-images.githubusercontent.com/1296369/62202588-79600600-b381-11e9-831c-82a0ac927a75.png)

Notice the bottom spacing when this is hovered
![image](https://user-images.githubusercontent.com/1296369/62202935-1de24800-b382-11e9-9cac-db4f36c13863.png)

**Comment by N6REJ** [comment]
as I stated in #26374 this is being caused by a inconsistent box size between elements.  Quite frankly I don't understand why the elements are stacked instead of being part of the bar itself.

**Comment by brianteeman** [comment]
Closed as most of this has been resolved and the rest is very minot
