### ISSUE TITLE
[4.0] [backend-template] Login page

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25868]
### Steps to reproduce the issue

After installing Joomla 4 for the first time, I go to visit the admin login page, and the "Username" field is showing an error.
This is without me performing a single interaction with the page:

![Screenshot_2019-08-15 J4 - Administration](https://user-images.githubusercontent.com/2019801/63100516-21272780-bf6f-11e9-98a3-a75681f745d4.png)

**Comment by brianteeman** [comment]
Is this only on the first time after installation? 

Which browser are you using

**Comment by C-Lodder** [comment]
Yup, only happens after installation and I click "Visit Backend" or whatever the button says
Using Firefox 68.0.2

**Comment by brianteeman** [comment]
I thought I knew the reason why but if its only on that first time - then I dont

**Comment by C-Lodder** [comment]
Haven't tested on any other browser after the installation, but if I rightly remember, doesn't Firefox have some focus bug?

**Comment by brianteeman** [comment]
Thats what I was thinking (and the validation being triggered on focus) but then it would be every time

**Comment by HLeithner** [comment]
Maybe it's because you come by clicking a link to the backend login, normally you go directly to this page. Could you check this?

**Comment by Quy** [comment]
@C-Lodder Unable to reproduce after installation using Firefox 70.0.1 on Windows 10 Home.

![25868](https://user-images.githubusercontent.com/368084/69181013-30b09200-0ac3-11ea-8294-13f971cfdbfa.jpg)

**Comment by coolcat-creations** [comment]
Unable to reproduce in current staging (4.0) @C-Lodder

**Comment by C-Lodder** [comment]
Closing for now as I can no longer reproduce.
