### ISSUE TITLE
[4.0] [backend-template] Inconsistent hover

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25869]
### Steps to reproduce the issue

1. Go to the Admin Login page
2. Hover over the top-right box

![11](https://user-images.githubusercontent.com/2019801/63100792-b5918a00-bf6f-11e9-8ffd-aff4fe3ad245.png)

### Expected result

Icon and site name change to white at the same time

### Actual result

- Text changes instantly
- Icon has a small animation + delay

**Comment by ghost** [comment]
Can't confirm.
#### System Information

Setting | Value
-- | --
PHP Built On | Linux lamp129.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.5.el6h.x86_64 #1 SMP Thu Nov 22 10:07:47 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.23-cll-lve
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.7
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 4.0.0-alpha11-dev Development [ Amani ] 29-June-2019 11:27 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by C-Lodder** [comment]
@franz-wohlkoenig This also occurs with the top menu icons on the dashboard too.

You should be able to confirm as the icons use:

```
.header .fa, .header .fab {
    transition: all .2s ease-in-out;
}
```
which delays any transition (including colour), by 0.2 seconds

**Comment by brianteeman** [comment]
Confirmed
![hover](https://user-images.githubusercontent.com/1296369/63157862-db6e6b80-c00f-11e9-8a24-38bb766bd0e6.gif)

**Comment by ghost** [comment]
I can't see any difference in @brianteeman 's record but thats me :-)

**Comment by C-Lodder** [comment]
@franz-wohlkoenig https://ezgif.com/speed/ezgif-2-aae037840f27.gif

Change to speed to `10% of current speed`, then view the result below

You'll notice the text becomes white instantly and the icon takes longer to change colour

**Comment by ghost** [comment]
@C-Lodder i trust People having sharp Eyes :-)

**Comment by brianteeman** [comment]
see #27803
