### ISSUE TITLE
[4.0] edit a tag

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#25863]
### Steps to reproduce the issue
edit a tag

### Expected result
able to edit a tag

### Actual result
![Screenshot from 2019-08-15 13-37-29](https://user-images.githubusercontent.com/181681/63092419-01d5cd80-bf62-11e9-8857-16fbcd7d98a1.png)

maybe merged something old with template see #25635

**Comment by ghazal** [comment]
Issue confirmed.

**Comment by SharkyKZ** [comment]
Test PR #25880 please.
