### ISSUE TITLE
[4.0] Backend Template Button Style

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#25860]
### What needs to be fixed
![grafik](https://user-images.githubusercontent.com/828371/63092065-bd95fd80-bf60-11e9-87f7-a5145ec715af.png)
 
Some of the Buttons (Action and Help) have a thin white border below the front part, this should look rather like the other buttons do.

**Comment by brianteeman** [comment]
Duplicate of #25854 Please search before postiing

**Comment by ghost** [comment]
closed as duplicate Report.
