### ISSUE TITLE
[4.0] [backend-template] Top menu hover

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25866]
### Steps to reproduce the issue

Hover over one of the top-right menu items:

![63094685-5df02000-bf69-11e9-96ce-734eeb1c38a1](https://user-images.githubusercontent.com/2019801/63099229-95140080-bf6c-11e9-80c8-2fb6e3e3d2f7.png)

### Expected result

Chrevron and bell icons turn white, as does the text

### Actual result

Icon colours stay the same

**Comment by Quy** [comment]
Not reproducible with Firefox 68.0.2 (64-bit) and Chrome Version 76.0.3809.100 (Official Build) (64-bit).

![25866](https://user-images.githubusercontent.com/368084/63113685-ecec4080-bf47-11e9-9253-1638bb1396ab.jpg)

**Comment by ghost** [comment]
@C-Lodder Can't confirm.
#### System Information

Setting | Value
-- | --
PHP Built On | Linux lamp129.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.5.el6h.x86_64 #1 SMP Thu Nov 22 10:07:47 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.23-cll-lve
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.7
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 4.0.0-alpha11-dev Development [ Amani ] 29-June-2019 11:27 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by infograf768** [comment]
Can't reproduce in Safari, Chrome, Firefox Macintosh

**Comment by ghost** [comment]
closed as not to reproduce. It can always reopened.

**Comment by C-Lodder** [comment]
Was a cache issue
