### ISSUE TITLE
[4.0] Backend Template Article Overview

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#25862]
### What needs to be fixed
The article overview looks still quite messy with all the buttons and icons and their size and position. 
![grafik](https://user-images.githubusercontent.com/828371/63100387-4ae44c80-bf77-11e9-891c-0f65517e1fcb.png)

This was the design proposal for this view, I'd suggest to try to reposition the icons to make the interface more clear.

![grafik](https://user-images.githubusercontent.com/828371/63100553-98f95000-bf77-11e9-8d39-ead92595669a.png)

**Comment by brianteeman** [comment]
You're being a bit unfair with those screenshots

The first is with the filters expanded and the second is not. Its comparing apples to oranges

**Comment by coolcat-creations** [comment]
I will update the screenshot to not be unfair, its still messy.

**Comment by Quy** [comment]
See #28056

**Comment by coolcat-creations** [comment]
Thank you @Quy - closing this as it does not apply anymore
