### ISSUE TITLE
[4.0] Backend Template Quickicons

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#25861]
### What needs to be fixed

![grafik](https://user-images.githubusercontent.com/828371/63092171-21202b00-bf61-11e9-8303-c0ffbf37a1b4.png)

The QuickIcons Buttons and Install Buttons should follow the Buttonstyle that is used accross the template. Currently there are everywhere different buttons.

This was the design proposal, you see here a more consistent styling of the buttons.

![feinschliff](https://user-images.githubusercontent.com/828371/63092148-12d20f00-bf61-11e9-9878-fdda9ffe5198.jpg)

**Comment by brianteeman** [comment]
Things moved on a long way from the design proposal based on discussing in the template repo (as you so often point out). Please see the relevant discussions there

**Comment by coolcat-creations** [comment]
The main repo is a good place to discuss improvements of merged items.

**Comment by brianteeman** [comment]
roflmao says the person who required the private repo.

But fine discuss it here if you want. The people who created the template had very good reasons for not following your design proposal.

**Comment by coolcat-creations** [comment]
so childish...

**Comment by brianteeman** [comment]
Sorry for caring about accessibility and usability and logic

**Comment by coolcat-creations** [comment]
Fine - point me to the discussion where it was said that it's good accessibility, ux and ui to use different button styles everywhere accross the system. I can't imagine any valid point that says: we need to style a button here like that: 
![grafik](https://user-images.githubusercontent.com/828371/63100893-479d9080-bf78-11e9-8a6f-24ba3d93412b.png)
and here like that: 
![grafik](https://user-images.githubusercontent.com/828371/63100912-53895280-bf78-11e9-87cf-068c5599c7e9.png)
And somewhere else different again:
![grafik](https://user-images.githubusercontent.com/828371/63100960-67cd4f80-bf78-11e9-9a62-f12f8e419eb4.png)

**Comment by brianteeman** [comment]
unfollow

**Comment by brianteeman** [comment]
Is there anything to do here or should it be closed

**Comment by coolcat-creations** [comment]
Thank you, I close this issue as it does not apply anymore and will reopen another one regarding the spacings of the elements.
