### ISSUE TITLE
[4.0] Custom Fields in com_contact

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#25864]
### Steps to reproduce the issue
1. Open com_contact 
![Contacts   test   Administration](https://user-images.githubusercontent.com/9974686/63094685-5df02000-bf69-11e9-96ce-734eeb1c38a1.png)

### Expected result
I see a sub menu for creating a custom field.

### Actual result
I do not know how to create a custom field for com_content

### System information (as much as possible)
Current 4.0-dev branch in firefox on ubuntu 18.04

**Comment by brianteeman** [comment]
@astridx This is because the PR to add the contacts to the main menu has not been merged yet

**Comment by astridx** [comment]
@brianteeman Thank you. I did not know this PR. You mean https://github.com/joomla/joomla-cms/pull/23366/, right?

**Comment by brianteeman** [comment]
Yes thats the one
