### ISSUE TITLE
[4.0] Focus outline

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25877]
For some reason we are setting the focus outline to none (not recommended)

```
 .js-focus-visible :focus:not(.focus-visible) {
    outline: none
}

```

And then manually putting it back to each element

```

.custom-select:focus {
    border-color: #368ace;
    outline: 0;
    box-shadow: 0 0 0 .2rem rgba(26,70,107,.25)
}

.custom-select:focus::-ms-value {
    color: #495057;
    background-color: #fff
}

```

But the focus style is not being set for everything - eg switcher

You can see this by going to any option page and try to tab between the fields. When you are in a list you get the outline. When you are focussed on  a switcher you dont

**Comment by brianteeman** [comment]
There is also no focus outline on the cog icon here
![image](https://user-images.githubusercontent.com/1296369/63166327-ff3cac00-c025-11e9-9e8d-8e5c60dda7e1.png)

**Comment by brianteeman** [comment]
There are also inputs that have custom focus outline and other inputs that have default focus outline

![image](https://user-images.githubusercontent.com/1296369/63211581-35932d80-c0f1-11e9-81dd-3c1a6be3ab36.png)

![image](https://user-images.githubusercontent.com/1296369/63211584-3d52d200-c0f1-11e9-9800-bbb9adf4e8dc.png)

**Comment by brianteeman** [comment]
we need to 
1. revert the focus-visible code and polyfill - 1 year after that code was committed there is still no browser that supports focus-visible
2. revert all the element specific outlines
3. remove the outline: none
4. make sure that the default outline: is styled how we want.

Right now its a mess of inconsistencies and accessibility failures

**Comment by wilsonge** [comment]
@dgrammatiko - you mentioned about focus polyfill on our skype call. Can you just drop your comments in here on it

**Comment by dgrammatiko** [comment]
@wilsonge sure. First of all, we need to understand what this `:focus-visible` is. For this, I've created a pen: https://codepen.io/dgrammatiko/pen/rNBjLLd

So if you tab to the first button (default browser CSS) and press enter you'll see that the focus ring is still there
<img width="756" alt="Screenshot 2019-08-22 at 18 54 57" src="https://user-images.githubusercontent.com/3889375/63534158-ccefea80-c50e-11e9-83d4-18569fb04443.png">

If you repeat the process and tab to the green (bootstrap CSS) button you won't get a ring on the button: 
<img width="808" alt="Screenshot 2019-08-22 at 18 55 23" src="https://user-images.githubusercontent.com/3889375/63534235-ff99e300-c50e-11e9-9c5b-2ae662afa29d.png">

So bootstrap is breaking an accessibility rule here and buttons are not the only elements that BS is breaking that rule.

So focus-visible is a pseudo-class that allows better control of the ring, eg we don't need a ring for the mouse but we need one on the keyboard. Obviously patching Bootstrap all over the place to get it right might be something that the project won't like to do. So, I guess, a small hiccup in the accessibility by removing this polyfill and using the code (as is) form Bootstrap is also ok.

**Comment by dgrammatiko** [comment]
> revert the focus-visible code and polyfill - 1 year after that code was committed there is still no browser that supports focus-visible

Well that's not accurate: https://caniuse.com/#search=focus-visible

**Comment by brianteeman** [comment]
One browser supporting it with a vendor prefix is hardly support

This is nothng to do with bootstrap but sadfly once again you let your prejudice get the better.

Clearly you have no wish to do anything constructive.

</unsubscribed>

**Comment by dgrammatiko** [comment]
> This is nothng to do with bootstrap but sadfly once again you let your prejudice get the better.

Sure, that's because I'm an idiot and I can't understand when a rule is broken...

**Comment by brianteeman** [comment]
Show me an example on https://getbootstrap.com where there are buttons with no outlines on keyboard focus - I checked every page of the site and every example

**Comment by dgrammatiko** [comment]
@brianteeman dude can you please take it easy?
I already stated that this polyfill can be removed but I went ahead and created a pen to demonstrate one of the cases this polyfill was covering (try it with safari for better understanding)...

**Comment by brianteeman** [comment]
I am referring to your comments about bs

I am happy for the polyfill to stay but it has "broken" so many things it is easier to remove it and the associated css changes.

**Comment by brianteeman** [comment]
@ciar4n could you take a look at this please. The closer I look at the problem with the missing outline on the cog the more it looks like a css specificity issue. But I suck at css

**Comment by ciar4n** [comment]
I guess the issue here is the focusable elements of the switcher (inputs) are always hidden. Basically, the default browser/bootstrap method of focus will not work here. Focus CSS specific to the switcher can be added to get around this.

Is there any other fields missing a focus?

**Comment by ciar4n** [comment]
Also, what is the preferred focus styling for J4. There appear to be some variations.

**Comment by brianteeman** [comment]
I never said anything about the switcher

**Comment by ciar4n** [comment]
@brianteeman 

> But the focus style is not being set for everything - eg switcher

**Comment by ciar4n** [comment]
#26377 .. PR adding focus styling for the switcher which is mentioned in the description of this issue.

**Comment by brianteeman** [comment]
fixed the issue with the cog

closing for now
