### ISSUE TITLE
[4.0] Disabled buttons

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25874]
All disabled buttons are "faded"  and removed from the tab order which is great. But sometimes the colour is such that a sighted user can't tell if its a design colour or a disabled button.

To make it easier to tell for a sighted mouse user I see that the action button changes the cursor when it is disabled but for some reason the search-clear button doesn't

![image](https://user-images.githubusercontent.com/1296369/63102883-dd82ec80-bf73-11e9-9513-5a3cd0536963.png)

![image](https://user-images.githubusercontent.com/1296369/63102897-e70c5480-bf73-11e9-8057-8d0cbe46c63b.png)

**Comment by ghost** [comment]
Closed as having Pull Request #25933
