### ISSUE TITLE
[4.0] [backend-template] Toolbar dropdown animation is glitchy

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25879]
### Steps to reproduce the issue

1. Reduce the size of your viewport
2. Go to edit a user
3. Click the "Toolbar" button to expand/collapse the toolbar

### Expected result

Smooth animation

### Actual result

Glitchy animation

### System information (as much as possible)

- Firefox 68

### Additional comments

Not look at any of the code but at a guess, you're not taking into consideration the padding/margin, so the JS is having to recalculate the height.

![Screenshot_2019-08-15 Users Edit Profile - J4 - Administration](https://user-images.githubusercontent.com/2019801/63104484-fb9e1c00-bf76-11e9-8524-af354061a590.png)

**Comment by ghost** [comment]
Issue confirmed.

**Comment by Quy** [comment]
Duplicate #27531
