### ISSUE TITLE
[4.0] [backend-template] Add dashboard module colour

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25878]
### Steps to reproduce the issue

Go to:
> administrator/index.php?option=com_cpanel&view=cpanel&dashboard=system

The white dashed box at the bottom allowing you to add a new module to the dashboard is pretty hard to see, as the white border/icon is too light of a colour for the light grey background.

![Screenshot_2019-08-15 System Dashboard - J4 - Administration](https://user-images.githubusercontent.com/2019801/63104038-18861f80-bf76-11e9-9740-f1723389602c.png)

**Comment by Mari234** [comment]
you can change it in the file _com_cpanel.scss in joomla-cms\administrator\templates\atum\scss\pages in line 127. Change the border color from white to one which can be seen better and fits the design. Or the border could be thicker in order to not have a third forth color in the design
```
 .cpanel-add-module {
    background-color: var(--atum-bg-light);
    color: var(--atum-text-dark);
    border: 0.125rem **var(--white)** dashed;
    position: relative;
    transition: all .3s ease-in;
```

**Comment by infograf768** [comment]
In fact the whole "box" is clickable. Why not use the default `<a` colour and take off its black override and use the same colour for the dashed border?
```
.cpanel-add-module {
    background-color: var(--atum-bg-light);
    border: .125rem dashed var(--atum-link-color);
    position: relative;
    transition: all .3s ease-in;
```

This would give:

<img width="647" alt="Screen Shot 2019-10-30 at 09 02 35" src="https://user-images.githubusercontent.com/869724/67839481-1010a000-faf4-11e9-9b2e-00f5c501b145.png">

**Comment by Mari234** [comment]
i think it looks better that way and the text is easier to read

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/26872

Closing as we have a patch
