### ISSUE TITLE
[4.0] [backend-template] Add read-more link

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25873]
### Steps to reproduce the issue

1. In the Joomla backend, go to create an new article.
2. in TinyMCE, click on **CMS Content** >> **Read More**

### Expected result

Add a "read more" link to the article

### Actual result

An alert saying one already exists.

![screeny](https://user-images.githubusercontent.com/2019801/63102657-736a4780-bf73-11e9-9be4-a1f5016f51fe.png)

**Comment by brianteeman** [comment]
confirmed

**Comment by infograf768** [comment]
One gets this wrong alert when the readmore is added in an empty textarea, otherwise it works fine.

The js does not take into account an empty textarea.
```
var content = window.Joomla.editors.instances[editor].getValue();

    if (content && !content.match(/<hr\s+id=("|')system-readmore("|')\s*\/*>/i)) {
      Joomla.editors.instances[editor].replaceSelection('<hr id="system-readmore">');
    } else {
      // TODO replace with joomla-alert
      alert(options.exists);
      return false;
    }
```

After modifying to
```
    var content = window.Joomla.editors.instances[editor].getValue();

    if (content && !content.match(/<hr\s+id=("|')system-readmore("|')\s*\/*>/i)) {
      Joomla.editors.instances[editor].replaceSelection('<hr id="system-readmore">');
    }
    else if (!content) {
    	Joomla.editors.instances[editor].replaceSelection('<hr id="system-readmore">');
    } else {
      // TODO replace with joomla-alert
      alert(options.exists);
      return false;
    }
```
we have no more error and get the same behavior as in 3.x

**Comment by infograf768** [comment]
Closing as we have a patch
https://github.com/joomla/joomla-cms/pull/25907
