### ISSUE TITLE
[4.0] [backend-template] Auto navigate to tab

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25875]
If I rightly remember, Phil Taylor added support for this in J3

### Steps to reproduce the issue

Go to the following URL:

> administrator/index.php?option=com_content&view=article&layout=edit#permissions

### Expected result

Opens a "New Article" page and auto navigates to the "Permissions" tab

### Actual result

Opens a "New Article" page:

1. Doesn't navigate to the permissions tab
2. Throws an error in the console

![screeny2](https://user-images.githubusercontent.com/2019801/63102935-00150580-bf74-11e9-8576-d0632d9bdd1c.png)

**Comment by brianteeman** [comment]
Duplicate of https://github.com/joomla/joomla-cms/issues/25359 ??

**Comment by C-Lodder** [comment]
My bad. Closing
