### ISSUE TITLE
[4.0] [backend-template] Bottom link cut off on smaller devices

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25870]
As you can see in the screenshot below, on a smaller viewport width, the last link is cut off.

![Screenshot_2019-08-15 J4 - Administration](https://user-images.githubusercontent.com/2019801/63101009-220c8900-bf70-11e9-865f-68d4531a6c98.png)

**Comment by ghost** [comment]
Issue confirmed.
#### System Information
Setting | Value
-- | --
PHP Built On | Linux lamp129.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.5.el6h.x86_64 #1 SMP Thu Nov 22 10:07:47 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.23-cll-lve
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.7
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 4.0.0-alpha11-dev Development [ Amani ] 29-June-2019 11:27 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by brianteeman** [comment]
Closed see #27865
