### ISSUE TITLE
[4.0] smart search js error

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#25883]
### Steps to reproduce the issue
Smart Search - index content

### Expected result

content indexed

### Actual result
![Screenshot from 2019-08-16 07-17-03](https://user-images.githubusercontent.com/181681/63145108-5c206e00-bff6-11e9-82b6-044d40c0f2e4.png)

### System information (as much as possible)
4.0-dev

**Comment by infograf768** [comment]
I do not get this error here (FF) but the modal may display differently when the minified js is used or not.

When debug is off, we get:
<img width="980" alt="Screen Shot 2019-08-16 at 09 50 46" src="https://user-images.githubusercontent.com/869724/63152228-9f390c00-c00b-11e9-82f4-b1356d51711c.png">

When debug is on, we get:
<img width="910" alt="Screen Shot 2019-08-16 at 09 53 54" src="https://user-images.githubusercontent.com/869724/63152291-c7c10600-c00b-11e9-8f29-d726a576b4ca.png">

@Hackwar 
Is that desired?

**Comment by Hackwar** [comment]
yes, that is desired debug data.
