### ISSUE TITLE
[4.0] [Installation] PDO can't create database

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#25885]
### Steps to reproduce the issue

Try to install using PDO driver and non-existing database.

### Expected result

Installation succeeds.

### Actual result

Installation fails.

### System information (as much as possible)

4.0-dev nightly

### Additional comments

`Joomla\CMS\Installation\Model\DatabaseModel` has code for creating database but it never runs, installation stops here because PDO driver throws an exception when database doesn't exist.

https://github.com/joomla/joomla-cms/blob/14fee5cff7d8c59c1d8e9cd3cb855af7d06459fd/installation/src/Model/SetupModel.php#L374-L378

**Comment by roland-d** [comment]
Closing as we have a PR #26273
