### ISSUE TITLE
[4.0] [backend-template] Missing external link icon on Help page

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25889]
### Steps to reproduce the issue

Go to `administrator/index.php?option=com_cpanel&view=cpanel&dashboard=help`

### Expected result

Link to "Official Language Forums" should have an "external link" icon as per the other external link

### Actual result

No icon

![Screenshot_2019-08-16 Help - J4 - Administration](https://user-images.githubusercontent.com/2019801/63155131-ec1be300-c009-11e9-84ba-bcfec13e37e3.png)

**Comment by brianteeman** [comment]
The reason is that technically it is not an external link. The link is `index.php?option=com_admin&view=help&layout=langforum` so it doesnt get the external link marker.

It should be fixed though

**Comment by Quy** [comment]
Please test PR #26497<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25889">issues.joomla.org/tracker/joomla-cms/25889</a>.</sub>
