### ISSUE TITLE
[4.0] [backend-template] com_config Options/Permissions not showing properly

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#25898]
### Steps to reproduce the issue
Go to administrator/index.php?option=com_config&view=component&component=com_content for example.
Check Permissions

### Actual result
In Select New Setting, text is cut half way.

![screen shot 2019-08-16 at 10 17 38](https://issues.joomla.org/uploads/1/225023fd50d5ac2f1fdf9a11bcfc07a6.png)

### System information (as much as possible)

OSX
Firefox 68.01 or Microsoft Edge Canary for Mac

**Comment by ghost** [comment]
closed as duplicate report #25887
