### ISSUE TITLE
[4.0] [backend-template] Plugin options duplication

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25899]
### Steps to reproduce the issue

Open any plugin in the Joomla backend

### Expected result

- Ordering
- Plugin Type
- Plugin File
- Note

appear once

### Actual result

They appear twice

![111](https://user-images.githubusercontent.com/2019801/63161771-c3e7b080-c018-11e9-9051-67292b5bf3f3.png)

**Comment by ghost** [comment]
Issue confirmed.

**Comment by infograf768** [comment]
Closing as we have a patch. See https://github.com/joomla/joomla-cms/pull/25913
