### ISSUE TITLE
[4.0] [backend-template] Mising alert from Sample Data installation

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25893]
### Steps to reproduce the issue

1. Login to the Joomla backend
2. Click the button to install Sample Data
3. Wait for it to finish

### Actual result

As you can see in the screenshot below, there is an empty space inbetween the alerts.

This alerts is supposed to read:

> Multilingual Sample Data has been installed!

![screeny2](https://user-images.githubusercontent.com/2019801/63159825-3e620180-c014-11e9-9dce-7c0a276493e3.png)

**Comment by infograf768** [comment]
> This alerts is supposed to read:

  >  Multilingual Sample Data has been installed!

Apparently you did not install Multilingual sample data but the testing sample data and although there is obviously a bug with empty space, the last message correctly display "Testing Sample Data has been installed".

**Comment by brianteeman** [comment]
The white space has the message "Multilingual Sample Data has been installed!" hence the comment.

However this can be closed as a duplicate of #25777
