### ISSUE TITLE
[4.0] [backend-template] Input fields UX

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25891]
A well known UX killer is horizontal forms. Stacked is preferred as it makes scanning much easier

Take the screenshot below as an example. The larger you make your viewport, the harder it is to scan.

![Screenshot_2019-08-16 Modules Articles - Archived - J4 - Administration](https://user-images.githubusercontent.com/2019801/63156267-3a31e600-c00c-11e9-9e34-98d0258702a7.png)

**Comment by brianteeman** [comment]
fully agree - I found it very confusing when navigating with the keyboard

**Comment by micker** [comment]
yes +1 => in media manager order and field placement aren't good
![image](https://user-images.githubusercontent.com/2539440/63340304-02e27280-c347-11e9-9624-8aed4cce8410.png)

**Comment by micker** [comment]
@infograf768 i know you do some change ... some return ?

**Comment by micker** [comment]
i think this is better
![image](https://user-images.githubusercontent.com/2539440/63428438-d8acb580-c417-11e9-9d97-851156dffdbc.png)
maybe we can add css on slider selection to be more visible ?

**Comment by micker** [comment]
i can propose a pr and move order field in xml but not sure that can be a solution in responsive ... some way to link field ?

**Comment by C-Lodder** [comment]
I haven't looked at the markup or CSS properly, but assume it's all in some grid at the moment.
It should ideally be like it was before, everything stacked (with the exception of groups of fields, such as the global configuration settings) and a `max-width` set on the `.form-control` class.

For inputs that require a bigger width (article title and alias), simply use a custom class

**Comment by brianteeman** [comment]
If I understand the css (not always something I do) then this layout is created using css grid and it is not possible with css grid to flow vertically unless you know the exact number of rows which we don't.

The only solution (that I can see) is to switch from css grid to flex which will achieve what we want easily.

**Comment by ciar4n** [comment]
Flex is not really going to work here without changing the markup. **column-count** would be the best option.

**Comment by ciar4n** [comment]
Ignore my last comment. At first read, I thought this was related to field order (#27136).

**Comment by Quy** [comment]
Please test PR #27141<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25891">issues.joomla.org/tracker/joomla-cms/25891</a>.</sub>

**Comment by ciar4n** [comment]
Sorry @Quy you can re-open this. I mentioned the wrong issue in #27141

This is a separate issue.

**Comment by regularlabs** [comment]
Not replying here to join in to the discussion. But just to add my 2 cents and some info.

Today I tried to mock up a plugin in the latest nightly build. And playing around with the plugin edit form.
The whole column layout is bugging me a lot and also creates UX issues.

- There is no control over where it splits the fields to the next column.
So fields that should stay together, might get split up.
- On pages with a lot of fields, you need to scrol down and up and down and up to follow the logical order of fields
- When fields show/hide using the showon thing, the columns get split differently, making fields jump from one to the next column. Major issue, as you have no idea what is going on. (Probably also the reason why the columns are not being used in the global configuration).
- Some field types - like subfields - need more horizontal space. The columns is killing the UX.

Some of the issues I ran into in the first 30 minutes of playing around.

As I said, this is not me trying to discuss these items, just handing over some info.

Also, I have already implemented some code in my first plugin conversion, so that it simply removes the "column-count-md-2 column-count-lg-3" class from the html output of the plugin edit form.
Meaning I don't really care what is done to solve the above mentioned issues. I'm gonna hack my way around issues anyway.

**Comment by brianteeman** [comment]
Thanks for the detailed feedback - full ack

**Comment by regularlabs** [comment]
#Peter googles "full ack"

**Comment by regularlabs** [comment]
Before:
![image](https://user-images.githubusercontent.com/13553242/81168764-eac78780-8f97-11ea-9be6-48f698a5b76f.png)
After:
![image](https://user-images.githubusercontent.com/13553242/81168774-ef8c3b80-8f97-11ea-9d2c-e372b88c43c7.png)

😜

PS: Those nested grouping field sets (Scroll to Top, Slideshow) are not something Joomla provides as a standard option. That is done through my own custom form field elements.

**Comment by coolcat-creations** [comment]
Is it possible to add a class to the fieldset into the xml, and if not, how can something like this be done in Joomla?

**Comment by brianteeman** [comment]
> Is it possible to add a class to the fieldset into the xml, 

Currently only for a field

> and if not, how can something like this be done in Joomla?

Should be a case of adding support in the custom element - joomla-tab

**Comment by Quy** [comment]
See https://github.com/joomla/joomla-cms/issues/27672 for discussion on one column.
See https://github.com/joomla/joomla-cms/pull/27613 to make one column.

**Comment by coolcat-creations** [comment]
I don't think that it should be generally 1,2 or 3 columns. It would be better to have a wrapping class in the fieldset or not? Just like Peter reported that he needs to have control when the column wraps...

**Comment by brianteeman** [comment]
Where it wraps is definitely an issue especially when you have one or more conditional (showon) fields

**Comment by Quy** [comment]
I see one column in Peter's screenshots just like in Global Configurations so I don't see where wrapping is required.

**Comment by coolcat-creations** [comment]
> I see one column in Peter's screenshots just like in Global Configurations so I don't see where wrapping is required.

I meant the before screenshot with the 3 Columns :-)

**Comment by Quy** [comment]
Yes but he prefers the 2nd screenshot which is the same as in Global Configurations.

**Comment by coolcat-creations** [comment]
> Yes but he prefers the 2nd screenshot which is the same as in Global Configurations.

Yes but @regularlabs also said that:

> The whole column layout is bugging me a lot and also creates UX issues.
> 
>     There is no control over where it splits the fields to the next column.
>     So fields that should stay together, might get split up.

I think we need a way to control the columns different than with just a class above it?

**Comment by regularlabs** [comment]
My advise would be:
Get rid of the `column-count-md-2 column-count-lg-3` classes until you offer a way to control the splits in the columns.
A way that could be done is to have sub-field groups that would be wrapped in a div in which the elements stay together. Or something. Again, I don't really care too much. I'll implement my own work-arounds.

**Comment by brianteeman** [comment]
Personally I think the issue in this specific case is that we should not be using columns at all **when** the container is not 100% width

**Comment by Quy** [comment]
Please test PR #29706

**Comment by wilsonge** [comment]
I'm re-opening this as a release blocker as the PR got closed

**Comment by HLeithner** [comment]
I created a RFC PR #31810 any input is welcome. Closing this for the moment can be reopen if pr is not the solution.

**Comment by ciar4n** [comment]
Another possible solution... #32422
