### ISSUE TITLE
[4.0] [backend-template] Accessibility Settings menu item does nothing

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25897]
### Steps to reproduce the issue

Go to the `User Menu` in the top right corner and click `Accessibility Settings`

### Expected result

No idea what it's supposed to do, but probably something

### Actual result

Does nothing

![screeny56](https://user-images.githubusercontent.com/2019801/63160726-5e92c000-c016-11e9-8c8a-c1630288ea5c.png)

**Comment by alikon** [comment]
confirmed

**Comment by richard67** [comment]
Yes, I had discovered that, too, and had reported in the backend template PR. @bembelimen What should that link do? I assume it could be for switching to monochrome.

**Comment by ot2sen** [comment]
Took note of that too when testing last night.
Seemed strange that the Url behind that item changed depending on where you are in the backend. From # to com_users.. etc.

**Comment by brianteeman** [comment]
I guess this can be closed as we have a PR #26194
