### ISSUE TITLE
[4.0] [backend-template] Calendar button styling

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25896]
### Steps to reproduce the issue

1. Edit any article
2. Go to the `Publishing` tab
3. Open on of th calendar fields

### Actual result

The buttons `Clear`, `Today` and `Close` do not look like buttons and thus do not look clickable.

![Screenshot_2019-08-16 Articles Edit - J4 - Administration](https://user-images.githubusercontent.com/2019801/63160442-b11fac80-c015-11e9-8af2-424745bbc84b.png)

**Comment by ghost** [comment]
Issue confirmed.

**Comment by brianteeman** [comment]
Like this ?

![image](https://user-images.githubusercontent.com/1296369/64083315-ddc20c80-cd15-11e9-8235-92e8c5cd4a4f.png)

**Comment by C-Lodder** [comment]
Bit bigger please

**Comment by brianteeman** [comment]
??

**Comment by C-Lodder** [comment]
Bad joke, don't worry

Yes, like the screenshot you provided

**Comment by brianteeman** [comment]
I thought it was a bad joke - just wanted to check

**Comment by ghost** [comment]
Closed as having Pull Request #26142
