### ISSUE TITLE
[4.0] [backend-template] Annoying alerts

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25890]
After installing J4, I find myself having to close alerts after every single action. I must have closed 100 alerts in the space of 30 minutes whilst messing around and trying to find issues with the new template.

Rather than being discrete, they're big and clunky, thus cover up a large portion of the content and must be closed if you wish to continue working.

The alerts Custom Element supports auto dismissing, so I strongly suggest using them for success and info messages

**Comment by brianteeman** [comment]
Thats why I was trying to fix the js on the custom element

**Comment by alikon** [comment]
i'm not a js person, but, @C-Lodder can you submit a pr as it seems you know custom  elements very well, auto dismissing sound good to my annoyed hears

**Comment by brianteeman** [comment]
https://github.com/joomla-projects/custom-elements/issues/123

**Comment by C-Lodder** [comment]
@brianteeman Did you manage to get anywhere with it?

**Comment by brianteeman** [comment]
Not had the opportunity to rry

**Comment by dgrammatiko** [comment]
If someone could verify the a11y of https://codepen.io/dgrammatiko/pen/rXYeWM
I could start populating the new custom elements repo with production ready code

**Comment by brianteeman** [comment]
I can verify that the code you link to is not accessible.

**Comment by dgrammatiko** [comment]
@brianteeman helpful but can you point out what is not a11y?

**Comment by brianteeman** [comment]
You only asked for verification ;)

**Comment by dgrammatiko** [comment]
cool 😎 less work for me then

**Comment by C-Lodder** [comment]
Does anyone actually know what the markup requirements are for accessible alerts?

**Comment by brianteeman** [comment]
yes, me

**Comment by C-Lodder** [comment]
Can you provide it please?

**Comment by brianteeman** [comment]
from memory the current web component iss now ok apart from wanting to fix the auto dismiss

**Comment by Quy** [comment]
Please test PR #27213<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25890">issues.joomla.org/tracker/joomla-cms/25890</a>.</sub>
