### ISSUE TITLE
Articles - Related module Joomla 3.9.11 bug

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25894]
### Steps to reproduce the issue

Articles - Related module 

Position 2

Show Title doesn't work

### Expected result

Show Title is shown

### Actual result

Show Title doesn't show

### System information (as much as possible)

protostar template
joomla 3.9.11

**Comment by ghost** [comment]
Which Module Style you use? If "inherited" try another Style cause its maybe in the Position defined.

**Comment by ghost** [comment]
inherited, why protostar inherited not work ?

**Comment by SharkyKZ** [comment]
Default style for this position is `none` which has no title.

**Comment by ghost** [comment]
"inherited" of Position. Have you tried "another Style cause its maybe in the Position defined."? Or please ask on [Forum](https://forum.joomla.org/) as this Repository is for coding.

**Comment by infograf768** [comment]
Position 2 is
`<jdoc:include type="modules" name="position-2" style="none" />` in the index.php

When style is none, no title displays.
Change to
`<jdoc:include type="modules" name="position-2" style="xhtml" />`
if you absolutely want that module to display its title in the breadcrumbs position.

**Comment by infograf768** [comment]
Closing as not core issue.
