### ISSUE TITLE
[4.0] [backend-template] Tags input field placeholder text

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25895]
### Steps to reproduce the issue

1. Go to create a new article
2. in the `Tags` field, enter a value and press <kbd>Enter</kbd>

### Actual result

The placeholder text becomes cut off

![screenshot](https://user-images.githubusercontent.com/2019801/63160224-2e96ed00-c015-11e9-80dc-f5a4f3d7ff99.png)

**Comment by alikon** [comment]
part of me is unhappy to confirm, but i  can confirm ----
p.s.
never bring your laptop on the sand

**Comment by waader** [comment]
Also: the focus is lost after creating a tag

**Comment by Quy** [comment]
Please test PR #27093<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25895">issues.joomla.org/tracker/joomla-cms/25895</a>.</sub>
