### ISSUE TITLE
[4.0] [backend-template] Unused CSS

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25892]
As stated in the PR for the new template, it's importing a lot of unused CSS, such as:

```
@import "../../../../../media/vendor/bootstrap/scss/carousel";
@import "../../../../../media/vendor/bootstrap/scss/navbar";
@import "../../../../../media/vendor/bootstrap/scss/media";
```

The killer though is the Bootstrap utilities.

```
@import "../../../../../media/vendor/bootstrap/scss/utilities";
```

I would strong suggest creating a new `utilities.scss` and only define the ones used by the template.

**Comment by mbabker** [comment]
Disagree.  The backend template should make most of Bootstrap available to developers out-of-the-box to make integrations easier, the template shouldn't arbitrarily strip out parts of Bootstrap that the template designers did not decide to use in the core layouts (contrary to what some will say, the backend is more than 3 screens).

**Comment by C-Lodder** [comment]
> The backend template should make most of Bootstrap available

That's still possible by a sort of tree shaking approach

**Comment by HLeithner** [comment]
Loading everything in each request isn't very nice but as long as there is no way to only load whats needed by a page or extension it better to have everything ready for the extension dev.

If you can came up with a good solution that can easily handled by 3rd party it would be great.

**Comment by brianteeman** [comment]
I am going to close this in the absence of a suggested solution based on the comments of @HLeithner and @mbabker above
