### ISSUE TITLE
[4.0] [backend-template] Chevron not vertically aligned correctly

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25900]
### Steps to reproduce the issue

Screenshot below shows that the white chevron icons are not vertically aligned with the text correctly:

![screeny](https://user-images.githubusercontent.com/2019801/63162460-779d7000-c01a-11e9-914e-4303b75a884c.png)

**Comment by ghost** [comment]
Issue confirmed.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/27156.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25900">issues.joomla.org/tracker/joomla-cms/25900</a>.</sub>
