### ISSUE TITLE
[4.0] display created date instead of date published_up

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#25902]
### What needs to be fixed
display created date instead of date published_up in mod_latested and mod_popular

### Why this should be fixed
seem to be a copy & paste left over; in 3.9.x we use the created date

### How would you fix it
exchange line 
<?php echo HTMLHelper::_('date', $item->publish_up, Text::_('DATE_FORMAT_LC4')); ?> with
<?php echo HTMLHelper::_('date', $item->created, Text::_('DATE_FORMAT_LC5')); ?>

**Comment by chmst** [comment]
This is not template related. 
Have a look here - is is not a copy paste: https://issues.joomla.org/tracker/joomla-cms/24968<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25902">issues.joomla.org/tracker/joomla-cms/25902</a>.</sub>

**Comment by waader** [comment]
So after reading this I would prefer your solution to this problem.

**Comment by Quy** [comment]
@waader Please test PR #24968<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25902">issues.joomla.org/tracker/joomla-cms/25902</a>.</sub>
