### ISSUE TITLE
[4.0] [backend-template] big Joomla Logo before screen is loaded

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#25905]
### Steps to reproduce the issue
No matter what action I take (in this case I clicked on articles), before the final screen is loaded I see something like this for a frackion of a second:

![grafik](https://user-images.githubusercontent.com/9270310/63170188-0ae59e00-c039-11e9-810a-275dc990dbcd.png)

Tested with latest Firefox. This problem does not exist with latest chrome.

Edit: I found out that the avast add-on is responsible for that behaviour. On the other hand I don´t have the problem with joomla3.9, wordpress, typo3 etc.

**Comment by C-Lodder** [comment]
Can't replicate on FF68 on Windows 10

**Comment by ghost** [comment]
Can't confirm.
#### System Information

Setting | Value
-- | --
PHP Built On | Linux lamp129.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.5.el6h.x86_64 #1 SMP Thu Nov 22 10:07:47 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.23-cll-lve
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.7
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 4.0.0-alpha11-dev Development [ Amani ] 29-June-2019 11:27 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by dgrammatiko** [comment]
This is expected! For anyone that can follow the logic of any browser rendering any page...

Ps to eliminate this effect you need to split the css to inline (immediately executed) and then the normal css through a link...

**Comment by ghost** [comment]
Closed as expected behaviour.

**Comment by waader** [comment]
I installed J4 Alpha 10 and with this version I do not have this effect or rather I can not see it.
So there must be something with the new template that made this "very visible".
Hopefully there are not many browsers with the avast add-on or something like that in use.
