### ISSUE TITLE
[4.0] [backend] Creating of a category on the fly does not function

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#25903]
### Steps to reproduce the issue
In backend - article a newly entered category is displayed but not created.

**Comment by brianteeman** [comment]
Can not confirm.

**Comment by waader** [comment]
Digging a little bit deeper, in administrator/components/com_categories/Model/CategoryModel.php Line 602 I get the following error: "Field 'description' doesn't have a default value"

With this message I found an older issue: https://github.com/joomla/joomla-cms/issues/18993

I am using mariadb 10.1.36. According to https://mariadb.com/kb/en/library/sql-mode/#strict-mode strict mode is enabled per default only from 10.2.4 onwards.

Now I have to find out how to set strict mode for mariadb 10.1. These two commands did not work:
SET sql_mode = 'STRICT_TRANS_TABLES';
SET GLOBAL sql_mode = 'STRICT_TRANS_TABLES';

**Comment by ghost** [comment]
Can't confirm Issue. Created Category "new" in Article-View is assigned to Article and shown in Categories.
#### System Information

Setting | Value
-- | --
PHP Built On | Linux lamp129.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.5.el6h.x86_64 #1 SMP Thu Nov 22 10:07:47 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.23-cll-lve
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.7
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 4.0.0-alpha11-dev Development [ Amani ] 29-June-2019 11:27 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by waader** [comment]
I think you didn´t read my last message in which I analyzed the origin of the problem.

**Comment by ghost** [comment]
@waader i read your last Message but i couldn't get your Issue described in opening Comment.

**Comment by waader** [comment]
In mariadb strict-mode is set by default from version 10.2.4 onwards (https://mariadb.com/kb/en/library/sql-mode/#strict-mode). 
So I tested with a more current version (10.4.8) and now the adhoc creation of a category works.

@Richard67: Maybe it should be documented that older mariadb versions could cause problems with J4.

**Comment by richard67** [comment]
> In mariadb strict-mode is set by default from version 10.2.4 onwards (https://mariadb.com/kb/en/library/sql-mode/#strict-mode).
> So I tested with a more current version (10.4.8) and now the adhoc creation of a category works.
> 
> @richard67: Maybe it should be documented that older mariadb versions could cause problems with J4.

@wilsonge Maybe we should check and if necessary increase minimum version requirement for MariaDB in the DB driver?

**Comment by brianteeman** [comment]
If I read this correctly the issue is that we require strict_mode and with 5 year old (but still supported) versions of mariadb it is not enabled by default. If that is correct then either
1. We document that strict mode is required in the system requirements
2. If possible check for strict mode in the installer

**Comment by brianteeman** [comment]
@richard67 @wilsonge is this still an issue to resolve?

**Comment by richard67** [comment]
I don't know.

**Comment by brianteeman** [comment]
I am referring to the comments about mariadb

https://github.com/joomla/joomla-cms/issues/25903#issuecomment-545603979
https://github.com/joomla/joomla-cms/issues/25903#issuecomment-545609876

**Comment by richard67** [comment]
@brianteeman I wish I could help here, but to be honest, I did not really understand these comments. From my experience I would expect problems to appear when strict mode is on and not when it's off, and the error message fits to that, but here it seems to be vice versa, i.e. problems coming with the older version where strict mode was not enabled by default, and that confuses me.

So either I understand this issue completely wrong, or I am at least missing something.

**Comment by brianteeman** [comment]
@richard67 that is my reading of the op issue as well.

**Comment by joomdonation** [comment]
Joomla 4 was released more than one year ago and we didn't receive any other report, so I assume this was solved elsewhere. Therefore, I'm closing this issue. Feel free to re-open if the issue still valid.
