### ISSUE TITLE
[4.0] Keep Fontawesome v4.7 as well as using latest v5.x

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#25915]
### Is your feature request related to a problem? Please describe.
I was looking to see if I could change a Fontawesome icon using the icons supplied in the J4.0 dev core and then discovered that the icon not available in Fontawesome 5.0 free version. I came across PR #24648, and posted the following there,  but the PR was merged back in April, so I am opening a new issue:

The version of Fontawesome-free being used for J4.0 - version 5.0 - contains solid icons only. Any 'white' icons are now classed as 'light' and are only available in the Pro version. 

In Joomla 3x, in the template editor directory tree, for example, the file icon is light and easily distinguishable at a glance from the folder icon: 

![J3-white-icons](https://user-images.githubusercontent.com/36987494/63211691-a129ca80-c0f2-11e9-8010-7dbebe9dbccb.jpg)

In Joomla 4.0 dev, using Fontawesome version 5.0 free, they are all solid:

![j4-solid-icons](https://user-images.githubusercontent.com/36987494/63211700-c0285c80-c0f2-11e9-92c2-2c546aba878c.jpg)

You can see the difference on Fontawesome's pages for this icon here:

v4.7 free:
![fontawesome-4 7-file-o](https://user-images.githubusercontent.com/36987494/63211702-d7674a00-c0f2-11e9-8eff-34846e46ec06.jpg)

v5.0 free:
![fontawesome-5 0-free-file](https://user-images.githubusercontent.com/36987494/63211708-ebab4700-c0f2-11e9-9562-b60ceab93312.jpg)

v5.0 **Pro**:
![fontawesome-5 0-pro-file](https://user-images.githubusercontent.com/36987494/63211711-0087da80-c0f3-11e9-99ad-e0582aeb6939.jpg)

### Describe the solution you'd like
As well as using the latest version of Fontawesome in J4x core, keep Fontawesome 4.7 free in order to maintain access to light icons.

**Comment by brianteeman** [comment]
No need to keep 4.7 
Just need to add fa-regular as well as fa-solid

https://fontawesome.com/icons/file?style=regular

**Comment by Scrabble96** [comment]
Thanks, @brianteeman 
Will you do that?

I think that will also solve someone else's comment (can't find it now, though) that Fontawesome was all bold.

**Comment by Scrabble96** [comment]
I have just discovered that not all icons available as fa-solid are available as fa-regular. Look at the code icon, for instance:

`https://fontawesome.com/icons/code?style=regular`

**Comment by Quy** [comment]
Please test PR #26631. Please close if you are ok with it.

PS: It does not make sense to maintain 2 versions.

**Comment by infograf768** [comment]
There is now a 5.11.2 version of fontawesome and using the regular would fit.
We just need to update as the version we use is quite old (5.9.0)

**Comment by Quy** [comment]
See issue #27019 for request to upgrade to the latest version.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25915">issues.joomla.org/tracker/joomla-cms/25915</a>.</sub>
