### ISSUE TITLE
[4.0] [RFC] password strength

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25914]
The current defaults for password length is 4 characters - thats crazy and should be changed to 12 characters.

There should be text on screen that states the minimum length AND a recommendation to use a password manager

The password strength script is anything but a password strength check. It is just counting the complexity not the entropy and basically in its current state will give the green light to a 4 character password. 

There is no password strength check when creating the first super user at installation - 1234 is good enough :(

There are similarly lightweight scripts that can replace this useless on that actually measure the entropy https://github.com/autonomoussoftware/fast-password-entropy

Currently although we set a maxlength in the password input we dont set a minlength - instead we use a custom data-min-length which is just for the javascript and doesn't aid password managers etcc

The changes are relatively easy to make and I am happy to volunteer to do it if its seen to be a good idea

Thoughts?
@wilsonge @SniperSister

**Comment by alikon** [comment]
sometimes ago i've tryied to make something in this direction unfortunately without luck #18766
after wishing you more good luck, i can only approve this ...

**Comment by zero-24** [comment]
Sounds like a good idea to me 👍

**Comment by ReLater** [comment]
Just as additional info: https://github.com/joomla/joomla-cms/issues/23511

**Comment by brianteeman** [comment]
Thanks all - I guess I have a task to do on my holidays

**Comment by jeckodevelopment** [comment]
I agree, if not 12, we could go with at least 8 characters.
And it would be good to have a check to avoid having same username and password, as suggested in 18766

**Comment by brianteeman** [comment]
> And it would be good to have a check to avoid having same username and password,

As shown that is not as easy as it would seem

**Comment by jeckodevelopment** [comment]
> As shown that is not as easy as it would seem

Yes, i know, but still it would be a good improvement

**Comment by brianteeman** [comment]
@roland-d Don't suppose any of your students are interested in taking this on? I'm stuck on client work.

**Comment by roland-d** [comment]
@brianteeman I am afraid we are out of time.
