### ISSUE TITLE
[4.0] How many shades of blue ???

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25912]
administrator/index.php?option=com_users&view=users

There is no consistency in the colour blue and when it is used. Especially with :hover and :active 

![image](https://user-images.githubusercontent.com/1296369/63202145-48b9e500-c080-11e9-9c80-724ee9eb7cb0.png)

![blue](https://user-images.githubusercontent.com/1296369/63202313-05ac4180-c081-11e9-8a68-d5ffa0256842.gif)

- rgb(95, 126, 146)
- rgb(50, 97, 134)
- rgb(26, 70, 107)
- rgb(20, 50, 82)
- rgb(23, 87, 161)
- rgb(14, 34, 60)
- rgb(0, 27, 76)

**Comment by richard67** [comment]
The answer to the question in the title is ... 42. :smile:
