### ISSUE TITLE
[4.0] alert colours

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25911]
The colours for warning / error are wrong - I am not talking about the exact colour being wrong as I wouldnt have a clue which exact colour is best. I am talking about the expected behaviour associated with an alert colour.

### warning
![image](https://user-images.githubusercontent.com/1296369/63193109-8ad52d80-c064-11e9-903a-c6a84b70d575.png)

### error
![image](https://user-images.githubusercontent.com/1296369/63193083-798c2100-c064-11e9-84bb-d0566c454b95.png)

If I was to just use the bootstrap colour scheme then this would look like 
![image](https://user-images.githubusercontent.com/1296369/63193310-0931cf80-c065-11e9-9302-437d8e2bcec1.png)

I am all for _customising_ the colour but the current template goes way too far

**Comment by B3nito** [comment]
Is Bootstrap enough contrast color for accessible? have you checked?

**Comment by brianteeman** [comment]
yes and yes

**Comment by GCLW** [comment]
I think that Brian is pointing out that red should be an error, while yellow is a warning.
The colors bootstrap uses are pretty much universally recognized colors. 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25911">issues.joomla.org/tracker/joomla-cms/25911</a>.</sub>

**Comment by brianteeman** [comment]
Exactly

**Comment by brianteeman** [comment]
closed see #26124
