### ISSUE TITLE
[4.0] Include template style-files switch from dashboard quick icon

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#25916]
### Is your feature request related to a problem? Please describe.
From the backend control panel, after selecting System you see a module with four options:

![system-templates](https://user-images.githubusercontent.com/36987494/63212123-c5d47100-c0f7-11e9-97d9-715292da769b.jpg)

From the quick icon on the dashboard, there is only one, "Templates: Styles (site)" although you can switch from there to Admin styles.

When I first saw the dashboard icon, with its paintbrush icon, I assumed that there would (also) be a quick link to "Templates: Templates (Site)". There isn't. A paintbrush icon, to me, implies styling, css, etc.

### Describe the solution you'd like
What I'd like to see is the option to switch from there to Template files as there is in Joomla 3x:

![styles-files-switch](https://user-images.githubusercontent.com/36987494/63212101-958cd280-c0f7-11e9-8cd3-b824d411aa4f.jpg)

**Comment by brianteeman** [comment]
> From the quick icon on the dashboard, there is only one, "Templates: Styles (site)" although you can switch from there to Admin styles.

I dont understand what you are saying.

**Comment by Scrabble96** [comment]
> 
> I dont understand what you are saying.

To put it another way, perhaps the quick-icon should say "Template Styles" rather than just "Templates". When I first clicked on it I was expecting to reach Templates (files) that I could edit.

I personally spend far more time customising templates (css and layout) than I do switching between different templates. Could there be another quick-icon option (which could be 'Hide' by default) with the title "Templates Files" that links to this page: [/administrator/index.php?option=com_templates&view=templates&client_id=0](url)?

Thank you.

**Comment by brianteeman** [comment]
Sorry you mean you were referring to the link behind 
![image](https://user-images.githubusercontent.com/1296369/63222566-a1cd6a00-c1a1-11e9-9d7d-238c23cf80e7.png)

**Comment by Scrabble96** [comment]
> 
> 
> Sorry you mean you were referring to the link behind
> ![image](https://user-images.githubusercontent.com/1296369/63222566-a1cd6a00-c1a1-11e9-9d7d-238c23cf80e7.png)

Yes. You can switch to the Admin template style, but there's no link to template files (and seeing the paintbrush icon caused me to believe - at first - that it meant styling, not just choosing a template and/or template style). In J3 if you are in template styles, it's easy to switch to templates in order to edit files.

So, what I'd suggest is: 

![dashboard](https://user-images.githubusercontent.com/36987494/63224930-27154680-c1c3-11e9-93e7-2a49f25d3e54.jpg)

The template files option could be switched on or off as required.

**Comment by Scrabble96** [comment]
Actually, having looked closer at the control panel, it would make more sense to have 'Template Files' as an option on the 'System' dashboard, not the 'Site' dashboard. If you edit the System dashboard there is an option to show Templates, but it is again just Styles and not Files. 
![system-dashboard](https://user-images.githubusercontent.com/36987494/64075892-dff47e80-ccb5-11e9-8710-7ec282df79cb.jpg)

**Comment by coolcat-creations** [comment]
https://github.com/joomla/joomla-cms/pull/28977 Please test @Scrabble96

**Comment by coolcat-creations** [comment]
@Quy can this issue be closed since we have a PR?
