### ISSUE TITLE
Users last visit date partially does not save

### ISSUE THREAD

**Issue by alve89** [joomla/joomla-cms#25927]
### Steps to reproduce the issue
Can't reproduce

### Expected result
Users last visit date is saved in database

### Actual result
Some users last visit date is not saved

### System information (as much as possible)
J3.9.11
PHP 7.3
MySQL 5.6.44

### Additional comments
It only doesn't work with some users, the most are working properly.

**Comment by zero-24** [comment]
Do we have any details / differences between the users that work and that don't work? Do you have any log indicating any (database) errors? Do you use only the joomla core auth plugins or is some extension involved too? Why do you know that the last visit time is incorrect?

**Comment by alve89** [comment]
Actually I need to close this, because the affected users don't have this problem anymore. Maybe it was a problem caused by cache or whatever. Everything's fine and everything's working properly!

Thanks for this very quick response, you're doing a great job!
