### ISSUE TITLE
Missing language key

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#25930]
The key ```JLIB_LOGIN_DENIED``` is missing in the language files.

Reported here: https://github.com/joomla/joomla-cms/issues/10798 (there is a list of paths)

First attempt: https://github.com/joomla/joomla-cms/pull/10804
Merged PR: https://github.com/joomla/joomla-cms/pull/11611

But it seems some of the listed keys are still missing.

**Comment by infograf768** [comment]
In fact 3 strings at least there but I never could experience these errors. Any idea how to trigger them?

JLIB_LOGIN_EXPIRED at: JROOT\libraries\cms\application\cms.php:840
JLIB_LOGIN_DENIED at: JROOT\libraries\cms\application\cms.php:845
JLIB_LOGIN_AUTHORISATION at: JROOT\libraries\cms\application\cms.php:850

Also used in CMSApplication

**Comment by bembelimen** [comment]
you can only trigger them with a manual plugin which denies access after a successful login (e.g. I implemented a "failed login counter" which closed up an account after to much tries, regardless if the login afterwards work)

**Comment by infograf768** [comment]
Link to that plugin?

**Comment by brianteeman** [comment]
I will submit a Pr today

**Comment by alikon** [comment]
test #25954<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25930">issues.joomla.org/tracker/joomla-cms/25930</a>.</sub>
