### ISSUE TITLE
[4.0] Admin Adjustment - Suggestion

### ISSUE THREAD

**Issue by icc365** [joomla/joomla-cms#25937]
### What needs to be fixed
The left column menus suggestion.
Admin template for Joomla 4 alpha 11 menu links - move dashboard link to drop down and remove the icon next to the arrow.

### Why this should be fixed
Would make the left column menu navigation cleaner and less distracting with the icon for the dashboard page.

### How would you fix it
Remove the icon for the item's dashboard and move that as a link into the dropdown. 

### Side Effects expected
None

I tweeted about this: [HERE](https://twitter.com/andrejutras/status/1163651321196531712)

**UPDATE**: I added the screenshot examples here:

![joomla-admin-menu](https://user-images.githubusercontent.com/54302511/63321789-9af44380-c2d6-11e9-8a2c-14147cab4d1e.jpg)

**Comment by ghost** [comment]
Whats your opinion on #25865?

**Comment by icc365** [comment]
> Whats your opinion on #25865?

Not sure if you wanted me to reply here or on that ticket, but I took a look...interesting idea, but as Brian mentioned, there will be people who won't know what the standalone + symbol is for. Good idea for the side placement of just the icon, but I think it's better where it is on the bottom.  I would also go as far as adding the word "Add" to the add link boxes. Example:  Add Article, Add Category (not Add Article Category), etc. I can show a screenshot if you wish?
![joomla-add-item](https://user-images.githubusercontent.com/54302511/63321731-7009ef80-c2d6-11e9-8a65-d938a4f119a9.jpg)

**Comment by ghost** [comment]
Better to discuss one issue in one thread, so if you please comment your thoughts and show screenshots at #25865 and close this issue.

**Comment by brianteeman** [comment]
Not a fan of the dashboard icon change myself as it negates the reason for having it and I prefer the side approach in #25865 for the icons

My 2c

**Comment by icc365** [comment]
Shouldn't have closed this whole thread because there is still the item I brought up about the left column menus suggestion. That is not related to the other thread.

**Comment by ghost** [comment]
reopened. Can you please change the opening comment to " the left column menus suggestion" so we have one issue in one thread?

**Comment by icc365** [comment]
> reopened. Can you please change the opening comment to " the left column menus suggestion" so we have one issue in one thread?

I changed this thread to just be about the left column menus suggestion.

**Comment by micker** [comment]
for me its important to keep dashboard icon because first level link open submenu
for accessibility we need to have 2 buttons 1 for submenu and 1 for subdasboard

**Comment by brianteeman** [comment]
Based on the comments above I believe this should be closed
