### ISSUE TITLE
[4.0] Database table is not created while installation of a component

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#25943]
### Steps to reproduce the issue

1. Install a component. 
I used this one: https://github.com/astridx/boilerplate/releases/download/v0.0.1/com_foos.zip

### Expected result

The component is installed and the database table is created.

### Actual result

The component is installed, but the database table is not created. 
I solved the problem with the button 'fix database'. So the sql should be correct.

### System information (as much as possible)
Current 4.0-dev branch with firefox on ubuntu.

**Comment by brianteeman** [comment]
can you please also try to install the patchtester component https://github.com/joomla-extensions/patchtester/releases/download/3.0.0-beta4/com_patchtester.zip

**Comment by astridx** [comment]
@brianteeman Thank you. In the case of patch tester this is OK. Then the mistake is probably with me. I only wonder that fix database solves the problem.
