### ISSUE TITLE
The property 'input' of JFormFieldText cannot be set

### ISSUE THREAD

**Issue by chinphing5** [joomla/joomla-cms#25945]
### Steps to reproduce the issue
I tried to override value of 'input' in view code like this.
`$field->input = '<my input code>';`

but the result in html was not changed. (same as before overridden)

### Expected result
The input code is changed to new value.

### Actual result
The code is not changed. And this line is shown in log file.

`2019-08-16T12:36:56+00:00`	INFO ::1	-	Cannot access protected / private property input of `Joomla\CMS\Form\FormField`

### System information (as much as possible)
Joomla 3.9.8

**Comment by ghost** [comment]
can you please update on latest version?

**Comment by chinphing5** [comment]
Thankyou @franz-wohlkoenig. I will update Joomla to the latest version.

Another update, I try to look inside the method '__set' of FormField class (parent class of JFormFieldText). The 'input' property does not appear in switch case. So it means that the input property should not be set directly?

**Comment by ghost** [comment]
i'm no dev, but sure a dev. will answer :-)

**Comment by HLeithner** [comment]
It's not intended to set the input directly because most of the formfields building the input on the fly using the getInput method and render a layout.

**Comment by chinphing5** [comment]
Thankyou @HLeithner, I override the attribute of input html element via the other property of JFormFieldText such as `$field->class` and call renderField method. It works. The input html element is changed as my expectation.
