### ISSUE TITLE
No character restrictions in user registration

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#25942]
### Steps to reproduce the issue

Try to reginstate user you Can create Name with @ and .com

### Expected result

Users cant registrate with @ and .com as their legal name

### Actual result

Users can registrate with @ and .com as their legal name

### System information (as much as possible)

j 3.9.11

**Comment by HLeithner** [comment]
Joomla doesn't ask for a legal name, in the registration process it asks for a name, that could be anything incl. a company name for example.

Restricting this field makes not much sense imo

**Comment by brianteeman** [comment]
Note my company name has both @ and .com

**Comment by alikon** [comment]
expected behaviuor<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25942">issues.joomla.org/tracker/joomla-cms/25942</a>.</sub>

**Comment by ghost** [comment]
please reopen as in #25479 

@brianteeman said that:

> name is their real legal name (obviously not unique)

username can be anything that they want (must be unique)
As this is an agreement it must include the real legal 

> name

I doubt that in every country you can have legal name as @ and .com

**Comment by mbabker** [comment]
Copy/pasting something out of context isn't going to get you anywhere.

Joomla does not impose character restrictions on the name field for a user's name.  Nor should it.  There are more than likely plugins out there that can add this type of filtering if you require it on your website.

**Comment by ghost** [comment]
Writing about issues you dont understand and Copy/pasting general replys to specific issue out of context isn't going to get joomla anywhere.

Now its clear that buggy joomla is so messed up that even devs joomla babker and bteeman dont understand what is required

@HLeithner in  #25479 are you so sure Joomla doesn't ask for a legal name? If so brianteeman closed  issue on false and wrong assumptions, if he is wrigt this issue is closed on wrong accumptions.

**Comment by HLeithner** [comment]
@Milglius Joomla ask in the registration form for COM_USERS_REGISTER_NAME_LABEL which is "Name".
So yes, I'm sure it doesn't ask for a legal name. Also if the symbols are not used in some countries doesn't mean it's not used anywhere else.

Anyway as Michael wrote, Joomla has a powerful plugin system that can extend the registration form and you can manipulate the registration process to fit your needs.
