### ISSUE TITLE
[4.0] [backend-template] Language strings missing

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25955]
### Steps to reproduce the issue

1. Open the `Admin Menu` in the Module Manager
2. Set the `preset` to `Modern`
3. Expand the `Extensions` menu item in the sidebar

### Actual result

![screeny4](https://user-images.githubusercontent.com/2019801/63424334-1accfb80-c406-11e9-8ff1-979eff16ab87.png)

**Comment by infograf768** [comment]
LOL how great spirits meet
Please test https://github.com/joomla/joomla-cms/pull/25956
Closing
