### ISSUE TITLE
Any plausible reason for show_author condition in article default.php

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#25958]
Current Joomla 3.

Is there any plausible reason why there is an `if` condition for `show_author` around this code block that outputs the h2 headline?

https://github.com/joomla/joomla-cms/blob/3.9.11/components/com_content/views/article/tmpl/default.php#L50-L67

**Comment by SharkyKZ** [comment]
No, it's a leftover from https://github.com/joomla/joomla-cms/commit/c36efc67d511383f153cb494200481b7e80f9e26#diff-7e2e52f4d2bbd0ec2a484d89a9e79817. Can be removed.

**Comment by ReLater** [comment]
Thanks

In Joomla 3 and Joomla 4?

@HLeithner : Something critical concerning B\C

**Comment by HLeithner** [comment]
no concerns please write a pr if you have time for it.

**Comment by ghost** [comment]
Closed as having Pull Request #25964
