### ISSUE TITLE
[4.0] [backend-template] Language strings are coupled to template

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25950]
### Steps to reproduce the issue

If one was to create a new backend template, they'd run into some of the language strings deriving from modules being coupled to the Atum template.

Examples are here:

https://github.com/joomla/joomla-cms/blob/4.0-dev/layouts/joomla/sidebars/submenu.php#L21

and here:

https://github.com/joomla/joomla-cms/blob/4.0-dev/layouts/joomla/sidebars/submenu.php#L23

### Expected result

The language strings in core layouts should not be coupled to the template
Both the language strings should be prefixed and reside in the language file of the module they derive from.

### Additional comments

Of course these layouts can be overriden, as can any layout, but layouts have to be maintained and kept up to date.

**Comment by Quy** [comment]
Please test PR #27082<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25950">issues.joomla.org/tracker/joomla-cms/25950</a>.</sub>
