### ISSUE TITLE
[4.0] Missing string in "Add module to the Dashboard"

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-cms#25959]
### Steps to reproduce the issue
1) Login into Joomla 4.x Alpha 12dev administration
2) Click on Add Module to the Dashboard in any admin dashboard

### Expected result
The description string of the Frontend Link is visible.

### Actual result
The description string of the Frontend Link is not visible.

![immagine](https://user-images.githubusercontent.com/733133/63436496-1403b000-c429-11e9-805e-5e945258dbcd.png)

### System information (as much as possible)
Database Type | mysql
Database Version | 5.7.24-cll-lve
Joomla! Version | Joomla! 4.0.0-alpha12-dev Development [ Amani ] 19-August-2019 13:40 GMT

**Comment by Quy** [comment]
Please test PR #26049<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25959">issues.joomla.org/tracker/joomla-cms/25959</a>.</sub>
