### ISSUE TITLE
[4.0] [backend-template] System page - navigating via keyboard

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25951]
### Steps to reproduce the issue

Go to `administrator/index.php?option=com_cpanel&view=cpanel&dashboard=system`

### Expected result

When tabbing on your keyboard, you expect all action elements to come into focus at some point.

### Actual result

The buttons with a cog icon (screenshot below) never come into focus and this can't be access via keyboard

![Screenshot_2019-08-21 System Dashboard - J4 - Administration](https://user-images.githubusercontent.com/2019801/63415603-e6514380-c3f5-11e9-9bf0-c2beedb08036.png)

**Comment by brianteeman** [comment]
I thought I did a PR to fix this - checking

**Comment by brianteeman** [comment]
They do come in to focus - the problem is the stupid outline:none etc which I have another open issue for and waiting a reply from @wilsonge 

![image](https://user-images.githubusercontent.com/1296369/63417004-6d9fb680-c3f8-11e9-978e-e948001885c6.png)

**Comment by C-Lodder** [comment]
Thanks Brian.

Closing for: https://github.com/joomla/joomla-cms/issues/25877
