### ISSUE TITLE
[4.0] Avoid confusion in Database screen

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-cms#25960]
### Steps to reproduce the issue
On a Joomla 4.0 alpha installation, go to:
1) System
2) Database

### Expected result
A message in which the system says that the database is ok and there are no issues. 

### Actual result
`No matching results`

![immagine](https://user-images.githubusercontent.com/733133/63437141-4feb4500-c42a-11e9-8a95-c946b2034481.png)

### System information (as much as possible)
Joomla! 4.0.0-alpha12-dev Development [ Amani ] 19-August-2019 13:40 GMT

**Comment by brianteeman** [comment]
Something wrong there as it should look like this
![image](https://user-images.githubusercontent.com/1296369/63438355-0e579b80-c424-11e9-80d5-d8690d97b5f4.png)

**Comment by jeckodevelopment** [comment]
I'm using the latest nightly build, so it could be something new.
But i see your installation is reporting "1 problem".
If you don't have problems, or if you solve them, how do you see it?

**Comment by brianteeman** [comment]
Just the same display but with a different message in the problems cell

**Comment by brianteeman** [comment]
@jeckodevelopment can you still replicate this issue?

**Comment by Quy** [comment]
Closing as non-reproducible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25960">issues.joomla.org/tracker/joomla-cms/25960</a>.</sub>
