### ISSUE TITLE
[4.0] No notification of completed sample data installation

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-cms#25963]
### Steps to reproduce the issue
Click on install near to "Blog Sample Data"

### Expected result
Loading bar disappears at the end of the installation or stops "flashing"/loading.

### Actual result
The loading bar continues to appear as it is still loading.

![immagine](https://user-images.githubusercontent.com/733133/63439039-a017d680-c42d-11e9-9d64-d3ee8bf1577d.png)

### System information (as much as possible)
Joomla! 4.0.0-alpha12-dev Development [ Amani ] 19-August-2019 13:40 GMT

**Comment by ghost** [comment]
closed as duplicate report of #24459

**Comment by jeckodevelopment** [comment]
Thanks Franz! I didn't spot the old issue
