### ISSUE TITLE
[4.0] [RFC] Smart Search - Index button

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-cms#25969]
### Steps to reproduce the issue
This is more a doubt on a string than a real issue. 
That's why I'd request the opinion of an English native speaker like @brianteeman or @Joomv 

When you go on Component > Smart Search the first time, it asks you to create the index and it's right.
The button in the toolbar is "Index": 
![immagine](https://user-images.githubusercontent.com/733133/63507956-3b19ba80-c4d9-11e9-90c6-c63cd0a73fd6.png)

I know that "Index" is a verb, but it could be read also as a noun for the index itself.
Do you think that it could be better to change the button text into something like "Start Index" or "Build the index" or anything else that could help understanding that it's the right button to start the indexing process.

**Comment by brianteeman** [comment]
It is fine as it is

**Comment by Quy** [comment]
Fine as it. `Index` is an action button so it performs indexing (verb). `Indexed Content` goes to the index itself (noun).
