### ISSUE TITLE
[4.0] Placement of controls in Resize Image / Media Manager

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-cms#25961]
### Steps to reproduce the issue
In Joomla 4.0 Alpha
1) Go to Content > Media
2) Upload a picture
3) Edit a picture
4) Resize

### Expected result
The controls to resize the picture are coupled or placed near to fields where to specify the size of the final picture.

### Actual result
Selectors are placed on a new row and don't have a label to understand if you are editing picture width or height.
![immagine](https://user-images.githubusercontent.com/733133/63437668-3b5b7c80-c42b-11e9-96eb-c8c5405b6cee.png)

### System information (as much as possible)
Joomla! 4.0.0-alpha12-dev Development [ Amani ] 19-August-2019 13:40 GMT

**Comment by brianteeman** [comment]
This is a duplicate report

**Comment by jeckodevelopment** [comment]
Right, found that: https://github.com/joomla/joomla-cms/issues/25891#issuecomment-523416661
