### ISSUE TITLE
[4.0] [backend-template] Invalid HTML markup

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#25966]
### Steps to reproduce the issue

Go to the admin dashboard

The quickicons markup is invalid. You **cannot** have a `<ul>` as a direct child of `<ul>`

![screeny4](https://user-images.githubusercontent.com/2019801/63453218-0dccfe00-c440-11e9-9867-fc90e33677cf.png)

**Comment by brianteeman** [comment]
The ul should be wrapped in a li
@chmst can you try that please - it may need some tweeks to your css as a result

**Comment by chmst** [comment]
@C-Lodder thank you. 
@brianteeman can you test please? The Screenreader seems to announce it correct.

**Comment by Quy** [comment]
Please test PR # 26167 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25966">issues.joomla.org/tracker/joomla-cms/25966</a>.</sub>

**Comment by jeckodevelopment** [comment]
#26167
