### ISSUE TITLE
[4.0] Argument 2 passed to JAdapterInstance::__construct() must be an instance

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#25975]
### Steps to reproduce the issue

On the backend, the update joomla/extensions plugins are now red, and when go to the component you see the error.

### Actual result

Argument 2 passed to JAdapterInstance::__construct() must be an instance of JDatabaseDriver, instance of Joomla\Database\Mysqli\MysqliDriver given, called in C:\wamp\www\libraries\joomla\base\adapter.php on line 152

**Comment by HLeithner** [comment]
can you activate debugging and post the backtrace please?

**Comment by 810** [comment]
````
An error has occurred.
0 Argument 2 passed to JAdapterInstance::__construct() must be an instance of JDatabaseDriver, instance of Joomla\Database\Mysqli\MysqliDriver given, called in C:\wamp\www\j4new\libraries\joomla\base\adapter.php on line 153

Call stack
--
# | Function | Location
1 | () | JROOT\libraries\joomla\base\adapterinstance.php:47
2 | JAdapterInstance->__construct() | JROOT\libraries\joomla\base\adapter.php:153
3 | JAdapter->setAdapter() | JROOT\libraries\src\Updater\Updater.php:237
4 | Joomla\CMS\Updater\Updater->getUpdateObjectsForSite() | JROOT\libraries\src\Updater\Updater.php:156
5 | Joomla\CMS\Updater\Updater->findUpdates() | JROOT\administrator\components\com_installer\Model\UpdateModel.php:271
6 | Joomla\Component\Installer\Administrator\Model\UpdateModel->findUpdates() | JROOT\administrator\components\com_installer\Controller\UpdateController.php:111
7 | Joomla\Component\Installer\Administrator\Controller\UpdateController->find() | JROOT\libraries\src\MVC\Controller\BaseController.php:728
8 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\libraries\src\Dispatcher\ComponentDispatcher.php:146
9 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT\libraries\src\Component\ComponentHelper.php:383
10 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:117
11 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:160
12 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:241
13 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\includes\app.php:63
14 | require_once() | JROOT\administrator\index.php:36


````

**Comment by HLeithner** [comment]
I can't confirm this. Is this a new installation with git or alpha?

If git did you removed the autoloader? And die composer install?

**Comment by 810** [comment]
git. 

yes, i removed both 2 autoloaders.

Composer install, and composer update.

**Comment by HLeithner** [comment]
fresh install? And the problem occurs on administrator/index.php?option=com_installer&view=update ?

**Comment by richard67** [comment]
@810 which two autoloaders did you remove? I know only about one to be removed, don‘t remember name right now. And why composer update? We shall do only composer install and then npm install.

**Comment by 810** [comment]
Ok, i removed everything on the dir, now its working.  Looks there was a file that doesn't be there.

I do composer update, because im working on database changes, so i wanted to sure that i have the latest database framework release.

**Comment by richard67** [comment]
@810 Regarding composer update: If you want to pull in only the changes in the database package you can use `composer update joomla/database`. I guess you know that already, but just in case if not I thought I post this info here.
