### ISSUE TITLE
Support HTML5 Input Patterns  while creating text field

### ISSUE THREAD

**Issue by vijaykhollam** [joomla/joomla-cms#25973]
### Steps to reproduce the issue
1. Go to Admin => Content => Fields => Create new field of type text
2. There is no config for pattern attribute in HTML5

![Current config for custom field - Administration](https://user-images.githubusercontent.com/8510258/63509828-be97d380-c4fa-11e9-93e7-805902831ac0.png)

### Expected result
We should able to create a custom field with the pattern attribute

![Expected custom field Administration](https://user-images.githubusercontent.com/8510258/63509724-737dc080-c4fa-11e9-9ead-31bf9aaf5b45.png)

### System information (as much as possible)
Joomla 3.9.11
PHP 7.2

### Why
This will improve the usability of the form.
https://www.w3schools.com/tags/att_input_pattern.asp

**Comment by vijaykhollam** [comment]
Have sent a pull request for same

https://github.com/joomla/joomla-cms/pull/25974

**Comment by ghost** [comment]
Thanks for Report and Pull Request @vijaykhollam. If you do a PR there is no need doing a Report too.

**Comment by ghost** [comment]
Closed as having Pull Request #25974
