### ISSUE TITLE
Interest in meta maintenance

### ISSUE THREAD

**Issue by raux** [joomla/joomla-cms#25980]
Hi,

I am a software engineering researcher from NAIST, Japan. Currently we found that your project has a file similar to another project.

https://github.com/joomla/joomla-cms/commits/a81ada410a5bf6b700a79d432fc5926146ac9f94/media/jui/js/jquery.js

in simpl4-src

https://github.com/tpso-src/simpl4-src/commits/master/surface/js/libs/jquery-2.1.1.js

If you have time please fill out our 5 min survey. If not, just provide us an indication or you are interested in these changes and if we were to provide such similarities automatically, what would be your opinion.

Survey: https://forms.gle/PGT5xQMSVM9hfDj3A

Many thanks for your time

Raula

**Comment by HLeithner** [comment]
thanks for bringing this to Joomla!, I filed the survey and would be interested of the outcome.
