### ISSUE TITLE
[4.0] Language update checks

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#25987]
If your site is offline or behind a firewall then you always get the warning "The update table is not up to date. Please rebuild your update server table"
You can click rebuild and the list will be displayed but you need to do that everytime.

I would expect a message indicating that it cant connect to check or something like that

cc @zero-24

**Comment by zero-24** [comment]
Please see: https://github.com/joomla/joomla-cms/pull/25996
