### ISSUE TITLE
[4.0] Unpublish submenu on dashboard: js error

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#25999]
### Steps to reproduce the issue
Unpunblish a Submenu Module on a dashboard. 

### Expected result
The Submenu module is unpublished

### Actual result
Nothing happens, Console shows a js error.

**Comment by SharkyKZ** [comment]
Please post the error.

**Comment by richard67** [comment]
Duplicate of issue #25993 ?

**Comment by chmst** [comment]
Seems to be the same error for unpublishing submenu modules. 
The error is: .module-wrapper not found für a submenu module.

**Comment by ghost** [comment]
closed as duplicate report #25993
