### ISSUE TITLE
[4.0] Media manager doesn't support UTF-8 characters

### ISSUE THREAD

**Issue by newjie** [joomla/joomla-cms#25997]
### Steps to reproduce the issue
create a folder under /images/ with UTF-8 characters

### Expected result
In media manager, this folder's name should appear and once clicked, its content should be shown

### Actual result
In media manger, the folder just shows a folder icon with blank name, and there is no response when being clicked

### System information (as much as possible)
Any Joomla version  and any host

### Additional comments
In 2010 there was a post in Joomla's forum complaining about this. It is now 2019 and this problem is still there.

**Comment by Quy** [comment]
Related PR #16878 ?

**Comment by ghost** [comment]
Closed as having Pull Request #16878
