### ISSUE TITLE
table banner_tracks tracks every few minutes since 3.9.6

### ISSUE THREAD

**Issue by Pinkeltje** [joomla/joomla-cms#25994]
### Steps to reproduce the issue
Create site with banners. Activate impressions. Navigate a few times.

### Expected result
No errors

### Actual result
Duplicate entry '2019-07-22 10:20:13-1-54' for key 'PRIMARY'
Different time - track type - banner_id every time off course

### System information (as much as possible)
Joomla 3.9.11 (suppose all versions after 3.9.5)
MySQL 2.7.24
PHP 7.2.21

### Additional comments
See table banner_tracks. Joomla 3.9.6 was released on may 7th. From this date track_date interval changed. So when multiple visitors are viewing/browsing the site, duplicate entry occurs. 
![Yndi 20190823-027](https://user-images.githubusercontent.com/8941310/63595950-73dd9080-c5ba-11e9-85d8-9a7892402e94.png)

**Comment by SharkyKZ** [comment]
Test PR #24651 please.

**Comment by ghost** [comment]
@Pinkeltje please test (how to: https://docs.joomla.org/Testing_Joomla!_patches)

Closed as having Pull Request #24651
