### ISSUE TITLE
Joomla 4 Warning Color

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#25990]
### What needs to be fixed
![grafik](https://user-images.githubusercontent.com/43232309/63577003-b5a41200-c58d-11e9-9633-148ef70f8d91.png)
This warning color is more heavy than error color and it it also ugly.
I suggest to take other color like:  #f9ddaa and font and border #aa2e00 it is over 5.15 color ratio for accessible:
![grafik](https://user-images.githubusercontent.com/43232309/63577182-264b2e80-c58e-11e9-937b-0536b67b6984.png)
Or maybe background and font is switch by accident in template?

**Comment by brianteeman** [comment]
I agree - see #25911

**Comment by ghost** [comment]
closed as duplicate report.
