### ISSUE TITLE
[4.0] Admin dashboard

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#25993]
### Steps to reproduce the issue
Go to Admin - Help dashboard
Go to Admin - User dashboard (no all is gone issue)
Go to Admin - Component dashboard (no all is gone issue)
Go to Admin - Menu dashboard (no all is gone issue)
Go to Admin - Content dashboard (no all is gone issue)
Go to Admin - System dashboard (no all is gone issue)

## Edit issue
![ezgif-1-9465bee5e08d](https://user-images.githubusercontent.com/181681/63578964-e128fb80-c591-11e9-9ec8-c0f1560afadf.gif)

## Unpublish issue
![2nd](https://user-images.githubusercontent.com/181681/63579283-8f34a580-c592-11e9-9aa8-f143fcec5650.gif)

## all is gone issue
after you click on unpublish and refresh the page all is gone
![Screenshot from 2019-08-23 11-02-42](https://user-images.githubusercontent.com/181681/63580667-9ad59b80-c595-11e9-9a88-d1f07a638336.png)

### Expected result
you are able to edit a dashboard  module
you are able to unpubislh  a dashboard module

**Comment by chmst** [comment]
Confirm the problem with unpublishing submenu modules. See #25999

But editing modules works fine for me.

**Comment by SharkyKZ** [comment]
Test PR #26245 which removes incorrectly placed module edit icons.

**Comment by infograf768** [comment]
Please do not close this for now.

**Comment by Quy** [comment]
@infograf768 Still keep it open?

**Comment by infograf768** [comment]
I think it is not necessary anymore as it was solved by https://github.com/joomla/joomla-cms/pull/26600 by preventing Edit/Unpublish dashboards. maybe not the ideal solution but can't think of another one.

Closing
