### ISSUE TITLE
[4.0] z-index issue with admin module dropdown

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26007]
![image](https://user-images.githubusercontent.com/1296369/63637743-49eaa380-c678-11e9-9a7b-99db013cdd29.png)

A picture is better than a thousand words

**Comment by infograf768** [comment]
Confirmed.

For eventual testers, this will show when creating an Administrator SubMenu admin module in CPanel position using Preset - Components Dashboard

**Comment by Quy** [comment]
Please test PR #26371<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26007">issues.joomla.org/tracker/joomla-cms/26007</a>.</sub>
