### ISSUE TITLE
Linkedin API upgrade to oauth v2

### ISSUE THREAD

**Issue by DonaldTrump88** [joomla/joomla-cms#26004]
### Steps to reproduce the issue
joomla-cms/libraries/joomla/linkedin/ still uses oauth v1. Linkedin has stopped supporting in May 2019. It needs to be upgraded to v2. 

https://support.klipfolio.com/hc/en-us/community/posts/360028378754-LinkedIn-Company-Pages-v1-to-v2-API-migration
https://developer.linkedin.com/docs/guide/v2/concepts
https://docs.microsoft.com/en-us/linkedin/marketing/
https://developer.linkedin.com/docs/rest-api

**Comment by mbabker** [comment]
The social APIs are all abandonware and deprecated, you’re better off finding a well supported PHP SDK for use with their API or writing your own methods to interact with it.

**Comment by alikon** [comment]
closing for the reason stated above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26004">issues.joomla.org/tracker/joomla-cms/26004</a>.</sub>
