### ISSUE TITLE
[4.0] Backend Template

### ISSUE THREAD

**Issue by impressionestudio** [joomla/joomla-cms#26006]
I just installed Alpha 11 of Joomla 4 in order to test the pull request #25979 which, by the way, was successful.

The problem is that the design of the backend template became worse than what I had seen in earlier versions which was quite nice.

Some of the problems I see are:

- There are too many boxes, frames, borders, shadows, boxes inside other boxes that make the design look old fashioned. Everything is in an intensively designed box (top header, left menu, cards, buttons, some icons (e.g. plus icon) etc).

- The main content background in the dashboard has a grey pattern, which is actually not visible by the cards, and then the cards have a white background and then the buttons have again a grey background. This is not good design for me. There are too many color changes for no use.

- These thin shadows do not help. Shadow on the header, shadow on the left menu, shadow on the cards, shadow on some buttons... The shadows are also an old design for me. Shadow is like the bad solution to solve the weakness of a bad template trying to separate content areas. If used, they must be very limited.

- In the "Site", "System" and "Update Checks" of the "Home Dashboard" I see too many big boxes/buttons that look ugly. Painting these big buttons on mouse hover is also bad.

- Too many colors in the buttons and the filtering options. For example, if you see the page with the Articles list, the buttons above the list have so many colors and backgrounds: blue, dark blue, white, grey, green. There is no logic on when and where these colors are used.

- The background colors of the three areas: header, left main menu and main content, do not fit to me so well. Usually the most often used an area is the brighter background it has. So the header should be darker, then main menu lighter and the main content white or almost white.

In the first versions of the Joomla 4 backend I was positively surprised by the design. But now I mostly don't like what I see. I believe that the design of Joomla 4 backend is a very very important issue because we will be seeing it for many years every day. And this design is what will make new developers interested in Joomla 4 and I am almost sure it will not be the fresh new code behind it.

**Comment by vintzl** [comment]
I agree with @impressionestudio, personally, I found the 4.10 backend template very clean and clear. Moreover, I found there are too much padding, so it leads to more scrolling.

**Comment by simbus82** [comment]
> I just installed Alpha 11 of Joomla 4 in order to test the pull request #25979 which, by the way, was successful.
> 
> The problem is that the design of the backend template became worse than what I had seen in earlier versions which was quite nice.

> In the first versions of the Joomla 4 backend I was positively surprised by the design. But now I mostly don't like what I see. I believe that the design of Joomla 4 backend is a very very important issue because we will be seeing it for many years every day. And this design is what will make new developers interested in Joomla 4 and I am almost sure it will not be the fresh new code behind it.

Totally agree! From the UI side is something quite unwatchable in 2019.

You can partecipate in this thread https://forum.joomla.org/viewtopic.php?f=803&t=970614&start=120

**Comment by lllopo** [comment]
Fully agree. Badly old-fashioned. Also not scaled well - for example the filter buttons are very big, having how many they are usually.

**Comment by korenevskiy** [comment]
Thanks.
If we do not come to our senses then Joomla 4 will suffer the consequences of Windows 8
https://github.com/joomla/joomla-cms/issues/27758

**Comment by Quy** [comment]
Closing. No need to have 2 issues for the same topic. Please continue discussion at #27758.
