### ISSUE TITLE
[staging] 500 when adding link to article in admin mod_custom

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#26018]
### Steps to reproduce the issue
Create an admin module of type custom at CPanel position.
Use the article or contact xtd to insert a link to an article or contact in the textarea.
Link produced is of the type:
`http://localhost:8888/installmulti/trunkgitnew/administrator/index.php?option=com_content&view=article&id=66&catid=32&lang=fr-FR`
or
`http://localhost:8888/installmulti/trunkgitnew/administrator/index.php?option=com_contact&view=contact&id=1&catid=23&lang=en-GB`

which is obviously wrong as it is should be a frontend link and therefore not contain `/administrator`.
Therefore we get a 500.

**Comment by alikon** [comment]
confirmed

**Comment by Quy** [comment]
In Editor - TinyMCE plugin, change `URLs` to `Absolute` for `Set 0`.

**Comment by alikon** [comment]
nice found, it do the trick....missing that option in the sea of options
