### ISSUE TITLE
[4.0] Feature request: show other images in article as in picture

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#26013]
Feature request: show other images in article as in picture

![Untitled11](https://user-images.githubusercontent.com/43875462/63639644-80d3b000-c69e-11e9-9262-8f3256362661.jpg)

j 4

**Comment by richard67** [comment]
@Milglius Could you elaborate what you mean? With the information above I only can say that your requested feature already exists: it is possible to add other images to articles than those shown above in your description. I.e. if you want, you can add an image with a cat or a dog, it does not necessarily need to show smart phones. 👅

**Comment by alikon** [comment]
i guess it is about somekind of slideshow/carousel

**Comment by richard67** [comment]
Can be, but I prefer to have a description instead of having to guess.

**Comment by brianteeman** [comment]
There are many many extensions that can do this for you.

**Comment by mbabker** [comment]
I'm going to take a guess they want core to provide an image gallery plugin for free because the OP does not want to pay for a suitable extension and none of the free ones fulfill their requirements.

**Comment by ghost** [comment]
yes joomla 4 feature request is **show other images of that article in the same article as in picture above** (slideshow/carousel if its called so)

i thought picture tells it all, but if you have other questions please ask  :)

brianteeman I tried 8 expensions and none of them could do this, please inform which one can do this (couse you know many many)?

mbabker you guest good congrats best option this feature should be open source and free

**Comment by ghost** [comment]
@richard67 sorry I forced you to guess

I thought picture tells it all, but if you have other questions please ask :)

I am here to elaborate, sory english is not my mother tongue.

**Comment by brianteeman** [comment]
Sorry @Milglius it is not the role of Joomla or this repository at github to build your site for you or to teach you every step to build your site.

**Comment by ghost** [comment]
Sorry brianteeman but its joomla 4 feature request : I repeat for you hope you are not a troll and still have basik english understanding _show other images of that article in the same article as in picture above_ (slideshow/carousel if its called so)

As we see here joomla and joomla extensions can't provide this feature now (brianteeman claimed he knows extension but it seems he was mistaken by building his site). 

Plese dont hijack this joomla feature request

**Comment by C-Lodder** [comment]
@Milglius There are 891 extensions under the **Photos & Images** category:

https://extensions.joomla.org/category/photos-a-images

That's excluding extensions that don't reside on JED. You'll find more on Github and other 3rd party services.

And for the love of god, stop up voting your own comments

**Comment by brianteeman** [comment]
@HLeithner when is it enough for someone to lose the privilege of using the joomla github

**Comment by HLeithner** [comment]
@Milglius we understand your request and tried so explain you that Joomla is heavily extension driven. For several reasons it's not possible to add everything to the core.

Such a feature you requested would need much work and could be part of a new frontend template which like to add this feature for everyone (even other templates).

At the moment we don't have the resources to create this feature and it doesn't look like anyone want's to mange such a project.

Anyway please be respectful as part of the Joomla community and accept answers and other opinions.

We leave your feature request open but I wouldn't expect any progress in the near future except you find one who can develop such feature in a proper way.

thx

**Comment by brianteeman** [comment]
@HLeithner 
Access to this issue queue is a privilege not a right. Like all privileges they should be removed when they are abused. This user is repeatedly abusing contributors. It is not their first or second or even third warning. 
If we really want to change the environment in Joomla https://community.joomla.org/blogs/community/joomla-we-have-a-problem.html and create an atmosphere where contributors are appreciated and we talk about the code and not the person this  lack of affirmative action is not helping to resolve the issue. 

It is simply sending a message to those who abuse the privilege of posting here that you can say and do anything without any consequences.

**Comment by HLeithner** [comment]
Do you really think banning people from an public tracker change anything? Creating a new user is done in 2 minutes and doesn't prevent anything. If he or anyone else conflicts with our CoC anyone can create a CoC report.

Then there is an official mandate to ban a person, in the meantime there could be done 2 things:
* Don't feed the troll
* Please him to stay nice

my opinion

**Comment by brianteeman** [comment]
depends if you care about contributors or not

**Comment by mbabker** [comment]
@HLeithner if you think it's fair that someone can come to this issue tracker, repeatedly open new issues on topics that have already been answered, demand that others write free solutions to fulfill their requirements, and berate individuals that do not agree with their viewpoint, then by all means the status quo is definitely the way to go.  Much easier than acknowledging that there is a problem and addressing it.

**Comment by ghost** [comment]
If someone think its a solution to delete/ban/... a user, go for it. I don't hink so, so i'm sharing the opinion of @HLeithner. 

Thats my only comment on this topic cause i'm here for another reasons.

**Comment by brianteeman** [comment]
I have never suggested banning. Just the removal of priveliges to post on GitHub. 

Read the blog post I linked to. 

I guess that if a board member doesn't agree with it and thinks allowing personal abuse then it's a sad day.

Going back to the pool now . Guess I won't be contributing to joomla while it is acceptable for personal abuse to be tolerated.

I note that the personal abuse has not even been removed.

**Comment by HLeithner** [comment]
@brianteeman seams I missed the personal abuse can you point me to it.

And we have a procedure for his it's a CoC report. Sorry that I don't restrict people arbitrarily.

**Comment by brianteeman** [comment]
Seriously. You have to be kidding. Goodbye

**Comment by mbabker** [comment]
For everyone who's tried emailing or DM'ing me in the last couple of weeks about why I've basically ghosted out of the project and teams on Glip, this thread specifically is an example of one of the problems I have with the state of the project and why I am choosing to spend less and less time engaging with it.  And if you don't see the problem in this thread, then you are probably part of the problem that I am deliberately distancing myself from.

**Comment by Quy** [comment]
I too find Milglius' postings demanding, offensive, toxic and negative about the project, developers, contributors, and forums.

Here are some examples:
https://github.com/joomla/joomla-cms/issues/25637#issuecomment-513224948
https://github.com/joomla/joomla-cms/issues/25942#issuecomment-524188044
https://github.com/joomla/joomla-cms/issues/25552#issuecomment-511210481

Plus, some his topics have been locked.

**Comment by bembelimen** [comment]
Independenten if Miglius posts are offensive or not, I don't think that one person (in this case Harald) should be the judge if a person's privileges should be removed or not, for this you can fill a COC.

But I agree with closing this issue (btw. a gallery is already included => custom fields)

**Comment by brianteeman** [comment]
To be clear - I am not contributing anything at all until action is taken to prevent contributors being abused.

**Comment by Gitjk** [comment]
Usually I'm pretty good in locating existing extensions for a certain problem, but after searching for half an hour in Google and the JED, I still didn't spot an extension which does what the original poster is asking for. So I think it's a legitimate feature request. Most e-commerce/shopping carts do offer this for their product descriptions, but as an add-on for simple Joomla articles?... <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26013">issues.joomla.org/tracker/joomla-cms/26013</a>.</sub>

**Comment by rdeutz** [comment]
I am closing this for two reasons:

* We follow the concept of a light core so we are including only essentional things into core. I have seriours doubts that a slider is something we need in the core of Joomla!
* The feature request doesn't fullfil our requrements. This is the place we are working on code and not quiz show

@Milglius sadly your behauviour is not what we are expecting form a contributer, I will give you 7 days to prepare a propper feature request. You might also use the time to think about how to interact with other contributers.
