### ISSUE TITLE
[4.0] Backend - Keep visible left panel everywhere

### ISSUE THREAD

**Issue by vintzl** [joomla/joomla-cms#26022]
### Is your feature request related to a problem? Please describe.
I find very annoying how left panel works.

On of the annoying case: for instance, if we open, for edit an article, and we do whatever we want after (save or check only), **we have to close this window, and only then, we can access the left panel.**

It start to be a waste of time after few hours of work per day… And I cannot see any reason why the left panel is no more here.

### Describe the solution you'd like
Keep visible left panel everywhere.

### Additional context
Joomla! 4.0.0-alpha10

**Comment by ghost** [comment]
If you close "Articles: Edit" you got:

![Bildschirmfoto 2019-08-25 um 16 18 15](https://user-images.githubusercontent.com/8235763/63651363-285eea00-c754-11e9-955c-457f41997fe1.png)

You want to have left Panel open if you edit an Article – right?

**Comment by dgrammatiko** [comment]
@vintzl there is a vital information that you’re missing: if you click away from a form without proper canceling the form editing (or saving and closing) then this particular item you were editing will need to be check out! So **even if the menu was visible you shouldn’t be able to leave a form by simply clicking on some link**

**Comment by vintzl** [comment]
Yes  @franz-wohlkoenig, but I think it could be better if this side menu was every time/everywhere visible.

@dgrammatiko, but what about a warning (with js) if we try to leave a page with unsaved changes?

Because, when developing/adding content, we often check a page for something, and leave it without made any change. And I find very frustrating to not having this side panel…

**Comment by dgrammatiko** [comment]
@vintzl at least I tried some time ago: https://github.com/joomla/joomla-cms/pull/4773 and https://github.com/joomla/joomla-cms/pull/5815

The point was and still is that this behaviour should be crystal clear to ALL users. Of course, the design here failed miserably and thus the whole system has quirks that people need to figure out either form documentation or other sources. In sort #FAIL

**Comment by vintzl** [comment]
@dgrammatiko, maybe we should try again, a set a clear and consistent manner.
Moreover, I would have cached forms using HTML5 local storage and with Js on fallback.
Then warn user, but in any case, the form will have been saved in the local storage.
Finally, keep this side panel always open :p

**Comment by dgrammatiko** [comment]
> Finally, keep this side panel always open

From a design point of view, there is zero advantage to have a disabled menu occupying 1/3 of your screen. You cannot click anywhere, it's there just as decoration but still reduces your real estate for the task you want to complete: fill/edit the form.

> maybe we should try again, a set a clear and consistent manner.

You are welcome to use that old PRs and come up with a new one...

**Comment by simbus82** [comment]
> > Finally, keep this side panel always open
> 
> From a design point of view, there is zero advantage to have a disabled menu occupying 1/3 of your screen. You cannot click anywhere, it's there just as decoration but still reduces your real estate for the task you want to complete: fill/edit the form.

From a UX/UI Design point of view is disturbing and wrong moving the focus of user from a position to another, example from the 20% left to the 0% left.
People typically hate editors aligned to border of the windows/screen. 

With a 16:9 HD full screen 90% of the people use the maximized browser windows, so they need to move their chairs (:-P) to start writing in the editor...
WP, DatoCMS... every CMS has the editor in the "middle" of the screen.
Asana, Hootsuite, etc every marketing/communication app has editors in center.
Word, Photoshop, Illustrator... every software try to put the "edit view" in the center of windows.
Why Joomla not?

PS: OMG. I see only now your old PRs about "warning" and action for a page leave. ALL CMS in the world now uses this UX actions. And many has the left bar fixed and its link always active.
The myopia and incompetence (in that moment) of those who did not accept those PRs... is incredible.
I'm shocked!

**Comment by brianteeman** [comment]
You do realise that in joomla 3 where the top menu is equivalent to the sidebar it is completely disabled when you are editing content. So the behaviour you describe

> Because, when developing/adding content, we often check a page for something, and leave it without made any change. 

Is no different today than it was before - you have to exit the edit view (either with cancel or brower back) - you could never just select a new menu item.

There is no change in behaviour between joomla 3 and 4 in this regard!!

**Comment by vintzl** [comment]
@dgrammatiko man, I am a "full time" C# developer… and occasionally, I do some Java C/C++ and less often I write some Python, Php and Ruby code… And static languages are my cup of tea. So I think a PHP coder will do a better job than me. Not considering that my PHP codes are "strictly" typed… Not really as Joomla core code…

@brianteeman 
I guess you right, there is no change in behaviour between joomla 3 and 4 in this regard. But last time I wrote some code for Joomla 3, **it was almost three years ago**. And it was a single page website with one simple component… But for this project, it is something much bigger… Thus, sorry, but I find the behavior of this side panel **very broken**.

**Comment by brianteeman** [comment]
On the basis that this has been the behaviour since at least joomla 1.5 and almost certainly before that (I just dont have a site that old to test) I dont see any need to change this behaviour. If it was broken for anyone but you then the issue tracker would have had a lot of requests regarding this over the last 14 years

**Comment by vintzl** [comment]
With such mentality, you can keep Joomla in XHTML 1.0, and CSS1, and of course, no need to try to [enhance the Backend](https://github.com/joomla/joomla-cms/issues/26006) (Maybe this is why it has worsen)…

With all due respect, and I repeat myself, you seem **to me** too much psychorigid… Take a look at #4773 and #5815… There are people who are interested…

Know that things can be enhanced, even if no horde beg you to do so…

**Comment by brianteeman** [comment]
> Know that things can be enhanced, even if no horde beg you to do so…

the difference is one is about web standards and something that many many people asked for. what you want is something that no one is asking for.

But if you want to submit a pull request that fixes the issue it will be tested and reviewed. You cant ask for more than that

**Comment by mbabker** [comment]
This issue is about the consistency of the sidebar.  Leave it that way.  Take the UX/workflow discussion to an appropriate thread, you don't need that decided/actioned to make a decision on whether the sidebar defaults open or closed on an edit view.

**Comment by vintzl** [comment]
Sorry I did a **very bad shortcut**… What I really wanted to write is that from joomla 1 to 4, there is no "functionality" like the one tried in #4773 and #5815…

Yet, there are people who are interested until today, but this feature is still missing… And yet again, we do not see a lot of request for this… Now, should we give up? I do not think so… as well as for my request.

> But if you want to submit a pull request that fixes the issue it will be tested and reviewed. You cant ask for more than that

Well, now I agree with you.
