### ISSUE TITLE
[4.0] upload zip file to upgrade to 4 Alpha11

### ISSUE THREAD

**Issue by neiljames** [joomla/joomla-cms#26025]
### Steps to reproduce the issue
Downloaded Joomla_4.0.0-alpha11-Alpha-Full_Package to desktop and tried to update joomla from 4.10 to 4.11

### Expected result

Joomla 4.11 

### Actual result

See jpg attached
### System information (as much as possible)

Apache 2.4.37
PHP 7.2.13
MySQL 5.7.24
Localhost
### Additional comments

Might have used the wrong zip file![screen shot 2019-08-25 at 14 57 33](https://issues.joomla.org/uploads/1/e17e93c66e4726106d5f65a86525bcf5.jpg)

**Comment by ghost** [comment]
Upgrades from Alpha to Alpha are not possible, you have to install a fresh copy. Updates will come at Beta-Stadium.

**Comment by vintzl** [comment]
@neiljames 
1. Make a full backup of all your files inside your current Joomla folder installation.
2. Make a full backup of your Joomla db.
3. Remove all files inside your current Joomla installation folder (even hidden ones).
4. Then copy/paste the new Alpha 11 files in your, now empty, Joomla installation folder. Fix rights if needed.
5. Finally, copy/paste all your custom (templates/modules/components, etc) files (from your back) inside your Alpha 11 folder.

**Comment by SharkyKZ** [comment]
Delete `libraries/autoload_psr4.php` file.

**Comment by ghost** [comment]
closed as solutions are provided. Issue can always be reopened if needed.
