### ISSUE TITLE
[4.0] Installation of testing sample data stops with PHP notice after step 3

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#26036]
### Steps to reproduce the issue

1. Install clean 4.0-dev.
2. Install testing sample data using corresponding button in control panel and watch the installation there.

### Expected result

Installation completes without any PHP notices or warnings or errors.

### Actual result

Installation stops after step 3.

5 identical PHP notices like following one (path shortened for readability):

> PHP Notice:  Undefined offset: 0 in /libraries/src/Table/Nested.php on line 1430
>

In browser console JS error (with system debug on in global settings so unminified js file is used):

> SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
> sampledata-process.js:42:29
>

### System information (as much as possible)

PHP 7.2
MySQL 5.7
Linux OS for webserver and dbserver
Browser: Firefox Quantum 68.0.2 (64-Bit) on Windows 10

### Additional comments

Was working when I've tested 1 or 2 weeks ago, so the error seems to be more or less new.

**Comment by ghazal** [comment]
Can't reproduce this issue with the sampledata plugin.
Admin sampledata module OK too.
PHP 7.2.5
MySQL 5.7.22 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26036">issues.joomla.org/tracker/joomla-cms/26036</a>.</sub>

**Comment by ghost** [comment]
Installed multilang. Sampledata – works as expected.
#### System Information

Setting | Value
-- | --
PHP Built On | Linux lamp129.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.5.el6h.x86_64 #1 SMP Thu Nov 22 10:07:47 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.23-cll-lve
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.7
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 4.0.0-alpha11-dev Development [ Amani ] 29-June-2019 11:27 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:68.0) Gecko/20100101 Firefox/68.0
Multilanguage | Yes: French, German, Persian

**Comment by richard67** [comment]
@franz-wohlkoenig The title of this issue clearly tells that it is about testing sample data, not multi language sample data.

Testing sample data is only available when working on clone of the GitHub repo, not when working with a nightly build.

@ghazal Did you try with testing sample data?

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/63771336-e7d7ab80-c8ce-11e9-895b-2d8f3a6ad744.png)

I could not replicate this

**Comment by franz-wohlkoenig** [comment]
@richard67 i wanted to make sure its not about multilang.

**Comment by ghazal** [comment]
@richard67 Yes, I tried the sampledata plugin, not the module.
On a today's cloned version, with composer and npm installed.

**Comment by richard67** [comment]
I've just tried it again and still have the error.

I did a clean install into an empty database with current 4.0-dev branch, with error reporting set to "Development" in global config server settings.

Current 4.0-dev means

- No remainders from previous tests
- Same external packages versions like on 4.0-dev, i.e. no composer update or so.

To make sure I have no remaonders from previous tests and no other unwanted files, I always do:

1. git checkout 4.0-dev
2. git remote update
3. git clean -d -x -f
4. git reset --hard upstream/4.0-dev
5. git push origin +4.0-dev
6. composer install
7. npm install

Then I cleared browser cache in order to be sure not to have any cached old js or css.

Then I make a new installation into empty database, without any modifications, i.e. no sample data, no additional languages.

Then I switch error reporting to "Development".

Then I go to the home dashboard and use the button marked with a red frame in the following screenshot to install testing sample data:

![Unbenannt-2](https://user-images.githubusercontent.com/7413183/63790967-b4ab1180-c8fa-11e9-855e-2f431d19f278.png)

@ghazal @brianteeman Sure you did not have any remainders from previous tests, or any updates external packages from a previous run of "composer update"? Or maybe it is the error reporting set to development which changes something? Btw. any debug I had switched off in global config. Can you check again with these settings?

**Comment by Quy** [comment]
I can reproduce the issue where Step 3 is stuck with PHP notices and console JS error.

**Comment by richard67** [comment]
Thanks god someone can reproduce it. I started to believe that I have visions or something wrong is in my tobacco ;-)

**Comment by alikon** [comment]
i can reproduce too, it seems related to the fact that now the finder plugins  are enabled by default 
at least this is what i can read in the error log

**Comment by ghazal** [comment]
@richard67 Don't worry about your tobacco.
I was finally able to reproduce the error with Error Reporting set to Development (and Finder plugins enabled).
Today's distrib.

**Comment by chmst** [comment]
Confirmed. It is still an issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26036">issues.joomla.org/tracker/joomla-cms/26036</a>.</sub>

**Comment by N6REJ** [comment]
confirmed still an issue as of 1hr ago pull 
![image](https://user-images.githubusercontent.com/1850089/64564602-888a8a00-d317-11e9-9b56-b8c70ad7a047.png)

**Comment by ghost** [comment]
Its expected that an Issue isn't resolved if no Pull Request is created ;-)

**Comment by N6REJ** [comment]
This breaks in the 2/2 section for articles.  It appears to be duplicate category issue.
step 4-6 completes properly.
pr #26235 does NOT fix the issue.

**Comment by N6REJ** [comment]
bit of debug info..
![image](https://user-images.githubusercontent.com/1850089/65395184-0a89a280-dd5d-11e9-8c3f-caa2e28a6500.png)
[j4test.local.har.zip](https://github.com/joomla/joomla-cms/files/3640230/j4test.local.har.zip)

**Comment by infograf768** [comment]
@N6REJ 
https://github.com/joomla/joomla-cms/pull/26235 solves part of the issue here:
<img width="526" alt="Screen Shot 2019-09-23 at 08 28 22" src="https://user-images.githubusercontent.com/869724/65405402-3ef07380-dddc-11e9-9ac8-a51e80ea9569.png">

Steps 8 and 9 not done.

**Comment by infograf768** [comment]
After another test, it sticks to step3... ⛔️

**Comment by infograf768** [comment]
To get it to work, I disabled ALL finder related plugins, including Content - Smartsearch
It installs fine but with a weird display:

<img width="607" alt="Screen Shot 2019-09-23 at 09 00 00" src="https://user-images.githubusercontent.com/869724/65406759-c9d36d00-dde0-11e9-8606-25572012d4ec.png">

**Comment by wilsonge** [comment]
yup disabling the smart search content plugin is good enough to work around for now (obviously not the long term solution). I've done some improved error handling in #26385 on the plane home last night so it now doesn't hang on the spinner but shows an error (doesn't actually solve the issue tho)

**Comment by infograf768** [comment]
Maybe we could disable the plugin in step1 and re-enable it in step9?

**Comment by wilsonge** [comment]
My guess is that if you manually create a category. then manually create an article and put it in the new category you're going to get the same error.

**Comment by richard67** [comment]
Will be solved by PR #26392 together with PR #27008 .
