### ISSUE TITLE
Cannot override renderfield.php on Registration view

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#26034]
### Steps to reproduce the issue

I've copied the following file:

> layouts/joomla/form/renderfield.php

to:

> templates/XXXX/html/layouts/joomla/form/renderfield.php

and made some changes. Everything good so far.

But when viewing the `com_users` registration page, this template override is void as `com_users` is overriding it also:

https://github.com/joomla/joomla-cms/tree/staging/components/com_users/layouts/joomla/form

### System information (as much as possible)

- Joomla 3.9.11
- PHP 7.2

**Comment by HLeithner** [comment]
In this case you have to override the component version too.
iirc the path should be 
```templates/XXXX/html/layouts/com_users/joomla/form/renderfield.php```
or
```templates/XXXX/html/layouts/com_users/form/renderfield.php```

**Comment by C-Lodder** [comment]
thanks @HLeithner, that worked perfectly
