### ISSUE TITLE
[3.10] [4.0] pre-update checker broken

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26048]
At some point since the merge of #17742 into 3.10 branch a subsequent commit has completely broken its functionality - it doesn't appear at all.

You can confirm this on 3.10 and 4.0 by following the test instructions on #17742

This is obviously a release blocker for both 3.10 and 4.0

**Comment by zero-24** [comment]
Hi, can you please explain what is the actual issue here is?

When you mean this message
![image](https://user-images.githubusercontent.com/2596554/63980612-79584080-cabc-11e9-85fe-05667851bf21.png)

The first thing is that we enable the updates from the update server please check: https://github.com/joomla/update.joomla.org/pull/145

**Comment by zero-24** [comment]
As mention in the other issue when the update server allows you to update from 3.10 to 4.0 the pre update checker comes up to me:
![image](https://user-images.githubusercontent.com/2596554/63981001-8f1a3580-cabd-11e9-89ad-24a162e3a02c.png)

Feel free to check it yourself by using this patched version of the update server: https://www.jah-tz.de/downloads/core/nightlies/next_major_list.xml

**Comment by zero-24** [comment]
Please note that 4.0 also requires 5.6 as database version and at least my xampp still runs with 5.5 please double check that when the update / pre update checker does not come up.

**Comment by brianteeman** [comment]
OK - I must have done something wrong with the local xml (which I had updated) as it works correctly with your update server.

Thanks for your patience.

Now I can write the code to fix the a11y on that page

**Comment by zero-24** [comment]
Great thanks for the update 👍
