### ISSUE TITLE
[4.0] Calendar usability in Filter Options

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#26044]
In Filter Options, calendar closes when switching between months and years using the arrows.

### Steps to reproduce the issue
Go to `Banners > Tracks`
Click `Filter Options` button
Click calendar icon
Click on `<` or `>`
Calendar closes

**Comment by ghost** [comment]
Issue confirmed.

**Comment by Quy** [comment]
Closing as no longer reproducible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26044">issues.joomla.org/tracker/joomla-cms/26044</a>.</sub>
