### ISSUE TITLE
[4.0] Count styling consistency

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26051]
A can be seen in the screenshots below there is no consistency in the styling of counts
### com_users groups
![image](https://user-images.githubusercontent.com/1296369/63813289-0d8f9f80-c925-11e9-94cb-6d82602a3048.png)

### com_content categories
![image](https://user-images.githubusercontent.com/1296369/63813365-4cbdf080-c925-11e9-9429-2efcf4a3f2af.png)

### com_menus manage
![image](https://user-images.githubusercontent.com/1296369/63813393-62331a80-c925-11e9-89bc-cc6c1c44d5bb.png)

**Comment by ghost** [comment]
Closed as having Pull Request #26066
