### ISSUE TITLE
[4.0] Terrible Overrides of Bootstrap Classes

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#26052]
I'm not wasting my time checking every Bootstrap component (TBH I don't know why I'm wasting my time with the issue), but what I saw in the [`_badge.scss`](https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/scss/vendor/bootstrap/_badge.scss) file scares me.  There are lots of good ways to override things in Bootstrap; change variable values or using custom functions or mixins to add app specific logic are two good ways.  Instead, the bad way of adding some CSS rules to override the SCSS generated values is used.  And apparently somebody decided that `badge-secondary` and `badge-info` are the exact same thing.  Why, just why!?

**Comment by infograf768** [comment]
@coolcat-creations
As it looks like you are the "somebody" and what you did scares "someone", can you explain?
https://github.com/joomla/joomla-cms/commit/d1b925a8c45f88203f1d0e510e470777d00a3e5c#diff-6a6e80a2ffae9ebe4bb49d5212880a62

**Comment by C-Lodder** [comment]
```
font-size: $badge-font-size;
padding: .1rem .3rem;
border-radius:0.3rem;
```

These can already be set by variables.

For things like badges, I'd suggest using the background utilities rather than defining `badge-danger`, `badge-success`, etc...:

https://getbootstrap.com/docs/4.3/utilities/colors/#background-color

The badge SCSS is one example of unecessary bloat.

The same applies to the alerts. There's `6kb` of **MINIFIED** CSS for the alerts alone, including the bootstrap ones, overrides and custom elements.

**Comment by dgrammatiko** [comment]
@C-Lodder for alerts specifically (same goes for tabs, tinyMCE etc...) the code is far worse. Reason: you already loading the specific CSS file (means one more http request was already done for this) and then the template overrides this files **internally**. The correct approach is to override the file by placing the css file in the template css directory. I guess this is very basic for anyone that did at least one website based on Joomla... In sort **#FAIL**

PS Charlie you remember all these talks about componentizing and modularizing the css? Well they did exactly the opposite. Forward thinking approach...

**Comment by mbabker** [comment]
> For things like badges, I'd suggest using the background utilities rather than defining `badge-danger`, `badge-success`, etc...:

Well until Bootstrap goes to using the background utility classes on their components, the component utility classes should still work adequately (basically, the less surprises there are between their documentation and the template implementation the better, sadly this isn't the first time I've found some awkward deviation from the Bootstrap documentation in this template).

**Comment by brianteeman** [comment]
@all Instead of "bitching" - roll up your sleeves

**Comment by dgrammatiko** [comment]
@brianteeman at least I've tried: https://github.com/joomla/joomla-cms/pull/26014 You got to give me that...

**Comment by mbabker** [comment]
Am I welcome in this repo again?  Last I checked, I was on so many blacklists the blacklists had blacklists.

**Comment by jeckodevelopment** [comment]
do we really have blacklists?  i'm not aware of that and i should be the list keeper

**Comment by brianteeman** [comment]
Is this really still relevant. The template must have undergone at least two rewrites since then and changed to bootstrap 5

**Comment by alikon** [comment]
No imho
