### ISSUE TITLE
[4.0] Admin sidebar menu wrapper opens and closes after selecting function

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#26058]
### Steps to reproduce the issue
Log into Admin 
Toggle the left sidebar menu so that it is minimised
Select one of the options without a sub-menu, e.g. System

### Expected result
The sidebar menu wrapper should stay minimised

### Actual result
The sidebar wrapper briefly expands to its standard width - but empty of content - and then shrinks back to minimum width, all within less than a second:

![1-wrapper-minimised](https://user-images.githubusercontent.com/36987494/63876137-cead2880-c9bc-11e9-9c3a-1afb2bec0d23.jpg)

![2-wrapper-expanding](https://user-images.githubusercontent.com/36987494/63876163-d8369080-c9bc-11e9-98a6-aec1567c63a4.jpg)

![3-wrapper-expanded](https://user-images.githubusercontent.com/36987494/63876174-dd93db00-c9bc-11e9-9e1f-82c692967a8b.jpg)

### System information (as much as possible)
Installation: Joomla 4.0 Alpha 11 full package
Browser: Firefox
OS: Windows 10

### Additional comments
1. On Google Chrome, it only does this when clicking the Home icon, but the screen does 'flash' when clicking onto System, or Help, so I think it's doing the same thing, only quicker.

2. After noticing this, I tested it on the Content and, as there are sub-menus, the menu needs to re-expands anyway and does so. It does this for four of the seven menu items, so I'm wondering if there is a need for the toggle at all.

3. When the menu is minimised, there are only icons visible (i.e. no text). Whilst the icons are reasonably self-explanatory, it would be useful to have tool tips when hovering over the icons.

**Comment by ghost** [comment]
>  Select one of the options without a sub-menu, e.g. System

Didn't get you as "system" is the Module called – can you please explain detailed?

I tried to replicate looking at your screenshots and can't get this behaviour.
#### System Information

Setting | Value
-- | --
PHP Built On | Linux lamp129.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.5.el6h.x86_64 #1 SMP Thu Nov 22 10:07:47 EST 2018 x86_64
Database Type | mysql
Database Version | 5.7.23-cll-lve
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.7
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 4.0.0-alpha11-dev Development [ Amani ] 29-June-2019 11:27 GMT
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:68.0) Gecko/20100101 Firefox/68.0
Multilanguage | Yes: French, German, Persian

**Comment by Scrabble96** [comment]
> 
> Didn't get you as "system" is the Module called – can you please explain detailed?
> 
Here's a PDF with more steps indicated

[26058-admin-menu-toggle.pdf](https://github.com/joomla/joomla-cms/files/3554755/26058-admin-menu-toggle.pdf)

**Comment by ghost** [comment]
Got it, meant is "System Dashboard". Can't replicate anyway this behaviour.

**Comment by Scrabble96** [comment]
I have now attached a very small 11-second video demonstrating the effect. It's in a zip file as Github does not accept mp4 files.

[J4A11-admin-menu-20190829_160536.zip](https://github.com/joomla/joomla-cms/files/3556227/J4A11-admin-menu-20190829_160536.zip)

**Comment by infograf768** [comment]
Confirmed. Not sure we can call this an issue.
![wrapper](https://user-images.githubusercontent.com/869724/64002867-6325a100-cb0b-11e9-9f72-ed12261267b5.gif)

**Comment by alikon** [comment]
Closing this  due to not receiving required information to determine if this is a bug or not. If you feel this still needs review, please open a new tracker entry with as much information as possible to ensure it can be reviewed properly

**Comment by brianteeman** [comment]
@alikon what was the required information that you were seeking? From what I can see everything is here.

**Comment by jwaisner** [comment]
@brianteeman These were marked as information required by someone. They have been open with no updates for months. I do not think closing record that are in that state and offering the option to create a new entry is a problem. This tracker is not managed effectively and is difficult to navigate. From a reporting perspective this looks like we are sitting on multiple open items when in reality they dont apply or were never confirmed as a bug. Based on what Nicola is doing I think it is a much needed clean up of the tracker and we can work to manage better the "information needed" tags going forward to ensure we dont end up the same boat again.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26058">issues.joomla.org/tracker/joomla-cms/26058</a>.</sub>

**Comment by brianteeman** [comment]
It might have been marked as information required (not on github only on jissues) but that was before @infograf768 commented and confirmed the report. The solution to "outdated" issues is not to blindly close them. In this specific example I personally would have just removed the information required label as it was clearly out of date and there was no outstanding information. In particular the copy/paste text was not applicable to this case. I did write a range of texts that could be used for a variety of different scenarios to avoid this and shared it with @alikon 

and please don't forget it is not a bug tracker - it is a combined bug and feature tracker.

**Comment by coolcat-creations** [comment]
Seems we are using https://github.com/onokumus/metismenujs for the menu, maybe updating it to the latest version (from 1.1.0 to 1.2.0) will fix issues? How to do that the proper way?

**Comment by brianteeman** [comment]
To update metis menu you just need to do an npm update

> `npm update metismenu`

**Comment by coolcat-creations** [comment]
> To update metis menu you just need to do an npm update
> 
> > `npm update metismenu`

Thank you, and this has to be done manually then with every release?

**Comment by coolcat-creations** [comment]
The issue still exists, anyone who can solve it?

**Comment by HLeithner** [comment]
The problem is the animation of the `closed` class, if we remove the open/close animation it works without the glitch.

As alternative we can set the open/close state as cookie instead of the localstorage and set the correct class in php.

@dgrammatiko or do you have a better idea to add the `close` class without the css animation?

**Comment by Quy** [comment]
This is no longer reproducible. Please confirm.

**Comment by chmst** [comment]
Cannot reproduce either

**Comment by Quy** [comment]
Closing as no longer reproducible. Thanks for the report.
