### ISSUE TITLE
[4.0] submenu dashboard module [a11y]

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26068]
Although the dashboards look like they have a lot of modules they are really mostly one module. This causes an accessibility problem as the cog dropdown is given the id of the module and an id must be unique

Go to the system dashboard on a clean install and all of those blocks are really just the same block and the cog icons in those blocks are all duplicates

**Comment by infograf768** [comment]
As explained in another issue, repeating that cog icon is also extremely confusing when adding multiple admin modules in a dashboard.
See https://github.com/joomla/joomla-cms/pull/26009#issuecomment-524612287

**Comment by brianteeman** [comment]
Please stop bikeshedding!!

This issue is about the accessibility and nothing else!!!!!!

**Comment by infograf768** [comment]
I don't know what you mean by bike shedding. I suppose it is not a nice word.
So cool down please.
It is clear that both issues are related. And it is not trivial.
If one has only one cog per REAL module, I guess the a11y would be easier to solve.

**Comment by brianteeman** [comment]
w

**Comment by B3nito** [comment]
@infograf768 https://www.youtube.com/watch?v=H4NW-Cqh308 I have like this video very much ...

**Comment by infograf768** [comment]
This patch removes the cog for dashboards sub items
https://github.com/joomla/joomla-cms/pull/26245

We still have a flaw though as the Real submenu Dashboard has no more cog, apparently because of Chrome.
