### ISSUE TITLE
403 error on creating new user

### ISSUE THREAD

**Issue by lijin4353** [joomla/joomla-cms#26062]
### Steps to reproduce the issue

A 404 error occurred after the user was created using the background

After installing joomla normally, I did not make any Settings, but 404 appeared after adding a New user directly in the backend, and 404 appeared after several buttons like Save Save & Close Save & New Cancel were clicked
Specific operation process can be downloaded below Excel file
URL:
http://sumcms.sumking.jp/404.xlsx

### Expected result
Displays the page where the user was successfully added

### Actual result
Display 404 pages

### System information (as much as possible)

Setting | Value
-- | --
 
PHP Built On | Linux users703.phy.lolipop.jp 4.14.33-300.1.1.hl6.x86_64 #1 SMP Mon Apr 9 03:08:03 JST 2018 x86_64
Database Type | mysql
Database Version | 5.6.23-log
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.1.5
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.9.11 Stable [ Amani ] 13-August-2019 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by ghost** [comment]
Please give more system information (like which 3.9-Joomla-Version, etc.) and how to reproduce the issue.

Can't confirm creating a new user in backend.

**Comment by lijin4353** [comment]
> 请提供更多系统信息（如3.9-Joomla-Version等）以及如何重现该问题。
> 
> 无法确认在后端创建新用户。

A screenshot of the 404 action appears
URL:http://sumcms.sumking.jp/404.xlsx

Setting | Value
-- | --
 
PHP Built On | Linux users703.phy.lolipop.jp 4.14.33-300.1.1.hl6.x86_64 #1 SMP Mon Apr 9 03:08:03 JST 2018 x86_64
Database Type | mysql
Database Version | 5.6.23-log
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.1.5
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.9.11 Stable [ Amani ] 13-August-2019 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by ghost** [comment]
> how to reproduce the issue.

please give information how you get the issue (frontend, backend, when did 404 come up, …) so developers don't have to guess.

**Comment by lijin4353** [comment]
> > how to reproduce the issue.
> 
> please give information how you get the issue (frontend, backend, when did 404 come up, …) so developers don't have to guess.

hello

After installing joomla normally, I did not make any Settings, but 404 appeared after adding a New user directly in the background, and 404 appeared after several buttons like Save Save & Close Save & New Cancel were clicked

Specific operation process can be downloaded below Excel file
URL:
http://sumcms.sumking.jp/404.xlsx

**Comment by ghost** [comment]
@lijin4353 thanks for the Informations. I hope a dev. will get in touch with it or ask you more details.

**Comment by lijin4353** [comment]
> @lijin4353 thanks for the Informations. I hope a dev. will get in touch with it or ask you more details.

Thank you very much for your help. This problem has been bothering me all day

**Comment by ghost** [comment]
do you have asked before on [Forum](https://forum.joomla.org/) as this Repository is for coding?

**Comment by SharkyKZ** [comment]
It says 403, not 404. It's likely to be caused by your server's firewall.

**Comment by lijin4353** [comment]
> do you have asked before on [Forum](https://forum.joomla.org/) as this Repository is for coding?

I didn't ask about database coding on Forum

**Comment by lijin4353** [comment]
> It says 403, not 404. It's likely to be caused by your server's firewall.

Thank you for reminding me. It's 403, not 404

**Comment by lijin4353** [comment]
Thank you very much
The problem was solved
The process of solving a problem
Login server background to turn off WAF function
You need to wait 5-10 minutes

The following file can be downloaded for specific operation
https://pan.baiduwp.com/s/19ZEQcKdwzJooPvqpELL5RQ
