### ISSUE TITLE
[4.0] Naming of presets for the main menu

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#26067]
### Is your feature request related to a problem? Please describe.

Go to Administrator - content - administrator module - new.
Here you can choose a preset for your Administrator Menu.

For the main menu you can choose between "Joomla" and "Modern"

This was already awkward in v3.9, as Joomla and Modern should not be Alternatives.
But in V4. "Modern" is the menu from Version 3.9. 

### Describe the solution you'd like
Choose other names for presets. Maybe Joomla3 and Joomla4?
Or Joomla-classic and Joomla-modern

**Comment by brianteeman** [comment]
I think its more that "modern" has never been updated with the new features in j4 - not just the new menu structure

**Comment by chmst** [comment]
This is the question. What is the difference between Joomla and modern? Is Joomla old-fashioned? 
What is modern compared to Joomla? Do we need different presets?

**Comment by brianteeman** [comment]
I would suggest to first decide if we need two presets and what is their purpose.

Only then can we really know what to call it.

My 2c is that we don't need 2 presets

**Comment by infograf768** [comment]
Joomla and Modern are alternatives. And not bad ones imho.
If someone does not want all the dashboard stuff except the Home dashboard , specially the System Dashboard, then the Modern preset is the preset to use as it proposes a similar navigation to what we had in 3.x
Does it need to be updated? I did not check all but it should be easy to do if needed.

**Comment by brianteeman** [comment]
I would name them default and alternate
but if nobody updates the second one then it should be removed

**Comment by infograf768** [comment]
First has to be decided what is missing into it... if anything is.

**Comment by chmst** [comment]
I agree that a simple preset "modern" is useful.
But it seems that I am the only one who automatically thinks "if this is modern, then other one alternative (Joomla) is old-fashioned"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26067">issues.joomla.org/tracker/joomla-cms/26067</a>.</sub>

**Comment by infograf768** [comment]
Understand. Changing names is the solution.

**Comment by infograf768** [comment]
The main change I would do for the "modern" one that could indeed be called "Alternate" is placing the Home Dashboard out of the MOD_MENU_SYSTEM container as its own. I.e.
```
	<menuitem
		type="component"
		title="MOD_MENU_CONTROL_PANEL"
		link="index.php"
		element="com_cpanel"
		class="home"
	/>

	<menuitem
		title="MOD_MENU_SYSTEM"
		type="heading"
		icon="wrench"
		class="class:wrench"
		>
etc.
```

In order to get
<img width="306" alt="Screen Shot 2019-08-29 at 18 38 35" src="https://user-images.githubusercontent.com/869724/63959360-4ac27180-ca8c-11e9-947b-4fb8a6147050.png">

**Comment by infograf768** [comment]
Also, needs moving Content above Media and take off the redundant workflows item. Add Smart Search when https://github.com/joomla/joomla-cms/pull/24020 will be done

**Comment by chmst** [comment]
Naming "default" and "alternate" is a first step, I'll try to find what has to be changed to do that. 
Changing the content of a preset then is easy.

**Comment by infograf768** [comment]
Apart from changing the names of the files, the code is in the MenusHelper in the `getPresets()` method. Therefore 2 lang strings to delete and 2 new ones to add + the path. 
```
static::addPreset('joomla', 'JLIB_MENUS_PRESET_JOOMLA', JPATH_ADMINISTRATOR . '/components/com_menus/presets/joomla.xml');
			static::addPreset('modern', 'JLIB_MENUS_PRESET_MODERN', JPATH_ADMINISTRATOR . '/components/com_menus/presets/modern.xml');
			static::addPreset('system', 'JLIB_MENUS_PRESET_SYSTEM', JPATH_ADMINISTRATOR . '/components/com_menus/presets/system.xml');
			static::addPreset('content', 'JLIB_MENUS_PRESET_CONTENT', JPATH_ADMINISTRATOR . '/components/com_menus/presets/content.xml');
			static::addPreset('help', 'JLIB_MENUS_PRESET_HELP', JPATH_ADMINISTRATOR . '/components/com_menus/presets/help.xml');
			static::addPreset('menus', 'JLIB_MENUS_PRESET_MENUS', JPATH_ADMINISTRATOR . '/components/com_menus/presets/menus.xml');
			static::addPreset('components', 'JLIB_MENUS_PRESET_COMPONENTS', JPATH_ADMINISTRATOR . '/components/com_menus/presets/components.xml');
			static::addPreset('users', 'JLIB_MENUS_PRESET_USERS', JPATH_ADMINISTRATOR . '/components/com_menus/presets/users.xml');
```
Simple to do.

**Comment by infograf768** [comment]
Can do if you wish

**Comment by chmst** [comment]
The renaming is done, but the alternate preset does not work as it is now.  I must derive it from the new default one. .

**Comment by infograf768** [comment]
>  I must derive it from the new default one. 

Can you explain? For me, except for a few things I noted above, it does not need much changes. Basically I see it without any dashboard except the Home one.

**Comment by chmst** [comment]
Seeems to be only missing language keys in the extensions submenu.

**Comment by infograf768** [comment]
That happened to me also at first sight.
I had to reload browser and the lang keys values display again instead of the constants.

**Comment by infograf768** [comment]
![preset](https://user-images.githubusercontent.com/869724/64001958-44bea600-cb09-11e9-9194-60406dd9c27f.gif)

**Comment by chmst** [comment]
@infograf768 Please try this. I have renamed the files but see conflicts.

**Comment by infograf768** [comment]
Closing as we have a patch
https://github.com/joomla/joomla-cms/pull/26084

**Comment by infograf768** [comment]
> @infograf768 Please try this. I have renamed the files but see conflicts.

Asked Tobias to look at that

**Comment by infograf768** [comment]
Found an issue for the joomla-default as well as for modern-alternate preset. We miss a sub menu for Messaging with the link
`option=com_messages&view=messages`
I guess it has to be added in the sql

I know we can access there via the top icon but I think we should anyway

**Comment by chmst** [comment]
You are right that this is missingin the presets. Would you open an issue for that? 

It is something private while all other links are just joomla, so don't see where it matches.
