### ISSUE TITLE
Popular Tags module is not showing after update

### ISSUE THREAD

**Issue by fr3deric** [joomla/joomla-cms#26061]
### Steps to reproduce the issue
- Have a module "Popular Tags" visible in the frontend
- In the Joomla Backend: check for Joomla updates (current version 3.10)
- Update to Joomla 3.11

### Expected result
The "Popular Tags" Module is still visible in the frontend

### Actual result
The "Popular Tags" Module disapears

### System information (as much as possible)
Database Version 	5.5.60-0+deb7u1
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.2.14
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.9.11 Stable [ Amani ] 13-August-2019 15:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 

### Additional comments
I hope this is the correct way to file something which I believe is a bug. This is the first time I actuallly used the issue tracker :-)
I also cleared all caches and tried different templates, e.g. Protostar

**Comment by Quy** [comment]
Please see if your issue is related to #23582 that was fixed in v3.9.11 with PR #25473.

**Comment by Quy** [comment]
Closing due to no response. Please post to Joomla forums if you still need assistance.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26061">issues.joomla.org/tracker/joomla-cms/26061</a>.</sub>

**Comment by slepoy1** [comment]
Hello. I have the same issue in J3.9.11 and J3.9.12. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26061">issues.joomla.org/tracker/joomla-cms/26061</a>.</sub>
