### ISSUE TITLE
[4.0] Template Fix Button code

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#26075]
The button styling has to be fixed but can't be done because the Button code is not consistent. Please see PR https://github.com/joomla/joomla-cms/pull/26070
for reference.

**Comment by brianteeman** [comment]
Please post the buttons that you say have problems

**Comment by Hackwar** [comment]
Sorry, but that is a completely useless bug report. If I hadn't read the other PR, I wouldn't know what you were talking about. And even now I have no idea what you mean with the apparently broken buttons, because they are pretty much okay as far as I can see.

**Comment by coolcat-creations** [comment]
![grafik](https://user-images.githubusercontent.com/828371/63976791-6b052700-cab2-11e9-9165-abb797c39e66.png)

**Comment by coolcat-creations** [comment]
![grafik](https://user-images.githubusercontent.com/828371/63976809-75bfbc00-cab2-11e9-825a-8259791f133b.png)

**Comment by coolcat-creations** [comment]
![grafik](https://user-images.githubusercontent.com/828371/63976878-a0117980-cab2-11e9-8f80-c91b31a18af6.png)
Quickicons using different classes too

**Comment by coolcat-creations** [comment]
![grafik](https://user-images.githubusercontent.com/828371/63976950-ca633700-cab2-11e9-92b1-6d0cf4022ed1.png)
Dropdown in Manage Menus also different code than save and close button

**Comment by coolcat-creations** [comment]
Export Icon does not use class btn-sm
![grafik](https://user-images.githubusercontent.com/828371/63977015-f2529a80-cab2-11e9-8026-d42bc7a5e759.png)

**Comment by coolcat-creations** [comment]
Option and Help does not use btn-sm
![grafik](https://user-images.githubusercontent.com/828371/63977044-05656a80-cab3-11e9-90b5-15803f72f341.png)

**Comment by coolcat-creations** [comment]
Batch does not use btn-sm class
![grafik](https://user-images.githubusercontent.com/828371/63977087-2201a280-cab3-11e9-8ce8-5c563fcee349.png)

**Comment by coolcat-creations** [comment]
Install Buttons Icon missing: 
![grafik](https://user-images.githubusercontent.com/828371/63977170-5ffec680-cab3-11e9-9796-2c6137ec1ed4.png)

**Comment by coolcat-creations** [comment]
Do not have btn-sm class
![grafik](https://user-images.githubusercontent.com/828371/63977205-73119680-cab3-11e9-97d1-940ca6b85da6.png)

**Comment by coolcat-creations** [comment]
left one does not use btn-sm class
![grafik](https://user-images.githubusercontent.com/828371/63977312-c8e63e80-cab3-11e9-9827-e4e987c511f5.png)

**Comment by Hackwar** [comment]
> 
> 
> ![grafik](https://user-images.githubusercontent.com/828371/63976791-6b052700-cab2-11e9-9165-abb797c39e66.png)

Again, can you please elaborate what is wrong with the markup that apparently makes this wrong?

**Comment by coolcat-creations** [comment]
![grafik](https://user-images.githubusercontent.com/828371/63977561-70637100-cab4-11e9-810d-b19a17e579f3.png)

If the code structure is the same, then all the dropdown-buttons will appear the same. I don't think we should fix wrong classes or different used structures with css. The structure should be likewise for same kind of buttons.

For the btn-sm classes I hope it's clear - there has to be a decision if there should be big OR small buttons and the classes should be equal. For the Action Drop Down / Save and Close both should use the same structure and then we can style one of these, but it should be consistent codewise.

**Comment by Hackwar** [comment]
Sorry, I might be blind, but I don't see a difference between these. It is the same XML structure...

**Comment by coolcat-creations** [comment]
It's not the same structure, if it was so it would appear the same. At the bottom you can spot the differences.

**Comment by coolcat-creations** [comment]
This is how it looks like if the structure is the same like save&close:
![grafik](https://user-images.githubusercontent.com/828371/63978411-912cc600-cab6-11e9-9468-422c929f2323.png)

**Comment by coolcat-creations** [comment]
Wrong styling here too...
![grafik](https://user-images.githubusercontent.com/828371/63979537-6728d300-cab9-11e9-80ea-6c1091997936.png)

**Comment by brianteeman** [comment]
what is wrong with that?

**Comment by coolcat-creations** [comment]
It's again different styling, markup and size.

**Comment by brianteeman** [comment]
seems ok to me

**Comment by brianteeman** [comment]
Is there anything to do here or should it be closed

**Comment by coolcat-creations** [comment]
The Toolbar Buttons seem to have almost all now a consistent class btn-sm - but in my opinion the toolbar buttons represent a regular size. So the Class should be not btn-sm
If you compare to the Install Buttons on the Home dashboard, the Install buttons are way smaller. They also have the btn-sm class. Which is correct for the small ones. 

btn-sm
<img width="112" alt="grafik" src="https://user-images.githubusercontent.com/828371/79065031-c4227380-7cad-11ea-932a-1e2e1061c058.png">

should not be btn-sm
<img width="460" alt="grafik" src="https://user-images.githubusercontent.com/828371/79065097-0b106900-7cae-11ea-833c-e39b30117eb8.png">

should have the same class as the toolbar Buttons:
<img width="157" alt="grafik" src="https://user-images.githubusercontent.com/828371/79065110-195e8500-7cae-11ea-853d-bf8113d46d09.png">

**Comment by brianteeman** [comment]
Closed as there is a pr
