### ISSUE TITLE
[4.0] fontawesome duplicated

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26093]
Use chrome inspector or similar and you will see that the icons are getting the css from **both** 

`media/vendor/fontawesome-free/css/fontawesome.css
`

and 

`administrator/templates/atum/css/template.css`

This is probably due to the changes in this commit by @bembelimen https://github.com/joomla/joomla-cms/commit/94bf16680eccf72daf5cd1864f7cc3b126e4db06

Obviously its not a good idea to load the same css twice

**Comment by dgrammatiko** [comment]
#26077 should fix this
