### ISSUE TITLE
[4.0] top-b and bottom-b missing chromes so do not display title when set to 'Show'

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#26095]
### Steps to reproduce the issue
Create a module in Cassiopeia of the type 'top-b' (or 'bottom-b'; this issue applies to both modules)
Set the title to 'Show'
### Expected result
Visible title

### Actual result
No title:
![Alpha11-module-top-b](https://user-images.githubusercontent.com/36987494/64037500-9e48c400-cb4d-11e9-83e1-94623ee41b54.jpg)

### System information (as much as possible)
Joomla 4 Alpha 11 full package nightly from 30.08.2019

### Additional comments
Index.php shows the code for this module is exactly the same as for the adjacent 'top-a' except for the style, which is 'card', rather than 'cardGrey':

```
    <?php if ($this->countModules('top-a')) : ?>
	<div class="grid-child container-top-a">
		<jdoc:include type="modules" name="top-a" style="cardGrey" />
	</div>
	<?php endif; ?>

	<?php if ($this->countModules('top-b')) : ?>
	<div class="grid-child container-top-b">
		<jdoc:include type="modules" name="top-b" style="card" />
	</div>
	<?php endif; ?>

```

The only difference being that top-a has a grey background. (I'm not sure where "cardGrey" comes from as it is defined as "card-grey" in both the minified and unminified template.css files.)

There are two Chromes for modules which, under the new system, are in html -> layouts -> chromes cardGrey.php and default.php, which differ only that cardGrey.php includes the class `card card-grey` and the default just `card

There does not appear to be any instruction to say - "do not display the title".
If there is, where is it and how can it be overridden?

**Comment by brianteeman** [comment]
> I'm not sure where "cardGrey" comes from 
As you stated in your next line its the name of the chrome - not the same thing as a css class

As for the "card" chrome that looks to me like you found a bug as I see several other chromes that are not defined either eg xhtml

**Comment by ReLater** [comment]
> I see several other chromes that are not defined either eg xhtml

xhtml has been removed in favor of html5 chrome. Sorry, I don't find the pr at the moment.

**Comment by brianteeman** [comment]
yes I know but the template has not been updated

**Comment by ReLater** [comment]
Ah, OK. Thanks for clarification.

**Comment by Scrabble96** [comment]
Of the current Cassiopeia chromes, both default.php and cardGrey.php, I've noticed some missing code in line 26:

Current code:
`<div class="card-body">`

Proposed code to allow styling of body section in modules in different positions, particularly for custom modules, but it may well apply to other types, too:

`<div class="<?php echo $modulePos; ?> card-body">`

I'm happy to raise a PR for this.

**Comment by Scrabble96** [comment]
I'm closing the PR but leaving this issue open because, as @brianteeman said earlier, several chromes have not been defined. Consequently, I've changed the title to reflect this.

**Comment by ghost** [comment]
looks solved:

![Screen Shot 2020-09-25 at 13 03 10](https://user-images.githubusercontent.com/70466955/94259910-8e0d3f00-ff2f-11ea-84f6-f1c672f2cffe.png)
![Screen Shot 2020-09-25 at 13 04 40](https://user-images.githubusercontent.com/70466955/94260051-c57beb80-ff2f-11ea-8d92-42987e44f947.png)

**Comment by Bakual** [comment]
Yep, this has been solved with https://github.com/joomla/joomla-cms/pull/30729

**Comment by alikon** [comment]
ok let's close it then
