### ISSUE TITLE
[4.0] Post-installation messages fubar

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26109]
~Multiple issues~

~1. on install there are 5 messages in the database but the counter only says 3 and the component only displays 3~

~2. neither the link in the status bar use the eid for joomla~

~3. In the database change the eid for one of the messages that is displayed to that of an extension you have installed. you will now see that extension listed in the select box but if you select that extension the message is not displayed or the newsfeed removed. the content doesnt change at all but the url changes from /index.php?option=com_postinstall to index.php~

The remaining issue is with sites that have been updated. When you click reset messages you will get all the messages from 3.x which is absolutely fine except that we have language strings missing. (Ignoring the newer messages which I assume have not been merged into j4 yet).

Of these messages I guess we can put the strings back into j4 (or modified versions of them) as they are still important information for users who have upgraded. 

The only one that this doesnt apply to is the pre-update check. Should we just delete this record on update?
![image](https://user-images.githubusercontent.com/1296369/96362715-2cec1c00-1127-11eb-846f-94d0531f364b.png)

**Comment by Quy** [comment]
Do we really need the dropdown items? Entries are not added frequently that require it on each page load. Personally, it will be one of the modules to disable.

**Comment by coolcat-creations** [comment]
> Do we really need the dropdown items? Entries are not added frequently that require it on each page load. Personally, it will be one of the modules to disable.

+1

**Comment by SharkyKZ** [comment]
>on install there are 5 messages in the database but the counter only says 3 and the component only displays 3

This seems intentional. Postinstall scripts have some code for hiding the messages when not needed. E.g. HTTP Headers message is not shown when the plugin is enabled.

**Comment by chmst** [comment]
Please test #29702

**Comment by ghost** [comment]
looks solved: ![image](https://user-images.githubusercontent.com/70466955/94259253-78e3e080-ff2e-11ea-9875-a1c8cb489e7f.png)

**Comment by brianteeman** [comment]
Nope all the reported issues are still present

**Comment by bembelimen** [comment]
> Multiple issues
> 
>     1. on install there are 5 messages in the database but the counter only says 3 and the component only displays 3

So I went through all of the messages and checked the condition:
id 1 is displayed if NO tfa is activated
id 2 is displayed all the time
id 3 is displayed all the time (there is a condition check, which always returns true)
id 4 is displayed if the update check plugin is activated + the caching time in the installer options is set to 0
id 5 is displayed if the httpheaders plugin is not enabled

>
> 2. neither the link in the status bar use the eid for joomla
>
> 3. In the database change the eid for one of the messages that is displayed to that of an extension you have installed. you will now see that extension listed in the select box but if you select that extension the message is not displayed or the newsfeed removed. the content doesnt change at all but the url changes from /index.php?option=com_postinstall to index.php

The ```eid``` is used for filtering the list. So you *could* set a model state to get post install messages from other extensions (fallback is the joomla core extension (files_joomla)). But the populatestate method is missing I guess, which pushs the request parameter to the model.

**Comment by brianteeman** [comment]
@bembelimen thanks for the check and for the PR. The only issue now is with upgrades from 3.x - I will update the original post with more details

**Comment by alikon** [comment]
for me the better thing to do is to  simply delete that messages on update to 4

**Comment by chmst** [comment]
With PR #31838 all issues should be resolved, so I am closing this.
