### ISSUE TITLE
[4.0] Language plurals

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26100]
If someone could point me in the right direction in the code where strings like this one are constructed I would be most grateful

COM_WORKFLOW_N_ITEMS_UNPUBLISHED

**Comment by HLeithner** [comment]
https://github.com/joomla/joomla-cms/blob/78ea041de2a936a6fbf7062ca11b4389c4d9a646/libraries/src/MVC/Controller/AdminController.php#L218-L245

**Comment by brianteeman** [comment]
Thanks
