### ISSUE TITLE
Mail link to a friend with cache enabled doesnt work

### ISSUE THREAD

**Issue by Pablo234** [joomla/joomla-cms#26117]
### Steps to reproduce the issue

Enable mail link to friend in articles
Enable global cache on Joomla (conservative for example)

### Expected result

Mail is sent

### Actual result

Error sending

### System information (as much as possible)

Joomla 3.9.11

### Additional comments

Joomla runs a script to generate a hash for that article, and then associates that hash with the URL of the article. The link for “emailing the article to a friend” will contain that hash, and so, when you fill in the popup form and click on Submit, Joomla will check that hash, and will get the article’s URL based on the hash, and then will email the link of the article to your friend.

If you use cache, the hash in invalid for all users.

**Comment by ghost** [comment]
@alikon can you please comment?

**Comment by SharkyKZ** [comment]
Pinging @zero-24 @HLeithner @SniperSister as this concerns a security feature.

**Comment by zero-24** [comment]
No that I'm happy with it but this should do the trick: https://github.com/joomla/joomla-cms/compare/staging...zero-24:cachable?expand=1

**Comment by SharkyKZ** [comment]
That doesn't work in category/featured view and doesn't account for menu item settings.

**Comment by brianteeman** [comment]
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed. 

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
