### ISSUE TITLE
[4.0] Backend System Menu missing

### ISSUE THREAD

**Issue by B3nito** [joomla/joomla-cms#26121]
### What needs to be fixed
when in system menu and for example install new language then menu left is missing so I have to go to system and search for language.

### Why this should be fixed
Because when setting up website is has to be fast: click click ready - current state is very bad for developer and site builder

### How would you fix it
add left menu für System settings.

**Comment by brianteeman** [comment]
I believe that the theory was that as this is something you will likely do only at setup and not during the lifetime of the site it is just clutter that is not needed

**Comment by brianteeman** [comment]
I believe that the theory was that as this is something you will likely do only at setup and not during the lifetime of the site it is just clutter that is not needed

**Comment by B3nito** [comment]
I setup 3 new sites every week I will go crazy to have this hard navigation. I know I can make admin preset but I will need to do on every site. It will be very hard. every menu has subitems but this not. why? it is not hurting anyone.

**Comment by infograf768** [comment]
@B3nito

This is why I am working at the alternate menu.
See https://github.com/joomla/joomla-cms/pull/26115

That one is fast to set.

Also, if a specific admin menu item is very important for you, just create a new admin menu without preset and then add the menu items you need often there.
I do that here for Languages.

**Comment by Quy** [comment]
Duplicate #26409<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26121">issues.joomla.org/tracker/joomla-cms/26121</a>.</sub>
