### ISSUE TITLE
[4.0] Remove comments re IE11 from core code

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#26123]
### Is your feature request related to a problem? Please describe.
Viewing the blog source code on Firefox inspector, I was surprised to see the following comment:

![image](https://user-images.githubusercontent.com/36987494/64080212-8d34ba00-cce9-11e9-98ee-2292fe7462d9.png)

I thought all support for IE has been dropped in J4. In this case, the comment - and the double div? - should be removed. ~~I've tried searching the repo code for 'blog' but there are very few files and I can't find where this comment is located. ~~

Edit: it is line 79 of [https://github.com/joomla/joomla-cms/blob/4.0-dev/components/com_content/tmpl/category/blog.php](url)

### Describe the solution you'd like
No reference to IE11 and any IE11-related code removed if not necessary for other browsers

**Comment by ghost** [comment]
Closed as having Pull Request #26160
