### ISSUE TITLE
[4.0] Break down prepared array values to their meaning in debug query view

### ISSUE THREAD

**Issue by eXsiLe95** [joomla/joomla-cms#26135]
When debugging Joomla!, you may need to execute a sql statement manually. You can copy the pre-build statement from the console, however, in com_content, many prepared array values are used which can not be associated with their meaning.

### Steps to reproduce the issue

* Go to System > Global configuration > System 
* Activate Debug System, Save & Close
* Go to Articles
* Open up the Console by clicking the Joomla! Logo on the bottom left corner (if not already opened)
* Go to Queries

### Expected result

`:preparedArray<n>` has some meaningfull name so that you can reproduce the sql statement by hand

### Actual result

![PreparedArray](https://user-images.githubusercontent.com/31202904/64118832-c2e4ac00-cd98-11e9-9404-290271d49601.png "Prepared Array Statements")

### System information (as much as possible)

* Fresh Joomla! 4.0-dev Installation from Git (Commit 6e3c348b6f2401d35fa179ffeae540dd1fd8edf6)
* PHP 7.2.19-0ubuntu0.19.04.2
* MySQL 5.7.27-0ubuntu0.19.04.1
* Apache/2.4.38 (Ubuntu)
* Brave Browser Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)

**Comment by wilsonge** [comment]
I don't consider this a beta blocker but definitely a "nice to fix" before we go live with 4.0

**Comment by Quy** [comment]
Please test PR #30717
