### ISSUE TITLE
[4.0] Selected language in Backend Login has no effect

### ISSUE THREAD

**Issue by bees4ever** [joomla/joomla-cms#26148]
### Steps to reproduce the issue
Install a second language, i.e. "German"
Log out from the backend and open the backend login mask
Select another langauge as the default one,  i.e. "German"
The backend is still translated in the default language and the menu setting has no effect

### Expected result
If I selected a langauge in the login mask, this language should be the backend language for this login. 

### Actual result
Change of language has no effect.

### System information (as much as possible)
Mac OS X 10.14.1
Joomla 4.0-dev at 6fd50ce11fce63f6029974a41fc02a6250bae25c

### Additional comments
I mean this login mask: 
![screen shot 2019-09-03 at 06 57 36](https://issues.joomla.org/uploads/1/0688792218a13ee8c100c3480d0367b5.png)

**Comment by ghost** [comment]
Same behaviour as in J3.

**Comment by SharkyKZ** [comment]
Issue confirmed. This is to do with AJAX login of the new template.

**Comment by infograf768** [comment]
Set as Release blocker

**Comment by bees4ever** [comment]
I will now working on it, I have here also @roland-d, so we just solved it, hopefully...

**Comment by ghost** [comment]
Closed as having Pull Request #26150
