### ISSUE TITLE
[4.0] com_installer warnings memory limit wrong

### ISSUE THREAD

**Issue by HRIT-Florian** [joomla/joomla-cms#26151]
### Steps to reproduce the issue

just got to backend index.php?option=com_installer&view=warnings
In our case the limit was set to 285 and 3200 for testing

### Expected result

There should be no memory limit warning .

### Actual result

Memory limit warning

![grafik](https://user-images.githubusercontent.com/12803406/64171415-e66c2d00-ce52-11e9-9377-7518099d88ad.png)

### System information (as much as possible)

PHP-Version | 7.3.2
Joomla! 4.0.0-alpha11 Alpha [ Amani ] 17-August-2019 12:58 GMT

**Comment by alikon** [comment]
please test #26488<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26151">issues.joomla.org/tracker/joomla-cms/26151</a>.</sub>
