### ISSUE TITLE
[4.0] Download key manager - language files

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26166]
When the changes to merge two views were made the extra language strings were not removed so now we have multiple unused strings that have been added to the cms

**Comment by brianteeman** [comment]
looks like checkin doesnt work either - no message and no checkin performed

**Comment by brianteeman** [comment]
@roland-d can you check this please - you know this code the best

**Comment by roland-d** [comment]
@brianteeman Yes, I will check it. You don't see the lock icon when you check-in an item? Assuming you have the checked_out and checked_out_time fields in the database.

**Comment by roland-d** [comment]
@brianteeman I see now what you mean with the check-in. I was thinking of something else. Will look into that as well.

**Comment by roland-d** [comment]
Closing as we have a PR
