### ISSUE TITLE
[4.0] Download Key manager SQL errors

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26164]
@roland-d @wilsonge 

Since the merge of PR #25553 when you do a clean install you will find that the database is reporting as out of date.

The problem is that there is a mismatch between the install sql and the update sql. The update sql file is for the #__update_sites table but the install sql is for the #__updates table

https://github.com/joomla/joomla-cms/blob/501dfad2de50584107ffbfd0448867ee45617c39/administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-08-03.sql#L1-L2

https://github.com/joomla/joomla-cms/blob/501dfad2de50584107ffbfd0448867ee45617c39/installation/sql/mysql/joomla.sql#L1936-L1937

**Comment by roland-d** [comment]
@brianteeman Thank you for reporting this. I will submit a PR to fix this.

**Comment by brianteeman** [comment]
@roland-d I was going to but then I wasnt sure which was correct ;)

**Comment by roland-d** [comment]
@brianteeman Feel free to post it, I can test it :)

The correct one is the `#__update_sites` because we moved the keys there. These columns are then used to be able to "lock" the rows.

**Comment by brianteeman** [comment]
ok - incoming
