### ISSUE TITLE
[4.0] Developer roadmap is out of date

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#26162]
### Is your feature request related to a problem? Please describe.
I'm not sure this is the right place to report this, but this page - [https://developer.joomla.org/roadmap.html#4](url) - is still showing Alpha 10 as the latest release when it should be Alpha 11.

**Comment by brianteeman** [comment]
I also tried via twitter the other week

**Comment by ghost** [comment]
Link is https://developer.joomla.org/roadmap.html#4

**Comment by brianteeman** [comment]
@franz-wohlkoenig we know the link. That's why we know it is out of date

**Comment by ghost** [comment]
click the Link in opening comment send to https://github.com/joomla/joomla-cms/issues/url.

**Comment by Scrabble96** [comment]
> 
> 
> click the Link in opening comment send to https://github.com/joomla/joomla-cms/issues/url.

I don't quite understand what you mean by sending the first link (URL) to this URL.

**Comment by ghost** [comment]
click on the link:

![Bildschirmfoto 2019-09-04 um 13 27 16](https://user-images.githubusercontent.com/8235763/64251013-cb172580-cf17-11e9-9724-a3e4ad94f705.png)

**Comment by wilsonge** [comment]
Updated the page. Thanks. 

> I also tried via twitter the other week

Twitter is not an issue tracker as you know - and given i was on holiday the chances of it being picked up were low....
