### ISSUE TITLE
[4.0] metismenu updates breaks menu

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26170]
Locally I updated the version of metismenujs being used from 1.0.3 to 1.1.0 and it broke the menu. No expanding menus will open and there are no js console errors

Looks like the changes [here ](https://github.com/onokumus/metismenujs/commit/beb950340b6c861aed8d98098beab3b6a4a4a250#diff-3b2ad9d6421a5163198820567753406fL11)are responsible - namely the changes as a consequence of removing
`var constant = require('./constant.js');`

**Comment by wilsonge** [comment]
Had a chat with Brian about this - looks like he missed https://github.com/onokumus/metismenujs#migrating-to-v103-from-v110 so we're going to try the class name change (in js/scss)

**Comment by brianteeman** [comment]
closed see #26275
