### ISSUE TITLE
[4.0] Selecting folders when creating New file in template customise

### ISSUE THREAD

**Issue by riishede** [joomla/joomla-cms#26172]
### Steps to reproduce the issue
When selecting 'New file' in Templates: Customise (Cassiopeia) it does not select correct if I only click on the folder-icon. Clicking the folder-icons just adds on when further more icons are clicked on.

### Expected result
The whole line – folder-icon and text should be selected with af colored selection.

### Actual result
When only clicking the folder-icon it does not select the colder, and the new file are placed at the template root.

### System information (as much as possible)
php: Linux server10.hosting4real.net 3.10.0-962.3.2.lve1.5.25.8.el7.x86_64 #1 SMP Wed May 15 09:51:12 EDT 2019 x86_64
dbserver: mysql
dbversion: 10.2.26-MariaDB
dbcollation: latin1_swedish_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 7.3.8
server: LiteSpeed
sapi_name: litespeed
version: Joomla! 4.0.0-alpha12-dev Development [ Amani ] 19-August-2019 13:40 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0

### Additional comments
I hope this issue are corect submitted :)

**Comment by ghost** [comment]
Issue confirmed.

**Comment by infograf768** [comment]
Confirmed here too when uploading a file.
Works fine when creating a new file.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/issues/27742.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26172">issues.joomla.org/tracker/joomla-cms/26172</a>.</sub>
