### ISSUE TITLE
[4.0] Cassiopeia sub-menu items do not hide when module 'sub-menu items' is 'Hide'

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#26173]
### Steps to reproduce the issue
Create a new front-end menu item and assign it to a parent item
Open the menu module and select 'Hide'

![image](https://user-images.githubusercontent.com/36987494/64333774-3243e100-cfcf-11e9-9559-9c97809559d7.png)

Save the module
View front end in browser and refresh the window

### Expected result
No sub-menu

### Actual result
Sub-menu displayed:

![image](https://user-images.githubusercontent.com/36987494/64333805-4851a180-cfcf-11e9-903a-52e7ea2d78da.png)

### System information (as much as possible)
J4Alpha11 full package

**Comment by ghost** [comment]
Issue confirmed.

**Comment by Scrabble96** [comment]
Additional info:

If there are two main menu items, each with a child sub-menu item, then the sub-menu item displays for the page you are actually viewing, but not the other. I have now added a sub-menu item to the Home page (yes, this is now possible!):

![image](https://user-images.githubusercontent.com/36987494/64334808-4be62800-cfd1-11e9-8666-b7f2cc037a9c.png)

If I switch to the Blog page, the view is the same as the first Mainmenu image above and the 'Home sub-menu' item disappears and the blog sub-menu reappears.

**Comment by Scrabble96** [comment]
Further comment: I noticed today that there is a class `mod-list` which is applied in the mod_menu but is undefined in the template css so it currently serves no purpose:

[https://github.com/joomla/joomla-cms/blob/e10150012c5fa32f9a04d9fb4e9ba6483a56918f/modules/mod_menu/tmpl/default.php#L26](url)
`<ul<?php echo $id; ?> class="mod-menu nav<?php echo $class_sfx; ?> mod-list">`
This file is, apart from the top few lines referencing the ModuleHelper and HTMLHelper is virtually identical to the same file in J3.10 Dev.

In J3.9 it's different, but still has the class `mod-list` and that isn't defined, either!

**Comment by Scrabble96** [comment]
Three further observations, if anyone is interested:

1. With 'sub-menu items' set to 'Hide' it is not possible to view the child items of other parent items without first clicking/tapping on the parent item. Not good for SEO and rather tedious if there are  several parents each with several child levels you need to click/tap through before finding the right place.

If 'sub-menu items' is set to 'Show' then you would see every item under every parent displayed, which could be a very long list.

What is needed is a drop-down system like the Admin menu, which I see is a plugin and not Joomla core code. 

2. the 'mod_menu/menu.min.js' file referenced in the menu's default.php seems to have no effect on the menu's display. Removing this line:
https://github.com/joomla/joomla-cms/blob/dcb689d14f62d6e504f17666ecfda14d6a62935a/modules/mod_menu/tmpl/default.php#L15

has no apparent effect.

3. As mentioned in a closed issue https://github.com/joomla/joomla-cms/issues/21134#issuecomment-405965488 the menu (for desktop/large tablet view) should really be horizontal. Therefore, the css 
`.mod-menu {
  flex-direction: column; }`

should really be
`.mod-menu {
  flex-direction: row; }`

It was commented that it would be too hard work to change the core to accommodate a switch between horizontal and vertical, but there's already a switch between 'Show' and 'Hide' child items (even though it doesn't really work) referenced in the menu helper file:

[https://github.com/joomla/joomla-cms/blob/4.0-dev/modules/mod_menu/Helper/MenuHelper.php](url)

So I don't see any reason why new switch field could be added for horizontal/vertical choice and the mod_menu/default.php adjusted from this:

https://github.com/joomla/joomla-cms/blob/dcb689d14f62d6e504f17666ecfda14d6a62935a/modules/mod_menu/tmpl/default.php#L26

to something like this:
`if ($newSwitchField==>'horizontal')
	{<ul<?php echo $id; ?> class="mod-menu-horizontal nav<?php echo $class_sfx; ?> mod-list">}
else	{<ul<?php echo $id; ?> class="mod-menu-vertical nav<?php echo $class_sfx; ?> mod-list">}`

with mod-menu replaced with the two classes above.

**Comment by ghost** [comment]
need label "J4 Frontend Template"

**Comment by drmenzelit** [comment]
@Scrabble96 is this issue still present after the improvements done in Cassiopeia?

**Comment by Scrabble96** [comment]
No, it isn't, so I'll close this issue as being fixed.

**Comment by drmenzelit** [comment]
Thanks
