### ISSUE TITLE
[4.0] Pre-Update checker missing extensions

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26177]
The backend template team removed the entire code for checking extension compatibility in the pre-update checker with this PR https://github.com/joomla/backend-template/pull/403 by @chmst 

I can't find any explanation or comment about this. 

If it was on purpose then it was incomplete as language files and notices referring to it are still present. If confirmed I can com[lete the removal

If it was an error caused due to lack of testing and blind merging then I can put it back while I am updating it for accessibility etc

@wilsonge @bembelimen Please advise

**Comment by brianteeman** [comment]
Assuming it was a mistake I put it back with #26178 

Please leave open until it is confirmed

**Comment by bembelimen** [comment]
Thx for the finding. Seems that it slipped through independently of having a PR and a enforced review.

**Comment by brianteeman** [comment]
so you can confirm it was an error and my pr to put it back is correct?

**Comment by wilsonge** [comment]
it was an error. pr to put it back is correct

**Comment by brianteeman** [comment]
thanks
