### ISSUE TITLE
[4.0] Update sites enabled messages

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26189]
Looking at these horrible language strings with their punctuation
https://github.com/joomla/joomla-cms/blob/46c892c7f9c3eb0ca2879d10ee7abd7d073b35e6/administrator/language/en-GB/en-GB.com_installer.ini#L28-L29

They are referenced in the model here
https://github.com/joomla/joomla-cms/blob/46c892c7f9c3eb0ca2879d10ee7abd7d073b35e6/administrator/components/com_installer/Model/UpdateModel.php#L316

But I dont see this code being used anywhere  in the update view

Instead the sites are enabled/disabled in the updatesite view with this code in the controller although the comment refers to extensions not sites
https://github.com/joomla/joomla-cms/blob/211576add632a923ad4ba9b7326014126a4ae2d4/administrator/components/com_installer/Controller/UpdatesitesController.php#L61

Is this code duplication? Is the comment wrong

@roland-d any ideas?

**Comment by roland-d** [comment]
@brianteeman According to Github you last changed the language strings as part of PR #5615 😆 

Agree, as far as I can tell this code isn't used anymore and can be removed. As you pointed out, this is now handled by the `publish()` function.

Will you make the PR or should I?

**Comment by brianteeman** [comment]
can you make the pr to make sure I dont miss any of the unused code

**Comment by roland-d** [comment]
Closing as we have PR #26193
