### ISSUE TITLE
[4.0] Drop custom progress bar for <meter> / <progress> element

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#26190]
Seeing as support for IE11 has been dropped, I suppose you can start utilising more native elements:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meter

**Comment by richard67** [comment]
Why not use <progress>? See the "See also" note at the bottom of the linked Mozilla docs page.

It seems it is supported on a wider range of browsers, including Android web view, which does not support the <meter> elemen, according to the Mozilla doc.

**Comment by brianteeman** [comment]
It should be progress not meter

**Comment by richard67** [comment]
Yes, that was what I meant with my previous comment. The tag had been stripped off from my comment because I had forgotten to quote it.

**Comment by C-Lodder** [comment]
@brianteeman I'd say use both. Certain elements in Joomla such as the Pasword Strength I'd say should be `<meter>` as the `<progress>` is there to show the level of completion

**Comment by brianteeman** [comment]
well the password strength needs completely rewriting (see my RFC) as its not a strength meter at all but yes in general you would be correct. Pull Requests welcome ;)

**Comment by C-Lodder** [comment]
PR: #29041
