### ISSUE TITLE
[4.0] Filters button etc when there are no filters

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26199]
### Steps to reproduce the issue

administrator/index.php?option=com_installer&view=languages

### Expected result
![image](https://user-images.githubusercontent.com/1296369/64474707-4a9f3180-d170-11e9-8986-1d9b7f48d9e4.png)

### Actual result
![image](https://user-images.githubusercontent.com/1296369/64474714-5db20180-d170-11e9-8e89-2bdb63012c72.png)

### Additional comments
I am assuming its a logic error somewhere in the layout `layouts\joomla\searchtools\default.php`

**Comment by brianteeman** [comment]
The same is true for the following urls
administrator/index.php?option=com_templates&view=templates
administrator/index.php?option=com_users&view=levels
administrator/index.php?option=com_users&view=groups
administrator/index.php?option=com_finder&view=searches
administrator/index.php?option=com_menus&view=menus
administrator/index.php?option=com_actionlogs&view=actionlogs
administrator/index.php?option=com_checkin
administrator/index.php?option=com_cache

**Comment by brianteeman** [comment]
@franz-wohlkoenig its not a template issue

**Comment by schnuti** [comment]
Be aware that you probably have to edit the Javascript if the filter button and with it the filter container is removed.
Alternative: remove the clear button as well. The search field can be cleared manually.

**Comment by infograf768** [comment]
See proposal for PR here:
https://github.com/joomla/joomla-cms/issues/26529#issuecomment-539947105

**Comment by infograf768** [comment]
My patch gives for all cases

<img width="1285" alt="Screen Shot 2019-10-09 at 12 49 03" src="https://user-images.githubusercontent.com/869724/66475282-42018a00-ea93-11e9-85b0-b6fd3f59159f.png">

**Comment by infograf768** [comment]
closing as we have a patch
https://github.com/joomla/joomla-cms/pull/26530
