### ISSUE TITLE
[4.0] Why is Cassiopeia CSS written for desktop then scaled down for small screens?

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#26191]
### Is your feature request related to a problem? Please describe.

Bootstrap 4 has been redesigned 'mobile-first' to cater for small screens first and foremost with larger screens second as the greater majority of website users are now using mobile devices rather than desktops/laptops.

Joomla 4 code seems to be working the other way, being designed for large screens and then CSS added for smaller screens e.g. `@media (max-width: 767.98px)`. Is this the right way to go?

I know it's easier to do the development work on a large screen, but all you need is another browser window open to change screen widths and you can see how it works at all sizes.

### Describe the solution you'd like
Build Joomla 4 CSS from small screens up.

**Comment by ciar4n** [comment]
> the greater majority of website users are now using mobile devices rather than desktops/laptops.

True for the web in general. I suspect the joomla admin however is still predominantly viewed on desktop.

**Comment by Scrabble96** [comment]
Sorry. I should have clarified that my point was about the front end, not the admin. The CSS for Cassiopeia is designed for desktop first and mobile second. It should be mobile first, as the vast majority of website visits are now on mobile devices, even among oldies like me. I've changed the title.

**Comment by Scrabble96** [comment]
Could the "J4 Backend Template" tag be amended to "J4 Issue" as it's to do with the front end?

**Comment by ciar4n** [comment]
Is this template been replaced with... https://community.joomla.org/gsoc-2019/gsoc-project-page-builder-third-coding-phase.html ?

If not then I'll switch the css to 'mobile first.

**Comment by ghost** [comment]
@ciar4n please see https://github.com/joomla/joomla-cms/issues/26201#issuecomment-529135371 (even this is no answer on your question)

**Comment by ciar4n** [comment]
Pinging @wilsonge @HLeithner @bembelimen

**Comment by bembelimen** [comment]
> Is this template been replaced with... https://community.joomla.org/gsoc-2019/gsoc-project-page-builder-third-coding-phase.html ?

When, then only somewhere in the future, the Page Builder needs some more love first, nothing for J! 4.

**Comment by HLeithner** [comment]
@ciar4n as benjamin wrote, there is no decision made yet when and how the page builder will be included into Joomla!

So I think changing the CSS to mobile first would be a good move. thx

**Comment by Scrabble96** [comment]
> ... then I'll switch the css to 'mobile first.

@ciar4n Will this be a manual job? If so, can you remove redundant IE fixes as you find them? For example, there is an IE fix for the Fontawesome fonts `(src: url("../../../media/vendor/fontawesome-free/webfonts/fa-solid-900.eot?#iefix"),` etc, although I'm d*****d if I can find the original file where the instruction comes from. Thanks.

If not, I'll raise an issue as I find them.

**Comment by Scrabble96** [comment]
Also, briefly mentioned elsewhere, but I've just found the code - why on very small screens do top-a and top-b modules drop below the component area, (and, for that matter, side-l, too)? It seems illogical. Surely top-a and top-b - and possibly side-l - should remain at the top?

https://github.com/joomla/joomla-cms/blob/2aac8311863ae224f77630472e1c72d790ba720f/templates/cassiopeia/scss/blocks/_css-grid.scss#L49-L62

I would

**Comment by ciar4n** [comment]
@HLeithner @bembelimen Thank you

@Scrabble96  Please create separate issues for these concerns.

**Comment by ciar4n** [comment]
PR created... #26237

**Comment by ghost** [comment]
Closed as having Pull Request #26237
