### ISSUE TITLE
Using cmd + save in Tiny MCE on a Mac redirects to article manager without saving

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#26197]
### Steps to reproduce the issue
Open a Joomla Article on a mac. 
Click into the editor field of Tiny MCE and change some text.
Use the Keyboard Shortcut cmd + S.

### Expected result
1) The browser would want to save the page as a document
or 
2) The text is saved (which would be great)

### Actual result
Redirects to article Manager without checking in and without saving.

### System information (as much as possible)
Mac Os, Firefox Developer Edition latest Version, Joomla 3.9.11

**Comment by brianteeman** [comment]
If my memory is correct we have an open issue for this already

**Comment by ghost** [comment]
found only closed (#16600, #16550)

**Comment by brianteeman** [comment]
so please reopen #16550 as there is useful information there for fixing this

**Comment by ghost** [comment]
closed in favor of #16550
