### ISSUE TITLE
[4.0] Cassiopeia breadcrumbs should be above component area

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#26195]
### What needs to be fixed
The Cassiopeia breadcrumbs module position

### Why this should be fixed
At the moment, it is below the component area (see index.php lines 151-157):
`	<div class="grid-child container-component">
		<jdoc:include type="modules" name="main-top" style="cardGrey" />
		<jdoc:include type="message" />
		<jdoc:include type="component" />
		<jdoc:include type="modules" name="breadcrumbs" style="none" />
		<jdoc:include type="modules" name="main-bottom" style="cardGrey" />
	</div>`

And it looks like this:

![current-position](https://user-images.githubusercontent.com/36987494/64447758-03636300-d0d4-11e9-92f6-759d17c12587.jpg)

### How would you fix it
Change the order in that section of index.php to this:
`	<div class="grid-child container-component">
	         <jdoc:include type="modules" name="breadcrumbs" style="none" />
      	         <jdoc:include type="modules" name="main-top" style="cardGrey" />
                 <jdoc:include type="message" />
	         <jdoc:include type="component" />
		<jdoc:include type="modules" name="main-bottom" style="cardGrey" />
	</div>`

So it looks like this:

![proposed-position](https://user-images.githubusercontent.com/36987494/64448119-da8f9d80-d0d4-11e9-8e6a-2f4efe61072f.jpg)

### Side Effects expected
None. (The misalignment at the top of the component and sidebar was already there).

**Comment by brianteeman** [comment]
I agree with you. For some reason I never understood the breadcrumbs is at the bottom in protostar

**Comment by ghost** [comment]
Closed as having Pull Request #26204
