### ISSUE TITLE
[4.0] Cassiopeia sidebars and component area not horizontally aligned

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#26201]
### What needs to be fixed
There is a 15px margin at the top of the first element in the component area. If there are left sidebar modules (whether there are right sidebars or not), then it is added to the top of the sidebar-left-container using the class `.sidebar-left-container`:

![component-and-sidebar-left](https://user-images.githubusercontent.com/36987494/64477350-73382300-d192-11e9-9dae-b3d71c9733a3.jpg)

![component-and-both-sidebars](https://user-images.githubusercontent.com/36987494/64477353-78956d80-d192-11e9-8d26-7d07cc35fd3c.jpg)

If there is no sidebar-left module, but a sidebar-right module, the margin is added to the top of component area with the class `container-component`:

![component-and-sidebar-right](https://user-images.githubusercontent.com/36987494/64477388-e80b5d00-d192-11e9-8b67-fec67f4c32e0.jpg)

### Why this should be fixed
It would be tidy

### How would you fix it
Inspecting the code in Firefox shows that this code is the culprit:

`.site-grid .container-header + div:not(.container-banner) {
    margin-top: 15px;
}`

Changing the margin to 0 does the trick:

![component-sidebar-adjusted](https://user-images.githubusercontent.com/36987494/64477490-fdcd5200-d193-11e9-88ee-f8764b9beab4.jpg)

I think this code is in (templates/cassiopeia/scss/blocks/_css-grid.scss) lines 64 to 71:

![image](https://user-images.githubusercontent.com/36987494/64477444-85669100-d193-11e9-9031-f179a5f8b89b.png)
(sorry - that is an image. I don't know how to 'quote' from a file other than using the code tags in the editor.)

If that is the correct code, would it affect anything else if it was removed?

**Comment by ghost** [comment]
At https://community.joomla.org/gsoc-2019/gsoc-project-page-builder-third-coding-phase.html i read about:

![Bildschirmfoto 2019-09-07 um 18 55 14](https://user-images.githubusercontent.com/8235763/64477916-358ec680-d1a1-11e9-8ddb-adce786abd06.png)

Maybe J4 comes with 2 Frontend-Templates?

**Comment by mbabker** [comment]
> Maybe J4 comes with 2 Frontend-Templates?

Oh please no.  Has nobody learned over the last 10 years why shipping two templates for either application is a bad idea?

**Comment by astridx** [comment]
@Scrabble96 Here is an explanation how to insert a link to code: https://github.blog/2017-08-15-introducing-embedded-code-snippets/

**Comment by ghost** [comment]
Closed as having Pull Request #26210

**Comment by Scrabble96** [comment]
> 
> 
> @Scrabble96 Here is an explanation how to insert a link to code: https://github.blog/2017-08-15-introducing-embedded-code-snippets/

Many thanks, @astridx

**Comment by N6REJ** [comment]
@Scrabble96 I had the same problem using the "code" button in git.  The solution is to use ``` preceding your code.  If you follow that by the language used ( php css, etc ) its supposed to style it for you also.
 Then paste in your text.
