### ISSUE TITLE
JViewLegacy in JControllerLegacy

### ISSUE THREAD

**Issue by xortrike** [joomla/joomla-cms#26218]
### Steps to reproduce the issue
In component controller.
```
class ExampleController extends JControllerLegacy {
    public function display($cachable = false, $urlparams = array()) {
        $this->getView();
}
```

### Expected result
Class \JViewLegacy

### Actual result
Redirect to dashboard.

### System information (as much as possible)
Method creating view. /libraries/src/MVC/Controller/BaseController.php:821
Argument $type is optional, but if not transfer to method - will result in an error.

### Additional comments
I testing on Joomla 3.9.11

**Comment by ghost** [comment]
@alikon can you please comment?

**Comment by SharkyKZ** [comment]
>Argument $type is optional, but if not transfer to method - will result in an error.

That's not entirely true. If type is not set the controller looks for `view.php` file.

**Comment by alikon** [comment]
@SharkyKZ  can we close this as expected behaviour or ?

**Comment by SharkyKZ** [comment]
I'm not sure if that answered @xortrike's question. Awaiting response.

**Comment by alikon** [comment]
since no response i'm closing
it can always be re-opened if needed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26218">issues.joomla.org/tracker/joomla-cms/26218</a>.</sub>
