### ISSUE TITLE
[4.0] Cassiopeia header-shadow hiding banner position

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#26228]
### Steps to reproduce the issue
1: create a custom module with some content and assign it to banner position, or
2: create a banner component and banner module and assign it to the banner position

### Expected result
Completely visible banner module

### Actual result

1.  Custom modules assigned to the banner position are overlayed with a grey shadow and also the wavy cut-out:

![1-custom-banner-added-shadow](https://user-images.githubusercontent.com/36987494/64526249-b3b2b080-d2fa-11e9-90e5-ac790b8b47e4.jpg)

with the shadow removed (using FF inspector) it looks like this:

![2-custom-banner-header-shadow-removed](https://user-images.githubusercontent.com/36987494/64526892-65061600-d2fc-11e9-83c8-a33a4510f1b3.jpg)

And with `.header-shape-bottom` removed it looks like this:
![3-custom-banner-no-shadow-no-shape](https://user-images.githubusercontent.com/36987494/64526983-ac8ca200-d2fc-11e9-83d9-a245899dabc7.jpg)

Which is probably how it should look.

2. A banner component in a banner module does not display at all. All you see is the header shadow, no banner content and a large 3em margin:

![4-banner-component](https://user-images.githubusercontent.com/36987494/64527701-849e3e00-d2fe-11e9-9f04-b6a50d6a284a.jpg)

Although there are two classes added, i.e. `<div class="mod-banners bannergroup">` those classes are empty as they do not exist in the css.

What purpose does the `.header-shadow` serve? It is only applied to the container-banner. Why would you want to cover up a banner with a shadow? The code is here:

https://github.com/joomla/joomla-cms/blob/27e4d2891c75abfab8c9835551b977f78ff41928/templates/cassiopeia/scss/blocks/_header.scss#L164-L180

As well as the shadow and the wavy line, there must be several other pieces of code that are interfering with the display of banners as seems also to have a height of 0 which is coming from somewhere.

### System information (as much as possible)
Alpha12Dev nightly update 09.09.19

**Comment by mbabker** [comment]
It sounds like that spot is meant to be a hero image type deal, not an advertisement banner as you would get with the banners component.

**Comment by Scrabble96** [comment]
> 
> 
>...not an advertisement banner as you would get with the banners component.

So there are, in fact, two issues here:

1. Anything placed in the banner module position is overlayed by an unnecessary semi-transparent grey div and also the curvy Cassiopeia cut-out.
2. A banner component placed in another position, e.g. top-a, still does not show anything. Could it be that there is a chrome missing?

**Comment by Scrabble96** [comment]
and 
3. If the banner module position is just a 'hero' position, then it should be called something else - 'Promo', for instance - so as not to confuse anyone wanting to use the banner component.

**Comment by Quy** [comment]
Please test PR #27566

**Comment by alikon** [comment]
closing as we have a pr<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26228">issues.joomla.org/tracker/joomla-cms/26228</a>.</sub>
