### ISSUE TITLE
[4.0] Error deleting category

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26226]
### Steps to reproduce the issue
Delete a content category

### Expected result
Category trashed with no error

### Actual result
Category trashed with error

`Argument 2 passed to Joomla\Component\Finder\Administrator\Indexer\Result::addNestedTaxonomy() must implement interface Joomla\CMS\Tree\ImmutableNodeInterface, null given, called in C:\htdocs\joomla-cms\plugins\finder\content\content.php on line 322`

**Comment by SharkyKZ** [comment]
Duplicate #26114.
