### ISSUE TITLE
[4.0] More control over Smart Search (Finder) indexation

### ISSUE THREAD

**Issue by jjnxpct** [joomla/joomla-cms#26233]
### Is your feature request related to a problem? Please describe.
In the search results we see results that match on 'author' (content plugin) and also (I believe) on the menu item slug /item URL. 

### Describe the solution you'd like
It would be great if we could have some settings in the content plugin (or component) to exclude matching on author name or article slug / URL.

### Additional context
On most of our sites the frontend users do not see the author of an article. But in on some sites this person is somehow relevant to the site and people might search on his/her name. To see if he or she is mentioned somewhere on the site. When someone searches on this name all articles created by this person are shown in the results. Even though the content does not contain the search term (persons name).

We could create custom plugins, and just change the things we want / don't want. But any future changes to the plugin (maybe bug fixes or new features) will be missed when we switch to a custom plugin. So I would to avoid this.

There are three possible solutions I think:
1) Prevent indexing on author data, on the plugin level using a plugin parameter
2) preventing the indexing on the component level somehow (of using some kind of filter)
2) Prevent the showing of the indexed articles in the menu item with a menu item parameter if they are only matched on the author name.

We also see results that are 'matched' on the item slug or some other way: The search term is present in the item URL and that makes the finder 'score' this article and show it as a result. Because maybe the menu item or category above the article menu item contains this search word. This creates a search result even when the title, article intro or text do nit contain the search term. So excluding this 'matching' on the article slug / URL would also be nice. 

Maybe a different feature might also help: The search result all have some kind of weight. I imagine URL/slug and author information are rated 'lower' the article title of article text.  Maybe adding an option to only show results with a minimal score (leaving ut lower scoring items) would also prevent unwanted (because: 'to many irrelevant') results.

I believe I have raised the 'author' issue before. But other then the suggestion to create my own plugins this was actualy dealt with. It's not a big issue, but I think this might make the search a bit more relevant for frontend users?

**Comment by brianteeman** [comment]
Don't you just have to disable the author in the maps?

**Comment by jjnxpct** [comment]
No I don't think that does anything... When I disable 'author' an all names below this the results are still shown. And re-indexing also just turns them on again?

**Comment by brianteeman** [comment]
> And re-indexing also just turns them on again?

Sorry only able to test in J4 and that's not the case their. The map stays unpublished

**Comment by jjnxpct** [comment]
Depublishing the author items in the 'map' does not prevent the articles to be shown as results when the search term is in the author name. After re-indexing the Author mappings are published again.

If this is working in J4, and this can not be  addressed in J3 anymore we will need to create a custom search plugin I guess. But I think / hope the J4 Smart Search will have some more granular settings. Not just disabling search in meta data like 'author' but also a way to not show results that have an very low score. But maybe this 'minimum score' might not be needed if we have some more control over what parts of an article to check for search terms.

**Comment by Hackwar** [comment]
Yes, it would be good to allow for more granularity. I had this on my todo list for the smart search plugins but didn't get to it. Now that we released the beta of 4.0, we have a feature freeze and I wouldn't push this in. We can add this in Joomla 4.1 and I would be happy if you could provide PR(s) for this.

**Comment by Hackwar** [comment]
Here is the PR to implement this: #36867

**Comment by Quy** [comment]
Closing as having a pull request.
