### ISSUE TITLE
[4.0] Class 'Joomla\Plugin\System\Debug\Storage\FileStorage' not found

### ISSUE THREAD

**Issue by diddipoeler** [joomla/joomla-cms#26255]
### Steps to reproduce the issue
In the backend i got this error !

### System information (as much as possible)
After Update to 4 alpha 12

**Comment by alikon** [comment]
i guess you are updating from alpha to alpha?
 in this case that kind of update is not yet supported.....

**Comment by ghost** [comment]
Closed as looks like expected behaviour. Please reopen, if i'm wrong.

**Comment by SharkyKZ** [comment]
To solve this specific issue delete `libraries/autoload_psr4.php` file. But, as said above, currently updates are not really supported. Other things might break when updating.
