### ISSUE TITLE
[4.0] add support for screen readers to active j4 admin menu item

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#26270]
adds `aria-current="page"` to active admin menu item.

![image](https://user-images.githubusercontent.com/1850089/64746860-d8fa1700-d4d2-11e9-8217-d8411b70df92.png)

**Comment by N6REJ** [comment]
@franz-wohlkoenig assign this to me please.

**Comment by brianteeman** [comment]
@franz-wohlkoenig @N6REJ 
We dont usually assign issues to people

Can you edit the original post please as it is the PR template and as this is an issue the information is confusing

@N6REJ Are you comfortable making this change - it has to be done in javascript - if not I can do it for you but I dont want to steal your thunder

**Comment by N6REJ** [comment]
> @N6REJ Are you comfortable making this change - it has to be done in javascript - if not I can do it for you but I dont want to steal your thunder

@brianteeman oh gosh! you do it please!! lol, js and I are barely acquaintances.

**Comment by brianteeman** [comment]
This should be closed as it was solved with #26326
