### ISSUE TITLE
[4.0] Language install

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26288]
After installing a language you get the following message

![image](https://user-images.githubusercontent.com/1296369/64851578-9853e800-d60f-11e9-9874-6b7edc67d15d.png)

Which is a bit confusing because as far as the user is concerned they installed a language not a package.

@infograf768 did make a change for this in J3 https://github.com/joomla/joomla-cms/pull/10523 

https://github.com/infograf768/joomla-cms/blob/940a8223567863af3e9b7142d31180cbeb1d6b23/administrator/components/com_installer/models/languages.php#L303

but it looks like that change has gone

**Comment by infograf768** [comment]
Not specially related to 4.0
The code has been changed drastically since 2016.
Now we have a general string for any package
`$msg = JText::sprintf('COM_INSTALLER_INSTALL_SUCCESS', JText::_('COM_INSTALLER_TYPE_TYPE_' . strtoupper($package['type'])));`

in `.../administrator/components/com_installer/models/install.php` line 197

**Comment by infograf768** [comment]
It uses `COM_INSTALLER_TYPE_TYPE_PACKAGE="package"` instead of `COM_INSTALLER_TYPE_TYPE_LANGUAGE="language"` because one can still (I guess. Would have to test) install a single language (site or admin) which would not be presented as a pack. (That kind is not proposed by core)

**Comment by infograf768** [comment]
Example whne I Installed the Russian admin.zip via extension install
<img width="854" alt="Screen Shot 2019-09-13 at 12 41 50" src="https://user-images.githubusercontent.com/869724/64857115-f5f22f80-d623-11e9-8395-fd2cc3a9ad58.png">

**Comment by brianteeman** [comment]
Either we need to have a new way of saying that a language pack has been installed (similar to the old way) or at a minimum the unused language string should be removed

**Comment by mbabker** [comment]
Without some kind of special attribute or some way to identify a language pack within the package adapter you won’t get the desired end state anywhere that isn’t the languages install page.  Because ultimately a language pack is just a collection of language extensions, and I don’t think it’s a good idea to try and assume something is a language pack based on file name or it only containing a certain extension type.

**Comment by infograf768** [comment]
And, in any case, one can install (although not recommanded by core), a single language as an extension and not as a pack. Which means we should keep the string.

**Comment by brianteeman** [comment]
It is crazy that on a page that can only install a language there can not be a message that says you installed a language. Saying that its not possible is something I can not believe.

**Comment by brianteeman** [comment]
I guess I wasn't clear enough that I was referring to installing a language the recommended way using the language specific install page and not the generic extension installer

**Comment by infograf768** [comment]
It was clear. Just explaining why we should keep the string. @mbabker explained the package issue.

**Comment by mbabker** [comment]
`git blame` says https://github.com/joomla/joomla-cms/commit/204ef46ae742a8ab7c2604c8d02e020f49d65837 undid that change.  So it was added in 3.6 and removed in 3.7 without notice.

**Comment by infograf768** [comment]
That PR was real good and this very small side effect is imho epiphenomenic.

**Comment by brianteeman** [comment]
When using big words its helpful to use the correct one.

Side effect or not - it should be fixed

**Comment by infograf768** [comment]
Then fix it. The word is correct. Learning semantics can be very useful for computer code as well as daily life. ROTFLOL

**Comment by brianteeman** [comment]
I will fix it. You are just stubbornly refusing to consider anything that was not your idea or that you overlooked

**Comment by infograf768** [comment]
Stop insulting people please.

**Comment by infograf768** [comment]
Closing as we have a patch https://github.com/joomla/joomla-cms/pull/26310
