### ISSUE TITLE
[4.0] RFC Plural strings

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26284]
### Preamble
This is referring to the english values in the strings **not** any translation
This is **not** about changing any language constants
This _is_ about consistency in the english used (if it was any other language it would not even be discussed as we would not know about it)

### Issue
We have  at least **THREE** different ways that singular strings are written in english

> COM_REDIRECT_N_ITEMS_ARCHIVED="%d links archived."
COM_REDIRECT_N_ITEMS_ARCHIVED_1="Link archived."

> COM_CONTACT_N_ITEMS_ARCHIVED="%d contacts archived."
COM_CONTACT_N_ITEMS_ARCHIVED_1="%d contact archived."

> COM_USERS_USERS_N_ITEMS_DELETED="%d users deleted."
COM_USERS_USERS_N_ITEMS_DELETED_1="1 user deleted."

Language strings should be consistent in style and language. This is not only important for consistency and creating a professional impression it is also import for accessibility. 

> providing consistent labels for the repeated components reduces the cognitive load of users with cognitive disabilities 

### Proposal
All the **values** to be updated to one single format and the enGB style guide updated so that singular strings are

> COM_REDIRECT_N_ITEMS_ARCHIVED="%d links archived."
COM_REDIRECT_N_ITEMS_ARCHIVED_1="Link archived."

> COM_CONTACT_N_ITEMS_ARCHIVED="%d contacts archived."
COM_CONTACT_N_ITEMS_ARCHIVED_1="Contact archived."

> COM_USERS_USERS_N_ITEMS_DELETED="%d users deleted."
COM_USERS_USERS_N_ITEMS_DELETED_1="User deleted."

**Comment by wilsonge** [comment]
So i guess `%d contact archived` is actually the same (in the end for the user) as `1 user deleted` so would involve less work to convert to that format for consistency.

However agree with you proposal as that's the "correct" English way I think.

**Comment by brianteeman** [comment]
Thanks - PR incoming

**Comment by infograf768** [comment]
> So i guess %d contact archived is actually the same (in the end for the user) as 1 user deleted so would involve less work to convert to that format for consistency.

Not really for some languages as the variable may still be necessary in code when the same wording is used for 1 and another figure.

EDIT: I meant we still need to Count in code.

**Comment by wilsonge** [comment]
@infograf768 Text::plural will still pass that variable in. Just in english language files we choose not to use it. Totally agree the option for language packs still needs to be there

**Comment by brianteeman** [comment]
Just deleted my reply after seeing the edit

This is nothing to do with the code - I was very explicit writing what it referred to at the very beginning of the proposal

**Comment by infograf768** [comment]
I was mostly referring to
> so would involve less work to convert to that format for consistency

As it will be the opposite as TTs will see these strings modified in en-GB and have to confirm or will feel obliged to modify them.
But this is an old debate and I was never followed on this, so just forget me.
