### ISSUE TITLE
[4.0] Duplicate ID error on update from Joomla 3 to Joomla 4

### ISSUE THREAD

**Issue by roland-d** [joomla/joomla-cms#26287]
### Steps to reproduce the issue
1. Install Joomla 3
2. Download Joomla 4 nightly build
3. Go to the Joomla Updater
4. Click on `Upload & Update` tab
5. Click on the File upload
6. Select the Joomla 4 nightly build package
7. Click on Upload & Install button
8. Go through the installation process
9. When the installation has completed you will see this notice:
![image](https://user-images.githubusercontent.com/359377/64803950-31dab580-d58e-11e9-907d-d81016789aa3.png)

### Expected result
No duplicate ID error

### Actual result
Duplicate ID error

### System information (as much as possible)
Joomla 3.9.12-dev
Joomla 4.0-alpha 12

**Comment by wilsonge** [comment]
@brianteeman This comes from https://github.com/joomla/joomla-cms/pull/26097 - in Joomla 3 we have many more menu items https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/joomla.sql#L1423 - so there's already an ID 18 - are you able to just remove the id to be inserted from just the update scripts please?

**Comment by wilsonge** [comment]
See #26289
