### ISSUE TITLE
[4.0] Missing language strings in installer

### ISSUE THREAD

**Issue by roland-d** [joomla/joomla-cms#26299]
### Steps to reproduce the issue
1. Install an extension that you know will fail the installation
2. Notice you get a popup with a message like this:
![image](https://user-images.githubusercontent.com/359377/64907180-6fa31f80-d6ef-11e9-8d3b-6407c2fbab0c.png)

The issue is that we have this code in the installer `'JLIB_INSTALLER_' . $this->route` but there are no translations for them.

We need to find out which routes we have, to know which messages we need.

### Expected result
The message is translated

### Actual result
The message is untranslated

### Additional comments
I am putting this issue here as a reminder so we don't forget about them

**Comment by brianteeman** [comment]
@roland-d are you sure that this is specific to Joomla 4 as it looks the same code as in joomla 3

**Comment by roland-d** [comment]
@brianteeman I am not sure it is specific to J4 as I did not look at J3, I just ran into this and wanted to make sure we don't forget about it.

**Comment by ceford** [comment]
I have had a look at this issue by searching the code for occurrences of JLIB_INSTALLER_' and I think there is only one string missing: JLIB_INSTALLER_DISCOVER_INSTALL and it is the same in J3. I could do a PR for J4. However, I don't know how to test it. Clearly I need to unpack a component and discover it. I tried that with the search component from J3 and it installed. I don't know how to set the PHP minimum requirement as suggested by the screenshot above. Also, I noticed that a lot of the instances of JLIB_INSTALLER_ were not followed by strtoupper - in ModuleAdapter.php, PackageAdapter.php, PluginAdapter.php and more. Should that be a separate issue? Or does it not matter?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26299">issues.joomla.org/tracker/joomla-cms/26299</a>.</sub>

**Comment by alikon** [comment]
please test #31315
