### ISSUE TITLE
[4.0] Undefined value in HTTP Headers Plugin

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#26291]
Undefined value `$cspValue` on line 410 of httpheaders plugin. Looks like the foreach loop is wrong. 

Placeholder for @zero-24 for later once JDayDE commitments are finished

- Define class variables
- App/DB variables in constructor can be removed
- Catch exception that can be thrown by random_bytes on really terrible servers

**Comment by zero-24** [comment]
@wilsonge please see: https://github.com/joomla/joomla-cms/pull/26851

**Comment by zero-24** [comment]
btw

> Undefined value $cspValue on line 410 of httpheaders plugin. Looks like the foreach loop is wrong.

https://github.com/joomla/joomla-cms/blob/d93325b45118a8abe7670fd2b8111a85f588dbfc/plugins/system/httpheaders/httpheaders.php#L410

There is no $cspValue var maybe an local install problem or not up-to-date branch ;)
