### ISSUE TITLE
[4.0][RFC] Allow source search in admin for plugin tags

### ISSUE THREAD

**Issue by ot2sen** [joomla/joomla-cms#26307]
### Is your feature request related to a problem? Please describe.
Have seen more threads lately on how to identify if an extension is in use at a site. Site maintainers find difficulty in knowing whether a plugin code is still used in their articles. Could be a loadmodule or a form integration or a gallery, all initiated by a plugin tag.

### Describe the solution you'd like
Would be nice to see the backend article search being extended to allow searching for plugin tags in a special 'source mode'. Direct search in intro and full text source, to know if a plugin tag is still in use. This to avoid broken content where you forgot to remove a no longer used included extension.

**Comment by SharkyKZ** [comment]
That's already possible, use `content:` prefix.

**Comment by ghost** [comment]
closed as stated above.

**Comment by ot2sen** [comment]
> That's already possible, use content: prefix.

Yes, indeed it does today for {load and similar. I was also expecting it to do so using the prefixes but didn´t get any results when testing it before reporting. I must have made a mistake and only searched for a more advanced code tag not visible in the non-source content areas. My bad :)
