### ISSUE TITLE
[4.0] Undefined property: stdClass::$workflow_id

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#26306]
### Steps to reproduce the issue
Create a new workflow.
Under Stages column, click the count badge.
Edit Unpublished.
Click Save & Close.
View PHP error log.

> \administrator\components\com_workflow\Model\StageModel.php on line 163

Do the same under the Transitions column.

> Trying to get property 'workflow_id' of non-object in \administrator\components\com_workflow\Model\TransitionModel.php on line 89

**Comment by wilsonge** [comment]
PR https://github.com/joomla/joomla-cms/pull/27874
