### ISSUE TITLE
[4.0] Add two new link attributes

### ISSUE THREAD

**Issue by ot2sen** [joomla/joomla-cms#26312]
### Is your feature request related to a problem? Please describe.
Google is evolving the nofollow attribute by adding two new attributes for better flagging Sponsored content and User Generated Content. 
rel="sponsored" and rel="ugc"

Ref.: https://webmasters.googleblog.com/2019/09/evolving-nofollow-new-ways-to-identify.html

### Describe the solution you'd like
We could add these to the already existing options in menus, content, categories, etc.

**Comment by simbus82** [comment]
Great @ot2sen!
For SEO then is needed to select one or more attributes like these, so this field should be a multiselect.

**Comment by alikon** [comment]
please test #28055
