### ISSUE TITLE
[4.0] Error when saving a new article / category (PostgreSQL)

### ISSUE THREAD

**Issue by twister65** [joomla/joomla-cms#26315]
### Steps to reproduce the issue
Save a new article / category

### Expected result
No error.

### Actual result
Save failed with the following error: 22021, 7
![NewArtError](https://user-images.githubusercontent.com/26852967/64922182-89fefb00-d7cc-11e9-96c8-f9e51567053b.png)

### System information (as much as possible)
- Joomla 4 version: alpha 12 dev,  Sunday, 15 September 2019 02:00:50 UTC
- Database Version: postgresql 11.5
- Database Collation: fr_FR.utf8
- Database Connection Collation: fr_FR.utf8
- PHP Version: 7.3.9

**Comment by twister65** [comment]
Article error message:
https://github.com/joomla/joomla-cms/blob/35f7f8b7418107b79977eb988bb509c811aa2b89/libraries/src/MVC/Controller/FormController.php#L762

CC @alikon , @richard67

**Comment by richard67** [comment]
@twister65 Could you test PR #25884 ? It might help here, too. Pls. report back here if it does or not. As long as not clear we should leave this issue open.

**Comment by twister65** [comment]
PR #25884 fixes this issue. Thanks.

**Comment by richard67** [comment]
Thanks goes to @alikon .

**Comment by richard67** [comment]
@twister65 Could you set the test result here? [https://issues.joomla.org/tracker/joomla-cms/25884](https://issues.joomla.org/tracker/joomla-cms/25884)
