### ISSUE TITLE
[4.0] Login Page Error Messages for inputs

### ISSUE THREAD

**Issue by unknown-sudo** [joomla/joomla-cms#26319]
If you have made wrong or empty entries in the login form, the error message will appear directly in the label, but will be placed optically under the field. From a accessibility point of view it is better if the error message does not change the label but is displayed after the input field.

Otherwise the screen reader reads the label as "Username please fill in this field" and later in the input field again that there is an error.
Better would be an output in the screenreader like the following:
Username (label)
Username Input field
Username error message

This can be done by entering the attribute aria-describedby in the input field and referencing the error message.

References:
https://www.w3.org/WAI/GL/wiki/Using_ARIA_role_of_alert_for_Error_Feedback_in_Forms

**Comment by brianteeman** [comment]
On the login this only applies to empty fields not fields with errors - If you have an example of it appearing with an error the please post details on how to replicate that

**Comment by unknown-sudo** [comment]
My issue relates to the empty fields notifications as described above, perhaps I have expressed myself unhappily with Error, I come from Germany, please be pardoned with my choice of words.

**Comment by brianteeman** [comment]
Thanks for the clarification.

One easy possibility for that specific page would be to remove the "required" on those fields.

**Comment by brianteeman** [comment]
After further investigation and consultation with external experts I am closing this. The error messages you are referring to are generated by the browser (not joomla) for an html5 required input field
