### ISSUE TITLE
(4.0) Edit Module Icon in Backend - Title wrong

### ISSUE THREAD

**Issue by unknown-sudo** [joomla/joomla-cms#26321]
The edit module icon in the backend has a title "Edit site" or "Edit system" and so on. I think it would be more appropriate to name it more detailed. "Edit the System information Module" or similar. "Edit System" would lead me to the configuration rather than to the module. Behind "Edit Sample Data" I would also expect something different.

**Comment by brianteeman** [comment]
You are correct

But currently the option in that submenu are actually incorrect so I would like to wait until that is resolved before resolving the text

**Comment by infograf768** [comment]
The title for the cog icon is defined by the module title
`<span class="sr-only"><?php echo Text::_('JACTION_EDIT') . ' ' . $module->title; ?></span>`
Change the modules titles and you will get what you need.

Imho we have another issue in the sense that it does not use at least a sprintf for multilingual better use.

We need a new constant, for example `JACTION_EDIT_MODULE`
`JACTION_EDIT_MODULE="Edit the '%s' module"`

code would be:
`<?php echo Text::sprintf('JACTION_EDIT_MODULE', $module->title); ?>`

**Comment by Quy** [comment]
Please test PR #26382<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26321">issues.joomla.org/tracker/joomla-cms/26321</a>.</sub>
