### ISSUE TITLE
[4.0] login page General problem of the dialog box

### ISSUE THREAD

**Issue by unknown-sudo** [joomla/joomla-cms#26320]
If you enter wrong access data, a div opens in the appearance of a dialog box. There are several problems here.

1) Usability in itself: the div appears optically like a modal window, which has the desire to be closed. But it doesn't have to be. 
2) The way it is integrated should put the focus in the "modal window" so that you can close it. 
3) In the backend these dialog boxes seem to be used more often, but the success boxes do not close on their own but remain open until the next action.

Long history in short, the usability and accessibility of these dialog boxes is not given and should be urgently rethought.

A better solution would be to bring the alerts via the form just like in Joomla 3. Such an alert could also contain a more detailed error message to help the user understand what he should do. The most accessible option for errors would be to use the default browser alert, but of course designers wouldn't be happy about it.

e.g.
"The form cannot be submitted as it's missing required data.
Please correct the listed fields and try again:
Please fill in Username (with link to the input)
Please fill in Password (with link to the input)"

Reference:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alertdialog_role

**Comment by brianteeman** [comment]
We have open issues for all of this
