### ISSUE TITLE
Hiding Browser Title Page do not work.

### ISSUE THREAD

**Issue by nicrame** [joomla/joomla-cms#26328]
It is impossible to hide "Home", or any other name i will put as menu position name - from the page title (name on the browser page title, used in title html tag) on the joomla site. Default install with sample data, or when i used different external template and my own data.

When You put something inside Menus \ All menu items \ Click on "Home" \ Browser Page Title form (anything, and still set Page Display - set Show Page Heading to No - it will still show the data (even when it's turned off).

### Steps to reproduce the issue

Install default Joomla 3 with sample data (do not change anything).

Login into Administrator.
1) Go to Menus \ All menu items \ Click on "Home" \ Page Display - set Show Page Heading to No, leave everything other empty. Click Save and close. Click Rebuild button on top.

2) Go to Menus \ All menu items \ Click Options button on top \ set Show Page Heading to No, leave everything other empty. Click Save and close. Click Rebuild button on top.

3) Go to System \ Global Configuration \ Site \ slect Site Name in Page Titles = No. \ Click Save and close.

I also selected "Hide Title" for default article used as front page for example, for both position menu place, and article itself. Result is always the same.

### Expected result

There shoult be no title on the borswer, or should be selected inside Global Configuration. Not from the menu position name!

### Actual result

There is always name of the menu position in the title tag.  even when selected to Yes, No, or Global.

### System information (as much as possible)

Database Type 	mysql
Database Version 	5.7.26
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.2.18
Web Server 	Apache/2.4.39 (Win64) PHP/7.2.18
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.9.11 Stable [ Amani ] 13-August-2019 15:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0 

Same problem on:

Typ bazy danych 	mysql
Wersja bazy danych 	5.5.60-MariaDB
Metoda porównywania znaków w bazie danych 	utf8_general_ci
Metoda porównywania znaków przy połączeniu z bazą danych 	utf8mb4_general_ci
Wersja PHP 	7.3.9
Serwer WWW 	Apache/2.4.6 (CentOS)
PHP działa na 	fpm-fcgi
Wersja Joomla! 	Joomla! 3.9.11 Stable [ Amani ] 13-August-2019 15:00 GMT
Wersja Platformy Joomla! 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Klient użytkownika 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0 

### Additional comments

It also didn't work with version 3.9.9 if i remember correctly.
I find no way to make it work as it should.
![screen shot 2019-09-16 at 10 14 53](https://issues.joomla.org/uploads/1/8e91d0554b5bd9303c64537466c8f288.jpg)
![screen shot 2019-09-16 at 10 14 54](https://issues.joomla.org/uploads/1/9e632be46b013168b9ccd644d03050c6.jpg)
![screen shot 2019-09-16 at 10 14 54](https://issues.joomla.org/uploads/1/fb2cbe4c8947cc2d433d81889b33367b.jpg)
![screen shot 2019-09-16 at 10 14 54](https://issues.joomla.org/uploads/1/713bd6fadf2163df6261c64e787ea2d7.jpg)

**Comment by brianteeman** [comment]
Every page should always have a title

**Comment by SharkyKZ** [comment]
Page Heading and Browser Page Title are not the same. You can hide the heading but not the title.

**Comment by alikon** [comment]
expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26328">issues.joomla.org/tracker/joomla-cms/26328</a>.</sub>

**Comment by N6REJ** [comment]
in the "browser page title" you can change the title.  Simply enter a space and it will be as blank as you can get it.
