### ISSUE TITLE
[4.0] Responsive toolbar

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26331]
Is it the intended behaviour that as soon as the screen width drops below 1200px that the option and help buttons are no longer separated from the other toolbar buttons and floated right?

![image](https://user-images.githubusercontent.com/1296369/64970672-3361f180-d89e-11e9-8617-a4d5d56c28c2.png)

**Comment by brianteeman** [comment]
and the same question for search and filters
![image](https://user-images.githubusercontent.com/1296369/64970929-ad927600-d89e-11e9-8111-faaf19249aeb.png)

**Comment by brianteeman** [comment]
anyone?

**Comment by infograf768** [comment]
For Options/Help, CSS is
```
@media (max-width: 1199.98px) {
  .btn-toolbar > joomla-toolbar-button,
  .btn-toolbar > .btn-group {
    margin-left: 0 !important;
    margin-right: 0.75rem;
    margin-bottom: 0.75rem; } }
```
which margin-left overrides `ml-auto`

For Search and Filters it is
```
@media (max-width: 1199.98px) {
  .js-stools {
    justify-content: flex-start; }. // Instead of flex-end
    .js-stools .js-stools-container-bar .btn-toolbar {
      /*! justify-content: flex-start; */ } }
```

Looks like we have no intermediary max-width between 1199.98px and 575.98px (for example 991.98px) 

One aspect to consider and makes it hard to decide the max-width is the change in available width when the admin menu is toggled.

**Comment by brianteeman** [comment]
Closed as no longer an issue
