### ISSUE TITLE
[4.0] Error backing up old database when installing into not empty PostgreSQL database

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#26349]
### Steps to reproduce the issue

1. Make a new, clean installation of current 4.0-dev using an empty PostgreSQL database and note the database prefix used for this installation.
2. After successful installation, delete configuration.php and install again into the same database, using the same database prefix.

### Expected result

At the 2nd installation, previously existing tables should be backed up by renaming them.

### Actual result

Installation fails, error alert shown:

![snap-3](https://user-images.githubusercontent.com/7413183/65068018-173a7f00-d988-11e9-8d56-955957fbcb82.png)

In PostgreSQL log file:

```
2019-09-17 20:11:34.151 CEST [6537] jdb1adm@joomladb1 ERROR:  relation "j4ux0_finder_terms_idx_term" already exists
2019-09-17 20:11:34.151 CEST [6537] jdb1adm@joomladb1 STATEMENT:  ALTER INDEX j4ux0_finder_terms_idx_term RENAME TO j4ux0_finder_terms_idx_term
```

### System information (as much as possible)

PHP 7.2
PostgreSQL database version 10.10

### Additional comments

Thanks @alikon for reporting this issue. I can confirm it.

**Comment by alikon** [comment]
just let me add this discussion for better reference  #18835

**Comment by brianteeman** [comment]
sounds like a simple bug and nothing to do with that issue

**Comment by brianteeman** [comment]
I am trying to test it but I cant get the joomla installer to see my newly installed pgsql  11.5. its running because I can access it through the shell/cli

will have to try again later

**Comment by richard67** [comment]
Well the main difference between MySQL and PostgreSQL here is that on PostgreSQL it needs not only to rename the tables but also the indexes, because index names are preceeded by the table names. And there happens the error. According to the log the new name is the same name as the old name when renaming the index. I am looking for it but have to go sleep soon, work tomorrow.

**Comment by richard67** [comment]
Table rename happens in database framework, in case of PostgreSQL driver including the indexes ... I have to further check code there.
Update: Code looks ok there ... so it needs deeper digging.

**Comment by brianteeman** [comment]
I have postgres:pdo working now.

**Comment by brianteeman** [comment]
Fixed it - pr incoming

Its a sql error

**Comment by richard67** [comment]
Closing as having PR #26351 .
