### ISSUE TITLE
Custom fields - List of images field

### ISSUE THREAD

**Issue by EJBJane** [joomla/joomla-cms#26350]
### Steps to reproduce the issue
Set default image value to -1

### Expected result
Show image represented as -1 in frontend 

### Actual result
Error
Save failed with the following error: The default value is invalid.
Error backend  

### System information (as much as possible)
[screencapture-dolcevia-nl-administrator-index-php-2019-09-18-10_11_53.pdf](https://github.com/joomla/joomla-cms/files/3625169/screencapture-dolcevia-nl-administrator-index-php-2019-09-18-10_11_53.pdf)

PHP Built On | Linux dedi2762.your-server.de 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3 (2019-09-02) x86_64
Database Type | mysql
Database Version | 5.7.27-1
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.2.22
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.9.11 Stable [ Amani ] 13-August-2019 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

### Additional comments
Also tried changing the value of the image in the database but it does not work either. No error but no image on frontend.

**Comment by SharkyKZ** [comment]
Can you check if #24643 solves your issue?

**Comment by brianteeman** [comment]
Why are you setting the default value as -1

default (optional) is the default image file name.

**Comment by infograf768** [comment]
The tip is useless and nothing in the docs:
<img width="464" alt="Screen Shot 2019-09-18 at 10 42 55" src="https://user-images.githubusercontent.com/869724/65132445-417c5300-da01-11e9-880f-ab074d48cd44.png">

**Comment by brianteeman** [comment]
@infograf768 the docs say it is the default image file name

**Comment by EJBJane** [comment]
Just to be clear, I first tried all combinations of image url, Lichte-_milieubelasting.png
and then images/2019/footprints/Lichte-_milieubelasting.png..

**Comment by EJBJane** [comment]
Any which way and anything I try as a default value gives the same validation error. I wanted to understand what was in that field and exported the contents of that field in some articles where i manually entered the field. The result was that a -1 was present in these fields so I thought, perhaps the default value should be something like that.

**Comment by infograf768** [comment]
> the docs say it is the default image file name

After navigating to the 3rd page of the help modal, not very user friendly.

**Comment by EJBJane** [comment]
> Can you check if #24643 solves your issue?

No it doesnt solve my issue

**Comment by EJBJane** [comment]
> Why are you setting the default value as -1
> 
Please see my answer below.

> default (optional) is the default image file name.

**Comment by infograf768** [comment]
I am afraid @EJBJane is right. We do have a bug here.
<img width="454" alt="Screen Shot 2019-09-18 at 10 55 58" src="https://user-images.githubusercontent.com/869724/65133512-067b1f00-da03-11e9-85bb-b7c1e05ee019.png">

**Comment by infograf768** [comment]
I tested here https://github.com/joomla/joomla-cms/pull/24643 and it solves the issue.
My test site is current staging. Saves OK, then when editing an article:

<img width="659" alt="Screen Shot 2019-09-18 at 11 03 18" src="https://user-images.githubusercontent.com/869724/65134045-fb74be80-da03-11e9-98ad-08cb61f6103d.png">

**Comment by EJBJane** [comment]
My apologies but "Can you check if #24643 solves your issue?" Yes it did, I just had to refresh cache a few times.

**Comment by EJBJane** [comment]
> > Can you check if #24643 solves your issue?
> 
> No it doesnt solve my issue

My apologies but YES it did, I just had to refresh cache a few times.

**Comment by infograf768** [comment]
I asked the original PR creator in https://github.com/joomla/joomla-cms/pull/24643 to reopen his PR. Until then, as its branch is no more available, let's not close this.

**Comment by infograf768** [comment]
If he does not reply, we will make a new PR.
Thanks @EJBJane for your Issue.

**Comment by EJBJane** [comment]
In fact perhaps I was too hasty to call this closed as, yes the validation error is fixed with #24643 but if I add the image name to the default value my expectation would be that image would show up by default in an article but it does not. 
I have a very sticky cache so I have to retry several times but I have refreshed a dozen times and still no default image showing up.

**Comment by infograf768** [comment]
Your cache is the issue as it works fine here in frontend article display.
We have 2 hours only if we want to get this patch in next version.
Will make the PR and post here a link where you can mark your test as OK.

**Comment by infograf768** [comment]
Patch ready here https://github.com/joomla/joomla-cms/pull/26352
Please test and mark your test OK here https://issues.joomla.org/tracker/joomla-cms/26352
