### ISSUE TITLE
[4.0] Joomla Installation RTL issue

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#26356]
### Steps to reproduce the issue
Modify installation/language/en-GB/en-GB.xml to set it to RTL
`<rtl>1</rtl>`
Install Joomla.
When clicking on the `Install Joomla` button, the rotating Joomla logo is misplaced.

### LTR result => OK
![installLTR](https://user-images.githubusercontent.com/869724/65230856-e6b12d00-dace-11e9-9a8f-cc836f674c34.gif)

### RTL result
![englishRTL](https://user-images.githubusercontent.com/869724/65230888-f7fa3980-dace-11e9-98c5-89617e403ed2.gif)

Could not find which precise css is concerned.

**Comment by brianteeman** [comment]
Is it just the spinner thats a problem? If so the relevant commit is #25776 by @dgrammatiko

**Comment by dgrammatiko** [comment]
It’s the svg, ping @C-Lodder

**Comment by infograf768** [comment]
Whether I try to correct margins in the joomla-core-loader js or css for each colour, I do not get any change.

**Comment by infograf768** [comment]
@dgrammatiko 
Which .svg is at stake? Me lost...

**Comment by C-Lodder** [comment]
I'm looking into it now. It's not an SVG

**Comment by infograf768** [comment]
same issue btw for com_associations

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/26358

**Comment by infograf768** [comment]
Closing as we have a patch
