### ISSUE TITLE
Action log: Exclude usergroups from logging

### ISSUE THREAD

**Issue by jjnxpct** [joomla/joomla-cms#26353]
It might be a nice feature to disable action logging for specific usergroups. 

Maybe you would like to only log actions in the backend (managers) without logging actions from registered users on the frontend.

Or maybe you would like to log all actions except Super Admin actions. Just to keep track of what other (not you as SU) are doing on the back- or frontend. So you can blame theme when things go wrong ;-)

**Comment by SharkyKZ** [comment]
Not sure about selective logging but we could definitely add a user group filter to `com_actionlogs`.

**Comment by alikon** [comment]
not convinced about selective logging.... but adding a user group filter seems reasonable to me

**Comment by SharkyKZ** [comment]
Actually you can log specific user groups by changing the access level of Actionlog plugins.

**Comment by jjnxpct** [comment]
So we could create an access level and add the usergroups to the we want to log and then set the plugin(s) to that access level?

Or if you don't want to log frontend actions you could use the default 'special' access level?

Both options would not exclude Super User a I think?

**Comment by SharkyKZ** [comment]
>So we could create an access level and add the usergroups to the we want to log and then set the plugin(s) to that access level?

Yes.

>Or if you don't want to log frontend actions you could use the default 'special' access level?

I don't think this would exclude frontend actions.

>Both options would not exclude Super User a I think?

The first option would, if configured properly.

**Comment by jjnxpct** [comment]
OK thanks @SharkyKZ

**Comment by alikon** [comment]
can we close this than @jjnxpct @SharkyKZ ?

**Comment by jjnxpct** [comment]
Yes!
