### ISSUE TITLE
[4.0] [PostgreSQL] Errors in com_contact and com_content

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#26355]
### Steps to reproduce the issue

View achived article view (with #26354 applied) or contact category view in frontend.

### Expected result

No errors.

### Actual result

>42804, 7, ERROR: CASE types integer and text cannot be matched LINE 1: ...LECT a.*,CASE WHEN CHAR_LENGTH(a.alias) != 0 THEN a.id::text... ^ 

### System information (as much as possible)
4.0-dev
postgresql 11.1

**Comment by alikon** [comment]
please test #26362
