### ISSUE TITLE
[4.0] Side menu with children non-functional

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#26370]
### Steps to reproduce the issue
install clean 4.0-dev
go to admin and click on any sidebar item.

### Expected result
switches to that menu item's view

### Actual result
nothing happens
clicking on the grid square DOES open the menu as shown in the video

### System information (as much as possible)

[systeminfo-2019-09-21T17_33_54+00_00.txt](https://github.com/joomla/joomla-cms/files/3638929/systeminfo-2019-09-21T17_33_54%2B00_00.txt)

### Additional comments
demo video => https://drive.google.com/open?id=1VhryNBF1RPW_VRA-Z9yF9ceK70uYBbGC

**Comment by brianteeman** [comment]
Can you check and see what version of metismenu is running

**Comment by N6REJ** [comment]
I didn't find metis... hope this helps.
![image](https://user-images.githubusercontent.com/1850089/65377689-2a459b80-dc75-11e9-8b69-082a0d55423d.png)

**Comment by brianteeman** [comment]
It's JavaScript!??

**Comment by Quy** [comment]
Are you testing with the [nightly build](https://developer.joomla.org/nightly-builds.html)?

**Comment by astridx** [comment]
@N6REJ 
You find version of metismenu on the top of file
`joomla-cms4/media/vendor/metismenujs/js/metismenujs.js`

**Comment by N6REJ** [comment]
> @N6REJ
> You find version of metismenu on the top of file
> `joomla-cms4/media/vendor/metismenujs/js/metismenujs.js`

ah!  ty!!!    metismenujs - v1.0.3

**Comment by N6REJ** [comment]
> Are you testing with the [nightly build](https://developer.joomla.org/nightly-builds.html)?

no, I do a pull daily, and hard reset anytime I'm unsure.

**Comment by Quy** [comment]
I am not able to reproduce with the nightly build and a fresh install of the daily pull.

**Comment by N6REJ** [comment]
@Quy I just ran npm ci on the install that did have the issue ( as you said last nights is fine ) and it fixed the issue.  idk what that means.

**Comment by brianteeman** [comment]
No idea what your problem was as it has been set to metismenu 1.0.3 since it was first committed but there is a problem with metismenu 1.10 which I have a pull request for.
