### ISSUE TITLE
[4.0] Top menu icon confusing

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#26373]
### What needs to be fixed
Remove version icon 
![image](https://user-images.githubusercontent.com/1850089/65377660-da66d480-dc74-11e9-8c64-3f1d400884d3.png)

### Why this should be fixed
The  info looks & exists where other buttons are.

### How would you fix it
Move the info under the logo on the left OR put back on bottom right like its always been.

### Side Effects expected
none.

**Comment by alikon** [comment]
please test #26447<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26373">issues.joomla.org/tracker/joomla-cms/26373</a>.</sub>
