### ISSUE TITLE
[4.0] Dropdown box 1px larger then parent

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#26374]
### What needs to be fixed
Size of dropdown chevron
![image](https://user-images.githubusercontent.com/1850089/65378711-edcc6c80-dc81-11e9-812d-8e40a3f73083.png)

### Why this should be fixed
it's 1px larger then parent

### How would you fix it
make chevron part of parent instead of overlay

**Comment by N6REJ** [comment]
The bar left of the chevron is 39px but the chevron box is 41
maybe this will help track down the true culprit
![image](https://user-images.githubusercontent.com/1850089/65378840-0f2e5800-dc84-11e9-9253-28a6b197f5cf.png)

**Comment by brianteeman** [comment]
Duplicate report

**Comment by Quy** [comment]
Duplicate #25854<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26374">issues.joomla.org/tracker/joomla-cms/26374</a>.</sub>
