### ISSUE TITLE
[4.0] Installer dates and users

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26387]
installation\src\Model\DatabaseModel.php

There are two functions
https://github.com/joomla/joomla-cms/blob/deb2d006b34424e5b232a1e710def47a8d13347a/installation/src/Model/DatabaseModel.php#L820

https://github.com/joomla/joomla-cms/blob/deb2d006b34424e5b232a1e710def47a8d13347a/installation/src/Model/DatabaseModel.php#L873

The list of tables and fields here are incomplete and/or contains items that don't need to be checked

As far as I can tell there is no point in checking to update the date or id if there is no data installed in /joomla.sql for that table

From what I can see the lists were created for earlier version of joomla when sample data was installed and have not been updated 
- to remove items no longer in the installed data
- to add items in the installed data

**Comment by richard67** [comment]
The date thing should become obsolete when our works on the datetime columns will be finished. I’ll put it on the task list which we have in Glip.

**Comment by brianteeman** [comment]
@richard67 that is unrelated

**Comment by richard67** [comment]
@brianteeman. No, it is not. @wilsonge Please check and confirm.

**Comment by mbabker** [comment]
It's unrelated.  The `updateDates` function sets various dates to the current time (as of when that function runs) for a newly installed site.  So instead of having a null date for your created date of the default uncategorised categories or your super user account's registration date, those are set to what is in essence the time the site was created.  So the only thing it has to do with the rest of the work you're doing for the date/time fields is ensuring that query is correctly updated to match up with whatever the defaults in the `joomla.sql` file are.

**Comment by brianteeman** [comment]
>  So the only thing it has to do with the rest of the work you're doing for the date/time fields is ensuring that query is correctly updated to match up with whatever the defaults in the joomla.sql file are.

Not even that. The issue raised here is that there are fields/tables being checked with these functions that will never need to be checked and other fields/tables that should be checked with these functions which are not

**Comment by richard67** [comment]
I see. Well, after my changes there will not be a null date anymore for created and modified columns, and for the others we will use real NULL values, so that function will need to be updated at least. Thanks toy Brian for opening this issue so I got aware of that.

**Comment by brianteeman** [comment]
You are still missing the point completely of this issue it is nothing to do with null dates - spend two seconds reading the code and you will see that.

**Comment by richard67** [comment]
I see.

**Comment by brianteeman** [comment]
see #26399

**Comment by brianteeman** [comment]
re-open as although the current code is wrong it doesnt address the issue of localise or custom.sql

**Comment by richard67** [comment]
@brianteeman Please test PR #26825 for the datetime part. The user ID part is handled with PR #26745 .
