### ISSUE TITLE
Namespaced classes should not have @package annotations

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#26395]
The use of the `@package` annotation is to help with grouping global classes into packages for easier consumption with tools such as phpDocumentor (which is used to generate `api.joomla.org`).  And yet, https://api.joomla.org/cms-3/classes/Joomla.CMS.Toolbar.ToolbarHelper.html and https://api.joomla.org/cms-3/classes/Joomla.CMS.Captcha.Captcha.html both indicate they have incorrect file level doc blocks because there is a package listed.

Maybe someone should write a PHPCS sniff to prevent this error from happening again...

**Comment by SharkyKZ** [comment]
What about class level blocks like here:

https://github.com/joomla/joomla-cms/blob/0433b2908b3a3fb4e3a2b03016f7cf365e450b36/libraries/src/Mail/MailWrapper.php#L16-L17

**Comment by mbabker** [comment]
Also should be killed with fire.  If it is namespaced, the namespace is the package/sub package.

**Comment by SharkyKZ** [comment]
Test PR #26405 please.
