### ISSUE TITLE
[4.0] It is very necessary, especially for news sites, for the module title to be a link.

### ISSUE THREAD

**Issue by SamusUA** [joomla/joomla-cms#26398]
**It is very important, especially for news sites, that the module title is a link.**

If you do not want to do this in the main version of the module because of the weight of the code and the speed of the site, then do this in an alternative version of the module layout. See images.

This is necessary for all modules, but most of all for menu modules and articles.

![Menu-Item-Alias](https://user-images.githubusercontent.com/41996277/65459377-700e8980-de58-11e9-97ae-17263c4b0c54.jpg)
![Header-link-layout](https://user-images.githubusercontent.com/41996277/65459383-7270e380-de58-11e9-83c9-24a094696094.jpg)

**Comment by ReLater** [comment]
> It is very important, especially for news sites, that the module title is a link.

Sorry that I have to ask: Why is it important? Could you please describe a use case.

> This is necessary for all modules, but most of all for menu modules

Why should a menu module have a linked title? It's a collection of links...

**Comment by SamusUA** [comment]
Because often a news site has both main sections and subsections. Subsections are menu links, but how do I get into the general section from this block ("All Related Articles")? Only third-party modules help. Or duplication of a module (a separate menu, a separate link to the header) also helps. But why, if one additional parameter is enough?

**But in fact, the link in the header is needed for all modules, it is needed as a standard functional.**
I think this is a good SEO.

Examples:
https://semenivka.com.ua/
https://pokrova.pl.ua/

![good-title-link](https://user-images.githubusercontent.com/41996277/65468982-7b6caf80-de6e-11e9-9e64-59a64343122f.jpg)
![good-title-link-2](https://user-images.githubusercontent.com/41996277/65469041-abb44e00-de6e-11e9-8463-96bb7580f5d2.jpg)

**Comment by SamusUA** [comment]
If everything is done perfectly, then for the module header there should be a separate "Tab" layout of the module, with parameters:

1. Text Header Module
2. Status Header  - on/off
3. ID Header 
4. CLASS Header 
5. TAG Header  - h1, h2, div, span
6. URL Header  - System item URL
7. Target URL  - blank...
8. ICON Header  (image, SVG, JPG)
9. Position ICON Header  - after/before
10. Options - Disable link (noopener, noreferrer, nofollow)

![header-options](https://user-images.githubusercontent.com/41996277/65470731-0f417a00-de75-11e9-97e1-dd3d3b36f83c.jpg)

But this is a lot of processing :(

**Comment by ssnobben** [comment]
+1 "It is very important, especially for news sites, that the module title is a link." yes this is the problem if you not working with sites that are more than a blog  or a few pages. Thks for bringing this up and as you stated " This is necessary for all modules, but most of all for menu modules", Cheers!

**Comment by simbus82** [comment]
I like this! For me should be a features of all modules type. We could link the "title" without template/layout overrides.
Probably is enough to have a field "custom header link"
I think i have made in past hundreds of overrides to obtain this, for me it can be a default/core feature.

PS: It's the type of proposal that come from who really use the CMS, and not from who only "develop" the CMS.

**Comment by ssnobben** [comment]
And also then some tabs with different languages titles for modules so you not need to install a new language module just for changing the language title for a module that does the same thing with no need of any extra setting. 

This would also be great to have ie tabs directly on articles too so you easy could add new content languages for different languages.

**Comment by simbus82** [comment]
> And also then some tabs with different languages titles for modules so you not need to install a new language module just for changing the language title for a module that does the same thing with no need of any extra setting.
> 
> This would also be great to have ie tabs directly on articles too so you easy could add new content languages for different languages.

This require to change all of multilanguage system in Joomla, could be very nice, but now it's impossible to do in core. I think you can try some external extension to do this.

**Comment by ssnobben** [comment]
I do have 3pds that doing this already but I think this would be a massive improvement for all Joomla users

**Comment by SamusUA** [comment]
Not change all of multilanguage system in Joomla! Just add fields URL please :)

**Comment by ReLater** [comment]
> And also then some tabs with different languages titles for modules

You can use language strings as module title for multilingual purposes. If they are not translated automatically you just have to create a custom module chrome (module style) that does it for you.

**If Joomla core does not translate the titles automatically (I don't know at the moment) then I would say "should be establihed in core!"**

> PS: It's the type of proposal that come from who really use the CMS

I'm using Joomla every day since decades now and personally don't see the real benefits of this proposal. At the moment I just see additional settings in core that can be managed via 3rd plugins and, to be honest, I don't see that too many users need a feature like this one in core. That's why I have asked.

> I think this is a good SEO.

Why? Please explain what this has to do with SEO. It's just a link like others to an internal page from my point of view.

**Comment by SamusUA** [comment]
> Why? Please explain what this has to do with SEO. It's just a link like others to an internal page from my point of view.

No, this is not just a link! This link is in an important tag for the SEO (H1, H2, H3, nav or other) and large fonts! It matters, you should know about it.

**Comment by mbabker** [comment]
If you are going to claim the ability to link random blocks of text on a page is important for SEO, please provide resources to back this claim.

**Comment by SamusUA** [comment]
> If you are going to claim the ability to link random blocks of text on a page is important for SEO, please provide resources to back this claim.

Headings very often include keywords, this is a recommendation for SEO.
It’s also good to make links with keywords.
It turns out that the same heading has a double SEO meaning, isn't that good?

**Comment by pinochico** [comment]
I do not know if I understand correctly, but I have been solving module title is a link for 4 years using a customized module and custom layout in override modules.php in the template.

I do not miss this feature at all in Joomla.

But perhaps it is really very necessary.

**Comment by Scrabble96** [comment]
You could use the free RokCandy plugin. I've used it to add icons to menu titles.

There's a good demo for creating linked module titles here: [https://joomla.stackexchange.com/questions/3766/make-module-titles-linkable](url)

I've just tested it on a J3.9.12 installation and it works perfectly. No overrides required.

**Comment by SamusUA** [comment]
> Scrabble96:  You could use the free RokCandy plugin. I've used it to add icons to menu titles.

Yes it is possible. But this is not very convenient and most likely to **add load to the server**.

**Comment by ssnobben** [comment]
> 
> 
> You could use the free RokCandy plugin. I've used it to add icons to menu titles.
> 
> There's a good demo for creating linked module titles here: [https://joomla.stackexchange.com/questions/3766/make-module-titles-linkable](url)
> 
> I've just tested it on a J3.9.12 installation and it works perfectly. No overrides required.

The linke goes to Github but discussions is here https://joomla.stackexchange.com/questions/3766/make-module-titles-linkable

**Comment by SamusUA** [comment]
> ssnobben: You could use the free RokCandy plugin. I've used it to add icons to menu titles.

Thanks for the good plugin, I have not used it before!
But it has a drawback, links can become broken when the URL changes.
Linking the module title link to the menu item by ID will be more reliable.

**Comment by brianteeman** [comment]
Maintainers please make a decision here. From what I can tell this should be closed @rdeutz @wilsonge

**Comment by drmenzelit** [comment]
Maintainers are closing this. It is an individual case and not a joomla issue.

**Comment by SamusUA** [comment]
@drmenzelit, It's not Joomla problem! This is a new feature to improve the friendliness and competitiveness of the CMS. Are you going to develop the CMS or stagnate behind the WP? There have been no major changes in the standard modules for 5 years already! When will you surprise users? Is it really that difficult.
