### ISSUE TITLE
[4.0] Installing 3.x component leads to inaccessible site

### ISSUE THREAD

**Issue by marscom65** [joomla/joomla-cms#26401]
Hi,
after having installed the latest Alpha version, I successfully installed my customized 4-template. After trying to install a DJ Mega Menu which is obviously not 4-ready, I get this error:

Call to undefined method Joomla\CMS\Application\SiteApplication::isAdmin() 

![screen shot 2019-09-24 at 12 04 00](https://issues.joomla.org/uploads/1/d36433ed17b6a0fdcf90555e582228d3.png)

No chance to enter the site, the admin area or whatever. Tried on other browsers - the same.
I'm using Mac OS 10.12.6, MAMP with PHP 7.2.21 running.

**Comment by SharkyKZ** [comment]
It's expected that extensions incompatible with your Joomla! version can break your site.

**Comment by marscom65** [comment]
OK then...

**Comment by SharkyKZ** [comment]
If extension's developers claim it supports J4, you should report this issue to them https://dj-extensions.com/support-center.

**Comment by mbabker** [comment]
Just for the sake of completeness, without forcing the XML schema to go through B/C breaks with every major version and definitively block old extensions from newer Joomla versions (which would make it pretty painful for extension developers to support both the old and new versions), there isn't anything that can be done at a core level to address this.  The tools are there for extension developers to check minimum and maximum supported Joomla versions and abort installs, but it relies on them to do the work to make it happen.
