### ISSUE TITLE
[4.0]trashing category with item trashes with error

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#26404]
### Steps to reproduce the issue
create article in uncategorized category.
trash uncategorized category.

### Expected result
category is NOT trashed.

### Actual result
![image](https://user-images.githubusercontent.com/1850089/65537588-1eebad80-decb-11e9-9851-2df6efb4a267.png)

### System information (as much as possible)
[systeminfo-2019-09-24T17_59_49+00_00.txt](https://github.com/joomla/joomla-cms/files/3648750/systeminfo-2019-09-24T17_59_49%2B00_00.txt)

**Comment by richard67** [comment]
Well I think it is desired that the "Uncategorized" category can't be trashed, someone please correct me if I'm wrong.

But of course one would expect a meaningful error message for this case.

**Comment by richard67** [comment]
Hmm, on 3 it works, trashing that category when it contains one article, so I was wrong with my comment above, it seems.

**Comment by richard67** [comment]
But here on my current 4.0-dev I get an error different to the screenshot in the description above:

> Argument 2 passed to Joomla\Component\Finder\Administrator\Indexer\Result::addNestedTaxonomy() must implement interface Joomla\CMS\Tree\ImmutableNodeInterface, null given, called in /home/richard/lamp/public_html/joomla-cms-4.0-dev/plugins/finder/content/content.php on line 322

**Comment by Quy** [comment]
@richard67 Your issue is fixed in PR #26235

**Comment by N6REJ** [comment]
@richard67 I probably worded the title badly.. maybe @franz-wohlkoenig can think of better title.

**Comment by infograf768** [comment]
After unpublishing the smartsearch plugins (so that I do not I have the same error as @richard67 , solved by #26235 ), I do not have the same result as @N6REJ .

The category is trashed without error.

**The expected result is that the category IS trashed, contrary to the description of the issue.**

It is only when the category contains an item, has been trashed and when using Empty Trash that we would have an error/alert stating that the category can't be deleted because it contains an item.

Closing this as it looks like related to a bad/corrupted installation.

**Comment by infograf768** [comment]
I reopen.
After correcting with #26235 and enabling the smartsearch plugins, I get the error stated by @N6REJ 

Note: Tested with blog and multilingual sample data on.

**Comment by infograf768** [comment]
Tested without sample data and using https://github.com/joomla/joomla-cms/pull/26235
Same issue:
The category is trashed but I get the `Out of range value for column 'state' at row 1` error.

Disabling the smartsearch plugins solves the error

**Comment by infograf768** [comment]
@SharkyKZ
Please look at this.

**Comment by SharkyKZ** [comment]
Test PR #26235 please.

**Comment by infograf768** [comment]
> Test PR #26235 please.

👍
