### ISSUE TITLE
Add search plugins to Codemirror on template file editing

### ISSUE THREAD

**Issue by AndNovAtor** [joomla/joomla-cms#26411]
Is possible to add Codemirror search plugins? https://codemirror.net/demo/search.html

If it isn't possible to add for Joomla 3.*, is it maybe possible to add for Joomla 4.0?

P.s. - search plugin js files is exist in addon directory in Codemiror dir in site 'media' dir, so it's simply not "loaded" ("copypaste" into addons.js)... isn't it?

**Comment by brianteeman** [comment]
Took a long time - sorry
Please test #37130
