### ISSUE TITLE
Addition of module

### ISSUE THREAD

**Issue by Laurentdubois59** [joomla/joomla-cms#26414]
Hello
In the Backoff![screen shot 2019-09-26 at 11 59 25](https://issues.joomla.org/uploads/1/ab8fb17cc4d38d03a07c43748418c754.jpg)ice
When we want to add a module with the + and we went before on modue administrator, we created an administrator module instead of a site module

### Steps to reproduce the issue

-> contents
  ->Administrator modules

We go out, do other things and then we go back to content then this time the + side of site Modules to add a new module for the site, it creates a module for administration

**Comment by SharkyKZ** [comment]
Test PR #26415 please.

**Comment by alikon** [comment]
please test #26415<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26414">issues.joomla.org/tracker/joomla-cms/26414</a>.</sub>
