### ISSUE TITLE
[4.0] Is sample data plugin [already] works on Joomla installation?

### ISSUE THREAD

**Issue by AndNovAtor** [joomla/joomla-cms#26412]
### Steps to reproduce the issue

- Make apache server with apache 2.4 x64 + php 7.2 x64 on Windows [10 x64]
- Install Joomla 4.0 Alpha 11
- After installation press "Customize Installation"
- Press "Skip" to skip language installation
- [See the first screenshot]
![image](https://user-images.githubusercontent.com/3628514/65672422-b24eeb00-e051-11e9-99b1-b0d63fefdbc9.png)
Press _"INSTL_SITE_INSTALL_SAMPLE "_

### Expected result

Some sample data generation

### Actual result

_JLIB_APPLICATION_ERROR_VIEW_NOT_FOUND_
[See the second screenshot]
![image](https://user-images.githubusercontent.com/3628514/65672503-df030280-e051-11e9-82de-2139fce1fa7d.png)

### System information (as much as possible)

Windows 10 x64 1903
apache 2.4 x64
php 7.2 x64
mysql 5.7 x64

### Additional comments
I remember that sample data was "broken" for first Joomla 4 alpha versions....
Also, sorry if my issue is [over-]duplicate

**Comment by alikon** [comment]
can you check against the latest nightly build https://developer.joomla.org/nightly-builds.html

**Comment by AndNovAtor** [comment]
> can you check against the latest nightly build https://developer.joomla.org/nightly-builds.html

Yes, wait a minute

**Comment by alikon** [comment]
no hurry take your time 😄

**Comment by AndNovAtor** [comment]
> no hurry take your time 😄

I have time NOW ;)

**Comment by AndNovAtor** [comment]
> can you check against the latest nightly build https://developer.joomla.org/nightly-builds.html

Mmm, after press "Skip" on language customization Sample data generation was NOT shown. As planned?
![image](https://user-images.githubusercontent.com/3628514/65677116-b54dd980-e059-11e9-8f90-a1f3e121aeee.png)


![image](https://user-images.githubusercontent.com/3628514/65677123-b979f700-e059-11e9-888d-789383cb7085.png)


![image](https://user-images.githubusercontent.com/3628514/65677134-bbdc5100-e059-11e9-9be3-ad634a294119.png)

**Comment by AndNovAtor** [comment]
Btw, after press "Customize installation", after "Skip", there no "Remove installation folder". As planned?
This button IS in Joomla 3.* before AND after customize installation progress.
If it wasn't planned do I need to create separate issue?
P.s - of course I can reload /installation page and then press "Remove installation folder"

**Comment by brianteeman** [comment]
Sorry no one replied to you

Sample data is not part of the installation process in joomla 4 - instead there are no dedicated _buttons_ on the dashboard to install the data

**Comment by ReLater** [comment]
> there are no dedicated buttons

A small typo.

there are **_now_** dedicated buttons

**Comment by wilsonge** [comment]
@AndNovAtor Bug of the skip button fixed with https://github.com/joomla/joomla-cms/commit/ce012bf15ac53a9e1c40bdf045e1b1a2887fab7f should come up in the nightlies generated on sunday

**Comment by Quy** [comment]
@wilsonge There are duplicate buttons.

![installation](https://user-images.githubusercontent.com/368084/65818642-30350280-e1c8-11e9-8cd9-51453318eac3.jpg)

**Comment by Quy** [comment]
Please test PR #27186<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26412">issues.joomla.org/tracker/joomla-cms/26412</a>.</sub>
