### ISSUE TITLE
[4.0] Cassiopeia: attempting to edit existing article within Menu setup causes 403 error

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#26417]
### Steps to reproduce the issue
Create new menu item of type 'Single Article' using 'Create' to create a new article
Save and close the item
Open the item again
Click on 'Edit' next to Article Name

### Expected result
The article editor will open

### Actual result
403 Forbidden error message.
Close, Save & Close and Save buttons do not work.
Escape does not work
The only way to get out of this is to close the whole tab
![403 Forbidden](https://user-images.githubusercontent.com/36987494/65697218-79733e00-e072-11e9-8d20-f7e1720476de.jpg)

### System information (as much as possible)
J4 Alpha 12 Nightly update 2019-09-20
PHP 7.2
### Additional comments
Same result on Firefox and Chrome

**Comment by SharkyKZ** [comment]
This is coming from your server's firewall.

**Comment by Scrabble96** [comment]
> 
> 
> This is coming from your server's firewall.

@SharkyKZ You were right. 

The domain I am testing on is on a shared server (smarthosting.co.uk / Krystal Hosting) so I have no control over the firewall. They tweaked the modsec settings and it now works. 

I'm explaining this in case anyone else has the same problem and comes looking for an answer.
