### ISSUE TITLE
[4.0] COM_WORKFLOW_DEFAULT_WORKFLOW not translated

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#26432]
### Steps to reproduce the issue
Go to Users > Manage
Click Permissions icon for admin. 

### Actual result
![workflow](https://user-images.githubusercontent.com/368084/65825977-51cad400-e232-11e9-980e-696c3f95a381.jpg)

**Comment by SharkyKZ** [comment]
Duplicate report #23794.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26432">issues.joomla.org/tracker/joomla-cms/26432</a>.</sub>
