### ISSUE TITLE
Smart search - click search

### ISSUE THREAD

**Issue by velyar** [joomla/joomla-cms#26436]
Joomla 3.7.5 modul smart search.

Search only works by pressing Enter again. Why is there no search setting when clicking mouse on the dropdown variants search?

How can this be done on their own? Have a ready-made solution?

**Comment by simbus82** [comment]
Hi @velyar, before trying to find a solution for a problem about Joomla, i think you should update Joomla to the latest version. Your version (3.7.5) is 2 years old!

**Comment by velyar** [comment]
> Hi @velyar, before trying to find a solution for a problem about Joomla, i think you should update Joomla to the latest version. Your version (3.7.5) is 2 years old!

Now I installed the latest version 3.9.12. The result is the same.

**Comment by Quy** [comment]
I don't fully understand your issue. Are you referring to the suggested terms? If yes, then it is working on my end. Can you reproduce on a clean installation? 

![search](https://user-images.githubusercontent.com/368084/65916898-0aa42680-e38b-11e9-91bd-0d8d67a4b4d2.jpg)

**Comment by esedic** [comment]
You have an option in Smart Search module to show/hide Search button, check it out.

**Comment by Quy** [comment]
If you need further assistance, please post in [Joomla forum](https://forum.joomla.org/).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26436">issues.joomla.org/tracker/joomla-cms/26436</a>.</sub>

**Comment by simbus82** [comment]
Please reopen @Quy, i have found the bug!
@velyar, you were right!
Only now have I understood the problem you exposed.
I've tried it and it happens on all my sites!

In a desktop environment:

1. Starts writing in the search field
2. Autocomplete starts to show suggested "keywords"
3. Move down the mouse and click on a suggested "keyword" inside the autocomplete list
4. Nothing happen!
5. Search field now is populated with suggested "keyword"
6. I have to click "search" button or do an ENTER
7. Now i see the search results page.

This is a really annoying UX problem.
**Steps 4, 5 and 6 should not exist.** 

When i click (step 3) on a suggested "keyword", i need to be taken to search results page!
This happen in a search module and also in the search component view.

**Comment by velyar** [comment]
> When i click (step 3) on a suggested "keyword", i need to be taken to search results page!
> This happen in a search module and also in the search component view.
Thank you, you understood me correctly.

**Comment by velyar** [comment]
> Please reopen @Quy, i have found the bug!
> @velyar, you were right!
> Only now have I understood the problem you exposed.
> I've tried it and it happens on all my sites!
> 
> In a desktop environment:
> 
> 1. Starts writing in the search field
> 2. Autocomplete starts to show suggested "keywords"
> 3. Move down the mouse and click on a suggested "keyword" inside the autocomplete list
> 4. Nothing happen!
> 5. Search field now is populated with suggested "keyword"
> 6. I have to click "search" button or do an ENTER
> 7. Now i see the search results page.
> 
> This is a really annoying UX problem.
> **Steps 4, 5 and 6 should not exist.**
> 
> When i click (step 3) on a suggested "keyword", i need to be taken to search results page!
> This happen in a search module and also in the search component view.

Thank you, you understood me correctly.

**Comment by SharkyKZ** [comment]
This is standard behavior of the autocomplete library used here.

**Comment by simbus82** [comment]
I can imagine.
It is a (sneaky) annoying problem in terms of usability (no autocomplete works like this in the world), it becomes very very annoying on mobile.

It will probably be enough to force the search, by clicking on the keyword.
The library will no longer be updated (I think), so maybe it is worth "fixing" it.

PS: if we do a PR for the 3.x ... will this be accepted, or is it wasted time?

**Comment by brianteeman** [comment]
It has been this way for over 7 years - maybe 10

**Comment by simbus82** [comment]
@brianteeman It's never too late to improve or correct past mistakes.

**Comment by brianteeman** [comment]
True but it gives an impression on just how "annoying" it really is

**Comment by velyar** [comment]
It surprises me why such an obvious and logical function has not yet been implemented :)

**Comment by Hackwar** [comment]
Ok, I looked into this again and we actually have this behavior implemented. Smart Search differentiates between the simple and the advanced form for searches and in case of the simple form, it directly submits the form upon selecting the suggestion. However, when you have an advanced form, so with additional fields for taxonomies, etc., then the form is not submitted directly. 

Long story short: This issue can be closed, since we have this at least since 4.0 😃
