### ISSUE TITLE
Pagination not working correct in blog front-end

### ISSUE THREAD

**Issue by peterwouda** [joomla/joomla-cms#26441]
On my website www.friesjournaal.nl I hundreds of articles that are published in blog-form with 18 articles per page.

I expect when I click on a page-number in the pagination that the articles of that page are shown. 

The actual result is that after clicking on some pages (for example 2, 4, 6, 8 )  the selected page is 1, 3, 5 and 7. I looks like when clickin on page 2, the blog starts with article number 13 instead of 19 (because I have an 18 articles blogpage)

The problem has been there for some Joomla-versions now (I hoped that it would solve with some version, but that is not the case). I use the most recent Joomla-versie now (3.9.12)

**Comment by brianteeman** [comment]
Please check the menu item to see what are the settings for 
![image](https://user-images.githubusercontent.com/1296369/66038887-4534cd00-e50b-11e9-8631-e67a85386549.png)

Please check with one of the default templates to make sure it is not a problem with the template

**Comment by peterwouda** [comment]
Thanks Brian for the reply. No matter setting is used in the menu, the problem is always there. Even in the Prostar-template. 
But I found the troublemaker: it is the Artio JoomSEF component that caused the pagination-problem. 
Disabeling JoomSEF made the pagination work again. I will contact Artio JoomSEF. 

![afbeelding](https://user-images.githubusercontent.com/18345618/66042877-fd6b7100-e51d-11e9-93e0-0f9c8fd73616.png)

Thanks,
Peter

**Comment by brianteeman** [comment]
Please close this issue as it is not core related
