### ISSUE TITLE
[4.0] Extension installation confirmation is out of view.

### ISSUE THREAD

**Issue by hennysmafter** [joomla/joomla-cms#26448]
### Steps to reproduce the issue
Install the latest J4 and try to use the "Install from Web" button for any extension. I used Akeeba.
Then click on [Install...]

### Expected result
I expected to receive a modal window with the confirmation. 

### Actual result
As at first, I did not realize I needed to scroll down and therefore thought it was not working at all. Then I realized that it needed a confirm so I went looking for it and found it at the bottom of the page. I suspect this is going to be very confusing for new Joomla! users.

### System information (as much as possible)
PC, Win10 v1803 / 17134.1006, Chrome Version 77.0.3865.90 (Official Build) (64-bit), Latest Joomla 4 build (from today), PHP 7.3

### Additional comments
Installation from the web is, I believe, unavailable in the current J4 builds but I am not sure if the confirmation message has anything to do with that. If it is then just close the issue, please.

**Comment by mbabker** [comment]
Maybe someone will finally finish #19429 but some of the JavaScript was prematurely disabled without replacements which is why it looks broken.

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/28992

**Comment by alikon** [comment]
please test  #28992
