### ISSUE TITLE
[4.0] Missing css class

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26449]
![image](https://user-images.githubusercontent.com/1296369/66043484-2d634600-e517-11e9-913e-5dc66433bf01.png)

The code is looking for a btn-inverse that doesn't exist

**Comment by Quy** [comment]
Please test PR #26452<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26449">issues.joomla.org/tracker/joomla-cms/26449</a>.</sub>
