### ISSUE TITLE
[4.0] Show changelog is not shown in update view

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#26450]
### Steps to reproduce the issue
I like to use the change log, that was introduced in this PR: https://github.com/joomla/joomla-cms/pull/24026

1. Install an extension that uses change log and update server. I created my own extension for this. If you like you can test with this extension: https://github.com/astridx/boilerplate/releases/tag/v1.0.0

2. Make sure, that in the manage view the change log is shown

![Extensions  Manage   test   Administration](https://user-images.githubusercontent.com/9974686/66044610-3c032a80-e522-11e9-9629-28e03c54d494.png)

3. Create a new version of this extension and open the update view. In my case the update version is version 1.0.1: https://github.com/astridx/boilerplate/releases/tag/v1.0.1

### Expected result
I can open the change log in the update view.

### Actual result

 Open the update view and see, that there is N/A in the column for the change log
![Extensions  Update   test   Administration(1)](https://user-images.githubusercontent.com/9974686/66044755-9308ff80-e522-11e9-93af-92fcd9394923.png)

### System information (as much as possible)
Current Joomla 4.0 Branch on Ubuntu. Browser: Firefox

### Additional comments
Unfortunately, I can not test with the original files from PR https://github.com/joomla/joomla-cms/pull/24026, because they are not available.

**Comment by brianteeman** [comment]
The problem is in your code not in joomla ;)

You have set the update url to be https://github.com/astridx/boilerplate/blob/tutorial/changelog.xml
But that is the full github html page

You need to change that to be https://raw.githubusercontent.com/astridx/boilerplate/tutorial/changelog.xml

![image](https://user-images.githubusercontent.com/1296369/66047139-2b9d8080-e51f-11e9-82c2-d7584202fc55.png)

**Comment by astridx** [comment]
@brianteeman Thank you. You're right. I could have seen that myself. Sorry. 
But. In the zip of the old version , the URL was right. Only in the zip of the new version, the URL was wrong. I did not expect that. Because the URL was recognized by the manager, I was sure of an error in the update view.

**Comment by astridx** [comment]
Now I have corrected the zip. The problem still exists. When I update the change log is not displayed. But: I can see it after the update.

**Comment by brianteeman** [comment]
what is the value of the changelogurl field in the #__extensions database table

**Comment by astridx** [comment]
@brianteeman Thank you for helping. 
The changelogurl is:  
https://raw.githubusercontent.com/astridx/boilerplate/tutorial/changelog.xml
In the manage view I can open the change log. The problem is in the update view
![localhost   localhost   joomla_db4   sdmgh_extensions   phpMyAdmin 4 9 0 1](https://user-images.githubusercontent.com/9974686/66069423-a088ae80-e54f-11e9-99bc-4034cac6400a.png)

**Comment by brianteeman** [comment]
> When I update the change log is not displayed

Nothing is being displayed in updates view
![image](https://user-images.githubusercontent.com/1296369/66070496-556b9d00-e549-11e9-950b-a915fd504f21.png)

This is the expected behaviour as there is no update to the version that is installed defined in your update server.

**Comment by astridx** [comment]
@brianteeman 
I did not express myself well. I mean, when have installed version 1.0.0 and I check for updates. In this case I see this:
![Extensions  Update   test   Administration(1)](https://user-images.githubusercontent.com/9974686/66044755-9308ff80-e522-11e9-93af-92fcd9394923.png)
But I should see a link in the column change log to the change log for version 1.0.1.
So it is explained in #24026
@roland-d That's correct, right?

**Comment by brianteeman** [comment]
you dont have a changelog url defined in your update xml so the #__updates changelogurl field never gets populated

The code is working correctly as far as I can tell. The problem is the documentation is missing

**Comment by roland-d** [comment]
@brianteeman Which documentation is missing?
https://docs.joomla.org/Adding_changelog_to_your_manifest_file

**Comment by brianteeman** [comment]
Grrrh, search sucks on that site.

@astridx the docs confirm what I wrote

**Comment by astridx** [comment]
I am ashamed, but I have seen the entry in `update.xml ` just now in JDoc. Before I did not see it. Many thanks for your help and sorry for the wrong error report.

**Comment by brianteeman** [comment]
Happens to all of us
