### ISSUE TITLE
[4.0] codemirror custom element

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26455]
### Steps to reproduce the issue
1. Make sure that joomla is installed in a subdirectory
2. Go to a page that loads the codemirror editor. eg the template file editor
3. Check that codemirror loads
4. Go to the codemirror plugin
5. Save and close without making any changes
6. repeat steps 2 & 3

### Expected result
codemirror loads

### Actual result
codemirror fails

### Inspect BEFORE codemirror fails
![image](https://user-images.githubusercontent.com/1296369/66085899-6678d600-e56a-11e9-99ef-b9e1836d0c76.png)

### Inspect source AFTER codemirror fails

![image](https://user-images.githubusercontent.com/1296369/66085781-17cb3c00-e56a-11e9-9a41-5b64af161809.png)

## Comments
I suspect the problems origin comes from 
https://github.com/joomla/joomla-cms/blob/7a9459004b5c49cae0ce9dfc8310e61f4597d416/build/media_source/plg_editors_codemirror/js/joomla-editor-codemirror.w-c.es6.js#L13-L21

### Note 
To reset the plugin to the values before saving 
```
INSERT INTO `h6nap_extensions` (`package_id`, `name`, `type`, `element`, `changelogurl`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `checked_out`, `checked_out_time`, `ordering`, `state`, `note`) VALUES (0, 'plg_editors_codemirror', 'plugin', 'codemirror', NULL, 'editors', 0, 1, 1, 1, '{"name":"plg_editors_codemirror","type":"plugin","creationDate":"28 March 2011","author":"Marijn Haverbeke","copyright":"Copyright (C) 2014 - 2017 by Marijn Haverbeke <marijnh@gmail.com> and others","authorEmail":"marijnh@gmail.com","authorUrl":"http:\\/\\/codemirror.net\\/","version":"5.40.0","description":"PLG_CODEMIRROR_XML_DESCRIPTION","group":"","filename":"codemirror"}', '{"lineNumbers":1,"codeFolding":1,"markerGutter":1,"lineWrapping":1,"activeLine":1,"selectionMatches":1,"matchTags":1,"matchBrackets":1,"autoCloseTags":1,"autoCloseBrackets":1,"keyMap":"","fullScreen":"F10","theme":"","activeLineColor":"#a4c2eb","highlightMatchColor":"#fa542f","fontFamily":"0","fontSize":13,"lineHeight":1.2,"scrollbarStyle":"native","preview":null}', 0, '0000-00-00 00:00:00', 1, 0, '');
```

**Comment by SharkyKZ** [comment]
Test PR #25591 please.

**Comment by brianteeman** [comment]
yes that fiex it
