### ISSUE TITLE
Script is running while making the product in Joomla 3.9.12

### ISSUE THREAD

**Issue by Ishanwebkul** [joomla/joomla-cms#26457]
### Steps to reproduce the issue

1. Login to back-end from the admin credentials.
2. Now click on VirtueMart and go to products.
3. Click on new button for making the new product.
4. In the '**Product Name**' field enter the script and click on save button.
5. When you click on cancel button the script will run which you have entered in the field.
6. After saving the product your product will be shown but you will be unable to click or open it.
https://prnt.sc/pea3wa

### Expected result

If we have entered some script in the product name field and click on save button than it should some error and tell you can't save the name with the tags in it.

### Actual result

[Screencast 2019-10-03 15:53:01.mp4.zip](https://github.com/joomla/joomla-cms/files/3685560/Screencast.2019-10-03.15.53.01.mp4.zip)

### System information (as much as possible)

Ubuntu 16.04 LTS

### Additional comments
 In all this type of fields in Joomla we are able to save the script and run.

**Comment by SharkyKZ** [comment]
This is a VirtueMart issue, not a Joomla issue. You should report this to VM developers.

**Comment by SharkyKZ** [comment]
Closing as non-core issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26457">issues.joomla.org/tracker/joomla-cms/26457</a>.</sub>
