### ISSUE TITLE
[4.0] $autocomplete sanity check

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26459]
Unless I am missing something then this docblock in all fields is wrong
https://github.com/joomla/joomla-cms/blob/bc42bb1e43d96334c38222dbe49b83f898413f2a/layouts/joomla/form/field/password.php#L20

All we ever do is this
https://github.com/joomla/joomla-cms/blob/bc42bb1e43d96334c38222dbe49b83f898413f2a/layouts/joomla/form/field/password.php#L72

Which means that we can never have any value for autocomplete in the xml other than 'off'

You can see this by changing the value for autocomplete here to anything else and instead of the autocomplete being output with the new value it is removed.

https://github.com/joomla/joomla-cms/blob/bc42bb1e43d96334c38222dbe49b83f898413f2a/administrator/components/com_users/forms/user.xml#L20-L30

Autocomplete has a lot of useful values that we could/should be using see https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

For example `autocomplete=off` really doesn't do anything on password fields. Instead we should be using `autocomplete="new-password"`

It looks to me that it can be _fixed_ by changing the code to
`$autocomplete ? '' : 'autocomplete="' . $autocomplete .'"',`

And autocomplete is not the same as autofill
> Chrome will still respect this tag for autocomplete data, it will not respect it for autofill data

But I am probably missing something
cc @HLeithner @wilsonge @mbabker

**Comment by wilsonge** [comment]
Your solution sounds correct to me

**Comment by brianteeman** [comment]
And I am not missing something based on the docblock?

**Comment by wilsonge** [comment]
I *think* it was built to disable autocomplete on password fields back in the day. i vaguely recall buggy browser behaviour back in the early html5 browser days.

**Comment by wilsonge** [comment]
But i don't see any reason we can't expand the scope to include custom values there

**Comment by brianteeman** [comment]
It is the same in all fields not just the password field

**Comment by Quy** [comment]
See PR #26467<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26459">issues.joomla.org/tracker/joomla-cms/26459</a>.</sub>
