### ISSUE TITLE
[4.0] com_mails select template

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26477]
It is absolutely not logical or clear that to edit the template you need to click on the language to select the template

I would expect to be able to click on the template title

![image](https://user-images.githubusercontent.com/1296369/66209972-95995f80-e6b0-11e9-839c-427f27ef3a11.png)

![image](https://user-images.githubusercontent.com/1296369/66209978-992ce680-e6b0-11e9-8d6a-a890ef65c905.png)

**Comment by Quy** [comment]
It is definitely not obvious to click the language to edit. Make the title clickable like everywhere else.

**Comment by brianteeman** [comment]
Unfortunately it can't be because it uses a non standard way of dealing with languages - no idea why though

**Comment by brianteeman** [comment]
Closed as solved elsewhere by @Hackwar - thanks
