### ISSUE TITLE
[4.0] Error after testinstall of extension

### ISSUE THREAD

**Issue by stell** [joomla/joomla-cms#26479]
After doing a test install of a package (working under J3) containing a component, modules and plugins the system stops working (front and backend) and outputs:

`Error: Unknown asset "template.atum.ltr": Call to a member function getWebAssetManager() on null`

It's the latest Alpha12

**Comment by regexaurus** [comment]
@stell I'm curious why you closed this issue...?
I encountered a similar error today, while attempting to install the Gantry 5 framework (v. 5.4.31) on a clean Joomla 4 alpha 12 site:

Error: Unknown asset "template.atum.ltr": Call to undefined method Joomla\CMS\Application\AdministratorApplication::isSite()

And now when attempting to access the front end:

Error: Call to undefined method Joomla\CMS\Application\SiteApplication::isSite(): Call to undefined method Joomla\CMS\Application\SiteApplication::isSite()

**Comment by stell** [comment]
Has nothing to do with my question, but:
`isSite()` is depricated in J4 Use isClient('site') instead.  Is Gantry 5 Joomla 4 compatible?

**Comment by regexaurus** [comment]
Apparently not yet... RocketTheme/Gantry developers are preparing for Joomla 4 compatibility.
I restored front/backend access by modifying the extensions table, setting the _enabled_ field to 0, for plg_system_gantry5, plg_quickicon_gantry5, mod_gantry5_particle, Gantry 5 Framework, gantry5_nucleus, com_gantry5, pkg_gantry5
Disabling all of those was probably unnecessary. plg_gantry5_preset was already disabled (default?)
