### ISSUE TITLE
[4.0] com_mails empty style

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26476]
https://github.com/joomla/joomla-cms/blob/8109142b9eb82fb88526316a9092f5eba12d78fd/administrator/components/com_mails/tmpl/templates/default.php#L69

What is the purpose of this line. Unless i am reading it wrong all it will do is to to create an empty style (  `style="">` )which makes no sense to me.

**Comment by brianteeman** [comment]
anyone?

**Comment by richard67** [comment]
I have no idea what this shall be good for, am same confused as everybody else who sees this piece of code.

**Comment by SharkyKZ** [comment]
It's meant to indicate that a template for a specific language exists.

**Comment by brianteeman** [comment]
closed see #27326
