### ISSUE TITLE
user type custom field not saving in subform

### ISSUE THREAD

**Issue by awdhaan** [joomla/joomla-cms#26484]
### Steps to reproduce the issue
I created a module with the following field:
`<field name="items" type="subform" formsource="<path>/forms/items.xml" multiple="true" min="1" max="10" groupByFieldset="true" layout="joomla.form.field.subform.repeatable-table" label="users" />
`

and in the items.xml:
`<?xml version="1.0" encoding="UTF-8"?><form><fieldset name="item"><field name="user_id" type="user" label="user" filter="unset" /></fieldset></form>`

When selecting a user through the standard control, the user is added to the field. When saving the module instance, the values for each user field are empty again.

### Expected result
The selected user value for each item should be saved upon saving the module

### Actual result

When saving the module instance, the values for each user field are empty again.

### System information (as much as possible)
3.9.12
PHP 7.3

### Additional comments
This used to work in previous versions of Joomla

**Comment by richard67** [comment]
@awdhaan It seems there is some information missing in your description. After the sentence "I created module with the following field" I would expect information about the field, and after the next sentence "and in the items.xml:" I would expect some information about the XML. Can it be that there are 2 screenshots missing?

**Comment by awdhaan** [comment]
> @awdhaan It seems there is some information missing in your description. After the sentence "I created module with the following field" I would expect information about the field, and after the next sentence "and in the items.xml:" I would expect some information about the XML. Can it be that there are 2 screenshots missing?

Thanks. I forgot to quote the xml in the description. It's now in there.

**Comment by SharkyKZ** [comment]
You need to change `unset` filter to something else. `unset` removes the value. This didn't happen before because until 3.9.7 subform did not support filtering and validation.

**Comment by awdhaan** [comment]
I feel a bit awkward not having noticed this before @SharkyKZ , thanks! this obviously
 works!
