### ISSUE TITLE
[4.0] toolbar on mobile needs some attention

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26486]
Thoughts?

### Before
![before](https://user-images.githubusercontent.com/1296369/66262105-ebb1f400-e7d1-11e9-93bc-e24eff6aa7bf.gif)

### After
![after](https://user-images.githubusercontent.com/1296369/66262110-02f0e180-e7d2-11e9-8fa3-a67cb5c1e674.gif)

**Comment by Fedik** [comment]
That looks much better to me.
maybe also make "Toolbar" button itself 100%

**Comment by brianteeman** [comment]
Or perhaps change the button to a burger menu?

![image](https://user-images.githubusercontent.com/1296369/66323187-4dca4080-e91b-11e9-8ebd-4b1e53d82357.png)

**Comment by Fedik** [comment]
It looks nice from screenshot, to me.
much better than "toolbar" button :)

**Comment by brianteeman** [comment]
See #26513
