### ISSUE TITLE
Wrong Latest Joomla Version

### ISSUE THREAD

**Issue by twister65** [joomla/joomla-cms#26487]
### Steps to reproduce the issue
Have Joomla 3.9.10 installed.
Log in as administrator.
![ControlPanel](https://user-images.githubusercontent.com/26852967/66265322-ed50db80-e814-11e9-99ff-9e50f6c52fd4.png)

### Expected result
Have Joomla 3.9.12 available.

### Actual result
The latest Joomla version is 3.9.11 with update package URL to Joomla 3.9.12.
![LatestJoomlaVersion](https://user-images.githubusercontent.com/26852967/66265314-cdb9b300-e814-11e9-9026-3e9fb04ae80a.png)

**Comment by alikon** [comment]
cannot confirm 
![Screenshot from 2019-10-06 09-28-07](https://user-images.githubusercontent.com/181681/66265745-b9c57f80-e81b-11e9-8005-75085663f5eb.png)

maybe you have a cached/old  update site item for Core ... can you check if is it pointing to the current manifest https://update.joomla.org/core/list.xml

**Comment by twister65** [comment]
Yes it is, but in the #__updates table I have got 3.9.11 version:
![__updates](https://user-images.githubusercontent.com/26852967/66266097-aa950080-e820-11e9-919b-0d9a6fb0f2a5.png)

https://github.com/joomla/joomla-cms/blob/163234b9a6fb324c8ef627770d77a031bd2923e0/administrator/components/com_joomlaupdate/models/default.php#L163-L166

**Comment by twister65** [comment]
After clearing cache in 'Extensions: Update', it works now.

**Comment by twister65** [comment]
Are you supposed to clear the cache to have correct update informations ?

**Comment by alikon** [comment]
i do it  as a default ....  not sure if it is documented somewhere in jdocs

**Comment by SharkyKZ** [comment]
This should be solved in 3.9.12 with #25923.

**Comment by twister65** [comment]
Unfortunately, PR #25923 does not solve this issue.

**Comment by ChristineWk** [comment]
@twister65 

of course, it will be solved - after having 3.9.12 for next version.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26487">issues.joomla.org/tracker/joomla-cms/26487</a>.</sub>

**Comment by twister65** [comment]
Not at all, once PR #25923 has been applied, it says that: 

> You already have the latest Joomla version, 3.9.10.

![UpToDate](https://user-images.githubusercontent.com/26852967/66266833-86d6b800-e82a-11e9-8d51-2c47ba4a73f5.png)

**Comment by ChristineWk** [comment]
PR #25923 ist merged for 3.9.12

3.9.10 / 3.9.11 Go to Extension > Manage > Update > Clear Cache

**Comment by twister65** [comment]
Click on 'Check for Updates' button is required.

**Comment by ChristineWk** [comment]
No. In the past, we had often this problem, concerning of: https://github.com/joomla/joomla-cms/issues/25920. Just give it a try - see above.

**Comment by twister65** [comment]
Considering you are an advertised administrator (like @alikon) with good habits, it works. What a shame for common joomla users like me !

**Comment by ChristineWk** [comment]
Olivier,

oh No, I'm not an advertised administrator - just a normal User only. Infos, experiences etc. as active supporter in German Joomla Forum - that's all. :-)

I don't know anything of e.g. PostgreSQL etc. as you are working as developer with your important repositories! Thanks you and all other programmers for your work and helps.

**Comment by zero-24** [comment]
@twister65 please send me a backup of the site including the database so I can take a look to this issue to tobias.zulauf[AT]communiy.joomla.org Thanks!

**Comment by N6REJ** [comment]
If they are using 3.9.10 it will still throw the 3.9.11 update but gives 3.9.12 report.  Quite frankly I see it as a non-issue was it's already fixed with 3.9.11 @twister65

**Comment by twister65** [comment]
"Good habits" before update:
1. Clear cache in 'Extensions: Update'
2. Apply PR #25923 and click on 'Check for Updates' button

@N6REJ , It is solved on 3.9.12 with the "good habit" 2.
@zero-24 , have you received my email ? It is an Akeeba Backup archive with postgreSQL database (just launch kickstart).

**Comment by zero-24** [comment]
Thanks @twister65  Yes i have got the mail but i havn't had a chance yet to review it. From a first guess can you please try this patch here: https://github.com/joomla/joomla-cms/pull/25847/files this is also included in 3.9.12 in response to this kind of issues.
