### ISSUE TITLE
[4.0] Mail configuration component

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26489]
Sorry but this language filter makes no sense to me at all. 

If I see this 
![image](https://user-images.githubusercontent.com/1296369/66261783-aee2fe80-e7cb-11e9-9077-7be7c75df214.png)

And then filter on EN and see this
![image](https://user-images.githubusercontent.com/1296369/66261804-084b2d80-e7cc-11e9-9669-f2688e3fd9ac.png)

it makes no sense to me as a user why there is no english records displayed

When I look in the database then I can see the reason (and it almost makes sense technically) but then the UI needs to be different.

In addition I would expect from the ui that even if I understood why there was no EN record (yet) then there would at least be an ALL record

![image](https://user-images.githubusercontent.com/1296369/66261846-7ee82b00-e7cc-11e9-845a-bc0806f4f293.png)

In fact is it ever possible to have an ALL record?

Or does it mean that ALL will display all the records that exist that have a specified language ie EN and FR and ES

If it is the latter then that's not correct as it is completely different to the rest of Joomla where ALL in a language filter means a record that is for all languages.

Either way it is wrong here

**Comment by Hackwar** [comment]
I'm open for better suggestions here. The goal was to not have a row in the table per language and lots of confusing entries in general.

It's a pity that this is brought up AFTER the original PR has been merged and not in the year before that, where that PR was waiting for reviews.

**Comment by brianteeman** [comment]
I don't build multilingual sites so I never spotted it. 

I still don't know if it's a bug or by design.

Not having a consistent UI will always be a bad ux

**Comment by Giuse69** [comment]
I would keep it consistent with the rest of Joomla:
"All" filter selects only items with language = *
"No filter" shows every item, whichever language it has

**Comment by Hackwar** [comment]
Proposal for the listview and how to make this better: (I'm only listing the things that would change)

- The language column only lists those languages, that you have a translation for this template. So if you have 5 content languages and created templates for 2 of them for a template ID, then that column for that row would contain just those 2 languages.
- Clicking on the title of a template opens a "dropdown" (styling to be decided) and that contains a list of "Create/Edit template for [language]", signifying if the language already have a template or not.

I think that should solve a lot of the confusion. Question: Do you think that would be good enough? It would be rather easy to implement this.

**Comment by Hackwar** [comment]
The PR linked here has been merged. Is this still an issue or can we close this, thus solving a beta blocker?

**Comment by jwaisner** [comment]
Increasing priority as per guidelines for beta-blockers.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26489">issues.joomla.org/tracker/joomla-cms/26489</a>.</sub>
