### ISSUE TITLE
[4.0] http headers

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26501]
### Steps to reproduce the issue
in the content security policy go to the options and enable Script hashes and style hashes

### Expected result
No errors

### Actual result
`Warning: hash() expects parameter 2 to be string, array given in \plugins\system\httpheaders\httpheaders.php on line 161`

`Warning: hash() expects parameter 2 to be string, array given in \plugins\system\httpheaders\httpheaders.php on line 172`

cc @zero-24

**Comment by brianteeman** [comment]
see #26505

**Comment by alikon** [comment]
#26505 is not the correct solution

**Comment by Quy** [comment]
Please test PR #28353<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26501">issues.joomla.org/tracker/joomla-cms/26501</a>.</sub>
