### ISSUE TITLE
[4.0] Can't get rid of Filter Options button in Installed Languages Manager

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#26529]
### Steps to reproduce the issue
Display the Installed Languages Manager
`.../administrator/index.php?option=com_languages&view=installed`

### Expected result
As we have no `Filter Options`, the button should not display at all.
The `Clear` Button should still be present.

### Actual result
The button is present and clicking on it displays an empty `<div`
![installedlanguagefilters](https://user-images.githubusercontent.com/869724/66471022-f519b580-ea8a-11e9-8d8c-c3db39a33552.gif)

**Comment by SharkyKZ** [comment]
Duplicate #26199.

**Comment by infograf768** [comment]
Looks like bar.php is missing a parameter
```
diff --git a/layouts/joomla/searchtools/default/bar.php b/layouts/joomla/searchtools/default/bar.php
index e1bb351..29c8e0f 100644
--- a/layouts/joomla/searchtools/default/bar.php
+++ b/layouts/joomla/searchtools/default/bar.php
@@ -55,13 +55,16 @@
 		</div>
 		<div class="btn-group">
-			<button type="button" class="btn btn-primary hasTooltip js-stools-btn-filter">
-				<?php echo Text::_('JFILTER_OPTIONS'); ?>
-				<span class="fa fa-angle-down" aria-hidden="true"></span>
-			</button>
+		<div class="btn-group">
+			<?php if ($filterButton) : ?>
+				<button type="button" class="btn btn-primary hasTooltip js-stools-btn-filter">
+					<?php echo Text::_('JFILTER_OPTIONS'); ?>
+					<span class="fa fa-angle-down" aria-hidden="true"></span>
+				</button>
+			<?php endif; ?>
 			<button type="button" class="btn btn-primary js-stools-btn-clear mr-2">
 				<?php echo Text::_('JSEARCH_FILTER_CLEAR'); ?>
 			</button>
 		</div>
-		
+
 	<?php endif; ?>
 <?php endif;
```

**Comment by infograf768** [comment]
this gives
<img width="1285" alt="Screen Shot 2019-10-09 at 12 49 03" src="https://user-images.githubusercontent.com/869724/66475328-62314900-ea93-11e9-980c-c92f62907cdf.png">

Does that look OK @SharkyKZ  ?

**Comment by SharkyKZ** [comment]
Looks fine, I guess.

**Comment by infograf768** [comment]
Closing as we have a patch
https://github.com/joomla/joomla-cms/pull/26530
