### ISSUE TITLE
[4.0] Expanded admin menu can't be collapsed when a Manager is displayed

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#26536]
### Steps to reproduce the issue
Expand an admin menu, for example Content.
Click on a Manager to display its page. for example Articles.
Try to collapse the Content menu = > impossible until you expand and click on another manager in a menu.
![retract_issue](https://user-images.githubusercontent.com/869724/66546406-3cf91500-eb3d-11e9-97b8-8fe115a40fdb.gif)

Consequence: one may have 2 expanded menus at the same time, forcing to scroll and scroll when wanting to display a manager in another menu.

Note: I don't remember if this issue has already been created.

**Comment by brianteeman** [comment]
Confirmed

**Comment by roland-d** [comment]
Closing this as we have a PR #26560
