### ISSUE TITLE
Anonymization with customfields 

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#26542]
### Steps to reproduce the issue

Create custom fields for user.
Create a user account and fill custom fields.
Submit anonymization request.

### Expected result

Customfields will be anonymized

### Actual result

data is not anonymized

### System information (as much as possible)

Joomla! 3.9.12

### Additional comments

The following solution would fix the problem:

plugin:
plugins\privacy\user\user.php

new function:
```
public function anonimizecustomfields($userid){
       // JLoader::register('FieldsHelper', JPATH_ADMINISTRATOR . '/components/com_fields/helpers/fields.php');
        $userfields = FieldsHelper::getFields('com_users.user', $userid, true);
        $model = JModelLegacy::getInstance('Field', 'FieldsModel', array('ignore_request' => true));

        foreach($userfields as $userfield) {
            $model->setFieldValue($userfield->id, $userid, '----');
        }
    }
```
at the end function:
onPrivacyRemoveData
`$this->anonimizecustomfields($user->id);`

**Comment by SharkyKZ** [comment]
Related RFC #25849.

**Comment by Quy** [comment]
Please comment/test in PR #25849.
