### ISSUE TITLE
[4.0] Mobile toolbar button requires double touch to close

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#26543]
### Steps to reproduce the issue
In the backend open articles list on a small screen. The toolbar toggle button requires 2 clicks to close. The first click attempts to open the already open toolbar.

**Comment by Quy** [comment]
Is this a duplicate of #26771?

**Comment by Quy** [comment]
Duplicate #27534

**Comment by ciar4n** [comment]
This is a separate issue.

**Comment by brianteeman** [comment]
confirmed the issue

**Comment by Subhang23** [comment]
I think the following issue is not limited to only articles component but extends to wherever this type of toolbar exists.

**Comment by Subhang23** [comment]
I think this issue can be solved by adding appropriate class names whenever the screen is loaded.

**Comment by Subhang23** [comment]
I would like to work on this issue.

**Comment by alikon** [comment]
thanks  @ Subhang23

**Comment by alikon** [comment]
thanks @Subhang23

**Comment by Subhang23** [comment]
Can you please review PR #27958 ?
