### ISSUE TITLE
Joomla 4 - Issue with Filter Options in Administrator Installed Language List Views

### ISSUE THREAD

**Issue by nitesh-solanki** [joomla/joomla-cms#26544]
### Steps to reproduce the issue

Go to System / Manage / Languages

I had installed few more languages.

Finally Click on Filter Options button near Search box.

### Expected result

Filter Options bar should be opened as pop-up below Search Box.

### Actual result

Filter Options bar is blank or missing.

### System information (as much as possible)

Joomla 4.0.0 Alpha 12
PHP 7.2.19

### Additional comments
URL - administrator/index.php?option=com_languages&view=installed
![Screenshot from 2019-10-11 15-17-55](https://user-images.githubusercontent.com/45821434/66643407-43ba8180-ec3c-11e9-912c-9221fd710f80.png)

**Comment by richard67** [comment]
This is already solved with #26530 and should be available in nightly builds from tonight or later.

**Comment by infograf768** [comment]
Closing as duplicate and solved.
