### ISSUE TITLE
[4.0] Improve restful Api by trimming the index.php

### ISSUE THREAD

**Issue by shim-sao** [joomla/joomla-cms#26564]
### Steps to reproduce the issue
It's not an issue but a little improvement because normal link for the Api is to call the `index.php` (it is logical) we can easily trim the `index.php` like the Joomla CMS root.

### Expected result
Calling Api with mod_rewrite: `api/v1/rest_call`

### Actual result
Calling Api without mod_rewrite: `api/index.php/v1/rest_call`

### System information (as much as possible)
Just a copy of a minimal .htaccess and web.config with `/api` as base to quick enable rewrite functionality. It can improve Joomla  to be totally Restful compliant.

Adding a little explanation in the documentation will be helpful for beginners.

### Additional comments
Keep in mind to not remove the entire `/api` folder or files on update or core reinstall.

**Comment by wilsonge** [comment]
Yup the intention is exactly to have this. We already have the code from the php side here https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Router/ApiRouter.php#L118-L129 just need the .htaccess file to go alongside it

**Comment by wilsonge** [comment]
This was fixed in https://github.com/joomla/joomla-cms/pull/29303
