### ISSUE TITLE
[4.0] Admin menu will not open again after opening and closing once

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#26578]
### Steps to reproduce the issue
Install nightly from 13th October.
In the Admin dashboard, click on any of the menu items that have a dropdown, i.e. Content, Menus, Components, Users.
Close the menu item.
Click on one of the other three menu items to open it.

### Expected result
The next menu item dropdown menu should open

### Actual result
It doesn't. Nothing happens.

N.B. If you click on a non-dropdown item, e.g. Home, System, or Help, it frees up the items with sub-menus again.

### Additional comments
This is, I think, the result of PR #26560 which was raised for issue #26536
In this case, if you click on a menu item to open its dropdown menu and then click on another item with a dropdown menu - _without_ closing the first - opening the second item closes the first automatically. That was the issue for #26536 which has been solved, but it would appear that the solution has caused another problem.

**Comment by infograf768** [comment]
Confused... I can't reproduce that issue.
![retract_notissue](https://user-images.githubusercontent.com/869724/66733865-3c27f200-ee61-11e9-8df0-b09fcba34b13.gif)

**Comment by Scrabble96** [comment]
I have updated with last night's Nightly and still have the same problem. I've tested on both Firefox and Chrome. This is what I see:


![ezgif com-optimize](https://user-images.githubusercontent.com/36987494/66740535-5666cd80-ee6b-11e9-924f-3913c7578544.gif)

**Comment by infograf768** [comment]
Houston, you have a problem...
I suggest you install a clean Nightly and NOT update.

**Comment by Scrabble96** [comment]
> 
> 
> I suggest you install a clean Nightly and NOT update.

Is there a way to do this without overwriting all the test articles, modules and menu items that I have set up?

**Comment by Scrabble96** [comment]
Ok. A clean full Nightly on another subdomain and the menu works correctly, so I'll close this issue.
