### ISSUE TITLE
[4.0] Captcha broken in article form, possible conflict with Editor buttons

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#26599]
### Steps to reproduce the issue

Install/enable a Captcha plugin.
Select it in Global Configuration.
Try to create a new article from frontend.
Inspect captcha field in article form.

### Expected result

Captcha field shown.

### Actual result
`Joomla\CMS\Object\CMSObject` text shown in place of Captcha field. The object appears to be an editor button:
```
object(Joomla\CMS\Object\CMSObject)[2425]
  protected '_errors' => 
    array (size=0)
      empty
  public 'modal' => boolean true
  public 'link' => string 'index.php?option=com_modules&amp;view=modules&amp;layout=modal&amp;tmpl=component&amp;editor=jform[captcha]&amp;105b73bec03a5feff8c60b7b445a9e84=1' (length=146)
  public 'text' => string 'Module' (length=6)
  public 'name' => string 'file-add' (length=8)
  public 'iconSVG' => string '<svg viewBox="0 0 32 32" width="24" height="24"><path d="M28 24v-4h-4v4h-4v4h4v4h4v-4h4v-4zM2 2h18v6h6v10h2v-10l-8-8h-20v32h18v-2h-16z"></path></svg>' (length=149)
  public 'options' => 
    array (size=4)
      'height' => string '300px' (length=5)
      'width' => string '800px' (length=5)
      'bodyHeight' => string '70' (length=2)
      'modalWidth' => string '80' (length=2)
```

**Comment by SharkyKZ** [comment]
@laoneo this is also coming from #20547 and is also fixed by moving `registerListeners()` call back to plugin constructor.

**Comment by brianteeman** [comment]
Looks like @wilsonge was right about that PR not being a good idea. This is not the only issue traced back to that

**Comment by laoneo** [comment]
The pr itself is ok. Would be good to investigate what exactly is the cause, I mean if the expectation is that the listeners are registered in the constructor, then make a pr to move it back. But for me it sounds like that something in the captcha plugin is not right.

**Comment by SharkyKZ** [comment]
Closed as having Pull Request https://github.com/joomla/joomla-cms/pull/28785.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26599">issues.joomla.org/tracker/joomla-cms/26599</a>.</sub>
