### ISSUE TITLE
Error while editing menu module in frontend 4.0 updated from 3.9.12 via upload

### ISSUE THREAD

**Issue by Stuartemk** [joomla/joomla-cms#26597]
### Steps to reproduce the issue
Clean installation from 3.9.12 to 4.0, put the menu module in the left position of Cassiopeia, open the frontend, log in, edit the menu module and change from right position to left position, the screen is blank with error message.

### Expected result

Work usual

### Actual result

{"error":true,"code":0,"message":"Call to a member function getType() on null"}

### System information (as much as possible)

Mysql 5.7.27
Php  7.2.19

### Additional comments

Enable debugger

{"error":true,"code":0,"message":"Call to a member function getType() on null","trace":"#0 \/home\/public_html\/components\/com_config\/Controller\/ModulesController.php(120): Joomla\\Component\\Modules\\Administrator\\Controller\\ModuleController->save()\n#1 \/home\/public_html\/libraries\/src\/MVC\/Controller\/BaseController.php(728): Joomla\\Component\\Config\\Site\\Controller\\ModulesController->save()\n#2 \/home\/public_html\/libraries\/src\/Dispatcher\/ComponentDispatcher.php(146): Joomla\\CMS\\MVC\\Controller\\BaseController->execute('apply')\n#3 \/home\/public_html\/libraries\/src\/Component\/ComponentHelper.php(383): Joomla\\CMS\\Dispatcher\\ComponentDispatcher->dispatch()\n#4 \/home\/public_html\/libraries\/src\/Application\/SiteApplication.php(205): Joomla\\CMS\\Component\\ComponentHelper::renderComponent('com_config')\n#5 \/home\/public_html\/libraries\/src\/Application\/SiteApplication.php(244): Joomla\\CMS\\Application\\SiteApplication->dispatch()\n#6 \/home\/public_html\/libraries\/src\/Application\/CMSApplication.php(241): Joomla\\CMS\\Application\\SiteApplication->doExecute()\n#7 \/home\/public_html\/includes\/app.php(63): Joomla\\CMS\\Application\\CMSApplication->execute()\n#8 \/home\/public_html\/index.php(36): require_once('\/home\/pu...')\n#9 {main}"}

**Comment by Quy** [comment]
Duplicate #25435. Same error with clean install of V4.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26597">issues.joomla.org/tracker/joomla-cms/26597</a>.</sub>
