### ISSUE TITLE
Some Notices after Joomla 4.00-alpha12-dev-Development-Update Package

### ISSUE THREAD

**Issue by ChristineWk** [joomla/joomla-cms#26591]
### Steps to reproduce the issue

After Joomla 4.00-alpha12-dev-Development-Update Package on october 09th & tried again on october 13th.
Last update was via Reinstall Joomla Core Files & DB on october 2nd

### Actual result

**Main Page:**
Notice: Trying to get property 'id' of non-object in xxx/modules/mod_menu/Helper/MenuHelper.php on line 44 Notice:
Trying to get property 'tree' of non-object in /xxx/modules/mod_menu/Helper/MenuHelper.php on line 56
Notice: Trying to get property 'id' of non-object in /xxx/modules/mod_menu/mod_menu.php on line 19 Notice: 
Trying to get property 'id' of non-object in /xxx/modules/mod_menu/mod_menu.php on line 20 Notice: Trying to get property 'tree' of non-object in /xxx/modules/mod_menu/mod_menu.php on line 21 
Warning: in_array() expects parameter 2 to be array, null given in /xxx/modules/mod_menu/tmpl/default.php on line 41 

**When searching in frontend a menue:
**
Notice: Trying to get property 'id' of non-object in /xxx/modules/mod_menu/mod_menu.php on line 20  and:

Notice: Trying to get property 'id' of non-object in /xxx/modules/mod_breadcrumbs/Helper/BreadcrumbsHelper.php on line 71

### System information (as much as possible)

Current Database Version: 4.0.0-2019-09-24 
Database Version: MySQLi
Manifest Version: 4.0.0-alpha12-dev 
PHP Version: 7.3.8
Webserver: Apache / cgi-fcgi 
Joomla Patchtester: 3.0.0-beta5-dev 

### Additional comments

After saving an article, I got also: 
Save failed with the following error: Column 'publish_up' cannot be null > this was on october10th. 

Tried some actions, such as rebuild menues etc. 

Found this: https://github.com/joomla/joomla-cms/pull/21901
and: https://github.com/joomla/joomla-cms/pull/25760
and https://github.com/joomla/joomla-cms/pull/26460
not sure, if belongs to Issue. 

**Had also:**
Correcting Notice in menu modal
Notice: Trying to get property 'input' of non-object in /xxx/administrator/components/com_menus/layouts/joomla/searchtools/default.php on line 98

this PR: https://issues.joomla.org/tracker/joomla-cms/26590 will solve it.

**Comment by SharkyKZ** [comment]
Have you updated database structure through System -> Database?

**Comment by ChristineWk** [comment]
@SharkyKZ 
thanks for your help. Of course. I'm always checking Database. And if it shows it's not up to date, then I fix it.
Current: Current Database Version: 4.0.0-2019-09-24 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26591">issues.joomla.org/tracker/joomla-cms/26591</a>.</sub>

**Comment by Quy** [comment]
Can you reproduce errors with a clean install of nightly build instead of updating? 
https://developer.joomla.org/nightly-builds.html

**Comment by richard67** [comment]
This looks definitely like database was not up to date, because since PR #26295 has been merged, the article table `#__content` allows NULL values. Please do as @Quy advised and check a clean install. And for testing updates, update a pre-4.0, e.g. 3.9.12 or current staging, to the latest nightly build using the update zip package, and use the "Upload & Update" tab of the Joomla Update component to do the update using the previously downloaded update package. Reinstall core files is something else, it is not a real update.

**Comment by richard67** [comment]
The PR #25760 you have mentioned is obsolete meanwhile because replaced by #26295 , so #25760 should be closed.

**Comment by richard67** [comment]
Here you can find a brief description how to test the update path of 4.0-dev: #25467 .

**Comment by ChristineWk** [comment]
@richard67 
OK, I mentioned some PRs, just wanted to tell, what I checked before here & there etc. :-)

Will also try (again) the usual way with: "latest nightly build using the update zip package using the "Upload & Update" tab". This procedure I also did very often in the past. Except last time, when I made the Reinstall function.

Thank you all above. Will inform ....
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26591">issues.joomla.org/tracker/joomla-cms/26591</a>.</sub>

**Comment by richard67** [comment]
@ChristineWk No problem, all fine. Just keep us up to date. Thanks for testing.

**Comment by ChristineWk** [comment]
First of all: thanks for understanding. 

Latest News for today:

System > Under Database:

There was a PR: https://issues.joomla.org/tracker/joomla-cms/26458
concerning the word: "Fix". which has been changed to: "Update Structure" > this I have :-)

Just made: latest nightly build using the update zip package from here:  https://developer.joomla.org/nightly-builds.html" using Upload & Update" tab" 

After OK update, DB has to be updated. It shows:

4.0.0-2019-09-27 ‎4.0.0-alpha12-dev 

Above situation still exists. 

@Quy I had already a Joomla 4 since last year. Resulting of some problems etc., I installed a (new) clean install of nightly build on september 6th. 

I‘m not a programmer, developer etc., just a „normal user“ :-) Just trying, learning & testing of Patches :- ) to put a little input for all your fantastic work.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26591">issues.joomla.org/tracker/joomla-cms/26591</a>.</sub>

**Comment by richard67** [comment]
@ChristineWk Which was the Joomla version before the update, i.e. from which version did you update to 4.0.0-alpha12-dev nightly build?

**Comment by Quy** [comment]
@richard67 It appears she did a clean install of the nightly build on September 6 and have been updating/upgrading it with the nightly builds.

**Comment by ChristineWk** [comment]
Yes indeed :-)

**Comment by richard67** [comment]
@Quy @ChristineWk You can't update from a 4.0-dev nightly built to another or alpha-x to alpha-y. Updates will be supported starting with 4.0-Beta-1. Then it will be possible to update from pre-4.0 to 4.0-Beta-1, and later from 4.0-Beta-1 to 4.0-Beta-2 and so on.

This has been communicated in JBS, too, Quy.

And this is the reason why I was allowed to change existing 4.0.0-yyyy-mm-dd.sql update sql scripts in my PRs in past and until Beta-1, because otherwise I would have had to make new scripts for each change and comment out changes in old scripts so they are being run when updating because having newer schema version in their file name.

So I am 100% sure that when @ChristineWk does the update from 3.9.12 to that 4.0.0-alpha12-dev nightly build, all will work as expected.

**Comment by richard67** [comment]
You know the changed update sql scripts for 4.0  has not been run again because their schema version number in file name was not greater than db schema version before the update.

**Comment by richard67** [comment]
I think that explains all ;-)

**Comment by ChristineWk** [comment]
Sorry, it's too much for me now to understand, but thank you for your investigation.

**Comment by richard67** [comment]
No problem. But if you find time tomorrow or later this week, it would be nice if you could really do the update test from 3.9.12 to 4.0 nightly build, because we need people who test that and report back issues. That would be really a help.

**Comment by ChristineWk** [comment]
Can I try with an existing one? (3.9.12)

Btw: I can't understand, see below, because it was fixed in Code Base after of my installation from September 6
> There was a PR: https://issues.joomla.org/tracker/joomla-cms/26458
> concerning the word: "Fix". which has been changed to: "Update Structure" > this I have :-)
thks.

**Comment by Stuartemk** [comment]
> No problem. But if you find time tomorrow or later this week, it would be nice if you could really do the update test from 3.9.12 to 4.0 nightly build, because we need people who test that and report back issues. That would be really a help.

Exactly what proof is needed?
of a clean installation 3.9.12 to 4.0 nightly build?

Only that or something else to try?

I can now do those tests.

If something more specific is needed, please let me know.

**Comment by richard67** [comment]
> Can I try with an existing one? (3.9.12)

Sure, but you should make a backup of filesystem and database in case if you need that 3.9.12 later again, because after the test it will be a 4.0-alpha12-dev.

> concerning the word: "Fix". which has been changed to: "Update Structure" > this I have :-)

You have "Fix" still? Or "Update Structure"? The update of the files should have been ok, so you should have had "Update Structure", as far as I know. It was only the dastabase stuff which failed, as far as I understand what happened. If you have still "Fix" after the update, then something else went wrong, too, or the nightly build does not contain that change (what it should because it was merged 11 days ago).

**Comment by richard67** [comment]
> of a clean installation 3.9.12 to 4.0 nightly build?

Yes. Update this way using the "Upload & Update" tab of the Joomla Update component.

**Comment by richard67** [comment]
Link to an issue where the update procedure is described in brief words (but with an older 3.9.x): #25467 .

**Comment by ChristineWk** [comment]
@richard67 > 
> 
> @Quy @ChristineWk You can't update from a 4.0-dev nightly built to another or alpha-x to alpha-y. Updates will be supported starting with 4.0-Beta-1. Then it will be possible to update from pre-4.0 to 4.0-Beta-1, and later from 4.0-Beta-1 to 4.0-Beta-2 and so on.
etc.

That's why I'm asking concerning PR #26458, because I  have: "Update Structure" after a nightly update package :-)

J 3.9.12, will check, what I can do etc.

**Comment by Stuartemk** [comment]
> > of a clean installation 3.9.12 to 4.0 nightly build?
> 
> Yes. Update this way using the "Upload & Update" tab of the Joomla Update component.

The update from 3.9.12 to 4.0 nightly build was almost perfect, except for the notifications of the lack of template, notices that stopped appearing at the beginning of the session already within 4.0

The update was by using the "Upload & Update" tab of the Joomla Update component.

I will take a look for warnings or errors.

**Comment by Quy** [comment]
@ChristineWk PR #26458 renames only the button. Function wise, it is the same as before. 

Please do a clean install of the full package of the nightly build from October 14 and you will be back in business without these notices.

**Comment by richard67** [comment]
@Quy or she updates from 3.9.x like I described.

**Comment by richard67** [comment]
@ChristineWk If after an update test from 3.9.x to current 4.0 nightly build succeeeds according to the description in #25467 and the issues mentioned in the description above have gone, you can close this issue.

@Quy Since this issue here is about the update and not a new install, it needs the update test to verify that this issue can be closed.

**Comment by ChristineWk** [comment]
About: update from 3.9.12 to 4.0 nightly build etc., this I will try in another task. 

FYI: I think I found out, the reason for above notices & checked/made following:
The Main Menue was not set as: default Page. Don't know why. 
- Set as Default Page. Response:
ErrorColumn 'publish_up' cannot be nullMessage
COM_MENUS_ITEMS_SET_HOME

- Created a new Main Menu > set to: default was successfully! Now everything works (frontend clean). Notices has gone.
- **But** minutes later: again above response.
Means: Main Menu could not be (or only for some minutes) set to: default page. 
Result was/is: Main Page: error 404 plus the other Notices.

You could close the Issue, if wanted. Thanks to all for your informations.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26591">issues.joomla.org/tracker/joomla-cms/26591</a>.</sub>

**Comment by richard67** [comment]
@ChristineWk You can close this issue yourself.
