### ISSUE TITLE
[4.0] options grid

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26605]
Most of the options fieldsets have a css class of `.options-grid-form-full` which assuming i read this correctly means that they should be in one column.
```

.options-grid-form.options-grid-form-full > div {
      grid-template-columns: 1fr;
]
```

However as can be seen below they are in **two** uneven columns
![image](https://user-images.githubusercontent.com/1296369/66870244-ebb3b000-ef98-11e9-8711-e80e634b4b48.png)

The cause of this is the description div which is set to start at col 1 and end at col 3 eben though at this resolution there is only 1 column.

```
.com_config .tab-description {
    grid-column: 1/3;
} 
```

This should be set to either grid-column:auto or removed as auto is the default and then we have one column displayed as per the defined css.

_I could do this but I am not sure if it was intended to be in two columns or not._ 

(As noted elsewhere by @C-Lodder two columns horizontally is not aa good idea)

**Comment by ciar4n** [comment]
Is there anywhere the `tab-description` is not inside `options-grid-form-full`? The CSS itself implies that there is. If so your suggested change will affect them.

Using `grid-column: 1/3;` inside a single column grid creates an implicit grid with 3 columns which is what's happening here. Considering this issue, I can only presume this wasn't intended.

**Comment by brianteeman** [comment]
> Is there anywhere the tab-description is not inside options-grid-form-full?

yes there are some

**Comment by ciar4n** [comment]
Change to this instead...

```
.com_config .tab-description {
    grid-column: 1 / -1;
} 
```

`.tab-description` will be full width regardless of the number of columns and not effect the grid.

**Comment by Quy** [comment]
See PR #26608<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26605">issues.joomla.org/tracker/joomla-cms/26605</a>.</sub>
