### ISSUE TITLE
Various deprecation for PHP 7.4

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#26607]
### Steps to reproduce the issue
Install PHP 7.4 and run Joomla latest 3.9.13dev

### Expected result
No deprecation notice

### Actual result
Several files with deprecated notice

![image](https://user-images.githubusercontent.com/17835460/66918402-92db2a80-f01f-11e9-80c6-9ed1d17fe16d.png)

**Comment by Quy** [comment]
Duplicate #25834<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26607">issues.joomla.org/tracker/joomla-cms/26607</a>.</sub>

**Comment by SharkyKZ** [comment]
For `get_magic_quotes_gpc()` notices see #26615.
