### ISSUE TITLE
[4.0] com_finder language

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26604]
There is an option for the default language. Why is it set by default to "none" and not "Site Default Language" ??

![image](https://user-images.githubusercontent.com/1296369/66869097-88c11980-ef96-11e9-9178-f3be3095e3f9.png)

cc @Hackwar @infograf768

**Comment by Hackwar** [comment]
This sets the default stemmer and there are situations where you don't want all articles handled by the default language stemmer or don't want a stemmer at all.

**Comment by brianteeman** [comment]
That would explain why its an option, not why _Site Default Language_ is not the default setting. Surely this means that by default there is no stemmer inn use at all

**Comment by Hackwar** [comment]
Indeed. As this is also a matter of performance, it is switched off by default.

**Comment by brianteeman** [comment]
Not a good User experience for this field in that caase

**Comment by Hackwar** [comment]
Yes, I'm happy for support there/suggestions how to improve this.

**Comment by brianteeman** [comment]
Well I would start by having it enabled by default and only switching it off for performance reasons

**Comment by brianteeman** [comment]
When you refer to a performance issue at what point (number of articles?) does this become an issue

**Comment by Hackwar** [comment]
I can't really tell, because it depends on several factors. The stemmer will process every word, so it isn't so much a matter of number of articles, but words to process. Then there is the question of the quality/performance of the stemmer. The stemmers that we are using are rather optimised, but can't say for other implementations which you could install separately. Then there is also the issue of the performance of the server. I've had problems on my local dev environment when installing the testing sampledata due to the indexing.

I also did not do extensive tests how big the performance impact is.

**Comment by brianteeman** [comment]
It just seems really odd to me to have it disabled by default. You usually turn things off for performance as a site grows.

**Comment by Hackwar** [comment]
I didn't want to enable it by default, since it depends on a properly set up site with right language installed and all. If you have a site that is in german, but did never install the german language pack, the stemmer would try to stem german words with the english stemmer.

**Comment by brianteeman** [comment]
If you have a site in german and dont install the language pack then this would be the least of your worries =- all success/error messages etc would be in english

**Comment by infograf768** [comment]
One can have a non-multilingual site which has content in various languages, independent from installed languages and therefore independent from the default site language.
Errors, etc, are totally independent from the contents which is what finder is only concerned with.
The language stemmer choice depends only on installed languages.
The Site Default Language may not have a specific stemmer but it still displays as a choice in the dropdown.

If we follow the tip (I have not tested):
`Set the language to be used for non-multilingual sites or content marked as "All". `
the `or` means that the stemmer could also be used on a multilingual site for items set to "All"

This is rather confusing, but the best default is `None` indeed.

**Comment by brianteeman** [comment]
Closing for the reasons stated by @infograf768 amd @Hackwar
