### ISSUE TITLE
[4.0] create/edit subfields  size does not fit

### ISSUE THREAD

**Issue by HRIT-Florian** [joomla/joomla-cms#26602]
### Steps to reproduce the issue

1. Creat a new subform field like in com_users.users
index.php?option=com_fields&view=field&layout=edit&id=2&context=com_users.user
2. Select field type "subfields"
3. See  "Render values " Table.

![field_edit_subforms](https://user-images.githubusercontent.com/12803406/66843239-c8730b80-ef6c-11e9-9d3d-14ca226bbff5.jpg)

### Expected result
Table should fit

### Actual result
Table does not fit

### System information (as much as possible)
Joomla! 4.0.0-alpha12-dev 

### Additional comments
The Problem depends on the css table theads  white-space: nowrap

`
.table thead td, .table thead th {
    white-space: nowrap;
`
Not sure why it is there, but i think for reponsive reasean these should be anyway set to normal.
Bett we fix the reasons why nowrap was necessary there?

**Comment by brianteeman** [comment]
looks like it is simply a copy paste error

**Comment by HRIT-Florian** [comment]
copy paste error?

What is the reason for these?
`.table thead td, .table thead th { white-space: nowrap;`

Maybe we should remove these line of css anyway ;)

**Comment by brianteeman** [comment]
actually looking at my install I dont have subfields

**Comment by Quy** [comment]
It was merged recently #24711.

**Comment by brianteeman** [comment]
ah - must update my branch then and check it tomorrow

**Comment by brianteeman** [comment]
Yikes that needs a lot of work

**Comment by Quy** [comment]
Please test PR #26614<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26602">issues.joomla.org/tracker/joomla-cms/26602</a>.</sub>
