### ISSUE TITLE
[4 aplha 12] missing language string: JLIB_UPDATER_ERROR_OPEN_UPDATE_SITE

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-cms#26620]
### Steps to reproduce the issue

1. Install Joomla 4 Aplha 12.
2. At the last step of the installation, a language string is untranslated:
JLIB_UPDATER_ERROR_OPEN_UPDATE_SITE

### Expected result

It should display the error "Update: Could not open update site #%d &quot;%s&quot;, URL: %s" (with parsed variables) instead.

### Actual result

![screencapture-localhost-Joomla4a12-installation-index-php-2019-10-18-06_06_32](https://user-images.githubusercontent.com/1217850/67065338-333f6500-f16e-11e9-9a62-f5e979882c51.png)

**Comment by infograf768** [comment]
Don't know how you got the error but the solution is easy.
The string has to be added to installation/language/en-GB/en-GB.ini and en-US/en-US.ini

**Comment by Quy** [comment]
Please test PR #26732<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26620">issues.joomla.org/tracker/joomla-cms/26620</a>.</sub>
