### ISSUE TITLE
User gets deactivated while using "Forgot Password" option from User side and he fails to reset the password.

### ISSUE THREAD

**Issue by Kaustubharas** [joomla/joomla-cms#26626]
### Steps to reproduce the issue

Go to user side of any Joomla website 
Go to Login page
Click on "Forgot Password" link
Enter your "Email Address" in the given text box and click "Submit"
Now, go to admin side and login as admin
Go to User Manager and search for the user for which "Forgot Password" is attempted
Check the user state - it shows "x" under the "Activated" column i.e Deactivated.

### Expected result

User should not get deactivated, only by attempting the "Forgot Password" action. Unless the password is not reset, till then user should state should be activated and should be able to access the website. 

### Actual result

User should is getting deactivated, only by attempting the "Forgot Password" action.

### System information (as much as possible)

OS: Ubuntu 18.04 LTS
PHP Version: 7.1
Browser: Chrome
Joomla Version - 3.9.12

**Comment by mbabker** [comment]
It’s a display issue, the account isn’t actually deactivated.  I’m pretty sure this conversation was had before here on GitHub but basically the token is stored in the database in the same column as the activation token so the UI can’t distinguish the state/intent.

**Comment by Quy** [comment]
Duplicate #24269. Please test PR #24461, but it is for J4 and will not be fixed in J3.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26626">issues.joomla.org/tracker/joomla-cms/26626</a>.</sub>
