### ISSUE TITLE
"Remember me" text

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#26624]
### What needs to be fixed

On the login forms, there is a checkbox to "Remember Me", but thinking about it, for those non-tecky people, this doesn't mean much.
- Does it remember me based on IP?
- Does it remember is on this device?
- How long does it remember me for?

### How would you fix it

Elaborate on how it remembers the user and how long for.

**Comment by brianteeman** [comment]
Whilst I agree with your comment it is a very common pattern. Having said that if you have any suggestions for an alternative ....

**Comment by C-Lodder** [comment]
@brianteeman It's a hard one, cause the last thing you want to do is clutter the admin module, and I don't know what the rules are on popovers in J4 in regards to a11y and preferences.

I believe Amazon have a "click for more details" link which opens a small modal, showing details about the "remember me" feature. So this could be a potential solution.

**Comment by Ankit7Das** [comment]
I would like to work on it

**Comment by Bakual** [comment]
As a background: It will remember you on that specific browser. So it is not device and not IP based.
The duration in days is set in the "Authentication - Cookie" plugin. It's a maximum duration, in practice it may be invalidated before that time (eg due to browser updates).
