### ISSUE TITLE
Error message behavior on login page is unusual.

### ISSUE THREAD

**Issue by kishorchate** [joomla/joomla-cms#26636]
### Steps to reproduce the issue
1. Open administrator
2. Enter wrong credentials
3. Click Log in button multiple times(repeatedly)

### Expected result
Error message pop up should shown only one at a time

### Actual result
Multiple error message(forbidden) shown after warning message

### Additional comments
User should be shown the warning message only.
![error message on log in](https://user-images.githubusercontent.com/39908485/67139406-851ae480-f26d-11e9-8a59-77bb93eecf2a.png)

**Comment by Quy** [comment]
Side effect of #25850<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26636">issues.joomla.org/tracker/joomla-cms/26636</a>.</sub>
