### ISSUE TITLE
[4.0] No client side validations are executed while creating new user from backend

### ISSUE THREAD

**Issue by ankush-maherwal** [joomla/joomla-cms#26639]
### Steps to reproduce the issue
1) Go to com_users
2) Click on "New" button to create a new user
3) Without filling mandatory fields click on "Save" button
4) Also, check the behaviour for "Save & Close" button

For the "Save & Close" button client-side validations are executed but not for the "Save" button

### Expected result
Client-side validations should be executed for "Save" button and form should not be submitted if the fields in the form contain invalid data

### Actual result
On click of "Save" button even if the form contains invalid data the form is submitted

### System information (as much as possible)
Joomla 4.0.0-alpha12
Linux server

**Comment by brianteeman** [comment]
I could not replicate this error report

**Comment by ankush-maherwal** [comment]
It seems that the client-side validations are not executed on click of "save" i.e apply button for any of the inbuilt extension except article creation

**Code generated or save button for article**
```
<joomla-toolbar-button id="toolbar-apply" task="article.apply" form-validation="">
<button class="button-apply  btn btn-sm btn-success" type="button">
	<span class="icon-apply" aria-hidden="true"></span>
	Save</button>
</joomla-toolbar-button>
```

**Code generated for save button for user creation**
```
<joomla-toolbar-button id="toolbar-apply" task="user.apply">
<button class="button-apply  btn btn-sm btn-success" type="button">
	<span class="icon-apply" aria-hidden="true"></span>
	Save</button>
</joomla-toolbar-button>
```

**form-validation=""** is the extra attribute in the button HTML which is missing in "save" button of user creation view

**Comment by HRIT-Florian** [comment]
I could reproduce it!

**Comment by brianteeman** [comment]
![valid](https://user-images.githubusercontent.com/1296369/67145749-ddf17980-f27b-11e9-93ae-f3d5dbc809ef.gif)

**Comment by Quy** [comment]
Closing as non-reproducible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26639">issues.joomla.org/tracker/joomla-cms/26639</a>.</sub>

**Comment by SharkyKZ** [comment]
Same with almost every other form. Contact, Tag, User Note, User Level, etc.

**Comment by SharkyKZ** [comment]
I see 2 options:

1. Not use `Joomla\CMS\ToolbarHelper::apply()` here.
2. Make use of methods defined in `Joomla\CMS\Toolbar\CoreButtonsTrait` in `Joomla\CMS\Toolbar\ToolbarHelper`.

@asika32764 What do you think?

**Comment by asika32764** [comment]
I need check the code, since the HTML side was changed to CE, I' not sure the form validation process how to work with toolbar buttons

**Comment by SharkyKZ** [comment]
It's not to do with CE but with `ToolbarHelper` adding a button in a basic way:
https://github.com/joomla/joomla-cms/blob/efca0fbceec2bbaf43806c7066e15ae173c4c851/libraries/src/Toolbar/ToolbarHelper.php#L477-L483

Instead we can use the trait which also enables validation:

https://github.com/joomla/joomla-cms/blob/efca0fbceec2bbaf43806c7066e15ae173c4c851/libraries/src/Toolbar/CoreButtonsTrait.php#L351-L356

My question is whether we should make the changes in `ToolbarHelper` or remove the uses of `ToolbarHelper` in views and use trait methods directly.

**Comment by asika32764** [comment]
I see,

I think we can try proxy `ToolbarHelper::apply()` to `CoreButtonsTrait::apply()` so that all components which uses ToolbarHelper won't break and keep B/C.

CoreButtonsTrait has already uses by `Toolbar` class so we can do like this:

```php
class ToolbarHelper 
{
    public static apply(...) 
    {
        $bar = Toolbar::getInstance('toolbar'); 
        return $bar->apply(...);
    }
}
```

**Comment by jwaisner** [comment]
I cannot reproduce this issue in 4.0.0-beta1-dev. I am using Firefox for the browser and MYSQL for database.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26639">issues.joomla.org/tracker/joomla-cms/26639</a>.</sub>

**Comment by vbv2312** [comment]
how to know if the client side verification is happening or not ??
can't reproduce the issue

**Comment by ankush-maherwal** [comment]
@vbv2312 The form is getting submitted even if the required fields are not filled. If the client-side validations are working then the form will not be submitted at all if any required filed is not filled.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/28897.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26639">issues.joomla.org/tracker/joomla-cms/26639</a>.</sub>
