### ISSUE TITLE
Privacy: Information Requests - Can able to save invalid email string

### ISSUE THREAD

**Issue by AdityaTaware** [joomla/joomla-cms#26637]
### Steps to reproduce the issue
1. Go to the Admin-> Users-> Privacy-> Request
2. Click on New and add invalid email string in the Email field and save it.
3. The record get save and the system shows the warning and item saved message at a time.

### Expected result
The system should not allow saving invalid email string and the record should not get save.

### Actual result
Both warning and item saved messages![screen shot 2019-10-19 at 07 30 57](https://issues.joomla.org/uploads/1/a205770e60f17aacd0a0e4ba2f88e475.png) at a time and record created.

**Comment by andreaskournoutas** [comment]
Issue confirmed. Although before saving, the input field shows a warning, it lets you save the record normally.![screen shot 2019-10-19 at 08 32 45](https://issues.joomla.org/uploads/1/e197c024eb55d405b36f240732116978.jpg)![screen shot 2019-10-19 at 08 32 46](https://issues.joomla.org/uploads/1/e6dd706df41f812a474f77bc9f34a786.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26637">issues.joomla.org/tracker/joomla-cms/26637</a>.</sub>

**Comment by Quy** [comment]
Please test PR #26810<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26637">issues.joomla.org/tracker/joomla-cms/26637</a>.</sub>
