### ISSUE TITLE
[4.0] New Article status stays Unpublished post creation

### ISSUE THREAD

**Issue by Kaustubharas** [joomla/joomla-cms#26635]
### Steps to reproduce the issue

Login as admin to your joomla website
Go to Content > Articles
Create a new Article and save it.
Now to to Article list view and check the created Article's status.
Article status shows "Unpublished".

### Expected result

Newly created article state should be "Published"

### Actual result

Newly created article state stays Unpublished

### System information (as much as possible)

PHP 7.2
Joomla 4.0.0-alpha12-dev

**Comment by simbus82** [comment]
Not a bug for me.
It's a correct workflow for article management.
An article must be voluntarily published. The "admin user" must specify the article status before saving.

![image](https://user-images.githubusercontent.com/1375730/67189139-f84b6480-f3ed-11e9-8d80-11d3990e5d83.png)

**Comment by alikon** [comment]
Expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26635">issues.joomla.org/tracker/joomla-cms/26635</a>.</sub>
