### ISSUE TITLE
[4.0] Extra clicks to users for changing the status of Article.

### ISSUE THREAD

**Issue by Kaustubharas** [joomla/joomla-cms#26633]
### Steps to reproduce the issue
Login as admin to your joomla website
Go to Content > Articles
Create a new Article and save it.
Now to to Article list view and try to change the status of the Article.
When try to change the state, it again gives you option to choose - i.e Published, unpublished or trashed.
Usability wise, user will expect a single click to publish / unpublished.

### Expected result
By click on the status and selecting the options, status of article should change. (its OK).

### Actual result
By click on the status and selecting the options, status of article should change. (its OK).

But, usability wise, it's taking more than one click to publish / unpublished the article. (not OK).

### System information (as much as possible)
PHP 7.2
Joomla 4.0.0-alpha12-dev

### Additional comments

User should be able to change the state of Article with a single click.

**Comment by brianteeman** [comment]
> Usability wise, user will expect a single click to publish / unpublished.

This is necessary as we now support the ability to have unlimited status

**Comment by Quy** [comment]
Closing for stated reason.
