### ISSUE TITLE
UI issue: Copied file

### ISSUE THREAD

**Issue by ahghatol** [joomla/joomla-cms#26638]
![Screenshot from 2019-10-19 13-37-40](https://user-images.githubusercontent.com/15344223/67140193-ada6dc80-f275-11e9-89b3-83fcf6174e4a.png)

### Steps to reproduce the issue
1. Open any template in the template manager
2. Click on `New file`
3. Click on close to close Popup window
4. Again click on `New file`

### Expected result
The copy file block should be displayed inside the popup window. 

### Actual result
The copy file block should be displayed going out of the popup window.

**Comment by Quy** [comment]
@ciar4n Do you know why it is doing this? Thanks.

**Comment by ciar4n** [comment]
From a CSS perspective it is been caused by `overflow-y: initial;` been applied to the `modal-body`. It is been applied inline with JS. Sorry to say I have no idea why or how.

**Comment by sanjulamadurapperuma** [comment]
@ciar4n I cannot seem to find `overflow-y: initial;` in the code base, specifically the default_modal_file_body.php

**Comment by ciar4n** [comment]
Possibly this... https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/legacy/js/bootstrap-init.es5.js#L162

**Comment by Quy** [comment]
Please test PR #28487
