### ISSUE TITLE
[4.0] Control Panel: Post Installation Messages

### ISSUE THREAD

**Issue by aishwaryabagawade200** [joomla/joomla-cms#26646]
### Steps to reproduce the issue
1. Control panel
2.  click on Post installation Messages
3. click on messages listed
4. Message will be displayed

### Expected result
1. count of messages on notification should be decremented once the message is visited.

### Actual result
1. count remains same

### Additional comments
![Post Installation Messages](https://user-images.githubusercontent.com/56737915/67140768-8d7a1c00-f27b-11e9-8ba3-a88070dc3883.png)

**Comment by brianteeman** [comment]
You need to press "hide this message" to remove the messaage and reduce th count

**Comment by brianteeman** [comment]
@quy I guess this one can be closed
