### ISSUE TITLE
[4.0] Error while publishing default Joomla category.

### ISSUE THREAD

**Issue by Kaustubharas** [joomla/joomla-cms#26640]
### Steps to reproduce the issue
Login to admin of your joomla website
Go to com_categories list view
Try to unpublish "uncategorised" categoty.
Error appears - 

**An error has occurred.
0 Argument 2 passed to Joomla\Component\Finder\Administrator\Indexer\Result::addNestedTaxonomy() must implement interface Joomla\CMS\Tree\ImmutableNodeInterface, null given, called in /home/eabbcbdv/public_html/start/joomla170/plugins/finder/content/content.php on line 322**

### Expected result

Category should get unpublished without showing any error.

### Actual result

Category gets unpublished with an error message.

### System information (as much as possible)

PHP 7.2
Joomla 4.0.0-alpha12-dev![screen shot 2019-10-19 at 08 16 32](https://issues.joomla.org/uploads/1/9ff996c6b6d913f7df33a5db5289a447.png)

**Comment by alikon** [comment]
please test #26392<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26640">issues.joomla.org/tracker/joomla-cms/26640</a>.</sub>
