### ISSUE TITLE
[4.0] Administrator - User Accessibility settings sub-menu not working.

### ISSUE THREAD

**Issue by Kaustubharas** [joomla/joomla-cms#26644]
### Steps to reproduce the issue

Login as admin to your joomla website
Click on "User Menu" present on top right corner of the screen
And, click on "Accessibility Settings". 

### Expected result

Clicking on "Accessibility Settings", it should redirect to accessibility settings view.

### Actual result

Clicking on "Accessibility Settings", it doesn't redirect.

### System information (as much as possible)

PHP 7.2
Joomla ![screen shot 2019-10-19 at 08 37 53](https://issues.joomla.org/uploads/1/5648ed2c0e72ecc56f82a1f869cd2330.png)4.0.0-alpha12-dev

**Comment by brianteeman** [comment]
This can be closed as a duplicate report and we have a PR for this

**Comment by Quy** [comment]
Please test PR #26194<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26644">issues.joomla.org/tracker/joomla-cms/26644</a>.</sub>

**Comment by Kaustubharas** [comment]
@brianteeman  Sure! But both the menus i.e "Edit Account" and "Accessibility Settings" redirects to Edit user view. It seems a duplicate menu with a different name.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26644">issues.joomla.org/tracker/joomla-cms/26644</a>.</sub>
