### ISSUE TITLE
[4.0] Error while deleting default Joomla category.

### ISSUE THREAD

**Issue by Kaustubharas** [joomla/joomla-cms#26648]
### Steps to reproduce the issue

Login to admin of your joomla website
Go to com_categories list view
Try to trash"uncategorised" categoty.
Error appears -

**An error has occurred.
0 Argument 2 passed to Joomla\Component\Finder\Administrator\Indexer\Result::addNestedTaxonomy() must implement interface Joomla\CMS\Tree\ImmutableNodeInterface, null given, called in /home/eabbcbdv/public_html/start/joomla170/plugins/finder/content/content.php on line 322**

### Expected result

Category should get trashed without showing any error.

### Actual result

Category gets trashed with an error message.

### System information (as much as possible)

PHP 7.2
Joomla 4.0.0-alpha12-dev

**Comment by SharkyKZ** [comment]
See PR #26235 please.
