### ISSUE TITLE
Articles Option: Page is not responsive, menu is get overlap to other menu

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#26645]
### Steps to reproduce the issue
1. Login to backend of joomla 4.0.0.alpha12-dev
2. Go to article menu
3. Click on option
4. See the responsiveness

### Expected result
Menu should not get to overlap to other menus

### Actual result
Menu are getting overlap

### System information (as much as possible)
Screeen resolution: 1366 x 768

![screen shot 2019-10-19 at 08 41 07](https://issues.joomla.org/uploads/1/a374cd31569a7b4d4a46ee0dc3e51ee1.png)

**Comment by brianteeman** [comment]
Can not replicate with your instructions. You have "tabs" present that are not in core

**Comment by Quy** [comment]
Please test PR #26890<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26645">issues.joomla.org/tracker/joomla-cms/26645</a>.</sub>
