### ISSUE TITLE
Template manager: Filename validation error if enter file extension in Copied file name

### ISSUE THREAD

**Issue by ahghatol** [joomla/joomla-cms#26641]
![Screenshot from 2019-10-19 13-45-59](https://user-images.githubusercontent.com/15344223/67140321-032fb900-f277-11e9-811a-93725150a7f7.png)

### Steps to reproduce the issue
1. Go to templates
2. Click on `Cassiopeia` (Column heading: `Template`) to open template files in template manager 
3. Click on `css`
4. Click on `offline.css`
5. Click on the `New File` button from the toolbar 
6. Enter the `Copied File Name` as  override.css

### Expected result
The copied file should be get created. 

### Actual result
It throwing error `invalid file name...`

### Additional comments
This works fine if we don't add filename without the file extension.

**Comment by brianteeman** [comment]
this is the same behaviour as in joomla 3

**Comment by Scrabble96** [comment]
If you are creating a new file or renaming one, you don't need to include the file extension in the name as you have to select it from the dropdown:

![create-new-file](https://user-images.githubusercontent.com/36987494/94993099-79135a00-0586-11eb-8b22-6274e83b09dd.jpg)

**Comment by brianteeman** [comment]
This should be closed as eexpeected behaviour
