### ISSUE TITLE
Confirmation message box should disappear in a few seconds

### ISSUE THREAD

**Issue by riishede** [joomla/joomla-cms#26643]
When an article og category (for example) are published or unpublished a messagebox appeares. It would be nice if that messagebox disappeares in af few seconds. Right now you need to click the X before another action can be carried out.

**Comment by brianteeman** [comment]
It will do - that's on my todo for today

**Comment by andreaskournoutas** [comment]
Are there any usability reasons for those messages to appear as modals? Isn't the alert or the toast component more suitable for notifications like these?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26643">issues.joomla.org/tracker/joomla-cms/26643</a>.</sub>

**Comment by brianteeman** [comment]
It's just not been completed yet. There were lots of things to put in place first

**Comment by Quy** [comment]
Duplicate #25890<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26643">issues.joomla.org/tracker/joomla-cms/26643</a>.</sub>
