### ISSUE TITLE
Articles > change status:  Status option is enable if content is in same status

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#26647]
### Steps to reproduce the issue
Login to backend of joomla 4.0.0.alpha12-dev
Go to article menu
Select the article which is unfeatured
Click on change status option
Click on unfeatured

### Expected result
The unfeatured option should be disable if article is in same status

### Actual result
Unfeatured option is enable

![screen shot 2019-10-19 at 08 51 33](https://issues.joomla.org/uploads/1/c08da4027908f89eba050a2dc2a22b2b.png)

### Additional comments

4.0.0.

**Comment by thite-amol** [comment]
I  have checked for this issue and found that this is not considered as a stage in the workflow. @brianteeman  @mbabker is this intentional or there is any plan to include it?

**Comment by brianteeman** [comment]
Featured/unfeatured is nothing to do with the workflow. It is completely separate and always has been

**Comment by anirudhsingh20** [comment]
Hi, I am Anirudh, want to contribute to Joomla any suggestion how can I understand the codebase?

**Comment by brianteeman** [comment]
a lot has changed since this was reported. at the time workflows was always on. now its not etc etc.

**Comment by joomdonation** [comment]
I'm closing this issue here because the request is not valid. In your case, there is only one article displayed but in a normal usage, there would be multiple articles there. We won't check for every checked articles and disable the button if all of these checked articles are already unfeatured.
