### ISSUE TITLE
Patch tester: Tooltip is getting displayed over search input field and this making difficulties for typing.

### ISSUE THREAD

**Issue by ahghatol** [joomla/joomla-cms#26642]
![Screenshot from 2019-10-19 13-56-38](https://user-images.githubusercontent.com/15344223/67140475-70901980-f278-11e9-888f-fc1bfb98897c.png)

### Steps to reproduce the issue
1. Go to components
2. Select component `Joomla patch tester`
3. Try to type something in the Search box. 

### Expected result
The tooltip should be displayed above/below the search box 

### Actual result
Tooltip is getting displayed over the search input box. Please check the screenshot.

**Comment by TobsBobs** [comment]
I can confirm this bug.

**Comment by mbabker** [comment]
Patchtester issues should be logged at https://github.com/joomla-extensions/patchtester
