### ISSUE TITLE
User - User Actions Log - Need Tooltip for search field

### ISSUE THREAD

**Issue by deepa-g** [joomla/joomla-cms#26659]
### Steps to reproduce the issue
Go to Administrator Login Page
Click on Users -> User Actions Log
Check Search input box tooltip

### Expected result
After hovering on the search field tooltip should display.

### Actual result
No tooltip found

**Comment by Quy** [comment]
Please test PR #26676<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26659">issues.joomla.org/tracker/joomla-cms/26659</a>.</sub>
