### ISSUE TITLE
[4.0] Administrator: Javascript Error when ordering of items with "Ordering descending"

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#26655]
### Steps to reproduce the issue
In backend go for example in the articles list and set ordering to "Ordering descending". When you try to reorder an item you will see this javascript error in the console:

Uncaught TypeError: f.reverse is not a function

Generally trying to reorder items with "Ordering descending" is a problem at other places such as in the category list or the module list.

**Comment by Quy** [comment]
https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/system/js/draggable.es6.js#L59

> TypeError: rows.reverse is not a function

```
      if (dir === 'desc') {
        // Reverse the array
        rows.reverse();
        inputRows.reverse();
      }
```

@C-Lodder

**Comment by C-Lodder** [comment]
`reverse()` requires an array, so it's most likely that `wrapper.querySelectorAll('[name="order[]"]')` isn't returning anything.

Check the view: https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_content/tmpl/articles/default.php#L222

**Comment by brianteeman** [comment]
its not returning anything because there is nothing for it to return when there should be

**Comment by Quy** [comment]
When in descending order, ordering should be disabled. Check Categories.

**Comment by Quy** [comment]
It is returning a nodelist that `reverse` cannot be performed on. Sadly, I don't know JavaScript to provide a fix.

```
NodeList(3)
0: <input class="width-20 text-area-order hidden" type="text" name="order[]" size="5" value="2" data-order="2">​
1: <input class="width-20 text-area-order hidden" type="text" name="order[]" size="5" value="3" data-order="1">​
2: <input class="width-20 text-area-order hidden" type="text" name="order[]" size="5" value="1" data-order="3">
```

**Comment by C-Lodder** [comment]
You need to convert the nodelist to an array

`[].slice.call(document.querySelectorAll('[name="order[]"]'))`

**Comment by Quy** [comment]
Please test PR #28773.
