### ISSUE TITLE
Error occur on editing logged in Admin account.

### ISSUE THREAD

**Issue by AdityaTaware** [joomla/joomla-cms#26651]
### Steps to reproduce the issue
1. Go to the admin site.
2. Click on the User menu from the top right side.
3. Click on Save and Close or Close button.
4. The error occurs.

If you go from the user menu then it works fine.

### Expected result
The changes should saved without any error

### Actual result
Getting an error - An error has occurred. 0

### System information (as much as possible)
Windows 10
Could site![screen shot 2019-10-19 at 09 05 19](https://issues.joomla.org/uploads/1/3e5d2241fb94a1fcf59a61b9443f9a0d.png)

### Additional comments
Some times getting below 500 error string on screen

Error: "500 "https://adityajoomlafour.joomla.com/administrator/index.php�[ۏX��W��ۙ�Y" is not valid header value" is not valid header value: "https://adityajoomlafour.joomla.com/administrator/index.php�[ۏX��W��ۙ�Y" is not valid header value

**Comment by brianteeman** [comment]
I have not been able to replicate this

**Comment by Quy** [comment]
To reproduce
```
Error: "500 "http://localhost/joomla-cms-4.0-dev/administrator/index.php�[ۏX��W��۝[� ��Y]�X\�X�\" is not valid header value" is not valid header value: "http://localhost/joomla-cms-4.0-dev/administrator/index.php�[ۏX��W��۝[� ��Y]�X\�X�\" is not valid header value
```

* go to Content > Articles
* go to User Menu > Edit Account (in the upper right hand corner)
* click Close button

**Comment by Quy** [comment]
Here is the return URL:
```
aHR0cDovL2xvY2FsaG9zdC9qb29tbGEtY21zLTQuMC1kZXYvYWRtaW5pc3RyYXRvci9pbmRleC5waHA/b3B0aW9uPWNvbV9jb250ZW50JnZpZXc9YXJ0aWNsZXM=
```

```
<input type="hidden" name="return" value="<?php echo $input->getCmd('return'); ?>">
```

`getCmd` accepts only `A-Za-z0-9.-_` therefore `=` and `/` are stripped in the above URL as seen below.

```
<input type="hidden" name="return" value="aHR0cDovL2xvY2FsaG9zdC9qb29tbGEtY21zLTQuMC1kZXYvYWRtaW5pc3RyYXRvci9pbmRleC5waHAb3B0aW9uPWNvbV9jb250ZW50JnZpZXc9YXJ0aWNsZXM">
```

Would `getString` be an acceptable fix?

**Comment by SharkyKZ** [comment]
No, use BASE64 filter.

**Comment by Quy** [comment]
Can you please provide code? Thanks.

**Comment by SharkyKZ** [comment]
`$input->get('return', null, 'BASE64')` or `$input->getBase64('return')`

**Comment by Quy** [comment]
Please test PR #26776<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26651">issues.joomla.org/tracker/joomla-cms/26651</a>.</sub>
