### ISSUE TITLE
[4.0] com_menus > Create new single article by Single Article: Single Article value lost after save with error

### ISSUE THREAD

**Issue by HRIT-Florian** [joomla/joomla-cms#26657]
### Steps to reproduce the issue

1. Go to menu
2. Create new menu item
3. Select Single Article
4. Select any existing Article
4. Save the manu with an error (like save the manu with an existing menu alias)

### Expected result
Selected Single Article should be selected
![SelectArticleWithValue](https://user-images.githubusercontent.com/12803406/67142721-39b00880-f264-11e9-8fbd-0bd8079f7a86.jpg)

### Actual result
Selected Single Article has been lost
![SelectArticleWithValueLost](https://user-images.githubusercontent.com/12803406/67142724-416fad00-f264-11e9-9453-f755d6a12ea3.jpg)

### System information (as much as possible)
Joomla! 4.0.0-alpha12-dev Development [ Amani ] 19-August-2019 13:40 GMT 

### Additional comments
We should pass and catch the selected single article value

**Comment by Quy** [comment]
PR #26675<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26657">issues.joomla.org/tracker/joomla-cms/26657</a>.</sub>
