### ISSUE TITLE
[4.0] Error saving articles with Publishing Options disabled 

### ISSUE THREAD

**Issue by tecpromotion** [joomla/joomla-cms#26650]
### Steps to reproduce the issue

Go to Articles: Options -> Editing Layout tab and switch Publishing Options to **Hide**

Create a new article and save.

### Expected result

Article is saved.

### Actual result

Error message
**Save failed with the following error: Field 'metakey' doesn't have a default value**

<img width="593" alt="Screenshot 2019-10-19 11 00 42" src="https://user-images.githubusercontent.com/1752513/67140993-cefcce00-f25f-11e9-8e48-f1cde19c2c8a.png">

### System information (as much as possible)

Joomla! 4.0.0-alpha12 Alpha [ Amani ] 17-October-2019 20:13 GMT
PHP 7.3.10
MySQL 5.7 (10.4.6-MariaDB)

### Additional comments

thanks @brianteeman https://github.com/joomla/joomla-cms/pull/26629

**Comment by brianteeman** [comment]
I can confirm this bug

**Comment by tecpromotion** [comment]
@nielsnuebel will try to fix it

**Comment by nielsnuebel** [comment]
The error only occurs with new articles.

**Comment by nielsnuebel** [comment]
https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Table/Table.php#L904
throws an error message with the following content "Field 'metakey' doesn't have a default value". We have to include the required fields in https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Table/Content.php#L184 here.

**Comment by wilsonge** [comment]
PR https://github.com/joomla/joomla-cms/pull/26714
