### ISSUE TITLE
[4.0] Unpublish admin-module works only on cpanel

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#26652]
### Steps to reproduce the issue
Add a module to a dashboard on a position != cpanel.
Use chrome "well".
The module is rendered on the dashboard. And the cog for edit / unpublish appears.
Now klock unpublish

### Expected resultT
The module is unpublished

### Actual result
Nothing happens

**Comment by infograf768** [comment]
Can't reproduce.
I just tested adding a logged users module to the cpanel-content position with well and I can unpublish it Ok.

**Comment by chmst** [comment]
Yes, this is right, it iis the cpanel canvas, no matter which component. Choose "bottom" as position.

**Comment by infograf768** [comment]
Confirmed.

**Comment by chmst** [comment]
It is the javascript which sends the unpublish request and does nor recognize modules outside from cpanel. But this not my field of experience. 
We tried to prepare a PR during PBF which allows users to add modules only on position cpanel. But I am not quite sure whether this is a solution.

**Comment by infograf768** [comment]
We must allow users to add modules in any admin position imho.
For example, if one chooses to use the alternate admin menu preset, then there would be only 2 dashboards.
We definitely have to solve the js issue.

**Comment by brianteeman** [comment]
I cannot replicate this using position bottom and chrome well
@chmst can you please confirm that it hasn't been fixed elsewhere

**Comment by chmst** [comment]
Yes, it is the same. 

![module-on-bottom](https://user-images.githubusercontent.com/1035262/73617254-f2843280-461c-11ea-9e5f-29937a856046.JPG)

This is a module on position bottom with chrome well. The dropdown appears but unpublish does nothing.

**Comment by brianteeman** [comment]
Sorry I see it now. I was trying the edit button

**Comment by brianteeman** [comment]
Please test #27782
