### ISSUE TITLE
Article - Finish Publishing - Accepting date less than start publishing - need validations

### ISSUE THREAD

**Issue by snehal0904** [joomla/joomla-cms#26658]
### Steps to reproduce the issue
- Create an article
- Add Start Publishing date as today's date or any future date
- Add Finish Publishing date as any past date, it is getting accepted.

### Actual result
There should be an error message if Finish Publishing date is less than start publishing date

**Comment by nielsnuebel** [comment]
I can't confirm that. You can select it in the DatePicker but after saving it sets the start date to the end date and the end date to the start date. What I actually find crazy.
https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Table/Content.php#L268_L274

**Comment by Quy** [comment]
@richard67 Please comment and close if expected behavior. Thanks.

**Comment by richard67** [comment]
@Quy Why me? I haven’t invented that. But @nielsnuebel is right, it works that way, and comments in code look as if this was expected behavior.

**Comment by richard67** [comment]
@Quy How can I close that?

**Comment by Quy** [comment]
@richard67 You worked with dates lately so I thought you might understand it best. If you have permission, you can close it here and in the issue tracker. For now, I will close it. Thanks.
