### ISSUE TITLE
Contacts: Categories > Ordering icon, getting disappeared after applying

### ISSUE THREAD

**Issue by deepa-g** [joomla/joomla-cms#26654]
### Steps to reproduce the issue
Login to the backend of joomla 4.0.0.alpha12-dev
Go to contacts -> Categories menu
set Ordering as descending

### Expected result
Ordering Icon should display after applying it for descending case

### Actual result
Ordering icon disappeared after applying it for descending case

**Comment by Quy** [comment]
This is the same behavior as J3.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26654">issues.joomla.org/tracker/joomla-cms/26654</a>.</sub>

**Comment by brianteeman** [comment]
not sure what is meant here about an icon disppearing

**Comment by Quy** [comment]
Disabled  (inactive) where you can only sort when in ascending and not descending order.

![26654](https://user-images.githubusercontent.com/368084/69588661-2b10eb80-0f9e-11ea-8fb4-7908558365a8.jpg)
