### ISSUE TITLE
User Actions Log => Export All as CSV

### ISSUE THREAD

**Issue by vijaykhollam** [joomla/joomla-cms#26661]
### Steps to reproduce the issue
Login to Joomla Admin using one of the superuser accounts.

Go to Users => User Actions Log
Click on Export All as CSV
You can see language constant in CSV. Please see attached CSV.

### Expected result
CSV should have the correct language constants.

### System information
Joomla! 4.0.0-beta1-dev Development [ Amani ] 17-October-2019 20:21 GMT
Web Server : Apache
WebServer to PHP Interface : cgi-fcgi
PHP 7.3.8
MySQL 5.7.23-cll-lve

**Comment by alikon** [comment]
can you please attach or show a snippet of your csv... pls

**Comment by vijaykhollam** [comment]
[logs_2019-10-19_111327_GMT.txt](https://github.com/joomla/joomla-cms/files/3746602/logs_2019-10-19_111327_GMT.txt)
Pls rename extenstion from txt to csv. Github do not allow to attach csv files.

**Comment by alikon** [comment]
ok, confirmed maybe related to the more general issue of Untranslated strings like : 
#26846, #26823, etc

**Comment by manojLondhe** [comment]
@vijaykhollam @alikon pls test https://github.com/joomla/joomla-cms/pull/26913

**Comment by alikon** [comment]
please test  #26913<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26661">issues.joomla.org/tracker/joomla-cms/26661</a>.</sub>

**Comment by Quy** [comment]
Fixed in #27155<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26661">issues.joomla.org/tracker/joomla-cms/26661</a>.</sub>
