### ISSUE TITLE
Modules: Unable reorder in module after click on ascending / descending arrow

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#26668]
### Steps to reproduce the issue
Login to backend of joomla 4.0.0.alpha12-dev
Go to modules
Redorder the modules - It will work
Click on asecnding descnding
Again select the reorder 
### Expected result
Re-ordering should be work

### Actual result
Reordering is not working

https://drive.google.com/file/d/1v67TaDA3EHlAOwcRX1UemMujamhijuCO/view

**Comment by brianteeman** [comment]
Issue confirmed
```

draggable.min.js:1 Uncaught TypeError: f.reverse is not a function
    at i (draggable.min.js:1)
    at Object.<anonymous> (draggable.min.js:1)
    at dragula.min.js:1
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (dragula.min.js:1)
    at Object.e.emit (dragula.min.js:1)
    at M (dragula.min.js:1)
    at HTMLHtmlElement.L (dragula.min.js:1)
```

**Comment by Quy** [comment]
Duplicate #26655<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26668">issues.joomla.org/tracker/joomla-cms/26668</a>.</sub>
