### ISSUE TITLE
[4.0] Collapased side toolbar -  icon should display the name on hover it

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#26667]
### Steps to reproduce the issue
Login to backend of joomla 4.0.0.alpha12-dev
Click on toggle menu
Only icon get displayed

### Expected result
System should show the label for the icon. As its more user friendly

### Actual result
Only icon get displayed
![screen shot 2019-10-19 at 10 32 44](https://issues.joomla.org/uploads/1/66f88133f17bb4cd9b4d37827b5d82ef.png)

**Comment by brianteeman** [comment]
I would say it is a matter of taste. I don't see the point myself as then there would be little point in collapsing the bar to just an icon

**Comment by uthorat** [comment]
@brianteeman 
If I get the label on each icon then the collapsing bar feature will be more user-friendly. Because 
whenever I want to go to another menu I want to click on expand icon and do the needful action.
Please refer the screenshot of GitLab

![Umesh Thorat   automation · GitLab](https://user-images.githubusercontent.com/10463754/68066678-c6c58800-fd61-11e9-84b7-1976a743e4b5.png)

**Comment by brianteeman** [comment]
Sorry I was completely wrong about this and you are completely correct - especially as it is an accessibility failure when the sidebar is collapsed as there is no discernible link name. If no one else works on this I will try to propose a solution in the next few days

**Comment by Quy** [comment]
Please test PR #27347
