### ISSUE TITLE
Cancel , Save & close button should be highlighted when user hover it

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#26662]
### Steps to reproduce the issue
Login to backend of joomla 4.0.0.alpha12-dev
Go to manage menu
Click on edit module
Hover on the Cancel , Save & close option

### Expected result
Two buttons should be highlighted

### Actual result
Cancel , Save & close button is not getting highlighted
![screen shot 2019-10-19 at 10 01 25](https://issues.joomla.org/uploads/1/d1674ebfc61d6d7351568fd1e6fab5bb.png)

**Comment by Quy** [comment]
Please test PR #26678<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26662">issues.joomla.org/tracker/joomla-cms/26662</a>.</sub>
