### ISSUE TITLE
Onhover text is not completed for workflows menu

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#26664]
### Steps to reproduce the issue
Login to backend of joomla 4.0.0.alpha12-dev
Click on content menu
Select workflow menu
On hover on status entries and see the label
Click on stages counts 
On hove the status entries again

### Expected result
Hover label should display the complete text

### Actual result
An incomplete![screen shot 2019-10-19 at 10 25 53](https://issues.joomla.org/uploads/1/75a25cb2d828639b16388da166269d62.png) label get displayed.

**Comment by Quy** [comment]
PR #26673<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26664">issues.joomla.org/tracker/joomla-cms/26664</a>.</sub>
