### ISSUE TITLE
Admin -> Privacy: New Information Request - Can able to submit request with status Confirmed

### ISSUE THREAD

**Issue by AdityaTaware** [joomla/joomla-cms#26669]
### Steps to reproduce the issue
1. Go to Privacy: New Information Request
2. Inspect section and change jform[status] value to 1
3. Submit the form.

### Expected result
Should not able to change status by changing the value of jform status as this field is disabled.

### System information (as much as possible)
Win 10

### Additional comments
![screen shot 2019-10-19 at 10 44 40](https://issues.joomla.org/uploads/1/744678b6d3ebe828e1d16f41ccbb2763.png)

**Comment by Hackwar** [comment]
I just checked this and both for the frontend and backend this is not true anymore. This has since been fixed. Still, thank you for your report.
