### ISSUE TITLE
[4.0] Administrator: Overlapping elements in modal of administrator menu module

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#26665]
### Steps to reproduce the issue
In Backend create a an administrator menu module. Open the position listbox and your screen should look like this.
![pbf01](https://user-images.githubusercontent.com/9270310/67143501-56503e80-f26c-11e9-9df8-d2619f58ee60.png)
Besides that the horizontal scroller is not needed. I used the current chrome browser.

**Comment by Quy** [comment]
Unable to reproduce the overlapping. Are you using the latest nightly build?

![26665](https://user-images.githubusercontent.com/368084/67318283-27320b00-f4c0-11e9-8259-b76e914a52be.jpg)

**Comment by waader** [comment]
I used the nightly build but since then I think a patch was commited that might have solved the issue. I will have a look at it tomorrow as I have to leave office now.

**Comment by waader** [comment]
With the current nightly build it looks a bit different, but the problem still exists.
![pbf5](https://user-images.githubusercontent.com/9270310/67413558-b07d3680-f5c1-11e9-97e8-7b4fe10d973a.png)
I have tested this with the current version of chrome.

**Comment by Quy** [comment]
Can you try clearing your browser's cache and/or try a different browser to see if it is a Chrome issue? 

I still can not reproduce using Chrome Version 78.0.3904.70 on Windows 10.

**Comment by waader** [comment]
Clearing the browser cache did the trick. So this can be closed. Thanks Quy!
