### ISSUE TITLE
[[4.0]Control Pane]save-close Button design issue

### ISSUE THREAD

**Issue by Shubhampotdar94** [joomla/joomla-cms#26670]
### What needs to be fixed
      Save-close button allignment need to be fixed 

### Why this should be fixed
     It will create bad user experience

### How would you fix it
    CSS properties need to be changed

### Side Effects expected
    nothing..
![article3](https://user-images.githubusercontent.com/56750439/67143713-d3d77700-f28b-11e9-92f8-74c6116a4097.png)

**Comment by brianteeman** [comment]
There is already a pr from me for this. Can be closed

**Comment by Quy** [comment]
See PR #26513<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26670">issues.joomla.org/tracker/joomla-cms/26670</a>.</sub>
