### ISSUE TITLE
Created tags are not available in article, category

### ISSUE THREAD

**Issue by tushar33** [joomla/joomla-cms#26679]
### Steps to reproduce the issue
1. Create tags
2. Create an article or category
3. Check tag list

### Expected result
1. Created tags in the dropdown

### Actual result

1. Created tags are not available

### Additional comments
Video link
https://drive.google.com/file/d/1COnJ1sDbAFO_CZ-SGf1r12LiM81JQ0Yu/view

**Comment by Quy** [comment]
See comment https://github.com/joomla/joomla-cms/issues/23589#issuecomment-542052627

**Comment by Quy** [comment]
> As explained in #23589 and #25759 it's working as expected. The full tag list is not loaded on page load for performance reasons. If you want to load the full list, use Nested Tag Entry Mode.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26679">issues.joomla.org/tracker/joomla-cms/26679</a>.</sub>
