### ISSUE TITLE
Admin Home Dashboard : Add module to the dashboard text misalignment

### ISSUE THREAD

**Issue by mangeshmane** [joomla/joomla-cms#26671]
### Steps to reproduce the issue

Login to Joomla Admin with admin accounts.

Go to Admin => Home Dashboard
You can see the bottom area add module to the dashboard box

### Expected result

Add module to the dashboard text should be align with icon.

### Actual result
icon and text overlapping each other

**Comment by mangeshmane** [comment]
![screen shot 2019-10-19 at 10 50 42](https://issues.joomla.org/uploads/1/f0758c148b418a89f6bbca732872bf20.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26671">issues.joomla.org/tracker/joomla-cms/26671</a>.</sub>

**Comment by astridx** [comment]
For me it looks like this
![System Dashboard   test   Administration](https://user-images.githubusercontent.com/9974686/67157362-5c592480-f32b-11e9-97ce-d361f4f12565.png)

**Comment by Quy** [comment]
Duplicate #26741<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26671">issues.joomla.org/tracker/joomla-cms/26671</a>.</sub>
