### ISSUE TITLE
Create New Private Messages is not working

### ISSUE THREAD

**Issue by pallaviu** [joomla/joomla-cms#26677]
#26297 # Steps to reproduce the issue
Go to Administrator
Login with Superuser
Components > Messaging > New Private Messages
Enter Recipient email id from the system.
Add Subject & Message
Then click on the Send button
You will get following error.
![message](https://user-images.githubusercontent.com/11749390/67144058-169b4e00-f290-11e9-949c-29f32763b6d0.png)

### Expected result
The system should send an email to the valid email id.

### Actual result
Currently, the system is not sending emails to the respective valid email id.

**Comment by SharkyKZ** [comment]
Test PR #26689 please.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26677">issues.joomla.org/tracker/joomla-cms/26677</a>.</sub>
