### ISSUE TITLE
Notes categories: Unable to save the tag against the notes  category

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#26674]
### Steps to reproduce the issue
Login to backend of joomla 4.0.0.alpha12-dev
Go to Users
Go to user note categories
Create one category
Save the tags against the category
Edit or check the same category
### Expected result
Tags should be get dispalyed

### Actual result
Tag field shows blank value

https://drive.google.com/file/d/1ckAGa8rJVXCtj2UQ_hr2Jvw4I5dbKTzc/view

**Comment by SharkyKZ** [comment]
Tags are entered individually by pressing `Enter`, not as comma-separated list.

**Comment by alikon** [comment]
@SharkyKZ can we close this as expected behaviuor?

**Comment by SharkyKZ** [comment]
Yes, I think so.

**Comment by SharkyKZ** [comment]
Closed as expected behavior.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26674">issues.joomla.org/tracker/joomla-cms/26674</a>.</sub>
