### ISSUE TITLE
Articles: Categories > Showing error message while applying Change status action like unpublish

### ISSUE THREAD

**Issue by deepa-g** [joomla/joomla-cms#26672]
### Steps to reproduce the issue
Login to backend of joomla 4.0.0.alpha12-dev
Go to Articles: Categories
Select list of Categories -> click on Change Status button -> selecte Unpublish action
Showing error 

An error has occurred.
0 Argument 2 passed to Joomla\Component\Finder\Administrator\Indexer\Result::addNestedTaxonomy() must implement interface Joomla\CMS\Tree\ImmutableNodeInterface, null given, called in /home/eabbcbdv/public_html/start/joomla158/plugins/finder/content/content.php on line 322

### Expected result
Work

### Actual result
Should work

**Comment by SharkyKZ** [comment]
Please see PR #26235.

**Comment by MikaelWinther1** [comment]
indexing 30000 articles on J4.03 running index from cli i get the same error about half way through indexing... I have tried to disable the content - smart search plugin, but i get the same error.
 
php cli/joomla.php finder:index

PHP Notice:  Trying to get property 'published' of non-object in /var/www/clients/client1/web367/web/plugins/finder/content/content.php on line 323
PHP Notice:  Trying to get property 'access' of non-object in /var/www/clients/client1/web367/web/plugins/finder/content/content.php on line 323
PHP Notice:  Trying to get property 'language' of non-object in /var/www/clients/client1/web367/web/plugins/finder/content/content.php on line 323

In Result.php line 427:

  Argument 2 passed to Joomla\Component\Finder\Administrator\Indexer\Result::
  addNestedTaxonomy() must implement interface Joomla\CMS\Tree\ImmutableNodeI
  nterface, null given, called in /var/www/clients/client1/web367/web/plugins
  /finder/content/content.php on line 323
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26672">issues.joomla.org/tracker/joomla-cms/26672</a>.</sub>
