### ISSUE TITLE
Category multiselect not working when you try to create menu for featured article

### ISSUE THREAD

**Issue by pranotiTechjoomla** [joomla/joomla-cms#26686]
### Steps to reproduce the issue
Login to backend of joomla website
Go to Menus > Create menu > featured article > layout
Select multiple categories not working

### Expected result
User should be able to select multiple categories.

### Actual result
User can only select one category.

### System information (as much as possible)
PHP 7.2
joomla 4.0.0.alpha12-dev!

[screen shot 2019-10-19 at 11 58 48](https://issues.joomla.org/uploads/1/9dcc19e3c20a751aaa5973547be883ad.png)

**Comment by Quy** [comment]
Use Ctrl key to multi-select.

![26686](https://user-images.githubusercontent.com/368084/68627619-0e02f580-0493-11ea-925a-1cf2b70d8cd7.jpg)
