### ISSUE TITLE
In article while adding tag it not show suggestions in dropdown

### ISSUE THREAD

**Issue by Ekta29yadav** [joomla/joomla-cms#26684]
### Steps to reproduce the issue
In any existing article while adding tag it not showing suggestions in dropdown.

### Expected result
It should show suggestion in tag dropdown while adding it on article.

### Actual Result
Suggestions shown in tag dropdown

![screen shot 2019-10-19 at 11 45 48](https://issues.joomla.org/uploads/1/489a63e5d0b4445427fb28a21d59ce32.png)

**Comment by thite-amol** [comment]
This works if you create a tag name with a length greater than 3(Default). You can change this behaviour in the config.
