### ISSUE TITLE
When clicked on Smart Search > Help Menu it throws RuntimeException Page Error

### ISSUE THREAD

**Issue by flavia-b** [joomla/joomla-cms#26682]
### Steps to reproduce the issue
Login to backend of joomla website
Go to Components > Smart Search
Click on Option
Click on the Help button on the top-right corner

### Expected result
Help page shouldn't throw any Exception

### Actual result
When the Help page is clicked for Smart search component it shows and Exception Error
Please refer the screenshot

[screen shot 2019-10-19 at 11 36 32](https://issues.joomla.org/uploads/1/91af4dec0a39696da40fa65be53498d6.png)

### System Information 
PHP 7.2
joomla 4.0.0.alpha12-dev

**Comment by Sandra97** [comment]
Thanks for reporting the error.

The page didn't exist yet, it's why you get this error.
I created it, it works as expected now.

Please close this issue if it works fine for you too.

**Comment by Quy** [comment]
Confirmed fix.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26682">issues.joomla.org/tracker/joomla-cms/26682</a>.</sub>
