### ISSUE TITLE
Administrator : Unable to send mail form Mass Mail Users

### ISSUE THREAD

**Issue by mangeshmane** [joomla/joomla-cms#26680]
### Steps to reproduce the issue

Login to Joomla Admin with admin accounts.

Go to Admin => Mass Mail Users

Enter Subject with a space at the end e.g: "Test Subject "

Enter at Send mail button

### Expected result

Should trim space in the subject and send the mail

### Actual result
Displaying error message "Could not start mail function.![screen shot 2019-10-19 at 11 25 34](https://issues.joomla.org/uploads/1/9dc53aef46b8b3b069481eccb3da8d63.png)"

**Comment by alikon** [comment]
please test #26742 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26680">issues.joomla.org/tracker/joomla-cms/26680</a>.</sub>
