### ISSUE TITLE
[4 Alpha 12] Upload & Delete message styling required

### ISSUE THREAD

**Issue by Nishtha003** [joomla/joomla-cms#26698]
### Steps to reproduce the issue

1. Open the **Change Image popup** on either Article or Menu or Category level.
2. When we upload any media file or delete any file then message notification popup needs styling.

### Expected result
**See screenshot:** In case of Delete, similar is for Upload!
![image](https://user-images.githubusercontent.com/45933977/67145403-f1620c00-f29e-11e9-92f6-8eaf21a112f3.png)

### Actual result
Popup should be styled and clearly visible to the user

**Comment by sirlegend** [comment]
hello folks, i would like to fix this issue

**Comment by Quy** [comment]
@sirlegend Please submit a pull request. Thank you.

**Comment by Quy** [comment]
Duplicate #26663 as it relates to styling in Media.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26698">issues.joomla.org/tracker/joomla-cms/26698</a>.</sub>
