### ISSUE TITLE
[4 alpha 12] Information icon issue, details not showing in Media Manager popup

### ISSUE THREAD

**Issue by Nishtha003** [joomla/joomla-cms#26690]
The i for information icon not working on media manager popup but does show the information on Media dashboard

### Steps to reproduce the issue
1. Open the Change Image popup on either Article or Menu or Category level
2. In the popup we see the **i** icon on the right but on clicking there is no information displayed
3. Similarly if we open **Media** dashboard there on right we see the information icon that displays details about the selected folder or image.

### Expected result
In the Change image popup also the information about the selected folder or file should be displayed

### Actual result
In the Change image popup no information is seen about the folder or file but in the Media dashboard the information can be seen

### System Information
Windows 10
PHP 7.3.0

**See video for reference:** https://www.screencast.com/t/Cmzq8icQ

**Comment by Quy** [comment]
Please test PR #26985<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26690">issues.joomla.org/tracker/joomla-cms/26690</a>.</sub>
