### ISSUE TITLE
[4 Alpha 12] Users: Fields Ordering is not working

### ISSUE THREAD

**Issue by itxchandan** [joomla/joomla-cms#26697]
### Steps to reproduce the issue
* Go to Users > Fields
* and Ordering the fields

### Expected result
https://www.youtube.com/watch?v=HCAVlbLzr-U

### Actual result
https://youtu.be/wPvYd6pjvlY

### Additional comments
Same for articles

### System information (as much as possible)
Window 10
PHP 7.2.0

**Comment by brianteeman** [comment]
Unable to replicate

![fields](https://user-images.githubusercontent.com/1296369/70860367-ca2f6000-1f18-11ea-8f25-e561b5522cb9.gif)

**Comment by alikon** [comment]
no more reproducible<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26697">issues.joomla.org/tracker/joomla-cms/26697</a>.</sub>

**Comment by itxchandan** [comment]
@brianteeman 

Yes working fine.
