### ISSUE TITLE
Articles - New > Not found "Save & New" button

### ISSUE THREAD

**Issue by deepa-g** [joomla/joomla-cms#26692]
### Steps to reproduce the issue
Go to Administrator Login Page
Click on Contents -> Articles > Click on New button
Not found "Save & New" button while creating a new article

### Expected result
"Save & New" button should be present in the article form view

### Actual result
Should work

**Comment by brianteeman** [comment]
Look again

![image](https://user-images.githubusercontent.com/1296369/67145245-c4e6c980-f277-11e9-8245-6fe9e94b465b.png)

**Comment by wilsonge** [comment]
Confirmed It's there per @brianteeman 's comment
