### ISSUE TITLE
[4 Alpha 12] Heading is missing on "Template Preview" Popup

### ISSUE THREAD

**Issue by itxchandan** [joomla/joomla-cms#26691]
### Steps to reproduce the issue
* Go to **Template Customise** and click on **Template Preview** button.

### Expected result
Text should be **Template Preview** or **Preview**

![image](https://user-images.githubusercontent.com/17069784/67144771-333b8400-f298-11e9-905d-0859feb9a0fd.png)

### Actual result
Heading is missing

![2019-10-19_17-43-55](https://user-images.githubusercontent.com/17069784/67144757-1606b580-f298-11e9-846f-4b7408fcd81d.png)

### System information (as much as possible)
Window 10
PHP 7.2.19

**Comment by brianteeman** [comment]
Why should the title be displayed? What is the benefit?

**Comment by wilsonge** [comment]
It does look very awkward with the X button in the top right

**Comment by wilsonge** [comment]
PR https://github.com/joomla/joomla-cms/pull/26720
