### ISSUE TITLE
[4 Alpha 12] Display units along the file size in list view

### ISSUE THREAD

**Issue by Nishtha003** [joomla/joomla-cms#26696]
### Steps to reproduce the issue

1. Open the **Change Image popup** on either Article or Menu or Category level.
2. Choose list view, there we see a table with one of the column name as **Size**.

### Expected result
Display the units along with the size numbers.

### Actual result
Only the file size in with random numbers can be seen

**See image for reference:** https://www.screencast.com/t/2hKHY6h2qR

**Comment by brianteeman** [comment]
as numbers they also should be aligned right

**Comment by Nishtha003** [comment]
Yes minor styling changes are required!

**Comment by brianteeman** [comment]
Closed see #27819
