### ISSUE TITLE
[4 alpha 12] Change pointer style in Change image popup on list view

### ISSUE THREAD

**Issue by Nishtha003** [joomla/joomla-cms#26694]
### Steps to reproduce the issue

1. Open the **Change Image popup** on either Article or Menu or Category level.
2. On hovering over any folder or file we can see a cursor instead of the finger pointer in **list** view.

### Expected result
Instead of the cursor popup over the folders or images finger pointer should be displayed. 

### Actual result
On mouse hover over the folders we see a cursor pointer.

**See video for reference:** https://www.screencast.com/t/sl5q5mWjMqi

**Comment by brianteeman** [comment]
please test #27780
