### ISSUE TITLE
[4.0] Backend: Article Fields - subfields - display broken

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#26699]
### Steps to reproduce the issue
In backend add an article subfield. With current chrome it looks like this:
![pbf03](https://user-images.githubusercontent.com/9270310/67145631-42fc9d80-f283-11e9-80e9-83af1bd35c23.png)

**Comment by brianteeman** [comment]
There is already a PR to resolve this and loads of other errors with subfields - this can be closed

**Comment by Quy** [comment]
See PR #26614<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26699">issues.joomla.org/tracker/joomla-cms/26699</a>.</sub>
