### ISSUE TITLE
[4 alpha 12] Article count  issue and  '+' Icon design

### ISSUE THREAD

**Issue by sudhirsingh111** [joomla/joomla-cms#26695]
Reference : [Link](https://www.screencast.com/t/l4s2dxWvmlll)

### When we assign menu type as a 'List All Categories'

   1. The text colour of the article count of first category list is white
   2. There is the '+' icon only next to the first category list title and style of icon is not good

### Why this should be fixed
  
    1. User cannot see the article count of the first category
    2. We don't think there is any need of '+' icon and icon style looks weird

**Comment by jwaisner** [comment]
Confirmed this still exists in 4.0.0-beta1-dev<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26695">issues.joomla.org/tracker/joomla-cms/26695</a>.</sub>

**Comment by alikon** [comment]
please test #27408

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/27915.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26695">issues.joomla.org/tracker/joomla-cms/26695</a>.</sub>
