### ISSUE TITLE
[4 Alpha 12] Placeholder issue

### ISSUE THREAD

**Issue by itxchandan** [joomla/joomla-cms#26709]
### Steps to reproduce the issue
* Content > Create New Articles 
* Add the tags in Tag Field (Position: Right Middle)

### Expected result
![image](https://user-images.githubusercontent.com/17069784/67146056-a945e800-f2a4-11e9-84fc-23fbe05740b3.png)

### Actual result
![image](https://user-images.githubusercontent.com/17069784/67146040-7a2f7680-f2a4-11e9-913e-6864b8f5a560.png)

### System information (as much as possible)
Window 10
PHP 7.2.0

**Comment by Quy** [comment]
Duplicate #25895<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26709">issues.joomla.org/tracker/joomla-cms/26709</a>.</sub>
