### ISSUE TITLE
[4 Alpha 12] Random horizontal scroll on Change Image popup in list view

### ISSUE THREAD

**Issue by Nishtha003** [joomla/joomla-cms#26703]
### Steps to reproduce the issue

1. Open the **Change Image popup** on either Article or Menu or Category level.
2. Change the view to **List view** from the icon on the right horizontal scroll 

### Expected result
Horizontal scroll is not required there at the bottom.

### Actual result
See image for reference: https://www.screencast.com/t/O80S2LNICxn5

**Comment by Quy** [comment]
Please test PR #26988<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26703">issues.joomla.org/tracker/joomla-cms/26703</a>.</sub>
