### ISSUE TITLE
[4 Alpha 12] Category Icon & Author Icon Missing from Article According to  Published,  Created, Last Updated & Hits

### ISSUE THREAD

**Issue by lalitkumarjoomdev** [joomla/joomla-cms#26708]
### What needs to be fixed
https://www.screencast.com/t/p1sZRsZ8p4Q

**Comment by Quy** [comment]
See PR #26943<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26708">issues.joomla.org/tracker/joomla-cms/26708</a>.</sub>
