### ISSUE TITLE
[4 Alpha 12] Help link is not working on Workflows

### ISSUE THREAD

**Issue by itxchandan** [joomla/joomla-cms#26707]
### Steps to reproduce the issue
* Content > Workflows
* Click on Help Button. (Position: Top Right)

### Actual result
![image](https://user-images.githubusercontent.com/17069784/67145943-abf40d80-f2a3-11e9-9b89-425f3f304e39.png)

### System information (as much as possible)
Window 10
PHP 7.2.0

**Comment by mbabker** [comment]
No help screens exist for 4.0 right now.  The 3.x screens load when they exist (which they won’t for new features).  So this can be closed out for now, if screens are still missing near the stable release then an issue should be opened.
