### ISSUE TITLE
[4 Alpha 12] Actions dropdown style issue on "Default"

### ISSUE THREAD

**Issue by itxchandan** [joomla/joomla-cms#26706]
### Steps to reproduce the issue

* Menus > Main Menu
* Select one menu item from the list and click on "Actions" button

### Expected result
https://www.youtube.com/watch?v=WR_0_XW5T3U

### Actual result
https://www.youtube.com/watch?v=OTzCsbuAHIE

### System information (as much as possible)
Window 10
PHP 7.2.0

**Comment by brianteeman** [comment]
This was resolved by #26056

**Comment by brianteeman** [comment]
@quy @wilsonge as #26056 has been reverted please can this be reopened

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/26815
