### ISSUE TITLE
[4 Alpha 12] Batch icon creating alignment issue

### ISSUE THREAD

**Issue by itxchandan** [joomla/joomla-cms#26701]
### Steps to reproduce the issue

* Content > Articles
* Select one or more articles from the list and click on **Actions** button

### Expected result
https://www.youtube.com/watch?v=ddGT7kSbb2A

### Actual result
![image](https://user-images.githubusercontent.com/17069784/67145373-c8417b80-f29e-11e9-8fdb-b995a6f2766e.png)

### System information (as much as possible)
Window 10
PHP 7.2.0

**Comment by Quy** [comment]
See PR #26056<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26701">issues.joomla.org/tracker/joomla-cms/26701</a>.</sub>
