### ISSUE TITLE
[4 alpha 12] Hover Issue In The Workflow Status

### ISSUE THREAD

**Issue by sudhirsingh111** [joomla/joomla-cms#26700]
### Steps to reproduce the issue
Dashboard > content>workflow

### Why this should be fixed
 After hovering status tooltip is unclear

**Comment by brianteeman** [comment]
Wasn't this just fixed?

**Comment by Quy** [comment]
See PR #26664<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26700">issues.joomla.org/tracker/joomla-cms/26700</a>.</sub>
