### ISSUE TITLE
[4 Alpha 12] Joomla Installation Logo is Not Vertically Centered

### ISSUE THREAD

**Issue by lalitkumarjoomdev** [joomla/joomla-cms#26702]
### Steps to reproduce the issue
Joomla Installation

### Actual result
https://www.screencast.com/t/OIUZkrS0kfqx

### System information (as much as possible)
Window 10
PHP v7.2.19

**Comment by brianteeman** [comment]
Sorry but you will have to share the information another way as I am not going to install Flash

**Comment by lalitkumarjoomdev** [comment]
Hello,

I think the Joomla installation logo should be vertically centered.
See here: https://www.screencast.com/t/jLEs9ynpxc4j

Thanks,
Lalit

**Comment by Quy** [comment]
Please test PR #26845<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26702">issues.joomla.org/tracker/joomla-cms/26702</a>.</sub>
