### ISSUE TITLE
[4 Alpha 12] Styling issue: Changing the article state, the dropdown icon disappears

### ISSUE THREAD

**Issue by Nishtha003** [joomla/joomla-cms#26705]
### Steps to reproduce the issue

1. Go to Articles.
2. Click on Published icon, then open the **dropdown icon** disappears.

### Expected result
The dropdown icon should be seen even when we open the dropdown list.
**See image for reference:** 
![image](https://user-images.githubusercontent.com/45933977/67145869-d4c7d300-f2a2-11e9-9b0e-2168ba23f5cd.png)

### Actual result
See image for reference: 
![image](https://user-images.githubusercontent.com/45933977/67145892-18224180-f2a3-11e9-8e60-f22ac79ff4bd.png)

**Comment by leeflix** [comment]
Can I solve this issue?

**Comment by brianteeman** [comment]
You dont need to ask for permission

**Comment by Quy** [comment]
Please test PR #27164<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26705">issues.joomla.org/tracker/joomla-cms/26705</a>.</sub>
