### ISSUE TITLE
[4.0] Adding a field into an article fails

### ISSUE THREAD

**Issue by HenkZ** [joomla/joomla-cms#26718]
### Steps to reproduce the issue

1. Pre requirements: at least a field.

2. Add some text and save.

3. Put some text into the field.

4. Select the field into the article (using the buttom cms content)

### Expected result

The content of the inserted field or the label the inserted field is displayed into the article.
The way of working has to be same as eg. inserting a menu item. 

### Actual result
The fieldcontent and the field label appears neigther.

### System information (as much as possible)
Joomla! 4.0.0-beta1-dev Development [ Amani ] 17-October-2019 20:21 GMT

### Additional comments

![screen shot 2019-10-19 at 15 08 09](https://issues.joomla.org/uploads/1/b64bcd28992d871c6f173174b5691ae7.png)

**Comment by brianteeman** [comment]
The same problem occurs when trying to add a module

**Comment by brianteeman** [comment]
can someone with access tag this as j4 please

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/27743.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26718">issues.joomla.org/tracker/joomla-cms/26718</a>.</sub>
