### ISSUE TITLE
[4.0] Postgresql: Error when adding an admin menu with importing a preset

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#26713]
### Steps to reproduce the issue
In Backend add a administrator menu and select "Preset - Joomla Main Menu". This will produce the following error:

Menu was saved but failed to import the preset: 22P02, 7, FEHLER: ungültige Eingabesyntax für ganze Zahl: »« LINE 3: ...onent' AND "link" = 'index.php' AND "parent_id" = '' AND "cl... ^

**Comment by Quy** [comment]
See if PR #25949 will fix your issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26713">issues.joomla.org/tracker/joomla-cms/26713</a>.</sub>

**Comment by alikon** [comment]
please test #26807
