### ISSUE TITLE
[4.0] Poor title for installer.

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#26716]
### Steps to reproduce the issue
The installer isn't a "web" installer like whmcs et al so lets not call it that.

### Expected result
![image](https://user-images.githubusercontent.com/1850089/67147185-3151d080-f258-11e9-93fc-cab035a68bfa.png)

### Actual result
![image](https://user-images.githubusercontent.com/1850089/67147188-37e04800-f258-11e9-8936-825c71628831.png)

**Comment by Quy** [comment]
It is not necessary to create an issue if you already have a PR for it. Put all the info in the PR instead. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26716">issues.joomla.org/tracker/joomla-cms/26716</a>.</sub>

**Comment by N6REJ** [comment]
ty @Quy  I thought @brianteeman scolded me for NOT doing so.

**Comment by brianteeman** [comment]
Nope
