### ISSUE TITLE
[4 Alpha 12] Simple and Short Label Field Names

### ISSUE THREAD

**Issue by itxchandan** [joomla/joomla-cms#26712]
### Steps to reproduce the issue
During installation labels on login form are too long to understand.

### Expected result
The labels should be short and simple for better user experience. Because this way it is hard to understand what input is required.

### Actual result
![image](https://user-images.githubusercontent.com/17069784/67146240-ced3f100-f2a6-11e9-8c78-a4834d3d1f3e.png)

### Additional comments
It takes time to understand which is it and what is required.

**Comment by brianteeman** [comment]
Disagree

**Comment by C-Lodder** [comment]
Tried and failed twice already. May aswell close as this will never be done

**Comment by Quy** [comment]
Duplicate #22972

**Comment by chmst** [comment]
My2cent: Ask newbies.

The texts will be different in every language, you are writing only about english texts - and maybe the translation is better or worse - who knows. But all the contributors here can install Joomla with eyes closed or without any labels. 

It is not an issue (my opinion) but a matter of taste.

**Comment by alikon** [comment]
for me too not an issue
