### ISSUE TITLE
[4.0] Frontend: several untranslated language strings in create request view

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#26715]
### Steps to reproduce the issue
In Backend add a menu item for menu type Privacy > Create Request and in frontend visit this menu item. You will find that several language strings like
- PLG_SYSTEM_PRIVACYCONSENT_REDIRECT_MESSAGE_DEFAULT
- PLG_SYSTEM_PRIVACYCONSENT_LABEL
- PLG_SYSTEM_PRIVACYCONSENT_FIELD_LABEL *
etc. are untranslated.

**Comment by brianteeman** [comment]
The correct language file is not being loaded - looking at it now

**Comment by brianteeman** [comment]
@infograf768 could you take a look please as I dont really understand the plugin language files. Basically the language file for the plugin is not being loaded

**Comment by infograf768** [comment]
1. No need to create the menu item. Only necessary to enable that system plugin and try to login.
2. Looks like $autoloadLanguage = true; is not working for this plugin. Using $this->loadLanguage(); works better but would still not translate the Notice depending where it is placed.  Maybe should be done like actionlogs with a public function onAfterInitialise() method

I guess 4.0 has changed something somewhere.

**Comment by mbabker** [comment]
It’s a known issue with system plugins and that onBeforeExecute event I have said just needs flat out reverted.  There’s an issue still open that still hasn’t been addressed.

**Comment by mbabker** [comment]
Duplicate of #17444

**Comment by richard67** [comment]
Wow, #17444 is an unresolved release blocker from August 2017 with last activity January this year. Seems that was forgotten somehow? Ping @wilsonge .

**Comment by infograf768** [comment]
In the mean while it looks like this patch solves the issue (same code as in actionlogs as stated above.:
```
diff --git a/plugins/system/privacyconsent/privacyconsent.php b/plugins/system/privacyconsent/privacyconsent.php
index 82926e4..4fb949a 100644
--- a/plugins/system/privacyconsent/privacyconsent.php
+++ b/plugins/system/privacyconsent/privacyconsent.php
@@ -33,12 +33,4 @@
 {
 	/**
-	 * Load the language file on instantiation.
-	 *
-	 * @var    boolean
-	 * @since  3.9.0
-	 */
-	protected $autoloadLanguage = true;
-
-	/**
 	 * Application object.
 	 *
@@ -72,4 +64,17 @@
 
 	/**
+	 * Listener for the `onAfterInitialise` event
+	 *
+	 * @return  void
+	 *
+	 * @since   4.0
+	 */
+	public function onAfterInitialise()
+	{
+		// Load plugin language files.
+		$this->loadLanguage();
+	}
+
+	/**
 	 * Adds additional fields to the user editing form
 	 *
```
@waader 
Can you test?

**Comment by brianteeman** [comment]
This looks like the fix I had to do in other plugins so it should be good to go BUT the root issue will need to be fixed as it will break lots of plugins

**Comment by waader** [comment]
@infograf768: Yes, that works.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/27155.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26715">issues.joomla.org/tracker/joomla-cms/26715</a>.</sub>
