### ISSUE TITLE
[4.0] Text for batch on fields says move or copy, but in reality no copy exists due to JavaScript error

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#26726]
### Steps to reproduce the issue
![image](https://user-images.githubusercontent.com/4665225/67149428-1b1d3200-f2a3-11e9-8887-ed0e492e5ccc.png)

Create two field groups.
Create a few fields.
Select more than one field.
Go to Batch -> move or copy

### Expected result
You can move or copy

### Actual result
You can only move but not copy.

There is a bug that is causing the javascript not changing the code from display:none

```
Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at HTMLDocument.a (batch-language.min.js?ae99f75e6db25b54b1b18001740f8a0e:1)
a @ batch-language.min.js?ae99f75e6db25b54b1b18001740f8a0e:1
```

**Comment by brianteeman** [comment]
It does exist but there is a bug that is causing the javascript not changing the code from display:none

```
Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at HTMLDocument.a (batch-language.min.js?ae99f75e6db25b54b1b18001740f8a0e:1)
a @ batch-language.min.js?ae99f75e6db25b54b1b18001740f8a0e:1
```

**Comment by uglyeoin** [comment]
@brianteeman do you know if that bug has already been reported?  If so I will close this PR

**Comment by brianteeman** [comment]
its a new bug - well discovered

**Comment by uglyeoin** [comment]
Then I will update the description

**Comment by Quy** [comment]
Please test PR #26731<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26726">issues.joomla.org/tracker/joomla-cms/26726</a>.</sub>
