### ISSUE TITLE
Calendar filter in banners component

### ISSUE THREAD

**Issue by fabrice4821** [joomla/joomla-cms#26738]
### Steps to reproduce the issue
Go to Banners component.
Go to tracks.
Click on "Shearch tools" button.
Click on the icon for open the calendar.

Try to used the navigation to change the year or the month.

### Expected result

When you click to up or down the year (or month), they must only up or down the year for have the possibility to up or down many years.

### Actual result

When you click to up or down the year, they change one year and enable the filter.

**Comment by brianteeman** [comment]
I can confirm this bug

**Comment by Quy** [comment]
What is the bug? It is the same behavior as J3.

**Comment by brianteeman** [comment]
> When you click to up or down the year (or month), they must only up or down the year for have the possibility to up or down many years.

Compare that to the calendar anywhere else. Basically it is reloading the page on every change

**Comment by Quy** [comment]
This is the same behavior as in J3. In the filter, it is an exception. Whenever a selection is made, it automatically submits to return the found results.

**Comment by brianteeman** [comment]
Doesn't mean that its not a bug

**Comment by fabrice4821** [comment]
If it's not a bug, how made for select a date ?

**Comment by brianteeman** [comment]
exactly - @quy please enlighten us as to why this is not a bug

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/27203.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26738">issues.joomla.org/tracker/joomla-cms/26738</a>.</sub>
