### ISSUE TITLE
[4.0][SCSS][Codestyle][Atum][RFC] Indents & line-breaks

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#26759]
Codestyle for indents and line breaks varies across SCSS files within the Atum template. In general, the following standards appear to be followed however there is places where it is not.

```JSON
"end_with_newline": true,
"indent_char": " ",
"indent_size": 2,
"newline_between_rules": true,
"selector_separator_newline": true,
"space_around_combinator": true,
```

**Comment by brianteeman** [comment]
shouldn't there be a lint or sniff (I forget the correct term) to test this?

**Comment by ciar4n** [comment]
I believe @C-Lodder had set up hound but it appears to have been disabled. However, if I remember correctly it didn't check line-breaks and indents (I could be wrong on this).

**Comment by C-Lodder** [comment]
@Hackwar decided to exclude the SCSS files for some reason: https://github.com/joomla/joomla-cms/pull/25645

Which explains why the SCSS never gets linted in PRs

**Comment by Hackwar** [comment]
The way I understood the code, it was supposed to be the other way around. If that isn't the case, then I have to apologise and it was an error on my part.

**Comment by C-Lodder** [comment]
https://github.com/joomla/joomla-cms/pull/25645/files#diff-e9419947d819494941dc8d981f0e128cL5 ;)

No worries. Just needs reverting and adjusting

**Comment by C-Lodder** [comment]
Actually apoligies on my part. It looks like you didn't move them into the exclude flag.

In which case I'm not sure why the SCSS isn't being linted. Could try reverting as a test

**Comment by ciar4n** [comment]
PR.. https://github.com/joomla/joomla-cms/pull/26793

Maybe someone could open a separate issue for hound/linting
