### ISSUE TITLE
[4.0] Banners are not displayed

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#26763]
### Steps to reproduce the issue
Define a banner and publish the banner modul. On frontend to will get

Warning: Invalid argument supplied for foreach() in
\components\com_banners\Model\BannersModel.php on line 211
Warning: Invalid argument supplied for foreach() in \modules\mod_banners\tmpl\default.php on line 23

**Comment by SharkyKZ** [comment]
Using PostgreSQL?

**Comment by waader** [comment]
mysql 8.0.17

**Comment by alikon** [comment]
please test #26767
