### ISSUE TITLE
[3.9.12] Error reporting does not work

### ISSUE THREAD

**Issue by interno15** [joomla/joomla-cms#26766]
### Steps to reproduce the issue
main menu -> system -> global configuration -> [TAB] Error Reporting -> Select Maximum -> Save

### Expected result
display of the error report

### Actual result
the website goes down

### System information (as much as possible)
Tipo database           mysql
Versione database 	10.1.41-MariaDB-cll-lve
Collation database 	latin1_swedish_ci
Collation connessione database 	utf8mb4_general_ci
Versione PHP 	7.1.32
Web Server 	Apache
WebServer interfaccia PHP 	litespeed
Versione di Joomla! 	Joomla! 3.9.12 Stable [ Amani ] 24-September-2019 15:00 GMT
Versione piattaforma Joomla! 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments
none

**Comment by SharkyKZ** [comment]
>the website goes down

How exactly? Are you getting a blank page? Or content encoding errors?

**Comment by interno15** [comment]
<img width="1005" alt="Schermata 2019-10-22 alle 17 59 55" src="https://user-images.githubusercontent.com/56885073/67305567-d0472880-f4f5-11e9-9d15-759100e0b5f5.png">

**Comment by interno15** [comment]
content encoding errors

**Comment by brianteeman** [comment]
This really should be asked on the forum as it is site/server specific

**Comment by Quy** [comment]
Please ask help in [Joomla Forum](https://forum.joomla.org/).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26766">issues.joomla.org/tracker/joomla-cms/26766</a>.</sub>
