### ISSUE TITLE
[4.0] Tagged Items View - Parameter "Select Content Type" lists non taggable items

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#26764]
### Steps to reproduce the issue
Banner and Banner Client can not be tagged but the are selectable items of the parameter "Select Content Type" in the Tagged Items View.

**Comment by brianteeman** [comment]
Can you please retest on a completely clean install. I suspect a database error in your install

**Comment by SharkyKZ** [comment]
The report is correct. Content Type field lists all entries from `#__content_types` table. We don't distinguish taggable and non-taggable content types here.

**Comment by brianteeman** [comment]
Sorry - I was looking in a different place
![image](https://user-images.githubusercontent.com/1296369/67721708-2244ee00-f9cf-11e9-9016-c1393f03a38c.png)

**Comment by brianteeman** [comment]
The only way that I can find to reasonably prevent this is to hard code an exclusion for newsfeeds and thats not really acceptable as there may be other non taggable content types installed with an extension.

For that reason I would acknowledge that this is not optimum but it should be a won't fix
