### ISSUE TITLE
[4.0] Debug kills site

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26761]
As the title says

`Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Debug\ExceptionHandler::handle() must be an instance of Exception, instance of Error given in C:\htdocs\joomla-cms\libraries\vendor\symfony\debug\ExceptionHandler.php:118 Stack trace: #0 [internal function]: Symfony\Component\Debug\ExceptionHandler->handle(Object(Error)) #1 {main} thrown in C:\htdocs\joomla-cms\libraries\vendor\symfony\debug\ExceptionHandler.php on line 118`

**Comment by SharkyKZ** [comment]
Run `composer install`.

**Comment by brianteeman** [comment]
thanks
