### ISSUE TITLE
[4.0] Error in theme.min.js

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#26768]
### Steps to reproduce the issue
I tried to insert a module in an article but that failed because of the following error that can be seen in the console:
theme.min.js:9 Error: <path> attribute d: Expected number, "…4.99-12 10zM2224h-18v-12h3.934c0…".

**Comment by richard67** [comment]
@waader Could you switch on debug for system in global configuration? If debug is on, the unminified version of the JS is loaded, which will lead to better information where the error is.

**Comment by waader** [comment]
Debug is now on but theme.min.js still is loaded - the error message didn´t change. I noticed that the error messages get fired right after clicking on the button "CMS Content".

**Comment by waader** [comment]
@richard67 Does this behaviour with debug enabled hold true also for minified versions that come from a third party component like in this case from tinymce (/media/vendor/tinymce/themes/silver/theme.min.js)?

**Comment by richard67** [comment]
@waader Don't know. Depends in which of the possible ways they are included, I think.

**Comment by brianteeman** [comment]
I am not sure what the error is but the js error you saw (which I can confirm) is a side effect of the real error. You can tell that because even if you have no editor you can not insert a module into an article

**Comment by brianteeman** [comment]
Same bug as seen in #26718

**Comment by infograf768** [comment]
The error I get here concerns skipTo.js and not theme.
 `Empty string passed to getElementById(). skipTo.js:455:28`

Line 455
`var element = document.getElementById(location.hash.substring(1));`

The error is displayed AFTER clicking on a module in the pop-up.

**Comment by Quy** [comment]
Please test PR #27499
