### ISSUE TITLE
[4.0] Styling issue with Save & Close button on mobile

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#26771]
@brianteeman 

Tested on a desktop.

### Styling issue when adding a new item

![26513b](https://user-images.githubusercontent.com/368084/67325380-e7702100-f4c9-11e9-939b-cb8f567e0f9b.jpg)

**Comment by brianteeman** [comment]
Why was this closed?

**Comment by Quy** [comment]
Duplicate #26543

**Comment by infograf768** [comment]
Imho, these are different issues ( specially concerning the save and close) and I confirm both.

**Comment by Quy** [comment]
Removed the duplicate issue and reopen to reflect the other issue.

**Comment by Subhang23** [comment]
I would like to work on this if possible.

**Comment by Quy** [comment]
See #27816. Thanks! @Subhang23
