### ISSUE TITLE
404 Article not found generated for Author's unpublished article.

### ISSUE THREAD

**Issue by bob-bob-bobbing** [joomla/joomla-cms#26773]
### Steps to reproduce the issue
Log in to user in Author group with Edit Own permission.
Submit an article.
Ensure it is unpublished.
Follow link eg. /index.php?option=com_content&view=article&id=26

My links were created in a module.[code-for-github.txt](https://issues.joomla.org/uploads/1/4e18f5df97d931f0ce0cc8f6a8baf363.txt)

### Expected result
Article displayed and editable.

### Actual result
Error 404 Article not found.

### System information (as much as possible)
Joomla! 3.9.12 Stable [ Amani ]
Joomla Platform 13.1.0 Stable [ Curiosity ]
Php 7.3.10 

### Additional comments
If Edit permission is set or the article is published, the error does not occur.
[systeminfo-2019-10-22T22_42_19+01_00.txt](https://issues.joomla.org/uploads/1/25fbe74d058110200f595966779ed948.txt)
![screen shot 2019-10-22 at 22 43 28](https://issues.joomla.org/uploads/1/9a23917012c2a41b4df599056cebbbec.jpg)

**Comment by Quy** [comment]
Duplicate #17812 & #25757<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26773">issues.joomla.org/tracker/joomla-cms/26773</a>.</sub>
