### ISSUE TITLE
Radio buttons are not styled when showing forms in modals in Protostar

### ISSUE THREAD

**Issue by obuisard** [joomla/joomla-cms#26774]
### Steps to reproduce the issue

Open a form containing radio buttons in a modal when using the Protostar template. 

### Expected result

Radio buttons show with styling.

### Actual result

The radio buttons have no style.

### System information (as much as possible)

Under Joomla 3.

**Comment by Quy** [comment]
See PR #26775<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26774">issues.joomla.org/tracker/joomla-cms/26774</a>.</sub>
