### ISSUE TITLE
[Edit Content Language] without ISO country code

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#26770]
### Is your feature request related to a problem? Please describe.

According to the official Google reference:
[https://support.google.com/webmasters/answer/189077](url)

**Supported language/region codes**

The value of the hreflang attribute identifies the language (in ISO 639-1 format) and optionally a region (in ISO 3166-1 Alpha 2 format) of an alternate URL. (The language need not be related to the region.) For example:

    de: German language content, independent of region
    en-GB: English language content, for GB users
    de-ES: German language content, for users in Spain

**Do not specify a country code by itself.** Google does not automatically derive the language from the country code. You can specify a language code by itself if you want to simplify your labeling.  Adding the country code after the language to restrict the page to a specific region.  Examples:

    be: Belarusian language, independent of region (not Belgium French)
    nl-be: Dutch for Belgium
    fr-be: French for Belgium 

### Describe the solution you'd like
Allow saving language settings without specifying a country code. 
**Field:** Language Tag

For example:
"en" or "de", without "en-GB" or "en-US"

![image](https://sun9-63.userapi.com/c858136/v858136570/b41d7/dJQWig965J4.jpg)

### Additional context
I do not want to limit the English language on my site to only one country - the United States or Great Britain. My site is not tied to a specific country; my site is tied to a language.

I believe that at the moment this is a very serious problem that must be resolved. It should be possible to save site settings without specifying a country.

This is still very bad for the SEO. For example, if I specify a country, then my site will be higher only in a certain country - for example, in the USA, because the country code is indicated, but in the UK the site will not have priority, despite the fact that the language on the site will be English.

**Comment by SharkyKZ** [comment]
You can use "System - Language Code" plugin to change language codes in HTML.

**Comment by 4digitalworld** [comment]
> 
> 
> You can use "System - Language Code" plugin to change language codes in HTML.

Thanks, just found this. Nevertheless, this is not too obvious. I believe that it is necessary to give the opportunity to preserve the language of the site, without reference to the country in this parameter settings.

**Comment by infograf768** [comment]
We HAVE to specify the country code for the language tag as it is the only way to differentiate variations of a language when a site has en-GB, en-US, en-XX installed. This is the only way to redirect to the correct pages on a multingual site. Just look at the hierarchy of the language folders.

You are free to use the Language Code plugin for what appears on the source of the page.
This is not a bug.
Closing.
