### ISSUE TITLE
[PostgreSQL] Banners don't work when filtering by meta keywords

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#26788]
### Steps to reproduce the issue

Enter some meta keywords in Global Configuration.
Create a banner, enter same meta keywords.
Publish a banner module and enable filtering by meta keywords.

### Expected result

Banner shown.

### Actual result

Banner not shown.

### System information (as much as possible)

PostgreSQL 11.1

### Additional comments

The error set by the model is this:

>42601, 7, ERROR: syntax error at or near "REGEXP" LINE 4: ...fix=0 AND cl.own_prefix=0 AND 1) AND (a.metakey REGEXP '[[... ^

Coming from here:

https://github.com/joomla/joomla-cms/blob/0aea5c3d8fe06fb758c4ff08239639b9857e915b/components/com_banners/models/banners.php#L164

**Comment by alikon** [comment]
please test #26791<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26788">issues.joomla.org/tracker/joomla-cms/26788</a>.</sub>

**Comment by SharkyKZ** [comment]
Closed as having Pull Request #26791.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26788">issues.joomla.org/tracker/joomla-cms/26788</a>.</sub>
