### ISSUE TITLE
[4.0] Display issue with article field of typ "subfields" or "repeatable"

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#26784]
### Steps to reproduce the issue
In Backend define for example 2 additional text fields for articles and after that 1 field of type "subfields" or "repeatable".  This screenshot shows the problem:
![pbf6](https://user-images.githubusercontent.com/9270310/67420780-8d598380-f5cf-11e9-8cff-0c2e6ccfd1f2.png)

**Comment by Quy** [comment]
Please test PR #26923<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26784">issues.joomla.org/tracker/joomla-cms/26784</a>.</sub>
