### ISSUE TITLE
Pop Up Box does not close

### ISSUE THREAD

**Issue by cybersalt** [joomla/joomla-cms#26785]
### Steps to reproduce the issue

Go to system> mail templates

Open an existing mail template and save it.

Green popup box appears after save

### Expected result

Click x to close popup box and box should close

### Actual result

Click x to close popup box, green box closes but gray box remains place

### System information (as much as possible)

Windows 10 FireFox 70 | Chrome Version 78.0.3904.70 (both incognito and non-incognito mode)

### Additional comments

Was unsure of what to put in the build info so I used the latest commit info. Sorry if that was wrong - this is my first ever bug report!

**Comment by Quy** [comment]
Duplicate #25850. Thank you for reporting.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26785">issues.joomla.org/tracker/joomla-cms/26785</a>.</sub>
