### ISSUE TITLE
[4.0] Redirect doesn´t function

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#26782]
### Steps to reproduce the issue
To see whether redirect does function I manipulated a URL in frontend. Then I get the following error:
The requested page can't be found. ....
500 PLG_SYSTEM_REDIRECT_ERROR_UPDATING_DATABASE

Tested with mysql 8.0.17.

**Comment by richard67** [comment]
@waader Which kind of J4 did you use? Current 4.0-dev branch? Or 4.0 Alpha 12?

Could you export structure of table `#__redirect_links` e.g. as create table statement, or check if columns `created_date` and `modified_date` have a default value or not, and if they have one, which one? Or in other words: Is PR #26381 already included? Please don't check the files only, check also in database.

And your J4, has that been a new installation, or has it been updated from a previous J4 alpha or daily build (which is not supported)?

**Comment by richard67** [comment]
@waader Please test PR #26799 .

**Comment by richard67** [comment]
P.S. ... and forget my questions above.

**Comment by richard67** [comment]
@waader Could you close this issue since it’s solved with my PR? Thanks.
