### ISSUE TITLE
[4.0] Edit icon frontend

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26783]
On the front end of the site the wrong icon is being displayed for the edit article link. It should be edit but its getting eye-slash

https://github.com/joomla/joomla-cms/blob/e2b623cef24cbbda6db386fdeab5beda4398205b/layouts/joomla/content/icons/edit.php#L32-L38

I can't get my head around all the conditionals here and it looks like its related to the date changes

**Comment by richard67** [comment]
@brianteeman Please test PR #26756 . It solves this issue.

**Comment by richard67** [comment]
@brianteeman I see, is already RTC, no need to test. But it solves the issue, definitely.
