### ISSUE TITLE
[4.0] URL Custom Fields - add option to add title display for URL

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#26801]
### Is your feature request related to a problem? Please describe.
I have just created a standard jcfield for URL entry. Unfortunately, the URL is very long, so on a small device it breaks out of the container.

### Describe the solution you'd like
Add the option to display a title instead of the full URL

### Additional context
This would be useful in J3, too.

**Comment by brianteeman** [comment]
Whoever codes this the same technique can be used on the image field to add the alt description

**Comment by Scrabble96** [comment]
> 
> 
> Whoever codes this the same technique can be used on the image field to add the alt description

That is a very good suggestion.

**Comment by Scrabble96** [comment]
Even better would be the option to add a hyperlink to the image as well, please.

**Comment by brianteeman** [comment]
Closed see #27571 for a single link
