### ISSUE TITLE
"D" missing in default backend template style

### ISSUE THREAD

**Issue by horssenp** [joomla/joomla-cms#26804]
### Steps to reproduce the issue
Got o User Basic Settings

### Expected result

In english the word "Date" or in Dutch "Datum" 
![Joomla _Date](https://user-images.githubusercontent.com/17496476/67499963-3791e380-f682-11e9-9a3c-5d83b34f0b20.JPG)

**Comment by brianteeman** [comment]
I think you uploaded the wrong screenshot

**Comment by brianteeman** [comment]
Ah - I see the confusion now.

The word is "Atum" - that is the name of the template.

https://en.wikipedia.org/wiki/Atum

This can be closed
