### ISSUE TITLE
Feature request: Allow change of custom field type after field has been saved

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#26802]
### Is your feature request related to a problem? Please describe.
This applies to both J3x and J4x:
After creating some customer jcfields (I'm new to these) I decided that the format - text area in this instance, as it won't take line breaks - was not suitable and the text editor was preferable. Having saved the field, it is not possible to change its type, so I had to delete it and start again with a new one.

### Describe the solution you'd like
Make changing the field type after creation possible.

### Additional context
This is similar to menus and modules:
1. You can change a menu type after creating the item
2. You CAN'T change a module type after creating the module

**Comment by mbabker** [comment]
This isn't really practical, for the same reason as modules.  It's essentially an entirely new thing with an entirely different data structure.  In a lot of cases, changing the field type is going to result in incompatible configuration or data storage (imagine switching from a textarea to a plain text input).

**Comment by alikon** [comment]
Expected Behaviour
