### ISSUE TITLE
[3.9] Tooltip in Modules:Banners > Search by Meta Keyword misleading

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#26819]
### Steps to reproduce the issue
It says "Banner is selected by matching the banner tags to the current document meta keywords". But there are no tags in a banner. I think matching is done by the content of the field "Meta Keywords".

**Comment by alikon** [comment]
please test  #26883<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26819">issues.joomla.org/tracker/joomla-cms/26819</a>.</sub>
