### ISSUE TITLE
[4.0] Export of Banner Tracks not possible

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#26818]
### Steps to reproduce the issue
After click on the export button in menu Banners > Tracks > Button Export the appearing modal window is grayed out and no further action is possible.

Tested with current firefox.

**Comment by alikon** [comment]
confirmed
![Screenshot from 2019-10-27 10-58-23](https://user-images.githubusercontent.com/181681/67632801-ba948300-f8a8-11e9-9cf2-c72c15663c6a.png)

**Comment by alikon** [comment]
please test #26848 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26818">issues.joomla.org/tracker/joomla-cms/26818</a>.</sub>
