### ISSUE TITLE
[4.0] Replace symfony/debug

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#26816]
Symfony 4.4 deprecates the Debug component in favor of a couple of newer error handling components.  The CMS should be updated before 4.0 ships to replace the deprecated component.

Symfony 4.4 will ship in November 2019 so it’s fine to start on this work now and just flip to a dev dependency for a few weeks.

**Comment by richard67** [comment]
Does anybody have an idea what shall be used as replacement? Symphony 4.4's newer error handling compontents, or something else?

**Comment by mbabker** [comment]
The appropriate Symfony component is fine.  They basically broke up the Debug component into smaller components with separated responsibilities, not completely abandon the code.

**Comment by wilsonge** [comment]
Finally got around to this. Please test https://github.com/joomla/joomla-cms/pull/27470
