### ISSUE TITLE
[4.0] Alert background

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26817]
### Steps to reproduce the issue
Do something that will create multiple alerts. eg install a patch with com_patchtesters

### Expected result
Multiple alerts that are independent of each other
![image](https://user-images.githubusercontent.com/1296369/67591359-2960c780-f755-11e9-91af-59a2e4b1961c.png)

### Actual result
All the alerts are on a div with a gray background

![image](https://user-images.githubusercontent.com/1296369/67591309-11894380-f755-11e9-8165-5dbedf1a8b33.png)

**Comment by Quy** [comment]
Similar to #25890

**Comment by brianteeman** [comment]
No it's different

**Comment by vlaucht** [comment]
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/scss/blocks/_system-message.scss#L2 

I guess if `background: var(--atum-bg-light);` and probably `box-shadow: 3px 3px 11px 0px rgba(0, 0, 0, 0.3);` is removed, the container should be transparent.

**Comment by Quy** [comment]
@brianteeman Please test PR #27394
