### ISSUE TITLE
PatchTester alert window and filter missing left margin

### ISSUE THREAD

**Issue by vlaucht** [joomla/joomla-cms#26826]
### Steps to reproduce the issue

1. Install latest Patch Tester
2. go to Components --> Joomla! Patch Tester

### Expected result
alert window and filter should have a left margin 

### Actual result

![screen shot 2019-10-26 at 11 06 20](https://issues.joomla.org/uploads/1/38f7a3a41c6330857bada741bb57f339.png)

### Additional comments
Since I'm new to the Joomla Community, I'm not quite sure if bug reports regarding the patch tester extension should be submitted here. I can fix this and file a PR to the patch tester repo.

**Comment by Quy** [comment]
Patchtester issues should be logged at https://github.com/joomla-extensions/patchtester<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26826">issues.joomla.org/tracker/joomla-cms/26826</a>.</sub>
