### ISSUE TITLE
[4.0]  Undefined index: featured_up/featured_down

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#26828]
### Steps to reproduce the issue
@richard67 

Log in administration control panel.
Check PHP error log.

```
PHP Notice:  Undefined property: Joomla\Component\Content\Administrator\Table\ArticleTable::$featured_up in \libraries\src\Table\Content.php on line 278
PHP Notice:  Undefined index: featured_up in \administrator\components\com_content\Model\ArticleModel.php on line 950
PHP Notice:  Undefined index: featured_down in \administrator\components\com_content\Model\ArticleModel.php on line 950
```

**Comment by richard67** [comment]
Seems to be related to [https://github.com/joomla/joomla-cms/commit/e5a67c237e110f1c18952f2e99061de95fd367cc](https://github.com/joomla/joomla-cms/commit/e5a67c237e110f1c18952f2e99061de95fd367cc).

**Comment by richard67** [comment]
@Quy But I could not reproduce. Is your database up to date with the commit I've linked in my previous comment?

**Comment by richard67** [comment]
@Quy Look in that commit here: [https://github.com/joomla/joomla-cms/commit/e5a67c237e110f1c18952f2e99061de95fd367cc#diff-db94a7a8f9f1edf368d10d7b96302889R948](https://github.com/joomla/joomla-cms/commit/e5a67c237e110f1c18952f2e99061de95fd367cc#diff-db94a7a8f9f1edf368d10d7b96302889R948). There is no check `isset($data['featured_up']` or  `isset($data['featured_up']`. Could that be the problem?

**Comment by Quy** [comment]
I did a refresh install (not using PatchTester) of the latest dev branch after PR #25979 was merged.

**Comment by richard67** [comment]
I did the same. Just doing it again.

**Comment by richard67** [comment]
Still can't reproduce.

**Comment by richard67** [comment]
@Quy You're testing on Windows? I see backslashes in your error log. I'm testing on Linux. Maybe that's the difference???

**Comment by richard67** [comment]
But what could cause that then? Only a recent change in class names regarding upper and lower case affecting this function and not working with Windows ... I don't remember such thing. So the only other thing could be differences in database? I have no idea.

**Comment by Quy** [comment]
Yes on Windows. 

Installing the `Blog Sample Data` results in `There is an error in a sample data plugin. Response is invalid.`.

**Comment by richard67** [comment]
Sample data is known issue as far as I remember. Unfortunately I don't have Windows testing environment to reproduce.

**Comment by Quy** [comment]
Know issue with `Testing Sample Data`, but not with `Blog Sample Data`.

Here is line 278. It is missing the null check.
```
if ($this->featured_up && $this->featured_down && $this->featured_down < $this->featured_up)
```

**Comment by richard67** [comment]
278 where?

**Comment by richard67** [comment]
ahh got it

**Comment by richard67** [comment]
@Quy Do you wanna make a PR or shall I do it?

**Comment by Quy** [comment]
Go for it please.

**Comment by richard67** [comment]
On the way.

**Comment by richard67** [comment]
Done, PR #26829 .

**Comment by Quy** [comment]
Thank you!
