### ISSUE TITLE
[4.0] Action Logs mail not translated

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#26823]
### Steps to reproduce the issue
Enable Action Logs plugin and set in User parameters User Actions Logs Options send mail to yes:
![Screen Shot 2019-10-26 at 06 48 24](https://user-images.githubusercontent.com/869724/67614395-a5422a80-f7bc-11e9-86a8-2906409ad0b9.png)

### Result
![Screen Shot 2019-10-26 at 06 50 10](https://user-images.githubusercontent.com/869724/67614476-e0912900-f7bd-11e9-8833-d2b68e9cd90b.png)

**Comment by mbabker** [comment]
I haven’t looked in a while but IIRC the action log plugin group get loaded by the action log system plugin and if it’s happening in the constructor or something early then it’s probably a similar issue to #26715 and ultimately leads back to #17444

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/27155.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26823">issues.joomla.org/tracker/joomla-cms/26823</a>.</sub>
