### ISSUE TITLE
[4.0] Missing closing

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#26827]
### Steps to reproduce the issue
@bembelimen Might be related to this commit https://github.com/joomla/joomla-cms/commit/afd1913f189150d6e96988013c8001215d5a4bdf#diff-cb262d040d4f93285ea37cc843632cfd

Edit a user.
View page source.
Missing closing `</div>`

### Actual result

![div](https://user-images.githubusercontent.com/368084/67619035-6fe11100-f7ab-11e9-8e6c-b8ce13e92d0a.jpg)

**Comment by brianteeman** [comment]
How to replicate?

**Comment by SharkyKZ** [comment]
Edit a user in backend.

**Comment by brianteeman** [comment]
I am not seeing anything missing

**Comment by Quy** [comment]
You will not visibility see the issue. However, view the page source where `</fieldset>` is highlighted red. It is missing `</div>` before it.

**Comment by Quy** [comment]
Please test PR #26998<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26827">issues.joomla.org/tracker/joomla-cms/26827</a>.</sub>
