### ISSUE TITLE
[4.0] Home Dashboard broken

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26834]
Current branch- everything is working except for the home dashboard where I have the error

`0 Return value of Joomla\Component\Installer\Administrator\Helper\InstallerHelper::getInstallationXML() must be an instance of SimpleXMLElement, boolean returned`

**Comment by SharkyKZ** [comment]
Please enable debug and post stack trace.

**Comment by brianteeman** [comment]
my error - oops
