### ISSUE TITLE
paypal cannot find paypal address

### ISSUE THREAD

**Issue by tubular-well** [joomla/joomla-cms#26836]
### Steps to reproduce the issue
joomla customer pays with paypal
transaction resolts in mail to admin :smile: 
"An error with your payment method paypal on your store Tubular Well. The details are logged in the file paypal.4.log.php

. The VirtueMart Team"

Contents of paypal.4.log : 
#
#<?php die("Forbidden."); ?>

2019-10-26 21:12:03 ERROR checkPaypalIps: Error with REMOTE IP ADDRESS = 66.211.170.66.
                        The remote address of the script posting to this notify script does not match a valid PayPal IP address

            These are the valid IP Addresses: 173.0.84.8,66.211.169.17,173.0.84.40,173.0.88.40,173.0.88.8,173.0.81.1,173.0.81.33The Order ID received was: YERI0330"

running : 

Systeminformation
Inställningar 	Värde
 
PHP byggd på 	Linux metro 2.6.32-042stab136.1 #1 SMP Wed Feb 27 09:04:24 MSK 2019 x86_64
Databastyp 	mysql
Databasversion 	5.5.5-10.1.41-MariaDB-0+deb9u1
Sorteringsordning 	utf8mb4_general_ci
Databasanslutningen sortering 	utf8mb4_general_ci
PHP Version 	7.0.33-0+deb9u5
Webbserver 	Apache/2.4.25 (Debian)
Webbserver till PHP-gränssnitt 	apache2handler
Joomlaversion 	Joomla! 3.9.10 Stable [ Amani ] 10-July-2019 15:57 GMT
Joomla! platformsversion 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Webbklient 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:69.0) Gecko/20100101 Firefox/69.0

**Comment by infograf768** [comment]
See http://forum.virtuemart.net/index.php?topic=131735.0

This has nothing to do with Joomla. This github concerns Joomla. Closing. Please post on Virtuemart forums.
