### ISSUE TITLE
[3.9] [4.0] [com_fields]  elements must only directly contain properly-ordered  and  groups,  or  elements

### ISSUE THREAD

**Issue by eddiekonczal** [joomla/joomla-cms#26849]
### What needs to be fixed

Custom fields are not displayed properly within definition lists.  The definition lists include only `<dd>` elements, and not the corresponding `<dt>` elements.

### Why this should be fixed

Without this fix, definition lists will violate the WCAG 2.0 accessibility standard "Ensures `<dl>` elements are structured correctly".

When not empty, element does not have at least one `<dt>` element followed by at least one `<dd>` element

c.f.  https://dequeuniversity.com/rules/axe/3.2/definition-list?application=AxeChrome

### How would you fix it

`$content` needs to be separated into separate elements: the field name (which should populate the `dt` element) and the field value (which should populate the `dd` element)

**Comment by eddiekonczal** [comment]
Code to be replaced:

line 72 in `/components/com_fields/layouts/fields/render.php` 

`$output[] = '<dd class="field-entry ' . $class . '">' . $content . '</dd>';`

Suggested new code:

line 72 in `/components/com_fields/layouts/fields/render.php` 

`$output[] = '<dt class="field-entry">' . $class . '</dt>' . '<dd class="field-entry">' . $content . '</dd>';`

**Comment by eddiekonczal** [comment]
Adding side effect:

Problem:  If render classes have been set for the custom field options, the class name will be shown instead of applied to the custom field.

**Comment by eddiekonczal** [comment]
Below is one way to make the code accessible.  There is probably a better way to do this - if the `<dt>` and `<dd>` elements could be shown on the same line with a colon separating them,

1. Insert at line 64 of `components/com_fields/layouts/fields/render.php`:  

  	`$showLabel = $field->params->get('showlabel');`
	`$label = JText::_($field->label);` 
  	`$value = $field->value;`

2.    (Optional) Suppress hidden labels:

Add new lines 75 - 80:

  	// If label should be hidden, suppress it
  	if ($showLabel == 0)   {$label = '';}

3. Modify `$output` statement (formerly line 72, now line 81):

	`$output[] = '<dt class="field-label ' . $class . '">' . $label . '</dt>' . '<dd class="field-value ' . $class . '">' . $value . '</dd>';
}`

**Comment by brianteeman** [comment]
Sorry this slipped my attention. I will take a look hopefully tomorrow

**Comment by brianteeman** [comment]
Sorry this cannot be fixed at a core level in Joomla 3.9 without significant backwards breaking changes.

I have created an issue for Joomla 4 and will be working over the next week to resolve this

**Comment by brianteeman** [comment]
See 27567<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26849">issues.joomla.org/tracker/joomla-cms/26849</a>.</sub>
