### ISSUE TITLE
[4.0] com_banners

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#26843]
Why do we create an alias for a banner?

- I can't see anywhere that it is used
- It is not unique (unlike in other components)

**Comment by Quy** [comment]
I don't see it being used either. 
Alias is required to be unique in Banners too.

**Comment by Quy** [comment]
See PR #27095<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26843">issues.joomla.org/tracker/joomla-cms/26843</a>.</sub>
