### ISSUE TITLE
[4.0] I lost some access in admin once upgraded

### ISSUE THREAD

**Issue by neoacevedo** [joomla/joomla-cms#26856]
Once upgraded from alpha 10 to 11, I lost the upper right links:

![Screenshot_20191029_123716](https://user-images.githubusercontent.com/438372/67793608-257cc000-fa49-11e9-90f1-dcdf4410ce47.png)

In addition, clicking in System:
![Screenshot_20191029_123758](https://user-images.githubusercontent.com/438372/67793713-5ceb6c80-fa49-11e9-89d1-d602642b6719.png)
I get an "empty" content, where before I had the extension manager module and other similar modules.

**Comment by alikon** [comment]
the upgrade from  an alpha version to alpha version is not supported currently
