### ISSUE TITLE
After update, template links are changed on rendered joomla page

### ISSUE THREAD

**Issue by WhiteKarma** [joomla/joomla-cms#26869]
Hello all,

To integrate an existing joomla website with another platform ( sub site B ) _running on the same server_ ( on localhost, on port XX ( different port than the one used by joomla website ) ) served by kestrel webserver on UBUNTU server 16.04, we are using an empty template that echoes the HTML markup of the other application ( sub site B ). The content is obtained with curl, after authentication on sub site B, on the same server via **https://localhost:XX/.**

The template has a library that handles the authentication on the sub site B and via an iframe within a joomla article associated with that template, allows the interaction and integration with sub site B.

After authenticating on the joomla website, if i point the browser to the template directly, the CSS and JS and IMG links are respected ( basically they keep the address base prefix **https://localhost:XX/** ) and thus the content renders fine.

After an update the links of the template embedded on the joomla page, instead of pointing to ( **https://localhost:XX/** ( the correct address of sub site B ) they are now pointing to **/localhost/** as if they were part of the same website ) and therefore, the content is not rendered correctly because of 404 errors of the browser not finding none of the incorrectly referenced resources of sub site B, present on a different port.

After authentication, the browser pointing directly to the empty template still renders nicely... It only breaks the links when the resulting HTML coming from sub site B is integrated on the final joomla page of the existing joomla website.

All used to work well until very recently, can you advise how to correct the situation according to the best practices?

Thank you very much in advance!!!

**Comment by Quy** [comment]
Please post support questions to the [Joomla Forum](https://forum.joomla.org/). If a bug if found, please open an issue here. Thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26869">issues.joomla.org/tracker/joomla-cms/26869</a>.</sub>

**Comment by WhiteKarma** [comment]
Thank you @Quy,

I did both, ( link for joomla forum here: https://forum.joomla.org/viewtopic.php?f=713&t=975409&p=3584719#p3584719 ). The integration was fine since 2016. Is it possible that there was a change on how iframe or template links references are simplified on recent versions?

Thank you very much for your project and for your valuable help.
