### ISSUE TITLE
version 4 beta 1 >   Menu Item Type : no banner

### ISSUE THREAD

**Issue by no-matter-0** [joomla/joomla-cms#26874]
admin panel : impossible to add a menu item type = banner 
not listed

thanks

**Comment by no-matter-0** [comment]
com_banners is listed in #__menu<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26874">issues.joomla.org/tracker/joomla-cms/26874</a>.</sub>

**Comment by SharkyKZ** [comment]
Are you asking about menu items for frontend (site) menu? Or administrator menu?

**Comment by no-matter-0** [comment]
for frontend menu , but I just noticed that it didn't exist in J3 too

you can close the topic

sorry<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26874">issues.joomla.org/tracker/joomla-cms/26874</a>.</sub>

**Comment by SharkyKZ** [comment]
Use Banners module to display banners in frontend.

**Comment by SharkyKZ** [comment]
Closed as expected behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26874">issues.joomla.org/tracker/joomla-cms/26874</a>.</sub>
