### ISSUE TITLE
[4.0] Error when adding a new menuEntry of type "create Article" and choose Category

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#26878]
### Steps to reproduce the issue
Add a new MenuItem of type "create article".
In options - choose "default category" and then try to select a category. 

### Expected result
A Modal with categories

### Actual result
Error: unknown column s.state in field list.

![screen shot 2019-10-31 at 21 40 12](https://issues.joomla.org/uploads/1/8ee35cf5de70c686b5ef70cd1f2c51e0.jpg)

### Additional comments
In general it is easy to find such issues, but here I cannot find any occurence of s.state in the models. 
Could be a n effect of predefined queries?

**Comment by SharkyKZ** [comment]
I can't replicate the issue. Please post the entire call stack.

**Comment by chmst** [comment]
Sorry of inconvenience. Can you close this? It is solved with new database
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26878">issues.joomla.org/tracker/joomla-cms/26878</a>.</sub>
