### ISSUE TITLE
[4.0] Pagination links and method not SEO friendly?

### ISSUE THREAD

**Issue by Giuse69** [joomla/joomla-cms#26881]
### Steps to reproduce the issue
In Joomla 3 pagination links are handled on the server as explicit separate URLs in the form `<URL>?start=X`.
In Joomla 4 with Cassiopeia template, pagination is done via javascript on the browser
`onclick="document.adminForm.limitstart.value=X; Joomla.submitform();return false;">`
so navigating to page 2, 3, ... **keeps the same page URL**

### Expected result
Crawlers expect to find different content to different URLs.

### Actual result
Completely different contents are associated to same URL.
Isn't that super confusing for crawlers/SEO?

### System information (as much as possible)
Joomla 4 beta 12

**Comment by Giuse69** [comment]
Hi, I see no comment so far: I think this SEO aspect for the upcoming native template is important, isn't it? Pagination should produce _different_ URLs for the different pages, am I wrong?
thanks for your attention
cheers

**Comment by brianteeman** [comment]
I can confirm this is a bug

**Comment by rajkumaar23** [comment]
> Hi, I see no comment so far: I think this SEO aspect for the upcoming native template is important, isn't it? Pagination should produce _different_ URLs for the different pages, am I wrong?
> thanks for your attention
> cheers
Hi @Giuse69  , I'm all new to Joomla. Could you please let me know what I can do to fix this issue ?

**Comment by Quy** [comment]
Please test PR #27489
