### ISSUE TITLE
[4.0] - white screen of death

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#26884]
### Steps to reproduce the issue
Go to Content->Articles
then click on User Menu on the upper right corner 
select Accesibility settings or Edit Account
you are redirected to the Users: Edit Profile
then simply hit the close  button

### Actual result
white screen of death
![Screenshot from 2019-11-01 10-49-51](https://user-images.githubusercontent.com/181681/68016696-623cf700-fc95-11e9-861f-3fd3e73910fe.png)

**Comment by infograf768** [comment]
Can't reproduce here

**Comment by alikon** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/181681/68018217-e8a70800-fc98-11e9-9929-75966797e998.gif)

**Comment by brianteeman** [comment]
Pretty sure there is/was an issue about this already

**Comment by C-Lodder** [comment]
Can't reproduce either

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/26776.

**Comment by brianteeman** [comment]
Thanks @SharkyKZ I new I had seen it somewhere ;)

**Comment by alikon** [comment]
thanks #26776 solve it
