### ISSUE TITLE
[4.0] Cassiopeia -  "fluid" option not displaying correctly

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#26887]
### Steps to reproduce the issue
In back-end Template Styles - Advanced, set layout to "fluid".

### Actual result
Front-end modules take full width of the allowed space.
See picture:
![screen shot 2019-11-01 at 12 30 59](https://issues.joomla.org/uploads/1/5aeb6bc1220d30cf2c9d517c0abe7a33.png)

I guess there is a mix-up in the grid/flex rules.

For example, in index.php, if I remove class "grid-child" from "sidebar-right", it goes to right as expected (not well correctly though).

`<?php if ($this->countModules('sidebar-right')) : ?>
	<div class="grid-child container-sidebar-right">
		<jdoc:include type="modules" name="sidebar-right" style="default" />
	</div>
	<?php endif; ?>`

**Comment by micker** [comment]
i see same error +1

**Comment by ghazal** [comment]
An error is that both sidebar-right and sidebar-left are outside the scope of a flex container while rules of a flex container are applied. These tags are within the scope of the grid body container though.


![screen shot 2019-11-09 at 10 49 21](https://issues.joomla.org/uploads/1/f29b0a611a31e92451ec85ee84a9cdc2.png)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26887">issues.joomla.org/tracker/joomla-cms/26887</a>.</sub>

**Comment by ciar4n** [comment]
PR.. https://github.com/joomla/joomla-cms/pull/27301

**Comment by alikon** [comment]
closed as we have a pr #27301 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26887">issues.joomla.org/tracker/joomla-cms/26887</a>.</sub>
