### ISSUE TITLE
[4.0] UI is not looking good when click on smart search.

### ISSUE THREAD

**Issue by SharayuYadav** [joomla/joomla-cms#26894]
### Steps to reproduce the issue
Go to components->smart search
![screen shot 2019-11-02 at 06 03 04](https://issues.joomla.org/uploads/1/d2442a12a0235058d7d075a1ce63f80e.png)

### Expected result
Position of search filters along with search text box has been moved to the left

### Actual result
Search text box and search filters should be aligned properly.

### System information (as much as possible)
Screen resolution: 1366 * 768 (16:9)

**Comment by brianteeman** [comment]
resolved by #26137
