### ISSUE TITLE
[4.0] Private Message: Notification absent for new private message  #pbf19 #bug

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#26895]
### Steps to reproduce the issue
1. Login to Joomla admin with one user
2. Go to the private message section.
3. Add another user Id in recipients
4. Add some context and send the message.
5. Now login with another user.
6. See the admin panel

### Expected result
User should be notified if new message comes

### Actual result
There are no any notification for new private message

![screen shot 2019-11-02 at 06 11 58](https://issues.joomla.org/uploads/1/641470200dec0c3274bc21e821732de0.png)

**Comment by infograf768** [comment]
Confirmed.
`<?php $countUnread = $app->getSession()->get('messages.unread'); ?>` is always NULL.

**Comment by alikon** [comment]
pleaset test #26912<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26895">issues.joomla.org/tracker/joomla-cms/26895</a>.</sub>
