### ISSUE TITLE
Unable to Enter in search box - Patch tester

### ISSUE THREAD

**Issue by priyankaSahutekdi** [joomla/joomla-cms#26898]
### Steps to reproduce the issue
- Click at Joomla patch tester from the toggle menu 
- mouseover to the search box, it will display a placeholder and not allow to enter anything in the search box  

### Expected result
The system should display placeholder on hover and should allow entering data 

### Actual result
Displaying placeholder and not allowing to enter data 

### Additional comments
![screen shot 2019-11-02 at 06 39 16](https://issues.joomla.org/uploads/1/a4819ac05d319b9e2e94f51d1e527178.png)

**Comment by alikon** [comment]
please report on the patchtester repository https://github.com/joomla-extensions/patchtester

**Comment by alikon** [comment]
please test https://github.com/joomla-extensions/patchtester/pull/246<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26898">issues.joomla.org/tracker/joomla-cms/26898</a>.</sub>
