### ISSUE TITLE
[4.0] Private message: Tooltip is missing for search filter #pbf19 #bug

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#26897]
### Steps to reproduce the issue
1. Login to Joomla admin with one user
2. Go to the private message section.
3. Click on filter option
4. See the new blank filter

### Expected result
Filter should show the tooltip or placeholder

### Actual result
Blank filter get displayed

![screen shot 2019-11-02 at 06 28 54](https://issues.joomla.org/uploads/1/af2f13df492e884bfe01a1bdb9e7c454.png)

### System information

![System Information - - Administration](https://user-images.githubusercontent.com/10463754/68068763-b1128b80-fd7e-11e9-9cdd-6806ea7dc1d5.png)

**Comment by alikon** [comment]
please test #26902<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26897">issues.joomla.org/tracker/joomla-cms/26897</a>.</sub>
