### ISSUE TITLE
While edit account getting error message

### ISSUE THREAD

**Issue by priyankaSahutekdi** [joomla/joomla-cms#26896]
### Steps to reproduce the issue
- Login to the site 
- Click at User menu at the top right corner 
- Don't change anything and click at close button 
- It will redirect to some random page and displaying "0 An error has occurred"   
- Once click at "return to dashboard" button, not displaying the error msg again![screen shot 2019-11-02 at 06 23 29](https://issues.joomla.org/uploads/1/397c1f82adb76b7c275edec33675fb4c.png) 
### Expected result
Should display a proper message 

### Actual result
Displaying "0 An error has occurred"

**Comment by alikon** [comment]
this has been fixed by #26776

**Comment by alikon** [comment]
fixed by #26776<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26896">issues.joomla.org/tracker/joomla-cms/26896</a>.</sub>
