### ISSUE TITLE
'Export' click is not working in com_banners

### ISSUE THREAD

**Issue by SharayuYadav** [joomla/joomla-cms#26899]
### Steps to reproduce the issue
Go to components->baneers->tracks
Click on the 'Export' button, a modal opens.
No functionality is provided to close/cancel the modal.
The escape button is also not working.
Redirection to the previous page is not available.

### Expected result
If nothing is present to export then there should be functionality to close the modal.

### Actual result
Onclick of export the screen becomes grey out.

![screen shot 2019-11-02 at 06 37 55](https://issues.joomla.org/uploads/1/987e94a8806f0f19a7e0061e5cb687c4.png)

**Comment by alikon** [comment]
please test #26848 and/or  #26868  same issues like #26818

**Comment by alikon** [comment]
we have pr's<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26899">issues.joomla.org/tracker/joomla-cms/26899</a>.</sub>
