### ISSUE TITLE
[4.0]User Note -> Select Category - Tooltip goes out of frame for Search field.

### ISSUE THREAD

**Issue by AdityaTaware** [joomla/joomla-cms#26900]
### Steps to reproduce the issue
1. Go to the user notes page.
2. Click on New
3. Click on the Select Category option.
4. Move the cursor in Search text field.

### Expected result
The tooltip should clearly visible

### Actual result
Getting hide

### System information (as much as possible)
Win 10.

**Comment by alikon** [comment]
confirmed

**Comment by Quy** [comment]
Please test PR #27035<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26900">issues.joomla.org/tracker/joomla-cms/26900</a>.</sub>
