### ISSUE TITLE
[4.0]: Multilingual Associations :Association > Hide Reference and Select Target buttons placement and font is not correct

### ISSUE THREAD

**Issue by ttplpoojak** [joomla/joomla-cms#26905]
![screen shot 2019-11-02 at 07 12 10](https://issues.joomla.org/uploads/1/1d2d23d705d63d249d3d83d95aef1f5b.png)### Steps to reproduce the issue
Assuming multi-language is setup 
1. Create new article > Association
2. Check Hide Reference and Select Target placement and font 

### Expected result
Buttons should be aligned and have the same font.

**Comment by Quy** [comment]
Please test Pr #26945<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26905">issues.joomla.org/tracker/joomla-cms/26905</a>.</sub>
