### ISSUE TITLE
User Notes - Tooltip goes out of frame on select Category view #pbf19 #bug

### ISSUE THREAD

**Issue by AdityaTaware** [joomla/joomla-cms#26906]
### Steps to reproduce the issue
1. Go to User Notes section.
2. Click on New option.
3. Click on Select Category option.
4. Move cursor in Search box.![screen shot 2019-11-02 at 07 11 29](https://issues.joomla.org/uploads/1/7c267940044bea547c6865a51eed854e.png)

**Comment by astridx** [comment]
I can confirm this on the current4.0-dev Branch on unbuntu with Firefox.
![User Notes  New Edit   test   Administration](https://user-images.githubusercontent.com/9974686/68075211-21340800-fda5-11e9-8a5f-d5ce1a89636c.png)

**Comment by Quy** [comment]
Please test PR #27035<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26906">issues.joomla.org/tracker/joomla-cms/26906</a>.</sub>
