### ISSUE TITLE
Language constant missing in Permissions for users list#pbf19 #bug

### ISSUE THREAD

**Issue by AdityaTaware** [joomla/joomla-cms#26903]
### Steps to reproduce the issue
1. Go to Manage users page.
2. Click on the Permissions option.
3. Search with language constant COM_WORKFLOW_DEFAULT_WORKFLOW![screen shot 2019-11-02 at 07 03 23](https://issues.joomla.org/uploads/1/28dfcd65c66882918a53a4416ff32757.png)

**Comment by pravinTek** [comment]
Hi,
this is duplicate issue...Please test #23992
