### ISSUE TITLE
[4.0]Private message: Help button is not aligned correctly #pbf19 #bug

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#26904]
### Steps to reproduce the issue
1. Login to Joomla admin with one user
2. Go to the private message section.
3. Click on toggle toolbar

### Expected result
Spacing & alignement should be corrected

### Actual result
Help button is not aligned correctly

### System information (as much as possible)
Screen resolution: 
![screen shot 2019-11-02 at 07 08 14](https://issues.joomla.org/uploads/1/b8555028362f579eb57298595e6a3ec8.png)

**Comment by brianteeman** [comment]
same issue as #26331
