### ISSUE TITLE
Add user note - Validation missing for User field #pbf19 #bug

### ISSUE THREAD

**Issue by AdityaTaware** [joomla/joomla-cms#26907]
### Steps to reproduce the issue
1. Go to User Notes page.
2. Click on New button.
3. Select Category.
4. Do not select a user name and save.

### Expected result
The error message should appear for the User field and unable to save with blank.

### Actual result
Record able to create with a ![screen shot 2019-11-02 at 07 20 37](https://issues.joomla.org/uploads/1/4f42d0a4b63364a256248c454d52bddc.png)blank user field.

### Additional comments
This happens only for the Uncategorised option. Select that option and check.

**Comment by brianteeman** [comment]
I could not replicate this

![image](https://user-images.githubusercontent.com/1296369/68148221-6d14b780-ff33-11e9-9672-191069a31c3b.png)

**Comment by Quy** [comment]
To reproduce, click `Save` and not `Save & Close`.

**Comment by Quy** [comment]
Please test PR #27463
