### ISSUE TITLE
while creating new joomla article jtoolbar_association language constant missing

### ISSUE THREAD

**Issue by ttplpoojak** [joomla/joomla-cms#26901]
### Steps to reproduce the issue
Go to 
administrator/index.php?option=com_content&view=article&layout=edit&id=0
JTOOLBAR_ASSOCIATIONS language constant missing.
also JGLOBAL_ASSOCIATIONS_NEW_ITEM_WARNING language constant missing.

**Comment by rajnish-dargan** [comment]
Can you explain in detail?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26901">issues.joomla.org/tracker/joomla-cms/26901</a>.</sub>

**Comment by Quy** [comment]
Unable to reproduce.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26901">issues.joomla.org/tracker/joomla-cms/26901</a>.</sub>
