### ISSUE TITLE
[4.0]Private message: Search filter tooltip is not displayed clearly in select recipient popup #pbf19 #bug

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#26909]
### Steps to reproduce the issue
1. Login to Joomla admin with one user
2. Go to the private message section.
3. Click on New 
4. Hover on search filter

### Expected result
Tooltip should be clearly displayed

### Actual result
Tooltip get half-broken![screen shot 2019-11-02 at 07 20 29](https://issues.joomla.org/uploads/1/ce6768514002bdb7259224eb79b9cdb4.png)

**Comment by Quy** [comment]
Please test PR #27035<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26909">issues.joomla.org/tracker/joomla-cms/26909</a>.</sub>
