### ISSUE TITLE
[4.0] search text label is cut down while selecting target

### ISSUE THREAD

**Issue by SharayuYadav** [joomla/joomla-cms#26916]
### Steps to reproduce the issue
Go to content->articles
Edit an already created article.
Click on 'Associations'.
Click on 'Select Target'.
Modal opens. Go to search text, its label is shown half.

### Expected result
The label should be shown below. If it is shown upwards then it should be visible properly

### Actual result

![screen shot 2019-11-02 at 08 57 59](https://issues.joomla.org/uploads/1/a15067ee1e0873521b50de27b5342ecd.png)

**Comment by infograf768** [comment]
Confirmed. Same for Category and certainly others.

**Comment by infograf768** [comment]
The issue is with the css
It should be
```
[id="filter[search]-desc"] {
  top: 100%;
  font-size: 0.875rem; }
```
instead of
```
[id="filter[search]-desc"] {
  bottom: 100%; }
```

when the search button is in a modal view.
Trying to find a way to solve this.

**Comment by Quy** [comment]
![26916](https://user-images.githubusercontent.com/368084/68420180-a4ac7b00-0150-11ea-9e94-21296b8df496.jpg)
Some of the modals area wrapped in `<div class="container-popup"></div>`. Associations is not. 
Try the following, but have to figure out how to display it correctly.

```
.container-popup [id="filter[search]-desc"] {
  top: 100%;
}
```

**Comment by Quy** [comment]
Please test PR #27035<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26916">issues.joomla.org/tracker/joomla-cms/26916</a>.</sub>
