### ISSUE TITLE
User Notes - Can able to save note without selecting category on edit flow#pbf19 #bug

### ISSUE THREAD

**Issue by AdityaTaware** [joomla/joomla-cms#26917]
### Steps to reproduce the issue
1. Create a user notes category and create a note using same category.
2. Now delete this category permanently.
3. Now ope the note for edit and click on save option. 

### Expected result
The system should raise error message for category.

### Actual result
The system saves a record and no any error message appear.

**Comment by brianteeman** [comment]
The problem here is that you should not be able to delete a category that has items

**Comment by alikon** [comment]
please test #26989<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26917">issues.joomla.org/tracker/joomla-cms/26917</a>.</sub>
