### ISSUE TITLE
[4.0]:[com_content]: Article filter option fonts are different

### ISSUE THREAD

**Issue by ttplpoojak** [joomla/joomla-cms#26918]
### Steps to reproduce the issue
1.Content > articles > Filter option
-- Compare Select Featured filter options font and Select Category filter font

### Expected result
Font of the filter option should be the same.
![screen shot 2019-11-02 at 09 14 07](https://issues.joomla.org/uploads/1/ef3471fd3642ae85beb12e90a362b8bd.png)
![screen shot 2019-11-02 at 09 14 06](https://issues.joomla.org/uploads/1/cc8b3ec8a81951a87fc72c30731cee45.png)

**Comment by Quy** [comment]
Please test PR #26983<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26918">issues.joomla.org/tracker/joomla-cms/26918</a>.</sub>
