### ISSUE TITLE
[4.0] View Private message: Add separator colon : while previewing the message #pbf19 #bug

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#26915]
### Steps to reproduce the issue
1. Login to Joomla admin with one user
2. Go to the private message section.
3. Open the message for reading

### Expected result
There should be colon: in the view so that the user can get a better view

### Actual result
There are no any separators.

![screen shot 2019-11-02 at 08 56 14](https://issues.joomla.org/uploads/1/774a56c8e905d5544f3275cbe17ad4c4.png)

**Comment by Quy** [comment]
See PR #26919<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26915">issues.joomla.org/tracker/joomla-cms/26915</a>.</sub>

**Comment by SharkyKZ** [comment]
Closing as fixed in code base with #28646.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26915">issues.joomla.org/tracker/joomla-cms/26915</a>.</sub>
