### ISSUE TITLE
For multilingual site setup - Enable multilingual plugin should open in another tab.

### ISSUE THREAD

**Issue by shinderohanoffical** [joomla/joomla-cms#26911]
### Steps to reproduce the issue
1: Login to Joomla admin with one user
2: Go to the components >> multilingual Associations.
3: Click on 'Language Filter plugin'

### Expected result
1: It should in a new tab.

**Comment by richard67** [comment]
You mean a new browser tab? That would not be good UX and not be consistent with the rest of the backend. New tabs should only be used with external links.
@brianteeman Please correct me if I’m wrong because I am not expert in this.

**Comment by Quy** [comment]
See PR #26920<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26911">issues.joomla.org/tracker/joomla-cms/26911</a>.</sub>
