### ISSUE TITLE
[4.0]com_content: Search filter tooltip is not displayed clearly in select user popup #pbf19 #bug

### ISSUE THREAD

**Issue by Mayaank12** [joomla/joomla-cms#26914]
### Steps to reproduce the issue
1. Login to Joomla admin with one user
2. Go to the com_content component.
3. Create a new article
4. Go to publishing tab and and select created by
5. Hover on the search filter in the popup

### Expected result
Tooltip should be clearly displayed

### Actual result
Tooltip get half-broken
![screen shot 2019-11-02 at 08 56 32](https://issues.joomla.org/uploads/1/0a94584ec9194bc43baadc0bfe840073.png)

**Comment by Quy** [comment]
Please test PR #27035<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26914">issues.joomla.org/tracker/joomla-cms/26914</a>.</sub>
