### ISSUE TITLE
Articles have extra space in select stage drop-down [4.0]

### ISSUE THREAD

**Issue by priyankaSahutekdi** [joomla/joomla-cms#26928]
### Steps to reproduce the issue
- Login to the backend 
- Go to Content > Articles > click at Filter options > 
- Click at Select stage![screen shot 2019-11-02 at 10 06 47](https://issues.joomla.org/uploads/1/fa70e50ad7d9ab2bf88a141ecd9a25bc.png) 
- There is a space before published opinion 

### Expected result
Space should be same everywhere  

### Actual result
Have an extra space in Slecte stag dropdown

**Comment by priyankaSahutekdi** [comment]
![screen shot 2019-11-02 at 10 37 28](https://issues.joomla.org/uploads/1/c7110c22e1909de68d2f8f55157523e9.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26928">issues.joomla.org/tracker/joomla-cms/26928</a>.</sub>

**Comment by Quy** [comment]
Please test PR #26987<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26928">issues.joomla.org/tracker/joomla-cms/26928</a>.</sub>
