### ISSUE TITLE
[4.0] Private message: When user selects the already read message then Mark as read option is getting enable #pbf19 #bug

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#26921]
### Steps to reproduce the issue
1. Login to Joomla admin with one user
2. Go to the private message section.
3. Select the already read message

### Expected result
Mark as read option should not get enable 

### Actual result
Mark as read option get enable. Same for unread as well, if user selects the unread messages respected option get enable

![screen shot 2019-11-02 at 09 25 32](https://issues.joomla.org/uploads/1/6e337a3dea9bdea7eeda69d18016a3e5.png)

**Comment by brianteeman** [comment]
Was this not resolved by #26912 ?

**Comment by Quy** [comment]
It is a separate issue. See https://github.com/joomla/joomla-cms/pull/26912#issuecomment-549028926

**Comment by brianteeman** [comment]
This is true everywhere. For example if a category is published then the action button still allows the action published

**Comment by chmst** [comment]
I don't see this as anissue. If the list would contain more items, the publish button could be applied on other or all items in the list as everywhere.

**Comment by Quy** [comment]
Closing for stated reasons.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26921">issues.joomla.org/tracker/joomla-cms/26921</a>.</sub>
