### ISSUE TITLE
[4.0]User field -> Publishing tab - The No User option is not working in select user popup.#pbf19 #bug

### ISSUE THREAD

**Issue by AdityaTaware** [joomla/joomla-cms#26929]
### Steps to reproduce the issue
1. Go to Users-> Fields.
2. Click on New button.
3. Go to the Publishing section.
4. Select the user for created by field.
5. Now again go for user selection popup and click on No User option.

### Expected result
The selected should get deselect.

### Actual result
the ![screen shot 2019-11-02 at 10 28 40](https://issues.joomla.org/uploads/1/1d16093cc02934dd40e6459126c2e577.png)button is not clickable.

**Comment by Quy** [comment]
Please test PR #26960<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26929">issues.joomla.org/tracker/joomla-cms/26929</a>.</sub>
