### ISSUE TITLE
Repeatable-table field - UX issue

### ISSUE THREAD

**Issue by snehal0904** [joomla/joomla-cms#26922]
### Steps to reproduce the issue
- Go to Plugins: Fields - Radio
- Create a radio type field
- Remove field option is not visible
### Expected result
- Add remove button should display on any device

**Comment by snehal0904** [comment]
![screen shot 2019-11-02 at 09 40 27](https://issues.joomla.org/uploads/1/a6839a03051d4590e9a515e25efa395f.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26922">issues.joomla.org/tracker/joomla-cms/26922</a>.</sub>

**Comment by Quy** [comment]
See PR#26923<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26922">issues.joomla.org/tracker/joomla-cms/26922</a>.</sub>
