### ISSUE TITLE
[4.0] Update checks - Text is getting touch to box border line #pbf19 #bug

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#26937]
### Steps to reproduce the issue
1. Login to joomla backend
2. Go to control panel
3. See the update checks

### Expected result
Text should be displayed between the box

### Actual result
Text is getting a touch to box borderline

![screen shot 2019-11-02 at 11 22 54](https://issues.joomla.org/uploads/1/5ebc20e7a4036ffed24f3acd0b91ca40.png)

**Comment by infograf768** [comment]
All depends on the window precise size. Toggling the menus solves almost all instances of this issue.

**Comment by brianteeman** [comment]
Unable to replicate this - even at the exact resolution in the report.

I would recommend that this is closed at this time. Maybe one of the gazillion changes since the report fixed it. It can always be reopened.
