### ISSUE TITLE
Usergroup field plugin - Plugin option 'Multiple'  - Description of the field is missing

### ISSUE THREAD

**Issue by snehal0904** [joomla/joomla-cms#26930]
### Steps to reproduce the issue
- Go to usergroup field plugin
- Check plugin option multiple, what is the field for is missing.

### Expected result
- Add a description for the multiple plugin option

**Comment by SharkyKZ** [comment]
This was removed intentionally. In 4.0 we're trying to avoid useless descriptions.

**Comment by Quy** [comment]
See PR #26931<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26930">issues.joomla.org/tracker/joomla-cms/26930</a>.</sub>
