### ISSUE TITLE
[4.0]Create User Group - Group parent dropdown gets blank.#pbf19 #bug

### ISSUE THREAD

**Issue by AdityaTaware** [joomla/joomla-cms#26933]
### Steps to reproduce the issue
1. Open new create a user group form.
2. Leave the required field blank and click on the save button.
3. Check parent group dropdown.

### Expected result
The options should display in a dropdown

### Actual result
The dropdown gets blank

### Additional comments
Basic use case![screen shot 2019-11-02 at 11 01 14](https://issues.joomla.org/uploads/1/bcdfcc1cc7f80f6a5ac0c81cb6cacd93.png) missing

**Comment by Quy** [comment]
See PR #26939<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26933">issues.joomla.org/tracker/joomla-cms/26933</a>.</sub>
