### ISSUE TITLE
[4.0] Admin dashboard -> Count keeps showing on post installation message #pbf19 #bug

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#26938]
### Steps to reproduce the issue
1. Login to joomla backend
2. Go to control panel
3. See the post-installation message

### Expected result
After visiting the post-installation link count should get removed

### Actual result
Post visiting the link count doesn't get removed
![screen shot 2019-11-02 at 11 31 25](https://issues.joomla.org/uploads/1/b377468a03481a05bd724f86e8f142b3.png)

**Comment by SharkyKZ** [comment]
You have to hide the messages for count to decrease.

**Comment by Quy** [comment]
Duplicate #26646<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26938">issues.joomla.org/tracker/joomla-cms/26938</a>.</sub>
