### ISSUE TITLE
[4.0][com_categories]: Articles: New Category - Tags saved only when used enter key and not when typed and clicked Save #26902

### ISSUE THREAD

**Issue by flavia-b** [joomla/joomla-cms#26934]
### Steps to reproduce the issue
Login to Joomla admin with one user
Go to the Content >> Articles: Categories section
Click on New - Articles: New Category
Try filling in the tag section on the right sidebar

### Expected result
The tag should be saved even if the enter-key isn't pressed.

### Actual result
When a tag is typed and you press enter-key try saving the article, it gets saved with the new tag.
But when you type a tag and you click outside the tag input box and then try saving the article, the new tag isn't saved.

![screen shot 2019-11-02 at 11 12 06](https://issues.joomla.org/uploads/1/a2e3f8b3c74b29d4db3afab4b3736547.png)

**Comment by SharkyKZ** [comment]
I think this is expected behavior.
