### ISSUE TITLE
[4.0]User group - System raise confirmation popup 'Are you sure you wish to delete groups that have users?' when deleting group which don't have users.#pbf19 #bug

### ISSUE THREAD

**Issue by AdityaTaware** [joomla/joomla-cms#26935]
### Steps to reproduce the issue
1. Create a new user group.
2. Select that group and click on the delete button.
3. Observe confirmation popups.

### Expected result
The second confirmation popup should not appear if there is no any user in that group.

### Actual result
![screen shot 2019-11-02 at 11 17 27](https://issues.joomla.org/uploads/1/21a3a295fa01d0c925a179427d870496.png)

**Comment by SharkyKZ** [comment]
Test PR https://github.com/joomla/joomla-cms/pull/26967 please.
