### ISSUE TITLE
Unable to login to administrator side

### ISSUE THREAD

**Issue by jaisheela** [joomla/joomla-cms#26936]
### Steps to reproduce the issue
Enter the url 
Enter the correct username 
Enter the correct password
Click on Log in button : Nothing happens/ does not login (nothing in console)
Click on Log in button Again

Shows error in console:
index.php:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at onSuccess (admin-login.min.js?b65d31df5863825298b9f8dbb4cc7745:1)
    at XMLHttpRequest.c.onreadystatechange (core.min.js?b65d31df5863825298b9f8dbb4cc7745:1)

### Expected result

Should log in successfully

### Actual result

Shows error
index.php:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at onSuccess (admin-login.min.js?b65d31df5863825298b9f8dbb4cc7745:1)
    at XMLHttpRequest.c.onreadystatechange (core.min.js?b65d31df5863825298b9f8dbb4cc7745:1)

### System information (as much as possible)

joomla4
php73![screen shot 2019-11-02 at 11 07 57](https://issues.joomla.org/uploads/1/59d31a36736940a76d92e411171820f0.png)

**Comment by Quy** [comment]
You are using an older alpha. Please use the latest nightly build and report if it is still an issue. https://developer.joomla.org/nightly-builds.html<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26936">issues.joomla.org/tracker/joomla-cms/26936</a>.</sub>
