### ISSUE TITLE
[4.0] Global Configuration: Mail Settings error message #pbf19 #bug

### ISSUE THREAD

**Issue by atpatil11** [joomla/joomla-cms#26932]
### Steps to reproduce the issue
Go to Global Configuration
Go to Server Tab -> Mail Settings section
Set some incorrect configuration (so that email doesn't work)
Click on the ![screen shot 2019-11-02 at 10 52 53](https://issues.joomla.org/uploads/1/05644d1b3111bfe9eed4127a5824024f.png)'Send Test Mail' button

### Expected result
It should show an error message that test mail could not be sent. 

It actually shows 'Could not start mail function' error in the response (Network tab)

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/27766.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26932">issues.joomla.org/tracker/joomla-cms/26932</a>.</sub>
