### ISSUE TITLE
[4.0]Menu - Wrong field name in error message.#pbf19 #bug

### ISSUE THREAD

**Issue by AdityaTaware** [joomla/joomla-cms#26948]
### Steps to reproduce the issue
1. Go to Menu -> Create menu.
2. Add Title.
3. Add blank space in the Unique Name field.
4. Click on the Save button.

### Expected result
The error message should show the correct field name.

### Actual result
Wrong field name show in![screen shot 2019-11-02 at 12 32 41](https://issues.joomla.org/uploads/1/8cea4670cee65531a5ec2e3f7ff4dcb0.png) error message.

**Comment by infograf768** [comment]
I guess we have to trim `$data['menutype'])` to make sure it never tries to save the field with a blank space. 
If trimmed, the error will be `Field required: Unique Name`

**Comment by astridx** [comment]
~~I just tried this (after `git pull origin 4.0-dev` on Ubuntu with Firefox) and I get the error `Field required: Unique Name`~~
![Menus  Add   test   Administration](https://user-images.githubusercontent.com/9974686/68075285-e67e9f80-fda5-11e9-8175-a28ed2f65472.png)

**Comment by infograf768** [comment]
@astridx 
Have you entered a blank space in the field before saving? If you do, then you will get the error `Menu type empty.`

To avoid this scenario, we can use this patch to get the `Field required: Unique Name` as anyway it is not a good idea to have some spaces around the Unique name.
```
diff --git a/administrator/components/com_menus/Controller/MenuController.php b/administrator/components/com_menus/Controller/MenuController.php
index 984bcc1..b3736c0 100644
--- a/administrator/components/com_menus/Controller/MenuController.php
+++ b/administrator/components/com_menus/Controller/MenuController.php
@@ -13,4 +13,5 @@
 
 use Joomla\CMS\Language\Text;
+use Joomla\CMS\Filter\InputFilter;
 use Joomla\CMS\MVC\Controller\FormController;
 use Joomla\CMS\Router\Route;
@@ -71,4 +72,6 @@
 		}
 
+		$data['menutype'] = InputFilter::getInstance()->clean($data['menutype'], 'TRIM');
+
 		// Populate the row id from the session.
 		$data['id'] = $recordId;
```

**Comment by astridx** [comment]
@infograf768 I was sure that I entered a space - but I probably do not have this. I just tested it again and now I can confirm the issue.

**Comment by infograf768** [comment]
will make PR later.

**Comment by brianteeman** [comment]
@infograf768 did you forget or was there a difficulty

**Comment by alikon** [comment]
please test #27206<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26948">issues.joomla.org/tracker/joomla-cms/26948</a>.</sub>

**Comment by infograf768** [comment]
> @infograf768 did you forget or was there a difficulty

I just forgot... Thanks @alikon
