### ISSUE TITLE
[4.0]Menus -> Edit menu - Getting error message for 'Menu type exists'.#pbf19 #bug

### ISSUE THREAD

**Issue by AdityaTaware** [joomla/joomla-cms#26947]
### Steps to reproduce the issue
1. Edit any menu.
2. Remove Unique Name and click save.
3. Now add the existing name again and click on the Save button.
4. Observe the error message.

### Expected result
The system should not raise error message if user adding an existing names for the ![screen shot 2019-11-02 at 12 22 32](https://issues.joomla.org/uploads/1/c170c7bc0ffe1f2eaeccb30f4ae8cde4.png)same record.

**Comment by astridx** [comment]
I can confirm this on Ubuntu and Firefox
![Menus  Add   test   Administration(1)](https://user-images.githubusercontent.com/9974686/68075328-8dfbd200-fda6-11e9-9d49-9651bfe4b1f1.png)

**Comment by infograf768** [comment]
What happens here is that when saving the menu again after deleting the Unique Name, the `$recordId` is lost ( it equals 0) and the menu is considered as a new menu.
Then as the id is different from the one already recorded, it throws the error.
Not sure we can do anything about it.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/28053.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26947">issues.joomla.org/tracker/joomla-cms/26947</a>.</sub>
