### ISSUE TITLE
[4.0] So many Scrolls in Media  #pbf19 #bug

### ISSUE THREAD

**Issue by kk9** [joomla/joomla-cms#26942]
### Steps to reproduce the issue
1)Click on add Article
2)New Article
3)click on the Images and Links tab
4)Click on select image
4)Check media pop up

### Expected result

We will remove Inner scroll 
or 
We can use the only inner scrolls

### Actual result

There are so many scrolls, which is not needed

**Comment by Quy** [comment]
Duplicate #26703<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26942">issues.joomla.org/tracker/joomla-cms/26942</a>.</sub>
