### ISSUE TITLE
[4.0]Components -> Categories -> New category -> options -> Image - The error message not representing correctly if user click on delete button without selecting item.#pbf19 #bug

### ISSUE THREAD

**Issue by AdityaTaware** [joomla/joomla-cms#26941]
### Steps to reproduce the issue
1. Go to Components -> Categories -> New category -> options -> Image.
2. Click on the Select button.
3. Without selecting items click on the Delete button.
4. Observe the error message.

### Expected result
The error message should have a background color.

### Actual result
The error message background strip doesn't have color.

### Additional comments
Check the same issue throughout the ![screen shot 2019-11-02 at 11 39 53](https://issues.joomla.org/uploads/1/0dcb19d38873417773cb0a747b7705a9.png)admin site.

**Comment by Quy** [comment]
Duplicate #26663 as it has to do with Media.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26941">issues.joomla.org/tracker/joomla-cms/26941</a>.</sub>
