### ISSUE TITLE
Unable to logout from administrator view

### ISSUE THREAD

**Issue by jaisheela** [joomla/joomla-cms#26940]
### Steps to reproduce the issue
Login to website
Login to system
Now click browser back
you are logged in
Now try to log out

### Expected result
Should logout successfully

### Actual result

Unable to log out
shows error
admin-menu.min.js:1 Uncaught TypeError: Cannot read property 'classList' of null
    at admin-menu.min.js:1
    at admin-menu.min.js:1![screen shot 2019-11-02 at 11 39 26](https://issues.joomla.org/uploads/1/310128b0955a892da0e580ca6705e915.png)

### System information (as much as possible)

php73
4.0.0-alpha11

**Comment by Quy** [comment]
You are using an older alpha. Please use the latest nightly build and report if it is still an issue. https://developer.joomla.org/nightly-builds.html<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26940">issues.joomla.org/tracker/joomla-cms/26940</a>.</sub>
