### ISSUE TITLE
[4.0] UI issue - Frontend Article edit - tinyMCE editor - styling options looking weird

### ISSUE THREAD

**Issue by SharayuYadav** [joomla/joomla-cms#26944]
Note: Please use tinyMCE editor to reproduce following issue 
### Steps to reproduce the issue
Edit the article from the frontend.
Go to paragraph->inline check options

![screen shot 2019-11-02 at 12 13 01](https://issues.joomla.org/uploads/1/c00190d3c2e0358dddb847fb799648bc.png)

### Expected result
It should look complete text in single line

**Comment by infograf768** [comment]
Confirmed. Set to release blocker.

**Comment by alikon** [comment]
please test #28579<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26944">issues.joomla.org/tracker/joomla-cms/26944</a>.</sub>
