### ISSUE TITLE
[4.0] RFC:  Change the word "columns" in blog category view to Intro Item Columns & also add same feature for leading

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#26950]
### Steps to reproduce the issue
I see "columns" and if I hover I see which section columns affects.  But I think it should be even clearer by adding the word "intro"

![image](https://user-images.githubusercontent.com/4665225/68071341-9e458a00-fd71-11e9-8666-41ddbdfd517e.png)

I've always found it a little odd that we can only do this on intro articles and not leading.  I actually think the name is a bit weird too as intro and leading have very similar meanings.  

Could we rename these in J4?

**Comment by SharkyKZ** [comment]
In 4.0 column feature is replaced by modifier classes. See https://github.com/joomla/joomla-cms/pull/18319.

**Comment by uglyeoin** [comment]
Fantastic. Perhaps not the .ost user friendly but we can always create a list option to show layout options if need be. A welcome addition.
