### ISSUE TITLE
[3.9] Specify image dimensions for logo

### ISSUE THREAD

**Issue by sshcli** [joomla/joomla-cms#26951]
### Steps to reproduce the issue
Choose a logo in Backend->Extensions->Templates->Styles->Protostar->Advanced->Logo

### Expected result
When you choose a logo in Backend->Extensions->Templates->Styles->Protostar->Advanced->Logo you should be able to specify the dimensions

### Actual result
When you choose a logo in Backend->Extensions->Templates->Styles->Protostar->Advanced->Logo there is no option to specify the dimensions.
When width and/or height attributes are missing, you get a negative impact in page load time
Maybe is not big deal, but something is something 

### System information (as much as possible)
Joomla 3.9.12 + Protostar + PHP 7.3.11 + MySQL 5.7.28

### Additional comments
You can see an example report in gtmetrix.com:
https://gtmetrix.com/reports/www.joomla.org/YDJ05ulT

**Comment by mbabker** [comment]
The height/width attributes aren’t enough, the image would need to be resized appropriately.  The HTML attributes just constrain the size on the rendered page, doesn’t affect the download size.

**Comment by sshcli** [comment]
@mbabker I agree, it doesn’t affect the download size

**The reason I'm reporting this is because:**
Specifying a width and height for all images allows for faster rendering by eliminating the need for unnecessary reflows and repaints.

**Details from Google:**
When the browser lays out the page, it needs to be able to flow around replaceable elements such as images. It can begin to render a page even before images are downloaded, provided that it knows the dimensions to wrap non-replaceable elements around. If no dimensions are specified in the containing document, or if the dimensions specified don't match those of the actual images, the browser will require a reflow and repaint once the images are downloaded. To prevent reflows, specify the width and height of all images, either in the HTML <img> tag, or in CSS.

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed.

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc [@zero-24](https://github.com/zero-24)
