### ISSUE TITLE
Sorry I forgot my login for JOOMLA builder for my web childrenmakingtomorrown.com. Could you please help me reset them.

### ISSUE THREAD

**Issue by Ibrom47** [joomla/joomla-cms#26961]

**Comment by N6REJ** [comment]
Are you asking about https://launch.joomla.org/ ?

**Comment by Ibrom47** [comment]
I need reset my password User Is IlyaB47, but I forgot my password for My Joomla builder

**Comment by Quy** [comment]
Sorry this repo is not for personal assistance. Please try Joomla Forum at https://forum.joomla.org/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26961">issues.joomla.org/tracker/joomla-cms/26961</a>.</sub>
