### ISSUE TITLE
[4.0] User item list in front

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#26973]
hello i think we have great tool for intranet in j4:
- custom field
- new workflow
- new transition
- new templating system

but i think we need a new view to acheive a some piece of intranet type

in front we we can't display user connected items with a single view ... it can be perfect in many case and i didn't think its an hard work (i am a dev but it my idea)

For me 2 possibility if some one can be interesting
- adding filter by **user / current user** in **blog / defaut view**
- adding a new menu link like category view with defaut template with filter by **user / current user** 

with this we can add view to alow user to manage they content more easly
what do you think ?

**Comment by brianteeman** [comment]
please see #25030

**Comment by micker** [comment]
hello thanks i see it but its a list of users
the=at i explain is a list of content, filter by a specific user or  current user connected

**Comment by brianteeman** [comment]
Sorry now I re-read your post I see it was not relevant

I think I do something like your idea on one of my sites with a module
![image](https://user-images.githubusercontent.com/1296369/68145003-b4e41080-ff2c-11e9-98e9-d4ee09c75978.png)

**Comment by micker** [comment]
i know this but i think it more powerfull to have a menu link type not ?
in your case we need menu link + module for a good assignement
2-3 actions ..
if we add filter by user in a category view that finished ... display in component area
not ?
it will be more simple to create view peer type with overide and specific column fr exemple

**Comment by web54** [comment]
Micker's suggestion is a good one 👍 
It suits the needs of those who want to let the user drive the site without going into the backend.
There was on old extension that did that : Frontend User article manager [http://joomlacode.org/gf/project/fual2/](url).
It added a menu item -> view with all the articles, status column, category filter, button to edit, button to unpublish, button to remove.
I guess it will be a great feature in a website for editors.

**Comment by brianteeman** [comment]
I just looked at that - it still works
