### ISSUE TITLE
addScriptOptions caching issue?

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#26975]
### Steps to reproduce the issue
in a content plugin onContentPrepare set scriptoptions via:
1. $document->addScriptOptions and
2. $document->addScriptDeclaration

Both are set correctly on the page

now enable cache
what you will see now is that addScriptOptions is only displayed on first page visit (page generated) but on second page visit (page from cache) the options are not on the page.

addScriptDeclaration works both on first page view and on page view from cache.

### Expected result

$document->addScriptOptions should be stored in the cache
![screen shot 2019-11-04 at 14 05 25](https://issues.joomla.org/uploads/1/a514897425a6cca9bd08fc3c2d086210.jpg)

### Actual result

$document->addScriptOptions is NOT stored in the cache
![screen shot 2019-11-04 at 14 05 40](https://issues.joomla.org/uploads/1/8b6e8d5f5c300104e43cdac11f6d4332.jpg)

### System information (as much as possible)

Joomla 3.9.12

### Additional comments

I ran into this issue after migrating my custom javascript variables in my plugin from addScriptDeclaration to addScriptOptions following this guide: https://docs.joomla.org/J3.x:Adding_JavaScript_and_CSS_to_the_page#Adding_the_Options_to_Your_JavaScript_Code

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/21007.

**Comment by Ruud68** [comment]
So if I understand correctly, the addScriptOptions function is broken on Joomla! sites that have caching enabled? Hope we get a second tester soon so this can be put into production.

thanks @SharkyKZ for pointing me to the solution to this issue!
