### ISSUE TITLE
[4.0] Valid HTML

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#26986]
### Steps to reproduce the issue
Go to the https://validator.w3.org and test a Joomla4 website

### Expected result
Valid HTml

### Actual result
Warning: The navigation role is unnecessary for element nav.

Line 107![screen shot 2019-11-04 at 22 23 52](https://issues.joomla.org/uploads/1/2260b69fc0ff719cb4e3ecb9cd93e23c.jpg)

**Comment by brianteeman** [comment]
It is not saying it is invalid html 
It is not saying there is an error - it's just a polite warning

There was much debate about this and after contacting a w3c member it was confirmed that IE11 did still require role=navigation even though it is a nav

https://mobile.twitter.com/brianteeman/status/1089555677780082690?s=19

**Comment by Open2logic** [comment]
Thanks Brian, i close it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26986">issues.joomla.org/tracker/joomla-cms/26986</a>.</sub>
