### ISSUE TITLE
[4] Config settings not saving

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#26994]
### Steps to reproduce the issue

Go to Admin / Global Configuration / Server / Mail Settings

Enter SMTP data

Send Test Email - that works fine

Save - Error / Could not connect to database

### Expected result

It should be possible to save SMTP settings

### Actual result

The SMTP settings are returned to Default

### System information (as much as possible)

Joomla 4 Alpha 12 / PHP 7.2.5 / MySQL 5.6.34 / MacBook Pro with Eclipse

### Additional comments

Actually, I have since noticed I cannot save any configuration settings. The error starts on

administrator/components/com_config/Model/ApplicationModel.php on line 140

and is thrown in libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php on line 274 where there is an untranslated error string.

**Comment by Quy** [comment]
Please test the nightly build to see if you can reproduce the issue. 
https://developer.joomla.org/nightly-builds.html

**Comment by ceford** [comment]
I restarted my computer and this problem went away. It may be something to do with the MySQL connection. So not an issue unless someone else reports something similar.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26994">issues.joomla.org/tracker/joomla-cms/26994</a>.</sub>
