### ISSUE TITLE
Cannot output multiple jdoc:include with same position of different style

### ISSUE THREAD

**Issue by Meday** [joomla/joomla-cms#26993]
### Steps to reproduce the issue
Add 1 module in position 1

templates/beez3/index.php :

<jdoc:include type="modules" name="position-1" style="MyStyle1"/>
<jdoc:include type="modules" name="position-1" style="MyStyle2"/>

templates/beez3/html/modules.php

  function modChrome_MyStyle1( $module, &$params, &$attribs ) {
    echo 'MyStyle1';
  }
  function modChrome_MyStyle2( $module, &$params, &$attribs ) {
   echo 'MyStyle2';
  }

### Expected result

Display in position-1 :
MyStyle1
MyStyle2

### Actual result

Display in position-1 :
MyStyle2
MyStyle2

### System information (as much as possible)

Joomla 3.9.12

### Additional comments

I use this for different display (mobile, screen...)
It can be interesting to use it also with diffrents attributes for multiple call of the same postion, same style.

For exemple: 
<jdoc:include type="modules" name="position-1" style="MyStyle1" mobile="1"/>
<jdoc:include type="modules" name="position-1" style="MyStyle1"/>

**Comment by SharkyKZ** [comment]
I can see where this is coming from but I'm not sure if this is not intended. Having multiple instances of the same position in the same document seems wrong to me.

**Comment by brianteeman** [comment]
I agree with @SharkyKZ 
If you want to achieve this you would create two modules in the same position with different styles.

This should be closed
