### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by no-matter-0** [joomla/joomla-cms#26991]
add **figure** to ModuletagField.php
add **figcaption** to HeadertagField.php

thanks

**Comment by no-matter-0** [comment]
add figure and details to ModuletagField.php
add figcaption ans summary to HeadertagField.php<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26991">issues.joomla.org/tracker/joomla-cms/26991</a>.</sub>

**Comment by brianteeman** [comment]
That makes no sense. Please explain further exactly your use case for this.

**Comment by Quy** [comment]
Closing due to lack of response. You can comment here and we can re-open the issue.
