### ISSUE TITLE
Improve flexibility of application enqueueMessage() function

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#26997]
### Steps to reproduce the issue

JFactory::getApplication()->enqueueMessage('My message', 'My Message Type')

### Expected result
Displays
**My Message Type**
My Message

### Actual result

Displays
**my message type**
My Message

### System information (as much as possible)

Joomla 3.9

### Additional comments

Suggest changing the function parameters to:

_public function enqueueMessage($msg, $type='message', $format='strtolower')_

And add a function exists check message enqueue line to:

_if (!empty($type) && function_exists($type))
{
    $type = $format($type);
}
$this->_messageQueue[] = array('message' => $msg, 'type' => $type);_

There are other ways of getting round this, such as in the template, but this change puts the design decision into the hands of the component / module developer.

**Comment by mbabker** [comment]
The type isn't meant to be used in this way.  The type really should be a standardized value (which 4.0 provides by defining a set of message type constants that match up to the PSR-3 log levels basically), not a section heading or anything like that.  Then it's up to the template to theme the message types.

**Comment by brianteeman** [comment]
As @mbabker this is not the correct use of the type and this issue should be closed (and it woun't work in j4 anyway)
