### ISSUE TITLE
[4.0] cli/finder_indexer.php fails on Alpha 12

### ISSUE THREAD

**Issue by skurvish** [joomla/joomla-cms#27007]
### Steps to reproduce the issue
From a command prompt run finder_indexer.php

### Expected result

Not sure but it fails

### Actual result
Fatal error: Class FinderCli contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Joomla\CMS\Application\CMSApplicationInterface::getName, Joomla\CMS\Application\CMSApplicationInterface::getMenu) in /var/www/html/cli/finder_indexer.php on line 59

### System information (as much as possible)
Alpha 12

### Additional comments
I am trying to get a CliApplication and WebApplication running on Alpha 12 but unable to. Got the same error as finder_indexer.

**Comment by skurvish** [comment]
Also, php 7.2.19 on Ubuntu 18.04.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27007">issues.joomla.org/tracker/joomla-cms/27007</a>.</sub>

**Comment by mbabker** [comment]
That file still needs to be ported to use the CLI Console application.  Problem is, there still isn't a good way for components to register commands since Joomla lives in a world where everything is lazy loaded (this is one of those cases where the lazy loading hurts more than helps).

**Comment by skurvish** [comment]
Fair enough. I don't actually need console support itself, just want to get both a cli and web application ported over from J3.x They both run fine in J3.9 but not in 4.0. Is there another example I can use?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27007">issues.joomla.org/tracker/joomla-cms/27007</a>.</sub>

**Comment by skurvish** [comment]
In my cli app I am able to get it to run past this error by providing 2 stub functions, one for getName and one for getMenu. I would suspect however that I should be able to startup a cli session without these.

I also note that if I use a constructor in my cli class the parameters from the class call are never passed through to my class or to the parent CliApplication constructor.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27007">issues.joomla.org/tracker/joomla-cms/27007</a>.</sub>

**Comment by jwaisner** [comment]
@skurvish is this still happen in the latest build?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27007">issues.joomla.org/tracker/joomla-cms/27007</a>.</sub>

**Comment by skurvish** [comment]
I haven't tried it again on J4. Not sure when I can do so as I am heading off on a trip for the next 5 weeks.

**Comment by skurvish** [comment]
This issue is still happening under the current J4 git. Two functions missing, Joomla\CMS\Application\CMSApplicationInterface::getInput, Joomla\CMS\Application\CMSApplicationInterface::getName

This is very easy to test, just run /cli/finder_indexer.php from a browser in the local web, or call it via php on a command line.

**Comment by richard67** [comment]
@skurvish Please test #28506 .

**Comment by richard67** [comment]
Cosing as having Pull Request (PR) #28506 which solves this issue.
