### ISSUE TITLE
[4.0][mod_menu] Blank img tag

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#27009]
Related to PR #25929

@infograf768 Please fix to not output `<img src="" alt="" >`. Thanks.

https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/modules/mod_menu/tmpl/default_submenu.php#L117

### Steps to reproduce the issue
Log in the administration area
View page source
Search for `<img src="" alt="" >`

**Comment by infograf768** [comment]
hmm

**Comment by infograf768** [comment]
Weird. The only way I found was to change that line to
`$iconImage = '';`

There must be something else here I do not see.

**Comment by infograf768** [comment]
In fact, `$iconImage = '';` is correct. Making patch now.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/27036

closing as we have  a patch
