### ISSUE TITLE
[4.0] Undefined index: featured_up/featured_down

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#27001]
### Steps to reproduce the issue
Install Blog Sample Data
View PHP error log

### Actual result
> PHP Notice:  Undefined index: featured_up in \administrator\components\com_content\Model\ArticleModel.php on line 950
PHP Notice:  Undefined index: featured_down in \administrator\components\com_content\Model\ArticleModel.php on line 950

**Comment by richard67** [comment]
Again this thing with those new columns featured_up and down having been moved from the content to the frontpage table ... will see if I can solve this issue, but I am not sure if I find time tonight, and tomorrow I will be away ... so it may take some time.

**Comment by infograf768** [comment]
I confirm the issue.

**Comment by richard67** [comment]
Yes, can confirm, too.

**Comment by Quy** [comment]
See PR #27008. Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27001">issues.joomla.org/tracker/joomla-cms/27001</a>.</sub>

**Comment by richard67** [comment]
Please test PR #27008 .
