### ISSUE TITLE
My website reads this message.......  "It appears you don't have permission to access this page. 403 Error. Forbidden."  Please help me fix this, we are a business and need it to be operating. asap.

### ISSUE THREAD

**Issue by SharonsDanceStudio** [joomla/joomla-cms#27010]

**Comment by Quy** [comment]
Sorry this repo is not for personal help. Please post to Joomla Forum. https://forum.joomla.org/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27010">issues.joomla.org/tracker/joomla-cms/27010</a>.</sub>
