### ISSUE TITLE
[4.0] Display Start/Finish Featured in Versions

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#27011]
`Featured` is displayed, but not `Start Featured` and `Finish Featured` in the `Preview of version...`. I assume these dates should be displayed too.

**Comment by brianteeman** [comment]
That wont be possible afaict

the versions is only storing the data in #__content. The optional start and finish featured data is in #__content_frontpage

imho displaying that would also be confusing as people may think it is the date that the article was changed to be featured
