### ISSUE TITLE
[4.0] Upgrade to FontAwesome 5.11.2

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#27019]
From https://github.com/joomla/joomla-cms/issues/25915#issuecomment-544107766

> There is now a 5.11.2 version of fontawesome and using the regular would fit.
We just need to update as the version we use is quite old (5.9.0)

**Comment by brianteeman** [comment]
You just need to do npm update and then commit

**Comment by Quy** [comment]
See PR #27028. Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27019">issues.joomla.org/tracker/joomla-cms/27019</a>.</sub>
