### ISSUE TITLE
[4.0] Framework /application fatal error

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27026]
### Steps to reproduce the issue
composer update joomla/framework

### Expected result
joomla continues to work

### Actual result

> Fatal error: Class Joomla\CMS\Application\AdministratorApplication contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Joomla\CMS\Application\CMSApplicationInterface::getSession) in C:\htdocs\joomla-cms\libraries\src\Application\AdministratorApplication.php on line 32

### Additional comments

Output from update

> C:\htdocs\joomla-cms>composer update joomla/application
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Package operations: 0 installs, 1 update, 0 removals
>   - Removing joomla/application (dev-2.0-dev 3d549e0)
>   - Installing joomla/application (dev-2.0-dev e15eb04): Loading from cache
> Writing lock file

Reverting that update and everything works

**Comment by SharkyKZ** [comment]
Related PR https://github.com/joomla/joomla-cms/pull/26820.

**Comment by brianteeman** [comment]
Thanks @SharkyKZ
