### ISSUE TITLE
[4.0] COM_CATEGORIES_CATEGORY_BASE_EDIT_TITLE

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#27025]
### Steps to reproduce the issue
Install multilingual 
Go to Content > Categories
Edit `Uncategorised`
Click `Associations` button

### Actual result

![uncategorised](https://user-images.githubusercontent.com/368084/68498273-514b3300-020b-11ea-99b3-c473cf0a886d.jpg)

**Comment by richard67** [comment]
Confirmed.

**Comment by Quy** [comment]
Please test PR #27029.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27025">issues.joomla.org/tracker/joomla-cms/27025</a>.</sub>

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/27031
