### ISSUE TITLE
Codestyle on xml files

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27022]
The coding standards state that we should use tabs not spaces yet when an xml file is using spaces and not tabs it is not failing the tests

**Comment by HLeithner** [comment]
We didn't find any xml validator till now. Thats the reason the test doesn't fail because we didn't test it^^

**Comment by brianteeman** [comment]
Must exist somewhere as intelliJ have a good one https://www.jetbrains.com/help/idea/settings-code-style-xml.html
