### ISSUE TITLE
Joomla! 3.9.11...3.9.13 - No Popular tags module

### ISSUE THREAD

**Issue by slepoy1** [joomla/joomla-cms#27027]
Hi. I just updated to latest Joomla! 3.9.13 and noticed that Popular tags module was disappeared. I tried to clear cashe and change to default Joomla template, but module is still hidden...

### Steps to reproduce the issue
Steps to reproduce the issue
Have a module "Popular Tags" visible in the frontend
In the Joomla Backend: check for Joomla updates (current version 3.10)
Update to Joomla 3.9.11, 3.9.12 or 3.9.13
Expected result
The "Popular Tags" Module is still visible in the frontend

### Actual result
The "Popular Tags" Module disapears
I also cleared all caches and tried different templates, e.g. Protostar

**Comment by ChristineWk** [comment]
Checked and tested with current version J 3.9.13 - Protostar (generally not using tags):

Before this, I had to activate Tags-Popular under: Extensions Manage > Manage > Extensions Module > Tags-Popular!
Check also directly under Module > Tags-Popular > Status / Position / for test purposes: Show Title etc. 
See also: https://github.com/joomla/joomla-cms/issues/26061
Result:
![screen shot 2019-11-09 at 10 27 17](https://issues.joomla.org/uploads/1/bf47d15720f635a908fca5b608876437.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27027">issues.joomla.org/tracker/joomla-cms/27027</a>.</sub>

**Comment by Quy** [comment]
In v3.9.11, PR #25473 changed the behavior of Popular Tags module. Please read the PR for details. If you need assistance, please post to [Joomla! Forum](https://forum.joomla.org/).
