### ISSUE TITLE
Admin usability enhancement: Simplifying workflow and access to related admin function and configurations

### ISSUE THREAD

**Issue by Salmon-Bard** [joomla/joomla-cms#27033]
This is a proposal from my long 14 years of working with Joomla
Use case:
Set and configure multilingual site.
There are language component sections settings, language plugins configurations, and language switch models. This is time consuming to navigate from one to another. 
Can We have a simple way to access all language related things on the admin UI.

solution:
Adding links to related settings within each component, plugin, module. so that if your working on settings in the language component UI you see a related settings box that has links to language related plugins and modules to allow you jump directly the required settings. and the same if your on language models or plugins. 

Same goes for search, articles, login ..etc.
This is very useful for new comers to Joomla since they have to spend a lot of time to figure out how to configure all aspects of a single function in Joomla as configurations are scattered between system configs, component configs, plugins configs, and modules config.

A search bar for admin panel would be also great to search in your settings and get all the configurations in one search result UI. you can the save this search in bookmark sidebar menu for fast access

**Comment by brianteeman** [comment]
If you could provide more details it would be easier to understand - perhaps include mockup screenshots

**Comment by infograf768** [comment]
> Use case:
Set and configure multilingual site.

Maybe we could indeed create a specific menu preset with a list of various items/config settings. 

In no order

Language filter plugin
Language code plugin
Modules Manager filtered by mod_languages items
Installed Languages
Content Languages
Multilingual Associations component
Modules config but how to display precisely the Administrator Modules tab
Articles Config  but how to display precisely the Show Associations field

**Comment by infograf768** [comment]
oops, sorry. reopening.

**Comment by Salmon-Bard** [comment]
The main objective is that admin works on setting and configuring site and CMS specific functions (search, langauge, themes, users ..etc) he is not looking at specific plugin, module or component name, all he wants is the function to work as intended . 
So if he is working on setting up search for example, the simplest way to reach the required setting pages is to group and categories them under functions labels Not like what we have currently which is type of extensions categorizing and groping (like plugins -> system plugin -> smart search). 

There for if we have a search category under which all search related settings live regardless of their types and system categorizing this will reduce time consumed searching for require type of extension to set all parameters to achieve  intended result.

**Note:** one of the long standing negative usability feedback and reviews of Joomla is the complex and extensive settings work required to get your site configured, with each site function settings scattered between main component, plugins, modules, menus.

here are some mockups to help get this concept through.

![Multilingual Associations  Select Item Type and Language  - Administration](https://user-images.githubusercontent.com/12681954/68893247-6e14c880-072d-11ea-8e73-f83567c55109.png)
![admin-cp](https://user-images.githubusercontent.com/12681954/68893248-6e14c880-072d-11ea-8193-e385b95b1d56.png)
![administration-search](https://user-images.githubusercontent.com/12681954/68893249-6e14c880-072d-11ea-88bc-c236241faafc.png)

**Comment by Salmon-Bard** [comment]
Here is another approach to functional workflow using tapped navigation. Which I think more practical from UX prospective.

![Search -tapped- Administration](https://user-images.githubusercontent.com/12681954/68901605-e6d05080-073e-11ea-9d23-9b1bcabefe4a.png)

**Comment by infograf768** [comment]
This would be a major change and I do not think it can be implemented in j4.
BTW, you should test J4 and not J3
https://developer.joomla.org/nightlies/Joomla_4.0.0-beta1-dev-Development-Full_Package.zip

**Comment by Salmon-Bard** [comment]
@infograf768 
thanks for your reply
I think being stuck in the 20 years old Joomla workflow paradigm is not going to help Joomla advance. Joomla adoption is declining rapidly while Joomla 4 is advancing very well on technology side the UX is still lagging. 

People has less time to learn and spend on getting websites working with all the competition from WordPress and other out of the box fancy site builders.
Productivity is the keyword here. Functional workflow model addresses productivity not on tasks level but on results level.

The functional workflow is a UX template level change not a major core or framework level redesign. The proposed workflow can be provided as a new template alternative while keeping the current classic workflow template as default. 

I think a good extension development company can develop such UX workflow without even touching system core.

Sorry for Joomla 3 images
I do test Joomla 4 Alpha from time to time but did not have installation ready when creating the mockups

**Comment by Salmon-Bard** [comment]
No answer!!!.... really disappointed on how much closed minded Joomal core team has became.

I'm moving away from Joomal following the majority of the flock in the community. 

Good luck with the NEW-OLD mixed Joomla 4 refreshed tech and boring old UX metaphor.

**Comment by brianteeman** [comment]
As a 14 year veteran thank you for your first proposal. What you are proposing is incredibly complex and would require an extensive rewrite.

**Comment by Salmon-Bard** [comment]
Thanks for your efforts and closing. 
Hopefully after the official release of stable V4.0 I will investigate creating a UI with a productive functional alternative for my clients. Without the complexity of going through tens of menus and pages to find the right setting to enable or disable a feature. Hopefully I will not need to create my own fork.
