### ISSUE TITLE
Menu main type is reset after choosing a menu item type

### ISSUE THREAD

**Issue by webmasterab** [joomla/joomla-cms#27034]
### Steps to reproduce the issue
1. login to the joomla backend
2. go to menu
3. create a new menu
4. give title
5. set main item
![screen shot 2019-11-09 at 15 28 46](https://issues.joomla.org/uploads/1/5078b212535260436d8e2488b06536b5.jpg)!
6. Now choose the menu type
![screen shot 2019-11-09 at 15 29 48](https://issues.joomla.org/uploads/1/af831ebdf6994ee9bc38a04cacce213d.jpg)

if the menu type is set, the main item is back on menu-root and you have to set it again

### System information (as much as possible)
Joomla 3.9.13 as well below.
I no longer know exactly which version I am aware of.

**Comment by Quy** [comment]
Duplicate #22150<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27034">issues.joomla.org/tracker/joomla-cms/27034</a>.</sub>
