### ISSUE TITLE
[4.0] Old code?

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#27037]
Is the line https://github.com/joomla/joomla-cms/blob/231740ba3634ec8eefabb8108f270eaae32bebf9/administrator/components/com_contact/controllers/ajax.json.php#L59 line correct?

`Table::addIncludePath(JPATH_ADMINISTRATOR . '/components/com_contact/tables');`

**Comment by infograf768** [comment]
Similar code for menu and newsfeeds. Look like this has not yet been updated to use Table, Factory, Text, etc

These files are no more present in J4 where they are replaced by AjaxController

**Comment by wilsonge** [comment]
It's fine as it is in J3

In J4 looks incorrect https://github.com/joomla/joomla-cms/blob/4.0.0-alpha12/administrator/components/com_contact/Controller/AjaxController.php#L65 - you're right needs to use the namespaced version of the code - obviously for example the directory for table doesn't exist there etc.

**Comment by alikon** [comment]
it seem's  Ok now.....closing

**Comment by wilsonge** [comment]
At least the line I linked to in 4.0-dev isn't ok. so reopening

**Comment by wilsonge** [comment]
See https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_contact/Controller/AjaxController.php#L65 as an example.

**Comment by SharkyKZ** [comment]
Please test https://github.com/joomla/joomla-cms/pull/27984.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27037">issues.joomla.org/tracker/joomla-cms/27037</a>.</sub>
