### ISSUE TITLE
Better favicon (HD) for isis template

### ISSUE THREAD

**Issue by Matysh** [joomla/joomla-cms#27043]
### Steps to reproduce the issue
1. Open joomla admin panel on retina display or 4k display with 200% system scale
2. Review favicon quality

### Expected result
Pretty icon (32x32)

### Actual result
Blurred icon (16x16)![screen shot 2019-11-11 at 05 19 55](https://issues.joomla.org/uploads/1/b8a3246be8e96363ccc4ad3a09e62288.png)

HD favicon can be downloaded hereL
https://yadi.sk/d/mEdtOCdzASy8Hw (can't attach this file type to issue)

**Comment by brianteeman** [comment]
As the isis icon now defaults to an svg this can be closed as resolved
