### ISSUE TITLE
Incorrect action on trash icon in materials manager

### ISSUE THREAD

**Issue by Matysh** [joomla/joomla-cms#27042]
### Steps to reproduce the issue
1. Remove any material to trash
2. Open list of materials in the trash
3. Click on trash icon near material title

### Expected result
Material removed from trash

### Actual result
Material restored (published)
Tooltip for trash icon also incorrect.

**Comment by brianteeman** [comment]
Which version of Joomla. Can you provide screenshots of the exact page and problem

**Comment by GCLW** [comment]
Looking at the article list view in 3.9.13

From what I can gather the tiny trash can icon indicates the item is "trashed". Same as the green check mark denotes "published" and the red circle with the white x is "unpublished".

Those are status, not action indicator icons.

For as long as I can remember clicking on the trash can icon was a quick re-publish. Not a delete from system action. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27042">issues.joomla.org/tracker/joomla-cms/27042</a>.</sub>

**Comment by Quy** [comment]
Duplicate #20258<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27042">issues.joomla.org/tracker/joomla-cms/27042</a>.</sub>
