### ISSUE TITLE
Smart Search: an option to disable OpenSearch xml-file

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#27040]
### Is your feature request related to a problem? Please describe.
I've added a menu item to the Smart Search component. 
However, I noticed an unnecessary line in the HTML:

`<link href="http://site.name/component/search/?id=45&amp;Itemid=104&amp;format=opensearch" rel="search" title="title" type="application/opensearchdescription+xml" />`

I want to avoid the generation of such a line in the code, but there is no way to disable it.
Someone asked such a question here:
https://joomla.stackexchange.com/questions/22843/joomla-how-to-disallow-joomla-download-opensearch-xml-file

My suggestion is to add an option to the component settings like:

Enable OpenSearch -- Yes / No

**Comment by Quy** [comment]
No new features in J3, however, this has been implemented in J4.
