### ISSUE TITLE
[4.0] Deprecated isSite & isAdmin

### ISSUE THREAD

**Issue by Stuartemk** [joomla/joomla-cms#27046]
### What needs to be fixed
CMSApplication
The $_clientId, $_messageQueue and $_name class properties have all been renamed to remove their underscore prefix.
Now implements CMSApplicationInterface
If there is an error retrieving a Pathway, Router or Menu object using the respective methods the exception will now bubble up rather than the method silently catching the exception and returning null
CMSApplication::getInstance will now additionally try and load the user object (using the loadIdentity function)
CMSApplication::isSite and CMSApplication::isAdmin have been removed as with the addition of the ConsoleApplication and ApiApplication can give misleading results. Please use CMSApplication::isClient (available from Joomla  3.7). For more information please see Discover on which client your extension code is running

### Why this should be fixed
Still present into Joomla 4

### How would you fix it
# grep -iRl "isAdmin" /home/public_html
/public_html/layouts/joomla/edit/admin_modules.php
/public_html/libraries/src/Form/Field/ListField.php
/public_html/libraries/src/Helper/ModuleHelper.php
/public_html/administrator/components/com_menus/Controller/DisplayController.php
/public_html/administrator/components/com_modules/View/Modules/HtmlView.php
/public_html/administrator/components/com_modules/tmpl/modules/default.php
/public_html/administrator/components/com_modules/tmpl/modules/default_batch_body.php
/public_html/administrator/components/com_modules/Model/ModuleModel.php
/public_html/administrator/components/com_modules/Controller/DisplayController.php

**Comment by SharkyKZ** [comment]
>grep -iRl "isAdmin" /home/public_html

You need to refine your search because all those results are `Joomla\CMS\Helper\ModuleHelper::isAdminMultilang()` calls.

**Comment by Stuartemk** [comment]
Best regards.
