### ISSUE TITLE
Option to hide ACL group in frontend

### ISSUE THREAD

**Issue by Tazzios** [joomla/joomla-cms#27053]
**Situation**
In my Joomla instance i have a lot of ACL groups for my extensions like 'agenda editor events', 'agenda editor building', 'Newsletter creator general' etc.
When people now add articles they have a long list of ACL groups they can choose from which is confusing. I reordered them to have the most important on top which helps a little. But the best solution would be if there was an option to hide some ACL groups.

**Wish**
I would like a option 'hide in frontend' for each individual ACL group.

**Comment by joomdonation** [comment]
This has been opening for 3 more years without any feedback. I don't think there is any chance this could be implemented in core, so I'm closing this issue.
