### ISSUE TITLE
[4.0] batch content fails

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27060]
I am sure this has been reported before (maybe by me) but I can not find it now.

It is not possible to batch copy any articles. This is because of the workflow. The content item is copied in the _content table but the item is not created in the _workflow_associations table. As a result the article is not available.

I know there was talk over the summer of workflows being rewritten but there has been no sign of this and if Joomla 4 is ever going to make it to a beta release etc then this and other workflow bugs need to be addressed

**Comment by Quy** [comment]
Maybe these PRs https://github.com/joomla/joomla-cms/pull/24519 and https://github.com/infograf768/joomla-cms/pull/55.

**Comment by richard67** [comment]
And PR #26835, for which is [https://github.com/infograf768/joomla-cms/pull/55](https://github.com/infograf768/joomla-cms/pull/55).

**Comment by richard67** [comment]
Please test #26835 ... the title of that PR doesn't reflect that yet, but it solves the problem with batch copying acticles in general.

**Comment by alikon** [comment]
please test #26835<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27060">issues.joomla.org/tracker/joomla-cms/27060</a>.</sub>
