### ISSUE TITLE
Missing word in CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by mohitm15** [joomla/joomla-cms#27063]
### What needs to be fixed
The missing word in the file.
_ _ _ _
### Why this should be fixed
To correct it grammatically.
_ _ _ _
### How would you fix it
By sending PR for this issue
_ _ _ _
### Side Effects expected
No

**Comment by C-Lodder** [comment]
As you've submitted a PR (#27064), please close the issue.

**Comment by alikon** [comment]
see #27064<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27063">issues.joomla.org/tracker/joomla-cms/27063</a>.</sub>

**Comment by mohitm15** [comment]
> As you've submitted a PR (#27064), please close the issue.

But I think it gets only be closed after the PR regarding this gets merged
