### ISSUE TITLE
The latest version don't have the Redis option for caching.

### ISSUE THREAD

**Issue by vandolphreyes** [joomla/joomla-cms#27065]
Hello, I tried the latest version on joomla but I can't see the redis option under cache settings, I'm using windows, I also installed it and run it too but still I can't see the option for redis inside the dropdown. When I try to change the config to "redis", its saying "Error: The redis Cache Storage is not supported on this platform. laravel"

**Comment by vandolphreyes** [comment]
Okay, please ignore, our boss was able to find the solution. He just installed "php71-pecl-redis 3.1.1-1.2.amzn1". Thanks

**Comment by mbabker** [comment]
For reference some of the fields in the global config have different options based on the server setup.  The cache, database, and session configs are all examples of this; so if you’re not seeing an option you expected to the answer is generally the corresponding PHP extension isn’t properly installed and enabled.
