### ISSUE TITLE
com_contact default setting allows spam

### ISSUE THREAD

**Issue by djalondon** [joomla/joomla-cms#27066]
### Steps to reproduce the issue
On 2 separate Joomla installs a contact was created without amending the default Contact Component settings. The email address for the contact was subsequently spammed with the website user first using /index.php?option=com_contact&view=contact&id=1 to check the contact existed. Then posted to the form which is available by default.

### Expected result

Contact can't be emailed unless the form is enabled, and secured with Captcha

### Actual result

The form was available to view and no Captcha or anti-bot mechanism was enabled

### System information (as much as possible)

Fresh install, no changes made to Contact Configuration except a contact was created. Joomla 3.9.12

### Additional comments

Web hosts see this as spam activity and one client's account was suspended. In both traffic came from the same IP addresses.

**Comment by Quy** [comment]
Duplicate #24187. If you don't use the Contacts component, then disable it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27066">issues.joomla.org/tracker/joomla-cms/27066</a>.</sub>

**Comment by djalondon** [comment]
Maybe the settings shouldn't be enabled by default in the first place?

**Comment by brianteeman** [comment]
If you dont have a contact on the site then there isnt even any need to disable it
