### ISSUE TITLE
[4.0] Category factory lacks caching

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#27073]
### Steps to reproduce the issue

Create some categories.
View frontend pages that contain many links to categories.

### Expected result

An OK number of queries.

### Actual result

Too many duplicate queries.

### Additional comments

Using the old `JCategories::getInstance()` method here eliminates duplicate queries:

https://github.com/joomla/joomla-cms/blob/4d6c67948ed3e0b642f3924eca63b9f7acb29a14/components/com_content/Service/Router.php#L104

**Comment by wilsonge** [comment]
The problem is because CategoryNode is a mutable class (i.e. we can change the data in it without saving) it shouldn't be cached in certain cases. It's on of those super tricky things where there's no obviously correct answer :/

**Comment by SharkyKZ** [comment]
Frontend performance in J4 is really crap because of this 😟 .

**Comment by SharkyKZ** [comment]
See PR https://github.com/joomla/joomla-cms/pull/27710 for adding caching to routers only .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27073">issues.joomla.org/tracker/joomla-cms/27073</a>.</sub>
