### ISSUE TITLE
404 Error into github page

### ISSUE THREAD

**Issue by docbenway75** [joomla/joomla-cms#27070]
### Steps to reproduce the issue
Hi,
i hava a script for auto upgrade my joomlas. 
Into this page, https://github.com/joomla/joomla-cms/releases/tag/3.9.13,  there is an error that does not allow me to use my script: should replace 3.8.12 and 3.8.x with 3.9.12 and 3.9.x respectively.

Thanks and best regards.

### Expected result

    New Joomla! Installations .tar.bz2 | .tar.gz | .zip
    Update from Joomla! 3.9.12 .tar.bz2 | .tar.gz | .zip
    Update from Joomla! 3.9.x .tar.bz2 | .tar.gz | .zip
    Update from Joomla! 2.5 or previous 3.x releases .tar.bz2 | .tar.gz | .zip

### Actual result

    New Joomla! Installations .tar.bz2 | .tar.gz | .zip
    Update from Joomla! 3.8.12 .tar.bz2 | .tar.gz | .zip
    Update from Joomla! 3.8.x .tar.bz2 | .tar.gz | .zip
    Update from Joomla! 2.5 or previous 3.x releases .tar.bz2 | .tar.gz | .zip

**Comment by HLeithner** [comment]
Fixed. sorry
