### ISSUE TITLE
[4.0] Choices.js

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27083]
This library has recently had two breaking change releases that we have not consumed because of the criteria correctly set in package.json.

Creating a PR to update our release is easy but I'm not sure if the _breaking changes_ have an impact on us or even how to check them.

https://github.com/jshjohnson/Choices/releases

**Comment by Fedik** [comment]
They dropped placeholder param for `<select>` input https://github.com/jshjohnson/Choices/pull/731 :smile: crazy

Need to check what we can do. 
Other stuff seems to work fine.

**Comment by Fedik** [comment]
please test #27093

**Comment by alikon** [comment]
closed as we have a pr #27093<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27083">issues.joomla.org/tracker/joomla-cms/27083</a>.</sub>
