### ISSUE TITLE
Repeatable custom field - Editor field: JCE-Editor problems when adding new list-item it adds the text area under the editor field

### ISSUE THREAD

**Issue by amit4106udale** [joomla/joomla-cms#27106]
This can be reproduced in old created fields like while using Joomla 3.9.6

I created different repeatable fields with text and editor field in it while using Joomla 3.9.6

But when I upgraded it to the latest. It started creating problems.

Whenever I click on add new item the editor changes to the text area and the data filled in the first editor field disappears.

The editor used is JCE.

![1574248064783](https://user-images.githubusercontent.com/26816967/69234059-2cb06d00-0bb4-11ea-8fb0-3ea39aa908d0.png)

**Comment by SharkyKZ** [comment]
Could you check if #27081 fixes the problem? And can you reproduce this issue with TinyMCE?

**Comment by amit4106udale** [comment]
@SharkyKZ  - I change the editor to tinyMCE. It's working fine then. But as per our client requirement, i need to use jce.

Also checked with the code of #27081. it is working. I have a question. Will this affect my existing data?

**Comment by Quy** [comment]
@amit4106udale So PR #27081 does not work with JCE? It should not affect your existing data.

If issue is fixed, please mark your test successful at the issue tracker so it can be merged with one more test. Thank you.

https://issues.joomla.org/tracker/joomla-cms/27081

**Comment by amit4106udale** [comment]
@Quy -> Does this effect to other editors Because I can see TinyMCE is working fine without this

**Comment by amit4106udale** [comment]
@SharkyKZ  - Yes it happens with the TinyMCE also

**Comment by amit4106udale** [comment]
> Could you check if #27081 fixes the problem? And can you reproduce this issue with TinyMCE?

yes it happens with TinyMCE also

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed.

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc [@zero-24](https://github.com/zero-24)
