### ISSUE TITLE
[4.0][com_messages] TypeError: menuToggleIcon is null

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#27103]
### Steps to reproduce the issue
Go to Components > Messaging > Private Messages
Click My Settings button
Click Save & Close button
Settings not saved

See Console tab in Developer mode.
> TypeError: menuToggleIcon is null admin-menu.js:72:7

**Comment by infograf768** [comment]
Confirmed

**Comment by chmst** [comment]
Confirmed fromme too. (@Quy It is in users, not in components).

My2Cent: This is the only modal for settings. 
Why do we not make a a view for it, as we also have for accessibility settings? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27103">issues.joomla.org/tracker/joomla-cms/27103</a>.</sub>

**Comment by Quy** [comment]
See #28958
