### ISSUE TITLE
MooTools JS Error

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#27109]
### Steps to reproduce the issue
Load a site.

Array.forEach is deprecated; use Array.prototype.forEach instead
Array.slice is deprecated; use Array.prototype.slice instead

Coming from this file: /media/system/js/mootools-core.js?7715ba7deb75cd59a93ffca47316b2d0

**Comment by C-Lodder** [comment]
These aren't errors, they're just warnings. Then again if J3 is supported for a couple more years after J4 is "released", browsers may have already started removing support for `Array.forEach` and `Array.slice`, so a core hack may be required or a polyfill

**Comment by Chaosxmk** [comment]
Wouldn't the easier/better fix be to just update the package Mootools to 1.6.0? The base include version of Mootools is 1.4.5 (at least in Joomla 3.9.13). I don't think current versions of Mootools proc any deprecated warnings.

**Comment by mbabker** [comment]
MooTools 1.5 broke compatibility with 1.4 and earlier.  At this point it's better to just leave well enough alone than try to do a major JavaScript library/framework update, especially considering the framework's use should be disappearing quickly as it goes away in 4.0.

**Comment by HLeithner** [comment]
As stated by michael a b/c break would be worse, if the deprecation get removed finally before J3 is EOL we have to patch mootools.

I'm closing this for now. Thanks
