### ISSUE TITLE
[4.0] Wording "Accessibility settings"

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#27108]
### Steps to reproduce the issue
The backend lets define accessibility settings. I do not like this name. 
I would prefer "colour contrast settings" or "layout settings" or what is correct English. At the moment, the contrast layout does not look cool, but this is can be changed by some love for the css and wolud be a great enhancement.  
Then an inverse colour scheme has nothing to do with disabilties but with users preferences. Developers often prefer dark background in their IDE. Why not in Joomla?

**Comment by chmst** [comment]
Sorry for wrong category. It should be "Backend Template".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27108">issues.joomla.org/tracker/joomla-cms/27108</a>.</sub>

**Comment by brianteeman** [comment]
The inverse colour scheme is not the same as the new trendy dark themes it really is an accessibility setting because all it is doing is drastically increasing the contrast

**Comment by Quy** [comment]
OK to close? See #26772 for dark theme request.

**Comment by chmst** [comment]
ok :)
