### ISSUE TITLE
[4.0] A11y 'High Contrast' misleading

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#27112]
### Steps to reproduce the issue
Navigate User Menu -> Accessibility Settings -> Accessibility Settings

'High Contrast' field inverts colors instead of increasing color contrast.

https://github.com/joomla/joomla-cms/blob/bdf0c948e1b3a6f7cf58246f7de1ff90a22eb6ee/administrator/templates/atum/scss/blocks/_global.scss#L20-L22

### Expected result
Enabling 'High Contrast' increases contrast

### Actual result
Enabling 'High Contrast' inverts colors.

**Comment by SharkyKZ** [comment]
Duplicate issue #27108?

**Comment by ciar4n** [comment]
@SharkyKZ No. That is regarding the title of the containing tab.

**Comment by Quy** [comment]
See PR #27143<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27112">issues.joomla.org/tracker/joomla-cms/27112</a>.</sub>
