### ISSUE TITLE
[3.9.13] error_log - PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; plgSystemCanonical has a deprecated constructor in...

### ISSUE THREAD

**Issue by MixingOnBeat** [joomla/joomla-cms#27118]
### Steps to reproduce the issue
can be seen repetitively on my error_log within the Joomla directory on my site and also the administrator directory.

### Expected result
(should be no errors in the error_log)

### Actual result
[21-Nov-2019 14:39:00 UTC] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; plgSystemCanonical has a deprecated constructor in /public_html/plugins/system/canonical/canonical.php on line 17

### System information (as much as possible)
OS: Linux n
PHP: 7.2.24
MySQLi: 5.6.45
Time: 14:50
Caching: Disabled
Gzip: Enabled

### Additional comments
Just wanted to report this, not sure if its something urgent or not, but I'd like to learn if there is a way to fix that?

**Comment by brianteeman** [comment]
That us a notice from an extension that you have installed. You should contact the developer of that extension to see if they have an update etc.

**Comment by MixingOnBeat** [comment]
Thanks for the reply.  

Is there a way to learn what extension it could be? 

Or (since I don't install much extensions to Joomla) is there a quick way to list all the extensions that I've installed in the ACP?

**Comment by SharkyKZ** [comment]
Through Extension Manager. The extension is System - Canonical plugin (could be named differently). If update isn't available, you can solve this issue by changing `plgSystemCanonical` on line 17 in `plugins/system/canonical/canonical.php` to `__construct`. Though if the plugin is not maintained anymore, more issues could pop up in the future.

**Comment by SharkyKZ** [comment]
Closing as non-core issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27118">issues.joomla.org/tracker/joomla-cms/27118</a>.</sub>

**Comment by MixingOnBeat** [comment]
Okay, I found the plugin and it's called: System - Canonical -- but I don't recall if I was the one that installed that -- unless it came bundled with something else? 

Is this something that belongs to Joomla?  I wonder?  So if it is a Joomla plugin that may have been there since an older Joomla version, would it be best to remove it or disable it?  I mean who would I report this to?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27118">issues.joomla.org/tracker/joomla-cms/27118</a>.</sub>

**Comment by MixingOnBeat** [comment]
Oh, here is more info about it, next to that file I found a XML file with the developer's info:

`<?xml version="1.0" encoding="utf-8"?>
<extension version="3.1" type="plugin" group="system" method="upgrade">
	<name>System - Canonical</name>
	<author>StyleWare</author>
	<creationDate>2015-12-01</creationDate>
	<copyright>Copyright (C) 2010 - 2015 StyleWare.EU. All rights reserved.</copyright>
	<license>http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL</license>
	<authorEmail>paypal@styleware.eu</authorEmail>
	<authorUrl>www.styleware.eu</authorUrl>
	<version>3.1.2</version>
	<description>Content plugin that puts canonical tag to all the correct URL for content items.</description>
	<files>
		<filename plugin="canonical">canonical.php</filename>
	</files>
</extension>`
