### ISSUE TITLE
[4.0] A11y - High Constrast & Monochrome can't both be enabled

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#27119]
### Steps to reproduce the issue
Navigate User Menu -> Accessibility Settings -> Accessibility Settings

Not possible to enable both 'High Contrast' and 'Monochrome' at the same time.

Applying the same CSS property multiple times with different values does not apply both values. Cascades to the last property, in this case `a11y_contrast`..

https://github.com/joomla/joomla-cms/blob/bdf0c948e1b3a6f7cf58246f7de1ff90a22eb6ee/administrator/templates/atum/scss/blocks/_global.scss#L17-L22

**Comment by Quy** [comment]
See PR #27142<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27119">issues.joomla.org/tracker/joomla-cms/27119</a>.</sub>
