### ISSUE TITLE
[4.0] Invalid controller class

### ISSUE THREAD

**Issue by miljan-aleksic** [joomla/joomla-cms#27120]
I know this error has been reported in #22033 and in #21335 and is so easy to reproduce that makes me wonder why I am opening this ticket, but here we go.

### Steps to reproduce the issue

Install J4 Alpha 12 version and try to login accessing this url `administrator/index.php?controller=whatever`

### Expected result

I would expect to be redirected to the login view

### Actual result

It displays an error stating `An error has occurred. Invalid controller class: whatever`;

### System information

mysql: 5.7.26
php: 7.2.21
Joomla! 4.0.0-alpha12 Alpha [ Amani ] 17-October-2019 20:13 GMT

**Comment by SharkyKZ** [comment]
This should be fixed in current nightly with #26072.

**Comment by miljan-aleksic** [comment]
Thanks @SharkyKZ, will test it out as soon as it is released.

**Comment by Quy** [comment]
You can test it now with the nightly build: https://developer.joomla.org/nightly-builds.html
