### ISSUE TITLE
[4.0] Fields ordered horizontally instead of vertically

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#27136]
### Steps to reproduce the issue
Fields within a UI should always be ordered vertically. They should read like text within columns. Fields within Joomla 4 are ordered horizontally across columns....

![o4grXhrkUc](https://user-images.githubusercontent.com/2803503/69492603-ae4a1880-0e9c-11ea-97c3-6d3c9a18abb3.gif)

### Expected result
Fields ordered vertically within columns

### Actual result
Fields ordered horizontally across columns

**Comment by brianteeman** [comment]
see #25891

**Comment by ciar4n** [comment]
A duplicate so closing

**Comment by ciar4n** [comment]
At a second read, this is different to #25891 so re-opening 

#25891 is regarding the existence of columns. This issue is regarding the ordering of items within the columns.

**Comment by ciar4n** [comment]
PR created... #27141
