### ISSUE TITLE
[4.0] Sidebar menu icons not aligned

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#27135]
### Steps to reproduce the issue
Sidebar menu icons not aligning...

![image](https://user-images.githubusercontent.com/2803503/69492531-eb61db00-0e9b-11ea-87d9-240d3ca7e65e.png)

**Comment by infograf768** [comment]
.has-arrow could be slightly modified to `top: .6rem;` instead of .8rem
Can you test?
<img width="314" alt="Screen Shot 2019-11-24 at 10 29 27" src="https://user-images.githubusercontent.com/869724/69492624-582da300-0ea5-11ea-9e63-ebcab7cd0aa0.png">

**Comment by ciar4n** [comment]
`.6rem` looks fines.

**Comment by ciar4n** [comment]
Or not use absolute positioning, matching the other icon and not needing tweaks every time something changes.

**Comment by C-Lodder** [comment]
Ditch the top positioning for flexbox

**Comment by Quy** [comment]
Duplicate #25900<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27135">issues.joomla.org/tracker/joomla-cms/27135</a>.</sub>
