### ISSUE TITLE
[4.0] Redundant monochrome setting?

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#27144]
There are 2 monochrome settings:

* Administrator Template Styles > autum > Colour Settings > Set Colour to Monochrome
* User Menu > Accessibility Settings > Monochrome

Should there only be one? Remove from template settings?

**Comment by brianteeman** [comment]
Template settings would be for all users
Accessibility setting is per user

**Comment by Quy** [comment]
Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27144">issues.joomla.org/tracker/joomla-cms/27144</a>.</sub>
