### ISSUE TITLE
'Forgotten Password' process doesn't clear 'Password Reset Required' flag if set

### ISSUE THREAD

**Issue by jakeinnh** [joomla/joomla-cms#27147]
### Steps to reproduce the issue
1) Set the 'Require Password Reset' flag on a user using the Administrator interface
2) Assume the role of that user, but who's forgotten their password
3) Use the 'Forgotten Password' process flow
4) Upon completing the password reset, when the user logs in, they are immediately asked to reset their password again.

### Expected result
A 'Forgotten Password' reset should satisfy a pending 'Require Password Reset' and clear that flag if set.

### Actual result
The user must reset their password twice.

### System information (as much as possible)
Joomla! Version 3.9.13
Joomla! Platform Version 13.1.0 Stable
PHP 7.3.11
Apache 2.4.41
Server OS Ubuntu

### Additional comments
Requiring the user to reset the password immediately after they've just completed that process is superfluous and a less than ideal UX which could lead to confusion and additional calls for support to system Administrators.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/27413.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27147">issues.joomla.org/tracker/joomla-cms/27147</a>.</sub>
