### ISSUE TITLE
[4.0] [backend-template] Button hover cursors

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#27148]
### Steps to reproduce the issue

Go to `/administrator/index.php?option=com_media`

- Hover over `Upload`, `Create New Folder` and `Delete`. You'll notice the **default** cursor
- Hover over `Options` and `Help`. You'll notice the **pointer** cursor

![Screenshot_2019-11-25 Media - Joomla 4 - Administration](https://user-images.githubusercontent.com/2019801/69544445-a2875080-0f87-11ea-9c64-3e27c5864be6.png)

**Comment by brianteeman** [comment]
Appears to be unique to com_media

**Comment by brianteeman** [comment]
Its because they are not actually real buttons and the pointer is only added to type=button

**Comment by Quy** [comment]
Please test PR #27251<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27148">issues.joomla.org/tracker/joomla-cms/27148</a>.</sub>
