### ISSUE TITLE
Error: 1054 on Joomla site

### ISSUE THREAD

**Issue by owenstiffler** [joomla/joomla-cms#27150]
I upgraded my version of Joomla and now when I try to enter the backend of my site it says Error: 1054 and a blank page shows up. How do I fix this?

**Comment by Quy** [comment]
Please help at Joomla! Forum. https://forum.joomla.org/viewforum.php?f=710<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27150">issues.joomla.org/tracker/joomla-cms/27150</a>.</sub>
