### ISSUE TITLE
Select Alias or URL as Base Entry for Menu

### ISSUE THREAD

**Issue by unknown-sudo** [joomla/joomla-cms#27154]
### Steps to reproduce the issue
I want to use a menu alias or a menu item type URL or a menu heading as a base item in a menu module, but this option is disabled. The menu item contains submenu items that I want to repeat in the Footer menu without creating another Footer menu.

### Expected result
It should be possible to use all menu item types as basic entries. I see this as root entry for the displayed menu in the module.

### Actual result

<img width="277" alt="grafik" src="https://user-images.githubusercontent.com/55348115/69616026-3152a680-1036-11ea-9c63-84a39c86ab6f.png">

### System information (as much as possible)

Joomla 3.9.13

**Comment by SharkyKZ** [comment]
Duplicate issue https://github.com/joomla/joomla-cms/issues/20556. There's a pending PR https://github.com/joomla/joomla-cms/pull/16061 but it has conflicts.
