### ISSUE TITLE
Breadcrumbs Structured Data Contains Errors

### ISSUE THREAD

**Issue by Shankowsky** [joomla/joomla-cms#27151]
### Steps to reproduce the issue
Add a bread crumb to your website
Test coding best practises on Google Structured Data testing tools
https://search.google.com/structured-data/testing-tool
Errors Appear

### Expected result

No Errors

### Actual result

Errors

### System information (as much as possible)

Joomla 3.9.13

### Additional comments

SEO is important for websites and breadcrumbs add vital code that can set users apart in search results giving Joomla an edge on Wordpress and other CMS's.

**Comment by ReLater** [comment]
Maybe a known issue (but not solved)?
https://github.com/joomla/joomla-cms/pull/26268

**Comment by aint-broke** [comment]
The breadcrumb module in Joomla! 4.x Cassiopeia template also fails Google Structured Data testing.  The problem this time appears to be with the <ol> output.  It is includes a reference to 'itemscope itemtype="https://schema.org/BreadcrumbList"' that is not needed as the breadcrumb structure data is also output in the Jason script correctly.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27151">issues.joomla.org/tracker/joomla-cms/27151</a>.</sub>

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed.

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc [@zero-24](https://github.com/zero-24)
