### ISSUE TITLE
[4.0] Caching broken with modules

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#27163]
### Steps to reproduce the issue
Activate Progressive caching or Conservative caching in Global Configuration

Publish a whatever module that uses a Document addScript/addScriptDeclaration etc such as:

$doc->addScriptDeclaration('var myvar= 1;');

### Expected result
The module is cached without errors and everything works the same as when the cache is disabled

### Actual result
There are multiple places in the framework where data retrieved from the cache are array instead of expected strings, such as the ones in the screenshot and in the function 'mergeHeadData' line 321in /libraries/src/Document/HtmlDocument.php

### System information (as much as possible)
Joomla 4.0 Beta 1
![testerror](https://user-images.githubusercontent.com/17835460/69680926-bb3d5680-10ac-11ea-9371-0849495ed816.jpg)

### Additional comments
Additionally in the page HTML an array is included:

```
<script nonce="YzQ5NzBjNzI0MzVhMDRmZWZkZTExNjE2NzQ3MTY5Mjg1MmVlZjczOWFhZGY4YmY2M2I1N2M5MGM0M2E4NTEwMjg5ODFlMGUzZTNjZmMzMmZmZDQ1N2ZiZGU0OGZmNzQ0NWI2YWQ3NDc1NDdiOGFmODY4NTU0NTc5NDdjYWQ5NWI=">Array</script>
```
instead of the real string:
```
<script nonce="YzQ5NzBjNzI0MzVhMDRmZWZkZTExNjE2NzQ3MTY5Mjg1MmVlZjczOWFhZGY4YmY2M2I1N2M5MGM0M2E4NTEwMjg5ODFlMGUzZTNjZmMzMmZmZDQ1N2ZiZGU0OGZmNzQ0NWI2YWQ3NDc1NDdiOGFmODY4NTU0NTc5NDdjYWQ5NWI=">var myvar= 1;</script>
```

**Comment by SharkyKZ** [comment]
Please test PR #28990.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27163">issues.joomla.org/tracker/joomla-cms/27163</a>.</sub>
