### ISSUE TITLE
Smart Search not highlight accented words

### ISSUE THREAD

**Issue by aureliozenor** [joomla/joomla-cms#27168]
### Steps to reproduce the issue
Search any accented word in the Smart Search.

### Expected result
The searched term must be highlighted, receiving a span (class highlight)

### Actual result
![screen shot 2019-11-27 at 12 16 12](https://issues.joomla.org/uploads/1/0b9b0909ae7af87e0cb62866933b0c23.jpg)Smart Search never highlights accented words (or containing special characters like ç). In that case the search term is recognized, the search run correctly, but the span (with the class highlight) is not generated, so the term is not highlighted.

### Additional comments
The simple search is working fine, highlighting any term you search. So, the collation and language must be ok.

**Comment by ReLater** [comment]
Did you activate setting "Highlight Search Terms" in com_finder configuration?

Related:
https://github.com/joomla/joomla-cms/issues/19518
https://github.com/joomla/joomla-cms/pull/20019

**Comment by SharkyKZ** [comment]
Test PR https://github.com/joomla/joomla-cms/pull/25845 please.

**Comment by maxgdias** [comment]
> ### Steps to reproduce the issue
> Search any accented word in the Smart Search.
> 
> ### Expected result
> The searched term must be highlighted, receiving a span (class highlight)
> 
> ### Actual result
> ![screen shot 2019-11-27 at 12 16 12](https://camo.githubusercontent.com/359e894d44a66cab70127145de921a477c8c54ad/68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f30623962303930396165376166383765306362363238363639333362306332332e6a7067)Smart Search never highlights accented words (or containing special characters like ç). In that case the search term is recognized, the search run correctly, but the span (with the class highlight) is not generated, so the term is not highlighted.
> 
> ### Additional comments
> The simple search is working fine, highlighting any term you search. So, the collation and language must be ok.

Ola amigo.
Você conseguiu resolver isso? Estou com a mesma situação aqui. Tudo funciona, só não fica marcado qdo a palavra tem acento.

**Comment by infograf768** [comment]
It does work here fine.
<img width="737" alt="Screen Shot 2020-08-15 at 08 57 06" src="https://user-images.githubusercontent.com/869724/90307345-65783b00-ded5-11ea-9786-a9880503965c.png">
