### ISSUE TITLE
Not possible to install language pack

### ISSUE THREAD

**Issue by rbuelund** [joomla/joomla-cms#27169]
### Steps to reproduce the issue
Install fresh Joomla 4 nightly build. 
Download danish language package from crowdin. Zip the files in 40-dev.
Install as extension in Joomla 4 by using "Or browse for file"

### Expected result
Installation of language

### Actual result
Error![screen shot 2019-11-27 at 12 24 56](https://issues.joomla.org/uploads/1/c2702e4a153f6f91ed6aaa017167c352.png)

### System information (as much as possible)
Attached[systeminfo-2019-11-27T13_26_22+01_00.txt](https://issues.joomla.org/uploads/1/1eddccae311fc9004451ebd1632fa83f.txt)

**Comment by rbuelund** [comment]
Forgot to mark this as High priority !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27169">issues.joomla.org/tracker/joomla-cms/27169</a>.</sub>

**Comment by SharkyKZ** [comment]
The issue is with the Danish language pack. `type` attribute in `install.xml` is translated but it shouldn't be:

    <extension version="3.9" client="frontend" type="sprog" method="upgrade">

**Comment by rbuelund** [comment]
Thank you! Don't know how that happened :-)Problem fixed!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27169">issues.joomla.org/tracker/joomla-cms/27169</a>.</sub>
