### ISSUE TITLE
[4.0] Repeatable Field with showon

### ISSUE THREAD

**Issue by mwi812** [joomla/joomla-cms#27176]
### Steps to reproduce the issue
Add subfom field:
[items.txt](https://issues.joomla.org/uploads/1/bf6e00d1393d4cd735b887b0d355221f.txt)

### Expected result
Only fields with parent value in showon should display.
(After save module it works fine)

### Actual result
All fields appears by adding new items.

### System information (as much as possible)
PHP Version	7.3.11
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 4.0.0-alpha12 Alpha [ Amani ] 17-October-2019 20:13 GMT

**Comment by Quy** [comment]
Please test PR #29691
