### ISSUE TITLE
Editing from front end

### ISSUE THREAD

**Issue by ecotypes** [joomla/joomla-cms#27172]
### Steps to reproduce the issue
Using the provided blog example, tried to change the top image from the front end -- image module.  Could select a an image as a background image, but saving it resulted in the following

{"error":true,"code":0,"message":"Call to a member function getType() on null"}

That said, the editor seems to have no good way to insert or replace an image in the actual content.  The editor does not have an insert image option.  

### Actual result

{"error":true,"code":0,"message":"Call to a member function getType() on null"}
for inserting a background image,
For manually inserting html into the image module, that worked.  

### System information (as much as possible)

Joomla4, beta1 -- I loaded the blog example to have some content to manipulate

### Additional comments
I'm coming at this from the perspective of someone who is going to need to have very basic users editing content.  It is going to be imperative that basic users be able to manage images in their content.  I'm currently experimenting with alternatives to a CMS that is aging out that had effective front-end editing.  I think a field (such as the one to upload a background image) would be OK in this instance, but as a generality, images need to be uploadable using the editor.

**Comment by Quy** [comment]
Duplicate #25435. Thank you for the report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27172">issues.joomla.org/tracker/joomla-cms/27172</a>.</sub>
