### ISSUE TITLE
[4.0] error on view in option com_installer view=database

### ISSUE THREAD

**Issue by diddipoeler** [joomla/joomla-cms#27175]
### Steps to reproduce the issue
open the link:
http://joomla40beta.diddipoeler.de/administrator/index.php?option=com_installer&view=database

### Expected result
ERROR
Return value of Joomla\Component\Installer\Administrator\Helper\InstallerHelper::getInstallationXML() must be an instance of SimpleXMLElement, boolean returned

**Comment by wilsonge** [comment]
Hi,
What are you testing this on? It sounds like the issue that got patched by https://github.com/joomla/joomla-cms/pull/27020

**Comment by diddipoeler** [comment]
solved.
