### ISSUE TITLE
[4.0] Variable in string for 0 items

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#27173]
In https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/language/en-GB/com_privacy.ini#L37 the string contains a variable, even if the value is always zero.

### Expected result
Variable is superfluos

### Actual result
Variable is used

### Additional comments
There are other cases like this.
@brianteeman Issue for you as a reminder as requested in https://github.com/joomla/joomla-cms/pull/27170#discussion_r351535384

**Comment by alikon** [comment]
please test #27177<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27173">issues.joomla.org/tracker/joomla-cms/27173</a>.</sub>
