### ISSUE TITLE
Joomla 3.9.13: help in the background points to a site that was shutdown

### ISSUE THREAD

**Issue by gillesosx** [joomla/joomla-cms#27178]
### Steps to reproduce the issue
In the back-end, click on Help > Joomla Help, a page is displayed with categories. Click on one of these categories.

Or in any page that has a Help button, click on the button.

### Expected result

Categories: the specific help page should be displayed - can't tell if it will be in the same page or a new window.

Help button: a new window should open displaying help.

### Actual result

Categories. The help is not displayed.

Help button: a new window open with error 500

### System information (as much as possible)

Joomla 3.9.13 running in a VM machine on Debian 9.9 64bits only available internally.

Connection to the back-end on a portable running Windows 10 1903 in Edge (BETA) current.

### Additional comments

Please see https://forum.joomla.org/viewtopic.php?f=7&t=976092&p=3587618#p3587618 A user which connected to his site available on Internet had the same issue.

**Comment by mbabker** [comment]
Fixed, issue can be closed.
