### ISSUE TITLE
[4.0] Registration complete??

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27182]
joomla-cms/components/com_users/views/registration/tmpl/complete.php

As far as I can see this file has **never** been used but for 10 years we have been updating it

**Comment by mbabker** [comment]
Linked to [here](https://github.com/joomla/joomla-cms/blob/49e57851179aba7208ad9ca72cc8775daadc22a2/components/com_users/Controller/RegistrationController.php#L133-L142) and [here](https://github.com/joomla/joomla-cms/blob/49e57851179aba7208ad9ca72cc8775daadc22a2/components/com_users/Controller/RegistrationController.php#L235-L245)

**Comment by brianteeman** [comment]
thanks - i did search I promise ;)
