### ISSUE TITLE
[3.9.13] Search in User Activity not searching full text

### ISSUE THREAD

**Issue by RalfRoemling** [joomla/joomla-cms#27185]
### Steps to reproduce the issue
BE > User > User Activity > Search

### Expected result
Find activities via full-text search

### Actual result
When searching for a specific string like K2 or JCE nothing is returned even when the components were installed a moment ago and the installation is logged correctly.

**Comment by brianteeman** [comment]
Unless these  extensions provide their own action log plugins then this is to be expected

**Comment by SharkyKZ** [comment]
It's only for searching usernames. It's not made clear in J3. In J4 a tooltip is shown:

![Untitled](https://user-images.githubusercontent.com/7325021/69900953-098b7780-1383-11ea-8f94-d6989c00eb44.png)

**Comment by RalfRoemling** [comment]
@brianteeman: As I wrote... the entries I'm speaking off are already logged.

@SharkyKZ: It'd be a lot more useful if all fields were searchable. Is there a reason why the devs have decided against it but to implement a tooltip instead? Ridiculous imo :-) How can I convert this into a feature-wish?

**Comment by brianteeman** [comment]
By asking nicely

**Comment by RalfRoemling** [comment]
Absolutely! :-)
But where?

**Comment by mbabker** [comment]
Activities aren’t going to be easily searched.  You’ve got language strings in the database to allow messages to be translated and a JSON data structure which generally isn’t going to be good for user searches.  Rewriting this system to allow user searches is going to require a massive B/C break in the action log data structure and probably lose some capabilities along the way.

**Comment by RalfRoemling** [comment]
Thx for the explanation which clears things up.

For me though it does render the search more or less half useless. I need to search for a users actions far less often than for actions regarding a specific extension over time.
