### ISSUE TITLE
Nested fieldsets in xml

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27188]
If you go to any page that uses nested fieldsets such as the integrations tab of article options you will see that none of the fieldsets inside the integration fieldset are being loaded

**Comment by brianteeman** [comment]
This is caused by #26890 by @C-Lodder - we missed it in testing

### Before that PR
![image](https://user-images.githubusercontent.com/1296369/72211043-31124b80-34bc-11ea-86a9-672dce975e65.png)

### Now with that PR
![image](https://user-images.githubusercontent.com/1296369/72211050-3ff8fe00-34bc-11ea-9989-62f4b731f379.png)

**Comment by brianteeman** [comment]
I will fix this tomorrow

**Comment by brianteeman** [comment]
@C-Lodder I would really appreciate you taking a look at this please

**Comment by C-Lodder** [comment]
Will take a look at this today

**Comment by C-Lodder** [comment]
@brianteeman PR: https://github.com/joomla/joomla-cms/pull/27507
