### ISSUE TITLE
Add positions to Joomla 4 Cassiopeia Default template.

### ISSUE THREAD

**Issue by AshrafTayab** [joomla/joomla-cms#27193]
### What needs to be fixed
if you don't mind to add New other position to Joomla 4 Cassiopeia Default template.
Top position in the top right corner for user menu, Login, Logout, User Profile ....et
Bottom position in the left bottom corner or in the middle for Data Protection and Legal Issues menu, Terms Of Use, Privacy Policy, End User License Agreement ... et ( NOT IN THE FOOTER COPYRIGHT )

**Comment by alikon** [comment]
are you talking about the test sample data ?

**Comment by AshrafTayab** [comment]
No, I am using joomla 4.0.0-alpha12 without install any data, I am using my data.

**Comment by alikon** [comment]
maybe i don't understand your request

**Comment by AshrafTayab** [comment]
In joomla-alpha12 Cassiopeia Default template there are no Top Position and Bottom position.
My request is : 
1 : Add Top Position to Cassiopeia Default template.
2 : Add Bottom position to Cassiopeia Default template.

**Comment by richard67** [comment]
Could you provide a screenshot on which you mark where you expect these positions to be? Maybe there are already such positions but with a different name.

**Comment by AshrafTayab** [comment]
![User Menu](https://user-images.githubusercontent.com/26835611/70246672-bd747480-1780-11ea-97f2-29edb6281b30.jpg)
![L Menu](https://user-images.githubusercontent.com/26835611/70246730-d2e99e80-1780-11ea-8b88-1c1ae8950a7d.jpg)

**Comment by infograf768** [comment]
If I do not mistake, we have these

Top right

<img width="1228" alt="Screen Shot 2019-12-06 at 08 34 17" src="https://user-images.githubusercontent.com/869724/70304930-5055f300-1803-11ea-9d88-183e99bbea14.png">

Bottom: maybe possible to add a position called footer-left

<img width="1439" alt="Screen Shot 2019-12-06 at 08 34 33" src="https://user-images.githubusercontent.com/869724/70304941-58159780-1803-11ea-85c3-b7af32c12a52.png">

**Comment by AshrafTayab** [comment]
First : 
This is Main Menu position and search position, Ok
I am talking about another new potions add up of Main menu position and search position.
Add new potions to Cassiopeia Default template for user menu (Login, Logout, User Profile ....et)

Second : 
In the bottom of Cassiopeia Default template we have (Position: bottom-b) and (Position: footer).
I am saying to add another new potions after (Position: bottom-b) and before (Position: footer) it is between to used for (Terms Of Use, Privacy Policy ...et)

**Comment by AshrafTayab** [comment]
![Joomla 4 Postion](https://user-images.githubusercontent.com/26835611/70392062-5f47cb80-19e4-11ea-96b3-be932ba0930e.jpg)

**Comment by infograf768** [comment]
I can easily add a bottom-c position as proposed above, but I would not know how to add a header position on top of those existing.

**Comment by ghost** [comment]
@infograf768 please add a bottom-c position as proposed above,

@richard67 Do you know how to add a header position on top of those existing?

**Comment by richard67** [comment]
> @richard67 Do you know how to add a header position on top of those existing?

No.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #31731 . Thanks in advance.
