### ISSUE TITLE
Fatal error on phpversioncheck if no supported PHP versions when last PHP version on array don´t have support

### ISSUE THREAD

**Issue by irbian** [joomla/joomla-cms#27195]
### Steps to reproduce the issue

I had this error:

 PHP Fatal error:  Call to a member function format() on null in /www/joomla/sede/plugins/quickicon/phpversioncheck/phpversioncheck.php on line 174

I use Joomla 3.8.1 on PHP 5.6

The problem is a simple null pointer. The array of supported PHP versions is fixed. Yesterday 2019/12/1, the last PHP version on the array, lost support https://github.com/joomla/joomla-cms/blob/3.8.1/plugins/quickicon/phpversioncheck/phpversioncheck.php#L130

Because of this, recommendedVersionEndOfSupport is null, and can´t be called format on

I understand that Joomla 3.8.1 is not the last version, and PHP 5.6 is unsupported, but this is beyond the point. I understand that a updated environment and version is the way to go, but this is a bug that breaks access from one day to the other without user intervention.

### Expected result

Maybe show something like "Update Joomla to show the recommended PHP version"

### Actual result

White page on the administrator page

### System information (as much as possible)

PHP 5.6
Joomal 3.8.1

**Comment by ReLater** [comment]
I confirm that the fatal error also occurs in current J3.9.13

#### Test
- Set page PHP version to 7.0
- Remove these lines from plugin
https://github.com/joomla/joomla-cms/blob/3.9.13/plugins/quickicon/phpversioncheck/phpversioncheck.php#L132-L139
- Reload control pamel => "0 Call to a member function format() on null "

**Comment by SharkyKZ** [comment]
Test PR #27197 please.
