### ISSUE TITLE
[4.0] Crop and Resize images

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27192]
In the media manager you can crop and resize images. The selector for this is restrained to the actual image. you can not select the container (the checked area)
![image](https://user-images.githubusercontent.com/1296369/69920093-bc3f0100-147b-11ea-9d79-34e84e91d260.png)

If you try to use the crop and resize functionality in the template manager the restraints do not apply and you can select anything
![image](https://user-images.githubusercontent.com/1296369/69920115-e8f31880-147b-11ea-9b25-8d542268bf4f.png)

This will result in an image as below
![image](https://user-images.githubusercontent.com/1296369/69920123-ff996f80-147b-11ea-9ec8-1c9ce842a7ee.png)

**Comment by dgrammatiko** [comment]
@brianteeman I don't think that we're doing anything different than the demo of the used script: https://fengyuanchen.github.io/cropperjs/

To patch this someone needs to dig into the options of that script and if the functionality is not available then restrict the area by some own code (I think we can interfere in the process)

**Comment by brianteeman** [comment]
@dgrammatiko its actually simpler than that. 
The settings for cropperjs are in the media-action plugin and com_media uses the media-action plugin

However com_templates is simply loading the cropperjs files directly and not using the plugin :(
So presumably instead of doing that com_template should be doing
`		PluginHelper::importPlugin('media-action');
`

Someone better than me can dig in and resolve that. I've done the hard detective work

**Comment by dgrammatiko** [comment]
I had to dig in the history and what I found is that the functionality is the same as what exists in the J3.x. I did the ES6 renaming/changes and Charlie did the initial clean up of the file. The functionality was never questioned by either of us, I guess because we didn't encounter this case (?) https://github.com/joomla/joomla-cms/pull/15449/files#diff-3e83167bf7041bbf0b6294e5e132e9fdR106-R125

Anyways changing the initialisation options for the cropperjs should be sufficient to also cover this case

**Comment by brianteeman** [comment]
> Anyways changing the initialisation options for the cropperjs should be sufficient to also cover this case

Are you able to do that please

**Comment by dgrammatiko** [comment]
Ok I’ll try to do a PR this weekend

**Comment by brianteeman** [comment]
Thank you

**Comment by alikon** [comment]
please test #27255<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27192">issues.joomla.org/tracker/joomla-cms/27192</a>.</sub>
