### ISSUE TITLE
[4.0] While creating Article if a script payload is inserted via Burp-suite it's getting executing at user's end.

### ISSUE THREAD

**Issue by Kaustubharas** [joomla/joomla-cms#27196]
### Steps to reproduce the issue

1. Login to Joomla admin.
2. Go to Articles and click on New to create a new Article.
3. Enter Title 
4. In Article text Enter some text e.g. "This is a test article"
5. Before saving start burp suite and then hit on save. The request will be captured by burp suite.
6. Go to Burp suite and go to "Params" tab and change the article text from "This is a test article" to "\<svg onload=alert(1)\>" and click on "Forward" till the article gets saved.
7. Now switch off the intercept on Burp suite and go to the joomla frontend and login with a user.
8. And click on the articles menu to view the article.
9. Once user clicks on article and the script gets executed.

### Expected result

The article shouldn't get saved with the script tag.

### Actual result

The article getting saved with the script tag and the script is getting executed on user side.

### System information (as much as possible)

PHP 7.2
Joomla 4.0.0-alpha12-dev

**Comment by SharkyKZ** [comment]
As far as I can tell, this only bypasses editor's client-side validation. If I had to guess you did this as a Super User and Super Users are actually allowed to insert Javascript in editor text by default (regarding server-side filtering).

I also tried this as Editor and it saved only `<svg />`. So server-side filtering seems to work fine.

**Comment by SharkyKZ** [comment]
Let's ask the experts @zero-24 @SniperSister.

**Comment by zero-24** [comment]
Exactly what @SharkyKZ said by default this is expected behavior for Super Users that no filtering is applied. You can review and change the setting in the "Text Filter" Options at the Global Configuration.

**Comment by alikon** [comment]
expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27196">issues.joomla.org/tracker/joomla-cms/27196</a>.</sub>
