### ISSUE TITLE
[4.0] Untranslated JLIB_INSTALLER_ABORT_INSTALL_ABORTED

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#27201]
Maybe related to #26299.

`JLIB_INSTALLER_ABORT_INSTALL_ABORTED` is in `\language\en-GB\lib_joomla.ini`
Copying it to `\administrator\language\en-GB\lib_joomla.ini` fixes the translation, but is this the correct fix?

### Steps to reproduce the issue
Install PatchTester.
Delete configuration.php
Reinstall.
Install PatchTester.

### Actual result
![JLIB_INSTALLER_ABORT_INSTALL_ABORTED](https://user-images.githubusercontent.com/368084/70013925-10a2b900-152e-11ea-9140-2b1f7f4d248b.jpg)

**Comment by infograf768** [comment]
Both `lib_joomla.ini` files should be exactly the same, so the string should also be added in admin for sure. At the same time would be good to compare these 2 files for other similar issues.

If the string can't be found in admin, it is fetched form frontend (this was done in the past to let TTs make "site-only packs").

The code is present in the `loadLibraryLanguage()` method in SiteApplication but not in CMSApplication. I suggest to also add the same conditional there but reversing the order of priorities (admin first).

**Comment by Quy** [comment]
Would you consider doing a PR for it since you have better understanding of it than I do? Thanks.

**Comment by infograf768** [comment]
Ok, will do asap.

**Comment by infograf768** [comment]
To test I may need to obtain the same error you got as I first want to modify CMSApplication.
What exactly did you try to install. I tried with both patchtester 4.0 and 3.0 and did not get any error.

**Comment by Quy** [comment]
Install PatchTester 3.0.
Delete configuration.php.
Reinstall Joomla.
Reinstall PatchTester 3.0.
Got the error/warning.

**Comment by infograf768** [comment]
Ok. Got the error.
In fact, it is just missing in backend. No need to load site one.
If a language has no admin lib_joomla.ini, it will use the en-GB one.
But both lib are not in sync and alpha order is not respected.
Making patch for that.

**Comment by infograf768** [comment]
Please test
https://github.com/joomla/joomla-cms/pull/27204
