### ISSUE TITLE
Mysql 8 joomla debug

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27217]
This is for joomla 3
### Steps to reproduce the issue
On a server with mysql 8 enable debug
Check the debug queries output

### Expected result
No errors

### Actual result
Every query says

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ....

Everything is working correctly otherwise

### System information (as much as possible)
 OS Windows
 PHP 7.4.0
 MySQLi 8.0.18

### Additional comments
Maybe its my config, maybe its the debug plugin

**Comment by alikon** [comment]
most the  2nd
please test #27218
