### ISSUE TITLE
Save message when saving an article

### ISSUE THREAD

**Issue by Luchen6** [joomla/joomla-cms#27211]
### Steps to reproduce the issue
Admin; go to existing article and open to edit it
Press save (save&close) button
Article will be saved and modal message appears.
Closing this modal box will clear the modal box but box still is visible

### Expected result
Box should disappear

**Comment by brianteeman** [comment]
System information (as much as possible)

**Comment by Luchen6** [comment]
Two screenshots. Just after saving an article 
![ArticleSaved](https://user-images.githubusercontent.com/6205641/70227569-1b8a6300-1753-11ea-850e-55be2656c3ff.JPG)
and after closing the modal box
![ModalBoxClosed](https://user-images.githubusercontent.com/6205641/70227590-2513cb00-1753-11ea-8f12-5ab7e8d94a83.JPG)

**Comment by Quy** [comment]
Duplicate #25850
