### ISSUE TITLE
Status coloring 

### ISSUE THREAD

**Issue by Luchen6** [joomla/joomla-cms#27210]
### Steps to reproduce the issue
Create new article and check whether status is 'Unpublished'

### Expected result
Color of status should be red; just like it is with article category

### Actual result
No color variation

### Additional comments
Dropdown list is different from dropdown list for article categories

**Comment by brianteeman** [comment]
For clarity could you please post a screenshot

**Comment by Luchen6** [comment]
Two screenshots; one for the status by articles (Articles.JPG) and one for the status by article category (ArticleCategory.JPG)
![Article](https://user-images.githubusercontent.com/6205641/70227364-c51d2480-1752-11ea-89fd-6ee404db19c2.JPG)
![ArticleCategory](https://user-images.githubusercontent.com/6205641/70227375-c77f7e80-1752-11ea-807f-753f3cd052b7.JPG)

**Comment by Quy** [comment]
Duplicate #23781
