### ISSUE TITLE
array_key_exists() with objects is deprecated in php 7.4

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27214]
https://wiki.php.net/rfc/deprecations_php_7_4#array_key_exists_with_objects

https://anastasionico.uk/blog/php-7-4-deprecations#array_key_exists

There are 300+ instances in J4

**Comment by SharkyKZ** [comment]
Edited title to not be misleading.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27214">issues.joomla.org/tracker/joomla-cms/27214</a>.</sub>

**Comment by mbabker** [comment]
`array_key_exists()` is NOT deprecated, the deprecation is using the function with objects (i.e. something like `Joomla\Registry\Registry` which implements `ArrayAccess` meaning you can work with the registry object as an array).

```php
$thing = new Joomla\Registry\Registry;
$thing['foo'] = true;
$thing['bar'] = true;

array_key_exists('foo', $thing); // emits deprecation because an object is being checked

$otherThing = array();
$otherThing['foo'] = true;
$otherThing['bar'] = true;

array_key_exists('foo', $otherThing); // this is OK
```

**Comment by brianteeman** [comment]
There are instances of using  the function with objects

**Comment by SharkyKZ** [comment]
It's possible. Could you point to some instances?

**Comment by brianteeman** [comment]
Closing for now - will keep an eye on my error logs

**Comment by brianteeman** [comment]
If you compare two versions of an article you will get the error
`Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in \joomla-cms\administrator\components\com_contenthistory\Model\CompareModel.php on line 104`

**Comment by alikon** [comment]
please test #27493 
closing this issue in the hope that all 7.4 compatibilty isuues will have a proper issue

**Comment by laoneo** [comment]
Please test #29430 as it fixes the same issue on J3 as well.

**Comment by rahulfromhighwire** [comment]
I have just changed

return array_key_exists($index, $this);
to

return array_key_exists($index, (array) $this);
It is working. I just type cast in Array datatype
