### ISSUE TITLE
Issue with privacy issue in iframe [4]

### ISSUE THREAD

**Issue by odmv18528** [joomla/joomla-cms#27229]
357/5000
When clicking in the front end contact form on the link, with which the privacy policy is to be called, an empty modal window (iframe) appears.

Through a test I have removed in the consentbox.php in the directory plugins / content / confirmconsent / fields the addition "& tmpl = component".

This will also show the content of the linked page.

xampp 3.2.4 PHP 7.3 Joomla 4 beta1

**Comment by jwaisner** [comment]
I cannot reproduce this. Can you provide steps to replicate what you are reporting?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27229">issues.joomla.org/tracker/joomla-cms/27229</a>.</sub>

**Comment by odmv18528** [comment]
Hello @jwaisner,

the error no longer occurred in the latest version. The contact form now works and also shows the selected page in the modal window.
