### ISSUE TITLE
Page Break pagination links lack style

### ISSUE THREAD

**Issue by Harmageddon** [joomla/joomla-cms#27222]
### Steps to reproduce the issue
1. Create a new article that contains page breaks.
2. Make sure that the plugin "Content - Page Break" is enabled and presentation style is set to "Pages".
3. Use the "Protostar" template (or Cassiopeia in 4.0).
4. Navigate to the article in frontend and pay attention to the page navigation links.

### Expected result
The pagination links (Previous, Next) should be styled consistently with other similar links (like the page navigation links). The latter ones have tooltips and icon arrows.

#### Joomla! 3.9.14-dev
The pagination links of Page Break have no tooltips and the arrows are plain ">>" or "<<". 

![joomla-pagebreak-v3](https://user-images.githubusercontent.com/1410135/70377144-4cb09200-1911-11ea-8b36-4ccb5a2f9f05.png)

#### Joomla! 4.0-dev
In v4 it's even worse. The links here are completely unstyled, just a normal bullet list.

![joomla-pagebreak-v4](https://user-images.githubusercontent.com/1410135/70377163-71a50500-1911-11ea-9886-3a56e1c6e641.png)

### System information (as much as possible)
? | ?
------------ | -------------
Database Version | 10.3.13-MariaDB-1:10.3.13+maria~bionic
PHP Version | 7.2.17
Web Server  | nginx/1.14.2
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 4.0.0-beta1-dev Development [ Amani ] 17-October-2019 20:21 GMT
User Agent | Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0

### Additional comments

Originally reported by user Gerry77 at forum.joomla.de: [Thread](https://forum.joomla.de/thread/10699-schaltflächen-für-vorwärts-und-zurück-werden-unterschiedlich-dargestellt)

**Comment by jwaisner** [comment]
Confirmed in staging branch that issue exists.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27222">issues.joomla.org/tracker/joomla-cms/27222</a>.</sub>

**Comment by HLeithner** [comment]
It would be great If one of you can provide a pr for j3.

**Comment by ReLater** [comment]
If nobody is already  busy with a pr I'll have a look and try to provide one for Joomla 3. Not too easy to fix all mentioned issues with the current code (Joomla 1.5 I presume).

Please ping me if somebody is already working on it.

**Comment by Quy** [comment]
Please test PR #27398
