### ISSUE TITLE
[3.9] com_media. Why are video filenames truncated?

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#27221]
### Steps to reproduce the issue
- Upload a mp4 video to your /images/ folder. Filename longer than 10 characters
- Go to Media Manager > Detail View.
- Video filename is truncated while other media filenames are not truncated.
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_media/views/medialist/tmpl/details_videos.php#L45
- Any reason for this behavior?

![07-12-_2019_13-20-41](https://user-images.githubusercontent.com/20780646/70374600-95a61d80-18f4-11ea-81ae-6717bd7c2742.jpg)

**Comment by HLeithner** [comment]
Seams like unexpected behavior, at least I didn't found a good reason. Also in the first column there should be a video icon which seams to not exists... could you create a PR for this?

**Comment by ReLater** [comment]
> could you create a PR for this?

Yes. 

> video icon which seams to not exists

<strike>The paths to the video icon pngs is wrong

```
    [icon_32] => media/mime-icon-32/mp4.png
    [icon_16] => media/mime-icon-16/mp4.png
```
</strike>

**Comment by ReLater** [comment]
Please test https://github.com/joomla/joomla-cms/pull/27230
