### ISSUE TITLE
[4.0- Title Edited] Crash installing node-sass 4.13 on node 13.2

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#27227]
[Edit]
After inquiring about this on github sass/node-sass project, I have been told that the binary that is downloaded might not work on macOS Catalina.
See:

> It's possible the Darwin binaries built on Mojave aren't compatibile with Catalina

https://github.com/sass/node-sass/issues/2807

macOS Catalina
npm 
6.13.1
node 
v13.2.0
Composer version 1.9.1 
git version 2.24.0

I got a node-sass package not found on my Terminal:
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/darwin-x64-79_binding.node"
Reasons are:
- darwin-x64-79_binding.node is not listed in v4.12
- message by xzyfer where it is stated that:
"Only 4.13.0 will work with node 13."
In:
Having an issue with node-sass v4.13.0 with node v13.3.0, create_string.cpp:17:25: error... · Issue #2799 · sass/node-sass
https://github.com/sass/node-sass/issues/2799

**Comment by brianteeman** [comment]
can you check and see if this issue is in the media manager by going to administrator/components/com_media and running composer install from there

**Comment by ghazal** [comment]
I have no pb to install composer. 
I use npm ci to install node-modules, which is quite strict.
Check line 5466 in package-lock.json

>       "version": "4.12.0",
>       "resolved": "https://registry.npmjs.org/node-sass/-/node-sass-4.12.0.tgz",

Version and integrity -> sha512-xxx should be updated.
PS: my node version is 13.2.0

**Comment by brianteeman** [comment]
can you please do what i asked

**Comment by mbabker** [comment]
`npm update` needs to be run on both the main repo and the media manager it sounds like.

**Comment by C-Lodder** [comment]
Now that the media manager is now back as part of core, it would be wise to move the build scripts to the core, rather than have them separated.

**Comment by dgrammatiko** [comment]
> it would be wise to move the build scripts to the core

Not to mention that the build tools for media manager are deprecated (Webpack 3, not using cue cli, etc)

If the production team will accept such thing Im willing to bring Rollup instead of Webpack and also use the vue-cli (as this is the norm these days) in the main tools

**Comment by ghazal** [comment]
See
 https://github.com/sass/node-sass/issues/2807
and
https://github.com/nodejs/node/issues/30581

Actually, it was an issue  with node 13.2
So comment closed.
