### ISSUE TITLE
 [4.0][com_associations] Undefined index: link

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#27236]
### Steps to reproduce the issue
Install Multilingual Sample Data (English, French, German, Persian)
Under System > Content Languages, delete Persian.
Under Components > Multilingual Associations, select Articles and English (en-GB).
Under Associations and Not Associated columns, see error.

### Actual result
> Notice: Undefined index: link in \layouts\joomla\content\associations.php on line 18

**Comment by infograf768** [comment]
Confirmed.

**Comment by infograf768** [comment]
It also breaks for example the Associations tab content when editing an article;
I.e. It displays the current language (In the case above Persian (fa-IR) in the possible associations to create.)

**Comment by infograf768** [comment]
This happens when the article has already a fa-IR associated item before the Content Language is trashed or deleted.

**Comment by Quy** [comment]
Elsewhere such as Content>Articles and Content>Categories, you don't get this notice under the `Association` column. Should the badge for the trashed/deleted Content Language be displayed?

**Comment by infograf768** [comment]
In the managers, we use `HTMLHelper()` and the service files.
In com_associations we use `getAssociationHtmlList()`

These are very different methods. 
I don't see where we would have a Trash for a Content Language deleted (Except in the multilingual status obviously where it already shows)

I guess the only solution would be to get an error message and prevent showing the items concerned in the associations columns, whether in com_associations or other components.

This implies changes in the layout and the `xxxService.php` files.
Concerning other `xxxService.php` than com_associations helper, I can get this: fa-IR associated items don't show in column and display a Warning (here an example for articles where we do have a fa-IR article associated to the en-GB one.)

<img width="1055" alt="Screen Shot 2019-12-22 at 08 19 40" src="https://user-images.githubusercontent.com/869724/71318670-37e90800-2494-11ea-9510-0e70142e74b7.png">

Looking how I can do for com_associations.

**Comment by infograf768** [comment]
For com_associations, we would get
<img width="1276" alt="Screen Shot 2019-12-22 at 09 13 46" src="https://user-images.githubusercontent.com/869724/71319208-7635f580-249b-11ea-98e9-de36964da01f.png">

**Comment by infograf768** [comment]
Shall I make the patch?

**Comment by Quy** [comment]
Yes please.

**Comment by Fedik** [comment]
I think it not only about deletion.

I have this issue also when I add a content language manually (without install language), without deletion anything.

so it available at index.php?option=com_languages&view=languages
but not exists at index.php?option=com_languages&view=installed

It sounds like com_associations looking on installed languages only or?

**Comment by infograf768** [comment]
Hmm, normally (at least this was the concept when we started multilang) one is supposed to be able to work when a language is not yet installed by just creating the Content Language.
Will look at this.

**Comment by infograf768** [comment]
@fedik
Thanks for finding this.
When we only have a content language and no corresponding installed language:

1. We can tag an item to this content language. That part works fine.
2. The problem exists indeed in com_associations: the target choice will not propose that Content Language language and it is not displayed in the `No associations` column
3. The language is not proposed in the Associations Tab when editing an item

I found why we have this issue:
`$checkinstalled` is set to true per default in 
https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Language/LanguageHelper.php#L365 
therefore it will never display the Content Language if it does not have also an installed language...

This has consequences all over multilang joomla... 

If I modify it to `false` in the associations helper, it works fine for the manager at least (as Target is still missing the language in the side by side page, which I also can solve by adding a `false` in `ItemlanguageField`).
Same if I use false in the articleModel.

I propose to try to deal with this in another PR as I wonder if we should set the default to `false`.

As it has no impact on this original issue, will make the PR for that.


**Note**: I also found a side problem concerning this issue (i.e. when a Content Language —with its Installed language OK— is trashed/deleted). When editing an item that was tagged to the trashed content language, the same language is still proposed in the Associations Tab. But I guess this would be taken care of with the new Warning.

**Comment by infograf768** [comment]
Hmm, concerning `$checkinstalled`, looks like we have the same issue in 3.x
I have been trying to find out when that was implemented to find the reason for it but I fail because history on github stops when the helper is moved to `src` in 3.8.0

If I remember well @andrepereiradasilva was the one who originally created that method, but not sure.

**Comment by infograf768** [comment]
The PR was https://github.com/joomla/joomla-cms/pull/12344 (tks @Bakual for helping me find it.)
I must say that I never tested the case at the time...
As stated above, will try to look at it later.

**Comment by Quy** [comment]
See PR #27340 & #27341
