### ISSUE TITLE
[4.0] API login

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#27243]
### Steps to reproduce the issue

Create a user with:
Username: `api`
Password: `Aa1Bb2Cc3Dd4Ee5!`

Do a API call: GET {{base_path}}/api/index.php/v1/content/article

### Expected result

The List of Articles

### Actual result

```
{
    "errors": [
        {
            "title": "Forbidden"
        }
    ]
}
```

### System information (as much as possible)

Tested with Joomla_4.0.0-beta1-dev-Development-Full_Package

### Additional comments

If you use a password like "api123" it works correctly

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/27245.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27243">issues.joomla.org/tracker/joomla-cms/27243</a>.</sub>
