### ISSUE TITLE
[‎4.0.0-alpha11] Language constants are shown during installation process

### ISSUE THREAD

**Issue by niteshkesarkar** [joomla/joomla-cms#27246]
### Steps to reproduce the issue
1. Download the Joomla 4.0.0-alpha11 version.
2. Successfully install Joomla till you get Congratulations! Your Joomla site is ready.
3. Now click on customize installation button
4. Now click on Skip button
5. Check the screen language constants are shown for 
   - `INSTL_SITE_INSTALL_SAMPLE`
   - `INSTL_SITE_INSTALL_SAMPLE_LABEL`
   - `INSTL_SITE_INSTALL_SAMPLE_DESC`
6. Click on `INSTL_SITE_INSTALL_SAMPLE` button
7. You will get the error saying
   - `JLIB_APPLICATION_ERROR_VIEW_NOT_FOUND`

### Expected result
1. Proper language translations should be displayed instead of language constants.

### Actual result
1. Language constants are shown 

### System information (as much as possible)
**OS**: `Ubuntu 18.04.3 LTS`
**PHP**: `7.2`
**MySQL**: `14.14 Distrib 5.7.28, for Linux (x86_64) using  EditLine wrapper`

**Comment by alikon** [comment]
the alpha 11 is quite old please test with the nightly builds https://developer.joomla.org/nightly-builds.html

**Comment by Quy** [comment]
Duplicate #26412<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27246">issues.joomla.org/tracker/joomla-cms/27246</a>.</sub>
