### ISSUE TITLE
[4.0] Associations UI

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27256]
### Steps to reproduce the issue
On a multilingual site create Contact-Categories for each language and associate them

At first I failed to do this because I clicked on the associations button in the toolbar instead of the associations tab on the category.

Its very confusing to have two things with the same label that do different things

![image](https://user-images.githubusercontent.com/1296369/70805019-de0b8280-1daf-11ea-82e7-6bebc57e7103.png)

**Comment by infograf768** [comment]
Same for all core components, for categories as well as items, since 3.9.0. https://github.com/joomla/joomla-cms/pull/21022

FYI info, you already commented on that and the string was modified:

<img width="768" alt="Screen Shot 2019-12-14 at 08 25 00" src="https://user-images.githubusercontent.com/869724/70845130-46f40880-1e4b-11ea-846e-5d7b28941c80.png">

**Comment by brianteeman** [comment]
So I was wrong

**Comment by infograf768** [comment]
The issue is that using `Edit/Create Associations` in the toolbar would make it extremely long already in English, not speaking for some other languages.
Any suggestion?

**Comment by Fedik** [comment]
what if name the toolbar button "Translate", or "Translations" or  "Go Translate" or similar?
that what it actually doing, opens a window for edit the article translations

"Associations" are confusing me in general :)

**Comment by infograf768** [comment]
It may not be a translation at all. This why we used Associations from the beginning of the feature implementation.

**Comment by infograf768** [comment]
Maybe "Associations Component" ?

**Comment by brianteeman** [comment]
Could you please using one sentence for each explain the purpose/role of the button and the tab

**Comment by infograf768** [comment]
Tab:
Edit/Create Associations for this item right here in this Edit form.
Button
Edit/Create Associations through the com_associations component, loading the edited item as Reference in a side by side UI.

**Comment by brianteeman** [comment]
All I can think of right now is to revert my previous suggestion and go back to your original name for the toolbar button
