### ISSUE TITLE
default object from empty value articles list [php 7.4]

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27259]
### Steps to reproduce the issue
Create a menu for of type articles list with enough articles for there to be pagination

### Expected result
Use the pagination without error

### 4.0
Warning: Creating default object from empty value in C:\htdocs\joomla-cms\components\com_content\tmpl\category\default_articles.php on line 24

### Staging - protostar
Warning: Creating default object from empty value in C:\htdocs\cms\components\com_content\views\category\tmpl\default_articles.php on line 18

### Staging - beez
Warning: Creating default object from empty value in C:\htdocs\cms\templates\beez3\html\com_content\category\default_articles.php on line 17

### System information (as much as possible)
**php 7.4**

### Additional comments
I only checked article lists - this may be present for other lists

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/27273.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27259">issues.joomla.org/tracker/joomla-cms/27259</a>.</sub>
