### ISSUE TITLE
[4.0] menu item select array offset [php 7.4]

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27257]
### Steps to reproduce the issue
Create a new menu item 

### Expected result
select a menu type with no problems

### Actual result
Notice: Trying to access array offset on value of type bool in C:\htdocs\joomla-cms\libraries\cms\html\bootstrap.php on line 440

![image](https://user-images.githubusercontent.com/1296369/70805690-75bda080-1db1-11ea-8163-92f5e61d06b8.png)

### System information (as much as possible)
**php 7.4**

**Comment by infograf768** [comment]
No problem here on php 7.3.1

**Comment by brianteeman** [comment]
It is b/c break in PHP 7.4

**Comment by brianteeman** [comment]
The same error when editing a module on the frontend

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/27274.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27257">issues.joomla.org/tracker/joomla-cms/27257</a>.</sub>

**Comment by vedmant** [comment]
I have the same issue, could this PR be published?
