### ISSUE TITLE
[4.0] warning language has been changed

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27258]
### Steps to reproduce the issue
On a multilingual site create anything and change the language from all to one of the installed languages

![image](https://user-images.githubusercontent.com/1296369/70806076-70ad2100-1db2-11ea-841d-eca4d17fb901.png)

1. On a new item this message is not relevant
2. Is it really correct to display this every single time? It's an incredibly bad user experience to see this message all the time

**Comment by infograf768** [comment]
It is correct to display the message when appropriate, but this is supposed to happen only when there are associations for the item and the item language is modified while editing the item.

This means that the js is not working properly.

in the non-minified association-edit.js, we have
First
```
          if (!existsAssociations && document.getElementById("".concat(formControl, "_associations_").concat(languageCode, "_name")).value !== '') {
            existsAssociations = true;
          } 
```
and further
```
        }); // If associations existed, send a warning to the user

        if (existsAssociations) {
          Joomla.renderMessages({
            warning: [Joomla.JText._('JGLOBAL_ASSOCIATIONS_RESET_WARNING')]
          });
```
@dgrammatiko @Fedik

**Comment by Fedik** [comment]
JavaScript are ok, the bug comes from the association field, it have a `value="Select an Article"` when nothing selected, 
that is wrong of course

![screen 2019-12-14 12 39 12 1083x407](https://user-images.githubusercontent.com/1568198/70847605-f1315780-1e6e-11ea-836c-7b0621bc49c6.png)

**Comment by infograf768** [comment]
@Fedik 
I see. It happens even if the item is set to All, which means the fields are not displayed.
There must be a solution.

**Comment by Fedik** [comment]
@infograf768 you were right, it a script

**Comment by Fedik** [comment]
please test #27269

**Comment by infograf768** [comment]
Replied there. Will explain further tomorrow.
Please do not close this issue now.

**Comment by infograf768** [comment]
Patch https://github.com/joomla/joomla-cms/pull/27269 works fine.
Closing this.
