### ISSUE TITLE
Copy Template Fails

### ISSUE THREAD

**Issue by rick9004** [joomla/joomla-cms#27260]
### Steps to reproduce the issue
Select Cassiopeia template, then select copy template, fill out a new name, then enter.  The error then gets thrown.

2 error messages:

Warning 
Jlnstaller: :lnstall: File does not exist bcd87\language 
Template Install: Could not copy files from the files source. 

Error 
Error installing template 
Unable to install new template from temporary folder. 

	

### Expected result

New template as copied

### Actual result

Error thrown. No template created or copied

### Additional comments

Version 4.0 Alpha 12
Actual error dialogs attached

**Comment by Quy** [comment]
Thank you for testing. Duplicate #26259<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27260">issues.joomla.org/tracker/joomla-cms/27260</a>.</sub>
