### ISSUE TITLE
[4.0] The alert message closes overview and distract from content managing

### ISSUE THREAD

**Issue by Fedik** [joomla/joomla-cms#27267]
### Steps to reproduce the issue
Try edit and save the article. 
Or add this to the index.php of admin template:
`$app->enqueueMessage('Lorem ipsum dolor sit amet, ei vim causae expetenda efficiendi, quem altera everti mea no. Est mutat congue ad. His no esse impetus appetere.');`

### Expected result
You should get a message that **not distract** you from content managing.
You should be able to see whole page, and all toolbar buttons, and stuff.

### Actual result
You get a huge popup that closes overview. And you cannot do anything until you close it.

### Additional comments
Add "dismiss" is not a fix of the issue, because it require extra move from user each time, it **distract**.

Comparison with previous Joomla.
**Edit screen:**
j4
![screen 2019-12-14 12 49 36 1353x389](https://user-images.githubusercontent.com/1568198/70848115-7f104100-1e75-11ea-8e23-c85fc50126d9.png)

j3
![screen 2019-12-14 13 26 11 928x306](https://user-images.githubusercontent.com/1568198/70848125-88011280-1e75-11ea-840d-cb54f7ceab22.png)

**Content List:**
j4
![screen 2019-12-14 12 47 26 1374x419](https://user-images.githubusercontent.com/1568198/70848136-b4b52a00-1e75-11ea-9867-2f1d34a64cd5.png)

j3
![screen 2019-12-14 13 29 17 1148x352](https://user-images.githubusercontent.com/1568198/70848143-cbf41780-1e75-11ea-9636-8274574a8af2.png)

**Comment by brianteeman** [comment]
Thats why we want to change them to be auto dismiss but that has been stuck waiting for javascript

**Comment by Fedik** [comment]
> Thats why we want to change them to be auto dismiss

Unfortunately, I think it also not a best solution, because we cannot predict how fast user can read the message. It will vary from a message size and user read experience.
Also message may happen when user was went out from PC for a couple min (or just switch to another browser tab), then he/she will miss the massage (example when processing backup or other long task by 3rd extension)

In my opinion, if people really want a popup, it should be styled smaller, and placed aside,
at least something like Mac notifications, but not that huge thing at the middle, that scream "look at me".

Maybe even with "a little tray" of history of recent messages that was popped on the page (but this a bit more complex of course).

**Comment by brianteeman** [comment]
We can't change the styling until the script is fixed

**Comment by infograf768** [comment]
See discussion here:
https://github.com/joomla/joomla-cms/pull/27213

**Comment by 200MPHMEDIA** [comment]
With the messages floating above the screen, when clicking anywhere else, re: a link item on the open admin screen, the popup should close automatically vs. the need to manually do so before proceeding.  We are experiencing this issue in all incidents of action taken results messages.

**Comment by Quy** [comment]
Please test PR #28824
