### ISSUE TITLE
[4.0][com_installer] Undefined index: :pkgname

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#27270]
> PHP Notice:  Undefined index: :pkgname in \libraries\vendor\joomla\database\src\Mysqli\MysqliStatement.php on line 402
PHP Notice:  Undefined index: :pkgname in \libraries\vendor\joomla\database\src\Mysqli\MysqliStatement.php on line 403
PHP Warning:  mysqli_stmt::bind_param(): Number of variables doesn't match number of parameters in prepared statement in \libraries\vendor\joomla\database\src\Mysqli\MysqliStatement.php on line 420

### Steps to reproduce the issue
Go to System > Update Sites
Click Rebuild
See `An error has occurred.`
View PHP error log

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/27272.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27270">issues.joomla.org/tracker/joomla-cms/27270</a>.</sub>
