### ISSUE TITLE
[4.0] Insert Module into Article Not Working

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#27279]
In the Article Workspace, we attempting to insert a Module into the Article Content, when clicking "Module" in the CMS Content dropdown, it opens the list of Site Modules. However, when selecting a Module, nothing happens.

No code is inserted into the Article Content when a Module is chosen.

Additionally, using the {loadmoduleid xx} and other code to insert Modules does not work either.

The appropriate Plugin is enabled.

**Comment by SharkyKZ** [comment]
The code responsible for this functionality has been removed https://github.com/joomla/backend-template/pull/146/commits/c4e893d3f4912ddb42cb3678cc89bef6a0fd8dc5.

**Comment by Quy** [comment]
Duplicate #26768?
