### ISSUE TITLE
[4.0] Cassiopea broken com_config features

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#27283]
### Steps to reproduce the issue
Install Blog sample data

Log as Super User in frontend.
Stay on the Home page.

In the TOP Author Menu, click on Site Settings
Save the form
Result: `{"error":true,"code":0,"message":"Form::loadForm could not load file"}`

Also in the TOP Author Menu, click on template settings
Change the description and save (Do not try to change to fluid Layout as it is really broken). 
Result: Nothing changes at first. It will change after reloading the page again.
The Page remains stuck on `/en/component/config` (I test on a multilingual site) and one has to click on Home in the Main menu to get out of there.

Now edit a module and Save it. No need to change anything.
Result: `{"error":true,"code":0,"message":"Call to a member function getType() on null"}`

**Comment by SharkyKZ** [comment]
See PR https://github.com/joomla/joomla-cms/issues/27284 for first issue.

**Comment by infograf768** [comment]
On it.

**Comment by infograf768** [comment]
First issue OK after patch

**Comment by Quy** [comment]
Duplicate #25435 for last issue.

**Comment by technicaldwiti** [comment]
Hii everyone. As a beginner to the world of open source and having intermediate experience on front end and back end how can how can i start contributing to JOOMLA?Means after forking and cloaning to my local computer what are the steps i have to follow to start contributing and modifying the codes?

**Comment by Quy** [comment]
@technicaldwiti Please read this article to get started. https://docs.joomla.org/Git_for_Coders

**Comment by SharkyKZ** [comment]
Please test #27441 for module issue.

**Comment by SharkyKZ** [comment]
Please test #27442 for template issue.

**Comment by SharkyKZ** [comment]
Closing this as there are PRs for all mentioned issues.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27283">issues.joomla.org/tracker/joomla-cms/27283</a>.</sub>
