### ISSUE TITLE
[4.0] Beta 1 Blog/Featured Laouts Missing Items

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#27281]
In Joomla! 4 Beta 1, under the Options tab for Blog/Featured Layouts, there are two fields missing. They are also missing in the Menu Link Item Manager for this type of layout. They are:

1) Number of Columns - to set the number of columns for Intro Articles.

2) Multi Column Order - to set how Articles flow into the mutlicolumns.

These two items are present in the Joomla! 3 Blog/Featured Layout admin, but not Joomla! 4.

**Comment by SharkyKZ** [comment]
Columns have been replaced with custom classes. See https://github.com/joomla/joomla-cms/pull/18319 for details.

**Comment by SharkyKZ** [comment]
Closing as expected behavior.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27281">issues.joomla.org/tracker/joomla-cms/27281</a>.</sub>

**Comment by 200MPHMEDIA** [comment]
What/Where is the User Guidance for creating multicolumn layouts and how to set the flow for the Blog/Featured Layouts.  Should these two important Blog/Featured Layout "options" be included intuitively vs. the need to know how to implement classes?
