### ISSUE TITLE
[4.0] Update to Bootstrap 4.4.1

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#27287]
Newest version of BS here:
https://github.com/twbs/bootstrap/releases/tag/v4.4.1

**Comment by peteruoi** [comment]
Bootstrap 4 will move to Long Term Support after we release v4.4 and will no longer receive new features from then on. It will continue to receive bug fixes, security updates, and documentation updates.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/issues/27294.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27287">issues.joomla.org/tracker/joomla-cms/27287</a>.</sub>
