### ISSUE TITLE
[4.0] Beta 1 Editing Layout Missing Items

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#27282]
n Joomla! 4 Beta 1, under the Options tab for Editing Layouts, there are three fields missing. They are:

1) Edit Screen Options

2) Article Permissions

3) Multilingual Associations

The associated Help Screens do not list or explain the purposes and use of these Options.

**Comment by brianteeman** [comment]
I assume you mean these
![image](https://user-images.githubusercontent.com/1296369/71306860-0ada1e00-23de-11ea-85a8-f5b11c6a1118.png)

I assume that when you say missing you expected something to be displayed on this page when you switch them on/off

If my assumption is correct then you misunderstood the purpose of these fields. They are in the section for the "editing layouts" and they govern what is displayed when you edit an article. 

For example if I disable all of those options (and similar) I get a simplified article edit screen

![image](https://user-images.githubusercontent.com/1296369/71306918-dfa3fe80-23de-11ea-86f3-f7c9c10a955c.png)



This is not a new feature - it is just an extended feature. In joomla 3 you could disable some of these tabs but not all

If I have misunderstood your issue I apologise and could you please provide a more detailed explanation of what is missing

**Comment by 200MPHMEDIA** [comment]
Brian:  We reinstalled J!4 from a new nightly build and the issues noted in the original post no longer exist, so it may have been missing on an earlier version.  Solved Now.  Thanks again.
