### ISSUE TITLE
[4.0] Beta 1 Adding Extensions Fail

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#27280]
Several attempts to add Extensions into the Beta 1 version of Joomla! 4 has resulted in failures.

Attempted to use the "Upload Package File" with a Joomla! 4 Compatible Extension continually fails.

Please advise the Developers of this issue.

**Comment by SharkyKZ** [comment]
Can't replicate this issue. Which extensions are you trying to install and what errors are you getting?

**Comment by 200MPHMEDIA** [comment]
The Extension was the Date & Time Extension obtained via the JED and attempted to install via Package Upload.

**Comment by SharkyKZ** [comment]
Can you post a link to the extension on JED?

**Comment by 200MPHMEDIA** [comment]
Here is the link to the Extension:

[https://extensions.joomla.org/extension/display-date-time/](url)

**Comment by SharkyKZ** [comment]
>Call to undefined method Joomla\CMS\Application\AdministratorApplication::isAdmin()

This extension is not compatible with 4.0.

**Comment by 200MPHMEDIA** [comment]
OK, thank you very much for noting that for us.  We will check further Extensions closer hence.  Thank you again.

**Comment by brianteeman** [comment]
Please close this

**Comment by Bakual** [comment]
Please note that Joomla 4.0 isn't in Beta yet. It's still Alpha.
And obviously neither Alpha nor Beta should be used in production.

**Comment by 200MPHMEDIA** [comment]
Thanks Bakual:
Was using "Beta 1" on a prototype testing site, not for production.  Appreciate the advice, but we are/were well aware of the version used and the cautions about using on a production site.

**Comment by AMurray2016** [comment]
@Bakual  If beta is not yet out, what is the nightly build Beta 1 currently available on Devleoper network page https://developer.joomla.org/nightly-builds.html ?

Joomla! 4.0
These packages were built based on commit fb716857ba76d37fd53ca1384afb99ccba857ad2
These packages were last built: Tuesday, 17 December 2019 03:00:45 UTC

    Joomla_4.0.0-beta1-dev-Development-Full_Package.zip
    Joomla_4.0.0-beta1-dev-Development-Update_Package.zip
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27280">issues.joomla.org/tracker/joomla-cms/27280</a>.</sub>

**Comment by Bakual** [comment]
`beta1-dev` means it's still in the development process for the upcoming first beta version. It's not a released beta yet (thus still in alpha version). After first beta (4.0.0-beta1) is released, the version in the nightlies will become beta2-dev until beta2 is released. And so on.
