### ISSUE TITLE
How to increase container width

### ISSUE THREAD

**Issue by life777eternal** [joomla/joomla-cms#27292]
Hi, I recently combined a couple articles and one of them is appearing over top of the left side of the container, how do I make the changes to the Container that I found when I inspected the page?
https://i.imgur.com/7RXAM2y.png

https://joomla.wholisticapproaches.net/index.php/8-security/2-secure-your-email-with-gnupg-pgp

Thank you.

**Comment by SharkyKZ** [comment]
To add custom CSS without copying the entire template, create `user.css` file in template's `css` directory. See documentation https://docs.joomla.org/J3.x:Adding_a_custom_CSS_with_Protostar.

**Comment by GCLW** [comment]
I don't know how you combined the articles, but your added html is using the .row class which has a margin-left attribute set to -20px.
You are nesting the header tag.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27292">issues.joomla.org/tracker/joomla-cms/27292</a>.</sub>

**Comment by life777eternal** [comment]
> I don't know how you combined the articles, but your added html is using the .row class which has a margin-left attribute set to -20px.
> You are nesting the header tag.
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/27292](https://issues.joomla.org/tracker/joomla-cms/27292).

Hello @GCLW thank you, aye, I see now the row class, though the text on the original website is farther to the right to begin with. With the images directly to the left of sections of text, using divs. 

> To add custom CSS without copying the entire template, create `user.css` file in template's `css` directory. See documentation https://docs.joomla.org/J3.x:Adding_a_custom_CSS_with_Protostar.

@SharkyKZ Thank you, I have a new blank user css file now,

**Comment by alikon** [comment]
@life777eternal  if solved then please close the issue 
thanks
