### ISSUE TITLE
Improved handling of overrides

### ISSUE THREAD

**Issue by thoni56** [joomla/joomla-cms#27293]
### Is your feature request related to a problem? Please describe.

Creating overrides is fairly easy (but see #24484), but managing them after that is cumbersome and leaks the implementation to the user. To delete an override you have to delete the file, it is hard to see which overrides you have already created. And, in particular, it is very hard to see what changes are made to an override.

### Describe the solution you'd like

I'd like a GUI where the overrides (not files) are listed so that I could see if there actually is an override, what differences to the original there are, with an easy way to delete a particular override (preferably in a more fine-grained way (like suggested in #24484).

A particularly useful, but more advanced, feature would be to be able to see which changes have updates made to the file in question compared to the file content when the override was created.

### Additional context

In order to implement this the abstraction of overrides has to be raised and maintained. E.g. under the hood a copy of the original file need to be kept to be able to diff the override after updates to the original, which should not be show to the user. The user should navigate overrides, not files.

And an override must be defined to mean any replacement of any single file. So names for overrides should probably be the "path" to the file.

**Comment by brianteeman** [comment]
I think you will find that all of this is already present in joomla 4.

**Comment by thoni56** [comment]
Lovely! I'm looking forward to seeing that. Just a few months from now ;-)

**Comment by infograf768** [comment]
You can test the present 4.0 beta by using the nightly build (NOT for production)
https://developer.joomla.org/nightly-builds.html

If you find there what you want, please close this Issue.

**Comment by Quy** [comment]
This can be reopened if you have further feedback after testing J4.
