### ISSUE TITLE
Database creation throws error and cannot proceed Joomla 4.0 Alpha 11

### ISSUE THREAD

**Issue by djalondon** [joomla/joomla-cms#27303]
### Steps to reproduce the issue

Uploaded Joomla! 4.0.0-alpha11 zip file. Created new database with cPanel database wizard. Set PHP version to 7.2 and ran the installer.

### Expected result

Progress to next step in Installer

### Actual result

The database is created, and configuration.php contains correct database details but cannot proceed past the Install Joomla > step

Error: Can't create/write to file '/mnt/ramdisk/mysql/#sql_70c5_0.MAI' (Errcode: 2 "No such file or directory")

Cannot proceed or go back a step after the db error is resolved. I had to remove all files in the folder, re-extract the installer zip and run the wizard again.

### System information (as much as possible)

PHP7.2 running on shared hosting account on Rochen - database type selected was MySQLi
Database server version: 10.3.21-MariaDB - MariaDB Server

### Additional comments

Once through the steps (on 3rd attempt) I skipped languages when taking the customize route, installed sample data then got:
Error
JLIB_APPLICATION_ERROR_VIEW_NOT_FOUND on the Completed window

**Comment by ReLater** [comment]
Could you please test again with a nightly build package?
https://developer.joomla.org/nightly-builds.html

Many things have changed since 4.0.0-alpha11

**Comment by brianteeman** [comment]
from the error message it sounds like a server issue and not related to joomla

**Comment by djalondon** [comment]
There was a server issue but the database was installed and I couldn't progress past that window in the installer, which to my mind is a Joomla issue, isn't it?

**Comment by alikon** [comment]
please use a nigthly build, 4.0.0-alpha11 is too old
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27303">issues.joomla.org/tracker/joomla-cms/27303</a>.</sub>
