### ISSUE TITLE
Dead Site

### ISSUE THREAD

**Issue by MusosGuide** [joomla/joomla-cms#27302]
Site www.musosguide.org.uk displaying this at both front end and back end:- INSERT command denied to user 'dbo451955272'@'infong-uk7.clienthosting.eu' for table 'musos_session' SQL=INSERT INTO `musos_session` (`session_id`, `client_id`, `time`) VALUES ('fdcbc22d746a1b1ac3fd336f846d596a', 0, '1576668349')

**Comment by brianteeman** [comment]
As already informed by @pe7er this is not the correct place for this. Please use the links he gave you

**Comment by MusosGuide** [comment]
The first link sent me there.

Kenny McMurtrie
Editor-in-Chief
www.musosguide.org.uk

**Comment by alikon** [comment]
This is a permissions problem, not a core issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27302">issues.joomla.org/tracker/joomla-cms/27302</a>.</sub>

**Comment by MusosGuide** [comment]
Like I know what that means.

Kenny McMurtrie
Editor-in-Chief
www.musosguide.org.uk

**Comment by alikon** [comment]
It means that the user `'dbo451955272'` don't have the right GRANT to access/write your data, but yet again this has nothing to do with a core issues,  for which this is place is for, please use the forum https://forum.joomla.org/

**Comment by MusosGuide** [comment]
Still Greek to me as I've no idea who or what that user name relates to.

Kenny McMurtrie
Editor-in-Chief
www.musosguide.org.uk

**Comment by Bakual** [comment]
Still wrong place. You have to go to the forum.
Locking this thread.
