### ISSUE TITLE
Subform with wrong/double field name array keys

### ISSUE THREAD

**Issue by cinemarene** [joomla/joomla-cms#27307]
Joomla 3.9.14

```
<field
                name="test_fields"
                type="subform"
                label=""
                multiple="true"
                buttons="add,remove"
                groupByFieldset="true"
                min="1"
                max="5">
            <form>
                <fieldset name="section1">
                    <field
                            name="test_field"
                            type="text"
                            label="TESTFIELD1"
                            default=""
                    />
                </fieldset>
            </form>
        </field>
```

Go to the form.
Now there is one row with key 0.
Add one row with "+" button.
Now there are two rows with 0 and 1.
Remove first row with key 0 over button "-".
Now there are one row with key 1.
Add one row with "+" button.
Now there are two rows with key 1 and 1.

![double_field_array_keys](https://user-images.githubusercontent.com/9309569/71098551-282aa480-21b2-11ea-8fcd-838ad5da1594.jpg)

**Comment by ReLater** [comment]
Confirmed.

Addition: If you save then 1 row is lost.

**Comment by ReLater** [comment]
Same issue in Joomla 3.9.13.

Side effect: If there's an editor field in the subform it's not loaded correctly if you follow the instructions above.

**Comment by Fedik** [comment]
can someone check 3.9.0 and older, I suspect this #22757 a reason

**Comment by ReLater** [comment]
No issue with 3.9.0.

Issue confirmed with 3.9.1.

Tested with subform in "Users Options" > "Email Domain Options"

**Comment by ReLater** [comment]
Corrected my last post (Joomla versions).

**Comment by ReLater** [comment]
Pinging @continga for the sake of completeness

**Comment by Fedik** [comment]
please test #27334

**Comment by alikon** [comment]
please test #27334<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27307">issues.joomla.org/tracker/joomla-cms/27307</a>.</sub>

**Comment by Fedik** [comment]
I found this bug also in j4, but this need to be fixed separately because the subform script was rewritten there.

#27334 only for j3

@alikon can you please reopen it? and maybe tag somehow that it also j4, if possible

**Comment by alikon** [comment]
reoponed as requested <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27307">issues.joomla.org/tracker/joomla-cms/27307</a>.</sub>

**Comment by alikon** [comment]
reopened 
p.s
unfortunately i don't ave that superpower

**Comment by Quy** [comment]
Thank you! Please test #27342 for J4.
