### ISSUE TITLE
[3] Installation. Misleading de-DE alert text

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#27306]
I really don't know if it's worth to change something here. Pedantry...

### Steps to reproduce the issue
- Install J3 and set language to de-DE for install process.
- In databse settings fill all fields but clear the table prefix field.
- Try to go to next installation step.

You'll see an alert (language string `INSTL_DATABASE_PREFIX_MSG`) that says:

`Der Tabellenpräfix muss mit einem Buchstaben beginnen, danach können optional alphanumerische Zeichen und ein Unterstrich folgen.`

(EN counterpart:
`The table prefix must start with a letter, be followed by optional alphanumeric characters and by an underscore`
)

- At least the German text suggests that the underscore is optional, too.

**Comment by brianteeman** [comment]
@Bakual one for you

**Comment by zero-24** [comment]
@ReLater hmm I'm not an regex pro but it does not seam to be required: https://github.com/joomla/joomla-cms/blob/3601da2a2398e8da31fdc2399c3e5aa9de122107/installation/model/database.php#L128

Demo
https://3v4l.org/SD0XE

**Comment by ReLater** [comment]
It's required. I've tested it without underscore.

See also description of the related input field: https://github.com/joomla/joomla-cms/blob/staging/installation/language/de-DE/de-DE.ini#L44

`enthält nur alphanumerische Zeichen und MUSS mit einem Unterstrich enden.`

I think it's a JS thing or client-site input validation but ???.

**Comment by zero-24** [comment]
Well than please send an issue / PR against https://github.com/joomlagerman/joomla so we make it more clear that the underscore is required in that string too. Any changes in the official language repo gets synced back in here.

**Comment by ReLater** [comment]
PR: https://github.com/joomlagerman/joomla/pull/847

**Comment by zero-24** [comment]
Thanks @ReLater
