### ISSUE TITLE
Invisible reCaptcha does not work

### ISSUE THREAD

**Issue by mazharvai007** [joomla/joomla-cms#27314]
### Steps to reproduce the issue
I used the unique site and secrete key in the **CAPTCHA - Invisible reCAPTCHA** plugin. But, in the front-end showing like the image
![Screenshot on 2019-12-19 at 14_50_45](https://user-images.githubusercontent.com/3949434/71158996-1bb85180-226f-11ea-92a4-25a9eb172deb.png)

**Comment by C-Lodder** [comment]
The badge is always shown by default. You can hide it using CSS:

```css
.grecaptcha-badge { 
    visibility: hidden;
}
```

**Note:** Do not use `display:none`

If you hide it, you must include the fact you're site uses reCaptcha in the user flow, as per their T&C's: https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed
