### ISSUE TITLE
[4.0] Associations return url

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27312]
### Steps to reproduce the issue
On a multilingual site edit an article and then click on the associations button in the toolbar. This will open the article in the multilingual associations component. Then click on Close in the toolbar

### Expected result
return to the article OR return to the  main multilingual associations with the item type already selected.

### Actual result
returned to the main multilingual associations component with no item selected

**Comment by brianteeman** [comment]
I am guessing that this can be achieved by adding a new variable to the button layout as a boolean for enabling the setting of a return url and then updating the js to use it in the generated output of the custom element

**Comment by infograf768** [comment]
I am not in favor of returning to the original edit article in com_content as the main reason for this Associations button is a shortcut to work with associations in the component and go on working on other stuff there.

When coming from an edited item clicked in the Associations Manager and closing in the side by side, we are redirected to the associations Manager with the type and language last used. 

We are not indeed redirected to the correct type and language when closing if we come originally from the article edit toolbar in com_content.
It would be good to implement that part. 

I guess it comes from the `UserState` which is set in the associations Model (`populateState()` method) and therefore can't be picked from it as we go directly to the side by side page.

**Comment by brianteeman** [comment]
> I am not in favor of returning to the original edit article in com_content as the main reason for this Associations button is a shortcut to work with associations in the component and go on working on other stuff there.

That behaviour is not consistent with other toolbar buttons. If you want to work on lots of associations then you would use the component link and not a link inside an article

**Comment by infograf768** [comment]
You are entitled to have your own opinion. If you don't like it, do not use it, but do not prevent users from using it.

**Comment by brianteeman** [comment]
It is illogical to have your desired behaviour

**Comment by brianteeman** [comment]
No point fixing this
