### ISSUE TITLE
[J3] Cannot remove links from category list titles

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#27322]
### Steps to reproduce the issue
Create a new menu item of type "Articles > Category List"
In the 'Options' tab, ensure that 'Linked Titles' is set to 'No'.

Why do I want to do that? Well, when creating this menu item in a menu for front editors, I want them to click the 'Edit' button which takes them straight to the editor. Clicking an article title link takes them not to the editor but to the actual article. Then, to edit the article they have to go through further clicks to access the editor.

### Expected result
Unclickable article titles

### Actual result
Active article links 

### System information (as much as possible)
Brand new installation of Protostar installed today (to ensure it wasn't an issue with my template overrides) on J3.9.14 but I first noticed this a year ago. Apache server, PHP 7.2.

### Additional comments
This works correctly in J4 Alpha.

**Comment by brianteeman** [comment]
You could resolve this by creating an override. The code is probably the same as for a blog title

https://github.com/joomla/joomla-cms/blob/e15a20a189e018e0acb363f563779b2f9eed916a/layouts/joomla/content/blog_style_default_item_title.php#L20-L31

**Comment by Scrabble96** [comment]
Yes, I realise I could create an override (and I'll have to), but it doesn't explain why it isn't working as expected, but does in J4 Alpha. The default.php code is almost identical apart from the params/helper part. Something in there, perhaps? 

Correction: should have said 'default_articles.php'

**Comment by ReLater** [comment]
@HLeithner 
Do we want to change the described behavior in Joomla 3 or should issue be closed as "expected/wanted behavior"?

**Comment by HLeithner** [comment]
@ReLater sounds like a bug to me and should be fixed

**Comment by ReLater** [comment]
I reflected a bit on this issue: The situation in catergory list views is a little bit different from category blog views.

1)
We should be aware that one cannot open articles then from the list view page because the title field is the only one that has a link in a table row. There is no readmore button or intro image or other.

2)
> but it doesn't explain why it isn't working as expected, but does in J4 Alpha.

I cannot confirm that it works like described above in current J4 nightly:


![001](https://user-images.githubusercontent.com/20780646/76026577-56a55980-5f2f-11ea-9fa4-d6eda15bae4d.jpg)

![002](https://user-images.githubusercontent.com/20780646/76026589-5c9b3a80-5f2f-11ea-9858-1b06760b0c93.jpg)

**Comment by ReLater** [comment]
...that is to say I would close this issue with mark "expected behavior".

**Comment by SharkyKZ** [comment]
Looking at code history, this parameter was never used in category list layout. It only affected single article layout. That use was removed with https://github.com/joomla/joomla-cms/pull/4402.

**Comment by Scrabble96** [comment]
> 
> 
> Looking at code history, this parameter was never used in category list layout. It only affected single article layout. That use was removed with #4402.

Which begs the question: why is the 'Linked Titles' option there at all if it's expected behaviour that it changes nothing if 'No' is selected?

My original query was based on looking at category lists when logged into the frontend with editing rights. Clicking 'Edit' takes the user straight to the editor. Clicking the active 'title' doesn't.

![linked-category-list-titles](https://user-images.githubusercontent.com/36987494/76071496-407ab600-5f8e-11ea-95f9-bf85622f6f66.jpg)

**Comment by SharkyKZ** [comment]
Because whoever did #4402 forgot to remove it 😄

>Clicking 'Edit' takes the user straight to the editor. Clicking the active 'title' doesn't.

I consider this to be expected behavior.

**Comment by Scrabble96** [comment]
In the meantime, I have achieved what I need with an override.

**Comment by ReLater** [comment]
> why is the 'Linked Titles' option there at all

<strike>"Linked Titles" is in tabulator "Options". **It's inherited by the single article views!!**

One could discuss if it's clever to link the title then in **blog** views, too, if activated but as said above:

> We should be aware that one cannot open articles then from the list view page because the title field is the only one that has a link in a table row.

If we change something here we should establish a new parameter/option like "butNotInCategoryView". That would match all needs and expectations.
</strike>

**Comment by ReLater** [comment]
```
<field
	name="link_titles"
	type="list"
	label="JGLOBAL_LINKED_TITLES_LABEL"
	description="JGLOBAL_LINKED_TITLES_DESC"
	useglobal="true"
	class="custom-select-color-state"
	>
	<option value="0">JNO</option>
	<option value="1">JYES</option>
        <option value="2">butNotInCategoryView</option>
</field>
```

**Comment by ReLater** [comment]
****Forget my last post above.** I'm wrong.**

**Comment by ReLater** [comment]
<strike>I will provide a pr. Let's see what happens with it.</strike>

**Comment by ReLater** [comment]
Not that easy. I'm sorry that I have to cancel my proposal to provide a pr.

We also have a setting `show_associations`. If activated it shows LINKED language labels to associated articles. That's too much effort and too time-consuming to find an acceptable solution for this case and everybody. It's not just deactivating the links but also CSS classes that have to be ported to `<span>`s and so on.

**Comment by brianteeman** [comment]
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed. 

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
