### ISSUE TITLE
post-installation messages [Class XMLReader not found]

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#27337]
### Steps to reproduce the issue
Go to:
`your website  /administrator/index.php?option=com_postinstall&eid=700`

### Actual result

> Release news from the Joomla! Project
> Error
>An error has occurred.
>    0 Class 'XMLReader' not found 
> Return to Control Panel

![изображение](https://user-images.githubusercontent.com/3662519/71325186-38b48500-24fa-11ea-9d12-06a44ec3970a.png)

### System information (as much as possible)
Joomla! 3.9.14 

### Additional comments
This bug is visible on all websites, on all versions of Joomla

**Comment by Quy** [comment]
Duplicate #17556

**Comment by 4digitalworld** [comment]
@Quy thanx! My problem is resolved.

Where can I see a complete list of all recommended PHP extensions that I should **turn on**? My hosting didn't turn on all extensions.

**Comment by 4digitalworld** [comment]
@brianteeman Please help me. Are there any other PHP extensions that I should include? I have not found a complete list of recommended PHP extensions for Joomla 3.9 anywhere.

It may be necessary to check the included instrument for PHP extensions so that each administrator can see this in the administrative panel, in order to avoid such issues. My hosting unfortunately disabled some of the PHP extensions, so now I am having various difficulties that I am trying to solve.

![изображение](https://user-images.githubusercontent.com/3662519/71326053-ba121480-2506-11ea-9fae-4b790c773301.png)

**Comment by brianteeman** [comment]
Best solution is to get a real host who understands the needs of its users and not a host that once read a random blog post on the Web with a suggestion to disable things

**Comment by 4digitalworld** [comment]
@brianteeman I'm using hosting now GoDaddy.com and I have similar problems. My previous hosting did not have such problems.

I know that when installing Joomla there is a check for compatibility with the hosting. But what if I move the website from one hosting to another?

I think it would be possible to add such a check to the Joomla admin panel so that you can check the site at any time.

**Comment by brianteeman** [comment]
Go to the system menu and then there is an information menu.

**Comment by 4digitalworld** [comment]
@brianteeman I know about this menu. I mean, maybe there you need to make indicators, as when installing Joomla?

I mean green (recommended value), red (need to be changed)?

There are just inscriptions now - on / off. This is not very informative. It is necessary to make green indicators for each value, if everything is in OK.

You need something like this (I saw this in JomSocial):
![изображение](https://user-images.githubusercontent.com/3662519/71349523-47de1600-2580-11ea-96af-0bb5df11c484.png)

**Comment by 4digitalworld** [comment]
@brianteeman I have no idea at the moment which values are recommended and which need to be changed in the PHP settings, because this is normal static information.

You must add green indicators for each value, if everything is OK.

![изображение](https://user-images.githubusercontent.com/3662519/71349804-e9fdfe00-2580-11ea-84db-384030b87edc.png)

**Comment by 4digitalworld** [comment]
@brianteeman We have a green value for folders, but this is not enough. It is necessary to do the same for system requirements and for PHP extensions. I think this will be correct and will help to avoid many questions, such as mine. Moreover, such settings are in a very popular hosting GoDaddy.

![изображение](https://user-images.githubusercontent.com/3662519/71350429-62b18a00-2582-11ea-87a0-4316b0251f0f.png)
