### ISSUE TITLE
[3.9.14] Option Value Label rendered incorrectly

### ISSUE THREAD

**Issue by marco-pistone** [joomla/joomla-cms#27332]
### Steps to reproduce the issue
in my language file i have these labels

```
COM_MPROWBUILDER_TITLE_SPEAKER_TYPE = "Select a type"
COM_MPROWBUILDER_TITLE_SPEAKER = "Speaker"
COM_MPROWBUILDER_TITLE_MODERATOR = "Moderator"
COM_MPROWBUILDER_TITLE_SPEAKER_MODERATOR = "Speaker/Moderator"
```

this is my form file

```
<field name="moderator" 
                     filter="safehtml" type="radio" default="0" 
                     required="true"
                     class="btn-group"
                     label="COM_MPROWBUILDER_TITLE_SPEAKER_TYPE"
              >
                     <option value="1">COM_MPROWBUILDER_TITLE_MODERATOR</option>
                     <option value="0">COM_MPROWBUILDER_TITLE_SPEAKER</option>
                     <option value="2">COM_MPROWBUILDER_TITLE_SPEAKER_MODERATOR</option>
              </field>
```

### Expected result
this is what i expect as result:
![joom2](https://user-images.githubusercontent.com/15220440/71311041-c8cfcd00-241b-11ea-9f01-b9119d819f17.png)

### Actual result
instead i have this
![joom1](https://user-images.githubusercontent.com/15220440/71311091-65926a80-241c-11ea-9f61-8b2cb80d7d68.png)

### System information (as much as possible)
Joomla 3.9.14
phph 7.3

### Additional comments
This behaviour happens only with option labels
infact the label "COM_MPROWBUILDER_TITLE_SPEAKER_TYPE" is rendered correctly.
It seems a parsing mistake.
To avoid this i changed the label in COM_MPROWBUILDER_TITLE_SPEAKERMODERATOR so it works

**Comment by ReLater** [comment]
Confirmed. Also with Joomla 3.9.13.

Image is with language debug activated. Strings in "en-GB.override.ini" (administrator).

![21-12-_2019_19-36-45](https://user-images.githubusercontent.com/20780646/71312337-cbd1ba00-2429-11ea-9dba-71983eb79e38.jpg)

**Comment by ReLater** [comment]
Test with article.xml in Joomla 3.9.1. Seems to be OK there.

![21-12-_2019_19-48-33](https://user-images.githubusercontent.com/20780646/71312418-0b4cd600-242b-11ea-91b4-dc3917c2a412.jpg)

Looks like something happend between Joomla 3.9.1 and 3.9.13-

**Comment by ReLater** [comment]
Test with Joomla 3.9.13 and "list" instead of "radio". Same issue:

![21-12-_2019_19-54-41](https://user-images.githubusercontent.com/20780646/71312500-f58be080-242b-11ea-967b-35cb6c448546.jpg)

**Comment by ReLater** [comment]
I've found the resaon for your special case:
Your field name is "moderator".

In `JFormField::getOptions()` your label `COM_MPROWBUILDER_TITLE_SPEAKER` is sent through
Methode `Text::alt()`
See: https://github.com/joomla/joomla-cms/blob/3.9.14/libraries/joomla/form/fields/list.php#L158

which means in your case
```
JText::alt('COM_MPROWBUILDER_TITLE_SPEAKER', 'moderator')
```
These lines lead to the error:
https://github.com/joomla/joomla-cms/blob/3.9.14/libraries/src/Language/Text.php#L163-L166

which means in your case
```
if (Factory::getLanguage()->hasKey('COM_MPROWBUILDER_TITLE_SPEAKER' . '_' . 'Moderator'))
{
 $string .= '_' . 'Moderator';
}
```
`COM_MPROWBUILDER_TITLE_SPEAKER` becomes `COM_MPROWBUILDER_TITLE_SPEAKER_MODERATOR`
because there also exists a key `COM_MPROWBUILDER_TITLE_SPEAKER_MODERATOR`.

All I can say is "strange behavior" but don't know how to solve it ;-)

**Comment by Quy** [comment]
Nice sleuthing! Looking at the examples in these lines, should `$alt` value be `field` and not dynamic values? It will fix in this instance, but I don't see a way to solve it either other than document it.

https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Language/Text.php#L148-L149

**Comment by ReLater** [comment]
> I don't see a way to solve it either other than document it.

Documentation done: https://docs.joomla.org/Wrongly_rendered_option_labels_in_form_fields_under_some_circumstances

**Comment by ReLater** [comment]
I did not test with Joomla 4. But I think it has the same issue after comparing the relevant classes:
https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Form/Field/ListField.php#L122

**Comment by brianteeman** [comment]
Based on the comments above and that this has been documented it should be closed
