### ISSUE TITLE
ItemListelement 'position' does not exsist and throws error in Google Rich Snippets Testing Tool

### ISSUE THREAD

**Issue by EJBJane** [joomla/joomla-cms#27349]
### Steps to reproduce the issue
Create a tag. 
Create list of tagged items.
Select type : Article  
### Expected result
List of articles with correct itemListElement properties 
### Actual result
itemListElement property 'position' is missing in the list element properties. 	
### System information (as much as possible)
The Google Structured Data Testing Tool throws the error: 'value for the position field is required'.
### Additional comments
This can be tested in the Google Structured Data Testing Tool.

**Comment by HLeithner** [comment]
Hello @EJBJane if I understand you correctly then this seams to be a template problem and you have to create a template override to solve this issue.

The github issue tracker is not the right place for this, please post your questin the https://forum.joomla.org

I'm closing this, if I'm wrong with my assumption you can always reopen the issue.

**Comment by EJBJane** [comment]
thank you

**Comment by ReLater** [comment]
> if I understand you correctly then this seams to be a template problem

No. See `<li>` HTML tags here:
https://github.com/joomla/joomla-cms/blob/staging/components/com_tags/views/tag/tmpl/default_items.php#L69

No `<meta itemprop="position" content="[number]">` there.

On the other hand I ask myself why this list layout is the only one in Joomla core (besides mod_breadcrumbs where it's a must) that uses these `itemprop="itemListElement"` for `<li>`.

**Comment by HLeithner** [comment]
Does this mean core supports it but it's wrong implemented?

**Comment by ReLater** [comment]
Yes. I think just a missing `<meta itemprop="position" content="[number]">` for each li that has a `itemprop="itemListElement"`.

I'll have a look on it.

**Comment by HLeithner** [comment]
Ok thanks

**Comment by ReLater** [comment]
Please test pr https://github.com/joomla/joomla-cms/pull/27350
