### ISSUE TITLE
[3 and 4] com_tags. Tagged Items. Microdata. Duplicate values for itemListElement.url are not allowed.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#27358]
This issue is a find of @EJBJane (https://github.com/joomla/joomla-cms/pull/27350#pullrequestreview-336814997) .

### Steps to reproduce the issue
- Create a tag "Joomla".
- Add this tag to some articles.

- **Add intro images to these articles.**

- Create a menu item of type "Tagged Items":

![27-12-_2019_14-56-50](https://user-images.githubusercontent.com/20780646/71519819-4cc10380-28b9-11ea-9e3f-b6867783de09.jpg)

- **Set "Item Image" to "Show"**

![28-12-_2019_14-49-39](https://user-images.githubusercontent.com/20780646/71544580-95dc8a80-2981-11ea-86ce-e38e4abbba14.jpg)

- Go to https://search.google.com/structured-data/testing-tool
and test the new menu item/front-end link.

### Actual result
- "Duplicate values for itemListElement.url are not allowed."
- Reason: Two links marked as "url"

```
<li class="cat-list-row1 clearfix" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
    <h3 itemprop="name">
 
	   <a href="/xyz" itemprop="url">
		  Blah
	   </a>
 
    </h3>
 
    <a href="/xyz" itemprop="url">
	   <img src="/images/zyx" alt="" itemprop="image">
    </a>

    ... MORE CODE ...
</li>
```

**Comment by ReLater** [comment]
**Joomla 4:** 
I propose to remove at least the nonsensical ItemList microdata from the layout (components/com_tags/views/tag/tmpl/default_items.php).

**Joomla 3:**
I'm not sure if it would be a too unexpected B\C break to remove it.

**Comment by HLeithner** [comment]
If it makes sense to remove it because it's useless or creates an error we can remove it in J3.
Would it break anything in J3?

**Comment by yashrajbothra** [comment]
Hey , Can i work on this issue?

**Comment by ReLater** [comment]
@yashrajbothra 
Yes

**Comment by ghost** [comment]
@yashrajbothra @ReLater where is pull request? cant find it

**Comment by yashrajbothra** [comment]
@Milglius  Sorry, I was't able to make it up😢.

**Comment by ReLater** [comment]
I removed **error-prone** and **completely senseless** and faulty structured data markup for `Tagged Items `menu type with pr https://github.com/joomla/joomla-cms/pull/28010
