### ISSUE TITLE
Do not create Frontend Tags on the fly by User Groups

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#27354]
Hi guys,
I want to enable the Frontend On the fly Tags creation only to, let me say, Super Admins
As far as I see when I select "Tags > Options > Data Entry > Tag Entry Mode" I cannot find any option about it

Please, Is there any trick / tip to disable the Tags creation on the fly from Frontend ?
As far as I understand I could just create an "hybrid" solution through Permissions > Edit State...

**Comment by brianteeman** [comment]
that's not a "hybrid" solution. it is the correct solution

**Comment by joomleb** [comment]
Hi Brian, 
so the right way, in first of all, is to disable the Create permission to all the Usergroups that have access only to the Frontend...

Thanks for your attention!

**Comment by brianteeman** [comment]
yes
