### ISSUE TITLE
Do not show Nested Tag into Tag

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#27353]
Hi guys, 
when I'm editing in frontend (an article for example), into the Tag selector, nested tags (tags with parent) are shown as:
- "World/China" (where "Word" is the parent Tag) 
> instead to be shown just like "China" or at least "-China" (as in the Administrator Panel list)

As far as I see there is no any Setting Option for that, Please, Am I missing anything ?

**Comment by sozzled** [comment]
See the discussion at the J! forum:  https://forum.joomla.org/viewtopic.php?f=708&t=976710

I do not support this feature request because it would probably cause problems/confusion if there were like-named child tags displayed without the accompanying parent tags.

**Comment by HLeithner** [comment]
In Joomla 3 you can't not easy change this, I see only a hackish way to use a override with str_replace/regex.

In Joomla 4 you are able to override the layout for tags and can modify the title.

Since such a change will not go into j3 and you can change it in j4 by your self I'm closing this. Feel free to reopen if you think I missed something.

**Comment by joomleb** [comment]
Hi guys, many thanks for the attention you have dedicated to me:

@sozzled as I wrote on the discussion there is no any chance to cause problems/confusion with like-named child tags displayed if the same "- nameofthetag" Administrator Panel list layout is applied into the tag selector. 
On the same discussion I also wrote where my need was born.

@HLeithner Please, Do you know if there is yet any type of guide/tutorial/documentation where I can learn more about that in J4 ?

**Comment by HLeithner** [comment]
for j4 the related layout is: layouts/joomla/form/field/tag.php

**Comment by sozzled** [comment]
Thanks, @HLeithner.  Please close this.

**Comment by joomleb** [comment]
@HLeithner Thanks, I appreciate

**Comment by SharkyKZ** [comment]
You can change `Tag Entry Mode` to `Nested` in `com_tags` configuration to get the layout you want. But that will also disable creating tags on the fly.

https://help.joomla.org/proxy?keyref=Help39:Components_Tags_Manager_Options&lang=en#Data_Entry
