### ISSUE TITLE
[4.0] com_redirects alerts

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27378]
I have no idea why we have the alerts on com_redirects to show that it is enabled but there has to be a better way than the current implementation which loads the alert on **every** page load. Personally I dont see the need for the notice at all.

![redirect](https://user-images.githubusercontent.com/1296369/71563586-e50de280-2a89-11ea-82d3-c61eb623f31d.gif)

**Comment by Quy** [comment]
I don't see the need for it either when it is enabled and it is not like this in other places. I vote to remove the notice.

**Comment by HLeithner** [comment]
A section for such (static) information (iirc in j3 you get a notification if the plugin is disabled) would be good...

A link in components to related plugins would be useful... unrelated I know...

**Comment by brianteeman** [comment]
the notification that the plugin is disabled is sensible. I am just referring to the notice saying its enabled

**Comment by HLeithner** [comment]
both is annoying, if you don't want to auto collect  urls it's a pain too

**Comment by brianteeman** [comment]
See #27380
