### ISSUE TITLE
[4.0] php 7.4 Hitting a wall with password hash algorithm Argon2

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#27375]
PHP 7.4
web servers : bitnami and xampp

I have been trying to test joomla 4 with php 7.4.
BDD is installed OK but I can't overcome this error while entering a password:

"This is not implemented, as it is not possible to implement Argon2i with acceptable performance in pure-PHP "
Tested on bitnami and xampp vm for mac, both equipped with php 7.4.

Any workaround ?
I know it's quite early to ask that but as I noticed some of you were already testing php 7.4, I wondered if someone had a solution.

**Comment by mbabker** [comment]
You need to install `ext/sodium` through PECL or compile PHP with Argon support enabled (both of which require `libsodium` installed).

The `sodium_compat` library cannot polyfill all functions in pure PHP, you have hit one of those cases.

Issue can be closed, nothing to do with core Joomla.

**Comment by richard67** [comment]
Closing as not a core issue, see [https://github.com/joomla/joomla-cms/issues/27375#issuecomment-569517885](https://github.com/joomla/joomla-cms/issues/27375#issuecomment-569517885) for details.

**Comment by ghazal** [comment]
Thanks anyway.

**Comment by richard67** [comment]
@ghazal No problem. Thanks for reporting. Better a false alarm for no bug than no alarm for a bug.

And thanks @mbabker for the information above.
