### ISSUE TITLE
Localise.php and php 7.4

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27386]
With php 7.4 you will get this notice with the farsi language pack. Maybe other language packs will as well.

`Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in C:\htdocs\joomla-cms\language\fa-IR\fa-IR.localise.php on line 115
`

@Bakual I guess you need to inform the translators?

**Comment by infograf768** [comment]
@alikon has already a patch for that and I have the corrected file.
I still have to test it on php 7.3 before giving the file to the Persian TT.

**Comment by Bakual** [comment]
Thanks for the notice.
I'm closing this issue as it's not a language pack and thus doesn't need to be tracked here.

**Comment by webpouya** [comment]
This problem exists with php version 8
Is the language file modified?
