### ISSUE TITLE
Joomla werkt niet (meer) op chromebook

### ISSUE THREAD

**Issue by Kasbonita** [joomla/joomla-cms#27382]
### System information (as much as possible)

Goedendag,

Mijn website wordt niet meer geopend op chromebook. Ik krijg de melding: 
Je verbinding is niet privé
Cybercriminelen proberen mogelijk je gegevens van my.vodafone.nl te stelen (bijvoorbeeld wachtwoorden, berichten of creditcardgegevens). Meer informatie
NET::ERR_CERT_COMMON_NAME_INVALID

Help de Chrome-beveiliging te verbeteren door URL's van sommige pagina's die je bezoekt, beperkte systeemgegevens en bepaalde paginacontent naar Google te sturen. Privacybeleid

Kunt u mij hierbij helpen dit weer te laten werken?

alvast bedankt voor de moeite!

Met vriendelijke groet,

Monique

**Comment by richard67** [comment]
In English please.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27382">issues.joomla.org/tracker/joomla-cms/27382</a>.</sub>

**Comment by richard67** [comment]
And it seems not to be a Joomla issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27382">issues.joomla.org/tracker/joomla-cms/27382</a>.</sub>

**Comment by richard67** [comment]
Looks to me like an issue with the SSL certificate, not related to Joomla. But I don't understand Dutch well enough to be 100% sure.

**Comment by Quy** [comment]
Please ask help in Joomla Forum. https://forum.joomla.org/
