### ISSUE TITLE
[3] plg_content_pagenavigation. Accessibility.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#27399]
### Steps to reproduce the issue
According to pr review https://github.com/joomla/joomla-cms/pull/27398#pullrequestreview-338299411 by @brianteeman the button texts "Next/Prev" of page navigation should not have the attributes `aria-hidden`. We removed these attributes in pr 27398 in pagebreak plugin.

```
<li class="next">
 <a class="hasTooltip" title="" aria-label="Next article: Getting Help" href="/path/getting-help" rel="next" data-original-title="Getting Help">
  <span aria-hidden="true">Next</span>
  <span class="icon-chevron-right" aria-hidden="true"></span>
 </a>
</li>
```

https://github.com/joomla/joomla-cms/blob/staging/plugins/content/pagenavigation/tmpl/default.php#L22

**Comment by brianteeman** [comment]
the original pr was https://github.com/joomla/joomla-cms/pull/17508

maybe i am wrong

**Comment by ReLater** [comment]
Pinging @zwiastunsw

**Comment by SharkyKZ** [comment]
#17508 added a different description for screen readers via `aria-label` attribute. Original description was made invisible to screen readers to avoid duplicated description.

**Comment by ReLater** [comment]
> to avoid duplicated description.

Yes, but that's nearly the same in https://github.com/joomla/joomla-cms/pull/27398

We have an aria-label like `aria-label="Next: Title of next page (Page 3 of 7)"` and a visible button `Next` (no `aria-hidden=true`). Thus a screenreader provides nearly duplicated informations with current state of code.

I don't know...
