### ISSUE TITLE
Contact form with Captcha and Custom fields

### ISSUE THREAD

**Issue by petrovicivan** [joomla/joomla-cms#27407]
### Steps to reproduce the issue
I created Custom fields in Mail form and they showed up after Captcha field and before Send button

### Expected result
Captcha should be last field in form before Send button

**Comment by alikon** [comment]
this can be solved with https://docs.joomla.org/How_to_override_the_output_from_the_Joomla!_core

**Comment by petrovicivan** [comment]
It seems that we can't override, I have tried chaneging order of fields in tempaltes/mytemplate/html/com_contact/contact/default_form.php

`<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_contact
 *
 * @copyright   Copyright (C) 2005 - 2019 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

JHtml::_('behavior.keepalive');
JHtml::_('behavior.formvalidator');

?>
<div class="contact-form">
	<form id="contact-form" action="<?php echo JRoute::_('index.php'); ?>" method="post" class="form-validate form-horizontal well">
		<?php foreach ($this->form->getFieldsets() as $fieldset) : ?>

			<?php $fields = $this->form->getFieldset($fieldset->name); ?>
			<?php if (count($fields)) : ?>
				<fieldset>
					<?php if (isset($fieldset->label) && ($legend = trim(JText::_($fieldset->label))) !== '') : ?>
						<legend><?php echo $legend; ?></legend>
					<?php endif; ?>
					<?php foreach ($fields as $field) : ?>
						<?php echo $field->renderField(); ?>
					<?php endforeach; ?>
				</fieldset>
			<?php endif; ?>

			<?php if ($fieldset->name === 'captcha' && !$this->captchaEnabled) : ?>
				<?php continue; ?>
			<?php endif; ?>

		<?php endforeach; ?>
		<div class="control-group">
			<div class="controls">
				<button class="btn btn-primary validate" type="submit"><?php echo JText::_('COM_CONTACT_CONTACT_SEND'); ?></button>
				<input type="hidden" name="option" value="com_contact" />
				<input type="hidden" name="task" value="contact.submit" />
				<input type="hidden" name="return" value="<?php echo $this->return_page; ?>" />
				<input type="hidden" name="id" value="<?php echo $this->contact->slug; ?>" />
				<?php echo JHtml::_('form.token'); ?>
			</div>
		</div>
	</form>
</div>`

**Comment by petrovicivan** [comment]
Her is suggested that only way to archive this is hardcode custom field in override template
[Your text to link here...](https://www.websolutionz.com.au/blog/modifying-a-joomla-contact-form-with-custom-fields "https://www.websolutionz.com.au/blog/modifying-a-joomla-contact-form-with-custom-fields")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27407">issues.joomla.org/tracker/joomla-cms/27407</a>.</sub>

**Comment by alikon** [comment]
yes, maybe not the most easy/clean override, but the way to go

**Comment by petrovicivan** [comment]
There is a problem with multilingual sites, you have to create 2 overrides

**Comment by SharkyKZ** [comment]
You can use this override to move captcha to bottom https://gist.github.com/SharkyKZ/592cc44c68eac9b3ef7e0b3abb2699f3.

**Comment by svermassen** [comment]
If the function like now exists in Joomla! 4 for adding custom fields, it's should not be an override, but should be fixed in the Core of Joomla.

**Comment by pepperstreet** [comment]
Absolutely agree with @svermassen @petrovicivan 
This is a layout and UX bug. 

@alikon
Please, re-open this issue. 
Any chance to get a solution into J!4.2 ? 

Thanks in advance.

**Comment by obuisard** [comment]
This is definitely an issue that should be addressed. 
There are easy ways to fix this. @SharkyKZ would you like to write a PR for it?

**Comment by brianteeman** [comment]
please test #38607 the code was there it was just wrong

**Comment by richard67** [comment]
Closing as having a pull request. Please test #38607 . Thanks in advance.

**Comment by svermassen** [comment]
Nice work !!!

**Comment by brianteeman** [comment]
its only nice if it is accepted and for that it needs people to test it

**Comment by svermassen** [comment]
For me it works.
But it's a YooTheme-site.
So I had to copy part of the code (changes) in the file from the template self.
So it's not the repro as it should be for the testing :-(

**Comment by obuisard** [comment]
@petrovicivan can you take a look at #38607 and test the patch? Thank you!
