### ISSUE TITLE
[4.0] Password view toggle

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27401]
![image](https://user-images.githubusercontent.com/1296369/71772190-e5512680-2f3e-11ea-9d57-6f52b7eb2616.png)

It doesn't matter what the state of the field the sr-only text never changes from JSHOW

The code is in passwordview.js

I am _guessing_ the issue is with the code changed made in #22666

(I spotted this because I was looking to change the text)

**Comment by SharkyKZ** [comment]
Please test PR #27412.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27401">issues.joomla.org/tracker/joomla-cms/27401</a>.</sub>
