### ISSUE TITLE
[4.0] Error: There is no a "template.cassiopeia.ltr" asset of a "preset" type in the registry.: Page not found

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#27414]
### Steps to reproduce the issue

Open a non-existing page.

### Expected result

Joomla! error page.

### Actual result

White screen with error:

>Error: There is no a "template.cassiopeia.ltr" asset of a "preset" type in the registry.: Page not found

### Additional comments

CC @Fedik

**Comment by joeforjoomla** [comment]
Probably effect of this merge https://github.com/joomla/joomla-cms/pull/25775
Pinging @wilsonge as requested by @Fedik must be reverted and not merged for the moment

**Comment by Fedik** [comment]
@SharkyKZ please check #27415

**Comment by alikon** [comment]
please test #27415 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27414">issues.joomla.org/tracker/joomla-cms/27414</a>.</sub>
