### ISSUE TITLE
Bootstrap 5 instead of 4.4.x (last minor version) in stable Joomla! 4

### ISSUE THREAD

**Issue by Mausino** [joomla/joomla-cms#27420]
### Is your feature request related to a problem? Please describe.

Latest Joomla! 3 have problem with outdated major Boostrap 2 version (where it stucked)
New Joomla! 4 Alpha X.version is comming with major version Bootrsrap 4 (now 4.4.1 )
Bootstrap 5 is on horisont and it could be relased in early 2020.

**Bootstrap 4,4.x - is the latest minor version of major 4 Bootstrap**

Would Joomla! 4 have same destiny as Joomla 3 that stucks in version which will for few months outdated in the core? 

reference: https://github.com/twbs/release
![bootstrap](https://user-images.githubusercontent.com/5773777/71835667-667cfa80-30b2-11ea-9a5a-b55034571511.png)
![bootstrap2](https://user-images.githubusercontent.com/5773777/71836492-6120af80-30b4-11ea-9e0d-bdd726d0cb80.png)

### Additional context

**Changes in Bootstrap 5**
Currently the major changes expected in v. 5 include:
Removing jQuery
Deprecated support for IE10
Dropping QUnit
Building testing infrastructure in Jasmine
Documentation rewritten in Hugo
General massive changes in JavaScript
General minor changes in CSS
Responsive containers

### Describe the solution you'd like

I know that you're hard working on new, better and the most powerfull Joomla! ever... but behind the time from first concept of Joomla! 4 relase to this Alpha stage went so much time and technologies go ahead.

PS: sorry for my English

**Comment by wilsonge** [comment]
Thank you for posting. I’d agree if there was anything sort of release date but their tracker currently suggests a date of March 2019. Without an alpha there’s nothing stable to use and by the history of bootstrap 4 there’s nothing to come. 

If the release is available we’ll move to it but there’s really nothing we can do right now

**Comment by Mausino** [comment]
@wilsonge thank you for your answer 👍 i know that nothing is relased yet in Bootstrap 5

I happy that if will something stable available (and if will before stable relase of Joomla! 4) you're as Joomla team open to look on it/think about it :) if it has some potencional or not.

My refences also were:

> "Nearly all new features will be carried forward into Bootstrap 5" - from blog
> https://blog.getbootstrap.com/2019/11/26/bootstrap-4-4-0/ 

https://github.com/twbs/bootstrap/projects/11 
and in the issue section you can see intesive work on labels **v5** and in pull request **backport-to-v4 v5**

Thank to all in team of Joomla! for great work 🥇
