### ISSUE TITLE
User Actions Log notification to be sent on email: problem with URLs

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#27431]
### Steps to reproduce the issue
Go to Users > edit user > User Actions Log

Send notifications for User Actions Log * - set to YES
![Screen Shot 2020-01-08 at 01 03 36](https://user-images.githubusercontent.com/3432048/71933589-93fd9d00-31b3-11ea-818f-6173700178fa.png)

Now the admin receives a notification on email about any changes made on the site by this user.

### Expected result
The action should have clickable URL

![Screen Shot 2020-01-08 at 01 04 19](https://user-images.githubusercontent.com/3432048/71933609-a7106d00-31b3-11ea-8c01-928f4e751ab3.png)

### Actual result
In fact, I see the list of users and actions with URLs, but they are non-clickable.
Perhaps there is a problem with <a>...</a> in the email layout...

### System information (as much as possible)
Joomla 3.9.14

**Comment by SharkyKZ** [comment]
Please test PR #27432.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27431">issues.joomla.org/tracker/joomla-cms/27431</a>.</sub>
