### ISSUE TITLE
No 'helper' folder found for fields

### ISSUE THREAD

**Issue by EJBJane** [joomla/joomla-cms#27433]
### Steps to reproduce the issue
I wanted to create a few custom fields in my article overrides. To achieve this, I was following the instructions posted here (answer 2): 
https://joomla.stackexchange.com/questions/21252/joomla-custom-fields-in-category-list?rq=1  
The solution wasn't working for me, so I checked the url to the helper file for fields. 
Found that there is no 'helper' folder on my Joomla installation. 

### Expected result

So folder should be present like this : components/com_fields/helpers/fields.php
In my installation it is this : components/com_fields/fields.php

### Actual result

Adding custom fields in custom overrides will not work with this method.

### System information (as much as possible)

Joomla! 3.9.14 Stable [ Amani ] 17-December-2019 15:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Linux dedi2762.your-server.de 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3 (2019-09-02) x86_64
Database Version MYSQL	5.7.28-1
Database Collation	utf8_general_ci

**Comment by brianteeman** [comment]
Were you looking in 
\administrator\components\com_fields\helpers

I suspect you were looking in
\components\com_fields\helpers

**Comment by EJBJane** [comment]
I was indeed :-)
