### ISSUE TITLE
com_redirect count hits

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27437]
### Steps to reproduce the issue
enable the redirects plugin and the collect urls option
visit several non-existing urls multiple times

com_redirects will now list all of the non-existing urls with a hit count

Take one of the non-existing urls and edit it so that it has a new url and enable the link

Revisit all of the same non-existing urls

### Expected result
com_redirects increases the hit count for all the non-existing urls

### Actual result
com_redirects increases the hit only for the disabled links

### Additional comments
It seems wrong to me that we stop recording the hits because a link is being redirected. 

I was looking at this to resolve the feature request #27436 
> After a site change a website may receive a number hits from cached Google results that will go away after Google's cache is updated. There is a 404 Hits column in the report, but adding a Last Hit Date column would help identify when a redirect was no longer needed.

**Comment by HLeithner** [comment]
I found the same problem last year on a project and wondered way existing redirects aren't counted.

Have you checked whats the reason is?

Your linked issue seams unrelated?

**Comment by brianteeman** [comment]
The reason is that the code is not there.

The reason the linked issue is related was because the single line of code I added to make it log the last date didn't work because the enabled do not get updated.

It's an easy fix just dont know the reasoning. I would have thought it was useful

**Comment by alikon** [comment]
if i've understand correclty the issue please test #27440

**Comment by Quy** [comment]
Please test PR #34640
