### ISSUE TITLE
[4.0] Admin menu title

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27448]
### Steps to reproduce the issue
Create an admin menu
Create at least one item in the new admin menu
Close that new item and then open it again

### Expected result
![image](https://user-images.githubusercontent.com/1296369/72067672-3c5a5100-32db-11ea-8ba4-2449d1a23713.png)

### Actual result

![image](https://user-images.githubusercontent.com/1296369/72067642-277dbd80-32db-11ea-97bb-95dca51d6f71.png)

**Comment by brianteeman** [comment]
I see now that this is intentional to be displayed and its just a poor design

`	<?php // Add the translation of the menu item title when client is administrator ?>
`

**Comment by infograf768** [comment]
One can call the title: MY_FEATURED_ARTICLES and then create langs overrides for each languages used in admin.
Then the box will show the translated title in the menu and as well when editing the menu item when the translation exists in the admin language used. If no translation, it will show the raw title.

**Comment by brianteeman** [comment]
Closed see #27469
