### ISSUE TITLE
[4.0]  Module Assignment bug  Prepared statements (#26364)

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27446]
Looks like this is caused by the prepared statement changes in #26364 @SharkyKZ 

### Steps to reproduce the issue
Create an admin menu
Create at least one item in the new admin menu
Go to Module manager
Open a site module and go to the menu assignment tab
Select "Only on the selected pages" from the Module Assignment Tab

### Expected result
Tree of all SITE menus and menu items

### Actual result
Tree of ALL menus and menu items - including the admin menu you created in the  steps to reproduce

**Comment by SharkyKZ** [comment]
Oops, what a silly mistake 🤦‍♂.

**Comment by SharkyKZ** [comment]
Please test PR #27449.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27446">issues.joomla.org/tracker/joomla-cms/27446</a>.</sub>
