### ISSUE TITLE
The default module language switcher does not apply good practices SEO

### ISSUE THREAD

**Issue by emma113140** [joomla/joomla-cms#27456]
### Steps to reproduce the issue

Version joomla: 3.9.11
Adress: https://www.memozor.com

I have a Joomla Multilingual site correctly configured.
I followed one by one all the recommendations for a multilingual joomla site.

This is my configuration:
- I use the native joomla for the multilingual, and I don't use any external plugin
- The default language is english
- I have only one module language switcher. This module is displayed on all the pages and the language parameter is configured to "all languages"
- The system plugin filter lang is configured like this: Remove the language code from the URL: YES
- My url look like:
https://www.memozor.com/memory-games
https://www.memozor.com/fr/jeux-de-memory

### Expected result

But I have only ONE PROBLEM (BUG?) that I had not noticed until now!
When I'm on a page of the site in the language which is not the default one (for example https://www.memozor.com/fr/jeux-de-memory) the link toward the associated page in the language selector has a prefix /en/ in the url (https://www.memozor.com/en/memory-games) while English is the default language.
It took me a long time to notice this problem because when I click on the english flag, joomla automatically redirects this url to the correct url (https://www.memozor.com/memory-games). So the problem is invisible for a simple user, but not for googlebot!

### Additional comments

The redirections are not a good practice SEO. So I would like to correct this problem because I don't want to be penalized in terms of SEO.

**Comment by HLeithner** [comment]
We need this redirect to set the new language for the current user session.

You can add the /en/ to the English version then you don't have an additional redirect.

I'm closing this because there is nothing we can't do about this, feel free to comment or reopen it.

**Comment by infograf768** [comment]
@emma113140 
Please do not post all over the place.
I have replied to you both in the French Forum and in https://forum.joomla.org/viewtopic.php?f=711&t=977013#p3591690
