### ISSUE TITLE
[4.0] Edit Module Settings from menu item

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27450]
### Steps to reproduce the issue
Open any menu item 
Go to the module assignment tab
Click on any of the module titles

### Expected result
Module opens (in a  modal?) for editing

### Actual result
Nothing

**Comment by Quy** [comment]
See PR #23609

**Comment by brianteeman** [comment]
looks like that pr needs a new owner as it has been abandoned

**Comment by Quy** [comment]
See PR #27455
