### ISSUE TITLE
[4.0] Autoload Libraries/Media namespace not working

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#27459]
### Steps to reproduce the issue

Install a libraries plugin or media plugin.

example: [Kunena 6.0 Libraries](https://www.kunena.org/lib_kunena_v6.0.0-ALPHA6-DEV.zip)

on kunena.xml file has

````
<namespace>Kunena\Forum\Libraries</namespace>
````

### Expected result

autoload_psr4.php has the libraries namespace.

### Actual result

No libraries or media dir has been added to the autoload_prs4.php file.

other namespaces has been added:
````
'Kunena\\Forum\\Site\\' => [JPATH_SITE . '/components/com_kunena/'],
'Kunena\\Forum\\Api\\' => [JPATH_API . '/components/com_kunena/'],
'Kunena\\Forum\\Administrator\\' => [JPATH_ADMINISTRATOR . '/components/com_kunena/'],
'Kunena\\Forum\\Plugin\\Kunena\\Altauserpoints\\' => [JPATH_PLUGINS . '/kunena/altauserpoints/'],
'Kunena\\Forum\\Plugin\\Kunena\\Community\\' => [JPATH_PLUGINS . '/kunena/community/'],
'Kunena\\Forum\\Plugin\\Kunena\\Comprofiler\\' => [JPATH_PLUGINS . '/kunena/comprofiler/'],
'Kunena\\Forum\\Plugin\\Kunena\\Finder\\' => [JPATH_PLUGINS . '/kunena/finder/'],
'Kunena\\Forum\\Plugin\\Kunena\\Gravatar\\' => [JPATH_PLUGINS . '/kunena/gravatar/'],
'Kunena\\Forum\\Plugin\\Kunena\\Joomla\\' => [JPATH_PLUGINS . '/kunena/joomla/'],
'Kunena\\Forum\\Plugin\\Kunena\\Kunena\\' => [JPATH_PLUGINS . '/kunena/kunena/'],
'Kunena\\Forum\\Plugin\\Quickicon\\Kunena\\' => [JPATH_PLUGINS . '/quickicon/kunena/'],	
'Kunena\\Forum\\Plugin\\System\\Kunena\\' => [JPATH_PLUGINS . '/system/kunena/'],
````

Also i tried on system plugin:

````
class plgSystemKunena extends CMSPlugin
{
	/**
	 * Method to register custom library.
	 *
	 * return  void
	 */
	public function onAfterInitialise()
	{
		\JLoader::registerNamespace('Kunena\\Forum\\Libraries', JPATH_LIBRARIES . '/kunena/');
	}
}
````

### System information (as much as possible)

4.0-dev git

**Comment by SharkyKZ** [comment]
Right, currently namespace mapper doesn't support libraries.

The plugin method should work but you need to pass the autoloading type (`psr4`) . `JLoader::registerNamespace()` doc block says it should default to `psr4` in 4.0 but that hasn't been done yet.

Note, autoloading is based on filesystem. Directory/file casing must match class names otherwise the code will fail on case sensitive filesystems (Linux).

**Comment by SharkyKZ** [comment]
Please test PR #27479.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27459">issues.joomla.org/tracker/joomla-cms/27459</a>.</sub>
