### ISSUE TITLE
Get module parameters

### ISSUE THREAD

**Issue by PedroFLCorreia** [joomla/joomla-cms#27453]
### Steps to reproduce the issue

I am working on a web site on localhost, had the site in version 2.5.28 so decided to upgrade to version 3.6.5. When I upgraded while accessing the site products, I got the following error.

### Expected result

I expected to see the product list on the site.

### Actual result

PHP Fatal error:  Call to a member function get() on string in D:\Utilizadores\DELL-Pedro\Desktop\trabalho\loja_vitorino\libraries\src\Helper\ModuleHelper.php on line 229

### System information (as much as possible)

PHP Fatal error:  Call to a member function get() on string in BASEDIR\libraries\src\Helper\ModuleHelper.php on line 225

PHP 5.6.3
JOOMLA 3.9.13

### Additional comments

I debugged the error, basically what is happening is that I initialize an instance of a Registry object. When I use the instance to call the get () method, it unlocks the above error.

After doing:
// Get module parameters
$ params = new Registry ($ module-> params);

error_log (json_encode ($ params)); -> give me {}

Hence give the following error, why the new Registry does not return the object to me? why give me the same that new StdClass???

The code presented in this post is from joomla source, I didn't make any changes, just to debug the error.

Can you help me?

**Comment by PedroFLCorreia** [comment]
I find a bug in your tracker report

See attachment<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27453">issues.joomla.org/tracker/joomla-cms/27453</a>.</sub>

**Comment by richard67** [comment]
Which attachment?

**Comment by PedroFLCorreia** [comment]
More an bug in google chrome. I dont can do upload attachment<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27453">issues.joomla.org/tracker/joomla-cms/27453</a>.</sub>

**Comment by joomdonation** [comment]
This happens with upgrading from Joomla 2.5 to a very old version of Joomla 3. There is no way for us to re-procedure/see the problem on Joomla 4 to confirm or fix it. Therefore, I'm closing this issue.
