### ISSUE TITLE
[4.0] TinyMCE editor.css

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27475]
### Steps to reproduce the issue
Tinymce will load the contents of the editor.css file found in templates/system

By doing this we get various styling applied to the tinymce dropdown menus AND to the pagebreak and readmore lines

The last few lines of that file are
https://github.com/joomla/joomla-cms/blob/0f16a077ffd9874d48d6bd3602719db732620662/templates/system/css/editor.css#L53-L59

Yet only two of those are in the menu
![image](https://user-images.githubusercontent.com/1296369/72204817-fd133800-3473-11ea-98fd-15e377a9cca7.png)

And the last  one is not usable

**Comment by Fedik** [comment]
interesting, if make it `.system-pagebreak { border: gray dashed 1px; color: gray; } ` then it work

upd, I suspect because hr cannot have a content/text, so it not possible to be used in this way,
it somehow need to be hidden from the menu? maybe

**Comment by brianteeman** [comment]
updating to tinymce 5.1 it now has the disabled icon on the hr which resolves that issue

![image](https://user-images.githubusercontent.com/1296369/72349841-30083680-36d5-11ea-93c7-c998a764ff27.png)

Still raises the question about the others which all have a space in them

**Comment by Quy** [comment]
Please confirm it is no longer an issue. Thanks.

![27475](https://user-images.githubusercontent.com/368084/92330386-622f2580-f023-11ea-93e4-1c3db10bdbc2.png)

**Comment by Fedik** [comment]
btw, please try change to:
```css
body  hr#system-readmore  { border: red dashed 1px; color: red; } 
body  hr.system-pagebreak { border: gray dashed 1px; color: gray; } 
```
then it should disappear from the menu, in theory

**Comment by Quy** [comment]
Please test PR #31828

**Comment by brianteeman** [comment]
Completely unrelated to that PR as this is for the editor.css file located in templates/system and is not dependant on the frontend template

**Comment by Quy** [comment]
Is this still an issue?

**Comment by brianteeman** [comment]
fixed elsewhere
