### ISSUE TITLE
Searching on the content of the fields

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#27483]
### Steps to reproduce the issue

Search for the word "Joomla" in the Joomla Search. Crate article having that word in their Custom Fields

### Expected result

By default, the Search does also cover Custom Fields. If you search for the word "Joomla" in the Joomla Search Engine, you will find any Article having that word in their Custom Fields

### Actual result

0

### System information (as much as possible)

Joomla 3.9.14

**Comment by Quy** [comment]
Duplicate #17294 ?

**Comment by ghost** [comment]
Thanks Quy it seems similar BC bug is in joomla for 3 years, and still joomla is promissing that by default, the Search does also cover Custom Fields, so is it or not, maybe we need to update documentation on this issue?

**Comment by SharkyKZ** [comment]
Can't reproduce this issue. Are you using regular Search (com_search) or Smart Search (com_finder)?

**Comment by Quy** [comment]
@Milglius Can't reproduce either. Please advise which search type you are using.

**Comment by ghost** [comment]
using regular Search (com_search) does it work on Smart Search (com_finder)?

**Comment by Quy** [comment]
@Milglius It works in both. Please try again and see if you can reproduce it.

**Comment by ghost** [comment]
tried again it doesnt work in j 3.9.15

what seetings you have that you get results from searching on the content of the fields?

**Comment by Quy** [comment]
Here is what I did:

* Created a text field. 
* In 2 articles, entered `Quy` in this custom text field. 
* On the frontend, searched `Quy` and these 2 articles appeared in the search results.

Please advise steps you did.

**Comment by ghost** [comment]
Here is what I did:

    Created a list field.
    In 2 articles, entered Quy in this custom list field.
    On the frontend, searched Quy and these 2 articles have not appeared in the search results.

    Created a integer field.
    In 2 articles, entered integer in this custom integer field.
    On the frontend, searched these integer and these 2 articles have not appeared in the search results.

**Comment by Quy** [comment]
I did as you described and search results returned as expected. Can you test on a clean install?

**Comment by Bakual** [comment]
List fields are searchable, but keep in mind that it will search the value, not the text of the selected option.
For the integer, keep in mind that you need at least 3 digits to search. So "99" will not work, but "100" will work.

**Comment by Quy** [comment]
Closing as not reproducible.
