### ISSUE TITLE
[4.0] Plugin ordering field

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27514]
There are two visible issues with this field although I suspect that they are the result of a deeper issue with the field type.

### 1. Accessibility
As can be seen in the generated code below the select has the wrong id - it should be the same as the `for` attribute in the label.

```
	<div class="control-label"><label id="jform__ordering-lbl" for="jform__ordering">
	Ordering</label>
</div>
	<div class="controls has-success">
		<select id="jformordering" name="jform[ordering]" class="custom-select valid form-control-success" aria-invalid="false">
```

### 2. Numbers
Unlike similar ordering fields this one has a first and a last entry but you will notice that they are without a period after the number

![image](https://user-images.githubusercontent.com/1296369/72332396-df331680-36b1-11ea-8428-19d67477161d.png)

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/27582.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27514">issues.joomla.org/tracker/joomla-cms/27514</a>.</sub>
