### ISSUE TITLE
4.0 joomla frontend articles filter by custom fields

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#27527]
### Is your feature request related to a problem? Please describe.

its not posible to core 3.9.14 joomla user in frontend article filter by custom fields

### Describe the solution you'd like

4.0 joomla frontend article filter by custom fields

user in frontend filter articles by custom fields

**Comment by brianteeman** [comment]
closing as a duplicate<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27527">issues.joomla.org/tracker/joomla-cms/27527</a>.</sub>

**Comment by ghost** [comment]
Brian where is a duplicate?

**Comment by SharkyKZ** [comment]
#26258.

**Comment by ghost** [comment]
thank you SharkyKZ
