### ISSUE TITLE
Remove Privacy Notice "Next" and "Prev" Buttons

### ISSUE THREAD

**Issue by jwaisner** [joomla/joomla-cms#27525]
### Steps to reproduce the issue

Enable Content - Confirm Consent plugin and assign a privacy article.
Go to a contact form.
Click on Privacy Note.

"Next" and "Prev" buttons appear and if clicked redirect to the home page inside the Modal(prostar) or on contact page (Beez3)

![privacy notice](https://user-images.githubusercontent.com/12568201/72389652-803fc280-36ee-11ea-8e34-fac32ef8646d.jpg)

### Expected result

Privacy Article displays but does not include "Next" or "Prev"

### Actual result

"Next" and "Prev" buttons appear and if clicked redirect to the home page inside the Modal(prostar) or on contact page (Beez3)

**Comment by brianteeman** [comment]
I am not sure that this is something that we can do programatically for this specific use case. However you can disable the navigation on a per article basis so its easy to resolve

![image](https://user-images.githubusercontent.com/1296369/72390426-9798a300-3722-11ea-8e17-8dc7752aa96a.png)

**Comment by jwaisner** [comment]
Understood. Closing at "Not A bug"
