### ISSUE TITLE
4.0 joomla Frontend image upload using mobile phone

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#27522]
### Is your feature request related to a problem? Please describe.

joomla Frontend image upload using mobile phone

### Describe the solution you'd like

Frontend joomla with image upload TinyMCE 5.1 mobile UI with sticky toolbar allows toolbar to remain in view when editing large text areas.

**Comment by brianteeman** [comment]
the pull request to update to tinymce 5.1 is already created<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27522">issues.joomla.org/tracker/joomla-cms/27522</a>.</sub>

**Comment by ghost** [comment]
Brian does this pull includes joomla Frontend tinyMCE 5.1 mobile UI with sticky toolbar allows toolbar to remain in view when editing large text areas?
