### ISSUE TITLE
[4.0] [backend-template] Mobile menu icon

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#27532]
### What needs to be fixed

On mobile, the button to show the main menu has an "X" icon.
This does not signify that it should open a menu, but instead looks like a button to close/delete something.

![screeny3](https://user-images.githubusercontent.com/2019801/72426846-6b147380-3782-11ea-8f6d-bbe04b2d77af.png)

**Comment by brianteeman** [comment]
its a bug - probably caused by me trying to do stuff that I dont have the skills to do but those that do, dont

**Comment by Quy** [comment]
See #27705
