### ISSUE TITLE
[4.0] [backend-template] Colour swatch toggle cursor

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#27538]
### Steps to reproduce the issue

1. To go the Template Manager
2. Open Atum
3. Go to the "Colour Settings" tab
4. Hover over coloured squares to the left of the HEX value (shown in screenshot)

### Expected result

A default or pointer cursor

### Actual result

A text cursor

![screeny2](https://user-images.githubusercontent.com/2019801/72429118-1a534980-3787-11ea-8b67-bdb7ec698126.png)

**Comment by brianteeman** [comment]
that is the setting of the plugin

https://labs.abeautifulsite.net/jquery-minicolors/#demos

**Comment by C-Lodder** [comment]
Yup. But seeing as the last release of jQuery MiniColor was in Dec 2018, I assume they won't be patching this, so may have to be fixed here

**Comment by brianteeman** [comment]
i dont even know why we are still using it

**Comment by C-Lodder** [comment]
Hopefully #25162 gets resurrected

**Comment by brianteeman** [comment]
The code to change this is easy - I just dont know where to put it

```
span.minicolors-swatch-color {
    cursor: pointer;
}
```

**Comment by brianteeman** [comment]
> Hopefully #25162 gets resurrected

The code is still there but the lack of support for transparency in the native color pickers seems to have killed it

**Comment by C-Lodder** [comment]
> administrator\templates\atum\scss\vendor\minicolors\minicolors.scss

**Comment by brianteeman** [comment]
The front end would need it as well

**Comment by C-Lodder** [comment]
> templates\cassiopeia\scss\vendor\_minicolors.scss

**Comment by brianteeman** [comment]
Not a fan. Third party templates need it too

**Comment by C-Lodder** [comment]
> build\media_source\system\scss\_jquery-minicolors.scss

**Comment by brianteeman** [comment]
thanks - will do it after the flight - this scss isnt being generated at the moment :(<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27538">issues.joomla.org/tracker/joomla-cms/27538</a>.</sub>

**Comment by N6REJ** [comment]
@brianteeman according to https://github.com/Simonwep/pickr pickr is fully accessible

**Comment by brianteeman** [comment]
It is absolutely not accessible with a screen reader

**Comment by simonwep** [comment]
@brianteeman Maintainer of pickr here 👋
Accessibility was discussed in this [thread](https://github.com/Simonwep/pickr/issues/11) which was closed and required features implemented by @NateSeymour. lacymorrow also tested it with the Google's Accessibility Developer Tools [here](https://github.com/Simonwep/pickr/issues/167) and added missing features in [this PR](https://github.com/Simonwep/pickr/pull/168).

I myself, and my fellow maintainer, are not experts in accessibility - although we try our best to make it as accessible as possible. If you encounter any issues or got ideas of how to improve it you may want to add a comment to [this issue](https://github.com/Simonwep/pickr/issues/11) and I'll reopen it 😊

**Comment by brianteeman** [comment]
@Simonwep Thanks for taking the time to pop in and comment. I will comment more in depth on your own site. For the benefit of casual observers - passing automated tests does not make anything accessible. They only report on the things that can be tested automatically. For example they cannot report on the ability to  move from A to B etc.

**Comment by brianteeman** [comment]
@Simonwep comment and suggestion added here https://github.com/Simonwep/pickr/issues/11#issuecomment-582009375

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #27829
