### ISSUE TITLE
[4.0] [backend-template] Mobile toolbar height

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#27534]
### Steps to reproduce the issue

1. Go to any list or edit view in the backend
2. Reduce viewport down to a mobile size

The toolbar container is overlapping the main content. To get a better view of what the user is look at, they have to keep collapsing the toolbar.....poor UX

![screeny6](https://user-images.githubusercontent.com/2019801/72427628-1245da80-3784-11ea-8de2-f0f66e5314d0.png)

I'd suggest redesigning the toolbar for mobile

**Comment by brianteeman** [comment]
It really should be collapsed by default and not open by default

**Comment by brianteeman** [comment]
again probably caused by me trying to do stuff that I dont have the skills to do but those that do, dont

**Comment by C-Lodder** [comment]
Worst scenario I could find is when you try and edit a file via the template manager
![toolbar](https://user-images.githubusercontent.com/2019801/82565712-c8766200-9b72-11ea-991d-cdb2e75cac41.png)

**Comment by Quy** [comment]
Please test PR #30131
