### ISSUE TITLE
[4.0] [backend-template] Space between tabs on hover

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#27533]
### What needs to be fixed

1. In the backend, go to edit any user
2. Reduce viewport width to a mobile size
3. Hover over any of the blue tabs at the bottom of the page (as per screenshot)

Note the space inbetween the tabs on hover

### Why this should be fixed

Looks weird

![screeny4](https://user-images.githubusercontent.com/2019801/72427236-3bb23680-3783-11ea-99bd-96d36134017e.png)

**Comment by brianteeman** [comment]
It wasn't actually a space it was the wrong colour ;)

See #27860
