### ISSUE TITLE
[4.0] [backend-template] Missing language string com_finder

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#27539]
### Steps to reproduce the issue

1. Go to `administrator/index.php?option=com_finder&view=index`
2. Click the "Index" button in the toolbar

You will notice a missing language string in the modal head, as per my screenshot

![screeny3](https://user-images.githubusercontent.com/2019801/72430057-496aba80-3789-11ea-949c-cadeaa26ba54.png)

**Comment by brianteeman** [comment]
The language string is present :(
I am going to take an educated  guess that the problem lies in the code for `appendButton('Popup'` as the only place this problem occurs is when this code is used

**Comment by brianteeman** [comment]
Please test #27542<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27539">issues.joomla.org/tracker/joomla-cms/27539</a>.</sub>
