### ISSUE TITLE
[4.0] [backend-template] Top nav click event

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#27530]
### Steps to reproduce the issue

In the admin backend, reduce your viewport width so that the top-right nav displays a blue button (as per the screenshot below)

Clicking it opens a dropdown.

Normally you'd expect clicking anywhere on the screen to hide the dropdown, but you have to click on the blue button agin to hide it.

Being able to click anywhere on the screen improves the UX and is the behaviour for all other dropdowns on the dashboard.

![screeny](https://user-images.githubusercontent.com/2019801/72425852-78306300-3780-11ea-9058-19887e09ab71.png)

**Comment by Subhang23** [comment]
I am working on it

**Comment by Quy** [comment]
Please test PR #27895

**Comment by richard67** [comment]
Closing as having a pull request. Please test #31730 . Thanks in advance.
