### ISSUE TITLE
[4.0] [backend-template] Media Manager unusable on mobile

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#27537]
### Steps to reproduce the issue

View the Media Manager on a mobile or reduce viewport width
It's completely unusable.

![screeny](https://user-images.githubusercontent.com/2019801/72428801-5639df00-3786-11ea-8cbe-9b105ef33a68.png)

**Comment by AndyGaskell** [comment]
With the CSS tweak like...
`.media-browser-item-preview {
    font-size: 20px;
}`
...it would be better
![Screen Shot 2020-01-19 at 14 37 06](https://user-images.githubusercontent.com/91541/72682830-4ba28100-3ac9-11ea-91dd-5931d88def8b.png)

**Comment by AndyGaskell** [comment]
Just looking at the code to do a PR

**Comment by AndyGaskell** [comment]
I think making it 10vw may be the best option, just doing some testing.

**Comment by Quy** [comment]
> I think making it 10vw may be the best option, just doing some testing.

See #27536

**Comment by AndyGaskell** [comment]
See #27537 after change it looks like...
![Screen Shot 2020-01-19 at 18 20 50](https://user-images.githubusercontent.com/91541/72686133-45240180-3ae9-11ea-8861-de5170ab0ee5.png)

**Comment by Subhang23** [comment]
I would like to work on this.

**Comment by Quy** [comment]
Please test PR #31140
