### ISSUE TITLE
[4.0] [backend-template] Modal not central on mobile

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#27536]
### Steps to reproduce the issue

1. Go to the admin dashboard
2. Reduce viewport width down to a mobile size
3. Click the "Add module to the dashboard" button at the bottom of the page

### Expected result

Horizontally aligned modal

### Actual result

Modal aligned to the left

![screeny](https://user-images.githubusercontent.com/2019801/72428234-2938fc80-3785-11ea-809e-9b869fac3054.png)

**Comment by anirudhsingh20** [comment]
Hi, I am Anirudh how can I understand the codebase and contribute?

**Comment by brianteeman** [comment]
weird but its a bootstrap intended behavioour

See pull request #27859
