### ISSUE TITLE
[4.0] [backend-template] Toolbar toggle button overlapping main menu

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#27535]
### Steps to reproduce the issue

1. Go to any list view in the backend...such as Article Manager
2. Reduce viewport down to mobile size
3. Open the main menu

### Expected result

The button to toggle the toolbar menu shouldn't be visible

### Actual result

The button to toggle the toolbar menu **is** visible

![screeny7](https://user-images.githubusercontent.com/2019801/72427889-99934e00-3784-11ea-98ef-083674748bcb.png)

**Comment by brianteeman** [comment]
I assume its a zindex issue?
Pull Requests welcome

**Comment by Quy** [comment]
See #27705
