### ISSUE TITLE
[4.0] [backend-template] Postinstallation messages dropdown padding

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#27541]
### Steps to reproduce the issue

1. Go to the `#__postinstall_messages` table
2. Replace any of the language constants in the `title_key` column with a faily long string.
3. Go to the Joomla backend and open the "Post Installation Messages" dropdown

You'll notice there's no right padding on the items (see screenshot below)

I'm using the Post Installation Message in this example as they're dynamic and extension developers can add their own, but it applies to all dropdown items in the `<header>`

![screeny2](https://user-images.githubusercontent.com/2019801/72430953-85068400-378b-11ea-9b10-2010dffed511.png)

**Comment by N6REJ** [comment]
question is is what behavior on overflow?  "Normal" solution is to wrap

**Comment by SharkyKZ** [comment]
Please test PR #27586.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27541">issues.joomla.org/tracker/joomla-cms/27541</a>.</sub>
