### ISSUE TITLE
[4.0] [backend-template] Custom select missing icon on focus

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#27543]
### Steps to reproduce the issue

1. Go to `/administrator/index.php?option=com_postinstall`
2. Look at the `Showing messages for` dropdown
3. Click it

You'll notice the arrow icon disappears

![screeny3](https://user-images.githubusercontent.com/2019801/72441217-2f89a180-37a2-11ea-98dc-bbc15bb58b67.png)

**Comment by brianteeman** [comment]
There is a pr for this

**Comment by C-Lodder** [comment]
Do you mean this one? https://github.com/joomla/joomla-cms/pull/27487

**Comment by brianteeman** [comment]
yes<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27543">issues.joomla.org/tracker/joomla-cms/27543</a>.</sub>

**Comment by C-Lodder** [comment]
That fixes custom selects with the `.active` class. This is a different issue

**Comment by C-Lodder** [comment]
The problem here isn't the icon itself. That still exists, but instead it's the background of the square which changes to white, thus you can't see it.

**Comment by brianteeman** [comment]
Pull requests welcome.

**Comment by N6REJ** [comment]
@C-Lodder the problem is .form-control:focus background.  As soon as I can find the dang thing I'll create a pr

**Comment by Quy** [comment]
Remove `form-control` to fix the issue.

`<select id="eid" name="eid" onchange="this.form.submit()" class="form-control custom-select">`

**Comment by N6REJ** [comment]
@Quy yep, I JUST saw that after comparing it to others.  You wanna do a pr?

**Comment by Quy** [comment]
Please test PR #27544

**Comment by N6REJ** [comment]
lol you beat me to it.
