### ISSUE TITLE
[4.0] System Information

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27553]
Since the change in global configuration to use True/False instead of 1/0 the display of the system information missing some important information

![image](https://user-images.githubusercontent.com/1296369/72605721-37b61e00-3915-11ea-9b66-6512d082204d.png)

Basically anything with a value of false doesnt display anything

**Comment by jwaisner** [comment]
Confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27553">issues.joomla.org/tracker/joomla-cms/27553</a>.</sub>

**Comment by infograf768** [comment]
Maybe we could do
```
diff --git a/administrator/components/com_admin/tmpl/sysinfo/default_config.php b/administrator/components/com_admin/tmpl/sysinfo/default_config.php
index 16f0764..6796ac7 100644
--- a/administrator/components/com_admin/tmpl/sysinfo/default_config.php
+++ b/administrator/components/com_admin/tmpl/sysinfo/default_config.php
@@ -36,4 +36,5 @@
 					</th>
 					<td>
+						<?php $value === false ? $value = Text::_('JNO') : $value; ?>
 						<?php echo htmlspecialchars($value, ENT_QUOTES); ?>
 					</td>
```
(`Text::_('JNO')` can be replaced by `'0'`) but I was also thinking that we could go further and also add
`<?php $value === 1 || $value === true ? $value = Text::_('JYES') : $value; ?>`

To get a readable value.

**Comment by mbabker** [comment]
I’d almost say it should print true/false over Yes/No so it matches the value in the config file.  Basically `if (is_bool($foo)) { echo $foo === true ? 'true' : 'false'; }`.

**Comment by Quy** [comment]
Please test PR #27588
