### ISSUE TITLE
Filter for filelist field type doesn't work

### ISSUE THREAD

**Issue by webchun** [joomla/joomla-cms#27550]
### Steps to reproduce the issue
I have these css files in the folder _foldername/subfoldername_ :
- style1.css
- style1.min.css
- style2.css
- style2.min.css

I created a new field in my custom module backend as below :
`<field name="fieldname" type="filelist" default="default.min" label="Field label" description="Field Desc" directory="foldername/subfoldername" filter="min.css" exclude="" stripext="true" hide_none="true" hide_default="true" />`

### Expected result

The dropdown shows *.min.css files only :
- style1.min
- style2.min

### Actual result
The dropdown showed all files :
- style1.css
- style1.min.css
- style2.css
- style2.min.css

### System information (as much as possible)

Joomla ‎4.0.0-alpha12

**Comment by SharkyKZ** [comment]
In 4.0 the attribute for filtering files has been renamed to `fileFilter` to resolve conflict with `filter` attribute used for filtering form input.

Related documentation:

> https://docs.joomla.org/Filelist_form_field_type
> https://docs.joomla.org/Folderlist_form_field_type
> https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4#Form

**Comment by Quy** [comment]
@webchun Be sure to test with the nightly builds. https://developer.joomla.org/nightly-builds.html

**Comment by webchun** [comment]
> In 4.0 the attribute for filtering files has been renamed to `fileFilter` to resolve conflict with `filter` attribute used for filtering form input.

Ok it's working good with fileFilter
