### ISSUE TITLE
[4.0][CSS] Old floating hack still used with 'control-group' fields 

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#27558]
The CSS for the control-group field (most Joomla fields) uses an old floating hack to align the label with the field. I presume this is something that predates even J3. Basically it floats the label to take it out of the flow of the page and then places a left margin on the field to give it a fixed inset width. I propose moving them to use flex instead. It is a typical scenario flex is used designed for.

- Less CSS required
- Flex naturally supports RTL so no RTL CSS required.
- Media queries look at the width of the viewport and are the only way to change the orientation of the current control-group fields. Flex would allow us to change the orientation of the field depending on the space available to it. A much more versatile and safer way to approach responsive fields especially.

It is a change that would touch a large part of the Joomla UI so I am reluctant in making such a change without bringing it up as an issue first. Maybe there is a reason this wasn't done before that I am unaware of?

**Comment by SharkyKZ** [comment]
That would be great. Does this require much change in HTML markup? Or are changes mostly limited to CSS?

**Comment by Fedik** [comment]
that would be cool to fix :wink:

**Comment by ciar4n** [comment]
> Does this require much change in HTML markup? Or are changes mostly limited to CSS?

No change required in the HTML. Change would be CSS only.

**Comment by ciar4n** [comment]
PR created... #27684
