### ISSUE TITLE
[4.0] Cassiopea: banner display totally broken

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#27565]
### Steps to reproduce the issue
Create a banner. Define the image size.
Create a Banner module, define a class for the module, assign to banner position.

### Expected result
The size of the image should be respected for display.
The module class should be used.

### Actual result
None of the above... 
Even if `grid-child container-banner` is corrected with dev tools, the svg (in the `<div class="header-shape-bottom">`) hides part of the banner.

<img width="1299" alt="Screen Shot 2020-01-19 at 10 23 49" src="https://user-images.githubusercontent.com/869724/72678403-d5405780-3aa5-11ea-9e04-3f239800f6ec.png">

Definitely a release blocker.

**Comment by ciar4n** [comment]
PR... #27566

**Comment by infograf768** [comment]
Works. Commented there. Until we decide what to do with module class I leave this open and take off release blocker.

**Comment by infograf768** [comment]
Closing as we have #27566
