### ISSUE TITLE
Routing issue in the Archived articles module (SEF)

### ISSUE THREAD

**Issue by kofaysi** [joomla/joomla-cms#27578]
### Steps to reproduce the issue

Publish Archived articles and archive some articles.

Choose a specific months in the list of links and display the list of articles.

### Expected result

The links shall list articles for a the specific months of a specific year.

### Actual result

The links list every archived article with publish date in May month (2019, 2018, 2017,...).

### System information (as much as possible)

J3.9.14

The links in the module for "Months Year" (example "May 2019") look like:
https://blah-blah/archived/2019?view=archive&month=5
And they list every archived article published in month May in every available year (2019, 2018,...). 

The selector is set to any Year by the link:
![image](https://user-images.githubusercontent.com/17022173/72707078-e2ba1800-3b5f-11ea-9ff6-fd5c0931fb4f.png)

With `Search Engine Friendly URLs` global option set to Off, the links look like
https://blah-blah/index.php?option=com_content&view=archive&year=2019&month=5
And they list the specific months of a year.

### Additional comments

https://github.com/joomla/joomla-cms/issues/6745
https://github.com/joomla/joomla-cms/issues/19382

**Comment by brianteeman** [comment]
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed. 

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
