### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#27576]
### Steps to reproduce the issue
Navigate to Uncategorised Category Permissions
Observe Author Edit is Not Allowed (Inherited)
Observer Editor Edit is Allowed (Inherited)

In Global config Permissions set Editor Edit from Allowed to Inherited.  Global Editor Edit will show Not Allowed (Inherited.  But Uncategorised Category Editor Edit remains Allowed (Inherited)

### Expected result
By default Uncategorised Category Editor Edit should be Allowed instead of Allowed (Inherited).
When global config Editor Edit is changed to Not Allowed (Inherited) the corresponding value in Category Editor Edit should be the same

### Actual result
Global Editor Edit will show Not Allowed (Inherited).  But Uncategorised Category Editor Edit remains Allowed (Inherited)

### Additional comments

Methinks it is just the wrong icon being displayed rather than the actual setting.

**Comment by mbabker** [comment]
Check the component and any parent category settings.  Inherited means from any parent in the ACL tree, not just the global config.

**Comment by Webdongle** [comment]
I have and the (direct Parent) has Not Allowed(Inherited).
All the other Categories have 
Author Edit is Not Allowed (Inherited)
Editor Edit is Not Allowed (Inherited)

Global has 
Author Edit is Not Allowed (Inherited)
Editor Edit is Not Allowed (Inherited)

Articles in Uncategorised show 
Editor Edit is Allowed (Inherited)

Change Global
to
Editor Edit Allowed
Then
Uncategorised Editor Edit calculated value remains  Not Allowed (Inherited)
But all the other Categories (that are not children of Uncategorised) the calculated value changes to Allowed

If you set (in Global) Editor Allowed a user in that group is unable to edit an Article in. Uncategorised.

**There is definitely something wrong with the calculated value in uncategorised.**

**Believe me I understand the hierarchy of the Permissions and there is an error.**

**Comment by Webdongle** [comment]
Have also checked 
Uncategorised Editor 'Edit State'
Same error
Change in Global to 'Edit State'
In Uncategorised the calculated value remains Allowed (Inherited) instead of changing to just Allowed.
Also a logged in user of that group is unable to see Unpublished Articles.

The Calculated settings in Uncategorised Permissions that are set Allowed (Inherited) are preventing Global (manually set) Allowed from being recognised by the Article.

**Comment by mbabker** [comment]
This sounds like the com_content ACL might have something configured to override the global settings to me.  I'm having a hard time following all the text blobs, but if you're saying that the global level editors don't have edit permissions but on the "Uncategorised" category in com_content they do have edit permissions, then the likely cause is there is an explicit allow in the com_content settings for editors.

I checked a couple of sites that I know that ACL hasn't been edited on.  On both of those sites, there is an explicit allow for the default Editors group in both the global configuration and the com_content configuration.  So if you're changing the global setting, then the component level setting is still overriding the global setting.  Check the component setting and if that has an explicit allow, set it to inherited and see what happens.

**Comment by Webdongle** [comment]
This is strange
When opening Uncategorised for editing I had the warning
'JUser: :_load: Unable to load user with ID: 64'
Changed the 'Created by 64' to my su user and everything is OK

Either I was mixing too many tabs or something strange went on when I updated the site.
