### ISSUE TITLE
CHMOD rights on index files and question about updating Joomla

### ISSUE THREAD

**Issue by ZerooCool** [joomla/joomla-cms#27574]
I put my index files in 444 on the whole site.
When updating languages, I get the following error.

Do I hurt to put my indexes in 444?
Should I have done other than give the files to www-data: www-data?

I thought I would do well by passing the indexes to 444 but I hadn't thought that the updates would want to rewrite the indexes.

Erreur de copie : /var/www/html/tmp/install_5e24aea74d468/install_5e24aea7648bf/index.html vers /var/www/html/administrator/language/fr-FR/index.html
JInstaller: :Install: échec de la copie du fichier /var/www/html/tmp/install_5e24aea74d468/install_5e24aea7648bf/index.html vers /var/www/html/administrator/language/fr-FR/index.html

Two affected files :
/var/www/html/language/fr-FR/index.html
/var/www/html/administrator/language/fr-FR/index.html

To update I had to go back to 755.

**Comment by Quy** [comment]
Please ask help regarding migrating/upgrading in Joomla Forum. https://forum.joomla.org/viewforum.php?f=710
