### ISSUE TITLE
[4.0] Wrong permission check for "Save2Menu"

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#27581]
### Steps to reproduce the issue
Create a user which isn't allowed to create new menuitems, but is allowed to create new articles

### Expected result
The button "Save2Menu" doesn't show in the article form

### Actual result
Button shows

### Additional comments
I haven't tested this but stumbled over the code while writing my own extension.
Code is in https://github.com/joomla/joomla-cms/blob/8b5034f169ef14c3382d0fb4fd493089f0d00b7d/administrator/components/com_content/View/Article/HtmlView.php#L155 and https://github.com/joomla/joomla-cms/blob/8b5034f169ef14c3382d0fb4fd493089f0d00b7d/administrator/components/com_content/View/Article/HtmlView.php#L188-L190

If you look at it you see that the code just checks if the user is allowed to create in com_content. It should instead explicitely check against com_menus.

**Comment by infograf768** [comment]
Does it not need to be both, just for `save2menu`, `save2copy` needing only `core.create` ?

**Comment by Bakual** [comment]
save2copy can be done with $canDo->get('core.create') as currently done.
It's just the save2menu with needs an explicit check like
````
if ($user->authorise('core.create', 'com_menus.menu'))
{
	$childBar->save('article.save2menu', Text::_('JTOOLBAR_SAVE_TO_MENU'));
}
````
I haven't had time yet to test it, but that's what I think is the correct check.

**Comment by Bakual** [comment]
Closing as we have a PR: #27590
