### ISSUE TITLE
[4.0] Content Navigation

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27587]
The content navigation plugin doesn't work at all. Looks like an error in the query regarding workflows

**Comment by wilsonge** [comment]
I can't reproduce this. Sets up ok and menu on the right hand side as well as previous/next buttons in the main text both work ok

<img width="1280" alt="Screenshot 2020-01-26 at 00 28 22" src="https://user-images.githubusercontent.com/1986000/73129021-4023ee00-3fd2-11ea-9a77-ab8e869cec1d.png">

I used tiny - but here is the text in raw form so we can compare notes:

<img width="630" alt="Screenshot 2020-01-26 at 00 28 37" src="https://user-images.githubusercontent.com/1986000/73129032-4fa33700-3fd2-11ea-845b-731fc77bb559.png">

**Comment by brianteeman** [comment]
That's the page break stuff. I am talking about the next article link

**Comment by wilsonge** [comment]
Sorry can you show me a screenshot? I'm kinda confused

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/73139223-b7559280-4063-11ea-88c2-533bffd0f67f.png)

![image](https://user-images.githubusercontent.com/1296369/73139281-58444d80-4064-11ea-83a5-06672ec9f515.png)


In Joomla 3 that would produce the previous next buttons as shown below but in J4 nothing happens due to an error in the sql (i think)

![image](https://user-images.githubusercontent.com/1296369/73139284-61351f00-4064-11ea-80fa-eb7af455671f.png)

This is the query that I believe is wrong as if I remover the workflow related part of the query I do at least get values from that query
```
SELECT a.id, a.title, a.catid, a.language, CASE WHEN CHAR_LENGTH(a.alias) != 0 THEN CONCAT_WS(':', a.id, a.alias) ELSE a.id END AS slug, CASE WHEN CHAR_LENGTH(cc.alias) != 0 THEN CONCAT_WS(':', cc.id, cc.alias) ELSE cc.id END AS catslug
FROM c6cko_content AS a
LEFT JOIN c6cko_categories AS cc ON cc.id = a.catid
LEFT JOIN c6cko_workflow_stages AS ws ON ws.id = a.state
WHERE a.catid = 14 AND a.state = 1 AND a.access IN (1,1,5)  AND (ws.condition = 1 OR ws.condition = -2) AND (publish_up IS NULL OR publish_up <= '2020-01-26 17:51:10') AND (publish_down IS NULL OR publish_down >= '2020-01-26 17:51:10')
ORDER BY  CASE WHEN a.publish_up IS NULL THEN a.created ELSE a.publish_up END  DESC
```

**Comment by wilsonge** [comment]
Pretty sure the Joomla state should not be on the workflow stage - I guess it's a legacy of when we had bad naming on all that stuff and swagged stage/state around a bit

**Comment by brianteeman** [comment]
so you understand what I was referring to now?

I didnt contribute a fix as I'm not wasting my time if workflows is going to be pulled. Still waiting to see the report from fftf

**Comment by wilsonge** [comment]
PR here https://github.com/joomla/joomla-cms/pull/27871
