### ISSUE TITLE
[4.0] Users=>Permissions=>Call to a member function setName() on null

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#27594]
### Steps to reproduce the issue
Display user. Load Permissions. Filter by component.

### Result

Call to a member function setName() on null

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/27595.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27594">issues.joomla.org/tracker/joomla-cms/27594</a>.</sub>
