### ISSUE TITLE
[4] Fresh install Alpha 12 missing /libraries/autoload_psr4.php

### ISSUE THREAD

**Issue by stutteringp0et** [joomla/joomla-cms#27592]
### Steps to reproduce the issue
Fresh install Joomla_4.0.0-alpha12-Alpha-Full_Package.tar.bz2
Browse to site, 500 error.  Server error log reports:

> FastCGI sent in stderr: "PHP message: PHP Fatal error:  require(): Failed opening required '/var/www/html/development/4/libraries/autoload_psr4.php' (include_path='.:/usr/share/php') in /var/www/html/development/4/libraries/namespacemap.php on line 94" while reading response header from upstream, client: ::1, server: _, request: "GET /development/4/installation/index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "localhost"

### Expected result
installer page

### Actual result
500 error

### System information (as much as possible)
Ubuntu 19.10
PHP 7.3.11
NGINX 1.16.1

### Additional comments
Creating a symlink from /libraries/vendor/composer/autoload_psr4.php into /libraries resolves the issue.

**Comment by brianteeman** [comment]
it should be generated on first request. sounds like an issue with your server

**Comment by Quy** [comment]
Please test with the nightly builds. https://developer.joomla.org/nightly-builds.html

**Comment by stutteringp0et** [comment]
same thing with Joomla_4.0.0-beta1-dev-Development-Full_Package.zip

**Comment by stutteringp0et** [comment]
my bad.  fresh install, I doublechecked the permissions and everything went smoothly.  closing.
