### ISSUE TITLE
[4.0] JS error on fields

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27606]
### Steps to reproduce the issue
open the page showing the fields you have created for articles

`administrator/index.php?option=com_fields&view=fields&context=com_content.article`

### Expected result
no javascript errors

### Actual result
Console shows the following errror
```
Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at HTMLDocument.onSelect (batch-language.js?fd22800253b2f7b77f8bb448cfe50362:43)
onSelect @ batch-language.js?fd22800253b2f7b77f8bb448cfe50362:43

```

### System information (as much as possible)
php 7.4
mysql 8

**Comment by brianteeman** [comment]
If it helps with debugging the error doesn't appear until you have at least one field

**Comment by ankurshr01** [comment]
Can I work on this one?

**Comment by alikon** [comment]
@ankurshr01  yes please, 
you don't need to ask ;)

**Comment by Subhang23** [comment]
@alikon Can I work on this?

**Comment by Quy** [comment]
@Subhang23 Yes please. It is not necessary to ask for permission.

**Comment by Subhang23** [comment]
@Quz @alikon Can you review PR #27938
