### ISSUE TITLE
[4.0] Multiple Select lists

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27612]
I made a PR #25335 that makes sure that we are using the `joomla.form.field.list-fancy-select` layout when we have a **multiple** select list field.

@wilsonge closed it in the mistaken belief that you can do multiselects natively in the browser. Well you can do them but they look like hell as shown below.

### Before
![image](https://user-images.githubusercontent.com/1296369/60172060-d0fbd680-9803-11e9-8740-27eed67a6966.png)

### After
![image](https://user-images.githubusercontent.com/1296369/60172029-bd507000-9803-11e9-9876-a83c53d1db5b.png)

**Comment by jwaisner** [comment]
I agree @brianteeman. It looks much cleaner in the proposed change.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27612">issues.joomla.org/tracker/joomla-cms/27612</a>.</sub>

**Comment by brianteeman** [comment]
I would re-open the PR but it looks like because it was closed by a maintainer I cannot - @wilsonge please!!

**Comment by wilsonge** [comment]
I can't because it says it's been force pushed/recreated since it was closed

**Comment by wilsonge** [comment]
Tbh I'm really reluctant to reintroduce this everywhere. I want it still class based please. Not global select applying like we made the mistake with chosen

**Comment by brianteeman** [comment]
ok I will make a new PR

Can you still check that PR as I believe the approach there is correct

**Comment by wilsonge** [comment]
Ahh yes should be fine. sorry i should have re-reviewed before commenting rubbish

**Comment by brianteeman** [comment]
yes you should ;)

**Comment by brianteeman** [comment]
Closed see #27833
