### ISSUE TITLE
Message about an available update below the installed one

### ISSUE THREAD

**Issue by lesha73** [joomla/joomla-cms#27621]
Hello. Tell me why, after updating to the latest version of the program, there is a message that a new version is available, although it is lower than the installed now?
How to fix this issue?!
<img src="https://i.ibb.co/yVC1BwM/2020-01-24-17-07-57.png" alt="2020-01-24-17-07-57" border="0">

**Comment by alikon** [comment]
the bottom one is from a component K2 so not from the joomla core please ask to the extension developer

**Comment by lesha73** [comment]
The fact the version is listed at the top of the page is 3.9.13, and this is not the latest version, after clicking the "Update now" button, a page opens with a message that the latest version is installed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27621">issues.joomla.org/tracker/joomla-cms/27621</a>.</sub>

**Comment by SharkyKZ** [comment]
Not related to K2. Reopening<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27621">issues.joomla.org/tracker/joomla-cms/27621</a>.</sub>

**Comment by SharkyKZ** [comment]
I can't reproduce the issue but we had similar issues before. https://github.com/joomla/joomla-cms/issues/26487 should have fixed this, I think.

**Comment by SharkyKZ** [comment]
@zero-24 Can you take a look at this?

**Comment by zero-24** [comment]
What happes when the update cache is cleared? Using Extensions -> Updates -> Clear Or Components -> Joomla! Update -> Clear cache.

**Comment by brianteeman** [comment]
Due to lack of response this really should be closed
