### ISSUE TITLE
PHP 7.4.1

### ISSUE THREAD

**Issue by cibler95** [joomla/joomla-cms#27624]
### Steps to reproduce the issue

AVEC PHP 7.4.1 IMPOSSIBLE DE TÉLÉCHARGER UN MEDIA

**Comment by alikon** [comment]
please write in english...
and it will be very usefull if you can add more details like the issue template require
without that info it will be hard to answer you

**Comment by Quy** [comment]
Google translation:

> WITH PHP 7.4.1 UNABLE TO DOWNLOAD MEDIA

**Comment by richard67** [comment]
It can also mean "... upload ...".

**Comment by Quy** [comment]
Is the issue on J3 or J4?

**Comment by wilsonge** [comment]
Just tested J4 and it works for me (admittedly with 7.4.2 rather than 7.4.1). Is anyone here able to do a quick test on j3?

**Comment by SharkyKZ** [comment]
Uploads work fine for me. Tried with Media Manager (including modal) and with TinyMCE drag-n-drop. PHP 7.4.1.

**Comment by richard67** [comment]
I don't have PHP 7.4 avaliable.

**Comment by conseilgouz** [comment]
Just tried Joomla 3.9.14, PHP 7.4.2, upload a jpg file using media manager : no problem.
Need more information to test.

**Comment by conseilgouz** [comment]
Same result with PHP 7.4.0.

**Comment by conseilgouz** [comment]
If I tell you that I have the same result with PHP 7.4.1, are you surprised ?

**Comment by wilsonge** [comment]
@cibler95 if you don't give any more information in the next two days then we'll close this issue down as currently we are unable to reproduce

**Comment by b92** [comment]
On Wamperver with Joomla! 4 for different uploads:
- No issue with Content / Media / Upload with PHP 7.4.0 & 7.4.1 & 7.4.2
- No Issue with System / Install / Extension / Upload Package File / Browse for file with PHP 7.4.0 & 7.4.1 & 7.4.2
- Issue with System / Update / Joomla / Upload & Update  with PHP 7.4.1 & 7.4.2 (ok on 7.4.0 with another install) before updating file :
  Notice: Trying to access array offset on value of type bool in C:\ ... \administrator\components\com_joomlaupdate\View\Joomlaupdate\HtmlView.php on line 143
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27624">issues.joomla.org/tracker/joomla-cms/27624</a>.</sub>

**Comment by brianteeman** [comment]
@b92 that last item has already been fixed https://github.com/joomla/joomla-cms/pull/27653

**Comment by wilsonge** [comment]
No I closed it going to pull the version from staging when I merge it through

**Comment by b92** [comment]
For info: Last issue found with Joomla_4.0.0-beta1-dev-Development-Update_Package.zip uploaded 2 hours ago !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27624">issues.joomla.org/tracker/joomla-cms/27624</a>.</sub>

**Comment by brianteeman** [comment]
sorry @wilsonge I missed that part after I had tested it

**Comment by Quy** [comment]
@cibler95 Closing due to no response. Please post to Joomla Forum for assistance. https://forum.joomla.org/
