### ISSUE TITLE
Error installing Testing Sample Data

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#27623]
### Steps to reproduce the issue
Click `Testing Sample Data` button.
See error message.

### Actual result
> There is an error in a sample data plugin. Response is invalid.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/27625.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27623">issues.joomla.org/tracker/joomla-cms/27623</a>.</sub>
