### ISSUE TITLE
[4.0] duplicate selectors

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27639]
Assuming I am reading the scss correctly (and that's not certain) then the following selectors in `administrator\templates\atum\scss\blocks\_header.scss` should be combined and the conflicting values resolved.

https://github.com/joomla/joomla-cms/blob/bfd853ab3be7f2650c6da501430302a7ef75a218/administrator/templates/atum/scss/blocks/_header.scss#L157-L161

https://github.com/joomla/joomla-cms/blob/bfd853ab3be7f2650c6da501430302a7ef75a218/administrator/templates/atum/scss/blocks/_header.scss#L185-L188

**Comment by wilsonge** [comment]
Looks funky to me. Looks like only the padding from the 1st definition should survive in the second

**Comment by brianteeman** [comment]
closed see #27661
