### ISSUE TITLE
[4.0] Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#27649]
### Steps to reproduce the issue
Go to System > Joomla Update

### Actual result
> Notice: Trying to access array offset on value of type bool in \administrator\components\com_joomlaupdate\View\Joomlaupdate\HtmlView.php on line 143

### System information (as much as possible)
PHP 7.4.1

**Comment by ChristineWk** [comment]
? https://github.com/joomla/joomla-cms/issues/27252 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27649">issues.joomla.org/tracker/joomla-cms/27649</a>.</sub>

**Comment by wilsonge** [comment]
Fix https://github.com/joomla/joomla-cms/pull/27653
