### ISSUE TITLE
Top nav-bar is disabled

### ISSUE THREAD

**Issue by aditya20t** [joomla/joomla-cms#27654]
### Steps to reproduce the issue
Go to administrator/index.php and then go to edit accounts.

### Expected result
All drop-downs should be working.

![Screenshot (52)](https://user-images.githubusercontent.com/55142272/73130310-e0eacb80-401b-11ea-8839-f3ada3c6613c.png)

### Actual result
![Screenshot (51)](https://user-images.githubusercontent.com/55142272/73130312-e5af7f80-401b-11ea-8838-c91f0080701d.png)

Non responsive behaviour.

**Comment by N6REJ** [comment]
This is normal behavior.  You shouldn't be able to switch to another menu item when your editing a current one.  hit "close" and the menu will work again...
NOT A BUG

**Comment by aditya20t** [comment]
okay
