### ISSUE TITLE
[4.0] Sample data module does not show my sample data plugin

### ISSUE THREAD

**Issue by b2z** [joomla/joomla-cms#27659]
I am testing my extensions on **4.0.0-beta1-dev** and found that the sample data plugin is not visible in the sample data module. I do not have such an issue on the latest Joomla 3 installation.

Did a check that the code of `onSampleDataGetOverview()` method of my plugin and the blog sample data plugin is the same. So I am confused where the issue is.

You can see that the plugin is enabled:
![2020-01-26_165432](https://user-images.githubusercontent.com/3051676/73137037-e0bef000-405c-11ea-9fc5-9ff3539cdd45.png)

But nothing in the sample data module:
![2020-01-26_165332](https://user-images.githubusercontent.com/3051676/73137044-ef0d0c00-405c-11ea-897e-2cf07d7aaacd.png)

Here is the screen of my J3 installation where everything working fine:
![2020-01-26_170406](https://user-images.githubusercontent.com/3051676/73137170-03053d80-405e-11ea-8d9a-ea99a6d003a8.png)

**Comment by SharkyKZ** [comment]
Looks like plugin event names are now case sensitive. In J3 `onSampledataGetOverview`, `onSampleDataGetOverview` and any other casing work but in J4 it has to be `onSampledataGetOverview`.

**Comment by b2z** [comment]
Omg :) True it is case sensitive. Now it is working. Thank you.
