### ISSUE TITLE
[4.0] Default Permissions info

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27668]
### Steps to reproduce the issue
At the top of every page where you can set permissions it says "Default permissions for this component" 
![image](https://user-images.githubusercontent.com/1296369/73140683-867d5980-4073-11ea-8e80-900ce2edc895.png)

Is that really correct because if you change the permissions it still says _default_ ?

So what does _default_ mean in this context

If it is referring to the fact that the permissions could be changed on a per item basis and that this is the place to change the permissions for the entire component then it is less confusing if you don't have the word default. Especially as you cannot set permissions on a per item basis for everything

**Comment by jwaisner** [comment]
I would agree that this needs to either be clarified or removed.

Any thoughts on which direction we would want to go?

**Comment by brianteeman** [comment]
Personally I am leaning towards just deleting the word "default"

**Comment by jwaisner** [comment]
Wouldn't that be repetitive then? It already calls out "Permissions" just above that text. I would think removing it entirely would be the better choice IMO.

**Comment by brianteeman** [comment]
Thats also a valid suggestion - anyone else have an opinion please

@wilsonge

**Comment by Fedik** [comment]
I think it means "default" :smiley: 
~Example In Global config you have: article.edit = allow~
~And in Article item: article.edit = inherit~

~In this case it fallback to default value from Global config, that is "allow".~

Something like this, if I nothing missed.

**Comment by Fedik** [comment]
Sorry, update:

Example In Global config you have: item.edit = inherit
In Article component config you have: item.edit = "allow"
in Article item: item.edit = inherit

In this case it fallback to default value from Article component config, that is "allow".
It fallback to Component default value.

If Article component config have also: item.edit = "inherit", then it fallback to Global config that is "inherit" that is equal to "forbiden".
It fallback to Global default value.

**Comment by brianteeman** [comment]
To me the word "default" means the joomla default settings ie the settings on a new install

**Comment by Fedik** [comment]
Here it something like: "The value that will be used by default if nothing else defined. For "this" component."
Well, you know English better than me :smiley:

**Comment by brianteeman** [comment]
@fedik your explanation of what it means is correct. Just to me the english used is not accurately describing that.

**Comment by wilsonge** [comment]
My best attempt would be to delete the info bar (less screen clutter/duplication) and rename the existing "Permissions" label to "Component Permissions" (or similar)

**Comment by brianteeman** [comment]
that works for me

**Comment by brianteeman** [comment]
Closed see #27994
