### ISSUE TITLE
[4.0][Atum] Control-groups styled twice

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#27664]
### Steps to reproduce the issue
Control-groups styled twice

https://github.com/joomla/joomla-cms/blob/64b9025211b02d29be61ffe418f47e6334b8ed7b/administrator/templates/atum/scss/blocks/_form.scss#L8-L40

https://github.com/joomla/joomla-cms/blob/64b9025211b02d29be61ffe418f47e6334b8ed7b/administrator/templates/atum/scss/vendor/bootstrap/_form.scss#L7-L56

**Comment by brianteeman** [comment]
Confirmed. There are a few others as well

**Comment by ciar4n** [comment]
PR created... #27684
