### ISSUE TITLE
[4.0] com_content Options

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#27674]
### Steps to reproduce the issue
Open the options page in the articles manager on a smaller window (eg a laptop), but not as small as a mobile.

### Expected result
No horizontal scrollbar like eg for com_banners.
![image](https://user-images.githubusercontent.com/1018684/73163827-0564a780-40f1-11ea-9db0-d59d7e707afb.png)

### Actual result
We get multiple horizontal scrollbars, one for the registers and one for the whole window.
Imho, the one for the register is fine, but the one for the window not.
![image](https://user-images.githubusercontent.com/1018684/73163073-7dca6900-40ef-11ea-9e55-4c3aa7c02c3f.png)

### Additional comments
This happens because there are too many register tabs to display in the window.

**Comment by 200MPHMEDIA** [comment]
Even when the left menu is collapsed, the entire tab bar does not show.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27674">issues.joomla.org/tracker/joomla-cms/27674</a>.</sub>

**Comment by jwaisner** [comment]
Please reference PR [#27899](https://github.com/joomla/joomla-cms/pull/27899)

**Comment by brianteeman** [comment]
Re opened as #27899 was not a correct fix

**Comment by ghost** [comment]
looks solved:
![Screen Shot 2020-09-24 at 14 49 31](https://user-images.githubusercontent.com/70466955/94147212-4a55ff00-fe75-11ea-8205-46260034acb8.png)

**Comment by Quy** [comment]
Fixed #30675

**Comment by Bakual** [comment]
It is indeed fixed in current nightly, thanks to however fixed this 😄
