### ISSUE TITLE
[4.0] scss duplication

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27681]
When I inspect some of the classes I see lots of instances where we have the class declared twice and with identical values.

Digging into this further it looks like the files
administrator\templates\atum\scss\blocks\_form.scss
and
administrator\templates\atum\scss\vendor\bootstrap\_form.scss

are almost identical.

Is this correct? Shouldnt there just be one place where the class is defined etc

**Comment by ciar4n** [comment]
PR created... #27684

I assumed the ../bootstrap/ css is the one to remove considering it involves non bootstrap classes.

**Comment by brianteeman** [comment]
Thanks @ciar4n
