### ISSUE TITLE
Toolbar and navbar-toolbar icon

### ISSUE THREAD

**Issue by ravisaxena23** [joomla/joomla-cms#27699]
### What needs to be fixed
toolbar icon restrict closing of alerts and modals 
navbar icon should show hamburger icon without tap but show cross icon.
![Screenshot (29)](https://user-images.githubusercontent.com/44205807/73332872-1b5b9f00-428e-11ea-9922-5adae61a4dc4.png)
### Why this should be fixed
 increase user experince.
make joomla better.

### How would you fix it
fixing css

**Comment by alikon** [comment]
closing as we have pr #27700 


p.s
@ravisaxena23 you don't need to open an issue if you are going to submit a pr<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27699">issues.joomla.org/tracker/joomla-cms/27699</a>.</sub>
