### ISSUE TITLE
[4.0] Remove header SVG curve in error page

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#27709]
### Steps to reproduce the issue
Go to the front end
Go to a nonexistent page 
See error page with curve in header

### Actual result

![404](https://user-images.githubusercontent.com/368084/73418890-10c2f900-42d2-11ea-8c29-ff4c8c273ea4.jpg)

**Comment by brianteeman** [comment]
You should be able to just remove
https://github.com/joomla/joomla-cms/blob/456a1d2630030a8fbd685d2c7552e4bb980b7093/templates/cassiopeia/error.php#L110-L116

**Comment by brianteeman** [comment]
Closed see #27826
