### ISSUE TITLE
Multiple combo field [Joomla 3.9.15]

### ISSUE THREAD

**Issue by Polm90** [joomla/joomla-cms#27713]
I'm using Joomla! 3.9.15 with the protostar default layout.

Form xml example:
```
<field name="test"
			   type="repeatable"
			   icon="list"
			   description="test_desc"
			   label="test_label"
			  >
			<fieldset hidden="true" name="repeatable_test" repeat="true">

				<field name="description"
					   label="description_label"
					   size="30"
					   type="combo">
					<option value="1">test 1</option>
					<option value="2">test 2</option>
				</field>
			</fieldset>
		</field>
```
This is the result:
![image](https://user-images.githubusercontent.com/4883463/73447837-de5fdd00-435f-11ea-8988-21654860b29d.png)
Clicking on the "arrow icon" doesn't do anything (neither the first time).

Moreover, neither the combo field type with the multiple attribute actually works: it ignores the attribute.

XML example:

```
<field name="test_combo"
			   label="test_combo_label"
			   multiple="true"
			   size="30"
			   type="combo">
			<option value="1">test 1</option>
			<option value="2">test 2</option>
		</field>
```

Finally, using a combo field type inside a subform with multiple attribute, doesn't work: the first instance works properly, but the following ones don't (clicking the arrow doesn't open the option list).

XML example:

```
<field
				name="test_combo"
				multiple="true"
				type="subform"
				formsource="components/com_test/models/forms/subform.xml"
				label="test_combo_lbl"
				description="test_combo_desc"
				min="1"
				buttons="add,remove"
				required="true"
		/>
```
and in the subform.xml file:

```
<form>
	<fields>
		<field name="test_combo"
			   label="test_combo_label"
			   multiple="true"
			   size="30"
			   type="combo">
			<option value="1">test 1</option>
			<option value="2">test 2</option>
		</field>
	</fields>
</form>
```

**Comment by SharkyKZ** [comment]
Closing as duplicate #23077.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27713">issues.joomla.org/tracker/joomla-cms/27713</a>.</sub>
