### ISSUE TITLE
[3.9] Error in mediamanager is misleading

### ISSUE THREAD

**Issue by EmilMassey** [joomla/joomla-cms#27717]
### Steps to reproduce the issue
In `/administrator/index.php?option=com_media` upload file(s) larger than allowed limit

### Expected result
Error message: Uploaded file(s) are larger than allowed limit.

### Actual result
Error message: You have tried to upload file(s) that are not safe.

#### Server
Docker image `php:7.3-apache`

#### Client:
- Ubuntu, Chromium 79.0.3945.130
or
- MacOS, Safari

### Additional comments
https://github.com/joomla/joomla-cms/pull/15466 was based on incorrect assumption, that `JInputFiles get()` returns null only if unsafe file was uploaded. But it is also null if `upload_max_filesize` is less than uploaded file(s) (at least in my environment).

In the controller, there are some checks if the file is too large to upload, but they are called too late in the process.
[administrator/components/com_media/controllers/file.php](https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_media/controllers/file.php)

**Comment by Quy** [comment]
Is the uploaded file of type zip? If yes, see #26408.

**Comment by EmilMassey** [comment]
It’s not, it’s just a regular jpeg. I haven’t found similar issue on GitHub. 

In my environment, `$_FILES` global array is empty when file(s) exceed the limit and this is the reason `files->get()` returns nothing.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/27730.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27717">issues.joomla.org/tracker/joomla-cms/27717</a>.</sub>
