### ISSUE TITLE
JHTML grid.boolean tasks fail

### ISSUE THREAD

**Issue by softarius** [joomla/joomla-cms#27724]
### Steps to reproduce the issue
Add to any grid admin layout using JHTML like this
`JHTML::_('grid.boolean', $i, $row->important,'helloworlds.important','helloworlds.unimportant');`

### Expected result
The row is selected and the task is invoked

### Actual result
Error `JSON.decode is not a function` into JavaScript console 

### System information (as much as possible)
Joomla 3.9.15 and staging

### Additional comments
A component using the boolean field to illustrate this bug.
[Joomla-3-Hello-World-Component_0.16.zip](https://github.com/joomla/joomla-cms/files/4135978/Joomla-3-Hello-World-Component_0.16.zip)

I try will prepare the pull request to fix it

**Comment by Quy** [comment]
See PR #27725<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27724">issues.joomla.org/tracker/joomla-cms/27724</a>.</sub>
