### ISSUE TITLE
[4.0] Installation form shows fields in order different to the order in the form XML

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#27726]
### Steps to reproduce the issue

1. Start a new installation of current 4.0-dev or nightly build.
2. When coming to the databae connection options, select option "Two-way authentication" in the drop down "Connection Encryption".
3. Note the order of the fields for database connection encryption e.g. by making a screenshot.
4. Change back "Connection Encryption" to "Default (server controlled)" or whatever else works for you.
5. Fill in necessary database information, complete the installation, login to backend and go to the "Server" tab of "Global Configuration",
6. Select option "Two-way authentication" in the drop down "Connection Encryption".
7. Note the order of the fields for database encryption e.g. by making a screenshot.
8. Open files [https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/forms/setup.xml](https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/forms/setup.xml) and [https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_config/forms/application.xml](https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_config/forms/application.xml), go down to the fields for database connection enrcyption (field "db_encryption" in setup.xml and "dbencryption" in application.xml) and verify the order of the fields.

### Expected result

The order of fields related to database connection encryption is the same in the form xml files for new installation and for global configuration, and so the order of the fields shown in the form is the same for the installation form and global configuration.

### Actual result

The order of fields related to database connection encryption is the same in the form xml files for new installation and for global configuration, and the order of the fields is like that in global configuration, but in the installation form the switcher "Verify Server Certificate" is moved up for some reason. This can be also seen when inspecting html with developer tools in the browser, so it is not just a css position issue.

- The correct global configuration:
![db-ssl-options_backend_2-way-no-verify](https://user-images.githubusercontent.com/7413183/73486930-54873280-43a6-11ea-9650-8521e0fed70a.png)
- The wrong installation form:
![db-ssl-options_install_2-way-no-verify](https://user-images.githubusercontent.com/7413183/73486958-5e109a80-43a6-11ea-986c-26844df59c57.png)
- Comparison of the forms' XML files, left side global configuration, right side installation form:
![db-ssl-options_compare-backend-and-installation_form-xml](https://user-images.githubusercontent.com/7413183/73487063-8d270c00-43a6-11ea-9dd8-1589c8d32f20.png)

### System information (as much as possible)

Current 4.0-dev.
PHP version, database version, browser and so on don't matter.

### Additional comments

I have no idea what changes the field ordering. Maybe voodoo? Or was it the illuminati?

Anyway, I had noticed this already when I've made the PRs to integrate the new database connection encryption options into these forms, but later I have forgotten about it and forgotten to make an issue. Sorry for that. Thanks @Quy pointing me again on it.

**Comment by brianteeman** [comment]
Iirc the installation does not parse the XML. Each field is manually displayed

**Comment by richard67** [comment]
@brianteeman Manually? ~~You mean coded in PHP?~~

**Comment by richard67** [comment]
@brianteeman Thanks .. found it: [https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/tmpl/setup/default.php#L80](https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/tmpl/setup/default.php#L80) and later.

**Comment by richard67** [comment]
As @brianteeman correctly pointed out, the order of the fields in the installation form is not determined by the form XML but hardcoded in the template PHP. So this issue is invalid, but we have another issue that the ordering of db encryption fields is not the same in installation and global config. Will make PR to fix it.

**Comment by richard67** [comment]
P.S.: Seems I have bad memory regarding this, I should have remembered from integrating it.
