### ISSUE TITLE
[4.0] Alternate Menu Type missing

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27737]
### Steps to reproduce the issue
1. Create a custom admin menu with the alternate preset
2. In the menu manager open some menu items
3. Sometimes the menutype is empty
example
- Clear Cache
- Global Checkin
4. Sometimes the menutype is completed
example
- System information

### Expected result
The menutype is always completed

### Actual result
Sometimes it is blank. Which means the menu item cannot be saved without resetting the menutype as it cannot be empty as it is a required field

![image](https://user-images.githubusercontent.com/1296369/73535174-dadd5c00-441a-11ea-87d4-0cf1bc5e6c9b.png)

**Comment by infograf768** [comment]
Conditions:
Multilingual installed with the 4 languages possible
Here I can't even create any custom admin menu via Menus Manage Administrator New with a preset. It just refuses to use the preset. I am quite confused.

**Comment by infograf768** [comment]
<img width="1455" alt="Screen Shot 2020-02-02 at 07 46 34" src="https://user-images.githubusercontent.com/869724/73604391-4f85d700-4590-11ea-8801-6711a72700c8.png">

**Comment by chmst** [comment]
@infograf768 your issue is not related to this one. Please open another one for multilingual presets.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27737">issues.joomla.org/tracker/joomla-cms/27737</a>.</sub>

**Comment by infograf768** [comment]
@chmst 
I solved my issue in https://github.com/joomla/joomla-cms/pull/27800

**Comment by infograf768** [comment]
BTW, I confirm the issue.

**Comment by infograf768** [comment]
Testing further.
We have the same issue (but not as many) when using the Preset- Joomla Main Menu (not only the alternate).
See Home Dashboard for example.

**Comment by brianteeman** [comment]
Found the problem and the fix. PR incoming

**Comment by brianteeman** [comment]
closed see pr
