### ISSUE TITLE
[4.0] Custom Field Type media - hide_default

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#27735]
For what do we need the option `hide_default`  in the custom field `media`?

https://github.com/joomla/joomla-cms/blob/85ab859e465b29c9b7aa5de78bd76f188ecb5eb3/plugins/fields/media/media.php#L41

I don't see any place in [media field ](https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Form/Field/MediaField.php) where a standard value is offered that you want to deactivate.

I only see this option in the list fields ([FileListField](https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Form/Field/FilelistField.php#L165) and [FolderListField](https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Form/Field/FolderlistField.php#L167)).

Am I missing something or should I open a PR to remove this line?

**Comment by SharkyKZ** [comment]
You're right, it can be removed.
