### ISSUE TITLE
[4.0] Subfield - require

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#27736]
### Steps to reproduce the issue
1. Create a `custom field` of type `subfield` with one `subfield` of type text and set it as `required`.
![Articles  Edit Field   test   Administration(1)](https://user-images.githubusercontent.com/9974686/73531708-53dcb380-441b-11ea-8863-bb367e47810a.png)
2. Create an article and do not fill text in the in step one created custom field.

### Expected result

As the field is required the article should not be saved. 

### Actual result

The article is saved.

![Articles  Edit   test   Administration](https://user-images.githubusercontent.com/9974686/73531897-bcc42b80-441b-11ea-81a8-0318a4875097.png)

**Comment by Fedik** [comment]
Technically it have a value, that why it saved.

To make it work as you expected:
If the subform are non multiple, then one of its field should be set to "required".

**Comment by astridx** [comment]
OK. Thanks for the answer. Then you don't see it as a bug. 
How do others see it? Am I the only one who expects different behavior? I would disable the `require` option in the `subfield` field or switch it to invisible.

If I'm the only one who sees an error here, I'll close the issue.

**Comment by Fedik** [comment]
yeah, it may be confusing,
removing `require` option for this field sounds as not a bad idea

**Comment by astridx** [comment]
OK. Then I open it again so that it is not forgotten.

**Comment by astridx** [comment]
See https://github.com/joomla/joomla-cms/pull/27757
