### ISSUE TITLE
Override UI cannot save single quote '

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#27740]
### System information: PHP 7.3.11 + Joomla 3.9.15

**Solution** = As far as I know I can solve replacing all the double quotes " with single quotes '
Tested changing the Language file directly and it run.
But, when I enter single quotes through the Joomla Override UI all the single quotes ' are automatically transformed into double quotes during saving = BUG ?

**Comment by brianteeman** [comment]
> But, when I enter single quotes through the Joomla Override UI all the single quotes ' are automatically transformed into double quotes during saving = BUG ?

I could not replicate that
![image](https://user-images.githubusercontent.com/1296369/73692271-e7d4a680-46cb-11ea-8a85-68b32fb5a326.png)

Secondly and perhaps more importantly you cannot have a clickable link inside a bootstrap tooltip as you can never move your mouse into the tooltip to click on it.

**Comment by Quy** [comment]
Closing for reasons stated.

**Comment by joomleb** [comment]
Hi guys, sorry for my later. @brianteeman, Please, test:

**1** - **Single quote saved as double quote** > "...I could not replicate that...":
- Adding as single quote: The title of <a href=Q'Qhttps://test2.egulp.net/locationsQ'Q target=Q'Q_blankQ'Q rel=Q'QnoopenerQ'Q>Location</a>
- It is saved as double quote: The title of <a href=Q"Qhttps://test2.egulp.net/locationsQ"Q target=Q"Q_blankQ"Q rel=Q"QnoopenerQ"Q>Location</a>
PS here I had to add Q before and after quotes to show the entire text

**2** - **Click mode** > "...you cannot have a clickable link inside a bootstrap tooltip as you can never move your mouse into the tooltip to click on it..." = Right know:
- **Mobile**: the tooltips are opened on click Title or Field = I can click on links on mobile tooltips and they are opened in a new tab.
- **Desktop**: the Tooltips are opened on hovering = To add here also the mobile behaviour "on click mode" is a must thinking on **touchscreens**! On click mode should be the base. So, on desktop, at least, should be a mixed way: if I click on title/field / click out (like it is yet in the mobile view) + at least when hovering title the tooltip appear and disappear (like now).
