### ISSUE TITLE
Popular Tags module shows not tag with access level 0

### ISSUE THREAD

**Issue by svenbluege** [joomla/joomla-cms#27744]
### Steps to reproduce the issue

- have a 3rd party component which does not use an access level database table column
- create a tag within this component
- assign a content item to the tag
- create an instance of the "popular tags" module
- create an instance of the "similar tags" module
- check the output

Alternative: update #_ucm_content and set the core_access column to zero. This is exactly what happens if a 3rd party component does not use this column. Possible reason: different access level restriction implementation. 

### Expected result

I see the 3rd party tag. 

### Actual result

Popular Tags module: I don't see the tag
Similar Tags module: I see the tag

### System information (as much as possible)

Joomla 3.9.15

### Additional comments

For the similar tags module this was fixed some years ago: https://github.com/joomla/joomla-cms/pull/996/commits/04161600e69ebed68ffcc6fa5619dc249323cc0e

**Comment by brianteeman** [comment]
No need to create an issue if you are making a pull request at the same time.
