### ISSUE TITLE
[4.0] Subfield - Param repeat should be readonly

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#27751]
For what do we need this code:
```
// Don't allow the 'repeat' attribute to be edited
foreach ($xmlxpath->evaluate('//field[@name="repeat"]') as $field)
{
	$field->setAttribute('readonly', '1');
}
```
https://github.com/joomla/joomla-cms/blob/c590a1cf5fecc772f303d3140a75ff8f1014eddf/plugins/fields/subfields/subfields.php#L97

In any case, it does not work. 

### Steps to reproduce the issue
1. Create a new custom field of the type `subfield`
2. See, that you can edit the field `repeat`

### Expected result
After reading the code I expected:

Field for the param `repeat` should be `readonly`.

### Actual result

You can edit the field `repeat`.
![Articles  Edit Field   test   Administration(2)](https://user-images.githubusercontent.com/9974686/73589798-6e766180-44db-11ea-9f3d-0cb6fe68c70a.png)

**Comment by Fedik** [comment]
~I think it was made to make "require" option to work (your issue #27736), if it not work then it cause #27736~
~Need to find original PR and author, to be sure.~

**Comment by Fedik** [comment]
@astridx can you please check next:
1 Create a new custom field of the type subfield
2 See, that you can edit the field repeat
3 Save the field
4 Open to edit again, repeat field should be "readonly"

I found it need for prevent changing type of existing field, to avoid data loss.

If it not work, then it may be related to #27760

Original pr #24711

**Comment by astridx** [comment]
@Fedik I did like you asked. The new created field of the type subfield was all the time editable. So it was not `readonly` after saving and reopening.

**Comment by Fedik** [comment]
Thanks for checking.
Then it a valid bug.

**Comment by AndySDH** [comment]
This can be closed. It has been fixed in another PR and it's now fixed

**Comment by alikon** [comment]
can you please reference the pr that solved this.... then i'll be very happy to close this one

**Comment by AndySDH** [comment]
I think this is the one:
https://github.com/joomla/joomla-cms/pull/28356

Proof of the fix:

![image](https://user-images.githubusercontent.com/25923699/97802526-4cfdfe00-1c44-11eb-855d-12ca296126e6.png)

**Comment by alikon** [comment]
thank you
