### ISSUE TITLE
Update notification despite current version

### ISSUE THREAD

**Issue by darkcycs** [joomla/joomla-cms#27750]
### Steps to reproduce the issue
Update from 3.9.14 to 3.9.15

### Expected result
no mail notification: "installed version 3.9.14" - "new version 3.9.15 is available for installation"

### Actual result
I get a daily mail notification on all of my joomla installations (dozens): "installed version 3.9.14" - "new version 3.9.15 available". But this is wrong! All of my installations were updated yesterday - to 3.9.15!

### System information (as much as possible)
PHP 7.4.2
MariaDB 10.3.22
All updated joomla installations shows the version 3.9.15

**Comment by alikon** [comment]
related to #26487 #27621

**Comment by darkcycs** [comment]
In my case, it's not exactly the same as in the other post, you linked to. I did not receive the update message in the administrator. I only received the email update notification.

**Comment by darkcycs** [comment]
> 
> 
> related to #26487 #27621

In my case, it's not exactly the same as in the other post, you linked to. I did not receive the update message in the administrator. I only received the email update notification.

**Comment by jwaisner** [comment]
Reducing to Low priority as this is not affecting functionality, just an unnecessary notification.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27750">issues.joomla.org/tracker/joomla-cms/27750</a>.</sub>

**Comment by joomdonation** [comment]
As Joomla 3 is now in maintenance mode and only receive security bugs fixes, I'm closing this issue. If you still have the same issue with Joomla 4, please open a new issue. Thanks !
