### ISSUE TITLE
Discover after error cannot be repeated

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#27759]
### Steps to reproduce the issue
Install an extension which also creates a table. 
Let the sql have an error. 
Discover finds the extension and you can activate the installation. The installation throws an error as expected.
From now on, the extension is know in #__extensions, therefore the discover cannot be repeated.

### Expected result
After a broken installation, I can repeat with a correct extension

### Actual result
Repeating discover is not possible.

### Additional comments
Same behavour in 3.9 and 4.0, but better information in 3.9

**Comment by brianteeman** [comment]
From memory this was true in J3 as well. I used to see it with a failed patchtester install and had to follow the steps you describe to resolve it.

I really dont see how this is a release blocker - its a bug but hardly prevents normal usage of Joomla which is what a release blocker should be.

**Comment by richard67** [comment]
@brianteeman I’ve added release blocker label as suggested by @wilsonge .

**Comment by chmst** [comment]
When people migrate to J4 they probably will install many extensions by discover. So it should befixed before release.

**Comment by brianteeman** [comment]
If they have to do it by discover then we will have really messed up the upgrade - won't we?

**Comment by mbabker** [comment]
> When people migrate to J4 they probably will install many extensions by discover. So it should befixed before release.

How about if it’s a known bug in 3.x that it be fixed in 3.x (if it can be done without B/C issues) instead of reporting and fixing bugs against only 4.0?

And +1 on Brian, if you’re using discover install then the release process was messed up massively.  Of course since core makes no promises about upgrades until stable, nobody is going to know that answer until 4.0.2 comes around.

**Comment by richard67** [comment]
> Of course since core makes no promises about upgrades until stable, nobody is going to know that answer until 4.0.2 comes around.

@mbabker This is wrong. We we will promise updatability between 4.0 version beginning with beta-1. And that we don't promise before doesn't mean we aren't testing before.

**Comment by chmst** [comment]
@brianteeman and @mbabker 
When I am developing an extension, I always use discover. What's wrong about ist? Why do we have it, if it may not be used? 
If you think it is wrong or superfluous - remove it. 
I wrote this because "normal users" do not easily find these issues by chance and most of developers know how to make workarounds but do not write issues.

**Comment by brianteeman** [comment]
@chmst we misunderstood each other I think - trying again

> When people migrate to J4 they probably will install many extensions by discover. 

Why would they  install many extensions by discover because they have migrated?

**Comment by chmst** [comment]
As supporter I see users who have extensions but have lost their easy-to-install .zip files and we say them "use discover" if necessary. 
I think that this is needed often when migrations are made. Maybe I am wrong but that's not important. Let's try to fix it and basta.

**Comment by brianteeman** [comment]
You really shouldnt need to use discover on an upgrade - if you do then the upgrade code is wrong and needs fixing.

And as far as I recall this discover failure exists in j3 as well so it should be fixed there

**Comment by richard67** [comment]
@chmst Could you test if the issue exists in J3, too, and if so, just remove "[4.0] " from the beginning of the title and change "Build" from "staging" to "4.0-dev" in the issue tracker, and all is fine with the issue.

**Comment by richard67** [comment]
Regarding release blocker or not: For me it is not a blocker, but maybe @wilsonge can comment why he asked me to add the label ;-)

**Comment by chmst** [comment]
Indeed, the same in 3.9.

**Comment by richard67** [comment]
@wilsonge Any reason not to fix it in 3 but wait for 4? E.g. db drivers: Do they support transactions in staging branch, too, or only in 2.0-dev of the framework package? From my point ov view the installer should use sql transactions so it can roll back when an error breaks the installation somewhere in the middle.

**Comment by mbabker** [comment]
> From my point ov view the installer should use sql transactions so it can roll back when an error breaks the installation somewhere in the middle.

Transaction support exists in the database API in 3.x for all supported drivers IIRC.  Problem is core lacks proper error handling and someone would need to take the time to add transaction support to relevant parts of the API AND appropriate success/error handling (transaction commit/rollback) at the same time.

**Comment by rdeutz** [comment]
I agree should be fixed in 3.x, maybe we cam try/catch the db queries but working on installer code is far from fun. I removed the release blocker label. A workaround is to unstall the extension as far as I know. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27759">issues.joomla.org/tracker/joomla-cms/27759</a>.</sub>

**Comment by brianteeman** [comment]
Is this pr relevant/helpful https://github.com/joomla/joomla-cms/pull/21363
