### ISSUE TITLE
This Tracker - Empty Categories and Labels lists

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#27753]
### Steps to reproduce the issue

In this tracker the Search Tools Categories and Labels lists both drop down to reveal blank white space. That is because the style sheets have these styles in template_3.0.0.min.css:

.btn-group {
	font-size: 0;
} 
.btn-toolbar {
	font-size: 0;
} 

It would be nice if it could be fixed!

**Comment by richard67** [comment]
@ceford This here is the repository for the CMS, so here only issues with the CMS should be reported. For issues with the issue tracker there is [https://github.com/joomla/jissues](https://github.com/joomla/jissues) . Could you report your issue there and close this one here? Thanks in advance.

**Comment by Quy** [comment]
https://github.com/joomla/joomla-websites/issues/1378
