### ISSUE TITLE
[4.0] Readonly doesn't work with switcher

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#27760]
### Steps to reproduce the issue
1. Create a form that contains a `switcher`. In order to simplify testing, I temporarily changed the [core form `/administrator/components/com_content/config.xml`](https://github.com/joomla/joomla-cms/blob/c590a1cf5fecc772f303d3140a75ff8f1014eddf/administrator/components/com_content/config.xml#L19).
2. I changed this code beginning on line 19 
```
<field
	name="show_title"
	type="radio"
	label="JGLOBAL_SHOW_TITLE_LABEL"
	class="switcher"
	default="1"
	>
	<option value="0">JHIDE</option>
	<option value="1">JSHOW</option>
</field>
```
to 
```
<field
	name="show_title"
	type="radio"
	label="JGLOBAL_SHOW_TITLE_LABEL"
	class="switcher"
	default="1"
	readonly="true"
	>
	<option value="0">JHIDE</option>
	<option value="1">JSHOW</option>
</field>
```
in the form `/administrator/components/com_content/config.xml`. I added `readonly="true"`

And i tried this code. 
```
<field
	name="show_title"
	type="radio"
	label="JGLOBAL_SHOW_TITLE_LABEL"
	class="switcher readonly"
	default="1"
	readonly="true"
	>
	<option value="0">JHIDE</option>
	<option value="1">JSHOW</option>
</field>
```
in the form `/administrator/components/com_content/config.xml`. I addes the class `readonly`.

### Expected result
I cannot change the value of the field. It is displayed as a ~`readonly`~ `displayed` field. 

### Actual result
Nothing changes. The field can be edited as normal. The display is also such that you have the impression that the field is active.
![Articles  Options   test   Administration](https://user-images.githubusercontent.com/9974686/73592760-d8076780-44fd-11ea-8d80-3a72206ad58b.png)

### Additional comments

If I delete the class switcher, the radio input works as expected. It is now readonly. But the style is not nive :)

```
<field
	name="show_title"
	type="radio"
	label="JGLOBAL_SHOW_TITLE_LABEL"
	class=""
	default="1"
	readonly="true"
	>
	<option value="0">JHIDE</option>
	<option value="1">JSHOW</option>
</field>
```
![Articles  Options   test   Administration(1)](https://user-images.githubusercontent.com/9974686/73592790-41877600-44fe-11ea-80b4-bee136b004b6.png)

**Comment by chmst** [comment]
~~See https://issues.joomla.org/tracker/joomla-cms/27555.~~
Sorry, @astridx , I did not read carfully. 




<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27760">issues.joomla.org/tracker/joomla-cms/27760</a>.</sub>

**Comment by chmst** [comment]
~~Showon works in J4 only if fields are rendered as in layouts. Because the layout does this https://github.com/joomla/joomla-cms/blob/4.0-dev/layouts/joomla/content/options_default.php#L28.~~
Sorry, @astridx , I did not read carfully. This is another issue.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27760">issues.joomla.org/tracker/joomla-cms/27760</a>.</sub>

**Comment by chmst** [comment]
confirmed. Probably a javascript task. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27760">issues.joomla.org/tracker/joomla-cms/27760</a>.</sub>

**Comment by SharkyKZ** [comment]
How should disabled switcher look like? `btn-group-yesno` radio also doesn't have readonly styling.

**Comment by astridx** [comment]
In my opinion it should be gray and it should not be possible to change the state of the switcher

**Comment by SharkyKZ** [comment]
It is already gray when "negative" option is selected.

**Comment by astridx** [comment]
I think the important thing is, that it should not be possible to change the state.
The styling could be a lighter gray than the "not selected"/negativ state

**Comment by Bakual** [comment]
Let's have a look at https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly
> The attribute is not supported or relevant to input types that are already not mutable, such as checkbox and radio

Also

> Note: Only text controls can be made read-only, since for other controls (such as checkboxes and buttons) there is no useful distinction between being read-only and being disabled, so the readonly attribute does not apply.

Since the switcher technically is a radio element, it can't be `readonly`. You can only disable it.

In J3, readonly radios were technically automatically disabled and the button groups looked like this:
![image](https://user-images.githubusercontent.com/1018684/76703684-8133a700-66d3-11ea-8563-998ac362b973.png)

**Comment by astridx** [comment]
> @Bakual Since the switcher technically is a radio element, it can't be readonly. You can only disable it.

You are right, I meant disabled. I corrected it in the issue.

**Comment by Bakual** [comment]
I took care of the technical side with https://github.com/joomla/joomla-cms/pull/28356. The visual side has to be done by someone who has a clue 😄

**Comment by astridx** [comment]
Closed because we have provided.
