### ISSUE TITLE
[Images & Links] - add option for responsive images

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#27769]
**What I see now:**
![изображение](https://user-images.githubusercontent.com/3662519/73606532-385cde80-45bc-11ea-8640-a2318c0bab41.png)

**What I suggest:**
`<img alt="1" src="/images/1.jpg" style="max-width: 100%; height: auto;" title="1">`

**Add this option to display on mobile devices:**
`style="max-width: 100%; height: auto;"`

**Comment by mbabker** [comment]
Inline styles are not the right way to do this, and when using CSPs would cause errors in the browser.

**Comment by 4digitalworld** [comment]
@mbabker but this is a flaw, right? this is a display error for the image when adaptive display is required.

**Comment by mbabker** [comment]
You can do the same in your template with CSS.  Core should not be auto-generating markup with inline style rules (which are actually harder to override in CSS).

**Comment by brianteeman** [comment]
Closing for the reasons stated above. Inline styles should not be used

**Comment by SharkyKZ** [comment]
It looks like this image is using JCaption. It actually fits the image to screen width but it does not recalculate on window resize.

**Comment by 4digitalworld** [comment]
@brianteeman @SharkyKZ  I talked about same/similar problem 4 years ago - [https://github.com/joomla/joomla-cms/issues/10051](https://github.com/joomla/joomla-cms/issues/10051)

and this problem is still not resolved, and now I again saw this problem on a new test website.

**Comment by mbabker** [comment]
Inline CSS is still the incorrect fix.  The proper fix is to add the appropriate CSS to your template.

**Comment by 4digitalworld** [comment]
> 
> 
> Inline CSS is still the incorrect fix. The proper fix is to add the appropriate CSS to your template.

This is the standard template Protostar that everyone has in Joomla 3. It turns out that this is a problem of Joomla?

**Comment by mbabker** [comment]
As was pointed out on your issue 4 years ago, the appropriate CSS is already included in the template, and as you yourself pointed out because of changes in browsers you were experiencing the issue on an older browser but not a more recent version.

Either way the change you are suggesting is just wrong, end of discussion.  If you can demonstrate an actual bug in Joomla then submit a proper bug report with more details than a random screenshot that someone could actually troubleshoot.
