### ISSUE TITLE
[Images & Links] - do not show image

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#27768]
![изображение](https://user-images.githubusercontent.com/3662519/73606018-91c20f00-45b6-11ea-948b-7d89ab636b5d.png)
**I suggest adding new parameter:**

- do not show image

**Why add image hiding?**
Many plugins use this field to display a tag `og:image`, to display a thumbnail of the picture on social networks. This will allow you to add a higher quality image for social networks, as recommended for example by Facebook.

**Comment by brianteeman** [comment]
You can easily do this on your site with a template override<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27768">issues.joomla.org/tracker/joomla-cms/27768</a>.</sub>

**Comment by 4digitalworld** [comment]
> 
> 
> You can easily do this on your site with a template override
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/27768](https://issues.joomla.org/tracker/joomla-cms/27768).

I have heard this many times, and not just me. I think we can close this question by simply adding an additional parameter consisting of several lines of code.

I will give a simple example of why this might be necessary for the site:

If you publish lyrics, but want the user on the site to see only text, without images, and also the user can share this article on social networks, you must specify a tag for the image. If we add the option "do not show the image", then we will solve this problem once and for all.
There are many more similar examples.

**Comment by mbabker** [comment]
Use a plugin that sets metadata appropriately, not misuses core fields and data that serve a designated purpose.  Changing core to misuse a feature isn't exactly the best of solutions.

**Comment by 4digitalworld** [comment]
@mbabker This feature was made in 2005, along with the first version of Joomla. In 2005, no one shared content on social networks.

Now we live in a different world where people share links on social networks, and social networks have a requirement - this is a preview image for each link. But not all articles have images (**for example**: `song lyrics` or `documentation`), but it should be possible to specify images so that a link on a social network is displayed with an image.

This is not a “misuse”.

And when the manufacturers of templates for Joomla and the developers of CMS Joomla tell me to use plugins or overrides, it only means that the right solution for this problem has not been made at the moment. This is a problem of our days and it is necessary to solve this problem!

We need to stop going website administrators sending for plugins. This function has only a few lines of code, and this function will greatly improve life for many website administrators.

I wrote this problem here because this problem is very significant and I have seen many times how developers have proposed to solve this problem in non-standard ways.

**Comment by mbabker** [comment]
That’s why I suggest different fields for these types of images, not misusing the existing image fields which serve an explicit purpose for use in the frontend layout.  Note I’m not flat out saying that the idea here is wrong (some kind of field for managing social media imagery), but the approach you’re suggesting IMO is wrong.

**Comment by mbabker** [comment]
> And when the manufacturers of templates for Joomla and the developers of CMS Joomla tell me to use plugins or overrides, it only means that the right solution for this problem has not been made at the moment.

Core does not have to have every imaginable feature within it for the CMS to be successful.  It is perfectly fine to send users to the extension ecosystem to add on capabilities to their websites.  The problem is basically always one of people thinking some feature must be in the core CMS, usually for some pretty arbitrary or limited reason.

**Comment by 4digitalworld** [comment]
@mbabker You created Joomla 15 years ago. But you forgot that Joomla was created as a CMS.
CMS = **content management system**.

I do not ask to add a slider or the possibility of buying on the website.
What I wrote about relates to the basic functions of the CMS in 2020.

You can add another, additional field - for example, "image for social networks." In which you can, for example, make such a parameter - "use the image from the intro / full text" (if necessary). It's pretty simple, but the millions of people who use this CMS will be happy.

**Comment by 4digitalworld** [comment]
@mbabker I believe that Joomla should continue to develop way in order to make publishing content on the site more convenient and better than now.

CMS is a tool for publishing and managing content. I'm not talking about the functions of an online store or forum or gallery or something similar. Why doesn't Joomla develop features for publishing content?

**Comment by brianteeman** [comment]
Your solution works for you.
It does not work for me as I use that field for my intro image

Do you see the problem?

**Comment by 4digitalworld** [comment]
@brianteeman We can add another field, as I wrote above.

**Comment by brianteeman** [comment]
and then we are back to exactly what @mbabker said in the beginning.

this is going to go nowhere using the images and links functionality for social media links is not the correct thing to do.
