### ISSUE TITLE
[4.0] Dashboard title icons

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#27764]
The icons used for a 3rd party extension dashboard titles are created from a language string.

There was an original issue opened for core (https://github.com/joomla/joomla-cms/issues/26217) which got fixed by adding special threatment for core (https://github.com/joomla/joomla-cms/pull/26252).
While that worked obviously, it's wrong from an architecture point of view and doesn't work for 3rd parties, which still would have to add CSS classes to a language string.
Also the code would only load a 3rd party provied string if the "dashboard" parameter has a section (eg com_foo.bar), which is wrong as well.

### Expected result
Icon is defined by the respective component by an XML definition or PHP code. 

### Actual result
Component (content, menu, users, ...) specific stuff is hardcoded into com_cpanel.

### Additional comments
I stumbled over this by reverse engineering the dashboard functionality so I could add that to my component.
In that view there is way to much special handling for core components which must be eliminated so it is easier for 3rd parties to figure out how something works (since there likely will be no documentation).

**Comment by richard67** [comment]
@wilsonge Do you think this is a release blocker? Or even a beta blocker?

**Comment by brianteeman** [comment]
@bakual just seen this after writing my own post #27770

**Comment by Bakual** [comment]
Since Brian is a step further already, I'm closing this one in favor of his issue.

**Comment by brianteeman** [comment]
see #27773
