### ISSUE TITLE
Unable to copy Joomla 4 template

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#27776]
### Steps to reproduce the issue
Hello everyone

I can't **copy** site template or administrator template, I have an error :

```
JInstaller: :Install: File does not exist /home/bruno28/sites/joomla4beta1/tmp/template_copy_5e355972ce9ee/language
Template Install: Could not copy files from the files source.
```

and

```
Error installing template
Unable to install new template from temporary folder.
```
My temporary folder has 755 read/write property

### Expected result

**Copy** of (Cassiopea and Atum) to **override them**

### Actual result

Error

### System information (as much as possible)

Joomla  4.0.0-beta1-dev

**Comment by Quy** [comment]
Duplicate #26259

**Comment by ghost** [comment]
Thank you Quy

Sorry for duplicate

Have a good night or day where ever you are :)
