### ISSUE TITLE
[4.0] RFC component icons

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27770]
In the dashboards of joomla 4 we have a situation where sometimes there is an icon and sometimes not.

### components dashboard - no icons
![image](https://user-images.githubusercontent.com/1296369/73606781-b366ca80-45a5-11ea-8d9e-064ab116e781.png)

### users dashboard - has icons
![image](https://user-images.githubusercontent.com/1296369/73606788-c083b980-45a5-11ea-863c-fbeb633e85a6.png)

The reason for this is that the components dashboard is dynamically created while the others are statically defined (with an icon)
https://github.com/joomla/joomla-cms/blob/118d4c008fb899301fc7d69979c8f2ec322c8653/administrator/components/com_menus/presets/users.xml#L37-L41

This can be resolved by updating the sql so that the params field in the menus table includes for example.
`"menu_icon":"fa fa-puzzle-piece",`

The alternate menu already uses this param
![image](https://user-images.githubusercontent.com/1296369/73606922-9c28dc80-45a7-11ea-893f-17cc82414981.png)

Thoughts? Backwards Compatibility issues? Extension issues?

**Comment by Bakual** [comment]
I guess that works, and if it's in the SQL, then we can also remove the hardcoding.

Just needs also a way for 3rd party to populate those menu params, which currently imho doesn't work. But that should be doable I guess.

**Comment by brianteeman** [comment]
I have the icons working now - will submit the pr after the rugby ;)

**Comment by brianteeman** [comment]
@Bakual see #27773
