### ISSUE TITLE
[4.0] Global Configuration missing values?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27778]
Since the change in global configuration to use True/False instead of 1/0 the display of the current value is missing on page load if the value is false instead of 0

In this example you will see that it doesn't say the state of the Debug Language but it does for Debug System
![image](https://user-images.githubusercontent.com/1296369/73615836-ba242a80-4603-11ea-9aa9-bbcc57509d48.png)

This is because I set
```
	public $debug = 0;
	public $debug_lang = false;
```

As soon as I save it they will both be set to false and appear like
![image](https://user-images.githubusercontent.com/1296369/73615864-03747a00-4604-11ea-8574-b5627003cc47.png)

I am guessing that the same/similar fix that was applied to System Information #27553 would work here as well

**Comment by SharkyKZ** [comment]
See PR https://github.com/joomla/joomla-cms/pull/27098.

**Comment by brianteeman** [comment]
Thanks
