### ISSUE TITLE
Joomla installation issue Mac OS 16" Catalina and MAMP 5.6

### ISSUE THREAD

**Issue by andriesbron** [joomla/joomla-cms#27789]
### Steps to reproduce the issue

Mac OS 16" Catalina
MAMP 5.6
Download latest Joomla
put it in the htdocs of Mamp
Make all directories readable+writable for everyone (development reasons)
Browse with Safari to the site

### Expected result

See Joomla installation page

### Actual result

Safari shows server too busy, dropped the connection.

### System information (as much as possible)

0   libxml2.2.dylib               	 xmlParseDocument + 236
1   libxml2.2.dylib               	 xmlDoRead + 192
2   libxml2.2.dylib               	 xmlReadFile + 85
3   libphp7.so                    	 zif_simplexml_load_file + 309
4   libphp7.so                    	 ZEND_DO_ICALL_SPEC_RETVAL_USED_HANDLER + 153
5   libphp7.so                    	 execute_ex + 102
6   libphp7.so                    	 zend_execute + 1446
7   libphp7.so                    	 zend_execute_scripts + 611
8   libphp7.so                    	 php_execute_script + 1355
9   libphp7.so                    	 php_handler + 1881
10  httpd                         	 ap_run_handler + 101
11  httpd                         	 ap_invoke_handler + 420
12  httpd                         	 ap_process_request + 120
13  httpd                         	 ap_process_http_connection + 141
14  httpd                           ap_run_process_connection + 101
15  httpd                         	 ap_process_connection + 117
16  httpd                         	child_main + 1537
17  httpd                         	 make_child + 390
18  httpd                         	 perform_idle_server_maintenance + 713
19  httpd                         	 ap_mpm_run + 1447
20  httpd                         	 main + 3087
21  libdyld.dylib                 	 start + 1

### Additional comments

When I download previous versions of Joomla, 3.8 this also happens on this configuration.
When I change the php version to an earlier version it also happens.
It does not happen when I try to install a backup made with Akeeba.
It seems to happen only with new fresh installed software.
It appears to be a joomla installation issue, but am not sure.

**Comment by andriesbron** [comment]
Reloading the page several times sometimes shows the page. This looks like a process on my PC is disturbing something rather than Joomla!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27789">issues.joomla.org/tracker/joomla-cms/27789</a>.</sub>

**Comment by Quy** [comment]
Please post in Joomla Forum for assistance https://forum.joomla.org/ . If a bug is found, please provide detailed information. Thanks.

**Comment by andriesbron** [comment]
This was an error in the MAMP server, now solved in MAMP 5.7
