### ISSUE TITLE
[4.0] Admin Global Configuration Cookie Labels

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#27787]
### Steps to reproduce the issue

In Global Configuration set either Cookie Domain or Cookie Path to invalid values and logout.  

### Expected result

Normal login.

### Actual result

You will not be able to login. The login form appears dead. You may not remember what you were doing before logging out and spend days trying to figure out what went wrong. I did!

### System information (as much as possible)

J4-beta1-dev

### Additional comments

It would be nice if the cookie path label had a warning to the effect that 'Setting an invalid value will disable login - edit configuration.php to fix'. Or populate with the site path if it is empty.

**Comment by brianteeman** [comment]
Whilst it was unfortunate what happened to you I dont believe that the user interface is the place to document everything. 

In this particular example do you really believe that the message would have prevented you entering an invalid value. I don't as presumably you thought it was correct when you entered it.

**Comment by ceford** [comment]
My motivation was to help prevent some unfortunate soul losing a site. I notice that there is no descriptor for the Cookie Path field (COM_CONFIG_FIELD_COOKIE_PATH_DESC is not present in the language file). If there were a helpful message I would have seen it in one of the other sites I created and it might have helped me figure out what went wrong. And no coding involved! Should I go back to the Forum and ask for RFC on the wording of a label for the Cookie Path field?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27787">issues.joomla.org/tracker/joomla-cms/27787</a>.</sub>

**Comment by brianteeman** [comment]
I really dont agree that this description would have helped you. It is no different to lots of fields where the incorrect values will kill your site

**Comment by ceford** [comment]
OK. Let's forget it. I will close this issue.

**Comment by brianteeman** [comment]
It will be useful to add this to the docs web site
