### ISSUE TITLE
[4.0] Custom jdoc position in Admin atum template

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#27791]
Would it be possible to add a custom jdoc position to the atum template index.php file just before header? For me it would be the location of a custom top menu which I have created and tested. It just needs a line in index.php and a position in templateDeatails.xml. Example:

	<jdoc:include type="modules" name="topmenu" style="none" />
	<position>topmenu</position>

This change would avoid the need to create a separate template.

**Comment by brianteeman** [comment]
Just submit a pull request

**Comment by ceford** [comment]
I submitted a pull request - my first ever. And it scared the hell out of me when it said there were thousands of changes to commit. I had selected the staging branch rather than the j4dev branch. Changed that after a couple of minutes with a big sigh of relief.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27791">issues.joomla.org/tracker/joomla-cms/27791</a>.</sub>

**Comment by Quy** [comment]
Thank you for contributing! You will get the hang of it in no time. See #27793
