### ISSUE TITLE
[4.0] RFC metatags preview

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27794]
Is there any interest in something like this being part of the core

https://metatags.io/

Basically it would be in addition to the meta fields that we have and would provide a live preview of how the page would appear when shared on a variety of platforms

**Comment by Fedik** [comment]
That would be a nice feature, I think

**Comment by micker** [comment]
yes realy good !
maybe this can be a interesting ? https://github.com/vistamedia/socialmeta

**Comment by simbus82** [comment]
Thank you @brianteeman! This is a great feature that i want to see in a CMS that have to help people's websites to be performant and useful: it's a **SEO feature** too!
I'm a SEO and a feature like this is great! It can be **really useful for social sharing** too.

About the feature to preview snippets, i can say that the **only problem** will be manage in the time "how" search engines (Google, Bing, Yandex and Baidu... if we want to be "universal") and the social platforms change the **rendering of snippet**s in SERPs.

It would be fantastic to have this **preview** both in the **menu items**, both in the **articles** and in the **categories** ... so as to respect the various inheritances and overwriting of data in Joomla.

I hope people here judge this feature valid and important. Unfortunately Joomla Github is frequented massively by developers, not by Marketers, not by Copywriters, not by SEO Experts, not by Web Project Managers.
_I hope my bless can be important :-P_

**Comment by brianteeman** [comment]
One of the reasons for making this an RFC is that my other pull requests to improve meta data are all still waiting tests and approval

**Comment by richard67** [comment]
> my other pull requests to improve meta data

@brianteeman Would it be helpful if you post a list here as reference so we can find them more easily?

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/27359
https://github.com/joomla/joomla-cms/pull/25258

**Comment by 4digitalworld** [comment]
@brianteeman I think this is great! This is needed in Joomla!
It may also be compatible with this request - [https://github.com/joomla/joomla-cms/pull/10932](https://github.com/joomla/joomla-cms/pull/10932)

**Comment by brianteeman** [comment]
@sanek4life read that link and you will see it has already been done

**Comment by jeckodevelopment** [comment]
It would be a good improvement Brian. Thank you
