### ISSUE TITLE
TinyMCE problem with element name

### ISSUE THREAD

**Issue by mvanvu** [joomla/joomla-cms#27809]
Follow the file /media/editors/tinymce/js/tinymce.js at line 47

`var name = element ? element.getAttribute('name').replace(/\[\]|\]/g, '').split('[').pop() : 'default', // Get Editor name`
So, If I have two editors with the names are jform[description] and  jform[en-GB][description] then the editors will not work perfectly because the editors are the same name "description".

**Comment by brianteeman** [comment]
Any reason why your fields are not named jform[description] jform[en-GBdescription]

**Comment by mvanvu** [comment]
> Any reason why your fields are not named jform[description] jform[en-GBdescription]

It just an example. I have many language codes and I want to get the post data as an array not a string.

**Comment by mvanvu** [comment]
Nevermine but it's an issue. I think we should check the ID of textarea instead the name that will be replaced by some restriction.

**Comment by Fedik** [comment]
You need to provide a detailed info what you doing and what exactly does not work.

This behavior made to make possible to override the editor settings, by plugins etc.

The ID cannot be used, because example in subform it will be different id for the same editor name. that make overide not possible.

**Comment by jwaisner** [comment]
@mvanvu Can you please provide information asked by Fedik?

**Comment by mvanvu** [comment]
@jwaisner 
1. Edit the xml file /administrator/components/com_content/models/forms/article.xml
2. Add the new test fields into the end of form at line 1069
```xml
<fields name="test">
		<field
				name="articletext"
				type="editor"
				label="COM_CONTENT_FIELD_ARTICLETEXT_LABEL"
				description="COM_CONTENT_FIELD_ARTICLETEXT_DESC"
				filter="JComponentHelper::filterText"
				buttons="true"
		/>
</fields>```
3. Edit the edit layout file /administrator/components/com_content/views/article/tmpl/edit.php
4. Add the new code under line 71
```php
<?php echo $this->form->getInput('articletext'); ?>
<?php echo $this->form->getField('articletext', 'test')->input; ?>
```
5. Edit or add new article you will see the new editor. From the second editor, try to insert an image from the image button or any button you want and you will see the image will be inserted into the first editor not the second editor.

**Comment by mvanvu** [comment]
I have also submitted a PR #25931 for the same issue but look like no one care.

**Comment by Quy** [comment]
@mvanvu You have not commented/updated with suggested changes in PR #25931. So this issue already has PR #25931?

**Comment by mvanvu** [comment]
@Quy No, the PR #25931 for another issue that has the same issue with TinyMCE editor.

**Comment by jwaisner** [comment]
@mvanvu can you clarify what PR #25931 has to do with this issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27809">issues.joomla.org/tracker/joomla-cms/27809</a>.</sub>

**Comment by mvanvu** [comment]
@jwaisner I just close because it was there so long and nobody pay attention to it.

**Comment by Quy** [comment]
See PR #28321
