### ISSUE TITLE
[4.0] Show Password accessibility

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27801]
While testing #27733 I discovered a new accessibility issue with the show password button. When you press the button the password is revealed - which is correct. But there is no indicator that this has happened to a non sighted user.

After looking around to see how others address this I see it is a common failure (but that's not a reason for us not to fix it if we can)

The best example I have seen is with google and it is really very simple.

On selecting the show password button the focus is redirected to the password field

![after](https://user-images.githubusercontent.com/1296369/73732340-ea69e700-4731-11ea-97ab-dcec4a7fa0f9.gif)

**Comment by ghost-in-the-machine-web** [comment]
test

**Comment by brianteeman** [comment]
Closing as we have a pull request to test #27821
