### ISSUE TITLE
[4.0] mobile button visible on desktop

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27805]
### Steps to reproduce the issue
The toogle toolbar button is not _hidden_ on the desktop view and is focussable (can be clicked on)

To make it easier to see add the following code to the template.css

```
navbar-toggler {
    background: red;
}


```
### Expected result
nothing happens

### Actual result
clickable red box
![after](https://user-images.githubusercontent.com/1296369/73792247-cfcc5800-479b-11ea-81a6-bf6487d30803.gif)

### Additional comments
This is because at desktop resolutions the css for the toggler is

```
.navbar-toggler {
    padding: .25rem .75rem;
    font-size: 1.25rem;
    line-height: 1;
    background-color: transparent;
    border: 1px solid transparent;
}

```

This makes it contents  visually invisible but not hidden from the page and important not removed from the accessibility tree unlike the burger menu icon for toggling the menu on mobile

### Burger button (desktop resolution)
![image](https://user-images.githubusercontent.com/1296369/73792084-87149f00-479b-11ea-992a-fd28ebbe5db2.png)

### Toolbar button (desktop resolution)
![image](https://user-images.githubusercontent.com/1296369/73792147-9f84b980-479b-11ea-9ec1-c3c12970edff.png)

**Comment by brianteeman** [comment]
This is probably caused by the changes made in #27705

**Comment by ravisaxena23** [comment]
i guess CSS is same as written in  navbar-toggler button but i will look into it. what can be done to correct it? i feel collapse class is not working for gear button or break point not working.?

**Comment by infograf768** [comment]
What if we re-add the class `toggler-burger` for the button line 152 of index.php ?
```
<button class="navbar-toggler toggler-toolbar collapsed" type="button" data-toggle="collapse" data-target=".subhead" aria-controls="subhead" aria-expanded="false" aria-label="<?php echo Text::_('TPL_ATUM_TOOLBAR'); ?>">
 				<span class="toggler-toolbar-icon"></span>
 			</button>
```

**Comment by ravisaxena23** [comment]
@infograf768 @brianteeman please check

**Comment by brianteeman** [comment]
Closing as we have a pr for testing #27818
