### ISSUE TITLE
[Smart Search]: displaying search results with image thumbnails

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#27815]
Search engines such as [Google](https://www.google.com/cse/all) and [Yandex](https://site.yandex.com/) allow you to display site search results along with thumbnails of images for each link.

I suggest adding a thumbnail image display for each link to the site search results (**Smart Search**).

**Of course, in the settings there will be such options as:**

- thumbnails of images: show/hide
- tab with picture search: show/hide

**The thumbnail image will be displayed with the following settings:**

- Minimum image size for searching 100x100 px
- The thumbnail image will be retrieved from the field `Into Image` (tab: `Images and Links`)
- If no `Intro Image` is specified, then the first image that is added to the article through the editor will be displayed.
- If the article does not contain images, then the link will be displayed without a thumbnail image

![изображение](https://user-images.githubusercontent.com/3662519/73844961-aca0b780-4832-11ea-9075-d3cfe26efca6.png)

I think that the database will not grow too much, because all text and all article data has already been indexed. For the database, only one parameter will be added - a thumbnail image.
I believe that this is a very important feature for Smart Search in Joomla. It may also be related to this request - [https://github.com/joomla/joomla-cms/issues/27813](https://github.com/joomla/joomla-cms/issues/27813)

**Comment by brianteeman** [comment]
That's appropriate for a search engine but I don't see its use on an individual web site. Certainly not enough of a use for it to be in the core

**Comment by 4digitalworld** [comment]
> 
> 
> That's appropriate for a search engine but I don't see its use on an individual web site. Certainly not enough of a use for it to be in the core

Now it’s not 2005. This is a custom search for a website. Google doesn’t use thumbnails images in its primary Google.com search, but it does provide the opportunity for websites that have added website search to their website.

The web is changing, over the past 15 years, everything has changed a lot, but for the average user, Joomla looks the same as she was in 2005. This is not something unnecessary, this feature is very popular for each individual website.

Then you must either remove any search from the core of Joomla, or develop a search so that it meets modern web standards.

Websites are not just for developers who publish code in an article. The vast majority of websites have an entertaining theme. Joomla is losing its share compared to Wordpress, because it does not meet the modern standard for editors and website users.

**Comment by brianteeman** [comment]
Show me a web site using images in its search.

**Comment by gerryfrancis** [comment]
There are some Google Search-powered sites, e.g. notebookcheck.net, which do that.

But, TBH, showing a thumbnail next to the link only makes sense to me if the image is big enough to touch it with my fingers to open the link.

**Comment by 4digitalworld** [comment]
> 
> 
> Show me a web site using images in its search.

[https://www.rollingstone.com/results/#?q=the%20beatles](https://www.rollingstone.com/results/#?q=the%20beatles)
[http://www.mtv.com/](http://www.mtv.com/)

**Comment by 4digitalworld** [comment]
> 
> 
> There are some Google Search-powered sites, e.g. notebookcheck.net, which do that.
> 
> But, TBH, showing a thumbnail next to the link only makes sense to me if the image is big enough to touch it with my fingers to open the link.

You can set the size of the thumbnail to display in the search settings. it can be for example 100x100 or 500x500, it is not so important, each webmaster will install it in the settings on his own.

Now almost all news sites use site search along with thumbnails of images from articles.

**Comment by 4digitalworld** [comment]
> 
> 
> Show me a web site using images in its search.

@brianteeman It uses even Techcrunch!!!
[https://search.techcrunch.com/search;_ylc=X3IDMgRncHJpZANuVElYNjNGdFNBT3JLa0RVNVZCQkZBBG5fc3VnZwM5BHBvcwMwBHBxc3RyAwRwcXN0cmwDMARxc3RybAM3BHF1ZXJ5A2FuZHJvaWQEdF9zdG1wAzE1ODA5OTIyNDc-?p=android&fr=techcrunch](https://search.techcrunch.com/search;_ylc=X3IDMgRncHJpZANuVElYNjNGdFNBT3JLa0RVNVZCQkZBBG5fc3VnZwM5BHBvcwMwBHBxc3RyAwRwcXN0cmwDMARxc3RybAM3BHF1ZXJ5A2FuZHJvaWQEdF9zdG1wAzE1ODA5OTIyNDc-?p=android&fr=techcrunch)

**Comment by chrisdavenport** [comment]
If memory serves, the image data is already stored in the #__finder_links table, so you just need to write a template override to include the image in the search results.

**Comment by 4digitalworld** [comment]
@brianteeman I think this is not your problem if you have not used search on various websites in the past 15 years. I myself almost do not use search, but when I need a search, almost everywhere I see articles in search along with thumbnails of images! I believe that this is already the standard for many news websites.

Please add these few lines of code so that in the search you can make an option to show (or hide) thumbnails of images for each article. I don’t think it’s very difficult to do, but it will make Joomla much more friendly for each user, for each administrator and editor.

**Comment by 4digitalworld** [comment]
> 
> 
> If memory serves, the image data is already stored in the #__finder_links table, so you just need to write a template override to include the image in the search results.

I know it! Therefore, I suggest adding a setting to show thumbnails of images from articles. This is not so hard. Why invite each site administrator to override the template when you can make this setting available to everyone once? I think Joomla will be much better if this setting appears.

**Comment by 4digitalworld** [comment]
@brianteeman @chrisdavenport All data has already been indexed. This will not spoil the database for sites. Just add this setting for website administrators on Joomla. This will greatly simplify life and improve the user experience!

**Comment by brianteeman** [comment]
Please, please no more options.
Every time you add an option you kill a kitten

**Comment by 4digitalworld** [comment]
> 
> 
> Please, please no more options.
> Every time you add an option you kill a kitten

But **[Techcrunch](https://search.techcrunch.com/search;_ylc=X3IDMgRncHJpZANuVElYNjNGdFNBT3JLa0RVNVZCQkZBBG5fc3VnZwM5BHBvcwMwBHBxc3RyAwRwcXN0cmwDMARxc3RybAM3BHF1ZXJ5A2FuZHJvaWQEdF9zdG1wAzE1ODA5OTIyNDc-?p=android&fr=techcrunch)** disagrees with you. This is the standard of today's web. Search with thumbnails from articles. This is the standard.

![изображение](https://user-images.githubusercontent.com/3662519/73937894-1c787600-48f7-11ea-8c07-f1f2a65184c8.png)

**Comment by 4digitalworld** [comment]
> 
> 
> Show me a web site using images in its search.

[https://search.engadget.com](https://search.engadget.com/search;_ylc=X3IDMgRncHJpZAMzcFNBMFdrVVNRNmxMR2xMaEtrVGlBBG5fc3VnZwM5BHBvcwMwBHBxc3RyAwRwcXN0cmwDMARxc3RybAM3BHF1ZXJ5A2FuZHJvaWQEdF9zdG1wAzE1ODA5OTMwMzc-?p=android&fr=engadget)

[https://www.theverge.com/search?q=android](https://www.theverge.com/search?q=android)

How many links to websites should I send? I think that this is clear to everyone, this is the standard of the web industry of our day.

**Comment by brianteeman** [comment]
As already explained by @chrisdavenport you can achieve this with an override. 

Joomla can not and should not have options for every thing that someone thinks will be useful to them.

I am closing this

**Comment by 4digitalworld** [comment]
@brianteeman I think I need to change the Joomla CMS to the WordPress.
I write articles on a website that has been using Joomla since 2007, from version 1.0.
I see absolutely no development of this CMS for editors and for a more convenient publication of articles on the website. I think I was wrong when I read the word CMS in 2007, which means **CONTENT MANAGEMENT SYSTEM**.

If this is a management system for developers and css-designers, then I think that we need to remove the word CMS from the name Joomla. Leave just Joomla - a software package for developers and css-designers.

Over the 15 years I have seen improvements only for designers, developers and not a single improvement for content editors. I was mistaken in 2007.

**Comment by gerryfrancis** [comment]
@sanek4life I do not agree. Joomla! is a CMS, not perfect, but consistent. There are lots of plugins available that are capable to manage content the way you want to have it, so no need to change to WordPress. Even those sites have to be programmed and styled individually, which is called web design.

It seems that you are a true editor, that is totally fine. Whatever CMS you want to use, you probably need someone who builds your website just the way you want it to be. Should your site ever be relaunched, Joomla!, as an open-source application with a great community of users and developers, can be shaped just right. WordPress might be comparable, and thus I believe that one day you would reach its limitations, too. As long as you cannot/do not want to extend them by yourself by programming or implementing a(n existing) solution, you will never get what you want, neither with Joomla! nor with WordPress.

**Comment by 4digitalworld** [comment]
> 
> 
> Show me a web site using images in its search.

@brianteeman I found this website! officially!

[https://forum.joomla.org/](https://forum.joomla.org/) - The official Joomla forum uses **[Google Custom Search](https://cse.google.com/cse/all)** for websites.

[https://cse.google.com/cse/all](https://cse.google.com/cse/all) - @Joomla team uses this @google search for his forum because his own search is not good enough! I believe that this is an official recognition that the search is not good enough in Joomla.

Why don't you still want to add a few lines of code for image thumbnails?

You have spent so much time and human resources on completely useless things - the design of the `Control Panel` and unnecessary `Tags` that you forgot about the functions for creating articles.

I believe that I no longer need to prove why I'm right. Just look at this screenshot:

![изображение](https://user-images.githubusercontent.com/3662519/73955960-450f6880-4915-11ea-8804-ea60f8e49472.png)

I absolutely do not think that adding some small, but very important functions for the Joomla editor will have difficulty with support in major versions. That's bullshit. It is a reluctance to do at least something good.

Nobody needs `Tags` and the endless redesign of the `Control Panel`, which you spent so many lines of code on and which have much more compatibility issues than thumbnails or **[lazy loading](https://github.com/joomla/joomla-cms/issues/27761)**.

I'm as an editor, it doesn’t matter to me and it doesn’t matter what the design will be in the `Control Panel`, I won’t write long articles on the phone, I do it on the PC. And for me, `Tags` do not matter, because From the very beginning, the Joomla was built on `Categories`, `Nested Categories`, and the logical step was to make **[Multi Categories](https://github.com/joomla/joomla-cms/issues/9838)** (instead, `Tags` were made for nobody).

**Comment by brianteeman** [comment]
Sorry I am not engaging you with any more.

**Comment by mbabker** [comment]
@sanek4life at this point you're just trolling.  If you took more than 2 seconds to look at the forums you would know those aren't even running Joomla.

As is explained, all the data is there for you to do what you desire to do, it requires you to create and maintain template overrides for the functionality.  It's up to you to get your hands dirty and do some work and not expect everyone else to do it for you.

**Comment by 4digitalworld** [comment]
@mbabker Instead of writing articles and publishing content, should I study programming?

Maybe if I get sick, should I be a doctor? Do I have to be a shepherd to eat food? Who else do I need to be? I am not asking for something supernatural. These are the basic needs for a CMS.

I am not writing about the need to make a new template for Joomla. There are functions that should be in every Joomla template, so I believe that this should be implemented in the core, because every editor needs it.

I'm sorry you do not understand this. Why are you doing CMS if you don’t understand what it means to be an editor? Who are you doing CMS for programmers for? Wordress and Drupal - that would be the right decision for me in 2007, I am sorry that I chose Joomla 1.0 many years ago.

[oEmbed](https://github.com/joomla/joomla-cms/issues/27385) was included in the core of Wordpress and Drupal many years ago. When I use Joomla, I am offered to use third-party extensions, which very often stop releasing their extensions when switching to a new major version of Joomla - this was from 1.5 and from 2.5 and from 3.x and now it will be the same with 4.x I saw it is so many times.

**Comment by mbabker** [comment]
And I'm sorry you seem to think it's OK to crap over the work of the third party ecosystem and demand that every function you need be an integrated part of the core platform.  I'm also sorry you seem to think that Joomla should look and behave exactly the same as every other CMS out there.

I'll save you the couple hundred dollars an hour that would normally be charged for my consulting services and offer you a bit of free advice.  Go use a CMS that fits your use case and stop demanding that the CMS change to fit your use case.

**Comment by polynamaude** [comment]
> > That's appropriate for a search engine but I don't see its use on an individual web site. Certainly not enough of a use for it to be in the core
> 
> Now it’s not 2005. This is a custom search for a website. Google doesn’t use thumbnails images in its primary Google.com search, but it does provide the opportunity for websites that have added website search to their website.
> 
> The web is changing, over the past 15 years, everything has changed a lot, but for the average user, Joomla looks the same as she was in 2005. This is not something unnecessary, this feature is very popular for each individual website.
> 
> Then you must either remove any search from the core of Joomla, or develop a search so that it meets modern web standards.
> 
> Websites are not just for developers who publish code in an article. The vast majority of websites have an entertaining theme. Joomla is losing its share compared to Wordpress, because it does not meet the modern standard for editors and website users.

@sanek4life Damn it !
You're a real nut when it gets to repeating over and over again the same thing. We all know we ain't in 2005. Honestly, pay someone on UpWork to modify a fork that will suit your needs and let people live a bit.
You are filling my mail account with the same message over and over again. Stop looking at your own bellybutton and ask yourself if you are the only one on a island ? Acting this way will lead you a empty island if you don't give it a break.

You seem pretty good at repeating that we don't understand you as a editor. I doubt you take time to understand what motivate other people. It's easy to have opinion on developers but try to do the coding and we'll have a chat.

Nothing is owed to you. All you get is free, so either you appreciate it or go somewhere else.

**Comment by polynamaude** [comment]
> > Show me a web site using images in its search.
> 
> @brianteeman I found this website! officially!
> 
> https://forum.joomla.org/ - The official Joomla forum uses **[Google Custom Search](https://cse.google.com/cse/all)** for websites.
> 
> https://cse.google.com/cse/all - @joomla team uses this @google search for his forum because his own search is not good enough! I believe that this is an official recognition that the search is not good enough in Joomla.
> 
> Why don't you still want to add a few lines of code for image thumbnails?
> 
> You have spent so much time and human resources on completely useless things - the design of the `Control Panel` and unnecessary `Tags` that you forgot about the functions for creating articles.
> 
> I believe that I no longer need to prove why I'm right. Just look at this screenshot:
> 
> ![изображение](https://user-images.githubusercontent.com/3662519/73955960-450f6880-4915-11ea-8804-ea60f8e49472.png)
> 
> I absolutely do not think that adding some small, but very important functions for the Joomla editor will have difficulty with support in major versions. That's bullshit. It is a reluctance to do at least something good.
> 
> Nobody needs `Tags` and the endless redesign of the `Control Panel`, which you spent so many lines of code on and which have much more compatibility issues than thumbnails or **[lazy loading](https://github.com/joomla/joomla-cms/issues/27761)**.
> 
> I'm as an editor, it doesn’t matter to me and it doesn’t matter what the design will be in the `Control Panel`, I won’t write long articles on the phone, I do it on the PC. And for me, `Tags` do not matter, because From the very beginning, the Joomla was built on `Categories`, `Nested Categories`, and the logical step was to make **[Multi Categories](https://github.com/joomla/joomla-cms/issues/9838)** (instead, `Tags` were made for nobody).

@sanek4life Who are you to have knowledge about who's using the Tag system and who like the new Control Panel ?

What have you done lately ? Not end-user style, I'm talking about real stuff. This forum is not really meant for end-user. You may not be at the good place.
