### ISSUE TITLE
[4.0] The Road to Beta ?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27812]
# The Road to Beta

Joomla 4 has been under development for a very long time now and the first alpha release is now almost two and half years ago (17 Nov 2017). The vast majority of the work has been done by just a handful of people and they are all close to (or have reached) burn out.

_These are my personal views and opinions gathered from my involvement in the development of joomla 4, the available public information and experience of participating in taking Joomla through 5 major releases_

# Definitions
## Alpha Release
This is an early technology preview. It **should** contain all breaking changes but things can still be added and removed

## Beta Release
This a general release for review. It **must** contain all breaking changes and be feature complete (no new features can be added after a beta release). It **will** probably still contain bugs and will not be suitable for mainstream use.

## Dot Zero Release
This is the first release. It is available for general use.

## Dot Zero Dot One Release
This is the first bug fix release. It does **not** contain any new features. It does **not** have any breaking changes. It does have bug fixes discovered since the Dot Zero release.

## Dot One Release
This is the first feature release. It **can** contain new features. It does **not** have any breaking changes. It does have bug fixes discovered since the Dot Zero Dot Previous release.

# Where should we be at now?
All breaking changes have been made and documented
All new features have been created and documented
> We should be polishing in preparation of the first Beta Release

# Where are we at now?

## API & Underlying Code
- [x] Namespacing 
- [x] Prepared statements
- [x] Web Services
- [x] Deprecations
- [ ] Documenting above

## Accessibility
- [x] Admin Interface
- [ ] Site Interface
- [x] Acknowledge that Accessibility can always be improved

## Admin Template/UI
- [x] Tested
- [x] RTL
- [x] Mobile
- [x] Template Manager complete
- [x] Expectation of further issues created during wider beta testing phase
 
## Site Template/UI
- [ ] Tested
- [ ] Blog layout changes documented and completed
- [ ] RTL
- [ ] Mobile
- [x] Expectation of further issues created during wider beta testing phase

## Installation
- [x] UI complete
- [ ] Language Install
- [ ] FTP Install
- [x] Sample data plugins for J4

## Upgrades
- [x] Tested
- [ ] Document known issues
- [x] Expectation of issues created during wider beta testing phase

## Translation
- [ ] Infrastructure for delivering translations
- [x] Pro-actively engage with translation teams to encourage completion

## Web Services
- [x] Working as a basic technology preview and will always need ongoing development
- [x] Documented  

## Content Security Policy
- [x] Working
- [x] Documented

## Mail Templates
- [x] Extend to all core mails
- [x] Address html/plain text issues
- [x] Finalise the UI for creating texts 

## Media Manager
- [ ] Review
- [ ] Documentation

## External Assets
- [ ] Finalise
- [ ] Update
- [ ] Define version policy
- [ ] Let them know and engage

## Alerts/Popups
- [ ] Complete autodismiss
- [ ] Finalise design
- [ ] Static alerts/notices 

## Security
- [ ] Full private review

## SEO Review
- [ ] Ensure following current needs

# How do we get to Beta?
- Acknowledge that a Release Blocker is not the same as a Beta Blocker
- Set a HARD deadline and If a proposed new feature is not committed by then flag as Postpone to 4.1
- Review list above and ensure that every item has been adopted by at least one person AND that they are actively working on it
- Using the github _trello_ boards for this will really help

# Elephants in the Room
~## Alternative Admin Template
Set a HARD deadline and if it does not satisfy the established requirements by then it will unfortunately not be able to go into Beta~

## Workflows
~There are several relatively minor issues open on the tracker. They all relate to UI and not underlying code. They are open because a few people have insisted that it is replaced with a completely different codebase so no one wants to waste time fixing the open issues on code that will be replaced.~
~The reality is that the people insisting on these workflow changes have not documented them anywhere on this tracker (or at least I could not find them) so no one else has been able to work on them. The time that this should have been addressed was 18 months ago not now~
~To the best of my knowledge there is no new code under development for this. .There is a mention of a team working on this in the [October Production Department meeting minutes](https://volunteers.joomla.org/departments/production/reports/1127-production-dept-meeting-october-22-2019) and that this team has written a plugin but there is nothing further after that reported [anywhere](https://volunteers.joomla.org/teams/joomla-enhancement-development-team)~ 
~There are three choices~
~- Fix outstanding issues with current code and accept some people don’t like the architecture~
~- Revert the workflow commits and release with the old workflow - this is not a simple quick task as it touches a lot of areas. It will also be very hard (perhaps impossible) to add workflows in a later release due to backwards compatibility issues~
~- Set a HARD deadline for this new codebase and if not ready go with the other options~

# Post Beta
After the first beta we then need to apply the same rigidity in order to move to a Dot Zero release.

## Triage all new issues
- I don’t like it - is not useful - every issue must have a concrete suggestion or closed
- If it is a new feature suggestion then flag as Postpone to 4.1

## Documentation
- Ensure that user documentation is ready not just developer documentation
- Create Joomla 4 Training videos

## Certification
- the exams should be able to be written at this stage

## Completion
Life gets in the way of contribution. It’s a fact and we must acknowledge that. So if you can not honour a commitment there is no shame but it must be re-allocated. This can not be left to “thinking” someone is working on it. This needs to be actively and continuously reviewed to ensure nothing falls through the gaps.

**Comment by N6REJ** [comment]
Thanks for a well written document @brianteeman

**Comment by od-martin** [comment]
Well spoken!

Unfortunately, my English is not nearly as good (which annoys me extremely) to actively contribute to the development. But I learn more every day and hope to be able to make my contribution someday.

What happened in the forums in the last few days is not understandable. Instead of ALL working together and finally completing J4, the meaningfulness of a new backend template is discussed.
(I personally think the alternative backend is very good). If someone wants to develop a template, then please do it too. Whether it should be installed now, remains to be seen.

So I can only appeal to everyone to GO TOGETHER to release J4. The current development does not make a good impression in public and scares many users.

If I can contribute something that corresponds to my current knowledge, please let me know.

best regards

**Comment by richard67** [comment]
So as @brianteeman correctly pointed out, the next step should be to assign people to the particular tasks and set timelines. Who will do than when and where?

**Comment by brianteeman** [comment]
Sorry if you misunderstood. My intention was to list what needs to be done and not to suggest that people should be **assigned** to a task.

**Comment by horus68** [comment]
On translations:
- You can mark as solved the "Pro-actively engage with translation teams to encourage completion". There are lots of translations more then 99% and some days they are 100%, it depends when new strings being added. 
When the RC version will be released the translations for the most used languages will be 100%... as always! 

- On the "Infrastructure for delivering translations" this should be marked as a Dream for version 5.x

**Comment by richard67** [comment]
@brianteeman Then I maybe misunderstood the following in your list in section "How do we get to Beta?":

>- Set a HARD deadline and If a proposed new feature is not committed by then flag as Postpone to 4.1
>- Review list above and ensure that every item has been adopted by at least one person AND that they are actively working on it

So for me the above seem to be the next logical steps, and the 2nd item implied to me that someone has to assign people, or at least people have to assign themselves and someone has to keep an eye on it to identify unassigned topics.

So the very next step would be to clarify who will be "someone" ;-)

**Comment by richard67** [comment]
You know I just don't want that everybody likes this very good summary here but nothing happens then.

**Comment by brianteeman** [comment]
> people have to assign themselves and someone has to make a list.

That is what I meant

**Comment by 200MPHMEDIA** [comment]
If I were a programmer, would be more than happy to take on projects.  Certainly have time to do it.  But, coding, PHP, and all that stuff just isn't in my portfolio.  Appreciation is extended to all those that devote much time to making Joomla! 4 a good product.  Thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27812">issues.joomla.org/tracker/joomla-cms/27812</a>.</sub>

**Comment by Quy** [comment]
`Alternative Admin Template` It appears development has ceased.

**Comment by richard67** [comment]
Any link?

**Comment by Quy** [comment]
https://github.com/joomla-projects/j4adminui/issues/186#issuecomment-583064115

**Comment by richard67** [comment]
Seems they stop for core but later wanna make 3rd party template.

**Comment by brianteeman** [comment]
lets try and keep this on topic please

**Comment by richard67** [comment]
Sorry, yes.

**Comment by brianteeman** [comment]
oh well i tried.closing due to lack of interest in organised development
