### ISSUE TITLE
behaviour when error on type of menu

### ISSUE THREAD

**Issue by web54** [joomla/joomla-cms#27828]
### Steps to reproduce the issue

go into menu
see types of menu and remember one existing
go to edit another menu (existing)
change type with existing type
get error (existing type)
enter new type (non existing)
save and close

### Expected result
should edit the menu you are in

### Actual result

create a new menu

**Comment by gerryfrancis** [comment]
The new menu certainly has a different alias ("[name]-2"), thus it really is a new menu item.

**Comment by Quy** [comment]
Closing for reason stated.

**Comment by web54** [comment]
> The new menu certainly has a different alias ("[name]-2"), thus it really is a new menu item.

yes but that should not be the right behaviour

**Comment by web54** [comment]
> Closing for reason stated.

what is the reason ?

**Comment by gerryfrancis** [comment]
The concept of Joomla! is that each item is unique and has its own ID. You cannot overwrite an item with another of the same type with the same alias name, because Joomla! "recognizes" that such an item already exists, and applies a slightly different alias ("[name]-2") to the other item.

**Comment by web54** [comment]
yes, that is why I got an error, explained by joomla, an stay in the menu I want to change.
But at this moment (after error) I enter a new type, and it copymy menu instead of editing the menu I am in.
To be more clear : If I do not make the mistake to choose an existing one, it change the type when closing without creating a copy

**Comment by SharkyKZ** [comment]
Re-opening as valid issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27828">issues.joomla.org/tracker/joomla-cms/27828</a>.</sub>

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/28053.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27828">issues.joomla.org/tracker/joomla-cms/27828</a>.</sub>
