### ISSUE TITLE
Fixing of CSS styling in the close button of add modules for any rtl language

### ISSUE THREAD

**Issue by Subhang23** [joomla/joomla-cms#27823]
### Steps to reproduce the issue

Switch to a rtl language (Ex:-Persian)
Go to dashboard and press on the add modules button
You can notice the icon for close is not properly placed

### Expected result

The icon should be placed more to the right

### Actual result
![Screenshot from 2020-02-06 13-26-02](https://user-images.githubusercontent.com/43785080/73917169-e205dd80-48e4-11ea-88b5-27e907267bf1.png)

### System information (as much as possible)

Ubuntu 18.04(Virtual Machine) PHP-7.2.24

**Comment by Subhang23** [comment]
I would like to work on this

**Comment by infograf768** [comment]
It should be easy
we have for rtl

```
 .btn.btn-danger [class*=" fa-"],
  .btn.btn-danger [class*=" icon-"],
  .btn.btn-danger [class^=fa-],
  .btn.btn-danger [class^=icon-],
  .btn.btn-danger span {
    background-color: var(--danger);
    color: hsla(0, 0%, 100%, .9);

    display: inline-block;
    width: 2.375rem;
    height: 100%;
    margin: 0 16px 0 -22px;
    line-height: 2.375rem;
  }

  .btn.btn-success [class*=" fa-"],
  .btn.btn-success [class*=" icon-"],
  .btn.btn-success [class^=fa-],
  .btn.btn-success [class^=icon-],
  .btn.btn-success span {
    background-color: var(--success);
    color: hsla(0, 0%, 100%, .9);

    display: inline-block;
    width: 2.375rem;
    height: 100%;
    margin: 0 16px 0 -22px;
    line-height: 2.375rem;
  }
```

We have to add a `[dir=rtl] & {` where the margin is
`margin: 0 -22px 0 16px;`

for both

**Comment by infograf768** [comment]
@Subhang23 
Are you going to make this specific PR?

**Comment by Subhang23** [comment]
I will be doing it. I actually made a mistake with the branches.

**Comment by infograf768** [comment]
Thanks. Please limit your changes to this issue and please test https://github.com/joomla/joomla-cms/pull/27841 which solves mobile alignment.

**Comment by Subhang23** [comment]
> Thanks. Please limit your changes to this issue and please test #27841 which solves mobile alignment.

@infograf768 I don't understand what I should do here.

**Comment by Quy** [comment]
See PR #27883
