### ISSUE TITLE
Joomla template bug

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#27838]
### Steps to reproduce the issue

    Install Joomla
    Go to extensions >> Templates >> Templates
    Open protostar template.
    Click copy template on top left.

copy protostar template it creates strange extensions file /css/template.css?c250e51230c550e0

### Expected result

/css/template.css

### Actual result

/css/template.css?c250e51230c550e0

### System information (as much as possible)

j 3,9,15, php 7.4.2

**Comment by brianteeman** [comment]
Do you have any cache extensions installed?

**Comment by ghost** [comment]
no

**Comment by brianteeman** [comment]
I can not replicate this.

**Comment by Quy** [comment]
I can not replicate too.

**Comment by Fedik** [comment]
@Milglius where do you see this file `/css/template.css?c250e51230c550e0`?

**Comment by Twincarb** [comment]
Isn't it the intended behaviour of Protostar to set a version to template.css?

// Add Stylesheets
JHtml::_('stylesheet', 'template.css', array('version' => 'auto', 'relative' => true));
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27838">issues.joomla.org/tracker/joomla-cms/27838</a>.</sub>

**Comment by brianteeman** [comment]
yes it is but from the description of the report he is saying that this is the filename created

**Comment by Fedik** [comment]
but not saying that it create in file system, 
translations may be not perfect :wink: 

I suspect he seen it in the page source code, that of course not a bug

**Comment by brianteeman** [comment]
well lets wait a few days for a reply before closing

**Comment by ChristineWk** [comment]
> I suspect he seen it in the page source code, that of course not a bug

Agree. Checked some URLs to find out the "difference" :-)

... /templates/mytemplatecopy/css/template.css" rel="stylesheet" **type="text/css"** />
.../templates/mytemplatecopy/css/user.css" rel="stylesheet" **type="text/css"** />

.../templates/protostar/css/template.css?8e17160b713641b3cc489b29e3405a51" rel="stylesheet" />
.../templates/protostar/css/user.css?8e17160b713641b3cc489b29e3405a51" rel="stylesheet" />

**Comment by Quy** [comment]
@ChristineWk Please advise which page(s) that shows the "difference".

**Comment by ChristineWk** [comment]
@Quy The first 2 lines: From an older Protostar (of course up to date) starting years ago > Template copy. 
The second 2 lines: I think, when creating a new Protostar, then it will built as above automatically.

**Comment by Quy** [comment]
OK. So this is not an issue, but a misunderstanding by the user looking at the page source and not the file system and how it is generated now vs previously?

**Comment by ChristineWk** [comment]
Agree again that is not a bug :-) Checked differences via page source. From an URL, created  years ago.

**Comment by Quy** [comment]
Closing as not a bug. Please provide details/screenshots if still an issue. Thanks.

**Comment by Twincarb** [comment]
@Quy wasn't this being kept open for the OP @Milglius to respond?

**Comment by Quy** [comment]
@Twincarb It is not locked so he can still respond. If reproducible with additional information it will be reopened.

**Comment by ghost** [comment]
It is in page source code. ChristineWk why it's not a bug? My english not the best hope you understand me now, thanks.

copy protostar name it mytemplatecopy and instead of this

... /templates/mytemplatecopy/css/template.css" rel="stylesheet" type="text/css" />
.../templates/mytemplatecopy/css/user.css" rel="stylesheet" type="text/css" />

you get this ugly code

.../templates/mytemplatecopy/css/template.css?8e17160b713641b3cc489b29e3405a51" rel="stylesheet" />
.../templates/mytemplatecopy/css/user.css?8e17160b713641b3cc489b29e3405a51" rel="stylesheet" />

Why this ugly code addition is the intended behaviourand and not the bug? is there an option to get rid ?8e17160b713641b3cc489b29e3405a51 of it ?

**Comment by SniperSister** [comment]
That „ugly code“ is a hash of the file content. It will change when the linked file is changed, causing the browser to reload that file from the server instead of using the locally cached (and now outdated) file.

That’s not a bug, it’s a feature.

**Comment by ghost** [comment]
That code makes site slow. When was such feature introduced in protostar? How to disable such a feature?

**Comment by SniperSister** [comment]
> That code makes site slow.

Because a hash is generated? Hell no, that has no measurable impact.

**Comment by ghost** [comment]
David what test you done on .../templates/mytemplatecopy/css/template.css?8e17160b713641b3cc489b29e3405a51" rel="stylesheet" />
.../templates/mytemplatecopy/css/user.css?8e17160b713641b3cc489b29e3405a51" rel="stylesheet" /> to claim this?

**Comment by SniperSister** [comment]
What have you tested to claim that it makes the site slow?

**Comment by ghost** [comment]
Joomla site . David when was such feature introduced in protostar? How to disable such a feature?

**Comment by brianteeman** [comment]
You should not disable it - it is there for very good reasons. (If you check other cms you will see they do the same/similar thing)

**Comment by ghost** [comment]
brian what reason it is?

**Comment by Fedik** [comment]
> brian what reason it is?

answer already was:

>  It will change when the linked file is changed, causing the browser to reload that file from the server instead of using the locally cached (and now outdated) file

Only correction, not when " linked file is changed" but when you update joomla, it is version based hash.
This to prevent old files loading when site updated, to avoid browser cache that may lead to unexpected behavior and bugs.

There 0 performance impact, the hash updated only once.

**Comment by ghost** [comment]
That code protostar template makes joomla site slow as hell. Do google PageSpeed Insights. It slows site by about 3 seconds.

So Fedik and David, what test you done to claim that 3 seconds is zero impact?

When was such feature introduced in protostar? How to disable such a feature?

**Comment by Twincarb** [comment]
@Milglius the change was made to the default template **3 years ago** I have not seen any speed changes with it in place. If this caused a speed issue then it would have been reported over and over on the main forum.
Due to the complex number of variables that could be causing your issues then it would be better to open a post on the main support forum. https://forum.joomla.org/

**Comment by ghost** [comment]
Dave due to the complex number of closed but unsolved issues of joomla it would be better to https://developers.google.com/speed/pagespeed/insights/

Whese tests show how bad horrible joomla template performs with thisfeature not disabled on .../templates/mytemplatecopy/css/template.css?8e17160b713641b3cc489b29e3405a51" rel="stylesheet" />
.../templates/mytemplatecopy/css/user.css?8e17160b713641b3cc489b29e3405a51" rel="stylesheet" /> to claim this?

please reopen this issue

**Comment by Fedik** [comment]
@Milglius stop this nonsense, you have an issue on your side somewhere, 
and I suspect you misunderstood what  pagespeed/insights/ said to you.
The hash itself does not affect a performance.

If you need a help in solving of your problem, please follow @Twincarb comment, and ask for help at https://forum.joomla.org/
