### ISSUE TITLE
[4.0] Missing toolbar with RTL in EdgeHTML

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#27831]
### Steps to reproduce the issue
Use Microsoft Edge.
Install Persian language.
Edit account.
Switch to Persian language for the backend language.
Click Save & Close.
Edit account.
See missing toolbar.
This is happening with toolbars in other areas.

### Expected result
![toolbar-ltr](https://user-images.githubusercontent.com/368084/73986383-572bdf80-48f2-11ea-8455-83407b442064.jpg)

### Actual result
![toolbar-rtl](https://user-images.githubusercontent.com/368084/73986388-598e3980-48f2-11ea-877f-4e1d931a8b7d.jpg)

### System information (as much as possible)
Microsoft EdgeHTML 18.18363

**Comment by brianteeman** [comment]
So this is the non-chromium edge?

**Comment by Quy** [comment]
How do I find out? This comes preinstalled with Windows 10 Home.

**Comment by brianteeman** [comment]
I cant tell you as I already upgraded to the chromium release https://www.microsoft.com/en-us/edge

**Comment by Quy** [comment]
Upgraded and now it is fine. Should non-chromium Edge be supported?

**Comment by brianteeman** [comment]
That I don't know. I would create a new issue regarding that and then @wilsonge can direct a decision

**Comment by wilsonge** [comment]
This is a decision for production to make as a whole - my personal opinion would be not to support it 

// cc @HLeithner

**Comment by HLeithner** [comment]
Our current support cycle is planned Major version - 2, MS forces all users to upgrade to blink rendering version but I didn't found the timeline for the eol of EdgeHTML. So I would suggest to fix this problem instead hoping that EdgeHTML is not longer supported by MS.

**Comment by Quy** [comment]
OK the issue is with `position: sticky` in RTL with EdgeHTML. 
@ciar4n Can you suggest a fix? Thanks.

```
.subhead {
  position: sticky;
  top: 0;
  right: 0;
  left: 0;
  z-index: $zindex-toolbar;
  width: auto;
  min-height: 43px;
  padding: 13px 0;
  color: var(--atum-text-dark); //#0c192e;
```

**Comment by ciar4n** [comment]
This appears to be the case... https://stackoverflow.com/questions/56835658/in-microsoft-edge-sticky-positioning-doesnt-work-when-combined-with-dir-rtl

Until RTL/sticky is fixed in Edge, maybe something like...

```
@supports (-ms-ime-align:auto) {
  [dir=rtl] .subhead {
    position: relative;
  } 
}
```

**Comment by Quy** [comment]
Please test PR #27897
