### ISSUE TITLE
[4.0] httpheaders Plugin issue Document inline styles and script now with md5 array key

### ISSUE THREAD

**Issue by nielsnuebel** [joomla/joomla-cms#27837]
### Steps to reproduce the issue
1. error_reporting = development
2. com_csp options:
- CSP enabled
- Mode = detect

3. refresh frontend
4. com_csp options:
- mode = automatic
- hash for styles and script enabled
5. com_csp activate some item for example 
![image](https://user-images.githubusercontent.com/3214077/74006065-e11f8b00-497a-11ea-9d68-0f9d42ca36e3.png)
6. reload backend
![image](https://user-images.githubusercontent.com/3214077/74006116-fd232c80-497a-11ea-87ee-9675fde62494.png)

In Joomla 3 there was no md5 key yet
![image](https://user-images.githubusercontent.com/3214077/74006171-204ddc00-497b-11ea-924d-d4fe6f8f0855.png)

https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Document/Document.php#L564
https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Document/Document.php#L676

https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/system/httpheaders/httpheaders.php#L163
https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/system/httpheaders/httpheaders.php#L174

**Comment by SharkyKZ** [comment]
Related closed PR https://github.com/joomla/joomla-cms/pull/26505.

**Comment by nielsnuebel** [comment]
@SharkyKZ exactly that was the error, @zero-24 already fixed it

**Comment by SharkyKZ** [comment]
I don't think this was fixed yet. Please keep this issue open.

**Comment by N6REJ** [comment]
what is com_csp?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27837">issues.joomla.org/tracker/joomla-cms/27837</a>.</sub>

**Comment by Quy** [comment]
System > Content Security Policy

**Comment by Quy** [comment]
Duplicate #26501
