### ISSUE TITLE
Error in installing Hindi language extension.

### ISSUE THREAD

**Issue by aditya20t** [joomla/joomla-cms#27834]
### Steps to reproduce the issue

Go to system settings and try to install hindi language extenstion.

### Actual result
![Screenshot (54)](https://user-images.githubusercontent.com/55142272/73995888-1a0e2e80-4980-11ea-9ea0-d9c0472f3226.png)

### System information (as much as possible)

version: 4.0.0-beta1-dev

**Comment by Quy** [comment]
Duplicate #26653
