### ISSUE TITLE
[4.0] File location for Text "Single Article"

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#27844]
### Steps to reproduce the issue

Looking for the file that contains the text string "Single Article" which appears in the Menu Item Type modal.

Please point us to the file or files.  Thank you.

**Comment by brianteeman** [comment]
The file is en-GB.com_content.sys.ini
You should not need to ever touch that file though - thats why we have language overrides

**Comment by brianteeman** [comment]
Closed as there is nothing further to add
