### ISSUE TITLE
[4.0] TypeError: tabLink is null

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#27845]
### Steps to reproduce the issue
Go to System
Click Text Filters
View browser's console.

Sadly my attempt at a fix failed.
https://github.com/joomla-projects/custom-elements/pull/134

### Actual result
> TypeError: tabLink is null joomla-tab.js:277:7

```
    showTab(tab) {
      const tabLink = document.querySelector(`#tab-${tab.id}`);
      tabLink.click();
    }
```

### Expected result
The selected tab is active.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla-projects/custom-elements/pull/135.
