### ISSUE TITLE
[4.0] webasset user.css

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27867]
### Steps to reproduce the issue
Create a user.css for the atum template

### Expected result
user.css overrides template.css

### Actual result
template.css is loaded after user.css making user.css useless
![image](https://user-images.githubusercontent.com/1296369/74102526-06a7c280-4b3c-11ea-94c2-dccf119ffeef.png)

**Comment by Fedik** [comment]
please test #27872
