### ISSUE TITLE
[4.0] unable to add sample data

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#27863]
### Steps to reproduce the issue
use the latest 4.0-dev
add sample data

### Expected result
able to add sample data

### Actual result
js error

![Screenshot from 2020-02-09 08-48-13](https://user-images.githubusercontent.com/181681/74098494-00ecb580-4b19-11ea-83d8-b53a6936976b.png)

### System information (as much as possible)

tested on FF 72.0.2

**Comment by od-martin** [comment]
I have no problems. Works fine.

**Comment by richard67** [comment]
@alikon Switch on debug in global config and try again, and if same error post again screenshot. We could then see where it is (line and row) in the **unminified** script file.

**Comment by alikon** [comment]
i can confirm my findingins on the 1st attempt , maybe some cache issue, but really weird
