### ISSUE TITLE
Wrong alias for İ (capital i with dot in Turkish alphabet)

### ISSUE THREAD

**Issue by hakanara** [joomla/joomla-cms#27875]
### Steps to reproduce the issue
Either in a fresh Joomla installation or an old Joomla with a latest version, the same thing happens. When you write İ in the title area (in articles or in a component), the alias is produced as "i-" not "i". So for example if you write "İş" it becomes "i-s" as alias, not "is". İ is a Turkish letter (capital for i, not like in English). By the way, all other Turkish strange letters work fine, capital and small: ÜĞŞÇÖüğışçö

I have added İ to tr-TR.localise.php file both in site and admin language folders but the result did not change. 

The latest Turkish language file is a bit old, 3.9.4.1, a more recent version was not published. But what does it have to do with it indeed?

### Expected result
When you write İ, the alias field is expected to produce only i, without dash.
"i"

### Actual result
"i-"

### System information (as much as possible)
Tested with 3.9.14 Joomla which is 12 years old
Tested with a fresh 3.9.15 Joomla.
(Turkish language file latest: 3.9.4.1) Not the same version with Joomla, because this is the latest file. 

### Additional comments
I love everybody who spend their time for Joomla :-)

**Comment by infograf768** [comment]
Can you post here a .zip of your localise.php containing the transliterate method?

**Comment by hakanara** [comment]
[tr-TR.localise.zip](https://github.com/joomla/joomla-cms/files/4177675/tr-TR.localise.zip)
Thank you very much @infograf768 
On Joomla forums posts, who are even 10 years old, you were still answering these Turkish character problems :-) Nice to see you here again.

**Comment by infograf768** [comment]
Just add the `İ` line 118 after the `ή`

so you get
`        'i'     =>    'ì,í,î,ï,ı,ĩ,ī,ĭ,į,и,й,ъ,ы,ь,η,ή,İ', `

[tr-TR.localise.php.zip](https://github.com/joomla/joomla-cms/files/4179183/tr-TR.localise.php.zip)

**Comment by Bakual** [comment]
Closing this issue as it's a language pack issue, not a core issue.

**Comment by hakanara** [comment]
As I have mentioned on the issue (The first post) I already tried to add "İ" into that line, but it didn't work. I tried it again since you said this is the solution, it didn't work again. Do you have any other ideas why it might occur? I will create another fresh Joomla site in Turkish and see how it behaves. It wasn't like this before.

**Comment by infograf768** [comment]
It will never work. `İ` is a specific utf8 character which is not considered as having a lowercase equivalent.

**Comment by infograf768** [comment]
@Bakual 
In fact it is a bit more complex and one could say it is not only a lang pack issue because of the utf8 nature of this specfic character.
I think that if we could first change that specific character to a latin upper I, we could solve the issue.
This may require a new method.

**Comment by hakanara** [comment]
@infograf768 Thank you very much for your time and efforts. Actually I have been using Joomla for 12 years and I never remember seeing something like this before, even though I have some articles which have a title starting with "İ". 

İ is an upper case letter of i in Turkish. It is not lowercase.

**Comment by hakanara** [comment]
And if it is not considered to have a lowercase, then how does it have the alias i with a dash? There should be some code where it recognizes how it turns to lowercase. I am not a PHP expert, just thinking and asking.

**Comment by infograf768** [comment]
I suggest you test something and you may see how weird is this utf8 character.
in global configuration, set unicode slugs to Yes.
Then create an article which title will contain your special character.
Save and look at the alias.
instead of keeping the same character, it is display as an i to which is added another dot on top.
(on ipad now. can’t show you a scren shot)

**Comment by hakanara** [comment]
The same lines exist in update.sql. Is it a bug or is it something that has to be?

**Comment by hakanara** [comment]
I saw what you mean. I did all the changes, It created an alias with a character that looks like a lowercase i but it is not the exact i. 

I would like to repeat here, I believe something had changed either with server, PHP or Joomla. Because I created many web sites with Joomla within the last 12 years. Contact means "İletişim" in Turkish. So at every web site, I created at least a contact menu item starting with capital İ. But I never saw the alias as "i-letisim", I remember them as "iletisim". Therefore I opened this issue.

**Comment by infograf768** [comment]
See https://en.wikipedia.org/wiki/Dotted_and_dotless_I
Also
https://stackoverflow.com/questions/48067545/why-does-unicode-implement-the-turkish-i-the-way-it-does

I am not aware of any change from former Joomla.

**Comment by richard67** [comment]
Can't we just force the whole world to use pure ASCII? ;-) (sorry, bad joke)

**Comment by infograf768** [comment]
@hakanara 
We have now implemented transliterator_transliterate in Joomla 4.0 and it solves your issue.
https://github.com/joomla/joomla-cms/pull/27974

<img width="1003" alt="Screen Shot 2020-02-19 at 08 41 17" src="https://user-images.githubusercontent.com/869724/74812360-a8c16a80-52f3-11ea-9aec-96362f719697.png">

I you like, you can modify your 3.9.15 joomla with the code proposed here for J3 and which was refused at the time, as it depends on the php version you use as well as the presence of Intl

https://github.com/joomla/joomla-cms/pull/16880

**Comment by hakanara** [comment]
@infograf768 you are amazing. Thank you very much for your efforts. I love you :-)

**Comment by alikon** [comment]
@hakanara please close the issue if problem solved
thanks

**Comment by infograf768** [comment]
@hakanara 
Don’t forget to redo the j3 patch after future updates of j3.
