### ISSUE TITLE
UI Asymmetry of heights of inputs and its buttons in edit menues

### ISSUE THREAD

**Issue by MostafaHamedAbdelmasoud** [joomla/joomla-cms#27887]
### What needs to be fixed
![](http://rtl-ltr.000webhostapp.com/assets/tempsnip.png)
![](http://rtl-ltr.000webhostapp.com/assets/options.PNG)

hello everyone,
in first screenshot:
here in edit menues from administrator panel, there are some differences between heights for inputs and buttons (select) as they should be on the same size

in second screenshot:
remove icon is also different in height from select button

### Why this should be fixed
i think it can has a good UI, if all inputs and buttons are the same height onthe same level

### How would you fix it
for inputs: 
in administrator\templates\isis\css\template.css line 7420
```bash 
.controls input[type="text"]{
       max-width: 100%;
	height: auto;
}
 ```

for buttons and remove icons:
in administrator\templates\isis\css\template.css

``` bash
/* line 1566 for parent div  add position relative */
.form-horizontal .input-append {
	position: relative;
}
 
/*  line 1493 add these lines */
.input-prepend.input-append .add-on:last-child,
.input-prepend.input-append .btn:last-child {
   position: absolute;
    height: 100%;
    top: 0px;
}

```
### this also appears in articles->edit article->publishing  for history icons beside inputs
we can do the same steps too.

**Comment by brianteeman** [comment]
I can not replicate this.

In addition in your first screen  top right there is some off text that should not be there

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/74196247-b8d2ad80-4c54-11ea-873a-13d16f93b5b4.png)

![image](https://user-images.githubusercontent.com/1296369/74196248-ba9c7100-4c54-11ea-89ad-2f0a3fb8d2c8.png)

**Comment by chmst** [comment]
I cannot confirm this issue. Everything looks okay in my installations. 
@MostafaHamedAbdelmasoud Have you changed something in your xml files?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27887">issues.joomla.org/tracker/joomla-cms/27887</a>.</sub>

**Comment by MostafaHamedAbdelmasoud** [comment]
> In addition in your first screen top right there is some off text that should not be there

 **yes i was just see something**

what's your version of joomla? i have version 3.9.15 -> downloaded from [joomla.org](https://downloads.joomla.org/)

**_OS: microsoft 10
php version: 7.4.2_**

**Comment by jwaisner** [comment]
I cannot recreate this using using 3.9.15 on Windows 10 and PHP 7.4.2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27887">issues.joomla.org/tracker/joomla-cms/27887</a>.</sub>

**Comment by MostafaHamedAbdelmasoud** [comment]
ok i installed a new one, and yes this issue doesn't exist in it.
i didn't know what happened exactly.
so it can be closed now. 👍
