### ISSUE TITLE
[Sub-form]  Validation message for repeatable-table layout of sub-form getting blank

### ISSUE THREAD

**Issue by pranotiTechjoomla** [joomla/joomla-cms#27888]
### Steps to reproduce the issue

Login to administrator
Goto Email Domain Options of user config and add domain.
Domain name is a required field.
Save domain name with a blank value.

### Expected result

The error message should show as **Invalid field:  Domain Name** 

### Actual result

The error message only shows **Error**

### System information (as much as possible)

Joomla Version 3.9.X (tested on 3.9.15)

**Comment by Polm90** [comment]
Same issue, even in custom components, even on frontend side

**Comment by manav014** [comment]
I am working on the issue and would be updating soon.

**Comment by manav014** [comment]
https://github.com/joomla/joomla-cms/pull/27904
is there any other improvement required?

**Comment by manav014** [comment]
https://github.com/joomla/joomla-cms/pull/27909
Improved Solution

**Comment by jwaisner** [comment]
Please reference PR  [# 27909](https://github.com/joomla/joomla-cms/pull/27909)
