### ISSUE TITLE
Joomla 4.0.0-beta1-dev-Development — Notice: Undefined index: keywords 

### ISSUE THREAD

**Issue by vintzl** [joomla/joomla-cms#27881]
### Steps to reproduce the issue

JFactory::getDocument()->_metaTags['name']['keywords'];

### Expected result

get the keywords list

### Actual result

> Notice: Undefined index: keywords 

### Additional comments

Since, 2020/02/10, Joomla_4.0.0-beta1-dev-Development, `JFactory::getDocument()->_metaTags['name']['keywords'];` yields nothing.

**Comment by brianteeman** [comment]
Please see #25258
