### ISSUE TITLE
Hard-coded HTML in templates/system/incompatible.html file. 

### ISSUE THREAD

**Issue by aditya20t** [joomla/joomla-cms#27905]
### Steps to reproduce the issue
Simply go to templates/system/incompatible.html

### Expected result
![Screenshot (61)](https://user-images.githubusercontent.com/55142272/74331333-7eceec00-4db9-11ea-9bd1-9b96b40ec0b5.png)

### Actual result

![Screenshot (59)](https://user-images.githubusercontent.com/55142272/74331340-82627300-4db9-11ea-9bfe-c7c2d8c255b4.png)

**Comment by SharkyKZ** [comment]
This is expected. The file is not meant to be accessed directly. When Joomla! renders the page placeholder tag is replaced by minimum PHP version.

https://github.com/joomla/joomla-cms/blob/07bc37bfba86f7845318b3f9db907a0acd69b3fb/index.php#L18-L27

**Comment by aditya20t** [comment]
Okay I am closing this issue then.
