### ISSUE TITLE
[4.0] choices.js input issue

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#27907]
in `/media/vendor/choicesjs/js/choices.js` we have this code
```
  _proto.setWidth = function setWidth() {
    // Resize input to contents or placeholder
    var _this$element = this.element,
        style = _this$element.style,
        value = _this$element.value,
        placeholder = _this$element.placeholder;
    style.minWidth = placeholder.length + 1 + "ch";
    style.width = value.length + 1 + "ch";
  }
```
For example it defines the min-width and width of the input in the `tag` field.

When the placeholder text is long, the min-width may be too important, forcing the field to go over the edge of the page.

### Steps to reproduce the issue
Install Persian language although the issue is NOT related to RTL.
Edit an article and look at the Tags field.
Switch between en-GB and fa-IR (Persian)

**en-GB**
The placeholder string is
`JGLOBAL_TYPE_OR_SELECT_SOME_TAGS="Type or select some tags"`

Which gives for the input field

<img width="390" alt="Screen Shot 2020-02-12 at 11 49 51" src="https://user-images.githubusercontent.com/869724/74329023-4d412b00-4d8f-11ea-9648-70b809c465e0.png">

The element values are:

<img width="197" alt="Screen Shot 2020-02-12 at 11 50 08" src="https://user-images.githubusercontent.com/869724/74329054-5c27dd80-4d8f-11ea-968e-543c1e502cff.png">

**fa-IR**
The placeholder string is
`JGLOBAL_TYPE_OR_SELECT_SOME_TAGS="برخی از برچسب ها را تایپ یا انتخاب کنید"`

Which gives for the input field

<img width="389" alt="Screen Shot 2020-02-12 at 11 48 45" src="https://user-images.githubusercontent.com/869724/74329218-a9a44a80-4d8f-11ea-93f8-b6189ccfcbaf.png">

The element values are:

<img width="219" alt="Screen Shot 2020-02-12 at 11 49 37" src="https://user-images.githubusercontent.com/869724/74329315-d8babc00-4d8f-11ea-819d-3203f0273b38.png">

The only way I found to partly correct this issue without touching at the js is to override the `min-width`.

For example in choices.scss: 
```
.choices[data-type*="select-multiple"] .choices__input, .choices[data-type*="text"] .choices__input {
    padding: 0.2rem 0 0.356rem;
    color: #495057;
    min-width: 35ch !important;  // added
}
```
It still limits the number of characters as placeholder

For Persian the alignment is not too bad

<img width="371" alt="Screen Shot 2020-02-12 at 12 51 13" src="https://user-images.githubusercontent.com/869724/74332707-a6608d00-4d96-11ea-9c2d-610627c8e44d.png">

the default for German is already 35ch (and still not perfect alignment for German)

<img width="402" alt="Screen Shot 2020-02-12 at 12 46 11" src="https://user-images.githubusercontent.com/869724/74332471-10c4fd80-4d96-11ea-9b4a-80273d14c3f1.png">

Anyway in all cases, when reducing the window width, it is always bad... (until we get to x mobile view where all fields are 100%.

<img width="646" alt="Screen Shot 2020-02-12 at 12 55 32" src="https://user-images.githubusercontent.com/869724/74332886-1111c880-4d97-11ea-91e5-d99c17a00ef8.png">

@ciar4n

**Comment by ciar4n** [comment]
I think any JS setting a `width` and a `min-width` can be removed.  It doesn't make any sense and I can only presume is there to support a legacy browser.

**Comment by Fedik** [comment]
hm, maybe better open issue at source https://github.com/jshjohnson/Choices

**Comment by ciar4n** [comment]
True. These inline widths are not set on the choices demo (https://joshuajohnson.co.uk/Choices/ ). I thought it was something we added.

**Comment by infograf768** [comment]
Posted in Choices github
https://github.com/jshjohnson/Choices/issues/823

**Comment by infograf768** [comment]
@Fedik 
If no reply, we could do
```
.choices[data-type*="select-multiple"] .choices__input,
 .choices[data-type*="text"] {
[...]
  .choices__input {
    padding: 0.2rem 0 0.356rem;
    color: $custom-select-color;
    min-width: 100% !important;
    width: 100% !important;
  }
etc

```
this would override choices.js and solve our problem
What do you think?

**Comment by Fedik** [comment]
yeap, but something like in your first comment:
```
min-width: 10ch !important;  
max-width: 100%;
```
so it always will be at least 10ch width, and limited by 100% by box size
in theory

**Comment by infograf768** [comment]
My tests show here that `min-width: 10ch !important;` or `min-width: 100% !important;` would not change the result. 
In both cases `width: 100% !important;` is what counts.
Looks like `max-width: 100%;` is also not really necessary.

**Comment by Fedik** [comment]
I meant without `width: 100% !important;` :wink:
the `width` can stay as calculated by JS, we only have an issue with min-width, by removing it (with `min-width: 10ch !important;`) we will not force it to be bigger than container

**Comment by ChristineWk** [comment]
Are there any new findings about? Tks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27907">issues.joomla.org/tracker/joomla-cms/27907</a>.</sub>

**Comment by wojsmol** [comment]
Please see [this](https://github.com/jshjohnson/Choices#im-looking-for-active-maintainers-for-this-project-as-i-no-longer-have-the-time-to-support-it-please-get-in-touch-if-youre-interested-) note in the `jshjohnson/Choices` `REAME.md`.
