### ISSUE TITLE
[4.0] Error when changing the category of an article with custom fields

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#27919]
### Steps to reproduce the issue
Have two categories A and B  and articles in category A.

Have a custom field for articles of these categories.

Open an article and change the category from A to B. 

Save the article.

### Expected result
The article is saved.

### Actual result
The $this->hits is empty when it comes to save in TableContent and store fails with message "Incorrect value "" for column 'hits'.

**Comment by shubhamshubh** [comment]
Confirmed.
I am working on the issue.

**Comment by alikon** [comment]
confirmed from me too
i'll let you work on this

**Comment by chmst** [comment]
The same in 3.9. When the article is reloaded after a category change, the readonly fields "version", "modified_by" and "hits" remain empty on the screen. 
In 3.9, the article then can be saved and the values of these fields are correct again.
in J4.0 saving the article throws the error.

**Comment by SharkyKZ** [comment]
The issue is coming from `Joomla\CMS\MVC\Controller\FormController::reload()` method which filters data before storing it to user state. I don't think this is done for security. We do store unfiltered data in other places, e.g. when saving fails.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/28103.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27919">issues.joomla.org/tracker/joomla-cms/27919</a>.</sub>
