### ISSUE TITLE
[4.0] module style page rendering error

### ISSUE THREAD

**Issue by Twincarb** [joomla/joomla-cms#27922]
### Steps to reproduce the issue
Clean install of J4
Change a module style to use sliders or tabs

### Expected result
Joomla front end page to be rendered

### Actual result
Error: JHtml sliders not found.: JHtml sliders not found.
Error: JHtml tabs not found.: JHtml tabs not found.

### System information (as much as possible)
J4 Nightly

**Comment by brianteeman** [comment]
Which modul

**Comment by Twincarb** [comment]
Menu, Breadcrumbs, Articles - Category, Login

All have the same response<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27922">issues.joomla.org/tracker/joomla-cms/27922</a>.</sub>

**Comment by brianteeman** [comment]
Is this the thing you are talking about
![image](https://user-images.githubusercontent.com/1296369/74483234-f716d980-4ead-11ea-8caf-b8ee55db2fd3.png)

**Comment by Twincarb** [comment]
@brianteeman yes that's correct<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27922">issues.joomla.org/tracker/joomla-cms/27922</a>.</sub>

**Comment by MostafaHamedAbdelmasoud** [comment]
i don't have this error

**Comment by richard67** [comment]
@Twincarb Have you made a new, clean installation using that nightly build? or have you updated from a previous 4.0 nightly build or 4.0 alpha version using the Joomla Update component or any other method (e.g. just replacing the files, which would be wrong)?

If updated: This is not really supported yet. Updates will be supported between released versions as soon as Beta 1 will be releases. So your installation might be broken. In this case try again with a new installation, i.e. the nightly full package unpacked into an empty folder and making a new installation using an empty database, then test again and report back the result.

If not updated, i.e. clean new install: Please report back the database type (MySQL or MariaDB or PostgreSQL or very unlikely MS SQL Server) and the version, and the PHP version you use.

Thanks in advance.

**Comment by richard67** [comment]
P.S.: Due to the description I assume it is a clean installation, the question in my previous comment is just to be really sure.

**Comment by SharkyKZ** [comment]
These are old MooTools based chromes. They can be removed unless someone wants to refactor them to use something else (Bootstrap?).

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/27923.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27922">issues.joomla.org/tracker/joomla-cms/27922</a>.</sub>
