### ISSUE TITLE
[Smart Search] + [Multilingual]: search for articles in a specific language (only for different language versions of the website)

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#27929]
### Is your feature request related to a problem? Please describe.

A `Smart Search` in Joomla indexes a field that points to the language for the article. We can even turn off any language of the `Smart Search`. But I did not see such an opportunity so that for the `English` version of the website I could display the search results only in `English`, and for the `Russian` version of the website I could display the search results only in `Russian`.

![изображение](https://user-images.githubusercontent.com/3662519/74547788-baa2b680-4f5d-11ea-9cc4-78798d019a35.png)

### Describe the solution you'd like
I suggest adding a parameter for `Multilingual` websites to the settings of `Smart Search`, with which we can share search results for different language versions of the website.

And also add to the page with search results a new parameter for search - **search for articles by language**.

![изображение](https://user-images.githubusercontent.com/3662519/74549630-099e1b00-4f61-11ea-87bd-26513f036f0e.png)

### Additional context
Currently, `Smart Search` cannot be used on `Multilingual` websites. Search shows all search results in all languages. You need a parameter to display search results only in a specific language (English, Russian, etc) for the website version in a specific language (by default).

![изображение](https://user-images.githubusercontent.com/3662519/74550072-cc865880-4f61-11ea-90de-ea93688bc50a.png)

**For example:**

- I clicked on the English version of the website and when I search for something, the search results in English are shown to me (by default)
- I clicked on the Russian version of the website and when I search for something, the search results in Russian are shown to me (by default)

**Comment by infograf768** [comment]
For the moment (and there was a good reason to do that when finder was merged into J), maps are not implemented when the the multilanguage filter is on.

<img width="796" alt="Screen Shot 2020-02-15 at 08 31 22" src="https://user-images.githubusercontent.com/869724/74584032-f4130a80-4fcd-11ea-8be5-1540347a4637.png">

**Comment by 4digitalworld** [comment]
> 
> 
> For the moment (and there was a good reason to do that when finder was merged into J), maps are not implemented when the the multilanguage filter is on.
> 
> <img alt="Screen Shot 2020-02-15 at 08 31 22" width="796" src="https://user-images.githubusercontent.com/869724/74584032-f4130a80-4fcd-11ea-8be5-1540347a4637.png">

I don’t understand what you mean. And I don’t understand what `maps` mean (are they `sitemaps`?).

So it is impossible to do a `smart search` for two language versions of a website?

**Comment by richard67** [comment]
@sanek4life You can have different smart search menu items or smart search modules in different languages assigned to the pages in that language. With `maps` @infograf768 means the Content Maps of the Smart Search component, see `administrator/index.php?option=com_finder&view=maps`.

**Comment by 4digitalworld** [comment]
> 
> 
> For the moment (and there was a good reason to do that when finder was merged into J), maps are not implemented when the the multilanguage filter is on.
> 
> <img alt="Screen Shot 2020-02-15 at 08 31 22" width="796" src="https://user-images.githubusercontent.com/869724/74584032-f4130a80-4fcd-11ea-8be5-1540347a4637.png">

@richard67 @infograf768  in `Russian`, no one wrote a `NOTE` to this parameter:

![изображение](https://user-images.githubusercontent.com/3662519/74592777-b77af980-5035-11ea-831a-c171344652c4.png)

I still don’t understand how to include search results for different languages. I'm create 2 menu items with search results (for `ru` and `en`), created 2 search modules (for `ru` and `en`), `Associations` them. and still did not understand how to make the setting to display the search results - in the `Russian` version in `Russian language` and in the `English` version in `English language`.

Do I understand correctly that it is not possible to do this on a `multilingual` website at present?

Is there any instruction on how to do this, step by step, if possible?

**Comment by infograf768** [comment]
In a multilingual site. A smartsearch module set to ALL. 

If you have the same word in an article tagged to en-GB and an article tagged to fr-FR and your page is en-GB, only the results for article tagged to en-GB will be found.

The opposite for fr-FR evidently.
Please look at the urls below

en-GB

<img width="668" alt="Screen Shot 2020-02-15 at 19 11 24" src="https://user-images.githubusercontent.com/869724/74592989-18e79c00-5027-11ea-90bb-17e109e9bcd9.png">



fr-FR (default site language, languagefilter set to use `Remove URL Language Code`

<img width="668" alt="Screen Shot 2020-02-15 at 19 11 24" src="https://user-images.githubusercontent.com/869724/74592987-12f1bb00-5027-11ea-8e96-6390b9ab2c1f.png">

**Comment by infograf768** [comment]
The smart search results in a multilingual site depend on the language in use.

Here we have an example searching for the word `ligue` depending on the language in use, knowing that this word is used both in articles tagged to French and articles tagged to English

English

<img width="668" alt="Screen Shot 2020-02-15 at 19 11 24" src="https://user-images.githubusercontent.com/869724/74593055-e4281480-5027-11ea-9cfd-74ff3a77be72.png">

French

<img width="726" alt="Screen Shot 2020-02-15 at 19 11 03" src="https://user-images.githubusercontent.com/869724/74593069-ee4a1300-5027-11ea-9eff-f98766703d66.png">

**Comment by 4digitalworld** [comment]
> 
> 
> The smart search results in a multilingual site depend on the language in use.
> 
> Here we have an example searching for the word `ligue` depending on the language in use, knowing that this word is used both in articles tagged to French and articles tagged to English
> 
> English
> 
> <img alt="Screen Shot 2020-02-15 at 19 11 24" width="668" src="https://user-images.githubusercontent.com/869724/74593055-e4281480-5027-11ea-9cfd-74ff3a77be72.png">
> 
> French
> 
> <img alt="Screen Shot 2020-02-15 at 19 11 03" width="726" src="https://user-images.githubusercontent.com/869724/74593069-ee4a1300-5027-11ea-9eff-f98766703d66.png">

It turns out that it is impossible to exclude `articles` in **English** (articles for which the language is selected - `fr-FR`) from a site search in `French`. Search searches for any article in any language. This is not exactly what i'm need.

It is necessary to completely remove articles with language `en-GB` from the search in `Russian`. And completely remove articles with language `ru-RU` in `English` version, then it will be working `multilingualism`. Because `articles`, `categories`, `tags` and `menu` items have `Associations`, thus in the search those materials that have a link in another language and show the article only in the language selected on the site could be excluded (for example: `ru-RU` articles in the `Russian` version of the website, without `en-GB` articles).

**Comment by infograf768** [comment]
Joomla in general does not care about the language of the content of an article or the language used in its title. The only aspect considered is the language the item is tagged to.
 (article or anything else...)

Edit: also an association is not necessarily a translation!

**Comment by MaghSamana** [comment]
Smart search with multilingual is still problematic. I also got the problem described above after I enabled smart search and in addition the indexing is problematic for the other languages. 

Although articles etc. get normally indexed, if I look for a word that exists in english articles and also in other language(s) articles [from the other language(s) section] their resulting articles may or may not come up at all. 

Smart search really needs a lot of work, in multilingual Joomla.

**Comment by infograf768** [comment]
There were many changes in 4.0. You may want to test a 4.0 nightly build.

https://developer.joomla.org/nightly-builds.html

**Comment by 4digitalworld** [comment]
> 
> 
> Joomla in general does not care about the language of the content of an article or the language used in its title. The only aspect considered is the language the item is tagged to.
> (article or anything else...)
> 
> Edit: also an association is not necessarily a translation!

I know that the `article` may have different words (these words can be written in different languages in the article). For example, I have an `article` about **Android** in **Russian language**, but the word Android, which is written in **English language**, also appears in this `article`. This **article** is attached to the `ru-RU` language.

So, whe i use the Russian version of the website, no matter what word I wrote in the search on the site (in Russian language or English language), so that I want to see only articles that indicate the language of `ru-RU` articles.

**For example:** in the Russian version of the website, I search for the English word Android in the search, and the search shows me only those articles that indicate the language `ru-RU`, and the English word Android is written, but in the search I do not want see articles that indicate the language `en-GB` and in which there is the word Android (which is also written in English language).

As I do not see `menu items`, `categories`, `tags` and `articles` in English (`en-GB`), when I use the Russian version of the site (`ru-RU`), so the search should work - show only those articles in which the language is `ru-RU`, regardless of what language the words are in this article.

If the site user wants to see articles in English, then he will switch to the English (`en-GB`) version of the site. (I mean, these articles are written entirely in English, and not only contain English words).

Because `articles` in Russian also contain English words, but these articles should be shown only in the Russian version of the site and in search on the Russian version of the site.

I hope you understand what I mean. I am trying to explain this. Perhaps we do not understand each other (English is not my native language).

@MaghSamana I think you have the same problem as me.

**Comment by infograf768** [comment]
It looks like you do not understand my reply.
Please look again at the screenshots I posted above and the results obtained (look at the urls).

article containing searchword Android and tagged to en-GB will only appear in the search results if the frontend page is en-GB.

article containing searchword Android and tagged to ru-RU will only appear in the search results if the frontend page is ru-RU.

**Comment by Hackwar** [comment]
As @infograf768 wrote, this is definitely the case for at least Joomla 4.0 and I think also for 3.x. Thus this issue can be closed.
