### ISSUE TITLE
[4.0] Confusing label for TOS field

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#27928]
### Steps to reproduce the issue
Register yourself in frontend. 
The TOS is mandatory but followed by "(optionaol)" which is confusing

### Expected result
Either it is mandatory or optional, not both.

### Actual result
![tos-optional](https://user-images.githubusercontent.com/1035262/74549194-81fbe080-4f4f-11ea-9198-5bca650f42da.JPG)

**Comment by brianteeman** [comment]
I can not replicate that

![image](https://user-images.githubusercontent.com/1296369/74549455-92a85880-4f47-11ea-850f-bfef56087ebb.png)

There isnt even an option for that field to be optional - it is either required or disabled
![image](https://user-images.githubusercontent.com/1296369/74549586-ce432280-4f47-11ea-9f4f-a52a5143876a.png)

**Comment by chmst** [comment]
Your screen is as it should be. Thank you, so it is something in my installation.
