### ISSUE TITLE
bad Joomla template bug

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#27934]
#27838

j 3,9,15, php 7.4.2

copy protostar name it mytemplatecopy and instead of this

... /templates/mytemplatecopy/css/template.css" rel="stylesheet" type="text/css" />
.../templates/mytemplatecopy/css/user.css" rel="stylesheet" type="text/css" />

you get this ugly code

.../templates/mytemplatecopy/css/template.css?8e17160b713641b3cc489b29e3405a51" rel="stylesheet" />
.../templates/mytemplatecopy/css/user.css?8e17160b713641b3cc489b29e3405a51" rel="stylesheet" />

Is there an option to get rid ?8e17160b713641b3cc489b29e3405a51 of this ugly joomla template code addition  ?

That code protostar template makes joomla site slow as hell. Do google PageSpeed Insights. It slows site by about 3 seconds.

Due to the complex number of closed but unsolved issues of joomla it would be better to https://developers.google.com/speed/pagespeed/insights/

Whese tests show how bad horrible joomla template performs with thisfeature not disabled on .../templates/mytemplatecopy/css/template.css?8e17160b713641b3cc489b29e3405a51" rel="stylesheet" />
.../templates/mytemplatecopy/css/user.css?8e17160b713641b3cc489b29e3405a51" rel="stylesheet" /> to claim this?

**Comment by brianteeman** [comment]
I am closing this again. I am not commenting other than to say you are completely wrong.
