### ISSUE TITLE
Plugin contactcreator gets wrong category_id 34

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#27946]
### Steps to reproduce the issue
Enable the user plugin contactcreator
Enable registering of users in users options
Register as new user.

### Expected result
The newly generated contact has categoy "uncategorised" of com_contact.

### Actual result
The generated contact has catid = 34. 

### Additional comments
Tested on a existing installation (3.9.15), on staging (3.9.16 dev) with a clean installation, in 4.0 dev.

**Comment by Bakual** [comment]
After saving the plugins parameters, it will take the correct category. But the value initially set during installation is indeed wrong.

Fix the value set in the install.sql https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/joomla.sql#L607

**Comment by Bakual** [comment]
Closing as we have a PR
