### ISSUE TITLE
Email validation not consistent in the system

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#27948]
### Steps to reproduce the issue
1. Go to the global configuration
2. Set an email like: "foobar@localhost"
3. save
4. press "send test email" button

### Expected result
Either I get an error on saving, that the email is wrong or sending an email works.

### Actual result
Sending an email fails, because Joomla! validation uses the Email ruleset (https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Form/Rule/EmailRule.php) while the PHPMailer class ( ```addRecipient```) uses the PHP validation (https://github.com/joomla/joomla-cms/blob/staging/libraries/vendor/phpmailer/phpmailer/class.phpmailer.php#L1157)

### Additional comments
[Here was a short discussion already](https://github.com/joomla/joomla-cms/issues/21680)

**Comment by SharkyKZ** [comment]
We could make TLD required in our forms. The validation rule already supports it.

**Comment by brianteeman** [comment]
That would be wrong

**Comment by dgrammatiko** [comment]
Just add `type="email"` instead `type="text"`in the input. Browsers know better how a valid email looks like 😉

**Comment by alikon** [comment]
please test #28574<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27948">issues.joomla.org/tracker/joomla-cms/27948</a>.</sub>

**Comment by brianteeman** [comment]
For reference the problem was with phpmailer configuration
