### ISSUE TITLE
[4.0] Joomla Update - No option to supply the FTP details

### ISSUE THREAD

**Issue by twister65** [joomla/joomla-cms#27945]
### Steps to reproduce the issue

- System -> Global Configuration -> Server -> Enable FTP -> Yes

- Save & Close

- System -> Update - Joomla -> Upload & Update

- Installation method -> Write files directly
It hides all FTP fields.

- Installation method -> Write files using FTP
or  -> Hybrid (use FTP only if needed)

### Expected result
Fields :

- FTP Host

- FTP Port

- FTP Username

- FTP Password

- FTP Root

### Actual result
No FTP fields.

### System information (as much as possible)
The last nightly build.

**Comment by brianteeman** [comment]
ftp is not "done" yet. There is an open release blocker for this. Mainly because there was an unresolved debate if ftp was even needed any more

**Comment by richard67** [comment]
@brianteeman You mean #20774 ?

**Comment by twister65** [comment]
Please, test PR #28029
