### ISSUE TITLE
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/user/domains/example.com/components/com_weblinks/models/categories.php on line 95

### ISSUE THREAD

**Issue by klausmayer** [joomla/joomla-cms#27944]
### Steps to reproduce the issue
Loading web links

### Expected result
no warnings in error.log

### Actual result
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/user/domains/example.com/components/com_weblinks/models/categories.php on line 95

### System information (as much as possible)
Joomla 3.9.15, PHP 7.3, Component Web Links 3.7.0

**Comment by Quy** [comment]
Please report to the weblinks repo.
https://github.com/joomla-extensions/weblinks
