### ISSUE TITLE
Error in Search Component: Call to undefined method Joomla\CMS\Application\AdministratorApplication::getLanguageFilter()

### ISSUE THREAD

**Issue by MaghSamana** [joomla/joomla-cms#27959]
Hello,
not sure what's wrong here. The site runs multilingual Joomla 3.9.15 with Falang 3.0.2 installed, made a year ago. PHP version is 7.3.13.

At some point I noticed that the search component became inaccessible, and cannot be opened from Components > Search, but unfortunately I do not know when it happened. The site was already a 3.9.x version when I saw it. 

I checked search component & plugins, language plugins, falang plugin & module - everything looks ok and works fine. It is only when I try to access the Search component that I see this:

Call to undefined method Joomla\CMS\Application\AdministratorApplication::getLanguageFilter() 

Any ideas what might be causing it?

**Comment by gerryfrancis** [comment]
A user in the German Joomla! forum reported that Falang had to be updated to resolve the issue. @MaghSamana Please update Falang and report back, thanks.

**Comment by MaghSamana** [comment]
I just updated to the most recent Falang version, but I still get the same error.

**Comment by MaghSamana** [comment]
Indeed. I updated Falang, then cleared the cache, and tried to access search component. At first I got the same error, and rechecked the plugins, etc. Then I tried again accessing the search component and all of a sudden, it was working.

**Comment by infograf768** [comment]
Closing as not joomla bug.
