### ISSUE TITLE
[4.0]Toolbar disappearing on reducing and increasing size of screen

### ISSUE THREAD

**Issue by Subhang23** [joomla/joomla-cms#27957]
### Steps to reproduce the issue
Go to any page with components like articles, modules, etc.
Reduce the width until the toolbar is being rendered with the help pf a button
Collapse the dropdown
Enlarge the window screen size

### Expected result
The toolbar is present

### Actual result
It disappears

### System information (as much as possible)
Chrome
Ubuntu-18.04(Virtual Machine)

### Additional comments
![toolbar](https://user-images.githubusercontent.com/43785080/74616593-c30e1380-514e-11ea-943d-142270fa76f1.gif)

**Comment by Subhang23** [comment]
Please refer PR #27958 for the solution of this issue.

**Comment by infograf768** [comment]
closing as we have pr https://github.com/joomla/joomla-cms/pull/27958
