### ISSUE TITLE
Text Filter not entered into database when group is created

### ISSUE THREAD

**Issue by adjei7** [joomla/joomla-cms#27960]
### Steps to reproduce the issue
1. Create a group in the Joomla backend
2. Note down group ID and Check Text Filter Settings for the new group in Global Configuration->Text Filters. Should be the Default Blacklist set by default.
3. Go to database #__extension table and look at params for com_config record and look for the group ID for the new group.

### Expected result
Will see details of the new group with BL for default blacklist within the filter data.

### Actual result
New group is not present within params filter data at all.

### System information (as much as possible)
Joomla! 3.9.15 Stable 
mysql database
PHP version 7.2.24 
Web Server Apache
Template - Favthemes Favourite
Extensions - JCE Editor; favGDPR plugin
Viewing on Firefox on windows 10

### Additional comments
The filter data for the new group only seems to be entered into the database once global configuration is saved.
Is this expected behaviour?
I would have expected that the new group filter settings would be entered into the database at the same time the group was created.

**Comment by chmst** [comment]
Permissions in com_config are always stored when the save button is clicked. So there should be no exception with the global permissions. The new group inherits filters from the parent group. 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27960">issues.joomla.org/tracker/joomla-cms/27960</a>.</sub>
