### ISSUE TITLE
Either﹤or &lt； is not acceptable in custom field text type.

### ISSUE THREAD

**Issue by shawnhy** [joomla/joomla-cms#27976]
Title filters html marks, too. I replace filtered to show them properly.

### Steps to reproduce the issue
1. Create a custom filed group.
2. Create a text type custom field and assign to all categories. Not using any filter.
3. Create an article and input something like **< &lt； > &gt；**
4. save the article.

### Expected result
Since html symbol is not filtered, they should be savable.

### Actual result
html symbol < and &lt； are remove

### System information (as much as possible)

Joomla! 3.9.15
php 7.3

**Comment by brianteeman** [comment]
Set the filter to raw or perhaps safehtml

**Comment by MostafaHamedAbdelmasoud** [comment]
@shawnhy  i don't get it? so i created an article then i typed **< &lt； > &gt；** ,in it contect and it shows without deleting anything

**Comment by shawnhy** [comment]
@MostafaHamedAbdelmasoud You should replace my；with normal semicolon on your keyboard. In the same way use the left tag on your keyboard (at the right side of M key)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27976">issues.joomla.org/tracker/joomla-cms/27976</a>.</sub>

**Comment by shawnhy** [comment]
@brianteeman In setting custom field, setting the filter to row works. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27976">issues.joomla.org/tracker/joomla-cms/27976</a>.</sub>

**Comment by Quy** [comment]
Closing as not a bug.
