### ISSUE TITLE
Add option to disable Meta Keywords

### ISSUE THREAD

**Issue by sshcli** [joomla/joomla-cms#27973]
### Is your feature request related to a problem? Please describe.
Yes.
There are some SEO concern about this.
In my case, I use the Kunena forum component for Joomla and the keywords are generated automatically based on Joomla settings.
The current keywords are not relevant or useful, that's why I would like to disable the meta keywords tag.
 
The recommendation of many SEO experts is to remove the Meta Keyword Tag.

For example:
• Google https://youtu.be/jK7IPbnmvVU
• Yoast https://yoast.com/meta-keywords/
• Wordpress developers already removed the tag from the source code.
  

### Describe the solution you'd like
Add an option in the backend to Enable / Disable Meta Keywords
Backend->Menus: Edit Item->Metadata->Meta Keywords->Enable or Disable

**Comment by SharkyKZ** [comment]
Keywords were mostly removed in 4.0. See PR https://github.com/joomla/joomla-cms/pull/25258.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27973">issues.joomla.org/tracker/joomla-cms/27973</a>.</sub>

**Comment by sshcli** [comment]
Thanks @SharkyKZ 
I have installed the latest J4 Nightly Build and can confirm it.
