### ISSUE TITLE
[4.0] workflow button

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#27982]
I was looking to see if there was a way to hide the display of the stage name in com_content. There is only value in displaying the name when the default workflow is not being used. 

https://github.com/joomla/joomla-cms/blob/6f7416b1741c2281bec7bf727eb57bb52f5e37af/layouts/joomla/button/transition-button.php#L30

I came across this code but I can not see how it is ever triggered

**Comment by bembelimen** [comment]
The idea behind this "if" is: if there are now transitions for you available, the "click event" with displaying the dropdown makes no sense, so it's not implemented.

**Comment by brianteeman** [comment]
aha - no wonder I couldnt get it to work.

So instead of removing it (we shouldnt have unusable code) I will repurpose it so that if the default workflow is being used we do not display the stage.

OK?

**Comment by bembelimen** [comment]
I have no opinion here, tbh. But I trust your UX knowledge, if you say it makes sense, let's try it.

**Comment by brianteeman** [comment]
well on the basis that with the default workflow the stages are no different to the J3 behaviour it worked well without them then. Of course with a custom workflow they do make sense so I wouldnt remove the display of them in that case

**Comment by brianteeman** [comment]
Closed
