### ISSUE TITLE
[3.9] Background-Image Link is broken in -Tag when SEF is on

### ISSUE THREAD

**Issue by LittleToni** [joomla/joomla-cms#27988]
### Steps to reproduce the issue
Insert the following HTML code to your template:

```html
<style>
  .example {
    background-image: url("images/example.png");
  }
</style>
```
Show the page with SEF feature on and check the source code.

### Expected result

```html
<style>
  .example {
    background-image: url("/images/example.png");
  }
</style>
```

### Actual result

```html
<style>
  .example {
    background-image: url("images/example.png");
  }
</style>
```

### System information (as much as possible)
Joomla 3.9

### Additional comments
SEF Plugin doesn't check the described case using "background-image" in <style>-Tag. The Plugin checks only usage of "background-image" as inline css.

**Comment by brianteeman** [comment]
Sorry you are mistaken in your expectation. The expected behaviour is that the code you entered is the code that is used. That's exactly what is happening.

**Comment by LittleToni** [comment]
An example for comparison. If you insert the following HTML code to your template:

```html
<div style="background-image: url("images/example.png");">
  Example
</div>
```
**Result**

```html
<div style="background-image: url("/images/example.png");">
  Example
</div>
```
The expected behaviour is that the code you entered is the code that is used. That's not the case.

**Comment by infograf768** [comment]
If the image is in the main images folder, the code should be
` background-image: url("../images/example.png"); `

If it is in the template image folder, try

```
$this->addStyleDeclaration("
  	.example {
    	  	background-image: url('" . JURI::root(true) . "/templates/nameofmytemplate/images/example.png');
  	}
");
```

**Comment by LittleToni** [comment]
I insert Image URL with PHP from Custom Joomla Module (field type Media). This field type automatic makes the URL looks like "images/example.png".

Your Suggestion is ok but tell me a reason why the sef plugin checks case like:

```html
<div style="background-image: url("images/example.png");">
  Example
</div>
```

but not case like:

```html
<style>
  .example {
    background-image: url("images/example.png");
  }
</style>
```

**Comment by SharkyKZ** [comment]
If you use PHP to add images, you can add the base path yourself. However, I think this is a valid issue. It probably dates back to when `<style>` tags were only valid when used in `<head>` (before HTML5).

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed.

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc [@zero-24](https://github.com/zero-24)

**Comment by bembelimen** [comment]
My code in template:
![grafik](https://user-images.githubusercontent.com/1229869/187197601-9078eec3-7257-4584-bb0c-eb5360d388aa.png)

Calling home:
![grafik](https://user-images.githubusercontent.com/1229869/187197665-7019438b-4c2c-41ea-a37f-f1adb06efa40.png)

Calling a sub menu:
![grafik](https://user-images.githubusercontent.com/1229869/187197725-849a04be-4974-4ec9-be60-43b7a945246e.png)

**Comment by alikon** [comment]
you should do something like this instaed
```css
<style>
    body {
      background-image :url(<?php JURI::root(true); ?>/images/headers/blue-flower.jpg);
    }
  </style>
```
