### ISSUE TITLE
Add 'noopener' to list in Foreign URL menu item rel attribuut.

### ISSUE THREAD

**Issue by TVBZ** [joomla/joomla-cms#27990]
The menu item to add foreign URL has a Link `rel` attribute field in the **Link Type tab**.
The value `noopener` is missing from this list. If this could be added, that would be great.

Thanks!

**Comment by brianteeman** [comment]
rel="noopener" prevents the new page from being able to access the window.opener property and ensures it runs in a separate process.
rel="noreferrer" attribute has the same effect, but also prevents the Referer header from being sent to the new page. See Link type "noreferrer".

**Comment by TVBZ** [comment]
Huh. Okay, so it should also work. Thanks for clearing that out.

The question originated from trying to get my site to perform better in google LightHouse test.
It gives the warning to add `rel="noopener"` or `rel="noreferer"` to the link. After adding `rel="noreferer"`, the warning remains. While in other links (from custom html) the warning disappeared after adding `rel="noopener"`. 

But I guess this is an issue for LightHouse than, and not Joomla :)

![image](https://user-images.githubusercontent.com/43469713/74877603-01c9e680-5366-11ea-94f7-d40e514b474c.png)

**Comment by brianteeman** [comment]
I actually copy pasted that information from lighthouse :)

**Comment by jwaisner** [comment]
Closing at this has been identified as not being related to Joomla!.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27990">issues.joomla.org/tracker/joomla-cms/27990</a>.</sub>

**Comment by TVBZ** [comment]
I'dd like to reopen this. After thinking some more on it ...
There are some cases where `rel="noopener"` is the only good option.
Because we don't want to lose the Referer header, `rel="noreferer" `just wont do.

**Comment by jwaisner** [comment]
Reopened as per Author's request and new information provided.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27990">issues.joomla.org/tracker/joomla-cms/27990</a>.</sub>

**Comment by Quy** [comment]
See #24337 for J4 and per the discussion it will not be fixed for J3. This should be closed and continue the discussion in the other issue.

**Comment by TVBZ** [comment]
I don't think it's the same issue. I don't mean to enforce this on all external url's.
It's just an option that's missing in the dropdown list for foreign URL menu type, in _/administrator/components/com_menus/models/forms/item_url.xml_.

For the field _"menu-anchor_rel"_ (list type) this option should be added:
`<option value="noopener"/>`

That's all

**Comment by Quy** [comment]
@TVBZ Got it. Please test PR #28005. Thanks.
