### ISSUE TITLE
Fivem ER_BAD_FIELD_ERROR: Unknown column "inventory" in "field list"

### ISSUE THREAD

**Issue by DjukaMarko** [joomla/joomla-cms#27995]
I'm making a fivem server but when i add essentialmode to my database and when i run the server.bat it shows me ER_BAD_FIELD_ERROR: Unknown column "inventory" in "field list".
Please help i would really appreciate it. 
CODE:

CREATE TABLE `users` (
	`identifier` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_bin',
	`license` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`money` INT(11) NULL DEFAULT NULL,
	`name` VARCHAR(50) NULL DEFAULT '' COLLATE 'utf8mb4_bin',
	`skin` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`job` VARCHAR(50) NULL DEFAULT 'unemployed' COLLATE 'utf8mb4_bin',
	`job_grade` INT(11) NULL DEFAULT 0,
	`loadout` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`position` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`bank` INT(11) NULL DEFAULT NULL,
	`permission_level` INT(11) NULL DEFAULT NULL,
	`group` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`firstname` VARCHAR(50) NULL DEFAULT '' COLLATE 'utf8mb4_bin',
	`lastname` VARCHAR(50) NULL DEFAULT '' COLLATE 'utf8mb4_bin',
	`dateofbirth` VARCHAR(25) NULL DEFAULT '' COLLATE 'utf8mb4_bin',
	`sex` VARCHAR(10) NULL DEFAULT '' COLLATE 'utf8mb4_bin',
	`height` VARCHAR(5) NULL DEFAULT '' COLLATE 'utf8mb4_bin',
	`status` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`last_property` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`is_dead` TINYINT(1) NULL DEFAULT 0,
	`phone_number` VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	PRIMARY KEY (`identifier`)
)
COLLATE='utf8mb4_bin'
ENGINE=InnoDB

**Comment by alikon** [comment]
>  fivem server

??
this the the repo for Joomla CMS
