### ISSUE TITLE
JSON Parse error: Unrecognized token '

### ISSUE THREAD

**Issue by no-matter-0** [joomla/joomla-cms#28004]
when trying to install a very simple plugin I get the error JSON Parse error: Unrecognized token '<'

I can install this plugin on Joomla 3.x but not 4.0

**Comment by alikon** [comment]
can you share with us the plugin that you are trying to install ?
in this way we can better try to answer you
thanks

**Comment by no-matter-0** [comment]
2 files
ymages.xml

```
<?xml version="1.0" encoding="utf-8"?>
<extension version="3.0" type="plugin" group="system" method="upgrade">
    <name>System - Ymages</name>
    <author>Joomla! Project</author>
    <creationDate>February 2020</creationDate>
    <copyright>Copyright (C) 2005 - 2020 Open Source Matters. All rights reserved.</copyright>
    <license>GNU General Public License version 2 or later.</license>
    <authorEmail>web@ymages.com</authorEmail>
    <authorUrl>ymages.com</authorUrl>
    <version>1.0.0</version>
    <description>custom library.</description>

    <files>
        <filename plugin="ymages">ymages.php</filename>
        <filename>index.html</filename>
    </files>
</extension>
```

ymages.php

```
<?php
/**
 * @copyright   Copyright (C) 2005 - 2020 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later.
 */

defined('_JEXEC') or die;

/**
 * Ymages plugin class.
 *
 * @package     Joomla.plugin
 * @subpackage  System.ymages
 */
class plgSystemYmages extends JPlugin
{
    /**
     * Method to register custom library.
     *
     * return  void
     */
    public function onAfterInitialise()
    {
        JLoader::registerPrefix('Ymages', JPATH_LIBRARIES . '/ymages');
    }
}
```

**Comment by no-matter-0** [comment]
the plugin is installed and works but I get this error

**Comment by chmst** [comment]
I could install on both, J3.9.15 and J4 without error

Use `<name>plg_system_ymages</name>`
and remove line ` <filename>index.html</filename>.`
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28004">issues.joomla.org/tracker/joomla-cms/28004</a>.</sub>

**Comment by no-matter-0** [comment]
Then I have to try a clean install 

thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28004">issues.joomla.org/tracker/joomla-cms/28004</a>.</sub>

**Comment by brianteeman** [comment]
Closed as not a core joomla issue
