### ISSUE TITLE
[4.0] Featured Articles

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#28003]
Do we really need to have a separate view for featured articles and all the associated code. This really is just legacy code that we haven't needed for a very very long time since we introduced filters.

Featured Articles is just the display of articles pre-filtered does it really need its own view

Contacts component also has a featured flag. That doesnt have its own codebase or admin menu so why would we need to keep it for com_content.

NOTE: I am talking about the admin only

**Comment by chmst** [comment]
This was part of the GSoC project III Enhancement of this year.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28003">issues.joomla.org/tracker/joomla-cms/28003</a>.</sub>

**Comment by bembelimen** [comment]
I guess the only "challenge" is to implement the featured ordering if I remember correctly, because it's independent from the category the article is in.

**Comment by brianteeman** [comment]
Ah - that's the difference. Guess its not as easy as I was thinking.

**Comment by chmst** [comment]
You must not guess - itis described in the gsoc document :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28003">issues.joomla.org/tracker/joomla-cms/28003</a>.</sub>

**Comment by brianteeman** [comment]
;) You have to know it exists and where to find it

**Comment by chmst** [comment]
When I added the filter for featured to articles, I already wanted to remove the whole model/view/controller for featured. But could not do it at this time. Now we have at least improved the model.
And I like theis feature request, it is exactly what I want too. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28003">issues.joomla.org/tracker/joomla-cms/28003</a>.</sub>

**Comment by brianteeman** [comment]
OK - I will re-open this so it doesnt get forgotten.

**Comment by bembelimen** [comment]
Additional random thoughts: perhaps we should go the other way around and remove the limited ordering on category level at all (not sure if there is a reason why it is there).

Because this limitation brings a bunch of problems in the news modules when one select "order by ordering". It's not always the expected behaviour.

Removing this limitation makes it easier to fulfill this issue...

**Comment by Formatio-hippocampi** [comment]
In "Featured Articles"-View the Action "Batch" isn't shown: 

![Screenshot_2020-09-11 Articles Featured - fw4 - Administration](https://user-images.githubusercontent.com/70466955/92928512-7ae27580-f43f-11ea-8a38-126fb236beeb.png)

"Batch"-Button wasn't shown in J3 too.

**Comment by HLeithner** [comment]
@Formatio-hippocampi can you please create a new issue/feature request and delete your comment here because has not much todo with this issue

**Comment by ghost** [comment]
Comment was to support "Featured Articles is just the display of articles pre-filtered does it really need its own view".

**Comment by HLeithner** [comment]
> Comment was to support "Featured Articles is just the display of articles pre-filtered does it really need its own view".

Oh, now that makes sense, I don't think we remove that view in a reasonable time frame (maybe j5?) except someone finds a good way to to sort featured articles in the main articles view.

**Comment by brianteeman** [comment]
Closing
