### ISSUE TITLE
[4.0] Notice: Array to string conversion

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#28008]
### Steps to reproduce the issue
Create tag `Red`
Go to Content > Categories
Click Filter Options
Enter/select `Red` in `- Select Tag -`

### Actual result
> Notice: Array to string conversion in \administrator\components\com_categories\src\Model\CategoriesModel.php on line 142

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/28009.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28008">issues.joomla.org/tracker/joomla-cms/28008</a>.</sub>
