### ISSUE TITLE
Adding custom field imagelist in backend

### ISSUE THREAD

**Issue by no-matter-0** [joomla/joomla-cms#28015]
When adding  a custom field imagelist to an article I get {field 1} into the article 
I cannot select images or directory like with Joomla 3

it does not work anymore

**Comment by no-matter-0** [comment]
I notice that it is exactly the same for any custom field<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28015">issues.joomla.org/tracker/joomla-cms/28015</a>.</sub>

**Comment by brianteeman** [comment]
When you use the editor button "field" it will generate the code you report and this is the placeholder for the value of the field that would be rendered in the article.

The imagelist itself can be found in the "field" tab of the article.

This is exactly the same in joomla 3
