### ISSUE TITLE
[4.0] Multilingual Associations Side by Side view is not working properly in a custom component

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#28016]
### Steps to reproduce the issue

1. Activate `Language Filter plugin`.

2. Install a `second language`.
![Languages  Installed  Site    test   Administration(1)](https://user-images.githubusercontent.com/9974686/75094442-63b76580-558b-11ea-8427-7cdd3e2d698e.png)

3. Create a` Content Language `for the in 2 installed language
![Languages  Content   test   Administration](https://user-images.githubusercontent.com/9974686/75094446-703bbe00-558b-11ea-94c9-672683b4defa.png)

4. Comment out the line for testing
https://github.com/joomla/joomla-cms/blob/b22b02d72ef5bb8edbb66be1b9d5f69c6d754e21/administrator/components/com_content/tmpl/article/edit.php#L123

5. See, that you can create `associations` in the component `com_contact.`
![Articles  Edit   test   Administration(2)](https://user-images.githubusercontent.com/9974686/75094450-7d58ad00-558b-11ea-8a76-14e0239f5657.png)

6. Try to create an association via `Multilingual Associations Component`. 

### Expected result

`Side by Side` in `Multilingual Associations Component` view is not working properly

![Multilingual Associations  Edit Associations  Articles   Articles    test   Administration](https://user-images.githubusercontent.com/9974686/75094614-3370c680-558d-11ea-8d86-e580ef3c3a84.png)

### Actual result
`Side by Side` ended up in a endless loop.

### Additional comments

I am not sure if it is a Bug. But I think, that other third party extensions will run into this issue, too.

I was able to isolate the problem.

`$(this).contents().find('#jform_id').val()` is undefined in this line:

https://github.com/joomla/joomla-cms/blob/ff165bbc70738e4749294efa355ce27df027942a/build/media_source/com_associations/js/sidebyside.es5.js#L150

If you do not use the layout `joomla.edit.publishingdata`. Because in this layout a hidden field is set, that is used in the JavaScript File for the Side by Side view. So all extensions at one point must also set this field. 

`<input type="hidden" readonly id="jform_id" name="jform_id" value="<?php echo (int) $this->item->id ?>">
`

If my idea is correct, we should add this to this documentation: https://docs.joomla.org/J3.x:Multilingual_Associations/SidebySide

**Comment by infograf768** [comment]
We have a specific code in core components for articles:
```
<?php // Creating 'id' hiddenField to cope with com_associations sidebyside loop ?>
		<?php if ($params->get('show_publishing_options', 1) == 0) : ?>
			<?php $hidden_fields = $this->form->getInput('id'); ?>
			<div class="hidden"><?php echo $hidden_fields; ?></div>
		<?php endif; ?>
```
This is only due to the specific articles parameter `show_publishing_options`.
I do not think we use that for other core components.

**Comment by astridx** [comment]
> @infograf768 I do not think we use that for other core components.

Thank you very much for looking. 

It is the same with com_contact: https://github.com/joomla/joomla-cms/blob/671a4face7ed9e9487bba9a4523988b25a0eadab/administrator/components/com_contact/tmpl/contact/edit.php#L107 and com_newsfeeds: https://github.com/joomla/joomla-cms/blob/671a4face7ed9e9487bba9a4523988b25a0eadab/administrator/components/com_newsfeeds/tmpl/newsfeed/edit.php#L93

I want to put it differently
If you install the my com_foo component https://github.com/astridx/boilerplate/releases/tag/v1.0.0 and you do not use the layout, I mean, you delete this line:
https://github.com/astridx/boilerplate/blob/8068f3e4349207f759a567d1e2331c592142fb6c/src/administrator/components/com_foos/tmpl/foo/edit.php#L77

Then you run int this issue.

I encountered this problem when I prepared this component for use in Joomla version 4 (from Joomla version 3).

**Am I missing something or is it likely that others will encounter this problem and we could avoid it?**

**Comment by SharkyKZ** [comment]
You just need to render the ID field, not necessarily using `joomla.edit.publishingdata` layout. If your fields are using different names, that's another issue. The selectors in the script would have to be configurable.

**Comment by astridx** [comment]
> @SharkyKZ  The selectors in the script would have to be configurable.

What do you mean exactly?
Can I configure the selectors (I don't see that) or should the script be changed so that the selectors could be configured?
Do you think this is an issue and I should leave this open here.

**Comment by SharkyKZ** [comment]
The script could be changed to support this, if needed.

**Comment by infograf768** [comment]
@astridx 
What I meant is that com_content needs to define this `id` hidden field, but not com_contact for example.
To test, I commented `<?php //echo LayoutHelper::render('joomla.edit.publishingdata', $this); ?>` in contact edit and I had no loop issue in multilingual component.

**Comment by astridx** [comment]
@infograf768 I have this issue in all components. 
But as I am not sure if this is a bug I close this issue. I put a link to this issue on the end of the doc page https://docs.joomla.org/J3.x:Multilingual_Associations/Developers
