### ISSUE TITLE
[Web Links]: bug with [Associations] button for category

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#28020]
### Steps to reproduce the issue

1. Create a `category` and save in any language [example: `en-GB`].
2. Click on the `Associations` button.
3. You will see that the `category` has been **saved**, instead of seeing a window with creating a `category` in another language.

### Expected result
On the right you will see a window for creating a `category` in another language

### Actual result
![изображение](https://user-images.githubusercontent.com/3662519/75096176-11d40700-55ae-11ea-8764-968307dcfcfc.png)

### System information (as much as possible)
Joomla 3.9.15, Web Links 3.7.0, PHP 7.3.9, MySQL 5.5.5-10.3.13-MariaDB-log

### Additional comments
![изображение](https://user-images.githubusercontent.com/3662519/75096234-afc7d180-55ae-11ea-9791-3dcf55fde759.png)

**Comment by ReLater** [comment]
The weblinks component has been decoupled from Joomla CMS.
Please post your issues here: https://github.com/joomla-extensions/weblinks
