### ISSUE TITLE
[Web Links]: missing button [Associations] for created links

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#28022]
### Steps to reproduce the issue

1. Create and **save** the link in any language (for example: `en-GB`).
2. After that, you will not see button `Associations`, but it should be.

### Expected result
![изображение](https://user-images.githubusercontent.com/3662519/75096401-5bbdec80-55b0-11ea-838a-d00dae01390f.png)

### Actual result
![изображение](https://user-images.githubusercontent.com/3662519/75096438-a5a6d280-55b0-11ea-9dd0-2e7bbb02b385.png)

### System information (as much as possible)
Joomla 3.9.15, Web Links 3.7.0, PHP 7.3.9, MySQL 5.5.5-10.3.13-MariaDB-log

### Additional comments
See also: [https://github.com/joomla/joomla-cms/issues/28020](https://github.com/joomla/joomla-cms/issues/28020)

**Comment by ReLater** [comment]
The weblinks component has been decoupled from Joomla CMS.
Please post your issues here: https://github.com/joomla-extensions/weblinks
