### ISSUE TITLE
[4.0] Atum filter broken in mobile view

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#28036]
In the rush to merge #28032 no one actually tested it fully.

It now breaks the mobile view
![image](https://user-images.githubusercontent.com/1296369/75116478-bf9fee00-5660-11ea-90bf-f50447f5b042.png)

**Comment by HLeithner** [comment]
@astridx can you address this issue please

**Comment by astridx** [comment]
Sorry, I will have a look later.

**Comment by richard67** [comment]
Closing as having PR. Please test #28046 .
