### ISSUE TITLE
[4.0] Border radius

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#28042]
### Steps to reproduce the issue
Looks like there is something wrong about which side gets the radius (curved corner) and which doesnt

![image](https://user-images.githubusercontent.com/1296369/75117580-8a989900-566a-11ea-8606-a2d51c42360c.png)

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/28048.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28042">issues.joomla.org/tracker/joomla-cms/28042</a>.</sub>
