### ISSUE TITLE
[4.0] page navigation

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#28041]
### Steps to reproduce the issue
![navigation](https://user-images.githubusercontent.com/1296369/75117541-2675d500-566a-11ea-9035-7e03b1107750.gif)

**Comment by jwaisner** [comment]
@brianteeman Can you please provide what is happening in this video? I can tell how to test to confirm this exists.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28041">issues.joomla.org/tracker/joomla-cms/28041</a>.</sub>

**Comment by brianteeman** [comment]
Closed see #28057
