### ISSUE TITLE
[4.0] Search toolbar clear button

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#28045]
I am not sure what the logic was for moving the filter before the search in the toolbar - I can't see any benefit. But it has an unfortunate side effect on pages that do not have a filter as it leaves the clear button just "floating around"

Also as I have said elsewhere that to me it is crazy having a layout override in one of the core templates.

### Before
![image](https://user-images.githubusercontent.com/1296369/75118184-d39f1c00-566f-11ea-91df-84738b43cfce.png)

### After
![image](https://user-images.githubusercontent.com/1296369/75118165-b36f5d00-566f-11ea-96ff-3c97d102fb37.png)

**Comment by chmst** [comment]
The logic was: If I were blind, then I would like to know which input is in the search field before I klick the button clear. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28045">issues.joomla.org/tracker/joomla-cms/28045</a>.</sub>

**Comment by richard67** [comment]
@brianteeman Does #28046 fix this issue?

**Comment by brianteeman** [comment]
@chmst which is why I was querying the change

**Comment by astridx** [comment]
> @chmst The logic was: If I were blind, then I would like to know which input is in the search field before I klick the button clear.

I did not know this. But in this case we should not create an overwrite for Autum Template. In this case we should correct the layout https://github.com/joomla/joomla-cms/blob/4.0-dev/layouts/joomla/searchtools/default/bar.php, right?
