### ISSUE TITLE
[4.0] White arrow not visible in dropdown on install

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#28050]
### Steps to reproduce the issue
Do a new install
White arrow not visible in dropdown

### Actual result

![dropdown](https://user-images.githubusercontent.com/368084/75130578-fd623e00-5683-11ea-8c5c-78ce18e3f42f.jpg)

**Comment by jwaisner** [comment]
Confirmed. Looks like it is there (if you decrease the contrast) but still not visible at a glance.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28050">issues.joomla.org/tracker/joomla-cms/28050</a>.</sub>

**Comment by Quy** [comment]
See PR #28059
