### ISSUE TITLE
[3.9.16-dev] com_users. Save options => Error "Field required: Domain Name"

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#28060]
### Steps to reproduce the issue
- New installation of nightly build 3.9.16-dev
- Opened `Users: Options`
- Activated: `Allow User Registration` 
- Clicked `Save`

### Expected result
- Options saved

### Actual result
![24-02-_2020_18-34-36](https://user-images.githubusercontent.com/20780646/75176506-918bde00-5734-11ea-9531-08c4cf8c4260.jpg)

### System information (as much as possible)

Setting | Value
-- | --
 
PHP Built On | Linux dd46134 4.15.0-76-generic #86~16.04.1-Ubuntu SMP Mon Jan 20 11:02:50 UTC 2020 x86_64
Database Type | mysql
Database Version | 5.7.28-nmm1-log
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.4.2
Web Server | Apache
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 3.9.16-dev Development [ Amani ] 27-January-2020 17:50 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0

### Additional comments
- When I go in tabulator `Email Domain Options` and create a dummy row like
![24-02-_2020_18-38-30](https://user-images.githubusercontent.com/20780646/75176717-f6dfcf00-5734-11ea-9c68-2c7febf3c624.jpg)

I can save the options

**Comment by Quy** [comment]
See PR #27999 awaiting to be merged.
