### ISSUE TITLE
[4.0] admin list views - blurred

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#28069]
When you hover on a row in a list such as the article manager the background changes to a grey colour. Unfortunately the light blue border merges into the grey and produces a "blurred" image

![image](https://user-images.githubusercontent.com/1296369/75199747-cf502d00-575b-11ea-9b3c-a181e2aa0d71.png)

There are a few options to "fix" this

Change the colour to something darker
![image](https://user-images.githubusercontent.com/1296369/75199872-2a821f80-575c-11ea-9fd3-c29ea525f067.png)

Increase the border width
![image](https://user-images.githubusercontent.com/1296369/75199929-4f769280-575c-11ea-9a59-b4dcfd855742.png)

**Comment by chmst** [comment]
Or remove border on hover. Gray background should be enough.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28069">issues.joomla.org/tracker/joomla-cms/28069</a>.</sub>

**Comment by brianteeman** [comment]
yes thats another option if possible - depends on the markup and havent checked

**Comment by brianteeman** [comment]
@chmst just checked and that doesn't really work as its only a border-top so the blur only gets partially removed

**Comment by chmst** [comment]
Seems you are right. So my favourite is a thinner and darker border,

**Comment by brianteeman** [comment]
Closed see #28235
