### ISSUE TITLE
Call to undefined method JApplicationSite::isClient() after activate a plugin

### ISSUE THREAD

**Issue by KViktor1985** [joomla/joomla-cms#28071]
Greetings whos clever than me :)

I download and install a plugin (https://extensions.joomla.org/extensions/extension/site-management/cookie-control/cookiehint/) to my joomla (3.6.5)

And when i activated i got an error message in all pages, include the admin:
Call to undefined method JApplicationSite::isClient()

In next morning i will get FTP and phpmyadmin access, any idea how can i fix it? 

Thx guys! (and girls)

**Comment by Quy** [comment]
Please post support questions at Joomla Forum. https://forum.joomla.org/

**Comment by joomdonation** [comment]
@KViktor1985 The method isClient() is only available on Joomla 3.7.0+. So just update your site to latest version of Joomla and the error will be gone.

**Comment by hrvoojex** [comment]
@joomdonation How to update Joomla if backend is not working?

**Comment by joomdonation** [comment]
@hrvoojex The answer was from long time ago and for Joomla 3 only. I meant he should update to latest version of Joomla (at that time Joomla 3.x) to be able to use the plugin

In your case, I guess you are updating from Joomla 3 to Joomla 4 and get that same error. In this case, to get your backend back, I guess the easiest way would be copy the block of code from here https://github.com/joomla/joomla-cms/blob/3.10-dev/libraries/src/Application/CMSApplication.php#L679-L721 and paste it to the file **libraries/src/Application/CMSApplication.php**  on your Joomla 4 installation

The other option is find the plugin which causes this error, usually a system plugin which is stored in plugins/system folder. Rename the folder to prevent that plugin from being loaded and it would get your site back.

**Comment by hrvoojex** [comment]
@joomdonation I am on Joomla 3. Don't know for sure which version, I read in version.php 3.6.5, but I remember it was 3.10.x .. I was trying to install image slideshow plugin creativeimageslider_free_pack_3.2.0 after everything stoped working and this message showed: Call to undefined method JApplicationSite::isClient() . 

After I renamed that plugin folder in plugins/system/creativeimageslider site is working.
Thank you very much!

**Comment by joomdonation** [comment]
OK. But you should check your site and update to latest 3.10.x if possible. As mentioned, that method was added in Joomla 3.7.0, so if you got that error, your site certainly not in 3.10.x as you said.
