### ISSUE TITLE
[4.0] Display version number

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#28085]
![image](https://user-images.githubusercontent.com/1296369/75333236-ae7ff880-587d-11ea-8829-d6f7b899eff6.png)

As seen in the image we display another joomla logo and the version number in the toolbar. To avoid confusion with the other items there which are buttons it was styled differently. 

With the new revision of the template it fails accessibility tests for color contrast. Even without the tests it is clear that it needs to be changed.

But do we really need to display the version number on every single page of the site?
Would it perhaps be better as a footer to the sidebar?

**Comment by Quy** [comment]
Previous discussion https://github.com/joomla/joomla-cms/pull/26447.

**Comment by jwaisner** [comment]
Closing as duplicate. Please see #26734 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28085">issues.joomla.org/tracker/joomla-cms/28085</a>.</sub>

**Comment by brianteeman** [comment]
re-opening. This issue is not a duplicate of #26734. This issue is caused by the changes in that PR. Please read more carefully. It is better to leave something open if you don't know than to blindly close.

**Comment by brianteeman** [comment]
Closed as this has now been fixed
