### ISSUE TITLE
[4.0] Cassiopea duplicate site-grid

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#28084]
.site-grid has two competing values for grid-template-areas

Obviously this is wrong but which is the one that should be removed?

@ciar4n @C-Lodder 

https://github.com/joomla/joomla-cms/blob/cf8a75ee6a46684643394733a21f55ca0bbf3ec3/templates/cassiopeia/scss/blocks/_css-grid.scss#L6-L17

https://github.com/joomla/joomla-cms/blob/cf8a75ee6a46684643394733a21f55ca0bbf3ec3/templates/cassiopeia/scss/blocks/_css-grid.scss#L51-L61

**Comment by C-Lodder** [comment]
The 2nd one is wrapped in a media query:

```
@include media-breakpoint-up(md) { ... }
```
The difference is in the sidebars

**Comment by brianteeman** [comment]
@C-Lodder no that's the third one

**Comment by ciar4n** [comment]
My bad. The second is what is currently applied so I guess you could go with that. I would move it to the top in place of the first. 

The difference in the 2 is that the first places the bulk of the modules after the component on small screen devices. The second one has them in the same order as desktop.

**Comment by brianteeman** [comment]
ok @ciar4n thanks for confirming

**Comment by C-Lodder** [comment]
Oh sorry, I didn't notice a third one
