### ISSUE TITLE
[4.0] No gradients for some quick icons on hover

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#28101]
### Steps to reproduce the issue
Quick icons under Site and System don't have gradients on hover as quick icons under Update Checks.

### Expected result
![icon-gradient](https://user-images.githubusercontent.com/368084/75386208-1c381e80-5896-11ea-8809-3eb6a0e138e5.jpg)

### Actual result
![icon-no-gradient](https://user-images.githubusercontent.com/368084/75386219-20fcd280-5896-11ea-9218-78e57470177d.jpg)

**Comment by jwaisner** [comment]
Confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28101">issues.joomla.org/tracker/joomla-cms/28101</a>.</sub>

**Comment by brianteeman** [comment]
Based on the code that is the intended behaviour
