### ISSUE TITLE
Author Edit Front End cannot edit their 'OWN' article if it's not published

### ISSUE THREAD

**Issue by rytechsites** [joomla/joomla-cms#28113]
This is with Joomla 3.9.15 (typo)
### Steps to reproduce the issue
Have a user with group = AUTHOR

Set Author User group the following article permissions
CREATE - ALLOWED
EDIT - DENIED
EDIT OWN - ALLOWED
EDIT STATE - DENIED
EDIT CUSTOM FIELD VALUE - ALLOWED

Have author login to FRONT END
1. Create a NEW Article
2. On front end find this 'new article'
(Note, I'm using Latest News Enhanced to display all articles from a specific author, the developer adjusted so I CAN see unpublished articles)
3. Attempt to EDIT this unpublished Article

I'm not able to EDIT IT.

* IF I change the 'Edit Status' = ALLOWED
Then I CAN edit the article

Problem:
If an AUTHOR creates an article, it should NOT be published, and should NOT be displayed in the system, but they SHOULD have the ability to EDIT that article from the front end if they needed to.

I don't want them to have to change the publishing status, that defeats the purpose of only being an author.

I think this is the way things were 'setup', but perhaps it can be addressed.

**Comment by Quy** [comment]
Duplicate #22232

**Comment by rytechsites** [comment]
Yes, this is a dup... thanks!  although it seems there is a debate if it is a 'bug' or a 'feature request'... I see it will hopefully be addressed in j4.  no need to address it in j3.

**Comment by Quy** [comment]
See #24132 for discussion on preview for the backend that could apply to the frontend. Let's close this one.

**Comment by rytechsites** [comment]
YEs, this can be closed.  thanks.

**Comment by rytechsites** [comment]
@Quy, question I don't think it is 'preview' that I'm concerned about.  

I think my issue is more related to #22232, because if a user adds an article as an AUTHOR on the FRONT END, they should be able to edit that article, prior to it being published.  This would be on the FRONT END.

Should I add notes to that issue?

**Comment by Quy** [comment]
Yes, please add your comments to #22232 to keep it under one issue. Thanks.
