### ISSUE TITLE
[4.0] Backend view styling in frontend

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#28119]
### Steps to reproduce the issue

Edit an article in frontend.
Click `CMS Content` button and make a selection.
Inspect styling in the opened modal.

### Expected result

OK styling.

### Actual result

![Screenshot_2020-02-28 Testing Home](https://user-images.githubusercontent.com/7325021/75517665-e87d0600-5a07-11ea-812d-e011b099ed21.png)

**Comment by infograf768** [comment]
Confirmed

**Comment by infograf768** [comment]
searchtools.css not loaded

**Comment by infograf768** [comment]
WIP after some modifications I can get for now

<img width="1305" alt="Screen Shot 2020-02-28 at 11 19 55" src="https://user-images.githubusercontent.com/869724/75540481-66e3a300-5a1c-11ea-87e1-652f4f0c1031.png">

Needs much more love and care :)

**Comment by infograf768** [comment]
see partial fix here : https://github.com/joomla/joomla-cms/pull/28248

**Comment by infograf768** [comment]
This may now be closed. Please test https://github.com/joomla/joomla-cms/pull/28283
