### ISSUE TITLE
[4.0] joomla update error messages

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#28111]
I suspect these are php 7.4 specific issues but don't currently have anything lower to test on

url administrator/index.php?option=com_joomlaupdate

### 1 - all pages
Notice: Trying to access array offset on value of type bool in `administrator\components\com_joomlaupdate\src\View\Joomlaupdate\HtmlView.php on line 143
`
### 2 - Upload and Update tab
Notice: Undefined variable: message in `administrator\components\com_joomlaupdate\tmpl\joomlaupdate\default_upload.php on line 36`

Notice: Trying to access array offset on value of type null in `administrator\components\com_joomlaupdate\tmpl\joomlaupdate\default_upload.php on line 36
`

**Comment by SharkyKZ** [comment]
First one already fixed in staging https://github.com/joomla/joomla-cms/pull/27219. See PR https://github.com/joomla/joomla-cms/pull/28112 for the other one.

**Comment by alikon** [comment]
lookin only at code for  1)
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php#L143

should be

`$this->ftpFieldsDisplay = $ftp['enabled'] ? '' : 'style = "display: none"';`


but unable to test now

**Comment by wilsonge** [comment]
Closing this. I know the second one isn't fixed in 4.0-dev but I'm going to sit down a do a set of merging up which will de facto shut this other part. @alikon is right in terms of the fix thats going to come

**Comment by alikon** [comment]
@wilsonge   #28117
