### ISSUE TITLE
mysql: Warning: #1280 Name 'md5sum' ignored for PRIMARY key.

### ISSUE THREAD

**Issue by KarstenFrostholm** [joomla/joomla-cms#28125]
### Steps to reproduce the issue
from 
  Downloads\Joomla_4.0.0-beta1-dev-Development-Full_Package.zip\installation\sql\mysqljoomla.sql and
  Downloads\Joomla_4.0.0-beta1-dev-Development-Full_Package.zip\administrator\components\com_admin\sql\updates\mysql\4.0.0-2018-07-29.sql
execute this sql

DROP TABLE IF EXISTS `xxx__finder_logging`;

CREATE TABLE IF NOT EXISTS `xxx__finder_logging` (
  `searchterm` VARCHAR(255) NOT NULL DEFAULT '',
  `md5sum` VARCHAR(32) NOT NULL DEFAULT '',
  `query` BLOB NOT NULL,
  `hits` INT(11) NOT NULL DEFAULT 1,
  `results` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY `md5sum` (`md5sum`),
  INDEX `searchterm` (`searchterm`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

### Expected result
No warning

### Actual result

Warning: #1280 Name 'md5sum' ignored for PRIMARY key.

### System information (as much as possible)

Database Type | mysql
-- | --
10.4.11-MariaDB
utf8mb4_general_ci
utf8mb4_general_ci
None
No
7.4.2
Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.4.2
apache2handler
Joomla! 4.0.0-beta1-dev Development [ Mañana ] 17-October-2019 20:21 GMT
2020-02-25 download

### Additional comments

change to 
CREATE TABLE IF NOT EXISTS `#__finder_logging` (
  `searchterm` VARCHAR(255) NOT NULL DEFAULT '',
  `md5sum` VARCHAR(32) NOT NULL DEFAULT '',
  `query` BLOB NOT NULL,
  `hits` INT(11) NOT NULL DEFAULT 1,
  `results` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`md5sum`),
  INDEX `searchterm` (`searchterm`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci;

**Comment by ReLater** [comment]
Could you please testcheck again with the nightly build installation of today. To be sure that the issue is not fixed already. Thank you.
https://developer.joomla.org/nightly-builds.html

**Comment by alikon** [comment]
just tested via https://dbfiddle.uk and works 

![image](https://user-images.githubusercontent.com/181681/75566824-afb54f00-5a50-11ea-88c5-4d09fc71c529.png)

**Comment by KarstenFrostholm** [comment]
**Thanks for the earlier reply.**

Tested again with two days newer version (from today)
Same syntax in jommla.sql
I'm not saying it doesn't come into the system.

**According to https://dev.mysql.com/doc/refman/8.0/en/create-table.html
there is no [symbol] after PRIMARY KEY.**

This should be corrected as many view JOOMLA's many files as good examples.

I use latest XAMPP with their phpmyadmin which gives this warning.
Sincerely
Karsten

**Comment by alikon** [comment]
you are right 
![Screenshot from 2020-02-28 18-48-37](https://user-images.githubusercontent.com/181681/75572354-0758b800-5a5b-11ea-9008-bc8700791432.png)

**Comment by alikon** [comment]
@KarstenFrostholm thanks for pointing this out

i'll try do a pr in the weekend

![Screenshot from 2020-02-28 18-57-36](https://user-images.githubusercontent.com/181681/75572997-39b6e500-5a5c-11ea-8c34-61d814e1d413.png)

**Comment by alikon** [comment]
please test #28128
