### ISSUE TITLE
[4.0] Remove referece to `css-vars-ponyfill`

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28149]
Remove referece to `css-vars-ponyfill` in `package.json` as it's not longed used.

**Comment by brianteeman** [comment]
Do we even need this any more? It was for IE wasnt it?
https://caniuse.com/#feat=css-variables

**Comment by C-Lodder** [comment]
Doesn't appear to be used anywhere in the `build` directory. Maybe it was removed when the announcement for dropping IE11 went out.
Changing title

**Comment by brianteeman** [comment]
I can see it being used in atum

**Comment by wilsonge** [comment]
This was the polyfill for css vars in atum. It can definitely be removed. Although you did also update it to latest in https://github.com/joomla/joomla-cms/pull/28553

**Comment by brianteeman** [comment]
see #28637
