### ISSUE TITLE
[4.0] Outdated dependency - diff

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28148]
Expected version: 4.0.2
Actual version: 3.4.0

**Comment by brianteeman** [comment]
Looking at the changelog the reason for the bump in major version doesnt have an impact on us so should be safe to update

> Bower and Component packages no longer supported

**Comment by wilsonge** [comment]
Fixed with https://github.com/joomla/joomla-cms/commit/862f96e89fbb4b2a6d71986a32ec78fcae35651b
