### ISSUE TITLE
[4.0] Outdated dependency - babel-preset-minify

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28155]
Expected version: 0.5.1
Actual version: 0.4.3

**Comment by brianteeman** [comment]
the package says ^0.4.3
I understood that to mean "include everything greater than a particular version in the same major range" so it would include 0.5.x etc

But it doesnt update to that version and the calculator at https://semver.npmjs.com/ confirms that.

/me confused

**Comment by brianteeman** [comment]
This was fixed with #29253 and can be closed
