### ISSUE TITLE
[4.0][Control Panel][Install from Web] - Install Templates from [JED]

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#28167]
### Is your feature request related to a problem? Please describe.

**Extensions: Install**

Now in tab `Install from Web` you can install `components`, `modules`, `plugins` from **JED**, but you cannot find and install `Templates`.

In three other tabs - `Upload Package File`, `Install from Folder`, `Install from URL`, you can install `components`, `modules`, `plugins` and `templates`.

![изображение](https://user-images.githubusercontent.com/3662519/75623687-a4336680-5bbd-11ea-8727-35879dcee42e.png)

### Describe the solution you'd like
I suggest adding a new category - `Templates` to **[JED](https://extensions.joomla.org/)** directory.

In the `Templates` category add subcategories, such as - `Frontend Templates` and `Control Panel Templates`. In these subcategories add a section with `Official Templates` as it was done with **[Official Extensions](https://extensions.joomla.org/category/official-extensions/)**.

If the `Template` for Joomla is `Free`, then the user can install it immediately from this tab (as it is done for extensions), if the `Template` is `Paid`, then he can follow the link to the template developer’s website.

### Additional context
Developers such as @RocketTheme, @JoomlArt, @YOOTheme and many others will be able to place a catalog of their compatible with `Joomla 3` and `Joomla 4` templates in this directory. I think it will be very convenient for new users who have just started working with Joomla CMS and do not know where to find good `Templates` for their websites. Now they can find all the `Extensions` without leaving the `Control Panel`. The same can be done for `Templates`.

I think this section with `Templates` is sorely lacking. That would be very convenient.

What categories look like:

- Templates
- - Website (Frontend) Templates
- - - Official Templates
- - Control Panel Templates
- - - Official Templates

A similar catalog of templates is on the official WordPress [website](https://wordpress.org/themes/)

![изображение](https://user-images.githubusercontent.com/3662519/75623928-7dc2fa80-5bc0-11ea-95b9-cde440b7770b.png)

**Comment by brianteeman** [comment]
This is not an issue for this repo. Please ask on the forum
