### ISSUE TITLE
[4.0] Bug in Subfom

### ISSUE THREAD

**Issue by blueforce** [joomla/joomla-cms#28171]
### Steps to reproduce the issue

1. Go to System > Manage > Content Security Policy > Options
2. set the CSP Mode to custom
3. add directive below
4. add 2nd directive
5. try delete all directives...

### Expected result
all directives are deleted

### Actual result
Actual result: I can delete all, until one directive (first) still remain. I can't delete it.
![Bildschirmfoto 2020-02-29 um 16 52 49](https://user-images.githubusercontent.com/1141234/75610805-e5bc0700-5b14-11ea-805a-829ad6758aa2.png)

**Comment by SharkyKZ** [comment]
Not a bug. The subform here has `min="1"` attribute which means it requires at least 1 row.

https://github.com/joomla/joomla-cms/blob/6bffa56d6eab72555d941ff59a908ce9e377b7e2/administrator/components/com_csp/config.xml#L79

**Comment by zero-24** [comment]
Yes but should't the content of the last row not be deleted when they hit remove?

**Comment by zero-24** [comment]
I can take a look into dropping min too but i'm under the same impression as @blueforce that when we hit remove the value would be removed but the last entry would still be there.

**Comment by zero-24** [comment]
See here for the removal of min: https://github.com/joomla/joomla-cms/pull/28173

**Comment by astridx** [comment]
As we have PR. See https://github.com/joomla/joomla-cms/pull/28173<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28171">issues.joomla.org/tracker/joomla-cms/28171</a>.</sub>

**Comment by zero-24** [comment]
As said above I personally would expect that the last delete would reset the values to empty, the mention PR just masks the issue.

**Comment by astridx** [comment]
@blueforce I understood that correctly. Your issue would be solved with the PR  #28173, right?

**Comment by blueforce** [comment]
@astridx yes... works
