### ISSUE TITLE
[4] Atum transparent message container is blocking clicks

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#28177]
Sorry, if it's already reported somewhere. I can't find it anymore but wonder that it's not fixed already.

### Steps to reproduce the issue
- Nightly build of today
- Desktop screen
- Go to Global configuration, e.g. Mail
- Fill the fields with data
- Send a test email

![001](https://user-images.githubusercontent.com/20780646/75628614-09498500-5bdb-11ea-96be-c0aca2a4d243.jpg)

- You'll see a message/alert
- Close it
![002](https://user-images.githubusercontent.com/20780646/75628641-53326b00-5bdb-11ea-9b76-621973037f01.jpg)

- Select the `notify-alert` container in browser inspector of Firefox. See blue area on screen:

![003](https://user-images.githubusercontent.com/20780646/75628716-fb483400-5bdb-11ea-83fe-a205ffbf16d1.jpg)

![004](https://user-images.githubusercontent.com/20780646/75628726-20d53d80-5bdc-11ea-878b-7c0e00fdca47.jpg)

- Afterwards try to change a field, e.g. in my example above `Send Email` switcher, that was behind the blue area while inspection. Not possible without reloading the page.

# System

Setting 	Value
PHP Built On 	Linux dd46134 4.15.0-76-generic #86~16.04.1-Ubuntu SMP Mon Jan 20 11:02:50 UTC 2020 x86_64
Database Type 	mysql
Database Version 	5.7.28-nmm1-log
Database Collation 	latin1_swedish_ci
Database Connection Collation 	utf8mb4_general_ci
Database Connection Encryption 	None
Database Server Supports Connection Encryption 	Yes
PHP Version 	7.4.2
Web Server 	Apache
WebServer to PHP Interface 	fpm-fcgi
Joomla! Version 	Joomla! 4.0.0-beta1-dev Development [ Mañana ] 17-October-2019 20:21 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0

**Comment by Quy** [comment]
See #25850

**Comment by ReLater** [comment]
> See #25850

Similiar but not the same. In my issue there is no background anymore. The container must get a d-none or z-index smaller after closing all messages or someting like that. You see the background above only in HTML inspector. Without there's nothing.

**Comment by Quy** [comment]
Actually it is the same issue. The background was fixed to be transparent, but the issue persists. See https://github.com/joomla/joomla-cms/issues/25850#issuecomment-525044000 where the culprit is an OS setting.

**Comment by ReLater** [comment]
Yes, you're right. Thanks!
