### ISSUE TITLE
[4.0] Multilingual Option option when installing

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#28175]
### Is your feature request related to a problem? Please describe.

In Joomla Version 3 it is possible to create a multilingual Website on installation. If I am correct, then I have to set everything up manually in Joomla 4.

### Describe the solution you'd like

I would like the same options in the install routine like in Joomla 3

![install](https://user-images.githubusercontent.com/9974686/75626285-8fa79c00-5bc6-11ea-845f-02d8311db739.png)

**Comment by Quy** [comment]
Duplicate #27059?

**Comment by astridx** [comment]
Sorry, yes it is duplicate.
