### ISSUE TITLE
[4.0] Help Sites RuntimeException

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#28174]
### Steps to reproduce the issue
Go to System > Manage > Content Security Policy and click the help button on the top right corner.

### Expected result
You see Help Page or at least a message, that this page is going to be created.

### Actual result

![Screenshot from 2020-03-01 14-05-58](https://user-images.githubusercontent.com/9974686/75626210-ee204a80-5bc5-11ea-9e47-340ca9bd6fe3.png)

**Comment by zero-24** [comment]
It seams that pages does not exists yet. I'm taking an look on how they are created so we can add the content to it.

**Comment by zero-24** [comment]
@Sandra97 just created the pages:

Components CSP Reports
https://docs.joomla.org/Help4.x:Components_CSP_Reports
 
Components CSP Reports Options
https://docs.joomla.org/Help4.x:Components_CSP_Reports_Options

So they just need some input :)

**Comment by astridx** [comment]
@Sandra97  @zero-24 Thank you

So it is no bug anymore and I can close here.
![Screenshot from 2020-03-01 22-59-24](https://user-images.githubusercontent.com/9974686/75634711-5562ec80-5c10-11ea-9b9c-2dae4f92decb.png)
