### ISSUE TITLE
Warning The security token did not match. 

### ISSUE THREAD

**Issue by peteruoi** [joomla/joomla-cms#28198]
It may be a no issue i just let this here for one day in case it happens to others too...

For some time (maybe a month?) sometimes when i try to login to joomla administrator page
and after pressing  the login button it "freezes" and it doesn't enter at the cpanel. When i press for second time the login button it then enters and the warning i see is

Warning
The security token did not match. The request was aborted to prevent any security breach. Please try again.

I thought it happened only in my sites so it could be a server configuration problem but today i saw the same warning at another joomla site that makes joomla extensions (onlinecommunityhub .nl)

I know i haven't given you a lot of information about how to reproduce because i cannot do it consistenly and if you know it's expected behaviour feel free to close the issue. 
If you think it's no issue close it.
If this is not something that others have noticed  i 'll close it myself in two days.

**Comment by brianteeman** [comment]
The issue here is NOT that you see the message - that is correct behaviour when you try to submit twice. The issue is why it "freezes"

**Comment by peteruoi** [comment]
While "frozen" the spinner in chrome at the bottom left corner spins but never ends...
