### ISSUE TITLE
ERROR: Wrong FTP host or port

### ISSUE THREAD

**Issue by twister65** [joomla/joomla-cms#28199]
### Steps to reproduce the issue

1. Joomla Update -> Upload & Update

2. Choose an update package file.

3. Installation method -> Write files using FTP

4. Set the FTP options.

### Expected result
Update your Joomla files via FTP.

### Actual result
![wrong_ftp](https://user-images.githubusercontent.com/26852967/75794139-ab4ea600-5d70-11ea-8649-d424399e08e3.png)

### System information (as much as possible)
Joomla! Version 3.9.15
PHP Version 7.4.3
Web Server Apache/2.4.41 with APACHE_RUN_USER corresponding to my ftp_login in  /etc/apache2/envvars

### Additional comments
This issue is solved in PR #28029 (Joomla4) using FTP options in the global configuration.
This PR also fixes another issue with the FTP connection function.

**Comment by brianteeman** [comment]
If you are saying that it does NOT currently work in joomla 3 at all and we have had zero reports of this then it would suggest that no one is actually using it.

Or am I missing something

**Comment by ReLater** [comment]
I can confirm the issue with Joomla 3 nightly build of today.

**Comment by twister65** [comment]
@brianteeman , like PostgreSQL 🤔

**Comment by navonwolf** [comment]
A report to recovery the error [io games](https://iogames.onl)[skribbl io](https://iogames.onl/skribbl-io-games)
  
  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28199">issues.joomla.org/tracker/joomla-cms/28199</a>.</sub>

**Comment by PhilETaylor** [comment]
Are we going to fix FTP issues in Joomla 3 Following [the projects decision to remove the FTP Layer](https://github.com/joomla/joomla-cms/pull/33390#issuecomment-830000434) from Joomla 4?

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed.

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc [@zero-24](https://github.com/zero-24)
