### ISSUE TITLE
[4.0] Change sidebar menu 'plus' icons

### ISSUE THREAD

**Issue by minitek** [joomla/joomla-cms#28190]
### Is your feature request related to a problem? Please describe.
In accordion menus, a 'plus' icon usually expands the menu vertically.
Not a good idea to use the 'plus' icon as a symbol to add a new item.

### Describe the solution you'd like
Change the 'plus' icon to a 'pencil' icon for adding new items.

**Comment by richard67** [comment]
@minitek Is my assumption right that this issue refers to J4? This issue doesn't tell anything about that.

**Comment by minitek** [comment]
Yes, it's for J4 
(added [4.0] in title)

**Comment by richard67** [comment]
Thanks

**Comment by richard67** [comment]
@brianteeman What’s your opinion on this?

**Comment by infograf768** [comment]
plus also means adding
pencil would rather mean edit

the plus icon is also used in dashboard menu and quickicons...

**Comment by brianteeman** [comment]
i would leave it as is. its not destructive in anyway if someone misunderstands

**Comment by Quy** [comment]
Closing for reasons stated.
