### ISSUE TITLE
Problem with recapcha, Joomla 3.9.15, Google return "invalid-input-response"

### ISSUE THREAD

**Issue by akbet1** [joomla/joomla-cms#28191]
Hello

### Steps to reproduce the issue
Create recapctha with help PHP in VIEw:

        $captcha = JCaptcha::getInstance('recaptcha', array('namespace' => 'captcha_keystring_rent_request' ));
        echo $captcha->display('recaptcha', 'recaptcha', 'required');

Check  recapctha result in controller, with help PHP:

        $captcha = JCaptcha::getInstance('recaptcha', array('namespace' => 'captcha_keystring_rent_request'));
        if($captcha){
             $answer = $captcha->checkAnswer('captcha_keystring_rent_request'); <-- there exception: Google return "invalid-input-response" 
             if(!$answer) {
                   //show error, "bad filled captcha"
                   exit();
             }
        }

### Expected result
Until Joomla 3.9.15, this code work good (include Joomla 3.9.14)

### Actual result
Now we receive exception from Google.
 

### System information (as much as possible)
Joomla 3.9.15.
reproduce on many PC, keys in recaptcha plugin are good.
In Joomla registration recaptcha works good
Please check attachment

### Additional comments

Regards
Andrew!
[screen shot 2020-03-02 at 19 43 09](https://issues.joomla.org/uploads/1/584945200189290889cb9854c861cf7b.png)

**Comment by brianteeman** [comment]
reset priority according to our published guides<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28191">issues.joomla.org/tracker/joomla-cms/28191</a>.</sub>

**Comment by Fedik** [comment]
what captcha plugin is enabled?
`recaptcha` should work

however `recaptcha_invisible` has a bug in plugin implementation, the plugin ignores `$code` at all
https://github.com/joomla/joomla-cms/blob/35f1325e281164b91f9cdb8a12b540ab4f308275/plugins/captcha/recaptcha_invisible/recaptcha_invisible.php#L128-L138

**Comment by SharkyKZ** [comment]
It's Recaptcha. Since https://github.com/joomla/joomla-cms/pull/26882 it makes use of `$code` argument. It seems correct to me as well, but causes issues when passing whatever to `checkAnswer()` like in this case.

If we keep it as, @akbet1, you'll have to solve it on your end by removing erroneous argument or by passing the actual answer, e.g.

    $answer = $captcha->checkAnswer();

**Comment by akbet1** [comment]
Hi

@Fedik 
If I check joomla-cms/plugins/captcha/recaptcha_invisible/recaptcha_invisible.php
in joomla 3.9.15
I see there code exactly as you propose use
But we use "recaptcha", we not use "recaptcha_invisible"

@SharkyKZ
we use
    $captcha = JCaptcha::getInstance('recaptcha', array('namespace' => 'captcha_keystring_rent_request'));
    $answer = $captcha->checkAnswer('captcha_keystring_rent_request');

"captcha_keystring_rent_request" - it need because we have 2 forms on page, so we need check which captcha user press.

If I try use:
$answer = $captcha->checkAnswer();

I see next error:
Too few arguments to function Joomla\CMS\Captcha\Captcha::checkAnswer(), 0 passed in /home/windsorh/public_html/components/com_realestatemanager/realestatemanager.php on line 945 and exactly 1 expected
File: /home/windsorh/public_html/libraries/src/Captcha/Captcha.php
Line: 177

Regards
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28191">issues.joomla.org/tracker/joomla-cms/28191</a>.</sub>

**Comment by Fedik** [comment]
okay, then what exactly is 'captcha_keystring_rent_request', and how you get it?

**Comment by akbet1** [comment]
As I believe (before), it is namespace, we use it at time show captcha:

    $captcha = JCaptcha::getInstance('recaptcha', array('namespace' => 'captcha_keystring_rent_request' ));
    echo $captcha->display('recaptcha', 'recaptcha', 'required');

so on 1 page we may have 2 captha, as example for show second captcha we use:

    $captcha = JCaptcha::getInstance('recaptcha', array('namespace' => 'captcha_keystring_review' ));
    echo $captcha->display('recaptcha', 'recaptcha', 'required');

'captcha_keystring_review' - another namespace

Regards
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28191">issues.joomla.org/tracker/joomla-cms/28191</a>.</sub>

**Comment by SharkyKZ** [comment]
It's supposed to be the answer.

https://github.com/joomla/joomla-cms/blob/35f1325e281164b91f9cdb8a12b540ab4f308275/libraries/src/Captcha/Captcha.php#L170-L177

**Comment by Fedik** [comment]
> 'captcha_keystring_review' - another namespace

that incorrect, 
` $captcha->checkAnswer($code);` the `$code` supposed to be a token, answer from recpatcha api on client side

**Comment by Fedik** [comment]
@SharkyKZ was faster :smile:

**Comment by akbet1** [comment]
Thank you!
but will be best if you provide "how to", and not only hints, some like:
show captcha:

$captcha = JCaptcha::getInstance('recaptcha', array('namespace' => 'captcha_keystring_rent_request' ));
echo $captcha->display('recaptcha', 'recaptcha', 'required');

check captcha:
        
        //Check enabled plugin captcha-recaptcha
        $recaptchaPluginEnabled = JPluginHelper::isEnabled('captcha', 'recaptcha');

        //Check enable option captcha-recaptcha in admin form
        $app = JFactory::getConfig();
        $recaptchaAdminEnabled = false;
        if($app->get('captcha') == 'recaptcha'){
          $recaptchaAdminEnabled = true;
        }

                if( $googleRecaptchaEnabled && $recaptchaPluginEnabled ){
                    $captcha = JCaptcha::getInstance('recaptcha', array('namespace' => 'captcha_keystring_buy_request'));

                    if($captcha){
                        $get_answer = JFactory::getApplication()->input->get("g-recaptcha-response", "");
                        $answer = $captcha->checkAnswer($get_answer);
                           //check captcha
                            if(!$answer ) {
                            //captcha check error
                            exit();
                        }
                    }
                }

Regards<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28191">issues.joomla.org/tracker/joomla-cms/28191</a>.</sub>

**Comment by akbet1** [comment]
if( $googleRecaptchaEnabled && $recaptchaPluginEnabled ){

need replace to
if( $recaptchaPluginEnabled && $recaptchaAdminEnabled ){<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28191">issues.joomla.org/tracker/joomla-cms/28191</a>.</sub>

**Comment by akbet1** [comment]
but !!!!!!
How this worked in joomla 3.9.14 and before ?!!!
without:
 $get_answer = JFactory::getApplication()->input->get("g-recaptcha-response", "");

Regards<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28191">issues.joomla.org/tracker/joomla-cms/28191</a>.</sub>

**Comment by richard67** [comment]
@akbet1 @SharkyKZ has already provided the answer above [https://github.com/joomla/joomla-cms/issues/28191#issuecomment-593640289](https://github.com/joomla/joomla-cms/issues/28191#issuecomment-593640289):

> It's Recaptcha. Since #26882 it makes use of $code argument. It seems correct to me as well, but causes issues when passing whatever to checkAnswer() like in this case.

PR #26882 was merged end of December last year, this explains that there is a difference between 3.9.14 and 3.9.15.

**Comment by akbet1** [comment]
Hi
But continue this not good, as me seem, you may give possibility run
$answer = $captcha->checkAnswer(); <-- without argumenets

and in plugin, if call with "$code = null", you need add code like below:
 	
public function onCheckAnswer($code = null) 
 	{ 
 		$input      = \JFactory::getApplication()->input; 
 		$privatekey = $this->params->get('private_key');  
                if( $code == null) $code = $input->get("g-recaptcha-response", "");

Regards

**Comment by akbet1** [comment]
But, Thank you for your support !!!

**Comment by SharkyKZ** [comment]
There is already code like that in Recaptcha plugin:

https://github.com/joomla/joomla-cms/blob/35f1325e281164b91f9cdb8a12b540ab4f308275/plugins/captcha/recaptcha/recaptcha.php#L155

If code is not provided, `g-recaptcha-response` input variable is used.

**Comment by akbet1** [comment]
Sorry,
Bur As I wrote:

If I try use:
$answer = $captcha->checkAnswer();

I see next error:
Too few arguments to function Joomla\CMS\Captcha\Captcha::checkAnswer(), 0 passed in /home/windsorh/public_html/components/com_realestatemanager/realestatemanager.php on line 945 and exactly 1 expected
File: /home/windsorh/public_html/libraries/src/Captcha/Captcha.php
Line: 177

Regards<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28191">issues.joomla.org/tracker/joomla-cms/28191</a>.</sub>

**Comment by SharkyKZ** [comment]
You're right. It can't be omitted. So it should be either the answer or `null`.

**Comment by joomdonation** [comment]
More than 2 years later, I guess the author solved this issue base on the suggested code provided by @SharkyKZ in earlier comment. So I'm closing this issue. If you still need help (I don't think so), feel free to re-open.
