### ISSUE TITLE
[4.0] [backend-template] Sidebar menu bug

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28201]
### Steps to reproduce the issue

1. Open the J4 admin dashboard
2. Click on "Content" to the dropdown expands
3. Reduce the viewport size so that the sidebar collapses
4. Hover over any of the menu items

### Actual result

You've notice that the `active` state for "Content" menu item is still there and thus an overlapping light blue/grey box still appears.

See GIF below

![screeny](https://user-images.githubusercontent.com/2019801/75817874-d5639080-5d8f-11ea-9f33-bcdc45389e76.gif)

**Comment by brianteeman** [comment]
i can  see it in your video but could not reproduce locally

**Comment by jwaisner** [comment]
Confirmed. There is an overlap (look closely) and it occurs with all sidemenu items.

![28201](https://user-images.githubusercontent.com/12568201/75891185-0924d180-5df5-11ea-8806-d5f30e1d6217.png)

**Comment by brianteeman** [comment]
really weird - i guess my eyes were too tired last night

**Comment by vijay9908** [comment]
I wasn't able to reproduce the bug , Tried several times but didn't find the overlap

**Comment by Quy** [comment]
I am not able to reproduce the issue. Is it fix with PR #29023?

**Comment by brianteeman** [comment]
@quy yes
