### ISSUE TITLE
[4.0] [backend-template] Accordion tab item hover

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28205]
### Steps to reproduce the issue

1. Reduce viewport size so that the tabs turn into an accordion
2. Hover over any of the inactive items

### Actual result

Causes a 1-2px jump in content. Probably due to the border width on hover.

![tabs](https://user-images.githubusercontent.com/2019801/75819143-fe852080-5d91-11ea-94f8-22fb3c6468e8.gif)

**Comment by jwaisner** [comment]
Confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28205">issues.joomla.org/tracker/joomla-cms/28205</a>.</sub>

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/29093
closing as we have a patch

**Comment by infograf768** [comment]
Reopening as #29093 is no good.

**Comment by ghost** [comment]
Issue is solved.

**Comment by Quy** [comment]
Closing as non-reproducible.
