### ISSUE TITLE
[4.0] [backend-template] Template does respect disabled animations

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28206]
### Steps to reproduce the issue

1. In your OS settings, disable animations
2. Toggle the sidebar menu

### Expected result

Instantly shows/hides

### Actual result

Still expands using an animation

**Comment by brianteeman** [comment]
It could be argued that prefers-reduced-motion should only be applied to parallax  animations. For example we apply it to the candy stripe progress bar. It has also been suggested that it should not apply to single animations such as an animated refresh button (used very rarely but we do use it). We do use it for complex repeating animations such as the joomla loading "throbber".

Anyway it is an easy issue to address
 ```
   @media screen and (prefers-reduced-motion: reduce) {
    * {
      transition: none;
      animation: none;
    }
     }
```

**Comment by chmst** [comment]
My2cent: The animations used in our backend don't affect a11y. They don't meet the Three Flashes or Below Threshold.

The joomla logo disappears as soon as there is something the user can read, so does not disturb. 

Maybe the animated progressbar is catching attention - I'd generally prefer a progressbar without animation, not only for disabled. 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28206">issues.joomla.org/tracker/joomla-cms/28206</a>.</sub>

**Comment by C-Lodder** [comment]
@chmst Remember that the backend will contain views from 3rd party extensions, and who knows what'll they'll add. Better to use a small media query to completely disable animations and transitions to stay on the safe side.

**Comment by chmst** [comment]
You are rigth, I forgot that.

**Comment by brianteeman** [comment]
please test #30873
