### ISSUE TITLE
[4.0] [backend-template] Media Manager settings out of position

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28209]
### Steps to reproduce the issue

1. Go to the Media Manager
2. Select any image and go to edit it
3. Navigate to the "Resize" tab

### Expected result

Settings aligned properly

### Actual result

![media](https://user-images.githubusercontent.com/2019801/75821612-7e14ee80-5d96-11ea-8dc2-7d82ada2620a.png)

**Comment by brianteeman** [comment]
Can not replicate - google chrome - windows 10

![images](https://user-images.githubusercontent.com/1296369/75824337-3c3a7700-5d9b-11ea-98e5-ac4b697e2d17.gif)

**Comment by jwaisner** [comment]
Confirmed. Occurs on 1366x768 resolution screen, windows 10, FireFox<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28209">issues.joomla.org/tracker/joomla-cms/28209</a>.</sub>

**Comment by brianteeman** [comment]
tested again - still dont have an issue with chome but can confirm @jwaisner findings in firefox

**Comment by vijay9908** [comment]
issue confirmed, Using safari 
![Screenshot 2020-03-07 at 7 52 17 PM](https://user-images.githubusercontent.com/43515280/76145227-bde91800-60ad-11ea-9fab-fc6147d7bb0f.jpg)

**Comment by wilsonge** [comment]
@ciar4n is this something you'd be able to look at? It's something browser related as with same laptop/screensize i get different results in chrome/safari (OSX) - clearly something similar on the windows systems exists by the comments above. I assume it's related to how flex is implemented in the browsers?

![Screenshot 2020-03-15 at 16 22 14](https://user-images.githubusercontent.com/1986000/76705564-f5247e00-66d8-11ea-8dbc-ed7808fadba5.png) 

<img width="1274" alt="Screenshot 2020-03-15 at 16 20 44" src="https://user-images.githubusercontent.com/1986000/76705562-f190f700-66d8-11ea-8c4b-20f393e19850.png">

**Comment by ciar4n** [comment]
Looks to be related to `break-inside` (https://developer.mozilla.org/en-US/docs/Web/CSS/break-inside) not been supported in Firefox. I'll create a PR to fix.

**Comment by ciar4n** [comment]
Can anyone tell me where `/media/com_media/css/mediamanager.min.css` is been compiled from?

**Comment by C-Lodder** [comment]
`root/webpack.config.js`

**Comment by ciar4n** [comment]
Thanks Charlie. PR.. #28373

**Comment by wilsonge** [comment]
Thankyou!
