### ISSUE TITLE
[4.0] [backend-template] Gap at bottom menu on mobile

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28202]
### Steps to reproduce the issue

![sidebar](https://user-images.githubusercontent.com/2019801/75818223-63d81200-5d90-11ea-99fa-e284a04233ae.png)

**Comment by brianteeman** [comment]
quicker to write a fix than create an issue

closed see #28210

**Comment by C-Lodder** [comment]
Wish I could say the same about the number of Atum iterations, but who's counting
