### ISSUE TITLE
[4.0] [backend-template] Table headings hover state

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28207]
### Steps to reproduce the issue

1. Go to any table view
2. Hover over one of the table headings

You've notice the link becomes underlined, however there is a blank space at the end that also contains the underline.

![screeny](https://user-images.githubusercontent.com/2019801/75819955-6d16ae00-5d93-11ea-820d-e2d86665801e.png)

Use a margin to push the icon away from the text, not a space.

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/75889437-d85c9080-5e24-11ea-81fb-ef2f47ad58d3.png)

There is no space there. 
Margin does the same - its because of the markup and I am not sure of a css way to resolve it

**Comment by C-Lodder** [comment]
There's a space in the layout, between the `<span>` elements:
```
	<?php if (!empty($data->title)) : ?>
		<span>
			<?php echo Text::_($data->title); ?>
		</span><!-- Span ends here -->
[xxxx]<?php endif; ?>
[xxxx]<span class="<?php echo $icon; ?>" aria-hidden="true"></span>
^^^
whitespace
```

If you make it all one line:

```
<?php if (!empty($data->title)) : ?><span><?php echo Text::_($data->title); ?></span><?php endif; ?><span class="ml-1 <?php echo $icon; ?>" aria-hidden="true"></span>
```

Then it fixes the issue, but will probably fail drone CS tests.

Maybe there's a some PHP magic that can be done

**Comment by brianteeman** [comment]
i will take a look - we have had this issue before with cs breaking stuff

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/28225
