### ISSUE TITLE
[4.0] [backend-template] Sidebar menu dropdown animation glitchy

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28208]
### Steps to reproduce the issue

1. Make sure the sidebar is collapsed.
2. Click on one of the menu items to it expands

### Expected result

Smooth animation

### Actual result

Glitchy animation

![menu3](https://user-images.githubusercontent.com/2019801/75820531-6c324c00-5d94-11ea-9a97-cdd2d3b4de55.gif)

**Comment by jwaisner** [comment]
Confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28208">issues.joomla.org/tracker/joomla-cms/28208</a>.</sub>

**Comment by ciar4n** [comment]
Should be resolved with https://github.com/joomla/joomla-cms/pull/28756
