### ISSUE TITLE
[4.0]Atum color field option

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#28216]
i am not sure about this
but 
1 when we use color schema field nothing was adapt in other color field
2 the other field aren't a color field type
![2020-03-04_08h37_49](https://user-images.githubusercontent.com/2539440/75856398-8f8ce380-5df4-11ea-9f8a-d52f37a4ed71.png)

**Comment by brianteeman** [comment]
thats a bug - they should be color fields

**Comment by micker** [comment]
ok happy to find it

**Comment by N6REJ** [comment]
color field is not being processed properly... I'm looking into it.

**Comment by N6REJ** [comment]
it appears that either color form field is severely broken or it's been severely changed and there is no documentation on how it functions now.
perhaps @C-Lodder or @wilsonge can shed some light on this.
while "simple" control type functions rudimentarily its the only one other then hue that does.

**Comment by C-Lodder** [comment]
@N6REJ The CSS file `jquery.minicolors.css` isn't being loaded which is why the colour fields don't have the square swatch to open the colour pallette. Not sure why if I'm honest. The asset is calling the `minicolors` dependency correctly from what I can see.

**Comment by C-Lodder** [comment]
It works if you use `HTMLHelper` as per below:

```
HTMLHelper::_('stylesheet', 'vendor/minicolors/jquery.minicolors.css', ['version' => 'auto', 'relative' => true]);
HTMLHelper::_('script', 'vendor/minicolors/jquery.minicolors.min.js', ['version' => 'auto', 'relative' => true]);
HTMLHelper::_('script', 'system/fields/color-field-adv-init.min.js', ['version' => 'auto', 'relative' => true]);
```

so it could potentially be a bug within the web asset manager

**Comment by N6REJ** [comment]
@C-Lodder any documentation on how the field functions now?

**Comment by C-Lodder** [comment]
https://docs.joomla.org/J4.x:Web_Assets

**Comment by Fedik** [comment]
there was changes for it #27884
are you sure you run `npm install`?

**Comment by Fedik** [comment]
> The CSS file jquery.minicolors.css isn't being loaded which is why the colour fields don't have the square swatch to open the colour pallette.

ah well, that can be bug with  #27884,
I will check later

**Comment by N6REJ** [comment]
> there was changes for it #27884
> are you sure you run `npm install`?

dozens of times 🗡

**Comment by N6REJ** [comment]
> https://docs.joomla.org/J4.x:Web_Assets

I meant in how the color field is used now.  It's not at all like the docs state.

**Comment by C-Lodder** [comment]
Oh sorry the colour field. I'm not sure if there are docs for all types of colour fields

**Comment by Fedik** [comment]
please test #28271
