### ISSUE TITLE
[4.0]Atum custom logo size

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#28214]
Hello i am not sure that th moment but i tested last atum it was great ! thanks @angieradtke 
i try to customize it and i notice some problem

Actual size
![2020-03-04_08h40_32](https://user-images.githubusercontent.com/2539440/75856050-d3cbb400-5df3-11ea-830d-63a43ba7207f.png)

Good result
![2020-03-04_08h34_44](https://user-images.githubusercontent.com/2539440/75856075-e0e8a300-5df3-11ea-8550-90c4fb870d5e.png)

i think height and width in rem isn't good

**Comment by brianteeman** [comment]
You mean custom logo ??

**Comment by micker** [comment]
yes sorry i will update my title

**Comment by N6REJ** [comment]
what is the purpose of loading 2 images yet only displaying one?
![image](https://user-images.githubusercontent.com/1850089/76111484-f998ba80-5fa5-11ea-853c-c62b66226349.png)

What is the purpose for "small logo".  From what I've seen max-width: 100% would be proper not a fixed rem as @micker stated.

**Comment by brianteeman** [comment]
Sorry it's not obvious to you. The small logo is used when the sidebar is collapsed

**Comment by N6REJ** [comment]
well that was obscure as heck!  would've never thought to look there since it's in an entirely separate part of the page.
ty for telling me.

**Comment by N6REJ** [comment]
@angieradtke would you take a look @ this please.  Doesn't look like flex is being used properly in this case especially considering its used fixed units within a flex container.

**Comment by Quy** [comment]
Please test PR #28839
