### ISSUE TITLE
[4.0]Atum customisation color

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#28215]
Hello i try to custom atum with custom color .. but adaptation isn't complete

when we check a custom color need to adapt border in button
![2020-03-04_08h28_58](https://user-images.githubusercontent.com/2539440/75856196-21482100-5df4-11ea-85af-4c3bd47b2cfa.png)
color schema need to be improve and color in joomla version isn't good
![2020-03-04_08h30_49](https://user-images.githubusercontent.com/2539440/75856199-24431180-5df4-11ea-9e6d-55185cb8fc75.png)
![2020-03-04_08h32_45](https://user-images.githubusercontent.com/2539440/75856202-260cd500-5df4-11ea-9f15-3a7c48398b84.png)

**Comment by vijay9908** [comment]
The present color for Atum is comfortable to use and customising the color scheme isn't required I guess!

**Comment by micker** [comment]
for me its a very cool feature already use it in 70 sites  ... all my client link to see a backend admin with own color !

**Comment by brianteeman** [comment]
Closed as we have a PR

**Comment by coolcat-creations** [comment]
@micker please test https://github.com/joomla/joomla-cms/pull/28788
For Logo Issue can you please open a new issue?
Additionally take care for the new posted issue that you upload in the image options a small squared logo, like a favicon and a bigger also

**Comment by micker** [comment]
ok i will do this
