### ISSUE TITLE
[4.0] Duplicate quickicons

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28212]
### Steps to reproduce the issue

1. Go to dashboard
2. In the "Update Checks" box, click the "cog" icon and go to "Edit"

You then have the ability to show multiple quickicons, resulting in duplicates

![screeny1](https://user-images.githubusercontent.com/2019801/75823137-1ad88b80-5d99-11ea-8d62-ffe8640d5539.png)

![screeny](https://user-images.githubusercontent.com/2019801/75823143-1ca24f00-5d99-11ea-99de-5be010c21784.png)

**Comment by brianteeman** [comment]
cant see any reason to prevent that and i can see acl reasons why it might be desirable

**Comment by chmst** [comment]
This is intented behaviour. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28212">issues.joomla.org/tracker/joomla-cms/28212</a>.</sub>

**Comment by C-Lodder** [comment]
@chmst why is it intended? The "Users" quick icon on the right hand side of the screenshot links to the User Manager page, but the icon comes under the "Update Checks" section.
As far as I can see, it has absolutely nothing to do with Update Checks.

**Comment by chmst** [comment]
Every admin can decide which icon he/she wants to see. If there is only one quickicon panel which contains update checks + users, why not? 
Or, if someone wants to see the users icon in two places, why not? Could make sense  for view levels or user groups as @brianteeman has mentioned

**Comment by C-Lodder** [comment]
I get that each user can decide which icon to hide/show, but there are 2 problems:

1. There is a possibility to show the same quickicon twice. Sorry but I can't seem to understand a real usercase For this.
2. The 2nd quickicon is under the completely wrong category (Update Checks)

**Comment by C-Lodder** [comment]
You say this was intended...can you provide your research results for this requirement? Were There people out there requesting duplicate icons?

**Comment by SharkyKZ** [comment]
It's multiple instances of the same module. Nothing to do here.

**Comment by C-Lodder** [comment]
@SharkyKZ I'll ask again....WHY is this intended? What's the use case for this? WHY is it under the "Update Checks" box when it has nothing to do with this?

Sorry but based on current comments, I feel nobody actually knows the real answer and nobody seems to know of a fix.

**Comment by rdeutz** [comment]
You can also place the same module 3 times on the website. A usecase cold be that you have different modules for different usergroups with a different set of icons

**Comment by alikon** [comment]
why under **update checks** i could or should put something like articles or category etc
it's nonsense imho

**Comment by SharkyKZ** [comment]
There is no "Update Checks" module.

**Comment by infograf768** [comment]
The quickicons module can be totally custom. Just create a new one and you can add there anything you want.

**Comment by infograf768** [comment]
I mean anything present in the xml (code is in QuickiconHelper).

**Comment by chmst** [comment]
What could be seen as issue: The module for update check icons should contain only update check icons. This is another subject.
