### ISSUE TITLE
[4.0] Contrast Color Atum has no contrast

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#28213]
### Steps to reproduce the issue
The atum-contrast-color has very low contrast against the background or against the other dashboardicons.

To see this: hover the dashboarde icons or the "+" icons.

**Comment by brianteeman** [comment]
I took a look at this the other day. They both use the same css which is a problem as one has a dark background on hover and the other does not. Will submit a pr shortly

**Comment by brianteeman** [comment]
Closed please test #28219
