### ISSUE TITLE
[4.0] Backend article panel

### ISSUE THREAD

**Issue by rinka88** [joomla/joomla-cms#28224]
Dear developers! Since there has recently been a [debate](https://github.com/joomla-projects/j4adminui/issues/186) about the admin panel of Atum or Khonsu.
And after a long argument, the Honxu developers closed the topic until next time.
But there were people who said: that you can implement the best sides of Khonsu in Atum. And for this I suggest viewing the topic:
Creation of material on Joomla4:
 **This is how it looks in Atum:**
![Atum](https://user-images.githubusercontent.com/40716604/75892334-f4772680-5e52-11ea-88d7-54c8be2d92a9.png)

**And so in Khonsu:**
![Khonsu](https://user-images.githubusercontent.com/40716604/75892370-01941580-5e53-11ea-9394-c3831d9ea557.png)

I think the result is on the face. In fulfillment of Khonsu, I think it looks well designed and modern. All the necessary tabs are rendered to the right and convenient for filling (tabs). And if this is implemented, then I think not much to change the Atum code. And that would get a good response from the community.
What do you think? can this be realized in Atum?
@angieradtke 
I am writing through google translate

**Comment by brianteeman** [comment]
Those tabs are not usable at all

**Comment by rinka88** [comment]
But this does not mean that you can’t do this and there are people who use these tabs. and by design I think it will look good.

**Comment by brianteeman** [comment]
If they are not usable then it doesnt matter how pretty it is

**Comment by simbus82** [comment]
> If they are not usable then it doesnt matter how pretty it is

I think it is due an explanation of why that solution is not usable. I ask it to fill my ignorance about these UI elements (tabs vs accordion).
PS: i hate all of these solutions, if they are used for the frontend of a website.

**Comment by brianteeman** [comment]
ignoring the fact that they are not accessible or semantic the usability sucks - just try it and see what a frustrating experience it is

![images](https://user-images.githubusercontent.com/1296369/75906738-0e0e7300-5e3f-11ea-8aad-800f8ae854db.gif)

**Comment by simbus82** [comment]
Thanks @brianteeman. With a bigger resolution monitor the bad usability was less noticeable.
As i said, i don't like accordions...

**Comment by ReLater** [comment]
No accordions, please!

**Comment by Sulpher** [comment]
Someone started a good topic! :-)
Well, since Khonsu developers decided to freeze the project until better times (which means the death of the project in the web world where technologies developing too quickly), there are supposedly 2 ways to go:
1. New enthusiasts can fork the current Khonsu version (if someone wants) and continue developing it according to public debates on UX/UI improvements.
2. Atum authors can examine Khonsu and take the best ideas for further implementation. 

What does the community think?

**Comment by 200MPHMEDIA** [comment]
Some improvements are noted, but there are some changes that run counter to norm.  The SAVE buttons being relocated to the right is one of those mistakes.  Why make users re-direct their "save" habits of going up and left, to up and right.  This template needs a complete "user usage autopsy" before make available as an "ALTERNATIVE BACK-END," not the default.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28224">issues.joomla.org/tracker/joomla-cms/28224</a>.</sub>

**Comment by simbus82** [comment]
> Some improvements are noted, but there are some changes that run counter to norm. The SAVE buttons being relocated to the right is one of those mistakes. Why make users re-direct their "save" habits of going up and left, to up and right. This template needs a complete "user usage autopsy" before make available as an "ALTERNATIVE BACK-END," not the default.
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/28224](https://issues.joomla.org/tracker/joomla-cms/28224).

Wrong example... The relocation of Save Button is one of the best things made in that backend.
I'm using tons of productivity, management and creativity, CMS web apps every day and only Joomla has the save on the left...

**Comment by 4digitalworld** [comment]
> 
> 
> Well, since Khonsu developers decided to freeze the project until better times 

I think this could help for anyone who wants to make an alternative template. Look at my issue - [https://github.com/joomla/joomla-cms/issues/28167](https://github.com/joomla/joomla-cms/issues/28167)

**Comment by brianteeman** [comment]
Not sure if there is any value in keeping this issue open. Perhaps move it to discussions or close?

**Comment by Hackwar** [comment]
Khonsu has not been adopted in Joomla and Joomla 4 has since been released without these changes. We are not going to change the UI this drastically in a minor version. I'm going to close this issue.
