### ISSUE TITLE
[4.0] Module XTD filters admin type and positions instead of site

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#28220]
### Steps to reproduce the issue
Edit/create an article in back-end or frontend.
Select CMS Content => Module
Display filters

<img width="567" alt="Screen Shot 2020-03-04 at 11 05 12" src="https://user-images.githubusercontent.com/869724/75869790-61b29980-5e0a-11ea-99a1-4ec6d9d3abe4.png">
<img width="1054" alt="Screen Shot 2020-03-04 at 11 04 40" src="https://user-images.githubusercontent.com/869724/75869796-6414f380-5e0a-11ea-88ca-3940fd6379b6.png">

**Comment by brianteeman** [comment]
confirmed

**Comment by infograf768** [comment]
This solution works here by forcing the clientid in the view
i.e.

```
// If in modal layout.
		else
		{
			// Client id selector should not exist.
			$this->filterForm->removeField('client_id', '');
			$this->clientId = 0;  /// Force clientid to site

			// If in the frontend state and language should not activate the search tools.
			if (Factory::getApplication()->isClient('site'))
			{
				unset($this->activeFilters['state']);
				unset($this->activeFilters['language']);
			}
		}
```
~Shall I make PR?~

**Comment by infograf768** [comment]
Making PR as I don't see another solution.

In site, we have other issues preventing these fields from display.
Preparing a general PR for frontend xtd display containing searchtools which will not solve the problem with these fields as well as for articles filters, but solves contact and menu.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/28221

**Comment by infograf768** [comment]
re-opening as pr does not work anymore
