### ISSUE TITLE
[4.0]atum login page concept ?

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#28222]
hello i am not sure to understand the concept of the login page ...
![2020-03-04_13h32_26](https://user-images.githubusercontent.com/2539440/75879995-bf4fe180-5e1c-11ea-92cd-82914d2b8d52.png)
the left side is customizsable ? what is the objectif ? can we change url for support ?
imagine for web agnecy this link isn't good ... they user will be redirect to joomla forum, confusion bettween pro support (agency) and community forum 
for me that take much place  for no interesting information
if we check a same presentation i check crowdin
![image](https://user-images.githubusercontent.com/2539440/75880238-31c0c180-5e1d-11ea-9a58-4209d3ea43e8.png)
=> the ratio is better because left side isn't empty ...
![image](https://user-images.githubusercontent.com/2539440/75880397-7ba9a780-5e1d-11ea-993d-1b034c48bcee.png)

or remove left side
![image](https://user-images.githubusercontent.com/2539440/75880606-e3f88900-5e1d-11ea-8f91-d9b84deb6564.png)

 
sorry for my bad english

**Comment by brianteeman** [comment]
Those links exist specifically for agencies. The links are all in a module. Just a regular custom module where you can put what you want

**Comment by micker** [comment]
oh cool maybe we can enchance the display and proportion (many blank part).. i will search a little

**Comment by brianteeman** [comment]
I will close this for now
