### ISSUE TITLE
[4.0] non-svg logo gives js error

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#28226]
### Steps to reproduce the issue
Change the site logo for the admin template to any type of jpg or png

### Expected result
Image displayed without error

### Actual result
Image displayed with js error below

```
uncaught TypeError: Cannot read property 'removeAttribute' of undefined
    at onSuccess (template.js?1f22f7c44da70e959cfcdbc249e4a13b:96)
    at XMLHttpRequest.xhr.onreadystatechange (core.js?1f22f7c44da70e959cfcdbc249e4a13b:823)
onSuccess @ template.js?1f22f7c44da70e959cfcdbc249e4a13b:96
xhr.onreadystatechange @ core.js?1f22f7c44da70e959cfcdbc249e4a13b:823
XMLHttpRequest.send (async)
Joomla.request @ core.js?1f22f7c44da70e959cfcdbc249e4a13b:837
(anonymous) @ template.js?1f22f7c44da70e959cfcdbc249e4a13b:78
changeSVGLogoColor @ template.js?1f22f7c44da70e959cfcdbc249e4a13b:74
(anonymous) @ template.js?1f22f7c44da70e959cfcdbc249e4a13b:276

```

### Additional comments
I am guessing that this code is failing because it cant find an svg image

**Comment by brianteeman** [comment]
Should be a super easy fix for anyone that understands the javascript to check if the image is an svg before continuing

**Comment by vijay9908** [comment]
Can you explain how I can reproduce the bug in a clear way?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28226">issues.joomla.org/tracker/joomla-cms/28226</a>.</sub>

**Comment by brianteeman** [comment]
in the admin template style set a logo that is a jpg or png image

**Comment by chmst** [comment]
https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/templates/atum/js/template.es6.js#L81 here the parsing fails if the img is not svg<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28226">issues.joomla.org/tracker/joomla-cms/28226</a>.</sub>

**Comment by N6REJ** [comment]
> https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/templates/atum/js/template.es6.js#L81 here the parsing fails if the img is not svg
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/28226](https://issues.joomla.org/tracker/joomla-cms/28226).

thats for applying color only isn't it?  Strange that it would even be called.

**Comment by chmst** [comment]
I think that this replaces the big logo (j-logo + "joomla") by the small logo (J-logo only) and vice versa when the Sidebar is toggled.

**Comment by brianteeman** [comment]
the part of the js that is the problem is changing the color of the svg but it does it without checking to see that the logo is an svg and therefore produces the error when the logo is a png or jpg

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/28295.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28226">issues.joomla.org/tracker/joomla-cms/28226</a>.</sub>
