### ISSUE TITLE
[Twemoji] plugin for displaying emoji images

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#28228]
### Is your feature request related to a problem? Please describe.
Since @Joomla uses [Bootstrap](https://github.com/twbs/bootstrap), I also suggest adding support for emoji characters in the form of [Twemoji](https://github.com/twitter/twemoji) images from @Twitter.

This will help to solve at least the problem with displaying the emoji of flags.

I did not find extensions for Joomla that would show images for emoji symbols.

### Describe the solution you'd like

**How these symbols look now:**
![изображение](https://user-images.githubusercontent.com/3662519/75913224-9999fb00-5e63-11ea-873b-0e1d63ab6a87.png)

**How these symbols may look:**
![изображение](https://user-images.githubusercontent.com/3662519/75913311-bf270480-5e63-11ea-8370-fbbca9da42c8.png)

### Additional context
This plugin can be `enabled` / `disabled` in the settings.

[https://github.com/twitter/twemoji](https://github.com/twitter/twemoji)
[https://twemoji.twitter.com/](https://twemoji.twitter.com/)

**Comment by 4digitalworld** [comment]
@810 What do you think about this? This could be used in Articles `com_content` and @Kunena forum.

**Comment by brianteeman** [comment]
I thought emoji support was added years ago

**Comment by 4digitalworld** [comment]
> 
> 
> I thought emoji support was added years ago

Emoji **symbols** support has been added. I suggest adding the display of these symbols as **images** (for example: country flags are now displayed as letters, if we go to a website from a computer, in android flags are displayed as images, because there they are displayed as images)

**Comment by brianteeman** [comment]
Sorry I dont understand

**Comment by 4digitalworld** [comment]
> 
> 
> Sorry I dont understand

Images from the flags folder ([Twemoji](https://github.com/twitter/twemoji)) could also be used for display in the multilingual `module`. I think that would be great.

**Comment by brianteeman** [comment]
actually it doesn't matter - we cannot use that because of the license

**Comment by 4digitalworld** [comment]
> 
> 
> actually it doesn't matter - we cannot use that because of the license

So bad. I thought it was an open source project that could be added. But anyway, I think something like this can be done for Joomla in the future.
