### ISSUE TITLE
[4.0] Component wrapper -  Class 'Joomla\Component\Wrapper\Administrator\Extension\WrapperComponent' not found

### ISSUE THREAD

**Issue by bugsmafia** [joomla/joomla-cms#28231]
### Steps to reproduce the issue
Create any component menu item with output wrapper 

### Crashe error

`0 Class 'Joomla\Component\Wrapper\Administrator\Extension\WrapperComponent' not found`

Call stack
--
# | Function | Location
1 | () | JROOT/administrator/components/com_wrapper/services/provider.php:49
2 | class@anonymous/home/c/cj45623/goodhouse/public_html/administrator/components/com_wrapper/services/provider.php0x7f43f6141737->{closure}() | JROOT/libraries/vendor/joomla/di/src/ContainerResource.php:182
3 | Joomla\DI\ContainerResource->getInstance() | JROOT/libraries/vendor/joomla/di/src/Container.php:96
4 | Joomla\DI\Container->get() | JROOT/libraries/src/Extension/ExtensionManagerTrait.php:176
5 | Joomla\CMS\Application\CMSApplication->loadExtension() | JROOT/libraries/src/Extension/ExtensionManagerTrait.php:46
6 | Joomla\CMS\Application\CMSApplication->bootComponent() | JROOT/libraries/src/Component/ComponentHelper.php:384
7 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:196
8 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:235
9 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:232
10 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:63
11 | require_once() | JROOT/index.php:36

**Comment by SharkyKZ** [comment]
I can't reproduce this issue. Are you using nightly or git clone? Check if `administrator\components\com_wrapper\src\Extension\WrapperComponent.php` exists.

**Comment by bugsmafia** [comment]
> I can't reproduce this issue. Are you using nightly or git clone? Check if`administrator\components\com_wrapper\src\Extension\WrapperComponent.php`exists .
04/03/2020
https://developer.joomla.org/nightlies/Joomla_4.0.0-beta1-dev-Development-Full_Package.zip


administrator\components\com_wrapper\src
"src" 
The folder is missing.
Now I’ll add it manually from the repository.

**Comment by bugsmafia** [comment]
This did not fix the problem.
updated all files by night build

**Comment by SharkyKZ** [comment]
Works for me on clean installation with the provided package. Have you tried deleting `libraries/autoload_psr4.php` file?

**Comment by bugsmafia** [comment]
No, this file is present.
Removed it and everything works.
