### ISSUE TITLE
[3.x] Textarea form field type - cols attribute ignored

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#28237]
### Steps to reproduce the issue
The cols attribute of the textarea field type is been ignored. Create a textarea field type... 

```xml
<field name="mytextarea" type="textarea" default="default" label="Enter some text" description="" rows="10" cols="50" />
```

### Expected result
A textarea of 50 cols width

### Actual result
Textarea always 206px width

### Additional comments
**cols** attribute been overridden by the following....

https://github.com/joomla/joomla-cms/blob/2e40eb237e825eb7bd9187ff2865cb00f532bd3d/media/jui/less/forms.less#L94-L98

**Comment by Mayank-Khurmai** [comment]
#A textarea of 50 cols width

I can resolve this issue of improper size variation

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed.

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc [@zero-24](https://github.com/zero-24)
