### ISSUE TITLE
Calendar field doesn't display empty value (when mysql db type column is DATE and not DATETIME)

### ISSUE THREAD

**Issue by fuscage** [joomla/joomla-cms#28232]
### Steps to reproduce the issue

Change a DATETIME field to DATE (in MYSQL)

ALTER TABLE `jos_content` CHANGE `publish_down` `publish_down` DATE NOT NULL DEFAULT '0000-00-00 00:00:00';

Open a content (with end publish date at empty) and see the field displays "30-11-2001 00:00:00" and doesn't display empty

![image](https://user-images.githubusercontent.com/19620381/75958608-e5c55980-5ebc-11ea-9836-eccda2787079.png) 

### Expected result

empty in field calendar

### Actual result

"30-11-2001 00:00:00"

### System information (as much as possible)

joomla 3.9.15, mysql

### Additional comments

Because in the librairies/joomla/form/field/calendar.php file the getNullDate fonction return always the time??

```
// Format value when not nulldate ('0000-00-00 00:00:00'), otherwise blank it as it would result in 1970-01-01.
		if ($this->value && $this->value != JFactory::getDbo()->getNullDate() && strtotime($this->value) !== false)
		{ ...
```

**Comment by gerryfrancis** [comment]
Computers use values to interpret date and time. In theory, "0000-00-00 00:00:00" is the time when Jesus Christ was born, but the first computers were invented over 1900 years later. This date is not null, but it has a value that just cannot be processed. ;)

**Comment by richard67** [comment]
The calendar field is made for datetime, not for date database fields. Joomla core used datetime only (and on PostgreSQL timestamp withut time zone), not date.

So to be honest: I am not sure if this here is really an issue or a wrong usage of the calendar field.

**Comment by richard67** [comment]
@wilsonge What do you think? Should the calendar field support date (without time) database column type? I don't think so, but I might be wrong.

**Comment by brianteeman** [comment]
I agree with you - its a date time field not a date field - at least as far as the definition of the field. Displaying of the date is a different issue and is down to the formatting of the data not how it is stored.

**Comment by Bakual** [comment]
You certainly also need to adjust the calendar field format to not show the time. Also you need to remove the UTC filtering so no timezone is applied.

**Comment by richard67** [comment]
@brianteeman @Bakual So what do you suggest? Closing as no issue?

**Comment by brianteeman** [comment]
Closed for the reasons stated above
