### ISSUE TITLE
[4.0] The text with hovering on Search in contents/Articles is out of bounds

### ISSUE THREAD

**Issue by vijay9908** [joomla/joomla-cms#28253]
### Steps to reproduce the issue
in the contents , select Articles and hover across Search bar to find the out of bound text

### Expected result
A neat and clear text hover is visible.

### Actual result
The hover text is not visible completely and font is not clean

### System information (as much as possible)
I observed this issue with [safari.]
![now](https://user-images.githubusercontent.com/43515280/76102272-c4b45400-5ff5-11ea-8424-1cdc457d3cca.gif)
![Screen-Recording-2020-03-06-at-9](https://user-images.githubusercontent.com/43515280/76102308-d4339d00-5ff5-11ea-8009-9cd65e6b0e9e.gif)

**Comment by Quy** [comment]
Duplicate #28246
