### ISSUE TITLE
[4.0] Sidebar overflow issue when opening

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#28260]
### Steps to reproduce the issue
From closed, open the sidebar menu. Menu items displayed before sidebar is opened. The issue comes from https://github.com/joomla/joomla-cms/pull/27352 which required `overflow:hidden` to be removed from the sidebar.

(gif slowed down to emphasize)

![mVp8Qlxpfc](https://user-images.githubusercontent.com/2803503/76141149-7b95eb80-6059-11ea-8797-7afe60c3ed5f.gif)

**Comment by jwaisner** [comment]
Confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28260">issues.joomla.org/tracker/joomla-cms/28260</a>.</sub>

**Comment by Quy** [comment]
Please see if PR #33628 is a fix. Thanks.

**Comment by Quy** [comment]
Closing since no longer reproducible.
