### ISSUE TITLE
[4.0] min height calculation

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#28276]
The calculation for the minimum height is not correct. If correct the login page and the home dashboard wouldn't have the need for a scroll

https://github.com/joomla/joomla-cms/blob/530225bc70d702018cb11130e3967f1fe4b24401/administrator/templates/atum/scss/blocks/_global.scss#L102-L106

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/28281
