### ISSUE TITLE
[4.0] API language files

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#28270]
As a quick fix the language folder and files were created in the /api folder

[ ] They appear in discover - nothing on a clean install should be there
[ ] Should they be part of the language package
[ ] How does a language pack install to the api folder

cc @wilsonge

**Comment by wilsonge** [comment]
There’s already been PRs for language pack (On phone but will try and dig it out in a bit when home). It depends if you do package installs or all in 1 (both should work).

Yup sounds like it should be added to the pack - I think site and admin are currently separate installs in the package? But whichever way should be treated same as site and admin are now

**Comment by SharkyKZ** [comment]
I think we just need to add `#__extensions` entries to installation/update SQL.

**Comment by Bakual** [comment]
Yep, admin and site are separate "extensions", usually installed with a package. So the api would ideally be a third extension within that pack. Looking at the files, the needed XMLs are already present.
It needs to be added to the package (https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/manifests/packages/pkg_en-GB.xml) and as @SharkyKZ wrote to the #__extensions

**Comment by brianteeman** [comment]
IF that's the way you want to go forward I can do the PR

**Comment by Bakual** [comment]
I haven't thought much about it yet, but I'd say it's the simplest approach. If you can do the PR, that would be appreciated.
Just saw Crowdin needs some adjustment in https://github.com/joomla/joomla-cms/blob/4.0-dev/crowdin.yml as well so it picks up the new XML files.

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/manifests/packages/pkg_en-GB.xml

api in here too

**Comment by brianteeman** [comment]
are you sure crowdin.yml needs updating? I can see the api on line 15

**Comment by brianteeman** [comment]
PR at #28282

**Comment by wilsonge** [comment]
@brianteeman Crowdin has the ini files but not the xml files

**Comment by brianteeman** [comment]
ah
