### ISSUE TITLE
[4.0] Choices css on filters

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#28272]
Sorry my scss-fu is not good enough to fix this - I can do some but not all. @angieradtke can you?

[ ] text color
[ ] border-radius
[ ] border color
[ ] border color : focus
[ ] box-shadow
[ ] box-shadow : focus 

![before](https://user-images.githubusercontent.com/1296369/76163661-00f3cb80-6140-11ea-8bcd-5e08ef35c422.gif)

**Comment by angieradtke** [comment]
select tags should like select access?

**Comment by angieradtke** [comment]
`.choices.is-focused
{border-color:#39f;
box-shadow: 0 0 0 .2rem #d3e2f5;}`

But.... it looks a little bit strange at the bottom

**Comment by brianteeman** [comment]
I have done most bits except for the part that makes the box-shadow when focused have rounded corners and not square ones - can't find that

**Comment by jwaisner** [comment]
Confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28272">issues.joomla.org/tracker/joomla-cms/28272</a>.</sub>

**Comment by angieradtke** [comment]
ah now I understand.
`administrator/templates/atum/scss/vendor/choicesjs/choices.scss`

`
.choices__inner {
  border: $input-border;
  border-radius: $border-radius;
  box-shadow: $input-box-shadow;
}

.choices.is-focused
  {
   .choices__inner {
     border-color: $focuscolor;
     box-shadow: $focusshadow

  }
}


`

**Comment by brianteeman** [comment]
thanks - will check it later and submit pr

**Comment by brianteeman** [comment]
did you check that - It doesnt impact on the focus box-shadow corners - they are still square

**Comment by angieradtke** [comment]
border-radius: $border-radius; ???
I have that
![brian](https://user-images.githubusercontent.com/1172403/76296757-f9a2fe00-62b6-11ea-8b6d-8a77fb7293f8.jpg)

**Comment by brianteeman** [comment]
@angieradtke I dont know how you get this to work

It cannot work because $border-radius is not defined in 
```
// Atum Variables
@import "../../variables";
```

**Comment by angieradtke** [comment]
it's a bootstrap var
media/vendor/bootstrap/scss/_variables.scss

**Comment by brianteeman** [comment]
well your code still doesn't work for me - odd

**Comment by angieradtke** [comment]
hm?

What does the inspector  says? Do you get an error message?

Am 10.03.2020 um 10:30 schrieb Brian Teeman:

**Comment by brianteeman** [comment]
can you post an image of your successful inspector please

**Comment by angieradtke** [comment]
sure .-)
![brian](https://user-images.githubusercontent.com/1172403/76323032-6d0f3480-62e4-11ea-8394-86e03e33db66.jpg)

**Comment by brianteeman** [comment]
I still get the square corners

**Comment by infograf768** [comment]
Folks. you are not talking about the same thing
@angieradtke 
your patch does work by adding a rounded shadow when the choice is limited to one item (select the category when editing an  article.)
It does not work when the choices is multiple (searchtools)

**Comment by angieradtke** [comment]
I'm confused
![shot1](https://user-images.githubusercontent.com/1172403/76396333-464f0d80-6379-11ea-87a9-f18ce514f95c.jpg)
![shot2](https://user-images.githubusercontent.com/1172403/76396335-4818d100-6379-11ea-9ce8-0e69f3d8318a.jpg)

**Comment by angieradtke** [comment]
will  update my branch

**Comment by infograf768** [comment]
Select condition, select stage, select language etc, do not use fancyselect and choices.

Select category, Select author, Select Tag do (in searchtools), but they are multiple choices fields. Select category when editing an article is a single choice.

![shadow](https://user-images.githubusercontent.com/869724/76396873-56b3b800-637a-11ea-84d4-137946ef2fca.gif)

**Comment by brianteeman** [comment]
Based on the class names that @angieradtke mentioned she is talking about the correct place

**Comment by infograf768** [comment]
The problem is not the class name.
What I am trying to explain is that her patch works when fancy select is set to select-one, NOT when fancyselect is set to multiple...
TBH I don't care about such petty issues. There are more important stuff to deal with.

**Comment by brianteeman** [comment]
Sorry you are completely wrong. And if you don't care then don't comment. You don't have to comment on everything

**Comment by infograf768** [comment]
GL

**Comment by angieradtke** [comment]
it's a  browser issue.
Firefox has rounded corners, will take a look

**Comment by angieradtke** [comment]
the border-radius has to go to :

`
.choices {
  border: 0;
  border-radius:$border-radius;
}`
