### ISSUE TITLE
[4.0] Dashboard icon's background overlaps

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#28289]
### Steps to reproduce the issue
Hover over a dashboard icon

![dashboard](https://user-images.githubusercontent.com/368084/76229711-dbb69a00-61df-11ea-87ba-82efb5584d50.jpg)

**Comment by jwaisner** [comment]
I am not able to reproduce on the latest:

![28289](https://user-images.githubusercontent.com/12568201/76237783-cbf97e80-61fc-11ea-8620-b81783bb4490.png)

**Comment by brianteeman** [comment]
Closed see #28290
