### ISSUE TITLE
[4] Atum. Buttons behavior on resize.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#28288]
### Steps to reproduce the issue
- Change window width to 767px (sm)!
- Go to "Joomla Update"!
- Check buttons! OK.

![001](https://user-images.githubusercontent.com/20780646/76222519-fa865200-621a-11ea-8c99-61fd43710ae4.jpg)

- Change window width to 575px (xs)!
**=> Wrong icon to hide the buttons.**

![002](https://user-images.githubusercontent.com/20780646/76222549-0540e700-621b-11ea-85e3-db18b3838ada.jpg)

- Click icon to hide the buttons!
**=> Nothing happens but icon changes.** Correct icon now.

![003](https://user-images.githubusercontent.com/20780646/76222611-1db10180-621b-11ea-8dfa-bb270083d535.jpg)

- Click icon to hide the buttons! OK. Buttons hidden now. Icon to show them is present.

![004](https://user-images.githubusercontent.com/20780646/76222659-2bff1d80-621b-11ea-9c87-b8f6406250e4.jpg)

- Change window width to 767px (sm)!
**=> No buttons. One have to reload the page to get them back.**

![005](https://user-images.githubusercontent.com/20780646/76222741-4df8a000-621b-11ea-85bc-068c12ba2a43.jpg)

**Comment by brianteeman** [comment]
is this a duplicate of #27958

**Comment by ReLater** [comment]
I don't know.
