### ISSUE TITLE
[4] Atum. Webinstaller. Pixel card heights create several overflows and cropped texts

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#28296]
### Steps to reproduce the issue
- Go to installer > Install From Web
- Fiddle with screen sizes. With any similiar issues:

![0001](https://user-images.githubusercontent.com/20780646/76298530-e0e81780-62b9-11ea-8144-482936e346e8.jpg)

### Reason

![0002](https://user-images.githubusercontent.com/20780646/76298560-ef363380-62b9-11ea-9f52-dd4781d3ce82.jpg)

![0003](https://user-images.githubusercontent.com/20780646/76298574-f3fae780-62b9-11ea-9b39-bec7cc34514e.jpg)

**Comment by mbabker** [comment]
If someone wants to improve the design then go for it but in the meta task there was an item about restoring the fade effect on the bottom of these cards.  And yes, a fixed height is needed otherwise things get a lot worse.

**Comment by ReLater** [comment]
The backend rulers will find a way. Perhaps they remove it or hide it somewhere because it's rarely used by them ;-)
