### ISSUE TITLE
Checking the database structure

### ISSUE THREAD

**Issue by fontanil** [joomla/joomla-cms#28292]
### Steps to reproduce the issue
After update beta1dev goto System->Information->database: 

### Expected result
Database uptodate

### Actual result
"One problem": "Table '#__webauthn_credentials(' does not exist"
 '(' in excess, I mean.

### System information (as much as possible)
Joomla! 4 beta1dev march 09 2020 updated this morning
PHP 7.3.13

**Comment by alikon** [comment]
should be fixed when #28254 will be merged
