### ISSUE TITLE
Display Registered Users Front End

### ISSUE THREAD

**Issue by johnnydevs** [joomla/joomla-cms#28294]
Using Joomla 3.9.15

Currently there's no default way of showing as list of registered users on the front end. I think this is a drawback and would benefit many sites.

The only way to do this currently is to develop a custom plugin or module, which isn't suitable for everyone.

**Comment by gerryfrancis** [comment]
There are many plugins available for this, just have a look [here](https://extensions.joomla.org/category/clients-a-communities/members-lists/).

**Comment by johnnydevs** [comment]
Thanks @gerryfrancis but the reason I posted here is because I think it should be a default feature within Joomla. 

Apologies if this is in the wrong place, I though I tagged it with 'Feature Request'.

There are reasons when adding an additional plugin / extension isn't an option. 

At current it's possible to view site contacts on the font end, surely extending this to site users could also be considered and would be beneficial?

**Comment by brianteeman** [comment]
I don't see any reason to add this to the core. It would not be somethign that the majority of sites would need and there are extensions available

**Comment by johnnydevs** [comment]
HI @brianteeman, thanks for your comment.

Can I ask how you know it would not be something the majority of sites would need? 

Personally I've looked for this feature many times, I've also been asked for this by clients. Each time I've had to use a custom plugin or custom code. I think it would be very beneficial to have this as a default menu item, for example. 

There are also numerous posts online asking how to achieve this, see SE, JSE, Joomla Forum etc. This would indicate it's something people are looking for?

Also, I think there are current core features that the majority of sites would not need but there are available.

Thanks

**Comment by gerryfrancis** [comment]
@johnnydevs 

> Each time I've had to use a custom plugin or custom code.

That is the concept of Joomla!: If there is no built-in function you could use for your site, get a plugin to make things work. :)

> Also, I think there are current core features that the majority of sites would not need but there are available.

... as there are many plugins, too, IMHO. Do you see the parallels? ;)

**Comment by johnnydevs** [comment]
@gerryfrancis Thanks for your comments.

I disagree, if there's no built-in function for Joomla there should be a way of requesting this, if it gets turned down by the community then that's fair. That's what I'm attempting to do, request a feature that I think would benefit the community :) 

I don't think the answer should ever be 'We don't have it, go somewhere else and get it.'. In my opinion, the whole concept of Joomla is for us (customers and users) to further develop and maintain the CMS, this involves highlighting shortcomings and potential new features. Granted, some advanced features can't be expected by default, that's where third party plugins come in useful.

**Comment by brianteeman** [comment]
There is a PR for this feature already https://github.com/joomla/joomla-cms/pull/25030 but it looks like the author has abandoned it

**Comment by jwaisner** [comment]
If this is a feature request, it must be for J4. Adjusted labeling to match J4 feature request.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28294">issues.joomla.org/tracker/joomla-cms/28294</a>.</sub>

**Comment by AndySDH** [comment]
By the way, you can already do this by using the Contacts Component and the Contact Creator Plugin.

Follow this guide:
https://www.joomlashack.com/blog/joomla/contact-creator/

In the settings, you can set to hide the contact form, and show the user profile field. You can even show the user custom field and the articles written by the user. It's all in the core options for the Contacts component.

I personally dislike the way it's done too, but hey, at least it can be done :)

**Comment by joomdonation** [comment]
I'm closing issue for now because :

- There is third party extension offer this feature
- There is workaround using Contacts component using as mentioned by @AndySDH
