### ISSUE TITLE
[3.x] Tag form field does not allow empty when not multiple, forces the first option

### ISSUE THREAD

**Issue by hakanara** [joomla/joomla-cms#28298]
### Steps to reproduce the issue
Create any component with a tag field like in joomla docs:
<field name="tags" type="tag" label="JTAG" description="JTAG_DESC" mode="ajax" />
Do not define the `"multiple="true"` as it is an optional parameter.

### Expected result
I expect the tag field to be optional when I don't define it as required. But when I don't choose "multiple" in the field parameters:
1. It forces me to add the first tag in the options when I post the form. So posting an empty tag is not possible. This is only possible in multiple mode. Why not in single mode? I try adding `<option value="">Please select your option</option>` as in SQL field, but it does not work. 
2. In single mode, defining Nested or Ajax mode does not differ, it always behaves as a simple listbox with options in it.
3. In single mode, the custom mode does not work as described in the docs: "**custom (optional)** if the ajax mode is chosen, setting this to deny will prevent users from adding in new tags." It is never possible to add a new tag item in the single mode no matter how you define the custom setting of the tag.

### Actual result
As decsribed above, it forces the form to chose the first item of the tag and records it in the database even if you don't choose anything from the tags. It is never possible to leave this field empty in the single mode.

### System information (as much as possible)
Latest all

### Additional comments
I also couldn't manage to post the language field empty for all/any languages or post an asterisk as in article manager. The issue seems to be similar but I didn't dig into it much as it is OK for me to force any language or a default setting of the field at the moment.

**Comment by SharkyKZ** [comment]
I can't reproduce the issue. We have a field like this and the empty `- Select Tag -` option appears correctly.

https://github.com/joomla/joomla-cms/blob/2e40eb237e825eb7bd9187ff2865cb00f532bd3d/administrator/components/com_contact/models/forms/filter_contacts.xml#L58-L67

**Comment by Quy** [comment]
Closing due to no response.
