### ISSUE TITLE
[4.0] Partial border display of Permissions table

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#28316]
### Steps to reproduce the issue
Edit an article
Go to Permissions tab

### Actual result

![permissions](https://user-images.githubusercontent.com/368084/76372487-cda96c00-62fa-11ea-8021-acae164915de.jpg)

**Comment by chmst** [comment]
Confirmed.

It is a consequences from:  https://github.com/joomla/joomla-cms/pull/28129 
We must find a more generic solution.  
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28316">issues.joomla.org/tracker/joomla-cms/28316</a>.</sub>

**Comment by brianteeman** [comment]
see #28317
