### ISSUE TITLE
[Multilingual Associations] Menu item > Associations button, does not display the Edit Associations view

### ISSUE THREAD

**Issue by rvbgnu** [joomla/joomla-cms#28310]
### Steps to reproduce the issue
In the back end
- Edit a Menu item, with or without a previous language association
- Use the **Association** button just beside the **Close** one
![screen shot 2020-03-10 at 17 08 39](https://issues.joomla.org/uploads/1/6699f99103e1080430a8b829a0c1d558.png)

### Expected result
It is expected to go to the view **Multilingual Associations: Edit Associations (Menus > Menu items)**
![screen shot 2020-03-10 at 17 08 59](https://issues.joomla.org/uploads/1/1675bb6a123eb85180607ef20a46b658.png)

### Actual result

The **Edit** view closes with the green message **Menu item saved.**.

### System information (as much as possible)

Joomla 3.9.16 (official release and RC)
Works as expected on 3.9.15, 3.9.14, 3.9.4.

### Additional comments

- Related to
https://github.com/joomla/joomla-cms/pull/27941
as without this patch, it works as expected.
- the **Associations** tab (second last before **Module Assignment**) is working as expected.

**Comment by infograf768** [comment]
Confirmed.
@Bakual

**Comment by rvbgnu** [comment]
Thanks Jean-Marie for your help in the Glip chat.

**Comment by Bakual** [comment]
Please try https://github.com/joomla/joomla-cms/pull/28314
