### ISSUE TITLE
[4.0] Add support search ID in articles and modules managers in search field admin panel.

### ISSUE THREAD

**Issue by korenevskiy** [joomla/joomla-cms#28311]
### Steps to reproduce the issue
For a very large number of 1500 articles and a large number of 100 modules . 
 It is very inconvenient to search by sorting materials.
 For example, among 1500 materials, it is extremely difficult to find a material with ID 525.
At the same time, we know that searching for material by ID is a very common task.
.
You also need to add a filter for several categories, several types , and several positions for modules in the module Manager.

**Comment by brianteeman** [comment]
You can already do this in joomla 3 and have been able to do so for a long time.

![image](https://user-images.githubusercontent.com/1296369/76340305-47d5f280-62f3-11ea-87ad-8b01bbbd3709.png)

**Comment by korenevskiy** [comment]
@brianteeman
> You can already do this in joomla 3 and have been able to do so for a long time.


But no one knows about it. Maybe we can add filter buttons like in the picture. Then everyone will know about filters. Even clients and article editors will know.
![image](https://user-images.githubusercontent.com/6898474/76341407-0d2d8380-630e-11ea-8bb1-f0ced9d6dd34.png)

For example, for the ID column, you can set the filter range from 10-20, and for the type column, set the check boxes, and for the date field, set the calendar.

**Comment by korenevskiy** [comment]
For example, for the ID column, you can set the filter range from 10-20, and for the type column, set the check boxes, and for the date field, set the calendar.

**Comment by brianteeman** [comment]
Sorry - just because you didnt know about a feature that has been in joomla for many years is not enough to say that no one knows about it. There is a giant message telling you about it everytime you click on the search,

**Comment by korenevskiy** [comment]
@brianteeman You're right. 
But the problem is in the module Manager of a different kind. You cannot use a filter for multiple items or for multiple types .
For example, display only for two types , and only for two categories.

**Comment by korenevskiy** [comment]
or at least use "position:mainmenu position:leftpanel" in the search

**Comment by richard67** [comment]
For readers who are not familiar with Russian language: "Material" and "materials" means "content".

**Comment by Chaosxmk** [comment]
> 
> 
> or at least use "position:mainmenu position:leftpanel" in the search

I don't see much of a usecase for a position or type prefix when there is a dropdown that exists with all possibilities pre-generated already. If anything, maybe allow multi-select for those dropdowns, but even then the usecase is still very limited.

**Comment by korenevskiy** [comment]
> I don't see much of a usecase for a position or type prefix when there is a dropdown that exists with all possibilities pre-generated already. If anything, maybe allow multi-select for those dropdowns, but even then the usecase is still very limited.

In manager modules not filter with multiple several select categorys and positions. Example: (position-1 and position-2) filter.

**Comment by Hackwar** [comment]
As has been written already, the feature already exists. So I'm closing this issue.
