### ISSUE TITLE
Modern Router and List All Categories menu item

### ISSUE THREAD

**Issue by hfittipaldi** [joomla/joomla-cms#28333]
### Steps to reproduce the issue
Router is set to Modern and Remove IDs is set to Yes
Create a category and add some articles, add some subcategory and add some articles too (eg. News / Clippings). Create a menu item type List All Categories selecting the parent category (News).

### Expected result
Valid article url.

### Actual result
Error 404 URL invalid.

### System information (as much as possible)

Setting | Value
-- | --
PHP Built On | Windows NT MAQUINA03 10.0 build 18363 (Windows 10) AMD64
Database Type | mysql
Database Version | 5.7.21
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.9
Web Server | Apache/2.4.33 (Win64) OpenSSL/1.1.0g PHP/7.3.9
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 3.9.16 Stable [ Amani ] 10-March-2020 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

**Comment by Hackwar** [comment]
Can you please provide an example of the URL that is generated?

**Comment by ReLater** [comment]
I can't reproduce this issue with current nightly 3.9.17-dev and also all "sub clicks" are working as expected.

**Comment by ReLater** [comment]
```
Expected result
Valid article url.
```
A menu item type `List All Categories` doesn't display any articles. The question is now: Where do you click an article url there?

**Comment by hfittipaldi** [comment]
> Can you please provide an example of the URL that is generated?

Menu: News > List all categories
Article: https://localhost/www/joomla/news/some-article (error 404)

**Comment by Hackwar** [comment]
I'm sorry, but with the example URL I still don't know what we could do here. As others have already written, there are no article links in a "List all categories" menu item. Right now I would assume that you have a template, which has a layout override and does something crazy there, which is breaking on your site.

**Comment by ghost** [comment]
close?
