### ISSUE TITLE
[4.0] Error when saving users options

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#28349]
### Steps to reproduce the issue
Try to save the options in users.

### Expected result
Saved

### Actual result
An error has occurred. 0 Call to a member function test() on null 

In PHP error log:
PHP Notice:  Undefined variable: rule in /libraries/src/Form/FormField.php on line 1139

**Comment by richard67** [comment]
@wilsonge Possibly coming from recent merge of 3.10-dev up to 4.0-dev? [https://github.com/joomla/joomla-cms/commit/d42f08218b722af05598e727424e88b8c3aa7feb#diff-1a31ec6292bd41ba0bafe545bf8c1262](https://github.com/joomla/joomla-cms/commit/d42f08218b722af05598e727424e88b8c3aa7feb#diff-1a31ec6292bd41ba0bafe545bf8c1262)

**Comment by wilsonge** [comment]
Yup from the 3.9.16 merge conflicts. Fixed with https://github.com/joomla/joomla-cms/commit/602bc238d5bb21c563d8347f65eff5b26a26b823
