### ISSUE TITLE
Displaying category item uses wrong menu item when category is used in two menu items 

### ISSUE THREAD

**Issue by dandpclements** [joomla/joomla-cms#28344]
I am creating a ‘cut down’ version of a website for use on a mobile. It runs as part of the main website.

The main website uses template layout A and the mobile version uses template B. Both sites have their own separate menus.

Both versions need to display articles for a category. The main site has a menu item to display a category blog, the mobile site has a menu item for category list to keep it simple

Using either menu item works ok and the list or blog appears ok with the correct template. The problem occurs when I then select an article from the list to display.

- The main site displays the article ok with the correct template
- The mobile site displays the article, however it uses the main site menu item to display it, so it appears with the template of the main site rather than the mobile site

If I temporarily unpublish the main site menu item then the mobile site displays the article ok using the correct template under the mobile menu item

It seems to me that when an article is selected to be displayed, Joomla uses the category to find the menu item and just uses the first one it finds – in this case the main site one.

The only way I have been able to get round this is to create a second category for the mobile version and put copies of the articles in it. The site then works ok, but it creates a maintenance overhead of having to remember to keep two categories in step.

**Comment by brianteeman** [comment]
> It seems to me that when an article is selected to be displayed, Joomla uses the category to find the menu item and just uses the first one it finds – in this case the main site one.

Yes that's pretty much the way joomla works. Whichever menu item has the lowest itemid will be the one that is used when you access the article

**Comment by brianteeman** [comment]
Closing as its the expected behaviour

**Comment by infograf768** [comment]
The fact that it is a known issue (cat list vs cat blog for the same category) does not make it expected. It is imho a long standing bug that we were unable to solve.
