### ISSUE TITLE
[4.0] Permissions section display issue when window size reduced

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#28347]
### Steps to reproduce the issue
Edit an article. Click on the Permissions tab.
Reduce window size.

When we get to the accordeon display, the unfocused tabs don't get a background-color and are therefore invisible until hover.

![permissions](https://user-images.githubusercontent.com/869724/76700514-9949fd00-66b8-11ea-857e-d35d9ab279f7.gif)

**Comment by brianteeman** [comment]
I have a half finished fix for this. will try to submit it tonight unless someone beats me to it

**Comment by brianteeman** [comment]
the more I look at the scss for joomla-tabs the more I think it needs to be rewritten from scratch

**Comment by brianteeman** [comment]
yes it definitely needs rewriting. the scss is completely wrong with lots of issues with nesting. Probably explains why you see this issue and others with the joomla-tabs

someone better than me at scss will need to recreate it.

**Comment by infograf768** [comment]
@angieradtke 
Could you have a look please

**Comment by angieradtke** [comment]
ok

**Comment by angieradtke** [comment]
https://github.com/angieradtke/joomla-cms/commit/0f8c0f1db1eed51df372950abb617d3abad9affa#diff-ffefd5c001375d6ba19d6cda3fe13a80

**Comment by infograf768** [comment]
@angieradtke 
Looks like working for what concerns joomla-tab.scss
Not sure I understand why you also modify choices.scss and package-lock.json

Can you create a PR?

**Comment by Quy** [comment]
Please test PR #30167
