### ISSUE TITLE
[4.0] Subfields layout  vs 3 column layout

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#28340]
### Steps to reproduce the issue
Generate a filed of type subfields with two or three fields, and at least one other field.
Subfields needs more space than singular fields and destroy the 3 column layout.

 
![screen shot 2020-03-14 at 17 34 33](https://issues.joomla.org/uploads/1/cb7709d6c2dc3c10c99eefa32aab91f6.jpg)

**Comment by Quy** [comment]
Please test PR #29706
