### ISSUE TITLE
Enable Cache breaks the site. J4Issue!

### ISSUE THREAD

**Issue by chetanmadaan** [joomla/joomla-cms#28355]
### Steps to reproduce the issue
Go to Global Config >> Enable Cache
On - Progressive Caching 
Cache Handler File

### Expected result
Cache should work.

### Actual result
Error:

Call stack
--
```
Serialization of 'Closure' is not allowed
# | Function | Location
1 | () | JROOT\libraries\src\Document\HtmlDocument.php:474
2 | serialize() | JROOT\libraries\src\Document\HtmlDocument.php:474
3 | Joomla\CMS\Document\HtmlDocument->getBuffer() | JROOT\libraries\src\Document\HtmlDocument.php:804
4 | Joomla\CMS\Document\HtmlDocument->_renderTemplate() | JROOT\libraries\src\Document\HtmlDocument.php:571
5 | Joomla\CMS\Document\HtmlDocument->render() | JROOT\libraries\src\Application\CMSApplication.php:982
6 | Joomla\CMS\Application\CMSApplication->render() | JROOT\libraries\src\Application\SiteApplication.php:754
7 | Joomla\CMS\Application\SiteApplication->render() | JROOT\libraries\src\Application\CMSApplication.php:247
8 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\includes\app.php:63
9 | require_once() | JROOT\index.php:36
```

![image](https://user-images.githubusercontent.com/3968575/76707335-a967d980-66c4-11ea-9423-445e64e4038b.png)

### System information (as much as possible)
Joomla 4.0.0-alpha12
PHP 7.3.12
### Additional comments

Thanks to @cybersalt for reporting this.

**Comment by ReLater** [comment]
> Joomla 4.0.0-alpha12

Please try with a nightly build! Thank you!
https://developer.joomla.org/nightly-builds.html

**Comment by chetanmadaan** [comment]
Updating Gives an error.
`Error: The 'atum' service key is already registered.: Cannot access protected property Joomla\CMS\Menu\MenuItem::$params`
I'll try to do a fresh install of the nightly build and rest.

**Comment by Quy** [comment]
Duplicate #27598<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28355">issues.joomla.org/tracker/joomla-cms/28355</a>.</sub>

**Comment by chetanmadaan** [comment]
> Duplicate #27598
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/28355](https://issues.joomla.org/tracker/joomla-cms/28355).

The original issue was something else not a duplicate. however, I am yet to test on a nightly build.
