### ISSUE TITLE
[4.0] Notice when TagsPopular module is displayed in frontend (3.9.10 merge)

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#28378]
### Steps to reproduce the issue
Publish a mod_tags_popular in frontend
Since the merge of 3.10-dev into 4.0 we have an error which breaks frontend display

Notice: Array to string conversion in .../modules/mod_tags_popular/src/Helper/TagsPopularHelper.php on line 100
Error: Unknown column 'Array' in 'where clause': Unknown column 'Array' in 'where clause'

Code merged was
```
-			->whereIn($db->quoteName('c.core_access'), $groups)
+			->where('(' . $db->quoteName('c.core_access') . ' IN (' . $groups . ') OR ' . $db->quoteName('c.core_access') . ' = 0)')
```

@wilsonge

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/28379.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28378">issues.joomla.org/tracker/joomla-cms/28378</a>.</sub>
