### ISSUE TITLE
[4.0] [backend-template] Component options sidebar bug

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28374]
### Steps to reproduce the issue

1. Go to `/administrator/index.php?option=com_config&view=component&component=com_content`
2. Reduce viewport width down so everything gets stacked
3. Click the `Toggle Menu` button so the menu is hidden
3. Increase viewport width back to desktop size

### Expected result

Menu is becomes visible

### Actual result

Menu is stilll hidden

![screeny1](https://user-images.githubusercontent.com/2019801/76769705-b227e080-6794-11ea-8838-1827a1aca1b4.gif)

**Comment by jwaisner** [comment]
Confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28374">issues.joomla.org/tracker/joomla-cms/28374</a>.</sub>

**Comment by Quy** [comment]
Please test PR #30132
