### ISSUE TITLE
[4.0] [backend-template] Permission colours on mobile

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28375]
### Steps to reproduce the issue

1. Go to `/administrator/index.php?option=com_config&view=component&component=com_content`
2. Reduce viewoort width down to mobile size
3. Navigate to `Permissions` tab

![screeny2](https://user-images.githubusercontent.com/2019801/76769937-0af77900-6795-11ea-9c40-8002db757c34.gif)

**Comment by Quy** [comment]
Duplicate  #28347

**Comment by C-Lodder** [comment]
oops, sorry
