### ISSUE TITLE
[4] wrong file name "4.0.0-2020-09-03.sql"?

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#28387]
### Steps to reproduce the issue
- See https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-09-03.sql

Shouldn't it be 4.0.0-2020-03-09.sql ??

**Comment by alikon** [comment]
true.... :smile:

**Comment by richard67** [comment]
For posgresql same error. It seems @brianteeman mixed up day and month in the ISO date format in the file names.

**Comment by richard67** [comment]
I suggest we postpone Beta until the file name matches the real date ;-) (joking)

**Comment by brianteeman** [comment]
its a mistake - just create a pr to fix it - doesnt need a big discussion

**Comment by alikon** [comment]
see #28388
