### ISSUE TITLE
[J  4.x] datalist instead of  js chosen

### ISSUE THREAD

**Issue by no-matter-0** [joomla/joomla-cms#28403]
Joomla uses chosen https://harvesthq.github.io/chosen/  to display select boxes in frontend or backend
HTML5 provides now the perfect datalist who does the same thing without the need for  another JS library
It would be nice to natively integrate this datalist

the support is good  https://caniuse.com/#feat=datalist

thanks to all

**Comment by SharkyKZ** [comment]
Datalist is not a suitable replacement for Chosen. It's fine for text fields (already implemented in J3).

In J4 Chosen is already replaced by Choicesjs for multi-select and single-select uses nothing (can use Choicesjs as well if you need its features).

**Comment by no-matter-0** [comment]
I am using J4 beta 1 and I cannot see any advantages on  JS choice over datalist

**Comment by brianteeman** [comment]
J4 is not using chosen it is using choices

in some use cases datalist could be used but not in all the places that joomla uses selects

For reference the requirements are
1. accessible
2. select multiple
3. create new option on the fly

**Comment by Bakual** [comment]
Datalist provide possible options for text field.
It's no replacement for a select list as it doesn't restrict the input to the datalist options as a select field would.
Chosen and choices both work on select lists, not on regular text inputs. So it's something completely different, allthougt looking similar.

**Comment by C-Lodder** [comment]
Datalist and Choices are 2 very different things. The former being extremely limited and rather buggy. They had good intentions implementing this element, but it's not very good at what it does.

**Comment by no-matter-0** [comment]
there is a possibility with js to do a multiple select on datalist (for now)
but it was only a suggestion
thanks to all

**Comment by brianteeman** [comment]
Closed for the reasons stated
