### ISSUE TITLE
Category Custom Fields do not save

### ISSUE THREAD

**Issue by grantg182** [joomla/joomla-cms#28402]
### Steps to reproduce the issue
Created a plugin to add extra field to the Category edit page as I cannot use 'com_fields' Custom Fields for various reasons. Code as below for this. Field renders as expected.

categoryextension.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<form>
    <fields name="params">
        <fieldset name="category-icon" label="Icon">
            <field name="icon" type="text" default="icon-round" label="Category Icon" description="Enter the category icon" size="100" />
        </fieldset>
    </fields>
</form>
```
categoryextension.php
```
<?php
// no direct access
defined('_JEXEC') or die('Restricted access');

class plgContentCategoryExtension extends JPlugin
{

    /**
     * Load the language file on instantiation.
     *
     * @var boolean
     * @since 3.1
     */

    protected $autoloadLanguage = true;

    public function onContentPrepareForm($form, $data)
    {

        $app = JFactory::getApplication();
        $option = $app->input->get('option');
        $view = $app->input->get('view');

        switch ($option) {

            case 'com_categories':

                switch ($view) {

                    case 'category':

                        if ($app->isAdmin()) {

                            JForm::addFormPath(__DIR__ . '/forms');

                            $form->loadFile('categoryextension', false);

                        }

                        return true;
                }

            return true;
        }

        return true;

    }

}
```

### Expected result
Custom field is rendered. Data is saved to the database.

### Actual result
Custom field is rendered. Data is NOT saved to the database.

### System information (as much as possible)
3.9.8

### Additional comments
Here's a very old blog post about this exact issue, in Joomla 2.5 and 3.0, but the code in com_categories edit.php has changed a lot since then.... https://techjoomla.com/developers-blogs/joomla-development/adding-custom-fields-to-joomla-categories-in-joomla-25

**Comment by SharkyKZ** [comment]
Don't use the view to determine which form it is. It will get lost when saving the form. Instead use form name.

```
public function onContentPrepareForm(JForm $form, $data)
{
	if ($form->getName() !== 'com_categories.categorycom_content')
	{
		return;
	}

	JFormHelper::addFormPath(__DIR__ . '/forms');

	$form->loadFile('categoryextension', false);
}
```

**Comment by SharkyKZ** [comment]
Closing as issue is in your code.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28402">issues.joomla.org/tracker/joomla-cms/28402</a>.</sub>
