### ISSUE TITLE
Bug in the backend (strtolower)

### ISSUE THREAD

**Issue by plancked** [joomla/joomla-cms#28408]
Hello,

Joomla 3 uses strtolower function on backend (for example on searching modules) which does not support UTF-8 and search will not work for example in Greek.

We changed that file and it works with the modification.

Thanks
Alex

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/28410.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28408">issues.joomla.org/tracker/joomla-cms/28408</a>.</sub>

**Comment by infograf768** [comment]
@plancked 
what was the exact search you did?
Please post screenshots of the module edited and the search itself.
