### ISSUE TITLE
New article button missing from frontend of category blog layout

### ISSUE THREAD

**Issue by drjjw** [joomla/joomla-cms#28414]
### Steps to reproduce the issue
Create menu item for Category Blog
Login frontend with Super Admin
Access menu item above. 
### Expected result
Button for new article should appear

### Actual result
Button for New Article does not appear
If changing to Category List layout, button appears

### System information (as much as possible)
Joomla! 3.9.16
Protostar template

**Comment by brianteeman** [comment]
Has this ever been there or is this a feature request?

**Comment by infograf768** [comment]
As far as I remember, this has always been the case. 

I could easily add this feature here, and it can also be done via an override.

```
diff --git a/components/com_content/views/category/tmpl/blog.php b/components/com_content/views/category/tmpl/blog.php
index 320fbec..0232a81 100644
--- a/components/com_content/views/category/tmpl/blog.php
+++ b/components/com_content/views/category/tmpl/blog.php
@@ -135,3 +135,8 @@
 			<?php echo $this->pagination->getPagesLinks(); ?> </div>
 	<?php endif; ?>
+
+	<?php // Code to add a link to submit an article. ?>
+	<?php if ($this->category->getParams()->get('access-create')) : ?>
+		<?php echo JHtml::_('icon.create', $this->category, $this->category->params); ?>
+	<?php endif; ?>
 </div>

```

Which gives
<img width="970" alt="Screen Shot 2020-03-21 at 09 43 37" src="https://user-images.githubusercontent.com/869724/77222965-7dcb7000-6b58-11ea-860a-7f160cb06cf3.png">

**Comment by ReLater** [comment]
I made some hasty investigations yesterday down to version 3.7.4. As far as I saw it was never a feature in blog views and I ended with the question: "Is it a bug that it was forgotten in blog views?".  ;-)

**Comment by drjjw** [comment]
OK thanks very much, but before you get too smug about whether this a bug or feature, perhaps acknowledge that it seems rather random that this "feature" would appear only for Category List and not Category Blog. To a user new to Joomla (which I am not), this would certainly seem more bug than feature.

**Comment by alikon** [comment]
i cannot see a reason why it is there for Category List and not for Category Blog
so more a bug than a feature imho
@infograf768 can you do a pr please ?

**Comment by ReLater** [comment]
> but before you get too smug about whether this a bug or feature

Please understand that it's a frustrating waste of time for guys like me to provide a pr and for others to test it if the pr will be refused in the end. Therefore it's better to discuss it and collect input before a production lead decides.

**Comment by drjjw** [comment]
> > but before you get too smug about whether this a bug or feature
> 
> Please understand that it's a frustrating waste of time for guys like me to provide a pr and for others to test it if the pr will be refused in the end. Therefore it's better to discuss it and collect input before a production lead decides.

Understood. But also bear in mind, I go about troubleshooting, creating test sites to reproduce and report. We are encouraged to help...

**Comment by ReLater** [comment]
Just to clarify (doesn't need no more discussion here):

I think you simply misunderstood my comment above ("and I ended with the question: "Is it a bug that it was forgotten in blog views?".  ;-) ")
1) For me the answer is "yes".
2) I don't have to decide that. I'm sometimes a contributer here but 90% of the time a user like you or a "developer" (custom extensions) that has to live with missing or overloaded "features" in J3 .

Perhaps my translator translated "smug" in your comment wrongly. For me it felt disrespectful.

**Comment by infograf768** [comment]
Can make PR. We can, and have lived without it since 1.5, but it does cost much to add it.
Remains to decide if we add it as an override to our core templates or by default.

@HLeithner please advise.

**Comment by HLeithner** [comment]
Is a bug in my opinion. Please create a PR.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/28429
Closing as we have a patch.

**Comment by ghost** [comment]
infograf768 this created issue #28514 aand will be very unpleasant surprise for joomla 3.9.17 users!

 At least make this 2 issues as an option? Couse This will break lyout of many joomla sites if these are not optional So this issue is BC issue.

My personal opinios this New article button in the botom should be removed in joomla 3.9.17

**Comment by HLeithner** [comment]
Lock down see https://github.com/joomla/joomla-cms/issues/28514#issuecomment-605900545
