### ISSUE TITLE
Frontend ContactModelContact displays stack trace when contact not found

### ISSUE THREAD

**Issue by stutteringp0et** [joomla/joomla-cms#2841]
In my implementation, contacts get shuffled around to different categories and they're published and unpublished as well as their access levels changing frequently.

While testing some of my functionality - I ran across a full stack trace in the system message after I changed the access level of a contact.

Line 286 throws Exception, which gives stack trace in the front-end system message.

The error should throw a JException which would give a pretty error message instead of an ugly stack trace.

On top of that, the status code set in the exception isn't carried over to the resulting page - line 301 sets the error, line 302 should set the status code:

JResponse::setHeader('status',$e->getCode());

**Comment by brianteeman** [comment]
After no update this is being closed. If you feel it is still an issue please provide more information and it can always be reopened <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/2841">issues.joomla.org/joomla-cms/2841</a>.</sub>
