### ISSUE TITLE
[4.0] Font should not be italicized

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#28428]
### Steps to reproduce the issue
Install the nightly build.
See font and dropdown in italicized.

### Actual result
![installer](https://user-images.githubusercontent.com/368084/77241242-864d9600-6bac-11ea-9d6e-6715fd9ce0e4.jpg)

![dropdown](https://user-images.githubusercontent.com/368084/77241243-89488680-6bac-11ea-9d6b-349e19c1ad30.jpg)

### System information (as much as possible)
Nightly build

**Comment by infograf768** [comment]
Maybe on Nightly build but not here on -dev clean install.

<img width="754" alt="Screen Shot 2020-03-22 at 09 34 25" src="https://user-images.githubusercontent.com/869724/77245643-648df680-6c20-11ea-9c7e-c21c54d91ae9.png">

**Comment by brianteeman** [comment]
I think I know what is happening. @quy can you inspect the code and see if there is an italic applied to the page - I suspect not.

**Comment by Quy** [comment]
It is also happening on dev branch. No italic tag. It may be my Windows system but I don't know why.

**Comment by Quy** [comment]
Closing for now and investigate and see if others will report this issue.

**Comment by brianteeman** [comment]
Exactly what I suspected. Its a known problem when you use web fonts that I brought up some time ago. If you check the fonts on your system you will see that you have a font with the same name as the web font being used in the installer. However you only have the italic version of the font on your system - hence the result

**Comment by Quy** [comment]
Strange. It has been fine until yesterday. Thanks for the hint.

**Comment by brianteeman** [comment]
I could be wrong
