### ISSUE TITLE
[4.0] After update from 3.10 error message shown once after first login to backend

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#28432]
### Steps to reproduce the issue

1. Install a fresh copy of 3.10 nightly.
2. Go to the Joomla Update Component component config and set the URL to custom (https://update.joomla.org/core/nightlies/next_major_list.xml) and the status to development.
3. Update to Joomla 4.0
4. After files are successfully written and you re-authenticate (with a known issue about incorrect templates warnings when you do this) then you'll get following error shown after the first login to 
backend:
![j4-error-after-update-from-3-10](https://user-images.githubusercontent.com/7413183/77250871-1a6e3a80-6c4b-11ea-986c-4e66528c2aa7.png)

When then navigating through the backend, all is ok. Frontend works, too. The error message never appears again.

### Expected result

No error shown after first login to backend after update from 3.10 to 4.0.

### Actual result

Error shown after first login to backend after update from 3.10 to 4.0, see steps to reproduce.

### System information (as much as possible)

PHP 7.3, MySQL 8, Linux

### Additional comments

The `aministrator/logs/joomla_update.php` shows that all SQL changes have been applied, compared to the update sql files. So it is not caused by any SQL error like it was reported with issue #28385 and solved with PR #28391 .

The changes from PR #28399 are implemented too, and the PHP warning logged in the PHP log which was present before PR #28399 was merged does not appear anymore. But the error shown in the screenshot above is the same as the one handled with PR #28399.

**Comment by richard67** [comment]
Ping @wilsonge .

**Comment by richard67** [comment]
@wilsonge Maybe it needs some additional cache cleaning in between the steps, deleting old plugin and deleting unused files and folders?

**Comment by zero-24** [comment]
Do you have a stack trace? Where this error is coming from?

**Comment by richard67** [comment]
No idea. I have full error log to file on in my PHP settings, but there is no error logged in the log file.

**Comment by richard67** [comment]
But normally this error comes when trying to read XML files but the file is not there.

**Comment by richard67** [comment]
It should have been solved with #28399 , but seems that wasn't enough.

**Comment by zero-24** [comment]
what happens when you enable the debug plugin? Any more info displayed than?

**Comment by richard67** [comment]
@zero-24 Thanks for kicking my ass to the debugger ;-)

```
Call stack
--
# | Function | Location
1 | () | JROOT/libraries/src/Installer/Adapter/PluginAdapter.php:424
2 | Joomla\CMS\Installer\Adapter\PluginAdapter->setupUninstall() | JROOT/libraries/src/Installer/InstallerAdapter.php:1180
3 | Joomla\CMS\Installer\InstallerAdapter->uninstall() | JROOT/libraries/src/Installer/Installer.php:764
4 | Joomla\CMS\Installer\Installer->uninstall() | JROOT/administrator/components/com_admin/script.php:412
5 | JoomlaInstallerScript->uninstallRepeatableFieldsPlugin() | JROOT/administrator/components/com_admin/script.php:96
6 | JoomlaInstallerScript->update() | JROOT/administrator/components/com_joomlaupdate/src/Model/UpdateModel.php:866
7 | Joomla\Component\Joomlaupdate\Administrator\Model\UpdateModel->finaliseUpgrade() | JROOT/administrator/components/com_joomlaupdate/src/Controller/UpdateController.php:180
8 | Joomla\Component\Joomlaupdate\Administrator\Controller\UpdateController->finalise() | JROOT/libraries/src/MVC/Controller/BaseController.php:728
9 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:146
10 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:384
11 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:131
12 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:174
13 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:231
14 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:63
15 | require_once() | JROOT/administrator/index.php:36
```
It seems it fails when uninstalling the repeatable fields plugin.

**Comment by zero-24** [comment]
hmm seams to be something broken in the uninstall of the plugin uninstallRepeatableFieldsPlugin.

**Comment by richard67** [comment]
Yep, am checking, but haven't found the mistake yet ;-)

**Comment by richard67** [comment]
The `$this->group = (string) $this->getManifest()->attributes()->group;` in the PluginAdapter fails. It seems it doesn't find any manifest file.

**Comment by richard67** [comment]
Or it doesn't have a `group` attribute.

**Comment by richard67** [comment]
Maybe order of processing in function `uninstallRepeatableFieldsPlugin()` in file `script.php`is wrong? To me it seems to be ok. Or maybe we should do the `$db->transactionCommit();` there before we run the installer to uninstall the plugin, and not after like it is now?

**Comment by richard67** [comment]
@Hackwar Any idea?

**Comment by zero-24** [comment]
https://github.com/joomla/joomla-cms/blob/staging/plugins/fields/repeatable/repeatable.xml#L2

hmm the xml looks good to me maybe the path used is not the correct one?

**Comment by mbabker** [comment]
Is that function running before or after the plugin was removed from the filesystem?  It doesn’t matter if the manifest looks right or not, if it’s not there then you’re SOL.

**Comment by richard67** [comment]
@mbabker It was changed with PR #28399 to run before the removal from file system. And after the update, the script.php which is there includes that change.

**Comment by wilsonge** [comment]
It's related to this https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_joomlaupdate/restore_finalisation.php#L75

I forgot at the end of restore.php we trash all the files :( That's before we call the usual script methods. Which is unfortunate. Not really sure how best to work around that.

**Comment by richard67** [comment]
@wilsonge At least we have an explanation now. Easy fix: Add it to the readme of the known issues like we have it (hopefully) for the "template style does not exist" message ;-) (joking)

**Comment by richard67** [comment]
@wilsonge Could we exclude the files and folders of that plugin from the delete files routine and the delete folders (and also from the script to generate those lists)? Shouldn't the uninstallation of the plugin remove that stuff already?

**Comment by richard67** [comment]
Alternatively, we could change the function uninstallRepeatableFieldsPlugin in script.php so it doesn't uninstall the plugin anymore using the extensions installer but is deleting database stuff like e.g. the record in the extensions table itself.

**Comment by wilsonge** [comment]
> @wilsonge Could we exclude the files and folders of that plugin from the delete files routine and the delete folders (and also from the script to generate those lists)? Shouldn't the uninstallation of the plugin remove that stuff already?

Yes I think that's the correct thing to do

**Comment by richard67** [comment]
Have just tested with a patched update zip and it works.

**Comment by richard67** [comment]
Patch was change in script.php as shown here: [https://github.com/joomla/joomla-cms/compare/4.0-dev...richard67:4.0-dev-test-issue-28432](https://github.com/joomla/joomla-cms/compare/4.0-dev...richard67:4.0-dev-test-issue-28432)

**Comment by richard67** [comment]
Custom URL for testing: [https://test5.richard-fath.de/next_major_list_issue-28432.xml](https://test5.richard-fath.de/next_major_list_issue-28432.xml).

**Comment by zero-24** [comment]
looks good to me. 👍

**Comment by richard67** [comment]
@zero-24 Problem is it doesn't make sense that I make a PR with that fix. @wilsonge has to change the procedure to generate these lists in script.php instead.

**Comment by wilsonge** [comment]
Make the PR its fine

**Comment by richard67** [comment]
You mean I shall make? Ok, will do so.

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/pull/25559/commits/a342106fcf66f85ecdf7aea7cd3cf25ee983e198 script updated. just do the PR :) saves me from downloading nightlies and doing diff's :)

**Comment by richard67** [comment]
Closing as having PR. Please test #28433 .

**Comment by richard67** [comment]
> [a342106](https://github.com/joomla/joomla-cms/commit/a342106fcf66f85ecdf7aea7cd3cf25ee983e198) script updated. just do the PR :) saves me from downloading nightlies and doing diff's :)

@wilsonge LGTM.
