### ISSUE TITLE
[3.9] Missing constant JLIB_DATABASE_ERROR_VALID_MAIL

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#28438]
### Steps to reproduce the issue

If you enter incorrect data in the e-mail input field during the installation of Joomla 3.9.16, the system will display a warning. However, there is no such constant in language files.

![Screenshot_2](https://user-images.githubusercontent.com/8440661/77306294-22d47d00-6d00-11ea-87ab-d5904eeeb843.png)

It is in the file, for example, **en-GB.lib_joomla**:
`JLIB_DATABASE_ERROR_VALID_MAIL="The email address you entered is invalid. Please enter another email address."`

### System information (as much as possible)

Joomla 3.9.16
PHP 7.3.2

**Comment by infograf768** [comment]
Looks like the string has to be added in the installation ini for en-GB, en-US, en-AU, en-CA, en-NZ and then we should ask TTs to provide new installation ini files

**Comment by infograf768** [comment]
pr https://github.com/joomla/joomla-cms/pull/28440 
closing
