### ISSUE TITLE
[4.0] Change the size of the message popup

### ISSUE THREAD

**Issue by roland-d** [joomla/joomla-cms#28430]
### Steps to reproduce the issue
1. Login to the backend of Joomla 4
2. Go to System
3. Click on Database
4. See the message popup
![image](https://user-images.githubusercontent.com/359377/77246759-a2901800-6c2a-11ea-8aba-ce6d1599ed5d.png)

### Expected result
A rather not so intrusive popup that doesn't cover the search tools

### Actual result
This happens if you have a longer message.

![image](https://user-images.githubusercontent.com/359377/77246739-74aad380-6c2a-11ea-9eac-aa9921e20e7c.png)

### System information (as much as possible)
J4.0

### Additional comments
While I am completely fine with the message popup, I do wonder if we could make this a little more integrated into the design. Now when you have a longer message it will overlap the search tools. Whereas in Joomla 3, it would be inline to the page, as such not overlap any elements.

**Comment by brianteeman** [comment]
I am going to close this. You are absolutely correct but we already have several open issues regarding the complete mess that these alerts are. Some of which even have started to fix the code.
