### ISSUE TITLE
Tags-Only Smart Search (com_finder) Produces No Hits

### ISSUE THREAD

**Issue by cmbr** [joomla/joomla-cms#28442]
# Goal of the Search
Produce search results showing all articles that are classified with certain tags.

# Site Preparation
A. In _Administrator > Components > Smart Search_, I have indexed the site. The indexing completes without error.

B. Then in _Administrator > Components > Smart Search > Search Filters_, I created a published filter for tags only.
B1. In _Search by Author_, all authors are selected.
B2. In _Search by Category_, the relevant categories are selected.
B3. In _Search by Language_, _All_ is selected.
B4. In _Search by Type_, only _Tags_ is selected.
The title of this filter is _Expertise Smart Search - Tags Only_ and its ID is 5.

C. I have created another published Smart Search filter with the title of _General Smart Search_. Its ID is 3. All authors, categories, languages and types are selected.

D. I have created a menu item of type Search in a hidden menu. The link to that menu item contains _option=com_finder_ confirming my selection of a Smart Search. The link `index.php?option=com_finder&view=search&f=5`
D1. For our discussion here, the title of the Menu item is _Expertise Smart Search_ and it has an alias of _expertise-smart-search_. The ID of this menu item is 413.
D2. In the _Details tab > Search Filters_, I have selected _Expertise Smart Search - Tags Only_.

E. I have created another menu item of type Search in the same hidden menu.
E1. The title of this menu item is _General Smart Search_ and it has an alias of _general-smart-search_. The ID of this menu item is 401.
E2. In the _Details tab > Search Filters_, I have selected _General Smart Search_.

F. There is a menu module assigned to the hidden menu and that module is assigned to all pages on the site.

G. I have constructed 67 links to preset (or canned) searches and inserted them into an article that appears on the site. Here's an example:
```
<a title="Search for C2 Single Equation Models" href="/expertise-smart-search?q=&quot;C2+Single+Equation+Models&quot;" target="_self">C2 Single Equation Models</a>
```
The _q_ parameter in that link specifies an exact phrase search.

# Running a Search
When the link for the example above is selected, the Search Results reports:

_Assuming **c2 single equation** is required, and **equation models** is required, the following results were found. No Results Found. No search results could be found for query: "C2 Single Equation Models"._

In the _#__tags database_ table, there are 68 published tags listed. One of them (ID=3) has a title of C2 Single Equation Models. The alias and path for that tag record are both _c2-single-equation-models_.

In the _#__contentitem_tag_map_ database table, there are 74 entries with a tag_id of 3 but in the searches, none are found. The same behavior is seen for the other tags.

The next step I've taken is to analyze the PHP code in my Visual Studio Code debugger. When I try a search from the Website's front end, I trigger an exception at line 133 of _components/com_finder/helpers/route.php_. _Undefined index: q_. The _q_ parameter is null here.

At this point inside the _foreach_ loop opened at line 131, the _$items_ array has two members, both Joomla\CMS\Menu\MenuItems. Joomla has found the two _com_finder_ menu items, IDs 401 and 413. At this first iteration, _$item_ has the ID of 401.

As I single-step through the code, I notice that a query is constructed: `index.php?option=com_finder&view=search&f=3&q="C2 Single Equation Models"&Itemid=401`. This is at line 160 of _libraries/vendor/joomla/uri/src/AbstractUri.php_.

After stepping through the rest of the code, the page renders with the same failure noted above.

Note that a breakpoint set at line 131 of _components/com_finder/helpers/route.php_ is hit only **once** even though there are two elements in the _$items_ array.

Next I unpublished the _General Smart Search_ menu item (ID: 401) and ran another search. Now the _$items_ array has one element as expected but at line 160 of _libraries/vendor/joomla/uri/src/AbstractUri.php_, this is the _$uri_: _index.php?option=com_finder&view=search&f=3&q="C2 Single Equation Models"&Itemid=413_. Note that the filter ID is 3 (_f=3_) which is wrong. The _Expertise Smart Search_ menu item's filter is set to ID=5, the tags-only filter. This search also fails to produce any hits.

What additional tests shall I run to track down this problem?

# Environment
Joomla version 3.9.16
PHP Version 7.3.11
MySQL 8.0.19
In the database, there are 37,520 finder_terms (12.6 MB) and 457
finder_links (3.8 MB).

# Supplemental Information
See the Joomla Forum posting [Tags-Only Smart Search Produces No Hits](https://forum.joomla.org/viewtopic.php?f=715&t=978864)

**Comment by richard67** [comment]
@Hackwar Could you check this? Would be much appreciated. Thanks in advance.

**Comment by cmbr** [comment]
# Additional Observations

I continue to probe the code for clues about the failure of tags-only searches. In my debugging I have noticed some anomalies but couldn't be sure that what I was seeing wasn't due to operator error or some misconfiguration of my debugger.

As a cross-check, I enabled the System Debug in _Administrator > System > Global Configuration > System tab > Debug Settings > Debug System_. Set to _Yes_. _Save_.

Then I ran the same search mentioned above. At the bottom of the _No Results Found_ page in the Joomla! Debug Console section, I opened the Database Queries panel. _47 Queries Logged and 18 duplicate found._

Let's use this query as an example. (For this listing the actual database prefix has been replaced with #_.)
```
SELECT l.link_id,m.weight AS ordering
  FROM `#__finder_links` AS l
  INNER JOIN `#__finder_taxonomy_map` AS t0
  ON t0.link_id = l.link_id
  INNER JOIN `#__finder_taxonomy_map` AS t1
  ON t1.link_id = l.link_id
  INNER JOIN `#__finder_taxonomy_map` AS t2
  ON t2.link_id = l.link_id
  INNER JOIN `#__finder_taxonomy_map` AS t3
  ON t3.link_id = l.link_id
  INNER JOIN `#__finder_links_terms4` AS m
  ON m.link_id = l.link_id
  WHERE l.access IN (1,1)
  AND l.state = 1
  AND l.published = 1
  AND (l.publish_start_date = '0000-00-00 00:00:00' OR l.publish_start_date <= '2020-03-28 01:41:00')
  AND (l.publish_end_date = '0000-00-00 00:00:00' OR l.publish_end_date >= '2020-03-28 01:41:00')
  AND t0.node_id IN (645)
  AND t1.node_id IN (647,669)
  AND t2.node_id IN (649)
  AND t3.node_id IN (653,654,655,656,657,658,660,661,663,664,665,666,667,668,670,671,672,673,674,675)
  AND m.term_id IN (54280)
  ORDER BY m.weight DESC
  LIMIT 1000
```
The Joomla Debugger reports _Rows returned: 0_. In my Visual Studio Code debugger, at line 1720 of _/libraries/joomla/database/driver/mysqli.php_, the _$array_ has 24 elements of type _stdClass_ that are otherwise empty.

If I run the MySQL query above manually in PHPMyAdmin, I receive 24 populated rows with branches of types _Type_, _Author_, _Language_ and _Category_ as expected.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28442">issues.joomla.org/tracker/joomla-cms/28442</a>.</sub>

**Comment by cmbr** [comment]
After running the database query again in PHPMyAdmin, I find that it **also** returns an empty set. The last line of my Additional Observations comment above is wrong. I'll continue to examine the query.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28442">issues.joomla.org/tracker/joomla-cms/28442</a>.</sub>

**Comment by Hackwar** [comment]
So... I think I have a bad information for you: The tags for an article are not indexed. Tags are indexed as seperate entries, but there is no connection to the articles itself.

**Comment by cmbr** [comment]
I have reexamined my database tables in PHPMyAdmin to verify that my original analysis still appears to be valid.

For the particular search in my example above, I specified a tag of _C2 Single Equation Models_. In the #__tags database table, I find that record has an ID of 3 and the published value is 1, checked_out is 0, level is 1, created_time is 2020-02-04 23:31:41, modified_time is 2020-02-04 23:33:27, publish_up is 2020-02-04 23:31:41, publish_down is 2020-02-04 23:31:41. The alias and path for that tag record are both _c2-single-equation-models_.

Next I move to the #__contentitem_tag_map database table. There are 74 entries with a tag_id of 3. All records in that database table have a type_alias of com_content.article. There are various values of core_content_id and content_item_id. The tag_date fields have values before today's date. The type_id for all records is 1.

Take one record of the #__contentitem_tag_map database table. It has a core_content_id of 3 and a content_item_id of 77.

Now I open the #__content database table and search for an ID of 77. In the database record for that article, I see that the state is 1, created is 2012-10-11 13:41:20, checked_out_time is 0000-00-00 00:00:00, publish_up is 2012-10-11 13:41:20, publish_down is 0000-00-00 00:00:00, access is 1.

I open the selected article in the Joomla Administrator article manager and in the right column of the content tab, confirm that the _C2 Single Equation Models_ tag appears in the Tags section. Furthermore I can open the article itself in the front end of the Website.

The Smart Search Indexer runs to completion with no reported errors. The article with an ID of 77 appears in the Smart Search Indexed Content table with a status of Published. In Smart Search Content Maps, the article's category is also Published.

The configuration of the Smart Search Filter for the Tags-Only search remains as stated in section B of the original report above.

Note that the failure of Tags-Only Smart Searches is identical for all 67 searches not just this one tag.

What additional tests shall I run?
What additional connections are required to make the search produce results?

**Comment by Hackwar** [comment]
> B. Then in Administrator > Components > Smart Search > Search Filters, I created a published filter for tags only.
> B1. In Search by Author, all authors are selected.
> B2. In Search by Category, the relevant categories are selected.
> B3. In Search by Language, All is selected.
> B4. In Search by Type, only Tags is selected.
> The title of this filter is Expertise Smart Search - Tags Only and its ID is 5.

Again, I think you are misunderstand something here. If you select something in the filter, that means that a search result has to contain all selected taxonomies. If you select only Tags for Types and then select the whole list of categories, it can't display anything, because tags don't have categories. But your filter says "Display everything that is a tag and has one of these categories."

As I wrote earlier, the index does not contain any information about the tags in connection to other content items. We have a finder plugin for tags, but that adds the tags as an item to search for, like an article or a newsfeed. It does not add the connection between an article and its tags. For that, the article indexing plugin would have to add the tags as taxonomies to the article in the index and that is currently not happening. And it isn't happening, because the tagging system is very difficult to handle right now.

**Comment by cmbr** [comment]
Apparently what I was trying to do is not possible, at least in that old version of Joomla. Perhaps this issue should now be closed.

**Comment by richard67** [comment]
Closing as stated above. Thanks for reporting back.
