### ISSUE TITLE
content history problem with JSON fields

### ISSUE THREAD

**Issue by davidix** [joomla/joomla-cms#28448]
com_contenthistory have problem with displaying JSON fields and it returns "Object of class stdClass could not be converted to string"
and the only way to fix that is to "hideFields"

**Comment by richard67** [comment]
What means JSON fields? Some text field which contains JSON data? Or a database field of json type like it cones with MySQL 8 (but isn't supported in Joomla yet)?

And could you provide other missing details please, especially which Joomla version you use which has that problem, and which PHP version you use.

**Comment by Quy** [comment]
Closing due to no response.
