### ISSUE TITLE
[4.0] [backend-template] Custom select background colour

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28463]
### Steps to reproduce the issue

When attempting to override the custom-select background colour, it's not being applied across the entire element. This is becuase the SVG isn't being used as only an icon, but instead a background for the entire element.

### Expected result

The SVG should **only** consist of the arrow icon, allowing users to change the background colour of the dropdown.

### Screenshot

![screeny1](https://user-images.githubusercontent.com/2019801/77633348-3de4fe00-6f47-11ea-86d4-6494e937e354.png)

**Comment by infograf768** [comment]
+1 Having fought with these svg since the beginning of this template, I would love the idea of getting rid of them and go back to icons indeed.

**Comment by brianteeman** [comment]
you both keep saying this but all it needs is a pull request

**Comment by infograf768** [comment]
I would not know how to do that correctly.

**Comment by Quy** [comment]
@C-Lodder Please advise if PR #28680 is the correct fix. Thanks.

**Comment by C-Lodder** [comment]
@Quy That PR only changes the contrast

**Comment by C-Lodder** [comment]
@brianteeman & template team, are you happy with this?

![screeny](https://user-images.githubusercontent.com/2019801/79963607-8548a680-8481-11ea-8bb2-4bc7985351e6.png)

If so, I'll submit the PR

**Comment by infograf768** [comment]
Except for the purple colour, I like this to get rid of the svg(s)
There are other places to modify though
<img width="355" alt="Screen Shot 2020-04-22 at 11 23 06" src="https://user-images.githubusercontent.com/869724/79964950-b5954280-848b-11ea-9efc-5d898ad7b276.png">

@astridx @ciar4n

**Comment by C-Lodder** [comment]
@infograf768 Ignore the purple colour of the text. That was just me testing the hue settings in the template.

**Comment by astridx** [comment]
@C-Lodder 
Please submit the PR.

**Comment by C-Lodder** [comment]
https://github.com/joomla/joomla-cms/pull/28755
