### ISSUE TITLE
[3.10][4.0] Sessions when upgrading from J3 to J4

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#28465]
### Steps to reproduce the issue
Upgrade from 3.10 to 4. You get kicked out, have to re-authenticate. Also during this process you get a note about invalid templates.

### Issues
1. This re-logging in was a relic from the migration of sessions - it suggests we're moving the session storage around - figure out why
2. Is there a better way of changing the templates around before the session step kicks us out?

**Comment by zero-24** [comment]
I have to un assign me from this issue as I was not been able to find the root cause of the Issue. 

To me it is a release blocker as it breaks the upgrade and could possible break the site on upgrade too when you choose not to login and trigger the last steps of the upgrade.

**Comment by wilsonge** [comment]
Closing in favour of https://github.com/joomla/joomla-cms/pull/31561
