### ISSUE TITLE
Page title param take no effect if article has menu item

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#28468]
### Steps to reproduce the issue

Any article has a special param called 'Page title' allowing to define custom page title.
It works fine when you have a blog category. 
However, if the article has a menu item, the custom value takes no effect.
Yes, there is the same param in menu item settings, but it is empty. 
So, actually this is not the bug, but my proposal is to change the logic and check out - if menu item has no value in the 'Page title' field, but the article settings do, then use such value.

**Comment by chmst** [comment]
I see what you mean. 
In general, the value set in menu params has priority over the settings in the article. In this case the empty value. Otherwise there must be a selection like "use article settings".
But then it must be the same for all params of this type.

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/39249 should address this issue. Please help testing. Thanks !
