### ISSUE TITLE
[4.0] Behaviour plugin

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#28474]
Reminder that the two behaviour plugins have TODO

**Comment by wilsonge** [comment]
To expand: https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/behaviour/taggable/taggable.xml#L21 (which i had totally forgotten about - thankyou!)

**Comment by wilsonge** [comment]
RFC on the todo here https://github.com/joomla/joomla-cms/pull/28492 I suspect we'll just end up removing the TODO though

**Comment by wilsonge** [comment]
Removed with https://github.com/joomla/joomla-cms/commit/063eccccdea89f9655e9f7d262a08016cfdb5536 
https://github.com/joomla/joomla-cms/commit/65633494be7dce810250192ca624888bcd93149b

I'm not going to invest in #28492 at this stage
