### ISSUE TITLE
[3.9] Error in the filter (direction of sorting elements) in the Privacy component

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#28497]
### Steps to reproduce the issue
1. Install Joomla 3.9.16,
2. Activate all the necessary plugins and settings in the Privacy component (System - Privacy Consent, etc.)
3. Create a new user,
4. Log in as a new user in the frontend and accept the Privacy Policy,
5. Go to the control panel: **Users --> Privacy --> Consents**: pay attention to the filter (sorting direction) - 2 lines are added in it that disrupt its operation.

### Expected result
Filter (sort direction) is working correctly.

Until the first agreement appears in the filter (sort direction), there are no "inappropriate" lines.

![__01](https://user-images.githubusercontent.com/8440661/77830714-1488c580-7133-11ea-817e-1eb119427bdb.png)
### Actual result
Filter (sorting direction) is NOT working correctly: 2 lines are added in it that disrupt its operation.

![__02](https://user-images.githubusercontent.com/8440661/77830710-0d61b780-7133-11ea-91b8-8cec44ee2982.png)
### System information (as much as possible)
Joomla 3.9.16
PHP 7.3.2

### Additional comments
The error was confirmed on 2 sites.

Perhaps to reproduce the error you do not need to install a new distribution, try first checking on your working sites.

Thanks.

**Comment by Quy** [comment]
Thanks for the report. Please test PR #28502.
