### ISSUE TITLE
Joomla Category list in Menu Item Type bug

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#28509]
### Steps to reproduce the issue

create Category list in Menu Item Type 

![Uuuntitled](https://user-images.githubusercontent.com/43875462/77847939-64b26700-71c9-11ea-99e0-9775c131e539.png)

no option to disable buton New (create new article) in the bottom

### Expected result

no buton New (create new article) in the bottom

### Actual result

buton New (create new article) in the bottom

### System information (as much as possible)

Joomla 3.9.16 , joomla default 

Protostar template

**Comment by brianteeman** [comment]
This is only visible to people who have permission to create an article

**Comment by richard67** [comment]
And of course only when they are logged in.

**Comment by brianteeman** [comment]
Closed as exepected and desired behaviour

**Comment by ghost** [comment]
this is not expexted and not desired joomla 3.9.16 behavior it joomla bug 

if you have **other place to Submit new article** now you **get 2 places on the same page** to Submit new article

Its very confusing Joomla behavior to people who have permission to create an article

brian please reopen joomla bug issue

**Comment by ReLater** [comment]
The button is there since years. And now you come along and say that it's a bug and want another configuration option in an already overloaded Joomla 3?

Remove the lines in an override: https://github.com/joomla/joomla-cms/blob/3.9.16/components/com_content/views/category/tmpl/default_articles.php#L283-L286

Remove these lines in comming 3.9.17, too: https://github.com/joomla/joomla-cms/blob/staging/components/com_content/views/category/tmpl/blog.php#L138-L141

Or use CSS to hide the button.

**Comment by ghost** [comment]
if The button is there since years means no one fixed this joomla bug for years, that sad.
@ReLater can you fix this bug in 3.9.17 ?

**Comment by brianteeman** [comment]
It is not a bug - it is the intended behaviour

@relater has told you how to customise it for your own site

**Comment by ReLater** [comment]
> can you fix this bug in 3.9.17 ?

Even if I or whoever would provide a pull request it will not accepted and merged  (never ever!). We can be shure of that fact.

**Comment by ghost** [comment]
brianteeman why you claim its intended behavior? there are no documentation of such intended behaviour.

if you have other place to Submit new article now you sudden;y get 2 places on the same page to Submit new article if you have list, but no such thing if you get blog, 

Its very confusing Joomla behavior to users who have permission to create an article

@ReLater  why this joomla bug fix will not be accepted and merged (never ever!) ?

**Comment by infograf768** [comment]
There is no documentation that prevents anyone from displaying 10 times the same module on the same page either...
You are confusing a bug and a feature. Use overrides as explained above https://github.com/joomla/joomla-cms/issues/28509#issuecomment-605634061
I'm now locking this.
