### ISSUE TITLE
[4.0] Undefined property: stdClass::$version

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#28503]
### Steps to reproduce the issue
Install v3.10 nightly build
Upgrade to v4
Go to System > Manage > Extensions

### Actual result
> PHP Notice:  Undefined property: stdClass::$version in \administrator\components\com_installer\tmpl\manage\default.php on line 108

> PHP Notice:  Undefined property: stdClass::$version in \administrator\components\com_installer\tmpl\manage\default.php on line 124

### Additional comments
In `extensions` table, here is the `manifest_cache` value with new installation, but blank with the upgrade.

> {"name":"plg_api-authentication_token","type":"plugin","creationDate":"November 2019","author":"Joomla! Project","copyright":"Copyright (C) 2005 - 2019 Open Source Matters. All rights reserved.","authorEmail":"admin@joomla.org","authorUrl":"www.joomla.org","version":"4.0.0","description":"PLG_API-AUTHENTICATION_TOKEN_XML_DESCRIPTION","group":"","filename":"token"}

**Comment by richard67** [comment]
Maybe this api token authentication is missing in the list of core extensions in the extensions helper? That could be the reason why the manifest cache is not updated on update in script.php.

**Comment by richard67** [comment]
Please test PR #28505 .

**Comment by ReLater** [comment]
I still have this or similiar issue after update from 3.10 nightly to 4.0 where  #28505 is applied already.
for

User - Joomla API Token | Site | Plugin
-- | -- | --

English (en-GB) | API | Language
-- | -- | --

```
Notice: Undefined property: stdClass::$version in /administrator/components/com_installer/tmpl/manage/default.php on line 111

Notice: Undefined property: stdClass::$version in /administrator/components/com_installer/tmpl/manage/default.php on line 127
```

**Comment by richard67** [comment]
@ReLater What means "or similiar issue"?

@Quy Could you check if this issue here is solved and re-open it, if not?

**Comment by ReLater** [comment]
I'll open an new issue.
