### ISSUE TITLE
Request for comment: it is the intended behaviour in joomla or joomla bug?

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#28513]
When user finds joomla bug and other user claims its it is the intended behaviour without explanation or documentation is this usual joomla policy?

for example: bug or intended behavior

![Uuuntitled](https://user-images.githubusercontent.com/43875462/77881771-4ea7b380-7268-11ea-8389-2832b107f85b.png)

Articles in Category list in Menu Item Type

create Category list in Menu Item Type

In fronten joomla user who have permission to create an article get surprised by additional buton New (create new article)

no information you ll get surprised by new button, no option to delete or disable buton New (create new article) in the bottom

Then you use other Menu Item Type no surprise New (create new article) in the bottom appears

if joomla intended behaviour is revealed by surprise and is at leaste confusing is it usual for jooma to let these bugs or intended behavior to stay for years?

**Comment by infograf768** [comment]
Stop this @Milglius or we will have to ban you again from J github!
All was explained to you in https://github.com/joomla/joomla-cms/issues/28509

**Comment by zero-24** [comment]
Hi, can you please share the steps to get that button?

Thanks

**Comment by zero-24** [comment]
Ah seems i missed the other issue.

**Comment by ghost** [comment]
@infograf768 by baning me you hurt joomla even more cose even more users will see that its far better to use wordpress, couse even for asking what is intended behaviour in joomla get you a ban lol

jooma cms rip joomla bug you are now joomla intended behaviour ?

no answers and locked and closed conversation and ban to collaborators this is joomla policy ?

**Comment by HLeithner** [comment]
> no answers and locked and closed conversation and ban to collaborators this is joomla policy ?

You got your answer but you didn't accepted the answer, we can't do more so please stop it our you get banned because you block our resources and that's hurt joomla.

**Comment by rdeutz** [comment]
@Milglius just to let you know, this is the 2nd time that you got blocked and I haven't set an end date. Have a good time.
