### ISSUE TITLE
[3.9.10] update to [4] Strange message "The template for this display is not available"

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#28510]
1) What is that message good for? I saw it twice. I couldn't see any template issues during update and afterwards.
2) If it's good for anything it should be more descriptive. I only was confused.

![29-03-_2020_16-22-42](https://user-images.githubusercontent.com/20780646/77852423-e365cf00-71de-11ea-9733-421266438d51.jpg)

**Comment by wilsonge** [comment]
It's a side effect of how we are migrating to the new template. We do need to figure out a way to stop showing it. @zero-24 is already looking into this one alongside https://github.com/joomla/joomla-cms/issues/28465
