### ISSUE TITLE
New article button appear from frontend of category list layout

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#28514]
New article button present from frontend of category list layout

Steps to reproduce the issue

Create menu item for Category List
Login frontend with Super Admin
Access menu item above.
Expected result

Button for new article should not appear
Actual result

Button for New Article does appear
If changing to Category Blog layout, button not appears
System information (as much as possible)

Joomla! 3.9.16
Protostar template
Additional comments

Category Blog layout, button not appears is used a lot for many years and it is intended joomla behavior for years why to change it in Joomla! 3.9.17 and create a lot of confusion and disapointment for joomla users? At least make this as an option?

**Comment by ghost** [comment]
See the joomla 3.9.17 problems you get here #28513 #28509 #28429 

by closing this you hurt joomla even more cose even more users will see that its far better to use wordpress

no answers and locked and closed conversation and ban to collaborators this is brianteeman joomla policy ?

**Comment by ghost** [comment]
this issue #28414 create issue #28514

**Comment by brianteeman** [comment]
No it doesnt

You have asked how to do something. You have been told how to do it. 

We are not here to rewrite joomla specifically for your needs. 

@infograf768 @alikon over to you to handle this

**Comment by ghost** [comment]
brianteeman strange but you and infograf768 just rewrite joomla specifically for this users needs #28414 and in doing so you abused other joomla users needs

**Comment by alikon** [comment]
@joomla/cms-maintainers please ban @Milglius

**Comment by HLeithner** [comment]
@Milglius you got your answer in 3 tickets by different maintainers all with the same answer. This is not a bug it's a feature you also get work around how to remove. So please stop bugging us. I lock down this and the other 2 PR #28414 and #28429
