### ISSUE TITLE
[4.0] Impossible to save an Email Template in a HTML Format

### ISSUE THREAD

**Issue by blueforce** [joomla/joomla-cms#28524]
### Steps to reproduce the issue
1. Go to System > Email Templates > Options
2. Set the Mailformat to HTML and save and close
3. Create Mail Template for eg. German
4. Switch HTML-Body to «yes» and insert a Text, an image and various formats (H1, H2) usw.
    I used the TinyMCE as default Editor

My Example looks like this
<img width="1730" alt="email-template-3" src="https://user-images.githubusercontent.com/1141234/78045692-8c92fd80-7376-11ea-8bb9-00f03bf19f66.png">
5. Save the content

### Expected result
The content is saved

### Actual result
The content is not saved and the Button from the HTML-Body is set back to «No»

### System information (as much as possible)
PHP 7.2.x
Joomla 4.0 B1 dev Version Nightly Build from 26.03.
Nginx Webserver (localhost) and reproduced with joomla.com online Version

**Comment by Bakual** [comment]
@Hackwar Any idea?

**Comment by ReLater** [comment]
confirmed

**Comment by richard67** [comment]
Please test Pull Request #29229 . It should solve this issue.
