### ISSUE TITLE
Media field inaccessible for medium screens

### ISSUE THREAD

**Issue by Harmageddon** [joomla/joomla-cms#28520]
Original report by user charta at https://forum.joomla.de/thread/11473-bild-f%C3%BCr-offline-modus-l%C3%B6schen/?postID=69518#post69518. Confirmed by me.

### Steps to reproduce the issue
1. Navigate to the Site Configuration.
2. Enable the "Site offline" switch.
3. Set the viewport width to a small size above 767px (for me, in Firefox, the issue shows at below 1000px).
4. Try to access the "Select image" and "Delete image" (X) buttons.

### Expected result
The buttons should be accessible.

### Actual result
The media input doesn't change its width, so the buttons slide underneath the right form column and are no longer clickable.
![screen shot 2020-03-31 at 08 33 05](https://issues.joomla.org/uploads/1/c7d4d564386dc95b6bf872cc936a46ba.png)
This screenshot was taken at 1000px width.

### System information (as much as possible)
Mozilla Firefox 74.0, Manjaro Linux

Happens at Joomla! 3.9.16 and current staging (9a517cadf0).

**Comment by astridx** [comment]
I can not confirm this.
![Screenshot from 2020-03-31 23-44-55](https://user-images.githubusercontent.com/9974686/78078204-02fd2300-73aa-11ea-8e80-570b5df78e14.png)
![Screenshot from 2020-03-31 23-47-12](https://user-images.githubusercontent.com/9974686/78078205-0395b980-73aa-11ea-8fdf-878c1cbf02a0.png)
System Info
php: Linux astrid-TravelMate-5760G 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64
dbserver: mysql
dbversion: 5.7.29-0ubuntu0.18.04.1
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 7.2.29-1+ubuntu18.04.1+deb.sury.org+1
server: Apache/2.4.29 (Ubuntu)
sapi_name: apache2handler
version: Joomla! 3.9.16-dev Development [ Amani ] 27-January-2020 17:50 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0

**Comment by ReLater** [comment]
@astridx 
Try a screen width 768px +.

**Comment by astridx** [comment]
I got it wrong. I can confirm it. The problem begins when it becomes double-columned.
![Screenshot from 2020-04-01 01-01-43](https://user-images.githubusercontent.com/9974686/78082894-655b2100-73b4-11ea-872d-2bbbb512da8e.png)

**Comment by ChristineWk** [comment]
Made it also wrong. Ah, that's the point: "Set the viewport width to a small size above 767px" and  
> Try a screen width 768px +.

![2020-04-01 10_33_30-Window](https://user-images.githubusercontent.com/15275917/78118129-d6c3bf80-7406-11ea-8d9a-8f8871429d8f.png)

**Comment by brianteeman** [comment]
Could someonee add the J3 tag pleas
