### ISSUE TITLE
[4.0] [backend-template] Duplicate success alert when installing sample data

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28531]
### Steps to reproduce the issue

Install any of the same data types (Blog, Multilingual or Testing)

### Expected result

A single alert confirming is has installed successfully.

### Actual result

Duplicate alerts (one of them being hidden)

![screeny](https://user-images.githubusercontent.com/2019801/78119375-3c607d80-7400-11ea-80fb-649646414338.png)

**Comment by Quy** [comment]
Not reproducible.

![28531](https://user-images.githubusercontent.com/368084/78153766-48dcda00-73f0-11ea-93a3-42f55fe32743.png)

**Comment by brianteeman** [comment]
I can not reproduce this either. This was a bug a long time ago. Perhaps your branch was out of date. 

Closing for now - it can always be reopened
