### ISSUE TITLE
[4.0] Version Compare: encoded/decoded 

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#28533]
### Steps to reproduce the issue
Take any article, change something in the text and store.
Then go to version, mark 2 versions and call "compare".

### Expected result
like in Version 3.9, toggling html / plain text is possible
only changed parts are highlighted,

![screen shot 2020-04-01 at 13 51 44](https://issues.joomla.org/uploads/1/e6e52f48ac688ec66a735c4c05f1d7d6.jpg)

### Actual result
no toggling possible,
html code of version1 is compared against encoded version2 is compared against Html encoded content. 

![screen shot 2020-04-01 at 13 46 31](https://issues.joomla.org/uploads/1/cf174dd81f136ddbd37458cbfa4ae9bc.jpg)

**Comment by C-Lodder** [comment]
Replace this line:

https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/com_contenthistory/js/admin-compare-compare.es6.js#L32

with:

```
display.insertAdjacentHTML('afterbegin', fragment.textContent);
```

**Comment by chmst** [comment]
@C-Lodder thank you! Now the difference is shown with html tags 

![compare2](https://user-images.githubusercontent.com/1035262/78156255-d5ae8480-743e-11ea-8ec8-75b7f00a06e9.JPG)

But highlighting of the differnce is missing. Sorry, but js is not my field of experience.

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/28536/
