### ISSUE TITLE
<script> tag in language string

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28535]
### Steps to reproduce the issue

Not sure if Joomla supports this on purpose or not, but will raise it anyway.

If you create the following language string:
```
COM_MYCOMPONENT_STRING="<script>alert('test')</script>"
```

And then call it using:
```
echo Joomla\CMS\Language\Text::_('COM_CONTENTHISTORY_PREVIEW_FIELD');
```

It will display a browser alert on the page.

Is this allowed on purpose?

**Comment by SharkyKZ** [comment]
Yes, HTML is allowed here.

**Comment by C-Lodder** [comment]
@SharkyKZ - HTML yes, but a HTML script tag specifically?

**Comment by solracsf** [comment]
Can you also reproduce it with a language override trough the admin or only by manually editing the language file?

**Comment by C-Lodder** [comment]
@acs-ferreira Haven't tried overriding the string in the admin backend. This test is for editing language file

**Comment by chmst** [comment]
@acs-ferreira : If used in overrides, the script tag is removed

**Comment by SharkyKZ** [comment]
>HTML yes, but a HTML script tag specifically?

Why would it be excluded?

**Comment by C-Lodder** [comment]
To prevent any potential XSS attacks

**Comment by brianteeman** [comment]
This really should have been reported privately to the jsst 

@SniperSister @zero-24

**Comment by SharkyKZ** [comment]
If you're passing user input, you should filter or escape it before doing so. This doesn't belong in Text class.

**Comment by mbabker** [comment]
It should not be considered a security vulnerability that language strings can have any valid HTML structures in them.  Nor should the language API be trying to sanitize HTML before translating text.  That is really a concern of the presentation layer, not the translation layer.
