### ISSUE TITLE
[4.х] Error displaying a line in the action log module

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#28540]
**The problem is described for Joomla 3.x. but it is still relevant for Joomla 4.x.**

The contents of the language constant are not displayed in the control panel in the module of recent user actions:

`PLG_USER_TERMS_LOGGING_CONSENT_TO_TERMS="User <a href='{accountlink}'>{username}</a> consented to the terms and conditions during registration."`
(Plugin: User - Terms and Conditions)

![Screenshot_1](https://user-images.githubusercontent.com/8440661/78189103-1c6da000-747a-11ea-9ac9-93baa1466060.png)

At the same time, in the section Users -> User Actions Log everything is fine. I noticed this behavior only with this constant (at different times).

![Screenshot_2](https://user-images.githubusercontent.com/8440661/78189118-22fc1780-747a-11ea-82ba-05fbdcaae0e4.png)

Please correct. Thanks.

### System information (as much as possible)
Joomla 3.9.16
PHP 7.3.2

**Comment by ReLater** [comment]
This is already reported but was never solved:
https://github.com/joomla/joomla-cms/issues/22267
https://github.com/joomla/joomla-cms/issues/22951

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/187063863-bb4f893c-9292-40d4-ad5e-f0a17256dd5b.png)

Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

This is still an issue in Joomla 4. Please can the title and label be updated

cc @zero-24

**Comment by alikon** [comment]
please test #42562
