### ISSUE TITLE
[4.0] restful curl result {"errors":[{"title":"Forbidden"}]}

### ISSUE THREAD

**Issue by fuscage** [joomla/joomla-cms#28544]
### Steps to reproduce the issue
install joomla 4 
enable plugin API Authentication - Basic Auth
and try to get something with curl (https://docs.joomla.org/J4.x:Joomla_Core_APIs)

open msdos
curl -X GET https://{dnsname}/j4/api/index.php/v1/banners --user user_name:password

### Expected result
json with the list of elements (banners, articles, ...)

### Actual result
{"errors":[{"title":"Forbidden"}]}

### System information (as much as possible)
joomla 4 alpha 12

**Comment by Quy** [comment]
Alpha 12 is very outdated. Please test with the nightly build. https://developer.joomla.org/nightly-builds.html

**Comment by fuscage** [comment]
thanks, it's better with the last version

**Comment by studio16** [comment]
Sameissue  with  ‎4.0.0-beta6-dev.

**Comment by studio16** [comment]
both basic and bearer authentication  give all  {"errors":[{"title":"Forbidden"}]} 
Tried it with postman and  with a php curl file
