### ISSUE TITLE
[4.0] Override Manager - ReferenceError: JsDiff is not defined

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#28548]
### Steps to reproduce the issue
1. Open Template Manager and create an override
2. Change some text in the override file
3. Activate the diff view
![Templates  Customise  Cassiopeia      test     Administration  (1)](https://user-images.githubusercontent.com/9974686/78334063-5e3a3b80-758b-11ea-8462-b1c36da8331b.png)

### Expected result

See the Diff View. like explained here: https://docs.joomla.org/J4.x:Improved_Override_Management

### Actual result
You see the error "ReferenceError: JsDiff is not defined"
![Templates  Customise  Cassiopeia      test     Administration  ](https://user-images.githubusercontent.com/9974686/78333947-19aea000-758b-11ea-9239-46d120be586e.png)

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/28550
