### ISSUE TITLE
[4.0] Script/Style hash validation broken

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#28557]
### Steps to reproduce the issue
@SharkyKZ found the reason here: https://github.com/joomla/joomla-cms/pull/26505#issuecomment-544125325

> Since #25357 rendered scripts/styles have formatting added to them. But the hash is generated from scripts/styles without formatting. So the hashes don't match scripts/styles that appear on the page.
>
> Assuming SRI works on pages with MIME type other than text/html, this was actually broken since the beginning because we wrap code in CDATA on such pages: https://github.com/joomla/joomla-cms/blob/56d8a357c2a54656fea36ac7e2ec9f20a715c425/libraries/src/Document/Renderer/Html/HeadRenderer.php#L231

### Expected result
CSP Script hashes work

### Actual result
They don't

**Comment by zero-24** [comment]
Ok found the real reason for this. It has nothing todo with the CDATA stuff but with the $tab and $lnEnd stuff. I'm working on a patch

**Comment by zero-24** [comment]
Please see: https://github.com/joomla/joomla-cms/pull/28719

**Comment by zero-24** [comment]
Just for a note 

> Assuming SRI works on pages with MIME type other than text/html, this was actually broken since the beginning because we wrap code in CDATA on such pages:

We only run CSP on HTML pages so this CDATA stuff was not the reason.
