### ISSUE TITLE
Applying patch in issue tracker on J4 Nightly build causes Error

### ISSUE THREAD

**Issue by softforge** [joomla/joomla-cms#28568]
### Steps to reproduce the issue

Went to apply patch (27601) to do the second test as Nicola had just successfully applied patch and tested successfully. 
But for me the patch failed to apply with the message 
Error
The patch could not be applied because it would break the site. Check the pull request to see if it is up to date

I had just fetched all as had Nicola so for him the patch applied (I was watching his screen in the PBF without P)
I went to do second test when this happened

### Expected result
Patch installs

### Actual result
Patch failed with 
Error
The patch could not be applied because it would break the site. Check the pull request to see if it is up to date![screen shot 2020-04-04 at 10 27 52](https://issues.joomla.org/uploads/1/68efaf0b4017db5dcf38a127402204a0.png)

### System information (as much as possible)
Install the latest nightly 
Joomla_4.0.0-beta1-dev-Development-Full_Package.zip
Add the J4 patch tester 
Patch Tester 4.0.0 Release Candidate
GitHub Repo set to Joomla!CMS
Github Auth Method Token
PHP Version	7.3.16
Web Server	Apache
WebServer to PHP Interface	fpm-fcgi
10.1.44-MariaDB

**Comment by alikon** [comment]
closing as has been reported on the proper github repo https://github.com/joomla-extensions/patchtester/issues/262
