### ISSUE TITLE
[4.0] Frontend: TinyMCE bar display broken

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#28564]
### Steps to reproduce the issue
Edit an article in frontend
Edit an article in backend

### Backend

<img width="511" alt="Screen Shot 2020-04-04 at 09 44 00" src="https://user-images.githubusercontent.com/869724/78421611-4f21bf00-7659-11ea-8392-be510ec3bb12.png">

### Frontend

<img width="600" alt="Screen Shot 2020-04-04 at 09 44 12" src="https://user-images.githubusercontent.com/869724/78421600-3d401c00-7659-11ea-8536-918da01f7641.png">

**Comment by brianteeman** [comment]
There is an issue for this already

**Comment by infograf768** [comment]
`#` ?

**Comment by brianteeman** [comment]
#26944

**Comment by infograf768** [comment]
Closing as duplicate
