### ISSUE TITLE
Notification count on "Warnings" does not decreases after opening the message.

### ISSUE THREAD

**Issue by aishwaryab2** [joomla/joomla-cms#28569]
### Steps to reproduce the issue
1. go to System Dashboard->information->Warnings

### Expected result
1. the count should get decrease after viewing the message.

### Actual result
1. the count remains as it is so its difficult to understand that the message is read or not yet
![notification](https://user-images.githubusercontent.com/58217142/78425031-5794ec80-768f-11ea-943e-f86aa6c3f9c1.png)

**Comment by brianteeman** [comment]
No this is correct. The warning should not go away until the problem is resolved

**Comment by alikon** [comment]
count will decrease if you fix it
closing as expected behaviour
