### ISSUE TITLE
[4.0] user token

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#28567]
### Steps to reproduce the issue
Enable the user joomla token plugin
Enable api authentication plugin
Enable registration on the front end

Register a new user

### Expected result
Joomla token information is not displayed as the default for the token is for superadministrators and the default for new registrations is registered

### Actual result
Token information is displayed
![image](https://user-images.githubusercontent.com/1296369/78422429-17b21300-7657-11ea-92d1-5fa8d065aa69.png)

It makes no sense to display this on the registration page at all

**Comment by wilsonge** [comment]
Marked as release blocker

**Comment by alikon** [comment]
please test #28584<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28567">issues.joomla.org/tracker/joomla-cms/28567</a>.</sub>
