### ISSUE TITLE
[4.0] email validation

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#28570]
Email address validation takes place both on input by the browser and on submit by our code.

The problem is that there has been a change in our validation code for J4 that does not match the browser validation.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email
> A single properly-formed e-mail address. This doesn't necessarily mean the e-mail address exists, but it is at least formatted correctly. In simple terms, this means username@domain or username@domain.tld. 

So if I enter into an email field in user management the browser will respond 
brian     This value is not valid
brian@example     "no error message"
brian@example.com    "no error message"

However the regex has changed (#19300 I think) and brian@example is rejected on submission

@wilsonge this is a summary of what I mentioned

**Comment by brianteeman** [comment]
For the record I dont see why we have any extra code at all doing additional validation - there is no need

**Comment by Quy** [comment]
Is #27948 related/duplicate?

**Comment by wilsonge** [comment]
Yes

**Comment by brianteeman** [comment]
Related. Same root cause thinking we can validate emails better than browsers

**Comment by brianteeman** [comment]
~The simple and correct method is to simply remove the js. It doesn't add anything at all and just causes issues~

**Comment by brianteeman** [comment]
I am closing this as it turns out NOT to be anything to do with the email validation code but instead is the same as #27948  and is related to phpmailer
