### ISSUE TITLE
[4.0] There is no "field.calendar" asset of a "style" type in the registry.

### ISSUE THREAD

**Issue by xillibit** [joomla/joomla-cms#28582]
### Steps to reproduce the issue

In backend, goes under administrator module, then choose new and select "Quick icons" 

### Expected result

It expected no error on the right

### Actual result

There is an error displayed on the right : 

"There is no "field.calendar" asset of a "style" type in the registry."

![image](https://user-images.githubusercontent.com/876395/78501881-30f1b700-775e-11ea-98cf-59194e8c7e81.png)

### System information (as much as possible)

Joomla! 4.0 with last changes from git, Php 7.3.16, MySQL 5.7.26

**Comment by brianteeman** [comment]
confirmed

**Comment by Fedik** [comment]
please run `npm install`

**Comment by xillibit** [comment]
> 
> 
> please run `npm install`

Yes it fix the issue
