### ISSUE TITLE
[4.0][Atum][RTL] Redundant `.menu-*` classes

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#28586]
The following selectors are only declared in the RTL template CSS which makes me think this is now redundant?...

https://github.com/joomla/joomla-cms/blob/6442e32c10f3b72173402d68d52e4c1834099db0/administrator/templates/atum/scss/template-rtl.scss#L69-L82

**Comment by infograf768** [comment]
Indeed, I don't even see it loaded
We now use that class
```
.sidebar-wrapper .sidebar-toggle a
```

**Comment by ciar4n** [comment]
PR created... #28589
