### ISSUE TITLE
[3.9] Invalid title (tooltip) in the search field for overriding constants

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#28590]
### Steps to reproduce the issue
Go to **Extensions -> Languages -> Overrides**. Pay attention to the hint in the search field: `Search in title`. This is not a good hint because the search works by a language constant or text.

![Screenshot_3](https://user-images.githubusercontent.com/8440661/78572153-c446ed00-782f-11ea-8f3d-f0e49572f3f8.png)

By the way, in the localization file en-GB.com_languages.ini there is a constant:

`COM_LANGUAGES_VIEW_OVERRIDES_FILTER_SEARCH_DESC="Search constant or text."`

Need to fix it. Thanks.
### System information (as much as possible)
Joomla 3.9.16
7.3.2

### Additional comments
Not necessary.

**Comment by Quy** [comment]
Please test PR #28598. Thanks.
