### ISSUE TITLE
JFolder: :folder: Path is not a folder

### ISSUE THREAD

**Issue by humblehumanbeing** [joomla/joomla-cms#28593]
### Steps to reproduce the issue
Create a test site under main site: /home/mysite/public_html/testsite
Create a SYMLINK of the directory images of mysite under /home/mysite/public_html/testsite. That is /home/mysite/public_html/testsite/images is not an actual directory and will point to /home/mysite/public_html/images.
Go to mysite/testsite/administrator
Go to Content/Media

### Expected result
Images under /home/mysite/public_html/testsite/images should appear

### Actual result
You will have 'Warning JFolder: :folder: Path is not a folder. Path: /home/mysite/public_html/testsite/images
You cannot use images to add to your articles/categories etc.

### System information (as much as possible)
Joomla 3.9.16
PHP 7x

**Comment by Quy** [comment]
Please test PR ##28393 to see if it will fix your issue. Thanks.

**Comment by humblehumanbeing** [comment]
I have made changes to /home/mysite/public_html/testsite/libraries/joomla/form/fields/folderlist.php but nothing has changed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28593">issues.joomla.org/tracker/joomla-cms/28593</a>.</sub>

**Comment by humblehumanbeing** [comment]
Without changing folderlist.php as suggested I changed both 'Path to Files Folder' and 'Path to Images Folder' in media/options to ../images and it worked.
I can now see the files/folder under symlinked images folder.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28593">issues.joomla.org/tracker/joomla-cms/28593</a>.</sub>

**Comment by infograf768** [comment]
Closing as issue is solved.
