### ISSUE TITLE
[4.0] wrong css for module position

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#28591]
### Steps to reproduce the issue
log in admin side
choose Site modules/Administrator  module
select a couple of them
click on Action  and select Batch
look at the Set Position

### Expected result
clean view module positions

### Actual result

![Screenshot from 2020-04-06 18-23-15](https://user-images.githubusercontent.com/181681/78581547-4c2ef600-7834-11ea-869a-48910e674649.png)

**Comment by Quy** [comment]
Duplicate #23451 but at a different location.

**Comment by alikon** [comment]
let me close it in favour of #23451    anyway we will have a reference
