### ISSUE TITLE
Options for placing hCaptcha as a replacement for reCaptcha

### ISSUE THREAD

**Issue by mhajder** [joomla/joomla-cms#28613]
### Is your feature request related to a problem? Please describe.
On the [CloudFlare blog](https://blog.cloudflare.com/moving-from-recaptcha-to-hcaptcha/), an article appeared yesterday, from which we can learn that they abandoned reCaptcha in favor of hCaptcha. This is because apparently Google plans to change reCaptcha billing to paid.

> Earlier this year, Google informed us that they were going to begin charging for reCAPTCHA.
https://blog.cloudflare.com/moving-from-recaptcha-to-hcaptcha/

**Is this a good time to give the Joomla user the opportunity to choose?**

As you know, Google does not connect with privacy is the first advantage of hCaptch. Secondly, hCaptcha has more options for captcha settings. As the last one can add that hCaptcha pays users who place it on their pages for captcha solutions.

### Describe the solution you'd like
I can create a plugin but why? We need to show users that maybe it's time for a change. That's why it's best to convert these reCaptcha plugins (in Joomla Core) into hCaptcha. The cool thing is that hCaptcha has the same API as reCaptcha so it will only be a few minutes of work.

### Additional context
Of course, I do not mean removing the possibility of placing reCaptcha. I just want to add a second official option to embed another captcha.

hCaptcha Configuration: https://docs.hcaptcha.com/configuration

**We can't make it happen the same as with Google Maps!**

**Comment by alikon** [comment]
much more a work for an 3dp extension i guess than core

**Comment by ReLater** [comment]
Hm, I personally would be happy if it would become a core plugin and to move away from Google whereever possible. The linked blog post above has some good arguments against Google reCaptcha (if they are true). For example:

> We also had issues in some regions, such as China, where Google's services are intermittently blocked.

BUT: I have no idea yet  if hcaptcha is a reliable alternative, who and what hcaptcha.com is and so on.

Just a general statement.

**Comment by brianteeman** [comment]
You have a valid point about google recaptcha but there is nothing to indicate that it would be any better with hcaptcha

**Comment by mhajder** [comment]
> You have a valid point about google recaptcha but there is nothing to indicate that it would be any better with hcaptcha

But it is better. hCaptcha gives us the ability to choose which pictures will be displayed to the user. Let's say that we have a website for children and parents, it is better to display animals for them than any other pictures. We have several options to choose from.
![image](https://user-images.githubusercontent.com/6783135/79055270-05823700-7c4c-11ea-8289-0be1cea85c36.png)
And here we choose:
![image](https://user-images.githubusercontent.com/6783135/79055276-10d56280-7c4c-11ea-828a-de2d454a6f4f.png)

As we know, captcha solving trains google artificial intelligence for free. For this hCaptcha pays us for it: https://medium.com/@hCaptcha/how-hcaptcha-calculates-rewards-1195e6f18284

And last but not least, Google is changing the policy for reCaptcha. 
**Soon we will have to pay for using it!**

**Comment by brianteeman** [comment]
I dont see the need for this in the core but if you want to create a plugin for this for review then it can be considered.

**Comment by mhajder** [comment]
> I dont see the need for this in the core but if you want to create a plugin for this for review then it can be considered.

I also currently do not see the need, but as Google actually makes you pay for reCaptcha as for the Google Maps API, introducing an alternative to Joomla Core is a good idea.

**Comment by pe7er** [comment]
After I read about Cloudflare moving from reCAPTCHA to hCaptcha, I wrote a small hCaptcha plugin for Joomla 3.9: https://github.com/pe7er/hCaptcha

Shall I submit a PR for it to Joomla 4?

**Comment by ReLater** [comment]
> Shall I submit a PR for it to Joomla 4?

I would like it. Tested with the master.zip of your repository (because release does not install in Joomla 3.9). The configuration on hcaptcha.com is easy and intuitive even for several domains. And it technically worked well in a Joomla contact form.

**Comment by pe7er** [comment]
For Joomla 3.9 I have an installable package. The link is available in the description of https://github.com/pe7er/hCaptcha

@ReLater Did you get my 3.9 code to work in Joomla 4?

I've been working on a PR for Joomla 4 but I could not get it to work.
However the default Google reCaptcha in Joomla 4 seems broken too.
I've created an issue for that: https://github.com/joomla/joomla-cms/issues/28758
When reCaptcha works, I will submit my hCaptcha PR to Joomla 4.

**Comment by ReLater** [comment]
> Did you get my 3.9 code to work in Joomla 4?

No, because I didn't test that.

> For Joomla 3.9 I have an installable package. The link is available in the description

I don't read descriptions if there's a release tabulator ;-) But I used the wrong file "plg_captcha_hCaptcha-1.0.0" (whatever it is).
I've tested with the master.zip only to see if the whole procedure, e.g. creating a sitekey, is less annoying than weird Google API GUI hell. It is.

**Comment by mhajder** [comment]
> I've tested with the master.zip only to see if the whole procedure, e.g. creating a sitekey, is less annoying than weird Google API GUI hell. It is.

Yes. hCaptcha offers greater configuration options and easier key acquisition.

**Comment by ReLater** [comment]
> hCaptcha offers greater configuration

From my side the thumb up is primarily for the intuitive registration and configuration surface. For users. Not for "developer nerds" ;-)

**Comment by mhajder** [comment]
> > hCaptcha offers greater configuration
> 
> From my side the thumb up is primarily for the intuitive registration and configuration surface. For users. Not for "developer nerds" ;-)

It is worth adding that it is also another possibility for monetizing our website.

**Comment by J-Wick4** [comment]
Google is intrusive and evil, it should be deleted where ever possible. hCaptcha is amazing, make this happen.

**Comment by alikon** [comment]
please test #28798

**Comment by pe7er** [comment]
I've created a PR to add hCaptcha functionality to Joomla 4: https://github.com/joomla/joomla-cms/pull/28798

Note that you'll need this PR https://github.com/joomla/joomla-cms/pull/28785 that solves an issue with the Captcha's in Joomla 4, to get hCaptcha to work.
