### ISSUE TITLE
[3.9] com_fields image (media) not working and 504 Gateway Time-out

### ISSUE THREAD

**Issue by walturbo** [joomla/joomla-cms#28616]
### Steps to reproduce the issue
I create a new additional field.
I choose image (media)

![com_fields-1](https://user-images.githubusercontent.com/4063964/78882918-128b0480-7a59-11ea-9b7e-7b1ea70bb3cd.jpg)

### Expected result
No error.

### Actual result
After a long time 504 Gateway Time-out.

### System information
Server OSLinux
PHP 7.2.26
MySQLi 5.7.28-31-log
Chrome 80.0 or Firefox 75.0

**Comment by HLeithner** [comment]
without an error log from the server it's hard to say anything. Does the field type matter?

**Comment by Quy** [comment]
Closing due to no response/additional information.
