### ISSUE TITLE
[3.9] Discover install error: Call to a member function children() on null

### ISSUE THREAD

**Issue by pinta83** [joomla/joomla-cms#28617]
### Steps to reproduce the issue
When i try to Discover install an extension (plugin), i get an error "Call to a member function children() on null", and the extension does not get installed.

### Expected result
An installed discovered extension

### Actual result
Error: Call to a member function children() on null

### System information (as much as possible)
Joomla 3.9.16

### Additional comments
I've just ran into this in Joomla 3.9.16, haven't had any problem with previous versions (last tried with J! 3.9.11 which worked as expected).
Taking the plugin out of the folder, and creating a zip installation - Installs as expected.
A JCE plugin

**Comment by SharkyKZ** [comment]
Enable debug, reproduce the error again and post stack trace here please.

**Comment by pinta83** [comment]
Wird.... I've tried multiple times again, and I did not get any errors.... Must have been something on my local environment :)

**Comment by gersteba** [comment]
> Enable debug, reproduce the error again and post stack trace here please.

Joomla!3.10.5

Discovered extension:
![discovered](https://user-images.githubusercontent.com/12512224/153181477-b0631d22-e185-4f83-8cb3-bb262e20d952.jpg)

Stack trace on trying to install that extension:
![stack trace](https://user-images.githubusercontent.com/12512224/153181442-851acc2c-d002-4451-acb6-3a59c69036fb.jpg)

Is that of help to fix that issue?
