### ISSUE TITLE
[4.0] Refactor web asset registration on error pages

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#28623]
### Steps to reproduce the issue
We need to have a think about how to deal with web assets on the error pages. For example in #28614 we have an issue with an early exception being thrown in `onAfterInitialise`).  In this case we haven't loaded the registry file in the `AdministratorApplication`! 

https://github.com/joomla/joomla-cms/pull/28581/files#diff-de2cf03053c95fda1cc845b63abf324dL64

cc @Fedik

**Comment by Fedik** [comment]
> We need to have a think about how to deal with web assets on the error pages

The error page is a `ErrorDocument` , in the end instance of `Document`, which should load WebAsset already, every time new `ErrorDocument`/`Document` instance are made
https://github.com/joomla/joomla-cms/blob/96bff98513c34ecca8f0b94faa214e60dde5be04/libraries/src/Document/Document.php#L332-L341

This will pull the AssetRegistry from Container, which already load all required assets:
https://github.com/joomla/joomla-cms/blob/96bff98513c34ecca8f0b94faa214e60dde5be04/libraries/src/Service/Provider/WebAssetRegistry.php#L38-L48

**Comment by Fedik** [comment]
hm, issue I see is that Registry does not load an asset file for active template,
that normally happen at Dispatch:
https://github.com/joomla/joomla-cms/blob/96bff98513c34ecca8f0b94faa214e60dde5be04/libraries/src/Application/SiteApplication.php#L170-L175

What I can think, is to load registry file in the error.php explicitly:
```php
$wa->getRegistry()->addRegistryFile('templates/blablatemplate/joomla.asset.json');
```
That may help to avoid such problem, what do you think?
It does not have performance issue, because file will be parsed only once and flagged as parsed in registry instance.

I also had in mind a helper methods, like:
```php
// For template
$wa->getRegistry()->addTemplateFile('blabla-name', 'site');

// For component
$wa->getRegistry()->addComponentFile('blabla-name');

```

**Comment by Fedik** [comment]
or, do it in `ErrorDocument::render()`, that maybe more nice
https://github.com/joomla/joomla-cms/blob/ad0b43ea80da7a45c5a3d9d80cd0f04a07437438/libraries/src/Document/ErrorDocument.php#L100-L110

**Comment by wilsonge** [comment]
> That may help to avoid such problem, what do you think?
> It does not have performance issue, because file will be parsed only once and flagged as parsed in registry instance.

I thought about that but I couldn't actually see any code preventing it from being parsed a second time actually

**Comment by Fedik** [comment]
> but I couldn't actually see any code preventing it from being parsed a second time

ups, that actually a bug :smile: 
it must be here:
 https://github.com/joomla/joomla-cms/blob/ad0b43ea80da7a45c5a3d9d80cd0f04a07437438/libraries/src/WebAsset/WebAssetRegistry.php#L223-L229

but I see it missed check for `if (!empty($this->dataFilesParsed[$path]))`, 
I will prepare a pull request, maybe at the weekend

**Comment by Fedik** [comment]
fun thing, the issue was already fixed in past, but because the path was hardcoded for the "site" it does not work for administrator

https://github.com/joomla/joomla-cms/blob/96bff98513c34ecca8f0b94faa214e60dde5be04/libraries/src/Error/Renderer/HtmlRenderer.php#L52-L55

I have made pull #28636

**Comment by wilsonge** [comment]
ahh oops :) closing for the PR
