### ISSUE TITLE
[3.9] Batch processing: you can delete all groups from the user

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#28621]
I am not sure if this is a mistake. Perhaps so conceived, but ...

### Steps to reproduce the issue
1. Go to Users, select one or more users who are members of ONE (same) group and accept Batch processing.
2. In batch processing, select the same group, then the DELETE FROM GROUP item and click Run.

![Screenshot_2](https://user-images.githubusercontent.com/8440661/78980808-58ae9980-7b27-11ea-9799-a21cabc807ab.png)

As you can see, now the user is not in the group. But, for example, when creating a new user, Joomla does not allow him to be saved unless we establish some kind of group (at least 1).

![Screenshot_3](https://user-images.githubusercontent.com/8440661/78980858-6fed8700-7b27-11ea-9a9f-60e35c411927.png)

Logging into the site for obvious reasons is also prohibited.

![Screenshot_4](https://user-images.githubusercontent.com/8440661/78980977-9ca19e80-7b27-11ea-807b-25d18d66ca1b.png)

### Expected result

Perhaps it makes sense to prevent the user from deleting the last group during batch processing? In my humble opinion, a user without a group has no value and, perhaps, no sense.

Thanks for any info.

### System information (as much as possible)
Joomla 3.9.16
PHP 7.3.2

**Comment by brianteeman** [comment]
You are correct - you should not be able to remove all user groups

**Comment by ReLater** [comment]
I see no harm if they are deleted all. Better than deleting a group for this but not for that user in a large batch process.

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

As a pull request has been created for j4 (#38596 ) this issue will now been closed.

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24

**Comment by HLeithner** [comment]
@brianteeman can you please stop this posts if you didn't checked if this issue is still valid!
@alikon if you close anything please check if it should really be closed.

**Comment by brianteeman** [comment]
@HLeithner How about you actually read what is written and not what you think has been written before ranting!!!

# As a pull request has been created for j4 (https://github.com/joomla/joomla-cms/pull/38596 ) this issue will now been closed.

**Comment by HLeithner** [comment]
Maybe will do next time.
