### ISSUE TITLE
[4.0] Featured Article not shown in Frontend

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#28628]
In the German Forum, we have a post: https://forum.joomla.de/thread/11561-cassiopeia-und-hauptbeitr%C3%A4ge/?postID=70156#post70156

Featured Article is not shown in Featured Blog

### Steps to reproduce the issue
Write an article, set is published and featured.
Make a Featured blog.

### Expected result
The article is visible

### Actual result
The article is not visible in the featured blog, but in a normal categoy blog

### System information (as much as possible)
4.0 nightly build or newest clone. 

### Additional comments

The problem is only for new articles, not for sample data articles,

**Comment by richard67** [comment]
@chmst As you told me elsewhere, the problem is that no record is created in the `#__content_frontpage` table when a new article is created with featued=Yes, is that right?

**Comment by chmst** [comment]
It is what I found out - the table #__content_frontend is empty after storing and article with featured = yes - therefore not found via the query. 

Please not that this does not appear with sample data. They have entries in #__content_frontpage

**Comment by brianteeman** [comment]
Dont forget the sample data is written directly to the db so they are not good examples

**Comment by chmst** [comment]
Yes. It is a hint that people can reproduce the error only with new articles.

**Comment by brianteeman** [comment]
I found that if you make an article featured in the item view then it does not work but if you make the article featured by toggling the icon in the list view then it does

**Comment by richard67** [comment]
That's useful info. Then it should be almost clear where to search.

**Comment by richard67** [comment]
@brianteeman How is it with selecting a few items and using the action button?

**Comment by brianteeman** [comment]
Batch works. therefore the problem is in the item model and not the itemS model

**Comment by richard67** [comment]
Yep.

**Comment by richard67** [comment]
@chmst But the featured flag is saved with the new article in the content table? Or is that also lost?

If it is saved, then the mistake might happen somwehere in this function: https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_content/src/Model/ArticleModel.php#L1094

**Comment by richard67** [comment]
Haven't found the mistake yet. Can be tricky.

**Comment by richard67** [comment]
Maybe it fails already here so that the function isn't called at all?

https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_content/src/Model/ArticleModel.php#L1026-L1034

**Comment by chmst** [comment]
The problem is here:https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_content/src/Model/ArticleModel.php#L1189

As @richard67 said already, the prepared statements with empty date are the problem. If dates are entered, the #__content_frontpage record ist stored and all is comme  il faut

**Comment by richard67** [comment]
Then it can be that it broken with #27970 , because when I had done that null date stuff it wasn't prepared statements yet, and I am 100% sure we had tested this case at the end and it has worked.

=> @SharkyKZ Any idea? Maybe binding the null values for the datetimes doesn't work? Or maybe that array bind?

Problem is: Meanwhile I found time to reproduce the error, and I could see nothing in the error log of the database server or in PHP error log. So it is not really an SQL syntax error, such I would see.

**Comment by SharkyKZ** [comment]
Dates, when not set, are empty strings but should be `null` when running the query.

**Comment by brianteeman** [comment]
If only we had tests

**Comment by richard67** [comment]
F...ck, they are of data type sting ... they are not null as they should be. @SharkyKZ  is right.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/28632.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28628">issues.joomla.org/tracker/joomla-cms/28628</a>.</sub>
