### ISSUE TITLE
[4.0] Undefined property: stdClass::$version Part 2

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#28624]
### Steps to reproduce the issue
- Update 3.10 nightly to joomla 4.0
- Set error reporting to "Maximum".
- Go to extensions manager.
- See 2 entries

User - Joomla API Token | Site | Plugin
-- | -- | --

English (en-GB) | API | Language
-- | -- | --

#### Notice in column `Version`:
```
Notice: Undefined property: stdClass::$version in /administrator/components/com_installer/tmpl/manage/default.php on line 111

Notice: Undefined property: stdClass::$version in /administrator/components/com_installer/tmpl/manage/default.php on line 127
```

**Comment by ReLater** [comment]
I updated with custom package update server from https://github.com/joomla/joomla-cms/pull/28563

To confirm or not:
Issue should be tested with 4.0 update package (custom update server) from here: https://developer.joomla.org/nightly-builds.html

**Comment by richard67** [comment]
@ReLater I have found it, more stuff is missing in the extensions helper. Will make PR soon. Stay tuned.

**Comment by richard67** [comment]
Please test PR #28625

**Comment by richard67** [comment]
Closing as having PR #28625 .
