### ISSUE TITLE
[4.0] Wrong default Preset for Admin menu after clean install

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#28620]
### Steps to reproduce the issue
Make a clean install of j4-dev

Edit Admin Menu (Administrator Menu module)
### Expected result
The Preset displayed in the `Choose Preset` field should be `Preset - Joomla Main Menu`
But it is `Preset - Content Dashboard`, although it is indeed the `Joomla Main Menu` which is used.
If one does not care and just modify something else than the Preset and save, one loses the admin menu in back-end...

### Actual result
<img width="928" alt="Screen Shot 2020-04-10 at 10 26 53" src="https://user-images.githubusercontent.com/869724/78976824-462c6400-7b17-11ea-8fae-4c46789fff5f.png">

As the sql to create this administrator mod_menu does not specify the Preset in the params
`(0, 'mod_menu', 'module', 'mod_menu', '', 1, 1, 1, 0, 1, '', '', 0, NULL, 0, 0),`
My guess is that the field displays the default alpha ordered Preset which is `Content Dashboard`

Any idea?

**Comment by richard67** [comment]
Maybe it is set in script.php but not in the right way? Or maybe it should be set in script.php?

**Comment by infograf768** [comment]
It is important though that the default be used only once and not modified after each J4 upgrade.

**Comment by infograf768** [comment]
@richard67 
I found a solution by adding a default to the field.
```
				<field
					name="preset"
					type="menuPreset"
					default="default"  // Added
					label="MOD_MENU_FIELD_PRESET_LABEL"
					description="MOD_MENU_FIELD_PRESET_DESC"
					showon="menutype:*"
				/>
```
which gives
<img width="1023" alt="Screen Shot 2020-04-11 at 11 29 03" src="https://user-images.githubusercontent.com/869724/79040276-b3a7c580-7be7-11ea-9561-e0bb09e276ee.png">

What do you think?

**Comment by richard67** [comment]
Looks good.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/28640
closing as we have patch
