### ISSUE TITLE
[4.0] [backend-template] TopBar - backgroud More Elements

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#28639]
### Steps to reproduce the issue

Set display at iPad size.
Open 3 dots menù (More Elements) in the top right corner

### Expected result

Icons are on dark backgroud

### Actual result

![immagine](https://user-images.githubusercontent.com/906604/79040565-ae4b7a80-7be9-11ea-9f17-99956c5700b9.png)

**Comment by Razzo1987** [comment]
Or set icons dark same as mobile:

![immagine](https://user-images.githubusercontent.com/906604/79040753-13ec3680-7beb-11ea-9765-4e32e7791685.png)

**Comment by brianteeman** [comment]
Closed please test #28652
