### ISSUE TITLE
[4.0][Choices] 'Press to select' text on dropdown

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#28648]
Is the 'Press to select' text really required on the choices dropdown?

- It is stating the obvious
- No other dropdown has such text
- Pretty sure it is non translateable
- Reduces the space available for dropdown items, often forcing dropdown items to wrap

![image](https://user-images.githubusercontent.com/2803503/79043454-2cfae480-7bf7-11ea-873c-4996d4ef69bc.png)

**Comment by Quy** [comment]
Related #28196

**Comment by ciar4n** [comment]
PR created.. #28658
