### ISSUE TITLE
Protostar CSS: Last button "Versions" missing top left and bottom left radius

### ISSUE THREAD

**Issue by gerryfrancis** [joomla/joomla-cms#28659]
### Steps to reproduce the issue
Choose "Protostar" as the frontend template for your site.
Load your site frontend and log in as an editor.
Edit any article to load the article editor.
Take a look at the group of buttons "Save", "Cancel", and "Versions".

### Expected result
![grafik](https://user-images.githubusercontent.com/51095533/79056083-f0f56d00-7c52-11ea-8351-fd363306c484.png)
The button radius is equal to each other.

### Actual result
![grafik](https://user-images.githubusercontent.com/51095533/79056089-fc489880-7c52-11ea-9935-a6e82d199a65.png)
The button radius is not equal to each other.

### System information (as much as possible)
Joomla! 3.9.16.
PHP 7.2.

### Additional comments
From English to German:
"Save" -> "Speichern".
"Cancel" -> "Abbrechen".
"Versions" -> "Versionen".

**Comment by jwaisner** [comment]
Confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28659">issues.joomla.org/tracker/joomla-cms/28659</a>.</sub>

**Comment by gerryfrancis** [comment]
Unfortunately I have no coding skills, but I have recognized that each of these buttons has its own `div.btn-group` in Protostar, which is different to the Isis backend.

All three buttons in one `div.btn-group` would look like this:

![grafik](https://user-images.githubusercontent.com/51095533/79382400-bb5ac780-7f63-11ea-89bf-768dedaa17b3.png)

(Note: I changed `.btn-group > .btn + .btn` to `.btn-group > .btn` in "template.css" to have `margin-left: -1px;` for the last button as well.)

Pressing "Versions" opens a modal showing such a toolbar, in case someone would like to compare.

If I only knew how and where to modify JS to access `div.btn-group div#versionsModal`...

**Comment by infograf768** [comment]
In fact, it could be done via a bootstrap override in ~cassiopea~ **protostar** template.less
```
// Need .dropdown-toggle since :last-child doesn't apply given a .dropdown-menu immediately after it
.btn-group > .btn:last-child,
.btn-group > .dropdown-toggle {
  .border-top-right-radius(@baseBorderRadius);
  .border-bottom-right-radius(@baseBorderRadius);
  .border-top-left-radius(@baseBorderRadius);
  .border-bottom-left-radius(@baseBorderRadius);
}
```
just before 
`@import "template_rtl.less"; // Specific for rtl. Always load last.`

then running generatecss.php to get
<img width="361" alt="Screen Shot 2020-04-16 at 08 38 26" src="https://user-images.githubusercontent.com/869724/79422726-af035880-7fbd-11ea-8c05-66dfb502ad8d.png">

But it should be tested all over to know if unwanted consequences

**Comment by gerryfrancis** [comment]
@infograf768 Thank you for your hint. Do you think this will work for Protostar, too?

**Comment by infograf768** [comment]
sorry this was for protostar...
(Cassiopea in J4 does not use less files, but scss)
I correct post above

**Comment by gerryfrancis** [comment]
@infograf768 Never mind.

I guess I better wait for a fix that may be included in one of the next minor updates. Unfortunately I do not have access to the PHP console, and it is not that important, anyway. If someone likes to work on this, I will be very pleased of course. :)

**Comment by brianteeman** [comment]
Please test #31776

**Comment by gerryfrancis** [comment]
Thanks a lot, folks! What a nice Christmas present! :+1:
