### ISSUE TITLE
[4.0] [backend-template] Messaging

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#28651]
### Steps to reproduce the issue

Create more then 1 user who have access to back-end
Go to: Users > Messaging

### Expected result
Only 1 items:
![immagine](https://user-images.githubusercontent.com/906604/79045901-fa101b00-7c0d-11ea-875f-e203b0fd9de0.png)

### Actual result

2 items:
![immagine](https://user-images.githubusercontent.com/906604/79045823-840bb400-7c0d-11ea-92a4-806e00aec572.png)

**Comment by brianteeman** [comment]
Closed please test #28653
