### ISSUE TITLE
[4.0] postinstall untranslated text languages

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#28654]
### Steps to reproduce the issue
update from j3.10 (multilingual) to j4 
check the postinstall dropdown 

### Expected result
all string are translated

### Actual result

![Screenshot from 2020-04-11 18-02-13](https://user-images.githubusercontent.com/181681/79048677-0e104880-7c1f-11ea-8613-421c442abe69.png)

**Comment by richard67** [comment]
Confirmed. The messages have been deleted in new J4 installations but there was obviously nothing done for deleting them on updated systems from that drop down.

**Comment by brianteeman** [comment]
post installation messages are completely fubar as I have stated before and was marked as a release blocker but no one has looked at it https://github.com/joomla/joomla-cms/issues/26109

**Comment by richard67** [comment]
@brianteeman Thanks, I knew there was some old issue and I was already searching. You saved me a lot of time.

Is this here a duplicate then? If so, we can close it of course. Im this case it could help to attach the above screenshot to the other issue so readers looking for their issue would seen the screenshot and see "Oh, it is already an issue there for it".

**Comment by alikon** [comment]
closing as it is a duplicate of #26109
sorry
