### ISSUE TITLE
[4.0] Fix spacing of Check Icons on Home Dashboard

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28665]
### What needs to be fixed

<img width="525" alt="grafik" src="https://user-images.githubusercontent.com/828371/79065437-94c13600-7cb0-11ea-818d-0923e6e8d73b.png">

The spacing of the text in privacy requests is bit to low, all the spacings should be equal and also the icon positioning should be matching.

Thank you!

**Comment by brianteeman** [comment]
Whoever works on this please remember that  changing the actual text to fit is not a solution as it will be different in every language

**Comment by adj9** [comment]
With Joomla! 4 beta-1 installed on 9th April, the spacings are like this.

<img width="475" alt="Schermata 2020-04-12 alle 13 23 35" src="https://user-images.githubusercontent.com/5918444/79067645-2e90df00-7cc1-11ea-8749-d6c2ee8f4ec4.png">


By varying the size of the browser, the block size varies.
I use safari 13.0.5.

**Comment by coolcat-creations** [comment]
@adj9 at 13" screen using firefox the result is like described in the initial issue.
In your screen there is a second template issue, the 3rd party icons should render with the same width like the core icons and also vertically aligned.

**Comment by ReLater** [comment]
Sacrilegious comment: Why must these boxes have the same heights in any circumstance? If an information is longer it's more important one can read it instead of any esthetic quality.

#### Current behavior:

![12-04-_2020_14-22-09](https://user-images.githubusercontent.com/20780646/79068731-5edc7b80-7cc9-11ea-9ad2-b1533f3d28df.jpg)

#### OK:

![12-04-_2020_14-21-34](https://user-images.githubusercontent.com/20780646/79068750-7582d280-7cc9-11ea-904c-717e87837750.jpg)

**Comment by coolcat-creations** [comment]
While your second example is still bit odd because the text does not use as much space as it could it's better than before. Not quite sure if the different height are solveable in css, an still keeping it dynamic. 
In your example the Kunena Icon is also to small in comparsion to the core icons. 

Also I don't know if "Update Checks" is the right headline here. Are Privacy Requests really "Updates" ?

**Comment by chmst** [comment]
Please test #28668 for the padding.

I agree that the name of the box could be "urgent notification" or someting similar, but this is question to a native speaker. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28665">issues.joomla.org/tracker/joomla-cms/28665</a>.</sub>

**Comment by ReLater** [comment]
> While your second example is still bit odd because the text does not use as much space 

I added `<br>` in the text just to demonstrate what happens if you have more than 3 lines.

**Comment by ReLater** [comment]
> Not quite sure if the different height are solveable in css

It is. Otherwise I couldn't demonstrate it above. I changed the CSS in browser inspector. Therefore it should be also possible in SCSS/CSS files.

**Comment by chmst** [comment]
@ReLater I've made a PR #28668 - would nice to get a test? 

@coolcat-creations could you open an own issue for the name of the box? I fully agree with this but these are two different topics<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28665">issues.joomla.org/tracker/joomla-cms/28665</a>.</sub>

**Comment by chmst** [comment]
Closed as we have a PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28665">issues.joomla.org/tracker/joomla-cms/28665</a>.</sub>

**Comment by coolcat-creations** [comment]
@adj9 Where did you find the akeeba Version to install on J4 ? I want to test the  patch with 3rd party too. Thank you

**Comment by brianteeman** [comment]
akeebabackup.com
