### ISSUE TITLE
[4.0] Associations Toolbar button broken for menu item and category

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#28662]
### Steps to reproduce the issue
Create a multilingual site with multilingual sample data module.
Edit a menu item. (same for a category)
Click on the Associations Toolbar button.
<img width="1094" alt="Screen Shot 2020-04-12 at 09 20 53" src="https://user-images.githubusercontent.com/869724/79064012-95a09a80-7ca5-11ea-895d-90cc643b91ed.png">

### Expected result
It should load the item in the side to side Reference in com_associations.

### Actual result
It only saves the item and redirects to the menu items manager.

### Note
Same result for category.
Works fine for article and contact

**Comment by alikon** [comment]
confirmed

**Comment by Hackwar** [comment]
The models of the components don't call the parent save() method of their base class and thus don't trigger the associations code. In general I don't see why they can't use their parents save() method, but comparing the code does take some time.

**Comment by richard67** [comment]
@Hackwar Are you on it regarding comparing code?

**Comment by infograf768** [comment]
What I wonder is « What has changed as it was working before? »

**Comment by richard67** [comment]
When was it working last time? Days ago? Or weeks? Or months?

**Comment by infograf768** [comment]
Good question...

**Comment by infograf768** [comment]
Tested alpha12 and it works fine. 
4.0-dev from 26 nov 2019 is also OK

4.0-dev from january 2020 is also fine

I do not have more recent packages

**Comment by infograf768** [comment]
@wilsonge 
This was broken when you merged 3.9.10 into 4.0 in March
The code was
https://github.com/joomla/joomla-cms/pull/28314
and
https://github.com/joomla/joomla-cms/pull/27941

**Comment by richard67** [comment]
Do I get it right that the categories problem will be fixed with #28675 for staging and then after release of 3.9.17 be merged up into 3.10-dev and finally to 4.0-dev, and so only the menu items problem remains to be fixed in 4.0-dev?

**Comment by brianteeman** [comment]
In theory yes

**Comment by richard67** [comment]
So who can care for the remaining menu item issue?

**Comment by infograf768** [comment]
there is no men u item issue in staging. only category.

**Comment by richard67** [comment]
I mean in 4.0-dev.

**Comment by infograf768** [comment]
When 3.9.17 is merged in 3.10 and 3.10 in 4.0, all this should be solved, I guess

**Comment by richard67** [comment]
Ah, ok.

**Comment by richard67** [comment]
Closing as solved with PR #29010 . I have just tested it.

@infograf768 Feel free to re-open if you can't confirm this.
