### ISSUE TITLE
[4.0] Change Title of "Update Checks"

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28669]
### What needs to be fixed
The "Update Checks" area shows also Notifications from 3rd Party Plugins and incoming requests from the privacy suite. Therefore "Update checks" seems to be a wrong title for this area.
Since I am not a native speaker I don't know what could be better. 
Maybe just "Notifications" ? or "Notifications and Updates" ?
<img width="528" alt="grafik" src="https://user-images.githubusercontent.com/828371/79073335-4464cb00-7ce6-11ea-9a09-77c06220dce3.png">

It would be also interesting to know if the post installation messages could not go into here instead of beeing that prominent in the upper toolbar.

thank you

**Comment by richard67** [comment]
I thought about using "Update checks and other useful notifications regularly ignored by the site admins so that they run into trouble later", but my feeling is that this could be too long ;-)

**Comment by richard67** [comment]
How about "Quick Info"?

**Comment by chmst** [comment]
@richard67 Quick info can be everything, your first text is better.

I even could imagine that the text changes - if anything is to do, make a fat red warning "action required", if nothing is to do make a text like "Your system in well maintained". 
This is a js callenge and I cannot do it but what do you think?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28669">issues.joomla.org/tracker/joomla-cms/28669</a>.</sub>

**Comment by richard67** [comment]
Quick icons can be used by 3rd party extensions for ... anything. It doesn’t need to be related to system health or required actions. Then only thing they all will have in common is .... giving quick info about something. That’s why I suggested that.

**Comment by ghost** [comment]
`Checks`

**Comment by Quy** [comment]
Please test PR #31733
