### ISSUE TITLE
[4.0] WebAuthn library needs updating to v3

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#28661]
### Steps to reproduce the issue
Upgrade in composer. Use migration docs here https://webauthn-doc.spomky-labs.com/migration/from-v2.x-to-v3.0

### Expected result
v3

### Actual result
v2

### System information (as much as possible)
n/a

### Additional comments
None

**Comment by brianteeman** [comment]
Should this still be done?

**Comment by wilsonge** [comment]
Ideally but it’s a large piece of work :( I mean it’s not a stable blocker. We’ll probably have to do it as a minor release and give a large amount of notice

**Comment by brianteeman** [comment]
This can be closed as j5 is now on 4.3.0
