### ISSUE TITLE
[4.0] Color harmony Toolbar color vs. Primary Color

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28663]
### What needs to be fixed
The primary color looks very nice and fresh, but the toolbar color does not harmony with it anymore.

The initial theme should have a better color harmony.

Now it's:
<img width="290" alt="grafik" src="https://user-images.githubusercontent.com/828371/79064746-e0bdac00-7cab-11ea-8b79-b6d3a176de03.png">

Since the Main Menu was switched to light theme like in one my first drafts (I like this very much), 
the hue change setting seems to be obsololete now? 

Can someone lead me to the discussion about the color scheme change?
The topbar needs now either more saturation to be harmonic or less saturation and more darkness for the initial theme...

**Comment by brianteeman** [comment]
Closed as there is a PR
