### ISSUE TITLE
[4.0] RFC - Sample Data install on Home Dashboard

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28672]
### What needs to be fixed
Just a question: Sample Data is most likely to be used only once and only shortly after Installing Joomla. Is the Home Dashboard really the place to have it constantly there?
In favor of a better overview and usability I would rather see it on the system or content dashboard? What do you all think?
<img width="561" alt="grafik" src="https://user-images.githubusercontent.com/828371/79074251-a4aa3b80-7ceb-11ea-83ac-6737005a7605.png">

**Comment by wilsonge** [comment]
Whilst I agree I'm slightly concerned about the multilang sample install as that enables the language filter plugins etc and I don't want to make that part too hidden. However I also agree it being available on the dashboard after it being used makes little sense

**Comment by richard67** [comment]
The thing is that on a multilingual site you can use the blog sample data multiple times, one time for each language. So to hide Blog Sample Data after having been used once would not be good.

**Comment by coolcat-creations** [comment]
how about placing two buttons below to let the user decide  "ask me later" or "no thanks" and thenn hide the module after being used or after the decision

**Comment by richard67** [comment]
So or so, when moving around I would pefer the system dashboard. The content dashboard is too hidden in my opinion. But that's just my personal taste.

**Comment by brianteeman** [comment]
there is already a pr for only displaying multilingual sample data on a multilingual site

**Comment by richard67** [comment]
Hmm, the system dashboard is so full already, better not move it to there.

**Comment by richard67** [comment]
@brianteeman I guess you meant PR #20749 , right?

**Comment by infograf768** [comment]
Please, please... Sample data install not being any more possible during J installation, they have to be available in a very obvious way, and that is in the first CPanel dashboard.
As for #20749 I have already commented on it.
Hiding stuff is not the right way to help users. J is not only for integrators...

**Comment by alikon** [comment]
simple disable the relative plugins if you don't want those in the dashboard
plus the relative sample data admin module

**Comment by coolcat-creations** [comment]
Maybe it would be good to have a simple / advanced switch in the installation process ? Is that a idea to suit all target groups?

**Comment by brianteeman** [comment]
Not really a solution as anyone using a hosting companies installer will never see that

**Comment by coolcat-creations** [comment]
@brianteeman good point. Then maybe a one-click hide button would be nice.

**Comment by brianteeman** [comment]
That already exists - see animation below
![mods](https://user-images.githubusercontent.com/1296369/79118527-10d97d80-7d86-11ea-8403-177fa06ff4f3.gif)

**Comment by coolcat-creations** [comment]
@brianteeman - Yes I meant a one-click solution to make it as easy as possible. But that's fair enough.

**Comment by alikon** [comment]
so can we close this one ?

**Comment by Bakual** [comment]
Since the sample data module can also be used by 3rd parties, hiding it isn't the best way as you wouldn't see sample data installation for your newly installed component.
A better solution would be to have that unpublish function also for each sample data (plugin) listed in that module. Then one could just easily hide the multilingual and blog sampe data while the module would still be able to display newly added sample data plugins.

**Comment by brianteeman** [comment]
A recent PR has now implemented the suggestion from @bakual so I guess this can be closed

**Comment by richard67** [comment]
Closing as fixed by #33168 and #33169 . Feel free to re-open if this is a mistake.
