### ISSUE TITLE
Notices and unexpected languages abbreviations in Sample Data 

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#28677]
### Steps to reproduce the issue

1. Create multilingual site using sample data.

![Joomla  Web Installer(2)](https://user-images.githubusercontent.com/9974686/79124049-cbc04600-7d9b-11ea-9ef5-db325c3a3153.png)

~2. Open `Content | Articles` and see that there is an `XX` in column associations for abbreviation the French language.~

3. Open Component Mulitlingual Associations and select Categories and language English. See that there are notices.
![Associations multilingues  Articles  gt  Catégories    test   Administration](https://user-images.githubusercontent.com/9974686/79124302-4e490580-7d9c-11ea-9629-21aa54082dfb.png)

**Comment by Quy** [comment]
Is this really an issue in J4 per your title?

**Comment by infograf768** [comment]
1. the screenshot shows we are in 3.x
2. the test english sample data is not multilingual. In fact you are installing 2 sample datas at install time.

3. Also, it looks like you may have done a second install after already tried one and installing languages. In that case, please verify you have a content language created for french.
The multilingual status module may be of help too to understand the situation.

**Comment by astridx** [comment]
> Is this really an issue in J4 per your title?

Sorry. No it is  a J3 issue. I corrected the title.

**Comment by astridx** [comment]
>    @infograf768  2. the test english sample data is not multilingual. In fact you are installing 2 sample datas at install time.

OK. You mean that I should not install the English sample data in the case, that I want to create a multilingual site, right?

**Comment by astridx** [comment]
>   @infograf768   3\. Also, it looks like you may have done a second install after already tried one and installing languages. In that case, please verify you have a content language created for french.
>         The multilingual status module may be of help too to understand the situation.

No, I did not a second install after already tried one. I deleted the configuration.php an configured everything while installation.

**Comment by astridx** [comment]
I just made a new installation and I did not install the sample data. 
The notices from point 3 are still there.

**Comment by richard67** [comment]
@astridx I can't reproduce on current staging. I've done a new installation and chose no sample data as clearly advised in the installation:
![j3-multilingual-no-sample-data](https://user-images.githubusercontent.com/7413183/79138812-6f6a2000-7db5-11ea-87b9-3e81bfbb5f11.png)

At the end of the basic installation I have chosen to install languages and have installed French.

Then at the last page I have selected to activate the multilanguage feature, install localized data and enable the language code plugin, and I have selected French as default language for admin and site, all as shown on your screenshot in the description.

Finally I've logged in to backend, set error reporting to maximun and enabled debugging, then I've opened the associations component, selected categories and English and all was as expected. No notices, neither on the page nor in my PHP error log.

**Comment by infograf768** [comment]
> No, I did not a second install after already tried one. I deleted the configuration.php an configured everything while installation.

That is exactly what I meant. The content language was not created for French as the languages were present already in their folders. We have just solved this « issue » in J4.

Basically, you can’t in J3 only delete configuration.php if the languages were already present in their folders. You also have to delete these lang.

**Comment by astridx** [comment]
Thanks all. Now I understand. I deleted the languages manually, made a new installation and I do not see this error anymore. Sorry for the confusion.
