### ISSUE TITLE
[4.0] System menu under Global Configuration

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#28674]
### Steps to reproduce the issue
Upgrade from v3.10 to J4 nightly build.
Go to Global Configuration.
Scroll to the bottom.

### Actual result

![global-config](https://user-images.githubusercontent.com/368084/79077185-69404a80-7cb4-11ea-82f0-08319e8520db.png)

**Comment by richard67** [comment]
Can confirm it with current 3.10-dev updating to latest nightly 4.0-dev build.

**Comment by wilsonge** [comment]
Added release blocker tag

**Comment by Quy** [comment]
This is due to the `Admin Submenu` module.

**Comment by chmst** [comment]
DELETE FROM `#__modules` WHERE `id` = 13
DELETE FROM `#__assets` WHERE `id` = 47 

would delete the old entry but maybe depends on the previous joomla versions.




<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28674">issues.joomla.org/tracker/joomla-cms/28674</a>.</sub>

**Comment by richard67** [comment]
Yes, IDs might be different depending on the update history.

**Comment by Quy** [comment]
`Admin Submenu` which is not in J4 is the same as `System Dashboard`. How about deleting it based on position `submenu` and respective `asset_id`?

**Comment by chmst** [comment]
Could a user have own modules on position submenu in older Joomla installations? 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28674">issues.joomla.org/tracker/joomla-cms/28674</a>.</sub>

**Comment by chmst** [comment]
I'd prefer to delete this < div: 
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_config/tmpl/application/default.php#L39

I cannot imagine that it makes sense to render modules in the sidebar.

**Comment by brianteeman** [comment]
@chmst wasnt this where integrators could out their own information - like on the login page?

**Comment by chmst** [comment]
Yes. This is position sidebar. in the login page.
We are speking here of the sidebar in the componente com_config.

**Comment by brianteeman** [comment]
Yes I realise that but wouldnt an integrator also want to put their information there as well

**Comment by brianteeman** [comment]
Of course you could simply rename the position in j4

**Comment by chmst** [comment]
If we keep both positions, we must rename one of them. But does it make sense to have a position here in the component sidebar?

![sidebar](https://user-images.githubusercontent.com/1035262/79539347-74192780-8086-11ea-823d-15cc16d920f2.JPG)

In J3 the sidebar was the left panel, this was a better place for additional module.

In any case: the sidebar module from 3.9 may not appear in the submenu of con_config. 
We could: 
delete any module sidebar from j3 database during migration and / or 
remove the whole position from the com_config sidebar  or
rename the position in com_config sidebar in j4

**Comment by brianteeman** [comment]
oops i must have been tired last night I thought this was the area below the mainmenu. sorry

you're right there is no sense in having a module there

**Comment by chmst** [comment]
I've made a PR so that the module is not rederen on com_config.

This does not solve that the old module remains in the database after migration. So pleas do not close this issue until we have a decision for this.

**Comment by brianteeman** [comment]
> I've made a PR so that the module is not reder on com_config.

Thanks

> This does not solve that the old module remains in the database after migration. So pleas do not close this issue until we have a decision for this.

That would be just the same as when you change site templates with different position names

**Comment by richard67** [comment]
> `Admin Submenu` which is not in J4 is the same as `System Dashboard`. How about deleting it based on position `submenu` and respective `asset_id`?

I'll have a look tomorrow if there is a way.

On installations with a longer update history we might not really know the ID's of these modules, and for the asset ID it's the same.

We have to find a combination of columns, maybe with a join of columns from another table, so that we are able to identify the records to be deleted in a WHERE clause in an update sql script safe enough to make sure it doesn't cause collateral damage on any other modules people might have in whatever template's position. I am not 100 % sure yet if we can grant this.

It would be easier if we had unique constraints in the database for things (columns or combinations of multiple columns) which our PHP code expects to be unique.

**Comment by chmst** [comment]
Can we close this? The issue itself is resolved. 

It will be better to make an issue for other problems which are not so obvious.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28674">issues.joomla.org/tracker/joomla-cms/28674</a>.</sub>

**Comment by richard67** [comment]
> Can we close this? The issue itself is resolved.

Depends on @Quy , I think.

**Comment by Quy** [comment]
@richard67 I thought you were researching on this when upgrading.  See your previous comment.

**Comment by richard67** [comment]
@Quy Well I have had only a brief look up to now, and I haven't seen a solution yet.

**Comment by Quy** [comment]
No longer reproducible.
