### ISSUE TITLE
[4.0] Install from Web does not work

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28671]
### Steps to reproduce the issue

Clicking on install from web does not do anything. Also no errors in console.

<img width="1382" alt="grafik" src="https://user-images.githubusercontent.com/828371/79073835-04ebae00-7ce9-11ea-8cd2-c9c272a87ffa.png">

**Comment by mbabker** [comment]
Duplicate of https://github.com/joomla/joomla-cms/issues/19429<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28671">issues.joomla.org/tracker/joomla-cms/28671</a>.</sub>
