### ISSUE TITLE
[4.0][a11y] Drop down chevron hard to recognize

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28673]
### What needs to be fixed

The contrast of the drop down chevron in the status of the plugins is not good. It's not easy to recognize it. It passes the a11y test with 4.1 but white would offer a better visibility and contrast for everyone with 5.12.

<img width="288" alt="grafik" src="https://user-images.githubusercontent.com/828371/79074815-bb9e5d00-7cee-11ea-8f29-76f07c4692b8.png">

**Comment by Quy** [comment]
Duplicate #28463

**Comment by brianteeman** [comment]
Not as easy as it may seem - see the discussion on the PR here #28755

**Comment by Quy** [comment]
Duplicate #35010
