### ISSUE TITLE
[3.10]=>[4] update "count(): Parameter must be an array or an object that implements Countable in override.php"

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#28682]
### Steps to reproduce the issue
- Updated 3.10 nightly to 4.0
- Notice in my error log file:

`PHP Warning:  count(): Parameter must be an array or an object that implements Countable in plugins/installer/override/override.php on line 134`

Also reported here: https://github.com/joomla/joomla-cms/issues/28614#issuecomment-611423392

**Comment by richard67** [comment]
@ReLater Please test PR #28683 .

**Comment by richard67** [comment]
Closing as having a PR.
