### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by faiyaz743** [joomla/joomla-cms#28693]
Dear All,
I am getting this error in my wordpress site so please let me know how can i solve it?
Through any pluging or i need to change setting in code?
As i dont know much about coding but if any one can help me what need to done then i can do it.
Thanks in advance.

Warning: Use of undefined constant MCRYPT_MODE_CBC - assumed 'MCRYPT_MODE_CBC' (this will throw an Error in a future version of PHP) in /home/customer/www/arrtkart.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php on line 94

**Comment by alikon** [comment]
i'm sorry but this repo is for Joomla not Wordpress maybe you can find more info here https://wordpress.org/support/forums/
