### ISSUE TITLE
Error in Joomla calendar

### ISSUE THREAD

**Issue by balvard** [joomla/joomla-cms#28698]
### Steps to reproduce the issue
file : media/system/js/fields/calendar-locales/date/jalali/date-helper.js
Error : This function not return required![screen shot 2020-04-17 at 08 00 42](https://issues.joomla.org/uploads/1/fcfa5ff3c55407d049f460ac930f6081.jpg) data
```
Date.prototype.getLocalMonthDays = function(dateType, month) {
	if (dateType != 'gregorian') {
		/** Modify to match the current calendar when overriding **/
		var year = this.getLocalFullYear('jalali');
		if (typeof month == "undefined") {
			month = this.getLocalMonth('jalali');
		}
		if (((0 == (year%4)) && ( (0 != (year%100)) || (0 == (year%400)))) && month == 1) {
			return 29;
		} else {
			Date.local_MD[month]; <=== Error : Must be returned this value
		}
	} else {
		var year = this.getFullYear();
		if (typeof month == "undefined") {
			month = this.getMonth();
		}
		if (((0 == (year%4)) && ( (0 != (year%100)) || (0 == (year%400)))) && month == 1) {
			return 29;
		} else {
			return Date.gregorian_MD[month]; <==== Like this
		}
	}
};
```

### Expected result

This is Expected
```
Date.prototype.getLocalMonthDays = function(dateType, month) {
	if (dateType != 'gregorian') {
		/** Modify to match the current calendar when overriding **/
		var year = this.getLocalFullYear('jalali');
		if (typeof month == "undefined") {
			month = this.getLocalMonth('jalali');
		}
		if (((0 == (year%4)) && ( (0 != (year%100)) || (0 == (year%400)))) && month == 1) {
			return 29;
		} else {
			return Date.local_MD[month];
		}
	} else {
		var year = this.getFullYear();
		if (typeof month == "undefined") {
			month = this.getMonth();
		}
		if (((0 == (year%4)) && ( (0 != (year%100)) || (0 == (year%400)))) && month == 1) {
			return 29;
		} else {
			return Date.gregorian_MD[month];
		}
	}
};
```

**Comment by balvard** [comment]
And This function has same error
Date.prototype.getMonthDays<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28698">issues.joomla.org/tracker/joomla-cms/28698</a>.</sub>

**Comment by infograf768** [comment]
@balvard 
Could you please add screenshots of the Jalali results obtained in both cases, i.e. with return and without the return, for a said Gregorian date?

@dgrammatiko 
Any possible error here?

**Comment by dgrammatiko** [comment]
@balvard @infograf768 yes a `return ` is required as correctly stated above.

**Comment by infograf768** [comment]
OK. You make patch or I do?

**Comment by brianteeman** [comment]
(reset priority according to our defined criteria)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28698">issues.joomla.org/tracker/joomla-cms/28698</a>.</sub>

**Comment by dgrammatiko** [comment]
>  You make patch or I do?

If you're referring to me please do the PR (or maybe @balvard would like to do that)

**Comment by infograf768** [comment]
will do as we also need a minified, but testing now differences first.

**Comment by infograf768** [comment]
Please see patch https://github.com/joomla/joomla-cms/pull/28700

@balvard 
Please explain there the display differences with screenshots.
Closing this as we have a patch.
