### ISSUE TITLE
issues when entering dates in persian calendar 

### ISSUE THREAD

**Issue by rasouldanesh90** [joomla/joomla-cms#28702]
Hello
We choose a solar date
On some dates, a unit is added to the month or day, and we reopen the calendar or save the content.
The Joomla version I am using is 3.9.12.

@farhadst
@dGrammatiko

**Comment by infograf768** [comment]
Is this the solution ?
https://github.com/joomla/joomla-cms/pull/28700
Please test.

**Comment by rasouldanesh90** [comment]
I tested your solution, no change
I think this problem should be in the file
media / system / js / fields / calendar.js
Lines 1014 to 1042 that change the value "data-alt-value" when the calendar opens

**Comment by infograf768** [comment]
This file has not been touched for years and is a dynarch project. I would not touch it even with twisters...

**Comment by richard67** [comment]
@rasouldanesh90 3.9.12 is a bit old, current version is 3.9.16, and 3.9.17 will be released soon. You should keep your Joomla always up to date because of security patches. Beside this, could you check if the corrections from pull requests #28596 and #17859 solve that issue? You should apply both changes together.

**Comment by infograf768** [comment]
Also, please specify some dates concerned (in gregorian format)

**Comment by balvard** [comment]
This error appeared when you want to declare personal function to control date in persian
and we need return true date but returned null
In gregorian is true
But joomla team forget to return true data for those function

**Comment by infograf768** [comment]
@balvard 
It is impossible to do anything if you do not explain exactly (with code) what you want to do and where precisely, in your opinion, is the error in the js files.
**fa-IR is using a custom calendar.js file** which is installed in media/fa-IR/js/
Here is its uncompressed version
[calendar-uncompressed.js.zip](https://github.com/joomla/joomla-cms/files/4508084/calendar-uncompressed.js.zip)

**Comment by Quy** [comment]
Closing due to lack of response. You can comment here and we can re-open the issue.
