### ISSUE TITLE
update.xml Type of current update is taken from previous

### ISSUE THREAD

**Issue by svanschu** [joomla/joomla-cms#28712]
### Steps to reproduce the issue
Update XML with content like

I had a bug in my update.xml that's true, but anyway the behaviour is a bug in my eyes.

1. the type of the 3.0.0 is package
2. the type of the 3.1.0 is component 

```
<updates>
        <update>
            <name>XXX</name>
            <element>com_xxx</element>
            <type>component</type>
            <version>3.1.0</version>
            <downloads>
                <downloadurl type="full" format="zip"></downloadurl>
            </downloads>
            <tags>
                <tag>stable</tag>
            </tags>
            <targetplatform name="joomla" version="3.[6789]" />
            <php_minimum>5.6</php_minimum>
        </update>
        <update>
            <name>XXX</name>
            <element>com_xxx</element>
            <type>package</type>
            <version>3.0.0</version>
            <downloads>
                <downloadurl type="full" format="zip"></downloadurl>
            </downloads>
            <tags>
                <tag>stable</tag>
            </tags>
            <targetplatform name="joomla" version="3.[6789]" />
            <php_minimum>5.6</php_minimum>
        </update>
    </updates>
```

### Expected result
the joomla update database table shows a update with with version 3.1.0 and type compnent

### Actual result
the joomla update database table shows a update with with version 3.1.0 and type package

### System information (as much as possible)
Joomla 3.6.16
PHP 7.3.6

**Comment by zero-24** [comment]
is the actual extension that added the update server from type component or package?

**Comment by svanschu** [comment]
The extension added the update server as component.
So I would expect that the newest update appear as update independent to the previous entry in the XML.
I tested with 5 entries and the 3 oldest are ignored as expected, even if they were added wrong to the XML.

**Comment by zero-24** [comment]
can you share an example component with the exact settings / xml you used. Would be interesting to debug and see what happend there.

**Comment by svanschu** [comment]
Hi @zero-24, I give up ... I created the application and update.xml as I posted, but I can't reproduce anymore.
I don't know what happend, I thought I tested enough before creating the issue.

Sorry

**Comment by zero-24** [comment]
Feel free to repopen when this comes up again and ping me so we can take a look :)
