### ISSUE TITLE
[4.0] load module plugin 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#28715]
### Steps to reproduce the issue
Create a custom html module in position none
Create an article and insert the module
create a menu link to the article

### Expected result
Article is displayed on the frontend with the content of module

### Actual result
Article is displayed on the frontend without the content of the module

**Comment by SharkyKZ** [comment]
Already fixed in staging https://github.com/joomla/joomla-cms/pull/28278.

**Comment by infograf768** [comment]
Indeed. for 3.9.17.

**Comment by brianteeman** [comment]
This should stay open until it is fixed in J4

**Comment by brianteeman** [comment]
It is not the exact same issue - that is for loadmodule by id

here it is for all methods of loading a module eg
```
{loadmodule articles_categories,Articles Categories}
{loadmoduleid 146}
```

**Comment by infograf768** [comment]
For id, I tested here and we do get, via the XTD
`{loadmoduleid 115}`
in 3.9.17 it is solved by #28278 
I corrected this in 4.0 with same code and it now works fine when using id.
Also, it concerns all modules, not only the html module.

Not tested for {loadmodule articles_categories,Articles Categories}

**Comment by brianteeman** [comment]
> Also, it concerns all modules, not only the html module.

yeah that was just for how to replicate

**Comment by SharkyKZ** [comment]
>{loadmodule articles_categories,Articles Categories}

This works. The module has to be assigned to current menu item.

**Comment by brianteeman** [comment]
Not for me

![image](https://user-images.githubusercontent.com/1296369/79635522-5cff3600-8169-11ea-9fc5-93c2e909ddd3.png)

**Comment by SharkyKZ** [comment]
The issue is in most likely in sample data. Try selecting a category that contains articles.

**Comment by brianteeman** [comment]
Nothing to do with sample data as I tested with other modules

**Comment by infograf768** [comment]
Tested here
```
Quo no falli viris intellegam, ut fugit veritus placeratper. Ius id vidit volumus mandamus, vide veritus democritum te nec, ei eosdebet libris consulatu.

-----------------

{loadmodule mod_breadcrumbs,Breadcrumbs}

------------------- customhtml module

{loadmoduleid 114}

-------------------- Login module

{loadmoduleid 115}
```
And it works fine.

<img width="964" alt="Screen Shot 2020-04-19 at 09 11 56" src="https://user-images.githubusercontent.com/869724/79681851-f12ad500-821d-11ea-8c15-ec4b7af87bcf.png">

**Comment by brianteeman** [comment]
I can see **my** error I was using {loadmoduleid for both examples
