### ISSUE TITLE
[4.0] Site Stats module - workflow error

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#28717]
### Steps to reproduce the issue
Publish the statistics module

### Expected result

![image](https://user-images.githubusercontent.com/1296369/79632665-bc087f00-8158-11ea-922d-4a09cf31f5be.png)

### Actual result
![image](https://user-images.githubusercontent.com/1296369/79632725-186b9e80-8159-11ea-881c-f61e7221273f.png)

### Additional comments
Once again the problem is with workflows - specifically this code
https://github.com/joomla/joomla-cms/blob/ad74804380ca414800b315c80706c6cb9aa94b9d/modules/mod_stats/src/Helper/StatsHelper.php#L135-L139

**Comment by alikon** [comment]
please test #28723
