### ISSUE TITLE
[3.9] User rights. Expected bahavior?

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#28733]
### Steps to reproduce the issue
- Joomla 3. current staging with testing sample data.

- Backend: Go to `Content `> `Options `> `Permissions`.
- Disallow anything for groups `Author`, `Editor`, `Publisher`.

- Create a new user in group `Administrator` only.
- Open front-end and try to edit an article there => Success.

- Backend: Add second group to user above: `Editor`.

- Open front-end and try to edit an article there => Not allowed.

For me that's weird bahavior. Or is it expected that a second group can remove rights from another?

**Comment by HLeithner** [comment]
I think I can't follow you do you have some screenshots?

**Comment by ReLater** [comment]
No time.

**Comment by gerryfrancis** [comment]
I think it is correct behavior. Although the new user is a member of Administrator group, he/she has no explicit right to edit. But my understanding can be wrong, of course.

**Comment by ReLater** [comment]
I wasn't aware that one additional group can block the rights of another group that has these rights. Both are in another tree. More irritating than logical for me.
I asked for another guy. I personally don't care ;-)

**Comment by gerryfrancis** [comment]
@ReLater This is interesting. What happens after the user has been kicked out of the groups "Author" and "Publisher"? Can he/she edit an article then?

**Comment by ReLater** [comment]
### com_content options:
![22-04-_2020_16-21-31](https://user-images.githubusercontent.com/20780646/79993903-8eec0180-84b5-11ea-90e6-9c9ff8e580f7.jpg)

![22-04-_2020_16-19-29](https://user-images.githubusercontent.com/20780646/79993922-94494c00-84b5-11ea-9aef-3d501b75b704.jpg)

### Edit article in front-end:
- User only in Administrator group: Can edit.

- Add second group (with limited rights like shown above in image 2) in user profile: Cannot edit.

- Remove second group in user profile:  Can edit.

**Comment by gerryfrancis** [comment]
@ReLater From my own logical thinking, editing should be prohibited when the user is a member of a group that has no rights for it. The question that is to be answered is: Where does the respective inheritation start from? Maybe from the "Registered" group?

**Comment by ReLater** [comment]
From my point of view it's not logical ;-) when I compare it with other systems like mediawiki, typo3, Magento...
As I've said already it's OK for me to know it now.
