### ISSUE TITLE
Make [Discussions] available (on GitHub page)

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#28731]
I mean this function, as the Bootstrap team did - [https://github.com/twbs/bootstrap/discussions](https://github.com/twbs/bootstrap/discussions).

To discuss Joomla 4 and other issues.

**Comment by mbabker** [comment]
👎

Looks like it's just a specialized list of issues or pull requests.  There is no additional functionality added with that tab that isn't already present.

**Comment by alikon** [comment]
what should be the added values ?
imho issues and pull requests are more than enough

**Comment by gerryfrancis** [comment]
> what should be the added values ?

The value to criticize without value... ;)

**Comment by richard67** [comment]
It seems it is not just a filter for issues or PRs, it is a new feature for a repository, and the discussion items are not listed in the issues or PRs.

This new discussions for repositories feature should not be mixed up with the Team Discussions on GitHub, for which already some documentation can be found. The discussions in a repository mentioned here are a new feature in a very early beta phase, as far as I could read up to now in diferse other repositories where the same request was made like it was made here.

E.g. you can find some info on it here: [https://github.com/zeit/now/discussions/3874](https://github.com/zeit/now/discussions/3874).

There is also an interesting comment here, with some drawbacks to be mentioned: [https://github.com/microsoft/microsoft-ui-xaml/issues/2013#issuecomment-592689659](https://github.com/microsoft/microsoft-ui-xaml/issues/2013#issuecomment-592689659).

Such discussions could maybe help us to separate pure discussions, e.g. about which of a few possible ways to go with a certain new feature, from real issues (bugs) or (draft) PRs. In this way it could maybe help us to reduce our number of (real) issues and PRs. It would be worth a question if also RFC issues should become discussions then.

But as long as it is in such an early beta phase that it seems to be nearly impossible to find some official documentation on it - at least not with the typical keywoards - we should wait a bit until that green banana became a bit more yellow.

Then we can evaluate if there is some value in it for us here.

**Comment by 4digitalworld** [comment]
@richard67 I think this new section can replace the [forum](https://forum.joomla.org/) in some way. 

It is enough to even see how much discussions has been created for example here: [https://github.com/zeit/next.js/discussions](https://github.com/zeit/next.js/discussions)

This section would be good for non-programmers. This section would be very good for ideas, for proposals for the development of Joomla. I mean, in this section it would be possible to create topics that do not require code, do not require a kernel change. Just a discussion of something.

**Comment by richard67** [comment]
No, I think we should not use it to replace the forum. Maybe we should make the forum better, it should stay the place for support questions. Here we have sometimes issues or pull requests which are in discussion, and for such the new feature might be a replacement.

**Comment by brianteeman** [comment]
This should probably be closed as it is not related to the code and referred to the Production Team @marcodings

**Comment by alikon** [comment]
i'm  closing it for now
lack of interest
