### ISSUE TITLE
Remove PLG_FIELDS_SQL_RULES_ADAPTED

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#28745]
### Steps to reproduce the issue
Per https://github.com/joomla/joomla-cms/commit/cf2534078e8b47162f5ba4b197ef99230ebe9d81#diff-11fed044d3100e730646fa939fed4be2L82, the following string should be removed.

> PLG_FIELDS_SQL_RULES_ADAPTED="For increased security the edit permission for this SQL field was set to denied for all non Super Users."

**Comment by ReLater** [comment]
See pr https://github.com/joomla/joomla-cms/pull/28757

**Comment by ReLater** [comment]
@Quy 

Please reopen. pr refused.

**Comment by HLeithner** [comment]
@ReLater would you be so nice and create the PR against j4?
