### ISSUE TITLE
[3.9.x] Menu Item Alias can't be selected as Base Item

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28742]
### Steps to reproduce the issue
Create a Menu Item Alias with Subitems
Create a Menu Module and try to select the Menu Item Alias as Base Item

### Expected result
You should be able to select the Menu Item Alias as Base Item

### Actual result
You have to switch the Menu Item Alias to another Item Type
Then you can select it as Base item
Then you switch back to Menu Item Alias to have the wished result

### System information (as much as possible)
Joomla 3.9.16

### Additional comments
Usability fix
Also Affected Menutypes are: URL, Headings, Seperators - they should be selectable as base item in a menu module.

**Comment by brianteeman** [comment]
Same issue as #20556

**Comment by coolcat-creations** [comment]
Thank you for finding that - closing then.
