### ISSUE TITLE
Can not update J3.9.16 to J3.9.17

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#28749]
### Steps to reproduce the issue

Go to Joomla Global Configuration > Components > Joomla Update

Select the Live Update tab and click on Check for Updates.

There appears a message "You already have the latest Joomla version, 3.9.16."

### Expected result

Joomla! 3.9.16 is being updated to 3.9.17

### Actual result

Joomla! 3.9.16 is NOT being updated to 3.9.17

### System information (as much as possible)

Joomla! Version	Joomla! 3.9.16 Stable [ Amani ] 10-March-2020 15:00 GMT

### Additional comments

It is possible to update Joomla via the Upload & Update tab

**Comment by zero-24** [comment]
Yes 3,9.17 has been taken down 3.9.18 is beeing prepared in the backgroud already to be released soon.

**Comment by sandewt** [comment]
> Yes 3,9.17 has been taken down 3.9.18 is beeing prepared in the backgroud already to be released soon.

@zero-24 , Is that already mentioned somewhere on the site?

**Comment by zero-24** [comment]
On wich site?

**Comment by sandewt** [comment]
> On wich site?

E.g. https://downloads.joomla.org/ or https://www.joomla.org/announcements.html<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28749">issues.joomla.org/tracker/joomla-cms/28749</a>.</sub>

Because others can get against this problem too :-)

**Comment by HLeithner** [comment]
Release is already done now.

**Comment by sandewt** [comment]
Thanks, it works.
