### ISSUE TITLE
3.9.17 update internal server error?

### ISSUE THREAD

**Issue by peteruoi** [joomla/joomla-cms#28744]
### Steps to reproduce the issue
In two sites hosten on the same vps when i press the update button from 3.9.16 to 3.9.17 it freezes.
i found in the error log [Tue Apr 21 18:47:05.951212 2020] [fastcgi:error] [pid 4843] [client 79.107.134.35:27472] FastCGI: incomplete headers (0 bytes) received from server "/var/www/clients/client/web/cgi-bin/php-fcgi-myipmysite", referer: https://mysite/administrator/index.php?option=com_joomlaupdate

### System information (as much as possible)

Ubuntu 16.04 php 7.4.5

### Additional comments
 Is this something that concerns the joomla update or some problem with hosting?

**Comment by peteruoi** [comment]
Just to add that upload and update works.
Also i changed to php 7.0 that comes preinstalled with ubuntu 16.04 and it works. So i guess it's an php 7.4.5 thing? If you think it's specific to my hosting tell me and i close it :)

**Comment by HLeithner** [comment]
hmm Github didn't want my message....

it seams you got a timeout on execution but I can't tell you the reason, PHP 7.4.5 should work but I didn't tested yet.

**Comment by peteruoi** [comment]
Yes it was an max execution reached bacause  couldn't fetch the update file... I don;t know why. However now it's not reproducible anymore. It's fixed (don't lnow how...) Thanks!

**Comment by peteruoi** [comment]
I has happened again with another site... Two sites worked and it happened on the third... Maybe joomla's update provider has some problems?
