### ISSUE TITLE
Superusers can no longer change their own password

### ISSUE THREAD

**Issue by rodfarrell** [joomla/joomla-cms#28750]
### Steps to reproduce the issue
Log into administrator dashboard as a superuser and select Users > Manage
Select your own account
Type a new password and confirm password
Save

### Expected result
Password should have changed

### Actual result
Error: Save failed with the following error: The email address you entered is already in use. Please enter another email address.

### System information (as much as possible)
Joomla 3.9.18

**Comment by richard67** [comment]
@rodfarrell Could you check if there is another user who uses the same email address as the super user has? If you have many users, the fastest way would be to look up in tooles like e.g. PhpMyAdmin.

**Comment by rodfarrell** [comment]
You are correct sir! I wonder how they managed to do that?  I've just taken over the site development so maybe the previous developer has done some manual editing of accounts direct to the database.  Thank you.  Should I mark this as closed?

**Comment by richard67** [comment]
@rodfarrell Maybe it was done directly in SQL. Anyway, happy we could solve it.
