### ISSUE TITLE
[4.0] reCaptcha not working

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-cms#28758]
In Joomla 4, the Google reCaptcha plugin seems broken. 
The iframe with the Captcha is not loaded.
I've tested this issue also with the "System - HTTP Headers" plugin disabled, which gives the same result.

### Steps to reproduce the issue
In Joomla 4 back-end:
- Enable + **configure** the **reCaptcha** plugin: 
System > Plugins > open the reCaptcha plugin
  - Add a Site Key + Secret Key
  - Enable the plugin
- **Set** reCaptcha as **default CAPTCHA** plugin
System > Global Configuration > [Site] tab > Default Captcha: select "**CAPTCHA - reCAPTCHA**"
- **Create** a **contact form**
Components > Contacts > Contacts > New
  - Add "Test" Name + Email
- **Create menu item** for **contact form**
Menus > Main Menu > New > 
  - Add menu title "Contact form"
  - Select "Menu Item Type": Contacts > Single Contact
  - Select "Contact": the "Test" contact that you've just created

On the front-end: Click on the "Contact form" menu item that you've just created.
At the bottom the form shows "Captcha * (optional)" but **without the Google reCaptcha**

![j4-recaptcha-missing](https://user-images.githubusercontent.com/1217850/79979302-96a1ab00-84a1-11ea-8c1b-5e8f5fc29f44.png)

### Expected result
The contact form should contain the reCaptcha CAPTCHA to protect the form against spam abuse.

I would expect Joomla's contact form to contain an iframe where the reCaptcha would be loaded.
The following HTML code is the HTML Source from a contact form (com_contact) that I copied from a **Joomla 3.9.x** website:

```html
<fieldset>
<div class="control-group">
<div class="control-label">
<label id="jform_captcha-lbl" for="jform_captcha" class="hasPopover required" title="" data-content="Vul de beveiligingscontrole in." data-original-title="Captcha">
Captcha<span class="star">&nbsp;*</span></label>
</div>
<div class="controls">
<div id="jform_captcha" class=" required g-recaptcha" data-sitekey="[xxx]" data-theme="light" data-size="normal" data-tabindex="0" data-callback="" data-expired-callback="" data-error-callback="" data-recaptcha-widget-id="0">
<div style="width: 304px; height: 78px;">
<div>
<iframe src="https://www.google.com/recaptcha/api2/anchor?[xxx]&amp;theme=light&amp;size=normal&amp;cb=kc6a5cbbomxn" width="304" height="78" role="presentation" name="a-n2pvm9ei6huv" frameborder="0" scrolling="no" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox">
</iframe>
</div>
<textarea id="g-recaptcha-response" name="g-recaptcha-response" class="g-recaptcha-response" style="width: 250px; height: 40px; border: 1px solid rgb(193, 193, 193); margin: 10px 25px; padding: 0px; resize: none; display: none;">
</textarea>
</div>
<iframe style="display: none;">
</iframe>
</div>
</div>
</div>
</fieldset>
```

### Actual result

In Joomla 4 the iframe is not loaded. The HTML source looks like:

```html
<fieldset>
<div class="control-group">
<div class="control-label">
<label id="jform_captcha-lbl" for="jform_captcha" class="required">Captcha<span class="star" aria-hidden="true">&nbsp;*</span></label>
<span class="optional">(optional)</span>
</div>
<div class="controls"></div>
</div>
</fieldset>
```

### Additional comments
I ran into this issue when coding a hCaptcha CAPTCHA alternative: https://github.com/joomla/joomla-cms/issues/28613
My hCaptcha plugin works on Joomla 3.9.x but not on Joomla 4. 
Hence I was looking at the default Google reCaptcha in Joomla 4 and ran into the same issue.

**Comment by alikon** [comment]
maybe related to  #28426 let's ping @Fedik for some more insight

**Comment by Fedik** [comment]
The bug in [`Joomla\CMS\Captcha\Captcha`](https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Captcha/Captcha.php)
`onInit()`, `onDisplay()`, `onCheckAnswer()` is a **callbacks** and not an events

**Comment by Fedik** [comment]
please test #28785

**Comment by pe7er** [comment]
@Fedik Thanks for fixing this issue!
