### ISSUE TITLE
Joomla Offline Site Problem 3.9.18

### ISSUE THREAD

**Issue by Gioiello196** [joomla/joomla-cms#28754]
sorry for my English. I'm italian.

Problem: With the site offline, if I try to log in from FrontEnd with username and password, an error page appears.

This happened with this morning's update to version 3.9.18

I hope someone can solve it. Thank you.

**Comment by infograf768** [comment]
can't reproduce the error here.

**Comment by Sandra97** [comment]
can't reproduce either.

**Comment by richard67** [comment]
can't reproduce either, using the one and only user I have, the super user created with installation. @Gioiello196 Could you provide details? Is it the super user you have problems with? Or another one? If another one: Which user group does that user belong to?

**Comment by C-Lodder** [comment]
I can see in the Network tab that it throws a 503, but nothing shown on the page

**Comment by richard67** [comment]
Same here.

**Comment by gerryfrancis** [comment]
@Gioiello196 Which error message appears when you attempt to load your site? (You may post the message in Italian, too.) Otherwise it is hard to guess which problem you are experiencing.

**Comment by Gioiello196** [comment]
ok .. I don't know what happened but now it works. However, the problem happened on my 2 joomla sites, immediately after the 3.9.18 update. Putting the site offline and logging on the frontend side with super user data resulted in an error. As if it didn't connect to the server. Thanks to everyone for the availability and we hope that it has settled.

**Comment by richard67** [comment]
@Gioiello196 Thanks for reporting back.
