### ISSUE TITLE
[3.x-4.0] Wrong types in API documentation

### ISSUE THREAD

**Issue by nhusung** [joomla/joomla-cms#28765]
### What needs to be fixed

To me it seems that the types of the properties `lastvisitedDate` and `registerDate` of `\Joomla\CMS\User\User` are wrong in the API documentation. I guess they should be `string` (at least if the other database drivers handle dates in a similar way compared to MySQLi).

https://github.com/joomla/joomla-cms/blob/7162ed44435e008451cb390a0cde9e17716a2328/libraries/src/User/User.php#L102-L116

### Why this should be fixed

Thinking the `lastvisitedDate` property of `\Joomla\CMS\User\User` was an `\DateTime` object I tried to `clone` it in my own plugin in order to convert the date to a string in the User’s timezone. However, that gave me an error because the property actually was a `string`.

The issue occured on J3.9.16 using the MySQLi database driver.

### How would you fix it

See #28766.

### Side Effects expected

None.

**Comment by nhusung** [comment]
Just created a PR for 4.0 in case that helps …

**Comment by nhusung** [comment]
Should I open one for J3.9 as well?

**Comment by Quy** [comment]
Closing as we have patch #28766
