### ISSUE TITLE
Update server for NightlyBuilds for 3.9.19-dev is broken

### ISSUE THREAD

**Issue by dmitriy-cloudaccess** [joomla/joomla-cms#28775]
`https://update.joomla.org/core/nightlies/next_patch_extension.xml`
has download link which points to `https://developer.joomla.org/nightlies/Joomla_3.9.19-dev-Development-Update_Package.zip`
There is no file available by this link.

and version 3.9.19-dev is not present at 
https://developer.joomla.org/nightly-builds.html

**Comment by HLeithner** [comment]
@dmitriy-cloudaccess we are award of this Problem and try to solve it, thx for you report.

**Comment by zero-24** [comment]
@HLeithner can we generate it one time manually? Or is there still the old package on that server so we work around the issue by pointing to that old package?

**Comment by jwaisner** [comment]
This has been corrected. Latest build is today 04/25/2020.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28775">issues.joomla.org/tracker/joomla-cms/28775</a>.</sub>
