### ISSUE TITLE
GUI problem - Category Article

### ISSUE THREAD

**Issue by adj9** [joomla/joomla-cms#28783]
### Steps to reproduce the issue
I downloaded the Joomla! Update 4 [[https://developer.joomla.org/nightly-builds.html](url)] today and when creating a new article, I don't have the arrow at the bottom of the article category button.
screan
<img width="1428" alt="Schermata 2020-04-25 alle 11 47 32" src="https://user-images.githubusercontent.com/5918444/80276695-9f38f200-86ea-11ea-8f64-35d71e186e6d.png">

I notice that when I open the category menu, the load of items is not immediate.

# Requires

- Web site
- Safari 13.0.5
- macOS Catalina 10.15.3

**Comment by Quy** [comment]
Is this reproducible in Chrome or just in Safari?

**Comment by brianteeman** [comment]
This has been fixed elsewhere and can be closed
