### ISSUE TITLE
AppVeyor CI tests are failing for PHP >= 7.2 on staging branch

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#28789]
### Steps to reproduce the issue

Since commit [https://github.com/joomla/joomla-cms/commit/683793d180f930490b248fd46a294e3f8d480df8](https://github.com/joomla/joomla-cms/commit/683793d180f930490b248fd46a294e3f8d480df8) the AppVeyor CI tests are failing for PHP versions >= 7.2 on the staging branch.

### Expected result

AppVeyor CI tests succeed.

### Actual result

AppVeyor CI tests fail.

### System information (as much as possible)

[https://ci.appveyor.com/project/release-joomla/joomla-cms/builds/32434590](https://ci.appveyor.com/project/release-joomla/joomla-cms/builds/32434590), or [https://ci.appveyor.com/project/release-joomla/joomla-cms/builds/32423781](https://ci.appveyor.com/project/release-joomla/joomla-cms/builds/32423781).

### Additional comments

The "error" message "Your Composer dependencies require a PHP version ">= 5.3.10" and "< 7.2.0". You are running ..." at the bottom of each log is misleading, is also comes when a build has run with success.

**Comment by richard67** [comment]
Ping @zero-24 as agreed.

**Comment by zero-24** [comment]
We might try here: https://github.com/joomla/joomla-cms/blob/staging/.appveyor.yml#L132

composer install --ignore-platform-reqs ?

And see whether it is a workaround.

What do you think @rdeutz

**Comment by zero-24** [comment]
Here is the proposed PR: https://github.com/joomla/joomla-cms/pull/28890 please do not close here right now as I'm not sure whether that PR works out.

**Comment by zero-24** [comment]
As my proposed fix does not fix the issue i have just closed the PR so this Issue here should stay open to track the issue. So someone who has more knowledge with appveyor can take a look here. Thanks.

**Comment by brianteeman** [comment]
This appears to have been fixed https://github.com/joomla/joomla-cms/commit/3687dba27ed2f7e5cedc50797a8073ba31e29efa and can now be closed
