### ISSUE TITLE
J3.9 - Update issue with different versions format

### ISSUE THREAD

**Issue by zstergios** [joomla/joomla-cms#28782]
Hi,
the XML extension update server has version value 2.0.0
The extension XML version value is 2.0.

Joomla detects that there is available update.

PS: if I change both versions with same format works.

### Expected result
2.0.0 and 2.0 should be considered as same value.
Extension update should consider the extension is up to date.

### Actual result
Extension Updater displays new available update from 2.0 to 2.0.0

### System information (as much as possible)
Joomla 3.9.16
PHP 7.2

**Comment by zero-24** [comment]
Well we use version_compare here: https://www.php.net/manual/en/function.version-compare.php and this is the default behavior: https://3v4l.org/shGWF so it seems to be the correct behavior.

**Comment by jwaisner** [comment]
Agreed. This behavior is expected as 2.0 is considered a lower version than 2.0.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28782">issues.joomla.org/tracker/joomla-cms/28782</a>.</sub>
