### ISSUE TITLE
J4 beta1 Content - Page Break breaks the article completely

### ISSUE THREAD

**Issue by AMMX78** [joomla/joomla-cms#28795]
### Steps to reproduce the issue
Use a system-pagebreak in an article in J4 beta 1.

### Expected result
As usual. Worked in J4 alpha 12.

### Actual result
No article is displayed with the following message:
The requested page can't be found.

An error has occurred while processing your request.

You may not be able to visit this page because of:

    an out-of-date bookmark/favourite
    a mistyped address
    a search engine that has an out-of-date listing for this site
    you have no access to this page

Go to the Home Page

If difficulties persist, please contact the website administrator and report the error below.

    0 Call to a member function isRtl() on null 

### System information (as much as possible)
Webhosting with PHP 7.3. Just upgraded from alpha 12 to beta 1 and upgraded database tables using Joomla function.

### Additional comments
The only way to avoid this is to disable the corresponding plugin (Content - Page Break). But the system-pagebreak does not work anymore.

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/28797

**Comment by richard67** [comment]
Closing as having a pull request (PR). Please test #28797 .
