### ISSUE TITLE
[4.0] Dashboard icons missing borders on small screens

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#28793]
### Steps to reproduce the issue
View cpanel dashboard on latest github build. You can see some of my icons are missing borders (e.g. Global Configuration and Global checkin the right border, Media the bottom border). I assume this is due to the dashboard SCSS cleanup by @ciar4n combined with my 13 inch screen width being narrow.

![image](https://user-images.githubusercontent.com/1986000/80281294-feeec780-8701-11ea-8c2b-88cb0c46c6e6.png)

**Comment by C-Lodder** [comment]
OS? Browser? Version?
Have you tried a different browser?
Have you tried refreshing the page?

**Comment by richard67** [comment]
Can't reproduce with current 4.0-dev and Firefox 75.0 (64-Bit) for Windows or Google Chrome 81.0 (64-Bit) for Windows. Had made a fresh install, and before that I had cleared browser cache.

**Comment by richard67** [comment]
Maybe not only related to screen width, because with reducing width on my large screen I can't reproduce.

**Comment by ciar4n** [comment]
Unable to replicate here either (windows - chrome/ff).

It shouldn't be related to any recent changes... I haven't gotten around to this part of the template css yet.

**Comment by richard67** [comment]
Maybe an iOS thing?

**Comment by infograf768** [comment]
Can't reproduce on Firefox/Safari Macintosh

**Comment by wilsonge** [comment]
Just Chrome (version 81). OSX.

Firefox/Safari both look fine although interestingly both wrap the dashboard differently

<img width="1276" alt="Screenshot 2020-04-25 at 18 40 36" src="https://user-images.githubusercontent.com/1986000/80286668-9fee7a00-8724-11ea-81b2-901167756e61.png">

<img width="1280" alt="Screenshot 2020-04-25 at 18 41 19" src="https://user-images.githubusercontent.com/1986000/80286670-a3820100-8724-11ea-8e36-14cfd8ffa4b6.png">

**Comment by wilsonge** [comment]
Ignore me - I'm an idiot - I apparently was zoomed out to 90% on my localhost for some reason (which of course chrome persists across tabs) 🤦
