### ISSUE TITLE
[4.0] Frontend Template copy failed

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28796]
### Steps to reproduce the issue
Same issue like here: https://github.com/joomla/joomla-cms/pull/19420#issuecomment-619357149 - but it's closed and I was asked to create a new issue.

Tried to copy a template which did not work.

![grafik](https://user-images.githubusercontent.com/828371/80281629-d02a1e80-870c-11ea-8584-48af1869eb25.png)

**Comment by infograf768** [comment]
The issue is that the language folder in our Cassiopea template was taken off, which means the whole copy template code has to be modified to also check for the template language files in the core language folders, this whether copying a site or admin template.

See https://github.com/joomla/joomla-cms/pull/23493
Specially https://github.com/joomla/joomla-cms/pull/23493#issuecomment-527197099
and
https://github.com/joomla/joomla-cms/pull/23493#issuecomment-452999058

**Comment by infograf768** [comment]
@Bakual

**Comment by Bakual** [comment]
I think it fails in the fixTemplateName method (https://github.com/joomla/joomla-cms/blob/1377ce9a79e39b0ceb76aca63baef6598141d618/administrator/components/com_templates/src/Model/TemplateModel.php#L785) where it tries to rename the language files.

That's where we have to change the code so it looks up the language files both in the local language folder and in the global one. For the global one, it obviously has to filter the files by template name and not just blindly copy each ini file 😄

**Comment by infograf768** [comment]
Does it not have to be first done in the copy method?
```
			// Copy all files from $fromName template to $newName folder
			if (!Folder::copy($fromPath, $toPath) || !$this->fixTemplateName())
			{
				return false;
			}
```
I.e. creating a new `language` folder to `$toPath` containing the necessary files from the core language folder, and this for every language installed.

**Comment by Bakual** [comment]
The copy there just copies the whole template folder. The custom stuff is done in the fixTemplateName as it looks. Maybe it would make sense to create a new method which copies the language files if needed?

**Comment by infograf768** [comment]
> Maybe it would make sense to create a new method which copies the language files if needed?

And create the folder.
That would be the easiest to maintain as it is not a 2 lines of code (every installed languages + taking care of with/without prefix).

**Comment by Bakual** [comment]
I have a broad idea how it could be done. I'll try if I can do something this weekend.

**Comment by infograf768** [comment]
There are other assets to take care of, i.e. in `media/templates/nameoftemplate`

See https://github.com/joomla/joomla-cms/issues/26259#issuecomment-619485870

**Comment by Bakual** [comment]
Please test https://github.com/joomla/joomla-cms/pull/28813
