### ISSUE TITLE
[4.0] Password toggle - input focus bug

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28794]
### Steps to reproduce the issue

1. Go to the backend login page
2. Continuously toggle the password view button without having typed in a password

### Actual result

Clicking it once focuses on the password field.
Clicking it a second time doesn't focus on the password field and instead shows an error for the field

![login](https://user-images.githubusercontent.com/2019801/80281348-5725c980-8702-11ea-902b-7ccb2551c6e9.gif)

**Comment by jwaisner** [comment]
confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28794">issues.joomla.org/tracker/joomla-cms/28794</a>.</sub>

**Comment by brianteeman** [comment]
Please test #31775
