### ISSUE TITLE
Since Joomla 3.9.18 some pictures are turned around on EDITED BY MAINTAINER

### ISSUE THREAD

**Issue by lenoren** [joomla/joomla-cms#28805]
### Steps to reproduce the issue

Since Joomla 3.9.18 some pictures are turned around. 

See examples at // Deleted by maintainers

Before the last update all pictures were in the right direction.

**Comment by toivo** [comment]
spam<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28805">issues.joomla.org/tracker/joomla-cms/28805</a>.</sub>

**Comment by Quy** [comment]
Please ask help in Joomla Forums. https://forum.joomla.org/
