### ISSUE TITLE
[4.0] Module User Status missing for users not in viewlevel special

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#28804]
### Steps to reproduce the issue
Grant access to the backend for a usergroup which has not viewlevel "special", for example to usergroup registered. 
These user then can loign to the backend.
But cannot log out.

The module User Status should have viewlevel "public" per default. 

### Expected result
Every user who can login to the backend, also can log out 

### Actual result
![screen shot 2020-04-25 at 19 25 09](https://issues.joomla.org/uploads/1/1d36e512a29da897e3c5ff7372f668bb.jpg)

**Comment by chmst** [comment]
Just setting it public is not sufficient as the it appears also in the login screen. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28804">issues.joomla.org/tracker/joomla-cms/28804</a>.</sub>

**Comment by SharkyKZ** [comment]
Normally, if you change group permissions, access settings for items like modules should be changed accordingly. In your case using Registered access should be fine.

**Comment by SharkyKZ** [comment]
> Just setting it public is not sufficient as the it appears also in the login screen.

This should be fixed. The module isn't usable for guest users.

**Comment by brianteeman** [comment]
> Just setting it public is not sufficient as the it appears also in the login screen.

I guess we could edit the login template to remove the statusmodules

https://github.com/joomla/joomla-cms/blob/03a0ea4f5832446ed7840f14a72634f18e52326b/administrator/templates/atum/login.php#L118

**Comment by chmst** [comment]
Closing this - please test https://github.com/joomla/joomla-cms/pull/42254
