### ISSUE TITLE
[J!4.0]Article with page break - Article Index module has moved to the page

### ISSUE THREAD

**Issue by adj9** [joomla/joomla-cms#28801]
### Steps to reproduce the issue
- Creating an article with the page break
- I switch to the FrontEnd
- I go to the article
- I click on page break

### Actual result
the Article Index module has moved to the page.
The screan is
<img width="1428" alt="Schermata 2020-04-25 alle 17 57 05" src="https://user-images.githubusercontent.com/5918444/80285095-cd3a2880-8722-11ea-85de-8aa9cf627d9e.png">

### Expected result
the Article Index module waits for it to be aligned and the login for example

**Comment by SharkyKZ** [comment]
Article Index is not a module. It's coming from article layout.

**Comment by SharkyKZ** [comment]
Closing as expected behavior.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28801">issues.joomla.org/tracker/joomla-cms/28801</a>.</sub>
