### ISSUE TITLE
[4.0] {loadmoduleid} or {loadposition} don't work

### ISSUE THREAD

**Issue by web-eau-net** [joomla/joomla-cms#28819]
### Steps to reproduce the issue
1. activate the plugin content - Content - Load Modules
2. use the syntax {loadmoduleid ..} or {loadposition ...} in an article

### Expected result
Display a module in an article

### Actual result
Nothing happen

### System information (as much as possible)
Joomla 4.0 Beta 1 Development

**Comment by alikon** [comment]
should be fixed by this #28278 and will be available on j4.0-dev branch when 3.9.17 will be synched

**Comment by web-eau-net** [comment]
Gracie Nicola<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28819">issues.joomla.org/tracker/joomla-cms/28819</a>.</sub>

**Comment by devjoomla** [comment]
Actually, one other thing is found, that is, added phocamap and other map components, and tried to use their plugin codes to insert map into article, but it just showed plugin code only, not sure if it is issue from joomla or from extensions, other plugins like jw_ts i.e. slides and tabs plugin generates output properly as needed, but map plugins do not generating any output and only shows plugin insertion code as its in article.
