### ISSUE TITLE
[4.0] RFC Atum template - Change modal Messages

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28810]
### What needs to be fixed
The modal save messages are really very distracting and as far I remember they also had a11y issues? I could not find an open issue about that but can we please go back to inline messages?

It will be very tedious in the daily workflow to always have the modal overlapping for example the "New" button. 

Can we find a better solution?

**Comment by zero-24** [comment]
I agree on that.

Here an proposal:
- What about introducing a option in the "enque message" that the developer can switch between that message and such kind of messages:

![image](https://user-images.githubusercontent.com/2596554/80306270-7edc6680-87c2-11ea-9f66-f8de224017bc.png)

For sure you should force error messages to the big error messages but success messages can be use smaller things.

What do you think.

**Comment by zero-24** [comment]
That message could disapper after X time, when specified by the developer

**Comment by Quy** [comment]
See PR #27213

**Comment by coolcat-creations** [comment]
Thank you for leading me to the PR, but it actually only makes the modal disapear after a while... I think the better solution would be either having it inline or not distracting at the bottom right side...

**Comment by brianteeman** [comment]
It would not be a good solution to have the messages in multiple places depending on the level of message and you absolutely want an error or warning to be distracting

**Comment by zero-24** [comment]
> It would not be a good solution to have the messages in multiple places

hmm what would be your suggestion to that?

**Comment by PhocaCz** [comment]
Hi,

I like the way Gantry 5 goes. It just displays the message in the bottom right area and it will be hidden in a few seconds.

![Gantry5 Message](https://i.imgur.com/dwS1ODk.png)

Messages displayed in the bottom right area do not delay you at work and do not bind you anyway. Mostly there is nothing to do in the bottom right area.

Ok, if hiding a message could be a problem, e.g. regarding a11y, then messages should be displayed the same way like in Joomla! 3 because the current display, where part of the text and part of the buttons are hidden, definitely violates more rules.

![Standard Message](https://i.imgur.com/V21H5fo.png)

Jan

**Comment by brianteeman** [comment]
> Messages displayed in the bottom right area do not delay you at work

That's fine for a success but not for an error. When its an error it must be displayed prominently.

**Comment by zero-24** [comment]
Yes for that reason i proposed a switch in the inject method so you can have a different display when it is an error or success message

**Comment by mbabker** [comment]
Please do not introduce conditional styling based on the message level.  That’s just more confusion in the end.

**Comment by infograf768** [comment]
Imho, we should go back to the same behavior as in 3.x
Inline on top

**Comment by PhocaCz** [comment]
So, is there anything against using the same style like in Joomla! 3? (standard block at the top)

**Comment by richard67** [comment]
+1 from me for same style as in Joomla! 3 (standard block at the top).

**Comment by coolcat-creations** [comment]
+1 for J3 Style

**Comment by ReLater** [comment]
Not the first time I say:
+1 for J3 Style

**Comment by PhocaCz** [comment]
![J4 messages](https://i.imgur.com/XPnIpK1.png)

**Comment by ChristineWk** [comment]
I also don't like these overlapping messages:

![pr28810 ](https://user-images.githubusercontent.com/15275917/80319965-b45d7000-8813-11ea-95d2-da7ff1d42c21.JPG)
![pr28810_warning](https://user-images.githubusercontent.com/15275917/80319967-b7f0f700-8813-11ea-961d-64b1efb77ea2.JPG)
OK, the Alert messages in red of course - don't have at the moment :-)

@PhocaCz Jan
it's much better, but as @zero-24 says: ... success messages can be use smaller things.

**Comment by coolcat-creations** [comment]
What do we need to go back to J3 Style?

**Comment by ciar4n** [comment]
PR created... #28824

**Comment by zero-24** [comment]
Thanks. Closing here so we can test the PR. Thanks @ciar4n
