### ISSUE TITLE
[4.0] RFC Template Atum - Usage of badge colors

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28811]
Is there any reason why the information-badges in language install have a badge-warning class?
May I change it to badge-info ?

<img width="705" alt="grafik" src="https://user-images.githubusercontent.com/828371/80306188-fb227a00-87c1-11ea-9ac9-68a9839c7410.png">

<img width="396" alt="grafik" src="https://user-images.githubusercontent.com/828371/80306210-260cce00-87c2-11ea-974c-2217038ea34e.png">

**Comment by zero-24** [comment]
👍 from me can you send a PR for this?

**Comment by Quy** [comment]
It is a warning. Hover cursor over i icon to read message.

**Comment by coolcat-creations** [comment]
Ah I understand now, thank you - closing :-)
