### ISSUE TITLE
[3.9] In the message about JED, the link to ToS is broken

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#28818]
### Steps to reproduce the issue
On the **Extensions: Install** tab, there is an broken link in the JED message.

`COM_INSTALLER_INSTALL_FROM_WEB_TOS="By selecting "_QQ_"Add Install from Web tab"_QQ_" below, you agree to the JED <a class="_QQ_"alert-link"_QQ_" href="_QQ_"https://extensions.joomla.org/tos"_QQ_" target="_QQ_"_blank"_QQ_">Terms of Service</a> and all applicable third party license terms."`

Broken link:
[https://extensions.joomla.org/tos](https://extensions.joomla.org/tos)

Please change the link in the language constant or make the correct redirection.
Thank.

**Comment by brianteeman** [comment]
It really would be better if that link was fixed instead of changing the strings as not all languages are always upto date

**Comment by zero-24** [comment]
That has been reported to the JED already and will be fixed.

**Comment by conconnl** [comment]
PR created to fix the redirect in JED site code, will be deployed in the morning when the rest is awake.

**Comment by brianteeman** [comment]
Closed as resolved - thanks

**Comment by Kostelano** [comment]
In fact, this has not yet been decided :).

**Comment by brianteeman** [comment]
@Kostelano I am not sure what you mean. The link works now - I just confirmed

**Comment by Kostelano** [comment]
@brianteeman, I don’t quite understand ...
Now the link [https://extensions.joomla.org/tos](https://extensions.joomla.org/tos) (from language file) is redirected to [https://extensions.joomla.org/about-jed/terms-of-service](https://extensions.joomla.org/about-jed/terms-of-service) and gives it away:

![Screenshot_2](https://user-images.githubusercontent.com/8440661/80800104-52a15b00-8bb1-11ea-96f2-1df276ea1f5b.png)

**Comment by brianteeman** [comment]
When I click on the link i am redirected to https://extensions.joomla.org/community/terms-of-service/

![image](https://user-images.githubusercontent.com/1296369/80800499-896f7500-8ba1-11ea-9733-92840d30f7b5.png)

**Comment by Kostelano** [comment]
Sorry ... cache :) Everything works.
Sorry to distract.
