### ISSUE TITLE
[4.0] Template Atum - Usage and names of the Joomla Logo and Custom Logo

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28826]
### What needs to be fixed

We have currently in template Atum the different logos:

logo-joomla-white.svg
logo-joomla-blue.svg
logo-blue.svg
logo.svg

- The logo.svg is defined or used in:
login.php
error_full.php
index.php
error_login.php

But for examplate it's defined in index.php but not apparently not used there.

- Then there is the logo-blue.svg which is used in login.php in a different size as in index.php.
where logo-blue is the Joomla brandmark and logo-joomla-blue.svg is the full logo.

- The naming ist not logical and the usage of the logos is confusing, The logos need renaming, research where what is used and cleaned up. The names should be more general and contain their usage. For example something like logo-login-form.svg logo-header-collapsed.svg, logo-header-expanded.svg ... and so on. Since they can be coloured they don't have to contain a color name, since they can be changed after a template copy they should not contain "joomla" in it's file name.

- The usage of a custom logo in the template stile has to be corrected like reported by @micker

- The size of the svg should be defined in the svg itself and not in the scss like reported by @C-Lodder 

I can work on this issue just dropping it in here as an issue to have a worklist-item.

**Comment by micker** [comment]
hello i test with logo in login screen
![image](https://user-images.githubusercontent.com/2539440/80368699-6c7b2f00-888d-11ea-9646-9de1d03325cb.png)
i think max-height can be set to 2.3rem;
no header changing better alignement with link menu on right

**Comment by micker** [comment]
in menu collapsed and if i use mini logo
![image](https://user-images.githubusercontent.com/2539440/80368949-c7148b00-888d-11ea-8720-376a66c21c0a.png)
its better but i think we can center it in heigh and width

**Comment by micker** [comment]
same think in opnned menu, heigher max-height seams better
![image](https://user-images.githubusercontent.com/2539440/80369084-fc20dd80-888d-11ea-9eac-197d78f126b7.png)

**Comment by coolcat-creations** [comment]
> in menu collapsed and if i use mini logo
> ![image](https://user-images.githubusercontent.com/2539440/80368949-c7148b00-888d-11ea-8720-376a66c21c0a.png)
> its better but i think we can center it in heigh and width

yes I think that the brandmark needs a better alignment too, thank you!

**Comment by fevangelou** [comment]
Since you're at it, the Joomla logo is now visible as "Jooma". The SVG that was produced for the logo is surely not optimal. Here's how it looks on today's build from commit with ID: https://github.com/joomla/joomla-cms/tree/08b27e74737f859c6a873c661df268ca4a7f148b

![Screen Shot 2020-04-27 at 18 55 23](https://user-images.githubusercontent.com/1301787/80393658-7a46a980-88b9-11ea-8e5f-e2497bce2503.png)

**Comment by fevangelou** [comment]
Disregard my previous comment as it was a stuck cached copy showing up from before the update to today's snapshot.

![Screen Shot 2020-04-27 at 19 03 38](https://user-images.githubusercontent.com/1301787/80394005-ec1ef300-88b9-11ea-8936-ea10a3d6e392.png)

Still, it could use some really minor spacing between the letters (which would require a different SVG file altogether), if it's to display at such a small size OR it should be bumped from 1.3 to something like 1.8 rems. For example:

![Screen Shot 2020-04-27 at 19 06 28](https://user-images.githubusercontent.com/1301787/80394258-49b33f80-88ba-11ea-84b1-0376b9eff01e.png)

**Comment by coolcat-creations** [comment]
@fevangelou Thank you! Well, I will not be able to change the registered Joomla Logo but I'll see how to fix the Dimensions to make it appear better :-)

**Comment by coolcat-creations** [comment]
Closed because of the PR  #28839
