### ISSUE TITLE
[4.0] Display a blog on 2 or more columns

### ISSUE THREAD

**Issue by web-eau-net** [joomla/joomla-cms#28821]
### Steps to reproduce the issue
1. create a menu item blog articles category or articles featured
2. try to setup the display on 2 columns in the parameters (tab Layout)

### Expected result
Display the articles on 2 or more columns on frontend

### Actual result
Impossible to setup, there's no option :(

### System information (as much as possible)
Joomla 4.0 Beta 1

### Additional comments
As in J3 serie, this basic feature for a blog layout must be included in J4 serie. The end user mustn't spent hours to understand how to do it.

**Comment by brianteeman** [comment]
See the release blocker #27478 closing as a duplicate
