### ISSUE TITLE
Error in form validation on J4.

### ISSUE THREAD

**Issue by KarstenFrostholm** [joomla/joomla-cms#28836]
### Steps to reproduce the issue
using a class ComponentnameRule extends FormRule on this path C:\j4dev\htdocs\administrator\components\com_zzzz\src\Rule\ComponentnameRule.php

with xxxxx as vendor and zzzz as component name,  I can't make it work. 

### Expected result
Its work

### Actual result
Not work
It always ends with Joomla\CMS\Form\Field\TextField::validate() rule `componentname` missing.

### System information (as much as possible)

Using xampp with php 7.43 running on windows 10.
Joomla_4.0.0-beta1-dev-Development-Full_Package built: Monday, 27 April 2020 02:00:23 UTC

### Additional comments

with joomla as vendor and zzzz as component name, its work

From my edit form: 

<?xml version="1.0" encoding="utf-8"?>
<form
    addfieldprefix="xxxxx\Component\zzzz\Administrator\Field"
    addruleprefix="xxxxx\Component\zzzz\Administrator\Rule"
>

    <field
        name="name"
        type="text"
        ...
        validate="componentname"
        required="true"
    />

***********
From top of the validates Rule source:

namespace xxxxx\Component\zzzz\Administrator\Rule;

\defined('_JEXEC') or die;

use Joomla\CMS\Form\FormRule;

/**
 * Form Rule class for the Joomla Platform.

 */
class ComponentnameRule extends FormRule
{

Karsten

**Comment by SharkyKZ** [comment]
I can't reproduce the issue. Did you add `addruleprefix="xxxxx\Component\zzzz\Administrator\Rule"` attribute to your form?

**Comment by KarstenFrostholm** [comment]
Sorry this did not come up in a bug report from the draft:

**It looks like it was for the first time but is being eaten by the system**

    addfieldprefix="xxxxx\Component\zzzz\Administrator\Field"
    addruleprefix="xxxxx\Component\zzzz\Administrator\Rule"


**have you tried xxxxx as a vendor, not jooml**

It was very clear that only joomla as a vendor works. That was the only correction.
**xxxxx has been used as a vendor throughout the component.**
**When my code works, joomla is used throughout the component.**

**Comment by SharkyKZ** [comment]
I changed the namespace of `com_contact` to `MyVendor\Component\Contact`. Still can't replicate the issue.

**Comment by KarstenFrostholm** [comment]
I do code generation so switching Vendor is easy and I've tried it again and now it works. I'm very confused.
Thank you for checking this matter.
Sorry for wasting your time.
**We are going to close this case.**
