### ISSUE TITLE
[4.0] System Dashboard Color Inconsistancy with Installation Messages

### ISSUE THREAD

**Issue by jwaisner** [joomla/joomla-cms#28845]
### Steps to reproduce the issue

Navigate to the System Dashboard on the backend on a clean install.
Notice the counter for "Installation messages" does not match the "Post Installation" counter at the top right.

### Expected result

Consistent color between the two counters (both red or both yellow)

### Actual result

![image](https://user-images.githubusercontent.com/12568201/80418212-a69ffd00-889c-11ea-9496-d5715cd96ff1.png)

**Comment by coolcat-creations** [comment]
The post installation messages have the danger badge - actually it's not an error or danger but probably even only an information.

I am not sure which color it should have... Neutral or warning?

**Comment by jwaisner** [comment]
I would say it should be set to "Warning". Still draws attention as the messages are important but not "danger" level important.

**Comment by adj9** [comment]
I also find the yellow count in the database entry.
<img width="311" alt="Schermata 2020-04-28 alle 21 19 39" src="https://user-images.githubusercontent.com/5918444/80528590-78064d00-8996-11ea-8bab-00a156a71552.png">

The different color in my opinion can be fine to make a difference with the most important items at the top of the Joomla! backend

**Comment by Quy** [comment]
This will not be an issue with PR #33100.

![28845](https://user-images.githubusercontent.com/368084/115085400-57911480-9ebf-11eb-9f9b-49f4271b3bfd.jpg)

**Comment by Quy** [comment]
Closing as no longer an issue.
