### ISSUE TITLE
[4.0] Switch between Styles and Templates

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#28844]
### Describe the solution you'd like
Hi,
in Joomla! 3 there is an easy way to switch between Styles and Templates in administration, see image:

![Templates - Styles 3](https://i.imgur.com/rSodDDi.png)

I cannot find any such option in Joomla! 4

![Templates - Styles 4](https://i.imgur.com/kQ0GLo6.png)

Is there some way to do the same like in Joomla! 3?

Thank you, Jan

**Comment by SharkyKZ** [comment]
Use Alternative admin menu preset.

**Comment by coolcat-creations** [comment]
From styles you can very easy click on the template logo to get into the template. It would be great to have a link to the styles in the template area. Absolutely needed UX change.

**Comment by Quy** [comment]
Duplicate #26409

**Comment by infograf768** [comment]
Do you want something like this?
<img width="1128" alt="Screen Shot 2020-04-28 at 09 47 09" src="https://user-images.githubusercontent.com/869724/80461272-4f9a3680-8935-11ea-9482-a7d3816c3fd8.png">

**Comment by coolcat-creations** [comment]
Looks good for me - at least for the Templates. 
Thinking about how to do a more "scaleable" approach. 

For example in Languages, would we there have a dropdown button with links to "manage, install, overrides,..." ?

**Comment by PhocaCz** [comment]
Those changes need to be more complex. In version 3, you go somewhere and you have the option to switch immediately. In version 4, it's as if you're always in a dead end.

See version 3 (I navigated to Styles and have two links to go to Templates available):

![Links](https://i.imgur.com/xFyPaQq.png)

In version 4, I don't see any other option than go back to dashboard (no left menu, no top menu, no breadcrumbs):

![Links](https://i.imgur.com/Dt1Zr2n.png)

I am just lost in dead-end street and need to go back.

**Comment by infograf768** [comment]
It is as easy as I did for templates to styles above, to add a toolbar button to switch to Templates from Styles.

**Comment by PhocaCz** [comment]
Yes, I understand, but I described the situation in general (this happens in many places in Joomla! 4), so it would mean that we would have to supply buttons at every point at the "dead-end street". But this is a possible unnecessary replacement for a missing menu or missing navigation (breadcrumbs).

**Comment by PhocaCz** [comment]
Analogous - I am inexperienced user and always go to plugins instead of modules and to modules instead of plugins.

In Joomla! 3 I have a quick way to switch to right place:

![3](https://i.imgur.com/0425mdK.png)

In Joomla! 4 I need to go back to dashboard and start my way from beginning:

![4](https://i.imgur.com/GMp2mR6.png)

It terribly delays work if I find myself at the end without being able to change my path quickly and need to go back to start.

**Comment by infograf768** [comment]
@PhocaCz 
As stated by @SharkyKZ https://github.com/joomla/joomla-cms/issues/28844#issuecomment-620221124
you can switch to the alternate admin menu. It is not as easy indeed as 3.x because someone has decided to create this sidebar, but it works fine.

Example:
<img width="304" alt="Screen Shot 2020-04-28 at 12 20 25" src="https://user-images.githubusercontent.com/869724/80476474-b8d87480-894a-11ea-83f8-c9dc360cadc0.png">

**Comment by PhocaCz** [comment]
@infograf768

Thank you for this info.

It reminds me of a situation with the start menu in Windows. They removed the start menu and everyone tried to replace it with something else. Many different extensions, many different hacks, etc. 

So we will look for an infinite number of nonsensical alternative solutions and hacks when we come to the conclusion, why not use what everyone knows and what everyone expects?

**Comment by PhocaCz** [comment]
Anyway, can someone point me to the place where i can switch to alternative admin menu?

Thank you.

**Comment by coolcat-creations** [comment]
Building an alternate Backend Menu is really hard in terms of UX ... 
I just give you a first hint, @PhocaCz - go into Menüs, create a new Menu in Administrator context - then please note the steps you are stumbling over...

**Comment by PhocaCz** [comment]
@coolcat-creations Thank you, it seems that easier way will be participation on external solution:

![menu](https://i.imgur.com/gaP21wp.png)

Thank you, Jan

**Comment by infograf768** [comment]
Can you share this code?

**Comment by infograf768** [comment]
Got it
https://github.com/joomla/joomla-cms/issues/26409#issuecomment-620798581

**Comment by PhocaCz** [comment]
Ok

**Comment by PhocaCz** [comment]
... continuing #26409 in this tread

The top menu is RTL ready, but there need to be done some hacks, because it seems that core Atum library:
administrator/templates/atum/css/template-rtl.css

includes bugs regarding RTL and dropdown-toggle classes. For now, J!4 does not use these classes so it seems nobody tested it (the classes are just copied from template.css but they should have reverse notation: ::after -> ::before, ::before -> ::after)

But this can be overriden in top menu css.

RTL:
![ltr](https://i.imgur.com/sTmGv6X.png)

LTR:
![rtl](https://i.imgur.com/FRd90mL.png)

**Comment by infograf768** [comment]
> includes bugs regarding RTL and dropdown-toggle classes. For now, J!4 does not use these classes so it seems nobody tested it (the classes are just copied from template.css but they should have reverse notation: ::after -> ::before, ::before -> ::after)

This is interesting. I wonder how we could test this with present atum.
I tried to add a dropdown toolbar button with multiple urls choices to direct to other managers and failed for the moment.
Example: in Languages we would have such a dropdown Toolbar button with links to Content Languages, Overrides, Installed languages, Install languages, depending on which Manager we are.

**Comment by coolcat-creations** [comment]
Does this make sense to have two seperate core system menu structures? Or do I misunderstand the top menu? For me as a new user who want to administrate Joomla it would be completely confusing what I see here in your screenshots.

**Comment by PhocaCz** [comment]
> Does this make sense to have two seperate core system menu structures? Or do I misunderstand the top menu? For me as a new user who want to administrate Joomla it would be completely confusing what I see here in your screenshots.

1) The top menu is not a part of core, so it will be installed by administrators who really know why they do it

2) The top menu includes all menu items, like link to Media manager, link to all extension functions, etc.
![extension](https://i.imgur.com/PVFNRV9.png)

3) It is a desktop feature. Even it is based on Bootstrap and works on mobile, the main function is to add complete menu for desktop administrators

4) Unfortunately I don't have any time to make record of my work in administration but if I do and will compare the work with and without top menu, you will see the huge time difference when administrating Joomla!

5) Example 'Styles and Templates' just shows the weak point of current Joomla! 4 menu. In Joomla! 3 there were two easy ways to switch between the items (in top menu or in sidebar menu). Both were removed in Joomla! 4. So for now users have 2 options in Joomla! 3 but zero option in Joomla! 4. Until this will be solved, there will be users searching for the alternative and please, it is not about me or my needs, I just participate on alternatives and needs which have existed for a long time and may have their requirements increase significantly after the release of stable.

6) For now I don't know if it is possible, but it can even happen, that there will be a demand for return of Joomla! 3 sidebar menu to Joomla! 4. If so, then the top menu will be indispensable (please we still speaking about hypothetical external extensions which will not affect core).

This topic is closed and in fact for now it does not have anything to do with core. But I continue here with information about the possibility to have top menu when needed by someone. The original extension exists and can be downloaded, I have made some changes (removed Smartmenus library, added option to have click and hover event, changed design to follow Joomla! 4 design and changed design to work in RTL) so maybe it will be better to release it as another extension (I am in contact with author of the original extension, so we will see).

So this top menu alternative does not affect new users. It is here for "old-fashioned desktop administrators" and if there will be no need to install it, it will be lost in time :-)

**Comment by coolcat-creations** [comment]
Sorry but this does not work for me. We need to make the backend usable for new users too. We need to make the other System Menu items from the same group accessible faster than with "10 clicks". 
What about displaying the groups that are in the panels in the sidebar? Even if it's long, but it would be there at least?

**Comment by PhocaCz** [comment]
@infograf768 
The dropdown feature is not more used in Joomla! 4, it is used in Joomla! 3 and there the RTL version is correct:

![arrows](https://i.imgur.com/0GqLOq5.png)

In fact it is only about switching :after (arrow is displayed on left side) and :before (arrow is displayed on right side) 

So switching from .dropdown-toggle::before to .dropdown-toggle::after in RTL just does the trick:

![rtl](https://i.imgur.com/cQkcwBU.png)

**Comment by PhocaCz** [comment]
> Sorry but this does not work for me. We need to make the backend usable for new users too. We need to make the other System Menu items from the same group accessible faster than with "10 clicks".
> What about displaying the groups that are in the panels in the sidebar? Even if it's long, but it would be there at least?

This is the question on core developers. Unfortunately my feedback to menu system in Joomla! 4 is just no accepted or different, so the only way for me is to improve alternatives for users who think the same way as me. Wit top menu (hover enabled) I can access "Styles" with one click, without top menu with two clicks plus waiting until system dashboard is updated.

![system dashboard](https://i.imgur.com/a0wMjcq.png)

**Comment by coolcat-creations** [comment]
Yes but than the top Menu needs to have at least the same structure as the main menu, even if with subitems but the structure should be consistent.

**Comment by PhocaCz** [comment]
It is up to you. The screenshots here are based on alternative menu, if you switch to main menu in module:

![switch](https://i.imgur.com/PPxLDUd.png)

you will just have main menu in top menu displayed:

![main menu](https://i.imgur.com/AWBp9po.png)

etc. etc.
Preset - Help Dashboard
![help](https://i.imgur.com/pd5szPk.png)

Preset - User Dashboard
![user](https://i.imgur.com/v05eKlZ.png)

You can just display on top position every menu you need. If you are desktop administrator, you will just select alternative main menu to have all the items in menu.

It has nothing to do with confusing new users, it is external module for users who know what they do.

**Comment by PhocaCz** [comment]
Anyway, you can do this in core for now (without any external module), but the result is following:
![top menu](https://i.imgur.com/Vok91Cv.png)

So the external module just cares about right displaying/right design/right function (hover or click event) of the top position menu. Nothing more. This feature to display something in top is just a core feature.
