### ISSUE TITLE
**SOLVED*** Cannot install a PACKAGE after uninstalling a PACKAGE -- AFTER 3.9.16 --> 3.9.18 upgrade

### ISSUE THREAD

**Issue by cyberspyderms** [joomla/joomla-cms#28846]
### Steps to reproduce the issue
Uninstall a **package** and try to install it back or another **package**. Installing from URL works, but not upload from folder or basic upload package.

### Expected result
Uninstalling something shouldn't break future uploading capability.

### Actual result
Upload, except install from URL, breaks after uninstalling something. _Installing/uninstalling PLUGINS doesn't seem to be affected or affect anything else._

### System information (as much as possible)
Attached is a FPA (forum post attachment) from the forum on a site with this issue but it happens on all sites, that I've tested.

### Additional comments
We currently have 150+ Joomla sites and this is a big problem for us that was discovered accidentally when trying to repair a bad update of SpeedCache (Joom United). In troubleshooting, the first step sometimes is to uninstall the update and then reinstall the new version clean. After uninstalling, we could not install anything else to the site. We've since testing uninstalling other items from other sites and afterwards, the upload is broken. Reinstalling Joomla from upgrade menu and also via FTP overwrite didn't fix the issue.

[FPA.txt](https://issues.joomla.org/uploads/1/81317f2b9ccbe2fa56175e141dd0a146.txt)

**Comment by jwaisner** [comment]
@cyberspyderms can you provide some more information such as the error message that would indicate that it isn't working. Also, have you cleared the cache on the websites?

**Comment by brianteeman** [comment]
What is the component as it sounds like a problem with that. I regularly uninstall and re-install the same component without any issue

**Comment by cyberspyderms** [comment]
@jwaisner There is no error message given. The install icon "spins" and the upload/install page simple reloads with no success or error message provided. Yes, all site cache was cleared. We've been doing Joomla sites for about 15 years now and this is something new to us and has only appeared since the last .16 to .18 update.

**Comment by cyberspyderms** [comment]
@brianteeman I have uninstalled several different components/packages on different sites and also tried to install another component/packages on them. The problem occurs once a component/package is uninstalled, nothing else can be installed on that site.
True, that this was first noticed when troubleshooting a specific component (simply uninstalling and trying to reinstall a clean/new version instead of an on-site updated version)m but was not able to install anything after the uninstall. We've since verified this issue with other components/packages. Once anything is uninstalled, nothing else can be installed by normal methods, except as mentioned by URL.

**Comment by brianteeman** [comment]
I just double checked one of my sites. I uninstalled akeeba backup and then reinstalled akeeba backup with no problem at all

**Comment by cyberspyderms** [comment]
@brianteeman That's good to know, but doesn't solve our issue. :-) If you've got a way to get you login info securely/privately, I'll set you up, if you wouldn't mind taking a look.
We could understand this on maybe one or even two sites, but it happens on every site that we check on.

**Comment by brianteeman** [comment]
well you never said what the extension is so I couldnt check that extension

sorry but I dont look at specific sites except on a commercial basis

**Comment by Quy** [comment]
@cyberspyderms Please ask help in Joomla Forum. https://forum.joomla.org/viewforum.php?f=710

**Comment by cyberspyderms** [comment]
@brianteeman I understand about working on sites.
I did specify that we had tried several different extensions on several different sites and in the Additional Comments, I listed "problem for us that was discovered accidentally when trying to repair a bad update of SpeedCache (Joom United)" However, we tried uninstalling something different on a site that has never had that extension installed on it and was not able to install anything afterwards. Plus, on sites that don't have that extension and those that do, we are able to install like normal, until anything is uninstalled.

**Comment by cyberspyderms** [comment]
@Quy - I have earlier today - https://forum.joomla.org/viewtopic.php?f=708&t=979692 Just now looking at some comments there.

**Comment by jwaisner** [comment]
As this is related to a 3dp application and not core,closing. Please refer to the forum for assistance with 3dp issues.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28846">issues.joomla.org/tracker/joomla-cms/28846</a>.</sub>

**Comment by cyberspyderms** [comment]
This is not specifically related to a single 3dp, but happens on every Joomla site that we've checked on since the update to .18

**Comment by HLeithner** [comment]
@cyberspyderms plz send me credentials and website to harald.leithner@community.joomla.org

**Comment by infograf768** [comment]
Tks @HLeithner for looking at this.

**Comment by cyberspyderms** [comment]
Thanks, Harald.
I am adding you on three sites and will email you the info about each so you can take a look.

 

 <https://www.cyberspyder.net/>

**Comment by cyberspyderms** [comment]
With the help of @HLeithner we've been able to determine this so far - in regards to this issue:
This issue seems to arise, after the 3.9.18 upgrade and seems to be only affecting installation of packages, once a package has been uninstalled. Plugins seem to be OK and not causing anything to break.
Will post more updates as we figure them out as we're communicating directly via email at this point.

**Comment by brianteeman** [comment]
I  tested with akeeba backup and that is a package and there was no problem at all - so what is the package that is failing

**Comment by toivo** [comment]
It was mentioned in "Additional Information", a paid extension: [SpeedCache by Joom United](https://extensions.joomla.org/extension/speed-cache/ "SpeedCache by Joom United")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28846">issues.joomla.org/tracker/joomla-cms/28846</a>.</sub>

**Comment by ReLater** [comment]
@toivo 
> It was mentioned in "Additional Information", a paid extension: SpeedCache by Joom United

We have also this [comment](https://github.com/joomla/joomla-cms/issues/28846#issuecomment-620256116)
 
> However, we tried uninstalling something different on a site that has never had that extension installed on it and was not able to install anything afterwards. Plus, on sites that don't have that extension and those that do, we are able to install like normal, until anything is uninstalled.

**Comment by cyberspyderms** [comment]
> I tested with akeeba backup and that is a package and there was no problem at all - so what is the package that is failing

@brianteeman - different packages as @ReLater mentioned above. In working with @HLeithner , we may have discovered that it may be related to our user account, as he is testing with us on a particular site with us (he has his own account) and is able to install/uninstall packages on the site, but we cannot install packages on the same site under our own account.
I'll keep everyone updated - stay tuned ...

**Comment by cyberspyderms** [comment]
To all (@brianteeman @ReLater @tolvo and especially @HLeithner )that have reached out - THANK YOU.
The root cause ended up being a corrupted file in Google Chrome on one specific PC and not any coding issues related to the update of J from .16 to 18 - even though it only appeared after the upgrade. Very strange timing indeed.

**Comment by brianteeman** [comment]
Glad you managed to solve it
