### ISSUE TITLE
[4.0] Template Atum - Menu Titles overlap clickable Area

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28840]
### What needs to be fixed
when the menu is collapsed I can't click for example on atum Style link
![grafik](https://user-images.githubusercontent.com/828371/80416560-9d328700-88d4-11ea-809c-7077da00ea90.png)
![grafik](https://user-images.githubusercontent.com/828371/80416575-a4f22b80-88d4-11ea-8927-7dcea4e87851.png)

### How would you fix it 
- maybe only small labels when the menu is collapsed?

**Comment by jwaisner** [comment]
Confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28840">issues.joomla.org/tracker/joomla-cms/28840</a>.</sub>

**Comment by rinka88** [comment]
I affirm.
In general, it is better to leave only icons when minimizing.
And the second when scrolling down, if there are a lot of modules on the board panel, the side menu goes up and this is wrong.
It must remain fixed

**Comment by coolcat-creations** [comment]
I think it speaks nothing against small badged that appear when hovering. Like Titles but styled...?
A fixed menu is a problem @rinka88 - you can customize the menu and it can get longer than the screen, how would you then manage to scroll to an item that is out of the viewport?

**Comment by rinka88** [comment]
I do not know about you, but my side menu is not fixed. And it will scroll along with the screen. Screen 15.6, resolution 1366 * 768
and in general terms of usability, I think you need to look through the [Khonsu ](https://github.com/joomla-projects/j4adminui/issues/186)admin area and select the best sides in Atum )
@coolcat-creations Have you seen the Khonsu admin area? If not, try it, take a look.

**Comment by coolcat-creations** [comment]
> @coolcat-creations Have you seen the Khonsu admin area? If not, try it, take a look.

Yes I saw it and it solves many issues we have, but unfortunately it's not meeting the requirements in Joomla.

> I do not know about you, but my side menu is not fixed. And it will scroll along with the screen. Screen 15.6, resolution 1366 * 768

Yes it's not fixed, probably because of the reasons I stated above...

**Comment by brianteeman** [comment]
This one is my fault in #27352
It is also the cause of #28260

**Comment by Quy** [comment]
See PR #29023
