### ISSUE TITLE
[4.0] No possibility to add a custom path in media field

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28852]
### Steps to reproduce the issue
If you want to define an own path in the media field it's not possible. 
It's not possible in the field itself which would increase speed of workflow for administrators and it's also not possible in the media manager to add a custom path, at least I can't find it anywhere...

![grafik](https://user-images.githubusercontent.com/828371/80458589-4e670a80-8931-11ea-9f22-838537f4b876.png)

### Expected result
Input should be allowed

### Actual result
Input is disabled
No possibility to add a path

**Comment by brianteeman** [comment]
> It's not possible in the field itself which would increase speed of workflow for administrators 

its also not possible in j3 (thats an observation not an explanation or excuse)

>  it's also not possible in the media manager to add a custom path,

You can add as many paths as you want now in joomla 4 using the FileSystem - Local plugin (again not saying its correct just explaining how)

**Comment by coolcat-creations** [comment]
> > It's not possible in the field itself which would increase speed of workflow for administrators
> 
> its also not possible in j3 (thats an observation not an explanation or excuse)

In some places it is possible in Joomla 3 (Article Intro Image for example) 
![grafik](https://user-images.githubusercontent.com/828371/80463401-7c038200-8938-11ea-8a76-1ece1294eedb.png)


> 
> > it's also not possible in the media manager to add a custom path,
> 
> You can add as many paths as you want now in joomla 4 using the FileSystem - Local plugin (again not saying its correct just explaining how)

For example to define a custom path in the template style settings in the image field - where can I input the custom path? Can you lead me to it?

**Comment by brianteeman** [comment]
I do not have that option in my joomla 3 article intro image
![image](https://user-images.githubusercontent.com/1296369/80464107-31cad280-8931-11ea-80ee-518656d556c9.png)

**Comment by coolcat-creations** [comment]
Oh sorry it's an enhancement by JCE MM ... I am already so used to it...
It's really useful to be able to add the path...

But still I don't know where in the new MM Modal can you add the custom path I did not find it? The old Media Manager (not JCE) has a path input in the modal...

**Comment by brianteeman** [comment]
> You can add as many paths as you want now in joomla 4 using the **FileSystem - Loca**l plugin (again not saying its correct just explaining how)

**Comment by ReLater** [comment]
> It's really useful to be able to add the path...

and copy/paste paths or change them quickly and so on...

**Comment by coolcat-creations** [comment]
> > You can add as many paths as you want now in joomla 4 using the **FileSystem - Loca**l plugin (again not saying its correct just explaining how)

I am not sure if we speak of the same thing... when I want to manually **write** something like media/foldername/imagename.jpg into the MediaManager - where could I do that?

For example here Joomla 3:

![grafik](https://user-images.githubusercontent.com/828371/80496791-f4366b80-8969-11ea-9b28-85eb85f6d7d8.png)

Background of my question: I often need to write there the link of a svg as it's not supported yet, also like @ReLater just stated I can quickly change the name of the path to -2.jpg or something if I want to insert a second version of the image ... etc.

**Comment by Razzo1987** [comment]
@coolcat-creations I found the same problem.
I joomla 3 I use sometimes an external image URL (CDN, autognerate image, ...)

**Comment by Razzo1987** [comment]
From API works correctly.
See: https://github.com/joomla/joomla-cms/pull/29020#issuecomment-629606509

**Comment by uglyeoin** [comment]
I would certainly use this

**Comment by dgrammatiko** [comment]
@coolcat-creations you just need to remove readonly attribute from the input eg: https://github.com/joomla/joomla-cms/blob/15c23c8f99421c54389f2edd7ef8229b6eeb3702/layouts/joomla/form/field/media.php#L161

BUT it's WRONG. It might enable some users to manually input any text but that text will never be validated either client side or server side. FWIW the readonly exists there as a way to validate the inputed data as there's nothing to verify something like `foobar` on the server side. In sort removing this, as you call it limitation I will call it a very well thought implementation, needs some magic either client side (eg is the path valid, is the file in the allowed list, etc) or server side or both.

**Comment by brianteeman** [comment]
and thats why we have the  FileSystem - Local plugin

**Comment by dgrammatiko** [comment]
> and thats why we have the FileSystem - Local plugin

No to mention that the new manager supports Dropbox, AWS S3, etc so basically covers all needs

Also creating a simple override and removing readonly is within anyone's reach 😉

**Comment by bcwang535** [comment]
Hi everyone, I just solved this need through [Razzo1987](https://github.com/Razzo1987)'s guidance, let me thank him first. 

Next, let me explain why this feature is still important to people like me. Basically, my hosting plan choice is less expensive, which means I have less node storage, so I always use existing web image assets, including the intro images. Furthermore, there will be multiple Joomla site mounted under my main domain, and I also want them to use the same image resources instead of uploading the same image once for each website.

Based on the above requirements, I think that via url to add intro image is still a very important function in Joomla4, I really hope this feature will be included in the official version in the future, thanks.

**Comment by dgrammatiko** [comment]
> Based on the above requirements, I think that viaurl to add intro image is still a very important function in Joomla4, I really hope this feature will be included in the official version in the future, thanks.

I'm against for the reasons I stated https://github.com/joomla/joomla-cms/issues/28852#issuecomment-692966112 and https://github.com/joomla/joomla-cms/issues/28852#issuecomment-692972999 
Also I already provided the [solution](https://github.com/joomla/joomla-cms/issues/28852#issuecomment-692966112) for those that want **TO COMPROMISE THE PERFORMANCE** of their sites by entering directly the url of the images (will be missing the width and height info thus no lazy loading)

**Comment by coolcat-creations** [comment]
This is against all usability, I can't tell you how often I need to paste the path because of migrating between sites or articles. If there must be a special path to increase performance, ok, but then let me paste a path and transform it into the weird format?

**Comment by dgrammatiko** [comment]
> but then let me paste a path and transform it into the weird format?

If you want to do it your way, as I said before, create an override of the media field layout and remove the `readonly` attribute. The core shouldn't ship broken things and thus a proper implementation requires as I said before quite more logic: validate the URL, get the image adapter, get the image dimensions. If you're willing to provide this functionality then you can have the non readonly input field in the core. BUT not without addressing the validation, adapter and dimensions. I hope this clears up why I'm against just removing the `readonly` attribute...

**Comment by coolcat-creations** [comment]
Sorry but I am not skilled enough to do something like this and feel pushed miles backwards as a user. 
What does this feature cost exactly so I can maybe organise a crowdfunding?

**Comment by dgrammatiko** [comment]
> so I can maybe organise a crowdfunding?

You know you can just create a PR removing the readonly attribute, so no crowdfunding is needed. Pretty sure it will also be accepted...

**Comment by alikon** [comment]
please test #36945

**Comment by bcwang535** [comment]
Haha, did I poke a hornet's nest?

Basically, Joomla4 is a very good CMS build tool, I like its flexibility and hierarchical permission control, which is why I choose it as the base of the website.

To talk a little about my background, I'm a UX/UI designer, and I know some interactive programming.

However, with my fairly rich design background, I still encountered many obstacles in solving the requirement of "using network images as Intro images". I will not discuss whether to restart this function here, because the views on both sides have their own basis for their arguments.

I was just from the perspective of a UX/UI user, and removing this function did make me have some doubts and needs to solve (compared to Joomla3).

Below I list my experience and solution steps so far, hoping to help general users at the same level as me, or even more outside the field.

`https://bcwgo.com/resource/html/joomla4-notice/enable-intro-image-via-web-link-function-in-joomla4.html`

**Comment by coolcat-creations** [comment]
@bcwang535 I don't know what you try to show in the screenshots but I appreciate your work to create and share :-)

So to summarize my problem:

1) As an admin I sometime migrate between articles and website-copies or speed up my workflow by copying a path and typing the image name myself. That all happens with relative paths, no absolute paths.

Example 1: Article A has images/general/intros/main/motors.jpg (just an example path, it's not a real one) as intro image, I need the same for article B so instead of: click, click, click, click, click - I do: right click, copy path, click paste path. 
It's a time saver!
Example 2: Website WP A needs to migrate some, but not all articles, left screen has the wp site open, right one the Joomla site. Almost same procedure as in Example 1, I just need to move a copy of the images to Joomla Media directory before (yes all, it's time saving) 
Example 3: I have some content using intro images like images/general/intros/main/motors-1.jpg, I know next article will have images/general/intros/main/motors-2.jpg, next one images/general/intros/main/motors-3.jpg and so on. I just copy paste the path instead of clicking gazzilion times.
Actually there are more examples where I need to paste a path.

The PR to remove the readonly, solves the symptom but leaves me hanging as a user to not take advantage of Lazy Load and other features. Isn't there a way to make it possible to past a path AND have the same abilities as selecting it manually? I really don't understand what has to be done in detail to make this happen.

**Comment by bcwang535** [comment]
@coolcat-creations My step-by-step screenshots just wanted to give someone less familiar with Joomla than me a clear guide to enabling web intro images, and all your needs can be executed, just replace it from second layer( the media selector ) to the first layer( Intro Image preview block ) of the article editing page, as for the "Lazy Load and other features" you mentioned, I have no experience and need help from other friends.
