### ISSUE TITLE
[4.0] Save and close not possible in Template Style (atum)

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28850]
### Steps to reproduce the issue
- Reset all Values in the Atum template (delete them) 
Click on Save and Close
An Error appears

- If you click just on save it works

![grafik](https://user-images.githubusercontent.com/828371/80457877-4b1f4f00-8930-11ea-8f1e-282f1596a7d9.png)

**Comment by brianteeman** [comment]
Confirmed

**Comment by Quy** [comment]
Related #26639

**Comment by Quy** [comment]
Please test PR #28897

**Comment by SharkyKZ** [comment]
Re-opening as #28897 won't solve this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28850">issues.joomla.org/tracker/joomla-cms/28850</a>.</sub>

**Comment by SharkyKZ** [comment]
The issue is specific to Color field. Its JS adds `pattern` attribute which forces validation:

https://github.com/joomla/joomla-cms/blob/8c1f5be8354ba26f5eb955461227eee239ec899e/build/media_source/system/js/fields/joomla-field-color-slider.es6.js#L195

I don't know if this is intentional or not.

**Comment by brianteeman** [comment]
I can not replicate this any more. Perhaps a change has been made elsewhere

**Comment by Quy** [comment]
Closing as no longer reproducible.
