### ISSUE TITLE
[4.0] Quick Icons - Wrong label or wrong Link for Template Styles

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28851]
### What needs to be fixed
If you click on Templates in the Quick Icon section you end up in Template Styles.

![grafik](https://user-images.githubusercontent.com/828371/80458310-e284a200-8930-11ea-8586-fd0786c88a94.png)

_(Sidenote: That is already very confusing in Joomla 3 when you click on Templates you end up there and when you click on Extensions » Manage you end up in Extensions » Install - that's something I need to explain in every training)_

### Why this should be fixed
It's confusing 

### How would you fix it
Renaming it to Template Styles and leave the link like it is

**Comment by brianteeman** [comment]
Far better to get rid of the two pages for templates and integrate them as one as was done in the proposal at https://github.com/joomla-projects/j4adminui

**Comment by coolcat-creations** [comment]
If possible of course it would be great

**Comment by chmst** [comment]
Getting rid of the two pages would be best solution. Alternative simple change of the button text #28854<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28851">issues.joomla.org/tracker/joomla-cms/28851</a>.</sub>

**Comment by Quy** [comment]
Related #25916

**Comment by Quy** [comment]
@coolcat-creations Close?

**Comment by coolcat-creations** [comment]
The text has been changed and merged so yes this can be closed :-)
