### ISSUE TITLE
[4.0] Complete SQL Statements in Debug area

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#28857]
### Is your feature request related to a problem? Please describe.
In J3.9 you can use the Debug area and see SQL Statements. 
![sql-39](https://user-images.githubusercontent.com/1035262/80477446-3781e180-894c-11ea-8b52-ac5c758e48fa.JPG)

This makes it easy to see, if the values are correct. 

In 4.0, we see only the prepared statement and cannot know if the parameters are correct:

![sql-40](https://user-images.githubusercontent.com/1035262/80477555-6c8e3400-894c-11ea-93f5-8f4b55422935.JPG)

### Describe the solution you'd like
It sould be as in Version 3.9, the SQL statement should be shown when it is complete, with variables, or at least the values of variables should be displayed together with the query.

**Comment by Quy** [comment]
Duplicate #26135
