### ISSUE TITLE
new Router NoMenuRules is parsing urls wrong

### ISSUE THREAD

**Issue by julienV** [joomla/joomla-cms#28858]
### Steps to reproduce the issue
create a router with a view that removes the id (and replace with just alias for example). 
do not create a menu item for the view, so that the NoMenuRules is triggered when building/parsing the url

### Expected result
the url segment is properly encoded/decoded

### Actual result

the parsing doesn't work, because the rule uses get<View>Segment to build the segment, but not get<View>Id when parsing

### System information (as much as possible)

joomla 3.9.18

### Additional comments
i'll submit a patch

**Comment by zero-24** [comment]
Closing as there is a PR thanks.
