### ISSUE TITLE
[4.0] Side Menu not aligned correctly in Edge Browser

### ISSUE THREAD

**Issue by jwaisner** [joomla/joomla-cms#28861]
### Steps to reproduce the issue
Log into backend and select any menu item (Content as an example)
Notice that the alignment of the text is all the way left 

### Expected result

![image](https://user-images.githubusercontent.com/12568201/80504620-f502d980-8938-11ea-8193-076ebad7e612.png)

### Actual result

![image](https://user-images.githubusercontent.com/12568201/80504541-db619200-8938-11ea-8df7-dbc8cb7ec80f.png)

### System information (as much as possible)

Windows 10, Microsoft Edge Browser build 18363

**Comment by brianteeman** [comment]
that is not the latest version of edge. that version number looks like it is the old pre-chromium version. The current version is Version 81.0.416.64 (Official build) (64-bit)

![image](https://user-images.githubusercontent.com/1296369/80520706-bba28c00-8981-11ea-93b6-b42e71e821c8.png)

**Comment by C-Lodder** [comment]
Not sure what Joomla's policy is with edgeHTML but reckon it's due to the lack of support for logical properties.

**Comment by jwaisner** [comment]
@brianteeman you are right. After finding and downloading the latest Edge version the issue does not exist.

That said, for those that may be running the non chromium based browser, do we still support?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28861">issues.joomla.org/tracker/joomla-cms/28861</a>.</sub>

**Comment by brianteeman** [comment]
tagging @marcodings for clarification on the policy for this

**Comment by marcodings** [comment]
Missed that.. i'm not a aware of a specific "edge" policy, ie clientside. We did discuss serersied, see motions PROD2020/025 and PROD2020/026. I will raise it in production

**Comment by brianteeman** [comment]
> serersied

??

**Comment by TobsBobs** [comment]
serverside?

**Comment by brianteeman** [comment]
@marcodings what is the result of your enquiries and where can people see these PROD motions

**Comment by brianteeman** [comment]
This should be closed as the chromium version of edge is now available for everyone automatically

Unless production department did actually discuss this - but I dont see any report on volunteers.joomla.org

**Comment by brianteeman** [comment]
Maintainers please make a decision on this. It is a year since @marcodings said he would raise it in production. I can only assume that this never happened. @wilsonge @rdeutz

**Comment by brianteeman** [comment]
Any update?

**Comment by brianteeman** [comment]
Any update?

**Comment by Quy** [comment]
Bootstrap 5 dropped browser support for the following applicable to this issue:

Microsoft Edge Legacy
Internet Explorer 10 and 11

OK to close?

**Comment by brianteeman** [comment]
360 days without a response from @marcodings is that a new record

**Comment by jwaisner** [comment]
@Quy , as the version this was tested on is not supported by BS5. I agree with closing.
