### ISSUE TITLE
[4] Wrong Language string or missing feature?

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#28867]
After installation you get the census dialog with the text "Select here to see the information that will be sent." Clicking on this link shows the information that get send but I can't disable parts for them.

At least that would be my understanding of "Select ...."

![image](https://user-images.githubusercontent.com/1497730/80592400-ab40ee80-8a1f-11ea-88a8-5bc9258db3e3.png)

**Comment by mbabker** [comment]
It’s a weirdly worded string, IIRC a victim of the “avoid click here” types of changes that have been made.  There has never been support for partial data submission and IMO adding it would make the data less useful.

**Comment by HLeithner** [comment]
Ok thx

**Comment by brianteeman** [comment]
https://twitter.com/ericwbailey/status/1255160136366260229?s=19 a very timely tweet

**Comment by mbabker** [comment]
I agree with the intent, this is just one of those cases where the replacement string seems more confusing than the original “click here to…” text.  Maybe just change it to something along the lines of “show information to be sent”, it’s already a link (hopefully in terms of display and HTML semantics), so a “click/tap/select/whatever here” preface shouldn’t be strictly necessary.
