### ISSUE TITLE
[4.0] Post Install Messages

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28863]
There are Postinstall Messages shown for the 3.x series. Since we have a new major version can we remove them for Joomla 4 ? 
<img width="1393" alt="grafik" src="https://user-images.githubusercontent.com/828371/80569559-75890f00-89f9-11ea-89f5-097b88625c93.png">

**Comment by alikon** [comment]
see #26109

**Comment by coolcat-creations** [comment]
No my question is related to the contents - actually there should be a Post Install message with maybe the Upgrade Complication-List for Joomla 4.0 or something but nothing from J3 anymore..

**Comment by brianteeman** [comment]
duplicate

**Comment by coolcat-creations** [comment]
> duplicate

of which issue? thank you

**Comment by Quy** [comment]
But for new users to J4, wouldn't these messages still be applicable?

**Comment by coolcat-creations** [comment]
> But for new users to J4, wouldn't these messages still be applicable?

About all Changes in all Joomla 3 series ? I don't think so. The changes should be then part of the documentation or not? I always thought that should be also only Messages that appear when upgrading from Version A to Version B.

**Comment by chmst** [comment]
Agree - in Joomla v4 we don't need the post-install messages of 3.9 versions.
But users who have 3.9 should get messages for J4.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28863">issues.joomla.org/tracker/joomla-cms/28863</a>.</sub>

**Comment by Quy** [comment]
Fixed in #31838
