### ISSUE TITLE
J4 Admin Save (Apply) button bypasses form validation

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#28868]
### Steps to reproduce the issue

Go to Admin / Users / New and click the Save button without entering any form data.

### Expected result

Form validation should prevent form submission.

### Actual result

The form is submitted and returns with three Field Required messages.

### System information (as much as possible)

J4 Nightly Build from April 27 2020 / Mac OSX/ Apache / PHP7.2

### Additional comments

This problem affects most of the Admin components. Comparing with the Articles form it seems that most components use ToolbarHelper::apply('xxx.apply'); whilst the Articles component uses $toolbar = Toolbar::getInstance(); $apply = $toolbar->apply('article.apply'); The adjacent Save & Close button works correctly.

**Comment by Quy** [comment]
Duplicate #26639
