### ISSUE TITLE
[4.0] Template Atum - Styling of Save and Close buttons

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28862]
Buttons in Modals have different styling and icons than buttons in Toolbar. 
They should look the same.

Modal:
<img width="364" alt="grafik" src="https://user-images.githubusercontent.com/828371/80524186-81d88200-898f-11ea-9f76-f9f959de0746.png">

Article:
<img width="543" alt="grafik" src="https://user-images.githubusercontent.com/828371/80524203-8bfa8080-898f-11ea-9f0b-d4d36c9c2e17.png">

**Comment by Quy** [comment]
Where do you see this?

**Comment by coolcat-creations** [comment]
Great - I don't remember what I did yesterday and now I can't find which modal it was - :-D 
Lesson learned... Trying to provide the information as soon as I stumble over it.

**Comment by coolcat-creations** [comment]
In Media Manager the buttons are also slightly different then accross the system:
At the top the ones with solid background (vertical margin could be bigger too) and at the bottom without icons:

<img width="1110" alt="grafik" src="https://user-images.githubusercontent.com/828371/80569829-ff38dc80-89f9-11ea-88e7-bc4a75c8a6a1.png">

Still searching for the other modal...

**Comment by ciar4n** [comment]
![image](https://user-images.githubusercontent.com/2803503/80957853-e7979480-8dfb-11ea-9c21-039f538785ab.png)

This styling was removed with https://github.com/joomla/joomla-cms/pull/28607. Local cache maybe?

**Comment by brianteeman** [comment]
I am going to close this as not reproducable.

Please create a new issue for media manager
