### ISSUE TITLE
"Cancel" on com_config does not respect the "return" URL variable

### ISSUE THREAD

**Issue by fevangelou** [joomla/joomla-cms#28871]
### Steps to reproduce the issue
- Hit the "Settings" toolbar button on any component (let's call it com_X) and you get redirected to the component's settings, loaded via com_config.
- If you hit "Save & Close" you get redirected back to the *exact* URL you previously were on com_X.
- If you hit "Cancel" you are redirected back to the component's main page (index.php?com_X) and NOT to the page you were in that component.

### Expected result
- If you hit "Cancel" you should be redirected back to specific page you were before.

### Actual result
- If you hit "Cancel" you are redirected back to the component's main page (index.php?com_X) and NOT to the page you were in that component.

### System information (as much as possible)
Joomla 3.9.18

### Additional comments
Submitted PR with fix at: https://github.com/joomla/joomla-cms/pull/28872

**Comment by Quy** [comment]
See #28872

**Comment by fevangelou** [comment]
@Quy So posting an Issue first is no longer required if a PR is ready?

**Comment by Quy** [comment]
It is not necessary if you have a PR for it. One less step to do. 😄  Include all the information in the PR instead.

**Comment by fevangelou** [comment]
Thanks :)
