### ISSUE TITLE
[4.0] Media manager event onContent[Before/After]Save misbehaving

### ISSUE THREAD

**Issue by dgrammatiko** [joomla/joomla-cms#28878]
### This **might NOT** be an actual bug!!! 

As I was playing around with J4 I found that the `content` type plugins **will not be triggered** on the respected events (given that the context was correct. Moving the plugins to `system` type things working as expected, or kinda as the `onContentBeforeSave` seems to always be skipped.

The question here: is it expected behaviour a `onContent[Before/After]Save` to be of a system type instead of the logical (at least for me) `content`?

Also can someone confirm that the events are triggered as expected?

**Comment by SharkyKZ** [comment]
Looks like only `media-action` plugin group is used:

https://github.com/joomla/joomla-cms/blob/8d7ad2ebac3d1dd0cda63e0f19905de6545e6914/administrator/components/com_media/src/Model/ApiModel.php#L529-L532

If plugins should be compatible with both J3 and J4, this needs to be changed.

**Comment by dgrammatiko** [comment]
> Looks like only media-action plugin group is used

I've tried that as well without any success

**Comment by SharkyKZ** [comment]
Seems to work for me but not sure how to display messages correctly. Aborting upload always shows generic `Internal Server Error` message.

**Comment by dgrammatiko** [comment]
@SharkyKZ I just created a PR: https://github.com/joomla/joomla-cms/pull/28886
