### ISSUE TITLE
[4.0] Error in Sidebar.php

### ISSUE THREAD

**Issue by ThomasFinnern** [joomla/joomla-cms#28874]
### Steps to reproduce the issue

* Extension with display of sidebars
* Updated Joomla 4.0 with nightly build used "Joomla_4.0.0-beta1-dev-Development-Update_Package.zip Wednesday, 29 April 2020 02:00:24 UTC"

### Expected result

* Sidebar still displaying

### Actual result

An error has occurred. "Class 'Joomla\CMS\HTML\Helpers\stdClass' not found" 
-> Location  JROOT\libraries\src\HTML\Helpers\Sidebar.php:57

### System information (as much as possible)

win10, XAMPP, PHP Version 7.3.9

### Additional comments

I try to  rewrite my "old" component rsgallery2 for j!4. I have used the code for the sidebbbars like in j!3. J4 showed the sidebars until last update.

![2020-04-29 21_13_55-Error_ 0](https://user-images.githubusercontent.com/7040580/80636946-81f38300-8a5e-11ea-8bcb-c191ad023ad1.png)

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/28875.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28874">issues.joomla.org/tracker/joomla-cms/28874</a>.</sub>
