### ISSUE TITLE
[4.0] [RFC] Atum system dashboard check marks float right

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#28879]
Regarding the system dashboard: What do you like more?

### Current look

![j4-system-dashboard-current](https://user-images.githubusercontent.com/7413183/80647107-347f1200-8a6e-11ea-8345-5b097ed631ca.png)

### Proposed look

![j4-system-dashboard-checks-right](https://user-images.githubusercontent.com/7413183/80647184-5aa4b200-8a6e-11ea-9d37-7f514bbc3787.png)

Please vote with comments below.

If people like the proposal and nobody is faster, I’ll make a Pull Request.

**Comment by brianteeman** [comment]
They should all float right

**Comment by jwaisner** [comment]
I agree with the float right for all of it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28879">issues.joomla.org/tracker/joomla-cms/28879</a>.</sub>

**Comment by infograf768** [comment]
and evidently left for RTL

**Comment by richard67** [comment]
Sure.

**Comment by richard67** [comment]
@C-Lodder Possibly you can advise: I've found a solution for this issue here which looks as follows (left side my change, right side 4.0-dev):
![j4-cpanel-quickicons-flow-right](https://user-images.githubusercontent.com/7413183/80694776-46e06680-8ad5-11ea-9a32-1f568a7dc7a1.png).

See also diff on GitHub between my branch for a new PR and 4.0-dev:[https://github.com/joomla/joomla-cms/compare/4.0-dev...richard67:4.0-dev-syspanel-check-marks-float-right]( https://github.com/joomla/joomla-cms/compare/4.0-dev...richard67:4.0-dev-syspanel-check-marks-float-right).

The disadvantage of this solution is that during the (normally short) time while the check is running and the spinner icon is shown, that spinner is not pulled to the right. After that, when ready, any error or result or check mark is then pulled to the right (LTR) or to the left (RTL) with the bootstrap css-class "float-right".

Of course I could set that css class "float-right" in PHP in the layout initially, so also the spinner would have that class, but this would be in the core layout and so cause dependency of 3rd party backend templates to bootstrap. As far as I know we don't want this, and for this little change here I should not create a template override.

So the only way to fix that I see in the way done here, in the template-specific js. But I would have to extend the onBoot function too much for that, so I think the solution shown above is an appropriate compromise.

But if you can make a proposal how to do it better, let me know please.

**Comment by C-Lodder** [comment]
You don't need to use any floats, just use flexbox. This will also work fine in RTL mode

**Comment by richard67** [comment]
@C-Lodder Hmm, it was using floats before for the counters, I just extended it to the other icons (check marks and danger). For changing that to flexbox you have to advise me. Or do a separate PR later.

**Comment by richard67** [comment]
I'm really not a CSS expert, I only started with that because it looks so ugly to me, and I haven't seen anybody else complaining about it, so I even thought it might be desired design, that's why I've made an RFC issue.

**Comment by richard67** [comment]
@C-Lodder It's not really a float, its bs class name "float-right" which we handle for RTL in SCSS having the correct float to the left (I hope. Will test later).

**Comment by richard67** [comment]
LTR:
![j4-system-dashboard-checks-right](https://user-images.githubusercontent.com/7413183/80698426-c0c71e80-8ada-11ea-907a-0b7aff2f7ac5.png)

RTL:
![j4-system-dashboard-checks-right_RTL](https://user-images.githubusercontent.com/7413183/80698448-c6bcff80-8ada-11ea-9cfe-c1b88c50694a.png)

**Comment by richard67** [comment]
I've meanwhile made a PR. See #28882 .
