### ISSUE TITLE
[3.9] Broken html in Date of Birth field in User Profile Form

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-cms#28883]
I noticed the Date of Birth field in User Profile Edit Form generates a broken html.

The issue is to due the extra info about the date format being added with broken html around it.

Might be related to this: https://github.com/joomla/joomla-cms/pull/7345

### Expected result

It should generate something like this (like all the other fields):

```
<div class="control-group">
    <div class="control-label">
            // Label here
    </div>
    <div class="controls">
            // Calendar Input here
            <span>The date of birth entered should use the format Year-Month-Day, ie 0000-00-00</span>
    </div>
</div>
```

### Actual result

Instead it generates a clearly broken HTML like this:

```
<div class="control-group">
    <div class="control-label">
    </div>
</div>
<div class="controls">The date of birth entered should use the format Year-Month-Day, ie 0000-00-00</div>
<div class="control-group">
    <div class="control-label">
      // Label here
    </div>
    <div class="controls">
      // Calendar Input here
    </div>
</div>
```

As you can see it creates an extra control-group, and the actual "controls" is outside of it, so two problems for the price of one.

Should be an easy fix probably but not sure in which file to look, couldn't find it.

**Comment by SharkyKZ** [comment]
https://github.com/joomla/joomla-cms/blob/2bac089d1e508548fab61720c16328dcd7e535b9/layouts/plugins/user/profile/fields/dob.php#L17

This is done on purpose but it looks very hacky. Maybe there's a better way.

**Comment by AndySDH** [comment]
Oh nice job for finding the culprit file! I will see to come up with a better solution for it and open a PR.

**Comment by AndySDH** [comment]
See pull request https://github.com/joomla/joomla-cms/issues/28883

**Comment by AndySDH** [comment]
See pull request https://github.com/joomla/joomla-cms/pull/28884
