### ISSUE TITLE
[4.0] White lines in Joomla logo during installation

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#28885]
### Steps to reproduce the issue
Do new installation using Firefox 75.0 on Windows.
See lines in Joomla logo.

### Actual result
![joomla](https://user-images.githubusercontent.com/368084/80722756-982c2e00-8ab4-11ea-8bba-d8f2d6965bfc.png)

### Additional comments
Not an issue in Chrome

**Comment by C-Lodder** [comment]
https://github.com/joomla/joomla-cms/pull/28888

**Comment by Quy** [comment]
Thank you!!!
