### ISSUE TITLE
[3.9] Option "Lock Inbox" does not work in Private Messages

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#28892]
### Steps to reproduce the issue
1. Your site must have 2 users with access to the control panel and work e-mail addresses,
2. Log in to the control panel under one of the users, go to **Components -> Private Messages -> My settings**, enable the **Lock Inbox** option, save and log out,
3. Log in to the control panel as a second user and try to send him a message in **Private Messages**,
4. Log back into the control panel under the first user and check the incoming messages.

### Expected result
Message must not be delivered. We should get an error or message:

```
if ($config->get('locked', false))
{
	$this->setError(JText::_('COM_MESSAGES_ERR_SEND_FAILED'));

	return false;
}
```
`COM_MESSAGES_ERR_SEND_FAILED="The user has locked their mailbox. Message failed."`

### Actual result
The message was delivered to the first user without any problems.

### System information (as much as possible)
Joomla 3.9.18
PHP 7.3.2

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/28893.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28892">issues.joomla.org/tracker/joomla-cms/28892</a>.</sub>
