### ISSUE TITLE
[4.0] node-sass updated required for NodeJS 14.x

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28895]
### Steps to reproduce the issue

- Update NodeJS to 14.1.0
- Try running `npm i`

### Expected result

build script work as expected

### Actual result

Errors thrown as node-sass 13.x doesn't work with NodeJS 14.x

**Comment by jwaisner** [comment]
Confirmed with NodeJS 14.1.0. Even ran npm ci and got same result.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28895">issues.joomla.org/tracker/joomla-cms/28895</a>.</sub>

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/28989
