### ISSUE TITLE
[4.0] Cassiopeia pagebreak shows empty content

### ISSUE THREAD

**Issue by ikueper73** [joomla/joomla-cms#28898]
### Steps to reproduce the issue

create a new article starting with a page break and add additional content and pagebreaks:

`<hr title="Content_1" alt="Content_1" class="system-pagebreak" />
<p>Content_1</p>
<hr title="Content_2" alt="Content_2" class="system-pagebreak" />
<p>Content_2</p>`

### Expected result

![expected_pagebreak](https://user-images.githubusercontent.com/6829635/80809186-6d7bcb80-8bc1-11ea-9d89-ba532099bbba.png)

### Actual result

as tabs:

![pagebreak_tabs](https://user-images.githubusercontent.com/6829635/80808603-2b9e5580-8bc0-11ea-9a6f-57ea42ce92e9.png)

as tabs with text before first pagebreak:

![pagebreak_tabs_mit_text_davor](https://user-images.githubusercontent.com/6829635/80808675-4c66ab00-8bc0-11ea-8536-955cc49dd245.png)

`<joomla-tab id="myTab" recall="" orientation="horizontal" view="tabs">
    <ul role="tablist">
        <li role="presentation"><a role="tab" aria-controls="article3-tabs0" aria-selected="false" tabindex="-1" href="#article3-tabs0" id="tab-article3-tabs0">1</a></li>
        <li role="presentation"><a role="tab" aria-controls="article3-tabs1" aria-selected="true" tabindex="0" href="#article3-tabs1" id="tab-article3-tabs1" active="">Content_1</a></li>
        <li role="presentation"><a role="tab" aria-controls="article3-tabs2" aria-selected="false" tabindex="-1" href="#article3-tabs2" id="tab-article3-tabs2">Content_2</a></li>
    </ul>
    <section id="article3-tabs0" name="1" aria-labelledby="tab-article3-tabs0" aria-hidden="true" role="tabpanel">
        <p>Text vor erstem pagebreak</p>
    </section>
    <section id="article3-tabs1" name="Content_1" active="" aria-labelledby="tab-article3-tabs1" role="tabpanel">
        <p>Content_1</p>
    </section>
    <section id="article3-tabs2" name="Content_2" aria-labelledby="tab-article3-tabs2" aria-hidden="true" role="tabpanel">
        <p>Content_2</p>
    </section>
</joomla-tab>`

### System information (as much as possible)

php7.2, joomla 4.0.0-beta1-dev

**Comment by chmst** [comment]
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28898">issues.joomla.org/tracker/joomla-cms/28898</a>.</sub>

**Comment by ChristineWk** [comment]
Confirmed

![pr28898](https://user-images.githubusercontent.com/15275917/80815175-6eb2f580-8bcd-11ea-9a79-c7f99b3312d7.JPG)

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/28901.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28898">issues.joomla.org/tracker/joomla-cms/28898</a>.</sub>

**Comment by ikueper73** [comment]
tested and can confirm the changes in PR #28901 fixed the issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28898">issues.joomla.org/tracker/joomla-cms/28898</a>.</sub>
