### ISSUE TITLE
[4.0] Since today's merges toolbar button colors and other colors have gone

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#28906]
### Steps to reproduce the issue

1. Checkout currenmt 4.0-dev.

2. Do `composer install` and `npm ci`.

3. Make a new installation.

4. Login to backend.

5. Check colors of tool bar buttons in any tool bar.

### Expected result

Some buttons have green and some red color depending on their purpose, at least that's what I remember how it looked yesterday. E.g. "Close" was red, "Save" was green and so on.

### Actual result

All blue only.

![j4-button-clolors-gone](https://user-images.githubusercontent.com/7413183/80867911-30820880-8c97-11ea-8fd6-c558604c78fc.png)

### System information (as much as possible)

4.0-dev of today, May 2, 15:00 UTC or later.

### Additional comments

The toolbar buttons are only the most visible examples. To me it seems other colors have slightly changed, too.

**Comment by richard67** [comment]
@coolcat-creations Was that intended? It seems to come from #28788 .

**Comment by coolcat-creations** [comment]
was not intended at all :-) Thank you for reporting, I will create a PR for this.

**Comment by brianteeman** [comment]
Closed see #28907
