### ISSUE TITLE
[4.0][3.9] J Installation: debug lang shows constant per default instead of value

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#28913]
### Steps to reproduce the issue
Get a clean 4.0-dev pack or a staging pack
Modify `installation/localise.xml` to use debug

`<debug>1</debug>`
Start installation

We get the constants between the stars instead of the translated strings between stars although language strings are OK.

<img width="973" alt="Screen Shot 2020-05-03 at 08 52 44" src="https://user-images.githubusercontent.com/869724/80908034-a3819280-8d1c-11ea-8bf9-d7bd1494baf8.png">

<img width="1079" alt="Screen Shot 2020-05-03 at 09 05 13" src="https://user-images.githubusercontent.com/869724/80908085-4508e400-8d1d-11ea-8ffa-2783b22ea39a.png">

The issue comes from the introduction of the choice between constant and value in https://github.com/joomla/joomla-cms/pull/21691 in 3.9.0

**Comment by infograf768** [comment]
Comparing with 3.8.x
<img width="1078" alt="Screen Shot 2020-05-03 at 09 53 04" src="https://user-images.githubusercontent.com/869724/80908906-09bde380-8d24-11ea-94c8-0e10f1feacb4.png">

**Comment by SharkyKZ** [comment]
See partial PR for changing default behavior https://github.com/joomla/joomla-cms/pull/28914.

**Comment by SharkyKZ** [comment]
@infograf768 should installation also have ability to switch between strings/constants? Would need to add another option to `localise.xml`.

**Comment by infograf768** [comment]
@SharkyKZ 
The debug functionnality in the localse.xml is only useful for TTs imho.
Therefore I do not think we do really need a new parameter there. $value is ok I think.

**Comment by SharkyKZ** [comment]
Then this can be closed, I guess.
