### ISSUE TITLE
[4.0] com_config. Save&Close options. No message displayed.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#28915]
### Steps to reproduce the issue
- Go to `Content > Articles`.
- Click `Options` button.
- Click `Save`:
You see message: "Configuration saved".
- Click `Save & Close`:
_**=> No message**_

### System information (as much as possible)
- Nightly build full packege of today (Sunday, 03 May 2020 02:00:34 UTC).
- Fresh installation.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/28917 (for staging).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28915">issues.joomla.org/tracker/joomla-cms/28915</a>.</sub>
