### ISSUE TITLE
New user registration: "no password" and "no system emails" - need to improve tooltips & more?

### ISSUE THREAD

**Issue by CodeOfConduct** [joomla/joomla-cms#28924]
### Steps to reproduce the issue
Use default settings in J! 3.9.18 for the creation for new users under Global configuration>Users>

   i)Send password: NO
   ii)New User Activation: Administrator
   iii) Send mail to administrators: YES
   iv) New user registration group: Registered

2) Create new user

Set Users>New>

i)	Receive Systems Emails: NO
ii)	Require Password Reset: NO

Enter passwords or leave blank.

### Expected result 

a) "User will receive an email with an activation link. When the user clicks this link, the Site Admin will be notified via email and the Site Admin needs to activate the user's account." (as per https://docs.joomla.org/Help39:Components_Users_Configuration) 

b) Password is *not* sent in email to newly created user

c) The administrator needs to activate the user to change its status to "actived" in the backend.

### Actual result (applies when site is *online or offline*)

1) New user receives email *with username and password*, as well as link to the site (*not activation link*)
2) The user's status in the backend is "activated" as soon as it has been created, i.e. before the administrator has activated it.
3) Administrator does not receive email after creating new user.

### System information (as much as possible)

a) Joomla! 3.9.18 installed from scratch on Unix shared hosting environment
b) Multilingual site configured at Joomla! installation, default site language: Italian
c) Installed Gantry 5 (latest version) + Rockettheme template

**Comment by gerryfrancis** [comment]
> i) Receive Systems Emails: NO

> Expected result a) "User will receive an email with an activation link.

How should a user receive mails when "Receive System Emails" is set to "NO"?

**Comment by infograf768** [comment]
A user created from backend is totally different from a user creating his/her new account in frontend.
The parameters are set in the plugin.

<img width="862" alt="Screen Shot 2020-05-04 at 11 53 03" src="https://user-images.githubusercontent.com/869724/80954552-e23b4980-8dfd-11ea-9ecb-ca1d60c25e67.png">
<img width="473" alt="Screen Shot 2020-05-04 at 11 53 18" src="https://user-images.githubusercontent.com/869724/80954574-ee270b80-8dfd-11ea-9792-27ef69491a0c.png">

**Comment by ReLater** [comment]
> How should a user receive mails when "Receive System Emails" is set to "NO"?

That's a misunderstanding of this setting concerning this case. Normally you never set this setting to "Yes" for registered users. That's a setting for special emails from the Joomla system.

**Comment by CodeOfConduct** [comment]
@gerryfrancis: That's a fair comment, if the "systems emails" in that setting include the first email after registration from the backend, as I assumed. As infograf768 clarified, that is an incorrect assumption, as the first system email in this case is allowed or suppressed by the plugin. 

@infograf768: Thank you very much for your answer. It gave me a solution that at least avoids the password being sent by email.

The question remains, why the tooltip for Global configuration > Users > Send password says ""If set to "Yes" the user's first password will be emailed to the user as part of the registration mail." when in fact the password is sent even if this setting is NO.

So, **my suggestions** are as follows:

1) Check whether the functionality related to Global configuration > Users > Send password is correct or/and whether the tooltip needs to be changed. I don't know what the intended functionality is - maybe it relates to passwords being sent as part of password reset requests?

2) Improve tooltip for "Receive Systems Emails" as follows: "If set to yes, the user will receive system emails, *except* the first email after registration, whose despatch is determined in the "User - Joomla!" plugin. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28924">issues.joomla.org/tracker/joomla-cms/28924</a>.</sub>

**Comment by brianteeman** [comment]
Sorry but this is completely wrong.

1. If set to no then it should not send the password. If it does then that is a bug. However in my tests the registration email did not send the password. See screenshots at the bottom.

2. System emails refers to the type of email sent to an administrator eg update available, user awaits approval. It is nothing to do with this email which is a user email.

![image](https://user-images.githubusercontent.com/1296369/80960791-7c50c100-8e01-11ea-8a13-b246e7f6c945.png)

![image](https://user-images.githubusercontent.com/1296369/80960879-aace9c00-8e01-11ea-8512-d7a4ed38916a.png)

**Comment by CodeOfConduct** [comment]
@brianteeman - interesting that we are getting opposite results. When I set "Notification Mail to User" = Yes in the User - Joomla! plugin, I definitely get a confirmation mail with the password (which I entered, optionally, as administrator when creating the new user), but it is a different email from the one you receive. Mine does not include an activation / verification link (as mentioned in my opening description) and shows the password below the user name. 

Also, there seems to be a misunderstanding about the mail setting: I am referring to the one in the attached screenshot.

I hope this helps us isolate what action (if any) should be taken.

Btw, when the "Notification Mail to User" = No in the User - Joomla! plugin, the password fields in the form for the creation of a new user become mandatory. I presume that is intended behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28924">issues.joomla.org/tracker/joomla-cms/28924</a>.</sub>

**Comment by CodeOfConduct** [comment]
Here the screenshot mentioned in my previous comment...![screen shot 2020-05-04 at 11 59 54](https://issues.joomla.org/uploads/1/aca6cd942e25b899b7c111e2a7a6afcb.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28924">issues.joomla.org/tracker/joomla-cms/28924</a>.</sub>

**Comment by brianteeman** [comment]
If you are creating a users account for them then it is obviously assumed they do not need to verify

**Comment by CodeOfConduct** [comment]
@brianteeman "If you are creating a users account for them then it is obviously assumed they do not need to verify" - sure. I referred to the verification link merely as evidence that we are talking about different emails. One of the issues of this ticket is the fact that the password was sent out when i.m.o. it should not have been - or is my expectation incorrect?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28924">issues.joomla.org/tracker/joomla-cms/28924</a>.</sub>

**Comment by brianteeman** [comment]
If you are creating an account for a user then it has to send them a password otherwise they can not log in

**Comment by gerryfrancis** [comment]
Sorry for misunderstanding, I thought system mails are those sent from the (Joomla!) system in general. Thanks for clarifying.

**Comment by CodeOfConduct** [comment]
@brianteeman Of course the user will have to be informed of his/her new temporary password, but I would much rather do that via a different channel than by email and without quoting both user ID **and** password in the same email. Presumably the setting in the User - Joomla! plugin to deactivate such emails was created partly to address such security concerns.

The question that remains is **whether the behaviour that I described at the beginning is correct.** If so, than I would say the tooltips should be changed. As I said, if the behaviour is not correct, I'll gladly carry out some more tests to help isolate the problem.

**Comment by brianteeman** [comment]
> @brianteeman Of course the user will have to be informed of his/her new temporary password, but I would much rather do that via a different channel than by email and without quoting both user ID and password in the same email. Presumably the setting in the User - Joomla! plugin to deactivate such emails was created partly to address such security concerns.

The setting is for users when they register. Not for admins when they register others.

The option Require Password Reset exists so that the user will receive an email AND when they login for the first time they will be forced to reset it before continuing.

The behaviour you describe in the Actual Results is the expected and designed behaviour

**Comment by CodeOfConduct** [comment]
@brianteeman Thank you for your clarifications. On that basis I'll now close this issue.
