### ISSUE TITLE
[3.x] contact category filter

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#28927]
### Steps to reproduce the issue
Create nested Contact Categories
Create Contacts in each category

From the Category view select the published contacts in one of the nested categories
![image](https://user-images.githubusercontent.com/1296369/80959922-b6b95e80-8dff-11ea-8bd4-5f7bebdb4721.png)

### Expected result
![image](https://user-images.githubusercontent.com/1296369/80959989-d781b400-8dff-11ea-9ace-597ce32d13c9.png)

### Actual result
![image](https://user-images.githubusercontent.com/1296369/80959955-c46ee400-8dff-11ea-8acd-e0c444fbeda2.png)

### Additional comments
The same functionality in com_content works correctly

**Comment by alikon** [comment]
please test #28933

**Comment by alikon** [comment]
#28933 is still a WIP

**Comment by alikon** [comment]
please test  #30413
