### ISSUE TITLE
Youtube embed code modified by TinyMCE

### ISSUE THREAD

**Issue by humblehumanbeing** [joomla/joomla-cms#28922]
### Steps to reproduce the issue
Use TinyMCE as default editor
Turn Joomla text filter ON in TinyMCE settings
Add a Youtube embed code
<iframe width="1129" height="635" src="https://www.youtube.com/embed/b1LjegNN09M" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></p>
Save the article

### Expected result
It should retain the code as is:
<iframe width="1129" height="635" src="https://www.youtube.com/embed/b1LjegNN09M" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></p>

### Actual result
Text filter won't clear iframe and its parameters but allowfullscreen parameter is enclosed with "s
<iframe width="1129" height="635" src="https://www.youtube.com/embed/b1LjegNN09M" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen"></iframe></p>

### System information (as much as possible)
Joomla 3.9.18

**Comment by SharkyKZ** [comment]
It doesn't wrap the attribute, it adds a value to the attribute. This is required in XHTML. Unless this is causing the attribute to fail (it really shouldn't), this isn't really an issue.

**Comment by brianteeman** [comment]
I am closing this as the _"problem"_ is upstream with tinymce and beyond our control. You can see this with the demo at https://www.tiny.cloud/ where the same thing happens.
