### ISSUE TITLE
[4.0] Can save "Menu Item Alias" without selecting a "Menu Item"

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#28935]
### Steps to reproduce the issue
- Create a new menu item (back-end)
- Select "Menu Item Type": "Menu Item Alias"
- DO NOT select a "Menu Item"!!
- Save.

### Expected result
- It should not be possible to save the menu item (or the `required` star is wrong there).

### Actual result
- One can save the menu item.

**Comment by SharkyKZ** [comment]
Please test PR #28937.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28935">issues.joomla.org/tracker/joomla-cms/28935</a>.</sub>
