### ISSUE TITLE
[3.9] Incorrect message when saving profile in control panel

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#28934]
### Steps to reproduce the issue
Log in the control panel and press Edit Account, then click Save. You can see the message about saving to the profile in an unusual way :).

![Screenshot_4](https://user-images.githubusercontent.com/8440661/81014667-f2870f00-8e65-11ea-9485-a647ebbbe54f.png)

Among other things, the file with the original constant is loaded, and then en-GB.com_messages.ini.

`JLIB_APPLICATION_SAVE_SUCCESS="Item saved."`
`JLIB_APPLICATION_SAVE_SUCCESS="Message sent."`
```
Language Files Loaded
**Loaded** : JROOT\administrator\language\en-GB\en-GB.lib_joomla.ini
...
**Loaded** : JROOT\administrator\language\en-GB\en-GB.com_messages.ini
```
Need your own constant for "message sent" in the private message component.

### System information (as much as possible)
Joomla 3.9.18
PHP 7.3.2

**Comment by SharkyKZ** [comment]
@infograf768 can we remove `JLIB_APPLICATION_SAVE_SUCCESS` from `com_messages.ini` at this point or will this have to wait for 4.0?

**Comment by brianteeman** [comment]
@SharkyKZ surely it is needed for com_messages

I am guessing that the problem is that this language file should not be being loaded here

**Comment by SharkyKZ** [comment]
We can add `COM_MESSAGES_SAVE_SUCCESS` and there will be no need for `JLIB_APPLICATION_SAVE_SUCCESS` in `com_messages.ini`. But if we can't remove it now, we'll also have to add `COM_ADMIN_SAVE_SUCCESS` to `com_admin.ini` for now.

**Comment by SharkyKZ** [comment]
That the file is loading is fine (it's done by Actionlogs plugin) but it really shouldn't be overriding main library strings.

**Comment by infograf768** [comment]
JLIB strings in specific component strings were designed to override the main lib.joomla.ini strings on purpose.
This situation is indeed created by the new Actionlogs plugin.
At first sight, it does not look like creating a specific string in com_messages.ini and deleting the JLIB one would create any issue.
Evidently that would mean adding a save method in the user controller.

**Comment by SharkyKZ** [comment]
No changes needed in controller, it supports string prefixes.

**Comment by infograf768** [comment]
ah.. right.
Therefore no problem to add the string COM_MESSAGES_SAVE_SUCCESS and kill the JLIB one

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/28939.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28934">issues.joomla.org/tracker/joomla-cms/28934</a>.</sub>
