### ISSUE TITLE
[4.0] Back-end. "Preview Module Positions" fails

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#28932]
### Steps to reproduce the issue
- Go to `administrator/index.php?option=com_config&view=component&component=com_templates`
- Activate option `Preview Module Positions`
- Open `administrator/index.php?option=com_templates&tp=1`

### Expected result
![04-05-_2020_20-57-37](https://user-images.githubusercontent.com/20780646/81002928-56034380-8e4a-11ea-8d6d-69496a65187e.jpg)

### Actual result
![04-05-_2020_20-56-51](https://user-images.githubusercontent.com/20780646/81002972-67e4e680-8e4a-11ea-81ce-a1d7cac42c5b.jpg)

### Solution
- Add language strings in back-end *.ini:
`JGLOBAL_PREVIEW_POSITION`, `JGLOBAL_PREVIEW_STYLE`

**Comment by brianteeman** [comment]
You will see that there is no option to view the positions in the admin ui - only the site templates. (same as in J3)

It is not as simple as adding the language strings as they are just the labels - there are no values being output

**Comment by SharkyKZ** [comment]
Adding the strings works fine.

**Comment by brianteeman** [comment]
sorry I forgot they were sprintf strings

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/28936 where I also implemented the admin templates Preview.
