### ISSUE TITLE
[4.0] Language Overrides - InputFilter error

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#28945]
Argument 1 passed to Joomla\Filter\InputFilter::__construct() must be of the type array, null given, called in \libraries\src\Filter\InputFilter.php on line 55 

### Steps to reproduce the issue
Create a language override.
Click Save button.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/28946.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28945">issues.joomla.org/tracker/joomla-cms/28945</a>.</sub>
