### ISSUE TITLE
[4.0] Article - Change Image

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#28940]
### Steps to reproduce the issue

Go to:
1. Articles > New
2. Open tab Images and Links
3. Select Intro Image

### Expected result

I can use an external URL fot the image like Joomla 3.x:
![immagine](https://user-images.githubusercontent.com/906604/81059519-d7051e00-8ed0-11ea-9827-6307b1ca456a.png)

### Actual result
No URL option:
![immagine](https://user-images.githubusercontent.com/906604/81059573-f0a66580-8ed0-11ea-8625-ed0056d63b2a.png)

**Comment by adj9** [comment]
I tried loading the image from URL and in Joomla! 4 and there is no field.

**Comment by Quy** [comment]
Duplicate #28852
