### ISSUE TITLE
[J!4.0] Upload button for non-functional images

### ISSUE THREAD

**Issue by adj9** [joomla/joomla-cms#28943]
### Context
![image](https://user-images.githubusercontent.com/5918444/81066714-cf984180-8edd-11ea-85b7-7ba21f32f475.png)

Go to:
1. Articles > New
2. Open tab Images and Links
3. Select Intro Image

I upgraded the Nightly Builds and the upload button doesn't work.

### Expected result
On click I get window for choosing the file.

### Software Requirements
- Web site
- Chrome 81.0.4044.129 (Build ufficiale) (a 64 bit)
- macOS Catalina 10.15.3

**Comment by Quy** [comment]
Is this reproducible with a clean install of the nightly build?

**Comment by adj9** [comment]
I installed the Nightly Build tonight and the context happens.
I haven't opened a PR since I don't have any solutions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28943">issues.joomla.org/tracker/joomla-cms/28943</a>.</sub>

**Comment by Quy** [comment]
I am unable to reproduce with a clean install of the nightly build.

**Comment by adj9** [comment]
@Quy do you use Chrome?

It could be that I have patches activated and I have internal problems.

**Comment by Quy** [comment]
Tested with Chrome Version 81.0.4044.129 on Windows 10.

**Comment by adj9** [comment]
Confirmed my internal bug of site. With a reset of site the upload bottom function correctly with previusly previous requirement and also with Safari 13.0.5.

**Comment by Quy** [comment]
Closing for now as non-reproducible.
