### ISSUE TITLE
Show linked article images missing from backend of articles newsflash module

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#28957]
### Steps to reproduce the issue

Login backend with Super Admin
Create Modules: Articles - Newsflash
Show Article Images Yes

### Expected result

Button for linked article images should appear

### Actual result

Button for Show Article Images to Linked Article Images does not appear
If changing to Show Article Title to Linked Titles, button appears

### System information (as much as possible)

Joomla! 3.9.18
Protostar template

**Comment by ReLater** [comment]
`Show Article Images` means: "Don't remove images in introtext of article". Images that you have embedded directly in the text via editor.

For the second setting `Show Intro/Full Image` there was never an option to link the images but you can do that via a module override.

Therefore I think it's not an issue ("bug") but a feature request.

J3 doesn't implement new features. Perhaps for Joomla 4?

**Comment by ghost** [comment]
OK thanks very much, but before you get too smug about whether this a bug or feature, perhaps acknowledge that it seems rather random that this "feature" would appear only for Show Article Title and not Show Article Images. To a user new to Joomla, this would certainly seem more bug than feature.

**Comment by ReLater** [comment]
I don't want to discuss anything. The decision was made: "No new features in Joomla 3".
That's what I've explained. Not more.

> Show Article Images

Let's say you have 5 images embedded in your article introtext. You want to link them all? I don't think that a pr would be accepted, nor in J3 neither in J4. 

> before you get too smug

Stop to insult participants.

**Comment by ghost** [comment]
Could you be so kind and please provide the code that should be inserted to link the images via a module override ?
I would be glad to test if to link the images via a module override works.

**Comment by ReLater** [comment]
Ask in a Joomla forum please but you should explain there about which images you are talking. For `Article Images` you need a regular expression, a preg_replace or similiar.

For `Intro/Full Image`
Change this line
https://github.com/joomla/joomla-cms/blob/3.9.18/modules/mod_articles_news/tmpl/_item.php#L27

to
```
		<a href="<?php echo $item->link; ?>">
			<img src="<?php echo $item->imageSrc; ?>" alt="<?php echo $item->imageAlt; ?>">
		</a>
```
