### ISSUE TITLE
[4.0] Overlay mobile navs, not clickable if a other one is open

### ISSUE THREAD

**Issue by HRIT-Florian** [joomla/joomla-cms#28952]
If the mobile menu is open, any other mobile menu like user is than not openable, because it overlays. 

### What needs to be fixed
1st click to the main mobile nav.
2nd click to any other mobile nav.

![mobilenav](https://user-images.githubusercontent.com/12803406/81110505-e8bfe300-8f1b-11ea-931f-51585eae5495.jpg)

### Why this should be fixed
Just fo UX ;)

### How would you fix it
Maybe a dynamic zindex, set to the higher by js if a menu is already open
Or close the current menu when another one is opened

**Comment by ghost** [comment]
Issue confirmed.

**Comment by brianteeman** [comment]
It is a z-index issue. My non-skilled css says that it is resolved by removing the special z-index-mobile-menu  here but maybe there are consequences I can not see and there is a better way to fix it

https://github.com/joomla/joomla-cms/blob/98a4b2a2cfa1a425131f5f0565459d8ef21ee87c/build/media_source/templates/administrator/atum/scss/blocks/_sidebar.scss#L277


@hans2103 any ideas?

**Comment by hans2103** [comment]
I can reproduce the issue

see movie

https://github.com/user-attachments/assets/7a45ec99-4f5a-42a7-8566-28d03ba597e2

onwards to find a solution. :-)

**Comment by hans2103** [comment]
The button bottom right to open _Main Menu_ is using "Bootstrap Collapse"
The two buttons bottom left to open _User Menu_ or _Joomla info_ are using "Bootstrap Dropdown"

> Dropdowns
> Toggle contextual overlays for displaying lists of links and more with the Bootstrap dropdown plugin.
https://getbootstrap.com/docs/5.2/components/dropdowns/

> Collapse
> Toggle the visibility of content across your project with a few classes and our JavaScript plugins.
https://getbootstrap.com/docs/5.2/components/collapse/


So... 
when you click the menu (bottom right) having data-bs-toggle="collapse" should close any open data-bs-toggle="dropdown".
And the other way around too... when you click the menu (bottom left) having data-bs-toggle="dropdown" should close any open data-bs-toggle="collapse".

**Comment by hans2103** [comment]
Created PR https://github.com/joomla/joomla-cms/pull/43891 to solve this issue

**Comment by alikon** [comment]
please test #43891

**Comment by hans2103** [comment]
@HRIT-Florian would you mind test my PR and see if your mentioned is fixed?
