### ISSUE TITLE
[4.0] com_messages: user settings not saved

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#28958]
### Steps to reproduce the issue
Load Private Messages Manager.
Click on `My Settings` button.
For example switch `Lock Inbox` to Yes.
Save.
Click again on the button.
`Lock Inbox` is still set to No.
No entry in table` _messages_cfg`
No fail or success message.

![lockbrokenj4](https://user-images.githubusercontent.com/869724/81145886-85639e80-8f77-11ea-96e0-b0a2312a7619.gif)

**Comment by infograf768** [comment]
Found the issue:
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_messages/src/Controller/ConfigController.php#L37

`$model = $this->getModel('Config', 'MessagesModel');`
should be
`$model = $this->getModel('Config');`

But it is not enough as we don't get any Success message after saving

**Comment by chmst** [comment]
Confirmed. 

I ask myself why it is a modal. It would be much easier in a view.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28958">issues.joomla.org/tracker/joomla-cms/28958</a>.</sub>

**Comment by brianteeman** [comment]
@chmst No idea but this is a very very old bit of code for something hardly used so its never had any love

**Comment by infograf768** [comment]
On it. Changing the popup to a view which solves the success message.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/29006
Closing as we have a patch
