### ISSUE TITLE
[4.0] HTMLHelper TabSet set active Tab did not work

### ISSUE THREAD

**Issue by HRIT-Florian** [joomla/joomla-cms#28951]
### Steps to reproduce the issue
administrator\components\com_content\tmpl\article\edit.php
Edit
`<?php echo HTMLHelper::_('uitab.startTabSet', 'myTab', array('active' => 'gernal')); ?>` 
To
`<?php echo HTMLHelper::_('uitab.startTabSet', 'myTab', array('active' => 'images')); ?>`

### Expected result
Images Tab should be activ

### Actual result
First Tab is active

### System information (as much as possible)
PHP Version | 7.3.14
Joomla! 4.0.0-beta1-dev Development [ Mañana ] 17-October-2019 20:21 GMT
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0

**Comment by SharkyKZ** [comment]
Tabs use sessionStorage to remember last opened tab. This is stored for each URL. Try editing a different article and it should go straight to image tab.

**Comment by C-Lodder** [comment]
@SharkyKZ Yes, but that's if a tab is clicked. This issue is regarding activating a specific tab

**Comment by HRIT-Florian** [comment]
@SharkyKZ Yes, right. I would suggest for UX, these should not be affected when a specific Tab is dynamic activated. In my case I used these for dynamic set a Tab by input like these:
 ```php
<?php echo HTMLHelper::_('uitab.startTabSet', 'myTab', array('active' => $inputTab)); ?>

**Comment by joomdonation** [comment]
I just tried it again and it worked on latest Joomla 4 (I use this kind of code in my own extensions, too). So look like it was solved elsewhere. For now, I'm closing this issue. Feel free to re-open it if you can still re-procedure it with latest Joomla 4.2.
