### ISSUE TITLE
Language code missing in Category field of com_categories batch popup

### ISSUE THREAD

**Issue by artur-stepien** [joomla/joomla-cms#28963]
### Steps to reproduce the issue
- Install new language and configure content language.
- Go to `com_categories` (eg `Content->Categories`)
- Create 2 categories: `Category 1` (language en-GB), `Category 2` (your additional language)
- Now check one of them in categories list and click on `Batch` button in toolbar
- Look into the category field (select field under `To Move or Copy your selection please select a Category.`)

### Expected result
- List of categories with language code in brackets eg. `Dogs (en-GB)`

### Actual result
- No language code in any of the categories

### System information (as much as possible)
3.9.18

### Additional comments
Nothing really harmful, just a bad user experience when you try to copy categories structure between languages. It affects all extensions using default categories functionality.

**Comment by richard67** [comment]
@artur-stepien There is no need to open an issue and then make a Pull Request (PR) if you have already the solution for the PR. It is sufficient to just make the PR and describe the issue in the PR'S description.

**Comment by richard67** [comment]
Closing as having a pull request: #28964 .

**Comment by artur-stepien** [comment]
I wasn't about to create the PR but found the quick fix after reported the issue.

**Comment by richard67** [comment]
Ah, ok, thanks, then all was right 😄
