### ISSUE TITLE
Linked intro article images missing from frontend of articles Show Intro Text

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#28973]
### Steps to reproduce the issue

Login frontend with Super Admin
Submit new Article - add image

### Expected result

Using frontend new article added intro image on Category blog clicable intro image should appear

### Actual result

Using frontend new article added intro image on Category blog nonclicable intro image appear

Using backend New Articles to Images and Links to Intro Image on Category blog you get clicable intro image

### System information (as much as possible)

Joomla! 3.9.18
Protostar template

**Comment by gerryfrancis** [comment]
@HerMuller AFAIK, Protostar does not offer a clickable intro image for an article:

https://docs.joomla.org/Help39:Content_Article_Manager_Edit#Images_and_Links

Maybe you can achieve your goal with an override.

**Comment by ReLater** [comment]
Intro images are always linked in multi article blog layout in Joomla core IF an intro image exists AND "Link article title" is activated:
https://github.com/joomla/joomla-cms/blob/3.9.18/layouts/joomla/content/intro_image.php#L19

(The same with featured layout.)

Intro images are added via tabulator "Images and Links". There is no difference between back-end and front-end creation of the article.

**Comment by ghost** [comment]
ReLater what are your steps to reproduce the Linked Intro images from fronted?

Additional comments
add image from frontend using default joomla tinymce editor then add read more
only article title and read more is clicable, but Category blog nonclicable intro image appear

**Comment by ReLater** [comment]
Perhaps we're talking about different things??????????

## This is the place to define a so called "Intro Image".

Front-end and back-end the same place. It gets a link in blog layout if "Link Titles" in blog view is activated:

![06-05-_2020_21-52-16](https://user-images.githubusercontent.com/20780646/81222089-0bb5ca00-8fe4-11ea-848b-6be4f51df9ca.jpg)


## This is not an "Intro Image":

![06-05-_2020_21-55-33](https://user-images.githubusercontent.com/20780646/81223443-46b8fd00-8fe6-11ea-8d9b-2958e271e544.jpg)


It never gets a link automatically by Joomla core. MY(!!!) reasons against it would be:
1) It can be already linked by the creator of the article.
2) An image inside the article text can also be a small icon or whatever
2) To find images inside article text eats up performance.
3) If you have more than 1 image which one gets the link? All, only the first ...

![06-05-_2020_21-59-41](https://user-images.githubusercontent.com/20780646/81223560-7831c880-8fe6-11ea-9b8d-8839d89dd08a.jpg)

**Comment by gerryfrancis** [comment]
@ReLater 

> Intro images are always linked in multi article blog layout in Joomla core IF an intro image exists AND "Link article title" is activated

I cannot find "Link article title". Is that function included in Joomla! version 3.x or 4.x only?
Edit: Found it, "Title" must be activated. Thanks a lot for your help!

**Comment by ghost** [comment]
Yes maybe we are talking about different things. Maybe you know how to call this thing properly in joomla? All area above read more to apear clicable. 

![81223560-7831c880-8fe6-11ea-9b8d-8839d89dd08a](https://user-images.githubusercontent.com/64595807/81260943-c4f7bc80-9043-11ea-9cd9-7554be6d0ed0.jpg)

Thanks. Maybe you know what code to add to protostar template or to joomla files to have this result? All area above read more to be clicable?

Could you be so kind and please provide the code that should be inserted?
I would be glad to test if this works. Hope this will help joomla and joomla community to be better.

**Comment by gerryfrancis** [comment]
@HerMuller 

> All area above read more to apear clicable.

I would not like to have such behavior on a web site if I was visiting it, especially for such a large area like the one you outlined on your latest screenshot. Feel free to search the web for tutorials how to achieve tiles, I believe there might be a plugin for this, too.

**Comment by ghost** [comment]
Screenshot size doesn't matter here, its to help ReLater and other joomla community members to understand what we are talking about, hope it helps joomla and joomla community

**Comment by gerryfrancis** [comment]
@HerMuller Nevertheless it is a new feature that you are requesting. Joomla! 3.x status is "feature complete".

**Comment by ghost** [comment]
gerryfrancis OK thanks very much, but before you get too smug about whether this a bug or feature, perhaps acknowledge that it seems rather random that this "feature" would appear only for one image insertion and not from joomla editor tinymce image insertion. To a user new to Joomla, this would certainly seem more bug than feature.

Could you be so kind and please provide the code that should be inserted?
I would be glad to test if this works. Hope this will help joomla and joomla community to be better.

Please theus joomla community members who dont want to provide actual code which I would be glad to test refrain from respone and please do not hijack this issue. Thanks to everyone who contributes code to joomla.

**Comment by gerryfrancis** [comment]
@HerMuller 

> Please theus joomla community members who dont want to provide actual code which I would be glad to test refrain from respone and please do not hijack this issue.

Regarding Joomla! 3.x, you are at the wrong place. This branch will not receive any further features, just bug fixes. You are requesting a new feature, which is "making the whole intro area of an article clickable in a blog view". This platform - here - is for issues in 3.x/4.x that are based on bugs, and for issues in 4.x that will result in new features. As you are using the current 3.x branch of Joomla!, please request support at forum.joomla.org . Thanks!

**Comment by ghost** [comment]
gerryfrancis if you have no clue and or unable and dont want to provide the code that should be inserted to fix this please dont spam here. If you need to discus please go to joomla forum.

here is the place about actual code and pr 

I am here to help joomla and joomla community, hope majority here is about code and pr and not about empty braging, spaming and hijacking issues.

thanks

**Comment by ReLater** [comment]
> You are requesting a new feature, which is "making the whole intro area of an article clickable in a blog view".

If that's the purpose (link whole intro text):

That's the override for blog_item.php (with redundant code):
https://raw.githubusercontent.com/ReLater/linked-intro/master/blog_item.php

That's the code change compared with the original file in Joomla 3.9.18.
https://github.com/ReLater/linked-intro/pull/1/files

I won't provide code for "only link images"! Ask in a forum for help, please.

**Comment by brianteeman** [comment]
I am closing this as the question has been asked and answered

**Comment by gerryfrancis** [comment]
@HerMuller Thank you for being so polite, I am sure you will get what you deserve...
