### ISSUE TITLE
[4.0] Install from web - link to developer site

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28978]
### Steps to reproduce the issue

1. Go to `administrator/index.php?option=com_installer`
2. Click on the "Install from Web" tab
3. Click any extension
4. Inspect the "Developer Wesbite" link element

### Expected result

Element should be made safe with `rel="noopener noreferrer"`

### Actual result

Unsafe link

## Notes

If the DOM belongs to JED, then I'm happy to submit the bug on their repo.

cc'ing @anibalsanchez

**Comment by anibalsanchez** [comment]
The IFW server is the service that generates the API responses that include the rendered output. It is currently managed by the core team. 

The improvement should be implemented in this repo: https://github.com/joomla/install-from-web-server.

**Comment by alikon** [comment]
@C-Lodder  can you have a look at https://github.com/joomla/install-from-web-server/pull/50

**Comment by C-Lodder** [comment]
@alikon looks ok to me. Should also be applied on the J3 file too.

**Comment by alikon** [comment]
sure right 
done

**Comment by alikon** [comment]
so i'm going to close this issue here, 
please follow  the ongoing at https://github.com/joomla/install-from-web-server/pull/50
