### ISSUE TITLE
[4.0] Template Atum Icon for Home Item in Menu

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#28976]
Can this (the star icon) be changed to a "Home" Icon since it's not a **featured** menu item? I think we should use one icon for only one matter for better usability and understanding.

![grafik](https://user-images.githubusercontent.com/828371/81222190-30aa3d00-8fe4-11ea-8623-3536e327ac56.png)

**Comment by brianteeman** [comment]
Unfortunately we also have a mismatch between calling this home and default

**Comment by infograf768** [comment]
We also have a difference between a monolingual site and a multilingual site.
<img width="1282" alt="Screen Shot 2020-05-07 at 10 06 01" src="https://user-images.githubusercontent.com/869724/81270008-68e46680-904a-11ea-962e-4fff2ea12b5a.png">

**Comment by alikon** [comment]
please test #29016
