### ISSUE TITLE
[4.0] Untranslated string in Atum

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28970]
### String

`Toggle navigation`

https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/index.php#L120

### Expected result

A translatable string using `Joomla\CMS\Language\Text`

**Comment by coolcat-creations** [comment]
Thank you, added a PR https://github.com/joomla/joomla-cms/pull/28972
