### ISSUE TITLE
[4.0] Users activation from administrator panel

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#28984]
### Steps to reproduce the issue

1. Enable users registration (Back-end > Users > Options > Allow User Registration: yes)
2. Go to frontend and create a new user but do not open the mail to confirm the new account
3. Return to back-end and go to Users panel.
4. Try to Activate the new user

![immagine](https://user-images.githubusercontent.com/906604/81330388-4d0baf80-90a0-11ea-94db-fea45d21b168.png)

### Expected result

As Joomla 3.x if you click on:
![immagine](https://user-images.githubusercontent.com/906604/81329846-6ceea380-909f-11ea-9442-684b4977276f.png)

The user is activated and enabled

![immagine](https://user-images.githubusercontent.com/906604/81329910-8b549f00-909f-11ea-9aaa-721ddf903526.png)

### Actual result

*ERROR*
```
An error has occurred.

    0 Argument 4 passed to PlgUserToken::onUserAfterSave() must be of the type string, null given, called in /var/www/vhosts/site.com/subdomains/j4/httpdocs/libraries/src/Plugin/CMSPlugin.php on line 285 
```
And a strange (never seen) Joomla icon appears in the left menu

![immagine](https://user-images.githubusercontent.com/906604/81330697-bf7c8f80-90a0-11ea-9641-047c811df94c.png)

### System information (as much as possible)

Joomla version, ‎4.0.0-beta1-dev

```
=============
System Information
=============
php: Linux web-lnx247.ergonet.host 3.10.0-1062.4.3.el7.x86_64 #1 SMP Wed Nov 13 23:58:53 UTC 2019 x86_64
dbserver: mysql
dbversion: 10.1.43-MariaDB
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: false
phpversion: 7.3.17
server: Apache
sapi_name: fpm-fcgi
version: Joomla! 4.0.0-beta1-dev+pr.28075 Development [ Mañana ] 17-October-2019 20:21 GMT
useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0
```

**Comment by alikon** [comment]
please test #28991
