### ISSUE TITLE
[4.0] [IE11] Installation throwing a JS error

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28985]
### Steps to reproduce the issue

Attempt to install J4 using IE11

### Actual result

> Syntax error

![ie-error-1](https://user-images.githubusercontent.com/2019801/81331206-226a2880-9099-11ea-9f23-074da863a9d6.png)

**Comment by HLeithner** [comment]
Internet Explorer is not longer support in J4 by Production Department Motion PROD2019/005

**Comment by C-Lodder** [comment]
please reopen

**Comment by brianteeman** [comment]
I dont understand why this was re-opened
