### ISSUE TITLE
[4.0] [IE11] Frontend throwing a JS error

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28987]
### Steps to reproduce the issue

Visit the frontend of your J4 site in IE11

### Actual result

> Syntax error

![ie11-frontend-error](https://user-images.githubusercontent.com/2019801/81331453-8bea3700-9099-11ea-930c-57be21f02bba.png)

**Comment by HLeithner** [comment]
Internet Explorer is not longer support in J4 by Production Department Motion PROD2019/005

**Comment by HLeithner** [comment]
That doesn't mean we don't accept IE fixes but I would prefer not to keep the issue open.

**Comment by C-Lodder** [comment]
So you're saying that we no longer need to ship ES5 files?

**Comment by HLeithner** [comment]
As already mentioned in the other issue that's a decision of george.

**Comment by C-Lodder** [comment]
If you're unsure about that or cannot make the decision, please leave the issue open. Shipping ES5 means you support IE11

**Comment by alikon** [comment]
reopened 
waiting for a final response

**Comment by HLeithner** [comment]
There are differences between shipping es5 files and supporting. As in the motion we don't support IE11, that doesn't mean we have to make it harder for 3rd party developers. So it's a won't fix but can be fixed.

**Comment by C-Lodder** [comment]
Why ship broken ES5 code then? I really don't get it

**Comment by wilsonge** [comment]
We should try and fix this but it's definitely a lower priority issue. We should allow people to build frontend templates that work on IE11 even if we won't support IE11 in core anymore

**Comment by brianteeman** [comment]
I am assuming that this has been fixed elsewhere as I can no longer replicate the console error
![image](https://user-images.githubusercontent.com/1296369/114102925-1cd81c80-98c0-11eb-8426-fdc77173b728.png)
