### ISSUE TITLE
[4.0] [IE11] Admin login throwing a JS error

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#28986]
### Steps to reproduce the issue

Go to the admin login page in IE11

### Actual result

> Object doesn't support property or method 'forEach'

![screeny](https://user-images.githubusercontent.com/2019801/81331372-63623d00-9099-11ea-8d14-2d9a83616d4c.png)

**Comment by SharkyKZ** [comment]
I thought IE was not supported? 🤔

**Comment by C-Lodder** [comment]
The JS apparently should work in IE11

**Comment by HLeithner** [comment]
Internet Explorer is not longer support in J4 by Production Department Motion PROD2019/005

**Comment by C-Lodder** [comment]
please reopen
