### ISSUE TITLE
[4.0] Install from web - modal is not showing correct

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#28988]
### Steps to reproduce the issue

enable install from web

1) Click on any extension
2) Click on install

### Expected result

The modal is showed

### Actual result

The html of the modal is showed under the extension details

![Untitled](https://user-images.githubusercontent.com/876623/81331674-38c8b200-90a2-11ea-96cb-f68632ec650f.png)

Also install not working:

````
Uncaught TypeError: Joomla.submitbutton5 is not a function
    at HTMLInputElement.onclick (index.php?option=com_installer&view=install:349)
````

**Comment by C-Lodder** [comment]
I think this markup is coming from the JED extension. I can't find any reference to it in core

**Comment by 810** [comment]
plugins\installer\webinstaller\tmpl\default.php

**Comment by brianteeman** [comment]
Please see #26448

**Comment by C-Lodder** [comment]
https://github.com/joomla-extensions/install-from-web-client/blob/master/media/plg_installer_webinstaller/js/client.js#L297

No idea what `submitbutton4()` is supposed to do

**Comment by 810** [comment]
https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/com_installer/js/installer.es6.js#L58

**Comment by mbabker** [comment]
For the record, it's not a modal, and never was one.  The slide animations which are present when used on a Joomla 3.x installation are not there because the jQuery code was commented out without replacement and as noted in https://github.com/joomla/joomla-cms/issues/19429 haven't been there for over 2 years now.

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/28992

**Comment by alikon** [comment]
closing as we have a PR for test  #28992
