### ISSUE TITLE
[4.0] Add Copy to Clipboard button to API token

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#28995]
Make it easy to copy the API token to clipboard by adding a `Copy to Clipboard` icon button similar to the Share in Media Manager.

![clipboard](https://user-images.githubusercontent.com/368084/81423256-174ee100-9109-11ea-968a-eb239093f2a0.png)

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/29005

**Comment by richard67** [comment]
Closing as having PR #29005 .
