### ISSUE TITLE
Custom Access Levels are not being listed in category fields

### ISSUE THREAD

**Issue by htmgarcia** [joomla/joomla-cms#28999]
### Steps to reproduce the issue
1. Go to Users > Groups > New. Set "Group parent" as registered
2. Go to Users > Access levels > New. Check the custom user group from previous step.
3. Go to Content > Categories. Edit a category and set the new access
<img width="850" alt="Screen Shot 2020-05-08 at 16 50 57" src="https://user-images.githubusercontent.com/4999794/81452311-23a85d80-914c-11ea-8a41-9604024dff67.png">

4. Go to Content > Articles. In "Search tools" > Category, look for the category you edited in previous step
<img width="479" alt="Screen Shot 2020-05-08 at 16 52 02" src="https://user-images.githubusercontent.com/4999794/81452384-55212900-914c-11ea-9a84-7cb69cd2ef82.png">

### Expected result
The category with custom access level should be displayed in the category filters

### Actual result
The category with custom access level is NOT displayed in the category filters 

### System information (as much as possible)
- Joomla 3.9.18
- PHP 7.2.8

**Comment by SharkyKZ** [comment]
It's a known issue. Category field is checking against authorised view levels.

**Comment by htmgarcia** [comment]
@SharkyKZ thanks for jumping to the conversation. Is there another opened issue?

**Comment by SharkyKZ** [comment]
Assuming you experience this issue when logged in as super user there's pending PR https://github.com/joomla/joomla-cms/pull/16417 that would fix this. Though I'm not sure if it's a good idea.

For now you would have to structure your user groups or access levels in a way that super users would have access to all levels.

**Comment by brianteeman** [comment]
Closing this as it has been resolved elsewhere and is no longer reproducable
