### ISSUE TITLE
Can't change status to unfeatured after Setting status to Featured via star

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#28998]
### Steps to reproduce the issue
go to http://j4.local/administrator/index.php?option=com_menus&view=items&menutype=
click on the star for main menu.
star will change to gold indicating featured.
click star again, no change.

### Expected result

status changed to unfeatured ( gray star )

### Actual result
no change in status.

### System information (as much as possible)
[systeminfo-2020-05-08T21_42_15+00_00.txt](https://github.com/joomla/joomla-cms/files/4601817/systeminfo-2020-05-08T21_42_15%2B00_00.txt)

**Comment by Quy** [comment]
The yellow star icon designates which menu item is the current Home Page. Clicking on an empty Star icon will designate that menu item as the new Home Page. It does not represent featured.

See #28976 on changing this icon.

**Comment by brianteeman** [comment]
There is no such thing as a featured menu item

**Comment by richard67** [comment]
Closing as expected behavior.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28998">issues.joomla.org/tracker/joomla-cms/28998</a>.</sub>
