### ISSUE TITLE
[4.0] [a11y] Private Message Layout

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#28994]
### Steps to reproduce the issue
Write a private message with some text. The message looks for the receiver like this:

![screen shot 2020-05-08 at 13 13 29](https://issues.joomla.org/uploads/1/203526e4cbd9815194f19d43c3b09f70.jpg)

### Expected result
A Screen with the message, not a form with disabled input fields. 

### Actual result
The layout is a form with disabled form controls

### System information (as much as possible)
Working local on win10, xampp

**Comment by brianteeman** [comment]
I agree its an easy but I dont get why the accessibility tag

**Comment by brianteeman** [comment]
Changing all the instances of form to control in the file administrator\components\com_messages\tmpl\message\default.php should fix it for you

**Comment by chmst** [comment]
I know that it is easy but I am working on other issues. As nice task for new developers :) 

For me it is an accessibility error if a form is announced  but it is not a form at all.

**Comment by brianteeman** [comment]
> As nice task for new developers :)

Ah ok - I gave up on that idea myself when it just sat there or was fixed really badly with a hack

> For me it is an accessibility error if a form is announced but it is not a form at all.

Fair enough. Not sure I agree. I see it as a readonly form but thats not the point - you're right it is currently wrong

**Comment by Quy** [comment]
It is a form to initiate a reply or cancel. It is same as an alert with text, no fields, and buttons to choose from.

![28994](https://user-images.githubusercontent.com/368084/84403639-c83e1500-abba-11ea-849e-90f0ad3db1b4.png)

**Comment by Quy** [comment]
Also, there are no disabled inputs.

**Comment by chmst** [comment]
The issue with overlapping Text in the input field is resolved. The issue can be closed. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28994">issues.joomla.org/tracker/joomla-cms/28994</a>.</sub>
