### ISSUE TITLE
[4.0] COM_MENUS_ITEMS_SET_HOME 

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#29001]
### Steps to reproduce the issue
Install Blog Sample Data.
Go to Menus > All Menu Items
Edit Home.
Click the browser's back button so that the Home menu item is checked out.
Click the Home icon of another menu item to make it the default.
See error/success alerts.

![menu-item](https://user-images.githubusercontent.com/368084/81458942-0a0a1480-9152-11ea-80af-46301fc6c5a0.png)

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29004.
