### ISSUE TITLE
responsive tables

### ISSUE THREAD

**Issue by nenad-shone** [joomla/joomla-cms#29018]
Hi, 
I
![rt-1](https://user-images.githubusercontent.com/65110051/81494782-ba3f6080-92ab-11ea-8cd3-14e6ba4e11d0.PNG)
 installed responsive tables and everything was ok until a couple of days ago when i saw it no longer work. In the meantime, I installed a new version of joomla 3.9.18. what could be the problem?

https://welsangelsport.ch/de/shop/welsangelsport/rollen/stationaerrollen/shimano-sedona-fi

Thanks

**Comment by infograf768** [comment]
`$document->addStyleSheet($baseurl.'plugins/content/responsive-tables/responsive-tables.css');`
I guess `$baseurl` has to be defined. Please contact the plugin developer.

**Comment by coolcat-creations** [comment]
@Quy can this be closed since it's not a core issue?
