### ISSUE TITLE
tag field in template config will not save new tags

### ISSUE THREAD

**Issue by ghasemy50** [joomla/joomla-cms#29015]
### Steps to reproduce the issue
i'm use tag field in my template,
but it's just ok with existing tags, and new tags will not save.

### Expected result
created tag will remove after save template, but existing tags are ok

### Actual result
save new tag

### System information (as much as possible)
PHP Built On 	Windows NT AFZONEH-NEVIS 10.0 build 18363 (Windows 10) AMD64
Database Type 	mysql
Database Version 	5.5.5-10.4.12-MariaDB
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.2.28
Web Server 	Apache/2.4.41 (Win64) PHP/7.2.28
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.9.18 Stable [ Amani ] 21-April-2020 19:30 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0

**Comment by ReLater** [comment]
Could you please provide the XML for the used `tag` field inside `templateDetails.xml`?

**Comment by SharkyKZ** [comment]
Tags are designed to be used with UCM content items only. You'll have to create a plugin for handling your template's parameters if you want to use tags like that.

**Comment by ghasemy50** [comment]
```
<field name="tags" type="tag" label="JTAG" mode="ajax" class="inputbox small" multiple="true" />
```
i'm use this code.

**Comment by ghasemy50** [comment]
i checked it in module parameters. same problem exists.
new tags will not save

**Comment by SharkyKZ** [comment]
Already explained. Neither templates nor modules support tagging. If you want your templates/modules to support creating new tags, you'll need a plugin with `onExtensionBeforeSave` event to handle this.

Closing as expected behavior.
