### ISSUE TITLE
Problem when i'm use tag field inside repeatable field

### ISSUE THREAD

**Issue by ghasemy50** [joomla/joomla-cms#29014]
### Steps to reproduce the issue
i'm develop a template. i use this code in config tag in xml file:
```
<field name="portfolios"
	type="repeatable"
	icon="list"
	description="Enter your portfolios"
	label="Portfolios"
	default=''>
	<fieldset hidden="true" name="property" repeat="true">
		<field name="photo"
			label="Photo"
			type="media" />
		<field name="title"
			label="Title"
			size="30"
			type="text" />
		<field name="tags" type="tag" label="JTAG" mode="ajax" class="inputbox small" multiple="true" />
	</fieldset>
</field>
```

### Expected result
tag field not show currect. it will show like a multiple select with no item.

### Actual result
show a field that user can type new tag or select from list

### System information (as much as possible)
PHP Built On 	Windows NT AFZONEH-NEVIS 10.0 build 18363 (Windows 10) AMD64
Database Type 	mysql
Database Version 	5.5.5-10.4.12-MariaDB
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.2.28
Web Server 	Apache/2.4.41 (Win64) PHP/7.2.28
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.9.18 Stable [ Amani ] 21-April-2020 19:30 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0 

### Additional comments
![screen shot 2020-05-09 at 20 34 02](https://issues.joomla.org/uploads/1/bff2e9c900f2c9a5e0bf233ae95d37f9.png)

**Comment by ReLater** [comment]
The `repeatable` field will be removed in the future in favour of the `subform` field. Maybe you can give `subform` a try?

But: I confirm your issue with the `repeatable` field with the difference that I get a list of already existing tags.

![09-05-_2020_23-04-08](https://user-images.githubusercontent.com/20780646/81484868-77e53780-9249-11ea-9461-38bba32996a9.jpg)

**Comment by ReLater** [comment]
See https://github.com/joomla/joomla-cms/issues/29015#issuecomment-626236860 why creating new tags isn't possible without additional efforts.

**Comment by ghasemy50** [comment]
oops
thanks very much for introduce `subform` field.
it's very good alternative.
if `repeatable` form field will delete , so this topic can close.

**Comment by ReLater** [comment]
You can close it yourself if you want to.
