### ISSUE TITLE
Class CSS submenu Cassiopeia Joomla 4

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#29025]
Hello, I'm looking for a solution to display the sub menu in Cassiopeia. I try a lot of CSS class from Bootstrap 4, but nothing works. What are the CSS class to display the sub menu in the main menu bar?

![Annotation 2020-05-10 162043](https://user-images.githubusercontent.com/26197929/81501920-29807900-92db-11ea-9e62-ad5c172c14e1.jpg)

**Comment by richard67** [comment]
Unfortunately Cassiopeia doesn't support more than one level of menus at that module position. See my issue #22930 , which I had closed not because it was solved but because a lack of interest.

I solved it for me by making a template override for the menu module. But I am not sure if I can still find it, it more than 1 year ago, maybe I have deleted it meanwhile.

**Comment by richard67** [comment]
@ciar4n @C-Lodder One of you both maybe has interest in making menus with more than one level useful in Cassiopeia, e.g. with dropdowns, especially in the "menu" position?

**Comment by Magnytu2** [comment]
I'm disappointed ... How is it possible that 2 years later there is no solution ? How did you measure that the under menu sounds uninteresting ?

**Comment by richard67** [comment]
People focused a bit on the backend template ;-)

**Comment by richard67** [comment]
Or maybe @coolcat-creations would like to work on it?

Unfortunately I am not good in js and css stuff.

Cassiopeia seems to user only parts of Bootstrap 4, so that e.g. `nav-pills` also doesn't work anymore on any module position.

**Comment by richard67** [comment]
I found my old override now, it made it work for the "menu" module position. Was an override of the "navbar.php" file of mod_menu.

Update: Don't even find the original file anymore. Seems there has been changed much since I've made my override.

Update: I see it was an alternative layout for mod_menu, therefore the new file name.

**Comment by richard67** [comment]
Will see if I can find some time to work on it.

**Comment by coolcat-creations** [comment]
With a little handover from @C-Lodder or @ciar4n I can work on the submenu. 

I think it's an important feature and obligatory to have in the frontend template, also the possibilty to add subtitles and modules in the menu to create something like a megamenu...

I heard the frontend template is css grid only, but I find bootstrap folders in the scss there, thats why I would need an intro how everything is supposed to be.

**Comment by Magnytu2** [comment]
I don't want to force anyone to work on that. But many people use Joomla's default template. Association, club, etc... It's a big miss I think.

**Comment by richard67** [comment]
If we wanna use bs4 we just have to use special class names in the navbar area

**Comment by brianteeman** [comment]
and this is why I said we are nowhere near a beta because no one has really looked at the front end for a very long time

**Comment by richard67** [comment]
@Magnytu2 You do not force us to anything. You remind us, and I think we should work on that. I have a horizontal menu on my J3 private website with submenus, and I want to see that on J4 in future.

**Comment by richard67** [comment]
@brianteeman 100% agree: Nobody has looked on the frontent for a very long time.

**Comment by Magnytu2** [comment]
That's why I play with Joomla 4 regularly.

**Comment by Magnytu2** [comment]
![Annotation 2020-05-10 170740](https://user-images.githubusercontent.com/26197929/81502868-f640e880-92e0-11ea-86f1-616e00661828.jpg)

**Comment by richard67** [comment]
Why closed?

**Comment by Magnytu2** [comment]
Oups ...

**Comment by Magnytu2** [comment]
Sorry I do not master Github at all ...

**Comment by richard67** [comment]
Reopened it for you.

Thanks for testing J4 and reporting.

**Comment by ciar4n** [comment]
> I heard the frontend template is css grid only, but I find bootstrap folders in the scss there, thats why I would need an intro how everything is supposed to be.

The main layout of modules/component area is set using CSS grid. Everything else is still largely styled with Bootstrap. The template still looks to be loading the entire Bootstrap library so no real reason not to use https://getbootstrap.com/docs/4.0/components/navbar/

**Comment by Magnytu2** [comment]
I've tried a lot of its CSS class, but nothing works. Or I didn't understand...

**Comment by ciar4n** [comment]
Looking at the html, it appears to be an issue between invalid bootstrap markup and conflicting template css.

**Comment by Magnytu2** [comment]
Hello using Joomla 4 beta 1, I don't see any change. Do you have a solution please?

**Comment by Quy** [comment]
Please test PR #29413
