### ISSUE TITLE
Effect apply PR 29020

### ISSUE THREAD

**Issue by adj9** [joomla/joomla-cms#29021]
### Steps to reproduce the issue
1. Apply the PR [#29020](https://github.com/joomla/joomla-cms/pull/29020)
2. Crete a article with an img
3. Click on dashboard
disappearing the PR the dashboard resizes

### Expected result
Home dashboard normal

### Actual result
![image](https://user-images.githubusercontent.com/5918444/81496813-b36c1a00-92ba-11ea-95e1-0f70d163b049.png)

### Software Requirements
- Web site
- Chrome 81.0.4044.138 (Build ufficiale) (a 64 bit)
- macOS Catalina 10.15.3

**Comment by coolcat-creations** [comment]
@adj9 Why don't you comment that on the PR itself? :-)

**Comment by adj9** [comment]
Yes, I could do it on PR, but it seems to me a problem separated from.
The patch only brings about a variation of PHP.

However, I will take the advice into account.

**Comment by Quy** [comment]
I don't see how this PR would have caused this. Please download the package installer with the patch included to see if you can reproduce it. https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/29020/downloads/32008/

**Comment by Quy** [comment]
Confirmed and reported https://github.com/joomla/joomla-cms/pull/29020#issuecomment-626362060.
