### ISSUE TITLE
[4.0] Tinymce Editor lost input text on save if in source edit more

### ISSUE THREAD

**Issue by HRIT-Florian** [joomla/joomla-cms#29028]
### Steps to reproduce the issue
1 Go to article create and click the "Toggle Editor" button at tinymce editor to switch to source edit.
OR
1 Go to modules, new custom modul and click on the "Toggle Editor" button at tinymce editor to switch to source edit.

2 Type any text to the editor textare input and try saving the content in the blank texarea source mode. 
3 The typed text is lost.

Note: These effects only at the blank textare mode without the tinymce toolbar, if in source editing mode.

### Expected result
Text should be saved no matter in which editor mode

### Actual result
Text is lost

### System information (as much as possible)
Joomla! 4.0.0-beta1-dev Development [ Mañana ] 17-October-2019 20:21 GMT 

### Additional comments
Attached two screenshots to reproduce the issue
![test1](https://user-images.githubusercontent.com/12803406/81507975-52b40000-9301-11ea-91d8-dabb1afcbf24.jpg)
![test2](https://user-images.githubusercontent.com/12803406/81507977-534c9680-9301-11ea-9501-36cfe816c929.jpg)

**Comment by Quy** [comment]
Duplicate #26579

**Comment by HRIT-Florian** [comment]
Okay, thanks, sorry, I didn't see that. I close this ticket
