### ISSUE TITLE
[4.0] Missing language strings in Extension Updates

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29039]
### Steps to reproduce the issue

1. Install an extension that has an update server
2. Go to `/administrator/index.php?option=com_installer&view=update`
3. Hover over the extension name

### Expected result

Tooltip shown with the extension description

### Actual result

Tooltip shown with the language constant

![Untitled](https://user-images.githubusercontent.com/2019801/81666282-bf321a80-9439-11ea-9751-fa9ccd8b760c.png)

**Comment by infograf768** [comment]
Is'nt it rather the `Text::` missing?

`<?php echo $item->description; ?>`

to
`<?php echo Text::_('$item->description'); ?>`

**Comment by infograf768** [comment]
See PR https://github.com/joomla/joomla-cms/pull/29067
