### ISSUE TITLE
[4.0] [RFC] Markdown support in changelog

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29038]
### Is your feature request related to a problem? Please describe.

Personally I don't know anyone who uses XML, but a lot of developers/projects use markdown for their changelogs.

What are people's thoughts on Joomla supporting markdown for the changelog as an **ALTERNATIVE**?

### Describe the solution you'd like

- You add the `<changelog>` to your extension XML as per normal, but would reference a `.md` file instead
- The system would only check that the file exists, unlike the current implementation which additional, but unecessary checks
- The markdown would then be parsed and loaded in the modal
- You would also be able to see the entire changelog, unlike the current implementation which only displays the current version.

If this is something Joomla wants, I'm happy to submit a PR

**Comment by ReLater** [comment]
If it's meant as an **additional** feature and does not remove the current implementation OK for me.

(I have spent a lot of time to change my changelogs.xml to fit for Joomla 4 and my changelog reader.)

**Comment by joeforjoomla** [comment]
The changelog is perfect and flexible with the current XML implementation. I don't see a sense about replacing it with a .md file.

**Comment by C-Lodder** [comment]
@joeforjoomla I never said anything about replacing the XML implementation. This would be an alternative.

**Comment by alikon** [comment]
nice to have for me
