### ISSUE TITLE
[4.0] Font size in TinyMCE Joomla 4

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#29031]
Hello everyone, Jooma 4 has been developed to be accessible to everyone. Except if the template administrator has taken a large size, the font in the editor is still as small. I think it should be increased by two sizes and perhaps with a slightly more visible font.

![Annotation 2020-05-11 102017](https://user-images.githubusercontent.com/26197929/81540499-094fc900-9372-11ea-81ab-9ecd7b0b7fac.jpg)

**Comment by adj9** [comment]
As for the accessibility of the articles, I did some tests with the emoticons.
I am using TinyMCE.
To associate a text with the emoticon, I right-clicked on the emoticon and clicked on Insert / editg link. I think it is necessary to fill in the text field (initially empty).
Then I inserted a text:
1. Right click on the smile
2. Insert / editg link
3. I have filled in the title field
4. I clicked on the save button
5. I saved the article
<img width="501" alt="Schermata 2020-05-11 alle 17 22 49" src="https://user-images.githubusercontent.com/5918444/81582540-75512200-93b0-11ea-8a35-e8d40228846a.png">

Returning to the Insert / edit link, the title field is empty.

### HTML Inspect
<img width="685" alt="Schermata 2020-05-11 alle 17 10 37" src="https://user-images.githubusercontent.com/5918444/81583318-7df62800-93b1-11ea-9450-ec31784ab429.png">

### Actual result
Returning to (2) it does not save it (empty field).

### Expected result
I expected the text in the window and a variation of the HTLM.

**Comment by brianteeman** [comment]
@adj9 thanks for testing but please always create a new issue when your are reporting something different

**Comment by adj9** [comment]
OK, in fact the object deviates a little.

It could come in "features for accessibility".

**Comment by Magnytu2** [comment]
Bonjour, have you looked at this problem? It's really too small compared to the environment and accessibility of Joomla 4.

**Comment by Magnytu2** [comment]
@brianteeman Hello I found where this finds this value that for me, for everything remains balanced be at 16px.
![Articles__New_-_Cassiopeia_11092020_-_Administration](https://user-images.githubusercontent.com/26197929/92998905-17c71080-f51d-11ea-83a0-441d9cf0782f.jpg)

**Comment by bato3** [comment]
Tis is result, that tinymce use his own style. Now you can create `/templates/cassopea/css/editor.css` with definitions it should be OK

(see related issue)

**Comment by richard67** [comment]
We have a pull request meanwhile which adds an editor.css for the Cassiopeia template: #31828 .

@Magnytu2 Could you test if that solves your issue here, too? It either needs to have a git clone and npm for testing, or you have to use the packages which have been built for that PR.

**Comment by brianteeman** [comment]
@richard67 it's a different request. #31828 correctly makes the css in the editor match the site template. This request was for the text in the editor to be displayed (in the editor) larger.

**Comment by Magnytu2** [comment]
Hello, I just tested and am not having a problem. It's nice, it's nicer to write and see the text bigger. But I believe it was already fixed in the previous version. I just regret the text which is a bit too stuck on the left. Thank you for your work.

**Comment by richard67** [comment]
So we can close this issue?

**Comment by Magnytu2** [comment]
Yes

**Comment by richard67** [comment]
Closing as having been solved with a past change. I assume it was #31520 where we had increased font size with the system template's editor.css. Thanks for reporting back.
