### ISSUE TITLE
[4.0] Update sites for templates

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29032]
### Summary

Minimum Extension Stability:  set to `Alpha`
URL: `/administrator/index.php?option=com_installer&view=update`

There seems to be some sort of issue with Update Servers for templates in Joomla 4. Having deployed an update server, I've cleared the cache and clicked "Find Updates".

Looking at the `#__updates` table, I can see the template listed, however `extension_id` is set to `0`, and the `client` value `0` instead of `1`, so the update won't be shown.

The `#__update_sites_extensions` is showing the correct `extension_id` value.

Does this feature not support templates?

### System information (as much as possible)

- PHP 7.4
- Joomla 4.0-dev branch (latest)

**Comment by SharkyKZ** [comment]
In the update XML `client` should be the name, not the ID of the client.

**Comment by C-Lodder** [comment]
@SharkyKZ 

https://docs.joomla.org/Deploying_an_Update_Server

client – Required for modules and templates as of 3.2.0. – The client ID of the extension, which can be found by looking inside the #_extensions table. To date, use 0 for "site" and 1 for "administrator".

**Comment by C-Lodder** [comment]
@SharkyKZ Turns out you were right. Changing the `client` to `administrator` works. It appears the documentation needs updating
