### ISSUE TITLE
missing robots.txt in Joomla_3.9.18-Stable-Full_Package.zip

### ISSUE THREAD

**Issue by pieter-groeneweg** [joomla/joomla-cms#29047]
I noticed there is not robots.txt in the package. Only a robots.txt.dist
Is that correct?
Is there a reason for that, I could not find it. It usually was there.
But of course I may have missed a moment it disappeared for a reason.

Tx,

**Comment by SharkyKZ** [comment]
It's correct. `robots.txt.dist` file is renamed to `robots.txt` during installation. It is this way to prevent overwriting your customized `robots.txt` when updating Joomla.

**Comment by zero-24** [comment]
Closing as this is expected behavior as pointed out by @SharkyKZ

**Comment by pieter-groeneweg** [comment]
oh really that did not happen during my last install then... (clean install, no update)..
 this was apache mod_php execution mode, can have anything to do with that?

**Comment by zero-24** [comment]
No that should not change anything.

**Comment by pieter-groeneweg** [comment]
weird then.. I will see If I can reproduce this tomorrow

**Comment by zero-24** [comment]
Sure maybe you have a Extension installed that did such things? When was the last time you installed a new site and got the robots.txt?
