### ISSUE TITLE
[4.0] Menu toggle label too large

### ISSUE THREAD

**Issue by adj9** [joomla/joomla-cms#29046]
If you work with the toggle menu, closed you have the labels of the items that appear when the mouse does not pass near the toggle.

The graphics are not the best.

### Expected result
smaller voices.

### Actual result
![Untitled](https://user-images.githubusercontent.com/5918444/81733679-b28de080-9492-11ea-866d-58fb4f846187.gif)

### Environment & Software Requirements
- Web site
- Safari 13.0.5
- macOS Catalina 10.15.3

**Comment by brianteeman** [comment]
Please see #29023

**Comment by Quy** [comment]
Fixed in #29023
