### ISSUE TITLE
[4.0] [responsive] Sidebar pushes content

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29059]
### Steps to reproduce the issue

1. Go to your admin dashboard
2. Reduce viewport width to 768px

**You'll already notice a small horizontal scrollbar**

3. Expand the sidebar menu

### Expected result

Content responds to the adjusted space

### Actual result

Horizontal sidebar increases and when used, displays whitespace

![menu](https://user-images.githubusercontent.com/2019801/81901871-1c9fa600-95b7-11ea-8ba2-b89e4ddc7ed9.gif)

**Comment by ghost** [comment]
Can't confirm.

**Comment by Quy** [comment]
Confirmed.

![29059](https://user-images.githubusercontent.com/368084/94179942-1d442500-fe52-11ea-8a7a-8c8164e34064.png)

**Comment by brianteeman** [comment]
Not sure when this was changed but testing with a screen size of 763px I can no longer replicate this

![overf](https://user-images.githubusercontent.com/1296369/128629896-b60b573e-2b48-4f61-b880-bc2e6a8ba9ee.gif)

**Comment by chmst** [comment]
In newer Versions this issue is resolved.
