### ISSUE TITLE
[4.0] [mobile] Add module view

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29064]
### Steps to reproduce the issue

1. Go to `administrator/index.php?option=com_modules&view=select`
2. Reduce viewport width to something like 480px

### Actual result

![module](https://user-images.githubusercontent.com/2019801/81904296-fc71e600-95ba-11ea-8da7-ce66bc32b948.png)

**Comment by brianteeman** [comment]
grrh - i am 99% certain this was correct when I submitted the code

**Comment by Quy** [comment]
Please test #29527
