### ISSUE TITLE
[4.0] Unecessary files being generated

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29092]
### Steps to reproduce the issue

Run `node build.js --copy-assets` from your terminal 

### Actual result

If you looks inside `media/system/js`, you'll notice a directory called `core.es6`.
This directory is unecessary and contains invalid files

**Comment by HLeithner** [comment]
Can you elaborate this a bit?

**Comment by C-Lodder** [comment]
How can I elaborate?

Run `node build.js --copy-assets` and look at the directory I mentioned. I shouldn't be generated

Not sure how else to explain it

**Comment by C-Lodder** [comment]
![Untitled](https://user-images.githubusercontent.com/2019801/81916613-ecaecd80-95cb-11ea-868c-dd05a7bd29ad.png)

**Comment by infograf768** [comment]
These come from https://github.com/joomla/joomla-cms/pull/26300
I guess they are supposed to replace most of core.es6.js which is still present in build.
I indeed wonder also why we have both in media/ as core.es6.js is recomposed there with their content.

**Comment by wilsonge** [comment]
I believe the aim was to conditionally load the es6 files on machines that support ES6 (basically everything we run core on at the moment out of the box). Can you explain why you think these files are invalid. I'm often using them to debug things (as it's the equivalent of the raw files used before babel transpiling)

**Comment by HLeithner** [comment]
The files are invalid because they are compiled to core.es6.js, that are only the plain source files for copyright reasons.

**Comment by C-Lodder** [comment]
@wilsonge last time I checked, there was no such thing as a `.es6` file extension.

Note `.es6` vs `.es6.js`

**Comment by wilsonge** [comment]
Ahh sorry I understand now. Yup that's all invalid and rubbish indeed

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/31201.
