### ISSUE TITLE
[4.0] TypeError: filteredByCaption is null

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#29100]
### Steps to reproduce the issue
Enable `Debug System`.
Go to `Content > Fields`.
View browser's console.

### Actual result
searchtools.js:285:11
> filteredByCaption.parentNode.removeChild(filteredByCaption);

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29066.
