### ISSUE TITLE
[3.9] Double (identical) line in the user registration action log

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#29114]
### Steps to reproduce the issue
1. Turn on the registration on the site and the **Self** value for parameter **New User Account Activation**.
2. Register on the site with a real email address. Follow all instructions to activate your account.
3. Go to the **User Actions Log** section and pay attention to the lines.

![ddfdfdf](https://user-images.githubusercontent.com/8440661/82098123-fee45500-970c-11ea-8954-da736cca3335.png)

### Expected result
1 entry in the action log - AFTER account activation

**OR**

1 entry in the action log - BEFORE account activation and 1 entry that the user has ACTIVATED his account.

### Actual result
2 identical entries in the action log - BEFORE and AFTER account activation.

### System information (as much as possible)
Joomla 3.9.18
PHP 7.3.2

### Additional comments
I assume that for the expected option (1) it is more difficult to implement the logic, since there are other actions that the user performs before activating the account (e.g. privacy policy and terms). Therefore, in my humble opinion, option (2) would be the best solution expected.

The same situation is with us for the case when the administrator activates the user account, but BEFORE this, the user is registered (1), and then activates (2) his account - again 2 identical lines in the action log.

**Comment by alikon** [comment]
> The same situation is with us for the case when the administrator activates the user account, but BEFORE this, the user is registered (1), and then activates (2) his account - again 2 identical lines in the action log.

when an admin activate the user there 2 different logs 

![Screenshot from 2020-05-16 08-56-24](https://user-images.githubusercontent.com/181681/82113065-3118a580-9753-11ea-8f4f-fa0e37bcea55.png)

**Comment by Kostelano** [comment]
I just repeated the test: registration of the user with ADMIN activation:

![dfsdfsdfsdf](https://user-images.githubusercontent.com/8440661/82117146-10624700-9777-11ea-85e6-7f8530ab7463.png)

Again 2 lines about registration, then a line about account activation by ADMIN.
The combination of parameters in the User Manager:

![adfgadfga](https://user-images.githubusercontent.com/8440661/82117141-09d3cf80-9777-11ea-8b22-5fcc9a8157c9.png)

**Comment by alikon** [comment]
please test #30725
