### ISSUE TITLE
[4.0] Mobile admin login screen

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#29119]
Depending on the size (height) of the mobile device the Site Name may be off the screen as it is below the login box.

Also the module does move to directly below the site title but the height of the sidebar is not reduced.

![chrome_2020-05-16_17-32-57](https://user-images.githubusercontent.com/1296369/82125091-72cd3e80-979b-11ea-8462-d0ad76164396.png)

![chrome_2020-05-16_17-33-15](https://user-images.githubusercontent.com/1296369/82125089-7234a800-979b-11ea-87f5-faa2c8f7730d.png)

**Comment by ghost** [comment]
Issues confirmed.

**Comment by drmenzelit** [comment]
Closing this as we have a PR #32634
