### ISSUE TITLE
[4.0] Notice in installer script 

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#29116]
### Steps to reproduce the issue
On a fresh installation try to install for example the patchtester component. 

Notice: on line 148 of libraries\src\Installer\InstallerScript.php ![screen shot 2020-05-16 at 07 50 35](https://issues.joomla.org/uploads/1/2d10da47611b7f62b13bf7123acd21ed.jpg)

**Comment by zero-24** [comment]
What notice? Seems this is not the complet error message

**Comment by chmst** [comment]
Trying to access array offset on value of type null in  line 148 of libraries\src\Installer\InstallerScript.php

Cannot be reproduced, once the installation is done.

**Comment by zero-24** [comment]
Hmm can you add a debugger here:
https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Installer/InstallerScript.php#L147-L148

And check what is in the $manifest variable? Maybe a var_dump ?

**Comment by chmst** [comment]
I have to set up a clean installation, as this happens only once. The problem seems to be the manifest cache.

**Comment by zero-24** [comment]
sounds like a valid issue so we need to take care of that and check wehether the old version is set. On a new install this can never be the case. So an if check should do the trick i guess.

**Comment by SharkyKZ** [comment]
I can reproduce this on staging. Happens with extensions that can be discovered (files exist but extension is not installed).

To reproduce:

1) Download Patch Tester.
2) Drop files from `admin` folder of the package to `administrator/components/com_patchtester`.
3) Install Patch Tester.

**Comment by zero-24** [comment]
Ok so this should be fixed in staging with the if check mention above right

**Comment by zero-24** [comment]
Closing here is a PR for staging that should than be merged up to 4.x; https://github.com/joomla/joomla-cms/pull/29207
