### ISSUE TITLE
[4.0] Menu Dashbord - too many settings

### ISSUE THREAD

**Issue by od-martin** [joomla/joomla-cms#29130]
### Steps to reproduce the issue

All of the website's settings are displayed under the "Menu" dashboard. 

Doesn't it make sense to only have the menu settings on the menu dashboard

### Expected result

![pic_02](https://user-images.githubusercontent.com/60319648/82217754-30327000-991b-11ea-8fdd-b48ad31b1038.jpg)

### Actual result

![pic_01](https://user-images.githubusercontent.com/60319648/82217523-d5991400-991a-11ea-83f6-6bfa23e4dd73.jpg)

**Comment by SharkyKZ** [comment]
I can't reproduce the issue. Does this happen on a clean installation?

**Comment by od-martin** [comment]
It is the last Nighly Build

**Comment by 810** [comment]
I can't reproduce this also:
![image](https://user-images.githubusercontent.com/876623/82224083-bc489580-9923-11ea-8c4a-7e133610bb6d.png)

**Comment by chmst** [comment]
Same result as @810 on a fresch installation. Only Menus and Site modules are shown.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29130">issues.joomla.org/tracker/joomla-cms/29130</a>.</sub>

**Comment by brianteeman** [comment]
Please retry with a fresh install - not an upgrade

**Comment by od-martin** [comment]
Yesterday a new installation was made with the same result.

Installed the new build today without any problems.
