### ISSUE TITLE
[4.0] [cassiopeia] Spacing between control groups

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29138]
### Steps to reproduce the issue

1. Login to the **frontend** of your site
2. Go to edit any article
3. Navigate to the `Publishing` tab

### Expected result

Spacing between each control group

### Actual result

No spacing:

![spacing](https://user-images.githubusercontent.com/2019801/82298983-d37f9580-99ac-11ea-8d7a-601b53ea38d8.png)

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/issues/29470#issuecomment-696548829

**Comment by drmenzelit** [comment]
That has been corrected on the Cassiopeia repo
https://github.com/joomla/cassiopeia/pull/99
