### ISSUE TITLE
[4.0] Font size accessibility setting - button background

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29133]
### Steps to reproduce the issue

1. Go to your accessibility settings in the backend
2. Enable `Increase Font Size`
3. Go back to the dashboard and click the `Add module to the dashboard` button at the bottom.

### Actual result

You'll notice a 1px gap below the bottom or the red block and button border

![test](https://user-images.githubusercontent.com/2019801/82232004-ea2ed980-9925-11ea-8778-0d035fb50453.png)

**Comment by brianteeman** [comment]
I can confirm the problem BUT its not related to the increase font size. The 1px gap is always visible

**Comment by brianteeman** [comment]
Closer inspection shows that the problem is that  the wrong classes are being used here
https://github.com/joomla/joomla-cms/blob/2e095fbbae1026a1811ceed686aeff8f00cc4775/administrator/components/com_cpanel/tmpl/cpanel/default.php#L43-L46

**Comment by ghost** [comment]
Can't confirm:
![image](https://user-images.githubusercontent.com/70466955/94000671-c7ab4200-fd97-11ea-9035-f85ab77c98fb.png)

**Comment by C-Lodder** [comment]
@brianteeman @wilsonge wasn't this fixed a while back?

**Comment by wilsonge** [comment]
Yup
