### ISSUE TITLE
[4.0] "Highlight Links" changes padding for dropdown items

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29132]
### Steps to reproduce the issue

1. In the backend, go to **User Menu** (_top right_) >> **Accessibility Settings**
2. Enable the `Highlight Links` option
3. Click `Close`
4. Open the **User Menu** or **Post Installation Message**s dropdown (top right)

### Actual result

The dropdown items have smaller padding

### Screenshot (before and after)

![screeny](https://user-images.githubusercontent.com/2019801/82230481-b18e0080-9923-11ea-95f5-a5316a9b3a3e.png)

**Comment by Quy** [comment]
Dropdown removed in PR #29135.

**Comment by C-Lodder** [comment]
@Quy This issue also appies to the `User Menu`. Please reopen.

**Comment by ghost** [comment]
Issue confirmed (`User Menu`).

**Comment by Quy** [comment]
Closing as this is no longer reproducible. Thanks for the report.

![29132](https://user-images.githubusercontent.com/368084/120827684-8e26fb00-c510-11eb-97eb-7fe31e0e7118.jpg)
