### ISSUE TITLE
[4.0] [cassiopeia] "x" buttons have small click areas

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29137]
### Steps to reproduce the issue

1. Login to the **frontend** of your site
2. Go to edit any article
3. Navigate to the `Publishing` tab

### Actual result

The click area for the "x" buttons is extremely small.

![click](https://user-images.githubusercontent.com/2019801/82299291-3e30d100-99ad-11ea-8593-00753157b5d5.png)

**Comment by ghost** [comment]
~~Can't confirm.~~

**Comment by C-Lodder** [comment]
@Formatio-hippocampi What can't you confirm? How big in the click area for you?

**Comment by ghost** [comment]
> How big in the click area for you?

Big enough that i have no problem to click, but that can be different feeling.

**Comment by C-Lodder** [comment]
The click area for the "x" on the dropdown is 20 x 20px, which fails WCAG 2.1 standards

**Comment by ghost** [comment]
Didn't noticed its about WCAG-standards.

**Comment by brianteeman** [comment]
The relevant WCAG section is https://www.w3.org/WAI/WCAG21/quickref/#target-size

This is a AAA requirement - so nice to fix but we are only aiming at AA level

**Comment by chmst** [comment]
The contrast ratio is far too low there. This at least must be done

**Comment by Quy** [comment]
It is larger now. OK to close?

![29137](https://user-images.githubusercontent.com/368084/102643935-e27e2000-4114-11eb-85d9-02ba09ba1ae4.png)
