### ISSUE TITLE
[4.0] [cassiopeia] Spacing between buttons

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29139]
### Steps to reproduce the issue

1. Login to the **frontend** of your site
2. Go to edit any module

### Actual result

There is no spacing between the toolbar buttons as shown in the screenshot

![buttons](https://user-images.githubusercontent.com/2019801/82299463-77694100-99ad-11ea-80fb-3a5e48d419dd.png)

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29143.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29139">issues.joomla.org/tracker/joomla-cms/29139</a>.</sub>
