### ISSUE TITLE
[4.0] Media Field is totally broken

### ISSUE THREAD

**Issue by dgrammatiko** [joomla/joomla-cms#29147]
### Steps to reproduce the issue
Download an image from Unsplash.com preferably with a file size bigger than 2MBb. Copy the file to the `images` folder. Try to use it as an intro or full text image.

### Expected result
Works

### Actual result
Javascript error (unhandled Promise Reject) due to Server error

**Comment by wilsonge** [comment]
So the good news is the media field is just missing an edge case for when you haven't selected an image - see the fix in https://github.com/joomla/joomla-cms/pull/29221

The bad news is that the media manager app is actually the thing that is "totally broken". It doesn't seem to attach the click events until the images have fully finished loading (i.e. this is some sort of race condition). Obviously not a solution but if you wait in the modal for a few seconds after it loads and then click the image everything is good.

**Comment by dgrammatiko** [comment]
I will consider all the Form Fields with hardcoded Font awesome classes as broken but anyways there is a PR for the weird behaviours #29256
