### ISSUE TITLE
[4.0] Media Manager - Can't preview entire image

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29149]
### Steps to reproduce the issue

1. Download https://unsplash.com/photos/xnEZYWmfPwU/download?force=true (original size)
2. Upload to the Media Manage or place in your `images` directory
3. Double click the image to preview it

### Expected result

Full image is shown (scaled down) or the ability to move the image about

### Actual result

Half the image is cropped and you cannot scroll down to view the other half

**Comment by ghost** [comment]
Issue confirmed.

**Comment by brianteeman** [comment]
I am not a css gut but the problem is valid and is coming from 
.media-preview-modal .modal-dialog {
 
```
.media-preview-modal {
  color: $modal-preview-text-color;

  .modal-dialog {
    max-width: 70vw;
    max-height: 70hw;
}
```

I can make it nice for portrait images or landscape images but not both. I am sure a css guru can fix it

**Comment by Quy** [comment]
Please test PR #33323
