### ISSUE TITLE
[4.0] [cassiopeia] JS error after cancelling changes in module edit

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29140]
### Steps to reproduce the issue

1. Login to the frontend of your site
2. Hover over one of the top menu items:

![screeny1](https://user-images.githubusercontent.com/2019801/82299893-ff4f4b00-99ad-11ea-92da-1ae37a4e0f42.png)

3. Change some of the options. In my case, I changed the `Title` switcher
4. Click `Cancel`

### Expected result

Goes back to the previous page without saving changes

### Actual result

Throws a JS error, coming from `validate.js`

![screeny2](https://user-images.githubusercontent.com/2019801/82300048-37ef2480-99ae-11ea-9cb4-85c6140fe39f.png)

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29141.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29140">issues.joomla.org/tracker/joomla-cms/29140</a>.</sub>
