### ISSUE TITLE
[4.0] Media Manager - renaming a file

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29154]
### Steps to reproduce the issue

1. Go to the media manager
2. Hover over an image and click the `rename` button

### Actual result

The file extension is cut off

![screeny](https://user-images.githubusercontent.com/2019801/82327320-1efa6980-99d6-11ea-87ae-e0dc98621156.png)

**Comment by Quy** [comment]
Please test PR #29212
