### ISSUE TITLE
[4.0] Media Manager - deleting multiple items

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29152]
### Steps to reproduce the issue

1. Go to the Media Manager
2. Select 2 or more images and click `Delete`

### Expected result

A single alert

### Actual result

- 1 hidden alert
- 1 visible alert

![screeny](https://user-images.githubusercontent.com/2019801/82324251-3edb5e80-99d1-11ea-9922-f2bc02639406.png)

**Comment by ghost** [comment]
Can't confirm.

![Screen Shot 2020-09-23 at 12 04 41](https://user-images.githubusercontent.com/70466955/93998662-228f6a00-fd95-11ea-8c28-1917d6ba9abe.png)

**Comment by micker** [comment]
hello issue confirmed for me
see in action
https://www.loom.com/share/ef9058e93cef4ed3aff6ffd6b40932f8

**Comment by Quy** [comment]
Please test PR #32868
