### ISSUE TITLE
[4.0] Media Manager - Missing FA icon

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29150]
### Steps to reproduce the issue

1. Open any article in the Article Manager
2. Navigate to the `Images and Links` tab
3. Click the `select` button under `Full Article Image` (which will open the Media Manager)
4. Select an image

### Actual result

You'll notice a missing FA icon as shown in the screenshot

![Screenshot_2020-05-19 Articles Edit - Joomla 4 - Administration](https://user-images.githubusercontent.com/2019801/82323711-60881600-99d0-11ea-8190-f28bb24c326c.png)

On a side note, this also results in a JS warning showing in the console:

> Empty string passed to getElementById()  ---- skipTo.js : 454:28

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29153.
