### ISSUE TITLE
[4.0] [RFC] Media Manager - share a link

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29155]
In the Media Manager, if you hover over an image and click the `anchor` icon, a modal is presented.

You have to click the `Get a shareable link` button which then presents the link and button to copy it

Is there any need for the first modal?

![screeny3](https://user-images.githubusercontent.com/2019801/82327626-97f9c100-99d6-11ea-9357-be6eaae10d06.png)

**Comment by dgrammatiko** [comment]
> Is there any need for the first modal?

For local files no, but the button inside the modal will resolve the link for externally store images (eg dropbox). Of course it can be done with a simple promise...
