### ISSUE TITLE
[4.0] Media Manager - Toolbar button spacing

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29151]
### Steps to reproduce the issue

1. Open any article in the Article Manager
2. Navigate to the `Images and Links` tab
3. Click the `select` button under `Full Article Image` (which will open the Media Manager)

### Actual result

There's no spacing between the toolbar buttons

![1](https://user-images.githubusercontent.com/2019801/82323785-7564a980-99d0-11ea-92b9-d87d9af56707.png)

**Comment by Quy** [comment]
Duplicate #29219

**Comment by C-Lodder** [comment]
The other issue was a duplicate, but no worries

**Comment by brianteeman** [comment]
I am guessing @quy _chose_ mine because it pointed out where the problem is
