### ISSUE TITLE
[4.0] Media Manager - image rotation causes content jump

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29156]
### Steps to reproduce the issue

1. Go to edit an image in the Media Manager
2. Click the `Rotate` tab
3. Click the buttons `0`, `90`, `180`, `270` to rotate the image

### Expected result

The content does NOT jump. Nicer experience for the user.

### Actual result

The content jumps

**Comment by regularlabs** [comment]
Try the resizing sliders (which have styling issues of their own too)!
Controls should be on the side or top.

**Comment by particthistle** [comment]
Good suggestion @C-Lodder
Stacking the controls to one side as @regularlabs suggests would be good as it stops the controls jumping below the image.

Some additional notes as I've looked up what was in the queue for Rotate Images after testing #30511 tonight and finding some issues on Rotate while testing. Making some notes to try and come back and create a PR later.

* There's an issue when using the angle input to rotate the image in that it keeps the original image size as the crop box.
* A Rotating slider like the Resizing sliders on previous tab could be also added.
* There's control-labels with HR (may be related to the columns vs being coded in) under each grid column, which then don't close up the controls as neatly as the Crop view does on Mobile.

![29156](https://user-images.githubusercontent.com/5515866/93669241-1fb32180-fad6-11ea-9337-96b00e55f88d.jpg)

**Comment by HLeithner** [comment]
closed because of PR #31830
