### ISSUE TITLE
[4.0] Media Manager - image rotation - JS error

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29157]
### Steps to reproduce the issue

1. Go to edit an image in the Media Manager
2. Click the `Rotate` tab
3. Click the buttons `0`, `90`, `180`, `270` to rotate the image

### Actual result

> TypeError: c.querySelector(...) is null -- rotate.min.js:1:1416

**Comment by Quy** [comment]
PR #30593
