### ISSUE TITLE
[4.0] Media Manager - NS_ERROR_NOT_AVAILABLE

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29158]
### Steps to reproduce the issue

1. Open an image in the Media Manager
2. Go to the `Resize` tab
3. Drah the `height` down to `0`
4. Go to the `Crop` tab, then directly back to the `Resize` tab
5. Attempt to change the width or height

### Expected result

Image resizes

### Actual result

JS error thrown

> NS_ERROR_NOT_AVAILABLE --  resize.min.js

**Comment by ghost** [comment]
Issue confirmed.
