### ISSUE TITLE
[J4][Atum] The SHOW-ON function does not work when the BTN-GROUP class is specified.

### ISSUE THREAD

**Issue by korenevskiy** [joomla/joomla-cms#29168]
### Steps to reproduce the issue
When creating a module, I place different types of fields in XML.
The `showon=` function for fields stops working when the `btn-group` class is specified for the control field.

```
<field
    name="categories_show" 
    type="radio"
    class="btn-group btn-group-yesno" 
    label="[[%1:]] [[%2:]],JCATEGORIES,JSHOW" 
    default="0">
    <option value="1">JENABLED</option>
    <option value="0">JDISABLED</option>
</field>    
```
The field at the bottom is always hidden, and the field at the bottom will never be displayed in the interface again.
```
<field name="categories_order" type="number" default="5" label="JGLOBAL_CATEGORY_MANAGER_ORDER"   
	showon="categories_show:1"/> 
```

**Comment by Quy** [comment]
Duplicate #27555
