### ISSUE TITLE
[4.0] Codemirror plugin - JS error when updating Key Map field

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29178]
### Steps to reproduce the issue

1. Go to your Plugin Manager and open Codemirror
2. Set the `Key Map` to **Emacs**, **Vim** or **Sublime Text**
4. Click `Save`

### Actual result

JS errors:

> CodeMirror is not defined
> n is undefined

**Comment by ghost** [comment]
Issue confirmed.

emacs:
![Screen Shot 2020-09-22 at 14 06 39](https://user-images.githubusercontent.com/70466955/93880013-09c37d80-fcdd-11ea-8b1d-fbdb1f11a05b.png)

**Comment by dgrammatiko** [comment]
Fixed https://github.com/joomla/joomla-cms/pull/32315

**Comment by alikon** [comment]
closing as we have a pr #32315
