### ISSUE TITLE
[4.0] Codemirror plugin - issue with Line Height parameter

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29177]
### Steps to reproduce the issue

1. Go to your Plugin Manager and open Codemirror
2. Click on the `Appearance Options` tab
3. Set the `Line Height` to `2.0`
4. Click `Save`

### Expected result

The parameter shows as `1.0`

### Actual result

The parameter shows as `2.0`

**Comment by Quy** [comment]
Please test PR #29185
