### ISSUE TITLE
[4.0] TinyMCE Menu Modal - Random square

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29173]
### Steps to reproduce the issue

1. Go to edit any Article in the backend or frontend
2. Click `CMS Content` >> `Menu`
3. Hover over the `star` icon

### Expected result

No idea what it's supposed to do

### Actual result

Shows a random square

![screeny](https://user-images.githubusercontent.com/2019801/82457909-ecbc3b00-9aad-11ea-9a0c-8e518631ba8e.png)

**Comment by brianteeman** [comment]
Do you mean the modal that is loaded by the xtd-editor button for inserting a menu link? I am guessing you do. It is caused by an empty tooltip

![image](https://user-images.githubusercontent.com/1296369/82458384-8257ca80-9aae-11ea-938d-11685ae8d6ef.png)

**Comment by C-Lodder** [comment]
Correct Brian

**Comment by SharkyKZ** [comment]
What should the tooltip say? In standard layout it says "Set Default" but here changing home menu item is disabled.

**Comment by brianteeman** [comment]
I dont see a need for one. However the one that indicates the default menu should stay

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29179.
