### ISSUE TITLE
[4.0] Media Manager - JS error when all action plugins are disabled

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29182]
### Steps to reproduce the issue

1. Go to `administrator/index.php?option=com_plugins&view=plugins`
2. Disable `Media Action - Rotate`, `Media Action - Crop` and `Media Action - Resize`
3. Go to your Media Manager and attempt to edit an image

### Expected result

Perhaps a warning alert stating there are no action plugins enabled

### Actual result

> TypeError: Joomla.MediaManager.Edit is undefined --- edit-images.min.js:1:385

**Comment by Quy** [comment]
Duplicate #25843
