### ISSUE TITLE
[4.0] [atum] Missing FontAwesome icons on mobile

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29188]
### Steps to reproduce the issue

Login to the backend and reduce your viewport size

### Actual result

![screeny](https://user-images.githubusercontent.com/2019801/82550918-301eb400-9b57-11ea-8441-feec919829a3.png)

**Comment by richard67** [comment]
This issue will not be solved with PR #28075 .

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29205.
