### ISSUE TITLE
[4.0] TinyMCE width - percentages don't work

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29181]
### Steps to reproduce the issue

1. Go to `/administrator/index.php?option=com_plugins`
2. Open TinyMCE and click the `Advanced` tab
3. Set the `HTML Width` to `50%`
4. Click `Save`

### Expected result

If percentages are NOT allowed, I would expect one or more of the following:

- The field indicates that only pixels are supported
- Field shows a validation error if I enter an `%`
- TinyMCE accepts I've entered a percentage for the width

### Actual result

Success alert is shown, but the parameter is blank

**Comment by Quy** [comment]
Related #22901

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29204 (for staging).
