### ISSUE TITLE
[4.0] [atum] Select dropdown cut off

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29189]
### Steps to reproduce the issue

1. Go to `/administrator/index.php?option=com_users&view=users`
2. Reduce viewport size down to that of a mobile device

### Actual result

![screeny](https://user-images.githubusercontent.com/2019801/82551071-72e08c00-9b57-11ea-8d34-4c34101e54e6.png)

**Comment by wilsonge** [comment]
Think this might be a bootstrap upstream bug. If I disable the `width: 100%` property from bootstrap it seems to fix the issue

**Comment by C-Lodder** [comment]
@wilsonge Not a BS bug. It's because Atum doesn't correctly wrap flex items
