### ISSUE TITLE
[4.0] Codemirror fullscreen - toolbar overlap

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29180]
### Steps to reproduce the issue

1. Set Codemirror as your default editor
2. Go to edit any article in the backend
3. Ensure the editor is in focus
4. Enable fullscreen (normally `F10`)

### Actual result

The toolbar slightly overlaps the first line of the editor:

![overlap](https://user-images.githubusercontent.com/2019801/82465243-fac28980-9ab6-11ea-924b-aee95d437cf2.png)

**Comment by Quy** [comment]
Duplicate #23512
