### ISSUE TITLE
[4.0] [atum] Toggle menu - first click

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29192]
### Steps to reproduce the issue

1.  Go to `/administrator/index.php?option=com_config`
2. Reduce viewport width to that of a small device
3. Click on the `Toggle Menu` button

### Expected result

As the menu is already opened by default, I would expect it to close

### Actual result

Re-opens

![toggle](https://user-images.githubusercontent.com/2019801/82565162-de375780-9b71-11ea-92e7-e62c31578175.gif)

**Comment by Quy** [comment]
Please test PR #30131
