### ISSUE TITLE
NO article display

### ISSUE THREAD

**Issue by jcss** [joomla/joomla-cms#29199]
#steps to reproduce the issue
1. create article with few text words, publish, save&close
2. create menu item to select article
3. display front end menu and select menu item to display article

### Expected result
1. Nothing is displayed - expect to observe article text
2. Note: onContentPrepare plugin is no triggered.
3. Note: This worked before installation of the 5/21/20 over night update

**Comment by ReLater** [comment]
Which Joomla version? 3 or 4?

> 5/21/20 over night update

You're talking about a nightly build from here: https://developer.joomla.org/nightly-builds.html ?

And you made an update with an update package from there?

**Comment by chmst** [comment]
I cannot confirm. Please check if your article is published.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29199">issues.joomla.org/tracker/joomla-cms/29199</a>.</sub>

**Comment by chmst** [comment]
I cannot confirm. Please check if your article is published.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29199">issues.joomla.org/tracker/joomla-cms/29199</a>.</sub>

**Comment by jcss** [comment]
Joomla 4.0 Beta1 build night 5/21/20
  ----- Original Message -----

**Comment by jcss** [comment]
It was published
  ----- Original Message -----

**Comment by chmst** [comment]
Could you please set debug on and  error-reporting to maximum in the configuration.php? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29199">issues.joomla.org/tracker/joomla-cms/29199</a>.</sub>

**Comment by jcss** [comment]
My assumption is something was not completed in the update because I repeated the update and issue no longer exists.  IMHO Joomla 4.0 is overly complex and will never be successfully completed following the currrent ever changing design.
  ----- Original Message -----

**Comment by chmst** [comment]
Closing as it is not an issue

**Comment by rinka88** [comment]
Even if you leave textarea, then do it by default rows = "1" so that all fields are the same size.
