### ISSUE TITLE
[4.0] The requested page can't be found

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29190]
### Steps to reproduce the issue

1. Login to the frontend as an admin
2. Go to edit a module
3. Click the `Options` accordion tab
4. Click `Create`

See GIF below for full example

### Actual result

> Form::loadForm could not load file 

![update](https://user-images.githubusercontent.com/2019801/82552833-ca342b80-9b5a-11ea-87df-4bdf27e5fd09.gif)

**Comment by ChristineWk** [comment]
Confirm Actual result. You can't also not Close etc. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29190">issues.joomla.org/tracker/joomla-cms/29190</a>.</sub>

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29191 (for staging).
