### ISSUE TITLE
[4.0] [mobile] Codemirror loading twice in Plugin Manager

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29193]
### Steps to reproduce the issue

1. Go to `/administrator/index.php?option=com_plugins&view=plugin`
2. Reduce viewport size down to that of a mobile device
2. Open the Codemirror plugin

### Expected result

Codemirror loads as expected

### Actual result

> Loading failed for the <script> with source “/media/vendor/codemirror/mode/text/html/text/html.min.js”.

![screeny](https://user-images.githubusercontent.com/2019801/82566334-a6311400-9b73-11ea-9edf-11b707aa4b0e.png)

**Comment by Quy** [comment]
Duplicate #22778?

**Comment by C-Lodder** [comment]
I dont think so.
I can't replicate the linked issue and this only occurs on small devices, not desktop

**Comment by Quy** [comment]
Try this:
Resize from desktop to mobile to get 2  editor instances.
Resize from mobile to desktop to get 3 editor instances.
Repeat to get n+1 instances.

**Comment by C-Lodder** [comment]
Ah yes, that works. Closing as duplicate
