### ISSUE TITLE
[4.0] Update module changelogurl missing in db

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#29208]
### Steps to reproduce the issue
- J4.0 current nightly build
- Install a module that has no changelogurl in it's manifest or update-XML.

E.g. this one for Joomla 3: https://snapshots.ghsvs.de/updates/joomla/mod_administratorlinkghsvs/mod_administratorlinkghsvs_2015.12.28.zip

- Then install the same module built for Joomla 4 following the docs on https://docs.joomla.org/Adding_changelog_to_your_manifest_file.

E.g. this one for Joomla 4: https://github.com/GHSVS-de/mod_administratorlinkghsvs/archive/2020.05.23.zip

### Expected result
- After update entry in `changelogurl` field of table `#__extensions` because it's in the new manifest file.
https://github.com/GHSVS-de/mod_administratorlinkghsvs/blob/2020.05.23/mod_administratorlinkghsvs.xml#L17

### Actual result
- `changelogurl` field empty.
- Therefore `Changelog` feature in extensions > update will not work with next release.
- Only the headline and the new version will be displayed in modal.
- the logic will stop working here https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_installer/src/Model/ManageModel.php#L457

### Addition
- If you make a fresh install of the Joomla 4 module changelogurl is filled in database.

**Comment by Quy** [comment]
Duplicate #29037?

**Comment by ReLater** [comment]
It differs. I see the Changelog button with a simulated update after I've updated the old J3 version (without changelogurl) to the J4 version (with changelogurl) like described above. But the Changelog modal only displays the headline.

**Comment by ReLater** [comment]
Please test https://github.com/joomla/joomla-cms/pull/29209
