### ISSUE TITLE
[4.0] The toggle menu does not appear

### ISSUE THREAD

**Issue by adj9** [joomla/joomla-cms#29202]
### Steps to reproduce the issue
1. I open the BackEnd 
2. I reduce it smartphon style
3. Click on the button to see the menu items, image dimension: 1232 × 1172
![image](https://user-images.githubusercontent.com/5918444/82731387-bcbba480-9d06-11ea-8d15-52d35a4e5c82.png)
4. Reclick 
5. Reset the browser to standard size.
You do not see the toggle menu
![image](https://user-images.githubusercontent.com/5918444/82731516-cbef2200-9d07-11ea-858d-61f3b0806bbd.png)
6. Update the page
The toggle menu appears

### Expected result
Tooggle menu visible without step 5

### Actual result
you need step 5 to see the toggle menu

### System information 
- Web site
- Safari 13.0.5
- Chrome  83.0.4103.61 (Build ufficiale) (a 64 bit)
- macOS Catalina 10.15.3

**Comment by richard67** [comment]
@adj9 Is it a duplicate report to issue #28374 , i.e. does that issue already report what you reported here again?

Please check and report back here, and if it is really a duplicate you can close this issue here. Of course I can close it for you, too, in this case.

**Comment by adj9** [comment]
It's not really the same problem. In the steps described, as you can see in the second image, the toggle menu bar appears after step 6 (manual page refresh)

From what I see in issue [#28374](https://github.com/joomla/joomla-cms/issues/28374) the toggle menu bar always remains throughout the gif I see.

Also, I would like to add a replication feature to my issue. Step 2 is not done in proportional mode on both sides, but is done in diagonal mode with a double click of the mouse on the top bar of Chrome (S.O. mac functionality).

 Maybe it is a feature to solve a different feature.

**Comment by ciar4n** [comment]
Could we even call this an edge case issue. Outside of testing, what real-world example would involve a user resizing the browser so dramatically?

**Comment by ReLater** [comment]
A user can switch Landscape to Profile by turning the display. Therefore I disagree that it's not a real-world example. And when testing pages with inspectors it's completetely annoying and unprofessionell responsive behavior.

**Comment by ciar4n** [comment]
> And when testing pages with inspectors it's completetely annoying and unprofessionell responsive behavior.

I dont argue with that. I'm just making the point it is an edge case for a Joomla 'user'. If you find this one so annoying, there is a few similar issues.

**Comment by adj9** [comment]
Surely it's a case of borderline use of Joomla! home dashboard is not primary.
I generated this issue by testing others on the same topic and I validated this anomaly.

It would be interesting to test the issue on touch computers with the new Windosw browser to know if the behavior is equivalent, I don't have the possibility.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29202">issues.joomla.org/tracker/joomla-cms/29202</a>.</sub>

**Comment by ciar4n** [comment]
It's going to happen on any device that switches menu between portrait and landscape. Needs to remove the close class from the menu on resize

**Comment by Quy** [comment]
Please test PR #30132

@ciar4n Thanks for the tip.
