### ISSUE TITLE
[4.0] Select image modal buttons

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#29219]
It looks like it is caused by the button-group and d-flex classes on the toolbar but it cant simply removed from the layout as that breaks the full media manager toolbar (I tried)

### Expected
![image](https://user-images.githubusercontent.com/1296369/82845943-77ea6600-9ede-11ea-8cd6-a45f888dd6f3.png)

### Actual
![image](https://user-images.githubusercontent.com/1296369/82845961-93557100-9ede-11ea-977c-b46518b1228e.png)

**Comment by jwaisner** [comment]
Confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29219">issues.joomla.org/tracker/joomla-cms/29219</a>.</sub>

**Comment by Quy** [comment]
PR #29681
