### ISSUE TITLE
Article Save ->OnContentPrepare

### ISSUE THREAD

**Issue by jcss** [joomla/joomla-cms#29210]
### Steps to reproduce the issue
Joomla 4.0.0Beta 5/21/20 Save of article containing PHP code fails to open existing/supporting PHP file with error message "No such file or directory".  Article can be successfully previewd and executed on front end.  Issue does not exist in v3.9.19
Review the attached callstack text, png, php files.
1. Requires installed/enabled DirectPHP plugin v3.0
2. Requires installing Replacement.php as published article
3. Preview the article Note: DirectPHP onContentPrepare is triggered to eval code
4. Save the article which causes the error. Note: DirectPHP onContentPrepare is triggered to eval code WHY? This does not occur in v3.9.19.  This prevents saving any article that has PHP code that fails eval.

### Expected result
1. Successful preview
2. PHP error on Save preventing saving article that has NO invalid PHP code
11.3 64bit

### Actual result
1. View the attached files

### System information (as much as possible)
Joomla 4.0.0Beta1 build 5/21/20 with DirectPHP v3.0 installed/enabled; Win7Pro w/Chrome wampserver v3.

### Additional comments
View the callstack.txt and CallStack.png.  Why the redundant calss to plugins? Why is onContentPrepare called? Not called in v3.9.19.[CallStaclk.txt](https://issues.joomla.org/uploads/1/27fd8bb85a2116bd38bd6dd14c9fbec3.txt)

![screen shot 2020-05-24 at 21 03 23](https://issues.joomla.org/uploads/1/a4a35ff2b5094f176dc0fd8a85abb8ea.png)![screen shot 2020-05-24 at 21 03 23](https://issues.joomla.org/uploads/1/7c3bc882913c5c95c488c45459d4539f.png)![screen shot 2020-05-24 at 21 03 28](https://issues.joomla.org/uploads/1/3cdf9a544ba39c9a14cd0055ede45f19.png)[Replacement.txt](https://issues.joomla.org/uploads/1/f32fa0fc6baedda03493e777d82196da.txt)

**Comment by SharkyKZ** [comment]
>Why is onContentPrepare called?

It's triggered on save by Content - Smart Search plugin which is now enabled by default.

**Comment by SharkyKZ** [comment]
Closing this as non-core issue. If you need help with DirectPHP plugin, ask its developers or on [Joomla! Forum](https://forum.joomla.org/viewforum.php?f=715).
