### ISSUE TITLE
Contact form in subcategories gives error with modern routing

### ISSUE THREAD

**Issue by webgras** [joomla/joomla-cms#29213]
### Steps to reproduce the issue
For com_contact enable modern routing:
![grafik](https://user-images.githubusercontent.com/10774704/82807198-996c3300-9e87-11ea-8718-75f77b0ae457.png)
Create contact categories with subcategories like:
- Category 1
-- Subcategory 1
![grafik](https://user-images.githubusercontent.com/10774704/82807530-38912a80-9e88-11ea-8c6e-2ee517dc65f2.png)

Add a contact (just with email-address) to "Subcategory 1"
Create a menu item "List all Contact Categories" or "List contacts in a category"
Chose category "Category 1"
![grafik](https://user-images.githubusercontent.com/10774704/82807583-58285300-9e88-11ea-9ee4-21cdc796c761.png)

Go to homepage, select menu "Contacts", open contact form, try to send email through form.

### Expected result
Email message sent
Show contact again

### Actual result
Email message is sent (in the background)
websites gives you "404 invalid URL"

### System information (as much as possible)
Joomla 3.9.18
PHP 7.3

### Additional comments
With routing in "legacy" mode, it works.

**Comment by webgras** [comment]
Thanks @Hackwar - he helped to find the problem:
components/com_contact/controllers/contact.php
Line 181
category ID is missing, so after sending the redirect to the contact is not working.

**Comment by infograf768** [comment]
can you propose a PR?

**Comment by Quy** [comment]
Closing per PR #29234
