### ISSUE TITLE
[4.0] post-installation message select

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#29220]
The styling of the dropdown is different to all other dropdown selects. I did not expect to see the dark border or the blue

![image](https://user-images.githubusercontent.com/1296369/82846444-cef13a80-9ee0-11ea-9f29-cd662ef24d54.png)

**Comment by chmst** [comment]
In FF and Edge (win 10), all dropdowns look equal (for examle in filter).
Edge: hover is grey with border 
FF: hover is blue, no border visible.

 ![screen shot 2020-05-26 at 07 08 43](https://issues.joomla.org/uploads/1/1378055d5b84415288ee74a942b21f3a.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29220">issues.joomla.org/tracker/joomla-cms/29220</a>.</sub>

**Comment by brianteeman** [comment]
Sorry should I have said my test was on chrome windows 10

**Comment by dgrammatiko** [comment]
@brianteeman chrome 83 (and probably all other chromium browsers) have a new design for the form elements: https://www.youtube.com/watch?v=RsMikJZhnSQ

I guess this is something that Bootstrap at some point will incorporate, I mean don't try to fix it locally before a version of BS that incorporates those changes is already merge

**Comment by brianteeman** [comment]
Yes i realise that now

**Comment by brianteeman** [comment]
Closed for the reasons stated by @dgrammatiko above
