### ISSUE TITLE
[4.0] [Cassiopeia] Submit buttons touch the last field in com_users forms

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#29228]
### Steps to reproduce the issue
Use the following front end functions in the Cassiopeia template:
Create an account 
Forgot your username?
Forgot your password?
Edit your profile

### Expected result
The buttons Register, Submit and Cancel should be at least 2px below the last field.

### Actual result
The buttons Register, Submit and Cancel touch the last field.

### System information (as much as possible)
Wampserver 3.2.1, PHP 7.4.5, Chrome 83

**Comment by ghost** [comment]
Issue confirmed.

**Comment by Quy** [comment]
Duplicate #29138

**Comment by infograf768** [comment]
see https://github.com/joomla/joomla-cms/issues/29470#issuecomment-696548829
