### ISSUE TITLE
[4.0] Can't Save article on frontend

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#29233]
Create a user at the author level
Change the "created by" of an existing article to that author.
On the front end login as the author and navigate to the article
Click on the edit article
Click on save

### Expected behaviour
Article is saved

### Actual behaviour
Warning
Field required: Category

**Comment by brianteeman** [comment]
Can someone try to confirm this please as if repeatable its a beta blocker

**Comment by SharkyKZ** [comment]
Issue confirmed.

**Comment by jwaisner** [comment]
Increasing priority to Urgent as this is a beta-blocker.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29233">issues.joomla.org/tracker/joomla-cms/29233</a>.</sub>

**Comment by wilsonge** [comment]
I've done some work on this. This isn't a beta blocker but is a release blocker. Will update with more information when I can.

**Comment by jwaisner** [comment]
Adjusted to release blocker and downgrade priority.

**Comment by brianteeman** [comment]
Not being able to save content is going to really hamper the ability for users to test joomla 4 beta

@wilsonge this really is a beta blocker

**Comment by wilsonge** [comment]
There's a equally major bug in j3 that's been fixed here - this needs to be fixed properly in both places (J4 fixed the J3 bug but it exposed this)

**Comment by brianteeman** [comment]
oops

**Comment by adj9** [comment]
With last builder:
- Created a menu item to create articles from frontend
- Created a Registered user from the backend
- Logged in from the frontend 
- Created article from menu item

Not a problem and I see it in the backend I see the article.

After I created a module of the last articles (public) and I see the title of article, clicking on the name I do not see the text
![image](https://user-images.githubusercontent.com/5918444/85919317-6ba15200-b86a-11ea-8d2a-77f7f9804ec8.png)

**Comment by adj9** [comment]
I rectify the mistake I made earlier. The article's status flag is on Unpublished, so error 404 is consistent. 

I want to change the status from Unpublished to Published, but the Status menu doesn't open on the article page.
I report how I display the items options bar in both Browsers used:
![image](https://user-images.githubusercontent.com/5918444/85920752-ab6e3680-b876-11ea-84e0-a5963b2c6590.png)

Is there another way to change the vice status? Or do I only have to act on this screen?

By testing the screen with all items, if I click on the x of the status nothing happens. 

### Environment & Software Requirements
- Web site
- Safari 13.0.5
- Chrome 83.0.4103.116 (Build ufficiale) (a 64 bit)
- macOS Catalina 10.15.3

**Comment by alikon** [comment]
i'm not able to reproduce this issue with the current 4.0-dev (with workflow disabled)
can someone else confirm ?

**Comment by ghost** [comment]
@alikon Issue confirmed:

![Screen Shot 2020-09-21 at 18 15 04](https://user-images.githubusercontent.com/70466955/93792994-83546080-fc36-11ea-978b-e0a0235c8677.png)

**Comment by HRIT-Florian** [comment]
Issue confirmed, PR https://github.com/joomla/joomla-cms/pull/31124
Problem with filter="unset" The PR fix these problem, but finally maybe we have anyway a problem with the "unset" filter.

**Comment by zero-24** [comment]
Please find attached an proposed patch: https://github.com/joomla/joomla-cms/pull/31228
