### ISSUE TITLE
[4.0]Feed Display module uncaught error in rss.xml feed

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#29236]
### Steps to reproduce the issue
Create a News Feed category and item for http://feeds.bbci.co.uk/news/world/europe/rss.xml
Use this feed item in a Feed Display module.

### Expected result
Should work the same way it works when set up as the menu item type News Feed - Single News Feed.

### Actual result
Uncaught Throwable of type Error thrown with message "Object of class Joomla\CMS\Feed\FeedLink could not be converted to string" in C:\www\joomla4\modules\mod_feed\tmpl\default.php (line 99)

### System information (as much as possible)
Nightly Build of 27 May  on Wampserver 3.2.1  MySQL 8.0.19 PHP 7.4.5

**Comment by toivo** [comment]
2020-05-27T02:56:02+00:00	CRITICAL 127.0.0.1	error	Uncaught Throwable of type Error thrown with message "Object of class Joomla\CMS\Feed\FeedLink could not be converted to string". Stack trace: #0 C:\www\joomla4\modules\mod_feed\mod_feed.php(20): require()
#1 C:\www\joomla4\libraries\src\Dispatcher\ModuleDispatcher.php(54): include('C:\\www\\joomla4\\...')
#2 C:\www\joomla4\libraries\src\Dispatcher\ModuleDispatcher.php(57): Joomla\CMS\Dispatcher\ModuleDispatcher::Joomla\CMS\Dispatcher\{closure}('C:\\www\\joomla4/...', NULL)
#3 C:\www\joomla4\libraries\src\Helper\ModuleHelper.php(300): Joomla\CMS\Dispatcher\ModuleDispatcher->dispatch()
#4 C:\www\joomla4\libraries\src\Helper\ModuleHelper.php(173): Joomla\CMS\Helper\ModuleHelper::renderRawModule(Object(stdClass), Object(Joomla\Registry\Registry), Array)
#5 C:\www\joomla4\libraries\src\Document\Renderer\Html\ModuleRenderer.php(97): Joomla\CMS\Helper\ModuleHelper::renderModule(Object(stdClass), Array)
#6 C:\www\joomla4\libraries\src\Document\Renderer\Html\ModulesRenderer.php(48): Joomla\CMS\Document\Renderer\Html\ModuleRenderer->render(Object(stdClass), Array, NULL)
#7 C:\www\joomla4\libraries\src\Document\HtmlDocument.php(590): Joomla\CMS\Document\Renderer\Html\ModulesRenderer->render('sidebar-left', Array, NULL)
#8 C:\www\joomla4\libraries\src\Document\HtmlDocument.php(899): Joomla\CMS\Document\HtmlDocument->getBuffer('modules', 'sidebar-left', Array)
#9 C:\www\joomla4\libraries\src\Document\HtmlDocument.php(661): Joomla\CMS\Document\HtmlDocument->_renderTemplate()
#10 C:\www\joomla4\libraries\src\Application\CMSApplication.php(972): Joomla\CMS\Document\HtmlDocument->render(false, Array)
#11 C:\www\joomla4\libraries\src\Application\SiteApplication.php(752): Joomla\CMS\Application\CMSApplication->render()
#12 C:\www\joomla4\libraries\src\Application\CMSApplication.php(237): Joomla\CMS\Application\SiteApplication->render()
#13 C:\www\joomla4\includes\app.php(63): Joomla\CMS\Application\CMSApplication->execute()
#14 C:\www\joomla4\index.php(36): require_once('C:\\www\\joomla4\\...')
#15 {main}<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29236">issues.joomla.org/tracker/joomla-cms/29236</a>.</sub>

**Comment by SharkyKZ** [comment]
Once https://github.com/joomla/joomla-cms/pull/29237 reaches 4.0, it will solve this issue.

**Comment by ghost** [comment]
If `Feed Image` in `Feed Display`-Module is 

Yes (default) | No
-- | --
![Screen Shot 2020-09-21 at 18 01 39](https://user-images.githubusercontent.com/70466955/93791713-dd542680-fc34-11ea-948c-d287a2a4bfb6.png) | ![Screen Shot 2020-09-21 at 18 01 59](https://user-images.githubusercontent.com/70466955/93791643-c8779300-fc34-11ea-95d9-2ad3ce2c8fd7.png)
White screen showing above lines | works as expected

**Comment by SharkyKZ** [comment]
Closing this as https://github.com/joomla/joomla-cms/pull/29237 has been merged into 4.0-dev via https://github.com/joomla/joomla-cms/commit/9c5ad82e96cba230d1cabccca025f2aa03c13868.
