### ISSUE TITLE
J4 Private Messages - Outgoing

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#29248]
### Steps to reproduce the issue

There does not seem to be any way to look at my own Outgoing Private Messages. Have I missed something? I have been revising the J4 Help screens and this seems like a glaring omission, also the case in J3.

**Comment by brianteeman** [comment]
I "think" the reasoning is that private messages are mainly sent by the system to the user and not user to user so this was never coded. It has always been this way - which doesnt mean its correct just explaining why its the way it is right now

**Comment by rdeutz** [comment]
The messaging system isn't meant to be a fully message system like Email, we are not planning to change this.
