### ISSUE TITLE
[4.0] config switcher toggle onshow?

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#29240]
### Steps to reproduce the issue
I have a component where in the config there are some radio buttons that use the onshow condition to show / hide other buttons / fields

in order for this to work in J4 I need to change my config.xml and add a layout="joomla.form.field.radio.switcher' field to the button that does the toggling

### Expected result
toggling the button show show / hide the other buttons / fields

### Actual result
J4: it works :)
J3: form is complete broken and doesn't show anything other then the buttontext (with the layout field).

### Additional comments
In php code I can work around these differences, but in the xml form files you can't. This means that it is not possible to have one version of your extension to support both J3 and J4

Maybe this will be fixed / added in J3.10... I don't know, maybe there is another trick... haven't found it yet. Cannot find anything related in the documentation

**Comment by Quy** [comment]
Duplicate #27555

**Comment by Ruud68** [comment]
Hi @Quy  , is probably related. will follow up on that issue and close this one. Little bit worried as that issue is already open since January :S.
For me as an extension developer this is blocking as due to this issue you either have an issue in J4 or in J3. and with J3 I do not mean J3.10. J3.10 will only be used by people moving to J4, but not everybody is doing that (off all J3 installed, only 27% is on J3.9), so extensions should be compatible not only with J4 but also with J3.x
