### ISSUE TITLE
[4.0] Lazy loading in atum

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#29250]
### Steps to reproduce the issue
any admin page with an image eg the country flags on a multilingual site

### Expected result
nothing in the google console

### Actual result
[Intervention] An <img> element was lazyloaded with loading=lazy, but had no dimensions specified. Specifying dimensions improves performance. See https://crbug.com/954323

**Comment by dgrammatiko** [comment]
This is on my todo list as mentioned here: https://github.com/joomla/joomla-cms/pull/28838#issuecomment-622984665

**Comment by brianteeman** [comment]
Looks like chrome is no longer reporting this as an issue
