### ISSUE TITLE
J4 Layout of Tag Edit Form Options Panel

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#29254]
### Steps to reproduce the issue

Go to Components -> Tags -> New and select the Options panel.

### Expected result

Nice layout of form fields

### Actual result

The image fields overlap and the image place holder covers up a label. See screen shot.

### System information (as much as possible)

Macbook Pro with resolution of 1440 pixels wide.

![screen shot 2020-05-29 at 09 12 03](https://issues.joomla.org/uploads/1/c452d8569726ef6f3ef92b0d1316f266.png)

**Comment by Quy** [comment]
See  #25891 and related PR #28790

**Comment by Quy** [comment]
Please test PR #29706
