### ISSUE TITLE
[4.0] Issue with admin login redirect

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29255]
### Steps to reproduce the issue

**Test 1:**
1. Login to the backend
2. Remove your session from the `#__session` table (to replicate a session timeout)
3. Click on the **_Users_** quickicon
4. You will be redirected back to the admin login page
5. Login as per normal
6. You're redirected to the User Manager after logging in

Everything working so far

**Test 2:**
1. Login to the backend
2. Remove your session from the `#__session` table (to replicate a session timeout)
3. Click on the **_Extension Updates_** quickicon
4. You will be redirected back to the admin login page
5. Login as per normal

### Expected result

You're redirected to the Extension Updates page after logging in

### Actual result

![screeny](https://user-images.githubusercontent.com/2019801/83243915-82cf2000-a196-11ea-8ee3-111d9c992044.png)

### Additional comments

Have a feeling it's something to do with the token in the URL, but could be wrong.

**Comment by dgrammatiko** [comment]
Add another funny scenario with login here:
Adjust you session timeout to 1 minute
Go to the login page
wait for over one minute 
try to login

> Can someone even now explain me what exactly was this ajaxy login is solving? Everybody ignored me back in time when I raised the question so maybe I'm a bit more lucky now

**Comment by Quy** [comment]
> > Can someone even now explain me what exactly was this ajaxy login is solving? Everybody ignored me back in time when I raised the question so maybe I'm a bit more lucky now

Related https://github.com/joomla/joomla-cms/issues/27786#issuecomment-627838002?
