### ISSUE TITLE
[4.0] ucm_history

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#29274]
Clean install 

Expected no tables to update

Actual

Table '#__ucm_history' doesn't exist

![image](https://user-images.githubusercontent.com/1296369/83332909-c52b5680-a295-11ea-9ad1-60893c9a91b9.png)

**Comment by wilsonge** [comment]
Fixed with https://github.com/joomla/joomla-cms/commit/f6f304c299afd46b98baa25762afdf387b00eba3

Troubled life with our schema checker :(
