### ISSUE TITLE
[4.0] Column 'checked_out' cannot be null   everywhere

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#29271]
Tested on latest git pull at time of writing

completely clean composer and npm 

`Column 'checked_out' cannot be null
`
 Only tested unpublishing a contact and a plugin

**Comment by Fedik** [comment]
Can confirm, I have the same issue

**Comment by brianteeman** [comment]
probably as a result of #29260

**Comment by wilsonge** [comment]
Have you guys done a fresh DB install to get the changes (or run the schema update)

**Comment by brianteeman** [comment]
a fresh install gets the change but reveals another problem

**Comment by Fedik** [comment]
I have run the schema update

**Comment by wilsonge** [comment]
OK what's the new problem?

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/issues/29274
