### ISSUE TITLE
[4.0b1] Super Admin not authorised to do actions in media manager on FRONTEND

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29286]
### Steps to reproduce the issue

Install Joomla 4.0.0 Beta1 with demo content
Login to the FRONTEND of the site as the new Super Admin 
Navigate to the "About" article (or I guess any article) and click the edit button. 
Click CMS Content in the wysiwyg
Click Image (model loads)
Click Create New Folder
Enter "test" as a folder name
Click create

### Expected result

Folder with name "test" created.

### Actual result

Model inside the model asking for the new folder name stays, the typed folder name is removed, the backdrop over the rest of the first model remains, but an red error message is shown under that saying "You are not authorised"

<img width="1550" alt="Screenshot 2020-05-30 at 22 17 36" src="https://user-images.githubusercontent.com/400092/83339218-8613fa00-a2c3-11ea-96ca-72e332ecd8c5.png">

BONUS ISSUE: Make two or more errors and you see that the errors are pushed down with huge whitespace were it appears another error might/should/may be wanting to sit, but is not.

<img width="1543" alt="Screenshot 2020-05-30 at 22 19 25" src="https://user-images.githubusercontent.com/400092/83339242-ba87b600-a2c3-11ea-92dc-d7799b73c679.png">

Same issue when attempting to upload images in the frontend. 

Same issue deleting folders/images from frontend

### System information (as much as possible)

Safari on Mac

### Additional Information 

The Ajax calls result with 

```
{"success":false,"message":"The security token did not match. The request was aborted to prevent any security breach. Please try again.","messages":null,"data":null}
```

**Comment by JeroenAdam** [comment]
Same issue here, upload works fine in backend, not frontend

responseText: "{"success":false,"message":"The security token did not match. The request was aborted to prevent any security...

**Comment by Razzo1987** [comment]
it is the same / related to https://github.com/joomla/joomla-cms/issues/30005 ?

**Comment by SharkyKZ** [comment]
@Razzo1987 Yes, the issue is coming from the same place. Test PR https://github.com/joomla/joomla-cms/pull/30617 please.
