### ISSUE TITLE
[4.0b1] Missing Language Strings

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29289]
### Steps to reproduce the issue

install Joomla 4.0.0 beta 1 (English United Kingdom) 
login to admin with super admin 
Click the cog for the privacy dashboard on the admin home page 
Click edit
Click Advanced Tab

### Expected result

Translated strings

### Actual result
Missing translations:
COM_MODULES_FIELD_MODULECLASS_SFX_DESC
COM_MODULES_FIELD_CACHE_TIME_DESC
COM_MODULES_FIELD_CACHING_DESC

<img width="1352" alt="Screenshot 2020-05-30 at 23 00 16" src="https://user-images.githubusercontent.com/400092/83339842-59fb7780-a2c9-11ea-95f4-54a9757c6335.png">

**Comment by wilsonge** [comment]
Patch in https://github.com/joomla/joomla-cms/pull/29299
