### ISSUE TITLE
[4.0b1] Toggles Inconsistancy (Safari)

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29285]
### Steps to reproduce the issue

Install Joomla 4.0.0 Beta 1
Edit your new admin user in admin
Click around the tabs

### Expected result

The toggles to be 50/50

### Actual result

SOME toggles are 50/50 and some are 100/0 then clicked become 0/100

Easier to explain with a video.

![Screen Recording 2020-05-30 at 10 09 PM](https://user-images.githubusercontent.com/400092/83339104-43055700-a2c2-11ea-832e-3c05b9343d01.gif)

### System information (as much as possible)

Safari on Mac.

**Comment by infograf768** [comment]
Confirmed. Specific to Safari.

**Comment by wilsonge** [comment]
Adding `z-index: 1000` to this SCSS block https://github.com/joomla/joomla-cms/blob/4.0.0-beta/build/media_source/system/scss/fields/switcher.scss#L90 seems to "solve" the problem. But given no SCSS in our entire tree has `z-index` values of `999` I kinda don't believe it's a real solution and it's some sort of mask. Also given bootstrap's dropdowns start with a z-index of 1000 we might set ourselves up for failure on pages with a switcher element and dropdown in close proximity.

**Comment by wilsonge** [comment]
Maybe @ciar4n is this one you are able to help with? Dunno if you actually have a safari install available to you

**Comment by PhilETaylor** [comment]
But why do some look and work ok and not others on the same tab/page? Surely that’s the key?

This happens all throughout the admin console in safari - not just this example page - some work some don’t

**Comment by PhilETaylor** [comment]
Also as you can see hover and toggling can make visual changes of OTHER toggles on the same page - surely they should be totally independent?

**Comment by wilsonge** [comment]
As far as I can tell it's any switcher element that's not in the first column of flex columns. They definitely should be independent. The switchers are entirely CSS driven though (there's no JS) - so it has to be some sort of browser bug (which is also why things work in firefox and chrome)

**Comment by infograf768** [comment]
I still think this is a release blocker. No idea why this was modified.

**Comment by ciar4n** [comment]
> Maybe @ciar4n is this one you are able to help with? Dunno if you actually have a safari install available to you

I'm running Windows so sorry to say I dont have Safari available to me. 

Going by the screenshot, the issue only appears to happen to items in the second column? If so this may imply that... 

 https://github.com/joomla/joomla-cms/blob/f88ae096efa89f12f2cfcc496d1569e980a874b4/administrator/templates/atum/scss/blocks/_utilities.scss#L38-L39 

... is not been applied in Safari. To confirm does removing the `column-count-md-2 column-count-lg-3` classes from the container of these fields resolve the issue?

**Comment by infograf768** [comment]
The problem is `overflow: hidden;` for `.switcher .toggle-outside`

**Comment by ciar4n** [comment]
Sorry, I can't help you so. This issue been caused by `overflow: hidden;` makes no sense to me and I don't have a mac to test.

**Comment by infograf768** [comment]
it's a known problem in Safari with overflow hidden
https://devdojo.com/tnylea/safari-overflow-hidden-problem

Alas here we can't use the trick  as position is absolute

**Comment by infograf768** [comment]
https://forum.webflow.com/t/overflow-hidden-round-corners-not-working-on-safari/67805/2

**Comment by infograf768** [comment]
Looks like I found the solution

```
  overflow: hidden;
  -webkit-mask-image: -webkit-radial-gradient(white, black); // adding this
```

**Comment by infograf768** [comment]
Making PR now

**Comment by infograf768** [comment]
Clsing as we have a patch. Please test https://github.com/joomla/joomla-cms/pull/30420

**Comment by Magnytu2** [comment]
I applied # 30420 but still get the same result.
![Joomla__Patch_Tester_-_J4_beta_4_-_Administration](https://user-images.githubusercontent.com/26197929/90630569-8fa56200-e221-11ea-9a13-286ca7785f92.jpg)

**Comment by infograf768** [comment]
1. test results should be done in the pr
2. patchtester is not enough. One needs to use npm to apply the modified scss to the css
