### ISSUE TITLE
[4.0b1] Article Versions not visible on versions page on frontend when logged in 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29287]
### Steps to reproduce the issue

Install Joomla 4.0.0 Beta 1 
Install Demo Data
Login to frontend as your super admin
Edit an article - save many times to create versions
Edit the same article - click the Versions button

### Expected result

Model loads with the versions listed.

### Actual result

Model loads with no versions listed.

<img width="1045" alt="Screenshot 2020-05-30 at 22 29 25" src="https://user-images.githubusercontent.com/400092/83339368-10109280-a2c5-11ea-93df-4f752122cad3.png">

When viewing the versions of this article in the admin console, logged in with the same super admin and same article, the versions are viewable.

<img width="1043" alt="Screenshot 2020-05-30 at 22 29 32" src="https://user-images.githubusercontent.com/400092/83339370-1272ec80-a2c5-11ea-9d9c-10e7e5239e2a.png">

### Additional comments

Frontend model URL: 

`https://example.com/index.php/index.php?option=com_contenthistory&view=history&layout=modal&tmpl=component&field=jform_contenthistory&item_id=1&type_id=1&type_alias=com_content.article&9f5a6f050f0553d672c7974dc26baaec=1`

Admin model URL:
`https://example.com/administrator/index.php?option=com_contenthistory&view=history&layout=modal&tmpl=component&item_id=com_content.article.1&344771ca5052c42d5ae4d6803a9d0aa3=1`

**Comment by SharkyKZ** [comment]
Please test PR #29326.
