### ISSUE TITLE
[4.0b1]  must have a valid `as` value

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29288]
### Steps to reproduce the issue

Install Joomla 4.0.0 beta 1
Visit frontend straight after successful install (no demo data) 

### Expected result

No console errors

### Actual result

`<link rel=preload> must have a valid `as` value`

Tested in Safari and Google Chrome - same issue

<img width="625" alt="Screenshot 2020-05-30 at 22 53 40" src="https://user-images.githubusercontent.com/400092/83339732-8f539580-a2c8-11ea-8dbd-d1429537b0d0.png">

<img width="1354" alt="Screenshot 2020-05-30 at 22 53 27" src="https://user-images.githubusercontent.com/400092/83339735-9084c280-a2c8-11ea-8c83-bcd5b6dab9a4.png">

### System information (as much as possible)

On Mac

**Comment by jwaisner** [comment]
Confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29288">issues.joomla.org/tracker/joomla-cms/29288</a>.</sub>

**Comment by PhilETaylor** [comment]
I think this might be about header like

```
Link: <https://fonts.googleapis.com/css?family=Fira+Sans:400>; rel="preload"; as="stylesheet"
```

?

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29578.
