### ISSUE TITLE
[4.0b1] Enforce 2FA Doesn't work if 2FA plugin not enabled.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29298]
### Steps to reproduce the issue

Install Joomla 4.0.0 beta 1 with sample data.

In Joomla 4.0.0. beta 1 User Options you can enforce 2FA on both the backend and the frontend. 

<img width="402" alt="Screenshot 2020-05-31 at 00 13 38" src="https://user-images.githubusercontent.com/400092/83340729-b2d00d80-a2d3-11ea-8d50-4c01556c83b9.png">

### Expected result

If an admin sets this to yes, the admin could be excused in thinking that is all he needs to do... however, enabling this doesn't actually enforce  2FA ... because the 2FA plugins are disabled by default.

### Actual result

No restriction to login at all.

**Comment by ghost** [comment]
Issue confirmed.

**Comment by brianteeman** [comment]
Please test #34176
