### ISSUE TITLE
[4.0b1] Token Copied Feedback Message Not Visible

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29291]
### Steps to reproduce the issue

install Joomla 4.0.0 beta 1 (English United Kingdom) 
install sample data
login to frontend with super admin
Click change password 
scroll down a long way, click the copy button next to your token

### Expected result

Token selected, Token copied to the clipboard, no flicker, no feedback and no "success message"

Just like the copy button here in GitHub next to the repo url for example. 

### Actual result

Page flickers

Took me ages to work out why, but if you scroll all the way back up the page to the top of the page you get a success message, which is outside of the window, and thus redundant 

![Screen Recording 2020-05-30 at 11 16 PM](https://user-images.githubusercontent.com/400092/83340074-e27b1780-a2cb-11ea-918e-9d2a8c7e5db2.gif)

**Comment by nikosdion** [comment]
This was introduced with https://github.com/joomla/joomla-cms/pull/29005 Paging @C-Lodder 

I believe that is we really want to use `Joomla.renderMessages()` we need to also scroll the browser to the messages area. Otherwise we should be displaying an inline message like everyone else does when copying tokens.

**Comment by C-Lodder** [comment]
The feature was added by me, yes, however the way alerts are managed are a different issue. I have raised concerns about them before but others believe they should be statically positioned on the page.
I won't fight the maintainers on UX and will let the issues raised (e.g this one) speak for themselves.
