### ISSUE TITLE
[4.0b1] Accessibility Highlight Links Inconsistent 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29292]
### Steps to reproduce the issue

Login to admin and set "highlight links" in your Accessibility Settings to yes.
Click Save.
Note that there is a red box around all three icons at top 

<img width="311" alt="Screenshot 2020-05-30 at 23 28 42" src="https://user-images.githubusercontent.com/400092/83340208-50740e80-a2cd-11ea-8f9a-460450f46cc1.png">

Click to some other page

note that now Private messages has no red box

### Expected result

red box around all three icons at top 
<img width="311" alt="Screenshot 2020-05-30 at 23 28 42" src="https://user-images.githubusercontent.com/400092/83340211-52d66880-a2cd-11ea-9752-5afbd7958472.png">

### Actual result

<img width="312" alt="Screenshot 2020-05-30 at 23 29 58" src="https://user-images.githubusercontent.com/400092/83340240-903af600-a2cd-11ea-9d2a-52fcd78398ed.png">

### System information (as much as possible)

Safari on Mac

### Additional comments

another example where these green items have no red box both the other links above them do

<img width="935" alt="Screenshot 2020-05-30 at 23 31 14" src="https://user-images.githubusercontent.com/400092/83340250-b6f92c80-a2cd-11ea-8c5a-f14540c23e76.png">

**Comment by ghost** [comment]
Issue confirmed.

**Comment by Quy** [comment]
PR #31333
