### ISSUE TITLE
[4.0b1] Editing template image on frontend leads to 404 model

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29296]
### Steps to reproduce the issue

Login to Joomla 4.0.0 beta 1 frontend with sample data as a super admin 
Click template settings pages you to
You are now at https://example.com/index.php/working-on-your-site/template-settings?view=templates
(Make a mental note of the breadcrumbs) 
Click Select
(Make a mental note this is a model)
Select image and click select
Click save
You are now at https://example.com/index.php/component/config?view=templates
(Make a mental note of the breadcrumbs - they have changed - but we are still in edit mode) 
click select to launch the image section model again

### Expected result

the media manager loads - again

### Actual result

a Joomla error page, actually a 404 error handled by Joomla

![Screen Recording 2020-05-30 at 11 59 PM](https://user-images.githubusercontent.com/400092/83340591-02153e80-a2d2-11ea-8e5a-4b8159d24542.gif)

### System information (as much as possible)

Tested on safari and chrome on Mac

**Comment by SharkyKZ** [comment]
Closed as having PR https://github.com/joomla/joomla-cms/pull/30007.
