### ISSUE TITLE
[4.0b1] css breakpoint creates blank dropdown in admin

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29293]
### Steps to reproduce the issue

Joomla 4.0.0 beta 1 admin console. 
Resize window to half the size of my MacBook Pro... ok I know you can't do that, so you are going to have to just drag the right side of your browser to make a smaller window... 

yeah yeah I know, "The web was meant to be read, not squished. This isn't the way to test a responsive design. - Agree or disagree I dont care" but here we are.. 

Do whatever you need to to replicate this on a smaller screen...

### Expected result

no blank dropdown

### Actual result

three dots leading to a blank dropdown

![Screen Recording 2020-05-30 at 11 36 PM](https://user-images.githubusercontent.com/400092/83340312-6df5a800-a2ce-11ea-947d-52afa653a77e.gif)

### System information (as much as possible)

replicated today on a Mac with safari "squashed" to half the screen real estate on a MacBook Pro 15"

### Additional comments

It seems that if you go even smaller screen this dotted-menu drops to the bottom and is then populated with Private Messages and Post Installation messages - so its a useful menu, but there is a breakpoint where its unpopulated, at the top still and no use.

**Comment by ghost** [comment]
Can't confirm on Firefox 80, Safari 13.1 / Mac.

**Comment by chmst** [comment]
@PhilETaylor is this still an issue? Unfortunately I cannot test myself, but meanwhile there were some changes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29293">issues.joomla.org/tracker/joomla-cms/29293</a>.</sub>

**Comment by PhilETaylor** [comment]
Its "changed" yes.. 

And with[ Bootstrap 5 on the cards](https://github.com/joomla/joomla-cms/pull/32037), lets just close this... 

https://user-images.githubusercontent.com/400092/104935633-612fdc80-59a3-11eb-9107-c0e337b9dd91.mp4
