### ISSUE TITLE
[4.0b1] Username (optional)

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29290]
### Steps to reproduce the issue

login to the frontend of Joomla 4.0.0 Beta 1 as a super user and click Change Password menu item (from the sample data installed)

### Expected result

`Username`

### Actual result

`Username (optional)`

<img width="450" alt="Screenshot 2020-05-30 at 23 12 02" src="https://user-images.githubusercontent.com/400092/83339983-19046280-a2cb-11ea-9e7d-9b954ca47b3a.png">

Maybe I missed something with the privacy stuff - is username now optional? Surely not, especially as its also a disabled field?

**Comment by PhilETaylor** [comment]
In fact these dropdown are also marked as optional - but there is no blank row in the dropdowns, so its impossible to not provide a selection, and thus by definition they are not optional. 

<img width="367" alt="Screenshot 2020-05-30 at 23 14 45" src="https://user-images.githubusercontent.com/400092/83340034-79939f80-a2cb-11ea-90d9-1928d57e9db4.png">

**Comment by richard67** [comment]
@PhilETaylor Regarding username and password fields: Its optional to fill in these fields, e.g. if you don't wanna change your password, just leave these fields blank, you only need to fill them in (our out ;-) ) if you wanna change the password oder the user name.

**Comment by PhilETaylor** [comment]
It is not optional to fill in the username field - the field is read only, prepopulated and disabled - thus not optional.

**Comment by Quy** [comment]
Please test PR #29339

**Comment by PhilETaylor** [comment]
> Please test PR #29339

@quy I can't see that - Teeman is blocked by my account ;-)
