### ISSUE TITLE
[4.0b1] Menu items On Hover icons/text not being inverted

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29295]
### Steps to reproduce the issue

Load Joomla 4.0.0 beta 1 on the smallest screen you have (or just squish your browser to as small a width as possible) 

Use the three-dots menu in the bottom left corner to expend the submenu

Hover over the two icons

### Expected result

Inverting of the icons and text - maybe to white? Im no coloraturas expert so do whatever you like :) 

Maybe they should look and act like the User menu does, white on blue?

### Actual result

Hard to read blue on different blue hover colours

![Screen Recording 2020-05-30 at 11 46 PM](https://user-images.githubusercontent.com/400092/83340450-253eee80-a2d0-11ea-9e9a-e515a8b9cf04.gif)

### System information (as much as possible)

Safar Mac tested today

**Comment by wilsonge** [comment]
Fix in https://github.com/joomla/joomla-cms/pull/29297
