### ISSUE TITLE
[4.0b1] Cannot logout from admin after 2fa enforced and 2fa not set up

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29301]
### Steps to reproduce the issue

Joomla 4.0.0 beta 1 
 enabling "Enforce 2FA = both" in user options and then publish the Yubikey 2FA plugin in admin
logout

Try to login to ADMIN as super admin (with no 2fa) 

You get redirected (correctly) to set up your 2FA which is now enforced

### Expected result

The ability to set up a yubikey correctly and save and carry on my life BUT lets say I dont have a yubikey (as lets say I just ordered one) I should be allowed to at least logout! 

### Actual result

... but I cannot logout,  I cannot navigate away from my user profile page, Im stuck in this session.

**Comment by HLeithner** [comment]
Logout should be possible the rest is ok in my opinion.

**Comment by PhilETaylor** [comment]
see comments on https://github.com/joomla/joomla-cms/issues/29302#issuecomment-636452656 - same applies here... too much can be accessed and changed when it should be ONLY 2FA that can be modified.

**Comment by PhilETaylor** [comment]
Still cannot logout.

<img width="1602" alt="Screen Shot 2022-03-06 at 21 34 50" src="https://user-images.githubusercontent.com/400092/156943092-b259a1cf-08ec-4852-b51a-1ca36db0c144.png">
