### ISSUE TITLE
[4.0b1] Warning message squashed for no reason.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29309]
### Steps to reproduce the issue

Go to Media Manager Options in Joomla 4.0.0 Beta 1 

### Expected result

The warning block

```
Warning! Path Folder
Changing the 'Path to files folder' from the default of 'images' may break your links.
The 'Path to images' folder has to be the same or a subfolder of 'Path to files'.
```

is squashed, not to half the area, or even just to the label area, just a random width it seems

Probably doesn't need "Path Folder" in the title either. 

### Actual result

<img width="1225" alt="Screenshot 2020-05-31 at 12 03 33" src="https://user-images.githubusercontent.com/400092/83350841-ded0aa80-a336-11ea-886a-e1344b50fe6b.png">

### System information (as much as possible)

Mac on Safari.

**Comment by Quy** [comment]
Besides the display issue to be fixed, is the warning necessary considering it is repeated in the help descriptions?

**Comment by brianteeman** [comment]
Please test #30852
