### ISSUE TITLE
[4.0b1] "Token (optional)" label when its not actually user supplied

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29306]
### Steps to reproduce the issue

Edit your user on frontend 
see that the token field says `Token (optional)`

### Expected result

Sensible label that doesn't confuse.

The Token is not actually optional as its system provided, system generated, a read only field and shown for information purposes only. You cannot not provide it.

### Actual result

 `Token (optional)`

<img width="943" alt="Screenshot 2020-05-31 at 11 41 54" src="https://user-images.githubusercontent.com/400092/83350400-c0b57b00-a333-11ea-81ae-ee9ee3363927.png">

**Comment by Quy** [comment]
Please test PR #29339
