### ISSUE TITLE
[4.0b1] Impossible to set up 2FA on frontend 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29300]
### Steps to reproduce the issue

Joomla 4.0.0 beta 1

publish the Yubikey and/or Google 2FA plugin in admin

Try to login to FRONTEND as super admin (with no 2fa) 

You get redirected (correctly) to set up your 2FA 

### Expected result

The ability to set up a yubikey correctly on the frontend and save and carry on my life

### Actual result

Changing the "Authentication Method" dropdown doesn't show the hidden fields which would accept my yubikey generated code, so I can't save it. Im now screwed ;-) , I cannot navigate away or set up 2FA. 

![Screen Recording 2020-05-31 at 11 37 AM](https://user-images.githubusercontent.com/400092/83350306-35d48080-a333-11ea-81f4-9b6c4f6ede4a.gif)

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29365.
