### ISSUE TITLE
[4.0b1] Site Name in Page Titles is not constantly applied

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29315]
### Steps to reproduce the issue

Install Joomla 4.0.0 beta 1 
install sample data
login to frontend as super admin
Click Site Settings
Set "Site Name in Page Titles" to After
Save

### Expected result

On every page, on the frontend, the site name should be appended to the page title. 

### Actual result

The site name is only appended to some (most) pages 

The exceptions (from the sample data) are:
 - Click Site Settings menu item - note that the site title is not appended to the page title
 - Click Template Settings menu item - note that the site title is not appended to the page title
 - Click to edit a module  - note that the site title is not appended to the page title

So it appears that the site name is not appended to the page title when the page is a Edit Form kind of action... 

So maybe this is "by accidental design" and is a `won't fix` ?

**Comment by brianteeman** [comment]
> So it appears that the site name is not appended to the page title when the page is a Edit Form kind of action...

No just when it is a com_config form - article edit for example correctly shows the title

**Comment by ghost** [comment]
> The exceptions (from the sample data) are:

Same behaviour in J3.

**Comment by brianteeman** [comment]
Please test #34068
