### ISSUE TITLE
[4.0b1] Cancel button on edit profile page redundant 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29313]
### Steps to reproduce the issue

Edit your user profile on the frontend in Joomla 4.0.0 b1

### Expected result

A save button (see: #29312) only

### Actual result

Cancel button on edit profile page is redundant

A cancel button, that when pressed does nothing but reload the page as there is no where to cancel "to" (I.e where would you redirect to if you cancelled?! it makes no sense) 

<img width="218" alt="Screenshot 2020-05-31 at 12 20 34" src="https://user-images.githubusercontent.com/400092/83351191-bc8c5c00-a339-11ea-9b1e-114aca645585.png">

**Comment by SharkyKZ** [comment]
It's an issue with routing. You should be redirected to user profile but currently this only works if user profile menu item is set up.

**Comment by PhilETaylor** [comment]
Nothing to fix except everything.
