### ISSUE TITLE
[4.0b1] Options panel missing bottom border on module edit on frontend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29311]
### Steps to reproduce the issue

login to frontend of a Joomla 4.0.0 beta 1 site
click the edit icon next to any module position

### Expected result

Edit form loads, options and advanced panels look right

### Actual result

Options has missing bottom border
Advanced looks right 

<img width="998" alt="Screenshot 2020-05-31 at 12 15 09" src="https://user-images.githubusercontent.com/400092/83351046-a6ca6700-a338-11ea-90ed-660880d4d008.png">

### System information (as much as possible)

Safari on Mac

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29579.
