### ISSUE TITLE
[4.0b1] "Submit" button text, whereas all others are "Save"

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29312]
### Steps to reproduce the issue

Edit your user profile on the frontend in Joomla 4.0.0 b1

### Expected result

A save labeled button - like every other edit screen in Joomla. 

### Actual result

A Submit labeled button... 

<img width="218" alt="Screenshot 2020-05-31 at 12 20 34" src="https://user-images.githubusercontent.com/400092/83351140-50115d00-a339-11ea-9285-b9e877343682.png">

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29367.
