### ISSUE TITLE
[4.0b1] Double scroll bars in popup modal window

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29317]
### Steps to reproduce the issue

log into joomla 4.0.0 beta 1 admin console as super admin in Safari on a Mac or Google Chrome on Mac

scroll down on the "Home Dashboard" 

Click Add Module to dashboard

### Expected result

No double scroll bar 

### Actual result

the modal has a double scroll bar on some screen resolutions
![Screen Recording 2020-05-31 at 01 20 PM](https://user-images.githubusercontent.com/400092/83352149-881c9e00-a341-11ea-9e31-7c7c08045491.gif)

### System information (as much as possible)

 Safari on a Mac or Google Chrome on Mac

**Comment by Quy** [comment]
Please confirm if this is still reproducible after PR #29527. Thanks.

**Comment by PhilETaylor** [comment]
YES This problem still exists in 4.0-dev @ 4110ab97ea50819d6ecfd77a00b047d4362a56b6 (Today) 

Video: https://screenshot.phil-taylor.com/Jru6vn2A

**Comment by infograf768** [comment]
Confirmed, also on wide screens.

**Comment by infograf768** [comment]
And it is not only with that modal
![Screen Shot 2020-08-05 at 12 26 27](https://user-images.githubusercontent.com/869724/89402305-eb96c380-d716-11ea-88c8-d238e926dbc2.png)

**Comment by infograf768** [comment]
My guess it is related to the overflow for modal-body which is set to auto. In Safari it is corrected if we use ` initial`

Testing now if this has any unwanted consequences.

**Comment by infograf768** [comment]
Making PR now as it looks like working fine.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/30283
Closing as we have a patch

**Comment by infograf768** [comment]
@PhilETaylor 
please test patch
