### ISSUE TITLE
[4.0b1] Add Module To Dashboard Crazy Layout on Mobile

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29319]
### Steps to reproduce the issue

login to Joomla 4.0.0 beta 1 admin console as a super admin on the smallest screen (or squeezed up browser window) you can find. 

Scroll down and click add module to dashboard

### Expected result

Ability to read and add modules

### Actual result

tall and squashed boxes that are hard to use/read

![Screen Recording 2020-05-31 at 01 24 PM](https://user-images.githubusercontent.com/400092/83352279-48a28180-a342-11ea-9c70-dd9fe3669325.gif)

### System information (as much as possible)

Mac and google chrome

**Comment by Quy** [comment]
Duplicate #29064

**Comment by PhilETaylor** [comment]
I promise I did search before submitting :-)

**Comment by Quy** [comment]
No worries. Thanks for testing/reporting. 👍
