### ISSUE TITLE
[4.0b1] Add Module to dashboard cancel button needs tweaks

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29318]
### Steps to reproduce the issue

log into joomla 4.0.0 beta 1 admin console as super admin in Safari on a Mac or Google Chrome on Mac

scroll down on the "Home Dashboard" 

Click Add Module to dashboard

### Expected result

a cute and cuddly button that makes me scared to press it

### Actual result
needs a little tweak to the bottom border under the X

<img width="194" alt="Screenshot 2020-05-31 at 13 22 48" src="https://user-images.githubusercontent.com/400092/83352195-da5dbf00-a341-11ea-9a7a-e1b0f7272fb4.png">
<img width="219" alt="Screenshot 2020-05-31 at 13 23 22" src="https://user-images.githubusercontent.com/400092/83352215-eba6cb80-a341-11ea-89a1-fcb5c9a39b46.png">

**Comment by wilsonge** [comment]
Hopeful fix in https://github.com/joomla/joomla-cms/pull/29375

**Comment by PhilETaylor** [comment]
Wrong image in PR ;-) should be the non hover state

**Comment by wilsonge** [comment]
oops thanks :)
