### ISSUE TITLE
[4.0b1] Cannot select image when creating menu item (Safari Only)

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29314]
### Steps to reproduce the issue

Attempt to create a menu item in Joomla 4.0.0 beta 1 

### Expected result

Ability to select an image on the "Link Type" tab

### Actual result

The Select and X area of the image selector are missing. Note that the toggles are also wrong and toggling them causes a flash of the Select|X area so possibly linked to RELEASE BLOCKER https://github.com/joomla/joomla-cms/issues/29285

<img width="1493" alt="Screenshot 2020-05-31 at 12 39 28" src="https://user-images.githubusercontent.com/400092/83351456-fc544300-a33b-11ea-9951-aa8271316971.png">

![Screen Recording 2020-05-31 at 12 39 PM](https://user-images.githubusercontent.com/400092/83351479-36254980-a33c-11ea-8224-877f2c24c737.gif)

### System information (as much as possible)

Only broken on safari
google chrome shows correctly.

**Comment by PhilETaylor** [comment]
This was broken by adding `overflow: hidden;` by the pr https://github.com/joomla/joomla-cms/pull/28645

**Comment by infograf768** [comment]
Clsoing as we have a patch.
See https://github.com/joomla/joomla-cms/pull/30420
