### ISSUE TITLE
[4.0b1] Unable to set a new image root for use in media manager

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29310]
### Steps to reproduce the issue

Edit Media Manager Options

Set new image path/files path root, instead of images, lets try myImages which is an existing folder with images in it

Revisit the media manager

<img width="1201" alt="Screenshot 2020-05-31 at 12 11 31" src="https://user-images.githubusercontent.com/400092/83350970-e2186600-a337-11ea-8da0-04117dcaea86.png">

### Expected result

Expected to see the contents of myImages folder 

### Actual result

Still seeing the default /images folder

### Additional comments

Joomla 3.9.19 allows me to change the paths and see the folders in media manager - whereas Joomla 4 doesn't honour the change in the media manager

**Comment by dgrammatiko** [comment]
There is plugin for that, so the field you’re looking is there

**Comment by PhilETaylor** [comment]
All I know is that in Joomla 3 this is the place to change the root folders for images to load in the media manager - and in Joomla 4 that no longer has any affect on the media manager. 

If there is now - yet another different place - to change the root path then what's the point of these fields?

**Comment by PhilETaylor** [comment]
in fact if I change these two fields to /MYIMAGES and then visit the PLUGIN "Fields - Media" then the plugin ALSO doesn't respect the configuration of /MYIMAGES and still shows folders beneath /images

**Comment by Quy** [comment]
Duplicate #23972?

**Comment by PhilETaylor** [comment]
"Opened 21 Feb 2019" with no action...

**Comment by dgrammatiko** [comment]
I think the plugin is called filesystem not in front of a pc right now

**Comment by PhilETaylor** [comment]
ok well apparently this is a duplicate so closed anyway now
