### ISSUE TITLE
Certificate expired err no cert. run

### ISSUE THREAD

**Issue by 1337180** [joomla/joomla-cms#29327]
### Steps to reproduce the issue
fresh install on websupport.sk

### Expected result
https loaded

### Actual result
no https loaded

### System information (as much as possible)
websupport.sk php 7.3.16

### Additional comments
probably hosting variation issue

**Comment by SharkyKZ** [comment]
>probably hosting variation issue

Yes, most likely. Please ask your hosting provider.
