### ISSUE TITLE
[4.0b1] - Extend 2FA Enforcement option to select usergroups

### ISSUE THREAD

**Issue by conconnl** [joomla/joomla-cms#29321]
In 4.x we now have the option to Enforce Two Factor Authentication, but the option is limited to "Frontend", "Backend" or "Both"
This doesn't work for the scenario where you want to enforce 2FA for certain groups who work on the frontend, but have more rights then Registered users.

A enforcement on usergroup bases would give us more flexibility.

<img width="867" alt="image" src="https://user-images.githubusercontent.com/11913918/83353413-c1113e80-a352-11ea-8092-654c20f2c16b.png">

**Comment by zero-24** [comment]
PR here: https://github.com/joomla/joomla-cms/pull/30522
Backport for 3.9+ here: https://github.com/zero-24/plg_system_force2fausergroup/releases/latest
