### ISSUE TITLE
inserting an image does not work - joomla 4

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#29324]
I work on an online site, with https for the exercise. Whether from a module or an article, it is impossible to insert an image from the "CMS Content" button. The image is selected in the media manager but the import does not take place.

![screen shot 2020-05-31 at 14 00 01](https://issues.joomla.org/uploads/1/8dee1ce5d7ff6094566ace44c0f6a335.jpg)

**Comment by Quy** [comment]
Please test PR #29323
