### ISSUE TITLE
[4.0-beta1] An extension that needs to be updated is not detected

### ISSUE THREAD

**Issue by ntatsis** [joomla/joomla-cms#29328]
### Steps to reproduce the issue
1. Login at backend
2. Install Akeeba backup 7.1.3
3. Go System > Update > Extensions >Find Updates

### Expected result
Show Akeeba backup 7.1.3 as outdated extension

### Actual result
Message: There are no updates available at the moment. Please check again later. 

### Additional comments
With the same configuration, in Joomla 3.9.18 works as expected.

**Comment by infograf768** [comment]
Which joomla version?

**Comment by ntatsis** [comment]
4 beta 1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29328">issues.joomla.org/tracker/joomla-cms/29328</a>.</sub>

**Comment by mbabker** [comment]
Close as expected behavior.  An extension's update server can specify what versions of Joomla an update is advertised to, at least with the pro version of Akeeba Backup the update server does not specify that updates for the in-development 3.10 or 4.0 versions are available.

**Comment by infograf768** [comment]
Closing as expected

**Comment by nikosdion** [comment]
Hi, the extension's developer here :) Our policy is that our extensions are not marked as compatible with a specific Joomla version until we release a version that supports at the very least the first published beta. Before that there is no feature freeze in Joomla and by the time you download our software it may no longer be compatible with the in-development Joomla version. Akeeba Backup 7.1.4 was only tested with a pre-release version of 4.0.0.b1 and we are aware of a few remaining issues. The next version will indeed be marked as fully supporting 4.0 which will solve your problem. That said, you can still use Akeeba Backup 7.1.4 on Joomla 4.0.0.b1 if you can put up with a view visual issues.
