### ISSUE TITLE
[4.0b1] Links to off site locations occasionally missing some padding

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29335]
### Steps to reproduce the issue

I just come across these while browsing, I'll log them here when I see them again.

### Expected result

Some nice padding:

Eg: 

<img width="271" alt="Screenshot 2020-05-31 at 13 13 58" src="https://user-images.githubusercontent.com/400092/83356869-caa1a300-a360-11ea-9a16-0f9e7148b4af.png">

### Actual result

Examples of bad padding Ive seen before logging this issue (not sure where these were now, will log exact locations when I find them again or come across them) 

<img width="194" alt="Screenshot 2020-05-31 at 00 10 06" src="https://user-images.githubusercontent.com/400092/83356843-9e862200-a360-11ea-9e33-1d5d33e297d7.png">
<img width="229" alt="Screenshot 2020-05-31 at 00 11 11" src="https://user-images.githubusercontent.com/400092/83356845-9f1eb880-a360-11ea-9045-1cc8b53d5880.png">

<img width="403" alt="Screenshot 2020-05-31 at 17 01 49" src="https://user-images.githubusercontent.com/400092/83356862-bd84b400-a360-11ea-9380-8eb005aa0fae.png">

**Comment by PhilETaylor** [comment]
<img width="663" alt="Screenshot 2020-06-08 at 16 47 59" src="https://user-images.githubusercontent.com/400092/84052016-e5e76080-a9a7-11ea-90c4-328c6a499a84.png">

**Comment by PhilETaylor** [comment]
<img width="1174" alt="Screenshot 2020-06-09 at 19 17 26" src="https://user-images.githubusercontent.com/400092/84193308-25d74200-aa93-11ea-95a0-7c55767879ed.png">

**Comment by brianteeman** [comment]
1. The icon should have a margin-right and that explains why the image above looks wrong
2. The times that it looks correct are when there is a space in the source (not the string)

Fixing 1 -  is easy.
Fixing 2 - I have no idea.

With just the margin then there will be complaints that sometimes the space is too big.

**Comment by PhilETaylor** [comment]
Another good (bad) example, there're now double icons on the install from web pages when selected an extension 

<img width="1595" alt="Screenshot 2020-06-22 at 22 41 28" src="https://user-images.githubusercontent.com/400092/85338090-96418280-b4d9-11ea-8550-7503b8c7eee0.png">

**Comment by PhilETaylor** [comment]
#30250
