### ISSUE TITLE
[4.0b1] Impossible to select subfolders of the images folder in filesystem plugin

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29334]
### Steps to reproduce the issue

Edit the filesystem plugin in Joomla 4.0.0 b1

### Expected result

The ability to specify sub folders that are not folders on the root as the places I want to store images

E.g:

 - /images/migrated_images
 - /images/client_provided
 - /user_uploaded/someotherapp/imagesfolder/omg/photos

### Actual result

You can only select a top level folder from the root of the site

<img width="1433" alt="Screenshot 2020-05-31 at 16 55 07" src="https://user-images.githubusercontent.com/400092/83356704-af826380-a35f-11ea-9101-97000f9da9bd.png">

**Comment by brianteeman** [comment]
Please see #29719

**Comment by brianteeman** [comment]
Please re-open as #29719 is now closed as not good enough

**Comment by infograf768** [comment]
@PhilETaylor 
Although it was closed. I think the solution is https://github.com/joomla/joomla-cms/pull/29719#issuecomment-646948486

Please post there your opinion.

**Comment by infograf768** [comment]
I made a PR which is not exactly doing what @PhilETaylor requires, but is easy to modify to avoid the overload by the other one:
https://github.com/joomla/joomla-cms/pull/29721

**Comment by PhilETaylor** [comment]
The filesystem plugins are meant to be the DEFINITIVE PLACE that the Media Manager can use to access media. 

The "local" filesystem folders select and thus should be the DEFINITIVE folders that user-selectable media can reside in locally. Not everyone will want to use /media or /images and so any folder within the local web-accessible file-system should be selectable. (It would also be nice for folders to be subject to ACL too, but that's not implemented either)

The plugin approach improves security and to allow additional plugins for media (e.g loading from dropbox/AmazonS3) 

However, the [Joomla project (JSST Team) has already rejected correctly implementing this](https://github.com/joomla/joomla-cms/issues/29523) to ensure that all places in Joomla ONLY use the media plugins /facepalm/ and therefore the whole concept is now null and void and its "just another half baked idea" only implemented in "some places" and not others. 

> doing what @PhilETaylor requires

Might be lost in translation, but I dont personally "require" anything, I am simply pointing out the current limitation in the current plugin and saying that its not good enough to only have a list of the root folders (most of which have nothing to do with media) and not be able to select any other custom folder within the local filesystem.

**Comment by PhilETaylor** [comment]
Hmm I also dont have Github permissions to reopen my own issues now.

**Comment by infograf768** [comment]
I understand the limitations you point to.
Whether it is possible to add this feature and keep also what we have now (anyway should be modified as proposed in https://github.com/joomla/joomla-cms/pull/29721 as indeed proposing all core root directories there makes no sense) looks like needing a total refactoring of the plugin and com_media.
I tested by modifying directly in db the possible plugin directories params (for example by using `components/mycustommedia`) and although the directory exists in Media, it does not display subs nor images.

**Comment by brianteeman** [comment]
It has always been possible to have a folder other than /images as the root folder for the media manager

**Comment by infograf768** [comment]
Yes, in J3. 
Have you even tried in J4: it's impossible as it is the plugin which has priority over the Media Options... In J4, only a root folder will be usable.

just do that 
<img width="512" alt="Screen Shot 2020-06-21 at 10 10 16" src="https://user-images.githubusercontent.com/869724/85219871-8033a500-b3a7-11ea-837c-86fc102f979c.png">

**Comment by brianteeman** [comment]
Yes I know - I raised an issue about those fields being useless now.

**Comment by infograf768** [comment]
J3:

<img width="569" alt="Screen Shot 2020-06-21 at 10 14 28" src="https://user-images.githubusercontent.com/869724/85219941-1071ea00-b3a8-11ea-8ba5-50cb4b8a36d3.png">
