### ISSUE TITLE
[4.0b1] Uploading images in media manager doesn't show preview

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29330]
### Steps to reproduce the issue

Install Joomla 4.0.0 beta 1
login to /administrator/ as super admin
Navigate to the media manager
Upload some PNG images

### Expected result

Image uploads and shows a preview

### Actual result

Image uploads and shows the representation of a transparent square image

![Screen Recording 2020-05-31 at 04 32 PM](https://user-images.githubusercontent.com/400092/83356223-8c09e980-a35c-11ea-9f8e-00abe127aa21.gif)

The images are actually uploaded and doing a hard refresh of the page the thumbnails correctly show again.

### System information (as much as possible)

Does the same thing in Safari and Google Chrome on Mac

### Additional comments

Same happens with drag and dropping image on the screen

Nothing special about the PNG's - here is one I tested with 

<img width="199" alt="Screenshot 2020-05-31 at 16 37 44" src="https://user-images.githubusercontent.com/400092/83356283-118d9980-a35d-11ea-8578-c0ebf065e884.png">

**Comment by Quy** [comment]
I am not able to reproduce this on macOS High Sierra 10.13.6 with Safari 13.1.2 and Chrome 85.0.4183.

Please confirm if this is still an issue. Thank you.

**Comment by PhilETaylor** [comment]
seems fixed
