### ISSUE TITLE
[4.0b1] Copy url button missing left border when link highlighted

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29331]
### Steps to reproduce the issue

Go to media manager in admin, select an image and select to get the shareable link.
click "Get shareable link"

### Expected result

When clicking the copy button, the left border doesn't disappear

### Actual result

left border of the copy button disappears on click, and on any click/selection of the actual url

![Screen Recording 2020-05-31 at 04 39 PM](https://user-images.githubusercontent.com/400092/83356350-95478600-a35d-11ea-939a-ebd81467cb41.gif)

### System information (as much as possible)

Happens in Google Chrome and Safari on Mac

**Comment by ghost** [comment]
Issue confirmed in Firefox80/Mac.

**Comment by Quy** [comment]
PR #30855
