### ISSUE TITLE
[4.0] Invalid controller class: file 

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#29333]
### Steps to reproduce the issue
Go to Media Manager.
Upload an image.
Go to Home Dashboard.
Under `Latest Actions`, click on the link of the uploaded image.

**Comment by ghost** [comment]
Issue confirmed, get:

![Screen Shot 2020-09-21 at 15 30 48](https://user-images.githubusercontent.com/70466955/93772914-b2130c80-fc1f-11ea-9c59-3f798de057dd.png)
![Screen Shot 2020-09-21 at 15 31 46](https://user-images.githubusercontent.com/70466955/93772921-b3443980-fc1f-11ea-87ff-3fddbaada7b8.png)
