### ISSUE TITLE
[4.0b1] When image list zoomed out to maximum zoom there is not enough room

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29332]
### Steps to reproduce the issue

Got to media manager of a folder with lots of images - use the zoom out button as far as you can zoom out

When image list zoomed out to maximum zoom there is not enough room for both squares

### Expected result

No overlapping?. Maybe stop one zoom stop less than currently as that still has enough room for both select boxes?

### Actual result

![Screen Recording 2020-05-31 at 04 47 PM](https://user-images.githubusercontent.com/400092/83356517-a5ac3080-a35e-11ea-8b16-56c8d64abe95.gif)

**Comment by jwaisner** [comment]
Confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29332">issues.joomla.org/tracker/joomla-cms/29332</a>.</sub>

**Comment by Quy** [comment]
PR #30869
