### ISSUE TITLE
[4.0b1] Tag name not showing on searching tags in edit article

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29341]
### Steps to reproduce the issue

install Joomla 4.0.0 beta 1 and sample data
Add a tag called "myTag" using com_tags
Edit "Welcome to your blog" article
on the right search or "tag" in the tags field

### Expected result

Tags should be in the dropdown search results

### Actual result

2 is in the dropdown search results 

The result of the AJAX search call doesn't return the tag name:

`[{"value":2,"text":"","path":""}]`

![Screen Recording 2020-05-31 at 06 47 PM](https://user-images.githubusercontent.com/400092/83359051-8e297380-a36f-11ea-9106-6a3a144b12b4.gif)

**Comment by SharkyKZ** [comment]
Please test PR #29346.
