### ISSUE TITLE
[4.0] Notice  Undefined index: home when saving atum admin template style

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#29355]
### Steps to reproduce the issue
Do a clean install of 4.0-dev or beta
No need to do anything else.

Edit atum template style
Save

`PHP Notice:  Undefined index: home in .../Joomla_4/administrator/components/com_templates/src/Table/StyleTable.php on line 58`

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/issues/29358.
