### ISSUE TITLE
[4.0b1] - Displaying the system menu

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#29360]
Wouldn't it be possible given the long list of treats? Is it possible to make the system settings menu always visible?

![screen shot 2020-06-01 at 13 27 52](https://issues.joomla.org/uploads/1/8a57e70348a7f3593671176303e084ac.jpg)

**Comment by infograf768** [comment]
Not sure I understand. You mean the System sidebar or the System menu?

**Comment by Magnytu2** [comment]
I'm talking about the horizontal menu which starts with "article"

**Comment by Quy** [comment]
I still don't understand your request.

**Comment by Magnytu2** [comment]
Like the first menu "save - save & close ...", make a second floating menu.
![Annotation-2020-06-01-183337](https://user-images.githubusercontent.com/26197929/83431020-f2fbd100-a436-11ea-9981-cd75cdeb2564.png)

**Comment by brianteeman** [comment]
Do you mean like the options button?

**Comment by Magnytu2** [comment]
You get lost quickly in the settings. Menu 2 should remain visible, as menu 1 also does. Here a photoshop montage to show you.
![Annotation-2020-06-01-185704](https://user-images.githubusercontent.com/26197929/83434185-43c0f900-a43a-11ea-8c59-d9f01b1b6f69.png)

**Comment by brianteeman** [comment]
Simple answer is that it would probably be impossible.

The item you highlight as 1 is a single element so it can be given a position:sticky css

The item you highlight as 2 is not a single element

**Comment by Magnytu2** [comment]
it's sad ... :( :)
![J4_crew-dragon](https://user-images.githubusercontent.com/26197929/83436786-c946a800-a43e-11ea-81eb-6139f2c7fd4e.jpg)

**Comment by brianteeman** [comment]
Just noticed the screens in the graphic - nice ;)

**Comment by brianteeman** [comment]
This should be closed for the reasons stated above
