### ISSUE TITLE
[4.0b1] Tags should be under content

### ISSUE THREAD

**Issue by regularlabs** [joomla/joomla-cms#29364]
Categories, Fields, and now even modules can be found under Content.
Tags is under Components.
Makes no sense.

![image](https://user-images.githubusercontent.com/13553242/83421847-ff792d00-a428-11ea-82f9-b1236a686474.png)

**Comment by infograf768** [comment]
Can't be compared imho.
Tags concerns all components, not only Content.
Categories are specific to each component, fields are specific to Articles, Contacts, Users

**Comment by SharkyKZ** [comment]
By that logic, Media, Site Modules and Administrator Modules also don't belong under Content item.

**Comment by infograf768** [comment]
Well, Media is content. For the Modules it can be discussed.
Tags is just a signal of sorts, links.
I am happy we have the alternative admin menu...
