### ISSUE TITLE
[4.0b1] Tabs outside view

### ISSUE THREAD

**Issue by regularlabs** [joomla/joomla-cms#29363]
/administrator/index.php?option=com_config&view=component&component=com_content

Width: 1680px
![image](https://user-images.githubusercontent.com/13553242/83421045-c7251f00-a427-11ea-827d-8593cfe7d96a.png)

Width: 1200px (side menu collapsed)
![image](https://user-images.githubusercontent.com/13553242/83421276-208d4e00-a428-11ea-8330-0daed7ac832a.png)

**Comment by Quy** [comment]
Duplicate #28799
