### ISSUE TITLE
[4.0b1] Installer when using remote database: button [Install Joomla] hardly visible

### ISSUE THREAD

**Issue by crimle** [joomla/joomla-cms#29379]
### Steps to reproduce the issue
- download Joomla_4.0.0-beta1-Beta-Full_Package.zip 
- unzip the file
- upload the files into an empty folder of the webserver
- open the related URL in order to start the installation
- step 1: enter the necessary data then click the button [Setup Login Data]
- step 2: enter the necessary data then click the button [Setup Database Connection]
- step 3: enter the necessary data USING A REMOTE DATABASE then click the button [Install Joomla]
- step 4: you will encounter a 

«Warning
You are trying to use a database host which is not on your local server...»
Notice
To confirm that you are the owner of this website please delete the file ... Then select [Install Joomla] to continue the installation»

### Expected result
The button [Install Joomla] should be placed directly underneath this warning and this notice.

### Actual result
In fact, the button [Install Joomla] is not immediatly visible. A summary of the first steps is displayed. In order to find the button [Install Joomla] the user needs to scroll down considerably far. 

### Additional comments
Professional users might find the button readily. But unexperienced users could be bewildered by not finding immediately the button that is ledaing to the next step.

**Comment by richard67** [comment]
@crimle Would it be also a solution to extend the text in the blue message at the end by changing the
`Then select "Install Joomla" to continue.`
to something like
`Then use the "Install Joomla" button at the bottom of this form to continue.`
?

**Comment by crimle** [comment]
Yes it would. Although I do not see the necessity for displaying here the summary of the previous steps. Maybe, a [Back] button for each step would be appreciated in order to go back to a previous step and correct mistypings.

**Comment by ChristineWk** [comment]
Similar to this? https://issues.joomla.org/tracker/joomla-cms/29325
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29379">issues.joomla.org/tracker/joomla-cms/29379</a>.</sub>

**Comment by crimle** [comment]
Oh yes, very similar. Only the solution approach is different. I would not mind if you merge my report with the one mentionned above.
