### ISSUE TITLE
[4.0] String unclear

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#29371]
A translator stumbled over the following string and asked if there is a bug in the string since it looks like strange english.

PLG_WORKFLOW_NOTIFICATION_RECEIVERS_SELECT="Select single  Users who obtain a Notification"
See https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/language/en-GB/plg_workflow_notification.ini#L14

After doing a search, I didn't find any use of that string, so it may even be possible to delete completely.

Pinging @bembelimen since he last touched the string with https://github.com/joomla/joomla-cms/commit/b53334a74449dc3345cf68e4ebd4e7cfb5d4b5a6

**Comment by brianteeman** [comment]
Originally the string was used here I believe

![image](https://user-images.githubusercontent.com/1296369/83453284-1ed88000-a452-11ea-8d1f-565f46edcfe8.png)

**Comment by bembelimen** [comment]
Yes this was the "placeholder text" of the select I guess. Therefore I ping @chmst she was the original author.

**Comment by chmst** [comment]
Thank you for the hint, @Bakual.  It should be the description for the users select field.
I think that the meaning of the users select field is clear, and I will remove this string, with a PR which is in preparation. 
@brianteeman do you think the text is necessary? I f yes, your help for a correct english text would be appreciated ;)

**Comment by brianteeman** [comment]
I don't think it is necessary

**Comment by richard67** [comment]
Closing as having PR #29672 . Please test.
