### ISSUE TITLE
[4.0] Hide "Add module to the dashboard" from Manager group

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#29372]
### Steps to reproduce the issue
Log in to the Administration backend as a manager.
Click `Add module to the dashboard` icon.

### Actual result
> You don't have permission to access this. Please contact a website administrator if this is incorrect.

**Comment by brianteeman** [comment]
You identified the error but I think your solution is wrong.

The code says that this should be present 
` if ($user->authorise('core.create', 'com_modules'))`

and a manager does have create access - however a manager does not have access to the admin interface 

![image](https://user-images.githubusercontent.com/1296369/83461962-e3de4880-a461-11ea-9d96-438c891cc4f0.png)

**Comment by Quy** [comment]
So no access to the admin interface, then hide it??

**Comment by Quy** [comment]
> and a manager does have create access - however a manager does not have access to the admin interface

Do you mean access to the administration backend? Well I am able to log in with a Manager account.

**Comment by chmst** [comment]
The condition must be `<?php if ($user->authorise('core.manage', 'com_modules')) : ?>` in com_cpanel default.php, not core.create .

**Comment by brianteeman** [comment]
Please see #29718
