### ISSUE TITLE
Your 4.0 beta test site won't recognize .PRO TLD as valid to create

### ISSUE THREAD

**Issue by mpryandds** [joomla/joomla-cms#29383]
Deciding to look at the Joomla 4.0 beta on the test site created to do that, my www.healthcard.pro website didn't pass the first welcome screen. Testing was impossible.  .PRO has been a TLD (top level domain) extension for many years.  Your form there has no information regarding user entries, abandoning them.  Is this a bug too?  Thanks.  Peace.

**Comment by HLeithner** [comment]
I don't think that there is any code in joomla that checks the tld... what's the error message, do you have a screenshot? error.log?

**Comment by brianteeman** [comment]
I am guessing from the comment that they are referring to launch.joomla.org

**Comment by mpryandds** [comment]
Brian Teeman and Harald Leithner, Thank you for responding. That is correct.  Launch.joomla.org.  What is the format for entering a site name? I am immediately asked to sign into Facebook in a non-navigating popup window.   (I hate facebook.) A field note on the domain name says  “PLEASE ENTER A VALID DOMAIN NAME” Healthcard.pro doesn’t do it. Peace, prayers, blessings, grace and agape,Mark  From: Brian TeemanSent: Tuesday, June 2, 2020 6:16 PMTo: joomla/joomla-cmsCc: MPRyanDDS; AuthorSubject: Re: [joomla/joomla-cms] Your 4.0 beta test site won't recognize .PRO TLD as valid to create (#29383) I am guessing from the comment that they are referring to launch.joomla.org—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by brianteeman** [comment]
Did you mean this highlighted field
![image](https://user-images.githubusercontent.com/1296369/83576412-a6dd8900-a529-11ea-98b3-2f73b74d454e.png)

Launch.joomla.org offers free sites in the format subdomain.joomla.com so you should be entering a single word in this field (if you want to upgrade to host a real full domain then you can do so afterwards.

I am assuming your facebook comment is referring to this
![image](https://user-images.githubusercontent.com/1296369/83576616-08055c80-a52a-11ea-9df4-ee00c48d3095.png)

This is offering you 4 ways to sign up/authenticate for the free service.
As you will see the last one of those is to do it manually

**Comment by mpryandds** [comment]
Yes Brian, that is the field.   OK so enter a single word.  I understand it is for testing only and changes every day.   I find Joomla more friendly than WordPress – ocean_wp – elementor.   Way better than Dreamweaver.  Peace, prayers, blessings, grace and agape,Mark From: Brian TeemanSent: Tuesday, June 2, 2020 6:38 PMTo: joomla/joomla-cmsCc: MPRyanDDS; AuthorSubject: Re: [joomla/joomla-cms] Your 4.0 beta test site won't recognize .PRO TLD as valid to create (#29383) Did you mean this highlighted fieldLaunch.joomla.org offers free sites in the format subdomain.joomla.com so you should be entering a single word in this field (if you want to upgrade to host a real full domain then you can do so afterwards.I am assuming your facebook comment is referring to thisThis is offering you 4 ways to sign up/authenticate for the free service.As you will see the last one of those is to do it manually—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Quy** [comment]
Closing as non-core issue. Please report issue here: https://github.com/joomla/joomla-websites/issues

**Comment by brianteeman** [comment]
@quy nothing to report. It was a misunderstanding on what to enter in the field
