### ISSUE TITLE
After upgrading to Joomla 3.9.18 Helix error

### ISSUE THREAD

**Issue by bsylwek** [joomla/joomla-cms#29382]
### Steps to reproduce the issue
Fatal error: require_once(): Failed opening required '/home/users/xxxx/public_html/libraries/joomla/document/html/renderer/head.php' (include_path='.:/usr/multiphp/php7.2/usr/share/php:/home/lib/php7.2:/home/lib/php7.2/pear') in /home/users/xxxx/public_html/templates/lt_envico/error.php on line 27

### Expected result
After upgrading to Joomla 3.9.18, the following error occurred. How can I solve it?

**Comment by richard67** [comment]
Is your PHP version 7.2 so the include path is right? If so, please check if the folders "/usr/multiphp/php7.2/usr/share/php" and "/home/lib/php7.2:/home/lib/php7.2/pear" really exist and are not excluded from access by the webserver by an open_basedir directive.

**Comment by ChristineWk** [comment]
There were similar posts there: https://pcmshaper.com/forum/joomla-3-8-12-update-why-is-the-head-php-file-suddenly-not-found/99
See also last post. Maybe you could ask in forum. BTW: You should use PHP 7.3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29382">issues.joomla.org/tracker/joomla-cms/29382</a>.</sub>

**Comment by richard67** [comment]
Yes, and check if your Helix template is up to date ;-)

**Comment by Quy** [comment]
Closing as it appears to be a template issue.
