### ISSUE TITLE
Joomla! 3.x.x to 3.x.x Patch Package contain .github folder

### ISSUE THREAD

**Issue by Fedik** [joomla/joomla-cms#29385]
### Steps to reproduce the issue

Download https://downloads.joomla.org/cms/joomla3/3-9-19/Joomla_3-9-x_to_3-9-19-Stable-Patch_Package.zip?format=zip

Check archive content, it contain .github folder

### Additional comments

It was for all older releases also :) 

Nothing critical, just to note.

**Comment by HLeithner** [comment]
Thanks for the report, I will update the build script later.

**Comment by Quy** [comment]
PR #30100
