### ISSUE TITLE
[4.0] com_tags images

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#29388]
The images are squashed into 3 columns
![image](https://user-images.githubusercontent.com/1296369/83555424-2d806f00-a506-11ea-915a-c2dc0cc39dc5.png)

They are much more usable in 2 columns
![image](https://user-images.githubusercontent.com/1296369/83555506-4852e380-a506-11ea-9282-3c3447178bc8.png)

The class column-count-lg-3 is coming from 
https://github.com/joomla/joomla-cms/blob/c01e33b929d388e931cd056fe6593be229961d7f/layouts/joomla/edit/params.php#L117-L122

**Comment by Quy** [comment]
Duplicate #29254
