### ISSUE TITLE
Horizontal scroll on screen Article options 

### ISSUE THREAD

**Issue by rachelwalraven** [joomla/joomla-cms#29384]
### Steps to reproduce the issue
Open backend on a smaller (laptop) screen between 936 and 1482 pixels and go to Content > Articles > Options.

### Expected result
The option tabs fit on the screen or are shown below each other as sliders (as the mobile view).

### Actual result
A horizontal scroll bar appears.
![fig1](https://user-images.githubusercontent.com/25247750/83519624-a074f000-a4dc-11ea-80da-1340f1165a4e.png)

### System information (as much as possible)
Joomla 4.0 beta, windows 10 machine, Chrome browser, PHP 7.4.6

**Comment by Quy** [comment]
Duplicate #28799
