### ISSUE TITLE
[4.0b5] Joomla Installer suddenly shows previous installation steps when entering wrong database credentials

### ISSUE THREAD

**Issue by PixedBo** [joomla/joomla-cms#29409]
### Steps to reproduce the issue

Just install J4 beta, insert wrong credentials in the database section

### Expected result

Stay in the database section, in order to correct the error without seeing all the previous steps.

### Actual result

Site name and user data shows up first and i have to scroll down to database section again. More: there are still the blue buttons "setup login data ->", "setup database connection -> " that hides the previous parts

### System information (as much as possible)

PHP 7.2

### Additional comments

The problem occurs even when there is no real error: just insert a database host other than localhost and all the previous steps become viewable. Furthermore, all the buttons of the previous steps are also active.
I think this behavior is very confusing especially for new users who are not practical in installing joomla (and it is therefore easy for them to make configuration errors).

![joomlasetup](https://user-images.githubusercontent.com/12549961/97583489-4cbcf300-19f7-11eb-9470-2e30accc2790.PNG)

**Comment by Quy** [comment]
Duplicate #29325
