### ISSUE TITLE
[4.0] Content > Articles > Filter Options > multiple categories filter doesn't work

### ISSUE THREAD

**Issue by frankazoid** [joomla/joomla-cms#29406]
### Steps to reproduce the issue

1. make sure you have articles in different categories
2. go to Content > Articles and click [filtering options]
3. select category1 and ensure that proper articles are displayed
4. select category2

### Expected result
either articles for both categories displayed or category2 should replace category1 in the filter

### Actual result
both categories are displayed in the dropdown but only category2 articles are displayed

### System information (as much as possible)
php 7.4.2
joomla 4.0 beta1

**Comment by brianteeman** [comment]
Confirmed

**Comment by chmst** [comment]
Confirmed. With every select, the form is submitted for this one selection. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29406">issues.joomla.org/tracker/joomla-cms/29406</a>.</sub>

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29466.
