### ISSUE TITLE
Smart search does not index joomla content items

### ISSUE THREAD

**Issue by louisjansen** [joomla/joomla-cms#29407]
### Steps to reproduce the issue
Given I i am logged in to the Joomla! administrator section
When I go to Components > Smart Search > Indexed Content and click on "index" 
I do see the pop-up that says that the indexer is running.

However, only 2 items are indexed. Both are SP Pagebuilder page. I do have a few hundred regular Joomla! articles

### Expected result
All Joomla content items are indexed

### Actual result
Non of my Joomla content items are indexed

### System information (as much as possible)
Joomla 3.9.19
PHP 7.4

Issue did happen with Joomla 3.9.18 already, 3.9.19 did not solve it
Changing to the latest PHP version 7.4 did not solve it

### Additional comments
I did find older documentation on running indexer via commandline from the /%root%/cli directory running the command 
php finder_indexer.php

With this command smart search DOES index all my content correctly

**Comment by HLeithner** [comment]
Just to be sure can you check that the content finder plugin is active?

**Comment by louisjansen** [comment]
> Just to be sure can you check that the content finder plugin is active?

The plugin is active. I am using Smart Search and its indexing for some years in the current set-up already. No issues till recently. Furthermore I did describe that 2 pages (sometimes 3) are actually indexed. That could not be done if the plugin was inactive I guess?

**Comment by richard67** [comment]
Could you check in "Extensions - Manage - Database" if there are database problems shown, and report back the result?

**Comment by louisjansen** [comment]
![dbase](https://user-images.githubusercontent.com/30545178/83659624-0f794400-a5c4-11ea-92c1-cb9b0b65ee52.jpg)

This is what I get to see after "Extensions - Manage - Database".

**Comment by richard67** [comment]
So the database seems to be ok.

**Comment by louisjansen** [comment]
So it seems. Tried to index with multiple browsers and both windows pc and a Macbook to ensure that it is nothing device or browser related. Same result.

Does anyone know what happens on the background when I hit the index-button. Does is start a different proces compared to the command line option: php %root%/cli/finder_indexer.php ?

**Comment by richard67** [comment]
What happens if you switch error reporting to "Maximum" in global configuration server settings and start indexing again? Do you see any errors on the page or in your PHP error log file (if PHP is confighured to log errors into a file), or in your server log file?

**Comment by richard67** [comment]
> Does anyone know what happens on the background when I hit the index-button. Does is start a different proces compared to the command line option: php %root%/cli/finder_indexer.php ?

@Hackwar Any idea why indexing with Smart Search in 3.9.19 could fail in backend but succeed with CLI?

**Comment by louisjansen** [comment]
> What happens if you switch error reporting to "Maximum" in global configuration server settings and start indexing again? Do you see any errors on the page or in your PHP error log file (if PHP is confighured to log errors into a file), or in your server log file?

Nothing extra happens, same result pop-up appears mentioning "Indexer Running
Your content is being indexed. Do not close this window."

**Comment by Hackwar** [comment]
There are several things that could go wrong here. I'll try my best to help out:

Lets first home in on the issue. Please go to the plugin manager and filter for the finder plugins. Do you have more than one plugin active? I'm guessing that the Pagebuilder plugin is the first one in the list? Please move that plugin to the end of the list and try the indexing again.
By reordering the plugins, we can see if this is a general issue with the indexing process or only relates to a specific plugin. If it is a specific plugin, it should now index more stuff before failing again.

Please then enable debugging and set error reporting to simple or even maximum. Then go to the Smart Search indexing page and open the developer tools of your browser. (Press F12) In those tools go to the network tab and clear the list first. That makes it easier for you later on. Now click on indexing and wait. In that network tab, several new entries should show up slowly. When you see a request that returns something else than a 200 status code, that would be the one interesting for us. Please select that request and show us what response you got there.

Generally I would expect this to be an issue of not enough memory or not enough time to process everything and most likely being related to one specific article/page in the pagebuilder, which now throws an error and thus stops the whole process dead in its tracks. I don't really expect this to be a Joomla issue itself.

**Comment by louisjansen** [comment]
Many thanks @Hackwar that is really helpful. The Smart Search - SP Pagebuilder plugin was indeed the first in order. I moved it to last and now my regular content items start indexing normal again.

However, whenever the progress bar is at about 75% of the indexing process it stops. The network tab shows an error 500.

![error-500](https://user-images.githubusercontent.com/30545178/83716775-2b66ff00-a631-11ea-8cab-0e7e4ee9d4a1.png)

Does this give better insight in what's happening on the background? Did not find a reference to memory. Would that be harddisk space or internal memory by the way? I did not experience issues with this in the past.

**Comment by louisjansen** [comment]
Many thanks @Hackwar that is really helpful. The Smart Search - SP Pagebuilder plugin was indeed the first in order. I moved it to last and now my regular content items start indexing normal again.

However, whenever the progress bar is at about 75% of the indexing process it stops. The network tab shows an error 500.

![error500](https://user-images.githubusercontent.com/30545178/83723029-47bd6880-a63e-11ea-9630-4b6b653a9b6c.png)

Does this give better insight in what's going on? Did not find any reference to memory in the error but I am not very good at this :-). And would that be internal memory or harddisk memory you are referring to?

**Comment by Hackwar** [comment]
You want to have a look at the response tab of the request. That should give you more ideas what error you are getting. But generally it means that the issue isn't really with Joomla, but most likely with SP Pagebuilder.

**Comment by louisjansen** [comment]
Thanks again @Hackwar. The response shows a raw html output. The title is this "<title>Error: 0 Call to undefined method Joomla\CMS\Application\AdministratorApplication::getLanguageFilter()</title>"

The content covers the same info:


					<h1 class="page-header">An error has occurred.</h1>
					<blockquote>
						<span class="label label-inverse">0</span> Call to undefined method Joomla\CMS\Application\AdministratorApplication::getLanguageFilter()											</blockquote>
										<p><a href="/administrator" class="btn"><span class="icon-dashboard"></span> Return to Control Panel</a></p>

**Comment by richard67** [comment]
That could be a useful hint to find the cause of the issue.

**Comment by Hackwar** [comment]
Any news regarding this?

**Comment by Quy** [comment]
Closing due to no response.
