### ISSUE TITLE
[4.0] Publish / unpublish plugins not working after the second click

### ISSUE THREAD

**Issue by nikosdion** [joomla/joomla-cms#29412]
### Steps to reproduce the issue

Go to System, Manage Plugins.

Find any published plugin, e.g. System - HTTP Headers.

Click on the published icon in the Status column. It get unpublished.

Click on the unpublished icon in the Status column.

### Expected result

The plugin gets published.

### Actual result

Joomla says "Plugin enabled." but the plugin remains unpublished and the status icon shows unpublished.

I can, however, disable the plugin if I edit it and set published to none.

The same problem exists if I select the checkbox and use the Actions dropdown to select unpublish.

### System information (as much as possible)

System 1: Ubuntu 20.04 with PHP 7.4.4 from the Sury PPA and default Apache 2.4
System 2: macOS Catalina, Apache 2.4, PHP 7.4.5 installed via Homebrew
System 3: Windows 10, IIS, PHP 7.4.5 downloaded from php.net

### Additional comments

This didn't happen with the pre-beta about ten days ago so it must be a recent thing. I'm too tired to debug; it's past 9 pm my time now, sorry.

**Comment by SharkyKZ** [comment]
Can you try on clean installation (of git clone or nightly)? https://github.com/joomla/joomla-cms/pull/29356 should have fixed this.

**Comment by Quy** [comment]
PR #29356 merged 2 days ago should have fixed it.

**Comment by nikosdion** [comment]
That's exactly the solution. As I was debugging it – I really should log off, it's late, I know – I saw the problem was indeed with null values. Sorry, I hadn't seen that other issue. Thank you very much for the quick reply!

**Comment by nikosdion** [comment]
Just a quick note which maybe should be part of the 4.0 beta 2 release notes.

If you had already tried to publish/unpublish a plugin with a click to the status icon the patch will NOT work UNLESS you edit the item and click on Save & Close. From that point on you can click on the status icon to toggle the publish state as many times as you want.

So if you receive reports about this resolved issue don't waste time debugging it. Tell people to edit the item, click on Save & Close and their issue will magically go away.

**Comment by richard67** [comment]
> Just a quick note which maybe should be part of the 4.0 beta 2 release notes.
> 
> If you had already tried to publish/unpublish a plugin with a click to the status icon the patch will NOT work UNLESS you edit the item and click on Save & Close. From that point on you can click on the status icon to toggle the publish state as many times as you want.
> 
> So if you receive reports about this resolved issue don't waste time debugging it. Tell people to edit the item, click on Save & Close and their issue will magically go away.

Confirmed. If you have installed a 4.0 Beta 1 and have unpublished a plugin, and now e.g. update to nightly with the PR included, you have this problem and can solve it by editing the plugin. On a newly installed nightly with the PR included you don't have that.
