### ISSUE TITLE
No admin user created with install process

### ISSUE THREAD

**Issue by ConfidantCommunications** [joomla/joomla-cms#29410]
### Steps to reproduce the issue
Install Joomla.

### Expected result
Ability to log in with new admin user.

### Actual result
Cannot log in. I check the database table for users and it is empty.

### System information (as much as possible)
PHP 7.3.9 on MAMP 5.7

**Comment by Quy** [comment]
Which Joomla version?

**Comment by ConfidantCommunications** [comment]
Joomla 4 beta

**Comment by ConfidantCommunications** [comment]
I tried it again; got a user this time but cannot log in. Will report back soon.

**Comment by ConfidantCommunications** [comment]
I will close this for now since I can get in now. Not sure what happened.
