### ISSUE TITLE
[4.0] #__user_usergroup_map wrong index PRIMARY Key

### ISSUE THREAD

**Issue by HRIT-Florian** [joomla/joomla-cms#29419]
DB Table #__user_usergroup_map has two cols user_id and group_id
One user can be added multiple, because of multiple groups, but user_id is set as primary key.

### Steps to reproduce the issue
Try import a #__user_usergroup_map  where a user is associated to more aus one usergroup

you will see it runs into duplicate  entry error
`Duplicate entry ... for key 'PRIMARY' `

### Expected result
Should be possible to import

### Actual result
Error 
`Duplicate entry ... for key 'PRIMARY' `
Because of PRIMARY Key user_id could only be exists once
Same foru group_id

### System information (as much as possible)
 Joomla! 4.0.0-beta1 Beta [ Mañana ] 30-May-2020 18:32 GMT 
Database Type | mysql 5.7.25-28

![usergorupmap](https://user-images.githubusercontent.com/12803406/83744865-09837180-a65d-11ea-936f-3439f4580dd1.jpg)

**Comment by HLeithner** [comment]
The primary key uses 2 column that means the combination of both columns have to be unique which is correct.

It seams your import data has duplicated entries. ex. 2 rows with user_id: 1 and group_id: 1

**Comment by HRIT-Florian** [comment]
You are right, thanks and sorry @HLeithner 👌
