### ISSUE TITLE
[4.0] Duplicate IDs (adminForm)

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29423]
### Steps to reproduce the issue

1. Go to `/administrator/index.php?option=com_templates&view=templates`
2. Click on `Cassiopeia Details and Files`
3. Inspect the page source

### Expected result

Every ID should be unique

### Actual result

Conflicting ID's (adminForm)

![screeny](https://user-images.githubusercontent.com/2019801/83755379-68e57f80-a665-11ea-8a3b-6a0dfcef91ac.png)

**Comment by brianteeman** [comment]
confirmed

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37131 . Thanks in advance.
