### ISSUE TITLE
[4.0] PHP error in com_templates if ID doesn't exist

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29422]
### Steps to reproduce the issue

Go to `/administrator/index.php?option=com_templates&view=template&id=10000000`

_Note:_ keep the `10000000` in the URL

### Expected result

No PHP error

### Actual result

> Warning: Creating default object from empty value in \administrator\components\com_templates\src\Model\TemplateModel.php on line 1710

along with another 10 ether errors

### Additional notes

If you go to `/administrator/index.php?option=com_content&view=article&layout=edit&id=1000000` (for an article instead), it doesn't show a PHP error, but instead redirects back to the list view.

**Comment by SharkyKZ** [comment]
Duplicate https://github.com/joomla/joomla-cms/issues/29345.
