### ISSUE TITLE
[4.0] Notices image_intro_caption in articles layouts

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#29427]
### Steps to reproduce the issue
Create an article with an Intro Image, without Caption
View the font-end

### Expected result

NO warning

### Actual result

Warn about image_intro_caption

### System information (as much as possible)
Joomla 4.0 Beta 1

### Additional comments

In `/layouts/joomla/content/intro_image.php` the cose is:
```
		<?php if ($images->image_intro_caption !== '') : ?>
			<figcaption class="caption"><?php echo htmlspecialchars($images->image_intro_caption, ENT_COMPAT, 'UTF-8'); ?></figcaption>
		<?php endif; ?>
```

I suggest change the code with:

```
		<?php if (!empty($images->image_intro_caption)) : ?>
			<figcaption class="caption"><?php echo htmlspecialchars($images->image_intro_caption, ENT_COMPAT, 'UTF-8'); ?></figcaption>
		<?php endif; ?>
```

REF: https://github.com/joomla/joomla-cms/pull/20503#issuecomment-639096109
@infograf768

**Comment by richard67** [comment]
@infograf768 I think @Razzo1987 is right here, and both changes from your PR #20503 should be modified from `if ($images->image_fulltext_caption !== '')` to `if (!empty($images->image_intro_caption))`.

As as I understand the type safe comparison `!==`, it is true if the values or the data types are different. As `null` is a separate data type in PHP, this would only result in true if the value is an empty string, but not if the value is null. But `!empty()` covers both, not null and not empty string.

**Comment by richard67** [comment]
@infograf768 Do you wanna make a new PR?

**Comment by infograf768** [comment]
Please do. ;)

**Comment by richard67** [comment]
I don't have time before late evening today or even tomorrow.

**Comment by infograf768** [comment]
@SharkyKZ 
The code was done this way after your suggestion:
https://github.com/joomla/joomla-cms/pull/20503#issuecomment-390471409

Quid?

Also, I can't confirm the error at all

**Comment by richard67** [comment]
I haven't tested yet if I can confirm the issue.

**Comment by infograf768** [comment]
<img width="682" alt="Screen Shot 2020-06-05 at 09 04 40" src="https://user-images.githubusercontent.com/869724/83847317-51150680-a70c-11ea-8c8a-aa6f63b3b175.png">

<img width="935" alt="Screen Shot 2020-06-05 at 09 08 21" src="https://user-images.githubusercontent.com/869724/83847336-5a9e6e80-a70c-11ea-88dd-2086fc1a00a8.png">

<img width="716" alt="Screen Shot 2020-06-05 at 09 09 14" src="https://user-images.githubusercontent.com/869724/83847364-65590380-a70c-11ea-8542-073e561462d5.png">

**Comment by SharkyKZ** [comment]
My guess this occurs when creating articles programmatically (e.g. using the API) and not providing some fields. I guess we can fix this. But then there's more places like this, e.g. URLs in articles.

**Comment by richard67** [comment]
@SharkyKZ Sounds reasonable. Could you make a PR?

**Comment by infograf768** [comment]
API and I are long time enemies. Can't help here.
Some one has to test using API.

**Comment by richard67** [comment]
With API testing I am a bit familiar meanwhile, so if someone makes a PR I can test later tonight or tomorrow.

**Comment by Razzo1987** [comment]
Yes, I have created the article with API

**Comment by alikon** [comment]
with or without #29020 ?
asking for a friend of mine :smile:

**Comment by Razzo1987** [comment]
Only Joomla 4.0 Beta 1 (https://github.com/joomla/joomla-cms/releases/download/4.0.0-beta/Joomla_4.0.0-beta1-Beta-Full_Package.zip)

**Comment by PhilETaylor** [comment]
You can replicate this with the Testing Data in Joomla 4 - see the following for instructions https://github.com/joomla/joomla-cms/issues/29507

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29513.
