### ISSUE TITLE
[4.0] JS error in com_menus

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29437]
### Steps to reproduce the issue

This is similar to https://github.com/joomla/joomla-cms/issues/29436 but I'm creating a separate issue just incase

1. In the Menu Manager, open edit menu item
2. Click on the `Module Associations` tab
3. Select any module (a modal will appear)
4. Click the `Close` modal button

### Expected result

No JS error

### Actual result

> h is null   ---  admin-module-edit.min.js:1:2012

**Comment by SharkyKZ** [comment]
Please test PR #29443.
