### ISSUE TITLE
[4.0] [RTL] Media Manager Info slideout

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29433]
### Steps to reproduce the issue

Enable an RTL language in the backend, then go to the Media Manager and click on the "i" icon.

On LTR, the container slides out from the right hand side as per normal, however on RTL, the container also slides out from the right and is first visible on top of the content.

See the differences:

### LTR
![ltr](https://user-images.githubusercontent.com/2019801/83868942-a6104700-a723-11ea-8686-c981b0831617.gif)

### RTL
![rtl](https://user-images.githubusercontent.com/2019801/83868952-aa3c6480-a723-11ea-85f0-cc4d35ea37fe.gif)

**Comment by wilsonge** [comment]
See https://github.com/joomla/joomla-cms/pull/29475
