### ISSUE TITLE
[4.0] jQuery is not defined in com_menus

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29436]
### Steps to reproduce the issue

1. In the Menu Manager, open edit menu item
2. Click on the `Module Associations` tab
3. Select any module (a modal will appear)

### Expected result

No JS error

### Actual result

> jQuery is not defined    --   treeselectmenu.min.js

**Comment by brianteeman** [comment]
The only error I get when doing that is when I close the modal
```

VM444 admin-module-edit.js:80 Uncaught TypeError: Cannot set property 'innerHTML' of null
    at Object.Joomla.submitbutton (VM444 admin-module-edit.js:80)
    at HTMLButtonElement.onclick (index.php?option=com_modules&view=module&tmpl=component&layout=modal&id=120&client_id=0:110)
    at HTMLButtonElement.<anonymous> (admin-item-edit_modules.js?84b1de9577ab54f332d68209292c8163:96)
```

**Comment by brianteeman** [comment]
and I see you have a seperate issue for that

**Comment by PixedBo** [comment]
I can confirm the error:

![immagine](https://user-images.githubusercontent.com/12549961/83899207-5304b700-a758-11ea-9ac4-386ff45d988c.png)

the first one when i click on a module, the second when i close the modal

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29447.
