### ISSUE TITLE
[4.0] [RTL] Tree select styling

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29438]
### Steps to reproduce the issue

Ensure you're using an RTL language

1. In the Menu Manager, open edit menu item
2. Click on the `Module Assignment` tab
3. Select any module (a modal will appear)
4. Click the `Menu Assignment` tab

### Actual result

![rtl](https://user-images.githubusercontent.com/2019801/83872539-19b55280-a72a-11ea-92d3-d09cfe96649f.png)

**Comment by adj9** [comment]
I can't find the screenshot you're looking at. What steps did you take?

**Comment by C-Lodder** [comment]
@adj9 The steps in the `Steps to reproduce the issue` list

**Comment by infograf768** [comment]
@C-Lodder 
I also can't find.
What is the `Module Association` tab when one edit a menu item?

**Comment by infograf768** [comment]
@C-Lodder

**Comment by brianteeman** [comment]
Module Assignment

**Comment by C-Lodder** [comment]
@infograf768 Here's a gif showing you:
![rtl](https://user-images.githubusercontent.com/2019801/83940292-6efd6c80-a7db-11ea-92eb-256bdf309d91.gif)

**Comment by infograf768** [comment]
Yep, I found, although the display is a bit different from yours. Corrected your instructions.

LTR
<img width="381" alt="Screen Shot 2020-06-06 at 10 56 55" src="https://user-images.githubusercontent.com/869724/83940481-ade3f000-a7e4-11ea-884e-bd00871f1304.png">

RTL
<img width="958" alt="Screen Shot 2020-06-06 at 10 57 33" src="https://user-images.githubusercontent.com/869724/83940484-bb997580-a7e4-11ea-88e2-479d9bf01466.png">

Looking at it to see if I can help.

**Comment by infograf768** [comment]
In fact simpler as it is the same issue when not in modal
Set language to Persian
Edit a site module=>Menu Assignments

**Comment by infograf768** [comment]
Patch coming.

**Comment by infograf768** [comment]
Please test
https://github.com/joomla/joomla-cms/pull/29453
