### ISSUE TITLE
[4.0] [Atum] External link icons

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29432]
### Steps to reproduce the issue

Go to `/administrator/index.php?option=com_templates&view=styles`

### Actual result

Looks rather weird having multiple icons like this

![screeny](https://user-images.githubusercontent.com/2019801/83864075-2763db80-a71c-11ea-9e99-9d4a382b4f8c.png)

**Comment by infograf768** [comment]
We could get this when preview on:

<img width="936" alt="Screen Shot 2020-06-05 at 12 24 28" src="https://user-images.githubusercontent.com/869724/83866129-9e52a180-a727-11ea-950d-dc6f461cce0c.png">

and keep the eye slash when preview off

<img width="954" alt="Screen Shot 2020-06-05 at 12 24 49" src="https://user-images.githubusercontent.com/869724/83866176-b62a2580-a727-11ea-9064-229e471f3ef2.png">

**Comment by brianteeman** [comment]
Please see #29717
