### ISSUE TITLE
[4.0] [Atum] Media Manager "close" button is hard to see

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29434]
### Steps to reproduce the issue

Open an image in the Media Manager to preview it.
An "X" icon will appear in the top right, however it's not very noticeable.

**_Note:_** The user should also be allowed to click the backdrop to close the preview

![screeny](https://user-images.githubusercontent.com/2019801/83869302-4a928900-a724-11ea-9118-66587e307223.png)

**Comment by brianteeman** [comment]
agreed. especially hard with a small image on a large screen.

I am sure this was reported before but I can not find it right now

**Comment by brianteeman** [comment]
Please test #30851
