### ISSUE TITLE
[4.0] [RTL] Media Manager description list - text alignment

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#29435]
### Steps to reproduce the issue

When using an RTL language, the description list text isn't aligned correctly.
Some is to the right, and some is to the left

![screeny2](https://user-images.githubusercontent.com/2019801/83869617-c1c81d00-a724-11ea-8431-27c250cb8233.png)

**Comment by infograf768** [comment]
hmm.
In RTL, we do need direction ltr to display correctly the folder, dates, size

in LTR, we have
<img width="431" alt="Screen Shot 2020-06-08 at 11 40 05" src="https://user-images.githubusercontent.com/869724/84016609-d05d4100-a97d-11ea-91b0-b44f4fcd66fb.png">

Trying to find a solution.

**Comment by infograf768** [comment]
Easy to solve. only a text-align setting.
making PR.

**Comment by infograf768** [comment]
Closing as we have a patch https://github.com/joomla/joomla-cms/pull/29483
