### ISSUE TITLE
changing default language to nl-NL_joomla_lang_full_4.0.0vb1 did not work

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#29442]
### Steps to reproduce the issue
install languges

**Comment by conconnl** [comment]
Just installed J4 Beta.
Downloaded NL language from JC website.
Installed it and pressed the Star.

Result:
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/11913918/83893033-bb02cf80-a74f-11ea-87b5-a728fc6735e8.png">

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/11913918/83893063-c48c3780-a74f-11ea-8b63-59d2a465aa93.png">

**Comment by infograf768** [comment]
1. How is it that you got a nl-NL 4.0.0 lang pack from JC ? Where was it exactly?
2. What is wrong ? What does not work?

**Comment by conconnl** [comment]
@MartijnMaandag  translated it and put it on the site to download.
I don't know where it should be, at least not Joomlacode.

**Comment by infograf768** [comment]
> translated it and put it on the site to download

on which site? It should not be proposed as j3 update.

**Comment by conconnl** [comment]
Don't know what you mean with J3.
This issue is about J4 and NL language file.
The file is on the JC Downloads page (https://www.joomlacommunity.nl/downloads) as J4 Language Download.

I didn't create the issue, so don't know what the issue is for the creator.
I can just install the language and make it work in J4

**Comment by richard67** [comment]
Nobody knows what the issue is for the creator because there is not proved any information except of „does not work“.

**Comment by brianteeman** [comment]
JC apparently means JoomlaCommunity.nl and not JoomlaCode.org

https://www.joomlacommunity.nl/downloads/joomla-4/90-nederlands-taalpakket-nl-nl-joomla-4-0-0-beta

Having said that I was able to download and install that language pack without any problem and had no problem making it the default language

**Comment by infograf768** [comment]
Ok, the package is NOT on joomlacode. JC for all here is Joomlacode, not joomlaCommunity.nl

**Comment by infograf768** [comment]
And, yes, no problem with the pack, as the screenshots you posted show well.
Not an issue. Closing.

**Comment by ghost** [comment]
> JC apparently means JoomlaCommunity.nl and not JoomlaCode.org
> 
> https://www.joomlacommunity.nl/downloads/joomla-4/90-nederlands-taalpakket-nl-nl-joomla-4-0-0-beta
> 
> Having said that I was able to download and install that language pack without any problem and had no problem making it the default language

Please help, how can I install this pack? I use joomla4 on mamp local on a macbook.

**Comment by ghost** [comment]
> Just installed J4 Beta.
> Downloaded NL language from JC website.
> Installed it and pressed the Star.
> 
> Result:
> <img alt="image" width="1403" src="https://user-images.githubusercontent.com/11913918/83893033-bb02cf80-a74f-11ea-87b5-a728fc6735e8.png">
> 
> <img alt="image" width="1402" src="https://user-images.githubusercontent.com/11913918/83893063-c48c3780-a74f-11ea-8b63-59d2a465aa93.png">

ik heb de .zip gedownload maar weet niet hoe te installeren, 

> Just installed J4 Beta.
> Downloaded NL language from JC website.
> Installed it and pressed the Star.
> 
> Result:
> <img alt="image" width="1403" src="https://user-images.githubusercontent.com/11913918/83893033-bb02cf80-a74f-11ea-87b5-a728fc6735e8.png">
> 
> <img alt="image" width="1402" src="https://user-images.githubusercontent.com/11913918/83893063-c48c3780-a74f-11ea-8b63-59d2a465aa93.png">



> Just installed J4 Beta.
> Downloaded NL language from JC website.
> Installed it and pressed the Star.
> 
> Result:
> <img alt="image" width="1403" src="https://user-images.githubusercontent.com/11913918/83893033-bb02cf80-a74f-11ea-87b5-a728fc6735e8.png">
> 
> <img alt="image" width="1402" src="https://user-images.githubusercontent.com/11913918/83893063-c48c3780-a74f-11ea-8b63-59d2a465aa93.png">



> Just installed J4 Beta.
> Downloaded NL language from JC website.
> Installed it and pressed the Star.
> 
> Result:
> <img alt="image" width="1403" src="https://user-images.githubusercontent.com/11913918/83893033-bb02cf80-a74f-11ea-87b5-a728fc6735e8.png">
> 
> <img alt="image" width="1402" src="https://user-images.githubusercontent.com/11913918/83893063-c48c3780-a74f-11ea-8b63-59d2a465aa93.png">

Wat moet ik stap voor stap doen om nl pack te installeren? Via install extensies>languages werkt het bij mij niet. Ook niet via install extensies by map, url of web. Voel me een beetje dom worden, ben ik niet hoor, wel nieuw in 4 beta!!

**Comment by MartijnMaandag** [comment]
Install extension.

**Comment by ghost** [comment]
Dank je wel, maar hoe precies install ik welke extension?
Bedoel je deze .xml ? pkg_nl-NL lukt me ook niet!!

**Comment by conconnl** [comment]
For Dutch support please go too:
https://www.joomlacommunity.nl/forum

For English you can go to https://forum.joomla.org

This is for issues within the code base of Joomla, not for General support. 
Thank you.

**Comment by ghost** [comment]
ok
