### ISSUE TITLE
[4.0] Front-end editing, invisible text for Status field

### ISSUE THREAD

**Issue by Fedik** [joomla/joomla-cms#29452]
### Steps to reproduce the issue

Edit article on front-end, check the status field

![image](https://user-images.githubusercontent.com/1568198/83941474-4c2b8200-a7f4-11ea-8a7a-5e7f8b842063.png)

### Expected result

You should be able to see a status

### Actual result

The status invisible, because `color:white` for status field.

Browser: Chrome 83.0.4103.97, for Linux

**Comment by Quy** [comment]
Please test PR #29269
