### ISSUE TITLE
[4.0] Problem creating new module positions

### ISSUE THREAD

**Issue by rbuelund** [joomla/joomla-cms#29459]
### Steps to reproduce the issue
Create two custom modules with positions bubletopright and bubletopleft.
Create a third custom module with position bublebottomright

### Expected result
Posible to create the new third module in new position

### Actual result
Not posible to create a module in new position - one of the other positions is selected all the time!

### System information (as much as possible)
Fresh instal of Joomla 4 beta

**Comment by chmst** [comment]
I cannot reproduce this. Are you sure that you have pressed the enter-button to complete the input of the new position name?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29459">issues.joomla.org/tracker/joomla-cms/29459</a>.</sub>

**Comment by brianteeman** [comment]
I can confirm this. It is the same problem everywhere that we have the ability to create new inside a select eg tags, categories

The problem is that if you have created "banana" then the script wont let you create "banana2" because it has matched with "banana"

**Comment by brianteeman** [comment]
The problem is in our javascript https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/system/js/fields/joomla-field-fancy-select.w-c.es6.js

Sorry I'm not going to even attempt to fix it

cc @fedik

**Comment by Fedik** [comment]
hm, that can be tricky, need to look what Choices offer for it

**Comment by brianteeman** [comment]
I "think" that part is joomla js not choices

**Comment by Fedik** [comment]
well, Choices offers nothing :smile: 
in past we had some code to handle this case, but now it not work, something internally changed in choices.js

need some time

**Comment by chmst** [comment]
The trick is (since always in J3). to move the mouse out of the select and then back to the inputfield.

**Comment by rbuelund** [comment]
But a trick is not an intuitive solution. I think it is important to make a real fix for this. But I have no insight into the choices package. Obviously there is some comparising going on that is not as strict as it should be.

**Comment by Fedik** [comment]
please test #29793

> The trick is (since always in J3). to move the mouse out of the select and then back to the inputfield.

this trick also not work in J4, but I have add similar behavior in #29793
