### ISSUE TITLE
[4.0b1] plugin manager toolbar on mobile state not correct button?

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#29468]
### Steps to reproduce the issue
open the configuration for a plugin on a mobile device (small screen)

1. toolbar is open and button to close the toolbar is 'cogs'

2. click the cogs button > toolbar stays open and cogs button is replaced by close button

3. click close button, toolbar closes correctlu

### Expected result

step 1 when toolbar is open, button should be type close, not cogs
step 2 when clicking button on open toolbar, toolbar should close not stay open

### Actual result

step 1.
![screen shot 2020-06-07 at 09 26 10](https://issues.joomla.org/uploads/1/09ffff6fe70b3da685bdd469578b6e00.jpg)
step 2.
![screen shot 2020-06-07 at 09 26 19](https://issues.joomla.org/uploads/1/93a4ba540840b1280406b48cc15d4968.jpg)
step 3.
![screen shot 2020-06-07 at 09 26 30](https://issues.joomla.org/uploads/1/ebab4c9410cffeceeba0a7b710886e5b.jpg)

### Additional comments
I personally think that initial state for the toolbar should be closed as this is for a user not the first thing he / she is going to do when entering the config. Because it is open initially, it pushes down everything and for a large part of the screen, so the first thing you need to do as a user is to close this toolbar before you can do anything else.

**Comment by Quy** [comment]
See PR #27958

**Comment by Quy** [comment]
Please test PR #30131

**Comment by Ruud68** [comment]
Hi @Quy I have tried it but the patchtester is telling me "There are no files to patch from this pull request. This may mean that the files in the pull request are not present in your installation"

So not able to test, or am I missing something?

**Comment by Quy** [comment]
If you are not testing with the development branch, then use the package installer which includes this PR: https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/30131/downloads/34008/
