### ISSUE TITLE
Meta-Keywords from article not listed

### ISSUE THREAD

**Issue by Harry5001** [joomla/joomla-cms#29467]
### Steps to reproduce the issue

Create a new article, define some keywords in the Publishing Tab. Save the article. Then open the article at the Front-End and check HTML.

### Expected result

The defined keywords should be displayed in HTML coding.

### Actual result

No Keywords from the article are displayed.

### System information (as much as possible)

Joomla 4 Beta 1

### Additional comments

Tested on two separate Joomla installations / servers.

**Comment by brianteeman** [comment]
Correct that is the intended behaviour.
Please see https://github.com/joomla/joomla-cms/pull/25258

**Comment by Harry5001** [comment]
I see. There were some further confusions because I was using the german language. I will switch back to english to avoid that in the future. In that language pack the fields "tags" under "content" is labeled "keywords" and the field "keywords" unter "publishing" is labeled "meta-keywords". Sorry for that.
