### ISSUE TITLE
[4.0] Webauthn button in com_users needs padding

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#29470]
![image](https://user-images.githubusercontent.com/1497730/83966920-9167b680-a8bd-11ea-820f-e608a46833cb.png)

### What needs to be fixed
The "Webauthn" button is directly attached to the "Log In" button.

### Why this should be fixed
Looks ugly?

**Comment by brianteeman** [comment]
1. you can have multiple buttons
2. Not tested it myself but this was a screenshot showing that taken from #29454 

![image](https://user-images.githubusercontent.com/1296369/83969818-fd501c00-a8c9-11ea-8873-0fd2e62f92e3.png)

**Comment by HLeithner** [comment]
That's the module not the com_user login view

**Comment by brianteeman** [comment]
Sorry I missed that in the title. The comment about multiple buttons is still valid though.

**Comment by nikosdion** [comment]
That should be something to be addressed in the output of com_users. You could add the mb-2 class on each extra button but please wait until https://github.com/joomla/joomla-cms/pull/29454 is merged first to avoid conflicts and duplicate work.

**Comment by Quy** [comment]
Duplicate #29138 due to no `control-group` class for the frontend template.

![29470](https://user-images.githubusercontent.com/368084/92140135-90afc500-edc5-11ea-9e33-a5c3bb0d20a6.png)

**Comment by ghost** [comment]
Label `J4 Frontend Template`?

**Comment by infograf768** [comment]
Can't we just add a class for control-group?
```
diff --git a/templates/cassiopeia/scss/blocks/_form.scss b/templates/cassiopeia/scss/blocks/_form.scss
index ae587bc..adf4870 100644
--- a/templates/cassiopeia/scss/blocks/_form.scss
+++ b/templates/cassiopeia/scss/blocks/_form.scss
@@ -22,4 +22,8 @@
 }
 
+.control-group {
+  margin-top: .5rem;
+}
+
 .custom-select {
   max-width: $input-max-width;

```
It would also work for https://github.com/joomla/joomla-cms/issues/29228 and https://github.com/joomla/joomla-cms/issues/29138

**Comment by hans2103** [comment]
Or apply [Lobotomized Owl](https://alistapart.com/article/axiomatic-css-and-lobotomized-owls/) selector
```
* + * {
  margin-top: .5em;
}
```

**Comment by infograf768** [comment]
My local owls protest strongly against lobotomization... ;)
![bitingowl_small](https://user-images.githubusercontent.com/869724/93858614-b3464700-fcbc-11ea-8e06-4b05f67a859f.png)

**Comment by Quy** [comment]
Here is the history of this class.

Bootstrap 2: `.control-group`
Bootstrap 3/4: `.form-group`
Bootstrap 5: `.mb-3`

So instead of top margin it should be bottom margin to be consistent with Bootstrap?

**Comment by infograf768** [comment]
That will not work for the Submit buttons. https://github.com/joomla/joomla-cms/issues/29228

**Comment by infograf768** [comment]
But we could use another css for these com_users buttons:
```
diff --git a/templates/cassiopeia/scss/blocks/_form.scss b/templates/cassiopeia/scss/blocks/_form.scss
index ae587bc..4c26844 100644
--- a/templates/cassiopeia/scss/blocks/_form.scss
+++ b/templates/cassiopeia/scss/blocks/_form.scss
@@ -113,2 +113,7 @@
   bottom: auto;
 }
+
+// com_users submit buttons
+[class^=com-users-] {
+  margin-top: .5rem;
+}
```

**Comment by Quy** [comment]
It will work because it is wrapped in a `control-group`.

![register](https://user-images.githubusercontent.com/368084/93908473-82addf80-fcb3-11ea-90ed-52242dadb72c.png)

**Comment by infograf768** [comment]
@Quy
You are right. Can you make patch?

**Comment by Quy** [comment]
@infograf768 There is a PR under the cassiopeia repo: https://github.com/joomla/cassiopeia/pull/99

**Comment by Quy** [comment]
Please test PR #31520
