### ISSUE TITLE
[PHP] - [FastCGI](Apache): images & components are not uploaded to the site through this mode

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#29473]
### Steps to reproduce the issue
I tried to upload images to my site in the `control panel`, but could not. I tried `drag and drop`, tried through `standard loading`(ftp), but all my attempts were unsuccessful. Images were not uploaded to articles.

Also, any components and plugins did not load if I tried to download them from my computer.

Images and components were downloaded only if I provided a link to another website, but nothing was downloaded from my computer.

### Expected result
Images and components must be uploaded to my site from my computer

### Actual result
Images and components cannot be uploaded to my site from my computer

### System information (as much as possible)
Joomla 3.9.19, PHP 7.2.31, 5.5.65-MariaDB
PHP: **FastCGI** (Apache)
![изображение](https://user-images.githubusercontent.com/3662519/83974997-dc072400-a8f9-11ea-8847-fa51007ebd09.png)

### Additional comments
Uploading images and components works well in mode: PHP - **CGI** and absolutely not working in mode **FastCGI**

I think it’s worth adding a special warning for sites if a mode FastCGI is installed, as well as done now, if the site does not meet the minimum requirements for the transition to Joomla 4.

**Comment by brianteeman** [comment]
Sorry to say but it absolutely does work with FastCGI

**Comment by 4digitalworld** [comment]
> 
> 
> Sorry to say but it absolutely does work with FastCGI

It's strange to hear this, because I no longer changed any settings on my VPS, I just switched this PHP mode. And in one case, I can upload images to the site from my computer, and in the other case, the images do not upload.

And this has happened over the years on different servers over the past 10 years, when I changed the VPS and hosting.

**Comment by brianteeman** [comment]
All I can say is that my localhost and clients domains hosted at siteground all use fastcgi

**Comment by brianteeman** [comment]
This should be closed - it is not a joomla bug
