### ISSUE TITLE
[4.0b1] Can use a single char super admin password on install

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29476]
### Steps to reproduce the issue

Attempt to install Joomla 4.0.0. beta 1 
For your super admin use `a` as a password

### Expected result

Error saying "use a secure password that meets some kind of limitations that the Joomla project has set as a minimum for super admins at the time of installation"

### Actual result

`a` is a valid super admin password.

**Comment by richard67** [comment]
@brianteeman Do you know if we have some regex already somewhere for checking password strength with some kind of minimum requirement, but safe enough for installation? If not, maybe you can suggest a regex? I would know where to implement the check then.

Update: Or just suggest the rule, I could make the regex myself.

Same with some language string: Do we already have one for a suitable validation error message?

**Comment by brianteeman** [comment]
See #27253 and the comments

**Comment by richard67** [comment]
I see, thanks. Let's see if someone wants to make a PR.

**Comment by Quy** [comment]
Related #20312

**Comment by richard67** [comment]
Well, JS it would need for a nice solution with a password strength meter. With this I can't help.

What I could do - and maybe it should be done anway as a second line of defense even if there is a client-side validation - is to add a server-side validation against some minimum, hard-coded requirements (which we first have to agree about) to the setup model.

@SniperSister Would you recommend that, a server-side check in PHP using a regex? If so, what should be the hard-coded requirements? Minimum 1 character of each kind (lowercase, uppercase, digit, symbol) and minimum length of 8? Or better 10?

**Comment by SniperSister** [comment]
@richard67 

If you *really* want to enforce your password policy, you have to enforce it on the serverside of things for obvious reasons. In this case however, I think that a JS-based solution is good enough if that makes everyones live easier.

Regarding the complexity question: the topic has been raised for j.org properties too (see https://github.com/joomla/joomla-websites/issues/1454, cc'ing @brianteeman). 

Length: A min length of 8 characters is a no-brainer; considering that the super admin account is a rather critical asset, I would suggest that we even use 10.

Complexity: The current policy, at least on the JCM site, seems to require at least one symbol. Some entities specifically recommend such an enforcement (i.e. www.enisa.europa.eu), others strongly advocate against it (i.e. NIST). We will discuss that question in the next JSST meeting and afterwards I'll get back to you.

**Comment by brianteeman** [comment]
I am not sure where enisa make that recommendation about symbols. All I found was this [article](https://www.enisa.europa.eu/news/enisa-news/tips-for-secure-user-authentication) where is stresses that you should use a password manager. The UK  [NCSC](https://www.ncsc.gov.uk/collection/passwords/updating-your-approach) specifically say they do "_**not** recommend the use of complexity requirements_" other than for minimum length.

As neither google, firefox or keepass and probably others (just not tested them) can not be forced to include a symbol and do not include a symbol by default then the rule makes using a password manager harder not easier.

**Comment by SniperSister** [comment]
Quoting the enisa Password best practice:
> Use  complex  passwords  longer  than  8  characters, which  contain  alphanumeric  and  special characters

German BSI either recommends "short and complex" (8-12 characters, lowercase, uppercase, digits and symbols) or "long and simple" (20 to 25 characters, two sorts of characters).

**Comment by brianteeman** [comment]
thanks. 

If the policy prevents the usage of a password manager then it's a bad policy from my perspective no matter what type of character is used.

**Comment by SniperSister** [comment]
> If the policy prevents the usage of a password manager then it's a bad policy from my perspective no matter what type of character is used.

I see your point. However not all users are using a password manager, so giving guidance to people entering a short and potentially unsafe password is equally important.

I kind of like the combination approach:
If your password is short (8-12 characters) you need an extra symbol to increase complexity, if it's longer (which should be the case for a password manager) less complexity is ok.

What do you think about that?

**Comment by PhilETaylor** [comment]
Why are you even discussing this. Why not just adopt the default settings that Joomla applies after installation in User manager, to before the installation, when setting the super admin password.

After standard installation, with no changes, its impossible to set a password as `a` in User Manager. 

The (insane) defaults currently are 

<img width="1158" alt="Screenshot 2020-06-08 at 14 47 02" src="https://user-images.githubusercontent.com/400092/84037788-fb07c380-a996-11ea-9006-f28110022c50.png">

Its a whole difference conversation to have about what minimum standards Joomla should apply. The current minimum length of 4 for example is insane and way below any acceptable standard produced by any authority - however its up to the site admin to set THEIR own rules and not for Joomla to enforce any on a site 

Therefore the fix for this reported issue is to make the super admin password validate against the same rules that the User Manager uses by default. (And if Joomla wishes to upgrade those minimum requirements, then that's a whole different topic of conversation!)

**Comment by PhilETaylor** [comment]
And for the record, 1Password.com and all its apps can and do generate passwords with a combination of symbols however you want it. 

<img width="520" alt="Screenshot 2020-06-08 at 14 45 01" src="https://user-images.githubusercontent.com/400092/84038170-7c5f5600-a997-11ea-9a69-1250b8d8696d.png">

The UK Cyber Essentials guidelines - used by government organisations looking for funding, require a minimum of 8 chars and NO OTHER RULES as other rules actually decrease the chances of a human selecting a secure password. They do however insist that users are prompted to, and encouraged to use a password manager and 2FA (Although Joomla refuses to enable 2FA by default as evidenced in past issues)

**Comment by brianteeman** [comment]
@PhilETaylor what is the default for 1password?

**Comment by brianteeman** [comment]
@SniperSister 
> I see your point. However not all users are using a password manager, so giving guidance to people entering a short and potentially unsafe password is equally important.

Exactly but the current _password strength_ is not doing that at all. That is why I requested the use of zxcvbn library. It is also why I reported the issue to JSST but as usual no reply. ;(

**Comment by PhilETaylor** [comment]
> @PhilETaylor what is the default for 1password?

Length 24
Digits 1
Symbols 0 
Avoid ambiguity: On

**Comment by brianteeman** [comment]
Thanks - thought so just wanted to have it confirmed.

**Comment by PhilETaylor** [comment]
> Exactly but the current password strength is not doing that at all. That is why I requested the use of zxcvbn library. It is also why I reported the issue to JSST but as usual no reply. ;(

I repeatedly throughout the Joomla 4 development cycle expressed concerns (in GitHub issues that can be dug out) with the password meter and was repeatedly told that it was only a visual indication that it passed the validation rules and not that the password was actually "strong".

**Comment by SniperSister** [comment]
@PhilETaylor @brianteeman issue was discussed during today's JSST meeting and proposal for a policy is up for comment for the other team members internally. Will share the outcome on thursday!

**Comment by PhilETaylor** [comment]
Specifically what is "up for comment" in the JSST?

1) That a super admin on installing can use a single char as a super admin password with no restrictions or limitations on the password at all? **THE REASON FOR THIS GITHUB ISSUE**

**To close this GitHub issue all that is needed is for the installer to implement the same defaults as Joomla will, once the install is complete, which are documented in the image** 

![](https://user-images.githubusercontent.com/400092/84037788-fb07c380-a996-11ea-9006-f28110022c50.png)

Other issues discussed but could be forked to their own issues and discussed [until the cows come home](https://idioms.thefreedictionary.com/until+the+cows+come+home):

2) The fact that a "progress meter" is used to show compliance with site's own requirements (however insecure they are) and gives a false sense of "security" that a password is "more secure" the higher up the progress bar you go?

3) Joomla's whole approach to minimum password requirements in line with government and other official sources of security recommendations?

**Comment by zero-24** [comment]
PR has been landed here: #29859

**Comment by zero-24** [comment]
> To close this GitHub issue all that is needed is for the installer to implement the same defaults as Joomla will, once the install is complete, which are documented in the image

This has been adressed in the PR mention please confirm and than close here thanks @PhilETaylor

**Comment by PhilETaylor** [comment]
12 chars...  wow. Cant see people gonna like that 🤪

Also the cli now needs to implement this minimum too...

**Comment by PhilETaylor** [comment]
For cli see https://github.com/joomla/joomla-cms/issues/29817
