### ISSUE TITLE
[4,0b1] Select a Module Type screen on mobile squashed

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29487]
### Steps to reproduce the issue

***I  know there are ALMOST similar issues raised for other screens, adding this one for this specific screen***

install joomla 4.0.0b1 and login to admin on iPhone

go to the + next to modules

http://example.com/administrator/index.php?option=com_modules&view=select&client_id=0

### Expected result

useable screen 

### Actual result

<img width="500" alt="Screenshot 2020-06-08 at 15 26 27" src="https://user-images.githubusercontent.com/400092/84042012-74ee7b80-a99c-11ea-9af0-d95ab6bc5550.png">

### System information (as much as possible)

iPhone 11 max pro - but repeatable on squashed browser screen

**Comment by Quy** [comment]
Duplicate #29064

**Comment by PhilETaylor** [comment]
ok
