### ISSUE TITLE
[4.0b1] Button toggle on mobile view starts on wrong state

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29488]
### Steps to reproduce the issue

Login to Joomla 4.0.0 beta 1 Admin on iPhone
Click + next to modules

### Expected result

Either
1) a X graphic and a cancel button that when graphic is clicked hides buttons
or
2) a Cogs graphic and no buttons that when graphic is clicked shows buttons

### Actual result

a Cogs graphic and buttons are shown and when graphic is clicked, animation shows the buttons again

<img width="504" alt="Screenshot 2020-06-08 at 15 28 48" src="https://user-images.githubusercontent.com/400092/84042549-1d044480-a99d-11ea-92fd-0a58a1bf980b.png">

![Screen Recording 2020-06-08 at 03 34 PM](https://user-images.githubusercontent.com/400092/84042881-8ab07080-a99d-11ea-89ed-c9855d7e9079.gif)

### System information (as much as possible)

Discovered on iPhone 11 max pro but reproducible on squashed browser. Tested with squashed safari on Mac.

**Comment by ReLater** [comment]
Duplicate ? https://github.com/joomla/joomla-cms/pull/27958
There are already issues related to this one, I think, but I am not sure. I don't understand all this custom JS reinventing the wheel.

**Comment by PhilETaylor** [comment]
I would love to say its a duplicate but there are multiple places - for example go to Joomla Global Configuration on a mobile, and click the Toggle menu button and the same kind of thing happens, the menu on page load is already showing and the first click of toggle menu just animates the SHOWING of the menu again, instead of hiding it. The fix in #27958 looks specific to one example only. 


<img width="501" alt="Screenshot 2020-06-08 at 16 12 24" src="https://user-images.githubusercontent.com/400092/84047157-e0d3e280-a9a2-11ea-8b70-cfdcef976ff4.png">

**Comment by C-Lodder** [comment]
Issue for Global Config related toggle: https://github.com/joomla/joomla-cms/issues/29192

**Comment by PhilETaylor** [comment]
Awesome. Github needs a better search as I did look before posting

**Comment by C-Lodder** [comment]
I'd leave it open to be honest. Not really a duplicate as the toggle I've raised is for a different element

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/pull/27958 covers the other element and #29192 covers the com_config so mine is covered by those both
