### ISSUE TITLE
[4.0b1] No Matching Results when starting menu assignments

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29489]
### Steps to reproduce the issue

install Joomla 4.0.0 beta 1 with no sample data
login to admin as super admin
attempt to create new module 
Go to Menu Assignment tab
Select "only on the pages selected"
Note the yellow warning "No Matching Results"

### Expected result

<img width="1224" alt="Screenshot 2020-06-08 at 15 40 54" src="https://user-images.githubusercontent.com/400092/84043648-7c168900-a99e-11ea-81d7-81d7549884f9.png">

### Actual result

unclear yellow warning "No Matching Results" - not sure WHAT results it was looking for as all I have done is open this panel so far. 

The warning should be hidden by default.

### Additional comments

It looks related to the sieve filter search - because if you search for crap you are left with the yellow warning, and if you then search for Home (a valid menu item name) the yellow warning is not there.

**Comment by ghost** [comment]
Issue confirmed.

![Screen Shot 2020-09-21 at 15 11 35](https://user-images.githubusercontent.com/70466955/93770701-d3bec480-fc1c-11ea-99e2-056f088e359f.png)

**Comment by brianteeman** [comment]
please see #30854
