### ISSUE TITLE
[4.0b1] mod_footer renders content when it should not with ?tp=1

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29494]
### Steps to reproduce the issue

install Joomla 4.0.0b1 with no sample content
go to Template options and enable `Preview Module Positions`
Go to site modules and ensure - confirm - that there is no mod_footer configured or enabled (by default there is not) 

Visit your frontend using ?tp=1

### Expected result

Module position names show

### Actual result

Module position names show
mod_footer is rendered in the bottom right with the Joomla copyright information

<img width="686" alt="Screenshot 2020-06-08 at 16 38 04" src="https://user-images.githubusercontent.com/400092/84051078-863c8580-a9a6-11ea-9d07-18f40e3b557d.png">

### Additional comments

Requesting @joomla/security (hmm team deleted?)

 @SniperSister review, because this could be considered a security issue. Note also that other module positions are populated on the page using tp=1 when they should not be, example the top menu position renders a MENU when none is configured in that place either. 

<img width="478" alt="Screenshot 2020-06-08 at 16 40 22" src="https://user-images.githubusercontent.com/400092/84051269-ca2f8a80-a9a6-11ea-8049-6bed6ce4d2cd.png">

**Comment by brianteeman** [comment]
Why should those modules not be populated? This is exactly the same behaviour as with Joomla 1, 2, 3

**Comment by PhilETaylor** [comment]
Because they don’t exist!

There are no modules named “mod_footer” in the position “footer” configured on the site when you go to “Site Modules”

**Comment by SharkyKZ** [comment]
This is related to https://github.com/joomla/joomla-cms/issues/25239.

**Comment by SharkyKZ** [comment]
>Note also that other module positions are populated on the page using tp=1 when they should not be

They should be. That's the whole point of module position preview.

**Comment by ReLater** [comment]
> They should be. That's the whole point of module position preview.

I don't think that module CONTENT of a not existing module should be rendered. In this case mod_footer is rendered even if it's not existing under Modules. Other positions without applied modules only display the black labels but not the CONTENT of something.

**Comment by SharkyKZ** [comment]
OK, I misunderstood the issue. If no modules are assigned to a position, we try to load a module based on position name (`mod_footer` for `footer` position). The code is here:

https://github.com/joomla/joomla-cms/blob/6aa0e48a99659cff1fe464b13a4a1695512a671e/libraries/src/Helper/ModuleHelper.php#L99-L107

**Comment by PhilETaylor** [comment]
> I misunderstood the issue. If no modules are assigned to a position, we try to load a module based on position name

Thus leaking information on a site with tp=1 enabled.

**Comment by SharkyKZ** [comment]
This is not new in 4.0.

**Comment by PhilETaylor** [comment]
I never said it was new in 4.0 - I’m simply challenging the status quo and asking why it still needs to be here, when you could take this major series change to remove such crap and ancient bugs ... 

No one has yet been able to tell me why it needs to be this scatter gun approach and why we need at least one module loaded in the tp =1 mode (hint, we don’t need this - it can be scrapped if joomla has the guts) 

Currently if I have a mod_custom and a custom module position then the html from that module can be loaded if tp=1 is enabled (and 32% of sites in mySites.guru have this enabled on their first snapshot with our service!!!) 

If you can justify why you need to load a module then I’m all ears?? Else joomla is just dragging stuff into joomla 4 for the sake of it

**Comment by SharkyKZ** [comment]
We do need this to make sure all positions are shown regardless of whether a module is published in any given position. But the code can probably improved.

**Comment by PhilETaylor** [comment]
Fine, if there is a reason then there is a reason.

But you manage to show all the other positions when they have no modules published in them ok without falsely publishing a random name matched module ... so I’m still not convinced.

**Comment by PhilETaylor** [comment]
See the screenshot in the opening comment - the search position has nothing in it but it’s still shown ok

10+ other module positions are shown correctly without pushing a false module published into them

I’m still not seeing why you need to push a module content to the screen just to show a position when the others don’t

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29521.
