### ISSUE TITLE
[4.0b1] Random image folders should be restricted by filesystem plugin

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29490]
### Steps to reproduce the issue

Add a new module of type random image
note that the "Image Folder" is a text field with no instructions or help

### Expected result

You should only be able to select image folders as defined in the filesystem plugin for the new media manager

### Actual result

you can type whatever you like

**Comment by adj9** [comment]
What kind of `form`do you use in the filesystem plugin?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29490">issues.joomla.org/tracker/joomla-cms/29490</a>.</sub>
