### ISSUE TITLE
[4.0b1] uploading disallowed media gives generic error message

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29498]
### Steps to reproduce the issue

from a default install of Joomla 4 try to upload a PHP or zip file in media manager in admin

### Expected result

A specific message saying this file type is not allowed. 

### Actual result

Generic unhelpful message
<img width="206" alt="Screenshot 2020-06-08 at 17 34 35" src="https://user-images.githubusercontent.com/400092/84056594-54c7b800-a9ae-11ea-8238-ab29e787a05e.png">

The Ajax call returns no message 

```
{"success":false,"message":"","messages":null,"data":null}
```

**Comment by ghost** [comment]
Issue confirmed (upload a php-File).

**Comment by Quy** [comment]
Closing as duplicate of #33702.
