### ISSUE TITLE
[4.0b1] Notice: Undefined property: stdClass::$image_intro_caption

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29507]
### Steps to reproduce the issue

Install Joomla 4.0.0b1 and then install the "Testing Sample Data" from the "Home Dashboard"
Go to the frontend, "Australian Parks" menu -> Image Gallery -> Scenery

### Expected result

No PHP Notices

### Actual result

```
Notice: Undefined property: stdClass::$image_intro_caption
```

<img width="657" alt="Screenshot 2020-06-08 at 19 21 56" src="https://user-images.githubusercontent.com/400092/84066339-aa579100-a9bd-11ea-8d89-2a038a47a41b.png">

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/issues/29427

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29513.
