### ISSUE TITLE
[4.0b1] Language Switcher tutorial link in testing data leads to 404

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29506]
### Steps to reproduce the issue

Install Joomla 4.0.0b1 and then install the "Testing Sample Data" from the "Home Dashboard"
Go to the frontend, and click Language Switcher in left menu
follow link to `the instructions in this tutorial`

### Expected result

Links to a tutorial on how to use Language Switcher

### Actual result

link Is to https://docs.joomla.org/Language_Switcher_Tutorial which is a 404

**Comment by brianteeman** [comment]
All the testing data is out of date. It is not shipped with Joomla. There is already an open issue for it #25777 

Please close

**Comment by PhilETaylor** [comment]
I give up - again...
