### ISSUE TITLE
[4.0b1] Add A Note totally out of Joomla character 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29509]
### Steps to reproduce the issue

Im sure I have mentioned this before but here we are.

The "Add a Note" area of the User Manager has always looked wrong and operated like no other part of Joomla admin console. 

Its now a split button with an icon, text and a dropdown menu all in one.

Furthermore when the 2FA plugins are enabled it gets smaller and smaller

I know it is subjective. However its totally out of character with everything else 

### Expected result

maybe something as simple as the Permissions icon?
Im no UX/UI Expert
I dont have any answers, I just "find fault in others hard work"

### Actual result

<img width="361" alt="Screenshot 2020-06-08 at 19 35 01" src="https://user-images.githubusercontent.com/400092/84067366-3e762800-a9bf-11ea-9a9a-f09470dfea39.png">

### Bonus

"Add a Note" or "Add A Note" or "Add a note" ?

**Comment by brianteeman** [comment]
as this refers to the same issue as ##33730 and that one has some discussion I suggest this one is closed as a duplicate (yes I know it was created first)

**Comment by PhilETaylor** [comment]
No worries.

**Comment by brianteeman** [comment]
please close
