### ISSUE TITLE
[4.0-dev] Sample content leads to WebAsset PHP errors

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29502]
### Steps to reproduce the issue

Install Joomla 4.0.0 beta 1 and `Testing Sample Data`

Navigate on the frontend to `Sample Sites` in the right hand menus

then `Australian Parks` or `Fruit Shop` in the content 

### Expected result

No PHP errors - anything but a PHP error. 

### Actual result

```
 Argument 1 passed to Joomla\CMS\WebAsset\WebAssetRegistry::addExtensionRegistryFile() must be of the type string, null given, called in /application/libraries/src/Application/SiteApplication.php on line 173
```

<img width="1190" alt="Screenshot 2020-06-08 at 18 45 23" src="https://user-images.githubusercontent.com/400092/84063037-3d8dc800-a9b8-11ea-9506-8a8538d9681a.png">

### System information (as much as possible)

PHP 7.4.6

**Comment by brianteeman** [comment]
All the testing data is out of date. It is not shipped with Joomla. There is already an open issue for it #25777 

Please close

**Comment by PhilETaylor** [comment]
No I will not close this one as this is a PHP error, I'll try and replicate it another way, but ANYWAY Joomla should not be returning a PHP error.

**Comment by mbabker** [comment]
Valid bug regardless of whether a reproducer can be supplied, in this case "just read the code" is the right answer.

https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Application/SiteApplication.php#L173 calls the registry's `addExtensionRegistryFile` method, which expects a string value and does not support null.  Through a series of questionable defaults, it is possible for `$component` to be null, which can trigger this error.  Why `$component` is null in the request at this point (hard to say what point it's at without a stack trace) is concerning though.

**Comment by SharkyKZ** [comment]
The link points to a non-existing menu item. In J3 a  404 with `Component not found` message is thrown.

**Comment by Fedik** [comment]
well, that obviously a broken link `index.php?Itemid=243` 
there should be 404 error,
I will do pull later to handle empty $component while addExtensionRegistryFile()

**Comment by SharkyKZ** [comment]
The call to `addExtensionRegistryFile()` should be wrapped in `$component` check instead. But, realistically, shouldn't the registry file be added when booting the component?

**Comment by Fedik** [comment]
> shouldn't the registry file be added when booting the component?

Need to keep order: 
1 component registry file
2 template registry file

So template can override component assets.

**Comment by Fedik** [comment]
hm, or maybe a good idea.

Split this code to 2 parts: 
`addExtensionRegistryFile($component)` move to component booting
`addTemplateRegistryFile($template->template, $this->getClientId())` move to $app->render() or something

I try to check

**Comment by Quy** [comment]
Please test PR #29530

**Comment by Fedik** [comment]
please test #29530

About my previous comment, about "Split this code to 2 parts":
I just remembered that I made in in this way to allow for plugins to do fancy stuff onBeforeRenderEvent
