### ISSUE TITLE
[4.0b1] Testing data broken image in Australian Parks

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29503]
### Steps to reproduce the issue

Install Joomla 4.0.0b1 and then install the "Testing Sample Data" from the "Home Dashboard"
Go to the frontend, and click `Single Article`  in the  right menu

### Expected result

No broken images

### Actual result

broken missing image

http://127.0.0.1/index.php/images/sampledata/parks/banner_cradle.jpg

<img width="799" alt="Screenshot 2020-06-08 at 19 08 32" src="https://user-images.githubusercontent.com/400092/84064983-79765c80-a9bb-11ea-8695-207372ff7786.png">

**Comment by PhilETaylor** [comment]
More broken images - going to tack on here instead of opening a new issue

Home -> Article Category List ->Extensions


<img width="620" alt="Screenshot 2020-06-08 at 19 11 46" src="https://user-images.githubusercontent.com/400092/84065271-04575700-a9bc-11ea-910b-6c169e0606d1.png">

**Comment by PhilETaylor** [comment]
Testing Data "Image gallery" article missing image too 

<img width="657" alt="Screenshot 2020-06-08 at 19 21 56" src="https://user-images.githubusercontent.com/400092/84066143-62386e80-a9bd-11ea-97a5-68120b01a9db.png">

**Comment by brianteeman** [comment]
All the testing data is out of date. It is not shipped with Joomla. There is already an open issue for it #25777 

Please close

**Comment by PhilETaylor** [comment]
I give up
