### ISSUE TITLE
[4.0b1] Login form in testing data not working 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29505]
### Steps to reproduce the issue

Install Joomla 4.0.0b1 and then install the "Testing Sample Data" from the "Home Dashboard"
Go to the frontend, and click Login Form menu item in the right menu

### Expected result

The login form (which is working at http://127.0.0.1/index.php/login) 

### Actual result

http://127.0.0.1/index.php/login-form

<img width="1249" alt="Screenshot 2020-06-08 at 19 15 02" src="https://user-images.githubusercontent.com/400092/84065547-7334b000-a9bc-11ea-8e91-b6b2518dd300.png">

Note in menu manger it thinks its a tag

<img width="336" alt="Screenshot 2020-06-08 at 19 16 17" src="https://user-images.githubusercontent.com/400092/84065626-92334200-a9bc-11ea-859f-118699d21ee2.png">

but when clicked is clearly com_users

<img width="777" alt="Screenshot 2020-06-08 at 19 16 41" src="https://user-images.githubusercontent.com/400092/84065665-9fe8c780-a9bc-11ea-9e63-30fd1d72f9f0.png">

**Comment by brianteeman** [comment]
All the testing data is out of date. It is not shipped with Joomla. There is already an open issue for it #25777 

Please close
