### ISSUE TITLE
[4.0b1] Article Category List in Cassiopeia template not styled

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29504]
### Steps to reproduce the issue

Install Joomla 4.0.0b1 and then install the "Testing Sample Data" from the "Home Dashboard"
Go to the frontend, and click Article Category List

### Expected result

Filters, 10 and Filter button nicely aligned

### Actual result

<img width="665" alt="Screenshot 2020-06-08 at 19 09 43" src="https://user-images.githubusercontent.com/400092/84065147-c22e1580-a9bb-11ea-93d5-3ebe6882a257.png">

### System information (as much as possible)

safari on Mac

**Comment by ghost** [comment]
Issue confirmed.

![Screen Shot 2020-09-21 at 12 20 43](https://user-images.githubusercontent.com/70466955/93756180-f3e28980-fc04-11ea-92d7-c1956d282711.png)

**Comment by infograf768** [comment]
@hans2103 
;)

**Comment by hans2103** [comment]
created PR https://github.com/joomla/joomla-cms/pull/30761 to solve this issue

**Comment by alikon** [comment]
closing as we have a pr
