### ISSUE TITLE
[4.0b1] Testing data broken image in Fruit Encyclopedia

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29501]
### Steps to reproduce the issue

Install Joomla 4.0.0b1 and then install the "Testing Sample Data" from the "Home Dashboard"
Go to the frontend, and click `Fruit Encyclopedia` in the top right menu

### Expected result

No broken images

### Actual result

Broken image with url:

`http://127.0.0.1/index.php/images/sampledata/fruitshop/apple.jpg`

<img width="856" alt="Screenshot 2020-06-08 at 18 32 59" src="https://user-images.githubusercontent.com/400092/84061827-7fb60a00-a9b6-11ea-910b-2512642118f6.png">

note `Fruit Encyclopedia` is a menu type of `List All Contact Categories`

**Comment by brianteeman** [comment]
All the testing data is out of date. It is not shipped with Joomla. There is already an open issue for it #25777 

Please close

**Comment by PhilETaylor** [comment]
Quotes from  #25777

> Are these now all fixed?
> no one seems remotely interested in it

This issue is NOT listed in #25777

What the hell is the point of the testing data if one cannot test Joomla with it....
