### ISSUE TITLE
[4.0b1] left admin menu items dont stay highlighted which options is selected consistently 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29512]
### Steps to reproduce the issue

Easy steps to replicate
Login to admin 
Go to Components -> Smart Search -> index
Click Options

**NOTE THE LEFT MENU HAS COLLAPSED**

ok lets ignore that, click Save and Close 

**NOTE THE LEFT MENU HAS OPENED TO Index AS WE WOULD EXPECT**

Click Options again

**NOTE THE LEFT MENU HAS COLLAPSED - ah well, we knew it was going to do that**

Click Close

**NOTE THE LEFT MENU HAS COLLAPSED - was not expecting that**

Click Options again

**NOTE THE LEFT MENU STILL COLLAPSED**

click Save and Close 

**NOTE THE LEFT MENU STILL COLLAPSED**

### Expected 

That the left menu would stay open and highlighting something relevant at all times. 

or at least that CLOSE and Save and Close buttons were consistent in what happened to the left menu

**Comment by PhocaCz** [comment]
Hi, can you please specify what do you mean with:

- "left menu" (if the left left menu or the left right menu :-) ):

![left menu](https://i.imgur.com/daQqypl.png)



- and "menu collapsed"

horizontally?

![h](https://i.imgur.com/HCvNUU7.png)

![h](https://i.imgur.com/a36PsDJ.png)

or vertically?

![v](https://i.imgur.com/Tb4MMii.png)

![v](https://i.imgur.com/TYYGgO1.png)


I am asking, because working in Joomla! 4 is very cumbersome, because the left menu is missing active items (when you are in the active component, its menu items are collapsed). So for now I am not sure, if this is the same problem I have or any other problem (e.g. problem with horizontal collapsing which I don't have)

What I mean is closed menu for active component:

![no menu for active component](https://i.imgur.com/2zDJYoc.png)

vs. Joomla! 3
![menu for active component](https://i.imgur.com/zHuC5ue.png)
where everything works like expected and you are always able to switch between items in active component easily and quickly.

Thank you, Jan

**Comment by PhilETaylor** [comment]
> I am asking, because working in Joomla! 4 is very cumbersome, because the left menu is missing active items (when you are in the active component, its menu items are collapsed)

This.

**Comment by PhocaCz** [comment]
> This.

Ok, so I can confirm this issue :-)

**Comment by Quy** [comment]
> the left menu is missing active items (when you are in the active component, its menu items are collapsed)

I am not experiencing this issue. Which browser/OS?

![29512](https://user-images.githubusercontent.com/368084/85332858-8603b600-b48d-11ea-8028-ed25465d88ba.png)

**Comment by PhilETaylor** [comment]
Did you follow the instructions in my opening post?

**Comment by Quy** [comment]
Yes I can reproduce per your test instructions. 

Sorry my reply was to @PhocaCz where submenu items collapse upon selection and not going to Options.

**Comment by PhilETaylor** [comment]
here is a quick example of a broken left menu 

Both these are the same page
https://joomla4beta1.myjoomla.io/administrator/index.php?option=com_associations&view=associations
https://joomla4beta1.myjoomla.io/administrator/index.php?option=com_associations

One will show a selected left menu, the other will not. 

Both are be replicated using the Options -> Save and Close and Options -> Close buttons as per my opening comment.

**Comment by PhilETaylor** [comment]
Here is another example (Sorry @nikosdion) 

Install Akeeba Backup for Joomla 4

Go to Components -> Akeeba Backup 

Click Manage Backups or Configuration or Profiles Management or View Log 

Note that the left side menu collapses instead of staying at "Components -> Akeeba Backup"

**Comment by nikosdion** [comment]
Not my monkey, not my problem. Please don’t at mention me on issues unrelated to my code, especially ones I’ve reported a month prior.

**Comment by PhocaCz** [comment]
> Sorry my reply was to @PhocaCz where submenu items collapse upon selection and not going to Options.

Hi, see what I mean:
![Collapsed Menu](https://i.imgur.com/KSvg5VK.gif)


The menu items of active component are hidden (collapsed) when the component is active.

Windows 8/10, Firefox, Chrome, Opera, Brave

**Comment by Quy** [comment]
@PhocaCz Are you testing with the nightly build? https://developer.joomla.org/nightly-builds.html

I cannot reproduce the issue. Do you get the grey background when `System` is active?

![29512-system](https://user-images.githubusercontent.com/368084/85423917-23adc280-b52c-11ea-9b19-9e7edbfb240d.png)

**Comment by PhocaCz** [comment]
> I cannot reproduce the issue. Do you get the grey background when `System` is active?

No.

![system](https://i.imgur.com/vBtjwR3.png)

Today updated, the same problem - testing the 4.0-dev branch per composer/npm (2020/06/24)

Installed the NB release (24 June 2020 02:00:20 UTC), the same, no grey background.

**Comment by brianteeman** [comment]
I cant reproduce that with the system menu either. What is the exact url you are on? What browser etc?

**Comment by PhocaCz** [comment]
Hi, 

URL:
administrator/index.php?option=com_cpanel&view=cpanel&dashboard=system

Windows 8, Windows 10, Suse Linux: Chrome, Firefox, Avast, Brave, Opera browsers

**Comment by infograf768** [comment]
can't reproduce issue : Macintosh, Firefox, Safari, Chrome.

**Comment by PhilETaylor** [comment]
Please, when people are saying they `can't reproduce issue` please be specific. 

To be clear: The issue reported, to open this GitHub issue, **can be replicated in all browsers**.

To be clear: The issue reported by @PhocaCz cannot be reproduced by any of us testing.

**Comment by infograf768** [comment]
Right.
Can't reproduce  @PhocaCz issue.

**Comment by PhocaCz** [comment]
Hmmm, I am testing latest development branch, latest nightly build, can someone paste a screenshot how it looks when the menu is not collapsed.

E.g. on Contacts view:

administrator/index.php?option=com_contact&view=contacts

![menu not collapsed](https://i.imgur.com/mKgLmpP.png)

Sorry @PhilETaylor - I would like to test your reported issue step by step but seems I am not able to do as it looks like my Joomla! 4 is somehow completely different to standard  :-)

**Comment by infograf768** [comment]
<img width="803" alt="Screen Shot 2020-06-25 at 12 34 22" src="https://user-images.githubusercontent.com/869724/85704046-3ec13380-b6e0-11ea-8b79-a2b9fe66e531.png">

**Comment by PhocaCz** [comment]
Great, thank you @infograf768 ... now I need to find what is wrong with my Joomla! 4

1) First instance: Downloaded https://developer.joomla.org/nightly-builds.html - installed standardly
2) Second instance: download 4.0-dev branch - composer install --ignore-platform-reqs - npm ci

both the same result :-(

**Comment by PhilETaylor** [comment]
@PhocaCz Funnily enough I had the same problem as you today. The problem where nothing in the left menu highlighted on a Joomla 4 beta 1 site locally.  I debugged it for ages. It was only affecting safari at the time, google chrome was fine. 

The "fix" for me on this site on this occasion was to open the Dev Inspector tools in safari -> Sources Tab and then to select template.min.css - it took a few seconds to load the source, but after it did, I refreshed the page and then menu highlighting (your issue, not the reason this GitHub issue is open) was resolved. 

Im going to assume there is some aggressive caching in the browser - despite me disabling caching and flushing the cache several times!

**Comment by PhocaCz** [comment]
@PhilETaylor Testing now, still the same problem, I usually use Chrome DevTools with disabled cache:

![chrome cache](https://i.imgur.com/VpedqcB.png)

I feel like Alice in Wonderland :-), I have tested 3 different ways how to install Joomla! 4 (download, git clone, nightly build), cleaned cache in browser, in DevTools, cleaned sessions in database, enabled debug mode (to get not minified versions of CSS and JS), etc. etc. Still the same problem. :-(

**Comment by Quy** [comment]
@PhocaCz Please confirm if this is the issue in your case in #30155.

**Comment by PhocaCz** [comment]
> @PhocaCz Please confirm if this is the issue in your case in #30155.

Hi, thank you very much for this info, yes, I can confirm it, the uppercase is the problem, more info in #30155 

Thank you, Jan

**Comment by Quy** [comment]
Please test PR #32330. Thanks.
