### ISSUE TITLE
[4.0-dev] Search Menu item leads to generic 500

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29510]
### Steps to reproduce the issue

install Joomla 4
Add menu item to Smart Search with all default config
visit menu item on frontend

### Expected result

A search page

### Actual result

`500`

<img width="870" alt="Screenshot 2020-06-08 at 20 01 08" src="https://user-images.githubusercontent.com/400092/84069675-cf023780-a9c2-11ea-9ed6-96160066adb5.png">

### Additional comments

Enabling development error reporting and debugging I get stack trace

<img width="988" alt="Screenshot 2020-06-08 at 20 01 40" src="https://user-images.githubusercontent.com/400092/84069725-e5a88e80-a9c2-11ea-8613-145c4422f375.png">

which leads to /components/com_finder/src/View/Search/HtmlView.php line 146

```
// Check for errors.
		if (count($errors = $this->get('Errors')))
		{
			throw new GenericDataException(implode("\n", $errors), 500);
		}
```

Those errors are never handled and shown to the screen but `var_dump($errors);` gives:

```

Warning: mysqli_stmt::bind_param(): Number of variables doesn't match number of parameters in prepared statement in /application/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php on line 420

Warning: mysqli_stmt::bind_param(): Number of variables doesn't match number of parameters in prepared statement in /application/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php on line 420

Warning: mysqli_stmt::bind_param(): Number of variables doesn't match number of parameters in prepared statement in /application/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php on line 420
array(3) { [0]=> string(0) "" [1]=> string(0) "" [2]=> string(0) "" }
```

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29428.

**Comment by PhilETaylor** [comment]
confirmed that #29428 allows the search page to load... however ;-) incoming bug ....
