### ISSUE TITLE
JFolder: :delete: when error reporting totally OFF

### ISSUE THREAD

**Issue by imanagerseo0** [joomla/joomla-cms#29516]
### Steps to reproduce the issue

**JFolder: :delete: Не удалось удалить каталог: /home/..../public_html/media/nextend/cache/image/n1591634700
JFolder: :delete:  cant remove catalog /home/..../public_html/media/nextend/cache/image/n1591634700**

Joomla 3.9.19

**Comment by imanagerseo0** [comment]
totally error reporting is OFF
why this error ones ?

LITESPEED php 7.3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29516">issues.joomla.org/tracker/joomla-cms/29516</a>.</sub>

**Comment by alikon** [comment]
if you don't explain how to reproduce step by step it's hard to have an answer

**Comment by SharkyKZ** [comment]
Error reporting affects only PHP errors, not Joomla API errors.

**Comment by SharkyKZ** [comment]
It's a log message being outputted:

https://github.com/joomla/joomla-cms/blob/6aa0e48a99659cff1fe464b13a4a1695512a671e/libraries/src/Filesystem/Folder.php#L391

Maybe it shouldn't be displayed. See similar https://github.com/joomla/joomla-cms/issues/20689 discussion.

**Comment by brianteeman** [comment]
This year old issue has been asked and answered. There is nothing to do here and no reason to keep it open
