### ISSUE TITLE
[3.9][4.0] Joomla Installer - localhost:3308 not accepted as database host on local server

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#29519]
### Steps to reproduce the issue
Install Joomla 3.9 or 4.0-beta on localhost system where MariaDB is the default DBMS but use MySQL, which has been assigned port 3308.

### Expected result
localhost:3308 should be accepted as a local database server

### Actual result
Warning
You are trying to use a database host which is not on your local server. For security reasons, you need to verify the ownership of your web hosting account. Please read the documentation for more information.

Error
To confirm that you are the owner of this website please delete the file named "_JoomlaNkFQ7jQhIjmbUIXD3h1SL.txt" we have created in the "installation" folder of your Joomla site.

### System information (as much as possible)
3.9.20-dev Nightly Build of 9 June
4.0.0-beta2-dev Nightly Build of 9 June  ‎4.0.0-beta2-dev

Wampserver 3.2.2  MySQL 8.0.19  MariaDB 10.4.10  PHP 7.4.5

### Additional comments
The warning and error are not necessary in localhost environment.  Those messages can confuse new users:
![screen shot 2020-06-09 at 06 11 42](https://issues.joomla.org/uploads/1/0556a4e8df5a65eafbb7ef306ada0190.jpg)

**Comment by richard67** [comment]
@zero-24 Our localhost check only checks if in the list "localhost", "127.0.0.1", "::1", it doesn't check for such stuff with ports. I could change the check to use a regex, something like
`^(localhost|127\.0\.0\.1|\:\:1)(\:[0-9]+)?$`,
and allow optional colon with a number behind it. Could be done in J3 and J4. Shall I do that? Beginning on Thursday I would have time for that. I ping you for your opinion because as I remember, that localhost check came from you once. If you say "won't fix" I'll keep my hands in my pockets.

**Comment by zero-24** [comment]
Go for it @richard67

**Comment by richard67** [comment]
Will do later today or tomorrow or so.

**Comment by richard67** [comment]
I just see my regex is not ok for IPv6 with ports, because it needs square brackets around the address part when having a port but no square brackets without a port, as far as I know up to now. I'll have to tune that a bit.

**Comment by richard67** [comment]
I just see it is not that easy. Unlike a web browser, where the port is a part of the URL, it works differently with the database clients, see e.g here for MySQLi: [https://www.php.net/manual/de/mysqli.construct.php](https://www.php.net/manual/de/mysqli.construct.php).

I.e. host and port are different parameters, and I have to check if our database drivers support ports. If not, there might be more to do.

**Comment by richard67** [comment]
Closing as having Pull Requests.

Please test #29567 for Joomla 3.9 (staging) and #29568 for Joomla 4.
