### ISSUE TITLE
[4.0] Notices from property of non-object by front end contact.php

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#29518]
### Steps to reproduce the issue
Articles - Options:  select 'Link to Author's Contact Page'.  
Do not set the author as a contact.
View articles of the author from the front end.

### Expected result
No PHP notices.

### Actual result
Notice: Trying to get property 'contactid' of non-object in C:\www\joomla4\plugins\content\contact\contact.php on line 73
Notice: Trying to get property 'webpage' of non-object in C:\www\joomla4\plugins\content\contact\contact.php on line 74
Notice: Trying to get property 'email_to' of non-object in C:\www\joomla4\plugins\content\contact\contact.php on line 75

### System information (as much as possible)
Wampserver 3.2.2  PHP 7.4.5  Beta2-dev Nightly Build of 9 June

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29520.
