### ISSUE TITLE
[4.0b1] Search for :":":@£4@£$asd produces PHP Notices

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29511]
### Steps to reproduce the issue

checkout 4.0-dev
apply #29428 so that you can actually use com_finder (Bug not fixed in, or broken by that PR, it exists before and after that PR, but you need that PR to actually GET TO the search page at the moment) 
Create a new menu item pointing to smart search 
visit that menu item on the frontend
search for 

```
:":":@£4@£$asd
```

### Expected result

No results. No PHP Notices

### Actual result

PHP Notices repeated/

```
Notice
: Trying to get property 'phrase' of non-object in
/application/administrator/components/com_finder/src/Indexer/Query.php
on line
1329
Notice
: Trying to get property 'term' of non-object in
/application/administrator/components/com_finder/src/Indexer/Query.php
on line
1338
Notice
: Trying to get property 'stem' of non-object in
/application/administrator/components/com_finder/src/Indexer/Query.php
on line
1338
```

<img width="776" alt="Screenshot 2020-06-08 at 20 13 52" src="https://user-images.githubusercontent.com/400092/84070786-97948a80-a9c4-11ea-9b81-70cad56a13bb.png">

### System information (as much as possible)

`Mysqli` driver

**Comment by PhilETaylor** [comment]
I have managed to reduce the search string needed to replicate this down to 

```
":"
```

using just that will replicate this problem

**Comment by Fedik** [comment]
I suspect it something with value filtering, in the end (after filtering) it doing search for empty string.
But not tested.

**Comment by Quy** [comment]
Please test PR #30010
