### ISSUE TITLE
Select Articles Menu Item Type in Control Panel Menus Screen

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#29526]
### Steps to reproduce the issue

Sign in to Joomla! 4 Beta 1 for Testing Control Panel.

Select Menus.

Select a Menu.

Select NEW menu Item.

Select ARTICLES type.

### Expected result

List of ARTICLE menu item types (Single Article is at bottom of listed options)

### Actual result

List of ARTICLE menu item types (Single Article is at bottom of listed options)

### Additional comments

Request that SINGLE ARTICLE menu item type be at TOP of listed options.

Reason: this is the most common type of Menu Link that I create.

If this is the same fpr most users then it would make sense for it to be at the top.

Benefit: smoother faster workflow.

**Comment by SharkyKZ** [comment]
Duplicate issue https://github.com/joomla/joomla-cms/issues/27476.
