### ISSUE TITLE
[4.0] Mass email uses email as Name and Email when sending messages.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29538]
### Steps to reproduce the issue

Send a mass email, view the headers 

### Expected result

`To: "myTest Users Name" <test@phil-taylor.com>`

### Actual result

`To: "test@phil-taylor.com" <test@phil-taylor.com>`

<img width="396" alt="Screenshot 2020-06-09 at 20 07 51" src="https://user-images.githubusercontent.com/400092/84189273-ed346a00-aa8c-11ea-832b-eda850d22a5d.png">

### System information (as much as possible)

Using SMTP mail caught by Mailhog.

**Comment by SharkyKZ** [comment]
Should this be changed on J3 or J4 only?

**Comment by PhilETaylor** [comment]
I dont make those decisions. I was asked to test Joomla 4 beta 1 and that's the version I tested and reported against :-)

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29769.
