### ISSUE TITLE
[3/4] Mass Mail doesn't clear session on close

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29535]
### Steps to reproduce the issue

Joomla 3 or Joomla 4 - both do this

Go to Admin -> Users -> Mass Mail Users

Compose an email 

Select a group that has no users in it

Click Send email - note correct error message saying group has no users

Give up and click Cancel, can't be arsed to email anyone anyway... 

Do something else for a while, Grab a coffee, edit some content, look out the window...

Go to Admin -> Users -> Mass Mail Users

### Expected result

Blank form ready for some new mail I want to compose.

### Actual result

The contents of the last form submission (The composed email) which failed to send some time ago.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29539.
