### ISSUE TITLE
[4.0] incrementing id reveals blank form instead of 404 not found

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29532]
### Steps to reproduce the issue

Might exist in Joomla 3, only tested in Joomla 4

fake urls to `com_messages`

http://127.0.0.1/administrator/index.php?option=com_messages&view=message&message_id=1

increment the message_id to numbers that dont exists

### Expected result

404 Not found or some kind of error message

### Actual result

Blank form:

<img width="1576" alt="Screenshot 2020-06-09 at 19 06 12" src="https://user-images.githubusercontent.com/400092/84183768-51066500-aa84-11ea-941c-3d8f30f264dc.png">

**Comment by Quy** [comment]
Please test PR #30112 for J3 that will be ported to J4. Thanks.
