### ISSUE TITLE
[4.0] Private message subject is not put in email subject line

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29533]
### Steps to reproduce the issue

Send a private message to another Joomla 4 super admin 

<img width="582" alt="Screenshot 2020-06-09 at 19 07 34" src="https://user-images.githubusercontent.com/400092/84184044-9fb3ff00-aa84-11ea-8930-a8e3b5973da4.png">

Look at the email received. 

### Expected result

Expected that the subject typed would appear in the subject of the email notification

### Actual result

Email has a subject of:  `New Message from admin at Test`

Raw message source 

```
Content-Type: text/plain; charset=utf-8
Date: Tue, 9 Jun 2020 18:07:38 +0000
From: Test <phil@phil-taylor.com>
MIME-Version: 1.0
Message-ID: <WeV6UARGsy8Yw86rG0kvDxbPaO8hoalql0OiDMRHf4@localhost.localdomain>
Received: from localhost.localdomain by mailhog.example (MailHog)
          id 32qc9H2sSudK-uPuNWmjwvpirpFTTsgjYoLBuLM30Hk=@mailhog.example; Tue, 09 Jun 2020 18:07:38 +0000
Reply-To: admin <phil@phil-taylor.com>
Return-Path: <phil@phil-taylor.com>
Subject: New Message from admin at Test
To: test <test@phil-taylor.com>

This is my subject 

This is my message

Please log in to http://127.0.0.1/administrator/index.php?option=com_messages&view=message&message_id=2 to read your message.

```

The help screen for this page simply says

> Subject. The subject of the message. Just like the subject of an email, it helps if this is a short description of the message body.

which doesn't make it clear if the subject will be mapped to the email subject or not. 

This might be a `won't fix` but nethertheless confusing ...

**Comment by infograf768** [comment]
@PhilETaylor 
Code is
```
$subj	  = sprintf($lang->_('COM_MESSAGES_NEW_MESSAGE'), $fromName, $sitename);
$msg 	  = $subject . "\n\n" . $message . "\n\n" . sprintf($lang->_('COM_MESSAGES_PLEASE_LOGIN'), $siteURL);

```
I guess we could do
```
$subj	  = sprintf($lang->_('COM_MESSAGES_NEW_MESSAGE'), $fromName, $sitename) . ' - ' . $subject;
$msg 	  = $message . "\n\n" . sprintf($lang->_('COM_MESSAGES_PLEASE_LOGIN'), $siteURL);
```

This would give:
![Message-2020-06-10-at-11 58 01](https://user-images.githubusercontent.com/869724/84255018-55795f00-ab12-11ea-8086-49485f0a8631.png)


What do you think?

**Comment by PhilETaylor** [comment]
Personally, I dont see a need for the string COM_MESSAGES_NEW_MESSAGE as you 

1) know its a new message....
2) You know who its from - as they name/email is in the from
3) You know which site it is, because you get a URL to the site

also the "Please login in to...." is also redundant, because you dont need to "log in to read your message" as WE JUST SENT YOU THE WHOLE MESSAGE above that link....

**Comment by brianteeman** [comment]
Most of that is just legacy stuff from before the PR that made com_messages useful

**Comment by infograf768** [comment]
`New` is indeed useless.

`You know who its from - as they name/email is in the from`

One would not know who exactly send you the message, in my case above "otheradmin". The site email may not reflect the site name.

`You know which site it is, because you get a URL to the site`
The url to the site does not use the name of the site, therefore it may be useful to display it.

`also the "Please login in to...." is also redundant, because you dont need to "log in to read your message" as WE JUST SENT YOU THE WHOLE MESSAGE above that link....`

Indeed, it should not be `to read`, but rather ` to access` (or similar) as the user may need to change the status of the message to `Read` or just trash it.

**Comment by brianteeman** [comment]
> Personally, I dont see a need for the string COM_MESSAGES_NEW_MESSAGE as you
> 
> 1. know its a new message....
> 2. You know who its from - as they name/email is in the from
> 3. You know which site it is, because you get a URL to the site
> 
> also the "Please login in to...." is also redundant, because you dont need to "log in to read your message" as WE JUST SENT YOU THE WHOLE MESSAGE above that link....

There have been some changes since this issue was first raised as the message no longer contains the legacy line "please log in to.." great -

I am going to propose a PR to change the title to 
<sitename> - <subject>

This will allow you to filter your incoming mails based on the sitename etc

**Comment by Quy** [comment]
Please test PR #37133. Thanks.
