### ISSUE TITLE
[4.0] 500 error page in admin is missing toggle navigation and has a joomla logo

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29531]
### Steps to reproduce the issue

Generate an error in admin in Joomla 4

How I did it was to send a private message to another super admin, and then click url below when still being signed in as the sending admin

`http://127.0.0.1/administrator/index.php?option=com_messages&view=message&message_id=1`

### Expected result

`403 Forbidden` instead of 500 code message 
Left menu to be exactly the same as normal

### Actual result

Missing toggle navigation
Additional Joomla color logo appeared

<img width="1296" alt="Screenshot 2020-06-09 at 19 03 31" src="https://user-images.githubusercontent.com/400092/84183515-ee14ce00-aa83-11ea-9816-38f8b7f549f3.png">

**Comment by wilsonge** [comment]
Patch in https://github.com/joomla/joomla-cms/pull/29599
