### ISSUE TITLE
[4.0] Argument 1 passed to Joomla\CMS\User\UserFactory::loadUserByUsername() must be of the type string

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29534]
### Steps to reproduce the issue

go to faked url:

http://127.0.0.1/administrator/index.php?option=com_messages&view=message&message_id=

same with 

http://127.0.0.1/administrator/index.php?option=com_messages&view=message&layout=dasdasd

### Expected result

No PHP Error. Something other than a PHP error :) 

### Actual result

Argument 1 passed to Joomla\CMS\User\UserFactory::loadUserByUsername() must be of the type string, null given, called in /application/libraries/src/User/User.php on line 271

<img width="1920" alt="Screenshot 2020-06-09 at 19 13 52" src="https://user-images.githubusercontent.com/400092/84184496-616b0f80-aa85-11ea-82a9-b9a6a1fa75ea.png">

**Comment by alikon** [comment]
confirmed
**`com_messages`** needs a bit of  care

**Comment by PhilETaylor** [comment]
I’ve given it a good shake this week - raised a few issues for it 

Apparently it’s to become a used feature in joomla 4 because of the new workflow features instead of the hardly used feature it currently is in Joomla 3 

It’s probably going to need more work once joomla 4 is released to add more features to it so it’s a real messaging system rather than a very very small feature set.
