### ISSUE TITLE
[4.0] Manager cannot view private messages

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29542]
### Steps to reproduce the issue

Login to Joomla 4 admin console as a user with `manager` group permissions

Note the Private Message icon in the header

Click the Private Message Icon

### Expected result

To see my private messages?

### Actual result

`403 You don't have permission to access this. Please contact a website administrator if this is incorrect.`

<img width="998" alt="Screenshot 2020-06-09 at 20 29 38" src="https://user-images.githubusercontent.com/400092/84191137-f410ac00-aa8f-11ea-92dc-175aef6c654d.png">

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29545.
