### ISSUE TITLE
Celebrate 10,000 Closed Issues (+this one!)

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29546]
### Steps to reproduce the issue

<img width="259" alt="Screenshot 2020-06-09 at 21 04 55" src="https://user-images.githubusercontent.com/400092/84194432-ef022b80-aa94-11ea-8349-4cdc1edf557a.png">

### Expected result

PARTY!

**Comment by alikon** [comment]
ok let'close it
