### ISSUE TITLE
[4.0] Cancel button should be a close button & vice-versa?

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29544]
### Steps to reproduce the issue

Read a private message in Joomla admin 

### Expected result

Reply | Close 

Because you close a screen, but you cancel an action. There is no action to be taken on this page, so it should be simply a close. 

### Actual result

Reply | Cancel 

<img width="330" alt="Screenshot 2020-06-09 at 20 42 09" src="https://user-images.githubusercontent.com/400092/84192321-b876e180-aa91-11ea-87dd-83ba36c2b8ac.png">

### BONUS

The opposite bug is true on the private message COMPOSE page where there is a Close button. 

This is an action page, so the button should be a Cancel and not a close. 

<img width="475" alt="Screenshot 2020-06-09 at 20 43 04" src="https://user-images.githubusercontent.com/400092/84192444-e6f4bc80-aa91-11ea-8805-cd19d303519d.png">

**Comment by PhilETaylor** [comment]
Hmmm... maybe subjective here, as Editing content has a close button, when ME PERSONALLY would say that also should be a cancel button. Feel free to just close this if you think that Im wrong. I'll not be offended. But a decision on close/cancel should be made and universally applied one way or the other. 

You can't "close" an action page, you "cancel" out of an action page is my view on this. 

You can "close" something that you are just reading.. 

For example, Banners - has a cancel on the New page...

<img width="485" alt="Screenshot 2020-06-09 at 20 46 26" src="https://user-images.githubusercontent.com/400092/84192735-566aac00-aa92-11ea-8f18-2658dc860e7a.png">

**Comment by PhilETaylor** [comment]
<img width="477" alt="Screenshot 2020-06-09 at 20 47 46" src="https://user-images.githubusercontent.com/400092/84192856-7ef2a600-aa92-11ea-8972-be948a6e9a37.png">
<img width="496" alt="Screenshot 2020-06-09 at 20 48 12" src="https://user-images.githubusercontent.com/400092/84192885-8b76fe80-aa92-11ea-9e14-9a79a89f2656.png">

**Comment by brianteeman** [comment]
Cancel when its a new item
Close when its an existing item ?

**Comment by PhilETaylor** [comment]
Sounds right

**Comment by brianteeman** [comment]
That should be doable - putting it on my list

**Comment by brianteeman** [comment]
Can be closed see #33317

**Comment by PhilETaylor** [comment]
Thanks https://github.com/joomla/joomla-cms/pull/33317/files
