### ISSUE TITLE
[4.0] Cannot select other users in selector when sending private message

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29541]
### Steps to reproduce the issue

Login as a super admin to a Joomla 4 site that has 1 other super admin and 4 registered users

Use the Private message icon in the header

Click New 

Click to select users

Note you can only see the one other super admin 

Use the filter to select the registered group 

### Expected result

Expect to see registered group users

### Actual result

No matching results.

### However

Reading the "Help" on Private messages, it says you can only send to "other backend users" Meaning then that `super admins` should be able to send to `Manager` Group - so lets select `Manager` group in the filter - and still I dont see any of my manager users. 

So two bugs:

1) the filter has groups in it that you cannot send messages to
2) when filtering by "other backend users" group `managers` you get no list of manager users.

**Comment by brianteeman** [comment]
This whole component needs a rethink. 
Is it ok to be able to receive a message but not to reply to it
What would be a better message in the user selection to be clearer what the "no matching results" refers to
The select user filter should either not be present or should be limited to the groups who have access

**Comment by PhilETaylor** [comment]
Also what if the OtherAdmin has locked their mailbox and cannot (doesn't want to) receive messages...
