### ISSUE TITLE
[4.0] Manager User cannot select users to private message

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29548]
### Steps to reproduce the issue

Configure Joomla 4 permissions to Messaging to ALLOW everything for Manager user eg:

<img width="1628" alt="Screenshot 2020-06-09 at 21 35 48" src="https://user-images.githubusercontent.com/400092/84197136-58843900-aa99-11ea-91e6-059e4c8bdfa6.png">

Login as a manager user
Navigate in the left menu to Private Messaging 
Click New to compose a message

### Expected result

Ability to select a recipient 

### Actual result

No ability to select a recipient 

<img width="843" alt="Screenshot 2020-06-09 at 21 37 42" src="https://user-images.githubusercontent.com/400092/84197216-781b6180-aa99-11ea-9637-67acd3b5cf35.png">

**Comment by PhilETaylor** [comment]
So what #29545 teaches is that, not being able to select users is the correct thing here, however it makes no sense that a user with access to com_messages but no access to com_users should even be able to get to this screen at all. 

Therefore the solution to this issue is for an ACL check to be made on this page, to block writing of a message and a ACL check on send to check to prevent #29558 but at the same time allowing the viewing of messages (because that's what allowing com_messages and denying com_users allows users to do, just read, not send)

**Comment by Quy** [comment]
Please test PR #37134. Thanks.
