### ISSUE TITLE
[4.0] Filter options in private messaging layout 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29549]
### Steps to reproduce the issue

Click filter options in private messaging in admin 

### Actual result

Note the uber wide dropdown for a tiny field content

<img width="1650" alt="Screenshot 2020-06-09 at 21 44 37" src="https://user-images.githubusercontent.com/400092/84197856-87e77580-aa9a-11ea-8634-a73b56205da5.png">

**Comment by PixedBo** [comment]
in class `.js-stools-container-filters-visible` (searchtools css) I would use

`grid-template-columns: repeat(auto-fill,minmax(220px,1fr));`
instead of
`grid-template-columns: repeat(auto-fit,minmax(220px,1fr));`

that would fix the problem

**Comment by Quy** [comment]
Please test PR #29777
