### ISSUE TITLE
[4.0] Send icon has a save icon in private messages

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29540]
### Steps to reproduce the issue

login to Joomla 4 admin as a super admin and go to send a private message on page

http://127.0.0.1/administrator/index.php?option=com_messages&view=message&layout=edit

### Expected result

Envelope icon like on the mass mail page for the Send button

<img width="397" alt="Screenshot 2020-06-09 at 20 22 00" src="https://user-images.githubusercontent.com/400092/84190463-e4dd2e80-aa8e-11ea-9ccc-b3322f718bf2.png">

### Actual result

Floppy disk icon

<img width="203" alt="Screenshot 2020-06-09 at 20 21 46" src="https://user-images.githubusercontent.com/400092/84190439-dabb3000-aa8e-11ea-8c15-dc02b5a7cb3b.png">

**Comment by brianteeman** [comment]
Please see #29716
