### ISSUE TITLE
[4.0] HTML Private message is badly rendered when on read page

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29543]
### Steps to reproduce the issue

Send another admin a private message taking full advantage of the WYSIWYG Editor to make a really nice and beautiful message with lots of formatting and line breaks and multi line message

Login as that other admin and read the message

### Expected result

Unicorns and flowers erupt from your brain as you read the perfectly composed message that is rendered beautifully on the page

### Actual result

Brutal.

<img width="1309" alt="Screenshot 2020-06-09 at 20 38 43" src="https://user-images.githubusercontent.com/400092/84192123-7352af80-aa91-11ea-9c28-5d9345de9c69.png">

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29574.
