### ISSUE TITLE
[4.0] COM_WORKFLOW_BASIC_WORKFLOW/COM_WORKFLOW_BASIC_STAGE

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29547]
### Steps to reproduce the issue

untranslated strings found when viewing the permissions of a user group

COM_WORKFLOW_BASIC_WORKFLOW
COM_WORKFLOW_BASIC_STAGE

on url http://127.0.0.1/administrator/index.php?option=com_users&view=debuggroup&group_id=6

<img width="817" alt="Screenshot 2020-06-09 at 21 30 04" src="https://user-images.githubusercontent.com/400092/84196641-684f4d80-aa98-11ea-8857-22ee471b327a.png">

**Comment by brianteeman** [comment]
Not saying it is correct but the reason that you see what appear to be untranslated strings is that those strings are the actual asset title. 

![image](https://user-images.githubusercontent.com/1296369/84198125-ffb5a000-aa9a-11ea-8df1-8927fd4d3e32.png)

**Comment by Quy** [comment]
See #23794

**Comment by PhilETaylor** [comment]
Awesome

**Comment by brianteeman** [comment]
Should not have been closed as #23794 was outdated. I have created a new updated PR to address that.

**Comment by PhilETaylor** [comment]
ok reopening (and then going to bed)

**Comment by brianteeman** [comment]
Reading when its late saves you time. There is a PR now
