### ISSUE TITLE
[4.0] Colors for status of article on frontend 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29551]
### Steps to reproduce the issue

Login to frontend and edit article
Go to the publishing tag
select different publishing states

### Expected result

Published = Green
Unpublished = kind of red
Archived = grey maybe? No idea! But was not expecting white.
Trashed = black maybe? No idea! But not the same kind of red as unpublished

### Actual result

Published = Green
Unpublished = kind of red
Archived = no color
Trashed = same kind of red as Unpublished

![Screen Recording 2020-06-09 at 10 06 PM](https://user-images.githubusercontent.com/400092/84199818-b4e95780-aa9d-11ea-805e-19bef1b60226.gif)

### System information (as much as possible)

safari on Mac

**Comment by brianteeman** [comment]
Exactly the same as in the admin

**Comment by brianteeman** [comment]
I am guessing this was resolved with the last repaint

Frontend
![image](https://user-images.githubusercontent.com/1296369/115999909-cc61fe00-a5e5-11eb-9031-4fad6a0ac97b.png)

Admin
![image](https://user-images.githubusercontent.com/1296369/115999920-dc79dd80-a5e5-11eb-87f1-01cdeb117e2f.png)

**Comment by PhilETaylor** [comment]
yup
