### ISSUE TITLE
[4.0b] TinyMCE stripping away onclick attribute

### ISSUE THREAD

**Issue by regularlabs** [joomla/joomla-cms#29557]
After entering html code in the html view that contains onclick attributes, and then switching to the WYSIWYG view (toggle editor), these attributes are removed.

```
<button class="btn btn-secondary" onclick="console.log('why does this get removed?')">My Button</button>
```
Results in:
```
<button class="btn btn-secondary">My Button</button>
```

This happens as a Super Admin, even though the global Text Filters is set to 'No Filtering'. That seems to have no effect at all.
![image](https://user-images.githubusercontent.com/13553242/84246106-602df700-ab06-11ea-80cc-fba23033e909.png)

In the TinyMCE plugin settings the 'Use Joomla Text Filter' option is switched off.
![image](https://user-images.githubusercontent.com/13553242/84246063-53a99e80-ab06-11ea-88fc-cc120cf2c4f5.png)

**Comment by regularlabs** [comment]
PS: Might be connected to: https://github.com/joomla/joomla-cms/issues/26185

**Comment by Quy** [comment]
In the TinyMCE plugin under Set 0, enable `Use Joomla Text Filter`.

**Comment by regularlabs** [comment]
Wow, would never have found that. Very confusing on multiple levels!

**Comment by AndySDH** [comment]
Yeah, it's really not clear that those are Tabs in the first place, and then when you realize they're Tabs, you still don't understand where they start or end!

**Comment by AndySDH** [comment]
> In the TinyMCE plugin under Set 0, enable `Use Joomla Text Filter`.

I'm surprised you were able to figure it out 😂

**Comment by Quy** [comment]
PR #28721 enables this setting by default on new installs.

**Comment by Quy** [comment]
> Existing sets of the TinyMCE panel, and options for each set.
In each set you can add or remove from the available menus and buttons.

They look like tabs to me. Plus, the description above tabs hinted they are tabs. You can also check out the Help documentation.
