### ISSUE TITLE
[4.0] Fields pages in admin missing icons

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29553]
### Steps to reproduce the issue

In Joomla 4 admin navigate to the Fields and Field Group pages, and their edit pages. 

### Expected result

All pages to do with fields/field groups  have icons in their headers like all other Joomla admin components

### Actual result

http://127.0.0.1/administrator/index.php?option=com_fields&view=fields&context=com_users.user
Missing Icon in header:
<img width="414" alt="Screenshot 2020-06-09 at 22 12 26" src="https://user-images.githubusercontent.com/400092/84200244-5375b880-aa9e-11ea-9c9f-c549bcb2c4f9.png">

The edit state HAS the icon:
<img width="524" alt="Screenshot 2020-06-09 at 22 12 58" src="https://user-images.githubusercontent.com/400092/84200298-67211f00-aa9e-11ea-8e6e-681a90336f7e.png">

Field Groups page has no icon:
<img width="541" alt="Screenshot 2020-06-09 at 22 13 27" src="https://user-images.githubusercontent.com/400092/84200332-799b5880-aa9e-11ea-9250-f14047901b8a.png">

Edit Field Group page has no icon:
<img width="517" alt="Screenshot 2020-06-09 at 22 13 52" src="https://user-images.githubusercontent.com/400092/84200355-8324c080-aa9e-11ea-9294-6808b2d3380c.png">

**Comment by Quy** [comment]
Not producible. Maybe a side-effect of installing/uninstalling #28075 with Patch Tester.

![29553](https://user-images.githubusercontent.com/368084/84200769-1688d200-aa5c-11ea-9e1e-ab37408f9424.png)

**Comment by PhilETaylor** [comment]
Correct. Must be time for bed. 

After reverting the patch the icons appear. 

Therefore isn't this actually a GOOD THING that this was discovered as it means the #28075 breaks the icons?

**Comment by Quy** [comment]
It is fine with #28075. It must be the Patch Tester as I have had issues with installing/uninstalling.

**Comment by PhilETaylor** [comment]
ok cool.

**Comment by PhilETaylor** [comment]
I applied the PR using Towerapp and now I see the icons (much bigger too) 
<img width="400" alt="Screenshot 2020-06-09 at 22 25 59" src="https://user-images.githubusercontent.com/400092/84202667-435ed880-aaa0-11ea-8b16-bf0936e36197.png">
