### ISSUE TITLE
SQL field default value validation always fails

### ISSUE THREAD

**Issue by brbrbr** [joomla/joomla-cms#29565]
### Steps to reproduce the issue
Create a new field 'sql'
add query 
`(SELECT id as value, title as text FROM `#__categories` where extension = 'com_content' and published = 1)  union (SELECT 0 as value,'Empty' as text)`

add valid default value, in this case existing category or 0

save
### Expected result
Successful save

### Actual result
Save failed with the following error: The default value is invalid.

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/39355 should address this issue. Unfortunately, Joomla 3 does not receive regular bugs fixes on anymore, so we can only have this issue fixed for Joomla 4. Please help testing . Thanks !
