### ISSUE TITLE
[4.0] Private message reply_id is not validated before loading compose page

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29562]
### Steps to reproduce the issue

fake a reply id 

http://127.0.0.1/administrator/index.php?option=com_messages&view=message&layout=edit&reply_id=666999666

### Expected result

Expect that reply_id would be validated as an int, and if previous message not found, then an error to be raised

### Actual result

Message compose page loads, `Re:` in subject line

<img width="461" alt="Screenshot 2020-06-10 at 12 11 16" src="https://user-images.githubusercontent.com/400092/84261332-8017e780-ab13-11ea-9169-470bca78a7a9.png">

**Comment by Quy** [comment]
Please test PR #30103
