### ISSUE TITLE
[4.0] Filesystem plugin doesn't deduplicate folders 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29563]
### Steps to reproduce the issue

Edit the `FileSystem - Local` plugin in Joomla 4 

Click the add button to add the `images` folder multiple times.
Click save

### Expected result

deduplication so only 1 `image` folder is stored or an error message saying you cannot add the same folder twice (as, why would you want to?!)

### Actual result

When visiting media manager: 

<img width="668" alt="Screenshot 2020-06-10 at 12 18 01" src="https://user-images.githubusercontent.com/400092/84261975-a7bb7f80-ab14-11ea-9cbc-d9f5fb534ea2.png">

**Comment by ghost** [comment]
Issue confirmed.

**Comment by PhilETaylor** [comment]
Fixed partially. 

Fixed in media manager, not fixed in the file system plugin
