### ISSUE TITLE
[4.0] Mass Mail subject prefix input-group-prepend style incorrect

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29561]
### Steps to reproduce the issue

Probably a bootstrap migration thing? 
got to http://127.0.0.1/administrator/index.php?option=com_users&view=mail
click options 
click Mass Mail Users tab
set a prefix and a suffix
click save and close

### Expected result

Inlined subject prefix, inline with the subject field

Its using input-group-prepend so I had expected something like:

<img width="377" alt="Screenshot 2020-06-10 at 12 04 37" src="https://user-images.githubusercontent.com/400092/84260827-95d8dd00-ab12-11ea-830f-e41913168c54.png">

### Actual result

<img width="819" alt="Screenshot 2020-06-10 at 12 03 10" src="https://user-images.githubusercontent.com/400092/84260832-983b3700-ab12-11ea-9ab1-aff494f0d048.png">

### Additional comments

Joomla 3 screenshot for comparison:

<img width="675" alt="Screenshot 2020-06-10 at 12 02 47" src="https://user-images.githubusercontent.com/400092/84260669-57432280-ab12-11ea-9416-3d95c56824fc.png">

**Comment by SharkyKZ** [comment]
Please test PR #29572.
