### ISSUE TITLE
[4.0] Modal footer buttons color on hovering & ordering

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29560]
### Steps to reproduce the issue

Just one example - the "fix" probably involves a far greater investigation and review of modal buttons throughout.

Joomla 4.0b1
Users -> Add Note
Click create next to category 
Note three buttons in the footer.

Note their hover color
Note their ordering

### Expected result

Colors the same as normal, therefore save and close would be green and close red

Order the buttons the same as "normal"

"Normal" being defined like the buttons in the tool bars

<img width="444" alt="Screenshot 2020-06-10 at 11 55 16" src="https://user-images.githubusercontent.com/400092/84260039-4645e180-ab11-11ea-9dc1-fc2b6c9058ac.png">

### Actual result

<img width="468" alt="Screenshot 2020-06-10 at 11 50 38" src="https://user-images.githubusercontent.com/400092/84259726-d20b3e00-ab10-11ea-9e93-c5ce038a4d76.png">

### Additional Information 

Also see Close/Cancel debate: https://github.com/joomla/joomla-cms/issues/29544

**Comment by Quy** [comment]
Please test PR #29976
