### ISSUE TITLE
[4.0] Fix line height to modal buttons without icons

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#29575]
### Steps to reproduce the issue
Regression from #29375

Delete an image in the Media Manager to display a modal with buttons.

### Expected result
![83572077-c8b11e80-a4dd-11ea-8f10-d0eb89f71d58](https://user-images.githubusercontent.com/368084/84404917-4818af00-abbc-11ea-9607-69a4fe9dd26f.png)

### Actual result
![83572086-ca7ae200-a4dd-11ea-90d4-fd6271f7b60c](https://user-images.githubusercontent.com/368084/84404935-4d75f980-abbc-11ea-9cb4-b8e178a6069d.png)

**Comment by PhilETaylor** [comment]
Other modal button issues if someone is interested
https://github.com/joomla/joomla-cms/issues/29544
https://github.com/joomla/joomla-cms/issues/29560

**Comment by brianteeman** [comment]
please see #29715

**Comment by Quy** [comment]
Thanks.
