### ISSUE TITLE
[4.0] `No Matching Results`  in modal layout wrong.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29588]
### Steps to reproduce the issue

Joomla 4
Edit the plugin `System - Privacy Consent`
Click Select button next to the `Privacy article` field

### Expected result

`No Matching Results` correctly formatted under the filters

### Actual result

<img width="1570" alt="Screenshot 2020-06-12 at 22 38 01" src="https://user-images.githubusercontent.com/400092/84548388-66d28f00-acfd-11ea-8c3e-deb766f19b60.png">

### System information (as much as possible)

Safari on mac

**Comment by brianteeman** [comment]
Looks like all the markup needs checking in that modal. As well as confirming the issue above there is an issue that the toolbar moves to the right when the search filters are open.

![image](https://user-images.githubusercontent.com/1296369/84549109-1bb97b80-acff-11ea-9320-81395b2a0880.png)

**Comment by brianteeman** [comment]
sorry forgot to add
When the filter options are open the "no results" is displayed in the correct place but not 100%

![image](https://user-images.githubusercontent.com/1296369/84549193-528f9180-acff-11ea-8e61-8da4d10fcad9.png)

**Comment by chmst** [comment]
Please test #29594<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29588">issues.joomla.org/tracker/joomla-cms/29588</a>.</sub>

**Comment by chmst** [comment]
Closing this as we have a PR
