### ISSUE TITLE
[4.0] Unable to install italian in joomla4 beta

### ISSUE THREAD

**Issue by PixedBo** [joomla/joomla-cms#29583]
### Steps to reproduce the issue

Install J4Beta, at the end try to install italian as additional language

### Expected result

italian is installed

### Actual result

got a warning and language not installed:

![immagine](https://user-images.githubusercontent.com/12549961/84527656-902ff280-acde-11ea-89c1-51705ace182a.png)

### System information (as much as possible)

i did try on both linux (virtual host) and XAMPP local host

### Additional comments

other languages have no problems (or at least the ones i did try.. like german or french).
All the languages have "versione 3.9.x.y" beside, but just italian does not install... if something is missing in the translation i'm willing to help

**Comment by Quy** [comment]
Duplicate #21806
