### ISSUE TITLE
[4.0] Should uitabs have open/close arrows on narrow screens?

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#29580]
### Steps to reproduce the issue

Look at any Edit screen with multiple tabs on a narrow screen.

### Expected result

Full screen width tabs usually have open/close arrows.

### Actual result

![screen shot 2020-06-12 at 11 56 53](https://issues.joomla.org/uploads/1/94bbb9d115fd8983abf3af6a1bec35b8.png)

### Additional comments

Looked for but did not find anything similar.

**Comment by infograf768** [comment]
Alas, I have also complained about that and received a will-not-do response from @dgrammatiko

**Comment by dgrammatiko** [comment]
> and received a will-not-do response from @dgrammatiko

You received the `will not do` for 2 reasons:
- I don't agree with the decision that tabs automatically convert to accordion
- When I tried last time to fix the mess people weren't interested (to put it nicely)

So although I implemented the idea (it wasn't mine and I wasn't in favour) I cannot be blamed for it, I was just translating the requirements to code. Also just because you have different requirements now I cannot just simply jump in and implement them. It doesn't work like that...

**Comment by infograf768** [comment]
I was not the one having that requirement, as you may or may not know. In fact I never had any requirements for J4...
I am curious to know who had as this is one of J4 aspects which is totally counter-productive.
 I discovered the issue when testing com_associations as it does not require a smaller screen.

**Comment by dgrammatiko** [comment]
> I am curious to know who had as this is one of J4 aspects which is totally counter-productive.

The accessibility team, read their docs

**Comment by ceford** [comment]
I looked / searched for information on this topic but did not find anything. Is there a place where decisions are recorded? I am curious to know what the arguments were. I have been using Tabs that wrap and prefer that design.

**Comment by dgrammatiko** [comment]
@ceford unfortunately due to some reason the original docs are not available anymore (https://joomla.github.io/accessibility/#/) so the only resource there is https://github.com/joomla/accessibility/issues/22

**Comment by richard67** [comment]
I think there should be some arrows or +/- icons, however it is achieved. Just my 5 ct.

**Comment by dgrammatiko** [comment]
> I think there should be some arrows or +/- icons, however it is achieved. Just my 5 ct.

It can be done with some css. No js code needed for this

**Comment by infograf768** [comment]
arrows are not the issue.
what is needed is what we get with bootstrap accordion + slide, so that we can close a slide.
uitabs only closes a slide when opening another which forces to scroll and scroll...

**Comment by dgrammatiko** [comment]
> uitabs only closes a slide when opening another which forces to scroll and scroll

@infograf768 just add a `return` after https://github.com/joomla-projects/custom-elements/blob/4395d94226466041ac874dcbcfe9acb7b3c0e647/src/js/tab/tab.js#L202

So simple...

**Comment by ceford** [comment]
I think this is worth pursuing. As evidence I include screenshots in responsive design mode. Firstly from one of my Admin forms in j3, portrait mode:
![image](https://user-images.githubusercontent.com/1560390/84556270-529c8b00-ad19-11ea-98dc-1b9b7cd015cb.png)
And from the same form in J4, landscape mode:
![image](https://user-images.githubusercontent.com/1560390/84556279-73fd7700-ad19-11ea-85a0-89441974c8d6.png)
In the latter it is not possible to see all of the Tabs at once and you have to scroll past a long form section to find the next tab. As a user experience - dreadful. And those wide blue bands - ugly!

So I am thinking custom css and/or javascript.

**Comment by infograf768** [comment]
> @infograf768 just add a return after https://github.com/joomla-projects/custom-elements/blob/4395d94226466041ac874dcbcfe9acb7b3c0e647/src/js/tab/tab.js#L202

> So simple...

@dgrammatiko 
Not so simple. I'm afraid this is not enough.
```
        if (this.hasActive) {
          this.hideCurrent();
          return;
        }
```
It lets close the open slide indeed by clicking on it but then it is impossible to open any slide, including the one just closed.

**Comment by dgrammatiko** [comment]
> It lets close the open slide indeed by clicking on it

That's what you've asked for

> but then it is impossible to open any slide, including the one just closed.

So it needs to be conditional only if the the clicked link is the current one and you're in the accordion mode...

**Comment by infograf768** [comment]
> So it needs to be conditional only if the the clicked link is the current one and you're in the accordion mode...

@dgrammatiko 
Not sure what you mean exactly. I am no js expert.
What we need is a behavior similar to bootstrap accordeon/slide

I.e. clicking on the slide title lets open when closed and close when opened.
Can you provide the full patch?

**Comment by dgrammatiko** [comment]
Sorry no, no spare time

**Comment by infograf768** [comment]
@Fedik 
Could you please have a look?

**Comment by Fedik** [comment]
to be honest I not very like current tabs/accordion thing :)
I cannot promise much,
but I agree it an issue, not arrow/plus icon, but toggling

**Comment by Fedik** [comment]
@infograf768 please try the changes from that pull https://github.com/joomla-projects/custom-elements/pull/141 
that should toggle an accordion

**Comment by brianteeman** [comment]
@infograf768 did you test the proposed change from @fedik to address your change request

**Comment by infograf768** [comment]
No. Will look.

**Comment by infograf768** [comment]
It works great!

https://github.com/joomla-projects/custom-elements/pull/141#issuecomment-749395292

**Comment by infograf768** [comment]
To test:
Set debug system and replace file
`/media/vendor/joomla-custom-elements/js/joomla-tab.js`
by this one, decompressed.

[joomla-tab.js.zip](https://github.com/joomla/joomla-cms/files/5728463/joomla-tab.js.zip)

**Comment by infograf768** [comment]
Closing as toggling now works correctly in 4.0-dev. The matter of up/down arrow looks epiphenomenic.
