### ISSUE TITLE
Will SVG be displayed in the media manager when selecting an image? 

### ISSUE THREAD

**Issue by sokoloff-rv** [joomla/joomla-cms#29582]
When you select an image through a field with the type "media", SVG format files are not displayed. Will this be fixed in the future?

**Comment by richard67** [comment]
I know there was a big discussion in past but I don't find the issues for it now.
@brianteeman @SniperSister Do you know what the status of the discussion was and if there was a conclusion?

**Comment by Quy** [comment]
See https://github.com/joomla/joomla-cms/pull/20741

**Comment by richard67** [comment]
Hmm, I see .. and this then refers to issue #18373 ... and this then to PR #13499 ... long story.

What to do with this issue here now?

**Comment by sokoloff-rv** [comment]
I can’t understand one thing. If I [enable SVG in the settings](https://drive.google.com/file/d/1wiuYcblp84QKOZxxNaQbwIwxwjpi_G6W/view?usp=sharing), then when I open the media manager, the [SVG files become visible](https://drive.google.com/file/d/15rCMNse6zsef34Q-T8Wgf7oosT7yaZq9/view?usp=sharing). But if I try somewhere to choose SVG as the image (for example, for the opening text of the article), the system will tell me that there [are no suitable files](https://drive.google.com/file/d/1GjWChqEdNYMmPlBXi-Wmf0w6mLjJrtCQ/view?usp=sharing). Why can’t display an SVG file in the same way as in a media manager?

**Comment by Quy** [comment]
See previous discussion #28599

**Comment by Quy** [comment]
Please test PR #29728
