### ISSUE TITLE
Updating to 3.9.19 gives Error #1054 Unknown column 'status' in 'field list'

### ISSUE THREAD

**Issue by justinherrin** [joomla/joomla-cms#29585]
### Steps to reproduce the issue
I was doing typical maintenance on a client's Joomla site. Updated a Joomla site from 3.9.16 to 3.9.19. I also updated some extensions that needed it (i.e. JCE, RS Form Pro, RS SEO)

### Expected result
Site working.

### Actual result
Error page seen showing... Error # 1054 Unknown column 'status' in 'field list' 

### System information (as much as possible)
Joomla 3.9.19
PHP 7.2.31
MySQL 5.5.5-10.3.23-MariaDB
Apache/2.4.43

### Additional comments
I tried the usual Extensions -> Manage -> Database -> Fix button, but it shows that the "Database table structure is up to date."
Database schema version (in #__schemas): 3.9.19-2020-06-01.
Update version (in #__extensions): 3.9.19.
Database driver: mysqli.
187 database changes were checked.
212 database changes did not alter table structure and were skipped.

I also tried to re-install the 3.9.19 files through Components -> Joomla Update -> Reinstall button

I also tried disabling the site's custom template and using Protostar template got me the error message above.

**Comment by SharkyKZ** [comment]
Enable debug in Global Configuration, trigger the error again and post stack trace here.

**Comment by justinherrin** [comment]
Hi there. Stack trace is...


1054 Unknown column 'status' in 'field list'
/public_html/libraries/joomla/database/driver/mysqli.php:665


Call stack
--
# | Function | Location
1 | () | JROOT/libraries/joomla/database/driver/mysqli.php:665
2 | JDatabaseDriverMysqli->execute() | JROOT/plugins/system/cleantalkantispam/lib/Cleantalk/ApbctJoomla/SFW.php:20
3 | Cleantalk\ApbctJoomla\SFW->universal_query() | JROOT/plugins/system/cleantalkantispam/lib/Cleantalk/Antispam/SFW.php:87
4 | Cleantalk\Antispam\SFW->check_ip() | JROOT/plugins/system/cleantalkantispam/cleantalkantispam.php:2069
5 | plgSystemCleantalkantispam->sfw_check() | JROOT/plugins/system/cleantalkantispam/cleantalkantispam.php:556
6 | plgSystemCleantalkantispam->onBeforeCompileHead() | JROOT/libraries/joomla/event/event.php:70
7 | JEvent->update() | JROOT/libraries/joomla/event/dispatcher.php:160
8 | JEventDispatcher->trigger() | JROOT/libraries/src/Application/BaseApplication.php:108
9 | Joomla\CMS\Application\BaseApplication->triggerEvent() | JROOT/libraries/src/Document/Renderer/Html/HeadRenderer.php:67
10 | Joomla\CMS\Document\Renderer\Html\HeadRenderer->fetchHead() | JROOT/libraries/src/Document/Renderer/Html/HeadRenderer.php:38
11 | Joomla\CMS\Document\Renderer\Html\HeadRenderer->render() | JROOT/libraries/src/Document/HtmlDocument.php:501
12 | Joomla\CMS\Document\HtmlDocument->getBuffer() | JROOT/libraries/src/Document/HtmlDocument.php:793
13 | Joomla\CMS\Document\HtmlDocument->_renderTemplate() | JROOT/libraries/src/Document/HtmlDocument.php:567
14 | Joomla\CMS\Document\HtmlDocument->render() | JROOT/libraries/src/Application/CMSApplication.php:1044
15 | Joomla\CMS\Application\CMSApplication->render() | JROOT/libraries/src/Application/SiteApplication.php:778
16 | Joomla\CMS\Application\SiteApplication->render() | JROOT/libraries/src/Application/CMSApplication.php:202
17 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/index.php:49

**Comment by justinherrin** [comment]
And dang, looks like I found the culprit...

Plugin called "Anti-spam by CleanTalk". If I unpublish that, the site works again.

**Comment by Quy** [comment]
Closing as non-core issue. Please contact the developer.
