### ISSUE TITLE
[4.0] page_subheading unused param

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#29586]
### Steps to reproduce the issue

```
			<field
				name="page_subheading"
				type="text"
				label="JGLOBAL_SUBHEADING_LABEL"
				size="20"
			/>
```

This field exists in several front end tmpl eg blog category, featured articles. list category

### Expected result
The content of the field is displayed

### Actual result
in the list category tmpl it is never used.

**Comment by chmst** [comment]
Could we remove these fields? I don't remember that there were subheadings.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29586">issues.joomla.org/tracker/joomla-cms/29586</a>.</sub>

**Comment by ReLater** [comment]
They are used in several frontend views but not in Article Category List (J3 and J4). In Joomla 3 Beez has a custom override for Article Category List  where it's used, too.

In the name of consistency and B\C I would add it in the Article Category List output of Joomla 4 instead of removing it.

**Comment by ReLater** [comment]
https://github.com/joomla/joomla-cms/blob/staging/components/com_content/views/category/tmpl/blog.php#L39-L45

https://github.com/joomla/joomla-cms/blob/staging/components/com_content/views/featured/tmpl/default.php#L27-L31

**Comment by brianteeman** [comment]
That's what i said

**Comment by astridx** [comment]
Staging and Beez are Joomla 3x. This is about Joomla 4, right?

I mean a subtitle doesn't belong in a component. It does not belong to C in MVC, but to the view. If a template wants to display a subtitle, then I think it should create its own override (In my opinion, this also applies to the standard template). A subtitle could then be specified via a menu parameter. This also has the advantage: In this case, everything is together and is not forgotten when deleting.

**Comment by chmst** [comment]
This is right (that it belongs to the view), but I think, if somone wants subheadings, he ca use a custom field and template override.

**Comment by SharkyKZ** [comment]
Looks like this was lost by mistake when switching to JLayout https://github.com/joomla/joomla-cms/commit/de3a3e1c2fdc9accd285a9d3f0f6fbfcda9774c2.

**Comment by ReLater** [comment]
When we remove the page_subheading fields that are there for a long time in Joomla and used/displayed can we then please remove also all other settings/fields where some professors will find arguments for removing them?

Because users can make overrides and some more overrides and more overrides instead of relying in B\C promises that were made in the past. Let's kick them in the a... again.

**Comment by AndySDH** [comment]
I stumbled upon this while making PR #32525, so I addressed it there. Please test the PR.

**Comment by alikon** [comment]
please test #32525
