### ISSUE TITLE
[4.0] Workflow: "Save as copy" of default workflow brings up "Warning - Field required: Default" and doesn't make a copy.

### ISSUE THREAD

**Issue by particthistle** [joomla/joomla-cms#29597]
### Steps to reproduce the issue
"Save as copy" of default workflow brings up "Warning - Field required: Default" and doesn't make a copy.

- _Enable Workflows in Joomla 4 Beta 2 to be able to test this issue_
- Go to Content > Workflows
- Edit the default workflow
- Go to Save as Copy
![image](https://user-images.githubusercontent.com/5515866/84571453-8689b600-add6-11ea-836c-9fc7def3b926.png)

### Expected result
You should have a second copy of the default workflow that you can then edit to your own requirements.

### Actual result
Warning thrown and new copy is not created.
![image](https://user-images.githubusercontent.com/5515866/84571475-b2a53700-add6-11ea-9719-04394b7ecdb0.png)

### Additional comments
- If you create a new workflow, and then Save as Copy to duplicate the new workflow, it makes a copy, so the issue is only affecting when you go to make a copy of the default workflow.
- Discovered while testing https://github.com/joomla/joomla-cms/pull/29263

**Comment by chmst** [comment]
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29597">issues.joomla.org/tracker/joomla-cms/29597</a>.</sub>

**Comment by particthistle** [comment]
Additionally while testing PR for https://issues.joomla.org/tracker/joomla-cms/29573 I encountered a related variation - same code will most likely fix both.

I can set the second workflow as default while on the Workflows screen
![29597-worfklowsdefault](https://user-images.githubusercontent.com/5515866/85918498-aa54fd80-b8a6-11ea-8c1f-cf6805c681b4.gif)

When I edit the workflow, and then set it as default:
- Setting the workflow to default and clicking Save a first time saves the workflow with the default setting set to Yes
- Clicking Save again once the workflow is set as Default brings up the _Warning: Field Required: Default_
- Clicking Save and Close one the workflow is set as Default also brings up the _Warning: Field Required: Default_ and won't let you close the workflow due to the error.
- When opening the workflow that is selected as default to modify it, you will get the _Warning: Field Required: Default_ warning message on Save or Save and Close, so you can't customise the Basic Workflow while it's set as the default workflow, or any other workflow if it's set as the default workflow.
- The only way to close the default workflow is to click Cancel.
![29597-worfklowssaveasdefault](https://user-images.githubusercontent.com/5515866/85918542-1cc5dd80-b8a7-11ea-9821-2dd1b7be02ef.gif)

**Comment by particthistle** [comment]
@bembelimen you might be in the best position to address this issue.

**Comment by particthistle** [comment]
Thanks @chmst - testing it now.

**Comment by particthistle** [comment]
![image](https://user-images.githubusercontent.com/5515866/85920874-dd08f100-b8ba-11ea-8cc0-11a7295109fb.png)

**Additional issue discovered:**
This issue was initially raised using Joomla 4.0 Beta 2 Dev where @benbelimen's final changes were then pulled into the final Joomla 4.0.0-beta1.

It appears "Save as Copy" is disabled in 4.0.0-beta1, so that needs to be also resolved.

**Comment by particthistle** [comment]
Ignore previous comment. 

This pull request fixes the Save2Copy being missing in 4.0.0-beta1
https://github.com/joomla/joomla-cms/pull/29263

Applying nightly build restored the functionality.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29597">issues.joomla.org/tracker/joomla-cms/29597</a>.</sub>
