### ISSUE TITLE
English language strings Robots 

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#29595]
### Steps to reproduce the issue
Have a look at the Global Configuration, tab "Site" label "Robots".
The options are presented by the following strings:
JGLOBAL_INDEX_FOLLOW="Index, Follow"
JGLOBAL_INDEX_NOFOLLOW="Index, No follow"
JGLOBAL_NOINDEX_FOLLOW="No index, follow"
JGLOBAL_NOINDEX_NOFOLLOW="No index, no follow"

### Expected result
JGLOBAL_NOINDEX_FOLLOW="No index, Follow"
JGLOBAL_NOINDEX_NOFOLLOW="No index, No follow"

### System information (as much as possible)

Joomal 3.9 and Joomla 4.0-beta

**Comment by richard67** [comment]
@brianteeman Could you have a look on this ~~PR~~ isue? From my point of view it makes it consistent, but I think the result is wrong, it would be only uppercase at the very beginning and not again after the comma. So this issue suggest to change just the wrong 2 of the 4 strings.

**Comment by richard67** [comment]
I think it should be:
JGLOBAL_INDEX_FOLLOW="Index, follow"
JGLOBAL_INDEX_NOFOLLOW="Index, no follow"
JGLOBAL_NOINDEX_FOLLOW="No index, follow"
JGLOBAL_NOINDEX_NOFOLLOW="No index, no follow"

**Comment by brianteeman** [comment]
Personally they are all wrong. They are neither an explanation of what they mean which can be translated not the correct technical terms which should not be translated

**Comment by richard67** [comment]
@brianteeman Do you have a suggestion what they should be, explaining or the technical terms?

**Comment by brianteeman** [comment]
I would use the correct technical terms and make sure they are marked as not to be translated.

**Comment by richard67** [comment]
Thanks ... anyone wants to make a PR for J3 (staging)?

@wilsonge I think it should find its way up to J4 after it has been corrected in staging, even with the renamed language files, am I right?

**Comment by richard67** [comment]
For J3 (staging), see Pull Request (PR) #29612 .

@MartijnMaandag @brianteeman Please test. Thanks in advance.

**Comment by richard67** [comment]
Closing as having a Pull Request (PR). It is for J3 and will either later be merged up into the branch for J4 when this is regularly done, or if desired I will make a PR for J4, too.

**Comment by richard67** [comment]
PR for J4 is #29613 .

**Comment by horus68** [comment]
So you are saying that "technical terms are not to be translated"?
If the translated value do not mess with the system then they could be translated (by translator decision)
If translated value mess with the code they should not be in translation files!

**Comment by richard67** [comment]
@horus68 It is not about technical terms in general.

The possible values of the "robots" meta tag are fixed in HTML standard, and everybody who adjusts such stuff will expect those values and not any translation in the list. Things like that should not be translated.

**Comment by horus68** [comment]
I disagree with that. 
On the comments for the string it is misleading.
It should be edit from the "Please do not translate the following language string" (only to be used when there is a real problem) to something like "It's recommended to not translate the following language string"

**Comment by richard67** [comment]
> It should be edit from the "Please do not translate the following language string" (only to be used when there is a real problem) to something like "It's recommended to not translate the following language string"

Nitpicking.

**Comment by richard67** [comment]
So if you want to translate "index, follow" in a UI where people select a robots meta tag which shall have exactly that value, "index, follow", do you also want to translate e.g. things like the values of the "rel" attribute, e.g. "noreferrer" and so on, of a hyperlink in the UI?

And the comments for the translaters have been copied from other places, I haven't invented them myself.

**Comment by horus68** [comment]
I don't say you are wrong. I understand your option, I just do not agree with it, for so many reasons. For me this is a question for each language team to deal (and i'm not talking here on different alphabet systems used).

On the comments: we need to be "Nitpicking" sometimes.
If a comment says not to translate then it should be a real alert. Else nobody will remember in a year from now if this is a true alert or just an option!

**Comment by richard67** [comment]
Well, in my opinion the comment is right because the text shall not be translated at all, like all texts listing values defined in HTML standards as they appear in a tag or an attribute. In principle it would be even better to remove the language string but for technical reasons that was not possible.

If you disagree, feel free to propose a pull request to change it, or convince someone else to do so, or open a new issue. A discusssion in a closed issue will not find much attendance by the community.
