### ISSUE TITLE
[4.0] [Workflow] Close the opened Transition list in articles list view

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#29608]
### Steps to reproduce the issue
Go to the com_content articles list view in the backend and click the workflow-icon to open the dropdown.
There is no way to close the list again.

### Expected result
Some way to close the list.

### Actual result
No way to close the list.

### Additional comments
This is just a copy of @brianteeman post [here](https://github.com/joomla/joomla-cms/pull/29235#issuecomment-635230933) so it's not forgotten.

**Comment by Quy** [comment]
Duplicate #25020
