### ISSUE TITLE
Prb with parent field

### ISSUE THREAD

**Issue by flob38** [joomla/joomla-cms#29600]
### Steps to reproduce the issue
Create or edit a tag from the backend

### Expected result
List of tags sort by there title

### Actual result
When creating a tag from the backend, the "parent" field doesn't show any already created tags.
When editing a tag from the backend, the "parent" field only show IDs

### System information (as much as possible)
Windows 10, Firefox 77.0.1
Local server with EasyPhp, Php7.3.17

**Comment by Quy** [comment]
Duplicate #29341?

Please test with the beta nightly builds: https://developer.joomla.org/nightly-builds.html
