### ISSUE TITLE
[4.0] s/No sufficient/insufficient ?

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29617]
### Steps to reproduce the issue

Mess with your permissions so that Joomla 4.0 installer cannot write a configuration.php 

Load http://127.0.0.1:8400/installation/index.php which redirects to http://127.0.0.1:8400/installation/index.php?view=preinstall

### Expected result

Correct English?

### Actual result

<img width="752" alt="Screenshot 2020-06-15 at 09 02 10" src="https://user-images.githubusercontent.com/400092/84632497-e96a7280-aee6-11ea-9d59-048e4804f94b.png">

### System information (as much as possible)

Doesnt matter but this was in a docker bind mount, any incorrect permissions on the parent folder should replicate the issue

**Comment by brianteeman** [comment]
see #29623
