### ISSUE TITLE
[4.0] Cannot proceed with installer if permissions are wrong

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29618]
### Steps to reproduce the issue

Set your permissions so that the parent folder is unwritable

attempt to install Joomla 4.0 beta 1

### Expected result
I expect this screen
<img width="752" alt="Screenshot 2020-06-15 at 09 02 10" src="https://user-images.githubusercontent.com/400092/84632612-1028a900-aee7-11ea-8789-76c3804b919f.png">

But then I expect to be able to proceed, and manually create my configuration.php

### Actual result

You cannot proceed, there is nothing to click

You cannot provide a FTP connection details

### System information (as much as possible)

Joomla 3 allows you to create the db and populate it, and gives you the text of configuration.php at the end for you to manually copy and write to configuration.php

Joomla 4 should do that too as there are occasions on some crap web hosts where this is needed.

**Comment by wilsonge** [comment]
We have a ticket tracking FTP here https://github.com/joomla/joomla-cms/issues/20774 but we were never able to setup a host to test everything on.

This other method that exists in J3 - I've honestly never seen it/used it before. can you show screenshots? Honestly the only thing i was aware of was copying configuration.dist.php and manually replacing the prefix's in the installation.sql and running that in phpmyadmin.

**Comment by PhilETaylor** [comment]
In bed but here is a quick google found image

**Comment by PhilETaylor** [comment]
![8CF075CB-8516-4266-8517-276EF32581F9](https://user-images.githubusercontent.com/400092/84708086-bf9d6400-af57-11ea-88e9-dc4759da5aba.png)

**Comment by PhilETaylor** [comment]
Closing to #20774
