### ISSUE TITLE
[3.0] Repeated Media fields in a repeatable subform loose live preview rendering

### ISSUE THREAD

**Issue by nordmograph** [joomla/joomla-cms#29614]
Hello!

### Steps to reproduce the issue
Create a form xml with a repeatable subform field element. 
Within this subform use a media field with preview enabled.

### Expected result

When repeating that subform field, every repeated media field preview should display the preview straight away after media selection

### Actual result

It works only for the first media field , the one that has not been repeated. Other media fields would only display the preview after the form has been saved

### System information (as much as possible)
J3.9.19 - PHP 7.3.12

**Comment by richard67** [comment]
@nordmograph Would you mind to provide some system information? The corresponding section in the issue template is not there without any reaspn. PHP version and Joomla version should be sufficient as a start. Thanks in advance.

**Comment by Quy** [comment]
> System information (as much as possible)

Probably should update the template to replace `as much as possible` with request for Joomla version and PHP version.

**Comment by richard67** [comment]
@Quy I think people ignore it so or so.

**Comment by Quy** [comment]
@richard67 See the title. It is for J3.

**Comment by nordmograph** [comment]
Sorry for the missing info, I edited to add the php version. I thought the Joomla version that I provided was enough regarding this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29614">issues.joomla.org/tracker/joomla-cms/29614</a>.</sub>

**Comment by richard67** [comment]
@nordmograph Yes, was ok, seems I just have not checked the title carefully enough. But PHP version and exact Joomla version is always good, thanks for adding it.

**Comment by stutteringp0et** [comment]
Isn't this related to the warning on the subform documentation "If your field in the subform has additional JavaScript logic then it may not work in multiple mode"

There is example code to overcome the issue.

https://docs.joomla.org/Special:MyLanguage/subform_form_field_type

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed.

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
