### ISSUE TITLE
[4.0] "Complete &" is not required. 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29620]
### Steps to reproduce the issue

Install Joomla 4 

Look at last screen with fresh eyes.

### Expected result

No duplicate reference to `Complete &`
The buttons DONT `Complete` anything, they are just links to / and /administrator/

Maybe better links:
`"Visit your new site"` ?
`"Open the admin console"` ?
`"Login to the admin console"` ?

Is there even a good reason to visit the frontend of a newly installed website? I dont think much is gained from that, so maybe just have a link with

`"Continue to customise your site in the admin console"`?

Bonus points if there was an auto login to the admin console from the installer too ;-) 

### Actual result

<img width="715" alt="Screenshot 2020-06-15 at 09 09 58" src="https://user-images.githubusercontent.com/400092/84633285-153a2800-aee8-11ea-86a1-58e9615c5aa5.png">

**Comment by ReLater** [comment]
> Is there even a good reason to visit the frontend of a newly installed website?

Normally I check first both, frontend and backend, in new tabulators before I continue.

**Comment by Quy** [comment]
See #18833
