### ISSUE TITLE
Cannot logout in certain circumstances

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#29628]
### Steps to reproduce the issue
Create a new user
Create a new user group
create a new access level

go to system and allow the usergroup back end access

login

### Expected result
User has a means to logout

### Actual result
User does not have access to anything (correctly), which also means they cannot log out

User cannot visit /administrator/index.php?option=com_users&view=login&layout=logout either

**Comment by toivo** [comment]
@uglyeoin that is interesting but surely not an issue in a live site where new usergroups and access levels are usually tested before any real users are added to new usergroups.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29628">issues.joomla.org/tracker/joomla-cms/29628</a>.</sub>

**Comment by uglyeoin** [comment]
I didn't test it, so we can assume someone else could do the same thing.  Once I had logged in and realised the error I couldn't log out of my test user, so I couldn't fix the problem by logging back into my Super User.  I could have cleared my cookies, but perhaps another user doesn't know that.

Is there ever a time when a logged in user should not be authorised to log out?

What you have said is almost on par with saying, we shouldn't check that an email address has been entered when creating a user, because surely they know to do that.  In some cases we shouldn't rely on the users.

**Comment by brianteeman** [comment]
It's a valid bug

**Comment by toivo** [comment]
@uglyeoin @brianteeman - 
Creating users is completely different, of course.  In this particular case we should not be relying on users either, but new users should be able to rely on webmasters to have created their usergroup in such a way that it inherits permissions from its parent or is otherwise set up and tested properly beforehand.   That is how back end administration has worked in the past.

**Comment by uglyeoin** [comment]
But how can you test it without logging in as that user?  And then once you do you cannot log out to fix whatever error you have made.

**Comment by toivo** [comment]
@uglyeoin - nothing stops you from using two different browsers.

**Comment by brianteeman** [comment]
That is a work around. Doesn't stop it being a bug that can be fixed

**Comment by SharkyKZ** [comment]
Is this about `mod_user` having `Special` access level (related https://github.com/joomla/joomla-cms/issues/28804)?

**Comment by brianteeman** [comment]
yes it is but I am assuming that @uglyeoin is referring to j3 and that is for j4

**Comment by uglyeoin** [comment]
Sorry I thought I mentioned it but obviously I didn't this was in J4.

**Comment by uglyeoin** [comment]
@SharkyKZ yes that looks the same to me.  Nice work I'll close this.
