### ISSUE TITLE
[4.0]  Undefined class constant 'ONLY_BLOCK_DEFINED_TAGS'

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#29634]
### Steps to reproduce the issue
Enter data in a field where filter="safehtml", i.e.
Open Login module, field pretext.
Save and close

### Expected result
The input is accepted and saved.

### Actual result
Error 0:  Undefined class constant 'ONLY_BLOCK_DEFINED_TAGS'

**Comment by SharkyKZ** [comment]
Run `composer install`.

**Comment by chmst** [comment]
@SharkyKZ thank you
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29634">issues.joomla.org/tracker/joomla-cms/29634</a>.</sub>
