### ISSUE TITLE
[4.0] Big Cursor doesnt work on frontend.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29647]
### Steps to reproduce the issue

Enable `System - Additional Accessibility Features` Plugin in Joomla 4.0.0 beta 1
configure the plugin to load on the frontend

Load the frontend

### Expected result

it works as designed?

### Actual result

click the icon to open the menu
Click "Big Cursor" - note the cursor changes
move the mouse to the webpage as you would, to navigate - note that the cursor size reduces to normal again

FRONTEND:
Seems if you move slowly the big cursor is never invoked, and sometimes after you have moved, the cursor stays large, and sometimes it reduces in size again

ADMIN CONSOLE:
The big cursor is always big regardless of movement or location = expected 

### System information (as much as possible)
tested on Mac - Safari and google chrome

**Comment by PhilETaylor** [comment]
ok I think I have worked out the cursor issue on frontend... 

First lets look at Reading Guide - note that the green/black line can show ANYWHERE on the default page see: 

<img width="1535" alt="Screenshot 2020-06-16 at 21 46 01" src="https://user-images.githubusercontent.com/400092/84826482-e8d2f880-b01a-11ea-98a6-4dca11439ec2.png">

However the Big Cursor is limited to the html tag with class `_access_cursor` which DOESNT cover the whole (huge 27" iMac) screen by default

<img width="1606" alt="Screenshot 2020-06-16 at 21 47 19" src="https://user-images.githubusercontent.com/400092/84826596-1455e300-b01b-11ea-98b9-9891181dfcd0.png">

**Comment by brianteeman** [comment]
This is an upstream library see https://github.com/ranbuch/accessibility

**Comment by PhilETaylor** [comment]
yes a library `last released 4 Oct 2016` - its last release only predates my first Joomla 4 logged issue in this tracker by 1 month... 

Maybe if the Joomla project's flagship release with accessibility features is going to rely on it, then the Joomla project might want to fork it? 

Checking their project the last commit 16 days ago was "fix vulnerabilities"... 

Joomla 4 beta 1 states 

```json
 {
      "name": "accessibility",
      "type": "script",
      "uri": "vendor/accessibility/accessibility.min.js",
      "attributes": {
        "defer": true
      },
      "package": "accessibility",
      "version": "3.0.9"
    }
```

However there is no such version 3.0.9 released here https://github.com/ranbuch/accessibility/releases

so im as confused as the fish on the floor at the restaurant at the end of the universe.

**Comment by PhilETaylor** [comment]
Ah I see 3.0.9 is from the npm eco system... https://www.npmjs.com/package/accessibility oh well
