### ISSUE TITLE
[4.0] Mime Types not validated

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29646]
### Steps to reproduce the issue

Probably a `won't fix` but hey Ill report anyway... 

Joomla 4.0.0 beta 1
http://example.rocks/administrator/index.php?option=com_config&view=component&component=com_media

Enter `nosuch/mimetypeexists` for the mime types

<img width="923" alt="Screenshot 2020-06-16 at 21 30 01" src="https://user-images.githubusercontent.com/400092/84824917-8ed13380-b018-11ea-8ed8-050cdfa2cf91.png">

Click Save

### Expected result

Validation of the mime types against a predefined definitive list of mime types assigned http://www.iana.org/assignments/media-types/media-types.xhtml

### Actual result

No validation. 

### Additional comments

I guess there might be two camps here...

**Comment by brianteeman** [comment]
I would say that this should be a won't fix.

**Comment by Fedik** [comment]
It is valid mime type `nosuch/mimetypeexists` if you write the app that produce such files :wink:  
https://stackoverflow.com/a/3828381/1000711

Nothing to fix here.

**Comment by PhilETaylor** [comment]
Wrong. `nosuch/mimetypeexists` is not a valid mime type until it is assigned and listed by the IANA. 

[RFC2046] specifies that Media Types (formerly known as MIME types) and Media
Subtypes **will be assigned and listed by the IANA**.

Procedures for registering Media Types can be found in [RFC6838], [RFC4289], 
and [RFC6657]. 

Additional procedures for registering media types for transfer via 
Real-time Transport Protocol (RTP) can be found in [RFC4855].

**Comment by Fedik** [comment]
Anyway, there is no good reason to spend a time on it. We does not developing an email server or anything else that require strict mime types validation.

**Comment by PhilETaylor** [comment]
> anything else that require strict mime types validation.

LMAO that is literally the point of this field in the form. For security, to check strict for illegal mime types for security reasons hahaha

I agree though there there are more important things to spend time on ... ;-)

**Comment by PhilETaylor** [comment]
@brianteeman Please can you rewrite the sentence:

"A comma separated list of illegal MIME types to upload (blacklist)"

as it makes no sense at the moment.

**Comment by Fedik** [comment]
> LMAO that is literally the point of this field in the form. For security, to check strict for illegal mime types for security reasons

In our context "illegal mime" means "not allowed mimes", not illegal from IANA point of view ;)
This English so confusing ;)
