### ISSUE TITLE
Move articles "Browser Page Title" to publishing tab

### ISSUE THREAD

**Issue by TVBZ** [joomla/joomla-cms#29644]
### What needs to be fixed
In article "options" tab, there is the Browser Page Title field. This field feels misplaced here.
![image](https://user-images.githubusercontent.com/43469713/84814566-f6d04b80-b011-11ea-88a1-29b10fe32185.png)

### Why this should be fixed
This field is mostly for SEO purposes. It belongs in the publising tab, where the other meta fields are.
Currenlty, when disabling the options tab, the field is not accessible.
It's an important field for articles that don't have a dedicated menu item.
I believe it would be an improvement in SEO management if the field was moved.

### How would you fix it
Inside the article.xml, simply move the field from [line 597](https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/models/forms/article.xml#L597) to [line 1016](https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/models/forms/article.xml#L1016), just before the robots field.

![image](https://user-images.githubusercontent.com/43469713/84814669-18c9ce00-b012-11ea-8adf-d4d36a93061f.png)

**Comment by Quy** [comment]
Duplicate  #15833

**Comment by AndySDH** [comment]
It's not really a duplicate, I mean, even just the simple change of moving the Browser Page Title to the Publishing Tab (without creating a separate SEO tab) is a step forward already

**Comment by TVBZ** [comment]
Agreed. I don't see the logic of putting it inside the options tab.
