### ISSUE TITLE
[4.0] System - Additional Accessibility Features safari admin issues

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29648]
### Steps to reproduce the issue

Joomla 4.0.0 beta 1 - enabled plugin `System - Additional Accessibility Features` 

Compare admin console in Safari and Google Chrome

### Expected result

The same

### Actual result

Note that in Safari the "Recycle" image is used instead of refresh in google chrome
The X image is different too 

Safari:
<img width="410" alt="Screenshot 2020-06-16 at 21 52 58" src="https://user-images.githubusercontent.com/400092/84827021-bfff3300-b01b-11ea-8975-720018fdd693.png">

Google Chrome:
<img width="426" alt="Screenshot 2020-06-16 at 21 53 16" src="https://user-images.githubusercontent.com/400092/84827048-cb525e80-b01b-11ea-8e78-e2cdcfab848c.png">

Console log on SAFARI on Mac says:

<img width="847" alt="Screenshot 2020-06-16 at 22 04 22" src="https://user-images.githubusercontent.com/400092/84828087-639d1300-b01d-11ea-9c37-8aa29c460b63.png">

Also this icon is different for a reason?

<img width="314" alt="Screenshot 2020-06-16 at 21 37 39" src="https://user-images.githubusercontent.com/400092/84825656-a8bf4600-b019-11ea-9c9b-b6cd4ea50da8.png">

**Comment by brianteeman** [comment]
This is an upstream library see https://github.com/ranbuch/accessibility
