### ISSUE TITLE
[4.0] Cannot save empty values for Illegal Mime Types and other fields. 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29645]
### Steps to reproduce the issue

Joomla 4.0.0 beta 1
http://example.com/administrator/index.php?option=com_config&view=component&component=com_media

delete the value `text/html` from `illegal mime types` (which is perfectly valid to do, a admin might want a user to be able to upload html files)

click save

### Expected result

field remains empty. No mime types are blacklisted on upload

### Actual result

field is repopulated with `text/html`

### Additional comments

Also applies to other fields on this page, for example (no idea why you would want to, that's why Im highlighting the above only) you cannot delete all the `legal extensions` or `legal mime types`

<img width="1300" alt="Screenshot 2020-06-16 at 21 25 01" src="https://user-images.githubusercontent.com/400092/84824452-dc996c00-b017-11ea-9dca-5dbed6fb4407.png">

**Comment by mbabker** [comment]
If I had to blindly guess it's the same long standing problem of the value from the `default` attribute on a form field definition being used when a field is submitted with an empty value.

**Comment by PhilETaylor** [comment]
yup the old `0 !== "" !== false !== null` kind of problem :-)

**Comment by brianteeman** [comment]
Michael is correct with the reason. 

However I wouldnt try to "fix it" because the reason for this is so that you can reset the value of a field to the defaults.

**Comment by PhilETaylor** [comment]
Its also reasonable to assume an admin might not want to block any MIME Types, and therefore the catch 22 exists - you can't allow all because doing so resets the default.

**Comment by PhilETaylor** [comment]
and if the underlying reason for this is as stated - then this has knock on effects for ALL fields where an admin might rightly want to remove the default and save a blank value.

**Comment by brianteeman** [comment]
I doubt that there is a real world example where a default is present and you would want to make it blank. I'm not going to take the time to try and find one.

**Comment by PhilETaylor** [comment]
I already gave one. 

> delete the value text/html from illegal mime types (which is perfectly valid to do, a admin might want a user to be able to upload html files)

**Comment by brianteeman** [comment]
ok ouch i withdraw  my earlier comment

**Comment by PhilETaylor** [comment]
no one else complained in the last decade so can't be that important.

**Comment by Webdongle** [comment]
Is that what is causing https://github.com/joomla/joomla-cms/issues/38235 ?

**Comment by richard67** [comment]
> Is that what is causing #38235 ?

I think that's the case.
