### ISSUE TITLE
plugin Recaptcha invisible doesn't appear in the list of my plugins - joomla 3.9.19

### ISSUE THREAD

**Issue by Johann009** [joomla/joomla-cms#29641]
I'd like to try putting an invisible recaptcha in my contact form. But the plugin ReCaptcha Invisible does not appear in my plugin list I only have the Captcha Recaptcha plugin. Why can't I see and activate the invisible Recaptcha plugin? I use version 3.9.19 of joomla.

**Comment by Johann009** [comment]
I find the way !!
Extenstions > Manage > Discover > Find the plugin > Install
So I installed the invisible recaptcha plugin on my contact form and it works fine.
the problem is with the form of the acymailing component (subsribe to my newsletter) on the same page : the invisible recaptcha conflicts with the invisible recaptcha in the contact form. The answer is: "The form could not be submitted Error: reCAPTCHA has already been rendered in this element"
How to have 2 invisible captchas recaptcha on the same page?

**Comment by Quy** [comment]
Please ask help in Joomla Forum. https://forum.joomla.org/
