### ISSUE TITLE
[4.0] Custom Field Image List missing Alt Tag

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#29640]
### Steps to reproduce the issue
Create a Custom Field of type Image List

### Expected result
To see an option to add an Alt tag

### Actual result
None available

![image-list](https://user-images.githubusercontent.com/36987494/84786161-4861e180-afe4-11ea-8484-b471d4bbe045.jpg)

### System information (as much as possible)
Joomla 4 Alpha

### Additional comments
The missing Alt tag for the Custom Field of type "Image URL (Media)" was addressed in PR [4.0] Media fields accessibility - second try (#27712), but doesn't include "Image List" field.

**Comment by Scrabble96** [comment]
Hi. Can anyone address this? I couldn't begin to add code, but whoever did PR #27712 should be able to do this. Thanks.

**Comment by richard67** [comment]
@astridx Could you have a look on this issue? Thanks in advance. If you know how to solve it but don'tg have the time, let me know, then I can try or we find someone.

**Comment by astridx** [comment]
@richard67 I've seen it before. I think that the media field should be swapped with the accessible media field. But it takes a lot of work and I don't have the energy for it at the moment.

**Comment by richard67** [comment]
Ah, I remember, the accessible media field ... we have to find someone who has the time and mood.

**Comment by brianteeman** [comment]
This can be closed as it was resolved elsewhere

**Comment by richard67** [comment]
Closing as stated above.
