### ISSUE TITLE
[4.0] Max Impressions of Banner is Exceeded

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29651]
### Steps to reproduce the issue

Joomla 4 beta 1  

create a banner
Configure it with a max impressions of "1" 
save and publish it using a banner module
refresh the page you published it on - note that it loads twice before disappearing. 

### Expected result

Banner should load "1" time

### Actual result

Banner loads "2" times before being disabled as evidenced by you seeing it twice and the "Total Impressions" being `2` in admin

<img width="1584" alt="Screenshot 2020-06-16 at 22 52 30" src="https://user-images.githubusercontent.com/400092/84831886-13757f00-b024-11ea-9177-a7f8325587b1.png">

### System information (as much as possible)

Safari on Mac.
Possibly a Joomla 3 bug as well, but Im only testing Joomla 4 

### Bonus while you are there.

Add a space before `Unlimited`

<img width="253" alt="Screenshot 2020-06-16 at 22 56 27" src="https://user-images.githubusercontent.com/400092/84832143-9e567980-b024-11ea-87e5-4fb29d5abc88.png">

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29664 (for staging).
