### ISSUE TITLE
[4.0] TinyMCE console.log SyntaxErrors in Safari 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29659]
### Steps to reproduce the issue

Install Joomla 4 beta 1 

Go to the create new article screen

### Expected result

No console log errors

### Actual result

TinyMCE still seems to load, but with SyntaxErrors logged

<img width="1027" alt="Screenshot 2020-06-17 at 00 03 14" src="https://user-images.githubusercontent.com/400092/84836603-f8a80800-b02d-11ea-958f-1d21a21e06a4.png">

(Ignoring the ones from select-bg.svg as that's in https://github.com/joomla/joomla-cms/issues/29658)

### System information (as much as possible)

<img width="352" alt="Screenshot 2020-06-17 at 00 03 57" src="https://user-images.githubusercontent.com/400092/84836629-0c536e80-b02e-11ea-87aa-f315f636c0c8.png">

**Comment by infograf768** [comment]
Can't reproduce with Safari 12.1.2

**Comment by PhilETaylor** [comment]
Fresh install this morning from 4.0-dev @ e375092c22eac9bdd8bca3b26578c4e2e7e601ec gives the same issue

<img width="1498" alt="Screenshot 2020-06-17 at 10 06 21" src="https://user-images.githubusercontent.com/400092/84878814-3fbfe880-b082-11ea-9f05-99fe09e81685.png">

**Comment by infograf768** [comment]
Yep, but not on my older version of safari. :) Here I only have the svg issue.

**Comment by PhilETaylor** [comment]
Correct.

<img width="1603" alt="Screenshot 2020-06-17 at 10 10 55" src="https://user-images.githubusercontent.com/400092/84879244-dc828600-b082-11ea-9196-0ac27f1df578.png">

**Comment by infograf768** [comment]
Note: svg issue solved in https://github.com/joomla/joomla-cms/pull/29675

**Comment by PhilETaylor** [comment]
The other errors is probably a `won't fix` as its a TinyMCE emitted error?... and when I go to https://www.tiny.cloud/docs/demo/full-featured/ in Safari 13.1.2 I get 

<img width="1601" alt="Screenshot 2020-06-17 at 11 11 39" src="https://user-images.githubusercontent.com/400092/84885750-60d90700-b08b-11ea-92cd-a656ecb41d87.png">

I'll maybe report it upstream at TinyMCE

**Comment by infograf768** [comment]
Please do report.
