### ISSUE TITLE
[4.0] when error message in admin with &tmpl=component the menu is still shown

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29655]
### Steps to reproduce the issue

reproduce an error in Joomla 4 admin (use https://github.com/joomla/joomla-cms/issues/29654 for now, which generates a url of http://127.0.0.1:8400/administrator/index.php?option=com_contenthistory&view=preview&layout=preview&tmpl=component&0ccff38d01deb02be4cacd7ccf11fd3f=1&version_id=21 - dust your token to suit) 

### Expected result

Because the url has `&tmpl=component` in it, the error page should not have the menu/toolbars etc as `&tmpl=component`  should render (what I shall call) chrome-less. 

### Actual result

<img width="1044" alt="Screenshot 2020-06-16 at 23 07 58" src="https://user-images.githubusercontent.com/400092/84833457-3b1a1680-b027-11ea-918c-43234e473de4.png">

**Comment by SharkyKZ** [comment]
We don't have a separate template file for this.

**Comment by PhilETaylor** [comment]
should there be? or is this a `won't fix` ?

**Comment by brianteeman** [comment]
can this be re-opened please as it really should be fixed
