### ISSUE TITLE
[4.0] User Notes, Version Note field doesnt save/persist

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29657]
### Steps to reproduce the issue

Create a new user note for a user in Joomla 4 admin 

enter text in the `Version Note` field

Click save

### Expected result

The value persists/stored

### Actual result

The value doesnt persist in the form, the field is now blank
![Screen Recording 2020-06-16 at 11 40 PM](https://user-images.githubusercontent.com/400092/84835165-e4164080-b02a-11ea-92b3-47a81b71f8ff.gif)

### System information (as much as possible)

safari on Mac
not tested on Joomla 3 but might be there too

**Comment by PhilETaylor** [comment]
The Version Note in Articles is also not saving...

**Comment by SharkyKZ** [comment]
>The value doesnt persist in the form, the field is now blank

This is expected. The note is cleared so it wouldn't be automatically used for new revision.

**Comment by brianteeman** [comment]
@SharkyKZ is correct - this is intended and expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29657">issues.joomla.org/tracker/joomla-cms/29657</a>.</sub>
