### ISSUE TITLE
[4.0] Accessibility: speech to text isn't supported in this browser or in http protocol (https required)

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29650]
### Steps to reproduce the issue

Joomla 4.0.0 beta 1 - enabled plugin `System - Additional Accessibility Features` 

Visit frontend
Enable `Text To Speech` in the Accessibility fly-in menu

### Expected result

either 
1) the console warning is correct and it doesnt work 
or 
2) no console warning

### Actual result

I get the console warning 

>Accessibility: speech to text isn't supported in this browser or in http protocol (https required)

However Im **not on https** and text to speech is working fine! (Both browsers below) 

### System information (as much as possible)

Google Chrome on Mac

<img width="1592" alt="Screenshot 2020-06-16 at 22 03 38" src="https://user-images.githubusercontent.com/400092/84828007-3ea8a000-b01d-11ea-9e99-b95b034b9333.png">

AND
Safari on Mac

<img width="848" alt="Screenshot 2020-06-16 at 22 03 25" src="https://user-images.githubusercontent.com/400092/84827990-394b5580-b01d-11ea-8208-4ee3c97057d2.png">

**Comment by brianteeman** [comment]
"speech to text" and "text to speech" are not the same thing ;)

**Comment by PhilETaylor** [comment]
console.log warnings of any type have no place on a live site. This plugin is full of bugs it seems.

**Comment by brianteeman** [comment]
it is working correctly. it is not a bug. it is correctly telling you that speech to text is not available to you. what you have working is text to speech

**Comment by PhilETaylor** [comment]
Outputting of console.log warnings on a live site is a bug. IMHO but I know you dont care.
