### ISSUE TITLE
[4.0] Deleting selected versions appears to delete ALL version (phew it did not)

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29653]
### Steps to reproduce the issue

Joomla 4 beta 1

Edit an article and click save multiple times to create `Versions` of the article. 

Click Versions button.

Modal appears.

Select some (not all) versions

Click delete

### Expected result

Selected items are deleted

### Actual result

It appears ALL are deleted at first glance!!!!!
Refreshing the page manually the non-selected ones reappear. Phew. 

![Screen Recording 2020-06-16 at 11 02 PM](https://user-images.githubusercontent.com/400092/84832661-9c40ea80-b025-11ea-80bc-c7ad13c5dd82.gif)

### System information (as much as possible)

safari on Mac

**Comment by SharkyKZ** [comment]
Please test PR #29663.
