### ISSUE TITLE
[4.0] Safari bugs with chosen images/select-bg.svg

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29658]
### Steps to reproduce the issue

Install Joomla 4.0.0 beta 1

Go to add a new article screen in SAFARI ON MAC

### Expected result

No console errors 
Category and Tags to be looking the same as google chrome and have dropdown arrows

### Actual result

Google Chrome on LEFT Safari on RIGHT of this image:

<img width="957" alt="Screenshot 2020-06-16 at 23 58 07" src="https://user-images.githubusercontent.com/400092/84836285-5b4cd400-b02d-11ea-9650-fe9f39a4ac6a.png">

Error messages in safari console log:

<img width="1101" alt="Screenshot 2020-06-16 at 23 59 08" src="https://user-images.githubusercontent.com/400092/84836304-67389600-b02d-11ea-9f0e-c467958e34de.png">

Note that chrome is looking for the same SVG in a different place - and finding it there:

`/administrator/templates/atum/images/select-bg.svg`

### System information (as much as possible)

As explained above

**Comment by infograf768** [comment]
Confirmed. release blocker.

**Comment by PhilETaylor** [comment]
Confirmed in "current" Safari version too (as my safari is "next" version due to beta schedule on Mac) 

<img width="1603" alt="Screenshot 2020-06-17 at 10 10 55" src="https://user-images.githubusercontent.com/400092/84879352-02a82600-b083-11ea-8d27-1cd4047e1f5a.png">


<img width="570" alt="Screenshot 2020-06-17 at 10 12 25" src="https://user-images.githubusercontent.com/400092/84879393-10f64200-b083-11ea-8b54-dbca058126c9.png">

**Comment by infograf768** [comment]
I found the issue:
Safari does not like that both background color AND url are in the same line
`background: var(--atum-bg-light) url(../../../images/select-bg.svg) no-repeat 100%/116rem;`
If you delete `var(--atum-bg-light)` the svg will display

**Comment by infograf768** [comment]
making patch now to separate color and image.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/29675 as it seems not so many people use Mac and safari.

**Comment by PhilETaylor** [comment]
> Please test #29675 as it seems not so many people use Mac and safari.

Crazy isn't it... I have seven browsers installed and a whole suite of browsers in my browserstack.com account... seems people just dont like to test in anything other than Google Chrome nowadays...
