### ISSUE TITLE
[4.0] View versions gives Call to a member function load() on bool

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29654]
### Steps to reproduce the issue

Joomla 4 beta 1 
Create an article and create loads of versions by clicking save many times
Click versions button 
Click on a date/time 
Note New window popup 

### Expected result

New window displays details of the article

### Actual result

New window displays an error message

`Call to a member function load() on bool`

<img width="1044" alt="Screenshot 2020-06-16 at 23 07 58" src="https://user-images.githubusercontent.com/400092/84833004-3bfe7880-b026-11ea-9fc4-68c158c3390f.png">

**Comment by PhilETaylor** [comment]
can be replicated at made up url:

`/administrator/index.php?option=com_contenthistory&view=preview&layout=preview&tmpl=component&version_id=`

**Comment by SharkyKZ** [comment]
Can you test on git clone or latest nightly? https://github.com/joomla/joomla-cms/pull/29326 might have fixed this.

**Comment by PhilETaylor** [comment]
tested on e375092c22eac9bdd8bca3b26578c4e2e7e601ec and the problem remains, only difference this morning is the left menu in the popup is collapsed on load

<img width="1363" alt="Screenshot 2020-06-17 at 09 57 21" src="https://user-images.githubusercontent.com/400092/84877893-f9b65500-b080-11ea-8681-3dbf2e91323f.png">

**Comment by SharkyKZ** [comment]
I can't reproduce the issue. Can you enable debug and post the stack trace?

**Comment by PhilETaylor** [comment]
Today on 50ef84d184722f0584de3f14ee2d18c61ff38f4f

Installed Joomla from scratch with no crazy changes to setting,  - no sample data

Logged into admin 

Went straight to 

> http://127.0.0.1/administrator/index.php?option=com_contenthistory&view=preview&layout=preview&tmpl=component&version_id=

and replicated the error - enabled debug mode and error reporting = development and get:

<img width="1517" alt="Screenshot 2020-06-18 at 16 20 49" src="https://user-images.githubusercontent.com/400092/85039714-e807a700-b17f-11ea-8d22-c0dbfdeccd4b.png">

**Comment by PhilETaylor** [comment]
`$typesTable` is false...

```php
public static function prepareData(ContentHistory $table)
	{
		$object = static::decodeFields($table->version_data);
		$typesTable = Table::getInstance('Contenttype', 'Joomla\\CMS\\Table\\');
		$typeAlias = explode('.', $table->item_id);
		array_pop($typeAlias);
		$typesTable->load(array('type_alias' => implode('.', $typeAlias)));
		$formValues = static::getFormValues($object, $typesTable);
		$object = static::mergeLabels($object, $formValues);
		$object = static::hideFields($object, $typesTable);
		$object = static::processLookupFields($object, $typesTable);

		return $object;
	}
```

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29692.
