### ISSUE TITLE
[4.0] Accessibility Menu loads in Modal

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29652]
### Steps to reproduce the issue

Joomla 4.0.0 beta 1 - enabled plugin `System - Additional Accessibility Features` 

Edit an article 

Click versions

### Expected result

One accessibility icon in the main screen 
No accessibility icon in the modal

### Actual result

accessibility icon in the modal
accessibility icon in the main screen

<img width="633" alt="Screenshot 2020-06-16 at 23 00 50" src="https://user-images.githubusercontent.com/400092/84832556-6996f200-b025-11ea-8678-4fd9ff8262a4.png">

### System information (as much as possible)

Safari on mac

**Comment by brianteeman** [comment]
Nothing to do with the accessibility plugin. Debug plugin does exactly the same as well. Probably all system plugins do.

**Comment by PhilETaylor** [comment]
Just because they do - doesn't mean they should. 

And no, not all of them do, because its a modal, and thus the plugin should respect the `&tmpl=component` part of the url and not load. 

Unless you can give me a reason why this plugin needs to be loaded in the modal a second time?

**Comment by PhilETaylor** [comment]
Now its screwed... 

<img width="476" alt="Screenshot 2020-06-16 at 23 34 57" src="https://user-images.githubusercontent.com/400092/84834855-3d31a480-b02a-11ea-8bea-8a3ae04f1372.png">

**Comment by PhilETaylor** [comment]
and now I have two different icons in the same browser at the same time ... 

<img width="715" alt="Screenshot 2020-06-16 at 23 36 58" src="https://user-images.githubusercontent.com/400092/84834879-4de21a80-b02a-11ea-907b-499707d414dc.png">

**Comment by Quy** [comment]
PR #31863
