### ISSUE TITLE
[4.0] Field validation doesnt show help on category 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29662]
### Steps to reproduce the issue

Joomla 4 - user notes -> New

Just hit save.

NOTE that the User is RED and a help text of `Please fill in this field` is shown.
NOTE category is still blue and no help text

Select a user.
Click save

Note the global error at the top of the page, it doesnt say WHICH field so now we go hunting for tiny asterisks (which we assume to be meaning "required" as there is no *=required key in Joomla ;-) 

Note category is STILL NOT RED, and no help text. 

![Screen Recording 2020-06-17 at 12 31 AM](https://user-images.githubusercontent.com/400092/84838489-7a019980-b032-11ea-9bfc-67bb8e1cd234.gif)

### Expected result

Category would be red and would have a help text of `Please fill in this field` like the user field did.

### Actual result

as above.

### System information (as much as possible)

safari on Mac

### Additional comments

Compare this with the (working) field highlighted on a submission of a new user

<img width="951" alt="Screenshot 2020-06-17 at 00 35 10" src="https://user-images.githubusercontent.com/400092/84838486-779f3f80-b032-11ea-8fb6-a4bc3f9625c7.png">

**Comment by paternax** [comment]
It is quite strange. The field were the cursor was located last, gets this green border. In my example the version note and not the field with the required input.![screen shot 2020-08-21 at 14 50 08](https://issues.joomla.org/uploads/1/f5ffe40fd4592376b8b4a95bbabd8eae.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29662">issues.joomla.org/tracker/joomla-cms/29662</a>.</sub>

**Comment by alikon** [comment]
please test #30612

**Comment by infograf768** [comment]
Reopening as prposed pr is wrong
