### ISSUE TITLE
Profile Edit page BUG

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#29661]
Hi guys, 
PHP 7.3.18 + Joomla 3.9.19

I'm having back an Alert BUG:
--- With default Joomla "System - Privacy Consent" plugin enabled - Existing users who have not consented yet will be redirected on login to update their profile and check the privacy consent
--- So, when I login, I'm redirected to the edit profile page
--- The Edit Profile page is opened with an Info Alert: "Please, confirm that you accept the Privacy Policy"
--- BUG: that Alert is white because an inexistent **alert-notice** class has assigned https://photos.app.goo.gl/yFe1d3jtppnsQZS3A > while it should be **alert-info**

Please, Can you replicate it ?
Please, on Which file can I fix it ?

**Comment by Quy** [comment]
This is not a core issue. Please contact the template provider or ask help at Joomla Forum. https://forum.joomla.org/

**Comment by SharkyKZ** [comment]
You'll need to create a layout override of `layouts/joomla/system/message.php` for your template. The default Protostar template also comes with such override, you can use it as example https://github.com/joomla/joomla-cms/blob/6e82ccacbdf013535493d657dbab1a39e562e2c7/templates/protostar/html/layouts/joomla/system/message.php.

**Comment by joomleb** [comment]
Hi @SharkyKZ 
many thanks to your suggestion I found the BUG and I reported its solution here in the Helix Ultimate project:
https://github.com/JoomShaper/helix-ultimate/issues/84
(bringing it back here as a form of education and thanksgiving)
