### ISSUE TITLE
[4.0] Strange body right padding/margin on admin panel main page on mobile device

### ISSUE THREAD

**Issue by AndNovAtor** [joomla/joomla-cms#29673]
### What needs to be fixed
Strange body right padding on admin panel main page on mobile device, for example, on Android 9 [Samsung A8] in Chrome, with clear Joomla 4 Beta 1

![joomla4_admin_main_0](https://user-images.githubusercontent.com/3628514/84877784-9aad0c00-b091-11ea-8cd4-c90200bca671.jpg)
![joomla4_admin_main_1](https://user-images.githubusercontent.com/3628514/84877791-9c76cf80-b091-11ea-9fec-7ee28d252690.jpg)
![joomla4_admin_main_2](https://user-images.githubusercontent.com/3628514/84877796-9da7fc80-b091-11ea-8230-9399aabc4843.jpg)

### Why this should be fixed
It's not normal

### How would you fix it
Maybe some modules min size is root cause?

### Side Effects expected
\-

**Comment by ghost** [comment]
Can't confirm.
