### ISSUE TITLE
[com_contenthistory] Multiple unhandled PHP notices when ids dont exist

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29678]
### Steps to reproduce the issue

af6eddfa0a3bd1d85c9964c25d21b706c64993a4

Go to faked admin url: 
http://127.0.0.1/administrator/index.php?option=com_contenthistory&view=compare&layout=compare&tmpl=component&cb519da4124ac219494e83630c56cb09=1&id1=&id2=

<img width="1171" alt="Screenshot 2020-06-17 at 12 10 28" src="https://user-images.githubusercontent.com/400092/84891305-8ec24980-b093-11ea-8177-fd444ae41da6.png">

or http://127.0.0.1/administrator/index.php?option=com_contenthistory&view=compare&layout=compare&tmpl=component&cb519da4124ac219494e83630c56cb09=1&id1=1&id2=

<img width="1206" alt="Screenshot 2020-06-17 at 12 10 46" src="https://user-images.githubusercontent.com/400092/84891349-a26db000-b093-11ea-9437-bf79874f93ec.png">

**Comment by Hackwar** [comment]
Since this wasn't mentioned, I'm deducting that this is an issue on J4.0

**Comment by PhilETaylor** [comment]
Yes joomla 4 - sorry - was a late night 

Might exist on joomla 3 but never tested

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29683 (for staging).
