### ISSUE TITLE
[4.0] On mobile, change to the same category/click on category "input" of new article causes page reload

### ISSUE THREAD

**Issue by AndNovAtor** [joomla/joomla-cms#29671]
### Steps to reproduce the issue

1. Install "clear" Joomla 4.0 Beta 1
2. Open admin panel on mobile device
3. "Add new article"
4. Scroll down where article category dropdown shows "Uncategorized"
5. Click on it (not on arrow)

### Expected result

Categories dropdown shows

### Actual result

Page suddenly reloads

### System information (as much as possible)

Server:
Windows 10 x64
Nginx 1.17+Apache 2.4
PHP 7.3 x64
Joomla 4.0 Beta 1

Mobile browser:
Android 9
Chrome 

### Additional comments
If it isn't bug, it's strange

P.s. - pls, change my issue title if necessary. Sorry for my English

![joomla4_beta_newarticle_1](https://user-images.githubusercontent.com/3628514/84875182-4a807a80-b08e-11ea-9d83-03403bea672e.jpg)
![joomla4_beta_newarticle_2](https://user-images.githubusercontent.com/3628514/84875188-4ce2d480-b08e-11ea-958d-f7192df13952.jpg)
![joomla4_beta_newarticle_3](https://user-images.githubusercontent.com/3628514/84875312-7ac81900-b08e-11ea-809c-ad3d406566cd.jpg)

**Comment by Hackwar** [comment]
This is not the case anymore. Still thank you for reporting this. Closing this issue.
