### ISSUE TITLE
Release Blocker

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#29674]
### Problem identified
There is considerable inconsistency in when the release blocker tag is added to an issue. This devalues the use of the term and steers contributors away from certain issues in favour of those with the release blocker tag

### Proposed solution
Establish a set of criteria to be used.

### Open questions
What should the criteria be? I would suggest basing them on the existing https://docs.joomla.org/Bug_and_Issue_Tracker_Priority

So for example a css error in a specific browser could never be a release blocker
But a delete button not working could be a release blocker (depending on where)

**Comment by richard67** [comment]
Ping @wilsonge .

**Comment by infograf768** [comment]
> So for example a css error in a specific browser could never be a release blocker

Disagree: we have many issues for example with Safari. We can't obviously release J4 if Safari is unusable.

**Comment by brianteeman** [comment]
None of them have made joomla unusable

**Comment by brianteeman** [comment]
Closed due to lack of response - guess no one is interested
