### ISSUE TITLE
[4.0] Mouseover cursor incorrect on tags 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29677]
### Steps to reproduce the issue

tested on Joomla 4.0-dev @ af6eddfa0a3bd1d85c9964c25d21b706c64993a4

Hover over the dropdown toggles on the fields in admin when creating an article

Note that tags dropdown toggle is different to all the rest

### Expected result

hover should give pointer like the others

### Actual result

![Screen Recording 2020-06-17 at 11 53 AM](https://user-images.githubusercontent.com/400092/84889713-3722de80-b091-11ea-9a31-1674190afbb5.gif)

### System information (as much as possible)

Safari on Mac.

**Comment by Quy** [comment]
Please test PR #29682
