### ISSUE TITLE
If you have more tabs in  than screen width is, the tabs will be hidden

### ISSUE THREAD

**Issue by hotthemes** [joomla/joomla-cms#29676]
### Steps to reproduce the issue
Make a module or template with a lot of tabs (sections of parameters).
Use a smaller screen.

### Expected result
The tabs should wrap to the next line when they reach the end of the screen.

### Actual result
The tabs are hidden.

### System information (as much as possible)
Joomla ‎4.0.0-beta2-dev

### Additional comments
It can be fixed in CSS with:

joomla-tab>ul {
  flex-wrap: wrap;
}

**Comment by Quy** [comment]
Duplicate #28799
