### ISSUE TITLE
[4.0] When debug=true enabled, console.log errors about missing map files

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29679]
### Steps to reproduce the issue

af6eddfa0a3bd1d85c9964c25d21b706c64993a4
Enabled `	public $debug = true;`	in global config

load any page

### Expected result

No JS Errors in console

### Actual result

<img width="1594" alt="Screenshot 2020-06-17 at 12 18 15" src="https://user-images.githubusercontent.com/400092/84891959-a6e69880-b094-11ea-9fc2-beebd1ad4fc4.png">

### System information (as much as possible)

Safari on Mac

**Comment by PhilETaylor** [comment]
Google Chrome only

172.23.0.1 - - [09/Jul/2020:11:02:37 +0000] "GET /media/vendor/bootstrap/js/bootstrap.bundle.js.map HTTP/1.1" 404 8150 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
172.23.0.1 - - [09/Jul/2020:11:02:37 +0000] "GET /media/vendor/metismenujs/js/metismenujs.js.map HTTP/1.1" 404 8146 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"

<img width="659" alt="Screenshot 2020-07-09 at 11 53 55" src="https://user-images.githubusercontent.com/400092/87032260-40105700-c1dc-11ea-9cf5-97cbcfc3376d.png">

**Comment by brianteeman** [comment]
This has been resolved elsewhere and can be closed
