### ISSUE TITLE
[4.0] Unused string JHELP_ADMIN_USER_PROFILE_EDIT="Site_My_Profile" 

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#29687]
### Steps to reproduce the issue

Search all php and ini files for JHELP_ADMIN_USER_PROFILE_EDIT

### Expected result

Find a use in a php file

### Actual result

No php file contains this string.

### Additional comments

Replaced by JHELP_USERS_USER_MANAGER_EDIT

**Comment by infograf768** [comment]
There is a PR to reinstate edit profile. See https://github.com/joomla/joomla-cms/pull/29251
Let's see if we will need it again.

**Comment by richard67** [comment]
Yes, and that PR #29251 will use the string here:

https://github.com/joomla/joomla-cms/pull/29251/files#diff-86848cfa928aaf66451d294946d57b53R120

**Comment by richard67** [comment]
@infograf768 So what to do with this issue? Close? Or leave open until PR #29251 will be merged?

**Comment by infograf768** [comment]
imho wait

**Comment by ceford** [comment]
If I login as an admin in the Manager group I get this when I select Edit Account:
An error has occurred.
403 You don't have permission to access this. Please contact a website administrator if this is incorrect.
So that is a bug. And I could see that a separate Help screen may be needed when that gets fixed.

See also:
https://help.joomla.org/proxy?keyref=Help40:Site_My_Profile&lang=en
https://help.joomla.org/proxy?keyref=Help40:Users_User_Manager_Edit&lang=en

**Comment by Quy** [comment]
@ceford #29251 fixes the edit account issue for manager group.

**Comment by Quy** [comment]
#29251 Merged.
