### ISSUE TITLE
Use Statement For Non-Existing Class In Joomla\CMS\Form\Form

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#29680]
See https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Form/Form.php#L13, there is no class in Joomla 3.9 with this name.

The import can be misleading to developers as it implies a feature is intended for use in the class but since the class does not exist it can create confusion.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29684.
