### ISSUE TITLE
[4.0] Showon doesn't work with new items in a subform field

### ISSUE THREAD

**Issue by tassosm** [joomla/joomla-cms#29690]
### Steps to reproduce the issue
Use the following subform field in a form

```
<field name="field-name" type="subform"
    label="Subform Field"
    multiple="true">
    <form>
        <field name="fieldx" type="list"
            label="Foo">
            <option value="0">No</option>
            <option value="1">Yes</option>
        </field>
        <field name="fieldy" type="text"
            label="Example Text"
            showon="fieldx:1"
        />
    </form>
</field>
```
Click to add a new item

### Expected result
fieldy must show up only when we select Yes in fieldx 

![Peek 2020-06-18 19-03](https://user-images.githubusercontent.com/6807469/85044588-8141b800-b196-11ea-8d6e-6452b52d5b3e.gif)

### Actual result
fieldy shows up and ignores the showon rule.

**Comment by chmst** [comment]
Close this as there is a PR
