### ISSUE TITLE
[4.0] W3C Web Authentication (WebAuthn) Login layout

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29699]
### Steps to reproduce the issue

Visit Joomla 4 user edit page on a SSL url

Visit the `W3C Web Authentication (WebAuthn) Login` tab

### Expected result

The layout not to be bunched up into a small column 

### Actual result

This screenshot is half of my 27 inch iMac screen so approx 1600x1600px 

So much wasted whitespace :) 

The fieldset title `W3C Web Authentication (WebAuthn) Login` is immediately duplicated underneath and split into two lines

The `Authenticator added on 2020-06-18 20:24:16` is wrapped 

Remove icon appears larger than the edit button

The edit icon is bunched up to the word Edit

The information is wrapped below. 

<img width="1595" alt="Screenshot 2020-06-18 at 21 27 54" src="https://user-images.githubusercontent.com/400092/85068669-b7893280-b1aa-11ea-83b9-86f245055204.png">

**Comment by ghost** [comment]
Click `User Menu`> `Edit Account` show:

![image](https://user-images.githubusercontent.com/70466955/93706158-d7225500-fb23-11ea-897b-b5e40dfa785c.png)

**Comment by PhilETaylor** [comment]
I think Nic fixed this one without referencing this issue. So I'll close now.
