### ISSUE TITLE
[4.0][WebAuthn] Cannot add two keys in succession

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29697]
### Steps to reproduce the issue

Joomla 4 ON A SSL URL - login as admin and go to your account using the menu link top right

Click `W3C Web Authentication (WebAuthn) Login` Tab

Click Add New Authenticator - Touch your first hardware key

Click Add new authenticator 

### Expected result

Another popup to allow me to add another key

### Actual result

Nothing happens on the second click of the green button - keep pressing it, nothing happens.

Do a hard page refresh - then the add new authenticator button works again

### System information (as much as possible)

Safari on Mac

**Comment by PhilETaylor** [comment]
paging @nikosdion

**Comment by nikosdion** [comment]
This is because of the JavaScript refactoring. Just like 29701. I will make a new PR for all issue, there's no point in wasting my time doing it piecemeal. That's what you get when the project blindly merges stuff without testing :@

**Comment by PhilETaylor** [comment]
I tested when I was asked to test ;) I just report what I find ;-) Thanks Nic.

**Comment by nikosdion** [comment]
It's not your fault. The code I contributed was working fine. However, just before the beta a lot of bad merges without testing happened. The implementation of login buttons was broken, the JavaScript was ref@#!ktored and WebAuthn worked no more. I am frustrated that I have to spend time I don't really have to fix what other people broke. Oh, well, I guess it must be a day ending in "-y"...

**Comment by C-Lodder** [comment]
@nikosdion shall I just submit a PR reverting the JS changes?

**Comment by nikosdion** [comment]
Nope. It's not just your changes. It's also how @HLeithner changed my original ES5 to ES6. I have already submitted a PR to fix the remaining problems. I am frustrated because I had to essentially go through the entire plugin four times if you count the first time I tried to contribute it.

**Comment by PhilETaylor** [comment]
PR #29707
