### ISSUE TITLE
[4.0] TODO Abort if installer hash not validated 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29695]
### Steps to reproduce the issue

Not a bug - but on code review, this change should now be activated in Joomla 4 (according to the note) to increase the security of Joomla 4 and installing extensions. 

When installing an extension in Joomla 4 with an invalid hash, installation should "abort" apparently

```php
// The validation was not successful. Just a warning for now.
		// TODO: In Joomla 4 this will abort the installation
		if ($check === InstallerHelper::HASH_NOT_VALIDATED)
		{
			$app->enqueueMessage(Text::_('COM_INSTALLER_INSTALL_CHECKSUM_WRONG'), 'error');
		}
```

and 

```php
	// The validation was not successful for now just a warning.
		// TODO: In Joomla 4 this will abort the installation
		if ($result['check'] === false)
		{
			$message = Text::_('COM_JOOMLAUPDATE_VIEW_UPDATE_CHECKSUM_WRONG');
			$messageType = 'warning';

			try
			{
				Log::add($message, Log::INFO, 'Update');
			}
			catch (\RuntimeException $exception)
			{
				// Informational log only
			}
		}
```

### Expected result

Joomla 4 should "abort the installation"

### Actual result

Joomla 4 just shows a "a warning for now"

### Additional comments
@SniperSister

**Comment by alikon** [comment]
@PhilETaylor  can you give some feedback on #30076

**Comment by alikon** [comment]
@joomla/bug-squad  please don't close this one till #30076 is a draft

**Comment by richard67** [comment]
@alikon You mean "please don't close this one as long as #30076 is a draft", or in other words "please don't close this one till #30076 is not a draft anymore"?

**Comment by alikon** [comment]
the 1st ;)

> please don't close this one as long as #30076 is a draft

**Comment by richard67** [comment]
Both of my alternatives mean the same, but the opposite to what you wrote.

**Comment by alikon** [comment]
grr damned english

**Comment by richard67** [comment]
Chinese would be harder ;-)

**Comment by alikon** [comment]
let's close this one as #30076 is no more a draft pr
