### ISSUE TITLE
[4.0b1] form attribute hiddenLabel not working as expected

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#29709]
### Steps to reproduce the issue
add form attribute to a form field:

```
hiddenLabel="false"
```

### Expected result
the label for the field should be displayed

### Actual result
the label for the field is hidden

### Additional comments
this attribute only acts on if the attribute is set in the form, NOT what value is set. This prevents overwriting a form field that has the label hidden by default.

**Comment by Quy** [comment]
PR #29710
