### ISSUE TITLE
[4.0][WebAuthn] Edit button on frontend is white with a white icon

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29700]
### Steps to reproduce the issue

Joomla 4 ON A SSL URL - login as a user on the FRONTEND

### Expected result

icon and background of button not same colour in Joomla default template

### Actual result

<img width="1030" alt="Screenshot 2020-06-18 at 21 45 37" src="https://user-images.githubusercontent.com/400092/85070055-0f289d80-b1ad-11ea-94e0-8c2ad7b6d058.png">

### System information (as much as possible)

safari on Mac

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/29704
