### ISSUE TITLE
[4.0] Not a valid header value 

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#29712]
### Steps to reproduce the issue
Go to Content Dashboard
Click cog icon to edit a module
Click Save & Close

### Actual result
> "500 "http://localhost/joomla-cms-4.0-dev/administrator/index.php�[ۏX��W��[�[ ��Y]�X�[�[ �\���\�X�۝[�" is not valid header value" is not valid header value

### System information (as much as possible)
Beta 2

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29714.
