### ISSUE TITLE
[4.0] Fix string in  Plugins: Extension - Namespace Updater

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#29725]
### Steps to reproduce the issue

Go to 
Plugins: Extension - Namespace Updater

### Expected result

Text should say:
Automatically builds and updates the administrator/cache/autoload_psr4.php file that is used to autoload extensions.

### Actual result

Text actually says:
Automatically builds and updates the libraries/autoload_psr4.php file that is used to autoload extensions.

### Additional comments

autoload_psr4.php has moved

**Comment by brianteeman** [comment]
good spot

see #29726

**Comment by richard67** [comment]
Closing as having a pull request. Please test #29726 .
