### ISSUE TITLE
[4.0] Wrong / Missing Help String for Sample Data Module

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#29729]
### Steps to reproduce the issue

Go to Modules -> Sample Data and click the Help button

### Expected result

The Help screen should be for this module

### Actual result

The Help screen is for Latest Articles

### Additional comments

The string in mod_sampledata/mod_sampledata.xml is JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_LATEST
I have created the required new help page - it uses JHELP_EXTENSIONS_MODULE_MANAGER_SAMPLE_DATA
In joomla.ini the translation needs to be Extensions_Module_Manager_Sample_Data
I have checked locally that this works

**Comment by brianteeman** [comment]
Thanks - PR to test #29730
