### ISSUE TITLE
[4.0] Captcha appears behind right column modules

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#29722]
### Steps to reproduce the issue

Get Captcha V3 API keys and set one or more domains - I added localhost for testing
Enable Plugin Captcha - Invisible reCAPTCHA - use the keys and select Bottom right position.
In Global configuration set this as the default capture
In the Site select the link to Create an account. 
The Captcha symbol appears at the bottom right.

### Expected result

Nice layout.

### Actual result

The Captcha symbol has a slider - it goes beneath the module boxes in the right column. 

![screen shot 2020-06-20 at 09 52 35](https://issues.joomla.org/uploads/1/650ba63207e56d4ffc8547d8de7ad057.png)

If positioned at the bottem left it goes above the boxes.

### System information (as much as possible)

Firefox and Chrome on Mac OSX Catalina

**Comment by PhilETaylor** [comment]
> Get Captcha V3 API keys

You mean v2 surely? Joomla doesnt support ([or want to support](https://github.com/joomla/joomla-cms/issues/29336)) v3

**Comment by ceford** [comment]
The link to get keys in the Invisible Captcha plugin leads to Captcha V3. A Google redirect? I did not notice that at the time so got V3 keys for testing. I have only ever used V1 and V2 before so don't know the pros and cons of V3. I did not know of the previous discussion.

**Comment by PhilETaylor** [comment]
Correct - this link : 
<img width="1162" alt="Screenshot 2020-06-21 at 15 09 19" src="https://user-images.githubusercontent.com/400092/85226783-38c20e80-b3d1-11ea-9f57-57af74c9554d.png">

Is this link:
https://www.google.com/recaptcha

Which (currently) redirects to https://www.google.com/recaptcha/intro/v3.html

Maybe a better link would be https://developers.google.com/recaptcha/intro as that still allows seeing the older versions

**Comment by PhilETaylor** [comment]
I can confirm the slider for google goes behind the modules

![Screen Recording 2020-06-21 at 03 24 PM](https://user-images.githubusercontent.com/400092/85227145-6c059d00-b3d3-11ea-95ef-7678663c253f.gif)

**Comment by derKh4N** [comment]
so there is no solution to this problem as of now?

**Comment by Quy** [comment]
Please test PR #31454
