### ISSUE TITLE
[3.9] Error 403 on multilingual site after session time has expired, but remember me for the user was checked!

### ISSUE THREAD

**Issue by juuser99** [joomla/joomla-cms#29738]
### Steps to reproduce the issue
On multilingual site, login with "remember me" checked. 
Wait at least as many minutes as "session lifetime" in global settings.
Refresh the page, error 403 is displayed.
Refresh the page again, page is displayed as normal.

### Expected result
No error 403 after session time when "remember me" checked

### Actual result
Error 403

### System information (as much as possible)
Joomla 3.9.19, but problem exists also with older versions.

### Additional comments
Fix is here:
https://github.com/joomla/joomla-cms/commit/c7eab13a2f5851d1820bb9cc077eaa01b49d110a

Abstractmenu.php and remember.php need to be updated accordingly. Thius fixes issue for all my sites.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/21230

**Comment by richard67** [comment]
It seems that the issue has been solved meanwhile in J4. At least I got reported by @carlitorweb that it can not be reproduced anymore. Possibly it was solved with PR #30991 . So I'm closing this issue here. Feel free to reopen if you think this is wrong. Thanks @carlitorweb for checking.
