### ISSUE TITLE
[4.0] Webauthn Image missing on admin login screen

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29733]
### Steps to reproduce the issue

Access Joomla 4 over a SSL 
Go to /administrator/

### Expected result

The web authentication button has a SVG image before the text as per the HTML

```html
<button type="button" class="btn btn-secondary btn-block mt-4 plg_system_webauthn_login_button" data-webauthn-form="form-login" data-webauthn-url="https://63ed3465f24a.ngrok.io/administrator/index.php?3d507c383e47b5c680acae0417c95fea=1" title="Web Authentication" id="plg_system_webauthn-Aw2edsB6Pl3z-uibrG6pn">
									<img src="/media/plg_system_webauthn/images/webauthn-black.png" alt="Login without a password using the W3C Web Authentication (WebAuthn) standard in compatible browsers. You need to have already set up WebAuthn authentication in your user profile." class="icon" loading="lazy">								Web Authentication			</button>
```

### Actual result

<img width="497" alt="Screenshot 2020-06-21 at 13 01 04" src="https://user-images.githubusercontent.com/400092/85224062-77e76400-b3bf-11ea-810e-130c3549bea1.png">

### System information (as much as possible)

Safari on Mac 

<img width="417" alt="Screenshot 2020-06-21 at 13 03 12" src="https://user-images.githubusercontent.com/400092/85224078-92214200-b3bf-11ea-97c3-898f1d1013f6.png">

### Additional comments
// @nikosdion

**Comment by nikosdion** [comment]
This is a CSS issue. I don't touch that, I will only make it worse. @C-Lodder may I please make the bat signal, kind sir?

**Comment by PhilETaylor** [comment]
While I have you dressed in your Batman costume, it also appears the text is a different size/font? to the Log in button?

**Comment by C-Lodder** [comment]
Issue caused by this block of CSS: https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/scss/blocks/_login.scss#L38-L41

Remove it and the image shows correctly

**Comment by PhilETaylor** [comment]
> Remove it and the image shows correctly

And breaks a million other things? It feels like a trap, looks like that change was 16 months ago :-)

**Comment by C-Lodder** [comment]
Well as far as I can tell, there are no `<img>` elements inside the `.login` div, other than those used by WebAuthn, so removing it should be fine

**Comment by PhilETaylor** [comment]
From what I understand, the new onUserLoginButtons, there can be other buttons (and other buttons could have images) 

bad example 

![83941813-0ae8a180-a7f7-11ea-9f6a-c3c60a496679](https://user-images.githubusercontent.com/400092/85337669-cdfbfa80-b4d8-11ea-8daf-fab42f664671.png)

**Comment by N6REJ** [comment]
pr #31028
