### ISSUE TITLE
[4.0] Wrong / Missing Help String for Smart Search Statistics

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#29736]
### Steps to reproduce the issue

Go to Components -> Smart Search -> Statistics and click the Help button

### Expected result

A Help screen

### Actual result

An error message

### Additional comments

I have created the Help screen. joomla.ini needs this:
JHELP_COMPONENTS_FINDER_MANAGE_SEARCHES="Components_Finder_Manage_Searches"
I have tested it locally.

Sorry to find these missing strings one at a time!

**Comment by Quy** [comment]
Please test PR #29737
