### ISSUE TITLE
[4.0][a11y] Links in postinstallation messages are not suitable for colourblind

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#29744]
### Steps to reproduce the issue
Open post installation messages.
Links in texts of postinstallation messages are only marked with colour and have no textdecoration or iconand no title.

### Expected result
Links have either a icon or a text-decoration

### Actual result

![screen shot 2020-06-21 at 19 25 58](https://issues.joomla.org/uploads/1/6d1a7f7d347bd651c4dd62aacfa99f58.png)

### Additional comments
The links themselves sometimes come from files, of 3rd party extensions and are not generated by the core.
So if the provider of the extension does not add a title to the link, what can we do?

**Comment by carcam** [comment]
As this is our own screen, Atum is responsible of all the styling so we can probably fix not A11y implementations.

According to  https://webaim.org/techniques/hypertext/link_text it's not needed to underline the text, but we are missing the a:focus underline. So In general for the whole template we should add that styling.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29744">issues.joomla.org/tracker/joomla-cms/29744</a>.</sub>

**Comment by brianteeman** [comment]
No we do not need to add a:focus underline to every link in the template - thats plain wrong. 

You do not need a title for a link - in many cases this actually makes accessibility worse - we've discussed this before. see https://silktide.com/blog/i-thought-title-text-improved-accessibility-i-was-wrong/

Atum automatically applies the icon _only_ when the link opens in a new window/tab

**Comment by carcam** [comment]
Hi Brian,
Thank you very much for your reply.

I probably got overexcited to see that a:hover was applied to all the template and that's why I thought extending it would be a good idea. In any case, the recommendation is clear: All links should be recognizable onfocus or onhover, so I think it will be a good idea to add this. Obviously when there is a noticiable transition like a background change on hover, this will not be required.

I think we should apply the same behaviour to onfocus as we do for onhover.

PS: I agree with you Brian about the title thing. Also it's something we cannot easily control so I guess our best call is to leave it as it's and educate developers in good practices

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29744">issues.joomla.org/tracker/joomla-cms/29744</a>.</sub>

**Comment by brianteeman** [comment]
The links already have outline style when focussed

**Comment by carcam** [comment]
Do you mean Browser default thing:

<img width="712" alt="Captura de pantalla 2020-06-22 a las 17 21 30" src="https://user-images.githubusercontent.com/1695138/85305070-d3435000-b4ac-11ea-8989-42489c004b7a.png">

?

I guess, that makes sense.

**Comment by carcam** [comment]
Actually, keep checking on this and asked for some input by a user with color blindness and he cannot distinguish the links.

Then kept reading and found this:

> - The link text must have a 3:1 contrast ratio from the surrounding non-link text.
> - The link must present a "non-color designator" (typically the introduction of the underline) on both mouse hover and keyboard focus.

Contrast on between text and links in autum is 1.4:1 (https://webaim.org/resources/contrastchecker/?fcolor=173A65&bcolor=495057) so we do need to underline these links or increase color contrast among text and links.

**Comment by chmst** [comment]
Agree with the title. But if a colourblind comes to postinstall messages, he cannot see that some text is blue. So he does not try to focus there. I just tried with monochrome and here it is fine. We should have this also on the postinstall texts. ![screen shot 2020-06-22 at 15 38 58](https://issues.joomla.org/uploads/1/03c9a4d231eb920f53059bbf90a3faa8.png)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29744">issues.joomla.org/tracker/joomla-cms/29744</a>.</sub>

**Comment by brianteeman** [comment]
Guys you are both talking about different things at the same time.

@chmst is completely correct that the link is not distinguishable with normal text and  should have some styling other than colour. For example 
```
a{
text-decoration: underline
}
```

That is not what @carcam was saying. He was suggesting 
> All links should be recognizable onfocus or onhover, 

I pointed out that links were already "recognizable onfocus or onhover"

**Comment by carcam** [comment]
Sure I was!! I got lost in the specification and didn't notice the details till @chmst provided the explanatory screenshot.

We should underline for that specific part of the site so that links are correctly identified.

Thanks Brian!!

**Comment by brianteeman** [comment]
It's a fairly simple pr - looking forward to testing it

**Comment by ReLater** [comment]
Just as additional info: There's already a setting in user profile settings "Highlight links".

That sets

```
body.a11y_highlight a {
    padding: 3px;
    text-decoration: underline !important;
    border: 1px dotted #f00;
}
```

**Comment by PhilETaylor** [comment]
my point https://github.com/joomla/joomla-cms/issues/29344 was that "Red" was probably the wrong colour anyway, as its not bad or dangerous to "hide" these messages...

**Comment by PhilETaylor** [comment]
Also note that the messages are not limited to having just a red "Hide this message" button - but could have other buttons 

eg

<img width="874" alt="Screenshot 2020-07-04 at 13 07 12" src="https://user-images.githubusercontent.com/400092/86512146-58a4f980-bdf7-11ea-896e-266fa02d67c2.png">

**Comment by hans2103** [comment]
Created PR https://github.com/joomla/joomla-cms/pull/30207 to add underline to anchor by default

**Comment by chmst** [comment]
Closed as there is a PR
