### ISSUE TITLE
[4.0] Object of class Joomla\CMS\Feed\FeedLink could not be converted to string

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29740]
### Steps to reproduce the issue

Tested in Joomla 4 @ dea8aa6923cf7d8344041daa80414a7c19957fdb

Create a new site module of type "Feed Display" 

I used http://feeds.bbci.co.uk/news/world/rss.xml for my feed link

load the frontend of the site to view the feed 

(Set error reporting to maximum in global config to get stack trace) 

### Expected result

Feed loads

### Actual result

Object of class Joomla\CMS\Feed\FeedLink could not be converted to string

<img width="1604" alt="Screenshot 2020-06-21 at 18 19 55" src="https://user-images.githubusercontent.com/400092/85231020-d6c2d280-b3eb-11ea-99f8-5584f6356451.png">

(I love seeing the Symfony error pages in Joomla 👻)

**Comment by Quy** [comment]
Duplicate #29236
