### ISSUE TITLE
[4.0] Content Security Policy translations 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29748]
### Steps to reproduce the issue

`Content-Security-Policy (CSP)` is untranslated

note the hyphens 

### Expected result

??

### Actual result

Also I was unable to find the source of the translation with the non-hyphened version highlighted below, else I would have just PRed it to the other places. 

<img width="517" alt="Screenshot 2020-06-21 at 21 05 03" src="https://user-images.githubusercontent.com/400092/85234109-07623680-b403-11ea-8275-b247409f1b2f.png">

**Comment by SharkyKZ** [comment]
This was most likely done intentionally to prevent translation. It's not necessarily right, though.

@zero-24

**Comment by zero-24** [comment]
Correct this is expected behavior at this place.

**Comment by PhilETaylor** [comment]
So why have one way with hyphens and one without? Surely stick to one way or the other even if it’s not going to be translated?

**Comment by zero-24** [comment]
> So why have one way with hyphens and one without? Surely stick to one way or the other even if it’s not going to be translated?

Sorry i can not follow you?

**Comment by PhilETaylor** [comment]
The text on the TAB and the text on the fieldset both have hyphens

<img width="335" alt="Screenshot 2020-06-22 at 10 29 35" src="https://user-images.githubusercontent.com/400092/85271856-48922f00-b473-11ea-8739-f1c9e94b44ba.png">


The text on the field doesnt have hyphens 

<img width="238" alt="Screenshot 2020-06-22 at 10 29 43" src="https://user-images.githubusercontent.com/400092/85271868-4cbe4c80-b473-11ea-8b33-b5ff45edadd4.png">

**Comment by zero-24** [comment]
Yes because the texts on the fieldset comes from the XML file and the seccond one from a language string? The ``??`` vs. ``**`` is just showing when language debug is enabled right?

**Comment by PhilETaylor** [comment]
yes language debug is enabled in that screenshot 

I guess you need to choose one - and all three should be the same. It makes no sense to have 2 with hyphens and one not.

**Comment by zero-24** [comment]
> yes language debug is enabled in that screenshot

Yes that is the reason ;) Please disable language debug and check again.

The `??` vs `**` comes from whether that string is comming from the XML or via language string and is only showed in language debug.

**Comment by PhilETaylor** [comment]
> Yes that is the reason 

No its not. 

You dont seem to understand. 

Im not concerned now about `??` or `**` 

The Tab is `Content-Security-Policy (CSP)` with Hyphens `-` between the words 
The fieldset is `Content-Security-Policy (CSP)` with Hyphens `-` between the words 
The field label is `Content Security Policy (CSP)` with spaces ` ` between the words 

They should all be the same, either with or without spaces, either with or without Hyphens `-`

<img width="489" alt="Screenshot 2020-06-22 at 12 27 59" src="https://user-images.githubusercontent.com/400092/85282734-23f28300-b484-11ea-9396-b62934d3a49c.png">

**Comment by zero-24** [comment]
Ah ok sorry so it is good that i have asked. Can you give us the suggestion form a native speaker what to choose best here?

**Comment by brianteeman** [comment]
As a title it has no hyphen https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

As a response header it has a hyphen https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

So in this case none of the strings highlighted by Phil should be hyphenated.

**Comment by PhilETaylor** [comment]
RFC7762 uses spaces "Content Security Policy" throughout when using the term in sentences and titles.

"Content-Security-Policy" is the name of the HTTP Header (with hyphens) 

Therefore in all places referring to "Content Security Policy" in text, spaces should be used, except if talking specifically about the header values.

**Comment by brianteeman** [comment]
lol we wrote the same thing at the same time

**Comment by PhilETaylor** [comment]
With this being the case though, I dont see why "Content Security Policy" (with spaces) used in text cannot and should not be translated, as its just a sentence... Im no language expert, but Im guessing other languages refer to it in their own language?

as a header value, with hyphens - it should not be translated. 

For example - Spanish = "Política de seguridad de contenido" is used at https://developer.mozilla.org/es/docs/Web/Security/CSP/Introducing_Content_Security_Policy

**Comment by brianteeman** [comment]
I forgot - The hyphenation comes from when all the headers were defined in the plugin

The thinking was that these were **not** regular labels that were descriptive and therefore translatable but that they were the specific response headers.

![image](https://user-images.githubusercontent.com/1296369/85314225-13a4cd00-b4b1-11ea-8400-afc76ded45d0.png)

**Comment by PhilETaylor** [comment]
So maybe the strings in the global config (my screenshots) should be translated and the strings used in the HTTP Headers plugin should be left as they are, untranslated and with hyphens.

**Comment by brianteeman** [comment]
unless the component option field refers to the response header eg the same as x-frame-options in which case that should have the hyphens added. (not at computer to check code)

but 100% agree the tab and field group should not have the hyphen

**Comment by PhilETaylor** [comment]
at all times, except when directly referring to the exact header, the  "Content Security Policy" (with spaces) should be used and should be translatable.

**Comment by zero-24** [comment]
> So maybe the strings in the global config (my screenshots) should be translated and the strings used in the HTTP Headers plugin should be left as they are, untranslated and with hyphens. 

Ok great can you send a PR to fix it?

**Comment by zero-24** [comment]
> Correct - at all times, except when directly referring to the exact header, the  "Content Security Policy" (with spaces) should be used and should be translatable. 

I personaly dont agree that this technical term should be translated but i will let the native speaker decide on that.

**Comment by PhilETaylor** [comment]
The help page just makes it worse - so inconsistent in its use of spaces and hyphen versions

https://help.joomla.org/proxy?keyref=Help40:Components_CSP_Reports_Options&lang=es

**Comment by PhilETaylor** [comment]
The same conversation can be had over this screenshot now..  :-( :-( 

<img width="497" alt="Screenshot 2020-06-22 at 18 47 01" src="https://user-images.githubusercontent.com/400092/85318997-d47a7a00-b4b8-11ea-8835-87a2c034b28a.png">

**Comment by brianteeman** [comment]
I wouldnt translate them either

**Comment by PhilETaylor** [comment]
ok so lets not translate them (until someone else asks) but at least lets use the spaces and not the hyphen versions of these ... 

I cannot speak for non-English speakers - Im English I speak one language badly. 

Having googled though I see a lot of results and articles for "Política de seguridad de contenido" so I assume that some (Spanish) people know the feature by that ... 

maybe ask some more non-english speakers to comment here ?

**Comment by zero-24** [comment]
> The help page just makes it worse - so inconsistent in its use of spaces and hyphen versions
> 
> 
> 
> https://help.joomla.org/proxy?keyref=Help40:Components_CSP_Reports_Options&lang=es

Well as this page is written by an non native speaker (me) feel free to correct it this is what the wiki is about.

**Comment by zero-24** [comment]
> The same conversation can be had over this screenshot now..  :-( :-( 
> 
> 
> 
> <img width="497" alt="Screenshot 2020-06-22 at 18 47 01" src="https://user-images.githubusercontent.com/400092/85318997-d47a7a00-b4b8-11ea-8835-87a2c034b28a.png">
> 
> 

Sure and the same applies ;) please choose the correct english term and send a PR to correct it.

**Comment by infograf768** [comment]
See in French here:
It can be translatable as long imho as we add (CSP) after the translation.
“Stratégie de sécurité du contenu (CSP)”

**Comment by PhilETaylor** [comment]
haha that makes it more confusing for my poor head :) 

Stratégie de sécurité du contenu = SSC :-)

**Comment by zero-24** [comment]
> ok so lets not translate them (until someone else asks) but at least lets use the spaces and not the hyphen versions of these ... 
> 
> 
> 
> I cannot speak for non-English speakers - Im English I speak one language badly. 
> 
> 
> 
> Having googled though I see a lot of results and articles for "Política de seguridad de contenido" so I assume that some (Spanish) people know the feature by that ... 
> 
> 
> 
> maybe invite some more non-english (technical people) speakers to comment here ?
> 
> 

Well my personal opinion is that we should not translate it for one simple reason. It is an technical term that does not change. When you go and try to set „inhalts-sichereheits-richtlinie“ via htaccess it does not work right? Also all docs i saw until now only mention the correct technical term so to me it does not make sense translate it other than confusing people maybe thats just me?

Using the string with or without - is in my opinion up to the english native speaker to decide so please choose and send a PR so we use the correct term.

**Comment by infograf768** [comment]
CSP  is the accepted technical short, and yes, it is based on the English term.

**Comment by zero-24** [comment]
> See in French here:
> 
> It can be translatable as long imho as we add (CSP) after the translation.
> 
> “Stratégie de sécurité du contenu (CSP)”

As mention even in the language file comments i personally would not recommend to translate it as it is a technical term.

**Comment by infograf768** [comment]
https://developer.mozilla.org/fr/docs/Web/HTTP/CSP

**Comment by PhilETaylor** [comment]
There are two things.

1) The technical header name - this MUST NOT be translated and is always hyphenated. This is used when referring directly to the name of the header output in the response. 

2) When you talk about that header, as a subject of a conversation, in a paragraph or as a heading, **then its not a "technical term"**, its the name of the concept, you are discussing the topic, and its title should be translated and with space. 

Simple.

**Comment by PhilETaylor** [comment]
This describes exactly my point:

<img width="728" alt="Screenshot 2020-06-22 at 19 53 05" src="https://user-images.githubusercontent.com/400092/85324587-06440e80-b4c2-11ea-8930-61dc2d8a9bf9.png">

**Comment by infograf768** [comment]
Exactly!

**Comment by zero-24** [comment]
Ok feel free to send a PR than.

**Comment by infograf768** [comment]
Closing as we have PR
https://github.com/joomla/joomla-cms/pull/29768

**Comment by infograf768** [comment]
Reopening as https://github.com/joomla/joomla-cms/pull/29768 is closed.

**Comment by PhilETaylor** [comment]
Closing as the general consensus is that no one wants this translated.

**Comment by zero-24** [comment]
Should't we do the unification with or without - for the options screen as mention above? Or has this been canceled too?
