### ISSUE TITLE
[4.0] MOD_FINDER_SEARCH_VALUE when used as a component

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29745]
### Steps to reproduce the issue

Enable language debugging in Joomla 4 and create yourself a menu item pointing to Search.

Visit the menu item 

<img width="871" alt="Screenshot 2020-06-21 at 20 46 52" src="https://user-images.githubusercontent.com/400092/85233718-5d81aa80-b400-11ea-80f8-fce0c5f236c4.png">
 
NOTE the lack of translated placeholder text

### Expected result

Well here is where it gets complex.

The debug toolbar says that `MOD_FINDER_SEARCH_VALUE` is untranslated

So you go down the rabbit hole looking for MOD_FINDER_SEARCH_VALUE and you find its used as 

```php
Text::script('MOD_FINDER_SEARCH_VALUE', true);
```

However once the value is added to JS its not actually then used as the place holder of the input field for the search 

So the fix is 

 - wanting to actually use the JS language string somewhere, then we need a 

```php
Factory::getLanguage()->load('mod_finder');
```

 in the com_finder -  tmpl/search/default.php before `Text::script('MOD_FINDER_SEARCH_VALUE', true);`

 - Then we ALSO NEED some javascript (beyond me!) to populate this translated string as a placeholder of the input box (like the search MODULE does correctly) 

### Actual result

```json
 "joomla.jtext": {
            "MOD_FINDER_SEARCH_VALUE": "??MOD_FINDER_SEARCH_VALUE??",
            "JSHOWPASSWORD": "**Show Password**",
            "JHIDEPASSWORD": "**Hide Password**"
        },
```

<img width="909" alt="Screenshot 2020-06-21 at 20 42 20" src="https://user-images.githubusercontent.com/400092/85233634-b7ce3b80-b3ff-11ea-83d2-d4cbe58242e4.png">

### System information (as much as possible)

Safari on Mac

### Additional comments

Compare with the search MODULE which has a placeholder:

<img width="326" alt="Screenshot 2020-06-21 at 20 47 26" src="https://user-images.githubusercontent.com/400092/85233725-72f6d480-b400-11ea-8cc8-a1bfb603c73e.png">

**Comment by brianteeman** [comment]
Unless I am very much mistaken the line is a copy paste error and should not be there.

The module is populated because it has **"placeholder="' . Text::_('MOD_FINDER_SEARCH_VALUE')"**

**Comment by infograf768** [comment]
Indeed. We have to modify the default.form.php to get
```
<input type="text" name="q" id="q" class="js-finder-search-query form-control" value="<?php echo $this->escape($this->query->input); ?>" placeholder="<?php echo Text::_('MOD_FINDER_SEARCH_VALUE'); ?>">
```

But I see no reason to load the module lang file and use `MOD_FINDER_SEARCH_VALUE`.
We would be better creating a new string in com_finder.ini
`COM_FINDER_SEARCH_VALUE="Search ..."`

and use that as placeholder

<img width="862" alt="Screen Shot 2020-06-22 at 11 29 32" src="https://user-images.githubusercontent.com/869724/85271894-b6daef80-b47b-11ea-955c-59b026701698.png">

What do you think?

**Comment by PhilETaylor** [comment]
well that depends if you want a placeholder or not...  :-)

**Comment by brianteeman** [comment]
The reason for having a placeholder on the module is because you have the option to display the input without the button.  As that is not an option in the component I would not have the placeholder and simply remove the line that was added in error

**Comment by PhilETaylor** [comment]
#29755
