### ISSUE TITLE
[4.0] Disable Icons doesnt remove all icons.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29742]
### Steps to reproduce the issue

Install Joomla 4 
Edit the login module 
Set display labels = text 

<img width="637" alt="Screenshot 2020-06-21 at 18 31 07" src="https://user-images.githubusercontent.com/400092/85231265-91070980-b3ed-11ea-9dc3-0de7c0481ca8.png">

### Expected result

All icons are removed. 

### Actual result

a `?` is left dangling with no purpose

<img width="311" alt="Screenshot 2020-06-21 at 18 32 37" src="https://user-images.githubusercontent.com/400092/85231275-a0865280-b3ed-11ea-965b-6f70140d43a2.png">

### System information (as much as possible)

Safari on Mac

**Comment by Quy** [comment]
`?` is not a label, but help text.

![29742](https://user-images.githubusercontent.com/368084/88314489-d7d86f80-ccc9-11ea-8a01-d6b622d16be7.png)

**Comment by PhilETaylor** [comment]
its still dangling in a non sensible place, and there is not a popover, its just an image help text (I assume) which requires (I assume) you hovering over the image for several seconds and then relying on the browser to display the title/text of the image...

**Comment by Quy** [comment]
PR #30897
