### ISSUE TITLE
[4.0] 2FA is not shown on user profile on frontend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29743]
### Steps to reproduce the issue

Enable 2FA on your user and login to the frontend 
Click a link to view your profile:

### Expected result

2FA (YubiKey/Google Authenticator) shows as enabled
Maybe expect to see 2FA Scratch codes too...

### Actual result

Webauthn and Joomla API Token are shown but not 2FA

<img width="1179" alt="Screenshot 2020-06-21 at 19 33 13" src="https://user-images.githubusercontent.com/400092/85232358-3625e000-b3f6-11ea-9189-5cd2b300ad1b.png">

**Comment by AMurray2016** [comment]
I know the question is concerning J4, but this is just my observation...

In J3, the same thing as you describe occurs (and I have no reason to believe it shouldn't be the same for J4).  Your screenshot suggests you're not in the "edit" mode for the profile.   

Even in J3, if you are not actually in the active edit mode the 2FA information doesn't show, until you click "Edit Profile", at which time you then see what authentication method is used, the QR code, and the emergency codes.

Just my 2c.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29743">issues.joomla.org/tracker/joomla-cms/29743</a>.</sub>

**Comment by PhilETaylor** [comment]
But in J3 you also don’t have Webauthn and Joomla API Token on the view screen... whereas joomla 4 does

So either add 2FA for completeness or remove webauthn and Joomla api token for completeness

Having some but not all just makes no sense
