### ISSUE TITLE
[4.0]  ??**Actions**?? is being double processed for language

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29746]
### Steps to reproduce the issue

Enable language debugging 
Visit any admin page with an actions split button 

### Expected result

 `**Actions**`

### Actual result

` ??**Actions**??`

<img width="805" alt="Screenshot 2020-06-21 at 20 50 13" src="https://user-images.githubusercontent.com/400092/85233807-121bcc00-b401-11ea-8025-93aa762ff523.png">

**Comment by brianteeman** [comment]
Its the same as #24168 just the text has changed
