### ISSUE TITLE
[4.0] Feed Display Word Count Broken

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29741]
### Steps to reproduce the issue

Create a new feed display site module with RSS feed url of https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/section/world/rss.xml

Set the word count to 0 - load front page to see the module

<img width="328" alt="Screenshot 2020-06-21 at 18 24 58" src="https://user-images.githubusercontent.com/400092/85231118-8a2bc700-b3ec-11ea-885e-a6bb1e45882e.png">

set the word count to 5 - load the front page and compare.

<img width="1188" alt="Screenshot 2020-06-21 at 18 24 15" src="https://user-images.githubusercontent.com/400092/85231110-71231600-b3ec-11ea-9670-1ca258e5e25a.png">

### Expected result

5 words of each RSS feed item

### Actual result

`...` in each item.

<img width="317" alt="Screenshot 2020-06-21 at 18 24 40" src="https://user-images.githubusercontent.com/400092/85231114-7d0ed800-b3ec-11ea-8ebc-b9c8382125e5.png">

**Comment by SharkyKZ** [comment]
The label says word count but the code handling this is for character count.

**Comment by PhilETaylor** [comment]
Well even if that is the case, it’s not working as a char count as regardless what it’s set to all I get is ...

**Comment by SharkyKZ** [comment]
You do get "The..." in one of the entries. So that's working fine.

**Comment by SharkyKZ** [comment]
Before https://github.com/joomla/joomla-cms/commit/e3ccc0d680a3207112e148b421a1ae4144c4af2f this was indeed used as word count.

**Comment by brianteeman** [comment]
string.truncate counts characters not words

**Comment by ghost** [comment]
> string.truncate counts characters not words

`Word Count` > ` Character Count`

**Comment by bembelimen** [comment]
Closed as having a PR
