### ISSUE TITLE
[4.0] Module position changes visible value after save

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29749]
### Steps to reproduce the issue

In Joomla 4 admin create a new module (any type) 
On the right search the position to be "sidebar", and select `Sidebar-right [sidebar-right]`
Click save

### Expected result

The position display value to still be `Sidebar-right [sidebar-right]`

<img width="488" alt="Screenshot 2020-06-21 at 21 17 08" src="https://user-images.githubusercontent.com/400092/85234379-e39ff000-b404-11ea-8cbd-a3bd7fc263dc.png">

### Actual result

`sidebar-right`

(But note that `Sidebar-right [sidebar-right]` is still an option in the dropdown, the bug is purely the default visual value on page load)

<img width="466" alt="Screenshot 2020-06-21 at 21 17 13" src="https://user-images.githubusercontent.com/400092/85234376-e13d9600-b404-11ea-8a49-02073b2094d6.png">

### System information (as much as possible)

Safar on Mac

**Comment by ReLater** [comment]
The main problem is that "Sidebar-Right" could be a translated string coming from a template language sys.ini file.

If you have 2 templates and both have a position `sidebar-right` and one is translating the position label as `My nice sidebar right` and the other is translating it as `My ugly sidebar right` which one should be displayed?
The same behavior like in Joomla 3.
Compare:
https://github.com/joomla/joomla-cms/blob/staging/templates/protostar/language/en-GB/en-GB.tpl_protostar.sys.ini#L18
https://github.com/joomla/joomla-cms/blob/staging/templates/beez3/language/en-GB/en-GB.tpl_beez3.sys.ini#L17

**Comment by PhilETaylor** [comment]
So a won’t fix. Ok
