### ISSUE TITLE
[3] COM_CONTENT_READ_MORE_TITLE and sprintf

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#29758]
### Steps to reproduce the issue
- Wherever language string  `COM_CONTENT_READ_MORE_TITLE` is used in core it is translated via `JText::sprintf(...)`
- but neither a parameter is passed in `sprintf`s nor does the language string contain a replacement instruction like `%s`.

See:
for example https://github.com/joomla/joomla-cms/blob/staging/components/com_content/views/article/tmpl/default.php#L153-L154
https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/content/readmore.php#L35

and 
https://github.com/joomla/joomla-cms/blob/staging/language/en-GB/en-GB.com_content.ini#L89

### Additional comments
It doesn't greatly matter for me. It just irritated me for a while during development ;-)
Maybe a B\C thing (?)

**Comment by SharkyKZ** [comment]
This is fixed in 4.0, see https://github.com/joomla/joomla-cms/pull/29065.
