### ISSUE TITLE
showon attribute not working

### ISSUE THREAD

**Issue by ced1870** [joomla/joomla-cms#29756]
### Steps to reproduce the issue
create a field in the xml of a plugin or module
add the showon attribute to only show the option if the showon value is selected

### Expected result
the field to be shown / hidden 

### Actual result
none, the field is always shown

### System information (as much as possible)
joomla 4 beta 1

### Additional comments
it works in joomla 3.9 without problem with the same xml
showon added on a radio field

**Comment by chmst** [comment]
confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29756">issues.joomla.org/tracker/joomla-cms/29756</a>.</sub>

**Comment by Quy** [comment]
Fixed in #29691. Please test the nightly build https://developer.joomla.org/nightly-builds.html.
