### ISSUE TITLE
[4.0] Fancy Select missing icon for removing the selected value

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29750]
### Steps to reproduce the issue

NOT A SAFARI BUG
Tested on Google Chrome, Safari and Firefox on Mac.

Joomla 4 -> Site Modules -> Add New 

Position on the right, select an item, and then hover your mouse to the left of the dropdown trigger arrow, and click

### Expected result

A visual X in the whitespace

### Actual result

A badly placed click can remove the selected item and confuse idiots like me. Several times. 

![Screen Recording 2020-06-21 at 09 24 PM](https://user-images.githubusercontent.com/400092/85234611-8016c200-b406-11ea-8037-8f22f0d74bfd.gif)

When an item is selected there is a rendered remove button - just no visual indication its here

<img width="816" alt="Screenshot 2020-06-21 at 21 30 10" src="https://user-images.githubusercontent.com/400092/85234607-75f4c380-b406-11ea-91de-cf76d7fd7710.png">

### System information (as much as possible)

NOT A SAFARI BUG
Tested on Google Chrome, Safari and Firefox on Mac.

**Comment by chmst** [comment]
Related to #29608<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29750">issues.joomla.org/tracker/joomla-cms/29750</a>.</sub>

**Comment by Quy** [comment]
Please test PR #29761
