### ISSUE TITLE
[4.0] New Help Scrren

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#29754]
### Steps to reproduce the issue

Enable Workflows in Content -> Options -> Integration tab
Select Content -> Workflows -> Help button
Select Content -> Workflows -> Stages (numbered button) -> Help button
Select Content -> Workflows -> Transitions (numbered button) -> Help button

### Expected result

Helpful articles

### Actual result

404 Not found

### Additional comments

I have created the Help screens but some code changes are needed:

For consistency with other Help links the keys need to be changed:

JHELP_WORKFLOWS_LIST to become JHELP_COMPONENTS_WORKFLOW_WORKFLOWS_LIST
JHELP_WORKFLOW_STAGES_LIST to become JHELP_COMPONENTS_WORKFLOW_STAGES_LIST
JHELP_WORKFLOW_TRANSITIONS_LIST to become JHELP_COMPONENTS_WORKFLOW_TRANSITIONS_LIST

And the following strings need to be in Administrator language files, joomla.ini (and ...):

JHELP_COMPONENTS_WORKFLOW_WORKFLOWS_LIST="Components_Workflows_Lists"
JHELP_COMPONENTS_WORKFLOW_STAGES_LIST="Components_Workflows_Stages_List"
JHELP_COMPONENTS_WORKFLOW_TRANSITIONS_LIST="Components_Workflows_Transitions_List"

I have tested this locally.

**Comment by brianteeman** [comment]
Thanks again

See #29757 for the PR
