### ISSUE TITLE
[4.0] Login page during installer doesnt allow hide/reveal password

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29765]
### Steps to reproduce the issue

Joomla 4 
System -> Joomla (Update box) 
Choose any file (#29763 bug allows any file) 
Click upload and install 

### Expected result

Password hide/reveal icon is clickable like all other password boxes in Joomla 4

### Actual result

<img width="1121" alt="Screenshot 2020-06-22 at 22 16 20" src="https://user-images.githubusercontent.com/400092/85336122-064e0980-b4d6-11ea-8c95-394479028f51.png">

**Comment by brianteeman** [comment]
Looks like it needs to use the  WebAssetManager and useScript('field.passwordview')

**Comment by brianteeman** [comment]
Please test #30849
