### ISSUE TITLE
[3+] Failed Joomla 4 upgrade leads to a page that has nothing to click

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29764]
### Steps to reproduce the issue

You can replicate this today without an upgrade being available

Take Joomla 4.0-dev or 4.0.0 beta1 or 3.9.19

Login as a super admin 

Go to System -> Joomla (under update menu) 

Upload a PNG FILE instead of a Joomla package zip file. (bug #29763 allows you to upload this) 

Click upload and install 

Provide valid credentials 

You will then see 

<img width="497" alt="Screenshot 2020-06-22 at 22 10 09" src="https://user-images.githubusercontent.com/400092/85335619-2c26de80-b4d5-11ea-9626-e4b4c0a663fc.png">

Click close

### Expected result

A pathway forward, a "return to admin" button? a menu item that can be click? Something other than nothing. 

### Actual result

You are now stuck at a page with nothing clickable, no next step, no where to go 

<img width="1201" alt="Screenshot 2020-06-22 at 22 10 57" src="https://user-images.githubusercontent.com/400092/85335705-524c7e80-b4d5-11ea-9e60-4604b4818645.png">

### Additional Comments

Joomla 3 has same issue

**Comment by richard67** [comment]
PR for J3 is in progress: See #29884 . I leave this issue open until the PR is ready.

When it once will be merged into J3, it later will be merged up to J4 with the regular upmerge cycle.

**Comment by PhilETaylor** [comment]
#29884 was closed without being merged :(
