### ISSUE TITLE
[4.0] 404 file not found - media/vendor/codemirror/mode/text/x-php/text/x-php.min.js

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29767]
### Steps to reproduce the issue

Joomla 4 admin
System -> Site Templates -> Cassiopeia Details and Files -> Create Overrides -> mod_articles_archive
Click html -> mod_articles_archive -> default.php

### Expected result

No console errors 

### Actual result

`Failed to load resource: the server responded with a status of 404 (Not Found) for `

https://example.com/media/vendor/codemirror/mode/text/x-php/text/x-php.min.js

### System information (as much as possible)

Safari on Mac
nginx in docker as a webserver

**Comment by ReLater** [comment]
Confirmed.

**Comment by infograf768** [comment]
Not only Safari.

**Comment by brianteeman** [comment]
Its not a missing file. its an issue with mime type detection with codemirror

It **should** be detecting "text/x-php" as php and therefore loading php.js

**Comment by dgrammatiko** [comment]
If only someone already have fixed this and many other bugs related to code mirror: https://github.com/joomla/joomla-cms/pull/23426

**Comment by PhilETaylor** [comment]
I see #23426 was not merged, and therefore the reported issue remains.

**Comment by dgrammatiko** [comment]
Fixed with https://github.com/joomla/joomla-cms/pull/32315

**Comment by PhilETaylor** [comment]
Thanks
