### ISSUE TITLE
[4.0]  PHP Notice: Trying to get property 'id' of non-object in /application/libraries/src/Updater/Adapter/ExtensionAdapter.php

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29778]
### Steps to reproduce the issue

Joomla 4.x-dev

Ensure you have some PHP log output - mine here is a docker php-fpm log tail.

Install Akeeba Backup using Install From Url method with url 

https://www.akeebabackup.com/download/akeeba-backup/7-2-1/pkg_akeeba-7-2-1-core-zip.zip

After its installed click "Home Dashboard" 

Note that in the update checks the `Checking extensions` has failed 

<img width="653" alt="Screenshot 2020-06-25 at 16 30 52" src="https://user-images.githubusercontent.com/400092/85750106-5230c680-b701-11ea-9242-f8b56f9e946d.png">

### Expected result

No PHP Notices

### Actual result

Ajax request with Notices

<img width="792" alt="Screenshot 2020-06-25 at 16 31 42" src="https://user-images.githubusercontent.com/400092/85750172-5fe64c00-b701-11ea-8005-cc29afb07179.png">

php_1        | 192.168.32.5 -  25/Jun/2020:15:27:10 +0000 "GET /administrator/index.php" 200
php_1        | 192.168.32.5 -  25/Jun/2020:15:27:10 +0000 "GET /administrator/index.php" 200
php_1        | NOTICE: PHP message: PHP Notice:  Trying to get property 'id' of non-object in /application/libraries/src/Updater/Adapter/ExtensionAdapter.php on line 333
php_1        | 192.168.32.5 -  25/Jun/2020:15:27:10 +0000 "GET /index.php" 404
php_1        | 192.168.32.5 -  25/Jun/2020:15:27:10 +0000 "GET /index.php" 404
php_1        | NOTICE: PHP message: PHP Notice:  Trying to get property 'id' of non-object in /application/libraries/src/Updater/Adapter/ExtensionAdapter.php on line 333
php_1        | 192.168.32.5 -  25/Jun/2020:15:27:10 +0000 "GET /administrator/index.php" 200
webserver_1  | 2020/06/25 15:27:10 [error] 9#9: *155 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to get property 'id' of non-object in /application/libraries/src/Updater/Adapter/ExtensionAdapter.php on line 333PHP message: PHP Notice:  Trying to get property 'id' of non-object in /application/libraries/src/Updater/Adapter/ExtensionAdapter.php on line 333" while reading response header from upstream, client: 192.168.32.1, server: , request: "GET /administrator/index.php?option=com_installer&view=update&task=update.ajax&198756102de4392ec83bef34a7d00709=1&cache_timeout=3600&eid=0&skip=212 HTTP/1.1", upstream: "fastcgi://192.168.32.2:9000", host: "127.0.0.1", referrer: "http://127.0.0.1/administrator/index.php"
php_1        | 192.168.32.5 -  25/Jun/2020:15:27:12 +0000 "GET /administrator/index.php" 200

### System information (as much as possible)

safari on Mac

### Additional comments

THE SECOND and subsequent times it loads ok, can only be replicated on first load

**Comment by chmst** [comment]
There was already a PR: #17481 a longer time ago. Which PHP Version is on your server?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29778">issues.joomla.org/tracker/joomla-cms/29778</a>.</sub>

**Comment by PhilETaylor** [comment]
I doubt it’s php version specific 

I only use the latest php 7.4 version in docker containers

**Comment by PhilETaylor** [comment]
I can also replicate this in the CLI Application

On the first run of the command `php cli/joomla.php  update:extensions:check -vvv` you get the PHP Notices and then they dont show on the second and further 

<img width="964" alt="Screenshot 2020-06-28 at 20 17 40" src="https://user-images.githubusercontent.com/400092/85956235-7f3cdd80-b97c-11ea-8e05-6334a86e4900.png">

**Comment by PhilETaylor** [comment]
PR #28979

**Comment by PhilETaylor** [comment]
So I attempted to resolve this, and my proposed solutions were rejected - so I'm reopening this issue as it IS AN ISSUE to resolve (Showing of PHP Notices) and someone else can have a go.

**Comment by wilsonge** [comment]
I can't reproduce this with the modern (gave me an unrelated error on install) or original reported akeeba version (either in UI or CLI).

**Comment by PhilETaylor** [comment]
I just replicated this again in Joomla 4 beta 6

I went to the JED (install from web) and installed 4 or 5 extensions from the home page of install from web, including  Akeeba and JEvents

When I load the home dashboard of admin I get this problem with the Ajax call from the updates checker quick icon

```
<br/>
<b>Warning</b>
:  Attempt to read property "id" on null in 
<b>/Users/phil/Downloads/Joomla_4.0.0-beta6-Beta-Full_Package/libraries/src/Updater/Adapter/ExtensionAdapter.php</b>
 on line 
<b>333</b>
<br/>

[{"update_id":80,"update_site_id":8,"extension_id":250,"name":"JEvents","description":"JEvents Package Update","element":"pkg_jevents","type":"package","folder":"","client_id":0,"version":"3.6.12","data":"","detailsurl":"https:\/\/www.jevents.net\/newupdates\/package_jevents.xml","infourl":"https:\/\/www.jevents.net\/product-page?item_id=857","changelogurl":null,"extra_query":"","manifest_cache":"{\"name\":\"JEV_PACKAGE_TITLE\",\"type\":\"package\",\"creationDate\":\"September 2020\",\"author\":\"GWE Systems Ltd\",\"copyright\":\"(C) 2012-2020 GWE Systems Ltd\",\"authorEmail\":\"\",\"authorUrl\":\"www.gwesystems.com\",\"version\":\"3.6.6\",\"description\":\"JEV_PACKAGE_DESC\",\"group\":\"\",\"filename\":\"pkg_jevents\"}","client_translated":"Site","current_version":"3.6.6","type_translated":"Package","folder_translated":"N\/A","install_type":"Update"}]
```

The second page load it doesn't happen (as, cache!) 

Then if I go to the list of updates, and clear cache, and then return to home dashboard, I can repeat the error

I can replicate this again and again on demand.

**Comment by Quy** [comment]
#35376

**Comment by richard67** [comment]
It seems someone could reproduce it with some other 3rd party extensions, see the issue here recently reported: #35815 .

**Comment by richard67** [comment]
Closing as having a pull request. Please test #35822 . Thanks in advance.
