### ISSUE TITLE
menu + anchor results in error

### ISSUE THREAD

**Issue by BRoehling** [joomla/joomla-cms#29776]
### Steps to reproduce the issue

copy menu link url on your joomla website
set menu type to: URL
paste url to link
attach anchor #ananchor to url

the url looks like this: http://www.aaa.de/aaa/aaa/index.php?option=com_content&view=article&id=40&Itemid=104#section4

set error reporting to development
click menu link

### Expected result

on menu item click, jump to anchor "point" in page

### Actual result

the method works (menu item click results in jumping to anchor but one gets: 

Notice: Undefined index: option in /var/www/vhosts/aaa.de/aaa.de/aaa/aaa/components/com_content/views/article/view.html.php on line 245

Notice: Undefined index: option in /var/www/vhosts/aaa.de/aaa.de/aaa/aaa/components/com_content/views/article/view.html.php on line 253

Notice: Undefined index: option in /var/www/vhosts/aaa.de/aaa.de/aaa/aaa/components/com_content/views/article/view.html.php on line 253

### System information (as much as possible)

Joomla! 3.9.8
windows 10
intel 2.6ghz, 4 gb ram
google chrome Version 83.0.4103.116 (Offizieller Build) (64-Bit)

**Comment by ReLater** [comment]
Could you please first update your Joomla to current version 3.9.19. This repository here is intended for issues that concern the current version of Joomla to get fixed in the next version.

**Comment by ReLater** [comment]
This issue has been fixed in Joomla! 3.9.12.
https://github.com/joomla/joomla-cms/pull/25796
https://github.com/joomla/joomla-cms/pull/25796/files#diff-a2fbd25d7bac224516450abdd42cd57b

**Comment by BRoehling** [comment]
mind you, what's newer, 3.9.12 or 3.9.8 ?

**Comment by kitepascal** [comment]
Please update to 3.9.19 (always use the latest version).

**Comment by BRoehling** [comment]
wonderful the error had been fixed
