### ISSUE TITLE
[3+] Language filter for "List All Tags" has no effect in frontend

### ISSUE THREAD

**Issue by kmu360** [joomla/joomla-cms#29783]
### Steps to reproduce the issue
**Backend**
1. Create articles with different tags and in multiple languages
2. Create menu point with Menu Item Type "List All Tags"
3. Change Language Filter to specific language

![image](https://user-images.githubusercontent.com/66309533/85874599-2c73f200-b7d3-11ea-8136-117b13b7e192.png)

**Frontend**
1. Klick on the new menu point (List of Tags)
2. Klick on a Tag ... 

### Expected result
Frontend output when selecting a tag should be a list with articles with the selected tag in the selected (or current) language

### Actual result
**All** articles with the selected tag are displayed **regardless of language setting** 
Neither with "current" nor with "specified language"

### Bug?
`tag_list_language_filter` is not being stored in the database.

### Brute force debugging info

Added the following code to an override to "tag\default.php"

`$language = JComponentHelper::getParams('com_tags')->get('tag_list_language_filter');`
`echo '<br />Current language in Setting is: ' . $language;`
`$currentLanguage = JFactory::getLanguage();`
`echo '<br />Current language is: ' . $currentLanguage->getName();`
`echo '<br />Current Lang-tag is: ' . $currentLanguage->getTag();`

![image](https://user-images.githubusercontent.com/66309533/85874029-49f48c00-b7d2-11ea-9a42-8c60371cb59e.png)

Expected output would be: 
Current language in Setting is: German (Germany) or de-DE (not sure)

### System information 

Joomla! Version: Joomla! 3.9.19 Stable
Translation component: falang (latest) - Been in contact with Stephane, no bug from falang.

### Or am I wrong...

As far as I understand, the language filter limits the output to articles in the selected language and not to articles with a tag that has a specific language, right? 
If this is the case, my approach of displaying articles for a specific tag in a specific language would fail anyway (or at least multiply the work by 3). But still the `tag_list_language_filter` would not be stored in the database...

**Comment by infograf768** [comment]
In Joomla multilingual native feature, the filtering is done depending on the language of the item filtered and not the 'language filter' in tag.
I.e the `current` setting is the only one that makes sense.

**Comment by kmu360** [comment]
I totally agree. But also `current` is not stored In the database when set in the backend.

**Comment by infograf768** [comment]
`current language` (or any language ) IS saved for the `List all tags` menu item which uses the `tags` template (and not `tag/default.php`).

<img width="808" alt="Screen Shot 2020-06-28 at 08 40 32" src="https://user-images.githubusercontent.com/869724/85940165-16714900-b91b-11ea-9b67-40a98a6f3b0b.png">

But I wonder indeed why we have that field there. We may have a bug as it works fine for other cases.

It works for the `compact list of tagged items` (which uses tmpl `tag` `layout=list` and, in this case, it does filter by the language selected and displays correctly links to items tagged to that language (and click works fine) while the menu is itself used in another language.

<img width="862" alt="Screen Shot 2020-06-28 at 08 42 14" src="https://user-images.githubusercontent.com/869724/85940203-4c163200-b91b-11ea-8e9d-f41fbd774d7e.png">

It is also used correctly by `Tagged Items` menu item.

<img width="826" alt="Screen Shot 2020-06-28 at 08 51 10" src="https://user-images.githubusercontent.com/869724/85940418-8c29e480-b91c-11ea-8458-bc46bb5cf9f8.png">

**Comment by kmu360** [comment]
Firstly: Thanks for looking into it! 

So in my case the workaround would be using `tagged items` menu or so. 

...and leaving the suspect bug to you guys as my skills are far to weak to have a deeper look.

**Comment by kmu360** [comment]
There's something weird going on...

Just tried with `Tagged Items` and `compact list of tagged items` and it worked fine for the first time!
And then, after a reload, it is the same behaviour with showing all languages again. 

And no chance to revert. Also when setting up a completele new menu point "from scratch" it results in all languages being shown.

@infograf768 I can give you the URL or even direct access to the project if you think that might help.

**Comment by infograf768** [comment]
I am not sure I can help as you use falang. I suggest you contact Stephane referring him to this topic.

**Comment by kmu360** [comment]
I´m in contact with him already - And he said it doesn´t come from falang :)
No worries: I´ll somehow live with, it. 

And frankly: My single issue is not important as long as it is no core bug.

Thanks again!

**Comment by infograf768** [comment]
I had forgotten: found the use of the Language filter field for the `List All Tags` menu item. It is very different from the 2 other menu items.

In that case, it filters the tags displayed depending on the tag language (and not the items).
If one choses French, then it will display the tags tagged to French as well as for All languages.

So, if you have no tag set to ALL and add the tag tagged to French to only French articles, that tag will display and when clicking on the tag name you will display all articles tagged to French.

**Comment by infograf768** [comment]
As it is not a joomla issue, I am closing this.
