### ISSUE TITLE
WebLinks extension - Count / Countable bug in PHP 7.3+

### ISSUE THREAD

**Issue by LuxLOL** [joomla/joomla-cms#29782]
### Steps to reproduce the issue

Installing the WebLinks extension. And creating a Joomla menu to a Web Link.
https://downloads.joomla.org/extensions/weblinks

### Expected result

No errors in the HTTP Server log.

### Actual result

PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/clients/client1/web17/web/components/com_weblinks/models/categories.php on line 95

### System information (as much as possible)

Joomla v3.9.19 with PHP v7.4 (fpm-fcgi) and MySQL v5.5.5

### Additional comments

Forum Topic link: https://forum.joomla.org/viewtopic.php?f=715&t=980815

**Comment by toivo** [comment]
Similar issue also in Web Links module:
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in C:\www\joomlatest\modules\mod_weblinks\mod_weblinks.php on line 17<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29782">issues.joomla.org/tracker/joomla-cms/29782</a>.</sub>

**Comment by Quy** [comment]
The weblinks component has been decoupled from Joomla CMS.
Please post your issues here: https://github.com/joomla-extensions/weblinks
