### ISSUE TITLE
Selective extension updates hide option

### ISSUE THREAD

**Issue by BRoehling** [joomla/joomla-cms#29786]
### Steps to reproduce the issue

This is a feature request for joomla 3.9.x and 4.x

### Expected result

implementation of an easy and non-intrusive feature option to hide selected extensions from being notified for update.
for some users or in some cases it might be useful to have this option to exclude a/some plugin/s from being in the update notification.

### Actual result

option not implemented

### System information (as much as possible)

Joomla 3.9.8
Windows 10
2.6 Ghz, 4 GB RAM, SSD

### Additional comments

-

**Comment by Quy** [comment]
Disable in Extensions > Manage > Update Sites should do the trick.

**Comment by BRoehling** [comment]
thank you very much, the bugging is gone :) 
I hope you get some cheering!
