### ISSUE TITLE
[4] Control panel. Move module "Update Checks" up.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#29791]
### Steps to reproduce the issue
- Open control panel on device with smaller width (e.g. <  ~ 430px).

### Expected result
- Update Checks block should be shown prominentely as first module on top of the page. In J3 we have additional alert messages on top of the page when updates available. But no longer in Joomla 4 (see https://github.com/joomla/joomla-cms/pull/24893).

### Actual result
- You have to scroll down before you see the important update icons. Most users won't do that. At least users from J3 will expect update messages on top of the page.

**Comment by ghost** [comment]
Agree

**Comment by infograf768** [comment]
Normally it should be modified by ordering the quickicons admin modules, but this does not work... Even when ordered differently, when loading the Home Dashboard, they go back to their original order...

**Comment by infograf768** [comment]
In fact, ordering works when doing it from the module itself, not by dragging.
<img width="565" alt="Screen Shot 2020-09-20 at 09 19 22" src="https://user-images.githubusercontent.com/869724/93705989-6c244e80-fb22-11ea-929a-8d6ad13583fb.png">

**Comment by ghost** [comment]
> In fact, ordering works when doing it from the module itself, not by dragging.

true on Site-Modules too.

**Comment by infograf768** [comment]
Also remarked that, if ordered through the module, db is really weird as Site and Update Checks have the same order digit:

<img width="770" alt="Screen Shot 2020-09-20 at 09 33 56" src="https://user-images.githubusercontent.com/869724/93706250-9d058300-fb24-11ea-8f2d-97c8a0f7dcf9.png">

**Comment by chmst** [comment]
The order number is correct as it is related to the container. But ordering has some issues in other components, so maybe the whole concept of ordering numbers is not consistent

**Comment by micker** [comment]
Yes drag and drop IS only in a black template https://github.com/C-Lodder/joomla4-backend-template .. But not only the problem... No full width display in cpanel https://github.com/joomla/joomla-cms/issues/25952
