### ISSUE TITLE
[4.0] Inconsistent Grammar In Console Commands

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#29795]
Run `php cli/joomla.php`, review the command descriptions being shown.  You have “Checks for Joomla updates” and “Updates joomla core” right on top of each other, and you have one description ending with a period while no others do.

**Comment by brianteeman** [comment]
The same is true with the help text 
eg `php cli/joomla.php help cache:get`

**Comment by alikon** [comment]
@mbabker 
so what should be the correct grammar ? i'm sorry but i'm an english dumb
ok  i'll remove the the period

@brianteeman 
we don't have such command `php cli/joomla.php help cache:get` in console commands 
what i'm missing ?

**Comment by brianteeman** [comment]
Sorry - should have been this as an example

`php cli/joomla.php help config:set`

I will try to find some time to review ALL of the cli help and info strings to make them consistent in style and grammar

**Comment by alikon** [comment]
thank you i'm available to do the corrections

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/pull/29811
