### ISSUE TITLE
re-opening #19692 Menu item type = URL, cannot assign modules to the menu item 

### ISSUE THREAD

**Issue by BRoehling** [joomla/joomla-cms#29797]
### Is your feature request related to a problem? Please describe.

Original Post: https://github.com/joomla/joomla-cms/issues/19692
The solution described in above post didn't lead to a working solution, but I and potentially other Joomla users need this feature.

### Describe the solution you'd like

not restrict module/menu assignment from URL menu type, i.e. allow it for URLs

### Additional context

can we discuss it?

**Comment by BRoehling** [comment]
you guys are baaad

**Comment by ReLater** [comment]
Use the Advanced Module Manager of RegularLabs! There you can select any menu item. Perhaps you need additional overrides(?)

From my point of view it's correct and very helpful for most users to disable menu item selections in core where a selection is only resonable for some seldom edge cases.

**Comment by brianteeman** [comment]
The intent of the URL menu type is to link to external web sites - therefore it makes no sense to assign modules to the content of that menu item is not part of your web site
If you want to create a menu item that is a link to another menu item on your site then you should use the Alias menu type

**Comment by BRoehling** [comment]
I'm using the URL type to scroll to anchors e. g. #section. Joomla doesn't support that natively with the normal link 5ype.

**Comment by BRoehling** [comment]
ReLater, yes I did 5hat yesterday.

**Comment by brianteeman** [comment]
Well those are just links to an existing page which already has modules assigned to it.

**Comment by BRoehling** [comment]
Brian I drink tea man

**Comment by Quy** [comment]
> I'm using the URL type to scroll to anchors e. g. #section. Joomla doesn't support that natively with the normal link 5ype.

It should work. Do you have the `id="section"` anchor on the page?

**Comment by BRoehling** [comment]
> It should work. Do you have the `id="section"` anchor on the page?

yeah. `<a id="section"></a>`

**Comment by Quy** [comment]
Duplicate #29792

**Comment by BRoehling** [comment]
it works by using sefurl#anchor

duplicate thread I close it
