### ISSUE TITLE
Joomla 4 beta2-dev — No more articles in backend but showing in front end

### ISSUE THREAD

**Issue by vintzl** [joomla/joomla-cms#29796]
I have no more access to articles in backend, while they are showing in front end, after upgrading, from beta1-dev to beta2-dev, with a clean install package (Joomla_4.0.0-beta2-dev-Development-Full_Package.zip). If I am not mistaken, it happened around 2020-06-23.

Not sure if it is related, but now I get this exception each time I refresh the now blank `administrator/index.php?option=com_content&view=articles` link :

>Exception has occurred.
>UnexpectedValueException: FormFactory not set in Joomla\CMS\MVC\Model\ListModel

**Comment by richard67** [comment]
How can you upgrade with a full install package??? That seems wrong to me. Did you just unpack the new files but kept the old database? If so, this is definitely wrong! Or if not, how did you apply the database changes between these versions if not doing an update?

**Comment by vintzl** [comment]
OFF TOPIC.  You don't help me…

Anyway, you belong to the joomla organization and you ignore that `/administrator/components/com_admin/sql/updates/mysql/` holds all the incremental db updates??? (here for mysql, but also for postgresql)

**Comment by richard67** [comment]
I don’t ignore that. I asked if and how you have applied them in order to find out what went wrong.

**Comment by richard67** [comment]
And I am a normal volunteer like everybody here. That I belong to the Organisation on GitHub doesn’t mean I am a speaker or have any other position in the community than a volunteer unpaid contributor.

**Comment by vintzl** [comment]
Do not know why, but I had to run twice this sql script

```
INSERT INTO `kl0_workflow_associations` (`item_id`, `stage_id`, `extension`)
SELECT `id`, 1, 'com_content.article' FROM `kl0_content`;
```

to get my articles back, while I had `#__workflow_associations` populated with the good data.

But the exception remains.
