### ISSUE TITLE
Joomla 4 beta2-dev — UnexpectedValueException: FormFactory not set in Joomla\CMS\MVC\Model\ListModel

### ISSUE THREAD

**Issue by vintzl** [joomla/joomla-cms#29798]
For any URL reached from back-end, I get this exception from `libraries/src/Form/FormFactoryAwareTrait.php:43`

```
Exception has occurred.
UnexpectedValueException: FormFactory not set in Joomla\CMS\MVC\Model\ListModel
```

**Comment by chmst** [comment]
I cannot confirm this error, everything works fine here. Can you make a new, quite clean installation with the latest nightly build and a new database?

**Comment by vintzl** [comment]
With a clean install, I get the same issue.

Here a screenshot with vscode

![image](https://user-images.githubusercontent.com/44751088/87254362-6d7e2e80-c482-11ea-85a8-4c38bf5a9c61.png)

**Comment by Quy** [comment]
Please see if this reproducible with nightly builds: https://developer.joomla.org/nightly-builds.html

**Comment by vintzl** [comment]
Reproductible, even with Joomla_4.0.0-beta3-dev-Development-Full_Package (last built: Sunday, 12 July 2020 02:00:23 UTC).

**Comment by Quy** [comment]
Please test again with the nightly build to see if this is still reproducible. Thanks.

**Comment by vintzl** [comment]
With Joomla_4.0.0-beta6-dev-Development-Update_Package.zip from here:
- https://developer.joomla.org/nightly-builds.html

I get this:

![image](https://user-images.githubusercontent.com/44751088/103106136-4df35080-4633-11eb-8b5b-e2223b58c203.png)

**Comment by brianteeman** [comment]
I cannot replicate this either. To avid confusion and to help to see if it can be replicated. When you say
> For any URL reached from back-end,

Please give an exact url that you are trying

**Comment by Quy** [comment]
@vintzl Closing for now as you are the only one that can reproduce this. Please provide the info requested by Brian. Thanks.
