### ISSUE TITLE
[4.0] Ability to make faked admin dashboards 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29809]
### Steps to reproduce the issue

Install Joomla 4 
Go to admin and login as super admin

Fake a url 

`https://example.com/administrator/index.php?option=com_cpanel&view=cpanel&dashboard=SOMETHINGELSE`

### Expected result

404

The value of `dashboard` should be validated 

### Actual result

You can now see `Add module to the dashboard` link

You can use that link to actually add modules to this made up dashboard and save the module.

You can see the modules on your fake url

`https://example.com/administrator/index.php?option=com_cpanel&view=cpanel&dashboard=SOMETHINGELSE`

**Comment by SharkyKZ** [comment]
Validated against what?

**Comment by PhilETaylor** [comment]
No idea - but it should not be able to be created on the fly ;-)

**Comment by bembelimen** [comment]
Why? that's exactly an expected behaviour, creating dashboards on the fly, as many as you want (e.g. for creation in a custom menu)
