### ISSUE TITLE
[4.0][cli] Attempted to load class "Helper" from namespace "Joomla\Console"

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29815]
### Steps to reproduce the issue

Joomla 4.0-dev @ af9be59d0833bd8fa39476f01ee3cc09e5eaf2b7
Joomla Global Config Error Reporting = maximum

` php cli/joomla.php config:set -vvv`

### Expected result

<img width="336" alt="Screenshot 2020-06-28 at 19 54 02" src="https://user-images.githubusercontent.com/400092/85955791-228bf380-b979-11ea-96f4-9decf9b7218d.png">

### Actual result

<img width="526" alt="Screenshot 2020-06-28 at 19 54 30" src="https://user-images.githubusercontent.com/400092/85955800-33d50000-b979-11ea-9173-b92a7c63e359.png">

### Additional comments
other commands (I know invalid syntax on some) cause this same issue

`php cli/joomla.php  extension:remove -vvv`
`php cli/joomla.php   session:metadata:gc 1 -vvv`

**Comment by wilsonge** [comment]
Fixed with https://github.com/joomla/joomla-cms/commit/2ea0272436152e676f39f5a1ff6bcb9900c9ff70
