### ISSUE TITLE
[4.0][cli] config:set doesnt validate input 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29816]
### Steps to reproduce the issue

Joomla 4.0-dev @ af9be59
Joomla Global Config Error Reporting = maximum

`php cli/joomla.php config:set error_reporting=NONSUCH -vvv`

### Expected result

Expect that `NONSUCH` is rejected as a non valid value of error_reporting like it would be if submitted in Joomla Admin

### Actual result

value is stored in `configuration.php`

```php
	public $error_reporting = 'NONSUCH';
```

### Additional comments

Affects other properties of the config too - no validation.

**Comment by brianteeman** [comment]
> Expect that NONSUCH is rejected as a non valid value of error_reporting like it would be if submitted in Joomla Admin

My test shows that there is no validation in the admin either. It is perfectly possible to manipulate the form to submit garbage values.

![image](https://user-images.githubusercontent.com/1296369/86031534-dd75c900-ba2d-11ea-92d5-956b313fb099.png)

**Comment by PhilETaylor** [comment]
The difference being, at least a dropdown of predefined values is given in the admin console, so under normal circumstances its impossible to set an invalid value unless you are hacking yourself (while logged in as a super admin) 

At the command line a typo is VERY easy to make!

**Comment by brianteeman** [comment]
Not arguing that - just that the reported comment was not true

**Comment by wilsonge** [comment]
I'm going to close this in favour of the more generic #31900
