### ISSUE TITLE
[4.0][CLI] User password complexity rules not enforced at the cli

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29817]
### Steps to reproduce the issue

Joomla 4.0-dev @ af9be59

` php cli/joomla.php user:add`

Create a user with `p` as the password

### Expected result

Password doesnt meet configured Joomla User minimum password length and therefore should be rejected

### Actual result

User is created. 

<img width="532" alt="Screenshot 2020-06-28 at 20 02 50" src="https://user-images.githubusercontent.com/400092/85956013-603d4c00-b97a-11ea-81b0-45ffa0409d1c.png">

<img width="979" alt="Screenshot 2020-06-28 at 20 03 23" src="https://user-images.githubusercontent.com/400092/85956023-74814900-b97a-11ea-83d6-ac05eb1257d6.png">

**Comment by zero-24** [comment]
hmm seems that there is no validation at all on that thing right? https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Console/AddUserCommand.php

Does anyone has in mind how that kind of rule validation should be implemented in the CLI context?

**Comment by PhilETaylor** [comment]
Well the JSST have gone with 12 chars minimum only as a new rule - see https://github.com/joomla/joomla-cms/pull/29859

**Comment by PhilETaylor** [comment]
> Does anyone has in mind how that kind of rule validation should be implemented in the CLI context?

Surely it should read from the database the rules that the site admin has set ? The same rules that would be applied by the User Manager in admin.

**Comment by zero-24** [comment]
Yes all of that is done in the form rule. The question was do we have some kind of 'please validate this field' option in the CLI right now as i dont think we should add just another place where repeat the code.

**Comment by PhilETaylor** [comment]
There is currently no validation of input in any command that I can see, certainly not any password validation happening - it just takes the provided password and hashes it - its lacking in that area and I have raised [other issues](https://github.com/joomla/joomla-cms/issues/29816) about being able to set invalid vars by typo. 

The validation would be needed in the `ChangeUserPasswordCommand` as well as the add user command I guess

**Comment by mbabker** [comment]
> The question was do we have some kind of 'please validate this field' option in the CLI right now as i dont think we should add just another place where repeat the code.

Too bad Joomla lacks a general purpose data validation API and the closest thing that exists to one is a form rule which means everything has to be in an HTML form for it to be usable.

**Comment by zero-24** [comment]
> > The question was do we have some kind of 'please validate this field' option in the CLI right now as i dont think we should add just another place where repeat the code.
> 
> Too bad Joomla lacks a general purpose data validation API and the closest thing that exists to one is a form rule which means everything has to be in an HTML form for it to be usable.

Ok so we are required to reimplement the rules or do you think there can be a general purpose data validation api based on the form rules maybe?
