### ISSUE TITLE
[4.0[[cli] user:add Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29814]
### Steps to reproduce the issue

af9be59d0833bd8fa39476f01ee3cc09e5eaf2b7

Joomla 4.0-dev @ af9be59d0833bd8fa39476f01ee3cc09e5eaf2b7
Joomla Global Config Error Reporting = Maximum

`php cli/joomla.php user:add`

username = mike
name = mike
email = any@valid.com
password = mike

### Expected result

No notices when error reporting set to maximum 

### Actual result

After inputting a password `mike` 

```
PHP Notice:  Trying to access array offset on value of type null in /application/libraries/src/Console/AddUserCommand.php on line 226

Notice: Trying to access array offset on value of type null in /application/libraries/src/Console/AddUserCommand.php on line 226`
```

<img width="971" alt="Screenshot 2020-06-28 at 19 47 58" src="https://user-images.githubusercontent.com/400092/85955716-7ea24800-b978-11ea-9a88-a89ac859fb04.png">

**Comment by alikon** [comment]
please test #29828
