### ISSUE TITLE
Editing image in backend has numbers that are not defined

### ISSUE THREAD

**Issue by jwaisner** [joomla/joomla-cms#29821]
### Steps to reproduce the issue

Go to the media manager on backend
Edit a photo
See image below:

![image](https://user-images.githubusercontent.com/12568201/85956828-1179bd00-b94e-11ea-93e5-b5755102184e.png)

### Expected result

Header or description above numbers to define what they are for and alignment looks off.

### Actual result

Numbers that are not defined.

### System information (as much as possible)

Joomla 4.0-dev-b2

**Comment by ReLater** [comment]
Addition:
The label for this element is:
```
<div class="control-label sr-only"><label id="jform_rotate_distinct-lbl" for="jform_rotate_distinct">
	rotate_distinct</label>
</div>
```
Hidden by class "sr-only".

The label "rotate_distinct" for screen readers looks weird, too.

**Comment by Quy** [comment]
Related #25891. PR #29706 fixes the display issue, but not the label.

![29821](https://user-images.githubusercontent.com/368084/85961994-00877680-b963-11ea-958b-28c4bd13688f.png)

**Comment by Quy** [comment]
Closing. Same as #29943 but with additional info.
