### ISSUE TITLE
[4.0] Privacy Requests Dashboard - Total Requests Count Wrong.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29822]
### Steps to reproduce the issue

Joomla 4.x @ af87f61601b847ba8f924fe7574d0bbfc83ddb59

Create an export request - invalidate it
Create a remove request - invalidate it

Go to the privacy Dashboard: `/administrator/index.php?option=com_cpanel&view=cpanel&dashboard=privacy`

### Expected result

2 Total Requests (or 0 Total requests because they were invalid) 

### Actual result

`1 Total Request`

![Screen Recording 2020-06-28 at 08 56 PM](https://user-images.githubusercontent.com/400092/85957044-d98c6d00-b981-11ea-9463-25488ce290c7.gif)

**Comment by PhilETaylor** [comment]
#Bonus 

Create a new EXPORT request
Create a new REMOVE request

Check Dashboard:

<img width="660" alt="Screenshot 2020-06-28 at 22 02 20" src="https://user-images.githubusercontent.com/400092/85958144-20cb2b80-b98b-11ea-86da-91034c33aea9.png">

Should be 2 Active requests - not 1

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/issues/29826.
