### ISSUE TITLE
[4.0] Clickable area larger than toolbar buttons

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29820]
### Steps to reproduce the issue

Jomla 4.0-dev @ af87f61601b847ba8f924fe7574d0bbfc83ddb59

Total fluke but found that the buttons dont need to be selected to click, there is a small margin below the button that also accepts a click

### Expected result

Only the button, when hovered and changed color, is clickable. 

### Actual result

![Screen Recording 2020-06-28 at 08 44 PM](https://user-images.githubusercontent.com/400092/85956818-4e5ea780-b980-11ea-9c6f-884c74b1dfff.gif)

### System information (as much as possible)

Only tested with Safari on Mac sorry

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29852.
