### ISSUE TITLE
[4.0] Impossible to exit Menu Recovery Mode

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29829]
### Steps to reproduce the issue

Create an admin menu that doesnt have everything 

Menus -> Manager -> Select Administrator -> Click New =>
Title = MyBrokenMenu
Unique Name = MyBrokenMenu
Import a preset = none
Click Save and close
Click "Add a module for this menu"
Select MyBrokenMenu under Administrator in the left menu
Title = MyBrokenMenuModule
Menu to show = MyBrokenMenu
CheckMenu = yes
Position = Menu [menu]
Click save & close 

Enable Menu Recovery Mode

<img width="1314" alt="Screenshot 2020-06-29 at 09 43 30" src="https://user-images.githubusercontent.com/400092/85992949-818b5000-b9ed-11ea-8539-8630cf2227f2.png">

### Expected result

Exit Recovery mode is a hyperlink that is clickable in the menu

### Actual result

No href on the a tag for `Exit Recovery mode` and is unclickable.

<img width="1004" alt="Screenshot 2020-06-29 at 09 44 12" src="https://user-images.githubusercontent.com/400092/85992961-87813100-b9ed-11ea-98b6-97caeef41a62.png">

### System information (as much as possible)

Joomla 4 beta 1

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29833.
