### ISSUE TITLE
[4.0] 3rd Party Dashboard Module -> Modules count doesnt honour trash

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29831]
### Steps to reproduce the issue

Joomla 4.0 beta 1 enable the "3rd Party" Admin Module (This is a core Joomla thing, not actually a 3rd Party provided module) 

Not sure why its called "3rd Party" ???

Anyway, edit the module, set all to `Show Items with Count` 

<img width="1204" alt="Screenshot 2020-06-29 at 12 06 22" src="https://user-images.githubusercontent.com/400092/85997082-f916aa80-ba00-11ea-9262-4d7ac1f822f3.png">

View the module on the "Home Dashboard"

<img width="649" alt="Screenshot 2020-06-29 at 12 06 42" src="https://user-images.githubusercontent.com/400092/85997125-0a5fb700-ba01-11ea-9972-59b888f46650.png">

### Expected result

That the number of MODULES = the number of NON TRASHED modules

Note that the number of ARTICLES and ARTICLE CATEGORIES **DO** honour items that are trashed (E.g They show 0 if all are trashed. The number should show the number of NOT TRASHED items) 

### Actual result

The number of modules includes the number in the trash. 

### System information (as much as possible)

Joomla 4 Beta 1

**Comment by Quy** [comment]
Please test PR #29835
