### ISSUE TITLE
[4.0] Atum screenshot needs updating ;-) 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29832]
### Steps to reproduce the issue

/administrator/index.php?option=com_templates&view=templates&client_id=1

### Expected result

Screenshot needs updating as the Modules look different now after redesigning

### Actual result

administrator/templates/atum/template_preview.png

<img width="320" alt="image" src="https://user-images.githubusercontent.com/400092/85997825-f072a400-ba01-11ea-8065-d13f7d2dc59d.png">

### System information (as much as possible)

Joomla 4 beta 1

**Comment by zero-24** [comment]
Can you send a PR that replaces this file?

**Comment by PhilETaylor** [comment]
I could, but simple things like this are great first time PR's for new contributors... lets not always steal their glory :-)

**Comment by zero-24** [comment]
Thanks @brianteeman

**Comment by PhilETaylor** [comment]
LMAO

**Comment by zero-24** [comment]
?

**Comment by PhilETaylor** [comment]
I was laughing in the car at...

> simple things like this are great first time PR's for new contributors... lets not always steal their glory :-)

And then their glory was stolen moments later

It seems Joomla is not interested in on boarding new contributors with easy tasks.... not like Symfony does....

**Comment by brianteeman** [comment]
It was already done before your childish comment. Comments like that are what stops people contributing. Always with the personal insults I guess nothing has changed in the last 15 years

**Comment by zero-24** [comment]
Well sad that this is your view of things. The other day people complain that we have many open issues today someone picked up an issue and created an patch for it :-(

**Comment by PhilETaylor** [comment]
I actually did not notice it was you who submitted it as I’m in the car - the only personal attacks - sustained and upheld by repeated CoC reports is you.l - but yet you repeatedly threaten the project with legal action if they take action against you - all documented.
