### ISSUE TITLE
Click counter not counting correctly for multiple ads/banners with same click/destination URL

### ISSUE THREAD

**Issue by sm0rgm** [joomla/joomla-cms#29838]
### Steps to reproduce the issue
Create two ads/banners which links to the same click/destination URL. Set "Register clicks" to yes under banner details.
Publish the two ads through via a com_banner module. Visit the site frontend. Click on each ad/banner in the frontend, one time for each ad/banner. 

### Expected result
Clicks on each ad/banner should be counted on the corresponding ad/banner counter, i.e. in the example above the counter for each ad should be 1 and 1 after clicking each ad/banner one time.

### Actual result
All clicks are registered on the ad/banner with the lowest ID, i.e. the counter for the first ad/banner is 2 and the second is 0.

### System information (as much as possible)
PHP version	7.3.10
Web server	Apache/2.4.29 (Ubuntu)

**Comment by SharkyKZ** [comment]
I can't reproduce the issue.

**Comment by sm0rgm** [comment]
I tested it on a clean joomla install and you are correct, it can not be reproduced. It is probably caused by a third party extension or modification in the customers site. My bad, I should have tested this on a clean install before opening this issue. I will close it now. No further action is needed. Sorry for the inconvenience.
