### ISSUE TITLE
[4.0] Debug toolbar not displaying log items

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29843]
### Steps to reproduce the issue

Enable plugin `System - Debug` - Enable ALL the options in the plugin turning everything to `show` and `yes`

Browse the site

### Expected result

Something to show up in the `log` tab of the debug bar

### Actual result

Nothing is shown in the debug log

Something is logged in /administrator/logs/ 

```
jcontroller.log.php
deprecated.php
error.php
everything.php
```

<img width="812" alt="Screenshot 2020-06-29 at 21 30 42" src="https://user-images.githubusercontent.com/400092/86053037-cfd13b00-ba4f-11ea-98e6-4bbf0b33af60.png">

### System information (as much as possible)

Joomla 4.0-dev @ 5b9d0f29040ebfb31c9af8ab0c3372dc9081bcc8

**Comment by SharkyKZ** [comment]
Duplicate https://github.com/joomla/joomla-cms/issues/25675.

**Comment by PhilETaylor** [comment]
Not really the same. You are talking about a totally different tab in the other issue.

**Comment by SharkyKZ** [comment]
Reopening this but I'm pretty sure it's the same issue as #25675.

**Comment by PhilETaylor** [comment]
Having gone and read all the history from Jul 2019 in #25675 Im guessing, like you, that this issue is covered by that release blocker so Im closing here :) Thanks.
