### ISSUE TITLE
How do you upgrade from 4.0-alpha-12 to 4.0-beta-1 ??

### ISSUE THREAD

**Issue by chris001** [joomla/joomla-cms#29841]
### Steps to reproduce the issue
Install `4.0.0-alpha-12` on an empty website, add plenty of Joomla 4 compatible extensions, etc.
Try to get a `4.0.0-beta-1` upgrader package from github, but there's only an upgrader from `3.x` ?!?!

### Expected result
There should be an upgrader package to upgrade you from 4.0.0-alpha-x also.
OR instructions on how to upgrade from 4.0.0-alpha-12 to 4.0.0-beta-1 from the command line using `git`.

### Actual result
The upgrader from `3.x to 4.0.0-beta-1` fails to install, with vague error messages.

### System information (as much as possible)
Linux Debian server
`Joomla 4.0.0-alpha-12`

### Additional comments
Share the `git` commands to upgrade from `4.0.0-alpha-12` to `4.0.0-beta-1`.

**Comment by brianteeman** [comment]
those error messages might be "vague" to you but they have meanings so it would be helpful to know what they are

**Comment by Quy** [comment]
Download the nightly builds: https://developer.joomla.org/nightly-builds.html

**Comment by chris001** [comment]
> those error messages might be "vague" to you but they have meanings so it would be helpful to know what they are

My bad!  Here's a step by step with error messages:

In `php.ini`:
`upload_max_filesize = 50M`

1. From home dashboard in Joomla 4.0.0-alpha-12 I click `Joomla Update`.
2. Click `Upload & Update` tab.
3. It says:
`Joomla package file 	`
`Maximum upload size: ‎20.00 MB`

4. Click Browse.

5. Select `Joomla_4.0.0-beta1-Beta-Update_Package.zip` (24 MB)

6. Click `Upload & Install`.

7. Error (admin site error popup)

`COM_INSTALLER_MSG_INSTALL_WARNINSTALLUPLOADERROR`
`COM_INSTALLER_MSG_WARNINGS_SMALLUPLOADSIZE`


In the page error message:

`An error has occurred.`

`    403 Access forbidden. `

`(Return to Dashboard)` button.

**Comment by chris001** [comment]
> Download the nightly builds: https://developer.joomla.org/nightly-builds.html

Thanks.  Is there a `git` command to install these over the top of an existing `4.0.0-alpha12` instance?

**Suggestion, it'd be nice for the Joomla Updater to be able to `git` or `wget` these nightly builds and upgrade packages on the joomla server, directly from github, and from the joomla.org nightly builds site, and thereby get around the PHP client browser `upload_max_filesize` limit!**

**Comment by Quy** [comment]
Use custom update server: https://update.joomla.org/core/nightlies/next_major_list.xml

**Comment by chris001** [comment]
I've fixed the issue with uploading.  It was caused by PHP reading values in from the global `php.ini` not the local file, as soon as I edited the global `php.ini` file setting `upload_max_filesize` to `50M` then the upload worked, and it upgraded.

However, there is still an error, with no clear way to resolve it from inside the admin site:
```
Warning

There are tables not up to date!
Joomla! 4 Content Management System.
One Problem

    The Joomla! Core database tables have not been converted yet to UTF-8 Multibyte (utf8mb4).
    159 database changes were checked.
    252 database changes did not alter table structure and were skipped.

	4.0.0-2020-05-29 	‎4.0.0-beta1 	N/A 	205
```
How to resolve this error?  Shouldn't Joomla issue the commands to MySQL to convert all to `utf8mb4`?  Does it expect the admin to run a command line command?  It's not a very clear/simple user experience here!

**Comment by PhilETaylor** [comment]
> It's not a very clear/simple user experience here!

The Joomla Project has never officially supported Alpha to Beta upgrades and doesn't cater for "users" at this stage of development. 

> How to resolve this error? Shouldn't Joomla issue the commands to MySQL to convert all to utf8mb4?

Login to Admin -> System -> Database -> Select Joomla CMS -> Click Update Structure

**Comment by richard67** [comment]
> The Joomla Project has never officially supported Alpha to Beta upgrades and doesn't cater for "users" at this stage of development.

Exactly. Details can be found in the following discussion in the Joomla Support Forum: [https://forum.joomla.org/viewtopic.php?p=3607365&sid=e2cbc571de4b7fafa4f9b6befa948ea5#p3606084](https://forum.joomla.org/viewtopic.php?p=3607365&sid=e2cbc571de4b7fafa4f9b6befa948ea5#p3606084).

**Comment by chris001** [comment]
> > It's not a very clear/simple user experience here!
> 
> The Joomla Project has never officially supported Alpha to Beta upgrades and doesn't cater for "users" at this stage of development.

I meant to say, the UX for the admin site is not clear here in terms of the error message is overly vague as it fails to say how to resolve this charset issue in a way that won't break this joomla instance.  Since it's just commands to the database, that will change the charsets, why on earth doesn't it just contain the commands in the code and fix the problem for us rather than leave it up to a human?

> > How to resolve this error? Shouldn't Joomla issue the commands to MySQL to convert all to utf8mb4?
> 
> Login to Admin -> System -> Database -> Select Joomla CMS -> Click Update Structure

I did this already, and yet, it continues to complain with the same exact error, as if it didn't actually change the charsets of all tables, columns and rows (?).
After clicking Update structure, it still says: 
```
Warning

There are tables not up to date!
```

**Comment by richard67** [comment]
@chris001 The reason for it is because database and code don't fit together, as I've tried to explain above, because you have updated an alpha to beta. Try to update a 3.10 nightly build to 4.0 Beta 2 or recent nightly and you will see there is not such a problem. Same when you update a 4.0 Beta 1 to 4.0 Beta 2.

**Comment by chmst** [comment]
As @richard67 explained, it is not an issue.

**Comment by chris001** [comment]
Isn't the standard Joomla way of upgrading from one version to the next, the new version, in this case 4.0 Beta, is supposed to come with a SQL file to upgrade the database of 4.0 Alpha so that it'll be in the schema expected by the code of 4.0 Beta?

**Comment by richard67** [comment]
@chris001 Between alpha and beta we had to change the existing 4.0 schema update SQL files a few times and these will not run again if your database schema version is already higher. We had to do that because otherwise we would have some 500 4.0 update sql scripts now. So please accept what I and others say who have done these work and know the database well enough to know what they are talking about, ok?

**Comment by PhilETaylor** [comment]
I say again:

> The Joomla Project has never officially supported Alpha to Beta upgrades and doesn't cater for "users" at this stage of development.
