### ISSUE TITLE
[4.0] X problems on fancy select boxes (Safari)

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29846]
### Steps to reproduce the issue

History:  #29750
Previous PR https://github.com/joomla/joomla-cms/pull/29761 from @Quy 

Retested today, forked from [comment](https://github.com/joomla/joomla-cms/pull/29761#issuecomment-651377972) in https://github.com/joomla/joomla-cms/pull/29761 above so not lost in closed PR. 

### Expected result

X close to the right hand side

### Actual result

The X is too far left. 

<img width="439" alt="Screenshot 2020-06-29 at 22 25 42" src="https://user-images.githubusercontent.com/400092/86057663-81279f00-ba57-11ea-91ab-699bb2929edb.png">

To replicate just install the above and then edit the first module on the home dashboard after login

Also the actual "clickable area" appears to be HUGE! 

see: 

![Screen Recording 2020-06-29 at 10 27 PM](https://user-images.githubusercontent.com/400092/86057864-d6fc4700-ba57-11ea-9af5-0cbc86f3b985.gif)

### System information (as much as possible)

Safari Version 13.1.2 (15609.3.2) on Mac with Joomla 4.0-dev @ 5b9d0f29040ebfb31c9af8ab0c3372dc9081bcc8 (today)

**Comment by infograf768** [comment]
Confirmed for SAFARI only on 4.0-dev

**Comment by adj9** [comment]
I confirm, use Safari 13.0.5.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29846">issues.joomla.org/tracker/joomla-cms/29846</a>.</sub>

**Comment by PhilETaylor** [comment]
Also please consider and check FRONTEND editing of an article -  publishing tab

<img width="832" alt="Screenshot 2020-07-05 at 15 30 18" src="https://user-images.githubusercontent.com/400092/86534919-75632f00-bed4-11ea-88f8-b6c276dabd77.png">

**Comment by PhilETaylor** [comment]
Also note the X on tags in filter options on frontend - has a X when nothing is even selected and when clicked does a form action...

![Screen Recording 2020-07-05 at 03 33 08 PM](https://user-images.githubusercontent.com/400092/86534989-063a0a80-bed5-11ea-914f-70a815d28c2d.gif)

**Comment by richard67** [comment]
Closing as having a pull request. Please test #30739 .
