### ISSUE TITLE
[4.0] Debug Bar doesnt show on error pages

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29844]
### Steps to reproduce the issue

One of the reasons to enable the `System - Debug` plugin is for debugging - the problem is that it doesnt actually load on a page that is an error page! 

To replicate, login to Joomla 4 admin and enable the `System - Debug` plugin 

Then create a PHP error (easy to do, edit administrator/components/com_cpanel/src/Controller/DisplayController.php and add 

```php
Factory::isAdmin();
```

after 

```
public function display($cachable = false, $urlparams = array())
{
```

Then visit `Home Dashboard` menu item

### Expected result

Same as the actual result below - but with the debug toolbar at the bottom as well so that the request can be inspected. 

<img width="1093" alt="Screenshot 2020-06-29 at 22 16 41" src="https://user-images.githubusercontent.com/400092/86056978-3d806580-ba56-11ea-9a2a-886e75e1f574.png">

### Actual result

<img width="922" alt="Screenshot 2020-06-29 at 22 15 08" src="https://user-images.githubusercontent.com/400092/86056859-06aa4f80-ba56-11ea-8f50-5c7dfcdff6e6.png">

### System information (as much as possible)

Joomla 4 beta 1

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/30394.
