### ISSUE TITLE
[4.0][cli] user:add gets into a loop in Windows

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#29851]
### Steps to reproduce the issue
see #29814

### Expected result
User added correctly.

### Actual result
After an email address is entered, goes into a loop, displaying repeatedly
"Please enter a password:
>The system cannot find the path specified"

### System information (as much as possible)
Beta2-dev of 30 June out-of-the-box. No extensions installed, no PRs applied.

Windows 10 Wampserver 3.2.2 Apache 2.4.43 MySQL 8.0.20 PHP 7.4.7.

The site was installed in document root of a virtual host C:\www\joomla4.
Debug System: Yes, System - Debug plugin enabled, Log Almost Everything: Yes

### Additional comments
No PHP messages recorded in php_error.log, only deprecation-notes warnings in everything.php.

![screen shot 2020-06-30 at 07 38 24](https://issues.joomla.org/uploads/1/9a2731044da70c5d1fec92ca2eb05096.jpg)

**Comment by Quy** [comment]
Not reproducible. WampServer 3.2.0, PHP 7.4.0, MariaDB 10.4.10.

**Comment by Quy** [comment]
> Wampserver 3.2.2 Apache 2.4.43 MySQL 8.0.20 PHP 7.4.7.

How to upgrade to these versions?

**Comment by toivo** [comment]
@Quy Those versions are available from Wampserver forum sticky [WAMPServer 3 All you need to know](http://forum.wampserver.com/read.php?2,138295 "Wampserver 3.2.2 and latest extensions") and presented better in the alternative repo at [http://wampserver.aviatechno.net](http://wampserver.aviatechno.net "http://wampserver.aviatechno.net")

BTW, reproduced the behaviour also in Beta2 using Wampserver 3.2.2  Apache 2.4.43 MariaDB 10.4.13 PHP 7.4.7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29851">issues.joomla.org/tracker/joomla-cms/29851</a>.</sub>

**Comment by brianteeman** [comment]
Can not replicate 
Windows 10, php 7,4,7 apache 2.4.41

C:\htdocs\joomla-cms>php cli/joomla.php user:add

Add user
========

 Please enter a username:
 > brian

 Please enter a name (full name of user):
 > brian teeman

 Please enter an email address:
 > brian@example.com

 Please enter a password:
 > 

 Please select a usergroup (separate multiple groups with a comma):
  [0] Public
  [1] Registered
  [2] Author
  [3] Editor
  [4] Publisher
  [5] Manager
  [6] Administrator
  [7] Super Users
  [8] Guest
  [9] test
 > 1


 [OK] User created!

**Comment by toivo** [comment]
The message 'The system cannot find the path specified' must be a message from Windows 10 or one of the installed  applications, not Joomla.  The utility sfc /scannow repaired a small number of directories, reporting for example "Warning: Overlap: Directory \??\C:\Program Files (x86)\ is owned twice or has its security set twice" but those fixes did not get rid of the loop in user:add.  Closing this now.
