### ISSUE TITLE
Linking existing article to a new article body via CMS Content not working

### ISSUE THREAD

**Issue by Shedyk** [joomla/joomla-cms#29858]
### Steps to reproduce the issue
Create a site via launch.joomla.org
Install sample data
Click on add article icon 
Fill in article title
Click on CMS Content dropdown
Click on +article from the dropdown list
Dialog opens listing existing article
Click on an article to be linked to.

### Expected result
On clicking the article title it should add Link text to the new article body linking to the selected article

### Actual result
Upon clicking the article on the list, nothing happens. 

### System information (as much as possible)
PHP Built On 	Linux lamp129.cloudaccess.net  
Database Type 	mysql
Database Version 	5.7.23-cll-lve 
PHP Version 	7.3.17 
Joomla!  4.0.0-beta2-dev Development [ Mañana ] 30-May-2020 21:13 GMT 
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0 
![screen shot 2020-06-30 at 16 39 01](https://issues.joomla.org/uploads/1/9442f6c013c9a97b74a3b33d464a070f.png)
### Additional comments

[systeminfo-2020-06-30T12 36 24-04 00.txt](https://issues.joomla.org/uploads/1/863fa9df2d7eefb2cd34f462ef239618.txt)![screen shot 2020-06-30 at 16 39 01](https://issues.joomla.org/uploads/1/3c20998006fecedb102df4ea52e8759e.png)

**Comment by chmst** [comment]
Confirmed. 
Worked in beta1 but not in beta2. Checked with codemirror and tinyMCE.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29858">issues.joomla.org/tracker/joomla-cms/29858</a>.</sub>

**Comment by ReLater** [comment]
Please test https://github.com/joomla/joomla-cms/pull/29860
