### ISSUE TITLE
List limit of contact list by category is 20

### ISSUE THREAD

**Issue by titusvk** [joomla/joomla-cms#29866]
### Steps to reproduce the issue

Create 21 contacts with com_contacts
Create Menu Item with Menu Item Type "List Contacts in a Category"
Set Contact Display Options "# Articles to List" to "All"

### Expected result

all (9999)

### Actual result

20

### System information (as much as possible)

Contact Category Model shows $app->get('list_limit') is set to 20

### Additional comments

Quick fix with system plugin:

    function onAfterRoute()
    {
        // Contakt List Bug - Override List Limit
        
        Factory::getApplication()->set('list_limit',999);
    }

**Comment by PhilETaylor** [comment]
> Set Contact Display Options "# Articles to List" to "All"

try `# Contacts to List` on the `list layouts` tab as that is the param `contacts_display_num` which is used as a limit here https://github.com/joomla/joomla-cms/blob/16f284fa7852c6f081da9dde4ef01c90a75e862d/components/com_contact/src/Model/CategoryModel.php#L289

**Comment by brianteeman** [comment]
Perhaps there is a bad translation here?

**Comment by SharkyKZ** [comment]
The option does what it says. It sets the number of articles. There's no option to set number of contacts in J3. Only in J4.

**Comment by PhilETaylor** [comment]
> Only in J4.

doh. I assumed Joomla 4. Sorry.

**Comment by brianteeman** [comment]
Pagination (list limit) for contacts is the global value set in configuration.php

**Comment by SharkyKZ** [comment]
Closing as expected behavior for J3.

**Comment by AndySDH** [comment]
@SharkyKZ
> There's no option to set number of contacts in J3. Only in J4.

Well, this has now been removed again even from J4, great -_- see: https://github.com/joomla/joomla-cms/pull/30904

@titusvk 

> function onAfterRoute()
{
    // Contakt List Bug - Override List Limit
    
    Factory::getApplication()->set('list_limit',999);
}

Had you tested this fix? I tried it, it doesn't work.
