### ISSUE TITLE
[4.0] Patchtester broken after update to Beta-3-Dev

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#29862]
### Steps to reproduce the issue

Update to Beta-3-Dev
Go to Patchtester and click Fetch Data

### Expected result

Latest patches to test

### Actual result

A popup dialog box says 'Preparing to Fetch GitHub data. Making sure all is well to fetch data. Sit tight.'
But nothing happens.

### System information (as much as possible)

Mac OSX / Firefox and Google Chrome

### Additional comments

I am out of testing until this gets fixed.

**Comment by particthistle** [comment]
@ceford,  @roland-d pointed out solution when I asked it on the weekend.

If you had patches applied that were not reverted before the Beta-3-Dev was installed, you need to go and empty the #_patchtester_tests table via phpMyAdmin, and then the routine  will work and fetch the new data.

Roland's indicated he's looking at working on an update to the Patch Tester component to allow you to flush the table when you make the refresh.

**Comment by ceford** [comment]
Thanks for the tip. I had one entry in the tests table. I deleted it and now Patchtester works normally. I guess we leave this issue open for others to find. Back to testing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29862">issues.joomla.org/tracker/joomla-cms/29862</a>.</sub>

**Comment by brianteeman** [comment]
No  this should be closed. This is not the place to document "known issues"
