### ISSUE TITLE
[4.0][UX]Install from Web tab shows extensions incompatible with Joomla 4

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#29864]
### Steps to reproduce the issue
Go to System - Install - Extensions - Install from Web. 

### Expected result
Extensions compatible with Joomla 4 are listed.  No extensions compatible only with Joomla 3 are shown.

### Actual result
The list starts with Akeeba Backup, which is compatible with J4 Beta, but then continues with BreezingForms Pro, RSForm! Pro and AcyMailing starter, none of which are compatible with Joomla 4 Alpha or Beta. 

### System information (as much as possible)
Beta3-dev from 1 July
Windows 10 Wampserver 3.2.2  Apache 2.4.43 MySQL 8.0.20 PHP 7.4.7

### Additional comments
Changed Minimum Extension Stability of the plugin 'Install - Install from Web' to Beta but it did not make any difference and should not be necessary.  Joomla 4 should display only extensions that have been tagged as compatible with Joomla 4 in JED.  Otherwise users try to install Joomla 3 extensions, which attempts will fail in most cases.

**Comment by Quy** [comment]
Duplicate #29366
