### ISSUE TITLE
[4.0] Cannot save articles when Workflows are disabled

### ISSUE THREAD

**Issue by regularlabs** [joomla/joomla-cms#29872]
I was getting errors on my Joomla 4.0b setup, so decided to create a fresh setup using todays 4.0b2 release.

By default the Workflows are switched off (PS: incredibly difficult to find the setting for this!!!).
But when it is switched off, saving an article throws errors.
Resulting in the workflow_associations data not being saved in the table.
Resulting in the article not being there in the article list view (it is there in the content table).

So it seems like a lot of stuff is hardcoded reliant on the Workflows being enabled. If it isn't, stuff falls apart.

I recommend this gets tested thoroughly!

**Comment by brianteeman** [comment]
> saving an article throws errors.

Was this in the front end or the admin?

What were the errors?

**Comment by regularlabs** [comment]
Sorry, this issue seems unrelated to the workflows. But with (too) long content.

**Comment by regularlabs** [comment]
New issue: #29873
