### ISSUE TITLE
[4.0] Impossible to turn off some quick icons (because they are not quick icons)

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29875]
### Steps to reproduce the issue

Login to Joomla 4 backend
see: 

<img width="655" alt="Screenshot 2020-07-01 at 13 13 25" src="https://user-images.githubusercontent.com/400092/86242929-5ba4ad80-bb9d-11ea-80e9-80105785c5b2.png">

Click Cog - Select Edit

<img width="1145" alt="Screenshot 2020-07-01 at 13 18 42" src="https://user-images.githubusercontent.com/400092/86242955-65c6ac00-bb9d-11ea-9363-fb35d6de99d5.png">

### Expected result

The ability to `Hide` the 4 default quick icons

### Actual result

No ability to `Hide` the 4 default quick icons

**Comment by brianteeman** [comment]
They are plugins

![image](https://user-images.githubusercontent.com/1296369/86244672-3a918c00-bba0-11ea-9edd-3248ddafc5de.png)

**Comment by PhilETaylor** [comment]
so either 

1) All the others in the list should be made into quick icon plugins too?

or 

2) The existing plugins should be added to the edit list

Makes no sense to have some being plugins and some not right?

**Comment by PhilETaylor** [comment]
Without them all being plugins - there is no way to affect the ordering of the icons either - you can only order the last 4 

<img width="641" alt="Screenshot 2020-07-01 at 13 42 18" src="https://user-images.githubusercontent.com/400092/86245093-e33feb80-bba0-11ea-9cec-7f2af98c41d8.png">

**Comment by brianteeman** [comment]
pull requests welcome

**Comment by PhilETaylor** [comment]
So you keep saying, but before wasting considerable time its nice to get OTHERS opinions if this is actually something that can/should be improved, and to find out why it was not done that way initially... there was obviously some reason someone never did all the hard work previously...

**Comment by rdeutz** [comment]
Could you please let your personal dislikes of each other out of github, thanks.

**Comment by PhilETaylor** [comment]
@rdeutz I dont believe I have said anything out of order... I just feel that Brian doesn't speak on behalf of the whole project... his opinion is just one opinion and shooting people down - consistently - not just me - by demanding "pull requests or shut up" attitude is unacceptable. If the Joomla Project actually took safeguarding of contributors seriously.... I digress...

**Comment by PhilETaylor** [comment]
For example, the SITE area also uses these same "non quick icon" icons ... so re-implementing them all as quick icon plugins would mean they could be shared.  However then the "group" parameter of quick icons would have to change, to allow multiple groupings instead of just one. 

Its not a quick 5 min pull request... it has bigger issues and knock on effects and thus should be DISCUSSED instead of just demanding a pull request. 

<img width="1189" alt="Screenshot 2020-07-01 at 13 53 09" src="https://user-images.githubusercontent.com/400092/86246001-3a928b80-bba2-11ea-9ce7-dc4b8a943763.png">

**Comment by brianteeman** [comment]
Don't forget that there are a large number of extensions that ship with quickicon plugins and now that they are more prominent in joomla 4 then there will be more developers wanting to add one for their own extension
