### ISSUE TITLE
[4.0][New feature?] Database schema update quick icon check 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29874]
### Steps to reproduce the issue

install Joomla 4 beta 1 
upgrade the FILES ONLY to Joomla 4 beta 2
Totally forget there might be schema changes

### Expected result

That something slaps you in the face to alert you that there are schema updates to apply 

### Actual result

Well the actual result is the same as its ever been - nothing slaps you in the face unless you go looking for it, however there is the perfect opportunity for a new quick icon in this screen:

<img width="655" alt="Screenshot 2020-07-01 at 13 13 25" src="https://user-images.githubusercontent.com/400092/86242629-e46f1980-bb9c-11ea-9d8f-0c301d226d49.png">

The code is already written for the JSON endpoint to get the data as its used elsewhere:

https://github.com/joomla/joomla-cms/blob/16f284fa7852c6f081da9dde4ef01c90a75e862d/administrator/components/com_installer/src/Controller/DatabaseController.php#L79

<img width="438" alt="Screenshot 2020-07-01 at 13 20 53" src="https://user-images.githubusercontent.com/400092/86243130-bb9b5400-bb9d-11ea-8c1f-02dcfd7cc77e.png">

It just needs the quick icon created

**Comment by zero-24** [comment]
The update files only approach is not supported also also has other issues like missing script execution as well as missing insert queriey. etc. The only supported upgrade path is via com_joomlaupdate and this should not be changed in my view.

This does not oppose the possibel quick icon. Can you create one and send the PR based on the json api you mention? I personally would think that this would be than maybe an optional by default disabled icon but could make sense in some cases of development sites. What does others think?

**Comment by PhilETaylor** [comment]
> The update files only approach is not supported also also has other issues like missing script execution as well as missing insert queriey. etc. The only supported upgrade path is via com_joomlaupdate and this should not be changed in my view.

Well what's the point in having a schema checker then ;-) haha The fact is it can and does happen... 

502 sites out of 63,603 sites in mySites.guru currently have a schema mismatch with the version they are running. 

There is a "Joomla is up to date" icon, but Joomla is *not actually up to date* unless the schema version matches...

**Comment by zero-24** [comment]
As mention there are valid cases thats the reason i would not oppose a PR.

**Comment by PhilETaylor** [comment]
well its already checking on the system page and if someone is going to bother addressing the fact we have tonnes of "[quick icons that are not quick icons](https://github.com/joomla/joomla-cms/issues/29875)" then this can be addressed then. 

Closing for now.
