### ISSUE TITLE
[4.0] Warning warning 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29887]
### Steps to reproduce the issue

Joomla 4.0-dev @ 16f284fa7852c6f081da9dde4ef01c90a75e862d

Login to admin 
System -> Installer - Extensions
Wait "forever" for the "Install from web" iframe to load zzzzz
Click Install from Folder tab
Click Check and Install (without having anything in tmp to install) 
Note the alert at the top of the page:  `Warning` Capital W 

<img width="370" alt="Screenshot 2020-07-01 at 22 02 03" src="https://user-images.githubusercontent.com/400092/86291166-82d39d00-bbe6-11ea-882b-babd21334c09.png">

Then go to Install from URL tab
leave the URL field blank
Click Check and Install 
Note the alert at the top of the page: `warning` LowerCase W 

<img width="317" alt="Screenshot 2020-07-01 at 22 02 46" src="https://user-images.githubusercontent.com/400092/86291240-9c74e480-bbe6-11ea-9a16-bde3a995bedb.png">

### Expected result

Consistency, possibly `Warning`

### Actual result

The Javascript rendered alert is `warning` whereas a PHP rendered alert is `Warning`

### System information (as much as possible)

Safari on Mac

**Comment by Quy** [comment]
Please test PR #29889
