### ISSUE TITLE
[4.0] Notice: Undefined property: stdClass::$version

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29888]
### Steps to reproduce the issue

Joomla 4.0-dev @ 16f284fa7852c6f081da9dde4ef01c90a75e862d install via git (see later)

Login to admin as super admin 

Crank up your debug mode to true and your error reporting to maximum in Global Config. 

Install a component (I suggest Akeeba Backup) 

using a git client you can see all the files added by Akeeba, trash those! 

(So what this is emulating is a database with Akeeba installed, but the Akeeba files have been deleted on the hard disk, people will often delete files using FTP)

Login to admin as a super admin and navigate 
System -> Manage / Extensions
Find the page with all the Akeeba items on it (I find sorting by ID Desc brings them to the first page) 
select them all and click the REFRESH CACHE toolbar button

### Expected result

No PHP notices

### Actual result

```
Notice: Undefined property: stdClass::$version in /application/administrator/components/com_installer/tmpl/manage/default.php on line 116

Notice: Undefined property: stdClass::$version in /application/administrator/components/com_installer/tmpl/manage/default.php on line 132
```

<img width="1304" alt="Screenshot 2020-07-01 at 22 41 20" src="https://user-images.githubusercontent.com/400092/86294256-165b9c80-bbec-11ea-9f2f-3fd1bba65032.png">

**Comment by chmst** [comment]
Please test #29946<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29888">issues.joomla.org/tracker/joomla-cms/29888</a>.</sub>
