### ISSUE TITLE
[4.0] Language Override Prefill Incorrect after pagination load

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29891]
### Steps to reproduce the issue

4.0-dev login as super admin 
Navigate to 
System -> [Manage]Language Overrides
Select English (United Kingdom) - Administrator
Click New
On the right hand side select "Search for Constant"
Enter search text as `warning` for example 
Click search 
You will get your first 10 results - click any of them and note that the left hand side boxes are correctly prefilled with what you click

Eg: 

<img width="1593" alt="Screenshot 2020-07-01 at 23 48 29" src="https://user-images.githubusercontent.com/400092/86298318-6428d280-bbf5-11ea-846a-c074adfb1179.png">

Now click the More Results blue button - note that another 10 items load below

Click one of these 10 that loaded AFTER you clicked the "More Results" button

Note now that the left hand side (scroll up if needed) boxes are prefilled with information UNCONNECTED to the item you just clicked !

If you click the FIRST of the new results (the 11th on the screen now) then the details of the 2nd item are used to prefill the left boxes. 

### Expected result

The clicked item to be used to populate the left boxes

### Actual result

![Screen Recording 2020-07-01 at 11 52 PM](https://user-images.githubusercontent.com/400092/86298611-0a74d800-bbf6-11ea-9f50-1ec23a50fdb3.gif)

### System information (as much as possible)

safari on Mac

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29892.
