### ISSUE TITLE
Editor button Articles not working

### ISSUE THREAD

**Issue by ced1870** [joomla/joomla-cms#29897]
### Steps to reproduce the issue
Open article >> click on the "CMS Content" button in Tiny MCE
>> select Articles, the popup opens
>> click on an article
>> nothing happens

 

### Expected result
to load the tag with article ID in the editor

### Actual result
nothing

### System information (as much as possible)
Joomla 4 beta2

### Additional comments

it works for the modules, but not the articles

**Comment by ChristineWk** [comment]
confirm. javascript:void(0)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29897">issues.joomla.org/tracker/joomla-cms/29897</a>.</sub>
4.0.0-beta3-dev

**Comment by brianteeman** [comment]
Please check #29860

**Comment by infograf768** [comment]
Closing as we have a patch already merged in 4.0-dev
