### ISSUE TITLE
[4.0] Installation: Token error OR Warning when trying to install again another additional language

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#29896]
### Steps to reproduce the issue
Install a clean 4.0-dev.
When you get to the first screen which lets you `Install Additional Languages`, click to install a new language.
Select or French fr-FR or German de-DE and click `Next` button.

Test 1
In the next screen choose a default admin and site language (default to en-GB is OK) and click on `Set default language` (_no need for a chevron there_).
Then click again on `Install Additional Languages` button (_the chevron should be left and placed before the text in LTR, the opposite in RTL_).
Select a language you did not install formerly (French or German) and click `Next` button

-----------------
Test 2 (with a new clean install)

Do not click on `Set default language` but click again on `Install Additional Languages`
Do NOT select any language and click on `Next` button.
IMPORTANT NOTE FOR test2: 
Test can also be done when we first access to `Install Additional Languages` and do not choose any language to install although we do have some message for that in the controller (and that message is not displayed...)
```
	public function languages()
	{
		$this->checkValidToken();

		// Get array of selected languages
		$lids = $this->input->get('cid', [], 'array');
		$lids = ArrayHelper::toInteger($lids, []);

		if (!$lids)
		{
			// No languages have been selected
			$this->app->enqueueMessage(Text::_('INSTL_LANGUAGES_NO_LANGUAGE_SELECTED'), 'warning');
		}
		else
		{
			// Get the languages model.
			/** @var \Joomla\CMS\Installation\Model\LanguagesModel $model */
			$model = $this->getModel('Languages');

			// Install selected languages
			$model->install($lids);
		}

		// Redirect to the page.
		$r = new \stdClass;
		$r->view = 'remove';

		$this->sendJsonResponse($r);
```
Apparently, one of the problem here, which makes it behave differently in J4 vs J3 is that we are in the same `remove` view (J3 uses the `defaultlanguage` view. for the redirect). The other is that the method used is `languages()` and not the specific `execute`.

### Expected result
Test1
The language is installed and we are redirected again to the screen when one can choose default site and admin languages. OR the `Install Additional Languages` button should not be displayed anymore.

Test2
We are redirected to the former screen where you can select default languages, etc.

### Actual result
Test 1
We get a token error.

![installationtokenerror](https://user-images.githubusercontent.com/869724/86335069-52274e00-bc4e-11ea-80db-7bd38900fba9.gif)

Test 2
We get a warning

<img width="804" alt="Screen Shot 2020-07-02 at 10 44 44" src="https://user-images.githubusercontent.com/869724/86337255-22c61080-bc51-11ea-9fd8-7eb856131c25.png">

For both tests, only way to get out of this screen is then to click on `Skip` button.

**Comment by infograf768** [comment]
@astridx

**Comment by astridx** [comment]
1. Install a clean 4.0-dev and made sure, that no language is left from a previous installation.
2. I clicked to install a new language and selected de-DE and installed it via next.

Test 1
3. I choosed German for admin and site default language and clicked on set default language
4. I clicked again on install additional language and installed fa-IR

Everything was fine, no token error.

Test 2
5. I deleted the `configuration.php` and the languages (de-DE, fa-IR) in the site and admin language folders.
6. i deleted the cache
7. I made a new installation
8. I installed fr-FR as additional language
9. I did NOT change the default language
10. I clicked again on install additional language
11. I clicked on next
12. I see the warning  `Warning No languages have been selected to be installed.`

That is fine for me.

If I select after step 12 a language and click on `next` again, everything is fine. If I click on `skip`, the form is messed up.

**The only thing I notice: The form looked messed up, if you click on on the Skip-Button, because the the first section is missing (congrads).**

I tested in firefox and google chrome on ubuntu.

**Comment by infograf768** [comment]
Houston, we have a problem...
I am testing on macintosh Firefox with Mamp

**Comment by infograf768** [comment]
Tested again. I still have the token issue. I have to click a second time on `Next` after selecting a language when I go back to Install Additional Languages for it to work fine.

@astridx 
Could that help you find out what's going on?

Note: I can't reproduce anymore the test2 findings above. I do rightfully get `No languages have been selected to be installed.`, the only difference with J3 being that the same page is displayed instead of automatically going to next page, therefore forcing to use `Skip`.

**Comment by chmst** [comment]
My experinece on win10, xampp, php version 7.4 

install additional language (chervron always is right on the button)
choose german and cklick button next
install german
set german as default.

install additional language
choose french and click next

**The token error  comes as described.**

-------------------------------------------------------

install additional language (chervron right on the button)
choose german and cklick button next
install german

install additional language 
no language selected

Warning
No languages have been selected to be installed (as expected)

choose french
click next
french is installed  (as expected)

**Comment by infograf768** [comment]
Tks for testing @chmst 
Good to know that I am not totally Covided. 😅

**Comment by astridx** [comment]
@chmst Thank you 

Am I missing something? Does anyone see this token error message on Linux?

**Comment by richard67** [comment]
> Does anyone see this token error message on Linux?

Test 1: I can reproduce the token error when exactly proceeding as described in the description and in @chmst 's test here https://github.com/joomla/joomla-cms/issues/29896#issuecomment-653451318 . Server is Apache 2.4 on Kubuntu 19.10, which is a kind of Linux, PHP 7.3, MySQL 8.0.20, Browser = Firefox 78.0.1 (64-Bit) on Windows 10.

**Comment by richard67** [comment]
@astridx Did you mean server on Linux, or did you mean also Browser on Linux?
