### ISSUE TITLE
[4.0] Undefined variable: icon 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#29903]
Since the merge of #28075 

The default icon for a template style gives the following error
`Notice: Undefined variable: icon in C:\htdocs\joomla-cms\libraries\src\HTML\Helpers\JGrid.php on line 144`

![image](https://user-images.githubusercontent.com/1296369/86364027-9119cb80-bc6f-11ea-9e31-b77bbb14bb2a.png)

**Comment by Quy** [comment]
PR #29933

**Comment by N6REJ** [comment]
@brianteeman thanks for catching this.
