### ISSUE TITLE
[4.0] joomla update issues [a11y]

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#29901]
![image](https://user-images.githubusercontent.com/1296369/86359110-80b22280-bc68-11ea-9d60-1f4938106636.png)

1. This is using a table for layout purposes - it is not tabular data.
2. The labels are not associated with the form elements
3. Other form elements have no label at all
3. Selecting either of the ftp methods should reveal extra fields - it doesn't

The same is true for the other views of the update component.

**Comment by hans2103** [comment]
@brianteeman created PR https://github.com/joomla/joomla-cms/pull/30168 to fix this issue.

**Comment by Quy** [comment]
@hans2103 Can you also do the form under `Live Update`? Thanks.

Go to Global Configuration > Joomla! Update
Select `Custom URL`, `Development`, and enter `https://update.joomla.org/core/nightlies/next_major_list.xml`
Go to System > Joomla Update 
Click `Live Update` tab

**Comment by hans2103** [comment]
> @hans2103 Can you also do the form under `Live Update`? Thanks.
> 
> Go to Global Configuration > Joomla! Update
> Select `Custom URL`, `Development`, and enter `https://update.joomla.org/core/nightlies/next_major_list.xml`
> Go to System > Joomla Update
> Click `Live Update` tab

Created new PR =>  https://github.com/joomla/joomla-cms/pull/30171

**Comment by alikon** [comment]
please test #30171 e #30168

**Comment by Quy** [comment]
@hans2103 Sorry last one. Thank you!

Install Beta 2.
Go to Global Configuration > Joomla! Update
Select `Custom URL`, enter `https://update.joomla.org/core/nightlies/next_major_list.xml`
Go to System > Joomla Update
Click `Live Update` tab

**Comment by hans2103** [comment]
@Quy 
> @hans2103 Sorry last one. Thank you!
> 
> Install Beta 2.
> Go to Global Configuration > Joomla! Update
> Select `Custom URL`, enter `https://update.joomla.org/core/nightlies/next_major_list.xml`
> Go to System > Joomla Update
> Click `Live Update` tab

isn't that the same as the previous request?
=> #30171

**Comment by Quy** [comment]
The previous one is to reinstall. This one is to update.

![29901](https://user-images.githubusercontent.com/368084/88432742-a5a23d00-cdb1-11ea-93da-2e3883533622.png)

**Comment by hans2103** [comment]
@Quy I've made the mistake to create two separate issues. 
I'll fix the last request when the other issues are merged. 
That will save me to fix the JS issue on this new request too.

**Comment by Quy** [comment]
Yes, there are 2 separate issues. One should be just the markup in your PRs and the other Javascript. Without your PRs when toggling between direct and FTP options, the FTP fields don't hide after display.
