### ISSUE TITLE
[4.0] batch copy/move module

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#29910]
The markup for this batch copy/move field in com_modules is completely wrong as there are labels for the wrong item and orphaned labels.

Looking at the similar field in com_content which is rendered correctly I can see that it is using a layout joomla.content.batch.item and someone better than me should probably check this out and move the field in com_modules to use a similar layout

**Comment by infograf768** [comment]
Not sure I understand. We can't move modules when using batch. That is the only issue I see with the UI as only copy works once a new position is selected.

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/86448411-a265e500-bd0e-11ea-8b45-ea6858da26fd.png)

![image](https://user-images.githubusercontent.com/1296369/86448490-ba3d6900-bd0e-11ea-86aa-e891c7ab5741.png)
