### ISSUE TITLE
Incorrect rounded border with multiple appended buttons

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#29934]
Both screenshots are with maximum zoom to make seeing this quite easy.

From a WIP UI change I'm making for a project showing the incorrect current state:

<img width="964" alt="Screen Shot 2020-07-03 at 10 41 18 AM" src="https://user-images.githubusercontent.com/368545/86483577-f7f3bf00-bd19-11ea-9b3e-eec996a35f85.png">

Example from the Bootstrap 2.3.2 documentation showing the desired result:

<img width="965" alt="Screen Shot 2020-07-03 at 10 41 31 AM" src="https://user-images.githubusercontent.com/368545/86483599-017d2700-bd1a-11ea-90df-b36382e625fc.png">

**Comment by brianteeman** [comment]
This is for joomla 3?

**Comment by mbabker** [comment]
Yes.  Sorry, didn't think about writing the version in since I specified the Bootstrap version.

**Comment by brianteeman** [comment]
I assumed that was the case but wanted to be 100% as we had the same problem in j4 but it was fixed

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed.

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
