### ISSUE TITLE
Web Authentication enabled in J4 by default

### ISSUE THREAD

**Issue by ManfredHuebner** [joomla/joomla-cms#29931]
### Steps to reproduce the issue

After standard installation, web authentication is enabled by default if a certificate and https connection is already installed

### Expected result

I expect a clean and easy login on my home page. Web authentication should be disabled by default because it cannot work out of the box

### Actual result

beside the login button, the web authentication button is also visible. It is more prominent (first button) but cannot work after installation as web authentication is not set-up

### System information (as much as possible)

J4 beta 2 on php 5.3 and Apache Linux server

### Additional comments

Usability issue that might confuse beginners

**Comment by zero-24** [comment]
Hmm maybe we go the same direction as we did with the 2fa plugins. They are disabled by default too but we had a postinstall message explaining the feature and allowed the users to opt into that feature. What is your opinion on that @wilsonge ?

**Comment by ManfredHuebner** [comment]
Would be a good idea :-)

**Comment by alikon** [comment]
Maybe a typo but j4 doesn't work on PHP 5.3 at least PHP 7.2.5

Il ven 3 lug 2020, 15:50 Manfred (sentix) <notifications@github.com> ha
scritto:

**Comment by ghost** [comment]
> maybe we go the same direction as we did with the 2fa plugins

agree

**Comment by Quy** [comment]
See #30905
