### ISSUE TITLE
[4.0] npm install failure

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#29937]
<img width="1440" alt="Screen Shot 2020-07-03 at 12 58 04 PM" src="https://user-images.githubusercontent.com/368545/86490586-858cda00-bd2d-11ea-9b10-9a3d983450c2.png">

4.0 @ cbaa9571e17968ad9e9659b86ff07e766c1bfbf4
Node v12.16.3
NPM 6.14.5

**Comment by brianteeman** [comment]
perhaps a silly question but are you sure that there is no packages.json in the media manager folder

**Comment by mbabker** [comment]
No package.json.

<img width="576" alt="Screen Shot 2020-07-03 at 1 18 08 PM" src="https://user-images.githubusercontent.com/368545/86491177-aa824c80-bd2f-11ea-9291-d7fbee3c4537.png">

**Comment by brianteeman** [comment]
I asked because it happened a few times to me when I was testing an old PR.

**Comment by brianteeman** [comment]
I was on slightly older versions than you with no problem.
I just update to  latest versions and no problem
node v14.5.0
npm  v6.14.5

windows not mac

**Comment by PhilETaylor** [comment]
On Mac (10.15.6 beta) with 
```
node v14.5.0
npm v6.14.5
```

I cannot replicate your issue - sorry. Only error I have looks like an upstream error. 


```
> fsevents@1.2.13 install /Users/phil/Sites/joomla-core/joomla-cms4/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:2884:
../../../../nan/nan_typedarray_contents.h:34:43: warning: 'GetContents' is deprecated: Use GetBackingStore. See http://crbug.com/v8/9908. [-Wdeprecated-declarations]
      data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                          ^
/Users/phil/Library/Caches/node-gyp/14.5.0/include/node/v8.h:5254:3: note: 'GetContents' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use GetBackingStore. See http://crbug.com/v8/9908.")
  ^
/Users/phil/Library/Caches/node-gyp/14.5.0/include/node/v8config.h:402:39: note: expanded from macro 'V8_DEPRECATE_SOON'
# define V8_DEPRECATE_SOON(message) [[deprecated(message)]]
                                      ^
1 warning generated.
  SOLINK_MODULE(target) Release/fse.node
```

**Comment by mbabker** [comment]
Nuking the `node_modules` folder from `administrator/components/com_media` seems to have fixed it.

**Comment by brianteeman** [comment]
doh - sorry - thats what it was - not the packages.json
