### ISSUE TITLE
[J4]Place the "Save" and "Fullscreen" buttons in the corners of the article editor TinyMCE.

### ISSUE THREAD

**Issue by korenevskiy** [joomla/joomla-cms#29949]
Please place the Save and Fullscreen buttons in the corners of the editor.
This is a very important change for accessibility by managing the editor of the article.
The Full screen button is not a text formatting button. It is strange that this button is located in the middle of the tools.
The Full screen button should be available immediately, without opening under the menu.
The Save button should also be available in full screen mode. This is the way towards all the authors of all the articles around the world. Everyone will be able to use these buttons.
The location of these buttons in the corners of the editor is accessible.
The Windows operating system has a START button in the lower-left corner of the screen, and the Close button of each window is located in the upper-right corner of the screen. This means that if any user (for example, a pensioner) has a bad mouse, a simple movement of the mouse along the diagonal of the screen will always get the user to the corner of the screen on the button. The SAVE button in MS Word or MS Excel is located in the upper-left corner. This is also a good sign of availability. Microsoft has accustomed users around the world to the location of buttons.
I suggest making our editor more accessible...

![img-2020-07-04-13-30-08](https://user-images.githubusercontent.com/6898474/86510839-2b0e7f00-bdfc-11ea-8922-36ba837f1924.png)
fullscreen mode
![img-2020-07-04-13-29-17](https://user-images.githubusercontent.com/6898474/86510842-2f3a9c80-bdfc-11ea-8eb5-b6ba6df97088.png)

**Comment by brianteeman** [comment]
Much of that is beyond our control as it is a 3rd party editor. 

One thing you can do is to use the plugin to edit which buttons are displayed and in what order.

**Comment by korenevskiy** [comment]
So we need to change the plugin (change the default values) to change the button layout.
The editor has a CMS Content button. Changes its content depending on the component, so the editor plugin can know exactly when to place the SAVE button.

I will write to the plugin developers.

**Comment by korenevskiy** [comment]
> Much of that is beyond our control as it is a 3rd party editor.

@brianteeman Please tell me how TinyMCE developers added their plugin to the Joomla repository?
How do I find out who exactly copied the plugin to the Joomla source?

**Comment by brianteeman** [comment]
It is not possible to put a toolbar icon on the menu bar with tinymce. Thats a limitation of tinymce not of joomla

This should be closed
