### ISSUE TITLE
[4.0] The word Purge in Toolbar buttons

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#29947]
### Steps to reproduce the issue

Go to Users -> User Actions Log
See the Purge button in the Tool bar. 
What does it do? Click to find out - having logged some actions.

### Expected result

Purge means get rid of some items, Purge the Cabinet, Purge the Politbureau.

### Actual result

It deletes all logged items.

### Additional comments

I see four instances of Purge in the strings translation files:
COM_ACTIONLOGS_TOOLBAR_PURGE="Purge"
COM_FINDER_INDEX_TOOLBAR_PURGE="Clear Index"
COM_INSTALLER_TOOLBAR_PURGE="Clear Cache"
JTOOLBAR_PURGE_CACHE="Clear Cache"
So it looks like COM_ACTIONLOGS_TOOLBAR_PURGE="Purge" should be COM_ACTIONLOGS_TOOLBAR_PURGE="Clear Log"

Sorry to be pedantic but you see these things when you write or revise documentation.

**Comment by infograf768** [comment]
Maybe plural: "Clear logs" ?

**Comment by alikon** [comment]
feel free to submit a pr with the correct english words..... that was my fault when in 3.9 the actionlogs was born...i'm notoriosuly an english dumb :stuck_out_tongue:

**Comment by adj9** [comment]
To me the button deletes all the actions of the Log. 
If I do not select any, does it delete all actions? There is a pop-up alert.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29947">issues.joomla.org/tracker/joomla-cms/29947</a>.</sub>

**Comment by PhilETaylor** [comment]
Purge is the correct word used in many different projects to clear out log files.

**Comment by brianteeman** [comment]
It's a very technical term and possibly hard to translate. As we don't use it elsewhere we should be consistent and not use it here either. Your proposal makes sense.

**Comment by chmst** [comment]
It is used in redirect: Purge Disabled. 
In german it is translated with "remove all" or "remove deactivated links".

**Comment by ceford** [comment]
In English Delete Disabled would be a better term because it says exactly what it is going to do, even more so than Clear Disabled. Clear Log or Clear Logs? The plural makes me wonder what other logs might be cleared. For me 'Purge' is the most ambiguous of the choices.

**Comment by brianteeman** [comment]
Delete is not correct in the context of joomla. In general in Joomla if you delete an item then it is in the trash and you can undelete it. Here purge means completely and permanently remove.

I am happy with your original suggestion of standardising on "clear"

AFAIK there is just one log that is removed. so it is singular as you originally suggested. 

It is a log of logs ;) isnt english wonderful

**Comment by Quy** [comment]
Please test PR #30174
