### ISSUE TITLE
[4.0] mod_multilangstatus running update query on every page load

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29948]
### Steps to reproduce the issue

Joomla 4 Admin console with debug = true
Load any admin url

### Expected result

Every SQL run has a reason, only run UPDATE statements if *really* needed - for performance

### Actual result

Every page load `MultilangstatusAdminHelper.php` runs three sql queries, 2 selects and then an update to set the `published` state of mod_multilangstatus regardless of its current state

<img width="1606" alt="Screenshot 2020-07-04 at 11 33 40" src="https://user-images.githubusercontent.com/400092/86510762-9d766380-bdea-11ea-8df9-f41478b0ce76.png">

**Comment by SharkyKZ** [comment]
Performance is hardly an issue here. But the whole concept makes no sense to me. `mod_user` keeps unpublishing my modules 🤷‍♂️ .

**Comment by SharkyKZ** [comment]
Let's scrape it. See PR https://github.com/joomla/joomla-cms/pull/30113.
