### ISSUE TITLE
[4.0] Feature icon position

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#29941]
I am sure we had this before and it was fixed but the star of the featured icon is not centered in the circle

![image](https://user-images.githubusercontent.com/1296369/86496482-8f3a3000-bd75-11ea-903c-6128690821d3.png)

**Comment by adj9** [comment]
I don't see it centered either.
Both with Safari 13.0.5 and chrome 83.0.4103.116 (Official Build) (64-bit)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29941">issues.joomla.org/tracker/joomla-cms/29941</a>.</sub>

**Comment by ghost** [comment]
Looks solved (Firefox 80, Safari 13.1; Mac):

![Screen Shot 2020-09-19 at 15 19 53](https://user-images.githubusercontent.com/70466955/93668322-fb325780-fa8b-11ea-8e0e-9189defa5b06.png)

**Comment by infograf768** [comment]
Older issue. Closing.
