### ISSUE TITLE
[4.0] Post Installation Message Count not cached

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29950]
### Steps to reproduce the issue

Joomla 4 admin console 
When you login and there are Post Installation Messages there is a number next to the icon in the header

### Expected result

Expect that number to be cached and not to generate additional sql queries on every single page load

### Actual result

On every single admin page load there are additional sql queries to check the post install message conditions. 

Example with "Two Factor Authentication is Available" message which calls `twofactorauth_postinstall_condition` function on every page load 

<img width="1605" alt="Screenshot 2020-07-04 at 11 44 35" src="https://user-images.githubusercontent.com/400092/86510870-bfbcb100-bdeb-11ea-91e0-dda846808cf4.png">

ok so `441μs` is not a lot - but this can multiply if there are a lot of conditions to check and is just another mysql query that is not needed to run on each and every page load.

**Comment by chmst** [comment]
Related to #29702<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29950">issues.joomla.org/tracker/joomla-cms/29950</a>.</sub>

**Comment by SharkyKZ** [comment]
Maybe messages could be disabled (hidden) in the database once their conditions are met?

**Comment by alikon** [comment]
please test #30409

**Comment by alikon** [comment]
i'll not close this issue for now..... i'll wait for some more feedback
cause i think more can be done/cached

**Comment by alikon** [comment]
please test #33344

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/pull/33344 doesn't fix this. 

It needs to be implemented as an ajax call like the other badges, so that it can be cached and can also only check periodically.  and not have to process all the post installation conditions on every page load ever. Thats simply just a waste.

**Comment by alikon** [comment]
sure

**Comment by PhilETaylor** [comment]
actually this and https://github.com/joomla/joomla-cms/issues/32995 are the same thing. reported almost a year apart - so maybe close this one after all and leave https://github.com/joomla/joomla-cms/issues/32995 open :)
