### ISSUE TITLE
[4.0] Color selector boxes too small

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29954]
### Steps to reproduce the issue

safari on Mac

Edit atum template style in Joomla admin 
Colour Settings tab

### Expected result

I think the color selector boxes should be full height of the input area - or maybe a bootstrap prepend area?

"Choose your hue value for the dark template colour" on one line
### Actual result

```
Choose your hue value for the 
dark template colour
```

<img width="1595" alt="Screenshot 2020-07-04 at 12 30 13" src="https://user-images.githubusercontent.com/400092/86511539-1e852900-bdf2-11ea-8358-2df2833f4d6b.png">

### System information (as much as possible)

safari on Mac

**Comment by Quy** [comment]
PR #30585
