### ISSUE TITLE
[4.0] Debug Queries shows preprepared query and no values

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29951]
### Steps to reproduce the issue

Joomla 4
Enable debug mode
Refresh any admin page
Go to queries tab

### Expected result

The queries shown contain all the values in order that they can be copy and pasted

Eg:
<img width="685" alt="Screenshot 2020-07-04 at 11 55 44" src="https://user-images.githubusercontent.com/400092/86511058-52118480-bded-11ea-91f5-82152a49a037.png">

### Actual result

The queries contain their pre-processed placeholders and not the actual values, making it impossible to debug as you dont know the values that were in the sql query 

<img width="1599" alt="Screenshot 2020-07-04 at 11 55 13" src="https://user-images.githubusercontent.com/400092/86511044-3dcd8780-bded-11ea-894e-83639732976e.png">

**Comment by PhilETaylor** [comment]
This also makes the `duplicate count` incorrect I think as its comparing queries with placeholders and not queries with values actually used

**Comment by Quy** [comment]
Duplicate #26135

**Comment by chmst** [comment]
See #26135, #28852<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29951">issues.joomla.org/tracker/joomla-cms/29951</a>.</sub>

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/issues/28852 is completely unrelated.

**Comment by MrTobyDog** [comment]
This still seems to be present in Joomla 4.0.3 and as the original poster stated makes it almost impossible to debug withou changing the code with lots of echo statements
Whilst the params button does show the parameters used it is s fair bit of work cutting and pasting if you want to replicate the statement for testing in phpMyAdmin

**Comment by chmst** [comment]
It is intended. This is why prepared statements increase the security of the system.

**Comment by MrTobyDog** [comment]
I understand that. But if I have debug on I can see the SQL statement with
placeholders. I can also see the parameters so with a bit of "cut and
paste" it is possible to recreate the statement and test it in phpMyAdmin.
This is often useful when debugging.

So my question really I guess is can we have the option to see the SQL
statement with the values filled in - I do not see how this will compromise
the system.
