### ISSUE TITLE
[4.0] Colour inputs jump around when trying to use them 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29955]
### Steps to reproduce the issue

Edit atum template style in Joomla admin
Colour Settings tab
Click all the inputs to make changes to the colours

### Expected result

it works - no re-flow/repainting of fields, fields not jumping around. 

### Actual result

![Screen Recording 2020-07-04 at 12 34 PM](https://user-images.githubusercontent.com/400092/86511640-fd710800-bdf2-11ea-85e1-71b6c8afc650.gif)

### System information (as much as possible)

Safari on Mac

<img width="324" alt="Screenshot 2020-07-04 at 12 37 05" src="https://user-images.githubusercontent.com/400092/86511655-137ec880-bdf3-11ea-90fb-a1300e636c01.png">

**Comment by ghost** [comment]
Issue confirmed.

**Comment by marcorensch** [comment]
Issue confirmed

**Comment by HLeithner** [comment]
Fixed in #31810 can be closed if merged

Edit: It seems minicolor has a problem with flex-grow 1 but I'm not sure

**Comment by brianteeman** [comment]
This was fixed elsewhere and can be closed

**Comment by PhilETaylor** [comment]
Confirmed "mitigated" by using a single column 

<img width="975" alt="Screenshot 2021-04-25 at 16 24 01" src="https://user-images.githubusercontent.com/400092/115999170-b1da5580-a5e2-11eb-99cf-90252e69302b.png">
