### ISSUE TITLE
[4.0] Cannot select new light background or link colour in atum template style

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29956]
### Steps to reproduce the issue

Edit atum template style in Joomla admin
Colour Settings tab
Click to change "light background" or "link colour"

### Expected result

Ability to drag around and select a new color

### Actual result

As soon as you click into the color palette the square closes 
Unable to select a color of choice

![Screen Recording 2020-07-04 at 12 39 PM](https://user-images.githubusercontent.com/400092/86511699-825c2180-bdf3-11ea-8efd-c6d607ecc6bc.gif)

### System information (as much as possible)

Safari on Mac 
<img width="324" alt="Screenshot 2020-07-04 at 12 37 05" src="https://user-images.githubusercontent.com/400092/86511687-635d8f80-bdf3-11ea-9eb3-2353dcac8216.png">

**Comment by PhilETaylor** [comment]
Interesting... the "box" is actually in midair in the next column

![Screen Recording 2020-07-04 at 12 53 PM](https://user-images.githubusercontent.com/400092/86511933-72454180-bdf5-11ea-824b-8398d06d79d2.gif)

**Comment by ghost** [comment]
Confirmed both issues on
![Screen Shot 2020-09-19 at 11 50 13](https://user-images.githubusercontent.com/70466955/93664356-81d83c00-fa6e-11ea-89ad-d336d6a779d5.png)

**Comment by brianteeman** [comment]
This was fixed elsewhere and can be closed

**Comment by PhilETaylor** [comment]
Probably by moving to a single column?

**Comment by PhilETaylor** [comment]
Confirmed "mitigated" by using a single column...

<img width="975" alt="Screenshot 2021-04-25 at 16 24 01" src="https://user-images.githubusercontent.com/400092/115999202-ce768d80-a5e2-11eb-98d2-8d519b0e2323.png">
