### ISSUE TITLE
[4.0] Templates: Styles (Administrator) menu color changes on save

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29958]
### Steps to reproduce the issue

Joomla 4 admin 
NOTE THE LEFT MENU COLORS
Navigate to System -> Administrator Template Styles -> atum (default)
Change NOTHING!!! 
Click SAVE AND CLOSE 
NOTE THE LEFT MENU COLORS

### Expected result

Nothing has changed

<img width="302" alt="Screenshot 2020-07-04 at 13 03 18" src="https://user-images.githubusercontent.com/400092/86512083-c3a20080-bdf6-11ea-9504-5e04f95f38c9.png">

### Actual result

New colour scheme

<img width="320" alt="Screenshot 2020-07-04 at 12 58 16" src="https://user-images.githubusercontent.com/400092/86512006-0fa07580-bdf6-11ea-8b9a-48c85a0415f6.png">

### System information (as much as possible)

safari on Mac

**Comment by adj9** [comment]
Starting from System, I don't understand why when you click Save & Close a different item is selected.
Anyway, I made a test and when I click on Save & Close the left menu is this one:
<img width="293" alt="Chrome" src="https://user-images.githubusercontent.com/5918444/86514103-e12f9400-be0f-11ea-81e5-ffb3fa53a0b4.png">

In this moment I move with the mouse, the color of the Toggle Menu item changes and becomes blue (its native color).

The trials are with:
- Safari 13.0.5 
- Chrome 83.0.4103.116 (Build ufficiale) (a 64 bit)

The two priors are no different.

**Comment by PhilETaylor** [comment]
Ignore which item is selected - the screenshots are generated to show the difference in colours only. 

So basically you were able to replicate the issue - thanks.

**Comment by adj9** [comment]
So, the color change wasn't defined ad hok? Is it a bug?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29958">issues.joomla.org/tracker/joomla-cms/29958</a>.</sub>

**Comment by PhilETaylor** [comment]
All I do is open the settings and click save - NOTHING should change. The fact that the colours change after saving is a bug - yes.

**Comment by brianteeman** [comment]
That means the values in the XML are different to those in the variables.scss

**Comment by brianteeman** [comment]
@angieradtke @coolcat-creations Could you look at this please as you have both changed these files. Basically the default value in the templateDetails.xml should match the value in the scss. I just don't know which is the intended colour of the two

**Comment by brianteeman** [comment]
Please test #30847
