### ISSUE TITLE
[4.0] Disabled Dropdown doesnt "look disabled"

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29953]
### Steps to reproduce the issue

Joomla 4.0-dev
Login to admin as super admin
Navigate Content -> Fields
Create a new text field - click save

Look at the Type dropdown with non-sleepy eyes. 

### Expected result

Visually looks disabled. 

### Actual result

Hovering over gives a hand pointer to further mislead you to believe you can click

Compare the disabled Type field dropdown with the enabled dropdown on the right, or the filter dropdown low-down, they look the same, and it takes a careful eye to note the change between disabled an enabled states. 

<img width="1583" alt="Screenshot 2020-07-04 at 12 19 36" src="https://user-images.githubusercontent.com/400092/86511397-a36f4300-bdf0-11ea-879f-e87086cdd49c.png">

note on (slower) page load you catch a glide of a fully greyed out input area, but on page render it reverts to a white background.

### System information (as much as possible)

safari on Mac

**Comment by Quy** [comment]
Partial fix #30187 for cursor.

**Comment by brianteeman** [comment]
Please test #31394
