### ISSUE TITLE
[4.0] TypeError: undefined is not an object batchSelector.addEventListener

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29952]
### Steps to reproduce the issue

Joomla 4.0-dev
Login to admin as super admin 
Navigate Content -> Fields
Create a new text field - click save and close
view JS console

### Expected result

No errors 

### Actual result

`TypeError: undefined is not an object (evaluating 'batchSelector.addEventListener')
onSelect — batch-language.js:43`

<img width="1606" alt="Screenshot 2020-07-04 at 12 16 20" src="https://user-images.githubusercontent.com/400092/86511356-2f349f80-bdf0-11ea-9db9-4124141aeda2.png">

### System information (as much as possible)

Safari on Mac

**Comment by Quy** [comment]
See PR #27938
