### ISSUE TITLE
[4.0] Templates: Styles (Administrator) default stars not aligned 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29957]
### Steps to reproduce the issue

Joomla 4.0-dev
(without #29933 you will get php notices with error reporting on) 
Navigate to System Administrator Tempalte Styles
Duplicate Atum a few times
Look at the default column 

### Expected result

All stars regardless of state should be aligned 

### Actual result
<img width="1295" alt="Screenshot 2020-07-04 at 12 46 05" src="https://user-images.githubusercontent.com/400092/86511849-d3b8e080-bdf4-11ea-83ff-a2eedd8b98c4.png">

same with Site

<img width="986" alt="Screenshot 2020-07-04 at 12 50 14" src="https://user-images.githubusercontent.com/400092/86511866-ef23eb80-bdf4-11ea-9853-4029dc3ad0e5.png">

### System information (as much as possible)

safari on Mac

<img width="324" alt="Screenshot 2020-07-04 at 12 37 05" src="https://user-images.githubusercontent.com/400092/86511850-d6b3d100-bdf4-11ea-8605-fd61cdc6ee52.png">

**Comment by adj9** [comment]
Even with Chrome (Version 83.0.4103.116 (Official Build) (64-bit)) there is non-alignment of the stars

**Comment by brianteeman** [comment]
Duplicate

**Comment by PhilETaylor** [comment]
Do you mean of your https://github.com/joomla/joomla-cms/issues/29941 16 hours ago?  - its not a duplicate of that at all.

**Comment by brianteeman** [comment]
Obviously not.

#29933

**Comment by PhilETaylor** [comment]
So now Im expected to not only search for open issues, open pull requests, but also trawl the deep nested comments of RTC issues unrelated to what Im reporting. FML!?

A comment in a RTC Pull request is not a duplicate of an issue. Its a comment that's prone to loss and not being addressed.

**Comment by infograf768** [comment]
Reopened after merging https://github.com/joomla/joomla-cms/pull/29933 to not forget to solve this different issue.

**Comment by infograf768** [comment]
My possible solution is
https://github.com/joomla/joomla-cms/pull/29933#issuecomment-653731073

**Comment by N6REJ** [comment]
why don't the ^= & *= match?
![image](https://user-images.githubusercontent.com/1850089/86531608-622a7200-be88-11ea-8ae7-613a05338826.png)
I would think fa- and icon- would both use the same ^ or *

**Comment by Quy** [comment]
Please test PR #29983
