### ISSUE TITLE
[4.0] Replace Generic error message with a shiny one.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29968]
### Steps to reproduce the issue

install Joomla 4 
once installed turn off the mysql server (or make a new typo in the mysql credentials in /configuration.php)

### Expected result

In Joomla 3 we just got white screen of death with "Error" on it. 

In Joomla 4 we have the opportunity to make the generic error page beautiful - or at least allow the text to be translated/edited by Super Admins 

### Actual result

The default Symfony error page is displayed

<img width="645" alt="Screenshot 2020-07-04 at 15 48 03" src="https://user-images.githubusercontent.com/400092/86514984-d5db6900-be0d-11ea-8348-d606cf0a4e62.png">

**Comment by PhilETaylor** [comment]
Ok looks like its not possible to overwrite the default Symfony error page just yet as its hard coded into the symfony/error-handler, I'll work on that upstream first so that its possible in the future. 

https://github.com/symfony/error-handler/blob/9a033aedc45ba7dcca9e3ae49670a6ca73fddc7b/ErrorRenderer/HtmlErrorRenderer.php#L137

**Comment by PhilETaylor** [comment]
Upstream Submitted. https://github.com/symfony/symfony/pull/37492

**Comment by PhilETaylor** [comment]
Upstream PR Approved and awaiting merging....

**Comment by PhilETaylor** [comment]
This has now been merged upstream for inclusion in Symfony 5.2 - this means Joomla can now have a customisable, translatable error page 🎉🎉

**Comment by ReLater** [comment]
The question for me is "How?". Or will you provide a pr then?

**Comment by PhilETaylor** [comment]
Well between now and November we need to add one single line to joomla (as per my example in the readme of the upstream pr) next to the line enabling the symfony error handler and point that to a custom system template that contains very little logic in it (based on views/error.twig.html), and some way of translating it without assuming anything is loaded - as this template is only ever used when something drastic is wrong and therefore cannot assume anything is booted.

It would be nice if this could also be customised without losing changes on joomla upgrade - maybe check for a custom version first and fall back to joomla provided version of the template? 

For look and fee I was thinking to just copy the template used when you checkout from git without building your assets and just make it more red than blue. 

We could ship joomla 4 with the dev-master release of symfony/error-handler to get this feature now or else we would need to wait for symfony 5.2 to be released in November

**Comment by PhilETaylor** [comment]
PR https://github.com/joomla/joomla-cms/pull/30056
